### ISSUE TITLE
Graph rendering issues after Upgrade to Grafana 8.5.9

### ISSUE THREAD

**Issue by TimoL** [grafana/grafana#52931]
**What happened**:

Grafana update from 8.3.x to 8.5.9, we started to see problems with our Graph panels.

sometimes rendering issues with Graph panels:
![broken-rendering](https://user-images.githubusercontent.com/1062826/181486112-333094b2-c95a-4073-b2ee-e7bd9ed31bbb.png)

and sometimes missing data:
![missing-data](https://user-images.githubusercontent.com/1062826/181486199-afd9c62c-d456-4fd2-8d8e-6f0b7b2dabce.png)

**What you expected to happen**:

Graph look the same way as before.

**How to reproduce it (as minimally and precisely as possible)**:

 Sorry, no real details on our end. Graph panel with simple (and pretty fast) Prometheus query worked in Grafana 8.3.x, but fails about 50% of the time with Grafana 8.5.9.

Reloading the dashboard randomly end up in one of those options:
* 50% works as expected
* 40% arbitrary parts of data are missing (other parts after each reload)
* 10% graph is broken

**Anything else we need to know?**:

I just want to check with you, if there is a known problem, since our data source (Prometheus) seems to be reliable.

**Environment**:
- Grafana version: 8.5.9
- Data source type & version: Prometheus
- OS Grafana is installed on: using official Grafana docker image, running in K8S
- User OS & Browser: OSX, Safari, Chrome
- Grafana plugins: not considered relevant
- Others:

**Comment by ashharrison90** [comment]
hi @TimoL 👋 

i don't think this is a known problem, although the graph panel has been deprecated for some time now. does migrating to the newer timeseries panel solve your problems? it has significantly better performance, and in many cases it's simply a case of clicking the `migrate` button:
![image](https://user-images.githubusercontent.com/20999846/181488186-dac32515-dfd0-4862-8058-7d52fe7bfe8c.png)

**Comment by TimoL** [comment]
Hi @ashharrison90 ,

unfortunately we see the exact same behaviour with the newer time series panels.
(We currently have that dashboard duplicated for testing, one is using Graph panels, the other is using Time Series panels).

Here's an example using time series panels:
![time-series-panel](https://user-images.githubusercontent.com/1062826/181489216-663934db-7e98-492e-a849-95c222c53ac3.png)

**Comment by TimoL** [comment]
I would like to add that using the query inspector "Refresh" button the results are 100% stable. query times hover around 100-100ms.
![query-inspector](https://user-images.githubusercontent.com/1062826/181490575-8001215b-e714-43ad-936e-4223d2191334.png)
.

**Comment by ashharrison90** [comment]
@TimoL so just to check... when loading the dashboard for the first time you intermittently see these issues. reloading the whole dashboard also intermittently shows the issues. but if you inspect each panel query and refresh the individual query it always works? 🤔

**Comment by TimoL** [comment]
@ashharrison90 you're correct, when editing the panel it 100% works. I tested by hitting thre "Refresh" button approx 30 times:
![edit-view](https://user-images.githubusercontent.com/1062826/181493391-4d424461-8f64-43a5-b918-0204df51d249.png)

It is only broken when showing the dashboard with the panel.

**Comment by ashharrison90** [comment]
that's... _really_ weird 😕 sounds like queries are interfering with each other somehow, but i've never seen or heard of that happening

few more questions to see if we can tease out anything:
- can you be more specific about exactly what queries you're running (don't have to include anything sensitive, but just the general format)
- can you share query results from the network tab (again redacting anything sensitive) for a single (broken) query that's executed on the whole dashboard vs. a single query in panel edit?

**Comment by TimoL** [comment]
The query we're using is not really sensitive, so I can simply share that part: `sum(max(zuul_nodepool_current_requests) by (pipeline,tenant))`.

dev-tools: graphs rendered correctly
![working](https://user-images.githubusercontent.com/1062826/181497568-e0401a77-7275-48ed-8e5d-4ae73d71e9e2.png)

dev-tools: graphs are missing data
![missing-data](https://user-images.githubusercontent.com/1062826/181497661-755b2005-897a-49ec-8c9e-e88a80657a8c.png)

looks pretty much identical.

**Comment by roastiek** [comment]
I'm experiencing same behaviour after upgrading from 8.5.4 to 9.0.2 and now running on 9.0.4. Using prometheus data source, too.

**Comment by torkelo** [comment]
Looks like the data is not sorted properly by time?

**Comment by roastiek** [comment]
In my case its probably a thanos bug https://github.com/thanos-io/thanos/issues/5501

I tried all versions between 8.5.9 and 8.5.4 and still the same. Then I have downgraded thanos back to 0.26.0 from 0.27.0 and the issue is gone even when I have returned back to grafana 9.0.4.

**Comment by TimoL** [comment]
I can confirm, that the Thanos downgrade 0.27 -> 0.26 fixed all rendering issues. I assume we can close this issues as "not a Grafana bug".

**Comment by ashharrison90** [comment]
@TimoL @roastiek that's great 

i would also guess Grafana can probably work around this bug by using the `Sort by` transform if you really need to be on the latest Thanos version 👍
