### ISSUE TITLE
Panel with Datasource "-- Dashboard --" in repeated row is hard linked to first row data

### ISSUE THREAD

**Issue by MelK-HH** [grafana/grafana#52930]
**Setup**: I have a dashboard with 2 Graph Panels in a row. The row will be repeated for my variable $volume. The second panel in the row has a datasource "-- Dashboard --" using results from first panel.

**What happened**: In all rows the second panel is displaying the data from the first panel in row 1. The first panel in each row shows correct data. When filtering the dashboard to show only one row the second panel always shows the correct data.

**What you expected to happen**: When having multiple rows the second panel should always display the data of the first panel of the same row.

**How to reproduce it (as minimally and precisely as possible)**: 

- Create a new dashboard with variable $row with values 1, 2, and 3 and "Multi-value" and "All" Options
- Create a row repeated by $row
- Create a panel "Panel1" in the row with with a PostgreSQL  as database with query  "SELECT  $__time(current_timestamp  - interval '10m'), $row::int as row", Display as "Bars"
- Create a second panel in the same row with Datasource = "-- Dashboard --" and Panel1 as result-source.
- Both panels with display the same data
- When selecting "All" for parameter "row" then the Panel1 will show a different value for each row but Panel2 will display value "1" for all three rows.

_Panel with "all" Rows_:
![grafik](https://user-images.githubusercontent.com/63095974/181485851-b5d7d244-0539-4b29-8a0f-daa2539f5d9d.png)

_Panel with only Row 2_:
![grafik](https://user-images.githubusercontent.com/63095974/181486159-309e0ee0-bbf7-4b84-90c6-4b0817f5f8f5.png)

_Source Code_:
[Panel_json.txt](https://github.com/grafana/grafana/files/9208325/Panel_json.txt)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v.7.5.11
- Data source type & version: PostgreSQL
- OS Grafana is installed on: docker container

- User OS & Browser: Windows 11/ Firefox 103.0
- Grafana plugins: Only Core Plugins
- Others:

**Comment by zuchka** [comment]
> Grafana version: v.7.5.11

Grafana 7 is no longer receiving support. Can you please upgrade to Grafana 9 and try reproducing this?

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by zuchka** [comment]
> Grafana version: v.7.5.11

Grafana 7 is no longer receiving support. Can you please upgrade to Grafana 9 and try reproducing this?

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by MelK-HH** [comment]
Hi zuchka, I would like to reproduce this behaviour in the public sandbox but I am not able to create a new dashboard there.
In the next 2 weeks I am off on vacation and will not be able to reply to comments.

**Comment by The1hauntedX** [comment]
I just found myself in this exact situation. I have a multi-select/All variable named `products`, and a repeating panel that queries a New Relic data source and repeats for each `product`.  
I want to create another repeating panel (repeating on the same variable), that uses the `-- Dashboard --` data source to use the same queries/data that the first repeating panel uses.

![image](https://github.com/grafana/grafana/assets/13578289/0d3de07d-5a2c-4847-98ac-6c48c487bb40)

As you can see, the `-- Dashboard --` data source panels all share the same data as the first base panel titled `IE`.

Here is the JSON model for folks to "play" with it themselves ;)  
<details>
  <summary>Show Code</summary>
  
  ```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 25,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 16,
      "panels": [],
      "title": "Base repeating panels",
      "type": "row"
    },
    {
      "aliasColors": {
        "logins.count.mean": "#7EB26D"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": {
        "type": "graphite",
        "uid": "000000001"
      },
      "editable": true,
      "error": false,
      "fill": 1,
      "fillGradient": 0,
      "grid": {},
      "gridPos": {
        "h": 6,
        "w": 6,
        "x": 0,
        "y": 1
      },
      "hiddenSeries": false,
      "id": 1,
      "legend": {
        "alignAsTable": false,
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "rightSide": false,
        "show": false,
        "sort": "avg",
        "sortDesc": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 2,
      "links": [],
      "maxPerRow": 4,
      "nullPointMode": "connected",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "10.0.1-cloud.3.f250259e",
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "repeat": "server",
      "seriesOverrides": [
        {
          "alias": "logins.count.mean"
        }
      ],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "datasource": {
            "type": "graphite",
            "uid": "000000001"
          },
          "refId": "A",
          "target": "aliasByNode(apps.*.$server.counters.requests.count, 2)",
          "textEditor": true
        }
      ],
      "thresholds": [],
      "timeRegions": [],
      "title": "$server",
      "tooltip": {
        "msResolution": true,
        "shared": true,
        "sort": 0,
        "value_type": "cumulative"
      },
      "type": "graph",
      "xaxis": {
        "mode": "time",
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "$$hashKey": "object:69",
          "format": "short",
          "logBase": 1,
          "show": true
        },
        {
          "$$hashKey": "object:70",
          "format": "short",
          "logBase": 1,
          "show": true
        }
      ],
      "yaxis": {
        "align": false
      }
    },
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 7
      },
      "id": 23,
      "panels": [],
      "title": "-- Dashboard -- data source repeating panels",
      "type": "row"
    },
    {
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "description": "this is a description",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [
            {
              "options": {
                "match": "null",
                "result": {
                  "text": "N/A"
                }
              },
              "type": "special"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "rgba(35, 118, 31, 0.97)",
                "value": null
              },
              {
                "color": "rgba(237, 129, 40, 0.89)",
                "value": 280
              },
              {
                "color": "rgba(245, 54, 54, 0.9)",
                "value": 300
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 6,
        "x": 0,
        "y": 8
      },
      "id": 9,
      "links": [],
      "maxDataPoints": 100,
      "options": {
        "colorMode": "background",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "mean"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "10.0.1-cloud.3.f250259e",
      "repeat": "server",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 1,
          "refId": "A"
        }
      ],
      "title": "$server",
      "type": "stat"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allFormat": "glob",
        "current": {
          "selected": true,
          "text": [
            "IE",
            "SE",
            "US",
            "ZA"
          ],
          "value": [
            "IE",
            "SE",
            "US",
            "ZA"
          ]
        },
        "datasource": {
          "type": "graphite",
          "uid": "000000001"
        },
        "definition": "",
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "multiFormat": "glob",
        "name": "server",
        "options": [],
        "query": "apps.*.*",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-15m",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "Templating, repeated panels",
  "uid": "000000025",
  "version": 9,
  "weekStart": ""
}
  ```
</details>

**Comment by dprokop** [comment]
@MelK-HH thanks for opening this issue. The -- Dashboard -- data source is not supported in panel repeats. Under the hood, it's a reference to a given panel ID that's supposed to be the source of data, and the repeated panel using -- Dashboard -- data source is not aware of the repeat context.

We do not rule out supporting this in the future, but we do not have any immediate plans on implementing this.
