### ISSUE TITLE
[Feature request] Graph panel: color based on value/thresholds

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#5293]
### Idea

It would be nice to colorize lines/bars or dots in graphs per value.
Maybe, it's easiest to add this to the current thresholds configuration
### Examples

Variable: Ping packet loss measurement
##### Colorize graphs
- Points should be green is they're below 3%
- Points should be red is they're 15% or higher
- Points should be orange, otherwise.
##### SLA display
- Make full height bars with a color depending on the variable (i.e. horizontal: time, vertial: constant, color=variable)
- Red if >=10%, green if <10%

**Comment by p0nts** [comment]
I want to vote for this feature as well!

**Comment by roidelapluie** [comment]
That would be excellent.

We achive this by running multiple queries but it is expensive:

![exp1](https://user-images.githubusercontent.com/291750/35430703-bc64eb56-0279-11e8-9c26-fd24cc1f9b18.png)
![exp2](https://user-images.githubusercontent.com/291750/35430767-fc155ed4-0279-11e8-8aa9-1fd10192476d.png)
![exp3](https://user-images.githubusercontent.com/291750/35430774-09d86124-027a-11e8-812a-82fd9edf35aa.png)

**Comment by nickwilliams-eventbrite** [comment]
Bummer. I was searching, hoping to find instructions on how to do this, and instead found a feature request. 🙁 Any update from Grafana on when this might make it in?

**Comment by ryantxu** [comment]
I can see how to support his in the new react panels -- once we have it working there we can see if it is reasonable to get working in the existing flot graph

**Comment by ablecable** [comment]
any update on this?

**Comment by wz2b** [comment]
I'm interested in this, too ... a line on a graph that changes color based on the value.

**Comment by dal00** [comment]
A graph that can show two values. X/Y + color is something I would like.
Maybe like query A draws a graph over time. Then query B colors the line of the graph with some other data. maybe even makes it thicker or thinner based on the data.

**Comment by lealceldeiro** [comment]
> I can see how to support his in the new react panels -- once we have it working there we can see if it is reasonable to get working in the existing flot graph

Any updates on 2021?

**Comment by bwentzel** [comment]
This would be quite useful!

**Comment by gsperry2011** [comment]
Not sure this will help but I also came across this searching how to do it and found this feature request instead.

Example use case:

With metrics that look like:
```
vmware_host_connection_state{cluster_name="cls1",dc_name="dctr1",host_name="host1.fqdn.com",state="notResponding",tags="n/a"} 1.0
vmware_host_connection_state{cluster_name="cls1",dc_name="dctr1",host_name="host2.fqdn.com",state="Connected",tags="n/a"} 1.0
```

I want to color based on the value of the `state` label. The metric always returns 1 regardless of connection state.

Currently this leaves me with this:
![image](https://user-images.githubusercontent.com/21208713/117988895-d421e200-b309-11eb-89e4-04182b49109a.png)

When I'd rather have something like this:
![image](https://user-images.githubusercontent.com/21208713/117988937-e1d76780-b309-11eb-853a-4b493e984408.png)
and
![image](https://user-images.githubusercontent.com/21208713/117988972-ea2fa280-b309-11eb-99f8-72e5e789c6ad.png)

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/35910
