### ISSUE TITLE
Canvas: Selected element background/border connected to the Layer background/border

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#52951]
https://user-images.githubusercontent.com/88068998/181576039-3ca51978-48b9-40e0-98e4-6306f674056c.mov

Actions made in Selected element background/border sections seem to trigger a scroll to Layer's background/border section.

**Comment by nmarrs** [comment]
Does this also occur with the inline editor as well?

**Comment by adela-almasan** [comment]
Just tested it and yes, inline editor seems to have the same behavior..
