### ISSUE TITLE
Checkmark flips backwards when unselected

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#5296]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 6.7
- What did you do? uncheck option box
- What was the expected result? box to be unchecked 
- What happenend instead? check mark flips backwards instead

It seem that the top row of all the check box options, when unselected flips backwards instead of unchecking.  The effect is the same, but is a little misleading if you just glance at settings it looks like it's on.

Pictures as an example:

First two rows checked:
![screen shot 2016-06-06 at 4 44 29 pm](https://cloud.githubusercontent.com/assets/1132262/15840273/0e8e0684-2c06-11e6-9426-cba41381c373.png)

First two rows unchecked (and backwards):
![screen shot 2016-06-06 at 4 44 48 pm](https://cloud.githubusercontent.com/assets/1132262/15840293/1b4fe586-2c06-11e6-8c99-27618d99117a.png)

**Comment by torkelo** [comment]
what browser and browser version?

**Comment by calebcall** [comment]
Ah, didn't even think to check different browsers.  This is in Safari 9.1.1 (11601.6.17).  Just checked in Chrome and this same behavior doesn't exist.

**Comment by bigkraig** [comment]
+1 see it in Safari 9.1.2, has been a source of quite a bit of confusion :)

**Comment by danievanzyl** [comment]
Also seeing it in Safari Version 9.1.2 (11601.7.1) OSX 10.11.6 (Beta). Chrome works just fine.

**Comment by tjschuck** [comment]
Also seeing it in Safari Version 9.1.1 (11601.6.17) on OS X 10.11.5 (15F34).

[Here's a video](https://monosnap.com/file/8rhsHsupDXbwRmsAiH28aR0tJJnZVZ) that shows some of the weirdness a little better than the static images.

**Comment by torkelo** [comment]
seems to be fixed in Safari 10
