### ISSUE TITLE
Canvas: Unable to clear background image

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#53008]
When setting a background image for an element user is unable to clear it once set (via "x" button to clear selection).

Only way to clear the background image is to clear the background image (via the "x" button) and then save and refresh the page

https://user-images.githubusercontent.com/22381771/181826732-90e4a753-5354-4bbd-9f9a-16220bf7269b.mov

**Comment by adela-almasan** [comment]
Fixed in https://github.com/grafana/grafana/pull/52958
