### ISSUE TITLE
[Bug] Templating with InfluxDB generates wrong query

### ISSUE THREAD

**Issue by Buzut** [grafana/grafana#5300]
Hi!
I'm not sure which version I'm using (how is it possible to know actually?)
I installed it yesterday via packagecloud.io on Ubuntu 16.04:

    curl https://packagecloud.io/gpg.key | sudo apt-key add -
    echo "deb https://packagecloud.io/grafana/stable/debian/ wheezy main" | tee /etc/apt/sources.list.d/influxdb.list
    apt-get install grafana

I built a request to check for one server, it works great:
`SELECT value FROM "cpu_load" WHERE host='bm1' AND $timeFilter`

Now, I define a template to be able to query other hosts, this is how it looks like:
![capture d ecran 2016-06-07 a 11 46 58](https://cloud.githubusercontent.com/assets/6450536/15853505/9781a3d4-2ca5-11e6-95b5-3339c9e2405e.png)

I then update my query like:
`SELECT value FROM "cpu_load" WHERE host='$host' AND $timeFilter`

This generates the following query:
`SELECT value FROM "cpu_load" WHERE host='(bm1|mn1|monit)' AND time > 1465246598s and time < 1465291436s`

It returns nothing… It seems to me that a valid query would rather be:
`SELECT value FROM "cpu_load" WHERE (host='bm1' OR host='mn1' OR host='monit') AND time > 1465246598s and time < 1465291436s`

**Comment by torkelo** [comment]
please use the query editor in grafana metrics tab, if you use that Grafana will use the right template value encoding depending on if you use regex operator or (like in your case regular equality operator), 

If you use raw query then all template variables are regex escaped to support multi value filtering, so you need to switch to regex operator host =~ /^$host/

**Comment by Buzut** [comment]
It works as you said indeed. Just have to know it!
