### ISSUE TITLE
Add event tracking for dashboard creation

### ISSUE THREAD

**Issue by zsofiakomaromigrafana** [grafana/grafana#53005]
We would like to understand what % of new Cloud users end up creating a dashboard. We'll use this as a baseline when optimizing the flow of connecting data and then setting up a dashboard (working with the Self-Serve onboarding team).

**Given**: A user is editing a new (previously unsaved) dashboard
**When**: They save the dashboard
**Then**: A tracking event to RudderStack is emitted with the following attributes:

Proposed event name: grafana_dashboard_created

Event properties: Default event properties only. We can add more properties that we would like to analyze in a following iteration.

**Comment by ivanortegaalba** [comment]
@zsofiakomaromigrafana one question: Could we also track when the creation is triggered but it fails? This could give us data about the user experimenting failures while trying to create the dashboard, helping us to discard the users that don't arrive at the final of the funnel for system errors. WDYT?
