### ISSUE TITLE
Hard set the lost e-mail domain

### ISSUE THREAD

**Issue by vfxGer** [grafana/grafana#5301]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4
- What OS are you running grafana on?
Using the official docker image

docker run  --restart=always --name mygrafana -d -p 80:3000  --link mygraphite -e GF_SMTP_ENABLED=true -e GF_SERVER_DOMAIN=internal.secretexamplecompany.com -e GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP=true  -v /var/lib/grafana:/var/lib/grafana grafana/grafana:3.0.4

I'm having problems setting GF_SERVER_HTTP_PORT=80 but the configuration works fine for me except the lost password e-mail and other e-mails point to port 3000, could I put the domain for e-mails in the config?

**Comment by torkelo** [comment]
set GF_SERVER_ROOT_URL=http://your_grafana_address

GF_SERVER_ROOT_URL should be the root url you use to access grafana in browser, it will be used to generate links in emails
