### ISSUE TITLE
Start date for Monthly line chart

### ISSUE THREAD

**Issue by kapilkathuria** [grafana/grafana#53025]
**What happened**:
Start of the month is shown as some Random date rather than 1st of month in Time Series chart.

**What you expected to happen**:
Start of the month should be 1st of month

**How to reproduce it (as minimally and precisely as possible)**:
Create a in Time Series chart for data grouped over Months from MySQL DB
```
SELECT
  $__timeGroupAlias(time,1M),
  count(number) AS "number"
FROM incident
WHERE
  $__timeFilter(time)
GROUP BY 1
ORDER BY $__timeGroup(time,1M)
```

**Anything else we need to know?**:
Pls see snap-shot attached in community post:
https://community.grafana.com/t/start-date-for-monthly-line-chart/69456

**Environment**:
- Grafana version: v8.5.4
- Data source type & version: MySQL, '8.0.26'
- OS Grafana is installed on:
- User OS & Browser: Windows 10, Edge
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @kapilkathuria ,

I am closing this issue as it seems more of a general question which you had already opened.
