### ISSUE TITLE
Unable to select all points on Time Series panel

### ISSUE THREAD

**Issue by apellew** [grafana/grafana#53034]
**What happened**:
I was unable to select a point in the Time Series panel (despite it being in the centre of the crosshairs)
![Screen Recording 2022-08-01 at 12 45 01](https://user-images.githubusercontent.com/61825444/182141933-f9e23a1a-26e8-496c-9dde-995b6ffd7c97.gif)

**What you expected to happen**:
The point should be selected (yellow halo).

**How to reproduce it (as minimally and precisely as possible)**:
There are approximately 2,160 points plotted on the panel (90-days at one reading per hour). 1,440 points (60 days) doesn't appear to have the same issue but it's likely this is due to the points not being so close together.

This SQL (postgres) will generate a series with outliers approx. 20% of the time that are sufficiently apart to test selection using the y-axis rather than just x;
```
SELECT 
  a.a AS time,
  CASE WHEN RANDOM()<0.2 THEN 20 ELSE 0 END as value
FROM generate_series($__unixEpochFrom(), $__unixEpochTo()) a
```

The point selection algorithm seems to be relying on proximity of the mouse cursor using the horizontal line only rather than using the vertical line. Using both Axis would make the selection of outliers possible near a cluster of data. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v9.0.2 (0641b5d0cd)
- Data source type & version: Postgres
- OS Grafana is installed on: Docker/ Google Hosted
- User OS & Browser: Edge on MacOS.
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
in you screenshot it looks like the `add annotation` popup is present. Perhaps that is interfering with the tooltip behavior?

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by leeoniya** [comment]
> The point selection algorithm seems to be relying on proximity of the mouse cursor using the horizontal line only rather than using the vertical line.

that's correct.

i'll see what kind of perf impact there would be to doing additional proximity testing on every mousrmove event * multiple series * dozens of neighboring datapoints * multiple panels (when shared dashboard cursor is enabled).

the relevant code is here

https://github.com/grafana/grafana/blob/8ee0555bac10fea6b3cdf8d4d887c22c6cedf619/packages/grafana-ui/src/components/TimeSeries/utils.ts#L491

**Comment by apellew** [comment]
@zuchka I don't seem able to duplicate the issue on play.grafana.com but I suspect this is because points are being aggregated in some way I can't see. 

https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&from=now-1y&to=now&editPanel=1

I'm trying to adjust this panel but when I fully zoom in I get points every 10 minutes but when I view a year's worth of data I only get selectable points every hour (or this could be the issue if it is displaying everything!). The data is also so close it's difficult to target outliers as in the example above.

I note that the version on the sandbox is also `8.0.0-beta1` (whereas I'm using `7.5.6`).

**Comment by leeoniya** [comment]
certainly, it's not going to be possible to precisely target a specific point if you have 10x more datapoints than you have available screen pixels and all your spike happens to contain 5 datapoints with similar y values all within a single pixel. your recording does not appear to be this extreme so we can look into possibly improving this, but if you're not somehow aggregating or limiting your data, this situation can always arise with specific & dense datasets.

**Comment by apellew** [comment]
You are correct, but the intention is to spot outliers and obtain details on them. As you can see from the gif we have an outlier with no points near it that is impossible to select.

The recording we are using are measurements from the operation of a machine (i.e. vrms) and because of the need to spot and investigate outliers we can't do any aggregation (the investigation is viewing a detailed spectrum for the outlier which is generated and displayed on a separate dashboard).

**Comment by leeoniya** [comment]
> As you can see from the gif we have an outlier with no points near it that is impossible to select.

it becomes possible if you zoom in on that region, correct?
