### ISSUE TITLE
Missing escape characters when using templated variables

### ISSUE THREAD

**Issue by mgresser** [grafana/grafana#5304]
- [ x] Bug report

Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? InfluxDB 0.13
- What OS are you running grafana on? CentOS 7
- What did you do? Used a template variable in a field name
- What was the expected result? Variable would be passed to Influxdb with the value replaced
- What happenend instead? Variable was surrounded by $ at beginning and end. Trailing $ is passed to influx in the query. As such the only way I can find to use a template variable in a field name is to make the value the last string in the field name. Otherwise the extra $ gets injected into the field name.

Works as expected:
SELECT (sum("FieldName_$Variable") FROM "measurement" WHERE GROUP BY time($interval) fill(null)

Does not work:
SELECT (sum("$Variable$_FieldName") FROM "measurement" WHERE GROUP BY time($interval) fill(null)

I haven't been able to find a way to escape the second $ in the second statement.

Also I've noticed that when using template variables with "/" in them, for instance when templating mount points, they are also improperly escaped. This was not an issue in the 2.9.x releases.

**Comment by torkelo** [comment]
template string evaluation works with two syntaxes, either `$varname`  where varname cannot contain non word characters (like punctuation, space etc. The other syntax is `[[varname]]`

Try this:
SELECT (sum("$Variable$_FieldName") FROM "measurement" WHERE GROUP BY time($interval) fill(null)
