### ISSUE TITLE
Alerting: Add "stat" mode to Alert list panel

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#53043]
Add the concept of "view modes" to the alert list panel and add a stat mode. The stat mode shows the number of alerts matching the filters as a number (could use the BigValue component), the use case for this being if you have a dashboard and you want to basic metrics at the top. 

Another use for "view modes" is mentioned in [#50694](https://github.com/grafana/grafana/issues/50694) where there could be an option to view only alerts or rules.

**Comment by jtheory** [comment]
**User view & value**
Persona: SRE or dev wants to confirm that:
* all alerts (or all alerts matching a filter) are active (properly configured)
* and in the state they expect -- probably "not firing"; but maybe muted, firing, etc.

Maybe 1+ urgent alerts are already firing, and they want a rapid summary of states in that category.

Current workflow:
* They have to open the Alerting view, or look at the full list of alerts on a panel (...is this right? TODO)

Workflows:
* Open dashboard + panel, check status summary: any odd alert states?
* Apply filter, check status summary; any odd alert states?
* Respond: can they drill down to a set of alerts, or... what do they do from here?
