### ISSUE TITLE
CloudWatch: Variable editor and Metrics query builder should display custom values

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#53049]
When I implemented https://github.com/grafana/grafana/pull/52955, I forgot that custom variables need to be added to the options for the field in order to show up when the variable is edited.

The metrics stats editor has the same bug, where a custom value will not be displayed when the query is edited.

**Comment by sarahzinger** [comment]
hi @iwysiu can you share a screenshot or something for this issue? Its not super clear to me what options and what field we're talking about

**Comment by iwysiu** [comment]
Currently fighting with my local copy of the repo and I can't run it, so no screenshot, but I was talking about the "Namespace", "Metric", and "Dimension Key" fields in the variable editor. With the caveat that I can't currently check if its true or not, if it is, you can reproduce it by setting one of those fields for a Dimension Values query, saving it and returning to the main dashboard, and then re-opening the variable in the variable editor. If the bug still exists, the field will appear blank despite having a value.

**Comment by iwysiu** [comment]
Went back and got an example:
Despite being saved as `foo`, when we open the variable editor the metrics field does not display the custom value
![Screenshot 2024-02-12 at 4 11 23 PM](https://github.com/grafana/grafana/assets/5421859/a00b8917-c06d-4bc6-b931-1e5ded2ac186)

Note that it is saved on the dashboard json
![Screenshot 2024-02-12 at 4 12 08 PM](https://github.com/grafana/grafana/assets/5421859/c81ea011-2479-47ef-ba99-8332f300a3d2)

**Comment by katebrenner** [comment]
bug exists, but not a huge issue. not prioritizing right now
