### ISSUE TITLE
Devenv: Build Loki devenv dashboard

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#53046]
**Level: medium**

Currently, we don't have any test/sample dashboard for `gdev-loki` data source. We should create a `gdev-dashboard` for loki, similarly as we have for elasticsearch and other data sources - see `devenv/dev-dashboards/datasource-elasticsearch`).

The dashboard could have at least: 
- 2 log panel - (1 log query could have line filter)
- 2 time series panels 
- 2 stats panels 
- template variables 
- ad-hoc filters

**Comment by matyax** [comment]
Giving this one a try.

**Comment by matyax** [comment]
@ivanahuckova When you request:

> 2 time series panels
> 2 stats panels

What would you suggest as a datasource for those?

**Comment by matyax** [comment]
@ivanahuckova Reformulating my question:

> 2 time series panels
> 2 stats panels

Can we display those kind of panels with Loki data?

**Comment by matyax** [comment]
After exploring this task, I'm not really sure how to pull a useful dashboard from Loki displaying those kinds of panels.

**Comment by ivanahuckova** [comment]
@matyax It doesn't have to be useful. 🙂 In `gdev-loki` we have dummy data and the point for the task is mainly to see loki used with different visualisation. No need to worry about the context/if the query is useful.
