### ISSUE TITLE
Templating "Include All Option" error after upgrading to 3.0.4

### ISSUE THREAD

**Issue by castrojsec** [grafana/grafana#5305]
upgraded from 2.5 to 3.0.4 recently.  My current dashboards that have the "include all option" selected along with the "Multi-value" option look like this now.  I have to unselect then re-select to clear.

![error](https://cloud.githubusercontent.com/assets/4368158/15872004/48cc0962-2cc5-11e6-993c-8ab9c8b0c6db.jpg)

This happens in all browsers

Please include this information:
- What Grafana version are you using?
- What datasource are you using?  Graphite
- What OS are you running grafana on?  Debian GNU/Linux 7 (wheezy)

**Comment by torkelo** [comment]
already fixed in master and in 3.0.x branch 
https://github.com/grafana/grafana/issues/5172
