### ISSUE TITLE
Alerting: create and use compare function for provisioning structs

### ISSUE THREAD

**Issue by JohnnyQQQQ** [grafana/grafana#53060]
Currently, in provisioning, we always update structs if they already exist. This introduces some load to the database. In the future, we would like to have a function that compares the internal state with the external state.

- [ ] Alert rules
- [ ] Contact points
- [ ] Templates
- [ ] Mute timings

This relates to provisioning.

**Comment by armandgrillet** [comment]
@JohnnyQQQQ What is you feedback regarding @hereisajvi's comment?
