### ISSUE TITLE
[QUESTION] how could I request for JSON file locally?

### ISSUE THREAD

**Issue by NUS-Anonymous** [grafana/grafana#5307]
Hi, I would like to download JSON file (dashboard data) using HTTP API request as given, however, I would like to do it through Javascript so that I wont need to configure proxy (if my organization network has proxy set up). The problem right now is Cross-Domain-Request is not allowed in any browser, and while return data from HTTP API request is not set to Allow-Cross-Domain Access. Hence I am wondering if there is other way for me to request for JSON file directly from grafana installation directories? Else do you have a better approach? Thanks in advance. Great job with Grafana btw!

**Comment by torkelo** [comment]
please read the issue template :)

```
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
```

Must have missed  this :) 
Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
