### ISSUE TITLE
Panel change not recognized and save dashboard not possible

### ISSUE THREAD

**Issue by agido-malter** [grafana/grafana#53084]
**What happened**:
After a minor change in panel, such as legend or alert thresholds, change is not recognized. Save dashboard is not possible, because of no chnaged recognized

**What you expected to happen**:
After change, save dashboard should show changes and save button shoould be active

**How to reproduce it (as minimally and precisely as possible)**:
Open dashboard and edit panel
Change something in panel settings or change a alarting threshold. Example from below 20 to below 10
Click on apply
Click on save dashboard

No change is shown, save button is not active

**Anything else we need to know?**:
Workaround after minor changes, add a space after prometheus query. Than save is possible
Could be related to #48304 

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: Prometheus 2.36.1
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: macOS, Google Chrome
- Grafana plugins: Grafana Renderer
- Others:

**Comment by zuchka** [comment]
> such as legend or alert thresholds

it sounds like you are using the legacy alerting platform, which is deprecated. Can you confirm: are you using the new Grafana Alerting platform (first released in Grafana 8) or the legacy alerting platform? I should note that the legacy platform is no longer actively developed:

https://grafana.com/docs/grafana/next/alerting/migrating-alerts/

**Comment by agido-malter** [comment]
@zuchka i can confirm that legacy alertig is off.  As quick test, open a panel, change on y-axis from 100 to 200 and try to save the dashboard. Save button is not active

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by agido-malter** [comment]
@zuchka Hi Matt

For sure. I was able to reproduce it on your sandbox. See screencast

https://monosnap.com/file/PYn1I6LRKpnRtDWuWtk9ooMdZNFezc

**Comment by zuchka** [comment]
@agido-malter yep, I was able to reproduce the same. But then I updated all of those panels from Graph (old) to Timeseries and they appear to work now. Give it a try:

https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m

**Comment by agido-malter** [comment]
@zuchka i tried it on your sandbox and also on our system. On the sandbox it works and after update a panel in ous system also. Looks like an upcoming mega job to update all panels from legacy Graph to Timeseries 😆
