### ISSUE TITLE
Grafana removing duplicate values in fields

### ISSUE THREAD

**Issue by Pyttei** [grafana/grafana#53089]
**What happened**:

When trying to make a pie chart with values coming from a certain field, duplicate values in an array are automatically removed.

**What you expected to happen**:
I expected duplicate values to stay.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have a Elasticsearch log with the field and values: `failure: [“Test failed”,“Test failed”]`. 
2. Make a pie chart with count of `failure`, and the pie chart only shows one count of `“Test failed”` even though it should show two.

**Anything else we need to know?**:
I inspected the query editor and it is only returning one `“Test failed”`, so I'm not sure if the problem is in Elasticsearch side or Grafana.

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Elasticsearch 8.2.3

**Comment by zuchka** [comment]
Can you [inspect your raw request and response](https://grafana.com/docs/grafana/latest/panels/inspect-panel/#view-raw-request-and-response-to-data-source) and then share it in a code-block?

Can you use the data tab inside [the Grafana Inspector panel](https://grafana.com/docs/grafana/next/panels/working-with-panels/navigate-inspector-panel/) to share your data?

https://grafana.com/docs/grafana/next/panels/working-with-panels/navigate-inspector-panel/

**Comment by Pyttei** [comment]
The raw request and response:
```
{
    "request": {
      "url": "api/datasources/proxy/9/_msearch?max_concurrent_shard_requests=5",
      "method": "POST",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"error-index-*\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1656460800000,\"lte\":1657756799000,\"format\":\"epoch_millis\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"failure.keyword\",\"size\":500,\"order\":{\"_count\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1656460800000,\"max\":1657756799000},\"format\":\"epoch_millis\",\"fixed_interval\":\"365d\"},\"aggs\":{}}}}}}\n",
      "hideFromInspector": false
    },
    "response": {
      "took": 12,
      "responses": [
        {
          "took": 12,
          "timed_out": false,
          "_shards": {
            "total": 28,
            "successful": 28,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": {
              "value": 7,
              "relation": "eq"
            },
            "max_score": null,
            "hits": []
          },
          "aggregations": {
            "3": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "2": {
                    "buckets": [
                      {
                        "key_as_string": "9684654000000",
                        "key": 9684654000000,
                        "doc_count": 1
                      }
                    ]
                  },
                  "key": "Test failed",
                  "doc_count": 1
                }
              ]
            }
          },
          "status": 200
        }
      ],
      "$$config": {
        "url": "api/datasources/proxy/9/_msearch?max_concurrent_shard_requests=5",
        "method": "POST",
        "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"error-index-*\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1656460800000,\"lte\":1657756799000,\"format\":\"epoch_millis\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"failure.keyword\",\"size\":500,\"order\":{\"_count\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1656460800000,\"max\":1657756799000},\"format\":\"epoch_millis\",\"fixed_interval\":\"365d\"},\"aggs\":{}}}}}}\n",
        "hideFromInspector": false
      }
    }
  }
```
This is the data from data tab:

```
"Time","Test failed"
2022-01-19 02:00:00,1
```

And in Elasticsearch the data looks like this:

```
  {
    "_index": "error-index-2022.07.08",
    "_id": "vejkahdgjGIUSjhs",
    "_version": 1,
    "_score": 1,
    "_source": {
      "@timestamp": "2022-07-08T11:28:57.576372Z",
      "failure": [
        "Test failed",
        "Test failed"
      ]
    },
    "fields": {
      "failure": [
        "Test failed",
        "Test failed"
      ],
      "failure.keyword": [
        "Test failed",
        "Test failed"
      ]
    }
  }
```

**Comment by gabor** [comment]
hi @Pyttei , based on the elasticsearch-response you provided, to me it seems elasticsearch is saying: `["test failed", 1]`.
so Grafana is correctly displaying what elasticsearch returned.

the query you are sending to elasticsearch is:
- take all the documents, group them by the value of the field `failure.keyword`, and count every group

and elasticsearch is reporting that there is a single document, that's the `1`.

so i think the elasticsearch query needs to be changed.

**Comment by Pyttei** [comment]
Hi @gabor,
Yeah that's what I was thinking too but I'm not sure how I could make the right query. If you have any suggestions I would love to try them out.

**Comment by gabor** [comment]
hi @Pyttei , i'm sorry, i don't have any useful suggestions for this. i recommend checking with the elasticsearch community, perhaps at https://discuss.elastic.co/ .
