### ISSUE TITLE
Table footer doesn't honour decimal override setting for fields

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#53097]
**What happened**:

Configured a table with multiple fields; one has decimals set to 0.  Footer has all the decimal places :-)

<img width="287" alt="image" src="https://user-images.githubusercontent.com/444037/182337075-f9cd3632-7b3d-4e04-86bf-ef65bf2de161.png">

**What you expected to happen**:

Footer should have same formating as the field in the table.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: d06ea6ea0
- Data source type & version: BigQuery
- OS Grafana is installed on: k8s
- User OS & Browser: Version 103.0.5060.134 (Official Build) (arm64) on an M1 Mac
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @tomwilkie,

thanks for reporting this case.

Can you please reproduce this same issue on https://play.grafana.org/ and then the dashboard link so that we can view it?

Thanks

**Comment by usmangt** [comment]
1.

**Comment by tomwilkie** [comment]
Hi @usmangt! Heres a link to our internal dashboard that shows the issue, you should be able to access that: https://ops.grafana.net/d/HGyv4K07k/cloud-costs?orgId=1

**Comment by ashharrison90** [comment]
@tomwilkie looking at the ops dashboard it seems this has been fixed

feel free to reopen if i've got that wrong 👍
