### ISSUE TITLE
[Feature Request] Allow importing from spaces you have access to or batch export/import

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#5310]
### Overview
The export/import json that is used currently is lengthy when doing more than one.

It would be useful to be able to copy/import dashboards from other spaces. This could be in the form of : 
- if user has sufficient rights (possibly either viewer as editor, editor or admin)
- then allow (multi) importing dashboard(s) from selected space

The only problem with this is that if you import a dashboard and you don't have a datasource with the same config/name etc it will break. 

I saw an issue made here about import/export easiness (maybe this could be added if pertinent) : https://github.com/grafana/grafana/issues/5084

### Alternatives (this is probably simpler)
Batch export of dashboards to one big json file, and import of the same file from another multi-select interface.

### The why
People in one team may like the dashboards of other teams, but either cannot or should not edit them. being able to import or copy from other spaces would be useful. This is especially true for dashboards done by the team I am in who make performance oriented dashboards (JVM memory, threading, request breakdowns, performance metrics etc). They are used as "templates" by other teams who want to fiddle, but not mess with the relative complexity of all the template variables.

**Comment by bergquist** [comment]
We are working on improving the dashboard sharing experience. Once https://github.com/grafana/grafana/issues/5084 is complete the problems you addressed will be solved. 

You can use API for exporting/importing dashboards if you want it customized for your workflow.

**Comment by torkelo** [comment]
dashboard folders & permissions we is going to solve this https://github.com/grafana/grafana/issues/1611
