### ISSUE TITLE
Loki: Remove hardcoded values for parsed query parts

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#53116]
**Level: easy**

 In public/app/plugins/datasource/loki/query_utils.ts and in lezer-logql we are using many string comparisons. Example: 
	if (type.name === 'LabelFormatExpr') {
   		queryWithLabelFormat = true;
}

	Change those to something like 
	if (type.id === LabelFormatExpr) {

This can be be also done for Prometheus and lezer-promql.

**Comment by itsmylife** [comment]
There are more in the following files:
- `public/app/plugins/datasource/loki/querybuilder/parsing.ts`
- `public/app/plugins/datasource/loki/addToQuery.ts`
