### ISSUE TITLE
[Bug] Null value option Null behaves like connected

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#5311]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.0.3
- What datasource are you using?
  Prometheus
- What OS are you running grafana on?
  Linux
- What did you do?
  Use stacked graph with "Null value" option "Null".
- What was the expected result?
  Gaps in some time series returned (Prometheus does not fill gaps with `null` values but just omits them) Grafana should just treat them as null. This worked fine in previous versions.
- What happened instead?
  Grafana stops rendering the graph as soon as it hits the first gap in a time series.

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
  ![screenshot from 2016-06-08 16-04-15](https://cloud.githubusercontent.com/assets/3432/15897128/8135ae10-2d93-11e6-9fdc-c17ba7071398.png)
  ![screenshot from 2016-06-08 16-03-51](https://cloud.githubusercontent.com/assets/3432/15897127/813565b8-2d93-11e6-91f3-fe9d8fdeb2cc.png)

**Comment by mtanda** [comment]
@grobie Would you share raw Prometheus response?
The latest Prometheus timestamp format becomes "seconds" not "milliseconds".
I think it might affect this issue.

**Comment by daniellee** [comment]
No response to follow up question so closing this. Will reopen if still a problem.
