### ISSUE TITLE
Loki: Remove hardcoded values for LokiOperationId

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#53115]
**Level: easy**

In `public/app/plugins/datasource/loki/querybuilder/parsing.ts` and `public/app/plugins/datasource/loki/querybuilder/parsing.test.ts` we are using hardcoded values for LokiOperationId (e.g. __label_filter). These should be changed to to LokiOperationId enums (e.g. `LokiOperationId.LabelFilter`). 

This can be also done for Prometheus and PromOperationId. If decided to work on this, it should be done in separate PR. Moreover, before working on Prometheus, we should check with observability/metrics team.

**Comment by matyax** [comment]
@grafana/observability-metrics do you think we can work on the Prometheus part of this task?

**Comment by gtk-grafana** [comment]
Yup, @ivanahuckova created these tickets for our squad: https://github.com/grafana/grafana/issues/53152, https://github.com/grafana/grafana/issues/53156, which should address this issue with prometheus!

**Comment by matyax** [comment]
Just to be sure, are you going to take care of the Prometheus part in those? Thanks!
