### ISSUE TITLE
[Feature request] Scripted dashboard for organisation only

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#5312]
Hi,

Scripted Dashboard is a very nice feature.
It will be nice if we could restrict acces by organisation.
Otherwise it will be better again if we could add main menu entry to call a scripted dashboard with parameter

Should we expect developments on scripted dashboard for the v4 version ?

Thank you

**Comment by daniellee** [comment]
Scripted dashboards has been deprecated and we will be working on a different approach to this.
