### ISSUE TITLE
Navigation: Plugin architecture to support new hierarchy

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#53141]
see example of oncall here: https://www.figma.com/file/m0q3sBVILBNGZO1QolsMn6/Top-Nav-and-Secondary-Nav?node-id=1049%3A906

- [ ] plugins can be positioned in arbitrary places in the navbar
- [ ] plugins will need to have a similar secondary navigation to other pages

**Comment by ashharrison90** [comment]
fyi @grafana/plugins-platform-frontend 

let's use this issue to discuss 👍

**Comment by torkelo** [comment]
@ashharrison90 / @grafana/plugins-platform-frontend 

Did some initial exploration on this, https://github.com/grafana/grafana/tree/plugin-page-layout  
It's very tricky, on many levels
* Backward compatible (old plugins that are not updated should still look "ok" (with some degradation but usable)
* Plugins need to be able to "opt-in" to new page layouts (and correct place in information hierarchy) when topnav feature is enabled but still work/look "ok" when topnav is disabled 
* We need to be able to move plugins around the information hierarchy (preferably without updating/recompiling the plugin). 
* Communty plugins should not be able to change what section they are in. 
* Plugins need control over page layout (full page or with section nav)
* Plugin pages need to support item navigation (ie breadcrumbs and item page nav model) (This is already supported by Page componnet in core, just need a wrapper for this that is exposed to Plugins, this part what I started exploring in the branch above).

**Comment by leventebalogh** [comment]
Mentioning this issue here as it is about something similar: https://github.com/grafana/grafana/issues/49788
