### ISSUE TITLE
[Bug] Template Variables Error When Data Contains Chars That are Escaped by Grafana

### ISSUE THREAD

**Issue by forewarned** [grafana/grafana#5314]
## See Edit Near Bottom of Post

This issue is similar to https://github.com/grafana/grafana/issues/5228 and perhaps https://github.com/grafana/grafana/issues/5227

I've been able to get other nested queries to work, but there a few that are generating errors where the data contains null or -1 values. For example, I have a Number field where the data contains a -1, 0, and positive integers. When I attempt to write a query, I get the following error as copied from Chrome:

`boot.js:35 SyntaxError: Unexpected number in JSON at position 62
    at Object.parse (native)
    at Object.X [as fromJson] (http://localhost:3000/public/app/boot.js:33:22171)
    at h.metricFindQuery (http://localhost:3000/public/app/boot.js:13:15380)
    at updateOptionsFromMetricFindQuery (http://localhost:3000/public/app/boot.js:10:29077)
    at b (http://localhost:3000/public/app/boot.js:40:19987)
    at h (http://localhost:3000/public/app/boot.js:35:19121)
    at http://localhost:3000/public/app/boot.js:35:19293
    at n.$eval (http://localhost:3000/public/app/boot.js:35:26810)
    at n.$digest (http://localhost:3000/public/app/boot.js:35:25318)
    at n.$apply (http://localhost:3000/public/app/boot.js:35:27093)`

Here are the parameters to my query:
![image](https://cloud.githubusercontent.com/assets/14337073/15899300/5086880e-2d69-11e6-9cb0-27cb671b7e5c.png)

When the variable doesn't contain a Lucene query but the data for that field contains null or -1 values, there is no error. I would expect similar behavior when using a Lucene query.
- Version: Grafana 3.0.4
- Datasource: Elasticsearch
- OS: Windows 7
## EDIT

I think the issue might lie with Grafana escaping characters in the data. The following are parts of the request payload of the search query that I pulled from Chrome:
`"query": ...Number:(\"\\-1\" OR \"1\")....AND City:(\"Miami\" OR \"Las\\ Vegas\") AND Region:(\"Asia\" OR \"South\\/Southeast\\/Southwest\\ \" OR...)"`

Notice the double back slash on the negative sign (-), space, and forward slash. Although I haven't tested it for all situations, when my data does not contain a space or forward slash then the query appears to work. My data does not contain the backslashes.

**Comment by timparkinson** [comment]
I've also noticed, on the influxdb datasource, that the hyphen character in template variable data is being double escaped. I'm seeing it get to influx logs as: ...  AND "cluster" =~ /na\\-clus4$/ ...

**Comment by ricardoj-br** [comment]
I'm using Grafana 4.5.2 on Ubuntu 16.04 and Elasticsearch 5.6.2 and Teplating with Constant Type Variable still being escaped and the query fails. I have a Zip Code value in the format NNNNN-NNN or NNNNN. If I use only 5 digits query works but if I use 9 digits NNNNN-NNN wury fails.

**Comment by Elfo404** [comment]
The issue may be that we are escaping also quoted values in https://github.com/grafana/grafana/blob/61749dee2329b716ec499d13180659c4986ae7fc/public/app/features/templating/formatRegistry.ts#L32 and it *shouldn't* be necessary.

**Comment by Shawcs** [comment]
Same problem for me. I use variable with lucene format to query my elastic cluster and my variable are escaped. From this doc page [grafana doc variable format](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#lucene---elasticsearch) my query should beahave like that:  
['dmz', 'lan'] become '("dmz" OR "lan")'   
here I have:
 ['dmz', 'lan'] become '(\\"dmz\\" OR \\"lan\\")'  
as you can see in the screen:
![git data](https://user-images.githubusercontent.com/14977135/104437956-b5942000-558f-11eb-900f-792e9d9e521f.PNG)
This is fine for some query, but especially when I want to use wildcard this break the query for elastic.
