### ISSUE TITLE
Alerting: Provisioning rule API should validate rule namespace

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#53151]
**What happened**:

The provisioning rule API allows any string as the NamespaceUID - it doesn't check to see whether the folder actually exists before creation. The result is that a rule is created outside of any folder. There are periodic warnings in the logs: `failed to fetch alert rule namespace`.

**What you expected to happen**:

I expected the API to validate the `NamespaceUID` field against the created folders.

**How to reproduce it (as minimally and precisely as possible)**:

1. Issue a POST request to `/api/v1/provisioning/rules` with an invalid `NamespaceUID`.
2. The request succeeds.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
We need to use the folder service to check if the `NamespaceUID` exists, this should be done in Grafana's rule service to have it centralized.
