### ISSUE TITLE
SIGTERM: cleanly close sqlite3 / wait for transactions to complete

### ISSUE THREAD

**Issue by edmundnoble** [grafana/grafana#5315]
* **I'm submitting a ...**
- [ ✔️  ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.3
- What datasource are you using? Doesn't even start
- What OS are you running grafana on? Ubuntu
- What did you do? Started and stopped grafana very quickly because of peculiarities of a Chef recipe, using SQLite as a DB.
- What was the expected result? It started and worked.
- What happened instead? It crashed on startup with a migration failure, even though the migration it was trying to apply was already applied.

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

This is very reproducible from my end, happens right after a fresh install. The logs say:
```
2016/06/08 15:48:50 [I] Starting Grafana
2016/06/08 15:48:50 [I] Version: 3.0.3, Commit: v3.0.3, Build date: 2016-05-23 08:58:31 +0000 UTC
2016/06/08 15:48:50 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
  [2]: default.paths.plugins=/var/lib/grafana/plugins
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins

2016/06/08 15:48:50 [I] Database: sqlite3
2016/06/08 15:48:50 [I] Migrator: Starting DB migration
2016/06/08 15:48:50 [I] Migrator: exec migration id: create index IDX_temp_user_code - v1-7
2016/06/08 15:48:50 [migrator.go:135 func1()] [E] Migrator: exec FAILED migration id: create index IDX_temp_user_code - v1-7, err: index IDX_temp_user_code already exists
2016/06/08 15:48:50 [migrator.go:103 Start()] [E] Migrator: error:
index IDX_temp_user_code already exists:
CREATE INDEX `IDX_temp_user_code` ON `temp_user` (`code`);
2016/06/08 15:48:50 [log.go:84 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: index IDX_temp_user_code already exists
```

Deleting `/var/lib/grafana/grafana.db` allows Grafana to run normally.

**Comment by torkelo** [comment]
So you have a old grafana.db? Thought you said it was fresh install? On a completely clean system with no prior grafana version do you get this error?

What version is your grafana.db coming from?

**Comment by edmundnoble** [comment]
It's a fresh install, completely clean system every time. I don't have an old grafana.db. I have a grafana.db which is created by Grafana, and partially migrated before Grafana is killed by SIGTERM.

**Comment by torkelo** [comment]
I guess it's a bug in the chef script that somehow kills grafana and leaves the db in a corrupt state maybe?

**Comment by edmundnoble** [comment]
Killing Grafana with SIGTERM, *cleanly*, should *not* be able to corrupt my data. It's moot anyway, because the database doesn't even seem to be corrupt. The migrator is simply unable to recognize it has already applied some migrations.

I applied a temporary fix to my Chef script, so it's not something I need urgently, but I don't know how you can't see that this is a bug in Grafana.

**Comment by torkelo** [comment]
might be that sqlite3 db is not cleanly closed / waiting for transaction to complete on SIGTERM

**Comment by ethan-eb** [comment]
We seem to be experiencing the same thing. In our case we have a Docker container running graphite, I recently added grafana 3.0.4 to the same container. The boot script first starts and stops grafana (this is to ensure that the sqlite DB gets created on a newly built container ... a better way probably exists, but I didn't see a command or a stand-alone schema I could use). I then run a sqlite3 command to hook up the right backend. Then when the container finally launches grafana is launched and left running.

I have not been able to reproduce the problem myself, but two other engineers have run into nearly identical errors as reported here (see below). After re-trying the build they have gotten past the problem. So it's intermittent for us.

Errors we've seen:

    2016/06/27 21:12:47 [migrator.go:135 func1()] [E] Migrator: exec FAILED migration id: Add column updated_by in dashboard - v2, err: duplicate column name: updated_by
    2016/06/27 21:12:47 [migrator.go:103 Start()] [E] Migrator: error: duplicate column name: updated_by: alter table `dashboard` ADD COLUMN `updated_by` INTEGER NULL

and: 

    2016/07/01 22:30:30 [migrator.go:103 Start()] [E] Migrator: error: index UQE_user_login already exists:

**Comment by torkelo** [comment]
fixed!
