### ISSUE TITLE
WorldMap plugin with InfluxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5316]
How do i use WorldMap plugin with InfluxDB?

My query returns following reasults

SELECT count(distinct(eId)) FROM ep."default".epdetail3 WHERE time > now() - 30d GROUP BY time(30d), siteId fill(none)
name: epdetail3
tags: siteId=0
time			count
----			-----
2016-04-29T00:00:00Z	2
2016-05-29T00:00:00Z	3

name: epdetail3
tags: siteId=MCMS
time			count
----			-----
2016-04-29T00:00:00Z	1
2016-05-29T00:00:00Z	1

> SELECT count(distinct(eId)) FROM ep."default".epdetail2 WHERE time > now() - 30d GROUP BY time(30d), siteId fill(none)
name: epdetail2
tags: siteId=0
time			count
----			-----
2016-04-29T00:00:00Z	11
2016-05-29T00:00:00Z	9

name: epdetail2
tags: siteId=15
time			count
----			-----
2016-04-29T00:00:00Z	1
2016-05-29T00:00:00Z	1

name: epdetail2
tags: siteId=3
time			count
----			-----
2016-04-29T00:00:00Z	6
2016-05-29T00:00:00Z	4

name: epdetail2
tags: siteId=77
time			count
----			-----
2016-04-29T00:00:00Z	5
2016-05-29T00:00:00Z	4

siteId is countryCode and hence for Country Code 0 (US) i want two circles with radius/diameter 11 and 9 and so for other groups.

Is this correct usage ?

**Comment by torkelo** [comment]
if you have tags with contrycode then you can use that to name your series so they contain the contry code , please post questions for this plugin in that plugin repo
