### ISSUE TITLE
Import dashboard from InfluxDB

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#5318]
Seems that the option to import dashboards from influxdb is restricted to influxdb_08 datasources, but those don't exists any more.

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/importCtrl.js#L22

**Comment by torkelo** [comment]
yes it does, it's a plugin you can install:
https://grafana.net/plugins/grafana-influxdb-08-datasource

**Comment by adrianlzt** [comment]
I really want to know if will be posible to use the import dashboards from the new influxdb datasource

**Comment by torkelo** [comment]
well since Grafana never supported saving dashboards to InfluxDB 0.9+  it would be impossible to have dashboards stored there (and hence import them)
