### ISSUE TITLE
[Bug] InfluxDB Templates Containing Periods In The Variables Fail

### ISSUE THREAD

**Issue by spjmurray** [grafana/grafana#5319]
InfluxDB: 0.13.1
Grafana: 3.0.4

Apologies for not fixing but JS scares me ;p

I have a template query which looks like this:
```
$domain 	SHOW TAG VALUES FROM load WITH KEY = "domain"
```
Which correctly resolves to "angel.net".

I have a second template which does the following
```
$hostname  SHOW TAG VALUES FROM load WITH KEY = hostname WHERE domain = '$domain'
```

Basically when running this second query the macro expansion yields the following because formatValue has done a regex escape:
```
"SHOW TAG VALUES FROM load WITH KEY = hostname WHERE domain = 'angel\.net'"
```

This eventually makes its way down into an InfluxDB query which then fails with
```
GET /query?db=icinga2&epoch=ms&q=SHOW+TAG+VALUES+FROM+load+WITH+KEY+%3D+hostname+WHERE+domain+%3D+%27angel%5C.net%27 HTTP/1.1 400
```
```
curl 'http://localhost:8086/query?db=icinga2&epoch=ms&q=SHOW+TAG+VALUES+FROM+load+WITH+KEY+%3D+hostname+WHERE+domain+%3D+%27angel%5C.net%27'
{"error":"error parsing query: found \\., expected identifier, string, number, bool at line 1, char 69"}simon@influxdb:~$
```

Without the escaped slash we are okay!
```
curl 'http://localhost:8086/query?db=icinga2&epoch=ms&q=SHOW+TAG+VALUES+FROM+load+WITH+KEY+%3D+hostname+WHERE+domain+%3D+%27angel.net%27'
{"results":[{"series":[{"name":"load","columns":["key","value"],"values":[["hostname","ns"],["hostname","centos"],["hostname","fedora"],["hostname","jenkins"],["hostname","icinga"],["hostname","puppet"]]}]}]}
```

**Comment by torkelo** [comment]
template value escaping defaults to regex to support multiple values in the variable. 

Change query to this:
"SHOW TAG VALUES FROM load WITH KEY = hostname WHERE domain =~ /^$domain/
