### ISSUE TITLE
Support setting `dashboard_uid` and `panel_id` through the alerting provisioning API

### ISSUE THREAD

**Issue by JohnnyQQQQ** [grafana/grafana#53199]
Currently, this can only be done by using file provisioning. We should also extend it to the normal API.

**Comment by moyamos** [comment]
Hi,
Thanks for opening the issue. :hand:

Do you have any estimate of when it will extend to the provisioning API?
I want to generate alerts via the API and associate them with dashboard panels. Can I use file provisioning instead till it is available through the API? How can I use file provisioning?

**Comment by JohnnyQQQQ** [comment]
File provisioning will be released in 9.1. I don't have an ETA yet for this. We will try to get in in 9.1 but we cannot guarantee it.

**Comment by moyamos** [comment]
Would you please update here after release? Thanks.

**Comment by JohnnyQQQQ** [comment]
Sure thing!

**Comment by JohnnyQQQQ** [comment]
This is fixed on main and will be part of the 9.1 release.
