### ISSUE TITLE
Connections Page: figure out how to "launch"

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#53209]
The issue is about figuring out how we are planning to launch this page in Cloud.
(Currently only available behind a feature flag, but once we are happy with the MVP version we would like to gradually roll it out to some users I think)

**Comment by mikkancso** [comment]
Rollout plan document: https://docs.google.com/document/d/1k-V-SZ_pC9kE-GqH27rpBdbrUlIsJ3GrL85a7wpPi8c/edit?usp=sharing

**Comment by mikkancso** [comment]
Next step: let Hosted Grafana team know about this. (Also keep this page in mind for when we're about to roll out: https://github.com/grafana/deployment_tools/tree/master/ksonnet/environments/hosted-grafana/waves/feature-toggles#instructions)

**Comment by leventebalogh** [comment]
As @mikkancso created that amazing [rollout plan doc](https://docs.google.com/document/d/1k-V-SZ_pC9kE-GqH27rpBdbrUlIsJ3GrL85a7wpPi8c/edit?usp=sharing) I think we can actually close this issue and follow things over there.
(Please reopen if you have objections.)
