### ISSUE TITLE
Chore: refactor the Plugins and Datasources client-side state

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#53210]
**What is the problem?**
Currently the client-side Redux state for Plugins and Datasources is a bit coupled, they store information in each others reducers. (I will try add actual example here later.) This makes working with and extending logic in these areas is harder. 

**What is the goal?**
We would possibly like to have a similar state structure to what we already have in the plugins reducer, where all meta-data for plugin objects is stored in a list of objects.

**Comment by mikkancso** [comment]
@leventebalogh is this something that still requires some work? If yes, could it be removed from the Connections Console Project?

**Comment by leventebalogh** [comment]
Thanks for the heads up! Although it would still require some work and could be still relevant, it's not connected to the connections work (anymore). I am closing it for now, we might recreate it once we see the need in those refactors.
