### ISSUE TITLE
'folder:current' query no longer works in Grafana 9

### ISSUE THREAD

**Issue by deimantastumas** [grafana/grafana#53212]
**What happened**:
After upgrading to Grafana 9.0.6, we've noticed that searching dashboards with `folder:current` no longer works as it used to. The issue can be reproduced on Grafana playground too.

**What you expected to happen**:
Expected to see dashboards in the current folder.

**How to reproduce it (as minimally and precisely as possible)**:
![reproduce](https://user-images.githubusercontent.com/36602611/182601246-11dd0bbf-b799-4c3c-91cf-7ebb3b8522be.gif)

**Comment by usmangt** [comment]
Hi @deimantastumas ,

Thanks for opening this issue. Yes, I see that on play as well.

Can you please tell on which OS and Platform you were able to reproduce this issue?

And,

does it only reproducible only doing upgrade an existing dashboard to a new grafana server version  OR can be reproduced on a fresh grafana server too?

Thanks

**Comment by deimantastumas** [comment]
Hey! We're running dockerized Grafana container on physical CentOS 7 servers.

I've tried reproducing the issue locally and it seems like `panelTitleSearch` feature causes the issue. Without toggling the feature searching works as expected.

**Comment by ashharrison90** [comment]
thanks for the report! 🙌 

this has been fixed in 9.1.0-beta1 and will be released in 9.1.0 fully 👍
