### ISSUE TITLE
[BUG] ldap and company bind

### ISSUE THREAD

**Issue by BMarvi** [grafana/grafana#5322]
grafana 3.0.4
Hello, 
I have configured Grafana to use the ldap configuration, but I have a annoyng problem:
my configuration contains these relevant settings:

    [[servers.group_mappings]]
     group_dn = "*"
    org_role = "Viewer"
    org_id = 2

obv. there is an organization with id=2
when an user try to login for the first time he gets an error: "Error while trying to authenticate user".
logs says: 

    [login.go:102 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin

as admin I check the organizations and I find a new organization with the name equal to the user email.
The login error perisist until I delete the new organization created.
As I delete it, the user can enter, but he isn't associated to the desired company. So he have to switch to it.
After this he can login/logout correctly. 
But next new user will have the same issue... 

Is it my fault? or is a bug?

thanks

**Comment by torkelo** [comment]
what is your auto_assign_org option?


http://docs.grafana.org/installation/configuration/#auto_assign_org

**Comment by BMarvi** [comment]
Was left to the default (commented). 
Settinig it to _true_  I have no more login errors, no new unwanted organizations. 
Much better now, thanks! 
Only a little thing: at the first login the user is not associated to the #2 organization as I would expect (org_id = 2 parameter in ldap.toml), but get an "organizations missing". So he must switch manually to the designed company. 
Not a problem, but could be a little improvment. 

Thanks again, Marvi

**Comment by torkelo** [comment]
set auto_assign_org to false
