### ISSUE TITLE
Docs feedback: /datasources/alertmanager.md

### ISSUE THREAD

**Issue by jimethn** [grafana/grafana#53263]
I followed the yaml example [on this page](https://grafana.com/docs/grafana/latest/datasources/alertmanager/) to add an alertmanager datasource, but it threw errors in the UI.

After searching through the forums, I was able to get it working by adding the implementation to the datasource:

```
    jsonData:
      implementation: prometheus
```

As far as I can tell, this implementation field isn't documented anywhere, nor are its values. I only found out about it by reading a commenter on [this issue](https://github.com/grafana/grafana/issues/50648), who in turn found it on a blog.

**Comment by zuchka** [comment]
cc: @grafana/docs-squad

**Comment by brendamuir** [comment]
Thanks for the feedback-will work on getting this updated!

**Comment by brendamuir** [comment]
@gg can you help here since it's a data source topic?

**Comment by gguillotte-grafana** [comment]
The `implementation` key was implemented in #39775 without documentation. #50943 implemented `mimir` as a valid option for `implementation`, also without documentation. This data source appears to be maintained at least in part by the Alerting team, particularly around this feature, and they might be better to ask for technical confirmation.

cf. #53907

I'm also concerned about a potential UI issue exposed by this. The documentation states that the implementation should be set in the data source UI. #50648 suggests that doing so does not work as expected.

This is a similar issue as #46908 - Prometheus data source settings implemented without documentation. It's unclear to me from the PRs whether they are even intended to be documented; if not, this might also be a product bug.

cf. grafana/grafana-api-golang-client#44, which implemented both `implementation` and #46908's `alertmanagerUID` and `manageAlerts` settings.

**Comment by gguillotte-grafana** [comment]
Filed #57043.
