### ISSUE TITLE
customizable panel pixe-presice sizing or rendering for presentations

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#5326]
I'm working on a presentation for a conference, my slides have to be 720p, e.g. 1280x720px.
I want to include some grafana graphs in it, fullscreened for 720p.

my current workflow is the following:
go to dashboard i want to include, fullscreen my browser.
resize the panel i want to 8/12 of the available row width
set panel height to 720px in grafana. i don't know how exactly this is implemented, when i look at the size with the dev inspector the graph itself is 664, with the legend block it's 693 and with the title 731

then open my screenshot app and then i just select the area around the graph, but very little whitespace around the legend and title., this brings me more or less to 1280x720px
then i open my image editor and trim some blank space to make sure width and height are no more than what's allowed, and sometimes they're already a bit too short, but i just live with that.

anything to improve this workflow would be a nice to have. the best would be if there was a button somewhere where i could say "export this panel as a png of these dimensions"

**Comment by torkelo** [comment]
specifying width and height in the image rendering query returns a graph image with the exact dimensions you want. 

Example 1280x720px graph
http://play.grafana.org/render/dashboard-solo/db/new-features-in-v2-0?panelId=11&from=1465551001123&to=1465554601123&width=1280&height=720

**Comment by Dieterbe** [comment]
cool thanks.
