### ISSUE TITLE
Minified React error #185 (Grafana Home page) on some browsers

### ISSUE THREAD

**Issue by lspaula** [grafana/grafana#53267]
The current issue is related to this other: https://github.com/grafana/grafana/issues/36096

![image](https://user-images.githubusercontent.com/13789626/182679625-f4f13041-525c-4aad-848d-39d312e81e76.png)

**What happened**: Some browser instances, including Chrome (103.0.5060.134), Samsung Internet (17.0.7.34) and Edge (103.0.1264.77 ) are showing this behavior. I have one extra Edge (103.0.1264.77) which still works ok. 

**What you expected to happen**: The authentication page should be shown.

**How to reproduce it (as minimally and precisely as possible)**:  I 've tried to reach my Grafana page with http://<my_ip>:3000, like always.

**Anything else we need to know?**:  It happens when there is a large number of items on the page. I've tried with only a few items and it works fine. It stopped working a few days ago and was working ok prior to that. It seems to be related to a browser condition.

**Environment**:
- Grafana version: v8.3.3 (30bb7a93ca)
- Data source type & version: InfluxDB
- OS Grafana is installed on: Openhab 3.2.0
- User OS & Browser: Windows 10 (Browsers and versions listed above)
- Grafana plugins: None

**Comment by zuchka** [comment]
Thanks for creating this issue, @lspaula 

> It happens when there is a large number of items on the page

can you explain this in more detail?

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by lspaula** [comment]
Hi zuchka. 

I've reinstalled Grafana and now everything is working correctly. Perhaps the issue was a corrupted data from a server migration. I will close the issue.

Best,

Luciano
