### ISSUE TITLE
How to add timeFilter in Template queries for InfluxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5327]
I have a template query (REFRESH on Load selected)that takes quite a few seconds to load and this results in unpleasant experience to user as the dashboard is never loaded.

[query] 2016/06/09 12:05:37 SELECT _tagKey AS "key", value FROM ep."default"._tags WHERE (_name = 'epdetail') AND (_tagKey = 'experimentId')
[http] 2016/06/09 12:05:51 10.103.178.199 - root [09/Jun/2016:12:05:37 -0700] GET /query?db=ep&epoch=ms&q=show+tag+values+from+epdetail+with+key%3DexperimentId%09 HTTP/1.1 200 2027 http://healthmonitor-860059.lvs01.eaz.ebayc3.com:8080/dashboard/db/guid-delta-treated Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36 26dff14d-2e75-11e6-b4c0-000000000000 13.766275981s

It took almost 20 seconds to execute this template query. Can i give a timeFilter so as to make it run faster ?

**Comment by deepujain** [comment]
Q1: show tag values from epdetail with key=experimentId 

got mapped to

Q2:  SELECT _tagKey AS "key", value FROM ep."default"._tags WHERE (_name = 'epdetail') AND (_tagKey = 'experimentId')


Q1 took < 5 seconds to complete whereas Q2 tool at least 20 seconds. Is something inconsistent ?

**Comment by torkelo** [comment]
template queries only support the "SHOW ..."  style InfluxDB queries. InfluxDB does not support time filters for SHOW queries (meta info queries). 

SELECT queries support time filter. If you use the Grafana Query editor it will add a time range filter so you only fetch the data points for the time range. If you use a manual text

**Comment by torkelo** [comment]
template queries only support the "SHOW ..." style InfluxDB queries. InfluxDB does not support time filters for SHOW queries (meta info queries).

SELECT queries support time filter. If you use the Grafana Query editor it will add a time range filter so you only fetch the data points for the time range. If you use a manual text query it is important that you add WHERE $timeFilter   ,  Grafana will replace $timeFilter with the current time range. 

It also important that you metric query has a GROUP BY time($interval) , with out this you query returns to much data and both InfluxDB will be slow and Grafana. 

The only problem you have that I cannot explain is that you say the template variable query takes 12 seconds:
`show tag values from epdetail with key=experimentId` 

If this takes 12 seconds you should look over you InfluxDB data, that type of query should be very quick. But maybe InfluxDB is too slow for you use case-.
