### ISSUE TITLE
Absolute time range taken as local timezone 

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#53288]
**What happened**:

I like to view dashboards in UTC; my current local timezone is BST.

As you can see in this video, the menu showing Recently Used Absolute Time Ranges is one hour out from the time I get when I pick one.  Worse, it then adds the off-by-an-hour entry at the top of the list.

https://user-images.githubusercontent.com/8125524/182828362-f3759480-66fe-41d5-9bcc-4916ec5d41b8.mp4

I experimented by setting my laptop timezone to EST and the effect shifted by 5 hours.

**What you expected to happen**:

Recently-used time ranges should be in the same timezone as the dashboard view.

**Environment**:
- Grafana version: `v9.1.0-beta1 (947ad8045b)` (run via `docker run grafana/grafana`; image sha 17bf8bd0e7f0.
- Data source type & version: Prometheus (how am I supposed to know the version?)
- OS Grafana is installed on: Linux (Docker Desktop)
- User OS & Browser: macOS Version 11.6.1 (Build 20G224), Google Chrome | 103.0.5060.114 (Official Build) (arm64)
- Grafana plugins: None that I know of
- Others:

**Comment by codeincarnate** [comment]
That's indeed strange behavior and likely not intended, we're taking a look at it.

**Comment by mdvictor** [comment]
Fixed by #53763

**Comment by beeksanalytics** [comment]
Looking in 9.4 and 9.5 this still seems to be a problem

**Comment by beeksanalytics** [comment]
> Fixed by #53763

Not fixed - it's actually fixed here
https://github.com/grafana/grafana/pull/66281
in 10.0

**Comment by felixglow** [comment]
Could this issue be fixed in V9.5.x? Due to certain reasons, we are unable to upgrade to version V10.
