### ISSUE TITLE
[Bug] Templating field does not work

### ISSUE THREAD

**Issue by usdin** [grafana/grafana#5328]
Version 3.0.4
Datasource: Influxdb(proxy)
Influxdb Version: 0.13
Ubuntu 14.04

We created dashboard for telegraf metrics and  defined templates as following
![template](https://cloud.githubusercontent.com/assets/17239584/15956767/5b4feea6-2f08-11e6-885b-c7f61cb9785d.png)

and query as following
![query](https://cloud.githubusercontent.com/assets/17239584/15956772/6758c970-2f08-11e6-925e-e9ef91561d92.png)

It sends following request 

`http://127.0.0.1:3000/api/datasources/proxy/1/query?db=telegraf&q=SELECT%20mean(%22%2F%5Einterrupts%24%2F%22)%20FROM%20%2F%5Ekernel%24%2F%20WHERE%20%22host%22%20%3D~%20%2F%5Ex-pc%24%2F%20AND%20time%20%3E%201465460835s%20and%20time%20%3C%201465460960s%20GROUP%20BY%20time(100ms)%20fill(null)&epoch=ms`
unescaped
`http://127.0.0.1:3000/api/datasources/proxy/1/query?db=telegraf&q=SELECT mean("/^interrupts$/") FROM /^kernel$/ WHERE "host" =~ /^x-pc$/ AND time > 1465460835s and time < 1465460960s GROUP BY time(100ms) fill(null)&epoch=ms`

It doesn't return any result. 

Though after changing query (by toggle edit mode) from
![raw_query1](https://cloud.githubusercontent.com/assets/17239584/15956778/72f0076c-2f08-11e6-984f-b71a71cbef6a.png)

to 
![raw_query2](https://cloud.githubusercontent.com/assets/17239584/15956779/7644fdb4-2f08-11e6-9f5b-247d2504711a.png)

gave correct graph. We've changed `mean("/^$fields$/")` to `mean("$fields") ` and query sent to server was 
unescaped
`http://127.0.0.1:3000/api/datasources/proxy/1/query?db=telegraf&q=SELECT mean("interrupts") FROM /^kernel$/ WHERE "host" =~ /^x-pc$/ AND time > 1465460835s and time < 1465460960s GROUP BY time(100ms) fill(null)&epoch=ms` 

What could be cause behind this, are we missing something?

**Comment by torkelo** [comment]
the templating variable suggestion is just a suggestion, it works for tags that support regex expressions. 

Nothing is stopping from entering just $fields when you click the field value in the query editor:
![image](https://cloud.githubusercontent.com/assets/10999/15961633/0ae69160-2f06-11e6-9979-c871f57a7e1f.png)
