### ISSUE TITLE
[Correction] Docker Beta instead of Stable

### ISSUE THREAD

**Issue by himuura** [grafana/grafana#53295]
Latest tag of docker image deploys v9.1.0-beta1 (947ad8045b). Should be a stable Version not a beta one.

**What happened**:
Updated grafana via docker.
**What you expected to happen**:
Expected a stable version, not a beta one.
**How to reproduce it (as minimally and precisely as possible)**:
Just deploy the latest grafana for docker (grafana/grafana:latest).
**Anything else we need to know?**:
I like you guys =)

**Environment**:
- Grafana version: v9.1.0-beta1 (947ad8045b)
- Data source type & version: N/A
- OS Grafana is installed on: Raspbian / Docker
- User OS & Browser: N/A
- Grafana plugins: I love them all!
- Others: Keep yourself cools in the summer mates, drink plenty of fluids!

**Comment by zuchka** [comment]
please contribute to this thread:

https://github.com/grafana/grafana/discussions/47177
