### ISSUE TITLE
Alerting/Teams: no images in the notification body

### ISSUE THREAD

**Issue by krajster** [grafana/grafana#53299]
**What happened**: 
When sending MS Teams notifications with images (we use external image storage on AWS), the images themselves are not displayed.

**Anything else we need to know?**:
Now channel [teams.go](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/notifier/channels/teams.go#L119) are using a legacy kind of card (MessageCard) (JSON Payload). For the correct display of images in MS Teams, Microsoft recommends using **Adaptive Cards**. Teams Developer Portal includes a tool to design your adaptive cards and test directly in Teams. It can be accessed at https://dev.teams.microsoft.com/cards.

In attachment - example JSON with correct displayed image ([webhook_teams_image.zip](https://github.com/grafana/grafana/files/9259342/webhook_teams_image.zip)).

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: Influx
- OS Grafana is installed on: docker

**Comment by zuchka** [comment]
Thanks for creating this issue, @krajster

This is a known issue and we believe the bug is on the MS Teams side. Please see this thread for more details:

https://github.com/grafana/grafana/discussions/38030#discussioncomment-3279629

**Comment by krajster** [comment]
No, the problem is that the new Adaptive Cards format must be used to display the images. An example of such a format is in the attachment that I added. 

_What I see now in Teams notifications_
![image](https://user-images.githubusercontent.com/8490440/183005430-4ba3f02b-4149-41ce-920b-255d5afbec9a.png)


_And if use Adaptive Cards, the images are displayed:_
![image](https://user-images.githubusercontent.com/8490440/183004822-a0783996-b3f2-4b4c-b74b-1539448233a6.png)

**Comment by krajster** [comment]
I have an answer from Microsoft:
**I understood that you are facing an issue displaying an image from Webhook connector in Teams. I’ve analyzed the JSON payload and I noticed that you are using a legacy kind of card (MessageCard) - [Legacy actionable message card reference - Outlook Developer | Microsoft Docs](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference).

I suggest looking on Adaptive Cards as they are the recommended card for Teams Development:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards#adaptive-cards
https://docs.microsoft.com/en-us/adaptive-cards/

Teams Developer Portal includes a tool to design your adaptive cards and test directly in Teams. It can be accessed at https://dev.teams.microsoft.com/cards**

**Comment by krajster** [comment]
Alerting: Use Adaptive Cards in Teams notifications #53532
