### ISSUE TITLE
Grafana specifies invalid GROUP BY time when repeating panels

### ISSUE THREAD

**Issue by MatMeredith** [grafana/grafana#5330]
I have a panel which correctly charts a value (based on data in InfluxDB).   When I configure the panel to repeat over a template variable which contains the set of nodes reporting this value, the panel starts failing with the following error:
{
  "error": "error parsing query: found y, expected ) at line 1, char 136",
  "message": "error parsing query: found y, expected ) at line 1, char 136"
}

It appears that this is because the query it is issuing has a GROUP BY time(1y) in  it:
	SELECT mean("value") FROM "Latency WHERE "node" =~ /^MyNode$/ AND time > 1465513200s and time < 1465599600s GROUP BY time(1y) fill(null)

Presumably InfluxDB is objecting to the y specifier, but Grafana shouldn't even be specifiying 1y as the GroupBy -- the time range we're querying over is just "today".

Latest version of Grafana installed a few days ago -- I can't find the version number anywhere in the UI...

**Comment by torkelo** [comment]
panel repeats require a that the Min Span option is also set, (panel general tab). 
This should be required (or have default), but that has not been fixed yet (open issue for that)
