### ISSUE TITLE
Explore: investigate potential memory leaks

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#53310]
https://raintank-corp.slack.com/archives/CKF4X4H1D/p1658236452772189

**Comment by dannykopping** [comment]
Hey @Elfo404 

https://user-images.githubusercontent.com/373762/183370842-ba640ac0-66db-4f3e-a5fe-327eca7b6959.mp4

As discussed on Slack, I'm seeing clear evidence of a memory leak; the above video hopefully demonstrates that.
I'm using v9.2.0-42f9a6e6pre (42f9a6e67) on Ubuntu 22.04, running Chrome 103.0.5060.134 (Official Build) (64-bit)

**Comment by dannykopping** [comment]
If I were to guess, I'd say there's some issue displaying and reusing a large number of series.

**Comment by leeoniya** [comment]
repro link, e.g.:

https://ops.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22000000134%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.99,%20sum%20by%28le,%20pod%29%20%28rate%28cortex_request_duration_seconds_bucket%7Bcluster%3D~%5C%22prod-eu-west-0%5C%22,%20job%3D~%5C%22%28cortex-dedicated-12%29%2F%28%28gateway%7Ccortex-gw%7Ccortex-gw-internal%29%29%5C%22,%20route%3D~%5C%22api_%28v1%7Cprom%29_push%5C%22%7D%5B$__rate_interval%5D%29%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D

**Comment by leeoniya** [comment]
locally reproducible by data refreshing this page:

http://localhost:3000/explore?orgId=1&left=%7B%22datasource%22:%22PD8C576611E62080A%22,%22queries%22:%5B%7B%22scenarioId%22:%22random_walk%22,%22refId%22:%22A%22,%22seriesCount%22:10%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by Elfo404** [comment]
reopening to keep track of https://github.com/grafana/grafana/pull/53872#issuecomment-1219416593

**Comment by leeoniya** [comment]
i think this one should stay closed, since the re-init issue no longer causes leaks, fixing that would just be a perf improvement.
