### ISSUE TITLE
Can't open 8.5.5 and 8.5.4 release notes on grafana docs page

### ISSUE THREAD

**Issue by astafan8** [grafana/grafana#53311]
**What happened**: I wanted to read release notes for grafana version 8.5.5 and 8.5.4 but the pages would redirect me to the general release notes page instead.

**What you expected to happen**: pages with notes for versions 8.5.5 and 8.5.4 would open and i could read what's in those releases.

**How to reproduce it (as minimally and precisely as possible)**: go to this url https://grafana.com/docs/grafana/latest/release-notes/ and try to press these links:
![image](https://user-images.githubusercontent.com/15662810/182865705-2f463947-ac93-4fa9-a8d0-f7a71feef893.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
yep, looks like [Release notes for 9.0.0-beta1](https://grafana.com/docs/grafana/latest/release-notes/) is also not adding the subheader tag. Thanks for pointing this out, @astafan8

**Comment by astafan8** [comment]
@zuchka looks like it is fixed now, thank you!
