### ISSUE TITLE
[Feature request] Hide columns in native Table plugin 

### ISSUE THREAD

**Issue by DagW** [grafana/grafana#5332]
I am using Time Series Aggregation to show Metrics with the highest current values in the Table panel.
It would be nice to be able to hide or rename columns so the sort data does not have to be visible in the dashboard.

A predefined ordering by Aggregation would also be nice.

"Metric" -> "Latest X"
"Current" -> hidden

![table](https://cloud.githubusercontent.com/assets/289691/15962262/02ef25b8-2f0a-11e6-98ce-66fdd65874df.png)

**Comment by torkelo** [comment]
good idea, will close as it is the same as this feature request, https://github.com/grafana/grafana/issues/3551
