### ISSUE TITLE
Second datasource picker is missing when using "Split" functionality.

### ISSUE THREAD

**Issue by eamonryan** [grafana/grafana#53332]
**What happened**:
I had a query open in Explore and selected "Split".
The datasource picker for the right-hand pane was entirely missing.

**What you expected to happen**:
I should be able to select the datasource for the right-hand pane.

**How to reproduce it (as minimally and precisely as possible)**:
- Install Grafana 9.0.6.
- Open the Explore page.
- Click "Split".
- Notice there is no datasource picker visible for the right-hand pane.

**Anything else we need to know?**:
I rolled back to 9.0.5 but saw the same issue.
I rolled back to 9.0.4 and upon a refresh of the already-opened split pane, the second datasource picker returned.

**Environment**:
- Grafana version: 9.0.6
- Data source type & version: Any
- OS Grafana is installed on: Linux (Docker/Kubernetes)
- User OS & Browser: Firefox 103.0 for Ubuntu

Screenshots (just refreshing between each one after swapping the version underneath):
9.0.6:
![image](https://user-images.githubusercontent.com/11842311/182958637-975be234-5cdf-4822-b69b-0e036fd32ae1.png)

9.0.5:
![image](https://user-images.githubusercontent.com/11842311/182958655-2265d2c2-7a96-4b50-a506-3bac7189c9e1.png)

9.0.4:
![image](https://user-images.githubusercontent.com/11842311/182958677-56ac690c-0412-452a-8789-5415559eb38f.png)

**Comment by gelicia** [comment]
Fixed by #53285
