### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ncauchois** [grafana/grafana#53349]
## What happened :

I create an alert and the memory consumption increases a lot because of the PromQL evaluation of the alert.

## What you expected to happen :

I expected to have a memory consumption equivalent to the PromQL evaluation in explore feature.

### Step 1 : Evaluation in "explore" tab

Click on the "explore" tab.

Run some query like `{namespace="caascad-monitoring"}` for a period of 15 minutes.

Check memory consumption of Grafana. In our case : 180MB.

### Step 2 : Evaluation for an alert

Click on the "alerting" tab and "New alert rule".

Set the same query and alert condition `{namespace="caascad-monitoring"}` for a period of 15 minutes.

Check memory consumption of Grafana. In our case : 1.61GB.

## Environment :
- Grafana version: 9.0.2
- Data source type & version: Prometheus (using the built-in datasource)
- OS Grafana is installed on: Kubernetes with chart grafana from https://grafana.github.io/helm-charts
- User OS & Browser: Ubuntu 20.04 / Chrome
- Grafana plugins: no additional plugins
- Others: -

**Comment by armandgrillet** [comment]
How much data is being queried? How many data points? How many dimensions? This issue is probably is due to how we cache the last evaluations. An engineer will investigate this.

**Comment by grobinson-grafana** [comment]
Hi! 👋 Like Armand said it would be interesting to know the number of dimensions and the volume of data that is being returned. You can run Grafana with profiling (use `-profile`), take a sample of the heap via the debug server (http://127.0.0.1:6060/debug/pprof/), and then visualize the heap as a flame graph with `go tool pprof -http=:8082 heap.out`.

**Comment by grobinson-grafana** [comment]
Hi! I am going to close this issue as we haven't heard back. If this issue still persists in the latest version of 9.x please feel free to re-open it with some profiling data if possible.
