### ISSUE TITLE
Alert stay's in "firing/alerting" state

### ISSUE THREAD

**Issue by vesemmat** [grafana/grafana#53341]
**What happened**: I have set up alert rule where if the query value is above 0 then send alert. Alert is triggered, however the state of the alert stays in "firing/alerting" and will not go back to OK when whe query =0. 

Alert state will go back to the OK state only after editing the evaluation settings and saving the alert rule (without any changes)

**What you expected to happen**: Alert state should be reset to OK state when there is no longer specification for alerting.

**How to reproduce it (as minimally and precisely as possible)**:
Set up ElasticSearch Data source, and alert rule which will query, if some value is >0 send alert to MS teams.
Each time that value will be >0 I would expect alert notification.
**Anything else we need to know?**:
We want to upgread from Grafana v6.7.1 to 9.0.4 and this is blocking us. (in the version 6.7.1 is working as expected)
**Environment**:
- Grafana version: 9.0.4
- Data source type & version: Elasticsearch v 8.3.2
- OS Grafana is installed on: Red Hat Enterprise Linux release 8.6 (Ootpa
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: NA
- Others:

**Comment by vesemmat** [comment]
Hi @usmangt ,
no, we are moving directly from version 6.7.1. 
We have installed Grafana version 9.0.6 as new/fresh installation just for the case to test the alerting if it will work for us as on previous version...

**Comment by usmangt** [comment]
Hi @vesemmat,

Thanks for the reply. So if you see this issue on the new fresh installed version 9.0.x Can you please try to reproduce the issue on https://play.grafana.org ? as there we have Elasticsearch configured as a datasource.

**Comment by gabor** [comment]
hi @vesemmat i was unable to reproduce the problem with grafana 9.0.4 and elasticsearch 8.3.2.
maybe @grafana/alerting-squad has some ideas about an alert getting "stuck" in the firing-state even when the values goes down?

**Comment by vesemmat** [comment]
Hi @usmangt 
yes I will try reproduce the issue on https://play.grafana.org/. However I cannot see any datasource with some regular traffic of data. Is there way to increase the regular traffic for example on the FLight traffic datasource?

Thank you!!

**Comment by yuri-tceretian** [comment]
Hi @vesemmat. Can you please provide more info about the alert rule you created? I am interested in the following settings:
1. Evaluation interval.
2. `For` parameter
3. Mapping of NoData and Error state.
4. The status of the alert rule. Screenshot or (better) the dump of API response.
5. Query. 

Then, you can enable debug logging and, and look for logger=ngalert that mentions the UID of the rule you are investigating. There will be logs of the evaluation results that you can check.

**Comment by vesemmat** [comment]
Hi, thanks for the reply.
1) 30s 1m
2) for 1m
3) default set up - no data= No Data, Alert=Alerting
4) status is Alerting/Firing 
5) HTTP-SC: 500
![image](https://user-images.githubusercontent.com/110670543/185879247-fe2cbb95-3957-423d-8595-53964378f506.png)

**Comment by yuri-tceretian** [comment]
@vesemmat I guess that you meant `Error=Alerting` instead of Alert=Alerting. I wonder if it is alerting because of the error. 
- What does Grafana return when you click the button `Preview alerts`? 
- Did you find anything useful in the logs?

**Comment by vesemmat** [comment]
Hello,
This is the Preview alerts
![image](https://user-images.githubusercontent.com/110670543/186425632-0ea2d43b-93b4-41c8-a31d-ce8b826fcb8f.png)

**Comment by vesemmat** [comment]
I have tried this setup as in screenshot below, alert was triggered but still stays in the same status "Alerting/firing" (still the same behaviour)
![image](https://user-images.githubusercontent.com/110670543/186427493-2c576a20-d27b-4c9a-b3db-69e5dde45ca2.png)

**Comment by vesemmat** [comment]
I think I have the same issue as described here https://stackoverflow.com/questions/58729080/how-to-reset-alerting-state-in-grafana

**Comment by yuri-tceretian** [comment]
@vesemmat, the article at StackOverflow mentions legacy alerting but what I see on your screenshots is Grafana 8 Alerting which was introduced in Grafana 8 and replaced the legacy one. Those two engines are quite different, they execute rules differently. 

I believe that your situation is different: I took a look at your rule and realized that the condition might not be what you want to achieve:
your rule queries Elasticsearch and then counts the number of **data points** in the response, not the value of that data point. Elasticsearch will always return at least one data point with value 0, which I believe is not what you want to achieve.

If you want to alert if there are at least one 500 in the interval of the query then you need to use `sum()` function in the expression `B`
