### ISSUE TITLE
[Feature Request] Support verification of TLS certificates for data proxy

### ISSUE THREAD

**Issue by simonpasquier** [grafana/grafana#5334]
IIUC the data proxy disables globally the verification of the TLS certificates [1]. It would be nice to make it configurable for people that care about validating certificates.

[1] https://github.com/grafana/grafana/blob/aef2b6b45fd9c82e08d2b1271256d1426b7fcce3/pkg/api/dataproxy.go#L21

**Comment by bergquist** [comment]
Fixed by https://github.com/grafana/grafana/pull/9377
