### ISSUE TITLE
keys/labels with dot in the name can't be used with alert templating

### ISSUE THREAD

**Issue by killafunkinmofo** [grafana/grafana#53358]
I'm using elasticsearch datasource, I have several fields with . in the name. Like "core.value". When I use the alert templates $labels.core.value this does not work.  In go templating you can do something like {{ index $labels "core.value" }}. But it seems like the label templating isn't necessarily a full go templating system, because it doesn't evaluate it with index.

I'm on version 9.0.4

When I do preview alerts these are the values that it shows for my queries:
`[ var='B' labels={metricId=1, netflow.ipv4_dst_addr=1.2.3.4, netflow.l4_dst_port=443, netflow.protocol=TCP} value=1045.6294223333334 ], [ var='C' labels={metricId=1, netflow.ipv4_dst_addr=1.2.3.4, netflow.l4_dst_port=443, netflow.protocol=TCP} value=0 ]`

**Comment by river-kang** [comment]
I experienced the same issue when I want to refer labels in one of Alert's annotation.

In my case, the reference is done like  {{ $labels.resource.label.stream_id }} where whole valuestring looks like [ var='B' labels={.... resource.label.stream_id=my-stream, resource.type=[datastream.googleapis.com/Stream} value=-10 ]

**Comment by killafunkinmofo** [comment]
> I experienced the same issue when I want to refer labels in one of Alert's annotation.
> 
> In my case, the reference is done like {{ $labels.resource.label.stream_id }} where whole valuestring looks like [ var='B' labels={.... resource.label.stream_id=my-stream, resource.type=[datastream.googleapis.com/Stream} value=-10 ]
> 
> The annotation refencing the label looks lik <img alt="image" width="498" src="https://user-images.githubusercontent.com/97935869/183351505-f26fc8af-ae67-4ba1-bad9-1033945f6490.png">

That is what I try, unless I am missing that you are doing something different. 

Label:
my_label: {{ $labels.netflow.ipv4_dst_addr }}

Output:
my_label: <no value>

This label is auto added to the alert:
netflow.ipv4_dst_addr=1.2.3.4

The labels is there, I just can't seem to use it in a templated string.

**Comment by mellieA** [comment]
Depending on the type of condition you're using, the way to access the label will be different. 

The variable maps are described here: https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#variables 

for a classic condition, here's an example: 
{{ index $values.B0.Labels "netflow.ipv4_dst_addr" }}

![Screen Shot 2022-08-15 at 6 15 21 PM](https://user-images.githubusercontent.com/18175287/184757325-4cf2869a-46c5-4fbc-afab-03033961fd06.png)


if your alert has two or more conditions or an expression, then you can use the $labels variable: 
{{ index $labels "netflow.ipv4_dst_addr" }}

![Screen Shot 2022-08-15 at 6 11 25 PM](https://user-images.githubusercontent.com/18175287/184757033-9bf2e545-0c5d-4fd9-9f59-69f93f0062d6.png)

This question has come up before [here](https://github.com/grafana/grafana/issues/51184#issuecomment-1162973417) so I'm adding this issue to the docs squad to see if it's something that would be valuable to add.

**Comment by killafunkinmofo** [comment]
> Depending on the type of condition you're using, the way to access the label will be different.
> 
> The variable maps are described here: https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#variables
> 
> for a classic condition, here's an example: {{ index $values.B0.Labels "netflow.ipv4_dst_addr" }}
> 
> ![Screen Shot 2022-08-15 at 6 15 21 PM](https://user-images.githubusercontent.com/18175287/184757325-4cf2869a-46c5-4fbc-afab-03033961fd06.png)
> 
> if your alert has two or more conditions or an expression, then you can use the $labels variable: {{ index $labels "netflow.ipv4_dst_addr" }}
> 
> ![Screen Shot 2022-08-15 at 6 11 25 PM](https://user-images.githubusercontent.com/18175287/184757033-9bf2e545-0c5d-4fd9-9f59-69f93f0062d6.png)
> 
> This question has come up before [here](https://github.com/grafana/grafana/issues/51184#issuecomment-1162973417) so I'm adding this issue to the docs squad to see if it's something that would be valuable to add.

Thanks for suggesting index even though I already mentioned I tried it.  It made me try again.
My attempt was {{ index $labels 'netflow.ipv4_dst_addr' }} - which doesn't work and still doesn't work. 
I copied your first example to see if it worked any different `{{ index $values.B0.Labels "netflow.ipv4_dst_addr" }}` - which works.

So I think the conclusion may be that` {{ index $labels` ... doesn't work and can only be used with $values.

**Comment by mellieA** [comment]
I'm glad it worked for you with $values. I'll add more info here for our tech writers and other users searching: 

For an alert using a classic condition, like the one shown here, you'll want to use index with $values. Does that align with what you saw?

![Screen Shot 2022-08-16 at 3 35 59 PM](https://user-images.githubusercontent.com/18175287/184989632-1bf2c1f9-280b-4479-b1c1-68c66cb03b95.png)

**Comment by killafunkinmofo** [comment]
> I'm glad it worked for you with $values. I'll add more info here for our tech writers and other users searching:
> 
> For an alert using a classic condition, like the one shown here, you'll want to use index with $values. Does that align with what you saw?
> 
> ![Screen Shot 2022-08-16 at 3 35 59 PM](https://user-images.githubusercontent.com/18175287/184989632-1bf2c1f9-280b-4479-b1c1-68c66cb03b95.png)

Yes. I wasn't actually using classic condition though. so I replaced your B0 with B. 

I'm using these expressions:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/12109203/184990605-7aac3087-f4ba-4ee7-a596-0004f717b273.png">

**Comment by gguillotte-grafana** [comment]
@mellieA Can you please clarify @killafunkinmofo's last point re: needing `$values` but not using the Classic condition operation? I'll try to clarify the docs accordingly in the meantime.

**Comment by gguillotte-grafana** [comment]
> | $labels | The labels from the query or condition. For example, `{{ $labels.instance }}` and `{{ $labels.job }}`. This is unavailable when the rule uses a [classic condition]({{< relref "../../alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule" >}}).
> | $values | The values of all reduce and math expressions that were evaluated for this alert rule. For example, `{{ $values.A }}`, `{{ $values.A.Labels }}` and `{{ $values.A.Value }}` where `A` is the `refID` of the reduce or math expression. If the rule uses a classic condition instead of a reduce and math expression, then `$values` contains the combination of the `refID` and position of the condition.

Specifically, I'm not sure what in the above from https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#variables is missing - it states `$labels` "is unavailable when the rule uses a classic condition". Is there another circumstance where `$labels` is not available, causing @killafunkinmofo's issue?

**Comment by klubi** [comment]
@gguillotte-grafana does your last comment mean we can't, at all, put prometheus metrics labels into messages when classic condition is used?
Or there is a way, but it's not documented anywhere?
I have hard times understanding documentation wording around this issue.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

It sounds like there is some confusion about how Classic Conditions work.

In Grafana there are two kinds of alert rule. These are known as multi-dimensional and uni-dimensional (also sometimes refered to as single dimensional).

A multi-dimensional alert rule can have more than one firing alert at the same time. A uni-dimensional alert rule on the other hand can have just one firing alert at the same time (hence uni).

In Grafana, all alert rules are multi-dimensional unless the condition of the rule is a Classic Condition. Classic Conditions make alert rules uni-dimensional by removing labels from queries such that the only labels remaining are the inherited labels (such as alertname) and any custom labels that are in the rule definition. Classic Conditions do this to ensure the rule cannot have more than one firing alert at a time.

If you want to be able to use $labels then you probably should not be using Classic Conditions, and instead should consider using multi-dimensional alerting.

That said, you can still see which labels exceeded the conditions in the Classic Condition using $values or the value string, but the labels are not added to the alert to enforce uni-dimensional behavior.
