### ISSUE TITLE
[BUG] Google Auth - Login Failed

### ISSUE THREAD

**Issue by mdzidic** [grafana/grafana#5335]
* **I'm submitting a ...**
- [ x ] Bug report

- What Grafana version are you using?
3.0.4

- What did you do?
Enabled Google Auth with "allowed_domains" option.

- What was the expected result?
Filter Google Logins per domain.

- What happenend instead?
We have Google Apps and our emails are under our own domain, when I try to login with my Google Account I receive message from Grafana (without allowed_domains I can login normally):

**Login Failed**
Required email domain not fulfilled

**Comment by torkelo** [comment]
just tested this and it works fine for me. 

Specified:
 `allowed_domains = raintank.io`

Then I could login with raintank.io address but not my personal gmail address.

**Comment by mdzidic** [comment]
How can I debug this?

**Comment by torkelo** [comment]
Could build from source and add logging calls around the domain filtering logic

**Comment by mdzidic** [comment]
Hello,

When I disable `allowed_domains` I can login without any problems, but when I go to my Profile, fields Email and Username are empty. Is that normal?
