### ISSUE TITLE
mixed datasource dropdown list not appear on click

### ISSUE THREAD

**Issue by ouinouin** [grafana/grafana#53353]
**What happened**:
while selecting the mixed datasource on each query i create, i cannot select the datasource in the dropdown list 
**What you expected to happen**:
while selecting the mixed datasource you can then create a query  and select for each query which datasource you want to select
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
tried this on chromium and firefox on versions 9.0.1 to 9.0.6 (docker image oss alpine)
**Environment**:
- Grafana version: 9.0.1 9.0.6
- Data source type & version: influxdb datasources /mixed datasources
- OS Grafana is installed on: docker X86
- User OS & Browser: chromium and firefox esr102 / ubuntu
- Grafana plugins:
- Others: on the attached picture we see that I cannot select anything from the query  2 and 3, it remains as the default choice with no way to click on it and make the list of queries appear.
![2022-08-06_16-18](https://user-images.githubusercontent.com/6713759/183252806-65d5dd12-840e-462a-8095-4fc786f754a4.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @ouinouin 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by ouinouin** [comment]
@zuchka , good catch , i couldnt reproduce the issue in play.grafana.org , the behavior is normal.
I ll try with a fresh install though.

**Comment by ouinouin** [comment]
I fixed the behavior by restarting grafana without grafana.db and restarting again with reimplementin grafana.db , unsure if there is some logic behind this.
