### ISSUE TITLE
Transform: Rename by regex not working

### ISSUE THREAD

**Issue by EasyThe** [grafana/grafana#53362]
**What happened**: Rename by regex doesn't work anymore. A regex expression “{.*” that I was using previously worked flawlessly. 
The data names come like this from Prometheus:
```
guilds{instance="localhost:9284", job="thothbot"}
old_stats{instance="localhost:9284", job="thothbot"}
slash_stats{instance="localhost:9284", job="thothbot"}
```

**What you expected to happen**: The names to change from `guilds{instance="localhost:9284", job="thothbot"}` to `guilds`, a.k.a. to remove everything after the {

**How to reproduce it (as minimally and precisely as possible)**: Try renaming with regex

**Anything else we need to know?**: I do not remember what the version of the Grafana was when the “Rename by regex” worked but since June 2022 it has been broken.

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: 
- OS Grafana is installed on: Grafana Cloud (Linux?)
- User OS & Browser: Windows 10 Pro, Google Chrome 103.0.5060.134 (Official Build) (64-bit)
- Grafana plugins:
- Others: hosted here: https://thothbot.grafana.net/
- Screenshot with transformation input & output 
![image](https://user-images.githubusercontent.com/1358923/183309146-436e552a-4fa6-49cc-8c29-3f5c8211b36c.png)

**Comment by ashharrison90** [comment]
hi @EasyThe 👋 

this was a breaking change we released in 9.0.0, see the `Release notes breaking changes` section here: https://github.com/grafana/grafana/pull/48179

you will get the same behaviour by changing your regex expression from `{.*` to `/{.*/`

hope that helps! 😄

**Comment by AndreKR** [comment]
I think the [docs for Rename by regex](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#rename-by-regex) should really mention that the regex has to be surrounded by slashes to work properly. Unlike in programming code, when you have an input field for a regex it is relatively common that you do not have to type the delimiters.

While this GitHub issue is currently the _second_ Google result for "grafana rename by regex not working", I first looked at the docs which actually contain an (outdated) example without the delimiters. What _further_ adds to the confusion is that if you do enter a regex without delimiters, it still kind of works, probably for backwards compatibility, but it works as if it had been entered with `^` and `$` at the start and end.

**Comment by imatwawana** [comment]
> I think the [docs for Rename by regex](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#rename-by-regex) should really mention that the regex has to be surrounded by slashes to work properly. Unlike in programming code, when you have an input field for a regex it is relatively common that you do not have to type the delimiters.
> 
> While this GitHub issue is currently the _second_ Google result for "grafana rename by regex not working", I first looked at the docs which actually contain an (outdated) example without the delimiters. What _further_ adds to the confusion is that if you do enter a regex without delimiters, it still kind of works, probably for backwards compatibility, but it works as if it had been entered with `^` and `$` at the start and end.

We've updated the docs on PR #86627
