### ISSUE TITLE
i can't save and test

### ISSUE THREAD

**Issue by TaiGiap** [grafana/grafana#53365]
I configure prometheus on Grafana to monitor them
![image](https://user-images.githubusercontent.com/110224102/183345690-58caf805-12d7-4e29-bb24-6effb70d7c1a.png)
But when i press save and test this problem occurs. I taught myself how to use prometheus and grafana so I don't know how to fix them. please help me and tks for that
![image](https://user-images.githubusercontent.com/110224102/183345588-637ffa0d-02e3-402d-8f6f-99e53eebdb4e.png)

**Comment by MattKobayashi** [comment]
Looks to me like you're pointing Grafana at your Node Exporter instance instead of Prometheus itself. Check the port that Prometheus is listening on and ensure you're pointing Grafana at that port (I believe it's 9090 by default).

**Comment by TaiGiap** [comment]
> Looks to me like you're pointing Grafana at your Node Exporter instance instead of Prometheus itself. Check the port that Prometheus is listening on and ensure you're pointing Grafana at that port (I believe it's 9090 by default).

tks u for comment but if i set 9090, it will show this error
![image](https://user-images.githubusercontent.com/110224102/183793675-95ceddb8-a9ce-48e8-a0eb-caaf75b586e4.png)

**Comment by MattKobayashi** [comment]
Have you installed Prometheus itself? Can you access the Prometheus web interface? If not, I'd suggest troubleshooting your Prometheus installation.
