### ISSUE TITLE
[Feature Request]: Double Click Panel Title for Full Screen Panel View

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#5336]
It would find it handy if viewing a panel in fullscreen (or the edit view, I don't have an opinion on that) was triggered by double clicking the the title of the panel. Currently it is click - move mouse - click.

**Comment by digrich** [comment]
+1

**Comment by mitjaziv** [comment]
https://github.com/grafana/grafana/pull/7727

**Comment by torkelo** [comment]
I do not think this is needed now that we have keyboard bindings `v` and `e` to enter/toggle edit and view mode
