### ISSUE TITLE
Variables - No way to go back to the variable list in dashboard settings. 

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#53363]
**Steps to reproduce**: Open a dashboard. Go to Dashboard settings, click variables, click one variable. Now, try to go back to the variables list. There is no way to go back to the variables list. There is no back button inside the variable edit. If the user clicks the browser back button, user is taken back to thr General settings. If user clicks the arrow on the top left, user is taken back to the dashboard. 

**Actual Result**:
There is no way to go back to the variables list, without clicking into some other item on the settings, then clicking variables again. 

Please consider adding a back button to go back from a variable edit screen to the variable list screen. 

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**: 
- Grafana version: 9.0.6
- Data source type & version: InfluxDB 1.8
- User OS & Browser: Windows. Firefox

**Comment by usmangt** [comment]
Hi @yurividal,

Thanks for providing the details.

I tried to reproduce it based on your provided steps but for me, it seems to work fine.
Once I click on any variable, I can still go back by clicking the "<-" button link on the top left corner.

![image](https://user-images.githubusercontent.com/69509548/184158981-b96f5225-c90a-4663-a8bd-974014627d9e.png)


Can you try to reproduce this same case on https://play.grafana.org/

**Comment by yurividal** [comment]
when i click on a variable to edit it, and then click the <- on top of the page, it takes me straight back to the dashboard, not to the variable list. just tested in play.grafana.org too.

**Comment by usmangt** [comment]
Hey @yurividal,

Thanks, now I was also able to reproduce it on my test machine using.

Grafana Ver: 9.0.3
Google Chrome Version 104.0.5112.79 (Official Build) (64-bit)

I will now forward it to our team so that they can investigate further.

**Comment by natellium** [comment]
Hey @yurividal, thanks for raising this! 

This is actually part of larger navigation issue and we're working on solving this as part of our next navigation project iteration https://github.com/grafana/grafana/issues/50791. More specifically by introducing breadcrumbs so users can move between levels more easily.

I will close this issue as we won't work on this as an isolated bug but as part of the project I mentioned :)
