### ISSUE TITLE
Grafana crashed when setting the first alert rule

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [grafana/grafana#53364]
**What happened**:
I'm new to grafana, so I didn't touch any other configurations except for `[security]` (which in order to set a initializing password) and `[server]` (which in order to set a initializing server port). Grafana is running well for about a month, and no error occurs, so I think I have nothing wrong to my setting.

While I'm going to set a new alert rule, by clicking `New Alert Rule` button, it is normal to acceess the configuration page.

![image](https://user-images.githubusercontent.com/58684828/183331020-4ebfbd7d-4c5c-4333-9140-b56bf49397af.png)

But I didn't finish the configuration due to some other things, and I closed that page.

Unfortunately, when I tried to open that page again, grafana will never show that configuration page, instead of continuing request that page and getting an error tip, then repeat that move immediately so that I can hardly see that error.

the error page is like this
![image](https://user-images.githubusercontent.com/58684828/183330073-74858b6b-184b-4df6-a9e0-041d35be61bc.png)
and here is part of the log when grafana repeating request and failed:
```
logger=context traceID=00000000000000000000000000000000 t=2022-08-08T10:48:38.810754552+08:00 level=error msg="Failed to look up user based on cookie" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-08-08T10:48:38.810893297+08:00 level=error msg= error="context canceled" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-08-08T10:48:38.810965759+08:00 level=info msg="Request Completed" method=GET path=/alerting/new status=403 remote_addr=192.168.0.13 time_ms=0 duration=348.184?s size=47 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:38.857686837+08:00 level=error msg="Failed to get settings" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:38.857818376+08:00 level=error msg="Request Completed" method=GET path=/alerting/new status=500 remote_addr=192.168.0.13 time_ms=1 duration=1.950331ms size=1349 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:38.930173573+08:00 level=error msg="Failed to get settings" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:38.930352446+08:00 level=error msg="Request Completed" method=GET path=/alerting/new status=500 remote_addr=192.168.0.13 time_ms=3 duration=3.553053ms size=1349 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.034757353+08:00 level=error msg="Error from access control system" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.034873902+08:00 level=error msg="Failed to get settings" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.034999086+08:00 level=error msg="Request Completed" method=GET path=/alerting/new status=500 remote_addr=192.168.0.13 time_ms=3 duration=3.736655ms size=1349 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 t=2022-08-08T10:48:39.054748178+08:00 level=error msg="Failed to look up user based on cookie" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-08-08T10:48:39.054853968+08:00 level=error msg= error="context canceled" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-08-08T10:48:39.054940897+08:00 level=info msg="Request Completed" method=GET path=/alerting/new status=403 remote_addr=192.168.0.13 time_ms=0 duration=457.378?s size=47 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.185626447+08:00 level=error msg="Failed to get settings" error="context canceled"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.185756661+08:00 level=error msg="Request Completed" method=GET path=/alerting/new status=500 remote_addr=192.168.0.13 time_ms=4 duration=4.118019ms size=1349 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.203982642+08:00 level=error msg= error="context canceled" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-08T10:48:39.204058298+08:00 level=info msg="Request Completed" method=GET path=/alerting/new status=403 remote_addr=192.168.0.13 time_ms=1 duration=1.406502ms size=47 referer=http://192.168.0.200:8065/alerting/new?chunkNotFound traceID=00000000000000000000000000000000
```

**What you expected to happen**:
How to figure out what is going wrong, and how to fix it.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know how to reproduce that problem again, this is a sudden crash...maybe due to a vpn change. The first time I entered the configuration page successfully, I was using vpn proxy, then I closed that page. And I never get chance to open that page again afterwards.

**Anything else we need to know?**:
It is a simple singleton start of Grafana started from binary package, unzip by `tar -zxvf xxx.tar` and started by `nohup grafana-server web &`

**Environment**:
- Grafana version: v9.0.4
- Data source type & version: default sqlite in default configuration
- OS Grafana is installed on: CentOS Linux release 7.8.2003
- User OS & Browser: Win10 & chrome
- Grafana plugins: none
- Others:

**Comment by WilliamChen-luckbob** [comment]
problem soved when I reopen my vpn and connect to the same endpoint. The page was accessable again, and then I clicked cancel button to exit that page. The Grafana come back to normal and I can visit that configuration page again.... I don't know if there is some strategy to hold my visiting cache, and lead to that problem....

**Comment by anthosz** [comment]
On my side, Grafana crash every time I want to delete/edit/create alert/template/contact points/policies (all alerting stuff), I can only read but not write since upgrade to v9.0.6

Example when editing a template:
After 30s (timeout set to 3min on the reverse proxy / it worked well with Grafana v9.0.2):
![image](https://user-images.githubusercontent.com/14294064/183377866-c9f82546-34e6-4287-a2e3-2a3f5c4d6049.png)

Nothing in the logs and Grafana crash.

**Comment by usmangt** [comment]
Hi @WilliamChen-luckbob,

glad to hear that you found the solution. I will close this issue.

@anthosz for you issue, it seems somewhat similar to https://github.com/grafana/grafana/issues/53357

Can you please check if this is the case OR create a new issue if does not match.
