### ISSUE TITLE
Grafana UI: Lazy loading libs in CodeEditor doesn't work in custom panel plugin

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#53372]
**What happened**:

When lazy loading libs in the CodeEditor, the libs don't load/show.
![image](https://user-images.githubusercontent.com/39485579/183366723-f91b486a-2228-4e02-97ec-42f59a4504a2.png)

**What you expected to happen**:

Lazy loading libs should load the libs.
![image](https://user-images.githubusercontent.com/39485579/183366862-480e7f6b-bf41-4e1e-a177-6fd26e34ac97.png)

**How to reproduce it (as minimally and precisely as possible)**:

Repo: https://github.com/ZuperZee/zuperzee-bug1-panel/tree/51a6eed6cf49b616c1a43fb610b6f578cc68b7df

Add the panel plugin
Create a panel with the added panel plugin in Grafana
Type `nice` (niceCar should be suggested) in the CodeEditor option in edit mode

go to `src/EditorOption.tsx` and edit the setTimeout timeout to 0
Typing `nice` should show niceCar and niceTruck

**Anything else we need to know?**:

Seems like there was a bug (https://github.com/microsoft/monaco-editor/issues/2866) from https://github.com/microsoft/monaco-editor which was fixed in v0.32.0.

**Environment**:
- Grafana version: v9.0.6
- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu 22.04.1
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @ZuperZee 

is this issue specific to your own panel plugin? do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by ZuperZee** [comment]
This is a panel plugin issue. I made a "base" plugin following the https://grafana.com/tutorials/build-a-panel-plugin/ guide. Then added the CodeEditor component from the https://www.npmjs.com/package/@grafana/ui package.

The https://github.com/ZuperZee/zuperzee-bug1-panel/tree/51a6eed6cf49b616c1a43fb610b6f578cc68b7df is just a panel plugin to showcase the bug. Not a real panel plugin.

Not sure how it can be replicated on https://play.grafana.org/.

**Comment by ZuperZee** [comment]
The main issue is this part https://github.com/ZuperZee/zuperzee-bug1-panel/blob/51a6eed6cf49b616c1a43fb610b6f578cc68b7df/src/EditorOption.tsx#L13

**Comment by ZuperZee** [comment]
@zuchka was that enough info?

**Comment by tolzhabayev** [comment]
@ZuperZee hey there, we currently have an open PR to update `monaco-editor` https://github.com/grafana/grafana/pull/54068
I would wait and see if the solves the issue once it's merged and new packages are rolled out.

**Comment by tolzhabayev** [comment]
@ZuperZee it will be a part of `9.2.0`, but you can check the pre-build [9.2.0-77333pre](https://www.npmjs.com/package/@grafana/ui/v/9.2.0-77333pre) and see if it works.

**Comment by ZuperZee** [comment]
Works like a charm.
![image](https://user-images.githubusercontent.com/39485579/188200544-94c62710-1467-46ff-8f5e-2bd6e37818b4.png)

One note. It requires the monaco editor build files. Which depends on the installed Grafana version. Image above is the main branch (commit: https://github.com/grafana/grafana/commit/d2bb72fb3c46aa7bab3250849bfee074de96cc77).

**Comment by ZuperZee** [comment]
@tolzhabayev another note.
You do not have to upgrade the Grafana UI version to get the fix. Only the actual Grafana server version.

**Comment by ZuperZee** [comment]
Closing as this seems resolved on the main branch
