### ISSUE TITLE
bind_password cannot contain special characters

### ISSUE THREAD

**Issue by markayre** [grafana/grafana#5337]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.0.4
- What datasource are you using? 
  none configured yet
- What OS are you running grafana on? 
  Centos 7.2
- What did you do? 
  Installed Grafana and setup ldap authentication against Active Directory. Set bind_password with special characters (ie *!)
- What was the expected result? 
  LDAP authenticates and user from Active Directory can log in
- What happened instead? 
  Active Directory showed a failed bind user login attempt with incorrect username/password. Grafana logs show the below error:
  LDAP initial bind failed, LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903CF, comment: AcceptSecurityContext error, data 52e, v2580
  Changing the password to not contain special characters resolved the issue.

Not a big issue, i've changed my password but would be good to have a heads up in the docs (would have saved me some headache). thanks!

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by anhlqn** [comment]
I'm on 3.1.0 and I think this is still an issue.

**Comment by markkrj** [comment]
Did you try with single quotes? like this: 'P@$$w0rd*)'

**Comment by bergquist** [comment]
# is the comment char in ini files so it will remove the # char and anything after.
How ever if you wrap the password in the ini files with in """ it wont be threated as a password

ex
password = """#password"""
