### ISSUE TITLE
Node Graph - Legend for mainStat and secondaryStat works wrong when displayName value is the same as for arc fields

### ISSUE THREAD

**Issue by k8spacket** [grafana/grafana#53373]
**What happened**:

The legend in Node Graph works wrong when `mainStat` or `secondaryStat` has the same `displayName` value as one of the fields `arc__*`. It appears when a graph dynamically changes based on Grafana variables. I use Hamed's plugin from https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/. We checked together, and this is not the problem with this plugin.

![issue2](https://user-images.githubusercontent.com/95187481/183369575-4a7efa94-0e27-4747-912f-ff65872cff87.gif)

**What you expected to happen**:

The legend should be empty before rendering a new one.

**How to reproduce it (as minimally and precisely as possible)**:

- Install the data source plugin https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/
- Start `python` program from the attached `run.zip`
- Configure the plugin to URL from started `python` program (e.g.: http://localhost:5001)
- Select Explore from Grafana
- Choose `Node Graph API` as a data source
- Type in `Query String` several times: 
    - `var=connection`, and Run Query
    - `var=delay`, and Run Query
    - `var=connection`, and Run Query
    - `var=delay`, and Run Query
- Watch what is happen with the legend

<img width="767" alt="image" src="https://user-images.githubusercontent.com/95187481/183374458-c64407da-ddf2-4631-acee-4bcecc9f335e.png">

[run.zip](https://github.com/grafana/grafana/files/9280023/run.zip)

**Environment**:
- Grafana version: v9.0.6
- Data source type & version: Node Graph API v1.0.1
- Grafana plugins: https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/

**Comment by zuchka** [comment]
Thanks for creating this issue, @k8spacket 

It looks like you are using a community-built datasource plugin. You will need to file an issue in that repo instead, I believe:

https://github.com/hoptical/nodegraph-api-plugin
