### ISSUE TITLE
Time picker doesn't indicate relative time range within same day

### ISSUE THREAD

**Issue by tomahkvt** [grafana/grafana#53378]
Grafana:8.3.0 and later have the bug with  the current date highlighting

![Grafana 8 3](https://user-images.githubusercontent.com/13186324/183397699-ac840133-c238-4362-b7c5-5aaf18bb28e9.png)

Grafana 8.1.0 and earlier doesn't have this bug
![Grafana 8 1](https://user-images.githubusercontent.com/13186324/183398108-e4d9a780-4701-4393-891a-1885cfd66316.png)

It looks like the problem appeared after https://github.com/grafana/grafana/pull/39073

The solution of this bug will improve Grafana usability. Thank you in advance.

**Comment by usmangt** [comment]
Hi @tomahkvt ,

Thanks for opening this post/case.

Yes, I see that in version 8.1.0 it seems to be highlighting the current date in the calendar and in the newer version's I cannot see that.

**Comment by tomahkvt** [comment]
Hi @usmangt. Will you be able to fix this bug?

**Comment by usmangt** [comment]
Hi @tomahkvt,

I have forwarded it to our team. They will update the status here once reviewed it. You will get an update notification via comments.

**Comment by tomahkvt** [comment]
@usmangt Thank you a lot.

**Comment by joshhunt** [comment]
Grafana 8.1.0 doesn't actually highlight the current date - it's highlighting the current time range that happens to include the current date. In this 8.1.0 screenshot, taken on the 10th, 10th is not highlighted.

![NI2MxPj8eU](https://user-images.githubusercontent.com/46142/183878615-7b968aa8-6137-463f-b26c-f47b94934b3c.png)

The bug appears to be that the time picker calendar no longer shows the selected time range when time range is:
 - relative (includes "now")
 - happens entirely within one day
 
e.g. on Tue 9am:
 - select `now-8h to now` (abs. Tue 1am to Tue 9am), it doesn't show a selected time range
 - select `now-10h to now` (abs. Mon 11pm to Tue 9am), it shows Mon and Tue as selected
 - Select `now-12h to now-10h` (abs. Mon 9pm to Mon 11pm), it doesn't show a selected time range
