### ISSUE TITLE
grafana-server fail to start on x86-32 due to StandardCounter.count misalignment

### ISSUE THREAD

**Issue by szpajder** [grafana/grafana#5341]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using?
Version 3.1.0 (commit: v3.0.4+206-gbf1ea56)

- What datasource are you using?
(not applicable)

- What OS are you running grafana on?
Gentoo Linux on Intel Atom CPU (x86-32 arch)

- What did you do?
Built Grafana from source and launched ./bin/grafana-server

- What was the expected result?
grafana-server starts up

- What happenend instead?
grafana-server crashed with the following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference [signal 0xb code=0x1 addr=0x0 pc=0x822cf3c]
    
goroutine 6 [running]:
panic(0x88f5ce0, 0x1920a038)
        /usr/lib/go/src/runtime/panic.go:464 +0x326
sync/atomic.AddUint64(0x194d0604, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/grafana/grafana/pkg/metrics.(*StandardCounter).Inc(0x194d0600, 0x1, 0x0)
        /home/szpajder/src/go/src/github.com/grafana/grafana/pkg/metrics/counter.go:54 +0x3b
github.com/grafana/grafana/pkg/metrics.instrumentationLoop(0x192119c0, 0x0)
        /home/szpajder/src/go/src/github.com/grafana/grafana/pkg/metrics/publish.go:26 +0x3d
created by github.com/grafana/grafana/pkg/metrics.Init
        /home/szpajder/src/go/src/github.com/grafana/grafana/pkg/metrics/publish.go:22 +0x46
```

I have googled around and found this (https://golang.org/pkg/sync/atomic/#pkg-note-BUG):

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned. 

It seems the definition of StandardCounter does not conform to this requirement:
```
type StandardCounter struct {
        *MetricMeta
        count int64
}
```

But when I reordered the fields, grafana-server started without problems:

```
type StandardCounter struct {
        count int64
        *MetricMeta
}
```

**Comment by bergquist** [comment]
Thank you for reporting this problem and finding the solution!
