### ISSUE TITLE
Elasticsearch Template Variable formatting in Filters Agg 

### ISSUE THREAD

**Issue by 1tft** [grafana/grafana#5342]
- **I'm submitting a ...**
- [x] Bug report

Multiselection of Template Variable does not produce correct Elasticsearch query:

I have a Template Variable called "hoststage" with values like p, q, t
I use this template variable in a Filter query like: "hoststage:($hoststage)"

Grafana only show results if I chose only one value of the hostage template variable. With multi selection I get "parse_exception: Cannot parse 'hoststage:({p, t})'
Because correct Elasticsearch syntax should be hoststage:("p";"t")

Not working with multi selected template variable values:
![not_working](https://cloud.githubusercontent.com/assets/8899007/15999865/b62f7124-3148-11e6-8982-38c2005f2bc4.png)

Manual its working:
![working](https://cloud.githubusercontent.com/assets/8899007/15999866/b634c746-3148-11e6-819f-605e6ac4ce7b.png)

I can't make a working dashboard on play.grafana.org because there is only 3.0.2 installed.

If I make a lucence query hoststage:($hoststage)  than multi selection is also working!
- Grafana v3.0.4
- Elasticsearch 2.x
- Client Win7 / Backend: RHEL7

**Comment by torkelo** [comment]
thanks for reporting this, looks like a bug :)
