### ISSUE TITLE
No way of keeping Zero at the same level in Time series.

### ISSUE THREAD

**Issue by woyteck1** [grafana/grafana#53431]
**What happened**: I am unable to put the zero on Y axis'es in the same height of the graph.

**What you expected to happen**: In older version it just worked

**How to reproduce it (as minimally and precisely as possible)**: any time series graph where some values are only positive and some are also negative.

**Anything else we need to know?**: This should be an option!

**Environment**: v8.5.6
- Grafana version: v8.5.6
- Data source type & version: DB, postgres
- OS Grafana is installed on: linux (docker)
- User OS & Browser: Chrome
- Grafana plugins: no
- Others:

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by leeoniya** [comment]
there's a Symmetrical scale (centered zero) option in 9.1: https://github.com/grafana/grafana/pull/52555
