### ISSUE TITLE
[Bug] rendering issues with 'fill below to' and null value 'null'

### ISSUE THREAD

**Issue by jbergler** [grafana/grafana#5344]
- What Grafana version are you using?
  v3.0.4
- What datasource are you using?
  Graphite
- What OS are you running grafana on?
  Debian Wheezy
- What did you do?
  Created a graph with 3 series (lower, upper & mean of a graphite timer).
  Upper should fill below to lower.
  Mean should be a line.
- What was the expected result?
  Expected the fill area to be rendered in a sensible manner when both data points are present and depending on the null value setting.

Connected should fill the area between where the two lines would go if they were visible,
Null should just not render anything on the Y axis at that X value.
Zero should render nothing (fill from 0 to 0)
- What happenend instead?

Flot freaks out a bit and the fill area is inconsistent / overlapping itself.

![image](https://cloud.githubusercontent.com/assets/698597/16006888/45c10f00-3167-11e6-8361-dad1e86e4d94.png)
![image](https://cloud.githubusercontent.com/assets/698597/16006891/49a2cb5e-3167-11e6-8fac-c39edcdfd884.png)
![image](https://cloud.githubusercontent.com/assets/698597/16006894/4bb4ae44-3167-11e6-829d-9854238d7961.png)

**Comment by torkelo** [comment]
seems like you missed to specify any detail

**Comment by jbergler** [comment]
@torkelo apologies, github got slightly too excited while I was still filling in the form. Was hoping to update it before you got to reading it but apparently you're too quick.

**Comment by jbergler** [comment]
It's also worth noting that this doesn't happen all the time, sometimes that graph renders as expected in all three modes.

**Comment by jbergler** [comment]
Given the age of this, and since I haven't seen for quite some time I'll close this issue.
