### ISSUE TITLE
Regex in template variable value is escaped

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#5345]
Grafana 3.0.4 with InfluxDB 1.0beta.

I have 2 template variables: a custom variable called `foo` and an InfluxDB query `SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /$foo/`

- If the value of foo is `bar`, the query sent to InfluxDB is ok: `SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /bar/`
- If I change the template query to use a regex, it works ok: `SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /.*/`
- If I type a regex in foo, it is sent escaped to influxdb: `SHOW TAG VALUES FROM load_longterm WITH KEY = host WHERE host =~ /\.\*/`

Is there a way to prevent the value of foo being sent escaped?

**Comment by torkelo** [comment]
no, values are always regex escaped. The only case when it is not is the Custom All value, this is not regex escaped-

**Comment by jessetan** [comment]
Thanks for the response @torkelo.
For my particular case that proved to be sufficient: I removed the `.*` regex from the values and entered it as the Custom all value.
