### ISSUE TITLE
LibraryPanels: Library panels are unable to be deleted on certain databases

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#53456]
**What happened**:

On grafana cloud I cannot delete library panels. I've replicated on play.grafana.org (v9.0.5), and on my nightly instance (v9.2.0-pre (8185b6fdf7)). On ops I see this exception:

> Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXCEPT SELECT id from dashboard)' at line 1

See [logs + trace on ops](https://ops.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Borg%3D%5C%22joshhunt%5C%22%7D%20%7C%3D%20%60%60%20%7C%20logfmt%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660042996559%22,%22to%22:%221660043229144%22%7D%7D&right=%7B%22datasource%22:%22Em2icyuMk%22,%22queries%22:%5B%7B%22query%22:%22453b6591f2344bfc%22,%22refId%22:%22A%22,%22queryType%22:%22traceId%22%7D%5D,%22range%22:%7B%22from%22:%221660039629144%22,%22to%22:%221660043229144%22%7D%7D)

I cannot reproduce this locally when using sqlite. I suspect the DELETE SQL command is somehow incompatible with whatever database grafana cloud uses. 

**What you expected to happen**:

i expect to be able to delete library panels when using any supported database, especially on grafana cloud :) 

**How to reproduce it (as minimally and precisely as possible)**:

On play.grafana.org:

 - create a new dashboard, new panel, and convert it to library panel. save the dashboard.
 - delete the panel from the dashboard, and save the dashboard.
 - the library panel is now completely detached from any dashboard
 - go to https://play.grafana.org/library-panels and try to delete your library panel - you'll get an error.

Alternatively, try deleting the panel "Esc 3500 Library Panel" on https://play.grafana.org/library-panels.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kaydelaney** [comment]
Fix https://github.com/grafana/grafana/pull/53460

**Comment by axelavargas** [comment]
Reopening the issue as the problem is still present on Grafana v9.1. 

cc @kaydelaney
