### ISSUE TITLE
Cannot update alert rule in GUI when alert is created through the API

### ISSUE THREAD

**Issue by jaclynfink** [grafana/grafana#53464]
**What happened**:
I try updating an alert mySQL query in the UI. If the alert was created via the API - /grafana/api/v1/provisioning/alert-rules , then the changes I make to the alert query in the GUI do not save. Although I get a "save successful" prompt, the change does not actually take place.

**What you expected to happen**:
I expect to be able to modify an alert via the API and the GUI interchangeably.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert via /grafana/api/v1/provisioning/alert-rules , then edit that alert mySQL query in the GUI, save the changes, and see that the changes were not made.

**Environment**:
- Grafana version: 9.0.3
- Data source type & version: MySQL
- User OS & Browser: Mac OS Monterey v12.4

**Comment by mellieA** [comment]
Can you share an example of the API request you're using to create the alert?

**Comment by mellieA** [comment]
@jaclynfink while researching another issue I found out that provisioned rules aren't currently supported for editing in the UI: 

https://github.com/grafana/grafana/issues/51211#issuecomment-1162884503

> Provisioned rules, contact points, policies, silences etc. are not editable from the UI. There will be better support in the UI around this in 9.1. Sorry for the inconvenience.
