### ISSUE TITLE
[Alerting]: Alerting Rule UI & Thresholds

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5347]
This issue represents the work that is needed to complete the v1 of the Alerting Rule UI. 

This includes the ability to set thresholds visually in the graph panel via handles that can dragged: 
![alerting_short](https://cloud.githubusercontent.com/assets/10999/16010247/9a0f40a4-3180-11e6-915c-43386f3c64a9.gif)

What remains is to migrate the existing threshold rules over to a "visual only" alert so they can resuse the same logic. This means removing the level1, level2 thresholds and color and line options and replace them by warn, level & op, and critical level & op options.  No color option will be allowed. 

Hope to be able to migrate the old threshold options but could be some dashboard that has some backward compatibility issues (especially given that the threshold color options will be removed).

**Comment by tonyC2016** [comment]
@torkelo  other question ,does  grafana support Parent-Child Relationship,?

**Comment by torkelo** [comment]
@tonyC2016 in what context? what's the parent? what's the child? Panels? Alert Rules?

**Comment by Huangsir** [comment]
+1

**Comment by antjori** [comment]
@torkelo, the developments of this feature are being done in a separate branch or are they in Grafana's master?

**Comment by msylla** [comment]
+1
@torkelo How would the scheduler sub-module work ?

**Comment by torkelo** [comment]
@msylla maybe in the future. Right now we have a concept we call handler (in the screenshot it's called scheduler) that is an abstraction that executes and evaluates the rule. Right now we only support our internal (in the Grafana backend) scheduler and execution handler. 

But it would be possible to set rules to use a "No-op" handler, which disables the Grafana scheduler and execution handler so it could be processed by an external system (that would need to poll for the alert definitions from grafana), or let Grafana schedule the alert execution and push (HTTP POST) the rule to another system for execution and evaluation

**Comment by msylla** [comment]
@torkelo ok i see. 

"Let Grafana schedule the alert execution and a JSON object to POST to whatever system" would be a more efficient and flexible architecture i believe, at least for some of us Grafana users.

**Any idea yet of the (JSON?) model of the AltertNotification objet what would be POSTed ?**

On our alerting system implementation we have that object model :
- point : the data point value
- pointTime : the date/time of the data point
- pointFormat : the unit of the data point
- metricId : the id of the metric panel
- metricTitle : the title of the metric panel
- metricUrl : the link to the metric panel
- imageUrl : the link to the rendered
- dashboardTitle : the name of the daboard
- thresholdLevel : the threshold level that has been reached (T1/warning or T2/critical)
- metricSnapshotBase64 : a screenshot of the metric panel encoded in base64 (using phantomjs)
- detectedTime : the date/time when the threshold has been reached
- recipients : a list of emails recipients (we extended the Axes module with a specific form/submodule for that)

Would be great also to add the below properties to the model :
- the connected Grafana "user information"

**Comment by torkelo** [comment]
@msylla 

currently an alert rule looks like this:

```
{
   frequency: 10,
   handler: 1,
   warn: { op: '>', level: 10 },
   crit: { op: '>', level: 20 },
   query: {
     refId: 'A',
     from: '5m',
     to: 'now',
   },
   transform: {
     type: 'aggregation',
     method: 'avg',
   },
 };'
```

query.refId refers to a query in metrics tab. We will include the json model of the query defintion as well if we would push this to an external alerting query execution handler.

**Comment by msylla** [comment]
@torkelo ok only the "alert rule" metadata would be sent to the external system? No information about the metric/panel metadata itself, as i was trying to describe above ?

**Comment by torkelo** [comment]
the query model (or query expression/string) would be provided, but the point of sending it the external system is for that system to do the actual metric request and get the metrics and evaluate the rule

**Comment by msylla** [comment]
@torkelo ok i get it, thanks for the answers. 

So there will be no way for the external system to know from which Grafana panel/metric the alert rule came from ? Wouldn't it be useful if the external system needs to e.g. redirect the end-users that are notified, to the specific Grafana panel ?

And (finally) as asked @antjori can we already get access to those early developments ?

**Comment by torkelo** [comment]
of course the panelId and dashboard can be provided. 

Not sure what you mean by "metric" in this case. The metric query or metric data? metric data means that Grafana needs to issue the query to get that, which is the whole point of having an external handler (to process the query). 

Maybe you are talking more about wanting an external notification handler? That is something different and of course Grafana will support many different notifications mechanisms

**Comment by msylla** [comment]
@torkelo 
sorry when i said "metric/panel" i meant the visual display of the metric data in Grafana application (Graph, SingleStat, Table.. panel).

If the _panelID_ and _dashboard name_ are provided in the JSON _alert rule_, that would allow externals systems to reconstruct the link to the visual Grafana Panel
(e.g. : http://play.grafana.org/dashboard/db/**elasticsearch-metrics**?panelId=**1**&fullscreen ), then provide that link to end-users, or also get a rendered image of the visual Grafana Panel to be embedded in an alert notification email, still in direction to end-users...

That was the idea, hope it's clearer.

**Comment by tonyC2016** [comment]
@torkelo   grafana +elasticsearch ,how get alerting support ?i cant find the alerting ui?

**Comment by torkelo** [comment]
It's not done yet

**Comment by tonyC2016** [comment]
@torkelo is it has any  plan about  alerting support ?if does,which version,and can it support grafana2.6.0 +elasticsearch,mode in the further

**Comment by roscoe57** [comment]
this looks nice, but

really need a dynamic feature...

eg Temperature ACTUAL being the monitored field
Temperature SETPOINT being the target field

then create a Threshold that is say +3.0 above and -2.0 below the designated set point, as the setpoint follows a profile then the alerting threshold would so also ?
