### ISSUE TITLE
Threshold labels should be displayed in the selected unit 

### ISSUE THREAD

**Issue by JeanFred** [grafana/grafana#5348]
- [X] Feature request

When using the singlestat panel with a gauge with threshold labels, I would expect the labels displayed in the unit selected for the singlestat.

See this screenshot for an extreme example: I have data about time in the range of years ; but it is retrieved as a Statsd timer, so in milliseconds. I would want « 3 » (for 3 years) to be displayed instead of the equivalent in milliseconds
![screenshot from 2016-06-13 15-21-36](https://cloud.githubusercontent.com/assets/364381/16010771/929c7df6-317a-11e6-8b4e-554d910be2b8.png)

Please include this information:
- Grafana 3.0.4
- Graphite datasource
- Ubuntu 14.04

**Comment by Serphentas** [comment]
Any updates on this ? Would gladly welcome some tips on making the required changes and potentially a PR.
