### ISSUE TITLE
secondary template query variables not updating using 'Refresh on Load' when changing templated datasources

### ISSUE THREAD

**Issue by throck** [grafana/grafana#5349]
* **I'm submitting a ...**
- [X] Bug report

- What Grafana version are you using?
3.0.2 (Grafana version: 3.0.2, commit: v3.0.1+21-g0c345e2, build date: 2016-05-16 03:06:39)
- What datasources are you using?
multiple Graphite sources, and referencing them as templated 'Data source' variables 
- What OS are you running grafana on?
Red Hat Enterprise Linux 6.8
- What did you do?
Have defined two variables of type 'Query', both set to 'Refresh on Load'
- What was the expected result?
I expect all of the Query variables to update on the dashboard when switching datasources
- What happened instead?
Only one of the data sources is updating on the dashboard; if I change the refresh type for the second variable to 'On Time Range Change', both Query-type variables update when selecting another datasource.

Note: looking at the query/response in chrome dev tools, I see only one request/response, for the variable which is being updated; switching the refresh type as mentioned, I see two responses/requests in the network tab.

**Comment by torkelo** [comment]
Good news, think you issue is already solved in 3.0.4.

Please check changelog before opening issue if there is already a newer release than you already have! 
Also search for existing issues :)

https://github.com/grafana/grafana/issues/5165
https://github.com/grafana/grafana/issues/4861

**Comment by throck** [comment]
Dang!  I did search, but didn't find those, but yes, should have checked the changelog.  Thank you!
