### ISSUE TITLE
After updating to 9.0.6 alert value can not be read

### ISSUE THREAD

**Issue by RezaBabapour** [grafana/grafana#53502]
![Screenshot from 2022-08-10 09-20-58](https://user-images.githubusercontent.com/30316545/183823529-e7450ea5-6529-487b-8899-ec3c725c3742.png)

**What happened**:
Using grafana version 8.4.6 with docker, I created a alert, alert value was readable(value show the metrics that fires alert) and there is no problem. then I update grafana image to 9.0.6 and alert value looks like this: 
B0: -1e+00, B10: -1e+00, B1: -1e+00, B2: -1e+00, B3: -1e+00, B4: -1e+00, B5: -1e+00, B6: -1e+00, B7: -1e+00, B8: -1e+00, B9: -1e+00

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create alert in version 8.4.6(docker image from hub.docker.com) and then change image to 9.0.6(from hub.docker.com). 

**Environment**:
- Grafana version: 9.0.6
- Data source type & version: victoriametrics 
- OS Grafana is installed on: docker ubuntu
- User OS & Browser: ubuntu and debian, chrome and firefox

**Comment by mellieA** [comment]
@RezaBabapour new grafana alerts refer to the labels differently. There are some examples in the docs and this community post that should help to get them formatted the way you prefer: 

https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#how-to-template-annotations-and-labels 

https://community.grafana.com/t/how-to-use-alert-message-templates-in-grafana/67537
