### ISSUE TITLE
Elasticsearch datasource without Auth using Basic Auth return 403

### ISSUE THREAD

**Issue by thinkhp** [grafana/grafana#53511]
**What happened**:
When I fetch data from an Elasticsearch datasource using Basic Auth, the datasource without Auth configured returns 403

**using datasource 138**, not work, 403
<img width="669" alt="image" src="https://user-images.githubusercontent.com/26300404/183864370-03f57800-8a84-4e60-b841-5999c4b84990.png">

```
curl https://$username:$pwd@$grafana_host/api/datasources/proxy/138/_msearch?max_concurrent_shard_requests=5 
```
output:
```
{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic <base64(user:pwd)>"}
```

**using datasource 145**, is OK, 200
<img width="692" alt="image" src="https://user-images.githubusercontent.com/26300404/183865000-2fcff15d-6d56-4ca2-9506-d8196bfdf028.png">

```
curl https://$username:$pwd@$grafana_host/api/datasources/proxy/145/_msearch?max_concurrent_shard_requests=5 \
  -H 'content-type: application/x-ndjson' \
  -H 'x-grafana-org-id: 1' \
  --data-raw $'{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"ot_notify_message"}\n{"size":0,"query":{"bool":{"filter":[{"range":{"createTime":{"gte":1660120746575,"lte":1660122546575,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"terms":{"field":"merchantId","size":10,"order":{"_count":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"20s","field":"createTime","min_doc_count":0,"extended_bounds":{"min":1660120746575,"max":1660122546575},"format":"epoch_millis"},"aggs":{}}}}}}\n'
```
output: es data, status 200

**Anything else we need to know?**:
This problem also occurs when using API key.

**Environment**:
- Grafana version: grafana/grafana:8.1.8
- Data source type & version: Elasticsearch
- OS Grafana is installed on: linux
- User OS & Browser: macos chrome

**Comment by mellieA** [comment]
@thinkhp this looks like a support question - the best place to ask those for open source is in our community at https://community.grafana.com/ 

You can check if you get a response from elasticsearch without auth configured using the `<index>/_mapping` endpoint. 

For example, in my case with an index of `kibana_sample_data_logs`, the save & test button in the datasource sends a request to: 

`curl -XGET localhost:9200/kibana_sample_data_logs/_mapping` where localhost is my elasticsearch server without basic auth configured. If you can get a response there without authentication enabled, then it should work in your datasource. 

I tested with ES 7.10 and Grafana 8.5.0 and it worked without basic auth configured. I'll close this as a question, if you think it is a bug, feel free to reopen the issue.
