### ISSUE TITLE
kiosk can be rolled back when use the esc key

### ISSUE THREAD

**Issue by YuanXingH** [grafana/grafana#53518]
**What happened**:
I want to embed the grafana page with the kiosk，this way the user cannot operate the sidebar and variable options, but the browser go back when the esc key is pressed.

when i in kiosk mode
![grafana1](https://user-images.githubusercontent.com/26616949/183879067-a5056b2a-f98e-4d68-af74-ea80cee3cefe.jpg)

then i press esc
![grafana2](https://user-images.githubusercontent.com/26616949/183879460-a90e7cee-4032-4551-ae03-aeb2dcf8880c.jpg)

**What you expected to happen**:
If grafana in kiosk mode, it can not be rolled back, the sidebar and variable options always can not see by user

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The kiosk mode is designed to you can escape out of it :) 

It is accessed by the tv button on in the dashboard toolbar (far right), need a way to exit it. So working as designed

**Comment by torkelo** [comment]
You can vote for this: 
https://github.com/grafana/grafana/discussions/51295

**Comment by laoxiaokang** [comment]
@torkelo  Why does the old version not display the sidebar in kiosk=pc mode; A new version will appear

**Comment by torkelo** [comment]
@laoxiaokang ? not sure I understand your question

**Comment by laoxiaokang** [comment]
For the version 8.3.1, when using '&kiosk=pc' mode, the side bar will not appear in the view, but after upgrading to version 9.1.5, when using '&kiosk=pc' mode, the side bar will appear in the view;

**Comment by laoxiaokang** [comment]
![image](https://user-images.githubusercontent.com/45983816/191203524-95312de2-7a92-470c-bc53-10c18c2e06d9.png)

**Comment by torkelo** [comment]
Kiosk pc mode has never been valid value , tv or just &kiosk are the valid values

**Comment by laoxiaokang** [comment]
Is there any way to hide the sidebar and display the custom variable bar？like:↓↓↓
![image](https://user-images.githubusercontent.com/45983816/191390060-2ba37a4e-7ba6-43d1-98d2-be678a8d4b7d.png)

**Comment by laoxiaokang** [comment]
@torkelo

**Comment by torkelo** [comment]
@laoxiaokang nope

**Comment by laoxiaokang** [comment]
ok,I know.Thanks!
