### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by lyrixx** [grafana/grafana#5351]
**I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

- What Grafana version are you using? [v3.0.4](https://github.com/fg2it/grafana-on-raspberry/tree/master/jessie/v3.0.4)
- What OS are you running grafana on? `Raspbian GNU/Linux 8 (jessie)`
- What did you do? `$ grafana-server`
- What was the expected result? `A running server`
- What happenend instead? `std: Illegal instruction ; exit code: 132`

**Comment by torkelo** [comment]
Maybe running x64 binary on Arm processor?

**Comment by lyrixx** [comment]
@torkelo ok, thanks.

**Comment by lyrixx** [comment]
Sorry but actually, I used an ARM version. I tried on pi1B and toning on pi2 and it's the same result.
Just in case you did not see it, I'm using this version: https://github.com/fg2it/grafana-on-raspberry/tree/master/jessie/v3.0.4

**Comment by lyrixx** [comment]
Actually, even go binary itself produce the same error... 
Anyway, thanks.
