### ISSUE TITLE
Single stat averaging bug?

### ISSUE THREAD

**Issue by arsibaba** [grafana/grafana#5352]
* **I'm submitting a ...**
- [x] Bug report

Grafana Version 3.0
Graphite
Windows 7

Trying to create a single stat panel to calculate week over week numbers.
Whatever time frame is chosen, grafana provides information that lets us know what the average rolling week over week percentage looks like. For simplicity, here is an example:
Today's numbers are 10, 15, 20
Last week's numbers are : 20, 25, 30

Expected Result: 
10 + 15 + 20 = 45
20 + 25 + 30 = 75
Result = 45/75 = 0.6 or 60% week over week.

- What happenend instead?
It looks like when you average or total, its actually comparing each number individually and then averaging. i.e.
10/20 = 0.5. 15/25 = 0.6. 20/30 = 0.66
(0.5 + 0.6 + 0.66)/3 = 0.586 or 58.6%

Is this a known issue? Is this intended behavior?

Thank you

**Comment by bergquist** [comment]
Not sure I understand how this can happen since singlestat panel only support single series.  
Are you calculating this in graphite?

**Comment by arsibaba** [comment]
not sure what it means to do it in graphite.

I'm on the grafana interface. I'm editing my panel. Creating an #A series (which is the sum of all values for the allotted time frame today). Creating a #B series (which is the sum of all values from the same time frame but a week ago). then creating a #C series where I'm using the asPercent(#A,#B). I've also tried to use divideSeries(#A,#B)

Hope that helps. Sorry I'm new to Grafana so I'm still learning. I know we use Graphite as the database for this but the interface where I'm plugging all this in is inside Grafana's edit function of the panel.
