### ISSUE TITLE
Problem with initial setup

### ISSUE THREAD

**Issue by Toledodev** [grafana/grafana#53535]
**What happened**: I managed to do the initial setup, but when trying to run the project locally only this page is displayed. I would like to know if anyone else has had this problem, I tried the things suggested in the photo but there was no change

![Screenshot from 2022-08-09 19-14-13](https://user-images.githubusercontent.com/87545086/183924161-d7eb6abc-a0f0-4d90-b971-92012f83eb3c.png)

**What you expected to happen**: I would like to view the project normally

**How to reproduce it (as minimally and precisely as possible)**: Run yarn start and make run

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
have you compiled the frontend (Via yarn start for continuous re-build on source change or yarn dev if you only want to build once, yarn build for production frontend build)

Check browser developer console logs for errors or network tab (it will show if fronend assets return 404)
