### ISSUE TITLE
Grafana API snapshots-delete doesn't work

### ISSUE THREAD

**Issue by jerryxguo** [grafana/grafana#5353]
I am running the grafana 3.0.4 on the windows.

I could create the snapshot successfully with http API (  Authorization: bearer  eyJrIjoiSW5wR3Bvek42T1RvNnVSV05HdFFudkVKR3pzVzhhS3AiLCJuIjoiYWQiLCJpZCI6MX0) 

but  when i tried to delete the snapshot just created with the http: 
GET /api/snapshots-delete/KvgKVf2cpVenVO5795meiL6QQRFXe1z3

it responded with Statuscode=403,  Forbidden.  rather than {"message":"Snapshot deleted. It might take an hour before it's cleared from a CDN cache."}

Jerry

**Comment by torkelo** [comment]
you need an Editor role api key

**Comment by jerryxguo** [comment]
@torkelo Thanks for saving me
