### ISSUE TITLE
Alpine Dockerfile uses Edge repositories and can break

### ISSUE THREAD

**Issue by chennin** [grafana/grafana#53551]
The current [custom Alpine docker file](https://github.com/grafana/grafana/blob/dbc21714016dc6e62ca92d3c0236d353534f4157/packaging/docker/custom/Dockerfile) adds [Edge](https://wiki.alpinelinux.org/wiki/Edge) repositories, which is not recommended for production. (This docker file is [documented](https://grafana.com/docs/grafana/next/setup-grafana/installation/docker/#build-with-grafana-image-renderer-plugin-pre-installed) for those who want to run the image renderer plugin in a docker install. The ["main" Dockerfile](https://github.com/grafana/grafana/blob/dbc21714016dc6e62ca92d3c0236d353534f4157/packaging/docker/Dockerfile) also references an Edge package).

This image is currently broken (2022-08-10).

Repro:

```
cd $(mktemp -d)
wget https://raw.githubusercontent.com/grafana/grafana/dbc21714016dc6e62ca92d3c0236d353534f4157/packaging/docker/custom/Dockerfile
docker build --build-arg GF_INSTALL_IMAGE_RENDERER_PLUGIN=true -t grafana-image .
```

The  build fails today with:

```
(6/18) Upgrading ca-certificates-bundle (20220614-r0 -> 20220614-r2)
ERROR: ca-certificates-bundle-20220614-r2: trying to overwrite etc/ssl1.1/cert.pem owned by libcrypto1.1-1.1.1q-r0.
ERROR: ca-certificates-bundle-20220614-r2: trying to overwrite etc/ssl1.1/certs owned by libcrypto1.1-1.1.1q-r0.
...
1 error; 23 MiB in 26 packages
The command '/bin/sh -c if [ $GF_INSTALL_IMAGE_RENDERER_PLUGIN = "true" ]; then     echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories &&     echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories &&     echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories &&     apk --no-cache  upgrade &&     apk add --no-cache udev ttf-opensans chromium &&     rm -rf /tmp/* &&     rm -rf /usr/share/grafana/tools/phantomjs; fi' returned a non-zero code: 1
```

I guess that this specific packaging error is an Alpine Edge error that will be resolved by them soon. However, it could be argued that Grafana's usage of Edge mixed with production is a bug, and will break again in the future.  I do not know why edge repos were added when they were (#20241), but please consider removing the usage of Edge repos for production use.

I have built an image without the edge repos on Grafana 9.0.7, and it appears fine.

**Comment by kminehart** [comment]
I agree these should probably be removed.

But just to correct one statement:
> which is not recommended for production

The root dockerfile is not used in production. We package Grafana for Docker with the dockerfile in the `packaging/docker` folder. The root one is mostly a nice thing to have for people wanting to contribute to Grafana.

I believe the edge package referenced there was specifically to resolve a CVE at the time in OpenSSL
