### ISSUE TITLE
[Bug] Organisation switching broken in Internet Explorer/Edge

### ISSUE THREAD

**Issue by iDemonix** [grafana/grafana#5356]
- **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
  3.0.4
- What datasource are you using?
  Graphite
- What OS are you running grafana on?
  CentOS 7.2
- What did you do?
  Tried to switch organisation
- What was the expected result?
  To be switched to that organisation
- What happened instead?
  The page refreshes, showing the same (default) organisation, not the newly selected one

We have recently upgrade to Grafana 3.0.4 and decided to break out in to organisations as having a singular organisation was becoming crowded. After doing this, we have realised that IE/Edge users are unable to switch organisation. Granted, I've informed them all to get a real browser, but unfortunately things aren't always that simple in the business world.

Is this a known bug already? It seems like something that would have been noticed by now but I couldn't find any history.

Tested using:
Windows 10 + IE 11.0
Windows 8 + IE 11.0
Windows 10 + Edge (Latest)

All show the same issue, which is rectified by switching browser.

**Comment by dannygoulder** [comment]
You may have a caching issue.

I have found that IE is pretty bad with Grafana WRT caching of page resources (it basically caches everything, including influxdb proxied queries, so that new data doesn't show up on an auto-refreshing graph).  

Chrome doesn't cache pages in the same way as you seem to be observing.  One workaround I have used is to run IE in Dev tools mode (it doesn't cache _anything_ that way) but this obviously isn't a good solution.

One way would be for Grafana to be more explicit about caching certain resources, with HTTP Expires: and/or cache-control: headers

For now I have put everything behind an Apache proxy and used mod_expires to set a 5 second ttl on all resources.  of course this puts more load on Grafana but it works for me and IE functions just fine.

**Comment by iDemonix** [comment]
I'll see what the dev replies with before making changes. I didn't really think about caching, as I wasn't aware how differently MS browsers behaved.

If there's no response or it seems like this may be an unresolved bug, I'll have to look at something like apache or nginx to manage caching headers. Thanks.

**Comment by benthorner** [comment]
We're having this issue too. Users have to manually refresh the browser to see the change.

**Comment by benthorner** [comment]
Just to add that we fixed this by going Internet options, Browsing history, Settings, and selecting 'Every time I visit the webpage' under 'Check for newer versions of stored pages'.

**Comment by daniellee** [comment]
This was worse than I thought. Added a Cache-Control header for all HTTP GET requests to the API to stop IE caching so aggressively. It will be released with v4.4.0.

**Comment by benthorner** [comment]
That's great. Thanks Dan - really helpful :-)

**Comment by benthorner** [comment]
Hmm...Tried this after upgrading to 4.4. We're still not able to switch between organisations without changing Internet Explorer's caching behaviour. Perhaps you put it in a later version (currently running in 4.4.1-1)?

**Comment by iDemonix** [comment]
We've just upgraded to v4.4.0, I'm home now but it seems to be working on my VM, with default Edge and IE settings.

I'll get some business users to test tomorrow to see if I can still replicate the issue.

**Comment by daniellee** [comment]
@benthorner no, it should be in this version. If you look at the response headers for any GET request then it should have a Cache-Control header with the value `no-cache`. Are you using Edge or IE11? Maybe the Cache-Control header isn't enough for older versions?

**Comment by benthorner** [comment]
@daniellee yes, we are using IE11 and I can see the Cache-Control header coming through. This [article](https://support.microsoft.com/en-gb/help/234067/how-to-prevent-caching-in-internet-explorer) from Microsoft and this StackOverflow [article](https://stackoverflow.com/questions/5017454/make-ie-to-cache-resources-but-always-revalidate) indicate that's not quite right.

**Comment by benthorner** [comment]
Also, did you have Developer Tools open when testing? Just wondering as that's caught me out in the past - having them open disables caching automatically.

**Comment by daniellee** [comment]
I'll test again today. I only tested on Edge. Not sure we want to put the effort into supporting IE11 but in this case I can add some extra headers for IE11.

**Comment by iDemonix** [comment]
I can't replicate the issue across 3 Windows machines, seems to be fixed here!

**Comment by benthorner** [comment]
@iDemonix, @daniellee, just to be sure we're testing the same thing: in IE11 I'm logging in and then trying to switch to one of the orgs I created. 

One improvement is that I can now see the orgs I can switch to, which I couldn't before. However, I still can't switch orgs without manually changing the caching behaviour.

**Comment by daniellee** [comment]
@benthorner I could see the same symptoms when I tested in IE11. I'd forgotten how weird IE is. Added two extra headers, Pragma and Expires. Seems to work for me when switching orgs in IE11 after adding the pragma header. This probably does not work for older IE versions though.

**Comment by benthorner** [comment]
That's OK, we'll be fine until then. It'll be nice not to have to tell people to apply this change, is all. Happy to wait until the next release, and thanks for giving it another go :-)
