### ISSUE TITLE
Failed to save screenshots uploaded with a signed url

### ISSUE THREAD

**Issue by VDVsx** [grafana/grafana#53566]
**What happened**:

An error occurs while saving the metadata of unified alerts screenshots uploaded to an external image storage.

Logs:

```
grafana logger=ngalert t=2022-08-11T05:23:02.217652653Z level=warn msg="failed to generate a screenshot for an alert instance" alert_rule=1odSl7m4k dashboard=G9jnlni4k panel=2 err="failed to save image: failed to insert screenshot: Error 1406: Data too long for column 'url' at row 1"
```

**What you expected to happen**:

The metadata is saved successfully.
 
**How to reproduce it (as minimally and precisely as possible)**:

- Enable Grafana unified alerting screenshot capture and upload to a external storage with signed urls, in our case we are using "gcs".

Our config:

```
- name: GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE
   value: "true"
- name: GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE
   value: "true"
- name: GF_EXTERNAL_IMAGE_STORAGE_PROVIDER
   value: "gcs"
- name: GF_EXTERNAL_IMAGE_STORAGE_GCS_ENABLE_SIGNED_URLS
   value: "true"
```

**Anything else we need to know?**:

If I understand the code correctly, the url column is currently having a limit of 190 chars, signed url returned from gcs can be 800+ chars: https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/ualert/tables.go#L391

**Environment**:
- Grafana version: V9.0.6
- Data source type & version: Prometheus and others
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: Google Cloud MySQL 5.7

**Comment by VDVsx** [comment]
HI @grobinson-grafana are you already working on this?
I just did a fix that I could contribute, just needs a bit more testing.

**Comment by grobinson-grafana** [comment]
Hi @VDVsx, we just discussed it with the team and I was about to start working on a fix. However, please feel free to open a PR and we can look at that instead.
