### ISSUE TITLE
Google Cloud Monitoring: Service dropdown is failing to render the services

### ISSUE THREAD

**Issue by kaushall** [grafana/grafana#53563]
**What happened**:
The service dropdown of Google Cloud Monitoring Datasource is not loading all the services for the project which has more than 10k metrics descriptors. I've recorded a video for more detailed explanation: https://drive.google.com/file/d/1ruB8SWcqfuhO03jVYte_qccpA-UXsFC8/view?usp=sharing

**What you expected to happen**:
It should display all the services and load all the metric descriptors.

**How to reproduce it (as minimally and precisely as possible)**:
Try to load a project which has more than 10k metrics descriptors and you'll see the same issue.

**Anything else we need to know?**:
Probably cause for the issue is, there is no pagination handling for the metric descriptor api. As per google docs it will load upto 10k metrics for each request if pagination is not passed in the url. This can be solved by adding pagination parameters in the url.

**Environment**:
- Grafana version: Grafana v8.3.1 (8d38082755)
- Data source type & version: Google Cloud Monitoring
- OS Grafana is installed on: NA
- User OS & Browser: NA
- Grafana plugins: NA
- Others: NA

**Comment by aangelisc** [comment]
Hi @kaushall!

I can see that you've referenced [8d3880082](https://github.com/grafana/grafana/commit/8d380827554752fa641ec1b5aa52f863e4eea3ca) as the version you're using. Is it possible for you to upgrade to a later version? [This](https://github.com/grafana/grafana/pull/42546) PR added support for pagination of responses when a `pageToken` is returned.

Let me know if you need further information or if this doesn't fix your problem and I can investigate further!

**Comment by kaushall** [comment]
Hi @aangelisc 

Thank you for your reply, I'll test it with a newer version and update you here.

**Comment by kaushall** [comment]
Hi @aangelisc 

After upgrading the Grafana to 9.1.0 it started working, now it is loading all the metrics using API. 

But now the issue is Grafana is dying while loading the data.

Current Flow:
- By default it is loading all the metrics descriptors after selecting the project. (~39k)
- After selecting one of the services it is again trying to load all the metrics for all the services in the project. (~39k)
- For eg. I've selected External service and it has only 20k metrics so ideally it should load only 20k metrics descriptors in the dropdown but it's currently loading 39k metrics. Which is the total of all the metrics descriptors of the project.

Ideal Flow:
- Select the project but and use api to fetch only Services of the project. (~30 services)
- Once the service is selected fetch only metrics descriptors of that service. (For Custom service it's ~9k metrics descriptors)
- For eg. I've selected the External service and it has only 20k metrics so ideally it should load only 20k metrics descriptors in the dropdown.

**Comment by kaushall** [comment]
Hi @aangelisc 

It gets stuck while rendering the 'Metric name' dropdown. The page becomes unresponsive while clicking on the dropdown. I actually don't have any logs for this as there were no console errors or warnings.

If you need more details I can create one more video recording for you.

Grafana Version: 9.1.0
Data it is trying to load is of 17.5MB
Network transfer size is 424KB
Browser: Chrome 104.0.5112.101 Official Build

**Comment by aangelisc** [comment]
Hi @kaushall, I'd definitely appreciate a video but I understand the issue you're facing at the moment. I'll update here with more information as I get it 😊 Thanks!

**Comment by aangelisc** [comment]
Hi @kaushall, did you manage to record a video? I've pushed an update to the flow so the metric descriptors API shouldn't be called multiple times anymore. That should be released this week and may solve the issue you were seeing!

**Comment by kaushall** [comment]
Hi @aangelisc 

Yes I've recorded the video but didn't uploaded because you've already made the changes by that time. And yes I'm eagerly waiting for this release :) 

Thank you so much for your efforts.

**Comment by aangelisc** [comment]
No worries at all @kaushall! I'm going to close this issue now and if anything comes up again feel free to create a new issue or comment on this one 😊
