### ISSUE TITLE
[Feature Request] Space between rows and columns

### ISSUE THREAD

**Issue by mravv** [grafana/grafana#5358]
It would be nice to add a small UI improvement, which will allow to change (and delete, by setting 0px, for example) a space between rows and elements in a row.
![capture_grafana copy](https://cloud.githubusercontent.com/assets/12971726/16047129/8d3db8a6-3257-11e6-84ae-4938bba219ab.png)

**Comment by bergquist** [comment]
Hi

To get a more unified look you can set the panel back ground to transparent in the Panel -> General tab. Maybe that's what your aiming for? 

Its not likely that we will add such setting with the current panel setup. Maybe if we update the complete panel rendering but then everything will change.
