### ISSUE TITLE
Bug: Template variable overlap breaks dashboard

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#5359]
Grafana version: 3.0.3
Datasource: Graphite API
OS: CentOS 7

What did we do?
We've created several dashboards using a Graphite API data source. To make them more general, we also added some template variables: portgroup and port.

What happened next?
After saving the dashboard and refreshing, all you can see is a blank screen (no headers, nothing). Some experimentation showed this happens when one template variable overlaps with another e.g. portgroup and port both contain the word port.

What do we expect to see?
It would be great if this was fixed - it's hard to debug if you haven't come across it before!

**Comment by bergquist** [comment]
Would be great to see the dashboard json for this issue. But I suspect that you get an recursive match since port matches both port and portgroup.

The easiest workaround for this is to replace $port and $portgroup with [[port]] and [[portgroup]]

**Comment by torkelo** [comment]
this should be fixed in 3.0.4 I think

**Comment by benthorner** [comment]
I can't reproduce this in the latest version - thanks.
