### ISSUE TITLE
Manage dashboards doesn't list folders in alphabetical order with panelTitleSearch

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#53609]
**What happened**:

When enabling `panelTitleSearch`, the Manage/Browse Dashboards default page does not list folders in alphabetical order, despite the Sort dropdown suggesting default is alphabetical

Feature flag off:

![2788_2022-08-11-16-49_chrome](https://user-images.githubusercontent.com/46142/184176668-f1977b86-e4a6-4245-825b-d0fcf593655b.png)

Feature flag on:

![2789_2022-08-11-16-49_chrome](https://user-images.githubusercontent.com/46142/184176735-dcc6abf6-b2c5-413e-8104-4532ef481fab.png)

**What you expected to happen**:

its sorted alphabetically.

**How to reproduce it (as minimally and precisely as possible)**:

 - enable `panelTitleSearch`
 - add folder "x Folder"
 - add folder "

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ArturWierzbicki** [comment]
The frontend issues this query:

```
{
  "queries": [
    {
      "refId": "Search",
      "queryType": "search",
      "search": {
        "query": "*",
        "tags": [],
        "sort": "name_sort",
        "starred": false,
        "kind": [
          "dashboard",
          "folder"
        ],
        "limit": 50
      },
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "datasourceId": -1
    }
  ]
}
```

the response is sorted by name, but it contains both folder names _and_ dashboard names. We could either issue a separate query for just folders (`"kind": [ "folder" ]`), or parse the response and extract the folder names on frontend, but that could be tricky with pagination (?)

**Comment by Toledodev** [comment]
Hey @natellium, how can i enable panelTitleSearch?

**Comment by Toledodev** [comment]
The "General" folder encompasses all other folders, so it always appears first, but when changing the order (Z-A) "General" disappears. We could:
1. Make some sort of distinction in the General folder so that it's not next to the others
2.Resolve the problem that it doesn't appear when we change the order
3.Delete it so that it's no longer shown

**Comment by natellium** [comment]
Apologies for the late reply @Toledodev. Seeing your comment you probably found the answer, but just in case the new search can be accessed by enabling the `panelTitleSearch ` feature toggle. [Here](https://grafana.com/docs/grafana/next/dashboards/use-dashboards/#dashboard-search) are the docs

**Comment by ashharrison90** [comment]
@joshhunt looks like this has been fixed. if you're still seeing it feel free to reopen 👍
