### ISSUE TITLE
Cannot find newly created dashboard when searching for it to add a panel to it

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#53603]
I have created a new dashboard 6 hours ago, it's called Team and it's in the folder Alerting. I try to add a panel to a dashboard after having explored my possibilities and search is not returning the dashboard I want. Images cut a bit for better privacy.
<img width="781" alt="PS 2022-08-11 à 16 52 30" src="https://user-images.githubusercontent.com/2117580/184164422-4b9584de-58e7-405a-9330-5c24ba20b4f1.png">

<img width="754" alt="PS 2022-08-11 à 17 01 25" src="https://user-images.githubusercontent.com/2117580/184165052-27ddc6fd-7e0b-43fe-b189-31eb732955ec.png">

<img width="173" alt="PS 2022-08-11 à 16 52 01" src="https://user-images.githubusercontent.com/2117580/184164848-12cf3cb2-6640-45da-a0da-8707de748d19.png">

<img width="129" alt="PS 2022-08-11 à 16 51 26" src="https://user-images.githubusercontent.com/2117580/184164863-1f4a977e-dc1d-45bc-b59d-3fef161854f7.png">

<img width="820" alt="PS 2022-08-11 à 16 51 12" src="https://user-images.githubusercontent.com/2117580/184164879-cd40fa9b-8018-4345-88a0-4894ea1d8e65.png">

**What happened**: I cannot find my dashboard when searching for it to save a query as a panel to it.

**What you expected to happen**: Find my dashboard.

**How to reproduce it (as minimally and precisely as possible)**: See screenshots above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2 (ca72cd570)
- Data source type & version: GitHub, latest
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: macOS, Chrome
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
What happens when you search for the dashboard by it's name - "Team"?

**Comment by armandgrillet** [comment]
That way I can indeed find it.

**Comment by ArturWierzbicki** [comment]
I can reproduce it both with `panelTitleSearch` and without - I think we should migrate this UI component to use the new search endpoint

**Comment by joshhunt** [comment]
Those inputs you screenshot all describe dashboards, and list only dashboards titles, and search by the dashboard title.

This is working as expected.
