### ISSUE TITLE
Public Dashboard: panels with expressions does not work

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#53617]
**What happened**:
When creating a Public Dashboard with a panel that has an expression it shows an error in Public Dashboard View.

**What you expected to happen**:
It should show the same info as the original Dashboard

**How to reproduce it (as minimally and precisely as possible)**:
Create a public dashboard with a panel that contains query and simple expression like `$A - 1`

**Anything else we need to know?**:

**Environment**:
- Grafana version: `9.1.0-beta` with Public Dashboards turned on

**Comment by baur** [comment]
How to activate Public dashboards?

**custom.ini**
`publicDashboards = true`

does not affect

**Comment by baur** [comment]
done

```ini
[feature_toggles]
enable = publicDashboards
```

But there are limitations, most importantly template variables do not work

**Comment by jalevin** [comment]
https://github.com/grafana/grafana/pull/54336
