### ISSUE TITLE
RPM postinst scriptlet fails to restart Grafana

### ISSUE THREAD

**Issue by jealouscloud** [grafana/grafana#53612]
**What happened**:
Upgrading Grafana RPM on systems without systemd fails to restart Grafana in spite of `RESTART_ON_UPGRADE=true` in `/etc/sysconfig/grafana-server`
It attempts to call `/etc/inid.d/grafana-service stop`, but that script does not exist. 

**What you expected to happen**:
Grafana to restart, via
```
/etc/init.d/grafana-server stop
/etc/init.d/grafana-server start 
```
as part of the postinst scriptlet.
**How to reproduce it (as minimally and precisely as possible)**:
This bug was discovered on a CentOS 6 machine which is EOL.
Installing any modern version of Grafana followed by upgrading to any other version in Grafana, one can observe that the grafana service isn't restarted.

**Anything else we need to know?**:
The stopGrafana function in https://github.com/grafana/grafana/blob/e9980a9bb8335a94bf6b25de401bac343bff6bfc/packaging/rpm/control/postinst#L18 uses /etc/init.d/grafana-service, which is not provided by the RPM. It looks like it was intended to use /etc/init.d/grafana-server.

**Environment**:
- Grafana version:9.0.7-1
- OS Grafana is installed on: CentOS 6
- User OS & Browser : not relevant
- Grafana plugins: none

**Additionally**:
CentOS 6 is end of life and officially out of support, but the RPM is built to support non-systemd systems and the fix is fairly trivial.

**Comment by usmangt** [comment]
Hi @jealouscloud,

Thanks for opening this issue.

I will forward it to the correct team so that they can have a look and can investigate further.

**Comment by summerwollin** [comment]
Closing as stale
