### ISSUE TITLE
Template Search Box - Power User Tip

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5362]
I have a template variable that allows me to manually select multiple values as shown below.

![screen shot 2016-06-14 at 12 00 31 pm](https://cloud.githubusercontent.com/assets/406777/16055846/b8634724-3227-11e6-9131-4abfc65825de.png)

I want to copy paste a bunch of values instead of manually selecting. I tried
1,2,3
1+2+3
1|2|3

Did not work.

How can i paste multiple values without selecting it manually

**Comment by bergquist** [comment]
Im not sure about adding a searchbox in that list. I think very few would use it. An other solution that might solve the same issue is sending the template variables as querystrings to the dashboard. Ex: http://play.grafana.org/dashboard/db/influxdb-templated-queries?var-host=10.1.100.10&var-host=server1&var-host=server2

**Comment by torkelo** [comment]
you could create another small utility app that generates links with the selected experiments ids?

**Comment by deepujain** [comment]
I was not asking to add a search box. 
I have template variables configured in the query. I was wondering is it possible to copy paste a bunch of values in the template variable text box instead of manually selecting from a list. Imaging a list of 100s of values and if i need to select more than 10, then it can be a pain, especially when i have the list handy in a text file.

The list can keep changing. And hence template variables feature is useful. The only problem i see is selecting few is easy but searching and selecting more than 10 can be a pain. In that case, if i can simply paste a list of values directly into text box with any delimiter it can speed up things.

More over we do have a text box where user can type in, why not go a step ahead and allow him to type multiple values.

**Comment by deepujain** [comment]
I am unable to re-open it.
