### ISSUE TITLE
Null As Zero not working as exected

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5363]
I have five data points that are plotted below. After first two points, the metric is not available for few days until it shows up again.

I was wondering if is it possible to break the continuous line. I tried null as connected, null as zero,  null as null, all three had no effect on the graph.

![screen shot 2016-06-14 at 1 59 22 pm](https://cloud.githubusercontent.com/assets/406777/16059617/83026e14-3238-11e6-991d-82e77e671db5.png)
![screen shot 2016-06-14 at 1 59 08 pm](https://cloud.githubusercontent.com/assets/406777/16059616/82f39092-3238-11e6-9408-2ae51f2802c1.png)

Is it possible to achieve what am seeking ?

**Comment by torkelo** [comment]
Null as zero only work if you query returns null missing data points, does it do that?

**Comment by eaglewu** [comment]
@vijaykansal3 ref https://github.com/grafana/grafana/issues/7967#issuecomment-401290251
