### ISSUE TITLE
Char after variable name in []

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#5366]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

```
3.0.4
```

I have a prometheus query that looks like this:
```
delta(some_metric[10m])/10
```

I'd like to put ```10``` to a variable, but non of the following works:
- ```delta(some_metric[[[i]]m])/$i```
- ```delta(some_metric[$im])/$i```

How can I make this work?

**Comment by torkelo** [comment]
please redirect questions to the mailing list or other support options 
http://grafana.org/support/
