### ISSUE TITLE
um, how do you use elasticsearch? 

### ISSUE THREAD

**Issue by hujosh** [grafana/grafana#5369]
I have 'documents' in my 'index' that look like this:

> {"_index":"tt","_type":"test","_id":"3","_version":1,"found":true,"_source":{ "first_name" : "Jane", "last_name" : "Smith", "age" : 32, "about" : "I like to collect rock albums", "interests": [ "music" ], "@timestamp" :"2016/06/16 16:53:50"}}

I have connected Grafana to these 'documents' ( and i know that it really has connected because the 'save and test' button tells me it has).

However, when i try to 'view' the data inside of the documents, i get nothing back. I have used grafana with graphite before, and i had no problems. But Elasitcsearch + Grafana makes no sense..

I am staring at an input box containing the text  ' lucene query' without a clue of what i am supposed to enter into that box. 

There is literally not a single document on the internet that explains what one is supposed to enter  into that box. For my sake and for the sake of others, can you please explain what one is supposed to enter into that box. That would be a good start. I think i can figure out what to do from there. 

Thank you

**Comment by bergquist** [comment]
Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
