### ISSUE TITLE
Add basic table to display queries in

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#53693]
For this we may reuse the search table or potentially the reporting table depending on whichever is easiest 

https://github.com/grafana/grafana/blob/ec5fd4b3d2804a77ccd72e422df88a9bb9f74be8/public/app/features/search/page/components/SearchResultsTable.tsx#L1

**Comment by nmarrs** [comment]
Looks like Artur beat us to it 😬 at least for implementing basic table

**Comment by nmarrs** [comment]
Looks like Artur beat us to it 😬 at least for implementing basic table

**Comment by drew08t** [comment]
Saw that, awesome! More time to focus on the super fun stuff!

**Comment by nmarrs** [comment]
https://github.com/grafana/grafana/commit/147d6cc695003529d603a895a408d20e8dd96910
