### ISSUE TITLE
ability to save dashboard to a shareable URL (without elasticsearch etc.)

### ISSUE THREAD

**Issue by fche** [grafana/grafana#537]
It would be handy if grafana core (without elasticsearch, for permalinking purposes) supported a way of taking a dashboard specification from the URL querystring.  Perhaps JSON-compressed-urlencoded as a grafana/index.html query string?  (Perhaps optionally tinyurl'd ?)

**Comment by torkelo** [comment]
fixed in Grafana v2.0

**Comment by fche** [comment]
@torkelo , could you elaborate?  I can see some querystrings show up when editing/sharing an individual view, but that doesn't contain enough data to reproduce the view.   e.g., after editing one of the default dashboards to add some random beer metric, the "share" operation results in this URL:

http://play.grafana.org/?from=1434887658965&to=1434887789111&width=1000&height=500&panelId=3&fullscreen

IOW it describes what the dashboard was, but not what it is now.

**Comment by torkelo** [comment]
You need to save the dashboard to the grafana db , ether as a dashboard or as a snapshot dashboard (visible data is embedded in the dashboard json)

**Comment by fche** [comment]
OK, so the original request was to encode the whole dashboard state in a querystring url (no database, no json file).  Is that functionality of interest to y'all?

**Comment by torkelo** [comment]
It wont work, the url can only contain arround 2083 characters (depending on web server and browser)

**Comment by fche** [comment]
Hi -

> It wont work, the url can only contain arround 2083 characters (depending on
> web server and browser)

Sure, though compressed json is not that large, and info about
those 2K limits are rather dated.

- FChE

**Comment by torkelo** [comment]
Yea I know those limits are a little dated, but some (extreme) Grafana dashboards are more than 16K characters when json encoded

**Comment by torkelo** [comment]
Can you describe your use case? Is it just a way for you to share temp dashboards (or temp modifications to existing dashboards)?

**Comment by torkelo** [comment]
That should be more than 16 million characters :)  (For example dashboards with many template variables and values)

**Comment by fche** [comment]
Hi -

> Can you describe your use case? Is it just a way for you to share temp
> dashboards (or temp modifications to existing dashboards)?

Exactly; bookmarking & sharing, without any breakable infrastructure
or manual steps.

- FChE
