### ISSUE TITLE
Refine query popover tab - usage

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#53700]
What dashboards use this query? list that links to each instance?

![Image](https://user-images.githubusercontent.com/22381771/185221745-028a4860-2115-4d21-8c64-053bf852eee3.png)

**Comment by nmarrs** [comment]
Need data from backend?

**Comment by ArturWierzbicki** [comment]
@nmarrs will add this tomorrow

**Comment by nmarrs** [comment]
https://github.com/grafana/grafana/commit/722eab5395b889c635b825212313d80f904a4deb
