### ISSUE TITLE
Inconsistent in showing logs for the query with empty filter in Loki query dashboard

### ISSUE THREAD

**Issue by SanthoshS20** [grafana/grafana#53716]
What happened:
In the Loki query dashboard, No data present in the logs for the query with empty filter. Ran a query with empty filter results in No data present for that empty filter. 

What you expected to happen:
Based on the time range, It should show all the logs for the query with empty filters present in the query field.

**How to reproduce it (as minimally and precisely as possible):**
1. Go to the Loki query dashboard.
2. Add a query with empty filter in the query field and run it.
3. It will show that no logs present for the query with empty filter.

**Anything else we need to know?:**
![image](https://user-images.githubusercontent.com/37366893/184538447-13165747-da14-459e-a24c-6d020c0aca5f.png)

**Environment:**
Grafana version: _9.0.5_
Data source type & version:
OS Grafana is installed on:
User OS & Browser: _Windows 10 & Google Chrome_
Grafana plugins:
Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @SanthoshS20 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by SanthoshS20** [comment]
@zuchka I tried it and replicated the same issue in the public sandbox

https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice%3D%5C%22web_app_1%5C%22,%20status_code%3D%5C%22200%5C%22%7D%20%7C%3D%20%60%20%20%60%22,%22queryType%22:%22range%22,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by usmangt** [comment]
Hi @SanthoshS20 

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I will forward it to the Engineers to have a look and check if this is an expected behaviour or a bug.

**Comment by ivanahuckova** [comment]
I don't think this is a bug. You are not running query with empty line filter. You are actually searching for lines containing 2 spaces and your log lines don't have 2 spaces in their content, so it is retruning `no data`. This is a correct behaviout. 

<img width="115" alt="image" src="https://user-images.githubusercontent.com/30407135/209148705-273421a9-93a8-4de2-bdf4-7eb002418c4b.png">

You can see here, if I have logs with 2 spaces, it correctly finds them:


If you run empty line filter (|= ``), it is working as expected, you see all of the log lines - check here: https://play.grafana.org/goto/GWbMl6c4k?orgId=1
