### ISSUE TITLE
Inconsistent in showing logs on Loki query dashboard

### ISSUE THREAD

**Issue by SanthoshS20** [grafana/grafana#53715]
**What happened**:
In the Loki query dashboard, the logs for the query with a filter was present on the logs for the query with an another filter.
**_Example:_** I fetched logs with a query and a filter **_Error_**. After the execution of the query, I tried with a different filter **_Name_**. The logs of the previous query with filter **_Error_** was present in the current logs. 

**What you expected to happen**:
It should only show the logs based on the filters present in the query field.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to the Loki query dashboard.
2. Add a same query with filters in the two query fields and run it.
3. Change the filter and run the query.
4. It will show the previous filter logs and current filter logs in the current filter.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/37366893/184537665-56324feb-b2bc-4679-9832-e74bc3c105f3.png)

**Environment**:
- Grafana version: 9.0.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows 10 & Google Chrome 
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @SanthoshS20 ,

Thanks for opening this case here. To my understanding, if the Log-query A is to search ERROR then the result should have contained log lines ERROR.

When adding another Log-query B to search for e.g. WARN (and query A is still running) then the resulted output log line should contain both ERROR and WARN.

This is to my understanding why we have multiple queries OR maybe I did not understand you that well?

Can you maybe share a live example on https://play.grafana.com/ ?

**Comment by SanthoshS20** [comment]
I tried in this Grafana https://play.grafana.com/ Still facing the issue.

Time Stamp - (Start -> 2022-08-18 11:09:55 and End -> 2022-08-18 12:04:55)

Step 1: Have 2 query field and execute it.

Query 1 -> {agent="promtail", host="appfelstrudel", job="nginx_access_log"} |= `error`
Query 2 -> {agent="promtail", host="appfelstrudel", job="nginx_access_log"} |= `10845`

Step 2: Disable the Query 1 and see the logs. It contains an additional one log and that log should present only for Query 1.

**Comment by usmangt** [comment]
Thanks, Yes I am now able to reproduce it.

I used your query but instead of 10845 replaced it with "warn" and can see the extra log line which does not have any warn after disabling query#1

![image](https://user-images.githubusercontent.com/69509548/185399168-69cc6297-b1e7-4767-949a-5f713f52c5af.png)

**Comment by gabor** [comment]
hi @SanthoshS20 thanks for reporting the issue. it was fixed in the code, the fix will be available in Grafana9.1.1.
