### ISSUE TITLE
Legend sorting problem

### ISSUE THREAD

**Issue by lark** [grafana/grafana#5371]
Grafana 3.0.4 with opentsdb datasource

The legend is sorta sorted but...

![image](https://cloud.githubusercontent.com/assets/705163/16108670/2ddfdbe2-33d7-11e6-92c4-1cd26a5e0c1a.png)

The graph is generated using this setting

![image](https://cloud.githubusercontent.com/assets/705163/16108783/dbd006f0-33d7-11e6-9583-95c5d6164f98.png)

The very strange part is "01 03 02", in every graph. We deliberately using leading 0 padding to make sorting to work as expected both numerical or alphabetical, but we failed badly.

Or this is opentsdb sorting problem, grafana just presents it as is?

**Comment by torkelo** [comment]
Yes, this is an OpenTSDB issue, the series order is the responsibility of the TSDB & query
