### ISSUE TITLE
Annotation breaks on adjusting time range

### ISSUE THREAD

**Issue by lazam** [grafana/grafana#53727]
![grafana-issue](https://user-images.githubusercontent.com/7956429/184615585-55c7799d-1f5d-46bc-88d7-b6766332d5dd.gif)

**What happened**:
Annotation breaks when increasing the time range to a larger window

**What you expected to happen**:
Annotation should still remain the same regardless of the time range 

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Prometheus as datasource, and add the metrics
2. Use this query 
`ansible_annotation unless (ansible_annotation offset 1m) `

**Anything else we need to know?**:
If you increase the offset to a larger window then it will work with a larger the time range but breaks on a more larger time frame. An example is 1m is good for 3 hour time range, 15m for 12 hour time range, and so on which isn't supposed to be since querying the data works as expected as seen in the gif.

**Environment**:
- Grafana version: v9.03
- Data source type & version: Prometheus 2.36.1
- OS Grafana is installed on: Debian 10
- User OS & Browser: Debian 11 / Firefox 103.0.2 and Chrome 103.0.5

**Comment by zuchka** [comment]
Thanks for creating this issue, @lazam 

we have some working prometheus datasources up here. do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by lazam** [comment]
Hi @zuchka ,

I can't create any  dashboard in https://play.grafana.org/, and I tried to create the panels in an existing dashboard but I don't have the permission to save it. Is there also a way to push data in the existing Prometheus datasource since this needs a new data to easily replicate?

**Comment by mellieA** [comment]
@lazam I see work is in progress that looks like it will address this - https://github.com/grafana/grafana/issues/61073 

I also found an explanation of why this happens in the code as is: 

>  I've investigated this and it seems that the issue is due to the interval(step) set for annotations. Prometheus annotations have maxDataPoints set at 100 and this causes the step to get wider as the range of the window is extended. When the step is too great, queries may be missed. This is what is happening with the annotations. 

>The panel and queries done in the panel use maxDataPoints that can be set, usually around 1000 or greater depending on the width of the panel. This makes the interval/step smaller and allow the queries to be done more granularly and that is why the data points show up when they are queried.

>Prometheus uses LegacyAnnotationQueryRunner for annotations and as far as I can tell, it does not have access to the maxDataPoints of the panel.
