### ISSUE TITLE
Panel Description box does not expand to fit markdown table

### ISSUE THREAD

**Issue by sgil-isi** [grafana/grafana#53725]
**What happened**:
Panel Descriptions support Markdown formatting. Making a table that is too wide for the panel does not adjust it's size to fit the content.
The Table section spreads outside the tooltip and can be difficult to read.

**What you expected to happen**:

- a) The panel should expand in width to contain its content if there is enough space.

- b) If there is not enough space (Browser Windows size or whatever) or a reasonable max width is reached, switch to having a scroll bar (or otherwise handle the large table).

**How to reproduce it (as minimally and precisely as possible)**:

- Edit any panel, e.g. https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?orgId=1&editPanel=4

- Add Description text containing table markdown code, e.g.:
```
| Correct | Horse | Staple | Butter | Mint | Bus | Bread | Elephant| Extremity| Problematic | Incomplete|
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| |
|Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |Lorem Ipsum |
```

- Result
![image](https://user-images.githubusercontent.com/111264449/184594746-ff1500c2-1c03-4f07-8c83-1277499e94f0.png)
Here the table escapes the description box. (Firefox)

![image](https://user-images.githubusercontent.com/111264449/184596338-c6fbf0bc-8cda-4143-86f7-cbd04d597a0e.png)
Here a panel on the right side of the dashboard has the description cut off. (Firefox)

![image](https://user-images.githubusercontent.com/111264449/184597165-45012646-131e-457f-8229-3537881371a8.png)
Here is the same issue duplicated in Chrome.

**Anything else we need to know?**:
This issue is similar to [Issue #29239](https://github.com/grafana/grafana/issues/29239) which has been fixed.

**Environment**:
- Grafana version: `Grafana v9.0.7 (eed942a50)`
- Data source type & version: 
- OS Grafana is installed on: 
- User OS & Browser: Windows 10 21H1, Firefox 103.0.2 (64-bit), Chrome Version 104.0.5112.81 (Official Build) (64-bit)

- Grafana plugins: 
- Others:

**Comment by usmangt** [comment]
Hi @sgil-isi,

Thanks for opening this case.

Can you please paste the complete markdown code as I tried to reproduce it using your description inside the 

`
```
your-provided-description
```
`

But for me, it seems to be not the exact output as your screenshot.

**Comment by sgil-isi** [comment]
Sorry for the confusion. I have fixed the description text so that it should work properly now.

**Comment by usmangt** [comment]
Thanks. I was now able to reproduce it as well. 

This might be a bit tricky one to say as either a bug or further enhancement. I will forward it to the team so that can view and decide what can be done with it.

**Comment by devnamrits** [comment]
Hi @usmangt, @sgil-isi , Can I pick this up and start my contribution to grafana?
