### ISSUE TITLE
Should a none Admin, Viewer user be able to create a new org?

### ISSUE THREAD

**Issue by rafaturtle** [grafana/grafana#5373]
* **I'm submitting a ...**
- [ ] Bug report
- [ X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
v3.0.4
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu
- What did you do?
Created a view only user.
- What was the expected result?
The user not be able to create a new org.
- What happenend instead?
The user was able to create a new org.

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Change config option allow_org_create
http://docs.grafana.org/installation/configuration/#allow_org_create
