### ISSUE TITLE
store current organization in the session or URL

### ISSUE THREAD

**Issue by tux21b** [grafana/grafana#5374]
It's currently not possible to use Grafana (3.0) with a user account on multiple hosts and different organizations. It appears that the current organization is stored in the database on a per-user basis and not per-session basis.

The preferable solution is probably to store the organization within the url (https://github.com/grafana/grafana/issues/1613) to support multiple tabs on a single host, but a reasonable solution should at least store the organization within the session to support at least multiple hosts.

**Comment by bergquist** [comment]
Thank you for the suggestion. But this will be implemented using a GET parameter as discussed in https://github.com/grafana/grafana/issues/1613
