### ISSUE TITLE
Unable to delete Library Panel - Grafana Cloud

### ISSUE THREAD

**Issue by westonforbes** [grafana/grafana#53752]
**What happened**: I tried to delete a library panel. Instead I got the message "Failed to delete library element"
![image](https://user-images.githubusercontent.com/56303146/184695536-eb0d834f-b475-407c-905f-63d594b0b84f.png)
I've closed my browser instance and reloaded and the issue persists. I've tried on different panels. No panel will delete.

**What you expected to happen**:  The panel to successfully delete.

**How to reproduce it (as minimally and precisely as possible)**: Try to delete a panel on Grafana Cloud.

**Anything else we need to know?**: No

**Environment**:
- Grafana version: Grafana Cloud
- Data source type & version: N/A
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 11 & Chrome
- Grafana plugins: None
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @westonforbes 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by westonforbes** [comment]
@zuchka, Library panels don't appear to be available in the sandbox.
Here is my live runtime menu

![image](https://user-images.githubusercontent.com/56303146/184864473-4bc97a87-a769-49b0-ae3f-bbb98801d636.png)

And here is the sandbox

![image](https://user-images.githubusercontent.com/56303146/184864529-5524f89a-8bf5-4f8f-9ddb-16a8dd72eb54.png)

If I attempt to save a panel to a folder in the sandbox, I am presented with this error.

![image](https://user-images.githubusercontent.com/56303146/184864677-ed7bd906-c4cc-4fad-9750-23ff7ebd8a23.png)

**Comment by mc-em** [comment]
Hi,
I am also encountering the same issue and seeing below error message in logs.

![image](https://user-images.githubusercontent.com/110811012/190107846-9db287fb-becd-4511-b29b-b8808724246b.png)

level=error msg="library element could not be found" error="library element could not be found"
level=error msg="Failed to delete library element" error="Error 1093: You can't specify target table 'library_element_connection' for update in FROM clause" 
level=error msg="Request Completed" method=DELETE path=/api/library-elements/yuTxNrWVk status=500

Environment:

Grafana version: Grafana OSS v9.1.1
Data source type & version: ES 7.11
OS Grafana is installed on: Windows Server 2016 Standard
User OS & Browser: Microsoft Edge Chromium

**Comment by usmangt** [comment]
Hi @mc-em and @westonforbes ,

I just tried to reproduce this on my Grafana Cloud and was able to delete a Library panel successfully.

My Grafana version is 9.3.2

Can you please try again on the new stable version?

**Comment by usmangt** [comment]
I will close this issue as not reproducible on the newer version. Feel free to open it if it still occurs
