### ISSUE TITLE
[Bug] Graph with multiple series - color problem

### ISSUE THREAD

**Issue by Lahorde** [grafana/grafana#5375]
## Description
Cannot differentiate multiple series when using same count() operator on series.

## Steps
Add 2 grafana metrics on a single graph

    select count(value) from series where $timeFilter GROUP BY time($interval)
    select  mean(value) from series where time > now() - 3d GROUP BY time($interval)
You can choose a different color for each graph.
Now replace mean operator with count operator :

    select count(value) from series where $timeFilter GROUP BY time($interval)
    select  count(value) from series where time > now() - 3d GROUP BY time($interval)

I cannot anymore choose a different color for series! When I change color, new color is set during ~100ms (so I have 2 different colors) and then new color is automatically set to other graph!

## Setup
grafana Version 3.0.0-beta6
InfluxDB shell version: 0.13.0

**Comment by bergquist** [comment]
The color is associated with the serie name. Having two series with the same name will give them the same color. I suggest you set an alias on one of the series to avoid conflicts. 

Having multiple series with the same name makes it harder to understand the graphs.

**Comment by Lahorde** [comment]
Thanks for suggestion about alias, it solved my issue.
