### ISSUE TITLE
[Feature Request] Support Password Policies (Especially, forced reset)

### ISSUE THREAD

**Issue by brewneaux** [grafana/grafana#5376]
The company I work for is not keen on hooking up our LDAP to Grafana, since we are running the grafana server on AWS.  Therefore, I am manually creating the users, and having to walk them through changing there passwords every time.

It would be nice to be able to force a password reset upon them, having it redirect when they log in the first time.

**Comment by bergquist** [comment]
Thank you for taking the time to contribute to Grafana. 

But this is out of scope for Grafana. We strongly suggest any setup that requires password policies to use LDAP or Oauth.
