### ISSUE TITLE
[Feature Request]: Graph series overrides, fill below to & use regex capture group

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#5378]
* **I'm submitting a ...**
* [ ] Bug report
* [x] Feature request
* [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Let's say you have several servers, each with `last smth` and `first smth` metrics. Trey are presented with two queries but result on 2*n graphics. You may be interested in stacking or filling them without defining a rule for each server. For example:

```json
"seriesOverrides": [
{
"alias": "/last (.*)/",
"fillBelowTo": "first \\1",
"lines": true
}
],
```

Unfortunately this doesn't work even with direct panel `json` insertion.

**Comment by rjes** [comment]
+1

**Comment by alpglide** [comment]
any update on this? this feature is really needed. thanks

**Comment by hryamzik** [comment]
Well that's one way to minimise amount of opened issues
