### ISSUE TITLE
[Feature request] Single stat for daily metrics

### ISSUE THREAD

**Issue by Lahorde** [grafana/grafana#5380]
## Description
Cannot display a singlestat for a today timeInterval (from 00:00 to now() ). It is possible to do it using a today timepicker (that applies to whole dashboard) but not possible to set it on a single singlestat panel setting today in "overriding relative time" - http://docs.grafana.org/reference/timerange/ 

## Setup
grafana Version 3.0.0-beta6
InfluxDB shell version: 0.13.0

## Remark
I opened this issue because getting these operators at grafana level would be nice. So far, today operator does not exist at influxdb level https://github.com/influxdata/influxdb/issues/2071#issuecomment-226480241

**Comment by torkelo** [comment]
specify `now/d` in the panel time range override
