### ISSUE TITLE
TimeSeries: Toggling series via Legend causes axis config to be changed

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#53804]
**What happened**:

I've created a panel with two series and toggled one of them using legend. The axis configuration of the series has changed kicing one of the series to the right y-axis. Illustrated but the following video:

https://user-images.githubusercontent.com/2376619/185068312-042acb1b-d6ec-406f-bc1e-e1334ea43c9a.mov

**What you expected to happen**:

I would expect the axis config not to change when the series is being hidden using the legend.

**How to reproduce it (as minimally and precisely as possible)**:

You can use the attached dashboard [1]

**Anything else we need to know?**:

**Environment**:
- Grafana version: main 81957732abf01c9df88307c5f41a12c9f117c0c2
- Data source type & version: Test db
- OS Grafana is installed on: MacOS 21D5025f
- User OS & Browser: Chrome (latest)
- Grafana plugins: -
- Others: -

**Comment by leeoniya** [comment]
was gonna follow up in https://github.com/grafana/grafana/pull/53671 today.

feels wrong to have the visibility as part of the scale  key. we had a quick call and agreed the legend alignment should remain stable even if series & axis is hidden.
