### ISSUE TITLE
Allow time ranges for playlists

### ISSUE THREAD

**Issue by sebastianw** [grafana/grafana#5381]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0

I'm using the new feature to save playlists. What I noticed is that I can't set a custom time range for playlists. It's always the last 24 hours. When I try to use the from= and to= parameters on the playlist URL (<code>/playlists/play/1?from=now-30d&to=now</code>) it's ignored. When I try to set the time range with the menu on the top right the playlist is stopped.

It would be nice to specify a defaut time range per playlist when saving the list.

**Comment by torkelo** [comment]
No its not always last 24 hours, it's what the saved time range is for the dashboard

**Comment by torkelo** [comment]
__
