### ISSUE TITLE
[Feature Request]: Value to image mapping

### ISSUE THREAD

**Issue by castrojsec** [grafana/grafana#5382]
Is it possible to have an option to place some html  inside of the singlestat panel.  Would be nice if I could place an image there verses having the value (much like the "Value to text mapping") so I can build a customized home page.  

so this:
![testing12](https://cloud.githubusercontent.com/assets/4368158/16159270/ccb4d700-348f-11e6-83dd-131be6ff3ad6.jpg)

would look like this:

![testing123](https://cloud.githubusercontent.com/assets/4368158/16159449/d545962e-3490-11e6-8e40-d8e15aa72187.jpg)
![testing1234](https://cloud.githubusercontent.com/assets/4368158/16159501/26cf4440-3491-11e6-8766-22aafcfd72f2.jpg)

**Comment by daniellee** [comment]
ref #1999

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
