### ISSUE TITLE
cannot add oauth user to organization anymore since version 9.1

### ISSUE THREAD

**Issue by tob123** [grafana/grafana#53833]
**What happened**:
i cannot add an oauth user to an organization anymore.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. use keycloak / oauth provider and login as the oauth user.
2. in a different session (as admin) add the oauth user to an organization different than the default.

**Anything else we need to know?**:
I am still able to remove existing oauth users from organizations. this seems weird. why I cannot add them (aka undo the removal?)

**Environment**:
- Grafana version: 9.1 opensource
- Data source type & version: any
- OS Grafana is installed on: docker
- User OS & Browser: chromium
- Grafana plugins: geomap
- Others:

**Screenrecording that shows adding oauth user works in version 9.0.7**
![working9 0 7](https://user-images.githubusercontent.com/11362436/185156241-55762184-44da-4bd4-8f5b-e0c3fcf004ed.gif)

**Comment by mellieA** [comment]
@tob123 this behavior was added by https://github.com/grafana/grafana/pull/52160 

> Adding users to new orgs when they'll just be removed after

**Comment by napstr** [comment]
I'm also hitting this.
@mellieA can you please share what the new correct way to add Github OAuth users to a Grafana organization is? I can't seem to find a working combination of config values.

**Comment by yylbfyl** [comment]
I'm also met the issue in 9.1 version , does anyone can fix it ?

**Comment by mellieA** [comment]
@napstr and @tob123 

The legacy external auth behavior has been that changes were allowed in the UI, but then the next time the user logged in via an external provider their settings would be overwritten by the external authentication configuration.

The new behavior introduced by [#52160](https://github.com/grafana/grafana/pull/52160) is that the buttons in the UI will disappear so there isn't a false impression that the admin can use the UI to manage the user's role.

It seems that lots of users were relying on the ability to temporarily override a user's role, so there will be a configurable setting that will disable the role_sync behavior and allow an admin to manage the role in the UI - [#55182](https://github.com/grafana/grafana/pull/55182)

**Comment by SirSkizo** [comment]
Just use and check the error message in the response:

```
curl -X POST http://<your-ip>:<your-port>/api/orgs/<your-org-id>/users \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -d '{"loginOrEmail":"<your-user-email-in-Oauh>","role":"Viewer"}'
```

Note that YWRtaW46YWRtaW4= is the result of parsing user:passwd to base64. I let you there the encoding of admin:admin which is the default for grafana.

You can always do something like `export AUTH_H=$(echo -n 'admin:admin' | base64)`
