### ISSUE TITLE
unique count with es datasource at grafana2.6

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5384]
i just use grafana 2.6 for unique count a String ID,and get a wrong result back ,i check at es with cardinality and got a right number ,i use unique count and use the Group by time interva 1y assure the datapoint is only one ,and got a wrong number ,does it like issue3536,it only support number field
how i can get a dictinct result back wish anyone tell me a way to fix it,like lucene query?if does ,how
thanks

**Comment by bergquist** [comment]
What does your query look like?

**Comment by torkelo** [comment]
probably related to precision threshold ES query parameter?
https://github.com/grafana/grafana/issues/4689

**Comment by tonyC2016** [comment]
@torkelo  in grafana  ,there is no option to set precision threshold,and i have no find the precision threshold in request json which i got at the network

**Comment by torkelo** [comment]
@tonyC2016 that is correct, that is what the issue I linked to is about (feature request to add precision threshold option)
