### ISSUE TITLE
[Bug] InfluxDB source: Escaping of template variables in SELECT columns (regex not detected)

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#5386]
## Problem
Template variables are being escaped when using as math operands in ```SELECT``` queries.

This is a follow up of  #5154. I opened a new case, as the problem cannot be solved using the proposed regexing (at least I couldn't).

## Environment
- What Grafana version are you using?
```Version 3.0.4 (commit: v3.0.4)```

- What datasource are you using?
```InfluxDB version: 0.13.0```

- What OS are you running grafana on?
```Centos7 x86_64```

## Description
- What did you do?

 - Added a template variable ```$adc_gain``` with some pre-defined values (0,1,0.001763), and enabled user-defined values.
 - Added a graph with the following query:
```SELECT mean("value") *$adc_gain FROM "adc" WHERE $timeFilter GROUP BY time($interval) fill(null)```
 - If I select a non-integer value for ```$adc_gain```, the dot is being escaped. Strangely this doesn't happen if I graphically create the query (using a ```math``` element).
 - Changing the query to ```SELECT mean("value") */$adc_gain/ FROM "adc" WHERE $timeFilter GROUP BY time($interval) fill(null)``` doesn't help (Putting the $adc_gain into double-quotes doesn't, either).

- What was the expected result?
No escaping

- What happenend instead?
 - The dot was escaped:
```;SELECT mean("value") *0\.00174216 FROM "adc" WHERE time > now() - 1h GROUP BY time(2s) fill(null)```
  - So InfluxDB complained:
```
{
  "error": "error parsing query: found \\, expected FROM at line 1, char 116",
  "message": "error parsing query: found \\, expected FROM at line 1, char 116"
}
```
(The full query contained another SELECT, so the char count is not correct)

## Proposal
- No escaping of template variables if it's being used in the columns part of a select clause
- Alternatively: ... if the template variable is contained in slashes (same as a regex)

**Comment by torkelo** [comment]
Right now if you use raw query (text editor mode), then template variables will always be regex escaped.
