### ISSUE TITLE
Accessing Custom Variables Returns Only First In List

### ISSUE THREAD

**Issue by astrocaribe** [grafana/grafana#53861]
![2022-08-17 15 03 10](https://user-images.githubusercontent.com/2208060/185233310-1aa547c6-0003-446c-b82a-f82eb5ce443d.gif)

**What happened**:
Attempting to use a custom variable in a dashboard with a defined list of values returns only the first item in the variable list.

**What you expected to happen**:
Accessing the custom variable should return the configured list in a query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new variable, custom type, and populate the list with options
2. After saving, access the variable in a query, e.g:
```
  rate(etl_facility_success_metrics{facility=~"$gulf_coast_div"}[5m])
```
3. Run query in a panel

**Anything else we need to know?**:

Inspecting the query while building is returning an erroneous query for the variable:
![Screen Shot 2022-08-17 at 3 14 09 PM](https://user-images.githubusercontent.com/2208060/185234166-49998537-4e5c-43b5-9684-ea235677eb8a.png)

Even though the raw query contains the correct usage.
![Screen Shot 2022-08-17 at 3 14 44 PM](https://user-images.githubusercontent.com/2208060/185234248-18e22970-75e8-4455-b7d1-b9e2a49b3a9e.png)

**Environment**: 
- Grafana version: v9.1.0-beta1 (947ad8045b)
- Data source type & version: Prometheus v2.17.0
- OS Grafana is installed on: CentoOS v7
- User OS & Browser: Brave [Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (arm64)](https://brave.com/latest/)
- Grafana plugins: None
- Others: Mac OS Monterey (12.4 Arm)

**Comment by dprokop** [comment]
@astrocaribe thank you for opening the issue. I think the problem is that your variable is hidden and the actual option selected is the first one by default. If you make the variable visible and select more than one option or All, it will work as expected.
