### ISSUE TITLE
Log browser query doesn't work correctly on OSX/Firefox when adding a tilde after a pipe "|~"

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [grafana/grafana#53877]
**What happened**:
When I try to search text with the pipe+tilde operator "|~" it breaks on OSX/FF and removes the tilde, when I enter the next key. It is impossible to use this operator, except when I write the query in a text editor and copy paste it over?

Also it is not possible to move with the arrow keys completely to the right (see screencast), it stops before the tilde.

**What you expected to happen**:
Pipe+Tilde operator should be working, tilde shouldn't be removed

**How to reproduce it (as minimally and precisely as possible)**:
Go to the Explore-> Log Browser and add a query like:

```
{app="test123"} |~ "
=> gets replaced with
{app="flave-rails"} |" 
immediately
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.11
- Data source type & version: Loki latest
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Firefox 103.0.2 64 Bit, OSX 12.3.1 Monterey
- Grafana plugins: Loki
- Others:

![screencast 2022-08-18 10-09-13](https://user-images.githubusercontent.com/10075/185345762-85035d31-6df1-4ef9-9a6f-cb2446643e39.gif)

**Comment by zuchka** [comment]
Thanks for creating this issue, @h0jeZvgoxFepBQ2C 

> Grafana version: 7.5.11

Grafana 7 is EOL. We don't really support it anymore. v9 is way more feature rich. Highly recommend you upgrade :+1:

**Comment by h0jeZvgoxFepBQ2C** [comment]
ahh ok I see, sorry, seems rancher is shipping a really old grafana installation then
