### ISSUE TITLE
Incorrect time period with multiple interval variables

### ISSUE THREAD

**Issue by Mikanoshi** [grafana/grafana#5387]
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

Grafana 3.1.0 (commit: v3.0.4+204-g1584dac)
InfluxDB 0.13.0
FreeBSD 9.2 RELEASE p15

Multiple interval variables with enabled auto option (but different number of steps) produce the same time period (it's always equal to the period of the first var).

**Comment by bergquist** [comment]
Not sure I understand this issue.

It's not possible to have multiple interval parameters in influxdb queries.

**Comment by Mikanoshi** [comment]
Variables are in grafana templating. InfluxDB has nothing to do with the issue really))

**Comment by Mikanoshi** [comment]
All interval variables are using a single internal variable to store period value, maybe that's the problem?
https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L135
