### ISSUE TITLE
PhantomRenderer / Direct Image Issue

### ISSUE THREAD

**Issue by cvern3221** [grafana/grafana#5388]
Running 3.0.4 with a Graphite backend. No problem in terms of gathering and viewing data. Trying to use the "Direct link rendered image" sharing feature and am running into an issue.

If I set root_url to "HTTPS://###.###.###.###:443 (I'm running SSL without any other issues) PhantomRenderer just serves up an image of the Grafana login/sign up page of the site. The PhantomRenderer URL it targets per the log can be accessed in the browser and it properly loads the data without a problem.

If I leave the root_url as it's default expression with variables, but change the domain to the IP (HTTPS and the port are already set in the ini) it seems like PhantomRenderer is faster in its request, but all I get is a blank (all black) image. The target URL per the log still shows the correct data when accessed directly via a browser.

Read multiple tickets talking about this being a PhantomJS SSL issue and to set it to either tlsv1 or "any" for SSL protocol, but I'm not sure how to do it.

Thanks in advance! I've tried a million things.

--------------------

UPDATE

It appears that I can actually generate a good majority of my data as images which come out properly sized and alright. However, some data images show up incorrectly sized (only utilizing 50% of image height for example) or show up as blank as originally described. In every case the data can still be accessed directly via browser without issue. Is there some sort of timeout for Phantom that larger data sets to crash out?

**Comment by cvern3221** [comment]
@ #1933 - this appears to be related.

**Comment by torkelo** [comment]
there is a 10 second timeout

**Comment by cvern3221** [comment]
It doesn't even come close to ten seconds. It presents the blank finalized
image within the first four seconds.

**Comment by torkelo** [comment]
Ok, strange, do you have any log outputs?
