### ISSUE TITLE
Loki: Detected fields shows labels 	[object Object] in LogDetailsRow

### ISSUE THREAD

**Issue by adambro** [grafana/grafana#53897]
**What happened**:

Detected fields shows `labels 	[object Object]` in LogDetailsRow.

**What you expected to happen**:

The `[object Object]` is a result of bad casting JS object to string, obviously.

However I wonder if the `labels` fields is not redundant at all. When I peek in React inspector the `row.labels` field seems to have all the predefined labels of the log entry.

In other words `labels` field seem to be special. I'm deducting that from the following snippet taken from `LogDetails.tsx` file:
```ts
    const labels = row.labels ? row.labels : {};
    const labelsAvailable = Object.keys(labels).length > 0;
    const fields = getAllFields(row, getFieldLinks);
```

**How to reproduce it (as minimally and precisely as possible)**:

Put something in `labels` field, as tests use empty object, so it might go unnoticed.

**Anything else we need to know?**:

I'm happy to contribute the fix, but I'd need to know if labels should be displayed on the UI at all. Let me know, please :)

**Environment**:
- Grafana version: 9.0,3
- Data source type & version: Loki helm chart 6.2.2
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on Ubuntu
- Grafana plugins: none
- Others:

**Comment by MatheusBeniniF** [comment]
hey @adambro, can you give me the steps to reproduce this?

**Comment by adambro** [comment]
@MatheusBeniniF you can see the problem on playground, just go to log details. Example link:
https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%22appfelstrudel%5C%22%7D%22,%22queryType%22:%22range%22,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-30m%22,%22to%22:%22now%22%7D%7D

**Comment by mellieA** [comment]
![Screen Shot 2022-08-19 at 3 50 18 PM](https://user-images.githubusercontent.com/18175287/185711844-84441c6a-35b7-41de-be6d-6def8e296cc6.png)

**Comment by gabor** [comment]
hi @adambro , this has been fixed in grafana9.1.0 (in https://github.com/grafana/grafana/pull/53319 ), we do not show that `labels` field there anymore.

**Comment by adambro** [comment]
I haven't found #52455 issue before. Thanks!
