### ISSUE TITLE
In Grafana 9.1.0, the "General" folder contains both folders and dashboards.

### ISSUE THREAD

**Issue by SaigaGentil** [grafana/grafana#53908]
**What happened**:
After upgrading to Grafana 9.1.0, I noticed that the "general" folder contains both folders and dashboards, and one can't tell which is a folder and which is not. In previous Grafana versions, the general folder would only contain dashboards that have not been explicitly categorized to a folder.

**What you expected to happen**:
I expect to see the "general" folder only containing dashboards that have not been explicitly categorized to another folder.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create another dashboard in a addition to the default "general" folder.
2. Create a dashboard and don't explicitly put it in a folder. This means that by default it will go to the "general" folder
3. Now if you check the general folder, you can see that both the folder and the dashboard are in there and you can't tell which is a dashboard and which is not.

**Anything else we need to know?**:
-

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: N/A
- OS Grafana is installed on: Grafana in Docker on Red Hat Enterprise Linux 7.9
- User OS & Browser: Microsoft Edge on Windows 10
- Grafana plugins: N/A
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @SaigaGentil 

can you include a scrreencast or some screenshots? I'm having trouble following you.... thank you!

**Comment by tomwennerstrom** [comment]
Maybe this will help. I have the same problem with 9.1.0.

![image77](https://user-images.githubusercontent.com/112690250/188098791-bf2edc31-0f71-48b6-8a05-b93bab5eb3dd.png)

**Comment by SaigaGentil** [comment]
Thanks @tomwennerstrom. That's exactly what I was describing. @zuchka, I hope that helps.

**Comment by tomwennerstrom** [comment]
Hi @ashharrison90. Nope, I don't have this problem any more. (v9.1.7)

**Comment by ashharrison90** [comment]
thanks for the prompt response ❤️ 

closing as fixed
