### ISSUE TITLE
Query Editor: Query name should have a range limit

### ISSUE THREAD

**Issue by SanthoshS20** [grafana/grafana#53900]
**What happened**:
In the Loki Query Dashboard, query name doesn't have a range limit. It accepting **_N_** number of characters and updated. Long name was accepted and place above the disable/remove/duplicate query button. User not able to view those buttons.

**What you expected to happen**:
In the Loki Query Dashboard, query name should have a range limit. It should not accept _**N**_ number of characters.

**How to reproduce it (as minimally and precisely as possible)**:
Step 1: Go to the Loki Query Dashboard
Step 2: Change the query name with a long paragraph.
Step 3: Click Enter 

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/37366893/185422384-daee1380-2066-4a80-9eaa-a57edc6989b4.png)

**Environment**:
- Grafana version: 9.0.7
- User OS & Browser: Windows 10 & Google Chrome

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:


and is it present in Explore and in the qeury builder for a panel?

**Comment by SanthoshS20** [comment]
> do you think you could try and replicate this on our public sandbox, https://play.grafana.org? 🙏
> 
> and is it present in Explore and in the qeury builder for a panel?

Yes @zuchka. I tried in public sandbox and it is reproducible. It is present in Explore and on query builder

**Comment by Toledodev** [comment]
Hey @SanthoshS20, what the characters length should be?

**Comment by SanthoshS20** [comment]
> Hey @SanthoshS20, what the characters length should be?

80 - 100 Characters

**Comment by Toledodev** [comment]
Ok :+1:

**Comment by gabor** [comment]
@grafana/observability-experience-squad is this your area?

**Comment by Elfo404** [comment]
AFAIK that component is owned by @grafana/dashboards-squad, assigning it to you :)
