### ISSUE TITLE
Alert manager data source yaml doesn't show how to specify the implementation

### ISSUE THREAD

**Issue by dannystaple** [grafana/grafana#53907]
**What happened**:

The Alertmanager UI shows an "Implementation" drop down, with Mimir, Cortex and Prometheus. 
The documentation at https://grafana.com/docs/grafana/latest/datasources/alertmanager/#alertmanager-implementations does not show how to configure this in the provisioning yaml.

**What you expected to happen**:

A reference for the alertmanager provisioning YAML - the possible configuration options, including implementation, auth and the types of value accepted here.

**How to reproduce it (as minimally and precisely as possible)**:

Compare the UI options with the documentation.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.0 (82e32447b4)
- Data source type & version: alertmanager
- OS Grafana is installed on: grafana/grafana container image
- User OS & Browser: Chrome, MacOS
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Have you seen the newest stable API endpoints for provisioning Grafana alerts?

https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/api.json

**Comment by fberube-psee** [comment]
If I want to provide a datasource alertmanager with infra as code, how to set the implementation type (cortex, mimir, prometheus) the documentation does not specify it.

**Comment by dominik-horb-umg** [comment]
I was able to get this work with Ansible by setting this inside the `jsonData` field:

```yaml
jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
```

**Comment by dannystaple** [comment]
> Have you seen the newest stable API endpoints for provisioning Grafana alerts?
> 
> https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/api.json

Hello, this shows how to create Grafana alerts, and will be useful for some types. However, where we use prometheus alerts (and make use of the handy promtool test feature), or Loki alerts we route through to alert manager with a config as code approach. While interesting - I don't think it answers the request on documenting the datasources `type: alertmanager`. I've not been able to make this work with a local cortex backend.

**Comment by armandgrillet** [comment]
https://grafana.com/docs/grafana/latest/datasources/alertmanager/ includes that.
