### ISSUE TITLE
When only anonymous users, /login pages still renders login page

### ISSUE THREAD

**Issue by jdelgad** [grafana/grafana#5392]
Only anonymous users are permitted on my grafana instance, but when visiting /login they are not redirected to /. The same goes for other routes such as /org/create.

Please include this information:
- What Grafana version are you using?
2.1.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux

- What did you do?
Browsed to /login and /org/create routes

- What was the expected result?
Redirected to / since only anonymous logins are allowed

- What happened instead?
I was routed to the correct page for nearly every route instead of /

**Comment by torkelo** [comment]
yes, you can mix anonymous and login so of course login page shows login page :)
