### ISSUE TITLE
AccessControl: v9.1.0 /api/datasources/name/:name requires datasources:read from the Admin

### ISSUE THREAD

**Issue by vooon** [grafana/grafana#53934]
**What happened**:

With Grafana 9.1.0 Ansible module `community.grafana.grafana_datasources` fails with "Permission denied".
After debug i've found that request to get datasource fails:
```
curl -u admin:admin http://localhost:3000/grafana/api/datasources/name/Prometheus | jq .
{
  "accessErrorId": "ACE9052423734",
  "message": "You'll need additional permissions to perform this action. Permissions needed: datasources:read",
  "title": "Access denied"
}
```

Only `/api/datasources/uid/:uid` responding normally (404 in my case, as nothing was setup).

**What you expected to happen**:

RBAC mustn't block admin.

**How to reproduce it (as minimally and precisely as possible)**:

Install 9.1.0, try to use ansible module to setup sources.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.0, from official RPM
- Data source type & version: n/a
- OS Grafana is installed on: CentOS 8 Stream
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:
  - Mariadb was used
  - `root_url = http://example.com/grafana`
  - `serve_from_sub_path = true`

**Comment by kalleep** [comment]
Related to https://github.com/grafana/grafana-enterprise/issues/3516

**Comment by ju4nmg** [comment]
Having this same error on terraform after manually deteling the data_source on grafana, cant create or do anything after that ```grafana_data_source.azure: Refreshing state... [id=44]
Error: status: 403, body: {"accessErrorId":"ACE9028648010","message":"You'll need additional permissions to perform this action. Permissions needed: datasources:read","title":"Access denied"}```
