### ISSUE TITLE
LDAP configuration: paths to root CA cert files should contain spaces

### ISSUE THREAD

**Issue by DragoonAethis** [grafana/grafana#53942]
**What happened**: LDAP configuration does not allow pointing to CA certs with spaces in the path. Grafana tries to [split the provided path on spaces](https://github.com/grafana/grafana/blob/main/pkg/services/ldap/ldap.go#L101) and load each space-separated path as a separate file. There's nothing in the [config file](https://github.com/grafana/grafana/blob/main/conf/ldap.toml#L17) or the [associated struct](https://github.com/grafana/grafana/blob/main/pkg/services/ldap/settings.go#L29) that suggests this is happening.

**What you expected to happen**: Grafana loads the provided path without any splitting by spaces et al.

**How to reproduce it (as minimally and precisely as possible)**:
- In LDAP configuration, point `root_ca_certs` to a path with spaces in it (for example `/opt/certs/Nice Cert.crt`)
- Open the Grafana LDAP config page, where it'll complain about not being able to open `/opt/certs/Nice`.

**Anything else we need to know?**:

- This behavior was introduced back in 2015 with [this commit](https://github.com/grafana/grafana/commit/458e6da7001eee58ba677784bd73a04a01839f6a) - it looks like the logic for that was just a copy-paste from the host reading logic below.
- It looks like someone else hit the same issue [here](https://community.grafana.com/t/root-certificate-path-grafana-on-windows-server/48831).
- A new `root_ca_certs: []string` config value would be the best, where each path from the TOML list gets used as is.
- If not, a comment needs to be added that spaces in this single string separate multiple paths.

**Environment**:
- Grafana version: 9.1.0 (but affects all versions since ~2015)
- OS Grafana is installed on: Official Alpine container (Docker on Ubuntu 20.04).

**Comment by DragoonAethis** [comment]
I'm not much of a Go dev, but it looks simple enough to handle - if you decide that adding a new config value is the way to go, I could give it a try and send out a PR :)

**Comment by mgyongyosi** [comment]
@cindy Thanks for your interest in fixing this 💯 . I assigned the issue to you. In case you need assistance feel free to reach out.

**Comment by Jguer** [comment]
https://github.com/grafana/grafana/pull/61288 this PR introduces a good standard to follow

**Comment by david-shiko** [comment]
Closed?

**Comment by DragoonAethis** [comment]
Thank you!
