### ISSUE TITLE
Use generated Dashboard schema in DashboardModel

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#53941]
We currently have an [experimental Dashboard cue schema](https://github.com/grafana/grafana/blob/a87c6853453c51b3c5e1159b94d44f60dc97e81a/pkg/coremodel/dashboard/coremodel.cue) that we're [codegen-ing to typescript](https://github.com/grafana/grafana/blob/a87c6853453c51b3c5e1159b94d44f60dc97e81a/packages/grafana-schema/src/schema/dashboard/dashboard_experimental.gen.ts/#L221).

At the moment, when we [load a DashboardModel](https://github.com/grafana/grafana/blob/a87c6853453c51b3c5e1159b94d44f60dc97e81a/public/app/features/dashboard/state/DashboardModel.ts/#L128), we accept the base input as `any`, which means the input is barely type checked at all, which makes it easy for the types to be inaccurate and [cause bugs](https://github.com/grafana/grafana/pull/53722).

To improve the correctness of the cue Dashboard schema, and DashboardModel and PanelModel we should use this schema as the input to both DashboardModel and PanelModel. Also when we serialise the DashboardModel to save, we should convert the DashboardModel to the generated Dashboard schema interface.

Possible tasks:
 - Export the generated Dashboard schema ts interface
 - Investigate whether it's possible/good idea to feature flag a typescript type.
 - Change the type of `data` in the DashboardModel constructor to the Dashboard schema
   - This will probably cause a bunch of knock on typescript errors that will need to be addressed either in code, or by updating the schema
 - Change the type of the model in [PanelModel constructor and restoreModel function](https://github.com/grafana/grafana/blob/a87c6853453c51b3c5e1159b94d44f60dc97e81a/public/app/features/dashboard/state/PanelModel.ts/#L201-L209) to the Panel schema.
   - This will probably cause a bunch of knock on typescript errors that will need to be addressed either in code, or by updating the schema
 - change DashboardModel getSaveModelClone to return the Dashboard schema
    - This might be problematic due to all the places that call this, so it might be better to add a new function for serialisation 
  - change PanelModel getSaveModel to return the Panel schema
    - This might be problematic due to all the places that call this, so it might be better to add a new function for serialisation

**Comment by joshhunt** [comment]
One of the goals of this would be to start to encourage more people to enable the feature flag that validates dashboard schemas on save https://github.com/grafana/grafana/blob/a87c6853453c51b3c5e1159b94d44f60dc97e81a/pkg/services/featuremgmt/registry.go/#L195-L200

**Comment by natellium** [comment]
@ivanortegaalba can you look into this one and see if we can close it?

**Comment by ivanortegaalba** [comment]
`Dashboard` type is already used in `DashboardModel`, so we can close this issue. Next steps here #60590
