### ISSUE TITLE
Navigation: Add profile menu to top navbar

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#53947]

**Comment by Toledodev** [comment]
Hey @ashharrison90, this is the expected behavior?
![Screenshot from 2022-08-19 11-24-09](https://user-images.githubusercontent.com/87545086/185640122-c9dc74ea-9142-4ba3-9845-ce4e26c30a06.png)

**Comment by ashharrison90** [comment]
hi @Toledodev 👋 

no, we have a completely new design we're working on. 🙂
