### ISSUE TITLE
Bug report - Dashboard doesn't change after being prompted (and saving) "unsaved changes" modal

### ISSUE THREAD

**Issue by hailthemelody** [grafana/grafana#5395]
**What Grafana version are you using?**

3.0.4

**What datasource are you using?**

InfluxDB

**What OS are you running grafana on?**

Ubuntu LTS 14.04

**What did you do?**
- Edited a dashboard
- Clicked on another dashboard before saving changes
- Was prompted to cancel, ignore, or save
- Pressed save
- It saved, but stayed on the current dashboard.

**\- What was the expected result?**

After saving it should have gone the dashboard I requested.

**\- What happenend instead?**

After saving it stayed on the current dashboard.

**Comment by hailthemelody** [comment]
I would be happy to explore developing this functionality, but wanted to check in first if this was the intended behaviour.

**Comment by torkelo** [comment]
I agree, it should change dashboard after successful save

**Comment by marefr** [comment]
This seems fixed in latest version so closing this.
