### ISSUE TITLE
[Feature Request] Populate custom template values via http endpoint

### ISSUE THREAD

**Issue by millerjp** [grafana/grafana#5397]
When defining variables it is currently only possible to populate them via data queries or hard coded values. It would be extremely useful if it would be possible to extend the custom template variables (http://docs.grafana.org/reference/templating/)  to support populating the values via a http endpoint returning some JSON adhering to a specified format.

For example - a dashboard with the custom templated variables - `$service, $datacenter, $rack` . Define a http endpoint to call when the dashboard loads (potentially client side) which returns a JSON payload

```
{
   "variables":{
      "service":[
         "service 1",
         "service 2"
      ],
      "datacenter":[
         "dc 1",
         "dc 2"
      ],
      "rack":[
         "rack 1",
         "rack 2"
      ]
   }
}
```

This could potentially be extended further to support more complex structures with relationships between variables eg service 1 is only in datacenter dc 1, but arguably this complexity is better serviced via the existing datasource query functionality.

The goal of this feature request is to provide a slightly more flexible alternative to hardcoding comma separated values in dashboards to support more flexible reuse and refactoring.

**Comment by torkelo** [comment]
you could easily do this today by using the simple json data source , 
and implement the search api request 
https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js

**Comment by millerjp** [comment]
Thanks - I will give that a go!

**Comment by linar-jether** [comment]
Currently, we're using a hidden html panel at the bottom of the page as a more simple (but very hacky) alternative to a datasource...

Example to create a variable with today's date when the dashboard loads
```html
<script>
var t = angular.element('grafana-app').injector().get('templateValuesSrv');
var varName = 'Today';
var today = t.dashboard.formatDate(undefined, 'YYYYMMDD')
var varValue = { text: today, value: today };
var tVar = _.findWhere(t.variables, { name: varName })
t.setVariableValue(tVar, varValue);
t.variableUpdated(tVar);
</script>
```

**Comment by linar-jether** [comment]
Update for current grafana version:

``` html
<script>
var t = angular.element('grafana-app').injector().get('templateSrv');
var dash = angular.element('grafana-app').injector().get('dashboardSrv').dash;
var varName = 'Today';
var d = new Date();
d.setDate(d.getDate() - 1);
var today = dash.formatDate(d, 'YYYYMMDD');
var varValue = { text: today, value: today };
var tVar = t._index[varName];
tVar.setValue(varValue);
t.updateTemplateData()
</script>
```

**Comment by torkelo** [comment]
Given the plugin architecture this is simple to do with either custom plugins or plugins like , https://github.com/grafana/simple-json-datasource
