### ISSUE TITLE
Call out key differences by layout types

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#53978]
Identify the key differences between layout types

**Identified Layout Types**
- Standard
- Wizard
- Grid
- Panel Edit
- Explore
- Dashboard

**Comment by torkelo** [comment]
@staton-hyse11 

Not sure we have that many layouts (in the core app at least), not sure what you mean by layouts. Do you mean full page layouts or small section layouts (card lists). 

* Standard?: you mean our current page header with tabs? 
* Grid? Do you mean the grid layout we have for cards in some list views like plugin list? 
* Explore: Explore does not really have a unique layout, it's like a dashboard but with a simple panel layout, and the unique feature of supporting a split view
