### ISSUE TITLE
[Bug]: InfluxDB & tag value auto complete issue with upper case tag values

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#5399]
* **I'm submitting a ...**
- [ ] Bug report

When editing a query the search text of the drop down box to find metrics only support lower case text, even if the metric itself has upper case characters. It returns no results when a single upper case letter is entered. I would expect the search text to be case insensitive.  

Please include this information:
- What Grafana version are you using?      3.0.4
- What datasource are you using?              Influx (>0.10)
- What OS are you running grafana on?     Redhat Linux

**Comment by efficks** [comment]
@torkelo I confirm the same problem with graphite and grafana version 2.6.0

**Comment by xianzi25** [comment]
Grafana allows you to reference queries in the Query Editor by the row that they’re on. If you add a second query to graph, you can reference the first query simply by typing in #A. This provides an easy and convenient way to build compounded queries.   

Some metrics  prefixed with [A-Z] will conflict with its ${order} ?
