### ISSUE TITLE
[importent][feature request]Alerting: Add webhook custom fields

### ISSUE THREAD

**Issue by Fury76** [grafana/grafana#53993]
Hi,
Can you add a new feature to the webhook that can support custom fields and values, so that you can use the webhook to meet many scenarios. For example, if there is a new im system, you only need to support the access of the im system according to the corresponding fields of the im system and the template, without the need for separate development

like this:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/7465355/185774301-6d8d7b98-45e9-4f6c-acf2-266a5ba80386.png">

**Comment by gelicia** [comment]
Hello, please add new feature requests in the [grafana discussions page](https://github.com/grafana/grafana/discussions). Please see https://github.com/grafana/grafana/discussions/36963 for more information.
