### ISSUE TITLE
while building the "build.go" in intellij idea ide..I got an error like

### ISSUE THREAD

**Issue by yuvaraj951** [grafana/grafana#5400]
"/tmp/Build github.comgo"
GOROOT=/usr/local/go
GOPATH=/home/gogimcodev2/src/github.com:/home/gogimcoitdev2/IdeaProjects
/usr/local/go/bin/go build -o "/tmp/Build github.comgo" /home/gogimcodev2/src/github.com/grafana/grafana/build.go

> **"Failed  to open  package.json"**

**Comment by torkelo** [comment]
must be an issue with intellj, please open support ticket with intellij, not sure what could be the cause, npm has no issue reading package.json
