### ISSUE TITLE
upgrade grafana from 9.0.2 to 9.1.0, does not send log volume query for specifical expr

### ISSUE THREAD

**Issue by hanjm** [grafana/grafana#54017]
**What happened**:
I upgrade grafana from 9.0.2 to 9.1.0, and the loki-like datasoruce query logvolume broken, the grafana frontend does not send log volume query to the backend datasource, the behavior changed.
the expr is '1=1'
**What you expected to happen**:
send log volume query to the backend datasource.
**How to reproduce it (as minimally and precisely as possible)**:
add loki datasource, input an expr '1=1'
open the chrome network, it not send a query like 'sum by (level) ... ' request.
**Anything else we need to know?**:
I try to debug it 
![image](https://user-images.githubusercontent.com/7621241/185897759-5397a462-c6c8-43ac-b563-d3edf5f530dd.png)
![image](https://user-images.githubusercontent.com/7621241/185897779-28b6ec69-c25a-4027-9fe3-396d2ee9853f.png)

https://github.com/grafana/grafana/pull/50711/files#diff-2e4d3a3dbd431f921794de33720c6fc3ac7a8a2f6dbde31424e487080bb572c1R111 is `!isMetricsQuery(expr)`, 
https://github.com/grafana/grafana/pull/51795/files#diff-2e4d3a3dbd431f921794de33720c6fc3ac7a8a2f6dbde31424e487080bb572c1L701 remove the `isMetricsQuery` function,
https://github.com/grafana/grafana/pull/51795/files#diff-2e4d3a3dbd431f921794de33720c6fc3ac7a8a2f6dbde31424e487080bb572c1R112 modify it to `isLogsQuery(expr)`.

IMO `!isMetricsQuery(expr)` is more suitable for this. beacause judge metrics query is more small scope, it always have a function. https://grafana.com/docs/loki/latest/logql/metric_queries/
**Environment**:
- Grafana version: 9.1.0
- Data source type & version: loki-like custom datasource
- OS Grafana is installed on: linux
- User OS & Browser: macos chrome
- Grafana plugins: No
- Others:

**Comment by gabor** [comment]
hi @hanjm , we only show the logs-volume histogram for queries that produce logs (meaning they return data with `"resultType": "streams"`.

your example query `1=1` is not a valid logQL query. if you try to send that query to Loki, it returns an error message.

can you show an example where a valid Loki LogQL logs-producing query is run, and not producing a logs volume histogram?

**Comment by hanjm** [comment]
@gabor the backend is a loki-like custom datasource backend, not the offical loki backend.  😢 
yes, the `1=1` is not a valid logQL query, it works fine before 9.1.0, the grafana behavoir changed.

**Comment by gabor** [comment]
@hanjm i'm sorry but the loki datasource is maintained to work correctly with the Loki database.
the new code better describes what we are doing (only run the logs-volume-query for logs-producing queries), so we will not revert the change.

you could perhaps create your own grafana datasource as a grafana plugin, to handle your loki-like custom database.
