### ISSUE TITLE
Timeline panel regression?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#54029]
The timeline panel used to look like this:

![image](https://user-images.githubusercontent.com/444037/185931730-08ab7eb9-61ca-4130-aaac-b028fd9c2863.png)

But since Aug ~8th now looks like this (missing values are red, not empty):

<img width="638" alt="image" src="https://user-images.githubusercontent.com/444037/185591657-9a489ff0-207c-4507-af6b-7c28fedd8449.png">

I believe this is a regression, similar to the one which occurred back in May and was fixed in https://github.com/grafana/grafana/pull/50054

/cc @ryantxu @cristiangreco

**Comment by codeincarnate** [comment]
Hey Tom, is there a value set for "no value"? The changes had been around that and I've seen a similar report here but was having trouble reproducing [#52449](https://github.com/grafana/grafana/issues/52449)

**Comment by tomwilkie** [comment]
Hi Kyle! The dashboard in question can be found here: https://ops.grafana.net/d/54b797d6caf45a842047f08226501169/grafana-cloud-slos?orgId=1&refresh=5m

There doesn't seem to be anything configured for "no value":

<img width="384" alt="image" src="https://user-images.githubusercontent.com/444037/186394135-174fd9b4-a54b-4cfe-bc46-0eea93fef0e3.png">

**Comment by codeincarnate** [comment]
Thanks so much Tom! I'll take a look at this today

**Comment by codeincarnate** [comment]
Hi Tom, sorry for the delay in update here as I wanted to take another look. From what I'm seeing in this case is that it appears the datasource is returning zero values and from what I can tell hasn't been affected by the null value transformation changes. Were there some Prometheus or configuration changes around August 8th that may have caused this?

**Comment by ahurtaud** [comment]
Hello,
Maybe this is a more general issue. In our grafana instance, we see sometimes that null value are replaced by 0, even on Explore !
![Screen Shot 2022-09-01 at 14 55 19](https://user-images.githubusercontent.com/25080995/187922433-d0a75bf1-8f08-404b-bcff-bc39ded08011.png)
![Screen Shot 2022-09-01 at 14 55 29](https://user-images.githubusercontent.com/25080995/187922459-8b1d1a0a-8634-4489-acb8-03b5c80bca3d.png)

but for some metrics (with longer null I believe?, it works)
(grafana 9.1.2)
