### ISSUE TITLE
[Bug Report] InfluxDB Querying from default retention policy

### ISSUE THREAD

**Issue by bmundt** [grafana/grafana#5403]
Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Centos 7
- What did you do? Used the query editor to try and query using the default retention policy.
- What was the expected result? Query the database using retention policy "default"
- What happened instead? 
Query the database using no retention policy or retention policy "DEFAULT". I believe this is because an error in the interpretation of the retention policies in influxDB. In influxDB at first there is one retention policy, "default" which keeps everything forever and it is originally set to be the "DEFAULT" retention policy. However, you can change that when creating a new retention policy. For example, in my database the default retention policy is "one_month". InfluxDB default to using "DEFAULT" if you do not specify a retention policy, which is what the query editor does when you select "default". This can be confirmed by switching to the raw query editor after building the query with the query builder.

![influx_bug_query_editor](https://cloud.githubusercontent.com/assets/11317863/16235690/c116bac8-37a3-11e6-92a8-c1b6a1f1ef7c.PNG)
![influx_bug_raw_query](https://cloud.githubusercontent.com/assets/11317863/16235688/c1136594-37a3-11e6-88f8-ca16b7067309.PNG)
![influx_one_month_query_editor](https://cloud.githubusercontent.com/assets/11317863/16235687/c1136da0-37a3-11e6-9f9c-b88f378385a4.PNG)
![influx_one_month_raw](https://cloud.githubusercontent.com/assets/11317863/16235689/c1158112-37a3-11e6-865b-aa44dded8a6d.PNG)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
that is what it means using the default, that the query does not contain the policy, so that InfluxDB will sue the default one
