### ISSUE TITLE
Status History panel doesn't show date/time in tooltip in 

### ISSUE THREAD

**Issue by txjmb** [grafana/grafana#54034]
**What happened**:
In earlier versions of Grafana, Status History panel showed timestamp in tooltip when mousing-over graph, however in 9.1, it doesn't:

V 9.1:
![image](https://user-images.githubusercontent.com/1986390/185943606-e1cd6389-6c14-4b0a-8e64-14370f4bda55.png)

**What you expected to happen**:
in V 8.5.2:
![image](https://user-images.githubusercontent.com/1986390/185943058-ed8ae10d-94a2-4bb7-8399-55b7d1009a16.png)
Encountered this issue while testing upgrade to 9.1.0.  Panels were copied directly from 8.5.2 to 9.1 install.

**How to reproduce it (as minimally and precisely as possible)**:
Compare behavior on older version to 9.1 for tooltip content on Status History panel.
**Anything else we need to know?**:

**Environment**:
- Grafana version:  Tested 8.5.2 (works), 9.1 (doesn't work)
- Data source type & version:
- OS Grafana is installed on:  Linux Docker Compose
- User OS & Browser:  Windows, Chrome
- Grafana plugins:
- Others:

**Comment by MatheusBeniniF** [comment]
what time is desired in the tooltip?

**Comment by gelicia** [comment]
@MatheusBeniniF the time is when the status was reported

**Comment by txjmb** [comment]
@MatheusBeniniF, I agree with @gelicia .  It should have the same behavior as it did before this was broken.
