### ISSUE TITLE
Grafana 9.1.0 shows dashboard folders as "open" instead of "closed"

### ISSUE THREAD

**Issue by jphx** [grafana/grafana#54048]
In Grafana 9.0.7 and earlier, when I browse dashboards, the folder list is shown closed, that is, without showing the individual dashboards in the folder.  Like this:

![grafana-closed-folders](https://user-images.githubusercontent.com/14140294/185955222-9db0dd17-0671-4111-b115-7584697dfc2b.png)

but in Grafana 9.10, the dashboard list is always open, showing not just the folder names, but also all the individual dashboards in the folders.  Like this:

![grafana-open-folders](https://user-images.githubusercontent.com/14140294/185955614-72f0eb2c-9543-4b60-88e9-5d8434348dc9.png)

Since we have _many_ folders and dashboards, this makes the list a lot more difficult to navigate.  Is it possible to restore the previous behavior of showing the folder list as closed?

One fact that may be relevant:  We use the Grafana Operator to manage our Grafana instance, and the Operator uses the Grafana dashboard API to load the dashboards into Grafana.  Could the use of the API be triggering the different UI state?

**Comment by juliopiubello** [comment]
Hi @gelicia! Hope you are doing well

When you add the labels it means that the suggestion from the issue was approved by the Grafana and therefore can be worked on?

**Comment by gelicia** [comment]
> Hi @gelicia! Hope you are doing well
> 
> When you add the labels it means that the suggestion from the issue was approved by the Grafana and therefore can be worked on?

@juliopiubello It means it is being organized and sent to the right team for triage. In a case such as this, the team would need to talk to find out if it was deliberately done or if it's a bug. Are you thinking about picking up this ticket?

**Comment by juliopiubello** [comment]
yep! my company wants to contribute to open source, we were taking a look and wondered which of the issues we could pick up

**Comment by ashharrison90** [comment]
hey @juliopiubello 👋 

i'm not able to reproduce this. both browse and search do remember which folders you've expanded previously... is it possible this is the behaviour you're seeing? 🤔 

https://user-images.githubusercontent.com/20999846/186393868-93896b7d-3bc4-4d4b-8c5c-858a887598a1.mp4

thanks!

**Comment by jphx** [comment]
Thanks for looking at it.  Unfortunately, it is definitely _not_ the case that a user previously interacted with this page to open folders and that the state is remembered from that interaction.  In our setup, Grafana is running under Kubernetes, with no persistent storage.  In my test, the Grafana pod had just started, so it's brand new with no remembered state.  I was the only user to interact with it, and the folders were open on my first viewing.

But I think this may be important information:  We use the Grafana Operator for populating the dashboards.  That is, the Grafana instance starts out with no dashboards or folders.  They are created after Grafana starts up by the Grafana Operator using the Grafana dashboard API (based on custom resources defined by the Grafana Operator).  Could this use of the Grafana API make Grafana _think_ the folders were recently opened by a user and thus be affecting the UI state?

**Comment by ashharrison90** [comment]
hey again @jphx (sorry, tagged the wrong person last time 🤦 )

the UI state for whether the folders are opened or not is purely a frontend thing, so the fact the pod has just started isn't really a contributing factor. 

this UI state also isn't tied to an individual grafana instance in any way currently, so if you've opened those folders on a previous instance of grafana it will remember that state in your new instance.

could you try opening your instance of grafana in an incognito window - are the folders still open then? 🤔

**Comment by jphx** [comment]
I've learned something new.  I didn't realize that state was maintained on the client instead of the server.  As you suggested, I opened Grafana in a private window and the folders now show as closed.  I then figured out how to delete the local data for this host name in my non-private window.  After I did that, the folder list appears as closed in that window also.  I apologize for taking up your time with this issue!

**Comment by jphx** [comment]
I still don't understand by the folder list appears different using Grafana 9.0.7 instead of 9.1.0.  Perhaps some identifiers changed, so the local data from 9.0.7 was expanding different folders when using 9.1.0?  Mumble, mumble.  I guess it's not that important.

**Comment by ashharrison90** [comment]
no problem @jphx , glad we got to the bottom of it 👍 

it's an area we're actively working on so please continue to keep an eye out for bugs and raise them whenever you see any, we really appreciate it! 🙌
