### ISSUE TITLE
Feature Request: Use AWS_ACCESS_KEY_ID and  AWS_SECRET_ACCESS_KEY env variables for cloudwatch authentication

### ISSUE THREAD

**Issue by micahhausler** [grafana/grafana#5405]
* **I'm submitting a ...**

- [x] Feature request

Please include this information:

- What Grafana version are you using? 
`3.0.4`

- What datasource are you using?
Cloudwatch

- What OS are you running grafana on?
docker image: `grafana/grafana:3.0.4`

I'd like to use Cloudwatch simply by setting the environment variables `AWS_ACCESS_KEY_ID` and  `AWS_SECRET_ACCESS_KEY`. The rest of Grafana configuration is a breeze by using `GF_<SectionName>_<KeyName>` environment variables, but manually munging the `~/.aws/credentials` file in a docker container is much less elegant, and not really practical. I may end up writing some wrapper script that shoves env vars into the aws credential file, but it would be preferable that Grafana could handle it.

I get that a user may have multiple profiles, (including multiple accounts), but maybe the secrets could be namespaced (something like `GF_CWPROFILE_<profile>_AWS_ACCESS_KEY_ID`)?

**Comment by torkelo** [comment]
data source config is not handled in grafana config (ini or env vars )

**Comment by fubar** [comment]
What kind of response is that? This is a feature request, not an inquiry about current behaviour.

**Comment by fubar** [comment]
@micahhausler See bottom of https://github.com/grafana/grafana-docker/blob/master/README.md:

## Configuring AWS credentials for CloudWatch support

```
docker run \
  -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_AWS_PROFILES=default" \
  -e "GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY" \
  -e "GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY" \
  -e "GF_AWS_default_REGION=us-east-1" \
  grafana/grafana
```

You may also specify multiple profiles to `GF_AWS_PROFILES` (e.g.
`GF_AWS_PROFILES=default another`).

Supported variables:

- `GF_AWS_${profile}_ACCESS_KEY_ID`: AWS access key ID (required).
- `GF_AWS_${profile}_SECRET_ACCESS_KEY`: AWS secret access  key (required).
- `GF_AWS_${profile}_REGION`: AWS region (optional).
