### ISSUE TITLE
ElasticSearch: fixed_interval problem with long intervals

### ISSUE THREAD

**Issue by alimli** [grafana/grafana#54075]
**What happened**:
ES returned an error "Elasticsearch error: [1:517] [date_histogram] failed to parse field [fixed_interval]"
<img width="1206" alt="Screen Shot 2022-08-22 at 18 03 49" src="https://user-images.githubusercontent.com/2609255/186095327-96333de3-bcf1-45b6-9ebb-0033179a7b1a.png">

**What you expected to happen**:
Query result is returned without errors.
<img width="1180" alt="Screen Shot 2022-08-22 at 18 03 30" src="https://user-images.githubusercontent.com/2609255/186095430-60e62c7c-2819-4d58-92e4-cd6a7cbec519.png">

**How to reproduce it (as minimally and precisely as possible)**:
When setting a "Min Interval" value less than 365days, it is working as expected.However if you sent a longer duration to "Min Interval" (e.g. 365d), the Interval is automatically converted to years. Accordingly ES returns an error because units up to days are supported for fixed_interval as explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-aggregations-bucket-datehistogram-aggregation.html).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: ES 7.10+
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: MacOS & Firefox
- Grafana plugins: CompareQueries plugin but looks unrelated
- Others:

**Comment by gabor** [comment]
hi @alimli , this is fixed now, should be available in Grafana9.1.2 .
