### ISSUE TITLE
Geomap: Coord not working with InfluxDB

### ISSUE THREAD

**Issue by sszilvasi** [grafana/grafana#54071]
**What happened**: Using an InfluxDB data source the Geomap plugin fails to display the geo points when specified as _Coords_.

**What you expected to happen**: The geo point markers to show up at the query result (lat, lon) coordinates.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start InfluxDB and Grafana
2. Load some valid (lat, lon) data points into InfluxDB
3. Create corresponding InfluxDB datasource
4. Create Geomap panel
5. Create query with two fields for (locations.lat, locations.lon)
6. Configure Geomap plugin:
   - Location: Coords
   - Latitude field: locations.lat
   - Longitude field: locations.lon
7. Observe that no markers show up on the map

![geomap-lat-lon-annot](https://user-images.githubusercontent.com/4781311/186059141-518b5d2c-32af-4736-b093-c768303012fc.png)

**Anything else we need to know?**:

Selecting the _first_ query field (locations.lat) for both the plugin Latitude and Longitude fields, the markers do show up.

![geomap-lat-lat-annot](https://user-images.githubusercontent.com/4781311/186059110-06572a11-2d15-48da-b97c-4c73b80c39be.png)

**Environment**:
- Grafana version: 8.1.0, 8.5.10, 9.0.2
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu 20.04 & Chrome
- Grafana plugins: Geomap
- Others:

**Comment by sszilvasi** [comment]
Thank you for the suggestion, switching "Format as" to "Table" solves the issue.

In trying to make the most out of first impressions, I would still expect "Format as" set to "Time series" to work as described above. Furthermore, based on the [documentation](https://grafana.com/docs/grafana/latest/visualizations/geomap/), I would also expect "Location" set to "Auto" to display the markers when the InfluxDB query fields are aliased as "lat" and "lon":

> **Auto** automatically searches for location data. Use this option when your query is based on one of the following names for data fields.
> - geohash: “geohash”
> - latitude: “latitude”, “lat”
> - longitude: “longitude”, “lng”, “lon”
> - lookup: “lookup”

**Comment by XANi** [comment]
Geomap in general is very confusing on how to make it work. I tried to use test data generator to give an example of a problem I'm having with prometheus GPS data and for example with test data source:

![image](https://user-images.githubusercontent.com/147394/230740548-a99bacde-1469-43f9-8b1b-19b780181adb.png)

When I set latitude and longitude to respective columns I get undisclosed error:

![image](https://user-images.githubusercontent.com/147394/230740567-e365c7d6-217b-468d-b988-0c22da73ee69.png)

While setting both to first data source produces something (obviously incorrect):

![image](https://user-images.githubusercontent.com/147394/230740592-f0cf026a-322b-4a9f-b0a6-7e56009f74c9.png)

and setting both to second data source gets error again:

![image](https://user-images.githubusercontent.com/147394/230740603-e339c486-114c-4dc2-9704-16cc5e470c37.png)

my Prometheus data is just something like

```
gps{type="latitude",host="hostname"} 12.345
gps(type="longitude",host="hostname"} 23.456
```
so I expected to just point it at 2 measurements (as all are measured at same time) and "just work". Instead I had to do 3D transform

![image](https://user-images.githubusercontent.com/147394/230741150-e2dddc79-3071-4e5c-867f-f9766106a2b1.png)

And only after that it started working.

**Comment by AurelienLourot** [comment]
I think [the documentation](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/geomap/) should clearly state how the data is expected to look like. When using InfluxDB, the documentation gives the impression that Grafana would simply expect measurements with a `latitude` and a `longitude` field. Unfortunately no point then shows up in the Geomap and there is no way to know what is wrong.

For future travelers:

1. If querying InfluxDB over InfluxQL, setting `Format as` to `Table` is needed, as stated in earlier comments.
2. If querying InfluxDB over Flux, a `Merge` transformation is needed, because the `Format as` setting isn't available.

Interesting related posts:

* https://github.com/grafana/grafana/issues/37861#issuecomment-898311968
* https://community.grafana.com/t/worldmap-panel-with-mysql-database/1871/13
* https://community.grafana.com/t/geomap-panel-not-working-for-me/61130

**Comment by AnonymousWebHacker** [comment]
> I think [the documentation](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/geomap/) should clearly state how the data is expected to look like. When using InfluxDB, the documentation gives the impression that Grafana would simply expect measurements with a `latitude` and a `longitude` field. Unfortunately no point then shows up in the Geomap and there is no way to know what is wrong.
> 
> For future travelers:
> 
>     1. If querying InfluxDB over InfluxQL, setting `Format as` to `Table` is needed, as stated in earlier comments.
> 
>     2. If querying InfluxDB over Flux, a `Merge` transformation is needed, because the `Format as` setting isn't available.
> 
> 
> Interesting related posts:
> 
>     * [Geomap with influxDB 2.0.7 #37861 (comment)](https://github.com/grafana/grafana/issues/37861#issuecomment-898311968)
> 
>     * https://community.grafana.com/t/worldmap-panel-with-mysql-database/1871/13
> 
>     * https://community.grafana.com/t/geomap-panel-not-working-for-me/61130

you save my day :)

**Comment by ozdeadmeat** [comment]
I had exactly the same image as you are getting. Although I used flux to sort it out. Take a look at this. Hope it helps

`
from(bucket: "ALL-DCS-SERVERS")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "SERVER STATS")
  |> filter(fn: (r) => r["_field"] == "UID" or r["_field"] == "Lon" or r["_field"] == "Lat" or r["_field"] == "MaxPlayers" or r["_field"] == "Name" or r["_field"] == "Players" or r["_field"] == "Description")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group()
  |> drop(columns: ["_start", "_stop", "_measurement"])
  |> yield(name: "last")
`
