### ISSUE TITLE
[Question] How to put annotation in Grafana

### ISSUE THREAD

**Issue by FheA** [grafana/grafana#5407]
Hello,

Actually i work on grafana with elasticsearch.

I want to put an annotation on my report.

![image](https://cloud.githubusercontent.com/assets/17929622/16261802/4d1039a4-386d-11e6-9d71-7557eb44f32e.png)

But i dont understand why dont show on my graph.

Maybe a problem in Lucene Query.

I  dont find exemple for lucene query with elasticsearch on grafana.

On the website grafana, Annotation with Elasticsearch is "TO DO".

Could you help me ?

Thanks a lot.

**Comment by torkelo** [comment]
sorry, you must have missed this in the issue template 

> - [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
