### ISSUE TITLE
[Bug] grafana-cli ReadPlugin function ignores dist/plugin.json

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#5410]
The `ReadPlugin` function in `pkg/cmd/grafana-cli/services/services.go` only looks for `plugin.json` in the root folder of a plugin.

This means that plugins like `raintank-worldping-app` which don't have a `plugin.json` in their root do not show up in the output of `grafana-cli plugins ls`, will not be upgraded by `grafana-cli plugins [update|upgrade]-all`, cannot be upgraded via `grafana-cli plugins [update|upgrade]` and cannot be removed via `grafana-cli plugins [remove|uninstall]` (side note: `uninstall` should be an alias of `remove`, right now it's unclear whether it's an alias or a separate action).

`ReadPlugin` should first look for `dist/plugin.json` then fall back to `plugin.json`, so that these plugins can be read successfully.

In researching this behavior I also noticed that `upgrade_command.go` uses `ReadPlugin` directly which `remove_command.go` uses `GetLocalPlugins` then loops over the results, I'm not sure what the reason is for that inconsistency.

**Comment by bergquist** [comment]
So this issue contains a few things that can be improved in the CLI tool. But lets focus on `plugin.json` / `dist/plugin.json` first.

I'm gonna fix this in the CLI so we can ship it with the 3.1 release today. But I don't think we should encourage multiple config location in the future. It's just messy.

**Comment by bergquist** [comment]
- [x] support for dist/plugin.json
- [x] remove/uninstall alias

Inconsistent ReadPlugin/GetLocalPlugin usage will be fixed after 3.1 is released.

**Comment by DanCech** [comment]
Cool!
