### ISSUE TITLE
Filter fields with null values in exported dashboard model

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#54126]
One background goal with schematization is that we disallow any field, in any schematized object, from containing an explicit `null` value. Much ink could be spilled over this, but it is essentially because it reduces ambiguity: by banning nulls universally, we make it so that no one authoring a schema ever has to answer the question, "if a field exists with value `null`, is that meaningfully different from that field being absent?"

#41385 helped a lot with this by purging nulls from dashboard JSON that's sent for save. But we're still producing nulls on export, which is why PRs like #54124 end up happening - to fix something that was exported (and avoided the test that should have caught it that i only just fixed in #53797 😱).

We need to go the additional step of also stripping nulls from exported dashboard JSON.

cc @joshhunt @ryantxu

**Comment by joshhunt** [comment]
We use `Infinity` in the dashboard model ([as a sentinel value](https://github.com/grafana/grafana/blob/f8bde4df09ea8449693f0ed63bab9d4ef5179d63/public/app/features/dimensions/editors/ThresholdsEditor/ThresholdsEditor.tsx/#L50)). When browsers stringify Infinity, it converts it to null. [sortedDeepCloneWithoutNulls](https://github.com/grafana/grafana/blob/f8bde4df09ea8449693f0ed63bab9d4ef5179d63/public/app/core/utils/object.ts) doesn't handle this.

**Comment by sdboyer** [comment]
i have to think on it a bit, but that feels like one case where it'd be OK to break the "no nulls in JSON" rule. That's simply because, if browsers stringify `Infinity` as `null`, then that's a) a meaningful `null`, because it is being used to represent a value that is not in the set of values directly representable with `number`, and b) doesn't require any special handling in our serialization algorithm.

That said, i am concerned about how we would account for JS having both [negative](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY) and [positive infinity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/POSITIVE_INFINITY) - `null` can only be assumed to correspond to one of those.
