### ISSUE TITLE
Clock panel crash: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by baur** [grafana/grafana#54128]
**What happened**:

**Can not migrate dashboards with Clock panel to Grafana 9.1**

![image](https://user-images.githubusercontent.com/2898361/186303973-499eb52c-5541-41d0-8bc0-801b861f23d7.png)

![clock-panel-crash](https://user-images.githubusercontent.com/2898361/186303893-0007182f-10f2-4ead-87c0-5bc0edb98028.gif)

**How to reproduce it (as minimally and precisely as possible)**:

- Add clock panel
- Choose color

**Environment**:
- Grafana version: v9.1.0 (82e32447b4)
- OS Grafana is installed on: Windows Server 10
- User OS & Browser: Chrome

**Comment by baur** [comment]
Can not migrate dashboards with Clock panel to Grafana 9.1

**Comment by torkelo** [comment]
Are you using latest version of plugin?

**Comment by baur** [comment]
> Are you using latest version of plugin?

Yes, needs updating ...
