### ISSUE TITLE
Unable to show stats in indian currency format 

### ISSUE THREAD

**Issue by rohit-innodeed** [grafana/grafana#54130]
**What happened**: There is a feature in grafana for showing the stats in indian currency format but when I used the feature, it started showing the large values in millions & billions.

![image](https://user-images.githubusercontent.com/101693459/186338728-050d7670-8191-42b1-bfe2-b89f0e572532.png)

![image](https://user-images.githubusercontent.com/101693459/186339479-cbbd7010-21df-4abe-8d6d-3fa72a8de219.png)

**What you expected to happen**: In indian currency format we have lacs and crores for large values, which grafana is unable to show.

**How to reproduce it (as minimally and precisely as possible)**: Just select the Indian Rupee currency in unit feature in stat panel as shown in the image above.

**Anything else we need to know?**: I know that grafana uses browser's native function for showing stats but even after using English(India) in my browser it's unable to show the stats in indian currency format whereas the stats in other platforms such as Youtube are showing in indian currency format with same settings as shown in the image below:

![image](https://user-images.githubusercontent.com/101693459/186341231-325abd41-1452-4e95-85b9-c17ba4b6a8b7.png)

![image](https://user-images.githubusercontent.com/101693459/186341273-d23f060f-7623-495b-b3f7-b01cb9d0c5a1.png)

![image](https://user-images.githubusercontent.com/101693459/186341116-a84592ca-3387-4625-80d7-5add0080d758.png)

**Environment**:
- Grafana version: Version 8.3.4
- Data source type & version: Infinity datasource 0.8.8
- OS Grafana is installed on: RHEL8
- User OS & Browser: Ubuntu 20.04 & Google Chrome
- Grafana plugins: Stat
- Others: Using AWS ec2

**Comment by usmangt** [comment]
Hi @rohit-innodeed,

Thanks for opening this case.

So, if I understand it correctly, it does work but, there is a missing part (or more like translation conversion) in the Indian currency for e.g.

1 Million (English) = 1 Lac (Indian Currency)
1 Billion (English) = 1 crore (Indian Currecny)

is this correct?

**Comment by rohit-innodeed** [comment]
Hi @usmangt 

Thanks for replying

Apart from translation conversion, there are following value differences:

1 Million (English) = 10 Lacs (Indian Currency)
1 Billion (English) = 100 Crores (Indian Currency) 

Please refer this link: https://en.wikipedia.org/wiki/Crore

**Comment by gelicia** [comment]
@rohit-innodeed thank you for the bug report. Unfortunately, Grafana does not yet have translation files/language support, and as you point out, our currency conversion is more basic and straightforward than what you are asking and what other apps provide. This would need to be tackled as a new feature instead of a bug. Please create a topic over in [discussions](https://github.com/grafana/grafana/discussions) and the correct team can prioritize it.

**Comment by rohit-innodeed** [comment]
Thanks for the information @gelicia.
