### ISSUE TITLE
Generating Prometheus queries with multi-value template variables

### ISSUE THREAD

**Issue by knweiss** [grafana/grafana#5413]
* **I'm submitting a feature request.**
- What Grafana version are you using? grafana-3.0.4-1464167696.x86_64
- What datasource are you using? Prometheus 0.19.3
- What OS are you running grafana on? CentOS 7.2
- What did you do?

I'm experimenting with Templating support. Using  template variables e.g. in Prometheus metric labels works fine. However, I'm wondering if it is possible to generate Graph queries with the contents of multi-value template variables as Prometheus metric names.

Example:

The query variable
```
$Metrics = metrics(node_load(1|5|15))
```
contains the (multi) values:
- `node_load1`
- `node_load5`
- `node_load15`

I would like to create a Graph panel that shows 1-3 plots **in the same graph** depending on the selected metrics in the `$Metrics` variable. I.e. it would be nice to somehow iterate over the values (metric names) and generate a query with each iteration (instead of configuring a hard-coded number of queries). I expected functionality like this in the Graph query editor:
```
foreach m in $Metrics: $m{instance="test1:9100"}
```
- What was the expected result?

I did not find a way to express this in Grafana and came to the conclusion that this is impossible right now.

(In **this** case a possible workaround is to always configure and show all three `node_load` metrics in the Graph panel and then ask the user to select a subset of metrics in the graph's legend. But what if the number of matching metrics is not fixed?)

**Comment by torkelo** [comment]
use Prometheus regex operator in the label condition

**Comment by torkelo** [comment]
oh, so this is not a label but metrics? Not sure Prometheus supports regex in the metric name, maybe it does, if not open an issue with the Prometheus project :)

**Comment by mtanda** [comment]
I don't read issue well, but metric name is record as "__name__" label, can use regex operator.

**Comment by mtanda** [comment]
https://prometheus.io/docs/querying/basics/
> ```Label matchers can also be applied to metric names by matching against the internal __name__ label. For example, the expression http_requests_total is equivalent to {__name__="http_requests_total"}. Matchers other than = (!=, =~, !~) may also be used. The following expression selects all metrics that have a name starting with job::```

**Comment by knweiss** [comment]
I think you misunderstood the issue. Matching the metric name (`metrics()` works fine as described) but specifying multiple graphs in a single Graph query e.g. by iterating over the metric names in the multi-value template variable.

The goal is to create a Graph panel in which the user can choose which **metrics** he wants to see by selecting the multi-value template variable
(which contains the matched metric names).

**Comment by mtanda** [comment]
This is a example query.
http://demo.robustperception.io:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22%7B__name__%3D~%5C%22node_memory_Active%7Cnode_memory_Active_anon%5C%22%2Cinstance%3D%5C%22demo.robustperception.io%3A9100%5C%22%7D%22%2C%22tab%22%3A1%7D%5D

Maybe you need to set like following.
```
{__name__=~"$m",instance="test1:9100"}
```

**Comment by knweiss** [comment]
Yup, I'm sorry, just as you posted your example I got it working, too, after re-reading you comment. Thanks a lot!

**Comment by Thilaknath** [comment]
Hi Team, I have metrics coming in the following format in prometheus

magellan_a37463746adfdf_passed 9
magellan_a37463746adfdf_failed 4

The random value is the build number and it keeps varying, How do i query this from grafana? I am looking for a ideal query which could query passed||failed for a build.
