### ISSUE TITLE
Add controls to `IconButton` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54166]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

The current existing `Simple` story should be renamed to `Examples` and a new story should be created that shows only a single instance of the `IconButton` and has controls attached to it.

**Comment by orlandoortegajr** [comment]
Hi @JoaoSilvaGrafana , can you assign this one to me I have started working on this issue.

**Comment by JoaoSilvaGrafana** [comment]
Hi @orlandoortegajr thanks for helping with a lot of these tasks, assigned this one to you as well! Will try to get it reviewed today 😄
