### ISSUE TITLE
Optionally add captions for metrics

### ISSUE THREAD

**Issue by bigunyak** [grafana/grafana#5416]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

Grafana-3.0.4
- What datasource are you using?

Graphite
- What OS are you running grafana on?

Debian

I know that I can use graphite `alias` function to set arbitrary metric name, but what I want is to be able to specify a short description for some metrics which can be shown in a small popup when hovering over the metric's name in the legend for example.
That would be especially useful in some cases when you have hundreds of metrics with not very descriptive names. Take a look at Couchbase stat metrics for example:
http://developer.couchbase.com/documentation/server/4.5/cli/cbstats-intro.html
Would be cool to be able to specify those short descriptions somewhere in the graph.

**Comment by torkelo** [comment]
good idea, will close as similar issue already exists, https://github.com/grafana/grafana/issues/4079
