### ISSUE TITLE
Add controls to `QueryField` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54168]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by timagixe** [comment]
Hi @JoaoSilvaGrafana, could you please assign this to me? I am willing to help with it.

**Comment by JoaoSilvaGrafana** [comment]
Thanks for already submitting a PR @timagixe ! I will try to have a look at this today 🎉
