### ISSUE TITLE
Add controls to `Button` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54161]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

The current existing `Variants` story should be renamed to `Examples` and a new story should be created that shows only a single instance of the `Button` and has controls attached to it.

**Comment by Pomierski** [comment]
Hi @JoaoSilvaGrafana 👋 I would like to help. Could you please assign this issue to me? :)

**Comment by JoaoSilvaGrafana** [comment]
Hey @Pomierski sure, assigned it to you! Thanks for helping 😄 I will try to review the PR today!
