### ISSUE TITLE
Stat display needs tweak to allow spacing between name and value

### ISSUE THREAD

**Issue by westonforbes** [grafana/grafana#54160]
The stat display panel does not put a space between the name and value when oriented in horizontally.
This does not look good and with the care y'all have put into your interface, I'd suppose its a tweak you'd want to address. See below image. I tried to add a trailing space to the name of the stat but the UI doesn't display trailing spaces.

![image](https://user-images.githubusercontent.com/56303146/186460904-cce4d6a4-1f44-487a-8d71-8eb0a4ec52a5.png)

**Comment by MatheusBeniniF** [comment]
hey @westonforbes, what do i need to do to get to that part?

**Comment by gelicia** [comment]
@MatheusBeniniF sorry for the delay - are you asking how to add a stat panel in Grafana? You would create a new dashboard, add a panel, and select "Stat" in the top right

<img width="342" alt="Screen Shot 2022-08-31 at 11 47 09 AM" src="https://user-images.githubusercontent.com/1533128/187734534-5852b177-759b-4eff-8197-3bd9f6082318.png">

**Comment by MatheusBeniniF** [comment]
No, I ask how to add the panel like this
![image](https://user-images.githubusercontent.com/88898100/187752138-f7771f1c-1b90-41c6-84b1-07940f3cc005.png)
