### ISSUE TITLE
Add controls to `Checkbox` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54170]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by gefgu** [comment]
Hello @JoaoSilvaGrafana! I would be happy to work on this issue and be assigned to this task :)

**Comment by JoaoSilvaGrafana** [comment]
Hey @gefgu sure, assigned it to you! Thanks for helping 😄  I will try to review the PR today 🙏
