### ISSUE TITLE
Add controls to `InlineField` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54171]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by gefgu** [comment]
@JoaoSilvaGrafana I decided to work on this issue too. Can you assign it to me?

**Comment by JoaoSilvaGrafana** [comment]
Done it, thanks for picking another issue @gefgu 🎉
