### ISSUE TITLE
Add controls to `InlineLabel` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54173]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by timagixe** [comment]
Hello @JoaoSilvaGrafana, can I help with this task? Could you please assign it to me? Thanks.

**Comment by timagixe** [comment]
Hello @JoaoSilvaGrafana, I have opened PR, please take a look on it whenever you have a chance. Thanks!
