### ISSUE TITLE
Using regex on Template variables does not make any match on Grafana 3.0

### ISSUE THREAD

**Issue by 3fr61n** [grafana/grafana#5418]
Hi 

I would like to understand if there is a behaviour change on Grafana 3.0.4 (compared to v2.6) related to regex usage on template variables.

For instance in play.grafana.org in this dashboard, I'm not able to select more that one datacenter using regex (like A.*) (please click below)

http://play.grafana.org/dashboard/db/influxdb-templated-queries?var-datacenter=A.*&var-host=All&var-summarize=1m

![screen shot 2016-06-23 at 13 15 23](https://cloud.githubusercontent.com/assets/6707509/16301234/967dd880-3944-11e6-92df-513b01be4622.png)

In previous Grafana (2.6) a had dashboards using template variables with influxdb and they work smoothly,  I'm missing something? perhaps there is a hidden option somewhere.

Thanks in advance
Efrain

**Comment by torkelo** [comment]
the variable value is regex escaped to support multiple values. Not possible to know for Grafana if what you specify is a value that should be regex escaped or it is a regex

**Comment by 3fr61n** [comment]
Hi @torkelo 

I'm sorry to taking back this topic,  it could be possible to have an option to select multiples values from a template, (in a similar way 'Clear Selection' works)?


![screen shot 2016-09-05 at 17 00 23](https://cloud.githubusercontent.com/assets/6707509/18251614/49b20fbe-738a-11e6-85c4-4b519d9098e4.png)


Thanks in advance.
Efrain
