### ISSUE TITLE
Public Dashboards: Zooming in doesn't work for all panels

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#54189]
**What happened**:

See https://github.com/grafana/grafana/discussions/49253?sort=old#discussioncomment-3467176 for more details on this one, but basically when you zoom in on a public dashboard the time series panels update but the gauges do not.

**What you expected to happen**:

Gauges would requery

**How to reproduce it (as minimally and precisely as possible)**:

+ Create a dashboard with timeseries and gauge panels.
+ make it a public dashboard
+ observe when you zoom in on the timeseries (click + drag) only the time series panels update.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.x

**Comment by jalevin** [comment]
We should disable zooming until Time Ranges are solved
