### ISSUE TITLE
State Timeline: Setting Tooltip to Hidden Doesn't Hide Tooltip

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#54190]
**What happened**:

Reported in #54129, when setting tooltip configuration option to hidden on the state timeline the tooltip still shows.

**What you expected to happen**:

Tooltip shouldn't show in this situation.

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: N/A
- OS Grafana is installed on: MacOS
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others:

**Comment by mdvictor** [comment]
fixed by https://github.com/grafana/grafana/pull/54697
