### ISSUE TITLE
[Feature request] Templating Custom: Add condition if to show specific list

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5421]
Hi,
In templating with type=Custom. It's will be very nice if we use condition (if else) to show a specific list.

My use case:
I have 3 lists (Cluster, Cluster1_Hosts and Cluster2_Hosts) defined
![captureazq](https://cloud.githubusercontent.com/assets/15362041/16305323/987f3092-3959-11e6-8f9c-584541962701.PNG)
I hide `Cluster1_Hosts` and `Cluster2_Hosts` lists
![aaazzzzza](https://cloud.githubusercontent.com/assets/15362041/16305435/19145a5c-395a-11e6-8ab3-62f2ba9bf1a3.PNG)

**The Feature Request:**
In Cluster list, If i select "Cluster1" i would like to show "`Cluster1_Hosts`"
In Cluster list, If i select "Cluster2" i would like to show "`Cluster2_Hosts`"
![aaaazsq](https://cloud.githubusercontent.com/assets/15362041/16306268/626bb634-395d-11e6-91de-dc37dde8d093.PNG)

An idea to do this:
![aaaaqaaz](https://cloud.githubusercontent.com/assets/15362041/16306029/9d00fea4-395c-11e6-8e01-183c61ae5ec6.PNG)

**Comment by torkelo** [comment]
You should store that info you time time series store and use queries to fill the list of values in your template variable
