### ISSUE TITLE
Add controls to `DatePickerWithInput` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54222]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by orlandoortegajr** [comment]
@JoaoSilvaGrafana Hi, I was searching for issues with the label good first issue and stumbled upon this project which looks pretty interesting! I am a full stack dev mostly focusing on the frontend side of things using React with Typescript and I found this issue pretty interesting. I have successfully setup my dev environment, was able to build storybook and already found the file that deals with this issue. As I started reading the docs I figured that I am already pretty deep into this and was wondering if I could get this assigned. This is my first time working with storybook directly so should be a pretty good learning experience, would greatly appreciate it!

**Comment by JoaoSilvaGrafana** [comment]
Hey @orlandoortegajr ! 👋 Yep I can assign this issue to you, thank you so much for helping 😄
