### ISSUE TITLE
"default" retention policy on InfluxDB taken as DEFAULT which might be different

### ISSUE THREAD

**Issue by DavidDurman** [grafana/grafana#5422]
Bug report.
Using Grafana v3.0.4 on Ubuntu 14.04.4 LTS with InfluxDB as a data source.

Steps:
1. Create a panel with a new metric.
2. From clause has two dropdowns, one for the InfluxDB retention policy and one for the measurement.
3. When "default" retention policy is selected, Grafana constructs a query that completely skips this "default" policy from the fully qualified measurement.

![screen shot 2016-06-23 at 5 48 59 pm](https://cloud.githubusercontent.com/assets/125717/16310152/bb1c15a4-396b-11e6-8893-96070da88370.png)

Example query when "default" policy is selected in the From clause (taken from the browser dev tools network tab):

```
/api/datasources/proxy/1/query?db=thermologs&q=SELECT%20mean(%22value%22)%20%20%2F%2010%20FROM%20%22downsampled_measured_temperature%22%20WHERE%20%22unit%22%20%3D%20%27it04348%27%20AND%20time%20%3E%20now()%20-%2024h%20GROUP%20BY%20time(1m)%20fill(null)%3BSELECT%20mean(%22value%22)%20%20%2F%2010%20FROM%20%22downsampled_set_temperature%22%20WHERE%20%22unit%22%20%3D~%20%2F%5Eit04348%24%2F%20AND%20time%20%3E%20now()%20-%2024h%20GROUP%20BY%20time(1m)%20fill(null)%3BSELECT%20mean(%22value%22)%20%20%2F%2010%20FROM%20%22downsampled_outside_temperature%22%20WHERE%20%22unit%22%20%3D~%20%2F%5Eit04348%24%2F%20AND%20time%20%3E%20now()%20-%2024h%20GROUP%20BY%20time(1m)%20fill(null)&epoch=ms
```

which when prettified looks like:

```
/api/datasources/proxy/1/query?db=thermologs&q=SELECT mean("value")  %2F 10 FROM "downsampled_measured_temperature" WHERE "unit" %3D 'it04348' AND time > now() - 24h GROUP BY time(1m) fill(null)%3BSELECT mean("value")  %2F 10 FROM "downsampled_set_temperature" WHERE "unit" %3D~ %2F^it04348%24%2F AND time > now() - 24h GROUP BY time(1m) fill(null)%3BSELECT mean("value")  %2F 10 FROM "downsampled_outside_temperature" WHERE "unit" %3D~ %2F^it04348%24%2F AND time > now() - 24h GROUP BY time(1m) fill(null)&epoch=ms
```

As can be seen, the "default" is skipped from the query.

Expected result:

The SELECT query should contain the "default" retention policy, i.e. from the example above: 
```
SELECT mean("value")  %2F 10 FROM "default"."downsampled_measured_temperature" WHERE ...
```

This is because "default" might not be the actual default retention policy (from influx cli):

```
> show retention policies on thermologs
name		duration	shardGroupDuration	replicaN	default
default		0		168h0m0s		1		false
two_weeks	336h0m0s	24h0m0s			1		true
```

**Comment by torkelo** [comment]
if you have a policy named default that is not default, then use the raw query editor mode. The query editor will not include the policy name if you pick default, so InfluxDB will use the default one.
