### ISSUE TITLE
Curly brackets invert string syntax highlighting

### ISSUE THREAD

**Issue by Condla** [grafana/grafana#54237]
Loki query in Explore mode: when filtering a regex with curly brackets, the query syntax highlighter inverts the colours of what’s inside the quotes (green) and outside (white). 

**Steps to reproduce**:
Loki query example to reproduce the issue for filtering a label `pod` that has the label value `grafana-agent-0`:
`{pod=~"grafana-agent-\\d{1}"} |= "test"`

**Actual Result**:
* The syntax of `"grafana-agent-\\d{1}` and `test"` is black
* The syntax of `"} |= "` is green

Syntax Highlighting of strings is inverted by the curly brackets starting at last use of `}`

**Expected Result**:
* The syntax of `"grafana-agent-\\d{1}` and `test"` is green
* The syntax of `"} |= "` is black

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: v9.0.7-76194 (438c95892)
- Data source type & version: Loki
- User OS & Browser: MacOS + Chrome
- Others:

**Comment by gabor** [comment]
i wonder how hard is to add this, whether it is an easy fix in https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/syntax.ts , or something harder... @ivanahuckova do you have any idea if this is easy or hard?

(if it's hard i'd recommend we solve this after https://github.com/grafana/grafana/issues/44985 )

**Comment by ivanahuckova** [comment]
@gabor No idea. Considering that this is only incorrect highlight (query works as expected), and we know we want to migrate to monaco soon, I wouldn't spend time on this. Or we can make it `help wanted` issue and if this is very important for someone, they can pick it up.

**Comment by ivanahuckova** [comment]
Considering that we are working on monaco editor, can this be closed? Even if someone implemented the fix, new editor will be probably part of the next minor release?

**Comment by Condla** [comment]
Yes definitely, this is not urgent and will hopefully be fixed with the next release
