### ISSUE TITLE
Elasticsearch: Incorrectly creates new HTTP client on each query

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#54233]
**What happened**:
Noticed in the code that the elasticsearch backend implementation creates a new HTTP client on each query. This is not good since HTTP connections can't be reused and could in theory use up all available TCP sockets on a server/node.  

**What you expected to happen**:
That it creates a new HTTP client for a non-instantiated datasource instance and reuses that throughout the life-cycle of that instance. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Creating a new client on each query and providing `HTTPClientProvider`:
https://github.com/grafana/grafana/blob/ca3296da342881946966acd6df0deffd2a896c70/pkg/tsdb/elasticsearch/elasticsearch.go#L54
Creates a new HTTP client on each client search execution:
https://github.com/grafana/grafana/blob/ca3296da342881946966acd6df0deffd2a896c70/pkg/tsdb/elasticsearch/client/client.go#L176

My recommendation to instantiate HTTP client in `newInstanceSettings` and put in `DatasourceInfo` and pass around `httpClient` instead of `HTTPClientProvider`:
https://github.com/grafana/grafana/blob/ca3296da342881946966acd6df0deffd2a896c70/pkg/tsdb/elasticsearch/elasticsearch.go#L128

**Environment**:
- Grafana version: main

**Comment by gabor** [comment]
(NOTE: for an example of how to do it, the Loki datasource has it done the right way: https://github.com/grafana/grafana/blob/main/pkg/tsdb/loki/loki.go#L83)
