### ISSUE TITLE
Template variable service failed Cannot destructure property 'includeAll' of 's' as it is undefined.

### ISSUE THREAD

**Issue by mariaiff** [grafana/grafana#54236]
I created a dashboard with Geomap that has an override with a link to another dashboard with Flowchart.
In the link, two variables are sent. But sometimes when accessing the second dashboard the error appears "Template variable service failed Cannot destructure property 'includeAll' of 's' as it is undefined."

When inspecting the browser, the following error appears:
Uncaught TypeError: Cannot destructure property 'includeAll' of 's' as it is undefined.
    at updateVariableOptions(reducer.ts:145:15)
    at redux-toolkit.esm.js:616:32
    at produce (immer.esm.js:1:16051)
    at redux-toolkit.esm.js:615:28
    at Array.reduce (<anonymous>)
    at d (redux-toolkit.esm.js:594:29)
    at Object.reducer (redux-toolkit.esm.js:669:20)
    at l (variablesReducer.ts:31:54)
    at redux.js:560:29
    at templating(keyedVariablesReducer.ts:47:26)

The link to the second dashboard is: /d/0ZK28mk4k/synway-detailed?orgId=1&refresh=5s&var-cities=${__data.fields.Locality}﻿&var-host=${__data.fields.Host}

**Environment**:
- Grafana Version: 9.0.2
- Data source type and version: Postgres
- OS Grafana is installed on: Centos 7
- User OS and browser: Windows/Chrome/Firefox/Edge
- Grafana plugins: Geomap and Flowchart
![Grafana](https://user-images.githubusercontent.com/61873375/186694808-e079d34a-c726-49e9-98b7-1eb3444d92b4.png)

**Comment by gelicia** [comment]
@mariaiff - if you are receiving the error in flowchart, I would like to confirm with that team that they are handling these kinds of template variables correctly. We do not maintain that plugin - I believe the repo for that plugin is https://github.com/algenty/grafana-flowcharting. I looked to try to see if anyone else had found your issue and didn't see anything. Can you check to see if your data flow is supported with them? You can always re-open this ticket if it seems like something we could investigate and fix within Grafana's codebase. Thank you!
