### ISSUE TITLE
metrics: Some grafana_database_conn_* metrics are incorrect

### ISSUE THREAD

**Issue by hairyhenderson** [grafana/grafana#54242]
**What happened**:

The `grafana_database_conn_max_idle_closed_total` metric, for example, is intended to expose the value of [`DBStats.MaxIdleClosed`](https://pkg.go.dev/database/sql#DBStats). `DBStats.MaxIdleClosed` is a counter that only increments, from the lifetime of the `*sql.DB`.

However, when collecting metrics, Grafana adds that value to the metric (itself also a counter):
 
https://github.com/grafana/grafana/blob/82b63688d236a4c5788043822e8a22d003bb8a8c/pkg/services/sqlstore/sqlstore.go#L546

The effect is that the metric is exponentially increasing, rather than exposing the correct value from `DBStats`.

This bug appears to exist for all of the counter metrics that are exposed:

- `grafana_database_conn_max_idle_closed_seconds`
- `grafana_database_conn_max_idle_closed_total`
- `grafana_database_conn_max_lifetime_closed_total`
- `grafana_database_conn_wait_count_total`
- `grafana_database_conn_wait_duration_seconds`

**What you expected to happen**:

I expect the `grafana_database_conn_*` metrics to correctly expose the `DBStats` values.

**How to reproduce it (as minimally and precisely as possible)**:

n/a

**Anything else we need to know?**:

The name `grafana_database_conn_max_idle_closed_seconds` is also not ideal - suffixes like `_seconds` imply that the value's unit is time, but in this case it's not - it's exposing `DBStats. MaxIdleTimeClosed`, which is the number of connections closed due to `MaxIdleTime` being reached.

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by hairyhenderson** [comment]
One option to solve this would be to use https://github.com/dlmiddlecote/sqlstats, but I'm not sure we can use it as-is because it wraps the `*sql.DB`, whereas Grafana's `*SQLStore` wraps an `*xorm.Engine` instead.

We could definitely use the approach as `sqlstats` though. I can look into this.

**Comment by hairyhenderson** [comment]
(I can get started working on a PR for this!)

**Comment by bergquist** [comment]
My fault! :grin:

**Comment by hairyhenderson** [comment]
> One option to solve this would be to use https://github.com/dlmiddlecote/sqlstats, but I'm not sure[...]

Looks like we can, and pretty easily too! However, it would break metrics compatibility (a few names would change, labels would be added).

I think what I'd like to do is go through a deprecation cycle for the current metrics, and add the `sqlstats` wrapper as a feature-flagged option.
