### ISSUE TITLE
Bar width is huge/unstable when using OpenTSDB downsampling

### ISSUE THREAD

**Issue by boboli** [grafana/grafana#5425]
I'm using OpenTSDB as the datasource, and trying to graph a statsd counter using bar graph style. I set the downsampling interval to 60s to try to control the bar widths, and to prevent them from being too skinny.

Unfortunately, the bar widths don't behave properly. The strange part is that the widths are inconsistent as I change the time range. In my current graph, 6 hours is good and correct, while any other time range shows huge bars.

I've found a couple of similar issues listed for other datasources (influxdb, graphite, ES) but haven't found anything yet for OpenTSDB.

Please include this information:
- What Grafana version are you using?
2.6.0
- What datasource are you using?
OpenTSDB
- What OS are you running grafana on?
Ubuntu Linux 14.04
- What did you do?
Setup a graph using bar rendering, and trying to configure the bar width by setting downsampling interval.
- What was the expected result?
A graph with bar widths that are consistently 60s wide.
<img width="1424" alt="screen shot 2016-06-23 at 12 01 51 pm" src="https://cloud.githubusercontent.com/assets/4108038/16316251/8369f95e-393a-11e6-8aa9-26d0e3bdbbe1.png">
The above is a correct expected graph, note the time range that's set to last 6 hours.
- What happened instead?
A graph with unpredictable (but mostly huge) bar widths.
<img width="1432" alt="screen shot 2016-06-23 at 12 02 00 pm" src="https://cloud.githubusercontent.com/assets/4108038/16316267/a4e7b634-393a-11e6-8f72-6d629c3fcea2.png">
The exact same graph, but set to a time range of 12 hours.
<img width="1425" alt="screen shot 2016-06-23 at 12 02 11 pm" src="https://cloud.githubusercontent.com/assets/4108038/16316282/b7c2f8ea-393a-11e6-8d61-ae508bc51ada.png">
Also huge on 1 hour.

The POST request/response for the 6 hours graph:
[6hours.txt](https://github.com/grafana/grafana/files/330645/6hours.txt)

The POST request/response for the 12 hours graph:
[12hours.txt](https://github.com/grafana/grafana/files/330646/12hours.txt)

**Comment by torkelo** [comment]
looks like a bug in OpenTSDB downsampling, looks like there is missing data, the bar width is determined by looking at the distance between the first two data points. 

if you group by 60s or downsample to 60s OpenTSDB should return data points for each 60s interval

**Comment by torkelo** [comment]
Oh, and you should be able to solve this using OpenTSDB fill policy 
http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html#fill-policies

OpenTSDB v2.2 feature

**Comment by boboli** [comment]
Ok. Thanks for the lightning-fast response!

**Comment by boboli** [comment]
I upgraded to the latest Grafana (v3.0.4), and indeed the fill policy was what I was looking for, after I switched the datasource to allow OpenTSDB v2.2. Many thanks!
