### ISSUE TITLE
[Feature request] ElasticSearch - aggregation by Terms

### ISSUE THREAD

**Issue by Turum** [grafana/grafana#5428]
Hi,
It would be nice to have aggregation "by terms", like it's done in kibana. Now works only grouping "by date histogram".
Or may be you could give me a clue how to eliminate gap in date histogram when there is no data for this date.

![image](https://cloud.githubusercontent.com/assets/19665888/16332536/231cf6e4-39ff-11e6-9610-a1ab17a63311.png)
Graph from kibana with terms aggregations.
![image](https://cloud.githubusercontent.com/assets/19665888/16332666/daa9de3a-39ff-11e6-80e3-128ebeea622c.png)

**Comment by torkelo** [comment]
you can click the plus icon on the group by line to add another group by, then select Terms aggregation or filter aggregation. 

<img width="1152" alt="screen shot 2016-06-24 at 11 19 49" src="https://cloud.githubusercontent.com/assets/10999/16333802/9bc7dd22-39fd-11e6-9ec4-449d78ab612d.png">

**Comment by Turum** [comment]
Yes, but this is not eliminate gaps with no data in date histogram (5/1 for example). And graph is not built without date histogram.
![image](https://cloud.githubusercontent.com/assets/19665888/16335186/ee62abec-3a0d-11e6-9bea-c98a1ac485fe.png)
![image](https://cloud.githubusercontent.com/assets/19665888/16335251/4c9848f2-3a0e-11e6-9a10-26fc9e407c08.png)

**Comment by torkelo** [comment]
You need date histogram and terms aggregation,  you can have both of you click the plus icon on the right of the date histogram row. 

Not sure what you mean,  "not eliminate gaps".  Thought you wanted to group by terms. 

If you want to remove gaps you can change the group by time interval, or in display options change null point mode, or in date histogram change min doc count and no docs value

**Comment by Turum** [comment]
I have one row of data for each working day, except weekends. I just want to make a graph without gaps by the weekends (because it's days without any data). When I choose group by "terms" i get "No data points returned from metric query" in dev tools. Then I add "then by data histogram" option, i get graph with gaps by the weekends. How can I solve this? Sorry for my molestation.
Thanks.
