### ISSUE TITLE
Cannot render panels to png behind reverse proxy

### ISSUE THREAD

**Issue by StianOvrevage** [grafana/grafana#5430]
I'm trying to render a png panel. Grafana is located behind nginx and is proxied to hostname/grafana/. root_url is also set:

    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

However, it looks like grafana adds the "/grafana/" subdirectory when calling the local (non-proxied) URLs for rendering:

    2016/06/24 09:55:18 [I] PhantomRenderer::renderToPng url http://localhost:3000/grafana/dashboard-solo/file/linux-monitoring-pack.json?panelId=1&from=1466287200000&to=1466761652781&var-Hostname=server&width=1000&height=500

Which of course fails. Have not found any settings of changing the grafana endpoint URL as a workaround.

I'm using grafana - v3.0.3-1463994644 - 2016-05-23 docker image
Prometheus datasource
Ubuntu 16.04

* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/configuration/#root_url

> This is the full URL used to access Grafana from a web browser

**Comment by StianOvrevage** [comment]
I'm aware. But where do PhantomRenderer get that extra /grafana/ from when trying to render pngs?

**Comment by torkelo** [comment]
Your root url option

**Comment by StianOvrevage** [comment]
So how do I get Grafana to serve on /grafana/? root_url only has effect on the links it seems. It still uses localhost:3000 as it's own root apparently.

**Comment by StianOvrevage** [comment]
wget -O - http://localhost:3000/grafana/
2016-06-24 11:08:48 ERROR 404: Not Found.

**Comment by torkelo** [comment]
Yes, your root url option is wrong, that is way I linked to that

**Comment by StianOvrevage** [comment]
But grafana is hosted behind nginx and lives on my.public.com/grafana/ . Will that work with

    root_url = %(protocol)s://%(domain)s:%(http_port)s/

?

**Comment by torkelo** [comment]
Yes,

**Comment by StianOvrevage** [comment]
So, for anyone else who wonders. Just forget the variables in root_url and set the URL completely static:

    root_url = https://username:password@your.site.com/grafana/

**Comment by hugofoliveira** [comment]
I have the same problem, but my reverse proxy is on port 8080 and even with a static URL in the root_url, I receive a 404.
