### ISSUE TITLE
Datasources: Integration tests for HTTP datasources

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#54314]
In #54146 we introduced integration tests for the Prometheus datasource so that we have verification that the usage of HTTPClientProvider is correct and properly sets expected headers on outgoing HTTP requests. Headers not properly being set/forwarded is something that' been bugging us in multiple issue over the last releases why it would be good to introduce integration tests for all builtin HTTP datasources to make sure we don't break these thing while making changes.

The [integration tests](https://github.com/grafana/grafana/blob/main/pkg/tests/api/prometheus/prometheus_test.go) for Prometheus can be used as a template/helper implementing it for other datasources.

Datasources:
- [x] Azure Monitor https://github.com/grafana/grafana/issues/54379
- [ ] Cloud Monitoring https://github.com/grafana/grafana/issues/54391
- [x] Elasticsearch https://github.com/grafana/grafana/issues/54329
- [x] Graphite https://github.com/grafana/grafana/pull/54733
- [x] Influxdb https://github.com/grafana/grafana/pull/54700
- [x] Loki https://github.com/grafana/grafana/issues/54327
- [x] Opentsdb https://github.com/grafana/grafana/pull/54733
- [x] Prometheus https://github.com/grafana/grafana/pull/54146
- [ ] Tempo

**Comment by auwaerter** [comment]
@marefr do you think the removal of several headers could be related to https://github.com/grafana/grafana/issues/50841?

**Comment by aangelisc** [comment]
I'm going to close #54391 for now as it can't be implemented as the URL for Google is fixed and cannot be modified by the user.

**Comment by vickyyyyyyy** [comment]
Closing as the GCM issue is blocked
