### ISSUE TITLE
Unable to push embed graphs to Notion through Iframes.

### ISSUE THREAD

**Issue by SovnSkyrim** [grafana/grafana#54326]
**What happened**:
Grafana failing to load it's stuff within Notion
[Screenshot](https://i.imgur.com/P6Pa1OY.jpg)
**What you expected to happen**:
A graph to appear
**How to reproduce it (as minimally and precisely as possible)**:
Open your Grafana on for embeds; set your environment variables as below; create a graph with a datasource; try to share it via embed. Go to your Notion page; do "/embed" paste the link provided by Grafana; you'll see the image above.
**Anything else we need to know?**:

**Environment**:

- Grafana version: latest dockerfile
- Data source type & version: raw logs being querried
- OS Grafana is installed on: Official Grafana image 
- User OS & Browser: Ubuntu Dockerfile
- Grafana plugins: None that should interact with this.
- Others:
Environment variables:
`      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_CERT_FILE=/usr/share/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/usr/share/grafana/grafana.key
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true`

[Docker-compose.yml file](https://pastebin.com/4RAuYskD)
Note: I have a Web API running on the same server listening to port 3000 so that's why I use port 3333 for Grafana.
You can see I SSL signed the Web UI for Grafana; it's a free 90 Days trial through ZeroSSL

**Comment by axelavargas** [comment]
Hey @SovnSkyrim 👋🏾 , thank you for reporting this issue, I am able to reproduce it, I will add it to our backlog and we will prioritize in the future :)
