### ISSUE TITLE
Need help with using histogram plugin..

### ISSUE THREAD

**Issue by nagaprabhanjan** [grafana/grafana#5432]
Hi,

I am using grafana v3.0.4 and histogram plugin. I am trying to show memory usage of processes in the graph, and surprisingly, for histogram plugin I get the memory size on the x-axis instead of on the y-axis, because of this the graph is expanding and shrinking horizontally. I tried changing various parameters, but in vain. Can anyone please help me show what I am doing wrong here? Attached is a screenshot - each histogram is a process and the processes are spread across based on their memory consumption.

![grafana query](https://cloud.githubusercontent.com/assets/20130054/16343186/5b2a1af4-3a53-11e6-98fd-d84bd4a4762a.png)

**Comment by torkelo** [comment]
Please seek help with the plugin author
