### ISSUE TITLE
Feature Tracking: Create a dashboard for query history feature tracking

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#54323]
The dashboard should display graphs showing user events added in https://github.com/grafana/grafana/issues/49668

Also track query history migration failures:

`{ app="grafana"} | logfmt | logger="frontend" |= "QueryHistoryMigrationFailed"`

**Comment by ifrost** [comment]
We have a dashboard for query history: "Grafana feature tracking / Query history"
