### ISSUE TITLE
Templating All selection generates bad syntax

### ISSUE THREAD

**Issue by NoMotion** [grafana/grafana#5433]
Bug Report

- What Grafana version are you using? 3.0.4
- What datasource are you using? Graphite 9.15
- What OS are you running grafana on? RHEL

When generating a template such as the following:
`carbon.agents.*`
This will generate hostnames for all carbon relays I have and of course populate a metric
`alias(sumSeries(group(carbon.agents.$cache.updateOperations)),"Total Updates")`

However issue arrises only when i select **All** from the template dropdown. Individual selections work fine as well as multiple

Looking into the Chrome webtools i notice a difference in the request:
**Using All**
`alias(sumSeries(group(carbon.agents.{{server1,server2,server3}}.updateOperations)),"Total Updates")`
**Using single selected host**
`alias(sumSeries(group(carbon.agents.{server1}.updateOperations)),"Total Updates")`

It looks like there is a bug where Grafana is adding additional **{** curly braces when  **All** is selected.
Apologies if this issue is already posted. I spent a long time combing the issues for this with no avail

**Comment by torkelo** [comment]
Strange, I am unable to replicate this, any no one else has reported anything similar. 
http://play.grafana.org/dashboard/db/templated-graphs-nested?panelId=1&fullscreen&var-app=fakesite&var-server=All&var-interval=$__auto_interval

Could be that your All value is using old syntax with pre formatted value (was a change in how this format worked between 2.6 and 3.0). So to fix your issue go into the $cache template variable options and hit the Update button. Save & reload dashboard

**Comment by NoMotion** [comment]
@torkelo Recreating these template variables fixed the issue. Maybe it was an old syntax from different version, we did just upgrade when this started happening. I will reopen this issue if i find more evidence in the future or a way to easily recreate it.
