### ISSUE TITLE
Prometheus version 2.12.0 reports as "Cortex" datasource type when testing datasource config

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#54344]
**What happened**:
Testing prometheus `2.12.0` and I saw that it reported as "Cortex" instead of Prometheus like other versions (tested with 1.8 and
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
* Spin up 2.12.0 prometheus instance, 
* connect datasource to Grafana
* click test & save
* Open details accordion in success dialog
**Anything else we need to know?**:
Nothing else appears broken!

**Environment**:
- Grafana version: 9.10
- Data source type & version: Prometheus 2.12.0
- OS Grafana is installed on: OS X (local devenv)
- User OS & Browser: OS X, chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by gtk-grafana** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/109082771/186969140-3e6918fa-4274-4f7a-9e76-353121f6e15c.png">
It didn't upload my image! Well here it is

**Comment by gtk-grafana** [comment]
Looks like 2.12.0 returns a 404 instead of 405 like other versions (1.8, 2.3), so this code:
```
if ('status' in e && e.status === 404) {
      return undefined; // Cortex does not support buildinfo endpoint, we return an empty response
}
```
in /grafana/grafana/public/app/features/alerting/unified/api/buildInfo.ts

triggers the code to determine that this prometheus instance is a Cortex datasource.

**Comment by konrad147** [comment]
General question, how old Prometheus versions we are supposed to support? Prometheus 2.14 is almost 3 years old

**Comment by gtk-grafana** [comment]
This issue will be address by the new configuration fields added in https://github.com/grafana/grafana/pull/56496
