### ISSUE TITLE
Heatmap color scheme range from high to low breaks color rendering

### ISSUE THREAD

**Issue by gegtor** [grafana/grafana#54364]
**What happened**:

After the update to Grafana 9.1.1 from 8.5.10 heatmap colors with color ranges from high to low display wrong colors

Here you can see TPS display where values aren't properly visualised (data point with value 50 is selected but it displays as red)
Color range goes from 50 (blue) to 0 (red)
Colors for values like 25 also don't render properly and only show blue or red
<img width="1680" alt="Screenshot 2022-08-28 at 05 47 15" src="https://user-images.githubusercontent.com/10978723/187056561-dea0c81e-c564-4a94-a202-d7f36cb86667.png">

Here with a PING display from 0 to 100 everything is displayed properly
<img width="1680" alt="Screenshot 2022-08-28 at 05 46 54" src="https://user-images.githubusercontent.com/10978723/187056566-d88a5eb2-38e4-405a-be0c-48920d958f4f.png">

Those two heatmaps have the exact settings and the bug could be reproduced with the same data on either of them by only changing color scheme range

**What you expected to happen**:

I expect heatmap colors to be correctly displayed based on value

**How to reproduce it (as minimally and precisely as possible)**:

Create a heatmap and set the color scheme from high to low (50 to 0 for example)

**Anything else we need to know?**:

No setting were changed this started to happen after update from 8.x.x to 9.1.1

Values outside the range (50 means blue) for example 55 display as red but they should be blue

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: InfluxDB 2.0 Flux query
- OS Grafana is installed on: VPS Ubuntu Server 20.04
- User OS & Browser: Tested on Safari, Firefox, Chrome
- Grafana plugins: none
- Others: -

**Comment by gegtor** [comment]
Log shows no errors only requests

```
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-28T04:04:01.988019192Z level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=x time_ms=4 duration=4.206284ms size=12 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-08-28T04:04:15.542932855Z level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=x time_ms=3 duration=3.896964ms size=12 referer= traceID=00000000000000000000000000000000
```

**Comment by leeoniya** [comment]
hmm, i wonder if a better fix for this would be to add an explicit toggle to reverse the chosen color scale instead of sprinkling a bunch of code everywhere to handle inverted min/max settings. :thinking:
