### ISSUE TITLE
Library panel cannot be modified from panel's settings

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#54367]
**What happened**:
It is impossible to modify the library panel from panel's settings view.
When I create the panel, create library panel (expand visualizations, switch to library panels and click ```Create new library panel```) the library panel is being created, but when I go back to the dashboard, the same panel becomes standard panel again.
Only creating library panels by clicking panel's title and choosing ```More``` > ```Create library panel``` works correctly.

In order to edit library panel on dashboard, I need to unlink the panel, make changes, remove old library panel and create the library panel again.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create panel & create a library panel from it
2. Make any changes to the panel and click save library panel
3. After saving, go back to the dashboard. All the changes will be gone

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: InfluxDB 2 (Flux)
- OS Grafana is installed on: Debian
- User OS & Browser: Opera GX

**Comment by mellieA** [comment]
@szerwi it looks like there's a discussion and potential fix for this one. Closing in favor of https://github.com/grafana/grafana/pull/52855
