### ISSUE TITLE
Missing $__timeEpoch function when provisioning alert rule

### ISSUE THREAD

**Issue by soukeiz529** [grafana/grafana#54369]
**What happened**:
Using provisioning feature to provision an alert rule which contains a rawSql like below
```
                SELECT 
                  temperature as temperature,
                  $__timeEpoch(date_time) 
                FROM dbo.records 
                WHERE 
                  device='device1'
                ORDER BY 
                  date_time ASC
```

When the grafana started, the sql in alert rule is like below
```
SELECT 
  temperature as temperature,
  (date_time) 
FROM dbo.records 
WHERE 
  device='device1'
ORDER BY 
  date_time ASC
```

the $__timeEpoch is gone.
<img width="543" alt="image" src="https://user-images.githubusercontent.com/106508895/187078634-933bd107-9fa7-4676-9fc4-5eb178252ca1.png">
Is this a bug?

**What you expected to happen**:
the $__timeEpoch function stays as I provisioned.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start a MS SQL SERVER
2. Using alert-rule.yaml in attached zip when provisioning.
3. When Grafana started. check the sql in alert rule

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: Latest version of MS SQL SERVER 
- OS Grafana is installed on: Docker Image
- User OS & Browser: Docker Image
- Grafana plugins: none
- Others:
[alert-rule.yaml.zip](https://github.com/grafana/grafana/files/9439824/alert-rule.yaml.zip)

**Comment by zuchka** [comment]
please verify that you are using the newest endpoints:

Here are the newest stable API endpoints for provisioning Grafana alerts:

https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/api.json

**Comment by mellieA** [comment]
@soukeiz529 I see you're using provisioned alerts with yaml files. I've seen another issue with interpreting special characters in the files, forwarding on to our devs to find out if this is expected.

**Comment by mellieA** [comment]
@soukeiz529 I found out that there is a fix for this issue https://github.com/grafana/grafana/pull/54293
