### ISSUE TITLE
Query Builder: Remove Beta Tag from Query Builder

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#54378]
At some point/release we should remove the beta tag from the Loki Query Builder.

@ivanahuckova what do you think about this?

**Comment by ivanahuckova** [comment]
I agree athat we should remove it before 9.2, ideally now. As we use 1 component for Loki & Prometheus, @grafana/observability-metrics would you be okay with removing beta badge from Prometheus query builder?

**Comment by bohandley** [comment]
Part of our team is out this week so we would like to wait to make a decision. What are the criteria of things that are no longer listed as beta? @evandandrea are you able to find this out? Also, @aocenas, what do you think of removing the beta tag from the Prometheus query builder?

**Comment by aocenas** [comment]
@bohandley I have basically the same thoughts as @ivanahuckova on this :)

**Comment by bohandley** [comment]
We at Observability Metrics are all in agreement! Thank you @ivanahuckova and @aocenas, let us know how we can help.

**Comment by ivanahuckova** [comment]
Awesome! 🎉 I'll create a PR and add you as reviewer.
