### ISSUE TITLE
Megabit/s speedrate metrics

### ISSUE THREAD

**Issue by Deathlok** [grafana/grafana#5438]
Grafana version: 2.5.0
Datasource: influxdb
 OS: ubuntu server 14.04

Hi all,

I was trying to get the current speed rate in megabit/s from a server interface but I cannot figure out how to transform "if_octets" in Megabits using Grafana. Or better I don't know what query to use.

I used this query but I have no output 

`select derivative(mean(value), 1s) from "interface_rx" where "istance" ='em1' and "type" = 'if_octects' and time > now() - 4h group by time(1m)
`

Can you help me? Thank you

**Comment by rgelobterFH** [comment]
This will get you bits per second, which you can then set bits/sec as your Data Rate in Grafana. It will automatically convert to Mbps, Gbps, etc as needed.

SELECT 8 * derivative(mean("value"),1s) AS "value" FROM "ifHCInOctets" WHERE "instance" = 'ge-0/0/0' AND $timeFilter GROUP BY time($interval) fill(none)
