### ISSUE TITLE
Cloud Monitoring: Add Integration test for HTTP header handling

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#54391]
Add an integration tests like it is done for prometheus in https://github.com/grafana/grafana/blob/main/pkg/tests/api/prometheus/prometheus_test.go

to make sure headers are correctly sent.

for more details see https://github.com/grafana/grafana/issues/54314

**Comment by aangelisc** [comment]
This is currently blocked due to the fact that the GCM data-source doesn't specify the URL via the `JSONData` prop but instead uses hardcoded routes. Because of this there is no way to intercept the outgoing request.
