### ISSUE TITLE
Mixed datasources stop working in version Grafana v3.1.0 beta1

### ISSUE THREAD

**Issue by svenmueller** [grafana/grafana#5440]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- `Grafana v3.1.0 beta1`
- datasource: "--Mixed--" (multiple graphite datasources)
- ubuntu 14.04.

After upgrading to version `Grafana v3.1.0 beta1 `(from `Grafana v3.0.4`), Dashboards using the "--Mixed--" Datasource option are not working anymore. Each of the mixed graphite query works when the other ones are disabled (e.g. using the "eye" icon).

**Comment by torkelo** [comment]
what other data sources are you using? 

Cannot replicate any issue :(
http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=4&fullscreen&edit

**Comment by svenmueller** [comment]
@torkelo Sorry for the late reply. The provided example doesn't work and the response is showing error "Internal Server Error". As soon as you delete query B and C, the result for query A will show up again.

**Comment by torkelo** [comment]
@svenmueller InfluxDB had crashed, the example link is working now

**Comment by svenmueller** [comment]
@torkelo i just tried the latest version `3.1.0`. The problem still persist. Can we please open this issue again? When switching back to version `3.0.4` the dashboard is working proberly.

**Comment by svenmueller** [comment]
I'm happy to help with providing as much information as you need.

**Comment by torkelo** [comment]
what error do you get? Check chrome dev console

**Comment by AGirin** [comment]
Same here. Using Grafana v3.1.0. Mixed data sources stopped working. 

The query basically sits there forever and not return anything. Individually every query query works fine but if you combine them into mixed view dashboard is not working at all. You will just see this forever;

![image](https://cloud.githubusercontent.com/assets/5177657/16952997/1417b594-4d91-11e6-8f8d-07ef25f04d21.png)
