### ISSUE TITLE
Alerting: Cannot retrieve all alerting rules via API

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#54418]
**What happened**:

I'm building an integration for the Grafana Unified Alerting platform.

Missing in the `provision`-ing API that I think is the "right" way to manage Rules in the alerting engine:

1. `GET /api/v1/provisioning/alert-rules` - Dump all the rules currently provisioned so we can get UIDs and figure out if we need to create or update an existing rule.
2. An API to CRUD **Silences** - I have a system tracking whether a host is in a repair status. I need to set silences for hosts. I am using Graphite without tags, so metrics come in like `srv.$dc.$role.$hostname.$metric` and I have label extraction to pull out those elements. I need to sync the silences by hostname to the host status in my asset system.

I suspect these end points currently live elsewhere but are not documented. Currently there's:

https://grafana.com/docs/grafana/latest/developers/http_api/

Which doesn't mention API end points I've discovered by brute-forcing things and Googling viciously:

1. `GET /api/ruler/grafana/api/v1/rules/$namespace` fetches all the rule definitions
2. Feeding those events back through: `POST /api/ruler/grafana/api/v1/rules/$namespace` will create/update those rules, but then the alerts are no longer able to be edited in the Grafana UI.. attempting to interact with form controls on Rules created via the `ruler` API results in React.js errors locking the whole browser tab.  Why?  See #54169 for that ticket.
3. My guess is the **Silences API** is the [AlertManager API](https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml) ([view in SwaggerEditor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/prometheus/alertmanager/main/api/v2/openapi.yaml)) Maybe via `/api/alertmanager/grafana/` ??? I'm hesitant to use that API path as it's not documented anywhere?
4. What is `/api/ruler/grafana/`? It is not documented on the HTTP API docs page nor in the OpenAPI specification. Can I rely on it?

Without the documentation, I'm taking a real risk relying on these API end-points for making Grafana a critical piece of my infrastructure.

**What you expected to happen**:

All API paths to de documented. CRUD for most endpoints available. Some acknowledge that these APIs will be stable so I can rely on them.

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to build an integration to the alerting system and slowly go insane, in silence.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment]
just verifying that you are using these endpoints:

Here are the newest stable API endpoints for provisioning Grafana alerts:

https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/api.json


also:
See this thread for using Grafana's newest stable Alerting API:

https://community.grafana.com/t/alert-provisioning-the-newest-stable-api/68009?u=mattabrams

**Comment by reyjrar** [comment]
I'm seeing reports that the new Provisioning API is not working. Listing rules is missing in the Provisioning API. I've been chatting with someone here:  https://community.grafana.com/t/unified-alerting-alert-rule-provisioning-lifecycle-examples-needed/71465

They are stating grabbing the data out of the API and reinjecting it does not work.

I will be trying this later too and I guess I'll open a new issue since all my issues are being closed.

**Comment by 1ms-ms** [comment]
You can export the alert rules to json using GET curl and /api/v1/provisioning/alert-rules, but after resetting the infrastructure and using POST with the json we exported, it either doesnt show in the UI or returns problems with alert_id not being unique, thus making the usage of this API worthless.

Every source in grafana should be exportable via json/yaml without using API (like dashboards) and easily provisioned,as now you cant achieve full cycle of automation (or in case of alerts, any at all).

**Comment by AAverin** [comment]
I would argue that provisioning should work both ways – via json/yaml and via API.
API is convenient for teams without devops expertise.
Devops configures setup scripts via API, then someone else changes dashboards/alerts/whatever via UI and saves it.
Then in a timely manner backup script runs that retrieves all the changes via API and stores them somewhere like S3.
Setup scripts would load backed up data from storage(S3) and provision it via API back after instance is running/restarted.

This setup allows to run Grafana without any storage attached and still have everything provisioned correctly.

**Comment by 1ms-ms** [comment]
I may have overreacted with json/yaml import/export, but for now I struggle to provision alerts at all.

**Comment by AAverin** [comment]
Connected to alerts migration, I have opened this discussion: https://github.com/grafana/grafana/discussions/55220

**Comment by arash-bizcover** [comment]
So weird why there is no "Get **all the alert rules**" API at all?
How are we supposed to get the UID of the Alerts without having a way to list them .....

**Comment by arash-bizcover** [comment]
@zuchka Could you please guide us or reopen this issue? 

This was the first point OP mentioned in this issue:
![image](https://user-images.githubusercontent.com/62287461/195520266-63660983-a437-4140-bd13-3f8e9ab260c6.png)

**Comment by zuchka** [comment]
@arash-bizcover can you please check out the newest docs for the alerting http api and see if this does not resolve your issue
https://grafana.com/docs/grafana/latest/developers/http_api/alerting/#get-alerts

looks like we now have a `GET /api/alerts/` endpoint...

**Comment by arash-bizcover** [comment]
Thanks @zuchka 
The "alerting-api" is being said to be deprecated on the current version (v9) top of that page:
![image](https://user-images.githubusercontent.com/62287461/196063107-22fea2f4-b049-4caa-80fd-c2a7529d53a8.png)

Isn't the "[alerting_provisioning](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/)" the new API that has replaced "alerting-api" ??

**Comment by arash-bizcover** [comment]
This issue is clearly asking for the same thing @zuchka why do you need another issue for this.
Could anyone please reopen this issue and take a look at how issues are being taken care of please

@ana-yankova @aocenas @axelavargas @cinaglia @codesome @CrypticSignal @daniellee @dgzlopes @dprokop @Duologic @eamonryan @Ferril @FZambia @gillesdemey @gitdoluquita @gouthamve @gwdawson @iainlane @inancgumus @ivanahuckova @JacobsonMT @jdbaldry @jesusvazquez @joe-elliott @JohnnyQQQQ @Konstantinov-Innokentii @kovrus @kvrhdn @Llandy3d @lukasztyrala @mapno @marefr @maskin25 @matthewhelmke @Matvey-Kuk @mostafa @na-- @obetomuniz @oleiade @owen-d @pstibrany @rfratto @RichiH @rlankfo @robingustafsson @ryantxu @SadFaceSmith @sdboyer @sh0rez

**Comment by zuchka** [comment]
@arash-bizcover I've reopened the issue. Moving forward please refrain from pinging developers who are not already engaged on a given issue. It's just extra noise.

**Comment by armandgrillet** [comment]
We're gonna fix this with https://github.com/grafana/grafana/issues/48622#issue-1223895164, you will need two calls: one to get the alert groups and then a loop getting all the alert rules. Or you will be able to use the UI. We have prioritized this to critical, we want to get it done by Grafana 9.3 max.

**Comment by wjordan** [comment]
> you will need two calls: one to get the alert groups and then a loop getting all the alert rules.

Unless I'm mistaken, a call to get all alert rule groups also doesn't exist in the current API, which seems to be a necessary prerequisite to the first approach you're suggesting already exists here. Should this be opened as a separate issue?
