### ISSUE TITLE
Can I copy a dashboard from one organization to another organization programatically??

### ISSUE THREAD

**Issue by raj990** [grafana/grafana#5441]
I'm using grafana 2.6. My requirement is to copy a dashboard from one organization to another organization. That too i wanted to do it programatically. Is it possible to do this?

**Comment by torkelo** [comment]
Yes, via the http api, everything you can  do in the UI is using the http api. 

Will have to use two api keys for the different orgs

**Comment by marefr** [comment]
@AniGunner Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by AniGunner** [comment]
@marefr ok
