### ISSUE TITLE
Annotation-List HTML Content

### ISSUE THREAD

**Issue by theo416** [grafana/grafana#54423]
**Steps to reproduce**:
Create Annotation with a href(a)-Tag and Switch to Annotation List.

**Actual Result**:
The href-Tag is displayed like this: `<a href="http://Server/otherContent">Link-Text</a>` (In raw HTML)

**Expected Result**:
A clickable Link like [Link-Text](http://Server/otherContent).
On the trend panels, hovering over an annotation already displays it correctly.

And same for other HTML-Tag's like `<b>` 

**Environment**:
- Grafana version: v9.1.0-beta1
- User OS & Browser: Win10 & Firefox

**Comment by lpskdl** [comment]
Hi @theo416 ,

Currently, annotation item is a button and clicking it will leads to opening the dashboard where it belongs. What we could do is to display the html content properly inside the annotation item. 

Will this be alright?

**Comment by theo416** [comment]
Hi @lpskdl ,

Yes, that's correct. It should display the link blue with underscore on hover (like any other link).

Currently it looks like this:
![AnnotationTagList](https://user-images.githubusercontent.com/92939693/188938532-b6be9db0-b2d7-4efd-87c6-80acf55cd520.png)

And it should look like this (Like already on the dashboard), so you can click directly onto the link:
 
![AnnoHoverPanel](https://user-images.githubusercontent.com/92939693/188938716-2e1f6b71-9a8d-4c80-ad6b-6934f7b19893.png)

Thank you for your efforts,
Theo
