### ISSUE TITLE
Posting empty dashboard result in corrupted dashboard

### ISSUE THREAD

**Issue by corentingi** [grafana/grafana#5443]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Hi,
I'm using `v3.1.0-beta1`

I have posted an empty dashboard and it created one but with empty slug and so this dashboard cannot be accessed nor deleted from the web interface or the API...

POST `.../api/dashboards/db` with data  `{"dashboard": ""}` result in this error.

Is there a way to remove this empty dashboard ?

Thanks!

**Comment by corentingi** [comment]
I found a way to delete this dashboard by posting a new one with the same id.
I got the ID from the search method: `/api/search`
The solution is to post the following:
```json
{
  "overwrite": true,
  "dashboard": {
    "id": 154,
    "title": "Dashboard name"
  }
}
```

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/6741

**Comment by corentingi** [comment]
This bug re-appeared in 4.3.1 or prior
Here is a way to delete the faulty dasboard:

```
POST /api/dashboards/db
{
    "dashboard": {
        "id": 154,
        "title": "Something",
        "version": 0
    }
}
```
You need the find the matching dashboard version...

Then you can delete:
```
DELETE /api/dashboards/db/something
```
