### ISSUE TITLE
[9.1.1] Alerting - Url in annotations are not clickable in Teams notifications

### ISSUE THREAD

**Issue by mxmorin** [grafana/grafana#54442]
**What happened**:
When you create a rule with a field containing a url in the annotations, the field is clickable in the UI but not in the Teams notification

**Rule** :
![image](https://user-images.githubusercontent.com/58942529/187440591-a1905b91-5091-4f37-a4c0-b2fb2a1a8f9c.png)

**UI** : 
![image](https://user-images.githubusercontent.com/58942529/187440443-54418cc3-1d3f-4311-ad94-0644a0d4471b.png)

**Teams notification** : 
![image](https://user-images.githubusercontent.com/58942529/187440339-1607c054-4f11-4961-b18c-29d531910caa.png)

**Environment**:
- Grafana version: 9.1.1
- OS Grafana is installed on: Linux

**Comment by JacobsonMT** [comment]
From your screenshot it looks like Teams is recognizing a few URLs as hyperlinks and for some reason not recognizing the Kibana URL. We don't do anything special here to make those work, you might have to fiddle with your template to get Teams to correctly make it a hyperlink.

What happens if you put the Kibana annotation in its own line instead of in a list tag?

**Comment by aparcheminou** [comment]
Hi guys, I have the same issue since the last update : all my previous links that were working are not working anymore.
In the meantime, autogenerated links by Grafana (which I don't need) have been added below and they work....
@JacobsonMT a picture is worth a thousand words:
![image](https://user-images.githubusercontent.com/113507349/190101089-823e2913-a0bf-4879-baba-548442d86abd.png)

The link above that worked is dead; I tested by removing a href tags and result is identical. 
Thanks for your help!

**Comment by armandgrillet** [comment]
@mxmorin @aparcheminou Which OS are you using when receiving these alerts on Microsoft Teams? It seems there is a difference depending on the OS used.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

In Grafana 9.1 we moved from [Office365 connector cards](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card) to [Adaptive Cards](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) to fix an issue where images were not shown in Microsoft Teams messages https://github.com/grafana/grafana/discussions/38030#discussioncomment-3232575.

When I tested Office365 connector cards both on web and on the OSX desktop client URLs were not links (please see screenshot below):

![image](https://user-images.githubusercontent.com/85952834/191941127-613b7a90-eae8-4d8f-bf99-98847b09672c.png)

Here is a screenshot from the new Adaptive Cards message where URLs are also not links:

![image](https://user-images.githubusercontent.com/85952834/191941233-8175f0a5-a247-4bc0-99af-f9348a1c35c6.png)

However, it seems that some clients (perhaps Microsoft Teams on Windows?) made URLs into links where as other clients (such as Microsoft Teams on OSX) did not. It would be great if we could understand:

1. Do links work in Microsoft Teams for Windows?
2. Do links work in Microsoft Teams for web when using Windows?

Thanks!

**Comment by grobinson-grafana** [comment]
Hi! 👋 

In Grafana 9.1 we moved from [Office365 connector cards](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card) to [Adaptive Cards](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) to fix an issue where images were not shown in Microsoft Teams messages https://github.com/grafana/grafana/discussions/38030#discussioncomment-3232575.

When I tested Office365 connector cards both on web and on the OSX desktop client URLs were not links:

![image](https://user-images.githubusercontent.com/85952834/191941127-613b7a90-eae8-4d8f-bf99-98847b09672c.png)

Here is a screenshot from the new Adaptive Cards message where URLs are also not links:

![image](https://user-images.githubusercontent.com/85952834/191941233-8175f0a5-a247-4bc0-99af-f9348a1c35c6.png)

However, it seems that some clients (perhaps Microsoft Teams on Windows?) made URLs into links where as other clients (such as Microsoft Teams on OSX) did not. It would be great if we could understand:

1. Do links work in Microsoft Teams for Windows?
2. Do links work in Microsoft Teams for web when using Windows?

Thanks!

**Comment by armandgrillet** [comment]
No reply since 14 days, closing.

**Comment by dennis-spiegel** [comment]
Hi,

I found  a solution for this, quoting the URL in `<` and `>` works!
E.g. `<https://github.com/>`.

**Comment by cedricmof** [comment]
> Hi,
> 
> I found a solution for this, quoting the URL in `<` and `>` works! E.g. `<https://github.com/>`.

thanks @dennis-spiegel, I confirm that it works.
