### ISSUE TITLE
Dashboard: Unsaved changes prompt is displayed with no changes when editing a panel

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#54443]
**What happened**:

When we save a dashboard from Panel Edit, if we move away from the dashboard the "Unsaved changes prompt" is displayed with no changes. 

https://user-images.githubusercontent.com/239999/187440895-5468461f-9b42-4237-a823-d3908c20656d.mp4

**What you expected to happen**:

It should not be displayed with zero changes 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: V9.1.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanortegaalba** [comment]
It seems we're using two different methods to detect changes in the dashboard. This creates inconsistencies at the UX level. We should use the same method in both places.
