### ISSUE TITLE
Sharing a panel produces an image without axis and legend information

### ISSUE THREAD

**Issue by abadyan-vonage** [grafana/grafana#5444]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I am using Grafana 3.0.4 with InfluxDB as data source. It's running on RHEL 7.2.
I have a dashboard with multiple panels configured. Ideally, I would like the feature #2085, but for now I can do with just exporting a panel. 
I select a panel, choose Share and click on the "direct link" button. I get something like the following:
![panel](https://cloud.githubusercontent.com/assets/17905032/16379489/7dd11bc4-3c7a-11e6-81e7-deb84949d9ee.png)

As you can see, no axis information, no legend.
This is the request that is going out:
http://[ip]:3000/render/dashboard-solo/db/call-cluster?panelId=7&from=1466425368711&to=1467030168711&var-source=beta&var-host=%24__all&width=1000&height=500

**Comment by torkelo** [comment]
due to missing font packages
