### ISSUE TITLE
Plugins Catalog: Unable to filter plugins using special characters

### ISSUE THREAD

**Issue by murtazaqa** [grafana/grafana#54441]
**What happened**:
Plugin having name as "Graph (old)" was not shown in the list as soon as the search string had "(" character

**What you expected to happen**:
It should show "Graph (old)" plugin

**Environment**:
- Grafana version: v9.0.2

**Comment by usmangt** [comment]
Hi @murtazaqa,

Thanks for opening this issue.

I have tested this on https://play.grafana.com/ and it seems that if I press enter the first time after e.g. writing  "Graph (old)"  without quotes, it does not show the result.

But if I just press enter a second time, it shows it. 

Is it the same phenomenon in your case too?

**Comment by murtazaqa** [comment]
@usmangt 

Firstly, it should filter as I start typing. When it encounter special character e.g., "graph (", the filtered plugins don't return any value.

Secondly, when I hit enter to actually search then it handles the escape characters correctly and I can see filtered plugins.

**Comment by murtazaqa** [comment]
Fixed in https://github.com/grafana/grafana/pull/54474
