### ISSUE TITLE
[Feature Request] Auto fill line plot when no data

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5445]
Hi,

In my usage case, I need to extend the last value to now. I would like to know if it's possible to add an option.

Example usage case: Nagios send log to ElasticSearch ONLY when a service state CHANGE:
![nanannagiso](https://cloud.githubusercontent.com/assets/15362041/16383126/140b6316-3c84-11e6-8646-901cd2e48a70.png)
Here, the service is critical since 3 days and Nagios send data only when a state change. So the user can think that the service is UP since 3 days.

So, the feature request is to add an option to "Auto fill" the line if there's no data.

Thx

Grafana 3.0 
Datasource: ElasticSearch

**Comment by torkelo** [comment]
This is a feature that has be added to the TSDB, Graphite supports this using keepLastValue function. Not sure Elasticsearch has something like this right now. It does have a "missing value" option in the metric value where you could specify that a missing value should result in a specific value (say 0)
