### ISSUE TITLE
[Feature Request] Convert null value to integer in SingleStat (influxdb)

### ISSUE THREAD

**Issue by blackhill** [grafana/grafana#5446]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Grafana 3.0
Influxdb 0.13
OS : CentOS

Convert null value from influxdb to an integer like 0 in a SingleStat panel.
Reason : I would like to display a red background if no value was returned by influxdb

**Comment by torkelo** [comment]
You can do this using the InfluxDB fill(0) function
