### ISSUE TITLE
Timeseries panel switches showLegend to true

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#54472]
**What happened**:

Dashboard is generated as JSON with `showLegend: false` [here](https://github.com/grafana/mimir/blob/cacd7593458475964391ce27acf2f3059d290a6c/operations/mimir-mixin-compiled/dashboards/mimir-writes.json#L655-L679)

When I load it into Grafana the legend is visible.  If I go into Settings / JSON Model it flips to `true`:

```
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
```

**What you expected to happen**:

Legend should stay not-shown.

**How to reproduce it (as minimally and precisely as possible)**:

Use the above JSON.

**Anything else we need to know?**:

If you have the permissions at Grafana Labs you can load this via [URL](https://admin-ops-us-east-0.grafana.net/grafana/d/8280707b8f16e7b87b840fc1cc92d4c5/mimir-writes?from=now-1h&to=now&var-datasource=ops-cortex&var-cluster=prod-eu-west-0&var-namespace=cortex-dedicated-12&orgId=1&refresh=10s&editview=dashboard_json).

**Environment**:
- Grafana version: v9.2.0-7a340f48pre (7a340f486b)
- Data source type & version: Prometheus / please include instructions how to get the version.
- OS Grafana is installed on: Linux I guess.  How would I know, it's hosted by a different team.
- User OS & Browser:  Windows 10 Version 21H2 (Build 19044.1889), Google Chrome 104.0.5112.102 (Official Build) (64-bit)
- Grafana plugins: dozens of them, please include instructions here how to get a list if you want this. 
- Others: what.

**Comment by zuchka** [comment]
@grafana/backend-platform I'm moving this to your board but it might belong elsewhere, like with the Dashboards squad. Please move as needed 👍

**Comment by ivanortegaalba** [comment]
Hi @bboreham, I'm trying to reproduce this issue, but I cannot.

[Here is a super simple dashboard](https://play.grafana.org/d/b4XpscMVz/54472-timeseries-panel-switches-showlegend-to-true?orgId=1) with `showLegend: false` and you can see when the dashboard is open the state is persisted and the legend is hidden.

**Comment by bboreham** [comment]
Thanks for taking a look.
One thing I notice is that my file has `"schemaVersion": 14` while yours has `"schemaVersion": 37`; is it possible that has an impact?

Is there a concise list somewhere of all the changes between version 14 and 37 ?

**Comment by sdboyer** [comment]
> One thing I notice is that my file has `"schemaVersion": 14` while yours has `"schemaVersion": 37`; is it possible that has an impact?

Quite plausibly, yes.

> Is there a concise list somewhere of all the changes between version 14 and 37 ?

AFAIK there's no concise list - only [the actual migration behaviors](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/DashboardMigrator.ts).

The new schema is analyzable, such that we'll be able to generate concise lists of deltas. i can't say anything about how high a priority actually generating those lists would be - only that it'd be feasible for a machine to do it :)

**Comment by bboreham** [comment]
Thanks @sdboyer!  This line catches my eye: https://github.com/grafana/grafana/blob/be5369d6fa2fd5c843b246db1b6e5b6943c5ffee/public/app/features/dashboard/state/DashboardMigrator.ts#L796

Setting `"displayMode": "hidden"` is a work-around for my problem.

**Comment by sdboyer** [comment]
excellent!

gonna close this, as that's probably the best resolution for this that's immediately at hand :)

**Comment by bboreham** [comment]
You could have that migration code honor the value of `showLegend` if set.
How old is schema 37?

**Comment by sdboyer** [comment]
mm, fair...reopening. Will leave that up to actual members of the dashboard team :)

it's pre-9.0, but only slightly.

**Comment by ivanortegaalba** [comment]
> You could have that migration code honor the value of `showLegend` if set. How old is schema 36? (Which would be the newest version affected by the behaviour)

I don't see any problem with that. Let me open a quick one. Good catch!

**Comment by ivanortegaalba** [comment]
@bboreham probably you don't need to modify the dashboards you currently have if the PR in the migration script is merged. However I'd recommend to use the latest version 😄
