### ISSUE TITLE
aliasByMetric leaving trailing close paren

### ISSUE THREAD

**Issue by jblaine** [grafana/grafana#5447]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

3.0.3, but that's another bug -- there's no way to find that out via the web UI once logged in!

- What datasource are you using?

Graphite

- What OS are you running grafana on?

RHEL 7

- What did you do?

I constructed a graph with metric pieces: ourserver, our_application, our_counter, derivative(), aliasByMetric()

- What was the expected result?

A metric with name **our_counter**

- What happened instead?

A metric with name **our_counter)**

Note too that the same thing happens if I do aliasByMetric() first and then derivative()

**Comment by torkelo** [comment]
Bug in Graphite please upgrade Graphite (think it's fixed)
