### ISSUE TITLE
BarChart: Color by values and new data getting wrong colors

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#54485]
Looks like the Barchart with value mappings that define are not updating the color when the data changes. (

Escalation: https://github.com/grafana/support-escalations/issues/3754

Test with the dashboard below, but add some more rows. 

![Screenshot from 2022-08-30 19-53-00](https://user-images.githubusercontent.com/10999/187508839-4970237f-1423-46df-8df3-60a134fe913b.png)

Adding some rows, they get wrong color (no value mapping color applied):
![Screenshot from 2022-08-30 19-54-17](https://user-images.githubusercontent.com/10999/187508911-325536f4-3fcb-4f0c-9ace-461eebd43a54.png)

Might be linked / same issue encountered in https://github.com/grafana/grafana/issues/47844

<details>
   <summary>JSON Block</summary>

```json

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 971,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [
            {
              "options": {
                "Linux": {
                  "color": "red",
                  "index": 0
                },
                "Other": {
                  "color": "purple",
                  "index": 2
                },
                "Windows": {
                  "color": "blue",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "unique_count"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "yellow",
                  "mode": "fixed"
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "auto",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "pluginVersion": "9.1.0-76166",
      "targets": [
        {
          "csvContent": " os_type,unique_count\n Linux,22\n Windows,2\n Other,9\n Linux,8\n Windows,6\n Windows,13\n Linux,4\n Windows,1\n Windows,3\n Windows,1",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "transformations": [],
      "type": "barchart"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "barchart",
  "uid": "qxthYlWVz",
  "version": 3,
  "weekStart": ""
}

```
</details>

**Comment by codeincarnate** [comment]
#52038 was contributed to fix this. Unfortunately it breaks value mapping and so it was reverted. I believe a fix is needed that can work with both value mapping and the color fix.

**Comment by torkelo** [comment]
@codeincarnate @oscarkilhed 
When testing this I see that the function getColor 
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/barchart/BarChartPanel.tsx#L229 

The colorByField.values.get is returning undefined when it get's values for indices that was not part of the first render data. So the getColor function must be cached somehow and not updated on data updates.

**Comment by oscarkilhed** [comment]
@torkelo 

Yes I did some quick investigation on this when we reverted a PR that caused another regression. I commented on it [here](https://github.com/grafana/grafana/issues/47297#issuecomment-1219109093) I think we're in agreement on what's causing it?

**Comment by oscarkilhed** [comment]
@codeincarnate @torkelo @leeoniya 
I did some more research on this.

The [`getColor`](https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L229) function is set in [`preparePlotConfigBuilder`](https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L265) which is passed to GraphNG as [`prepConfig`](https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L275)

getColor brings [`colorByField`](https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L225) in it's closure and uses the values from `colorByField.values` to set the color. This is necessary to be able to set the color of bars depending on the string field used as the label.

The problem is that `prepConfig` is only executed when GraphNG is mounted(?) so `getColor` will never be replaced with an instance of the function with the current values in `colorByField.values`

Is it possible to rebuild the configuration every time the data changes? Is it going to wreck performance? Maybe `getColor` needs to be set somewhere else, where it's updated when the data changes.

**Comment by leeoniya** [comment]
is the solution to re-run the `colorByField` matcher at the panel level https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/utils.ts#L333

and then store it in something like a `colorByFieldRef`

https://github.com/grafana/grafana/blob/a230439679ff129b0b56f9283a63047c3a28971c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L99

which will then be used by `getColor()`?

:thinking:
