### ISSUE TITLE
[Bug] bad escaped character in Templating variable

### ISSUE THREAD

**Issue by zijian1981** [grafana/grafana#5449]
I'm submitting a
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
-  What Grafana version are you using?  3.1.0-alpha1
-  What datasource are you using?  es1.4.4
-  What OS are you running grafana on?  redhat linux 6.4

I have created a templating variable named subsysname and another templating variable named ap which is associated with the subsysname.
{"find": "terms", "field": "ap", "query":"subsysname:$subsysname"}

But if the subsysname variable  contains the character '(', for example:"PMSE(Web)", I'll get a problem like this ,at the upper right corner of the page:

Templating
Template variables could not be initialized: JSON.parse: bad escaped character at line 1 column 64 of the JSON data

**Comment by zijian1981** [comment]
some other characters like "-" may be also need escaped

**Comment by daniellee** [comment]
dupe #5452
