### ISSUE TITLE
Geomap: Panel's Go back button focused

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#54499]
After today's `main` merge, the Go back button seems to be focused when hovering over the map. It seems to stop when you click on the options right pane.

https://user-images.githubusercontent.com/88068998/187541529-a0da5a98-6e9d-4716-aa8f-a4e1ca3b70df.mov

**Comment by drew08t** [comment]
I'm not seeing this issue anymore, please confirm if we can close this, thanks!
