### ISSUE TITLE
Alert List doesn't have "Normal" state from Prometheus Datasources

### ISSUE THREAD

**Issue by Edoz77** [grafana/grafana#54494]
**What happened**:
Alert List plugin doesn't show "Normal" state from alerts directly upload on Amazon Managed Prometheus.
![Alert List](https://user-images.githubusercontent.com/17069089/187517048-fd5ec9c4-fa10-4cad-bfc4-fd674689b097.png)

**What you expected to happen**:
Alert not in Firing mode too.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup an Amazon Managed Prometheus Workspace
- Add the datasource to Grafana
- Upload alerts and rules in Amazon Managed Prometheus
- Use the Alert List plugin

**Anything else we need to know?**:
Seem to have the same issue with a Prometheus host on the same k8s cluster than Grafana.
The problem must be due to the Prometheus API distinction between Rules and Alerts (the plugin seem to only use Alerts?)
https://prometheus.io/docs/prometheus/latest/querying/api/#rules
With the Rules API call we can see our Rules and the current Alerts in Firing:
![Prometheus API Rules](https://user-images.githubusercontent.com/17069089/187517226-1b4ffae9-00f3-4474-b759-c2ea5509e472.png)
![Prometheus API Rules Firing](https://user-images.githubusercontent.com/17069089/187517375-2cd516a9-acd8-49aa-887b-4fc2129e6841.png)

**Environment**:
- Grafana version: 9.1
- Data source type & version: Amazon Managed Prometheus
- OS Grafana is installed on: K8S
- User OS & Browser: Windows/Chrome
- Grafana plugins: Alert List
- Others:

**Comment by mellieA** [comment]
I'm seeing something similar on play.grafana.org, only firing alerts are shown in the alert list, even though the filter is set to include the normal state: 

Used the test alert panel at https://play.grafana.org/d/Kb2RgVQnk/alert-panel?orgId=1&refresh=5s&editPanel=2 

![Screen Shot 2022-09-02 at 6 44 22 PM](https://user-images.githubusercontent.com/18175287/188249399-78a179e3-0d3f-48e0-a529-8f1e4efa84ca.png)

Here you can see there are a lot of non-firing alert rules for this datasource:

![Screen Shot 2022-09-02 at 6 48 16 PM](https://user-images.githubusercontent.com/18175287/188249427-e84c5265-53bd-4e32-815d-930311d2f375.png)

**Comment by gillesdemey** [comment]
This is a bug in the alert list panel; we intentionally hide alert rules with no instances matching filters (state or label filters) but for Prometheus and other cloud rules the "inactive" rules do not have any instances at all – and are thusly hidden.
