### ISSUE TITLE
Alerting: users should always be able to edit broken alertmanager configuration.

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#54505]
In Grafana Alerting there are some alertmanager configurations that are invalid or unparseable. In many cases the user is able to edit these broken configurations in the user interface until the config is valid.

However, there are still some cases where the configuration API will return a 500 error, or the backend will refuse to start up, because of broken configuration. Grafana should never crash loop or fail to display broken configuration, because fixing the config in those cases requires direct modification of config in the Grafana database. This is much more error-prone than editing in the user interface.

This requires some research and decisions:
* How should the Grafana Alertmanager operate in the face of invalid alertmanager config? Should it use a previous, valid config? Should it enter a "paused" state?
* How can we effectively warn about broken alertmanager config? If it's broken and the application still runs, we should ensure that users know about this so they don't miss critical alerts when config is broken.
* How can we detect bugs in the write path and validation? Right now start-up refusal and bad UI editing state are loud signals of invalid configuration. We need a way to still find bugs that can lead to invalid config being accepted.

**Design doc** https://docs.google.com/document/d/1m7fWyDMsP4AlSSIk-vMQ0NGQwA5yEemS_cPBinZU3Es/edit

**Comment by konrad147** [comment]
Design doc https://docs.google.com/document/d/1m7fWyDMsP4AlSSIk-vMQ0NGQwA5yEemS_cPBinZU3Es/edit
