### ISSUE TITLE
[ Feature request] How to use korean?

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#5450]
Hi. Brother

I'm running grafana 3.0.0v.

I want to play the graph with korean.

But, Don't recognize the Korean..
<img width="1223" alt="2016-06-28 6 59 36" src="https://cloud.githubusercontent.com/assets/13283116/16411534/82d26036-3d62-11e6-9dfe-c2ea069a6d1d.png">

How to apply Korean in parser?

```
app/plugins/datasource/graphite/lexer.ts
app/plugins/datasource/graphite/parser.ts
```

**Comment by bergquist** [comment]
I'm afraid you have to fall back to writing queries in raw format.
