### ISSUE TITLE
Unable to detect newly installed panel plugins

### ISSUE THREAD

**Issue by rubixlai** [grafana/grafana#5451]
* **I'm submitting a ...**
- [* ] Bug report

Please include this information:
- What Grafana version are you using? 

v3.0.4
- What datasource are you using? 

N/A
- What OS are you running grafana on? 

CentOS 6
- What did you do? 

grafana-cli plugins install grafana-clock-panel
- What was the expected result? 

shows clock panel in add panel list
- What happened instead?

Can't find clock panel in "ADD PANEL" list

Appreciate help in advance

**Comment by bergquist** [comment]
@rubixlai Did you restart the grafana server? Can the grafana user access the plugin folder?

**Comment by rubixlai** [comment]
yes, and the permission of plugins shows like this 
drwxr-xr-x 5 grafana grafana   4096 Jun 29 10:46 plugins

**Comment by bergquist** [comment]
@rubixlai does the CLI manage to download the plugin? There should be a folder named grafana-clock-panel in the plugin folder.

**Comment by rubixlai** [comment]
@bergquist , yes clock-panel folder is exactly where it should be, after one night without doing anything, it appears in the "ADD PANEL", thanks for the support anyway, closing it.
