### ISSUE TITLE
Table panel header and footer in v9.1.1 is not fixed at the top and bottom of panel view when scrolling down

### ISSUE THREAD

**Issue by mc-em** [grafana/grafana#54516]
**What happened**: I just recently upgraded to v9.1.1 and noticed that the Header and Footer of table panel also moved when I scroll down the panel. Please find below screenshot.

**What you expected to happen**: We expect it to be fixed at the top and bottom of panel view and always visible even when we scroll down/up just like on previous version in 8.4. (I did not check if same behavior in 8.5)

**How to reproduce it (as minimally and precisely as possible)**: Choose table panel. records must be a lot enough for user to scroll down. Tick enable the header and footer options

<img width="960" alt="snap_footer1" src="https://user-images.githubusercontent.com/110811012/187638208-6fac5c8c-3da4-43d8-bd5b-096cc7cb5232.png">

<img width="956" alt="snap_footer2" src="https://user-images.githubusercontent.com/110811012/187638245-e3a05062-155a-40de-adc9-a76487667381.png">

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: Elasticsearch v7.11
- OS Grafana is installed on: Windows
- User OS & Browser: Microsoft Edge
- Grafana plugins: Table Panel

**Comment by funfried** [comment]
Exactly the same for me with Grafana 9.1.2 and Data source InfluxDB 2.4.0 running in the Grafana Docker container and viewing with latest Brave Browser on MacOS 12.5.1

**Comment by ssunny1081** [comment]
Exactly the same Issue for me with Grafana 9.1.2 using the latest Windows Chrome Browser

**Comment by supilee** [comment]
still reproducible in 9.1.3

**Comment by supilee** [comment]
still reproducible in 9.1.5

**Comment by mvalletta** [comment]
all table panels are affected by this bug
Grafana version: 9.1.5
Data source type & version: postgresql 14
OS Grafana is installed on: ubuntu
User OS & Browser: ubuntu, chrome and firefox
Grafana plugins: Table Panel

**Comment by mdvictor** [comment]
Hello! Work is in progress to fix this bug.
