### ISSUE TITLE
[Bug] Bad escape characters in templating -- problem when '-' is in the variable result

### ISSUE THREAD

**Issue by michal-dudek** [grafana/grafana#5452]
Grafana version:
- grafana-3.0.4-1464167696

Datasource:
- Elasticsearch

OS grafana is working on
- Red Hat, kernel 2.6.32-573.8.1.el6.x86_64

---

Dear Developers / Support,
First of all I want to thank you for developing Grafana ... it is really very good and powerful tool.

Lately I have been struggling with a problem while using Grafana variables in templating. I have noticed, that when the result inside the Grafana template variable (in my case host names, lets say $fec) contain hyphen characters ('-') ... this variable cannot be used in other queries.

Example:
$fec = 'this-is-my-host' <- result from query
$device = "... AND host: $fec" <- this gives "bad escape character ..." error

Images
![1](https://cloud.githubusercontent.com/assets/20183359/16412784/7482f600-3d2e-11e6-829a-5391b6e75d41.jpg)
![2](https://cloud.githubusercontent.com/assets/20183359/16414155/6b7c7c36-3d36-11e6-8ad6-39fb983ce549.jpg)
![3](https://cloud.githubusercontent.com/assets/20183359/16412786/74bde9a4-3d2e-11e6-83f4-7a55f8df8f96.jpg)

Issue is similar to:
- #2972
- #2918

**Comment by JozoVilcek** [comment]
Yes, I have the same problem on grafana 3.1.0 with elasticsearch 2.x

**Comment by michal-dudek** [comment]
@JozoVilcek thanks for the feedback, we will see that the developers will say.

**Comment by zijian1981** [comment]
+1
same problem

**Comment by whitelynx** [comment]
Seems related to #5314.

**Comment by aegixx** [comment]
+1

**Comment by daniellee** [comment]
Sorry, we seem to have missed this issue.

Now in version 4.2.0 of Grafana, it seems to work on the demo site at least:

http://play.grafana.org/dashboard/db/elasticsearch-templated?var-source=backend&var-host=server-5&panelId=1&fullscreen&edit

If this is still a problem could you also include details about the elasticsearch response:

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by torkelo** [comment]
this should be fixed in 4.x as we now by default lucene escape variable interpolated in template variable queries
