### ISSUE TITLE
QueryFields/Input fields are broken in the recent Chrome browser

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#54535]
Initially reported [here](https://raintank-corp.slack.com/archives/C13QEUGLB/p1661934429060559).

It seems that there are some inputs, or combination of inputs, that potentially cause cursor jumps/focus loss on the code editor.

Some examples both in Firefox and Chrome:

https://user-images.githubusercontent.com/1069378/187705345-3cc11c1f-12e1-407c-886b-74b59d81fbe5.mov

https://user-images.githubusercontent.com/1069378/187705346-e1b2a864-8046-4e27-b6cb-182e4f43703c.mov

**Comment by aknuds1** [comment]
It's also browser dependent. I'm not having this problem in MacOS (Chrome), nor in Firefox on Arch Linux. The one browser where I'm having problems is Chromium on Arch Linux. F.ex. if I type "na" into the query input using Chromium, the following text appears: `Enter a Loki query (run with Shift+Enter)na`.

Still in Chromium, if I type first an opening curly bracket, then "n", auto-completion adds a closing curly bracket to the code input and moves the caret after it, so I end up typing f.ex. `{n}amespace="cortex-prod-09"` instead of `{namespace="cortex-prod-09"}`.

**Comment by svennergr** [comment]
I noticed, that this is not only the case for the code-editor but also other input fields. In my case it was the `derivedFields` URL input.

**Comment by mwoodson-coinbasecloud** [comment]
This is happening to me on MacOS, Chrome 105.0.5195.52.  Yesterday this wasn't happening, I updated chrome, and now it's happening.  Not sure if it's related, but it's bugging!

I type chars in, and it "ends" (like you would hit the end key, goes to the end of the line) and then other weird characters start appearing.  Very strange.

**Comment by outinspace** [comment]
This started happening for me today.

MacOS 12.5.1.
Chrome Version 105.0.5195.52 (Official Build) (x86_64)

I didn't experience this on Firefox.

**Comment by honganan** [comment]
> Also adding my short observation from Chrome on MacOS.
> 
>  Screen.Recording.2022-08-31.at.16.20.32.mov

I caught this too. In MacOS, after upgrading Chrome to 105.0.5195.52（Official Build） (arm64). I received user reports then I tested, before upgrading it's ok, and after upgrading it acts like this video shows. Safari works alright, not sure how it happends.

**Comment by mwennrich** [comment]
same on Ubuntu (latest Chrome)

**Comment by lucagouty** [comment]
same here, wasn't happening yesterday, MacOS Chrome `105.0.5195.52`

**Comment by svennergr** [comment]
Thanks for your feedback, which we highly appreciate. 

We narrowed down the issue and are working on a bugfix.

**Comment by svennergr** [comment]
> Is there anything we can tweak in chrome to make this work while a bug fix is being worked on? Any hints on what changed in chrome to make this stop working so it can be tweaked back in the short term while we do get the bug fix and are able to upgrade grafana?

I am unsure about tweaks in Chrome itself and also unsure what they exactly changed, such that this is failing now. I will try to check on that.

You can follow the patch/change in this PR https://github.com/grafana/grafana/pull/54566. If that gets merged to `main` you can run your Grafana from that branch.

**Comment by shipa988** [comment]
i have the same issue with Chrome 105.0.5195.52 от macOS 12.4

**Comment by nikitapecasa** [comment]
@svennergr Hi 👋 

I have one more important observation and a question.

- I'm getting the same chrome specific issue in Grafana v8.2.7 (d2cccfe91e), but interestingly enough not in v9.0.1 (14e988bd22).
- Would the fix be back-ported to 8.2.x? or only to 9.1.x?


In my case the issue in 8.2.7 is the same as @mwoodson-coinbasecloud described - query editor jumps to the end on each key press and weird symbols appear (ufeff).

Works ok in Safari. Does not work in chrome and chrome canary.
- Grafana v8.2.7
- macOS 12.4
- safari Version 15.5 (17613.2.7.1.8)
- chrome canary Version 107.0.5272.0 (Official Build) canary (arm64)
- chrome Version 105.0.5195.52 (Official Build) (arm64)

**Comment by iameli** [comment]
Getting this in both Brave and Chrome.

Brave:
Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64)

Chrome:
Version 105.0.5195.102 (Official Build) (arm64)

**Comment by jcputter** [comment]
will this fix to backported to 7.4.~ release ?, i have some old install with that along with 9.1.3...Firefox 104.0.1 seems ok but Chrome 105.0.5195.102 is broken

**Comment by yongzhang** [comment]
same issue, expecting an emergency fix

**Comment by daniel-anova** [comment]
Microsoft Edge v105.0.1343.27 has joined the list of chrome-based browsers affected by this issue.

**Comment by asvatov** [comment]
Ubuntu 18.04 and Chrome 105.0.5195.102 (Official Build) (64-bit)
After updating Chrome I faced inadequate behaviour of input.

**Comment by gabor-grafana** [comment]
should be fixed by https://github.com/grafana/grafana/pull/54566

**Comment by gabor** [comment]
should be fixed by https://github.com/grafana/grafana/pull/54566

**Comment by Andrey-cisco** [comment]
Same issue on Chrome Version 105.0.5195.52 (Official Build) (x86_64)

parse error at line 1, col 3: syntax error: unexpected IDENTIFIER, expecting = or =~ or !~ or !=

**Comment by ivanahuckova** [comment]
I am closing this issue as https://github.com/grafana/grafana/pull/54566 was merged. @kaydelaney @svennergr @ashharrison90 feel free to reopen if I miss-understood and this is not fixed yet.

**Comment by michael-burt** [comment]
Are there any workarounds identified for older versions of Grafana? There are a lot of users that cannot upgrade for a variety of reasons.

**Comment by m62534** [comment]
@michael-burt Having same issue - for now, I am copy-pasting queries after typing on another place (vscode, etc).

**Comment by natellium** [comment]
@michael-burt the most straightforward work around would be to use a different browser, the issue seems to be present in or copy pasting as @m62534 mentioned.

**Comment by renanqts** [comment]
It is a bit better, but the filters after the pipe are not working properly.
version 9.1.4

**Comment by svennergr** [comment]
> It is a bit better, but the filters after the pipe are not working properly.

Hi @renanqts,
could you please describe this issue further?
Thanks!

**Comment by jnyi** [comment]
Could we get a patch to Grafana 7.5.* too? Thanks!

**Comment by natellium** [comment]
We released [9.1.4](https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-1-4/) with the fix. If you're still finding any issues in that version, please let us know. 

Besides, we'll be releasing the fix for v8 this week and assessing the possibility of releasing for earlier versions.

**Comment by kaydelaney** [comment]
The previous patch could cause problems if using an older plugin that refers to `@grafana/slate-react`.
[Here's a PR ](https://github.com/grafana/grafana/pull/55027) that should fix that issue, to be included with 9.1.5

**Comment by Syalone** [comment]
Dear Contributor @natellium @kaydelaney 
May I know if you are releasing the fix for v7.3.* or v7.* as well? Currently my organization is using Grafana v7.3.5 (11f305f88a) and it might be challenging for us to upgrade to v8 / v9 in short period of time Orz.

**Comment by rgnv** [comment]
@Syalone typically only the last two versions are officially supported, with exceptions made for contracted enterprise customers for EoL patches. If you're a contracted customer, submit a ticket to see if there will be a 7.x release.

**Comment by sachabrants** [comment]
A workaround is to copy paste the query you want. I use log editor to show some logs, edit the query in a text editor, paste it back and run the query.

**Comment by Syalone** [comment]
> @Syalone typically only the last two versions are officially supported, with exceptions made for contracted enterprise customers for EoL patches. If you're a contracted customer, submit a ticket to see if there will be a 7.x release.

Thanks a lot for your clarification and @sachabrants thanks a lot for the workarounds! :)

**Comment by danielgattiluxor** [comment]
Any update on the backport to v8?

**Comment by mithi** [comment]
> Is this fix going to be backported to v8?

Looking forward to the answer to this question too!

**Comment by luciocorral** [comment]
Any update about this? We started suffering this issue in several Linux and macOS computers after last Chrome update.

**Comment by islopma** [comment]
> I am closing this issue as #54566 was merged. @kaydelaney @svennergr @ashharrison90 feel free to reopen if I miss-understood and this is not fixed yet.
> 
> The fix should be part of the next v9.1.4 release.

Please, can the fix be backported for v8.x? We can't easily upgrade to v9.x and it's an annoyance to use it as is

**Comment by nitronick600** [comment]
Just ran into this - any way to get this fixed?

**Comment by natellium** [comment]
@nitronick600 @islopma @luciocorral @mithi @danielgattiluxor @faraonc Hey there, as mentioned above this will be backported to 8 and released this week. Sorry for the inconvenience!

**Comment by avg07** [comment]
Just tested the image [8.5.12 ](https://hub.docker.com/layers/grafana/grafana/8.5.12/images/sha256-d320728ccb9156e7d251aa2e45ca3e18fe2914c23d9a1395a0ca698ca956003a?context=explore)
Same problem.

**Comment by fredrik84** [comment]
https://user-images.githubusercontent.com/5592150/191514889-26352e8d-ab2c-4eac-8b19-436ea695f4f4.mp4

https://user-images.githubusercontent.com/5592150/191515405-04090d01-4b97-4f79-aa4b-d7ba0710bac3.mp4

I still encounter this issue on 9.1.6 and I even tried downgrading to 8.5.13 just to make sure. Running Chrome, it works on Firefox. I also get this in other query fields.

**Comment by victorolinasc** [comment]
I am getting all sorts of input errors in Firefox too. v9.1.5 here. Commented on another issue https://github.com/grafana/grafana/issues/55521#issuecomment-1253958789

**Comment by mohammedafzal0702** [comment]
> It is a bit better, but the filters after the pipe are not working properly. version 9.1.4

im also facing same

**Comment by svennergr** [comment]
> > It is a bit better, but the filters after the pipe are not working properly. version 9.1.4
> 
> im also facing same in 7.2.1

Thanks for your feedback @mohammedafzal0702 and @renanqts. There [is a fix for that](https://github.com/grafana/grafana/pull/55576), which will be released next week.

**Comment by mohammedafzal0702** [comment]
Dear Contributor @natellium @kaydelaney
May I know if you are releasing the fix for v7.2.1 as well?

**Comment by dongseokk** [comment]
Looks like a backport for v7 has been released.
Let me try it out.

https://github.com/grafana/grafana/commits/v7.5.17

**Comment by asaf400** [comment]
> ~Just tested the image [8.5.12 ](https://hub.docker.com/layers/grafana/grafana/8.5.12/images/sha256-d320728ccb9156e7d251aa2e45ca3e18fe2914c23d9a1395a0ca698ca956003a?context=explore) Same problem.~
> 
> Upd: Image 8.5.12 already deleted from DockerHub.
> 
> Upd: New image [8.5.13](https://hub.docker.com/layers/grafana/grafana/8.5.13/images/sha256-e50578a25326b1b443fce526dca3b2d447ae02dfaea7a4f1f52235c6f8336057?context=explore) works fine!

be wanted, 8.5.13 image also has an issue with inviting users,
the fix has not been release, but has been merged with the v8.5.x branch:
https://github.com/grafana/grafana/pull/51964/files - issue introduced
https://github.com/grafana/grafana/pull/55585/files - issue fixed

related: 
https://github.com/grafana/grafana/issues/51634#issuecomment-1238305742
https://github.com/grafana/grafana/pull/52894
https://github.com/grafana/grafana/blob/release-8.5.13/pkg/api/org_invite.go#L73

**Comment by fredr** [comment]
I'm having similar problems in grafana 9.1.7 with firefox (105.0.3-1). It happens especially when using ~. Not sure if I should open a new issue, or report it here, but I was asked in the loki slack write in this issue.

[Screencast from 2022-10-20 15:39:51.webm](https://user-images.githubusercontent.com/762956/196964694-eb890dba-0eb6-4d90-a2fd-5a86036c7115.webm)

**Comment by dewe** [comment]
The tilde problem happens to me as well, when using Chrome. I looks exactly like [this older issue](https://github.com/grafana/grafana/issues/31968).

**Comment by mator** [comment]
any chance to release updated 7.5.x version of grafana with this fix? thanks!

**Comment by antwacky** [comment]
I'm seeing this in 8.3.11, 8.3.5 is the current version of Grafana in the loki-stack helm chart, I thought upgrading the image to the latest 8.3 would include a fix.

**Comment by dfenerski** [comment]
This seems to be still an active issue in latest `loki-stack` helm charts

**Comment by daniel-koudouna** [comment]
> This seems to be still an active issue in latest `loki-stack` helm charts

If anyone still encounters this issue, the default tag for the `loki-stack` helm chart and possibly others has not been updated. Set `grafana.image.tag`  in your values yaml to a newer version, e.g:

```yaml
grafana:
  enabled: true

  image:
    tag: 10.3.1
```
