### ISSUE TITLE
[Feature] Filter unique entries in table using specified column / field

### ISSUE THREAD

**Issue by dudek-michal** [grafana/grafana#5453]
Grafana version:
- grafana-3.0.4-1464167696

Datasource:
- Elasticsearch

OS grafana is working on
- Red Hat, kernel 2.6.32-573.8.1.el6.x86_64

---

Dear Developers / Support,
Would it be possible to add a feature for 'table', which will be sorting unique entries on a specified column / field?

Example ... this is what is today
![1](https://cloud.githubusercontent.com/assets/20183359/16415139/093b122a-3d3c-11e6-8842-6b310ee4a671.jpg)

Instead of having multiple entries about the same device ... I would like to have unique filter per 'device' column ... which means in my case I should see only one entry.

**Comment by jkong3** [comment]
Mine is similar.  is there any solution to this?  I would like column to be unique, if the time stamp is same, just need one.  thanks

**Comment by michal-dudek** [comment]
@jkong3 I did not find the workaround for that ...

**Comment by aocenas** [comment]
This seems like something that could be either done on the query level or since version 7.0 with [transformations](https://grafana.com/docs/grafana/latest/panels/transformations/#transformations)
