### ISSUE TITLE
[Panel/Stat] Sparkline graph is irrelevant when stat value is high (> 200k)

### ISSUE THREAD

**Issue by Telokis** [grafana/grafana#54542]
**What happened**:

Sparkline is unusable when stat value is high.  
It makes it look like there are enormous spikes but the lack of y-axis/hover prevents me from figuring things out.  
There is no way for any user to know what the spikes mean, making the graph completely useless.

![image](https://user-images.githubusercontent.com/6382729/187721213-6bbb491b-0cc1-4977-9650-3576c691be4e.png)

**What you expected to happen**:

Either show the y-axis values or force the axis to start at 0 so I can have a better sense of scale.

**How to reproduce it (as minimally and precisely as possible)**:

Have any metric with a high enough value that Grafana will try to be smart about the minimal y value of the sparkline graph.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: Prometheus datasource to a VictoriaMetrics backend.
- User OS & Browser: Win10 / Chrome
- Grafana plugins: None

**Comment by leeoniya** [comment]
this is a good point. i think the current logic doesnt require large values for this behavior. it simply uses the data min and max for the range.

https://github.com/grafana/grafana/blob/530dd63ac62fac5d5f5a4ece3081db0f9ceb6709/packages/grafana-ui/src/components/Sparkline/Sparkline.tsx#L96

> Either show the y-axis values or force the axis to start at 0 so I can have a better sense of scale.

starting at 0 would be problematic if you have values below and above zero. we could potentially draw a dashed line through zero in that case, maybe.

showing a y axis with inset tick values for high/low might work as well and does not have the issue of a pinned zero with a mixed pos/neg range.

**Comment by cedsana** [comment]
Maybe we could add a bit more configuration options to the sparkline?  
Letting users configure the y axis could make the sparkline more attracive

**Comment by torkelo** [comment]
@Telokis not sure I understand your issue? why not just specify min: 0  (under standard options)  if you want the y-axis to start at zero. 

If you want y-axis tick labels your better of using time series panel (graph). Could see an feature request there to add a "big stat" option to overlay a big number ontop of a graph

**Comment by Telokis** [comment]
Thanks, I didn't know about the `min: 0`. I can't try right now but it might do the trick.

However, I still think this issue is relevant. The Sparkline graph doesn't give enough information for it to be anything more than a purely aesthetic feature.  
That's not necessarily a problem but it would be nice to mention it somewhere.

You say I should use a time series panel but I simply thought I could avoid having both a graph and a Stat by using this panel that seemed to do both at once.

**Comment by torkelo** [comment]
@Telokis stat panel is for big numbers, the sparkline is just there for aesthetic and to provide a small amount of context / trend
