### ISSUE TITLE
Alerting: make "Reduce" the default instead of "Classic Condition"

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#54552]
Currently, the default type of expression when creating an alert is `Classic Condition`, which exists mostly for backwards compatibility reasons but doesn't preserve labels from Prometheus queries.

By changing this default to `Reduce` we make sure that labels are preserved just like in Prometheus (see [related issue](https://github.com/grafana/grafana/issues/46094)). This helps us being [Prometheus Alert-Generator compliant](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md) and avoids confusion around why labels are not available for templating.

**Comment by weaversam8** [comment]
It looks like the [default expression type was changed to `ExpressionQueryType.math`](https://github.com/grafana/grafana/blob/c8e7e7ccf199da5462902f1df672be1b99333977/public/app/features/expressions/ExpressionDatasource.ts#L57), is this still an issue?

**Comment by konrad147** [comment]
Fixed by https://github.com/grafana/grafana/pull/55102
