### ISSUE TITLE
Unable to use toggles in panel options

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#54550]
**What happened**:
On the latest `main` the toggles from the options panel don't seem to work as they should. Trying to toggle will scroll to the first (?) toggled element.

Looks like the issue was introduced in https://github.com/grafana/grafana/pull/54400

Seems to be reproducible in all the panels. 
(This also created some additional bugs in Geomap - the Back button is always focused when the tooltip is visible). I can provide further details if needed.

https://user-images.githubusercontent.com/88068998/187757062-8a00aa59-563e-46e9-a827-8d7f7725ccf0.mov

**Comment by joshhunt** [comment]
@adela-almasan Are you able to consistently reproduce this? I got it to happen once, but never again.

@polibb would you like to check if this is related to your change?

**Comment by joshhunt** [comment]
Managed to reproduce it fairly consistently. 

Focus a text field, scroll the text field out of view, then try and interact with a toggle (or any other control?). It might work fine on the first click, but breaks after that.


https://user-images.githubusercontent.com/46142/187895830-5ed52216-3629-452a-8bc6-fb181f8cfa3e.mp4
