### ISSUE TITLE
Docs: Incorrect link to "Creating a systemd service to manage the agent"

### ISSUE THREAD

**Issue by nessita** [grafana/grafana#54575]
**What happened**: Following the documentation published at https://grafana.com/docs/grafana-cloud/quickstart/noagent_linuxnode/ I tried to follow links for "Creating a systemd service to manage the agent" to configure node_exporter as a daemon in my system, but the link took me to the same page I was in.

**What you expected to happen**: When clicking on the link, I should have been taken to https://grafana.com/docs/grafana-cloud/data-configuration/agent/agent_as_service/

**How to reproduce it (as minimally and precisely as possible)**: Visit https://grafana.com/docs/grafana-cloud/quickstart/noagent_linuxnode/ and click on "Creating a systemd service to manage the agent".

**Anything else we need to know?**: A public link to the docs to submits PR would be amazing!

**Comment by GrafanaWriter** [comment]
This looks like it's been fixed.
