### ISSUE TITLE
Plugins: Core plugins requesting invalid logos

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#54571]
**What happened**:
![image](https://user-images.githubusercontent.com/1173299/187901671-a4d90571-f3ff-4c4d-8167-23a83ab33dc6.png)

**What you expected to happen**:
Requests should probably not happen or images should be valid

This has happened as a result of the recent introduction of plugin schematization

**Comment by tolzhabayev** [comment]
@wbrowne git pull, verify it was fixed by https://github.com/grafana/grafana/pull/54580 and close this issue?
