### ISSUE TITLE
Snapshot dropdown disabled - Makes dashbaord as code validation with snapshot worst?

### ISSUE THREAD

**Issue by ahurtaud** [grafana/grafana#54578]
**What happened**:
With the merge of https://github.com/grafana/grafana/pull/52827
We are unable to select dropdowns on snapshots (which were working for our setup...)

We followed a presentation done at PromCon in order to generate a snapshot with dashboard as code to validate pull-requests "visually" on top of code changes. See https://youtu.be/kV3Ua6guynI?t=413

By disabling dropdowns on snapshot, its harder to validate that the dashboard as code change work for dropdowns :(

WDYT?

**Comment by mellieA** [comment]
@ahurtaud the queries for a snapshot cannot be re-executed, so the drop downs were removed so users wouldn't get the impression that they could be used. 

Can you share more about your use case and how this was working for you before? Please include a video and the versions of grafana that you were using.

**Comment by ahurtaud** [comment]
Hello @mellieA ,

As explained in the video, the dropdowns were working for our snapshots (tested in 9.0.5).
Here is a video record of our pipeline generating snapshot from our dashboards as code.

https://user-images.githubusercontent.com/25080995/188470376-9189c7aa-52c4-474d-b859-35bc5b744f70.mp4

below is the code sample we use to create the snapshots:
```shell
    # Compile first so that we see any jsonnet errors.
    dbjson=$(mktemp)
    jsonnet -J vendor  -J . "${DASHBOARD}" > "${dbjson}"

    # Generate the snapshot JSON in to a temporary file.
    json=$(mktemp)
    jq "{ \"dashboard\": ., \"expires\": ${EXPIRY} }" < "${dbjson}" > "${json}"

    # Use token authentication if we have a token.
    CURL=(curl -fsSL)
    if [[ ! -z "${TOKEN:-}" ]]; then
        CURL+=(-H "Authorization: Bearer ${TOKEN}")
    fi

    # Create the snapshot
    resp=$("${CURL[@]}" -X POST -H 'Content-type: application/json' -H 'Accept: application/json' \
                        "${GRAFANA}/api/snapshots" --data-binary "@${json}")
```

**Comment by ahurtaud** [comment]
any news @mellieA ?

**Comment by fernsmark** [comment]
We are experiencing the issue. The snapshot dropdown filters did run the variable query and return the list of values.

[https://github.com/grafana/grafana/pull/52827#issuecomment-1267284495](url)

**Comment by fernsmark** [comment]
Allowing to pick the variables from filters is actually an important feature and it did work(v8.5.x) up until this release.

We still want to create a snapshot with the default 'All', the variable will still run the query and return the list of values to be selected. However, now in the UI it is not possible to make the selection. eg. the dashboard snapshot consists of many hosts and instead of showing All the hosts, we want to be able to filter by each host within the snapshot.

Please undo this change as it broke all the snapshots feature or provide an alternate solution.
Thanks.

<img width="1920" alt="grafana-snapshot-issue" src="https://user-images.githubusercontent.com/17345658/193880598-378c9479-b582-420d-b53b-e3b8d6ae9944.png">

**Comment by joshhunt** [comment]
Snapshots should not execute any queries to data sources at all. If they do, that's a bug that needs to be fixed.

**Comment by ahurtaud** [comment]
> Snapshots should not execute any queries to data sources at all. If they do, that's a bug that needs to be fixed.
> 
> The purpose of a snapshot should be a frozen... snapshot in time of the data, able to be shared without authentication, without any queries being able to be ran.

Actually, with my usecase explained above (mainly dashboard as code testing), all the panels data execute queries to the prometheus datasource...

To me this is heavily used and valuable. 
Would you consider adding a `GF_SNAPSHOT_ALLOW_QUERY` config or something similar?

Thanks,

**Comment by ndombroski** [comment]
> Snapshots should not execute any queries to data sources at all.
@joshhunt If that is the case, wouldn't that contradict and invalidate the [Snapshot API](https://grafana.com/docs/grafana/v9.0/developers/http_api/snapshot/) entirely? Data cannot be included in the `POST` request to create the snapshot, so the data must be queried when the snapshot is loaded into the browser. 

I definitely see your point about portability though, so I support @ahurtaud 's proposal for a configuration option. For dashboards that are source-controlled, it is a common use case to utilize the Snapshot API to preview dashboards, and that would be made impossible if snapshots cannot execute any queries.

**Comment by RichiCoder1** [comment]
Wanted to see if there was an update for this? We finally got around to updating our Grafana instance and greatly miss the ability to preview Dashboards before publishing them.

**Comment by natellium** [comment]
👋  As mentioned above snapshots shouldn't allow for queries to be executed thus we won't be adding this functionality. Nevertheless, we have a public dashboards alpha feature that may be better suited to your use case. More info [here](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/)
