### ISSUE TITLE
Repeat by variable not working correctly with InfluxQL editor

### ISSUE THREAD

**Issue by zeroone82** [grafana/grafana#54587]
@bohandley update
**Description:** With InfluxDB InfluxQL, [repeating a panel](https://grafana.com/blog/2020/06/09/learn-grafana-how-to-automatically-repeat-rows-and-panels-in-dynamic-dashboards/) with a template variable and enabling the influxBackendMigration interpolates all selected variables into the query for all repeated panels.
**Acceptance criteria:** Each repeated panel should only use one of the selected variables.
**Status:** [PR](https://github.com/grafana/grafana/pull/54934) is in, added scopedVars to tags. 

**What happened**:
Repeating a panel with "Repeat by variable" doesn't work correctly when using InfluxQL editor. Panels get repeated but all of them include all variables selected. This can be confirmed by checking the raw query for each panel.

Switching from editor to raw query (no other changes made) fix this issue.

**What you expected to happen**:
Each repeated panel should only include only one of the variables selected when working with the editor.

**How to reproduce it (as minimally and precisely as possible)**:
Recording attached
![grafana_query](https://user-images.githubusercontent.com/7476701/187932716-1e593164-3b77-4750-96aa-6ccc33b665e6.gif)

**Environment**:
- Grafana version: 9.1.0 Enterprise
- Data source type & version: InfluxDB 1.9.5
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Arch Linux / Firefox 104
- Grafana plugins:
- Others:

**Comment by bohandley** [comment]
Thank you for adding us @ivanahuckova, I have not been able to reproduce this on Grafana enterprise v9.1.0.

This is the variable I am repeating
![Screen Shot 2022-09-08 at 8 38 16 AM](https://user-images.githubusercontent.com/25674746/189125840-00d93dfd-2313-4b5e-8393-caaa192f3d51.png)

<img width="445" alt="Screen Shot 2022-09-08 at 8 50 14 AM" src="https://user-images.githubusercontent.com/25674746/189126166-379a164a-33b3-47d2-901a-9c5f218b7e77.png">


Using the query editor
![Screen Shot 2022-09-08 at 8 43 53 AM](https://user-images.githubusercontent.com/25674746/189125968-083673d0-219d-4d16-915e-ce87769a4bff.png)

![Screen Shot 2022-09-08 at 8 43 10 AM](https://user-images.githubusercontent.com/25674746/189126483-f8808912-e5cf-44ac-9fd4-f9cde137169b.png)

and checking that the query in one of the repeated panels is not including all variables
<img width="654" alt="Screen Shot 2022-09-08 at 8 47 28 AM" src="https://user-images.githubusercontent.com/25674746/189126353-87c088b6-7783-4e77-8fd0-22c62d9c40e5.png">

@zeroone82 May I get the following from you? It is hard to see exactly what the variable is and how you are interpolating it in the video you shared.
-a screen shot of the variable creation or the query for the variable you are repeating
-a screen shot of how you are interpolating the variable

Thank you!

**Comment by zeroone82** [comment]
Hey @bohandley, here's a screenshot from my variable's query:
![image](https://user-images.githubusercontent.com/7476701/189132075-67477096-6c32-47be-948c-8bcce16367de.png)

Something I forgot to add on my original post, I have enabled the feature **influxdbBackendMigration** by suggestion of a support engineer. I just tested the same on an instance without this feature enabled, and it seems to be working correctly.

**Comment by bohandley** [comment]
Without the feature toggle, the template variables are handled by the classicQuery function in the frontend datasource. With the feature toggle, we handle the template variables on the front end and then send them to the backend. My previous though about that with the fix mentioned above was a red herring. The influx backend migration handles the repeated variables across panels, but only with the raw query. @zeroone82, you mentioned this in the original description where you stated that switching to the raw query fixes the issue.

I have more exploring to do to see why the raw query repeats the variables correctly and the query editor does not on the backend. 

The query is built the same way for the raw query and the editor
https://github.com/grafana/grafana/blob/82e32447b474565e5f815c5cfffc9d91da875f87/pkg/tsdb/influxdb/query.go#L21
and both look like 
SELECT mean(*) FROM "disk" WHERE "device" =~ /^(grpcfuse|vda1)$/ AND time >= 1662649259229ms and time <= 1662670859229ms GROUP BY time(20s) fill(null) ORDER BY time ASC

So, I believe somewhere in the backend we are identifying that it is a repeated panel, a template variable, and the raw query and doing it correctly. I am looking through the Influx backend code, `grafana/pkg/tsdb/influxdb` and then will explore further outside that to see where this is happening.

**Comment by bohandley** [comment]
We had not handled scopedVars with tags. scopedVars are used for repeating variables to identify which panel gets which template variable. I think [this](https://github.com/grafana/grafana/pull/54934) will fix it, just needs a review.

**Comment by bohandley** [comment]
The fix is in version 9.1.6 :)
