### ISSUE TITLE
[Bug] Prometheus query accidentally canceled

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#5459]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  - af216ecf8396c349c538adbd4e17e72eecab300f
- What datasource are you using?
  - Prometheus
- What OS are you running grafana on?
  - Mac
- What did you do?
  - create two graph panel, and set same query
- What was the expected result?
  - show two graph panel correctly
- What happened instead?
  - one panel stop loading

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

dashboard json:
https://gist.github.com/mtanda/c5b23a62bcdb8b2de667722754bfdcee
screen capture:
![cancel](https://cloud.githubusercontent.com/assets/224552/16421579/77f383d8-3d90-11e6-84f8-249ca917bf39.png)

@torkelo This line might be wrong. The request ID should be unique in dashboard. (/cc @stuartnelson3)
https://github.com/grafana/grafana/commit/81e9aa4de430ac9a865ecad91feb6cea91c0666c#diff-a59431ca1f1f94cdb3ae176c50a585b2L80

**Comment by mtanda** [comment]
@torkelo This is a critical bug. should fix this before releasing 3.1.0.

**Comment by torkelo** [comment]
Yes, guess we need to include panel Id and query index in the request ID

**Comment by stuartnelson3** [comment]
This was handled in the original pull request, but was dropped in the refactoring.

Is there a reason to handle generating the unique query id at the datasource level? It seemed sensible in `metrics_panel_ctrl.ts`, since it would guarantee a unique id regardless of datasource:

https://github.com/grafana/grafana/commit/81e9aa4de430ac9a865ecad91feb6cea91c0666c#diff-f87378d7f7c033569f3a0e8e5cf22d51L186

**Comment by torkelo** [comment]
@stuartnelson3 well that had some issues, leaking internal and type specific stuff from the data source implementation into the panel base class which should not know or care about this. The metric panel send panel id which should be enough for this use case I think.

**Comment by stuartnelson3** [comment]
I think this might have an issue with multiple queries in the same panel, which is common when querying prometheus.

Graphite is currently using just the `panelId` to create the unique portion of the `requestId` (https://github.com/grafana/grafana/commit/81e9aa4de430ac9a865ecad91feb6cea91c0666c#diff-fba613d41443865e5e1d416756aae4a4R43), but multiple queries from the same panel will have the same `requestId`, canceling each other.

At first blush, adding `panelId` + `target.expr` seems like an appropriate solution. However, if a user sends a request, changes the query slightly, and then sends another request before the first completes, the initial request won't be canceled as it will have a different `requestId` owing to its different `target.expr` value. I think using `panelId` and `target.refId` is the best solution.

I've created a PR that only uses data available within `datasource/prometheus.ts`, keeping the creation of a unique `requestId` the responsibility of individual datasource implementations.

**Comment by grobie** [comment]
@torkelo If the panel sends the panel ID, why can't it also send the metric reference ID? Seems to be at at the same level of knowledge and would guarantee a unique identifier for every use case / datasource.

Given @stuartnelson3's Prometheus specific change has been merged, this is now less of an issue for us, but I'm not sure I understand what was wrong with that part of the original implementation.

**Comment by bergquist** [comment]
I'm closing this issue since its been fixed for Prometheus.
