### ISSUE TITLE
Grafana managed alert: new rule page crashes when typing only letter(s) for "Evaluate every"

### ISSUE THREAD

**Issue by fabio-silva** [grafana/grafana#54609]
**What happened**: When creating a new rule for Grafana managed alerts, deleting the "Evaluate every" field and typing only a letter will crash the page.

**What you expected to happen**: Probably a validation error after I try to submit, as happens with other combinations there.

**How to reproduce it (as minimally and precisely as possible)**: Go to `/alerting/new`, select Grafana managed alert, erase what's in "Evaluate every" (step 2) and type a letter.

**Anything else we need to know?**: Error comes from function `checkEvaluationIntervalGlobalLimit`, which calls `rangeUtil.intervalToMs`. This last one then finally calls `rangeUtil.describeInterval`, which throws an error when the interval is an invalid string.

**Note**: in this rule creation page, there's a typo related to this same function: when we insert an interval lower then the configured `min_interval`, we get this warning in the page:
`Global evalutation interval limit exceeded`, should be "evaluation".

**Environment**:
- Grafana version: 9.1.1

**Comment by mellieA** [comment]
Thanks for reporting this, I tried it on version 9.1.2 and it looks like it's fixed. Please reopen if I missed a step 

![Screen Shot 2022-09-02 at 6 10 28 PM](https://user-images.githubusercontent.com/18175287/188248024-5aa4dd03-41a6-4755-8190-01042c28286e.png)

**Comment by fabio-silva** [comment]
@mellieA Are you sure about this? Because I checked the code on release-9.1.2 and it's the same, I still get the crash.

**Comment by mellieA** [comment]
@fabio-silva Another user has reported this so I was looking again. I can only reproduce this on self-managed grafana, it doesn't happen in my cloud instance which makes me think that it might be related to a configuration setting. I'm linking it to the other issue https://github.com/grafana/grafana/issues/55357
