### ISSUE TITLE
Custom time range for a "day"

### ISSUE THREAD

**Issue by vitalyd** [grafana/grafana#5460]
I have a graphite-backed time series recorded at 30s intervals for each calendar day (with the exception of weekends, but that's not overly relevant).  On each of these days, the data points start at, say, 8am and end at 5pm.  I'd like to summarize(<timeseries>, 1d, avg) this series, but define what 1d actually means; instead of it being (essentially) midnight to midnight, I'd like it to be (as an example) 10am - 3pm only.

Is that possible?

Thanks

**Comment by torkelo** [comment]
the summarize function is processed in Graphite, so you have to open a feature request for that project :)

**Comment by vitalyd** [comment]
Fair enough, thanks.  I wasn't sure if Grafana could stitch together separate Graphite queries and mimic this behavior -- looks like there's no such facility.
