### ISSUE TITLE
Can grafana exports dashboard to csv?

### ISSUE THREAD

**Issue by zhenzh** [grafana/grafana#5462]
I'm using grafana 2.6 generated a dashboard which is composed with table and single stat.

At present, I have to use screen capture  of the dashboard to show the overall data to others who have no access to the grafana. But it do be a struggle for me and the reader as the data shown in picture is not editable.
I'd like to export the captured data of the whole dashboard into a file with some readable/editable format, such as csv so that post-process of these data(draw customized charts in excel) can be available. 

Will the export dashboard to file function be available by grafana?

**Comment by torkelo** [comment]
You can use dashboard snapshot to share a dashboard with an external user who do not have access to your grafana server.

There are export to csv in table panel in 3.0

**Comment by zhenzh** [comment]
I don't find the dashboard snapshort, only snapshort for a specified panel.
Where can I snapshort the whole dashboard which contains multiple panels.
