### ISSUE TITLE
Adding additional metadata to results_clicked events in dashboard search

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#54659]
The backend team is going to work on improving the relevance of search results. We would like to compare the performance of the legacy and new search engines, and it the near future, we'll also run A/B tests on different configurations of the new search engine.

To measure and compare the performance of these versions, we would like to add more metadata to relevant events.

**Given**
The two events we're logging for search results clicked:
- dashboard_search_result_clicked 
- manage_dashboards_result_clicked 

**When**
Logging the event through rudderstack

**Then**
Please add additional metadata to the event: 
- result_rank: The position of the clicked result. E.g. the position for the result at the top of the list is 1.
- search_engine_version: Is it the legacy search engine or the new one? If it's the new one, which configuration version is it? Should be discussed with the backend team how we can get this data.

___________________________________
In addition, please also add search_engine_version metadata to the dashboard_search_query_submitted and manage_dashboards_query_submitted, so that we can calculate the click-though rate accordingly.

**Comment by zsofiakomaromigrafana** [comment]
@ArturWierzbicki How can we differentiate between different versions of the search engine? For now it's just old search vs. new search which we know based on the feature toggle, but in the future, we might want to test different configurations.
