### ISSUE TITLE
Fatal crash in secrets migration when LockExecuteAndRelease fails to release

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#54653]
Will Browne reported this error:
```
Failed to start grafana. error: there is already a lock for this actionName: secret migration task 
there is already a lock for this actionName: secret migration task 
Exiting.
```

Most likely setup for this was pausing (with the debugger) in the middle of migration, then killing the process before the LockExecuteAndRelease function did the release. The next run, this happened.

Throwing an error is good, but it should not be fatal since the migrator runs regardless of if there are secrets. Maybe a big ugly warn instead.

**Comment by guicaulada** [comment]
Running migration on the background all this does is stop the background service, not Grafana.

Fixed by https://github.com/grafana/grafana/pull/54676
