### ISSUE TITLE
Plugins: Add support for error plane and 207 in /api/ds/query

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#54664]
Use the [errutil](https://github.com/grafana/grafana/tree/main/pkg/util/errutil) package for /api/ds/query.

Example usage:
https://github.com/grafana/grafana/blob/aee13563cefd5ce555115b8e1e90882b4ce7d733/pkg/models/shorturl.go#L9-L15

- [x] https://github.com/grafana/grafana/pull/54750
  
**Note:** 
- Any HTTP 4xx returned from a downstream server indicates a client error so we should be able to return status and actual response body to the end user to help them understand what's wrong. Only potential drawback is security in case responses includes any sensitive information, however the datasource proxy already works in suggested way and just forward the downstream status/response.
- Any HTTP 5xx returned from a downstream server indicates a server error and we probably shouldn't return detailed information about this to end users since it can contain sensitive information.

**Comment by wbrowne** [comment]
Done
