### ISSUE TITLE
Geomap: Reordering layers removes measure layer

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#54668]
When re-ordering map layers, measure vector layer is removed, so any measurements are not persistent.

![Image](https://user-images.githubusercontent.com/60050885/188206752-dfa5209d-6298-4118-a83f-31630d5d939d.gif)

**Comment by ryantxu** [comment]
I don't see any issue at all with this... seems totally fine.  The use case for using measure tool while editing is pretty slim to start with :)

**Comment by drew08t** [comment]
Just circling back to this, and agree that this is not an issue.
