### ISSUE TITLE
Problem Report: Playlists organization

### ISSUE THREAD

**Issue by evandro-portugal** [grafana/grafana#5467]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
v3.1.0-beta1

Hello, 
There's been two issues with the playlists, one is that it's not respecting the order that they are assigned to be displayed (they are displaying at "random"). And the other issue can be checked on this image:
The selected dashboards are being show in front of the +add dashboard button from availables.

![playlists](https://cloud.githubusercontent.com/assets/16374689/16470247/7ba03170-3e2b-11e6-80c9-c85d0d218bfb.png)

ps: Are template variables cycling for playlists on the roadmap for the next releases?

**Comment by evandro-portugal** [comment]
Hi guys, I see that the fix for this issue was postponed, but I've got to say, this is really annoying since we are not able to have control over the show order for the dashboards, having long names dashboards make the playlist creation impossible, since when we add two dashboards it becomes impossible to add the dashboards that are on the top of available list.
The sort order is very important, but the fix for the component size is a must, since it makes impossible to use this feature.

**Comment by torkelo** [comment]
fixed!
