### ISSUE TITLE
[UI] Missing legend when using grafana import to my website

### ISSUE THREAD

**Issue by nguyencaochien** [grafana/grafana#54685]
![chart in my website](https://user-images.githubusercontent.com/24190909/188346619-9fba1ea7-806a-4a3c-9125-79fc1e6a3941.png)
![chart in grafana admin](https://user-images.githubusercontent.com/24190909/188346622-cbfff67c-1dc7-46ed-95db-77ffe179bfa6.png)

**What happened**:
I'm import grafana chart in my website, but not show the legend (bottom). If i change bottom to right/table, it's ok. Only happent when position is bottom
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @nguyencaochien,

Thanks for opening this issue.

Can you please provide the steps of reproduction so that we can try to reproduce it on a test machine? 

Thanks.

**Comment by nguyencaochien** [comment]
HI @usmangt ,

My steps : 
1. Go to grafana page, create chart "UPS Power (300kVA)", show legend at bottom
![Screen Shot 2022-09-06 at 10 53 57](https://user-images.githubusercontent.com/24190909/188543944-d2b6486e-7966-49a0-9e45-9a60bfbb271b.png)

2. Embed this grafana into my website (using iframe).
3. Go to my website, and view this grafana
![Screen Shot 2022-09-06 at 10 56 15](https://user-images.githubusercontent.com/24190909/188544043-4a231ba0-f44c-4b84-af9b-22dbfc23927b.png)

Can not see the legend of  chart "UPS Power (300kVA)". Only show in grafana page, and not show in my website. It's not happen if is change position to right

**Comment by usmangt** [comment]
Hi @nguyencaochien,

Thanks for defining the steps.

I have tried but cannot reproduce it as in my case I can see the legend at the bottom.

Did you enable the configuration parameter inside grafana.ini file i.e. 

`allow_embedding = true
`

If yes and it is still showing like that then please do the following, 

- Goto https://play.grafana.com/ 
- Create a test visualisation and put it as iframe on your website.
- See if you can reproduce it
- Also, what kind of web server you are using where you put this embed ifram linke i.e. apache, nginx etc ?

**Comment by nguyencaochien** [comment]
Thank @usmangt ,

I have resolved this issue. 

Thanks so much for your support.
