### ISSUE TITLE
 Error 1062: Duplicate entry '114-xxxxxxxx' for key 'UQE_alert_rule_org_id_uid' 

### ISSUE THREAD

**Issue by ritubajaj89** [grafana/grafana#54680]
What happened:
I want to update grafana from v7.3.5 to v8.4.6, so I copied history data from our live environment, and then start grafana.
I upgraded grafana from version 8.4.2 to 9.1.0 without unified alerting. DB was cloned before upgrade. Now while trying to enable unified alerting I am getting below error:

level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="Error 1062: Duplicate entry '114-rMBR2ZGVz' for  │
│ logger=migrator t=2022-09-03T03:19:21.502720885Z level=error msg="Exec failed" error="Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'" sql="code migration"        │
│ Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'                 │
│ migration failed (id = move dashboard alerts to unified alerting): Error 1062: Duplicate entry '114-rMBR2ZGVz' for key 'UQE_alert_rule_org_id_uid'

What you expected to happen:
Migration is done successfully with other environment having less data.

How to reproduce it (as minimally and precisely as possible):
GF_UNIFIED_ALERTING_ENABLED: false
  alerting:
    enabled: true  
  unified_alerting:
    enabled: false  
add these values in grafana.ini

Anything else we need to know?:
Production there are 25000 alerts to be migrated across 150 organisations and it is failing for multiple org_ids. DB size is 50 GB.

Environment:

Grafana version: v9.1.0
Data source type & version:
OS Grafana is installed on: linux
User OS & Browser:
Grafana plugins:
plugins:
  - instana-datasource
  - farski-blendstat-panel
  - yesoreyeram-boomtable-panel
  - jdbranham-diagram-panel
  - natel-discrete-panel
  - agenty-flowcharting-panel
  - pierosavi-imageit-panel
  - simpod-json-datasource
  - marcusolsson-json-datasource
  - grafana-piechart-panel
  - natel-plotly-panel 
  - vonage-status-panel
  - grafana-worldmap-panel
  - https://github.com/GoshPosh/grafana-meta-queries/archive/refs/tags/0.0.9.zip;goshposh-metaqueries-datasource
  - flant-statusmap-panel
  - grafana-athena-datasource
  - grafana-timestream-datasource
Others:

**Comment by JacobsonMT** [comment]
Hi @ritubajaj89, thanks for reporting this issue! I have a few questions that will help us track this down:

Have you tried re-running the migration, and if so does it fail on the exact same ID (`114-rMBR2ZGVz`) or does it change?

> How to reproduce it (as minimally and precisely as possible):
> GF_UNIFIED_ALERTING_ENABLED: false
> alerting:
> enabled: true
> unified_alerting:
> enabled: false
> add these values in grafana.ini

Was this meant to have `unified_alerting: enabled: true`?

**Comment by ritubajaj89** [comment]
Hi @JacobsonMT, 
To answer your queries:

Yes, I have tried running migration multiple times and ID keeps on changing. But I have found issue with org id 114 and 78 so far, as they are biggest ones as of now. Also, random alphanumeric value 'rMBR2ZGVz' keeps on changing. No reference of same in database as well. 

Was this meant to have unified_alerting: enabled: true?   -- My bad, grafana.ini snapshot is when I disabled unified alerting as it didn't work, but anytime before starting migration, I enable unified and disable alerting option.

Please let me know, if any other information is required from my end.

**Comment by malulitom** [comment]
Hi, we have the same kind of problem. Generated uids are case sensitive but our database is not ! For example, during the migration process an uid **r**MBR2ZGVz is generated and then another one **R**MBR2ZGVz. 
So we got  Error 1062: Duplicate entry key. 
Someone have a tips to resolve this issue ?

**Comment by ritubajaj89** [comment]
Can anyone look into this ?

**Comment by alexweav** [comment]
@malulitom None of the [supported databases](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases) are case in-sensitive on indexes by default. Are you using a database that isn't one of these supported ones? Alternatively, is it possible someone directly modified that index out from underneath Grafana, like adding collation?

We're trying to reproduce this on our side, in the meantime is it possible your table acts similar to the above one and is case insensitive? @ritubajaj89

**Comment by ritubajaj89** [comment]
@alexweav - We are using AWS RDS - Engine MariaDB. No one has changed/modified index for database from our side.

**Comment by alexweav** [comment]
Okay, that's good to know. It sounds like your issue is likely a different one from @malulitom's in that case.

**Comment by armandgrillet** [comment]
Closing as more than two weeks without answer, please reopen if you have more information.

**Comment by ritubajaj89** [comment]
I would like to reopen this issue as I did not hear anything from grafana team and still unable to start with unified-alerting.

**Comment by JacobsonMT** [comment]
Hi @ritubajaj89, thanks for your patience here. I think you're correct in your concerns, MySQL (and by extension MariaDB) does in fact use case insensitive collation here that I believe is causing our short uid generator to collide if uids are generated in quick succession.

I'm not certain on the more general implications of this but in the meantime I should be able to fix how we generate uids during migration to prevent this from blocking. I'll work on a PR shortly.
