### ISSUE TITLE
Auth: Take into account `oauth_skip_org_role_update_sync` for locking down UI

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#54688]
**What happened**:

With `oauth_skip_org_role_update_sync` enabled, the UI remains locked out for oauth causing existing flows to break

https://github.com/grafana/grafana/pull/52160#issuecomment-1231945457

**What you expected to happen**:

oauth parameters that are not synced to remain editable in the UI (role and such)

**Comment by Wafa9** [comment]
HI @Jguer, I would like to work on this issue, I am looking for a good first issue so can I take this.

**Comment by JayEkin** [comment]
@Wafa9 

Do we have a PR for this issue as one of customers has reported the similar issue and requesting for an ETA on the fix.
Also, the mentioned PR - https://github.com/grafana/grafana/pull/52160 has been merged in 9.1.0 beta1.

> After upgrading to 9.1.2 from 9.0.1 Grafana Admin can't use the domain/admin/users/edit/:id page to add users to available orgs. It can still remove user from orgs, but can't add to orgs.

**Comment by Jguer** [comment]
Hey @Wafa9, we ended up implementing this as part of a more urgent fix for oauth. 

Here is what we came up with if you're curious about the resolution :slightly_smiling_face:. If you'd like to take a look at a different issue I can try and find an issue that's beginner friendly that does not have time constraints in the auth domain

**Comment by vsile** [comment]
@Jguer, great news! Thanks!
What release version will have this fix?

**Comment by sepich** [comment]
I've tried both v9.1.8 and v9.2.1 and the issue still persist.
We use Google auth, and `GF_AUTH_OAUTH_SKIP_ORG_ROLE_UPDATE_SYNC=true`
and there is no button to add user to Org in server admin Users section.
What I'm missing?

**Comment by gamab** [comment]
Seems like a miss on our side, thanks for pointing it out, we'll fix :slightly_smiling_face:

**Comment by dm3ch** [comment]
What about JWT?
https://github.com/grafana/grafana/issues/63601
