### ISSUE TITLE
Node Graph - node arc color bug

### ISSUE THREAD

**Issue by marwin1991** [grafana/grafana#54683]
**What happened**:
When there is one value of arc__** and set to 1.0 there is no color. 

**What you expected to happen**:
When changed to f.e. 0.99999 color is correct.

![grafana_bug](https://user-images.githubusercontent.com/25181517/188325641-45947e7c-a750-48e4-8094-8341bb15db20.gif)

**How to reproduce it (as minimally and precisely as possible)**:
I have really complicated query, but you can get it here:

https://github.com/logchange/hofund/blob/master/grafana-dashboards/hofund-node-graph.json

The most important part IMO is:
```
abs(sum by (id) (sum by (id) (sum without () (hofund_info) or (0 * sum_over_time(hofund_info[1w])))) - 1) * 0.999999
```

If you have `bash`, `docker` and `mvn` (maven) installed you can easily reproduce it:
1. Get https://github.com/logchange/hofund-example
2.  Run `./run.sh` (maybe first you will need `chmod +x ./run.sh`
3. Run `./run_tools.sh` (maybe first you will need `chmod +x ./run_tools.sh`
4. Go to http://localhost:3000/ login: admin password: foobar
5. Import dashboard from https://github.com/logchange/hofund/blob/master/grafana-dashboards/hofund-node-graph.json (change datasource id)

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest (9.1.2 3c131....)
- Data source type & version:
- OS Grafana is installed on: docker
- User OS & Browser: Brave based on Chromium
- Grafana plugins: Defined in repo above

**Comment by aocenas** [comment]
Hey @marwin1991 I think is an issue with the values. Don't really understand the query but I assume it can happen that the value is actually slightly above 1 which if you multiply by 0.9999 gets down to <1. If that happens it messes up the math computing the arc and the arc can be rendered mirrored out of the actual place of the node. You can check that here https://github.com/grafana/grafana/blob/d87cd6f26c82000f7dadaa47577eb139853df1da/public/app/plugins/datasource/testdata/testData/serviceMapResponse.ts#L127, this is some test data used with test data source and you can see there are values of 1 works ok. If you change something to 1.000001 for example you will see the rendering broken a bit.

We can probably cap the values to max 1, but I consider this to be an issue with the query at them moment.
