### ISSUE TITLE
Graphs look weird when using repeat for panels or rows

### ISSUE THREAD

**Issue by Bondza** [grafana/grafana#5468]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4
- What datasource are you using?
Influxdb 0.13
- What OS are you running grafana on?
Docker on Ubuntu 14.04.2 LTS
- What did you do?
Use repeat for rows and panels from tag values returned by Influxdb
- What was the expected result?
Graphs should look like they normally do, just more of them
- What happened instead?
Graphs render randomly, some graphs are overlaying others when repeating paneles. When repeating rows, the only thing visible for a graph is the legend.

This is what I get when I try to use repeat on a graph:
![Repeat Panel](https://cloud.githubusercontent.com/assets/1886115/16482642/f6c9767e-3eb0-11e6-8f2c-453a583a61bc.png)
![Panel Settings](https://cloud.githubusercontent.com/assets/1886115/16483546/27bb650e-3eb5-11e6-91a4-1ec00fc95afd.png)

And when I use repeat rows I get this:
![Repeat Row](https://cloud.githubusercontent.com/assets/1886115/16482702/53806008-3eb1-11e6-9fff-7a3e23c24a9b.png)
![Row Settings](https://cloud.githubusercontent.com/assets/1886115/16483564/3cb79586-3eb5-11e6-8e0e-c1885a4acf94.png)

My query:
![Metric Query](https://cloud.githubusercontent.com/assets/1886115/16483530/1574a7fc-3eb5-11e6-8111-6b0245ae5e01.png)

This is the raw [request](http://pastebin.com/5b5euZSj) and [response](http://pastebin.com/8nasB5Xw) 
for one of the variable values when I use repeat.

I was not using repeat for rows and graphs at the same time, I tried setting up repeat for graphs first and then rows.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by DEvil0000** [comment]
Have seen similar or maybe same bug.
Happens when you set **repeat** for a graph with **12 or more** repeats and you have not configured a **min span** value for the graph (in general).
Maybe also related to very few data points in the time frame for the graph.
Try setting min span to something.

**Comment by torkelo** [comment]
you need to set min span
