### ISSUE TITLE
New version available" wants

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#5470]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by bergquist** [comment]
@bobrik Was this issue created by mistake? It doesn't make any sense to me :)

**Comment by bobrik** [comment]
Not sure how this happened 😕  #5471.
