### ISSUE TITLE
"New version available" wants to downgrade

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#5471]
Grafana v3.1.0-beta1 (commit: v3.1.0-beta1). This doesn't look right:

![image](https://cloud.githubusercontent.com/assets/89186/16485035/82cc574c-3eb4-11e6-92ae-46ce39fab016.png)

**Comment by torkelo** [comment]
sorry, this was due to me not having updated https://github.com/grafana/grafana/blob/master/latest.json
