### ISSUE TITLE
Plugins icons aren't displayed for Grafana 3.0.4 in Win7

### ISSUE THREAD

**Issue by chaminator** [grafana/grafana#5472]
HI,

Kind of issue I faced for my grafana 3.0.4 win7 x64 installation.
I installed 2 plugins: zabbix and piechart. 
Plugins are available in the according Grafana web UI section, but their icons are absent.

Issue is reproducible both in Chrome (Version 51.0.2704.106 m (64-bit)) and FF (38.5.1)

Some screenshots to illustrate:
![image](https://cloud.githubusercontent.com/assets/10546044/16488016/ecca9ef2-3ed6-11e6-9c0e-3b005588d8d6.png)

and
![image](https://cloud.githubusercontent.com/assets/10546044/16488026/f8f88590-3ed6-11e6-9dcb-3e3730a75a7f.png)

So my question: is this a known issue or I did some configuration mistake?

Thanks,
Artyom

**Comment by daniellee** [comment]
Closing this issue, if this is still a problem then I can reopen the issue.
