### ISSUE TITLE
Series Selection in Time Series Panel clashes with "hide" overrides

### ISSUE THREAD

**Issue by ypnos** [grafana/grafana#54721]
**What happened**:

I have a time series panel with overrides to hide specific fields ("begin" and "end"). Use cases:

1. Hide only in legend to remove clutter
2. Hide completely but use for data links

When I click on a series, it hides all other series but the selected one - in theory. In practice, it shows all other series in the legend in gray, including the ones configured for the panel. The result:

![Grafana-series-select-overrides](https://user-images.githubusercontent.com/8481470/188480652-65f4f741-c563-4742-87e3-e15a99652d7b.gif)

**What you expected to happen**:

The feature to toggle display of a single series vs all series in the legend does only that, and not suddenly show series that were previously hidden.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add an override to hide a series by name
2. Select another series in the legend

**Environment**:
- Grafana version: 9.0.3

**Comment by mdvictor** [comment]
Hello @ypnos. This was fixed in v9.1 . Can you please update and check if the issue reproduces?

**Comment by mdvictor** [comment]
I just checked on v9.1.6. Issue no longer reproduces.
