### ISSUE TITLE
Unified alerting: bad input in the alert evaluation behavior throws a 'fatal' error

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana#54743]
**What happened**:
I changed the "Evaluate every" input from `20s` to `20n` and this instantly forwards me to a "An unexpected error happened" page.

**What you expected to happen**:

To just give me UI notification / validation on the field, rather than this 'fatal' exception page.

**How to reproduce it (as minimally and precisely as possible)**:

Go to a unified alert (or create one) and change the field `Evaluate every` into a non-valid input.

**Anything else we need to know?**:

![Kapture 2022-09-06 at 10 55 51](https://user-images.githubusercontent.com/5786097/188592745-13712d57-7745-4600-a821-faf4afc0ae73.gif)

**Environment**:
- Grafana version: v9.1.2 enterprise
- OS Grafana is installed on: K8s
- User OS & Browser: MacOS - Chrome

**Comment by caviliar** [comment]
I also have the same problem.

I can reproduce by:
- editing a current alert
- editing the text-box to have anything that would be invalid in it.

if i wanted to change it from `2m` to `10m` then it would instance error the page. i have to change it by removing the `m` first, then setting it to `10m`. pretty much can't transition the value by any means that would leave 1) just a letter in it, 2) accidentally having an invalid letter along with a number also breaks it.
