### ISSUE TITLE
Loki Explore Query Bug

### ISSUE THREAD

**Issue by tripitakav** [grafana/grafana#54740]
**What happened**:
I don't know why there are repeated strings when querying in Loki through keyboard input, but I can query normally by copying and pasting this query statement

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: loki
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome(105.0.5195.102)
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/73687556/188588407-d31186e6-be4a-4e08-91bf-c1f1542aed00.png)
![image](https://user-images.githubusercontent.com/73687556/188589005-87d56cda-0fd5-483b-8337-3736321609d0.png)

**Comment by StefanCenusa** [comment]
Indeed, this happens to us too. And I've noticed it happens since Chrome `105.0.5195.102`. On previous Chrome version `104.0.5112.101 (Official Build) (64-bit)` it worked. Also, on Safari `15.6.1 (17613.3.9.1.16)` it works.

**Comment by StefanCenusa** [comment]
Seems like a known [issue](https://github.com/grafana/grafana/issues/54535).

**Comment by tripitakav** [comment]
> 似乎是一个已知[问题](https://github.com/grafana/grafana/issues/54535)。

ok
