### ISSUE TITLE
[Feat Req]: Table panel, limit string length in by Column Style

### ISSUE THREAD

**Issue by 3IWOH** [grafana/grafana#5475]
- **I'm submitting a ...**
- [x] Feature request

I am using Grafana to display a list of application alerts/errors in a table. The specific details of the error string can vary in length. It would be great to be able to limit the display of a table value by x number of characters to keep the view consistent. I imagine this could be added to Column Styles.

Perhaps there could also be the ability to see the entire string via a tootip when hovering over a truncated value?

Ideally, there would be a way to click on the truncated value to drill down into a detail dashboard...I know this has already been suggested for the table panel.

**Comment by Mikanoshi** [comment]
Agreed, requests can be very long (when someone's fuzzing for example or you are making requests in grafana) and table widths glitch, horizontal scrolling appears and headers don't match columns.

![grafana](https://cloud.githubusercontent.com/assets/5113439/17137022/249778ca-5352-11e6-923e-3126f3f7d8be.jpg)

**Comment by iamash** [comment]
Yes that'd be great. Anything updated on this request?

**Comment by CantankerousBullMoose** [comment]
If this were implemented, I would like to see text wrap when it exceeds the specified column width for my usecase.  I could also see a need for setting a maximum row height and doing the tool-tip or drill down for text that is too long to show within a cell as the OP suggested.

**Comment by CSSassess** [comment]
I'm out of the office returning July 30th

Your mail has been received and I'll get to it upon my return. For anything
urgent please contact IT Operations in my absence.

Robert Klickermann
Systems Architect
Hamilton Police Service
(905) 546-4791

***This email has been scanned for malicious content ***

**Comment by hackeryard** [comment]
Hello, I face a problem that I use grafana v5.4.2, but the table palne doesn't support the limited length of row string. But I find this issue and also the changelog says this feature is included in v4.4. Is there anything I missed?

**Comment by benjdl** [comment]
Any update on this issue ? No word on the roadmap about it

**Comment by criskolkman** [comment]
So @torkelo is there any update on this?
I would like to shorten the output as well.

![image](https://user-images.githubusercontent.com/17678609/86252451-8699fc00-bbb3-11ea-87f8-2cb9ff9c67b3.png)

**Comment by torkelo** [comment]
This should not be needed in new table panel

**Comment by SincerelyUnique** [comment]
![image](https://user-images.githubusercontent.com/16249717/100960503-536be800-3518-11eb-98ef-e186b99556a9.png)
