### ISSUE TITLE
Azure Monitor: Custom Metric Namespaces not working (Grafana 9.1.3)

### ISSUE THREAD

**Issue by yggdrasil-tynor** [grafana/grafana#54757]
After the Grafana 9.0.0 and these changes https://github.com/grafana/grafana/pull/49029. It is not possible to find/chose custom Metric Namespaces.
We have a namespaces named "Yggdrasil ServiceBus Metrics", which we could find and chose before, but now it's not possible - not even when typing it in manually.

![image](https://user-images.githubusercontent.com/43808309/188612157-67fb1e49-d2cf-4dbe-ae9c-aa0409d11622.png)

Not able to find or query it:
![image](https://user-images.githubusercontent.com/43808309/188610692-c618925e-5eca-4c28-b149-23c30afbaaa4.png)

With Grafana < 9.0.0 it worked perfectly fine and we could chose it from the picker.

**Comment by JakubAdamczyk344** [comment]
@yggdrasil-tynor thanks for pointing this out! I was struggling with this one for days.
