### ISSUE TITLE
Rename `pluginmeta` coremodel

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#54752]
I picked `pluginmeta` as a name for the coremodel because it seemed more or less OK and i didn't know what else to call it.

Turns out, this collides with an existing term of art, "plugin meta," which is used to refer to some actual data about the state of an installed plugin that's communicated out on the frontend.

`pluginmeta` was never a particularly great name for the coremodel anyway, so that's what should change.

cc @wbrowne @ryantxu

**Comment by wbrowne** [comment]
`pluginjson`? 😄

**Comment by sdboyer** [comment]
i'd say that's good, except for the plausible near-future in which we allow `plugin.cue` or `plugin.json` 😬

**Comment by sdboyer** [comment]
What about `pluginspec`?

**Comment by wbrowne** [comment]
That's not terrible. Also, maybe `plugindef`?

**Comment by sdboyer** [comment]
That feels a bit better.

It's worth noting that, if/when we allow a plugin to provide either `plugin.cue` or `plugin.json`, we'll no longer be able to just say "the plugin.json file." We'll need a term to abstracts over the two possibilities - and that should probably align with this name we pick.

I don't know if there's already a term we use that sorta does this, but "the plugin definition file" seems reasonable to me. And, IMO, it aligns sufficiently obviously with `plugindef` to pass an intuitive smell test.

**Comment by ryantxu** [comment]
+1 for either `plugindef` or `pluginspec`

Now you get why I was so confused by "pluginmeta" :)

Why would we ever want a plugin.cue?  or is this in a world where the plugin model is pretty different than it is today?

**Comment by sdboyer** [comment]
@ryantxu a `plugin.cue` is the simplest, most direct path from the current architecture to allowing plugins to define custom types. I thought we'd discussed this several times? It's [here](https://docs.google.com/document/d/1du7nubkw7UBKaOblgXEIYhcUQVaHlCndJCBVzQ2eqPU/edit?disco=AAAAetZapSk), at least.

Plugins that don't want or need to define any custom types can continue using `plugin.json` - no muss, no fuss. For those that do, `plugin.cue` would be a drop-in replacement; they can write a lineage at some structured subpath, and (given entity API + storage) that's all we'd need to enregister a custom type.
