### ISSUE TITLE
Explore: new navigation improvements ideas

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#54751]
follow up on https://github.com/grafana/grafana/pull/54547

We can probably make use of the breadcrumb area and the top nav more efficiently like in  dashboards:
- we probably can remove the icon & Explore title from the left pane given it's present in the breadcrumb
![Screenshot 2022-08-31 at 20 52 11](https://user-images.githubusercontent.com/1170767/187770456-c066195a-7fa4-4436-884c-ea996b0aa189.png)

- the share button can be moved like in dashboards (we got feedback that the share button is not really discoverable, making it look exactly the same as dashboards would probably improve the situation)
![Screenshot 2022-08-31 at 20 57 32](https://user-images.githubusercontent.com/1170767/187770688-73ec8512-a5cf-4e14-9732-d7aa789ed4e5.png)

- the split button may be moved to the right section of the "breadcrumb" given it's a page level action (up to debate, it may also be confusing to have the split button up there and close buttons in each pane)
![Screenshot 2022-08-31 at 21 00 50](https://user-images.githubusercontent.com/1170767/187771219-98aed4e6-8fc1-4650-b99d-e3b98da93429.png)

- dashboards have the time picker in this area. i know we struggled a bit with the active state for the buttons, but maybe we can move the range picker up there when it's in in the "linked" state given - as per the previous point - it affects both panes.
![Screenshot 2022-08-31 at 21 01 38](https://user-images.githubusercontent.com/1170767/187771353-398c5bd0-383f-47e3-ac99-061a509cd4fe.png)
![Screenshot 2022-08-31 at 21 04 51](https://user-images.githubusercontent.com/1170767/187771882-2e575a5c-0c32-4405-bd9c-d42aa3d58799.png)

The new layout looks great btw, it'd be awesome if we could fix the padding and scrolling issue before merging 🚀

_Originally posted by @Elfo404 in https://github.com/grafana/grafana/issues/54547#issuecomment-1233370123_

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/54547 is not really how this is supposed to be used, Explore should use the Page component (in Canvas layout) but there is a lot more to do than just that

**Comment by ifrost** [comment]
Also there's an issue mentioned in https://github.com/grafana/grafana/pull/56381#issuecomment-1268473925

**Comment by gelicia** [comment]
This issue isn't well defined and we will define it in future work if need be.
