### ISSUE TITLE
[Granafa Build] I got some trouble while building grafana

### ISSUE THREAD

**Issue by summer0nguyen** [grafana/grafana#5476]
Hello,
I'm a Devops engineer work with Python, PHP ,... but not Go and NodeJS . 
However, I'm very excited in Grafana and making some custom modules , and yes, learn GO and NodeJS.

I follow the instruction here :http://docs.grafana.org/project/building_from_source/ 
But I got some error to start the grafana-server here : 

Start : 

[root@06f9017161a3 grafana]# ./bin/grafana-server 
CRIT[06-30|17:14:36] Failed to detect generated css or javascript files in static root (/go/src/github.com/grafana/grafana/public), have you executed default grunt task?%!(EXTRA []interface {}=[]) 

Build the Front-end Assets
[root@06f9017161a3 grafana]# grunt
Version 3.2.0-pre1
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/go/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/vendor'

Running "phantomjs" task
Warning: Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file (Error code: ENOENT). Use --force to continue.

Do you have any idea how to fix it. 
Thank you very much.

**Comment by torkelo** [comment]
did you run `npm install` ?

**Comment by summer0nguyen** [comment]
Hello,
Problem solved. 
The first time npm install run,  the node_modules is broken due to some network issues which make further unexpected error . 
Removing the node_modules and running npm install should fix the problem .

Btw: I also get a problem when I use GIT 1.7 , and it seems that my machine can not pull dependencies repositories , upgrading GIT to 2.x should fix it. 

Thank you.

**Comment by cyrilis** [comment]
Same here, `npm rebuild node-sass` and `npm rebuild phantomjs-prebuilt` resolved my problem.
