### ISSUE TITLE
Explore tests: ExplorePage.test.tsx - move Handles document title changes and Handles different URL datasource redirects test to public/app/features/explore/spec/browser.ts

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#54776]
* Move [Handles document title changes](https://github.com/grafana/grafana/blob/15756ecf86dd3f019cbf9f8356c825f2a76d2647/public/app/features/explore/Wrapper.test.tsx#L272) and [Handles different URL datasource redirects](https://github.com/grafana/grafana/blob/15756ecf86dd3f019cbf9f8356c825f2a76d2647/public/app/features/explore/Wrapper.test.tsx#L303) to a new file explore/spec/browser.ts
* Check if we can reuse existing helpers defined in [spec/helper](https://github.com/grafana/grafana/tree/15756ecf86dd3f019cbf9f8356c825f2a76d2647/public/app/features/explore/spec/helper)

**Comment by Elfo404** [comment]
Why do we want to move `Handles document title changes`? that logic is defined right alongside ExplorePage and used only there. the hook that updates the document title itself is not exported nor reused anywhere else. imho the should stay colocated.

**Comment by ifrost** [comment]
I think the idea was to test the full flow from URL (through redux) to setting the title but, yes just for the title it might not be needed, and testing it at the component level might be enough.
