### ISSUE TITLE
Explore tests: ExplorePage.test.tsx - move Handles open/close splits in UI and URL test to public/app/features/explore/spec/split.ts

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#54775]
* Move [Handles open/close splits in UI and URL](https://github.com/grafana/grafana/blob/15756ecf86dd3f019cbf9f8356c825f2a76d2647/public/app/features/explore/Wrapper.test.tsx#L157) to a new file explore/spec/split.ts
* Check if we can reuse existing helpers defined in [spec/helper](https://github.com/grafana/grafana/tree/15756ecf86dd3f019cbf9f8356c825f2a76d2647/public/app/features/explore/spec/helper)

**Comment by Elfo404** [comment]
this can probably be closed with https://github.com/grafana/grafana/pull/66286/files#diff-24330f830280a9ebd5d8d041209b41aaedf84f54e36a5a9fdfaaab9dfe375519 as it introduces/enhances tests for that scenario
