### ISSUE TITLE
root_url to custom path is not working with HaProxy

### ISSUE THREAD

**Issue by Lax77** [grafana/grafana#5478]
I am trying to use **HAProxy** to proxy to Grafana with end point '/grafana'. For that I happened to change  root_url in my ini file to '**root_url** = %(protocol)s://%(domain)s:%(http_port)s**/grafana/**'

In my HAProxy config I just have end point listed as '/grafana' to invoke the HOST:PORT of the grafana server.

Now when I invoke grafana with end point **http://[Proxy Host IP]/grafana**, I keep getting error
2016/07/01 00:23:10 [I] Completed 10.154.174.102 - **"GET /grafana HTTP/1.1" 404 Not Found** 19 bytes in 521us

Then I tried to directly invoke Grafana end point without proxy (i.e. as **http://[Grafana host IP]:[Grafana Port]/grafana** ) with  root_url still as %(protocol)s://%(domain)s:%(http_port)s/grafana/, even then I still get same 404 error. 

I do see there were people managed to get it work with nginx same way, but those solutions does not seems to work for me with HAProxy. Also why does direct Grafana end point using new root url fails? Was it only meant to be used along with Proxy and that too nginx only?

**Comment by bergquist** [comment]
try setting root_url to %(protocol)s://%(domain)s:%(http_port)s/grafana (no trailing /)

**Comment by Lax77** [comment]
I tried both with and without trailing slash and the behavior is same.

**Comment by torkelo** [comment]
then maybe it's your ha proxy config,

for nginx I use  this 

```
location /grafana/ {
 proxy_pass http://localhost:3000/;
}
```

set root_url in grafana.ini to the one you use in your browser

```
root_url = http://yourserver.com/grafana
```

**Comment by Lax77** [comment]
root_url = http://yourserver.com/grafana , in here yourserver.com should be pointing to proxy server?

In my case HaProxy and Grafana are running on different servers. Also I have multiple HAProxy servers, user could be coming in from any of the HA Proxy server.

**Comment by Lax77** [comment]
Also if I swtich root_url, can I reach that new root end point directly (without HA Proxy)? Because that also is failing for me with 404 on /grafana.

**Comment by torkelo** [comment]
Grafana should be hosted from a single domain / subpath  (as root_url is used for redirects, links in emails etc) 

You cannot put grafana under subpath (/grafana) and access grafana directly at the same time, you need to decide if you want to access grafana through the ha proxy under subpath or not.

**Comment by Lax77** [comment]
Ok.

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
