### ISSUE TITLE
State timeline: Value mapping does not work as expected

### ISSUE THREAD

**Issue by baur** [grafana/grafana#54815]
**What happened**:

Value mapping does not work as expected!

![image](https://user-images.githubusercontent.com/2898361/187817474-7e4b8439-8e8a-4cbc-aa2f-fd58299e94b8.png)

**How to reproduce it (as minimally and precisely as possible)**:

Try map values 

https://play.grafana.org/d/8jRyQ13Mz/1-new-features-in-v8-0?orgId=1&viewPanel=65

**Environment**:
- Grafana version: 9.1.3
- OS Grafana is installed on: Windows Server 10
- User OS & Browser: Chrome

**Comment by ivanahuckova** [comment]
This might be duplicate of https://github.com/grafana/grafana/issues/40661. I am not sure, passing to BI squad to evaluate.

**Comment by baur** [comment]
fixed
