### ISSUE TITLE
parse error at line 1, col 3: syntax error: unexpected IDENTIFIER, expecting = or =~ or !~ or !=

### ISSUE THREAD

**Issue by zhaods927** [grafana/grafana#54817]
使用Loki 

logbrowser 输入（输入及其不方便并且报错）

{app="shop-center-provider", namespace="fat"} |= `1`

报错  parse error at line 1, col 3: syntax error: unexpected IDENTIFIER, expecting = or =~ or !~ or !=

**Comment by austinborn** [comment]
+1 on this. I seemingly randomly can't delete certain characters from the input box (like `{` and `}`).

**Comment by winwill2012** [comment]
我也遇到同样的问题，之前还是好的，最近一周突然这样

**Comment by winwill2012** [comment]
把查询语句复制到本地编辑器，然后再粘贴上去就可以，直接键盘输入就是报解析错误

**Comment by winwill2012** [comment]
好像是chrome的问题，升级到最新版本的chrome有问题，老版本104就是好的

**Comment by MikeMichel** [comment]
Seeing the same issue on 9.1.1

**Comment by rukos-consult** [comment]
got the same on 9.1.1 when editing the Query.

**Comment by Kuzbekov** [comment]
It sends broken query in request to grafana backend. If you copy and then paste the same edited query it will be executed without errors. Very annoying issue :( I don't why understand why there are not so many reporters as it makes almost impossible to work with requests to Loki

**Comment by Kuzbekov** [comment]
I think it's related to [https://github.com/grafana/grafana/issues/54535](https://github.com/grafana/grafana/issues/54535)

**Comment by ivanahuckova** [comment]
>I think it's related to https://github.com/grafana/grafana/issues/54535

Yes, this is an issue with query editor. Please follow https://github.com/grafana/grafana/issues/54535 to see when it is resolved.

**Comment by zhaods927** [comment]
是和 https://github.com/grafana/grafana/issues/54535 同样的问题，新版 chrome 和  microsoft Edge 有问题，换成了 华为浏览器就好了。所以使用的话需要换下浏览器吗?这样不太友好吧？

**Comment by winwill2012** [comment]
@zhaods927 你直接升级grafana到9.1.3就好了

**Comment by PolkachuIntern** [comment]
9.1.3 does not fix it, but 9.1.4 fixes it.

**Comment by sungaohui** [comment]
chrome version 版本 105.0.5195.127, 9.1.3/4/5 都测试了一般，还是存在该问题

**Comment by xulun2468** [comment]
> 

我最近也是遇到这个问题，解决了吗？

**Comment by CzyerChen** [comment]
亲测，应该是chrome版本兼容性问题(粘贴进去报错，手动书写跳字)，safari语法正常丝滑查询
本人Chrome版本 115.0.5790.114（正式版本） (x86_64)，Safari版本13.1.3 (15609.4.1)

**Comment by 1Ckpwee** [comment]
使用 Chrome 老版本还是会出现语法问题，copy 到编辑器中会出现下列字符串：
![image](https://github.com/grafana/grafana/assets/51103782/8a417082-4491-4c43-8a1f-46de80aa5f6f)
看起来是字符编码问题。
解决办法：
- 换其他浏览器（Safari 以及 Edge 均可解决该问题）
- 升级 Chrome 版本（升级到最新 Version 116.0.5845.96 也可以解决该问题）
