### ISSUE TITLE
table panel with clickable rows

### ISSUE THREAD

**Issue by sunnos9** [grafana/grafana#5481]
- **I'm submitting a ...**
- [ ] Bug report
- [ x ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Looking for any suggestions on making the rows in a Table Panel 'clickable' and use it to drill down to a more detailed view (another dashboard using Template variables). Currently displaying a summary of several servers as rows in a Table Panel and we want to select an individual row (i.e a server) to drill down to a more detailed Dashboard. 

Thanks

Please include this information:
- What Grafana version are you using? 
  3.0.4
- What datasource are you using?
  Influx 0.13
- What OS are you running grafana on?
  CentOS 7
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by inselbuch** [comment]
and when you click on a row it should pass a selected column as a template variable!

**Comment by buinhansinh** [comment]
@inselbuch  Could you clarify  ? Is there any document mentioning this

**Comment by inselbuch** [comment]
when you click on a row on a table, it should be possible to open another dashboard and a template variable should be populated based on the row (or cell) that you clicked

**Comment by torkelo** [comment]
closing as this is basically the same as https://github.com/grafana/grafana/issues/3754
