### ISSUE TITLE
[Bug] "Unsaved Changes" prompt while playing a list 

### ISSUE THREAD

**Issue by kirillkovalenko** [grafana/grafana#5482]
**What Grafana version are you using?** 
Current: 3.0.4
Issue seen since: 3.0-beta
**What datasource are you using?** 
InfluxDB
**What OS are you running Grafana on?**
Server: Ubuntu 14.04, 
Client: Windows 7, Latest Chrome Browser
**What did you do?**
Play a playlist
**What was the expected result?**
Playlist goes without interruption
**What happened instead?**
"Unsaved Changes" prompt appears, UI hangs, have to restart the web browser.

After upgrade to 3.0 we've been observing an issue with dashboards being played in playlists.

We have a small and rather weak nettop PC where we run a playlist with about 5 dashboards. We start a play list and after some time there is a modal pop-up saying that some changes have been made to the dashboard and the playback stops. 
![untitled](https://cloud.githubusercontent.com/assets/3592194/16514011/685bb19a-3f69-11e6-859f-b357091a26de.png)

**Comment by torkelo** [comment]
Open and save the dashboard where this is happening, might have an old schema and opening the dashboard is causing a schema upgrade
