### ISSUE TITLE
Input on focus, adding the placeholder text to the input field 

### ISSUE THREAD

**Issue by vvvprabhakar** [grafana/grafana#54832]
**Environment**:
- Grafana version: v8.2.7
- Data source type & version: Any Datasource
- OS Grafana is installed on: mac OS Monterey
- User OS & Browser:mac OS Monterey & chrome version Version 105.0.5195.102 (Official Build) (arm64)

The above mentioned issue is not happening in chrome versions 95.x
<img width="1644" alt="Screenshot 2022-09-07 at 2 32 42 PM" src="https://user-images.githubusercontent.com/20414336/188838965-baa0edf9-658e-4b45-8a2e-95dd737e21b3.png">
<img width="1656" alt="Screenshot 2022-09-07 at 2 33 30 PM" src="https://user-images.githubusercontent.com/20414336/188838990-fe680feb-78e8-438c-ba68-171b4a528f83.png">

**Comment by ivanahuckova** [comment]
To fix your issue, we recommend to update to (at least) Grafana v8.3.0 where we use different query input library - monaco.

**Comment by ivanahuckova** [comment]
@grafana/user-essentials passing to you to evaluate, if we want to reopen this issue and possibly backport fix to v7.5.x.
