### ISSUE TITLE
Inclusion of W/m² in the list of measure units

### ISSUE THREAD

**Issue by dstreppa** [grafana/grafana#5483]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4
- What datasource are you using?
InfluxDB 0.12.1.
- What OS are you running grafana on?
Centos 6.7
- What did you do?
I created a graph containing data about a weather station with an irradiance sensor (https://en.wikipedia.org/wiki/Irradiance)
- What was the expected result?
A graph with W/m² as unit of measure. I think W/m² - and also Wh/m² - should stay in "energy" section of the "Axes" tab.
- What happened instead?
A graph with a custom unit.

**Comment by DEvil0000** [comment]
how about adding own unit configurations?
I feel like this would be the real feature ;)

**Comment by torkelo** [comment]
will close this in favor of https://github.com/grafana/grafana/issues/2968
