### ISSUE TITLE
Service Graph does not work if `span_name` contains regex-sensitive characters.

### ISSUE THREAD

**Issue by StianOvrevage** [grafana/grafana#54849]
**What happened**:
- Go to Explore.
- Select Tempo datasource.
- Select Query type Service Graph.
- Set filter to `namespace` = `abcdef`

Response:
```
Query error
bad_data: invalid parameter "query": 1:104: parse error: unknown escape sequence U+002F '/'
```

![image](https://user-images.githubusercontent.com/6630005/188886527-80c217b0-a997-44dc-98e6-2da6a40348c7.png)

**What you expected to happen**:

Service Graph displayed without errors.

**How to reproduce it (as minimally and precisely as possible)**:

- Enable exporting metrics to Prometheus from traces
- Create a span with regex-sensitive characters in the span name, for example `some-server.abcdef.svc.cluster.local:9090^\/config.grpc.?(.*)`

Why the weird span name? I have no idea. These traces are generated by [Spring Cloud Sleuth](https://spring.io/projects/spring-cloud-sleuth) and I'm assuming there's some automatic trace gathering and naming in there.

**Anything else we need to know?**:

It seems Grafana does a couple of queries to Prometheus to discover all of the span names.

The second last response to Grafana contains

```
{span_name=\"some-server.abcdef.svc.cluster.local:9090^\\\\/config.grpc.?(.*)\"}
```

That leads to a request with queries like
```
{"refId":"topk(5, sum(rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",namespace=\"abcdef\",span_name=~\"some-server.abcdef.svc.cluster.local:9090^\\/config.grpc.?(.*)|some-server.abcdef.svc.cluster.local:9090/*|some-server.abcdef.svc.cluster.local:8080^\\/config$|^\\/config\\/.*|some-server.abcdef.svc.cluster.local:8080/*\"}[$__range])) by (span_name))"
```

Which leads me to think that Grafana tries to be clever and use regex query (`=~`) to retrieve X time-series in one round-trip. (I.e. filter span_name to be a|b|c|d and then sum by span_name to get all the individual timeseries.

But this fails since Grafana doesn't process and escape the `span_name` before passing it back to Prometheus with the regex-operator.

**Environment**:
- Grafana version: v9.1.2
- Data source type & version: Tempo 1.5.0 and Prometheus 2.35.0

**Comment by hannahchan** [comment]
Hi,

I'm experiencing the same issue mentioned here however I'm wondering if is just easier to replace the double quotes `"` in the PromQL for backticks `` ` `` like what we did in this issue; https://github.com/grafana/grafana/issues/59251. That way no further escaping is required.

See the following PromQL documentation for more information.

https://prometheus.io/docs/prometheus/latest/querying/basics/#string-literals

**Comment by aocenas** [comment]
@hannahchan I don't think that would solve this. We want to create a valid regext as `<span_name1>|<span_name2>|<span_name3>` but we don't want span_name to be treated as regex what ever the content. So we need to escape regex special chars in the span_names.
