### ISSUE TITLE
Grafana 3.1.0-beta1 escapes spaces in elasticsearch templating

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#5485]
Grafana 3.1.0-beta1.

![image](https://cloud.githubusercontent.com/assets/89186/16516385/b1ec6be6-3f6f-11e6-9931-388fa597c8b9.png)

> Template variables could not be initialized: Cannot read property '1' of undefined

Generated query:

```json
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"metric:kafka.topics.offsets\ AND\ tags.topic:requests"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1467351395556","lte":"1467362195556","format":"epoch_millis"}}}]}}}},"aggs":{"1":{"terms":{"field":"tags.cluster","size":0,"order":{"_term":"asc"}}}}}
```

This is invalid JSON:

```
{
  "responses": [
    {
      "error": {
        "root_cause": [
          {
            "type": "json_parse_exception",
            "reason": "json_parse_exception: Unrecognized character escape ' ' (code 32)\n at [Source: [B@265dd154; line: 1, column: 119]"
          }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
          {
            "shard": 0,
            "index": "metrics-2016.07.01",
            "node": "ugHskf0yTVq5vIrpXohDNw",
            "reason": {
              "type": "query_parsing_exception",
              "reason": "Failed to parse",
              "index": "metrics-2016.07.01",
              "caused_by": {
                "type": "json_parse_exception",
                "reason": "json_parse_exception: Unrecognized character escape ' ' (code 32)\n at [Source: [B@265dd154; line: 1, column: 119]"
              }
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by bobrik** [comment]
Looks like 38790e2c4b69c76c42af0fa0c10d86b20d9bb4c7 is to blame, @torkelo. Why do we need to escape space characters?

**Comment by torkelo** [comment]
@bobrik because you need to do that for lucene,

**Comment by torkelo** [comment]
https://dismantledtech.wordpress.com/2011/05/15/handling-spaces-in-lucene-wild-card-searches/

**Comment by bobrik** [comment]
You need to escape things in templating variables before inserting them, but not in the query itself.

**Comment by torkelo** [comment]
@bobrik not sure what you mean escape before inserting, makes no sense, need to escape the json string properly after interpolation, that was the issue :) 

this problem is due to an interpolation step happening after json to string (was done this way before to support raw user edited json)

**Comment by bobrik** [comment]
This didn't make it in 3.1.0.
