### ISSUE TITLE
Some graphs are just empty

### ISSUE THREAD

**Issue by ton31337** [grafana/grafana#5486]
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? Prometheus
- What OS are you running grafana on? CentOS
- What did you do? Metrics -> Query (`mysql_global_status_connections`)
- What happened instead? No data (there was data two days before, nothing was changed)

I can query directly Prometheus and it returns data correctly. 

Some screenshots:
![screen shot 2016-07-01 at 11 26 33](https://cloud.githubusercontent.com/assets/3352707/16516429/b55c2792-3f80-11e6-8b98-5c527d3361e5.png)
![screen shot 2016-07-01 at 11 40 31](https://cloud.githubusercontent.com/assets/3352707/16516430/b55c78e6-3f80-11e6-9faa-fa9654280a01.png)

Some warning in developers console:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

**Comment by torkelo** [comment]
Strange, no one else has reported similar issues, and I am unable to replicate it :( 

Can you open chrome dev tool and check network tab and inspect the request and response from Prometheus?

**Comment by torkelo** [comment]
Maybe your mysql node exporter is not working correctly?

**Comment by ton31337** [comment]
exporter is working properly, these metrics are already in prometheus..

**Comment by ton31337** [comment]
will check with dev tools later

**Comment by zeddmalam** [comment]
Hello, i have the same issue. I'm using free hosted grafana. From time to time metrics are not loading.

Query inspector says:

```
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1531596420253"
to:"1539372420253"
queries:Array[6]
0:Object
refId:"A"
intervalMs:7200000
maxDataPoints:960
datasourceId:4
rawSql:"SELECT UNIX_TIMESTAMP(time) as time, value, 'Unrealized Total' as metric FROM account WHERE $__timeFilter(time) and metric='account.total.profitLoss.unrealized' ORDER BY time ASC "
format:"time_series"
1:Object
2:Object
3:Object
4:Object
5:Object
response:Object
results:Object
A:Object
refId:"A"
meta:Object
series:null
tables:null
B:Object
C:Object
D:Object
E:Object
F:Object
```

I've checked mysql connection and query. everything is fine.

* What Grafana version are you using?  Grafana v5.3.0 (commit: c613a31)
* What datasource are you using? mysql
* What OS are you running grafana on? hosted grafana 
* What did you do? open dashboard
* What happened instead? No data

if you have chance to check the [dashboard](https://zedd.grafana.net/d/Vta2U9Dik/forex?orgId=1)

[shared dashboard](https://snapshot.raintank.io/dashboard/snapshot/gI8M5OQio6JZkD9JQHRDvwI5zTuGR7h7?orgId=2)

**Comment by zeddmalam** [comment]
my expectation on this is that probably there was an update of hosted grafana and after that queries stoped working:

example:

```
SELECT
  UNIX_TIMESTAMP(time) as time,
  value - 2300 - 229.94 as value,
  'Profit And Loss' as metric
FROM account
WHERE $__timeFilter(time) and metric='account.total.refined.profitLoss'
ORDER BY time DESC
Limit 1
```

I think that `$__timeFilter(time)` is not functional part

db sample data:

```
# time, value, metric
1539216000, -21.41, 'Weekly Income'
```

**Comment by zeddmalam** [comment]
with grafana:5.2.5 everything works fine

**Comment by marefr** [comment]
@zeddmalam #13621

**Comment by zeddmalam** [comment]
Please correct me if i'm wrong, but i don't think that it's a timezone issue. Macros replacement doesn't works for me. If you can check query inspector dump in my comment:

```
rawSql:"SELECT UNIX_TIMESTAMP(time) as time, value, 'Unrealized Total' as metric
 FROM account 
WHERE $__timeFilter(time) and metric='account.total.profitLoss.unrealized' 
ORDER BY time ASC "
```
`$__timeFilter(time)` has not been replaced with interval

**Comment by marefr** [comment]
@zeddmalam works as expected for me on v5.3.0:

![image](https://user-images.githubusercontent.com/1668778/46964618-d4ea2d00-d0a8-11e8-84e1-a8cb1cc6ff0f.png)

Please try and clear any cache in your browser. Open chrome dev tools and and right click the refresh button and do a "Empty cache and hard reload". Does that help?

![image](https://user-images.githubusercontent.com/1668778/46964732-24305d80-d0a9-11e8-8986-aeb992a917cd.png)

You've not described same problem as original author because he uses Prometheus. Please open a new  issue if you still have this problem.

**Comment by zeddmalam** [comment]
Oh, come on! 

I tried in incognito browser session. nothing works for me.

Consider this as issue report. This is your product and it's up to you if you want to make it better. So if you want, please create a new issue. For me it works with prev grafana version but not with the latest one.

And title of issue `Some graphs are just empty` perfectly describes my issue. So for me this is the same problem.

Have a nice day!

**Comment by marefr** [comment]
@zeddmalam I checked out your hosted Grafana instance now. And I would say it works as expected. The $__timeFilter are being replaced on the server side. When using the query inspector you should look at each response object -> meta -> sql for the actual sql query that was executed.
