### ISSUE TITLE
Broken result when group by special character

### ISSUE THREAD

**Issue by nhanloukiala** [grafana/grafana#5487]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- Version :  3.0.4
- Elasticsearch : 2.3

- I am trying to create a graph which executes GROUP COUNT on a field which includes these values:
["in-line", "in-media", "in-scroll", "in-screen"]

- But the group results on the graph are:
["in", "line", "media", "scroll", "screen"]

Apparently all the "-" characters are tokenized on Grafana side. Try to perform the query manually in Elasticsearch and the result were correct.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
This is related how Elasticsearch group's values, and to fix this you have to change your ES index (disable analyzing on the field)
