### ISSUE TITLE
Can't see the detail when there are too many unique metrics

### ISSUE THREAD

**Issue by chinglinwen** [grafana/grafana#5488]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
grafana-3.1.0-1466666977beta1.x86_64

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Redhat 6.4 similar 
Linux test 2.6.32-358.el6.x86_64 #1 SMP Tue May 21 09:27:32 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

- What did you do?
Open dashboard,  can't see the detail

- What was the expected result?
Scroll down, etc, too see all results, or just the result of where mouse indicate

eg. Prometheus do show the detail from popup window
![prometheus_graph_example](https://cloud.githubusercontent.com/assets/16344129/16518583/34d541d6-3fb6-11e6-937a-06ec28aa3eb6.png)

- What happened instead?

The popup windows can't see all result or the result that I want ( specific result )
The windows is limit to the size ( even whole screen is not be able to show  them all )

note: Prometheus graph just show the individual result

I think there are two problems

1. The pop up windows position ( it near the mouse, it should focus to show the contents)
2. If too many result to show(by pop up) , how about make it can scroll up and down( or some other better way that I don't know)

![grafana_hardtosee](https://cloud.githubusercontent.com/assets/16344129/16518397/1e031fa6-3fb5-11e6-9f6e-7f1156d83e5a.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

http://192.168.100.94:3000/dashboard/db/tqmp

Request URL:http://192.168.100.94:3000/api/datasources/proxy/1/api/v1/query_range?query=tqmp_receive&start=1467363569&end=1467367169&step=10

Request URL:http://192.168.100.94:3000/api/datasources/proxy/1/api/v1/query_range?query=tqmp_send&start=1467363569&end=1467367169&step=10

Request URL:http://192.168.100.94:3000/api/datasources/proxy/1/api/v1/query_range?query=tqmp_store&start=1467363569&end=1467367169&step=10

**Comment by torkelo** [comment]
if you want individual result on hover you can configure that in display tab, hover info, change from All Series to Single Series

**Comment by chinglinwen** [comment]
Thanks, I'll try it later ( when I at my workstation)

**Comment by chinglinwen** [comment]
I configured it to Single Series, It is what I looking for. Thank you!
