### ISSUE TITLE
InfluxDB 0.13 error on autocompletion. Integer tags must be quoted (again!).

### ISSUE THREAD

**Issue by aperdices** [grafana/grafana#5489]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  Grafana v3.1.0-beta1
- What datasource are you using?
  InfluxDB 0.13.0
- What OS are you running grafana on?
  Debian Linux Jessie 64 bits.
- What did you do?
  I'm trying to create a query where a tag value is an integer.
- What was the expected result?
  Query editor must continue offering new tags to filter.
- What happened instead?
  Not showing new tags to filter.

Seems that now InfluxDB 0.13 needs the integer tag value to be quoted (again!).

Grafana launch this query to get autocompletion data:
`SHOW TAG KEYS FROM "SensorInfo" WHERE "SensorId" = 208`

But backend responds:
`ERR: right side of '=' must be a tag value string`

Quoting the integer value works fine:
`SHOW TAG KEYS FROM "SensorInfo" WHERE "SensorId" = '208';`

Seems that tags are always strings and values must be single quoted when querying. Maybe the #4163 was not a Grafana bug, but an InfluxDB bug. From InfluxDB 0.13 Docs:

> Tag values are strings and they store metadata. Tag values are indexed so queries on tag values are performant.

**Comment by torkelo** [comment]
I don't know what to do here, because the same syntax is used for both value filtering and tag filtering, and value filter can be integer (and should not be quoted).

**Comment by aperdices** [comment]
Ok. I see that I'm mixing things... ;) Tag filtering must be quoted, but value filtering not. I see that involved files in InfluxDB query generation are
`public/app/plugins/datasource/influxdb/influx_query.ts`
and 
`public/app/plugins/datasource/influxdb/query_builder.js`.

There's no way to identify if filtering condition comes from value or tag?

I'll try to modifiy this files by myself... :)

**Comment by oopschen** [comment]
I encounter the same issue on InfluxDB 1.0 and Grafana lastest docker.
May it be possible quote tag value when the condition is type tag? I see requests for filter conditon, e.g. "Show tags ....". It should be possible to distinguish tag and field values.

**Comment by daniellee** [comment]
Seems to work now. Can re-open if this is still an issue for anyone.
