### ISSUE TITLE
Explore tests: Refreshing Explore

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#54894]
Add coverage for: https://github.com/grafana/grafana/blob/v9.1.1/public/app/features/explore/state/explorePane.ts#L196

Test scenario:

```
WHEN a query is run
AND the user changes the query
THEN the URL is updated with new query state
```

**Comment by Elfo404** [comment]
after some refactoring was done and `useStateSync` was introduced, tests should be added to public/app/features/explore/hooks/useStateSync/index.test.tsx instead

**Comment by ifrost** [comment]
This is already covered
