### ISSUE TITLE
Possibility to export a graph

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#549]
Hello

I think it would be very useful to have features like "copy link location" with right click on a graph (or some other sharing facilities)

When you see an incident or something noticeable on a graph, you surely want to isolate the graph and quickly share it with some other person (dev, it ...) without the full dashboard

Regards
Jeremy

**Comment by bergquist** [comment]
@nemenemsrouge you can share a panel as well. Click on the panel title -> share and use the url in the popup.
