### ISSUE TITLE
enable the Grafana JS agent in Alerting

### ISSUE THREAD

**Issue by jtheory** [grafana/grafana#54904]
Enables capturing client-side errors and basic telemetry, forwards to the Grafana Agent: https://grafana.com/docs/agent/latest/

Some open questions:
* ...is this actually already capturing errors? Domas suggested it is in core OSS (see Slack link below); if so let's see what's next
* can/should we disable this by default in config? What's the experience for users in an OSS or enterprise environment? Is it collecting data that'll be ignored / discarded, or could it cause errors?
* what options should we enable as a starting point?

References
* Incident merged in the agent here: https://github.com/grafana/incident/pull/1486
* Intro to what the JS agent does here in (private) Slack, in a good channel to ask more questions: https://raintank-corp.slack.com/archives/C01T8C5CNTE/p1658919421600889?thread_ts=1658918722.525349&cid=C01T8C5CNTE

**Comment by jtheory** [comment]
Tracked in (private) epic: https://github.com/grafana/gops-frontend-squad/issues/1

**Comment by VikaCep** [comment]
Another reference that seems relevant:  https://github.com/grafana/grafana/pull/50801 - _Adding [Grafana Javascript Agent](https://github.com/grafana/grafana-javascript-agent) Integration to battle-test it on Hosted Grafana_.

After enabling it in the `conf/custom.ini` configuration I was able to see exceptions being reported to the `custom_endpoint` set in that config file:
![image](https://user-images.githubusercontent.com/6271380/189741868-f7327ced-09d1-4aa1-870e-ff57f5cd6a00.png)

**Comment by VikaCep** [comment]
We can see an existing dashboard with measurements (such us first paint, load time, errors) related to hosted grafana here:

https://ops.grafana.net/d/rR3OAueGz/grafana-frontend?orgId=1

![image](https://user-images.githubusercontent.com/6271380/192060294-abe56f88-c550-4644-9990-37f9ff17b9f4.png)

**Comment by VikaCep** [comment]
I created a dashboard in ops where I'm displaying web vitals and errors information that is specific to Alerting (by matching `alerting` in the `page_url`): https://ops.grafana.net/d/tThxRZ4Vk/grafana-frontend-alerting?orgId=1

We can go adding more useful panels as we continue tracking user activity.

![image](https://user-images.githubusercontent.com/6271380/192860955-db1b1b17-56cc-42b7-ba44-2b88eb7d601f.png)

**Comment by jtheory** [comment]
This is great -- you've fixed up the Grafana defaults, set up basic tracking for Alerting + some selected important events, and set up the initial dashboard. We'll iterate in other issues.
