### ISSUE TITLE
High CPU usage at moderate request load

### ISSUE THREAD

**Issue by jphx** [grafana/grafana#54918]
My organization runs Grafana under Kubernetes, controlled by the Grafana Operator.  When we migrated from Grafana v8.4.7 to v9.1.3, we saw the average CPU usage of the Grafana pod change from about 0.5 CPUs to about 1.2 CPUs, even when not being used by any users.  One more piece of information:  For my testing, I've set `execute_alerts` under `unified_alerting` to `false`, so I don't think the background activity has anything to do with evaluating alerts.

It turns out the Grafana Operator makes about 25 HTTP requests per second to Grafana, mostly using the dashboard API to manage dashboards.  The Grafana CPU usage is for handing these HTTP requests, _which use basic authentication_.

The change in CPU usage seems to be due to the Grafana 9 RBAC changes.  It is now a lot more expensive to process basic-authentication requests (any maybe other kinds too).

I ran Grafana v9.1.3 with the `-profile` option and captured a 30-second CPU usage profile.  I attach the raw profile, which can be viewed in a web browser with the command:

```bash
go tool pprof -http :8000 bin/grafana-server /path/to/pprof.grafana-server.samples.cpu.001.pb.gz
```

[pprof.grafana-server.samples.cpu.001.pb.gz](https://github.com/grafana/grafana/files/9527533/pprof.grafana-server.samples.cpu.001.pb.gz)

I'm not expert at looking at CPU profiles, but the "flame graph" that you can select from the View menu is quite informative.  The major CPU user appears to be the path that uses `util.EncodePassword` as part of checking the basic auth password.  It uses 36% of the total CPU in the crypto functions that it employs.

Could some caching be added to make this more efficient?  The Grafana Operator is using the same userid and password over and over, so perhaps the last few encoded passwords could be cached.

Another high CPU usage path is a call stack that uses `accesscontrol.LoadPermissionsMiddleware.func1`.  But I think perhaps PR #53279 already addressed this CPU usage.

Any improvement that could be made to the Grafana CPU usage would be appreciated.

**Comment by mildwonkey** [comment]
Hi @jphx! Thanks for reporting this unexpected behavior. I learned about profiling Grafana (I'm pretty new) thanks to you 😁 

The root issue appears to be in the Grafana Operator itself, which isn't maintained by Grafana Labs. The maintainers of the Grafana Operator recently [reached out to us](https://grafana.slack.com/archives/CBA3NSALE/p1661257447614359) in the Grafana Community Slack (Grafana community FAQ [here](https://community.grafana.com/faq)) about reducing the operator's calls to the Grafana Dashboards API:

> I'm the maintainer of the grafana-operator and we are currently working on a new major release.
One of the issues that we are trying to solve is to minimize the number of API calls that we do to kubernetes and grafana API.
One thing we are trying to solve is to make sure that if you create a grafana dasthboard and then update in the UI the operator should revert those changes to match the CR (gitops ftw).
Would it be possible/interesting to add a webhook feature to trigger if a dashboard or datasource gets updated?
This way we could send a webhook to the operator and tell it to reconcile the dashboard CR again.

We'd love to help the Grafana operator work more efficiently, but it may take awhile to prioritize that work. It doesn't look like there's a bug fix, though I will tag in the @grafana/grafana-authnz-team in case they want to double check my logic.

**Comment by jphx** [comment]
I agree that the Grafana Operator could use some changes, and in fact I have used an operator option to reduce the number of calls it makes to Grafana to mitigate this symptom.  However, the profiling shows that Grafana is still spending 36% of all CPU time in one function (and those that it calls) when called at a moderate request rate.  That seems excessive to me.

**Comment by Jguer** [comment]
@kalleep I think you'd have a good input on this

**Comment by kalleep** [comment]
Hey! Thanks for the report. We have done several things to improve loading permissions, the one you mentioned https://github.com/grafana/grafana/pull/53279 and most recently adding cache support for permissions https://github.com/grafana/grafana/pull/55098.

Adding caching support for basic auth is something I think we should look into

**Comment by eleijonmarck** [comment]
@jphx adding caching for basic authentication would increase security holes.

Using basic auth should be used in spare and we recommend using a service account with a service account token to authenticate.
https://grafana.com/docs/grafana/latest/administration/service-accounts/#add-a-token-to-a-service-account-in-grafana
