### ISSUE TITLE
Nav: Changing from Org Admin to Viewer, the configuration nav tree shows invalid options

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#54926]
**What happened**:

https://user-images.githubusercontent.com/1173299/189174436-d5a39887-9357-4d1d-905b-72225ca8f283.mov

The configuration nav tree when Admin:
- Recorded queries
- Service accounts
- API keys
- Preferences
- Plugins
- Teams
- Users
- Correlations
- Data sources

The configuration nav tree when switched to Viewer and reloading:
- Recorded queries
- ~Service accounts~
- API keys
- Preferences
- ~Plugins~
- Teams
- Users
- Correlations
- Data sources

The configuration nav tree when logged out and back in again:
- Correlations

**What you expected to happen**:
A viewer only ever sees the correct nav tree for configuration - which is maybe no configuration nav at all?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by wbrowne** [comment]
Copying comment from other issue as it's more relevant here: https://github.com/grafana/grafana/issues/54927?notification_referrer_id=NT_kwDOABHnM7I0MzYxNDI4NDIyOjExNzMyOTk#issuecomment-1241172914

@Elfo404 I just realized I for one commented on the wrong issue and also didn't even share the right video that highlights the error🤦 



https://user-images.githubusercontent.com/1173299/189332457-91404e34-1276-4234-aa98-c7d48330c8b3.mov

**Comment by Elfo404** [comment]
i can't really reproduce the issue with the correlations page 🤔 

refreshing after changing role:
https://user-images.githubusercontent.com/1170767/189345928-520250fa-c5f4-4fc2-a9b8-ab0b6e2f9cad.mov

no refreshing after changing role:
https://user-images.githubusercontent.com/1170767/189346399-f78d237a-9c3b-49d6-bf25-6bc0bc07fbfc.mov
