### ISSUE TITLE
Graphite function asPercent parameter converted to string

### ISSUE THREAD

**Issue by rubalo** [grafana/grafana#54924]
**What happened**:

When using the asPercent graphite function in the query editor, the query fails : 
![image](https://user-images.githubusercontent.com/8589466/189170434-87ff3c87-c0d3-405b-a513-da0da05a66b5.png)

It is because the second parameter is escaped as a string : 
![image](https://user-images.githubusercontent.com/8589466/189170647-c6ee9c55-5c06-4c26-9d52-2c227874b752.png)

**What you expected to happen**:

I would expect to have the second parameter used as it is in the query. The result would be 
asPercent(#A, #B)
instead of 
asPercent(#A, '#B')

**How to reproduce it **:

I just created a free trial account on grafana cloud and was able to reproduce the issue.
Using 
Query A : constantLine(100)
Query B : constantLine(100)
Query C : #A then using the function dropdown menu asPercent(#B)

The weird thing is that when using diffseries, it behaves as expected

Cheers ! 

**Environment**:
- Grafana version: Grafana Cloud 9.1.3
- Data source type : Grafana Cloud Graphite 
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Linux, Chrome & Firefox
- Grafana plugins: None
- Others:

**Comment by bohandley** [comment]
I will devote half a day to looking at this by this Thursday. Thank you @rubalo!

**Comment by bohandley** [comment]
@rubalo Sorry for the delay! This was a little confusing as you mentioned, diffSeries worked perfectly, but asPercent did not with a series-ref like '#B', and as you said, asPercent escaped that as a string.

We get the functions list differently for different Graphite versions and we handle the parameters of those functions differently, which resulted in the bug with the asPercent function

Here's where we differentiate the  versions and get those functions
https://github.com/grafana/grafana/blob/f3f9a818c2ab4abaf7a6c952d903e5b9b550c934/public/app/plugins/datasource/graphite/datasource.ts#L822-L826

For Graphite < v.9 we call the graphite endpoint for the functions list. For asPercent, we were getting this function def with params of total and nodes, with types string and type node_or_tag. 

```
{
    "name": "asPercent",
    ...
    "category": "Combine",
    "params": [
        {
            "name": "total",
            "type": "string",
            "optional": true,
            "multiple": false
        },
        {
            "name": "nodes",
            "type": "node_or_tag",
            "optional": true,
            "multiple": true,
            "options": [...]
         }, ...
```

For Graphite > v.9 we implement an updated list. 
https://github.com/grafana/grafana/blob/f3f9a818c2ab4abaf7a6c952d903e5b9b550c934/public/app/plugins/datasource/graphite/gfunc.ts#L986-L988

From this list, the params are labeled differently, 
```
{
  name: 'asPercent',
  params: [{ name: 'other', type: 'value_or_series', optional: true, multiple: true }],
  defaultParams: ['#A'],
  category: 'Combine',
}
```
and thus we handle them different and don't escape them as strings.
https://github.com/grafana/grafana/blob/f3f9a818c2ab4abaf7a6c952d903e5b9b550c934/public/app/plugins/datasource/graphite/gfunc.ts#L1030-L1033

My thoughts are that we can fix this by assuming the asPercent function params as more than likely having a series-ref and never escaping the strings. I'll have a fix for this soon, thank you for your patience!

**Comment by rubalo** [comment]
Thank you very much !
