### ISSUE TITLE
Bar Gauge Panel Graph (vertical orientation) flips direction with data links

### ISSUE THREAD

**Issue by curiousbaker** [grafana/grafana#54936]
**What happened**: Bar gauge panel graph with vertical orientation flips in opposite direction when adding data link

**What you expected to happen**: Graph orientation in bar gauge panel should be independent of adding data links.

**How to reproduce it (as minimally and precisely as possible)**:
Bar Gauge Panel in Edit Mode (vertical orientation, without data link)
![image](https://user-images.githubusercontent.com/89766980/189265934-4f32d241-c37b-4233-9b02-a11a8d3f7529.png)

Bar Gauge Panel in Edit Mode (vertical orientation, with data link)
![image](https://user-images.githubusercontent.com/89766980/189265880-77d3ff63-5748-459b-9b4b-904ff702a4b1.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: PostgreSQL & 12
- OS Grafana is installed on: Windows 11
- User OS & Browser: Windows 11 & Firefox 104
- Grafana plugins: Bar Gauge Panel

**Comment by ivanahuckova** [comment]
Thank you for creating the issue. I was able to reproduce it as well.
