### ISSUE TITLE
plot difference area for "inconsistent number of points"

### ISSUE THREAD

**Issue by mar-v-in** [grafana/grafana#5493]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? Prometheus
- What OS are you running grafana on? Linux
- What did you do?
Two prometheus queries: `min_over_time(x[1h])` and `max_over_time(x[1h])<100`. Notice the upper limit applied to max query causes some datapoints to be excluded. I now want to show a difference area for both queries.
- What was the expected result?
A valid difference area with either "null" displayed for the missing datapoint or (as nullPointMode was set to connected) the difference to the value the max line displays at that point.
- What happened instead?
The difference area is not displayed at all. The js console prints "Refusing to graph inconsistent number of points". 

Example with real data: https://snapshot.raintank.io/dashboard/snapshot/NV04vAP7jvgzkJmUVbVv332Y7RMY7wnH?panelId=3&fullscreen there should be a difference area between rx_max (invisible, but you can see the points on hover) and rx_avg. At the point with high values in the middle, there is no actual value for rx_max, as the restriction removed the data.

**Comment by torkelo** [comment]
This is a problem with Prometheus in that it does not return null values for missing data points, so when you filter out values there is only a gap. So best solved in Prometheus I think

**Comment by mtanda** [comment]
Prometheus itself doesn't return null values for missing data points.
But Prometheus datasource plugin fill null to the gaps.
So, the graph plot should work, I think.

I check snapshot data, and all datapoints length is same (no problem!), but data length is differ (this difference cause the inconsistent number error).
Maybe, you change "Null value" options to "null" will fix the issue. The option is exists in Display tab.

![prometheus_null](https://cloud.githubusercontent.com/assets/224552/16545614/37fc85c0-416b-11e6-853c-d1a3d149a5f4.png)
