### ISSUE TITLE
Add controls to `Segment` story

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#54957]
Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props in a story.

**Comment by timagixe** [comment]
Hi, please assign this one to me. Thanks!

**Comment by timagixe** [comment]
Hi @JoaoSilvaGrafana, as far as I see, there are three stories for Segment: `SegmentSync`, `SegmentAsync`, `SegmentInput`.

Should we add controlled version of a story for each one or we simply need to create one controlled version of a story?

**Comment by JoaoSilvaGrafana** [comment]
Hey @timagixe maybe lets keep them the three separate stories for now, even if they are very similar? If that starts seeming very convoluted while you're developing it we can rethink it. Does that sound ok?

PS: Fantastic job in all of these tasks, we really appreciate it! 🚀

**Comment by timagixe** [comment]
Got you, that's why I asked, since they are pretty much the same 🙂 Most likely I will finish this one tomorrow. Thank you for a quick response.
