### ISSUE TITLE
Geomap: Measuring tools selector in Map controls not visible

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#54953]
The measuring tool selector/button in the Map controls is not visible.  Is this an error or do I need to activate some special settings.   The problem is on both OSS and Enterrprise installations

![image](https://user-images.githubusercontent.com/8969659/189317638-1d8d18f2-6ce6-4d04-8f19-12a64d56de9d.png)

**Measuring tools map control selector not visible**:

**I would expect the selector for measuring tools to be visible and selectable but it's not visible after upgrade to 9.1.1 OSS and enterprise**:

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: Influxdb 1.8
- OS Grafana is installed on: Windows server 
- User OS & Browser: Edge and GoogleChrome
- Grafana plugins: Geomap
- Other: enable_alpha is set to true

**Comment by nmarrs** [comment]
Hi, this is not an error and actually is a mess up on our part 🙁, we did not include the related code in the v9.1 release branch, this should be resolved in the next release (v9.1.6)

**Comment by nmarrs** [comment]
Confirming that measure tools are now available in [v9.1.6](https://grafana.com/grafana/download/9.1.6)

**Comment by HenrikRolandHansen** [comment]
Cool Thanks - yes it works perfectly now, can't wait to measure distances to cable faults and vessels 😎
