### ISSUE TITLE
Logs: Remove useless quote and backslash in logs panel detected fields

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#54959]
**Steps to reproduce**:

Use Explorer or logs panel with TestDataDB - RawFrames:
```json
[
  {
    "schema": {
      "meta": {
        "preferredVisualisationType": "logs",
        "custom": {
          "RequestId": "46eb66dd-3595-4067-a769-9e2ba2061c43",
          "SamplingRate": 0
        },
        "executedQueryString": ""
      },
      "fields": [
        {
          "name": "__TIMESTAMP__",
          "type": "time",
          "config": {}
        },
        {
          "name": "__LogJson__",
          "type": "string",
          "config": {
            "custom": {
              "displayMode": "json-view"
            }
          }
        },
        {
          "name": "__META__",
          "type": "string",
          "config": {
            "custom": {
              "hidden": true
            }
          }
        }
      ]
    },
    "data": {
      "values": [
        [
          1662717487414
        ],
        [
          "{\"logType\":\"clientlog-tkex\",\"tsTime\":\"1662717487414\",\"lid\":\"BJNHGddxi\",\"ownerUin\":\"100001001014\",\"body\":\"{\\\\\\\"serviceType\\\\\\\":\\\\\\\"cls\\\\\\\",\\\\\\\"action\\\\\\\":\\\\\\\"DescribeMachines\\\\\\\",\\\\\\\"regionId\\\\\\\":4,\\\\\\\"data\\\\\\\":{\\\\\\\"Version\\\\\\\":\\\\\\\"2020-10-16\\\\\\\",\\\\\\\"GroupId\\\\\\\":\\\\\\\"5caa0b48-0b4e-4314-9c25-02d4ef7f89f7\\\\\\\"},\\\\\\\"clientTimeout\\\\\\\":65000}\",\"life\":\"7154259\",\"result\":\"{\\\\\\\"data\\\\\\\":{\\\\\\\"Response\\\\\\\":{\\\\\\\"Machines\\\\\\\":[],\\\\\\\"AutoUpdate\\\\\\\":1,\\\\\\\"UpdateStartTime\\\\\\\":\\\\\\\"12:42:00\\\\\\\",\\\\\\\"UpdateEndTime\\\\\\\":\\\\\\\"14:42:00\\\\\\\",\\\\\\\"LatestAgentVersion\\\\\\\":\\\\\\\"2.8.2\\\\\\\",\\\\\\\"ServiceLogging\\\\\\\":true,\\\\\\\"RequestId\\\\\\\":\\\\\\\"30adda99-6c49-44d3-9532-8d159bcf2f89\\\\\\\",\\\\\\\"Flag\\\\\\\":\\\\\\\"\\\\\\\"}},\\\\\\\"code\\\\\\\":0}\",\"b.version\":\"2020-10-16\",\"returnCode\":\"0\",\"appId\":\"1254077820\",\"host\":\"{\\\"name\\\":\\\"qcbase-prod-cq1-0\\\"}\",\"action\":\"DescribeMachines\",\"tkexNodeIp\":\"30.50.81.206\",\"uin\":\"871571094\",\"timeCost\":\"279\",\"resRegion\":\"ap-shanghai\",\"tkexWorkload\":\"qcbase-prod-cq1\",\"seqId\":\"1bd26f96-8471-9da1-c910-2b2851b30a1a\",\"b.clientTimeout\":\"65000\",\"tkexNodeHostName\":\"qcbase-prod-cq1-0\",\"b.serviceType\":\"cls\",\"method\":\"POST\",\"ip\":\"113.108.77.55\",\"r.requestId\":\"30adda99-6c49-44d3-9532-8d159bcf2f89\",\"userAgent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\",\"urlPath\":\"hosts\",\"url\":\"http://iaas.cloud.tencent.com/cgi/capi?i=cls/DescribeMachines&uin=871571094\",\"callerIp\":\"30.50.81.206\",\"logTime\":\"2022-09-09 17:58:07.414\",\"@time\":\"2022-09-09T09:58:07.414Z\",\"errCode\":\"0\",\"b.regionId\":\"4\",\"time\":\"2022-09-09 17:58:07.414\",\"region\":\"cq\",\"status\":\"200\"}"
        ],
        [
          "{\"Source\":\"9.143.206.80\",\"HostName\":\"VM-206-80-centos\",\"PkgId\":\"57C5412163117D48-6\",\"PkgLogId\":\"13959354\"}"
        ]
      ]
    }
  }
]
```
 

**Actual Result**:

When detected value is number, it will work good. 
But when detected value is string, it will be wrapped with extra quote:
      `{key: "abc"}`  -> `key    "abc"`

When detected value is stringify string content, lots of `\"` symbol will be shown.
      `{key: '{"abc": []}'}` ->  `key    "{\\"abc\\": []}"`

<img width="1895" alt="image" src="https://user-images.githubusercontent.com/12808432/189326338-bea13407-0bda-49d7-a7f1-804e69a00b9b.png">

**Expected Result**

Without useless quote and backslash symbol.

like this:

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/12808432/189327004-63b44e77-d21a-473d-b549-4a95dccb0b8d.png">

**Solution**

When use exploer and logs component, detected fields will be stringified.

https://github.com/grafana/grafana/blob/942be4215afaea27757fb3a034126452aaf3fab2/packages/grafana-data/src/utils/logs.ts#L71-L94

I think follow stringify code `JSON.stringify(parsed[key])` can be replaced with `isObject(parsed[key]) ? JSON.stringify(parsed[key]) : parsed[key]`

https://github.com/grafana/grafana/blob/942be4215afaea27757fb3a034126452aaf3fab2/packages/grafana-data/src/utils/logs.ts#L78

If this solution is acceptable, i will create new pullrequest to fix this.

**Environment**:  any
- Grafana version:  9.1.3
- Data source type & version:  any
- User OS & Browser:   chrome
- Others: .

**Comment by ivanahuckova** [comment]
@MeetzhDing thank you for bringing this up. Your solution make sense, so if you are up for it, we would appreciate your contribution here! 🧡  

2 points here: 
- we have moved logic from `grafana/packages/grafana-data/src/utils/logs.ts` to `public/app/features/logs/utils.ts`. `grafana/packages/grafana-data/src/utils/logs.ts` is deprecated and not used anymore, so feel free to update only `public/app/features/logs/utils.ts`. 
- could you please add some unit tests for this

**Comment by gabor** [comment]
since the last communication happened here, the way logs-details work were changed in https://github.com/grafana/grafana/pull/60448 , so this issue does not happen anymore. closing it.

(if you think it still happens, feel free to reopen it and we can continue)
