### ISSUE TITLE
Public dashboards: subpath is ignored in generated URLs

### ISSUE THREAD

**Issue by karlkibus** [grafana/grafana#54969]
**What happened**:

When the public dashboard feature is enabled, it will generate a URL for that dashboard that ignores that Grafana is being served from a subpath

For example, for a Grafana instance being served on `DOMAIN/grafana`, the public dashboard URL will be generated as `DOMAIN/public-dashboards/ID`

**What you expected to happen**:

The expected URL that should be generated would be `DOMAIN/SUBPATH/public-dashboards/ID` (in the example above, the expected URL would be `DOMAIN/grafana/public-dashboards/ID`)

**How to reproduce it (as minimally and precisely as possible)**:

Run Grafana on your computer with the following configuration file:

```
[server]
root_url = http://localhost:3000/grafana
serve_from_sub_path = true

[feature_toggles]
publicDashboards = true
```

Create a new dashboard, and make it public. Note the **Link URL** it gives you

![Screenshot from 2022-09-09 15-07-47](https://user-images.githubusercontent.com/112620155/189346866-d0b07eca-2b03-415b-b76d-6f0d2100e4e9.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: -
- OS Grafana is installed on: Ubuntu 22.04.1 LTS
- User OS & Browser: Ubuntu 22.04.1 LTS, Firefox 103.0.2
- Grafana plugins: none, this was tested on a freshly downloaded Grafana
- Others:

**Comment by bpedersen2** [comment]
We did not use subpath, but with 9.5.2 the URL is correct. So it can probably be closed as resolved.
