### ISSUE TITLE
Evaluation of Loki dashboard variable queries fails when other variables are referenced

### ISSUE THREAD

**Issue by ChrisSteinbach** [grafana/grafana#54961]
**What happened**:

When Loki dashboard variables are used _without_ the query referring to any other variable they seem to work fine, but when another variable from the dashboard is introduced, no values are returned.

**What you expected to happen**:

We expected the referenced dashboard variables to be evaluated. This was the behaviour in previous grafana versions.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create dashboard variable of type "Constant" giving it a value that will match a label in Loki
2. Create another dashboard variable with Loki as the data source
3. Choose the query type "Label values"
4. Fill in the "Stream selector" with a valid Loki stream returning some labeled entries, match the label with the constant previously created (e.g. mylabel="$myconstant")
5. Fill in the "Label" field with a label that exists among the entries of the stream and a reference to 
6. No label values are returned

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2.0-77907pre (933ec4817f)
- Data source type & version: Loki 2.6.1
- OS Grafana is installed on: OpenShift 4.9
- User OS & Browser: MacOS Montery 12.5.1 running Chrome Version 105.0.5195.102 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by ChrisSteinbach** [comment]
![Screen Shot 2022-09-09 at 09 53 12](https://user-images.githubusercontent.com/3025196/189342890-22b2c254-4b74-4805-90f7-278e4d480872.png)
![Screen Shot 2022-09-09 at 09 53 47](https://user-images.githubusercontent.com/3025196/189342900-6b202d73-d4f4-4623-bf6a-4dfc0708975a.png)

In case the main description is not clear enough, here are two screenshots, one where the Loki variable returns some values, and the same query with a variable reference introduced that breaks the query.

**Comment by ivanahuckova** [comment]
Thank you for creating the issue. We actually have an issue for this https://github.com/grafana/grafana/issues/54907, so I am closing this as duplicate.
