### ISSUE TITLE
divide metric time series using elastic as datasource 

### ISSUE THREAD

**Issue by tlktoash** [grafana/grafana#5497]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1
- What datasource are you using? elastic
- What OS are you running grafana on? windows 7

Hi , i switch to use Grafana/elastic from kibana/elastic. Grafana is awesome . i love it. I am looking divide two elastic metric series in grafana. i refer to #5437 but this option is not available for elastic as data source. i cant switch to graphite . Is there any option to divide metric series in grafana/elastic ?

**Comment by torkelo** [comment]
Elasticsearch query API does not support operations on series like Graphite. 

But we hope to do this some day via this meta queries: https://github.com/grafana/grafana/issues/3677
