### ISSUE TITLE
Dark Theme fails to show everything in Safari 9.1.1

### ISSUE THREAD

**Issue by stefws** [grafana/grafana#5498]
- [x ] Bug report

Please include this information:
- What Grafana version are you using? 3.04
- What datasource are you using? ES 2.3
- What OS are you running grafana on? CentOS 6.8
- What did you do? Editing Dashboards from OSX 10.11.5+Safari 9.1.1
- What was the expected result?
- What happened instead? 
Some links/buttons are not visible in Dark Theme, works in Chrome and in Light Theme, making it hard to edit in Safari + Dark Theme :(

**Comment by torkelo** [comment]
tested on OSX 10.10 and Safari 9.1.1 could not find any invisible buttons / links. Where did you find them?

**Comment by stefws** [comment]
Admitted this morning I don’t see missing links either, but friday in the panel editor under metrics I missed out the move-up/down,view, delete buttons on the right, dunno what the heck didn't even restart my Safari this morning… sorry!

/Steffen

![gf_darktheme_paneleditor](https://cloud.githubusercontent.com/assets/6408122/16552391/0a61c976-41c1-11e6-84f3-c3eba7bf27a4.png)
