### ISSUE TITLE
About showing different time series charts

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#5499]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
I want to know if I can show the 2 charts on the page... for my use case -- which is show page performance as below:
1. Page performance for a given page for Peak hours during weekdays 
2. Page performance for a given page for non-peak hours
3. Page performance for a given page during weekend only

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Please direct questions to the mailing list (check support link on grafana.org)
