### ISSUE TITLE
Tempo - Add field in TempoQuery for TraceQL query

### ISSUE THREAD

**Issue by adrapereira** [grafana/grafana#54998]
We're currently using the `query` field of `TempoQuery` to hold the state of the TraceQL editor but this field is used by the `TraceID` tab. This means that when users change between the two tabs the input value will be the same, which isn't the ideal user experience. 

Let's create a new field in `TempoQuery` to track the state of the TraceQL query.

**Comment by CrypticSignal** [comment]
Will no longer implement because as discussed in #55025, we plan on combining the TraceID and TraceQL tabs to use the same query field for both types of queries.
