### ISSUE TITLE
Public Dashboard: Flag should not show public if you have it disabled

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#55004]
![Image](https://user-images.githubusercontent.com/3534544/189437941-e613ce47-49aa-48b2-813f-c732fe4bd821.png)

If you create a new public dashboard, then disable it, the "public" tag on the header still remains. We should hide the public tag if the public dashboard is disabled (regardless if there is a row).

**Comment by owensmallwood** [comment]
Waiting to hear from the frontend team about the correct way to force the dashboard to refetch it's state

**Comment by owensmallwood** [comment]
Waiting to hear from the frontend team about the correct way to force the dashboard to refetch it's state
