### ISSUE TITLE
create custom variables issues

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#55003]
The following 2 locations show the wrong way to create custom variables

1. Documentation
https://grafana.com/docs/grafana/latest/variables/variable-types/add-custom-variable/

```
key1 : value1,key2 : value2
```

It should be

```
key1 : value1, key2 : value2
```

Spacing is critical otherwise it won't work

2.  In the Variables creation section of a dashboard

![image](https://user-images.githubusercontent.com/900951/188927640-a782f91d-a557-4d54-b8a4-528b9f2669c7.png)

As you can see here it lists the keys first comma delimited and then the values
key1, key 2, key3 : value1, value2, value3

Thanks

**Comment by dougmellon** [comment]
Link to latest documentation page: https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/

**Comment by zuchka** [comment]
thanks as always, @yosiasz!

looks like that page is now archived. I've forwarded this to the docs team to be safe. They can close as needed 👍

**Comment by zuchka** [comment]
@yosiasz but I just realized that you are totally right about your second point. I'll try to push a fix for that rn

**Comment by zuchka** [comment]
@yosiasz I believe that example is correct, but the docs still have a spacing error for the key-value pairs:

in the new docs:

>In the Values separated by comma list, enter the values for this variable in a comma-separated list. You can include numbers, strings, or key/value pairs separated by a space and a colon. For example, key1 : value1,key2 : value2.

this part def should have proper spacing ` key1 : value1,key2 : value2`

**Comment by yosiasz** [comment]
✊🏿 cool
