### ISSUE TITLE
include timelion (or similar functionality) as a data panel/source

### ISSUE THREAD

**Issue by yehosef** [grafana/grafana#5500]
Feature request
Grafana allows you to use graphite and perform operation on different series (eg add, divide, etc).  This is really great - but only works for graphite.  You cannot combine any other data sources.

https://github.com/elastic/timelion allows you to combine arbitrary series and perform math on them similar to how you can using graphite.  Currently it support just graphite and elasticsearch, but it should be relatively simple to include others.

It would be amazing if Grafana included Timelion or a solution similar to it to allow combining arbitrary data series.

**Comment by torkelo** [comment]
yes, we do plan to do this :)

https://github.com/grafana/grafana/issues/3677
