### ISSUE TITLE
[Feature Request] show to different dashboard using template variable

### ISSUE THREAD

**Issue by sjahn90** [grafana/grafana#5501]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
Please include this information:
- What Grafana version are you using? Grafana 3.2.0-pre1
- What datasource are you using? Influx 0.13.0
- What OS are you running grafana on? CentOS 6.3
- What did you do? I'll make monitoring dashboard to show different dashbord per specific group. 
- What was the expected result? new template variable type
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

I'm trying to monitor of thousand of servers. Those server can be classified server group. Each group has different monitoring view(different panel). To provide different view per each group, we can show different dashboard use using URI query string or a tag for grouping in influx DB. The former case, it is not user-friendly. Because user have to know name of all group in advance. And if add more group, user is not easy to know new group name. The latter case, our db does not have the tag for grouping. And it is difficult to add new tag.  

So, if there is new template variable type for this purpose, grafana user can make more flexible dashboards.

Below is sample.
 
---  
dashboard.templating = {
  enable: true,
  list: [
    {
      name: 'test',
      query: 'one,two,three',
      refresh: true,
      options: [],
      current: null,
      type: 'new type'
    }
  ]
};

if ("$test" == "one")
  dashboard.rows.push { panel1 }
else if ("$test" == "two")
  dashboard.rows.push { panel1; panel2 }
else if ("$test" == "three")
  dashboard.rows.push { panel1; panel2; panel3 }
else
  dashboard.rows.push { defaultpanel }

return dashboard;

**Comment by torkelo** [comment]
Have you looked at Gefana templating? Look at the InfluxDB dashboards on play.grafana.org, templating allows you to create dynamic dashboards, you can have variables dynamically filled with values from InfluxDB, you can repeat panels for each value of that is what you want

**Comment by sjahn90** [comment]
Now, I've checked graphite panel repeats and Influxdb related dashboards on play.grafana.org. In case of graphite panel repeats, looks to repeat with same panels.

My intention is to show different panel depending on something group.

For example, I can classify 3 groups (db, web, storage) about our all servers. In terms of db group, I want to show db-related monitoring data(mysql stat). In web, want to show no of current user, HTTP RPS, etc(nginx mod_status). Storage is to show disk I/O, IOstat, etc. 
To do this, I need new type of template variable in order to compare group with the variable.

**Comment by torkelo** [comment]
Why use variable for this? Do not understand what you are trying to do.

**Comment by sjahn90** [comment]
As I mentioned previously, I am trying to make monitoring system using collectd + influxdb + grafana.
Target servers are more than thousand of that.
I can divide several group including db, web, storage, etc.

Each group has different raw & panels.

I want to switch to draw different dashboard per group with template variable.
I've attached sample script.. Ignore that template variable is custom type in file.
[server_template.js.txt](https://github.com/grafana/grafana/files/347210/server_template.js.txt)
