### ISSUE TITLE
Command palette: disable autofill

### ISSUE THREAD

**Issue by cubakid** [grafana/grafana#55010]
**Steps to reproduce**: open the command palette, start typing

**Actual Result**: if the browser has saved info, it will pop-up a list of word suggestions OVER Grafana's list

**Expected Result**: no browser pop-up

**Environment**:
- Grafana version: 9.1.2
- User OS & Browser: Windows 10, Edge, haven't tested other browsers

**Comment by usmangt** [comment]
Hi @cubakid,

Thanks for opening this issue. We would like to get some more details.

Can you please try to reproduce this on Chrome or Firefox? (as for me it works fine at least on these 2 while I will try to get it tested on an Edge browser).

Also, on the Edge browser, if you may have any plugins or addons, then please disable them and then try to reproduce and tell if that still happens.


Thanks.

**Comment by cubakid** [comment]
While I didn't do extensive testing, Chrome didn't seem to have the issue,
probably due to the element having autocomplete="off".

I don't have any extensions installed in Edge. I had searched for info on
how to disable in Edge and it might need an aria-autocomplete attribute.
