### ISSUE TITLE
`<PluginPage>` - figure out a way how it can be backwards compatible

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#55020]
### The problem
https://github.com/grafana/grafana/pull/53174 has introduced a new `<PluginPage>` component that can be used by the plugins to migrate from using the `onNavChanged()` callback, that was (and still is) passed in by Grafana to the main plugin component. Although this is a good and important step forward, in case a plugin updates to it they will no longer work in previous versions of Grafana (<9.2).

### The goal 
We would like to provide a well documented and as-simple-as-possible solution for plugin authors to update their plugins in a way that is backwards compatible with Grafana versions <9.2.

### The how

https://github.com/grafana/grafana/issues/55020#tasklist-block-f2939f20-06d7-4a6f-a931-87a1c141996f

**Comment by torkelo** [comment]
@tolzhabayev @leventebalogh 

This is already solved in https://github.com/grafana/grafana-starter-app/pull/39  

But needs to be documented. It's not easy or pretty but I don't see any other way than something like that. The biggest problem is that that solution is not universal. Around 50% of plugins don't use onNavChanged but instead create their own page layout and for those plugins the solution will have to be different, and potentially a bit more complex

**Comment by tolzhabayev** [comment]
@torkelo yeah, we saw that (it's also linked above in the description) and thanks for the solutions. We will definitely look at it first and maybe see if there is anything else we can do. We want to help the app developers with examples and docs to be able to migrate. Luckily we don't have that many app plugins out there currently so that the ones that use own page layout can migrate to using it, we just need a guide / examples for how to do it.

**Comment by mikkancso** [comment]
I don't think this strictly relates to the Connections project, therefore I'm removing this from that project.

**Comment by sympatheticmoose** [comment]
Completed
