### ISSUE TITLE
In chrome version of ( Version 105.0.5195.102 (Official Build) (x86_64) ) bug in typing ( mac m1 )

### ISSUE THREAD

**Issue by kibernetik542** [grafana/grafana#55037]
When I try to type `{ namespace}` result changing to `{n}a`
in Opera and in Mozilla it works as expected.

![Screenshot 2022-09-12 at 16 24 33](https://user-images.githubusercontent.com/24855827/189680530-6111ba49-0e89-4138-a0f2-ba350932a176.png)

**Comment by meehanman** [comment]
Confirmed on Grafana v8.2.7 (d2cccfe91e) using Version 105.0.5195.102 (Official Build) (x86_64)

Not sure if relevant, but the `n` character within the `{ }` is showing as this in the inspect tools. This surrounds every character; for example writing the letter a will only show 1 character in the UI but you will have to press backspace n-times.
![image](https://user-images.githubusercontent.com/4993167/189706695-397eb0cf-1002-4bce-8a87-0e82c14c7f2b.png)

These characters are in the search as when you do a search; you'll get the following returned.
```
"1:2: parse error: unexpected character inside braces: '\\ufeff'"
```

**Comment by zuchka** [comment]
known issue: the PR merged into 9.1.4

https://github.com/grafana/grafana/pull/54566

**Comment by qixiaobo** [comment]
So sad to hear this…… with m1

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/191765058-230f468f-407d-4c14-8468-e41c3e0113df.png)

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/191770044-e82a769c-51ca-4bae-9822-1532a5bb6ecf.png)

**Comment by meehanman** [comment]
If it's any help. We upgraded from `Grafana v8.2.7 (d2cccfe91e)` to `v1.9.5` which resolved the issue with only a short downtime of 2-3 minutes while the database was rebuilt and haven't seen any issues with our existing configuration/dashboards.

**Comment by qixiaobo** [comment]
> If it's any help. We upgraded from `Grafana v8.2.7 (d2cccfe91e)` to `v1.9.5` which resolved the issue with only a short downtime of 2-3 minutes while the database was rebuilt and haven't seen any issues with our existing configuration/dashboards.

Maybe typo? v9.1.5?

**Comment by WonderLand33** [comment]
> > If it's any help. We upgraded from `Grafana v8.2.7 (d2cccfe91e)` to `v1.9.5` which resolved the issue with only a short downtime of 2-3 minutes while the database was rebuilt and haven't seen any issues with our existing configuration/dashboards.
> 
> Maybe typo? v9.1.5?

一样的问题啊， 我是docker跑的，如何不影响旧的容器正常运行修复这个BUG？
I have the same problem, I am running with docker, how can I fix this bug without affecting the normal operation of the old container?

**Comment by qixiaobo** [comment]
> 

No k8s? No deployment?

**Comment by dkalashnik** [comment]
Maybe someone knows about any trick to fix the chrome behavior? There is no possibility to update the grafana, so I had to downgrade to chrome-stable 104.0.5112.101-1

**Comment by qixiaobo** [comment]
> Maybe someone knows about any trick to fix the chrome behavior? There is no possibility to update the grafana, so I had to downgrade to chrome-stable 104.0.5112.101-1

Use safari😢
