### ISSUE TITLE
[Feature request] Enable the templating to have global variables for every dashboard

### ISSUE THREAD

**Issue by rydeng** [grafana/grafana#5504]
Just like the title, enable the templating to have global variables for every dashboard.

**Comment by rydeng** [comment]
Ho-ho,is there someone?
^-^

**Comment by torkelo** [comment]
@rydeng yes?

**Comment by torkelo** [comment]
think this is a good idea, will probably be implemented some day :) 
will close as feature as already been requested in https://github.com/grafana/grafana/issues/1959

**Comment by rydeng** [comment]
it is cool

**Comment by andrewnaguib** [comment]
Any update on that?

**Comment by shaunroselt** [comment]
This would be very useful to have.

+1
