### ISSUE TITLE
[Feature request] Number formatted with thousands separator

### ISSUE THREAD

**Issue by jazzzz** [grafana/grafana#5505]
Large numbers are hard to read, they would be easier to read with thousands separators, configurable for several locales.

![image](https://cloud.githubusercontent.com/assets/290626/16561734/1af6310c-41fb-11e6-8b1c-35784ba3162f.png) ⇒ 1,262,557 (US) or 1 262 557 (Europe)

![image](https://cloud.githubusercontent.com/assets/290626/16561741/2281fe10-41fb-11e6-9d50-ee85a27ed5ae.png) ⇒ 43,339 (US) or 43 339 (Europe)

**Comment by torkelo** [comment]
yes! will close as issue already exists
https://github.com/grafana/grafana/issues/1395
