### ISSUE TITLE
Docs and clarifications improvements

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#55068]
This issue is a collection of improvements we can introduce to give users a better explanation and understanding of Grafana Alerting features. It's based on users' questions from community channels

- [ ] Explain the difference between Grafana-managed and cloud alerts
- [ ] Explain dynamic label templating (how to set a label's value based on the value of metrics)
- [ ] Notification policies reordering https://github.com/grafana/grafana/discussions/52574
- [ ] Alert rule duplication https://github.com/grafana/grafana/issues/39431

**Comment by valkom1** [comment]
Hi @konrad147, last Alert rule duplication needs to be reopened, solution is only provided to duplicate a query inside an alert, not to duplicate the alert itself with all it's queries.

**Comment by Eve832** [comment]
@brendamuir can you please update the status of this ticket, if appropriate?

**Comment by brendamuir** [comment]
Cancelling this as it's covered in the new alert creation workflow ui text and docs.
