### ISSUE TITLE
Grafana integration with IPA

### ISSUE THREAD

**Issue by amitactive2008** [grafana/grafana#5506]
Hi,

I would like to integrate Grafana with IPA. Below is my ldap.toml file.
=============
verbose_logging = true
[[servers]]
host = "192.168.16.210"
port = 636
use_ssl = true
ssl_skip_verify = false
root_ca_cert = /etc/grafana/ca.crt
bind_dn = "uid=admin,cn=users,cn=accounts,dc=atpl,dc=com"
bind_password = 'Password'
search_filter = "(cn=%s)"
search_base_dns = ["dc=atpl,dc=com"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
[[servers.group_mappings]]
group_dn = "cn=admins,dc=atpl,dc=com"
org_role = "Admin"
[[servers.group_mappings]]
group_dn = "cn=users,dc=atpl,dc=com"
org_role = "Editor"
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
======================
while restarting I am getting below error.

LoginPost()] [E] Error while trying to authenticate user: LDAP Result Code 200 "": x509: cannot validate certificate for 132.1.16.210 because it doesn't contain any IP SANs

Kindly suggest me.

**Comment by torkelo** [comment]
I am not sure `Cannot validate certificate for 132.1.16.210 because it doesn't contain any IP SANs` what that means, maybe check serverfault or other Grafana support channels (mailing list). 

http://grafana.org/support/
