### ISSUE TITLE
[Feature Request] Custom order for elasticsearch query in group by/terms split

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#5507]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0
- What datasource are you using?
elasticsearch
- What OS are you running grafana on?
Ubuntu 14.04

I would like some custom order for some queries.
When using _group by/term split_ in elasticsearch queries I can select the order (top/bottom) and order by (term value/doc count/avg x/max x/...) but for RAM memory graphs for example I want some fixed custom order. 
e.g. free memory should be first.

So I would like to put something like a comma separated list in the group by value field or the associated order by field. e.g. (used,cached,buffered,free)

**Comment by torkelo** [comment]
Custom sort order is not something that will likely ever be implemented, so far no one has ever requested it. Sorry, not keen to add a new option for an edge case like this that will only be used by 0.001% of users. 

Legend sort order can controlled the TSDB query backend (in this case Elasticsearch), or sorted in Grafana by max, min, avg etc.
