### ISSUE TITLE
Grafana 9.1.4 admin could not add organization to user

### ISSUE THREAD

**Issue by pablozone** [grafana/grafana#55077]
User log in via ldap, Then admin add credentials to organiations. In Grafana 9.1.4 there is no button "Add user to Organizations"

![bug2](https://user-images.githubusercontent.com/29774180/189890880-ca5831ab-2188-45b4-95e7-0ae8b78f3c70.jpg)

**Comment by zuchka** [comment]
I believe this was removed on purpose:

https://github.com/grafana/grafana/pull/52160

**Comment by mellieA** [comment]
@pablozone I think this is related to https://github.com/grafana/grafana/pull/55302
