### ISSUE TITLE
Repeat Row metric color to be consistant

### ISSUE THREAD

**Issue by trevorndodds** [grafana/grafana#5509]
Feature/Bug

3.0.4 Windows build, Elasticsearch

When building repeat rows the color of the metrics are not consistent across the rows.

![image](https://cloud.githubusercontent.com/assets/10899305/16564288/aa4dcc42-41d4-11e6-9e21-4cb749e0b39d.png)

**Comment by torkelo** [comment]
Automatic color is determined by the order of the series returned, you can also specify color for each series but this will only be specified based on series name, if the series name change then the color will fall back to automatic again. So when you  repeat panel if the series name change it will not match the name you specified for the "template" panel. You can specify regex color rules in the display tab, series override style (select regex and color)
