### ISSUE TITLE
extra line in Slack message

### ISSUE THREAD

**Issue by matrog** [grafana/grafana#55099]
After upgrading from grafana 8.5.6 to 9.1.4 there's an extra title line in Slack notification message.

v8.5.6
<img width="600" alt="2" src="https://user-images.githubusercontent.com/103855/189903545-a2322648-e788-4f3c-a417-2155e70060bc.png">

v.9.1.4
<img width="694" alt="1" src="https://user-images.githubusercontent.com/103855/189903570-01b3fc58-48dd-40d9-9360-05a50cb834ac.png">

The Slack Contact Point is using customized Subject and Text but it's the same even with default values.

This extra line should be removed

**Environment**:
- Grafana version: 9.1.4
- Data source type & version: Flux (with Influxdb 2.1.0)
- OS Grafana is installed on: RedHat 8.6
- User OS & Browser: Chrome / Firefox on macOS
- Grafana plugins: N/A
- Others: N/A

**Comment by mellieA** [comment]
@matrog thanks for taking time to open this issue. This is a known issue  based on the comment in https://github.com/grafana/grafana/issues/52881 

> We had to https://github.com/grafana/grafana/pull/52391 to the Slack message to fix issue https://github.com/grafana/grafana/issues/42768. This is expected for now until we move to [Block Kit](https://api.slack.com/block-kit). However, we don't have an ETA for this as we would like to continue to be compatible with upstream Alertmanager, and there is an open issue https://github.com/prometheus/alertmanager/issues/2217 for adding Block Kit to Alertmanager.
