### ISSUE TITLE
Navigation: Adjust Megamenu to work with topnav

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#55100]
TODO:
- [ ] Make section headers clickable (e.g. `Dashboards` goes to the `/dashboards` page)
- [ ] Make hover/active states consistent with `SectionNav`
- [x] Investigate removing storing state of expanded items

**Comment by Wafa9** [comment]
HI @ashharrison90  I would like to work on this issue, I am looking for a good first issue so can I take this?

**Comment by ashharrison90** [comment]
hi @Wafa9 👋

I would say this is not a good issue to pick up as we have a set of designs we're working to.

if you're looking to contribute, look for issues with the `help wanted` or `good first issue` label
