### ISSUE TITLE
Panels' rendering behind custom reverse proxy

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#5511]
**I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

v3.1

- What datasource are you using?

Elasticsearch

- What OS are you running grafana on?

Linux RHEL6.4 x86_64

- What did you do?

Created an application (_myApp_) that's running behind a custom reverse proxy, that communicates with Grafana and that's deployed on **localhost:8080/myApp**.

Then I modified Grafana's full public facing URL, on *default.ini*, to:

`root_url = %(protocol)s://%(domain)s:%(http_port)s/myApp/graph`

_myApp_ can successfully communicate with Grafana and redirect the pertinent requests to it.

Afterwards, on Grafana (localhost:8080/myApp/graph), I tried to render a panel by clicking on _Direct link rendered image_.

- What was the expected result?

I was expecting that the selected panel's image would be rendered on a new tab.

- What happened instead?

I got a *404 page not found* response error for the following URL:

    http://localhost:8080/myApp/graph/render/dashboard-solo/db/myServer?from=now-3m&to=now&panelId=8&width=1000&height=500

Below follows the _grafana.log_ content:

    t=2016-07-05T10:41:18+0200 lvl=info msg="PhantomRenderer::renderToPng url [http://localhost:3000/myApp/graph/dashboard-solo/db/myServer?from=now-3m&to=now&panelId=8&width=1000&height=500]"
    t=2016-07-05T10:41:18+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/dashboard-solo/db/myServer status=404 remote_addr=10.24.191.4 time_ns=232ns size=19

Tried to follow the approaches mentioned on issues #2051 and #5430 without any success.

As a side note, I've noticed that a FTP request is triggered when fetching the image. On the limit, is it necessary also to implement a mechanism, on my custom reverse proxy, that deals with FTP requests?

**Comment by torkelo** [comment]
set root_url to the url you use in the browser (the reverse proxy url) this url is used in redirects and when generating links in emails.
