### ISSUE TITLE
ScriptedDashboard : after generate dashboard to be able save it as permanent dashboard

### ISSUE THREAD

**Issue by azicko** [grafana/grafana#5512]
Hello,

It will be very helfull if you can add support to save dashboard in ScriptedDashboard.js. This feature was in grafana 

1.9.0-rc1 (2014-11-17) ---> ScriptedDashboard: datasource services are now available in scripted dashboards, you can query datasource for metric keys, generate dashboards, and even save them in a scripted dashboard (see scripted_gen_and_save.js for example)

Closed feature in commit : 
https://github.com/grafana/grafana/commit/a7b0f6dc9fcbb4f3ad1449e7ebde42ded7f67fc4

But in new versions of Grafana this feature dissapearred.

Is it possible to add this feature to grafana again ? 
Or
Is it possible to do this by some other way ? 

Thanks,

* **I'm submitting a ...**
- [ x ] Feature request

Some informations about grafana what I'm using : 
- What Grafana version are you using? -> Grafana version 3.0.4
- What datasource are you using? -> InfluxDB
- What OS are you running grafana on? -> Debian Jessie, Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by torkelo** [comment]
dashboardSrv and datasourceSrv is still available for scripted dashboards.  

If you want to build dashboard dynamically and then save them, you could do that in an external application then save them to grafana using the HTTP api. 
http://docs.grafana.org/http_api/dashboard/

**Comment by azicko** [comment]
Thank you very much !.
