### ISSUE TITLE
Geomap: Tool tip toggle not working in 9.1.5

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#55125]

**Comment by supilee** [comment]
The toggling option in the data layer is disabled and thus cannot be used in 9.1.5:

Steps to reproduce:
1. Create a new panel
2. Select geomap
3. open up the data layer option
4. enable the tool tip by using the tooltip toggle slider

Expected Result:
The tooltip toggle will be activated and information is available in the panel.

Actual Result:
The tooltip toggle is not responding and thus cannot be used.

OS: MacOS Monterey 12.5.1
Browser: Chrome 105.0.5195.102 (Official Build) (arm64)
Grafana Version: v 9.1.5 

Also tested on:
OS: MacOS Monterey 12.6
Browser: Chrome 105.0.5195.102 (Official Build) (arm64)
Grafana Version: v 9.1.3 
--> same behavior

**Comment by drew08t** [comment]
A consistent way to replicate:
1. Collapse "Map layers" category
2. Expand "Map layers" category
3. On a data layer, attempt to toggle tooltip

![Image](https://user-images.githubusercontent.com/60050885/190235018-b6fffbae-9763-4f24-a8fd-146be1a6a849.gif)

**Comment by drew08t** [comment]
<input/> element is being removed (not disabled) when collapsing a category.

![Image](https://user-images.githubusercontent.com/60050885/192828878-9fdcdff4-9176-47e7-8e4a-6634afe82928.gif)

**Comment by drew08t** [comment]
I think this might be the cause:
https://github.com/grafana/grafana/blob/main/public/app/core/navigation/GrafanaRoute.tsx#L78-L86
