### ISSUE TITLE
Bug/Feature: Disable "Do you want to save your changes?" dialog for dashboard or globally

### ISSUE THREAD

**Issue by StianOvrevage** [grafana/grafana#5513]
Please include this information:
- What Grafana version are you using?
3.0.3
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Put a panel inside an iframe. Reloaded the parent page without touching the iframe.
- What was the expected result?
To have the page reload (and it's child iframes)
- What happened instead?
A Chrome dialog box pops up saying that my changes might not be saved. Blocking reload and all other Chrome windows.

---
Recently Chrome deprecated the option to show a custom dialog box when leaving a page. The dialog box used to show the black Save/Cancel/Ignore question when leaving an edited dashboard without saving. ( https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove-custom-messages-in-onbeforeload-dialogs ).

Now instead a Chrome dialog box pops up with the text "Changes you made may not be saved.". This dialog box is blocking all other windows and tabs before it is answered.

In my specific setting I have embedded a few grafana panels in iframes on a status page together with other information. This status page is reloaded every 5 minutes. However, every 2-3 times the Chrome dialog box pops up warning about unsaved changes and blocking reloads and requiring human intervention. So the bug is that this happens even if there have been no changes to the panels. The feature request is to disable the ifChanged check alltogether on certain dashboards.

**Comment by torkelo** [comment]
Try opening the dashboard with the embedded panel and save it, the dashboard and panel might have only schema that needs a save to update it

**Comment by StianOvrevage** [comment]
It is a json file based dashboard.
