### ISSUE TITLE
Extend list of time zones

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#5514]
Currently the only two options for the time zone setting are "Local time" or "UTC". 
We have machines all over the world and need to show the graphs in local time of the machine. I currently have a cumbersome procedure in place that shows the user how to change it's computer timezone in order to get the graphs in machine local time. This is extremely user unfriendly, but it is the only workaround I have (Influx only returns epoch time at the moment).

It would be great if we could set the time zone of an Organisation, Dashboard or Panel to other time zones than UTC (Europe/Amsterdam, Asia/Hongkong, etc. see http://momentjs.com/timezone)

**Comment by torkelo** [comment]
There is already a feature request for this so will close this issue, 
https://github.com/grafana/grafana/issues/558
