### ISSUE TITLE
Form validation problem in table panel option (column width & minimum column width)

### ISSUE THREAD

**Issue by curiousbaker** [grafana/grafana#55145]
**What happened**: I can't type number (in my case 105) into column width & column width option field, the error says out of range

**What you expected to happen**: form validation on column width & column width option field should be triggered after a while after the user finished typing the number.

**How to reproduce it (as minimally and precisely as possible)**: Create table panel with some column, and set the column width or minimum column width option. GIF file attached.

**Anything else we need to know?**:
GIF of this bug.
![column_width_bug](https://user-images.githubusercontent.com/89766980/190082211-c790594f-34ac-4aac-95f4-d1503d321330.gif)

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: Windows 11
- User OS & Browser: Windows 11 & Firefox 104
- Grafana plugins: Table
- Others:

**Comment by mellieA** [comment]
Reproduced this in my 9.1.5 instance
