### ISSUE TITLE
CI: Split enterprise and enterprise2 pipelines

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#55151]
**What happened**:

Currently our `enterprise` pipelines do too much. We need to split `enterprise2` from `enterprise` pipelines, so our pipelines are responsible for building one thing at a time. This will save us some time and make our pipelines more lightweight.

https://github.com/grafana/grafana/issues/55151#tasklist-block-c3cc31f3-b3a1-469e-adf6-1716d63bb300

**Comment by tleopold** [comment]
Changes are ready for HG - HG are not ready to consume yet.  Work with Leonor
Update release guide with this new process.
Doc need to update their Doc build process to trigger doc build from successful product build
Need to be moved from sandbox to live
Need to implement for Cloud Partners
