### ISSUE TITLE
[ templating ] [ Query type ] text : value pairs dismissed with duplicate value

### ISSUE THREAD

**Issue by Satyam1210** [grafana/grafana#55154]
I am trying to use the Query Type variable with a regex `.*key=\"(?<text>[^\"]+)\"} (?<value>[^\\ ]+).*`
The result of the query is unique keys with multiple keys having same value.
However, with regex, only the entries that have unique values is shown, rest all are dismissed. 

For example:
Entries without applying regex: 

> {key="2022-09-15 01:00:00 <-> 2022-09-15 11:30:00"} 48600 1663147810000
> {key="2022-09-09 22:00:00 <-> 2022-09-11 04:30:00"} 120600 1663147810000
> {key="2022-09-10 22:00:00 <-> 2022-09-12 04:30:00"} 120600 1663147810000
> {key="2022-09-11 22:00:00 <-> 2022-09-13 04:30:00"} 120600 1663147810000
> {key="2022-09-12 22:00:00 <-> 2022-09-14 04:30:00"} 120600 1663147810000
> {key="2022-09-08 22:00:00 <-> 2022-09-10 04:30:00"} 120600 1663147810000
> {key="2022-09-14 01:00:00 <-> 2022-09-15 11:30:00"} 135000 1663147810000

Entries with regex: 

> 2022-09-15 01:00:00 <-> 2022-09-15 11:30:00
> 2022-09-09 22:00:00 <-> 2022-09-11 04:30:00
> 2022-09-14 01:00:00 <-> 2022-09-15 11:30:00

Expected behaviour: Show all unique keys no matter what the values are
Actual behaviour: Keys are dropped with same values

This can be reproduced with any query that produces entries with unique key names, but with same values.

Based on this https://github.com/grafana/grafana/issues/40414, there was similar issue in Custom type variable, which was fixed in v8.2.2. However it still does not work for Query type. 

Grafana v 8.3.4
Datasource : Prometheus

Any help is greatly appreciated !

Thanks

**Comment by dprokop** [comment]
I can confirm this works as described in the issue. I can't promise when this is going to be fixed, but I'm moving this into our backlog.
