### ISSUE TITLE
Remove piechart panel plugin hack

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#55184]
**Why?**
We have deprecated the https://grafana.com/grafana/plugins/grafana-piechart-panel/ starting from Grafana `8.+`
We can now remove the workaround and make sure people are using the core panel instead.

**Steps:**
- Remove https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/loader/loader.go#L213-L215 in `9.2.0` ([PR](https://github.com/grafana/grafana/pull/55215))
- Backport to `v9.1.x`,`v9.0.x` and `v8.5.x`
- Update `grafanaDependency` to `>=4.6 <=7` in https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.2 to make users from Grafana `8+` to switch to using the built-in piechart panel
- Update readme in https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.2 to display deprecated message on the plugin details page 
- Update plugin name in https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.2 to display `Pie Chart (old)
`

**Comment by tolzhabayev** [comment]
@oscarkilhed @dprokop any objections?

**Comment by tolzhabayev** [comment]
FYI @wbrowne

**Comment by torkelo** [comment]
@tolzhabayev not sure what is the goal here, just remove the rename hack? https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.2  is still named "Pie Chart" , so the rename hack still has some value?

**Comment by torkelo** [comment]
But customers will only see that new name if they upgrade the plugin, which I think most won't?

**Comment by tolzhabayev** [comment]
I think the following scenarios exist:
- For the users upgrading Grafana to 9.2, 9.1.x, 8.5.x that do reinstall plugins - they will have to switch to the native panel due to updated compatibility requirements - which is what we want anyway as it is deprecated.
- For users upgrading Grafana to 9.2, 9.1.x, 8.5.x that do not reinstall plugins on upgrade (no auto provisioning or such) - they will not see "(old)" in the panel name so it might be a bit confusing.
- For the users that are on Grafana 7- that are not updating their instance or the plugin - there will be no impact at all
- For the users that are on Grafana 7- that are updating their instance or the plugin - they will have the (old) displayed in the plugin title. 

Maybe there is a better way of doing this, I am open to any suggestions on how to clean up the code while having as little impact on the customers as possible.

**Comment by tolzhabayev** [comment]
@torkelo wdyt?
