### ISSUE TITLE
[Bug] Graph wihtout data when I use variable from QSA

### ISSUE THREAD

**Issue by mcortinas** [grafana/grafana#5519]
Hello,

 After upgrade from 2.6.0 to 3.0.2 the variable requested from Query String Agent using "var-$var" it doesn't work fine.

http://$FQDN:3000/dashboard/db/dashboardX?var-varname=varvalue

In version 2.6.0 i can see all the graphs filtered with this filter -varname=varvalue
In version 3.0.2 this doesn't work.

- What Grafana version are you using?
In version 2.6.0 it works fine, in 3.0.2-1463383025 it doesn't work

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Ubuntu 14

- What did you do?

- What was the expected result?
I hope my dashboards filtered with the variables requested in the Query String Agent.

- What happened instead?
Graph without results...

**Comment by torkelo** [comment]
cannot replicate this, seems to work here.

http://play.grafana.org/dashboard/db/templated-graphs-nested?var-app=fakesite&var-server=web_server_02&var-interval=$__auto_interval

Try to upgrade to 3.0.4 or 3.1.0-beta1

**Comment by mcortinas** [comment]
Yeah!  3.1.0-beta1 it works fine!!!!!!!  :+1:
