### ISSUE TITLE
Azure Monitor: ARG template variable not updating sub picker values when switching amongst Azure Monitor ds

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#55193]
**What happened**:
I have two Azure Monitor data sources. I configured an ARG variable using one them, on the same variable, on the same variable I switched the Azure Monitor data source, but the subscriptions that first showed were not gone even though the new select AzMon data source did not have access to them, and vice versa.

The only time the subs update was when I selected something in the UI that made the ARG variable editor disappear completely (i.e. switching my query type to subscriptions and then back to Resource Graph)

**What you expected to happen**:
My subscriptions to update properly if the data source is changed

**How to reproduce it (as minimally and precisely as possible)**:
1. Ensure 2 AzMon data sources are configured, preferable with access to different subs each
2. Create a resource graph template variable
3. Check the sub dropdown to see which subs show
4. Switch the AzMon data source to a different AzMon data source and check the sub dropdown again 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: NA
- User OS & Browser: Windows, Edge
- Grafana plugins: NA
- Others: NA

**Comment by andresmgot** [comment]
I am able to reproduce this, marking it as a bug
