### ISSUE TITLE
Instrumentation: Improve distributed tracing coverage for background jobs

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#55196]
In order to understand what Grafana's background jobs do and how they correlate/interact with other parts of the system we need to improve our tracing coverage. 

In general, all incoming HTTP requests is already covered. In theory any interactions with other parts of the system originating from an incoming HTTP request we can correlate using logs and traces by using the `traceID`. However, if a background job not being instrumented with tracing and interacts with other parts of the system there's no `traceID` to correlate things with.

Not sure what best practices are around long running background jobs if they run for minutes/hours so needs to be discussed. However for the below list we should at least be able to trace each evaluation:
- [x] https://github.com/grafana/grafana/pull/61057
- [x] Recorded queries evaluation
- [x] https://github.com/grafana/grafana/pull/55465

**Comment by joeblubaugh** [comment]
Can you put these behind a feature toggle? Alerting rule evaluation can be very high volume, so it will be hard to understand the performance impact here. I ran into this myself with a big database client refactor that later had to be reverted.

**Comment by marefr** [comment]
@joeblubaugh you mean a feature toggle to trace or skip tracing?

**Comment by joeblubaugh** [comment]
@marefr yes, that's what I mean.

**Comment by marefr** [comment]
@joeblubaugh sure, feel free to use a feature toggle as you see fit.

**Comment by yuri-tceretian** [comment]
I think that all parts related to alerting have been addressed. Can we close it? or just remove it from the alerting team's board?

**Comment by marefr** [comment]
@yuri-tceretian you can remove it from the alerting team's board. Thanks
