### ISSUE TITLE
Feature - Collapse/Expand All Rows

### ISSUE THREAD

**Issue by acesaro** [grafana/grafana#552]
A useful feature would be a collapse/expand all rows button somewhere.  This would be handy for dashboards with a lot of named rows, such as one row per host or something like that.  Maybe it would make sense to put this next to the "Add A Row" button on the bottom of the dashboard, maybe left aligned instead?

**Comment by mtanda** [comment]
+1

**Comment by akaey** [comment]
+1

**Comment by stockto2** [comment]
+1

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/7538
