### ISSUE TITLE
Dashboard not loading

### ISSUE THREAD

**Issue by Favorlock** [grafana/grafana#5520]
* **I'm submitting a ...**
- [x] Bug report

- What Grafana version are you using?
v3.0.1-beta1

- What datasource are you using?
influxdb

- What OS are you running grafana on?
centos 7

- What did you do?
I created variables as seen in this image: http://i.imgur.com/Vrsao4K.png and enabled multi selection with all option, and refreshing set to the time update. 

- What was the expected result?
For the dashboard to load even though one of the queries is not recommended.

- What happened instead?
Dashboard does not load.

**Comment by torkelo** [comment]
Can you inspect the chrome dev tools and network tab? What is the responses from InfluxDB? 

Any JS errors?

**Comment by Favorlock** [comment]
Not seeing any errors. I'm able to reproduce this bug by using those variables as seen in the screenshot.

**Comment by torkelo** [comment]
So no errors in Chrome js console? No requests to InfluxDB in network tab? 

What did you mean,  your queries are not recommended?

**Comment by Favorlock** [comment]
I"m just thinking that the the query for city may be having issues because of it's dependency on uuid, That appears to be where the dashboard appears to cease loading from the db at least. The only query that runs is the one that retrieves the countries. Here is the response for that: http://pastebin.com/sLCbJsGA

**Comment by torkelo** [comment]
I think the problem is that your variables depend on each other in a recursive way 

$uuid is using $city in it's query
$city is using $uuid in it's query 

You cannot have recurive dependencies :)

**Comment by Favorlock** [comment]
I understand that, but shouldn't grafana have a way of dealing with those recursive dependencies to prevent the page from completely failing to load to rectify those changes?

**Comment by RAHUL8491** [comment]
> I think the problem is that your variables depend on each other in a recursive way
> 
> $uuid is using $city in it's query
> $city is using $uuid in it's query
> 
> You cannot have recurive dependencies :)

Please suggest how to fix this. I made changes in variables as it was not updating the newly made changes. After saving the changes in variables of custom dashboard, it is not loading. The page says "Services" and show symbol of loading. Please help

**Comment by RAHUL8491** [comment]
> I understand that, but shouldn't grafana have a way of dealing with those recursive dependencies to prevent the page from completely failing to load to rectify those changes?

@Favorlock :-  Could you please help me if you were able to recover that dashboard. Or is there any way we can get the json file for that particular dashboard. Losing the custom dashboard just for nothing is not digestable. Please suggest steps to get over of this error.

**Comment by frenchviking** [comment]
@RAHUL8491 
I was in the same situation as you and did the following:

1. Request the /api endpoint to get the dashboard uid:
`curl -L -u "login:password" http://localhost:3000/api/search?query=My%20Dashboard%20Name`

2. Request the /api endpoint to get the dashboard json:
`curl -L -u "login:password" http://localhost:3000/api/dashboards/uid/[DASHBOARD_UID]`

3. Paste content to a text editor and:
3.1 Remove content before `{"annotations":`
3.2 Edit the templating part and fix/remove the circular dependencies
3.3 At the end of the json remove `"uid":"[DASHBOARD_UID","version":[DASHBOARD_VERSION]}}`

4. Copy and import to grafana.
5. Have a beer.
