### ISSUE TITLE
API Create Alert Error

### ISSUE THREAD

**Issue by taylord0ng** [grafana/grafana#55229]
**What happened**: I create grafana alert by HTTP API, if i post json with folderUID(folderUID is not exist), then alert create success, i can get alert by id, but it cannot display show grafana UI

**What you expected to happen**: I create grafana alert by HTTP API, if i post json with folderUID is not exist, it should show error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: 

**Environment**: 
- Grafana version: 9.0.8 9.1.5
- Data source type & version: prometheus
- OS Grafana is installed on: grafana docker image
- User OS & Browser: chrome
- Grafana plugins: no
- Others:

**Comment by mellieA** [comment]
@taylord0ng thanks for opening this issue, I ran into this earlier this week too. I think @JohnnyQQQQ might be working on it per the comment [here]( https://github.com/grafana/grafana/issues/55001#issuecomment-1243061393)

**Comment by grobinson-grafana** [comment]
Grafana doesn't check if the folder exist when creating an alert rule. @JohnnyQQQQ and I agree this is a bug and we will work on a fix!

**Comment by lado936** [comment]
This is still happening in version 10.1.2, is there any estimate when this bug will be fixed?
