### ISSUE TITLE
User's organization memberships lost after upgraded to 9.1.x

### ISSUE THREAD

**Issue by aitchjoe** [grafana/grafana#55248]
**What happened**:

After we upgraded Grafana from 9.0.5 to 9.1.5, if user logout and login again then they lost their organization memberships except public org. Turn on the debug log:

```
Sep 15 17:08:37 grafana01 grafana[1394617]: logger=login.ext_user t=2022-09-15T09:08:37.853942373Z level=debug msg="Removing user's organization membership as part of syncing with OAuth login" userId=6 orgId=11
```

and from [loginservice.go](https://github.com/grafana/grafana/blob/v9.1.5/pkg/services/login/loginservice/loginservice.go#L257) and [login_oauth.go](https://github.com/grafana/grafana/blob/v9.1.5/pkg/api/login_oauth.go#L260):

```
	if userInfo.Role != "" && !hs.Cfg.OAuthSkipOrgRoleUpdateSync {
```

We know how to fix it by set [oauth_skip_org_role_update_sync](https://grafana.com/docs/grafana/v9.0/setup-grafana/configure-grafana/#oauth_skip_org_role_update_sync) to `true`.

**Why happened**:

But why 9.0.5 works even not set `oauth_skip_org_role_update_sync`? Because we use GitLab as SSO Server, we compared these codes:

**9.0.5**
https://github.com/grafana/grafana/blob/v9.0.5/pkg/login/social/gitlab_oauth.go#L120
```
	role, err := s.extractRole(response.Body)
```
https://github.com/grafana/grafana/blob/v9.0.5/pkg/login/social/gitlab_oauth.go#L144
```
func (s *SocialGitlab) extractRole(rawJSON []byte) (string, error) {
	if s.roleAttributePath == "" {
		return "", nil
	}
```

**9.1.5**
https://github.com/grafana/grafana/blob/v9.1.5/pkg/login/social/gitlab_oauth.go#L117
```
	role, err := s.extractRole(response.Body, groups)
```
https://github.com/grafana/grafana/blob/v9.1.5/pkg/login/social/social.go#L314
```
func (s *SocialBase) extractRole(rawJSON []byte, groups []string) (models.RoleType, error) {
	if s.roleAttributePath == "" {
		if s.autoAssignOrgRole != "" {
			return models.RoleType(s.autoAssignOrgRole), nil
		}
		return "", nil
	}
```

So the login user has a default role (`autoAssignOrgRole)` when 9.1.5, but empty role when 9.0.5. And from loginservice.go [v9.1.5](https://github.com/grafana/grafana/blob/v9.1.5/pkg/services/login/loginservice/loginservice.go#L257) ([v9.0.5](https://github.com/grafana/grafana/blob/v9.0.5/pkg/services/login/loginservice/loginservice.go#L232) has almost same function):

```
func (ls *Implementation) syncOrgRoles(ctx context.Context, user *user.User, extUser *models.ExternalUserInfo) error {
	logger.Debug("Syncing organization roles", "id", user.ID, "extOrgRoles", extUser.OrgRoles)

	// don't sync org roles if none is specified
	if len(extUser.OrgRoles) == 0 {
		logger.Debug("Not syncing organization roles since external user doesn't have any")
		return nil
	}
```

So 9.0.5 "Not syncing organization roles" but 9.1.5 jump to "Removing user's organization membership".

**What you expected to happen**:

Even though we can config carefully (set `oauth_skip_org_role_update_sync`) to avoid this problem, but we think this issue need more attention, because it not only broken but also make data (`org_user` table) lost.

**Environment**:

- Grafana version: 9.0.5 Vs 9.1.5
- OAuth: GitLab

**Comment by Jguer** [comment]
Hi, there were some changes in the default behavior in some versions of 9.1.x, this was an unintended breaking change to align oauth integrations into being the source of truth for org role mapping. 

This has been reversed and the latest releases of 9.1.x and 9.2.0+ follow the old behavior of skipping org role sync if no mapping is found. 

This will be changed in Grafana 10 to follow the behavior described in the warnings [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/gitlab/#map-roles).

Sorry for unannounced change, we hope by Grafana 10 to have a solid and coherent configuration behavior for all auth integrations that will remain stable for the following versions
