### ISSUE TITLE
MySQL: Visual query builder doesn't update underlying query when filtering using a date.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#55247]
**What happened**:
When filtering using a date, changing the date does not update the underlying query.

**What you expected to happen**:
WHERE clause using the date column and date to be added.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new panel
2. Use a mysql datasource
3. flip the filter switch
4. select a datetime column
5. select a date in the calendar component

**Comment by zoltanbedi** [comment]
https://github.com/grafana/grafana/pull/58248#issuecomment-1305196013 I think you also missed the apply button at the bottom modal.
