### ISSUE TITLE
[Feature request] Enable templating to support function

### ISSUE THREAD

**Issue by rydeng** [grafana/grafana#5525]
Now I need to define three var like this,
$testFirst   (341/(287+mean("field1")))
$testSecond   (341/(287+mean("field2")))
$testThird   (341/(287+mean("field3")))
It is repetitions work, so is it possible to supply a function templating?
for example, 
$function1    (341/(287+mean("$field"))) ,
we can use $function1(a) express (341/(287+mean("a")))

**Comment by torkelo** [comment]
you should be able to do this now. what is stopping you from doing `$function1(341/(287+mean("$field"))) `?

**Comment by rydeng** [comment]
$function1 is my defined templating var, I want to use it like $function1(a) to present (341/(287+mean("a"))) or $function1(b) to present (341/(287+mean("b")))

**Comment by torkelo** [comment]
why not create a custom template variable with values like, `(341/(287+mean("b")))`, etc . 

The templating system is basically string replacement
