### ISSUE TITLE
Unified Alerting resolve notification sends wrong screenshot

### ISSUE THREAD

**Issue by MSommer95** [grafana/grafana#55253]
**What happened**: 
The unified alerting resolve notification sends the same screenshot that was sent in the firing notification.

**What you expected to happen**: 
Expected behavior would be a new screenshot of the moment the alert was resolved.

**Anything else we need to know?**: 
Telegram was used as a contact point.

**Environment**:
- Grafana version: 9.1.0
- Others: Grafana Renderer as Docker Container 3.5.0

**Comment by mellieA** [comment]
👋 @MSommer95 this should be resolved by PR https://github.com/grafana/grafana/pull/54793 with a posted milestone of 9.1.6
