### ISSUE TITLE
[Feature Request] Add button to build query with template

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5526]
Hi,

This PR: it's to add a button to build a "query" with template. 
 
For example on this graph http://play.grafana.org/dashboard/db/graphite-panel-repeats how to show a first graph with `$app="backend" + $server="backend_01"` AND a second graph with `$app="country" + $server="ZA"` on the same page ?

Currently it's not possible, so my idea it's to have a button something like that:
![send](https://cloud.githubusercontent.com/assets/15362041/16618180/493c696c-4388-11e6-87c7-a344c306fccb.png) 
When user click on Send button the first graph is `$app="backend" + $server="backend_01"`
For the second graph the user choose different params:
![send2](https://cloud.githubusercontent.com/assets/15362041/16618231/9591869e-4388-11e6-82da-cdb02bd58166.png)

Currently if you want these two graphs on same page, the problem is the param $app doesn't change:

![captureggrra](https://cloud.githubusercontent.com/assets/15362041/16618360/47e383ce-4389-11e6-9766-ceb2202cd7ad.PNG)

 Did you understand the FR ? Have you need more datails ? What do you think ?

**Comment by torkelo** [comment]
you can select backend and fakesite and select a webserver and a backend sever hand have them both show.
http://play.grafana.org/dashboard/db/graphite-panel-repeats?var-app=backend&var-app=fakesite&var-server=backend_01&var-server=web_server_01&var-interval=$__auto_interval

**Comment by Azef1** [comment]
I am not agree with you :)
Check my last screenshot, you could notice if I select backend and country and I select a backend server and a country code, the attribute $app doesn't change, it's always $app="backend" (in title dashboard , i show the attribute $app and $server).

Other example:
Go to http://play.grafana.org/dashboard/db/graphite-panel-repeats 
Change title of one dashboard to:  `App: $app AND Server: $server`
Select backend+fakesite AND backend_01+web_server_01

You notice the second dashboard doesn't work because $app=backend AND $server=web_server_01 does not make sense.
![captureaz](https://cloud.githubusercontent.com/assets/15362041/16726673/c11667f2-475d-11e6-8300-bc428f59fcb5.PNG)

**Comment by torkelo** [comment]
I am not sure I understand what you are talking about. First dashboard, second dashboard? Multiple dashboards??? 

When I have two values selected for app variable the title reflects that: 
<img width="699" alt="screen shot 2016-07-11 at 12 54 39" src="https://cloud.githubusercontent.com/assets/10999/16728459/afb3cb54-4766-11e6-8993-07110c6468e9.png">

http://play.grafana.org/dashboard/db/graphite-panel-repeats-copy

do you want to repeat a panel for both each selected app and each server?

**Comment by Azef1** [comment]
Thx for the link, the result corresponds what I want. 
To be precise: My goal is to have on **same** dashboard: first graph showing `backend with backend_01` and a second graph showing `fakesite with web_server_01`.

How did you do it ?  Have you modify something  in settings ? 

In JSON export i noticed only one difference:
Before (http://play.grafana.org/dashboard/db/graphite-panel-repeats)
```
          "resolution": 100,
          "scale": 1,
          "scopedVars": {
            "app": {
              "selected": true,
              "text": "backend",
              "value": "backend"
            },
            "server": {
              "text": "backend_01",
              "value": "backend_01",
              "selected": true
            }
          },
          "seriesOverrides": [],
          "span": 6,
```

After your edit (http://play.grafana.org/dashboard/db/graphite-panel-repeats-copy)
```
          "resolution": 100,
          "scale": 1,
          "scopedVars": {
            "server": {
              "text": "backend_01",
              "value": "backend_01",
              "selected": true
            }
          },
          "seriesOverrides": [],
          "span": 6,
```
