### ISSUE TITLE
Log the total number of DB queries for background services.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#55278]
In order to understand the performance impact of background services/jobs in Grafana we should log the total number of db queries and other outgoing call upon completion. If we suspect the service/job sometimes perform large number of queries/requests we should log the number of expected operation before as well as debug logs. 

For HTTP requests we store an int in the `ctx` that we inc on every database call. It should be possible to do something similar for alerting/reporting/clean up jobs. 

https://github.com/grafana/grafana/blob/main/pkg/middleware/logger.go#L38
https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/database_wrapper.go#L96
https://github.com/grafana/grafana/blob/main/pkg/middleware/logger.go#L69

**Comment by bergquist** [comment]
The same pattern can be used to count outgoing HTTP requests or other RPC calls

**Comment by armandgrillet** [comment]
We have added tracing to critical alerting paths which allows you to see the number of DB operations per alert evaluation.
