### ISSUE TITLE
[Feat]: Dashboard search, add explore links

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5528]
Link to links to dashboard repo

**Comment by torkelo** [comment]
Link in search popup:

![image](https://cloud.githubusercontent.com/assets/10999/16722214/6c67a1ca-4745-11e6-9bab-44b5191eef44.png)

Link on plugin list page:
![image](https://cloud.githubusercontent.com/assets/10999/16722249/8e047452-4745-11e6-8c7d-0a3892fcd019.png)

feedback?
@mattttt @nopzor1200

**Comment by mattttt** [comment]
Couple options for the dashboard picker:

![image](https://cloud.githubusercontent.com/assets/2886187/16734658/50563ca8-4754-11e6-8f8f-3bdb70c460a3.png)

![image](https://cloud.githubusercontent.com/assets/2886187/16734664/571d0ad0-4754-11e6-8e6d-b5d71d7bdd62.png)

**Comment by mattttt** [comment]
I like it a lot in the above, but like it less on the button. @bulletfactory, what do you think here:

![image](https://cloud.githubusercontent.com/assets/2886187/16735758/46bf133c-4758-11e6-96e2-6b58059b1a19.png)

**Comment by bulletfactory** [comment]
I agree - I like the wordmark (v2 that matt showed) in the dasboard picker,
but don't think it works as well at the top of the plugin section. It feels
like a new convention.
I might suggest the primary CTA that's text only, (like the add datasource,
for instance). Feels cleaner.

**Comment by torkelo** [comment]
Not sure about the "Get More", more what? Or maybe spelling it out is not needed. Like the "Explore" or "Discover" word and "ready made dashboards" , can maybe be shortened to "Explore complete dashboards", not sure about that either. "Explore reusable dashboards on .. "

**Comment by mattttt** [comment]
- Im cool with "[Explore/Discover/Find] more dashboards", whichever you prefer @torkelo. Just need to keep that text short, we definitely dont need a sentence CTA.

- For the list pages, we could do something like this and avoid taking the CTA space - in case we wantto use that at some point. 

![image](https://cloud.githubusercontent.com/assets/2886187/16738405/8403c034-4763-11e6-9931-657ce515e943.png)

**Comment by bulletfactory** [comment]
+1 - I like this version a lot.

**Comment by torkelo** [comment]
yea, having it next to the grid layout selector works great
