### ISSUE TITLE
Datasource: Setting cookie not possible

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#55290]
**What happened**:
We need to set a cookie for accessing a REST API through grafana.
We tried using the "simpod-json-datasource" or "marcusolsson-json-datasource" datasource plugins.

Adding the Cookie as Header (like it is for example possible in Icinga Director Datasources) like this:
![image](https://user-images.githubusercontent.com/124109/190604119-f774f228-c448-4fb6-a40d-e086f615140e.png)

results in the following log message:
`t=2022-09-16T11:18:40+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=2 orgId=1 uname=<removed> path=/api/datasources/proxy/27 remote_addr=<removed> referer=https://our.domain.net/grafana/datasources/edit/LB98An74k error="http: proxy error: net/http: invalid header field name \"Cookie: OURCOOKIE\""`

**What you expected to happen**:
Setting cookies should be possible as they may be required by some applications

**How to reproduce it (as minimally and precisely as possible)**:
1. add json datasource plugin (e.g. marcusolsson-json-datasource)
2. create datasource using Custom HTTP Headers with Header "Cookie: YOURCOOKIE"
3. Request fails with "JSON API: Bad Gateway" and above log message

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: marcusolsson-json-datasource 1.3.1 (also happens with other json datasources like simpod-json-datasource)
- OS Grafana is installed on: RHEL 7.9
- User OS & Browser: Windows & Chrome
- Grafana plugins: see datasource type

**Comment by mellieA** [comment]
@friesoft the marcusolsson-json-datasource and  simpod-json-datasource are created by our wonderful community members!  I'd recommend posting this in their repositories as an issue/feature request: 

https://github.com/marcusolsson/grafana-json-datasource
