### ISSUE TITLE
Table panel footer visual bugs in Safari/Firefox

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#55295]
**What happened**:
Table footer looks off on Firefox and Safari (possibly other browsers too). Tested on Grafana v8.5.4 and v9.1.5.

Firefox (seems to lack styling):
![Screenshot 2022-09-16 at 13 28 43](https://user-images.githubusercontent.com/36818606/190620607-53ad4ba2-d0f9-4731-8c2f-17b053c41154.png)

Safari:

https://user-images.githubusercontent.com/36818606/190620654-ddf27fe1-00ca-4add-a69f-908d2cc6329c.mov

**How to reproduce it (as minimally and precisely as possible)**:
Easily reproducible with any data in a table panel and the table footer option enabled.

**Comment by supilee** [comment]
Same behavior on Version 105.0.5195.125 (Official Build) (arm64)
