### ISSUE TITLE
[Feat]: Update Dashboard Apps

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5529]
Improve situation for updating dashboard apps

**Comment by torkelo** [comment]
App dashboards are now
- Automatically imported when app is enabled (dashboard table now have a plugin_id column to track dashboard -> app link)
- Automatically updated on startup when app version changed and dashboard revision changed
- When app is disabled all dashboards for this app are removed (**not** custom user copies)
- When saving a dashboard with a plugin_id link user will be presented with a warning that this app is part of app and will be automatically be updated on app update. The warning modal suggests you use Save As or you can ignore the warning. Save As will create a copy without the plugin_id link. 
- If you rename a dashboard in an app then the auto update code that runs on startup will detect this and remove the old dashboard and insert the new one (under the new name). This only works from now on as the clean up mechanic requires the plugin_id link. 

![image](https://cloud.githubusercontent.com/assets/10999/16722148/07a43136-4745-11e6-9042-af9404c09d32.png)


Potential issues: 
- App makers will have to be very careful about how they name dashboards so they will not conflict with users existing dashboards as these will be overwritten. The dashboard name should include app prefix. Why not only overwrite existing dashboards with plugin_id and ignore dashboards that already exist with the same name? Then this auto dashboard update sync will not have any effect on existing users of worldPing, kentik apps etc. 

@nopzor1200 @woodsaj @mattttt

**Comment by torkelo** [comment]
@mattttt 
![image](https://cloud.githubusercontent.com/assets/10999/16757395/0b1acf56-480c-11e6-8156-9330f950b0c0.png)

"The dashboard belongs to"  or "The dashboard is part of" ?

**Comment by bulletfactory** [comment]
My personal preference: "This dashboard is part of the plugin worldPing"

**Comment by mattttt** [comment]
"...is included with", then it reinforces the language on the app pages that says, "Includes"
