### ISSUE TITLE
Tempo: Traces to Metrics don't add a buffered time range

### ISSUE THREAD

**Issue by sherifkayad** [grafana/grafana#55317]
**What happened**:
Configuring Tempo Traces to Metrics doesn't result in a correct time range given to the Prometheus data source, thus using `$__rate_interval` doesn't seem to work properly as per the docs.

**What you expected to happen**:
The time range given by Grafana to the Prometheus data source should either be automatically buffered or allowing it to be configurable (similar to the `spanEndTimeShift` and `spanStartTimeShift` of the Traces to Logs functionality).

**How to reproduce it (as minimally and precisely as possible)**:
- Configure Traces to Metrics with a query e.g. `sum by (client, server)(rate(traces_service_graph_request_total{$$__tags}[$$__rate_interval]))` as a "Request Rate" query
- Fetch one of the existing traces from Tempo (using the search or search by ID)
- Click on the anchor to visualize the query

(also attached in the screen recording GIF)

**Anything else we need to know?**:
Nothing further ..

**Environment**:
- Grafana version: `9.1.5`
- Data source type & version: Tempo datasource
- OS Grafana is installed on: Kubernetes using Helm / data source provisioning using Kiwigrid Sidecar
- User OS & Browser: Windows / Chrome
- Grafana plugins: N.A.
- Others:

**Screenshots  / Recordings**:
![screen-capture (2)](https://user-images.githubusercontent.com/8362784/190677682-1518a154-8d08-4ebd-b9cd-bfd5f49bd072.gif)
<img width="733" alt="image" src="https://user-images.githubusercontent.com/8362784/190677934-f7f23924-b45c-4f5d-9fb0-67893d5d5841.png">

**Comment by sherifkayad** [comment]
I am wondering how is it working fine with buffered time ranges in this video here https://player.vimeo.com/video/740767700?h=d1190760df 🤔

**Comment by joey-grafana** [comment]
Closing as this will be covered in https://github.com/grafana/grafana/pull/55335

**Comment by sherifkayad** [comment]
@joey-grafana Thanks for the heads-up ;)
