### ISSUE TITLE
[Feature request] ability to control granularity of local snapshots

### ISSUE THREAD

**Issue by abraae** [grafana/grafana#5531]
Snapshots are awesome!

However zooming in to a snapshot is not as useful as I had hoped, since its clear the snapshot only stores aggregate data, not all the data within the date range. Fair enough, we don't want snapshots to be enormous, but is there any way I can specify a "minimum snapshot resolution"?

i.e. this snapshot should store data down to a 1s resolution?

**Comment by abraae** [comment]
Just to be clear I'd like to do it at the panel or dashboard level, not as a user choice when taking the snapshot :)

**Comment by torkelo** [comment]
no, snapshots are more a what you see is what you get situation, and will likely stay that way.
