### ISSUE TITLE
Linking to a dashboard of a different org only works on a new tab

### ISSUE THREAD

**Issue by guicaulada** [grafana/grafana#55326]
**What happened**:

When I create a link to a dashboard passing the orgId on the URL, even if I have access to such org, when I click the link and open it on the same tab I get a "Dashboard not found" message, but if I open the link on a new tab I don't have any issues.

**What you expected to happen**:

I expected to be able to link to dashboards of different orgs than the current one if I have access to those orgs and open the dashboards on the same tab, without requiring a new tab.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard on the main org
2. Create a new org
3. Create a dashboard on the new org
4. Add a text panel to the dashboard on the new org with a link to the dashboard on the main org
5. Click the link, it will fail to open on the same tab
6. Click the link with the hotkey to open a new tab pressed (most times it's CTRL), it works

**Anything else we need to know?**:

**Environment**:
- Grafana version: main(https://github.com/grafana/grafana/commit/5c66c412200b8f756851ef84da0a4130b9bbc16a)
- Data source type & version: Prometheus (prom/prometheus:latest) from devenv
- OS Grafana is installed on: macOS Monterey 12.6
- User OS & Browser: Chrome Version 105.0.5195.125 (Official Build) (arm64) on macOS Monterey 12.6
- Grafana plugins:
- Others:

**Comment by taleena** [comment]
I think we can specify that some links open in a new tab, we could double check if this behavior still persists even if that is selected. It does look like this was broken and fixed in the past: https://github.com/grafana/grafana/issues/24881

**Comment by guicaulada** [comment]
I think that issue might be related to the Panel Links feature:

![Screen Shot 2022-09-19 at 18 02 21](https://user-images.githubusercontent.com/7741292/191116203-58dd57b7-af33-48e1-ab62-67201a200339.png)

However functionality is the same, if the link doesn't open in a new tab it doesn't work, even if I have access to the org and dashboard linked.
