### ISSUE TITLE
[Feature request] make templateSrv.replace() able to return object

### ISSUE THREAD

**Issue by jifwin** [grafana/grafana#5532]
I'm using v3.0.4. Since version 3 Grafana supports custom format function for templating (templateSrv.replace). However its output is always casted to string, so returning array or object makes no sense.

templateSrv.js
`return target.replace(this._regex, function(match, g1, g2) {`

e.g.
`var target = "$rows";
undefined
target.replace("$rows",[1,2,3]);
"1,2,3"`

It would be nice to have an option to return an array or object, because some datasources (e.g. KairosDB) may like to have it in plain (not stringified) form. Right now, to put it back to object it is necessary to implement a hack (see https://github.com/grafana/kairosdb-datasource/issues/14).

**Comment by torkelo** [comment]
what you are looking for is something else than templateSrv.replace, templateSrv replace is an interpolation function, which takes a string and returns a string, that is the basis for the templating system, string interpolation. 

what you are looking for is a new function
