### ISSUE TITLE
[Feature request] Tell CLI to install specific version of a grafana plugin

### ISSUE THREAD

**Issue by mhenderson-so** [grafana/grafana#5533]
* **I'm submitting a ...**
- [x] Feature request

Tangentially related to [feature request 4823](https://github.com/grafana/grafana/issues/4823), we would like to be able to tell `grafana-cli` the version number of a specific plugin to install.

This is important for reproducible environments via config management, such as puppet. Otherwise deploying a new grafana instance may install a different plugin version to existing grafana instances, if the existing instances have not been updated.

This is related to request 4823, as if we could install from an official git path, the version number could be related to a release that's got a tag of that version number in the git repository.

**Comment by DanCech** [comment]
This would be very useful

**Comment by mhenderson-so** [comment]
This functionality has been merged in #5665
