### ISSUE TITLE
graph is overriding legend when using a 'group by' greated than $interval

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#5534]
* **I'm submitting a ...**
- [ X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using : 3.1 beta
- What datasource are you using? Influxdb 0.13
- What OS are you running grafana on? : Debian
- What did you do? Weather mettering with max/min on 12 hours to display a tunneled value
- What was the expected result? The graph should not override the legend on the left
- What happened instead? The graph overrides the legend on the keft

See:

![grafana](https://cloud.githubusercontent.com/assets/2684878/16670308/f214d4f4-4499-11e6-9580-215e65bff8fe.png)

**Comment by torkelo** [comment]
related to render bug with fill below to, https://github.com/grafana/grafana/issues/4243
