### ISSUE TITLE
Plugin grafana-swis-datasource-develop not compactible on Grafana 9. Same plugin was working fine in version 6. 

### ISSUE THREAD

**Issue by Karthick31** [grafana/grafana#55356]
**What happened**: Plugin grafana-swis-datasource-develop not compactible on Grafana 9. Same plugin was working fine in version 6.

**Comment by mellieA** [comment]
👋 @Karthick31 I was going to refer you to the plugin developer, but I see you already opened the issue there. Have a great weekend!
