### ISSUE TITLE
Make the dtos package self-contained

### ISSUE THREAD

**Issue by avaskys** [grafana/grafana#5535]
- [x] Feature request

It would be nice to use the dtos package (in pkg/api/dtos) in order to communicate with grafana over its HTTP API from other go binaries. Unfortunately, models.go imports github.com/grafana/grafana/pkg/models, which in turn brings in a slew of dependencies. Ideally we'd be able to use the dtos package without having to bring in any additional libraries.

Please include this information:
- What Grafana version are you using? master
- Other questions: N/A

**Comment by daniellee** [comment]
We are planning to build and maintain a go client for Grafana. In the meantime, you can use this: https://github.com/grafana/grafana-api-golang-client
