### ISSUE TITLE
Glue: Query Editor for target query

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55369]
Create new UI elements displayed when adding or editing a correlation entry:
* Target Field
* Target Query Editor

<img width="1431" alt="Screen Shot 2022-09-19 at 12 15 54" src="https://user-images.githubusercontent.com/745532/190996767-d0497c14-6a39-484f-97b8-01b0081bd912.png">

When a correlation is added/edited the _target field_ and _target query_ should be saved using new API methods defined in #55368.

The editor should be reloaded when target data source is changed.

Target field is a static text input (once we get results from a sample source query it will be changed to a dropdown).

**Comment by gelicia** [comment]
Validation outside of the validation the query editors provide is out of scope for this ticket.
