### ISSUE TITLE
logs: evaluate if we should create a storybook-like thing for logs components

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#55363]
the logs visualization components were moved from `grafana-ui` to `grafana` in https://github.com/grafana/grafana/pull/55041 .

we had the idea that maybe it would make sense to have some kind of compoenent-gallery (storybook style) for these components...we are not sure, so this is about evaluatiing if it makes sense.

some questions:
- are the react-components in the `logs/components` folder independent enough to be used from outside the `logs/components` folder, or are they mostly internal components of other `logs/components` react components
- is there such a widget-gallery thing already for "main grafana" react components?

**Comment by matyax** [comment]
We don't think this is really necessary right now.
