### ISSUE TITLE
Azure Monitor: Allow selection of multiple resources of the same type

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#55372]
Related discussion https://github.com/grafana/grafana/discussions/41807

# Goal

Azure Portal supports to select multiple resources in the same query, depending on the service, there are different requirements:

- For metrics ([docs](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-dynamic-scope)): Only resources of the same type, subscription and location can be selected.
- For logs ([docs](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/scope#query-scope-limits)): The requirements are more flexible, all resources of the same type can be queried, regardless of its subscription or location. Azure documentation alerts about requests that query multiple workspaces because the performance gets severely affected.

# API Specifics

## Azure Monitor Metrics

For metrics, we use the [Metric List API](https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list). At the moment, we use the full resource URI of the resource we want to monitor. For example:

```go
Method: GET
Host: "management.azure.com"
Path: "/subscriptions/<subID>/resourceGroups/<rg>/providers/<ns>/<resource>/providers/microsoft.insights/metrics"
Params: 
 - "aggregation=Average"
 - "api-version=2018-01-01"
 - "interval=PT1M"
 - "metricnames=Percentage+CPU"
 - "metricnamespace=ns"
 - "timespan=ts"
```

From there we can remove the resource ID from the URL and use a `$filter`, matching multiple resources:

```go
Method: GET
Host: "management.azure.com"
Path: "/subscriptions/<subID>/providers/microsoft.insights/metrics"
Params:
 - "region=northeurope"
 - "$filter=Microsoft.ResourceId eq '/subscriptions/<subID>/resourceGroups/<rg>/providers/<ns>/<resource1>/providers/microsoft.insights/metrics' or Microsoft.ResourceId eq '/subscriptions/<subID>/resourceGroups/<rg>/providers/<ns>/<resource2>/providers/microsoft.insights/metrics'"
 - "aggregation=Average"
 - "api-version=2018-01-01"
 - "interval=PT1M"
 - "metricnames=Percentage+CPU"
 - "metricnamespace=ns"
 - "timespan=ts"
```

**Note**: It may be possible to do a POST request, including the filter in the body so we don't reach limits in the URL size.

- Pro: Only one request, likely faster than doing multiple requests since the processing is made in Azure's side
- Con: We need to specify a region to do this, which is not part of the data that we handle at the moment

**Note**: Not all resource types are supported for multi-resource queries. At the moment this is the list of types supported:

![Screenshot from 2022-09-28 13-33-55](https://user-images.githubusercontent.com/4025665/192769065-a0ac965b-da89-4143-8042-bea053d8936e.png)

As far as I can see, there is not an API in which this information is available so we would need to hardcode the list for the moment.

Apart from that, we need to add some post-processing of the result. We either need to return a wide frame (single timestamp, multiple values) or multiple frames.

## Azure Monitor Logs

For logs, there are two (similar) APIs that we use to retrieve metrics:

 - [Query - Execute](https://learn.microsoft.com/en-us/rest/api/loganalytics/dataaccess/query/execute) for workspaces (deprecated).
 - [Query - Execute](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/azure-resource-queries) for resources.

In the case of workspaces (which we avoid), the API documentation mentions the `workspaces` parameter that you can specify for querying multiple workspaces. Even though the analogue thing is not documented for the `resources` case, I have checked that queries made in the Azure portal set this parameter when requesting multiple values.

```
Method: POST
Host: "api.loganalytics.io"
Path: "/v1/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/virtualMachines/<rn>"
Body:
  query: ...
  resources: [
    "/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/virtualMachines/<rn>",
    "/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/virtualMachines/<rn2>",
  ]
```

TBD: It seems that it's necessary to set a resource ID in the URL even though the real list is in the POST body so we need to double check if that's really needed.

As in the metrics case, it's necessary to do some post-processing to transform the different values into frames.

## Multi-value template variables

_EDITED: Jan 24, 2023_

One of the requests of https://github.com/grafana/grafana/discussions/41807 is to able to select multiple resources for the template variables that resolve resource groups and names. For supporting multiple resource names, there is no major problem, we only need to generate multiple values, based on the same resource group. In the case of multiple resource groups, it's not possible to use them to obtain resource names using a single template variable. This is because the function that return resource names only stores the name, instead of the full resource ID so the resource group information is lost. The only possibility for supporting multiple resource groups would be using multiple template variables.

Another problem with template variables is that we cannot apply the limitations of the different APIs, for example, we wouldn't limit that the returned resources are in the same region, which is a requirement for Azure Monitor metrics. We can add more filters to help (like filtering by region) with this but it won't ensure that the queries are valid.

Another limitation would be cascading variables. For example, for retrieving metric names, it's necessary to specify a resource group and name (along with other parameters). Since the combinations would grow exponentially if each of those parameters can contain multiple values, and most of the combinations would be invalid results, only one value can be used to resolve resource groups, metric namespaces and metric names.

## Query Models

The internal query models can use some adaptation. We could reuse the current format, to avoid breaking changes (and the need of migration code), and encode multiple resources as a comma-separated list (one single string) but this has the disadvantage that the API would have singular names (e.g. `resourceName`) when the value may contain several values.

We can deprecate that value and a new plural for the values that we allow multiple resources. If the deprecated field (e.g. `resourceName` is used, it's trivial to migrate it to the new list format). A template variable containing multiple values, should be resolved in the frontend, and transformed to a list to be properly processed in the backend.

Apart from that, for Azure Monitor metrics, we will need to add a new parameter to specify the region of the resource(s):

```patch
+type AzureMonitorResource struct {
+       ResourceGroup string `json:"resourceGroup"`
+       ResourceName  string `json:"resourceName"`
+}
+

 // AzureMonitorJSONQuery is the frontend JSON query model for an Azure Monitor query.
 type AzureMonitorJSONQuery struct {
        AzureMonitor struct {
@@ -117,8 +122,10 @@ type AzureMonitorJSONQuery struct {
-               ResourceURI string `json:"resourceUri"`
+               ResourceURIs []string `json:"resourceUris"`
                // These are used to reconstruct a resource URI
                MetricNamespace string `json:"metricNamespace"`
                CustomNamespace string `json:"customNamespace"`
                MetricName      string `json:"metricName"`
-               ResourceGroup   string `json:"resourceGroup"`
-               ResourceName    string `json:"resourceName"`
+               Region          string                 `json:"region"`
+               Resources       []AzureMonitorResource `json:"resources"`

                Aggregation      string                        `json:"aggregation"`
                Alias            string                        `json:"alias"`
@@ -133,6 +138,8 @@ type AzureMonitorJSONQuery struct {
 
                // Deprecated, MetricNamespace should be used instead
                MetricDefinition string `json:"metricDefinition"`
+               // Deprecated: Use Resources with a single element instead
+               AzureMonitorResource
+               // Deprecated: Use ResourceURIs with a single element instead
+               ResourceURI string `json:"resourceUri"`
        } `json:"azureMonitor"`
```

For Logs, we will need a similar change, deprecating the single resource and adding a plural:

```patch
 type LogJSONQuery struct {
        AzureLogAnalytics struct {
-               Resource     string `json:"resource"`
+               Resources    []string `json:"resources"`
                Query        string   `json:"query"`
                ResultFormat string   `json:"resultFormat"`
 
                // Deprecated: Queries should be migrated to use Resource instead
                Workspace string `json:"workspace"`
+               // Deprecated: Use Resources with a single element instead
+               Resource string `json:"resource"`
        } `json:"azureLogAnalytics"`
 }
```

## UX

Following the API limitations, when opening the resource picker, it should allow to select multiple resources, informing about the limitation of the API (different for metrics and logs):

![Screenshot from 2022-09-28 13-08-44](https://user-images.githubusercontent.com/4025665/192764788-028dd749-6b71-4993-91ee-e3eb5072417c.png)

The "Advanced" section should allow you to display, edit and add or remove elements. We can achieve that using a list.

![image](https://user-images.githubusercontent.com/4025665/193012507-6f1d7d98-cbe1-4b61-b34b-4e9aab8eb519.png)

![image](https://user-images.githubusercontent.com/4025665/193012588-43ce40ca-2cd3-4890-9180-851f49236a72.png)

Once the modal is closed, a comma-separated list of resources will be shown in the specific field:

![Screenshot from 2022-09-28 14-51-51](https://user-images.githubusercontent.com/4025665/192783156-1f30efeb-19d7-4ac0-923f-f5b424a4deca.png)

# Task list

In order to help with implementation, prioritization and the estimation of the work, we can divide this issue in multiple tasks. We can also divide between tasks that allow us to have feature parity with the Azure portal and additional feautres (UX only available in Grafana):

To achieve feature parity:
- [x] #56102
- [x] #56103
- [x] #56104
- [x] #56105
- [x] #56106
- [x] #62299

To also add support for multi-value variables:
- [x] #62017
- [x] #56108
- [x] #56109
- [x] #56110
- [x] #56111

Misc:
- [x] #62457
- [ ] #62331

**Comment by aangelisc** [comment]
Great overview on this issue! Looking forward to working on implementing this. One question I have (potentially a silly one):

>The internal query models could use some adaptation but to avoid breaking changes (and the need of migration code), we can encode multiple resources as a comma-separated list (one single string). This has the disadvantage that the API would have singular names (e.g. resourceGroup) when the value may contain several values and that it does not enforce that the number of resource groups is equal to the name of resource names.

I'm unsure of how we'd implement this without changing the query model in some way. We would need a way of tying resource group -> resource which arrays wouldn't allow us to do. Unless we're planning on relying on order in the array but this feels like it could be brittle (and may cause some issues with template variables).

**Comment by andresmgot** [comment]
thanks for the feedback @aangelisc ! I have added a new section "Multi-value template variables" and updated the models section to reflect changes.

I have also added a section at the end with a list of tasks and rough estimations
