### ISSUE TITLE
Ability to use template variables in InfluxDB retention period field

### ISSUE THREAD

**Issue by zp-markusp** [grafana/grafana#5537]
* **I'm submitting a ...**
- [ ] Bug report
- [ x ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0
- What datasource are you using? Influxdb
- What OS are you running grafana on? CentOS

As user I would like to have the ability to use a template variable to select a different retention policy for a given query.
Use case: I would like to use the same dashboard for fine granular time resolution as well as for long term trends.
I basically works in manual editing mode, but switching the the normal query mode removes the variable again.

![image](https://cloud.githubusercontent.com/assets/6648693/16686109/17fd4c20-4510-11e6-8e79-bbb8eacc9a3b.png)
![image](https://cloud.githubusercontent.com/assets/6648693/16686119/2d3b957e-4510-11e6-9420-175df430d074.png)

**Comment by torkelo** [comment]
have you tried it? It should work, just manually specify a template variable `$varname` in the policy selection field

**Comment by zp-markusp** [comment]
you are right, works if you enter in manually... I was just confused that it's the only field there which doesn't offer the dropdown of template variables
