### ISSUE TITLE
Elasticsearch: Rename public/app/plugins/datasource/elasticsearch/language_provider.ts to follow convention

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#55382]
**Level: easy**

Some files that are maintained by logs squad have snake_case name. According to convention https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions we should use:
- `camelCase` when the primary export is a function
- `PascalCase` when the primary export is a class or React component. 

Rename following files  in `grafana/grafana` to follow the above-mentioned convention:
- `public/app/plugins/datasource/elasticsearch/language_provider.ts`
- `public/app/plugins/datasource/elasticsearch/language_provider.test.ts`

**Comment by mvsousa** [comment]
Hi @ivanahuckova 
Im new into open source projects and I would like to contribute to grafana, since its a tool very used for my company and my team

Can I tackle this issue ? :)
