### ISSUE TITLE
SubQuery

### ISSUE THREAD

**Issue by POorzech** [grafana/grafana#5538]
I have problem with subquery syntax.
The query : 
 SELECT mean("OLT_OltLaserTemperature_C") FROM "PonMeas" WHERE "OLT_IpAddress" = **'SELECT "OLT_IpAddress" FROM "OntStatusMeas" WHERE "OLT_OntSerialNumber"=~ /$serial_number$/'** AND $timeFilter GROUP BY time($interval) fill(null)

If I set OLT_OntSerialNumber as a exact number e.g. 485754434F606D21 I have such error : "error": "error parsing query: found 485754434, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 2, char 155".

**Comment by torkelo** [comment]
I guess you are using InfluxDB? Please open issue with that project as the error is relating to the InfluxDB query syntax

**Comment by POorzech** [comment]
Yes. Could you tell me if influxDB supports subqueries.

2016-07-08 15:31 GMT+02:00 Torkel Ödegaard <notifications@github.com>:

**Comment by torkelo** [comment]
It does not. If you want subqueries I suggest Graphite.

**Comment by deric** [comment]
FYI: as of InfluxDB 1.2 [subqueries are supported](https://github.com/influxdata/influxdb/issues/4619).
