### ISSUE TITLE
[Bug] Shared tooltip with constantLine metric doesn't show correct timestamp

### ISSUE THREAD

**Issue by zachd** [grafana/grafana#5539]
Grafana 3.0.4, using Graphite datasource.

When a constantLine is used on a graph panel, the shared tooltip only shows the timestamp of a single datapoint on the line, and not and timestamps for other metric data. Image showing the problem attached below. Not sure if this is related to the other issue with shared tooltips and Influx.

![oaspzdmo0q](https://cloud.githubusercontent.com/assets/1366937/16691408/8d7fafe2-4524-11e6-9a3f-5b907047bc0f.gif)

Kind regards,
Zachary (Hosted Graphite)

**Comment by torkelo** [comment]
I don't think constantLine is working 100% with the json renderer  (not returning values are regular intervals)

**Comment by zachd** [comment]
Looks like if the `office.*.*.temperature` metric is moved below the constantLine in the metric list then the correct timestamps are shown.

**Comment by torkelo** [comment]
I mean the graphite json response is only returning 2 values for a contantLine (start and end) no values in between

**Comment by torkelo** [comment]
the all values tooltip has issues when the time series do not align on points (different resolution, missing data etc)

**Comment by zachd** [comment]
Is there scope for fixing this? Any other related PR? 
Thanks

**Comment by torkelo** [comment]
There is an open issue for improving all series tootip, but to truly fix this I think  constantLine needs to return more data points,  so needs to be fixed graphite api

**Comment by zachd** [comment]
Alright, thanks. A fix in the meantime is to put constantLine as the first metric in metric list and other metrics after as explained above.
