### ISSUE TITLE
invalid datasource name in localstorage causes explore to crash

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#55392]
how to reproduce:
- open the explore-page
- open the browser-devtools, find in localstorage this key: `grafana.explore.datasource.1` , and change it's value to something invalid, like `hehe`.
- now open the explore-page in your browser, but make sure there is no query-string, i mean open directly this URL : "http://localhost:3000/explore"

the webpage will show an empty explore-section, in the console you get the error message `ExplorePaneContainer.tsx:121 Uncaught (in promise) {message: 'Datasource ... was not found'}`

(i had this error when i deleted some datasources locally, i assume the default-datasource was one that i deleted)

**Comment by Elfo404** [comment]
@gabor i'm not really able to reproduce this, i always end up with the `-- Grafana --` Datasource in explore. I also tried creating a new datasource, setting it as default and deleting it.

are you on main? any other thing that could've made it heppen?

**Comment by gabor** [comment]
i'll go back and do it again, and give you the commit number.. oh, one thing maybe important, i do not have the mixed-datasources-thing enabled.

**Comment by Elfo404** [comment]
also tried with that disabled :(

**Comment by gabor** [comment]
ok, we can close this, it got fixed yesterday 😁  in https://github.com/grafana/grafana/pull/55055 , so thanks @gelicia for fixing this 👍 

it seems there was another bugreport about this at https://github.com/grafana/grafana/issues/54749

**Comment by Elfo404** [comment]
totally forgot about that! 🤦 

sorry!
