### ISSUE TITLE
Pubdash: investigate clickhouse not working

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#55409]
Report that public dashboards weren't working with the Clickhouse datasource. The plugin json has `true` for both backend and alerting, so we should look into it.

https://github.com/grafana/grafana-partnerships-team/issues/360

**Comment by Divulcan** [comment]
I made a support ticket with more information and a way to replicate the issue. **Ticket #6261**; I hope that helps 🦥

**Comment by owensmallwood** [comment]
@Divulcan Is that the right link to the ticket?

**Comment by Divulcan** [comment]
@owensmallwood Ooops. #62611 that's the right ticket number, apologies for that.

**Comment by owensmallwood** [comment]
Looks like issue for this is related to auth headers required for Cloudflare, which is still being investigated. Confirmed public dashboards are working with the Clickhouse plugin and the Altinity plugin with a Clickhouse datasource. I'm going to close this and let this specific issue be handled through the support ticket.
