### ISSUE TITLE
[Bug] Graphite metrics query fired for every keypress for first metric box

### ISSUE THREAD

**Issue by zachd** [grafana/grafana#5540]
Grafana 3.0.4, Graphite datasource.

On a new dashboard, when adding a metric and typing in the first field, a Graphite metrics query with `?query=*` is fired for every keypress, until one response returns back 200 and the metric paths are cached. This can be seen in the image attached. It seems like once the metric query is successful, only the first keypress on subsequent boxes fires off the next `.*` request.

![rvtszdivde](https://cloud.githubusercontent.com/assets/1366937/16692142/682cb840-4527-11e6-8159-7d903a698db3.gif)

Kind regards,
Zachary (Hosted Graphite)

**Comment by torkelo** [comment]
Strange, I cannot replicate this in master, or in 3.1-beta1 nor in 3.0.4

**Comment by torkelo** [comment]
oh, misse the fact that the query is not returning
