### ISSUE TITLE
[Feature request] Add "include zero" to graph Y-axis

### ISSUE THREAD

**Issue by kipe** [grafana/grafana#5541]
* **I'm submitting a ...**
* [ ] Bug report
* [x] Feature request
* [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:

* What Grafana version are you using? 3.0.4
* What datasource are you using? Influx DB 0.13
* What OS are you running grafana on? Linux

When drawing graphs currently the only possible way to control the Y-axis is to set value limits or use automatic limits. While this is enough for most use cases, it would be nice to have a feature to always include zero to the Y-axis.

For example, when viewing a graph with positive values it's quite normal to set Y-min to 0. By setting this, the graph can be "normalized" to always include 0 value. However, when there are some points in which the value is below zero, the values are lost from the graph with this solution.

Couple screencaps to demonstrate the issue:
[without Y-min, only positive values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero1.png)
[without Y-min, a few negative values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero2.png)
[Y-min = 0, only positive values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero3.png)
[Y-min = 0, a few negative values](https://kipe.kapsi.fi/rnd/grafana_issue/include_zero4.png)

The logic of "include zero" as pseudo-code:

```js
if (include_zero) {
if (min(y) > 0) {
y_axis_min = 0;
}
if (max(y) < 0) {
y_axis_max = 0;
}
}
```

**Comment by mgaugusch** [comment]
I'd also really like to see this implemented, especially for temperature graphs (which may include values less than zero in my area)
