### ISSUE TITLE
Feature Request: Basic Comma Separation Unit type

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#5542]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

This was previously requested in #2082 and was said to have been done in #1910 but #1910 was only for currency and not the three digit comma separation.  This would make many of our metrics and graphs a lot more readable.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/4252
