### ISSUE TITLE
Trace visualiser can pick the same colour for different services within a trace

### ISSUE THREAD

**Issue by hedss** [grafana/grafana#55431]
**What happened**:
Trace diagrams for two different services (denoted as two different names in the `service.name` resources for the spans) used the same colour for all spans. See attached screenshot.

![image](https://user-images.githubusercontent.com/8259026/191138238-964c7be2-1529-4329-a6fb-1d4830912779.png)

**What you expected to happen**:
Each different service identified by the `service.name` span resource should show spans in a different colour.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, this is not easily reproducable, as other traces with different services did show unique colours for spans from those different services.

Ideally the trace visualising code should ensure that colours picked are sufficiently different as to be independently distinguishable.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Cloud - v9.1.5-0100a6a (0100a6aa96)
- Data source type & version: Grafana Cloud Traces/Tempo
- OS Grafana is installed on: N/A
- User OS & Browser: MacOS, https://www.whatsmybrowser.org/b/YHLEX
- Grafana plugins: Standard GC plugins
- Others:

**Comment by joey-grafana** [comment]
Each color is based on the hash of the service.name in the span. 

Idea 1
To ensure colors are different we disallow using a color a second time, although we only have about 55 colors to use - so we could also factor that in i.e. don't reuse colors unless we have used all of them.

Idea 2
Don't use the same color for sequential spans. So at least if a color is repeated for spans the spans wont be one after the other.
