### ISSUE TITLE
Grafana Kairosdb Top N rows

### ISSUE THREAD

**Issue by gitvegas** [grafana/grafana#5543]
When Grafana pulls the data it shows all the rows returned by the query, so can we have a UI option where we can choose the number of rows we want to see under the graph. I use Kairosdb with Grafana, cheers

**Comment by torkelo** [comment]
Please open KairosDB issues in the kairosdb repo 
https://github.com/grafana/kairosdb-datasource

**Comment by gitvegas** [comment]
Im requesting this feature for Grafana UI, to simply have a setting, something like RowLimit where one can provide a number based on how many rows they want to show under the graphs.

Having an API call option to query Kairosdb with a limit option is also a good feature, sure will request this with Kairosdb guys, cheers
