### ISSUE TITLE
Tooltips are incorrect on influxDB2.3 and Flux.

### ISSUE THREAD

**Issue by tatsutaigu** [grafana/grafana#55433]
**What happened**:
![image](https://user-images.githubusercontent.com/44219065/191188412-fe3211a1-35d1-464a-8806-1e9c844d0967.png)

Tool tips are incorrect on Time Series plugin.
I did not check other plugins.

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/44219065/191188055-930742c6-a842-4a40-8f72-3c462c4c57d9.png)

Tool tips shows above label, I want
Tool tip label should show without `{id="1401", name="DPS310"}`

**How to reproduce it (as minimally and precisely as possible)**:
1. input below 3 data to influxDB.
```
DPS310,id=1401 temperature=20.2,pressure=1013.1,rssi=-40
DPS310,id=1402 temperature=21.4,pressure=1013.5,rssi=-45
DPS310,id=1403 temperature=23.7,pressure=1012.8,rssi=-50
```
Two or more series are required for this issue to occur.
So, I set id=1401 to 1403.

2. use Time Series plugin.
3. add query as below.
``` 
from(bucket: "my_bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "DPS310")
  |> filter(fn: (r) => r["_field"] == "temperature")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
```

**Anything else we need to know?**:
    Panel -> Inspect -> JSON is as below.
[Inspect_JSON.txt](https://github.com/grafana/grafana/files/9604696/Inspect_JSON.txt)

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: influxDB 2.3 + Flux
 InfluxDB v2.3.0+SNAPSHOT.090f681737 (git: 090f681737) build_date: 2022-06-16T19:33:50Z
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: windows 10
- Grafana plugins: Time series
- Others:

**Comment by oscarkilhed** [comment]
This isn't an issue with time series.

You can change the display name of the series by creating an override for the field name like this:

![image](https://user-images.githubusercontent.com/468940/193788417-73476e33-697c-4376-8024-2c38c4f5cc26.png)

**Comment by tatsutaigu** [comment]
@oscarkilhed 
Thank you so much!
