### ISSUE TITLE
auto time resolution down to the millisecond (and beyond)

### ISSUE THREAD

**Issue by robjk** [grafana/grafana#5544]
Hi,

I'm submitting a Feature request.  It is similar/duplicate of: https://github.com/grafana/grafana/issues/1231 but that appears to be closed.

Grafana: 3.0.3 (docker-hub image, can't upgrade to 3.0.4 yet by the looks of things)
InfluxDB: 0.13

My time series are stored at millisecond and microsecond resolution.  If I "group by time(10ms)" then I can see finer detail than if I leave the default "group by time(auto)".

Would it be possible to allow the calculated 'auto' value to go down to the millisecond range (or beyond)?  It seems like there is a minimum cut-off used.

Generally speaking auto works just fine but when anomalies in visualization occur (missing points on the graph as points cluster within the calculated 'auto' range), zooming in doesn't help find them.

At the moment I've made a clone of the dashboard with time(10ms), but that's only really useful over a 5 min window before the number of points grafana gets back overwhelms the browser.

All that aside, grafan has been a revelation, extremely impressive how quickly I've been able to pull the bits together and crack on with the actual problems at hand rather than worrying about visualization.  Keep up the good work.

Cheers,
Rob

**Comment by torkelo** [comment]
It seems to work in 3.1-beta1  tested on http://play.grafana.org/dashboard/db/influxdb-issue-5544?panelId=1&fullscreen&edit

Generates query with group by time 10ms when zooming in

**Comment by ckatsulis** [comment]
Has anyone been able to get the auto interval selection (`$__interval`) to move below the 10ms level.

I need to have more defined zooms return the periodicity to the 1us level.  Currently fractional ms levels supplied in the min grouping don't return an error, but still limit the grouping to 10ms chunks.

Please let me know if there is something that can be done on this issue.
