### ISSUE TITLE
Grafana Kairosdb Top N rows

### ISSUE THREAD

**Issue by gitvegas** [grafana/grafana#5545]
When Grafana pulls the data it shows all the rows returned by the query, so can we please have a query option with something like RowLimit? So we can only show limited number of rows on Grafana unlike now it just gets and shows everything.

I have also requested a UI option with Grafana guys where we can choose the number of rows we want to see under the graph, cheers

**Comment by torkelo** [comment]
this is the responsibility of the query backend (in your case KairosDB), 

dupe https://github.com/grafana/grafana/issues/5543
