### ISSUE TITLE
Explore: Improve query imports flow

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55462]
The current implementation of query imports in Explore may cause problems like the one described in #52213.

This task requires a design doc but the gist is:

* The query import that is happening asynchronously should be canceled if the query was updated by the editor
* There should be some visual feedback that the query was not imported (should be rare case)

Some known-unknowns to be covered by the design doc / investigation:
* There's no way to distinguish user input changes and some automatic changes fired by the editor. We need to check if editors do not call `onChange` automatically with an empty query after loading (e.g. filling in some defaults).  Such behavior may cancel importing the query even though the user didn't change it. Also `onChange` may be called during the import.
  * Note: `onChange` seems to be [triggered by Elastic when the editor is loaded](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/components/QueryEditor/ElasticsearchQueryContext.tsx#L63).
* It should be tested with mixed and non-mixed data sources.

<details><summary>Scratchpad</summary>

We need to find a solution that would mitigate such problems. Possible options to consider:

* Make query imports synchronous 
* Do not import the query if the query changes while importing is in progress 
* Add an overlay to the query editor while the queries are being imported between data sources, letting the user know that something is happening. Maybe have a x second timeout on it or a message about what is happening with the ability to cancel the import in case that is not important to the user. 
* Do not import automatically in Explore but rather provide the abstract query to the editor so it can decide how to handle it.
* Do not import the query if it was changed during the conversion. 
</details>

Please re-test the scenario described in #52213 when this is complete.

More details are in [the design doc](https://docs.google.com/document/d/1n4niEjlB8cpfb4omzhHidc8XNHIQN0rixALDK9RrsTQ/).

**Comment by ifrost** [comment]
> Make query imports synchronous

Probably worth keeping it async so it's easier to externalize (for example via API calls)

> Do not import the query if the query changes while importing is in progress

It'd reflect more of what's happening (i.e. the editor is not ready to be used before the import)

> Add an overlay to the query editor while the queries are being imported between data sources, letting the user know that something is happening. Maybe have a x second timeout on it or a message about what is happening with the ability to cancel the import in case that is not important to the user.

 An improvement over the previous but may be annoying if the action takes too long

> Do not import automatically in Explore but rather provide the abstract query to the editor so it can decide how to handle it.

That would require handling imports in each editor separately 

> Do not import the query if it was changed during the conversion.

Feels like the most reasonable version, we can also provide some visual feedback that the query is being imported + if user manually changes it info that the import was canceled.

**Comment by Elfo404** [comment]
also to me last option seems the most reasonable. and i agree that we should provide some visual feedback that something is happening / import process is cancelled. 👍

**Comment by ifrost** [comment]
Moved to https://github.com/grafana/grafana/issues/62747
