### ISSUE TITLE
Option to share live dashboard

### ISSUE THREAD

**Issue by klausenbusk** [grafana/grafana#5547]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request
Grafana version: 3.1.0-beta1
Datasource: Prometheus 0.20
OS: Grafana docker image on Coreos latest stable

Hello

The share snapshot option is useful, but I think a option to share a live dashboard will be even more useful.

Two use-case:
* You want to display your Dashboard on some sort of "digital signage box"/"Linux kiosk" and don't want to login everytime.
* You want to share a dashboard with a customers and don't want to create org/user (which is a mess if you have a lot of customers).

My idea was a API like:
```
POST /api/dashboards/db/:dashboard/share HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "dashboard": {
    "editable":false,
    "hideControls":true,
    "templating":{
      "list":[
      ]
    },
  "expires": 3600
}
```
The idea with templating, is that you could overvride a template value.
For example we use a slight modified version of this dashboard: http://play.grafana.org/dashboard/db/prometheus-demo-dashboard , and it would be preferable if we could override the "$node" template value, so we can give every customer a link which only allow them access to the metrics for their server.
and a response like:

```
HTTP/1.1 200
Content-Type: application/json
{
  "deleteKey":"XXXXXXX",
  "deleteUrl":"myurl/dashboard/private/XXXXXXX",
  "key":"YYYYYYY",
  "url":"myurl/dashboard/private/YYYYYYY"
}
```

What do you  think? :)

Regards
Kristian Klausen

**Comment by torkelo** [comment]
if it's a live dashboard, meaning data is actually requested from the data source then the user will have to access the data source, so any query to that data source will be valid. Grafana dataproxy is just a proxy of the requests, Prometheus in your case do not allow for any per query or label/metric name permissions, if you expose it to an end user any query will be allowed.

**Comment by klausenbusk** [comment]
Hello Torkel

I'm aware of that, you also said the same for issue https://github.com/grafana/grafana/issues/2132

At worst case we could add some sort og filtering to the proxy right?

I at least think this issue should be repopened.
Wrtiting from a smartphone, it slow :)

Date: Sun, 10 Jul 2016 22:52:26 -0700

**Comment by klausenbusk** [comment]
@torkelo Could the following work?

`POST` to `/api/dashboards/db/:<foo>/share`.
1. Copy foo dashboard in grafana.dashboard and change slug to some random id (like snapshot) (also add a "type" field which we set to "private" or something).
2. Encrypt every expr

Then in the GUI javascript code we add something so if dashboard type is == private. It call `/api/datasources/private/proxy/` (or something like that), and the golang code the then decrypt the expr and forward it to the datasource.

It will of course break template variables (for shared "private" dashboard), but maybe we can fix that later..

Could that work? Hope you get the idea.

**Comment by klausenbusk** [comment]
More throughs.

We could implement it as a snapshot feature, lets call it "Live Snapshot", the dashboard is static but the metrics is "realtime/live". 

I dont think it would be that hård to implement. Add a "key" field to the "snapshot" table, which we then ude for AES encryption/decryption. To the json we then add a extra expr field named "encryptedExpr", which we them decrypt in the go code before forwarding to the datasource.

Template variables will og course not work, but we van live with that until someone figure out a solution for that.

**Comment by klausenbusk** [comment]
@torkelo ^

**Comment by webnard** [comment]
@torkelo This is already abstracted with the image URL generation (no data requests are made aside from what is passed as query parameters). To allow these images to be accessed publicly would be a huge boon.

**Comment by nalberto** [comment]
I would also love to be able to share selected live public dashboards. BIG +1 for that feature

**Comment by rsutaria** [comment]
BIG + 1. We are running a realtime Air Quality Monitoring dashboard in India. And we use grafana for a lot of our analysis. Providing a mechanism for a LIVE public dashboard where realtime data can be seen without having to login would be hugely beneficial for us too.

**Comment by stefan-muc** [comment]
I found a way to achieve that feature using [nginx](http://nginx.org/) as reverse proxy.
So if you are able to use that, see description here: https://community.grafana.com/t/how-to-make-one-live-dashboard-public/12819
