### ISSUE TITLE
Grafana, theme won't change

### ISSUE THREAD

**Issue by daven1985** [grafana/grafana#5548]
Morning,

I installed Grafana as part of a bundle with OMD Lab Edition, it is in the Light Theme however when I select Dark Theme it won't change.

Anyone know what I can do to change the theme?

Thanks.

**Comment by torkelo** [comment]
just go to your profile page and set theme
![image](https://cloud.githubusercontent.com/assets/10999/16721059/a366ac6a-473c-11e6-8555-c8c3dc91e616.png)

Then hit update button. If this does not work OMD Lab Edition might have a modified Grafana with hard coded light theme
