### ISSUE TITLE
Grafana variables question

### ISSUE THREAD

**Issue by kiranprabhu** [grafana/grafana#5549]
Does Grafana support variables to get $Start and $End time of the range currently chosen in the dashboard?
I got a table panel and a graph panel, I want table panel to fetch based on the time range chosen in the graph. This is to let the query of table panel know it need to #get data for a $End date.

Grafana Version 2.6.0
Backend Influxdb 0.9.x
Server OS Linux
Front End OS Chrome on Windows

Thanks 
Kiran

**Comment by torkelo** [comment]
if you use `where  $timeFilter` in your InfluxDB query (or use query builder UI) grafana will set the time range automatically based on the dashboard time range. If you zoom in on a graph the dashboard time range will change and the table panel query will be reissued with the new time range
