### ISSUE TITLE
Public Dashboard - error 429 - Too Many Requests

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#55499]
**What happened**:
When accessing a public dashboard using Cloudwatch datasource with 40 panels it is returning `Too Many Requests` for some of them.  
The original Dashboard works as expected.

**Comment by anton-definit** [comment]
We have the same problem. Anyway to fix this?

**Comment by evictorero** [comment]
@anton-definit this issue was fixed, you should see the changes after an instance reboot.
It was not related to Grafana but some wrong configuration in our infra.
