### ISSUE TITLE
Alerting: Migrating paused alerts un-pauses them

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#55519]
**What happened**:

Paused alerts are not a thing in unified alerting. So, migrating a paused alert makes it start evaluating.

Often, customers pause alerts because they aren't working or have no data. When migrating this to unified alerting, it's un-paused and starts evaluating. It's very likely that this alert will fail and either suddenly emit lots of DatasourceNoData/Error alerts. This can cause a flood of alerts on migration.

**What you expected to happen**:

I expected paused alerts to not begin evaluating and create spam after the migration.

The migration should create an infinite mute timing for each paused alert. It should also take care to match DatasourceNoData alerts which emenate from paused alerts.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an alert rule in Legacy alerting that is broken due to NoData.
2. Pause it.
3. Run the migration
4. Observe the DatasourceNoData alerts flowing out of alertmanager.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuri-tceretian** [comment]
It would be great to have `pause\stop` feature in the new alerting.

**Comment by alexweav** [comment]
Seems like the choices are:
1. Implement pausing in UA. Migrate legacy pauses to UA pauses, very straightforward.
2. If that cannot be done, have the migration create mute timings for paused alerts to simulate it.

**Comment by joeblubaugh** [comment]
How do paused alerts work in legacy alerting? Are they still evaluated? If KKR relied on seeing the state but never getting notifications that changes how we'd implement option 1.

From a UX perspective I quite like option 1 - it can all happen in the ruler so we don't have to worry about alertmanager config or semantics drifting from upstream.

**Comment by yuri-tceretian** [comment]
The team considered possible options and concluded that we would like to move forward with implementing support for pausing rule evaluations:
1. Create an API endpoint(s) that would allow changing the state of rule evaluations (paused\inactive\disabled and active\enabled). The names can be discussed in a pull request.
2. Add a property to the API specifications of the alert rule that would let users to pause\resume rule evaluations declaratively. The field name and location can be discussed in a pull request.

**Comment by armandgrillet** [comment]
@yuri-tceretian @grobinson-grafana I don't think this should still be in our inbox as we've finished the design doc for this feature.

**Comment by yuri-tceretian** [comment]
Also, I think the reason it was in the inbox was that it need to be estimated and prioritized. Imo, it's medium to high priority

**Comment by grobinson-grafana** [comment]
@alexmobo I think the last change we need to make is to add `IsPaused` to the migrations right?

**Comment by alexmobo** [comment]
@grobinson-grafana yes, that is my intention for next week when I am off on-call.

**Comment by alexmobo** [comment]
Pausing alerts and migration ([here](https://github.com/grafana/grafana/pull/62798)) from Legacy Alerting to Grafana Alerting has landed in Grafana 9.4.

**Comment by higp14** [comment]
Can you please share the API docs that enables pausing alerts?
