### ISSUE TITLE
Repeating panels are cancelled when using prometheus

### ISSUE THREAD

**Issue by chlunde** [grafana/grafana#5551]
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1.0-beta1
- What datasource are you using? prometheus
- What OS are you running grafana on?
- What did you do? create repeated templated panel
- What was the expected result? panel repeating with data from different jobs in each panel
- What happened instead? the panel was repeating but only one panel had data

I think there's a small fix required for #5321 in order to handle repeating/templated panels: when multiple templated panels are visible all but the last query are cancelled.

This is probably because the template is used as `requestId`, instead of the resulting string:

In `public/app/plugins/datasource/prometheus/datasource.ts`, `query.requestId = target.expr` should probably be `query.expr`.

**Comment by torkelo** [comment]
this is fixed in latest 3.1 builds https://github.com/grafana/grafana/issues/5459

http://grafana.org/download/builds.html

**Comment by chlunde** [comment]
Should that commit be added to the 3.1.x branch too?

**Comment by torkelo** [comment]
yes it should! good catch! it is now cherry picked over to the 3.1.x branch
