### ISSUE TITLE
[Feature request] allow dashboard backup/restore using grafana-cli

### ISSUE THREAD

**Issue by jacekn** [grafana/grafana#5552]
It would be useful for grafana-cli to support dashboard backup and restore. Even simple JSON stdin/stdout export/import as start would be useful.

**Comment by sstarcher** [comment]
It would be very helpful to be able to import dashboards via the CLI into grafana.  Currently it looks like the API for grafana.net supports revisions, but it does not have a latest tag.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
