### ISSUE TITLE
Prometheus histogram heatmap y-axis out-of-order with auto legend

### ISSUE THREAD

**Issue by jstangroome** [grafana/grafana#55535]
**What happened**:

I created a Heatmap panel of some Prometheus histogram metrics, with the legend set to `auto` and the `+Inf` entry on the y-axis appeared between `0` and the next positive y-axis value. The corresponding data was also incorrectly plotted.

**What you expected to happen**:

The `+Inf` label should appear at the topmost position on the y-axis and its cumulative value correctly interpreted, the same way was when the legend is explicitly specified as `{{le}}`.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/148754/191410900-7b8a6151-3a62-4cc2-b857-f8139786ae13.png">

**How to reproduce it (as minimally and precisely as possible)**:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/148754/191410789-1f049499-01cb-49c0-af89-d53616e32bb4.png">

**Anything else we need to know?**:

I was only able to get this working when I stumbled upon this comment on an indirectly related issue:
https://github.com/grafana/grafana/issues/24343#issuecomment-1250728216

**Environment**:
- Grafana version: v9.1.4 from [Docker Hub](https://hub.docker.com/layers/grafana/grafana/9.1.4/images/sha256-f776b98f6bc3115d04f76f9b52b8172ac0cd81a8a78933d7e48bf2b76ce13d95?context=explore)
- Data source type & version: Prometheus 5.0.0 (core)
- OS Grafana is installed on: Docker host is Ubuntu 18.04
- User OS & Browser: Windows 11 and Chrome v105
- Grafana plugins: Heatmap 5.0.0 (core)
- Others:

**Comment by Lightn** [comment]
Looks similar to the previously fixed issue #15637

**Comment by abursavich** [comment]
It looks like the raw label values are being sorting as strings. Here's the same axis with "Number" and "milliseconds (ms)" formatting.

<img width="187" alt="Screen Shot 2022-10-31 at 4 22 50 PM" src="https://user-images.githubusercontent.com/1512418/199128028-bd2a8e6d-48aa-4110-bc3b-429e04d8e5ec.png"> <img width="191" alt="Screen Shot 2022-10-31 at 4 23 22 PM" src="https://user-images.githubusercontent.com/1512418/199128026-90e42385-e627-49d7-8178-379ecd7a316a.png">

**Comment by metanull-operator** [comment]
I ran into this issue today. I assume it is related.

![image](https://user-images.githubusercontent.com/54516310/199850166-bb8d6b2e-78f3-470a-95ae-1ce0940baecb.png)

**Comment by skeagy** [comment]
I ran into this issue too with  grafana-9.2.1-r0
![image](https://user-images.githubusercontent.com/23060915/200706821-e9ff48a6-f6ae-41a0-8224-291876d5f7d8.png)

**Comment by leeoniya** [comment]
we currently sort by (and detect numeric strings) in the frame `name`, and this only populates as `+Inf` when sticking `{{le}}` into the Legend option of the query editor:

`{{le}}`:

![image](https://user-images.githubusercontent.com/43234/202936148-ae078c9c-3af3-451c-9d3d-601d5c5fec18.png)

`Auto`:

![image](https://user-images.githubusercontent.com/43234/202936158-47d98d12-4098-4a77-87f2-c1b358aec4a3.png)

i think the correct fix here is for our prometheus backend to set frame names to `le` when the response format is `heatmap` unless `legendFormat` is explicitly set to another label, probably here:

https://github.com/grafana/grafana/blob/2cd9cbd35925830dee97d9d18840eadc9d0cbbf3/pkg/tsdb/prometheus/querydata/response.go#L114-L118

cc @itsmylife @gtk-grafana @bohandley @toddtreece
