### ISSUE TITLE
Inaccurate time series bar graph at different timeframes

### ISSUE THREAD

**Issue by olliekabi** [grafana/grafana#55565]
**What happened**:
The time-series bar graph displays inaccurate values at different timeframes. When viewing the graph with a larger time frame, bars were shown for times that they did not actually exist. When zooming into a smaller time frame the inaccurate bars disappear. The inaccurately shown bars seems to relate to data elsewhere in the time-series that are "bleeding" into other times.

This can be seen clearly in the panel snapshot linked. Note how the grouping of data on the right contains both red (representing down status) and green bars (representing up status) at first, but upon zooming into just that section, you can now more accurately see that there some red bars (down status) disappear for this time period. This is demonstrated in the attached gif, as well as in the snapshot linked.

It should be noted that this 

![Kapture 2022-09-21 at 13 18 24](https://user-images.githubusercontent.com/53619179/191502138-27c17496-bd3c-4f6f-8658-1639b2a02add.gif)

https://snapshots.raintank.io/dashboard/snapshot/rrqEaXVsWvQ9KHQeJtmOKpbn13nScs3e?orgId=2&from=1663669981105&to=1663756381105

**What you expected to happen**:
Data should be represented accurately at all time frames, with no incorrect bars where the data does not exist.

**How to reproduce it (as minimally and precisely as possible)**:
The closest to a reproduction that I can offer is the interactive snapshot linked. However this is simply a time series graph displaying a Victoria Metrics query, with some colour overrides for each state based on regex matching "sort_desc(sum(browser_api_link_info{user =~ "$user", name =~ "technologies", instance =~ "$browser_tab"} and on(instance) browser_website_visible_toggle{user =~ "$user", instance =~ "$browser_tab"} > 0) by (status, instance) > 0)" (some var names changed for privacy). 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.5 (but this issue was present back to at least 8.4.7)
- Data source type & version: Victoria Metrics v1.75.0 - Prometheus 5.0.0
- OS Grafana is installed on: Kubernetes (docker image: grafana/grafana:9.1.5
- User OS & Browser: MacOS 12.5.1 - Chrome 105.0.5195.125 & Safari 16.0
- Grafana plugins: Time series 5.0.0, Prometheus 5.0.0
- Others:

**Comment by codeincarnate** [comment]
We've looked into this and at different zoom levels data is overlapping so only one color ends up being shown. Which series will be on top isn't always stable so that's why the switch occurs. We'd suggest using the State Timeline visualization as it's more suited to situations like this where data is either on or off 😄
