### ISSUE TITLE
Tempo: Search tab dropdown menus don't work when the cursor is in the `Tabs` field

### ISSUE THREAD

**Issue by CrypticSignal** [grafana/grafana#55587]
**What happened**:
The dropdown menu for the `Service Name` and `Span Name` fields don't work if the cursor is inside the `Tags` field.

![image](https://user-images.githubusercontent.com/48166845/191547638-88060055-6825-48aa-aff7-d857913f2bc7.png)

**What you expected to happen**:
I expected to be able to use the dropdown menu.

**How to reproduce it (as minimally and precisely as possible)**:
1. Click inside the `Tags` input field.
2. Click on dropdown menu for `Service Name` or `Span Name`

**Environment**:

- macOS 12.5.1
- Grafana v9.1.6
- https://www.whatsmybrowser.org/b/TCJ6W

**Comment by xiyu95** [comment]
I can take a look at this one 😄
