### ISSUE TITLE
[Bug] Stacking SingleStat panels on a single row

### ISSUE THREAD

**Issue by enviroeye** [grafana/grafana#5559]
Grafana version: 3.0.4
Datasource: InfluxDB 1.0
OS: Ubunutu 15.04

Trying to stack some SingleStat panels on top of one and another _within a single row._

![screenshot_3](https://cloud.githubusercontent.com/assets/16280541/16755760/4b230050-4843-11e6-84e7-d7f30e11aeb7.png)

Row height is set to 400px, the Graph panel also to 400px as is the text panel to the right. The SingleStat panels are set to a height of 125px.

I was expecting the SingleStat panels to simple stack on top of each other, however I end up with the with the lower singlestat panel dropping to the far left under the first graph panel instead

Is this the normal behaviour or a bug?

Mark

**Comment by torkelo** [comment]
That kind of layout is not supported right now. 

You should be able do something close to it. 
http://play.grafana.org/dashboard/db/advanced-layout

Better layout options is something that we want to add in the future
https://github.com/grafana/grafana/issues/170
