### ISSUE TITLE
Auto Complete Performance Issues  on Large Amount of Alert Groups

### ISSUE THREAD

**Issue by ryan-grafana** [grafana/grafana#55600]
**What happened**:
We are seeing performance issues when loading alert groups. We have over 10,000 groups and the auto complete is taking a very long time which makes the alert creation experience very rough. We are gearing towards rolling out Grafana Enterprise to 2000 engineers, so any added complications to the user experience without a workaround could result in a poor user experience.

**What you expected to happen**:
Alert groups load fast (sub 2 seconds)  no matter how many have been created. 

**Anything else we need to know?**:
User is doing a bulk migration via API. They are running version 9.1.3. They tried this with “only” 5k alerts but unfortunately even typing ‘Add New’ is so unresponsive (in the screen recording I was trying to type ‘Add New’ continuously but ‘Add New’ showed up after couple seconds).

User was viewing Create Alert Rule > Alert Group

**Comment by konrad147** [comment]
Fixed by https://github.com/grafana/grafana/pull/61221
