### ISSUE TITLE
The location of storing my dashboard

### ISSUE THREAD

**Issue by wi-cuckoo** [grafana/grafana#5560]
I need to use created dashboards in other web pages, but I don't know how the grafana store my dashboards, where and the type. I hope I can choose the location( eg: mysql) for storing my dashboard,
and pass the uri parms( like: http://192.168.8.29:3000/dashboard/db/cluster-demo?cluster=cluster1) to dashboard and I can use the variable $cluster in the graph configuration. Thanks for your response!!!

**Comment by torkelo** [comment]
Grafana stores the dashboard definition in it's database, which can use mysql. The table name i dashboard. 

You can pass template variables in URL using `var-<varname>=value` syntax. 

Example
http://play.grafana.org/dashboard/db/templated-graphs-nested?var-app=fakesite&var-server=web_server_01&var-server=web_server_02&var-interval=$__auto_interval

**Comment by wi-cuckoo** [comment]
@torkelo I can't find the doc to introduce its database, you mean **grafana.db**? As the parameters you said, I have know that ! Actually, I mean, if I passed a  custom *name=value*, and I want to use *$name* to set the row title. Yeah, that is, can I ? Anyway, very appreciate your answer /smile/smile
