### ISSUE TITLE
[Feature Request] Allow collapsing of rows in non-editable dashboard.

### ISSUE THREAD

**Issue by afics** [grafana/grafana#5561]
* **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using?
3.0.4-1464167696

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Debian 8

We have huge dashboards per host in which most rows are collapsed by default to achieve better overview. Once one clicks on a collapsed rows title bar, said title bar vanishes and I could not find a way to collapse the row again. This is a non-issue if the dashboard is editable, as the title bar stays visible.

I would like a way to collapse rows again for the sake of visibility.

**Comment by torkelo** [comment]
If you show the row title you can collapse and expand it, even for non editable dashboards
