### ISSUE TITLE
Glue: Validate if target query is valid

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55625]
_Background_

An idea that @gelicia suggested is: Add a button to validate the target query.  Why? In https://github.com/grafana/grafana/issues/55369 a target query editor was added. However, there's no way to test if the query is valid or if it returns any results.

In later stages, we plan to display the results. However, by doing simple validation now we could add a simpler initial implementation that would hugely improve UX with smaller effort. It will also help us work on running Correlations Page queries earlier and use the same logic to run the source query. 

_Requirements_

* Add a "Test query" button (can be a different text) near the target query editor
* When a button is clicked the query is run
* A message below the query is shown below the target query
  * an error if no data frames are returned
  * info that the query works fine otherwise 

Note: The validation may stop properly working in Stage 2. In stage 2 we will allow using variables in the query that correspond to the field name, but there will be no sample results available to fill in the variables (sample results will be added in Stage 3) so queries will run not interpolated and may fail.

The benefit of doing it at this stage is that we will figure out how to run queries on Correlations Page, and it will be easier to
implement Source Editor in Stage 3.

_Technical details_

The correlations page can retrieve the corresponding data source API and run `.query` method to get results (like in [Explore](https://github.com/grafana/grafana/blob/802d67eecaecb129308b0b3d966c73ec01358ca6/public/app/features/query/state/runRequest.ts#L113), it may require using some default time-range or time range selector)

**Comment by gelicia** [comment]
This was probably intended to be for the target query only.

**Comment by ifrost** [comment]
Adding support for the source query validation doesn't make much sense - the source query is not persisted and we only going to use results which means we need to display them anyway, not only the validation message.

It can still be useful to add validation to the target query editor which is being added in #55369. 

We can:

(1) Add validation to target query as part of Stage 1 (static queries)
* Add validation of this query once the above PR is merged.
* The validation, however, may stop properly working in Stage 2. We will allow using variables in the query that correspond to the field name, but there will be no sample results available to fill in the variables (sample results will be added in Stage 3) so queries will run not interpolated.
* The benefit of doing it at this stage is that we will figure out how to run queries on Correlations Page, and it will be easier to 
implement Source Editor in Stage 3.

(2) Add validation to target query as part of Stage 3
* Add validation after showing sample results is implemented 
* In Stage 4 the validation will be replaced with the visualization of results

I think it makes sense to go with (1). It will allow us to figure out how to run the query in Correlations Page. We could work on this as part of Stage 1 or even move it to Stage 2 because it won't block anything.

**Comment by gelicia** [comment]
I like option 1.

**Comment by ifrost** [comment]
I've updated the description to option 1
