### ISSUE TITLE
Geomap: Dynamic Geojson Style Mapping

### ISSUE THREAD

**Issue by janicaud** [grafana/grafana#55626]
**What happened**
When using the **awesome** Geomap plugin, when you use the dynamic Geojson configuration for your layer, the mapping between the query & the geojson layer does not reset itself when refreshing the data.

**What you expected to happen**
The mapping between the 2 should reset, for instance if you want to Zoom in or out on the timerange to colorize elements.

To fix, i think you probably need to fix : 

geojsonDynamic.ts:172
```
if (frame) {
          const field = findField(frame, config.idField);
          if (field) {
            field.values.toArray().forEach((v, i) => idToIdx.set(v, i));
          }

          style.dims = getStyleDimension(frame, style, theme, config.dataStyle);
        }

```

to
```
if (frame) {
          const field = findField(frame, config.idField);
          if (field) {
            idToIdx.clear():
            field.values.toArray().forEach((v, i) => idToIdx.set(v, i));
          }

          style.dims = getStyleDimension(frame, style, theme, config.dataStyle);
        }

```

**Environment**:
- Grafana version: 9.1.6

**Comment by yosiasz** [comment]
You can do dynamic geojson!?!? Wow
