### ISSUE TITLE
Grafana : Average Calculation + Dynamic Threshold

### ISSUE THREAD

**Issue by shayan90** [grafana/grafana#5562]
Hi All

I am new to Grafana World , I needed to clear up two things with you guys:

1) Is there anyway to dynamically change threshold within a time range ?

2) How does Grafana calculate Average ? Is there a way to calculate average by dividing total count by a constant variable using lucene ?

* I am using Elasticsearch as Data source

**Comment by torkelo** [comment]
1) No there is no way to do dynamically change thresholds

2) Elasticsearch has a script feature. But you can only modify each value in the document with that, not do calculations on the total.

**Comment by id3a** [comment]
We really need this feature...

For example I want the singlestat to show red if the the average from the last 15 min is 50% more than the average from the last 7 days
