### ISSUE TITLE
State timeline tooltip showing on more panels, Grafana 9.1.x

### ISSUE THREAD

**Issue by krzysion** [grafana/grafana#55630]
Panel State timeline tooltip showing on more panels:

![2022-09-22 17_47_33-Window](https://user-images.githubusercontent.com/36912975/191796140-33b5f82f-2bd4-4aa0-b0da-eb158594aa43.png)

Panel options, graph tooltip setting: Shared crosshair

![2022-09-22 17_56_18-Window](https://user-images.githubusercontent.com/36912975/191796162-adffe07b-c53a-4d61-9501-95b9cd9bad27.png)

**Environment**:
- Grafana version: 9.1.x

**Comment by mdvictor** [comment]
Hello @krzysion . Thanks for opening this issue! A fix will be released by the next patch.
