### ISSUE TITLE
 Download Filename Tweak Breaking my Scripts

### ISSUE THREAD

**Issue by andyl** [grafana/grafana#5563]
I install/config Grafana with Ansible. The install method takes a version number as a parameter - (eg 3.0.0). So far so good.

But starting in version 3.0.3, and continuing in 3.1.0, you added the build number to the download filename:

grafana_3.1.0-1468321182_amd64.deb

Feature request: please remove the build number, so I don't have to go look it up each time you come out with a new release. The filename should look like this:

grafana_3.1.0_amd64.deb

This issue is related to #5146

**Comment by torkelo** [comment]
why not treat `3.1.0-1468321182` as the whole version?

**Comment by andyl** [comment]
Because I have to look it up.  When I see an announcement "3.1.0 is released" - it is simpler to plug the version number, rather than have to look up the build number.

**Comment by andyl** [comment]
I've just started using the whole version number - will close this issue.
