### ISSUE TITLE
Alerting: error saving existing evaluation period

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#55649]
**Setup: create an alerting rule of a certain kind.**
1. Navigate to _Alerting_ on the side panel.
2. Create a rule with _Evaluate every_ = 70s
<img width="499" alt="image" src="https://user-images.githubusercontent.com/4903007/191870876-92677e51-9e29-43de-95a9-ac0a3d377c0a.png">

3. Save and Exit.

 **Bug:**
1. Navigate to _Alerting_ on the side panel.
2. Open the created rule.
3. Make a modification, e.g. change "Summary" tag.
4. Click _Save_.

**Expected:** the rule is saved.

**Actual:** error:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/4903007/191870207-eacfbf76-92cf-4f2c-8a9e-49ccab4d52a8.png">

Note that the timespan is converted to "XmYs" syntax. We either need to make this syntax acceptable (parsable) as valid input, or pre-fill the field content in an accepted syntax (like "70s").
 
**Environment**:
- Grafana version: Cloud
- Data source type & version: Azure Data Explorer
- User OS & Browser: Mac & Chrome
- Grafana plugins: Azure Data Explorer data sources v. 4.1.5

**Comment by mvsousa** [comment]
Hey @greatvovan 
I've open a PR with a suggestion to fix this bug, im not a Grafana code owner, so not sure if this is the right approach. It would be good if you could review it :) 
https://github.com/grafana/grafana/pull/55709

**Comment by konrad147** [comment]
Fixed by https://github.com/grafana/grafana/pull/56115
