### ISSUE TITLE
Feature request: handle other units

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#5564]
#### I'm submitting a Feature request to handle more Units

* bar
* t/h

```
diff --git a/public/app/core/utils/kbn.js b/public/app/core/utils/kbn.js
index 29cd7c4..cb1663c 100644
--- a/public/app/core/utils/kbn.js
+++ b/public/app/core/utils/kbn.js
@@ -424,6 +424,7 @@ function($, _, moment) {
kbn.valueFormats.opm = kbn.formatBuilders.simpleCountUnit('opm');
kbn.valueFormats.rpm = kbn.formatBuilders.simpleCountUnit('rpm');
kbn.valueFormats.wpm = kbn.formatBuilders.simpleCountUnit('wpm');
+ kbn.valueFormats.feed = kbn.formatBuilders.fixedUnit('t/h');

// Energy
kbn.valueFormats.watt = kbn.formatBuilders.decimalSIPrefix('W');
@@ -446,6 +447,7 @@ function($, _, moment) {
kbn.valueFormats.humidity = kbn.formatBuilders.fixedUnit('%H');

// Pressure
+ kbn.valueFormats.pressurebar = kbn.formatBuilders.fixedUnit('bar');
kbn.valueFormats.pressurembar = kbn.formatBuilders.fixedUnit('mbar');
kbn.valueFormats.pressurehpa = kbn.formatBuilders.fixedUnit('hPa');
kbn.valueFormats.pressurehg = kbn.formatBuilders.fixedUnit('"Hg');
@@ -706,6 +708,7 @@ function($, _, moment) {
{text: 'ops/min (opm)', value: 'opm' },
{text: 'reads/min (rpm)', value: 'rpm' },
{text: 'writes/min (wpm)', value: 'wpm' },
+ {text: 'tonne/hour (t/h)', value: 'feed' },
]
},
{
@@ -762,6 +765,7 @@ function($, _, moment) {
{
text: 'pressure',
submenu: [
+ {text: 'Bars', value: 'pressurebar'},
{text: 'Millibars', value: 'pressurembar'},
{text: 'Hectopascals', value: 'pressurehpa' },
{text: 'Inches of mercury', value: 'pressurehg' },
```

**Comment by bbczeuz** [comment]
I vote for a general review/update on the 'units' list before merging this. Tonne per hour _seems_ to me to not be the most common unit.

**Comment by pulux** [comment]
A general review/update off the 'units' sounds good for me.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
