### ISSUE TITLE
No datapoints returning for cloudwatch s3 metric

### ISSUE THREAD

**Issue by tomschlick** [grafana/grafana#5565]
I'm trying to add some metrics for a few S3 buckets we are monitoring in CloudWatch but when I add the metrics this is what the HTTP request returns

```json
{"Datapoints":null,"Label":"BucketSizeBytes"}
```

This is how I have the metrics setup
![](http://i.imgur.com/K3jl3oE.png)

But you can see no data is coming through. The cloudwatch data source seems to be setup correctly as I can get billing metrics with the new [shared billing metric dashboard](https://grafana.net/dashboards/139).

Also I can see the same data in the CloudWatch dashboards so I know it is being collected ...
any advice?

**Comment by tomschlick** [comment]
Note: I'm using the new 3.1.0 stable

**Comment by mtanda** [comment]
I'm not sure, but specify StorageType dimension and set 1 week time range, I get this graph.
Please try.
![s3_cloudwatch](https://cloud.githubusercontent.com/assets/224552/16771154/6db0d790-488a-11e6-857a-e8b62c040468.png)

**Comment by tomschlick** [comment]
That works for NumberOfObjects but I can't seem to get the BucketSizeBytes to return anything... Can you try that on your end and see if it works for you?

**Comment by mtanda** [comment]
For BucketSizeBytes, you need to specify StandardStorage or somethng.

http://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html
> Valid storage type filters: StandardStorage, or StandardIAStorage, or ReducedRedundancyStorage (see StorageType dimension)

![s3_cloudwatch2](https://cloud.githubusercontent.com/assets/224552/16771935/3b87d75c-488d-11e6-9ffb-2e0f6f2e3de5.png)

**Comment by tomschlick** [comment]
That works! Didn't realize I had to specify the StorageType as well. Thanks!

**Comment by alkalinecoffee** [comment]
Just a tip for this: on top of setting a long time range (7d), it also helps to set Display -> Null Value to `connected`.  I think it's just something with how cloudwatch reports S3 size (the datapoints are very sparse so they might not easily show up on a chart).

**Comment by Syntactical01** [comment]
I am somewhat having this issue is well:
![image](https://user-images.githubusercontent.com/46199814/134695227-3b73bd74-f6e2-4d88-bb84-c181ad583e4b.png)
Not graphing anything, but if I flip to a table I get some data points, but I get one data point with a value and the next data point is null:

![image](https://user-images.githubusercontent.com/46199814/134695390-54b4a692-84bf-45fe-8c96-5a5421f78269.png)


Any tips or tricks on this?
