### ISSUE TITLE
Graph Rendering Issue

### ISSUE THREAD

**Issue by zp-markusp** [grafana/grafana#5567]
* **I'm submitting a ...**
- [ x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0
- What datasource are you using? influxdb
- What OS are you running grafana on? centos 7

I see some fancy chart while using influxdb 1.0 Beta1 as data source. Not sure if this is a rendering issue or influx related. Does someone has the same issue?

![image](https://cloud.githubusercontent.com/assets/6648693/16783115/066bae36-4883-11e6-892b-ae7675f0a62b.png)

regards, Markus

**Comment by torkelo** [comment]
This is a bug in influxdb 1.0 Beta1, think it is fixed in beta2
