### ISSUE TITLE
DB migration from 3.0.4 to 3.1 fails

### ISSUE THREAD

**Issue by infiniteproject** [grafana/grafana#5568]
DB migration seems to fail from 3.0.4 to 3.1 - using grafana/grafana:3.0.3-1463994644 or 3.0.4 grafana starts cleanly.

Please include this information:

- What Grafana version are you using?
grafana/grafana:latest

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Docker 1.11.2 Debian 8.5 

- What did you do?
Pulled latest grafana/grafana, recreated container using docker-compose up.

- What was the expected result?
Upgrade from 3.0.4 to 3.1

- What happened instead?
t=2016-07-12T20:39:28+0200 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: duplicate column name: plugin_id\n"
t=2016-07-12T20:39:28+0200 lvl=eror msg="Executing migration failed" logger=migrator id="Add column plugin_id in dashboard" error="duplicate column name: plugin_id"
t=2016-07-12T20:39:28+0200 lvl=eror msg="Exec failed" logger=migrator error="duplicate column name: plugin_id" sql="alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL "
t=2016-07-12T20:39:28+0200 lvl=info msg="Starting DB migration" logger=migrator

**Comment by torkelo** [comment]
Tried to replicate this using docker-compose, upgrading from 3.0.4 to 3.1.0, but the schema migration worked. 

```
❯ docker-compose up                                                                                                                                    system
Recreating docker_grafana_1
Pulling grafana (grafana/grafana:3.1.0)...
3.1.0: Pulling from grafana/grafana
5c90d4a2d1a8: Already exists
b1a9a0b6158e: Pull complete
acb23b0d58de: Pull complete
Digest: sha256:3476700a51ff136a507f9d09a6626964b6cfbc9352ed23e0063d8785d2b2c30f
Status: Downloaded newer image for grafana/grafana:3.1.0
Attaching to docker_grafana_1
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Starting Grafana" logger=main version=3.1.0 commit=v3.1.0 compiled=2016-07-12T06:42:28+0000
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Starting DB migration" logger=migrator
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column gnetId in dashboard"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for gnetId in dashboard"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_id in dashboard"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for plugin_id in dashboard"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_version to plugin_settings"
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1 | t=2016-07-13T08:10:58+0000 lvl=info msg="Server Listening" logger=server address=0.0.0.0:3000 protocol=http subUrl=
```

do you have a backup of the grafana sqlite3 db? Maybe try the upgrade again. Otherwise locate the sqlite3 db in the docker volume and open it with the sqlite3 client tool and try to remove the plugin_id column from the dashboard table.

**Comment by infiniteproject** [comment]
Tried to upgrade again - no luck.

sqlite3 grafana.db .dump | grep plugin_id:

`, `plugin_id` TEXT NOT NULL
INSERT INTO "migration_log" VALUES(80,'create index UQE_plugin_setting_org_id_plugin_id - v1','CREATE UNIQUE INDEX `UQE_plugin_setting_org_id_plugin_id` ON `plugin_setting` (`org_id`,`plugin_id`);',1,'','2016-05-12 18:56:40');
INSERT INTO "migration_log" VALUES(91,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:25');
INSERT INTO "migration_log" VALUES(92,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:28');
INSERT INTO "migration_log" VALUES(93,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:31');
INSERT INTO "migration_log" VALUES(94,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:34');
INSERT INTO "migration_log" VALUES(95,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:38');
INSERT INTO "migration_log" VALUES(96,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:41');
INSERT INTO "migration_log" VALUES(97,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:46');
INSERT INTO "migration_log" VALUES(98,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:27:53');
INSERT INTO "migration_log" VALUES(99,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:06');
INSERT INTO "migration_log" VALUES(100,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:07');
INSERT INTO "migration_log" VALUES(101,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:08');
INSERT INTO "migration_log" VALUES(102,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:09');
INSERT INTO "migration_log" VALUES(103,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:11');
INSERT INTO "migration_log" VALUES(104,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:14');
INSERT INTO "migration_log" VALUES(105,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:18');
INSERT INTO "migration_log" VALUES(106,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:26');
INSERT INTO "migration_log" VALUES(107,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:28:41');
INSERT INTO "migration_log" VALUES(108,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:29:08');
INSERT INTO "migration_log" VALUES(109,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:03');
INSERT INTO "migration_log" VALUES(110,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:05');
INSERT INTO "migration_log" VALUES(111,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:06');
INSERT INTO "migration_log" VALUES(112,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:08');
INSERT INTO "migration_log" VALUES(113,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:10');
INSERT INTO "migration_log" VALUES(114,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:12');
INSERT INTO "migration_log" VALUES(115,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:15');
INSERT INTO "migration_log" VALUES(116,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:19');
INSERT INTO "migration_log" VALUES(117,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:27');
INSERT INTO "migration_log" VALUES(118,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:30:41');
INSERT INTO "migration_log" VALUES(119,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:31:08');
INSERT INTO "migration_log" VALUES(120,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:32:00');
INSERT INTO "migration_log" VALUES(121,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:39');
INSERT INTO "migration_log" VALUES(122,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:41');
INSERT INTO "migration_log" VALUES(123,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:42');
INSERT INTO "migration_log" VALUES(124,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:44');
INSERT INTO "migration_log" VALUES(125,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:45');
INSERT INTO "migration_log" VALUES(126,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:48');
INSERT INTO "migration_log" VALUES(127,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:51');
INSERT INTO "migration_log" VALUES(128,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:37:56');
INSERT INTO "migration_log" VALUES(129,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:03');
INSERT INTO "migration_log" VALUES(130,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:22');
INSERT INTO "migration_log" VALUES(131,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:23');
INSERT INTO "migration_log" VALUES(132,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:25');
INSERT INTO "migration_log" VALUES(133,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:26');
INSERT INTO "migration_log" VALUES(134,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:28');
INSERT INTO "migration_log" VALUES(135,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:32');
INSERT INTO "migration_log" VALUES(136,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:35');
INSERT INTO "migration_log" VALUES(137,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:40');
INSERT INTO "migration_log" VALUES(138,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:38:47');
INSERT INTO "migration_log" VALUES(139,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:39:01');
INSERT INTO "migration_log" VALUES(140,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 18:39:28');
INSERT INTO "migration_log" VALUES(141,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:37');
INSERT INTO "migration_log" VALUES(142,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:38');
INSERT INTO "migration_log" VALUES(143,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:39');
INSERT INTO "migration_log" VALUES(144,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:40');
INSERT INTO "migration_log" VALUES(145,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:41');
INSERT INTO "migration_log" VALUES(146,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:44');
INSERT INTO "migration_log" VALUES(147,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:49');
INSERT INTO "migration_log" VALUES(148,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:14:56');
INSERT INTO "migration_log" VALUES(149,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:15:09');
INSERT INTO "migration_log" VALUES(150,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-12 21:15:36');
INSERT INTO "migration_log" VALUES(151,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:15');
INSERT INTO "migration_log" VALUES(152,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:19');
INSERT INTO "migration_log" VALUES(153,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:23');
INSERT INTO "migration_log" VALUES(154,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:26');
INSERT INTO "migration_log" VALUES(155,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:28');
INSERT INTO "migration_log" VALUES(156,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:31');
INSERT INTO "migration_log" VALUES(157,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:35');
INSERT INTO "migration_log" VALUES(158,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:42');
INSERT INTO "migration_log" VALUES(159,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:29:57');
INSERT INTO "migration_log" VALUES(160,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:30:24');
INSERT INTO "migration_log" VALUES(161,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:31:16');
INSERT INTO "migration_log" VALUES(162,'Add column plugin_id in dashboard','alter table `dashboard` ADD COLUMN `plugin_id` TEXT NULL ',0,'duplicate column name: plugin_id','2016-07-13 15:33:00');
, `updated_by` INTEGER NULL, `created_by` INTEGER NULL, `gnet_id` INTEGER NULL, `plugin_id` TEXT NULL);
, `plugin_id` TEXT NOT NULL
CREATE UNIQUE INDEX `UQE_plugin_setting_org_id_plugin_id` ON `plugin_setting` (`org_id`,`plugin_id`);
`
I exported dashboard and started fresh - re-imported dashboard, set data source and it works.
