### ISSUE TITLE
Investigate HTML plugin not working with pubdash

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#55685]
See github [discussion](https://github.com/grafana/grafana/discussions/49253#discussioncomment-3717491)

**Comment by jalevin** [comment]
check to see if granularity fix also fixes this first

**Comment by LarsStegman** [comment]
It does not work yet in 9.2.0, is there a PR or issue that you can point me to?

**Comment by mmandrus** [comment]
> It does not work yet in 9.2.0, is there a PR or issue that you can point me to?

Hi @LarsStegman, this will be fixed in 9.3.0.

**Comment by LarsStegman** [comment]
That's great, thanks!

Good to know, thanks for the heads up! It shouldn't too hard to replicate the functionality. Would it make sense to extend the Text panel with css and js functionality?

**Comment by mmandrus** [comment]
Resolved by https://github.com/grafana/grafana/pull/57129
