### ISSUE TITLE
Blank dashboards appear when using api to create dashboards from json

### ISSUE THREAD

**Issue by jchauncey** [grafana/grafana#5569]
<img width="676" alt="screen shot 2016-07-12 at 5 14 30 pm" src="https://cloud.githubusercontent.com/assets/430360/16783987/a51ff1e2-4854-11e6-89d4-619c88eef0f9.png">

I can't delete them either.

**Comment by torkelo** [comment]
Please provide the API call details

**Comment by jchauncey** [comment]
whoops here you go -

```bash
echo "Importing default dashboards..."
for filename in ${DASHBOARD_LOCATION}/*.json; do
  echo "Importing ${filename} ..."
  curl -i -XPOST --data "@${filename}" -H "${HEADER_ACCEPT}" -H "${HEADER_CONTENT_TYPE}" "http://${GRAFANA_USER}:${GRAFANA_PASSWD}@localhost:${GRAFANA_PORT}/api/dashboards/db"
  echo ""
  echo "Done importing ${filename}"
done
```

and a dashboard looks like this - 

```json
{
  "dashboard": {
    "id": "",
    "title": "Redis",
    "originalTitle": "Redis",
    "tags": [],
    "style": "dark",
    "timezone": "browser",
    "editable": true,
    "hideControls": false,
    "sharedCrosshair": false,
```

Ive tried both `null` and `""` for the id

**Comment by jchauncey** [comment]
Here is a gist of an entire dashboard template - https://gist.github.com/jchauncey/ea5d97a630c825cd902cc08d36a79edb

**Comment by jchauncey** [comment]
You can find out more information here - https://github.com/deis/monitor/tree/master/grafana

**Comment by torkelo** [comment]
I had no problem saving the gist using the API:
![image](https://cloud.githubusercontent.com/assets/10999/16923415/6c530140-4d1a-11e6-9256-2b2865d25915.png)

![image](https://cloud.githubusercontent.com/assets/10999/16923429/7d850454-4d1a-11e6-88ef-e07d97d6a7bc.png)

**Comment by jchauncey** [comment]
... why close this. I can reproduce this problem every time I rebuild the my grafana image with that exact gist in a file.

**Comment by torkelo** [comment]
because I think you must be using the API wrong, not sure what though.

**Comment by jchauncey** [comment]
That above curl statement is exactly what I do everytime. This only started happening when we moved from 2.x of grafana to 3.0.0

**Comment by jchauncey** [comment]
The weird thing is that grafana only reports 7 dashboards. Which is the correct number (if we dont count the blank ones)

<img width="958" alt="screen shot 2016-07-18 at 2 56 17 pm" src="https://cloud.githubusercontent.com/assets/430360/16926686/d488daf0-4cf7-11e6-9f89-a6fbc1f93864.png">

I also cannot delete the blank dashboards using the UI. It's like they are orphaned rows.

**Comment by torkelo** [comment]
what is the response from the curl command? what are the headers you send? -H "${HEADER_ACCEPT}" -H "${HEADER_CONTENT_TYPE}"

**Comment by torkelo** [comment]
Maybe you have enabled json file based dashboards? and scanning that directory?

**Comment by jchauncey** [comment]
Here is the curl statement that is executed 

```
curl -i -XPOST --data @/usr/share/grafana/dashboards/redis.json -H Accept: application/json -H Content-Type: application/json http://admin:admin@localhost:3500/api/dashboards/db
```

**Comment by torkelo** [comment]
looks like the empty dashboards that appear in search are the the file based ones (not the one you save to db), 

https://github.com/deis/monitor/blob/master/grafana/rootfs/usr/share/grafana/grafana.ini.tpl#L285

That line will make grafana index the json files in the dashboards folder and make them available in search. But the dashboard json files are not pure dashboards, they have the dashboard under a sub property "dashboard" (which is correct for the write API) but not correct if you want to open file based dashboards directly from search. please move the dashboards you want to import with the api to another folder

**Comment by jchauncey** [comment]
ah k thanks

**Comment by jchauncey** [comment]
Ok that fixed the issue thanks again.
