### ISSUE TITLE
Cloud home app crashes when datasource is misconfigured

### ISSUE THREAD

**Issue by summerwollin** [grafana/grafana#55704]
**What happened**:
Cloud home app landing page shows "An unexpected error happened" for cloud instance

**What you expected to happen**
 Page loads correctly

**How to reproduce it (as minimally and precisely as possible)**:
In a cloud grafana instance
Create a datasource with incorrect auth credentials
Navigate to that instance's /cloud-home-app page
See error

**Anything else we need to know?**:
Other UI pages load correctly when navigated to directly. Seen on Chrome browser.
Restart and rollback did not resolve the issue, so it is not related specifically to 9.1.5 as 9.1.3 had the exact same issue
Issue started for the instance on Sept 23 2022

**Environment**: grafana cloud
- Grafana version: 9.1.5 and 9.1.3
- Data source type & version: AWS prometheus datasource
- OS Grafana is installed on: cloud grafana
- User OS & Browser: OS Monterey, Chrome
-
![Uploading Scr
<img width="682" alt="Screen Shot 2022-09-23 at 2 51 15 PM" src="https://user-images.githubusercontent.com/16504889/192054654-20071c13-11e7-4f6e-920a-3971ab458274.png">
een Shot 2022-09-23 at 2.51.04 PM.png…]()

**Comment by jarben** [comment]
Hi @summerwollin, any chance to give me access to this instance?

**Comment by jarben** [comment]
@summerwollin We are now showing this when there is an error instead of crushing the whole page: 
![image](https://user-images.githubusercontent.com/561365/192311627-03eee55a-f7bb-4aa0-935d-0ee1c7c2062b.png)

Is this good enough to resolve the escalation? 

Feels like we may need to add a better error message too...

**Comment by chrisharbro** [comment]
@jarben customer is now confused why the usage component is broken. I don't think this will be sufficient for closing the escalation.

**Comment by jarben** [comment]
@chrisharbro do you know if they fixed the permissions issue described here? https://github.com/grafana/support-escalations/issues/4055#issuecomment-1256651772

**Comment by chrisharbro** [comment]
@jarben They made not changes as far as the user is concerned. They noticed that when testing the data source it worked correctly, so they did not really know what changes needed to be made

**Comment by chrisharbro** [comment]
Going to try and give them some context on the permissions error so they can hopefully address it and we can see if that fixes the usage component error.

**Comment by chrisharbro** [comment]
@jarben the permissions issue is unrelated to the new error (usage component on cloud-home-app) we have discovered.

**Comment by jarben** [comment]
Oh ok, @chrisharbro any chance to invite me to the org as admin? I'll need to investigate why the usage data source fail for the plugin...

**Comment by chrisharbro** [comment]
@jarben done!

**Comment by jarben** [comment]
Hey @chrisharbro, we have introduced a less disturbing error message when the data source is misconfigured: 
![image](https://user-images.githubusercontent.com/561365/193241775-aba28f59-5f78-4f13-b05d-c524d8109f7a.png)

However, the issue will only be fixed once [this is resolved](https://github.com/grafana/support-escalations/issues/4103).

**Comment by chrisharbro** [comment]
That's definitely a huge improvement as the previous error was so ambiguous that you didn't even know what was broken without looking at a working instance. Thanks!

**Comment by jarben** [comment]
Perfect thanks @chrisharbro !
