### ISSUE TITLE
Grafana 9.1.6: AnnotationQueryRunner Error in Prometheus DataSource with Browse Access Mode

### ISSUE THREAD

**Issue by jnyi** [grafana/grafana#55705]
**What happened**: We recently try to upgrade to Grafana 9.1.4 from earlier versions in order to fix https://github.com/grafana/grafana/issues/54535. However we encounter 2 blockers regarding browse access mode in prometheus data source plugin, one for templating, one for annotation. In v9.1.6, there is a fix for [proemetheus metadata requests for browse access mode](https://github.com/grafana/grafana/pull/55403) which resolved 1 blocker. But annotation queries still encountered:

<img width="531" alt="Screen Shot 2022-09-22 at 10 19 29 PM" src="https://user-images.githubusercontent.com/96499497/192060040-fb0a174a-4c43-466a-aff3-f95c9766f393.png">

We identified this could be caused by this PR since v8.3: https://github.com/grafana/grafana/pull/41059 that annotation queries has to go through backend regardless of `Browse Access Mode`. Since in v9.1.x, prometheus plugin still supports browse access mode and https://github.com/grafana/grafana/pull/55403 is labeled as a bug fix for templating, we'd hope to have a similar fix for annotation queries too.

**What you expected to happen**:
Annotation works for prometheus data sources in earlier versions using browse access mode.

<img width="591" alt="Screen Shot 2022-09-22 at 10 18 41 PM" src="https://user-images.githubusercontent.com/96499497/192060338-e5f319fd-1124-435b-896e-489728f494d9.png">

**How to reproduce it (as minimally and precisely as possible)**:

Bring up grafana v9.1.6 with prometheus browser mode, and configure an annotation to query prometheus data source taht can't be reached from grafana backend server due to firewall reasons..

**Anything else we need to know?**:
We are currently using Browse access mode due to how the data sources endpoints are authA&Z and accessed across different regions/envs/clouds, it would not be a short term solution to move to Server Access mode.

**Environment**:
- Grafana version: v9.1.6
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux 
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others:

**Comment by jnyi** [comment]
I had an PR which fixed this issue internally: https://github.com/jnyi/grafana/pull/1, give some ideas about this issue.

**Comment by itsmylife** [comment]
I created a [PR](https://github.com/grafana/grafana/pull/57876) as well. When it is merged It will solve the issue. Please check it. And thank you very much for the inputs @jnyi

**Comment by jnyi** [comment]
hi @itsmylife, just wonder if grafana could make a new release for `v9.1.x`, i think unfortunately the last release v9.1.8 didn't include this change.
