### ISSUE TITLE
Grafana Kairosdb Multi Value Templating not working, perhaps

### ISSUE THREAD

**Issue by gitvegas** [grafana/grafana#5571]
Templating is working fine on Grafana with Kairosdb but Multi Value templating is not, perhaps. Im selecting glob option and on the template dropdown i do get checkbox options but i see the graph only when i select one at a time and more than one, i get nothing. Could you please let me know a work around or how this would work.

So as a work around i have created multiple template drop downs and i associated each one with its respective query on a graph, so i can see multiple metrics. However, i want to use the multi value options, cheers

**Comment by torkelo** [comment]
https://github.com/grafana/kairosdb-datasource/pull/18/

**Comment by gitvegas** [comment]
Torkel,
Thank you very much for getting back with the info. Can you please suggest how to get and install this patch. Your help is really appreciated
Cheerssraj
