### ISSUE TITLE
Query performing bug with variable on dashboard

### ISSUE THREAD

**Issue by breslavsky** [grafana/grafana#55715]
**What happened**:

Query from Grafana to ClickHouse is not performing when dashboard has a variable.

```
error querying the database: code: 47, message: Missing columns: 'p.name' while processing query: 'SELECT email, p.name, address FROM users AS u ALL LEFT JOIN addresses AS a ON user_id = id', required columns: 'email' 'p.name' 'id' 'address' 'user_id', maybe you meant: ['email','id'], joined columns: 'a.id' 'user_id' 'address' '_part' '_part_index' '_part_uuid' '_partition_id' '_partition_value' '_sample_factor' '_part_offset'
```

**What you expected to happen**:

Query successfully performed and user sees table with data.

**How to reproduce it (as minimally and precisely as possible)**:

1. Prepare data in database

```sql
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    `id` UInt32,
    `email` char(155)
)
ENGINE = MergeTree
PRIMARY KEY id
SETTINGS index_granularity = 8192;
INSERT INTO users VALUES(1, 'test@test.com');

DROP TABLE IF EXISTS profiles;
CREATE TABLE profiles
(
    `id` UInt32,
    `user_id` UInt32,
    `name` char(155)
)
ENGINE = MergeTree
PRIMARY KEY id
SETTINGS index_granularity = 8192;
INSERT INTO profiles VALUES(1, 1, 'test name');

DROP TABLE IF EXISTS addresses;
CREATE TABLE addresses
(
    `id` UInt32,
    `user_id` UInt32,
    `address` char(155)
)
ENGINE = MergeTree
PRIMARY KEY id
SETTINGS index_granularity = 8192;
INSERT INTO addresses VALUES(1, 1, 'test address');
```
2. Create dashboard with name [Grafana bugs](https://tinyurl.com/2elpn2af)

4. Add variable [name](https://tinyurl.com/2f6arpha) as **Text box**

6. Add panel with name [Bug with second join](https://tinyurl.com/2hpef7u2) and query

```sql
select 
	u.email,
	p.name,
	a.address
from
	users u
left join profiles p on
	p.user_id == u.id
left join addresses a on
	a.user_id == u.id
```

7. Run the query.

**Anything else we need to know?**:

It looks Grafana is trying to parse the query and losing the second join.

If we will remove variable **name** from Dashboard the query [will work](https://tinyurl.com/2hpef7u2).

Please check [full video](https://www.awesomescreenshot.com/video/11312756?key=4d32f404714f36b143914fd464613c19) about the problem.

**Environment**:
- Grafana version: v9.0.5
- Data source type & version: ClickHouse 22.7.2.15
- OS Grafana is installed on: Linux 5.15.0-43-generic 46-Ubuntu SMP
- User OS & Browser: macOS Monterey, Google Chrome 105.0.5195.125 (Official Build) (arm64)
- Grafana plugins: just built-in plugins

**Comment by mvsousa** [comment]
@breslavsky Hi how are u ?
I tried to reproduce here but the error did not happen, maybe updating the grafana or the datasource might help

Grafana version tested:
Version: 9.3.0pre

ClickHouse version tested:
ClickHouse 22.10.1.526 (revision: 54467, git hash: 105b210126d9c1fb0e80095755b2f237afd74403, build id: <unknown>)

**Comment by breslavsky** [comment]
@mvsousa thanks I am fine. Hope you too.

I have upgraded to grafana: 9.1.5 (last available stable image on docker hub) and fully reproduced a bug :-(

https://tinyurl.com/2g89bjxf

**Comment by breslavsky** [comment]
I have updated  to `9.3.0-beta1` and problem is still here :-(

I think this bug is connected also with https://github.com/grafana/grafana/issues/55718

**Comment by mostenberg** [comment]
I've seen similar issue. When I use hard code the value, the query works. When I use a variable, the query fails with 'missing columns'. It looks like it's erroneously adding the value of the variable to the list of 'required columns': 
![image](https://github.com/grafana/grafana/assets/3945004/30617ca9-3081-4765-b1ef-165f98e123d0)
![image](https://github.com/grafana/grafana/assets/3945004/6928203d-4df1-4b0e-8c9e-4142a402e429)
