### ISSUE TITLE
Edits to a Panel's Alert tab do not cause the Panel to be Updated until the Browser Page is Refreshed

### ISSUE THREAD

**Issue by mattparkes** [grafana/grafana#55713]
**What happened**:

An update of the the frontend cache/properties of a panel doesn't seem to be triggered when a panel's Alert tab is updated, even if the Dashboard is saved.

It _does_ however correctly occur when e.g updating the Title of the Panel and clicking Save. (In fact, updating the Title _and_ the Alert causes the correct behaviour, where the object is refreshed, including the Alert tab).

**What you expected to happen**:

I expect my most recent edits to the Alert panel to be shown when re-editing that Panel, without having to refresh the entire browser page.

**How to reproduce it (as minimally and precisely as possible)**:

Bugged Path:
1. Create a new Dashboard and create a new panel, for e.g `count(kube_pod_info)` and call it "`Test`" and click Save to Save the whole dashboard.
2. Create an Alert (e.g `avg(A) >0`)and click `Save`.
3. Click the Back arrow at the top of Grafana
4. Edit the Panel and it will show `Alerts (0)` and if you click on the Alerts Tab, there are no Alerts configured.
5. Refresh the browser and it will show `Alerts (1)` and your alert will be there

![Kapture 2022-09-26 at 14 04 09](https://user-images.githubusercontent.com/4359576/192191746-6ff4bed2-4bbb-4cd9-a928-d916ac849010.gif)

Working Path:
1. Create a new Dashboard and create a new panel, for e.g `count(kube_pod_info)` and call it "`Test`" and click Save to Save the whole dashboard.
2. Change the Panel name (for example) and then (without clicking Save yet) go create an Alert and then click `Save`. _(Note that the name immediately updates with the new name)_
3. Click the Back arrow at the top of Grafana
4. Edit the Panel and it will show `Alerts (1)` and your alert

**Anything else we need to know?**:

I have reviewed the Network Requests and Console of my browser and both the working and non-working path are identical (e.g the POST to `/api/dashboards/db/` and nothing else relevant), which leads me to believe this is entirely a front end issue.

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux / Docker
- User OS & Browser:M1 Mac (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)
- Grafana plugins: MetaQueries, MultiStat, Treemap

**Comment by dprokop** [comment]
@mattparkes indeed, this is a front-end-only issue. I was wondering - have you considered switching to unified alerting (https://grafana.com/docs/grafana/v9.0/alerting/migrating-alerts/) ?

**Comment by dprokop** [comment]
@mattparkes I'll close this issue as we do not plan to introduce a fix for the legacy alerting and we encourage people to use the unified alerting going forward.
