### ISSUE TITLE
Variable in MQL not working

### ISSUE THREAD

**Issue by shi-ron** [grafana/grafana#55717]
**What happened**:
Variable in MQL returns no data

**What you expected to happen**:
Variable in MQL should work

**How to reproduce it (as minimally and precisely as possible)**:
![mql-text](https://user-images.githubusercontent.com/74239685/192217806-95fbb5ee-8f94-401c-8a6f-5077e19ff782.png)

![mql-var](https://user-images.githubusercontent.com/74239685/192216343-7077a142-3e3e-436b-99bf-9fd83731a1ac.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Google Cloud Monitoring
- OS Grafana is installed on: Docker container in kubernetes
- Grafana plugins: vonage-status-panel, agenty-flowcharting-panel, yesoreyeram-boomtable-panel, jdbranham-diagram-panel, briangann-gauge-panel, camptocamp-prometheus-alertmanager-datasource, doit-bigquery-datasource
- Others:

**Comment by sunker** [comment]
Don't think this is supported at the moment, but should be a simple thing to add.

**Comment by aangelisc** [comment]
Thank you for the report @shi-ron, I'll add this to our backlog to look at implementing and we will keep this issue updated 👍🏽

**Comment by andresmgot** [comment]
hi @shi-ron,

I tried to reproduce this but I can't, this should be working already. If you click on the query inspector, you should be able to see the final query being sent to the API. For example, here I have `query0` which is being properly replaced by `foo`:

![Screenshot from 2022-10-06 13-07-19](https://user-images.githubusercontent.com/4025665/194298067-203d0000-6656-4743-a22d-0910ba7fe44a.png)

What do you see in the query inspector? (Maybe there is a typo in the name of the varible `$node`?

**Comment by shi-ron** [comment]
After another try it works now. I don't know what's the cause. Anyway, I can close this issue for now.
