### ISSUE TITLE
Bug: Timestamps in "all series" tooltips show wrong time in sparse graphs.

### ISSUE THREAD

**Issue by sblatnick** [grafana/grafana#5572]
When there is a lot of data, the timestamps look right, but sparse graphs seem to show the wrong time in the tooltip only when Display=>Tooltip mode is set to "All series".
For example, notice how both points show 15:00 hours:
![first](https://cloud.githubusercontent.com/assets/2575534/16787105/e39b540a-4856-11e6-8d07-196b3108002b.png)
![last](https://cloud.githubusercontent.com/assets/2575534/16787107/e5df861e-4856-11e6-9a1c-04fc9af7be0c.png)

**Comment by torkelo** [comment]
The All series tooltip is not recommended for sparse data yet, use single series tooltip. 

There is already a bug report for this :)
https://github.com/grafana/grafana/issues/3063

**Comment by sblatnick** [comment]
Ok, sorry for the repost.  I didn't see that one.
