### ISSUE TITLE
grafana 7.5.12 edit expr faild,can`t use

### ISSUE THREAD

**Issue by hbzhu** [grafana/grafana#55720]
grafana 7.5.12 ，

In a day or two I editd grafana dashboard, I find the expression become messy code,such as "sum﻿(﻿nginx_http_connections﻿)" ,the value can`t show,when I checkd the json file of that dashboard ,I found the expr was 
"sum� ﻿(﻿�nginx_http_connections﻿�) 

I upgrated grafana to 8.5.13,the old dashboard can displayd   sum �(﻿�nginx_http_connections﻿�)   in browser

**Comment by usmangt** [comment]
Hi @hbzhu,

Sorry but reading your comment here seems to tell that in your previous Grafana version 7.5.12, the dashboard was not showing the result.

But, after you updated the Grafana to ver. 8.5.13 it then shows the result correctly on the Dashboard?

Did I understand it correctly or incase if this is not the case then please let us know.

**Comment by hbzhu** [comment]
Yes，I can edit datasource such as elasticsearch，Prometheus in safari browser，When I edited in chrome ，the dashboard json file show sum� ﻿(﻿�nginx_http_connections﻿�)，Show more �

Grafana-7.5.12  I  used  for about a year, it came up recently，I don't know what caused it，I've tried a lot of environments ，when I edit, the cursor will suddenly appear at the end，I can confirm that the Chrome browser has not been updated recently

<img width="357" alt="微信图片_20220926154300" src="https://user-images.githubusercontent.com/8680035/192666945-63597301-f627-4a16-9616-c5a01c4fab7f.png">

![image](https://user-images.githubusercontent.com/8680035/192667010-5fad9333-fc20-494c-8dcf-3ad77bd7cd8f.png)

**Comment by usmangt** [comment]
Hi @hbzhu,

Thanks for the reply. So these special symbols  � only appear when using the Chrome browser but not on Safari.

Can you please tell us the version of the Chrome browser you are using?

Also, paste a screenshot from the Safari browser so that can see what they look like in real which gets broken in Chrome?

Thanks

**Comment by hbzhu** [comment]
chrome version 106.0.5249.103

**Comment by gelicia** [comment]
I'm pretty sure this is a result of #54535 


@hbzhu Does this sound like what might have happened? 
# Using grafana 7.5.12. Chrome updates and breaks the code editor as documented in #54535 
# Attempt to edit some queries and save them with the bug with the cursor/unreadable characters
# Update to grafana 8.5.13 which fixes the chrome bug. You now can edit/save queries as intended but some bad data was saved from before the upgrade

**Comment by hbzhu** [comment]
Thank you ，I will try to upgrade Grafana 7.5.13 or later

**Comment by gelicia** [comment]
Please reopen this ticket if this ends up not solving your issue. Thanks!

**Comment by hbzhu** [comment]
@gelicia I upgraded 7.5.17, It's OK ，Thank you
