### ISSUE TITLE
Alerting labels  don't enriched

### ISSUE THREAD

**Issue by Nexy3gpp** [grafana/grafana#55748]
**What happened:**
I'm using Grafana alerting. Config: 
`[unified_alerting]
enabled = true
admin_config_poll_interval = 60s
alertmanager_config_poll_interval = 60s
ha_advertise_address = ""
ha_peers = ""
ha_peer_timeout = 15s
ha_gossip_interval = 200ms
ha_push_pull_interval = 60s
execute_alerts = true
evaluation_timeout = 30s
max_attempts = 3
min_interval = 10s`

The alert setting:
![image](https://user-images.githubusercontent.com/49400660/192285896-c9776767-004e-4e91-8e35-f20d38093355.png)
![image](https://user-images.githubusercontent.com/49400660/192286016-eebe64e0-c3d9-45dc-a8ad-0ec70c91f35d.png)

But labels don't enriched
![image](https://user-images.githubusercontent.com/49400660/192287386-506137c3-4062-4e2a-93b3-10fdcd57cb03.png)

**What you expected to happen:**
I'm waiting for the value of the labels.

**Anything else we need to know?:**
Version Grafana 9.1.5 
Preview alert:
`[ var='B0' metric='test1-01 /home' labels={__name__=disk_used_percent, device=/home, fstype=xfs, host=test1-01, mode=rw, path=/home} value=87.3928560476 ]`

**Comment by RavianXReaver** [comment]
I'm having the same issue. I'm not only able to refer to labels, but also the value of the expression.
Version: v9.1.4 (2186d0bbeb)

**Comment by feelan03** [comment]
I have this problem too

**Comment by xom4ek** [comment]
ex `{{$Labels.target))`

Big letter `Labels`

**Comment by Nexy3gpp** [comment]
![image](https://user-images.githubusercontent.com/49400660/197873789-98abad51-483d-4e21-a222-ab976525adf0.png)

**Comment by xom4ek** [comment]
@Nexy3gpp so your alert didnt have label `path` and `host`.

You can use `preview alerts` for check where your alerts contains any `labels` and `values`

![image](https://user-images.githubusercontent.com/29627495/197931937-6487fd05-0f2c-4f9b-b95a-fcc36968bfbd.png)

**Comment by Nexy3gpp** [comment]
My alert has :
[ var='B0' metric='test1-01 /home' labels={__name__=disk_used_percent, device=/home, fstype=xfs, host=test1-01, mode=rw, path=/home} value=87.3928560476 ]


When I use Classic Condition it doesn't work. But i need it

**Comment by santihernandezc** [comment]
@Nexy3gpp The `$labels` variable is not supported when using Classic Conditions, because those don't emit labels. This is due to Classic Conditions being unidimensional.
You can use another type of expression to make your alert rule [multi-dimensional](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule).
