### ISSUE TITLE
State timeline hover areas incorrect when zooming on page

### ISSUE THREAD

**Issue by bucovaina** [grafana/grafana#55743]
**What happened**:
I'm trying out State timeline and noticed that the areas highlighted when you hover over the panel are not correctly "overlay-ed" when you zoom in with your browser (CMD +). When you reset the zoom to "0", the overlay-ed areas match again.

**What you expected to happen**:
The overlay-ed areas to match at all "reasonable" zoom levels.

**How to reproduce it (as minimally and precisely as possible)**:
1. Zoom level 0: Hover with mouse over the state timeline area to highlight areas. Conclude all is good.
2. Zoom level 1: Zoom in one step with your Firefox Browser.

**Anything else we need to know?**:
Firefox version I'm running is attached. I have also tried this in Safari but I cannot reproduce the issue in Safari. I have tried private mode in Firefox (plugins disabled): same issue

Zoomed in 1 step:
This shows there's something "skewed"
![Screenshot 2022-09-26 at 14 29 04](https://user-images.githubusercontent.com/42909233/192280324-fb414e6b-928d-45c6-8203-8cc085c63cbd.png)

Zoom level 0:
This looks right to me:
![Screenshot 2022-09-26 at 14 48 14](https://user-images.githubusercontent.com/42909233/192280471-fd6c6ba5-fe82-4d12-abe8-4f54c0a3b37d.png)

![Screenshot 2022-09-26 at 14 47 25](https://user-images.githubusercontent.com/42909233/192280326-b3ddd7a5-a679-456b-9dff-18f6ec43c301.png)

While creating the issue I was running 9.1.5 while I thought I was in 9.1.6. I did the actual upgrade and still have the same issue.

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Influx 1.8.10
- OS Grafana is installed on: Raspbian GNU/Linux 11
- User OS & Browser: Macos 12.6
- Grafana plugins: None
- Others:

**Comment by codeincarnate** [comment]
Unfortunately supporting different zoom levels is a non-trivial task and would require significant changes to our underlying plotting library (uPlot). While it's on our radar it may be some time before this can be implemented in a way the works nicely across various browsers.

I'll keep this open for tracking purposes, but adding full zoom support to uPlot is quite a mountain to climb.

**Comment by bucovaina** [comment]
Thanks for coming back to this. 

It's not a critical issue but nice to know it's on the radar 👍 .

**Comment by leeoniya** [comment]
i wouldn't call it a "mountain" exactly :D

https://github.com/grafana/grafana/pull/57224

**Comment by bucovaina** [comment]
@leeoniya : great thanks for fixing this 👍
