### ISSUE TITLE
blog posts become inaccessible after a while

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#5575]
the blog - http://grafana.org/blog/ - only shows the most recent blog posts, there's no "older" or "archive" link.
this is annoying for people who may be stuck with a very old grafana version and want to look up older release announcements, or people who look for older content for whatever reason, there's useful stuff there, bummer it becomes inaccessible!

**Comment by torkelo** [comment]
interesting, had not noticed that. Wonder when that went away.

**Comment by torkelo** [comment]
fixed now :) 
http://grafana.org/blog/
