### ISSUE TITLE
Proxying http datasource don't work if grafana is hosted on https

### ISSUE THREAD

**Issue by bbinet** [grafana/grafana#5576]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request

Please include this information:
- What Grafana version are you using? => 3.1.0 and 3.0.4
- What datasource are you using? => InfluxDB
- What OS are you running grafana on? => Debian Jessie
- What did you do? Add a new proxied (access=proxy) InfluxDB datasource which url looks like **http**://my.datasource while my grafana instance url looks like **https**://my.grafana.instance
- What was the expected result?
=> Datasource test should work when saving my new datasource
- What happened instead?
=> Datasource test failed with the following error message:
"Unknown error
InfluxDB Error Response: Internal Server Error"

Note that if I change the "Access" value from "proxy" to "direct", it works.

**Comment by torkelo** [comment]
Is your InfluxDB data source accessible from the grafana server? any info in the log? Many are running Grafana behind https with no issues, so this sounds strange.

**Comment by bbinet** [comment]
Yes, if I use curl to query my InfluxDB datasource from the Grafana instance, it works.

**Comment by bbinet** [comment]
And here is the grafana log when I hit the "Save & Test" button:
```
2016/07/13 12:39:52 http: proxy error: dial tcp 91.121.116.114:18086: i/o timeout
t=2016-07-13T12:39:52+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=3 uname=admin method=GET path=/query status=500 remote_addr="172.19.0.1, 172.18.0.5" time_ns=30.001µs size=0
```

**Comment by torkelo** [comment]
looks like it's getting an io timeout. 91.121.116.114:18086  , is that the correct port?

**Comment by bbinet** [comment]
Yes, the port 18086 is correct, and curl can query data from there.

**Comment by torkelo** [comment]
not sure then what could be the cause, in the issue title you mention https, had you tried it without https and it worked?

**Comment by bbinet** [comment]
Sorry, I ran curl on the wrong server: it does not work actually with curl either.
It seems to be a firewall configuration issue on my side.
Sorry for the noise.
