### ISSUE TITLE
grafana api set-home-dash

### ISSUE THREAD

**Issue by xploit42** [grafana/grafana#5577]
Hello,

I'm scripting the creation of users organisations and dashboards and I'm stuck on the setting of the orgs home dashboard.

I manualy add the home dashboard on Main Org, his name is "Home Dashboard" and his id is 56.

Now with the api i change actual org to the org named "test", i do a put on the endpoint /api/org/preferences with data: '{"theme":"","homeDashboardId":56,"timezone":""}'
It return {"message":"Preferences updated"}
I'm fine.

But when i try to get this dashboard on Grafana, i get an error message: "Dashboard not found"

I think it's because the dashboard is not linked with the org "test", is there a solution? An easy way to set the "Home Dashboard" by default to all orgs?

regards

**Comment by torkelo** [comment]
Organizations are isolated islands in Grafana (only share users), dashboards & data sources are only linked to one organization, so one dashboard cannot be accessed by another organization,
