### ISSUE TITLE
Alerting - duplicate a panel with an alert vs copy panel and paste from clipboard - results in different JSON

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#55786]
**What happened**:
duplicate panel vs copy and paste a panel with an alert results in different JSON structure

**What you expected to happen**:
The panel JSON structure is identical

**How to reproduce it (as minimally and precisely as possible)**:
Take a panel with an alarm
Action 1: dulicate the panel
Action 2: copy the panel and use "Add panel", "Paste panel from clipboard"

**Anything else we need to know?**:
Look at the JSON of the two new panels with "Inspect", "Panel JSON" and compare them
What is your desired behavior? Should alarms be copied with a copy or duplicate action?

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Prometheus
- OS Grafana is installed on: docker container
- User OS & Browser: Windows 10, Browser: Chrome
- Grafana plugins:
grafana-clock-panel/
grafana-image-renderer/
grafana-piechart-panel/
grafana-polystat-panel/
grafana-simple-json-datasource/
grafana-singlestat-panel/
jdbranham-diagram-panel/
monitoringartist-monitoringart-datasource/
natel-plotly-panel/
novalabs-annotations-panel/
radensolutions-netxms-datasource/
ryantxu-ajax-panel/
savantly-heatmap-panel/
vonage-status-panel/
- Others:

**duplicate vs copy & paste JSON Structure**

***duplicate***
![duplicate](https://user-images.githubusercontent.com/56024424/192444527-9899da95-a052-4350-b7c9-c0ab20892681.gif)
***copy & paste***
![copy and paste from clipboard json](https://user-images.githubusercontent.com/56024424/192444577-b5d7c73b-a096-4f59-a492-7cc8238598ed.gif)
***copy & paste expanded***
![copy and paste from clipboard json expand](https://user-images.githubusercontent.com/56024424/192444696-c94fd4d1-296e-4a27-9d49-10bf807b880e.gif)

**Comment by armandgrillet** [comment]
This is an issue with legacy alerting only which is deprecated, please migrate to Grafana Alerting: https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/
