### ISSUE TITLE
Support custom timezone selection 

### ISSUE THREAD

**Issue by Zert** [grafana/grafana#558]
Is it possible to configure Grafana to always show only server time? I.e. if event has appeared in 00:00 on server, I want to see it only in 00:00 in Grafana independently on my browsers local timezone, which may be changed.

**Comment by victorhooi** [comment]
Vote from me as well!

Would be great to have a drop-down to allow you to toggle timezones for the currently displayed graph.

On the InfluxDB side - this looks interesting:

https://github.com/influxdb/influxdb/issues/2074

(Sidenote, I wish Github had a vote or +1).

**Comment by olourkin** [comment]
Add my vote for this - and I'd personally be more interested in a global setting rather than something that needed to be set on every dashboard.

**Comment by pasancario** [comment]
I think, just a new dropdown selection in 
![image](https://cloud.githubusercontent.com/assets/811713/11839152/e38c226a-a3eb-11e5-8aaf-a0ccab3c15ab.png)
with all timezones will be needed. It can be in an additional dropdown like: 

![image](https://cloud.githubusercontent.com/assets/811713/11839276/c3f06744-a3ec-11e5-803e-e24495332697.png)

**Comment by xneo64** [comment]
+1 
We offer support for various geographically varied offices and it's quite confusing for them to look at snippets set in our timezone. A TZ selection per dashboard would be the best solution - if not, at least a globally configurable one.

**Comment by ldep30** [comment]
Voting for this feature too ! Being able to specify a custom TZ would be awesome.

**Comment by sbarale** [comment]
+1 (maybe a tad late? ) lol
Keep up the awesome work.

**Comment by linar-jether** [comment]
+1

**Comment by svetlina** [comment]
+1

**Comment by x3m** [comment]
+1

**Comment by hhallman** [comment]
+1

**Comment by pierluca** [comment]
+1

**Comment by decentlab** [comment]
87207b2 extends the timezone list with fixed offsets. This is highly experimental WIP implemented only for graph panel (flot). There are things to decide beforehand like: whether timezone names or fixed offsets (timezone != offset) should be used, which library to use moment-timezone (grafana uses momentjs) or timezone-js (flot uses timezone-js).

**Comment by PaulKuiper** [comment]
Fixed offsets are not very usefull. This would mean you have to change the offset when day light savings change. Best option is a list of geographical zones. See for example: https://momentjs.com/timezone/docs/#/zone-object/name/
Extending the timezone selection box with a dropdown search box at organisation level and dashboard level would be the best option.

**Comment by torkelo** [comment]
The problem is that that library is so humongous :(

**Comment by PaulKuiper** [comment]
25.6kB for the minimized all years version. 
Not ideal, but ok if good caching or CDN is used.

**Comment by torkelo** [comment]
that is not so bad, last time I checked it was much larger, maybe they found away to minimize the huge database it contains.

**Comment by PaulKuiper** [comment]
To be honest it is minimised AND gz zipped. If you pull it into your own project in full glory it will  be much larger.

**Comment by decentlab** [comment]
To use flot with custom timezones you probably have to load timezones in timezoneJS too. It offers lazy loading scheme by the way.

**Comment by Codelica** [comment]
Might be another potential option for TZ math..  https://github.com/bigeasy/timezone

Certainly small enough :)

**Comment by flyingvince** [comment]
+1 for timezone support for either dashboard or panels (fixed offsets do not help us due to possible DST issues).

**Comment by flavianc** [comment]
+1 for this feature. It's very much needed for geolocated services

**Comment by maciejasembler** [comment]
+1 for it

**Comment by JonasGutermuth** [comment]
It would also be useful, to use the timezone from a template variable.

**Comment by jsedy7** [comment]
+1

**Comment by terrillmoore** [comment]
+1 -- using Grafana to display environmental data at a given location, it's really painful for users to have to deal with converting to the timezone where the measurement was taken... and local time (for correlating when people come to work, etc.) is really important. (Grafana is lovely, and we'll deal anyway... but it sure would be nice.)

**Comment by irfansharif** [comment]
+1

**Comment by kushagraSahu** [comment]
+1. Just adding the feature of fixed offset won't help due to DST.

**Comment by gealtrag** [comment]
+1 It's a very much needed feature. Global TZ selection is a must.

**Comment by perostgard** [comment]
+1 Timezone support would be great

**Comment by tammytankian** [comment]
+1

**Comment by rajakadali4134** [comment]
+1, TZ feature might be one of the needed features.

**Comment by dexy31337** [comment]
+1 on this one. I was fiddling with Telegram alerts (with external GCS image storage) and what It get is message timestamp and times on image differ (I'm in UTC+3).
<img width="586" alt="banners_and_alerts_and_telegram" src="https://user-images.githubusercontent.com/98269/32694172-10f85b46-c74a-11e7-8691-92e4c5af6124.png">

**Comment by psellers89** [comment]
+1

**Comment by growler** [comment]
+1
We do monitor plenty of services around the globe and that would be way more useful to see a dashboard in a time zone local to the service being monitored, not to UTC or my own. I'm perfectly aware about my own time, but every time I see a spike it takes some efforts to put it in context and calculate the local time.

**Comment by AndrewStickler** [comment]
+1  yes please!

**Comment by loic-sz** [comment]
Would be great +1

**Comment by smalik03** [comment]
+1

**Comment by chron0** [comment]
+1 - we have most on UTC but due to _reasons_ a couple of boxes have to be PST which makes time matching a pain. https://github.com/grafana/grafana/issues/558#issuecomment-165067470 seems like a good solution for it.

**Comment by nayeemnayyu** [comment]
+1

**Comment by lior-jether** [comment]
+1

**Comment by chrismusty** [comment]
+83748927398479273947

**Comment by kobuskleynhans** [comment]
+1

**Comment by vlsoprun** [comment]
+1

**Comment by Tobias007** [comment]
+1

**Comment by otherpirate** [comment]
+1

**Comment by raykamp** [comment]
+1

**Comment by Hyruu** [comment]
+1
While doing a per-dashboard selection might be a lot to do, as a quick first step the solution @pasancario suggested would already help a lot of use cases. I have a use case where I show monitoring data to a specific client, who might not be physically present in the same timezone as the server they want to monitor, ending up in confusing screens for them. Allowing them to specify the timezone they want instead of either UTC or their own time would be a huge plus.

**Comment by johnhtodd** [comment]
+1 - Having the ability to quickly change offset via a pulldown in the "Time Range" box would be amazing, as I would like to quickly convert timezone offset while on the phone with people debugging problems (time waste: "It was at 23:39 in my timezone which is... uh... hang on, are you in daylight savings?")

**Comment by nirwander** [comment]
+1
It should be in priority list

**Comment by VitalySolntsev** [comment]
we're still waiting for it

**Comment by shalstea** [comment]
+1

**Comment by urkele** [comment]
+1
This is a great start: https://github.com/grafana/grafana/issues/558#issuecomment-165067470

**Comment by mmatson** [comment]
+1

This is a super useful feature for us to publish the beautiful metrics coming from Grafana. As it is now, in order for me to have this data meaningful for our business users, we have to export the data, time shift the data in different zones and re-assemble the graphs.

I would take the timezone offset approach (vs the conical names that deal with daylight savings) if it is an easier implementation. I can manage changing the timezone displayed 2x year.

**Comment by RudW0lf** [comment]
+1

**Comment by lordorfan** [comment]
+1, please

**Comment by Tobias007** [comment]
+1, would be so useful

**Comment by AlexMabry** [comment]
+1

**Comment by rhlnair87** [comment]
+1

**Comment by onggie** [comment]
+1, really need this feature as we share dashboards across multiple sites in multiple countries.

**Comment by samhatchett** [comment]
+1 - all use cases mentioned are really valid and important. Also would advocate for fixed-offset zones, as we have users who need this.

**Comment by gzhukov** [comment]
+1

**Comment by ryanjohara** [comment]
+1 West, central, and northeast divisions require different timezones.

**Comment by louiesjian1993** [comment]
+1

**Comment by knoguchi** [comment]
I'm hoping that Grafana will support per panel, dashboard, and user level timezones.  But not sure which one can override which level.

For the time being I'm using "Change Timezone" extension in Google Chrome browser.  I suggest that you create a dedicated profile in Chrome for Grafana so you wouldn't be in a wrong TZ accidentally. 

https://chrome.google.com/webstore/detail/change-timezone-time-shif/nbofeaabhknfdcpoddmfckpokmncimpj

**Comment by reactcker** [comment]
+1

**Comment by KristapsR** [comment]
I have time offset information in database and made variable in grafana dashboard.
I thought to use it in time shift parameter, but I can't do that also.
That would be very convenient.

**Comment by Orjanp** [comment]
Would also like to see this.

**Comment by maoyaowu** [comment]
+1 from me as well. Would also like to see this.

**Comment by Tobias007** [comment]
+1 again

**Comment by ortizleo** [comment]
+1 Please.

**Comment by timothyasp** [comment]
+1

**Comment by vnikolaenko** [comment]
+1

**Comment by leggerf** [comment]
+1

**Comment by M0rdecay** [comment]
+1

**Comment by AirmakZ** [comment]
+1
I cannot use Quick Ranges that are using "NOW" because UTC is set in the query (2 hours wrong in summer or 1 hour wrong in winter)
What I cannot understand why there is setting in the dashboard that even is making "UTC" when this TimeZone is selected... (v6.2.0-beta2 (7824f66))
Even I set 'default' or 'local browser time' always UTC is inserted in the QUERY by function '$__timeFilter'

**Comment by mvalletta** [comment]
+1

**Comment by wbworks** [comment]
+1

**Comment by woot365** [comment]
+1 could really do with this being added.

**Comment by nogoltsovdev** [comment]
+ 1

**Comment by liferili** [comment]
+1

**Comment by everfeng** [comment]
+1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sza2** [comment]
+1

**Comment by antipooh** [comment]
+1

**Comment by Razikus** [comment]
+1

**Comment by pseudocoder** [comment]
Simple option - rather than (or in addition to) fixed offsets, just allow a user specific string for the timezone.  For cases where the browser timezone doesn't match anything the server recognises, and to fix it regardless of browser.

e.g. in my case this would be "Europe/Zurich".

**Comment by patrickjuchli** [comment]
We need support for IANA timezones for correct handling of DST. Libraries like [Luxon](https://github.com/moment/luxon) don't need to include all the TZ data. 

Our use case: We have many energy storage systems all over the world. Looking at data we always want to see it in the timezone of the storage system.

**Comment by GameOfThrow** [comment]
+1

**Comment by chitwan-malhotra** [comment]
+1

**Comment by tsarajar** [comment]
+1

**Comment by Dylantje** [comment]
+100

**Comment by gmcdowelli3logix** [comment]
+1

**Comment by huynhphuong10284** [comment]
+1

**Comment by Grant-Visser** [comment]
+1

**Comment by Artiiz-ZA** [comment]
+1

**Comment by yogi4u** [comment]
+111

**Comment by Shanginre** [comment]
+1 I need this too!

**Comment by juanjo-s2** [comment]
I also vote for this feature.

**Comment by STYNET** [comment]
Hello,
I have installed the stack Prometheus and Grafana with Helm (prometheus-community/kube-prometheus-stack).
I set the timezone Grafana (Configuration > Preferences > Timezone : Europe/Paris (UTC+02:00) ).
But the graphs are always on UTC.
Any idea ?
