### ISSUE TITLE
Race condition when saving snapshots

### ISSUE THREAD

**Issue by caldwell** [grafana/grafana#5582]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
3.1.0-1468321182
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Debian

This code in  grafana/public/app/features/dashboard/shareSnapshotCtrl.js contains a race condition that I'm running into:

```typescript
    $scope.createSnapshot = function(external) {
      $scope.dashboard.snapshot = {
        timestamp: new Date()
      };

      $scope.loading = true;
      $scope.snapshot.external = external;

      $rootScope.$broadcast('refresh');

      $timeout(function() {
        $scope.saveSnapshot(external);
      }, 4000);
    };
```

It just waits 4 seconds and hopes that all the data is loaded by that point. I'm running on a constrained server where most of the queries on my dashboard are taking longer than 4 seconds to complete (the longest takes 24 seconds), and so none of that data gets saved.

Ideally this code should instead wait for things to finish (however long it takes) and only then save the snapshot.

**Comment by torkelo** [comment]
yes, currently all queries need to complete within 4 seconds. 

There is already an issue for this:
https://github.com/grafana/grafana/issues/2537
