### ISSUE TITLE
How To configure InfluxDB and grafana

### ISSUE THREAD

**Issue by sincsc** [grafana/grafana#5583]
hi all：
 I am new, I meet a question and I do not know how to configure InfluxDB and Grafana. In Grafana, I create a data source and choice the type InfluxDB , but I meet the question "Unknown error
InfluxDB Error: undefined", so I think it is because I make a mistake in configuration, but I don't know where the error is, Looking forward to your answer

**Comment by torkelo** [comment]
make sure the InfluxDB url and port is correct and reachable, did you specify access direct or proxy?

**Comment by sincsc** [comment]
thanks for your answer.  I'm sure the InfluxDB url and port is correct because I can visit it  in the browser like this http://InfluxDBurl : port, the default access is proxy and I don't change it. my operate system
is Ubuntu14.04  64-bit, and InfluxDB version is V0.13.0 and grafana version is V3.0.4, I install both of them like this way: wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb, so I don't know whether need I configure some config in their config file, thank you
