### ISSUE TITLE
Context Menu fails to open on Graph View when clicking on a node

### ISSUE THREAD

**Issue by perotta** [grafana/grafana#55838]
**What happened**: Context Menu is not appearing when left click nodes on Node Graph View. Curiously, it works as expected when on Grid View

**What you expected to happen**: Context menu to show on node click

**How to reproduce it (as minimally and precisely as possible)**: Left click any node on Graph View. Nothing happens

**Anything else we need to know?**: Reproduced it with a fresh install of Grafana on Debian 11 (installed through apt)

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Test Data DB
- OS Grafana is installed on: Debian 11
- User OS & Browser: Ubuntu 20.04 LTS & Chrome Version 105.0.5195.125 (Official Build) (64-bit) also tried Firefox version 104 (64-bit)
- Grafana plugins: Node Graph
- Others:

![image](https://user-images.githubusercontent.com/45238586/192552664-471c09d4-1a78-46d6-9638-f00d5544a95e.png)

**Comment by aocenas** [comment]
At this moment we don't show the context menu if there aren't any links to show https://github.com/grafana/grafana/blob/1a0cbdeabe9d68e3263d3a82dcd3789e3439684b/public/app/plugins/panel/nodeGraph/useContextMenu.tsx#L86. In grid view though we also always add a link to switch back to graph view. This probably looks a bit inconsistent and also as there can be some other info in the context menu does not make that much sense anymore. Probably makes sense to just show the context menu always, even if there is nothing to show (just show something like <no details> or something) for the sake of consistency.
