### ISSUE TITLE
winxp ff37.0 shows BLANK page only...

### ISSUE THREAD

**Issue by biopilz** [grafana/grafana#5584]
* **I'm submitting a ...**
- [x] Bug report ...

see http://ffka.xylou.info/#/dashboard/file/pernode.json?var-Knotenname=ffka-linkes-zentrum-R12

the "source-code" my browser offers is as follows:

+ + +

<!DOCTYPE html>
  
   <html class="no-js" lang="en"> 
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="google" value="notranslate">

    <title>Grafana</title>
    <link rel="stylesheet" href="css/grafana.dark.min.21253ffa.css" title="Dark">
    <link rel="icon" type="image/png" href="img/fav32.png">

    <script src="app/app.496fdc2e.js"></script>

    <script>require(['app'], function (app) { app.boot(); })</script>

  </head>

  <body ng-cloak ng-controller="GrafanaCtrl">

    <link rel="stylesheet" href="css/grafana.light.min.81a2958f.css" ng-if="grafana.style === 'light'">

		<div class="page-alert-list">
			<div ng-repeat='alert in dashAlerts.list' class="alert-{{alert.severity}} alert">
				<button type="button" class="alert-close" ng-click="dashAlerts.clear(alert)">
					<i class="icon-remove-sign"></i>
				</button>
				<div class="alert-title">{{alert.title}}</div>
				<div ng-bind-html='alert.text'></div>
			</div>
		</div>

		<div ng-view></div>

	</body>
</html>

+ + +

yes, addblocker disabled, all scripts allowed...

and: NO, i dont want to change my system...

**Comment by torkelo** [comment]
any js errors in console?

Any change to upgrade to newer firefox version?

**Comment by biopilz** [comment]
thanks for reply:
i have no idea of detail of js:
just mark, copy, pasted what a console of this tab shows:
is this of interest?
+ + +

"Error: window.localStorage is null
.getBool@http://ffka.xylou.info/app/app.496fdc2e.js:19:3053
@http://ffka.xylou.info/app/app.496fdc2e.js:21:13778
e@http://ffka.xylou.info/app/app.496fdc2e.js:8:23325
_b/this.$get</</<@http://ffka.xylou.info/app/app.496fdc2e.js:9:11768
v/<@http://ffka.xylou.info/app/app.496fdc2e.js:9:2681
f@http://ffka.xylou.info/app/app.496fdc2e.js:8:6707
v@http://ffka.xylou.info/app/app.496fdc2e.js:9:2665
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30825
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30842
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30842
F/<@http://ffka.xylou.info/app/app.496fdc2e.js:8:30321
$/h/</<@http://ffka.xylou.info/app/app.496fdc2e.js:8:12316
Rc/this.$get</l.prototype.$eval@http://ffka.xylou.info/app/app.496fdc2e.js:10:6192
Rc/this.$get</l.prototype.$apply@http://ffka.xylou.info/app/app.496fdc2e.js:10:6406
$/h/<@http://ffka.xylou.info/app/app.496fdc2e.js:8:12274
e@http://ffka.xylou.info/app/app.496fdc2e.js:8:23325
$/h@http://ffka.xylou.info/app/app.496fdc2e.js:8:12195
$@http://ffka.xylou.info/app/app.496fdc2e.js:8:12481
f.boot/</<@http://ffka.xylou.info/app/app.496fdc2e.js:15:3668
_.Callbacks/k@http://ffka.xylou.info/app/app.496fdc2e.js:5:22480
_.Callbacks/l.add@http://ffka.xylou.info/app/app.496fdc2e.js:5:22794
_.fn.ready@http://ffka.xylou.info/app/app.496fdc2e.js:5:24882
f.boot/<@http://ffka.xylou.info/app/app.496fdc2e.js:15:3631
newContext/u.execCb@http://ffka.xylou.info/app/app.496fdc2e.js:4:12204
newContext/t.prototype.check@http://ffka.xylou.info/app/app.496fdc2e.js:4:6453
newContext/t.prototype.enable@http://ffka.xylou.info/app/app.496fdc2e.js:4:8965
newContext/t.prototype.init@http://ffka.xylou.info/app/app.496fdc2e.js:4:5555
e/<@http://ffka.xylou.info/app/app.496fdc2e.js:4:10660
"Error: window.localStorage is null
.getBool@http://ffka.xylou.info/app/app.496fdc2e.js:19:3053
@http://ffka.xylou.info/app/app.496fdc2e.js:21:13778
e@http://ffka.xylou.info/app/app.496fdc2e.js:8:23325
_b/this.$get</</<@http://ffka.xylou.info/app/app.496fdc2e.js:9:11768
v/<@http://ffka.xylou.info/app/app.496fdc2e.js:9:2681
f@http://ffka.xylou.info/app/app.496fdc2e.js:8:6707
v@http://ffka.xylou.info/app/app.496fdc2e.js:9:2665
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30825
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30842
h@http://ffka.xylou.info/app/app.496fdc2e.js:8:30842
F/<@http://ffka.xylou.info/app/app.496fdc2e.js:8:30321
$/h/</<@http://ffka.xylou.info/app/app.496fdc2e.js:8:12316
Rc/this.$get</l.prototype.$eval@http://ffka.xylou.info/app/app.496fdc2e.js:10:6192
Rc/this.$get</l.prototype.$apply@http://ffka.xylou.info/app/app.496fdc2e.js:10:6406
$/h/<@http://ffka.xylou.info/app/app.496fdc2e.js:8:12274
e@http://ffka.xylou.info/app/app.496fdc2e.js:8:23325
$/h@http://ffka.xylou.info/app/app.496fdc2e.js:8:12195
$@http://ffka.xylou.info/app/app.496fdc2e.js:8:12481
f.boot/</<@http://ffka.xylou.info/app/app.496fdc2e.js:15:3668
_.Callbacks/k@http://ffka.xylou.info/app/app.496fdc2e.js:5:22480
_.Callbacks/l.add@http://ffka.xylou.info/app/app.496fdc2e.js:5:22794
_.fn.ready@http://ffka.xylou.info/app/app.496fdc2e.js:5:24882
f.boot/<@http://ffka.xylou.info/app/app.496fdc2e.js:15:3631
newContext/u.execCb@http://ffka.xylou.info/app/app.496fdc2e.js:4:12204
newContext/t.prototype.check@http://ffka.xylou.info/app/app.496fdc2e.js:4:6453
newContext/t.prototype.enable@http://ffka.xylou.info/app/app.496fdc2e.js:4:8965
newContext/t.prototype.init@http://ffka.xylou.info/app/app.496fdc2e.js:4:5555
e/<@http://ffka.xylou.info/app/app.496fdc2e.js:4:10660
" app.496fdc2e.js:9:25524
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 422ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 656ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 375ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 469ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 344ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 391ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 469ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css [HTTP/1.1 200 OK 140ms]
GET 
http://ffka.xylou.info/css/grafana.dark.min.21253ffa.css
"

+ + +


> Torkel Ödegaard <notifications@github.com> hat am 14. Juli 2016 um 15:22
> geschrieben:
> 
> 
> any js errors in console?
> 
> Any change to upgrade to newer firefox version? 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/grafana/grafana/issues/5584#issuecomment-232663419

--
http://biopilz.wordpress.com

**Comment by torkelo** [comment]
Tried upgrading firefox?
