### ISSUE TITLE
Unable to install or list plugins because of short timeout

### ISSUE THREAD

**Issue by brianburton** [grafana/grafana#5585]
All attempts to run grafana-cli to list or install plugins fail with the following message:

Error: Get https://grafana.net/api/plugins/repo: dial tcp: i/o timeout

Yet from the same system I can access the endpoint and receive JSON response.  It just takes a few seconds.  Is this extremely short timeout adjustable in some way?  I didn't see anything in /etc/grafana/grafana.ini file or in the --help output of grafana-cli.

# curl https://grafana.net/api/plugins/repo/alexanderzobnin-zabbix-app|wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1678  100  1678    0     0    283      0  0:00:05  0:00:05 --:--:--   498

There have been some other issues related to this but they were closed after some unrelated change.

Running grafana grafana-3.0.2 from yum repo on a CentOS 7 docker image.

**Comment by torkelo** [comment]
strange, unable to replicate it here :(

**Comment by brianburton** [comment]
Do you get a 5 second response time from the endpoint?  If not you won't get the timeout and won't be able to reproduce.

My question is simply can I override that very short timeout?  Is that possible?

I wound up hard coding the IP for grafana.net into /etc/hosts.  The DNS lookup appeared to be slow.  However there are two other tickets where this timeout issue came up so increasing its default will probably help others later.

**Comment by brianburton** [comment]
I modified the /etc/resolve.conf file to remove the default, slow DNS server and use a faster one.  Now these timeouts are fixed without having to hard code the IPs.  Maybe others who encountered this problem had the same root cause as me.  If so then we can probably close this.  Unless you think the timeout is something you could make adjustable in grafana?

BTW - loving grafana!  Great system for creating high quality dashboards.
