### ISSUE TITLE
org query parameter ignored and lost for authenticated orgs with RO main org

### ISSUE THREAD

**Issue by Sutrannu** [grafana/grafana#5586]
* **I'm submitting a Bug report**

- Grafana  3.1.0
- Datasources: Influx & Zabbix
- Ubuntu 12.04
- What did you do? Click link to dashboard with ?org=2 query parameter only
- What was the expected result? If the org requires login, bring the user to the login page, and then to the dashboard upon successful login.
- What happened instead? "Dashboard not found" error and org query parameter rewritten to org=1

Note: org1 is RO anonymous. All other orgs are assigned via ldap.

**Comment by torkelo** [comment]
including org name or id in url has yet to be implemented .
https://github.com/grafana/grafana/issues/1613

**Comment by Sutrannu** [comment]
If you don't mind, clarifying, the urls in 3.1.0 include the org# in the query parameter as stated above. Are you saying it is intentionally ignored? It's not. In the example above, if the user is already authenticated, the url with the org defined as a parameter will bring the user to the dashboard as expected.

**Comment by torkelo** [comment]
where do the urls include orgId ?

**Comment by Sutrannu** [comment]
To try to be clear, the URL does not technically contain the org number, depending on the technical definition of url you subscribe to. Specifically, the org parameter appears in the query string as a parameter. E,g, https://example.org/grafana/dashboard/db/my-dashboard?org=2. In that case org=2 appears in normal use defining the org, but is ignored, disabled, circumvented or otherwise rendered useless in the example I gave above.

**Comment by torkelo** [comment]
It appears? Maybe your are running a pre release build of 3.1? It does not appear in the stable release version.

**Comment by Sutrannu** [comment]
Grafana v3.1.0 (commit: cf87e8e)

**Comment by torkelo** [comment]
That could explain it, the orgId parameter in dashboard url was an experiment, not in stable release
