### ISSUE TITLE
Slowness when updating from 3.0.4 to 3.1.0 only when using multiple rows

### ISSUE THREAD

**Issue by camiloribeiro** [grafana/grafana#5587]
- [ ] Bug report

Grafana 3.1.0, using graphite 0.9.14, official grafana docker image with no changes but volumes for configuration and dashboards 

I started experiencing slowness and timeouts since I upgraded from 3.0.4 to 3.1.0 stable. My report was composed of repeated rows, each with two singelstats and two graphs. It basically stopped working due to performance issues. I did many experiments with datapoints trying to spot the issue changing queries and so on, and it kept happening, until I tried reproduced the same report, but without using rows. The same data, same datapoints, same singelstats and graphs in the same server, and it is super fast now (single row). 

ps: I tried also using only two rows, and it times out as well.

I am so sorry for not being able to provide more data, I will try to reproduce it using fake data this weekend.

**Comment by torkelo** [comment]
strange, not able to replicate it. 

http://play.grafana.org/dashboard/db/repeated-rows
