### ISSUE TITLE
Cant save span of a panel that has "Repeat Panel" field non-empty.

### ISSUE THREAD

**Issue by eugenea** [grafana/grafana#5588]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
   grafana_3.1.0-1468321182_amd64.deb

- What datasource are you using?
   graphite
- What OS are you running grafana on?
  Debian 7
- What did you do?
  add 2 panel to a row, set span of first panel to 6, save, everything works fine!,
  set spat of a second panel to 6, save, reload dashboard, see that 2-nd panel span reset to 12.

This only happens for 2-nd panel in a row, but never for a first panel.

- What was the expected result?
  Expected result would be to have both panels span set to 6.
- What happened instead?
 Grafana does not want to store (to mysql in my case) the span of a second pane and resets it to 12 on reload.

**Comment by torkelo** [comment]
I am unable to replicate this, no matter how I try the panels stay with the span I have selected. 

http://play.grafana.org/dashboard/db/span6

**Comment by eugenea** [comment]
Ok it seems like this related to upgrade. If i duplicate panel and delete old one then it can remember span correctly.

**Comment by eugenea** [comment]
I dumped panel json, duplicated it and dumped json again, this is the diff i have :
diff old.json new.json 
14c14
<   "id": 6,
---
>   "id": 24,
34,41d33
<   "repeat": "volume",
<   "scopedVars": {
<     "volume": {
<       "text": "df-root",
<       "value": "df-root",
<       "selected": false
<     }
<   },

Of course new duplicated panel can remember span correctly.

**Comment by eugenea** [comment]
Ok during duplication it makes "repeat panel" field to be empty, and thats when i can change and save span, and it works, but then when i set "repeat panel" to some non-empty value and save - the span of the 2-nd panel resets to 12 on reload.

**Comment by eugenea** [comment]
Correction, the problem happens not with 2-nd panel in a row but with any panel that has "Repeat Panel" field non-empty. Removing value from "Repeat pane" fixes the span save problem (but breaks templating of course).

**Comment by eugenea** [comment]
Panel source on which you can reliably repro the problem
[https://gist.github.com/eugenea/2d533f4ed72477297900976898d2f5c7](url)

Set span to 6, save, reload, see that span got reset to 12.

Repeat panel field suppose to be set to volume.

**Comment by torkelo** [comment]
So repeat panel repeats a panel, so you specify the variable for which the panel should repeat, and the `min span`  sets the minimum span for each panel, if you only have one value selected in the template variable the span will be set to 12. Repeated panels will always try to fill up the row (you cannot mix repeated panels and non repeated panels within one row)

http://play.grafana.org/dashboard/db/graphite-panel-repeats

**Comment by eugenea** [comment]
Thanks for clarification, that explains it.
