### ISSUE TITLE
Variables: Adds substitution regex

### ISSUE THREAD

**Issue by jackmeagher** [grafana/grafana#5589]
- **I'm submitting a ...**
- [x] Feature request

Using Grafana v3.1.0, I would like to be able to do a substitution regex in a template, instead of just a match.

For example, if my glob matches the value "abcdef" I would like to use the regex "s/bcd/xyz/" and have the value transformed to "axyzef".

**Comment by jisaitua** [comment]
+1 Very useful for transforming some cryptic/to_technical values (e.g: ["ofh","nofh"]) to values that some uneducated user can understand (e.g: ["Office Hours","Non Office Hours"])

**Comment by jogoussard** [comment]
+1 Very useful for mapping a variable obtained from one data source query (cloudwatch for ex) to query another data source (graphite)

**Comment by hugohaggmark** [comment]
I think this would be a great addition.

**Comment by tigattack** [comment]
I'd also love to see this.
