### ISSUE TITLE
No default time in “Traces to Metrics”

### ISSUE THREAD

**Issue by amitsetty** [grafana/grafana#55898]
**What happened**:
When moving from traces to metrics in grafana metrics open up without a specified time frame. The graph doesn’t render until manually a time frame is given 

**What you expected to happen**:
Expect a default time frame to be given (or configured in the data source) 

**How to reproduce it (as minimally and precisely as possible)**:
Set up traces to metrics in grafana and try moving from traces to metrics 

**Environment**:
- Grafana version: 9.1.X
- Data source type & version: Tempo, Prometheus

**Comment by ifrost** [comment]
In 9.1.x the time range that is used to show metrics is the same as the range covering the span which may be too narrow to show any metrics data. This has been improved by adding a config option to extend the time range of the metrics query in #54710. [The PR with the change](https://github.com/grafana/grafana/pull/55335) is targeting 9.3.0, but it was merged long time ago so I believe it made it to 9.2.x. cc @grafana/observability-traces-and-profiling for more details.

**Comment by joey-grafana** [comment]
[This](https://github.com/grafana/grafana/pull/55335) was more of a mini-feature than a bug fix so it would be better suited in 9.3.0 than backporting :)
