### ISSUE TITLE
Logs: detected-fields JSON parse does not handle large numbers correctly

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#55933]
for example, assume a loki log-line like this: `{"_entry":"log text","large": -137198070982544818}`. if you display this data in the logs-visualization, and then click on the log-line, in the detected-fields section there will be this entry: 
`large: -137198070982544820`

the value will be incorrect.

the problem is that javascrip'ts `JSON.parse` cannot handle large integers well. this issue is similar to https://github.com/grafana/grafana/issues/55856

**Comment by gabor** [comment]
we could probably use the approach described at https://github.com/grafana/grafana/pull/55863#issuecomment-1259889566       : 
using a regular-expression find the "potentially problematic" numbers, and add quotes around them. this turns them into strings.

while it is true that this changes a JSON by turning some numbers into strings, for the use-case described here it does not matter.

**Comment by ivanahuckova** [comment]
I am removing needs investigation label as we know why the issue happens and how to fix it. Now we are just waiting for agreement on what is the future of detected fields.

**Comment by gabor** [comment]
not needed anymore since the rework in https://github.com/grafana/grafana/pull/60448
