### ISSUE TITLE
Can't save silence for Grafana with disabled auth

### ISSUE THREAD

**Issue by kotchaosu** [grafana/grafana#55948]
#### What

When trying to save silence in Grafana with disabled auth (and "anonymous" Mimir tenant only) - the following error pops up:

```
Error: createdBy in body is required
```

![alertmanager_mimir_bug](https://user-images.githubusercontent.com/3284212/192514035-9cda5c81-812e-4e18-8f96-dfa2938e97bd.png)

As `createdBy` cannot be added in the menu - I'd expect there should be a possibility to skip the validation for such setup.

#### Setup

- Grafana 9.0.9
- Mimir 2.1.0

both installed via helm charts

#### To reproduce

1. Disable auth in Grafana.
2. Add Mimir Alertmanager datasource.
3. Configure and save silence.

**Comment by gotjosh** [comment]
I can also see we have a duplicate in https://github.com/grafana/grafana/issues/47155
