### ISSUE TITLE
[Feature request] Dynamically create dashboard & panel from URL

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5594]
Hi,

I would like sending a JSON graph to API to **generate** a temporary graph with POST method.

**More explanation:**
With graphite to generate graph i could set my query directly in url (GET method):
E.g: `http://graphite/render?target=summarize(derivative(app.numUsers),"1min")&title=New_Users_Per_Minute` and the graph is generated.
With Grafana i would like to do same thing but with a JSON graph.

**Example:**
I have a JSON graph: http://pastebin.com/xwZa7C66 
I send this JSON to Grafana API with POST method, something like that: 

```
POST /api/generate HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
/// My JSON graph
}
```

I see the graph in my browser.

This will be useful to use Grafana as "presentation graph as a service". 

Please include this information:

* What Grafana version are you using? 3.1.0-beta1 
* What datasource are you using? Graphite
* What OS are you running grafana on? CentOS

**Comment by angadsingh** [comment]
+1 this could help put a dynamic grafana link in bosun notifications (for example)

**Comment by sreetamdas** [comment]
+1

**Comment by grifx** [comment]
That would be awesome. My Grafana setup would become almost stateless! No need to sync the dashboards. Being able to inject variables is good but definitely not enough.
