### ISSUE TITLE
Elasticsearch: Add types for elastic data source

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#55946]
level: hard

Elasticsearch uses type `any` at most of the places in datasource.ts. This should be fixed and correct types should be added.

**Comment by Toledodev** [comment]
Hey @ivanahuckova, just to confirm if I understand correctly, is it to type all the components "datasource"?
![Captura de Tela (3)](https://user-images.githubusercontent.com/87545086/193072050-d59f3997-a6fc-4c66-8f92-e3008dacb0de.png)

**Comment by matyax** [comment]
To be done after the backend migration.

**Comment by Toledodev** [comment]
I was trying to do it for a while @matyax

**Comment by ivanahuckova** [comment]
Let's wait with this until frontend running of queries is removed.

**Comment by gabor** [comment]
this has been mostly done, closing the issue (feel free to reopen, if you disagree 👍 )
