### ISSUE TITLE
CLI reset-admin-password fails when admin user hasn't ID 1 anymore

### ISSUE THREAD

**Issue by Bacto** [grafana/grafana#55976]
Hi,

If the admin user hasn't ID 1 anymore, it is not possible to change its password using the CLI:
```
grafana-cli --homepath ... --config ... admin reset-admin-password ...
Error: ✗ could not read user from database. Error: user not found
```

How to reproduce:
1. Log as "admin" on WEB UI
2. Create a user "admin2" and give it admin rights
3. Log as "admin2"
4. Delete user "admin"

At this moment, we have one user in database which is "admin2". Its ID in database is 2.
Using the CLI to reset admin password will fail because it  will look at user ID 1.
See https://github.com/grafana/grafana/blob/20f4191e566a15c3b87975fb122b26765cb07a24/pkg/cmd/grafana-cli/commands/reset_password_command.go#L18

I think the code should be modified to update the first user with admin rights found in database.

Best,
Adrien

**Comment by papagian** [comment]
thank you for reporting this! I think that it will be even better if we introduce a new flag that defaults to 1.
