### ISSUE TITLE
Grafana Transform Sort - Start Time column sorts in alphabetical order, rather than sorted by time  

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#55990]
**What happened**:

Grafana Transform Sort - Start Time column sorts in alphabetical order, rather than sorted by time  

In the screenshot below, you'll see the Start Time column sorts alphabetically, rather than by actual time. This means that "less than 5 seconds ago" sorts after "7 minutes" ago. Is this correct/intended ? I managed to reproduce it myself on se-demo. The data source is tempo traces. 

![image](https://user-images.githubusercontent.com/54800912/192991475-5c37b895-f109-492a-aaf7-edff3fb8999e.png)

**What you expected to happen**:

Sort by time 

**How to reproduce it (as minimally and precisely as possible)**:

Transform / Sort traces on their time column.  

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud latest 
- Data source type & version: Tempo (cloud / latest) 
- OS Grafana is installed on: cloud
- User OS & Browser: macos/chrome 
- Grafana plugins: tempo plugin 
- Others: n/a

**Comment by aocenas** [comment]
Seems like BI squad is working on update to Table that would allow us to separate visual rendering and sorting which would allow us to solve this. https://github.com/grafana/grafana/pull/56635

**Comment by codeincarnate** [comment]
Yes, I'm looking into this currently. Hoping to have a decent solution fairly soon.

**Comment by CrypticSignal** [comment]
@aengusrooneygrafana In the meanwhile, we have switched to using the `YYYY-MM-DD HH:MM:SS` format (#56635) for all traces (previously this format was only uses for traces that started over an hour ago), so if you pull the latest code in the main branch, the start time column will be sorted by time.
