### ISSUE TITLE
grafana does not show anything when all is selected and query ends with aliasbynode(1)

### ISSUE THREAD

**Issue by hesamaseh** [grafana/grafana#5599]
These are the error pages

![grafana_error_1](https://cloud.githubusercontent.com/assets/7535609/16897958/d6073bee-4b92-11e6-87a7-aa9d95ad4db6.png)

![grafana_error_2](https://cloud.githubusercontent.com/assets/7535609/16897959/fc2029b2-4b92-11e6-8e0b-edcb317f5c6d.png)

The "All" does not show any thing :

![image](https://cloud.githubusercontent.com/assets/7535609/16897962/131389ca-4b93-11e6-8a8a-af68c1714c80.png)

It works if i choose any other options than the "All"

![image](https://cloud.githubusercontent.com/assets/7535609/16897963/24ebfff6-4b93-11e6-828c-c64920537c3e.png)

This is my variable configuration :

![image](https://cloud.githubusercontent.com/assets/7535609/16897965/31f92930-4b93-11e6-979b-db5e4eb9ab11.png)

However it shows all the graphs when i take the aliasbynode out of query

![image](https://cloud.githubusercontent.com/assets/7535609/16897980/941d27a6-4b93-11e6-9a3e-1c7f887bbbf0.png)

**Comment by torkelo** [comment]
looks like an error in Graphite? Try upgrading Graphite. 

Works when I test it here with latest Graphite, http://play.grafana.org/dashboard/db/issue-5599?panelId=1&fullscreen&edit
