### ISSUE TITLE
Add in-product help for alerting

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#56009]
We want to make docs accessible from within the product, avoiding extra clicks, optimising and creating a great user experience. This would require to find how to update docs to be related to an endpoint, e.g. https://grafana.com/docs/grafana/latest/alerting/notifications/mute-timings/ for `alerting/routes`.

Questions to solve:
1. Which UIs to prioritise?
2. How to connect the docs content to the right UI?
3. Write the content -- could this also include mouseovers to clarify key alerting definitions? Should focus on task type documentation--steps on how to complete my goal.

**Comment by joeblubaugh** [comment]
Based on escalations I've been handling recently:
1. The message template UI is still confusing for many people.
2. The notification policy UI and how policy matching works need some explanation.
3. The way mute timings are defined and referenced is confusing for many people.

**Comment by armandgrillet** [comment]
I agree with @joeblubaugh's observation, @brendamuir can we start with these 3 areas?

**Comment by armandgrillet** [comment]
@brendamuir @gillesdemey What is the status of this? Is it moving to Q1?

**Comment by brendamuir** [comment]
yes

**Comment by armandgrillet** [comment]
Closing this after having talked with Brenda, this will be done with smaller issues refactoring views.
