### ISSUE TITLE
Docs: Update the existing documentation to favor `@grafana/create-plugin` instead of toolkit.

### ISSUE THREAD

**Issue by academo** [grafana/grafana#56001]
The following documentation pages should mention the usage of create-plugin and not toolkit:

* https://grafana.com/tutorials/build-a-data-source-plugin/
* https://grafana.com/tutorials/build-a-panel-plugin/
* https://grafana.com/tutorials/build-a-data-source-backend-plugin/
* https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/
* https://grafana.com/docs/grafana/latest/developers/plugins/
* https://grafana.com/docs/grafana/latest/developers/plugins/migration-guide/
* https://grafana.com/tutorials/build-a-panel-plugin-with-d3/

**Comment by academo** [comment]
Related https://github.com/grafana/create-plugin/issues/42

**Comment by GrafanaWriter** [comment]
The content for the tutorials has been fixed, but the developers plugins documentation is still out of date.
