### ISSUE TITLE
[Bug] datasource API incomplete for elasticsearch missing index pattern

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#5601]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0
- What datasource are you using?
elasticsearch
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Get datasource information from API.
Then try to recreate the source with the API.
- What was the expected result?
The datasource created with API should work.
- What happened instead?
The datasource was not working, the date pattern was not getting set and returned by the API.

Can not get/set datasource pattern with the API.

Set in UI and working:
"[collectd-]YYYY.MM.DD" -> pattern daily (working)
Retrieved by API:
"[collectd-]YYYY.MM.DD" / no pattern variable
After creating the datasource with the API:
"[collectd-]YYYY.MM.DD" -> pattern no (not working)
Changed pattern in the UI:
"[collectd-]YYYY.MM.DD" -> pattern daily (working again)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/16910036/82619dc8-4cd6-11e6-9bf6-5447d1cb6cd1.png)


you need to set the interval property in the jsonData field

**Comment by DEvil0000** [comment]
OK this works. thanks.
A GET on /datasources does not show this information while a get with ID will show it.
I was searching docu but it is not documented on the website.

**Comment by wireless00** [comment]
What if I want NO PATTERN in the interval ?
