### ISSUE TITLE
Toolkit: Remove `plugin:create` command in favor of `@grafana/create-plugin`

### ISSUE THREAD

**Issue by academo** [grafana/grafana#56018]
`@grafana/create-plugin` replaces `plugin:create` but there are many resources out there referring to `plugin:create`.

Instead of removing the command we can put a permanent message linking to the new documentation or suggesting the new command to use.

**Comment by matheusmuniz03** [comment]
Hey @academo, can you tell me if you prefer to completely remove this command or leave something similar to print?
![Captura de tela de 2022-09-30 19-40-44](https://user-images.githubusercontent.com/87545749/193365785-04abe37b-cad0-43e1-a82c-9021fe05ebda.png)

**Comment by academo** [comment]
hi @matheusmuniz03 It seems the change in the image is related to `component:create` but this issue is regarding `plugin:create`.

Also keep in mind `plugin:create`  will only be removed in V10 and we are still working in versions 9.x
