### ISSUE TITLE
Toolkit: Remove `changelog` command (already replaced by a github workflow)

### ISSUE THREAD

**Issue by academo** [grafana/grafana#56028]

**Comment by academo** [comment]
@dsotirakis could you tell us if this command `@grafana/toolkit changelog` is used anywhere in our pipelines?

**Comment by dsotirakis** [comment]
@academo 👋 
As far as I am concerned I'd say we are safe to remove that! Drone doesn't use it and I also think Github Actions don't use it as well. Until we're proven wrong 😂
