### ISSUE TITLE
Toolkit: Deprecate `plugin:github-publish` command in favor of `@grafana/create-plugin`

### ISSUE THREAD

**Issue by academo** [grafana/grafana#56020]
* Research which of granary-labs-maintained plugins are using circle ci. e.g.: https://github.com/grafana/grafana-image-renderer
* Make a decision if we still want to deprecate and remove the `plugin:github-publish` command based on the amount of work
* Migrate the existing plugins to not use the `plugin:github-publish` command.
* Mark `plugin:github-publish` as deprecated.

**Comment by tolzhabayev** [comment]
Not relevant anymore due to https://github.com/grafana/grafana/issues/70042
