### ISSUE TITLE
Datasource type templating vars doesn't save current position with dashboard(or not loaded correctly).

### ISSUE THREAD

**Issue by AlexMaksimkin** [grafana/grafana#5603]
* **I'm submitting a ...**
- [X ] Bug report

Please include this information:
- What Grafana version are you using? - grafana-3.0.0-beta71462173753.x86_64
- What datasource are you using? - cloudwatch/elasticsearch
- What OS are you running grafana on? CentOS
- What did you do?
Created templating variable "test" with var type: datasource, data source option: cloudwatch.
Then clicked on template var dropdown menu - select second cloudwatch datasource, then clicked on "save dashboard" icon. After reloading dashboard, templated var reset to first cloudwatch datasource instead of second. Also checked with elasticsearch - same result.

I see that in dashboard.json current section of templated var saved correctly, i.e:

`{
        "current": {
          "text": "second-CW",
          "value": "second-CW"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "label": "test",
        "multi": false,
        "name": "test",
        "options": [
          {
            "text": "second-CW",
            "value": "second-CW",
            "selected": true
          },
          {
            "text": "first-CW",
            "value": "first-CW",
            "selected": false
          }
        ],
        "query": "cloudwatch",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      }`

but after page reload - it resets to:
`{
        "current": {
          "text": "first-CW",
          "value": "first-CW"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "label": "test",
        "multi": false,
        "name": "test",
        "options": [
          {
            "text": "first-CW",
            "value": "first-CW",
            "selected": true
          },
          {
            "text": "second-CW",
            "value": "second-CW",
            "selected": false
          }
        ],
        "query": "cloudwatch",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      }`

- What was the expected result?
Saving/loading correct current var value.

**Comment by torkelo** [comment]
This bug was fixed in 3.0.1, 
https://github.com/grafana/grafana/issues/4934
