### ISSUE TITLE
Prometheus Stats dashboard: Mixed content warning

### ISSUE THREAD

**Issue by knweiss** [grafana/grafana#5604]
* **I'm submitting a bug report**

Please include this information:
- What Grafana version are you using? **3.1**
- What datasource are you using? **Prometheus**
- What OS are you running grafana on? **Linux (CentOS 7.2)**
- What did you do? Install the **Prometheus Stats** dashboard
- What was the expected result?

No https mixed content warning.

- What happened instead?

The **Prometheus Stats** dashboard causes a **https mixed content browser warning** if Grafana is accessed by https. The dashboard references the external prometheus logo with the http protocol (URI: http://prometheus.io/assets/prometheus_logo_grey.svg).

Suggested fix: **Embed the small SVG** instead of referencing the logo by https. I'm using Grafana from a browser that isn't connected to the Internet
i.e. it couldn't access the logo anyway.

**Comment by knweiss** [comment]
I'm curious: Is there a reason why you didn't embed the SVG instead? This would work in browsers without Internet connection, too.

**Comment by torkelo** [comment]
Because I did not have to, the svg is included in Grafana along with the prometheus plugin
