### ISSUE TITLE
Heatmap reverse color option does nothing

### ISSUE THREAD

**Issue by asantoni** [grafana/grafana#56058]
![Animation](https://user-images.githubusercontent.com/569913/193133316-0a63fcdf-ccc0-4ecf-904b-8c9c75d54a5e.gif)

**What happened**:

In the Grafana 9.2.0 beta, the Heatmap widget has a bug. In the "Colors" tab, the "Reverse" option no longer works. When you click the toggle button for it, nothing happens. Also, in any existing Heatmap panels I had where colours were reversed in previous versions of Grafana, are now rendering with the colours the wrong way (not reversed). So it's not the toggle button that's broken, it's the rendering.

**What you expected to happen**:

The colours should be reversed. 

**How to reproduce it (as minimally and precisely as possible)**:

Make a new dashboard. Add a Heatmap widget, and hook it up to any datasource (eg. InfluxDB). Select a simple measurement like CPU usage. Edit the Heatmap and in the Colors tab, click the Reverse toggle button. The colour map does not get reversed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.0 beta
- Data source type & version: InfluxDB 1.x
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome 105, Windows
- Grafana plugins: None
- Others: None

**Comment by dprokop** [comment]
@leeoniya can't see any changes to https://github.com/grafana/grafana/pull/54365 recently, anything comes to mind?
