### ISSUE TITLE
Notification Policies created after migrating Legacy Alerts not being deleted/removed if those alerts are deleted

### ISSUE THREAD

**Issue by milinpatel13298** [grafana/grafana#56053]
**What happened**:
Notification Policies created after migrating Legacy Alerts not being deleted/removed if those alerts are deleted.

**What you expected to happen**:
Policies expected to be removed since the only label would be the rule_uid and that policy is not useful anymore if that rule_uid does not exist - unless this was intentional, which I do not understand the point of.
Perhaps, some sort of check that removes policies that only have the rule_uid label and a uid that does not exist?

**How to reproduce it (as minimally and precisely as possible)**:
Delete an alert that was migrated to the Grafana9 alert rules from the legacy alerts

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by grobinson-grafana** [comment]
Hi! Thanks for opening an issue. Grafana won't remove notification policies that are no longer in use, so I think this is expected. Please let me know if that does not match your expectations!

**Comment by milinpatel13298** [comment]
I believe that answers my question then. Cheers!
