### ISSUE TITLE
Data link not retrieving the right values on time series panel

### ISSUE THREAD

**Issue by jdmedeiros** [grafana/grafana#56063]
**What happened**:
I have a dashboard with three variables [_meter, readtime and kwh_total_], one time series panel and one data panel. Both panels use the exact same query. In both panels, in the overrides section, I added field _kwh_total_ and the following link:
`http://x.x.x.x:3000/d/xNTeB744z/data-manipulation?var-meter=${__data.fields.meter}&var-readtime=${__data.fields.readtime}&var-kwh_total=${__data.fields.kwh_total}
`
In both panels, the link points to the same dashboard. The data link in the table is behaving properly. As I move the mouse from one line to the other, the link variables update according to the line that I am on. The time series panel behaves in an inconsistent manner; as I move the mouse to the data point and hover on top of the link, the link variables do update, but most of the time to the wrong values. As you watch the video look at the status line. You will see clearly what I mean.

**What you expected to happen**:
I expecteds the data link in the time series panel to behave in the same manner as in the table panel.

**How to reproduce it (as minimally and precisely as possible)**:
Please watch the video.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: **Gafana v9.1.6 (92461d8d1e)**
- Data source type & version: 
      **Amazon Athena - version: 2.1.0**
- OS Grafana is installed on: 
**Linux ip-10-0-1-42.ec2.internal 5.10.135-122.509.amzn2.x86_64 #1 SMP Thu Aug 11 22:41:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux**
- User OS & Browser: MacOS / Chrome
- Grafana plugins: Attached file: plugins.json
- Others: None

https://user-images.githubusercontent.com/3796667/193154272-a2497d2b-e486-49b4-afaf-fd8bc9d2d248.mp4

**Comment by jdmedeiros** [comment]
Sure, here they are. 

[data.csv](https://github.com/grafana/grafana/files/9683166/data.csv)
[TimeseriesDataFrame.json.zip](https://github.com/grafana/grafana/files/9683182/TimeseriesDataFrame.json.zip)
[TableDataFrame.json.zip](https://github.com/grafana/grafana/files/9683183/TableDataFrame.json.zip)

**Comment by jdmedeiros** [comment]
> Looks like this is grabbing records from the previous value so might be an indexing issue. Looking into it further.

Only in some cases!

**Comment by mdvictor** [comment]
Work is in progress to provide a fix for this!

**Comment by mdvictor** [comment]
Fix ready for v9.2.2
