### ISSUE TITLE
Grafana/OpenTSDB: Unable To Use Dashboard Variables in Filter Keys 

### ISSUE THREAD

**Issue by pchang388** [grafana/grafana#56060]
**What happened**:
According to: https://github.com/grafana/grafana/issues/43258, we should have the ability to use dashboard variables in the filter keys section of queries for OpenTSDB plugin. However, from my testing, this is not working:

![image](https://user-images.githubusercontent.com/51681873/193140301-04544ba2-ab40-44b7-8e7b-8986fafa9b6d.png)

It's not clear from the referenced issue, if this is supposed to actually work, the referenced snippet in the comments of that issue has actually been there in versions < 8.3.3 indicating that the feature never actually existed.

Has anyone been able to get this to work? Would be very helpful for us to not have to create so many panels and use a variable for our normalized data (i.e. a lot of our data has the same suffixes, "${agent_name}_**_status_**").

**What you expected to happen**:
Variable replacement in filter keys of queries.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with any OpenTSDB datasource and try to use a variable in the key of a filter. Variable will not be replaced when calling the datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.6
- Data source type & version: OpenTSBD
- OS Grafana is installed on: Offical Docker image of Grafana (grafana/grafana:9.1.6)
- User OS & Browser: Chrome + Windows
- Grafana plugins: OpenTSBD
- Others:

**Comment by bohandley** [comment]
According to [this](https://github.com/grafana/grafana/issues/43258) there was no fix implemented to allow for using dashboard variables in filter keys, just a suggestion of where to add the code. We are happy to take this on as a feature request.

**Comment by pchang388** [comment]
> According to [this](https://github.com/grafana/grafana/issues/43258) there was no fix implemented to allow for using dashboard variables in filter keys, just a suggestion of where to add the code. We are happy to take this on as a feature request.

Ah sorry for the confusion, I misread the comment and thought it was going to be implemented. Thanks for that! Please let me know if there is anything I can provide (background or use case, etc.) to get this implemented

**Comment by bohandley** [comment]
Hi @pchang388, I have a PR for this, to allow variables to be used in filter keys. How does this look?

**Comment by pchang388** [comment]
> Hi @pchang388, I have a PR for this, to allow variables to be used in filter keys. How does this look?

Hey @bohandley, that looks good to me at least but I had a question. Does it also work when you do something like:

`${agent_name}_status` or `agent_${agent_name}` basically using it in a prefix/suffix of a bigger string?

**Comment by bohandley** [comment]
Good question! It does work for interpolating the variable into a filter key with the syntax you mentioned.

![Image](https://user-images.githubusercontent.com/25674746/197053818-5d469010-210a-4669-a95d-407643a6d14f.png)

**Comment by pchang388** [comment]
@bohandley

Thanks for working on this and getting it done. From what I've read in your comments in other issues, this should be included in the v9.3 and won't be available till then since it depends on a related feature in v9.3?

**Comment by pchang388** [comment]
Just confirming, finally had time to get back to this. It is working as expected in v9.3.6
