### ISSUE TITLE
Respect "For" Duration for NoData alerts

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#56067]
### Discussed in https://github.com/grafana/grafana/discussions/48849

<div type='discussions-op-text'>

<sup>Originally posted by **joeblubaugh** May  9, 2022</sup>
Grafana 8 alerting lets you define states for query execution errors and no data conditions. You can have them alert, have them be "OK" or have them notify you with the states "Error" and "No Data".

In the NoData condition mapping code there's a switch:
```go
func (a *State) resultNoData(alertRule *ngModels.AlertRule, result eval.Result) {
	a.Error = result.Error

	if a.StartsAt.IsZero() {
		a.StartsAt = result.EvaluatedAt
	}
	a.setEndsAt(alertRule, result)

	switch alertRule.NoDataState {
	case ngModels.Alerting:
		a.State = eval.Alerting
	case ngModels.NoData:
		a.State = eval.NoData
	case ngModels.OK:
		a.State = eval.Normal
	}
}
```
This switch will immediately set the value of an alert to Alerting on the first NoData evaluation. I guessed that it would wait for the "For" period in the same way that Error alerting does. Should it do that?</div>

Answered by @yuri-tceretian :
<div type='discussions-op-text'>

The same way we https://github.com/grafana/grafana/pull/47052 for option Alerting for Error state, this option should consider the rule's for parameter.

[grafana/pkg/services/ngalert/state/state.go](https://github.com/grafana/grafana/blob/4b417c8f3e7d77b6d790d77432bb8e60f634fdef/pkg/services/ngalert/state/state.go#L128-L138)

Lines 128 to 138 in [4b417c8](https://github.com/grafana/grafana/commit/4b417c8f3e7d77b6d790d77432bb8e60f634fdef)
 default: 
```go
 	// For is observed when Alerting is chosen for the alert state 
 	// if execution error or timeout. 
 	if execErrState == eval.Alerting && alertRule.For > 0 { 
 		a.State = eval.Pending 
 	} else { 
 		a.State = execErrState 
 	} 
 	a.StartsAt = result.EvaluatedAt 
 	a.setEndsAt(alertRule, result) 
 }
```
</div>

**Comment by yuri-tceretian** [comment]
The problem here is that NoData __mapped to Alerting__ starts alerting immediately whereas it should use for to be either Pending or Alerting. The state Error mapped to Alerting behaves this way, so I think we should fix it.

**Comment by alexweav** [comment]
If we are strictly talking about changing the behavior when NoData is mapped to Alerting and not when kept as NoData, I'm a little more in favor of this.

As long as we don't feel this would unexpectedly hide a broken datasource. But, if the user cares about that, they can always keep the mapping to NoData, right? It'll ping them immediately regardless.
