### ISSUE TITLE
[Bug]: Panel rendering, phantomjs render code not detecting the moment panel rendered, always wait until timeout to capture image

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5606]
Backend panel rendering is not as fast as it should, it is waiting to long and not detecting the panel has actually completed rendering.

**Comment by rotanid** [comment]
thanks for fixing this!

**Comment by amuraru** [comment]
hi @torkelo - we upgraded to 3.1.1 and while the indiv panel rendering is faster the whole dashboard rendering is broken:

https://grafana.mysite.com/render/dashboard/db/my-dashboard renders empty panels:
(it used to work in the previous version, a bit slower fwiw but we got all panels rendered).

![image](https://cloud.githubusercontent.com/assets/728853/18490467/e2f559f2-7a0a-11e6-85dc-bb71832fe417.png)

**Comment by torkelo** [comment]
Whole dashboard rendering has never been supported

**Comment by amuraru** [comment]
I am confused, what do you mean by not being supported. The render endpoint was there for a while.

**Comment by torkelo** [comment]
Yepp, but only built for panel rendering
