### ISSUE TITLE
State Timeline Strings (play.grafana): CSV Metric Values: with mid data NULLs cause Cross Series Contamination

### ISSUE THREAD

**Issue by olirockone** [grafana/grafana#56080]
The State Timeline Strings example uses CSV Metric Values strings for the data source. However If you have empty strings or NULLs in the middle of a series then the graphic does not neccessarily scale the preceding non NULL value correctly.

The are 3 series (A,B,C) in the play.grafana example
https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1&editPanel=63

Adding extra commas at the end of any of the series correctly rescales that individual series, however if there are NULLs (or ,,) in the middle of the other series then they will also be affected with the value prior to the NULL being squished by differing amounts.

So this appear to be a graphical error rather than a data error.

NORMAL:
![Normal](https://user-images.githubusercontent.com/87179076/193250340-92b2e90f-1607-4dbf-a3c4-7ca49b31133c.GIF)

NORMAL:
"time","Level A"
2022-09-30 05:17:55,LOW
2022-09-30 05:57:55,HIGH
2022-09-30 06:37:55,NORMAL
2022-09-30 07:17:55,NORMAL
2022-09-30 07:57:55,NORMAL
2022-09-30 08:37:55,LOW
2022-09-30 09:17:55,LOW
2022-09-30 09:57:55,NORMAL
2022-09-30 10:37:55,HIGH
2022-09-30 11:17:55,CRITICAL

"time","Level B"
2022-09-30 05:17:55,NORMAL
2022-09-30 05:57:55,LOW
2022-09-30 06:37:55,LOW
2022-09-30 07:17:55,CRITICAL
2022-09-30 07:57:55,CRITICAL
2022-09-30 08:37:55,LOW
2022-09-30 09:17:55,LOW
2022-09-30 09:57:55,NORMAL
2022-09-30 10:37:55,HIGH
2022-09-30 11:17:55,CRITICAL

"time","Level C"
2022-09-30 05:17:55,NORMAL
2022-09-30 05:57:55,NORMAL
2022-09-30 06:37:55,NORMAL
2022-09-30 07:17:55,NORMAL
2022-09-30 07:57:55,CRITICAL
2022-09-30 08:37:55,LOW
2022-09-30 09:17:55,NORMAL
2022-09-30 09:57:55,NORMAL
2022-09-30 10:37:55,NORMAL
2022-09-30 11:17:55,LOW

SQUISHED:
Delete a field value from series B (I did the first CRITICAL)
The graph appears as expected
But then add commas to the end of series C, the WIDTH of the field prior to the NULL in Series B gets rescaled (In this Case the LOW)
![BSquished](https://user-images.githubusercontent.com/87179076/193251263-6ceca7ab-662d-4779-a980-b9b0fa1b915b.GIF)

"time","Level A"
2022-09-30 05:26:40,LOW
2022-09-30 06:06:40,HIGH
2022-09-30 06:46:40,NORMAL
2022-09-30 07:26:40,NORMAL
2022-09-30 08:06:40,NORMAL
2022-09-30 08:46:40,LOW
2022-09-30 09:26:40,LOW
2022-09-30 10:06:40,NORMAL
2022-09-30 10:46:40,HIGH
2022-09-30 11:26:40,CRITICAL

"time","Level B"
2022-09-30 05:26:40,NORMAL
2022-09-30 06:06:40,LOW
2022-09-30 06:46:40,LOW
2022-09-30 07:26:40,
2022-09-30 08:06:40,CRITICAL
2022-09-30 08:46:40,LOW
2022-09-30 09:26:40,LOW
2022-09-30 10:06:40,NORMAL
2022-09-30 10:46:40,HIGH
2022-09-30 11:26:40,CRITICAL

"time","Level C"
2022-09-30 05:26:40,NORMAL
2022-09-30 05:54:22,NORMAL
2022-09-30 06:22:03,NORMAL
2022-09-30 06:49:45,NORMAL
2022-09-30 07:17:26,CRITICAL
2022-09-30 07:45:08,LOW
2022-09-30 08:12:49,NORMAL
2022-09-30 08:40:31,NORMAL
2022-09-30 09:08:12,NORMAL
2022-09-30 09:35:54,LOW
2022-09-30 10:03:35,
2022-09-30 10:31:17,
2022-09-30 10:58:58,
2022-09-30 11:26:40,

PUTBACK
![PutBack](https://user-images.githubusercontent.com/87179076/193251718-80b33fd8-6869-404f-abd4-5735dd0d28f4.GIF)
If you remove the NULL in Series B by putting something back in it then the alignment appears correctly

**Comment by olirockone** [comment]
My guess by the way is that when the next value is a null that the box will only be drawn as far as the next time point across any series:

So instead of Series B drawing
2022-09-30 06:06:40,LOW
2022-09-30 06:46:40,LOW
2022-09-30 07:26:40, (Next in Series B)

It actually draws series B as
2022-09-30 06:06:40,LOW
2022-09-30 06:46:40,LOW
2022-09-30 06:49:45,  (Which came from series C)

**Comment by olirockone** [comment]
I also noticed that the last string:
2022-09-30 11:26:40,CRITICAL
Doesn't get displayed unless it has a comma after it
LOW,HIGH,NORMAL,NORMAL,NORMAL,LOW,LOW,NORMAL,HIGH,CRITICAL
needs to be
LOW,HIGH,NORMAL,NORMAL,NORMAL,LOW,LOW,NORMAL,HIGH,CRITICAL,
to see the critical

**Comment by codeincarnate** [comment]
@leon you have any ideas here? Don't think this is from null value changes but maybe related?

**Comment by olirockone** [comment]
Interestingly your graphs do show the last Critical states which I assume is due to the connect nulls setting. But they were not visible on the play grafana example. I had to add a comma to the end of the default data to get that to show.

I agree that the misaligned data is crucial to the bug. But that is highly likely when data has come from multiple sources. Both the missing last Criticals and the way the mid series states followed by nulls are displayed maybe reveals a little about the graphics code. The logic which attempts to merge the consecutive states together is failing where ever there is no next state or it is null. It is terminating the rectangle at the next timestamp across all series. So the null in series b terminates at the timestamp from all series, much like a tab might align to the next tab stop in an editor. Equally the missing last State starts and terminates at the same time (because there are no subsequent timestamps) and therefore has 0 width. That last state is a problem as you don't really know how wide it should be as there is no guarantee that it is regular spaced time series data being displayed.  I would suggest a min width potentially based on the state string unless that causes an overlap with the next non null state.

Note that the same data visualised as a Status History panel is drawn correctly. Where obviously there is no attempt to merge consecutive states into one rectangle.

Regards Robert

Get BlueMail for Android<https://bluemail.me>
On 4 Oct 2022, at 20:17, Leon Sorokin ***@***.******@***.***>> wrote:

@olirockone<https://github.com/olirockone> your examples threw me for a bit, because you're showing two different datasets.

in your first dataset all the timestamps are aligned, but in your second dataset the timestamps of C differ from those in A and B.

i've put together both datasets into a dashboard to discuss further. the left column is your first (aligned) dataset and the right column is the second (unaligned C) dataset. i have turned off "Merge equal consecutive values" so it's easier to understad what's going on.

state-timeline-alignment.json

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 450,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:17:55Z,LOW\n2022-09-30T05:57:55Z,HIGH\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,NORMAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "\ntime,Level B\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,LOW\n2022-09-30T06:37:55Z,LOW\n2022-09-30T07:17:55Z,CRITICAL\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,NORMAL\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,NORMAL\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,NORMAL\n2022-09-30T11:17:55Z,LOW",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 6,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:26:40Z,LOW\n2022-09-30T06:06:40Z,HIGH\n2022-09-30T06:46:40Z,NORMAL\n2022-09-30T07:26:40Z,NORMAL\n2022-09-30T08:06:40Z,NORMAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level B\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T06:06:40Z,LOW\n2022-09-30T06:46:40Z,LOW\n2022-09-30T07:26:40Z,CRITICAL\n2022-09-30T08:06:40Z,CRITICAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T05:54:22Z,NORMAL\n2022-09-30T06:22:03Z,NORMAL\n2022-09-30T06:49:45Z,NORMAL\n2022-09-30T07:17:26Z,CRITICAL\n2022-09-30T07:45:08Z,LOW\n2022-09-30T08:12:49Z,NORMAL\n2022-09-30T08:40:31Z,NORMAL\n2022-09-30T09:08:12Z,NORMAL\n2022-09-30T09:35:54Z,LOW",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 10
      },
      "id": 3,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:17:55Z,LOW\n2022-09-30T05:57:55Z,HIGH\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,NORMAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "\ntime,Level B\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,LOW\n2022-09-30T06:37:55Z,LOW\n2022-09-30T07:17:55Z,\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,NORMAL\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,NORMAL\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,NORMAL\n2022-09-30T11:17:55Z,LOW",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 10
      },
      "id": 5,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:26:40Z,LOW\n2022-09-30T06:06:40Z,HIGH\n2022-09-30T06:46:40Z,NORMAL\n2022-09-30T07:26:40Z,NORMAL\n2022-09-30T08:06:40Z,NORMAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level B\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T06:06:40Z,LOW\n2022-09-30T06:46:40Z,LOW\n2022-09-30T07:26:40Z,\n2022-09-30T08:06:40Z,CRITICAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T05:54:22Z,NORMAL\n2022-09-30T06:22:03Z,NORMAL\n2022-09-30T06:49:45Z,NORMAL\n2022-09-30T07:17:26Z,CRITICAL\n2022-09-30T07:45:08Z,LOW\n2022-09-30T08:12:49Z,NORMAL\n2022-09-30T08:40:31Z,NORMAL\n2022-09-30T09:08:12Z,NORMAL\n2022-09-30T09:35:54Z,LOW",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 12,
        "x": 0,
        "y": 19
      },
      "id": 4,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:17:55Z,LOW\n2022-09-30T05:57:55Z,HIGH\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,NORMAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "\ntime,Level B\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,LOW\n2022-09-30T06:37:55Z,LOW\n2022-09-30T07:17:55Z,\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,LOW\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,HIGH\n2022-09-30T11:17:55Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:17:55Z,NORMAL\n2022-09-30T05:57:55Z,NORMAL\n2022-09-30T06:37:55Z,NORMAL\n2022-09-30T07:17:55Z,NORMAL\n2022-09-30T07:57:55Z,CRITICAL\n2022-09-30T08:37:55Z,LOW\n2022-09-30T09:17:55Z,NORMAL\n2022-09-30T09:57:55Z,NORMAL\n2022-09-30T10:37:55Z,NORMAL\n2022-09-30T11:17:55Z,LOW\n2022-09-30T12:03:35Z,\n2022-09-30T12:31:17Z,\n2022-09-30T12:58:58Z,\n2022-09-30T13:26:40Z,",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Level C trailing nulls",
      "type": "state-timeline"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "CRITICAL": {
                  "color": "red",
                  "index": 3
                },
                "HIGH": {
                  "color": "orange",
                  "index": 2
                },
                "LOW": {
                  "color": "blue",
                  "index": 0
                },
                "NORMAL": {
                  "color": "green",
                  "index": 1
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 12,
        "x": 12,
        "y": 19
      },
      "id": 7,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "csvContent": "time,Level A\n2022-09-30T05:26:40Z,LOW\n2022-09-30T06:06:40Z,HIGH\n2022-09-30T06:46:40Z,NORMAL\n2022-09-30T07:26:40Z,NORMAL\n2022-09-30T08:06:40Z,NORMAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level B\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T06:06:40Z,LOW\n2022-09-30T06:46:40Z,LOW\n2022-09-30T07:26:40Z,\n2022-09-30T08:06:40Z,CRITICAL\n2022-09-30T08:46:40Z,LOW\n2022-09-30T09:26:40Z,LOW\n2022-09-30T10:06:40Z,NORMAL\n2022-09-30T10:46:40Z,HIGH\n2022-09-30T11:26:40Z,CRITICAL",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "time,Level C\n2022-09-30T05:26:40Z,NORMAL\n2022-09-30T05:54:22Z,NORMAL\n2022-09-30T06:22:03Z,NORMAL\n2022-09-30T06:49:45Z,NORMAL\n2022-09-30T07:17:26Z,CRITICAL\n2022-09-30T07:45:08Z,LOW\n2022-09-30T08:12:49Z,NORMAL\n2022-09-30T08:40:31Z,NORMAL\n2022-09-30T09:08:12Z,NORMAL\n2022-09-30T09:35:54Z,LOW\n2022-09-30T10:03:35Z,\n2022-09-30T10:31:17Z,\n2022-09-30T10:58:58Z,\n2022-09-30T11:26:40Z,",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "C",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    }
  ],
  "refresh": false,
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2022-09-30T05:16:33.000Z",
    "to": "2022-09-30T13:42:52.000Z"
  },
  "timepicker": {},
  "timezone": "utc",
  "title": "state-timeline-alignment",
  "uid": "vwCI9B4Vk",
  "version": 9,
  "weekStart": ""
}

[image]<https://user-images.githubusercontent.com/43234/193904006-f4af602c-733d-434a-862a-bf4adf03bc57.png>

you can see that the first dataset works fine. but the second one appears to have the bug you're describing.

if you hover carefully, we can see there's an extra "Low" slice hanging out in the time slice that's the overlap between the state edges in Level A and Level B. this does look like a bug.

[image]<https://user-images.githubusercontent.com/43234/193904808-988c784c-a8c5-4c6f-8ad0-829a9f5973b7.png>

however, we do treat null values as explicit state terminations by default, so even after this gets fixed, it will not extend that LOW state forward to the CRITICAL state automatically. to accomplish this you can do one of two things:

  *   Omit null values from your data
  *   Set "Connect null values" to "Always"

https://user-images.githubusercontent.com/43234/193906255-082ab13a-9910-4d30-8b7e-08d4be8a9795.mp4

**Comment by leeoniya** [comment]
> Interestingly your graphs do show the last Critical states which I assume is due to the connect nulls setting. But they were not visible on the play grafana example. I had to add a comma to the end of the default data to get that to show.

my example shows them because i zoomed out to allow them to be visible into the future (where we have no data). the last critical states _begin_ at the end of the high states and are the last datapoints we have. e.g. if you request a time range of 12am - 4am in the picker, grafana will not show you a time range some arbitrary amount beyond 4am, so any states that begin exactly at 4am but have no explicit end will not be visible without explicit zoom out.
