### ISSUE TITLE
AWS-SDK-GO: Upgrade to latest version

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#56099]
Security scanning tools have identified a few vulnerabilities in the version of the aws-sdk-go that we currently use. We should upgrade to the latest version and see if that solves the problem. See https://raintank-corp.slack.com/archives/CMSUYD6H3/p1664544133692429. Once tested and merged, we can report to @jongyllen.

**Comment by fridgepoet** [comment]
Version that we currently use: v1.44.9
Latest version as of today: v1.44.109

The vulnerability warnings are still present on that latest version.
