### ISSUE TITLE
grafana 3.1.0 template  bug when use all for query ,Failed to parse query 

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5609]
i sure its an old bug, 2.x version have the probelm,this is part of json eeror
{
    "root_cause": [
        {
            "type": "query_parsing_exception",
            "reason": "Failed to parse query [giftType:{Money,Vouchers}]",
            "index": "gift-send-log",
            "line": 1,
            "col": 526
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "gift-send-log",
            "node": "ycKB5pFRQTq29qbv8Kq3EA",
            "reason": {
                "type": "query_parsing_exception",
                "reason": "Failed to parse query [giftType:{Money,Vouchers}]",
                "index": "gift-send-log",
                "line": 1,
                "col": 526,
                "caused_by": {
                    "type": "parse_exception",
                    "reason": "Cannot parse 'giftType:{Money,Vouchers}': Encountered \" \"}\" \"} \"\" at line 1, column 24.\nWas expecting one of:\n    \"TO\" ...\n     ...\n     ...\n    ",
                    "caused_by": {
                        "type": "parse_exception",
                        "reason": "Encountered \" \"}\" \"} \"\" at line 1, column 24.\nWas expecting one of:\n    \"TO\" ...\n     ...\n     ...\n    "
                    }
                }
            }
        }

**Comment by torkelo** [comment]
Are you saying 2.x and 3.1 have this issue? 

All is working fine with Elasticsearch here, http://play.grafana.org/dashboard/db/elasticsearch-templated

**Comment by tonyC2016** [comment]
@torkelo  yes , one option all is right,but when both two options are all dont work well

**Comment by torkelo** [comment]
@tonyC2016 and what version are you running? Try going into the template variable edit view and hit the Update button, the format of variable values changed in 3.x and requires a manual update to get a new "All" value.

**Comment by tonyC2016** [comment]
@torkelo 
my template settting is 
$planName	{"find":"terms","field":"planName"}			
$giftType	{"find":"terms","field":"giftType"}			
$tradeType	{"find":"terms","field":"tradeType"}
when i add filter with planName:$planName, its dont work,at grafana 2.6.0 its work well

**Comment by torkelo** [comment]
did you go into the planName template variable and hit the update button?

**Comment by tonyC2016** [comment]
@torkelo  i create  a new one
