### ISSUE TITLE
feature: Grafana internal stats for other datasources

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#5610]
The new internal stats feature is great, but it seems limited to graphite backends.
Is there a way to change this, or maybe an API to query it (e.g. with collectd)?

**Comment by torkelo** [comment]
there is an API and a plugin model so we can add more publishers later
http://play.grafana.org/api/metrics

Any specific TSDB you would want added?

**Comment by faxm0dem** [comment]
I'm currently using ES

**Comment by mjtrangoni** [comment]
Prometheus too! A configuration option in grafana.ini, under "Internal Grafana Metrics", would be a "nice to have".
