### ISSUE TITLE
[Feat Req] Auto refresh per User/Datasource/Dashboard configuration

### ISSUE THREAD

**Issue by DaveTaboola** [grafana/grafana#5611]
- **I'm submitting a ...**
- [X] Feature request

Please include this information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? Elasticsearch and Graphite
- What OS are you running grafana on? Centos 6.7
- What did you do? 
  As the usage of Grafana is increasing in our organization we're reaching the point that too many queries are committed against our datasources, we've found that the main problem is created by end users that defined auto refresh on dashboards without too much logic (for example 5 seconds interval as our data is aggregated per minute, therefore for 55 seconds they won't see anything new either way) 
- What was the expected result?
- What happened instead?
  our datasources suffered from OOM issue

We'd like the following capabilities: 
1. users that are allowed to preform auto refresh to data 
2. define by ourselves the interval values, maybe with option for refresh interval per datasource/user/dashboard.
3. define limitation of queries per data source (per 1 minutes, per 10 minutes and so on), once the quota reached display warning

**Comment by yogeswaran** [comment]
👍

**Comment by iksaif** [comment]
https://github.com/grafana/grafana/pull/6920 may help

**Comment by torkelo** [comment]
closing this as it's very similar to https://github.com/grafana/grafana/issues/3356
