### ISSUE TITLE
Show context should open centered on the lines closest to the line you're showing context for

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#56122]
Actually looking closer maybe this is a regression? This appears that it should have been fixed here:
https://github.com/grafana/grafana/issues/50268

-------

When you open the show context modal, Grafana fetches the next 10 lines that come after my selected line. 

The modal that pops up aligns itself to show the lines that are furthest away (furthest in the future) from my selected line. 

This is confusing for me as a user, since my workflow is to start on the line I'm interested in (the one I asked to show context for) and then scroll gradually further back in time, or further forward in time. 

To better fit this workflow, I would expect the modal to pop up centered on the lines that are nearest to the one I'm looking at the context for. So I should see the lines that are immediately in the future and immediately in the past and then be able to gradually scroll away from those. 

Here's what it looks like today. If you look at the red arrow, you'll see that there's a bunch of lines that are closer in time to the line I'm looking at the context for that are being truncated. The view is set with the line pointed to by the light blue arrow at the top of the screen
<img width="965" alt="Screen Shot 2022-09-30 at 12 42 29 PM" src="https://user-images.githubusercontent.com/9610816/193327687-ce67926d-50ae-4072-ae08-08d6cc146c86.png">

Here's what I'd expect -- that the view pops up with the scroll set so I see the line that's closest to the line that I'm looking at the context for. See the red curly brace. 
<img width="918" alt="Screen Shot 2022-09-30 at 12 43 32 PM" src="https://user-images.githubusercontent.com/9610816/193327953-2731868d-34a9-40be-b1c8-4535aad447c7.png">

**Comment by svennergr** [comment]
Thanks @09jvilla. Just to clarify, how does this differ from https://github.com/grafana/grafana/issues/51150?

**Comment by 09jvilla** [comment]
video with more description:
https://www.loom.com/share/5b24008c01814958a45f5014a11fe6e6

**Comment by 09jvilla** [comment]
Thanks @svennergr !!! =)
