### ISSUE TITLE
Unify Grafana Cards

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#56121]

**Comment by natydej** [comment]
Design new cards.
Here are the [explorations](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Grafana-design-system---Dark-theme?node-id=8444%3A13482) and the ones we have on the Storybook are [here](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/branch/V90aexluk8oORH0Tdsp600/Grafana-design-system---Dark-theme?node-id=6757%3A16222&t=PF7VDst3XS2a46tv-0).

**Comment by Aires-Grafana** [comment]
Closing due to duplicated issue with Card epic.
