### ISSUE TITLE
Explore: log volume histogram y-axis is not anchored to 0

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#56159]
**What happened**:

Because Y axis is not anchored 0, log volume histogram display a misleading representation of log level ratio. 

In the following capture, we can observe that warnings seems to dominate while they represent less than 5% of the volume. 
 
![image](https://user-images.githubusercontent.com/1764725/193537650-b1a10dcd-bd04-463f-9554-c59b0c120c67.png)

**What you expected to happen**:

Y axis min should always be set to 0. 

**How to reproduce it (as minimally and precisely as possible)**:

Use Logs in Explore.

**Anything else we need to know?**:

No.

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Loki

**Comment by gabor** [comment]
i can reproduce it. normally this does not happen, but if you narrow the time-range down with your mouse to a point where there is only a single "bar" remaining, it will become not-anchored-to-zero.
