### ISSUE TITLE
SQL: Postgres Dialect generates 32-bit serial columns when using 64-bit integers with `autoincr`

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#56151]
**What happened**:
When testing #55350, we found instances where random keys would overflow the postgres test database's ID column. This is because the Postgres dialect in the sqlstore migrator returns a SERIAL for int64 columns with autoincr when it should return a BIGSERIAL.

**How to reproduce it (as minimally and precisely as possible)**:
On the joe/sqlstore-column-test, run the [test in pkg/services/sqlstore/migrator](https://github.com/grafana/grafana/blob/joe/sqlstore-column-test/pkg/services/sqlstore/migrator/postgres_dialect_test.go)

**Anything else we need to know?**:
There are a few ways to address this:

If we change all existing types to use int32s instead of int64s, we will be backwards compatible with existing installations *of Postgres* but may not be compatible with installations of MySQL that have already used IDs higher than 2^31, because the bigint columns in MySQL will overflow int32 id fields on structs.

If we only change the column translation code to start returning BIGSERIAL, then new installs will have big integer columns for IDs, while old installs keep their existing 32-bit columns. At some point those older installations may start to fail when they reach IDs higher than 2^31.

To fix it while remaining backward compatible, we could run a migration at startup, on postgres only, to change the type of any affected ID columns. This could take a *long* time on large installations because it rewrites the entire table for these columns.

https://github.com/grafana/grafana/issues/56151#tasklist-block-fd3d7eef-c289-4ef1-93b8-a11e7739354e

**Comment by sakjur** [comment]
> If we only change the column translation code to start returning BIGSERIAL, then new installs will have big integer columns for IDs, while old installs keep their existing 32-bit columns. At some point those older installations may start to fail when they reach IDs higher than 2^31.

Maybe we could tolerate that? Is there a natural path that any instance is likely for any of these values ever reach more than two billion IDs?
I'm wondering if "fix it going forward" and "ignore it backward" is safer than fixing it for everyone? 🤔

**Comment by joeblubaugh** [comment]
I think it's probably OK - you could imagine some machine-driven Grafana instance doing crazy stuff, but failures would at least be "loud and clear".

The current situation is repeatedly causing CI failures: https://drone.grafana.net/grafana/grafana/82718/4/9
