### ISSUE TITLE
Mixed datasource is not working in version 3.1

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#5617]
This is related to the closed ticket:
https://github.com/grafana/grafana/issues/5440

All our dashboards that use mixed data sources broke. Please take a look at it. 

Thanks,

Andrew

**Comment by mtanda** [comment]
This issue is similar what I encount in beta version.
https://github.com/grafana/grafana/issues/5459

```
Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
```
These information is very important, I think you should include these information.

**Comment by mtanda** [comment]
If you can use Chrome developer tools, please open it and capture error message.
It is very helpful to investigate.

**Comment by AGirin** [comment]
Grafana version is 3.1. 
Datasources are Graphite servers. 
OS is CentOs 6.6

And I am not seeing any errors. The page just hangs without displaying anything.

**Comment by AGirin** [comment]
Actually looks like I see a lot of similar errors in Chrome dev console:

![image](https://cloud.githubusercontent.com/assets/5177657/16995054/cd71acd2-4e6f-11e6-98d5-52a59193a108.png)

**Comment by mtanda** [comment]
Thanks for update!
I guess you add multiple Graphite server as datasource, and set query for these servers by Mixed datasource, right?

**Comment by AGirin** [comment]
Yes, correct:

![image](https://cloud.githubusercontent.com/assets/5177657/16999280/cdd983bc-4e82-11e6-9006-cb1ca5aae0c2.png)

**Comment by mtanda** [comment]
I success to replicate.
![graphite_mixed1](https://cloud.githubusercontent.com/assets/224552/17009964/c0e50de4-4f3a-11e6-997e-59ac00f3c961.png)

The requestId (for Graphite datasource) in this line should be unique.
https://github.com/grafana/grafana/commit/81e9aa4de430ac9a865ecad91feb6cea91c0666c#diff-fba613d41443865e5e1d416756aae4a4L36

@torkelo please check.

**Comment by svenmueller** [comment]
Thx!
