### ISSUE TITLE
Explore: timerange keyboard bindings behave weirdly

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#56175]
**What happened**:
There are a few weird behaviours related to using time range keyboard bindings in Explore:

<details><summary>1. (fixed by https://github.com/grafana/grafana/pull/61892) Navigating away from explore and then back to it causes keybindings to be ignored (no error in console):</summary>

https://user-images.githubusercontent.com/1170767/193575390-d9c998f4-1be3-45ce-a48b-721210ae4e08.mov
</details>

<details><summary>2. In split view, only right pane's time range is updated:</summary>

https://user-images.githubusercontent.com/1170767/193575696-79b43e5c-07f4-4065-8a02-90041d98a8fd.mov
</details>

<details><summary>3. (not reproducible in 10.0) after closing split view it errors:</summary>

https://user-images.githubusercontent.com/1170767/193575904-6a138aac-fd0e-47e1-ae0c-94cad97cf1a1.mov

(opening the split view again is then similar to point 2)

**What you expected to happen**:

1. When navigating back to explore, it should work as normal
2. both pane should be affected (debatable)
3. no error should happen, it should work as normal.

</details>

**How to reproduce it (as minimally and precisely as possible)**:

se screen recordings

**Anything else we need to know?**:

**Environment**:
- Grafana version: `main`

**Comment by gelicia** [comment]
The first and third aspect of this are very straightforward and ready to be worked on - if that can happen, feel free to break those out into a different ticket and work on those and the second aspect which requires some UX help can be dealt with differently.

**Comment by radiorental** [comment]
WRT #2, from a UI interaction perspective I strongly advise to have the keyboard shortcuts apply universally.  There's no affordance currently to indicate only the RHS pane respects the input.  There's also no method currently to change the focus of the input.  I have also not been able to find a use case to support keyboard shortcuts only affecting one of the panes.

**Comment by gelicia** [comment]
Bug 1 will be fixed by #61892

**Comment by ifrost** [comment]
Bug 3 does seem to be happening any more.

Regarding bug 2:

I think there's some technical debt that would need to be addressed first to make this work nicely. Technically keyboard shortcut modifies TimeService's range which is singleton. Explore doesn't use its value directly, but holds two separate time ranges per each pane. Every time user changes the range, it's synchronized back to the singleton. The same happens with templating service. We synchronize TimeService and TemplateService *before* the query is run.  This is to make all downstream dependencies work fine, e.g.:

- This allows interpolation of __from/__to variables work fine for the query that is being run, or 
- Loki Data Source which uses TimeService to calculate query stats.

Ideally we would like to not depend on the singleton but there's a few Explore dependencies that rely on it, so might not be easy. 

Alternatively we could...

1. don't trigger time keyboard shortcuts in split mode (+ docs) (...but it has low visibility)
2. sync panes (using left as the source) before the keyboard shortcut is triggered (...but it's a bit unexpected why left panel is the source)
3. override time range keyboard shortcuts in Explore and create custom handlers for events like `ShiftTimeEvent` (...but is harder to maintain and requires some code duplication, also it'd require adding new shortcuts 

@grafana/explore-squad / @diegoadams - do you think option 1 or 2 would improve the situation in any way?
