### ISSUE TITLE
Auth: synced users through external Auth should be seen in roles

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#56189]
**context**

When assigning roles for users in Grafana that have been synced via external auth provider it is unclear that we are not able to change their roles.

see image:
![Screenshot from 2022-09-30 16-00-53](https://user-images.githubusercontent.com/7727602/193600290-d7bfeb62-aa13-4e19-aeaa-192789e7b9df.png)

**proposal**
Add synced via <auth provider> to the context of the role picker, as the role picker is tied to their roles of the external authentication provider.

The following should be able to provide context for what needs to be done on a implementation level:

We should include `lockedEdit` and `lockedMessage` in the rolepickerwrapper
https://github.com/grafana/grafana/blob/main/public/app/features/admin/UserOrgs.tsx#L202

we extend the component to include the same information as the “Synced via <Auth>” we have for  UserProfileRow

Same way we do in userprofile - https://github.com/grafana/grafana/blob/main/public/app/features/admin/UserProfile.tsx#L95

**Comment by 201B153** [comment]
- But doesn't `basicRoleDisabled` work the same as `editLocked`

![image](https://user-images.githubusercontent.com/89572392/193633393-902d2d82-ad31-4c9d-88ed-ec6223f7b0fa.png)
in 
![image](https://user-images.githubusercontent.com/89572392/193633649-68a658b6-d4a3-45d4-9142-b3d0a8297ae1.png)

**Comment by ashutosh887** [comment]
I would like to work on the issue if not resolved yet @eleijonmarck  @mstomar698

**Comment by eleijonmarck** [comment]
@ashutosh887 you are free to give it a go. Remember to implement the locking behaviour so that it is consistent with our current implementation. Let me know if you need some pointers!

**Comment by a-loke** [comment]
Hi @eleijonmarck,  as I can see this issue is still open, and I would like to contribute. I have set up Grafana on my local machine. I could not signup via external authentication providers. I can only log in with admin user credentials or create an account using the invite link. Can you tell me how to create a user via external authentication providers?

**Comment by eleijonmarck** [comment]
@lokeswaran-aj we have made some changes for this UI and backend. do you mind merging main?

Your contribution was great. Wondering how you feel about the synced users UI now?

**Comment by eleijonmarck** [comment]
We are going to make some improvments to this in grafana, we refactored the backend to make it easier. you can see the progress here - https://github.com/grafana/grafana/issues/63835

**Comment by lokeswaran-aj** [comment]
> @lokeswaran-aj we have made some changes for this UI and backend. do you mind merging main?

Sure, please go ahead with merging my changes with the main.

**Comment by eleijonmarck** [comment]
@lokeswaran-aj oh i meant if you could update your branch with main "merging from main" as we have made alot of changes. We actively working on this and making improvements. So i would like to see if you feel like latest main makes sense to you (UI wise).

We are merging these changes soon - https://github.com/grafana/grafana/pull/64033

**Comment by lokeswaran-aj** [comment]
Oh, you are asking me to take the latest pull resolve if there is any conflicts, aren't you?

**Comment by eleijonmarck** [comment]
@lokeswaran-aj you could also pull from the PR that i referenced and see if that makes sense

**Comment by eleijonmarck** [comment]
@lokeswaran-aj we had a huge backend refactoring work, so the labels are no longer required in the frontend. 🙏 

So this change is already covered by it. I think the efforts in your PR is not required.
