### ISSUE TITLE
Embedded graph's height not working

### ISSUE THREAD

**Issue by PaulieShore** [grafana/grafana#5618]
* **I'm submitting a ...**
- [X] Bug report

- What Grafana version are you using?

v3.1.0

- What datasource are you using?

Graphite

- What OS are you running grafana on?

Ubuntu 14.04

- What did you do?

Upgraded to v3.1.0

- What was the expected result?

Embedded graphs (iFrames) would not be impacted. 

- What happened instead?

Embedded graphs using iFrames are not using the designated height. For example, a graph has a height of 180px, the embedded iFrame code is height=180, but the graph is truncated vertically. Changing the graph's height has no impact when embedded. 

My graphs include the legend, as a table, to the right, and show MAX, CURRENT, and AVERAGE stats. 

It appears the height of the graph is ignored when embedded using an iFrame.

**Comment by torkelo** [comment]
fixed in master & 3.1.x branch, 
https://github.com/grafana/grafana/issues/5605
