### ISSUE TITLE
Register new queries available in InfluxDB - Holt Winters

### ISSUE THREAD

**Issue by TheFlyingCorpse** [grafana/grafana#5619]
- [ X ] Feature request

Please include this information:
- What Grafana version are you using? 3.1.0
- What datasource are you using? InfluxDB 1.0 beta
- What OS are you running grafana on? Debian Jessie
- What did you do? Read changelog of InfluxDB 1.0 beta
- What was the expected result? Someone else already making a feature request for this or opening a PR
- What happened instead? Opening the ticket myself.

Since InfluxDB influxdb/influxdb#6621

New query types:
HOLT_WINTERS()
HOLT_WINTERS_WITH_FIT()

Docu: https://docs.influxdata.com/influxdb/v1.0/query_language/functions/#holt-winters

**Comment by dstreppa** [comment]
+1

**Comment by rikkuness** [comment]
+1
