### ISSUE TITLE
A11y: Focus disappears when closing Time Picker menu on a dashboard

### ISSUE THREAD

**Issue by polibb** [grafana/grafana#56192]
**What happened**:
When closing the Time Picker on a dashboard with the Esc key, the focus disappears. The user does not know where their selection focus is now.

**What you expected to happen**:
Focus is kept on the Time Picker, as it was before it was open. The tooltip on the Time Picker can be closed as well.

**How to reproduce it (as minimally and precisely as possible)**:
Navigate to the Time Picker on a dashboard with Tab. Open it with Enter. Hit Escape to close it.

https://user-images.githubusercontent.com/13227501/193606818-ba8a8587-ad3a-4b6e-8676-8261411e8b22.mov

Press Shift+Tab now. The focus is on the on the Time Picker.

**Relevant WCAG Criteria**:
[2.4.7 Focus visible - Level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#focus-visible)

**Environment**:
- Grafana version: 9.3.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sysa20** [comment]
I can do that if you assign me that

**Comment by polibb** [comment]
Hi @sysa20, thank you for taking the initiative! You can open a PR when you fix it and we'll see it when you add "Fixes #56192" to it.
