### ISSUE TITLE
singlestat shows bytes with lowercase b

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#5620]
let's say i have a value of +- 100k
if in a graph panel i chose datarate bits/s this will show as 100 Mbps, and bytes/s is shown as 100 MBps. this is good.

in singlestat it's shown as 100Mbps either way. when it's bytes/s it should be 100 MBps.

**Comment by torkelo** [comment]
did you refresh the dashboard (trigger rerender)? 

It's working for me, although I have to hit dashboard refresh for the new unit to take effect, think this if fixed in master. 
![image](https://cloud.githubusercontent.com/assets/10999/17023378/6383c3ac-4f53-11e6-81dd-a0a16cb257f3.png)
