### ISSUE TITLE
Explore: Fix various styling issues around split resize feature

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#56213]
**What happened**: 
As reported by @torkelo  - there are styling inconsistencies in Explore following the split resize feature https://github.com/grafana/grafana/pull/56190/files#r985932734

Also, I was able to create a situation where the pane would bounce back and forth from the minimum size and another size. That should not occur.

**What you expected to happen**:
Explore to look primarily the same, and for no "dancing panes" 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Main

**Comment by ifrost** [comment]
> Also, I was able to create a situation where the pane would bounce back and forth from the minimum size and another size. That should not occur.

What's the way to reproduce it in the reverted PR?
