### ISSUE TITLE
HELM: lots of CVEs in project dependencies pulled in

### ISSUE THREAD

**Issue by jcpunk** [grafana/grafana#56212]
**What happened**:
Reviewing https://artifacthub.io/packages/helm/grafana/grafana the security report shows a number of grafana dependencies have security issues.

**What you expected to happen**:
Some sort of automated tooling to open bugs/PRs/etc against grafana to avoid producing images with insecure dependencies

**How to reproduce it (as minimally and precisely as possible)**:
https://artifacthub.io/packages/helm/grafana/grafana?modal=security-report

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by gelicia** [comment]
@jcpunk Looking at this, it seems the scan was done on a different Grafana repository - https://github.com/grafana/helm-charts. Can you confirm that is the case, and if so, can you close this issue and open a new one in the other repository?

**Comment by jcpunk** [comment]
The scan report points to usr/share/grafana/bin/grafana-cli and usr/share/grafana/bin/grafana-server which I'd expected come out of here... are those artifacts generated in the helm chart?

**Comment by gelicia** [comment]
@jcpunk Oh, interesting - I'm not sure! I'll keep this open and pass it to the security team to take a look at.
