### ISSUE TITLE
Grafana panel repeat not consistent

### ISSUE THREAD

**Issue by kotwal13aditya** [grafana/grafana#5621]
* **I'm submitting a Bug Report**

Please include this information:
- What Grafana version are you using?
3.1.0-1468321182
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Hosted on - Ubuntu 14.04.4 LTS
Browser - Chrome/Safari on MacOS

- What did you do?
I have a single row with a single panel (graph):

- Query: SELECT "value" FROM /^$Graphs$/ WHERE "host" =~ /^$entitySelected$/ AND $timeFilter
- Repeat Panel: $Graph
- Title: $Graphs 

$Graph is multi-valued, and $entitySelected is single-valued variables. Currently $Graph has 6 values:

$Graph = {'m1','m2','m3','m4','m5','m6'}
$entitySelected = {'host1', 'host2'}

I have selected $Graph as "ALL".

- What was the expected result?
When I change $entitySelected = host1, I should see 6 graphs for host 1. Then, when I change to host2, I should see 6 graphs for host2.

- What happened instead?
When I change $entitySelected = host1, I correctly see 6 graphs for host host1. Then, when I change to host2, I should see 11 graphs for host2. 6 correct graphs for host2, and 5 extra graphs each of them containing all metrics m1 through m6 for host2. When I refresh:

1) If dashboard is not in editable mode, it get corrected to 6 graphs with 1 metric each of host2
2) If dashboard is not editable mode, the problem persists. If I change it back to host1 in this case, I end up with 16 graphs.

Another way to repro is to have a graph repeat for a multi-select variable. Change from ALL to use one of the values, and then it also shows N-1 extra graphs with that one metric. Gets correct once you refresh.

**Comment by torkelo** [comment]
can you describe steps to reproduce here?
http://play.grafana.org/dashboard/db/graphite-panel-repeats

**Comment by kotwal13aditya** [comment]
Hi @torkelo , thanks for creating the environment. In order to repro the issue, I will need an influx db database with a bit different structure. The issue occurs when the variable on the basis of which the panel repeats, is itself dependent on another variable.

In my case panels repeat for each $Graph, while $Graph in itself is dependent on $pageNumber

Variable $Graph is defined as all tags for that $pageNumber:
`show tag values from $pageName with key="graph"`


So, in short, can you add some entries to the "grafana" database:

```
page1,graph=cpu
page1,graph=derivative
page1,graph=logins.count
page2,graph=logs
page2,graph=payment.end
page2,graph=payment.started
```

the values in graphs would thus be decided by a 'custom' variable $page with values page1,page2.

which is basically being able to choose the following metrics through an intermediate page variable.

![screen shot 2016-07-21 at 12 55 16 pm](https://cloud.githubusercontent.com/assets/19351144/17036744/7253e454-4f42-11e6-98d8-f9789560b90b.png)

.. i don't think I have access to the database.

**Comment by torkelo** [comment]
but this dashboard has the exact same setup:
http://play.grafana.org/dashboard/db/graphite-panel-repeats?var-app=backend&var-server=All&var-interval=$__auto_interval

Server set to All 
Server is dependent on what you select for app, and when I change it everything is working as expected.

**Comment by kotwal13aditya** [comment]
Ok, I was able to reproduce it on your dashboard. It gets confused when I add row-repeats:

1) Step 1: Add a template variable called test (custom) with values 'test1','test2'.
2) Select value at test1
3) In row-editor, change row policy to repeat on test
4) Now switch between test1 and test2 and you'll see the issue. Here is the snapshot:

![screen shot 2016-07-21 at 1 30 50 pm](https://cloud.githubusercontent.com/assets/19351144/17037785/63f687c2-4f47-11e6-8b75-0435e0517b29.png)

**Comment by torkelo** [comment]
you cannot mix row repeats and panel repeats right now, or rather it is not supported

**Comment by kotwal13aditya** [comment]
thanks Torkel. Is there a feature request tracking this? Can you point me to code dealing with this, it is quite important for my application.

**Comment by torkelo** [comment]
No feature request that I know of, it's not very easy to combine row repeat and panel repeat as the variables don't know which value belongs to which subset of child value. 

so variables:
app ALL = (backend, fakesite)
server ALL = (backend_01, backend_02, web_server_01, web_server_02)

if you repeat a panel for each value in server then you will get 4 panels, and if you repeat that row for each value in app you will get 2 rows, row 1 will contain 4 panels (with app scoped to backend), row 2 will also get 4 panels with app scoped to fakesite. 

The panel & row repeat code is very complex:
Code
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dynamicDashboardSrv.js
Tests:
https://github.com/grafana/grafana/blob/master/public/test/specs/dynamicDashboardSrv-specs.js

I do not see an easy way to solve it but you might
