### ISSUE TITLE
Can't add Graphite datasource, due to "Cannot read properties of undefined" on Test

### ISSUE THREAD

**Issue by dragoangel** [grafana/grafana#56210]
**What happened**:
While adding a new Graphite datasource following error appears: `Cannot read properties of undefined (reading 'get')`
**What you expected to happen**:
New datasource added without error
**How to reproduce it (as minimally and precisely as possible)**:
1. Go to datasources
2. Add Graphite datasource url, no basic auth etc
3. Click on Test button

**Anything else we need to know?**:
Enabling debug logging does not provide any details in the container console as well

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Graphite 1.1
- OS Grafana is installed on: grafana/grafana docker image
- User OS & Browser: any
- Grafana plugins: -
- Others: -

**Comment by gtk-grafana** [comment]
This looks like a recent escalation which resulted in https://github.com/grafana/grafana/pull/56029, which will be released in 9.1.7.

**Comment by dragoangel** [comment]
@gtk-grafana Hi, thank you for your quick reply. Waiting 9.1.7 now even more then before :)

**Comment by gtk-grafana** [comment]
Closing this out, please reopen if you're still having issues with 9.1.7, thanks for taking the time to report this!

**Comment by dragoangel** [comment]
@gtk-grafana update to 9.1.7 fixed issue, thx
