### ISSUE TITLE
PluginDetails: Custom config page has incorrect breadcrumb  

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#56230]
Load a react plugin config page 

like synthetic monitoring 
http://localhost:3000/plugins/grafana-synthetic-monitoring-app?page=config

The breadcrumbs reads just Plugin page. I am unable to replicate it with the starter app plugin. 

![Screenshot from 2022-10-04 09-03-27](https://user-images.githubusercontent.com/10999/193756308-24d4d4d8-a5b5-49f2-8297-c49afefebb34.png)

**Comment by andresmgot** [comment]
I am not able to reproduce this with the latest version:

![Screenshot from 2023-02-06 17-33-59](https://user-images.githubusercontent.com/4025665/217029527-870dacac-5da3-4fa2-a0fe-613d69e7d92a.png)

Is this still an issue?

**Comment by sympatheticmoose** [comment]
Please reopen if still an issue
