### ISSUE TITLE
[Feat] Gitlab oauth backend with support for filter by groups

### ISSUE THREAD

**Issue by zingmars** [grafana/grafana#5623]
- **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using? 3.1.0
- What datasource are you using? InfluxDB 
- What OS are you running grafana on? Ubuntu 14.04 LTS
- Feature request - I was looking into the authentication methods supported for Grafana as our org is in need of a way to chart data coming out of our software. Since everyone involved with the project has access to our GitLab instance, I thought it would be nice to have that as an authentication method. Grafana already supports GitHub as an authentication method, and I actually managed to authenticate with GitLab using the GitHub oAuth method (their APIs are near identical in most cases), but I had to remove the scope parameter from the URL Grafana sends you to when you authenticate to achieve this, so unless I can figure a way to make it drop or disregard this parameter it's not an ideal solution.

**Comment by torkelo** [comment]
maybe this can be solved by this?
https://github.com/grafana/grafana/pull/4718

**Comment by kri5** [comment]
@torkelo #4718 solves the issue of getting authentication to work, but it doesn't allow to filter by groups, which is the equivalent of teams/org in github.

So if you're hosted on a shared instance of gitlab, you cannot restrict access to the concerned teams.
