### ISSUE TITLE
update grafana on synology docker

### ISSUE THREAD

**Issue by KevinSzr** [grafana/grafana#56244]
Hi,
I am running grafana 7.3.7 in a docker on my Synology NAS. As I endountered some isues I would like to update the image.
Unfortunately the newly created docker image is a blank one (admin:admin / no dashboards) although I copied all the docker settings:

![grafik](https://user-images.githubusercontent.com/79407376/193770040-6e79ffb3-a1dd-41ca-8dbb-044bf6f8ace4.png)

As soon as I activate the old image all the data is still there.

Am I doing anything wrong or is there a bug?

Best regards,
Kevin

**Comment by gelicia** [comment]
I am not sure if this would be a problem with docker or synology but we can investigate.

**Comment by KevinSzr** [comment]
Is there anything I can provide to help 'investigating'?

**Comment by gelicia** [comment]
@KevinSzr Unfortunately this isn't something I know a lot about. Do you have a version for synology youre using? Have you done similar updates in synology and had it work? We can check the docker upgrade between those two versions works but it might also be something to contact Synology about

**Comment by sakjur** [comment]
It looks like your mount point is for `/lib/grafana` and the Grafana data directory is `/var/lib/grafana`, so it looks like your Grafana data isn't persisted in the volume? 🤔
You should be able to dig into the image and pick out the content of the 7.3.7 (I never cannot think of the airplane model when I see that version number 😅) and move it into your volume for the future, but I really don't know how you'd do that in Synology.

**Comment by KevinSzr** [comment]
@sakjur  This seems to be the reason.
I will try to fix that.

**Comment by gelicia** [comment]
I'll close this assuming the discrepancy was the issue here. Please reopen if that's not the case.
