### ISSUE TITLE
Dashboard stored on disk can't be used in playlist.

### ISSUE THREAD

**Issue by uhriap** [grafana/grafana#5624]
* **I'm submitting a ...**
- [ ] Bug report

- What Grafana version are you using? 3.1.0

All disk dashboards (dashboard.json) have id = 0.
When creating/editing playlist all disk dashboards filtered out from available list if any of them added to playlists, because of the same id for all of them
When playlist with such dasboards starts (play), none of them returned by api, cause only db dashboards assumed.

I fixed it for us in [this commit](https://github.com/uhriap/grafana/commit/e1fa77fc107d38f5ab1616b60483e080363ec3da), not shure it is good enough for pool request.

**Comment by torkelo** [comment]
We will likely  be phasing out loading json files directly as these dashboards cannot be starred or marked as a home dashboard. The substity feature will be sync tools that can sync directories with json files to the Grafana db

**Comment by MartinLeedotOrg** [comment]
Reviving this because I just ran into the same issue with Grafana v4.2.0 (commit: 349f3eb)

We're keeping dashboards as json so that we can version control them.

**Comment by torkelo** [comment]
for dashboard json files you can import them into the database using somethig like https://github.com/utkarshcmu/wizzy

We are going to depricate the dashboard.json feature and instead replace it with something like wizzy that can import them and export them to/from json files
