### ISSUE TITLE
[BUG] template variable not being expanded in metric query

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#5626]
Please include this information:
- What Grafana version are you using? 3.1
- What datasource are you using?  Graphite
- What OS are you running grafana on? Ubuntu
- What did you do? loaded dashboard which uses template variables
- What was the expected result? all panels to load
- What happened instead? panels where metric queries use multiple template variables intermittently fail due to the metric query being invalid due to template variable not being expanded.

This is happening on worldping-endpoint-dns, worldping-endpoint-web dashboards, and it is always the $outlier variable that is the problem, which is a static

Metric Query:
```
aliasByNode(removeAbovePercentile(litmus.$endpoint.$probe.dns.time, $outliers), 2)
```

Body sent in request to Graphite.
```
target:aliasByNode(removeAbovePercentile(litmus.google_com.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.dns.time, $outliers), 2)
```

**Comment by torkelo** [comment]
does this always happen? cannot see it on
https://app.raintank.io/dashboard/db/worldping-endpoint-dns

**Comment by woodsaj** [comment]
found an interesting issue.

![templatevarissue](https://cloud.githubusercontent.com/assets/8415072/17029547/3b0aaaf8-4f9e-11e6-8d02-c7b8d24332dc.png)

but when refreshing the dashboard (full page refresh) and the panel loads and the outliers template variable is present in the Templating config drop down.

**Comment by woodsaj** [comment]
And no, this does not always happen, it is intermittent.

**Comment by torkelo** [comment]
any errors in chrome console when this happens?

**Comment by woodsaj** [comment]
No errors in chrome console.

I do find that this issue is triggered when i navigate to the dashboard from the endpoint-list page, but doesnt happen when i hard refresh the page.

**Comment by mattttt** [comment]
@woodsaj Does this also lead to the UI error being thrown, "Template variables could not be initialized: Cannot read property 'message' of null”

Or is that different?

**Comment by woodsaj** [comment]
That is a separate issue.  For this issue, it is just the panel that doesnt load due to the graphite query resulting in a 500 response (graphite removeBelowPercent function expects a number and gets "$outliers" instead)

**Comment by torkelo** [comment]
seems like when you click on the DNS link from the endpoints list page it tries to load the summary dashboard and then at the same time the DNS dashboard, maybe a cancel event propagation issue again?

**Comment by torkelo** [comment]
@woodsaj but if happens only when you go from endpoint list is seems likely that the loading of two dashboards at the same time could be the cause

**Comment by woodsaj** [comment]
Sounds like the obvious culprit.  Opened https://github.com/raintank/worldping-app/issues/130 to address it.

**Comment by woodsaj** [comment]
adding the $event.stopPropagation looks to have solved the issue.  Thanks.
