### ISSUE TITLE
Current version of Jquery (2.1.4) has known security vulnerabilities and should be updated

### ISSUE THREAD

**Issue by kjlubick** [grafana/grafana#5627]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Grafana 3.1.0 uses Jquery 2.1.4, which has a known XSS vulnerability
https://github.com/jquery/jquery/issues/2432

It should be updated to at least JQuery 2.2

**Comment by torkelo** [comment]
thanks for informing us, will fix!

**Comment by szarouski** [comment]
Hi, unfortunately if you take a look at jquery/jquery#2432 you'll see that fix was only added in version 3. There is no fix for v2.

**Comment by torkelo** [comment]
ok, well then the upgrade will have to wait and happen in stable branch, not doing a major jquery update in a patch release :)

**Comment by torkelo** [comment]
upgraded master to jquery 3.1.0
