### ISSUE TITLE
Alerting queries omit authentication header when connected to an InfluxDB datasource using InfluxQL

### ISSUE THREAD

**Issue by btasker** [grafana/grafana#56285]
**What happened**:

When creating alerts, using an InfluxDB datasource and InfluxQL, a 401 Authorization failure is returned

![Screenshot_20221004_115558](https://user-images.githubusercontent.com/88340935/193801952-97878e34-8d6a-4469-95b8-7007cfe33e33.png)

For avoidance of doubt, the same datasource works fine when used in dashboards.

A test with a packet capture shows that credentials are not being sent to the upstream datasource

![Screenshot_20221004_115308](https://user-images.githubusercontent.com/88340935/193802285-30b99850-aa10-4694-ab38-49270d04749c.png)

**What you expected to happen**:

The query should run successfully

**How to reproduce it (as minimally and precisely as possible)**:

- Create an InfluxDB Datasource, using InfluxQL (you can use a HTTP server rather than Influx if you just want to verify what hits the wire)
- Ensure a username/password is set in the datasource config
- Go to alerts, alert rules, create an alert ruke
- Select the InfluxDB datasource
- Hit `Run Queries`

You'll get a 401 back (or a 404 if you're talking to a webserver rather than Influx). If you run packet captures you'll see there's no `Authorization` header in the request.

**Anything else we need to know?**:

Had hoped it was only the UI triggered queries which fail, but pushing ahead and creating the alert leads to those failing too.

This doesn't affect datasources using Flux - auth headers are correctly included with upstream requests for those.

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: InfluxDB (any)
- OS Grafana is installed on: Tested on a range
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by grobinson-grafana** [comment]
Hi! :wave: Would it be possible to upgrade to the latest version of Grafana 9.1.7 and see if this issue is still present?

**Comment by btasker** [comment]
Sure - just a side note, although there's a `9.1.7` tag, the `latest` tag in docker hub is currently still pointing to `9.1.6`, not sure if that's deliberate?

Looks like this is fixed in 9.1.7, thanks!

![Screenshot_20221005_085346](https://user-images.githubusercontent.com/88340935/194009105-3c169bb8-a1e8-44fc-88dd-d171eefb21c6.png)
