### ISSUE TITLE
Grafana always connect to default Cloudwatch account

### ISSUE THREAD

**Issue by vinhlh** [grafana/grafana#5628]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Latest
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
Docker
- What did you do?
Add multiple Cloudwatch profiles
- What was the expected result?
Per Datasource per profile
- What happened instead?
Always use default profile.
Try to set invalid profile name, Click `Test`, still get successful notice.

**Comment by torkelo** [comment]
do you have a ~/.aws/credentials file in the grafana user's home directory?

**Comment by vinhlh** [comment]
@torkelo yes, I had. I must have that file to test data source successfully.
