### ISSUE TITLE
Sag DS -Token Semantics

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#56298]
Establish a scaleable semantic structure for our design tokens to ensure consistency and adoption.

**Comment by staton-hyse11** [comment]
[Figma file](https://www.figma.com/file/320OLRpxmHyeNps3zsAvt4/CSSstats-Color-Exploration?node-id=27%3A10&t=s3jqn6V9zWJyJejg-1) where semantic token structure is being explored

**Comment by Aires-Grafana** [comment]
We can close this issue. It is being addressed at #78865 
cc @staton-hyse11
