### ISSUE TITLE
Logs: in mixed-datasource-mode, in explore, logs related functions don't work correctly

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#56314]
when mixed datasource mode is enabled, and, in explore, you choose the mixed datasource, some things don't work correctly:
- histogram says no support for full range histogram, even when there is support (for example, in Loki & Elastic)
    - this will be complicated, created separate github-issue at https://github.com/grafana/grafana/issues/57354
- using the [+]/[-] buttons in log-row-details does not do anything, even if you only have a single Loki query
    - fixed in  https://github.com/grafana/grafana/pull/56560
- using the [+]/[-] buttons in table-view does not do anything, even if you only have a single Elasticsearch query
     - fixed in https://github.com/grafana/grafana/pull/57356
- using the log-row-context is probably problematic too
     - separate issue created at https://github.com/grafana/grafana/issues/57359
- using split button in logs sample won't work

**Comment by gabor** [comment]
note: every time, where, in explore, we look up the correct datasource, we will have to modify the code, because the datasource that we get back the "old" way is a `MixedDatasource`.
we will have to take the given `query`, and find the `datasource` from there.
the code to do that is:
```
import {getDatasourceSrv} from '@grafana/runtime';

const ds = await getDatasourceSrv().get(query.datasource);
```

please note, this is async, so we are going from a `query` to a `Promise<Datasource>`.

**Comment by ivanahuckova** [comment]
Log context will probably need a fix too.

**Comment by evandandrea** [comment]
- We think this has to happen in Q4. @gabor has the details.

**Comment by gtk-grafana** [comment]
Closing out as everything has been merged in!
