### ISSUE TITLE
labels to fields: transformation drops refid 

### ISSUE THREAD

**Issue by kranthikirang** [grafana/grafana#56312]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/18152400/193852790-cce83593-2b45-45b5-90e9-0854a97bc6e6.png">

Grafana 9.1.2 with any datasource when we transform labels to fields and transformation output doesn't show refId at all

Refid should be available after transformation

Query: a time series simple query
SELECT $__timeGroup(DATETIME,$__interval) as Time, HOST as metric, (max(USED/10241024)/max(TOTAL/10241024)*100) AS used_percent FROM SERVER_MEMORY WHERE $__timeFilter(DATETIMEUTC,$__interval) GROUP BY 1,2 ORDER BY 1

Add a transformation labels to fields to display all nodes/servers as columns. Look at the transformed output

**Comment by bohandley** [comment]
Can you give us a little more context, what are you trying to achieve having the refid shown?

**Comment by kranthikirang** [comment]
Say a panel or flowcharting plugin depends on refId to get the column data. If the refId is undefined it will fail. Since  labels to fields transformation drops it we can't use those plugins

**Comment by kranthikirang** [comment]
@LudoVio thanks a lot for the fix. Any idea when this will be delivered as part of grafana docker image? or perhaps how to build a new docker image with this change?

**Comment by LudoVio** [comment]
It will be included in the next Grafana release. From a few days to a few weeks I would say, no release date yet.

Grafana also provide docker images of the last successful build of main

```sh
docker run -d -p 3000:3000 grafana/grafana-oss:main
```

The changes will be there.

You can learn more [here](https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/)

**Comment by kranthikirang** [comment]
this is great; I have used main image and transformations works like charm. Great help to overcome our issue. Really appreciate it @LudoVio
