### ISSUE TITLE
Prometheus annotations title and text problem

### ISSUE THREAD

**Issue by LuboVarga** [grafana/grafana#5633]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- I am using Grafana v3.1.0 (commit: v3.1.0) 
- My datasource is Prometheus
- Grafana and also prometheus is running on Centos 7.2
- What did you do?

I have set up annotations for dashboard with alerts. I have set "job,instance,alertname,alertstate" into all three Field formats (title, tags and also text). My queried alert data are something like this:

```
ALERTS{alertname="InstanceDown",alertstate="firing",env="test54",instance="testb.asdf.sk:2560",job="appX",severity="warning"}
ALERTS{alertname="InstanceDown",alertstate="pending",env="test54",instance="testA.asdf.sk:2570",job="appX",severity="warning"}
```
- What was the expected result?

I have expected (because of pre filled shadow text suggested it a bit) that all entered strings will be replaced by actual label values from selected data. i.e., title of annotation will be something like "appx,testA.asdf.sk,InstanceDown,pending". I have also tryied another format of title field. like "job", "$job" or "{job}", but nothing worked.

- What happened instead?

given text was presented in annotation as is (without replacing placeholders with real label data). This was only problem in title and text field. tags was working ok.

**Comment by LuboVarga** [comment]
![grafanaannotations](https://cloud.githubusercontent.com/assets/17848321/17049257/813f79c4-4fec-11e6-9222-73f85f2f436f.png)

**Comment by torkelo** [comment]
I think replacement syntax for prometheus is `{{label}}` sorry, this should be made clear in the UI and docs

**Comment by LuboVarga** [comment]
Thanks for solution.

PS: Make tags also require that syntax and for sure make "text" area bigger and perhaps multiline.
PS2: it would be helpfull, if given syntax is also visible on screens here http://docs.grafana.org/reference/annotations/

**Comment by LuboVarga** [comment]
One last thing: is it possible to use templating variable in annotations? (in query for annotation it is working with **$var**, but **$var**, nor **{{var}}** is working in text/title part of annotation.)
