### ISSUE TITLE
Dashboard alert migration fails if escaped character in alert message

### ISSUE THREAD

**Issue by joaoluchetti** [grafana/grafana#56338]
**What happened**:
Grafana won't start after upgrading to unified alerting, following error is on logs:
```
{"id":"clear migration entry \"remove unified alerting data\"","level":"info","logger":"migrator","msg":"Executing migration","t":"2022-10-04T18:40:35.9043244Z"}
{"id":"clear migration entry \"remove unified alerting data\"","level":"debug","logger":"migrator","msg":"Executing code migration","t":"2022-10-04T18:40:35.904371403Z"}
{"id":"move dashboard alerts to unified alerting","level":"info","logger":"migrator","msg":"Executing migration","t":"2022-10-04T18:40:35.906210792Z"}
{"id":"move dashboard alerts to unified alerting","level":"debug","logger":"migrator","msg":"Executing code migration","t":"2022-10-04T18:40:35.906296808Z"}
{"error":"invalid character '\\n' in string literal","id":"move dashboard alerts to unified alerting","level":"error","logger":"migrator","msg":"Executing migration failed","t":"2022-10-04T18:40:36.168881344Z"}
{"error":"invalid character '\\n' in string literal","level":"error","logger":"migrator","msg":"Exec failed","sql":"code migration","t":"2022-10-04T18:40:36.168958518Z"}
Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): invalid character '\n' in string literal
migration failed (id = move dashboard alerts to unified alerting): invalid character '\n' in string literal
```
i have turned it on with the following config:
```
  unified_alerting:
    enabled: true
  alerting:
    enabled: false
```
Any ideas on where this invalid character is coming from?

**What you expected to happen**:

Successful migration and grafana startup.

**How to reproduce it (as minimally and precisely as possible)**:

Enable unified alerting and start Grafana

**Anything else we need to know?**:

I upgraded from Grafana 8.3.4 to Grafana 9 with unified alerting disabled, Grafana was working fine at this time. Although when i try to enable unified alerting i get the described scenario

**Environment**:
- Grafana version: 9.1.5
- OS Grafana is installed on: Kubernetes

**Comment by grobinson-grafana** [comment]
Hi! :wave: Would it be possible to find the alert in the `alert` table that has the escaped newline `\\n` and tell us what column it's in?

**Comment by joaoluchetti** [comment]
Hi @grobinson-grafana, 

i was able to find the problematic alerts in the alert table, the collumm with problems was settings and the issue was the `\\N` on  the alert message:

```
message":"No success in`Documents\\NFe\\Emitted` on the last 13 hours
```

After removing the back slashes from the problematic messages the errors stopped and Grafana was able to finish the migration to unified alerting succesfully.

**Comment by alexmobo** [comment]
Hi @joaoluchetti! What DB were you using? Could you please share the problematic alert data (I know that might be impossible since much time has passed)?

**Comment by JanSF** [comment]
Hi @alexmobo! I'm running into this exact same issue when trying to migrate our alerts over to unified alerting using Grafana 8.5.22 on Kubernetes and Mysql. I have the Grafana logs I can share with you, and still have all the data, so I should be able to pinpoint the problematic alert data.

**Comment by cpretzer** [comment]
@alexmobo I'm seeing similar behavior as described in #79720
