### ISSUE TITLE
How to show network traffic in grafana

### ISSUE THREAD

**Issue by qi-zhou** [grafana/grafana#5636]
- What Grafana version are you using?
`version:3.1.0`
- What datasource are you using?
`elasticsearch`
- What OS are you running grafana on?
`ubuntu14.04`

I want to show network traffic in grafana, I collect OS metrics use collectd and logstash.
my query string as graph is:
![2016-07-22 19 35 17](https://cloud.githubusercontent.com/assets/16607058/17056052/8050b86e-5043-11e6-8394-1c2e1734573b.png)
my collect data format is:
```
{
  "_index": "collectd-2016.07.22",
  "_type": "collectd",
  "_id": "AVYSW6A4DqOFOtsknHvK",
  "_score": null,
  "_source": {
    "host": "logserver-1",
    "@timestamp": "2016-07-22T11:26:47.537Z",
    "plugin": "interface",
    "collectd_type": "if_octets",
    "plugin_instance": "eth1",
    "rx": 882377789,
    "tx": 2565360765,
    "@version": "1",
    "type": "collectd"
  },
  "fields": {
    "@timestamp": [
      1469186807537
    ]
  },
  "highlight": {
    "plugin_instance": [
      "@kibana-highlighted-field@eth1@/kibana-highlighted-field@"
    ],
    "plugin": [
      "@kibana-highlighted-field@interface@/kibana-highlighted-field@"
    ],
    "host": [
      "@kibana-highlighted-field@logserver@/kibana-highlighted-field@-@kibana-highlighted-field@1@/kibana-highlighted-field@"
    ],
    "collectd_type": [
      "@kibana-highlighted-field@if_octets@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1469186807537
  ]
{
  "_index": "collectd-2016.07.22",
  "_type": "collectd",
  "_id": "AVYSWwzhDqOFOtsknAql",
  "_score": null,
  "_source": {
    "host": "logserver-1",
    "@timestamp": "2016-07-22T11:26:07.537Z",
    "plugin": "interface",
    "collectd_type": "if_octets",
    "plugin_instance": "eth1",
    "rx": 882369242,
    "tx": 2565343536,
    "@version": "1",
    "type": "collectd"
  },
  "fields": {
    "@timestamp": [
      1469186767537
    ]
  },
  "highlight": {
    "plugin_instance": [
      "@kibana-highlighted-field@eth1@/kibana-highlighted-field@"
    ],
    "plugin": [
      "@kibana-highlighted-field@interface@/kibana-highlighted-field@"
    ],
    "host": [
      "@kibana-highlighted-field@logserver@/kibana-highlighted-field@-@kibana-highlighted-field@1@/kibana-highlighted-field@"
    ],
    "collectd_type": [
      "@kibana-highlighted-field@if_octets@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1469186767537
  ]
}
```
![2016-07-22 19 53 46](https://cloud.githubusercontent.com/assets/16607058/17056481/1353be8e-5046-11e6-90c8-b5394f2ff70e.png)

I find the line of trends in grafana is not real fact. how do I get tx rate and rx rate for network, what should I do?

**Comment by torkelo** [comment]
not sure what you mean, is the values shown in the graph not the same as the values returned by your ES query?

**Comment by qi-zhou** [comment]
+ not is that!  my mean is how to get "The rate of change rx/tx ", this value should be caculate by like this formula:
![screenshot from 2016-07-24 12 43 08](https://cloud.githubusercontent.com/assets/16607058/17081900/3c578214-519c-11e6-88aa-13b37c99c7c5.png)
, but after using derivative aggregation I find som results is negative number,  in fact  , I think all result should be positive number.
+ now , if you , ignore what I did , you should how to show the `network traffic` in grafana , can you tell me the query string is what?

**Comment by trevorndodds** [comment]
The counters for network reset once they hit a certain limit on the OS, I see the same issue depending on how busy the network interface is, if the interface is very busy the counter will reset very often. causing spikes in my graphs and usually an incorrect value. When using graphite as your datasource you can use the ScaleToSeconds(1) which seems to help. With Elasticsearch as a datasource you do not get this option.
