### ISSUE TITLE
Elasticsearch: Add trace to Logs functionality

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#56367]
### Summary

Add trace to logs functionality for ES to allow ES users jump into their logs from tempo traces. 

### Problem statement

Currently, ES is not supported in trace to logs functionality. We want to add logic so ES is supported for this feature. 
 
### Scope

Implementation

### Solution

This is hardcoded for splunk + loki here https://github.com/grafana/grafana/blob/2970c6db375e258a6fbf129c21b7210af248d40c/public/app/features/explore/TraceView/createSpanLink.tsx#L115
It just needs a case for elastic so it creates correct query.

And then in `public/app/core/components/TraceToLogs/TraceToLogsSettings.tsx` elasticsearch should be added.

### Resources
Discussed in https://github.com/grafana/grafana/discussions/51746

**Comment by gabor-grafana** [comment]
> With support for the latest version of Elastic, plus two older versions if possible?

just to clarify this part, it can be implemented for all the Elastic versions that we support. (we support what elastic-company supports, right now that's 7.13.x and higher, see https://www.elastic.co/support/eol)

**Comment by kyreddie** [comment]
This should also be implemented for OpenSearch datasource.

**Comment by evandandrea** [comment]
Here's the [approach taken](https://github.com/grafana/grafana/pull/46855) for Splunk.
