### ISSUE TITLE
Database migration failing after 9.1.6 image upgrade

### ISSUE THREAD

**Issue by tewfik-ghariani** [grafana/grafana#56382]
**What happened**:

I am trying to deploy the Grafana helm chart but the image with `appVersion: 9.1.6` upgraded per https://github.com/grafana/helm-charts/pull/1834 is failing the startup with the following log output:

```sh
logger=sqlstore t=2022-09-23T06:51:37.602377351Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2022-09-23T06:51:37.656249202Z level=info msg="Starting DB migrations"
logger=migrator t=2022-09-23T06:51:37.669065987Z level=info msg="Executing migration" id="admin only folder/dashboard permission"
logger=migrator t=2022-09-23T06:51:37.670377262Z level=error msg="Executing migration failed" id="admin only folder/dashboard permission" error="Error 1055: 'grafana.dashboard.uid' isn't in GROUP BY"
logger=migrator t=2022-09-23T06:51:37.670432877Z level=error msg="Exec failed" error="Error 1055: 'grafana.dashboard.uid' isn't in GROUP BY" sql="code migration"
Failed to start grafana. error: migration failed (id = admin only folder/dashboard permission): Error 1055: 'grafana.dashboard.uid' isn't in GROUP BY
migration failed (id = admin only folder/dashboard permission): Error 1055: 'grafana.dashboard.uid' isn't in GROUP BY
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
My current version is 9.1.5 and it works without any problems

**Anything else we need to know?**:
Not totally sure but it could be somehow linked to https://github.com/grafana/grafana/issues/55924

**Environment**:
- Grafana version: 9.1.5 -> 9.1.6
- Data source type & version: mysql
- Previous issue: https://github.com/grafana/helm-charts/issues/1836

**Comment by gelicia** [comment]
The migration is from an access control file, so I'm sending it to the auth team to take a look at.

**Comment by TheMeier** [comment]
I'm seeing this problem also

**Comment by coolermister** [comment]
+1

**Comment by kalleep** [comment]
Hey, @tewfik-ghariani.

What version of Mysql is you running for grafana. Was able to reproduce this with mysql 5.5 and ONLY_FULL_GROUP_BY set.
Grafana officially supports [mysql 5.7+](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases). If it is not possible to upgrade the mysql istance I think removing ONLY_FULL_GROUP_BY from sql_mode should fix it

**Comment by tewfik-ghariani** [comment]
Hii @kalleep thanks for looking into this, we are currently using '**MariaDB 10.6**'

**Comment by kalleep** [comment]
Mariadb is not a db we support and we are not running any tests against it. With that said removing ONLY_FULL_GROUP_BY from sql_mode should solve the migration issue

**Comment by tewfik-ghariani** [comment]
I confirm that the removal of the `ONLY_FULL_GROUP_BY` from sql_mode solved the migration issue

Thanks for the help
