### ISSUE TITLE
Grafana 9.1.7 - plugins cannot bind to IPv6

### ISSUE THREAD

**Issue by himuura** [grafana/grafana#56400]
**What happened**:
Updating grafana docker to 9.1.7 breaks grafana-clock-panel and grafana-simple-json-datasource
**What you expected to happen**:
I would expect it to work, just like other versions...
**How to reproduce it (as minimally and precisely as possible)**:
Just update from grafana docker image 9.1.6 to 9.1.7.
**Anything else we need to know?**:
Yes, i got this error:

Error: ✗ Get "https://grafana.com/api/plugins/repo/grafana-clock-panel": dial tcp [2600:1901:0:b3ea::]:443: connect: cannot assign requested address

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: Influx
- OS Grafana is installed on: Raspbian OS (64-bit)
- User OS & Browser: N/A
- Grafana plugins:grafana-clock-panel, grafana-simple-json-datasource
- Others: Got portainer running on top of docker, already did a "docker-compose up -d --force-recreate" with no avail...

**Comment by tolzhabayev** [comment]
It seems like your Grafana instance has no access to the internet, or some networking issues as it can not fetch the plugin from Grafana catalog so it has nothing to do with plugins.

**Comment by himuura** [comment]
> It seems like your Grafana instance has no access to the internet, or some networking issues as it can not fetch the plugin from Grafana catalog so it has nothing to do with plugins.

Sorry for the long delay!
Well, weirdly enough, this only happens with versions after 9.1.6. This one works fine in docker but when i update the container to the newer versions, i get the ipv6 issues...this is odd. will try to troubleshoot some more this weekend. Thanks mate!

**Comment by himuura** [comment]
Well, figured it out...actually, it's not a grafana per se bug, it's a docker / docker image issue...while downloading the plugins, the docker image downloads the plugins through ipv6, not ipv4 (dunno if it's intentional or not) and doesn't fallback to ipv4 if ipv6 fails.
Docker does not activate ipv6 for containers natively (at least not on Raspbian OS) so as @tolzhabayev said (and well said!) the problem was in fact with ipv6.
So, to fix it, you need to create (if you dont have) the /etc/docker/daemon.json file with the ipv6 subnet for docker containers and you need to create a ip6tables rules (don't forget to persist it or it wil fail again after reboot!!).
Here's the solution:
https://github.com/docker/for-linux/issues/648
https://medium.com/@skleeschulte/how-to-enable-ipv6-for-docker-containers-on-ubuntu-18-04-c68394a219a2#7ae3

Hope this helps someone!! Mark it as closed!
