### ISSUE TITLE
Changing a dashboard folder via dashboard settings won't save

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#56402]
**What happened**:
When going into the settings of a dashboard and changing the folder via the dropdown, the dashboard can not be saved, as the save dialogue says "No Changes to Save"

**What you expected to happen**:
The ability to save, effectively moving the dashboard to another folder. Or alternatively, the UI doesn't present the folder dropdown in dashboard settings as a changeable if it can't be changed from this view.

**How to reproduce it (as minimally and precisely as possible)**:
Try to move a dashboard to a different folder via dashboard settings

**Environment**:
- Grafana version: 0d8ea2bb34 (main as of Oct 05, 2022)

**Comment by kheuser** [comment]
I have confirmed that this issue is active on the current release. Linked pr #56590 will resolve the issue by re enabling the meta as checked when looking for changes.
