### ISSUE TITLE
The Dashboard has been changed by someone else.

### ISSUE THREAD

**Issue by mcf-rocks** [grafana/grafana#56417]
When I try to save it says - the dashboard has been saved by someone else... I am the only person who has access to the dashboard... I am the only person who knows it exists.

**Comment by gelicia** [comment]
@mcf-rocks Do you have any other replication steps? Does it happen every time you try to save?

**Comment by mcf-rocks** [comment]
It just happens sometimes... quite random.... sorry not to be more help.

**Comment by gelicia** [comment]
@mcf-rocks What version of Grafana are you using?
