### ISSUE TITLE
Custom labels in prometheus queries not working

### ISSUE THREAD

**Issue by nachogiljaldo** [grafana/grafana#56412]
**What happened**:

In build `v9.3.0-36287pre (b396f16fe1)` there seems to be some sort of issue with prometheus queries with custom labels.

No matter what custom label are specified, all labels are appended. See some examples:

![Screenshot from 2022-10-05 17-28-52](https://user-images.githubusercontent.com/998352/194100155-a34863df-3867-434a-9344-3e2aefb27701.png)
![Screenshot from 2022-10-05 17-28-28](https://user-images.githubusercontent.com/998352/194100164-ab66738a-79bf-471f-9ad4-73f60185d3d6.png)

**What you expected to happen**:

Custom labels are applied correctly.

**How to reproduce it (as minimally and precisely as possible)**:

In Explore, create a prometheus query with a custom label, for example test, you can see that it is not applied correctly.

**Anything else we need to know?**:

**Environment**:
- Grafana version:`v9.3.0-36287pre (b396f16fe1)`
- Data source type & version: prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Ubuntu / Chrome

**Comment by gtk-grafana** [comment]
I'm not able to reproduce this locally (on `b396f16fe1`) with prometheus or mimir, but I can reproduce this in the cloud instance. @grafana/hosted-grafana-team I'm a little confused as to how the prometheus functionality is different for the hosted instances?
