### ISSUE TITLE
Azure Monitor: Unable to change namespace for microsoft.storage/storageaccounts

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#56411]
**What happened**:

Selecting a sub namespace is not working:

[Screencast from 05-10-22 17:26:27.webm](https://user-images.githubusercontent.com/4025665/194099918-c3541533-20a7-487b-9ff9-c3bda3266a59.webm)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by taleena** [comment]
As part of Grafana’s plugin program, we have a commercial relationship with Microsoft to maintain the Azure Monitor plugin. Currently, those discussions are held up and Microsoft has asked us to hold on providing maintenance and support. If you'd like this to be fixed asap, please convey your needs to Microsoft.
