### ISSUE TITLE
(transformations) Joining two tables doesn't allow you to select both right and left side fields

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#56424]
**What happened**:

I want to join two tables (two different queries) together with transformations. I tried to use the "join by field" but that only works if both tables have the field with the same name and type.

**What you expected to happen**:

I want to be able to select both the left and right side fields of the join. e.g. `WHERE a.field = b.other_field`.

**How to reproduce it (as minimally and precisely as possible)**:

* Get some table data (i was using github datasource, for tag data)
* Get some other table data (i was using github datasource, for release data)
* try to join those tables together with the transformations

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.x
- Data source type & version: any with tabular data
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by bnnlukas** [comment]
Any updates on this problem?
