### ISSUE TITLE
Panels with DataSource "-- Dashboard --" don't refresh on variable change

### ISSUE THREAD

**Issue by florentscle** [grafana/grafana#56445]
**What happened**:
I have a table panel with a MySQL query, using a variable.
In the same dashboard, I have another panel, using DataSource : "-- Dashboard --".
When I change the value of the variable, the table panel refresh, but the other don't.

**What you expected to happen**:
I want the second panel to also refresh when the datas of it's referenced panel change.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: MySQL 5.0.0
- OS Grafana is installed on: linux debian 10
- User OS & Browser: Windows 10 / Firefox 105.0.1
- Grafana plugins:
- Others:

**Comment by gelicia** [comment]
@florentscle What type of panel is the one that is not refreshing?

**Comment by florentscle** [comment]
It's a Stat panel

**Comment by lpskdl** [comment]
Hi @florentscle ,

Would you be able to replicate it in play.grafana.com? I did try the scenario but could not be able to reproduce it.

[sample play grafana dashboard i created](https://play.grafana.org/d/r_TvUNIVk/panel-dont-refresh-on-variable-change?orgId=1&var-var1=tan)



https://user-images.githubusercontent.com/108552997/195540608-590ec105-93cd-4f20-ac84-f7bb9fccc050.mov

**Comment by florentscle** [comment]
I've modified your sample panel like the mine is.
But I can't reproduce neither.
The differences are : your play server is 9.2.0, I'm 9.1.6.
And my source is not MySQL like I've wrote but MS SQL.
Have you a MS SQL source for verifying this point ?
I haven't found trace of this pb resolution between our 2 versions.
I'll try to upgrade as soon as possible to check.

**Comment by lpskdl** [comment]
alright I thought it is on My SQL as what you had written in the description. I will give that a try on MS SQL

**Comment by florentscle** [comment]
I've updated on 9.2.0, the problem isn't resolved

**Comment by lpskdl** [comment]
Thanks @florentscle, It could be specific to the mssqldatasource. I'm having issue running mssql on my m1 machine. I will keep you posted on any updates.

**Comment by oscarkilhed** [comment]
Was not able to reproduce this. Seems to work as expected.
![testvariablenotupdating](https://user-images.githubusercontent.com/468940/222732347-75da7f26-d050-4f78-a08c-7df8ede025a8.gif)
