### ISSUE TITLE
Applying search filter on alert rules only show the rule in pending or alerting state

### ISSUE THREAD

**Issue by hussain-ujjaini** [grafana/grafana#56454]
**What happened**: Search filter on alert rules only show the rule in pending or alerting state

**What you expected to happen**: Applying filter should show alert rule in any state (normal, pending or alerting)

**How to reproduce it (as minimally and precisely as possible)**: Go in alert-rules > try to filter any alert by alertname

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: safari, Firefox
- Grafana plugins:
- Others:

**Comment by svzhl** [comment]
Reproduced on version 9.2.1

**Comment by VikaCep** [comment]
Not being able to reproduce in 9.4.0

![2023-02-07 10 10 53](https://user-images.githubusercontent.com/6271380/217254098-a948699d-f15f-4db9-9ad0-b23a21ae207f.gif)

**Comment by VikaCep** [comment]
Closing as can't reproduce it. Please reopen otherwise.

**Comment by hussain-ujjaini** [comment]
Thanks
