### ISSUE TITLE
"undefined is not an object" in Safari when opening query editor

### ISSUE THREAD

**Issue by atombender** [grafana/grafana#5645]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.
- What datasource are you using? Prometheus.
- What OS are you running grafana on? Official Docker image `grafana/grafana:3.1.0`.
- What did you do? Entered a simple query, e.g. `probe_sucess{namespace=~"$namespace"}` and set the template variable to _All_.
- What was the expected result? Editor should render when I do "Edit" on the graph.
- What happened instead? Shows a buggy UI in the "Metrics" tab (scrambled, none of the buttons work), and the following output to the console:

```
Error: undefined is not an object (evaluating 'a.replace')
k
_a@https://example.com/public/app/boot.8ba215a1.js:41:28256
interpolateQueryExpr
formatValue@https://example.com/public/app/boot.8ba215a1.js:10:31561
https://example.com/public/app/boot.8ba215a1.js:11:887
replace@[native code]
apply@[native code]
call@[native code]
call@[native code]
Call@https://example.com/public/app/boot.8ba215a1.js:4:4095
https://example.com/public/app/boot.8ba215a1.js:4:7462
apply@[native code]
call@[native code]
call@[native code]
Call@https://example.com/public/app/boot.8ba215a1.js:4:4095
ja@https://example.com/public/app/boot.8ba215a1.js:4:7639
replace@https://example.com/public/app/boot.8ba215a1.js:11:606
updateLink
d
g@https://example.com/public/app/boot.8ba215a1.js:35:3779
https://example.com/public/app/boot.8ba215a1.js:35:29005
o@https://example.com/public/app/boot.8ba215a1.js:35:16302
https://example.com/public/app/boot.8ba215a1.js:35:22086
h@https://example.com/public/app/boot.8ba215a1.js:36:18233
https://example.com/public/app/boot.8ba215a1.js:36:18405
$eval@https://example.com/public/app/boot.8ba215a1.js:36:25921
$digest@https://example.com/public/app/boot.8ba215a1.js:36:24434
https://example.com/public/app/boot.8ba215a1.js:36:26015
e@https://example.com/public/app/boot.8ba215a1.js:35:5644
https://example.com/public/app/boot.8ba215a1.js:35:7097
```

Screenshot:

![screen shot 2016-07-24 at 14 11 21](https://cloud.githubusercontent.com/assets/50314/17085565/8eb45e12-51a9-11e6-87b7-a27feaa76042.png)

**Comment by atombender** [comment]
Downgraded to 3.0, can confirm that it's working there.

**Comment by atombender** [comment]
I spoke too hastily. Happening in 3.0, too. However, I found what triggers it: If I select _All_ from a template variable. It does not happen otherwise. Will edit description.

**Comment by atombender** [comment]
As another data point: If I set _Custom blank value_ in the template to `.*`, it works.

**Comment by torkelo** [comment]
what safari version?

**Comment by atombender** [comment]
Latest. Safari 9.1.2 (11601.7.7) on OS X 10.11.6.
