### ISSUE TITLE
LogQL Query: Impossible to edit the query on Explore view

### ISSUE THREAD

**Issue by vlad-diachenko** [grafana/grafana#56463]
**What happened**:
When the stream selector is entered, it's impossible to edit the query. the caret is always moving. Also, when I delete the whole query, I see the placeholder `Enter a Loki query (run with Shift+Enter)` but when I start typing, my text is concatenated with this placeholder and displayed in input.

**What you expected to happen**:
I expected to be able to remove the whole query and enter whatever I want ;) 

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/82767850/194305466-8b49f221-e519-4cb8-9cb5-2fd937730bd4.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.2 (3c13120cde)
- Data source type & version: Loki (Loki Plugin v5.0.0)
- OS Grafana is installed on: Docker Compose
- User OS & Browser: MacOS (12.6 (21G115))  + Google Chrome (Version 105.0.5195.125 (Official Build) (x86_64))
- Grafana plugins: Loki Plugin v5.0.0
- Others:

**Comment by vlad-diachenko** [comment]
Looks like this issue is fixed in: `grafana/grafana:9.2.0-beta1`

**Comment by gelicia** [comment]
Closed as duplicate #55137

**Comment by zhamdoctor** [comment]
> 

nope,image: grafana/grafana:9.0.5,i cannt edit it using code style either.
![Uploading image.png…]()

**Comment by zhamdoctor** [comment]
> Closed as duplicate #54535
> 
> This was fixed in 9.1, 9.0, 8.5, and 7.5.

![image](https://user-images.githubusercontent.com/29030455/195278507-a14bc4dd-57ad-4733-90bb-9d8693c3f564.png)
