### ISSUE TITLE
Loki: History autocomplete in query field does not work

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#56465]
**What happened**:

In Loki query field, we are supposed to show passed queries in autocomplete option, but history is always empty array, therefore never shown. 

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/30407135/194311897-3510d60e-73da-4b91-81fe-aa2bfb47ad2b.png">

**What you expected to happen**:

See history items is Loki query field.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Loki data source
2. Go to Explore
3. Choose code mode
4. Write some query
5. Delete the query
6. Start to write the same query

Past query should be suggested

**Anything else we need to know?**:

**Environment**:
- Grafana version: pre-9.3 (but this has been happening for a while)
- Data source type & version: Loki

**Comment by ivanahuckova** [comment]
Discovered during reviewing https://github.com/grafana/grafana/pull/55391

**Comment by matyax** [comment]
Should we move this to Q3 or Q4?

**Comment by ivanahuckova** [comment]
No need to, this is a small bug and I have fix ready. I was just waiting for https://github.com/grafana/grafana/pull/57192 to be merged, so we implement the fix for used editors.
