### ISSUE TITLE
Dashboard admins can't see users permissions in that dashboard

### ISSUE THREAD

**Issue by vtorosyan** [grafana/grafana#56462]
**What happened**:

A dashboard administrator was able to see user permissions on that dashboard before Grafana 9.x. With Grafana >=9.x as a dashboard Admin, I can't see and list users permissions on that dashboard anymore.

**Environment**:
- Grafana version: 9.x

**Comment by murtazaqa** [comment]
This is applicable for listing "teams" level permission as well. Folder/Dashboard admin cannot see list of teams in permission list unless they are part of the team.
