### ISSUE TITLE
[feature request] Batch processing in frontend snapshot sharing

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#5647]
Hi since problem in https://github.com/grafana/grafana/issues/5639 is understandable I would like to ask for a new feature - batch processing in frontend snapshot sharing:
- over one or more template variables (with possibility to use "all" or selected values)
- output of the list of template variables values + URL of snapshot into edit item or file
- nice to have would be possibility to use variables values in snapshot name

Our use case is daily snapshot for ~80 customers.

Many thanks
Josef

**Comment by torkelo** [comment]
this will likely never be implemented, I would recommend you use phantomjs to automate the creation of snapshots
