### ISSUE TITLE
Incoherence between case sensitive UID and case insensitive MySQL column

### ISSUE THREAD

**Issue by Qmeriaux** [grafana/grafana#56471]
**What happened**: 
Issue while migration from Grafana 8 to Grafana 9, 'failed to migrate permissions: failed to bulk-create roles: Error 1062: Duplicate entry \'GyC0Y1GVz\' for key \'UQE_role_uid\'.

**What you expected to happen**: 
Migration successful.

**How to reproduce it (as minimally and precisely as possible)**: 
Try to set up a MySQL database working with Grafana 8.1.6 with around 50K users, 20k dashboards, 4k orgs. Run migration to Grafana 9.x.x (tried with 9.1.6 and 9.0.0, behave same).

**Anything else we need to know?**:
While migrating data from Grafana 8 to Grafana 9, migration script generate UID to insert into role table. We faced an error during migration, "duplicate entry 'G**y**C0Y1GVz'". We noticed that the entry 'G**Y**C0Y1GVz' was already existing, and that was the cause of the bug. The UID is generated **case sensitive** (A-Z, a-z, 0-9, and - and _). However, the MySQL migration script enforce tables to be **case insensitive** ("utf8mb4_unicode_ci"). It should rather be configured as case sensitive (for example collation "utf8mb4_0900_as_cs"). 
Editing collation in mysql_dialect.go could possibly resolve this bug.

**Environment**:
- Grafana version: from 8.1.6 to 9.1.6
- Data source type & version: MySQL 8.0

**Comment by Jguer** [comment]
Hey @Qmeriaux , can you try the latest 9.2.x? 
It should contain https://github.com/grafana/grafana/pull/56620 which should prevent some of these collisions. 

Your main point of case insensitive collation being unduly applied on short UIDs is still valid
