### ISSUE TITLE
Grafana is trying to connect to Loki gateway in singleBinary Loki

### ISSUE THREAD

**Issue by balonik** [grafana/grafana#56498]
**What happened**:
Running Grafana + Loki. Loki runs in singleBinary mode.
Deployed using `kube-prometheus-stack` Helm Chart.
Datasource in Grafana is configured to `http://loki.loki:3100/`

**What you expected to happen**:
No errors in Grafana logs like

```
"failed to connect to ws://loki-gateway.loki.svc.cluster.local/loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-7j844%22%7D with err dial tcp: lookup loki-gateway.loki.svc.cluster.local on 10.43.0.10:53: no such host"
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Running Grafana + Loki. Loki runs in singleBinary mode. Watch Grafana logs.

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/grafana:9.1.6
- Data source type & version: Loki
- OS Grafana is installed on: k8s
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by gelicia** [comment]
@balonik should this be an issue for the helm chart not configuring the loki/grafana connection correctly? That repo would be at https://github.com/prometheus-community/helm-charts

**Comment by balonik** [comment]
Sorry, I forgot to mention that the datasource and queries work fine. I can query Loki and get results. That functionality works as expected. This error just appears randomly in Grafana log.

**Comment by gelicia** [comment]
If you do a search in your grafana config for loki-gateway.loki.svc.cluster.local do you see anything? I'm wondering if something is pre configured with that URL but your url is the loki.loki one instead.

**Comment by balonik** [comment]
If I look into `grafana.example.com/admin/settings` there is no such thing.

**Comment by balonik** [comment]
I am really sorry for your time. The log entries are actually not coming from Grafana pod.
