### ISSUE TITLE
[Feature request] Client certificate support for datasources

### ISSUE THREAD

**Issue by blaubaer** [grafana/grafana#5650]
If a ElasticSearch (or Prometheus, ...) endpoint is secured by certificates it should be possible to access it using a client certificate. This should work together with `proxy` access (This should already works if we use `direct` connections - because it uses the certificate of my browser.)

Please include this information:
- What Grafana version are you using? 3.1.0
- What datasource are you using? ElasticSearch, Prometheus, ...
- What OS are you running grafana on? Linux
- What did you do? Query data from a server/client certificate secured ElasticSearch instances.

**Comment by bergquist** [comment]
This has been fixed in 4.6
