### ISSUE TITLE
Possible bug: missing data points in InfluxDB (collectd) cause graphs not to be displayed

### ISSUE THREAD

**Issue by michalrus** [grafana/grafana#5651]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- Grafana: 2.6.0
- Data source: InfluxDB (data from collectd)
- OS: NixOS 16.03.659.011ea84 (Emu)

I’ve defined a `<Plugin ping/>` data source in collectd. It pings some hosts and reports RTT, stdev and drop rate. This data is sent to InfluxDB using their `collectd` frontend. So far, so good.

Now, when a host dies, drop rate rises to 100% (expected), but **no** round-trip times are added (expected, too).

When I’m trying to view a time range where a host was dead in Grafana, I’m getting:

```
InfluxDB Error: a.data is undefined
```

Viewing range when no datapoints are missing works perfectly.

Screenshot:

![influxdb-collectd-graphana-missing-points-error](http://i.imgur.com/dVLXoSJ.png)

**Comment by torkelo** [comment]
whats the response from InfluxDB from your query? (open chrome dev tools network tab to inspect)

**Comment by michalrus** [comment]
@torkelo, you’re right!

```
json: error calling MarshalJSON for type httpd.Response: json:
error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN
```

What should I do now, then?

**Comment by torkelo** [comment]
@michalrus maybe open a InfluxDB bug report with the influxdb project, ask in influxdb mailing list

**Comment by michalrus** [comment]
@torkelo, okay, thank you, solved!

In case anyone experieces the same problem:

1. It’s caused by collectd plugin accepting NaNs into InfluxDB store, and these cannot be handled yet → https://github.com/influxdata/influxdb/issues/4089
1. Solve this permanently by updating your InfluxDB, as newer versions ignore NaNs → https://github.com/influxdata/influxdb/issues/3994#issuecomment-182024994
1. Alternative quick fix would be to add `WHERE "value" >= 0` or something similar, that would filter out NaNs. Downside: you cannot edit such queries in graphical mode in Grafana (at least not in 2.6.0).
