### ISSUE TITLE
Grafana Panel with blank Title (Panel Options) > Filters in table header ca'nt be clicked / edit dialog appears

### ISSUE THREAD

**Issue by paulfirstimpression** [grafana/grafana#56526]
**Grafana Panel with blank Title (Panel Options) > Filters in table header ca'nt be clicked / edit dialog appears**:

**What you expected to happen**:
As in previous versions, only clicking the 'v' arrow made the edit dialog to appear, so you can use the filters.
Now if you press anywhere in the panel header (without title, so one row less height), it will make the edit dialog to appear.

**How to reproduce it (as minimally and precisely as possible)**:
I've had this issue in 9.1.5-9.1.7. 
- Add a table panel to your dashboard
- Under Panel Options, leave Title empty
- Table > Show table header eabled
- Table > Column Filter > Enabled
- Apply and use your dashboard
- Try to click a filter in the header of your table, it will make the edit dialog to appear over the entire width, instead of only for the 'v' arrow.

**Environment**:
- Grafana version: tested on 9.1.5-9.1.7, in older versions (9.0?) things were ok

![panel - no title - filter not accessable](https://user-images.githubusercontent.com/65596790/194499409-ec65517c-0047-4a38-b72a-600a1c874b58.png)

- Windows 10/11
- Chrome 105

**Comment by gelicia** [comment]
Thank you for the detailed steps! I was able to replicate this. 

<img width="716" alt="Screen Shot 2022-10-07 at 7 54 09 AM" src="https://user-images.githubusercontent.com/1533128/194558583-0859ec78-0085-4823-80ca-c1ae04ed97cd.png">

**Comment by natellium** [comment]
Hey there, this will be solved by the new panel Chrome implementation(see https://github.com/grafana/grafana/issues/63093). It's currently in beta behind `newPanelChromeUI ` and we're aiming to release it by default in 9.5.
