### ISSUE TITLE
[Bug] Moving average / pipeline aggs missing in elasticsearch query 

### ISSUE THREAD

**Issue by vaibhavinbayarea** [grafana/grafana#5654]
Please include this information:
- What Grafana version are you using?

>> Version 3.1.0 (commit: v3.1.0)
>> Version 4.0.0-pre1 (commit: v3.1.0+113-g3f861dd-dirty)

- What datasource are you using?

>> Elasticsearch

- What OS are you running grafana on?

>> Ubuntu 14.04

- What did you do?

>> Trying to plot moving average of a metric. Cant find the option in the UI query editor. Only see Extended stats.
 
- What was the expected result?
 
>> Should see moving average option as seen in the pic here:
![](https://cloud.githubusercontent.com/assets/10999/11743096/0d9d696e-a005-11e5-892e-dee5a9327c42.png)

Apologies if this is really stupid but I have already clicked around and cant seem to find it.

**Comment by torkelo** [comment]
You need to specify elasticsearch version om the grafana data source options page

**Comment by vaibhavinbayarea** [comment]
Works! Thanks!
