### ISSUE TITLE
Can't assign LDAP user to organization

### ISSUE THREAD

**Issue by dauchua** [grafana/grafana#5656]
Hi all,, 
Im running grafana 3.0.1 from image grafana/grafana:3.0.1 on catalog of rancher. 

With normal signup user, i can assign that user to any orgs. With Ldap user, i can assign that user in Admin > Users and it's popup success : 
![image](https://cloud.githubusercontent.com/assets/9334607/17125204/b3e5ccc0-531b-11e6-8f85-4d025a8c6e80.png)

 But when i'm logging  in that account :
![image](https://cloud.githubusercontent.com/assets/9334607/17125246/03c94136-531c-11e6-8836-f78013dde1c9.png)
They dont show any orgs.

And when i return to admin : 
![image](https://cloud.githubusercontent.com/assets/9334607/17125264/2aa227be-531c-11e6-9bf1-0c6105ef5bca.png)

User has unassigned. Could you tell me how to fix this :) Reply if you need any further information

**Comment by torkelo** [comment]
currently LDAP users must map what organization they belong to via LDAP config
http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync

**Comment by bastianvs** [comment]
Can we change this to local? Is there a way if i only need ldap to login not to map the org. Incase i need to map locally
