### ISSUE TITLE
[Feature request] Support dashboard inheritance

### ISSUE THREAD

**Issue by abadyan-vonage** [grafana/grafana#5657]
It would be cool if we were able to create once a common set of graphs inside a dashboard (or a template, call it what you will) and then use that in several dashboards geared for different purposes.
Currently our choice is to either clone the dashboard and remember to maintain multiple locations or have many unrelated graphs in one dashboard to avoid duplication.

**Comment by FUSAKLA** [comment]
This is exactly the problem we are facing right now.

Bit terrible solution I'm using as workaround is to create one HTML panel in which i include all iframes of `parent dashboard`, position them, some JS to pass template variables
and then including this HTML panel of iframes in `child dashboard` in another HTML

so thats dashboard with HTML panel  with iframe of HTML panel with iframes of graphs of parent dashboard... horrible solution


We have standardized set of metrics for all applications so we have `default dashboard` but every application may have other custom metrics so they need to add some panels.

But number of these inherited dashboards will go to more than 20 so if there is need to edit the default graphs. It's almost impossible to do it one by one.

**Comment by FUSAKLA** [comment]
I spent some time on this today and got some workaround

I create one `default` dashboard which i want to include in every inherited dashboard
Than i create second `app` dashboard which has some additional graphs i would like to have under the default dashboard

To concatenate these two dashboards i use scripted dashboard which requests API for JSON of both dashboards. Than gets all rows from the `default` dashboard and prepends them to the rows of `app` dashboard. (there is one problem with panel ID collision but i solved it by counting panels of `default` and adding this number to every panel ID of `app` dashboard )

Then a made `home` dashboard which have links to these scripted dashboards.

There is risk that if you use some template values in `default` which are not supplied by the `app` dashboard than data wont be loaded offcourse.

If this helps somebody you can just paste this to 
`/usr/share/grafana/public/dashboards/dashboard-concat.js` 
and than call 
`http://foo.bar/dashboard/script/dashboard-concat.js?app_dashboard_slug=<dashboard_slug>&default_dashboard_slug=<dashboard_slug>`

the source code of the scripted dashboard is here:
```
// accessible variables in this scope
var window, document, ARGS, $, jQuery, moment, kbn;

var app_dashboard_slug = "",
    default_dashboard_slug = "",
    grafana_url = "/api/dashboards/db/",
    default_dashboard_json = {},
    app_dashboard_json = {},
    contacenated_rows = [],
    dashboard = {},
    return_callback = null;

if(!_.isUndefined(ARGS.app_dashboard_slug)) {
  app_dashboard_slug = ARGS.app_dashboard_slug;
};

if(!_.isUndefined(ARGS.default_dashboard_slug)) {
  default_dashboard_slug = ARGS.default_dashboard_slug;
};

function getDashboardDefenition(dashboard_slug){
  return $.ajax({
      method: 'GET',
      url: grafana_url + dashboard_slug
   });
};

function countDashboardPanels(dashboard){
  var i = 0,
      panel_count = 0;
  for (i = 0; i < dashboard.rows.length; ++i) {
    panel_count += dashboard.rows[i].panels.length
  }
  return panel_count;
}

function shiftDashboardPanelsIds(shift, dashboard){
  var i = 0,
      j = 0;
  for (i = 0; i < dashboard.rows.length; ++i) {
    var row = dashboard.rows[i];
    for (j = 0; j < row.panels.length; ++j) {
        row.panels[j].id += shift;
    }
  }
}


function mergeDashboards(app_data, default_data){
  panel_id_shift = 0;
  app_dashboard_json = app_data[0].dashboard;
  default_dashboard_json = default_data[0].dashboard;
  
  // We need to add max ID of panel from Default to all panel IDs in app dashboard to avoid colisions
  panel_id_shift = countDashboardPanels(default_dashboard_json);
  shiftDashboardPanelsIds(panel_id_shift, app_dashboard_json);

  contacenated_rows = default_dashboard_json.rows.concat(app_dashboard_json.rows);
  app_dashboard_json.rows = contacenated_rows;
  dashboard = app_dashboard_json;
  return_callback(dashboard);
};

function logError(r1, r2){
  console.log("ERROR:");
  console.log("serponse1:");
  console.log(r1);
  console.log("serponse2:");
  console.log(r2);
};

return function(callcack) {
  return_callback = callcack;
  $.when(getDashboardDefenition(app_dashboard_slug), getDashboardDefenition(default_dashboard_slug)).then(mergeDashboards, logError);
};
```

**Comment by FUSAKLA** [comment]
If you want to use playlist for these scripted dashboards you can use this simple snippet
https://gist.github.com/czerasz/569ed1f923b610efba91375eeb35d5ab

**Comment by torkelo** [comment]
closing as it's duplicate (or similar to), https://github.com/grafana/grafana/issues/1803
