### ISSUE TITLE
Legacy Send Reminders notification channel settings not preserved in Grafana Alerting migration

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#56578]
**What happened**:

I had a legacy alerting setup with several notification channels that have customized 'Send Reminders' settings to re-send notifications every x minutes/hours. Upon migrating to Grafana Alerting, the migration created a set of notification policies (one for each legacy alert rule), and a set of contact points (one for each legacy notification channel).

In the migrated setup, there is a default root policy with a 'Repeat interval' setting of 4 hours, and none of the migrated notification policies contain any 'Repeat interval' overrides.

**What you expected to happen**:

I expected the 'Send reminders' settings previously configured on notification channels to be preserved within the 'Repeat interval' setting of the migrated notification policies.

Additionally, I did not expect a 4-hour Repeat interval to be globally applied across all migrated notification policies where no Send reminders setting was previously configured.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a legacy alerting notification channel with a customized 'Send Reminders' setting
- Migrate to Grafana Alerting
- Note the customized setting is not migrated, and is replaced with a global default 4-hour Repeat interval setting.

**Environment**:
- Grafana version: [v9.2.0-beta1 (9e0bb05d90)](https://grafana.com/docs/grafana/next/release-notes/release-notes-9-2-0-beta1/)
- OS Grafana is installed on: ubuntu (from docker image `grafana/grafana-oss:9.2.0-beta1-ubuntu`)

**Comment by santihernandezc** [comment]
Sounds like a good idea, and we're planning to do this.
It's not possible to implement this right now, but there's a [PR](https://github.com/grafana/grafana/pull/52071) on the way that should allow us to work on this.
