### ISSUE TITLE
Enable Unified Alerting screenshots capture by default

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#56572]
**What happened**:

After migrating from legacy to Unified Alerting, notification screenshots were no longer working despite having the image rendering plugin installed. I had to manually re-enable screenshots by setting an additional config option `unified_alerting.screenshots.capture = true`. This is [well-documented](https://grafana.com/docs/grafana/v9.0/alerting/images-in-notifications/#configuration), but is nonetheless inconvenient, as it adds an extra manual step (and additional server restart) to the alerting upgrade process.

**What you expected to happen**:

Ideally, migrating from legacy to Unified Alerting should preserve notification screenshots without requiring additional manual changes to the global configuration. Although the screenshot setting is no longer toggled per contact point, I imagine that installing the image rendering plugin in the first place should be enough of a signal that notification screenshots are desired, so I think changing the default of `unified_alerting.screenshots.capture` to `true` would be appropriate.

**Comment by grobinson-grafana** [comment]
Hi! :wave: Thanks for opening an issue! I appreciate that it's an inconvenient when upgrading, however as Grafana 9 uses file based configuration for images in notifications we did not think the migration should be changing configuration files on disk. Likewise, in Grafana 9 screenshots are either enabled or disabled for all contact points while in old alerting it was enabled or disabled for individual contact points (notifiers), and this makes it difficult to decide what configuration to use if some contact points (notifiers) have screenshots enabled and others have them disabled.

**Comment by grobinson-grafana** [comment]
Hi! 👋 Thanks for opening this issue! I appreciate that it's an inconvenience when upgrading, however as Grafana 9 uses file based configuration for images in notifications we did not think the migration should be changing configuration files on disk. 

Likewise, in Grafana 9 screenshots are either enabled or disabled for all contact points while in old alerting it was enabled or disabled for individual contact points (notifiers), and this makes it difficult to decide what configuration to use if some contact points (notifiers) have screenshots enabled and others have them disabled.
