### ISSUE TITLE
Deduplicate migrated notification policies

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#56582]
As a followup to #45443, I'd like to re-raise one specific item that wasn't addressed upon closing that issue, the first caveat mentioned in https://github.com/grafana/grafana/issues/45443#issuecomment-1088148604:

> I didn't tackle the matching label on notification policy using a random rule_uid. I agree that this isn't optimal, it's difficult to see at a glance which alert each policy is supposed to reference. That being said, I can't think of a simple solution that doesn't have major drawbacks. For example, I could instead match using the rule title but this value isn't guaranteed to be unique and furthermore if the alert title is changed it should (correctly but silently) break the association. IMO, this behaviour is not intuitive for a migrated alert (especially for someone migrated to unified alerting for the first time). If you have thoughts here, I'm all ears!

The one-to-one mapping of notification policy to alert rule using a random `rule_uid` adds an extra layer of confusion to users performing the alerting migration (ie, what exactly is the `rule_uid` label? do newly-added rules need a similar `rule_uid` label? Why is the UI redundantly displaying the `rule_uid` redundant label when it's already the internal identifier?). It also leaves the migrated setup in a rather unmaintainable state. (For example, deleting a migrated alert rule doesn't delete the corresponding notification policy - #56053)

One alternate solution would be to attach `contact_point_[id|slug]=true` labels to migrated alerts, linking an alert rule to any number of contact points, and one migrated notification policy per contact point matching against the label and linking the contact point. (This would also provide a place to more cleanly migrate the 'Send Reminders' settings from a legacy notification channel to a 'Repeat interval' setting on the migrated notification policy; see #56578.)

Whatever the ideal solution, this issue represents a significant pain point in the current migration process. If the current process is in fact the best we can do, I'd like to see additional documentation in the upgrade guide explaining these additional generated resources and how one might reasonably maintain them moving forward, since it currently leaves a confusing mess of notification policies with no clear guidance on how to proceed.

**Comment by gelicia** [comment]
Looking at the description and the linked PR, this seems to be a known limitation with alerting migration and not necessarily a bug. I'm assigning this to the correct team to help ascertain if there is a coding solution here or if, like you said, more thorough documentation on the migration progress is the best we can do to help mitigate some of the confusion

**Comment by wjordan** [comment]
For a visual illustration of this issue, here's what a just-migrated set of notification policies looks like in the UI (one per alert rule), it's effectively unusable if you have more than a small handful of alert rules:
![image](https://user-images.githubusercontent.com/56541/194677231-b00e3cd2-43d8-4c6f-921e-d78c272cd567.png)

**Comment by santihernandezc** [comment]
[This PR](https://github.com/grafana/grafana/pull/52071) reduces the number of notification policies being created. Instead of creating one per alert rule, we now create one per contact point. This should fix the issue you describe.
