### ISSUE TITLE
plugin development: load plugins error

### ISSUE THREAD

**Issue by fengfirst** [grafana/grafana#5658]
resolve plugin development

Grafana3.1.0
CentOS release 6.7 

I want to develop a datasource plugin
follow step:
**1. install grafana**
    from http://docs.grafana.org/project/building_from_source/
**2. clone simple-json-datasource**
[..grafana]$ cd grafana/public/app/plugins/datasource/
[..grafana]$ git clone https://github.com/grafana/simple-json-datasource.git
**3. start server**
[..grafana]$ grunt --force
[..grafana]$ bin/grafana-server

Plugin Error
Error: XHR error (404 Not Found) loading http://.../public/app/plugins/datasource/grafana-simple-json-datasource/module.js?bust=1459496168101 Error loading http://.../public/app/plugins/datasource/grafana-simple-json-datasource/module.js

![error](https://cloud.githubusercontent.com/assets/1661545/17131018/f57de4e2-534d-11e6-8a39-828a94364223.png)

**Comment by torkelo** [comment]
plugins should be in the plugins dir specified in you config file (for installs running the official packages this is default `/var/lib/grafana/plugins`  but if you and build grafana from local source in dev mode it might also default to `<working dir>/data/plugins`
