### ISSUE TITLE
about Building Grafana from source

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5659]
i wanna building grafana at local,and i read the doc of Building Grafana from source.
at first  i install node.js and go ,use go version and node --version command  it show the version :go 1.5 and node.js  is v6.3.1,and  and i never konw go before, so ,i follow the doc，however，it had golang issuse, and i upate go for the latest version , and it worked ,but when i execute the npm install command ,it also has errors as below: looks like phantomjs  have no installed, so  can the doc more  detailed .if any greenhand can do it as follow the doc

npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/usr/local/nodejs/node/bin/node" "/usr/local/nodejs/node/bin/npm" "install" "phantomjs"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/golang/grafana/src/github.com/grafana/grafana/npm-debug.log

**Comment by torkelo** [comment]
strange, it's not failing on the build server using node 5.11

**Comment by tonyC2016** [comment]
maybe the network ,there is some file cant be download ,like as below
import "golang.org/x/oauth2": https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.58.221.241:443: i/o timeout
package golang.org/x/oauth2: unrecognized import path "golang.org/x/oauth2"
,so i  download those files by myself ,and put them in _workspace ,but i doest work too

**Comment by tonyC2016** [comment]
i down the source from github in a zip way ,and when i execute go run build.go setup  its error like 
import cycle not allowed

**Comment by torkelo** [comment]
just download a nightly build of 4.0-pre1 http://grafana.org/download/builds.html

**Comment by tonyC2016** [comment]
there is no click for download  button

**Comment by torkelo** [comment]
? there are download links

**Comment by tonyC2016** [comment]
@torkelo  the download links is disabled

**Comment by tonyC2016** [comment]
![image](https://cloud.githubusercontent.com/assets/18416187/17167472/fe43a5cc-540f-11e6-8140-a0fb5e20bf8e.png)

**Comment by torkelo** [comment]
strange, have you disabled javascript?
![image](https://cloud.githubusercontent.com/assets/10999/17167544/f62cc620-53dd-11e6-9df1-33e387533ab0.png)


https://grafanarel.s3.amazonaws.com/builds/grafana-4.0.0-1469547136pre1.x86_64.rpm

**Comment by tonyC2016** [comment]
@torkelo  thank u

**Comment by tonyC2016** [comment]
@torkelo  hi , i try build again ,and use npm taobao.org，and i can npm install sucess ,but when i excute grunt ,process out of memory errors  ,like as below
![image](https://cloud.githubusercontent.com/assets/18416187/17236752/d430e758-557d-11e6-9c7a-b6adb6e0359a.png)

**Comment by tonyC2016** [comment]
anyone met the same problem?

**Comment by onlyyn** [comment]
i have the same problem if i use taobao.org ,  fix it if i use npm
