### ISSUE TITLE
Support absolute values for singlestat thresholds

### ISSUE THREAD

**Issue by marcelocarlos** [grafana/grafana#5660]
The singlestat panel is great and the support for thresholds makes everything even better. However, the threshold options are a bit limited.

For example, I have a panel displaying NTP offset of a server and I'd like to make it go orange/yellow when the offset is over +/- 0.5s and red when over +/-1s. The problem is that I cannot define thresholds for both positive and negative values of a metric.

The direct approach to solve that would be supporting defining thresholds for both positive and negative values (e.g. -0.5,-1;0.5,1). Another option would be having the possibility of applying functions on the value before using the thresholds (e.g. a tickbox or dropdown with the option 'absolute values'). 

The second option seems a bit more generic and would cover additional scenarios, however, the first appears to be simpler to implement.

Thanks,
Marcelo

**Comment by gwuillou** [comment]
I have the same need for this feature . +1

**Comment by wols** [comment]
:+1:

**Comment by geckogecko** [comment]
:+1:

**Comment by sslupsky** [comment]
See issue #5234 for a work around.  The work around might be a problem for you since you require decimal precision but for others looking for a solution to the negative values problem where the values can be represented with integers, #5234 offers a solution.

**Comment by wols** [comment]
@sslupsky good hint!
But this is not yet the solution for the missung threshold - we need left **and** right from zero a warning and critical threshold, eg.
```
<-- RED --|-- YELLOW --|-- GREEN --|-- YELLOW --|-- RED -->
        -0.5s        -0.3s       +0.3         +0.5
```

**Comment by wols** [comment]
@marcelocarlos My current **visual only** usage
![grafana_singelstat_gauges](https://user-images.githubusercontent.com/764167/42422605-6fc3aba2-82e9-11e8-914e-9f62f4c669da.png)

![grafana_singelstat_settings](https://user-images.githubusercontent.com/764167/42422611-906cf0ac-82e9-11e8-8d77-ee78f2f0e932.png)

**Comment by torkelo** [comment]
should be fixed in new panels
