### ISSUE TITLE
0.0002847 is rendered as "a few seconds" in a table, when "seconds" is chosen

### ISSUE THREAD

**Issue by volter** [grafana/grafana#5661]
The problem was there in the 3.1.0 release and is still present in grafana_3.1.1-1469444398_amd64.deb (25th of July).

I would expect this to render as 0.2 ms or something meaningful, or at least 0, but not "a few seconds".

**Comment by torkelo** [comment]
the unit formats only upscale (so 60 is rendered as 1 min) etc, 

But this pr might change that if there is enough interest in this
https://github.com/grafana/grafana/pull/5642

**Comment by volter** [comment]
Hard to say! I could possibly multiply, if the datasource allows it, but that's not necessarily the case, I think.

"A few seconds" is wrong regardless.

**Comment by torkelo** [comment]
if you see that you are using the wrong format. Change to the seconds format. You must be using the duration format which is designed for very long time duration in (weeks, days, hours etc)

![image](https://cloud.githubusercontent.com/assets/10999/17136539/4f51e3c8-5336-11e6-8e8a-b594c98cd958.png)

**Comment by volter** [comment]
Oh, I hadn't noticed that! Thanks a lot!
