### ISSUE TITLE
panels with Dashboard DataSource cannot choose the folding Panel

### ISSUE THREAD

**Issue by loserbird** [grafana/grafana#56622]
**What happened**:
there is many panel in my dashbard. i fold some panel so that they don't send query when i open the dashboard.
and i have a panel using dashboard datasource and want to reuse the query result from another panel in the same dashboard, but i cannot choose the folding pannel. 

**What you expected to happen**:
i can choose the folding pannel to reuse query result. 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Grafana version: 9.1.6

**Comment by torkelo** [comment]
The panel needs to be in an expanded row for it to be available (and it needs to be expanded for the other panel to share it's data)

**Comment by loserbird** [comment]
> The panel needs to be in an expanded row for it to be available (and it needs to be expanded for the other panel to share it's data)

why is it designed this way? can it be achieved to choose the folded pannel?

**Comment by zuchka** [comment]
I'm guessing that would complicate the dashboard's ability to lazy-load panels. As you note in your original post, you too are putting panels in unexpanded rows partly so they don't all fire at once
