### ISSUE TITLE
[Bug] Repeat panel: Invalid GROUP BY time(1y) (InfluxDB)

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#5662]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Version     : 3.1.0
Release     : 1468321182

- What datasource are you using?
Influxdb, 0.13.0

- What OS are you running grafana on?
RHEL 6

- What did you do?
 - I want to see Error stats of all interfaces of a device, so I defined a table displaying all variables of a certain interface and tried to apply this per interface using a template variable $name
- The table displays aggregates of columns (To Table Transform: Time Series Aggregations)
 - Enable "Repeat panel" based on template variable (multi selection, singlestat)

- What was the expected result?
 - It displays the table panel for each element of the template variable

- What happened instead?
 - Original query (template variable $name):
```
SELECT max("in-discards") AS "in-discards", max("out-discards") AS "out-discards", max("in-errors") AS "in-errors", max("out-errors") AS "out-errors" FROM "SNMP Interface" WHERE "name" =~ /^$name$/ AND $timeFilter GROUP BY time($interval) fill(null)
```
 - Query sent to InfluxDB:
```
SELECT max("in-discards") AS "in-discards", max("out-discards") AS "out-discards", max("in-errors") AS "in-errors", max("out-errors") AS "out-errors" FROM "SNMP Interface" WHERE "name" =~ /^SOME_DEVICE-ae12$/ AND time > now() - 30d GROUP BY time(1y) fill(null)
```
 - Response:
```
{
  "error": "error parsing query: found y, expected ) at line 1, char 247",
  "message": "error parsing query: found y, expected ) at line 1, char 247"
}
```
 - Grafana somehow uses a GROUP BY time(1y). Even if I manually set the interval to some value, it keeps using 1y, which InfluxDB doesn't understand (It understands 365d or 52w)

**Comment by bbczeuz** [comment]
Workaround: Manually remove the time($interval) clause from the queries. But I think in that case, InfluxDB will send the raw (unaggregated) data to grafana or even the browser, which can be very inefficient

**Comment by torkelo** [comment]
this happens only when you repeat a panel and don't set the min span option (general tab)

I know this should min span should have default value, will fix.

**Comment by bbczeuz** [comment]
Confirmed. Setting a 'min span' fixes error.
But there's another problem: When changing the template value selection from "All" to just one, panels after the one selected are not removed, but the values from the current selected element are applied to all panels. Changing back to "All" adds more panels. Repeat.

**Comment by torkelo** [comment]
Strange cannot replicate that behavior, sure you are not mixing panel repeat with row repeat?

**Comment by damm** [comment]
Thanks for this issue; ran into it and set the min span and ... saved me a lot of work :)
