### ISSUE TITLE
Log file is created although log mode is set to syslog

### ISSUE THREAD

**Issue by kbabioch** [grafana/grafana#5663]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.0
- What OS are you running grafana on? Linux (Arch)
- What did you do? Changed log mode (`mode` in `[log]` section to `syslog`).
- What was the expected result? No log file is created under `/var/log/grafana`
- What happened instead? `/var/log/grafana/grafana.log` is created, although is stays empty and everything is written to syslog instead.

**Comment by torkelo** [comment]
This has been fixed in master already :) 
https://github.com/grafana/grafana/pull/5393

To work around this issue in 3.1 set log mode via command line
for example:
`cfg:default.log.mode=syslog`
