### ISSUE TITLE
Summing kBps should render a value in kB

### ISSUE THREAD

**Issue by michalrus** [grafana/grafana#5664]
* **I'm submitting a ...**
- [x] Feature request

- Grafana 3.1.0
- InfluxDB 0.13.0, collectd 5.5.1
- NixOS 16.09pre87412.e725c92 (Flounder)

When dealing with RX/TX counters of an interface, I’m using `derivative()` to get rates. This metric is in **kBps**. Now, when I select `[x] Total` in the Legend tab of the graph, the totals are reported in **kBps**, too.

The “total” of this chart (i.e. rate integrated wrt. time) is really of **kB** unit, not kBps. =)

**Comment by torkelo** [comment]
The total will almost never be accurate for rates anyway as  it is just the sum of all values returned  by your query, which probably has an average aggregation going on (or last value for derivative).

**Comment by michalrus** [comment]
Aahhh, you’re right. =) Thank you for the hint.
