### ISSUE TITLE
AzureAD: warn about misconfigured URL if oauth payload matches v1 payload

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#56667]
On first configuring azure oauth it's possible to mistake and configure oauth v1 endpoints instead of v2 endpoints.

**Definition of Done**

- [ ] Emit warning about v1 payload detected. "Azure v1 oauth payload detected. Grafana supports v2+, please review oauth endpoint configuration"

**Comment by gamab** [comment]
And that was 5 hours of my time :D
