### ISSUE TITLE
State timeline: consider truncating string values which exceed the segment length

### ISSUE THREAD

**Issue by gianluca-nitti** [grafana/grafana#56687]
In the state timeline panel, if the rendered string of an item is longer than the timeline segment it's associated with, it overflows in the neighbor segment(s).

![Screenshot from 2022-10-11 12-41-19](https://user-images.githubusercontent.com/15270303/195070383-ce83b5a6-91c7-40cc-aa2c-bc4079961828.png)

Screenshot from https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1&editPanel=63 after editing one of the strings.

Maybe it would look better to handle this cases by truncating the string and adding an ellipsis symbol `...`. When hovering with the mouse cursor, the tooltip (if enabled) would still show the full string.

**Comment by zuchka** [comment]
Thanks for creating this issue, @gianluca-nitti 

closing this in favor of this ongoing discussion. I invite you to read this thread and add your feelings:

https://github.com/grafana/grafana/discussions/38303

**Comment by leeoniya** [comment]
@zuchka i think that's a different issue. what's being shown here should be fixed by https://github.com/grafana/grafana/pull/56794
