### ISSUE TITLE
Bug in table/piechart plugins with ElasticSearch ?

### ISSUE THREAD

**Issue by solidz03** [grafana/grafana#5668]
Hello,

I meet an issue with Grafana. 

I collect NetFlow metrics with Logstash and I store this in ElasticSearch. I use Grafana to display informations about NetFlow metrics in ElasticSearch.

When I want to display source port and destination port in table plugin, I see "0" before ports (please refers to pictures). 

![1](https://cloud.githubusercontent.com/assets/20536224/17175605/b92b4e6a-5408-11e6-8b6b-791875e59b46.PNG)

![2](https://cloud.githubusercontent.com/assets/20536224/17175604/b91bb70c-5408-11e6-8b7a-1334dfb88ca5.PNG)

It's the same with Pie Chart plugin. 

It's strange because the field which contains the port's value in ElasticSearch it's correct :
__________________________
"netflow":{
     .....
     "l4_src_port":61785,
     "l4_dst_port":179,
     .....
}
__________________________

It's the same issue with the others fields.

Grafana version : 3.1.0-1468321182.x86_64

Thanks for help.

Regards,

solidz03

**Comment by torkelo** [comment]
The series name looks to be numeric and is matching the number column style. 

Add a string column style (BEFORE the numer column style) with alias / regex pattern `Metric`

**Comment by solidz03** [comment]
Thanks for your answer Torkel. It work when I change the field type (int to string).

Have a nice day !
