### ISSUE TITLE
Provide the ability to name / alias multi value fields

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#5669]
When querying influxdb with grafana using a template variable with multi enabled there doesn't seem to be any way to setup nice names for the legend.
```sql
SELECT mean("value") FROM /^$app.$metric.$count$/ WHERE $timeFilter GROUP BY time($interval) fill(null)
```
It should possible to get the individual names i.e. the value of $count for the legend.

This works if $count isn't multi but when it is you end up with all fields with the same name e.g. {total,increments,decrements} instead of each series having their individual names.

The closest I can find is $m but that's often long which makes the legend messy and hard to read and leads to truncated names making them useless in the hover over.

Supporting the same capture method as for templates based on the measurement would be a nice way to solve this.

**Comment by torkelo** [comment]
$count is should be a tag, then you can group by tag and use `$tag_count` in the alias field. 

since you use dots to separate your measurement name you can also use `$2` to only have the 3rd indexed node (splits metric name into nodes by dot)

**Comment by stevenh** [comment]
Unfortunately the dots are there to replace '_' which breaks as it things its part of the previous variable name so thats not an option.

Also tags aren't an option as these are statsd metrics in influx so there's only the metric nothing else :(

**Comment by torkelo** [comment]
Ok, then I recommend you switch to Graphite that have better naming / alias features
