### ISSUE TITLE
Dividing two elasticsearch metric series in grafana

### ISSUE THREAD

**Issue by phume** [grafana/grafana#5671]
HI all,

I am new to both ES and Grafana.

I am wondering if there is any divide function in grafana for elasticsearch.
I see that there is a divide for graphite ( https://github.com/grafana/grafana/issues/1295) but I can't find anything for elasticsearch.

Basically, I want to compare the number of problem (1 row in the database represent 1 problem) for each server to the average number of problem (row) in the SingleStat i.e. more than average => red or below average => green. It seems like there is no dynamic threshold (yet).
So I tried to bypass it by normalize the count by divide the `number of problem(row) of server A` by the `avg number of problem` which would require the divide function and average function.

Thank you for your awesome work :)

**Comment by torkelo** [comment]
Elasticsearch does not allow you to do operations on the result of queries (like Graphite can). 

But maybe in the future you will be able to do that via this feature
https://github.com/grafana/grafana/issues/3677
