### ISSUE TITLE
Add documentation for language selection

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#56717]
With Grafana 9.3, organization admins and users will be able to select their preferred language in Grafana.

We should document this on the following pages in the documentation: 
- [User preferences](https://grafana.com/docs/grafana/latest/administration/user-management/user-preferences/)
- [Org preferences](https://grafana.com/docs/grafana/latest/administration/organization-preferences/)

**Comment by zsofiakomaromigrafana** [comment]
Related: https://github.com/grafana/cloud-docs/issues/409

**Comment by chethan27** [comment]
Hi , can I work on this ?

**Comment by joshhunt** [comment]
Hey @chethan27 thanks for checking first!

You're more than welcome to take a stab at this if you would like! The changes to the Server/Org preferences, and User preferences documentation shouldn't be that involved, and should just mirror the other preference documentation that we have.

If you submit a PR, we might not get auto-tagged, so please tag myself (or request review from @grafana/user-essentials, if you can) so we can be across it 🙌🏻
