### ISSUE TITLE
Supporting plugin for Clouthealthtech App

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#5672]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request - https://apps.cloudhealthtech.com/ --- provides detailed charting on AWS / AZure etc... also they provide REST API to pull the chart data... but it could be fairly complex... Can we have someone look @ it and provide some guidance on how that can be envisioned in Grafana... do we need some kind of importer to graphite for this to work in grafana???
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
What is needed is a data source plugin that uses their API, for example 
https://grafana.net/plugins
