### ISSUE TITLE
[Feature Request] Support Import/Export of Datasources as JSON Files

### ISSUE THREAD

**Issue by ajsmith** [grafana/grafana#5674]
# Motivation

To be able to automate Grafana deployments and migrations, especially on Docker.
# Problem

The import/export mechanism in Grafana 3.1 allows you to parameterize the datasource, via the `__input` section of the JSON file. However, it's a still manual step to configure and select the datasource.
# Solution

Provide support for the import and export of datasources as JSON files. This should also support loading datasource JSON files from the filesystem. This could be configured as a `[datasources.json]`,  similar to the `[dashboards.json]` mechanism.
# Advantages
1. This would help facilitate Docker deployments, as automated container deployment becomes much simpler if all required configuration is available on the filesystem (as opposed to an interaction with the UI or the REST API, which requires somewhat complex interactions).
2. Exported datasource configuration files could be put in version control systems such as Git.

**Comment by maximecolin** [comment]
I'm very interesting by this features. I'm using a provisioning solution to automate Grafana installation and there is no simple way to add datasources programmatically.

**Comment by jpereira** [comment]
:+1:

**Comment by cwilldev** [comment]
Any updates or progress on this issue?

**Comment by BartVB** [comment]
This has been implemented in Grafana 5, hasn't it?
http://docs.grafana.org/administration/provisioning/
