### ISSUE TITLE
Alerting: Rule gets stuck in inactive state after reload

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#56752]
**What happened**:

Assume you have a firing rule. Update the rule with a new condition such that it should go to Normal.

Then, the rule gets incorrectly stuck in the `inactive` state indefinitely, even though it's clearly evaluating.

![2022-10-11-142719_310x196_scrot](https://user-images.githubusercontent.com/8410871/195181310-53c7bb24-ede0-4346-b4be-b45553766052.png)

Note: `state: "inactive"`. As I watch this request poll, I see the "lastEvaluation" timestamp increasing - the rule is evaluating just fine, it's not actually inactive.

This caused some notifications to not be sent:
- Grafana never sent a resolved notification when the rule was updated, because it was just always `inactive`.
- Updating the rule even further (back to a Firing condition) caused firing notifications to also not be sent, because Grafana technically never saw a Normal->Firing transition.

**What you expected to happen**:

I expected the rule to go the Normal state when it's normal, not get stuck in inactive forever.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an always firing rule. In my case, I used a promql query of `vector(5)` and a classic condition of `A greater than 0`.
2. Observe the notification that you receive.
3. Update the condition to something non-firing, like `A greater than 10`
4. Wait a bit...no resolve notification. The UI shows "Normal" but if you look at the responses in the browser, the state is actually "Inactive."
5. Update the condition back to something always-firing, like `A greater than 0`
6. Wait a bit ...no firing notification either, because there was never a Normal->Alerting edge :(

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by grobinson-grafana** [comment]
I'm not sure I was able to reproduce this using the instructions 😞

**Comment by alexweav** [comment]
It's reproducing on the `alertingsquadtest2` HG instance right now.

Also, I noticed it doesn't _always_ happen, i had a few runs where it did not reproduce. There is probably a race condition with how rules get loaded.
