### ISSUE TITLE
Quick Range unexpectedly subtracts from end of range

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#5675]
* **I'm submitting a ...** Bug report

Please include this information:
- What Grafana version are you using? v3.0.4
- What datasource are you using? Graphite

Quite often (in a to me, random fashion) when selecting one of the quick ranges like "Last 7 days" or "Last 1 hour" Grafana unexpectedly changes the end date from "now" to something like "now-1m" or "now-5m".

Apart from it not being the intended time range, it also causes the label atop the dashboard to be less pretty. It becomes **now-24h to now-1m** instead of "Last 24 hours".

I first thought that maybe this is because it copies it from what the dashboard already had, but even when I open a dashboard that explicitly has from "now-24h"  to "now", it will sometimes do this. The behaviour is somewhat random to me, as it does not happen consistently. But usually, once it does happen, it will continue to happen when selecting another quick range.

**Comment by torkelo** [comment]
Have you specified a now delay in the dashboard settings? 

![image](https://cloud.githubusercontent.com/assets/10999/17240917/b43f58ee-556e-11e6-8eb1-c7260b07702e.png)

**Comment by Krinkle** [comment]
Thanks. I've removed it from all our dashboards. A few of them did indeed have it set to `1m
