### ISSUE TITLE
Canvas: Renaming element scrolling issue

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#56758]
https://user-images.githubusercontent.com/88068998/195204333-64af627e-b95d-4981-b5b4-0ae46e4b6ac3.mov

**Comment by nmarrs** [comment]
This appears to only occur when one of the sub editing menus is open for element editing (and not when all sub menus are closed)

**Comment by nmarrs** [comment]
We may want to address this more generally as a general overhaul of the inline editor experience (i.e. tab idea from Ryan given complexity of having a lot of elements at once in list etc.)
