### ISSUE TITLE
wildcard in opentsdb metrics query

### ISSUE THREAD

**Issue by tombin** [grafana/grafana#5676]
Is it possible to do wildcard searches in a opentsdb metrics query the same way you can do this in graphite ?  For example, i have metrics in opentsdb that look like this:

sys.network.eth0.tx
sys.network.eth0.rx
sys.network.eth1.tx
sys.network.eth1.rx

I would like to have only 2 queries like: sys.network.*.tx and sys.network.*.rx.  I can do this with a graphite backend, but opentsdb backend does not appear to work like this.  I am able to create a template to get the eth0, and eth1 as a dropdown, but i'd like to have all the metrics in 1 graph with a simple query.  Could I please request this in a future version ?

**Comment by torkelo** [comment]
Not sure, ask in OpenTSDB forum/project
