### ISSUE TITLE
[Feature Request] Support LDAP Configuration through Environment Variables

### ISSUE THREAD

**Issue by ajsmith** [grafana/grafana#5678]
LDAP configuration (as of Grafana v3.1.0) must be loaded from a file and cannot be read from environment variables. However, file-based configuration can complicate Docker based deployments, especially in cloud deployments such as Kubernetes or OpenShift. Ideally, LDAP configuration would be configurable using environment variables just like most other Grafana configuration settings.

**Comment by andrewthad** [comment]
I would also like for ldap to be configurable through environment variables.

**Comment by ivanfromtheroot** [comment]
Ultimately , configuring LDAP through environment is a must-have feature.

**Comment by actionjack** [comment]
It kinda is a configurable via environment variables.
use GF_AUTH_LDAP_ENABLED=true
Mount your ldap.toml file in a new volume and point to it e.g.:
GF_AUTH_LDAP_CONFIG_FILE=/location/to/mounted/ldap.toml

**Comment by flamein** [comment]
One of the reasons to want environment variables is to pass bind user and bind password from something like Kubernetes secrets without needing complex systems to do it.

**Comment by flamein** [comment]
Also, see https://github.com/grafana/grafana/pull/17526
