### ISSUE TITLE
SQL Query wrong Manipulation

### ISSUE THREAD

**Issue by stefanLeo** [grafana/grafana#56784]
**What happened**: Since upgrading from 9.1.X to 9.2.0 the following queries are parsed wrong by Grafana:
SELECT COUNT(*) FROM X WHERE Y = '' AND B = '$A'

Sent to SELECT Server = SELECT COUNT(*) FROM X WHERE Y = ' AND B='AVALUE'
Note the missing quotation mark.

**What you expected to happen**:
The query sent to SQL Server should be as follows:
Sent to SELECT Server = SELECT COUNT(*) FROM X WHERE Y = '' AND B='AVALUE'

**How to reproduce it (as minimally and precisely as possible)**:
Run a query as specified above

**Anything else we need to know?**:
I am using a variable in the query, this however does not affect the outcome. So the issue persists without variables as well like:
SELECT COUNT(*) FROM X WHERE Y = '' 

results in

SELECT COUNT(*) FROM X WHERE Y = ' 

**Environment**:
- Grafana version: 9.2.0
- Data source type & version: SQL Server 2019
- OS Grafana is installed on: WINDOWS
- User OS & Browser: Firefox (actually any)
- Grafana plugins: None
- Others: I am using the "CODE" UI element to write my queries

**Comment by Ads87** [comment]
Also just come across this same issue after upgrading.

Currently using a variable as an empty string to bypass the parsing error.

**Comment by banzify** [comment]
Experiencing the same issue, valid queries return a syntax error when they contain ''. Can reproduce the issue on the Grafana Live Demo:
![image](https://user-images.githubusercontent.com/38366720/195381895-bb948e82-c9f4-44a8-afad-648fc7510506.png)

**Comment by mdvictor** [comment]
Hello!

Indeed this is an error we are working on - https://github.com/grafana/grafana/pull/56879
