### ISSUE TITLE
Minor annoyance: GitHub atom feed contains the v0.0.0-test tag

### ISSUE THREAD

**Issue by c4talyst** [grafana/grafana#56788]
**What happened**:
- The GitHub atom feed contains the `v0.0.0-test` tag.
- Every time someone/something pushes the `v0.0.0-test` tag, the atom feed gets a new entry at the top.
- Because we use the RSS app in Slack, this posts to a Slack channel every time someone pushes the `v0.0.0-test` tag.
- It's therefore mildly annoying (see screenshots)
- We use the Feed to track Grafana releases in Slack; so we can be informed of awesome new features (and not the `v0.0.0-test` tag, which we don't care for).

**What you expected to happen**:
- Don't push tags for tests
- So that we don't see Test tags in the Atom feed

**How to reproduce it (as minimally and precisely as possible)**:
- Use the RSS app in Slack
- Subscribe to the [atom feed](https://github.com/grafana/grafana/releases.atom)

**Anything else we need to know?**:
- It would be great to not have to turn off this Slack app. 

**Environment**:
- GitHub, CI/CD

**Examples**
Good - e.g. 9.1.7 tag
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16097897/195322821-812c9a6e-bd05-48d1-a605-af8fe795abea.png">

Bad - v0.0.0-test tag
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16097897/195322535-6c3e499d-016f-41eb-a046-c27d309a38f5.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16097897/195322642-d6481132-c6ed-4e75-8660-ad6972e29c03.png">

**Comment by dsotirakis** [comment]
Hello @c4talyst 👋 
Thanks for spotting this. Unfortunately we've encountered this thing in the past as well. It's not our fault really, we use some random tag versions to test our release processes and we want them to be there. `release.atom` ([atom feed](https://github.com/grafana/grafana/releases.atom)) should really notify you only about releases and not about tags.
I have created an issue here https://github.com/orgs/community/discussions/35990 to track it.
Sorry for the inconvenience and the noise, I'll come back as soon as GitHub comes back to us with a suggestion - fix.

**Comment by c4talyst** [comment]
Thanks @dsotirakis - I've upvoted the GitHub community issue and will encourage others to do so too. I've disabled the RSS feed for now. The first time I saw this tag was on 23/08/2022.

**Comment by Hipska** [comment]
@c4talyst Why not using the suggested releases feed?

**Comment by gtirloni** [comment]
This is really annoying.
