### ISSUE TITLE
Alerting notifications 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5679]
- [x] Basic email
- [x] Basic webhook
- [x] Basic slack 
- [x] Rich slack with metric + value
- [x] Rich webhook with metric + value

**Comment by mathias-baumann-sociomantic** [comment]
if you add a `*` in front of those lines they appear as proper checkboxes ;)

**Comment by bergquist** [comment]
removing rich emails since thats part of https://github.com/grafana/grafana/issues/5849
