### ISSUE TITLE
Dashboard is set to UTC, but is ignoring this and accounting for daylight-savings timezone changes

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#56799]
The context of the problem is described in more detail here:
https://github.com/grafana/grafana/discussions/56795

**What happened**:
I use this PromQL to query **only for data at 23:00:00 on the last day of each month**:
```sql
sum(grafanacloud_logs_instance_bytes_received_per_second)
and day_of_month() == days_in_month() and hour() == 23
```

But when I render the Bar Chart, I see that the timezone is being taken into account, and the date rendered onto the x-axis tick-labels on the graph is the first of the month, not the last (ie the time got changed to 00:00:00, because I live in the UK and it's BST right now, ie UTC +1) for the months since the spring time:

Specifically note the x-axis tick labels: `02/28` followed by `04/01`!

<img src=https://user-images.githubusercontent.com/2903904/195337586-8bb6ddd4-ef9a-445e-85a7-4eb187295f37.png width=400>

The tick-marks from End-Oct thru End-Feb show how I want and expect them to show, but the tick marks for the rest of the year show month-start for the following month, rather than month-end of the preceding month.

Why is it that when I use ` and day_of_month() == days_in_month() and hour() == 23` in my PromQL my own timezone is taken into account, even though the dashboard is clearly set to use UTC and not my own browser timezone or personal time.
<img src=https://user-images.githubusercontent.com/2903904/195338546-1cfdfc56-f9f4-4ae4-b8c2-6ed8612cf93c.png width=400>

**What you expected to happen**:
The time to remain at 23:00:00 for every month shown, both before and after British daylight-savings time changed, given that this dashboard is in UTC only
ie. End of March to be rendered with x-axis tick-label as `03/31` and not `04/01`, and the same for the months following March.

**How to reproduce it (as minimally and precisely as possible)**:
Just repeat the query provided above
With:

- 1 year into the past
- Max data points: 8760
- Min interval: 1h

**Anything else we need to know?**:
This doesn't seem to be present in all environments. I've seen one internal Grafana Ops instance where this isn't a problem!
And for people in other time-zones I've seen that more hours get added to every month. Ie. the 23:00:00 may become 07:00:00 for someone 8 hours ahead.

**Environment**:
- Grafana version: GrafanaCloud
- User OS & Browser: MacOS, Chrome
- Grafana plugins: None relevant

**Comment by zuchka** [comment]
@samjewell is this issue specific to the bar-chart plugin? Just want to get this to the right squad 👍

**Comment by samjewell** [comment]
@zuchka I think you commented and then deleted your comment. But yes, I think this is specific to the Bar Chart plugin. Thanks

**Comment by leeoniya** [comment]
i think we are forgetting to pass the timezone into the x axis constructor since barchart was not originally intended to have time along x (only text labels).

i just fixed a very similar issue with Heatmap. will take at this look today.

**Comment by samjewell** [comment]
@leeoniya and team, I know it's been fixed a while back, but just wanted to say **thanks** for fixing this ❤️
