### ISSUE TITLE
Support for pie chart

### ISSUE THREAD

**Issue by Nihn** [grafana/grafana#568]
Please add support for graphite's pie chart. It would greatly improve representation of various kind of statistics.

**Comment by sunjay** [comment]
+1
Any word on when this will be in?

**Comment by gsaray101** [comment]
+1 
I am also eagerly waiting for pies and gauges. Has anybody created this?

**Comment by kmoppel** [comment]
+1

**Comment by MrGeneric** [comment]
+1

**Comment by skynet** [comment]
:+1:

**Comment by elasticwarehouse** [comment]
+1

**Comment by pzuk** [comment]
+1

**Comment by gsaray101** [comment]
@loredo, I am also interested in your solution. Would you be more detailed as to how you were able to draw a pie chart?

**Comment by mermino** [comment]
+1

**Comment by skynet** [comment]
can we mix grafana with other charting library? Particularly interested to setup a business dashboard that works with (http://gionkunz.github.io/chartist-js/)[chartist.js]

**Comment by bahadir** [comment]
I've created a simple pie chart panel using single stat panel:

![Pie Chart](http://i.imgur.com/rkDu1EB.jpg)

Here's the code: https://github.com/bahadir/grafana/compare/panel-pie-chart

I'll open a PL after I fix some CSS issues. All feedback is greatly appreciated.

**Comment by o** [comment]
@bahadir :100: Looks good!

**Comment by phagedorn** [comment]
Looks very nice :+1: 
do we have a time offset for data thats deliverd only for the last day and not for today ?
Next one is the table Chart ? ;)

**Comment by bahadir** [comment]
@phagedorn it should respect any timestamp defined with timepicker. I want to add legend to pie chart, I guess it can evolve into table chart.

**Comment by kishorecsit7** [comment]
+1

**Comment by bigkraig** [comment]
:+1:

**Comment by makapuf** [comment]
:+1:

**Comment by iDemonix** [comment]
+1

**Comment by niclashoyer** [comment]
@bahadir did you open a PR yet? Do you need help?

**Comment by jregovic** [comment]
+1

**Comment by guileen** [comment]
:+1:

**Comment by jlopp** [comment]
Since +1s and :+1:s haven't been working, I reached out to @bahadir on Twitter. Hopefully we'll see a PR soon: https://twitter.com/kandemir/status/610024988666691584

**Comment by bahadir** [comment]
Hello,

I'm still working on this. It was working on 1.9 branch but I couldn't manage to run in on master.

**Comment by nimeops** [comment]
Of Course !! +1

**Comment by shankar-piriya** [comment]
+1 Eagerly waiting for this one

**Comment by bahadir** [comment]
My branch was based on 1.9 and I can't locate the problem with master branch. I'm going to clone static panel graph to make it work again. Apologies.

**Comment by druchoo** [comment]
+1

**Comment by xjewer** [comment]
+1

**Comment by vaisakhb** [comment]
+1

**Comment by theplaypig** [comment]
+1

**Comment by danievanzyl** [comment]
+1

**Comment by akamel001** [comment]
+1

**Comment by enchantner** [comment]
+1

**Comment by blysik** [comment]
Would love to see this.

**Comment by KunalSaini** [comment]
+1

**Comment by sudarkoff** [comment]
Don't care for pie charts (http://www.businessinsider.com/pie-charts-are-the-worst-2013-6), but would love to see gauges.

**Comment by goriparthi** [comment]
+1. 

@bahadir : Thanks Mate for extra effort in trying to get this. This will be really useful. I hope this and other type data rendering visualizations are given more importance in this project. Great project.

**Comment by vintrax** [comment]
+1 - Pie chart support would be great!

**Comment by bamboo54** [comment]
+1 - do need Pie chart support!

**Comment by Johaann** [comment]
+1 !!!!

**Comment by csueiras** [comment]
+1 Other types of charts would be great to have.

**Comment by unaizorrilla** [comment]
+1 Other types of charts would be great to have.

**Comment by martinb69** [comment]
+1 woud be great to have!

**Comment by jeansg** [comment]
+1 In graphs like singlestat with a pie chart, awesome !

**Comment by jmaitrehenry** [comment]
I just tke the work of @bahadir and made some modification for having it running on master.

You can find the modification on my branch here: https://github.com/jmaitrehenry/grafana/compare/master...jmaitrehenry:panel-pie-chart?expand=1
<img width="661" alt="screen shot 2015-10-06 at 9 39 26 am" src="https://cloud.githubusercontent.com/assets/593562/10310786/ae799bc8-6c11-11e5-81c2-9faac75085bc.png">

I will add more option like label / legend before making a PR.

**Comment by jmaitrehenry** [comment]
You can now choose how the legend will be displayed (none, on graph, at the right side)

<img width="796" alt="screen shot 2015-10-06 at 9 46 57 pm" src="https://cloud.githubusercontent.com/assets/593562/10327308/de9499f4-6c73-11e5-98c1-ca9534daa9c9.png">

Next table value and display value (not only %)

**Comment by bahadir** [comment]
kudos @jmaitrehenry!

**Comment by karma1911** [comment]
@jmaitrehenry that seems great ! How can I install it on my own grafana server ?

**Comment by bigkraig** [comment]
@torkelo can we get this merged?

**Comment by jmaitrehenry** [comment]
I need to do some refactor on it, but I didn’t have the time for that, sorry.

**Comment by bigkraig** [comment]
Yep I saw that, looks like it needs a little bit more. no problem

**Comment by karma1911** [comment]
No prob, I'll wait for that, thanks !

**Comment by addshore** [comment]
*jumps on the +1 bandwagon*

**Comment by patjlm** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by alvaromunoz** [comment]
+1

**Comment by larsr85** [comment]
+1

**Comment by pavleec** [comment]
:+1:

**Comment by wzph** [comment]
+1

**Comment by floppy84** [comment]
+1

**Comment by sc0rp10** [comment]
+1

**Comment by Fursje** [comment]
+1

**Comment by karma1911** [comment]
@jmaitrehenry any chance working on the subject recently ?

**Comment by jmaitrehenry** [comment]
@karma1911 not really, I was pretty busy last weeks, and I would like to finish a contribution in an another project first and my second child was born 7 day ago ~~

If someone want to take the leadership of my branch, it will help me a lot!

**Comment by karma1911** [comment]
Congrats for the baby ! 
Hope someone will be able to help you out (for the pie, not your child ;)

**Comment by shamasis** [comment]
+1

**Comment by arenstar** [comment]
+1

**Comment by bergquist** [comment]
Thank you @bahadir and @jmaitrehenry for your contributions.
I have moved and update the code from the PR into a plugin repository.

https://github.com/grafana/panel-plugin-piechart

So now you can add piecharts as a plugin :)

**Comment by bergquist** [comment]
Closing this issue since the plug-in have been created.

**Comment by addshore** [comment]
Woo! Many thanks! :)

**Comment by FulvioSpelta** [comment]
Thanks for the work. A question is it possible to evolve this in order to have true and various gauge widgets ? I think that they could be very useful to show "current values" in a graphical rich format
Thanks again

**Comment by gsaray101** [comment]
has anybody installed pie-chart plugin to windows, trying to mimic linux install, does dot seem to be working. Not seeing the pie-chart panel

**Comment by karma1911** [comment]
Anybody made that plugin work ? I'm on centos, using grafana 2.5.0 on prod env, 2.6.0 in dev env, and I was not able yet to make it work. Tried to put the plugin in different paths, without success : /var/lib/grafana/plugins, /usr/share/grafana/public/app/plugins, /usr/share/grafana/public/app/panels .. I have nothing in the menus when I try to add a new element in my dashboards.

Also tried to add the path in config file, and I have the following error message in the logs : 
2015/12/28 10:33:34 [setting.go:285 loadSpecifedConfigFile()] [E] Unknown config section plugins.piechart defined in /etc/grafana/grafana.ini

Any clue please ?

**Comment by bergquist** [comment]
@karma1911 @gsaray101 @FulvioSpelta @addshore 

Sorry for not mentioning it :(
The plug in support is only available in master. So you have three options
* use the nightly build
* build it yourself from master branch
* wait for next Grafana release

**Comment by karma1911** [comment]
Makes more sense :) Thanks, will do that !

**Comment by FulvioSpelta** [comment]
Thanks a lot for your infos. Wish you an happy new year.

**Comment by rmsys** [comment]
Tks!

**Comment by toni-moreno** [comment]
:+1:

**Comment by c4t3l** [comment]
When is the next release scheduled to occur?  :)

**Comment by rmsys** [comment]
+1

**Comment by torkelo** [comment]
@c4t3l maybe mid/end February

**Comment by muhahacz** [comment]
+1

**Comment by zapient** [comment]
+1

**Comment by chewre** [comment]
+1

**Comment by zphj1987** [comment]
+1

**Comment by ntquyen** [comment]
+1

**Comment by Hronom** [comment]
+1

**Comment by Zlogene** [comment]
+1

**Comment by ricardoekm** [comment]
+1!

**Comment by evanbreznyik** [comment]
I'm having a hard time imagining how this is anything but a single stat
graph, yes?

It would be cumulative for a time offset, right?

**Comment by gmoi** [comment]
Pie charts? Why?

**Comment by shamasis** [comment]
I know - they suck. But still, multi level pie is very useful for me.

**Comment by ssjunior** [comment]
+1

**Comment by Keleir** [comment]
@loredo I'm fond of pie chart, but confused how to configure it quiet soon. :face_with_thermometer:

**Comment by bergquist** [comment]
You can download the piechart plugin from https://grafana.net/plugins/grafana-piechart-panel

**Comment by penupati** [comment]
Hi,

We would like to draw pie chart from elastic search json data mentioned below, we are unable to find suitable lucene query.
we need to draw graph for 3 categories with color value (color=blue and color=red). I am not getting how to group data and display in pie chart. Can some one help us?

{
  "_class" : "hudson.model.Hudson",
  "jobs" : [
    {
      "_class" : "org.jenkinsci.plugins.workflow.job.WorkflowJob",
      "name" : "amc-bootstrap-pl",
      "color" : "blue"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "archiva-demo-app",
      "color" : "blue"
    },
    {
      "_class" : "org.jenkinsci.plugins.workflow.job.WorkflowJob",
      "name" : "aris-analytics-pipeline",
      "color" : "blue"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "aris-core-ui",
      "color" : "blue"
    },
    {
      "_class" : "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
      "name" : "aris-core-ui-pl"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "aris-demo-app",
      "color" : "blue"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "aris-web-base-app",
      "color" : "notbuilt"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "aris-web-platform",
      "color" : "blue"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "aris-web-platform-backup",
      "color" : "red"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "awa-emr-trigger",
      "color" : "red"
    },
    {
      "_class" : "hudson.model.FreeStyleProject",
      "name" : "config-server-build",
      "color" : "red"
    }
}
