### ISSUE TITLE
Feature request for docs around backup

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#5680]
It would be nice if there was a set of docs for backing up a grafana server, config/data/dashboards (not export as doing this one at a time will take very long so a doc on how to back them up server side). 
Basically more docs on backup as this is becoming a critical part of many peoples monitoring infra. Its taken me months to perfect all my dashboards.

**Comment by torkelo** [comment]
Generally it depends on what grafana database you use. If you use sqlite3 you should backup the sqlite3 database, if you use mysql or postgres use the best practice backup processes for those databases.

**Comment by waqark3389** [comment]
I'm using default. So simply backing up the grafana.db file is enough?

**Comment by torkelo** [comment]
yes, and your `/etc/grafana/grafana.ini` file
