### ISSUE TITLE
Stacked Bar charts are not really stacked

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [grafana/grafana#5681]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
Version: 3.1.0
Datasource: InfluxDB 0.13
OS: Ubuntu Linux

I'm creating a stacked bar chart and expected to see all values/bars stacked on top of eachother. Instead some bars are overlapping others. This happens with every stacked barchart that I'm creating, independent of the measurement I'm using. When I hover over the bar (as seen in the screenshot) it's visible that one bar overlaps others behind it.
As soon as I add lines (with 0 width) to the chart the bars seem to stack fine but when I hover they begin to "jump and move"
All tested in Chrome 51 if that matters.

Stacked bar chart, note that the sum of values doesn't add up to where the stacked bar ends. Also note that the bars get translucend and seems to show the other values behind it.
![screen shot 2016-07-29 at 13 09 22](https://cloud.githubusercontent.com/assets/10830223/17246673/e33fdd8e-558d-11e6-85c2-3b8abd0abeff.png)

Stacked bar chart with additional lines (ad 0 width). Bar seems correct but hover makes the bars jump
![screen shot 2016-07-29 at 13 09 04](https://cloud.githubusercontent.com/assets/10830223/17246678/e8157eb8-558d-11e6-9508-8c4d9d3c4f58.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
what's your query? Do you have a group by time? The data needs to be grouped to the values fall on the  same time for the stacking to work :)

**Comment by reinhard-brandstaedter** [comment]
There is a group by time(5m)

SELECT distinct("DB_Count") FROM "Page Types - DB Usage" WHERE $timeFilter GROUP BY time(5m), "y_page_controller_name" fill(null)

![screen shot 2016-07-29 at 13 47 21](https://cloud.githubusercontent.com/assets/10830223/17247363/05b2a162-5593-11e6-9247-19ee19dee850.png)

**Comment by torkelo** [comment]
change your query to have `fill(0)` so there is a value for each series at every group.

**Comment by reinhard-brandstaedter** [comment]
I tried that before with different settings 0, previous, null. Didn't really make a change.
What puzzles me is that some values are really stacked but two are overlapping the rest.

**Comment by torkelo** [comment]
strange, maybe a bug in the influxdb group by time? Can you open chrome dev tool and network tab look at the raw data influxdb responds with? Are the groups in regular 5m buckets?

**Comment by reinhard-brandstaedter** [comment]
That might be the issue the individual measurements are not coming into influx in regular time intervals. So the raw data has different occurences/timestamps and maybe that confuses the charting.

If I change the aggregate function to avg() the stacked bar chart works fine but it's not really what I want to see...

![screen shot 2016-07-29 at 14 26 13](https://cloud.githubusercontent.com/assets/10830223/17248144/aad21c18-5598-11e6-973a-89da547ca112.png)

**Comment by torkelo** [comment]
if you want to group the data into time buckets to stack them you need to group the data, looks like InfluxDB distinct does not returned proper grouped timestamps

**Comment by reinhard-brandstaedter** [comment]
Yes, seems like it. So it's indeed not a grafana display issue. Thank you.
