### ISSUE TITLE
Panel not found when using panelId as string and sharing as embeded iframe

### ISSUE THREAD

**Issue by maykSVK** [grafana/grafana#5682]
I have found possible bug. I am using grafana API to create and update dashboards especially graph panels. I know that when you create new graph panel using grafana UI, the integer panelId is assigned to new panel. I need for my solution identify panel by unique string. So I tried to send panelId throught API as unique string and everything worked perfectly. I can update this panel, everything displays perfectly in grafana UI. The "Panel not found" problem will occur, when I want share this panel in embeded iframe. Everything works fine as soon as I change panelId from string to integer. The error from console is:
`boot.8ba215a1.js:36 TypeError: Cannot read property 'getPanelById' of undefined
    at a.initPanelScope (boot.8ba215a1.js:13)
    at n.$emit (boot.8ba215a1.js:36)
    at n.f.appEvent (boot.8ba215a1.js:28)
    at boot.8ba215a1.js:11
    at q (boot.8ba215a1.js:36)
    at boot.8ba215a1.js:36
    at h (boot.8ba215a1.js:36)
    at boot.8ba215a1.js:36
    at n.$eval (boot.8ba215a1.js:36)
    at n.$digest (boot.8ba215a1.js:36)`

I assume that panelId is designed to be integer, but is there som way how to identify panel by unique string? I just found out, that with string panelId everything is displayed fine, but I cannot update anything using grafana UI neither, so there is definity not good to set panelId to string, but still I need to achieve this somehow, can you give me some feedback how to do this? Using panel title might be the way, but this title will be localized string and definitely will not be unique.

Thanks for your advice.

**Comment by torkelo** [comment]
panelId should be a integer, but any dashboard unique integer will work
