### ISSUE TITLE
Mixed source panels displays invalid times on graph tool tips

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#5684]
If you hover over the graph that is created with the "Mixed" Panel Data Source you get the current values an the time, however the values displayed in the hover over don't corrispond with the X-Axis

![image](https://cloud.githubusercontent.com/assets/104239/17251010/d449ba14-559e-11e6-9cd7-3addd5ecbb49.png)

**Comment by torkelo** [comment]
The all series tooltip has some issues when your series contain discontinuous / disconnected / regular timestamps etc, use single value tooltip instead for now.

https://github.com/grafana/grafana/issues/3063
