### ISSUE TITLE
No error icon for error in query response

### ISSUE THREAD

**Issue by smalik03** [grafana/grafana#5685]
There used to be an error icon on the top left of the panel if a query returns an error in response. I do not see that anymore in 3.1.0. Did something change?

Before - 
![image](https://cloud.githubusercontent.com/assets/6777407/17254516/2a3f4892-5583-11e6-8c36-a0470e0962c1.png)

Now - 
![image](https://cloud.githubusercontent.com/assets/6777407/17254622/83fbb49c-5583-11e6-94df-a877fccc5fb5.png)

- What Grafana version are you using?  - 3.1.0
- What datasource are you using?  - OpenTSDB
- What OS are you running grafana on? - Windows 7
- What did you do? - Made wrong query
- What was the expected result? - Error icon on panel
- What happened instead? - no error icon

**Comment by torkelo** [comment]
Can you show the response from OpenTSDB? (open chrome dev tools network tab)

**Comment by smalik03** [comment]
@torkelo this is the response I am getting from OpenTSDB - 

`{"error":{"code":400,"message":"No such name for 'metrics': 'xyz'","details":"No such name for 'metrics': 'xyz'"}}`

Also, this was working fine in 3.1.0 beta-1.

**Comment by torkelo** [comment]
And the http response code?

**Comment by smalik03** [comment]
Response code is 400

**Comment by smalik03** [comment]
@torkelo I did some digging and looks like this stopped working after 6a8c774. I am not sure what this commit does, but commenting lines 254 and 255 fixes this issue.

**Comment by smalik03** [comment]
@torkelo any updates on this?

**Comment by utkarshcmu** [comment]
@smalik03 I can see the error "No such metrics" in 3.1.1 and in master branch of Grafana on Chrome. If you can test with 3.1.1 or master branch then this is not an issue anymore.
