### ISSUE TITLE
$tag_ec2-instance-id not working in aliases when using group by

### ISSUE THREAD

**Issue by zachaller** [grafana/grafana#5687]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.4

- What datasource are you using? InfluxDB

- What OS are you running grafana on? Ubuntu Server

- What did you do? Tried to use "cpu_usage $tag_ec2-instance-id" in an alias when using group by

- What was the expected result? I would expect that the alias would show up in the tabled legend with the instance id in them

- What happened instead? I get this as a label in the table "cpu_usage undefined-instance-id"

**Comment by torkelo** [comment]
try `[[tag_ec2-instance-id]]`

**Comment by zachaller** [comment]
worked thanks, sorry for the issue, i did a decent search i thought and could not find any references to escape type sequences etc.
