### ISSUE TITLE
Feature Request - Add option for predict value in "Moving average" pipeline agg

### ISSUE THREAD

**Issue by vaibhavinbayarea** [grafana/grafana#5688]
I found a need for trending / predicting certain values. Moving average in elasticsearch has an option for "predict" based on the model used.

See: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-movavg-aggregation.html#_prediction

I have a patch that adds support for this. 

Please include this information:
- What Grafana version are you using?
  Version 4.0.0-pre1 (commit: v3.1.0+116-g934030a-dirty)
- What datasource are you using?
  Elasticsearch

Patch in action:
![screen shot 2016-07-29 at 12 06 26 pm](https://cloud.githubusercontent.com/assets/4401392/17260394/edec34d4-5584-11e6-8a93-f3e7fc4c8804.png)

Will be creating a pull request soon.

**Comment by tomfun** [comment]
+1
The example
```json
{
    "the_movavg":{
        "moving_avg":{
            "buckets_path": "the_sum",
            "window" : 30,
            "model" : "simple",
            "predict" : 10
        }
}
```
is good start, but what if we want more complex situation:
```json
{
    "the_movavg":{
        "moving_avg":{
            "buckets_path": "the_sum",
            "window" : 30,
            "model" : "holt_winters",
            "settings" : {
                "type" : "mult",
                "alpha" : 0.5,
                "beta" : 0.5,
                "gamma" : 0.5,
                "period" : 7,
                "pad" : true
            }
        }
}
```
I think, you need add not just another field, but make textarea for such jsons, this will be much better.

**Comment by vaibhavinbayarea** [comment]
I have the complex situation working as well (need to add pad option). I need to create unit tests and rebase with top of the tree. 

Will try to get it done by EOW.

**Comment by vaibhavinbayarea** [comment]
@tomfun https://github.com/grafana/grafana/pull/7154 addresses your complex situation

**Comment by julienmary** [comment]
Is is planned to merge this with the main branch ? on grafana/grafana ?

**Comment by torkelo** [comment]
was merged last summer

**Comment by julienmary** [comment]
But there is no similar screen when using InfluxDB database as datasource, especially nothing to select holt_winters model for example. I missed something ?

**Comment by torkelo** [comment]
Yes, this issue is about Elasticsearch moving average aggregation.
