### ISSUE TITLE
Dashboards with multiple template variables using key/value pairs have refresh problem

### ISSUE THREAD

**Issue by ftasso** [grafana/grafana#56892]
**What happened**: after upgrading to Grafana 9.2.0, all my dashboards having two or more comboboxes using key/value loaded from database have problem, only the last combobox if updated

**What you expected to happen**: all the comboboxes must be updated

**How to reproduce it (as minimally and precisely as possible)**: in attach a basic dashboard with two comboboxes with key/value pairs
[grafana.txt](https://github.com/grafana/grafana/files/9778830/grafana.txt)

**Anything else we need to know?**:

**Environment**: CentOS Linux release 7.9.2009
- Grafana version: 9.2.0 (2022-10-11)
- Data source type & version: MySql
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

https://github.com/grafana/grafana/issues/56892#tasklist-block-40d30e9d-36e8-4816-bda1-6d7605536942

**Comment by ftasso** [comment]
Step to recreate the error:
- create two variables type query using the following sql script (no table needed):
SELECT "A" AS __text, "AKEY" AS __value FROM DUAL
UNION
SELECT "B" AS __text, "BKEY" AS __value FROM DUAL
UNION
SELECT "C" AS __text, "CKEY" AS __value FROM DUAL
- select two different value for the two combobox then save the dashboard with the option "Save current variable values as dashboard default"
- reloading the dashboard only one combobox is filled

Thank you,
Fabrizio

**Comment by zuchka** [comment]
Thanks for creating this issue, @ftasso 

I think I was able to reproduce this on our sandbox. Is this your error?
https://play.grafana.org/d/NhgzZASVk/query-var-test?orgId=1

**Comment by ftasso** [comment]
Yes, this is error I have in my dashboard. 

Thank you

**Comment by jakubvojacek** [comment]
Also having this issue, thanks @ftasso for reporting it

**Comment by ntimo** [comment]
Do you have any news when this will be fixed? This sadly broke all my mariadb based dashboards.

**Comment by ftasso** [comment]
Ok, Grafana 9.2.1 solve this issue!
