### ISSUE TITLE
9.2.0 broke previously working datasource

### ISSUE THREAD

**Issue by cameronwaterman** [grafana/grafana#56891]
**What happened**:

After upgrading to Grafana 9.2.0, one of our datasources is no longer working, however there are other datasources that are working.

**What you expected to happen**:

The datasource would load.

**How to reproduce it (as minimally and precisely as possible)**:

Build [systemlink-dataframe-datasource](https://github.com/ni/systemlink-dataframe-datasource) and attempt to load it.

Here is also a zip containing a couple different versions of the datasource, 1.2.1 was previously working and 1.3.0 is untested. There is also a different datasource in there that does work with 9.2.0 (source [here](https://github.com/ni/systemlink-notebook-datasource)).
[datasources.zip](https://github.com/grafana/grafana/files/9778800/datasources.zip)

Edit: I've validated that the non-working data source did work with Grafana 9.1.8 and stopped loading immediately after upgrading to 9.2.0.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.0
- Data source type & version: [systemlink-dataframe-datasource](https://github.com/ni/systemlink-dataframe-datasource)
- OS Grafana is installed on: Windows / Linux (various distros)
- User OS & Browser: Chrome
- Grafana plugins: See datasource above
- Others: N/A

**Comment by zuchka** [comment]
Thanks for creating this issue, @cameronwaterman 

sorry you're blocked on this.  [systemlink-dataframe-datasource](https://github.com/ni/systemlink-dataframe-datasource) is a community built plugin so you're two best bets for support would be to make an issue in their repo or ask for help in the [plugins community section on our forum](https://community.grafana.com/c/plugin-development/30).

in the meantime here are some /maybe/ helpful insights:
1) that plugin is what we call a frontend datasource plugin. That is the old style, which does not work with the new alerting platform.
2) if you have to build the plugin from source then I would make sure that you're using node 16+ and make sure this isn't a dependency issue
3) here are a list of recent changes to plugins that were merged in 9.2.0:
```
Plugin development fixes & changes
GrafanaUI: Add required behavior to Inline Field. https://github.com/grafana/grafana/pull/54867, [@gefgu](https://github.com/gefgu)
CustomScrollbar: Add optional scroll indicators to CustomScrollbar. https://github.com/grafana/grafana/pull/54705, [@ashharrison90](https://github.com/ashharrison90)
Build: Introduce ESM and Treeshaking to NPM package builds. https://github.com/grafana/grafana/pull/51517, [@jackw](https://github.com/jackw)
```

and also these:
```
93:- **CloudWatch:** Enable feature adoption tracking in the plugin. [#54299](https://github.com/grafana/grafana/pull/54299), [@sunker](https://github.com/sunker)
113:- **GrafanaUI:** Add icon to links on Plugin configuration page. [#55581](https://github.com/grafana/grafana/pull/55581), [@leandro-deveikis](https://github.com/leandro-deveikis)
132:- **Navigation Bar:** Remove plugins link under Server Admin. [#54386](https://github.com/grafana/grafana/pull/54386), [@academo](https://github.com/academo)
133:- **Navigation:** Don't round app plugin icon images. [#54543](https://github.com/grafana/grafana/pull/54543), [@joshhunt](https://github.com/joshhunt)
138:- **Plugins:** Add feature toggles for long running queries. [#54349](https://github.com/grafana/grafana/pull/54349), [@kevinwcyu](https://github.com/kevinwcyu)
139:- **Plugins:** Add secure JSON fields to plugin setting DTO. [#55313](https://github.com/grafana/grafana/pull/55313), [@wbrowne](https://github.com/wbrowne)
140:- **Plugins:** Handle app plugin proxy routes per request. [#51835](https://github.com/grafana/grafana/pull/51835), [@marefr](https://github.com/marefr)
141:- **Plugins:** Use error plane for api/ds/query. [#54750](https://github.com/grafana/grafana/pull/54750), [@wbrowne](https://github.com/wbrowne)
161:- **RBAC:** Add permissions to install and configure plugins. [#51829](https://github.com/grafana/grafana/pull/51829), [@gamab](https://github.com/gamab)
177:- **Secrets:** Add fallback to secrets kvstore plugin. [#54056](https://github.com/grafana/grafana/pull/54056), [@guicaulada](https://github.com/guicaulada)
179:- **Secrets:** Implement secrets manager plugin fallback store. [#54496](https://github.com/grafana/grafana/pull/54496), [@guicaulada](https://github.com/guicaulada)
180:- **Secrets:** Improve error handling for secrets manager plugin. [#54811](https://github.com/grafana/grafana/pull/54811), [@guicaulada](https://github.com/guicaulada)
207:- **Fix:** Adjusting plugin.json schema regex. [#54515](https://github.com/grafana/grafana/pull/54515), [@tolzhabayev](https://github.com/tolzhabayev)
```

those might help the NI folks get up and running again 👍

**Comment by cameronwaterman** [comment]
@zuchka - Following up on this and documenting for anyone else that runs into this issue... it does seem there was a change in behavior with 9.2.0 that broke loading multiple unsigned plugins that are delimited by a comma followed by a space.

That is to say, this worked prior to 9.2.0:
`allow_loading_unsigned_plugins = ni-sldataframe-datasource, ni-slnotebook-datasource`
...and does not work with 9.2.0. Removing the commas between the datasources fixes the issue.

I didn't nail down the exact commit, but I'm assuming it is related to one of these two:
https://github.com/grafana/grafana/commit/d0d8544dedfd67e336a6ba1959e8040b8f732f45
https://github.com/grafana/grafana/commit/0571d98bba44f523f717b9d855250f4c6a743b0c

**Comment by zuchka** [comment]
thank you so much, @cameronwaterman! ❤️
