### ISSUE TITLE
Loki: log-row-filtering with escaped label-values produces incorrect LogQL query

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#56918]
when you display logs from Loki in explore, you can open a log-row, and click the [+] button to narrow things down.
this breaks when the query already contains a filter where the label-value contains escaped characters.

how to reproduce:

- `make devenv sources=loki`
- go to explore, add this loki query: `{job="\"grafana/data\""}`, run the query, verify it worked
- open a log-line, and click [+] next to `source=data`. the query becomes `{job="\grafana/data\", source="data"}`. if you run it, you get an error about invalid-char-escape

**Comment by ivanahuckova** [comment]
I have tried to reproduce this but it seems at one point we fixed it. I have tested this in both - code mode and builder mode. 
Therefore I am closing the issue. 

https://user-images.githubusercontent.com/30407135/211858694-5e703677-68d3-4db0-a5fc-8b12a27e0f6f.mov

https://user-images.githubusercontent.com/30407135/211858962-6ef830fe-b82f-49f8-9169-24ca81a51293.mov
