### ISSUE TITLE
[Bug]: Elasticsearch query editor allows user to remove last group by (should not allow this)

### ISSUE THREAD

**Issue by danielkman** [grafana/grafana#5692]
I changed the query in the live demo dashboard using the Elasticsearch Metrics dashboard "[Top 5 servers](http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=1&fullscreen&edit&editorTab=Metrics)" panel and the metrics query panel became broken 

<img width="1052" alt="grafana_-_elasticsearch_metrics" src="https://cloud.githubusercontent.com/assets/2141074/17286894/209b81f8-57d5-11e6-8134-cc572412568e.png">

The console shows this

<img width="1009" alt="grafana_-_elasticsearch_metrics" src="https://cloud.githubusercontent.com/assets/2141074/17286925/4de93592-57d5-11e6-9c75-4b64435581ad.png">

This also happens when I grab the latest release (3.1.0) from homebrew on Osx

**Comment by torkelo** [comment]
cannot replicate here :(

![image](https://cloud.githubusercontent.com/assets/10999/17291337/8c1678b2-57e3-11e6-86bb-294d8ced1569.png)

http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=1&fullscreen&edit&editorTab=Metrics

Can you describe what you are doing to get the error? Have you changed the json? The error message suggest the json is not valid ES query

**Comment by danielkman** [comment]
I opened the query editor and removed the last 2 group by clauses
<img width="1429" alt="grafana_-_elasticsearch_metrics_" src="https://cloud.githubusercontent.com/assets/2141074/17291581/8140eb16-57ed-11e6-8679-5f4d808ff710.png">

Then switched to the General tab and when I switched back it was corrupted.

**Comment by torkelo** [comment]
ah, that should not be possible (to remove the last group by), will fix.
