### ISSUE TITLE
empty annotation is created

### ISSUE THREAD

**Issue by LuboVarga** [grafana/grafana#5693]
* **I'm submitting a Bug report**

Please include this information:
- What Grafana version are you using?
Grafana v3.1.0 (commit: v3.1.0)

- What did you do?
I have porovisioned dashboard by curl call:
```
curl -X POST -d @"/usr/share/grafana/public/dashboards/stage.json.dashboard.request" 'http://localhost:3000/api/dashboards/db' --header 'Content-Type: application/json' --header 'Authorization: Bearer eyJrIjSOMEcorrectAPIkeyForGRAFANAinstanceIjoxfQ=='
```
In request, there is an empty annotation. something like this:
```
"annotations": {
  "list": [{}]
}
```

- What was the expected result?
I have expected that no annotation will be created (there is no name for annotation, nor query)

- What happened instead?
An empty annotation has shown on dashboard. Just empty named checkbox.

**Comment by torkelo** [comment]
well your dashboard did include an empty annotation object :) 

change to 
```
"annotations": {
  "list": []
}
```
