### ISSUE TITLE
Timeseries：unable to show point info and timeseries display error

### ISSUE THREAD

**Issue by lushaorong** [grafana/grafana#56934]
**What happened**:
unable to show point info and timeseries display error
![image](https://user-images.githubusercontent.com/16489768/195816473-9d498fc8-d2ab-4ffa-b8bd-b5695fba585d.png)
![image](https://user-images.githubusercontent.com/16489768/195816518-a7c865e3-0e66-4717-bae5-d2b288da01da.png)

**What you expected to happen**:
 show point info and timeseries display erightror

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.4.5
- Data source type & version:  Altinity plugin for ClickHouse:2.5.2
- OS Grafana is installed on: docker
- User OS & Browser: window10-Chrome(106.0.5249.103)
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
make sure your values are sorted ascending by timestamp and/or try a 9.1.0 or later release. we improved the unsorted detection and auto-sorting logic in https://github.com/grafana/grafana/pull/51602

**Comment by lushaorong** [comment]
> make sure your values are sorted ascending by timestamp and/or try a 9.1.0 or later release. we improved the unsorted detection and auto-sorting logic in #51602

This panel consists of multiple queries. How do I sort them

**Comment by leeoniya** [comment]
there is a `Sort by` transformation: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#sort-by

or the `Prepare time series` transformation: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#prepare-time-series

**Comment by lushaorong** [comment]
> there is a `Sort by` transformation: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#sort-by
> 
> or the `Prepare time series` transformation: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#prepare-time-series

only ```sort by``` or  ```Prepare time series``` will not work, I used ```Out join``` and ```Sort by```

**Comment by leeoniya** [comment]
`Outer join` does a sort internally, so you probably don't need the additional `Sort by`
