### ISSUE TITLE
grafana snapshot do not refresh data 

### ISSUE THREAD

**Issue by pc10201** [grafana/grafana#5696]
Grafana version:3.1
datasource:influxdb 0.13
OS:centos 6

I want share the dashboards to another web system.

I have created a snapshot at 15:43,after 30mins

I see it again.But the data is not refresh.

![snapshot](https://cloud.githubusercontent.com/assets/8475089/17287429/34a6a8bc-5802-11e6-8534-76be6d1ca0f6.png)

**Comment by torkelo** [comment]
A snapshot only contains the visibile data at the time you made the snapshot :) You cannot change time range and expect more data, all the metric queries are removed etc

**Comment by pc10201** [comment]
How can I share the dashboards to another web system?
Can you give me advise?

**Comment by torkelo** [comment]
not sure what you mean "to another web system", you mean another Grafana server? you can export and import a dashboard

**Comment by pc10201** [comment]
I have another web dashboard system like wordpress.
I want a page to show the grafana dashboards in wordpress.

**Comment by torkelo** [comment]
you can use an iframe to embed one web application in another.

**Comment by pc10201** [comment]
Thanks.I  enable anonymous access and use an iframe.It works

**Comment by douglasg14b** [comment]
An ideal solution wold being able to have the snapshot update at a set interval, and the client viewing it just refreshes the view at an interval so you have a read-only dashboard without exposing access to the data source.

**Comment by nsayedqt** [comment]
I was thinking the same.

**Comment by torkelo** [comment]
nope, it a bit similar to asking why a still photo can't update it's image after it's been taken : )

**Comment by torkelo** [comment]
Yes, but that is very different from how snapshot works and their intended uses case. They are designed for to show a single time slice and store that for posterity, you can even push it to an external grafana server that is publicly available)
