### ISSUE TITLE
Can't create new organization

### ISSUE THREAD

**Issue by kelunik** [grafana/grafana#5698]
**I'm submitting a bug report.**

- What Grafana version are you using? → 3.1.0
- What datasource are you using? → Graphite
- What OS are you running grafana on? → Docker with official image
- What did you do? → Tried to create a new organization
- What was the expected result? → A visible and clickable "Create" button
- What happened instead? → No button at all

![image](https://cloud.githubusercontent.com/assets/2743004/17291640/77931aa6-57e5-11e6-8422-7b98188cb513.png)

I guess there should be a button to create a new organization. I'm logged in as root / admin user and could create a new user, but there's no button to create new orgs. I even tried to set `allow_org_create = true`, but it didn't change anything.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/17292431/465d477c-57ea-11e6-8f36-dde9c759aeb8.png)

**Comment by kelunik** [comment]
@torkelo Thanks! I think it still counts as UX bug then.

**Comment by torkelo** [comment]
@kelunik ??? why? because the admin section is missing this feature you consider it a bug?

**Comment by kelunik** [comment]
Because new users can be created using the admin panel, also edited and deleted. Organizations can be edited and deleted there as well. Just the creation of organizations is missing there.

Creation of them is at a very different place where it's hard to find if you just created a new user and want to create a new org for him.

It's not that the admin section is missing this feature, it's that the feature is at the wrong place, maybe missing at a second place. And yes, I consider this a UX bug.

**Comment by lovelaced** [comment]
I know this is closed but I actually agree with this. I was expecting new Orgs to be able to be created on the Org page, and actually found this issue while I was searching for where it actually was...

**Comment by MarcusCaepio** [comment]
Same here.
Had to google how to create a new organisation :D

**Comment by kelunik** [comment]
@torkelo Could you maybe reconsider reopening this issue as UX bug?

**Comment by torkelo** [comment]
In what world is this a bug?

**Comment by kelunik** [comment]
If multiple users just can't find a feature, that's clearly a bug to me. A user experience / user interface bug.

I tried to help making your product easier to use, but it seems like this help isn't needed, because your product is obviously already easy to use, at least from your viewpoint. I know that if you know where it is, it is easy to find again. Especially you, as a maintainer, know where it is. Maintainers are often so used to things, that they can't imagine how new users see things. Anyway, I already helped other users by opening this issue, others can at least find the information now if they try to search for it.

**Comment by torkelo** [comment]
Sorry, I understand that it is a ux problem. And the ux could be changed to make it easier to find.   But the fact that Grafana sever admin pages does not contain this feature is not a bug, but a missing feature, we have thousands of features that people find missing or needed. 

Making it easier to find a way to create new organizations is not a top priority as it's a extremely rare action, and multi organization setup is likely something we will try to discourage in the future and replace with more of a user group/team concept (not saying we will completely remove organization concept) 

Anyway I am sorry for the tone, just did not like the classification of this as a bug. Really appreciate you opening an issue and giving feedback into how we can make grafana better

**Comment by MarcusCaepio** [comment]
Will it possible to Filter Host views By AD groups? E.g i have ohne orga but few Departments, each Department only See its Server Filtered By its AD Group?

**Comment by kelunik** [comment]
> Sorry, I understand that it is a ux problem. And the ux could be changed to make it easier to find. But the fact that Grafana sever admin pages does not contain this feature is not a bug, but a missing feature, we have thousands of features that people find missing or needed.

Great! UX problem == UX bug to me. I don't care how exactly it will be made easier to find, the group admin page is just the place where I expected it to be. Dunno how Grafana handles UX issues / missing features, but I usually label them and leave them open until they're resolved. If they're low-priority, fine, add a `low-priority` label to it or add it to a `Defer / Nice to have` milestone. It's still October, adding `hacktoberfest` as a label might even result in a PR. :-)

**Comment by torkelo** [comment]
As I said we are planning to phase out organizations, the possibility to create new organizations is completely hidden in v4 by default, only enabled by configuration option. 

@MarcusCaepio filtering hosts by AD group requires integration with the tsdb, most support wildcard queries so no secure way for grafana to handle that, needs new security filters in the TSDB backend

**Comment by Ulrar** [comment]
Hi,

So what is the config setting to enable organizations again ? Kind of need something to control what our clients can or cannot see, organization aren't great for this but it's the only thing we found.

**Comment by torkelo** [comment]
enable orgs? They are enabled by default. There is a allow_org_create if you want regular users to be able to create orgs by themselves.

**Comment by Ulrar** [comment]
Hi,

Seems weird then, following your screenshot I just don't have the "New organization" button, just a couple of "Switch .." to other organizations I had created last year.
And I should have the rights to create org as I have the admin role.

**Comment by relrod** [comment]
Throwing in another vote for the original issue. The user page has a button to create a new user, I expected the org page to be similar. I was looking in the config, thinking I missed something to enable the creation of new orgs.

Throwing in a vote to get this fixed until orgs are deprecated officially.

**Comment by tisc0** [comment]
+1 :  had to google to find out how to create a company, blind as I am.
But for sure it's not a bug, "just" an ergonomic mistake IMHO.
Thanks for the project guyz!

**Comment by lafrech** [comment]
Just stumbled upon this thread while searching about organizations.

Is organization deprecation still planned? I saw a few relatively recent issue organization bugs or improvements, so I guess not.

**Comment by arturomp** [comment]
> Just stumbled upon this thread while searching about organizations.
> 
> Is organization deprecation still planned? I saw a few relatively recent issue organization bugs or improvements, so I guess not.

any news on this @torkelo?
