### ISSUE TITLE
[Feat]: Option to specify data source proxy timeout 

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#5699]
It seems there's a hidden timeout in the elasticsearch proxy.
The reason I'm suspecting this is that one of my dashoard works fine when using a timespan of 6 hours, but fails to display anything when asking e.g. for 12 hours. The error is the following:

```
502 Proxy Error

Proxy Error
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /api/datasources/proxy/1/_msearch.
Reason: Error reading from remote server
```

**Comment by torkelo** [comment]
do you get this after a while? looks like ES is returning an invalid response

**Comment by faxm0dem** [comment]
yes, after a while. I'm currently investigating to give you more info

**Comment by faxm0dem** [comment]
it also seems that the timeout is 120s

**Comment by faxm0dem** [comment]
@torkelo I'd love to give this a shot. Could you give me a few hints at where to start? *e.g.* where in the code is the proxy implemented, where are the plugin callbacks *etc.*

Cheers

**Comment by torkelo** [comment]
it depends where the timeout is, if it's in the request from the browser -> grafana http proxy of if its from http proxy -> ES

https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go

**Comment by faxm0dem** [comment]
see also #3168

**Comment by pparth** [comment]
+1

**Comment by RangerRick** [comment]
+1 we are running into this as well, because of the hard 30-second limit in the proxy: https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L30

We have some data sources that get their input from large, complicated elasticsearch queries that take longer than 30 seconds.

**Comment by amotl** [comment]
Hi there,

we also have been running into this recently at [Hiveeyes](https://hiveeyes.org/). The commit by @RangerRick above looks good to us. Do you see any chances to have this for the upcoming 5.1.0 release?

With kind regards,
Andreas.

**Comment by jdfalk** [comment]
Can we get the commit by @RangerRick reviewed and added? We are still having issues due to long running queries and this would solve that.

**Comment by RangerRick** [comment]
Just did an updated PR for it.  Not familiar with Go enough to be comfortable trying to write a test for it though.  Change is small enough that I would hope it doesn't matter, but if it needs a test, I'd need some help with that.
