### ISSUE TITLE
CloudWatch Logs: Log Group Empty in Panel dashboard or Grafana Explore

### ISSUE THREAD

**Issue by Brolywood** [grafana/grafana#56998]
What happened:

- Editing a log type panel with a CloudWatch Logs data source
- Set a log group
- Save the dashboard
- Close the dashboard
- Come back to the dashboard, edit the panel
- The "log group" field in the panel settings is empty and has to be filled out again
- This does not seem to affect fetching results, only the edit mode, so the log group is saved somewhere, just not displayed

- When you open a shared grafana explore link, the field log group is empty.

What you expected to happen:
Display the log group that's been saved with the panel when editing the panel

How to reproduce it (as minimally and precisely as possible):
See above

**Environment**:
- Grafana version: v9.1.8
- Data source type & version: Cloudwatch 5
- OS Grafana is installed on: Docker Image grafana/grafana-oss:9.1.8-ubuntu
- User OS & Browser: Windows11/MacOS Chrome / Edge Version 106.0.1370.4 / Firefox 105.0.3
- Grafana plugins: NA
- Others: NA

**Comment by danito8905** [comment]
same problem in version 9.1.2

**Comment by hristaki** [comment]
Example what happens in 9.2.0 (same problem)

![Kapture 2022-10-17 at 11 55 48](https://user-images.githubusercontent.com/4948421/196148770-9f633c63-b57e-49a0-a32c-f1698aacfd80.gif)

**Comment by iwysiu** [comment]
Hi @Brolywood ! Do you have more than 50 log groups? If so, we're looking at this bug in issue https://github.com/grafana/grafana/issues/55700

**Comment by nicolasarancibiago** [comment]
Hi @iwysiu. Yes, I do. Ok, I'll keep an eye on the issue https://github.com/grafana/grafana/issues/55700

Thank you!

**Comment by Brolywood** [comment]
Hi @iwysiu. Yes, I do. Ok, I'll keep an eye on the issue https://github.com/grafana/grafana/issues/55700

Thank you!

**Comment by iwysiu** [comment]
Hi, as an update, #55700 was closed and the bug fix will go out in the 9.2.2 patch release. Thanks for submitting this issue!
