### ISSUE TITLE
dashboard + filter set to All + influxdb breaks query

### ISSUE THREAD

**Issue by steenzout** [grafana/grafana#570]
Hello,

  I'm using Grafana with InfluxDB backend.
  I have a dashboard with a filter Server and a graph using a query that is defined like
```
select
  server, count(server)
from
  "series_name"
where
  time > now() - 15m and
  server = [[Server]]
group by time(1s), server order asc
```

  when I set the Server filter to a single value it works well.
the query being sent is something like:
```
select
  server, count(server)
from
  "series_name"
where
  time > now() - 15m and
  server = '192.168.1.2'
group by time(1s), server order asc
```

  when I set the Server filter to All it breaks the query.
```
select
  server, count(server)
from
  "series_name"
where
  time > now() - 15m and
  server = {'192.168.1.2', '192.168.1.3'}
group by time(1s), server order asc
```

I've tested what would be the correct query and it would be something like:
```
select
  server, count(server)
from
  "series_name"
where
  time > now() - 15m and
  server in ('192.168.1.2', '192.168.1.3')
group by time(1s), server order asc
```

  could the list of values from the filter be expanded to (element1, ..., elementN) instead of {element1, ..., elementN}?
with this I believe I can manipulate the query by hand and make it work since the expanded values would be correct.

  another option would be on the InfluxDB query builder to have a "in" option (which would imply that the value would always be surrounded by parenthesis) added to the =, =~, etc values?

cheers!

**Comment by torkelo** [comment]
I think this was solved a long time ago, will close
