### ISSUE TITLE
Can I change one of the bar from stacked bar on condition base?

### ISSUE THREAD

**Issue by digambarGitHub** [grafana/grafana#5700]
Can anyone have idea about this?
![1](https://cloud.githubusercontent.com/assets/8347565/17294351/ebd7f3cc-5813-11e6-94e9-44baf2f7c745.png)
please see above stacked graph, with 3 bars 1, 2, 3.

I want to change the color of bar, if any of the bar has value < 1mb.(i.e. red).
Basically I want to get notified that this bar has lower value than threshold.

I have 3 counters for each bar for each hour of the day.

Thanks in advance. :-)

**Comment by torkelo** [comment]
no this is not possible :/
