### ISSUE TITLE
Windows client install detects as generic trojan.

### ISSUE THREAD

**Issue by GRobersonUCBI** [grafana/grafana#5702]

**Comment by GRobersonUCBI** [comment]
The windows client installer "grafana-cli.exe" detects as a generic Trojan for multiple products.

The 3.1.1 (MD5 - 8f021319c90d2c023985717f9e764507) and the 3.0.4 (MD5 - 67bcfef332d9a3e11fc22cceaab18026) both seem to have the issue to varying degrees.

I did not see this issue reported elsewhere, and I'm having trouble finding hashes to compare other than the ones packaged with the install.

Is there a known issue with the code that could be generating these detections?

**Comment by torkelo** [comment]
it is built on appveyor using this script, it's likley a false positive. 
https://github.com/grafana/grafana/blob/master/appveyor.yml

**Comment by GRobersonUCBI** [comment]
I see some similar issues related to appveyor and similar products coming up in searches.
I'll submit it to our AV vendor and see if they can sort it out.

Thanks.
