### ISSUE TITLE
Alerting: Grafana should retry failed evaluations or support configuration of Error state

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#57025]
**What happened**:

Grafana should retry failed evaluations if the error is transient (i.e. network) or support configuration of Error state such that an alert must error for at least N seconds or minutes.  

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
Waiting to see if the datasources should be updated to fail less instead.

**Comment by chenlujjj** [comment]
What‘s the conclusion of this issue ?
