### ISSUE TITLE
Grafana unable to send alerts on email channels when alert rule passes and firing is true

### ISSUE THREAD

**Issue by sanasz91mdev** [grafana/grafana#57033]
**What happened**:

Grafana is  unable to send alerts to email channel. 
When i use TEST button on Notification Channel, alert is received on said email address.
But when i reproduce a scenario where alert rule is passed and an alert should fire. It shows that its in Alerting state . But alert Never goes to defined email addresses.

I checked logs and found following:

**Logs for case when alert rule is in firing state:**

`t=2022-10-15T15:16:30+0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Alert_Local_Prometheus id=11
t=2022-10-15T15:16:30+0500 lvl=dbug msg="Sending query" logger=tsdb.prometheus start=2022-10-15T10:11:30+0000 end=2022-10-15T10:16:30+0000 step=15s query=avg(prometheus_http_request_duration_seconds_sum/prometheus_http_request_duration_seconds_count)*1000
t=2022-10-15T15:16:30+0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=5.985 alertId=11 name=Alert_Local_Prometheus firing=true attemptID=1`

**Logs for case when i test notification channel:**

```
t=2022-10-15T15:38:21+0500 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email uid= isDefault=false
t=2022-10-15T15:38:21+0500 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[sana_sz91@hotmail.com] singleEmail=true

```

<img width="892" alt="alert1" src="https://user-images.githubusercontent.com/39674269/195982876-c7cbda45-ebc8-431c-bdc4-e886002e3fd8.png">

**Testing alert rule thats in firing state gives following details:**

<img width="960" alt="alert2_testruleJSON" src="https://user-images.githubusercontent.com/39674269/195982738-7e4089b0-e1ea-4591-b545-27b64d23b296.png">

**Alert is in Alerting State:**

<img width="939" alt="alert2_testrule" src="https://user-images.githubusercontent.com/39674269/195982772-e7f7c66d-36eb-4022-8439-fc969ea869b2.png">

**What you expected to happen**:

Since Email test channel notification is passed, i expect that when alert rule fires, notification should send but thats not case.

**How to reproduce it (as minimally and precisely as possible)**:

Configure any valid smtp settings that successfully fires test notification. and then configure the alert on metric

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: Prometheus
- Others:

**Comment by ashharrison90** [comment]
hi @sanasz91mdev 👋 

can you confirm whether this is legacy or unified alerting? if the former, have you tried with unified alerting or tried upgrading to a later version of grafana?

i can't replicate this locally but i am using unified alerting on a newer version of grafana, so it's possible the issue has already been fixed.

**Comment by sanasz91mdev** [comment]
> hi @sanasz91mdev 👋
> 
> can you confirm whether this is legacy or unified alerting? if the former, have you tried with unified alerting or tried upgrading to a later version of grafana?
> 
> i can't replicate this locally but i am using unified alerting on a newer version of grafana, so it's possible the issue has already been fixed.

Hi, I tried both on same version 8.3.1

Didn't try on latest grafana version though. You want me to try on latest version and get back ?

**Comment by ashharrison90** [comment]
@sanasz91mdev if that's possible then yes that would be great 👍

**Comment by elysiumHL** [comment]
We also encountered this issue in 9.2.2 with enable unified alerting.
The test notification sent successes any time, but the alert in firing state didn't send any notification.

**Comment by elysiumHL** [comment]
When we used the mimir-alertmanager, we found the alert sent correctly.
But another problem is we cannot check contact points and notification policies in grafana.
![a](https://user-images.githubusercontent.com/17973558/202342106-5de0413c-b1b7-4ae4-ad63-0b336c06c813.jpg)

**Comment by usmangt** [comment]
Hi @elysiumHL,

Are you still having this issue or is it resolved?

If you are still having this issue then kindly confirm the grafana version you are using and provide us with the grafana logs when this error appears.

**Comment by sanasz91mdev** [comment]
> Hi @elysiumHL,
> 
> Are you still having this issue or is it resolved?
> 
> If you are still having this issue then kindly confirm the grafana version you are using and provide us with the grafana logs when this error appears.

Yes last I checked on grafana 9.2 I was facing this issue

**Comment by usmangt** [comment]
Hi @sanasz91mdev,

Could you please provide us with the backend logs (the default location in Linux is `/var/log/grafana/grafana.log`) so that we can have more information about the error message?

**Comment by usmangt** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!

**Comment by erofgleb** [comment]
Grafana v9.0.4

It happens when I use the same alert for routing it to different channels. 

This works for me: if I want to send the same notification to telegram and email - I must create two alerts by the same metric. But I need to use different Groups for each of them (see on screens). If I set the same group I have only telegram notification. 

![image](https://github.com/grafana/grafana/assets/90589938/deb87bee-cd1b-4656-89dc-66ce3752b7c0)

![image](https://github.com/grafana/grafana/assets/90589938/91e72ed0-f8d1-4623-9278-69d5aaa4a07b)

![image](https://github.com/grafana/grafana/assets/90589938/32d46ad4-81ff-4adc-ae0b-35915b4b8b0b)

![image](https://github.com/grafana/grafana/assets/90589938/19c15ab1-1f47-471d-92ca-67a6d12fc7d6)

**Comment by andreinfilip** [comment]
I found a solution for your problem.
I had the same issue, and the solution is:

Do not create another specific routing, all you need to do is edit your only contact point and add a new contact point type like in the print attached, and the notification will be sent to multiple sources.
In my case i wanted to send an email and a slack webhook.

My grafana version is 9.2.0
Hope it helped!
[https://ibb.co/LRchZwM](url)
