### ISSUE TITLE
Admin controls for snapshot 'never' expiration

### ISSUE THREAD

**Issue by rbak** [grafana/grafana#5704]
- Feature request
  It would be helpful as an admin to be able to turn off the ability to create snapshots with no expiration.  We offer Grafana as part of our internal monitoring service, and we're concerned about users filling the database with snapshots that never expire.

**Comment by Lou-Cipher** [comment]
We would very much like to see this, too, as our security team will not allow us to use snapshots with no expiration.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
