### ISSUE TITLE
Plugins Catalog: fix the layout on smaller screens

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#57054]
**Related Slack thread:** https://raintank-corp.slack.com/archives/C01C4K8DETW/p1665593562141809

### What is the problem?

The Plugins Catalog layout is currently looking a bit odd on smaller screens.

![Image](https://user-images.githubusercontent.com/9974811/196110117-dc2b1ed9-fe94-4e74-8ea1-9765b198a5cb.png)

**Comment by sympatheticmoose** [comment]
There's only a small range where this view is present. It's valid feedback, but if we're going to address this its more likely to be part of a larger redesign. Closing for now.
