### ISSUE TITLE
Fix or document handling of non-datasource-specific-headers in backend-datasources

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#57065]
the alerting module currently sets the `FromAlert` and `X-Cache-Skip` values in `backend.QueryDataRequest.Headers` ,and, it seems, datasource-plugin are supposed to forward this using http-headers to the databases.

for a developer of a datasource-plugin it's not clear how to handle the situation:
- should they look for these specific values in `backend.QueryDataRequest.Headers`  and send them "out"? this seems brittle. if this is the way to go, we should document these special header values, and write some sample code to demonstrate the best practice
- should this happen somehow automatically by generic grafana code?

**Comment by marefr** [comment]
Guess one question is if `FromAlert` is something that developers of a datasource-plugin should need to think about in general. It feels like an edge/special case. It was introduced since CloudWatch plugin needed a way to know if a query was originating from alerting.

**Comment by gabor** [comment]
yes, i'd love to have something where i do not have to "hardcode" the header-names in the datasource plugin. some random ideas:
- add an `OutgoingHeaders` attribute to `ackend.QueryDataRequest`, and the expectation is that these should go "out".
- have an API that the datasource can call that returns the list of header-names they have to take and forward

also, we should not forget about external datasource-plugins here.

**Comment by gabor** [comment]
https://github.com/grafana/grafana/issues/41623 is maybe related

**Comment by marefr** [comment]
Some leftovers from #58646:
- Loki: 
  - has custom logic to only forward certain header for call resources https://github.com/grafana/grafana/blob/3c9ccd45121aeef5cac4ed0e5f1718bb33c436f1/pkg/tsdb/loki/loki.go#L123-L145
  - QueryData forwards all `QueryDataRequest.Headers` to outgoing HTTP requests https://github.com/grafana/grafana/blob/3c9ccd45121aeef5cac4ed0e5f1718bb33c436f1/pkg/tsdb/loki/loki.go#L194
- Prometheus:
  -  QueryData forwards all `QueryDataRequest.Headers` to outgoing HTTP requests https://github.com/grafana/grafana/blob/3c9ccd45121aeef5cac4ed0e5f1718bb33c436f1/pkg/tsdb/prometheus/querydata/request.go#L90
