### ISSUE TITLE
about node version when Building Grafana from source error 

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5706]
when i grunt ,running the task  "typescript:build" (typescript) task  ,i tryto use go1.5.1 and  node 4.11 or node 5.11 the error as below:
![image](https://cloud.githubusercontent.com/assets/18416187/17314137/b5d4b4a0-5894-11e6-83df-8d48bb006799.png)

**Comment by tonyC2016** [comment]
i use grafana version is 3.1.0

**Comment by torkelo** [comment]
seems to work for me with node 5.10,  how much ram do you have on the build machine?

**Comment by tonyC2016** [comment]
where can i look the ram on the build machine,the machine memoery is 8G

**Comment by torkelo** [comment]
ok, what OS are you building on?

**Comment by tonyC2016** [comment]
cents os 7

**Comment by torkelo** [comment]
https://github.com/Microsoft/TypeScript/issues/9052

**Comment by tonyC2016** [comment]
![image](https://cloud.githubusercontent.com/assets/18416187/17319421/10bb6956-58c0-11e6-8558-3e22da05caec.png)

**Comment by tonyC2016** [comment]
@torkelo  in grafana3.1.0  the package.json dependencies "typescript": "^1.7.5"  is it need the more high version?

**Comment by tonyC2016** [comment]
@torkelo  another question ,does grafana support parent-child Relationship
https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html
