### ISSUE TITLE
CI: Decide between `parallel` and `no-parallel` Drone agents 

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#57075]
**What happened**:

Currently, all of our Drone agents in OSS CI, use `no-parallel` linux runners, which is a pool of runners set up by the cloud platform which uses one pod per node.
While this was initially introduced to avoid caching issues between runners which used to exists between two runners that were running in the same pod, there are some steps that can run using the same filesystem without causing problems, now that our pipelines are split better and do certain things at a time.

------

Tasks: 

- [ ] Start using parallel runners again, in Grafana OSS https://github.com/grafana/grafana/pull/57077

**Comment by tleopold** [comment]
Try PR in CI sandbox to test out
