### ISSUE TITLE
loki: webui breaks the ability to type in code Log Browser

### ISSUE THREAD

**Issue by adamdecaf** [grafana/grafana#57096]
**Describe the bug**
I am trying to use the Web UI provided with Loki to query logs, but it seems to be breaking on whatever is typed. 

**To Reproduce**
1. Started Loki `v9.0.5 (1b595e434a)`
2. Type `{app!=""} != "query"`

**Expected behavior**
The query I type above should be represented in the input box. All I see is a completely broken input. The webui prevents me from fixing this and won't let me make a query. 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
![Screen Shot 2022-10-17 at 9 37 56 AM](https://user-images.githubusercontent.com/120951/196206950-a3bc1bc6-1035-48f8-a8d7-cded6248e314.png)

**Comment by dannykopping** [comment]
Transferred the issue to grafana/grafana because grafana/loki is for the Loki database only.

**Comment by ashharrison90** [comment]
hey @adamdecaf 👋 

this is a duplicate of https://github.com/grafana/grafana/issues/54535, which has been fixed in the latest version of Grafana or v9.0.9 if you need to stay on the 9.0.x branches for some reason

thanks! 😄
