### ISSUE TITLE
New version notification shown after installing the latest .deb version

### ISSUE THREAD

**Issue by itatabitovski** [grafana/grafana#5710]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708)
- What datasource are you using?
not relevant for this bug
- What OS are you running grafana on?
not relevant for this bug
- What did you do?
Installed the latest .deb package 3.1.1
go to admin and check the footer, there is notification for new version available

- What was the expected result?
I i install the latest version from grafana.org I should not see the notification for a new version.

- What happened instead?
the footer contains the new version Grafana v3.1.1 (commit: a4d2708) and a notification on the right that there is a new version available "New version available!"

**Comment by torkelo** [comment]
ah, thanks for informing me! forgot to updated latest.json

https://github.com/grafana/grafana/commit/01e5fd623b3e865f5716fc81f64e1f34b0e95e80

**Comment by itatabitovski** [comment]
Great, the notification is already gone, but you can still see the vertical bar "|". It looks nicer if the bar is also gone if there is no new version.
