### ISSUE TITLE
[Bug] : Templating is not correct with ElasticSearch datasource

### ISSUE THREAD

**Issue by solidz03** [grafana/grafana#5711]
Hi,
I discovered a problem with templating. 
My values in templating are not correct in comparison with datas in the table (please check images). 

![grafana-bug-3](https://cloud.githubusercontent.com/assets/20536224/17320796/9a9a5e6e-5895-11e6-94f6-14ec7cd61eda.PNG)
![grafana-bug-2](https://cloud.githubusercontent.com/assets/20536224/17320794/9a973dba-5895-11e6-85ff-292358211601.PNG)
![grafana-bug-1](https://cloud.githubusercontent.com/assets/20536224/17320795/9a9855c4-5895-11e6-8709-3bfa17c69495.PNG)

I think that Grafana split the data with this separator "**/**" in templating.

In templating, I have "**ethernet1**" and "**3**", "**44**", "**5**", "**6**". However, my data in ElasticSearch are: 
"**ethernet1/3**"
"**ethernet1/44**"
"**ethernet1/5**"
"**ethernet1/6**"

For example:
- When I select "**ethernet1**" AND/OR ("**3**" AND "**44**" AND "**5**" AND "**6**") in templating, I have "**ethernet1/3**", "**ethernet1/44**", "**ethernet1/5**", "**ethernet1/6**" in my table.
- When I select "**6**", I have "**ethernet1/6**" in my table.
- When I select "**3**" and "**44**", I have "**ethernet1/3**" AND "**ethernet1/44**" in my table

My data are correct in ElasticSearch: 

"_index" : "netflow-ES-2016.08.02",
"_type" : "netflow",
"_source" : {
	"timestamp" : "2016-08-02T08:23:12.000Z",
	"netflow" : {
		...
		"input_interface" : "**Ethernet1/44**",
		...
		},
"version" : "1",
"type" : "netflow"

This issue is just in templating terms.
I hope to be clear enough.

Thanks.

**Comment by torkelo** [comment]
The values 3,  44, 6 you get from the interface names are returned by ES from the terms query. This is how ES does terms by default on a analyzed field, remember ES is a text search database, so it will analyze sentences and extract sub words.  

To fix this you need to update your ES index mapping and disable analyzing on the input_interface field
