### ISSUE TITLE
Dashboard: General folder not showing in list to move dashboard

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#57111]
**What happened**:
The general folder is not in the folder list when the user wants to move a dashboard to another folder. It was commented on this [escalation](https://github.com/grafana/support-escalations/issues/4263).

**What you expected to happen**:
The general folder will be one of the `select` options.

**How to reproduce it (as minimally and precisely as possible)**:
1.- Go to the dashboard page.
2.- Click on the `checkbox` of a dashboard and then click on the `Move` button.
3.- Click on the select to display all the folders.

**Anything else we need to know?**:
It was triggered by this [PR](https://github.com/grafana/grafana/pull/54687).

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by eledobleefe** [comment]
Hi @soniaAguilarPeiron! We found this bug comes from this [PR](https://github.com/grafana/grafana/pull/54687) running `git bisect`. Could you know what change could have triggered it? Thanks in advance for your feedback 🙂

**Comment by soniaAguilarPeiron** [comment]
> 
sorry @eledobleefe , I missed this question!! 🙏
Do you still need more info about this?
