### ISSUE TITLE
Zoom and label precision

### ISSUE THREAD

**Issue by maykSVK** [grafana/grafana#5712]
I am not sure if this is bug, or just something, that I am missing. As you can see on the first image, label displays rounded numbers (even thought graph is showing them good)
![Image1](https://s31.postimg.org/fe5v9dynv/img1.png)

In the second picture is the same metric, but more zoomed and values are displayed with 2 decimal places.
![Image2](https://s31.postimg.org/9o5vjz4pn/img2.png)

Is it possible to set fixed precision in label no matter how much is graph zoomed out or zoomed in?

**Comment by torkelo** [comment]
The graph tries to optimize the number of decimals used depending on scale on the y axis (min / max etc),
