### ISSUE TITLE
Template variable not listing the latest 

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#5713]
I created a template variable in my dashboard from graphite

example query; `productName.application.*`

above query lists all my servers say **server-prod-06, server-prod-07** as expected.

Later say couple of months, we added two more servers. `(server-prod-04, server-prod-05)` . **_Still my template variable in the dashboards shows only the old list._**  Not getting the latest from the graphite. 

When i rebuilt the template variable, it is working as expected.  Am i missing anything here in terms of configuration?

**Comment by torkelo** [comment]
What is you template variable refresh option set to?

**Comment by yesoreyeram** [comment]
Oh my bad.. It was "Never"... :( . Now i changed to appropriate. Thanks @torkelo
