### ISSUE TITLE
upload json file not working for dashboards

### ISSUE THREAD

**Issue by Hsinin** [grafana/grafana#57138]
Grafana version: 9.2.0
same with https://github.com/grafana/grafana/issues/49359

**Comment by ashharrison90** [comment]
hi @Hsinin 👋 

can you confirm which browser you're running on? if it's chrome, updating to the latest version should fix the problem.

please let me know if that fixes your problem.

thanks! 🙌

**Comment by ashharrison90** [comment]
hi @Hsinin 👋 

i'm going to assume that fixed the problem - please reach out if that's not the case and we can reopen this.

thanks! 🙌

**Comment by Hsinin** [comment]
thanks! update to 106.0.5249.119(arm64) fix the problem
