### ISSUE TITLE
Incorrect handling of quotes in Mysql 

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#57152]
**What happened**:
Empty string surrounded by double single quotes `''` is escaped to single quote`'` incorrectly.
This bug is introduced in v9.2.0

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/4949937/196386267-50d474a3-71e2-4b26-b8e5-3fdf561df022.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: [v9.2.0 (c7eea48209)](https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-2-0/)
- Data source type & version: MySQL

**Comment by imReker** [comment]
{
  "id": 2,
  "gridPos": {
    "h": 14,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "table",
  "title": "Panel Title",
  "datasource": {
    "uid": "QTzGEw97z",
    "type": "mysql"
  },
  "pluginVersion": "9.2.0",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto",
        "inspect": false
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": []
  },
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": ""
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "QTzGEw97z"
      },
      "format": "table",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT\nLanguage\nFROM countrylanguage\nWHERE Language != ''",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "countrylanguage",
      "timeColumn": "time",
      "where": [],
      "editorMode": "code",
      "sql": {
        "columns": [
          {
            "type": "function",
            "parameters": []
          }
        ],
        "groupBy": [
          {
            "type": "groupBy",
            "property": {
              "type": "string"
            }
          }
        ],
        "limit": 50
      }
    }
  ]
}

**Comment by HenningRath** [comment]
Maybe a duplicate of https://github.com/grafana/grafana/issues/56784

**Comment by imReker** [comment]
> Maybe a duplicate of #56784

Seems like yes. I'll close this.
