### ISSUE TITLE
Graph disappears on clicking on the "Refresh dashboard" inside the non-first repeating row

### ISSUE THREAD

**Issue by wf1nder** [grafana/grafana#57159]
When you click on "Refresh dashboard", or change time window, the graph expanded in full screen ("view" mode) disappears if it is located in a repeating row, and if it is not in the first row.
The problem is reproduced only if the variable, on the basis of which rows is repeated, has the "Refresh" option specified to "On time range change". If you change it to "On dashboard load", the problem goes away.

Recorded a screencast: https://youtu.be/qa5ISR-h1_4

**Environment**:
- Grafana version: 9.1.6 and 9.2.0
- Data source type & version: Prometheus, we using VictoriaMetrics
- OS Grafana is installed on: Docker image, based on Alpine
- User OS & Browser: macOS Monterey, Firefox 105.0.3 (64-bit), Chromium 107.0.5253.0, Safari 16.0
- Grafana plugins: btplc-alarm-box-panel,vertamedia-clickhouse-datasource,vonage-status-panel,grafana-clock-panel,grafana-piechart-panel,grafana-worldmap-panel,jdbranham-diagram-panel,praj-ams-datasource,yesoreyeram-boomtable-panel

**Comment by day4me** [comment]
Hello guys.
I have a question regarding this re-drawing behavior of repeated panels:
This behavior has been introduced in 8.3.3 with this PR:https://github.com/grafana/grafana/pull/42828
After that, users created issues regarding this and has been considered a bug
(https://github.com/grafana/grafana/issues/43843, https://github.com/grafana/grafana/issues/44605)
In 8.3.4 the issue has been fixed, but only for the "On dashboard load" option.

So the question is: is this re-drawing behavior expected for "On time range change" in repeated panels or not?
And if it's not expected, will https://github.com/grafana/grafana/pull/58392 fix this?
