### ISSUE TITLE
Repeating row and repeating panel results in additional panels

### ISSUE THREAD

**Issue by jkv** [grafana/grafana#5715]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana v3.1.1 (commit: a4d2708)
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 14.04
- What did you do?
  Created a dashboard with 2 variables. One variable (app) is used in a repeating row. The other variable (region) is used as a repeating graph panel. When I change the selected "region" variable between the number of selected options to see multiple panels I get duplicate panels. This only happens when I have the repeating row set. If I turn off the repeating row then this issue goes away. Attached a sample dashboard for this issue.
- What was the expected result?
  If I have 3 regions selected I expect to see 3 panels in each row. If I have 1 region selected I expect to see 1 panel in each row.
- What happened instead?
  When I select 3 regions I end up seeing 4 panels: region1, region1+region2+region3, region2 and region3. If I change the selection back to just region1 I see 5 region1 panels. Turning off the repeating row and this doesn't happen.

[jkv repeating bug test.txt](https://github.com/grafana/grafana/files/398113/jkv.repeating.bug.test.txt)
<img width="1430" alt="step1 1 region 1 app no repeating row" src="https://cloud.githubusercontent.com/assets/385531/17344881/f50322b6-58c0-11e6-81b5-9150d58a68c0.png">
<img width="1421" alt="step2 3 regions 1 app no repeating row" src="https://cloud.githubusercontent.com/assets/385531/17344885/f7c09ace-58c0-11e6-8df4-553cd2b41cb4.png">
<img width="1364" alt="step3 turn on the repeating row" src="https://cloud.githubusercontent.com/assets/385531/17344888/f9b291de-58c0-11e6-9ee1-a92e1432badc.png">
<img width="1424" alt="step4 3 regions 1 app repeating row enabled" src="https://cloud.githubusercontent.com/assets/385531/17344889/fb61c298-58c0-11e6-920f-23a05c45de61.png">

**Comment by nerk01** [comment]
Also seeing the same issue in our install.  Repeating on a Row or a Graph is fine, when repeating both we get extra graphs based seemingly on the all glob.

**Comment by Sprakle** [comment]
Also reproducable on the Live Demo dashbord, at http://play.grafana.org/dashboard/db/graphite-panel-repeats

Open the row editor, enable repeat for "app", then toggle app variables on and off.

**Comment by torkelo** [comment]
Should be fixed in master
