### ISSUE TITLE
[Bug Report][Feature Request] Datasource Template Variable Doesn't Update

### ISSUE THREAD

**Issue by bmundt** [grafana/grafana#5716]
* **I'm submitting a ...**
- [x] Bug report
- [x] Feature request

Please include this information:
- What Grafana version are you using? 4.0.0-pre1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 7
- What did you do? Created datasource template variable
- What was the expected result? Datasource template variable would update value when other template variable changed.
- What happened instead? It only updated when interacting with that variable's editor.

I created a datasource template variable $ds, where the value is $otherVar.
$otherVar, is a query template variable. When changing the value of $otherVar from the dropdown list, it should update the value of $ds, however it does not, however if I have two query template variables, updating one will update the value of its dependent variable.

**Comment by torkelo** [comment]
> datasource template variable $ds, where value is $otherVar

What? a data source template variable has data source names as values.
