### ISSUE TITLE
update 9.2: Error SQL queries

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana#57164]
Hi, 
Since the last update we have an issue with MySQL queries wich have variables inside: 

SQL query failed with an error:

![image](https://user-images.githubusercontent.com/24936778/196363308-f04bcd29-5fdd-4b2d-b2a5-a46f7846b8b1.png)

The line of the error aim a grafana variable.
If we go into variables and run queries into variables

![image](https://user-images.githubusercontent.com/24936778/196363476-1eef15ec-3e62-4506-b1c1-863d7d1a937b.png)

then come back into the dashboard, queries works correctly.

![image](https://user-images.githubusercontent.com/24936778/196363620-0efb1af3-e823-4ceb-81c7-f4b88b79d75c.png)

But if we refresh the dashboard (with F5), SQL query error come back :/

It seems that all SQL queries in a dashboard wich have variables, and where the variables are SQL queries don't work anymore :(

It's like the sql query in the dashboard does not reconize the variable and think that is a syntax error ($variable)

**Comment by eglyn** [comment]
I just installed the 9.2.1 update which seems to fix the problem :) thanks!

**Comment by stanleyondrus** [comment]
I had the same problem on 9.2.0, and can confirm that 9.2.1 fixes the issue.

**Comment by roewan** [comment]
I also had the same SQL query problem in dashboard that have variables after upgrading to V9.2.0. Issue resolved after upgrading to V9.2.1. Thanks.
