### ISSUE TITLE
Traces - Spans less visible when using light UI theme

### ISSUE THREAD

**Issue by JBodkin-Amphora** [grafana/grafana#57198]
**What happened**:
The spans have changed colours and have become more difficult to tell apart when using the light theme. As per the screenshot from our system, there are two different coloured (brown vs purple) spans that are next to each other, but these are quite difficult to tell apart

![spans](https://user-images.githubusercontent.com/98747854/196461814-955032c7-1f32-4c23-a77a-d457e0886cd0.png)

**What you expected to happen**:
The previous colours were better suited to the light theme

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Grafana from 9.1.1 to 9.2.0

**Anything else we need to know?**:
There was a recent issue that was closed that may have contributed to this issue https://github.com/grafana/grafana/issues/54512
The change seems to prefer darker luminance colours on the light theme.

**Comment by CrypticSignal** [comment]
I have made @joey-grafana aware of this issue.
