### ISSUE TITLE
Exporting of axis metric microseconds is broken

### ISSUE THREAD

**Issue by JorritSalverda** [grafana/grafana#5719]
* **I'm submitting a ...**
Bug report

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
prometheus
- What OS are you running grafana on?
debian jessie
- What did you do?
exported a dashboard as json and imported it again
- What was the expected result?
the graph with microseconds should render
- What happened instead?
the graph with microseconds as unit didn't render

What happens is that the export has the following format

`"format": "Âµs"`

where it should actually be this

`"format": "µs"`

**Comment by torkelo** [comment]
seems to only affect the View JSON action and not the Save JSON file action

**Comment by alexanderzobnin** [comment]
Seems, it's browser-related issue. `vewJson()` function works proper, but some browsers show encoded json incorrectly.
```javascript
$scope.viewJson = function() {
    var clone = $scope.dashboard.getSaveModelClone();
    var html = angular.toJson(clone, true);
    var uri = "data:application/json," + encodeURIComponent(html);
    var newWindow = window.open(uri);
};
```
For example, try to paste this encoded json into browser address bar
```
data:application/json,%7B'unit'%3A%20'%C2%B5s'%7D
```
I see this works correctly only in Safari. But Chrome and Firefox shows `{'unit': 'Âµs'}`.
All these browsers tested on Mac OS X. Will try also on Linux.
Any ideas?

**Comment by DanCech** [comment]
That sounds a lot like a character encoding issue, try changing to:
```
var uri = "data:application/json;charset=utf-8," + encodeURIComponent(html);
```

**Comment by DanCech** [comment]
https://tools.ietf.org/html/rfc2397 is somewhat ambiguous, it says that "If <mediatype> is omitted, it defaults to text/plain;charset=US-ASCII." but doesn't specify the default character set for types other than `text/plain`.  It looks like Firefox & Chrome default to US-ASCII, while it seems Safari decides to use utf-8.

The utf-8 url above works in Chrome also, and this url produces the same output as without the charset specified (in both Chrome and Firefox):
```
data:application/json;charset=US-ASCII,%7B'unit'%3A%20'%C2%B5s'%7D
```
