### ISSUE TITLE
9.2 Grafana send too many INFO logs

### ISSUE THREAD

**Issue by Nemric** [grafana/grafana#57205]
**What happened**:
Since upgrade to v9.2 I receive a lot of logs 
```
logger=ngalert t=2022-10-18T17:34:00.001667795Z level=info msg="no changes detected. Skip updating"
logger=ngalert t=2022-10-18T17:33:50.00262745Z level=info msg="no changes detected. Skip updating"
logger=ngalert t=2022-10-18T17:33:40.002646615Z level=info msg="no changes detected. Skip updating"
logger=ngalert t=2022-10-18T17:33:30.00249408Z level=info msg="no changes detected. Skip updating"
logger=ngalert t=2022-10-18T17:33:20.002615789Z level=info msg="no changes detected. Skip updating"
```

**What you expected to happen**:
Don't being flooded by so many INFO logs

**How to reproduce it (as minimally and precisely as possible)**:
I don't reallt now how to reproduce, perhaps just need to have alerts ...

**Research**:
I've found that : https://github.com/grafana/grafana/commit/76ea0b15ae756b8d1d824498252052d718717203

**Environment**:
- Grafana version: 9.2
- Data source type & version: Prometheus:latest & loki:latest
- OS Grafana is installed on: Fedora CoreOS
- User OS & Browser: WIndows/firefox
- Grafana plugins: /
- Others: Grafana uses mariadb and is containerized

**Comment by ashharrison90** [comment]
@grafana/alerting-squad this might be intended. i can repro quite easily in main, every 10s i'm getting `no changes detected. Skip updating`. it does seem a bit spammy for an info message? 🤔

**Comment by kimboslice99** [comment]
@yuri-tceretian coming from google here, forgive any apparent ignorance, I see your PR was merged, but whats the fix here? A little confused

sick of logs being filled with nonsense messages
