### ISSUE TITLE
Extra parenthesis added for InfluxDB templating query

### ISSUE THREAD

**Issue by jonozzz** [grafana/grafana#5721]
* **I'm submitting a ...**
- [X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v4.0.0-pre1 (commit: 01e5fd6) 
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu
- What did you do?
Created a templated dashboard
- What was the expected result?
Correct query generated
- What happened instead?
Wrong query is being generated

![image](https://cloud.githubusercontent.com/assets/250343/17377271/daaa781c-596d-11e6-882d-e9790f3e8a9a.png)

The first query is handled correctly and all values returned as expected.
The second query contains a variable which gets converted to (XYZ) instead of XYZ, which doesn't cause InfluxDB to throw any error but no values are returned.

For $Harness = H01
SHOW TAG VALUES FROM "events" WITH KEY = "host" WHERE harness='$Harness'
Converts to:
SHOW TAG VALUES FROM "events" WITH KEY = "host" WHERE harness='(H01)'
Which is incorrect.
Should be:
SHOW TAG VALUES FROM "events" WITH KEY = "host" WHERE harness='H01'

**Comment by torkelo** [comment]
for query variables the templating engine will format as a regex to support multiple values so change harness='$Harness' to harness=~/$Harness/

**Comment by jonozzz** [comment]
Right, I just realized that a minute ago. That works like a charm!

Thanks

**Comment by shyamsingh7** [comment]
When I try to add a record containing parentheses, say, value ="version 1.2(M1)", it doesn't show up in DB. The whole record gets dropped, and no error thrown. How to add it to the db.
