### ISSUE TITLE
session_life_time has no effect on admin user

### ISSUE THREAD

**Issue by rayprill** [grafana/grafana#5723]
* **I'm submitting a ...**
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v3.0.4
- What datasource are you using? Graphite
- What OS are you running grafana on? Linux
- What did you do? Waited a few days with an admin user session opened. 
- What was the expected result?  For it to time out and close.  It never did.
- What happened instead?  Session still open even though session_life_time is set to the default 86400 (one day)

So is session_life_time supported for the admin user?  Or is it only other users?  Seems like you'd want the admin user to time out too since it is the most powerful user.

**Comment by torkelo** [comment]
there is a remember me cookie as well, set the grafana ini option `login_remember_days` 

https://github.com/grafana/grafana/blob/master/conf/sample.ini#L129

**Comment by rayprill** [comment]
I've tried pretty much everything, including login_remember_days = 1 or 0.  I cannot get sessions to timeout.

This worked OK on v.2.5
