### ISSUE TITLE
Starter plugin repos: archive them

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#57244]
The following plugin starter repos are deprecated as we are having our examples in the <> repo for some time.

Although the deprecation notice is added to all the repos, we should also archive them (make them read-only). As `@grafana/toolkit` still depends on them when scaffolding new plugins, let's only do this once the `plugin:create` command has been removed in favor of @grafana/create-plugin.

**Comment by tolzhabayev** [comment]
Closing, we agreed on keeping the deprecation message for now instead of archiving to still be able to make changes if really necessary. We will archive it later.
