### ISSUE TITLE
Multi search_base_dns to query two AD LDAP Forest

### ISSUE THREAD

**Issue by RedHat93** [grafana/grafana#5726]
I'm submitting a ...
- [ X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options]

Please include this information:
- Grafana Version:   Grafana v3.1.0-beta1
- What OS are you running grafana on? CentOS Linux release 7.2.1511 (Core)

- What did you do?
I configure my ldap.toml file to include:
host = _domain_controller_agency1_ _domain_controller_agency2_
port = 389
bind_dn = _user that exist in ActiveDirectory of agency 1_
search_filter = "(sAMAccountName=%s)"
search_base_dns = [ "_search_base_dns_agency1_", "_search_base_dns_agency2_" ]

Both domain are trusted:
If i open a Windows Client tool (with run as _user that exist in ActiveDirectory of agency 1_) i succesfully see user in _search_base_dns_agency2_

Unfortunately a login attempt, with an user that belong to _agency2_ AD, failed...

I activate the verbose_logging in ldap.toml (value set to "true") but i obtain only this line:
`t=2016-08-04T16:51:14+0200 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 10 \"Referral\": 0000202B: RefErr: DSID-0310082F, data 0, 1 access points\n\tref 1: '_agency2_domain_'\n"`

- What was the expected result?
I expect that GRAFANA try to lookup a user to login in both domain controller and use both search_base_dns.

Thanks you very much in advance,

If something is not clear, or you want more log and test, please tell us.

Have a nice day and good work!
p.s.: I really believe in GRAFANA functionality to better support all IT professionist, GREAT WORK AND THANKS FOR ALL! :)

**Comment by torkelo** [comment]
you can specify multiple servers, just duplicate the whole [[servers]] section

**Comment by RedHat93** [comment]
Hi Torkelo, 

thanks for all, we love you ;)

RH93
