### ISSUE TITLE
[Feature request] Make possible to pass refresh interval in dashboard query url

### ISSUE THREAD

**Issue by hc4** [grafana/grafana#5727]
Currently you can pass only from and to parameters in dashboard url.
http://metrics:3000/dashboard/db/test?**from**=now-1h&**to**=now

It will be very handy to also be able to pass refresh interval using query parameters, like:
http://metrics:3000/dashboard/db/kachalki?from=now-1h&to=now&refresh=10m

**Comment by jsjohnst** [comment]
**bump** 

I spent the last hour digging through code and docs trying to find this as I need it, but alas, no luck. Is this something you will never support, something I missed, any feedback other than a blow off?

**Comment by torkelo** [comment]
Dam, you are the rudest :)

**Comment by jsjohnst** [comment]
Apologies, you set me off by linking to a page which basically the only option was paying $7,200+/yr for something that seemed simple to just respond directly too.
