### ISSUE TITLE
v9.3: Grafana alert-edit: "Preview alerts" button is missing

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#57278]
The "Preview alerts" button has gone missing in 9.3. It was present in 9.2

See the screenshot - 9.2 is on the left, and 9.3 is on the right:
![image](https://user-images.githubusercontent.com/2903904/196698790-cb83e760-bfd7-4e4b-b4e7-fbe376c94854.png)

**Comment by samjewell** [comment]
Ok thanks @konrad147 

I now see a small summary appears:
- 1 `Firing`
- 1 firing, 0 normal

![image](https://user-images.githubusercontent.com/2903904/196704142-e7bfc51e-7e8c-4b63-b8f0-3904405ef25e.png)

I guess this isn't a bug, so I'm happy to close this.

But somehow I didn't find that UI/UX very helpful - I wanted to see some content appear close to the "Preview" button or below it. Or for that button to somehow point me towards the alert status.

**Comment by jantman** [comment]
Sorry to comment on a closed issue, but... the "Preview Alerts" button gave actual data, i.e. a table of the items, values, and labels. Is there any way to get this with the new "Preview" button?

**Comment by konrad147** [comment]
You can find the data in the expression box e.g. Take a look at B and C expressions. There is a list of labels, values and which of the time series triggers alerts
![image](https://user-images.githubusercontent.com/6293563/213163812-333c6e6b-efa9-4db6-ba7e-85ad1bb63264.png)

**Comment by akovov** [comment]
I'm still missing ValueString values on alert configuration page

**Comment by JohnnyQQQQ** [comment]
Closing this for now. Feel free to reopen it if you are still facing issues with the latest Grafana versions.
