### ISSUE TITLE
[Feature Request] Show Version Release Builds

### ISSUE THREAD

**Issue by nomade** [grafana/grafana#5730]
* **I'm submitting a ...**
- [ ] Bug report
- [ X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

We have a server with Grafana to monitor the performance of our application.
We have shell-scripts integrate with the REST interface.
This tool is fantastic for this purpose.

I wonder if the grafana has some way to present what versions are running in the environment.
Ex:
We installed the RC1 and then upgraded to RC2, RC3, RC4

I would look at the graphics and know the RC that was running at the time. Currently I have to note when the server was upgraded to compare correspondents graphics are each RC.

The script would:

VERSION_STR = $ (cat app / version.txt | "grep version_str =" | sed s / version_str = // g)
VERSION_NUMBER = $ (cat app / version.txt | "grep version_number =" | sed s / version_number = // g)

sendgrafana.sh Table_Version $VERSION_STR $VERSION_NUMBER $(date)

**Comment by torkelo** [comment]
you see version in footer on all non dashboard pages
