### ISSUE TITLE
[Feature Request] Support Elasticsearch moving_avg settings / predict

### ISSUE THREAD

**Issue by clhain** [grafana/grafana#5731]
- **I'm submitting a ...**
- [ ] Bug report
- [ X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Would be great to be able to specify "settings" values for different moving average models (e.g. holt_winters) in elasticsearch pipeline aggregations. Currently the only options presented are "window" and "model". Would be awesome to be able to specify the full range of settings values (or a free form "settings" field that could have arbitrary structured data passed to it).

"moving_avg":{
            "buckets_path": "the_sum",
            "window" : 30,
            "model" : "holt_winters",
            "settings" : {
                "type" : "mult",
                "alpha" : 0.5,
                "beta" : 0.5,
                "gamma" : 0.5,
                "period" : 7,
                "pad" : true
            }
        }

**Comment by marefr** [comment]
Fixed by #7154
