### ISSUE TITLE
(Cloudwatch) "All" or "Null" for Template Dimension

### ISSUE THREAD

**Issue by timtrinidad** [grafana/grafana#5732]
I have a cloudwatch graph showing the number of requests for an ELB. I would like to add a template that allows the specification of an AZ which is fairly easy - however, there's no easy way to quickly "remove" the dimension from the template.

For example, I would like the graph to show us-east-1a, us-east-1b, and then the graph with no AZ Dimension filter. However, selecting "All" doesn't show any data, and "null" or " " doesn't work either. Is there any way to quickly remove a dimension from a template so that the graph displayed does not use the dimension filter, short of going into the graph editor and removing the dimension each time?

**Comment by adrianhowchin** [comment]
+1, I am also seeing no data when I select "All". Is this supposed to work?

**Comment by mtanda** [comment]
The "All" meaning is selecting "All" template variable values, not "All" dimensions.
I think supporting this is very difficult because Grafana templating is text based feature.
