### ISSUE TITLE
Candlesticks' widths inconsistent in different screen (or browser) resolutions

### ISSUE THREAD

**Issue by Feiyang** [grafana/grafana#57321]
In the candlestick panel, the widths of bars (boxes) are inconsistent when displayed in different screen (or browser) resolutions. The panel looks all right in 1080p. However, they are too wide in low resolution and too slim in high resolution. 

**What happened**:
1) In my Macbook's default display, the bars are too slim
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/39115085/196861930-88a9fab7-973a-45b3-bf15-a6fcaff3e1c2.png">

2) After I set the browser's zoom level to 50%, the bars become wider than above
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/39115085/196862185-17ec865a-644b-40da-a65f-0f527ae3c28f.png">

3) When using another 1080p screen (100% zoom level), the panel is beautifully displayed (**Nice!**)
![image](https://user-images.githubusercontent.com/39115085/196862620-c3c75bdf-4e6a-4ff6-8f8e-ef23f508ba72.png)

**What you expected to happen**:
The panel should always look like the third figure.

**How to reproduce it (as minimally and precisely as possible)**:
Draw a candlestick panel and try to zoom in/out.

**Anything else we need to know?**:
Nope.

**Environment**:
- Grafana version: v9.1.6 (92461d8d1e)
- Data source type & version: JSON
- OS Grafana is installed on: Ubuntu
- User OS & Browser: macOS 12.4, Chrome 105.0.5195.125 (x86_64)
- Grafana plugins: Candlesticks v5.0.0
- Others:

**Comment by leeoniya** [comment]
probably forgetting a devicePixelRatio multiplier in there

**Comment by Feiyang** [comment]
Great! Thanks
