### ISSUE TITLE
When using decimal 0 and unit time seconds with metric data in seconds with decimals the Y axis loses granularity.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#57337]
The old graph panel did not display the decimal places
![image](https://user-images.githubusercontent.com/468940/196912750-90f26b89-a9f1-488a-b4b0-3b97ecbc4f95.png)

When decimal: 0 is used the Y-axis is only displaying whole seconds
![image](https://user-images.githubusercontent.com/468940/196912785-f32c0f1d-ee93-408c-95cc-a5484979cacd.png)

The expected behavior would be for the Y-axis to display ms without the decimals.

The unit data kilobytes has the same behavior, when decimal is set > 0 y axis shows up as byte when values are between 0-1000. But if decimal is set to 0 only 0 kb and 1 kb is displayed on the y axis.

**Comment by leeoniya** [comment]
related trickiness:

https://github.com/grafana/grafana/pull/52912
https://github.com/grafana/grafana/pull/54679
