### ISSUE TITLE
Provisioning AlertManager: Missing config option for "Receive Grafana Alerts"

### ISSUE THREAD

**Issue by siegenthalerroger** [grafana/grafana#57342]
**What happened**: I updated to Grafana 9.2 and the setting for "Receive Grafana Alerts" moved from "additional altermanagers" to being configured on the AlertManager Datasource.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/6848427/196917146-ac664149-8c8c-426d-b72e-a64230a6ffd3.png">

**What you expected to happen**: As our AlertManager Datasources are provisioned, their config can't be changed in the UI. Therefore I expected there to be a documented value for the `jsonData` of the provisioning file.

**How to reproduce it (as minimally and precisely as possible)**:
1. Try to provision an Alertmanager datasource that is set to "Receive Grafana Alerts"

**Anything else we need to know?**: The following setting is what I want to set to true.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/6848427/196917578-ae2aaca0-a127-459f-a237-b9fd30a828a1.png">

**Environment**:
- Grafana version: 9.2.0
- Data source type & version: AlertManager 5.0.0 (built-in)
- OS Grafana is installed on: Ubuntu on AKS
- User OS & Browser: Chrome
- Grafana plugins: only built-in
- Others:

https://github.com/grafana/grafana/issues/57342#tasklist-block-5619aa2e-5371-4f6f-a223-9337fab717a4

**Comment by ashharrison90** [comment]
hi @siegenthalerroger 👋 

looking at the code, i think you need to set `handleManagedGrafanaAlerts` in the jsonData to `true`.

if that solves your problem, can you please let me know then we can use this issue to make sure we add some documentation for this property correctly. thanks! 👍

**Comment by ashharrison90** [comment]
@siegenthalerroger ah, ok, time to get the alerting experts involved then 😅

**Comment by brendamuir** [comment]
@JohnnyQQQQ can you help here?

**Comment by ChristianOps** [comment]
Got it working in 9.3.0 by adding `handleGrafanaManagedAlerts: true` in jsonData

**Comment by siegenthalerroger** [comment]
This worked for us as well, however it's now reporting "pending" for each Alertmanager with no documentation what this means...
