### ISSUE TITLE
Grafana version: 9.1.2   elasticsearch datasource No options for versions below 7.10

### ISSUE THREAD

**Issue by dba-ws** [grafana/grafana#57347]
**What happened**:
elasticsearch datasource No options for versions below 7.10

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.2
- Data source type & version: elasticsearch 6.8.6
- OS Grafana is installed on: centos7.6
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
hi @dba-ws 👋 

i don't think there is any bug here, you can see the supported versions of elasticsearch on the docs page [here](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/)

this is based on elastic's own EOL disclaimer [here](https://www.elastic.co/support/eol#:~:text=Any%20version%20prior%20to%20the%20versions%20shown%20in%20the%20tables%20below%20is%20unsupported.)
