### ISSUE TITLE
[Bug]: Export CSV as columns,  uses wrong timestamps

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#5734]
- **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB 0.13.0
- What OS are you running grafana on? Ubuntu 14.04

---

Hello.  If I have >1 measurement (using the Influx terminology) on a graph, and the data for each measurement uses different timestamps, the resulting graph is correct, the "Export CSV (series as rows)" file is correct, but the "Export CSV (series as columns)" file has data with incorrect timestamps.

To reproduce, in this case using Influx:

```
> create database csv_test
> insert into csv_test.default measurementA value=3 1451606400000000000
> insert into csv_test.default measurementA value=4 1451606402000000000
> insert into csv_test.default measurementA value=3 1451606404000000000
> insert into csv_test.default measurementB value=91 1451606401000000000
> insert into csv_test.default measurementB value=92 1451606403000000000
```

Then create a simple dashboard with two sets of points:

```
SELECT "value" FROM "measurementA" WHERE $timeFilter
SELECT "value" FROM "measurementB" WHERE $timeFilter
```

<img width="1077" alt="graph" src="https://cloud.githubusercontent.com/assets/15203906/17423288/8b12c2d0-5a6e-11e6-900b-15d58f289973.png">

The graph is showing the points correctly.  If you click on "Export CSV (series as rows)" you get a file containing the following, which is the same data we inserted into Influx:

```
sep=;
Series;Time;Value
measurementA;2016-01-01T00:00:00.000Z;3
measurementA;2016-01-01T00:00:02.000Z;4
measurementA;2016-01-01T00:00:04.000Z;3
measurementB;2016-01-01T00:00:01.000Z;91
measurementB;2016-01-01T00:00:03.000Z;92
```

However, if you click on "Export CSV (series as columns)" you get a file containing the following, which you'll notice associates some data with the wrong timestamps:

```
sep=;
Time;measurementA;measurementB
2016-01-01T00:00:01.000Z;3;91
2016-01-01T00:00:03.000Z;4;92
2016-01-01T00:00:04.000Z;3;undefined
```

**Comment by nickpunt** [comment]
+1. Exporting as columns is the standard way to move this data around and far more useful for analysis than export as rows.

**Comment by bgruenefeld** [comment]
run in the same issue. 
Would be great if this bug could be fixed

**Comment by masthiren** [comment]
Pull request of fix - https://github.com/grafana/grafana/pull/9726

**Comment by w4kpm** [comment]
I still had the issue with this - for me, it turned out that the problem was having 'fill(none)' on the influx query - this caused a different number of items to be in the series data and causing things to get 'off' in the export - switching to 'fill(previous)' gave a much better result.

**Comment by jessabe** [comment]
Hej @w4kpm. As this issue is related to Grafana 3x and has potentially been fixed, I'm going to go ahead and close this. If this issue is still relevant in Grafana 6+, please feel free to open up another bug request/issue with us with relevant details, or comment here and we can re-open it. Cheers!
