### ISSUE TITLE
Timeseries: 100% stacking doesn't stack negative values

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#57352]
**What happened**:

Looking at the TimeSeries & BarChart Stacking - Stacked 100% panel looks different in current main and in 9.0.3.

**What you expected to happen**:

I think stacking should look like as in 9.0.3.

**How to reproduce it (as minimally and precisely as possible)**:

Take a look at TimeSeries & BarChart Stacking - Stacked 100% dev dashboard.

This is 9.0.3. 
![Screenshot 2022-10-20 at 14 06 32](https://user-images.githubusercontent.com/13729989/196945477-3d55328b-a022-4445-817d-f3bf02b5253a.png)

This is the same panel in current main.
<img width="1552" alt="Screenshot 2022-10-20 at 13 34 03" src="https://user-images.githubusercontent.com/13729989/196945559-a7692dab-d865-4975-b2fb-f6a0f42614f5.png">

**Comment by leeoniya** [comment]
i think it _is_ stackings, but the y axis range it's choosing does not include neg values. i had some commits that touched the axis ranging logic..maybe one of them affected this.

**Comment by leeoniya** [comment]
good catch, this one was easy to miss, how did you stumble upon it?

fix is in https://github.com/grafana/grafana/pull/57470
