### ISSUE TITLE
Logs: in mixed-datasource-mode, the histogram does not work

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#57354]
if you enable the mixed-datsource-mode, the histogram in explore-mode will always say histogram-not-supported.

the problem is that the code assumes there is a single datasource for all the queries, when:
- check for logs-volume support at:
    - https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L457
    - https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L520
- calculates teh logs-volume data at:
    - receives the histogram data at https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L579

in general, for every logs-query we have to use `query.datasource` to get to the real datasource for the given query using:

```typescript
import {getDatasourceSrv} from '@grafana/runtime';

const ds = await getDatasourceSrv().get(query.datasource);
```

(note that this is async)

an open question is,  what to do when you have two datasources with queries in explore-mode, where one has support for histograms and the other one does not have support for histograms.

**Comment by ivanahuckova** [comment]
This was fixed in https://github.com/grafana/grafana/issues/61546
