### ISSUE TITLE
Plugins: make it easier for plugins to access metadata

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#57358]
Sometimes we get asked by plugin authors how they can easily get hand of the current version of their plugin, or we see plugins implementing ways to share plugin metadata throughout their plugin using React context. Maybe it would be beneficial creating a simple hook (or set of hooks) that the plugins can use to access plugin metadata anywhere in their component tree while running inside Grafana.

**Comment by mckn** [comment]
Fixed by this PR: https://github.com/grafana/grafana/pull/77933
