### ISSUE TITLE
[Bug Report] TypeError: Cannot read property 'pageClass' of undefined

### ISSUE THREAD

**Issue by natemurthy** [grafana/grafana#5735]
I am running Grafana behind a proxy server (nginx). I have the following `nginx.conf`:

```
        location /grafana {
                proxy_pass    http://domain.com:3000/login;
                proxy_set_header   Host $host;
        }

        location /public {
                proxy_pass    http://domain.com:3000/public;
                proxy_set_header   Host $host;
        }
```

I initially tried following the instructions in this[ stackoverflow article](http://serverfault.com/questions/684709/how-to-proxy-grafana-with-nginx) but my server kept responding with `404` on nearly every single resource. With the config I have above, I get as far as:

![image](https://cloud.githubusercontent.com/assets/1788878/17428010/ff670bac-5a99-11e6-924e-802c40212233.png)

Is there anything else I need to configure on either of these servers to get the reverse proxy working properly?

**Comment by torkelo** [comment]
your nginx config is wrong, try this

```
location /grafana {
                proxy_pass    http://domain.com:3000/;
                proxy_set_header   Host $host;
        }
```

also set grafana ini config option `root_url` to the exact browser url you want to use (the nginx url), for example `http://your.nginx.com/grafana`

**Comment by natemurthy** [comment]
@torkelo your solution does not work. I still get 404 when I have my ngnix and grafana servers the way you have shown. can you please re-open this ticket?

**Comment by torkelo** [comment]
No, questions should not be opened on github :)

**Comment by natemurthy** [comment]
Ok, so where should I post my question? Is this more appropriate: https://groups.io/g/grafana?

**Comment by torkelo** [comment]
Yes, and with the nginx config I showed it works for me and everyone else who I have helped with nginx setup

**Comment by natemurthy** [comment]
One subtle difference between what you've shown and my setup is that I have SSL/TLS configured on my ngnix server, so my URL is prefixed with `https`. However, I don't have SSL/TLS on the grafana server itself. I configured ngnix like this:
```
location /grafana {
                proxy_pass    http://domain.com:3000;
                proxy_set_header   Host $host;
        }
```
and `grafana.ini` with:
```
root_url = https://proxy.server/grafana
```
And here are what my logs show:
```
tail -n 1 /var/log/nginx/access.log
<IP REMOVED> - - [06/Aug/2016:19:57:14 +0000] "GET /grafana HTTP/1.1" 404 19 "-" "<OS and BROWSER DATA REMOVED>"
```
```
tail -n 2 /var/log/grafana/grafana.log
t=2016-08-06T19:54:31+0000 lvl=info msg="Server Listening" logger=server address=0.0.0.0:3000 protocol=http subUrl=/grafana
t=2016-08-06T19:56:31+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/grafana status=404 remote_addr=172.31.18.59 time_ns=0 size=19
```
What else could be different from what I'm doing and what others are doing successfully?

**Comment by torkelo** [comment]
You are missing the trailing slash in the proxy pass line

**Comment by natemurthy** [comment]
I added the trailing slash; now I get a redirect but followed still by 404 responses:

```
<IP REMOVED> - - [07/Aug/2016:06:05:25 +0000] "GET /grafana HTTP/1.1" 302 37 "-" "<OS and BROWSER REMOVED>"
<IP REMOVED> - - [07/Aug/2016:06:05:25 +0000] "GET /grafana/login HTTP/1.1" 404 19 "-" "<OS and BROWSER REMOVED>"
<IP REMOVED> - - [07/Aug/2016:06:05:26 +0000] "GET /favicon.ico HTTP/1.1" 404 208 "https://proxy.server/grafana/login" "<OS and BROWSER REMOVED>"
```

**Comment by sagarmah** [comment]
@natemurthy did you get a solution for your issue??? I am facing a similar issue.

**Comment by natemurthy** [comment]
@sagarmah still do not have a working solution =/

**Comment by torkelo** [comment]
strange, many run grafana behind nginx without issue. 

```
location /grafana {
                proxy_pass    http://domain.com:3000/;
                proxy_set_header   Host $host;
        }
```

Did you add the trailing slash in the above?

**Comment by natemurthy** [comment]
@torkelo yes, even with the trailing slash, still having this issue

**Comment by aph-vsn** [comment]
Im getting this exact same error!! Was a solution ever found!

**Comment by natemurthy** [comment]
@torkelo Can we re-open this issue?

**Comment by torkelo** [comment]
Not sure, maybe open it in the mailing list, as it is more a support/question. most have no issues setting up nginx reverse proxy, so it just config issue that is causing your problem. Hard to say what though :(

But does not look like a bug (so no need to reopen the issue), but an nginx config issue

**Comment by hemsush** [comment]
@ Nayar, i want to access the dashboard via server side as accessing via javascript is not secure. In java ,i with the help of http url connection , i am trying to hit the page with authorization header . I am getting html page as response . But that is not rendering properly (Grafana-app tag is not rendered properly. Other elements are getting loaded due to erro r" cannot read property of ‘pageClass’ of undefined. "

                URL obj = new URL("grafana dashboard url);
		HttpURLConnection con = (HttpURLConnection) obj.openConnection();
		con.setRequestMethod("GET");
		con.setRequestProperty("X-WEBAUTH-USER", "username");
		int responseCode = con.getResponseCode();
		System.out.println("GET Response Code :: " + responseCode);
		if (responseCode == HttpURLConnection.HTTP_OK) { // success
			BufferedReader in = new BufferedReader(new InputStreamReader(
					con.getInputStream()));
			String inputLine;
			StringBuffer response = new StringBuffer();

			while ((inputLine = in.readLine()) != null) {
				response.append(inputLine);
			}
			in.close();

			// print result
			System.out.println(response.toString());
		} else {
			System.out.println("GET request not worked");
		}
