### ISSUE TITLE
Add a settings option to set the default editor (code/builder) option for Prometheus

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#57366]
### Description
Since we have Visual Query Builder in place for Prometheus we set it as default. So users are seeing it first instead of Code Editor. So that default behavior is not ideal for some users so they want an option to set what they will see. 
Actually, if they pick Code Editor once and left it this way when they will visit again they will see Code Editor. We remember their preference. But giving the option to modify the default is something they want to have in the end.

### Benefits
- Users will see they are being listened
- More personalization options
- Easy to implement such a feature

**Comment by gtk-grafana** [comment]
@itsmylife add some more detail here
