### ISSUE TITLE
Dependent template variables are not recalculated when repeating

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#5736]
# Bug report
- Grafana Version - v3.1.0
- Datasource - influx - v1.0.0-BETA3
- OS - Linux

## How to reproduce?
1. Create a template with dependent variables.
   variable: name
   query: SHOW TAG VALUES FROM "metadata" WITH KEY = name
   variable id
   query: SHOW TAG VALUES FROM "metadata" WITH KEY = id WHERE name = '$name'
2. Create a graph which makes use of the variables e.g. use $name in the graph title and id as a filter in the data series e.g.
   query: SELECT mean("value") FROM "mymetric" WHERE "id" =~ /^$id$/ AND $timeFilter GROUP BY time($interval) fill(0)
3. Select repeat on the higher level variable (name)

## What was the expected result?
The value of the dependent variable (id) should be re-calculated for each graph.

## What happened instead?
Only the value of the repeat on variable (name) varied resulting in two graphs with different titles but the same data.

**Comment by torkelo** [comment]
this is not how repeat / templating works, only the repeated variable is different for each repeated panel

**Comment by stevenh** [comment]
Is there no way to have calculated variables then?

**Comment by torkelo** [comment]
Not currently

**Comment by stevenh** [comment]
If you could give us some pointers to the area of the code which would need to be enhanced to facilitate that we'd be willing to have a crack at it if that's OK?
