### ISSUE TITLE
Canvas: Support data links

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#57376]
See https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-3924112

Figure out a way to integrate data links into canvas - community idea is to connect into the metric value element

Tricky part of this will be figuring out desired UX in a way that doesn't interfere with editing mode etc.

**Comment by nmarrs** [comment]
Addressed by #61648

**Comment by mgeriesa** [comment]
How can I use link in Canvas plugin. It doesn't work for me. When I use Button and click I didn't drill down to the other dashboard , it open the item for editing.

**Comment by mgeriesa** [comment]
Thanks for the update.
So in 9.4.0-beta we can configure for a metric a datalink and then click on
it and drill down to another URL page. Is that correct?
After googling I saw that someone suggested using the "Button Alpha" , so I
may have missed something.
What we need is : to click on a metric value and then it will open another
URL page.

I hope that 9.4.0-beta supports this.

Regards,
Manal
