### ISSUE TITLE
Missing documentation about specific behavior in Okta OAuth Configuration 

### ISSUE THREAD

**Issue by gauravprachchhak** [grafana/grafana#57384]
**What happened**: While following [this](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/) documentation, in the `allowed_groups` part. I discovered that if the group names have whitespace in them, the configuration does not work.

**What you expected to happen**: I hoped the spaces in the name worked, or this behavior was at least documented so that people are aware.

**How to reproduce it (as minimally and precisely as possible)**: Add any Okta groups that you are part of which have whitespace separating two words, e.g. `one two`. This will not work

I tried the following ways to see if I could escape the whitespace:
```ini
allowed_groups = one two, three four
allowed_groups = "one two, three four"
allowed_groups = 'one two, three four'
allowed_groups = "one two", "three four"
```

**Anything else we need to know?**: To make this work, I had to rename my Okta groups to have no whitespace. So the following worked:
```ini
allowed_groups = oneTwo, threeFour
```

**Environment**:
- Grafana version: v8.5.14 Enterprise
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS, Chrome / Firefox
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @gauravprachchhak,

Thanks for opening this issue.

I will forward it to the responsible team so that they can review it and update the documentation
