### ISSUE TITLE
Repeating row and repeating panel results in duplicates

### ISSUE THREAD

**Issue by beserg** [grafana/grafana#5738]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
 Grafana v3.1.1 (commit: a4d2708)

- What datasource are you using?
bug replicates with any datasource

- What did you do?
1) created templating variables (type custom)
$var1	1,2 (multi-value, Include All option)
$var2	a,b (multi-value)
2) added graph pannel with "$var1 $var2" title
3) turned on Repeat Panel by var1
4) turned on Repeat Panel by var2
5) selected var1=All , var2=a or var2=b

- What was the expected result?
graphs [ 1 a,  2 a ] or [ 1 b,   2 b ]

- What happened instead?
first iteration [1 b, 2 b] - correct
then selected a and got [1 a, All a, 2 a]
thet selected b and got [1 b, All b,All b, 2 b]
thet selected a and got [1 a,  All a, All a, All a, 2 a]
etc
![duplicates](https://cloud.githubusercontent.com/assets/3377445/17441434/b6bcae7a-5b39-11e6-926b-f75f82ec4f00.gif)

similar to #5715 

[templating bug_json.txt](https://github.com/grafana/grafana/files/404059/templating.bug_json.txt)

**Comment by torkelo** [comment]
yes, currently combining both panel and row repeats is now supported
https://github.com/grafana/grafana/issues/5715

**Comment by natecarlson** [comment]
@torkelo  

> yes, currently combining both panel and row repeats is now supported

Should that be 'not' supported?

**Comment by torkelo** [comment]
Yep
