### ISSUE TITLE
Loki: Add tests for public/app/plugins/datasource/loki/querybuilder/operations.ts

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#57396]
Currently we don't have unit tests for `operations.ts`. We should make sure this module has enough coverage, by asserting that `getOperationDefinitions()` returns a list of `QueryBuilderOperationDef[]`.

**Comment by gupsho** [comment]
I can take this one.

**Comment by matyax** [comment]
Thank you @gupsho but this has already been done as part of other closely related tasks.
