### ISSUE TITLE
Grafana Live over HTTP from Telegraf error on v9.2.1

### ISSUE THREAD

**Issue by badrbouslikhin** [grafana/grafana#57404]
**What happened**: After an upgrade of my docker image to latest today (9.2.1), Grafana Live push over HTTP (from Telegraf) crashes frequently.
```
telegraf     | 2022-10-21T08:32:47Z E! [agent] Error writing to outputs.http: Post "http://grafana:3000/api/live/push/telegraf": EOF
grafana      | server.go:3230: http: panic serving 172.18.0.4:54222: chain did not write HTTP response
grafana      | goroutine 2947 [running]:
grafana      | net/http.(*conn).serve.func1()
grafana      | 	/usr/local/go/src/net/http/server.go:1850 +0xbf
grafana      | panic({0x2ef9820, 0x3edea70})
grafana      | 	/usr/local/go/src/runtime/panic.go:890 +0x262
grafana      | github.com/grafana/grafana/pkg/web.(*Context).run(0xc001361a40)
grafana      | logger=context userId=0 orgId=1 uname= t=2022-10-21T08:32:47.449170047Z level=info msg="Request Completed" method=POST path=/api/live/push/telegraf status=0 remote_addr=172.18.0.4 time_ms=283 duration=283.450497ms size=0 referer= handler=/api/live/push/:streamId
grafana      | github.com/grafana/grafana/pkg/web.(*Router).ServeHTTP(0xc000d74d40, {0x3f08a98, 0xc001970540}, 0xc0014d7100)
grafana      | 	/drone/src/pkg/web/router.go:221 +0x192
grafana      | github.com/grafana/grafana/pkg/web.(*Macaron).ServeHTTP(0xc000d94960?, {0x3f08a98?, 0xc001970540?}, 0xc0014d7100?)
grafana      | 	/drone/src/pkg/web/macaron.go:161 +0xf1
grafana      | net/http.serverHandler.ServeHTTP({0x3effdd8?}, {0x3f08a98, 0xc001970540}, 0xc0014d7100)
grafana      | 	/usr/local/go/src/net/http/server.go:2947 +0x30c
grafana      | net/http.(*conn).serve(0xc001b22280, {0x3f0ae70, 0xc0012d4780})
grafana      | 	/usr/local/go/src/net/http/server.go:1991 +0x607
grafana      | created by net/http.(*Server).Serve
grafana      | 	/usr/local/go/src/net/http/server.go:3102 +0x4db

```
After a roll-back to the previous (grafana-oss v9.1.6 with image ID: 99169ddb2b0b), it works as expected.

**What you expected to happen**: No error on Telegraf push to Grafana's endpoint.

**How to reproduce it (as minimally and precisely as possible)**: send data on Grafana live v9.2.1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: Telegraf (data incoming from MQTT)
- OS Grafana is installed on: Synology DSM7
- User OS & Browser: macOS + Firefox
- Grafana plugins:
- Others:

**Comment by bob454522** [comment]
I can confirm that i too am seeing this,  after upgrade of (only) grafana from 9.1.1  to 9.2.1 , today,  i was seeing some issues on my dashboard which uses live panels (that get their data from another machine via telegraf http push -> grafana live).

(will roll back to 9.1.1 for now,  hopefully that is easy, have never had to go back on grafana)

over on the telegraf machine im seeing this:
`Oct 24 23:57:19 rukconfTOL telegraf[22475]: 2022-10-25T04:57:19Z E! [agent] Error writing to outputs.http: Post "http://172.17.69.40:3000/api/live/push/telegraf": EOF
Oct 24 23:57:23 rukconfTOL telegraf[22475]: 2022-10-25T04:57:23Z E! [agent] Error writing to outputs.http: Post "http://172.17.69.40:3000/api/live/push/telegraf": EOF
Oct 24 23:57:27 rukconfTOL telegraf[22475]: 2022-10-25T04:57:27Z E! [agent] Error writing to outputs.http: Post "http://172.17.69.40:3000/api/live/push/telegraf": EOF
Oct 24 23:57:31 rukconfTOL telegraf[22475]: 2022-10-25T04:57:31Z E! [agent] Error writing to outputs.http: Post "http://172.17.69.40:3000/api/live/push/telegraf": EOF
Oct 24 23:57:35 rukconfTOL telegraf[22475]: 2022-10-25T04:57:35Z E! [agent] Error writing to outputs.http: Post "http://172.17.69.40:3000/api/live/push/telegraf": EOF
`

and on my grafana machine im seeing this:
`Oct 24 23:55:21 grafana-server[550]: server.go:3230: http: panic serving 172.17.69.30:50476: chain did not write HTTP response
Oct 24 23:55:21 grafana-server[550]: goroutine 127468 [running]:
Oct 24 23:55:21 grafana-server[550]: net/http.(*conn).serve.func1()
Oct 24 23:55:21 grafana-server[550]: /usr/local/go/src/net/http/server.go:1850 +0xbf
Oct 24 23:55:21 grafana-server[550]: panic({0x32a2a40, 0x43ae6c0})
Oct 24 23:55:21 grafana-server[550]: /usr/local/go/src/runtime/panic.go:890 +0x262
Oct 24 23:55:21 grafana-server[550]: github.com/grafana/grafana/pkg/web.(*Context).run(0xc000e50040)
Oct 24 23:55:21 grafana-server[550]: /drone/src/pkg/web/context.go:50 +0xf4
Oct 24 23:55:21 grafana-server[550]: github.com/grafana/grafana/pkg/web.(*Router).Handle.func1({0x43db528, 0xc002230380}, 0x3b92854?, 0x2?)
Oct 24 23:55:21 grafana-server[550]: /drone/src/pkg/web/router.go:155 +0x8e
Oct 24 23:55:21 grafana-server[550]: github.com/grafana/grafana/pkg/web.(*Router).ServeHTTP(0xc0017a4640, {0x43db528, 0xc002230380}, 0xc00255e500)
Oct 24 23:55:21 grafana-server[550]: /drone/src/pkg/web/router.go:221 +0x192
Oct 24 23:55:21 grafana-server[550]: github.com/grafana/grafana/pkg/web.(*Macaron).ServeHTTP(0xc0017a6a20?, {0x43db528?, 0xc002230380?}, 0xc00255e500?)
Oct 24 23:55:21 grafana-server[550]: /drone/src/pkg/web/macaron.go:161 +0xf1
Oct 24 23:55:21 grafana-server[550]: net/http.serverHandler.ServeHTTP({0x43d2188?}, {0x43db528, 0xc002230380}, 0xc00255e500)
Oct 24 23:55:21 grafana-server[550]: /usr/local/go/src/net/http/server.go:2947 +0x30c
Oct 24 23:55:21 grafana-server[550]: net/http.(*conn).serve(0xc0011b8d20, {0x43dda68, 0xc0019f3ef0})
Oct 24 23:55:21 grafana-server[550]: /usr/local/go/src/net/http/server.go:1991 +0x607
Oct 24 23:55:21 grafana-server[550]: created by net/http.(*Server).Serve
Oct 24 23:55:21 grafana-server[550]: /usr/local/go/src/net/http/server.go:3102 +0x4db
`
(both are seperate VMs , no docker,  ubuntu20 on the telegraf,  debian10 on the grafana machine)
