### ISSUE TITLE
Feature request: Elasticsearch 5.x support

### ISSUE THREAD

**Issue by nickcarenza** [grafana/grafana#5740]
Opening issue to track progress and interest for ES 5.x support.

**Comment by danielcb** [comment]
Is there any timeline for this yet? Days, weeks, months? Just wondering if running from sources for now is worth the effort. :)

**Comment by bergquist** [comment]
@danielcb no timeline yet. Our current main focus is alerting and ux.

**Comment by megakid** [comment]
I am in the same position @danielcb after our recent Elastic 5.0 upgrade - Sounds like running from sources is the way to go for now.

**Comment by Spacefish** [comment]
I compiled this from source as well for now.
B.t.w. i had to run "grunt build" after you ran "npm build" to get the js files merged into one big boot.js.. Otherwise the site would load like 3-4 times longer as ~100 js files get downloaded one by one.

Alerting does not seem to work for ES (datasource elasticsearch not supported).

**Comment by ToddZhao** [comment]
waitting...

**Comment by timtofan** [comment]
+1

**Comment by defkev** [comment]
👍 

Currently the only thing holding me back from upgrading my deployments.

**Comment by sachavuk** [comment]
Hello,

Any news about this feature request ?

**Comment by nugusbayevkk** [comment]
today i had the same problem. 
Grafana team can you tell me, when are you plan fix this problem?
Thanks you a lot.
Today i migrated all data to ELK 5.0.2 from 2.3.4 and then after got next error:
 "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No search type for [count]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No search type for [count]"
  },
  "status": 400

**Comment by msteggink** [comment]
The latest nightly (grafana-4.1.0-1481284081pre1.x86_64.rpm) seems to work fine with ElasticSearch 5.0 (5.0.1-1)

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/4970

**Comment by amdei** [comment]
Hit exactly the same issue with Grafana v4.1.2  and ES 5.2.0

**Comment by panikgaul** [comment]
Have the issue with Grafana 4.1.1 or 4.1.2 and ES 5.1.1 or 5.2.1 (all version combinations).

Log from grafana by using an Elasticsearch datasource:

```
t=2017-02-20T08:49:49+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=X.X.X.X time_ms=188ns size=42
t=2017-02-20T08:49:49+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=X.X.X.X time_ms=21ns size=26
t=2017-02-20T08:50:48+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/_msearch status=403 remote_addr="X.X.X.X, Y.Y.Y.Y" time_ms=73ns size=0
t=2017-02-20T08:50:48+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/_msearch status=403 remote_addr="X.X.X.X, Y.Y.Y.Y" time_ms=513ns size=0
t=2017-02-20T08:50:56+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/_msearch status=403 remote_addr="X.X.X.X, Y.Y.Y.Y" time_ms=62ns size=0
```

**Comment by sujaldalia** [comment]
Any updates on this? I'm using Grafana 4.4.3-1 & Elasticsearch 5.5 and have same issues.

**Comment by torkelo** [comment]
what issues? We have only one other report of issues with 5.5,

**Comment by agxs** [comment]
@amdei @panikgaul @sujaldalia make sure to specify you're using ElasticSearch 5.x in the Data Source properties too.

![image](https://user-images.githubusercontent.com/804915/32789485-dbdd1fbc-c953-11e7-8ead-c8ec60fc77f5.png)

**Comment by ErolOZKAN-** [comment]
There is no Version in datasource properties menu @agxs

**Comment by msteggink** [comment]
@ErolOZKAN-  There sohuld be when configuring the data source. which Grafana version are you using?
