### ISSUE TITLE
Tempo: Implement a more concise UI for querying in Explore

### ISSUE THREAD

**Issue by CrypticSignal** [grafana/grafana#57407]
Currently, with the `traceqlEditor` feature flag enabled, the Tempo datasource in Explore has 5 `Query type` tabs:
`Search`
`TraceID`
`JSON File`
`Service Graph`
`TraceQL`

![Screenshot from 2022-11-23 15-56-47](https://user-images.githubusercontent.com/1014802/203578121-9e6628db-9877-4cf1-8bde-8f908d9c6c56.png)

This is a somewhat overwhelming for the user, and there are some changes that can be made. For example, the `TraceID` and `TraceQL` tabs could be merged.

This is something that has been discussed briefly internally (@grafana/observability-traces-and-profiling) as part of Q4 planning. The goal is essentially to provide a more concise UI for the user.

Few things to consider:
- As mentioned `TraceID` does not make sense as a separate query type. We can just figure out from the input that user inserted a traceId in a traceQL input a return the correct thing based on that.
✅ https://github.com/grafana/grafana/pull/60180#event-8025493118

- `Search` shows a simplified "builder like" UI capable of doing simple queries with some dropdowns. Could be also part of the traceQL query type as sort of `simple`/`raw` query switch.
- `JSON file` kinda stands out as it does not do a query, could be moved to some separate button?

**Comment by aocenas** [comment]
We probably need a bit of UX help with this to figure out a better layout for the query type.

**Comment by joey-grafana** [comment]
Draft PR https://github.com/grafana/grafana/pull/61237

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/grafana/pull/69402 where we moved the upload button to the right in the query editor (so it is no longer a tab of its own).

We have discussed merging the search and traceql tabs and will look into this more in the future.
