### ISSUE TITLE
Package update from yum repo should restart grafana-server

### ISSUE THREAD

**Issue by fdelapena** [grafana/grafana#5742]
* **I'm submitting a ...**

- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 7
- What did you do? upgrade package from yum
- What was the expected result? the update restarts the grafana-server to make it work properly
- What happened instead? after the package update the web interface fails to load until grafana-server gets restarted by hand

**Comment by phemmer** [comment]
Restarting services when packages are installed is not standard behavior for RPMs, or redhat/fedora based distros. Restarting the service would cause an interruption. And what if the config file were no longer compatible with the new version? The restart would fail and your service would be down.

Thus it's up to the admin to restart the service when they are ready.

**Comment by fdelapena** [comment]
That makes sense. However, unlike other services, every grafana package update breaks the web interface before any service restart. Could be a way to prevent this?

**Comment by phemmer** [comment]
Breaks it in what way? I just tried downgrading from 3.1.1 to 3.0.4 and back again, and didn't experience any issues with old processes still running.

**Comment by fdelapena** [comment]
> Breaks it in what way? I just tried downgrading from 3.1.1 to 3.0.4 and back again, and didn't experience any issues with old processes still running.

It gets reproduceable for me when opening the browser, otherwise the UI keeps working. I guess it was unable to load some assets after the full page refresh, maybe old ones weren't exist anymore and still being referred, as asset file names change every release. However I've not checked the reason properly, it is just an assumption.

**Comment by bergquist** [comment]
@fdelapena If you upgrade while having an active browser session you might get broken resources since Grafana is a single page application. A full refresh should solve fix it.

**Comment by torkelo** [comment]
I hear so many conflicting things about restart on upgrade or not, some say that Grafana packages are horribly broken due to not restarting the backend server on upgrade (Which leaves the frontend in a broken state if you try to do full page reload). But some say that restarting on upgrade is WRONG and not default standard behavior (you can change the default behavior by setting the RESTART_ON_UPGRADE env variable in the grafana default/sysconfig file

**Comment by fdelapena** [comment]
> you can change the default behavior by setting the RESTART_ON_UPGRADE env variable in the grafana default/sysconfig file

Oh, I didn't know about this setting, then I guess it fits for this need for both deb/rpm cases (`/etc/default/grafana` for deb based). I guess it should be enough to solve this issue for particular needs. Thank you!
