### ISSUE TITLE
alias works incorrectly when using template var in metrics

### ISSUE THREAD

**Issue by pkufranky** [grafana/grafana#5743]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? opentsdb
- What OS are you running grafana on? debian

When setting alias for metrics with template var, the legend displays incorrectly (all with the same name). See highlights in following picture

This can reproduce on 3.1.1 and older version

![grafana-bug](https://cloud.githubusercontent.com/assets/5346/17455577/b96c896e-5bee-11e6-9d08-dfa38185e749.jpg)

**Comment by torkelo** [comment]
This is an Open tsdb issue, fixed in latest opentsdb

**Comment by pkufranky** [comment]
3x. we will try

**Comment by torkelo** [comment]
After you upgrade OpenTSDB you need to specify your version in data sorce edit view

**Comment by pkufranky** [comment]
ok, 3x
