### ISSUE TITLE
Glue: Add various data links to test-datasource

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#57449]
### Background

It's hard to quickly demonstrate data links for various use cases without a cumbersome setup of different data sources. 

For development it's easy to use raw data frames input, but for demonstration purposes it'd be good to have something set up.

### Requirements ###

High level: _Provide consistent data links to logs/metrics/traces scenarios in test data source_

#### Technical details

There should be a scenario that allows showing data with multiple visualizations including:

* tables
* logs
* graphs
* service maps
* trace view

There should be a single scenario that would generate interconnected data. Data links should be set up in a way so it's possible to go through all visualizations just by clicking through data links:

<details><summary>Node Graph</summary>

```json
[
  {
    "meta": {
      "preferredVisualisationType": "nodeGraph"
    },
    "fields": [
      {
        "name": "id",
        "values": ["service", "database"]
      },
      {
        "name": "title",
        "values": ["service", "database"]
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "nodeGraph"
    },
    "fields": [
      {
        "name": "id",
        "values": ["1"]
      },
      {
        "name": "source",
        "values": ["service"]
      },
      {
        "name": "target",
        "values": ["database"]
      }
    ]
  }
]
```

</details>

<details><summary>Trace View</summary>

```json
[
  {
    "meta": {
      "preferredVisualisationType": "trace",
      "custom": {
        "traceFormat": "otlp"
      }
    },
    "fields": [
      {
        "name": "traceID",
        "values": ["1", "2"]
      },
      {
        "name": "spanID",
        "values": ["1", "2"]
      },
      {
        "name": "operationName",
        "values": ["parent", "child"]
      },
      {
        "name": "serviceName",
        "values": ["parentService", "childService"]
      },
      {
        "name": "parentSpanID",
        "values": ["", "1"]
      },
      {
        "name": "startTime",
        "values": [0, 2]
      },
      {
        "name": "duration",
        "values": [5, 2]
      }
    ]
  }
]
```
</details>

To add: Table, Logs Panel, Graph

Scenarios:

metric (graph) -> logs (logs) -> trace (trace)
metric (graph) -> table -> service map

#### To Do
- [ ] TBD

TBD

🚧 Outstanding questions

* Should we add tracking?

<details><summary>DoR checklist</summary>

- [ ] Should our squad work on it?  ***Yes, it will be beneficial to correlations***
- [ ] Why is it important?  ***It will help with testing, development and demonstration purposes.***
- [ ] Dependencies: ***No***
- [ ] Priority: ***Low***
- [ ] Functional requirements. ***TBD***
- [ ] Non-functional requirements . ***TBD***
- [ ] Documentation requirements. ***TBD***
- [ ] UX design / approval. ***N/A (no new UX/UI)***
- [ ] Technical design / approval.  ***TBD***
- [ ] How will the outcome value of the feature be measured? ***Tracking for test data?***
- [ ] Should we write a blog post about it?  ***No***
</details>

**Comment by L-M-K-B** [comment]
I had a look into this task and I have some questions:
1. Did I get it right that we can add a scenario to gdev-testdata for it?
2. There seems to be a bigger variety of data links that I was aware of. Can you please give some more details for: tables, graphs, service maps?
3. Is there some kind of documentation about how to create scenarios? If yes, where can I find it?

**Comment by ifrost** [comment]
> I had a look into this task and I have some questions:
> 
> 1. Did I get it right that we can add a scenario to gdev-testdata for it?

Yes. gdev-testdata is [a core plugin](https://github.com/grafana/grafana/tree/main/public/app/plugins/datasource/testdata) internally used for development. Scenarios are returned by [datasource's getScenarios() method](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/testdata/datasource.ts#L182) which pulls available scenarios [from the backend](https://github.com/grafana/grafana/blob/main/pkg/tsdb/testdatasource/scenarios.go). Some queries have special handlers in the frontend; others go through backend simulation by default.

We could have an "Observability" scenario that would allow generating logs, traces, and metrics for a single use-case, e.g. something like TNS.

> 2. There seems to be a bigger variety of data links that I was aware of. Can you please give some more details for: tables, graphs, service maps?

Tables: When a link is attached to a field, all cells in the column for that field become a link that can be clicked
Graph: Links can be accessed by clicking on the series, which shows a pop-up with the link
Service Map: Links can be accessed by clicking on the node.

> 3. Is there some kind of documentation about how to create scenarios? If yes, where can I find it?

The only documentation is on how to use it at https://grafana.com/docs/grafana/latest/datasources/testdata/, so the only way to find out is to follow existing patterns in the plugin.

**Comment by ifrost** [comment]
The full support for graphs (https://github.com/grafana/grafana/issues/58441), logs panel (https://github.com/grafana/grafana/issues/61782), exemplars (https://github.com/grafana/grafana/issues/59091), trace view (https://github.com/grafana/grafana/issues/59092) are not fully available yet so we can work on this later. For now I've created smaller task just to add something for testing in #62462.

**Comment by gelicia** [comment]
I feel like a decent diagram of how we could link together various test data scenarios goes like the following

![Untitled (15)](https://github.com/grafana/grafana/assets/1533128/7f1c27bb-5b24-472c-a470-cc5f38190669)

It requires the following work
1. Create a new scenario that has a few usernames with fake user data 
2. Change the Logs scenario to add more interconnected data
   1. Use usernames from fake user data
   2. Add traceId to tie to trace scenario
   3. Add service name and service instance id to tie to service maps
3. Add to service maps
   1. Add containerId, referenced by logs scenario
4. Create new graph scenario that has some numbers by containerId, referenced by logs scenario
5. Change trace view scenario
   1. Add container Id, to reference logs and new graph scenario

**Comment by gelicia** [comment]
We are moving this further forward with #69929.
