### ISSUE TITLE
Sorted stacked graph

### ISSUE THREAD

**Issue by superdump** [grafana/grafana#5744]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1

- What datasource are you using?
Prometheus and Elasticsearch

- What OS are you running grafana on?
Linux/Docker

- What did you do?
Queried container memory usage over time from Prometheus. Presented data as a graph of the memory usage with series split by containers.

- What was the expected result?
The series are ordered according to the value for the series at a specific point in time, so that, for example, it is visually easy to recognise the most significant contributor to memory usage.

- What happened instead?
Series were unordered and visual identification of most significant contributors to memory usage is more difficult.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
See above.

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
An example Prometheus container memory usage query could be:
`sum(container_memory_usage_bytes{hostname=~"^$hosts$",name=~".+"}) by (name)`

**Comment by superdump** [comment]
A suggested implementation detail could be to allow sorting by some point in time or some aggregate value per series for a time period. For example, for live graphs it may make sense to order the stacking by the current value. For historical graphs perhaps a mean or median is more sensible.

**Comment by torkelo** [comment]
you can do this in the metric query (for ES terms aggregation, specify order by)

**Comment by superdump** [comment]
I tried adding a sort() around the Prometheus query but it does not work. In promdash it works for the current values only in the console but not in the graph series.

I discussed this a bit with the Prometheus peeps and it felt like it made more sense to address in the visualisation tool as all the data is present and maybe there are different ways to do the ordering that make sense in different situations.

**Comment by torkelo** [comment]
Series order is the responsibility of the time series database, as it allows for things like top 5 series based on sort

**Comment by mtanda** [comment]
I check this little.
The behavior of Prometheus API "query" and "query_range" seems to be different.

"query" API: topk(5, foo) return metric list sorted by metric value
"query_range" API: topk(5, foo) return metric list sorted by label values (alphabetical order)

> Series order is the responsibility of the time series database

If follow this rule, the datasource plugin can't do anything.

**Comment by torkelo** [comment]
>If follow this rule, the datasource plugin can't do anything.

Explain?

**Comment by mtanda** [comment]
Ah sorry, not so much meaning.
The current datasource plugin doesn't do anything special now.
The datasource plugin know what the metrics (time series) has biggest value, so datasource plugin can sort the metrics, but it breaks the rule.

I agree with your opinion, I think the sort order is the responsibility of the time series database.

**Comment by ViViDboarder** [comment]
I'm still a bit confused as to where this fix should be. Prometheus to make query_range support sorting? Or grafana to use the query api rather than query_range?

I'm new to both, so I'm not sure why the two exist in the first place. Can anyone advise?

**Comment by discordianfish** [comment]
#7664 might solve this too. At least there is https://github.com/prometheus/prometheus/issues/586 pointing to this issue as a solution.
