### ISSUE TITLE
NodeGraph: Allow specifying an icon for node in node graph

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#57443]
Currently our service map shows just a simple circular nodes with some stats inside:

![node-graph-8-0](https://user-images.githubusercontent.com/1014802/197202427-33117800-eca0-4106-8a96-2596bef9cfb3.png)

This does not make it easy to visually recognize type of a node, like what kind of service it is like a database, message queue, app etc. For example some way other systems differentiate nodes:
![service_map_wide](https://user-images.githubusercontent.com/1014802/197202728-949ccef5-925d-4319-b98c-586e533a7e04.png)
![2-traceMap](https://user-images.githubusercontent.com/1014802/197202734-29cb82a9-a554-4c68-a406-9b4e28da2328.png)

There is a bit of research required about the actual implementation. We can just allow defining a name of an icon in a dataframe column from a predefined set of icons included in Grafana. Not sure if it's easily possible to add new icons from a data source plugin but I have a feeling that would be somewhat complex at this point.

It also probably a good guess that data source itself is the best place to know what kind of icon each node should have so data sources will have to implement some sort of matching based on data they have available to the set of predefined icons.

There is also a possibility to add a visualization configuration to match node name pattern to an icon manually tweaking or adding icons where they are not available from the data source, but would consider this a stretch goal and probably a later separate feature request.

**Comment by adrapereira** [comment]
Related: https://github.com/grafana/grafana/issues/54843

**Comment by aocenas** [comment]
Done in https://github.com/grafana/grafana/pull/60989
