### ISSUE TITLE
Cloudwatch plugin does not support linking to AWS Gov Cloud partition.

### ISSUE THREAD

**Issue by dutchhaag** [grafana/grafana#57473]
**What happened**:
When adding links via the CloudWatch plugin, the partition of the AWS account is not considered.
When the region is govcloud the partition needs to be updated from aws.amazon.com to amazonaws-us-gov.com.
Currently it gives a dead URL if you are in a gov-cloud region.

**What you expected to happen**:
Code would change the partition within the URL to match gov cloud when a gov cloud region is provided.
**How to reproduce it (as minimally and precisely as possible)**:
Set region to gov cloud on datasource. Create CW panel, add link. Receive incorrect URL.
**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/aws_url.ts#L15
Here is the line of code that needs to be updated.

**Environment**:
- Grafana version: [v9.2.1](https://github.com/grafana/grafana/releases/tag/v9.2.1)
- Data source type & version: CloudWatch latest
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac/Firefox
- Grafana plugins: Cloudwatch
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue @dutchhaag! 

I don't have gov cloud setup so can't test this myself, but url domain is definitely [hard coded](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/models/cloudwatch_query.go#L171) so I have no doubt this is broken. 

To be able to solve this, we'd need to start taking partition into consideration. We do that in the [x-ray plugin](https://github.com/grafana/x-ray-datasource/blob/a180f9dbeb8d502c942344795f0054f8c657f165/pkg/datasource/getRegions.go#L20-L27) so should be possible to do here too I think. Will discuss this with the team.

**Comment by sunker** [comment]
We should try and add support for aws china too.

**Comment by iwysiu** [comment]
Hi! I merged a commit to fix this, and it generates what I think are the correct links, however, I don't have access to other partitions to test that. Feel free to comment/reopen this issue if it still isn't working.
