### ISSUE TITLE
[Enhance] Improve drag and drop experiance (insert between panels) 

### ISSUE THREAD

**Issue by pkufranky** [grafana/grafana#5748]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? opentsdb
- What OS are you running grafana on? debian

See following picture, i can not drag the last panel to position 2 (between panel 1 and 2).  When dragging, i can only swap with panel 2, instead of inserting before panel 2.

![swap](https://cloud.githubusercontent.com/assets/5346/17461806/41c075dc-5ccb-11e6-9a0d-bf0c2066fab2.jpg)

**Comment by torkelo** [comment]
seems like the drag image is gone, you can still drag and drop panels but you do not see the drag panel being dragged

**Comment by torkelo** [comment]
The issue you describe is not a bug, it is how the drag mechanic has always worked, you need to make space before dragging if you want to move a panel to a new place (instead of switching place which is the default).

But I agree that this behavior is not very good.

**Comment by pkufranky** [comment]
> you need to make space before dragging
how can i do this?

**Comment by torkelo** [comment]
by reducing the width of a panel using the panel menu plus/minus or by dragging the last panel's right lower corner

**Comment by pkufranky** [comment]
After making space before dragging, i can not still insert between panels. The simplest case, i can move any panel to the end of the row if there are more than 5 panels in one row (which will wrap to display on more than one row)

**Comment by torkelo** [comment]
yes, you cannot only make space at the end of the row, and drag and drop there. I know it sucks, will be improved in 4.0 or 4.1

**Comment by pkufranky** [comment]
3x. look forward to it.
