### ISSUE TITLE
[bug] cannot display panel with . in the query for datasource prometheus

### ISSUE THREAD

**Issue by pkufranky** [grafana/grafana#5749]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? prometheus version 0.18.0 (revision: f12ebd6)
- What OS are you running grafana on? debian

After upgrading from 3.0.4 from 3.1.1,
metric can not display when var host contains '.'
the query example: mysql_global_status_threads_running{alias="$host"}

The reason is that 3.1.1 add \\ before . in the query

version 3.0.4:
mysql_global_status_threads_running{alias="10.4.xx.xx:3312"}

version 3.1.1:
mysql_global_status_threads_running{alias="10\\.3\\.xx\\.xx:3300"}

see following pictures
![v3.0.4](https://cloud.githubusercontent.com/assets/5346/17461959/18c5f158-5ccf-11e6-84a3-8a72bfe61880.jpg)
![v3.1.1](https://cloud.githubusercontent.com/assets/5346/17461961/201b5d3a-5ccf-11e6-8789-397b8c6b1aa8.jpg)

**Comment by torkelo** [comment]
Is the variable marked as supporting multi or all value? Then you must use regex operator in your prometheus query

**Comment by pkufranky** [comment]
no, the variable hasn't been marked as multi or all
It works in v3.0.4, so i think it is a regression?

**Comment by torkelo** [comment]
can you show variable options? either screenshot or json?

**Comment by pkufranky** [comment]
"templating": {
    "list": [
      {
        "allFormat": "glob",
        "auto": true,
        "auto_count": 200,
        "auto_min": "1s",
        "current": {
          "text": "auto",
          "value": "$__auto_interval"
        },
        "datasource": "Prometheus",
        "hide": 0,
        "includeAll": false,
        "label": "Interval",
        "multi": false,
        "multiFormat": "glob",
        "name": "interval",
        "options": [
          {
            "selected": true,
            "text": "auto",
            "value": "$__auto_interval"
          },
          {
            "selected": false,
            "text": "1s",
            "value": "1s"
          },
          {
            "selected": false,
            "text": "5s",
            "value": "5s"
          },
          {
            "selected": false,
            "text": "1m",
            "value": "1m"
          },
          {
            "selected": false,
            "text": "5m",
            "value": "5m"
          },
          {
            "selected": false,
            "text": "1h",
            "value": "1h"
          },
          {
            "selected": false,
            "text": "6h",
            "value": "6h"
          },
          {
            "selected": false,
            "text": "1d",
            "value": "1d"
          }
        ],
        "query": "1s,5s,1m,5m,1h,6h,1d",
        "refresh": 0,
        "type": "interval"
      },
      {
        "allFormat": "glob",
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "hide": 0,
        "includeAll": false,
        "label": "Host",
        "multi": false,
        "multiFormat": "regex values",
        "name": "host",
        "options": [],
        "query": "label_values(alias)",
        "refresh": 1,
        "refresh_on_load": false,
        "regex": "",
        "tagValuesQuery": "alias",
        "tagsQuery": "up",
        "type": "query",
        "useTags": false
      }
    ]
  },

**Comment by torkelo** [comment]
very strange, I fail to replicate it :( when having multi and includeAll false, there is no regex escaping of the value.

http://play.grafana.org/dashboard/db/prometheus-issue

**Comment by pkufranky** [comment]
i can't replicate it either now.

However, since = is used, why treating value as regex, even if multi values is marked?
