### ISSUE TITLE
Unable to clear Standard Options Min / Max Fields

### ISSUE THREAD

**Issue by Soon5** [grafana/grafana#57495]
**What happened**:
I removed the Standard Options => Min / Max Values to calculate the Values based on all values. After "Apply", the values were reverted. I can change the fields, but not clear them

**What you expected to happen**:
Have the fields cleared and the graph being calculated using the values

**How to reproduce it (as minimally and precisely as possible)**:
Create a new Panel, enter a value in Max, hit apply and try to clear it afterwards.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.8, but same issue in 9.2.1
- Data source type & version: doesn't matter, even an emtpy panel has the issue
- OS Grafana is installed on: Raspberry Pi OS 11
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: none
- Others: Using Docker Container

**Comment by amberin** [comment]
I have the same issue.

**Comment by leeoniya** [comment]
fixed in https://github.com/grafana/grafana/pull/57142, will be in 9.2.2 and 9.1.8
