### ISSUE TITLE
[Feat Req]: Support template variable in step field (Prometheus)

### ISSUE THREAD

**Issue by pkufranky** [grafana/grafana#5750]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? prometheus 0.18
- What OS are you running grafana on? debian

See the screenshot, when seting step as $interval, the panel doesn't display. After changing step to a fixed value 5m, it works.

In version 3.0.4, both work ($interval or 5m)

![p-no-interval](https://cloud.githubusercontent.com/assets/5346/17463749/8f1684c8-5cff-11e6-85a3-04f13aa1e605.jpg)
![p-with-interval](https://cloud.githubusercontent.com/assets/5346/17463750/8f5dd346-5cff-11e6-9ec2-b655e95feb9a.jpg)

Following is the exception (the value of var a is "$interval", which cause c to be null)
![p-exception](https://cloud.githubusercontent.com/assets/5346/17463771/33451514-5d00-11e6-9aa9-f8f6e390b299.jpg)
![p-source](https://cloud.githubusercontent.com/assets/5346/17463774/3bc5dd86-5d00-11e6-82e7-1ade2c435a8c.jpg)

**Comment by pkufranky** [comment]
Is it not a regression? template var in step works in version 3.0.4

**Comment by jaceklubzinski** [comment]
Very useful percona plugin for grafana https://grafana.net/plugins/percona-percona-app stops working because of that.

**Comment by mtanda** [comment]
Will release at 4.0.0.
https://github.com/grafana/grafana/pull/5839

**Comment by bergquist** [comment]
Closed by #5839
