### ISSUE TITLE
[DOCUMENTATION] Binding to port 80 outdated binary name

### ISSUE THREAD

**Issue by jblachly** [grafana/grafana#5751]
Documentation at [http://docs.grafana.org/installation/configuration/#http_port](http://docs.grafana.org/installation/configuration/#http_port) refers to outdated binary name in the `setcap` example.

It should read:
```
setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
```

**Comment by torkelo** [comment]
thanks for the heads up! fixed!
