### ISSUE TITLE
NodeGraph: Move out of beta

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#57511]
The node graph has been in beta state since it was first released and while we stabilised its feature set. There has been some time since its initial release and multiple users (external and internal) have asked why it is still in a beta state.

This is probably a relatively small task.

**Comment by aocenas** [comment]
This mostly means changing some labels and statuses so the beta badge isn't visible in the code and it's not in docs.

**Comment by aocenas** [comment]
I would like to wait with this until this is done though https://github.com/grafana/grafana/issues/57438
