### ISSUE TITLE
Loki log volume histogram missing log levels

### ISSUE THREAD

**Issue by patproj** [grafana/grafana#57523]
Hello,

we are facing and issue with the explore function on grafana version 9.x.
The Histogram is not showing a legend with log levels only with the logs tag, but the logs below the histogram are colored correct.
We are using the fluent-bit-plugin-loki from Grafana  to ship the log messages to grafana.
![grafana-loki-histogram](https://user-images.githubusercontent.com/108123567/197520528-c5c5cbe0-10cc-4d26-9186-17f68ca28839.png)
![histogram-log](https://user-images.githubusercontent.com/108123567/197520891-38936f1e-7ed8-41cf-9fac-6684f5237baa.png)

**What happened**:
We updated to the new version of Grafana and the histogram stopped working as we expect with our logs, the histogram is still working properly but the colors and the legend is not right.

**What you expected to happen**:
Incoming logs should be highlighted in the histogram as colors also the legend should contain the log levels

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: 
- OS Grafana is installed on: Loki 2.6.1
- User OS & Browser: Everywhere

**Comment by svennergr** [comment]
Hi @patproj,

Thanks for the issue, but that's the expected behaviour. 
More information can be found in that blog post: https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/#3-how-to-see-log-volume-with-levels

**Comment by eugenberend** [comment]
> Hi @patproj,
> 
> Thanks for the issue, but that's the expected behaviour. More information can be found in that blog post: https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/#3-how-to-see-log-volume-with-levels

There is almost no information about what is the structure of logs from this example
I have the same problem - after upgrade to v9.0 colors on histogram are missing (querying logs from the same app), so this is a bug. Adding `| logfmt` does not the trick.

**Comment by svennergr** [comment]
> There is almost no information about what is the structure of logs from this example
I have the same problem - after upgrade to v9.0 colors on histogram are missing (querying logs from the same app), so this is a bug. Adding | logfmt does not the trick.

Hi @eugenberend,

key to this should be that your logs contain a label called `level`, which is then used to determine the correct color.
