### ISSUE TITLE
LDAP user sync not done when using SSO proxy

### ISSUE THREAD

**Issue by larhauga** [grafana/grafana#5753]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request

Please include this information:
- What Grafana version are you using? 
   **3.1.1**
- What datasource are you using? 
   **Influxdb**
- What OS are you running grafana on? 
   **RHEL 7.2**
- What did you do? 
   **Configured grafana to use LDAP while adding username as X-Remote-User header in apache**
- What was the expected result?
**The expected result would be that new users would be created with the configured roles according to the ldap configuration.**
- What happened instead?
**New users (or existing users with updated role configuration) do not get the correct permissions, as there is no syncing of user information when doing SSO with X-Remote-User with LDAP users**

**Comment by torkelo** [comment]
LDAP is not integrated with Auth headers, they are two different ways to authenticate a user
