### ISSUE TITLE
Oauth: Display users external status in Org Users and lock basic role assignment

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#57539]
**Currently**

Admin users displays external auth labels
![image](https://user-images.githubusercontent.com/8071073/197559488-c13db0ee-535b-4e52-8ff9-a69ac845f828.png)

Org users does not display external auth labels

![image](https://user-images.githubusercontent.com/8071073/197559650-0889ebf7-7cf3-4b9d-8cc2-ee245bd8c413.png)

**Definition of Done**

- [ ] External auth label is displayed in org users table (before remove user button)
- [ ] Basic role assignments are locked in org users table for external users (under same rules and conditions as admin users profile page `public/app/features/admin/UserAdminPage.tsx`)

**Comment by kalleep** [comment]
Did a bit of digging for this one. There are two different endpoints used for these pages. One is owned by the user service and the other one is owned by the org service. 

The user service query requires the `global.users` scope in the access control filter and the org user query requires `users`.
For "global" users search there is a left join on the auth_info table to include the auth labels.

So to fix this either we do a similar join for the other query or we need to do a bit of refactoring to the AuthInfoService, maybe add a function to fetch auth info for a list of users

**Comment by Jguer** [comment]
> maybe add a function to fetch auth info for a list of users

That seems to be in line with how we handle AC metadata and how it should behave "in the future"
