### ISSUE TITLE
isNonNull errors out

### ISSUE THREAD

**Issue by expeepit** [grafana/grafana#5754]
* **I'm submitting a ...**
- [ X ] Question / Support request: **Please do not** open a github issue. 

Please help...

We have 40 servers which are used to process data.  These servers are always powered on, but not necessarily always "processing".  If the CPU utilization is above 10% or so we assume the server is processing something.  So we have a nice SingleStat in a Grafana dashboard which takes the CPU Idletime, and if that's below 90 (ie. 10% or more in use) is counted using the CountSeries function - and hence we see a single stat of how many of our processing nodes are currently actively processing.  Lovely.

What we would ideally like to do is have this count displayed over time, in a graph.  However, the CountSeries function does not appear to work in a graph, and so we stumbled across the isNonNull feature.  This looks ideal; for any CPU that is over 10% count as non-null and boom, we should have our graph.  But when we try to use isNonNull with ANYTHING we receive the Error in the top left of the graph, which says "Internal Server Error".

Here's our query (without the complexities of the 10% stuff):
isNonNull(*.*.*.Servers.*.process.test_process.processortime)

What are we doing wrong please !?

Many thanks.  

Please include this information:
- What Grafana version are you using? **3.1.1**
- What datasource are you using? **Graphite**
- What OS are you running grafana on? **Ubuntu**

**Comment by torkelo** [comment]
isNonNull is a graphite function that is only available in Graphite master / 1.0 pre release builds
