### ISSUE TITLE
How to add some texts below one panel?

### ISSUE THREAD

**Issue by howfree** [grafana/grafana#5755]
In order to make a panel clear, I want to add some text below a panel to describe its meaning.
but I cannot find the way to realize it.
I wonder whether Grafana 3,0 support it or not ?

thanks.

**Comment by bergquist** [comment]
Its not supported at the moments. 
But you can use text panels next to your graph panels. 

Panel description have been requested in https://github.com/grafana/grafana/issues/1168 

Please avoid asking questions on github. Use another support channel http://grafana.org/support
