### ISSUE TITLE
Scripted dashboard without login

### ISSUE THREAD

**Issue by wociscz** [grafana/grafana#5756]
Question:
Is there a solution to access scripted dashboards without login (as anonymous)?
When i'm logged in, scripted dashboards works, logout - not working.

Details: https://groups.io/g/grafana/topic/scripted_dashboard_without/2356857

Grafana: 3.1.1-1470047149
Influxdb: 0.13.0-1

**Comment by torkelo** [comment]
Is anonymous accessed enabled?

**Comment by wociscz** [comment]
As stated @ groups.io topic - anonymous enabled - i used it for regular dashboards. But .js give me "script error" and "unable to load datasource metadata" in grafana.log

**Comment by wociscz** [comment]
just made separate instance of grafana with only first organisation and enabled anonymous login to this first organisation. 
Everything working as expected - so workaround is separate grafana instance with only one org.

You should close this issue - this separation is even better for me (.js is for customer graphs).
Thanks
