### ISSUE TITLE
Metric Query Error: "metric request error: ValidationError: SELECT is not available in this region"

### ISSUE THREAD

**Issue by saamrezaei** [grafana/grafana#57562]
**What happened**:
Grabbing metrics from aws cloud watch. Was using metric search, now trying to convert that set of metric search requests into metric query request. 
After receiving this error a bunch I simplified the new metric query request into a 1:1 translation of a functional metric search request just to try and receive any output from the metric query. However, no luck and continously receive this error. 

"metric request error: \"ValidationError: SELECT is not available in this region\\n\\tstatus code: 400, request id: a993f93c-357e-4eb0-bbff-170c3370bd82\""

<img width="712" alt="image" src="https://user-images.githubusercontent.com/99278771/197604529-cf263ad2-9474-4595-a014-65e7beb200b3.png">

**What you expected to happen**:
Return a single metric. 

**How to reproduce it (as minimally and precisely as possible)**:
Convert a working metric search request into an equivalent metric request. 
Even trying simple examples pulled directly off of https://docs.aws.amazon.com/grafana/latest/userguide/CloudWatch-using-the-metric-query.html return same error. So I know its some form of configuration or maybe permissions error.  

Here is the functioning metric search configuration. 
![image](https://user-images.githubusercontent.com/99278771/197604981-72f0d574-819d-47a2-8f6f-97d348f53c5c.png)

And here is the 1:1 metric query result that is broken
![image](https://user-images.githubusercontent.com/99278771/197608311-261abb3a-a246-450e-a42b-41079a04866d.png)

**Anything else we need to know?**:
Just curious for some context around what this error means. I have changed the region to various different ones just in case, but been mainly testing with our default on which again works with metric search. 
Note: the region is a gov region, not sure if that makes a difference in terms of supported features.  

**Environment**:
- Grafana version: 8.5
- Data source type & version: AWS Cloud Watch
- OS Grafana is installed on:
- User OS & Browser: Safari
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue @saamrezaei! 

Not entirely sure, but I believe Metric Insights (corresponds to Metric Query in the Grafana plugin) should be available in all AWS regions now. Do you use a governmental cloud? To help us investigate this further, would you be able to share the panel json with us? To do that, click on the "Query inspector" above the editor, select "Json" tab, select source "Panel json" and then copy the json from the code editor. You may need to hide sensitive data before sharing it here. Thanks!

**Comment by sunker** [comment]
Thanks for details! 

I just spoke to our contact person at AWS and got clarification that Metric Insights (corresponds to Metrics Query in grafana cloudwatch plugin) is currently only available in commercial regions. I believe the goal is to make it available in gov clouds eventually, but don't now exactly when that will be. You can find more info [here](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-cloudwatch-metrics-insights/). 

I'm gonna close this issue now. Feel free to re-open if you feel the need to.
