### ISSUE TITLE
following upgrade to grafana 9.2.1 from 8.x table cells with data links do not center justify/alignment

### ISSUE THREAD

**Issue by robhamnett** [grafana/grafana#57572]
Following upgrade to grafana 9.2.1 from 8.x table cells/columns with data links do not center justify/alignment. Any cell in a table that has a data link will only align left even with explicit field overrides.

![image](https://user-images.githubusercontent.com/65688161/197659195-b54300ec-5410-45b0-b416-ed1edcac0dec.png)
![image](https://user-images.githubusercontent.com/65688161/197659268-19221972-c6cf-4c9b-a2dd-23dc7a60093a.png)
![image](https://user-images.githubusercontent.com/65688161/197659298-f82b95f7-d6fa-4a47-9314-805e5be6327d.png)

^^ these are all from the same instance, the behavior is consistent across multiple dashboards.

**Comment by itsjusth** [comment]
This issue is impacting new table panels built on version 9.3.2 also.
