### ISSUE TITLE
Display "Null" as null, and stacking don't play nicely

### ISSUE THREAD

**Issue by MatMeredith** [grafana/grafana#5757]
I have a set of nodes reporting a count of active calls and I want to draw a graph of total call count across all nodes, by stacking the per-node call counts.

![image](https://cloud.githubusercontent.com/assets/3448274/17510394/95692912-5e16-11e6-95f6-77aee829c9c3.png)

In my charts I really want to display Null as null rather than as zero.   This is important as it means I can distinguish between a node reporting a zero value and a node not reporting anything.   But if at a given time one node reports a NULL value, I lose visibility of all the values from my other nodes too -- I can see the values if I hover over the data point, but nothing is shown on the graph...   

![image](https://cloud.githubusercontent.com/assets/3448274/17510465/ed66d808-5e16-11e6-8b72-bdd3020aa430.png)

In this case I just want the node reporting the null value to disappear from the graph rather than all of the nodes...

**Comment by torkelo** [comment]
The stacking logic requires non null values,  null + 5 = undefined, if you want to see null values you will have to disable stacking or add another  graph

**Comment by MatMeredith** [comment]
I understand why the current behaviour is as it is, but do you not recognise the behaviour that's needed for this use case as valuable?   Would it be hard to have a version of stacking where we just don't show Null values and still show a stack of the non-Null values?

**Comment by torkelo** [comment]
Yes, of course.  Sorry forgot to link to the existing issue for that https://github.com/grafana/grafana/issues/2912
