### ISSUE TITLE
Strange value of payload in Alerting -> OnCall integration

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#57578]
In OnCall, I set up an integration with Grafana Alerting (using _Grafana Alerting_ integration type of course). Additionally I created a custom web hook contact point with an identical notification policy, for debugging purposes. I expect OnCall to receive the same updates (and at the same time) as my custom web hook, so that I can control what payload it receives.

Standard Grafana Alerting web hook contains general information about the update on the top level of JSON, as well as `alerts` array with detailed information about each particular alert:

[Redacted a bit:]
```
{
  "receiver": "Test web hook 1",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "TagName": "TAG_001",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
      },
      "annotations": {},
      "startsAt": "2022-10-24T17:42:00Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "https://xxx.grafana.net/alerting/grafana/yyy/view",
      "fingerprint": "5d40ab866f96ebde",
      "silenceURL": "https://xxx.grafana.net/alerting/silence/new?alertmanager=grafana&matcher=TagName%3DTAG_001&matcher=alertname%3DConsumptive&matcher=grafana_folder%3DAWARE",
      "dashboardURL": "",
      "panelURL": "",
      "valueString": "[ var='A' labels={TagName=TAG_001} value=3.669710585 ], [ var='B' labels={TagName=TAG_001} value=1 ]"
    },
    {
      "status": "resolved",
      "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
      },
      "annotations": {},
      "startsAt": "2022-10-24T17:35:00Z",
      "endsAt": "2022-10-24T17:44:00Z",
      "generatorURL": "https://xxx.grafana.net/alerting/grafana/yyy/view",
      "fingerprint": "bd5855532c57e057",
      "silenceURL": "https://xxx.grafana.net/alerting/silence/new?alertmanager=grafana&matcher=TagName%3DTAG_002&matcher=alertname%3DConsumptive&matcher=grafana_folder%3DAWARE",
      "dashboardURL": "",
      "panelURL": "",
      "valueString": "[ var='A' labels={TagName=TAG_002} value=0.06126459 ], [ var='B' labels={TagName=TAG_002} value=0 ]"
    }
  ],
  "groupLabels": {},
  "commonLabels": {
    "alertname": "Consumptive",
    "grafana_folder": "AWARE"
  },
  "commonAnnotations": {},
  "externalURL": "https://xxx.grafana.net/",
  "version": "1",
  "groupKey": "{}/{grafana_folder=\"AWARE\"}:{}",
  "truncatedAlerts": 0,
  "orgId": 1,
  "title": "[FIRING:1, RESOLVED:1]  (Consumptive)",
  "state": "alerting",
  "message": "Some big message..."
}
```

My rule defines a two-dimensional alert. One individual alert is firing and another one was just resolved. Everything looks good, no questions here.

Now I go to my alert group in OnCall, enter the triggered alert and trying to adjust the message template. I enter `{{ payload | tojson_pretty }}` as the message template to view all available options. it prints this (redacted):

```
{
"annotations": {},
"dashboardURL": "",
"endsAt": "0001-01-01T00:00:00Z",
"fingerprint": "bd5855532c57e057",
"generatorURL": "https://xxx.grafana.net/alerting/grafana/yyy/view",
"labels": {
"TagName": "TAG_002",
"alertname": "Consumptive...",
"grafana_folder": "AWARE"
},
"panelURL": "",
"silenceURL": "https://xxx.grafana.net/alerting/silence/new?alertmanager=grafana&matcher=TagName%3DTAG_002&matcher=alertname%3DConsumptivedf&matcher=grafana_folder%3DAWARE",
"startsAt": "2022-10-24T17:35:00Z",
"status": "resolved",
"valueString": "[ var='A' labels={TagName=TAG_002} value=0.06126459 ], [ var='B' labels={TagName=TAG_002} value=0 ]"
}
```

Instead of having the entire payload as sent by the web hook, it seems to pick a random element from `alerts` array. I say random because I saw instances when it was both first and second element. Maybe there is a rule though.

I think the behavior is bad and unexpected due to the following reasons:

1. It provides more restricted capabilities for message templating. With other alerting contact points (e.g. email, OpsGenie), I have an option to generate the Title and Message text based on the entire content of the payload, e.g. access top-level keys and iterate through alerts (`.Alerts.Firing` and `.Alerts.Resolved`). If the integration is based on a web hook (and I like that as it is potentially more advanced), the templating capabilities are expected to be similar on the receiving side, but they are not.
2. It causes misleading situations like this:
![image](https://user-images.githubusercontent.com/4903007/197657758-a55a859e-6885-4273-ba63-413cd63d8afd.png)
one alert is resolved but another one is still firing (so the whole rule), but the status of the alert group has "resolved:"
![image](https://user-images.githubusercontent.com/4903007/197657962-6fbd4420-5479-4cff-b870-7320eaa50b5e.png)
3. _Resolve Condition_ must be determined on the top-level `status` element of the web hook payload. It cannot be determined based on individual alert entries. It renders the feature useless.
4. Same for _Acknowledge Condition_.

I realize that I might be missing something and ask you to correct me if I am wrong. The documentation I used: https://grafana.com/docs/oncall/latest/integrations/create-custom-templates/

**Environment**: Alerting, OnCall
- Grafana version: Cloud
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Chrome
- Grafana plugins: N/A

**Comment by greatvovan** [comment]
I think the labeled area must be OnCall. Alerting part seems fine to me.

**Comment by mderynck** [comment]
Webhook and Grafana Alerting integration behave differently.  As Grafana Alerting expects an alerts array element it is able to apply the template rules to each alert in the array individually whereas the webhook can contain anything so we do not parse the array of alerts there further.

The main reason for Grafana Alerting to process individual elements in the array is for the purpose of grouping.  The default grouping criteria is the `alertname` but in the example above if you were to change the grouping criteria to be `TagName` sending that one request would result in two alert groups (Allowing for different alerts to be routed to different escalation chains).  Since these objects are processed individually the array element is the payload being considered in the template rather than the entire alert group.  Being able to access all alerts in a group from the template would be useful for rendering some aggregated info in cases like this, it would be a good feature request.

For the alert payload that is displayed at the top of the alert group, this should be "last" alert payload received but I am unsure about the order if those alerts come in an array in one request.  Also note the status displayed here is the status indicated in that last payload not of the alert group as a whole.  The alert group in the screenshot (#21) has the status acknowledged and is not resolved.

With the Grafana Alerting integration for the group to auto-resolve the resolve condition is applied to each alert in the array.  Each firing message must have a corresponding resolved message with a matching label set for the alert group as a whole to be considered resolved.  For this to happen here it would need to receive a `status=resolved` where the labels had `TagName=TAG_001`

**Comment by greatvovan** [comment]
Now I see the point. Thank you for writing that @mderynck.

The problem however is the default preset that groups alerts based on `alertname` tag. If we change that to some meaningful grouping key based on individual alert data, we can have reassemble flow of alerts based on escalation needs. I realized the idea only after your post though.

I have a feeling however that something is not quite right. In the screenshot `#21` please look at the **Status** field of the templated message, it says "resolved". The templated is defined as follows:

```
{{- payload.message }}
{%- if "status" in payload %}
**Status**: {{ payload.status }}
{% endif -%}
**Labels:** {% for k, v in payload["labels"].items() %}
*{{ k }}*: {{ v }}{% endfor %}
**Annotations:** 
{%- for k, v in payload.get("annotations", {}).items() %}
{#- render annotation as markdown url if it starts with http #}
*{{ k }}*: {% if v.startswith("http") %} [here]({{v}}){% else %} {{v}} {% endif -%}
{% endfor %}
```

(Basically it is the default template). Note, that **Status** value comes from `{{ payload.status }}`, meaning the effective value is "resolved". At the same time, Resolve Conditions is defined as

```
{{ payload.get("status", "") == "resolved" }}
```

So the entire alert group must have been marked as resolved automatically, but it did not happen. Do you have an idea why? In the (original) payload preceding to that, there were two alerts, one firing, and one resolved. Not sure how it work so that `payload.status` works in one place and does not work in another.

**Comment by greatvovan** [comment]
> Being able to access all alerts in a group from the template would be useful for rendering some aggregated info in cases like this, it would be a good feature request.

A workaround for that seems using custom Webhook integration, where `payload` means the original payload with `alerts` as array. I found it is not hard at all to setup integration with Grafana Alerting using Webhook integration type (as soon as you learn how to write Jinja templates).

**Comment by mderynck** [comment]
Using the webhook integration is a workaround for accessing the entire payload together.

I would need to see the other 9 grouped alerts to be certain of the status for `#21`.
The Grafana Alerting integration will not use the top level status field since it cannot represent mixed states, for example in the request in the first post there is one firing alert and one resolved alert in the alerts array, the top level status element is "firing" but that doesn't tell the whole story.  The payload being processed by the templates is only each of the elements in the alerts array.

What is confusing about the current presentation is that if you send the request above to Grafana Alerting integration you will see 3 status fields shown but none of them will be the top level status, it will select one of the alerts as "most recent" and present that above the grouped alerts.  The reason for doing this is if you have a large number of grouped alerts you can see the latest without having to expand and scroll.

Since Grafana Alerting integration ignores the top level status it will process each alert in the alerts array and will auto resolve the alert group when the alerts inside the array meet the resolve condition for each unique set of labels.  If auto resolve is enabled and the alert group has not resolved it is likely waiting to receive a resolved message matching a label combination that is still firing. Using the request above as an example if it was sent on its own it would be waiting for a request where the alerts array had an element looking with:
```
"status": "resolved",
"labels": {
  "TagName": "TAG_001",
  "alertname": "Consumptive",
  "grafana_folder": "AWARE"
}
```

**Comment by greatvovan** [comment]
> The Grafana Alerting integration will not use the top level status field since it cannot represent mixed states, for example in the request in the first post there is one firing alert and one resolved alert in the alerts array, the top level status element is "firing" but that doesn't tell the whole story.

Yes, this is understood and expected after the explanation you provided on Oct 28.

> I would need to see the other 9 grouped alerts to be certain of the status for #21.

Here you are:

- 1st request: 1 firing alert (1 total)
- 2nd request: 2 firing alerts (3 total)
- 3rd request: 1 firing, 1 resolved (5 total)
- 4th request: 2 firing alerts (7 total)
- 5th request: 1 firing, 1 resolved (9 total)

This was my way of experimenting with updates. I have a two-dimensional rule with 2 individual alerts I can control. In the beginning I changed one of them to firing state and then flipped another one back and forth a few times. The structure of the payload is the same as in the initial post, differs just in `status` values and timestamps.

So, on the 5th request, where I had two individual alerts (1 firing and 1 resoled), the value of `status` was taken to form the _Message_ according to the template. However the same source field did not contribute to resolution of the group. I understand that there is an ambiguity with status values as per my grouping configuration. I can't say it is logically right or wrong, because we have two contradicting statuses from two individual alerts, but it is kind of weird that `payload.status` contributed in one place but not in another, isn't it?

> Since Grafana Alerting integration ignores the top level status it will process each alert in the alerts array and will auto resolve the alert group when the alerts inside the array meet the resolve condition **for each unique set of labels**.

Just curious, how do you know that? Is it documented somewhere? Are you by chance a contributor to Grafana OnCall or otherwise engaged with Grafana? Sorry, I am not aware of the local community.

**Comment by mderynck** [comment]
The final state of the alert group for those 5 requests would also depend on the contents of the labels in each alert. If you can add that information as well I can give more insight into the behavior.

> Just curious, how do you know that? Is it documented somewhere? Are you by chance a contributor to Grafana OnCall or otherwise engaged with Grafana? Sorry, I am not aware of the local community.

I am a contributor to Grafana OnCall. We are working to improve documentation and communication about how this works.
I'm not sure if it will be helpful but [here](https://github.com/grafana/oncall/blob/1b3b0f9e13f2644d3edce0956112097f691c8f9a/engine/apps/alerts/models/alert_manager_models.py) is where we compute the hashes for the labels of each alert we receive to determine if a group is resolved:

**Comment by greatvovan** [comment]
> The final state of the alert group for those 5 requests would also depend on the contents of the labels in each alert. If you can add that information as well I can give more insight

Awesome. As per _Alert Payload_ button:

1

```
{
    "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
```

2 and 3

```
{
    "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
{
    "labels": {
        "TagName": "TAG_001",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
```

4 and 5

```
{
    "labels": {
        "TagName": "TAG_001",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "resolved",
}
{
    "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
```

6 and 7

```
{
    "labels": {
        "TagName": "TAG_001",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
{
    "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
```

8 and 9

```
{
    "labels": {
        "TagName": "TAG_001",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "firing",
}
{
    "labels": {
        "TagName": "TAG_002",
        "alertname": "Consumptive",
        "grafana_folder": "AWARE"
    },
    "status": "resolved",
}
```

The order is given as shown in _N Grouped Alerts_, increasing time. The pairs have identical time. The original order in the payloads cannot be restored.

**Comment by greatvovan** [comment]
I just realized that there is a separate repo for Grafana OnCall. I apologize for filing that in a wrong place.

**Comment by mderynck** [comment]
To summarize the alert group would have the following state:
| Event       | Alert Group Status | Label Set 1 (TAG_001) | Label Set 2 (TAG_002) |
|-------------|--------------------|-----------------------|-----------------------|
| After 1.    | Firing             | Unknown               | Firing                |
| After 2 & 3 | Firing             | Firing                | Firing                |
| After 4 & 5 | Firing             | Resolved              | Firing                |
| After 6 & 7 | Firing             | Firing                | Firing                |
| After 8 & 9 | Firing             | Firing                | Resolved              |

There was no time where after a request where both sets of labels encountered with resolved value so the auto resolution would not occur.  If 1 more request were to come either with only TAG_001 Resolved or both resolved, the auto resolution mechanism should resolve the alert group.

The content displayed at the top on the alert group page above Grouped Alerts is one of the last received alerts in the array not a representation of the alert group as a whole.  One way to illustrate this is if you were to add a field to annotations that was unique in every alert instance you can see it is a specific alert from the grouped alerts below that is being rendered at the top.

**Comment by greatvovan** [comment]
@mderynck that explains why the group was not resolved. Due to that tracking per a distinctive labels sets, there was an unresolved label set by the time of request `#5`. At the same time there is an ambiguity on what value to put into the group description based on the template, and it puts the "latest" value as per the order in `alerts` array.

Information in this thread is very useful for anyone who decides to go with _Grafana Alerting_ type of integration (I decided to not to, as I need access to the original payload). It looks like these details about label sets are underdocumented and my hope that someone will convert them into the official documentation, because I am about to close this issue.

**Comment by greatvovan** [comment]
The suggestion to improve the documentation moved here: https://github.com/grafana/oncall/discussions/899.
