### ISSUE TITLE
nested policy not working as expected

### ISSUE THREAD

**Issue by romkimchi1002** [grafana/grafana#57587]
**What happened**: 
Hi! i have issues with nested policies.
my alert is configured with the reduce operation in alert rule which generated different label for all alert instances (showed as 1,2,3):
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/116630343/197719505-287b6fe7-6745-48cb-a444-ce99df77b2dd.png">
my notification policy is configured like this:
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/116630343/197720535-df8f6e54-f345-44d4-8837-0d997d0e27a6.png">
all alerts where sent to the parent contact point including the one that wasn't supposed to.
when i configured the nested policy on different label that wasn't generated automatically by the reduce operation it worked as expected

**What you expected to happen**:
I expected the alert with label site_name=3 to be sent to the contact point configured in the nested policy

**How to reproduce it (as minimally and precisely as possible)**:
create alert rule with reduce operation
create a notification policy that catch all the alert instances and break the grouping (...)
add nested policy to catch one of the alerts 

**Anything else we need to know?**:
this feature is super important for us and our entire alerting management is relying on configuring one alert for many instances but to still have flexibility on each alert instance

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: influx (not sure what version or how to check it)
- OS Grafana is installed on: Ubuntu 
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:

**Comment by armandgrillet** [comment]
In your first screenshot we see `aidoc_site=3` and in the second screenshot `site_name=3`, both keys and labels have to match in order for a policy to match an alert instance. Can you confirm that this is case or try again with both keys and labels being the same?

**Comment by romkimchi1002** [comment]
you are right, what a stupid mistake, i triple checked it with a coworker and still managed to miss it.
thank you very much for your fast response

**Comment by jtheory** [comment]
By the way: we're working right now on making this experience better & safer -- it's **really easy** to accidentally type one label into a rule and a slightly different one into a notification policy -- and we don't currently provide any clues that you're building something that won't work... sorry about that, and better is on the way.
