### ISSUE TITLE
Alert payload and payload passed via provisioning API are different.

### ISSUE THREAD

**Issue by ali-avci** [grafana/grafana#57588]
**What happened**:
I did an update via the provisioning API to reduce the threshold for an existing alert rule. 

**What you expected to happen**:
On every where the threshold gets updated to the last given value. 
- Get method did deliver the same labels as they were PUT
![image](https://user-images.githubusercontent.com/44406279/197727975-27e4e088-b22d-4494-885c-1dd78af1c23c.png)

- the user interface is on some places showing the outdated threshold value (label value for threshold)
![image](https://user-images.githubusercontent.com/44406279/197727612-f2e0bd57-ed54-4eaa-9f1f-9118695ff755.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create an Alert Rule via Provisioning API, 
Change any of the labels that is also representing a value in the comparison expression.
Observe the UI of the alert rule where the state is shown. 
Payload is not reflecting the values past via the API.
Have seen that the delivered email is also reflecting the old payload. 

**Anything else we need to know?**:
I've a clue that the update did occur after the initial alert did fire where the old values were present. 
If this is the case then this issue turns into a bug in requirements. IMO if the rule is changed the alert needs to be re-evaluated.
might have the same root cause as https://github.com/grafana/grafana/issues/57578#issue-1421706534

**Environment**:
- Grafana version: 9.2.0
- Data source type & version: for this issue IMO not relevant
- OS Grafana is installed on: Ubuntu 
- User OS & Browser: for this bug IMO not relevant
- Grafana plugins: for this issue IMO not relevant

**Comment by ali-avci** [comment]
After the system is rebooted the shown values on the state area are getting consistent with the labels.

**Comment by greatvovan** [comment]
I don't think it is related to [#57578](https://github.com/grafana/grafana/issues/57578):
- this issue is about alert definition, not function;
- issue [#57578](https://github.com/grafana/grafana/issues/57578) is on OnCall side, alerting payload looks good.
