### ISSUE TITLE
Possible to  migrate from sqlite to mysql??

### ISSUE THREAD

**Issue by vijaik10** [grafana/grafana#5760]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [* ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Hi,
 
I'm using grafana with zabbix plugin running on centos. I installed grafana 3.1 with default sqlite3 database and created several users and dashboards which are mapped to users. Now i want to  migrate my db to mysql to  get better performance. Is it possible to  migrate from sqllite to mysql? or can i export all dashboards and userlist in  a single shot ,where i can import directly after creating and mapping new to mysql database.

Thanks!!

**Comment by bergquist** [comment]
I bet there are tools for importing sqlite databases into mysql. Ive never done it mysql but a quick google search show plenty of results. 

For Grafana you just have to update the connection string in the config file and restart grafana-server.

**Comment by envintus** [comment]
For people who land here via a Google search: https://community.grafana.com/t/migrating-grafana-data-to-new-database/2454/16

That shell script correctly converts the sqlite3 database to a MySQL version. The only change that was made to the SQL was to update the `data` column in the `dashboard_version` table to `mediumtext`.
