### ISSUE TITLE
Alert rule expression copied from 'Alert rules' page contains several UTF-8 BOMs

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#57610]
**What happened**:

I copy a Mimir alert rule expression in the 'Alert rules' page.

![Screenshot 2022-10-25 08-29-41 alert list](https://user-images.githubusercontent.com/3270755/197786100-cdd21430-3017-4189-b2dd-318489058ffc.png)

When I paste it in the Prometheus query builder, I see a lot of non-printable control characters were copied also. This query is invalid unless I remove all those control characters.

![Screenshot 2022-10-25 08-30-54 explore](https://user-images.githubusercontent.com/3270755/197786382-58a6f95f-d9fa-42c3-9762-869f7dd03da8.png)

hexdump of the clipboard content:
```
hexdump -C
100﻿ - ﻿(﻿avg ﻿by﻿ ﻿(﻿agent_hostname﻿)﻿ ﻿(﻿rate﻿(﻿node_cpu_seconds_total﻿{﻿mode﻿=﻿"idle"﻿}﻿[﻿2h﻿]﻿)﻿)﻿ * ﻿100﻿)﻿ ﻿>﻿ ﻿97
00000000  31 30 30 ef bb bf 20 2d  20 ef bb bf 28 ef bb bf  |100... - ...(...|
00000010  61 76 67 20 ef bb bf 62  79 ef bb bf 20 ef bb bf  |avg ...by... ...|
00000020  28 ef bb bf 61 67 65 6e  74 5f 68 6f 73 74 6e 61  |(...agent_hostna|
00000030  6d 65 ef bb bf 29 ef bb  bf 20 ef bb bf 28 ef bb  |me...)... ...(..|
00000040  bf 72 61 74 65 ef bb bf  28 ef bb bf 6e 6f 64 65  |.rate...(...node|
00000050  5f 63 70 75 5f 73 65 63  6f 6e 64 73 5f 74 6f 74  |_cpu_seconds_tot|
00000060  61 6c ef bb bf 7b ef bb  bf 6d 6f 64 65 ef bb bf  |al...{...mode...|
00000070  3d ef bb bf 22 69 64 6c  65 22 ef bb bf 7d ef bb  |=..."idle"...}..|
00000080  bf 5b ef bb bf 32 68 ef  bb bf 5d ef bb bf 29 ef  |.[...2h...]...).|
00000090  bb bf 29 ef bb bf 20 2a  20 ef bb bf 31 30 30 ef  |..)... * ...100.|
000000a0  bb bf 29 ef bb bf 20 ef  bb bf 3e ef bb bf 20 ef  |..)... ...>... .|
000000b0  bb bf 39 37 0a                                    |..97.|
000000b5
```

The offending bytes are `ef bb bf`. It's the UTF-8 [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark).

**What you expected to happen**:

No BOM copied.

**How to reproduce it (as minimally and precisely as possible)**:

I can reproduce it in https://play.grafana.org/alerting/list.

**Anything else we need to know?**:

* As a workaround, I edit the alert rule. If I copy the expression from the editor, it does not include non-printable control characters.
* Copying a Loki alert rule expression also copies BOMs. When pasting in the Loki query editor, the BOMs are removed (but they were still there in the clipboard before pasting) and the query runs successfully.

**Environment**:
- Grafana version: v9.2.1
- Data source type & version: Grafana Cloud metrics and logs
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox 105.0.1 on Pop_OS! 22.04
- Grafana plugins:
- Others:

**Comment by gillesdemey** [comment]
This looks to be an issue in the slate editor

https://github.com/ianstormtaylor/slate/issues/2597
