### ISSUE TITLE
Node Graph: Leverage edge and node thickness to display data

### ISSUE THREAD

**Issue by adrapereira** [grafana/grafana#57611]
We can leverage the edge thickness/pattern or change the shape or size of the node to display additional data in the node graph. For example we could differentiate throughput, latency or the kind of resource a node represents. These visual elements could be used to differentiate parts of the trace graph at a glance.

**Comment by aocenas** [comment]
We probably need to research this a bit. This is a common ask and is something that other tools have but probably one question is whether to make this configurable and how or whether there one single pattern we can hardcode for the benefit of all usecases.
