### ISSUE TITLE
TraceView: UX feedback session to gather ideas and select highest impact items to improve UI/UX

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#57626]
Our trace view (Tempo/Jaeger/Zipkin) has a lot of built in functionality and information displayed on screen. It was initially adopted from Jaeger and so feedback with regards to how we make this view feel more like a Grafana component as well as general ideas for improving the user experience is what we are looking for here. We can then select the highest impact items to improve our UI/UX with.

**Comment by aocenas** [comment]
This should result in a list of items that we can work on in the next quarter. We should separately decide on planning if it's bigger items.

**Comment by joey-grafana** [comment]
Had the UX feedback session on Dec 7th. The following were the most impactful ideas that we took note of;

- TraceView: Associate colours in trace view with colours in node graph (makes it easier to see related services between both views)
- TraceView: More spacing in trace header between pieces of data (view feels compact and over crowded)
- TraceView: More spacing for mini map (enough padding creates zones between our UI elements)
- TraceView: Check grey text contrast on light and dark backgrounds (+ other text but grey is the main one as it’s used a lot)
- TraceView: Link from node in node graph to span in trace view (in a large trace this would make it much easier to view span data)

**Comment by aocenas** [comment]
My notes for these:
> TraceView: Associate colours in trace view with colours in node graph (makes it easier to see related services between both views)

Could be interesting but as we use colors to convey success vs errors it would be hard to make this not look like a clown costume :D. Maybe could be some sort of switch between color modes similar we have in flamegraph now.

> TraceView: More spacing in trace header between pieces of data (view feels compact and over crowded)
> TraceView: More spacing for mini map (enough padding creates zones between our UI elements)

I think this is hard to decide as most of the time the feedback is that it's hard to work with bigger traces. Adding more white space does not help that I would think.

> TraceView: Link from node in node graph to span in trace view (in a large trace this would make it much easier to view span data)

Which one? I don't think we show a trace in node graph anymore and there isn't 1 to 1 mapping between service graph and trace.

**Comment by joey-grafana** [comment]
> Could be interesting but as we use colors to convey success vs errors it would be hard to make this not look like a clown costume :D. Maybe could be some sort of switch between color modes similar we have in flamegraph now.

Good point here. If the user is comfortable with recognising specific colors in the trace view, this could be helpful but I wonder how helpful. Also would definitely not want too many colors to make this look like a circus clown! :D

> I think this is hard to decide as most of the time the feedback is that it's hard to work with bigger traces. Adding more white space does not help that I would think.

Yeah this was mostly something that came up once or twice before we designed the new trace view header. I don't think it's an issue now.

> Which one? I don't think we show a trace in node graph anymore and there isn't 1 to 1 mapping between service graph and trace.

We still show the node graph above the trace view if it is turned on in the datasource config. This link could be helpful especially in the case of large traces.

**Comment by aocenas** [comment]
> We still show the node graph above the trace view if it is turned on in the datasource config. This link could be helpful especially in the case of large traces.

Ah forgot about that. Yeah there it would be nice. Also in general with things like having similar coloring and linking it would be nice to have better sync between service/node graph and trace

**Comment by joey-grafana** [comment]
Closing in favour of a more specific issue https://github.com/grafana/grafana/issues/83598
