### ISSUE TITLE
[Feature request] Feature to overlay previous week,day,hour metrics

### ISSUE THREAD

**Issue by ashokrajar** [grafana/grafana#5762]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Ubuntu
- What did you do?
N/A
- What was the expected result?
Need a new feature to overlay previous week,day,hour metrics 
- What happened instead?
N/A

**Comment by torkelo** [comment]
Use graphite's timeshift function :)
