### ISSUE TITLE
SQL: Issue when selecting multiple date time fields (mssql, mysql, postgres)

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#57627]
Greetings,

**What happened**:
When selecting multiple date time fields we get the following error: "convert value to float failed: metricIndex 1 type can't be converted to float"

**What you expected to happen**:
Ability to choose multiple datetime columns

**How to reproduce it (as minimally and precisely as possible)**:
Using following ms sql query as time series
```
select '2022-10-21 03:40:00' as CollectDate, '2022-10-22 03:40:00' ProblemStartDate, '2022-10-25 03:40:00' ProblemEndDate
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: Microsoft Sql Server
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: mssql

Thanks

**Comment by yosiasz** [comment]
this also happens with mysql

```
select DATE_ADD(now(),interval 2 hour) as time, DATE_ADD(now(),interval 3 hour) as jaja
```

**Comment by wohenbushuang** [comment]
Similar problem on mysql, and one more thing.

My raw data shown in `Table` format:
![image](https://user-images.githubusercontent.com/15613184/198567409-1b46bd1e-483a-43ab-988e-657c87694b47.png)

It works if I only select one datetime column as time in `Time series` format.
> SELECT device_id, longitude, latitude, create_at AS 'time'

It reports error with no data returned if query two datetime columns in `Time series` mode:
> convert value to float failed: metricIndex 4 type []*time.Time can't be converted to float

If I transform the other time column `location_time` into a string, its value become part of the other columns' name:
![image](https://user-images.githubusercontent.com/15613184/198567869-2068ed18-2f05-471a-9048-4c2835ca94a3.png)

**Comment by yosiasz** [comment]
Any update on this?

**Comment by zoltanbedi** [comment]
Hey @yosiasz thanks for opening this issue. I was able to reproduce this. Sadly I can't say anything when will we have time to fix it. We are open for contributions though if anyone wants to tackle this.

**Comment by gabor** [comment]
hi @yosiasz , i can reproduce the error message, but i'm not sure about the use-case here.
  if you goal is to create a time-series, that will need a single timestamp field, and a number field (and maybe some extra fields), but two timestamp fields cannot really work.

could you explain what you are trying to achieve here?

(i completely agree that showing that go-error-message is not a good user interface 👍 )
