### ISSUE TITLE
OAuth: Feature toggle for access token expiration check and refresh token handling

### ISSUE THREAD

**Issue by mgyongyosi** [grafana/grafana#57622]
Move the OAuth access token expiration check and token refresh handling behind a feature toggle and set the default value to false (disabled) to make it an opt-in feature.

### Why
Grafana 9.3 will handle the OAuth access tokens' expiration properly, but it can cause issues for existing Customers who do not have refresh token handling configured properly (missing `offline_access` scope, administrators did not enable the Refresh Token grant type on the provider side, etc). Hence we are going to introduce a feature toggle to make the transition to a more secure Grafana smooth.

### References
https://github.com/grafana/grafana/blob/main/pkg/services/contexthandler/contexthandler.go#L448

**Comment by nathangoss** [comment]
@mgyongyosi - is there a rough date estimate for the availability of Grafana 9.3, as well as details around the OAuth improvements?

**Comment by mgyongyosi** [comment]
@nathangoss we expect it to be available end of this year. We'll provide more details around the OAuth improvements on the [What's new in Grafana](https://grafana.com/docs/grafana/latest/whatsnew/) page. 

In a nutshell, currently OAuth providers are used only for logging in to Grafana and as part of our security improvements the access tokens' expiration date will be checked as well (if it's set by the IdP), to verify that the current user is still authorized to access Grafana. Besides Grafana does try to obtain a new access token using the refresh token in case the access token is expired. This will be an opt-in functionality in 9.3.
