### ISSUE TITLE
Include ability to stack auth.proxy with auth.ldap for better role resolution

### ISSUE THREAD

**Issue by sgroucutt** [grafana/grafana#5764]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 
  3.1.1
- What datasource are you using? 
  N/A
- What OS are you running grafana on? 
  Ubuntu 16.04
- What did you do?
  Our program has an HAProxy reverse proxy configured to do client certificate-based authentication, so we peel off the certificate's CN and pass it to our backend services for further authorization / auditing / etc.  We're looking at integrating Grafana as another available service behind our proxy, so we are passing this CN as X-WEBAUTH-USER to a Grafana backend and configuring auth.proxy appropriately.  However, our users have various groups defined in our organization's LDAP, and we want to assign some of them as Admins, some of them as Editors, and some of them as Viewers based on the groups they hold, so we'd also like to integrate auth.ldap (using X-WEBAUTH-USER as the search string for the user, and mapping our organization's groups to the roles above).  It does not seem possible to do this today based on https://groups.io/g/grafana/topic/269493#1116 - all authenticating users via auth.proxy wind up in the same role.
- What was the expected result?
  The value of X-WEBAUTH-USER (or whatever the configured header name is) from auth.proxy should be used as the user's search string in the LDAP query, and the groups-to-roles mapping in the auth.ldap configuration should be applied to the authenticated user to determine its role.
- What happened instead?
  The user authenticates only using auth.proxy configuration, and (it seems) winds up in the role defined in the auto_assign_org_role configuration.

**Comment by seuf** [comment]
can be closed..

**Comment by torkelo** [comment]
was implemented in https://github.com/grafana/grafana/pull/6895
