### ISSUE TITLE
Prometheus: Typing in query editor causes extra spaces added so query don't work

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [grafana/grafana#57647]
**What happened**:
with version 8.0.6, typing in query editor causes extra spaces to be added and query fails. Also, cursor jumps to the end of the expression each time I type a letter. Only at the end of expression can I type freely. If I open the JSON and copy to another board, cannot save with error `parse error: unexpected character: '\ufeff'`.

**What you expected to happen**:
Can type freely without extra spaces added and query works. And copy/paste of whole JSON works.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel, start typing in query editor in the middle of a query. You type and cursor jumps to the end. Or, it stops there, but you must press backspace multiple times to delete the letter you just typed. It seems deleting a bunch of "other things" before deleting the letter, in this case, I guess, are the added things.

Copy the query into Prometheus, you see red spots showing they are unneeded spaces. Removing the spaces and copy it back to Grafana, and query starts to work.

**Anything else we need to know?**:

Similar to #29850 [](url)

**Environment**:

- Grafana version: 8.0.6
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL(maybe)
- User OS & Browser: Ubuntu 18 with Gnome, Chrome version Version 105.0.5195.102 (Official Build) (64-bit)
- Grafana plugins: 
- Others:

See this gif:
![demo-grafana-bug](https://user-images.githubusercontent.com/12695200/197970958-5afb56de-c813-4e74-834c-d821742c8f9b.gif)

**Comment by safetytrick** [comment]
I can duplicate this in chrome. Works fine in Firefox.

**Comment by herrbpl** [comment]
Similar issues for me
https://github.com/grafana/grafana/issues/58496#issuecomment-1328896895

**Comment by itsmylife** [comment]
@WesleyBlancoYuan Could you please try upgrading to `v8.5.13`? 
Related PR for more details https://github.com/grafana/grafana/pull/54566

**Comment by WesleyBlancoYuan** [comment]
@itsmylife Hi I just tested `grafana/grafana-enterprise:8.5.13` docker image, with Prometheus also running in Docker(`prom/prometheus`), it works without problem. Don't know if the Prometheus version affects, and a pity that for my company I am not the responsible to upgrade to that version but I will let them know. Thanks for helping.

**Comment by WesleyBlancoYuan** [comment]
@itsmylife Hi I just tested `grafana/grafana-enterprise:8.5.13` docker image, with Prometheus also running in Docker(`prom/prometheus`), it works without problem. Don't know if the Prometheus version affects, and a pity that for my company I am not the responsible to upgrade to that version but I will let them know. Thanks for helping.

**Comment by WesleyBlancoYuan** [comment]
And I tried again with `grafana/grafana-enterprise:8.0.6`, indeed I again see the extra spaces(reproduced). So that version is indeed broken. Chrome 108.0.5359.94 on Windows 10. Same prometheus as last post.

**Comment by WesleyBlancoYuan** [comment]
Of course. Sorry I thought you should close it and I cannot. Now closing this. Thanks again.

**Comment by itsmylife** [comment]
@WesleyBlancoYuan I wanted to make sure you have your solution :) Thanks for closing this.
