### ISSUE TITLE
Login form doesn't offer oauth after redirect from signup

### ISSUE THREAD

**Issue by Unactived** [grafana/grafana#57651]
**What happened**:

When redirected from `/signup` to `/login`, oauth isn't offered as an authentication means.

**What you expected to happen**:

`/login` form after redirection from `/signup` matches the form you get by going to `/login` directly.

**How to reproduce it (as minimally and precisely as possible)**:

Configure `generic_oauth` ;
set `GF_USERS_ALLOW_SIGN_UP=false` (also `GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true`)

Go to `/login`, get : 
![image](https://user-images.githubusercontent.com/33038089/197977137-a0215c66-2e51-4678-b3d0-8422c42e1b6e.png)

Go to `/signup`, get correctly redirected to `/login`, and get : 
![image](https://user-images.githubusercontent.com/33038089/197977326-b6fef490-e23e-4900-b6ec-6013a842e1e5.png)

**Anything else we need to know?**:

Tested using official Docker image `grafana/grafana:9.2.1`

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: n/a
- OS Grafana is installed on: Docker inside User OS
- User OS & Browser: Ubuntu 22.04.1 LTS & Mozilla Firefox 106.0.1
- Grafana plugins: n/a
- Others: n/a

**Comment by kalleep** [comment]
Can replicate the issue, Will add it to our backlog
