### ISSUE TITLE
Docs: Improve alert rule types documentation

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#57658]
Improve docs around the different types of alert rules that we offer re conversation in slack:

Team, do we have documentation on the differences between Mimir/Loki Alerts and Grafana Managed Alerts?  I'm looking for something deeper than how to configure them.  More of an "under the hood" view.  The questions I'd like to be able to answer are:
How is each architected?
Use cases for each (i.e. when would I use which and why)?
Tradeoffs
Scalability

**Comment by yorugac** [comment]
Additional point from UX perspective. Grafana Managed Alerts and Mimir / Loki Alerts are configured differently: one type allows multiple queries and expressions set up while another doesn't. IMHO, clear understanding of why it is so would help pick the right one in some cases.

**Comment by brendamuir** [comment]
Closing this as we have a parallel issue for this: https://github.com/grafana/alerting-squad/issues/345
