### ISSUE TITLE
support parent-child Relationship

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5766]
when i deal some mode,we related two index with  parent-child Relationship  ;how grafana support for it?
https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html

**Comment by torkelo** [comment]
how do you want grafana to support it?

**Comment by tonyC2016** [comment]
@torkelo   there is two indexes at es ,and  index b is index a's child , when i set datasouece is a or b ,how i can show the data from its parent or child at grafana

**Comment by tonyC2016** [comment]
the es query like as below:
GET /company/branch/_search
{
  "query": {
    "has_child": {
      "type": "employee",
      "query": {
        "range": {
          "dob": {
            "gte": "1980-01-01"
          }
        }
      }
    }
  }
}

**Comment by cm2d** [comment]
Hello, +1 
For a more detailed description, look here: https://github.com/grafana/grafana/issues/3163 
Thank you for the work Grafana

**Comment by sradco** [comment]
+1 
Really need this option.
We want to get from one source the metadata and the metrics data from a different source and be able to correlate between them.

**Comment by shayan90** [comment]
+1

**Comment by nsanson** [comment]
+1
