### ISSUE TITLE
Unable to Assume AWS Role in another account

### ISSUE THREAD

**Issue by upodroid** [grafana/grafana#57664]
**What happened**:

I'm unable to assume a role from another account.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25100905/198006710-533a68c4-884d-4945-a9e3-bb03cfbc6b6a.png">

**What you expected to happen**:

I should be able to assume the role on the other account. I can verify this actually works with the aws cli.

```
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  puppet   develop  2✎  1+  $   env | grep AWS
AWS_REGION=eu-central-1
AWS_ROLE_ARN=arn:aws:iam::760591208458:role/gke-to-aws
AWS_ROLE_SESSION_NAME=grafana
AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/token
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  puppet   develop  2✎  1+  $   aws sts get-caller-identity
{
    "UserId": "AROA3CFWE2AFEKD5FUXOU:grafana",
    "Account": "760591208458",
    "Arn": "arn:aws:sts::760591208458:assumed-role/gke-to-aws/grafana"
}
 REDACTED  MCW0CDP3YY  ~  Desktop  Git  puppet   develop  2✎  1+  $   aws sts assume-role --role-arn arn:aws:iam::691556712356:role/gke-grafana --role-session-name grafana | jq .AssumedRoleUser
{
  "AssumedRoleId": "AROA2CA7576SLIMDUFOXM:grafana",
  "Arn": "arn:aws:sts::691556712356:assumed-role/gke-grafana/grafana"
}
# I can assume the role succesfully

```

**How to reproduce it (as minimally and precisely as possible)**:

Create an IAM role in one account and then assume another role in a different account.

**Anything else we need to know?**:

https://github.com/borg-land/k8s-demo/blob/dev/monitoring/values.yaml#L11

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: CloudWatch v5
- OS Grafana is installed on: GKE 1.23
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue @upodroid. 

I have just tried assuming a role in a different account using the CloudWatch plugin in Grafana 9.2.1, and it's working as expected with my setup. Configuring assume roles is tricky, and there can be numerous reasons for why it's not working so it's hard to give advice. I suggest you check you setup once again. You can also refer to the official AWS [assume role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) documentation.

**Comment by upodroid** [comment]
If you don't mind me asking, what was the source principal? An IAM User?

**Comment by sunker** [comment]
Yes IAM user. 

Gonna close this issue now. Feel free to re-open if you feel the need to.
