### ISSUE TITLE
Dashboard: "Dashboard not editable" layout bug

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#57691]
![Layout bug dashboard not editable](https://user-images.githubusercontent.com/2903904/198081688-e909ac99-9230-4e56-8248-5d1100182af2.png)

For dashboards which are not editable (whether provisioned, or simply save with "not editable" toggled) clicking the Gear ⚙️ symbol from the dashboard renders this view (see above).

There's some missing padding and alignment I believe, on the left had side of the screen, for both of:
- text "Dashboard not editable"
- Button "Make editable"

It's very ugly!

**Comment by mckn** [comment]
Thanks for reporting this. I am able to reproduce it on main but please follow the issue template next time you open an issue.

**Comment by parkedwards** [comment]
one additional observation - clicking the button doesn't change the view state, so the user doesn't know whether or not grafana registered the click (leading to some spam clicking)

**Comment by Wafa9** [comment]
Hi @samjewell , can i work on this issue if it still open?

**Comment by samjewell** [comment]
Hey Wafa
Yes I believe this is still an issue- doesn’t look like anyone is working
on it. Thanks!

**Comment by Wafa9** [comment]
thanks @samjewell , it my first time to contribute , if you don't mind please can you tell more details or guide me how to work on this issue.

**Comment by samjewell** [comment]
Hey @Wafa9 
Sorry but I have almost no familiarity with the Grafana front-end here. I'm not sure what the best route is to get help here - Maybe you could ask for help in the [#grafana-dev](https://grafana.slack.com/archives/CBA3NSALE) channel in the community Slack?

**Comment by samjewell** [comment]
Thanks @mckn 

You said:
> Thanks for reporting this. I am able to reproduce it on main but please follow the issue template next time you open an issue.

I'll try harder, sorry. But also see my response and questions here: 
https://github.com/grafana/grafana/issues/57694#issuecomment-1308596254

**Comment by natellium** [comment]
Hey @Wafa9, great to see you're interested in contributing. If you're still looking for some indications, [here](https://grafana.com/docs/grafana/latest/developers/contribute/ ) are the resources available. For this issue in particular they key ones will probably be our [Developer guide](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md), [Create a pull request](https://github.com/grafana/grafana/blob/main/contribute/create-pull-request.md), and our [styleguides](https://github.com/grafana/grafana/tree/main/contribute/style-guides)

**Comment by Shadow27374** [comment]
I was just about to edit something and have this exact problem.

Is there any way to make the dashboards editable again until there is an update or do I have to wait now?

**Comment by mshahzeb** [comment]
Issue already reported against Grafana here: https://github.com/grafana/grafana/issues/57691

**Comment by reuvygroovy** [comment]
When you click on the Make Editable button, it does in fact become editable. Just need to save the dashboard changes after clicking and refresh, then when coming back to the gear icon you will see everything as normal.

This problem exists in 9.3.0 as well.

**Comment by Shadow27374** [comment]
In the meantime, I have also managed it. After the "make editable" I could not save because the button no longer has a function. But you can go back one view and there appears the save button which also works.

However, this is very annoying.

**Comment by samjewell** [comment]
@joshhunt and team: **thanks** for fixing this ❤️
