### ISSUE TITLE
TimeSeries: Regression in 9.2.2 affecting node_exporter CPU graphs.

### ISSUE THREAD

**Issue by courtland** [grafana/grafana#57690]
**What happened**:

When upgrading from Grafana 9.2.1 to 9.2.2, the CPU timeseries graphs in the popular "Node Exporter Full" dashboard become blank.

https://github.com/rfmoz/grafana-dashboards/issues/105

**How to reproduce it (as minimally and precisely as possible)**:

Launch a fresh 9.2.2 install, with latest prometheus and a node_exporter as a target. Load the [Node Exporter Full dashboard](https://grafana.com/grafana/dashboards/1860-node-exporter-full/). The CPU graphs are blank.

**Anything else we need to know?**:

Reverting to 9.2.1 fixes the problem (CPU graphs have data).

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 22.04.1 LTS
- User OS & Browser: MacOS Chrome
- Grafana plugins: Default

**Comment by xelatirdan** [comment]
Hello! As a quick fix you can set Stack series to Normal in graph settings and it starts work.
![Screenshot_2022-10-31_11-53-41](https://user-images.githubusercontent.com/17021453/198970227-7c2d4ba6-16f1-4ecc-a600-a7d0657a1ed8.png)

**Comment by courtland** [comment]
This is no longer an issue for me with 9.3.0-beta1 and recent "Node Exporter Full" dashboard.
