### ISSUE TITLE
[Feature] Abstract image uploading to enable images for email and slack

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5770]
Slack message and emails that include images requires the image to be public to the internet. It should be possible to upload the images to s3, webdav or just internal within grafana. 

It's not recommended to upload the images within grafana since it might not be available to the public internet but still possible since some grafana instances are.

**Comment by torkelo** [comment]
email dont really need this feature as email attachments are part of the email data

**Comment by bergquist** [comment]
Its not required but I think its good to provide both since mail servers might reject attached files. Enterprise ftw!
