### ISSUE TITLE
Can't use $__from or $__to in grafana managed alert with mysql

### ISSUE THREAD

**Issue by donutsaregood** [grafana/grafana#57705]
Thanks for taking a look, this is my first time posting about an issue.

**What happened**:
I'm setting up a grafana managed alert using a MySQL database. I can run the following query in the explore tool in grafana and I get back the results I am expecting:
```
SELECT
  convert(table1.data_value, DECIMAL(4,1)) as value,
  table2.timestamp as time
FROM 
  table2,
  table1
WHERE
  table2.id >= (SELECT MIN(id)
                       FROM table2
	               WHERE table2.created_timestamp >= $__from AND table2.created_timestamp <= $__to)
  AND
  table2.id <= (SELECT MAX(id)
		       FROM table2
	               WHERE table2.created_timestamp >= $__from AND table2.created_timestamp <= $__to)
  AND
  table2.id = table1.data_id
  AND 
  table2.sensor_id = '100'
  AND
  table2.data_key = 'weight'
ORDER BY 
  table2.id
```
Running this query in the explore tool runs without any issues.

When I run the exact same query in the alert tool, I get the following error:
"Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: db query error: Error 1054: Unknown column '$__from' in 'where clause'"

The query executes normally if I hard code values in for $__from and $__to.

**What you expected to happen**:
I expect the query generator to replace $__from and $__to with the unix timestamps corresponding to the time range that I've selected. I expect the query to run the same way that it does in the explore tool.

**How to reproduce it (as minimally and precisely as possible)**:
Run a MySQL time series query in the explore tool using $__from and/or $__to. Copy the query into the alerting tool (create an alert using that query) and try to run it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2.1
- Data source type & version: MySQL 8.0.30
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, firefox
- Grafana plugins: MySQL 5.0.0
- Others:

**Comment by mckn** [comment]
The  `$__from` and $__to` is frontend based template variables that are not available in the backend when running alert queries. But the `$__timeFilter(column)` or `$__timeFrom`/`$__timeTo` should be available.

These kinds of questions should be asked in the community forum so more people can take part of the answers. For further assistance please use https://community.grafana.com/
