### ISSUE TITLE
Alerting: Rule query default max data points & interval can cause unexpected requests

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#57715]
**What happened**:

Alert rule queries will default to max data points=43200 and interval=1s. This can cause unexpected queries/results: heavier load on your datasource, returning more data than necessary, errors with no clear workaround in every datasource.

Using Prometheus as an example, this has the following effects (**NOTE**: Setting the `min-step` to a larger value will allow you to avoid most of these in Prometheus, though not in all datasources):

- If the time range is between `0` and `11000s`, the calculated interval will be `1s`. (`11000` is the hard limit used as a safe resolution in Prometheus). The interval will be `1s` even if the prom scrape interval is larger. This will often over-sample unnecessarily and cause more data to be returned than is likely required for your query. Sometimes resulting in `413` errors, as seen [here](https://github.com/grafana/support-escalations/issues/4315).
![Screenshot from 2022-10-27 00-40-34](https://user-images.githubusercontent.com/8484471/198202091-e29f264c-efe0-4309-bed9-3d5f3af98b1f.png)

- If the time range is larger than `11000s`, the calculated interval will be `=time range / 11000` and rounded. [Specific logic here](https://github.com/grafana/grafana/blob/152c7f149ae5be930f7ce8a31921837667c5230b/pkg/tsdb/prometheus/models/query.go#L153-L159.). This can have some strange effects:
  - Setting the time range to be `now-11001s` will cause the safe interval calculation to fail (because of rounding) and the query will error with `... exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)`. 
  
![Screenshot from 2022-10-27 01-50-37](https://user-images.githubusercontent.com/8484471/198202312-1a9c2be1-2287-41df-97c3-e138e57e5e46.png)
Setting to `now-16501s` will work again though.
![Screenshot from 2022-10-27 01-51-38](https://user-images.githubusercontent.com/8484471/198202426-10fcf715-f370-40d9-9882-20dac1eda4d5.png)

  - As the range increases, the step interval will become more reasonable (though still very small) as the calculation hits each rounding plateau.
- The same query with a default `min-step` will have different results in Explore and Alerting. This is because Explore, similar to dashboards, calculates a reasonable max data points / interval based on the time range and width of panel when not explicitly set.
![Screenshot from 2022-10-27 01-53-23](https://user-images.githubusercontent.com/8484471/198202630-136f25b4-7bcd-4569-bcd5-ea2e91b57331.png)

**What you expected to happen**:

- The default max data points / step size to be calculated in a similar fashion to explore & dashboards.
- Max data points should be editable in the UI as a query option common to all datasources. (https://github.com/grafana/grafana/issues/36336)

**How to reproduce it (as minimally and precisely as possible)**:

- Create a `vector(0)` query on any Prometheus datasource and look a the response time series sizes /  timestamp step sizes for various time ranges.

**Anything else we need to know?**:

There is technically already a way to set `maxDataPoints` for Alerting queries as originally discussed [here](https://github.com/grafana/grafana/issues/27469#issuecomment-878891684). It requires you to create a panel with max data points set and then create an alert based on that panel. This will save the max data points value in the model of the alert query.

![Screenshot from 2022-10-27 01-57-01](https://user-images.githubusercontent.com/8484471/198203297-553d4f0d-0b15-468a-a498-dfbcebbae537.png)
![Screenshot from 2022-10-27 01-57-19](https://user-images.githubusercontent.com/8484471/198203302-a86e13b7-8f4b-4b09-8faf-7b8aee98e122.png)

This is not well documented and even if it were I don't think this should be the only way to accomplish this.

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by soniaAguilarPeiron** [comment]
I created this [PR](https://github.com/grafana/grafana/pull/61904) for adding maxdatapoints in the alert rule form for each query

**Comment by JacobsonMT** [comment]
The UI now has the ability to adjust the maximum number of data points for alerting queries. This issue also discusses whether there should be limitations on the backend as well, such as restricting Prometheus queries to not have a minimum interval smaller than the scrape interval. After internal discussion, it has been decided not to make this change as it would require adding data source specific logic to the evaluation code. Instead, any limitations should be implemented on the plugin side, as they have access to the necessary information to make that decision.

I'm going to close this issue as done and we can reopen it later if need be.
