### ISSUE TITLE
Sensu is not in Grafana 9.1/9.2 contact point

### ISSUE THREAD

**Issue by zyxep** [grafana/grafana#57720]
**What happened**:
The documentation on:
https://grafana.com/docs/grafana/v9.1/alerting/contact-points/notifiers/
and latest documentation
https://grafana.com/docs/grafana/latest/alerting/contact-points/notifiers/

Shows it support **Sensu** as contact point.
but in reality it isn't in the list when creating a new connection.

**What you expected to happen**:
To still have **Sensu** listed and used.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1
- Data source type & version:
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mckn** [comment]
Hello, thanks for this issue. Are you using grafana managed alerts? Looks like I have the option to use Sensu as a contact point.

<img width="685" alt="Skärmavbild 2022-10-27 kl  12 52 20" src="https://user-images.githubusercontent.com/172951/198266122-1b0acedf-0ca2-4146-ac14-55ca9aea42b8.png">

**Comment by zyxep** [comment]
There is a huge difference between Sensu Go & just Sensu.
I expect it to have both options.

**Comment by mckn** [comment]
Okay, I'm sending this to the proper people to have a look at it.
