### ISSUE TITLE
Timeseries: No points shown despite option "show points" set to "auto" in Time series panel

### ISSUE THREAD

**Issue by skladd** [grafana/grafana#57722]
**What happened**:
In a Time series panel, when switching option  "Show points" to "Auto", single points disappear.

**What you expected to happen**:
Single points should stay visible.

**How to reproduce it (as minimally and precisely as possible)**:
Edit panel, zoom into data until only one dataset is visible, then set "Show points" to "Auto".

![](https://media4.giphy.com/media/VyzWCq1ACdoe2EeXi3/giphy.gif?cid=790b7611ee9d0571f891050309ea2cb0d0a11e05696de225&rid=giphy.gif&ct=g)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Docker/Linux
- User OS & Browser: Ubuntu 20.04, Chromium 106

**Comment by mckn** [comment]
Might be related to #57690

**Comment by skladd** [comment]
I cannot say if it ever used to work, at least it does not in v9.1.6. Same behavior as in v9.2.2.

**Comment by leeoniya** [comment]
@skladd can you post your data?

is that point the first or last non-null point of a dataset that starts or ends with null values?

**Comment by skladd** [comment]
@leeoniya You are right, I get a lot of null values before and after one dataset with values. In the query, I have no fill option at all. After adding `fill(none)` it works as expected, the points are shown.

**Comment by skladd** [comment]
Just updated Grafana to v9.2.4, the points are shown as expected.
@leeoniya Thanks a lot!
