### ISSUE TITLE
Allow a constant number of buckets with Elasticsearch

### ISSUE THREAD

**Issue by volter** [grafana/grafana#5773]
I'd love to have an option that keeps a certain number or maybe maximum number of buckets. Zooming out over a week worth of data while keeping the bucket size of 1 minute, you may have used before, is no fun.

Kibana appears to do it like that, when Auto is specified. A setting of the same name in Grafana apparently doesn't behave like that.

**Comment by torkelo** [comment]
yes it does, there is an Auto option in Grafana as well, will adapt group by interval to time range :)

**Comment by torkelo** [comment]
the auto option tries to create one bucket per pixel, rounded to an an appropriate interval, if you want less buckets you can use an interval template variable, add auto option and specify the desired number of buckets and use the variable in the interval field
