### ISSUE TITLE
Transformation Convert Field Type not converting to Numerical Value

### ISSUE THREAD

**Issue by strudel0209** [grafana/grafana#57737]
**What happened**:
Using Grafana Cloud and Infinity Plugin we are trying to apply Convert Field Type to Numeric transformation upon a string returned value. 
The string values are "A","B","C","D"
using Value Mappings as per below:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/9446504/198260555-5e9ab5a2-029d-44af-bb67-e1ed0729dba6.png">
 we are trying to transform the mapped value to numerical using the Convert Field Type transformation 
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/9446504/198260917-e9a488e5-f4fa-4901-8936-24de20ddba6c.png">

We are trying to transform the value into a numerical one so that we can apply boolean operation based on it.
The transformation is not working as the value returned upon the boolean operation is NaN / 0

**What you expected to happen**:
Convert Field Type to Numeric should convert field to numeric

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
Grafana Cloud and Infinity Plugin v1.0.0
- Data source type & version:
Infinity Plugin
- OS Grafana is installed on:
- User OS & Browser:
- MacOS M1 / Chrome
- Grafana plugins:
Infinity Plugin v1.0.0

**Comment by strudel0209** [comment]
Hi,

Any update on this?

**Comment by zoltanbedi** [comment]
Fixed in https://github.com/grafana/grafana/pull/66807 The fix will be out in Grafana 10
