### ISSUE TITLE
G10 Get Started: Elastic

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#57732]
A key goal of Grafana 10 is to improve the getting started experience in Grafana, where that journey is defined as going from an empty instance to monitoring something. This is valuable because:

> An improved onboarding experience for new-to-Grafana users will help people achieve their desired outcomes (creating dashboards, keeping their systems healthy) faster, and help them build confidence as continuing users. Users who successfully set up their first data source and query it are far more likely to return to, share, and eventually pay for Grafana and Grafana Cloud.

Additional context:

- [Framing](https://docs.google.com/document/d/1j8ew0mNL3jQUa4KmdHmZzzPxpJl_1HunczaJuvMA7bU/edit#bookmark=id.7abyf01er8bt)
- [Presentation](https://docs.google.com/presentation/d/1mzZYfKVbo9ju8X0EqpSiN_z1Q865clVXbAUjiaS3eaQ/edit#slide=id.g1596ba710f4_0_114)
- [FAQ](https://docs.google.com/document/d/1Ts2TK_uHd4ffc-UxEcT1kyXd8ceouepJ_wkRLo4nByg/edit#)

This represents investment of roughly one month of an engineer's time in improving the Getting Started experience around Elastic. We should balance this time between: clearing technical blockers (i.e. BE migration, research, and initial execution on research.

https://github.com/grafana/grafana/issues/57732#tasklist-block-5b751e26-e00b-442f-a91c-c6aa13e0d71e

**Comment by gabor-grafana** [comment]
we finished the research to identify the changes that will improve the getting-started experience with elastic, the steps are described in https://github.com/grafana/grafana/issues/62196

**Comment by gabor** [comment]
we finished the research to identify the tasks to improve the elasticsearch new user experience, the tasks are described in https://github.com/grafana/grafana/issues/62196
