### ISSUE TITLE
Loki: Query validation in monaco editor

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#57746]
### Summary

Our users would benefit greatly if they instantly learned if the query they constructed is valid or not. Moreover if they knew where exactly does query have error, it would be significantly easier and faster to fix it. This would result in users who are more confident in queries that they are sending to Loki. 

### Problem statement

Currently, to learn if the created LogQL is valid, users need to run the query and if the query is invalid, they get the not-super-user-friendly error message. With a new monaco editor we have a great opportunity to improve query writing experience for our users by doing query validation and instantly showing query errors in editor. This way, users learn right away which part of the query is incorrect. This removes frustration of running a query, waiting for result and getting error message about invalid logql. 

### Scope

Design Doc

### Solution

With loki lezer parser and monaco editor, we have a great way how to improve query writing. While now, users have to send query to see if it is valid or invalid, we could use parser to show them this information even before sending the query out. Moreover, we could point them to the exact spot where the issue it.

This requires design doc as this could be a new data source API used for all data sources using monaco editor. 

![Image](https://user-images.githubusercontent.com/30407135/196750686-9ac52ee6-8ce5-429e-a8ab-551beac6587c.png)

![Image](https://user-images.githubusercontent.com/30407135/196750838-d3db7b8d-76db-4538-95f9-8496fb98760a.png)

### Measurement

- Higher ratio of successful queries.
- Less queries that error out due to incorrect LogQl. 

### Resources

https://github.com/grafana/grafana/discussions/52358
https://github.com/grafana/grafana/discussions/53647

**Comment by matyax** [comment]
I've been playing with Monaco and the Parser, and came out with this:

https://user-images.githubusercontent.com/1069378/204344140-5ef89f73-7d84-4c06-949c-5fe465a6af72.mov

We can use Monaco [markers](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-model-markers-example) to display parse errors to the user before the query is executed.

If we like this, I can work on this implementation which is basically and `onChange` listener an a validation function.

@ivanahuckova I see that you mention a design doc in the issue description, but I'm not sure how to approach that or what to do about it. The implementation is super trivial: https://github.com/grafana/grafana/pull/59427/commits/b9191d3225c8f69d6602b1e235a3598c655d8baf

**Comment by ivanahuckova** [comment]
Nice! This looks really great. ✨✨ The design doc was mentioned because there wasn't clarity on how complex would the solution be. Moreover, we could consider, if we should use internal parser or if we want to check with loki server if query is valid. But I personally think this looks great! So you could create PR and we can test it out. 🙂

**Comment by stevendungan** [comment]
A couple thoughts going through this on success criteria:
* do we have a way to measure these two items? (I really like the % of successful queries, it is a good guardrail metric to make sure people aren't just querying less)
* do we have a way to measure time to success? i think it isn't just incorrect queries, but reducing time to get the result they want - so how long does it take to write, and rewrite, queries, even if "successful" they may not return the anticipated result

i do think the demo above looks like a fantastic place to start also!
