### ISSUE TITLE
Same scale on left Y and right Y

### ISSUE THREAD

**Issue by xelite** [grafana/grafana#5775]
Grafana 3.1.0 with graphite on debian.

I would like to use same auto scale on left/right Y metrics in same graph (eg. left Y Max = right Y Max). Also in others graphs (eg. graph 1 left Y Max = graph 2 left Y Max).

**Comment by torkelo** [comment]
The point of having two y axis is to allow different scales / different min/max :)

**Comment by kogaba** [comment]
+1

**Comment by kogaba** [comment]
I would like to have warning and critical level displayed, but i'd like the legend be clear, so at least let the legend arrange to right without assign them, to right axis. (and maybe center align, so it is possible to use the right axis and less important legend could be in the center)
What do yo mean?
