### ISSUE TITLE
Grafana 10 Getting Started: Prometheus

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#57754]
A key goal of Grafana 10 is to improve the getting started experience in Grafana, where that journey is defined as going from an empty instance to monitoring something. This is valuable because:

> An improved onboarding experience for new-to-Grafana users will help people achieve their desired outcomes (creating dashboards, keeping their systems healthy) faster, and help them build confidence as continuing users. Users who successfully set up their first data source and query it are far more likely to return to, share, and eventually pay for Grafana and Grafana Cloud.

Additional context:

- [Framing](https://docs.google.com/document/d/1j8ew0mNL3jQUa4KmdHmZzzPxpJl_1HunczaJuvMA7bU/edit#bookmark=id.7abyf01er8bt)
- [Presentation](https://docs.google.com/presentation/d/1mzZYfKVbo9ju8X0EqpSiN_z1Q865clVXbAUjiaS3eaQ/edit#slide=id.g1596ba710f4_0_114)
- [FAQ](https://docs.google.com/document/d/1Ts2TK_uHd4ffc-UxEcT1kyXd8ceouepJ_wkRLo4nByg/edit#)

This represents investment of roughly one month of an engineer's time in improving the Getting Started experience around Prometheus. This will start with research.

**Comment by bohandley** [comment]
Proposal for the squad:
Grafana 10 Prometheus Getting Started Research Proposal

**Benefit** 
- Grafana 10 goals Getting started/Onboarding/Personas are a priority for the company, squad and customers

**Acceptance Criteria**  
- Provide insight into Getting started/Onboarding/Personas
- Provide 3-4 design docs to execute on for Q1 or possibly in Q4

**What is it?**
One month dedicated research
Weekly check in meetings with Galen
The official deep dive kick off is the offsite or when I’ve finished [#48](https://github.com/grafana/observability-metrics-squad/issues/48) & [#49](https://github.com/grafana/observability-metrics-squad/issues/49) whichever comes first, but the research brainstorming, idea generation and check in meetings with Galen with are already started.

What kind of research? What guidelines am I starting with? (suggestions by)
- Offsite un-conference with Mary(Evan)
- Community channel/issues scraping (Galen)
- Set up prometheus as a beginning user (Kyle)
- document all pain points
- weird buttons
- missing documentation
- opportunities for tooltips or guidance

**Comment by bohandley** [comment]
Offsite outcomes here =>

1. [Squad Session Day Notes](https://docs.google.com/document/d/1OagpLYnWjCT_buRlqyxYDwgBIg2LdUfnULIZTBjsaqQ/edit#)

2. [Un Conference Getting Started with Prometheus](https://docs.google.com/document/d/1MFHIkFq2hR6C4-HTDPVTLCq9QMdPBAIwnHIAGnS7u2o/edit#heading=h.y0yfh2v7ctk6)

**Comment by bohandley** [comment]
Update with high level description Dec 13, 2022

1. Overall Strategy

- The metrics team will partner with UX to map out the flow of getting started with Prometheus, identify personas, identify pain points, get fresh perspectives and data from actual users and use all of this information to generate solutions to improve the experience of getting started with Prometheus.

2. Timeline/Goals/Milestones

- [X] Dec 15, 2022 [Mapping out full user journeys](https://miro.com/app/board/uXjVPDcNmwc=/?moveToWidget=3458764540147480223&cot=14). (Prom & Loki)
- [X] Dec 13, 2022 Pain points defined (workshop with Prom & Loki)
- [ ] Dec 21, 2022 User interviews with users who have recently undergone the onboarding to get fresh perspectives. This can be both internal and external users. 
- [ ] Jan 13, 2023 First Draft Designs of possible new solutions to simplify the process.

3. Actors
- UX Researcher [Diego Adams](mailto:diego.adams@grafana.com)
- Developer [Brendan O'Handley](mailto:brendan.ohandley@grafana.com)
- Support Devs  [Ismail Simsek](mailto:ismail.simsek@grafana.com) [Galen Kistler](mailto:galen.kistler@grafana.com)
- Stakeholders  [Evan Dandrea](mailto:evan.dandrea@grafana.com)

**Comment by bohandley** [comment]
Part 1 of Getting Started with Prometheus is wrapping up. Listed below is a summary of the research outcomes, a list of work completed, a list of work in progress and possible work for Q1. The full discovery doc is [here](https://docs.google.com/document/d/11UbFJjAvCWW6Mlv4iahDQXnVIxzFiNhak-Wz4vDIXno/edit#heading=h.n8gemq1gc10r). The summary of the discovery doc is [here](https://docs.google.com/document/d/11UbFJjAvCWW6Mlv4iahDQXnVIxzFiNhak-Wz4vDIXno/edit#heading=h.n8gemq1gc10r)

**Research outcomes:**

1. We need to update the documentation
- Set up is confusing, there are multiple ways to configure Prometheus to work with Grafana
- Getting Started Doc was confusing
- Support Docker usage of Prometheus in Getting Started Doc

2. We need to provide better support for onboarding
- Onboarding hints
- Need for hint for how to start a query
- Users desire a quick functional query
- Not intuitive what to start query with
- Hand holding stops after setting up datasource

3. There is room to improve the UI
- Not intuitive what to start query with
- Histograms and heatmaps require extra knowledge to set up correctly
- Busy UI, too many buttons, hard to find features
- Better UI for metrics list

**Work that have been complete:**
[Remove raw query toggle](https://github.com/grafana/grafana/pull/59069)
[Toggle default editor](https://github.com/grafana/grafana/pull/61510)
[Instant query results in addition to Table](https://github.com/grafana/grafana/pull/60479)
[Getting Started Doc updated to funnel to Grafana Cloud](https://github.com/grafana/grafana/pull/60803)
[Measure successful query](https://github.com/grafana/grafana/pull/61004)
[Kickstart your Query, formerly query patterns](https://github.com/grafana/grafana/pull/60718)

**Work in progress:**
[Deprecate the Prometheus landing page button to docs in favor of hosted Grafana instructions](https://github.com/grafana/grafana-com/issues/5531)
[Getting Started from Scratch Documentation](https://github.com/grafana/mimir/issues/3757)
- Partnering with doc writers
- Expand to beginning users
- Custom metrics
- Explore metric types
- More research opportunities
- Possible onboarding doc in Grafana

**Suggested work:**
[Metric Encyclopedia](https://docs.google.com/document/d/13BvYtJ05yaPvdUovFYP2BZDgUBNClFkZPBBgMXZ-Xmk/edit#heading=h.a7lpb7903kup)
What needs does this address?\
- Hand holding stops after setting up datasource
- Need for hint for how to start a query
- Not intuitive what to start query with
- Easy path to writing a query
- Better UI for metrics list
- Clearer definitions of functions and uses with metrics

[Query Onboarding](https://docs.google.com/document/d/1JOdwMOiYHWICnTETuOutk_mzhFQqn8BOM7ymC_iUOuM/edit#)
What needs does this address?
- Need for hint for how to start a query
- Onboarding hints
- Hand holding stops after setting up datasource
- Clearer definitions of functions and uses with metrics
- Not intuitive what to start query with
- Busy UI, too many buttons, hard to find features

**Comment by bohandley** [comment]
Thank you @diegoadams, @gtk-grafana, UX team and @grafana/observability-metrics for the help and support with this issue.

[The official research results are here.](https://raintank-corp.slack.com/files/U02PK71RAN7/F04LLGAQYE9/copy_of_user_research_findings__prometheus_query_builder)

This work will be continued with an audit of docs, configs, and query editor as well as research, testing and validation of work suggested in the research results in [Grafana 10 Getting Started: Prometheus Part II.](https://github.com/grafana/grafana/issues/62978)

**Comment by gtk-grafana** [comment]
@bohandley Great work on this! That link to the research results is on the internal slack, and this is a public facing issue, do we want to put those results somewhere everyone can see?

**Comment by bohandley** [comment]
@gtk-grafana Good catch! Let me fix that
