### ISSUE TITLE
Lasts version of marcusolsson-json-datasource not available in plugins api repo

### ISSUE THREAD

**Issue by mchauvel** [grafana/grafana#57756]
**What happened**:
I use an artifactory to proxy grafana plugins, and when i try to get the last version of marcusolsson-json-datasource plugin, i only get the `0.4.0`.

**What you expected to happen**:
I expect to download the last version (`1.3.2`)

**How to reproduce it (as minimally and precisely as possible)**:
Artifactory seems to use this URL : https://grafana.com/api/plugins/repo/marcusolsson-json-datasource
and the version problem is visible here.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.7
- Data source type & version: marcusolsson-json-datasource
- OS Grafana is installed on: OpenShift (helm release)
- User OS & Browser:
- Grafana plugins: marcusolsson-json-datasource
- Others:

**Comment by mckn** [comment]
Hello, this should probably be a question to ask in the community forum. Please post [here](https://community.grafana.com/) next time you have a question like this.

It sounds like your proxy isn't passing all the headers to the upstream API properly. Especially this one `grafana-version` that is used to detect what version of Grafana is calling the endpoint. We use that one to try to figure out what is the latest compatible version of the plugin.
