### ISSUE TITLE
Nested Notification Policy Expected Behavior (contd.)

### ISSUE THREAD

**Issue by milinpatel13298** [grafana/grafana#57762]
**What happened**:
@armandgrillet @brendamuir
Firstly, I'm sorry to bring this up again.
I noticed the documentation change based on this commit ([06780e2](https://github.com/grafana/grafana/commit/06780e2c418591c014b3c75a30cc0cb241edcce5)) after I had brought up an issue ([#57908](https://github.com/grafana/grafana/issues/57098)) earlier (thank you for addressing this so quickly :) ).
I see it still says `When this option is enabled, you can get more than one notification for one alert.` If this is the expected behavior, I would like to reopen my issue again since I'm not receiving more than one notification (for more than one contact points) like I described.

**What you expected to happen**:
Alert sent to parent policy since the labels defined in parent policy would match;
Alert sent to child/sibling policy when labels from the parent policy match (which is obvious as that is necessary to trigger the "continue evaluating" part) AND labels defined in the child policy match.

**How to reproduce it (as minimally and precisely as possible)**:
Screenshot from earlier issue
![notification-policy-tree](https://user-images.githubusercontent.com/20999846/196688485-a6f7c4b3-cc41-4e8f-b20c-7eb5afcb6eb1.jpg)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by brendamuir** [comment]
@armandgrillet can you assign someone to help with figuring out why there's not more than one notification being delivered?

**Comment by milinpatel13298** [comment]
@armandgrillet
Just following up - Is there any update related to this issue?

**Comment by alexweav** [comment]
Hello :wave: I think the confusion here lies in the wording that was changed in the docs - continue only applies to **sibling** nodes, and does not apply to **nested** nodes.

For example, say we have two sibling nodes that both match the same alert, shown by policies B and C below:
```
         ┌──────────────────┐
         │Policy A          │
         │Matches           │
         │Contact Point: A  │
         └────┬────────────┬┘
              │            │
┌─────────────┴───┐     ┌──┴──────────────┐
│Policy B         │     │Policy C         │
│Matches          │     │Matches          │
│Contact Point: B │     │Contact Point: C │
│Continue: true   │     │Continue: true   │
└─────────────────┘     └─────────────────┘
```
When this is evaluated, `Continue: true` means that the alert will be routed to both contact points B and C.

Under the default behavior of `continue: false`, the alert is "consumed" by the first node that matches it. If we have the same scenario as above, with all nodes `continue: false`, the alert will only go to contact point B. This is what it means by "When this option is enabled, you can get more than one notification for one alert."

The key here is that B and C are sibling nodes of each other. However, in the screenshot above, none of the nodes have siblings, it's just a single chain all the way down. So, the `continue` option has no effect in this case - continue doesn't do anything to parent/child nodes. The routing will still only ever go to the furthest-out leaf that matches. It won't send to every contact point all the way down the chain.

**Comment by alexweav** [comment]
I might see what you're trying to accomplish, perhaps this is closer to what you're wanting:
![image](https://user-images.githubusercontent.com/8410871/203714157-5a10f1de-504f-4382-868b-c49be8024d8b.png)
(With continue=true on all nodes)

This says:
1. Send all alerts with `grafana_folder=Services - Astra` and `service=myservice` to contact point `One`
2. Any alerts with those labels plus `alert_type=healthcheck` and `env!=sandbox` are also sent to contact point `Two`, in addition to `One`
3. Any alerts with those labels plus `env=~dev|training` will be sent to contact point `Three`, in addition the others that match, and only if it's not a weekend. If it is a weekend, such an alert may be sent to contact point `One` and possibly `Two` if it matches.

In general, if multiple alert destinations are the goal, they need to be siblings somewhere in the tree.

**Comment by milinpatel13298** [comment]
@alexweav 
Hello, thank you for the explanation. It brings so much more clarity!
I have one more question based on your explanation and understanding how sibling vs child nodes work, say I would like to create another policy under the parent notification policy but one which is not dependent on all the labels defined under that  policy, how would I achieve that?
Maybe an example to be more clear,
I would like to create another policy with `severity=critical`, going to Contact 4 if the labels `grafana_folder=Services - Astra` AND `service=myservice` match (assuming an alert would have already been sent to Contact 1 since those two labels matched).
My confusion is that I think if I add it as another sibling node at the bottom of how you showed in your example, it would mean that the labels `alert_type=healthcheck`, `env!=sandbox`, `env=~dev|training` would also need to be present in order for the this policy to be evaluated.
Am I understanding this right? If so, what should be the ideal way to make this possible?

**Comment by milinpatel13298** [comment]
I did some testing in my sandbox GrafanaCloud instance and have come to the following conclusion(s)

**Q -** Even with the assumption that condition 3 in the example provided by @alexweav satisfies and an alert is sent to Contact 3, is it because labels from 1., 2., and 3. matched or is it just because labels from 1. and 3. matched?

**A -** It is just because labels from 1. and 3. matched.

**So, in summary, there is no way sibling nodes can be expected to work in an AND condition, that is what child nodes are for.
In addition, child nodes have an AND relation but there is no way to set them up such that alerts are sent to all contact points through out the tree path.**

As a result, the way I found I could make it to work so by doing something like below (note that there is a slight variation from the initial example)

* `grafana_folder=GrafanaCloud` -> Contact1
   * matches all alert instances -> Contact1
   * `service=service1` -> Contact2
      * matches all alert instances -> Contact2
      * `alert_type=healthcheck` AND `env!=sandbox` -> Contact2
         * `env=~dev|training` -> Contact3; Mute timings - weekends
   * `service=service2` -> Contact2
      * matches all alert instance -> Contact2
      * `alert_type=healthcheck` AND `env!=sandbox` -> Contact2
         * `env=preprod` -> Contact4

@alexweav , please feel free to correct me or leave a comment, fi you have any.
Thanks again for the explanation!

**Comment by brendamuir** [comment]
@alexweav do docs need updating for this issue? lmk and we can work together on it, thanks
