### ISSUE TITLE
Grafana Version Release Notes Link in Footer 404 Error (After v9.2)

### ISSUE THREAD

**Issue by callmehyde** [grafana/grafana#57782]
**What happened**:
On a locally running Grafana Enterprise 9.2.2 I clicked the version slug in the footer on the login page. The link took me to a page that returns a 404 error, https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-2-2/. 

**What you expected to happen**:
I expected to be taken to the Release Notes for Grafana 9.2.2, or at least taken somewhere relevant where I could find more info about this version.

**How to reproduce it (as minimally and precisely as possible)**:
1. Spin up Grafana 9.2.2 in preferred way (OSS or Enterprise, both are affected)
2. Navigate to http://localhost:3000/login
3. Click the version slug link in the footer <--- error is here

**Anything else we need to know?**:

- Recently, the Grafana team decided to no longer publish Release Notes in our documentation in favor of directing users to https://github.com/grafana/grafana/blob/main/CHANGELOG.md.  Additional context on how we're directing users on the release notes page at https://grafana.com/docs/grafana/latest/release-notes/.
- I suspect this line of code will need to be changed https://github.com/grafana/grafana/blob/main/public/app/core/components/Footer/Footer.tsx#L77.

I don't necessarily have a strong opinion one way or the other on what this should do at the moment. However, when I think about when a Changelog or Release Notes is useful to users, I think it funnels down into two primary categories.

1. Before an upgrade so developers/administrators can review and make informed choices about their deployment(s).
2. To learn about new features to the software that may change/improve workflows.

The first feels more suited to a Changelog while the second feels more like the "What's New" posts (e.g. [What’s new in Grafana v9.2](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/)). I think **both are valuable**, just in slightly different situations.

Thinking out loud...maybe if there's an update available we link to the Changelog and if there's no update available we link out to the "What's New" post for their branch?

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: N/A
- OS Grafana is installed on: Alpine (Grafana Enterprise 9.2.2 Docker image)
- User OS & Browser: macOS / Chrome
- Grafana plugins: N/A
- Others:

**Comment by mckn** [comment]
Thanks for reporting this. We should update the UI to link to the [changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#922-2022-10-25) instead of the grafana.com website.

Looks like this needs to be backported to the 9.1.8 version and forward.
