### ISSUE TITLE
Provisioned alert rules are not viewable in the UI for ADX data source

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#57793]
Provisioned alert rules show very limited amount of information about their definition.

_**Note:** I realize that UI features may depend on the used data source type. I am using Azure Data Explorer type of data source, but the issue may be actual for other data sources as well._

![image](https://user-images.githubusercontent.com/4903007/198399560-983296eb-f3ad-4fdf-8987-e475ef5e1b06.png)

Upon clicking _View_ button the situation does not improve a lot. In addition to the above, it shows group name (which is not very useful) and results of the queries (Stat/Table/Time Series), but not queries themselves or the used parameters (such as time range). _View in Explore_ button alleviates the situation a bit, but only for the first query. There is no way to view expressions for the subsequent queries.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/4903007/198400932-aaf8f887-594e-447e-a8a1-f1aa6266b590.png">

### Reproducing steps
1. Provision an alert rule through [Provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/) or [Terraform](https://registry.terraform.io/providers/grafana/grafana/latest/docs).
2. Navigate to the created rule in the UI.

### Expected behavior
All rule metadata is visible.

### Actual behavior
Only part of the rule definition is visible. Not enough for troubleshooting.

### Rationale
Debugging misbehaving alerts is complicated with the above limitations. Viewing/modifying a rule in the UI provides means for quick troubleshooting, whereas for provisioned alerts, the workaround seems to be creating a temporary rule in the UI, iteratively modifying it until its JSON definition matches to the definition of the provisioned (buggy) rule, and then figuring out what's wrong. This is a tedious process.

### Proposed solutions (alternatives)
1. **Make provisioned rules editable in the UI.**
Seriously, what is the point? If you are using Terraform, it will synchronize the rule with the IaC definition on the next run or is able to just show differences. If using Provisioning API, each call provides definition of the entire alert rule, I do not see the room for conflicts. (And if the user **wants** to shoot into their leg, why don't allow them?)
2. **Make viewing UI (upon clicking _View_ button) same as Edit UI, just read-only.**
All defining parameters must be visible. This way it at least simplifies creating of the debugging rule.
3. **Make an ability to duplicate a rule in the UI (in non-provisioned state).**

### Environment
- Grafana version: Cloud
- Data source type & version: Azure Data Explorer, v4.1.9
- OS Grafana is installed on: N/A
- User OS & Browser: Chrome
- Grafana plugins: Azure Data Explorer, v4.1.9

**Comment by mckn** [comment]
@grafana/alerting-squad-frontend Feel free to reach out to us in @grafana/plugins-platform-frontend if you need help with this. I guess we need to add something to each data source where you can ask it for the raw query etc. so we can display more information in a view like this.

**Comment by greatvovan** [comment]
See also:
- #57136 
- #57911

**Comment by stianlagstad** [comment]
This would be very useful indeed! I have a file provisioned alert that I tried to change, but Grafana did not pick up the change in my alert. It took me a while to figure out that was what had happened, and I would have figured that out sooner if it was easy for me to see the alert rule in the UI. What I ended up doing was to query the API to see what the rule looked like:

Get auth token
1. Verify that you can send a request using basic auth for the admin user:
```bash
curl "http://grafana.my.url/api/orgs" -u "admin:admin"
```
This gives a response with one organization; The default one. You can also see that default organization by going to <http://grafana.my.url/admin/orgs>.

2. Switch context to that organization:
```bash
curl -X POST http://admin:admin@grafana.my.url/api/user/using/1
```
This gives the response:
```json
{"message":"Active organization changed"}
```

3. Create the api token:
```bash
curl -X POST -H "Content-Type: application/json" -d '{"name":"apikeycurl", "role": "Admin"}' http://admin:admin@grafana.my.url/api/auth/keys
```
This gives the response:
```json
{"id":1,"name":"apikeycurl","key":"some_token"}
```

Get all alerts
```bash
curl -H "Content-Type: application/json" -H "Authorization: Bearer token_from_above" "http://grafana.my.url/api/ruler/grafana/api/v1/rules"
```

And the response from that showed me that the alert rule was not changed as I thought.
