### ISSUE TITLE
Table footer shows count value under each column

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#57799]
Maybe as designed but the current table footer shows the count under each column.
When selecting count for the footer i expected the total count either right next to Total (so under the first column) or all the way to the right under the last column.

How it looks:

![Image](https://user-images.githubusercontent.com/110845248/198494105-dad084e9-e135-4023-8590-f58b04e10fe5.png)

How i expected it:

![Image](https://user-images.githubusercontent.com/110845248/198494202-ecf13e90-5404-4bf8-a75a-ad0c84748ac8.png)

Steps to reproduce:
1. create a table with multiple columns
2. enable table footer and select "Count" from the drop down
Expected:
The count is either under the first column, next to total, or under the last column.
Actual: 
The count is under all columns 

Version: 9.2.2

**Comment by torkelo** [comment]
Count is just how many values in each field (rows), if you want total you need to select that

**Comment by codeincarnate** [comment]
Hey Torkel, I don't think that's the issue with this in particular but rather that count is repeated for each column. I'd tend to agree that this is a confusing presentation and that in the case of "count" it should only be shown once as the number of rows will remain the same regardless of what is in the columns.

**Comment by torkelo** [comment]
I guess it depends on how count works, does it count null values? or undefined? (Undefined in case of joins where they do represent a missing value)

**Comment by codeincarnate** [comment]
Currently it's just set to the length of the data, relevant code is here:

https://github.com/grafana/grafana/blob/a9fa41cb67757b7a39582d0900c8857c5332e472/packages/grafana-data/src/transformations/fieldReducer.ts#L294
