### ISSUE TITLE
Add 'Next' and 'Previous' Dashboard (Similar to time 'zoom out')

### ISSUE THREAD

**Issue by magnusboman** [grafana/grafana#5780]
At my organisation, we have currently have ~40 dashboards, with more being added.

I frequently go through and look at a range of them one by one. Having to use the dropdown list gets tedious quickly.

Having an option, next to the time zoom, to go to the next/previous dashboard would be great.

**Comment by torkelo** [comment]
you can add dashboard links to other dashboards in dashboard settings
