### ISSUE TITLE
Restricting access to /api/datasources/proxy

### ISSUE THREAD

**Issue by ictcorebiz** [grafana/grafana#5781]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [X] Question 

Please include this information:
- Grafana: version 3.1
- Datasource: Elasticsearch through proxy
- OS: Linux

Hi,

When you define a datasource of type ElasticSearch, with access through Proxy, Grafana configures a proxy datasource api which accesses the Elasticsearch instance through the Grafana instance.

This works great!

However... I do not want to give direct elasticsearch access to my users, but only want to have them access elasticsearch through Grafana userinterface.

Would it be possible to add configuration options which define which Origins / referrers can access the proxy url.

*Example:*
Currently everyone can send a GET request to:
http://www.mydomain.com/api/datasources/proxy/3/logstash-2016.08.11/_search

I would like to have an option where I can set the domains that can access the proxy like (in this way I can allow other frontends to reuse the proxy):
DatasourceProxyDomain=https://www.mydomain.com, http://tools.mydomain.com

If a request is triggered from the Grafana instance that is running on www.mydomain.com, it will have an Origin HTTP header of https://www.mydomain.com.

So my proposal is to do a Origin validation based on the configuration parameter.

This will create a hurdle (because people could inject an Origin header) for other consumers of the proxy (at least if they want to add a reference on their own webpages).

I hope this story is somewhat clear?
Sjoerd

**Comment by torkelo** [comment]
You can control this using regular Grafana user authentication options (if anyone can access the data source using GET then you must have enabled anonymous access). 

Or if you have other requirements you can put nginx or apache infront of Grafana to add custom auth options.
