### ISSUE TITLE
Debugging Suggestions

### ISSUE THREAD

**Issue by ChocoPowwwa** [grafana/grafana#5782]
Hi Grafana,

i was just wondering if you guys plan to add more verbosity on the dashboard edit page like for instance,
- Showing the success reponse in the ui instead of only the error one
- Show that request that actually sent to the datasource ( ex: elasticsearch, show the payload and the endpoint)

that would be really nice if you guys support, it could be really helpful

Thank You,

**Comment by torkelo** [comment]
yes, more inbuilt troubleshooting toolswould be great!
