### ISSUE TITLE
Basic user authentification and panel sharing

### ISSUE THREAD

**Issue by maykSVK** [grafana/grafana#5783]
I have a question about basic authentification and panel sharing. The problem ist, that when I do request in iframe like:
`http://admin:admin@localhost:3000/dashboard-solo/db/dashboard_administrator?from=1467529359471&to=1470121359471&panelId=1`
I always get redirected to login page. Am I missing something, or it is not possible to use basic authentification in this case?

If so, how can I authentificate user before dsiplaying shared panel in our application? I want to authentificate user in our application  and not to displaying login page in iframe.

**Comment by torkelo** [comment]
I dont think browers support that kind of basic auth for iframes. To embedd an iframe without login you have to enable anonymous access in you grafana.ini config gile

**Comment by maykSVK** [comment]
Yes, this is the way, but still I need to authentificate user somehow. I just want to have only one level of authorization (our application authorzation) and I do not want to expose all the grafana content to the outside world. I just want to send from aplication some kind of authorization request to grafana and then the shared panel will be visible.

Another way, is there som kind of possibility to set session cookie another way then login or oauth?
If not, are you planning this kind of functionality?

**Comment by torkelo** [comment]
you can proxy the request and use the auth header feature

**Comment by maykSVK** [comment]
I was trying to do so, but I did not succeeded. Is there any example how to do it, that I missed? 
Anyway thanks for advice, I will try to do it again.

**Comment by torkelo** [comment]
no example, but search for how to reverse proxy request in what ever application framework/language your app is using
