### ISSUE TITLE
Alerting: Global Alerts List

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#5784]
Stub for the UX work on global alert list. Updates forthcoming.

**Comment by mattttt** [comment]
Haven't annotated these or made an invision yet, but wanted to post this before @torkelo went to bed for the evening. 

![alertlist-resting](https://cloud.githubusercontent.com/assets/2886187/17601671/4cb4a4ae-5fd7-11e6-8945-356bfe405fc3.png)

![alertlist-menus](https://cloud.githubusercontent.com/assets/2886187/17601672/4f711f1a-5fd7-11e6-8836-0ec2a530d8a0.png)

![alertlist-modal](https://cloud.githubusercontent.com/assets/2886187/17601675/5304a372-5fd7-11e6-8b68-cb26e6f52cf1.png)

**Comment by mattttt** [comment]
A few notes: 

- That title should be "All Alerts"
- I know we wont have bulk actions to start, but I know it will be a highly requested feature and wanted to build for it. Just remove select boxes and actions above list for initial version. 
- Changed the filters into a multi-select dropdown like template variables in the dashboard. Much cleaner for the options we'll be presenting. 
- Tooltip for dashboard & panel names instead of cluttering the list. Still accessible, but doesnt not to be viewable at all times. 
- Quick, common actions accessible on the cog menu. 


Finally, the "how to add an alert" button goes to a modal w/ instructions. I dont think it's intuitive to a new user that new alerts cannot be created from the "Alerts" home page. The button perhaps isnt ideal, but it'll help a new user understand that this list is _only_ for existing alerts, and to add a new one, they have to go to a whole different section.

**Comment by mattttt** [comment]
Also, here's my idea again for creating a temporary dashboard showing just the selected alerts. Potentially very useful is you're troubleshooting a problem and you want to be watching an ad-hoc dashboard for a short period a time. ¯\_(ツ)_/¯

![alertlist-dynamic](https://cloud.githubusercontent.com/assets/2886187/17602102/1b49bf24-5fd9-11e6-82ca-3ca20d278256.png)

**Comment by torkelo** [comment]
this looks great, will need some space to put info on error state (query errors, notification errors). 

Also maybe at the top show current active silence rules (need to open an issue on how silence mechanic will work), but the basic initial idea I have is that you create temporary silence rules that are active for a set amount of time (1h, 10min etc)

**Comment by mattttt** [comment]
Oh! I'm glad you reminded me. 

I specifically omitted the alerting stats, thinking that they'd be more appropriate to include in the Server Stats section of Admin (as it seemed like related information). If not, then I can definitely work it in.

**Comment by mattttt** [comment]
Torkel to do:
- [ ] Change name to Alert List (from Home)
- [ ] We'll create an Alerting Home page in the future
- [ ] Create an Alerting Stats dashboard to show as many metrics as we can. 

Matt to do:
- [ ] Write copy for "Adding an alert" modal
- [ ] Suggest a design/placement for the "Execution Error!" on Alert List

**Comment by mattttt** [comment]
@torkelo to replace Dashboard Icon w/ Cog Icon and both Alert Name and Cog go to Alert editor tab.

**Comment by torkelo** [comment]
ok, just the how to modal text that is needed now then we can close this issue. 
https://github.com/grafana/grafana/blob/alerting/public/app/features/alerting/partials/alert_howto.html

**Comment by mattttt** [comment]
![screenshot 2016-08-17 09 57 43](https://cloud.githubusercontent.com/assets/2886187/17738901/255d8446-6461-11e6-92b1-f3be7db7d29c.png)


> Alerts are added and configured on the Alert tab of any existing dashboard graph panel, letting you build and visualize an alert using existing queries.
>
> Go to Home Dashboard

**Comment by mattttt** [comment]
@torkelo, @bulletfactory will have this for you tomorrow. If it's going to hold anything up, let us know and I'll make something quickly and trent can replace with the nicer one.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/17766284/b65d3f62-652a-11e6-9372-ca7fd1f0aa93.png)

**Comment by bulletfactory** [comment]
Here's the graphic that can go above the text. I have a svg of this as well (can't upload here). If svg is preferred, I can email it to you.

![add_alert_modal](https://cloud.githubusercontent.com/assets/1950595/17779865/38ab7e50-6537-11e6-81d2-9e34c0b3f553.png)

**Comment by bergquist** [comment]
![image](https://cloud.githubusercontent.com/assets/618863/17781788/053970ec-6571-11e6-9cb2-f6b3f4e42210.png)
@bulletfactory like this?

**Comment by bulletfactory** [comment]
Yep - thanks for getting that in there!
