### ISSUE TITLE
Grafana annotation edit UI crash in JavaScript code with empty query/expr result from Prometheus data source

### ISSUE THREAD

**Issue by natewang341124** [grafana/grafana#57848]
**What happened**:
Grafana annotation edit UI crash in JavaScript code with empty query/expr result from Prometheus data source.

There are two annotations that I have in my dashboard, and one of them crashes the dashboard when I try to edit it.
![Screen Shot 2022-10-28 at 1 40 12 PM](https://user-images.githubusercontent.com/10676667/198728298-2e572228-91f8-4512-9372-1bf548534569.png)

**What you expected to happen**:
The edit UI should pop up

**How to reproduce it (as minimally and precisely as possible)**:
1. Have an annotation created with Prometheus data source, using an expr that returns no data
2. save dashboard
3. now try to go to the edit UI of this new annotation, the error showed in the screenshot above pops up

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.6
- Data source type & version: Prometheus
- OS Grafana is installed on: not sure
- User OS & Browser: macOS Monterey (12.5.1), Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by mellieA** [comment]
@natewang341124 thank you for reporting this. I wasn't able to reproduce it. Can you share screenshots or dashboard json for the dashboard and annotation that produce the error?

**Comment by mellieA** [comment]
@natewang341124 thank you for sharing the solution! Is it ok to close this one?
