### ISSUE TITLE
No shown data with Null value = null misc option

### ISSUE THREAD

**Issue by dstreppa** [grafana/grafana#5785]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4
- What datasource are you using?
InfluxDB 0.12.1.
- What OS are you running grafana on?
Centos 6.7
- What did you do?
A simple data visualization with Null value Misc option set to null
- What was the expected result?
![ok](https://cloud.githubusercontent.com/assets/11214654/17591109/e28d3e78-5fdc-11e6-9412-821b585d5c41.png)

- What happened instead?
![nok](https://cloud.githubusercontent.com/assets/11214654/17591115/ecd32e7e-5fdc-11e6-9cc5-16996bc0857c.png)

I have the error only requesting less than 10 days, otherwise Grafana works fine.

**Comment by torkelo** [comment]
maybe there are nulls between every value? So no lines are being drawn.
