### ISSUE TITLE
Query inspector shows the same query repeated when prometheus source is in table format

### ISSUE THREAD

**Issue by luizluca** [grafana/grafana#57854]
**What happened**:

When Data Source is mixed, and you have two prometheus queries, "Query inspector" will show the first query as the first one and the second one. The number of rows and the json output are correct. Only the box with the "Expr: and Step:" is wrong.

**What you expected to happen**:

Each box should show each query

**How to reproduce it (as minimally and precisely as possible)**:

- Use mixed data source
- Create two prometheus queries
- Click on "Query Inspector"

**Anything else we need to know?**:
I'm using mixed datasource because I use json api. However, the issue does not seem to be related to the use of different data sources but the "Mixed datasource"

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: prometheus
- OS Grafana is installed on: sles15sp4
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@luizluca thanks for reporting this. I tried to reproduce it with two different prometheus datasources and I see both queries shown as expected. Can you share a screenshot of what you're seeing? 

![Screen Shot 2022-11-01 at 3 38 02 PM](https://user-images.githubusercontent.com/18175287/199346619-2d6caaa1-f8f6-4c4e-80d1-71d4912bfc59.png)

**Comment by mellieA** [comment]
The query screen? Can you spot what might be different from your example?

![Screen Shot 2022-11-01 at 3 38 52 PM](https://user-images.githubusercontent.com/18175287/199346753-1b0110be-042b-4c55-af6a-d58673a2be75.png)

**Comment by luizluca** [comment]
> @luizluca thanks for reporting this. I tried to reproduce it with two different prometheus datasources and I see both queries shown as expected. Can you share a screenshot of what you're seeing? 
> 
> ![Screen Shot 2022-11-01 at 3 38 02 PM](https://user-images.githubusercontent.com/18175287/199346619-2d6caaa1-f8f6-4c4e-80d1-71d4912bfc59.png)
> 
> 

I'll be away from office today but the issue is in this screen. Frames and rows have different values but Expr: is always the same in A and B. I'll try to reproduce it in the grafana playground site tomorrow.

**Comment by luizluca** [comment]
The issue is not with mixed datasources... it is with table format. I'll update the issue label.

![image](https://user-images.githubusercontent.com/836788/199791114-6ed21555-c3cd-4d99-8aaa-e9802960d94b.png)

Here is a simply dashboard:

```
{
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "9.2.1"
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "description": "Para brincar",
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "continuous-RdYlGr"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto",
            "inspect": false
          },
          "decimals": 0,
          "mappings": [],
          "max": 1,
          "min": 0,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "#F2495C",
                "value": null
              }
            ]
          },
          "unit": "string"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 28,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "maxDataPoints": 1,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "9.2.1",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "up{job=\"echo4\"}",
          "format": "table",
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "A"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "up{job=\"echo6\"}",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "B"
        }
      ],
      "title": "Test",
      "transformations": [],
      "type": "table"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Playground (sandbox)",
  "uid": "itCAljy7z",
  "version": 1,
  "weekStart": ""
}
```

**Comment by mellieA** [comment]
@luizluca thank you! I confirmed the same behavior when I change the query format option to *table*.

**Comment by gtk-grafana** [comment]
I can still reproduce this on main.
