### ISSUE TITLE
No chart is being drawn

### ISSUE THREAD

**Issue by padcom** [grafana/grafana#5787]
Latest Grafana (3.1.1), InfluxDB 0.13.0, both running on Docker 1.12, Kernel 4.4.0-21-generic.

The following shows no data:

https://grafana.aplaline.com/dashboard/db/performance?from=now-178m&to=now

The following shows data

https://grafana.aplaline.com/dashboard/db/performance?from=now-181m&to=now

The following sometimes show data:

https://grafana.aplaline.com/dashboard/db/performance?from=now-179m&to=now
https://grafana.aplaline.com/dashboard/db/performance?from=now-180m&to=now

You're free to poke around the given Grafana/InfluxDB instance - it's a test setup specifically created for this case.

Used InfluxDB queries:

```
SELECT mean("usage_system") AS "system", mean("usage_user") AS "user" FROM "cpu" WHERE "host" = 'aphrodite' AND $timeFilter GROUP BY time($interval)
SELECT mean("used") FROM "mem" WHERE "host" = 'aphrodite' AND $timeFilter GROUP BY time($interval)
```

Dashboard settings:
[performance-dashboard.txt](https://github.com/grafana/grafana/files/413671/performance-dashboard.txt)

Influxdb Datasource:
https://grafana.aplaline.com/api/datasources/proxy/3

**Comment by torkelo** [comment]
the reason looks to be that your group by time is too low, it's sometime gets lower than the rate at which you sends data, so the time range is split into to many buckets, only every other bucket has a value, and grafana cannot draẃ lines between null values (unless you in display option specify to ignore null values, but that can result in that missing data points is hard to spot). 

The solution is to specify a lower limit for group by time, like `>10s` if you send every 10s, you can do this globally in the data source setting or per graph (below the metric queries).

**Comment by padcom** [comment]
Thanks - it solved the problem.
