### ISSUE TITLE
Datasource Loki does not pass ID token header to Loki backend 

### ISSUE THREAD

**Issue by siiimooon** [grafana/grafana#57870]
**What happened**:
Datasource Loki does not pass ID token to the Loki backend when _Forward OAuth Identity_ is enabled.

**What you expected to happen**:
I expected Grafana to pass the ID token to the Loki backend of the Loki datasource, in header `X-ID-Token`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure Grafana with OAuth-based user authentication (Azure AD in my case).
2. Configure a Loki-based datasource, where option _Forward OAuth Identity_ is enabled.
3. Check whether `X-ID-Token` is passed to the Loki backend. Which it is not, in my case.

**Anything else we need to know?**:
Seems like the `X-ID-Token` header is filtered out by this method:
https://github.com/grafana/grafana/blob/main/pkg/tsdb/loki/loki.go#L122

I made this method preserve `X-ID-Token` in my local dev environment, and then Grafana started passing the header to the Loki backend.

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: Loki, 2.6.1
- OS Grafana is installed on: Alpine Linux (official Docker image)
- User OS & Browser: macOS, Chrome
- Grafana plugins:
- Others:

**Comment by svennergr** [comment]
Hi @siiimooon and thanks for your contribution.

We'll look into this during the week.
I noticed that there's a similar feature request already: https://github.com/grafana/grafana/discussions/46240

Could you maybe add a few resources and background regarding the "X-ID-Token" coming from Azure? Does Azure have some documentation around that token?

Thanks.

**Comment by siiimooon** [comment]
Hi!

The ID token is needed by our OAuth-oriented datasources, as the token [1] carries information about the end-user (e.g Azure AD group membership). The ID token is a core concept of OIDC, and is passed alongside the _access token_ - and is already widely used by Grafana. E.g:
https://github.com/grafana/grafana/blob/main/pkg/api/datasources.go#L823

Both Prometheus and Tempo datasources, already include the ID token in header "X-ID-Token" when option _Forward OAuth Identity_ is enabled. So we expected the Loki datasource to pass the ID token in the same way.

I think #46240 is a bit more comprehensive, as it proposes a datasource _option_ for putting the ID token in the _Authorization_ header. This issue suggests just to preserve the _X-ID-Token_ header for calls towards Loki backends. E.g:
https://github.com/grafana/grafana/pull/57878/files

1 - https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens 
2 - https://www.oauth.com/oauth2-servers/openid-connect/id-tokens/

**Comment by gabor** [comment]
@grafana/plugins-platform-backend could you please take a look at this? the proposed fix certainly fixes the problem, but i wonder:
- is this the "best practice" approach? (we should probably also document this in the datasource-developer-docs)
- should this be done by datasources, or should this be done somehow "more automatically"?

also, there is a somewhat-related feature-request discussion about id-tokens at https://github.com/grafana/grafana/discussions/46240 . thanks!

**Comment by marefr** [comment]
> is this the "best practice" approach? (we should probably also document this in the datasource-developer-docs)

Given how Grafana currently functions, for `CallResource`, yes that would be the proper approach. We do have some documentation, but agree it's not great: https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/#forward-oauth-identity-for-the-logged-in-user. The general rule with `CallResource` is to forward all headers. `QueryData` and `CheckHealth` are different in that sense, but we're trying to figure out how to put an end to all the header madness, mainly tracked via https://github.com/grafana/grafana/issues/47734.

 > should this be done by datasources, or should this be done somehow "more automatically"?

As stated above, the general rule for `CallResource` is to forward all request headers, i.e. like a HTTP proxy. If you do this, the idea is that Grafana should provide all needed/configured headers automatically.

> also, there is a somewhat-related feature-request discussion about id-tokens at https://github.com/grafana/grafana/discussions/46240

Not really related to this I would say.

**Comment by gabor** [comment]
@marefr wrote:

> The general rule with `CallResource` is to forward all headers.

thanks for the info! my only problem with this is that.. for example, Prometheus does it this way, but, they also maintain a list of headers that they remove : https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/resource/resource.go#L22-L39 
this seems somewhat error-prone to me, for every datasource to maintain the list-of-dangerous-headers... could we maybe strip these in generic-grafana-code? what do you think?

**Comment by svennergr** [comment]
Thank you for your contribution @siiimooon! 🚀
We just merged the PR and it should land in the next Grafana release.

**Comment by Ziphone** [comment]
Awesome! Thanks for your support and attention!

**Comment by siiimooon** [comment]
Awesome! Thanks for your support and attention!
