### ISSUE TITLE
Graph: Option to hide series from Hover

### ISSUE THREAD

**Issue by JeanFred** [grafana/grafana#5788]
- **I'm submitting a ...**
- [X] Feature request

Just as it is possible to hide series from the Legend (using Display > Series override > Legend: False), I would like to be able to hide from the Hover panel.

(I think it could even be the default when the series is hidden from the Legend)

Please include this information:
- What Grafana version are you using? 3.1.0
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 14.04

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/pull/4410 I will get back to this PR sometime in the future.

**Comment by RichiH** [comment]
This has partially been implemented as of Grafana v4.3.2 (commit: ed4d170).

You can hide "with only nulls" and "with only zeros", but what's still missing is "hide everything zero at _that_ point in time" and "hide everything null at _that_ point in time". The context is to ignore mounds of time series which are zero and focussing on the ones non-zero at the interesting point in time.
