### ISSUE TITLE
[Feature Request] alias pattern for labeling data returned from "group by" (InfluxDB)

### ISSUE THREAD

**Issue by stefanKnott** [grafana/grafana#5789]
Please include this information:
Grafana version: 3.1.0
Datasource: InfluxDB v0.13.0
Operating System: OS X El Capitan

Currently when I query my InfluxDB using the following pattern: 
	select  "metric" from "series" where tag key=~ /tag value regex/ group by  different tag key 
the default alias names return as:
	series.metric {different tag key: different tag value}

I think it'd be great to be able to create aliases based on the values returned from group by (each different tag value).  This makes sense to me as a user as I want to visualize the data related to each element returned form group by and drop unnecessary data such as series info -- this information related to how the data is stored is irrelevant to the people who will be viewing and using these graphs.

Example of current implementation:
	query: 
		select  "MaxRtt" from "pingy.results" where CorrelationID=~ /cannedPing/ group by  InstanceKey
	aliases: 
		pingy.results.MaxRtt {InstanceKey: pingy.instance.TROLOLOL}
		pingy.results.MaxRtt {InstanceKey: pingy.instance.bos}
		pingy.results.MaxRtt {InstanceKey: pingy.instance.den}

Being able to change the aliases to pingy.instance.TROLOLOL, pingy.instance.bos, and pingy.instance.den is the functionality desired and is currently unavailable given the alias patterns provided on the Grafana dashboard FE.

If this seems unreasonable or you believe that I should just restructure the data and query feel free to close.
![grafanaaliases](https://cloud.githubusercontent.com/assets/7797257/17598748/2d97c150-5fb9-11e6-81b1-01f11d2413cb.jpg)

**Comment by torkelo** [comment]
not sure I understand, you can do this with the current alias patterns. just specify `$tag_InstanceKey` in the alias input field  in your query
