### ISSUE TITLE
unexpected type found for frames custom metadata

### ISSUE THREAD

**Issue by aptMattKoe** [grafana/grafana#57903]
**What happened**:
I want to show an table of data but an Error "Could not add custom metadata: unexpected type found for frames custom metadata" occurs.
![image](https://user-images.githubusercontent.com/57363453/199010597-489bf3be-683f-48f1-8c8c-d6028b297852.png)
(table is currently empty.)

**What you expected to happen**:
That they work as other tables:
![image](https://user-images.githubusercontent.com/57363453/199010778-f341b9db-4b6b-4cbb-aa59-df8b4d228cfc.png)

**How to reproduce it (as minimally and precisely as possible)**:
Use "AppExceptions" as the table and show the Data (Explore is enough)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: Azure Montitoring
- OS Grafana is installed on: Linux Container on an Linux host
- User OS & Browser: Windows 11 and Chrome

**Comment by aptMattKoe** [comment]
Additional:
I get the same message, when I try to filter on a field that does not exist
![image](https://user-images.githubusercontent.com/57363453/199019617-4f4f355c-94d7-4ec1-9d29-0fc37196c1cd.png)
(ADO_BuildNo does not exists here)

Or did I do something wrong?

**Comment by pablo-corralllorca-extrelayr** [comment]
Hey! 

Try to change "Format as" and choose "Table". If it's "Time Series" chosen that will potentially be causing that error.

Hope it helps.

**Comment by pablo-corralllorca-extrelayr** [comment]
Same problem in here...

**Comment by pablo-corralllorca-extrelayr** [comment]
Make sure you have "Format as table" and the same thing at the top right-hand side corner. I was getting the same error until I changed that.

Hope it helps!

**Comment by aptMattKoe** [comment]
Did you mean here:
![image](https://user-images.githubusercontent.com/57363453/201362891-5f3e52c6-e2a5-40f2-b535-c58a8b9ddc8c.png)

:/

**Comment by aptMattKoe** [comment]
And its also in "Explore"
![image](https://user-images.githubusercontent.com/57363453/201363808-d561a613-1271-4a24-9ed2-8b7c79fcacc2.png)

**Comment by aptMattKoe** [comment]
One last Update (today):
If there is Data, it will be shown.

**Comment by erickroseira** [comment]
@aptMattKoe any new about it? I am also facing this same issue.

**Comment by andresmgot** [comment]
this warning only appears when there is no data in the response. Let me send a quick PR to avoid that.
