### ISSUE TITLE
Repeated Rows with Repeated Panels

### ISSUE THREAD

**Issue by grwnman** [grafana/grafana#5790]
* **I'm submitting a ...**
- [ x] Bug report
- [x ] Feature request
- [ x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.0.2
- What datasource are you using? Zabbix
- What OS are you running grafana on? centos
- What did you do? 
Added template var for application and item (metric group and metric). I want to be able to repeat rows for each group, and then repeat a graph for each metric. 
- What was the expected result? 

I expect for each row to be the group, and to contain only the items in that group
- What happened instead? 
Each group creates a repeated row correctly, but each row contains all items (many blank) since they aren't in that row.

**Comment by grwnman** [comment]
Is there a way to achieve this kind of dynamic templated dashboard?

**Comment by bergquist** [comment]
@grwnman not at the moment.

**Comment by whitelynx** [comment]
@bergquist So, is this a "wontfix", or is this something that is planned for the future? (if it's the latter, it seems that this should stay open unless there's another issue for it)
