### ISSUE TITLE
Min / Max is not accurate

### ISSUE THREAD

**Issue by clrung** [grafana/grafana#5791]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

  - Version 3.1.1 (commit: a4d2708)

- What datasource are you using?

  - InfluxDB

- What OS are you running grafana on?

  - Ubuntu 14.04 LTS

- What did you do?

  - I was curious to see the minimum and maximum network throughput I was getting

- What was the expected result?

  - I expected to see ~18MBps down.

- What happened instead?

  - I saw 9MBps down:
![result](https://cloud.githubusercontent.com/assets/5472850/17605865/8b142054-5fea-11e6-9bb0-709e29e80e39.png)

  - When I zoomed in, I saw the expected result:
![expected](https://cloud.githubusercontent.com/assets/5472850/17605874/901b4b54-5fea-11e6-8951-1cf122a6318b.png)

**Comment by bergquist** [comment]
How does the query look like?

**Comment by torkelo** [comment]
min and max cannot be accurate at the same time, InfluxDB only returns one value for each time point, if you use min or max or avg in your query as way to aggregate (combine data points as part of group by time), min only accurate if you use min in your query, max will be accurate if you use max in your query etc :) 

for total to be accurate you need sum as the aggregation function

**Comment by clrung** [comment]
@torkelo I'm not sure I understand.  Why would min/max not be accurate if InfluxDB returns one value for each time point?  Grafana should query the dataset and return the maximum/minimum value in the time range.
Why would this be dependent on my query?  If it matters, I am using the following for Rx ([glances](https://github.com/nicolargo/glances)' default template):

`SELECT mean("eth0.rx")/mean("eth0.time_since_update") FROM "localhost.network" WHERE $timeFilter GROUP BY time($interval) fill(null)`

**Comment by torkelo** [comment]
As you can see you use a mean aggregation in your query. So the max will be the max of the mean values. 

The legend values in Grafana are calculated client side by Grafana and is therefor dependent on the aggregation you have in your query.

**Comment by clrung** [comment]
Ah I see.  Thank you for the explanation, @torkelo!
