### ISSUE TITLE
Alerting provisioning: allow edits of provisioned alerts

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#57911]
As reported in https://github.com/grafana/grafana/discussions/57136, provisioned Alerting objects are not editable. This makes sense due to the fact that, if using e.g. Terraform, edits through the UI will be overridden. However, some users use the provisioning API as a normal API which makes sense as the normal API is not stable.

As a stable Alerting API is not planned just yet, we want to alleviate the pain now by allowing the editing of alerts created via the Alerting provisioning API (and maybe more if that works well enough). We should do this by adding a query parameter to provision editable alerts.

**Comment by bitethecode** [comment]
@armandgrillet Hello, I want to take this one, but I don't have much context on requirements since it's the very first time contribution. Could you assign it to me and guide me through it?

**Comment by wjordan** [comment]
I have been affected by this issue, the workaround I have been using is to just manually reset the provenance to `""` through a direct database query after using the API to create/update alert rules (e.g.: `UPDATE provenance_type SET provenance = '' WHERE record_type = 'alertRule'`).

Here is a quick fix that might work: 2c6aadcf83c341503af8a478bd1b1d8fbe7ac405- if the  create/update alert rule API routes use the optional `provenance` field in the data models, setting a Provenance of `ProvenanceNone` (empty string) should allow the API to provision editable alerts. Let me know if this approach seems acceptable and I can prepare a proper PR.

**Comment by pushkar00** [comment]
Could someone shed light on how to set this in file provisioned alerts?

**Comment by pushkar00** [comment]
Could someone provide insight on how to set provenance fields on file provisioned alerts?

**Comment by shohei-ihaya** [comment]
Is there any better way to realize this purpose than directly querying DB?
