### ISSUE TITLE
how to get the host CPU usage

### ISSUE THREAD

**Issue by yang-wu** [grafana/grafana#5793]
* **I'm submitting a ...**
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
grafana-2.0.2

- What datasource are you using?
dalmatinerdb

- What OS are you running grafana on?
smartos

- What did you do?
I want to get CPU usage of Host.

- What was the expected result?
only see the:
#cpu_stat:::user
#cpu_stat:::idle
#cpu_stat:::intr
#cpu_stat:::iowait
#cpu_stat:::syscall
#cpu_stat:::kernel

- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by bergquist** [comment]
@yang-wu this question should be directed to the dalmatinerdb projects. Grafana just shows the possible series that gets returned from the time serie database. 

But it seems like you could use #cpu_stat:::idle instead.
