### ISSUE TITLE
can not backspace after edit a graph.(chrome, grafana v3.1.1)

### ISSUE THREAD

**Issue by taurenyu** [grafana/grafana#5794]
* **I'm submitting a ...**
- Bug report

Please include this information:
- What Grafana version are you using?
   v3.1.1
- What datasource are you using?
   opentsdb 2.2
- What OS are you running grafana on?
   ios
- What did you do?
   I want to go back to last page after editted a graph
- What happened instead?
   did not backspace to last page

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
what do you mean?
