### ISSUE TITLE
dashboard toolbar is flash

### ISSUE THREAD

**Issue by siriusa51** [grafana/grafana#57944]
**What happened**:
When I view the dashboard, the toolbar in the upper right corner keeps blinking. I looked at the web code and saw that there is a control inside the toolbar that toggles the visible and hidden style.
version: 9.1.x is fine.

![dlkuv-9uhmp](https://user-images.githubusercontent.com/32152488/199185712-5df8f006-784c-49f1-86d5-7eb6b2e70e78.gif)

![image](https://user-images.githubusercontent.com/32152488/199183964-17cb76af-e81e-4758-8f6e-56cf97448d14.png)
![image](https://user-images.githubusercontent.com/32152488/199184048-e514eaae-0f6e-4eab-aa8e-f8c5cccea38f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.x
- Data source type & version:
- OS Grafana is installed on: linux(k8s)
- User OS & Browser: macos microsoft edge 91.0.864.67
- Grafana plugins:
- Others:

**Comment by maxloi74** [comment]
I am experiencing the same issue

**Comment by mellieA** [comment]
@maxloi74 which browser and OS are you using when you see this issue?

Which specific release of Grafana are you seeing this with? I wasn't able to reproduce it on 9.2.3 with the Edge for Mac browser

**Comment by silverwind** [comment]
I'm seeing this button flashing as well on Chrome 89, Windows 7, Grafana 9.2.4.

(Before you ask, no I can not upgrade Chrome in the affected environment).

**Comment by ancarpan** [comment]
I have the same issue.
* MacOS Monterey 12.5.1
* Browser: Chromium Version 89.0.4389.72 (Official Build) (x86_64)
* Grafana: v9.3.1

**Comment by alainsharemat** [comment]
I had the same problem after migrating grafana from 8.5.13 to 9.3.1

Upgrading to the latest version of my browser (Brave Browser) solved the problem.

Not working on Brave Version 1.34.81 Chromium: 97.0.4692.99 (Build officiel) (64 bits).

Works fine on Brave Version 1.46.134 Chromium: 108.0.5359.94 (Build officiel) (64 bits).

**Comment by middlestone** [comment]
I had the same problem using grafana 10.1.1-1, Chromium 89.0.4389.90, WIndows Server 2019.

**Comment by barskern** [comment]
I have the same issue in Grafana version 10.1.1 using Microsoft Edge Version 96.0.1054.53.

**Comment by Tzaphkiel** [comment]
Same issue in Grafana v10.2.0 (895fbafb7a)

**Comment by listade** [comment]
Схуяли закрыто, проблема воспроизводится!

**Comment by taoyantu** [comment]
@ivanortegaalba @torkelo @bergquist @marefr @ryantxu 
I deployed grafana version 9.5.17 in an offline environment, and the time picker flickering problem also occurred. My browser is chrome 90.0.4430.72, and the phenomenon is style="order: 3 visibility:visible" and style="order : 3 visibility:hidden" Crazy transition between states. Currently we want to use grafana, but this problem prevents us from using it normally. Please help and tell me what should I do? Thanks

**Comment by matthieu-labas** [comment]
@taoyantu it works fine with Firefox (at least the versions I tried).
Could Chrome be the new IE? ;)

**Comment by Michael-Blackwell** [comment]
I am also experiencing this issue in an offline deployment of Chrome 91 with Grafana 10.4.2.

**Comment by ara4n** [comment]
same on chrome 92
