### ISSUE TITLE
Cognite Data Fusion plugin: Cannot group the mapped numeric values from timeseries data

### ISSUE THREAD

**Issue by Gargi5** [grafana/grafana#57952]
**What happened**: We are using the cognite data fusion plugin in grafana as a datasource. We need to create a chart which shows the number of wells in each category. These categories are given as string values to the timeseries data in cognite.
For visualsing  this timeseries data, we used the map function given in the cognite documentation for grafana visualisations.
The different categories(values) are getting mapped to the specified number correctly, but we cannot group the same numbers (which are corresponding to same values) by using the available transforms in grafana

**What you expected to happen**:  Same values should get grouped so that we can display the counts of the categories

**How to reproduce it (as minimally and precisely as possible)**: Use the cognite data fusion plugin in Grafana. choose bar guage in visualisation.
Under the timeseries custom query, write the map query. for eg : map(TS{externalId='stringstate'}, ['OPEN', 'CLOSED'], [1, 0], -1)
you can refer to this documentation for details about the query: https://docs.cognite.com/cdf/dashboards/guides/grafana/timeseries/#string-time-series
Now the string values will be mapped to the corresponding numbers.
This is when we cannot group the same numbers into one bar and cannot show the count.

**Environment**:
- Grafana version: 9.1.3
- User OS & Browser: windows, microsoft edge
- Grafana plugins: Cognite Data Fusion

**Comment by mellieA** [comment]
@Gargi5 this is a commercial plugin that is maintained by Cognite. Their project site [here](https://github.com/cognitedata/cognite-grafana-datasource) suggests opening issues with the plugin in their support portal here: https://cognite.zendesk.com/hc/en-us
