### ISSUE TITLE
PanelRenderer/BarChart: Minimum height for low values

### ISSUE THREAD

**Issue by 2Steaks** [grafana/grafana#57963]
### What would you like to be added:
Enable a minimum height for bars with comparatively low values.

### Current behaviour:
<img width="1424" alt="Screenshot 2022-11-01 at 11 09 17" src="https://user-images.githubusercontent.com/4395376/199220443-2ad59fd2-b84d-4d19-82a5-dfe072981b40.png">

### Why is this needed:
It is not currently possible to increase the minimum bar height without skewing the data, which makes it difficult to interact with.

### Desirable:
<img width="1423" alt="Screenshot 2022-11-01 at 11 17 05" src="https://user-images.githubusercontent.com/4395376/199221464-721286bc-0961-44ec-8653-c268f274547f.png">

**Comment by leeoniya** [comment]
we currently use uPlot's built-in bars renderer which faithfully follows the y scale. while it's possible for me to add clamping bar min/max height to this renderer, it would be the first time that a renderer violates the core y scale such that you can no longer reliably get the top or bottom of the bar by simply doing `u.valToPos(0.5, 'y')` (the renderers are decoupled from the core). so i'm quite hesitant to introduce something like this that breaks conventions/API contract.

i wonder if a feasible/easier alternative is to offer a different interaction model that doesnt require hovering the actual bars, e.g.:

https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html

this would also play nice with our future plans to support line series in this panel, e.g.:

https://leeoniya.github.io/uPlot/demos/multi-bars.html

**Comment by codeincarnate** [comment]
Also wanted to add that we probably don't want to be intentionally incorrectly rendering data. That seems like that could open up a whole array of potential issues. 

The interaction updates make sense to me and would be nice to have regardless.

**Comment by mdvictor** [comment]
Highlight over a bar area option will be available in v9.4
