### ISSUE TITLE
Template-repeated panels incorrectly update when selecting new variable values

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#5797]
I have two template variables, `host` and `target`, both multiselect.
A row is set up to repeat on `host`.
A single panel in that row is set up to repeat on `target`.

If I load (or reload later) a dashboard with a set of variables, everything renders as expected:
<img width="1672" alt="screenshot 2016-08-12 12 25 34" src="https://cloud.githubusercontent.com/assets/299579/17619924/e48f5bb4-6088-11e6-9c47-c21d36e969bc.png">
If I start selecting/deselecting values for `target`, the following happens:
<img width="1677" alt="screenshot 2016-08-12 12 26 00" src="https://cloud.githubusercontent.com/assets/299579/17619929/ea8bfa2c-6088-11e6-8863-95c566ebde2a.png">
<img width="1673" alt="screenshot 2016-08-12 12 27 16" src="https://cloud.githubusercontent.com/assets/299579/17619931/eed8ade6-6088-11e6-9c9f-87c61a74af62.png">
<img width="1666" alt="screenshot 2016-08-12 12 27 33" src="https://cloud.githubusercontent.com/assets/299579/17619936/f457abb4-6088-11e6-8d65-a398ec9740ed.png">

(If I save the dashboard after that, these ghost panels seem to be saved as standalone panels, not repeat-cloned)

**Comment by torkelo** [comment]
Combining row and panel repeats is currently not working / supported, think there already is an issue for that

**Comment by earwin** [comment]
Okay. Is there any other way to get a matrix of panels for two multivalued variables? (putting multiple graphs in a single panel is not an option, they are already very complex)
