### ISSUE TITLE
api/dashboards/import API isn't working with folderUid

### ISSUE THREAD

**Issue by lpskdl** [grafana/grafana#57988]
**What happened**:

We are in the process of replacing or using `folderId` with `folderUid`. It seems that  importDashboard is only working with `folderId` not with `folderUid` even the `folderUid` is part of the request api. The API isn't returning an error however it keeps on adding the dashboard to the `Genera`l folder instead to the user selected folder

**What you expected to happen**:
Using `folderUid`, Importing of dashboard and placing it on a specific folder should be supported.

**How to reproduce it (as minimally and precisely as possible)**:
- the easiest way would be making a request using postman to import a dashboard `api/dashboards/import` and use `folderUid` instead of `folderId`
- don't use `general` as `folderUid`
- 
**Anything else we need to know?**:

**Environment**:
- Data source type & version:
- User OS & Browser: Chrome

**Comment by ying-jeanne** [comment]
PR to fix the issue https://github.com/grafana/grafana/pull/58415

**Comment by papagian** [comment]
Fixed by #58415
