### ISSUE TITLE
A11y: Explore page text contrast too low for WCAG AA/AAA

### ISSUE THREAD

**Issue by nemobis** [grafana/grafana#57984]
**Steps to reproduce**:

Visit the /explore page

**Actual Result**:

The list of folders is barely readable because it uses thin grey text on grey background (contrast 6.54); the filter and sort controls are even worse (3.05).

**Expected Result**

The list of folders and other controls are readable.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 9.2
- Data source type & version: N/A
- User OS & Browser: Fedora Linux, Firefox 106
- Others: Measured with https://addons.mozilla.org/it/firefox/addon/wcag-contrast-checker/
![Screenshot_20221101_154337](https://user-images.githubusercontent.com/901528/199249314-a587d5cc-0957-47d6-9820-208fd01dca6f.png)
![Screenshot_20221101_154405](https://user-images.githubusercontent.com/901528/199249324-1fabc54d-6510-4700-9521-4a271f99e384.png)

**Comment by mellieA** [comment]
I validated that the filter and sort boxes have too little contrast for the A criteria check. I'll forward this to the squad working on accessibility for review and comments

**Comment by mellieA** [comment]
With dark mode (default) it meets AA, but is still not enough contrast for AAA:

![Screen Shot 2022-11-01 at 3 53 14 PM](https://user-images.githubusercontent.com/18175287/199349047-5888ac3e-d485-4895-acdc-0218b0f783c1.png)

**Comment by ashharrison90** [comment]
hi @nemobis 👋 

thanks for raising this! i've increased the contrast on our `Select` placeholders to meet the AA criteria. whilst the folder names don't meet AAA, they do meet the AA criteria which is what we're currently working towards (see our [accessibility statement](https://grafana.com/accessibility/)) so i've left those unchanged.

hope that makes sense! 🙌
