### ISSUE TITLE
[Bug Report]  Grafana Table display duplicated rows when grouping 

### ISSUE THREAD

**Issue by summer0nguyen** [grafana/grafana#5800]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.0.3
- What datasource are you using? influxdb 
- What OS are you running grafana on? CentOS 6.8
- What did you do? Create Grafana Table with group by CHANNEL_ID
- What was the expected result?  Single Rows for each Group   CHANNEL_ID 
- What happened instead?  Duplicate rows for CHANNEL_ID

Hello,
I have data that have CHANNEL_ID and some others data  with 2 types of data : Integer , float as percent ( 0-1) . 

But when I create using a query like this : 

SELECT sum("REG_SUM") AS "REG_SUM", sum("DAY_1") AS "D1", sum("DAY_2") AS "D2", sum("DAY_3") AS "D3", sum("DAY_4") AS "D4", sum("DAY_5") AS "D5", sum("DAY_6") AS "D6", sum("DAY_7") AS "D7", sum("DAY_8") AS "D8", sum("DAY_9") AS "D9", sum("DAY_10") AS "D10", sum("DAY_11") AS "D11", sum("DAY_12") AS "D12", sum("DAY_13") AS "D13", sum("DAY_14") AS "D14", sum("DAY_15") AS "D15", sum("PER_DAY_1") AS "PD1", sum("PER_DAY_2") AS "PD2", sum("PER_DAY_3") AS "PD3", sum("PER_DAY_4") AS "PD4", sum("PER_DAY_5") AS "PD5", sum("PER_DAY_6") AS "PD6", sum("PER_DAY_7") AS "PD7", sum("PER_DAY_8") AS "PD8", sum("PER_DAY_9") AS "PD9", sum("PER_DAY_10") AS "PD10", sum("PER_DAY_11") AS "PD11", sum("PER_DAY_12") AS "PD12", sum("PER_DAY_13") AS "PD13", sum("PER_DAY_14") AS "PD14", sum("PER_DAY_15") AS "PD15" FROM "retention_report" WHERE "GAME_ID" =~ /^$GAME_ID$/ AND "SERVER_ID" =~ /^$SERVER_ID$/ AND "CHANNEL_ID" =~ /^$CHANNEL_ID$/ AND $timeFilter GROUP BY time(1d), "CHANNEL_ID" fill(none)

Note : Dx is interger , PDx are float . 

When I choose 2 Channel to get data :  
the data is duplicated like this : 

![image](https://cloud.githubusercontent.com/assets/6456947/17620942/2e456e84-60ba-11e6-9b1e-e30f4d6346e1.png)

When I choose single Channel to get data : 
![image](https://cloud.githubusercontent.com/assets/6456947/17620956/456deab4-60ba-11e6-9502-15f0dc3502f7.png)

The data is as expected . 

I'm so confused because all of anothers tables works as expected. 

Can you guys help me troubleshooting it. 
Thank you very much.

**Comment by torkelo** [comment]
You group by time and channel so you will get one row per channel and day
