### ISSUE TITLE
[Feature Request] elasticsearch with client cert authentication

### ISSUE THREAD

**Issue by dwerder** [grafana/grafana#5801]
Grafana: 3.1.1
Elasticsearch 2.3 with SearchGuard

If you need more secured elasticsearch instances there are plugins for elasticsearch like[ S.H.I.E.L.D](https://www.elastic.co/products/shield) or [SearchGurad](https://floragunn.com/searchguard-ssl/), which provide TLS CLient Cert authentication.

At the moment, the datasource for Grafana only supports basic auth.  It is still possible to use client certs, but then every user of a dashboard with elasticsearch needs to install a client certificate.

Furthermore it is not possible to use the proxy access of the grafana server.

It would be nice if we could provide a ClientKey.pem and Ca.pem or some other trustore (.pfx, .jks etc.) to the grafana server.

**Comment by joelanford** [comment]
This seems related to #2316, right?

I'm also interested in this, except for Prometheus, which I host behind a reverse proxy that performs TLS client auth. Right now I make this work by hosting both Grafana and Prometheus on the same server and configuring Grafana to talk to Prometheus on the localhost unsecured port. However, I'd like to be able to host them on different servers and still use the Grafana datasource proxy.

I can take a stab at submitting a PR. It looks like an update to ```pkg/api/datasource.go``` to add ```Certificates``` in the ```TLSClientConfig``` struct of ```dataProxyTransport``` (and probably making that a function that has an argument for the path to the cert), and then exposing it as a new form field in each of the datasources.

Anything I'm missing?

**Comment by dwerder** [comment]
@joelanford Yes it seems to describe the same issue.

**Comment by daniellee** [comment]
Fixed by #6692.
