### ISSUE TITLE
Trace View crashes when using the "Find" functionality with TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by bcarlock-emerge** [grafana/grafana#58020]
**What happened**: 
When using the "Find" functionality in the Trace pane if you start searching for a word that does exist and then typo or for any reason your input doesn't match some text in the trace the whole pane will crash with this error: 
`TypeError: Cannot read properties of null (reading 'toString')`
![GIFrecord_2022-11-01_171203](https://user-images.githubusercontent.com/101663794/199358489-9efed76a-62b8-4a11-b2f1-0df0aa529d7a.gif)

In the gif I typed Q to cause the crash, where "brokerage" works and "brokeQ" crashes, but we've been able to reproduce it essentially any time someone typos.

**What you expected to happen**:
Find functionality should gracefully fail and stop highlighting previously matching results

**How to reproduce it (as minimally and precisely as possible)**:
Open a trace from the Trace search. Type any character that doesn't exist in the trace. We've found that "/" is an almost guaranteed crash.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: Tempo v1.5.0 (helm chart 0.24.2)
- OS Grafana is installed on: Linux, deployed with kube-prometheus-stack
- User OS & Browser: Ubuntu 22.04, Vivaldi, Chrome, Brave, Firefox
- Grafana plugins: 
1. Core
2. Chaos Mesh
3. Cloudflare Grafana App
4. Discrete
5. Node Graph API
6. Pie Chart
7. Polystat
8. Scatter
9. StatusMap
10. Synthetic Monitoring
11. Worldmap Panel

- Others:

**Comment by usmangt** [comment]
Hi @bcarlock-emerge,

Thanks for opening this issue.

I was not able to reproduce this case while using Grafana version v9.2.3-997144b7 (997144b79f)

Could you please test it in the most recent version and let us know if the problem still occurs or not?

Thanks

**Comment by bcarlock-emerge** [comment]
I was able to reproduce it again on v.9.2.3-ec0c2ed029. We use the kube-prometheus-stack helm chart.
I did discover that this only happens when your original search term contains a slash.
IE: 
![image](https://user-images.githubusercontent.com/101663794/200692629-2a52fba2-b1df-45a1-bf0c-9127bb34f50f.png)
will error if you typo in the "find" dialogue for any reason.

This one: 
![image](https://user-images.githubusercontent.com/101663794/200692765-75e49163-e21f-4ea7-83a0-e5cb84a072ca.png)
does not (as demonstrated by the random characters in the Find box)

**Comment by bioplasticlining** [comment]
Hi, leaving a comment on this old issue with more information, as we've also recently encountered this issue.

The specific conditions to reproduce are that the trace contains a span which has an attribute value set to null. This causes the `toString()` method here https://github.com/grafana/grafana/blob/f72401e23b7d650c727fb6f31de558618aef4c7a/public/app/features/explore/TraceView/components/utils/filter-spans.tsx#L81 to null reference resulting a crash of the panel. Correspondingly, searching for a string which does exist but does not short-circuit the logic also results in an exception.

This is on Grafana version `Grafana v10.4.2 (22809dea50)`.
