### ISSUE TITLE
A dashboard with the same name in the folder already exists

### ISSUE THREAD

**Issue by Ganji00** [grafana/grafana#58036]
**What happened**:
Wh trying to update the dashboard through API the post request got `'message': 'A dashboard with the same name in the folder already exists', 'status': 'name-exists'` error.
**What you expected to happen**:
i want to update the dashboard so it is true that the dashboard exists, it has to as i want to update it.
**How to reproduce it (as minimally and precisely as possible)**:
1. So first Download the dashboard JSON through APi.
2. modify some values, i've edited tose:
`    response_json["meta"]["folderId"] = folder_id
    response_json["meta"]["folderUid"] = folder_uid
    response_json["meta"]["overwrite"] = True
    response_json["dashboard"]["uid"] = dashboard_uid
    response_json["dashboard"]["id"] = dashboard_id
    response_json["dashboard"]["title"] = None`
3. try to upload it back
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version:
- OS Grafana is installed on: 
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @Ganji00,

Thanks for opening this issue.

I will check it and will update the new status via comments

**Comment by usmangt** [comment]
After some investigation with my colleagues. It was found that when you do a GET request to download the Dashboard JSON data. It also comes along with meta.

However, this meta is not recognizable when doing a POST call. Therefore the API don't understand it and gives you the error. 

Looking closely at the documentation for GET to [get](https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#get-dashboard-by-uid) the Dashboard UID will give you meta and dashboard JSON.

While for POST to [update](https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#create--update-dashboard), does not need the meta part from JSON

Closing this issue as work as expected.
