### ISSUE TITLE
Dashboard after update through API moved to general

### ISSUE THREAD

**Issue by Ganji00** [grafana/grafana#58038]
**What happened**:
the dashboard after updating though APi is being moved to general
**What you expected to happen**:
It should stay in current folder that i defined:
`    response_json = response.json()
    response_json["meta"]["folderId"] = folder_id
    response_json["meta"]["folderUid"] = folder_uid
    response_json["meta"]["overwrite"] = True
    response_json["dashboard"]["uid"] = dashboard_uid
    response_json["dashboard"]["id"] = dashboard_id`
**How to reproduce it (as minimally and precisely as possible)**:
1. So first Download the dashboard JSON through APi.
2. modify some values, i've edited tose:
3. try to upload it back
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @Ganji00,

Thanks for opening this issue.

I will check it and will update the new status via comments

**Comment by usmangt** [comment]
So, I check with my colleagues and based on the [documentation](https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#create--update-dashboard), you need to provide the "folderUid":"8061X7d4z" of the folder where it is originally located.

If you do not provide it, then the default behaviour of the API is to move it into the General.

This is the JSON data I used in the Postman under "Body" 

`{"overwrite":true, "dashboard":{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 13,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "NYlpsq67z"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "NYlpsq67z"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "22,20,90,30,5,0"
        }
      ],
      "title": "leo222",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "laura222",
  "uid": "pPwJ97dVk",
  "version": 2,
  "weekStart": ""
},"folderUid":"8061X7d4z"
}`

I will now close this issue as work as expected.
