### ISSUE TITLE
Postgres: Filter is not working in the visual query builder

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#58031]
The filter is not working in the visual query builder.

https://user-images.githubusercontent.com/13729989/199454581-fdd6ec54-f72a-4e1e-8502-a614f5157356.mov

_Originally posted by @zoltanbedi in https://github.com/grafana/grafana/issues/52831#issuecomment-1299937850_

**Comment by codeincarnate** [comment]
Looking into this more deeply, this is definitely strange in that this appears to be happening either in or at the boundary of `react-awesome-query-builder`. Alias changes don't seem to be effecting this either so I'm at a bit of a loss at the moment.

**Comment by codeincarnate** [comment]
This is doing it, looks like something is being effected downstream of this. Not sure what exactly yet.

https://github.com/grafana/grafana/blob/3a5ddbfbdfc697ed862c15e6c445a262f01975db/public/app/features/plugins/sql/components/visual-query-builder/WhereRow.tsx#L42
