### ISSUE TITLE
New Scroll Feature in dashboards

### ISSUE THREAD

**Issue by Smishra81** [grafana/grafana#5803]
![scroll](https://cloud.githubusercontent.com/assets/20995612/17630631/bc368098-60dd-11e6-935f-d1b4a7f6e574.png)
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Ans. grafana-3.0.4-1464167696.x86_64
- What datasource are you using?
ElasticSearch and Graphite
- What OS are you running grafana on?
CentOS
- What did you do?
Upgraded

I see that there is a new scrolling bar  feature in my dashboards. I want to disable it.

 
**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
increase the height of the panel so all series in the legend fit, that will disable scrollbar  :)

**Comment by Smishra81** [comment]
Hey there, Thanks, but the height option has max 700 px  and my legends go beyond that :(  ??

**Comment by torkelo** [comment]
You can specify manually a higher row or panel height

**Comment by Smishra81** [comment]
ok..tried that and it seems to be working for me. however, I have around 40 dashboards which are affected...do we have any cli or bulk edit option...by chance..
