### ISSUE TITLE
Saving Live Graphs

### ISSUE THREAD

**Issue by Smishra81** [grafana/grafana#5805]
Is there a way to capture live graphs ( interactive kind of thing where one can zoom into different time slots) for viewing it offline on a different machine?

**Comment by nopzor1200** [comment]
Have you seen our snapshot feature? It sounds like it might be along the lines of what you're looking for. http://docs.grafana.org/reference/sharing/
Snapshots allow you to save static interactive dashboards that aren't dependent on the data source.
Only the data that you are viewing is saved in the snapshot.
