### ISSUE TITLE
grafana-cli should check in different locations for plugins on OS X

### ISSUE THREAD

**Issue by ctdk** [grafana/grafana#5806]
On Mac OS X, grafana-cli assumes the plugin dir is at `/var/lib/grafana/plugins`, but by default it gets installed in `/usr/local/var/lib/grafana/plugins` by homebrew. As a workaround you can specify `-pluginsDir /usr/local/var/lib/grafana/plugins`, but this isn't ideal.

We should have grafana-cli:

a) When running under Mac OS X, it should assume that by default everything grafana related is under `/usr/local` (`/usr/local/var/lib/grafana/plugins`, `/usr/local/etc/grafana`, etc.) unless told otherwise, or
b) Check `/var/lib/grafana/plugins`, `/usr/local/var/lib/grafana/plugins`, or
c) Read `grafana.ini` to see where the plugins directory is. Of course, that doesn't help very much here because the config file itself is in `/usr/local/etc/grafana/grafana.ini` rather than `/etc/grafana/grafana.ini`, which brings us back to point a).

Thoughts?

**Comment by solugebefola** [comment]
I am trying to use the grafana-cli in OSX (installed via homebrew today), but the directory is still defaulting to `/var/lib/grafana/plugins`.

**Comment by elsehow** [comment]
Any updates on this?
