### ISSUE TITLE
[Bug] Rows and Panels based on Template variables

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#5807]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I thought I've already mentioned this problem, but can't find it anymore.

Please include this information:
- What Grafana version are you using?
3.1.1 (via Repo)

- What datasource are you using?
InfluxDB 0.13.0

- What OS are you running grafana on?
Centos 6

- What did you do?
 - I want to display the port status of network devices ($device) with multiple ports ($name), so I created two template variables; type query:
   - $device: ```SELECT TAG VALUES WITH KEY = "device_name"```
    - $name: ```SELECT TAG VALUES WITH KEY = "name" WHERE "device_name" =~ /^$device$/```
 - Create a table panel
 - Set min span to 1, max span to 12
 - Select template variable $name as "Repeat Panel"
 - Row Editor: Select template variable $device as "Repeat Row"
 - Both template variable variable allow multi select and "All" options
- What was the expected result?
 - Grafana dynamically creates and removes rows and panels based on my selection

- What happened instead?
 - Grafana does successfully create rows and panels based on my selection, but doesn't completely remove panels when I change my selection, so the number of panels keeps growing. Remaining panels seem to copy values from other panels.

 - Example:
   - I select device ZUR01ARE02 and all interfaces; Grafana behaves as expected (1)
    - I then change the selection to only display interface ae0; Grafana adds the ae0 panel, doesn't remove the previous panels and replaces their values with the ones from ae0 (2)
    - If I didn't select the first interface (ae0), Grafana would remove panels of all interfaces BEFORE the one selected and keep the rest, but change their values to the values of the selected interface)

(1)
![grafana_iferror_are02](https://cloud.githubusercontent.com/assets/11089403/17639520/5d174a1e-60f3-11e6-9631-82147f399bb8.png)
(2)
![grafana_iferror_are02_ae0](https://cloud.githubusercontent.com/assets/11089403/17639524/60605db4-60f3-11e6-8dfb-0da9c88234d9.png)

**Comment by torkelo** [comment]
Combining row and panel repeats is currently not supported.

**Comment by cubranic** [comment]
Duplicate of #5715?

**Comment by JeromeVi** [comment]
@torkelo Hi, do you have an idea about when we will be able to do that ? Or maybe @bbczeuz you have find a way to make it ? Because I'm searching a way to do it too

**Comment by JeromeVi** [comment]
Hi @torkelo you say that we can't make it but in the issue #1888 your example make exactly what @bbczeuz  tried no ? Or am I wrong, because I'm actually looking for a way to make something like this and like your example in #1888.

Thank you for your answer and for your amazing work !

**Comment by veeruscmmonk** [comment]
is this fix is working in grafana v3.1?.
