### ISSUE TITLE
Alerting: have frontend consuming the backtesting API

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#58086]
Once https://github.com/grafana/grafana/issues/53443, we should use the new API to let users see how alerts would have been triggered in the past.

**Comment by yuri-tceretian** [comment]
The API is worked in https://github.com/grafana/grafana/pull/57318. Once it is merged, Grafana will support backtesting API (backtesting of query is what UI want to use).
The output format will be a wide series in the format of the data frame. 
In UI we need to think about how we present it to the user.

**Comment by armandgrillet** [comment]
Due to the API not being done yet, we will not take care of this in the next 3 months.

**Comment by KlausPopp** [comment]
Did you implement this feature in the frontend already? I am using `Grafana v10.0.0-cloud.3.b04cc88b (4f5dbbbb36)` and it doesn't seem to be there. It would be a great feature!
