### ISSUE TITLE
Canvas: Black screen on element rearrangement

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#58081]
The screen goes black when trying to rearrange (drag/drop) elements from the tree view.
Works fine in 9.1.8 - the issue was introduced in 9.2.0 - https://github.com/grafana/grafana/compare/release-9.1.8...release-9.2.0

https://user-images.githubusercontent.com/88068998/199539527-57b289b6-a72f-4fd0-b1dd-5daa21a30f1d.mov

**Comment by drew08t** [comment]
Can replicate on Chrome, but not Safari.

**Comment by nmarrs** [comment]
I'm not able to replicate this issue anymore on chrome, let's have a few more folks test it locally before closing. This potentially could of been resolved through an update to Chrome? Still kind of mysterious though

**Comment by nmarrs** [comment]
I am unable to replicate this issue so will close out this bug - if we see this in the future we can reference back 👍
