### ISSUE TITLE
Grafana report displays wrong data for mixed DST selected period (EEST and EET)

### ISSUE THREAD

**Issue by dioangh** [grafana/grafana#58085]
Hi,

In a Grafana report, when we are filtering data using a period that includes dates both before and after the end of DST, the result is to have some days reporting data at 00:00 while other days are reporting data with an offset from midnight: in some cases is 01:00 and in others 23:00.
The selected time zone in the date filters window is "Greece EET, UTC+0200" (executed 02 Nov 2022). The DST ended on 30 Oct 2022 at 04:00 thus changed to 03:00.
In the query options we set the "min interval" to "1d".
The expected behavior is when we set the "min interval" to "1d" to see all data displayed for all days at 00:00.

However, when we select a period with dates only before the end of DST or only after the end of DST, the data are aligned to 00:00 of each day as expected.
So, the problem seems to appear when the date period is "mixed DST”.

The problem is easily reproducible: In a new panel we used the internal "-- Grafana --" data source with "query type" set to "Random Walk" and selected the period: 
from: 2022-10-27 00:00:00, to: 2022-11-02 23:59:59.
In this case for the days 27, 28, 29 and 30 Oct, the data are aligned at 00:00 while for 31 Oct and 1 and 2 Nov the data are aligned at 23:00.

Attached you may find the details of the report as extracted from the "Query Inspector".

From the exported data you may see that the dates in epoch format are the below:
1666818000000 -> 26/10/2022 21:00 EEST
1666904400000 -> 27/10/2022 21:00 EEST
1666990800000 -> 28/10/2022 21:00 EEST
1667077200000 -> 29/10/2022 21:00 EEST
1667163600000 -> 30/10/2022 21:00 EEST
1667250000000 -> 31/10/2022 21:00 EET
1667336400000 -> 01/11/2022 21:00 EET
1667422800000 -> 02/11/2022 21:00 EET

As you may see all days are calculated with +3 hours offset from UTC while this is not correct for the last 3 dates where the DST ended.

Environment:
Grafana versions used: "8.4.3" and "9.2.3" with same behavior.
Data Source: "-- Grafana --"
Grafana OS: Docker image "grafana/grafana:8.4.3" and 
User OS: Windows 10
User Browser: Edge and Chrome

Best Regards,
Dimitris Ioannidis

[2022-11-02 17_48_01-Dataframe Structure.txt](https://github.com/grafana/grafana/files/9922399/2022-11-02.17_48_01-Dataframe.Structure.txt)
[2022-11-02 17_48_01-Panel Data.txt](https://github.com/grafana/grafana/files/9922400/2022-11-02.17_48_01-Panel.Data.txt)
[2022-11-02 17_48_01-Panel JSON.txt](https://github.com/grafana/grafana/files/9922401/2022-11-02.17_48_01-Panel.JSON.txt)
[2022-11-02 17_48_01-Panel Title-data.txt](https://github.com/grafana/grafana/files/9922402/2022-11-02.17_48_01-Panel.Title-data.txt)
[2022-11-02 17_48_01-Query.txt](https://github.com/grafana/grafana/files/9922403/2022-11-02.17_48_01-Query.txt)

**Comment by usmangt** [comment]
Hi @dioangh,

Thanks for opening this issue.

I have forwarded it to our team so that they can have a look and investigate further to tell you more about it.
