### ISSUE TITLE
Grafana Live Feed Data 

### ISSUE THREAD

**Issue by robert-preissl** [grafana/grafana#5808]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

This is to officially thumb up the idea of Torkel to implement a live feed mechanism into Grafana.
(as shown here: https://www.youtube.com/watch?v=EGpOvJX-8kk).
That would be awesome.

**Comment by torkelo** [comment]
:) 
https://github.com/grafana/grafana/issues/4355
