### ISSUE TITLE
Docs feedback: No permalinks

### ISSUE THREAD

**Issue by remram44** [grafana/grafana#58098]
**What happened**: The Grafana documentation has a dropdown allowing me to see documentation for a previous version. However, there is no permanent link to the current version (9.2); my only option is to link to "latest" which will change (and possibly break) with the next release.

**What you expected to happen**: I can get a permalink to the current release's documentation

**How to reproduce it (as minimally and precisely as possible)**:

* Go to https://grafana.com/docs/grafana/v9.2/setup-grafana/upgrade-grafana/, see 404
* This works but is not latest: https://grafana.com/docs/grafana/v9.1/setup-grafana/upgrade-grafana/
* This works for now but might be something else entirely (or 404) when 10.x is out: https://grafana.com/docs/grafana/latest/setup-grafana/upgrade-grafana/
* There is already a "next" so there probably doesn't need to be a "latest". Or just have "latest" immediately redirect (HTTP 302) to the version that is currently the latest

**Anything else we need to know?**:

This already seems to be causing problems with your attempt at keeping old links alive, for example https://grafana.com/docs/grafana/latest/installation/debian/ redirects to a page in v9.0 docs (9.0 is not latest...)

**Comment by Eve832** [comment]
This issue has been addressed with the "click here for latest version" banner on grafana docs when viewing old content

**Comment by remram44** [comment]
No, you have completely misunderstood the issue. There is still no way to link to any current doc page.
