### ISSUE TITLE
Offset as a Percentage

### ISSUE THREAD

**Issue by Blobitos** [grafana/grafana#5810]
- [x] Feature request

Please include this information:
V3.1.0  Source =Graphite

Would it be possible to have the "offset" work as a percentage of the value rather then a fixed value?

I am trying to create a trend that follows an average bell curve in order to measure its trend against past weeks/years and ensure it is within an agreed margin. +/- 15%

If I offset by 15 as a static point as does not work as the bell curve ramps as at peak volumes will move from 10's - 1000's making the peaks and dips much larger then 15 static points but still well within the acceptable margins

![image](https://cloud.githubusercontent.com/assets/21006620/17642922/ecca5bfe-610e-11e6-8cec-888f720ab240.png)

**Comment by torkelo** [comment]
Offset is a graphite function, if you wish for new graphite functions / behaviors open feature req with graphite project
