### ISSUE TITLE
Grafana-enterprise 9 RPM obsoletes grafana yum package

### ISSUE THREAD

**Issue by robertlich** [grafana/grafana#58103]
**What happened**:
Yum failed to install version 8.5.13, instead installing the _enterprise_ version of 9.2.3 - no enterprise version was used previously or specified. The upstream repo we are pointed at is https://packages.grafana.com/oss/rpm

**What you expected to happen**:
Yum installs version 8.5.13

**How to reproduce it (as minimally and precisely as possible)**:
On any RHEL box with a yum repo configured for: 
 `[grafana-stable]
name=grafana-stable repo
baseurl=https://packages.grafana.com/oss/rpm
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key`

Run this command:
`yum install -y grafana-8.5.13`

Dependencies Resolved
**Anything else we need to know?**:
Please check out this previous issue, I believe this is the same issue that occurred here:  https://github.com/grafana/grafana/issues/24801
And there are some enterprise packages in the wrong repo. 

full log here:
`# yum install -y grafana-8.5.13
Loaded plugins: s3iam
Package grafana is obsoleted by grafana-enterprise, trying to install grafana-enterprise-9.2.3-1.x86_64 instead
Resolving Dependencies
--> Running transaction check
---> Package grafana-enterprise.x86_64 0:9.2.3-1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved`

**Environment**: 
- Grafana version: 8.5.13
- Data source type & version: n/a
- OS Grafana is installed on: CentOS 7
- User OS & Browser: n/a
- Grafana plugins:  n/a
- Others: n/a

**Comment by dreyTee** [comment]
Yeah, same thing happened to grafana-7 package back in 2020th =)

**Comment by madogan** [comment]
We have same issue in enterprise.

**Comment by wouterdb** [comment]
Same on rocky 8.6

**Comment by robertlich** [comment]
I can confirm that we're now getting the correct package when installing grafana. Going to resolve this.
