### ISSUE TITLE
Grafana 3.1.1 http api dashboard import fails 

### ISSUE THREAD

**Issue by saargrin** [grafana/grafana#5811]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
3.1.1

- What OS are you running grafana on?
CentOS 6.7
- What did you do?  
Export dashboard then try to import JSON via POST command to /api/dashboards/db

python:

payload_dash_cdrp={
        "dashboard": {
            "id": null,
            "title": "Production Overview",
            "tags": [
                "templated"
            ],
            "timezone": "browser",
            "rows": [
                {}
            ],
            "schemaVersion": 6,
            "version": 0
        },
        "overwrite": false
    }
with requests.Session() as s:
                p = s.post("http://admin:admin@192.168.116.69:3000/api/dashboards/db",payload_dash_cdrp)
                print p.text

- What happened instead?
./testRest.py
[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]

**Comment by torkelo** [comment]
did you set Content-Type header to application/json?

**Comment by saargrin** [comment]
yes

also,other API requests using the same python lib work, for example datasource creation and others 

this does work : 


payload_ds={
  "name":"DS_TSDB",
  "type":"opentsdb",
  "url":"http://lab-hdp004:4242",
  "access":"proxy",
  "basicAuth":false
}
with requests.Session() as s:
                p = s.post("http://admin:admin@192.168.116.69:3000/api/datasources",payload_ds)
                print p.text

**Comment by torkelo** [comment]
look at the request the grafana api makes when it saves a dashboard, no one else has had any issues with it (and the UI is using it), so must be doing something wrong in your code

**Comment by saargrin** [comment]
can you please guide me how to find that? i enabled debug log level for grafana but did not see that actual request 

i compared the fields from a json file that is created by making a new dashboard in the gui with the data im submitting and it seems im not missing anything ..

**Comment by torkelo** [comment]
chrome dev tools network tab

**Comment by annym** [comment]
Was a solution found for this issue? 

I am using Grafana Version 4.1.1.

I am trying to create a dashboard through the HTTP API in Python (using the requests library. Version: 2.4.3) however I get the error message:

[{"classification":"DeserializationError","message":"json: cannot unmarshal string into Go value of type models.SaveDashboardCommand"},{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]

I am using:

```
    dashboard = {
          "dashboard": {
            "id": None,
            "title": "pyDashboard",
            "tags": ["templated"],
            "timezone": "browser",
            "rows": [
              {
              }
            ],
            "schemaVersion": 6,
            "version": 0
          },
          "overwrite": False
    }
    db_json = json.dumps(dashboard)
    response = session.post(url=url_pattern.format(**params), json=db_json)
```

And have set header Content-Type to application/json. 

If I use a REST Client it does work (using the same json). 

I've even copied the request payload I see in the dev tool when saving a dashboard through the UI and keep hitting the same issue.

**Comment by annym** [comment]
A quick update for anyone who faces this same issue, just found the solution:

`response = session.post(url=url_pattern.format(**params), **data=**db_json)`

** Though db_json is a valid JSON

**Comment by jjo** [comment]
For other ones dealing with this error: I was trying to post a dashboard directly with its JSON and getting above error - you *need* to wrap it with e.g.  `{ "dashboard": <dashboard json>, "overwrite": true }`, I'm using:
```
echo '{"dashboard": '$(cat dashboard.json)', "overwrite": true }' | \
  curl -H "Content-Type: application/json" --data-binary @- http://admin:PASS@grafana:3000/api/dashboards/db
```
