### ISSUE TITLE
[Graph Feature] Allow X-value to be a non-time metric

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5812]
Graph panel should support non time x-axis

- [x] Time series name on x-axis and last/total/max/etc as y
- [x] Table data format queries (ex from InfluxDB)
- [x] Json data query from ES

**Comment by hl68fx** [comment]
Hi,

does this feature already work?
I have installed the latest master branch and could not find a way to show non-timeseries data.
Thanks for your great work!

Kind regards,
Tom

**Comment by torkelo** [comment]
There is some refactoring work before this can be merged to master

**Comment by hl68fx** [comment]
Cool, thank you very much for the information! I am looking forward to using this new feature when it is ready :)

**Comment by inbilla** [comment]
+1
Would this allow a similar thing to this PR?
https://github.com/grafana/piechart-panel/pull/50

**Comment by torkelo** [comment]
yes, but in bar chart form

**Comment by inbilla** [comment]
(See the link - it's a pull request to make the piechart a bar graph :) 30 lines)

**Comment by Will-Beninger** [comment]
@torkelo 
Is this feature going to support the following: (Want to check before I submit a separate feature request)

From an example (influxdb) query:

> select temperature from database group by server, Locale

And the data value could be either Current, Max, Min, Avg, etc

Locale | Server 1 | Server 2 | Server 3 | Server 4
--------|----------|----------|-----------|----------
Chassis | 32C | 33C | 34C | 35C
Ambient | 20C | 21C | 22C | 23C
CPU | 40C | 40C | 40C | 40C
Memory | 26C | 25C | 27C | 28C

**Comment by txisme** [comment]
I can't seem to plot data with X-Axis mode in series. In Metrics tab i have group by terms, in which the term has integer values and i would like to see the data ordered by those values.

**Comment by jacobweber** [comment]
Would this allow segmented bars, the way the current Graph panel does? That's something that the pie chart doesn't have, obviously, so I just wanted to make sure it will work in a bar chart.

**Comment by veeruscmmonk** [comment]
which release of grafana this feature (Allow X-value to be a non-time metric) avilable

**Comment by lakal-malimage** [comment]
+1

**Comment by daniellee** [comment]
@veeruscmmonk it was added in v4.0 (the commit is from the 22 September last year).

@lakal-malimage what's the +1 for? This feature has been in Grafana since October last year. Some feature that you are still missing?

**Comment by Yaiba782** [comment]
@daniellee Hello,

I'm using grafana 4.1.1, and yet I still can't use graphs without a time-driven abscissa.

"this.datapoints[a][1] is undefined".
Yet I only want to display the Count of http codes returned, grouped by each of those codes. It works with the timestamp used in abscissa, not without it.

**Comment by daniellee** [comment]
@Yaiba782 what data source are you using? Sounds like it should work.

**Comment by veeruscmmonk** [comment]
@daniellee  do you have any demo dash-board for  x-axis non time_series data?

**Comment by torkelo** [comment]
Graph panel does not yet support non time series, it can display time series in two ways (using time as x axis, or using each time series as x-axis). But it needs time series to display anything. It does not work with table or json data yet.

**Comment by Yaiba782** [comment]
@daniellee 
Elasticsearch, Im doing the exact same thing with an other data viz tool, and it works

**Comment by torkelo** [comment]
@Yaiba782 make sure you have a Date Histogram as the last group by in your ES query, otherwise it will not work with graph panel

**Comment by daniellee** [comment]
@veeruscmmonk like Torkel says, it does not work with non time series data. But in the example @Yaiba782 gave, it sounds like it is time series data.

**Comment by wols** [comment]
> @torkelo : It does not work with table or json data yet.

I need this feature for use with data source Elasticsearch also:

My docs have eg. {offset:6, delay:19} and I wish a point on coordinates x=19, y=6.
The x-axis should begin with min(delay) and end with max(delay).
See (not my) http://doc-tcpip.org/Images/server.jpg

**Comment by SnchitGrover** [comment]
Any updates on this?

**Comment by demonkoryu** [comment]
Want to throw mention that there are other dimensions - like build number - that would be perfectly served by this feature.

**Comment by mikich** [comment]
I need this feature badly, but It looks like no answer till now? isn't it?

**Comment by ganeshmuralidhar** [comment]
+1 - I am looking to plot a graph with Build Number on x-axis and page times on y-axis. I cannot see an option to select the terms of Build Number on X-Axis.

**Comment by CFlatWouldbeMinor** [comment]
+1 I would also like to compare builds, (Non time series based). Dummy time series are possible, but not nice. I am also open which db to use underneath.

**Comment by xiequanqin** [comment]
+1

**Comment by Nefariis** [comment]
+1

**Comment by cyrilthank** [comment]
+1

**Comment by fdamador** [comment]
+1

**Comment by jo-tud** [comment]
+1

**Comment by estan** [comment]
@torkelo: I'm very much interested in doing what @demonkoryu and @ganeshmuralidhar describes (having build number on the X-axis). I see that this issue was closed. Is that possible currently?

**Comment by alext9** [comment]
@demonkoryu, @ganeshmuralidhar, @estan:

Not sure about other data sources, but I'm using influx and have been able to set up something similar to build number on the X axis.

You'll need to tag your measurements with a buildNumber tag.
Add a graph with:
SELECT field(yourMeasurement)
GROUP BY tag(buildNumber)
ALIAS BY $tag_buildNumber
Change X-Axis mode to be Series

**Comment by Rodionc** [comment]
@alext9, @demonkoryu, @ganeshmuralidhar, @estan, @CFlatWouldbeMinor
Trying with mySQL datasource:
query: SELECT duration as value, name FROM stat.ejdub2 limit 20;
Getting "Found row with no time value" below Query window, trying select mode for X-axis on Axis tab - it shows all 3 options for x-axis (time\series\histogram) but text in field still empy.

**Comment by GedPL** [comment]
I'm also interested in this feature to have SystemName (string) on X-axis and stacked bar (values ERROR/SUCCESS/WARNING - count) for each System.

**Comment by cauepor** [comment]
I have the same problem of @Rodionc , on the X-axis selection it shows the options but not when I click on Series it maintains the select in blank, any way to solve this?

**Comment by ewortzman** [comment]
@torkelo You said that graphs can be set to display each time series as an x-axis tick.  How do you set that option?

**Comment by mikich** [comment]
This feature is working well, but I missing "stack" option with bar chart functionality not working :(

**Comment by benkindt** [comment]
@Rodionc I have the same issue. I can not assign any X-Axis Mode, Name or Value in Axes Tab. It remains blank.
Getting:
> Panel data error: {message: "No field name specified to use for x-axis, check your axes settings"}

Trying to set the axes settings:
> TypeError: Cannot read property 'map' of undefined
    at a.getDataFieldNames

**Comment by JamesGalt** [comment]
@alexanderzobnin @torkelo 

> Graph panel does not yet support non time series, it can display time series in two ways (using time as x axis, or using each time series as x-axis tick). But it needs time series to display anything. It does not work with table or json data yet.

Is it now supported? if not will it be?
Thanks

**Comment by abhagupta** [comment]
We need this as well.

**Comment by jacastellano** [comment]
We need this as well.

**Comment by RustamGimadiev** [comment]
+1

**Comment by nichtleiter** [comment]
+1

**Comment by sanderp42** [comment]
+1. I really need this feature as well. I would like make a scatter plot with non-time values on the x-axis.

**Comment by jdmaresco** [comment]
+1

**Comment by dsmale** [comment]
+1

**Comment by matfiej88** [comment]
+1

**Comment by NoelzeN** [comment]
+1 for this, still no solution available? Wanted to migrate from  Redash to Grafana but need to be able to plot a table as chart for that :(

**Comment by nthienan** [comment]
Does anyone know any workaround?

**Comment by Kazmirchuk** [comment]
+1 I can't imagine the leading industrial monitoring solution on the market without such basic feature

**Comment by yayitazale** [comment]
+1, still waiting for this feature.
