### ISSUE TITLE
grafana-cli cannot resolve grafana.net

### ISSUE THREAD

**Issue by sc0rp10** [grafana/grafana#5814]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?

`Grafana cli version 3.0.4`
- What OS are you running grafana on?
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```
- What did you do?
`grafana-cli plugins install grafana-piechart-panel`
- What was the expected result?

Installed plugin
- What happened instead?
```
Error: Get https://grafana.net/api/plugins/repo/grafana-piechart-panel: dial tcp: lookup grafana.net on 10.7.66.144:53: no such host
```

I attached gist with full log https://gist.github.com/sc0rp10/9d113d19856d2fcdc952a8b659e131e9
Other tools such a `dig` or `curl` can resolve this address. grafana-cli can't

**Comment by bergquist** [comment]
Seems like your dns server failed (10.7.66.144:53)

It this persistant? Are you using a proxy server?

**Comment by sc0rp10** [comment]
@bergquist are blind? you can't see attached log? my dns server is not failed, failed your software

**Comment by torkelo** [comment]
@sc0rp10 so you still get the same error? what happens when you try to access https://grafana.net/api/plugins/repo/grafana-piechart-panel  in your browser? try wget it from your server, any difference? 

Might have been a temporary network issue.
