### ISSUE TITLE
The latest version of grafana does not have Phlare's data source

### ISSUE THREAD

**Issue by hexiang1219** [grafana/grafana#58158]
Grafana version: v9.2.3
datasource plugins: 
![图片](https://user-images.githubusercontent.com/34543240/199750078-fe2aec2c-722f-452a-ad3c-6ee441d89bda.png)
own datasource：
![图片](https://user-images.githubusercontent.com/34543240/199750569-09103c65-7a7b-4f32-9465-7270f57d76ea.png)
![图片](https://user-images.githubusercontent.com/34543240/199750684-1283cee8-5a32-42ee-ab7e-33fbce0858a1.png)
![图片](https://user-images.githubusercontent.com/34543240/199751002-149f066e-2965-4dcc-8937-eb2c9a31a83b.png)

**Comment by usmangt** [comment]
Hi @hexiang1219,

Thanks for opening this issue.

I am checking it out with our team and will get back to you once have more information.

**Comment by usmangt** [comment]
Hi @hexiang1219,

So I found out that if you are using container technology e.g. Docker, you can get it easily by simply following the [documentation](https://grafana.com/docs/phlare/latest/operators-guide/get-started/).

For getting it on a local installation, you need to go to https://grafana.com/grafana/download and have to change to OSS then there is the Nightly Builds button top right. 

That generates the links to https://grafana.com/grafana/download/9.3.0-87537pre?edition=oss 

which can be used to download it. After that, you need to make a small change in the configuration file  inside the [feature_toggles] section i.e.
enable = flameGraph

As this is really a very recent release with only a few latest nightly builds so it could happen that the nightly build links get invalid quickly. 

The rest you find more in the documentation in the [release notes](https://grafana.com/docs/phlare/latest/).

I will now close this issue but feel free to open if you have any questions
