### ISSUE TITLE
Let users know and migrate their unused provisioned legacy alerts in frontend

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#58169]
Until recently, legacy alerting => Grafana Alerting was not allowing the migration of provisioned legacy alerts.

Even now, users on Grafana Alerting might have legacy alerts provisioned in dashboards that are useless. Those need to be able to be migrated.

This is not the backend issue https://github.com/grafana/grafana/issues/43546, only frontend.

More details needed.

**Comment by konrad147** [comment]
FE part waits for BE https://github.com/grafana/grafana/issues/43546 implementation
