### ISSUE TITLE
Alerting: Update rule API to address folders by UID

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#58184]
**Description**:
Currently, unified alerting API address folders by name. However, this will not work in the future when nested folders feature (https://github.com/grafana/grafana/issues/10339) is released. We need to update the API to address folders by UID.

**Comment by armandgrillet** [comment]
There was a kickoff meeting about nested folders last week which is why this issue has been created. @yuri-tceretian which API are you talking about?

**Comment by yuri-tceretian** [comment]
https://github.com/grafana/grafana/blob/1dd3f9f3e6bb84a3b1c0894e2b3d6cff2cc2e206/pkg/services/ngalert/api/authorization.go#L42-L60
