### ISSUE TITLE
Grafana 9.2.2 Mysql/SQLQuery drag and  drop is gone

### ISSUE THREAD

**Issue by tedraymond** [grafana/grafana#58199]
**What happened**: after upgrading to 9.2.2, the Query organization grabber does not work.

**What you expected to happen**: expected to have the ability to reorganize queries based on criteria

**How to reproduce it (as minimally and precisely as possible)**: 9.2.1 the drag and drop works. 9.2.2 it does not

**Anything else we need to know?**: I was also able to scale the size of the query window prior to 9.2.1

**Environment**:
- Grafana version: 9.2.2
- Data source type & version: SQL Server and MYsql 
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

![image](https://user-images.githubusercontent.com/73015641/199833950-a30ff8ad-39fb-4605-bd82-98fd2f334193.png)

**Comment by tedraymond** [comment]
Issue exists with any data source

**Comment by mellieA** [comment]
@tedraymond thanks for reporting this. There is a fix for this coming: https://github.com/grafana/grafana/pull/56515
