### ISSUE TITLE
Add sample code and component preview in the `@grafana/ui` storybook website

### ISSUE THREAD

**Issue by hongbo-miao** [grafana/grafana#58190]
It would be great to improve the `@grafana/ui` storybook website. Thanks! 😃

1. Add sample code:

   Some components are missing no code. So it is hard to know how to use this button for users.
   For example, https://developers.grafana.com/ui/latest/index.html?path=/docs/buttons-button--basic
   <img width="1157" alt="image" src="https://user-images.githubusercontent.com/3375461/199805896-87907cc9-f611-44f6-b68d-29fc145ba4ad.png">

3. Add component preview:

   Some components are missing visualization. So it is hard to know how it looks.
   For example, https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-cascader--simple
   <img width="1148" alt="image" src="https://user-images.githubusercontent.com/3375461/199806456-ba7f1f73-db80-41c1-b68a-8c5d6e6c273d.png">

**Comment by JoaoSilvaGrafana** [comment]
Hey @Hongbo-Miao thanks for raising this! We have a whole project to improve our storybook specifically on the documentation side, it will be a long process but thanks for requesting this issue, they are great suggestions! Added it to the project so we can take them in when we add more to the docs 😄

**Comment by staton-hyse11** [comment]
Added to our backlog. This is a great idea and something we should consider in the future. Thanks @Hongbo-Miao!

**Comment by staton-hyse11** [comment]
Historical issue: [#41071](https://github.com/grafana/grafana/issues/41071) for reference and linked similar idea

**Comment by staton-hyse11** [comment]
@JoaoSilvaGrafana would this still be work we want to do?

**Comment by JoaoSilvaGrafana** [comment]
We will be closing this issue as we are gradually moving to using the [Saga website](https://grafana.com/developers/saga/about/overview) to have sample code and component previews 🙏
