### ISSUE TITLE
State Data in grafana 

### ISSUE THREAD

**Issue by sahilthapar** [grafana/grafana#582]
I'm using InfluxDB as my source which has the capability of storing strings but I don't have a way of representing state data in grafana.
Right now I'm using a hack, creating a binary signal for each state to represent which state is currently active but it requires adding a new column in Influx for every state and feels terribly inefficient. While annotations are helpful, I was wondering if there can be a way to represent state data like in a stripe chart without using the hacks.
I'm new to Angular, but I'm going to try and look into incorporating stripe chart support any kind of help would be great, like for which source code files should I be looking at !
Thanks
The hacks I use right now, 

![displaystyles](https://cloud.githubusercontent.com/assets/3141362/3567161/b5763430-0b10-11e4-8c23-e092c9f6a063.png)
![individualseries](https://cloud.githubusercontent.com/assets/3141362/3567162/b5767c24-0b10-11e4-8626-97d96b05916f.png)
  

Edit: I've been thinking about it and would like to know if there is a way to map a string column of influx to a colour in a Grafana panel rather than a value(metric)

**Comment by torkelo** [comment]
This can be handled by annotations for now, might be solved better with the alerting feature
