### ISSUE TITLE
How to sort the label's name value?

### ISSUE THREAD

**Issue by haroldHT** [grafana/grafana#58204]
I want to sort the label's name like this, i using time series now:
![image](https://user-images.githubusercontent.com/13550119/199914834-6ba29470-4991-461d-b5fe-b13025d80187.png)

- Grafana version: Version 9.2.3 (commit: ec9c2ed029, branch: HEAD)
- Data source type & version:
prometheus version 2.36.0 
- User OS & Browser: 
CentOS Linux release 7.7.1908 (Core)
- Others:

https://github.com/grafana/grafana/issues/58204#tasklist-block-5a4327e2-7b12-41a5-962b-42eb0ca81289

**Comment by kheuser** [comment]
The legends order is defined by the order of the query name on the panel. So if you use the default "A, B, C" names when you created the panel, then for your case you would make the label 8 "A" then label 57 "B".
![Screenshot 2022-11-04 at 9 58 13 AM](https://user-images.githubusercontent.com/72710395/200006672-3da91b06-e21a-4cb0-a391-9c6e4db5b684.png)

**Comment by haroldHT** [comment]
Thanks for your msg, but I have a lot of number label, it is not a good choose.

> The legends order is defined by the order of the query name on the panel. So if you use the default "A, B, C" names when you created the panel, then for your case you would make the label 8 "A" then label 57 "B". ![Screenshot 2022-11-04 at 9 58 13 AM](https://user-images.githubusercontent.com/72710395/200006672-3da91b06-e21a-4cb0-a391-9c6e4db5b684.png)

**Comment by haroldHT** [comment]
> The legends order is defined by the order of the query name on the panel. So if you use the default "A, B, C" names when you created the panel, then for your case you would make the label 8 "A" then label 57 "B". ![Screenshot 2022-11-04 at 9 58 13 AM](https://user-images.githubusercontent.com/72710395/200006672-3da91b06-e21a-4cb0-a391-9c6e4db5b684.png)

Thanks for your reply, but there is too many number, it is not a good choose

**Comment by usmangt** [comment]
Hi @haroldHT,

Thanks for opening this issue.

You can use the Transformation and then inside use the "Organize fields". For e.g. I am pulling some basic data from a repo where it will by default show many fields but I have hidden most of the unwanted ones and even can rename the ones which I want to get displayed in the dashboard.

See the attached screenshot:

![image](https://user-images.githubusercontent.com/69509548/200552426-ac3c1aa0-92f2-42a0-bf68-65ef456aa4d0.png)

Here are the links to the Transformation documentation:

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#organize-fields

More detailed version:

https://grafana.com/docs/grafana/v9.0/panels/transform-data/

I hope this helps.
