### ISSUE TITLE
Snapshots cannot be created via API without setting `id` to an arbitrary value. 

### ISSUE THREAD

**Issue by ndombroski** [grafana/grafana#58200]
A PR that was shipped with v9.0.9 amended `api` package to return an error when attempting to create a snapshot of a dashboard where the `id` field has a 0 value. This partially breaks the snapshot API, as attempting to create a snapshot from source json that does not set the `id` field will cause an error. 

**What happened**:
Attempting to create a dashboard snapshot from source using the Snapshot API returned the following error:
```Creating a local snapshot requires a dashboard``` 

**What you expected to happen**:
Snapshot to be created

**How to reproduce it (as minimally and precisely as possible)**:
The example request included in the HTTP API for creating a snapshot will experience this issue: https://grafana.com/docs/grafana/latest/developers/http_api/snapshot/

**Anything else we need to know?**: 
N/A

Grafana version: v9.1.6

**Comment by usmangt** [comment]
Hi @ndombroski ,

Thanks for opening this issue.

I will ask our team to have a look. Can you please share the link from where you build the dashboard snapshot from the source?

Thanks

**Comment by ahurtaud** [comment]
Also please consider this issue discussions and particularly this comment as I guess snapshot API usage must be re-thought heavily :)
https://github.com/grafana/grafana/issues/54578#issuecomment-1303531112

**Comment by gamab** [comment]
I just merged a fix. It will be available in 9.3, next 9.2 (I think 9.2.7), next 9.1 (I think 9.1.9).
Thanks for reporting!
