### ISSUE TITLE
OAuth: allow requesting refresh token from authorization flow

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#58202]
Following #56076, Grafana will need to request a refresh token in its initial oauth2 auth flow, in order to maintain active user sessions that last longer than the short-lived access-token duration. However, the internal authorization-redirect code is hard-coded to `access_type=online`: https://github.com/grafana/grafana/blob/376f4b0cc76d24dbfab8fc13cad7ec30abbcd2be/pkg/api/login_oauth.go#L100

This setting prevents a refresh token from being returned by some OAuth providers. (Specifically, I've encountered this issue when using Google OAuth).

Further, it's not possible to override the `access_type` setting by adding a query parameter to the `auth_url` config, as this results in a duplicated query parameter which the Google OAuth provider rejects (with the error message: `OAuth 2 parameters can only have a single value: access_type`).

Fixing this issue will need to either change the hard-coded auth redirect setting to `oauth2.AccessTypeOffline` so that `access_type=offline` is passed to the authorization redirect, or allow a query parameter passed to the `auth_url` config to override (and remove) the existing `access_type=online` query param when the url is constructed.

**Comment by mgyongyosi** [comment]
@wjordan Thank you for this report 💯 , this part is still in active development and I'm going to look into this issue!
