### ISSUE TITLE
Cannot properly secure snapshot?

### ISSUE THREAD

**Issue by phutchins** [grafana/grafana#5821]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Elasticsearch, zabbix
- What OS are you running grafana on? Ubuntu 14.04
- What did you do? Created a snapshot
- What was the expected result? The snapshot would be shared with all users
- What happened instead? No data was loaded into the dashboards windows. If I set auth.anonymous enabled to true, it works but this is pointless as the point of the snapshot is to make it read only.

Am I missing something about the way this works?

**Comment by torkelo** [comment]
> The snapshot would be shared with all users

What do you mean? When you get the snapshot link anyone with the link should be able to open it without login. If the graphs where empty maybe the metric queries did not complete in time (all metric queries need to complete within 4 seconds)

**Comment by phutchins** [comment]
Hey @torkelo, so everything works just fine if auth.anonymous.enabled = true. As soon as I set it to false, I get the results described above. The dashboard loads in just a few seconds so I don't think it's the 4 second limit. 

Here are snapshots of the dashboard that didn't load correctly after setting auth.anonymous.enabled to false.

<img width="1162" alt="screen shot 2016-08-19 at 1 09 13 pm" src="https://cloud.githubusercontent.com/assets/1074345/17817850/a69dc4fe-660e-11e6-85ec-5f997e94c892.png">

<img width="1155" alt="screen shot 2016-08-19 at 1 09 45 pm" src="https://cloud.githubusercontent.com/assets/1074345/17817860/ab96660a-660e-11e6-93f5-90c6d4afbe42.png">

Any thoughts on what I might be missing? Thanks so much for an awesome tool and your help! :)

**Comment by phutchins** [comment]
@torkelo, any thoughts? I'd really love to get this working...

**Comment by torkelo** [comment]
It looks like the snapshot data is not there which usually means the metric queries did not complete within 4 seconds

**Comment by phutchins** [comment]
@torkelo ok, I think you're right about this. I created a super simple dashboard and the snapshot for that works. I limited the time range which my larger dashboard is using and still couldn't get it to display. 

Can you point me to where in the code this 4 second limitation happens? I'd like to understand where/how this is happening. If it's on the total time of all requests combined, or just the longest if they're all running in parallel...

**Comment by phutchins** [comment]
@torkelo I've looked through the source and can't seem to find where this 4 second limit is being set. Any way you could point me in the right direction in the source as to where this limitation is happening?

**Comment by phutchins** [comment]
@torkelo, or anyone else, some input would be great... This arbitrary 4 second limit will make me move away from Grafana if it can't be overcome and I really like the project so I'd rather not. Anything?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/shareSnapshotCtrl.js#L56

**Comment by phutchins** [comment]
@torkelo, thanks a ton! What do you think about a PR that allows adjusting this timeout from the config?
