### ISSUE TITLE
PluginPage: Expose a mechanism for customising the `PageHeader`

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#58210]
- [ ] add documentation for `PluginPage` props

**Comment by amy-super** [comment]
A few items that came up in discussions that we should include here for visibility:

- Ideally we will limit the action buttons to 2. Any place we need 3 or more, we should have a primary button and a secondary `more actions` (label of your choosing) button to keep buttons from proliferating across the top of the page.
- Ideally we will also limit `info` style items to no more than 3 - again to keep items from proliferating. Additional information realistically isn't all that helpful and can be placed in an accordion kind of item under the title and subtitle. 
- For narrow viewports, we can collapse all buttons into one actions button, and `info` items can wrap underneath the title/subtitle - or make use of the accordion mentioned above. 

@teddyba and @staton-hyse11 tagging you here for visibility.
