### ISSUE TITLE
[Bug] Migrate dashboards from graphite broken

### ISSUE THREAD

**Issue by gesquive** [grafana/grafana#5822]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? v3.1.1
- What datasource are you using? graphite
- What OS are you running grafana on? linux
- What did you do?
  - go to `http://<grafana_instance>/dashboards/migrate`
  - make sure the correct graphite datasource is selected under "Load dashboard from Graphite-Web"
  - click on the "list dashboards" button
- What was the expected result?
Expected a list of graphite dashboards to appear so i can import them
- What happened instead?
Nothing happens, exception is shown in the console under chrome:
```
TypeError: d.datasource.listDashboards is not a function
    at boot.8ba215a1.js:formatted:12711
    at h (boot.8ba215a1.js:formatted:41743)
    at boot.8ba215a1.js:formatted:41753
    at n.$eval (boot.8ba215a1.js:formatted:42229)
    at n.$digest (boot.8ba215a1.js:formatted:42159)
    at n.$apply (boot.8ba215a1.js:formatted:42256)
    at HTMLButtonElement.<anonymous> (boot.8ba215a1.js:formatted:46144)
    at HTMLButtonElement.dispatch (boot.8ba215a1.js:formatted:36097)
    at HTMLButtonElement.q.handle (boot.8ba215a1.js:formatted:35989)
```

From the git history, the `listDashboards` and `loadDashboard` functions were removed from `public/app/plugins/datasource/graphite/datasource.ts` in PR #5321. I can't tell why the functions were removed, but they are needed for the graphite migrate dashboards feature.

**Comment by obfuscurity** [comment]
I think you mean [this commit](https://github.com/grafana/grafana/commit/81e9aa4de430ac9a865ecad91feb6cea91c0666c#diff-fba613d41443865e5e1d416756aae4a4L180).

**Comment by gesquive** [comment]
yup, that is the line!

you just taught me i can link to a specific line, thanks!

**Comment by torkelo** [comment]
where did you find the link to the migrate page? The feature removed (the import process was not very good and not used by many). Must have forgotten to remove the page, is there a link to the page in the app or did you just specify the url?

**Comment by gesquive** [comment]
I looked through the changelists and never saw where this feature was removed. So I just specified the URL.

This feature has worked well for us and it's a feature we need. If it has been removed on purpose, I really wish you would bring it back.

**Comment by torkelo** [comment]
you can run an older version of grafana and import the dashboards you need and then upgrade Grafana. 

The feature is not going to be re-added. It was not used by many, was not working very well.

**Comment by vrobert78** [comment]
I agree with gesquive this feature was really useful.

**Comment by torkelo** [comment]
you can install grafana 2.6 and migrate, then upgrade to 4.x
