### ISSUE TITLE
Navigation: Kiosk mode behavior issues on non-Dashboard pages

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#58236]
Two different scenarios found so far:

### Scenario A

1) Press "Kiosk mode"
2) The top bar does NOT disappear, but the toast shows up and it appends `?kiosk` to the url
3) Press "Kiosk mode" again or press ESC, the top bar disappears
4) Pressing ESC does not exit kiosk mode, only navigating away/refreshing does

This happens in (could be more):
- Administration > Data Sources
- Administration > Server admin (+ other new home pages)

### Scenario B

1) Press "Kiosk mode"
2) While the toast is showing, press ESC
3) The view stays in kiosk mode until the toast disappears

This happens in (could be more):
- Administration > Preferences
- Administration > Stats and license

**Comment by torkelo** [comment]
@JoaoSilvaGrafana have a fix
