### ISSUE TITLE
github.auth fails if the user has set their email to a private address

### ISSUE THREAD

**Issue by xyntrix** [grafana/grafana#5823]
- Bug report

Please include this information:
- What Grafana version are you using?
grafana-3.1.1-1470047149.x86_64
- What datasource are you using?
none, login issue
- What OS are you running grafana on?
PRETTY_NAME="CentOS Linux 7 (Core)"
- What did you do?
User attempted to login using github auth (from internal github enterprise).
- What was the expected result?
Login success
- What happened instead?
Unable to login

t=2016-08-15T19:53:03-0700 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="json: cannot unmarshal object into Go value of type []social.Record"

t=2016-08-15T19:53:03-0700 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=xxx time_ns=127ns size=709

t=2016-08-15T19:53:07-0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=xxxtime_ns=0 size=280

t=2016-08-15T19:53:08-0700 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="json: cannot unmarshal object into Go value of type []social.Record"

User has their e-mail address set to "do not show" in their settings. 

[auth.github]
enabled = true
allow_sign_up = true
client_id = xxx
client_secret = xxx
scopes = 'user:email, read:org'
auth_url = https://github.XXX/login/oauth/authorize
token_url = https://github.XXX/login/oauth/access_token
api_url = https://github.XXX/api/v3/user
team_ids =
allowed_organizations =

Other accounts can login, if they have their e-mail set to "show publicly".

**Comment by torkelo** [comment]
try change scopes to 
scopes = user:email

**Comment by mcanevet** [comment]
I have the same issue and if I change the scope to just `scopes = user:email` (removing `read:org`) it fails with `Login Failed: Required team membership not fulfilled`.

**Comment by mcanevet** [comment]
Actually I had a typo in my conf. `scopes = user:email,read:org` works for me with private email addresses. Sorry for the noise.
