### ISSUE TITLE
OPTIONS request fails when using api

### ISSUE THREAD

**Issue by namnn96** [grafana/grafana#5824]
Hi team, 

I am trying to use grafana api to create dashboard on my grafana server. When testing with Postman, it is completely fine.

However when going into javascript, a pre-flight OPTIONS request is sent before my post request, and cause 404. Is there any way I can overcome this by configuring grafana?

Thanks

**Comment by torkelo** [comment]
this is due to browser CORS, https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS 

Currently there is no cors option in Grafana so if you want to use it's api from another web domain you need to put a nginx/apache infront that adds the CORS headers responses

**Comment by namnn96** [comment]
Hi @torkelo ,

Can you be more specific? What do you mean by infront, is it in the request header? How should I do that?

Thank you.

**Comment by torkelo** [comment]
I mean as a reverse proxy,  so nginx can handle the options  call

**Comment by PmcFizz** [comment]
if someone meet this problem， can see [my blog article ](https://blog.csdn.net/github_35631540/article/details/108278598)
I hava solve it .
