### ISSUE TITLE
Request to include AWS/ApiGateway namespace for Cloudwatch Datasource

### ISSUE THREAD

**Issue by josephmelendrez** [grafana/grafana#5826]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
   [Ans] Version 3.1
- What datasource are you using?
  [Ans] Cloudwatch
- What OS are you running grafana on?
  [Ans] Amazon Linux AMI release 2016.03

Request: Please include the AWS/ApiGateway namespace

**Comment by mtanda** [comment]
I can't found such namespace.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html

**Comment by webdestroya** [comment]
They only show up once you deploy an API, but it definitely exists.. not sure why it is not shown in the CloudWatch docs.

Here are the ApiGateway CloudWatch docs:
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-dimensions.html

**Comment by mtanda** [comment]
Oops, sorry.

I make a PR for this. Adding metrics/dimensions is very easy, please try next time if you want to add something.
https://github.com/grafana/grafana/pull/5874

**Comment by josephmelendrez** [comment]
I tried to manually type ApiGateway on the namespace, 5XXError on the metric and the ApiName on the the dimensions even they are not on the dropdown selection, they can get the metric data from cloudwatch and put it on the graph.
Anyway, thanks for all your help, I really appreciate those. Hopefully #5874 will be added on the next update.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/5874
