### ISSUE TITLE
Add elapsed() transformation for InfluxDB

### ISSUE THREAD

**Issue by mroch** [grafana/grafana#5827]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v3.1.1 (commit: a4d2708)
- What datasource are you using? InfluxDB

InfluxDB 0.13 added an [`elapsed()`](https://docs.influxdata.com/influxdb/v0.13/query_language/functions/#elapsed) function. It would be great to add it to the list of aggregations. Is it as simple as adding another entry to [query_part.ts](public/app/plugins/datasource/influxdb/query_part.ts)?

**Comment by torkelo** [comment]
yes, it is as simple as that.

**Comment by mroch** [comment]
Cool. I'd send a PR but would have to clear it with Legal at work first, and that might not be worth the effort. :/
