### ISSUE TITLE
Legend and graph don't have the same colors

### ISSUE THREAD

**Issue by Alucardfh** [grafana/grafana#5828]
- **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
  --> 3.1.0
- What datasource are you using?
  --> InfluxDB
- What OS are you running grafana on?
  --> Centos 7.2
- What did you do?
  --> Create a graph with templating variable and two stack series
- What was the expected result?
  -->Graph is displayed and legend colors match graph colors
- What happened instead?
  --> In some cases colors don't match between legend and graph

The line pointed by the arrow in the graph below is what in the legend is called "gpc backlog cores"
The legend shows it as a shade of blue ... but is quite red on the graph !

![image](https://cloud.githubusercontent.com/assets/1701397/17694624/9d5c6360-639c-11e6-9021-a102cd6d765a.png)

If you untick all others lines first it stay red ("Total cores" is the reference point and all metrics named *backlog are stacked above it, all metrics named *used are stacked under)

![image](https://cloud.githubusercontent.com/assets/1701397/17694315/296277f2-639b-11e6-8849-2dc32cb521d3.png)

But if you untick everything and tick "gpc backlog cores" first it shows with the right color !

![image](https://cloud.githubusercontent.com/assets/1701397/17694344/4c7adb12-639b-11e6-8ffb-ce3b9171e0ec.png)

Below is the query definitions :
![image](https://cloud.githubusercontent.com/assets/1701397/17694440/ce171492-639b-11e6-9ebe-6ed275e039e6.png)

And here are the series specific options:
![image](https://cloud.githubusercontent.com/assets/1701397/17694454/dab140e2-639b-11e6-8e0f-f641be72fdfc.png)

Here is the templating variable used: 
![image](https://cloud.githubusercontent.com/assets/1701397/17694792/7b47302e-639d-11e6-865f-bc273fa3e373.png)

I have attached a sample of the data
[grafana_data_export.zip](https://github.com/grafana/grafana/files/419893/grafana_data_export.zip)

And the full json definition of the panel:
[panel.json.txt](https://github.com/grafana/grafana/files/419894/panel.json.txt)

**Comment by torkelo** [comment]
I cannot see the issue, it looks like `Total cores` is red in all you images and ´"gpc backlog cores` is blue in all. 

The only issue I can see is in this image:
![](https://cloud.githubusercontent.com/assets/1701397/17694315/296277f2-639b-11e6-8849-2dc32cb521d3.png) 

looks like the the `gpc backlog cores` is filled with blue, but drawn in red. your are stacking the `gpc backlog cores` on top of the Total series. 

Try to disable the line fill for all, or switch of stacking, or switch stack: true to a stack: B.

**Comment by Alucardfh** [comment]
I can reproduce and expand the issue (Disabling the line fill or switching stack:true to stack:b don't help)

![image](https://cloud.githubusercontent.com/assets/1701397/17696226/f45ab5ec-63a4-11e6-8af9-5318c848186d.png)


It definitely depend on the way you select the data in the legend : 
If you clear everything, colors are correct. If you progressively unselect data colors are not matching.

But the problem also shows on the graph with everything enabled as the line that represent "gpc backlog cores" is red on the first graph, but should be blue according to the legend.

**Comment by torkelo** [comment]
strange, unable to replicate it. Can you try to replicate it here?
http://play.grafana.org/dashboard/db/legend-colors

**Comment by Alucardfh** [comment]
Nope, can't replicate it on the demo.

My guess would be that this has to do with the templating : there are series that are catch by the regex that don't have data for this time period.

**Comment by torkelo** [comment]
Please change null point mode to null as zero.  If you have stacking enable and series that are missing data points you need fill(0) in your query and null point mode cannot be set to connected

**Comment by Alucardfh** [comment]
I changed to null as zero. But this doesn't solve the issue :  

![image](https://cloud.githubusercontent.com/assets/1701397/17698860/646824ae-63b5-11e6-9849-30e1c96a4f6a.png)

**Comment by torkelo** [comment]
and fill(0) in your query?

**Comment by torkelo** [comment]
if you disable the stacking does the issue persist?

**Comment by Alucardfh** [comment]
Fill(0) doesn't affect the behavior.

But as mentioned in comment https://github.com/grafana/grafana/issues/5828#issuecomment-240065941 when stacking is disable the issue goes away.


![image](https://cloud.githubusercontent.com/assets/1701397/17699536/30fd77fa-63b9-11e6-9cbb-314c2d671525.png)

**Comment by Alucardfh** [comment]
Hi,

I think I managed to get a simpler reproducer : 

In InfluxDB : 
- Create a time serie with at least a tag called test. 
- Input some data for test=value1 with timestamp around t-1H
- Input data for test=value2 with a timestamp around t
- Input data for test=value3 with timestamp around t
- Input data for test=value3 with timestamp around t

In Grafana:
- In a dashboard create a multivalue templating variable calles TestVar for the tag test with a query like : 
SHOW TAG VALUES FROM "YOUR_SERIE" WITH KEY = "test" 
- Create a graph with a metric having query like : 
SELECT sum("VALUE_COLUM") FROM "YOUR_SERIE" WHERE "test" =~ /^$TestVar$/  AND $timeFilter GROUP BY time(1m) fill(null)
- Alias the metrics with something like "$tag_test my value"
- Stack the serie

- Select a timerange T that don't contain data for the tag test=value1
- Observe the color mismatch between graph and legend !

![image](https://cloud.githubusercontent.com/assets/1701397/18386646/2c4d93c2-7690-11e6-9420-acc14fcc1954.png)


So it looks like have a templating variable that map to empty value is correctly handled in the legend but not in the graph rendering.

**Comment by torkelo** [comment]
There ia probably no mismatch only series stacked on top each, one is all zero and hiding / drawing on top of another,  what's you legend options? Are you hiding  all null series?

**Comment by clinta** [comment]
I'm also seeing this issue, here's an example of it

 ![](https://i.imgur.com/kTGARhX.gif)

**Comment by crawforde** [comment]
I'm also having problems with this. I have a graph with two sets of points on it. If I click the legend and show each one individually, the colors are correct. If I show both at the same time, the graph swaps the two.

**Comment by torkelo** [comment]
closing this as it looks like just multiple series overdrawing each other

**Comment by MikeC-BC** [comment]
I'm experiencing the same issue. When the `Legend value` is set to `Last (not null)` the graph colors do NOT match the legend colors. 

Can this be fixed?

**Comment by St3f1n** [comment]
There is still this issue, known since 2016, and not solved :(.

However, changing Time series => Graph styles => Stack series to "Off" solved the problem on my side.
