### ISSUE TITLE
Config: Datasources url is not honoring root_url when using sub-path

### ISSUE THREAD

**Issue by howcroft** [grafana/grafana#58290]
**What happened**:
When navigating to /datasources page the datasources components being generated aren't honoring the root_url
This isn't immediately noticeable, as the javascript intercepts the request if you click it.
However, if you Ctrl/Cmd + Click the link (or "copy the link", or open the source in developer tools) you see the URLs generated for the datasources are not honouring the root_url setting.

**What you expected to happen**:
I expect the same behaviour as the /plugins which generates the list of plugins with correct urls (i.e. honouring root_url).
Instead of all links starting with /datasources, I expect links to honour root_url/datasources
In the below case, this would mean root_url/grafana/datasources and not root_url/grafana

**How to reproduce it (as minimally and precisely as possible)**:
If using the container just use the env vars:
GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana"
GF_SERVE_FROM_SUB_PATH=true
My datasources are pre-provisioned with a datasources.yml file in /etc/grafana/provisioning

**Anything else we need to know?**:
I believe this is something to do with
Line 74 of DataSourcesList (in main - current commit 3f654b932abbd82532c58850fa0126ac23533be1)
              <Card href={dataSourcesRoutes.Edit.replace(/:uid/gi, dataSource.uid)}>
https://github.com/grafana/grafana/blob/bdb8fe3b025f8f5eb11d85f8287901e73ac4b35b/public/app/features/datasources/components/DataSourcesList.tsx#L74

I currently have a lot to handle but, if this is the bug source, I could probably pick this up in the beginning of 12/2022. 
I am more versed in VueJS than React however, so feel free to pick it up

**Environment**:
- Grafana version: 9.2.3 (docker tag)
- Data source type & version: All
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Windows + firefox + chrome
- Grafana plugins:
- Others:

**Comment by howcroft** [comment]
![Link-badly-formed](https://user-images.githubusercontent.com/3884712/203385757-8747d358-9829-4906-b5fd-3733969fbd50.gif)

**Comment by howcroft** [comment]
As you can see, the datasources link completely ignores the url prefix. I've included the "plugins" example to show correct link formation. What is weird, is that the UI intercepts the datasource click if I don't Ctrl+click it (i.e. same as copying and pasting link into browser manually)

**Comment by zuchka** [comment]
are you running the grafana docker container on `8443` or is there some other tooling in play here like a reverse proxy?

**Comment by howcroft** [comment]
Same behaviour direct to container on port 3000 and behind a loadbalancer (haproxy), as shown in gif.

**Comment by zuchka** [comment]
managed to reproduce:

![CleanShot 2022-11-29 at 10 20 39@2x](https://user-images.githubusercontent.com/37156449/204640169-ea4bf0eb-acb4-4e32-b16e-bdbfaaff2c01.png)
![CleanShot 2022-11-29 at 10 20 43@2x](https://user-images.githubusercontent.com/37156449/204640181-fe9c5631-3e0d-4176-99eb-edd8296651e9.png)
![CleanShot 2022-11-29 at 10 20 52@2x](https://user-images.githubusercontent.com/37156449/204640198-00db7853-c32e-4404-a0c0-372571bab16b.png)
