### ISSUE TITLE
Annotation update not possible.

### ISSUE THREAD

**Issue by joergfreimuth3778** [grafana/grafana#58305]
**What happened**:
A created annotation can no longer be updated afterwards

**What you expected to happen**:
Generated annotations should be changeable afterwards

**How to reproduce it (as minimally and precisely as possible)**:

### Create
curl -s -XPOST http://127.0.0.1:3000/api/annotations -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer ###' -m 10 -d '{"text": "deployment", "time": 1667806221000, "timeEnd": 1667806221000, "tags": [
  "progress",
  "live",
  "foo",
  "deployment"
]}'
{"id":2,"message":"Annotation added"}%

### Update
curl -s -XPATCH http://127.0.0.1:3000/api/annotations/2 -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer ###' -m 10 -d '{"timeEnd": 1667806243000, "tags": [
  "success",
  "live",
  "foo",
  "deployment"
]}'

**Anything else we need to know?**:
logger=accesscontrol.service t=2022-11-07T07:31:24.568292652Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-apikey-1
logger=accesscontrol.service t=2022-11-07T07:31:24.568659652Z level=debug msg="cache permissions" key=rbac-permissions-1-apikey-1
logger=accesscontrol.evaluator t=2022-11-07T07:31:24.568757111Z level=debug msg="matched scope" userscope=annotations:* targetscope=annotations:id:2
logger=ngalert t=2022-11-07T07:31:27.186687112Z level=debug msg="recording state cache metrics" now=2022-11-07T07:31:27.186645903Z
logger=sqlstore.transactions t=2022-11-07T07:31:29.70051628Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=0
logger=sqlstore.transactions t=2022-11-07T07:31:34.829799532Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1
logger=context userId=0 orgId=1 uname= t=2022-11-07T07:31:34.83063499Z level=error msg="Failed to update annotation" error="context canceled" remote_addr=172.17.0.1 traceID=
logger=context userId=0 orgId=1 uname= t=2022-11-07T07:31:34.830767324Z level=error msg="Request Completed" method=PATCH path=/api/annotations/2 status=500 remote_addr=172.17.0.1 time_ms=10282 duration=10.282997504s size=54 referer= handler=/api/annotations/:annotationId
logger=ngalert t=2022-11-07T07:31:34.844757532Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0

**Environment**:
- Grafana version:  9.2.3 (docker tag)
- Data source type & version: All
- OS Grafana is installed on: Official Docker image
- Grafana plugins:
- Others:

**Workaround**:
- Delete grafana.db File
- Deploy Grafana version 7.5.x
- create an Annotation
- update an Annotation
- Update to grafana 9.2.x

Now you can create and update new annotations with grafana 9.2.x

**Comment by usmangt** [comment]
Hi @joergfreimuth3778,

Thanks for opening this issue.

Looking at the logs before getting the error line about annotations, there is this message:

`logger=sqlstore.transactions t=2022-11-07T07:31:29.70051628Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=0`

Could you please check if your Database is up and running (not in an inactive or locked state).

Also, just to understand the problem description a bit better, the problems occur for e.g.

1- Install a fresh Grafana server
2- Create a panel dashboard and create an annotation
3- Update the Grafana server to a newer version
4- After the update, the annotations could not be changed?

**Comment by joergfreimuth3778** [comment]
Hi @usmangt,

yes the database (sqllite) is running.

1- Yes, we use a fresh installed grafana 9.2.3
2- yes, it's possible to create dashboards and annotations
3- No, we have not performed any update
4- Without any grafana update, the update of annotations is not possible

In our workaround we start with a fresh grafana 7.5 installation. We create an annotation and update it. If we now update to grafana 9.2.3, we can create new annotations and update them.

Only with a fresh 9.2.3 version the update of annotations is not possible.

**Comment by usmangt** [comment]
Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by joergfreimuth3778** [comment]
Hi, I am not able to generate an API token. But we generate the annotations exclusively through the API

**Comment by usmangt** [comment]
Thanks, I also got the same message. I will forward this issue to our Engineers so that they can have a look and maybe tell us more if incase any parameter is missing.

**Comment by MichaelVoelkel** [comment]
This has been opened for quite some time. We would also appreciate a fix!
