### ISSUE TITLE
Canvas: Specifying Icon via Field does not work

### ISSUE THREAD

**Issue by pflodo** [grafana/grafana#58303]
When giving an icon Element the path of a fixed icon, via a field, it will not display that icon.

**What you expected to happen**:
I expected the icon element to show the specified icon

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new Dashboard, with Random Walk Grafana test data (A-series)
2. Create new panel of type Canvas
3. Edit metric-value to use field (A-series) - it shows the random data
4. Create an Icon element, and set to one of the shipped icons: eg plane.svg - switch over to URL tab, and get path ie img/icons/marker/plane.svg
5. Edit Icon element to also use field (A-Series)
6. Create a value map for a range eg 0-1000 and set it to value of icon img/icons/marker/plane.svg
7. Confirm that metric value shows mapped value

**Anything else we need to know?**:
I could just be doing something wrong - but i could not find any documentation or sample - I looked at your gdev canvas demo dasboard, but you don't load icon from field in any of them

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: Grafana test data
- OS Grafana is installed on: Debian 
- User OS & Browser: Windows/Firefox

Panel JSON attached
[canvastest.zip](https://github.com/grafana/grafana/files/9948766/canvastest.zip)

**Comment by pflodo** [comment]
Should have done screenshot as well, showing the metric-value and icon both tied to A-series field, but icon displaying default icon
![bild](https://user-images.githubusercontent.com/7450377/200242618-ecbd73a4-8c07-4dc3-b837-13a3dea90543.png)

**Comment by usmangt** [comment]
Hi @pflodo,

Thanks for opening this issue.

We recently had a question about the Canvas plugin in our community forums:

https://community.grafana.com/t/new-canvas-plugin-data-link-support-for-each-element/74094/15

We suggest that you have look in there as it tells about the special configuration + link to report issues about it as it is still in beta state.

I hope this helps.

I will now close this issue.
