### ISSUE TITLE
Row editor repeating rows do not actually repeat rows

### ISSUE THREAD

**Issue by joriws** [grafana/grafana#5831]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Version 3.1.1 (commit: a4d2708)
- What datasource are you using? Irrelevant to bug but influx
- What OS are you running grafana on? Ubuntu 14.04
- What did you do? Tried to use "repeating rows" on row editor with templated variable
- What was the expected result? Have multiple rows with multiple titles
- What happened instead? 

Did not get repeating rows, only displayed row #1.  I created this dashboard to illustrate problem and it does the same. Panel is text panel to display row as well. I'd expect to get 4 rows and then "add row" button as in screenshot.

I also have other dashboard similar which works similar. The purpose is have a standard row maybe 10-15 custom items and all rows have two panels, pie-chart and a detailed chart. Panels are not repeated. Only rows but naturally panels get the data from repeating row variable.

![gra_var](https://cloud.githubusercontent.com/assets/5603060/17698161/1beab2ca-63c2-11e6-8406-857a04dc3998.png)
![gra_row](https://cloud.githubusercontent.com/assets/5603060/17698164/1fb70ec6-63c2-11e6-85ec-ad09f6b5981b.png)

**Comment by torkelo** [comment]
Looks like your template variable only has one value selected, try enabling multi select or all value and select or multiple values

**Comment by joriws** [comment]
How do I do that. I've hidden variable because I want hide it, run it as "for-loop"

{
  "id": 35,
  "title": "template test",
  "tags": [],
  "style": "dark",
  "timezone": "utc",
  "editable": true,
  "hideControls": false,
  "sharedCrosshair": false,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "100px",
      "panels": [
        {
          "title": "Panel Title $row_repeat",
          "error": false,
          "span": 12,
          "editable": true,
          "type": "text",
          "isNew": true,
          "id": 1,
          "mode": "markdown",
          "content": "I am text at $row_repeat\n",
          "links": []
        }
      ],
      "repeat": "row_repeat",
      "showTitle": true,
      "title": "Row $row_repeat",
      "scopedVars": {
        "row_repeat": {
          "selected": true,
          "text": "1",
          "value": "1"
        }
      }
    }
  ],
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "templating": {
    "list": [
      {
        "current": {
          "text": "1",
          "value": "1"
        },
        "datasource": null,
        "hide": 2,
        "includeAll": false,
        "multi": false,
        "name": "row_repeat",
        "options": [
          {
            "selected": true,
            "text": "1",
            "value": "1"
          },
          {
            "selected": false,
            "text": "2",
            "value": "2"
          },
          {
            "selected": false,
            "text": "3",
            "value": "3"
          },
          {
            "selected": false,
            "text": "4",
            "value": "4"
          }
        ],
        "query": "1,2,3,4",
        "refresh": 0,
        "type": "custom"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "schemaVersion": 12,
  "version": 2,
  "links": [],
  "gnetId": null
}

**Comment by joriws** [comment]
But I see your answer - I made variable visible, selected "All" and rows repeated. Then re-hide variable again and it is showing. Not really expected behaviour..

**Comment by AkashKrDutta** [comment]
@joriws  But after you refresh the page it goes away :/

**Comment by AkashKrDutta** [comment]
Got it working! Just use query as a panel and not visualization. :)
