### ISSUE TITLE
Update Header of Data source Edit connection page

### ISSUE THREAD

**Issue by mikkancso** [grafana/grafana#58311]
The data source "Edit" page should look like this:
https://www.figma.com/file/2L3Fqq7D2iUQWbS1B1uqTJ/Connections?node-id=3508%3A89439

Which means that there should be the following buttons in the right side of the header:
- build a dashboard
- explore
- delete
- save changes

**Comment by GrafanaWriter** [comment]
Removing the type/docs label as this is not a Grafana docs issue.
