### ISSUE TITLE
Uninstalling plugins can lead to undeletable dashboards

### ISSUE THREAD

**Issue by kchristensen** [grafana/grafana#5832]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Was using the Worldping plugin
- What OS are you running grafana on? Ubuntu 14.04
- What did you do? Uninstalled Worldping plugin after trial ended
- What was the expected result? Worldping related dashboards would be deletable.
- What happened instead? Most dashboards were able to be deleted, however the "worldPing: Home" dashboard cannot be deleted as it contains panel types that no longer exist after uninstalling the plugin. Additionally, the  "Worldping endpoint comparison" dashboard is also unable to be deleted, because it fails to init with the following error: "Dashboard init failed
Template variables could not be initialized: Cannot read property 'text' of undefined".

As mentioned above, I uninstalled the Worldping plugin, and some of the dashboards the plugin creates have become orphaned, and I can't delete them. Reinstalling the plugin would recreate the dashboards, but I'm sort of stuck in a catch 22 where I can't rid our Grafana installation of the plugin cruft.

**Comment by torkelo** [comment]
try disabling the plugin before uninstalling it

**Comment by kchristensen** [comment]
That did it, disabling the app removed the dashboards, then I was able to uninstall the app and they stayed gone. I'm not sure if I missed that in the documentation, but it might be worth noting some where to prevent that scenario from happening to others.

Thanks @torkelo!
