### ISSUE TITLE
Searching for Grafana users shows a JS error when there is no match

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#58324]
**What happened**:
There is an error when searching for a user that does not exist.
Let's say I have a user with the email user1@mail.com that exists in grafana
When typing "user1" in the search bar, the user shows up correctly.
But when typing "user2", an error message shows up.

![2022-11-07_12-23](https://user-images.githubusercontent.com/3624853/200300920-7479b1f0-699b-45d2-bd3a-b2e8ea4bccf4.png)

**What you expected to happen**:
It should be a clean message like "No user found" or something like that, instead of a cryptic JS error message

**How to reproduce it (as minimally and precisely as possible)**:
Just start typing anything in the users's search bar until it doesn't match any user.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: NA
- OS Grafana is installed on: Official latest Grafana Docker image
- User OS & Browser: POP OS - Firefox 106
- Grafana plugins: None
- Others: NA

**Comment by usmangt** [comment]
Hi @hakro,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I will inform our team so that they can investigate further and provide more details about the cause.

Thanks

**Comment by usmangt** [comment]
I was able to reproduce it on:

Version 9.2.2 (commit: 78a3e64e4f, branch: HEAD)
Grafana OSS
OS: CentOS 7 (Virtual Machine)
Browser: Chrome Version 107.0.5304.87 (Official Build) (64-bit)

Attached are the browser console logs when the issue occurred:

[browser-console.log](https://github.com/grafana/grafana/files/9960788/browser-console.log)

**Comment by TheFern2** [comment]
This issue only happens on 9.2.2 and 9.2.3 when the app is in development at least that's what I experienced. When is in production app_mode it appears to work fine. Also docker image with 9.2.4 appears to work just fine on any app_mode.
