### ISSUE TITLE
Loki: Add step option

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#58337]
**What happened**:

Following up on https://github.com/grafana/grafana/issues/52387 and https://docs.google.com/document/d/1giA6oxb_gyAJYvI2b0qL1XACgVrsS1HsiN0ZzCDze7o/edit#heading=h.41dvitd003pb and https://raintank-corp.slack.com/archives/C02TXB92G6T/p1666192269896219 we decided the best way to implement step editor in Loki is by `Add a step editor to Loki that does not change/influence the interval.`

Steps MVP:
- [x] Add step option to data query https://github.com/grafana/grafana/pull/69558
- [x] Implement step in editor and use it https://github.com/grafana/grafana/pull/69648
- [x] Add validation https://github.com/grafana/grafana/pull/70319
- [x] Deprecate/Remove `Resolution` https://github.com/grafana/grafana/pull/70326
- [x] Add documentation https://github.com/grafana/grafana/pull/70358

Future work, not MVP
- [ ] Add a "calculate step" resource call to unify logic `ivana/loki-step-api`
- [ ] Maybe? Add interpolation of variables
- [ ] [auto] step https://github.com/grafana/grafana/issues/71743

**Comment by gabor** [comment]
NOTE: we should doublecheck with the explore-squad when we have a more specified idea about how this will work, especially about URL-handling.
