### ISSUE TITLE
Admin API documentation is misleading

### ISSUE THREAD

**Issue by rytis** [grafana/grafana#5834]
If you read http://docs.grafana.org/http_api/admin/ you may assume that admin API calls can be made using an API token as authentication mechanism:

    GET /api/admin/settings
    Accept: application/json
    Content-Type: application/json
    Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

However, according to the comments in https://github.com/grafana/grafana/issues/3909 the API token can only be admin on organisation level, and not at the system level.

The documentation should clearly state that for system administration tasks Basic authentication should be used.

**Comment by torkelo** [comment]
your right! this should be fixed!

**Comment by onitake** [comment]
Apparently, this also affects the organisation API.
Can you update http://docs.grafana.org/http_api/org/#get-organisation-by-id et al. as well?
