### ISSUE TITLE
AzureAD App with Personal Accounts is allowed to bypass group assignment requirement

### ISSUE THREAD

**Issue by daniel-anova** [grafana/grafana#58341]
**What happened**:

When configuring the AzureAD application as `AzureADandPersonalMicrosoftAccount` it allows a user using a Personal Microsoft Account to login and be granted viewer access to grafana without being assigned a role even though "Assignment required?" is set to true.

**What you expected to happen**:

Access would be restricted to users assigned a role directly or through a group. 

**How to reproduce it (as minimally and precisely as possible)**:

- Create an AzureAD application for grafana with Microsoft Personal Account enabled
- Setup AzureAD to require assignment and assign tenant user to the application
- Setup grafana as per [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#azure-ad-oauth2-authentication).
- Login with an authorized tenant user should work, login with a non-authorized tenant user should fail, login with an unauthorized Microsoft personal account should work.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.4
- Data source type & version: N/A
- OS Grafana is installed on: kube-prometheus-stack, aks 1.23.8
- User OS & Browser: Windows 10 22H2, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35
- Grafana plugins: N/A
- Others: N/A

**Comment by usmangt** [comment]
Hi @daniel-anova,

Thanks for opening this issue.

I will forward it to our team so that they can have a look and tell more about the issue.

**Comment by kalleep** [comment]
Hey, have you added `role_attribute_strict = true` for the azure ad configuration?

That one should block users without a valid role

**Comment by kalleep** [comment]
Yes I agree that having `role_attribute_strict` set to true by default would be better and is something we have talked about. But it would be a breaking change and is something we would have to do in a major release.

We are currently looking at sane default for all of the different auth providers and if we want to change it it would be done for all of them :)

**Comment by daniel-anova** [comment]
A first good step would be to change the default documentation to not show `role_attribute_strict = false`.

To give some further detail on the issue in case anyone faces the same.

After enabling `role_attribute_strict = false` logins with Personal Accounts were being rejected as having no role assigned.

That was due to using "https://login.microsoftonline.com/common/oauth2/v2.0/authorize" as the endpoint per   [Microsoft documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-nodejs-webapp-msal#add-app-registration-details) instead of "https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/authorize".

Seems appRoles are only returned when using the tenantId endpoint.
