### ISSUE TITLE
[Epic - Panel Edit]: Improve Panel Edit user experience - Quick Wins

### ISSUE THREAD

**Issue by thanos-karachalios** [grafana/grafana#58350]
**What**

Improve the user experience of the panel edit page by rethinking Information Architecture, UI refinements in terms of text alignment and small quick wins.

**Why**

User research provided insights that depict obstacles new users have when editing a panel that affect multiple steps in the process. Examples are visualisation choice, panel layout options, etc. More of the insights can be found in this [Miro link](https://miro.com/app/board/uXjVPQq9yrw=/?share_link_id=805734469002). 

The current experience results to users spending considerable time to get value from the product which increase the churn probability considering they have already configured their data source successfully.

The aims are to decrease this time-to-value for the user and eventually decrease the user churn on this funnel.

https://github.com/grafana/grafana/issues/58350#tasklist-block-dc9864eb-ee05-47f6-ad62-4ddb863a9d62

### Docs

[Product DNA](https://docs.google.com/document/u/0/d/1GF5-gI_MVlZMrtLy3C5qJA00dA4Vzc-y13E_2foOkdk/edit)

**Comment by natellium** [comment]
Closing this one as we've created more specific projects to tackle this.
