### ISSUE TITLE
[Feature Request] Allow timezone to be changed by the viewer

### ISSUE THREAD

**Issue by tphipps** [grafana/grafana#5836]
Currently, the timezone can only be specified on the Dashboard settings page, and cannot therefore be adjusted by the average consumer of the data. It would be very convenient (and UI-wise appropriate) for the timezone to be changeable when viewing a Dashboard or snapshot from the Time Range picker.

Alternatively, making the "UTC" lamp clickable (that appears next to the time range when the dashboard is configured to display in UTC), and have it drop down timezone options would be a very intuitive approach.

Timezones are a very personal thing and it should be up to the viewer to determine what timezone they are viewing the data in - not the dashboard creator.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/558
