### ISSUE TITLE
Switch between how colors are assigned in flamegraph

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#58378]
I think we should have a switch button (right now just on/off but may be more later) to change the color scheme of the flamegraph.

We should be able to switch between:
-  normal  percentage of self compare to root gradient colouring (current) 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1053421/186866774-77d9dda9-4543-42f6-9285-786b65b527fa.png">

-  and code colouring 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1053421/186866847-98b85c86-dd95-4b6f-b732-8461a2ff5569.png">

The code colouring goal is to improve the ability to locate similar symbols, from the same application, namespace or package. There's an [article](https://www.brendangregg.com/blog/2017-07-30/coloring-flamegraphs-code-type.html) from brendan gregg which is very interesting and I think the hack solution should be preferred at first. 

If possible we should try to use gradient of the same colour with a higher percentage  the closer symbols are. 

We might need to have later a language selector ? Or some sort of configuration to fit most of needs (C/C++/JAVA/.NET/GO/RUST). Alternatively or at a later stage finding the language automatically could be added server side see:
- https://stackoverflow.com/questions/475033/detecting-programming-language-from-a-snippet
- https://github.com/github/linguist

**Comment by aocenas** [comment]
Closing this as color switcher is already implemented.

This part though:
> If possible we should try to use gradient of the same colour with a higher percentage the closer symbols are.

This may be tricky to get right so we don't get too similar colors everywhere, right now we area actually trying to have as diverse colors as possible. 

> We might need to have later a language selector ? Or some sort of configuration to fit most of needs (C/C++/JAVA/.NET/GO/RUST). Alternatively or at a later stage finding the language automatically could be added server side see:

We don't have the info sent from backend yet but seems like the basic autodetection of the package prefix format works right now.
