### ISSUE TITLE
How can I fix Cross-Origin Resource Sharing (CORS) error?

### ISSUE THREAD

**Issue by pc10201** [grafana/grafana#5837]
Grafana 3.1

I have export a link to share a dashboard.

Then I use iframe to use the link.I want to use js to do something.

But Cross-Origin Resource Sharing (CORS).

How can set Grafana server headers?

**Comment by torkelo** [comment]
using similar options as detailed here: (you need to put Grafana behind a nginx or apache reverse proxy)
http://docs.grafana.org/v1.9/installation/#graphite-server-config

**Comment by pc10201** [comment]
I use nginx proxy_pass as reverse proxy.But it do not work.I will give you the nginx conf file tomorrow.

**Comment by pc10201** [comment]
My nginx conf 

       location /public {
                alias /usr/share/grafana/public;

                 location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                                expires max;
                                add_header Pragma public;
                                add_header Cache-Control "public, must-revalidate, proxy-revalidate";
                                tcp_nodelay off;
                                break;
                 }

    }  
        
     location /monitor {
      
        proxy_pass      http://127.0.0.1:3000/;
}
