### ISSUE TITLE
Scrollbar in metric selection menu is not working in IE11

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#5838]
If you type in a search phrase in the parameter search box then you get a drop down menu, but if you click on the scroll bar the drop down menu vanishes.  

Grafana version 3.0 and 3.1 show this effect in Internet Explorer 11 (Chrome and Firefox do not show the effect).

![scrollbar](https://cloud.githubusercontent.com/assets/5039017/17731206/ad65477e-646c-11e6-8a40-d0a2a756614e.PNG)

**Comment by torkelo** [comment]
We do not support IE11
