### ISSUE TITLE
graph zoom inhibit time interval selection

### ISSUE THREAD

**Issue by gtortone** [grafana/grafana#5840]
Hi,
I don't know if this is a bug, but I have this dashboard: 
https://snapshot.raintank.io/dashboard/snapshot/iRao0dtaCbkXSE1T1gRlADEPmYZESFpB

and if I zoom on a graph (e.g. CPU) time interval selection (left - top) does not work anymore...
and the only way to recover time interval selection is to go on time ranges
(right - top) and select a "Quick range"

**Comment by torkelo** [comment]
What do you mean `time interval selection does not work anymore` ? 

I can change time fine after a zoom.

**Comment by gtortone** [comment]
if you open this dashboard available on play.grafana.org:

 	http://play.grafana.org/dashboard/db/monitorama-templating

try to zoom data in graph and after select an interval from template
control "interval" (e.g. 10m) data in the graph remains "freezed" to
zoom...

I try with firefox and chrome browser and result is the same;

On Wed, 17 Aug 2016, Torkel Ödegaard wrote:

> 
> What do you mean time interval selection does not work anymore ?
> 
> I can change time fine after a zoom.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.[AGO1vt2FLA35g0byIOG6bvQyiBS-834vks5qgwLdgaJpZM4JmZzd.gif]
> 
> 
>

-- 
Gennaro Tortone
INFN Napoli
Italy
tel: +39 81 676169

"Computer Science is no more about computers
     than astronomy is about telescopes."
     - Edsger Dijkstra

**Comment by torkelo** [comment]
freezed to zoom? what do you mean? I can continue changing time range fine. (Btw the interval variable in that dashboard is not being used)

**Comment by gtortone** [comment]
I mean this (see animated gif)

![grafana-zoom-interval](https://cloud.githubusercontent.com/assets/6534590/17740982/e8f489b6-649a-11e6-9156-f9dc03ba0032.gif)

**Comment by torkelo** [comment]
what data source are you using? Where are you using the interval variable?

**Comment by gtortone** [comment]
I'm using InfluxDB data source;

I'm using interval variable here:

![interval](https://cloud.githubusercontent.com/assets/6534590/17741680/6d459b72-649d-11e6-9803-bcbfdfe3b6e9.png)

**Comment by torkelo** [comment]
ok, so you have overriden the panel time range, using the variable. The Panel relative time override is only active when the dashboard time is relative, after you zoom in to a graph the time range override is not taking effect (otherwise zoom would not work). 

interval is mostly used in the group by time in the query to change the granularity of the graph

**Comment by gtortone** [comment]
ok,
this is clear to me;

and if I want to plot last ($interval) samples which is the best approach ?

is there a way to shift from relative to zoom and from zoom to relative mode ?

**Comment by torkelo** [comment]
yes, you can switch from absolute time range (zoom region) to relative using the time picker in the upper right

**Comment by gtortone** [comment]
yes I know this... I wrote this in my first comment...

I was wondering if it is possible to inform user that he is using "zoom view" and some actions are
required from him to "recover" interval selections;

**Comment by torkelo** [comment]
the time picker shows the zoomed in time and the override time in the panel is removed.

**Comment by gtortone** [comment]
ok thanks,
when a graph is zoomed it should be useful (IMHO) to know this info from the graph without looking
at top screen. This could be the same mechanism Grafana use for "time override info" when user
select an interval.

Just my cent...

**Comment by torkelo** [comment]
yea, some info text that says "time overrride disabled" could be useful

**Comment by gtortone** [comment]
I was thinking something like "zoom mode"...

**Comment by gtortone** [comment]
another thing that is lost between "zoom mode" and "time interval" is refreshing interval... and it is very
boring to (re)select it every time...

near "zoom mode" label could be inserted an icon to recover previous "view" of dashboard... but
I don't know the difficult of this development...

**Comment by gtortone** [comment]
I mean something like this:

http://www.highcharts.com/demo/line-time-series

**Comment by torkelo** [comment]
refresh interval is automatically restored when you switch back to a relative (to now) time range

**Comment by gtortone** [comment]
sorry,
you are right,

refresh is restored correctly when I switch to a relative time range;


On Wed, 17 Aug 2016, Torkel Ödegaard wrote:

> 
> refresh interval is automatically restored when you switch back to a relative (to now) time range
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.[AGO1vhIRdbEyPXmOUlvwVEoY5Zv3uakyks5qg2pngaJpZM4JmZzd.gif]
> 
> 
>

-- 
Gennaro Tortone
INFN Napoli
Italy
tel: +39 81 676169

"Computer Science is no more about computers
     than astronomy is about telescopes."
     - Edsger Dijkstra

**Comment by gtortone** [comment]
a possible solution to this issue:

- when I select a time interval from $interval control the URL contains only this variable (e.g. for 30m):
http://localhost:3000...<snip>...&var-interval=30m
in this case all graphs are update correctly with time override label

- when I zoom a graph the URL contains the following variables:
var-interval=30m&from=1471468319471&to=1471469072911
in this case all graphs are update correctly with zoom range values

- if I (re)select a different time interval after zoom the variable "var-interval" contained
in URL is updated but "from" and "to" variables are still passed to URL
in this case the selection of a new time interval has "no effect" on graphs

- if I manually remove "from" and "to" variables from URL and get the page the graphs
are updated correctly regarding time interval

proposal: it is possible to remove "from" and "to" variables when user "touch" a template variables ?

**Comment by gtortone** [comment]
Another misleading thing is when user switches to a relative time range (e.g. Last 30 minutes from time picker) this has no effect on the graphs in presence of selected time interval.

**Comment by torkelo** [comment]
Of course it doesn't, that is why it is called a Relative time range **override** , and why the blue text in the upper right of the panel shows the override.

**Comment by gtortone** [comment]
then you agree that in presence of selected time interval that menu (time picker) is useless...

**Comment by gtortone** [comment]
it seems to me the only purpose of time picker **in presence of a time interval menu** is to reset zoom

**Comment by torkelo** [comment]
if all you panels use interval time range override. This is not the norm, usually most panels use the dashboard time range, and maybe a select few have an overriden (static, ie not variable) relative time range override. 

The interval variable is 99% of the time used as a group by time interval (changing the granularity of the data), NOT as a property to change the relative time override. This makes very little sense as You can do that from the time picker already.

**Comment by gtortone** [comment]
thanks,
now this sounds clear to me !

**Comment by shubhamod1** [comment]
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.
