### ISSUE TITLE
Unknown config Key Errors for correct configuration file.

### ISSUE THREAD

**Issue by sagarmah** [grafana/grafana#5842]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 2.6
- What datasource are you using? Influxdb 12
- What OS are you running grafana on? Ubuntu
- What did you do?
I have been running an instance on kubernetes, it was working fine. but suddenly it gave me a 503 error saying no server available to serve the request. I checked the HAproxy and other configurations, everything seemed right. Checked logs for grafana.
- What was the expected result?
The container was running but gave the following errors/ warnings
- What happened instead?
[setting.go:290 loadSpecifedConfigFile()] [E] Unknown config key plugins defined in section paths, in file /etc/grafana/custom.ini
2016/08/16 18:44:09 [setting.go:290 loadSpecifedConfigFile()] [E] Unknown config key check_for_updates defined in section analytics, in file /etc/grafana/custom.ini
2016/08/16 18:44:09 [setting.go:285 loadSpecifedConfigFile()] [E] Unknown config section snapshots defined in /etc/grafana/custom.ini
2016/08/16 18:44:09 [setting.go:285 loadSpecifedConfigFile()] [E] Unknown config section snapshots defined in /etc/grafana/custom.ini
2016/08/16 18:44:09 [setting.go:285 loadSpecifedConfigFile()] [E] Unknown config section snapshots defined in /etc/grafana/custom.ini
2016/08/16 18:44:09 [I] Starting Grafana
2016/08/16 18:44:09 [I] Version: 2.6.0, Commit: unknown-dev, Build date: 2016-05-06 1

I can see all these keys or sections it talks about are a solid part of the config and have always been. I have other instances with same config running perfectly. Miraculously, the app is working fine again but I am trying to figure out what happened and how to avoid it.
Thanks.

**Comment by torkelo** [comment]
fixed in 3.+

**Comment by torkelo** [comment]
or rather I dont know what's going on, maybe the defaults ini file cannot be found? looks like you are running a custom dev build of 2.6.

How do you start grafana-server?

**Comment by sagarmah** [comment]
Yes it a custom build, the dockerfile I wrote uses the following command to run grafana.
`CMD ./bin/grafana-server -config /etc/grafana/custom.ini`

**Comment by sagarmah** [comment]
Also since we are already here I am anyways planning to move to 3.0 for the plugins feature and even the UI is very cool. great work there. Is there a documentation or post to guide safely migrate my SQLite data to this new version instance I will create?

**Comment by torkelo** [comment]
the data schema will migrate automatically

**Comment by sagarmah** [comment]
Thanks.
