### ISSUE TITLE
[Bug]: Templates with "All" option escape values.

### ISSUE THREAD

**Issue by mberhault** [grafana/grafana#5843]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1-1470047149
- What datasource are you using?
Prometheus (version 1.0.1)
- What OS are you running grafana on?
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
- What did you do?
Checked the `Include All Option` in templating and used it in a query.
- What was the expected result?
Expected metrics to keep working, at least when selecting non-All options (it worked before enabling the `All Option`
- What happened instead?
Metric is not found. Request to prometheus now escapes the values (it didn't before).

### Template:
![template_before](https://cloud.githubusercontent.com/assets/5901480/17739443/166835ba-6463-11e6-805c-1fdfdbe3dd25.png)

### SingleStat:
The title is the following string: `"$node" "$cluster"`
![singlestat_before](https://cloud.githubusercontent.com/assets/5901480/17739470/3004c722-6463-11e6-9a87-796eeef87c29.png)

### Request to prometheus:
from chrome console, with `view parsed` and `view decoded`
![request_before](https://cloud.githubusercontent.com/assets/5901480/17739512/62de3818-6463-11e6-92ca-9456f6f9ca56.png)
Raw request:
`query=sum(sys_rss%7Bjob%3D%22cockroach%22%2Ccluster%3D%22beta%22%2Cinstance%3D%22104.196.150.126%3A8080%22%7D)&start=1471421895&end=1471443495&step=600`

Response:
`{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1471439295,"5114769408"],[1471439895,"11241529344"],[1471440495,"15166668800"],[1471441095,"4953292800"],[1471441695,"5341851648"],[1471442295,"4920795136"],[1471442895,"6289530880"],[1471443495,"7658889216"]]}]}}`

### Template:
![template_after](https://cloud.githubusercontent.com/assets/5901480/17739547/820cd3c0-6463-11e6-877f-eff2fb50169d.png)

### SingleStat:
The title (still the string `"$node" "$cluster"` does not show the escaped values)
The stat now displays nothing. Replacing `"$node"` with `"104.196.150.126:8080"` works as expected.
![singlestat_after](https://cloud.githubusercontent.com/assets/5901480/17739664/d73c8a70-6463-11e6-9096-a82a231dde0f.png)

### Request to prometheus:
![request_after](https://cloud.githubusercontent.com/assets/5901480/17739636/c1f36d3c-6463-11e6-91b2-bf9b17b79c12.png)
Raw request:
`query=sum(sys_rss%7Bjob%3D%22cockroach%22%2Ccluster%3D%22beta%22%2Cinstance%3D%22104%5C%5C.196%5C%5C.150%5C%5C.126%3A8080%22%7D)&start=1471422022&end=1471443622&step=600`

Response:
`{"status":"success","data":{"resultType":"matrix","result":[]}}`

**Comment by torkelo** [comment]
Variables with all option will be escaped to support multiple value filtering, so you need to use regex operator in you Prometheus query (or disable the All option)

**Comment by mberhault** [comment]
Or if they do differ and escaping is needed for multi-value, shouldn't it only be done when `Multi-Value` is selected?

**Comment by torkelo** [comment]
To support All and Multi-value use the same method (rendering a regex multi condition with the values)

Not sure what you mean by `remain consistent` , to support multi value filtering Grafana must escape and use regex format, this is how it works in Prometheus.

**Comment by mberhault** [comment]
I meant that it could be less surprising if values were always escaped. eg: I would have been less surprised if I had to use a regexp query from the very beginning (when `All Option` wasn't enabled).

Anyway, I switched my queries to use prometheus' `=~` label operator, so it's all good.

Thank you for the quick response.
