### ISSUE TITLE
Glue: Support correlations in TimeSeriesPanel

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#58441]
It's possible to attach a correlation data link to a time series panel, but there are some problems with it:

#### 1) Link is always opened in a new window

Explore visualizations use [getFieldLinksForExplore()](https://github.com/grafana/grafana/blob/v9.2.4/public/app/features/explore/utils/links.ts#L26) to create LinkModels. This method is responsible for defining onClick behavior when the button is clicked, i.e. opening the split view. [TimeSeriesPanel](https://github.com/grafana/grafana/blob/v9.2.4/public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx#L36) however uses this method only in [ExemplarsPlugin](https://github.com/grafana/grafana/blob/v9.2.4/public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx#L143) and not in the [MenuItem](https://github.com/grafana/grafana/blob/v9.2.4/packages/grafana-ui/src/components/Menu/MenuItem.tsx#L117) but uses [fieldOverrides' getLinkSupplier()](https://github.com/grafana/grafana/blob/v9.2.4/packages/grafana-data/src/field/fieldOverrides.ts#L198) It means that the data links is always opened in a new window.

In other places we override the link supplier in Explore, like in [TableContainer]([overriding the link supplier in Explore](https://github.com/grafana/grafana/blob/v10.0.2/public/app/features/explore/TableContainer.tsx#L71)). This, however, will not work with TimeSeries panel as it overrides the supplier when it's [regenerated](https://github.com/grafana/grafana/blob/v10.0.2/public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx#L83).

#### 2) Interpolation doesn't work

Timeseries panel goes through getLinkSupplier (see above) that uses replace function that doesn't seem be provided. Instead a simple [pass-through is provided in PanelRenderer](https://github.com/grafana/grafana/blob/v9.3.2/public/app/features/panel/components/PanelRenderer.tsx#L90)

#### 3) How to attach the link to specific results in the Correlations config?

Prometheus for multiple series returns many data frames. All frames have two fields - `Time` and `Value`. Attaching links to `Value` will result in the link always being attached to any series. In most cases, it shouldn't be a problem because links will probably use labels for variables interpolation and only if all variables exist the link will be created.

**Comment by gelicia** [comment]
Two things need to happen for this: 

1.) We need to be sure whatever handles the onClick for the link has access to the split function from Explore. I got this working by adding an optional Split function to `getLinksSupplier`, then move up the block for `link.internal` so it has precedence over `onClick`. I have this with a bunch of console.log garbage at `kristina/correlation-timeseries`.
2.) We need to map the Explore Links supplier to the panel one.

The relationship between this panel and links is [ExploreGraph > applyFieldOverrides](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Graph/ExploreGraph.tsx#L130) to [fieldOverrides > getLinksSupplier](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/fieldOverrides.ts#L201). GetLinkSupplier is what generates the links for this. On the flip side, we have `getFieldLinksForExplore` ([src](https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/links.ts#L62)) which takes in slightly different parameters but generates the special LinkModel we use for explore (which has a list of variables). 

I think the best approach here is to have some sort of map between getLinkSupplier and getFieldLinksForExplore, where we can pass that through ExploreGraph and let that handle our links.
