### ISSUE TITLE
Export dashboard JSONs without default values

### ISSUE THREAD

**Issue by mkuzmin** [grafana/grafana#5845]
**I'm submitting a ...**

* Feature request

I'm trying to apply "Infrastructure as code" approach to Grafana: keep dashboards as JSON-files in git, and create them by [Terraform](https://www.terraform.io/docs/providers/grafana/r/dashboard.html).

At the moment generated JSON files contain the whole boilerplate structure and all default values, even if they are not configured explicitly. This makes the files large, and difficult to review and change.

A minimal example with just one singlestat panel takes **169 lines**: https://gist.github.com/mkuzmin/7b0885299c2e4aefa0e10c61d32967a4

But the valuable code there is:

```
{
"title": "test",
"rows": [
{
"panels": [
{
"title": "Free Space",
"type": "singlestat",
"datasource": "vsphere",
"targets": [
{
"rawQuery": true,
"query": "SELECT last(freeSpace) FROM datastore WHERE $timeFilter"
}
],
"format": "bytes"
}
]
}
]
}
```

This is a working example - such minimal JSON is applied successfully, and produces a valid dashboard.

Please make generated JSONs include non-default parts only.

**Comment by bodsch** [comment]
:+1:

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
