### ISSUE TITLE
Prometheus: Remove unused editors

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#58460]
Remove `PromExploreQueryEditor` and `PromQueryEditor` since they are not being used anymore.

See an example PR from logs and traces squad: https://github.com/grafana/grafana/pull/57192

**Comment by swliu417** [comment]
Hey! I'm looking to contribute to Grafana for the first time. I think this issue might be a good start to understanding the code base. Mind if I take a look at it?

**Comment by LudoVio** [comment]
#59957

**Comment by itsmylife** [comment]
@swliu417 Sorry I missed your message. But you can check other issues labeled with `good first issue` (https://github.com/grafana/grafana/labels/good%20first%20issue). You can send PR directly and we will review it.
