### ISSUE TITLE
Rich alert messages in notifications

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5848]
It should be possible to create rich custom alert messages.
- Rich text
- Images of other refereed dashboards

**Comment by Dieterbe** [comment]
also would be nice to have different text based on alert state

**Comment by utkarshcmu** [comment]
#6436 Slack messages will parsed for channels, users or links and will be linked appropriately. 

![screen shot 2016-10-31 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/1019609/19873584/16f27590-9f7d-11e6-8910-991c1cac7e14.png)

**Comment by pdf** [comment]
Related: https://github.com/grafana/grafana/issues/6553#issuecomment-272602289

**Comment by sanchomuzax** [comment]
+1

**Comment by elancheziyan** [comment]
Could you please provide an update on this feature.

**Comment by OutOfFunException** [comment]
Also a +1. Would be very useful to at Dome variables to the Message. We have influxdb Dashboards with several hosts and I would like to include which host is alerting.

**Comment by DominikWA** [comment]
I would find it very useful too to include variables in the message like a host name of a trigger host alert.
Is it predictable when Gafana will support such a function?

**Comment by at-ishikawa** [comment]
Yeah, it would be great if we can include dashboard name in alert messages.

**Comment by vipwangtian** [comment]
+1, perfect if support this.
zabbix can use variables in alert message, but it can not send messages to different receivers.

**Comment by grep-vibhor** [comment]
For those who want to give a hostname with the alert, you can use Prometheus data source integrated with Alertmanager. Alertmanager does the same task and allows you to have label variables in your notification. Was not able to do so with Grafana alert mechanism. But it works fine with Prometheus Alertmanager.

**Comment by tmalkowski** [comment]
I'm tracking puppet changes, and have an alert that's triggered every time a puppet run results in changes. (For instance, when someone edits a file they're not supposed to, an alert is triggered that puppet changed something unexpectedly.) I wanted to include a couple URLs in the alert email, so that we could just clink a link and have it go to the puppet reports webpage, but <a> tags aren't supported, so I have to copy/paste the URL into my browser.

I also wanted to separate my two links with a line break, but the text gets merged into one long line that just relies on text wrapping.

**Comment by berezhinskiy** [comment]
+1

**Comment by fredbcode** [comment]
+1 Yes I agree with several hosts in each dashboards and we would like to see in mattermost notification which host is alerting.

**Comment by jaytardis** [comment]
Any movement on this? I'd love to include metrics/fields from datasources within the Grafana notification message

**Comment by vpbobade** [comment]
I am implementing alert mechanism in grafana and added an email as my notification channel.  I want to add a variable in my email message however when I actually tried to it is not working - could some suggest if this is possible here in case of email notification ??

I think we can do that in slack notifications however not possible in email notifications. Please let me know if some one did this.

Thanks in advance :)

**Comment by jonathanvdwatt** [comment]
+1 on this! 
I'd even be satisfied if we could only have new-lines in emails.

**Comment by mtanda** [comment]
Recently, we start to use Grafana Cloud, and then this feature becomes more important for us.
On self managed Grafana/Prometheus cluster, we use Prometheus alert, we can use template feature of Prometheus.
But on Grafana Cloud, we can't use temple, it is hard to read the alert message.

**Comment by aqt01** [comment]
1+ ward

**Comment by ifutant** [comment]
+1 on this. It would also be pretty cool if we could define a standard template that would populate upon alert creation. This would allow us to define a notification message standard and have the user update the relevant fields for the alert.

**Comment by orangr1989** [comment]
1+ for this request, to enrich the data of notification alert message. Since logs available for alerts, can be more detailed and efficient. thanks

**Comment by efinal** [comment]
+1 for being able to use variable in notification message

**Comment by Soumyank** [comment]
+1 Need the fix/enhancement
we have multiple lines in the Message section, but all gets merged into paragraph.
Need line differentiation/ new line

**Comment by Soumyank** [comment]
> It should be possible to create rich custom alert messages.
> 
> * Rich text
> * Images of other refereed dashboards

when can we expect this fix?

**Comment by GangadharanS** [comment]
> also would be nice to have different text based on alert state

Has that been fixed>.. am looking forward for this fix

**Comment by ashukla411** [comment]
> If we merger #6436, then Slack messages will be parsed for channels, users or links and will be linked appropriately.
> 
> ![screen shot 2016-10-31 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/1019609/19873584/16f27590-9f7d-11e6-8910-991c1cac7e14.png)

What this feature added?

**Comment by druskus20** [comment]
+1.
I would greatly appreciate this feature, right now the alerting system seems kind of limited.

**Comment by te4336** [comment]
Any update on this??

**Comment by haxedby** [comment]
+1 ! really needed feature, craving to have variables to use in messages

**Comment by iuriiismirnov** [comment]
+1

**Comment by mkjmkumar** [comment]
+1 We are in despreate need of this improtant missing feature. This is becauase our message server use only text to pub sub.

**Comment by armandgrillet** [comment]
Rich text is now available in the new alerting experience [using templates](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/). 

For including images, we have the feature request https://github.com/grafana/grafana/discussions/38030 and we are planning on adding this feature.

**Comment by yjacknewton** [comment]
it will be great if you can include "TRANSFORM DATA" like on the new unified alerting for label format and value on notification
