### ISSUE TITLE
Canvas: Unable to set icon via field data

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#58492]
A user found an issue where they could not set an icon based using field data. See comment [here](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-4071835)

When setting an icon source to field, only the fallback question mark icon appears even if the field data is a valid path

**Comment by mschweig** [comment]
Hi, I am using Grafana 10.0.2 with Postgres and still got this issue. I would like to set the source via the field data. 

![image](https://github.com/grafana/grafana/assets/58733365/87793b93-7892-4bc7-8124-5d62280d4439)

Thanks for your help.
