### ISSUE TITLE
Packaging: Updating Grafana 9.2.3 -> 9.2.4 not possible via APT

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#58500]
Ubuntu Server (headless)  22.04.1 LTS /  5.15.0-52-generic

apt-get update:

```
Paketlisten werden gelesen… Fertig
E: Für das Depot »https://packages.grafana.com/oss/deb stable InRelease« wurde der »Origin«-Wert von »grafana stable« in ». stable« geändert.
E: Für das Depot »https://packages.grafana.com/oss/deb stable InRelease« wurde der »Label«-Wert von »grafana stable« in ». stable« geändert.
N: Sie müssen dies explizit bestätigen, bevor Aktualisierungen von diesem Depot angewendet werden können. Lesen Sie die apt-secure(8)-Handbuchseite, wenn Sie weitere Informationen benötigen.
```

any idea ?

**Comment by lnicola** [comment]
To make things easier for anyone searching for this:

```
E: Repository 'https://packages.grafana.com/oss/deb stable InRelease' changed its 'Origin' value from 'grafana stable' to '. stable'
E: Repository 'https://packages.grafana.com/oss/deb stable InRelease' changed its 'Label' value from 'grafana stable' to '. stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

**Comment by Becker884** [comment]
I don´t get the option to accept !

**Comment by lnicola** [comment]
Maybe you have `DEBIAN_FRONTEND=noninteractive` somewhere? I don't know much about `apt`.

**Comment by weastur** [comment]
Hi, why change labels at all? It breaks updates with automotive systems like Ansible and Puppet. 

I'm not sure, but change 'grafana stable' to '. stable' looks like a bug, isn't it?

**Comment by daenney** [comment]
I"m getting a certificate validation issue on Ubuntu 20.04:

```
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 151.101.86.217 443]
```

The chain from ISRG X3 looks valid, but I'm guessing the fallback chain isn't anymore?

Both apt-transport-https and ca-certificates are up to date.

**Comment by kosza** [comment]
Hi,

Check [https://packages.grafana.com/enterprise/](https://packages.grafana.com/enterprise/).

1. Replaced the link to https://apt.grafana.com in /etc/apt/sources.list.d/grafana.list
2. `apt update`, apt could download the index files
3. `apt upgrade`

**Comment by tonypowa** [comment]
As pointed out by @weastur please find the details of the cause and solution by @julienduchesne  here
https://community.grafana.com/t/grafana-oss-debian-repo-changes-origin-label-is-this-intended/75330/2
