### ISSUE TITLE
Alert history

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5850]
It should be possible to see alert history at two places.

 - [x] For each alert in the alert_tab
 - [ ] Global list to see the X last alert state changes.

**Comment by phagedorn** [comment]
Alerts in the alert history should be duplicated for sequenced alerts with the same reason.
Only a counter should be visible after the first alert ?

**Comment by bergquist** [comment]
@phagedorn alert history will only contain state changes.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/issues/5981
