### ISSUE TITLE
Alerting: Move rule diff logic out of store package

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#58527]
The rule diff logic isn't really part of `store`, logically. It only depends on `store`'s exported APIs and is independent of database. We should find a better home for it.

https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/store/deltas.go

**Comment by sladyn98** [comment]
@alexweav I could give a shot at implementing this, where exactly would we want to move the diff logic.
