### ISSUE TITLE
Dashboards: `Copy` button should still be visible/usable on non-editable dashboards

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#58548]
**What happened**:
I tried to copy a panel from a non-editable dashboard onto an editable one.
Specifically the "Current Billable Metrics Series" panel, from the GrafanaCloud Billing/Usage dashboard:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/2903904/200939911-3176a85c-398d-404d-8d9b-ce0ca98e5212.png">
https://play.grafana.org/d/vXjDa4IVk/billing-usage

I need this on my own custom dashboard which I use to manage my own spend, and share with my colleagues.

But it's impossible to copy that panel, because it's on a non-editable (ie. Provisioned) dashboard. In order to copy it I first have to click the gear ⚙️ symbol, click **Edit Dashboard**, and then I can copy it. Even this I can only do on Grafana Instances where I am an admin I think - I can't edit that dashboard on play.grafana.com, so it's impossible for me to copy that panel on that instance.

**What you expected to happen**:
Any panel that I can view I should also be able to copy, so that I can then paste that panel on a new dashboard that I am building/editing.

Ie. the **More > Copy** option should _always_ show:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/2903904/200940484-cc8c24b8-c0bd-428a-9a44-b6a66b7416b3.png">

**How to reproduce it (as minimally and precisely as possible)**:

As described above

**Anything else we need to know?**:

I think there are other options that should also always be available but aren't yet on provisioned dashboards- just take a visual diff of the screenshots I shared above. The ones I can see are:

- Copy
- Create Library Panel
- Get Help

**Environment**:
- Grafana version: v9.2.3-997144b7 (997144b79f)
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: MacOS 12.6.1 (21G217), Chrome 107.0.5304.87 (Official Build) (arm64)

**Comment by zuchka** [comment]
thanks for reporting this @samjewell 

guessing [the `canEdit` check in this if statement](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/utils/getPanelMenu.ts#L180-L190) plays a role here. But also, the provisioned dashboard part adds another layer to this issue.

Agree that things could be clearer. Passing this along to the code owners. In the meantime, **there is a way to extract that panel JSON from play as a viewer-role.** There is a third workflow for grabbing panel JSON: using the `Share dashboard or panel` widget at the top:

![CleanShot 2022-11-13 at 20 51 08](https://user-images.githubusercontent.com/37156449/201594124-fb33a3c9-fb98-4061-ac4a-f56c9b141d3f.gif)

**Comment by axelavargas** [comment]
Fixed by https://github.com/grafana/grafana/pull/64826 🥳
