### ISSUE TITLE
grafana exemplar color changed

### ISSUE THREAD

**Issue by zdyj3170101136** [grafana/grafana#58554]
**What happened**:

when i upgrade grafana, the exemplar color is green:

![截屏2022-11-10 下午3 19 46](https://user-images.githubusercontent.com/52686065/201025474-01b94b76-6bbf-4d2f-9470-8dda41125c67.png)

**What you expected to happen**:

the color should be white just like grafana 7.x.

**Comment by usmangt** [comment]
Hi @zdyj3170101136,

Thanks for opening this issue.

What Grafana version you are before and now and what operating system are you using?

**Comment by ivanortegaalba** [comment]
Hi @zdyj3170101136, we're missing some info to be able to reproduce this issue.

* Previous and updated version
* Dashboard data (I attached a gif, of how to get it). 
* Which product or view you can find in that panel? Is it a custom dashboard, or it is a plugin view like k8s?

![Image](https://user-images.githubusercontent.com/5699976/201878265-44dcda46-e55f-49fc-958b-255a688e8e65.gif)

Thanks

**Comment by zdyj3170101136** [comment]
> 你好@zdyj3170101136，我们缺少一些能够重现此问题的信息。
> 
> * 以前的和更新的版本
> * 仪表板数据（我附上了一张 gif，说明如何获取它）。
> * 您可以在该面板中找到哪个产品或视图？是自定义的dashboard，还是像k8s一样的plugin view？
> 
> ![图片](https://user-images.githubusercontent.com/5699976/201878265-44dcda46-e55f-49fc-958b-255a688e8e65.gif) [ ![Image](https://user-images.githubusercontent.com/5699976/201878265-44dcda46-e55f-49fc-958b-255a688e8e65.gif) ](https://user-images.githubusercontent.com/5699976/201878265-44dcda46-e55f-49fc-958b-255a688e8e65.gif) [ ](https://user-images.githubusercontent.com/5699976/201878265-44dcda46-e55f-49fc-958b-255a688e8e65.gif)
> 
> 谢谢

i want to know the expected behavior, is the examplar designed color is  white or could changed?

**Comment by ivanortegaalba** [comment]
Thanks for the info. With the snapshot you sent, I don't see any specific palette assign to that chart. Did you have any custom palettes or overrides assigned to that chart that have been lost?

Anyways, You can add custom colors to the series using overrides. You can find an example in our playground https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2&showCategory=Override%201
