### ISSUE TITLE
Templating: Referencing a panel in repeating row always uses data from first row panel

### ISSUE THREAD

**Issue by padyx** [grafana/grafana#58558]
**What happened**:
When creating a repeating row with a time series panel, and a stats panel that has the time series panel as the source (source "Dashboard"), any subsequent stats-panel "clones" of this repeating row reference the _first_ time series panel.

**What you expected to happen**:
I expected that the repeating panel references the timeseries panel from the same repeating row instance, that it is located in.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create dashboard
2. Create variable with multiple values, and a "select all option"
3. Create repeating row and reference the variable from above
4. Create time series panel, filtering for the variable.
5. Create stats panel, select source=Dashboard and select the time series panel created before.

<summary>Reproducible on playground</summary>
<details>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1317,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "panels": [],
      "repeat": "job",
      "repeatDirection": "h",
      "title": "$job",
      "type": "row"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "lXkyJe6nk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 1
      },
      "id": 6,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "lXkyJe6nk"
          },
          "editorMode": "code",
          "expr": "go_threads{job=\"$job\"}",
          "legendFormat": "__auto",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Job $job",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 1
      },
      "id": 10,
      "options": {
        "colorMode": "value",
        "graphMode": "none",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "9.2.3-997144b7",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 6,
          "refId": "A"
        }
      ],
      "title": "Number",
      "type": "stat"
    }
  ],
  "refresh": "",
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": "All",
          "value": "$__all"
        },
        "datasource": {
          "type": "prometheus",
          "uid": "lXkyJe6nk"
        },
        "definition": "label_values(go_threads, job)",
        "hide": 0,
        "includeAll": true,
        "multi": false,
        "name": "job",
        "options": [],
        "query": {
          "query": "label_values(go_threads, job)",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "#43097 imported",
  "uid": "T202C0Tnk-clone",
  "version": 1,
  "weekStart": ""
}
```
</details>

**Anything else we need to know?**:

In this picture, we'd expect "8" for the first stats panel, but "7" for the second.
![image](https://user-images.githubusercontent.com/649179/201040150-afb52437-4127-4747-b4da-4907b780051c.png)

**Environment**:
- Grafana version: 9.2.3 (Playground), 9.1.7 (our instance)
- Data source type & version: Prometheus
- OS Grafana is installed on: Unknown (playground), Linux (our instance)
- User OS & Browser: Windows, Microsoft Edge Version 107.0.1418.35 (Official build) (64-bit)
- Grafana plugins: None apart from built-in
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @padyx, and doubly thanks for the JSON and the thorough reproduction steps.

Was able to replicate the bug using OP's JSON, which I've saved [on play.grafana here](https://play.grafana.org/d/T202C0Tnk-58558/58558?orgId=1&var-job=All&from=1668246379492&to=1668293391257)

**Comment by txjmb** [comment]
Also having this problem.  Causes a real issue for any templated dashboard using dashboard datasource.

**Comment by padyx** [comment]
Probably #52930 referenced the same problem in an older version.

I guess the dashboard datasource query logic mostly comes from https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/dashboard/runSharedRequest.ts ?

I don't have knowhow regarding how repeating rows work - if someone has a hint, maybe we can brainstorm enough for a PR :D

**Comment by lelithium** [comment]
Also affected by this in Grafana 9.4.7

**Comment by Rumbelstilzchen** [comment]
Still present in 9.5.1

**Comment by padyx** [comment]
I think I've narrowed it down to the initialization of the panels when the dashboard is loaded.

1. In `DashboardModel.ts` the `repeatRow` function is called to created the repeating panels.
2. It clones all panels in the source row, and then calls `updateRepeatedPanelId` which assigns it a new id.
3. It looks to me that the problem is that the `panelId` from the `DashboardQuery` (dashboard/types.ts) is _not_ updated to match to the new source.

If I edit those references in the browser inspector during cloning, then it works correctly.
So probably some remapping is required there.

**Comment by padyx** [comment]
I've managed to cobble together a fix that works "on my machine". It's crude and certainly wouldn't pass any kind of inspection or quality barrier for now:
https://github.com/grafana/grafana/compare/main...padyx:grafana:58558-repeating-dashboard-panel

Maybe I can bring it up to scratch, but probably a maintainer or @zuchka should say what the proper fix should look like 😃

Specifically, since accessing the property from the DashboardModel is probably not the proper way to fix this.
