### ISSUE TITLE
GET `api/search`(v1/v2) not working with folderUid

### ISSUE THREAD

**Issue by lpskdl** [grafana/grafana#58569]
To completely migrate on using folderUid in the frontend GET api/search should also return the list of alerts attached to a folder if a folderUid is passed. At the moment it is only working with folderId

This is also blocking https://github.com/grafana/grafana/issues/58564

**Comment by lockan** [comment]
This would be a greatly appreciated addition. We're currently trying to provisions alerts programmatically, but the PUT endpoint - /api/v1/provisioning/alert-rules/{UID} - for updating an alert-rule assumes you know the UID of the rule. Currently - as far as i can tell - there's no way to query the api to retrieve that alert-rule UID.
