### ISSUE TITLE
Alert notification silencing

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5856]
_We are not really sure about how to design the silencing part of alerting. But our intial take is something like this._

Silencing alerts means that no notifications regarding state changes will be sent. The Alerts will still execute and save state changes to the database. Silence rules should have an explicit end time to avoid silencing alerts for ever by mistake. It should be possible to have recurring silencing rules to be able to silence certain alerts during nights etc. 

It should be possible to silence by
- Alert Id
- Dashboard Id
- Notification channel
- Alert name pattern
- Alert eval match name pattern

Alert silence rules are always temporary, IE they have a TTL

**Comment by linkslice** [comment]
My 2 cents are that if a notification has been sent prior to a silenced rule taking affect that a clear notification should go out regardless of the current state even if snoozed.

**Comment by andrestc** [comment]
I dont know if this is possible, but silencing by datasource would also be pretty interesting if you expect some downtime during scheduled maintenance on the datasource.

**Comment by doanerock** [comment]
Yes, this is greatly needed!

**Comment by kierangirvan** [comment]
This would be a great addition to the alerting functionality.

I have a requirement to pause alerting overnight (as the system I'm monitoring undertakes a number of end-of-day activities i.e. pause alerts daily between 2am and 5am.  Is this something that can be included?

**Comment by monokal** [comment]
Closed?
https://github.com/grafana/grafana/issues/11378 links back to this Issue.

**Comment by freibuis** [comment]
For those who want a dirty way to silence your the alert-notifications..
list notifications
/api/alert-notifications
then change isDefault to false...

this assumes all `send on all alerts` is ticked in the notification channels..

I would suggest against this method as I have now seen a bug where if the isDefault is off then you manually add an alert notification for the same type in the GUI once save then refresh the screen the alert notifications will show an incremental number but the gui will not show the attached notifications `send to`
aside from this bug this method is dirty but works, the alarm is still on.. just not getting an notifications

for those who care about this bug..
the notifications data in the get alerts api end point returns multiple of the same id when this happens.
```ruby
     "notifications" => [
            [0] {
                "id" => 2
            },
            [1] {
                "id" => 2
            },
            [2] {
                "id" => 2
            }
```

**Comment by bcbeynon24** [comment]
Creating blackout/maintenance windows would be great!  Any update on when to expect in future release?

**Comment by bergquist** [comment]
It will be available in the next major version of Grafanas alerting.

**Comment by raags** [comment]
@bergquist is this on the roadmap, part of any subsequent releases?

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by jadrovski** [comment]
Missing that feature!

**Comment by giuliocalzolari** [comment]
any update on this feature?
any ETA?

**Comment by doanerock** [comment]
Would love an update.  There are machines that different alerts need to be ignored on a regular basis like a machine that gets rebooted once a month, I don't want to get alerted so I need to be able to silence the alarm for a set of time.  I really need to be able to pause them on a recurring basis, and not just manually one time.  This this feature is holding me back from completely switching.

**Comment by megha-jindal** [comment]
would love to know any updates on this feature

**Comment by primoz-p** [comment]
I would love something like that too.
It is easy to do that in PagerDuty and it will be nice to make that happen inside Grafana too. During every maintenance session we get a lot of not useful alerts all over the place.

**Comment by loganmc10** [comment]
Yes the ability to apply an "alert modifier" to partially silence an alert would be nice. For instance if you have an alert for CPU>70%, but you could silence it if "device=denver*" for a period of time would really help with maintenance windows

**Comment by orojina** [comment]
In case you find this useful I created a script to pause and resume alerts. I believe you can put it in a cron job or a pipeline and manage schedules there. As a temporary solution 

https://github.com/orojina/grafana-cli

**Comment by v1ru535** [comment]
Thanks @orojina it works like a charm!

**Comment by doanerock** [comment]
@orojina grafana-cli is really neat.  It is a good stop gap until grafana finishes building out true maintenance schedules into the web UI.  I will enjoy using grafana-cli.

**Comment by orojina** [comment]
@doanerock thanks a lot for your feedback. Im glad to hear that grafana-cli is useful for your needs! :)

**Comment by grimz-ly** [comment]
yeah. gaps in Grafana monitoring when trying to leverage as a somewhat traditional monitoring system of many targets. I've used 'targets' solely in reference to Prometheus.

Two key items of value which I know the second has an open issue. I'd love to know if the 1st doesn't and I'll gladly create one.

1. Scheduled pause of alerting at the target level (need to work on a single target)
2. Alerting based on defined hours of the day and/or days of the week vs 24/7

**Comment by a-mazed** [comment]
Are there any news on this issue?
Would like to have it.

**Comment by gotjosh** [comment]
Hey everyone!

Apologies it took us this long to get a response on such issues, for a while now Grafan has had a dedicated Alerting team to expedite such features. 

Silencing is now a core feature of Unified Alerting and pausing all the alerts of a rule is possible via https://grafana.com/docs/grafana/latest/alerting/unified-alerting/silences/

Also, silencing for a period of time is possible via https://grafana.com/docs/grafana/next/alerting/unified-alerting/notifications/mute-timings/

Let us know if there's anything else we're missing as part of a feature request for Alerting within Grafana's Discussions system.

**Comment by orojina** [comment]
@gotjosh thanks for the good news! 🎉 

Do you know if those new features are also available via grafana http api ? I 've been looking for it in the documentation but I didnt find it.

Thanks in advance 🙌🏻

**Comment by akovov** [comment]
by the way pausing by Alert ID not working anymore with unified alerting, silences have been created but do not affect rule, as it not a part of labels set.
