### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5857]
This is something we have meant to do for a long time but never gotten around to. The goal for the integrations tests is to be able to test:
- [x] sql migrations for mysql/postgres/sqlite3
- [ ] grafana-cli
- [ ] sessionstorage for redis/memcache
- [ ] login flow 
- [ ] alert rule execution
- [ ] alert notifications

**Comment by torkelo** [comment]
maybe start talking about this? seems like something that we need. 

Interesting how to setup the alert tests.

**Comment by bergquist** [comment]
I changed the list into a checkbox list. I think we can start small and just check them off one by one.

**Comment by bergquist** [comment]
Kicking it down the road.
