### ISSUE TITLE
Popup truncated data

### ISSUE THREAD

**Issue by tral** [grafana/grafana#5859]
* **I'm submitting a ...**
- [x] Bug report

- Grafana version 3.0
- SimpleJSON Datasource
- Debian

If there are a lot of metrics, data is truncated in the pop-up: http://i.imgur.com/JSwUwFp.png
Can you increase or remove the maximum height constraint of this pop-up?

**Comment by bergquist** [comment]
Having an endlist popup would also be problematic. Not sure about this.

Something that might in your case is "with only zero" 
![image](https://cloud.githubusercontent.com/assets/618863/17846546/83b393e6-6849-11e6-82a5-857c2c7ecc30.png)

**Comment by tral** [comment]
thanks! It fitsmy needs perfectly!

**Comment by bergquist** [comment]
Great! Closing this since we wont make the popup endless atm
