### ISSUE TITLE
Admin: Invite email includes a broken link to Grafana logo

### ISSUE THREAD

**Issue by BrunoBlanes** [grafana/grafana#58617]
**What happened**:
Grafana logo on invite email doesn't render

**What you expected to happen**:
An image to be displayed

**How to reproduce it (as minimally and precisely as possible)**:
Send an invite email through Grafana

**Anything else we need to know?**:

Broken link:
```html
<img class="logo" src="https://grafana.com/assets/img/logo_new_transparent_200x48.png" style="width: 200px; display: inline; outline: none !important; text-decoration: none !important; -ms-interpolation-mode: bicubic; clear: both; border-width: 0;" align="none" />
```

**Environment**:
- Grafana version: 9.2.4
- Data source type & version:
- OS Grafana is installed on: CentOS 9 Stream
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by gg-g** [comment]
Looks like it has to be https://grafana.com/static/assets/img/logo_new_transparent_200x48.png

**Comment by zuchka** [comment]
Thanks for creating this issue, @BrunoBlanes 

can confirm this. looks like [the link is broken](https://github.com/grafana/grafana/blob/mja%2Ffix-transformation-descriptions/public/emails/invited_to_org.html#L186-L187)
