### ISSUE TITLE
 Grafana Unified Alerting always uses first image on dashboard in email notifications for multidimensional alerting

### ISSUE THREAD

**Issue by gg-g** [grafana/grafana#58624]
**What happened**:

I have a dashboard with repeating rows for a variable. The row contains a panel on which I defined an alert using Grafana unified alerting. I’m using multi-dimensional alerting to create multiple alert instances. The notifications are sent by email. All of this works fine.

When testing and triggering alerts for several instances of the variable, I noticed that in each email the same panel screenshot (first on the page for the first variable instance) is included even though the labels and values correspond to other variable instances.

**What you expected to happen**:

The relevant image to be embedded in the alert

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

Is this a limitation?

The only information I found that could be related was on [Images in notifications 9](https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/) where it states:

> Some contact points only handle a single image. In this case, the first image associated with an alert will be attached.

**Environment**:
- Grafana version: 9.1.6 (92461d8d1e)
- Data source type & version: MariaDB 10.6.7
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.9 (Maipo)
- User OS & Browser: Windows 10 / Firefox 102.4.0esr (64-bit)
- Grafana plugins: Grafana Image Renderer: 3.6.1
- Others:

**Comment by mellieA** [comment]
@gg-g yes, it looks like you found the right docs for this issue. This is a limitation of images, as mentioned in the docs, the way to ensure that you get a single image for each alert is to make sure that your alert groups contain a single alerting rule.
