### ISSUE TITLE
for XY plots label is set on both Axis with no option to set x and y individually

### ISSUE THREAD

**Issue by naveen-rawat-cohere** [grafana/grafana#58622]
**What happened**: When configuring XY plots axis label, there is only one text field to provide label and it applies to both X and Y axis.

**What you expected to happen**: I expected two text box 1 for each of X and Y axis.

**How to reproduce it (as minimally and precisely as possible)**: set label in XY plot

**Anything else we need to know?**:
![Screenshot 2022-11-10 at 8 58 34 PM](https://user-images.githubusercontent.com/72522487/201267056-67ebf17d-1fdb-4c3f-809c-e26ab33467ea.png)

**Environment**:
- Grafana version: Version 9.2.2 (commit: 78a3e64e4f, branch: HEAD)
- Data source type & version: mysql  Ver 8.0.31 for Linux on x86_64 (MySQL Community Server - GPL)
- OS Grafana is installed on: CentOS 7: Linux ran5 3.10.0-1160.53.1.rt56.1193.el7.x86_64
- User OS & Browser: Mac OS 13.0, Safari 16.1
- Grafana plugins: XY Chart by Grafana Labs 5.0.0
- Others:

**Comment by leeoniya** [comment]
you can use field overrides to change these

**Comment by zuchka** [comment]
@naveen-rawat-cohere here is an example I added to play.grafana.org, our public sandbox:
https://play.grafana.org/d/_bjH2iOVz/xy-chart-axis-label-overrides?orgId=1

![CleanShot 2022-11-15 at 21 37 42@2x](https://user-images.githubusercontent.com/37156449/202117195-ec97de8b-73bb-44c9-af5c-9c4d93e036cf.png)

**Comment by naveen-rawat-cohere** [comment]
thanks... this helped.
