### ISSUE TITLE
[Feature Request] - Limit dashboards.json to specified organization

### ISSUE THREAD

**Issue by Diginomicon** [grafana/grafana#5862]
Currently in v3.1 when you use the [dashboards.json] feature to upload dashboards to the server directly, they are included in all organizations that exist within grafana.  It would be useful if it was possible to limit them to a specific organization that could either be globally specified in the ini file or as meta data in the json itself so that each chart could be assigned to a unique organization.

**Comment by mtanda** [comment]
Grafana 5.x dashboard provisioning can specify org id.
http://docs.grafana.org/administration/provisioning/

**Comment by bergquist** [comment]
Closing this since [dashboard.json] have been replaced with provisioning which supports this (as mtanda mentioned)
