### ISSUE TITLE
Prometheus: Remove raw query toggle in query builder and always show raw query 

### ISSUE THREAD

**Issue by diegoadams** [grafana/grafana#58626]
What happened:

In the Prometheus query builder, we have a toggle for Raw query that is used to toggle the preview of the query that the query builder produces. During a few user interviews, we've noticed that the query editor has (too) many buttons/toggles, which makes small buttons basically invisible. Moreover, no users we talked to toggle their query preview off.

To reduce the number of buttons/toggles we decided that it would make sense to:

- Remove the Raw query toggle
- Always show raw query (query text)
- Remove the heading/title Raw query.

<img width="630" alt="Screenshot 2022-11-11 at 11 20 05 AM" src="https://user-images.githubusercontent.com/95694434/201309105-da1e8e2e-281f-4430-bac0-d74564e88bc3.png">

The Loki Query Builder is doing the same, reference here:
https://github.com/grafana/grafana/issues/58511

**Comment by samjewell** [comment]
@diegoadams you said:
> The Loki Query Builder is doing the same, reference here:
> https://github.com/grafana/grafana/issues/56943

But you referenced one of my issues, which I think is unrelated! Just letting you know :-)

**Comment by gtk-grafana** [comment]
@diegoadams thanks for submitting this issue! I played around with this for a while, and I've got some thoughts, but no actions I think we should take, besides implement the requirements as described.

A minor concern for users with simple queries, the raw query seems redundant from what's already displayed when using the "explain" functionality, i.e. the other toggle in the query editor:
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/109082771/203135720-e7951af0-8c0e-43ac-8d3d-717fd2a2ce77.png">

However when Operations are introduced into the query, the raw query shows how it all comes together. 
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/109082771/203135341-20c15e55-c5ff-42b7-9b36-94f3355f1a44.png">

My other concerns are that some people might feel upset that we took away their ability to toggle this field on their own, as that it does add to how busy the editor is.

I played around with only showing this field when the explain toggle was active, so users would still have an option to hide seeing any promql, but I think that's unfair to those with more complicated queries who don't want the in-depth explanation of each function, but still want to see the final output. 
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/109082771/203136372-16a412ed-73bd-409b-834d-7d47983f98f2.png">
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/109082771/203136400-3e8949a7-4c66-4c6b-ab0d-8f4c6df126a1.png">

These minor concerns aside, I feel that this is a positive change for the query editor that aligns well with our goals. Also removing the higher contrast heading text did a really good job decreasing how visually distracting this section is!

**Comment by diegoadams** [comment]
> @diegoadams you said:
> 
> > The Loki Query Builder is doing the same, reference here:
> > #56943
> 
> But you referenced one of my issues, which I think is unrelated! Just letting you know :-)

Thanks for picking this up Sam. My mistake, I've updated it with the correct link

**Comment by diegoadams** [comment]
Hey @gtk-grafana , thanks for bringing this up and sharing some examples. I agree with you on the points raised. 🙂

**To add to your comments, these are my additional thoughts.** 
One positive is that the "raw query" doesn't take up too much real estate, even when the query is complex. It is usually on a single line. 
However, I think it does get lost at the bottom. A future iteration may be to move it to the top somewhere.  

For now, I think the best way forward is to see how users respond to these new changes.

**Comment by gtk-grafana** [comment]
Awesome, I'll work with the team next week to get that PR approved and merged. Thanks @diegoadams!
