### ISSUE TITLE
[Feature request] Showing actual percentage/values inside BarChart with (or) without stack mode

### ISSUE THREAD

**Issue by deepak-kosaraju** [grafana/grafana#5863]
Any plans to show the percentage/value inside BarChart with (or) without stack mode, like below.. it can be an option for user to either display it (or) not display it?

<img width="638" alt="screenshot 2016-08-18 11 40 46" src="https://cloud.githubusercontent.com/assets/1418472/17787120/a229113a-653c-11e6-9976-d091333f697f.png">

**Comment by bergquist** [comment]
I don't think its likely that we will add this in the near future. Maybe if this issue get lots of up votes.

**Comment by kkdk5535** [comment]
@bergquist 
Thanks for prompt response. Will look forward if this will hit the master one day.

**Comment by ank-everstake** [comment]
+1
Seems it could fix another case when there are relatively small values and you set "Show values" to "Always".

small values + staking + always show values  = ![image](https://user-images.githubusercontent.com/56387196/209885489-a2185cf1-c86f-4b48-a6a9-ab1329123b2a.png)

That's easy to simulate on [play](https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&viewPanel=15&editPanel=15)

@codeincarnate maybe it is feasible now to add this to #59458 ?
