### ISSUE TITLE
Support display/visualization of data response status in the UI

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#58637]
With https://github.com/grafana/grafana-plugin-sdk-go/pull/544 merged it results in query data responses having a `status` property rendered in the JSON response being returned from the /api/ds/query endpoint. This `status` property can have an HTTP status value, e.g. 200 Ok, 500 Internal server error etc.

By default, when data response doesn't include an error, the status 200 (Ok) is set:
![image](https://user-images.githubusercontent.com/1668778/201333395-3d90bdd6-b810-42cf-85e8-6abb9a67e20f.png)

By default, when data response include an error, the status 500 (Internal server error) is set:
![image](https://user-images.githubusercontent.com/1668778/201333451-ab31b7c9-cbf1-4502-a91b-63a40f4b35a5.png)

A plugin author could implement support in backend plugin for setting the status and by that circumvent the default behavior referenced above.

We want/need to support data response status code being displayed/visualized when there's an error to give end users more context of why an error happened. 

Open questions:
- How to display/visualize status code from a UX perspective? 
  - Is the existing query inspector enough perhaps?
  - Do we want to combine it somehow with the existing error message already being shown for panel errors, e.g. 
![image](https://user-images.githubusercontent.com/1668778/201334285-1e870ddb-2a87-46a3-ba0e-986973cc54d9.png)
  - Do we want to combine it somehow with the existing error message already shown for Explore query/panel query editing, e.g. 
![image](https://user-images.githubusercontent.com/1668778/201334506-43f35e20-ca89-43e9-ba2c-56ecf0341eae.png)
![image](https://user-images.githubusercontent.com/1668778/201334616-ef6e8880-35ee-48db-ba28-33aecb566573.png)

**Comment by itsmylife** [comment]
Also tagging @diegoadams for UX ideas.

**Comment by tolzhabayev** [comment]
Any updates @itsmylife ?

**Comment by itsmylife** [comment]
I think it is mostly @grafana/user-essentials squad domain (maybe even a UX question). I can Just show the status code in the error message but I think @grafana/user-essentials might have a better solution for this. I am assigning to them. 

@grafana/user-essentials if you folks think that is wrong feel free to reassign to us.

**Comment by JoaoSilvaGrafana** [comment]
Sorry to keep moving this around, but since this seems to be related to panels I think it would be something @grafana/dashboards-squad would have more knowledge of, so I will move it to their board. Do let us know if we can help in some way though.

**Comment by axelavargas** [comment]
Hey @marefr 👋🏾,  I am gonna give it a try and answer your open questions 😄 👍🏾 

Open questions:

> How to display/visualize status code from a UX perspective? 
> Is the existing query inspector enough perhaps?
> Do we want to combine it somehow with the existing error message already being shown for panel errors, e.g.
> Do we want to combine it somehow with the existing error message already shown for Explore query/panel query editing, e.g.

I would say yes, it would be great to display these errors in the existing panel errors and explore/panel query editing, it will keep what we have consistent :). Also, this is aligned with our current efforts with the 'new panel header', you can see what it will look like by enabling the 'newPanelChromeUI' feature flag.

![image](https://user-images.githubusercontent.com/239999/217018345-05030e03-1fe4-4a55-903c-4228c6c80b0d.png)

Let us know if you have any questions :).

ps, here is the [epic](https://github.com/grafana/grafana/issues/56163) of the new panel header :)

**Comment by dprokop** [comment]
I think it's worth looping in @Ijin08 and @grafana/explore-squad.

Regarding the questions asked by @marefr :
>How to display/visualize status code from a UX perspective?
>Is the existing query inspector enough perhaps?
>Do we want to combine it somehow with the existing error message already being shown for panel errors, e.g.
>Do we want to combine it somehow with the existing error message already shown for Explore query/panel query editing, e.g.

I am not sure if showing the status code directly in the error alert makes that much of a value. I would probably expect those error messages shown in the UI to be actionable, and i.e. allow the user to open Inspector for learning more about the error (status code included) if necessary. 

I wonder if support engineering would benefit anyhow from having the status code explicitly visible in the UI?

**Comment by andresmgot** [comment]
Thanks @dprokop @Ijin08! This is how it may look like: https://github.com/grafana/grafana/pull/63575. I added your comment in the PR, feel free to add more thoughts there!
