### ISSUE TITLE
query to influxDB converts to floating point

### ISSUE THREAD

**Issue by amoghd** [grafana/grafana#5864]
- Datasource: InfluxDB 0.10
- OS Linux
- What did you do?
  In the metrics selector, I use the graphical interface to construct queries. While constructing the query, grafana auto-fills possible tag keys and values using "show tag keys" queries to influxDB in the background. This is a wonderful feature as it makes data exploration so much easier. 

However, in the latest version, grafana seems to be converting numeric tag values to floating point type before issuing the query. 

For example, I have a tag named "ind" in my influxDB database. While constructing the query I select the value "1" for ind from the drop-down menu. After that, however, I cannot add further tags to the query filter, because the "show tag keys" query does not return any results. This is what grafana sends to influxDB:

[query] 2016/08/18 13:30:58 SHOW TAG KEYS FROM tspmult."default".tsplnk WHERE ind = 1.000

The value of the "ind" tag is '1'. It shows up properly in the drop-down menu but grafana is converting it to 1.000 while issuing the query. This causes influxDB to not return any results, and then metric exploration is broken from there on. 
- What was the expected result?

grafana should have passed the query to influxDB as: 
[query] 2016/08/18 13:30:58 SHOW TAG KEYS FROM tspmult."default".tsplnk WHERE ind = '1'
- What happened instead?

Please see query pasted above.

**Comment by bergquist** [comment]
related https://github.com/grafana/grafana/issues/4744

**Comment by amoghd** [comment]
Any word on this? Is there a workaround by any chance? I would really love to use the 4.0 beta of grafana, but this problem is preventing me from upgrading because metric exploration capability is broken.  
Does using a newer version of influxDB (e.g., 1.0) make any difference?

**Comment by gabor** [comment]
this works fine now.
