### ISSUE TITLE
Github oauth provider only supports 30 organizations, prevents login for some users

### ISSUE THREAD

**Issue by sdague** [grafana/grafana#58645]
**What happened**:

A new grafana installation attached to enterprise github oauth, which has login restricted to a single. One of our users was in a large number of organizations (54), and was getting login failures that he was not in the require organization. It appears that while the github teams lookup supports pagination, the github orgs function does not.

https://github.com/grafana/grafana/blob/main/pkg/login/social/github_oauth.go#L155-L179

**What you expected to happen**:

Users with > 30 organizations can log in.

**How to reproduce it (as minimally and precisely as possible)**:

Create a very large number or github orgs, put users in that, and filter based on github org. I can cause failures.

**Comment by usmangt** [comment]
Hi @sdague,

Thanks for opening this issue.

I have forwarded it to our team so that they can have a look and will get back to you once they have more information.
