### ISSUE TITLE
Geomap: Allow multiple queries in same panel 

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#58640]
**What happened**:
Using multiple query's e.g. A and B the data is not show on map at the same time. In order to show data from "B" I need to disable query "A"

![image](https://user-images.githubusercontent.com/8969659/201335732-3a7b54d2-0365-485d-b85d-995ab4d7bcc1.png)

**What you expected to happen**:

markers from both query's to be shown

**How to reproduce it (as minimally and precisely as possible)**:
Make to query "A" and "B"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.6 
- Data source type & version: Influxdb 1.8
- OS Grafana is installed on: Windows server
- User OS & Browser: Google
- Grafana plugins: Geomap
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @HenrikRolandHansen 

this sounds like a feature request. passing it along to the geomap folks so they can chime in 👍

**Comment by HenrikRolandHansen** [comment]
👍

**Comment by Mateorid** [comment]
@zuchka from my understanding, this feature is already implemented (but is having some issues?). At least that's what I gathered from this - https://github.com/grafana/grafana/pull/49966#issuecomment-1142596977
I'm having the same issue (https://community.grafana.com/t/geomap-multiple-data-sources-not-working/74952)
