### ISSUE TITLE
Prometheus: Error when defining query-based variable

### ISSUE THREAD

**Issue by aSemy** [grafana/grafana#58651]
**What happened**:

I am trying to manipulate the name of a label, but I get an error.

`invalid parameter "match[]": 1:14: parse error: unexpected "("`

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/897017/201353160-b1e0e9c0-1d6e-48fc-a53a-f9ba3a712228.png">

```
label_values(
label_replace(
  feign_Client_seconds,
  "client_name",
  "$1",
  "client", 
  ".+\\.(.+)"
),
"client_name")
```

```
.+?(?<text>[a-zA-Z]+)
```

When I run the query in Prometheus it works as expected.

```
feign_Client_seconds{client="my.project.AlphaService"}
feign_Client_seconds{client="my.project.BetaService"}
feign_Client_seconds{client="my.project.GammaService"}
```

**What you expected to happen**:

I expect that the label names are everything after the last `.`, and the label values are the entire label.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Prometheus v2.40.1
- OS Grafana is installed on: Docker
- User OS & Browser: macOS Chrome
- Grafana plugins: none
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @aSemy 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

here is a prom datasource. you should be able to test a query-based template variable but not save it as a viewer: https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m&editview=templating&editIndex=2

It will be a lot easier for our devs to reproduce then.

**Comment by aSemy** [comment]
I don't have the time to reproduce this, so I'll close the issue.

**Comment by jcdauchy-moodys** [comment]
@Adam did you find a solution ?
