### ISSUE TITLE
ElasticSearch Array handling in Grafana

### ISSUE THREAD

**Issue by ictcorebiz** [grafana/grafana#5866]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? - **Grafana 3.1.0**
- What datasource are you using? - **ElasticSearch**
- What OS are you running grafana on? - **Linux**
- What did you do? - **Use Table panel (any panel will do)**
- What was the expected result? - **Being able to see content of arrays**
- What happened instead? - **no values shown**

Hi,

In our elasticsearch database there are many fields that contain arrays. I would like to access / graph / put information in tables about the values coming from those arrays.

Example record:

"myInfo": {
    "Field1":"Somevalue1",
    "Field2":"Somevalue2",
    "ArrayData":[{"City":"Amsterdam","Country":"NL"},{"City":"Paris","Country":"FR"}]
  }

**Comment by grikag** [comment]
This is very true,
I suggest to promote this issue to more critical,
In my opinion, It is very important to make Grafana supporting Elastic 100% to break away from Kibana - poor man's monitoring UI .

**Comment by torkelo** [comment]
could you describe the query you want to do? what is the panel you want to use? Table raw data? What is the ES response to the query you wish was possible?

**Comment by grikag** [comment]
The issue is related to core functionality of the ES datasource,
where "JSON to table" is limited to discovering top level elements, omitting sub and arrays types. 
As part of the wish list, it would be great to standardize "data searching and aggregation" to sql-like
wizard with option to use (reuse) native (ES) requests (quires).
Additionally, as much as many of us would appreciate :) providing already promised alerts management, 
  
Listing example per your request,
  
In trying to reproduce following table in Grafana, where column names (aliases), when reading data from ES, can be assigned by user.

![image](https://cloud.githubusercontent.com/assets/21126577/18039865/e740b4b8-6d74-11e6-8e47-064089a7b5fc.png)

where captured server statistics is stored in ES (see JSON example below)

{
  "_index": "ham-statistics-2016.07",
  "_type": "ham-statistics",
  "_id": "AVXA-P_mQicQP8jdqbYp",
  "_score": null,
  "_source": {
    "@version": "1",
    "@timestamp": "2016-07-06T16:09:51.124Z",
    "host": "serverlab-d5",
    "type": "ham-statistics",
    "log": {
      "_id": "4ce86403-835a-4b02-854d-2203cf7f51a4",
      "content": {
        "apiVersion": "1.0.0",
        "createDate": "2016-07-06T16:09:51.124Z",
        "modifiedDate": "2016-07-06T16:09:51.124Z",
        "modifiedBy": "LogGenie",
        "transactionStatus": 0,
        "entry": {
          "id": "19200d8e-495d-4927-9641-dcb16d61e824",
          "sourceURI": "tcp://server-mom-vd11.somedomain.com:7222",
          "sourceLocation": "server-mom-vd11",
          "contentType": "application/json; charset=utf-8",
          "payload": {
            "connectionStatistics": [
              {
                "address": "11.29.58.82",
                "admin": true,
                "clientID": null,
                "clientType": "J",
                "clientVersion": "8.3.0.14",
                "consumerCount": 1,
                "fT": false,
                "host": "serverlab-d5",
                "iD": 89,
                "producerCount": 1,
                "sessionCount": 1,
                "startTime": {
                  "$date": 1467132396082
                },
                "type": "QUEUE",
                "uRL": "[admin@serverlab-d5]",
                "uncommittedCount": 0,
                "uncommittedSize": 0,
                "upTime": 688995040,
                "userName": "admin",
                "xA": false
              },
              {
                "address": "11.29.58.54",
                "admin": true,
                "clientID": null,
                "clientType": "J",
                "clientVersion": "7.0.0.12",
                "consumerCount": 1,
                "fT": false,
                "host": "workstation-21621",
                "iD": 90,
                "producerCount": 1,
                "sessionCount": 1,
                "startTime": {
                  "$date": 1467816809000
                },
                "type": "QUEUE",
                "uRL": "[admin@workstation-21621]",
                "uncommittedCount": 0,
                "uncommittedSize": 0,
                "upTime": 4582122,
                "userName": "admin",
                "xA": false
              },
              {
                "address": "11.29.58.54",
                "admin": false,
                "clientID": null,
                "clientType": "J",
                "clientVersion": "7.0.0.12",
                "consumerCount": 2,
                "fT": false,
                "host": "workstation-21621",
                "iD": 91,
                "producerCount": 0,
                "sessionCount": 1,
                "startTime": {
                  "$date": 1467816815981
                },
                "type": "TOPIC",
                "uRL": "[admin@workstation-21621]",
                "uncommittedCount": 0,
                "uncommittedSize": 0,
                "upTime": 4575141,
                "userName": "admin",
                "xA": false
              }
            ],
            "durableStatistics": [],
            "queueStatistics": [
              {
                "bridgeTargets": [],
                "inboundStatisticsMessageRate": 0,
                "inboundStatisticsTotalMessages": 4848082,
                "outboundStatisticsMessageRate": 0,
                "outboundStatisticsTotalMessages": 0,
                "pendingMessageCount": 0,
                "pendingMessageSize": 0,
                "pendingPersistentMessageCount": 0,
                "pendingPersistentMessageSize": 0,
                "queueName": "$sys.admin",
                "receiverCount": 0,
                "routeConnected": false,
                "routeName": null,
                "routed": false,
                "static": true,
                "store": null
              }
            ],
            "topicStatistics": [
              {
                "durableCount": 0,
                "global": false,
                "inboundStatisticsMessageRate": 0,
                "inboundStatisticsTotalMessages": 0,
                "outboundStatisticsMessageRate": 0,
                "outboundStatisticsTotalMessages": 0,
                "pendingMessageCount": 0,
                "pendingMessageSize": 0,
                "static": false,
                "store": null,
                "subscriberCount": 1,
                "topicName": "$sys.monitor.server.warning"
              }
            ]
          }
        }
      }
    },
    "createDate": "2016-07-06T16:09:51.124Z",
    "filename": "ham-statistics-mom-vd11",
    "elasticsearch_index_name": "ham-statistics-2016.07"
  },
  "fields": {
    "@timestamp": [
      1467821391124
    ],
    "log.content.createDate": [
      1467821391124
    ],
    "log.content.modifiedDate": [
      1467821391124
    ],
    "createDate": [
      1467821391124
    ]
  },
  "sort": [
    1467821391124
  ]
}

where ES query might look like (see file attached),

[tibcoems-ham-statistics-2016.07.txt](https://github.com/grafana/grafana/files/441623/tibcoems-ham-statistics-2016.07.txt)

**Comment by grikag** [comment]
Torkelo :+1:  
Would you require more details ?
Thanks

**Comment by torkelo** [comment]
Provide the ES metric  quer and the ES response and the panel options you wish and pseudo code for how to parse the ES respons into table columns and rows
