### ISSUE TITLE
Short-URL: Sort of URL Spoofing with Short-URL API

### ISSUE THREAD

**Issue by Fiery-Fenix** [grafana/grafana#58677]
**What happened**:
Grafana Short URL API allows to create short URL to any Grafana instance URL, including, for example, "logout" endpoint

**What you expected to happen**:
Grafana Short URL API should filter out such requests and allow to create shorten URL only to dashboards/panels/explorer/etc.

**How to reproduce it (as minimally and precisely as possible)**:
Run API request with "logout" endpoint as parameter:
```
POST /api/short-urls HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
{
  "path": "logout"
}
```
Go to URL from response on this request and validate that you have successfully logged out.
By passing this short URL to another user of the same Grafana instance - user will be logged out after the click on link.
I believe that it's low severity security risk and looks like URL Spoofing attack.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Not applicable
- OS Grafana is installed on: Windows 10
- User OS & Browser: Firefox 106.0.3 (64-bit)
- Grafana plugins: none

**Comment by zuchka** [comment]
Thanks for creating this issue, @Fiery-Fenix 

confirmed this on main. to reproduce:
1. run this command to start grafana in a container: 
```
docker run --rm \
    -e GF_LOG_LEVEL=debug \
    -e GF_LOG.CONSOLE_LEVEL=debug \
    -p 3000:3000 \
    grafana/grafana:main
```
2. log in as user: admin and pass: admin. don't change the password.
3. run this cURL command to generate a url with admin:admin encoded in base64:
```
curl --header "Content-Type: application/json" \
  --header 'Authorization: Basic YWRtaW46YWRtaW4=' \
  --request POST \
  --data '{"path": "logout"}' \
  http://localhost:3001/api/short-urls
```
4. click the generated link and verify that it logged you out

**Comment by tolzhabayev** [comment]
@zuchka I am not quite sure it fit's the `type/bug` as it was never intended to apply any filtering to this service, the only thing it does is turning a relative path in a long form, generate a short uid and use it - similar to any short url service like bit.ly, etc. 

The only place I know it's being used is in the dashboards so I would love to hear what the @grafana/dashboards-squad thinks about this feature's intended functionality.

**Comment by dprokop** [comment]
I think the intended behavior was to shorten the dashboard/explore links, but no validation was implemented nor considered - hence any Grafana's path can be shortened.

**Comment by tolzhabayev** [comment]
Closing as it works as intended according to our dashboards squad
