### ISSUE TITLE
Navigation: Users with `Viewer` role can still open pages hidden from menu

### ISSUE THREAD

**Issue by Fiery-Fenix** [grafana/grafana#58675]
**What happened**:
Pages Import Dashboard, New Folder and New Dashboard are not visible for users with Viewer role, but could be opened using direct URL, see attached screanshots

**What you expected to happen**:
Users with Viewer role shouldn't have access to that pages and redirected to Home page, the same way as it done for New Alert page

**How to reproduce it (as minimally and precisely as possible)**:
* Install fresh copy of Grafana
* Create a user with Viewer role
* Login under that Viewer user
* Try to open following pages:
* http://localhost:8080/dashboard/import
* http://localhost:3000/dashboards/folder/new
* http://localhost:3000/dashboard/new?orgId=1

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Not applicable
- OS Grafana is installed on: Windows 10
- User OS & Browser: Firefox 106.0.3 (64-bit)
- Grafana plugins: none

![image](https://user-images.githubusercontent.com/2854059/201399973-e3da5517-8afb-4c6d-b9da-78e1e8d7923b.png)
![image](https://user-images.githubusercontent.com/2854059/201400063-a20ada19-1d01-424d-836a-5f65c3470553.png)
![image](https://user-images.githubusercontent.com/2854059/201400160-518547f0-bd65-4d9b-b49a-e009773025d6.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @Fiery-Fenix 

I can reproduce this on main and on play. log out of play.grafana and then click this link. accessible with a viewer-role:

https://play.grafana.org/dashboard/new?orgId=1
