### ISSUE TITLE
Template variable quoting kills graph

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#5867]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request

- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  prometheus
- What OS are you running grafana on?
  linux
- What did you do?
  I created a template variable to select graphs for different instances. After switching to multi-value to use the "repeat" feature, the graphs show no data.
- What was the expected result?
  Multiple graphs, one per selected instance with data.
- What happened instead?
  Graphs do appear, but no data.

**IMPORTANT** If it relates to metric data viz:
- metric query
  sum by (mode)(irate(node_cpu{job='node',instance='$instance',mode!='idle'}[5m]))

- Working query sent when multi-value is disabled:
`/api/datasources/proxy/1/api/v1/query_range?query=sum%20by%20(mode)(irate(node_cpu%7Bjob%3D%27node%27%2Cinstance%3D%27172.20.20.1%3A9100%27%2Cmode!%3D%27idle%27%7D%5B5m%5D))&start=1471593733&end=1471595533&step=2
`
- Faulty query sent when multi-value is used:
`/api/datasources/proxy/1/api/v1/query_range?query=sum%20by%20(mode)(irate(node_cpu%7Bjob%3D%27node%27%2Cinstance%3D%27172%5C%5C.20%5C%5C.20%5C%5C.1%3A9100%27%2Cmode!%3D%27idle%27%7D%5B5m%5D))&start=1471593739&end=1471595539&step=2
`

**Comment by rsommer** [comment]
Seems to be a duplicate of #5843

**Comment by bergquist** [comment]
To support multi-value templates your query should use the =~ operator ( instance=~'$instance' )
