### ISSUE TITLE
List of all dashboards is quite slow

### ISSUE THREAD

**Issue by pawellesniewski** [grafana/grafana#5868]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v3.1.1 (commit: a4d2708)
- What datasource are you using? Graphite, Zabbix
- What OS are you running grafana on? 14.04.5 LTS, Trusty Tahr
- What did you do? Users created lots of dashboards - currently we have more than two thousand dashboards. 

- What was the expected result? Getting list of available dashboards takes too long (around 1.5 sec). Is this possible to introduce some caching layer for this (memcached or redis) to get this list as fast as it is possible?
- What happened instead?

99p:
![zrzut ekranu 2016-08-19 o 10 22 49](https://cloud.githubusercontent.com/assets/7325296/17803920/8cde0c1e-65f9-11e6-9f56-f88d4e11e79e.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by bergquist** [comment]
How many dashboards do you have? what kind of database are you using?

**Comment by pawellesniewski** [comment]
Total dashboards: 2082 (i would say 95% of them in one organization). Percona 5.7 on separate machine (connection via network).

**Comment by torkelo** [comment]
Do you use MySQL or sqlite for the grafana database?

**Comment by bergquist** [comment]
With that amount of dashboard I strong encourage you to use mysql/postgres for Grafana.

**Comment by pawellesniewski** [comment]
Percona = MySQL :)

**Comment by bergquist** [comment]
I'm talking about the database you store dashboards in. Which by default is sqlite3 https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L63 When you say Percona I assume your mean the datasource for the metrics? Please correct me if I'm wrong :)

**Comment by pawellesniewski** [comment]
Nope, our Grafana installation is working on Percona (not sqlite). We use Graphite and Zabbix as datasources.

**Comment by torkelo** [comment]
Found the cause for this. 

The dashboard_tag table only had a unique index on dashboard_id & term. But for the search the join is only on dashboard_id. 

Added an index on dashboard_id in the dashboard_tag table and the search time for 4K dashboard went from 1.2 seconds to 11ms

**Comment by HariSekhon** [comment]
We're using postgres here and also finding listing Grafana dashboards is a very slow operation, it typically takes 1-2 secs for 1040 dashboards.

I checked the dashboard_tag table but it already has an index on the dashboard_id field.

Other than moving dashboards under folders to try to limit the size of the dashboard listing, is there anything else that can be done? In fact, would moving dashboards under folders help or are they all retrieved in one query regardless?

@torkelo How did you track down your performance issue to that table? Query logging and explain plans?

**Comment by torkelo** [comment]
With that many dashboards it's angular that is causing a lot of the slowdown, we did some initial work on moving the dashboard search to react to improve that but needs to be completed.
https://github.com/grafana/grafana/pull/13397

**Comment by HariSekhon** [comment]
Would it help to put everything in folders so they don't all have to be queried / displayed in a huge drop down list?

I suspect nobody even scrolls down that list because it's so long - they almost certainly all use the search function instead, meaning the long listing delay is pointless.

This is how I've observed everybody in my team using Grafana, suffer the listing delay, and then type in to search to get the dashboard they want because scrolling is less impractical.

**Comment by torkelo** [comment]
Yes, is you can organize them into ~30 folders or so it will help

**Comment by HariSekhon** [comment]
I've moved all dashboards not already in a folder under a new folder using the Grafana API and this has immensely sped up the dashboards drop down, thanks!
