### ISSUE TITLE
AppRootPage: show the navigation while loading a plugin

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#58698]
### What is the problem?
https://user-images.githubusercontent.com/9974811/201642406-4d93af5d-eea2-4ae7-a936-70cb97d20d3a.mov

Currently when the user navigates from "Your datasources" to "Connect data", in case the latter is served by the Cloud Onboarding plugin they will experience a delay while the plugin is loaded. Unfortunately during the time of loading even the sidebar navigation is removed, which makes the experience a bit clattered.

### Possible solution(s)
- **Keep the sidebar navigation in its place while loading**, and show a nicer loading indicator. (Maybe this is not possible as it is `PluginPage` in the plugin which dictates the page layout and displays the sidebar).
- **Somehow preload plugins** that are serving standalone pages under a section

**Comment by leventebalogh** [comment]
Makes sense, thanks 👍

**Comment by sympatheticmoose** [comment]
nav has changed
