### ISSUE TITLE
Import dashboard dashboard enhancement: Customize span for each graph

### ISSUE THREAD

**Issue by ecbrodie** [grafana/grafana#587]
It appears that, when a Graphite dashboard is imported to Grafana, all graphs will have a span of 6, so that there are up to 2 graphs per row. Is there a way that we can change the span of the imported graphs to a different span? IE, use span 4 so that we can have 3 graphs per row, or span 3 so we can have 4 graphs per row. Ideally, this could be made possible through a button in the Web UI, so that a bulk action is applied to the dashboard and the spans of all graphs in the Grafana dashboard are changed? The only other alternative would be to manually edit the JSON of the exported Grafana dashboard and importing the changed JSON back to Grafana.

**Comment by torkelo** [comment]
close for lack of interest
