### ISSUE TITLE
Heading is not correct for New Dashboard and Import tab 

### ISSUE THREAD

**Issue by ajinkya-mulay** [grafana/grafana#58701]
**What happened**:
Page Heading is not correct in Grafana 9.2.2 for New Dashboard and Import page.
Please find the below screenshot 
![image](https://user-images.githubusercontent.com/95682162/201664462-6254ab4b-8f01-40c8-af03-8e3d244d252a.png)
![image](https://user-images.githubusercontent.com/95682162/201664483-c0b4be21-a5a9-422a-a5ca-7b365f449343.png)

**What you expected to happen**:
Import and dashboard page should be correct 
**How to reproduce it (as minimally and precisely as possible)**:
Login and check tabs Import and New Dashboard 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.2 OSS
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome 
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @ajinkya-mulay 

this appears fixed on main (9.3.0). Also, version 9.2.4 uses our new and much-anticipated new navigation layout. It is also fixed using that new feature. Please try upgrading to 9.2.4 ❤️

**Comment by ajinkya-mulay** [comment]
Can you give me PR where this issue is fixed? can we backport this PR in 9.2.2?
