### ISSUE TITLE
App Title is not consistent 

### ISSUE THREAD

**Issue by ajinkya-mulay** [grafana/grafana#58700]
**What happened**:
App Title shown in chrome is not correct in multiple places
1. Home Page -  home page title has multiple dashboard words. Current Name : Home - Dashboards - Dashboards - Grafana
![image](https://user-images.githubusercontent.com/95682162/201653322-99ca2eea-fdf7-4db2-91ca-94707818ebd6.png)
2. Search Page shows same title as home dashboard Current Name:  Home - Dashboards - Dashboards - Grafana
![image](https://user-images.githubusercontent.com/95682162/201654768-338f7049-c76c-4c5c-a8fc-d6660ef13ff4.png)

**What you expected to happen**:
Name should be corrects 
1. Home Dashboard Expected name: Home - Dashboards - Grafana 
2. Search Page Expected Name: Search - Dashboards - Grafana 

**How to reproduce it (as minimally and precisely as possible)**:
Just login and check these name 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.2 OSS
- Data source type & version:
- OS Grafana is installed on: Windows 
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@ashharrison90 can you take a look at this? 

I think we can improve the logic a bit https://github.com/grafana/grafana/blob/main/public/app/core/components/Page/usePageTitle.ts  for pages like home & Dashboards home

**Comment by ashharrison90** [comment]
@torkelo what do you think about just showing the page title and not attempting to show the full hierarchy? struggling to think of a page where that wouldn't work 🤔 some examples:

- Home would be `Home - Grafana`
- Dashboards would be `Dashboards - Grafana`
- Creating a new team would be `New team - Grafana`

**Comment by torkelo** [comment]
@ashharrison90 yea let's do that for now :+1:

**Comment by ashharrison90** [comment]
@ajinkya-mulay we can't merge any fixes into an already released version.
the earliest we could merge it in is the next 9.2.x version, but given we're about to release 9.3.0 we'll aim to release it in that 

hope that makes sense!
