### ISSUE TITLE
Public Dashboards: Impossible to unfold a folded row in the public dashboard.

### ISSUE THREAD

**Issue by Telokis** [grafana/grafana#58702]
**What happened**:
If a row is saved as folded on the real dashboard, the anonymous user will not be able to unfold it on the public dashboard.

**What you expected to happen**:
The row should properly unfold and its contained panels should work.

**How to reproduce it (as minimally and precisely as possible)**:
Simply collapse a row and save your dashboard. The public one will be able to unfold but will get an error with the panels.  
See the following three screenshots below:

<hr>

**The row is folded**
![image](https://user-images.githubusercontent.com/6382729/201667034-4ad935be-23d9-4f71-8311-f86bd43026ae.png)

<hr>

**I get an error when I unfold the row**
![image](https://user-images.githubusercontent.com/6382729/201667072-db7b11fc-7604-4cbb-b703-38c3bed1751a.png)

<hr>

**Here is the error**
![image](https://user-images.githubusercontent.com/6382729/201666968-7cc034a2-1640-48e0-a1d1-0bc9a653ec56.png)

<hr>

**Anything else we need to know?**:
I also get an error if I try to close the tab after unfolding the row. It apparently thinks I've make changes to the dashboard.

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome on Windows 10

**Comment by zuchka** [comment]
Thanks for creating this issue, @Telokis 

reproduced this on `main` using two rows with a testdataDB panel in each one
