### ISSUE TITLE
Combine conf/sample.ini and conf/defaults.ini

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5870]
The files get out of sync sometimes and the difference is not that obvious. 

I think defaults.ini can contain both documentation and samples and default values. If More documentation would be needed it should be moved into the docs instead. 

@torkelo what do you think?

**Comment by torkelo** [comment]
This is how elasticsearch, apache and many do it. That is the config file users should modify has all options commented out so are left to their default value. 

So what should be done (but is tricky with the current ini system) is to transform the defaults.ini file setting the same ini sections in code instead. But that is messy. 

there are multiple levels of configuration

defaults (in defaults.ini), -> override defaults in command line -> read user config and override defaults -> read command line overides -> read ENV variable overrides.

The "override defaults in command line" might seem confusing but is needed for proper init script / daemon initialization. Same approach is used in Elasticsearch config system (to override default in command line, but those can be overriden in user config file)
