### ISSUE TITLE
Feature request: Manually refresh (failed) graph(s)

### ISSUE THREAD

**Issue by nickcarenza** [grafana/grafana#5871]
Sometimes a single graph will fail to load on my dashboard and I can't seem to find a way to refresh just that one. Maybe instead, or additionally, a button to retry all failed requests.

**Comment by bergquist** [comment]
I'm sorry but I don't think that problems qualifies for a button. Perhaps retrying the request once and see if it succeed.

**Comment by nickcarenza** [comment]
On a large dashboard with many graphs though, I suspect it might be _because_ of the number of simultaneous requests that certain ones are failing. If I reduce the time range on the dashboard they usually all load.
