### ISSUE TITLE
api/folders/:uid is always returning empty `url` property

### ISSUE THREAD

**Issue by lpskdl** [grafana/grafana#58710]
**What happened**:
When navigating inside a folder(dashboards). It always redirect to the home page. Upon checking the response of `api/folders/:uid`. I noticed that the `url` value is always empty in the response regardless of whatever folder uid is sent to the api.

**What you expected to happen**:
- `url` is used by the frontend to decided which route the user will navigate to.

**How to reproduce it (as minimally and precisely as possible)**:
- Login to grafana
- Browse Dashboard
- Click go to folder(next to a folder name)

https://user-images.githubusercontent.com/108552997/201708755-2e30d4ed-48b4-49b8-ad41-426d231ce84b.mov

**Anything else we need to know?**:
- This can also be replicated using the postman 

**Environment**:
- Grafana version: Latest main (9.3.0-pre)

**Comment by MTLChrisLEE** [comment]
Hi @lpskdl ,

I don't think this issue is reproducible on 9.4.0-pre

[Screencast from 02-19-2023 04:21:03 PM.webm](https://user-images.githubusercontent.com/25248744/219975958-9d3fa24c-5010-4973-9d84-2369d59caea5.webm)
