### ISSUE TITLE
GLDS-Alerts; EPIC

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#58727]
The current Grafana Alerts and InfoBox are inconsistently used across the product, present long messages poorly and generally don't have the required documentation to ensure proper, consistent implementation.

```[tasklist]
### Tasks
- [x] #58751
- [x] #58752
- [x] #58753
- [ ] https://github.com/grafana/grafana/issues/63282
```

Resources/References:
[Figma alert explorations](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Grafana-design-system---Dark-theme?node-id=8444%3A13497)

**Comment by natydej** [comment]
**Update:** I've spoken with Ali and Bruno about Notification Banners, and have more information on how to approach this. Ali set up a **Grafana Pro** account for me to identify all the use cases for these Notification Banners, and I will also catalog those in the **New Navigation** account and the **Free** account.

**Comment by natydej** [comment]
I have a call with SammyJ, who share his user experience about it, and also gave me some good references about how this [website](https://www.registertovote.service.gov.uk/register-to-vote/date-of-birth) has some great user experience and usability. I will attached the examples on this [doc](https://docs.google.com/document/d/1W-MeWyTOeiZrn-nWK_JVJASAIVLu8MNtrOkis2Cwl3g/edit#).

**Comment by staton-hyse11** [comment]
- [ ] Alerts; Storybook needs updated to reflect recent design work

**Comment by staton-hyse11** [comment]
This epic won't finished until we have storybook updated
