### ISSUE TITLE
Offline plugin installation

### ISSUE THREAD

**Issue by farrokhi** [grafana/grafana#5873]
- What did you do? 
  Install a plugin using grafana-cli
- What was the expected result? 
  It requires internet connection, but the machine has no internet connection
- What happened instead?
  It is common in monitoring systems to be isolated from public internet. In such cases it would be great to be able to install a plugin using a local archive (e.g. .zip file or a local directory)

**Comment by bergquist** [comment]
Offline installations guide should be added to grafana.net/org and the cli when not able to connect to internet.

**Comment by bbalet** [comment]
Hi @bergquist @torkelo, Could you provide some hints? Is it possible to install a plugin manually or to use the cli offline? What are the steps of this kind of install?

**Comment by torkelo** [comment]
you can do it on a computer that has internet then copy the `/var/lib/grafana/plugins` dir the target computer

**Comment by schavalmane** [comment]
if installation is via cli then we should get option to download.

**Comment by discoduck2x** [comment]
@torkelo @bergquist 
do you mean we have to have an internet facing grafana just to be able to download grafana.net plugins via grafana-cli ? i think many are having their grafana instances deep buried behind fw´s and therefor would need to be able to dowload manually from workstation with internet and then transfer manually

**Comment by torkelo** [comment]
@discoduck2x no, it does not need to be internet facing. grafana-cli needs to have access to internet for it to download plugins. If the server you want to install plugins on cannot access the internet then you can install grafana on a computer that can, install using grafana-cli, then copy the plugins from plugins folder over the the server that does not have any access to the outside

**Comment by discoduck2x** [comment]
@torkelo , ok i understand that as a current workaround but why not provide a link on the grafana.net plugin page with a download url (same as grafana-cli uses?) , if im moving around working from different hosts  like - stationary desktop, laptop, vdi etc, , then this means i right now have to have local grafana installed on each in order to download via cli....or setup a grafana for "plugin downloads only"

thanks for always beeing so fast with responses - you and your team rox ! ::

**Comment by Yaiba782** [comment]
+1 This would be very useful for offline servers

**Comment by DanSHenry** [comment]
+1 it makes more sense to just make the download link available especially if installation is as simple as copy-paste into plugins directory. Downloading from the site then ftp to my server is a lot easier than install grafana again on another computer.

**Comment by olliewalsh** [comment]
Pretty easy to figure out the download url by looking at the source, but it would be nicer to have a direct link in the plugin page.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9299
