### ISSUE TITLE
GLDS- Alerts; pattern

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#58753]

**Comment by natydej** [comment]
Design the pattern as component [here](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/branch/q0pashrLHVo4EMZn4GncYo/Grafana-design-system---Dark-theme?node-id=8444%3A13497&t=RfNz9RLabRNyY0vc-0), need a review first and some help on how to structure all these findings on our product.
