### ISSUE TITLE
total metric in Legend Format

### ISSUE THREAD

**Issue by yosefy** [grafana/grafana#5876]
I'm submitting a 

- [v ] Feature request
  

using grafana
3.1
on prometheus
ubuntu14.04
===========

hi
the problem 
i have metric for free memory, for example , but i d don't know out of how much total
for total i have usualy another metric in prometheus

and i don't want graphs for total as it almost never changes and makes visual noise

so what coud be very useful is ti put in "Legend Format", something like
Free Memory out of (node_memory_MemTotal{instance=~"$hostname"})

for now what i did is created variable in templating
like so:
query_result(node_memory_MemTotal{instance=~"$host"} / 1024 / 1024 / 1024)
with regexp:
/^.* ([0-9|\.]{5})[0-9].* [0-9|*]*$/   (which gives the metric value)

and then use it in Legend Format.
BUT when the $host  is multi-value,it doesn't work

same goes for free disk space, free swap, free apache workers, free anything with static total

may be there is a better way? what do you say?
thanks

**Comment by yosefy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12940013/17835828/a41ac24e-6786-11e6-8b57-2baafc3abed9.png)

then i may remove two of four lines on graph

thanks
(trying to be clear)

**Comment by bergquist** [comment]
Legends should only describe the series returned by the TSDB. If you want to give current values from another query I suggest you add a single stat panel next to the graph panel. 
![image](https://cloud.githubusercontent.com/assets/618863/17845341/7ba63cb0-6841-11e6-9654-aaf1d3b47406.png) Those panels can be found in [https://grafana.net/dashboards/22](https://grafana.net/dashboards/22).

You could also hide one line by setting linefill and fillwidth to 0.
![image](https://cloud.githubusercontent.com/assets/618863/17845307/3b382f62-6841-11e6-98f7-163f6dd8be00.png)

Does this help?

**Comment by yosefy** [comment]
its t work for multiple choice situation

actually i have succeeded with adding a variable from query
then added it lo legend format

but then again it works for single "server"
may be it could be resolved , then we could have new functionality

![image](https://cloud.githubusercontent.com/assets/12940013/17845844/83b2cd04-684d-11e6-8ee7-a8669e790e96.png)


![image](https://cloud.githubusercontent.com/assets/12940013/17845815/4da93c5c-684d-11e6-9930-d0cf8b43ef9c.png)


and then we get

![image](https://cloud.githubusercontent.com/assets/12940013/17845822/5d23cf08-684d-11e6-9f1c-a998198f32cd.png)

but when i make the $server multiple, it doesnt work

thanks a lot

**Comment by bergquist** [comment]
This is clever usage of the templating in Grafana :)
But not something that we want to encourage. Handling multi serie result in the legend seems messy.

**Comment by yosefy** [comment]
thanks :)

problem with single stat is the same.
with multiple choice

any idea how to handle it?
usecase is
i want to check difference in usage on two servers or 5 may be
then need to see disk free out of total on all of them

thanks

**Comment by yosefy** [comment]
ok i have found workaround with table type of metric it works ok with multi selection :)

![image](https://cloud.githubusercontent.com/assets/12940013/17848481/765dcb54-685c-11e6-91f2-4af394208d0d.png)

thanks
