### ISSUE TITLE
Timeseries: Boolean units not shown on axis

### ISSUE THREAD

**Issue by rtoenniges** [grafana/grafana#58796]
**What happened**:
Boolean units (On/Off, Yes/No) show "NaN" on Axis.
True/False works as expected

Tooltip works fine with all three units.

![image](https://user-images.githubusercontent.com/8208011/202060383-237d4dfe-5238-4642-a9e8-f88537715548.png)

**What you expected to happen**:
The chosen unit should be shown on the axis.

**Environment**:
- Grafana version: v9.30-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: AlmaLinux 8
- User OS & Browser: Chrome

**Comment by zuchka** [comment]
Thanks for creating this issue, @rtoenniges 

can you confirm that you are using the Time Series panel and not the Graph (old) panel?

**Comment by rtoenniges** [comment]
Hi zuchka,

confirmed ;-)

**Comment by AdityaNaresh** [comment]
both  (On/Off, Yes/No) shows NaN 
( True, False ) still works as expected

**Comment by wintersteiger** [comment]
Same here. Used to work fine, but after upgrading to 9.3.2 On/Off and Yes/No don't work anymore.
