### ISSUE TITLE
Can we See the log data in grafana dash board

### ISSUE THREAD

**Issue by abhilash07** [grafana/grafana#5879]
hi we are planning to view the kibana log data from grafana metrics dashboard. I mean in our environment we have central database Influxdb, we get the metrics data influxdb and make graph on graphana dashboard. If any thing goes wrong i nmetrics can user can see the log details from grafana

**Comment by bergquist** [comment]
You can find info about how Grafana logs data in the docs http://docs.grafana.org/installation/configuration/#log
