### ISSUE TITLE
Product DNA doc for Scenes

### ISSUE THREAD

**Issue by thanos-karachalios** [grafana/grafana#58792]

**Comment by thanos-karachalios** [comment]
Document link: https://docs.google.com/document/d/1ul5iE6Q-CFhjbu9SOe-6LbsC71hobiSnYkHvdrXq014/edit?usp=sharing by @dprokop

**Comment by thanos-karachalios** [comment]
@dprokop I am closing this for the context we wanted.

**Comment by dprokop** [comment]
@thanos-karachalios - thanks
