### ISSUE TITLE
[Elasticsearch]: Enforce ES index setting, limit requests to specific index

### ISSUE THREAD

**Issue by wleese** [grafana/grafana#5880]
Bug report
- What Grafana version are you using?
  3.1
- What datasource are you using?
  Graphite with Elasticsearch for annotations
- What did you do?
  Created an Elasticsearch datasource for annotations, specifying a specific index to retrieve the data from.
- What was the expected result?
  Grafana users could only see data in that index
- What happened instead?
  Grafana creates an endpoint the user can manipulate in order to access all data on the elasticsearch cluster. This is a security issue in environments that restrict access to parts of their ES dataset.

Endpoint in our case:
https://grafana/api/datasources/proxy/8/_msearch

Post data:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["changelog-2016.08.22"]}
{"fields":["@timestamp","_source"],"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"@environment:test"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1471831950322,"to":1471853550322}}}]}}}},"size":10000}
```

From our perspective this makes the annotations ES datasource useless, because it introduces a security issue.

**Comment by wleese** [comment]
Just a start. Although it doesn't restrict users from accessing other indices, it does prevent other malicious behavior such as changing settings, mappings and deleting data.

https://github.com/grafana/grafana/pull/6031

**Comment by wleese** [comment]
New PR with a more extensive approach https://github.com/grafana/grafana/pull/7806

**Comment by marefr** [comment]
#12757 will solve this

**Comment by matyax** [comment]
Can anyone confirm is this one still valid?

**Comment by conet** [comment]
I still see this in 8.5.4 and consider it a security issue, I know it's an older branch but I can't upgrade until https://github.com/grafana/grafana/issues/25469 is fixed.

Steps to reproduce:
1. Copy an elasticsearch datasource frontend request as curl (the on like `/api/datasources/proxy/99/_msearch`)
2. Change the index and/or the query
3. It will run the query

Expected result:
The query on other index patterns that those defined in the datasources should not be allowed.
