### ISSUE TITLE
Navigation: Application files wont load when `GF_HELP_ENABLED=false`

### ISSUE THREAD

**Issue by rphlwnk** [grafana/grafana#58809]
**What happened**:
When help is disabled through **grafana.ini** the UI is not loading with error.

![image](https://user-images.githubusercontent.com/34039879/202147246-bd7b9982-8428-405c-aac9-4d9309357cff.png)

It works when you have a valid **grafana_session** session cookie.

**What you expected to happen**:
UI should load even with no session cookie.

**How to reproduce it (as minimally and precisely as possible)**:
Disable help in **grafana.ini** ([Configure Grafana - Help](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#help))

```
[help]
enabled = false
```

**Anything else we need to know?**:
In the log file (console log) i only can see this line when requesting the page

```
logger=infra.kvstore.sql t=2022-11-15T16:26:08.549870228Z level=debug msg="kvstore value not found" orgId=0 namespace=serviceaccounts key=hideApiKeys
logger=context userId=0 orgId=0 uname= t=2022-11-15T16:26:08.55345748Z level=info msg="Request Completed" method=GET path=/login status=200 remote_addr=172.16.40.167 time_ms=7 duration=7.433125ms size=6004 referer= handler=/login
```

Issue persists with and without reverse proxy

**Environment**:
- Grafana version: grafana/grafana-enterprise:9.2.4
- Data source type & version: no data source, fresh installation
- OS Grafana is installed on: Ubuntu 22.04 LTS as docker image
- User OS & Browser: Windows 10 / MS Edge, Google Chrome, Firefox
- Grafana plugins: none installed
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @rphlwnk 

I can reliably reproduce this on my local machine using the following docker command and building from source on `main`. I believe it has to do with the topNav feature flag because passing that in resolves the issue

this will break:

```
  docker run --rm \
    -e GF_LOG_LEVEL=debug \
    -e GF_LOG.CONSOLE_LEVEL=debug \
    -e GF_HELP_ENABLED=false \
    -p 3000:3000 \
    grafana/grafana:9.2.4
```

this will work:

```
  docker run --rm \
    -e GF_LOG_LEVEL=debug \
    -e GF_LOG.CONSOLE_LEVEL=debug \
    -e GF_HELP_ENABLED=false \
    -e GF_FEATURE_TOGGLES_ENABLE="topnav" \
    -p 3000:3000 \
    grafana/grafana:9.2.4
```
