### ISSUE TITLE
Alerting: Only the first threshold is visible in the query editor graph when using a multi-threshold classic condition

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#58808]
**What happened**:

When configuring an alert with multiple queries, and a classic condition with a threshold on each query, the threshold appears on the Graph correctly only for the first query listed in the condition.

The alert behaves correctly, the only issue is the display of the threshold in the alert page when running the queries.

We expected both thresholds to be displayed.

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/8410871/202145130-e0b329cd-c892-43e7-9054-53ae5ad1a7a1.png)

Note how the Classic Condition thresholds on queries A and B, but only A shows a threshold:
**How to reproduce it (as minimally and precisely as possible)**:

Similarly, if we reverse the order of the classic condition, now only query B shows a threshold:
![image](https://user-images.githubusercontent.com/8410871/202145326-6384ef0a-867b-408a-baeb-afabc2e68629.png)

I expected both to show a threshold.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by konrad147** [comment]
Fixed by https://github.com/grafana/grafana/pull/60046
