### ISSUE TITLE
[InfluxDB] Updating from 8.5.4 to 9.0 and then 9.2.4 causes Data Source to be changed to default Grafana/Random Walk in some panels without user's input.

### ISSUE THREAD

**Issue by jsarnowski96** [grafana/grafana#58804]
**What happened**: After updating Grafana from 8.5.4 to 9.0 and then 9.2.4, some of our dashboards and panels Data Source was changed to default Grafana with Random walk, filling them up with garbage data.

**What you expected to happen**: Above one not happening at all?

**How to reproduce it (as minimally and precisely as possible)**: Update from 8.5.4 to 9.0, then to 9.2.4

**Anything else we need to know?**: It seem like the problem occurs only when certain panel uses InfluxDB Data Source - neither Postgres nor Elasticsearch were affected. I had to perform direct DB restore in order to revert breaking changes.

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Original -InfluxDB, current one (switched without my knowledge) - Grafana
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
Thanks for creating this issue, @jsarnowski96 

question: was your influx instance, pre-migration selected as the default datasource inside the DS configuration?

![CleanShot 2022-11-16 at 13 26 21@2x](https://user-images.githubusercontent.com/37156449/202316825-dbcd4553-5f96-4139-9c90-7183c73ac405.png)

If so, can you try to toggle that off and then attempt your updates?

**Comment by jsarnowski96** [comment]
> Thanks for creating this issue, @jsarnowski96
> 
> question: was your influx instance, pre-migration selected as the default datasource inside the DS configuration?
> 
> ![CleanShot 2022-11-16 at 13 26 21@2x](https://user-images.githubusercontent.com/37156449/202316825-dbcd4553-5f96-4139-9c90-7183c73ac405.png)
> 
> If so, can you try to toggle that off and then attempt your updates?

yes, that is correct. I was digging in v9 issue list and found part covering default Data Source. but correct me if I'm wrong - shouldn't Grafana default to DS used by specific dashboard/panel? There was no mention of Grafana's built-in Data Source which would feed panels with dummy data.

In the end, cherry-picking of `dashboard` table from DB dump prove helpful. in the meantime another issue emerged from this apparently faulty update procedure, but it's another story.

**Comment by jsarnowski96** [comment]
I believe that everything essentialy started from this:
![Przechwytywanie](https://user-images.githubusercontent.com/20375860/202418280-425fec8a-a5ba-4375-b3a7-8c9418d583b5.PNG)

**Comment by jsarnowski96** [comment]
and here's the difference in selected table (dashboard):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20375860/202419619-7ad806d0-c91f-49c1-8082-699d51bb09b4.png)

So there's definitely something wrong with initial DB migration job launched on service's startup in newest version.

**Comment by jsarnowski96** [comment]
@zuchka I've discovered another strange thing in regards to the `default` flag in Data Source. Tested it on all related Grafana version (8.5.14, 9.0, 9.2.4).

If I toggle off the `default` flag in InfluxDB DS, all related dashboards break the same way as they would after updating Grafana to 9+, meaning panel data source will switch to `-- Grafana --` and query type to `Random Walk`. but in that specific version it can be easily fixed by toggling `default` flag on again - previous configuration in panels will  be magically restored.

Unfortunately it won't work this way on 9+ versions. I tested every possible scenario and the only way to fix it is to restore `dashboard` table from pre-v9 update, but it will cause another problems along the way.

I've spent last two work days trying to fix this mess but it seem like Grafana in its current state is impossible to upgrade, at least in our environment. I've seen several somewhat related issues reported previously on Issues tab, some of them dating back to July 2021.

**Comment by tolzhabayev** [comment]
not sure backend platform is the right squad @grafana/dashboards-squad ?

**Comment by dprokop** [comment]
@jsarnowski96 - any chance you could share the pre-migration dashboard json with us?

**Comment by jsarnowski96** [comment]
@dprokop hi, unfortunately it was quiet a long time ago and I don't have that config at hand anymore. though the issue was the same as reported in [here](https://github.com/grafana/grafana/issues/63484)

**Comment by dprokop** [comment]
@jsarnowski96 thans for responding, and really sorry we kept you waiting so long. I'm currently investigating #63484 and hopefully, we will address this issue soon.

**Comment by jsarnowski96** [comment]
@dprokop appreciate it :)

**Comment by dprokop** [comment]
@jsarnowski96 please have a look at the workaround described in https://github.com/grafana/grafana/issues/63484. Would appreciate if you could let us know if it helps your case anyhow.

**Comment by jsarnowski96** [comment]
@dprokop I have already tried using `schemaVersion` 32 back when I created that issue, however it didn't work for me. Apart from being unable to modify existing dashboards, creating new one from scratch was also impossible after upgrading to v9 major (detailed symptoms available above).

**Comment by jsarnowski96** [comment]
Though I checked a moment ago for current `schemaVersion` and it's now **36** (don't know how it changed). so might be worth a try, I'm just gonna have to clone a machine with that particular grafana instance.

**Comment by jsarnowski96** [comment]
it's gonna be fun changing ~50 dashboard JSONs in one go

**Comment by axelavargas** [comment]
Hello @jsarnowski96 👋🏾 , I'm going to close this issue as we've provided a workaround. I agree that it may not be the most ideal solution, but unfortunately, this is the best we can do under the current circumstances. If the workaround doesn't work for you, please don't hesitate to let us know and we can re-open the issue.

Thank you once again for your patience and for bringing this issue to our attention. 🙏🏾
