### ISSUE TITLE
PhantomRenderer::renderToPng renders image of login screen

### ISSUE THREAD

**Issue by pkolmann** [grafana/grafana#5881]
I have Grafana 3.1.1-1470047149 (dpkg install, on a Debian Jessie box) behind an Apache Proxy:

                ProxyPreserveHost On
                ProxyPass /grafana/ http://localhost:3000/
                ProxyPassReverse /grafana/ http://localhost:3000/

I want to export a panel to PNG and got so far, that the renderer is working behind the Apache Proxy:

t=2016-08-22T11:19:27+0200 lvl=info msg="PhantomRenderer::renderToPng url [https://www.DOMAIN.at/grafana/dashboard-solo/db/wetter?from=1471682902877&to=1471855702877&panelId=2&width=1000&height=500]"
t=2016-08-22T11:19:27+0200 lvl=info msg="Request Completed" logger=context **userId=0 orgId=0** uname= method=GET path=/dashboard-solo/db/wetter status=302 remote_addr=2001::123 time_ns=0 size=37

I get a properly rendered PNG of the Login-screen. It seems that the phantomjs somehow can't use the session it is called from. In the Second Log-row I see **userId=0 orgId=0** which sounds to me like no user is logged in.

**Comment by torkelo** [comment]
ProxyPassReverse should not be needed, remove that and instead set root_url property in grafana.ini to something like `http://my.apache.server/grafana`   (So the url of your apache server and the url you want to use in browser)

**Comment by pkolmann** [comment]
Thanks for the quick reply.

root_url = https://www.DOMAIN.at/grafana/ is set. I have removed the ProxyPassReverse but it didn't help.

Still the same issue.

**Comment by pkolmann** [comment]
For reference:

I changed now Grafana to a subdomain, removed the root_url setting and I am proxying now the whole domain to grafana. Now the png rendering works.
