### ISSUE TITLE
Make it possible to set the default maxDataPoints for a graphite source

### ISSUE THREAD

**Issue by erez-rabih** [grafana/grafana#5882]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
2.6.0
- What datasource are you using?
graphite
- What OS are you running grafana on?
linux
- What did you do?
try to graph a metric
- What was the expected result?
all datapoints from graphite should be shown
- What happened instead?
datapoints were consolidated

**Comment by torkelo** [comment]
the default is one point per pixel, why do you need more?

**Comment by erez-rabih** [comment]
Right now I my Graphite retention is set to 5 seconds for 6 hours
That means that if I set the timerange to last 6 hours I have 4320 data points
Graphite now consolidates the data with an average function by default and my metric represents a counter which I'd like to sum. That applies to every counter metric in my system meaning I will have to override each of the individually.
The real problem here is that graphite does not allow to set consolidation function by metric name, the way it allows to set aggregation method in storage-aggregation.conf.
All I have left to do is to treat every metric individually and that's very repetitive and not maintainable.
If I could set a default maxDataPoints at least I could avoid consolidation in the first place. I'd pay with performance but I make this decision with awareness to the implications.

**Comment by torkelo** [comment]
You can set consolidation function easily using consolidateBy query functiom

**Comment by torkelo** [comment]
If you disable maxDataPoints for 5s data, you would hang your browser for time ranges more than a day or so

**Comment by erez-rabih** [comment]
your last comment is actually wrong since graphite has its own aggregation so for a day it stores a point every 1 minute meaning I will have only 1440
It is the higher resolution timeranges which makes graphite display wrong data.

**Comment by torkelo** [comment]
Yes, my last comment depends in your aggregation schema :) but still, graphite has simple way to specify consolidation function in the query :)

**Comment by erez-rabih** [comment]
@torkelo:

Graphite has aggregation rules configuration for some reason - so you won't need to define aggregation function per metric.

Currently with the way Grafana works with maxDataPoint you're asking me to do exactly that - define an aggregation (consolidation) rule for each metric individually.

I have thousands of metrics - does it make sense to treat each and every one of them?

Bottom line is that as a user not having the ability to customize this setting is really making my life harder. I'd be very glad if we could open this for a broader discussion or some kind of vote because I sincerely believe it would make Grafana user friendlier.

**Comment by torkelo** [comment]
@erez-rabih yes, graphite has aggregation rules config for ingestion, sadly these are not used when doing runtime aggregation in queries. 

But consolidateBy solves that very well, because you need to do it per query as the runtime consolidation will have to change depending on what metric you use and what functions you have. Are you applying scaleToSeconds, then the default avg consolidation works fine, if you are looking at a max metric (for a timer), then add a consolidateBy(max), if you want accurate sums, use consolidateBy(sum) in the query. 

If you want to the default consolidation function to use the metric aggregation rules, then open an ticket with the graphite project (but that would be tricky, and a cause some confusion when querying I feel)
