### ISSUE TITLE
Bar Chart: 'Color by field' not updating when underlying data changes

### ISSUE THREAD

**Issue by tremsy** [grafana/grafana#58836]
# Scenario 1
This bug report is primarily related to the _Color By Field_ feature which was originally implemented under PR #43257. I am using a _Bar Chart_ panel to display production throughput over time, as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/30629146/202194999-3135e752-a9d9-4da6-8ba0-2a95374bae18.png)

In this example, I have imposed a threshold of 84. I am using a dashboard variable in my query to allow the user to select various pieces of equipment. The problem I am encountering occurs when the user selects a different piece of equipment. An example of this output is shown below. Notice how the values change for each bar, but the colors are not updated. In this case, the 92 should be green, and all others should be red.

![image](https://user-images.githubusercontent.com/30629146/202194974-ef12ed32-d97d-448d-b584-334755d00f24.png)

# Scenario 2
In another example, I do not change the equipment variable, but rather observe the chart over time. I have set an auto-refresh interval of 30 seconds. In this example, I have imposed a threshold of 12. Notice that the bar on the right will increase in value over time. In this first screenshot, the value for 10:00 is 11, so it is correctly colored red.

![image](https://user-images.githubusercontent.com/30629146/202203348-884c6f0c-50e9-4b9a-946e-963a11b7a6f8.png)

Once this value increases to 13, it remains red. I would expect this to automatically turn green when exceeding the threshold value.

![image](https://user-images.githubusercontent.com/30629146/202203375-f7b2dc43-6c12-4e80-838f-35d000e5880a.png)

# Other Observations
- Refreshing the page for both of these cases _will_ correct the bar coloring in both of these scenarios
- Pressing the _refresh_ button in Grafana _will not_ correct the bar coloring in either of these scenarios
- Changing the threshold value in the _Edit Panel_ view _will_ update the bar coloring

# Summary
There seems to be an issue with when the color updates get triggered. Ideally, these colors would get updated whenever the underlying data changes. The underlying data may change when:
- A dashboard variable changes, causing the data to change
- The dashboard is refreshed, either manually or on some fixed interval

# Data Format
The shape of the data being used to populate this chart is shown below:

![image](https://user-images.githubusercontent.com/30629146/202207789-d63dc3cd-d599-4fed-8b9c-8d5bf0af2a8d.png)

# Related PRs
Below are some PRs that may be related to this issue:
- #43257
- #53920
- #58285
- #58580

# Environment
- Grafana version: 8.4.3
- Data source type & version: Prometheus 2.33.5
- OS Grafana is installed on: Windows Server 2019 Standard 64-bit
- User OS & Browser: Windows 10 Enterprise 64-bit / Google Chrome 107.0.5304.107

**Comment by tremsy** [comment]
After updating to the latest version of Grafana (9.2.4), this issue appears to have been resolved

**Comment by amaresh0612** [comment]
This issue is still not resolved in Grafana 9.3.6 But admins keep avoiding the query

**Comment by alsiberij** [comment]
Grafana v10.2.2 (Dockered)
Issue still persists

**Comment by torkelo** [comment]
Tried to replicate on 10.2 but cannot

**Comment by alsiberij** [comment]
### Environment
Grafana v10.2.2 (Dockered)
Data source: Clickhouse 23.3.1.2823
Data source plugin: Clickhouse 3.3.0
### Data source
DDL ```
create table test2
(
    timestamp DateTime
) engine = MergeTree primary key timestamp

**Comment by alsiberij** [comment]
# Environment
Grafana v10.2.2 (Dockered)
Data source: Clickhouse 23.3.1.2823 (Dockered)
Data source plugin: Clickhouse 3.3.0
### Data source
DDL
```
create table test (
    timestamp DateTime
) engine = MergeTree primary key timestamp;
```
Data: 
Any data that have an explicit peak, for example
```
2023-12-17 13:00:00
2023-12-17 11:00:00
2023-12-17 11:00:00
2023-12-17 10:00:00
2023-12-17 10:00:00
2023-12-17 10:00:00
2023-12-17 10:00:00
2023-12-17 10:00:00
2023-12-17 10:00:00
2023-12-17 09:00:00
2023-12-16 11:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 13:00:00
2023-12-01 11:00:00
2023-12-01 11:00:00
2023-12-01 11:00:00
2023-12-01 10:00:00
2023-12-01 10:00:00
```
### Grafana
Panel:
```
{
  "datasource": {
    "type": "grafana-clickhouse-datasource",
    "uid": "ff8870bc-47b4-4029-ba9f-bf83bbdfaceb"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 1,
        "fillOpacity": 100,
        "gradientMode": "opacity",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "axisBorderShow": false,
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "continuous-RdYlGr"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "unit": "locale"
    },
    "overrides": []
  },
  "gridPos": {
    "h": 14,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "options": {
    "orientation": "auto",
    "xTickLabelRotation": 0,
    "xTickLabelSpacing": 0,
    "showValue": "auto",
    "stacking": "none",
    "groupWidth": 0.5,
    "barWidth": 1,
    "barRadius": 0,
    "fullHighlight": false,
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": false,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "colorByField": "c",
    "xField": "h"
  },
  "targets": [
    {
      "datasource": {
        "type": "grafana-clickhouse-datasource",
        "uid": "ff8870bc-47b4-4029-ba9f-bf83bbdfaceb"
      },
      "format": 1,
      "meta": {
        "builderOptions": {
          "fields": [],
          "limit": 100,
          "mode": "list"
        }
      },
      "queryType": "sql",
      "rawSql": "SELECT toHour(timestamp) AS h, count() AS c\r\nFROM test\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY h\r\nORDER BY h",
      "refId": "A",
      "selectedFormat": 4
    }
  ],
  "title": "Data",
  "type": "barchart"
}
```
# Steps to reproduce
1. Select a time range that contains all data including peak
![image](https://github.com/grafana/grafana/assets/70861822/33293479-b806-401b-933c-8cabf6f7836d)
2. Select a time range that does not contain most peak data
![image](https://github.com/grafana/grafana/assets/70861822/b1ccf18b-a009-4942-89e8-5d5158e88925)
Colors remain the same as in the first graph, even if you click grafana refresh button. I expect it to change
3. Refresh page
![image](https://github.com/grafana/grafana/assets/70861822/5a010082-a351-409c-a60a-c79c9e55273b)
Colors are fixed. 
_I expect that peak(6) would have green color but anyway it is better than everything is red_
By the way, reverse step is also broken. If now we select full time range again, colors will not be correct until page refresh.
After selecting full time range again:
![image](https://github.com/grafana/grafana/assets/70861822/948ea7a1-6acb-4e3c-980e-bdfeae5b5bfd)
And after page refresh:
![image](https://github.com/grafana/grafana/assets/70861822/0306cb35-a892-4515-b256-80ecc049ed3d)

**Comment by torkelo** [comment]
the data is a bit strange, not seeing the fields you normally have in bar chart (name + value fields)

**Comment by torkelo** [comment]
The data I tested with looked like this, two value fields, set color by to value2. If I change values of value2 the colors change correctly.

![image](https://github.com/grafana/grafana/assets/10999/9b31f3b6-4613-4389-9afe-18ae6e6c5ef3)

**Comment by alsiberij** [comment]
> the data is a bit strange, not seeing the fields you normally have in bar chart (name + value fields)

Table view looks like this. Field "h" is X axis and acts like name for bar, and field "c" is a value for this bar. As you can see, color by field "c" is set.
![image](https://github.com/grafana/grafana/assets/70861822/c1ac2498-eaf6-42bc-ae3e-dbf21e46b486)
![image](https://github.com/grafana/grafana/assets/70861822/c1eecb5f-9c59-49a9-a6a2-0b525b7f691e)
