### ISSUE TITLE
ElasticSearch “Auto time interval” issues

### ISSUE THREAD

**Issue by neuronring** [grafana/grafana#5884]
Bug Report

- What Grafana version are you using?
3.0

- What datasource are you using?
Elastic Search

- What OS are you running grafana on?
Linux 2.6.32-504.30.3.el6.x86_64

- What did you do?
created an Elasticsearch metrics with Auto time interval option.

- What was the expected result?
The graph should automatically adjust the lines in the graph based on selected time graph.

- What happened instead?
The lines overlapped on each other and shows incorrect values in Y-Axis when Auto interval options is chosen in the metrics.
It works fine when when Manual interval option is chosen such as 1d, 1h, 20m etc.,

![grafana_issue_2](https://cloud.githubusercontent.com/assets/20306104/17868614/2fe98654-6875-11e6-852a-d33befdf645d.JPG)
![grafana_issue_1](https://cloud.githubusercontent.com/assets/20306104/17868615/2ffcc3d6-6875-11e6-88ef-622364cf875d.JPG)

I am using elasticsearch as my datasource in Grafana 3.0 which works great.  When  I group my results by @timestamp field and TimeRange=Auto.. it really messes up the graph. It shows proper line/bar trends only when i choose minimum 6 months period view. If i select 1 week or 1 month view it shows numerous  tiny lines running on each other with incorrect counts on Y axis.

(The First two pictures attached shows the incorrect messy bars with Auto Interval option )

So i have to manually select the Time interval as "1d", "1h" and so on.. which would produce nice charts.. i tried lot of options and couldn't fix it.. In Kibana this feature works great.. The Visualizations auto adjusts the graphs based on time range selection.

(The last two pictures attached shows the perfect graph when i chose maual "1d" or "1h"  Interval option )
![grafana_issue_4](https://cloud.githubusercontent.com/assets/20306104/17868969/c27d7e5c-6876-11e6-81f5-4377927b1e9a.JPG)
![grafana_issue_3](https://cloud.githubusercontent.com/assets/20306104/17868970/c2867610-6876-11e6-9cc5-2237e7cdde04.JPG)

Is this a bug in Grafana or Am i missing something? Please help !!

**Comment by torkelo** [comment]
the bar width is determined by the number of buckets you have (group by time interval), this by default 1 data point per pixel (for auto interval), you can set min doc count to 1 if you do not want null buckets. Or use an interval template variable and specify the number of buckets (and then use that interval in the interval property you ES query). 

You can also set a min group by time interval by specifying `>10m` for example (in the group by time interval below your queries) to stop the auto interval to become to low

**Comment by neuronring** [comment]
I tried both options.. it is totally changing the Y-Axis value. It changes the actual count,, As i mentioned,  I have been trying most of the available options which i am aware of.  I wish i could share my graph here.,

**Comment by torkelo** [comment]
Of course it changes the year axis, your metric is doc count, when you increase time buckets (group by time interval) the count for each data points will increase
