### ISSUE TITLE
Loki: add tracking for Datasource settings explore clicks

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#58870]
I think there is an assumption here - that users will Explore their data after they have configured the data. I think this is something we should ""explore"" :) a bit

_Originally posted by @mary-sitzenstatter in https://github.com/grafana/grafana/issues/57731#issuecomment-1317240344_

**Comment by matyax** [comment]
@ivanahuckova what do you think?

**Comment by ivanahuckova** [comment]
This would be general feature tracking for every `Explore` button click, not just the Loki one. So I would add more context and then check with plugins platform team, or team working on config page if they would like to add it.

**Comment by matyax** [comment]
Looking back at the original comment, I think this is not the approach to answer that. Our intention from the discussion in G10 Getting Started with Loki was to actually get users to use this button and go to explore.
