### ISSUE TITLE
Send Custom Parameter From Grafana to Elasticsearch

### ISSUE THREAD

**Issue by karthikeyan95** [grafana/grafana#5887]
* **I'm submitting a ...**
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I'm currently using Grafana 3.1 with Elasticsearch 2.2 as data-source.

I have a scenario as below
1.I have a empty index in Elasticsearch and i have created a data-source for the index in Grafana
2.When a user tries to add a table with raw document, no column will be displayed. 

and in a working data source, when the entire index has been deleted, grafana shows a error message on the top-left corner.

Is it possible for grafana to store or send request in a particular index in Elasticsearch, which could be read by a Java Elasticsearch Transport Client.

is there any feasibility of achieving this?

**Comment by torkelo** [comment]
no this is not possible, might be with alerting and a custom alert notification handler
