### ISSUE TITLE
Legacy Alerting: Slack alerts do not include image

### ISSUE THREAD

**Issue by vincent-olivert-riera** [grafana/grafana#58872]
## Summary
- I use Grafana 8.5.9.
- I create an alert from a dashboard's panel.
- I send the notifications from that alert to Slack.
- The alert notifications received in Slack do not include the rendered panel image.

---

### I have set a "Notification channel" and checked the "Include image" check box:
![notification-channel](https://user-images.githubusercontent.com/6151586/202329336-eb75c0b5-8833-43e6-9ca9-c16b3c5113f2.png)

### I have set an "Alert" from a panel, and set the "Send to" field to the "Notification channel" above:
![alert-config](https://user-images.githubusercontent.com/6151586/202329453-57e0ee87-2024-4449-a4ca-d8b6f8d2aaf7.png)

### When I receive the alert in Slack, it does not include any image:
![real-alert-without-image](https://user-images.githubusercontent.com/6151586/202329875-b30581d2-106a-4b6c-a5de-001992c85140.png)

### I have tested the "Notification channel" and the received test alert does include an image:
![test-alert-with-image](https://user-images.githubusercontent.com/6151586/202329939-8fd01646-33dc-4a30-8d4e-854ea5cd5a52.png)

### I have also tested that Grafana Image Renderer works:
![share-direct-link-rendered-image](https://user-images.githubusercontent.com/6151586/202330190-10736563-5845-4f57-8277-f67c088667cb.png)
- I open the dropdown menu for that panel (the one that I used for creating the alert).
- I click on "Share" and the "Share panel" modal appears.
- From the "Link" tab I click on "Direct link rendered image".
- The rendered image for that panel successfully opens in a new tab.

### I have also checked that the `alert` in the database has the `dashboard_id` and `panel_id` fields correctly populated:
![database-alert](https://user-images.githubusercontent.com/6151586/202330514-de574f77-040e-41ba-9438-51b3d2a628bb.png)

---

At this point the only thing I can think of is that the integration between the "Notification channel" and Grafana Image Renderer is broken.

**Comment by zuchka** [comment]
Thanks for creating this issue, @vincent-olivert-riera 

> I create an alert from a dashboard's panel.

It looks like you are using the legacy alerting platform, which is deprecated. Have you tried migrating to the new Unified Alerting platform?

**Comment by vincent-olivert-riera** [comment]
> It looks like you are using the legacy alerting platform, which is deprecated. Have you tried migrating to the new Unified Alerting platform?

I don't want to migrate just yet.

"Legacy" does not necessarily mean "broken", so first I would like to confirm if that feature is broken, or if it should to work.

> @[zuchka](https://github.com/zuchka) closed this as [complete](https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted)

I got surprised that this issue was closed so quickly without any further discussion. Can't we leave it open until we determine what's the issue?

If the feature is broken and Grafana does not want to fix it, then we can close the issue, but at least it will be "documented" here that the feature is broken and won't get fixed.
If the feature is supposed to be working, then there must be some issue with my config and other users can help me debugging.

If you close the issue you will remove all the visibility to it and nobody will notice.

**Comment by zuchka** [comment]
hi @vincent-olivert-riera,

sure thing, happy to reopen and pass this along to the alerting folks. The situation with migrations is a bit complex by 8.5.9, so the alerting folks will probably want to know what precise alerting configuration options are in your grafana.ini. Please use [this template to include all the necessary information](https://github.com/grafana/grafana/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md)

here is a bit more explanation for my quick actions

- according to [this warning message, legacy alerting is deprecated ](https://github.com/grafana/grafana/blob/mja%2Ffix-query-name-overflow/public/app/features/alerting/components/DeprecationNotice.tsx#L7-L27)and due to get entirely removed in the next major release (v10, which is in ~7 months).
- The new unified alerting platform has made achieved huge development in terms of embedding images in notifications. [See the docs here](https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/)
- also please see [this lengthy discussion](https://github.com/grafana/grafana/discussions/38030) about how image inclusion was added to the early unified alerting system. It's a pretty deep dive in the status of it all, but I think the newest docs sum up the current state quite nicely

**Comment by zuchka** [comment]
I will also add that [our forum](https://community.grafana.com/) is an excellent place to troubleshoot legacy alerting issues. There are tons of posts about legacy alerting in there.

**Comment by vincent-olivert-riera** [comment]
@zuchka , thanks for re-opening the issue and for all the information you have provided 👍🏻

**Comment by armandgrillet** [comment]
> I don't want to migrate just yet.

Could you please tell us why? Legacy alerting is deprecated and we want to help everyone migrate with confidence.

**Comment by vincent-olivert-riera** [comment]
> > I don't want to migrate just yet.
> 
> Could you please tell us why? Legacy alerting is deprecated and we want to help everyone migrate with confidence.

Because before doing that migration I would like to know if that feature (including the rendered panel image in notifications) is broken for legacy alerting, or on the other hand there is a problem in my config.

If by migrating to the unified alerting platform you guarantee me that the feature (including the rendered panel image in notifications) will work, then I would migrate. However, I've been testing the unified alerting platform and I couldn't get that feature working. In fact, the "Include image" check box has disappeared. See: https://github.com/grafana/grafana/discussions/38030#discussioncomment-4171109
I created alerts from a panel, and I can see the dashboard ID and panel ID fields are populated.
Alerts are being delivered to Slack because I set a contact point and a notification policy, but the alerts do not include a rendered panel image.

**Comment by vincent-olivert-riera** [comment]
@armandgrillet,

I have been testing a little bit more the Unified Alerting Platform after getting involved in the issue I linked in my previous comment, and after reading the documentation further.

Currently, these are all the contents of my `grafana.ini`:

```
    [unified_alerting]
    enabled = true
    
    [alerting]
    enabled = false
    
    [log]
    level = debug
    
    [log.file]
    format = json
    
    [rendering]
    server_url = http://[redacted]/render
    callback_url = http://[redacted]/
    
    [unified_alerting.screenshots]
    capture = true
    
    [external_image_storage]
    provider = s3
    
    [external_image_storage.s3]
    endpoint = [redacted].com
    bucket = grafana
    access_key = [redacted]
    secret_key = [redacted]
```

Alerts are getting fired up and the notifications successfully reach Slack, however, they do not include a rendered panel image. And nothing is being stored in the S3 bucket.

This is how the notification looks like:

![slack-notification](https://user-images.githubusercontent.com/6151586/202946642-c1ce2676-2a73-4710-8d10-9f46ef3e47bc.png)

These are the logs from Grafana at the time the alert is fired up:

![grafana-logs](https://user-images.githubusercontent.com/6151586/202948397-ebe3e02d-2f04-4223-a883-2f2bfe487eeb.png)

And these are the logs from Grafana Image Renderer at the time the alert is fired up:

![grafana-image-renderer-logs](https://user-images.githubusercontent.com/6151586/202949041-f244907e-ae53-4feb-b626-ae095a113864.png)

By the way, I'm testing all of this with Grafana 9.1.1.

Am I doing anything wrong?

**Comment by grobinson-grafana** [comment]
Hi @vincent-olivert-riera! In Grafana 9.2.5 we added additional logging to help users debug this, and the documentation update is just waiting on approval from our docs team. Would it be possible to set the log level to `debug` and show the logs matching `ngalert.image`?

**Comment by vincent-olivert-riera** [comment]
@grobinson-grafana , sure, luckily the log level was already set as `debug`. Here are the logs around the time an alert was fired up:

![Uploading ngalert.image.png…]()

**Comment by grobinson-grafana** [comment]
Looks like image uploading is disabled, I think it just needs the following configuration to work:

```
[unified_alerting.screenshots]
capture = true
upload_external_image_storage = true
```

**Comment by vincent-olivert-riera** [comment]
I have added this line (I already had the other one):

```
upload_external_image_storage = true
```

But Grafana fails to start. The error looks like this:

```
    logger=live t=2022-11-21T09:00:12.104950308Z level=debug msg="GrafanaLive initialization" ha=false
    logger=live.push_http t=2022-11-21T09:00:12.140841086Z level=info msg="Live Push Gateway initialization"
    Failed to start grafana. error: failed to initialize uploading screenshot service: could not find bucket setting for image.uploader.s3
    failed to initialize uploading screenshot service: could not find bucket setting for image.uploader.s3
```

I have the bucket settings in my `grafana.ini`:

```
    [external_image_storage.s3]
    endpoint = redacted
    bucket = grafana
    access_key = redacted
    secret_key = refacted
```

**Comment by grobinson-grafana** [comment]
Looking at the code it looks like Grafana gets the bucket from the `bucket_url` field in the configuration. Would it be possible to add that and see if it works?

**Comment by grobinson-grafana** [comment]
I think `[external_image_storage.s3]` also needs a `region`. If we add that does it work?

**Comment by vincent-olivert-riera** [comment]
> I think `[external_image_storage.s3]` also needs a `region`. If we add that does it work?

@grobinson-grafana , we have made some progress.

After setting the `region` the rendered image for the panel gets successfully uploaded to the bucket (I could actually open it and see it from the bucket). And here are the relevant `ngalert.image` logs:

![image](https://user-images.githubusercontent.com/6151586/203031275-949a4388-0d30-401f-a434-b2aa2afc611f.png)

The logs from Grafana now have a `image_url` field for the Slack notification. See:

```
logger=alerting.notifier.slack t=2022-11-21T10:39:37.361334545Z level=debug msg="sending Slack API request" url=https://slackbot.mydomain.com/webhook/grafana-testing data="{\"username\":\"Grafana\",\"attachments\":[{\"title\":\"[FIRING:1] CPU busy Vincent \",\"title_link\":\"http://localhost:3000/alerting/list\",\"text\":\"**Firing**\\n\\nValue: [ var='B0' metric='host.mydomain.com:9100' labels={instance=host.mydomain.com:9100} value=99.97500000017074 ]\\nLabels:\\n - alertname = CPU busy\\n - grafana_folder = Vincent\\nAnnotations:\\nSource: http://localhost:3000/alerting/grafana/2NPPkTO4z/view?orgId=1\\nSilence: http://localhost:3000/alerting/silence/new?alertmanager=grafana\\u0026matcher=alertname%3DCPU+busy\\u0026matcher=grafana_folder%3DVincent\\nDashboard: http://localhost:3000/d/okgozoO4z?orgId=1\\nPanel: http://localhost:3000/d/okgozoO4z?orgId=1\\u0026viewPanel=2\\n\",\"image_url\":\"https://mybucket.mydomain.com/T1BFyEGTphwUa0rmZtFH.png\",\"fallback\":\"[FIRING:1] CPU busy Vincent \",\"footer\":\"Grafana v9.2.5\",\"footer_icon\":\"https://grafana.com/assets/img/fav32.png\",\"color\":\"#D63232\",\"ts\":1669027177}]}"
```

I have checked that the image referenced in the `img_url` field (`T1BFyEGTphwUa0rmZtFH.png`) is actually the image that has been uploaded to the bucket.

However, the Slack notification does **not** include the image :-(

**Comment by grobinson-grafana** [comment]
Hi! :wave: What are the permissions for the image in the bucket? It must be public readable as images in Slack are proxied via their CDN.

**Comment by vincent-olivert-riera** [comment]
> Hi! wave What are the permissions for the image in the bucket? It must be public readable as images in Slack are proxied via their CDN.

Well, the bucket is hosted inside our own cloud, and the images are readable to anyone inside our VPN.
Do we need those images to be readable to the outside world? What if they include sensitive data?

**Comment by grobinson-grafana** [comment]
> Well, the bucket is hosted inside our own cloud, and the images are readable to anyone inside our VPN. Do we need those images to be readable to the outside world? What if they include sensitive data?

I'm afraid so. The issue is that all image URLs shared on Slack are proxied via their CDN `slack-imgs.com`. If the bucket is not accessible outside the VPN then `slack-imgs.com` won't be able to show it.

> What if they include sensitive data?

I'm looking to add support for Slack's `files.upload` which would allow uploading images to `files.slack.com`. Unlike when using cloud storage, images uploaded to Slack cannot be accessed without being logged into the correct Slack organization.

**Comment by vincent-olivert-riera** [comment]
> > Well, the bucket is hosted inside our own cloud, and the images are readable to anyone inside our VPN. Do we need those images to be readable to the outside world? What if they include sensitive data?
> 
> I'm afraid so. The issue is that all image URLs shared on Slack are proxied via their CDN `slack-imgs.com`. If the bucket is not accessible outside the VPN then `slack-imgs.com` won't be able to show it.

Oh, bad news then :-(
 
> > What if they include sensitive data?
> 
> I'm looking to add support for Slack's `files.upload` which would allow uploading images to `files.slack.com`. Unlike when using cloud storage, images uploaded to Slack cannot be accessed without being logged into the correct Slack organization.

Nice! I would like to help you testing it. Please let me know when that is possible.

**Comment by grobinson-grafana** [comment]
OK. So I looked at the Slack API documentation for `files.upload` and remebered the issue I had the first time I tried to support uploading to Slack.

When using the Slack `files.upload` API it doesn't possible to upload an image with the permissions of a channel / direct message and then link the uploaded file in a subsequent message via it's URL. Instead, if we want the image to have permissions of a channel / direct message then it must be posted to that channel / direct message at the time it is uploaded. This means that either:

1. The image is posted twice: once when uploaded, and a second time when added to the message that contains the notification
2. The image is posted after the notification as a separate message
3. The image is posted as a reply to the original message as a thread

**Comment by grobinson-grafana** [comment]
OK. So I looked at the Slack API documentation for `files.upload` and remembered the issue I had the first time I tried to support uploading to Slack.

When using the Slack `files.upload` API it doesn't possible to upload an image with the permissions of a channel / direct message and then link the uploaded file in a subsequent message via it's URL. Instead, if we want the image to have permissions of a channel / direct message then it must be posted to that channel / direct message at the time it is uploaded. This means that either:

1. The image is posted twice: once when uploaded, and a second time when added to the message that contains the notification
2. The image is posted after the notification as a separate message
3. The image is posted as a reply to the original message as a thread

**Comment by grobinson-grafana** [comment]
OK. So I looked at the Slack API documentation for `files.upload` and remembered the issue I had the first time I tried to support uploading to Slack.

When using the Slack `files.upload` API it doesn't possible to upload an image with the permissions of a channel / direct message and then link the uploaded file in a subsequent message via its URL. Instead, if we want the image to have permissions of a channel / direct message then it must be posted to that channel / direct message at the time it is uploaded. This means that either:

1. The image is posted twice: once when uploaded, and a second time when added to the message that contains the notification
2. The image is posted after the notification as a separate message
3. The image is posted as a reply to the original message as a thread

**Comment by grobinson-grafana** [comment]
OK. So I looked at the Slack API documentation for `files.upload` and remembered the issue I had the first time I tried to support uploading to Slack.

When using the Slack `files.upload` API it doesn't possible to upload an image with the permissions of a channel / direct message and then link the uploaded file in a subsequent message via its URL. Instead, if we want the image to have permissions of a channel / direct message then it must be posted to that channel / direct message at the time it is uploaded. This means that either:

1. The image is posted twice: once when uploaded, and a second time when added to the message that contains the notification
2. The image is posted after the notification as a separate message

The second option is how it works in old alerting.

**Comment by vincent-olivert-riera** [comment]
>     2. The image is posted after the notification as a separate message 
> 
> The second option is how it works in old alerting.

That sounds perfectly fine to me. People coming from the Legacy Alerting Platform would experience the same behavior (not worse) as before, which means there shouldn't be any complaints about it.

**Comment by grobinson-grafana** [comment]
I opened [Alerting: Upload images to Slack via files.upload](https://github.com/grafana/grafana/pull/59163). Please let me know what you think about the changes!

**Comment by vincent-olivert-riera** [comment]
> I opened [Alerting: Upload images to Slack via files.upload](https://github.com/grafana/grafana/pull/59163). Please let me know what you think about the changes!

It looks great :-)

**Comment by Knud3** [comment]
We moved from legacy alerts and this is now working at least as good. Nice work!

Here is my quick notes about transfer, if it helps anyone:

`grafana.ini`:

```INI
[rendering]
server_url = http://grafana-image-renderer:8081/render
callback_url = http://grafana:3000/
renderer_token = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[unified_alerting]
enabled = true

[unified_alerting.screenshots]
capture = true
capture_timeout = 30s
```

`grafana` envs:

```YAML
- name: TZ
  value: "Europe/Helsinki"
```

`grafana-image-renderer` envs:

```YAML
- name: BROWSER_TZ
  value: "Europe/Helsinki"
- name: IGNORE_HTTPS_ERRORS
  value: "true"
- name: AUTH_TOKEN
  value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
- name: RENDERING_ARGS
  value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758"
```

For [Slack app](https://api.slack.com/apps), add OAuth Scope of `chat:write` and `files:write` on `OAuth & Permissions` page. If it had webhooks you can totally disable/delete those.

Copy `Bot User OAuth Token` from `Install App` page to Grafana Slack contact point `Token`. DO NOT fill `Webhook URL` or it wont work. Also add `Recipient` (ex. #grafana-alert).

Remember to include `Dashboard UID` and `Panel ID` as details in alert rule or it wont work.

Screenshot from Slack:
![grafana_slack_alert](https://user-images.githubusercontent.com/62902464/224132593-d00ed65f-1e72-4c99-a707-78162334d12e.png)

**Comment by jcdauchy-moodys** [comment]
> We moved from legacy alerts a week ago and this is now working at least as good. Nice work!
> 
> Here is my quick notes about transfer, if it helps anyone:
> 
> `grafana.ini`:
> 
> ```ini
> [rendering]
> server_url = http://grafana-image-renderer:8081/render
> callback_url = http://grafana:3000/
> renderer_token = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> 
> [unified_alerting]
> enabled = true
> 
> [unified_alerting.screenshots]
> capture = true
> capture_timeout = 30s
> ```
> 
> `grafana` envs:
> 
> ```yaml
> - name: TZ
>   value: "Europe/Helsinki"
> ```
> 
> `grafana-image-renderer` envs:
> 
> ```yaml
> - name: BROWSER_TZ
>   value: "Europe/Helsinki"
> - name: IGNORE_HTTPS_ERRORS
>   value: "true"
> - name: AUTH_TOKEN
>   value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> - name: RENDERING_ARGS
>   value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758"
> ```
> 
> For [Slack app](https://api.slack.com/apps), add OAuth Scope of `chat:write` and `files:write` on `OAuth & Permissions` page. If it had webhooks you can totally disable/delete those.
> 
> Copy `Bot User OAuth Token` from `Install App` page to Grafana Slack contact point `Token`. DO NOT fill `Webhook URL` or it wont work. Also add `Recipient` (ex. #grafana-alert).
> 
> Remember to include `Dashboard UID` and `Panel ID` as details in alert rule or it wont work.
> 
> Screenshot from Slack: ![grafana_slack_alert](https://user-images.githubusercontent.com/62902464/224132593-d00ed65f-1e72-4c99-a707-78162334d12e.png)

@Knud3 If I use webhook URL, the image upload won't work ? (I guess my company is using it :( ) ?

Would you mind sharing your slack template to get those displays. I am struggling with getting notification to work as I want. 
Thanks

**Comment by Knud3** [comment]
If you want/need to use webhook then you need external storage for pictures: https://grafana.com/docs/grafana/latest/alerting/manage-notifications/images-in-notifications/#supported-contact-points

I have made that template based on examples and information found here: https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/

**Comment by vincent-olivert-riera** [comment]
> I opened [Alerting: Upload images to Slack via files.upload](https://github.com/grafana/grafana/pull/59163). Please let me know what you think about the changes!

@grobinson-grafana , hello.

Sorry to bother you again.

After our discussion here (https://github.com/grafana/grafana/issues/58872#issuecomment-1322566515) I thought that the screenshots uploaded to the S3 bucket would automagically appear on the alert notification message.

Now I am testing this with Grafana 9.5.3, which should include the changes from your PR, and I can see the panel screenshots being uploaded successfully to the S3 bucket, however in the alert notification there is no screenshot, or even a link to the screenshot.
There is an `image_url` field in the logs, as we discussed earlier (https://github.com/grafana/grafana/issues/58872#issuecomment-1321868075), but it seems to be completely unused.

One thing to note is that, in the Contact Point, I am using the Slack integration with a Webhook URL. Perhaps that's why is not working automatically?

I am not using any template to customize the notification message, just whatever Grafana gives me by default. Shouldn't the `image_url` be included in the notification message?

**Comment by grobinson-grafana** [comment]
Hi @vincent-olivert-riera,

I tested in both Grafana 10 and 9.5.3:

![Screenshot 2023-06-09 at 11 39 56 am](https://github.com/grafana/grafana/assets/85952834/f419d733-88c8-4ee5-8494-8e8387373904)

![Screenshot 2023-06-09 at 11 41 21 am](https://github.com/grafana/grafana/assets/85952834/517ddb9f-b79f-412a-b114-90313bc0ef7f)

Are the images in S3 accessible over the public Internet or is it a private bucket? If its a private bucket then thumbnails won't work in Slack because Slack uses a CDN `https://slack-imgs.com/`.

**Comment by vincent-olivert-riera** [comment]
Hi @grobinson-grafana ,

first of all, thanks for taking your time to answer my question, really appreciated.

> Are the images in S3 accessible over the public Internet or is it a private bucket?

It is a private bucket.

> If its a private bucket then thumbnails won't work in Slack because Slack uses a CDN `https://slack-imgs.com/`.

So, there is no way to make this work? Since there already is an `image_url` field which contains the correct image URL, I was hoping that image (or at least the URL) to be attached on the notification message, perhaps under the `Annotations` section.

**Comment by grobinson-grafana** [comment]
When Slack cannot show the image (i.e. because of a private bucket) does it fallback to showing the URL, or does it just show nothing?

**Comment by vincent-olivert-riera** [comment]
Hello @grobinson-grafana , thanks again for taking your time to answer my comments.

> Good to know!
> 
> In situations such as this we tend to recommend uploading images to Slack from Grafana instead of using S3. We have a clause about this in the docs:

I feel like we are going in circles. We had the same conversation before a few comments above: https://github.com/grafana/grafana/issues/58872#issuecomment-1322121967

> I can't see any issues with adding the URL as an annotation to the message too though. Would you be able to open a pull request in [grafana/alerting](https://github.com/grafana/alerting) for that?

I am zero familiar with Grafana's code base, I'm afraid.
