### ISSUE TITLE
Localise dashboard Time Range Picker

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#58888]
We would like to localise the time range picker on dashboards to translate all of remaining phrases like "day before yesterday" or "last 5 minutes".

This is a bit of a challenge at the moment because a lot of these phrases in the UI live in grafana/data, which we don't translate (and would like to avoid adding i18next to), and a bunch of these are constructed dynamically, which is difficult to retrofit translations into.

![5yqb5IWAgu](https://user-images.githubusercontent.com/46142/203518006-090107f9-50e2-4c4f-aeb2-708fbe29a880.png)
![aiHkhmPVmC](https://user-images.githubusercontent.com/46142/203517852-03580b1e-3feb-4509-baf9-c445a6597d0d.png)

To translate:
 - Quick ranges list on the right (Last 5 minutes, Last fiscal year, etc)
 - Selected time range in dashboard actions

Not translating:
 - Time inputs (the From or To fields)
 - No additional calendar systems (for now)
 - Time/duration strings, such as `now` or `now-3d`

It is likely this would require a significant refactor of the time range picker.

**Comment by L-M-K-B** [comment]
Localisation would require to rebuild the time picker. That's why we close this issue.
