### ISSUE TITLE
[Bug] Dashboard does not warn on invalid template values

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5888]
* Grafana 3.1.1 commit: a4d2708
* Prometheus
* CentOS

We are starting to use external links into Grafana with template values prefilled. Think CMDB -> monitoring.  There are cases when devices are not (yet) in Prometheus, yet the link is built and Grafana considers it valid.

If a dashboard is loaded with a template value Grafana does not think exists, arguably, it should throw an error. Even if the template is stale and the device exists, making the user aware of this would be helpful.

**Comment by torkelo** [comment]
Not sure I understand `with a template value Grafana does not think exists, `  could you describe it more? What is your Prometheus query and what is the Prometheus response?

**Comment by bergquist** [comment]
The link to grafana contains a set template variable. Ex instance=foobar21 even thou that label is not yet available in Prometheus. Right now there are no indication that the instance cannot be set to foobar21 in Grafana.

I'm not sure how to solve this or if it should be solved. In the meantime I suggest you add a panel to the dashboard indicating if the label is available.

**Comment by torkelo** [comment]
@RichiH please provide the Prometheus response for the query, does it return an error that Grafana does not show?

**Comment by RichiH** [comment]
@torkelo Prometheus does not show an error when it does not return any results:

`{"status":"success","data":{"resultType":"matrix","result":[]}}`

Grafana shares Prometheus' knowledge that there's no data (which could already be visualized as a "no data" overlay for the graphs, but it has extra information over Prometheus: Grafana knows if the template values passed via URL match Grafana's own data on what possible template values are.

**Comment by RichiH** [comment]
@torkelo: @bergquist just ran into a related issue during the live demo at promcon which he could have solved more quickly if this was implemented. I think it makes sense to reopen the issue.

**Comment by torkelo** [comment]
Not sure, do you just want to show a no data label in graphs? I mean prometheus returns no error

**Comment by RichiH** [comment]
I will talk to @bergquist about it for a minute or two later; it might be simpler to sync that way.
