### ISSUE TITLE
PNG rendering does not wait for all panels in dashboard to be ready

### ISSUE THREAD

**Issue by jjaakola** [grafana/grafana#5889]
* **I'm submitting a ...**
- [ X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:

- What Grafana version are you using?
3.1.1

- What datasource are you using?
Influx

- What OS are you running grafana on?
Dockerized Grafana: https://hub.docker.com/r/grafana/grafana/

- What did you do?
I set up a multipanel dashboard and rendered the PNG out of it. E.g. http://www.example.com/render/db/dashboards/boulderdash?from=now-120m&to=now&width=1400&height=900

- What was the expected result?
All panels to have graphed values.

- What happened instead?
Only first panel had graphed values. Others had spinner.

**Comment by torkelo** [comment]
render API only supports single panel rendering right now

**Comment by aayoubi** [comment]
@torkelo It used to work perfectly on multiple panels. What broke this behaviour?

Cheers
