### ISSUE TITLE
GLDS-Graphs legend icon Dev update (Storybook)

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#58903]
Design needs validation/usability testing for accessibility.

Design done and approved. Just needs to be handed off to Dev.

https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Grafana-design-system---Dark-theme?node-id=8444%3A13518

**Comment by staton-hyse11** [comment]
This component needs its code counterpart to be updated to match.

**Comment by staton-hyse11** [comment]
@JoaoSilvaGrafana can you confirm if this was done

**Comment by JoaoSilvaGrafana** [comment]
Is this the component? https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-vizlegend--with-no-values
The storybook story isn't great anyway so might be worth changing that, but not sure what else you mean is missing?

**Comment by staton-hyse11** [comment]
This looks complete to me!
