### ISSUE TITLE
[Bug/Feature?] Connecting line over null values and last known value in legend

### ISSUE THREAD

**Issue by adamt42** [grafana/grafana#5891]
* **I'm submitting a ...**
- [x] Bug report / Maybe feature
(Sorry if dupe.)

Grafana 3.1.1, InfluxDB 0.13, CentOS 6

Using this setup, I'm streaming data from a couple of IPs into Influx and I'm wondering if what's happening is a bug or if not, I'd ask for a feature. So the thing is that I can freely turn off/on the streaming from these IPs, and I'd like it so that when I do that, the metric line/graph discontinues when turning off and then continues again when turning on - **without a connected line between the turn-off and turn-on point**. I have changed the "null value" option to all of its different values, but nothing changed.

Visually:
![image](https://cloud.githubusercontent.com/assets/21198369/17896275/ef655026-6947-11e6-92ea-efd2b7907ea1.png)
This is when one of the servers has been turned off for a couple minutes. Then I turn it back on:
![image](https://cloud.githubusercontent.com/assets/21198369/17896313/0e163d5a-6948-11e6-9f7a-2130db7e99c4.png)
And the line connects up. I don't think that should happen when the other metrics have been constantly updating and I have set the null value to "null", but I may be wrong. What can you say about this?

Also, as you can see on the first picture, the legend of the turned-off metric still shows its last known value, even though that's clearly not up-to-date and as such, the 18% percent should be the highest value. "Hide series with only nulls" works perfectly as soon as that line disappears on the left side, but I'd like it if the legend at least would show that in the meantime the metric is either "NaN" or "null" or "-" which are all lower than everything in terms of ordering.

Ask away, if I'm not clear on something,
Adam T

**Comment by torkelo** [comment]
what's you influxdb fill param (in you query)

**Comment by adamt42** [comment]
It was null. But now I've tried it with everything, and it doesn't seem to matter.

**Comment by torkelo** [comment]
I am unable to replicate this, when I have fill(null) and null point mode set to null, missing data shows up as gaps in the graph. Do you have stack turned off (stacking does not work with null values, and requires data for each point), and has some visual oddities when series have null values (so make sure stacking is disabled). 

> Also, as you can see on the first picture, the legend of the turned-off metric still shows its last known value, even though that's clearly not up-to-date and as such, the 18% percent should be the highest value. "Hide series with only nulls" works perfectly as soon as that line disappears on the left side, but I'd like it if the legend at least would show that in the meantime the metric is either "NaN" or "null" or "-" which are all lower than everything in terms of ordering.

If you have fill(null) in your query and null point mode set to null, the legend should show current as blank, (at least that is what I get)

**Comment by adamt42** [comment]
Ok, I think I know the issue. What I'm thinking is that there's a difference between "null" data and literally no data. Because when I "turn off" data streaming from the servers, literally no more data points arrive, so Grafana doesn't know that there are nulls there, but it's just waiting on the "next" data point (and it receives it when I turn streaming back, so it connects it). If this is truly the case, is there anything I can do about it?

**Comment by torkelo** [comment]
yes, fill(null) in the query will insert null values in each time bucket (group by time interval) where no data exists

**Comment by adamt42** [comment]
Well... I'm out of ideas then. I've tried two different queries, I'm going to show you both, maybe I'm doing something completely wrong:
![image](https://cloud.githubusercontent.com/assets/21198369/17929123/5cb81af6-69f6-11e6-846e-68fcb3823e78.png)
![image](https://cloud.githubusercontent.com/assets/21198369/17929132/6c36f8ee-69f6-11e6-933f-eaccd3edbc45.png)

Neither does what you are saying should happen. :disappointed:

**Comment by torkelo** [comment]
maybe a bug in InfluxDB then? the second query with a group by time and fill should work. What is the InfluxDB response (chrome dev tools network tab).

Maybe the use of distinct aggregation function? Try another one

**Comment by torkelo** [comment]
And just to double check for the second query with group by time and fill(null), is null point mode (in display tab), also set to null?

**Comment by adamt42** [comment]
Only the distinct aggregation shows the actual values when I'm grouping by a tag.
The response from InfluxDB is normal, does not contain any data in the interval where a server is off:
![image](https://cloud.githubusercontent.com/assets/21198369/17932384/ac8f4b38-6a07-11e6-9abd-b2365138f18f.png)
(You can see that the timestamp jumps 140 seconds between 28 and 29. In that 140 seconds though, legend still shows the value from the last known data point.)

And yes null point mode is set to null. (Just to make sure, I created a new dashboard with the same panel from  the ground up and same effect.)

**Comment by torkelo** [comment]
ok, seems like a bug in InfluxDB with distinct and fill not taking effect

**Comment by adamt42** [comment]
You are indeed correct. On other graphs, where I could use sum() or mean() to show the correct values I need, the gaps show correctly. I'm guessing I should take this up with Influx if I want it fixed, right?
Thanks so much for your help, keep up the amazing work, Grafana is incredible!

**Comment by adamt42** [comment]
Although, SingleStat panels show a weird behavior. I've set them to the state where they should work, and the background graph **does** indeed appear with gaps, but during the gaps, the stat value doesn't disappear or goes to 0, it still shows the last value.
I've tried setting the value to text to different things and changing the fill parameter without success.
