### ISSUE TITLE
Missing kilovolt-ampere-reactive unit

### ISSUE THREAD

**Issue by ThomasADavis** [grafana/grafana#5892]
- **I'm submitting a ...**
- [ ] Bug report
- [*] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

v3.1.1

Axes/Unit/Energy is missing kilovolt-ampere-reactive.  You have kilovolt-ampere, and volt-ampere-reactive.

**Comment by bergquist** [comment]
Closed by #7328
