### ISSUE TITLE
Debian binaries different between website and APT repository

### ISSUE THREAD

**Issue by bflorat** [grafana/grafana#58947]
**What happened**:
.deb downloaded from https://grafana.com/grafana/download/9.2.2?pg=get&plcmt=selfmanaged-box1-cta1 are different from the hash of the .deb issued from the APT repository (https://packages.grafana.com/oss/deb stable main).

This is a little bit freaky from a security perspective.

Release 9.2.2:
Website:
![image](https://user-images.githubusercontent.com/203516/202690828-8281cc79-cf4c-413b-b31d-3d06cbe39c38.png)

APT repository (from apt-cache) :
SHA256: 38dbf2f67a0a706a67d21bbd895ff23377d8e977e770734f39fa537f81430bde

**What you expected to happen**:
Same hash (sha1, sha256) for same binary release between both locations.

**Environment**:
- Grafana version: probably all releases (tested 9.2.2 and 9.2.3)

**Comment by zuchka** [comment]
Thanks for creating this issue, @bflorat 

this was also reported in https://github.com/grafana/grafana/issues/58500.

An explanation is provided here by one of our cloud-infra folks:

https://community.grafana.com/t/grafana-oss-debian-repo-changes-origin-label-is-this-intended/75330/2
