### ISSUE TITLE
choose tags that don't depend one on other (not tree style)

### ISSUE THREAD

**Issue by yosefy** [grafana/grafana#5894]
- **I'm submitting a ...**
- [ ] Feature request

grafana 3
ubuntu 14
prometheus

hi what we are missing a big time
dropdowns as they are today, but not depending one on other
so you choose tag "A" from one dropdown
then tag "B" from other dropdown

then press "go"
and see all hosts matching tags (so its on the fly)

it could be mixed with existing system i think

thanks

**Comment by bergquist** [comment]
Im sorry but I don't think I understand. Could you please elaborate? perhaps add some screenshoots if possible.

**Comment by yosefy** [comment]
hi
thanks for reply try again
1) choose "tag type  location" variable from 1st fropdown
2)choose "tag type server_role" variable from second dropdown ( not depanding on first one)
perss something and get "tag type  location" & "tag type role" resoult

OR!
DON'T choose anything in first dropdown, say we dont need "tag type location" this time
because we want all locations



so may be we will set 5 dropdowns like that and each type sort by what we need and not create another dashbord for that

thanks

**Comment by torkelo** [comment]
no sure I understand this issue, you can have variables that do not depend on each other today (in any version of Grafana)
