### ISSUE TITLE
[Feature Request] Add help link to online documentation

### ISSUE THREAD

**Issue by gesquive** [grafana/grafana#5895]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v3.1.1
- What datasource are you using? graphite
- What OS are you running grafana on? ubuntu

It would be nice to have a direct link to the online documentation so that users can figure out how to use grafana easily.

**Comment by torkelo** [comment]
all non dashboard pages have Docs link in footer. 
![image](https://cloud.githubusercontent.com/assets/10999/17939175/9424699e-6a29-11e6-8992-4789d8759a6a.png)


Could perhaps also be added to sidemenu, top nav bar is quite sensitive (dont want to much distracting stuff there). 

@mattttt thoughts? 

https://cloud.githubusercontent.com/assets/450565/17935680/d8720234-69e1-11e6-8814-22010ca2607d.png

**Comment by gesquive** [comment]
My vote is for placing it in the top nav bar. We want to place that link somewhere obvious so clueless users can't miss it. Putting it in the side menu would obscure it a bit and make it more difficult to find.

**Comment by philjc** [comment]
:+1:, It would aid discoverability as the dashboard is usually one of the first things people see.

**Comment by davidfox2** [comment]
A random two bits from an outsider: I think bulletfactory's idea of having those links be "actionable items for that dashboard" sounds reasonable, and I dont see the two ideas being exclusive. 

- add a link to the side menu to take people to the help section of the website
- add a ? mark at the top menu bar that acts as/enables a help cursor (the type that you place over something and it gives a brief description)

top nav bar ? is still actionable and allows the user to remain on the current dashboard but get help on things displayed

**Comment by bergquist** [comment]
Link this? what do you think @mattttt @bulletfactory ?

![image](https://cloud.githubusercontent.com/assets/618863/18165199/2e5bc488-7044-11e6-9c33-089bb90f9cfa.png)

**Comment by daniellee** [comment]
Don't think this issue is relevant anymore. Link to the docs is in the bottom left menu:

![image](https://user-images.githubusercontent.com/434655/98723693-05d5e280-2393-11eb-8365-b811930d0df4.png)
