### ISSUE TITLE
Azure Monitor datasource is not listing all available metrics in Azure GovCloud

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#58990]
**What happened**:

When using the Azure Monitor datasource some metrics are missing in GovCloud.  Specifically the ones we noticed missing are the kubernetes related metrics because that's really all we use but there may be others.

**What you expected to happen**:

The same metrics to be available between Azure and Azure GovCloud. 

**How to reproduce it (as minimally and precisely as possible)**:

See attached gifs

**Anything else we need to know?**:

I spent a couple of hours with Azure support verifying that this was not an issue on their end and that it was not a permissions problem with the service principal we are using.  We went as far as giving the service principal the Contributor role on the subscription which is then inherited down to the kubernetes service and that did not make a difference.  When using developer tools in the browser you can actually see that the information is returned for the kubernetes services however it is not given as an option in the UI in grafana 8.x.

It is also not given as an option in grafana 9.x but in 9.x you have the Advanced menu where you can manually enter in all the values and if we do that then we do get the kubernetes related metrics that we are looking for, this confirms that the service principal has the proper permissions and that the metrics exist, they are just not being given as an option for some reason.

The other odd thing with 9.x is that the only Types that are being shown are related to DNS so there seems to be some odd scoping or something going on there.  This doesn't happen in 8.x

**Environment**:
- Grafana version: 8.0.6 and 9.2.4
- Data source type & version: Azure Monitor
- OS Grafana is installed on: linux kubernetes pod installed via grafana helm chart
- User OS & Browser: OSX, tested in both Chrome and Safari
- Grafana plugins: N/A
- Others: N/A

* In the GIFs I've removed the tenant, subscription and service principal information from the data source configuration screen but the information is there and works.
 
Working metrics in grafana 8 in Azure:
![grafana_8_azure_metrics_commercial](https://user-images.githubusercontent.com/5891946/202780791-f6bf2519-321a-4a5e-9c61-d3b7da1b00ff.gif)

No Kubernetes resource type given as an option in grafana 8 in Azure GovCloud:
![grafana_8_azure_metrics_govcloud](https://user-images.githubusercontent.com/5891946/202781021-1941620a-2317-46a4-9a6d-1873e89496c7.gif)

Working metrics in grafana 9 in Azure:
![grafana_9_azure_metrics_commercial](https://user-images.githubusercontent.com/5891946/202781211-d1bb09be-0c56-4916-82a0-3eedd106cc3c.gif)

No kubernetes related metrics in grafana 9 in Azure GovCloud (and only DNS related options being shown):
![grafana_9_azure_metrics_govcloud1](https://user-images.githubusercontent.com/5891946/202781335-2cc3db4d-d965-44cd-8ae0-a470cf08a36e.gif)

Manually entering in the required values in grafana 9 in Azure GovCloud and then getting metrics:
![grafana_9_azure_metrics_govcloud2](https://user-images.githubusercontent.com/5891946/202781459-76178a70-7d1d-4d03-b0b1-e10719c7f583.gif)

**Comment by aangelisc** [comment]
Hi @danfinn, thank you for the bug report! I'm investigating this and if possible could you clarify some things for me:

- How many resources are returned? If you take a look in developer tools at the `metricNamespaces` request it should provide this information.
- If you attempt to search for a specific resource does that work?

Thanks 😊

**Comment by danfinn** [comment]
Hi @aangelisc, 

I used the 8.0.6 instance with safari and developer tools to get the resources.  I didn't see anything that was an actual count of the resources so what I did is took the output and counted each instance of an id field because it seems like every resource returned has an id field.  I got 136 returned.  Here is one of the entries for a kubernetes cluster that is returned (sensitive info removed):

```
        {
            "id": "/subscriptions/353c53b6-xxx/resourceGroups/ogcqa-cust-virginia/providers/Microsoft.ContainerService/managedClusters/ogcqa-cust-virginia-aks-01",
            "name": "ogcqa-cust-virginia-aks-01",
            "type": "Microsoft.ContainerService/managedClusters",
            "location": "usgovvirginia",
            "identity": {
                "principalId": "2119e313-xxx",
                "tenantId": "5a8faf71-xxx",
                "type": "UserAssigned"
            }
        },
```

Regarding searching for a specific resource, I think I mentioned that above.  There is no way to do that in grafana 8.0.6 that I can see but it looks like this was introduced in the 9.2.4 instance I'm using.  In that version, if I use the Advanced drop down and manually enter in the information it does pull the metrics, this is in the last gif above.

**Comment by danfinn** [comment]
Sorry @aangelisc, it's not entirely clear what you want me to do?

**Comment by danfinn** [comment]
I see a something like this being returned for namespaces, is this what you're looking for?

```
        {
            "id": "/subscriptions/353c53b6-xxx/resourceGroups/ogcqa-cust-virginia/providers/Microsoft.ServiceBus/namespaces/sb-ogc-ogqa-usgovvirginia",
            "name": "sb-ogc-ogqa-usgovvirginia",
            "type": "Microsoft.ServiceBus/namespaces",
            "sku": {
                "name": "Basic",
                "tier": "Basic"
            },
            "location": "usgovvirginia",
            "tags": {}
        },
```

**Comment by aangelisc** [comment]
Yep, that confirms that your namespace response seems to be fine. I'll update this issue as I progress the investigation 😊

**Comment by aangelisc** [comment]
If possible, from the Azure CLI, could you run the following command `az account list-locations -o table` and post the output here please.

**Comment by danfinn** [comment]
```
az account list-locations -o table
DisplayName     Name           RegionalDisplayName
--------------  -------------  ---------------------
USGov Virginia  usgovvirginia  (US) USGov Virginia
Global          global         Global
USGov Arizona   usgovarizona   (US) USGov Arizona
USDoD Central   usdodcentral   (US) USDoD Central
USDoD East      usdodeast      (US) USDoD East
USGov Iowa      usgoviowa      (US) USGov Iowa
USGov Texas     usgovtexas     (US) USGov Texas
```

**Comment by aangelisc** [comment]
Hey @danfinn,

Thanks for that update. I've made a PR that *should* fix this issue. Will keep this issue updated.

**Comment by aangelisc** [comment]
Hi @danfinn,

The PR with the fix has been merged, it'll be released in the next Grafana release. If possible could you let me know if that solves the issue for you?

Thanks!

**Comment by danfinn** [comment]
Yes, although we aren't quite ready to make the move to 9.x yet.  Will this fix be back ported to older versions?

**Comment by danfinn** [comment]
I just tested this on 9.3.2 (using a bitnami helm chart, the grafana helm repo doesn't have 9.3.2 yet) and it does seem to be fixed.  Thanks!

**Comment by aangelisc** [comment]
Thanks for the confirmation @danfinn!
