### ISSUE TITLE
Auto-decimals: spurious decimal places on axis with kilowatt (kW) units

### ISSUE THREAD

**Issue by candlerb** [grafana/grafana#59000]
**What happened**:

I am displaying data with units in kilowatts.  The values in the currently selected time range are between 0 and 1 (actually the peak value is 0.262)

However, when I set decimals to "auto", the axis labels have spurious decimal places (e.g. 100.000W, 150.000W etc)

![image](https://user-images.githubusercontent.com/44789/202893493-1aa01e75-8d42-4c37-8c20-89ded6b8a2c3.png)

If I set decimals to zero, then the axis rescales itself to the range 0kW to 1kW, and only those two values are labelled:

![image](https://user-images.githubusercontent.com/44789/202893524-2894756a-0253-4ec3-b44d-e23839665133.png)

If I set decimals to 1, then it works as expected, but I still get "100.0W" and "150.0W" whereas I want to see "100W", "150W" etc

![image](https://user-images.githubusercontent.com/44789/202893536-a72f75e0-fca7-474b-b3a0-bf2b18117500.png)

At the moment, the best result I can get is to set "Custom unit: kW" and decimals: auto, but then I lose the scaling between watts and kilowatts.

![image](https://user-images.githubusercontent.com/44789/202893831-9700d2a5-a8ac-4282-b0dd-40173cd85add.png)

**What you expected to happen**:

With auto decimals, I would expect to see "100W", "150W" etc.  That is, 0.010kW, 0.015kW etc, scaled to watts, with the same number of significant figures.

**How to reproduce it (as minimally and precisely as possible)**:

* Use Timeseries visualization
* Graph values between 0 and ~0.3
* Set units to "Kilowatt (kW)"
* Set decimal places to Auto

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: Prometheus 2.37.1
- OS Grafana is installed on: Ubuntu 20.04.5
- User OS & Browser: macOS 12.6.1, Chrome 107
- Grafana plugins: camptocamp-prometheus-alertmanager-datasource (not being used)
- Others: n/a

**Comment by leeoniya** [comment]
9.3.0-beta1 has a fix for this. if you don't want to use the beta, we have a 9.3 release currently scheduled for Tue, Nov 29.

if you want to see the string of PRs: https://github.com/grafana/grafana/pull/52912, https://github.com/grafana/grafana/pull/57386, https://github.com/grafana/grafana/pull/57373

![y-decimals](https://user-images.githubusercontent.com/43234/202929897-68de9dd1-3135-4dcd-a808-3bb4a5251f89.gif)

**Comment by candlerb** [comment]
Many thanks, and sorry I didn't pick up the previous issues.
