### ISSUE TITLE
Data Source is not visible

### ISSUE THREAD

**Issue by Malay00** [grafana/grafana#5900]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.11
- What datasource are you using?
- What OS are you running grafana on?
Windows
- What did you do?
- What was the expected result?
- What happened instead?

I am not able to see the data source icon in the grafana dashboard i do not have iflux DB in my system.
Steps i have done.
1) in the browser : http://localhost:8080
2) Then set up the account, looged in. but could not see the data source icon.

Please suggest
![grafan_screenshot](https://cloud.githubusercontent.com/assets/21237387/17961883/bd6e7b08-6acb-11e6-80c1-fbeeb78b1315.png)
![grafan_screenshot](https://cloud.githubusercontent.com/assets/21237387/17961889/c6f9975c-6acb-11e6-943b-bfae5ab6ccd2.png)

**Comment by torkelo** [comment]
your user role within the Org must be Admin for it to see Data sources

**Comment by Malay00** [comment]
Hello Torkel,
I have set up grafana on my machine.
Elastic search is also running and curl is able to check the health and other indices.
I am not able to set that up with grafana ….. it would be great If you can help me out.

Appreciate your time.

Regards
Malay
