### ISSUE TITLE
add checksumBehavior to yarnrc.yml?

### ISSUE THREAD

**Issue by ianhu92** [grafana/grafana#59005]
**What happened**:
yarn install shows "The remote archive doesn't match the expected checksum". Accroding to https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#frontend , we have to include "YARN_CHECKSUM_BEHAVIOR=update" prefix to avoid it.

**What you expected to happen**:
https://yarnpkg.com/configuration/yarnrc#checksumBehavior
Add "checksumBehavior:update" config to yarnrc.yml file, no need to manully prefix the command.

**How to reproduce it (as minimally and precisely as possible)**:
Run "yarn install --immutable" on macos 13.0.1

**Anything else we need to know?**:

**Environment**:
- Grafana version:github main (https://github.com/grafana/grafana/commit/8ac197b11c22e9d8672d969c07a76678b6d5fb5a)
- Data source type & version: N/A
- OS Grafana is installed on:Macos 13.0.1
- User OS & Browser:Macos 13.0.1, Chrome 107.0.5304.110
- Grafana plugins: N/A
- Others:

**Comment by jackw** [comment]
Hmm... rather than default the behaviour to `update` which would circumvent the integrity checks we should probably update the developer-guide asking for issues to be opened so we can fix the root cause.

**Comment by ianhu92** [comment]
> Hmm... rather than default the behaviour to `update` which would circumvent the integrity checks we should probably update the developer-guide asking for issues to be opened so we can fix the root cause.

Thanks for the review, close the issue for now.
