### ISSUE TITLE
Post 9.2 Using API & JWT auth - if email claim fails auth does not fall through to use basic auth

### ISSUE THREAD

**Issue by vCra** [grafana/grafana#59023]
**What happened**:

After upgrading from Grafana 9.1.4 to Grafana 9.2.1, authenticating with Basic auth with a non-user-account JWT present in the auth.jwt header_name header does not fallback to using Basic Auth, but instead instantly fails with the following error

`{"error":null,"level":"warn","logger":"context","msg":"Got a JWT without the mandatory 'sub' claim","t":"2022-11-21T10:27:54.299454803Z"}`

**What you expected to happen**:

A failed JWT login should fallback to Basic Auth (or another type of login)

**How to reproduce it (as minimally and precisely as possible)**:

(We are using Cloudflare access)
Configure a Cloudflare access tunnel to Grafana. In the grafana settings, configure `auth.jwt` to use the Cf-Access-Jwt-Assertion header, and set username and email claims to use `email`

Create a Cloudflare Service token with permissions to use the app.
Make an API call with the CF access headers, and basic auth headers for a local grafana user. In 9.1.4 this works successfully, but in 9.2.1 you get the above warning, and authentication fails

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1

**Comment by mellieA** [comment]
Not sure if this could be related to changes made in https://github.com/grafana/grafana/issues/54244

**Comment by mgyongyosi** [comment]
Hi @vCra,

The default behaviour in Grafana's authentication middleware is to attempt to login with the first configured method if the basic requirements are met for that method (in your scenario an existing JWT token), and in case the authentication fails then Grafana returns with Unauthorized.

Although in your scenario Grafana was working correctly before 9.2 but it was not the intended behaviour.

Could you please share why does a JWT token is included in the request when the user is expected to use Basic auth for logging in to Grafana? By any chance, does removing the JWT token/Cf-Access-Jwt-Assertion header from the request an option?

**Comment by vCra** [comment]
Hi @mgyongyosi

Because we are securing Grafana with CloudFlare access, all requests that pass the first layer of authentication automatically have a JWT in each request that is forwarded to Grafana.

For users connecting through a browser this makes sense. The user is already authenticated with an IDP, and a JWT is created using that data (e.g. the email, sub etc)

For programmatic access, we still have a JWT that is forwarded through CloudFlare (which contains an exp for example), but does not contain any user data (because it's not a user)

Comparing a users JWT and programatic access JWT, we can see that we get less data

| User JWT | Application JWT |
|----------|-----------------|
| aud      | aud             | 
| type     | type            |
| exp      | exp             |
| iss      | iss             |
|     | common_name             |
| iat | iat |
| sub | sub |
| email | |
| nbf | |
| identity_nonce | |
| country | |

For the programmatic access JWT, whilst we do get a `sub` field, it is empty, whereas for users it is populated

To clarify - users are not expected to be authenticated with BasicAuth - this is just for programmatic access (this issue will also affect API key and token auth, as JWT auth is done before this)

> By any chance, does removing the JWT token/Cf-Access-Jwt-Assertion header from the request an option?

We have considered this, but it's not an ideal situation. It will mean having to have a seperate address for programmatic access and user access, and have some form of proxy to strip the assertion header (probably with Envoy or similar) and then forward the request on to Grafana.

I'm wondering if checking for a non-empty `sub` would work as a work around and soft-failing if so, or if this would be too expensive to do

**Comment by mgyongyosi** [comment]
Hi @vCra! Thanks for the explanation we implemented your suggestion and the non-empty `sub` pre-check has been added to the JWT Auth client. It will be released with Grafana 9.4.
