### ISSUE TITLE
Multiple values template variable not drawing any graphs

### ISSUE THREAD

**Issue by sasq31** [grafana/grafana#5904]
Hi,

I've recently installed grafana-3.0.4 and am using prometheus as a datasource. 
In prometheus I am relabeling the Name tag to be instance :

relabel_configs:
- source_labels: ['__meta_ec2_tag_Name']
target_label:  instance

I have created a recording rule which enables me to compute CPU utilisation percentage for each node and that is :

instance:node_cpu:ratio_rate1m = sum by (instance,nodetype,zone) keep_common (rate(node_cpu{mode!='idle'}[1m])) / on (instance,nodetype,zone,job) sum by (instance,nodetype,zone) keep_common (rate(node_cpu[1m])) * 100

This basically enables to get a list of hostnames and the template below populates that with those hosts with "accept" in the hostname : 

![variable](https://cloud.githubusercontent.com/assets/18006624/17970877/4bd6844a-6ad0-11e6-8263-2ed3782e08ee.png)

Then without selecting "Multi Value" or "Include All option" I can select each node from that variable fine (shown below) : 

![variable](https://cloud.githubusercontent.com/assets/18006624/17970995/d4d87fd2-6ad0-11e6-81b4-c008adf3794a.png)

When I then select "Multi Value" or "Include All option" it fails to draw anything.

Is this because the query I have isn't expecting a list and that's what it's getting ? 

instance:node_cpu:ratio_rate1m{instance="$instance_name"}

I would really appreciate any help you may have on this subject and will promptly supply any more information that is needed.

Thanks !
Ben

**Comment by torkelo** [comment]
use regex operator

**Comment by apoorva11029** [comment]
What regex operator worked for you?

**Comment by daniellee** [comment]
@apoorva11029 here is an example of substring matching with Prometheus in a template variable: http://play.grafana.org/dashboard/db/3-promcon-templating?orgId=1&editview=templating

If you are still stuck then ask a question on our [community site](https://community.grafana.com/).

**Comment by apoorva11029** [comment]
Thanks for the prompt reply @daniellee .

I used the multivalue option for the disk template variable in this example and ended up getting the same error.[
![screen shot 2017-05-11 at 9 42 02 am](https://cloud.githubusercontent.com/assets/5749009/25961184/403f48c2-362e-11e7-80a1-b5ee47a471c8.png)
](url)
