### ISSUE TITLE
[Docs]: Include upgrade info for linux & windows

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#5905]
Include upgrade instructions & info in docs for linux & windows.

**Comment by torkelo** [comment]
you only need to copy over the new files and restart grafana-server.

**Comment by anhlqn** [comment]
Overwrite Grafana folder with the new package?

**Comment by torkelo** [comment]
yes, as long as you made your config changes in a new file called custom.ini (and did not modify defaults.ini), your config changes will not be overwritten

**Comment by anhlqn** [comment]
Great, thanks.
