### ISSUE TITLE
 Unique Count nested obj at grafana v4.nightly building 

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5907]
i use the nightly version  about grafana-4.0.0-1471946435pre1.x86_64,i use the feather Precision threshold 
for Unique Count,when i Unique Count a nested obj , it return a count number, the obj like :+1: {"product"[{"partyId":16815,"stringId":"16815"}],"inputDate":"1472206540900","partyId":16815,"stringId":"16815"}
if its not a nested obj like{ "inputDate":"1472206540900","partyId":16815,"stringId":"16815"} it worked,

**Comment by torkelo** [comment]
not sure I understand. Could you show the Grafana query sent to ES and the response?

**Comment by tonyC2016** [comment]
when Unique Count stringId,its type is string:
{"responses":[{"took":30,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":89691,"max_score":0.0,"hits":[]},"aggregations":{"2":{"buckets":[{"key_as_string":"2016-08-27T00:00:00.000Z","key":1472256000000,"doc_count":0,"1":{"value":0}},{"key_as_string":"2016-08-28T00:00:00.000Z","key":1472342400000,"doc_count":89691,"1":{"value":40003}}]}}}]}

{"responses":[{"took":35,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":89691,"max_score":0.0,"hits":[]},"aggregations":{"2":{"buckets":[{"key_as_string":"2016-08-27T00:00:00.000Z","key":1472256000000,"doc_count":0,"1":{"value":0}},{"key_as_string":"2016-08-28T00:00:00.000Z","key":1472342400000,"doc_count":89691,"1":{"value":39998}}]}}}]}

when Unique Count partyId,its type is long:
the correct value is 39998,maybe when use Unique Count,its need the long or integer type. string type has returned wrong value!

**Comment by torkelo** [comment]
Have you tried the precision threshold parameter? Not sure if this is a grafana issue

**Comment by tonyC2016** [comment]
yeah,i used the  precision threshold,maybe its not ,i will try again
