### ISSUE TITLE
Bug: slider input field is not focused any more on change

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#59073]
**What happened**:
The slider input field does not get auto focused on slider change anymore.

**What you expected to happen**:
Input field keep having focus on change

**How to reproduce it (as minimally and precisely as possible)**:
- Is `broken` in Grafana `v9.4.0-42650pre`
- Is `working` in Grafana `9.2.5` (you can see it on https://play.grafana.org/)

**Anything else we need to know?**:
Probably caused by https://github.com/grafana/grafana/pull/49242

Here is a GIF, first the `broken` then the `working` version. 

It might be working as expected, just want to make sure this is not a regression. 

![Nov-21-2022 22-13-48](https://user-images.githubusercontent.com/580672/203160281-f9c515fc-67d0-48e8-b0c8-1260eabe809a.gif)

**Comment by joshhunt** [comment]
probably regressed by https://github.com/grafana/grafana/pull/49242

**Comment by eledobleefe** [comment]
Hi @tolzhabayev and @joshhunt. 
I run `git bisect` and it seems to be triggered by #57964. I checked twice, just in case 😅
