### ISSUE TITLE
Unable to login to grafana (installed from latest source with alerting=true) - 404 error

### ISSUE THREAD

**Issue by anirbanroydas** [grafana/grafana#5908]
Having successfully installed grafana from latest source, and doing all configuration settings with custom.ini and running it behind Nginx.

Although when trying to go the address, I get a 404 error.

address: http://server_address_with_port/grafana/
I get redirected to http://server_address_with_port/grafana/login 
and get a 404 page not found error.

This is the log report : 
```
INFO[08-26|10:21:38] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=127.0.0.1 time_ns=0 size=37
INFO[08-26|10:21:38] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=//login status=404 remote_addr=127.0.0.1 time_ns=0 size=19
```

My nginx and custom.ini changes: 

```
nginx.conf

location /grafana/ {
     proxy_pass         http://localhost:3000/;
     proxy_set_header   Host $host;
}

grafana.ini update root:

[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

```

So why is it happening?

**Comment by torkelo** [comment]
Try 
```
location /grafana {
     proxy_pass         http://localhost:3000/;
     proxy_set_header   Host $host;
}
```

(notice the location url without trailing slash.
Also try to set grafana.ini root_url to

[server]
root_url = http://your.nginx.ip.or.domain/grafana

the root_url should be to the exact root url you use to access grafana in your browser

**Comment by anirbanroydas** [comment]
@torkelo So I don't have a grafana.ini, instead I have a defaults.ini and I have created a custom.ini, and there is also a sample.ini too. So does this have to do with anything?

Because I tried those above edits, still showing the exact error. Also, in the custom.ini, there is also a domain settings, so do I have to change that too along with the root_url? Because I am actually proxying it via nginx, so is that necessary too?

Problem not solved so far.

**Comment by torkelo** [comment]
strange, not sure what could be wrong. 

This nginx config 

```
location /grafana {
     proxy_pass         http://localhost:3000/;
     proxy_set_header   Host $host;
}
```

along with a root_url setting that is the same as the one you you have in your browser has worked for everyone I helped.

**Comment by anirbanroydas** [comment]
@torkelo  what about the domain settings? do i have to change that to reflect the actual domain name or leave it to default localhost. 

Actually I have tried with both of then and it gives error on both?

Okay so what all things could go wrong when it shows this error? If you can tell me this, then I can redo my installation.

Actually, since we need the alerting feature so I had to do source install. So had to install go first and then installed grafana with the go get command.

Actually followed the official documentation.

Also, since the server starts up successfully that means its working right? Really stuck up here. Need grafana. Need alerting. Help me out here a bit.

**Comment by torkelo** [comment]
the 404 error means you have not configured nginx or grafana correctly , can you show the output from grafana log when you start it? 

Also try installing a nightly build instead (which gives you a config file in /etc/grafana/grafana.ini)

**Comment by anirbanroydas** [comment]
@torkelo  I will look into the nginx and grafana config once more.

Also, if I install a nightly build, do I have to first uninstall the previous installation from source, will there be any conflicts or will it just overwrite everything?

**Comment by anirbanroydas** [comment]
@torkelo 
Now I did some changes in my config files. And now it seems to work.
As an update I would like to mention what I did, so that you can take note of it and update that with other users if they face similar problem.

```
nginx => configuration :

location /grafana {
     proxy_pass         http://localhost:3000;
     rewrite  ^/grafana/(.*)  /$1 break;
     proxy_set_header   Host $host;
}

graphana.ini

[server]
# domain = localhost (I haven't changed this)
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

```

After all the errors, only this seem to have worked. Please take not of this. If you can get the insight as to why this worked and not the other ones, let me know. There is something with your root_url setting which I couldn't understand what it is exactly doing, since this is the one which worked.

Let me know.
