### ISSUE TITLE
Extend templating with features from PromDash's

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5910]
@bergquist @grobiee @stuartnelson3 

As per promcon:
- @grobie 's suggestion is that @stuartnelson3 ports PromDash's templating system to Grafan
- There should be a way to filter out label values from stale time series
- It might be useful to automagically filter to the requested time frame by default
- pink and fluffy unicorns

**Comment by bergquist** [comment]
@stuartnelson3 @grobie Perhaps you could elaborate on the differences?

**Comment by grobie** [comment]
Point 1 is about providing template functions like `{{ $value | percent }}` which displays `0.1` as `10%`. Promdash provides a bunch of such filters https://prometheus.io/docs/visualization/promdash/#filters. I had asked @stuartnelson3 whether that's hard to port given both projects use angular.

Part 2 seems to be about hiding null values from the value hover? Not sure I understand that correctly, but I think that could be useful.

I don't have enough context for part 3 I guess?

**Comment by RichiH** [comment]
Part 2 is about the fact that as of right now Grafana will fill a template value list with everything that has ever been a valid label value. Combined with long retention periods, this results in the template dropdown being filled with e.g. instances which have been spun down months ago. This could be avoided by defining a maximum age of interesting label values.

Part 3 is about looking at the time range of a given query and adapting the label_value() result set to that time span.

**Comment by stuartnelson3** [comment]
1. the filters for template variables shouldn't* be difficult
2. I'm not familiar with how grafana caches these values, but can look at it (or @bergquist can expand)
3. Sounds like expanding upon the pre-existing functionality, but I would need context on what grafana does and how prometheus decides to return label sets (whether or not prometheus already supports filtering label sets by a date)

Unfortunately (well, I'm excited), I'm leaving for a weeklong vacation tomorrow, so the earliest I can look at this will be sometime after that.

* probably shouldn't, haven't tried yet

**Comment by bergquist** [comment]
1. Sounds like a good idea. I would love to have this for all datasources but starting with prometheus would be great.

2/3 To me these seems like the same problem. Digging into the prometheus datasource if seems like this should have been solved. https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/metric_find_query.js#L117-L119

**Comment by RichiH** [comment]
2/3 can easily solved in one go, but I wanted to make sure both aspects are addressed.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by aocenas** [comment]
@RichiH is this issue still relevant?

**Comment by RichiH** [comment]
It's relevant, yes. These days, it might make sense to implement part of this in PromQL and use Grafana to just consume the different outcome.

CC @ben, @beorn7 & @juliusv for thoughts.

**Comment by beorn7** [comment]
I'm not familiar enough with this depth of detail in dashboarding to really comment on this. And I have forgotten everything about PromDash. :-/

**Comment by roidelapluie** [comment]
It seems to be that all of these are standard features of grafana now.

1. Set unit as percentunit.
2. this is the case now out of the box.
3. set refresh=time on the dashbords variables
4. theming is available on grafana entreprise, there you can have unicorns.

**Comment by davkal** [comment]
Indeed @roidelapluie ! Let's close this 🎉
