### ISSUE TITLE
Instance name is not available when using agent metrics on gcp

### ISSUE THREAD

**Issue by mpostument** [grafana/grafana#59111]
I need to show instance name in legend. But there is no such label in grouping. So i am grouping by instance id. And i am trying alias as described here https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/. But i am getting incorrect value in legend

**What happened**: Cannot use name in legend when using agent metrics

**What you expected to happen**: Instance id is replaced with instance name in legend

**How to reproduce it (as minimally and precisely as possible)**: 
![gcp_alert](https://user-images.githubusercontent.com/9252594/203319008-a7e564e6-ac84-4098-b1ca-c452cd782eb9.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.4
- Data source type & version: stackdriver
- OS Grafana is installed on: kubernetes
- User OS & Browser: Chrome
- Grafana plugins:
- Others: Similar issue https://github.com/grafana/grafana/issues/18750

**Comment by mpostument** [comment]
Without alias it look like this. And i need to replace instance with id with instance name. When i am using other metrics (not agent), this alias work fine
![GCP](https://user-images.githubusercontent.com/9252594/203579467-6eb5a277-0d9e-49ad-8c22-9da2f9fb3951.png)

**Comment by andresmgot** [comment]
hi @mpostument, in the case of the metric `agent.googleapis.com/disk/percent_used` it's the [Google API](https://cloud.google.com/monitoring/api/metrics_agent#disk/percent_used) the one that does not return a label for the `instance_name`. The only labels returned at the metric lable are `state`and `device`. You can either use those or the resource ID (`resource.label.instance_id`). Basically you can only use the labels that you can see in the Filter section.

**Comment by hvspa** [comment]
> hi @mpostument, in the case of the metric `agent.googleapis.com/disk/percent_used` it's the [Google API](https://cloud.google.com/monitoring/api/metrics_agent#disk/percent_used) the one that does not return a label for the `instance_name`. The only labels returned at the metric level are `state`and `device`. You can either use those or the resource ID (`resource.label.instance_id`). Basically you can only use the labels that you can see in the Filter section.
> 
> Please re open the issue if you still think there is an issue with the editor.

hello All,

when i do group by instance id, i start to see instance_id-s, which are really ID-s and not the VM-s hostnames, which i am trying to see. but when you do query the same in google cloud console it clearly return the VM name:
`  Name (from instance_id)
`
so google knows how to convert the IDs into names.

any ideas how we can do the same in grafana using google cloud monitoring datasource? 

thanks in advance,

**Comment by masikrus** [comment]
use MQL for query and use group_by
example:
`fetch gce_instance::agent.googleapis.com/disk/percent_used
| filter state = 'used'
| filter device !~ '/dev/loop.*'
| group_by
[metadata.system.name: metadata.system_labels.name, device]`

and then you can used new label 
`{{ index $labels "metadata.label.system.name" }}`

![Image](https://github.com/user-attachments/assets/686bf51d-ab5f-457a-a50c-c08db793a1d5)

**Comment by hvspa** [comment]
> use MQL for query and use group_by example: `fetch gce_instance::agent.googleapis.com/disk/percent_used | filter state = 'used' | filter device !~ '/dev/loop.*' | group_by [metadata.system.name: metadata.system_labels.name, device]`
> 
> and then you can used new label `{{ index $labels "metadata.label.system.name" }}`
> 
> ![Image](https://github.com/user-attachments/assets/686bf51d-ab5f-457a-a50c-c08db793a1d5)
> 
> UPD... or use PormQL `avg by (metadata_system_name, device) (agent_googleapis_com:disk_percent_used{monitored_resource="gce_instance", device!~"/dev/loop.*", state="used"})`

thank you very much, seems this is what exactly i was looking for!!! 
much appreciated your help!!!!
