### ISSUE TITLE
Grafana cannot read some indexes in Elasticsearch 2.2.0

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#5912]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Elasticsearch 2.2.0
- What OS are you running grafana on? Windows Server 2012 R2
- What did you do?
Added multiple data sources for multiple index patterns stored in Elasticsearch 2.2.0
- What was the expected result?
Grafana should be able to display data from all data sources.
- What happened instead?
Grafana can only display data from one data source/index pattern. I have IIS log indexes with same template/data, but Grafana can read the indexes that are on Elasticsearch 2.3.x, but fail to read those on ES 2.2.0.

I've tried to enable `trace` log on Grafana but saw nothing, and no error appears on Elasticsearch node that Grafana queries against.

I wonder if anyone has encounter similar issues.

**Comment by torkelo** [comment]
can you show the requests Grafana makes to ES and the response from ES?

**Comment by torkelo** [comment]
Please you can view this in chrome dev tools network tab.
