### ISSUE TITLE
Ability to aggregate across data sources

### ISSUE THREAD

**Issue by amangup** [grafana/grafana#5913]
- [x ] Feature request

Is it possible to aggregate value across data sources? A simple example of the use case is: we have an http service, and its running across different data centers. There is one data source per datacenter. I want to know the total number of http requests my service is receiving.

I tried the following, but couldn't find it supported:
1. Allow multiple data sources in a single panel
2. Define a metric by referencing a metric in another panel
3. Create a new data source which is backed by multiple other data sources.

Can we add support for this use case?

Thanks,
Aman

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3677
