### ISSUE TITLE
Data-links edit and delete icons are off-screen and not visible

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#59150]
**What happened**:

**See this video for reproduction steps:
https://www.loom.com/share/e4874e7f4e884258a43d5f8e7e185f24**

Simpler reproduction steps:
1. Find a table panel
2. Add an override for one of the table columns
3. Add a data-link for that column
4. For the link-title, enter the text `View Cardinality Overview dashboard scoped to ${label}: ${__data.fields.value}`. The URL can be left blank
5. Now see that the edit ✏️ and delete ❌  icons quite easily disappear off the screen when the panel-edit side-panel isn't large enough.

**What you expected to happen**:
The edit and delete buttons should always be on the screen, no matter how wide or narrow I set the panel-edit side-panel, and no matter what content has been set in that specific data-link.

**How to reproduce it (as minimally and precisely as possible)**:

1. Sign up for GrafanaCloud free account
6. Go to Cardinality Management 1: overview
7. Make it editable
8. Edit "Highest cardinality metrics" panel
9. Try to edit the data-link, on a narrow panel-edit side-panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.0-42834pre
- Data source type & version: Prometheus - `grafanacloud-usage` datasource on GrafanaCloud
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: macOS 12.6.1 (21G217), Version 107.0.5304.110 (Official Build) (arm64)
Automatically update Chrome for all users [Learn more](https://support.google.com/chrome/answer/95414)

**Comment by mellieA** [comment]
Video summary: 
In the table panel options, the edit icon (pencil) and close (x) buttons in the data links section move out of the viewable area when you resize the options column. 

I tried this out on play running grafana 9.2.5 and the edit pencil and X are fixed and always show - so something has changed in the newer pre release (9.4.0-42834pre)

This is from 9.2.5 when I resize the column: 

![Screen Shot 2022-11-23 at 1 02 41 PM](https://user-images.githubusercontent.com/18175287/203638528-180ae723-6e1d-4757-bd93-a703b02efc14.png)

![Screen Shot 2022-11-23 at 1 02 26 PM](https://user-images.githubusercontent.com/18175287/203638530-e20e8f81-e724-470a-8571-cab0bd709b3e.png)

**Comment by samjewell** [comment]
Hi @mellieA 

Thanks for the investigation.
It is actually a problem in 9.2.5 also, but it's problematic on 9.2.5 for narrower screen widths. Typically on a laptop screen, and running Grafana side-by-side with another window. See the video. Thanks

https://www.loom.com/share/ae4d97ea0e7147a58009e0280d515e28

**Comment by samjewell** [comment]
@mellieA One more thought here:

You seem to have triaged this into `area/panel/table`, but as far as I know data-links are available on all panels, right? They're not unique to tables, but also present on things like bar-charts for example. Maybe this should just be `area/panel`? Thanks!

**Comment by zoltanbedi** [comment]
@samjewell right this is not related to the table panel more like the edit view. Thanks for reporting this though I was able to reproduce.

**Comment by samjewell** [comment]
@dprokop and team: **thanks** for fixing this ❤️
