### ISSUE TITLE
Docs feedback: Broken link on /enterprise/_index.md

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#59167]
The link to 'Data source query caching' is broken 

https://grafana.com/docs/grafana/latest/enterprise/#enterprise-features 

"[Data source query caching](https://grafana.com/404/) to temporarily store query results in Grafana to reduce data source load and rate limiting." 

Returns a 404.

**Comment by osg-grafana** [comment]
@chri2547, wanna grab this one?
