### ISSUE TITLE
Need help with Grafana Phlare 

### ISSUE THREAD

**Issue by Manasa-VG** [grafana/grafana#59207]
**What happened**:
Grafana-Phlare is not showing up under Datasource

**What you expected to happen**:
Phlare is not showing up as expected after installing an configuring. 

**Anything else we need to know?**:
Reference ticket thread - community.grafana.com/t/unable-to-upgrade-grafana-from-8-3-5-to-9-3/76030 

**Environment**:
- Grafana version: 9.4-89664pre (grafana.com/grafana/download/9.4.0-89664pre?edition=oss)
- Data source type & version: Phlare ( https://grafana.com/docs/phlare/latest/operators-guide/get-started/ ; [phlare_0.1.0_darwin_amd64.tar.gz](https://github.com/grafana/phlare/releases/download/v0.1.0/phlare_0.1.0_darwin_amd64.tar.gz) 
- OS Grafana is installed on: Virtual Box - Ubuntu 20
- User OS & Browser: Google Chrome
- Grafana plugins: 
- Others:

**Comment by joey-grafana** [comment]
Hello, thanks for opening the issue. 

Can we double check here that the feature toggle is enabled? Docs [here](https://grafana.com/docs/grafana/next/datasources/phlare/) and similar reference [here](https://github.com/grafana/grafana/issues/58158).

**Comment by Manasa-VG** [comment]
You are welcome and thanks for looking into this!

Yes I have enabled the feature in the configuration file . Unfortunately, no luck.

**Comment by Manasa-VG** [comment]
[feature_toggles]

enable = flameGraph

**Comment by joey-grafana** [comment]
Thanks for the update.

If you go to the the datasources configuration page and click `Add new data source` do you see Parca and Phlare in the profiling section?

<img width="1005" alt="Screenshot 2022-12-06 at 13 05 02" src="https://user-images.githubusercontent.com/90795735/205920630-4fdcf178-a674-4856-85d1-233bdac9d80c.png">
<img width="1140" alt="Screenshot 2022-12-06 at 13 05 12" src="https://user-images.githubusercontent.com/90795735/205920635-5ddee6f4-e123-4c56-b60f-c2695c8e1706.png">

**Comment by Manasa-VG** [comment]
Thanks for the information, I'll check again tomorrow and let you know.

**Comment by Manasa-VG** [comment]
No I don't see both under Datasoures

**Comment by joey-grafana** [comment]
Let's double check that the feature toggle is being applied to your Grafana.

Can you check your `feature_toggles` section on the `admin/settings` page to see if the flameGraph feature toggle is listed & enabled?

**Comment by Manasa-VG** [comment]
Hey Joey,

Yes i had enabled the feature toggle and restarted Grafana service , i am
now able to see phlare.
