### ISSUE TITLE
Build: Enterprise build doesn't work as expected for OSS PRs

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#59217]
**What happened**:
Comment on my PR that the Enterprise drone build failed, https://github.com/grafana/grafana/pull/58132#issuecomment-1324791929, and following that link I unexpectedly see a successful build.

**What you expected to happen**:
No comment since the build passed.

**How to reproduce it (as minimally and precisely as possible)**:
I had a PR in [OSS](https://github.com/grafana/grafana/pull/58132) and [Enterprise](https://github.com/grafana/grafana-enterprise/pull/4117) with a branch named the same.

**Anything else we need to know?**:
@dsotirakis thinks it's a bug

**Comment by tleopold** [comment]
This has been resolved.
