### ISSUE TITLE
Unable to define / update InfluxDB data source when database is empty

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#59224]
**What happened**:
When defining a new InfluxDB data source type InfluxQL for a newly created database, it fails with "error connecting influxDB influxQL" error message.

**What you expected to happen**:
Since all other things are correct, I would have expected Grafana to define the data source and tell me that it's ok.

**How to reproduce it (as minimally and precisely as possible)**:
* Define a new data source and point to "_internal" (to eliminate all other possible errors).
* In InfluxDB create a "foobar" database
* Now change the data source definition to point to the "foobar" database, leaving the rest as-is 
* Press [Save & Test] - this will fail as described

Create some random data in the new InfluxDB, like
* use _internal
* select * into foobar..cq from cq limit 10

Now [Save & Test] that data source, and see that it works

**Anything else we need to know?**:
I typically upgrade with existing definitions or with a working InfluxDB, so don't know for sure when this started. I suspect it started with the change that shows the number of measurements when [Save & Test] worked properly.
That's information is nice and helpful, but I think it would be good to allow definition or update of the data source with just a warning that there is nothing in it yet, or that the database does not exist yet. There's no real reason to enforce a specific ordering of the steps to define it all.

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: InfluxDB v1 - with InfluxDB on 1.8.10 
- OS Grafana is installed on: RHEL 8.7
- User OS & Browser: RHEL & Chrome
- Grafana plugins: InfluxDB core plugin
- Others:

**Comment by usmangt** [comment]
Hi @rvdheij,

Thanks for opening this issue.

I am not 100% sure as well if this is InfluxDB or Grafana. Therefore, I would encourage you to ask this one first in our [community forums](https://community.grafana.com/) as there is a dedicated category for [InfluxDB](https://community.grafana.com/c/support/influxdb/11) where many active community users help each other and since yours, one might be something they have some information already.

In case not then, I will reopen this issue (as for now I will close it).

**Comment by rvdheij** [comment]
@usmangt  Please re-open. I must not have made myself clear. Grafana is using a "show measurements" to see whether the database exists. This is cute and helpful, but there are other ways to detect that the database exists but does not have measurements (yet). For example empty database gives 0 rows where the non-existing one gives an error.

**Comment by mbentley** [comment]
Looks like a user on [Reddit](https://www.reddit.com/r/influxdb/comments/107fh2c/cant_create_a_grafana_datasource_to_indluxdb_1810/) is experiencing the same thing.  It is acting like the connection isn't working when testing but it is just likely that there is no data.  Can confirm that I see the same behavior with an empty database.

**Comment by itsmylife** [comment]
I am closing this issue. Feel free to reopen it or create a new issue if the problem still occurs.
