### ISSUE TITLE
query editor is very tiny to work in

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#59235]
**What happened**:
Space used to write queries is way too small

**What you expected to happen**:
Not to be too small

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/900951/203587017-8e80d5b1-1fac-496a-8805-62b657c1758e.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.15
- Data source type & version: json
- OS Grafana is installed on: Windows
- User OS & Browser: Windows/Chrome
- Grafana plugins: Infinity
- Others: All that wasted space on the right!

**Comment by mellieA** [comment]
@yosiasz I've moved this to the dev squad for review. I'll let them decide if they consider this a bug or feature request

**Comment by nmarrs** [comment]
This looks to not be related to the canvas panel, but instead to the query editor. I've updated tags accordingly 👍

**Comment by yosiasz** [comment]
que pasta with this bug?

**Comment by zoltanbedi** [comment]
This is not related to grafana but the infinity datasource. https://github.com/yesoreyeram/grafana-infinity-datasource
