### ISSUE TITLE
Grafana Nightly Build has no alert feature? I fail to find it? My version is 4.0.0-pre1

### ISSUE THREAD

**Issue by anirbanroydas** [grafana/grafana#5925]
I was looking for a alert based solution and thought to try out new grafana source, but I was told by @torkelo to use the nightly build source. I did it. But I see no alert feature in it.

Referring to #5908 

Please tell me what to do now? Reinstall from source or is there anything I am missing?

**Comment by bergquist** [comment]
@anirbanroydas have you enable it in the config?

Alerting is disable by default.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/conf/sample.ini#L321 

btw @bergquist that line should be commented out

**Comment by anirbanroydas** [comment]
@bergquist Yes. My bad. It was disabled. I did it last time when I built it from source, but this time it slipped out of my mind. Thanks.

@torkelo  Thanks.
