### ISSUE TITLE
regex formatting doesn't properly escape special characters for PromQL

### ISSUE THREAD

**Issue by klinki** [grafana/grafana#59251]
**What happened**:

Variable with values containing `/` doesn't get properly escaped and query ends with error 

> bad_data: 1:73: parse error: unknown escape sequence U+002F '/': details:

Here is expression copied from inspect-query:

```
expr:"rate(total_requests{server=\"Server A\", environment=\"staging\", raw_url=~\"\\/about\\.ashx\"}[2m])*60/2"
```

Example values:
- `/some/path/from/server`

used in query
```
rate(total_requests{server="$server", environment="$environment", raw_url=~"${raw_url:regex}"}[2m])*60/2
```

**What you expected to happen**:

I expect this to work correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Have label with values containing `/` 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.5 (on grafana cloud)
- Data source type & version: prometheus-net library, grafana-agent as collector

**Comment by usmangt** [comment]
Hi @klinki,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by klinki** [comment]
Hi @usmangt , sure, I will try.

Where can I find the credentials to log in?

**Comment by usmangt** [comment]
There are no login credentials. You simply click the link and directly land inside the UI with a bunch of Panel showing some visuals. Create a new panel to reproduce it.

**Comment by klinki** [comment]
Yeah the thing is I need dashboard variable. And also, I just tried to create the panel and I couldn't save it so changes are not persisted.

I tried to add panel to this dashboard: https://play.grafana.org/d/UVtfqAznz/panel-links?orgId=1
(I guess the Replicating Issues folder is the right one to look at, right? :) )

Anyway, I was able to reproduce it and I saved the dashboard JSON, so here it is at least in JSON format:
[dashboard-with-error.zip](https://github.com/grafana/grafana/files/10083414/dashboard-with-error.zip)

**Comment by hannahchan** [comment]
Hi,

I think I'm experiencing the same issue. I'm using OpenTelemetry automatic instrumentation in my app to collect HTTP metrics. The OpenTelemetry HTTP metrics contain an attribute called `http.route` which is populated with a route template. For example.

`/abc/{123}/`

These do not appear to be escape properly when I select them from a template variable to query Prometheus/Mimir.

**Comment by klinki** [comment]
That sounds promising, can you share an example please?

I tried this:
```
sum(rate(total_requests{server="$server", environment="$environment", raw_url=~`${raw_url:regex}`}[5m])*60*5)
```

 but it didn't work

**Comment by hannahchan** [comment]
This is currently working for me in this dashboard.

https://github.com/hannahchan/Local-Observability-Stack/blob/956b5ed0bd2b3ad7447c8449e0fea00ce9b532d7/Configurations/Grafana/dashboards/HTTP%20Server%20Metrics.json#L99

Your example above looks valid to me.

**Comment by klinki** [comment]
oh, I had error somewhere else, I fixed it and now it works, thanks!
