### ISSUE TITLE
Design cleanup: Top Nav Arrows

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#5927]
The main menu down arrow and the dashboard down arrow affordances should be aligned:

<img width="429" alt="grafana_-_worldping__home" src="https://cloud.githubusercontent.com/assets/2886187/18067421/5c551112-6e02-11e6-86dc-168d1436e330.png">

Small bit of cleanup, should be simple but havent gotten to look into it yet.

**Comment by bergquist** [comment]
Closing this since the header have been redesigned..
