### ISSUE TITLE
RPM package manager only shows Grafana BETA version as the default choice for installation

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#59283]
**What happened**:

A community user reported an issue on the RPM-based distro. The installer (`yum` or `dnf`) only show beta packages as available to be installed/upgraded on the machine.

**What you expected to happen**:

Should show the current stable package for the installation/upgrade

**How to reproduce it (as minimally and precisely as possible)**:

**Step 1**

Setup the repo by following the [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/installation/rpm/#install-from-yum-repository)

EXTRA STEP

We have added the `exclude=*beta*` in the repo as explained in the doc so the new `grafana.repo` look like this

```
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
exclude=*beta*
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

**Step 2**

Run these 2 commands to be sure that the package manager cache is clean any old data

```
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf clean metada

```

**Step 3**

Build the package manager cache

`[root@localhost ~]# dnf makecache
`

**Step 4**

Install Grafana using the command

```
[root@localhost ~]# dnf install grafana


Last metadata expiration check: 0:13:11 ago on Thu 24 Nov 2022 11:48:37 AM CET.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                               Architecture                            Version                                            Repository                                  Size
===================================================================================================================================================================================================================
Installing:
 grafana                                                               x86_64                                  9.3.0~beta1-1                                      grafana                                     84 M
Installing dependencies:
 chkconfig    
``` 

As you can see that it is installing  **9.3.0~beta1-1**   

**Anything else we need to know?**:

***WORKAROUND***

I found a workaround i.e run this command

`[root@localhost ~]# dnf whatprovides grafana
`
and it will provide a list of packages provided the grafana repo (already sorted by version)

Select the recent one showing just above the beta version i.e.

```
grafana-9.2.6-1.x86_64 : Grafana
Repo        : grafana
Matched from:
Provide    : grafana = 9.2.6-1
```

And install it like this way:

```
[root@localhost ~]# dnf install grafana-9.2.6-1.x86_64
Last metadata expiration check: 0:17:57 ago on Thu 24 Nov 2022 11:48:37 AM CET.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                               Architecture                            Version                                            Repository                                  Size
===================================================================================================================================================================================================================
Installing:
 grafana                                                               x86_64                                  9.2.6-1                                            grafana                                     92 M

```

This way the user can install the latest stable release.

**Environment**: CentOS 9 Stream, Rocky 9, OracleLinux 8.6 
- Grafana version: 9.2.x

**Comment by malcolmholmes** [comment]
@julienduchesne ?

**Comment by julienduchesne** [comment]
I've removed the beta packages from the RPM repository

**Comment by usmangt** [comment]
@julienduchesne Thanks I can confirm that I do not see the beta package anymore. 

But there still seems to be an error with the GPG key just after packages get downloaded and start to install get this:

```
Importing GPG key 0x24098CB6:
 Userid     : "Grafana <info@grafana.com>"
 Fingerprint: 4E40 DDF6 D76E 284A 4A67 80E4 8C8C 34C5 2409 8CB6
 From       : https://rpm.grafana.com/gpg.key
Is this ok [y/N]: y
Rocky Linux 9 - BaseOS                                                                                                                                                             1.7 MB/s | 1.7 kB     00:00    
Importing GPG key 0x350D275D:
 Userid     : "Rocky Enterprise Software Foundation - Release key 2022 <releng@rockylinux.org>"
 Fingerprint: 21CB 256A E16F C54C 6E65 2949 702D 426D 350D 275D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
Is this ok [y/N]: y
Key imported successfully
Key import failed (code 2). Failing package is: grafana-9.2.6-1.x86_64
 GPG Keys are configured as: https://rpm.grafana.com/gpg.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

```

_**WORKAROUND**_

**Step1**
 
sett `gpgcheck=0` in the .repo file `(/etc/yum.repos.d/grafana.repo`)

**Step 2**

then clean the package manager cache 

`dnf clean all `and `dnf clean metadata`

**Step 3**

Build new cache

`dnf makecache
`
**Step 4**

`dnf install grafana
`
Install the grafana and this time it will not give the GPG key error

**Comment by julienduchesne** [comment]
Interesting 🤔. I'm unable to reproduce the failure on my side . Everything works as it should. That's the correct GPG key and it should work for you as well

For info, I installed it on a Fedora docker image:
```
[root@b10b63549fa3 /]# yum --version
4.11.1
  Installed: dnf-0:4.11.1-2.fc36.noarch at Fri May  6 10:10:57 2022
  Built    : Fedora Project at Wed Mar 30 09:53:03 2022

  Installed: rpm-0:4.17.0-10.fc36.x86_64 at Fri May  6 10:10:57 2022
  Built    : Fedora Project at Mon Mar 21 22:49:27 2022
```

**Comment by usmangt** [comment]
I reproduced it on a Rocky Linux 9 docker image.

**Comment by sjansen1** [comment]
On RHEL 9 + Clones, SHA-1 is disabled in the default crypto policy, this also affects gpg package signing keys. If you want to provide packages for EL9+ you need a new gpg signing key using SHA-256 hashes.

**Comment by usmangt** [comment]
> On RHEL 9 + Clones, SHA-1 is disabled in the default crypto policy, this also affects gpg package signing keys. If you want to provide packages for EL9+ you need a new gpg signing key using SHA-256 hashes.

This is a known issue as already reported [here](https://github.com/grafana/grafana/issues/55962#event-7923370045)

**Comment by tleopold** [comment]
Since the original issue has been resolved and the GPG issue is being tracked via a separate issue this issue will be closed.
