### ISSUE TITLE
templating - "Include All option" always starts with "all" selected

### ISSUE THREAD

**Issue by yosefy** [grafana/grafana#5929]
which takes lot of time when it includes big amount of servers
could you pls add "default" option, so it won't choose "all" every time

thanks

**Comment by torkelo** [comment]
if you save the dashboard with something other than All selected it will default to that.

**Comment by yosefy** [comment]
ok thanks

**Comment by prburgu** [comment]
This is still a problem when selecting different value for other template variables. For example, try changing the 'datacenter' in the following dashboard. The 'host' gets selected to 'All'. 

http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by Yajan** [comment]
how to select default value from javascript dashboard?

**Comment by torkelo** [comment]
We the current property (set value and view dashboard json model)

**Comment by Yajan** [comment]
I have got it working by adding this piece of code based on @torkelo suggestion:
```
 current: {
      selected: true,
      text: data[0]['region_name'],
      value: data[0]['region_name']
    },
```
