### ISSUE TITLE
Grafana 9.3.0~beta1-1 RPM from repo has invalid login button

### ISSUE THREAD

**Issue by arnebjarne** [grafana/grafana#59294]
**What happened**:
We use the https://packages.grafana.com/oss/rpm repo to maintain our Grafana installation.
When we upgraded to the latest grafana.x86_64 0:9.3.0~beta1-1 the login button failed to work

**What you expected to happen**:
Button should honour "root_url" in grafana.ini but does not!

**How to reproduce it (as minimally and precisely as possible)**:
We run Grafana on port 3000 and use Apache's mod_proxy to serve grafana on https://ourdomain.com/stats/

When I hoover over the Sign-in in the left menu I get
https://ourdomain.com/?orgId=1&forceLogin=true
where I should get
https://ourdomain.com/stats/?orgId=1&forceLogin=true

Note - if i type in https://ourdomain.com/stats/?orgId=1&forceLogin=true manually, login _do_ work.

**Anything else we need to know?**:
We have downgraded to grafana 9.2.6-1 again and login button is correct again.

**Environment**:
- Grafana version: 9.3.0~beta1-1
- Data source type & version: not relevant
- OS Grafana is installed on: CentOS 7 64-bit
- User OS & Browser: Any
- Grafana plugins: not relevant
- Others: not relevant

BR,
Bjarne

**Comment by usmangt** [comment]
Hi @arnebjarne,

Thanks for reporting this issue.

Let me try to reproduce it by creating such environment and will get back here with new information.

**Comment by zuchka** [comment]
this sounds like the same problem with root_url and serving from sub-path that is described here:

https://github.com/grafana/grafana/issues/58290

@arnebjarne if this looks enough like a duplicate then maybe we should close in favor the existing issue

**Comment by arnebjarne** [comment]
> this sounds like the same problem with root_url and serving from sub-path that is described here:
> 
> #58290
> 
> @arnebjarne if this looks enough like a duplicate then maybe we should close in favor the existing issue

Yes, looks like it.
