### ISSUE TITLE
Alert rule and recording rule creation views are the same despite not having the same features

### ISSUE THREAD

**Issue by RutgerKe** [grafana/grafana#59301]
**What happened**:
I want to make a recording rule, or tell someone to 'go make a recording rule'. I have to click 'alert' four times and go deep into the UI to find the first mention of 'recording'. If you know 'recording rules' exist this is hard to find, and if you don't know about them you'll most likely not stumble upon them while using Grafana and miss out on the functionality.

**What you expected to happen**:
Have some guidance to end up on the right page, some mention of 'recording rule' at an earlier UI? Some alternate flow altogether?

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana with the new `topnav` and navigate to the page to make a recording rule
![createrecordingrule](https://user-images.githubusercontent.com/6214906/203801209-6684408b-a1cc-4beb-8b5a-e1eb5e812155.gif)

**Anything else we need to know?**:
Once you are creating a recording rule, the button to preview the query still says 'preview alerts' (which also seems to not do anything if you click on it? I'd expect some preview of the vlaues)
![image](https://user-images.githubusercontent.com/6214906/203796878-5b0cef50-e8fb-4581-82d2-6d830614743a.png)

This problem existed before, but it has gotten worse with the new UI.

**Environment**:
- Grafana version: Grafana v9.2.5 (042e4d216b)
- Data source type & version: Mimir / Loki
- OS Grafana is installed on: Cloud
- User OS & Browser: Any (using firefox)
- Others: `feature_toggles`, `enable = topnav`

**Comment by RutgerKe** [comment]
Thinking that I might've missed a flow I thought maybe this can be done from the 'explore' page, it does have a button to create 'recorded queries', but that is a [different feature all together](https://grafana.com/docs/grafana/latest/administration/recorded-queries/) (and doesn't seem to work for prometheus queries).
![image](https://user-images.githubusercontent.com/6214906/203803649-f0ad3ffd-f011-4735-b313-f0ff0973191a.png)

Putting it somewhere on explore might be one way to make it more accessible, but there might be other/better ways to fix this.

**Comment by mellieA** [comment]
Part 2 (preview alert) does nothing is a duplicate of https://github.com/grafana/grafana/issues/35699. Leaving this open for the feedback in part 1 (not intuitive to find recording rules).

**Comment by soniaAguilarPeiron** [comment]
maybe @dhalachliyski could take this in account in the new alert rule creation workflow?

**Comment by AndrejKiri** [comment]
I noticed some issues in alerting in version v10.2.0-59761 (65df5a0d). 

When I click on `+ New recording rule`, in the Add rule form you referring to the rule as an `alert rule` multiple times. I guess that is wrong, and it should be a `recording rule`. 

![image](https://github.com/grafana/grafana/assets/4126171/b203a512-6af9-477f-87e9-ed8c929f34b8)

Also, per [UX writing guidelines](https://docs.google.com/document/d/1Vx6EHVDTOpz_sUmM5Mtkx3XTMEj0bHen6mmStnp1IR4/edit#bookmark=id.iccqusgn1go5), the punctuation is unnecessary in the section name. You can remove the dot.
<img width="298" alt="image" src="https://github.com/grafana/grafana/assets/4126171/c8e916ed-1140-44fa-bc9d-d23f11574cf5">

FYI @armandgrillet
