### ISSUE TITLE
[Feat Req]: Highlight and filter out weekends or off work hours in graphs

### ISSUE THREAD

**Issue by gdubicki** [grafana/grafana#5930]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I would be nice to have a setting that would enable showing weekends in the graphs with a slightly different background (lighter or darker one).

**Comment by alx8** [comment]
Were also looking for same feature, is there any planning for such?

Thanks

**Comment by steffenknott** [comment]
I think this would really add a lot of usability. We encounter a lot of effects that occur on weekends and with the weekends highlighted interpreting the charts would become much more convenient.
Thinking about it, the same is true for showing "office hours" in the chart.
Thanks for all your amazing work!

**Comment by lyoungblood** [comment]
+1 on this feature - Zabbix has had the ability to highlight weekends/nights for some time in graphs; it would be great to see this in Grafana.

**Comment by shalstea** [comment]
+1

**Comment by ekote** [comment]
+1

**Comment by jpbaudoin** [comment]
+1

**Comment by twistedatoms** [comment]
+1

**Comment by raynix** [comment]
Good to be able to highlight some time periods with different background color

**Comment by edurivara** [comment]
+1

**Comment by zemek** [comment]
+1

**Comment by sekhavatosan** [comment]
As described in https://github.com/flot/flot/issues/513#issuecomment-20669253, it seems that "filter out" feature can be implemented by explicitly passing `ticks` array instead of passing ticks count for flot: https://github.com/grafana/grafana/blob/513434cadaea15d6df3bdbf7d26af49d254a7a8c/public/app/viz/Graph.tsx#L73-L80.

**Comment by sekhavatosan** [comment]
@marefr Should I create a new issue?

**Comment by marefr** [comment]
@sekhavatosan please do if you haven't already done that
