### ISSUE TITLE
Explore flaky E2E: explore.spec.ts

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#59315]
We have run a set of builds to detect E2E and this specific E2E has failed 3/40 times. Our goal is to have a 100% of success in tests to make sure they don't break the build and they are 100% reliable.

We suggest skipping the tests as the first step until the bug is solved.

**Errored builds because of this failure**
_Recordings S3 URL can be found in `e2e-test-artifacts-upload` build step of the errored build_
* https://drone.grafana.net/grafana/grafana-private-mirror/3338/6/23 
* https://drone.grafana.net/grafana/grafana-private-mirror/3318/6/23
* https://drone.grafana.net/grafana/grafana-private-mirror/3296/6/23

**Comment by aocenas** [comment]
@grafana/observability-experience-squad seems like the test mostly failing here is actually the Explore one so moving to your project.

**Comment by Elfo404** [comment]
@aocenas https://drone.grafana.net/grafana/grafana-private-mirror/3338/6/23 and https://drone.grafana.net/grafana/grafana-private-mirror/3318/6/23 are about the trace view lazy loading

**Comment by aocenas** [comment]
Well yeah but both also fail on the explore test:
![Screenshot from 2022-12-13 11-06-44](https://user-images.githubusercontent.com/1014802/207288769-a45d2cd0-6267-4414-89ca-d96c3a695c87.png)

I created a separate issue for the traceView test https://github.com/grafana/grafana/issues/60214

**Comment by Elfo404** [comment]
👍 didn't know about the other issue, my bad!
