### ISSUE TITLE
Using Single Stat with Elastic Search

### ISSUE THREAD

**Issue by mayankdevops** [grafana/grafana#5932]
**_Facing some issues with Single Stat panel with Elastic Search._**

- What Grafana version are you using? - **grafana-3.1.1.windows-x64**
- What datasource are using? - **Elastic Search 2.3.5**
- What OS are you running grafana on? - **Windows 7 Enterprise**
- What did you do? - 

Created a Sample index and some data in elastic search. Please find the json dump below.
Please find the json responses attached.

- http://localhost:9200/sample-index
[indexMeta.txt](https://github.com/grafana/grafana/files/444962/indexMeta.txt)
- http://localhost:9200/_search?q=*
[ElasticSearchIndexData.txt](https://github.com/grafana/grafana/files/444963/ElasticSearchIndexData.txt)

Created the sample panel using table. Please find the screen shot attached below.
![capture](https://cloud.githubusercontent.com/assets/11787440/18090468/8252844a-6ee2-11e6-8fc6-a1107ef3cab3.PNG) 
The above image is just to get some relevance with data.
Now what we are looking for is to use single stat panel with same set of data and get unique count of name.
Like from the above image at 2016-08-24 05:30:00 we have the count of occurrences for Anshul, Mayank, Priyanka and Vishal. We are trying to unique single digit number in single stat like 4 in this case. Not able to get that from single stat panel.

**Comment by torkelo** [comment]
why is it not working with singlestat? What's the query you have and ES response? what is you singlestat options?
