### ISSUE TITLE
Error moving variable up or down

### ISSUE THREAD

**Issue by lushaorong** [grafana/grafana#59326]
**What happened**:
 >When I move the order of variables, disorder may occur

**What you expected to happen**:
>Displayed in the order of movement

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/16489768/203885036-b7084e39-3d35-480c-bfe9-fc0497cc0483.png)
move a variable up or down the list using drag and drop.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.5
- Data source type & version: Altinity plugin for ClickHouse
- OS Grafana is installed on: docker
- User OS & Browser: chome
- Grafana plugins:
- Others:

**Comment by lushaorong** [comment]
![chrome-capture-2022-11-1](https://user-images.githubusercontent.com/16489768/204979412-487ea78d-c5df-4172-b10d-7eb0ee83372e.gif)

- chrome:107.0.5304.122
- I didn't find it in other browsers

**Comment by lushaorong** [comment]
> 



> ![chrome-capture-2022-11-1](https://user-images.githubusercontent.com/16489768/204979412-487ea78d-c5df-4172-b10d-7eb0ee83372e.gif) [ ![chrome-capture-2022-11-1](https://user-images.githubusercontent.com/16489768/204979412-487ea78d-c5df-4172-b10d-7eb0ee83372e.gif) ](https://user-images.githubusercontent.com/16489768/204979412-487ea78d-c5df-4172-b10d-7eb0ee83372e.gif) [ ](https://user-images.githubusercontent.com/16489768/204979412-487ea78d-c5df-4172-b10d-7eb0ee83372e.gif)
> 
> * chrome:107.0.5304.122
> * I didn't find it in other browsers

I tried to upload gif, but failed

**Comment by tonypowa** [comment]
Hi @lushaorong 

It looks like a local issue

Do you still experience this behavior? Have you tried clearing the browser's cache? 

If you still do, please update Chrome to latest version, clear cache, log out and log in back into Grafana and try again
