### ISSUE TITLE
Horizontal BarChart has too many tick marks to fit the X-axis

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#59332]
**What happened**:
On a horizontal bar chart with automatic maximum and number of decimals, the tick value labels are not spaced sufficiently anymore.
**What you expected to happen**:
I expect the chart to use not more tick marks than labels than would fit along the axis and be still readable.

**How to reproduce it (as minimally and precisely as possible)**:
I have a simple table with two rows (series) and two data columns:
![image](https://user-images.githubusercontent.com/11174694/203946941-2ccd0e7f-ea10-4fbc-a5a5-4cfdd0a1c28d.png)

The stacked bar has unit defined as "MB" (as the input data is in MB) and thus needs to cover the maximum of 5.5 GB (properly rounded to 6 GB). The display shows the labels running into each other, or positioned just too close.

![image](https://user-images.githubusercontent.com/11174694/203945709-fea052ab-8297-447f-adaf-bcaf015eedb1.png)

**Anything else we need to know?**:
I know that scaling with MB and GB can be a challenge since the number of digits varies, and depends on the position in the scale. Maybe the code didn't account for the "MB" suffix (it looks slightly better when I change the unit to "bytes" - though obviously incorrect) but then the labels are overdone with something like "500.0 B". I don't want to set the decimals to 0 because for a lower maximum it results in multiple tick labels with the same value.
When dealing with these 1024 scaling factors, I really don't know what 4.75 GB is; when the number of ticks is reduced, you might avoid those intermediates already. 

PS I tried whether Log2 scale worked better; in a way it is because there are less ticks. It starts nicely with 8 and 16 MB, but then comes up with ticks at 2.05 GB or 8.19 GB...  But I'm delighted to see something like that just work, and understand whether this is more useful as visualization (tough call because it does make it easier to see the small ones, but hides the fact than those are peanuts and there's one huge group).

![image](https://user-images.githubusercontent.com/11174694/203952977-8514e07d-94d4-46bf-aac9-3afd970ece8c.png)

**Environment**:
- Grafana version: 8.5.1
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: RHEL 9.1
- User OS & Browser: RHEL & Chrome
- Grafana plugins: n/a
- Others:

**Comment by leeoniya** [comment]
yeah, this one is tricky to get right, since properly choosing non-colliding ticks then requires measuring rendered labels...which depend on the chosen ticks / scale range...and so on goes the chicken/egg situation. we can maybe provide a way to omit tick _labels_ similar to what we have for the category axis. it's crude, but effective and doesnt eat into rendering perf:

![image](https://user-images.githubusercontent.com/43234/204069972-8cb58520-19b7-45ed-a069-45fe57897494.png)

**Comment by rvdheij** [comment]
Thanks, I'll keep an eye on when I pick up the fix. If I find the logic again that I did in the past, I'll make it a feature request.

**Comment by codebude** [comment]
Another useful solution would be adding a parameter "step size resolution" which could set up/down the amount of shown labels/ticks on the horizontal axis.

**Comment by rvdheij** [comment]
I'm not sure a parameter does the trick. Because I have systems with data in a very wide range (difference between small and large can be 3 orders of magnitude) I avoid specifying a maximum (so the scale adapts to the system usage) and I wouldn't want to specify the major tick distance either. What could work is a parameter to specify you want 10 tick marks, for example. But whether that works depends on the size of the panel and size of font. To make things worse, what might work with a scale of 0-9 wouldn't work well with single digit labels, but doesn't fit on  0-900 MB because the labels take much more room.
A logarithmic scale is for when the value differ between series (e.g. a 4 GB flash drive and a 2 TB SSD). When dealing with log2 scale, you'd try to evenly space on the log scale, but still at round numbers (e.g. 1, 2, 4, 8) and with data units you have that 1024 scaling as well. It's just not trivial.

**Comment by leeoniya** [comment]
> It's just not trivial.

this is painfully true, for at least all the reasons you mention. this doesnt even begin to cover how to choose the correct scale range, soft and hard scale limits, desired tick decimals, axis and plot padding auto-sizing, tick label rotation, and so on!

either the solution is imperfect for all cases and the complexity is somewhat manageable, or the complexity is unmanageable...and it's still imperfect!

that being said, i'm working towards an improvement in the core plotting lib that should help. it's a strategy which logarithmically scales up tick count based on the  axis length. the scaling factor will be user adjustable, effectively exposing control over the tick density. we can then omit any colliding labels. how and when this will trickle up through the grafana panel options ui remains to be decided.

it's one of those problems that feels trivial in isolation for a specific use case or value range, but a general solution that supports various additional features and options without ever falling apart is a different beast.
