### ISSUE TITLE
Grafana last 5 minutes not showing correctly

### ISSUE THREAD

**Issue by hostingwalk** [grafana/grafana#5933]
- Graphite  /  Ubuntu  (  Grafana v3.1.1 )

-  I use Grafana with Graphite but it not showing good on short time-frames like 5 or 15 minutes (misses some times.)

![352cbfe14cb5427ca918c894471d829a](https://cloud.githubusercontent.com/assets/9915051/18091092/c89b5140-6ec7-11e6-9598-7913e149a493.png)

anyone know where maybe the problem can be ? if i select 30 minutes or 1 hours or 1 week/month it just showing everything.

**Comment by pawellesniewski** [comment]
Do you have these datapoints in Graphite for this period of time? Try to fetch data from Graphite via api (/render/?target=metric&format=json) and compare.

**Comment by hostingwalk** [comment]
I hope if i can hire somebody for it please add me on Skype: hostingwalk

**Comment by torkelo** [comment]
Maybe your browser time is not in sync with graphite server time?

**Comment by hostingwalk** [comment]
Difference between server and PC time 	10 seconds 
Is there someone who can help via Skype or E-mail ? (paid)
