### ISSUE TITLE
Alerting: $__to and $__from does not work in alert rules 

### ISSUE THREAD

**Issue by LukasJerabek** [grafana/grafana#59330]
**What happened**:
I am trying to set up new alert rule. 

```
SELECT
    start_time as "time",
    duration
FROM cronscript_duration_ts
WHERE
  start_time between $__from and $__to
GROUP BY 1
ORDER BY 1
```

Then I get error in upper right corner of the window:

> Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: db query error: pq: syntax error at or near "$"

I know I could have used $__timeFilter(start_time) in this example but I have just made a smallest example possible to show the problem, in reality I need those elsewhere.
The point is just that they dont work.
I have tried '${__to}' and ${__to} and '$__to' as well, nothing works.

**What you expected to happen**:
I have expected that the variables would give the "from" and "to" time.

**How to reproduce it (as minimally and precisely as possible)**:
create a table, use a query.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- 9.2.2 (also tested on 9.2.6 with same result)
- Data source type & version: Postgres 14 timescaledb 2.8.1
- OS Grafana is installed on: rocky linux
- User OS & Browser: ubuntu, brave
- Grafana plugins: marcusolsson-dynamictext-panel
- Others:

**Comment by tonypowa** [comment]
Hello @LukasJerabek 

Thank you for your question. However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on https://community.grafana.com/

**Comment by LukasJerabek** [comment]
Hello @tonypowa how is this not a bug?

**Comment by LukasJerabek** [comment]
According to the documentation this should work https://grafana.com/docs/grafana/v9.0/variables/variable-types/global-variables/

**Comment by zuchka** [comment]
Hi @LukasJerabek,

Happy to reopen this. But could you please include some more info and more thorough reproduction steps. Having trouble reproducing this on our end:

1. Can you confirm that you are using the new Grafana Alerting platform and not the legacy alerting platform
2. Is this error reproducible with other datasources, or just the Postgres datasource?
3. can you try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to `debug` and note any errors. For printing to console, [set the console logs to `debug`](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) as well.

**Comment by LukasJerabek** [comment]
to reproduce:
```
CREATE TABLE asdf (
    start_time timestamp with time zone NOT NULL,
	somenumber integer NOT NULL
);
insert into asdf (start_time, somenumber) VALUES (now(), 1);
insert into asdf (start_time, somenumber) VALUES (now()+interval '1 second', 10);
insert into asdf (start_time, somenumber) VALUES (now()+interval '2 seconds', 8);
insert into asdf (start_time, somenumber) VALUES (now()+interval '3 seconds', 6);
insert into asdf (start_time, somenumber) VALUES (now()+interval '4 seconds', 5);
insert into asdf (start_time, somenumber) VALUES (now()+interval '5 seconds', 11);
```
After that I can go to explore and use this query and get results:
```
SELECT
    start_time as "time",
    somenumber
FROM asdf
WHERE
  start_time > '${__from:date}'
GROUP BY 1,2
ORDER BY 1
```
but when I go to Alerting->Alert rules and create new alert and use the same query I get: 

> Error
> Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: db query error: pq: invalid input syntax for type timestamp with time zone: "${__from:date}"

Thats because it does not write the variable in and uses the exact string.

If I switch the where condition to 
`start_time > $__from:date `
I get:
> Error
> Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: db query error: pq: syntax error at or near "$"

Thas because it does not recognize the variable at all.

If I switch the where condition to
`$__timeFilter(start_time)`
it works.  But it should also for above $__from variable. Same applies for $__to.

1. I am not sure what you mean by new and legacy alerting platforms. I simply go to Alerting->Alert rules and create new alert rule in grafana version 9.2.2 or 9.2.6 installed by dnf. If new is default, then I am probably using  the new one.
2. I dont have any other datasource, so I dont know...
3. tried, looked into logs, but does not find anything suspicious:
```
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=accesscontrol.service t=2022-11-29T22:28:54.108514914+01:00 level=debug msg="fetch permissions from store" key=<somekey>
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=accesscontrol.service t=2022-11-29T22:28:54.109964947+01:00 level=debug msg="cache permissions" key=<somekey>
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=accesscontrol.evaluator t=2022-11-29T22:28:54.110435977+01:00 level=debug msg="matched scope" userscope=<someuserscope> targetscope=<sometargerscope>
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=datasources t=2022-11-29T22:28:54.110654884+01:00 level=debug msg="Querying for data source via SQL store" uid=<someuid> orgId=<orgid>
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=secrets.kvstore t=2022-11-29T22:28:54.111735571+01:00 level=debug msg="got secret value" orgId=<orgid> type=datasource namespace=PostgreSQL-roger
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=context userId=<userid> orgId=<orgid> uname=<username> t=2022-11-29T22:28:54.113982681+01:00 level=error msg="Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: db query error: pq: syntax error at or near \"$\"" error="Failed to evaluate queries and expressions: failed to execute conditions:  failed to execute query A: db query error: pq: syntax error at or near \"$\"" remote_addr=<remote_addr>traceID=
lis 29 22:28:54 <hostname> grafana-server[3558929]: logger=context userId=<userid> orgId=<orgid> uname=<username> t=2022-11-29T22:28:54.114133579+01:00 level=info msg="Request Completed" method=POST path=/api/v1/eval status=400 remote_addr=<remote_addr>time_ms=7 duration=7.805499ms size=177 referer="http://<hostname>/alerting/new?returnTo=%2Falerting%2Flist" handler=/api/v1/eval
```

**Comment by zuchka** [comment]
have you tried the [macros that are specific to Postgres](https://grafana.com/docs/grafana/v9.3/datasources/postgres/#macros)? `$__timeFrom()` and `$__timeTo()` are pretty similar.

it also says in the global variables docs that `$__timefilter` is uses [specifically in SQL queries](SQL queries in MySQL, Postgres, and MSSQL.).

I will forward this to alerting team to see about the compatibility of the `$__to` and `$__from` variables. That might need a docs change, be a bug, or I'm missing something entirely. I see those two vars used in datalinks a lot--not so much in queries, where users tend to stick to datasource specific time macros like the ones listed on the postgres page, [these for influx](https://grafana.com/docs/grafana/latest/datasources/influxdb/query-editor/#use-macros), etc

**Comment by LukasJerabek** [comment]
You are right... I totally missed that there are datasource specific macros. Thank you, that works...

**Comment by JacobsonMT** [comment]
Seems like a solution has been found, going to close. Feel free to reopen if the issue persists.
