### ISSUE TITLE
Explore Loki query builder uses escape on backtick strings

### ISSUE THREAD

**Issue by gkloss** [grafana/grafana#59333]
**What happened**: If you click on the magnifier in the Explore page the value of the label gets escaped and put inside backticks.

![image](https://user-images.githubusercontent.com/73476012/203965436-caf0bf4d-282b-43f7-bf94-8efeae9388a4.png)

result query 

```
{app !="", level=~"error|warning", machineName="server"} | json | user=`DOMAINNAME\\USERNAME` | line_format "{{.app}}@{{.machineName}} : {{.t}} IP:{{.remoteAddr}}\n{{.user}}"
```

**What you expected to happen**: either use quotes or disable escaping.

**How to reproduce it (as minimally and precisely as possible)**: make a loki query and click on magnifier next to log lable with special characters 

**Environment**:
- Grafana version: 9.2.6
- OS Grafana is installed on: Windows Server 2019
- Others: loki, version HEAD-1b627d8 (branch: HEAD, revision: 1b627d880)
  build user:       root@079d888186e6
  build date:       2022-11-10T23:52:44Z
  go version:       go1.19.2
  platform:         windows/amd64

**Comment by svennergr** [comment]
Hi @gkloss,

thanks again - a fix was merged and will be released with the next v9.3.x version.

Best,
@svennergr
