### ISSUE TITLE
No data interpreted as error with ADX time series

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#59348]
1. Create an Alert Rule with a query returning no data (but otherwise valid), e.g. based on time frame condition.
```kusto
grafana
| make-series Value=avg(Value) on Time from $__timeFrom to $__timeTo step 1min by TagName
| project-rename Timestamp=Time
```
2. Set state on no data to Alerting.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/4903007/204121003-928b1165-e1cc-454c-92ef-98d2f007e456.png">
3. Check rule state

### Expected
Firing

### Actual
Normal

<img width="995" alt="image" src="https://user-images.githubusercontent.com/4903007/204121204-c4f27d09-ae45-48f6-ba8f-97426e5a8aff.png">

Error also can be seen in rule edit mode:

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/4903007/204121331-96236a8a-4dff-437f-9b8c-028ca5caaeaa.png">

### Environment
- Grafana version: Cloud
- Data source type & version: Azure Data Explorer v4.1.6
- OS Grafana is installed on: N/A
- User OS & Browser: MacOS, Chrome
- Grafana plugins: Azure Data Explorer v4.1.6

**Comment by mellieA** [comment]
@greatvovan what would the query result look like if there were data? It sounds like it's not using the correct **format** for the query or a reduce expression might be needed to return the expected value for alerting to evaluate.

**Comment by greatvovan** [comment]
@mellieA like I said the query is otherwise valid and works with charts, alerts, and Explore, if there is data. If there is no data, it works with charts and Explore, but not with Alerting.

Example output (_ADX Time series_):

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/4903007/205217500-349b404e-7317-415a-aba0-435743ccda26.png">

It successfully interprets the received data:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/4903007/205220608-1e206cd7-419d-4444-9744-405a0f34207d.png">

If time range is such that there is no data, it shows "No data", but additionally posts the error shown in the initial post.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4903007/205220087-f8ccad9a-086f-4ca1-80b3-be233428cb7b.png">

A reduce expression does exist, and also shows "No data":

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4903007/205220306-fb204ab3-2d1f-4b55-b59f-f7307e1a89e1.png">

But the final state of the alert evaluates to "Error":

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4903007/205220432-ea6d74e1-0d53-4adf-ba1e-5dc022f542b0.png">

**Comment by greatvovan** [comment]
You can play on your own with the following ad-hoc query:

```kusto
let ts = range Timestamp from ago(20m) to ago(6m) step 1m | extend dummy = 1;
let tags = datatable(tag: string)["TAG_001", "TAG_002", "TAG_003"] | extend dummy = 1;
ts | join kind=inner tags on dummy
| extend value = rand()
| sort by Timestamp asc
| make-series value=avg(value) default=real(null) on Timestamp from $__timeFrom to $__timeTo step 1m by tag
```

If you select more than last 5 minutes in the date picker, it will work. If you select last 5 minutes or less, it will throw error.

It emulates the situation when data stopped coming for a while, which can be a variant of normal.

Note that output of `make-series` always includes all bins in _Timestamp_ column, **but** only in case there is some data in the specified range, otherwise it returns no rows (instead of enumerating all bins with `null` value.

**Comment by andresmgot** [comment]
I can reproduce this. I have seen the same behavior in other plugins, even if the response has no rows, we are still returning a frame with some metadata, which Alerting does not support. I'll send a fix.

**Comment by greatvovan** [comment]
Was there a release with that change? I see the merge is quite fresh.

**Comment by andresmgot** [comment]
hi @greatvovan, no it has not been released yet (there is no release planned for this holidays season). In the meantime, you can grab the artifacts generated by the CI with the fix included:

[drone_grafana_azure-data-explorer-datasource_main_683_packages_grafana-azure-data-explorer-datasource-4.1.10.linux_amd64.zip](https://github.com/grafana/grafana/files/10285169/drone_grafana_azure-data-explorer-datasource_main_683_packages_grafana-azure-data-explorer-datasource-4.1.10.linux_amd64.zip)
[drone_grafana_azure-data-explorer-datasource_main_683_packages_grafana-azure-data-explorer-datasource-4.1.10.windows_amd64.zip](https://github.com/grafana/grafana/files/10285175/drone_grafana_azure-data-explorer-datasource_main_683_packages_grafana-azure-data-explorer-datasource-4.1.10.windows_amd64.zip)
