### ISSUE TITLE
Grafana Ldap Integration

### ISSUE THREAD

**Issue by mayankdevops** [grafana/grafana#5934]
* **I'm submitting a ...**
- [ ] Bug report
For Grafana and Ldap integration.

Please include this information:
- What Grafana version are you using?grafana-3.1.1.windows-x64
- What datasource are you using?Elastic Search 2.3.5
- What OS are you running grafana on? Windows Server 2012 R2
- What did you do? 
We updated the defaults.ini

###############Auth LDAP ###############
[auth.ldap]

enabled = true

config_file = /path/to/ldap.toml
###############Auth LDAP ###############
Please find the my ldap.toml also attached.
[ldap.txt](https://github.com/grafana/grafana/files/445029/ldap.txt)

LDAP authentication doesn't seem to work properly in my environment when using userPrincipalName or samaccountname as the value of username

Logging in with userPrincipalName or  samaccountname set as username works for the first time (ie, before the user exists in Grafana's database), but not on subsequent login attempts.

Also if other users tries to login with their credentials, they are too not able to login even though they are logging for the first time. (only one logon in working via ldap across all users)

I am getting following error in log file:
t=2016-08-30T18:33:26+0530 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.login"

t=2016-08-30T18:33:26+0530 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=127.0.0.1 time_ns=13ns size=53

sometimes i get error="UNIQUE constraint failed: user.login"
and sometimes error="UNIQUE constraint failed: user.email"

this is the response which is sent on the second time login/or other user login which i got from network->response screen:
{"user":"xyazbc","email":"","password":"564372@2"}

here if we see empty data in email field is sent to the ldap from grapana. I am wondering If my ldap is not returning the email then how does it works on the first logon??

@torkelo

**Comment by torkelo** [comment]
Try changing the email address ldap property name, have you looked in your ldap?  Is there an email field there?

**Comment by mayankdevops** [comment]
Yes, it has the email field. And ldap property name is also correct. If that was not the case how is it able to authenticate via Ldap the first time.

**Comment by torkelo** [comment]
The email from ldap is blank, do I think not.

**Comment by claire-w** [comment]
I am experiencing exactly the same issue. One ldap login is allowed across all users, afterwards it fails with the error "UNIQUE constraint failed: user.email".

**Comment by greck** [comment]
I was having a similar issue, and resolved it by using ldapsearch(1) with the bind_dn, and then using the results to properly map them to Grafana's needs in the [server.attributes] section of ldap.toml. E.g. I have

    [server.attributes]
    username="uid"
    email="mail"
    ...

to match our schema vs. the defaults. Everything working as expected now.

**Comment by troyygan** [comment]
I got the same issue. 

t=2017-03-04T16:08:07+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.login"

**Comment by willemdh** [comment]
I'm also experiencing the same issue:

Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.email

**Comment by willemdh** [comment]
Fyi I managed to 'solve' the isssue by deleteing the user in the global admin users section. No idea what suddenly caused this though.

**Comment by infinityminglei** [comment]
I am also experiencing the same issue. Any idea on how to fix this issue?

**Comment by willemdh** [comment]
The only solution I found to this problem was to remove and re-add the user.

**Comment by vkakhnych** [comment]
Got the same issue:

> t=2017-09-19T03:06:31-0400 lvl=info msg="LDAP: Searching for user's groups: [(&(objectClass=posixGroup)(memberUid=vkakhnych))]"
> t=2017-09-19T03:06:31-0400 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc8201332d0)({\n DN: (string) (len=45) \"uid=vkakhnych,ou=People,dc=<censored>,dc=com\",\n FirstName: (string) (len=6) \"Viktor\",\n LastName: (string) (len=8) \"Kakhnych\",\n Username: (string) (len=9) \"vkakhnych\",\n Email: (string) (len=31) \"viktor.kakhnych@<censored>.com\",\n MemberOf: ([]string) (len=2 cap=2) {\n  (string) (len=3) \"eng\",\n  (string) (len=4) \"crit\"\n }\n})\n]"
> t=2017-09-19T03:06:31-0400 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=1 uname= error="UNIQUE constraint failed: user.email"

Removed local grafana account but it still doesn't work. As you can see grafana gets correct email from LDAP.

**Comment by vkakhnych** [comment]
Oh, it is not LDAP related. The same when I create invite and trying to use it to re-create my local account.

**Comment by vkakhnych** [comment]
Figured out. Just replace my email from viktor.kakhnych@<censored>.com to vkakhnych@<censored>.com and it works. Something wrong with grafana email parsing algorithm. Dots before @ not allowed?
