### ISSUE TITLE
@grafana/ui Unused generic type parameter in Segment Components

### ISSUE THREAD

**Issue by DiamondMofeng** [grafana/grafana#59341]
**What happened**:

[SegmentProps](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Segment/types.ts) and some other Segment components have an unused generic type parameter.

I am developing a datasource plugin and using grafana's component liberay. This generic type parameter makes me very confused, as none of Segment components uses it actually.

For example, [SegmentInput.tsx](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Segment/SegmentInput.tsx) has a generic type parameter `T` but not using it. This makes me very confused as the type of its `value` was hard coded as `string | number`.

**What you expected to happen**:

Remove these unused generic type parameter, or find the place where should they be used.

**Comment by wx1322** [comment]
I would like to work on this Issue

**Comment by DiamondMofeng** [comment]
> I would like to work on this Issue

Do you have any good ideas on this issue? Besides, could you leave this issue to me? I'd also like to contribute to grafana.

**Comment by wx1322** [comment]
> > I would like to work on this Issue
> 
> Do you have any good ideas on this issue? Besides, could you leave this issue to me? I'd also like to contribute to grafana.

yes

**Comment by DiamondMofeng** [comment]
Currently there are 3 components that use [`SegmentProps`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Segment/types.ts): `SegmentInput`, `SegmentSelect` and `SegmentAsync`.

 `SegmentInput` dose not need that type parameter, so we can remove the type parameter in `SegmentProps` and `SegmentInput`, then add independent type parameters in `SegmentSelect` and `SegmentAsync`

This would not be a breaking change, since only inner types were changed, nor the exposed types.
