### ISSUE TITLE
Multi-dimensional alert reduce is giving broken results on postgres datasource

### ISSUE THREAD

**Issue by LukasJerabek** [grafana/grafana#59357]
**What happened**:
Following [grafana rule guide](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/) I am trying to set up multidimensional rule and I have in my A query:

```
SELECT
    $__time(start_time),
    name as metric,
    EXTRACT(epoch FROM duration) as duration
FROM cronscript_duration_ts
WHERE
  $__timeFilter(start_time) and duration is not null
ORDER BY 1 , 2, pid
```
I have in Reduce expression this:
> Operation: Reduce, Function: Max, Input: A, Mode: Strict

I have in Math expression this:
> $B > 20

but when I pres "preview alerts" I get:
> Error "invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}"

When I examine reduce results I see only B's in dropdown and no data.
![image](https://user-images.githubusercontent.com/55019231/204158754-1e5041a1-299f-4da1-9478-e4fe47b54450.png)

**What you expected to happen**:
Reduce gives resulting max value for each metric.

**How to reproduce it (as minimally and precisely as possible)**:

I have a simple table in postgres called cronscript_duration_ts that  has start_time, name, pid, end_time, duration columns. Duration is interval type, but I tranform it in my query to integer.

```
CREATE TABLE cronscript_duration_ts (
        start_time timestamp with time zone NOT NULL,
	name text NOT NULL,
	pid integer NOT NULL,
	end_time timestamp with time zone,
	duration interval
);
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.6
- Data source type & version: Postgres 14
- OS Grafana is installed on: Rocky linux
- User OS & Browser: Ubuntu, brave
- Grafana plugins: marcusolsson-dynamictext-panel
- Others:

**Comment by LukasJerabek** [comment]
Well I think I figured it out. It should be stated in documentation that metric alias must not be used (if that is actually intentional). It seams just natural to use a metric alias analogicaly to when one creates a panel with multiple series...

**Comment by mellieA** [comment]
@LukasJerabek can you share what is working for you now that you've found a workaround? I'm curious if it is expected or not

**Comment by LukasJerabek** [comment]
Replaces this
`name as metric,`
For
`name as anyotheralias,`

**Comment by armandgrillet** [comment]
This is already documented in the MySQL datasource docs: https://grafana.com/docs/grafana/latest/datasources/mysql/#time-series-queries

> For backward compatibility, there’s an exception to the above rule for queries that return three columns including a string column named metric. Instead of transforming the metric column into field labels, it becomes the field name, and then the series name is formatted as the value of the metric column. See the example with the metric column below.

**Comment by LukasJerabek** [comment]
I don't think this is solved until its in postgres source documentation as well or somewhere in general, or should I always check MySQL docu when I search something for postgres?
