### ISSUE TITLE
Dashboard list is not showing on small screen

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#59351]
The dashboard list control disappears on the smartphone screen in landscape mode:

![image](https://user-images.githubusercontent.com/4903007/204125217-aa29ee93-9136-453b-9403-d90ad7473aeb.png)

While landscape mode is generally more preferable on a smartphone, this issue may make user frustrate, as it seems like no dashboards available.

**Expected**:
The control is shown and allows to scroll through the list.

**Environment**:
- Grafana version: Cloud
- User OS & Browser: iOS 16.1.1 & Chrome 107.0.5304.101
- Device: iPhone SE 2020
- View port size: 667px x 375px

Please note that the issue is not reproducible in Desktop Chrome with dev tools, probably because it skips all browser panels and assumes full screen mode. There is "semi-full-screen" mode in Chrome, but it can be activated when scrolling content up, which is not possible in this case as there's nothing to scroll.

**Comment by tonypowa** [comment]
Hello @greatvovan . Thank you for creating this issue

Before i can forward this issue and this another issue that you have reported to our User Essential's team, could you please provide the following details:

- device's OS version: 
- viewport size: (see how to calculate it [here](https://stackoverflow.com/questions/37481224/how-to-calculate-viewport-width-based-on-device-specification))
- specific device's browser version:

**Comment by greatvovan** [comment]
@tonypowa I updated the initial post, please take a look.

**Comment by tonypowa** [comment]
thank you @greatvovan  i am adding the User Essential's team. 
For better visibility, i am pasting the requested device info bellow:


    Grafana version: Cloud
    User OS & Browser: iOS 16.1.1 & Chrome 107.0.5304.101
    Device: iPhone SE 2020
    View port size: 667px x 375px

**Comment by L-M-K-B** [comment]
This is related to [#83570](https://github.com/grafana/grafana/issues/83570). Fixing the other issue may help with this one.

**Comment by Clarity-89** [comment]
I think this was fixed by removing the filters, or maybe just by enabling the new browse dashboards by default:

![Image](https://github.com/grafana/grafana/assets/8878045/b4cb6c26-446c-44c7-be37-7fa25d072790)

**Comment by tskarhed** [comment]
There is no single PR that will fix this issue, but we're making incremental improvements to this. With `bodyScrolling` the URL bar will hide on mobile (rolled out 100% on Grafana Cloud at the moment, expecting to hit OSS in a couple of weeks). We are about to start some work to only have a single top bar, which will free up some space.
