### ISSUE TITLE
Hover panels overlap useful content in mobile browsers

### ISSUE THREAD

**Issue by greatvovan** [grafana/grafana#59350]
The panels that are supposed to appear on mouse hover in desktop browsers, when on mobile, appear on tap.

![image](https://user-images.githubusercontent.com/4903007/204122449-493daa21-c3da-4e65-af20-cfb708b4480f.png)

![image](https://user-images.githubusercontent.com/4903007/204122438-66a480c2-2ad9-4265-84ce-0957e5c2f7a9.png)

After appearing, they overlap controls underneath and do not allow to use them. Thus, it is very tricky to tap on the date picker or magnifying glass on the first screenshot and it is an annoyance on the second screenshot.

**Expected behaviour:**
Disable hover panels on mobile version, as there is no hover event.

**Environment**:
- Grafana version: Cloud
- User OS & Browser: iOS 16.1.1 & Chrome 107.0.5304.101
- Device: iPhone SE 2020
- View port size: 375px × 667px

Please note that the issue is not reproducible in Desktop Chrome with dev tools, the hover panel does not appear on tap.

**Comment by tonypowa** [comment]
hello @greatvovan 

As requested on your [other issue](https://github.com/grafana/grafana/issues/59351), and just to make sure we are working with the same info, please provide the following:

- device's OS version:
 - viewport size: (see how to calculate it [here](https://stackoverflow.com/questions/37481224/how-to-calculate-viewport-width-based-on-device-specification)):
  - specific device's browser version:
  
  Thank you

**Comment by greatvovan** [comment]
@tonypowa I updated the initial post, please take a look.

**Comment by tonypowa** [comment]
thank you @greatvovan  i am adding the User Essential's team. 
For better visibility, i am pasting the requested device info bellow:


    Grafana version: Cloud
    User OS & Browser: iOS 16.1.1 & Chrome 107.0.5304.101
    Device: iPhone SE 2020
    View port size: 667px x 375px
