### ISSUE TITLE
[Bug] Selecting single template multi value causes unnecessary curly braces in graphite queries

### ISSUE THREAD

**Issue by malinoff** [grafana/grafana#5936]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
> What Grafana version are you using?

Grafana v3.1.1 (commit: a4d2708) 

> What datasource are you using?

Graphite

> What OS are you running grafana on?

Doesn't matter, but in my case - Ubuntu/docker image

I have several variables defined in a template like this (assuming pattern `collectd.<project_env>-<project_name>-<server_type>-<server_num>`):

name: project_name
query: `collectd.*-*-*-*`
regex: `/^[a-zA-Z]*-([a-zA-Z]*)-[a-zA-Z]*-[0-9]*$/`

name: project_env
query: collectd.*-$project_name-*-*
regex: `/^([a-zA-Z]*)-[a-zA-Z]*-[a-zA-Z]*-[0-9]*$/`

and similar query/regexes for other variables. All variables have "multi-value" and "Include All option" selected.

A dashboard with these variables works perfectly on grafana 2.6, but fails on 3.1.1. For some reason when I select exactly one `project_name` and `project_env` value, grafana 3.1.1 puts curly braces around these values in the query like so:
`query: collectd.{devel}-{projectA}-*-*`
instead of (grafana 2.6)
`"collectd.devel-projectA-*-*"`
Unfortunately, graphite doesn't return any data for the 3.1.1 query.

I assume this is a bug, if you know a workaround/fix that I can implement on my dashboard - please, tell me.

**Comment by torkelo** [comment]
Remove the multi and all option from the template variable as the your graphite query does not support it

**Comment by malinoff** [comment]
@torkelo I suppose you missed the fact it was working in grafana 2.6. Graphite is not guilty here.

**Comment by malinoff** [comment]
@torkelo I really appreciate your work on grafana, but the issue isn't really resolved. Can we please continue discussion to truly fix this?

**Comment by torkelo** [comment]
@malinoff if you disable mutli on the template variable it will not use curly brace. If your query does not support curly braces then you cannot use a multi select variable.

**Comment by malinoff** [comment]
@torkelo I cannot disable multi because it's supposed to be used as multi-choice. And it's not "my query" that doesn't support curly braces, graphite does support curly braces but grafana 3+ adds unnecessary curly braces around _single_ selected value like so: `{devel}-{projectA}-*-*` while grafana 2.6 doesn't do that, it builds such query: `devel-projectA-*-*`.
As it works correctly in grafana 2.6 and _doesn't_ work correctly in grafana 3.1.1 I assume this is a bug in grafana and _not_ in my data source, graphite, which haven't been changed during grafana upgrade.

**Comment by torkelo** [comment]
If `{devel}-{projectA}-*-*` is not a valid query in graphite then `{devel,prod}-{projectA,projectB}-*-*` will not be so why is multi select enabled when graphite does not support it? if you disable multi the curly braces will be removed.

**Comment by malinoff** [comment]
Yes, the latter isn't valid - but we don't support this case for our users and they know it won't work for them. The question is really about why have you changed this behavior, when even selecting a single value results in curly braces on grafana 3+ while 2.6 builds the query without them. It's all about transition to grafana 3+ from 2.6 and we simply can't make this move without breaking all our existing metrics (as we must push metrics with different names like using dots instead of dashes) just because grafana 3+ puts unnecessary curly braces.

**Comment by esbite** [comment]
We are hitting this issue. We have a multi select template, and selecting multiple values works fine. Selecting a single value fails since graphite does not understand a query with a single value inside the curly braces.

- `statsd.metrics.{web1,web2}.consul` works fine, getting data for all selected hosts
- `statsd.metrics.{web1}.consul` FAIL with graphite returning no data at all
- `statsd.metrics.web1.consul` works fine with graphite returning data for one host

Yes this seems odd that graphite does not understand these queries, but I can't find any bug or issue filed with them regarding this so I don't think they will fix it anytime soon.

We are on Grafana 4.3.2 and Graphite 0.9.15. Cannot upgrade right now, but will try out never version soon to see if the issue is resolved.

**Comment by marcelfischer** [comment]
Im having the same Problem like @esbite but I already have graphite-web-0.9.16 from EPEL

**Comment by dannygoulder** [comment]
I have just hit this problem when upgrading Graphite from 0.9.15 to 0.9.16.

I observed that with a multi select template, if you select one or more entries (or All) then Graphite 0.9.15 accepts the curly brace syntax with one or more entries (i.e. the ‘new’ behaviour described in 3.x)

If you upgrade Graphite to 0.9.16 it will only work properly if you select two or more entries. As described above curlies are inserted but not recognised unless a comma is present, and the find metrics call ends up matching nothing.

Now I don’t know how well documented this is (and I can only guess as to what the behaviour is with 1.x Graphite), but for me the solution was to rollback the upgrade and revert to 0.9.15.

Grafana could arguably use a ‘more compatible’ approach (although this is more complex), which would be to strip the curly braces when only a single value is selected (as the user can select one value in a multi select) - and then only add curlies when there are at least two selections. This behaviour should be accepted by all versions of Graphite and will avoid this unexpected behaviour.

At least there should be a note documented (perhaps within the Templating documentation) to avoid poor souls coming a cropper as I have this evening.

**Comment by dannygoulder** [comment]
For the benefit of @marcelfischer and @esbite (if they haven't already solved their issues), I have installed graphite-web 0.9.15 from pip.

I guess if you wanted to be really creative (or you are really actually seeing this issue on 0.9.15) you could fix it with a RewriteRule ¯\_(ツ)_/¯

**Comment by wiad** [comment]
I'm hitting this as well, with graphite-web 0.9.16. 

A metric like
`metrics.{test}.values`
will fail, but interestingly a metric like
`metrics.{test,}.values`
will work - notice the added traling comma. Repeating commas does not seem to be a problem, so you could construct a rewriterule to achieve this. I actually gave it a go but it's a bit tricky for me to get it right and it really is a pretty crappy solution to this problem. 

It would be easier for grafana to always add an extra comma for multipart values, or to skip the braces completely when only a single value is selected. 

Is it the data source providers that should adapt their code to work with Grafana or Grafana that should adapt their code to work with the data sources?

**Comment by wiad** [comment]
Also, can confirm that downgrading graphite-web to 0.9.15 works for me too.

**Comment by j0j0i996** [comment]
Hi, 
I am experiencing a similar issue. I want to print my multi value variable to the regular text panel (HTML). Unfortunatly it prints it with the curly braces.  This just looks horrible. Any ideas?
