### ISSUE TITLE
auth.proxy 401's even with the header set.

### ISSUE THREAD

**Issue by liquidgecka** [grafana/grafana#5937]
Using grafana-3.1.1-1470047149 installed via deb on ubuntu xenial I am unable to get auth.proxy to work at all. It will allow access to some pages, but it rejects all calls to /api/login/ping as demonstrated by this curl which skips nginx and adds the header manually:

```bash
curl -H 'X-Webauth-User: admin' -D- localhost:3000/api/login/ping
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=UTF-8
Set-Cookie: grafana_sess=1bf250739b79f8c5; Path=/; HttpOnly
Date: Tue, 30 Aug 2016 16:23:12 GMT
Content-Length: 26

{"message":"Unauthorized"}
```

My config contains:
```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

[auth.basic]
enabled = false

[auth.google]
enabled = false

[auth.github]
enabled = false

[auth.anonymous]
enabled = false

[security]
admin_user = admin
admin_password = <snip>
secret_key = <snip>
```

I am assuming that I am doing something really wrong but for the life of me I can not get this to work no matter what the variation on the setup is. =/

**Comment by torkelo** [comment]
That api call is only for renewing session with a remember me cookie
