### ISSUE TITLE
UX: Quick way to copy a link to the Explore page with absolute (UNIX) time instead of relative time

### ISSUE THREAD

**Issue by tomasbanet** [grafana/grafana#59370]
### Background / Why we're doing this

Apologies if this issue has been reported already or if there is a way to achieve what I want already. I tried searching for it but couldn't find anything related.

In the `Explore` page, I want to be able to copy a link to the query / result with absolute time (UNIX time) instead of time relative to me. Copying a link with the default time parameters (now-1h to now) means the link gets stale after some time passes. I have a workflow where I often craft queries in the Explore page and save them somewhere later, but the queries should be for a specific time period only in order to highlight the right results.   

Problematic (default) workflow:
1. Go to the Explore page
2. Create a prometheus query / loki logs query
3. Copy a link to the results / query by going to the browser URL bar and CTRL+C'ing that
4. Share link with the team / paste it in a doc
5. Come back to the link a few months later, realise that the link no longer shows the same results because time was set to from `now-1h` to `now` by default.
6. Figure out what was the intended time (around the time the link was sent) and manually set that yourself.

Workaround workflow:
1. Create the query as in step 1-2.
2. Select the time selector in top right
3. Manually set an absolute time, clicking on the current day and adjusting the hours to be around your current time.
4. Copy the link by CTRL+C'ing the browser URL.

<img width="663" alt="Screenshot 2022-11-28 at 09 51 10" src="https://user-images.githubusercontent.com/105751190/204249108-86c086d0-6f62-4627-9556-857d1da17c50.png">

<img width="663" alt="Screenshot 2022-11-28 at 09 51 33" src="https://user-images.githubusercontent.com/105751190/204249096-e48ea5d3-6d41-4803-9716-9a021d5c614a.png">

New proposed workflow:
1. Create the query as in step 1-2.
2. Have a small "copy" button on the page which copies the link to the page for you (pastes it into your clipboard contents) with time parameters set to be 'now-1h' to 'now' but 'now' is replaced with absolute UNIX timestamps
**OR** have a button in the Time selector to switch to using "absolute time" for ranges such as last 1 hour, last 5 minutes, etc. so that it's "last 1 hour" at the time the time was evaluated.

### Is there existing research for this?

No research yet

### Problems or tasks

- How to provide a quick way of copying a link to prometheus metrics/loki logs with current time instead of relative time. 

### Deliverables

- A button / behaviour change on the Explore page OR a component in the time selector

**Comment by ivanahuckova** [comment]
Hi @tomasbanet, I just found this issue. This is actually possible with the shortcut `t``a` that changes relative time to absolute time.

But I agree - some UI for this would be helpful. Or even if clicking on `Copy link` would turn relative time into absolute one. 
<img width="162" alt="image" src="https://github.com/grafana/grafana/assets/30407135/3051ef01-299a-4c46-89fa-11a5ddaa8aca">

**Comment by ivanahuckova** [comment]
@grafana/explore-squad  +1 on this based on feedback from @mplzik 🙂

**Comment by ifrost** [comment]
> Or even if clicking on Copy link would turn relative time into absolute one.

I can see both making sense depending on how links are used:

* For a link that becomes a bookmark used on regular basis (e.g. to see last 24 hours every day) I'd like to have relative time
* For a link that is shared with someone else to see the same results I'd like to  have absolute time

Feels to me like it'd be good to give the user an option.

> Probably the time picker could benefit from a button to make the range absolute. I can see the same issue happening anywhere it is used

I think that'd actually be great to have! I think that a mix o both types can be needed is some cases (e.g. split view with relative on one side and absolute on the other side) and that could help.

**Comment by Elfo404** [comment]
imho the shortened link button works as it should, it just copies whatever the current state is in a short url, i don't see the need of overcomplicating it with more options if that can be solved by having an easy way to turn timeranges into absolute ones and then copying the URL as usual (either shortened or not)

**Comment by ivanahuckova** [comment]
>imho the shortened link button works as it should, it just copies whatever the current state is in a short url, i don't see the need of overcomplicating it with more options if that can be solved by having an easy way to turn timeranges into absolute ones and then copying the URL as usual (either shortened or not)

I think with shortened link you oftenly want to share what you are seeing with your colleagues. Therefore I think that just changing relative time range to absolute (automatically) would make more sense than just having relative time.

**Comment by Elfo404** [comment]
then i would consider doing the same as dashboards and let the user explicitly decide, changing automatically (and without any option) the time range for the users would prevent them to share shortened link with relative ranges, and it's not a pattern i've seen anywhere else in Grafana:

![Screenshot 2023-09-26 at 14 45 43](https://github.com/grafana/grafana/assets/1170767/3dd4427b-4ff9-40e2-a8a8-1f4182ec1a97)

**Comment by ivanahuckova** [comment]
I wouldn't add these options as it seems overkill for Explore. I think the goal would be finding when are the users clicking on sharing the url. And then finding the right defaults for that usecases make sense. I think absolute range to share "exactly what I am seeing" is definitely something worth considering. 

> and it's not a pattern i've seen anywhere else in Grafana:

We do it for permalinking in logs for example. 🙂

**Comment by diegoadams** [comment]
This topic was brought up in [Explore Slack](https://raintank-corp.slack.com/archives/C02TXB92G6T/p1696448824781799) so chiming in here:

What about having a dropdown in the Share icon? This dropdown would allow users to pick between the two link variants. We could have descriptive text to provide clarity as seen in the attached images.

<img width="620" alt="Screenshot 2023-10-06 at 15 47 03" src="https://github.com/grafana/grafana/assets/95694434/01f6eceb-e167-4af3-817c-1a6a10d69211">
ming in here, 
<img width="582" alt="Screenshot 2023-10-06 at 15 47 12" src="https://github.com/grafana/grafana/assets/95694434/67325b11-389c-46d0-b65b-1d6fc8c17477">

**Comment by Elfo404** [comment]
@gelicia i was looking at some user interviews, and some people mentioned copying the LONG URL with absolute time, not the shortened one (for stateless use cases)

**Comment by diegoadams** [comment]
posted ux update here: https://github.com/grafana/grafana/pull/77336#issuecomment-1804928320
