### ISSUE TITLE
Grafana built from source not working with upstart script

### ISSUE THREAD

**Issue by anirbanroydas** [grafana/grafana#5938]
This is my upstart script : 

```
description "Server to do graphing taking metrics from time series databases or graphite"
 author      "Anirban Roy Das"


 expect fork
# expect daemon 

 start on runlevel [2345]
 stop on runlevel [!2345]

 respawn
 respawn limit 10 5

 chdir ~/gopkgs/src/github.com/grafana/grafana

 env GRAFANA_BIN=bin/grafana-server

 pre-start script
     echo "[`date`] Grafan is  Starting" >> data/log//grafana.log
 end script

 script
     exec ./bin/grafana-server
 end script

 pre-stop script
     echo "[`date`] Grafan is  Stoping" >> data/log/grafana.log
 end script
```

Checking : 

```
$ init-checkconf /etc/init/grafana-server.conf
File /etc/init/grafana-server.conf: syntax ok
```

Status Check : 

```
$ sudo service grafana-server status
grafana-server stop/waiting
```

Start: 

```
$ sudo service grafana-server start
start: Job failed to start
```

What am I missing?

Or what is the other solution to make this process restartable so that it doesn't end when I close my ssh session?

**Comment by torkelo** [comment]
Check the initd and systemd launch scripts under /packaging in the repo fir how to start grafana-server

**Comment by anirbanroydas** [comment]
@torkelo  
Those are not upstart script.

Also, since I built from start, things are differing.

**Comment by torkelo** [comment]
yes, I know, I was just pointing you to some inspiration for how to start grafana-server from an init script. 

https://github.com/grafana/grafana/blob/master/packaging/deb/init.d/grafana-server#L64
