### ISSUE TITLE
Crushes if disable [help] section

### ISSUE THREAD

**Issue by baur** [grafana/grafana#59381]
**What happened**:
Crushes if disable help section ([help] enabled = false)

```
app.ts:185 Failed to start Grafana TypeError: t is not iterable
    at o (navModel.ts:15:22)
    at r (navModel.ts:10:3)
    at configureStore.ts:29:17
    at Object.init (app.ts:119:7)
    at 13593 (index.ts:21:5)
    at r (bootstrap:19:32)
    at app.c9d1bb402f8379b5d093.js:1:277108
    at r.O (chunk loaded:23:12)
    at app.c9d1bb402f8379b5d093.js:1:277128
    at a (jsonp chunk loading:71:28)
```

**What you expected to happen**:
Disable help section

**How to reproduce it (as minimally and precisely as possible)**:
1 - [help] enabled = false
2 - log out 
3 - log in

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.6 
- Data source type & version:
- OS Grafana is installed on: Win10
- User OS & Browser: Chrome
- Grafana plugins: no
- Others:

**Comment by zuchka** [comment]
hi @baur 

this should be fixed and backported to 9.2.x

https://github.com/grafana/grafana/pull/58919

looks like the backport just got merged:

https://github.com/grafana/grafana/pull/59375
