### ISSUE TITLE
keep url arguments when calling api

### ISSUE THREAD

**Issue by wociscz** [grafana/grafana#5939]
- [*] Feature request
(or bug?)

Grafana 3.1.1-1470047149
Datasource influx
Os debian jessie 8.5

When opening grafana dashboard with additional arguments in url (in my case is md5=somehash and expire=ttl) the additional arguments not passed to ajax calls to /api/*.
I have this md5 hash in arguments for nginx securelink module - so users accessing grafana with "secured" url and are able to display only their url with their own var-hostname=hostname&md5=therihash&expire=fewhours. 
The problem is, that user should call the api with another hostname and values - the additional arguments not passed to grafana and i'm not able to filter/process it in nginx reverse proxy...

Is there some way to pass them to _all_ other calls from main script?

Main reason for this is customers graphs - grafana is set to display scripted.js to non-logged users with var-hostname. "Secured" links for their hostnames are generated in our customers admin section. MD5hash is salt+hostname+ttl. Scripted.js is used to show them only one hostname (var-hostname) and only metrics which their machine has.

**Comment by bergquist** [comment]
This is not supported at the moment and I don't see our self supporting this either.

Would it be possible to use a cookie instead.

**Comment by wociscz** [comment]
I know this is not-as-usual setup, but all what i need is: pass all arguments from main uri to api (other) calls (do not touch them).
But as you spotted, i will try different approach through cookies/rewrites and so.

**Comment by bergquist** [comment]
@wociscz please post your progress. Might help others in the same situation :)

**Comment by wociscz** [comment]
Ok i solved it in nginx
First - i generate dashboard url for specific hostname at separate webserver with php so final url is i this form and customer gets this "secured" url.
https://somehost.tld/dashboard/script/customer.js?var-hostname=customer.hostname.tld&md5=hash&expires=now+1h

customer.js is scripted dashboard which fill dashboard with customers metrics (another story)
When customer connect to /dashboard, nginx checks md5&expire arguments with secure_link module. If everything is ok, nginx let user to connect & store md5, hostname and expire values to cookie.

When customer browser create ajax calls to /api nginx location for /api is in use and do the same secure_link check but not with arguments (because there aren't any) but with values from cookie.

http://nginx.org/en/docs/http/ngx_http_secure_link_module.html

snippet from nginx config:

```
# workaround for variable with dash
map $is_args $http_grafanahost {
        default $arg_var-hostname;
}

set $secure SomeL0NGSecureString;

location / {
                return 402;
}

location /dashboard {
                secure_link $arg_md5,$arg_expires;
                set $md5 $arg_md5;
                set $expires $arg_expires;
                set $grafanahost $http_grafanahost;
                secure_link_md5 "$secret$secure_link_expires$grafanahost";
                add_header Set-Cookie "secure=$md5; path=/; domain=somehost.tld; expires=$expires";
                add_header Set-Cookie "hostname=$grafanahost; path=/; domain=somehost.tld; expires=$expires";
                add_header Set-Cookie "expire=$expires; path=/; domain=somehost.tld; expires=$expires";
                if ($secure_link = "" ) { return 403; }
                if ($secure_link = "0" ) { return 410; }
                proxy_pass https://internal.ip:3000/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location ~ /(api|public|favico.ico) {
                # fetch values from cookie
                set $secmd5 $cookie_secure;
                set $sechostname $cookie_hostname;
                set $secexpires $cookie_expire;
                secure_link $secmd5,$secexpires;
                secure_link_md5 "$secret$secure_link_expires$sechostname";
                if ($secure_link = "" ) { return 403; }
                if ($secure_link = "0" ) { return 410; }
                proxy_pass https://internal.ip:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
Secure md5 is calculated from $secret$expirettl$hostname and is valid for all urls within our server. 

Grafana instance for customers is set to anonymous access without login to default organisation and scripted.js is attached to the first an only organisation.

This setup allow us to publish dashboards to customers without login and without expose api to the wild.

(should be better when nginx secure_link involved sha512 rather than md5, i know)
