### ISSUE TITLE
Introduce standard metadata and envelope for structured kinds

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#59399]
We need a standard mechanism for holding metadata about instances of structured kinds (so, schematized entities), that isn't part of the body of the object itself. We can refer to this as "entity metadata." Examples of things that plausibly should be part of an entity's metadata, rather than its body, include:

* Fields like `Created` or `Updated`, which reflect internal bookkeeping
* Fields like [`TeamDTO.MemberCount`](https://github.com/grafana/grafana/blob/ae8acf178bad20f7e59694edcd9e6a7a0a92ae9a/pkg/models/team.go#L92), which should be computed by the backend, not set externally

This is all similar in purpose to [k8s object metadata](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata). However, the above two cases also illustrate a key distinction: `Created` and `Updated` are fields that should come from the system and exist uniformly for all entities, but `MemberCount` is clearly specific to the `Team` kind. Kubernetes objects do not cleanly separate system-specified vs. kind-specified metadata. We should.

We should also expect to wrap body and metadata into an envelope, which will likely include additional data. But at its simplest, it means we can imagine an "enveloped entity" could look something like this, in JSON form:

```jsonc
{
  "metadata": {
    "sys": {...}, // system-specified metadata would appear here
    "kind": {...} // kind-specific metadata would appear here
  },
  "body": {...} // body of the entity, as specified in the kind's schema. probably the only part that's externally writable
}
```

Work has already begun in this direction as part of the object api/storage - see [these models](https://github.com/grafana/grafana/blob/5736b46962b4d4eb01a17d498c845955c965a8a2/pkg/models/object.go), for example. We'll need to reconcile these things.

**Comment by malcolmholmes** [comment]
Also included could be the folder a dashboard is in. This isn't part of the dashboard JSON, but it is needed to apply a dashboard to a Grafana instance.

**Comment by sdboyer** [comment]
cc @ryantxu

**Comment by sdboyer** [comment]
> So there's a difference between operator provided metadata (e.g. dashboard folder) and internally generated metadata (e.g. creation timestamp) that also needs to be handled somehow.

agreed! though this seems to me like the same distinction i was trying to capture with `Created` vs. `MemberCount` in OP. Do you see these as different?

**Comment by ryantxu** [comment]
The Entity store is currently using:
https://github.com/grafana/grafana/blob/main/pkg/services/store/entity/entity.proto#L20

as the wrapper, each kind can then add additional fields to the summary

**Comment by sdboyer** [comment]
As we're pivoting (back) to a k8s object model, there's really no longer a question about how this metadata/envelope is going to look.
