### ISSUE TITLE
Alerting: Require an alert to be firing for X min before changing state.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5940]
One thing that [Prometheus alert manager](https://prometheus.io/docs/alerting/rules/) offers is the option to require an alert rule to be firing for X min before it is consider triggered. I think this is a great way to avoid sending alerts for small spikes. 

Without the *FOR* concept
 - reducing timeseries with avg will be very volatile to isolated spikes. Causing false positives.
 - reducing with mean will lose the spike data

With the *FOR* concept
 - requiring the alert to be firing for 5min will only fire if the spikes are reoccurring.

I'm not sure how we should add this feature in Grafana but none the less I think its important.

**Comment by bergquist** [comment]
@torkelo I would like your feedback on the idea of introducing this. Assigning for now.

**Comment by DEvil0000** [comment]
I would not use a time based model there because you already define how often you execute it. (e.g. check alert every 60s).
I would use a counter in combination with this time for the feature.
e.g. the alert is only fired after X check (alert query execution) results represented "fire" (fullfilled)

**Comment by torkelo** [comment]
I think this issue can be closed, think it can  be handled in the metric query

**Comment by silvestre-abruzzo** [comment]
hi @torkelo I am very interested to understand how this issue can be handled with the "metric query". Could you please say more?

**Comment by torkelo** [comment]
Using the alert query time range?

**Comment by opsj** [comment]
@torkelo Can you provide an example? 
```
WHEN min () OF query (A, 3m, now) IS BELOW 1
```

Will alert if the metric drops below 1 at any point over the course of 3 minutes, not if the alert has _stayed_ below 1 for 3 minutes.
