### ISSUE TITLE
[Feature request] Working with dashboards from dashboards.json as with manually created ones.

### ISSUE THREAD

**Issue by KeNaCo** [grafana/grafana#5941]
# Motivation
Ability to automate Grafana deployments and migrations, especially on Docker.

# Problem
When using `dashboards.json` you can't set imported dashboards as default, star them or make lot of usual stuf. You need manually **save as** and then manage new dashboard again manualy.
Not working well with docker containers which should work out of the box.

This problem is related to #5674 both supports same idea.

# Solution
Make dashboards from `dashboards.json` equal to manually created ones.

# Advantages
Same as #5674. Automation of creation and deployment of Docker containers will be much easier and manageable.

**Comment by torkelo** [comment]
I guess we can could auto import them, but save changes back to the files is tricky as it wont work/be easy in HA  (clustered setup of many grafana instances behind load balancer)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/5269
