### ISSUE TITLE
NPM 9 breaks `@grafana/e2e` cli because `npm bin` is removed

### ISSUE THREAD

**Issue by fmterrorf** [grafana/grafana#59425]
**What happened**:
`grafana-e2e run` does not work and outputs 

```bash
Command failed with ENOENT: /home/test/proj/Unknown command: "bin"

To see a list of supported npm commands, run:
  npm help/cypress run --env CWD=/home/test/proj/,UPDATE_SCREENSHOTS=0 --project=/home/test/proj/node_modules/@grafana/e2e
spawn /home/test/proj/Unknown command: "bin"

To see a list of supported npm commands, run:
  npm help/cypress ENOENT
```

**What you expected to happen**:
The command runs

**How to reproduce it (as minimally and precisely as possible)**:
Create a new plugin using the plugin code gen and run `npm run e2e`. Make sure npm is using version 9

**Anything else we need to know?**:
* [@grafana/e2e](https://github.com/grafana/grafana/blob/main/packages/grafana-e2e/cli.js#L4) uses [resolve-as-bin](https://github.com/saltyshiomix/resolve-as-bin/blob/master/index.ts#L12) to resolve the cypress bin path. 
* The package uses `npm bin` command which is removed in npm @ 9 https://github.com/npm/cli/pull/5459
* Because `npm bin` is removed, `resolve-as-bin` will return an error

A temporary solution would be to downgrade to NPM 8

**Comment by zuchka** [comment]
Thanks for creating this issue, @fmterrorf 

I can reproduce this issue following the OP's steps. Use this guide to build a backend datasource plugin. with the following settings `npm run e2e` will fail as described:

```
node -v && npm -v && yarn -v
v16.14.0
9.1.2
1.22.17
```

**Comment by fmterrorf** [comment]
I can also attempt to put up a fix if you want.  Im thinking of just using `npx cypress` to run the cypress bin

**Comment by zuchka** [comment]
@fmterrorf by all means, we welcome community PRs! I'll make sure it gets reviewed right away 👍

**Comment by fmterrorf** [comment]
> @fmterrorf by all means, we welcome community PRs! I'll make sure it gets reviewed right away +1

I might have to skip on this. I can't figure how to setup my test environment and I don't have enough time to figure it out. Sorry
