### ISSUE TITLE
Repeat panel option affects group by interval.

### ISSUE THREAD

**Issue by IngaFeick** [grafana/grafana#5942]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.0

- What datasource are you using?
influxdb

- What OS are you running grafana on?
debian 8

- What did you do?
I activated the repeat panel option for a templating variable with multi-select and all-option.

- What was the expected result?
I expected the panel to repeat multiple times.

- What happened instead?
The panel did repeat, but it also stopped working. All copies of it have the same error message: 
> "error parsing query: found y, expected ) at line 1, char 157

The queries now have a faulty group by time interval:

> SELECT mean("value") FROM "java.cache.elements" WHERE "cache" = 'cache1' AND "host" = 'a' AND time > now() - 7d GROUP BY time(1y) fill(null);SELECT mean("value") FROM "java.cache.eviction" WHERE "cache" = 'cache1' AND "host" = 'a'  AND time > now() - 7d GROUP BY time(1y) fill(null);SELECT mean("value") FROM "java.cache.hitratio" WHERE "cache" = 'cache1' AND "host" = 'a' AND time > now() - 7d GROUP BY time(1y) fill(null)
I have not set a group by time. The normal time filter is set to 30 min - 1 month (all attempts end with the same error message).

I can work around this problem by setting a fixed "Group by time interval" value. That makes the error message go away and we have data, but it's not the desired functionality, as we really would like the group by interval to adapt dynamically.

The problem can not be reverted, as in: when I deactivate the panel repeat option, the problem persists. When I deactivate the multi select / all options in the templating variable, the problem persists. I scanned the dashboard source json for the term "1y" and I couldnt find it in there.
The only way to get rid of this is to create the whole dashboard from scratch.

**Comment by torkelo** [comment]
you need to set a min span as well (the option next to the repeat option)

**Comment by IngaFeick** [comment]
Awesome, thanks! @torkelo
