### ISSUE TITLE
[DASHBOARD>VARIABLES] : search/filter dropdown input visibility

### ISSUE THREAD

**Issue by tonypowa** [grafana/grafana#59426]
**What happened**:

The size of the search/filter drop-down input for the "Hide" option in DASHBOARD>VARIABLES>General options, is too small. 

![image](https://user-images.githubusercontent.com/45235678/204338515-861dfeb1-456b-4b21-aed6-93774f03c825.png)

The input area is approximately 3 times smaller than in the other options. This might impact the user experience when selecting an option from the drop-down such as "Label", or "Variable", due to that it might be hard to click back on the input area to switch it back to blank ("no value). 

Switched back to no value:
![image](https://user-images.githubusercontent.com/45235678/204340755-61f01464-53ac-491a-abe8-582ebc1935a0.png)

**What you expected to happen**:

The input area is as big as in the options displayed, or just more visible. 

**How to reproduce it (as minimally and precisely as possible)**:

Log in to Grafana.
Navigate to DASHBOARD>VARIABLES
Click + New variable 
In General options, find the "Hide" option.
Click on the drop-down arrow.
Notice the input area is too small

**Anything else we need to know?**: n/a

**Environment**:
- Grafana version: v9.2.5
- Data source type & version: n/a
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows, Firefox 107.0 (64-bit)
- Grafana plugins: n/a

**Comment by dprokop** [comment]
Thanks @tonypowa for opening this. FYI we have changed this in v9.3.x and now the visibility of the variable is controlled via radio button:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2376619/206137332-f9156e52-1c27-4606-8f77-6ab2c6a3d96f.png">

Ref https://github.com/grafana/grafana/pull/56326
