### ISSUE TITLE
Feature Request: Keep Time Across Dashboads

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#5943]
When I brush a period of time on a dashboard, there are instances where I would like to look at other dashboards for the same time period when investigating an issue that happened in that time window.

It would be nice if I could click something like "Lock Time" on the time selector that would keep the time fixed in my user session as I switch dashboards.

**Comment by bergquist** [comment]
In dashboard settings ->  links, you can include the time range from your current dashboard. 

Its not exactly what your looking for but might be useful until this is added.

**Comment by ybizeul** [comment]
That's actually one of the major issues I have when working with Grafana. When troubleshooting, you are focused on a specific period of time, being able to pin the period would be priceless.

**Comment by bergquist** [comment]
Dupe of https://github.com/grafana/grafana/issues/1097
