### ISSUE TITLE
Inserting a Datasource via API doesn't fill up all the fields (or GET datasource is not complete)

### ISSUE THREAD

**Issue by RollingFred** [grafana/grafana#5944]
Grafana 3.1.1 on Linux (Amazon Linux)

Following the Doc page for HTTP API, I'm submitting this:

I have a ElasticSearch Datasource, containing a Time Field, Pattern, Version.

Getting the Datasource via HTTP API returns the following
```
{
	"id": 3,
	"orgId": 1,
	"name": "myESDatasource",
	"type": "elasticsearch",
	"access": "proxy",
	"url": "http://127.0.0.1:9200/",
	"password": "",
	"user": "",
	"database": "[ccma-]YYYY.MM.DD",
	"basicAuth": false,
	"basicAuthUser": "",
	"basicAuthPassword": "",
	"withCredentials": false,
	"isDefault": true,
	"jsonData": null
}
```
The jsonData, which should contain` {"esVersion": 2, "interval": "Daily", "timeField": "timestamp"}` is null

Inserting a new Datasource specifying jsonData works fine.

**Comment by bergquist** [comment]
@RollingFred how does your create datasource request look like?

**Comment by RollingFred** [comment]
I did edit my initial post yesterday (but my title didn't change)
The create datasource, specifying the correct jsonData works fine and all the fields are filled up.

Only the GET part is incomplete.

**Comment by RollingFred** [comment]
This call works for inserting:

`curl -H "Content-Type: application/json" -X POST -d @testds.json http://admin:admin@localhost:3000/api/datasources`

with testds.json containing

```
{
    "id": 3,
    "orgId": 1,
    "name": "myESDatasource",
    "type": "elasticsearch",
    "access": "proxy",
    "url": "http://127.0.0.1:9200/",
    "password": "",
    "user": "",
    "database": "[ccma-]YYYY.MM.DD",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": true,
    "jsonData": {"esVersion": 2, "interval": "Daily", "timeField": "timestamp"}
}
```

**Comment by torkelo** [comment]
the datasource list api (`/api/datasources`) does not return the json details, you need get the data source by id to get the that. `/api/datasources/:id`

**Comment by RollingFred** [comment]
Understood.
I'm building deployment image based on a master system, hence I'm calling `/api/datasources` , not knowing how many datasources are installed or what their names are.
I can process the return value of `/api/datasources` and do individual calls to` /api/datasources/:id `which will solve my problem.

It would probably be cleaner if `/api/datasources` would return the whole content.

My problem is solved, so up to you if you want to fill a new issue for that

**Comment by torkelo** [comment]
@RollingFred it is pretty standard the list API does not return the full object details

**Comment by RollingFred** [comment]
@torkelo: Granted, but in that case it was returning `jsonData: null` (a wrong data)
Either of two choices: `jsonData` should not be there at all or should contain proper value.

I see @bergquist committed a change already. We're good. Thanks!

**Comment by torkelo** [comment]
yea, I agree the null property should not be there
