### ISSUE TITLE
Config: Grafana fails to start if the working directory is not readable

### ISSUE THREAD

**Issue by JonyEpsilon** [grafana/grafana#59441]
**What happened**:

If Grafana is started with the current working directory set to directory that the process does not have permission to access then it fails to start, yielding an error:

```
panic: error getting work directory: stat .: permission denied

goroutine 1 [running]:
github.com/grafana/grafana/pkg/api/static.init.0()
        github.com/grafana/grafana/pkg/api/static/static.go:38 +0x94
```

This situation can occur, for instance, at system start-up time - see this bug for more context, although it may contain more gory FreeBSD details than one wants to see (and for full disclosure, there's arguably something fishy going on there resulting in Grafana running with a PWD of `/root` ... but generically running with a PWD that you don't have access to feels like a situation that could reasonably come up): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267914 .

Looking at the code, https://github.com/grafana/grafana/blob/main/pkg/api/static/static.go#L38, it appears that the current working directory is stat'ed only for the purpose of resolving relative relative paths (at least in that module).

**What you expected to happen**:

It feels like running from any working directory could be reasonable when all paths are absolutely specified. At least for the code linked above, this could be supported by checking whether the path is relative first, and only if it is stat'ing the working directory.

**How to reproduce it (as minimally and precisely as possible)**:

Run Grafana from a directory that it cannot read. E.g. (see the bug above) if `/root` is owned `root:wheel`, permissions 0750, and the user `grafana` is not a member of wheel then
```
cd /root
su -m grafana -c '/usr/local/bin/grafana-server -config=/usr/local/etc/grafana/grafana.ini -homepath=/usr/local/share/grafana'
```
will generate the error quoted above.

**Environment**:
- Grafana version: v 9.2.4
- Data source type & version: n/a
- OS Grafana is installed on: FreeBSD 13.1 (in a jail)
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment]
This issue sounds specific to FreeBSD. Have you been able to reproduce on any other distro / OS? Having trouble replicating...

**Comment by JonyEpsilon** [comment]
I see the same thing if I try in a debian container. This reproduces for me:

```
podman run -it --rm debian

# In container:

apt-get update
apt-get install -y apt-transport-https
apt-get install -y software-properties-common wget
wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list
apt-get update
apt-get install grafana

# Checking grafana user group membership
groups grafana
# grafana : grafana

# Checking grafana homepath permissions
ls -al /usr/share/ | grep grafana
# drwxr-xr-x  7 root root 4096 Dec  1 23:26 grafana

# Start from / . This is the command that `service grafana-server start` would run, with the addition of a `--homepath` flag, pointing to the
# directory that start-stop-daemon would chdir to.

cd /
su -m grafana -c '/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=deb cfg:default.paths.provisioning=/etc/grafana/provisioning \
  cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins'

# Runs fine.

# Repeat in a directory that grafana cannot read. Note that homepath is still set.

# Checking / permissions
ls -al /
# <snip>
# drwx------   1 root   root    4096 Dec  1 23:30 root
# <snip>

cd /root
su -m grafana -c '/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=deb cfg:default.paths.provisioning=/etc/grafana/provisioning \
  cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins'

# Grafana does not start despite all paths being absolute, and a homepath argument being provided.

# panic: error getting work directory: stat .: permission denied
#
# goroutine 1 [running]:
# github.com/grafana/grafana/pkg/api/static.init.0()
#         /drone/src/pkg/api/static/static.go:38 +0x94
```

**Comment by drTr0jan** [comment]
@zuchka, I think this is true for any system with cleared other chmod bits root homedir,
Why is Grafana using workdirectory instead homepath in this case?
