### ISSUE TITLE
MySql: Variables not working as expected in 9.2.7

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#59453]
**What happened**:
Upgrading from 9.1.6 to 9.2.7 some variables has stopped working. Because of MySql syntax and in order to avoid errors while dynamically changing the columns name, I used to use this solution:
1) With SELECT CASE I created the correct syntax
2) Then, in another variable I simply called the previous one and the query was correctly executed.
Now this doesn't work anymore

IN GRAFANA 9.1.6 VERSION
variables list
![image](https://user-images.githubusercontent.com/51508670/204453685-52931c6d-b138-4d94-81c2-6fc82e583e5e.png)
"Variable" variable details
![image](https://user-images.githubusercontent.com/51508670/204454867-aeb7310b-e270-4d81-92e8-1bf0b166ab10.png)
"Panel_var" variable details (the main one that doesn't work anymore)
![image](https://user-images.githubusercontent.com/51508670/204453779-c0c55230-cb9a-412d-b0c9-d0907565f6af.png)

IN GRAFANA 9.2.7 VERSION
All the variables results are the same, but the main one: "Panel_var" variable
![image](https://user-images.githubusercontent.com/51508670/204455985-d8c0d8b9-da19-4d6b-91c0-e6cce86e168c.png)
At the moment all my dashboards don't work because of this issue/changment. How can I solve it?
Thanks a lot

**What you expected to happen**:
Get the query result as before

**How to reproduce it (as minimally and precisely as possible)**:
create two simple variables as shown

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.7
- Data source type & version: phpmyadmin 5.0
- OS Grafana is installed on: debian 11
- User OS & Browser: chromium
- Grafana plugins:
- Others:

**Comment by codeincarnate** [comment]
We're looking at some potentially interrelated SQL variable and macro issues and should be looking into this soon.

**Comment by DonatoD** [comment]
@codeincarnate Maybe this can help you a bit. I installed latest version 9.3.0 and I noticed that some variables, even if already used within the panel, in the variable settings page are marked as never used within any panels.
-- variable settings
![image](https://user-images.githubusercontent.com/51508670/205027596-05352def-b67b-49c8-9ded-43a3b2bcfd9a.png)
-- panel settings
![image](https://user-images.githubusercontent.com/51508670/205027952-736ba489-2642-4322-957a-68124adff443.png)

But in this case the panel correctly read the query

**Comment by DonatoD** [comment]
Hi, making some more test, because this is a big problem since I cannot update to the last version. I noticed some more thing.
The problem related to the precedent post, some variables are marked as never used even if thay are, happened especially with variable used within the library panels

**Comment by DonatoD** [comment]
Any news on this? I'm still not uble to update, since my dashboards don't work :-(

**Comment by gabor** [comment]
hi @DonatoD, i have problems reproducing this (i tried to have one variable return potential sql queries, and the second variable executing that sql query, and that worked ok).

could you please setup a minimal reproduction of this problem, and describe it here?
also, could you try it with a recent Grafana version? (`10.1.5` for example) thanks!

**Comment by DonatoD** [comment]
Hi, Thanks. I'm trying to update to the latest Grafana version, it will take me a while but I see that several problem seems to be solved. Iìll keep you update as soon as I can.
Thanks
