### ISSUE TITLE
Alert: Reset "send to" list

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#5945]
Thank @torkelo, Alerting was the most necessary feature in Grafana and you made it available.

* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 
Ans: Latest Nightly build(4.0)

- What datasource are you using? 
Ans: Graphite

- What OS are you running grafana on? 
Ans: Ubuntu14.04

- What did you do? 
Ans: Set the email list in Alert Notification tab and saved it

- What happened instead?
Ans: Whenever i refresh the page or reopen the dashboard, the alert "send to " list is getting reset, email id's are not not visible there

Thanks in Advance,

Regards,
Himanshu

**Comment by torkelo** [comment]
I am unable to replicate this, when I add or remove notifications to the notifications section of the alert tab, then save the dashboard, reload the page the changes are there.

**Comment by Himanshu-pupneja** [comment]
@torkelo, problem is there.

I downloaded the deb package from "latest build from master".
https://grafanarel.s3.amazonaws.com/builds/grafana_latest_amd64.deb

![image](https://cloud.githubusercontent.com/assets/15123322/18274233/11c60ba2-745f-11e6-9094-cf2688929fed.png)

can you try with this package?

**Comment by torkelo** [comment]
try a newer build, we had an issue with the nightly build system, it contains newer builds now

**Comment by Himanshu-pupneja** [comment]
Nevermind @torkelo 

It was a bit confusing for me at starting, i mentioned email ID in send to column.
but now i have set email in notification tab "/alerting/notification" and its working fine.

![image](https://cloud.githubusercontent.com/assets/15123322/18376844/1ff404e0-7680-11e6-9a77-8d8174eb32b7.png)


can you put a info sign after send to column?
