### ISSUE TITLE
How to get all query result for a variable?

### ISSUE THREAD

**Issue by ManuRodgers** [grafana/grafana#59451]
![image](https://user-images.githubusercontent.com/33333844/204429238-ab53d159-2660-487a-af8c-4e69b334acad.png)
With the flux query shown above, I can get all query result, which is the organisation name list in the Influxdb explorer, while I can only get tiny part of the query result in grafana as variable. In other words, I can only get a small portion of the organisation name list in the dropdown list. 
Is there any way that I can show all the result in the dropdown llst?

**Comment by tonypowa** [comment]
hello @ManuRodgers 

Thank you for your question. However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on https://community.grafana.com/
