### ISSUE TITLE
Webhook duplicate send

### ISSUE THREAD

**Issue by qdupuy** [grafana/grafana#59460]
Hello,

Have you ever encountered the case of a double send during a grafana alert with a webhook ?

I’ve trouble seeing why I have a duplicate in the sending and its resolution

**Comment by tonypowa** [comment]
hello @qdupuy 

thank you for bringing up this issue

In order to help you, we need to know more details. A good start would be to fill in the following template:


**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

Thank you

**Comment by qdupuy** [comment]
What happened:

When I send a webhook alert, I receive it twice or more on my slack channel.

What you expected to happen:

Avoid having duplicates polluting my slack channel

How to reproduce it (as minimally and precisely as possible):

the steps :

- Creating a contact point and a notification policy
- Creation of an alert with the labels it needs to use the right contact point
- Test sending an alert

Anything else we need to know?:

I’ve trouble seeing why I have a duplicate in the sending and its resolution

Environment:

    Grafana version: v9.2.6
    Data source type & version: Prometheus (version prometheus:v2.39.0)
    OS Grafana is installed on: Kubernetes
    User OS & Browser: Firefox, Safari, Chrome

**Comment by zuchka** [comment]
@qdupuy 
this is called alert flapping and its a common issue with all alerting systems.

Please see [this blog post for alerting best practices](https://grafana.com/blog/2022/03/10/best-practices-for-alerting-on-synthetic-monitoring-metrics-in-grafana-cloud/) and some tips for avoiding flapping alerts. specifically:

> - Use the for clause in alert rules to wait for a certain duration before an alert is considered active. This can help with flapping alerts or alerts that are firing for momentary failures that self-correct (e.g: error due to bad route between probe and target). See Prometheus: Understanding the delays on alerting for a detailed explanation of alert lifecycles.
> - Avoid alerting on a gauge metric directly (e.g: probe_success metric). A flapping gauge will reset for duration and alerts will NOT fire. But if you must, use sum_over_time or avg_over_time query functions on the metric in the alert rule. Read more on Alerting on gauges in Prometheus 2.0.
