### ISSUE TITLE
modif grafana alert rule, error: A: data source not found

### ISSUE THREAD

**Issue by kwenzh** [grafana/grafana#59467]
**What happened**:
when i remove a thanos datasoruce in grafana, i see alert rule report an err:  datasource not found
![image](https://user-images.githubusercontent.com/38367518/204484326-5ab6e388-483e-42a2-8639-bae2f7a3f93f.png)

then edit alert rule and update rule's datasource, choose a effect datasource , but can not to save, The popover reported an error： 
```
there are some error:
Error: invalid rule specification at index [0]: failed to validate condition of alert rule xxxxxxxxxxxxxxxxxxxxxxx : invalid query A: data source not found: v0Et_GnVz  , 
```
delete this rule will occur tha same error: 

![image](https://user-images.githubusercontent.com/38367518/204484463-e9aec626-335b-480a-aeaa-425760c9b9bb.png)

![image](https://user-images.githubusercontent.com/38367518/204484831-b704a4e7-8a1b-4c6f-bdd9-806a06e988a7.png)

**What you expected to happen**:
it can delete alert rule successful or modif alert rule datasource

**How to reproduce it (as minimally and precisely as possible)**:
it is hard to reproduct it ,  I just deleted a datasource named thanos. 

**Anything else we need to know?**:
i check grafana.db , it semms:

![image](https://user-images.githubusercontent.com/38367518/204483603-1a361402-67cf-4f95-8941-c844c2c515f7.png)

 so i think it is the similar issue with: 
https://github.com/grafana/grafana/issues/33885,
https://sqliteviewer.com/blog/database-disk-image-malformed/

**Environment**:
- Grafana version:  v9.0.7
- Data source type & version:  proemtheus、mimir、thanos
- OS Grafana is installed on:  k8s
- User OS & Browser: centos7
- Grafana plugins: no
- Others:

**Comment by kwenzh** [comment]
i decide delete database  recird in tb: alert_rule

**Comment by mellieA** [comment]
@kwenzh this is a known issue explained well in https://github.com/grafana/grafana/issues/53357#issuecomment-1256663151 

There is a PR that will introduce an API endpoint that can help in this situation: https://github.com/grafana/grafana/pull/58998
