### ISSUE TITLE
A better error pages (404, 500)

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5947]
Our 404 page is _kinda_ super boring. ex http://play.grafana.org/boring-404-page

I think we should have better 404 and 500 pages. Dont have to be extreme but anything is better then this :)

ping @mattttt  @bulletfactory

**Comment by bergquist** [comment]
Could we please have a grafanasouros eating graphs?

**Comment by bulletfactory** [comment]
I support this. We need to restart the update of the grafanasaurus character- I think this is a great first-implementation. Assign to me so I don't lose it. Thanks!

**Comment by bulletfactory** [comment]
Playing around with 404. Playing with making it look like a graph, but different enough not to confuse anyone. Will keep iterating.

![404](https://cloud.githubusercontent.com/assets/1950595/26078249/e469a31e-398c-11e7-9b02-9cbc678ab79a.jpg)

**Comment by torkelo** [comment]
nice! Like it, the legend on the side maybe should have "current" header, instead of total

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/9285
