### ISSUE TITLE
multiplied tags, graph with gap

### ISSUE THREAD

**Issue by r0bj** [grafana/grafana#5949]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
3.1.1-1470047149

- What datasource are you using?
Influxdb

- What OS are you running grafana on?
ubuntu 14.04

- What did you do?
Creating a graph with two hosts

- What happened instead?
Graph with every host separately looks ok:

<img width="1260" alt="screen shot 2016-09-01 at 15 10 49" src="https://cloud.githubusercontent.com/assets/1297747/18168595/d279c986-7056-11e6-8f19-96055165e5cc.png">

<img width="1273" alt="screen shot 2016-09-01 at 15 14 28" src="https://cloud.githubusercontent.com/assets/1297747/18168604/d8b04852-7056-11e6-87eb-dd29fab53f80.png">

But adding two host at once creates four hosts and strange graph with gap:
<img width="1270" alt="screen shot 2016-09-01 at 15 16 16" src="https://cloud.githubusercontent.com/assets/1297747/18168662/0f61625a-7057-11e6-938a-5ba40b3c6761.png">

**Comment by torkelo** [comment]
looks like you are stacking? try fill(0) to make sure that there are values for each data point. 

if you still think the viz is wrong please include the raw InfluxDB response (chrome dev tools network tab)

**Comment by r0bj** [comment]
This graph is not stacked and fill(0):
<img width="1262" alt="screen shot 2016-09-01 at 17 18 44" src="https://cloud.githubusercontent.com/assets/1297747/18173000/2c2586da-7068-11e6-82c4-077c1dc33ed9.png">

There is a influxdb response:
https://gist.github.com/r0bj/1da6a178d54a661954d2cd4c8112e9d4

**Comment by torkelo** [comment]
ok, as you can see with fill(0), there is a gap there.

**Comment by r0bj** [comment]
So this gap is the reason why there are 4 hosts instead of 2?

**Comment by torkelo** [comment]
?

**Comment by r0bj** [comment]
It seems that "group by tag(host)" cause to plot 4 hosts but there are actually 2: memcache-s1 and memcache-s2.
I'm not sure why, do you think this is related with this gap?

**Comment by torkelo** [comment]
you are grouping by data center and host

**Comment by torkelo** [comment]
tag $tag_dc to alias, you will maybe see more in the series name

**Comment by r0bj** [comment]
DC tag is the same in all cases. When zoom in graph looks like this:
<img width="1271" alt="screen shot 2016-09-01 at 17 57 22" src="https://cloud.githubusercontent.com/assets/1297747/18174439/dbdb3b10-706d-11e6-8537-e44d0ac2d6f3.png">

Thanks for help anyway.

**Comment by torkelo** [comment]
ok, maybe an InfluxDB bug then

**Comment by r0bj** [comment]
You are right, this is probably influx bug causing this behaviour:
https://github.com/influxdata/influxdb/issues/7220
