### ISSUE TITLE
Use DefaultAzureCredential for authenticating with Azure

### ISSUE THREAD

**Issue by dbg-raghulkrishna** [grafana/grafana#59512]
**What happened**:

Azure deprecated their pod-identity and moved to workload-identity azure monitor plugin does not support azure workload identity 
please check here for more details  https://github.com/grafana/grafana/discussions/53645

**What you expected to happen**:

query azure monitor using workload identity in AKS

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  9.2.5
- Data source type & version: Azure monitor1.0.0
- OS Grafana is installed on: AKS
- User OS & Browser: Windows Chrome
- Grafana plugins: Azure monitor
- Others:

**Comment by andresmgot** [comment]
hi @dbg-raghulkrishna, thanks for bringing attention about this feature request. To avoid duplicity, let me close the issue to keep the comments in the discussion. We will convert that into an issue once we start working on it.
