### ISSUE TITLE
Session max per user login ID

### ISSUE THREAD

**Issue by adamvtt** [grafana/grafana#5951]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Would it be possible to extend the quota system to allow a max session count per user login ID?  The use case is preventing shared logins where the underlying datasets are licensed on a per-user basis.

**Comment by dafero** [comment]
I am also very interested in this feature. Can it possibly be looked into? Otherwise, if it's already implemented, can anyone indicate how this can be configured/implemented?

**Comment by rafaelrferreira** [comment]
I have interest too. It can be done?
