### ISSUE TITLE
docs: time range controls section is missing in 9.2 docs

### ISSUE THREAD

**Issue by mellieA** [grafana/grafana#59515]
Click https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/ 
Click **Configuring dashboard time range controls** which goes nowhere

It exists for the 9.1 docs: 
https://grafana.com/docs/grafana/v9.1/dashboards/manage-dashboards/#configure-dashboard-time-range-controls

It looks like the link just needs to be updated for *latest*

**Comment by GrafanaWriter** [comment]
@imatwawana - can you please check the link and fix as needed?

**Comment by imatwawana** [comment]
Hey @mellieA, it looks like this content was refactored on [this PR](https://github.com/grafana/grafana/pull/55940) and moved to a new page, [Dashboard settings](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/modify-dashboard-settings/) in 9.2 ([that version here](https://grafana.com/docs/grafana/v9.2/dashboards/build-dashboards/modify-dashboard-settings/)). However, when the content got moved, removal of the link on the original page got missed, so I'll be making a fix for that.

**Comment by imatwawana** [comment]
Fixed!
