### ISSUE TITLE
[Bug]Turning on gzip compression breaks avatar transmission

### ISSUE THREAD

**Issue by chaosben** [grafana/grafana#5952]
If gzip is enabled, something goes wrong within the avatar transmission. 

The browser complains
`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH http://127.0.0.1:3000/avatar/ce02af25e212884d65c34cab5e191ff3`

If Grafana is used through mod_proxy the apache log says
`(70008)Partial results are valid but processing is incomplete: [client ...] AH01110: error reading response`

If gzip is disabled, everything works as expected.

Grafana 3.1.1
OS Fedora 4.5.6-200.fc23.x86_64

**Comment by DanCech** [comment]
enabling gzip also causes problems with plugin readme display, which shows the result of running the raw gzipped data through markdown

**Comment by Tom-Fawcett** [comment]
Enabling gzip also breaks the `/metrics` endpoint.

Both when behind a nginx reverse proxy, and when going direct to grafana.

Visiting the endpoint in Chrome returns `ERR_CONTENT_LENGTH_MISMATCH `

When using nginx I see:

```
2017/10/03 08:32:30 [error] 1630#1630: *10178 upstream prematurely closed connection while reading upstream, client: XXX.XX.X.XX, server: XXXXXXXXXXXXX, request: "GET /metrics HTTP/1.1", upstream: "http://127.0.0.1:3000/metrics", host: "XXXXXXXXX"
```

And prometheus, when trying to scrape `/metrics`, shows `unexpected EOF`.

**Comment by bergquist** [comment]
Created new issue for solving the bug regarding broken /metrics endpoint when gzip is enabled.

**Comment by daniellee** [comment]
Partial fix - fixed the plugin readme getting the wrong content type when gzipping. Could not recreate the avatar bug.

**Comment by torkelo** [comment]
the avatar bug might have been fixed in recent commit (when I merged annotations, as I in that commit brought over my changes from develop branch of the gravatar proxy)
