### ISSUE TITLE
HTTP API: Regression on 9.3.0 and 8.5.16 with DELETE `/api/folders/{UID}`

### ISSUE THREAD

**Issue by amotl** [grafana/grafana#59546]
Dear Grafana team,

first things first: Thanks a stack for your hard work on conceiving and maintaining Grafana, it is much appreciated. We just discovered a minor flaw with the most recent Grafana 9.3.0 release we would like to report back to you. Hope this helps.

With kind regards,
Andreas.

**What happened**:

When upgrading our CI jobs to Grafana 9.3.0, we discovered a small regression. When invoking the HTTP API endpoint DELETE `/api/folders/{UID}`, it responds with `200 OK`, but yields an empty response body now. The new behavior makes JSON parsers croak like `requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0`.

**References**:
- Where it happened: https://github.com/panodata/grafana-wtf/pull/44
- Where it was reported and analyzed: https://github.com/panodata/grafana-client/issues/47

**What you expected to happen**:

Grafana 9.3 should not introduce a significant API change compared to Grafana 9.2 here. The previous response when deleting folders was:
```json
{
    "id": 1,
    "message": "Folder foobar deleted",
    "title": "foobar"
}
```
If the change to omit the response body was intended, Grafana should respond with `204 No Content` instead of `200 OK`.

**How to reproduce it (as minimally and precisely as possible)**:

Install Docker and [HTTPie](https://pypi.org/project/httpie/).
```
docker run --rm -it --publish=3000:3000 --env='GF_SECURITY_ADMIN_PASSWORD=admin' grafana/grafana:9.3.0
http --auth=admin:admin POST localhost:3000/api/folders title=foobar
http --auth=admin:admin DELETE localhost:3000/api/folders/8EmOC4K4z
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0
- OS Grafana is installed on: Docker
- User OS & Browser: macOS, HTTPie

**Comment by zuchka** [comment]
thanks as always for your contributions @amotl 

reproduced this on 9.3.0 using the steps provided. Thanks for those as well 😄

**Comment by amotl** [comment]
Thanks. I think the https://github.com/grafana/grafana/labels/type%2Fregression label should get a more prominent color, similar to https://github.com/grafana/grafana/labels/type%2Fbug.

**Comment by zuchka** [comment]
seems reasonable, @amotl. it is done.

**Comment by amotl** [comment]
Hi again,

are there any plans to fix this within one of the upcoming Grafana 9.3.x patch releases?

With kind regards,
Andreas.

**Comment by amotl** [comment]
@zuchka: First things first, I would like to wish you a happy new year.

Maybe we can keep the https://github.com/grafana/grafana/labels/type%2Fbug label on this issue, together with https://github.com/grafana/grafana/labels/type%2Fregression, in order to make it more prominent? Also, do you have any power to add it to the next milestone, when possible?

**Comment by amotl** [comment]
Hi lovely Grafana team,

we just tested it with the most recent Grafana 9.3.6 release, but the error is still present. It can be easily reproduced like outlined below.

Currently, this issue is blocking us from upgrading the test harness of `grafana-wtf` to the most recent Grafana release, see https://github.com/panodata/grafana-wtf/pull/44. Maybe it is an easy fix you could schedule for the next patch release?

With kind regards,
Andreas.

## Run Grafana in Docker
```
# Works
docker run --rm -it --publish=3000:3000 --env='GF_SECURITY_ADMIN_PASSWORD=admin' grafana/grafana:9.2.8
# Fails
docker run --rm -it --publish=3000:3000 --env='GF_SECURITY_ADMIN_PASSWORD=admin' grafana/grafana:9.3.0
```

## Invoke requests using HTTPie
```
{apt,yum,dnf,brew} install httpie
http --session=grafana http://localhost:3000/ --auth=admin:admin
http --session=grafana POST localhost:3000/api/folders title=foobar
http --session=grafana DELETE localhost:3000/api/folders/NLCH2w04k
```

## Outcome
On the DELETE request, Grafana 9.2 responds with a JSON payload, while Grafana 9.3 does not.

### With Grafana 9.2.8
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 61
Content-Type: application/json
Date: Tue, 07 Feb 2023 19:35:58 GMT
Expires: -1
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

{
    "id": 2,
    "message": "Folder foobar deleted",
    "title": "foobar"
}
```

### With Grafana 9.3.0
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 0
Content-Type: application/json
Date: Tue, 07 Feb 2023 19:37:10 GMT
Expires: -1
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

<no output>
```

**Comment by amotl** [comment]
Dear @ying-jeanne, @yangkb09, @zserge and @mildwonkey,

first things first: Thanks a stack for your excellent work on wrestling the Grafana backend.

I've identified accb4dea5 from GH-58444 to be responsible for this change in behavior. It also affects to Grafana 8.5.16, while Grafana 8.5.15 still works. If you can find some time to look into this, I would be deeply indebted to you. 🌻 

With kind regards,
Andreas.

**Comment by amotl** [comment]
For your assistance, this is a minimal way to reproduce the error using Python's `requests` library, which shows that it really breaks existing clients and applications, because attempting to decode an empty JSON body croaks. I think the same behavior can well be exercised with other clients which adhere to the HTTP specification.

### Grafana 8.5.15 and 9.2.8
```python
>>> import requests
>>> requests.delete("http://admin:admin@localhost:3000/api/folders/jVmlow0Vk").json()
{'id': 1, 'message': 'Folder foobar deleted', 'title': 'foobar'}
```

### Grafana 8.5.16 and 9.3.0
```python
>>> import requests
>>> requests.delete("http://admin:admin@localhost:3000/api/folders/daFwTwAVz").json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amo/dev/panodata/sources/grafana-wtf/.venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mildwonkey** [comment]
👋 hi @amotl  / Andreas! I'm sorry for the regression, and also sorry for the long silence. I'm adding this issue to our triage board, so it'll get more timely attention. Thanks for the excellent reproduction steps!

**Comment by amotl** [comment]
Dear Kristin,

I know you are very busy. May I humbly ask about the state of this issue? Maybe you can bump it once more? It would be so sweet!

With kind regards,
Andreas.

**Comment by zuchka** [comment]
@grafana/backend-platform

**Comment by amotl** [comment]
Dear @zuchka,

thank you for bumping this.

While we've just worked around this on `grafana-wtf` (https://github.com/panodata/grafana-wtf/commit/a464bddf), in order to make the test suite work again, we are still tracking the issue at https://github.com/panodata/grafana-client/issues/47, with a corresponding suggestion to make Grafana's HTTP responses standards-compliant again.

> It looks like the endpoint is responding with 200 OK, but yields an empty response body. Maybe it should respond with `204 No Content` instead [which would be ok according to the HTTP spec]?

With kind regards,
Andreas.
