### ISSUE TITLE
Template Variables: Query-based. Newlines in query cause silent failure

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#59559]
**What happened**:

See this Loom video:
https://www.loom.com/share/c57c4cfbf6ea40ccbd11b01f727c3037

I'm naturally trying to bend Grafana to my will, so I have a template-var which is query-based, and has a query of reasonable length/complexity, as follows:

```
query_result(
  scalar(
    (sum(grafanacloud_instance_active_series)
    /
    sum(grafanacloud_instance_memory_series)
  )
)
```

Given the complexity I've introduced newlines in order to make it easier to work with.

**BUT** apparently the newlines lead to the query **never actually getting issued/executed.** This is doubly confusing because I **DO** see a "Preview of values" value present, but apparently it's still there and left over from a previous execution, from before I added the newlines 🤯 .

I can tell the query isn't executed, because when I take out all the newlines (and spaces) I get an error message due to a syntax error:

```
query_result(scalar((sum(grafanacloud_instance_active_series)/sum(grafanacloud_instance_memory_series)))
```
> invalid parameter "query": 1:91: parse error: unclosed left parenthesis

Even then, I still see the "Preview of values" populated 🤯🤯. It seems to me we should clear out this "Preview of values" as soon as the query starts failing and stops executing. While it remains it's lying to me, and implying that I will see that value on the dashboard itself for this dash-variable, when in practice I won't see it at all 💔 

Also the Input is exceeding the visual boundaries of the div that it sits inside, which is ugly:
<img width="1095" alt="input wider than parent div" src="https://user-images.githubusercontent.com/2903904/204808406-7e075180-862e-40d9-a493-dab9921712be.png">

**What you expected to happen**:

- Even with newlines, if I have a syntax error in my query code, I should be told that I have a syntax error and asked to fix it
- As soon as the query stops executing (due to syntax error or otherwise) the "Preview of values" should be cleared out.
- The input should not exceed the boundaries set by the parent/ancestor div.

**How to reproduce it (as minimally and precisely as possible)**:
- Use a GrafanaCloud account, which has the `grafanacloud-usage` datasource present
- Create a new dash-var with type "query" and datasource "grafanacloud-usage"
- Paste in the PromQL above, and see the behaviour I'm describing.

**Anything else we should know**:
This is closely related to https://github.com/grafana/grafana/issues/59495 but it is **NOT** a duplicate. This ticket describes separate and additional problems to my previous bug report (and super frustrating ones).

**Environment**:
- Grafana version: [v9.2.7-0f96ed148c (0f96ed148c)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser: macOS 12.6.1 (21G217), Chrome Version 107.0.5304.110 (Official Build) (arm64)

**Comment by tonypowa** [comment]
hello @samjewell  . thanks for creating this issue

I'm tagging the Metrics' squad to acknowledge the new issue regarding missing syntax error feedback in multi-line query. The other issues related to the query editor reported in #59495 have been acknowledged/responded. See comment [here](https://github.com/grafana/grafana/issues/59495#issuecomment-1332297866). 

As for the value preview, and input field issue, I'm tagging the Dashboard's squad.

**Comment by dprokop** [comment]
@samjewell the values preview input field issue should be fixed with https://github.com/grafana/grafana/pull/56326 that was released in 9.3.0.

**Comment by bohandley** [comment]
Hi @samjewell! The work in the above PR will allow newlines in the Prometheus query variable editor when using `query result`. Thank you for bringing this to our attention!

Another feature in this work is that you won't have to wrap your query in the string `query_result(rate(metric)/rate(other_metric))`. Now you can select the Query result query type and then write the only the query in the textarea input.

**Comment by bohandley** [comment]
There was an issue with migrating variables from Jsonnet mixins so the fix had to be reverted. The plan is to update this after GKO. Thank you for your patience.
