### ISSUE TITLE
units may not auto-scale down

### ISSUE THREAD

**Issue by glommer** [grafana/grafana#5955]
* **I'm submitting a ...**
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.0, from dockerhub.
- What datasource are you using? 
prometheus
- What OS are you running grafana on?
ubuntu 14.04
- What did you do? 
I have added a panel with exports units in seconds, but at the moment have very small values, a couple of nanoseconds
- What was the expected result?
I expected the units in the y axis to be scaled down to nanoseconds.
- What happened instead?
The y axis shows powers of 10 of seconds, with negative exponents. Scaling up (ms -> s) seem to work correctly, but not the other way around

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/pull/5642
