### ISSUE TITLE
Grouped columns in bar chart are not colored correctly based on thresholds

### ISSUE THREAD

**Issue by passing** [grafana/grafana#59552]
**What happened**:

I'm using multiple queries in a panel that result in data in columns (min, avg, max) and rows (resource):

![image](https://user-images.githubusercontent.com/8142186/204798108-cddf160e-3d99-46ef-abc9-5cdfd8978755.png)

Using the new bar chart visualization and enabling color schema "From thresholds (by value)" leads to the following result

![image](https://user-images.githubusercontent.com/8142186/204798153-4ea76946-1067-4a93-ab20-d2fe8a8e00f1.png)

**What you expected to happen**:

Each bar should be colored based on its own value, but as the example shows only the values of the last row (resource: requests.memory) of the data are considered: All the 'max' bars are colored yellow which should only be the case for the rightmost bar (which is the only one between 0.4 and 0.5).

**How to reproduce it (as minimally and precisely as possible)**:

- configure queries that create data in columns and rows
- choose bar chart
- configure thresholds

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Bar chart 5.0.0
- OS Grafana is installed on: Ubuntu 22.04
- User OS & Browser: Ubuntu 22.04 / Firefox 107.0
- Grafana plugins: -
- Others: -

**Comment by passing** [comment]
I just found that setting "Gradient mode" to "Scheme" brings the expected result with Grafana 9.3
![image](https://user-images.githubusercontent.com/8142186/204802807-5a35fa48-ff3e-4b0c-a760-affb916ce468.png)

with Grafana 9.2.6 it looks quite different:
![image](https://user-images.githubusercontent.com/8142186/204802394-901b3733-2dbd-462e-b728-1b2cb6c35526.png)

I'm not really sure, if any of that is on purpose and would actually expect individual colors on all bars as a default without having to change the gradient mode.

**Comment by tonypowa** [comment]
Thanks for creating this issue, @passing 

Could you share the panel json ? I will try to reproduce the behavior from my end

To share the panel JSON: `1` From your dashboard, click on the arrow next to the panel's name >`2` from the options, select Inspect >`3` PANEL JSON)

**Comment by passing** [comment]
@tonypowa here's the panel json
```json
{
  "id": 58,
  "gridPos": {
    "h": 5,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "barchart",
  "title": "$namespace",
  "repeat": "namespace",
  "transformations": [
    {
      "id": "merge",
      "options": {}
    },
    {
      "id": "organize",
      "options": {
        "excludeByName": {},
        "indexByName": {},
        "renameByName": {
          "Time": "",
          "Value #avg": "avg",
          "Value #max": "max",
          "Value #min": "min",
          "resource": ""
        }
      }
    },
    {
      "id": "filterFieldsByName",
      "options": {
        "include": {
          "names": [
            "resource",
            "min",
            "avg",
            "max"
          ]
        }
      }
    },
    {
      "id": "sortBy",
      "options": {
        "fields": {},
        "sort": [
          {
            "desc": false,
            "field": "resource"
          }
        ]
      }
    }
  ],
  "datasource": {
    "type": "prometheus",
    "uid": "${datasource}"
  },
  "pluginVersion": "9.2.6",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 1,
        "fillOpacity": 80,
        "gradientMode": "scheme",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "thresholds"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 0.4
          },
          {
            "color": "red",
            "value": 0.5
          }
        ]
      },
      "decimals": 1,
      "max": 1,
      "min": 0,
      "unit": "percentunit"
    },
    "overrides": []
  },
  "options": {
    "orientation": "auto",
    "xTickLabelRotation": 0,
    "xTickLabelSpacing": 0,
    "showValue": "always",
    "stacking": "none",
    "groupWidth": 0.9,
    "barWidth": 0.97,
    "barRadius": 0,
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "text": {
      "valueSize": 12
    },
    "xField": "resource"
  },
  "targets": [
    {
      "datasource": {
        "uid": "${datasource}"
      },
      "editorMode": "code",
      "exemplar": false,
      "expr": "min_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"used\"}) by (resource) [${__range_s}s:]) / max_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"hard\"}) by (resource) [${__range_s}s:]) ",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "min {{ resource }}",
      "range": false,
      "refId": "min"
    },
    {
      "datasource": {
        "uid": "${datasource}"
      },
      "editorMode": "code",
      "exemplar": true,
      "expr": "avg_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"used\"}) by (resource) [${__range_s}s:]) / max_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"hard\"}) by (resource) [${__range_s}s:]) ",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "max {{ resource }}",
      "refId": "avg"
    },
    {
      "datasource": {
        "uid": "${datasource}"
      },
      "editorMode": "code",
      "exemplar": true,
      "expr": "max_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"used\"}) by (resource) [${__range_s}s:]) / max_over_time(sum(kube_resourcequota{namespace=~\"$namespace\", resourcequota=~\"$resourcequota\", resource=~\"$resource\", type=\"hard\"}) by (resource) [${__range_s}s:]) ",
      "format": "table",
      "hide": false,
      "instant": true,
      "interval": "",
      "legendFormat": "max {{ resource }}",
      "refId": "max"
    }
  ],
  "scopedVars": {
    "namespace": {
      "text": "xxx",
      "value": "xxx",
      "selected": true
    }
  }
}
```

**Comment by leeoniya** [comment]
the coloring changes in 9.3 are intentional, so that rendered thresholds don't look like stacked bars (which is also a mode). see https://github.com/grafana/grafana/pull/58285.

> I just found that setting "Gradient mode" to "Scheme" brings the expected result with Grafana 9.3

i think this is logically consistent, but can probably use docs? a hint? i'm not sure.

**Comment by passing** [comment]
@leeoniya thank you for the feedback.

in my opinion, as soon as you enable "Color scheme: From thresholds (by value)", the first 3 "Gradient Mode" options are not very useful, as none of them colors the bars by their individual value (see below). And for me it was confusing, that I had to change the "Gradient Mode", while not being interested in any gradient, and that dropdown is quite far away from the "Color scheme"

![image](https://user-images.githubusercontent.com/8142186/205103710-db9178aa-42e6-48b3-94af-29f1ee42cfd9.png)
![image](https://user-images.githubusercontent.com/8142186/205103917-249fd334-79bf-4ab5-b7c9-82e2bf4c6623.png)
![image](https://user-images.githubusercontent.com/8142186/205103811-55b28b9f-8cb0-48db-a96d-ffb1f43df796.png)
![image](https://user-images.githubusercontent.com/8142186/205103830-ddf677c4-2890-491f-9001-c5deaf309ce6.png)
