### ISSUE TITLE
Feature Request: Single Stat Trends

### ISSUE THREAD

**Issue by eMerzh** [grafana/grafana#5959]
- *_I'm submitting a [ X ] Feature request *_
  for Grafana 3.1.1 influx/graphite

it would be cool to have in the single stat (or in another similar widget), the ability to summarize the trend of the KPI.

like you want to monitor the number of download per day...if i display the number , say 42, it won't say much .... but if you include an arrow up or maybe +42% it can have really much more value.

The trend can be computed over the half the period (first half for previous number, second half for the current number) or over the same amount of time before the period or smth like this

visually it could be represented like this

<img width="684" alt="capture d ecran 2016-09-03 a 14 52 11" src="https://cloud.githubusercontent.com/assets/177003/18224911/12e3f8ee-71e6-11e6-873c-8bdb55e0bd63.png">
<img width="530" alt="capture d ecran 2016-09-03 a 14 51 56" src="https://cloud.githubusercontent.com/assets/177003/18224912/12f87652-71e6-11e6-8179-ac89c6cbf675.png">
<img width="394" alt="capture d ecran 2016-09-03 a 14 43 23" src="https://cloud.githubusercontent.com/assets/177003/18224913/1311cfe4-71e6-11e6-94f4-e08c3a6789b7.png">
<img width="303" alt="capture d ecran 2016-09-03 a 14 53 40" src="https://cloud.githubusercontent.com/assets/177003/18224917/4038fc54-71e6-11e6-8704-2717df806ff9.png">

**Comment by Rucknar** [comment]
This would be super useful for me too. Currently i'm doing two smaller single stat panels to get the same data. It means it's a lot less clean and feels like it could be made easier. I feel the 2nd example in your post suits this the closest.

**Comment by tfylling** [comment]
I too have been sorely missing this. I would suggest using a second metric series for the trend calculation. That way you're not limited to the same resolution (eg last day's metric compared to average of last month), or even the same data (eg cpu usage of single node vs average across the cluster).

**Comment by schdief** [comment]
would love this, I started with Kibana, then switched to Grafana for the RBAC and now considering to switch again to Graylog, since they have trends and RBAC

**Comment by tablatronix** [comment]
Need this!

**Comment by sourabhsharma-cpi** [comment]
totally need this !!

**Comment by uptickmetachu** [comment]
@torkelo Can we revive this feature request? Its currently stuck in the backlog of a deprecated BI squad.

This is a sorely lacking feature that makes it very hard to use grafana for BI purposes. All BI apps have some ability to easily report the trend of a stat.

**Comment by leeoniya** [comment]
yep, we'll discuss this internally next week.
