### ISSUE TITLE
Public dashboard only showing one query per panel

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#59601]
**What happened**:

When viewing public dashboard only one query is shown per panel.

**What you expected to happen**:

Panel should show all queries as seen when viewing dashboard normally.

**How to reproduce it (as minimally and precisely as possible)**:

 * Clean install.
 * Add graphite data source.
 * Create new dashboard.
 * Create new panel. 
 * Select a graphite metric.
 * Add another query and select different graphite metric.
 * Apply
 * See graph with two lines, one per query.
 * Save dashboard.
 * Share dashboard as public.
 * Go to public URL. 
 * See graph only has one line.

**Anything else we need to know?**:

It appears to be showing only the last query. If I change order of queries then I see the other line is shown. If I use wildcard query then multiple lines of that query shown if that query is the last but still no other queries show.

![image](https://user-images.githubusercontent.com/2304970/204868363-277c83d3-b1a7-4857-ae31-667e9c65b217.png)

Also tried with Gauge panel, same issue.

**Environment**:
- Grafana version: 9.3.0 and 9.4.0-90933pre 
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, FF.
- Grafana plugins: None
- Others:

**Comment by mmandrus** [comment]
Hi @bobemoe, we've confirmed that this is an issue due to some problems in the graphite datasource backend code. We have begun working on a fix.

**Comment by jalevin** [comment]
We will need to audit all core datasources to figure out if they're calling a different endpoint from /ds/query

**Comment by mmandrus** [comment]
Thanks for reporting this, the fix is merged and will be released in 9.3.2.
