### ISSUE TITLE
Google Auth: send "hd" parameter in the request

### ISSUE THREAD

**Issue by xose** [grafana/grafana#5960]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request

Please include this information:
- What Grafana version are you using? 3.1.1
- What did you do?
  - Enabled Google auth
  - Set allowed_domains to my Google Apps domain
- What was the expected result?
  - The Google account selector displays only accounts from my Google Apps domain
- What happened instead?
  - Both Google Apps and gmail.com accounts show up

The Google OAuth flow accepts an extra "hd" (hosted domain) parameter to state which domain is allowed to login. Only accounts from that domain will show up on the account selector, and in the event that no account from that domain is available, the UI will hint which accounts are allowed and will forbid logins from any other domain.

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

**Comment by ericuldall** [comment]
Pull request open to add this feature.
