### ISSUE TITLE
[Feature request] Alter $timeFrame to match group by boundaries

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/grafana#5961]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I have a server which sends datapoints every 10s to the influxdb backend (at :02, :12, :22, :32, :42, :52).
The group by interval in Grafana is restricted to `>10s`.
Now when I select a time range of e.g. last day, the automatic group by variable `$interval` is set to 1m.
If the selected timeframe is from e.g. 00:00:04 until 23:59:51, the first and last group of the result is misleading, because the data points at :02 and at :52 is not included.
The same happens when multiple servers are sending datapoints to the database, and due to a inadequate timeframe in combination with the group by interval, the first and last group/bucket can be misleading (missing data points from one or more servers).

I think the best solution for this problem is to slightly alter the `$timeFilter` variable to match exactly the group by boundaries. In the example above, if the user enters 00:00:04 until 23:59:51, it should change the query to select the data from 00:00:00 until 23:59:59.
Of course I'm open to alternative approaches as well (maybe a solution for this problem already exists?)

(Limiting the group by interval to exactly 10s is a solution, but not a good one if the user requests a graph for e.g. the last month)

I'm using Grafana v3.1.1 and InfluxDB as datasource.

**Comment by phemmer** [comment]
I opened an issue several months ago on the InfluxDB side which would address this problem: https://github.com/influxdata/influxdb/issues/8010
I think the problem would be better addressed there since it applies to all clients, not just grafana. However depending on the implementation, it might still need support from grafana, such as enabling the behavior.

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/3781

**Comment by p3r7** [comment]
Hello,

Facing the same situation, at [Transatel](https://github.com/Transatel) we decided to solve it by making an HTTP proxy to handle this: [Transatel/cleanflux](https://github.com/Transatel/cleanflux).

We've been using it for 2 whole years, both from Grafana and various scripts (including Jupyter notebooks).

For now, it is quite declarative (retention policies have o be redeclared in proxy configuration) but this solution is pretty robust and transparent for the client.

In addition, it also solves issues [#5961](https://github.com/grafana/grafana/issues/5961) and [#8010](https://github.com/influxdata/influxdb/issues/8010).
