### ISSUE TITLE
cannot add oauth user to ogranization in latest 9.2

### ISSUE THREAD

**Issue by tobhv** [grafana/grafana#59610]
I have the exact same issue as described here:
https://github.com/grafana/grafana/issues/59282 
but then for generic oauth.
* i do not want the oauth provider to set the role or organization.
* i want to set the role and organization from within grafana.
* this is not possible anymore since 9.2.<latest> , it did work in previous 9.2 versions.
see also here: https://github.com/grafana/grafana/pull/55182 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.6, 9.2.7 (do not work)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tobhv** [comment]
reverting back to 9.0.X resolves the issue for me.

**Comment by mellieA** [comment]
@tobhv did you try the setting [oauth_skip_org_role_update_sync](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#oauth_skip_org_role_update_sync)?

**Comment by tobhv** [comment]
yes. i switched oauth_skup_org_role_update_sync to false or true. either way it does not solve it on 9.2.X (X being lateer versions).

**Comment by tobhv** [comment]
i am not entitled to re-open this issue, but i can create a new one.

**Comment by tobhv** [comment]
hmmm. just upgraded to 9.3.1 and there behavior is fine as long as i set oauth_skup_org_role_update_sync to true. sorry for the confusion and thanks for your attention.

**Comment by mellieA** [comment]
I re-opened for you.

Can you share the following to help us identify if there is a bug: 
- config settings exactly as they are in your instance. You can obscure any sensitive information.  
- enable [debug logging](https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs) and share the log after restarting grafana
- share screenshots to show what you see when you navigate to change the user's org
