### ISSUE TITLE
Azure Monitor: Metrics Dimensions no longer work in 9.3.0

### ISSUE THREAD

**Issue by NosIreland** [grafana/grafana#59629]
**What happened**: 
Upgraded to 9.3.0 and panels that use Azure Metrics with dimensions no longer work. Getting `request failed, status: 400 Bad Request`
![image](https://user-images.githubusercontent.com/19308746/205021410-f4098e0f-032a-4f13-aeef-3a05fdb695b9.png)
If dimensions are removed they work fine.
This has worked prior 9.3.0 version(9.2.6, 9.2.1 ,9.1.7)

**What you expected to happen**:
The panels should keep on working

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to 9.3.0
Add a panel and use Azure datasource, select any metric and add dimension to metric, you shoudl see `request failed, status: 400 Bad Request` when dimension is added

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 9.3.0
- Data source type & version: Azure Monitor
- OS Grafana is installed on: AKS
- User OS & Browser: Any
- Grafana plugins: NA
- Others:

**Comment by DannyArr** [comment]
Experiencing the same. Fine again when downgrading to 9.2.7. I've attached some data from the errors as well. It doesn't seem to like POST calls.

> error:"request failed, status: 400 The 'POST' is not supported for this request, please use 'GET'."

[GrafanaAzureMonitor_error.docx](https://github.com/grafana/grafana/files/10134169/GrafanaAzureMonitor_error.docx)

**Comment by zuchka** [comment]
[This was merged into 9.3](https://github.com/grafana/grafana/pull/54829), and it looks like the [grafana-azure-sdk got some updates](https://github.com/grafana/grafana-azure-sdk-go/commits/main) as well. Maybe those changes broke something?...

**Comment by andresmgot** [comment]
I see the problem. The query filter is now encoded in a POST body to avoid the 2048 character limit of an URL but POST requests are only supported at the subscription level, not when requesting a single resource. Let me send a patch.
