### ISSUE TITLE
Grafana Digest

### ISSUE THREAD

**Issue by Michsh** [grafana/grafana#5962]
I want to do a proxy authentication with Digest. My apache website in witch i will export my Grafana iframe use Digest authentication.
I realized proxy but with Basic authentication. 
Any idea will be great ;).

**Comment by torkelo** [comment]
Basic auth:
http://docs.grafana.org/installation/configuration/#authbasic

Proxy Auth:
http://docs.grafana.org/installation/configuration/#authproxy


Could you describe in detail how you wish the digest auth should work and be configured?

**Comment by Michsh** [comment]
MY website (digest)  import grafana chart using a single authentication.

**Comment by Michsh** [comment]
I setup a Digest configuration for grafana in my apache conf and now in my grafana server and now i get in log:
 msg="Invalid Basic Auth Header" logger=context error="Invalid basic auth header"

**Comment by torkelo** [comment]
@Michsh yes, Grafana does not support Digest auth so that is not so surprising.
