### ISSUE TITLE
Tooltip shows invalid values

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5963]
![image](https://cloud.githubusercontent.com/assets/618863/18241855/b21394ec-7353-11e6-8d12-c191f809efdc.png)

The series below state_ok should be zero

**Comment by torkelo** [comment]
sure?

**Comment by bergquist** [comment]
@torkelo nope :) Forgot that I enabled "stacked"

**Comment by cincodenada** [comment]
@bergquist What people want in the tooltip depends on the data.  In the "Display" tab under the "Multiple series" options (right under the "Stack" checkbox) there's a dropdown to select whether you want to display cumulative or individual values in the tooltip.  You probably want to switch to individual.
