### ISSUE TITLE
Grafana 3.1.1 : InfluxDB Error: undefined 

### ISSUE THREAD

**Issue by uzfarid** [grafana/grafana#5964]
* **I'm submitting a ...**
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
0.8
- What OS are you running grafana on?
Amazon Linux
- What did you do?
Added new datasource.
- What was the expected result?
Datasource supposed to be tested and pass 
- What happened instead?
InfluxDB error: undefined happened.  In Developer tools if we use localhost:8086, it says connected refused, but if we use IP then we get 404 i.e not found.

Full url in this case, for influxdb, is http://ip:8086/query?u=root&p=root&db=jmeter&q=SHOW%20MEASUREMENTS%20LIMIT%201&epoch=ms

In grafana logs it only says:
"ime_ns=0 size=29
t=2016-09-05T09:06:54+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.116.161.31 time_ns=0 size=29
t=2016-09-05T09:07:13+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.116.162.188 time_ns=0 size=29
t=2016-09-05T09:07:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.116.162.160 time_ns=0 size=29
t=2016-09-05T09:07:23+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.116.161.52 time_ns=0 size=29
t=2016-09-05T09:07:24+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.116.161.31 time_ns=0 size=29
"
in 3.1.1 during datasource selection it just mentions InfluxDB i.e it does not have option of selecting influxdb 0.9 or 0.8

thanks
br
Farid

**Comment by uzfarid** [comment]
I installed influxdb 0.8 plugin, but I get the following error now when I add datasource

XMLHttpRequest cannot load http://ip:8086/db/jmeter/series?q=list+series. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by torkelo** [comment]
Strange, try proxy access mode

**Comment by uzfarid** [comment]
yes that did solved the issue.

**Comment by andyl** [comment]
I ran into this issue after upgrading from 3.1.x to 4.0 beta2.  Switching to proxy mode solved the problem for me as well.

**Comment by vskubriev** [comment]
Switch to proxy mode in `data source` solving an issue:

`Edit data source -> Http settings -> Access -> SELECT "proxy".`
