### ISSUE TITLE
Dashboard versions: Listing versions queries ignore the dashboard UID even if it's present

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#59643]
**What happened**:

The [xorm](https://github.com/grafana/grafana/blob/0d4fd305c457fc1b559a67a7b283937cc899dee7/pkg/services/dashboardversion/dashverimpl/xorm_store.go#L74) and [sqlx](https://github.com/grafana/grafana/blob/0d4fd305c457fc1b559a67a7b283937cc899dee7/pkg/services/dashboardversion/dashverimpl/sqlx_store.go#L62) store implementations ignore the dashboard UID (even though it's set) when listing dashboard versions

**What you expected to happen**:

Need to give precedence to dashboard UID if it's present

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by johnmantios** [comment]
Hi! Is this still up for grabs? I am interested in tackling this but I am not sure how to reproduce the issue (also first contribution to grafana)

**Comment by MTLChrisLEE** [comment]
@papagian.
This can be closed, right?
It seems the PR 60800 was for this

**Comment by papagian** [comment]
> @papagian. This can be closed, right? It seems the PR 60800 was for this

right, it's fixed by #60800
thank you for bringing it into my attention
