### ISSUE TITLE
Table cell background color

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#59659]
**What happened**:
Visibility of colored lines in table is not as good as before. Missing line breaks.

Grafana 9.3
![image](https://user-images.githubusercontent.com/66313770/205081431-804db93e-5968-4745-abc7-a94c05fe261e.png)

Older Grafana
![image](https://user-images.githubusercontent.com/66313770/205081502-1771b621-d675-437c-bad0-d3223d2d60a1.png)

**Comment by torkelo** [comment]
@edin008 thanks for reporting this, fixed! https://github.com/grafana/grafana/pull/59660
