### ISSUE TITLE
Timerange: Using "relative time" does not take timezone into account

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#59665]
**What happened**:

When using the "relative time" from the query options of a panel, this uses the browser timezone instead of the dashboard selected timezone.

Browser in UTC:
<img width="835" alt="Screenshot 2022-12-01 at 16 45 52" src="https://user-images.githubusercontent.com/100691367/205110774-7d9067db-5504-4137-bb8d-b43d9f715910.png">

**What you expected to happen**:

Relative time takes dashboard timezone into account

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a timeseries panel and change the dashboard timezone to something that is not your timezone
2. On "query options > relative time" write down "now/d" and notice how the chart does not start at 00:00

**Anything else we need to know?**:

This was started from an escalation: https://github.com/grafana/support-escalations/issues/4570
Seems to be related to this function that does not take timezone as an argument: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/utils/panel.ts#L114

**Environment**:
- Grafana version: 9.3.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by eledobleefe** [comment]
➕  We can also see in [this escalation](https://github.com/grafana/support-escalations/issues/5018) that `TimeRange` does not take `timezone` into account.

**Comment by JoaoSilvaGrafana** [comment]
Similarly, [this issue](https://github.com/grafana/grafana/issues/47486) mentioned how it does not work when using relative time ranges in the `TimePicker`
