### ISSUE TITLE
[Bug] Wrong alias using groupByNode() and summarize() functions 

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [grafana/grafana#5967]
Submitting a bug report.
This bug appears in Firefox 47 and Chrome 53 on Ubuntu 15.
In the past I was able to fix it by moving the functions around in the graph editor, now it seems impossible to avoid it.

If I select a summarize() followed by a groupByNode() function, the alias on the labels is wrong:

groupByNode(summarize(collectd-helix.z-lhr1-esearch-101_zanox_com.cpu-*.*, '$interval', 'avg', true), 3, 'avg')

Labels:
cpu-idle, "5min", "avg", true)
cpu-interrupt, "5min", "avg", true)
cpu-nice, "5min", "avg", true)
...

Instead of:
cpu-idle
cpu-interrupt
cpu-nice
...

I cannot use any aliasByNode function to fix the issue, graphite returns an error.
The only fix I found is using aliasSub().

aliasSub(summarize(groupByNode(collectd-helix.z-lhr1-esearch-101_zanox_com.cpu-*.*, 3, 'avg'), '$interval', 'avg', true), 'summarize\((.*), ".*", ".*", .*\)', '\1')

**Comment by torkelo** [comment]
please open with graphite project
