### ISSUE TITLE
Support bucket script pipeline aggregations

### ISSUE THREAD

**Issue by obernal** [grafana/grafana#5968]
It would be great to be able to do custom aggregations using scripts. This is achieved through bucket script aggregations. For example we need to be able to do something like this:

<img width="1409" alt="screen shot 2016-08-27 at 4 51 25 pm" src="https://cloud.githubusercontent.com/assets/379148/18257687/64a28c92-738d-11e6-97b3-bf4d3ddc461b.png">

Where I can take the difference between two fields and plot it or show it in a table panel. 

For reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-script-aggregation.html

**Comment by jisaitua** [comment]
+1

**Comment by mekalz** [comment]
+1

**Comment by obernal** [comment]
There's a PR I submitted, waiting to be reviewed for some time now. https://github.com/grafana/grafana/pull/5918 Not sure why there hasn't been any response yet. Hopefully the maintainers will get to it soon.

**Comment by id3a** [comment]
We need support to this type of pipeline aggregations asap!
Is this feature on the roadmap?

**Comment by jisaitua** [comment]
This is a much needed feature for elasticsearch. What is needed to get #5918 accepted?

**Comment by markuslindberg** [comment]
This is exactly what I'm looking for! A much needed feature for the elasticsearch datasource.

**Comment by skywalker-gk** [comment]
+1.
This is a much needed feature for elasticsearch.

**Comment by bela0av** [comment]
+1

**Comment by mgatien** [comment]
+1

**Comment by mmatson** [comment]
+1

**Comment by vnikitov** [comment]
+1

**Comment by marcusianlevine** [comment]
+1 please re-open the PR #5918 !!! this would be great for latency calculation, current workaround requires additional epoch time fields...

**Comment by PeterWeiler** [comment]
+1

Without an ability to directly input queries, as is possible with the "toggle edit mode" of the InfluxDB data source, there isn't a way to make this work in Grafana.

**Comment by erouvin** [comment]
+1

Definitely needed for Singlestat panel to display percentage combining several fields.

**Comment by Toyto** [comment]
+1

**Comment by jkristensen** [comment]
+1

**Comment by nielslerches** [comment]
+1

**Comment by Emillos** [comment]
+1

**Comment by fjgal** [comment]
+1

**Comment by grantjosh** [comment]
+1

**Comment by usrlocalsbin** [comment]
+1

**Comment by konradkonrad** [comment]
I definitely have the need for custom aggregations -- ideally as free form json.
I want to aggregate based on a nested filter, i.e.
```
nested -> filter -> TERMS -> reverse_nested -> nested -> filter -> STATS
```
I don't see how this could be supported just through forms...

**Comment by bartebor** [comment]
This is very useful feature. We are drawing numerous ratios in kubernetes clusters, for example CPU usage to CPU request. ElasticSearch support in grafana lacks free-form queries like i.e InfluxDB limiting available options drastically. This FR gets the job done for most cases and I personally think it should be merged in (alternatively there could be a possibility of enabling raw ES queries for graphs/stats).

**Comment by Jordiherrero** [comment]
+1

**Comment by tamsl** [comment]
I need this too, would be great!

**Comment by dannygoulder** [comment]
Adding my vote for this feature!

**Comment by kccheung** [comment]
+1

**Comment by PepeLopez** [comment]
+1
Why it's not done yet!?

**Comment by UKSFM99** [comment]
+1

**Comment by Daphneitec** [comment]
We need it in elasticsearch, will it be in the next release?

**Comment by genthalili** [comment]
+1

**Comment by stossy** [comment]
+1

**Comment by a3mar** [comment]
+1

**Comment by mailo84** [comment]
+1 plz!

**Comment by zhka** [comment]
+1

**Comment by sijver** [comment]
+1

**Comment by apobbati** [comment]
Has there been any effort on getting the PR merged?

**Comment by Haurau** [comment]
+1

**Comment by unvaluedcustomer** [comment]
+1

**Comment by DvirM** [comment]
+1 - being able to sum 2 fields is something we definitely can use. thanks!

**Comment by melrom** [comment]
+1 - we need this SO MUCH.

**Comment by saadsarfrazz** [comment]
+1

**Comment by saadsarfrazz** [comment]
> +1 - being able to sum 2 fields is something we definitely can use. thanks!

This could be useful if it is not pipeline aggregation I think.
https://community.grafana.com/t/basic-elastic-search-query/1543/18

**Comment by faxm0dem** [comment]
please implement this!

**Comment by yanivroz** [comment]
+1

**Comment by xuxiaohu** [comment]
+1

**Comment by bmfmsd** [comment]
+1
