### ISSUE TITLE
Apostrophe in the metric cause reset query path after " back to the edit tab " (the graph works)

### ISSUE THREAD

**Issue by claenjoy** [grafana/grafana#5972]
- **I'm submitting a ...**
- [ X] Bug report

Please include this information:
- What Grafana version are you using?  3.1.1-1470047149
- What datasource are you using? icinga2-graphite
- What OS are you running grafana on?  debian 8.5
- What did you do?  Select a query with apostrophe included in the name metric 
- What was the expected result? to store the query path after save
- What happened instead?  the  query path is reset until the metric with apostrophe in the name  the graph is not reset only path metric

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

![screenshot from 2016-09-06 15-00-39](https://cloud.githubusercontent.com/assets/2983049/18276448/e63f5f86-7442-11e6-8c6e-78ffe1ba0297.png)

**Comment by aocenas** [comment]
Hey @claenjoy As this is a bit old I am going to close this. If this is still happening please reopen and add more details.
