### ISSUE TITLE
Expressions do not work with queries using dashboard variables

### ISSUE THREAD

**Issue by gstephant** [grafana/grafana#59730]
**What happened**:
The dashboards variables can't be used with a query + and expression

![Video-Fri-Dec-02-2022-15-13-54](https://user-images.githubusercontent.com/22791611/205313370-56684310-88b3-42de-a08a-e628db1592ee.gif)

As soon as an expression is added, a query using a variable do not give any result

**What you expected to happen**:

The result of the first query should be used in the expression

**How to reproduce it (as minimally and precisely as possible)**:

1. Build a dashboard variable. a simple custom one with a numeric value. 
2. Add a stat panel in format table
3. Build a simple sql query such as "select $var"
4. Add an expression using the result of the query such as "$A"
5. "No data" is displayed with an error

What has caught my attention in the query inspector is the rawSql field.
with the expression I read for the query : rawSql:"select $var"
without the expression I read for the query : rawSql:"select 10"

**Anything else we need to know?**:

I reproduced it with mysql and elasticsearh queries

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Mysql 5.7 & elasticsearch 6.4
- OS Grafana is installed on: ubuntu 16.04
- User OS & Browser: ubuntu mate & chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @gstephant 

I am not 100% sure but I don't know how compatible template variables (client-side) are with expressions (server-side). Server side expressions were mostly developed to power the new alerting platform.

I would try and make use of transformations for these kinds of data transforms inside a dashboard panel. We have an extensive number of transformations to choose from and they are well maintained/developed:

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/
