### ISSUE TITLE
Node Graph edge ContextMenu will not open if source and target nodes are positioned too closed by 

### ISSUE THREAD

**Issue by perotta** [grafana/grafana#59733]
**What happened**: On a Node Graph, when two nodes are too close toghether, trying to open the edge ContextMenu is impossible because it always open one of the nodes ContextMenu

Near nodes (bug):
![image](https://user-images.githubusercontent.com/45238586/205335234-397eb4b7-839a-483d-91fb-183077470c64.png)

Far nodes (works as expected)
![image](https://user-images.githubusercontent.com/45238586/205335470-5db3615b-e435-40ab-af8a-861e0d0026c4.png)

**What you expected to happen**: When clicking on an edge (and maybe more precisely the edge main stat box), I expect it to always open the edge ContextMenu, not the node ContextMenu.

**How to reproduce it (as minimally and precisely as possible)**: Create NodeGraph panel, pull Test Data DB with Node Graph scenario data type response. Then try opening edge ContextMenu for edge between the yellow and green nodes on the left 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Test Data DB
- OS Grafana is installed on: Debian 1
- User OS & Browser: Ubuntu 20.04 Chrome 107.0.5304.121
- Grafana plugins: Test Data DB datasource
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @perotta 

I'm also having trouble selecting some of the edge context menus on [this panel on our public sandbox](https://play.grafana.org/d/0KEnAyKVz/59733?orgId=1)? 👍 

![CleanShot 2022-12-06 at 12 17 30](https://user-images.githubusercontent.com/37156449/206035681-eda3d7df-f484-4e1c-855b-8eeac92a113a.gif)
