### ISSUE TITLE
Support for Annotation Templating

### ISSUE THREAD

**Issue by gurumeditator** [grafana/grafana#5974]
* **I'm submitting a ...**
- [x] Feature request

I would like the ability to use templating for event queries. Is this possible?

datasource: Graphite

**Comment by torkelo** [comment]
yes

**Comment by gurumeditator** [comment]
Is it possible to illustrate? I used the form:

```
$templateVar.$anotherTemplateVar.x.y
```
for the "Or Graphite events query" field, but, the annotations did not render as they did with hard coded values.

**Comment by torkelo** [comment]
Does your tags look like that? Open chrome dev tools and look at network request grafana makes to Graphite and it's response, maybe a little graphite issue

**Comment by gurumeditator** [comment]
Thanks for the reply. This looks to be a graphite query problem. The templates were resolving, but, I also had a wildcard in the event query string which is not resolving. I see that querying for graphite events using just the "*" works, but, I haven't been able to determine by the documentation if "someText*" is supported. Thanks for the help
