### ISSUE TITLE
Show Historical Data Graph by Default

### ISSUE THREAD

**Issue by tekzoom** [grafana/grafana#5975]
* **I'm submitting a ...**
- [x] Feature request

Show historical data graph by default. Let say we have historical time series data pushed to the database between 07/10/2015 and 07/20/2015 and there would be no data anymore of this type afterwards. This feature sets the time range to above and shows the graph.

**Comment by torkelo** [comment]
How would grafana know what the time range fore which there is data?

**Comment by tekzoom** [comment]
Providing the min and max of the time in the query.

**Comment by torkelo** [comment]
Just zoom on where there is data

**Comment by tekzoom** [comment]
With thousand of tags and corresponding date ranges it is pretty labor intensive. I thought it would be nice to have that feature almost similar to what Chronograph offers which automatically shows the graph when a tag key is selected.

**Comment by torkelo** [comment]
What do you mean? Tag key selected? Would you like to select the series name and have them time range changed to where that time range begin and end?

**Comment by tekzoom** [comment]
By tag name I meant filter or whatever goes in WHERE clause. IfluxDB calls it that way. Yes, I would like to select the tag key and have the tool show the graph where the time range begin and end. Thanks.
