### ISSUE TITLE
Alerting: Silence button not working with external alertmanager

### ISSUE THREAD

**Issue by frankyi-gh** [grafana/grafana#59750]
**What happened**:
Clicking the "silence" button on an alert rule while having an Alertmanager data source with "Receive Grafana Alerts" enabled always creates the silence in the internal Alertmanager data source. This happens even with the setting "Send alerts to = Only External".

**What you expected to happen**:
Silences are created in the external Alertmanager. Or if that's not possible for some reason, the "silence" button should not appear.

**How to reproduce it (as minimally and precisely as possible)**:
* create Alertmanager data source with "Receive Grafana Alerts" enabled 
* set "Send alerts to" to "External Only"
* click "Silence" on any alert rule

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3
- Data source type & version: Alertmanager
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS 12.3, Chrome
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
We were able to reproduce this issue, this is owned by frontend.

**Comment by TaylorMutch** [comment]
Hello; unfortunately with [this change](https://github.com/grafana/grafana/pull/62133), those those of us who configure Mimir to act as the alertmanager, it seems it is no longer possible to send silences to the external alertmanager. Would it be possible to allow this functionality to coexist? This makes it impossible for us to mute alerts simply like we could before when viewing an individual Mimir-based alerting rule.

**Comment by Swaps76** [comment]
Yes please also in the same boat, also I'm not sure what 'Matching labels' are needed to create the silences, Ive tried using the ones displayed in the alert itself but no affected alerts show up.
