### ISSUE TITLE
ARG queries throw error when no data is returned

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#59762]
**What happened**: If I write a query that returns no data, panel shows an error instead of simply showing no data: 

![image](https://user-images.githubusercontent.com/20448042/205412880-b80d0806-b4b8-4124-8c7d-c49dc2f36e9a.png)

This is the same panel when I use where conditions that make the query return data: 

![image](https://user-images.githubusercontent.com/20448042/205412949-c6760bd3-207d-4b98-835c-8bc8ef650fc1.png)

**What you expected to happen**:

No error to be returned if the query returns no data

**How to reproduce it (as minimally and precisely as possible)**:
1. Right any valid ARG query that does not return any data
2. tweak it to show data (time picker change, variable change, etc)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.7.1 
- Data source type & version: Azure Monitor 1.0.0
- OS Grafana is installed on:
- User OS & Browser: Windows & Edge
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @jcolladokuri,

Thanks for opening this issue.

Could you please provide us with the backend logs so that we can have more information about the error message?

Also, just want to understand the naming abbreviation ARG, what it stands for?

**Comment by andresmgot** [comment]
Hi @jcolladokuri, thanks for submiting the issue! We are aware of it. We have fixed it in https://github.com/grafana/grafana/pull/59691 and will be available in the next patch version (9.2.8 or 9.3.2).
