### ISSUE TITLE
Stat panel incorrectly measures text causing it to clip

### ISSUE THREAD

**Issue by SensSebastianSchlosser** [grafana/grafana#59766]
**What happened**:
Auto-Fontsize doesn't work properly. The text is cut off.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/117441229/205441351-e5cf6c13-c790-44f1-8758-a8dbb8bf2903.png">

**What you expected to happen**:
Text resize proberly

**How to reproduce it (as minimally and precisely as possible)**:
Here is the JSON from my Stat-Panel.
Here I just went for a "Select 'blabla'" request to SQL for demo-purpose.
```
{
      "datasource": {
        "type": "mssql",
        "uid": "6IyHxWQ7z"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 2,
        "w": 4,
        "x": 0,
        "y": 9
      },
      "id": 103,
      "options": {
        "colorMode": "background",
        "graphMode": "none",
        "justifyMode": "auto",
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "last"
          ],
          "fields": "/^Value$/",
          "values": true
        },
        "text": {},
        "textMode": "value"
      },
      "pluginVersion": "9.2.7",
      "targets": [
        {
          "datasource": {
            "type": "mssql",
            "uid": "6IyHxWQ7z"
          },
          "editorMode": "code",
          "format": "table",
          "rawQuery": true,
          "rawSql": "SELECT 'Ausreichend Batterie'",
          "refId": "A",
          "sql": {
            "columns": [
              {
                "parameters": [],
                "type": "function"
              }
            ],
            "groupBy": [
              {
                "property": {
                  "type": "string"
                },
                "type": "groupBy"
              }
            ],
            "limit": 50
          }
        }
      ],
      "transformations": [],
      "type": "stat"
    },
```
You may need to play with the size of the resolution (2582px*800px in my case)

**Anything else we need to know?**:
When I disable the "Font-Weight" in the css-settings on the "elements"-tab in the "resizing" is working the intended way.
<img width="188" alt="image" src="https://user-images.githubusercontent.com/117441229/205441674-c8068d03-088d-4fae-8b98-fb9389a4c4f8.png">
<img width="479" alt="image" src="https://user-images.githubusercontent.com/117441229/205443059-da3cfcf6-16ee-43d1-b804-30975a7db061.png">

**Environment**:
- Grafana version: v 9.2.7
- Data source type & version: irrelevant
- OS Grafana is installed on: Linux
- User OS & Browser: All (Opera, Chrome, Edge, ...)
- Grafana plugins: irrelevant
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @SensSebastianSchlosser 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

guessing this is the culprit:
> You may need to play with the size of the resolution (2582px*800px in my case)

**Comment by SensSebastianSchlosser** [comment]
Hi! Thank you for responding!

Unfortunately I don't know how to work with your sandbox (e.g. how to save a dashoard and share it with you!) Can you help me with this? @zuchka 

It also appears in other resolutions. e.g.:
``"gridPos": {
    "x": 0,
    "y": 0,
    "w": 9,
    "h": 3
  },
``
On a browser resolution on 1300px width.

**Comment by usmangt** [comment]
Hi @SensSebastianSchlosser 

Can you please share a snapshot of the whole panel where this Auto-Fontsize doesn't work properly (The text is cut off) i.e. the image you attached written with Ausreichend Batterie

I am trying to reproduce it but don't get it clearly as where it is visible and how it was defined.

**Comment by SensSebastianSchlosser** [comment]
Hi! Thank you for your answer! @usmangt 

After further investigation from my side I found out, that this occours only on mobile or extra large resolution.
Here I created a snapshot for you:

https://snapshots.raintank.io/dashboard/snapshot/pzrcJ3iNDIK719anqn1TKpDFGo7H6sS7?orgId=2

<img width="392" alt="image" src="https://user-images.githubusercontent.com/117441229/209312567-16de4fba-f8e8-48ef-9f59-113c3251df14.png">
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/117441229/209312702-9de4874f-e6a0-428a-880b-dd49c445839e.png">

I took screenshots with the resolution so maybe now you are able to replicate my issues.
I hope this helps for further investigations.

BR

**Comment by usmangt** [comment]
Since I was not able to reproduce it. Therefore I will forward this issue to our Engineers as they might be able to tell in more detail.

**Comment by joshhunt** [comment]
Able to replicate this at a slightly different size, but it does happen 

![image](https://user-images.githubusercontent.com/46142/213445169-f87c5f3c-5bb4-4c67-8f09-8afdbf058e2c.png)

**Comment by SensSebastianSchlosser** [comment]
This sounds good, that you were able to replicate that.
This happens also in resolutions greater than width: 1920px (QHD or WQHD monitors/resolutions).
You have to play with height and width of the panel and resolution.
