### ISSUE TITLE
Unable to configure and use proxy datasource when Grafana proxy authorization is enabled

### ISSUE THREAD

**Issue by pzhuk** [grafana/grafana#5976]
I'm submitting a  Bug report regarding the issue with configuration and use of proxy dataource and Grafana proxy authorization enabled.

So my current installations includes nginx (reverse proxy mode and proxy authorization gateway) and Grafana as a backend.

grafana version: 3.1.1-1470047149
datasource: graphite 0.9.12
OS: ubuntu 14.04

What I am trying to do: configure nginx as an authorization gateway via basic HTTP authorization by passsing X-WEBAUTH-USER header to downstream

Expected result: users who passed basic authorization - are auto-logged in to grafana
Actual result: users are auto-logged in, but unable to create a data-source, because grafana returns HTTP/415

Log record (attempt to add data source):

t=2016-09-07T03:42:01+0000 lvl=info msg="Request Completed" logger=context userId=8 orgId=3 uname=foobar method=PUT path=/api/datasources/9 status=415 remote_addr=a.b.c.d time_ns=0 size=70

I've also tried to create datasource when user is logged in manually (not auto-logged), and it works properly - user can add dataource and see graphs normally. However, any auto-logged users, can't see graphs even after that - instead getting error graphs with error (Can't read properly 'length' of undefined)
 

nginx config:
```
   location /grafana {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf/htpasswd;
        proxy_set_header   X-WEBAUTH-USER $remote_user;
        proxy_pass_request_headers off;
        proxy_pass http://my.grafana.url:3000;
        proxy_set_header   Host "my.grafana.url";
        rewrite  ^/grafana$  / break;
        rewrite  ^/grafana(.*)$  $1 break;
    }
```

grafana config:

```
[server]
root_url = %(protocol)s://%(domain)s:/grafana
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```

**Comment by torkelo** [comment]
status code 415 is unsupported media type, are you creating the data source from the HTTP API or UI? 

When you create a datasource you use POST grafana/api/datasources

**Comment by pzhuk** [comment]
I am doing that from UI

**Comment by torkelo** [comment]
The request you show in the log tries to update a datasource. 

Looks like your proxy removing headers, which is causing media type issues in the grafana http backend.  Update your nginx config

**Comment by TheTincho** [comment]
I am seeing the same issue with a similar configuration.

Could you explain which headers are missing? The log does not give any useful information, and the same authentication works for the rest of the endpoints.

**Comment by pzhuk** [comment]
@TheTincho , in my case, I was able to resolve issue by changing nginx config.

Added this:

`        proxy_set_header Authorization "";`

and removed this:

`        proxy_pass_request_headers off;`

**Comment by TheTincho** [comment]
I have already equivalent directives in Apache. But this looks like a bug, only the user "admin" is able to see the datasources, even if my user (tincho) is marked as admin:

```
$ curl -H "X-Proxy-REMOTE-USER: admin" http://localhost:3000/api/user  
{"email":"admin@localhost","name":"","login":"admin","theme":"","orgId":1,"isGrafanaAdmin":true}

$ curl -H "X-Proxy-REMOTE-USER: admin" http://localhost:3000/api/datasources
[]

$ curl -H "X-Proxy-REMOTE-USER: tincho" http://localhost:3000/api/datasources
{"message":"Permission denied"}
```
