### ISSUE TITLE
Show database views in SQL query builder for MS SQL

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#59775]
### Discussed in https://github.com/grafana/grafana/discussions/57598

<div type='discussions-op-text'>

<sup>Originally posted by **stepanurban** October 25, 2022</sup>
Would it be possible to list in MS SQL Query Builder (in Tables drop-down menu) also database views? We have a lot of views in our database with human readable names and we see only encoded table names which are not understandable for us.

By view I mean
```
CREATE VIEW machine AS
SELECT
[M3255322] AS [timestamp],
[SM432334] AS [pressure_01],
[M3f332284] AS [temperature_01]
FROM raw_data_table
```
and this view is not listed in this Table drop-down menu in MS SQL Query Builder
</div>

**Comment by lse-odoo** [comment]
The same happen with PostgreSQL views data sources (and probably SQL in general I guess)
