### ISSUE TITLE
Unable to render Node Graph using Loki as data source

### ISSUE THREAD

**Issue by akselleirv** [grafana/grafana#59777]
**What happened**:

I'm trying to use the Node Graph to visualize Loki logs, but it displays "No Data". 

**What you expected to happen**:

To be able to render the graph using logs.

**How to reproduce it (as minimally and precisely as possible)**:

I tried to use this Loki query:
```
sum by(id, source, target) (rate({namespace="my-ns", container="collector"} | json | __error__=`` | label_format id=pod_extracted | label_format target=destination [$__interval]))
```

I toogled the table view, and then I can see that the data is there:
![image](https://user-images.githubusercontent.com/52233080/205597256-b2dca417-0e52-433c-8491-ad2b39ee77fa.png)

How can I further debug this issue?

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
the node graph requires a very particular data shape/scheme for the panel to work:

https://github.com/grafana/grafana/issues/59730

**Comment by harisudarsan1** [comment]
> the node graph requires a very particular data shape/scheme for the panel to work:
> 
> https://grafana.com/docs/grafana/v9.3/panels-visualizations/visualizations/node-graph/#data-api
@zuchka 
I is not working even If I use correct data structure for node graph is there any examples for that?
