### ISSUE TITLE
Cannot read properties of undefined (reading 'color')  on Bar Chart

### ISSUE THREAD

**Issue by MonsieurZed** [grafana/grafana#59776]
Hola Folks,

Here a small i encounter since the last release

**What happened**:
One of my bar chart is "broken" since the last release. If the bar chart have a value mapping set to something that doesn't exist, it will crash
![image](https://user-images.githubusercontent.com/18287008/205594120-71993c28-db7f-4844-a47f-d241d2ce5c5d.png)
`TypeError: Cannot read properties of undefined (reading 'color')
    at 2352.d7c14cbd3dbda648a17f.js:7413:18202
    at Array.some (<anonymous>)
    at 2352.d7c14cbd3dbda648a17f.js:7413:18170
    at Array.some (<anonymous>)
    at G.c.useFieldConfig.standardOptions.settings.byValueSupport (2352.d7c14cbd3dbda648a17f.js:7413:17941)
    at ra (2754.c9252327f51106ea3a6d.js:2:801944)
    at Ws (2754.c9252327f51106ea3a6d.js:2:854025)
    at Ou (2754.c9252327f51106ea3a6d.js:2:841298)
    at ku (2754.c9252327f51106ea3a6d.js:2:841226)
    at Eu (2754.c9252327f51106ea3a6d.js:2:841089)`

**What you expected to happen**:
Not be broken and render it anyways

**How to reproduce it (as minimally and precisely as possible)**:
- Create a bar chart panel
- Make a basic query
- Add a Value Mapping to a value with text that doesn't exist  in query 
- The bar chart doesn't render anymore

**Anything else we need to know?**:
- If i remove the unuse mapping it work fine
- I've tried on other panel type, it work fine with unuse mapping value

**Environment**:
- Grafana version: [v9.3.1 (89b365f8b1)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: SQL Query
- OS Grafana is installed on: Unix/Kubernetes
- User OS & Browser: Chrome/Mozilla/Opera
- Grafana plugins: N/A
- Others:

**Comment by leeoniya** [comment]
this is same as https://github.com/grafana/grafana/issues/60002, will be fixed by https://github.com/grafana/grafana/pull/60066
