### ISSUE TITLE
Bug: Bad Escape Character for InfluxDB

### ISSUE THREAD

**Issue by gitmopp** [grafana/grafana#5979]
I'm submitting a bug report
grafana-3.1.1-1470047149.x86_64
datasource: influxdb-0.13.0-1.x86_64
OS: CentOS 6.8

Grafana escapes the InfluxDB query in a wrong way.
In my InfluxDB I' ve a service called "Gi1/0/1 Bandwidth".

This is my query in Grafana:
`SELECT mean("value") AS "$service.$performanceLabel" FROM "metrics" WHERE "host" =~ /$host$/ AND "service" =~ /^$service$/ AND "performanceLabel" =~ /^in$/ AND $timeFilter GROUP BY time($interval), "host" fill(null)`

This is the raw query
`SELECT mean("value") AS "Gi1\/0\/1 Bandwidth.$performanceLabel" FROM "metrics" WHERE "host" =~ /(MY-SWITCH-SW01\.some\.domain\.com)$/ AND "service" =~ /^Gi1\/0\/1 Bandwidth$/ AND "performanceLabel" =~ /^in$/ AND time > now() - 6h GROUP BY time(15s), "host" fill(null)`

InfluxDB error:
`ERR: error parsing query: found \/, expected identifier at line 1, char 30`

The query will work this way:
`SELECT mean("value") AS "Gi1/0/1 Bandwidth.$performanceLabel" FROM "metrics" WHERE "host" =~ /(MY-SWITCH-SW01\.some\.domain\.com)$/ AND "service" =~ /^Gi1\/0\/1 Bandwidth$/ AND "performanceLabel" =~ /^in$/ AND time > now() - 6h GROUP BY time(15s), "host" fill(null)`

It is necessary to disable escaping for the string.

**Comment by torkelo** [comment]
use the query editor, it will regex escape only where regex operator is used 
for raw query mode, all template variables are regex escaped.
