### ISSUE TITLE
Hackathon: storyboard video presentation

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#59799]

**Comment by staton-hyse11** [comment]
In trying to take a more marketing-focused approach to some pages of the design system site, it's become obvious that we need to have solutions for these types of products. The design system site bridges the gap between Grafana.com and the products but our typography, color, and other solutions are solely focused on the product. This has left major gaps in what we need for this product and has resulted in some "creative liberties" to make solutions yet stay "on brand"
