### ISSUE TITLE
repeat templating metric in a panel

### ISSUE THREAD

**Issue by juliennju** [grafana/grafana#5980]
* **I'm submitting a ...**
- [ ] Feature request

Please include this information:
- What Grafana version are you using?
3.1
- What datasource are you using?
opentsdb

I define a custom templating variable called cluster which is multi-value, and my metric is $cluster.system.cpu.idle.  
Now I use repeat panel to show my metrics, but I want to show metrics from different clusters in a panel.

**Comment by torkelo** [comment]
you will need to be more specific, you want to repeat it based on cluster but show many in same graph, you are contradicting yourself :)
