### ISSUE TITLE
Broken link, typo in administration topics

### ISSUE THREAD

**Issue by karengermond** [grafana/grafana#59811]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by karengermond** [comment]
Here are the details:

Was looking at RBAC docs for a customer issue and noticed a couple of minor issues.

On https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-grafana-provisioning/ the example role provisioning file link, leads to a 404

Additionally, on https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/ in the "Admin" Role section, one of the fixed roles is listed as fixes:folders:writer it should be fixed:folders:writer

**Comment by chri2547** [comment]
These issues have been addressed.
