### ISSUE TITLE
Executing migration failed - recipient must be specified when using the Slack chat API

### ISSUE THREAD

**Issue by GuyCarmy** [grafana/grafana#59823]
**What happened**:
Upgrading grafana (as part of kube-prometheus-stack helm chart) from 8.3.5 to 9.3.0 failed with the error:
`logger=migrator t=2022-12-05T11:19:00.811565472Z level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="failed to validate AlertmanagerConfig in orgId 1: failed to validate receiver \"data team alerts\" of type \"slack\": recipient must be specified when using the Slack chat API"
logger=migrator t=2022-12-05T11:19:00.81162255Z level=error msg="Exec failed" error="failed to validate AlertmanagerConfig in orgId 1: failed to validate receiver \"data team alerts\" of type \"slack\": recipient must be specified when using the Slack chat API" sql="code migration"
Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): failed to validate AlertmanagerConfig in orgId 1: failed to validate receiver "data team alerts" of type "slack": recipient must be specified when using the Slack chat API
migration failed (id = move dashboard alerts to unified alerting): failed to validate AlertmanagerConfig in orgId 1: failed to validate receiver "data team alerts" of type "slack": recipient must be specified when using the Slack chat API`

checking in another instance of grafana that was not upgraded yet, i can see that the recipient is actually missing and everything is working. i assume the issue is only on the migration (which is part of the upgrade?)
<img width="666" alt="image" src="https://user-images.githubusercontent.com/29687257/205627855-5f30008b-ddcd-4fed-a01c-3acb452a0cd7.png">
in addition, as shown in the screenshot, in 8.3.5 this field is "optional" so it probably became required later.

**What you expected to happen**:
I was expecting the upgrade to work, if the notification channel configuration changed, it makes since that specifically the relevant alerts won't work, but grafana should still come up.

**How to reproduce it (as minimally and precisely as possible)**:
install grafana on version 8.3.5, create a notification channel of slack type without a recipient, upgrade it to 9.3.0

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.5 to 9.3.0
- Data source type & version: 
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:
grafana is installed as part of the kube-prometheus-stack helm chart. upgrading from 32.2.1 to 42.2.0. which in turn upgrade the grafana helm chart to 6.45.0 which uses grafana 9.3.0

**Comment by zuchka** [comment]
Thanks for creating this issue, @GuyCarmy 

based on your screenshot you are still using the legacy alerting platform, which is deprecated.

For support or bug-reports, you will need to migrate to the new alerting platform

blog post: https://grafana.com/blog/2022/06/14/grafana-alerting-explore-our-latest-updates-in-grafana-9/
new docs: https://grafana.com/docs/grafana/latest/alerting/
how to migrate: https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/
