### ISSUE TITLE
Grafana Datasource Annotation support 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5982]
User story:

As a Grafana user I want to fetch annotations stored in Grafana's built in annotation storage. 

[ ] - Fetch Built In Grafana Stored Annotations

**Comment by mattttt** [comment]
I want this so badly, built-in annotation. :)

**Comment by torkelo** [comment]
first step, which this feature will cover, is to be able to but fetching annotations from the build in annotation database (where currently only alert state changes are written to)
