### ISSUE TITLE
Timeseries: Add support for template variables in axis label

### ISSUE THREAD

**Issue by Corbyn** [grafana/grafana#5983]
**I'm submitting a ...**
- [ ] Bug report
- [x] Feature request 

Please include this information:
- What Grafana version are you using?
  -- 3.1.1
- What datasource are you using?
  -- InfluxDB
- What OS are you running grafana on?
  -- SLES 11
- What did you do?
  -- Entered "$myvariable" in axis label
- What was the expected result?
  -- The graph should display the content of the variable (e. g. "Percent")
- What happened instead?
  -- The graph displayed "$myvariable"

![2016-09-07 15_28_45-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8446952/18313708/40fb8da0-7510-11e6-80a1-936738c56761.jpg)
![2016-09-07 15_29_32-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8446952/18313707/40f8a522-7510-11e6-91ec-4289a0e2979c.jpg)

**Comment by Ultraseamus** [comment]
+1

**Comment by bolausson** [comment]
+1

**Comment by 4knahs** [comment]
+1

**Comment by pkaramol** [comment]
+1

**Comment by johannesloher** [comment]
+1

**Comment by blancmatter** [comment]
+1

**Comment by silvercheese** [comment]
+1

**Comment by siegmund42** [comment]
+1

**Comment by siegmund42** [comment]
Supporting variables in the limits (Min/Max) of axes would be nice as well!

**Comment by jerboa-io** [comment]
@siegmund42 +1

**Comment by CptOrange16** [comment]
Any news on this feature? It would be really useful for my panels

**Comment by jkrauska** [comment]
+1 -- would be very helpful for some of my dashboards

**Comment by jaredleitner** [comment]
+1

**Comment by allomorphy** [comment]
Did this feature not make it? A bit sad as it is super useful for configurability. Variables are supported in the Panel name.

**Comment by Hivanoe** [comment]
I confirm it would be nice
I would show on X axix label (time series) the v.windowPeriod

**Comment by z3rone** [comment]
+1

**Comment by jaxels20** [comment]
+1

**Comment by michGB** [comment]
+1

**Comment by cccs-jory** [comment]
+1
