### ISSUE TITLE
Always keep thresholds visible in graphs ('minimum' maximum)

### ISSUE THREAD

**Issue by dannygoulder** [grafana/grafana#5984]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  Elasticsearch 2.x
- What OS are you running grafana on?
  RHEL 6.x
- What did you do?
  Added thresholds to a graph which could go far above the upper threshold
- What was the expected result?
  Threshold lines always visible
- What happened instead?
  Threshold lines not visible until datapoints exceed them.

I would like to have the option to keep thresholds visible on the graph at all times _without_ needing to set a fixed maximum in the panel settings.

The graph plots the age of replicated data on the y-axis, and our thresholds are 20 minutes and 30 minutes. We would like the upper threshold to be visible all the time to highlight how close (or ideally how far) the age of data is from the threshold, but also to allow the graph to scale beyond the threshold when required.

Effectively this would mean setting a 'minimum' on the maximum, or padding the upper value in the graph to ensure that the threshold is always visible.

Currently I am doing this by using graphite to plot a single value, but this makes the tooltip show the date on the far left of the x axis regardless of where you hover on the graph.

**Comment by bergquist** [comment]
I think this could be solved easier once flexible y-min/y-max have been added. ref https://github.com/grafana/grafana/pull/5720

**Comment by tyvich** [comment]
To expand visually on the value of this feature. Here is a graph of one of our instance’s CPU % value with the y-axis autoscaling based on the data points:

 ![cpu_2_percent](https://user-images.githubusercontent.com/31109639/54883935-9400fc00-4e30-11e9-8042-198f413b184d.png)

Graph panels allow us to easily compare metrics in relation to values before and after (typically across time), making visual anomaly detection quite easy for us. At first glance, the spike around 11:00 could warrant further investigation (and attracts the users attention) as it is 2 X the values around it.
However, when setting the y-max to 20%, that blip becomes nearly invisible:

![cpu_20_percent](https://user-images.githubusercontent.com/31109639/54883942-9fecbe00-4e30-11e9-9440-57f5fafda596.png)
![cpu_20_percent_cloudwatch](https://user-images.githubusercontent.com/31109639/54883903-4be1d980-4e30-11e9-99a6-7bca01d030cb.png)

This feature would allow us to add an additional dimension outside of the datapoints (20% in this case) without limiting y axis max (I still want to display up to 100% obviously) 

It would expand Grafana’s discovery capability, and allows dashboard users to cut down on lots of “metric clutter” to discover and hone in on just what’s relevant.

I’ve also included a picture of this feature as it works currently in CloudWatch dashboards. Implementation wise, I think a toggle on thresholds to allow them to set the visual initial max would work well.

**Comment by tyvich** [comment]
Would be similar in functionality to #979

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)
