### ISSUE TITLE
Alerting: Alertmanager configuration truncation in MySQL 8

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#59845]
**What happened**:

Many of the Alertmanager resources are stored in a single JSON blob in the database, as a single string field.

When running against MySQL 8.0.28, the JSON blob will be truncated once it reaches a certain size (roughly 60-100KB). This completely breaks the alerting config.

This bug does not reproduce against MySQL 5.7.40 with the same configuration, in the same environment.

The specific size is not clear. We've seen it truncate at different points on different deployments at the same MySQL version. One case truncated at 65KB, another truncated at 108KB.

The field in question is of type `MEDIUMTEXT`, which according to MySQL docs [should not truncate until 16MB](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings). In practice it truncates far earlier, only on MySQL 8.

**What you expected to happen**:

I expected the alerting configuration to not be truncated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up Grafana against MySQL 8.0.28. I used AWS RDS to do this quickly.
2. Create a lot of alerting objects. In my case, tried to create 1000 contact points.
3. The alertmanager config becomes broken after the first 300 or so, with an error like `unexpected end of JSON value`

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: MySQL 8.0.28

**Comment by alexweav** [comment]
We've validated that the source of this sits somewhere below the Grafana codebase. Grafana thinks it's persisting a well-formed config.

It's getting truncated at a lower level - ORM, transport, or in the database itself.

**Comment by alexweav** [comment]
This appears to be a bug in MySQL.

Specifically, the truncation happens at this line, inside the database: https://github.com/grafana/grafana/blob/78ef55eb0635b88c9eb1388eb2a9078d2ea95245/pkg/services/ngalert/store/alertmanager.go#L145

The copy from the in-memory temporary table `T` seems to be where the truncation happens.
Other operations do not reproduce this issue, and neither does a copy from an on-disk table. However, `INSERT INTO SELECT` behaves unpredictably when the target table is a temporary one in memory.

**Comment by hairyhenderson** [comment]
@alexweav 8.0.31 is current - I wonder if this bug was fixed between 8.0.28 and that?

**Comment by alexweav** [comment]
@hairyhenderson I dug through the patch notes and didn't see anything relevant, unfortunately.

This will be fixed by: https://github.com/grafana/grafana/issues/59845

**Comment by alexweav** [comment]
Lol, wrong link above, https://github.com/grafana/grafana/issues/60053
