### ISSUE TITLE
v7: The serial link is displayed as a parallel link

### ISSUE THREAD

**Issue by chenkaiyin1201** [grafana/grafana#59863]
grafana version: 7.5.9

When the jaeger link is displayed in Explore mode, a serial link is displayed as a parallel link, and the time point difference between the two spans is about 20ms.

**Comment by zuchka** [comment]
Thanks for creating this issue, @zuchka 

> grafana version: 7.5.9

v7 is eol and we only make security patches for it now. Please use the newest grafana version (v9) or newest-1 (v8).
