### ISSUE TITLE
Alerting: Provisioning: Bug: issue with provisioning directory picking up exported rules

### ISSUE THREAD

**Issue by GBBx** [grafana/grafana#59868]
**What happened**:
The alerting provisioning as described in the [documentation](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/) does not work with JSON files.

**What you expected to happen**:
JSON data exported from the API and placed into a file gets populated in the UI.

**How to reproduce it (as minimally and precisely as possible)**:
1. Get alert JSON via API `/api/v1/provisioning/alert-rules/{UID}`.
2. Place it into the provisioning directory: `/etc/grafana/provisioning/alerting/`.
3. Configure Grafana:
```
[paths]
...
provisioning = /etc/grafana/provisioning
...
[unified_alerting]
enabled = true
...
```
4. Restart Grafana
5. The rule is not marked as "provisioned" in the UI.
6. If I rename the rule in the JSON file, the alert with the new name does not appear in the UI.

**Anything else we need to know?**:
I added these rules when I was using Grafana 7.x, later I updated to 8 and now to 9.3.
I have these rules (legacy-style) in the Alert tab of some panels. These panels are on dashboards that are provisioned from files.

I would be happy to keep using the same approach, but provisioning alerts from the dashboard files does not work anymore (i.e. they can be changed in the UI and after I restart Grafana, those changes are not reset).

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
> I added these rules when I was using Grafana 7.x, later I updated to 8 and now to 9.3.
I have these rules (legacy-style) in the Alert tab of some panels. These panels are on dashboards that are provisioned from files.

sorry @GBBx but legacy alerting is deprecated and I do not believe that the recent work on alert provisioning is backwards compatible. I would highly recommend migrating completely to the new alerting platform 👍 

PS [our forum](https://community.grafana.com) is a good resource for legacy alerting-related troubleshooting

**Comment by GBBx** [comment]
@zuchka , thank you for your comments.

I'm afraid I was not clear.
The alerts were first created using legacy alerting, then I did switch to the new alerting mode.
The alerts are there in the unified alerting view. But I can only export them using the API, the exported file is not usable for provisioning. Also, the [documentation](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/) is not clear about what kind of JSON file could be provisioned and how it should look like.

Do I need to translate all my JSON files to YAML for it to be picked up by Grafana?

**Comment by m-rcl** [comment]
I'm encountering the same behavior. Having a look at the code this might be a bug.

Validation of file is done for yaml and json:
https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/alerting/config_reader.go#L37

Whereas the parsing of the file content is only performed for yaml:
https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/alerting/config_reader.go#L74

**Comment by m-rcl** [comment]
I have tested a fix for parsing json files as well but there seems to be another problem.
The format provided by `/api/v1/provisioning/alert-rules` differs from the one used to read the data.

API generates: [ProvisionedAlertRule](https://github.com/grafana/grafana/blob/57d6adbc7c4008143ac18fc7076607be227e12d3/pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go#L66)
parseConfig expects: [AlertingFileV1](https://github.com/grafana/grafana/blob/41b3398eb4b4436bf1d63ab30747cad193457864/pkg/services/provisioning/alerting/types.go#L30)

**Comment by JohnnyQQQQ** [comment]
Hey, can you please provide an example to reproduce this?

**Comment by JohnnyQQQQ** [comment]
Getting the rule by the rule ID will not create a valid rule group object, as mentioned in our [documentation](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules). So just adding the result from the response from the request into a file will not work.

**Comment by m-rcl** [comment]
Hi @JohnnyQQQQ, I will test the procedure described in the documentation on Monday. 
In the meanwhile, can you confirm json files will work at all? From what I saw in the corresponding code section only yaml will be processed ([see my first Comment](https://github.com/grafana/grafana/issues/59868#issuecomment-1346082115))

**Comment by JohnnyQQQQ** [comment]
JSON and YAML are interchangeable. Thus you can use the YAML parser to parse JSON; your conclusion is incorrect. We also have a [test](https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/alerting/config_reader_test.go#L76) for this.

**Comment by m-rcl** [comment]
@JohnnyQQQQ thanks for the information. Unfortunately I'm struggling to perform the suggested way of provisioning alerts from files in the new unified alerting.

The section of the documentation you're referring to tells to
> Use the [Alerting provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting/#get-alerts) to extract the alert rule.

The `GET /api/alerts/` endpoint seems to be

> relevant for the [legacy dashboard alerts](https://grafana.com/docs/grafana/v8.5/alerting/old-alerting/) only

For my setup
- Grafana 9.3.1
- unified alerting enabled
- pre-existing and newly created alert rules

this endpoint returns an empty array.

Could you point me to the correct endpoint, which will return all alerts in the correct format to be processed by the file provisioner? Thanks in advance!

**Comment by JohnnyQQQQ** [comment]
As mentioned, you can use `/api/v1/provisioning/alert-rules/{UID}` to fetch the rule definition, which you have to put in a rule group inside your provisioning file.

**Comment by m-rcl** [comment]
Thanks. So there is no endpoint which will give me all alerts within a rule group which I can simply copy/paste into a new provisioning file.

Compared to the previous workflow (exporting the whole dashboard json via UI and provisioning the exported file) the workflow for the unified alerting contains a lot more manual/to be automated tasks as they are now decoupled from the dashboard.
