### ISSUE TITLE
Corrected NaN behaviour on histogram_quantile causes "last non-null value" to not work as expected

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana#59862]
In Grafana < 9.3 we see the following behaviour:

histogram_quantile on a metric which buckets do not containing any data, returns null values

<img width="846" alt="image" src="https://user-images.githubusercontent.com/5786097/205854482-9110f495-1163-4b8f-9026-4d379beac1cf.png">

This is actually wrong as per Prometheus standard

If `b` has 0 observations, `NaN` is returned. For `φ < 0`, `-Inf` is returned. For `φ > 1`, `+Inf` is returned. For `φ = NaN`, `NaN` is returned.

Which seems to be fixed or at least changed in 9.3**?**  As we see the following behaviour in **Grafana 9.3**

![image](https://user-images.githubusercontent.com/5786097/205855784-00800f9b-d9ce-4153-9019-32b7a97793a9.png)

Which is by all means "good" yet it breaks the functionally of  "last *" - filtering out the last non-null value.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/5786097/205856018-a2e779fd-d25d-439e-b402-c1961965b585.png">

---

My suggestion or expectation is that "last *" _also_ ignores NaN and show the last non-null/nan value. At the moment (Grafana 9.3) it shows NaN in the Stat panel:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/5786097/205859737-c5badc96-224a-419b-a713-31641893eac1.png">

while < 9.3 would actually show the last non null/nan value

**Comment by wiardvanrij** [comment]
Potentially related / relevant: https://github.com/grafana/grafana/issues/59349

**Comment by ryantxu** [comment]
> My suggestion or expectation is that "last *" also ignores NaN

I think this is reasonable.  The intention of "last *" is to show the last value.  If you care about NaN vs null vs undefined... can use the last command 🤷🏻 (maybe with an additional transformer)
