### ISSUE TITLE
401 Url is too long

### ISSUE THREAD

**Issue by Michsh** [grafana/grafana#5987]
I use Grafana with proxy Apache, ssl  server and I have 30 query to same database InfluxDB. At 6 hours works normal but on mount i get the issue from image. If i delete 2 rows  works normal.
I read on internet that is better to use POST than GET.
Any idea will be great !

![url is to long](https://cloud.githubusercontent.com/assets/8654261/18340428/89e4aba8-75ad-11e6-9dae-ba89ec6349a5.png)

**Comment by torkelo** [comment]
does InfluxDB support POST for queries?

**Comment by Michsh** [comment]
No. Than other idea is to increase my Apache Get limit ? Or other idea ?

**Comment by torkelo** [comment]
not sure :(

**Comment by Michsh** [comment]
Y cannot ad as feature to do multiple GET if URL is to long ?

**Comment by torkelo** [comment]
no, better to request InfluxDB to improve support this case

**Comment by vgt** [comment]
As mentioned in the ticket I referenced, Influx does in fact support the query parameter to be transferred as part of MultipartForm. This way it should be possible to submit larger queries to Influx.

**Comment by blmpl** [comment]
@torkelo - I checked and POST is working fine now on influx side (with huge set of queries)
Would it be possible to add option which change method from GET to POST?
