### ISSUE TITLE
Crash on startup: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by milyenpabo** [grafana/grafana#59889]
**What happened**: I launched Grafana in Docker, and it crashed with a SIGSEGV. I'm sure there's a problem with how I start Grafana:

`docker run -d --name=grafana -v ~/grafana/etc/grafana:/etc/grafana -v ~/grafana/varlib:/var/lib/grafana -v ~/grafana/usrshare/grafana:/usr/share/grafana  --net=host grafana/grafana:9.1.0`

Where `~/grafana` contains directories/files copied from another running Grafana container. (This was meant to be a quick and dirty way to duplicate a Grafana instance.)

This is the result:

![grafana-crash](https://user-images.githubusercontent.com/8589452/205939542-7a5ade48-89ff-447f-9699-bdac7b5195bd.png)

**What you expected to happen**: Launch Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: This issue is not blocking me, I just report it so that you know about the problem.

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: -
- OS Grafana is installed on: Ubuntu 20.04.5
- User OS & Browser: -
- Grafana plugins: -
- Others: Docker version 20.10.17, build 100c701

**Comment by zuchka** [comment]
> This issue is not blocking me, I just report it so that you know about the problem

Thanks for creating this issue, @milyenpabo 

and thank you for letting us know 👍
