### ISSUE TITLE
Annotations Do not change color in grafana 3.o

### ISSUE THREAD

**Issue by kunchamharsha** [grafana/grafana#5989]
the color of annotation lines in grafana 3.0 are not changing. I thought i had a problem with my installation then i tried it on play.grafana.org. it not changing the color either. only the icon color changes. I am using a custom simple json datasource.I am running it on ubuntu 16.04 if it helps

**Comment by torkelo** [comment]
both the icon and lines change for me 
http://play.grafana.org/dashboard/db/annotations

**Comment by kunchamharsha** [comment]
hey its not changing when you hit the update button the line colors havent changed ! change the puppet apply from blue to green color.the lines do not change color.I have attached a series of screenshots.please see !!
![screenshot 79](https://cloud.githubusercontent.com/assets/16702583/18394429/9bc611d8-76d7-11e6-87de-ca7bb4b920df.png)
![screenshot 80](https://cloud.githubusercontent.com/assets/16702583/18394430/9bc662be-76d7-11e6-969b-747114518717.png)
![screenshot 81](https://cloud.githubusercontent.com/assets/16702583/18394431/9bc83b7a-76d7-11e6-9d26-de1b3fdfedcd.png)
![screenshot 82](https://cloud.githubusercontent.com/assets/16702583/18394432/9bcc67a4-76d7-11e6-871b-4416cc0c6a96.png)
