### ISSUE TITLE
Password not changed after "changed successfully" message

### ISSUE THREAD

**Issue by meangrape** [grafana/grafana#59915]
**What happened**:
I tried to change the admin user's password with `grafana-cli --config /etc/grafana/grafana.ini --homepath /usr/share/grafana admin reset-admin-password`.

The command appeared to complete successfully.
```
root@admin:/var/lib/grafana# grafana-cli --config /etc/grafana/grafana.ini --homepath /usr/share/grafana admin reset-admin-password 'admin'
INFO [12-06|20:23:49] Starting Grafana                         logger=settings version= commit= branch= compiled=1970-01-01T00:00:00Z
INFO [12-06|20:23:49] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO [12-06|20:23:49] Config loaded from                       logger=settings file=/etc/grafana/grafana.ini
INFO [12-06|20:23:49] Config overridden from command line      logger=settings arg="default.paths.data=/var/lib/grafana"
INFO [12-06|20:23:49] Config overridden from command line      logger=settings arg="default.paths.logs=/var/log/grafana"
INFO [12-06|20:23:49] Config overridden from command line      logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
INFO [12-06|20:23:49] Config overridden from command line      logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
INFO [12-06|20:23:49] Path Home                                logger=settings path=/usr/share/grafana
INFO [12-06|20:23:49] Path Data                                logger=settings path=/var/lib/grafana
INFO [12-06|20:23:49] Path Logs                                logger=settings path=/var/log/grafana
INFO [12-06|20:23:49] Path Plugins                             logger=settings path=/var/lib/grafana/plugins
INFO [12-06|20:23:49] Path Provisioning                        logger=settings path=/etc/grafana/provisioning
INFO [12-06|20:23:49] App mode production                      logger=settings
INFO [12-06|20:23:49] Envelope encryption state                logger=secrets enabled=true current provider=secretKey.v1

Admin password changed successfully ✔
```

**What you expected to happen**:
The password to change.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The current password is `bobbobbob`. After supposedly having a successful password change the SHA of the database is unchanged. There is no other `grafana.db` on this server. It is possible to change the password from the GUI.
```
root@admin:/var/lib/grafana# shasum grafana.db
038915e1b0aad18cda05b14f05a6b954c2aecf97  grafana.db

root@admin:/var/lib/grafana# grafana-cli --config /etc/grafana/grafana.ini --homepath /usr/share/grafana admin reset-admin-password 'admin'
...
Admin password changed successfully ✔

root@admin:/var/lib/grafana# shasum grafana.db
038915e1b0aad18cda05b14f05a6b954c2aecf97  grafana.db
```

**Environment**:
- Grafana version: Version 9.3.1 (commit: 89b365f8b1, branch: HEAD)
- Data source type & version: NA
- OS Grafana is installed on: Ubuntu 20.04.5 LTS
- User OS & Browser: NA
- Grafana plugins: NA
- Others:

**Comment by klein5656** [comment]
Same issue as above. But the UI also is not letting me reset the password after saying successful.

**Comment by stefanplk3** [comment]
Same problem here. Very dangerous btw since the output
Admin password changed successfully ✔
suggests, the password has been set while it in fact remains the default user/password combination admin/admin.

**Comment by gianluca-nitti** [comment]
Same problem here (using Grafana 9.3.1 on CentOS).

Very bad if you use some sort of script or automation tool (such as Ansible) to provision Grafana on your server with a configured admin password: the script will succeed silently and the expected pussword won't work but `admin` will.

**Comment by gianluca-nitti** [comment]
This also seems to happen on 9.3.0, while the password gets correctly changed on 9.2.7 (haven't tried 9.2.8 since it's currently marked as unreleased).

**Comment by mildwonkey** [comment]
Thanks everyone for reporting this issue, and I'm (personally) sorry for the misbehaving CLI - this was my error 😞. The fix will be in included in the next 9.3 release.

Until then, you can use the grafana 9.2 cli to reset the admin password. `reset-admin-password` works correctly in all of the 9.2 releases. For the record, it's also working if on main (which will be 9.4, eventually), where we're using a single dependency graph. 

And one last note for future-me: the incorrect wire binding still exists in main; however that is not the wire graph actually in use, somehow. We may be able to re-work - or remove!! - the cli-specific dependency graph. I'm not yet familiar enough with the recent binary changes to know precisely what's going on there, but I have a vague idea. Since reset-admin-password is working on main, I'm calling that a question for next year ;)

**Comment by tolzhabayev** [comment]
@mildwonkey can this issue be closed or do we wait until this is merged https://github.com/grafana/grafana/pull/61143?

**Comment by mildwonkey** [comment]
@tolzhabayev I'd say we can either wait until the 9.3.3 release to close it, or do it now since it's in the release branch. (I don't know if we have a standard procedure for closing issues before the fix is released)

**Comment by toralf** [comment]
same problem here with 9.5.1 the password was reset, but not to the given one at the command line, instead to "admin"
