### ISSUE TITLE
API: add datasource to a specific organization

### ISSUE THREAD

**Issue by loic911** [grafana/grafana#5991]
Hello,

I'm using the Grafana 3.1.1 API. 
I try to create an organization and a datasource inside this organization but the datasource has always orgId=1.

I first try with:

**1. POST http://localhost:3000/api/orgs with data**
 _Request data: {"name":"test16"}_
_Response id:19_

**2. POST http://localhost:3000/api/datasources**
_Request data: {"database":"databaseName","password":"password","access":"proxy","name":"test16","host":"http://localhost:8086","type":"influxdb","username":"user",**"orgId":19**}_
_Response id: 14_

**3. GET http://localhost:3000/api/datasources/14**
_Request data: {id=14, **orgId=1**, name=test16, type=influxdb, typeLogoUrl=, access=proxy, url=, password=password, user=, database=databaseName, basicAuth=false, basicAuthUser=, basicAuthPassword=, withCredentials=false, isDefault=false, jsonData={}}_

The organization id from datasource is not correct. So I try to switch the current user organization after the organization creation:

**1. Create organization (same request as below)**

**2. POST http://localhost:3000/api/user/using/19**
_Request data: {"message":"Active organization changed"}_

**3. Create datasource**

**4. GET http://localhost:3000/api/datasources/14**
_Request data: {id=14, **orgId=1**, name=test16, type=influxdb, typeLogoUrl=, access=proxy, url=, password=password, user=, database=databaseName, basicAuth=false, basicAuthUser=, basicAuthPassword=, withCredentials=false, isDefault=false, jsonData={}}_

How can I add a datasource inside a specific organization (not the default one)?

Thanks

**Comment by torkelo** [comment]
the data source is added to the current active org

**Comment by loic911** [comment]
That's what I explain in the second case.
But the switch don't work with API keys, even if it tells me "Active organization changed".
I will use basic auth.

**Comment by torkelo** [comment]
no, api keys are always linked to a single org and role

**Comment by jcmcken** [comment]
@torkelo Unless I'm mistaken, one outcome of this design is that datasource operations can't happen in parallel (e.g. create multiple datasources for multiple organizations). Traditional REST APIs would nest the datasource under the organization, e.g. ``POST /api/org/20/datasources``, which seems more natural to me. Would it be worth creating a feature request for this nested API endpoint?

**Comment by torkelo** [comment]
Those, to some extent already exist under the /api/orgs/id/  route

**Comment by torkelo** [comment]
At least they do for users, not sure on orgs (on mobile)

**Comment by miton18** [comment]
From an administrator point of view, it's very interesting to create datasources for a specific org. Any way to do that ? A feature will come ?

**Comment by contactmat85** [comment]
Having trouble with the PUT operation to change the current organization.
I have 2 organization: FirstOrganization, SecondOrganization.
If I do:
` GET /api/org -> {"id":11,"name":"FirstOrganization","address":{"address1":"","address2":"","city":"","zipCode":"","state":"","country":""}}`

So I infer the FirstOrganization is the current. 
I am trying to change to the second. I am doing:

>curl_setopt($curl, CURLOPT_URL,         $url );
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1 );
curl_setopt($curl, CURLOPT_POST,           1 );
curl_setopt($curl, CURLOPT_CUSTOMREQUEST,  "PUT");
curl_setopt($curl, CURLOPT_POSTFIELDS,     '{"name":"SecondOrganization"}');
curl_setopt($curl, CURLOPT_HTTPHEADER,     array("Content-Type: application/json)")); 

but I get as response: {"message":"Organization name taken"} and current organization doesn't change.
I know that something get wrong becouse the output message is not the correct one.

Any Idea???

**Comment by daniellee** [comment]
@contactmat85 what you are trying to do is change the details of the current org. I think what you want to do is to switch the active org for the current user?

http://docs.grafana.org/http_api/user/#switch-user-context

I will update the docs tomorrow to be more clear. The wording is confusing.

**Comment by bkez322** [comment]
It would be spectacular if Grafana had a more restful api for Datasources, such as ‘/api/org/<org-id>/datasource’.

We manage a Grafana that multiple organizations use. We also built an internal tool to automatically keep all these orgs up to date with the same datasources at all times. 

Because of the current state of the datasource API, we accomplish this by adding the system admin account to every org beforehand, and then this tool must switch the admin’s context to the org we want to update, and then finally add the datasource.

Drawbacks with this approach include that only 1 datasource update operation can occur at once, and also the added complexity of ensuring the admin is a member of all orgs at all times.

If a more restful datasource api existed, this tool could be much simpler!

**Comment by marefr** [comment]
@bkez322 you should be able to provide the custom http header X-Grafana-Org-Id to select which organization to use for the api call.

**Comment by bkez322** [comment]
I had no idea that was a thing. I’ll try it out, thanks!
