### ISSUE TITLE
Feature Request: Allow optional configuration of minimum threshold for auto-calculated y-max in Graph

### ISSUE THREAD

**Issue by toddwh50** [grafana/grafana#5992]
I'm currently using Grafana 3.1.1 with InfluxDB data source.

It would make our dashboards much more clear if we could configure the a minimum bound for the y-max value when y-max is configured as "auto".

In many of our graphs, we are using the bars to show a count of issues/problems. So a very low value is good and higher is bad.

For example, in the following, there was a higher count of issues in the first part of the graph and the count was "better" later in the chart.
![image](https://cloud.githubusercontent.com/assets/17885456/18353859/40a205de-75a9-11e6-8104-2cb340b740b7.png)

But, if I zoom the timescale and only look at the latter period of the chart, it looks like this:
![image](https://cloud.githubusercontent.com/assets/17885456/18353945/7cb8eda8-75a9-11e6-89d7-35bd37e2d05f.png)

From a distance, without being able to read the y-axis labels, it would appear that there are just as many problems in the 2nd chart as there were in the first part of the 1st chart.

I think it would help a lot if I could configure a "Lowest Auto Y-Max" (not sure what to call it), maybe 10 or 20 in this case so that the bars don't reach all the way to the top and look like there are a lot of problems. If we could set this "Lowest Auto Y-Max" value to 20 in the 2nd chart above, then the highest bars (currently at the height of 3 units) would only be 15% of the height of the chart and it would be clear from a distance the the values are Low (e.g. "Good").

But, if the "Lowest Auto Y-Max" was set to 20 in the case of the 1st chart above, it would have no effect because the auto-calculate Y-Max is above the threshold of 20. So the chart would look the same.

**Comment by torkelo** [comment]
we will try to merge this feature in some time in the coming 2-3 months
https://github.com/grafana/grafana/pull/5720
