### ISSUE TITLE
Alerting: feature request: Better error feedback for message templating

### ISSUE THREAD

**Issue by SanielDous** [grafana/grafana#59929]
**What happened**:
User of our Grafana instance tried to use variables in their alert message like this:
![image](https://user-images.githubusercontent.com/26697239/206115247-a37fc7d2-4e02-4df3-ba49-f0acb2ee8ad6.png)
As there is no error displayed on the Grafana website this seems to be accepted by Grafana.
Recently I had a look into the logs of the Grafana container and there showed up thousands of error-logs.
The error log is always the same (except for the timestamp):

    logger=ngalert 
    t=2022-12-06T14:13:02.39+0000 
    lvl=eror 
    msg="error in expanding template" 
    name=message value="{{ $values.B.$Labels.shortcut.keyword }} {{ $values.B.$Labels.OS_CSName.keyword }} {{ $values.B.$Labels.INSTANCE_KIND }} ... {{ $values.B.Value }} ..!" 
    err="error parsing template __alert_alertname alert: template: __alert_alertname alert:1: bad character U+0024 '$'"

**What you expected to happen**:
I would expect that if the given alert message contains illegal characters or syntax is already declined when saving the alert.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new alert rule with the syntax from above. The alert rule is accepted by Grafana. Now have a look at the output of the backend of the Grafana instance. It should repeatedly log an error.

**Environment**:
- Grafana version: v8.5.3 (409e9bc9a5)
- OS Grafana is installed on: Docker, Arch Linux
- User OS & Browser: Windows, Google Chrome

**Comment by zuchka** [comment]
Thanks for creating this issue, @SanielDous 

> v8.5.3

troubleshooting request: The alerting platform is developed a very high tempo. Can you please try reproducing this on 9.3.X? thanks!

thank you

**Comment by SanielDous** [comment]
> also, in your screenshot, I see a red squiggle. Is that giving you any meaningful feedback?

Oh, I think that's only my spell checker.

**Comment by JacobsonMT** [comment]
Great idea! We have plans to implement something along these lines here: https://github.com/grafana/grafana/issues/60387
