### ISSUE TITLE
Dashboard edit mode

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#59953]
**Goal**
As a user of a dashboard I want to have a clear differentiation between editing and viewing so I can understand the nature of the changes I make and feel safer while using my dashboard.

Related issues:

- https://github.com/grafana/grafana/issues/56995
- https://github.com/grafana/grafana/issues/24663
- https://github.com/grafana/grafana/issues/62086

**Requirements & Caveats**
- The first version will not have a sharing option in edit mode. We will AB test if this hurts the sharing metric.

**Task list (optional)**
- [x] Create product DNA
- [ ] Implement sharing button AB test

**Resources**
- [Figma file](https://www.figma.com/file/ma9eTeG1SDCgmnKwZ6rzCt/Toolbar?type=design&node-id=815-4906&mode=design&t=mQV9YAWeZSpAOFIy-0)
- [Product DNA](https://docs.google.com/document/d/1FT7Kj2kfnlZA_sOIVDB_UYwiNao7jure099wOT1QQq0/edit?usp=sharing)

**Comment by mdvictor** [comment]
@natellium I think this can be closed as these are all solved by the new approach. I've checked #56995 as well and it doesn't seem to trigger changes.
