### ISSUE TITLE
Variable only shows first 1000 values

### ISSUE THREAD

**Issue by flodabo** [grafana/grafana#59959]
**What happened**:
variable does not show all returned values from a query. this happens, if the query returns more then 1000 values.

both in the preview in the __Dashboard Settings -> Variables__ as well as in the dropdown menu for the variable. pictures below.

**What you expected to happen**:

variable shows all returned values from a query, even if there is a lot of them.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a query that returns more than 1000 values.
	
	for example
	```flux
	import "influxdata/influxdb/schema"
	schema.tagValues(
	  bucket: "testbucket",
	  tag: "system",
	  predicate: (r) => r._measurement =="test",
	  start: -1d
	)
	```

	To create test data for this with influxdb as a datasource, i used the following bash script to write values into the datasource
	```shell
	#!/bin/bash

	for ((i = 0 ; i < 2000 ; i++)); do
	  curl --request POST \
	"${INFLUXDB_BASE_URL}/api/v2/write?org=${INFLUXDB_ORG}&bucket=${INFLUXDB_BUCKET}&precision=s" \
	  --header "Authorization: Token ${INFLUXDB_TOKEN}" \
	  --header "Content-Type: text/plain; charset=utf-8" \
	  --header "Accept: application/json" \
	  --data-binary "
		test,system=client$(printf '%05d' $i) temperature=${RANDOM:0:2} $(date +%s)
		"
	done
	```
	
	Other datasources can also be used. same test was also conducted with a mysql datasource.

2.	Use that query in a Query Variable in Grafana

3. Check variable for values. Only the first 1000 results are shown in the variable. the rest of the values not shown.

**Pictures**
![image](https://user-images.githubusercontent.com/8964487/206202570-7972907b-1331-4913-b84e-6234343847aa.png)
*query results in table panel, contains all expected values*

![image](https://user-images.githubusercontent.com/8964487/206202605-5356271d-9c0d-4fc4-aa3a-6a2014b9bd9a.png)
*query results in dropdown menu, values missing. only first 1000 elements shown*

![image](https://user-images.githubusercontent.com/8964487/206204887-cfc718ef-554b-46b0-b378-89a7633665f2.png)
*variable definition, note the values in the preview sorted by descending order*

**Anything else we need to know?**:

* when the same query is executed in a panel all values are shown. So this is specific to variables.
* if not fixable, this should be mentioned in the documentation.(i could not find this behavior mentioned in the documentation where i would expect it https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/ )
* tested with different browsers. same behavior.
* possible workaround: use Text Box varible to enable the user enter a value manually instead. May be not suitable for all situations.

**Environment**:
- Grafana version: 8.5.15 & 9.2.6
- Data source type & version: influxdb 2.5.1, mariadb 10.10
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows 10, Chrome 108 & Firefox 107
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @flodabo 

You can expand the limit inside the InfluxDB datasource plugin configuration:

![image](https://user-images.githubusercontent.com/37156449/206266421-fd8b67d8-81ce-4c45-9b44-81aeb1924bfa.png)

**Comment by flodabo** [comment]
configuring the datasource with `maxSeries: 5000` does not alter behavior.

-----------------------------

the issue does not seem to be related to the type of datasource.
the same thing happens with a mysql datasource:
for testing i created a dataset using:
```shell
mysql --host=<<insert_db_host_here>> -u <<insert_db_user_here>> -p --execute="create database test; use test; create table test(a int PRIMARY KEY); INSERT INTO test (a) SELECT seq FROM seq_1_to_2000;"
```
corresponding query: `select a from test.test;`


when the returned data is displayed in a panel all values are shown as expected. when query is used as a variable values are missing.

![image](https://user-images.githubusercontent.com/8964487/206392897-d3bd1d5c-55e1-47d9-8e36-75c1c1eb1bfc.png)
*variable settings with preview(mysql datasource)*

![image](https://user-images.githubusercontent.com/8964487/206393271-63f50420-d5f8-4674-9475-1d7a40a6c4f1.png)
*same query in panel shows all values(mysql)*

**Comment by zuchka** [comment]
Yes, there has always been a 1000 item limit for variables. The reason is because that select component has to load everything up front and it can hang servers.

See [this thread](https://github.com/grafana/grafana/issues/12664) and [this thread](https://community.grafana.com/t/size-limit-in-templating-variables/8920/6).

There has been [work done recently to implement a virtualized select component](https://github.com/grafana/grafana/pull/55629) but I don't think it's implemented yet.
