### ISSUE TITLE
Alerting - tsdb.Handle Request() error for divideSeries() function

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#5996]
Hi,

I've the following Graphite dashboard:

![1](https://cloud.githubusercontent.com/assets/12551929/18369539/9f6eabbc-7626-11e6-9cbe-f2aceb8dcdcd.png)

After creating the alerting rule based on the` #L - divideSeries` function and testing, it returns an error:
`tsdb.HandleRequest() error invalid character '<' looking for begining of value`

![2](https://cloud.githubusercontent.com/assets/12551929/18369646/6048f9b4-7627-11e6-955c-184dd2bc79c8.png)

Is it a bug or alerting for divideSeries is not supported yet? Other functions work ok.
I'm using latest build (8.9.16)

**Comment by bergquist** [comment]
Right now we do not support queries that reference other queries. I'm not sure we will support it either.

I'll add an error message that informs the user for now.

**Comment by pavleec** [comment]
Ok, thanks for quick response.

**Comment by torkelo** [comment]
this is fixed but to make it work you have to rebuild (modify something) your queries so that the targetFull property is rendered on the query model .
