### ISSUE TITLE
[Bug] Browser timezone is used sometimes even if UTC is selected for the org&user

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#5997]
I'm working with Grafana 3.1.1, 
both user and org are set to UTC in settings, 
some of the dashboards always render in UTC, some of the dashboards always render in browser tz.
I failed to determine what else differentiates these dashboards.

**Comment by torkelo** [comment]
what is the dashboards timezone setting?

**Comment by torkelo** [comment]
there are 3 levels, dashboard setting, if default then check user profile, if default, then check org seting

**Comment by earwin** [comment]
Ugh. My bad, I missed that when looking for the first couple of times. Sorry for the bother.
Funny thing, though, I cannot select "default" on dashboard setting. When I click it, it changes to browser/utc depending on whatever is set uplevel.

**Comment by torkelo** [comment]
@earwin you cannot set default on dashboard level? is the option missing? 

> When I click it, it changes to browser/utc depending on whatever is set uplevel.

Yes, that is what the profile and org settings do, change the default behavior on dashboard level. 

Dashboard Level -> Profile Level -> Org Level
if default -> check profile level -> if default check org level

**Comment by earwin** [comment]
@torkelo The option is there. I have "default", "local", "utc".
But when I click "default" it is not getting selected, instead I get one matching an uplevel setting.
Consequently, when I change uplevel setting, this does not get propagated to the dashboard.

I made a screen recording (17.8Mb) that illustrates the problem: https://dl.dropboxusercontent.com/u/920413/Timezone%20Bug.mov

**Comment by lastsky** [comment]
grafana 4.1.1:

Org level settings:
no settings at all (selector not presents)

Profile level settings:
User1 -> `UTC`
User2 -> `Local browser time`

Dashboard level settings:
can't set `Default`, auto-assigned to `UTC`. can be statically saved to `Local browser time`.

Then dashboard time can be configured only by selecting `UTC` or `Local browser time`.


Expected result:

User1 -> works with `UTC` dashboards
User2 -> works with `Local browser time` dashboards

Would you like please to clarify that settings?...
