### ISSUE TITLE
Possibility to sort stacked graph created using a templating variable

### ISSUE THREAD

**Issue by Alucardfh** [grafana/grafana#5998]
* **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using? 
v3.1.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Centos 7.2
- What did you do?
Create a stacked graph using a templating variable
- What was the expected result?
It is possible to select the order of the stacked metrics
- What happened instead?
The stacked metrics are sorted by lexicographic order

For example this graph contain two stacks (one below the Total Cores metric and one above)
![image](https://cloud.githubusercontent.com/assets/1701397/18387038/12c3ce7e-7692-11e6-8256-20edbcdd7def.png)

In lexicographic order it is currently quite hard to relate the legend and the graph.

It would be good if sorting the legend could also sort the stacking order.
Or if there was a way to specify that a stack should be done by increasing/decreasing metric values.

Because in the current situation you can end up looking at things like this : 

![image](https://cloud.githubusercontent.com/assets/1701397/18387144/bc265ea0-7692-11e6-8198-e4a5a48b6540.png)

Due to the big difference in value between the two metrics being stacked on top of each other ... the small one override the colour of the big one.

**Comment by torkelo** [comment]
you can create two different stack groups if you want to stack them individually. If you want to sort the series based on some avg or max of the whole series window Graphite and Elasticsearch already support that but no InfluxDB, so I suggest raising a feature request for that there. The sorting is better done there as you can then limit the number of series as well (top 5 series based on max value for the time range in each series for example).
