### ISSUE TITLE
missed "datasource: null," parameter  in panelDefaults for table panel

### ISSUE THREAD

**Issue by Kotove** [grafana/grafana#5999]
* **I'm submitting a ...**
- [ x ] Bug report

when switching from default (graphite) datasource to Mixed datasource in Table panel - it throws an error. 
`Plugin componnet error Object {message: "Failed to find exported plugin component for query-ctrl-mixed"}`
after switching back to default (graphite) and then back to Mixed - error doesn't appear.

root cause of this behavior is in
commit 16dbf3166d2246904a8766d5d403dd23706f4892
missed "datasource: null," parameter  in panelDefaults for table panel (public/app/plugins/panel/table/module.ts)
while
`setDatasource(datasource)` function in public/app/features/panel/metrics_panel_ctrl.ts
checks that 
` ... target.datasource = this.panel.datasource;
        if (target.datasource === null) {...`
this property must be null (but it is "undefined" because of missed in panelDefaults ).

**Comment by torkelo** [comment]
thanks for reporting this! fixed
