### ISSUE TITLE
Explore: "Show all timeseries" limited to 20 series

### ISSUE THREAD

**Issue by frankyi-gh** [grafana/grafana#59994]
**What happened**:
When a query returns >20 time series, the Explore page only shows 20 by default, with a "show all" button to display them all on the chart. However, clicking the "show all" button does not show all time series. 

Additional time series results only appear after selecting then unselecting an item from the legend. 

**What you expected to happen**:
Clicking "show all" button shows all time series

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the explore page and query something with >20 time series
2. click the "show all" button on the explore chart

**Anything else we need to know?**:

I don't see any relevant errors in the JS console.

**Environment**:
- Grafana version: 9.3.0 enterprise
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 22
- User OS & Browser: MacOS 12.3, Chrome
- Grafana plugins:
- Others:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by zuchka** [comment]
Thanks for creating this issue, @frankyi-gh 

this value is hardcoded into Explore's functionality:

https://github.com/grafana/grafana/blob/main/public/app/features/explore/Graph/ExploreGraph.tsx#L41-L42

I imagine it is designed to prevent the server from hanging in the event of a huge request

**Comment by Elfo404** [comment]
i think what @frankyi-gh is describing here is a bug with the show more button. while the 20 series hardcoded limit is set, clicking on that button should (and does) remove that limit, but only after interacting with the panel. possibly introduced by https://github.com/grafana/grafana/pull/58660

https://user-images.githubusercontent.com/1170767/207061460-b372fb7d-1762-4ad1-856a-aa483b2b6e88.mov

**Comment by frankyi-gh** [comment]
@Elfo404 thank you for the fix! Will this be released with 9.4.0?

**Comment by Elfo404** [comment]
yes, 9.4.0
