### ISSUE TITLE
Update SingleStat Form Style to gf-form 

### ISSUE THREAD

**Issue by bulletfactory** [grafana/grafana#6000]
Can be replicated on play.grafana.org

In the screenshot you'll notice the Unit field in the singlestat panel doesn't appear to be a dropdown and runs into the decimal field, feeling like 1 long input box. Should have the dropdown style similar to other panels' Unit field (2nd screenshot).

<img width="885" alt="screenshot 2016-09-09 12 46 25" src="https://cloud.githubusercontent.com/assets/1950595/18395190/7927672c-768b-11e6-99f5-ceb1b0dcfa99.png">

<img width="830" alt="screenshot 2016-09-09 12 50 16" src="https://cloud.githubusercontent.com/assets/1950595/18395279/f9ff02d8-768b-11e6-9f73-a3733e354a8c.png">

**Comment by torkelo** [comment]
the whole singlestat options panel needs to updated to new form styles, it is still using the old tight form styles

**Comment by bulletfactory** [comment]
ah - you're right. thanks.

**Comment by obfuscurity** [comment]
Thanks!
