### ISSUE TITLE
Bar Chart error with MySQL queries

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana#60002]
Hi, 
Since the last update, Bar Chars does not work anymore with our MySQL queries.
We have this error: 
![image](https://user-images.githubusercontent.com/24936778/206399966-67f033cc-a560-4484-85c2-4e7c06b30144.png)
But if we switch to the Table view it works: 
![image](https://user-images.githubusercontent.com/24936778/206400108-eb2e1ee1-28b0-4aff-a774-376e40808cf5.png)

And the SQL query works with other visualizations.

Grafana Version: 9.3.1 on Debian 11

If you have an idea, that's would be helpful :)

**Comment by leeoniya** [comment]
please attach a debug snapshot of your panel, config, and data using the `Panel > Inspect > More > Get help`

![image](https://user-images.githubusercontent.com/43234/204548998-17544b21-e23f-42f5-97c6-db6a94877c47.png)
