### ISSUE TITLE
No permissions tab in datasources

### ISSUE THREAD

**Issue by Tarkhrodd** [grafana/grafana#60006]
**What happened**:
When i use datasources the permission tab is not showed. I tried with elasticsearch, prometheus and zabbix,

![image](https://user-images.githubusercontent.com/82598358/206411704-f0dbd9c2-4e89-40a8-8167-aa890bb9e0d7.png)

**What you expected to happen**:
As seen in the documentation, with enterprise version, we can adjust who can access and use data source in a permission tab.

**Anything else we need to know?**:
I use the enterprise version but it say (Free & unlicensed)

![image](https://user-images.githubusercontent.com/82598358/206412766-793f5169-9c0f-4211-b32d-3365e3d64cdd.png)

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: Elasticsearch, Prometheus, Zabbix
- OS Grafana is installed on: Debian 10
- User OS & Browser: Win10, Firefox/Chrome

**Comment by zuchka** [comment]
the setting you are referring to is inside each dashboard's settings, not the datasource plugin configuration page.

![CleanShot 2022-12-08 at 07 46 53@2x](https://user-images.githubusercontent.com/37156449/206525951-240dc53e-3c84-4612-9029-781e253b6ee7.png)

**Comment by Tarkhrodd** [comment]
No, I was reffering to what is said on the documentation https://grafana.com/docs/grafana/v9.3/administration/data-source-management/

> Enable permissions for a data source: 
Navigate to Configuration > Data Sources.
Select the data source you want to enable permissions for.
On the Permissions tab, click Enable.

**Comment by bulmust** [comment]
Still permission tab is missing.

Grafana Version: Grafana v10.0.1 (5a30620b85)
![missing_permission_tab_datasource](https://github.com/grafana/grafana/assets/19466488/5dd02619-c139-4f89-84c6-f330ef011b6e)

**Comment by blessdismann** [comment]
Please reopen this! I want a permissions tab in the data source area so that I can be doing the same things as the documentation says I can do. I like when the actual program has the same functionality as advertised. 
My data source is Influx and I have this issue.

**Comment by pReya** [comment]
> Please reopen this! I want a permissions tab in the data source area so that I can be doing the same things as the documentation says I can do. I like when the actual program has the same functionality as advertised. My data source is Influx and I have this issue.

This feature is only available in Grafana Enterprise and Grafana Cloud.

**Comment by ei-grad** [comment]
This is a very unexpected thing. What is it about, 10 lines of code?
