### ISSUE TITLE
Localise user password change email

### ISSUE THREAD

**Issue by krzd7** [grafana/grafana#60027]
**Steps to reproduce**: set a language for a specific user and request a password reset. It would be great to apply the user language and send emails with translated instructions.

**Actual Result**: the user will receive an email in english.

**Expected Result**: the user should receive a translated email, based on its profile/preferred language.

**Environment**:
- Grafana version: 9.3.1

**Notes**: 
- I'm not sure if we should report localisation issues as a "bug", but I'd not consider it an "acessibility issue" either. I'm sorry if this is the wrong category.
- I don't remember if Grafana sends welcome emails or any other email directed to the user. If this is the case, translations are probably missing on other emails.

**Comment by ashharrison90** [comment]
hi @krzd7 👋 

thanks for raising this! we have an existing discussion for localisation enhancement requests here: https://github.com/grafana/grafana/discussions/59227

can i ask that you please add your request here so we can prioritise effectively? 

many thanks! 🙌
