### ISSUE TITLE
Support Link Column styling 

### ISSUE THREAD

**Issue by dmitrios** [grafana/grafana#6002]
- [X ] Feature request

The navigation in the table from master to detail events is quite limited. For example, if you have event table with correlation identifier, you cannot have a column with link to open dashboards that use value in that variable to get related events from the datasource. Doing this in each datasource plugin is inefficient as it will be duplicated functionality. Doing it in the datasource implementation is inconsistent: for example InfluxDb does not support string functions. It does work fine with SQL datasources because string functions are available.      

The easiest solution would be to add column style in addition to String,Number and Date. Include Sanitize HTML option, name of dashboard and name of the variable to use for constructing relative link as the value of the cell.

**Comment by torkelo** [comment]
great idea :)

will close as there is already an issue for it , https://github.com/grafana/grafana/issues/3754
