### ISSUE TITLE
Clock Plugin feature request for Stopwatch with display format for DD:HH

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6003]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options]

just tried the CLOCK plugin

would be cool to have a **Timer** feature and have the display formatable for DD:HH
(it has a Countdown but no Stopwatch/timer)

**Comment by torkelo** [comment]
please open feature requests here: https://github.com/grafana/clock-panel/issues
