### ISSUE TITLE
Graph: Display/Series Override .. provide Decimals override

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6005]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Would be useful to allow the Overrides to specify a DECIMAL for a pen/alias where mixed line types are used e.g. Temperature at 17.3oC and Specific Gravity at 1.054

**Comment by torkelo** [comment]
and do they share the same axis?

**Comment by roscoe57** [comment]
No

**Comment by torkelo** [comment]
But the  you can specify y-axis in the series override and specify the unit in the axes tab

**Comment by roscoe57** [comment]
there is no unt that I like for specific gravity 1.XXX (density)

otherwise, I specify the DECIMALplaces in the LEGEND tab to get the show
table & mouse over to show to 3 d.p  I just accept seeing Temperatures to 3
dp when I do this


Regards

Alistair Ross

Mob: +44 (0) 7971 817051
Tel: +44 (0) 141 246 5558

**Comment by torkelo** [comment]
yes, there is no gravity unit

**Comment by roscoe57** [comment]
why have you closed ?

the only sort of solution you have suggested is not supported 
why not have decimal places as series override ?
or have a custom way to define UNIT for where a there is none suitable ?

**Comment by torkelo** [comment]
you can specify decimals in the legend options, you said these same axis so you have must have temperature on one axis and gravity on the other?

**Comment by roscoe57** [comment]
its not a big deal, but ...
even though units of Temperature selected there is only ONE Legend Decimals
and if you pick 3 dp (to show gravity) then all the HOVER & Table Legends
including the Temperatures now display 3dp


[image: Inline image 1]
