### ISSUE TITLE
Graph Panel Pen to Use a 'Global' Value Mappings Feature Request

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6006]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Nightly 4.x.x
- What datasource are you using?Influxdb

It would be useful to allow a PEN on a GRAPH to use a GLOBALY defined Value Mapping Set (something like that in the SINGLESTAT panel)

Example:

Equip123_Mode metric/tag has Integer format where 100=IDLE, 50=RUN, 60=HELD etc

Allow a common global text lookup, sorry Value Mappings to be defined and used in any Dashboard panel.

Then when the graph is displayed it would become more readable to show RUN rather than just 50, the actual pen 50 would still be used as a level on the graph.

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/9292 (better described )
