### ISSUE TITLE
Explore: UX issues with Table and Graph panel

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#60075]
Feedback from Torkel:

> Just noticed a small UX issue in Explore. The Graph container and Table container uses Collapse component (only used in Explore), I get a cursor pointer when hovering over both headers (and a focus when tabbing), as the header is a button. But none of these panels are collapsible (nothing happens when I click). Also why is Graph title left aligned and Table centered?

![Image](https://user-images.githubusercontent.com/745532/206657857-6017cf68-421e-49ef-89d3-300994c5e36e.png)

**Comment by Elfo404** [comment]
Closing this as fixed by https://github.com/grafana/grafana/pull/66370, for other panels when we'll eventually move them to PanelChrome the issue will be fixed as well (tracked in https://github.com/grafana/grafana/issues/61563)
