### ISSUE TITLE
Datasource templating requires full datasource name values

### ISSUE THREAD

**Issue by deejay1** [grafana/grafana#6009]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

3.1.1
- What datasource are you using?

Graphite
- What OS are you running grafana on?

Ubuntu 14.04
- What did you do?

Created a template variable of type custom with multiple values separated by commas.
Entered "graphite $my_template_variable" into panel datasource field
- What was the expected result?

Panel reads data from "graphite my_value" datasource.

- What happened instead?

"Datasource named my_value" doesn't exist or nothing at all

**Comment by torkelo** [comment]
you need to use the variable type `Datasource` for data source variables
