### ISSUE TITLE
Alerting: Allow re-ordering of Notification Policies

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#60101]
It's currently not possible to re-order notification policies in the policy tree. This is of little importance if none of the notification policies have overlapping label matchers.

This becomes more important if you _do_ have notification policies with overlapping label matchers and you want to use the deterministic algorithm of the tree selection (depth-first, left to right) to match the correct policy.

It should therefore be possible to re-order notification policies of the root route and child policies.

See https://github.com/grafana/grafana/discussions/52574
Prom docs https://prometheus.io/docs/alerting/latest/configuration/#route

**Comment by gtirloni** [comment]
We've migrated from the legacy alerting and would like to introduce new notification policies while keeping the old ones in place. For that, we need to created nested policies at the top of the tree but that's currently not possible (new nested policies go to the bottom). Yes, there will be some overlaps so I was looking to rearrange the policies.

Until this is implemented in Grafana, is there a workaround that avoids having to delete and recreate everything from scratch? Can we edit JSON somewhere?
