### ISSUE TITLE
Exported dashboards contain multiple instances of repeated panels

### ISSUE THREAD

**Issue by MatMeredith** [grafana/grafana#6011]
I have a panel in my dashboard which is repeated for each node in my deployment (by repeating on a template variable NODE).

When I export the dashboard, the exported JSON file contains multiple instances of this panel -- one for each node that existed at the time the dashboard was exported.

When another user imports this dashboard, if they don't yet have any nodes (so the NODE variable is empty) they see panels for all the nodes that I had when I exported the dashboard (including e.g. showing the IP addresses of my nodes -- which I display in the panel title).

I'm running Grafana v3.1.1 (commit: a4d2708).  Is this not the issue that was supposedly fixed by https://github.com/grafana/grafana/issues/5084 (which I thought was in v3.1.1)?

**Comment by torkelo** [comment]
Cannot replicate this. When I export a dashboard with repeated panels, only the source panel is there: 

![image](https://cloud.githubusercontent.com/assets/10999/18464457/835594f4-7991-11e6-9aa6-ca7df1451c34.png)

Tested here:
http://play.grafana.org/dashboard/db/graphite-panel-repeats?var-app=backend&var-server=backend_01&var-server=backend_02&var-server=backend_03&var-interval=$__auto_interval

**Comment by MatMeredith** [comment]
But it reproduces for me reliably.   What diagnostics can I provide you?   Like I say, I'm running v3.1.1 (commit: a4d2708).   I'll e-mail you an example exported dashboard.
