### ISSUE TITLE
Influxdb tags with forward slashes '/' break grafana

### ISSUE THREAD

**Issue by Ismael** [grafana/grafana#6012]
- **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  InfluxDB 0.13
- What OS are you running grafana on?
  Linux
- What did you do?
  Build a query with a tag that includes forward slashes
- What was the expected result?
  Graph!
- What happened instead?
  InfluxDB says the query is invalid. Plus sign in query editor no longer works.

Query is:
SELECT mean("resp_time") FROM "test" WHERE "url_class" =~ /web/start/ AND time > now() - 5m GROUP BY time(200ms) fill(null)

![plusbroken](https://cloud.githubusercontent.com/assets/120270/18435041/3d84355e-78c7-11e6-9d45-cf62b0e2d93b.png)

When I press +, the following query is issued:
SHOW TAG KEYS FROM "test" WHERE "url_class" =~ /web/start/

And I get 400 error:
{"error":"error parsing query: found start, expected ; at line 1, char 53"}

I guess the error is in not escaping the '/'.
This query works: SHOW TAG KEYS FROM "test" WHERE "url_class" =~ /\/web\/start\//;

**Comment by torkelo** [comment]
not sure how to fix this as Grafana uses the `/` to detect a regex pattern.

**Comment by fsvehla** [comment]
This happens for example with the cgroups telegraf plugin.

**Comment by erSitzt** [comment]
This happens with measurements too i think.
We are sending metrics for apps in mesos/marathon to influxdb an the app names are built like paths in the filesystem
e.g.
/project1/appname/version0.9

**Comment by jessabe** [comment]
I believe this has been fixed as I can't replicate this in 7.x, so closing this bug for now. If you're still having problems please let us know & we can reopen.
