### ISSUE TITLE
Adding an expression changes all the my labels on a panel.

### ISSUE THREAD

**Issue by OranMZT** [grafana/grafana#60126]
**What happened**:

I am currently creating a simple time series panel of "current" and "voltage". Each entry is labelled as expected ("voltage {component_id="PSU001", location="arches", stand_id="ED001"}, and "current {component_id="PSU001", location="arches", stand_id="ED001"}") but when I add any kind of expression they both become the same with the label "component_value component_value {component_id="PSU001", location="arches", stand_id="ED001"}".

Before adding expression
![image](https://user-images.githubusercontent.com/119887504/206769656-f6cc6ffb-db91-46e9-b61c-9232088f0cfa.png)

After adding expression
![image](https://user-images.githubusercontent.com/119887504/206769806-0499a5b7-0b48-454e-87a9-6cb68b61736b.png)

**What you expected to happen**:

I am expecting that my original queries will be unaffected by the addition of an expression and retain their original labels.

**How to reproduce it (as minimally and precisely as possible)**:

Create a plot with an InfluxDB data source (im using flux) and attempt to insert a expression (constants work for this, not just expressions that refer to my queries)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana cloud (latest)
- Data source type & version: InfluxDB Cloud 
- OS Grafana is installed on: Cloud
- User OS & Browser: Windows, Chrome
- Grafana plugins: None
- Others:

**Comment by OranMZT** [comment]
I've just realised this error can be mitigated with "resample" expressions, I still get the weird name change but I am able to do my calculations

**Comment by zuchka** [comment]
one additional note @OranMZT 

Thanks for creating this issue, @gstephant 

I am not 100% sure but I don't know how compatible template variables (client-side) are with expressions (server-side). Server side expressions were mostly developed to power the new alerting platform.

I would try and make use of transformations for these kinds of data transforms inside a dashboard panel. We have an extensive number of transformations to choose from and they are well maintained/developed:

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/

you will find that transformations play much nicer with templating as well
