### ISSUE TITLE
Flaky test: TestFeatureToggleFiles in pkg/services/export

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#60132]
The test `TestFeatureToggleFiles` intermittently fails the CI on unrelated changes.

Here is an example of a build where it failed:
https://drone.grafana.net/grafana/grafana/92531/1/7

**Comment by yuri-tceretian** [comment]
This PR was supposed to fix the problem https://github.com/grafana/grafana/pull/60030 but I still see it in the build of PR https://github.com/grafana/grafana/pull/60129

**Comment by yuri-tceretian** [comment]
Closing via https://github.com/grafana/grafana/pull/60164
