### ISSUE TITLE
Explore chart throws an exception when the a query in a set is hidden

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#60138]
**What happened**: With multiple queries in the explorer, if you hide a then the visualization panel throws a JS exception.

**What you expected to happen**: No exception. The results for other queries should be visible.

**How to reproduce it (as minimally and precisely as possible)**:
Create an explore page with two queries, then hide the first one by clicking the "eye" icon. An exception is thrown. Re-order the queries by dragging and observe that the panel no longer throws an exception. Unhide both queries, then hide the second one. Observe another exception.

Here is a sequence of screenshots that illustrate a minimal reproduction.
<img width="1864" alt="Screenshot 2022-12-12 at 11 09 58 AM" src="https://user-images.githubusercontent.com/1951900/206954155-7216a3dc-abcc-4d69-931e-5b36cc8fefd5.png">
<img width="1913" alt="Screenshot 2022-12-12 at 11 10 04 AM" src="https://user-images.githubusercontent.com/1951900/206954162-bf5eb6e3-9eed-42b7-80ac-1bf83b4e7af1.png">
<img width="1902" alt="Screenshot 2022-12-12 at 11 10 08 AM" src="https://user-images.githubusercontent.com/1951900/206954170-c0aacdfe-8296-429a-99b6-05b11a6edc18.png">

**Environment**:
- Grafana version: commit a589929c92
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: macOS with Firefox, Safari & Chrome
- Grafana plugins: Standard Grafana Cloud plugin bundle

**Comment by svennergr** [comment]
The error is 

```
TypeError: Cannot read properties of undefined (reading 'fields')
    at ExemplarsPlugin.tsx:122:42
    at Array.forEach (<anonymous>)
    at Ta (ExemplarsPlugin.tsx:117:19)
    at children (TimeSeriesPanel.tsx:136:32)
    at children (GraphNG.tsx:269:25)
    at d (VizLayout.tsx:98:18)
    at ra (react-dom.production.min.js:157:137)
    at za (react-dom.production.min.js:180:154)
    at Zs (react-dom.production.min.js:269:343)
    at Ou (react-dom.production.min.js:250:347)
```

pointing to this line: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/plugins/ExemplarsPlugin.tsx#L122

@grafana/observability-metrics you recently added this in https://github.com/grafana/grafana/pull/59743. Would be great if you can take a look at this. Something similar was recently fixed in https://github.com/grafana/grafana/pull/60011.

**Comment by samjewell** [comment]
@gtk-grafana and team: **thanks** for fixing this ❤️
