### ISSUE TITLE
Grafana OSS 9.3 & Amazon Managed Prometheus Alert Manager

### ISSUE THREAD

**Issue by elasticdotventures** [grafana/grafana#60135]
My `Silence` an alarm button doesn't appear when using an Amazon Managed Prometheus Alert manager backend.

An example of the Silence button is outlined on this [page](https://aws.amazon.com/blogs/mt/announcing-prometheus-alertmanager-rules-in-amazon-managed-grafana/) which suggesting that AWS has gotten this working in their managed Grafana offering.  

This is easy to test by adding this to the environment before running `yarn build` && `make run`
```
export GF_AUTH_SIGV4_AUTH_ENABLED=true
```

I've taken a look at the source code to try and figure out how complex this might be to solve / implement.  Not sure if it's a bug or a feature at this point. 

https://github.com/grafana/grafana/blob/5d6bdc60b161dc23b5b0bd1d1c57a82a520aa4ee/public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx#L105-L106

I'm not sure if this is related or not -- but I've noticed when running Grafana OSS and trying to use it with Amazon Managed Prometheus (AMP).   The alert manager API /v2 seems to be supported, but the Grafana logic (incorrectly) reports as Prometheus since the URL is at a different location and "assume Prometheus" is the else-fail position.   My suspicion is that something in that dataSource setup is janky. 

I'm posting this issue here and expect to follow up with a patch.   My goal is to make the Silence button appear, or at least figure out why it isn't appearing. 

While I'm not much of a react dev. (took a bootcamp years ago), I believe this is related to the culprit causing the OSS version of Grafana 9.3  to skip the  push. Button() for "Silence" button feature because it (incorrectly) believes that it is readonly data source. 

There are only two "Conditions" for the Silence button to be pushed (and I assume there is no other restriction that would remove it):
```
 if (alertmanagerSourceName && contextSrv.hasAccess(AccessControlAction.AlertingInstanceCreate, contextSrv.isEditor)) {
```  
[](https://github.com/grafana/grafana/blob/5d6bdc60b161dc23b5b0bd1d1c57a82a520aa4ee/public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx#L104-L106)

I am an admin user, so I'm going to assume the `contextSrv` isn't the issue for now.  At least that is what Occams razor suggests. 

tracing this issue:
```
  const alertmanagerSourceName = isGrafanaRulesSource(rulesSource)
    ? rulesSource
    : getAlertmanagerByUid(rulesSource.jsonData.alertmanagerUid)?.name;
```
[const alertmanagerSourceName = isGrafanaRulesSource(rulesSource)](https://github.com/grafana/grafana/blob/5d6bdc60b161dc23b5b0bd1d1c57a82a520aa4ee/public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx#L28-L31)

* in my case, `isGrafanaRulesSource` is false, so that calls `getAlertmanagerByUid(rulesSource.jsonData.alertmanagerUid)?.name;`
alertmanagerSourceName

not sure where to go from here.

**Comment by elasticdotventures** [comment]
🤔 hi level question: is there a better way to debug this than making changes to the JS code and then re-running `yarn build` followed by a `make run`

**Comment by elasticdotventures** [comment]
so as I expected the `alertmanagerSourceName` is set to undefined. 
`isEditor` & `hasAccess` are true

**Comment by elasticdotventures** [comment]
my `alertmanagerUid` is undefined.   So I think if I solve that..

```
| alertmanagerUid            | string  | Prometheus and Loki                                              | UID of Alert Manager that manages Alert for this data source.                                                                          
```
[alertmanagerUid](https://github.com/grafana/grafana/blob/5d6bdc60b161dc23b5b0bd1d1c57a82a520aa4ee/docs/sources/administration/provisioning/index.md#L182)

**Comment by elasticdotventures** [comment]
I've tried several different flavors of prometheusType and prometheusVersion
I am getting 404 errors when the Grafana client attempts to access
```
/api/datasources/proxy/2/api/v1/status/buildinfo
/api/ruler/xxxxxx/api/v1/rules/test/test
```
@nathanrodman any chance you could help me out?

my jsonData looks roughly like this (some values removed)
{
    "directUrl": "https://aps-workspaces.ap-southeast-2.amazonaws.com/workspaces/ws-xxxxxx",
    "httpMethod": "POST",
    "prometheusType": "Cortex",
    "prometheusVersion": "1.14.0",
    "sigV4AssumeRoleArn": "arn:aws:iam::1234:role/OrganizationAccountAccessRole",
    "sigV4Auth": true,
    "sigV4AuthType": "keys",
    "sigV4Region": "ap-southeast-2"
}

**Comment by elasticdotventures** [comment]
At this stage I need to take a break, but it seems like `manageAlerts` is failing.
my data source for Prometheus (not alert manager) says "Alerting supported"
the "Manage alerts via Alerting UI" is enabled.

the proxy for `/api/v1/status/buildinfo` always return a 404.
[detectPrometheusVariant](https://github.com/grafana/grafana/blob/5d6bdc60b161dc23b5b0bd1d1c57a82a520aa4ee/pkg/infra/usagestats/statscollector/prometheus_flavor.go#L68)

My suspicion is something got b0rked during the recent unified alarming enhancements.   The "buildinfo" url doesn't seem to work in the AWS implementation of cortex. 

```
awscurl -X POST --region ap-southeast-2 --service aps https://aps-workspaces.ap-southeast-2.amazonaws.com/workspaces/ws-xxxxxx/api/v1/status/buildinfo
```

**Comment by elasticdotventures** [comment]
So I figured out a few items, firstly, the AWS Managed Prometheus (present release) does not support the `buildinfo` autodetect feature capability. 
* https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html

Second, using terraform if I set the `alertmanagerUid` of the  `json_data_encoded` data of `resource "grafana_data_source" "prometheus_cortex"` to the `uid` property of the `resource "grafana_data_source" "prometheus_alertmanager"` then I can make the `Silence` button appear. 

(the silence button still doesn't actually work, but it appears, which feels like progress)

**Comment by jcdauchy-moodys** [comment]
> and finally, figured it out.
> 
> yay. .. but also 😓 I had gotten this working by setting the AMP url with an extra /xyz (which was required "hack" in a prior 8.x release of Grafana) with version 9.x the URL changed so it didn't require the (now superfolous) /alertmanager suffix on the URL.
> 
> This is why nothing was working! Closing this ticket.

@Brian Horakh, would you mind sharing your prometheus and alertmanager JSON datasource, since I upgraded to 9.3.1, I cannot make the prometheus datasource  work :(

Thanks.

**Comment by safa-topal** [comment]
We are having a related issue with OSS, although `buildinfo` endpoint returns 403 in our case: https://github.com/grafana/grafana/issues/60636
