### ISSUE TITLE
Public dashboard only rendering one metric from Graphite wildcard query

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#60141]
**What happened**:

Since the refactoring done in https://github.com/grafana/grafana/pull/59608 public dashboard graphite wildcard queries now only render the last metric matched. 

**What you expected to happen**:

All matching metrics rendered.

**How to reproduce it (as minimally and precisely as possible)**:

Create new dashboard with Graphite source, and a wildcard query that returns 2 or more metrics: (optionally as seen in screenshot I also added a non-wildcard query, just to test that too, but its not necessary to trigger the issue)

![image](https://user-images.githubusercontent.com/2304970/207024360-9c591500-3bdd-4f98-944f-6e8729dee9b8.png)

Save, share as public. See the wildcard query only rendering one metric on the public dashboard:

![image](https://user-images.githubusercontent.com/2304970/207024855-f4d8eb3c-5fcc-41cd-b312-0f097d9eccd8.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: [v9.4.0-92566pre (7bf7308ea5)]
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, FF
- Grafana plugins: Default
- Others:

**Comment by bohandley** [comment]
Hi @bobemoe! Thank you for finding this, so this is only in public dashboards as a result of the change to handle multiple queries? @mmandrus any thoughts?

**Comment by bobemoe** [comment]
> so this is only in public dashboards as a result of the change to handle multiple queries? - @bohandley

Yep, it certainly seems that way. I reported the original issue (at which point wildcards were rendering but multiple queries weren't) and upon testing the fix (multiple queries now work) noticed the wildcard now doesn't work!

**Comment by mmandrus** [comment]
Hi @bobemoe, thanks for reporting this and apologies for not catching it! The pubdash team will investigate.

**Comment by bobemoe** [comment]
No worries, awesome project. Thanks for everything.

**Comment by mmandrus** [comment]
Look for this fix in the 9.3.3 release in mid-January. Thanks again!
