### ISSUE TITLE
Social engineering hook possible in login?failedMsg function.

### ISSUE THREAD

**Issue by sysadmin1139** [grafana/grafana#6014]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

This was discovered on Grafana 2.6, but it still works on v3.1.1 (commit a4d270).

It looks like the failedMsg function for login accepts arbitrary URLencoded strings, which allows an attacker to customize the text presented to a user if they follow a malicious link. This is part of a social-engineering attack used to phish login credentials.

![grafanaevil](https://cloud.githubusercontent.com/assets/812860/18443139/2d8428c8-78d9-11e6-89c0-082f48d0ec22.png)

This can be recreated by submitting the following URL:

http://example.com:3000/login?failedMsg=Your%20account%20has%20been%20suspended%20due%20to%20suspicious%20activity.%20To%20reactivate%20it%2C%20please%20contact%20evil%40example.com%20with%20your%20authentication%20details%20to%20reactivate%20your%20account.

The string can be hidden using deceptive markup in email or other messaging that accepts HTML.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in https://github.com/grafana/grafana/commit/b4111d78e15d37e8f55e736a88f8acf6dbe00a0e
