### ISSUE TITLE
Grafana does not fetch Cloudwatch ElasticSearch Metrics

### ISSUE THREAD

**Issue by pratapsingh** [grafana/grafana#6015]
* **I'm submitting a ...**
- [ X] Bug report

Please include this information:
- What Grafana version are you using?  - Version 3.1.1
- What datasource are you using?  - Cloudwatch
- What OS are you running grafana on?  - Amazon Linux 4.4.5-15.26
- What did you do? - Created a dashboard. Selected Data source as Cloudwatch. Namespace "AWS/ES" Metric "CPUUtilization" , DomainaName then selected my Elastic search cluster name from drop down. 
- What was the expected result? - Graph should have appeared 
- What happened instead? - No graph were visible. Tried with other metrics too but same result. Not getting graph for namespace AWS/ES for other namespace works fine 
![grafana-cloudwatch-elasticsearch](https://cloud.githubusercontent.com/assets/484164/18446490/2a5a4292-7940-11e6-9ef5-f14af0152da9.jpg)

**Comment by Aamir010** [comment]
Can you please provide snapshot of data source config?

**Comment by mtanda** [comment]
You may need to specify both of `ClientId` and `DomainName` dimension.
(I success to show CPUUtilization graph)

**Comment by pratapsingh** [comment]
@mtanda  Thanks that worked

**Comment by chetanbasuray** [comment]
Is there a predefined dashboard for elasticsearch data from cloudwatch on grafana?
I am trying to add the DomainName and ClientId as variables to this graph, but there seems to be no way to achieve this...
