### ISSUE TITLE
Loki Label Browser redesign

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#60156]
Original message from @niat22 

> Since the Label Browser is one of the first steps within the user journey, I was wondering if we want to consider redesigning the modal for a better user experience and ease of use? e.g.:
> -  Include clear instructions for the user e.g 1. choose a label, 2. choose a value
> - Give the label a clear format and make the labels look like buttons/actionable item
> - Define the steps (there are actually 2 and not 3 steps)

**Comment by stevendungan** [comment]
@matyax @niat22 there may be synergies/overlaps with work for planned work for customers with large queries (what we are proxying as "Inditex" work)

in addition to getting them more quickly to a correct query, we also want to make sure we are NOT getting them to a non-performant query; we're still fleshing out the definition of non-performant but it will be things we've discussed elsewhere.

**Comment by stevendungan** [comment]
im curious more broadly too if this will surface in the Getting Started research - i believe we have 4 different ways that i know of to start a logs query in Explore today:
* Code mode (i.e. LogQL)
* Label browser within Code mode
* Query Builder mode
* Kickstart your query across both code mode and query builder mode

Do we have data on who is doing what? (This seems like a great place to check out FullStory when ready too!)

**Comment by evandandrea** [comment]
We need UX assistance to move this one forward. Dropping from Q1.
