### ISSUE TITLE
GitLab OAuth doesn't verify group membership

### ISSUE THREAD

**Issue by kravvcu** [grafana/grafana#60167]
**What happened**:

So this came out in a weird way. The setup is:

- hosted GitLab
- hosted Grafana 
- Grafana is configured with the hosted GitLab as an OAuth2 auth method

Due to me being an admin of both I have *visibility* (but not *membership*) of every group in GitLab.

Logging into Grafana through GitLab ends up being unsuccessful:

![image](https://user-images.githubusercontent.com/12016675/207063944-c3a2c86a-8239-4caa-88b2-cd550bfabeb0.png)

The request fails always after a minute. During this time Grafana logs hundreds of api calls made to the `group` endpoint.
It's [listing](https://github.com/grafana/grafana/blob/b71ae13b63f5743d163dbbb97c67d84874172c1a/pkg/login/social/gitlab_oauth.go) all groups the user has visibility on. I believe the request should be checking the membership status of the logging in user, so possibly changing the line to the below would make more sense (and fix the bug since visibility is checked, not membership status, as the `allowed_groups` is meant to handle?):

```go
# don't hardcode the access level ;)
for page, url := s.GetGroupsPage(client, s.apiUrl+"/groups?min_access_level=10"); page != nil; page, url = s.GetGroupsPage(client, url) {
```

Here's a log entry for our production system:
![image](https://user-images.githubusercontent.com/12016675/207070147-3db956db-1d91-4d25-b545-f55f672b8813.png)

Furthermore, the [allowedGroups] check should be made **before** the groups are listed, as the listing result is discarded anyways if [allowedGroups is empty](https://github.com/grafana/grafana/blob/main/pkg/login/social/gitlab_oauth.go#L19).

**What you expected to happen**:

I should successfully log in within reasonable time.

**How to reproduce it (as minimally and precisely as possible)**:

Hard to artificially setup I believe, because the issue is with the time it takes to iterate over all GitLab instance groups which have some sensible / random information / members etc.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3
- Data source type & version:
- OS Grafana is installed on: container
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by ashutosh887** [comment]
I would like to work on the issue @mellieA @vtorosyan

**Comment by leoashish** [comment]
I would like to work on this issue @mellieA and @vtorosyan.

**Comment by vtorosyan** [comment]
Thanks everyone for an interest to contribute. PRs are welcome for this issue, please assign yourself to the issue when starting to work on it to indicate to others that you have picked it up.

**Comment by ashutosh887** [comment]
Sure @vtorosyan 
I've set up the Project on my local machine

**Comment by ashutosh887** [comment]
The application is working on my machine
Can someone guide me how should I approach this Issue @mellieA  @vtorosyan

**Comment by mellieA** [comment]
@ashutosh887 thank you for working on this! 

You can check out our guide(s) about contributing [here](https://github.com/grafana/grafana/blob/HEAD/CONTRIBUTING.md#your-first-contribution). The link includes the steps you'll take for your first contribution. Which includes signing the contributor agreement and creating a PR to submit your changes for review.

**Comment by ashutosh887** [comment]
Thanks a lot @mellieA 
I wanted some help in understanding the flow of project
Can you please help me join Contributors Group for discussing project?

**Comment by yuri-potatoq** [comment]
Given the [current flow](https://github.com/grafana/grafana/blob/main/pkg/login/social/gitlab_oauth.go#L100) i see the suggestion in production and the problem no longer happening.

Can we close that issue?
