### ISSUE TITLE
Query builder isn't showing remove option in drop menu

### ISSUE THREAD

**Issue by enkinduweles** [grafana/grafana#60161]
Hi, after I noticed that (issue described below), I tried another versions 8+ until 8.5 but I got the same issue.
I can’t update to latest version of grafana.

**What happened**:
At first time nothing is render, only a line (Left Image). If I inspect element on browser I can see an html UL element rendered without content.

After that I need click twice, first to close drop menu and then one more time to reopen, so the content of drop menu appears correctly and I can delete select fields or where conditions (Right Image)

![Query Builder](https://user-images.githubusercontent.com/56451652/207055971-c2b69fbd-3a61-43c2-b17e-ee4cd72dc912.jpg)

**What you expected to happen**:
See Remove option in drop down menu at first time.

**How to reproduce it (as minimally and precisely as possible)**:
I tried using the docker image in the version we use 7.5.16 and when I identified this issue I started testing other images from other versions of grafana.
- I run docker image 
- Setup postgres database
- Add a panel to configure a query

I also tried locally running yarn start (front) and make run (backend).

Grafana: 7.5.16
OS: Windows 11
Browser: Chrome and Firefox latest version

**Comment by mellieA** [comment]
I tried this out with Grafana 8.5 . I was able to click on the WHERE or GROUP BY condition and see the Remove option immediately.  

I saw you tested multiple versions of Grafana 8, are you also seeing the issue with 8.5? The only difference I see is that I'm using macOS and the latest version of Chrome. 

<img width="562" alt="Screen Shot 2022-12-12 at 7 52 13 PM" src="https://user-images.githubusercontent.com/18175287/207214720-726fb0d6-ed94-48e9-9990-33306e57b286.png">

**Comment by enkinduweles** [comment]
I tried 8.5+.

When you mentioned that the only difference was the OS, I tried It on Linux, but It also had the same problem.

Is there any file that I could share to bring more informations?

**Comment by mellieA** [comment]
@enkinduweles following up on some older issues - are you still seeing this problem?

**Comment by gabor** [comment]
hi, as we got no feedback for a long time, we'll close the issue for now we can reopen it if new info arrives.
