### ISSUE TITLE
Displaying opposite thresholds background when Level2 = 0

### ISSUE THREAD

**Issue by elenigen** [grafana/grafana#6016]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? http://play.grafana.org/
- What datasource are you using? Graphite
- What OS are you running Grafana on? Any
- What did you do? Create a graph with Thresholds: Level1: 1 / Level2: 0
- What was the expected result? Show the threshold Level1's color in the background from 0  to 1
- What happened instead? The threshold Level's color is added to the background from 1 to infinite.
  Workaround: Since 0 is detected as a "null" value, by using 0.1 grafana detect Level2 is no longer null so the expected result is displayed.

**Comment by elenigen** [comment]
Workaround:
![image](https://cloud.githubusercontent.com/assets/8632319/18449168/31c4a476-78fc-11e6-8090-569eb8aa1619.png)

**Comment by torkelo** [comment]
think this is fixed in later versions
