### ISSUE TITLE
Azure Monitor metrics request failing with dimension on Azure/Insights/Cosmos DB dashboard

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [grafana/grafana#60175]
**What happened**: 
After upgrading to v9.3.1 (from v9.2.3), I realized that several of the panels on the Azure/Insights/Cosmos DB dashboard (included with the Azure Monitor datasource) failed to load. After looking closer, the failures appear to happen on all of the panels that use Dimensions to group the results into series. For each one, the following error is shown:
`request failed. status: 400 The 'POST' is not supported for theis request. please use 'GET'`

Screen shots are provided below:
![image](https://user-images.githubusercontent.com/14931768/207082587-37b19157-9a54-4b78-a9fb-4c721b2f9fab.png)
![image](https://user-images.githubusercontent.com/14931768/207083693-71cdaa4f-7009-4499-8bad-89f31a461496.png)

**What you expected to happen**:
Panels should render correctly with the Dimension used to "group" the results into series.

**How to reproduce it (as minimally and precisely as possible)**:
Install the Azure/Insights/Cosmos DB dashboard from the Azure Monitor datasource and point it to a valid Cosmos DB resource in Azure.

**Anything else we need to know?**:
NA

**Environment**:
- Grafana version: v9.3.1
- Data source type & version: Azure Monitor v1.0.0
- OS Grafana is installed on: Linux (container)
- User OS & Browser: Windows 10/Chrome
- Grafana plugins:
- Others:

**Comment by Blackbaud-ChrisBlythe** [comment]
Appears to be fixed in v9.3.2 already

**Comment by natellium** [comment]
Thanks for reporting the issue @Blackbaud-ChrisBlythe! Apologies it took us a bit to look into it, but glad you found it was fixed. I believe this PR might have been the one fixing it https://github.com/grafana/grafana/pull/59700 that was reported in https://github.com/grafana/grafana/issues/59629. Will close this one now.
