### ISSUE TITLE
Allow Y-Axis label padding

### ISSUE THREAD

**Issue by jamessewell** [grafana/grafana#6019]
- [X] Feature request

It would be really, really great if there was a per-graph y-axis label padding value.

This would allow manual management of aligning the y axis between horizontally stacked graphs.

Even better would be an option to auto-align to the widest y-axis-label in the same horizontal space- but I that sounds much more difficult.

Cheers,
James

**Comment by torkelo** [comment]
what do you mean "between horizontally stacked graphs" ? 

The graph panel already have so many options, an option like this will I afraid not happen, unless it's a very common scenario, but even then maybe the panel can do it automatically.

**Comment by jamessewell** [comment]
It's a very, very, very common scenario - in fact it would effect almost everyone who has multiple rows on a dashboard.

Picture attached. You can see that the labels being different widths are pushing the start of the y-axis out of alignment.

This makes visually interpreting stacked data non-intuitive. 

![image](https://cloud.githubusercontent.com/assets/1216931/18464397/2747dada-79d4-11e6-8394-aeae4fd36117.png)

Pushing the labels over the graph and adding transparency underneath might work, but that would be very messy and potentially unreadable in some situations.
