### ISSUE TITLE
Query: invalid parameter "match[]": parse error: unexpected "("

### ISSUE THREAD

**Issue by OPSTime** [grafana/grafana#60223]
![grafana](https://user-images.githubusercontent.com/5848331/207309865-a3315374-d5e0-4dd1-a783-c922a1802194.png)

**Query:**
`label_values(query_result(label_replace(kube_deployment_status_replicas{namespace="$namespace"},"workload","$1","deployment","(.*)") or label_replace(kube_statefulset_status_replicas{namespace="$namespace"},"workload","$1","statefulset","(.*)")),workload)`

**Comment by usmangt** [comment]
Hi @OPSTime,

Thanks for opening this issue.

From appearance it does seems that there are additional brackets after the OR

at the end **)),workload)`** these 2 )) do add up (to what I noticed).

Can you please check it again? Thanks

**Comment by OPSTime** [comment]
**No more than brackets were found.**

`label_values(
	query_result(
		label_replace(
			kube_deployment_status_replicas{namespace="$namespace"},
			"workload",
			"$1",
			"deployment",
			"(.)"
		) 
		or 
               label_replace(
			kube_statefulset_status_replicas{namespace="$namespace"},
			"workload",
			"$1",
			"statefulset",
			"(.)"
		)
        ),
	workload
)`

**Comment by usmangt** [comment]
Thanks and does the error only appear with this specific promql?

**Comment by OPSTime** [comment]
Did you find the reason for this problem?
