### ISSUE TITLE
Grafana Faro

### ISSUE THREAD

**Issue by Manasa-VG** [grafana/grafana#60222]
**What happened**:
I would like to try Faro on Grafana to monitor our Browser 

**What you expected to happen**:
Not many resources found, but I read this here https://grafana.com/docs/grafana-cloud/faro-web-sdk/?pg=oss-faro&plcmt=hero-btn-3 saying not publicly available. 

**How to reproduce it (as minimally and precisely as possible)**:
I have both Grafana enterprise and cloud , need to know how I get started with Faro

**Environment**:
- Grafana version: 9.3 Cloud
- Data source type & version: Faro 
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome

**Comment by usmangt** [comment]
Hi @Manasa-VG,

Thanks for opening this issue.

I had asked this question directly with our Faro team.

So, this is currently a **private** beta release. We will be rolling it out to just select customers.  Is this someone would you be interested in "beta-ing" and providing feedback?

**Comment by usmangt** [comment]
Got some more information on this topic that we do have a blog post that introduces Faro and links to a Google Form so that interested users can record their interest for the beta (right at the bottom) https://grafana.com/blog/2022/11/02/introducing-grafana-faro-oss-application-observability/

**Comment by Manasa-VG** [comment]
Hey @usmangt ,

Thank you for the details!

I would like to be part of beta-ing as I want to try and learn how Faro works so that we can implement this to our work projects.

**Comment by usmangt** [comment]
Then, please check the previous comment where I posted the details as how to enroll in the beta program

**Comment by Manasa-VG** [comment]
Thank you for the information!
