### ISSUE TITLE
Clean up all references to contributing guidelines in the Grafana repo

### ISSUE THREAD

**Issue by chri2547** [grafana/grafana#60236]
This work involves reviewing and scrubbing the readme, contributing docs, style guide, etc. Where appropriate, we need to link to the published toolkit docs.

**Comment by GrafanaWriter** [comment]
Yes, let's get this done, please now that the Toolkit it out.

**Comment by GrafanaWriter** [comment]
Can we please make a task list of affected repos, @jdbaldry, so we can share the work out to the writers.

**Comment by GrafanaWriter** [comment]
Repos:

- [ ] Grafana/grafana - @chri2547 to update
- [ ] ...etc.

**Comment by GrafanaWriter** [comment]
From a Grafana docs perspective, this is complete, with reference now to our [Toolkit](https://grafana.com/docs/writers-toolkit/).
