### ISSUE TITLE
Loki: Autocomplete improvements ideas 

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#60233]
**Ideas on what could we improve for Loki autocomplete suggestions:**

- [x] For `unwrap` suggest only labels that have number/bytes/duration values similar to this in [UnwrapParamEditor](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/querybuilder/components/UnwrapParamEditor.tsx#L79)
- [x] Remove extra added space when you write `| ` and autocomplete adds additional space

**Comment by matyax** [comment]
> For unwrap suggest only labels that have number/bytes/duration values 

@ivanahuckova do you think we can do that while the user types? I understand we would need to query for label values.

**Comment by ivanahuckova** [comment]
@matyax we already have label values. In `getParserAndLabelKeys` in https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/LanguageProvider.ts#L469, we get full log lines samples which include label + values. So we just need to check and filter out those labels for unwrap, which have incorrect values. We already do the same thing in here https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/querybuilder/components/UnwrapParamEditor.tsx#LL72-L80

**Comment by matyax** [comment]
@ivanahuckova right! Completely forgot about that. Thanks for the explanation!
