### ISSUE TITLE
ElasticSearch terms are not replicated in Grafana

### ISSUE THREAD

**Issue by Aamir010** [grafana/grafana#6024]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using? :- Version 3.1.1
- What datasource are you using? :- ElasticSearch
- What OS are you running grafana on? :- Centos 7
- What did you do? :- Creating dashboard from Filbeat and topbeat indices data 
- What was the expected result? :- All terms need to be populated so, I will map query result on graphs
- What happened instead?:- Only some terms are being visible on filebeat indices and even lesser terms are on topbeat indices. I also have Kibana running on my infra which have all terms.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3772

**Comment by Aamir010** [comment]
Is that PR release for this ?

**Comment by torkelo** [comment]
not yet

**Comment by Aamir010** [comment]
Just wants to confirm, so currently multiple terms are not supported on this version ?

**Comment by torkelo** [comment]
yes, you can group by multiple terms. 

Honestly I did not understand your english, but guessed your problem was that the autocomplete / field suggestion did not show all your available field

**Comment by Aamir010** [comment]
yes, you are correct my problem is with autocomplete/field suggestion. I do have have multiple terms in "topbeat" indices but all are not showing in drop down.
