### ISSUE TITLE
Explore - Split resize widen/narrow uses exact same icon as moving the time window

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#60253]
**What happened**:
In 9.4 we introduced [resizing the split pane](https://github.com/grafana/grafana/pull/58683).

Defining an absolute time in Explore creates arrows that allow you to "nudge" the time window. Those arrows are also introduced in the context of widening/narrowing the explore pane window in split mode. Having redundant icons that do vastly different actions is confusing.

<img width="979" alt="Screen Shot 2022-12-13 at 9 04 00 AM" src="https://user-images.githubusercontent.com/1533128/207371300-c375a222-254c-4107-b306-2032e603fd72.png">

**What you expected to happen**:
Different icons for the different actions

**How to reproduce it (as minimally and precisely as possible)**:
Set an absolute time in Explore. Go into split mode.

**Environment**:
- Grafana version: main

**Comment by radiorental** [comment]
![collapse](https://user-images.githubusercontent.com/3299847/207642092-b3d7bef7-a220-4dd8-9d01-4ac0d4563fc9.svg)
![expand](https://user-images.githubusercontent.com/3299847/207642096-ed1c4325-1b96-40c9-b0d8-1f6425e598e1.svg)
