### ISSUE TITLE
openldap integration

### ISSUE THREAD

**Issue by yuvarajanlga** [grafana/grafana#6026]
Hi Guys,

It looks like old issues. But could not resolve it. i have installed openldap on ubuntu and its configured and its working. could you please let me know where i am doing mistake. 

if i use group_dn = "*" , its working fine. 

I configured with grafana. But during authentication with ldap user, i am getting error.

FYI;-

t=2016-09-13T16:51:22+0800 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc8207459d0)({\n DN: (string) (len=42) \"cn=view test1,cn=cusview,dc=***ldap,dc=net\",\n FirstName: (string) (len=4) \"view\",\n LastName: (string) (len=5) \"test1\",\n Username: (string) (len=10) \"view test1\",\n Email: (string) \"\",\n MemberOf: ([]string) {\n }\n})\n]"
t=2016-09-13T16:51:22+0800 lvl=info msg="Ldap Auth: user [view test1 []] does not belong in any of the specified ldap groups, ldapUser groups: %!v(MISSING)"

ldap.toml

[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "cn=cusview,dc=***ldap,dc=net"
org_role = "Viewer"

**Comment by torkelo** [comment]
Have you tried this ldap search string in ldap? 
`cn=cusview,dc=***ldap,dc=net"`does not  look valid to me. 

And the group_dn cannot be an expression like this, it either has to be a full complete dn or just a wildcard

**Comment by yuvarajanlga** [comment]
cn=cusview,dc=lgaldap,dc=net. 

this is my actual dn.

**Comment by torkelo** [comment]
That is not a group though, the member of attribute seem to be empty

**Comment by yuvarajanlga** [comment]
Hi torkelo,
You can see below "customer" user is part of customer-group.  Am i doing any thing wrong ? please highlight my mistake. thank you.

Ldap entry:-
========
cn=customer-group
 	dn	cn=customer-group,ou=groups,dc=lgaldap,dc=net
 	cn	customer-group
 	gidNumber	500
 	memberUid	adam
                                customer
 	objectClass	posixGroup
                                top

grafana ldap configuration:-
=====================
[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "cn=customer-group,ou=groups,dc=lgaldap,dc=net"
org_role = "Viewer"

logs:-
====


t=2016-09-14T12:04:14+0800 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc82054d2d0)({\n DN: (string) (len=38) \"cn=customer,ou=users,dc=lgaldap,dc=net\",\n FirstName: (string) \"\",\n LastName: (string) (len=8) \"customer\",\n Username: (string) (len=9) \" customer\",\n Email: (string) \"\",\n MemberOf: ([]string) <nil>\n})\n]"
t=2016-09-14T12:04:14+0800 lvl=info msg="Ldap Auth: user [ customer []] does not belong in any of the specified ldap groups, ldapUser groups: %!v(MISSING)"
t=2016-09-14T12:04:14+0800 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"

**Comment by yuvarajanlga** [comment]
thank you. Finally issue has been resolved. its due to memberOf attribute issues.

**Comment by satishdotpatel** [comment]
@ycombinator what was the issue, We are having same issue. We don't have memberOf: attributes in openldap, because we are using memberuid:  

Does memberOf: is mandatory ?

**Comment by doctore74** [comment]
https://github.com/grafana/grafana/issues/6396

**Comment by MahadevG** [comment]
@yuvarajanlga 
I am new to Grafana and LDAP I need to integrate grafana and openLDAP. I have installed OpenLDAP in windows system . I tried with [Grafana and NGinX](https://community.grafana.com/t/how-to-use-auth-proxy-with-nginx/2257/9) but i got 500 error response.
I followed [tutorial ](http://kukusan-network.blogspot.com/2012/01/how-to-setting-ldap-openldap-in-windows.html)to install ldap.
Can you give your suggestions regarding how can I create users , how to integrate grafana with openldap, how to map the users and how to do sso. 

Thanks.
