### ISSUE TITLE
Fix missing Share Panel image

### ISSUE THREAD

**Issue by Eve832** [grafana/grafana#60276]
Bug
Image missing

**To Reproduce**
1. Go to https://grafana.com/docs/grafana/latest/sharing/share-panel/
2. Scroll down to Embed panel

**Expected behavior**
Interactive iframe image should render. It doesn't

![Screen Shot 2022-07-12 at 7 55 07 AM](https://user-images.githubusercontent.com/81647476/178521199-437f11d5-6049-40f6-a84e-fd6c9a110714.png)

**Comment by chri2547** [comment]
We removed this screenshot as part of the new nav project, closing this issue.
