### ISSUE TITLE
Panel relative time/time shift - panel shows nothing/freeze/won't load any data

### ISSUE THREAD

**Issue by virtualdreams** [grafana/grafana#60285]
**What happened**:

I want to restrict a panel to today regardless of the global time selection at the top. For this I have set "Relative time" and "Time shift". However, this leads to the fact that no more data is displayed in the panel. Errors are also not displayed. Neither in the UI nor in the log.
Also, I can't find any answers that pin a panel to today and yesterday regardless of the global time selection.
The help page is also not really informative.

**What you expected to happen**:

Working panel with data limited.

![Grafana 3](https://user-images.githubusercontent.com/3603832/207549591-a78be4d0-cf2d-4d00-8110-efed7ac85a43.png)

**How to reproduce it (as minimally and precisely as possible)**:

![Grafana 2](https://user-images.githubusercontent.com/3603832/207549506-009f7202-60c6-47c4-a556-3d12668075ce.png)

Big empty panel bottom left

![Grafana 1](https://user-images.githubusercontent.com/3603832/207549547-1a3ba809-db8d-4cb0-be85-0e5c55039fe0.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: InfluxDB 2.5.1 / timeseries every 5s
- OS Grafana is installed on: Debian 11 Bullseye
- User OS & Browser: WIndows 10/ Firefox 108
- Grafana plugins: -
- Others: -

**Comment by mellieA** [comment]
@virtualdreams I tested this on https://play.grafana.org/d/2N0n0Er7k/influx-2-2-live-noaa-buoy-data?orgId=1&from=now%2Fd&to=now&refresh=5s 

I set the query options to today & yesterday as you did and backed out to the main dashboard. I didn't save the changes to the dashboard since it's public - but the panel seems to work as expected with relative time ranges. 

Have you noticed what might be different between the working and non-working panels that you shared?

**Comment by virtualdreams** [comment]
I also set "yesterday" under the options (now-1d/d and now-1d/d) as a test. The data was refreshed exactly once, but I think the first now-1d/d does it.
Under Query Inspector -> Query -> Refresh nothing happens again. Loads forever.

**Comment by mellieA** [comment]
@virtualdreams I'm following up on some older issues and wondering if this is working for you now?

**Comment by virtualdreams** [comment]
It still does not work as desired. I still can't set a panel to a fixed time period, e.g. yesterday regardless of what was set in the Time range.


I have since set it to Today so far.
