### ISSUE TITLE
Alerting: Not Able to customize JSON data while sending alert via Webhook - contact points.

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana#60284]
**What happened**:
Not Able to customize JSON data while sending alert via Webhook - contact points.

**What you expected to happen**:
We should get more control over JSON data in alert which grafana sends. 
We need to customize json data while sending alert through webhook configuration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.7 / 9.3.0 / 9.3.1
- Data source type & version: Influxdb 2.0
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser: windows firefox
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@Dhyanesh97 this is expected. Did you intend to create a feature request?

**Comment by mellieA** [comment]
We have new documentation pending review here https://github.com/grafana/grafana/pull/60109 that states: 


> You cannot use message templates to:
> 
> - Change how images are included in notifications, such as the number of images in each notification or where in the notification inline images are shown
> - Change the design of notifications in instant messaging services such as Slack and Microsoft Teams
> - Change the data in webhook notifications, including the structure of the JSON request or sending data in other formats such as XML
> - Add or remove HTTP headers in webhook notifications other than those in the contact point configuration

**Comment by Dhyanesh97** [comment]
@mellieA We can add this as feature request it it not already present.

**Comment by bobemoe** [comment]
Already present at https://github.com/grafana/grafana/issues/6956 ?

**Comment by mellieA** [comment]
I agree it looks like a duplicate. The other feature request didn't belong to a project, I added it to the alerting project for more visibility. We have moved feature requests to discussions - I noticed there is another feature request out there that has an update: 

https://github.com/grafana/grafana/discussions/44334#discussioncomment-4049361 

> A https://github.com/grafana/grafana/pull/58058 to allow templating in the message and title fields has just been merged. This feature should be part of v9.3.0.
