### ISSUE TITLE
Sending two requests on every key stroke when changing the dashboard title

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana#60298]
**What happened**:
Like said in title, when trying to create/update a dashboard, while changing the dashboard title on every key stroke, there two requests to check if there is a dashboard or folder with such name... 

![image](https://user-images.githubusercontent.com/23135339/207578273-9a8c4549-e2f3-42b7-b717-b0c0c7456036.png)

**What you expected to happen**:
Use a debounce

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: N/A
- OS Grafana is installed on: *
- User OS & Browser: *
- Grafana plugins: N/A
- Others: N/A

**Comment by axelavargas** [comment]
Hey @Bujupah 👋🏾, 

Thanks for reporting this issue, I tried to reproduce it using versions 9.3.0 and 9.3.2, but I couldn't replicate the behavior you described. However, I did notice that when we open the "Save" drawer and when we save the dashboard,  we send two requests to the API, is this what you are experiencing? If not, could you provide a video of the issue and let us know if you have any plugins or feature flags enabled in your instance? This information would be helpful in triaging the problem quickly. 

My test: 

https://user-images.githubusercontent.com/239999/208471382-4b882477-ff53-42b6-9c4d-97fdf14b012f.mp4


Thank you 🙏🏾

**Comment by Bujupah** [comment]
I will update you ASAP

**Comment by natellium** [comment]
I was able to reproduce this. As mentioned above you first need to try to save the dashboard with a name that already exists. Once that's done, the end point is called twice every key stroke.

Thanks for the report @Bujupah. I'll move this into our backlog.

**Comment by c-oreills** [comment]
Could I clarify the intended behaviour here?

The two requests being sent are for different entities: one for a folder of the same name, one for a dashboard of the same name. The implementation is [here](https://github.com/grafana/grafana/blob/91221bc4362e50b9cca6dbff3a8342b2991900d2/public/app/features/manage-dashboards/services/ValidationSrv.ts#L41).

If have inferred from manual testing that having a Dashboard and Folder called the same thing is invalid:
* With an existing folder F, we cannot save a new Dashboard as F
* With an existing dashboard D, we cannot save a new Folder as D
  * Exception: we _can_ save a Dashboard as General despite the General folder existing by default. I assume this is an implementation quirk of the General folder.

So, I think the two requests are required to enforce these constraints and this is not a bug or something we can "debounce"? Can we close?

**Comment by Bujupah** [comment]
@c-oreills I understand that there are two required requests to ensure that there is no dashboard nor folder with that name, but at some point these requests gets triggered on each key stroke… for eg. if you type “some dashboard” there will be two requests per letter… 14x2=28… 28 requests just gets triggered when typing the name.

This I observed myself while debugging other issues… but yeah I thought its worth mentioning

**Comment by c-oreills** [comment]
@Bujupah thanks for clarifying, that makes sense! 😄 

I think it may be worth debouncing it if this was in the normal flow of naming a dashboard. Given that this only triggers in a very specific edge case, I agree with your action of closing this. Thanks very much!
