### ISSUE TITLE
[BUG] exponential legend entry duplicates for duplicate query paths 

### ISSUE THREAD

**Issue by luxifr** [grafana/grafana#6030]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708) 
- What datasource are you using?
Graphite-API
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Use multiple queries to the same path
- What was the expected result?
get the same amount of entries in the legend as I have queries
- What happened instead?
get n^2 amount of entries in the legend for queries with equal path, where n is the number of queries with equal path

![1](https://cloud.githubusercontent.com/assets/665715/18472093/997abce0-79b5-11e6-90f4-6496697f2094.png)

![2](https://cloud.githubusercontent.com/assets/665715/18472096/9d4e55a2-79b5-11e6-8c05-ef54857c9196.png)

![3](https://cloud.githubusercontent.com/assets/665715/18472101/9ff86694-79b5-11e6-8c8c-295de93111d8.png)

It's not noticeable in the pictures but there is only N graphs drawn, i.e. with 2 queries to the same path, 2 lines are drawn and 4 values are in the legend and with 3 queries to the same path 3 lines are drawn and 9 values are in the legend and so on.

This is pretty unnerving in my use case as in some graphs I query the same value path in multiple queries - transforming it in one query to have a summary of multiple servers AND exceptional values in the same graph.... like so:

![example](https://cloud.githubusercontent.com/assets/665715/18472244/7773c21c-79b6-11e6-9313-c69d80643eef.png)

(there should be 5 "exception" entries, as there are 5 servers in this data set... but due to this bug it's 20 "exception" entries - 4 identical ones per server!)

**Comment by torkelo** [comment]
Likely a graphite issue. could you show the raw graphite json response? (open chrome dev tool network tab)

**Comment by luxifr** [comment]
you're right, thanks!
