### ISSUE TITLE
Navigation: Issues without Top Nav enabled

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#60312]
Our Connections feature relies on the new Top Nav and apparently doesn't work properly if it is not enabled. This is kinda expected, as we planned to release it after the top navigation is shipped to production. 

As we are not 100% sure that the feature-toggle for turning the top-nav off will be removed soon, probably it's worth summarising what is not working with the current navigation, and also if it is a low-hanging fruit to fix it.

- [ ] List issues with the current navigation in a comment below
- [ ] Check if it is a low-hanging fruit to fix it

**Comment by mikkancso** [comment]
It seems that Grafana without the Onboarding plugin works as expected.

Some problems arise when the plugin is present.
[Screencast from 2022-12-29 14:06:42.webm](https://user-images.githubusercontent.com/13637610/209955472-d0152413-b8d5-4899-85b8-cd9e69e04865.webm)

1. the margins of plugin pages are non-existent
2. side-bar and tabs navigation does not work well below the second level, i.e. if I'm on the Data sources page, I can't easily find my way to the Infrastructure page. 
3. the back button on integration's details page always throws me on the Connect data page (this should be easy to fix in the plugin)

I think the cause of the main issue is that plugin pages are not wrapped in `<PluginPage>`, or any other fallback mechanism that would make these things work.

Honestly, I think it still gives an okay-ish experience - in the sense that the functionality is there. But I don't think it would be a lot of work to fix everything, either.

**Comment by leventebalogh** [comment]
Amazing, thanks for the investigation and update @mikkancso!

Although I am not convinced that we would ever use it without the Top Nav enabled, maybe we could dedicate and "hour" to it (time-boxed) and see if we can eliminate these issues. That way at least we wouldn't need to worry about them.
