### ISSUE TITLE
Switching to builder mode with a valid PromQL query shows a "Query Parsing Error" modal

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#60314]
**What happened**:
When switching to builder mode with a valid PromQL query a confirmation modal is being displayed. Since I have a valid PromQL query it should not happen. 
The Query:
```
sort_desc(sum without(job, instance) (rate(grafana_http_request_duration_seconds_count[$__rate_interval])))
```

The problem is `$__rate_interval`. I think the parser cannot handle `$` properly. Here is the function handling that https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L105

![image](https://user-images.githubusercontent.com/820946/207597524-3c55dc75-c1c8-415d-98b3-cba9a5340a85.png)
![image](https://user-images.githubusercontent.com/820946/207597545-f410a82b-18ae-4659-90f0-a982e2c60f00.png)

**What you expected to happen**:
No modal should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to Explore with the Prometheus datasource selected
- In the `Code Mode` write the following query `sort_desc(sum without(job, instance) (rate(grafana_http_request_duration_seconds_count[$__rate_interval])))`
- Click `Builder` to switch to `Builder Mode`
- Observe there is a confirmation modal
- Even though it says there are errors it will parse the query properly in `Builder Mode`

**Anything else we need to know?**:
The problem is `$__rate_interval`. I think the parser cannot handle `$` properly. Here is the function handling that https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L105

**Environment**:
- Grafana version: `v9.4.0-pre`

**Comment by aocenas** [comment]
Template variables in the range should be specifically handled here somewhere https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/parsing.ts#L203. I am pretty sure this worked so either something changed or it's some combination of other parts of the query.

**Comment by itsmylife** [comment]
@aocenas Thanks for commenting. We have a PR already. It would be nice if you can review it also https://github.com/grafana/grafana/pull/60461
