### ISSUE TITLE
CSP Blocks Google-Font

### ISSUE THREAD

**Issue by fionera** [grafana/grafana#60316]
**What happened**:
On Grafana 9.3.1-1 on CentOS, Grafana tries to load a Font from Google but fails because of the CSP.

![Screenshot_20221214_135835](https://user-images.githubusercontent.com/5741401/207601351-d97fca1f-695a-498b-917f-9ff030708c4d.png)

/usr/share/grafana/public/sass/base/_fonts.scss:
```
/* latin */
@font-face {
  font-family: 'Roboto Mono';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/robotomono/v13/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2)
    format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC,
    U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* latin */
@font-face {
  font-family: 'Roboto Mono';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/robotomono/v13/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2)
    format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC,
    U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

/* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'),
    url(#{$font-file-path}/roboto/ek4gzZ-GeXAPcSbHtCeQI_esZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
  unicode-range: U+0460-052f, U+20b4, U+2de0-2dff, U+A640-A69F;
}
...
```

**What you expected to happen**:
The Font is served locally

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana on CentOS

**Anything else we need to know?**:
I dont know why this is packaged like it is. In the repo its correct.

**Environment**:
- Grafana version: v9.3.1
- Data source type & version: -
- OS Grafana is installed on: CentOS 7.9.2009
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

**Comment by fionera** [comment]
This is also the reason why Requests via the Image-renderer fail.

```
{"level":"error","message":"Browser console error","msg":"Refused to load the font 'https://fonts.gstatic.com/s/robotomono/v13/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2' because it violates the following Content Security Policy directive: \"font-src 'self'\".\n","url":"http://localhost:3000/d-solo/tolmtyOVz/icinga2-asmdisk?var-hostname=s093052&var-service=oracle_asm_space-s093052-grid-DATA&var-command=ssh_restrict&panelId=1&orgId=&width=640&height=280&theme=light&from=now-7d&to=now&render=1"}
{"level":"error","message":"Browser console error","msg":"Refused to load the font 'https://fonts.gstatic.com/s/robotomono/v13/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2' because it violates the following Content Security Policy directive: \"font-src 'self'\".\n","url":"http://localhost:3000/d-solo/tolmtyOVz/icinga2-asmdisk?var-hostname=s093052&var-service=oracle_asm_space-s093052-grid-DATA&var-command=ssh_restrict&panelId=1&orgId=&width=640&height=280&theme=light&from=now-7d&to=now&render=1"}
/usr/src/app/build/browser/browser.js:45
            this.log.error('Browser request failed', 'url', req.url(), 'method', req.method(), 'failure', req.failure().errorText);
                                                                                                                       ^

TypeError: Cannot read properties of null (reading 'errorText')
    at Browser.logRequestFailed (/usr/src/app/build/browser/browser.js:45:120)
    at /usr/src/app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/usr/src/app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Page.emit (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:146:106
    at /usr/src/app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/usr/src/app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at NetworkManager.emit (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    ```

Disabling CSP is a workaround but not very nice

**Comment by alkuzad** [comment]
@mellieA this is serious issue breaking Grafana Image renderer, do you have any recommendations for remediation?

**Comment by tolzhabayev** [comment]
Hey @grafana/grafana-frontend-platform - it seems like https://github.com/grafana/grafana/pull/34836 did not make it into the `v9.3.x` branch https://github.com/grafana/grafana/blob/v9.3.x/public/sass/base/_fonts.scss 

although it did make it into [v9.2.x](https://github.com/grafana/grafana/blob/v9.2.x/public/sass/base/_fonts.scss) and [v9.4.x](https://github.com/grafana/grafana/blob/v9.4.x/public/sass/base/_fonts.scss)

For whoever finds this issue - consider upgrading to `9.4`

**Comment by joshhunt** [comment]
To follow up - For Grafana 9.4 we [removed the last font pointing to Google Fonts](https://github.com/grafana/grafana/pull/59544) and all fonts are now served directly by Grafana, so this issue should not occur any more.

If you're facing this issue, you're strongly recommended to upgrade to the latest Grafana. If you're unable to upgrade Grafana, you can tweak the CSP used in your Grafana config https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#content_security_policy_template. See [the default value in 9.3](https://github.com/grafana/grafana/blob/v9.3.x/conf/defaults.ini#L330).

I was not able to reproduce this issue directly myself with Grafana 9.3.1 - Firefox is picking up Roboto Mono from '../fonts' and image renderer is successfully rendering panels using it, so it's tough to recommend the tweak to the CSP to work around this pre 9.4.

![image](https://user-images.githubusercontent.com/46142/231728449-65544e76-fa48-4283-b691-969fb0beda56.png)

If you're still facing issues with this in latest Grafana, please open a new issue with reproduction steps.
