### ISSUE TITLE
Unable to import Dashboard with Mixed Datasource

### ISSUE THREAD

**Issue by matthicks05** [grafana/grafana#6032]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
**- What Grafana version are you using?**
3.1.1
**- What datasource are you using?** 
InfluxDB (Mixed)
**- What OS are you running grafana on?** 
Using Official Docker Image (Running on Host Ubuntu 16.04)
**- What did you do?** 
Created a dashboard using a Mixed datasource (using two different InfluxDB datasources).  Exported to JSON, and tried to re-import the dashboard.  
**- What was the expected result?**
The dashboard should be imported successfully using the mixed datasource.
**- What happened instead?
![mixed_dashboard_error](https://cloud.githubusercontent.com/assets/7862124/18478135/bf338374-7995-11e6-8aea-5bdd37273ccd.png)
[Greenbutton-1473777127212.json.txt](https://github.com/grafana/grafana/files/470079/Greenbutton-1473777127212.json.txt)

**
Received an error that Mixed datasource was "undefined" (see attached screenshot).  Unable to save and complete the import.

**Comment by torkelo** [comment]
thanks for reporting this!
