### ISSUE TITLE
Color each day's background differently

### ISSUE THREAD

**Issue by Ismael** [grafana/grafana#6033]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It's hard to see where each day begins and ends when viewing many days. It would be nice if the days would be colored differently (for instance, a lighter background on even days).

**Comment by steverweber** [comment]
https://grafana.net/plugins/fetzerch-sunandmoon-datasource
as a temp workaround could perhaps try.

**Comment by willneumob** [comment]
👍

**Comment by torkelo** [comment]
implemented by time regions
