### ISSUE TITLE
CloudWatch: Add namespaces AWS/AppRunner and AWS/IoTSiteWise and relevant metrics

### ISSUE THREAD

**Issue by VermaPriyanka** [grafana/grafana#60357]
**What happened**:
The namespaces listed in the drop-down of the Query editor for Cloudwatch plugin does not list namespaces AWS/AppRunner and AWS/IoTSitewise currently. 

**What you expected to happen**:
View AWS/AppRunner and AWS/IoTSitewise namespaces in the namespaces dropdown and underlying metrics in the query editor in Builder mode.

**How to reproduce it (as minimally and precisely as possible)**:
Pop-open the drop down for namespaces in the Panel query editor for Cloudwatch datasource.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.7
- Data source type & version: Cloudwatch
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins: Cloudwatch
- Others:

**Comment by mellieA** [comment]
related discussion https://github.com/grafana/grafana/discussions/60001

**Comment by sunker** [comment]
Thanks for creating this issue @VermaPriyanka. `AWS/AppRunner` metrics were added in [Grafana 9.0.0](https://github.com/grafana/grafana/pull/49048). 

I was going to add metrics for the `AWS/IoTSiteWise` namespace, but the [documentation](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/monitor-cloudwatch-metrics.html) doesn't seem to specify what dimensions to use. Would you be able to follow this up with the SiteWise team? For reference, [this](https://docs.aws.amazon.com/redshift/latest/mgmt/metrics-listing.html) is what the metrics documentation looks like for AWS Redshift.

Also note that when metrics are missing in Grafana, the user is still able to add them manually. 
![custom-metric](https://user-images.githubusercontent.com/2388950/207906016-3cbed020-892a-4c67-aea4-5950644e8694.gif)

**Comment by VermaPriyanka** [comment]
@sunker Thank you for looking into this. Similar reference for IoTSitewise can be found [here](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/monitor-cloudwatch-metrics.html)

**Comment by sunker** [comment]
I know @VermaPriyanka. That page doesn't specify what dimensions are valid for each metric.

**Comment by VermaPriyanka** [comment]
@sunker [This](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/monitor-cloudwatch-metrics.html) page is now updated with the dimensions. Let me know, if there are more questions.
