### ISSUE TITLE
Panel Render Missing Text

### ISSUE THREAD

**Issue by ArcticSnowman** [grafana/grafana#6035]
When I attempt the render a panel into PNG, the text in the panel is not included:

This is the PNG
![broward-db-performance](https://cloud.githubusercontent.com/assets/13837922/18489924/c6ad5142-79cd-11e6-8b91-3e9b95b5d0c3.png)

Of this (screen shot) panel
![9-13-2016 4-16-53 pm](https://cloud.githubusercontent.com/assets/13837922/18489942/d7301fe0-79cd-11e6-9a56-5a60aa2d5cdd.png)

Either this is a bug or I'm missing something from the installation.

**Comment by torkelo** [comment]
Try installing font packages, what OS / dist are you using?

**Comment by ArcticSnowman** [comment]
Centos7

**Comment by ArcticSnowman** [comment]
OK Installed urw-fonts package and that fixed it.    

Might want to add a note to the docker container to install a font package as it does not come in the base C7 repo.

**Comment by torkelo** [comment]
The official docker container has this installed already, and is using Debia.  The official cents install doc does mention font dependency, the rpm package also has a font package dependency :)
