### ISSUE TITLE
Dashboard rendering shows empty panels

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#6036]
* **I'm submitting a  Bug report** 

- What Grafana version are you using?
3.1.1

- What datasource are you using?
graphite

- What OS are you running grafana on?
Linux / Centos

- What did you do?
Call /render endpoint for a dashboard

- What was the expected result?
Get a png of the whole dashboard with all the panels rendered

- What happened instead?

Instead I got all panels empty with the loading wheel rolling

https://grafana.mysite.com/render/dashboard/db/my-dashboard renders empty panels:
(it used to work in the previous version, a bit slower fwiw but we got all panels rendered).
![image](https://cloud.githubusercontent.com/assets/728853/18490467/e2f559f2-7a0a-11e6-85dc-bb71832fe417.png)

**Comment by amuraru** [comment]
Relates to #5606

**Comment by amuraru** [comment]
Looking further at the code it seems that render.js checks that at least 1 panel in a dash is rendered. This is working for individual panel rendering but not for whole dashboard rendering.

**Comment by torkelo** [comment]
Whole dashboard rendering has never been supported, https://github.com/grafana/grafana/issues/2085
