### ISSUE TITLE
Dashboard refresh resets table panel pagination location

### ISSUE THREAD

**Issue by craftzneko** [grafana/grafana#60373]
As referenced in this bug from 2020 "Auto refresh in the dashboard resets the page to 1 #24462" table panels reset page location when the dashboard refreshes.

Using version 9.3.1 via edge 108.0.1462.46 (Official build) (64-bit)

**Comment by mellieA** [comment]
@pr1malc0de are you able to capture a screen recording of the issue? 

I tested this with the TestDataDB datasource and CSV Content input using this sample data: 

```
really,long, table
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,4
1,2,5
1,2,4
1,2,last
```

Then I set auto-refresh to 5sec and scrolled to the bottom of the table. It kept its position through the refreshes.

**Comment by mellieA** [comment]
![Screenshot 2022-12-16 at 6 57 55 PM](https://user-images.githubusercontent.com/18175287/208218087-c493d1a9-2065-4d2e-b4dd-52d42ad0fc3c.png)

I tested with the Edge and Chrome browsers

**Comment by pr1malc0de** [comment]
Hi @mellieA 

I cant screen capture the exact dashboard as the data is related to private individuals but for further info I have two SQL queries connected via an outer join transform, the panel is set to refresh every 30 seconds, which reset the pagination

**Comment by mellieA** [comment]
@craftzneko I was reviewing this and realized we have another issue with discussion. I'll close this in favor of https://github.com/grafana/grafana/issues/61259
