### ISSUE TITLE
Templating: AdHoc Key/Value Filters

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6038]
This is a new and very different type of template variable.

It will allow you to create new key/value filters on the fly. With autocomplete for both key and values. The filter condition will be automatically applied to all queries that use that data source. 

![adhoc_filters](https://cloud.githubusercontent.com/assets/10999/18716598/b8269984-801d-11e6-8ff5-a860f558acfc.gif)

When you define the ad hoc filter template variable you specify a data source. That data source is used to fetch keys and key values. In order to support this the frontend data source abstraction has to support 2 new functions
 
- getTagKeys(options)
- getTagValues(options)

The data source also needs to check for ad hoc filters and apply them to all queries. 

Currently only InfluxDB and Elasticsearch has basic support for these.

**Comment by bbinet** [comment]
Is it supposed to replace the current templating system completely?
I think this is also good to keep the current template system to be able to apply templating on a per panel basis.

**Comment by torkelo** [comment]
of course not, this is just a complement, very useful for log data or data where you have lots of dimensions / properties to filter by

**Comment by bbinet** [comment]
Ok thanks

**Comment by torkelo** [comment]
https://twitter.com/torkelo/status/781378688612958208

**Comment by jkrauska** [comment]
How do we track/follow when we may have this capability for tsdb?

**Comment by bergquist** [comment]
@jkrauska which tsdb? The datasources in core that doesnt support it is due to lack of support in the datasources.

**Comment by jkrauska** [comment]
@bergquist 
My datasource is opentsdb.

Metrilyx has this sort of adhoc hunting technique and it's the only reason we're keeping it around. (even though ticketmaster seems to have taken it off github)

Can you elaborate on 'lack of support'? It seems to moslty be a matter of searching available keys, and then available values for a known key. (both of which I can do in opentsdb).

Thanks.

**Comment by buom** [comment]
#7020

**Comment by rudasn** [comment]
hey @torkelo. I'm exploring grafana with influxdb and was wondering if it's possible to add an ad-hoc filter based on a field (as opposed to a tag). For example, I'd like to filter out measurements that are above (or below or within) a certain threshold.

I tried setting custom and constant variables but they are transformed into a regex in the WHERE clause making it impossible to do a numerical filter (<, >).

Btw Grafana is awesome. Thanks.

**Comment by anhlqn** [comment]
Is it possible to add the `OR` operator in addition to `AND`?
