### ISSUE TITLE
Bug: graph disappears after a certain zoom-level

### ISSUE THREAD

**Issue by fiksn** [grafana/grafana#6039]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 2.6.0 and 3.1.1.
- What datasource are you using? InfluxDB 0.9
- What OS are you running grafana on? Linux ("official" docker image inside kubernetes on coreos stable 1068.10.0)
- What did you do? When I zoom-in so that x axis has less than 1.5 hours (and my samples should be 1/s) the graph is sometimes drawn at first (I believe not at all on 2.6.0) but when dragging my mouse it instantly disappears. Mouse over still display data points however (on that red vertical line).
- What was the expected result? Graph shown.
- What happened instead? No graph is shown but I see certain points when hovering over.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query

api/datasources/proxy/2/query?epoch=ms&q=SELECT+mean(%22value%22)+FROM+%22stats.counters.xyz.rate%22+WHERE+time+%3E+1473802856s+and+time+%3C+1473805316s+GROUP+BY+time(1s)+fill(null)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

{"results":[{"series":[{"name":"stats.counters.xyz.rate","columns":["time","mean"],"values":[[1473802856000,null],[1473802857000,null],[1473802858000,null],[1473802859000,null],[1473802860000,0],[1473802861000,null]...

Could it be related to the fact that "null" values are returned? When zooming out I don't see null values. 

If this is not a duplicate (or wont-fix bug) I can also attach some screenshot to clarify the situation.

**Comment by fiksn** [comment]
I tried with fill(previous) and then it seems to work fine. But in case of "null" points I'd still expect a discontinuous line. Or does that not make sense?

**Comment by torkelo** [comment]
what is the null point mode? (in display options), it controls how null values are displayed (ignored, treated as zero, or as gaps) 

Make sure your group by time interval is not lower then the rate at which you write data, if it is it will insert null values between each data point. 

you can set a lower bound in group by interval below the queries or in data source settings, ex `>10s`

**Comment by ccoenen** [comment]
Has the group by interval setting been removed? I'm not seeing it. I'm experiencing the same problem. I don't want to display null values as connected, as sometimes the "gap" is important information, too.

![grafik](https://user-images.githubusercontent.com/124909/28586600-a6011df8-7174-11e7-9b89-cc88eb23e790.png)

**Comment by torkelo** [comment]
Graphite has no such option, Graphite always returns null values for missing values, you can change how null values are displayed in Display tab (option is called null value)

**Comment by ccoenen** [comment]
thanks for the explanation!

**Comment by shubhamod1** [comment]
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.
