### ISSUE TITLE
Alerting: Support per series state change tracking for queries that return multiple series

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6041]
Currently, we don't update the alert message if the alert query return new/other series then the first one. 

Let's say that one alert executes and have an eval match on "serie 1".
Next time the alert executes "serie 1" is fine but "serie 2" is alerting.  
This will go unnoticed in our current implementation. 

When an alert is triggered we should create a key based on the alerting series. The next time the same alert is triggered we can compare the state and the key created by the series.

If the data source support dimensions, we should include those when creating the key. 

One suggestions for how to implement such key creation:
ex
```
{ "serie 1", datapoints: ... },
{ "serie 2", datapoints: ... }
```
Should become `serie 1;serie 2`

```
{ "web-front-01", tags: {"server": "web-front-01", "application": "web"}, datapoints: ... },
{ "web-front-01", tags: {"server": "web-front-02", "application": "web"}, datapoints: ... }
```
Should become `web-front-01{server=web-front-01,application=web};web-front-02{server=web-front-02,application=web}`

Keys might seem long but I don't think it matters that much. Perhaps we could find a way of shortening them by just storing a hash of it or something like that.

**Comment by klausenbusk** [comment]
Just a +1 for this.

So our use-case for this feature, is that we have ~ 150 boxes at different locations and it could be really useful if we could setup a alert like "if memory usage 75%> of total".
With the current implementation that wouldn't work very well, as multiple boxes will only trigger 1 alert..

**Comment by pdf** [comment]
Implementation details will likely overlap with #6557 I believe.

**Comment by lgierth** [comment]
I realize this is a more suitable issue for my comment in https://github.com/grafana/grafana/issues/6685#issuecomment-272658737

I have another slightly different use case for this. I have multiple series in a graph: https://snapshot.raintank.io/dashboard/snapshot/V6cQW9mzHHfnDJHKgNKbyyCfzp4nZSBy

When the first reaches the alert level, everything goes smooth, but when the second reaches the alert level, it doesn't flip the alert state, and thus doesn't trigger anything. It'd be useful though :)

An idea how to go about this: a per-alert "notification id", which can use variables to distinguish between the desired alerts. In my graph above, I'd set the notification id to `{{host}}`.

**Comment by pdf** [comment]
@lgierth see also https://github.com/grafana/grafana/issues/6553#issuecomment-272602289 for how I'd like to see this sort of thing work.

**Comment by yannispanousis** [comment]
Would absolutely love this

**Comment by ddhirajkumar** [comment]
I was thinking that if we support https://github.com/ipfs/infrastructure/issues/217, we would automatically get the functionality of 'state change tracking of alert per series'

**Comment by bergquist** [comment]
Updated the description. Feedback on how to implement this would be appreciated.

**Comment by pdu** [comment]
I would like to share the way I got to work around this.

1. Manually create a dashboard to monitor one EC2 instance, I've created the separate panels in the dashboard to monitor CPU, memory, disk, network rx/tx/rx_error/tx_error, etc.
2. Then I export the dashboard as a JSON template file.
3. I write a cron script to automatically create/delete dashboards
3.1. get the EC2 list
3.2. get the dashboard list
3.3. call grafana API to add the missing dashboard based on the JSON template file
3.4. call grafana API to delete the dashboard if the EC2 instance got terminated

**Comment by gregorsini** [comment]
Hi pdu, do you have time to share some of your script or any generic script to add or delete a dashboard?  I've contemplated your approach, but would appreciate any head-start you're able to share.   

Best, Greg.

**Comment by shurshun** [comment]
+1

**Comment by whidrasl** [comment]
+1

**Comment by pdu** [comment]
@gregorsini sorry I just saw the message, please refer to https://github.com/pdu/grafana_ec2_monitoring

**Comment by ashuw018** [comment]
Hi, just checking if there are any chances of getting this feature in newer future, due to lack of template variable use in alerting , i have created separate dashboard for alerting only where i am not using any template variable but managing multiple series within single graph by tagging. So this feature will be very useful in my scenario. 


Thanks,

**Comment by bergquist** [comment]
If this was implemented we would have to improve the alert notifications as well. Sending one alert notification per state could potentially be very verbose. The same could be said for alert annotations/alert history. 

My current thinking is that we would have to implement https://github.com/grafana/grafana/issues/7330 first so it would be configurable how frequently anyone wants the evalMatches changes to be pushed.

**Comment by andyvig** [comment]
Any updates on if/when this might be targeted for release?  This is a pretty significant limitation for certain alerts.  Thanks in advance.

**Comment by bdeam** [comment]
+1

**Comment by agolomoodysaada** [comment]
A great use case for this is detecting every time a pod dies in Kubernetes. We don't want to create an alert for each pod. We want to get alerted for each individual pod from one panel. It scales better and it's the human thing to do.

**Comment by sushovan23** [comment]
This would also help in case when - two series are alerting.
one gets cleared. but right now that ok is not sent out only 1st series that is still alerting is send out as notification due to reminder feature in notification channel. So right now we are able to get subsequent alerts if another series starts alerting along with series 1. but we miss out on the OK/clear notifications for single series since OK is only sent out for entire panel right now.

**Comment by bergquist** [comment]
We should definitely update the state within Grafana. But I'm not sure about sending new notifications for each state change.

**Comment by agolomoodysaada** [comment]
@bergquist , thanks for your response. 

Why not add a boolean flag that user can toggle on the alert tab of a panel? Say we call it "Aggregate State"?
- [x] ON (default), Grafana does what it already does today and handles aggregate state change across series
- [ ] OFF, Grafana handles state change per-series and sends an alert for each series independent of each other

Would that be a reasonable solution here? The alternative is to create one panel + alert per series which doesn't scale at all for large deployments and clusters

**Comment by DanCech** [comment]
That seems like a reasonable idea to me.

**Comment by bergquist** [comment]
We are currently redesigning the alert system in Grafana and writing up a design doc about how we want to improve the alerting features in Grafana. Once the doc is in better shape, we will share it on github. In our current thinking it will be possible to route and and group alert notifications based on data from the alert rule and the series returned in the query. So the user will have much more flexibility on when to send or not send alert notifications.

**Comment by micw** [comment]
@bergquist Looking forward to read about the new alerting design. The current alerting is nice but far from being perfect.

For example the doc recommends to use alert reminders to workaround the limitation of this issue. Unfortunately this is set up per notification, not per alert. But different alert types require different notification intervals (e.g. unrachable prod app vs. an 80% full disk).

Another must-have for operations is silencing with timeout (and maybe also a comment). E.g. if an alert cannot be fixed instantly but work is in progress, no new notifications souhld be send meanwhile.

I'm aware that out there are other tools that do much more sophisticated alerting. But having everything in one place and configurable with the same intuitive GUI would be a great deal.

I hope you are doing the design discussion in public soon.

Best regards,
Michael.

**Comment by karimcitoh** [comment]
+1

**Comment by micw** [comment]
@bergquist Is there any progress in this?

Best regards,
Michael.

**Comment by manhojviknesh** [comment]
@bergquist : Kindly update on the status of this feature.
It would be extremely handy if we have alert triggers for every condition separately instead of alerting on single condition as a whole.

**Comment by fernandobeltranjsc** [comment]
I do not understand how this functionality is not available 3 years later, it is a problem not being able to have alarms for each series. If the CPU alarm goes off, it will no longer trigger while it is still active even if another computer has another CPU problem. It is not reasonable.

**Comment by mgiammarco** [comment]
I am another one that does not understand why you cannot have alarms for each series. 
In these years I have made 7 of mine customers to use Influx stack that has this feature. You have lost 7 potential customers. Worse when I have explained them that Grafana does not support this feature they replied me: "it is not a useful product" (the real sentence was far worse).

**Comment by mgiammarco** [comment]
And please stop considering workarounds like repeated notifications. There are already too many notifications we cannot add even more as a workaround of that feature.

**Comment by cqcn1991** [comment]
+ 1 for this

**Comment by erkexzcx** [comment]
+1

**Comment by lmondoux** [comment]
+1

**Comment by vbichov** [comment]
basically this feature will bring Prometheus (or cortex) alert engine functionality to grafana. 
I'm waiting for this feature for more than a year now.
Any chance this will be implemented?

**Comment by czd890** [comment]
+1

**Comment by papovyr** [comment]
Grafana Cortex alerting UI +1

**Comment by johntdyer** [comment]
we so need this

**Comment by janbrunrasmussen** [comment]
Any chance someone from Grafana could update on the state of this?

**Comment by wiardvanrij** [comment]
+1...

**Comment by bbl232** [comment]
bump! we also could really use this :)

**Comment by leoowu** [comment]
any further update ?

**Comment by knmorgan** [comment]
+1 from me too.

We are currently getting updates on alerts by using "Send reminders" in the notification channel settings, but this is obviously not ideal. This problem combined with #16662 really cripples alerts for us.

**Comment by rmccarthy-ellevation** [comment]
Is there going to be an update on this?

**Comment by uklance** [comment]
My use case for this is we have multiple applications running in Kubernetes and we calculate the replica utilisation for each application using a prometheus query. We get an alert if the replica utilisation is not 100% for more than 5 minutes (ie we get an alert if any application dies).

Currently, we only get a single alert when the first application dies and then get an OK alert when all applications are back up. But in between a second, third or fourth application might have died and we don't get an alert for these. Ideally we would like a fail/OK alert for each application/series.

**Comment by danielfariati** [comment]
Example use case:
Consider you have more than 1.000 different databases.
Consider you have an alert for RDS burst balance (Cloudwatch).
An alert is triggered because one of the databases have a low burst balance.
Even if you fix it right away, it can take a lot of time do the burst balance to go up again. 

Then, there are two possibilities, in the current grafana version, as far as I know:
1. With reminders off: You will not be notified if other databases have a low burst balance, as the alert will not be triggered again;
2. With reminders on: You will be notified several times, even if there are no new alerts, which can lead to information overload;

This funcionality to support per series state change would solve this in a nice way, at least for multiple use cases of mine.
We currently use another alerting solution for those cases, but this is also not ideal, as centralizing our graphs / alerts would be much better.

I can't think of any case where alerting per series would cause too many alerts.
If you created an alert is because you want to know if something happened.
If you are not insterested in knowing that, then it problably means that your alert is not useful or is not configured with the right parameters.
Also, if you grouped / created series for an alert is probably because the series matter.
Otherwise, you would create the alert without any sort of grouping.

We currently use another alerting solution for this use cases, as grafana can't handle them in a scalable way (creating one graph per series is not scalable is several cases).
But I would love to see this functionality in grafana, so we could centralize our alerts.

**Comment by danielfariati** [comment]
@bergquist Can you update us on this topic? You said that you guys were working on redesigning the alert system in and writing up a design doc, but I didn't see any follow up on that. Did that doc include this in some way?

**Comment by Artheriom** [comment]
Bumping into this. This feature would be useful to connect Grafana alerting with other supervision tools, and keep users updated about what's **really** going on on their infrastructure. 

I'm pretty sure this is not a complicated thing to do, because the "Test button" already does the job : even if the alert is already in alerting, it will display actualized information.

/api/alerts : 

```json
    {
        "id": 13,
        "dashboardId": 17,
        "dashboardUid": "___",
        "dashboardSlug": "supervision",
        "panelId": 38,
        "name": "my_alert",
        "state": "alerting",
        "newStateDate": "2021-02-04T08:55:03Z",
        "evalDate": "0001-01-01T00:00:00Z",
        "evalData": {
            "evalMatches": [
                {
                    "metric": "controller-2",
                    "tags": {
                        "__name__": "up",
                        "address_ori": "controller-2:7",
                        "instance": "controller-2",
                        "job": "node-exporter",
                        "type": "controller"
                    },
                    "value": 0
                }
            ]
        },
        "executionError": "",
        "url": "/d/____/supervision"
    },
```

"Test button" result : 
```json
{
  "firing": true,
  "state": "pending",
  "conditionEvals": "true = true",
  "timeMs": "7.959ms",
  "matches": [
    {
      "metric": "controller-0",
      "value": 0
    },
    {
      "metric": "controller-1",
      "value": 0
    },
    {
      "metric": "controller-2",
      "value": 0
    }
  ]
```

One (awful) workaround is to use /api/alerts/:id/pause to suspend and reactivate alert, so evalMatches is updated...

If you don't want to add this as a "base functionality", is this possible to have a /api/alerts/:id/recalculate endpoint, which will update evalMatches when asked ?

**Comment by kylebrandt** [comment]
The new beta version of alerting in Grafana 8 ([opt-in with "ngalert" feature toggle]( https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/)) supports "multi-dimensional" alerting based on labels and often in combination with Server Side Expressions. So one can have multiple alert instances from a single rule.

For example:

![image](https://user-images.githubusercontent.com/1692624/121185286-e5400f00-c833-11eb-892b-8892d462de82.png)

Would create alert (instances) per device,instance,job:

![image](https://user-images.githubusercontent.com/1692624/121185389-00ab1a00-c834-11eb-8be3-a032bd6b955e.png)

The exception is the "classic condition" operation within SSE, which is not per series and behaves like the pre-8 dashboard alerting conditions.

Demos etc regarding the new alerting V8 will be in the Grafacon session (online streaming) on June 16, 2021: https://grafana.com/go/grafanaconline/2021/alerting/

**Comment by pere3** [comment]
I don't really understand how is completely new feature (which is currently in alpha and not really doing the same alerting mechanism that we all used to (it separates alerts from graphs after creating)) closes issue from where it starts

It also strange how this feature closes issue https://github.com/grafana/grafana/issues/11849, where alerts api not being updated after "alerting" state.
