### ISSUE TITLE
Loki: Reduce the impact of brute force querying

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#60449]
### Summary

Improve response time for users running repetitive queries within the same time frame, preventing, if possible, the re-execution of a slow query. 

### Problem statement

For certain environments with many concurrent users running the same query Logs query in the same time frame, when this query involves a significant amount of data, it takes a lot of time to process and the user experience is degraded. The overall idea is to reduce the number of queries made and data read to achieve a better performance perception. 

### Scope
Research and implementation

### Measurement

TBD

### Resources

Design doc: https://docs.google.com/document/d/1kTIxR_Xq3oo7Tb3l1e1QlfmkTu23G1-SOe3vYpmB9M4/edit#

**Comment by matyax** [comment]
We will not implement range snapping. Closing as there is nothing else to do here at this point.
