### ISSUE TITLE
[Alerting] Newlines removed in email alerts template with Outlook client

### ISSUE THREAD

**Issue by SergioBernabe96** [grafana/grafana#60458]
Newlines are removed in the alerting email using an Outlook client to send those emails. I have seen a few discussions with people having this same issue which was supossed to be fixed.

We are using the following template:

```
{{ range $index, $element := $values }}
       -{{ index $element.Labels "pvcs" }}: {{ humanizePercentage $element.Value}}
{{end}}
```

We cannot use the `pre` class instead of `pre-line` as suggested [here](https://github.com/grafana/grafana/issues/53879) because we are running Grafana in K8s.

- Grafana version: 9.3.1

**Comment by mellieA** [comment]
@SergioBernabe96 it looks like this should be fixed with https://github.com/grafana/grafana/pull/57751 planned for 9.4
