### ISSUE TITLE
Azure: Custom app insights metrics not available in grafana

### ISSUE THREAD

**Issue by mpostument** [grafana/grafana#60450]
**What happened**:
Custom metrics which is available in azure not available in grafana
<img width="1429" alt="Screenshot 2022-12-16 at 13 56 35" src="https://user-images.githubusercontent.com/9252594/208093279-8b8947ba-6c98-4911-95e6-f315b896d53e.png">

But when i open grafana i don't see this metrics
<img width="1141" alt="Screenshot 2022-12-16 at 13 52 13" src="https://user-images.githubusercontent.com/9252594/208092506-0ee98e9f-b29a-4de0-bf5d-c1035d61aa55.png">

If i am trying to manually type them i am getting error `request failed, status: 400 Bad Request`

But i see my metrics as namespace, but i don't see any available dimension to filter those metrics
<img width="886" alt="Screenshot 2022-12-16 at 13 55 05" src="https://user-images.githubusercontent.com/9252594/208093108-570ed4a3-fc29-4ba4-b4cd-e7cbeec4e510.png">

**What you expected to happen**:
To be able visualize custom metrics

**How to reproduce it (as minimally and precisely as possible)**:
Write custom metrics with dimensions to azure. And then visualize them in grafana

**Anything else we need to know?**:

**Environment**: Docker
- Grafana version: 9.3.2
- Data source type & version: Azure
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
There's a fix for something similar in https://github.com/grafana/grafana/pull/54937 but it says this user has 9.3.2

**Comment by andresmgot** [comment]
@mpostument to see your custom metric, you first need to select the custom namespace (as you have done in the second screenshot) so that's working as expected.

For the dimensions issue, which values are you expecting there? Those filters are parsed from the time series metadata returned by the Azure API. If your metric does not return any metadata, that selector will be empty. Are you able to see dimensions in the Azure portal?

**Comment by mpostument** [comment]
@andresmgot on first screenshot i am doing split by service dimension. Besides there a few more, such as node and etc. But on azure i am selecting namespace as Log Based Metrics and then selecting metric. But in grafana i am selecting custom namespace and then there is no custom dimenstions

**Comment by aangelisc** [comment]
Thank you for the additional information @mpostument, I'll investigate this further 😊

**Comment by aangelisc** [comment]
Hi @mpostument, could you instead try the `Azure.ApplicationInsights` namespace and let me know what that displays please?  In the Azure portal does your custom metric show up under the `Custom` separator in the metric name dropdown?

**Comment by mpostument** [comment]
Here is grafana
<img width="1646" alt="Screenshot 2022-12-22 at 11 53 46" src="https://user-images.githubusercontent.com/9252594/209107884-96998b4c-c614-404c-ab23-9338158e0dc9.png">

Yes under the custom. I see there metrics which i saw under `Azure.ApplicationInsights` in grafana + my custom metrics

![Uploading Screenshot 2022-12-22 at 11.57.51.png…]()

**Comment by aangelisc** [comment]
Thanks @mpostument. If you were to choose the `avmon-pings` metric using the `Azure.ApplicationInsights` namespace do the dimensions correctly display?

**Comment by mpostument** [comment]
@aangelisc there is no avmon-pings metric in grafana. If i type it manually i don't see any dimensions. Also time grain show not found
<img width="1632" alt="Screenshot 2022-12-23 at 13 14 50" src="https://user-images.githubusercontent.com/9252594/209326759-f81c75e5-5a48-445c-8654-61f063f4a277.png">

**Comment by aangelisc** [comment]
Thanks @mpostument, can you tell me how you're generating your custom metric (`avmon-pings`)? Do any of the other custom metrics work as they should?

**Comment by mpostument** [comment]
I am doing similar as it described in this doc with opencensus sdk. https://learn.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#count-aggregation-example

Custom dimensions added as described here https://learn.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#set-custom-dimensions-in-metrics

I writing few more metrics, and none of them is work in grafana

**Comment by aangelisc** [comment]
Thank you for the update @mpostument, I will have another look at this next week.

**Comment by aangelisc** [comment]
Just to keep you updated @mpostument, I have managed to replicate this issue. I can see that when the `metricDefinitions` request is run the `dimensions` returned is empty and does not include any custom dimensions. I'll look into a fix for this.

**Comment by aangelisc** [comment]
As far as I can see the Azure Portal does not support dimensions in custom namespaces but it does support them for `Log-based metrics`. I will be querying this further with Azure 😊

**Comment by mpostument** [comment]
Hello @aangelisc. Any updates regard this issue?

**Comment by mpostument** [comment]
@aangelisc i created discussion, but i not able to add labels 
https://github.com/grafana/grafana/discussions/62288

**Comment by aangelisc** [comment]
Thank you @mpostument! I've added the labels and this will be reviewed 😊

**Comment by aangelisc** [comment]
Closing as the discussion has been opened 😊

**Comment by omri08** [comment]
Hey @aangelisc, is there any update on this? I was able to find the relevant discussion
