### ISSUE TITLE
Wrong time for instant queries since v9.3.0 (Prometheus datasource)

### ISSUE THREAD

**Issue by mxsiegle** [grafana/grafana#60467]
**What happened**:
Instant queries to Prometheus are using the wrong timestamp resulting in incorrect data, depending on the value of the timepicker 
e.g. 'last 6 hours' or 'last 90 days' should produce the same timestamp for the query but they don't (see screenshots)

This issue seems to have been introduced in Grafana v9.3.0 as it is not present in v9.2.7.
The screenshots were taken at exactly the same time.

![image](https://user-images.githubusercontent.com/81744122/208114482-3b738ee6-8018-45d5-9296-599e1520694c.png)

![image](https://user-images.githubusercontent.com/81744122/208114526-aa36b9d7-cacd-444f-a021-86d8eebadc67.png)

Previous versions use the current timestamp down to the second:

![image](https://user-images.githubusercontent.com/81744122/208114609-9b5c25f9-2b97-4e32-ba9b-d3b1210b82d5.png)

**What you expected to happen**:
The current & correct timestamp should be used independent of the timepicker selection

**Environment**:
- Grafana version: v9.3.x
- Data source type & version: Prometheus

**Comment by mellieA** [comment]
I confirmed that I see something like this in 9.3.2 on play.grafana.org with the prometheus datasource there

**Comment by itsmylife** [comment]
https://github.com/grafana/grafana/pull/60815 will fix the issue. It will be in the next release of `v9.2.x`
