### ISSUE TITLE
singlestat decimal value

### ISSUE THREAD

**Issue by paracetamol32** [grafana/grafana#6046]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1 
- What datasource are you using?
elasticsearch
- What OS are you running grafana on?
windows 10
- What did you do?
add a singlestat with a decimal value
- What was the expected result?
current decimal value
- What happened instead?
int value

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
data source are the same, and result are different : 15.4 on a graph and 15 on singlestat
i have missed something ??
![graphana](https://cloud.githubusercontent.com/assets/14573835/18543521/9651fae8-7b30-11e6-8ad4-29624202f438.JPG)

**Comment by torkelo** [comment]
can you show your singlestat options tab? 

![image](https://cloud.githubusercontent.com/assets/10999/18545499/b8776276-7b39-11e6-9ee2-7592b24ae599.png)

See the decimal option? It allows you to override the automatic decimal handling.

**Comment by paracetamol32** [comment]
![graphana2](https://cloud.githubusercontent.com/assets/14573835/18560964/257bb248-7b7e-11e6-875e-38257e04897f.JPG)
If i set decimal to 1 or 2  nothing change. And when i go out and the come back to configuration the parameter is set to auto...

**Comment by torkelo** [comment]
very strange, I can set it to 1 and 2 it works as expected, the parameter is saved like the others (if I save the dashboard). 

What browser are you using?

**Comment by PiR43** [comment]
I have also some time this decimal problem. But only if I change the value with more or less buttons. If I put the decimal number with keyboard before save all works well.
