### ISSUE TITLE
Grafana panics during start after update from 9.3.1 to 9.3.2 on raspberry Pi

### ISSUE THREAD

**Issue by zardoz99** [grafana/grafana#60463]
**What happened**:
Grafana fails to start after update from 9.3.1 to 9.3.2. 
Dec 15 22:50:34 rpi-3bplus.home.lan systemd[1]: Started Grafana instance.
Dec 15 22:50:36 rpi-3bplus.home.lan grafana-server[7157]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 15 22:50:36 rpi-3bplus.home.lan grafana-server[7157]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28db49c]
Dec 15 22:50:36 rpi-3bplus.home.lan grafana-server[7157]: goroutine 1 [running]:
Dec 15 22:50:36 rpi-3bplus.home.lan grafana-server[7157]: github.com/grafana/grafana/pkg/extensions/config/vault.init()
Dec 15 22:50:36 rpi-3bplus.home.lan grafana-server[7157]:         /drone/src/pkg/extensions/config/vault/instrumentation.go:21 +0x15c
Dec 15 22:50:36 rpi-3bplus.home.lan systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 15 22:50:36 rpi-3bplus.home.lan systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Dec 15 22:50:36 rpi-3bplus.home.lan systemd[1]: grafana-server.service: Consumed 1.516s CPU time.
Dec 15 22:50:36 rpi-3bplus.home.lan systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 8.

**What you expected to happen**:
Grafana to start normally. 

**How to reproduce it (as minimally and precisely as possible)**:
Just do an "apt upgrade" 

**Anything else we need to know?**:
If the package is downgraded back to version 9.3.1 it works as expected. 

**Environment**:
Raspberry Pi 3B+ running the latest official version of "Raspbian(bullseye)" 
"uname -a"
Linux rpi-3bplus.home.lan 5.15.76-v7+ #1597 SMP Fri Nov 4 12:13:17 GMT 2022 armv7l GNU/Linux

- Grafana version:
root@rpi-3bplus:~# dpkg -l grafana-enterprise
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version      Architecture Description
+++-==================-============-============-=================================
ii  grafana-enterprise 9.3.2        armhf        Grafana

- Data source type & version:
One single data set from Influxdb. 

- OS Grafana is installed on:
Raspberry Pi OS "bullseye" 

- User OS & Browser:
Not applicable. 

- Grafana plugins:
None

- Others:

**Comment by karelkryda** [comment]
Same issue on Raspberry Pi 4 running as Docker container

**Comment by jokri** [comment]
Same issue on raspberry pi 3B+ running:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

Kernel version:
Linux rpimeter 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

The same error occurs when upgrading using apt and when 'installing' in separate folder using wget + tar.

See: [https://community.grafana.com/t/grafana-enterprise-9-3-2-crashes-on-raspberry-pi/78252/12](https://community.grafana.com/t/grafana-enterprise-9-3-2-crashes-on-raspberry-pi/78252/12)

**Comment by 42bits** [comment]
use docker  image: grafana/grafana:main-ubuntu have same issue .
some dashboard  return panic :runtime error: invalid memory address or nil pointer dereference

**Comment by zardoz99** [comment]
Uninstalling "grafana-enterprise" and installing "grafana" instead has resolved the issue for me.

**Comment by karelkryda** [comment]
> Uninstalling "grafana-enterprise" and installing "grafana" instead has resolved the issue for me. 

Of course, this is not a solution, but at least we already know that this problem is only associated with the enterprise version.

**Comment by tleopold** [comment]
Not a RelEng issue.  transferring to backend triage

**Comment by sakjur** [comment]
👋 Is everyone experiencing this running a 32-bit OS for their Raspberry Pi? `uname -m` being `armv7l` (or at least not `aarch64`)

I'm asking because I tried reproducing this on my Grafana playground running a 64-bit Raspbian using `grafana/grafana-enterprise:9.3.2`, and was unsuccessful in doing so. In case anyone runs into this problem on aarch64 that would be really helpful to know, otherwise I'll investigate this under the assumption that this has something to do with the 32-bit ARM version of Grafana.

**Comment by jokri** [comment]
> 👋 Is everyone experiencing this running a 32-bit OS for their Raspberry Pi? `uname -m` being `armv7l` (or at least not `aarch64`)
> 
`uname -m` returns `armv7l`.

**Comment by sakjur** [comment]
A little bit of an update, I've built Grafana Enterprise v9.3.2 on a RPi 4 running 32-bit Raspbian, and that starts just fine.
I'm not going to be able to do that today, but I'd like to create another build using the same toolchain we're using for production build to see if it's reproducible.
I'd also like to take a look at the logs for the original build to see if there's any indication that the particular build had some problem.

**Comment by dkossman** [comment]
confirmed the problem reproduces with the  9.3.2 ARMv6 32-bit build on a Raspberry Pi Zero W.  9.3.1 works fine.

**Comment by sakjur** [comment]
I have looked into logs and the toolchain, and a later development build of Grafana Enterprise built just a couple of commits after 9.3.2, without any modifications to anything that I'd ever suspect would fix this problem, works just fine. I believe something somewhere (though I don't find support for it in the build logs ☹️) broke the ARM 32-bit cross-compile for this particular build — I don't think this is a code problem. I'm not any wiser as to what that something is.
The release build of Grafana Enterprise 9.3.2 for ARMv7 both built for musl and glibc fails on the line in the instrumentation file mentioned above, and for ARMv6 it also segfaults, though more spectactularly and later in the startup process.

**Comment by chrisweeksnz** [comment]
I have experienced this with arm64 (64 bit on rpi4).

```bash
# uname -m
aarch64
```

**Comment by Kratax** [comment]
I have the same problem. On rpi with 32bit system and kernel no issue. On the second one where there is aarch64 kernel (but 32bit system) ends with panic. No issue after rollback to 9.3.1.
Linux raspberrypi 5.15.89-v8+ #1620 SMP PREEMPT Wed Jan 18 12:26:08 GMT 2023 aarch64 GNU/Linux

**Comment by chrisweeksnz** [comment]
> I have experienced this with arm64 (64 bit on rpi4).
> 
> ```shell
> # uname -m
> aarch64
> ```
> 
> I have this deployed using docker (`grafana/grafana:main`)

For the segfault I am seeing, it appears to be concerned with AlertManager configuration. A temporary workaround with loss of functionality (to restore graphing service) has been to drop the alert_configuration table in the sqlite database. This causes Grafana AlertManager to not work, but at least restores the ability to start the service. 

Simply recreating the table  in sqlite whilst the application is running and navigating to the Alerts -> Admin page will cause the process to segfault and not be able to start again until the table is dropped again.

**Comment by Kratax** [comment]
@sakjur Yes, on 9.3.2. It was always working fine, also 9.3.1 is running fine, just saying that I have two RPIs and the key difference is 64bit kernel. The one with 32bit was running 9.3.2 fine, the second not... Thanks for your work on this!

**Comment by chrisweeksnz** [comment]
> 9.3.4 was recently released and it seems to start for me on both my 64-bit and 32-bit RPiv4.
> 
> @chrisweeksnz Could you extract the image ID for your `grafana/grafana:main`, I tried it yesterday and wasn't able to reproduce your problems at that time. It's likely I got another version than you did since that's a tag for a nightly build.
> 
> @Kratax With what image? 9.3.2? I _guess_ that the kernel itself shouldn't matter, since if you're running a 32-bit user userland, it'll probably run the 32-bit version of Grafana as well, which is what's triggering this problem. I'm working from the wrong place today to be able to set up a new Pi, but I could set up another to run Raspian with 64-bit kernel and 32-bit libs later 👍

# docker image inspect grafana/grafana:main
[
    {
        "Id": "sha256:7d8d695886114756e336e5c1b2e2d6c53e5082c74ad30701a52fc48ffdb417f6",
        "RepoTags": [
            "grafana/grafana:main"
        ],
        "RepoDigests": [
            "grafana/grafana@sha256:00c85701a5c24db23340809fd42358e1c96ea81d72b025f933a28e117d133460"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-01-24T01:56:21.988143463Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "472",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GF_PATHS_CONFIG=/etc/grafana/grafana.ini",
                "GF_PATHS_DATA=/var/lib/grafana",
                "GF_PATHS_HOME=/usr/share/grafana",
                "GF_PATHS_LOGS=/var/log/grafana",
                "GF_PATHS_PLUGINS=/var/lib/grafana/plugins",
                "GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/usr/share/grafana",
            "Entrypoint": [
                "/run.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Grafana Labs <hello@grafana.com>"
            }
        },
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
        "Size": 309017372,
        "VirtualSize": 309017372,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6110eaded695f1b88a4de59c04e64254bcd2bd51a04d7b9262803d782ab2de32/diff:/var/lib/docker/overlay2/9d8468ad8f7b8c93cd26fcaebfd669c699571d26342e331f82fa8de2d0edad37/diff:/var/lib/docker/overlay2/f59ac875e3f8415e5c0fefe2f495b1d253e50da86e726aecb9906551512dc4ec/diff:/var/lib/docker/overlay2/633222d68566c6b3f0db13ceba2f68a168ce48ccec8bddd0583d648c6e560d08/diff:/var/lib/docker/overlay2/1d154a351476b63f17a038a077b1c34ec8abe4b4d2492454a2bb1dfe66543166/diff:/var/lib/docker/overlay2/db3aead6a14998e5fa9fde5d387cdcf4c0e389d735e5dddbb03d02c3ce548e95/diff:/var/lib/docker/overlay2/35e2914bea18fd35474568be1f315a012019fe419b2c82b4cd0d5072ef2aa183/diff:/var/lib/docker/overlay2/0df0d96fc2735c3741b33c8b430c073de5f8f573332f79c7294007252ae5b551/diff",
                "MergedDir": "/var/lib/docker/overlay2/b908c272fc2eac61a5899d22d85d2abed39d5f736631af6f47f0dbe48f014285/merged",
                "UpperDir": "/var/lib/docker/overlay2/b908c272fc2eac61a5899d22d85d2abed39d5f736631af6f47f0dbe48f014285/diff",
                "WorkDir": "/var/lib/docker/overlay2/b908c272fc2eac61a5899d22d85d2abed39d5f736631af6f47f0dbe48f014285/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:9833f26c6bda49289ac8a34a3aa95591ec19bd573686c3c0b4e07e5e463edfa2",
                "sha256:dc141ae19659447b866e4b03d033d50f0c66f9aabe93a57683b23ab76f111f5e",
                "sha256:df225a8bf6529e821cf8cca2a724f250daa394248c8a1c65d8dbd382838e465e",
                "sha256:8afde508f6590aa2dac5b338ef6a070c700130b86e58cbb47aafb0cae4a7f043",
                "sha256:02660f3cb767c7a20935ac7d2fb734502aebaf8f321525894ec2fd9d2ba899c7",
                "sha256:f3328d851b279795a044a6e5e6a7a7c322f8e3aad54527beb04504928b9d53d7",
                "sha256:0e046a9fe58e00b4fdfd1e51f1b769b3f6373a7b4ea2ef036558725414448c57",
                "sha256:e4e486ab30a67f716ca59d928a22820cbc6910c49c53b0c368b2828a9f0b8a78",
                "sha256:53528c638db4d7bb123387364502ef96d6866bb60cddcaf4438cccd3bb778fde"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by karelkryda** [comment]
> 9.3.4 was recently released and it seems to start for me on both my 64-bit and 32-bit RPiv4.

Can confirm, that version **9.3.4** works just fine 👍🏻

**Comment by Kratax** [comment]
I confirm the same, i.e. 9.3.4 works well on both RPis….

**Comment by zardoz99** [comment]
Assuming 9.3.4 resolves the issue, I am happy for the case to be closed.
