### ISSUE TITLE
Get raw values in webhook payload

### ISSUE THREAD

**Issue by mathieu-pousse** [grafana/grafana#60465]
**What happened**:

I try to write a proxy that would receive the webhook for Grafana Alerting to push it, somehow, in another API.
I then need to gather all the data I have to properly generate a message.

```
{
    ...
    "alerts": [
        {
            ...
            "panelURL": "https://grafana....",
            "valueString": "[ var='B0' metric='xxx' labels={env=xxx} value=0.016666666666666666 ], [ var='B1' metric='yyy' labels={env=yyy} value=0.13333333333333333 ],... ]"
        }
    ],
```

Everything is fine apart from the fact that the most interesting information regarding the alert is encoded in a field named `valueString`.

I did not find where this is done in the code, but the format of the string is no really convenient.
Note: in this struct, there is a value field that seems to hold interesting information
https://github.com/grafana/grafana/blob/6637333748b49c55fe267d79dab98c0970cbd1af/pkg/services/ngalert/notifier/channels/template_data.go

**What you expected to happen**:

Would it be possible to have an additional attribute named "value" or whatever with a Json representation that would be much easier to manipulate.

**How to reproduce it (as minimally and precisely as possible)**:

Trigger an alert on a webhook and check the payload

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2
- Data source type & version: prometheus / loki
- OS Grafana is installed on: debian
- User OS & Browser: na
- Grafana plugins: none
- Others:

**Comment by mellieA** [comment]
@mathieu-pousse a new PR was just merged that allows using template variables in the webhook contact point title and description: 

https://github.com/grafana/grafana/pull/58058

These docs describe how template variables work. The `ValueString` you mentioned comes from the `values` map in the go template. 

https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#templating-labels-and-annotations
