### ISSUE TITLE
Finish migration of alerting code from simplejson to go/json

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#60486]
**What happened**:
PR started migration https://github.com/grafana/grafana/pull/60423 but there are many places in the code where we rely on simplejson features like mutation, read by key etc. Mostly in provisioning code. The PR added conversions from json.RawMessage to simplejson but this probably has some performance implications. 

Related to: https://github.com/grafana/grafana/blob/main/contribute/backend/style-guide.md

**Comment by deepto98** [comment]
Hi, can I work on this?

**Comment by yuri-tceretian** [comment]
@deepto98 sure! I will be happy to review it. Please go ahead and create a PR

**Comment by parulc7** [comment]
Hi @yuri-tceretian, If nobody is currently working on this, I would love to take this up as my first contribution to grafana.

BTW, The style guide that you pointed to in the first comment doesn't exist anymore. Can you please let me know if there is a style guide to be followed?

**Comment by yuri-tceretian** [comment]
@parulc7, great! I have fixed the broken link.
