### ISSUE TITLE
Panel time info element disappears when using custom range in time picker

### ISSUE THREAD

**Issue by davide1995** [grafana/grafana#60498]
**What happened**:
By using a custom range, the time defined in the "relative time" is lost
![wrong](https://user-images.githubusercontent.com/21131407/208315712-27b6c6af-5b74-407c-b875-777875bef7b3.png)

**What you expected to happen**:
Changing the range to a right date in the time picker should not affect the fixed range in the panel defined via the "relative time".
![right](https://user-images.githubusercontent.com/21131407/208315796-30feaf95-f621-4bc9-b1c2-5870bce3b243.png)

**How to reproduce it (as minimally and precisely as possible)**:
- Define a query with a where $timeFilter
- In "relative time" use e.g. now/d (Current Day)
- If you change the timepicker with "Last 5 Minutes", "Last 1 hour", "Last 12 hours", the value in the panel is not affected (it's right)
- Now change to a custom range with a starting date and an ending one. The value in the panel is changed (it's wrong)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Raspbian
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
Thanks for creating this issue, @davide1995 

I am forwarding the issue to the User Essential's team

**Comment by ashharrison90** [comment]
hi @davide1995 👋 

this is expected behaviour, see the note [here](https://grafana.com/docs/grafana/v8.5/dashboards/time-range-controls/#panel-time-overrides-and-timeshift)

hope that makes sense! 🙌

**Comment by davide1995** [comment]
Oh OK, I read in the doc but it doesn't hide the fact that it puzzles a user also because this behaviour is not at all intuitive. Anyway, thanks for your answer
