### ISSUE TITLE
Debian installation guide mentions unsupported parameters in update-rc.d invocation

### ISSUE THREAD

**Issue by edigaryev** [grafana/grafana#6052]
The [init.d service part](https://github.com/grafana/grafana/blob/master/docs/sources/installation/debian.md#start-the-server-initd-service) of the Debian installation guide suggest the user to run this command:

```
$ sudo update-rc.d grafana-server defaults 95 10
```

These two numeric parameters at the end are unsupported according to update-rc.d(8) manpage and update-rc.d source code:

```
$ cat /etc/issue
Debian GNU/Linux 8 \n \l

$ grep -A2 discarded /usr/sbin/update-rc.d
        # All start/stop/defaults arguments are discarded so emit a
        # message if arguments have been given and are in conflict
        # with Default-Start/Default-Stop values of LSB comment.
```

**Comment by torkelo** [comment]
fixed
