### ISSUE TITLE
X-Axis Erroneously Rescaling to Dashboard Time Range

### ISSUE THREAD

**Issue by 13ascott** [grafana/grafana#60540]
When I go to create an XY Chart (and occasionally other charts as well), the X-axis does not scale to the data provided. I believe it is scaling to the dashboard time range. See below:

![image](https://user-images.githubusercontent.com/25653158/208492602-872cf51d-f272-4daa-8e2d-3b7e1162b97c.png)

If I select a new dashboard time range, the X-axis becomes correct. See below:

![image](https://user-images.githubusercontent.com/25653158/208492684-7f35d03d-1439-436a-bf8e-c778f374f7bc.png)

I can apply and save the changes and it will look correct on the dashboard. But, if I leave the dashboard and return, it goes back to the erroneous x scaling. It will occasionally flash to the correct scaling, but revert back to the erroneous scaling.

I am running a self-hosted free version v9.2.4 on Ubuntu and accessing it with a Chrome browser v108.0.5359.125 on Windows 10.

EDIT: I've updated to v9.3.2 and the problem persists.

**Comment by mellieA** [comment]
@13ascott the bar chart has this, are you looking for something similar for xy chart? 

![Screenshot 2022-12-19 at 2 25 18 PM](https://user-images.githubusercontent.com/18175287/208527120-256a6ec2-b3b1-4db0-be93-7e8e3a16139f.png)

**Comment by leeoniya** [comment]
what's odd is that in the first image the x axis looks like timestamps but in the second one it's numeric.

can you attach a debug snapshot of this panel in each scenario (it will have the raw response data embedded in it so we can investigate further)

https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

![image](https://user-images.githubusercontent.com/43234/200391751-ca1c338a-460b-46de-b881-87ea81e55f5d.png)

**Comment by tomashedlund** [comment]
I have a similar issue with the XY chart, it occurs when I try to define the standard max and min of the x-axis:
![image](https://user-images.githubusercontent.com/8181737/226144287-b8308c31-8868-456d-a44f-f1b56bdc2c07.png)

**Comment by leeoniya** [comment]
should be fixed by https://github.com/grafana/grafana/pull/70412
