### ISSUE TITLE
AsyncSelect doesn't update the value after selecting an option

### ISSUE THREAD

**Issue by mtoso** [grafana/grafana#60547]
**What happened**:
I am trying to build a query form using an AsyncSelect component. I can successfully have the options get loaded asynchronously but once I select an option from the drop down the value doesn't get set. 
**What you expected to happen**:
I would expect the value to be set after a selection
**How to reproduce it (as minimally and precisely as possible)**:
```
export class QueryEditor extends PureComponent<Props, State> {

  constructor(props: Props) {
    super(props);

    // Set the default value for the dropdown
    this.state = {
      selectedOption: '',
    };
  }

   // Load the options for the dropdown asynchronously
  loadAsyncOptions = async () => {
    console.log("loadAsyncOptions")
    try {
      // Make the API call to fetch the options
      const response = await fetch("http://localhost:7001/api/tdd/");
      const data = await response.json();
      const options: any = [];
      Object.keys(data).forEach(site => {
        options.push({ value: site, label: site });
      });
      return options;
    } catch (error) {
      console.error(error);
      return [];
    }
  };

  // Handle changes to the selected option
  onOptionChange = (option: any) => {
    const { onChange, query } = this.props;
    this.setState({ selectedOption: option.value });
    onChange({ ...query, site: option.value });
  };

 render() {
    const { sessionId } = this.props.query;
    const { selectedOption } = this.state;
    return (
      <div className="gf-form">
        <AsyncSelect
          value={selectedOption}
          loadOptions={this.loadAsyncOptions}
          defaultOptions
          onChange={this.onOptionChange}
        />
      </div>
    );
  }
}
```
`
**Anything else we need to know?**:
I tried the the UI here and is it working: https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--basic-select-async but I am not sure how it is different from my code. 
**Environment**:
- Grafana version: latest
- OS Grafana is installed on: Docker
- User OS & Browser: OSX - Chrome
- Others:
  "@grafana/data": "9.3.2",
   "@grafana/runtime": "9.3.2",
   "@grafana/ui": "9.3.2",
   "react": "17.0.2",
   "react-dom": "17.0.2"

**Comment by usmangt** [comment]
Hi @mtoso,

Thanks for opening this issue.

I don't have info in this area, therefore I will forward it to our team so that they can have a look.

**Comment by ashharrison90** [comment]
hi @mtoso 👋 

instead of storing just the value in state, you want to store the entire selectable object. e.g. your example should become:
```typescript
  // Handle changes to the selected option
  onOptionChange = (option: any) => {
    const { onChange, query } = this.props;
    this.setState({ selectedOption: option });
    onChange({ ...query, site: option.value });
  };
```

note the `setState` is setting the entire option, instead of just option.value. 

hope that helps! 😄

**Comment by MiddleMan5** [comment]
Then the type annotations are incorrect
![image](https://user-images.githubusercontent.com/12738069/209716824-4d242ff3-24c9-426b-ae7b-80a714fedbee.png)

`value` is clearly annotated as taking the underlying value type or the SelectableValue object. Accepting both would better align with the behavior of the `Select` component.

I see this as a bug where the expected behavior should be to use the value, if it is a string or number type, to find the option object the last result loadOptions

**Comment by cap10morgan** [comment]
I agree with @MiddleMan5 this is unintuitive and inconsistent. Could this be reopened and fixed?
