### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 42bits** [grafana/grafana#60551]
**What happened**:
use grafana-plugin-sdk-go ，in dashboard some panel return panic： runtime error: invalid memory address or nil pointer dereference
and have a error message：logger=context userId=1 orgId=1 uname=admin t=2022-12-20T14:24:52.0443557+08:00 level=error msg="Internal server error" error="[plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=172.17.0.1 traceID=

**What you expected to happen**:

 work fine

**How to reproduce it (as minimally and precisely as possible)**:
no

**Anything else we need to know?**:
no

**Environment**: 

- Grafana version: 9.3.1

- Data source type & version:

The company's self-developed data source

- OS Grafana is installed on: grafana/grafana:main-ubuntu in windows docker

- User OS & Browser:chrome

- Grafana plugins: no

- Others: no

**Comment by usmangt** [comment]
Hi @42bits,

Thanks for opening this issue.

Can you please tell us from which URL you have downloaded this plugin?

**Comment by 42bits** [comment]
@usmangt 
Sorry, it was caused by my type judgment error, I will close the issue
