### ISSUE TITLE
Variable type (Custom)

### ISSUE THREAD

**Issue by romkat** [grafana/grafana#6055]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
Grafana ver.3.1
Open TSDB 
RedHAT Linux 
working on top 10 list 
to be able to sort and display the most utilized / busy list of out of many more with average or none utilized items , to better use real estate and possible avoid clotting in the dashboard    
I am not sure  where to configure  this setting. In the podcast "Screen Casts Episode 2" a use case called "smoothing variable" was giving to display similar idea , I believe Graphite Data source was used. It was pretty straightforward, however OTDB  have slightly different config views in Grafana

Templating variable was setup 
top10 = 1,2,3,4,5,6,7,8,9,10,20,30 
I was unable to find where under which tab in my graph my new custom variable $top10  should be applied  to. 
$top10 = 1,2,3,4,5,6,7,8,9,10,20,30 

http://docs.grafana.org/reference/templating/
Based on Podcast it was configured under the metrics tab with Grifite  datasource

Cheers for you support !

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
better ask in OpenTSDB mailing list or Grafana mailing list. 

Not sure what kind of OpenTSDB query you want. Not aware that it supports a "top" query.
