### ISSUE TITLE
webkit-scrollbar are neat but not noob userfrendly

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#6056]
The webkit-scrollbar take some getting used to. I would rather the default have them disabled/ or a global option to disable or override css. 
```
::-webkit-scrollbar
```

Why disabled? because on some computer screens the bar is hardly visible... Users are not expecting them to look different.. People that view our grafana pages are noobs.
Honestly I even have trouble working with them sometimes.

**Comment by torkelo** [comment]
will consider it, but look so horrible
![image](https://cloud.githubusercontent.com/assets/10999/18575181/fd5d58dc-7bd4-11e6-815a-f24959d36071.png)
