### ISSUE TITLE
BarChart: Tooltip has erroneous "Exemplar" header

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#60572]
**What happened**:
Bar charts ~~with exemplars~~ have broken ~~popover~~ tooltips. 

**What you expected to happen**:
Exemplars would not change the layout of bar charts, which do not support exemplars at this time.

**How to reproduce it (as minimally and precisely as possible)**:
Example from TNS app:
[debug-Exemplar 1 metric 1 label-2022-12-20 07_12_45.json.txt](https://github.com/grafana/grafana/files/10268623/debug-Exemplar.1.metric.1.label-2022-12-20.07_12_45.json.txt)

**Anything else we need to know?**:
Images aren't uploading right now, creating issue and will provide more details hopefully soon

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
i don't think exemplars can or should be supported in BarChart, where the primary use case is a category/text label x axis and a justified (non-temporal) x layout.

we have a bug with the Tooltip that now has an Exemplar" header which needs to be fixed. i think it was regressed by https://github.com/grafana/grafana/pull/59988

**Comment by leeoniya** [comment]
tooltip doesn't disappear when hovering away:

https://user-images.githubusercontent.com/43234/208679009-56c30ad8-21be-4eac-a2d8-3a8e9a00cf16.mp4

**Comment by gtk-grafana** [comment]
@leeoniya thanks for the details, I updated the description a bit, but feel free to make any other changes.
