### ISSUE TITLE
BarChart: tooltip no longer disappears when unhovering

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#60573]
regressed by https://github.com/grafana/grafana/pull/55809

tooltip doesn't disappear when hovering away:

https://user-images.githubusercontent.com/43234/208679009-56c30ad8-21be-4eac-a2d8-3a8e9a00cf16.mp4

**Comment by leeoniya** [comment]
looks like even then `clear` is true, `isActive` is always false:

https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/packages/grafana-ui/src/components/uPlot/config/addTooltipSupport.ts#L109

**Comment by mdvictor** [comment]
> looks like even when `clear` is true, `isActive` is always false:
> 
> https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/packages/grafana-ui/src/components/uPlot/config/addTooltipSupport.ts#L109

Myeah, that makes sense... dunno how I missed that. Thanks @leeoniya !
