### ISSUE TITLE
Variables: search in variable drop down is automatically selecting first value when pressing space

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#60589]
Based on [#4680](https://github.com/grafana/support-escalations/issues/4680)

**What happened:**

When the users try to search for a value that contains white space inside the dropdown variable options, it is automatically selecting the first value

**What you expected to happen:**

It should not select the value

https://user-images.githubusercontent.com/239999/208717288-c0d1efb3-7971-404f-97b5-2199b9ed74d2.mp4

**Comment by Vaani-pathariya** [comment]
Hello @axelavargas  , i am new to grafana and devops , but i would like to work on this issue . Also , can you suggest me with some resources to get to understand the project more 
Thank you !

**Comment by natellium** [comment]
Also brought up in https://github.com/grafana/grafana/discussions/38173
