### ISSUE TITLE
Build: Redis/Memcached integration tests problems

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#60587]
https://github.com/grafana/grafana-enterprise/pull/3503 removed build tags for redis/memcached in enterprise. OSS still has build tags for redis and memcached and seems like we never run these?
- https://github.com/grafana/grafana/blob/main/pkg/infra/remotecache/redis_storage_integration_test.go
- https://github.com/grafana/grafana/blob/main/pkg/services/live/managedstream/cache_redis_test.go
- https://github.com/grafana/grafana/blob/main/pkg/infra/remotecache/memcached_storage_integration_test.go

Memcached/redis integration tests sets the `GRAFANA_TEST_DB` to mysql in drone config, https://github.com/grafana/grafana/blob/ecf83a6df9db948992df61e369a85447383da2c4/.drone.yml#L3223-L3225, meaning that redis and memcached integration tests are running all integration tests using mysql again plus any redis/memcached integration tests.

Redis/memcached integration tests using mysql which takes 18+ minutes plus redis or memcached which takes ~2min. Optimally redis and memcached integration test steps should take 2min each instead of 20min

**Suggested/discussed solution:**
- Remove usage of `redis` and `memcached` build tags (should only be left in OSS)
- New naming rule for redis/memcached test:
  - all redis integration tests prefixed `TestRedisIntegration` and in Drone run `go list './pkg/...' | xargs -I {} sh -c 'go test -run RedisIntegration -covermode=atomic`
  - all memcached integration tests prefixed `TestMemcachedIntegration` and in Drone run `go list './pkg/...' | xargs -I {} sh -c 'go test -run MemcachedIntegration -covermode=atomic`

**Comment by papagian** [comment]
note that the tags were different in enterprise from the OSS (`integration` vs `redis`) and my assumption is also that we never run the OSS ones in the CI (checking [this](https://github.com/grafana/build-pipeline/blob/614cac4e4e7f35a5bdcfc4f7bd19289c65666d11/pkg/subcmd/integrationtests/action.go#L225) file's history I didn't find setting the OSS build tags anywhere.

**Comment by zerok** [comment]
@idafurjes I might have resolved this one by accident with #61920 . At this point we just use the same command for all the integration tests which is probably not ideal (speed-wise), though.

**Comment by papagian** [comment]
@zerok I have the impression that with your change we ignore the build tags (which BTW have become obsolete and we have to remove them) and we re-run all the backend tests even the `memcached`/`redis` specific ones which is not ideal since they have already run by another CI step.

therefore, I think that the solution proposed by @marefr for introducing a new naming rule for redis/memcached test is still valid.

**Comment by zerok** [comment]
At least I didn't make it worse 😌
