### ISSUE TITLE
Consolidate usage of Dashboard type generated by CUE schema

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#60590]
Nowadays, there are different types and sub-types that refer to dashboards and components. They are duplicated because they have been created at different times. Also, the backend types are not in sync with the frontend so we're using the CUE schemas to generate the different types.

There is a first version of the [Dashboard kind schema here](https://github.com/grafana/grafana/blob/5f93e67419e9587363d1fc1e6f1f4a8044eb54d0/kinds/dashboard/dashboard_kind.cue). It is not completed. There are some parts pending to work on. And here we did the first step to adopt Dashboard generated type in #55769.

## Usage of the generated schema in the frontend (TS generated)
Make sure we represent the persistent Dashboard object with the correct type everywhere
```
import {Dashboard, Panel, VariableModel} from '@grafana/schema'
```

- [ ] [`DashboardDTO.DashboardDataDTO`](https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/public/app/types/dashboard.ts#L63-L68) uses `Dashboard` as it is, and doesn't override some attributes to reduce specificity
- [ ] [`DashboardModel.getSaveModelClone`](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/DashboardModel.ts#L219) returns `Dashboard` type
- [ ] Since [DashboardModel defaults all non-provided properties when calling the constructor](https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/public/app/features/dashboard/state/DashboardModel.ts#L129-L157), the type accepted should be `Partial<Dashboard>`, and the model should use [`defaultDashboard`](https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/packages/grafana-schema/src/raw/dashboard/x/dashboard_types.gen.ts#L801-L811) to get the default values. 

## Schema definition
- [ ] [#VariableModel](https://github.com/grafana/grafana/blob/main/kinds/structured/dashboard/dashboard_kind.cue#L126-L143) generates [the current existing Variable types](https://github.com/grafana/grafana/blob/06ec8ad1858d0a65067541ba6057a6b293d5e506/packages/grafana-data/src/types/templateVars.ts). The generated types should match with the one represented by `TypedVariableModel`.
- [ ] Add descriptions to each of the schema properties to generate properly the types of documentation
- [ ] Improve [#Transformation.options](https://github.com/grafana/grafana/blob/da969e7d485c3d28b4a87d3d4693e870d1f760bf/kinds/dashboard/dashboard_kind.cue#L287) definition to be more specific than an object.
- [ ] [#Target](https://github.com/grafana/grafana/blob/da969e7d485c3d28b4a87d3d4693e870d1f760bf/kinds/dashboard/dashboard_kind.cue#L302). _Check the field description. @sdboyer

**Comment by sdboyer** [comment]
I think [`#Transformation.options`](https://github.com/grafana/grafana/blob/da969e7d485c3d28b4a87d3d4693e870d1f760bf/kinds/dashboard/dashboard_kind.cue#L287) might need to be added to the list for additional review?

Also definitely [`#Target`](https://github.com/grafana/grafana/blob/da969e7d485c3d28b4a87d3d4693e870d1f760bf/kinds/dashboard/dashboard_kind.cue#L302). For that, i should have a PR next week.
