### ISSUE TITLE
Switch theme button does not work properly on styleguide page

### ISSUE THREAD

**Issue by IldarMinaev** [grafana/grafana#6059]
- **I'm submitting a ...**
- [ x] Bug report

When going to /styleguide page button 'Switch theme' does not work correctly.
First click - redirect to light theme
Second click - theme back to black, because the button add ?theme= to URL each time
Next clicks - theme does not changed.

Root cause in the switchTheme function: [styleguide.ts](https://github.com/grafana/grafana/blob/252cd4901b347ffb7aed3e450921e06a617ca368/public/app/features/styleguide/styleguide.ts#L9)
The function does not check theme parameter exist.

Fix:

```
  switchTheme() {
    var other = this.theme === 'dark' ? 'light' : 'dark';
    if (/^.*[\?&]theme=/.test(window.location.href)) {
      window.location.href = window.location.href.replace(/^(.*\?.*)(theme=)[^&]*(.*)/,'$1$2' + other + '$3');
    } else if (/^.*\?.*/.test(window.location.href)) {
      window.location.href = window.location.href + '&theme=' + other;
    } else {
      window.location.href = window.location.href + '?theme=' + other;
    };
  }
```

**Comment by daniellee** [comment]
Seems to work in the latest master. Thanks for sending in a fix.
