### ISSUE TITLE
[grafana] Unknown error InfluxDB Error: undefined

### ISSUE THREAD

**Issue by kaushalshriyan** [grafana/grafana#6060]
Hi,

I am running grafana-3.1.1-1470047149.x86_64 and influxdb-1.0.0-1.x86_64 on CentOS Linux release 7.2.1511 (Core). I am encountering the below issue 

**Unknown error InfluxDB Error: undefined.**

Is there a way to enable debug logs in grafana to know the exact cause of issue as the error looks very generic. I did enabled level = "debug". I am unable to see any debug logs in /var/log/grafana/grafana.log.

Please also let me know if you want me to share both /etc/grafana/grafana.ini and /etc/influxdb/influxdb.conf.  Any help will be highly appreciable.

Regards,

Kaushal

**Comment by torkelo** [comment]
you can open chrome dev tools network tab and look at any requests issues by Grafana to your InfluxDB server. maybe there is a clue to what is wrong there? 

Please use the Grafana mailing list for questions.

**Comment by balageo** [comment]
Also, you could look at networking firewall rules on the server to check whether port 8086 is allowed for communication..
