### ISSUE TITLE
$interval issues? skewed mean values at different time ranges

### ISSUE THREAD

**Issue by xlwoon** [grafana/grafana#6061]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
3.1.0 - What Grafana version are you using?
InfluxDB - What datasource are you using? (fed by collectd)
CentOS 7 - What OS are you running grafana on?

Hi,

When I give this query to grafana:

SELECT difference(mean("value")) FROM "arcstatplugin_value" WHERE "type_instance" = 'zfs_misses' AND "host" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)

it renders a graph that shows much-too-high values when viewing at a wide time range, and eventually shows the right value when zoomed in. Is this perhaps something to do with how grafana handles $interval?

Or how it computes difference(mean("value"))?: I don't have this problem when I do a SELECT mean("value"), and mean(difference("value")) isn't valid. I find it strange that the $interval-rendered mean is higher than the absolute maximum value. As I understand, this should smooth peaks in the data but not exaggerate them.

![skewed_mean_vals_zoomout](https://cloud.githubusercontent.com/assets/14232888/18591410/bed63620-7c32-11e6-87fa-22c2a77bca41.png)
![skewed_mean_vals_midzoom](https://cloud.githubusercontent.com/assets/14232888/18591409/bed585ea-7c32-11e6-8b55-01fc723a2c62.png)
![skewed_mean_vals_zoomin](https://cloud.githubusercontent.com/assets/14232888/18591408/bed44f54-7c32-11e6-8ed8-71198b8b70d5.png)

The data and query for these pictures is exactly the same, only the viewing range differs.

Thanks!

Michael

**Comment by torkelo** [comment]
you will have to check the documentation for influxdb
https://docs.influxdata.com/influxdb/v1.0/query_language/functions/#difference

SELECT difference(mean("value")) FROM "arcstatplugin_value" WHERE "type_instance" = 'zfs_misses' AND "host" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)

So when you zoom out the $interval variable will be replaced with a larger timespan, which might make the difference between two points bigger.

**Comment by xlwoon** [comment]
I just worked it out in influxdb and you are correct.

In the end, I believe the real request / underlying need is for this feature: https://github.com/grafana/grafana/issues/5846 in order to scale the $interval-differences to the $interval-size
