### ISSUE TITLE
Set up analytics for DS connection on empty dashboard/explore pages

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#60620]
### Description
Add the following Rudderstack events to the connect DS in empty dashboard/explore page and track them on our dashboard.

### Todo

- [x] #60918 
- [ ] Create dashboard in our squads folder (accounting for event origin (explore/dashboard)

#### Rudderstack events
`dashboards_connectds_ds_clicked`
`dashboards_connectds_viewall_clicked`
~`dashboards_connectds_learnmore_clicked`~ (not implemented)
`dashboards_connectds_sampledata_clicked`

**Comment by natellium** [comment]
@kaydelaney @Elfo404 do you think there'd be a way to also know whether the user performs and action from Explore or Dashboards? Could help us understand where people start their journey.

**Comment by Elfo404** [comment]
absolutely. we may want to add `app: CoreApp` to the component props and add tracking internally so that is transparent to consumers. wdyt @kaydelaney?
