### ISSUE TITLE
Grafana generic_oauth invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by marian-gheorghe** [grafana/grafana#60632]
**What happened**:
Hi 
I have Grafana configured with generic_auth with a custom OIDC provider (see configuration bellow)
I am able to successfully authenticate users in the provider but on redirect to grafana dashboard/welcome page I get an error: "msg=login.OAuthLogin(NewTransportWithCode) error="invalid character '<' looking for beginning of value"

**What you expected to happen**:
Successfully logged in users are redirected to grafana without errors

**How to reproduce it (as minimally and precisely as possible)**:
```
# docker-compose.yml
version: '3'
services:
  # content hidden for the sake of brevity
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    user: '104'
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
       # [log]
      - GF_LOG_CONSOLE_LEVEL=debug
      - GF_LOG_FILE_LEVEL=debug

      # [users]
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      
      # [auth]
      - GF_AUTH_DISABLE_LOGIN_FORM=true

      # [auth.generic_oauth]
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_NAME=OAuth
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=<client_id>
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=<client_secret>
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=<my_auth_endpoint>
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=<my_token_endpoint>
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=true

      # - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=false
      - GF_AUTH_GENERIC_OAUTH_TLS_CLIENT_CA=/var/lib/grafana/ssl/ca_certificates.crt
```
 
`docker-compose up -d --build`

then go to localhost:3000 => login => Error will occur
<img width="431" alt="image" src="https://user-images.githubusercontent.com/39998360/208924207-ecdb91d9-2818-4119-bf14-d326cb854728.png">

**Anything else we need to know?**:
* I have already enabled debug logging (unfortunately couldn't get more info)
* The custom OIDC provider is signed with a private/corporate CA authority which is referenced by GF_AUTH_GENERIC_OAUTH_TLS_CLIENT_CA. (This part is correct, without it I would get "X509: certificate signed by unknown authority")
* Also, I could remove the GF_AUTH_GENERIC_OAUTH_TLS_CLIENT_CA and set GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true and I will get the same error: (i.e "invalid character '<' .... )

* Container logs: 
_2022-12-21 14:52:16 logger=context userId=0 orgId=0 uname= t=2022-12-21T13:52:16.531302287Z level=error msg=login.OAuthLogin(NewTransportWithCode) error="invalid character '<' looking for beginning of value"_

**Environment**:
- Grafana version: docker hub grafana:latest container
- Data source type & version: N/A
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others: GENERIC_OAUTH

**Comment by usmangt** [comment]
Hi @marian-gheorghe,

Thanks for opening this issue.

I have forwarded this issue to our Team as they have more expertise with Authentication and can provide you with more information.

**Comment by alexanderzobnin** [comment]
Hi, @marian-gheorghe ! I think it's something related to your configuration. I guess response returned from IdP (or maybe proxy between Grafana and IdP) contains HTML, not a JSON. So try to trace a request and see what's an actual reason. From the Grafana side, I think we can definitely improve error handling in this case.

**Comment by marian-gheorghe** [comment]
I've double-checked on my side, and indeed the OIDC server was returning 404 (aka HTML) because the token url had a typo. 
Closing the issue.
