### ISSUE TITLE
Leap Year causes url to show wrong date

### ISSUE THREAD

**Issue by jagte** [grafana/grafana#6063]
I am trying to create links that show the behavior of a server at the exact time that a test ran.  I am finding that any date that occurred after leap year, links to the date before it.

Example:
https://grafana.internal.company.com/dashboard/db/testing?var-env=beta&var-host=squid01&from=20160301T040001&to=20160301T050001

This shows the information for Feb 29th instead of March 1rst.

Grafana version 2.5.0

**Comment by torkelo** [comment]
strange, cannot replicate it in Grafana 3.1.1

![image](https://cloud.githubusercontent.com/assets/10999/18606678/e925990a-7cb6-11e6-8daf-1eccd5d97325.png)

**Comment by torkelo** [comment]
what time do you see in this dashboard?
http://play.grafana.org/dashboard/db/empty?from=20160301T040001&to=20160301T050001

**Comment by jagte** [comment]
![screen shot 2016-09-19 at 10 00 35 am](https://cloud.githubusercontent.com/assets/10214473/18641121/0628d7c0-7e50-11e6-8226-81eb6a6d5890.png)

**Comment by torkelo** [comment]
and if you change to UTC in dashboard settings? 

I think it's just a matter of 20160301T040001 being 29 feb in your local timezone

**Comment by jagte** [comment]
Looks like you are correct.  There is an 8 hour time difference.  I will try and figure out the settings for that.  Thanks!
