### ISSUE TITLE
Minified React error #31 when trying to open Grafana

### ISSUE THREAD

**Issue by FoxXxHater** [grafana/grafana#60638]
**What happened**:
Minified React error #31
after tryed to import an dashboard, when iam trying to enter my grafana with chrome

![image](https://user-images.githubusercontent.com/54017453/208936504-b7110b28-5ba3-4cce-9b14-67e7db3c6d2e.png)

**What you expected to happen**:
That i´t work

**How to reproduce it (as minimally and precisely as possible)**:
open my grafana with chrome

**Anything else we need to know?**:
With egde it works fine

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: InfluxDB (1.8)  and Prometheus (2.41.4)
- OS Grafana is installed on: Docker (Raspberry Pi 3)
- User OS & Browser: Chrome -> Fail; Edge -> Work's
- Grafana plugins: None
- Others: --

**Comment by FoxXxHater** [comment]
- with chrome on my mac it works

**Comment by usmangt** [comment]
Hi @FoxXxHater,

Thanks for opening this issue.

Can you please provide the steps of reproduction so that the community can also try to reproduce it on a test machine? 

Thanks.

**Comment by FoxXxHater** [comment]
Hello, 

i cant reproduce it. Because there was an problem with the IP config on my host where he cant reach the internet and the grafana servers. I fixed the ip problem.

**Comment by FoxXxHater** [comment]
I have reinstalled Google Chrome. Now it works... i dont know what was wrong, but i think grafana installed one cokie or data that chrome dosnt like...

**Comment by ofauchon** [comment]
I had the same problem (macosx/chrome/after Dashboard import by ID).

You can fix it with chrome dev. tools, and by clearing : 

- Storage / Local Storage 
- Session / Session storage 
- Shared storage 
- Cookies
