### ISSUE TITLE
Alert Templates Not Within Scope Everywhere

### ISSUE THREAD

**Issue by jayschell** [grafana/grafana#60648]
Using templates for values in `Custom Labels` seems partially supported. My use case is trying to dynamically generate the `og_priority` value for sending priority to OpsGenie. I'm using a template to pull the numeric value from an Elasticsearch document and create the P[1-5] string that OpsGenie wants in that tag. This works, as I can see the `og_priority` tag in the OpsGenie alert being set to the correct value; however, the actual `Priority` of the alert isn't being set correctly.

![Screenshot 2022-12-20 at 4 29 25 PM](https://user-images.githubusercontent.com/7072075/208983425-8d98464d-7c2c-4a17-b172-52881bdf2a12.png)

<img width="974" alt="Screenshot 2022-12-21 at 10 46 53 AM" src="https://user-images.githubusercontent.com/7072075/208983350-001be448-0d80-4359-8d63-ecf12107a982.png">

<img width="850" alt="Screenshot 2022-12-21 at 10 54 36 AM" src="https://user-images.githubusercontent.com/7072075/208982003-00467884-90c6-4a0d-a2de-9ddeeb237138.png">

This is the error I see in the grafana logs:

```
ngalert.state.manager t=2022-12-21T00:27:05.043956451Z level=error msg="Error in expanding template" name=description value="{{ template \"opsgenie.priority\" .}}" error="error executing template __alert_Log Monitor Tester: template: __alert_Log Monitor Tester:1:88: executing \"__alert_Log Monitor Tester\" at <{{template \"opsgenie.priority\" .}}>: template \"opsgenie.priority\" not defined"
```

It seems like wherever the actual `priority` is being set in the JSON data that's sent to OpsGenie doesn't have the same templating scope as wherever the tags are being generated.

**What happened**:

When using `{{template "opsgenie.priority" .}} for a `Custom Tags` value, the tag is created successfully with the correct value, but the `priority` value is not set correctly and an error is generated.

```
{
  "_incomingData": {
    "_parsedData": {
      "note": "null",
      "-responders": [],
      "-actions": [],
      "-tags": [],
      "description": "This is not an actual alert. Just a test doc for dev\n\t\n\thttps://log-kibana.corp_domain.io/goto/48060350-6c3a-11ed-90b3-81468a23b29f",
      "alias": "3615ad37c57322b49ba32b05bf7419c1d746e553a31b973a420f9127a79e8a8a",
      "source": "Grafana",
      "message": "Log Monitor Tester",
      "priority": "P3",
      "user": "Alert API",
      "_extraProperties": {
        "hits.keyword": "2",
        "level.keyword": "1",
        "rule_name.keyword": "Test Rule Name",
        "alertname": "Log Monitor Tester",
        "grafana_folder": "Alerting",
        "og_priority": "P1",
        "conditions.keyword": "Number of matching documents is greater than 1",
        "source": "elasticsearch_alert",
        "@message.keyword": "This is not an actual alert. Just a test doc for dev",
        "saved_search.keyword": "https://log-kibana.corp_domain.io/goto/48060350-6c3a-11ed-90b3-81468a23b29f",
        "url": "https://grafana.corp_domain.io/alerting/list"
      },
      "entity": ""
    },
    "integrationType": "GrafanaV2",
    "integrationName": "Grafana - Alert_Test",
    "incomingDataId": "18d2e5dc-5895-4bc3-bb58-c5e20f70256b"
  },
  "_result": {
    "alertMessage": "!!! TEST !!! [Grafana]: Log Monitor Tester",
    "alertAction": "Create",
    "integrationName": "Grafana - Alert_Test",
    "alertCount": "1",
    "integrationActionName": "Create Alert",
    "alertId": "1e0d126e-0912-40e0-a620-c364bc3c2e50-1671582571095",
    "alertAlias": "3615ad37c57322b49ba32b05bf7419c1d746e553a31b973a420f9127a79e8a8a",
    "user": "Alert API"
  }
}
```
**What you expected to happen**:

The `og_priority` value is set with a template, the `Priority` is set correctly as well.

**How to reproduce it (as minimally and precisely as possible)**:

- Create an OpsGenie contact point
- Enable the optional setting to override priority with the `op_priority` tag
- Create a template that will output a value of P[1-5]
- Use the template for the value of a `Custom Tag` of `og_priority`
- Generate an alert to OpsGenie

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: grafana:9.3.2 container (Alpine, I'm assuming)
- User OS & Browser:
- Grafana plugins: 
- Others:

**Comment by armandgrillet** [comment]
Thanks for this detailed issue, most engineers specialized on this topic are currently on vacation but we will investigate this early 2023.

**Comment by grobinson-grafana** [comment]
Hi! 👋 It looks like there is some confusion here between templating labels and annotations and templating notifications. These are separate features, and the templates from one cannot be used in the other. For example, it looks like you are trying to use a Message template, which is for templating notifications, in a Custom Label. This won’t work I’m afraid.

**Comment by jayschell** [comment]
Ah, ok. That makes sense. Does Grafana currently support creating templates for labels and annotations? I'm not finding a related page in the UI.

**Comment by grobinson-grafana** [comment]
Grafana does not support creating templates that can be shared between alert rules I'm afraid. Would you like to open a feature request for this, it would be interesting to see if other users need this feature too.

**Comment by grobinson-grafana** [comment]
Grafana does not support creating templates that can be shared between alert rules I'm afraid. Would you like to open a feature request for this? I would be interested to see if other users need this feature too.
