### ISSUE TITLE
Grafana templating  (custom variable) 

### ISSUE THREAD

**Issue by romkat** [grafana/grafana#6064]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
grafana ver. 3.1
OpenTSDB 2.2
Redhat
looking to get custom type variables working 
to minimize number of devices to be displayed 
message": "No such name for 'tagv': 

P.S.
it is working with Graphite  Data Source,   but not working with  OTSDB 

Please Ref: Variable type (Custom) #6055 for more information about the environment 

Thanks

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
please open questions in the mailing list. 

and if you think it could be a bug you missed some information. 

The issue template even contains a notice that you might have missed :) 
> IMPORTANT If it relates to metric data viz:
An image or text representation of your metric query
The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

How are you using the variable in you OpenTSDB query? what is the query sent to OpenTSDB? (check chrome dev tools network tab)
