### ISSUE TITLE
No data when opening dashboard as a public dashboard.

### ISSUE THREAD

**Issue by BryanTancre** [grafana/grafana#60651]
I am visualizing data on a dashboard that will soon go public. Public dashboards are a nice feature to display the dashboard without the need of a login. I have made a dashboard that will go over some KPI's/illustrations and functions quite well, but as soon as I create a public link, the data does not seem to load into the public dashboard. Resulting in all data visualisations (such as gauges) to display the no data sign.

there is a workaround from it (ish). The reason I think this happens, is that the public dashboard does not read queries that are disabled, and only load in the queries that are enabled. Meaning that if you create for example an expression (query B) of query A, and you disable query A so only query B is visible, that the gauge will show no data. This is due to query B being dependent on query A of delivering the data needed to compute the expression. And if query A is disabled (you want this or else there are two gauges visible) than query B shows no data. 

You can replicate this by making a new dashboard and adding some data (doesn't rally matter) into query A. Then from that data, you add a math expression where you enter e.g. : -$A. When that is done choose a way to visualise the data like a gauge and make the dashboard public. When looking at the public dashboard you will see the data for both queries in case they are both enabled (the little eye) en you will see no data when disabling query A on the public dashboard, even though on the normal dashboard you will see the results of query B with no problem. Fixing this problem can be done by transforming the queries and filtering out the unwanted queries. So in the end this problem is solved but should be mentioned so this problem can be adressed.

I am working with Clickhouse Native but this problem can be replicated with any kind of data source.

**Comment by WLR86** [comment]
Wow thank you @BryanTancre for this - I had the very same issue and eventually got it working thanks to the workaround you suggested.

**Comment by usmangt** [comment]
Hi @BryanTancre,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I will forward this issue to our Engineers as they might be able to tell in more detail.

**Comment by usmangt** [comment]
Grafana OSS Version: Version 9.3.2 (commit: 21c1d14e91, branch: HEAD)

Logs:
<details open>

```
logger=publicdashboards.service t=2023-01-05T11:18:20.218358137+01:00 level=error msg="Error querying datasources for public dashboard" error="expression request error: unable to find dependent node 'A'" datasources=[__expr__]
logger=context userId=1 orgId=1 uname=admin t=2023-01-05T11:18:20.218402778+01:00 level=error msg= error="unexpected error type [*fmt.wrapError]: expression request error: unable to find dependent node 'A'" remote_addr=192.168.122.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-01-05T11:18:20.218438759+01:00 level=error msg="Request Completed" method=POST path=/api/public/dashboards/64b7ecaa50134e719510f7c8fc7e9685/panels/2/query status=500 remote_addr=192.168.122.1 time_ms=0 duration=999.589µs size=48 referer="http://192.168.122.137:3000/public-dashboards/64b7ecaa50134e719510f7c8fc7e9685?orgId=1" handler=/api/public/dashboards/:accessToken/panels/:panelId/query
```

</details>
