### ISSUE TITLE
influxdb query builder support for ORDER BY and LIMIT

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#6065]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- What datasource are you using?
  influxdb

Would be nice if the query builder supported ORDER BY and LIMIT.

When displaying a table of data these modifiers are nice to have.
Limit is a must have when viewing a year worth of logs.

```
SELECT "request_type" as "type","request","request_status","ip","city" 
FROM "nginx_access" WHERE $timeFilter AND host =~ /p01/ 
ORDER BY time DESC LIMIT 100
```

**Comment by jpereira** [comment]
+1
