### ISSUE TITLE
Add `cue fix` to grafana/grafana CI & pre-commit hook

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#60676]
As with our other languages, we want to ensure standard formatting in our CUE files. That means doing it in CI, and making it a part of the husky-managed pre-commit hook in grafana/grafana itself.

If anything, it's doubly important to do this for CUE since there isn't good native IDE support for such things yet.

`cue fix` is the command to run. For stability and consistency, we'll need to manage the `cue` version using bingo (see `.bingo`).

**Comment by frossano-grafana** [comment]
developer experience 
I would do it but let's talk about it 
@rhorvath to review with the team to see if it's done - @spinillos  has the state for this

**Comment by joanlopez** [comment]
Related PR: https://github.com/grafana/grafana/pull/61941
