### ISSUE TITLE
Generate a set of github labels and automated assignments for them from kind introspection

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#60682]
To streamline reporting of schema issues, we need a GitHub action (or equivalent) that maintains at least one predictably named label for each kind. `kinds/core/$MACHINENAME` would probably work - so, `kinds/core/dashboard` for dashboards. The action needs to be idempotent, synchronizing the whole list every time it runs. That way, as soon as a kind exists, there's automatically a label associated with it.

Probably the easiest way to do this would be for the action to consume the [report.json](https://github.com/grafana/grafana/blob/9d64e7cedc316d894e1fd3013c39a4359b4c3b52/pkg/kindsys/report.json) we generate on main.

We also need automation to apply these labels to anything that modifies the relevant kind declaration, though that's probably a follow-up.

**Comment by sdboyer** [comment]
i think we can skip the automated assignment bit for schema day, what matters presently is just that the labels exist

**Comment by rhorvath** [comment]
Implementation detail of Schema issue reporting and will be decided by a community team
