### ISSUE TITLE
[Bug] The precision of y axis show

### ISSUE THREAD

**Issue by sunfaces** [grafana/grafana#6070]
It would be very helpful to have the decimal precision override option also for the y axis! If the value stays constant over a long time (like it is often with disk usage) Grafana always puts in as many decimals as possible and that messes up the graphs...

![image](https://cloud.githubusercontent.com/assets/7036754/18623502/83b0423a-7e70-11e6-8dcf-f85bd5ae3d35.png)

![image](https://cloud.githubusercontent.com/assets/7036754/18623575/a3cbc9bc-7e71-11e6-91b0-3e8c18936698.png)

**Comment by torkelo** [comment]
the code here must be updated to better handle very flow diff (or no diff) between min/max
https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js#L1744

**Comment by alexanderzobnin** [comment]
@torkelo should we change [jquery.flot.js](https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js) directly?

**Comment by torkelo** [comment]
Yes, it already contains many enhancements and fixes, J query flöt is a dead project so no new updates for it anyway

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/6082
