### ISSUE TITLE
AlertList: Feature Request: make Dashboard UID a link to dashboard

### ISSUE THREAD

**Issue by iameli** [grafana/grafana#60713]
Our Grafana front page has an Alert List component. Before Unified Alerting, I could click any of these alerts and go right to the panel in question. Now I just get this:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/257909/209230735-9e5e1319-9585-4b0c-8758-efc81ed4c80e.png">

It's... _so close_ to being useful! It has the Dashboard UID and Panel ID! It just needs to render a link and everything would be lovely. I'm on Grafana v9.3.2 (21c1d14e91)
```[tasklist]

- [ ] https://github.com/grafana/grafana/issues/63563
- [ ] https://github.com/grafana/grafana/issues/63564
```

**Comment by konrad147** [comment]
Solved by https://github.com/grafana/grafana/issues/63563 and https://github.com/grafana/grafana/issues/63564
