### ISSUE TITLE
PageHeader & TabsBar not shown according to the language I set

### ISSUE THREAD

**Issue by TaitChan** [grafana/grafana#60719]
**What happened**:
When I set the language to Chinese (in _grafana/conf/defaults. ini_，default_language = zh-Hans), 
PageHeader & TabsBar still show English

**What you expected to happen**:
When I change the default language, the PageHeader & TabsBar is displayed in that language

**How to reproduce it (as minimally and precisely as possible)**:
in _grafana/conf/defaults. ini_，set default_language = zh-Hans

**Anything else we need to know?**:
Can I submit a pr to fix this problem?
in _grafana/public/app/core/components/PageHeader/PageHeader.tsx_
`import { getNavTitle, getNavSubTitle } from 'app/core/components/NavBar/navBarItem-translations';`

**Environment**:
- Grafana version: The main branch
- Data source type & version: -
- OS Grafana is installed on: Local development
- User OS & Browser: Mac & Chrome
- Grafana plugins: -
- Others: -

**Comment by TaitChan** [comment]
**before：**
![before](https://user-images.githubusercontent.com/29780093/209298562-f5f952da-8deb-4972-8f58-664abf84c150.png)
**after：**
![after](https://user-images.githubusercontent.com/29780093/209298622-976b5d26-3315-4dad-a1bd-2254bba3cb25.png)

**Comment by usmangt** [comment]
Hi @TaitChan,

Thanks for opening this issue.

Yes, you can submit a PR if you already know the root cause of the fix.

**Comment by eledobleefe** [comment]
First of all, thank you @TaitChan for raising this issue, but regarding internationalization we don't currently accept contributions, as you can see in [this information doc](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md).

**Comment by TaitChan** [comment]
Thank you for response.
I will remove the translation part of the submission.
Can other parts be discussed? 
In fact, you have internationalized the left menu part, 
but the pageheader content does not match the left nav menu, 
theoretically they should display the same.

**Comment by eledobleefe** [comment]
Hi @TaitChan. I can bring your comment to the product owners but, as we are in the holiday season, they will not be available till after New Year.

**Comment by TaitChan** [comment]
Ok, thanks for replying and have a great holiday

**Comment by JoaoSilvaGrafana** [comment]
Hi @TaitChan , I have chatted to the product owner of this feature and we have discussed that the only thing we cannot accept at the moment is actual translations (editing things in the .json files). So the rest of your PR should be able to be reviewed if you remove those! Thanks for the contribution

**Comment by TaitChan** [comment]
Hi @JoaoSilvaGrafana , Thank you for your discussion and earnest response, which gives me great encouragement, and I will revise my submission to the point where it can be reviewed.
