### ISSUE TITLE
Inconsistent display of data

### ISSUE THREAD

**Issue by Mormaii** [grafana/grafana#6072]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? CentOS 7
- What did you do? Load a dashboard, then reload it and see missing data, reload it again and see different data almost every time.
- What was the expected result? Always show all of the data and consistently

I'm attaching a GIF as an example to show what I mean. All the graphs are set to have an interval of 30s  yet on 21s of refreshing it shows different values almost always and sometimes it even shows as as "N/A". This is really annoying as I have to reload the graphs several times to get them to display all of the data and sometimes I'm not even sure it's showing all of it. Is there any solution to this?

https://gfycat.com/ElasticGlossyAsianwaterbuffalo

**Comment by torkelo** [comment]
are you sure it's Grafana and not your elasticsearch that returns data inconsistently? 

What is your singlestat options? (what stat are you showing, total, avg, min, max). 

If you still think the problem is in Grafana, please provide the Elasticsearch query and response (find this in chrome dev tools network tab), and provide this for the NA case (where no data is show in the singlestat panel).

**Comment by Mormaii** [comment]
Here is the response:

http://pastebin.com/japW0DAU

I'm seeing there is an error 

"reason":"rejected execution of org.elasticsearch.transport.TransportService$4@621049a8 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@92ba1c5[Running, pool size = 13, active threads = 12, queued tasks = 1000, completed tasks = 936982]]"

Sorry for making opening an issue, it's not grafana's faults in any way. I've checked the query now and when it shows different values on a lower than 30s interval it's because some of them are failing but not all so that's why it doesn't show "NA" but it shows something different.

Could you by the way check my comment on this one? https://github.com/grafana/grafana/issues/2696
I'm 99% positive this is indeed a bug and not working as it should be.
