### ISSUE TITLE
exclude days/weekends

### ISSUE THREAD

**Issue by McKogan** [grafana/grafana#6073]
Hi

is there a way of excluding weekends or specific days from a graph?
Is it possible to exclude a specific point from graph?
 
I'm analyzing cellular network data, the weekends add anomalies to the graph and it would great if they can be excluded.

**Comment by torkelo** [comment]
to exclude data points you will have to do that in your metric query, 

to hide/skip weekends from the graph, similar to this issue:
https://github.com/grafana/grafana/issues/5930
