### ISSUE TITLE
Mismatched labels and colors with legend when stacking enabled

### ISSUE THREAD

**Issue by Koriit** [grafana/grafana#60746]
**What happened**:
Mismatched labels and/or colors when multiple series are stacked.
![image](https://user-images.githubusercontent.com/75976467/209391550-4b6bb883-e33f-4dfa-8e7c-c45eb1bc9a77.png)
![image](https://user-images.githubusercontent.com/8916393/209394326-80bcd53a-06b2-4499-b608-a3daeff5f55d.png)

**What you expected to happen**:
No mismatch like when the stacking is off.
![image](https://user-images.githubusercontent.com/8916393/209394340-06ca5b0b-3008-47a6-87fc-ee42400eb7ac.png)

**How to reproduce it (as minimally and precisely as possible)**:
I have noticed this problem appears when series are not continuous - some series start, and some series stop at "the same time" (like during Kubernetes pods restarts).

When series are continuous, there is no such problem even with stacking:
![image](https://user-images.githubusercontent.com/8916393/209394397-eaeae244-a684-40d1-9c85-bd45a2343806.png)

**Anything else we need to know?**:
I think I still remember the same problem was observed in v8.

And this issue from back in 2016 looks awfully similar: https://github.com/grafana/grafana/issues/5828

**Environment**:
- Grafana version: 
v9.3.2
- Data source type & version: 
Prometheus, chart=kube-prometheus-stack-41.3.2
- OS Grafana is installed on:
I don't know, but definitely some linux container
- User OS & Browser: 
Kubuntu 22.10, Chrome 108 64bit
- Grafana plugins: 
All from grafana labs, except for https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel which is not really used on affected dashboards
- Others: 
I only played with kubernetes metrics, don't know if it has any relevance.

**Comment by leeoniya** [comment]
looks like a dupe of #56623? (the lines are not erased in regions where the series' values in the stack are 0)
