### ISSUE TITLE
[Feature request] Add an option to change the first column title.

### ISSUE THREAD

**Issue by EstebanSantana** [grafana/grafana#6074]
Grafana version: 3.1
Datasource: Graphite
OS: RHEL 6.7

Hi,
I use Grafana in supervision mode with a lot of terminals.
I use the table panel to show differents top 5, some times is processes, IDs, metrics, etc.
It's possible add a field to overwrite the first column title?
thanks.
Best regards.
![capture](https://cloud.githubusercontent.com/assets/9363654/18628336/04aae4dc-7e60-11e6-9069-9ae0c209e882.PNG)

**Comment by torkelo** [comment]
no it's currently not possible, might be added in future table panel enhancements.
