### ISSUE TITLE
singlestat / thresholds

### ISSUE THREAD

**Issue by bf228** [grafana/grafana#6075]
Is the following possible?  If not this might be a useful feature.  For some singlestats I'm seeing "N/A" which I believe means the query return no results.   I'm using the range-map to translate a null to text "0" (so a 0 appears instead of N/A).  That's useful.  I've defined my thresholds to be "1,5" as I would like a 0 value to show as green.  However, it appears that the thresholding mechanism doesn't treat an "N/A" entry as a 0 so does not get color coded.  Is there a way to get the translated "N/A" values to be processed by the thresholding logic?  Is there a way to set a default bg color that would only be overridden if the thresholding logic kicked in?

I really like the ability to quickly flip between time durations-- last 1hr, 3hrs, etc.  It would be nice if the thresholding also could be keyed based on duration.  Right now, it appears that thresholding is static relative to the time window.   Is there a way to embed thresholding values based on time durations.  eg use threshold 1,5 for 1hr, use threshold 4,10 for 3hrs, etc.

thanks

**Comment by torkelo** [comment]
thresholds are only applied to the metric values returned from your query. For some time series databases you can transform nulls to zero. 

you can only provide one set of thresholds, not many depending on time range :(
