### ISSUE TITLE
Public Dashboard bug

### ISSUE THREAD

**Issue by Talhazzers** [grafana/grafana#60752]
Hi,
I get the following error when I try to view the public dashboard.

```
Panel plugin not found: Unable to load library panel:

status:400
statusText:"Bad Request"
data:Object
message:"Failed to extract queries from panel"
messageId:"publicdashboards.panelQueriesNotFound"
statusCode:400
traceID:""
config:Object
url:"api/public/dashboards/8e3a869ef786452b85d6236a4c148800/panels/2/query"
method:"POST"
data:Object
requestId:"Q100"
retry:0
headers:Object
hideFromInspector:true
message:"Failed to extract queries from panel"
```

**Environment**:
- Grafana version: v9.3.2 (21c1d14e91)
- Data source type & version: InfluxDB & Telegraf
- OS Grafana is installed on: Ubuntu 22
- User OS & Browser: MacOS, Safari

**Comment by krzd7** [comment]
Hi, I guess we are all getting this. Dashboard panels are broken for users with "view" permissions.

Check if this report is related: https://github.com/grafana/grafana/issues/59771

**Comment by usmangt** [comment]
Hi @Talhazzers and @krzd7,

Thanks for your comments on this issue. I have assigned the already existing issue  https://github.com/grafana/grafana/issues/59771 to the Engineering team as it got missed in selection. You will get an update there as for now I will close this one.
