### ISSUE TITLE
Canvas: Dynamic metric value

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#60751]
We're looking to do something rather dynamic and I was wondering if there was a way or in the future you could set the metric block to a variable or regex search value. With the dynamic panel layout when it changes the metrics inside of the Canvas keep the initial value and don't dynamically change with the rest of the dashboard.

IE: I want Metric Element 1 to swap between a metric from Machine A or Machine B if they are chosen on the dashboard. Right now when swapping to Machine B it does swap, but the metric element still is showing the value for Machine A (Which is nothing since it's swapped).

If I could set the metric element to be a regex search from the list of values it has available or a variable it would fix this problem

[See community feedback feature request](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-4461038)

**Comment by jfharden** [comment]
One workaround I've found for this is to use a rename by regex transformation.

For example we have multiple aws accounts and are using a cloudwatch data source with cross-account observability.

Lets take the example of a lambda called `<account_name>__log-delivery`.

We have a canvas field which displays the value for `<account_name>__log-delivery Errors`

The raw metric names are of the form `AWS/Lambda <lambda_name> <metric_name>` e.g `AWS/Lambda test__log-delivery Errors`.

If you apply a transform of `Rename by Regex` to match `AWS/[^ ]+ [^ ]+ (.*)` and replace with `$1` the metric name becomes just `Errors` and the canvas field can be set to `Errors`.

![Screenshot 2023-07-05 at 15 58 56](https://github.com/grafana/grafana/assets/2170030/41aa4a6d-bba6-4f40-a808-8bd02327e56e)

![Screenshot 2023-07-05 at 15 59 25](https://github.com/grafana/grafana/assets/2170030/3c2e0499-eec3-4802-8de5-6a30f5447fb3)

Then when you change the variable on the dashboard (in my case AWS Account Name) the fields still have the same transformed name, but the values have been queried from a different metric stream.

This example shows the dashboard with the account set to test:
![Screenshot 2023-07-05 at 15 33 15](https://github.com/grafana/grafana/assets/2170030/ba7ab2bf-1984-43eb-a4d2-40e7e346b07c)

Then if I change the account variable to staging all the canvas fields update accordingly

![Screenshot 2023-07-05 at 15 52 54](https://github.com/grafana/grafana/assets/2170030/2d01e14d-43d6-475d-8069-6e2d2174ca8c)
