### ISSUE TITLE
Merge transformation not working using uql

### ISSUE THREAD

**Issue by Usama420-git** [grafana/grafana#60762]
Merge transformation not working using uql Infinity Data Source
`parse-json
| jsonata "$map(value,function($v){{ 'inviteDateTime': $v.$substring(inviteDateTime, 0, 10), 'id': $v.id, 'duration': $v.duration,  'successfulCall': $v.successfulCall}})"`
when I am using Json and adding columns the merge transformation is working but when I am using UQL query merge not working when 1 of the query returns empty but this is not the same case with json 

I want to use uql because I want to convert my date with jsonata. but why the merge not working when I am using UQL Query

![query](https://user-images.githubusercontent.com/51694624/209547808-d69ed0e8-9b48-4992-9be2-99e4d71eede7.PNG)

**Comment by zuchka** [comment]
Thanks for creating this issue, @Usama420-git 

this is a third-party plugin. I would make your issue in the plugin's repo and include more precise details for reproduction:

https://github.com/yesoreyeram/grafana-infinity-datasource
