### ISSUE TITLE
Datasource UID is not updated properly when copying a dashboard to another Grafana instance

### ISSUE THREAD

**Issue by freak12techno** [grafana/grafana#60769]
**What happened**:
I have a dashboard that I want to copy over to another Grafana instance. Original Grafana instance has a Prometheus datasource with `uid: xxxxx`, while new Grafana instance has a Prometheus datasource with `uid: yyyyyy`.  I copy it as JSON and import it on another Grafana server, it asks me to select a datasource, but after saving it, all panels are empty, and if you inspect a JSON, it has references to the older Prometheus datasource UID, like this, instead of having it pointed to the newer one:

```

      "datasource": {
        "type": "prometheus",
        "uid": "xxxxxxx"
      },
```

If I use find and replace in JSON edit screen and replace all UIDs with the newer one, everything would start to work correctly.

**What you expected to happen**:
When choosing a datasource during import, it should update all datasource UIDs to ones from the current Grafana instance

**How to reproduce it (as minimally and precisely as possible)**:
- Have two Grafana instances with two Prometheus instances with different UIDs on each of them
- Have a dashboard on a first Grafana instance that uses Prometheus as a datasource
- Go to JSON edit screen and copy all of it
- On second Grafana, go to Dashboards -> Import and paste this JSON
- Choose a Prometheus datasource when importing
- The dashboard is displaying empty panels everywhere
- Go to JSON edit, and replace all of the UIDs of the Prometheus datasource from the first Grafana to the ones from the second ones
- Everything is working

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @freak12techno 

Please use the sharing modal for the appropriate workflow. It includes an `Export for sharing externally` option. Here are [the docs](https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/#export-and-import-dashboards) and here is a vid:

![CleanShot 2022-12-28 at 10 56 04](https://user-images.githubusercontent.com/37156449/209871533-d89e3515-026b-4faa-94ae-1217a5f34705.gif)

**Comment by freak12techno** [comment]
Lovely, didn't know that was a thing. Thanks for letting me know! @zuchka

**Comment by a-pattani** [comment]
Hi @zuchka When I enable "sharing externally" it assigns $DS_PROMETHEUS variable to data source UID. But what if I provision dashboards to multiple different environments. In that case it says "$DS_PROMETHEUS" not found.

Note: I am using helm charts to provision dashboards to different environments.

**Comment by alexmc1510** [comment]
Hello, @a-pattani , did you find a way to make it work with provisioning dashboards?

**Comment by alexmc1510** [comment]
Thank you very much for the answer. I got the same reply in the following
conversation and worked for me.
https://community.grafana.com/t/dashboard-provisioning-problem-with-data-source-uid/144294/2

Thanks!
