### ISSUE TITLE
Support logging in with Grafana.net account

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#6076]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It would be great is users could log into their Grafana using the same credentials they use on Grafana.net, similar to the way they can use their Github or Google credentials.

**Comment by daniellee** [comment]
Closed by #6077
