### ISSUE TITLE
Grafana looses "zoom in" capability after docker-compose --force-recreate, displays No Data on zooming in on panel

### ISSUE THREAD

**Issue by noahsmindfuck** [grafana/grafana#60775]
**What happened**:
I recently reported the issue #59408 and upon investigation I figured something out that might not be related. Whenever I use the command ```docker-compose up -d --force-recreate``` I am only able to zoom into the data segments that have accumulated after that command. The data from before is shown in any zooming level that includes at least one segment of data from that last restart but whenever I zoom into areas from before I get the "No Data" monster shown.

**Update**: After trying to understand what's going on by randomly changing things I figured that changing the Loki config and restarting Loki already leads to the same problem. That is very unfortunate because it means that Loki loses access to previous values after a change in the config? I opened a Loki specific request here https://github.com/grafana/loki/issues/8011

**Update 2**:
I want to add that the newly accumulated data is shown properly, it is the old data that is not visible through zooming anymore.

**What you expected to happen**:
See the data that Grafana is actually able to display.
 
**How to reproduce it (as minimally and precisely as possible)**:
See #59408 for the docker-compose file. 
Step 1: accumulate data over time
Step 2: ```docker-compose up -d --force-recreate``` 
Step 3: accumulate more data
Step 4: zoom into the data segments from before the forced recreation of the container

**Anything else we need to know?**:
A short image story for detailed understanding of the problem:
* forced recreate was at about 14:00, since then no data was collected
* screenshot of data that is visible bc. one data point is after 14:00
![Screenshot 2022-12-27 at 14 40 29](https://user-images.githubusercontent.com/24893086/209676474-fdda6d07-6a97-4249-9045-4b39b1917615.png)
* screenshot of the selection I want to display
![Screenshot 2022-12-27 at 14 40 55](https://user-images.githubusercontent.com/24893086/209676569-174f55e0-0e41-42ad-b00d-e7b3283ce082.png)
* screenshot of the result of the selection
![Screenshot 2022-12-27 at 14 41 04](https://user-images.githubusercontent.com/24893086/209676618-9b0a9eb3-0f54-451d-99b4-ec22922dbe80.png)

Also:
* It's probably related to #57995 in some way
* moving the sliders < and > in the top right reveals No Data until I reach the timespan that includes the point in time of the forced restart.

**Environment**:
Grafana version:
image: grafana/grafana:latest
Data source type & version:
image: grafana/promtail:2.4.0
image: grafana/loki:2.4.0
OS Grafana is installed on: MacOS X 10.15.7 (Localhost)
User OS & Browser: MacOS X 10.15.7 & Safari
Grafana plugins: clock
Others:

**Comment by zuchka** [comment]
we can decide how to move this forward pending the discussion in https://github.com/grafana/grafana/issues/59408
