### ISSUE TITLE
Canvas: Investigate displaying datalink variables on canvas

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#60778]
See [community feedback comment here](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-4497849)

In 1/10/23 daily we discussed adding a "link" option to the text dimension editor that would allow user to select a data link to display for the text element

We also discussed potential to add a dedicated "link" element similar to metric value but will first support text dimension editor change and then consider adding a custom component as a "short cut" - may or may not make sense to do

1/11/23 - we discussed adding a tooltip and displaying the data links. Initially it will apply to text and metric value elements.

**Comment by adela-almasan** [comment]
Canvas tooltip issue - #61415
