### ISSUE TITLE
Dashboards: can contain panels with null ids

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana#60777]
**What happened**:

Currently, you can import a dashboard (like [dashboard-nil-ids.json.txt](https://github.com/grafana/grafana/files/10309499/dashboard-nil-ids.json.txt)) where its panels don't have an id.

This produces some undesirable effects, like the one discussed on [this escalation](https://github.com/grafana/support-escalations/issues/4668). It also seems to be an undesirable state, because in certain places like [here](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/DashboardModel.ts#L427) we try to ensure that all panels have an id. 

So, I'm wondering if we should actually ensure that behavior on the backend side (on dashboards provisioning, importing, etc) in order to prevent these kind of incoherencies and/or unexpected behaviors.

**What you expected to happen**:

Behavior associated with panel ids to be predictable, reproducible and coherent between frontend and backend.

**How to reproduce it (as minimally and precisely as possible)**:

If you try to import the attached dashboard JSON, you'll notice that it can exist even if its panels don't have a valid id, but...
- Frontend guesses the ids at time of drawing the dashboard.
- If you navigate to the JSON model tab, it displays the guessed ids.
- If you make it editable, it sets the panel ids on first update/save.

So.. I'd expect that behavior to be guaranteed and/or centralized on the backend side.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: `main`
- Data source type & version: `N/A`
- OS Grafana is installed on: `MacOS` _(doesn't matter)_
- User OS & Browser: `Google Chrome` _(doesn't matter)_
- Grafana plugins: `N/A`
- Others: `N/A`

**Comment by joanlopez** [comment]
Related discussions [here](https://raintank-corp.slack.com/archives/C03MCTKAJA0/p1672158960660149) and [here](https://raintank-corp.slack.com/archives/C02DJ3HV42W/p1672158927150719).

**Comment by joanlopez** [comment]
> based on the above discussions it seems that the way to follow would be to validate the dashboard against the schema during import/provisioning however, I have noticed that the panel ID is [optional](https://github.com/grafana/grafana/blob/15d41698138f250b85ccd423f2f252dea7cf3c93/kinds/dashboard/dashboard_kind.cue#L400) there: not sure why

I'm sorry, but I'm definitely not a good candidate to answer this, indeed I had similar doubts when I created the issue.
Perhaps someone with a larger historical background? @torkelo

**Comment by torkelo** [comment]
Not sure we are guessing the ids, we just assign ids if they are missing. 

We could assign ids on import as well, but for provisioning it could be a bit trickier as we cannot modify the dashboard when we save a provisioned dashboard without some other changes to how we diff/know when a provisioned dashboard has updated.

**Comment by papagian** [comment]
from the above discussion and after discussing with @sdboyer I think that we have to differentiate imports from provisioning
and in the case of provisioning, the best the backend can do is to validate the JSON  and forbid storing invalid JSONs or emit some warnings (more permissive) so that users would get notified that they have to fix their dashboard files.
