### ISSUE TITLE
Grafana does not pick up alerting provisioning JSON files

### ISSUE THREAD

**Issue by GBBx** [grafana/grafana#60771]
**What happened**:
I opened a ticket for this issue before but unfortunately it was closed (https://github.com/grafana/grafana/issues/59868). The problem persists. This is not a legacy alerting issue.
Luckily other users helped me understand the issue better so I can report it now with more details.

Short: Grafana does not pick up JSON alerting files from the provisioning directory (/etc/grafana/provisioning/alerting).

**What you expected to happen**:
Get alerting JSON from API and save it into the provisioning directory:
```
curl -s --noproxy '*' -H "Content-Type: application/json"  -H "Authorization: Bearer <token> " http://<grafana-server>/api/v1/provisioning/alert-rules/<id> > /etc/grafana/provisioning/alerting/alert-testing.json
```

I expect the alert to me marked as "provisioned" in the UI after a restart.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
Further troubleshooting by other users:
https://github.com/grafana/grafana/issues/59868#issuecomment-1346082115

https://github.com/grafana/grafana/issues/59868#issuecomment-1346150806

**Environment**:
- Grafana version: `9.3.2-1`
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
closing this issue and re-opening the old one b/c it has more info. thanks
