### ISSUE TITLE
Grafana Alerting： "failed to execute conditions: [plugin.unavailable] plugin unavailable"

### ISSUE THREAD

**Issue by OPSTime** [grafana/grafana#60789]
grafana version: 9.2.5

**grafana log:**
`logger=ngalert rule_uid=WZdym5p4k org_id=1 version=1 attempt=0 now=2022-12-27T08:22:00Z t=2022-12-27T08:22:00.058174179Z level=error msg="failed to evaluate alert rule" results="[{Instance: State:Error Error:failed to execute conditions: [plugin.unavailable] plugin unavailable EvaluatedAt:2022-12-27 08:22:00 +0000 UTC EvaluationDuration:58.16998ms EvaluationString: Values:map[]}]" duration=39.662198ms`

**Looks like it's related to the clickhouse plugin：**
```
  plugins:
    allow_loading_unsigned_plugins: vertamedia-clickhouse-datasource
```
But the plugin works normally.

![alert error1](https://user-images.githubusercontent.com/5848331/209781828-9cf8506d-08a0-42f4-8f4e-f07d4979458b.png)

![alert error2](https://user-images.githubusercontent.com/5848331/209781848-574e119e-64ab-4b17-8d2f-fe1601950862.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @OPSTime 

I don't think the grafana OSS codebase is the source of this problem. This is a third-party plugin, and looking through the open issues in their repo, it looks like users are able to make the plugin work with the new alerting platform + grafana 9.3+. I would check out those issues and maybe repost your issue there:

https://github.com/Altinity/clickhouse-grafana/issues

**Comment by OPSTime** [comment]
Thx
The plugin version is too old.
