### ISSUE TITLE
Streaming Plugins: No way to set extra channel data in DataSourceWithBackend plugin

### ISSUE THREAD

**Issue by MiddleMan5** [grafana/grafana#60783]
I'm following the backend with streaming tutorial here: https://grafana.com/tutorials/build-a-streaming-data-source-plugin/ and I wanted to be able to pass query arguments to the data stream to initialize my backend stream. The methods `RunStream` and `SubscribeStream` appear to be passed a `Data` object that makes mention to custom data, but they were always `nil` when accessed.

The request interface in question:
https://github.com/grafana/grafana-plugin-sdk-go/blob/04d7c57478a115779986260ecc519abc630ee0fe/backend/stream.go#L37

I started digging into the issue a little more. I found that there is support in the frontend datasource plugin sdk for passing data into the query with the `LiveChannelAddress` object that's passed to the `GrafanaLiveSrv.getStream` call, but the address is extracted from the initial query response to the backend and there appears to be no way to inject additional data.

https://github.com/grafana/grafana/blob/ba6d2f2a82ec5e515cdad7da9d666a51f03c5f17/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L361

The workaround right now is to capture the channel id from the `QueryData` call in my backend, store the request query arguments in a map, and then later rebuild the channel id in the `RunStream` to retrieve the arguments. This feels super hacky to me.

**What happened**:
There seems to be no way to pass query arguments to my backend `SubscribeStream` calls without having to re-implement `query` in fronted datasource plugin code.

**What you expected to happen**:
There should be an interceptor function (ie: `getStreamData`) in the frontend sdk class that allows me to inject additional stream argument data such as query parameters and configuration values.
 
**Anything else we need to know?**:
Related discussions: 
- https://github.com/grafana/grafana-plugin-sdk-go/issues/509
- https://github.com/grafana/grafana-plugin-sdk-go/pull/434

**Environment**:
- Grafana version: 9.3.1

**Comment by tolzhabayev** [comment]
@grafana/grafana-edge-squad please take a look

**Comment by tolzhabayev** [comment]
Might also be @grafana/multitenancy-squad (fyi @ArturWierzbicki)
