### ISSUE TITLE
Web: The 'scroll for more' icon is annoying, please remove it.

### ISSUE THREAD

**Issue by shezhangzhang** [grafana/grafana#60790]
**What happened**:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/26793777/209782818-12366b12-42cd-43e0-bf16-0a4aa7d7dd01.png">
It jumps (too big...) and prevents me from reading the document.

**What you expected to happen**:
remove it 

**How to reproduce it (as minimally and precisely as possible)**:
https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/
sidebar

**Comment by zuchka** [comment]
this might belong in another repo that manages our website but I will forward to docs team 👍

**Comment by shezhangzhang** [comment]
thank you very much！

**Comment by monster1612** [comment]
in the meantime, for anyone using uBlock Origin, I've found that this custom filter works perfectly to block the scroll prompt:

`grafana.com##.scroll-dark`

**Comment by osg-grafana** [comment]
This issue is captured in the `website` repo, so closing here as a duplicate. See https://github.com/grafana/website/issues/11199.

**Comment by shezhangzhang** [comment]
it's gone.
