### ISSUE TITLE
Template variable with / in the value string not working

### ISSUE THREAD

**Issue by raj2569** [grafana/grafana#6079]
Hi,

I am new to grafana and testing it with InfluxDB. I am able to create a graph and display it in dashboard successfully. I have created a template variable and adjusted my query to use the template variable. The value of template variable has a / in the name for example: gi1/4. The query I have given for the graph is:

`SELECT 8 * derivative(mean("ifHCOutOctets"),1s) AS "value" FROM switch_snmp."default".switch_snmp_ifHCOutOctets WHERE "ip" = '172.20.1.1' AND "instance" = $Interface AND $timeFilter GROUP BY time($interval) fill(none)
`

When I run this query, I get an error:

```
{
  "error": "error parsing query: found \\, expected ) at line 1, char 160",
  "message": "error parsing query: found \\, expected ) at line 1, char 160"
}

```
The query that was sent to server is:

`SELECT 8 * derivative(mean("ifHCOutOctets"),1s) AS "value" FROM switch_snmp."default".switch_snmp_ifHCOutOctets WHERE "ip" = '172.20.1.1' AND "instance" = (gi1\/3) AND time > now() - 30m GROUP BY time(2s) fill(none)`

char 160 corresponds to the` \ ` in `(gi1\/3)`. 

For testing I created another graph where the instance is hard coded and it is working perfectly, query is:

`SELECT 8 * derivative(mean("ifHCOutOctets"),1s) AS "value" FROM switch_snmp."default".switch_snmp_ifHCOutOctets WHERE "ip" = '172.20.1.1' AND "instance" = 'gi1/3' AND $timeFilter GROUP BY time($interval) fill(none)
`

I am using  Grafana v3.1.1 (commit: a4d2708)  with data from influx db 0.13.0

I feel there is some issue with the escaping when there is a `\` in the template variable.

**Comment by torkelo** [comment]
try `"instance" =~ /$Interface/ `
