### ISSUE TITLE
Expression unexpectedly changing field names of queries, duplicating them

### ISSUE THREAD

**Issue by Kveri** [grafana/grafana#60808]
I created a panel with three influxdb flux queries and named them accordingly:

backup_l1_power:
```
from(bucket: "default")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) =>
    r._measurement == "goodwe" and
    r._field == "backup_l1_power"
  )
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

backup_l2_power:
```
from(bucket: "default")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) =>
    r._measurement == "goodwe" and
    r._field == "backup_l2_power"
  )
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

backup_l3_power:
```
from(bucket: "default")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) =>
    r._measurement == "goodwe" and
    r._field == "backup_l3_power"
  )
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
```

The chart correctly shown legend: backup_l1_power, backup_l2_power, backup_l3_power. I was also able to see these field names in overrides > 'fields with name'.

Like so:
![image](https://user-images.githubusercontent.com/3380181/209893826-cc4e474c-84c0-4e30-8edc-f8f9c0b04096.png)

However when I created an additional math expression called 'A':
```
$backup_l1_power + $backup_l2_power + $backup_l3_power
```
**the field names of all queries changed to 'goodwe goodwe'**, 'goodwe' is the _measurement from influxdb, not the _field.

![image](https://user-images.githubusercontent.com/3380181/209893899-4263aec4-2462-4767-836f-1ee1b6c3a6bd.png)

Moreover Overrides now show a single field 'goodwe goodwe'. Basically all three series have now the same name.

I checked JSON > Panel data and it seems that series->fields->name is mapped to the correct name in the working scenario but is mapped to 'goodwe' in the non-working scenario. Attaching Panel data from both scenarios.

[Paneldata-nonworking.txt](https://github.com/grafana/grafana/files/10317286/Paneldata-nonworking.txt)
[Paneldata-working.txt](https://github.com/grafana/grafana/files/10317287/Paneldata-working.txt)

**Environment**:
- Grafana version: [v9.3.2 (21c1d14e91)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: influxdb v2 (flux)
- OS Grafana is installed on: Ubuntu 22.04
- User OS & Browser: Windows/Chrome
- Grafana plugins: none
- Others:

**Comment by Kveri** [comment]
I'm new to Grafana and I just learned that instead of using math expression I can use transformation to add total which doesn't have this issue. But I still think the math expression shouldn't change the field names. Please close the bug in case I'm wrong. Thanks

**Comment by Kveri** [comment]
Another update: if I add |> drop(columns: ["_measurement"]) it seems Grafana will again correctly detect the series name. Why is Granafa using _measurement as series name and sometimes _field?

**Comment by zuchka** [comment]
Thanks for creating this issue, @Kveri 

I'm glad you figured out that transformations will work. they are better at manipulating data in panels. Expressions are mostly used for the alerting platform and they perform maths on the server-side, while transformations are client-side.

All that said, I still can't say why expressions behave the way you describe
