### ISSUE TITLE
Grafana managed alerts are not delivered to Mimir Alertmanager in multi-tenant mode

### ISSUE THREAD

**Issue by sakthiraam** [grafana/grafana#60807]
**What happened**: 
Grafana Managed alerts are not delivered to Mimir Alertmanager. We have enabled Grafana Unified alerting and configured a Grafana managed alert.
The admin page of the Grafana managed is configured to send alerts to external Alertmanager, in our case it is Mimir Alertmanager and multi-tenancy is enabled.
Alertmanager data source implementation is selected as Mimir, the health check of the data source is fine, we are able to configure  contact points and notifications policy and it’s getting uploaded to the respective tenants.

Upon checking the Grafana logs we see Grafana is trying to do a POST request to Mimir Alertmanager on /api/v2/alerts and resulting in HTTP 404. 
We further analysed and found the Mimir Alertmanager exposes the V2 api endpoints on /alertmanager/api/v2/alerts. So we need Grafana to include the /alertmanager to the URI when it’s trying to post the request to Mimir alertmanager.

We tried to include /alertmanager to the alertmanager url in the datasource configuration and upon saving changes we are getting warning stating “It looks like you have chosen a Mimir or Cortex implementation , but detected a Prometheus endpoint.Please update the implementation and try again”.

The change helps to include the /alertmanager to the URI but results in HTTP 401 as we suppose http header is excluded in the POST request sent to Mimir alertmanager.

**What you expected to happen**:

Grafana managed alerts gets delivered to Mimir alertmanager on the correct endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

Configure Mimir alertmanager as alertmanager datasource in Grafana with implementation selected to Mimir.
Enable the Receive Grafana alerts options in the datasource.
Configure X-scope-orgid header
Define contact points and notification policy using Grafana UI.
Navigate to admin page of alert rules and set the “Send alerts to” under External alertmanagers to Only External or Both.
Configure a Grafana alert and verify the logs of Grafana once the alert is moved to Firing state.

**Anything else we need to know?**:

We went one step further and removed the tenancy and post which we see alerts are getting delivered to Alertmanager but it’s not following our tenant specific contact points and notification policies instead using the mimir fallback alertmanager configuration which is kind of expected.

The removal of tenancy also results in contact points and notification policies getting a JSON response instead of YAML configuration.

We had a discussion in Grafana Slack Mimir channel and the link to the discussion is as below https://grafana.slack.com/archives/C039863E8P7/p1671787647315839

I’m unable to add screenshots please refer to support ticket 74646.

**Environment**: 
- Grafana version:  9.3.1 (Enterprise)
- Data source type & version: Alertmanager (Mimir) & 2.5.0
- OS Grafana is installed on: RedHat Linux 8 (UBI 8 image)
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by mellieA** [comment]
@sakthiraam there is an update to our documentation for configuring an external alertmanager starting in 9.2, have you tried these steps? 

> https://grafana.com/docs/grafana/latest/alerting/set-up/configure-alertmanager/#add-an-external-alertmanager
> 
> Note: Starting with Grafana 9.2, the URL configuration of external alertmanagers from the Admin tab on the Alerting page is deprecated. It will be removed in a future release.
> 
> External alertmanagers should now be configured as data sources using Grafana Configuration from the main Grafana navigation menu. This enables you to manage the contact points and notification policies of external alertmanagers from within Grafana and also encrypts HTTP basic authentication credentials that were previously visible when configuring external alertmanagers by URL.
> 
> To add an external Alertmanager, complete the following steps.
> 
> Click Configuration and then Data sources.
> Search for Alertmanager.
> Choose your Implementation and fill out the fields on the page, as required.
> Note: Prometheus, Grafana Mimir, and Cortex implementations of Alertmanager are supported. For Prometheus, contact points and notification policies are read-only in the Grafana Alerting UI.
> 
> Click Save & test.

**Comment by yuri-tceretian** [comment]
I think there is a problem on our side: when user creates a data source of type Alertmanager and chooses mode "Mimir", the feature "send alerts to external Alertmanager" does not work because Mimir Alertmanager hosts Alerts API by path `/alertmanager`. But if user adds that segment, the configuration UI stops working because data source is treated as Prometheus and therefore all configs are read-only. 

I think this is a bug, and we should check the type of the data source and automatically add the segment `/alertmanager` to the URL during configuration of sender to external Alertmanager

**Comment by yuri-tceretian** [comment]
I have re-read the issue description and identified another problem - the sending to the external Alertmanager with Mimir Implementation in multi-tenant mode does not work because the client does not append header `X-SCOPE-ORGID` (see https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/ for details).

**Comment by JohnnyQQQQ** [comment]
The headers configured in the datasource configuration are now also used when executing requests.
