### ISSUE TITLE
FeatureReq: Graph 'Sticky' Hovers 

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6081]
- **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options

the hover is very useful for analysis situations, what would be even better, would be some way to make the hover line/data sticky by double-click or something to make sticky say 2/3/4/5/6/ hover blobs as a way to describe a situation seeing the values in the hover blobs

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
