### ISSUE TITLE
[Feature Req]: Extend auth.proxy feature

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#6083]
- **I'm submitting a ...**
- [X ] Feature request

Please include this information:
- What Grafana version are you using? 3.1.1

I've been using the auth.proxy and it works just fine but I would like to have the functionallity extend/change the abit to match our needs.
In short username and email isn't the same and it sure would be nice to have the name set also.

From:

```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```

to:

```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
header_email_name = X-WEBAUTH-EMAIL
header_email_property = email
header_full_name = X-WEBAUTH-NAME
header_full_property = fullname
auto_sign_up = true
```

With the default, if a specific header isn't set, to header_property. Aka same as today.
(no changes needed for those that using auth.proxy today)

**Comment by huseyinkozan** [comment]
Is it possible to add X-WEBAUTH-ORG for default organization ?

**Comment by vganjare** [comment]
@ torkelo,

Is this functionality added to grafana?

Thanks,
Vishal

**Comment by cantino** [comment]
`X-WEBAUTH-ORG` would be very helpful.

**Comment by UXabre** [comment]
Hi, I'm working on a patch that works on X-WEBAUTH-ORG aspect:
https://github.com/grafana/grafana/pull/33162
This patch has the ability to provide a list of organizations that should be assigned to this user and implies that the first ID listed is the default org as well.
Please have a look and feel free to comment any improvement on that subject :-)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
