### ISSUE TITLE
Epic: Cover more areas with e2e tests

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#60848]
To help Grafana admins upgrade with confidence, we want to increase the coverage of e2e tests.

Remove 1 remaining Enzyme test.

To do: define prioritized list of e2e tests.

**Comment by yaelleC** [comment]
Remove last enzyme test too: https://raintank-corp.slack.com/archives/C02FLGJJEG4/p1673003127568209

**Comment by tolzhabayev** [comment]
It may be a good idea to start thinking about killing the unmaintained https://github.com/grafana/grafana/tree/main/packages/grafana-e2e wrapper in favour of a couple of helper / utility functions ([example of how it could look like](https://github.com/grafana/grafana/issues/45594))
