### ISSUE TITLE
BarGauge: visualization problem when result is one

### ISSUE THREAD

**Issue by albertollamaso** [grafana/grafana#60859]
**What happened**:

When using a BarGauge type visualization and the return value is **one** element then it is not showing the label of the element.

**What you expected to happen**:

Even when returning one element the label show be displayed.

**Examples**:

Example of returning more than one element and showing labels properly:

![image](https://user-images.githubusercontent.com/5437164/210107331-d321da78-6454-4702-8037-44c45fc6f091.png)

Example of returning one element without showing the label(the issue reporting):

![image](https://user-images.githubusercontent.com/5437164/210107365-26fff883-44c2-40d8-a745-bf31ede37a91.png)

**Environment**:
- Grafana version: v9.2.4
- Data source type: Prometheus

**Comment by mellieA** [comment]
I was able to reproduce this with the TestDB Datasource and a single metric value for one series

<img width="1660" alt="Screenshot 2023-01-04 at 5 58 31 PM" src="https://user-images.githubusercontent.com/18175287/210678197-a7aef0aa-491e-4f33-b2a4-88a939d3997e.png">

Add a second metric value to the series and the label appears


<img width="1663" alt="Screenshot 2023-01-04 at 5 58 48 PM" src="https://user-images.githubusercontent.com/18175287/210678233-addd7e29-6c9c-4ded-b6d9-5969d293bf64.png">

**Comment by JoaoSilvaGrafana** [comment]
Hi @albertollamaso thanks for raising this! I can reproduce it, but based on the code it seems to be deliberate for "Gauge", "Bar Gauge" and "Stat" panels. There is a work around for it, if on the panel settings you go to "Standard options" > "Display name" and set it to this `${__field.name}` it will actually force the name to be displayed.

If you tell me this workaround works for you, I will close this issue, as a full solution would have to involve adding an extra panel option which might be overkill.

**Comment by JoaoSilvaGrafana** [comment]
Hmm that is strange. Even if it didn't display the correct thing it should've displayed something.
Here is a dashboard where I got it to work with `${__field.name}` for the grafana test db and with `${__series.name}` for prometheus (might be worth trying that second variable): https://play.grafana.org/d/Yt9VWGh4k/60859-bargauge-visualization-problem-when-result-is-one?orgId=1

Is there any chance you could share a sample dashboard json with the __field.name or __series.name failing?

**Comment by JoaoSilvaGrafana** [comment]
I've updated that dashboard with a new prometheus panel, which uses the transformation "Labels to fields" and then also uses `${__field.name}` to extract the `severity` value from `{__name__="ALERTS", alertname="KubeletDown", alertstate="firing", severity="critical"}`. You could do something similar to extract the `image` value. Let me know if that works!

<img width="1492" alt="Screenshot 2023-01-05 at 19 16 38" src="https://user-images.githubusercontent.com/100691367/210862247-605a30bc-d203-401d-b6b3-50016f2dd6c3.png">

**Comment by albertollamaso** [comment]
@JoaoSilvaGrafana that worked like a charm. Much appreciated your help.
