### ISSUE TITLE
Feature Request: Alerting: Increase tag length beyond 100 characters

### ISSUE THREAD

**Issue by heldersepu** [grafana/grafana#60851]
**What happened**:
Adding long tags to an alert causes error,
`"{"message":"Failed to save dashboard"}"`
Found that the max it will allow is 100 Characters

**What you expected to happen**:
Proper error message relevant to long tags and UI validation preventing to enter tags longer than max
To me 100 is very small, our plan was to put there a url there but is too long, maybe 400 will be more appropiate 

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with an alert and add a really long tag over 100 characters

**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/release-8.4.7/pkg/services/sqlstore/migrations/tag_mig.go
`{Name: "value", Type: DB_NVarchar, Length: 100, Nullable: false},`

**Environment**:
- Grafana version: AWS managed Grafana 8.4.7
- Data source type & version: 
- OS Grafana is installed on: AWS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by taleena** [comment]
Hey all - the customer who initially reported this error is still looking for this fix. We do see the validation/error messaging was done in another PR. Do we have an ETA for this one?
