### ISSUE TITLE
MQTT datasource and variables

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#60862]
**What happened**:
I have tried using several syntax but it seems that it's not possible to use variables as topic

**What you expected to happen**:
That variables can be used as for in all others data sources. This can help a lot and make the dashboard much much more flexible.

Environment:
- Grafana version: 9.3.2
- Data source type & version: mqtt
- OS Grafana is installed on: qindows 11
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@DonatoD there is an enhancement request for this feature here https://github.com/grafana/mqtt-datasource/issues/28
