### ISSUE TITLE
Limit Transform shows the oldest rows by default 

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#60861]
**What happened**:
Using the Limit transform, the new data are deleted while the old ones are kept. In this way this transformation is is not usable (or at least I cannot imagine a real situazione where old data are needed rather that the new ones)

**What you expected to happen**:
That just the N new data are kept, while the old ones are deleted. The best thing could be to insert a new control that allow to decide which data to keep: new or old 

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: mqtt
- OS Grafana is installed on: qindows 11
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
I was able to reproduce this with a table panel and timestamped data. I tried sorting by clicking on the header name for time and it will only change the sort order of the 10 oldest rows. 

Workaround: 

1.  Combine this with the sort transform, you can choose which field to sort by (click reverse to reverse the sort)
2. Add the limit transform BELOW the sort and the top N sorted entries are kept

![Screenshot 2023-01-04 at 4 41 13 PM](https://user-images.githubusercontent.com/18175287/210670806-49ca68e2-94c0-4203-acb1-d8321d249f8f.png)

**Comment by mellieA** [comment]
If this is expected behavior, could we update to our docs to suggest combining the **limit** transformation with the **sort by** transformation or add it to the tooltip? 

If you click the **i** tooltip, the link takes the user to the 8.5 grafana docs even though it's set to `latest` because the URL location has changed in the new docs: 

8.5
https://grafana.com/docs/grafana/latest/panels/transformations/?utm_source=grafana 

Latest: 
https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/

**Comment by DonatoD** [comment]
Hi thanks. Yes teorichally this is the solution. Practically it doesn't work. If I put this transformations, after just a few data it stops receiving mqtt payloads, while I can still see them pass through the mqtt server. So there is something that doesn't seem to work properly. I made several test and when I delete this transformation it works great, I even tried with cleaning the cache, it is always the same

**Comment by mellieA** [comment]
@DonatoD can you share what the query request/response looks like Developer Tools of your browser (network tab) before/after it stops getting new query results?

**Comment by DonatoD** [comment]
Hi @mellieA, I was able to reproduce this behaviour.
the problem is that I need to set a refresh interval for the full dashboard because I have other panels that directly query to a mysql database.
Now, if I set to off the dashboard refresh interval, everything works quite well as expected. But If for example I set it to 5 second, then mqtt works just fine for the first 5 seconds, until the refresh. Then it stops working

**Comment by mellieA** [comment]
@DonatoD Thank you for creating the videos, that will really help us to understand better what might be happening here.

**Comment by oscarkilhed** [comment]
sorting and limiting works with the streaming test datasource. Could be an issue specific to the MQTT data source. However, sorting a streaming data source over and over could be resource intensive. Maybe a `tail` transformation that uses `array.slice()` would be useful in this scenario.
