### ISSUE TITLE
Profiling: Y-axis is showing the wrong units for CPU

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#60871]
**What happened**:
 Y-axis is showing the wrong units for CPU
I think this happens when I switch from one kind of profile to another.

**What you expected to happen**:
The Y-axis to change when selecting a new type of profile

**How to reproduce it (as minimally and precisely as possible)**:

Select memory profile then switch to CPU.

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/1053421/210228246-0b6ff11b-f7ca-4844-bc42-7e0212eb0c25.png)

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

cc @aocenas @joey-grafana

**Comment by CrypticSignal** [comment]
I have moved this issue to @grafana/explore-squad's board as this is an issue with the [ExploreGraph component](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Graph/ExploreGraph.tsx).
Internal users can read [this](https://raintank-corp.slack.com/archives/C023A30M3S7/p1674658878689549) Slack thread for context.
cc @Elfo404
