### ISSUE TITLE
I Would like to know how Grafana table panel can draw a line in each row 

### ISSUE THREAD

**Issue by DanielFRocha** [grafana/grafana#6088]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Zabbix 2.4.6
- What OS are you running grafana on? CentOS 7.1

Hi, 
I Would like to know how Grafana table panel can draw a line in each row 

I have a Table like that:

![image](https://cloud.githubusercontent.com/assets/6033757/18686126/2f185988-7f51-11e6-833a-390070f6f32c.png)

Each Row is a String how can I use HTML Sanitizer to Treat each row as in a real grafana Row type so I can use the sort use the tab like the picture.

![image](https://cloud.githubusercontent.com/assets/6033757/18688380/8c316192-7f5a-11e6-910f-8a9b9ac22a64.png)

thanks in advance.

**Comment by torkelo** [comment]
> Each Row is a String how can I use HTML Sanitizer to Treat each row as in a real grafana Row type so I can use the sort use the tab like the picture.

I do not understand this. Your row is a string? 

Please direct questions to the mailing list :)

**Comment by DanielFRocha** [comment]
Hi Torkelo,
Thanks for Answering.

Could you provides me the e-mail list?

Yes each column is a Zabbix Query.

![image](https://cloud.githubusercontent.com/assets/6033757/18709010/33aae0f0-7fd4-11e6-8a0b-daa14332f477.png)

Each row is a String Sanitize HTML:

![image](https://cloud.githubusercontent.com/assets/6033757/18709141/f35a3c0c-7fd4-11e6-8422-5ac9d56b8928.png)

I would like to know how to programming my scripts to so as I can sort like this:

![image](https://cloud.githubusercontent.com/assets/6033757/18709445/92a4afa8-7fd6-11e6-91bf-8c388610646c.png)

And for instance a line to divide each row.

Thanks in advance and sorry for posting in the wrong place.

**Comment by torkelo** [comment]
if you go to grafana.org, Support in the top menu, 

http://grafana.org/support/

It has some links to possible support options, one is the mailing list

**Comment by DanielFRocha** [comment]
Thanks Torkelo !
