### ISSUE TITLE
Unable to set vertical gradient severity color for bar chart

### ISSUE THREAD

**Issue by vahaldor** [grafana/grafana#60886]
**What happened**:
Unable to set vertical gradient severity color for bar chart. The whole bar takes the color of its maximum value, instead of showing a gradient from the bottom.

**What you expected to happen**:
That the gradient will apply on each bar from the bottom to the value the bar achieves, therefore I will be able to see how sever was energy consumption on each day along with severity gradent. 

**How to reproduce it (as minimally and precisely as possible)**:
Just use gradient severity color on bar chart.

**Anything else we need to know?**:
Changing between time series and bar chart shows it quite clearly, as here:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/6329152/210316225-09de88da-c644-4553-bce8-2d91db74d4e4.png">

We discussed it [here](https://community.grafana.com/t/creating-opacity-color-scheme-based-on-severity/78594/6).

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: InfluxDB 4.5.0 
- OS Grafana is installed on: as an addon on supervised home assistant v12.9 2022
- User OS & Browser: OSX and w11, browser Edge, last version
- Grafana plugins: 
- Others:

**Comment by mellieA** [comment]
@vahaldor is an intentional change made in https://github.com/grafana/grafana/pull/58285
