### ISSUE TITLE
legend issue with movingAverage inside groupByNode

### ISSUE THREAD

**Issue by jimpriest** [grafana/grafana#6090]
I'm submitting a ...
- [x] Bug report

Please include this information:
- What Grafana version are you using?  3.x
- What datasource are you using? graphite
- What OS are you running grafana on? RHEL
- What did you do?  Trying to use movingAverage with groupByNode
- What was the expected result?  legend with normal entries
- What happened instead? the legend appears to display artifacts from movingAverage

metric: groupByNode(movingAverage(collectd.com.myhost.$env.mysql*_*_myhost_com.load.load.*, 7), 9, 'sum')

In the legend I see:

![selection_001](https://cloud.githubusercontent.com/assets/197930/18717399/c24afbec-7fed-11e6-9f8a-4d8723887088.png)

I can work around this by wrapping everything with an aliasByNode(0)

**Comment by torkelo** [comment]
groupByNode is processed in graphite so this is graphite issue, please search the graphite github repository for existing issues, might have already been reported and fixed. 

https://github.com/graphite-project/graphite-web
