### ISSUE TITLE
Null value are shown as zero, inspite in Display selected Null value to Null

### ISSUE THREAD

**Issue by ssenthil416** [grafana/grafana#6091]
* **I'm submitting a ...**
- [* ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 
1.3.1
- What datasource are you using? 
mqe-datasource
- What OS are you running grafana on?
linux
- What did you do?
Executed query for cpu total usage idle for some hosts, which does not exists before
- What was the expected result?
It need to show null entry for the days it does not exists
- What happened instead?
It show zero vaule

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see 
<img width="1269" alt="screen shot 2016-09-21 at 3 24 34 pm" src="https://cloud.githubusercontent.com/assets/16314149/18727375/4bdd4cac-8016-11e6-92e5-255ebcf2a21e.png">
<img width="877" alt="screen shot 2016-09-21 at 3 56 39 pm" src="https://cloud.githubusercontent.com/assets/16314149/18727374/4bc67590-8016-11e6-9c5b-dad35999afdc.png">

metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
I am unable to replicate it with other datasources, maybe it's  a problem in the mqe datasource?
