### ISSUE TITLE
Microsoft Teams "webhook failed validation"

### ISSUE THREAD

**Issue by wymangr** [grafana/grafana#60924]
**What happened**: 

I’m having an issue starting at around noon EST today with Grafana sending alerts to Microsoft Teams channels. When an alert gets triggered, it’s spamming the channel with ~15 alerts, waiting a little bit and spamming with more alerts. This has been setup and working for a long time now. I was on Grafana version 9.2.4 and I’ve updated to version 9.3.2 and still having the same problem. Looking at the Grafana logs, I’m seeing this:

```
Failed to send test alert.: send notification to Teams: webhook failed validation: {"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}
```

In that error message it says that the status code was 200 and that isSuccessStatusCode is true. It also says that it failed to send the alert, however the alert comes trough. I’m guessing Grafana for some reason is not able to validate, it sends the notification, Grafana thinks it failed and then tries again? I have Grafana setup in a docker container and I’ve tried upgrading, restarting the container, restarting the VM, and creating new webhooks. I’m unable to fix the issue.

I’ve also tried to send a test notification from the contact point inside the Grafana gui and get the same error, but again the alert comes into my Teams channel.

**What you expected to happen**: Grafana to send 1 alert to Microsoft Teams and be able to validate that it sent successfully.

**How to reproduce it (as minimally and precisely as possible)**: Trigger alert or send a test notification from a contact point.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4 & 9.3.2
- Data source type & version: All Data Sources 
- OS Grafana is installed on: Docker on Centos 7 VM
- User OS & Browser: Windows 10  / Chrome
- Grafana plugins: 
- Others:

**Comment by wymangr** [comment]
Looking through the code, it looks like the issue is in the following function:
https://github.com/grafana/alerting/blob/main/alerting/notifier/channels/teams.go

```
func validateResponse(b []byte, statusCode int) error {
	// The request succeeded if the response is "1"
	// https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-messages-using-curl-and-powershell
	if !bytes.Equal(b, []byte("1")) {
		return errors.New(string(b))
	}
	return nil
}
```

It looks like the function is expecting the body of the response to be "1", but running the curl command it's returning this:

```
$ curl -H 'Content-Type: application/json' -d '{"text": "Hello World"}' https://secretwebhookurl.com
{"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":
```

I think a longer term fix might look something like this?

```
func validateResponse(b []byte, statusCode int) error {
	if !bytes.Equal(b, []byte("1")) {
		return errors.New(string(b))
	} else if statusCode != 200 {
		return errors.New(statusCode)
	}
	return nil
}
```
But my question is, is there a quick fix to get me back up and running? Right now my alerts are basically broken.

**Comment by mellieA** [comment]
@wymangr that change looks like it was made recently, there were also some recent changes in the past few months to add support for adaptive cards. 

I don't have a quick workaround or fix for you, but I'll move this to the alerting squad to take a look

**Comment by kompa3** [comment]
We have had the same kind of behavior starting on 3rd Jan when sending alerts from Zabbix (not Grafana) to Teams.
Maybe Teams has changed somehow yesterday?

**Comment by kompa3** [comment]
> We have had the same kind of behavior starting on 3rd Jan when sending alerts from Zabbix (not Grafana) to Teams. Maybe Teams has changed somehow yesterday?

Actually, there was the same kind of error handling that seems to be case with Grafana. So my best guess is that Teams has updated and changed their response body:

```
    if (response === '1') {
        return 'OK';
    }
    else {
        Zabbix.Log(3, '[ MS Teams Webhook ] FAILED with response: ' + response);
        throw response;
    }
```

**Comment by mattimo** [comment]
FWIW, according to [this comment](https://github.com/MicrosoftDocs/msteams-docs/issues/7830#issuecomment-1379256644) in the ticket for the Teams documentation the changes will be rolled back, so perhaps there may not be any action required here.

**Comment by wymangr** [comment]
That's good news! If they do end up rolling back fixing this issue, it might be worth still making a change to the logic so it doesn't care about what the response is so if Microsoft decides to make changes in the future it doesn't break again. Maybe just checking the status code as a confirmation?

**Comment by kompa3** [comment]
> FWIW, according to [this comment](https://github.com/MicrosoftDocs/msteams-docs/issues/7830#issuecomment-1379256644) in the ticket for the Teams documentation the changes will be rolled back, so perhaps there may not be any action required here.

Thanks for the info!!

**Comment by mubarizrahimi** [comment]
It seems to be working again !

**Comment by Wireheadbe** [comment]
Hi @armandgrillet - we see an HTTP status code of "207" when we post via a webhook to Teams. The message is delivered, but grafana still says "webhook failed validation". Thus in turn causing notifications to be repeated every 5 minutes. Is there a way to circumvent this?
