### ISSUE TITLE
Include a llink shortener when sharing dashboards/graphs

### ISSUE THREAD

**Issue by akrzos** [grafana/grafana#6092]
I am not sure if it has been requested yet but a link shortener when sharing dashboards or graphs would be handy as some of our dashboards have a lot of variables and the link gets very long.
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1
- What datasource are you using? Graphite
- What OS are you running grafana on? RHEL / Centos
- What did you do? Share links to my dashboards and graphs
- What was the expected result?
- What happened instead? 

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by daniellee** [comment]
Implemented: 
- https://grafana.com/docs/grafana/latest/explore/#share-shortened-link
- https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v7-3/#shorten-url-for-dashboards-and-explore

**Comment by daniellee** [comment]
Ref #27409
