### ISSUE TITLE
Dashboard Versions table shows userId in "Updated by" Column

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#60935]
**What happened**:
When viewing the version history for a dashboard, the "Updated by" column only shows userId:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/41969079/210442793-13baccd9-e000-4662-9f62-3ab787775a11.png">

**What you expected to happen**:
This column should show the user's email, username, or both instead.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open any dashboard (or create a new one and save it)
2. Click the settings cog and view version history
3. Observe the 'Updated by' column

**Environment**:
- Grafana version: 9.4.0-47064pre

**Comment by natellium** [comment]
Note: currently the API only returns user ID.
