### ISSUE TITLE
Piechart proportion changes on resize

### ISSUE THREAD

**Issue by panda-1token** [grafana/grafana#60937]
**What happened**:  the proportion of pie is shown as wrong in the dashboard, but when I view the pie in detail, the proportion turns to correct.

**What you expected to happen**: the proportion of pie should be correct in the dashboard view.

**How to reproduce it (as minimally and precisely as possible)**: create the same data shown in the gif

**Anything else we need to know?**:
![img_v2_1cc82ca5-b01d-4132-8c6f-4a5305325f6g](https://user-images.githubusercontent.com/50096879/210479676-a6a6e31c-b93e-4112-8033-d461ab4f1540.gif)

**Environment**:
- Grafana version: 9.2.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: macOS chrome
- Grafana plugins:
- Others:
-

**Comment by mellieA** [comment]
@panda-1token can you use the new *Get Help* feature on the panel to create a shareable version of the dashboard with randomized data? Then, if you will please upload it to this ticket we can take a look. 

<img width="338" alt="Screenshot 2023-01-04 at 6 19 56 PM" src="https://user-images.githubusercontent.com/18175287/210681612-0727da6f-2764-4694-8325-c505dfb457a2.png">

**Comment by mellieA** [comment]
duplicate of https://github.com/grafana/grafana/issues/59007 (but that one is closed, so we can work here)

**Comment by panda-1token** [comment]
not duplicate of https://github.com/grafana/grafana/issues/59007. they are different.

**Comment by panda-1token** [comment]
https://github.com/grafana/grafana/issues/59007 is the proportion in pie is smaller than data. But this issue is that the proportion of multiple items use the same color.

**Comment by panda-1token** [comment]
This issue is not shown now. It looks like an occasional issue. I will provide more info when it happens again. And can you reopen https://github.com/grafana/grafana/issues/59007, I have provided more info at that issue.

**Comment by panda-1token** [comment]
hi, it happens again. Here is our exported data.
[CurrentCoin View (USD)-data-as-joinbyfield-2023-04-09 08_39_41.csv](https://github.com/grafana/grafana/files/11185076/CurrentCoin.View.USD.-data-as-joinbyfield-2023-04-09.08_39_41.csv)
![img_v2_c88550a0-4721-4b74-93a2-a95eab2423bg](https://user-images.githubusercontent.com/50096879/230763361-8ed970d8-9d70-410f-8535-0fcb838cd59b.jpg)
![img_v2_075c6d25-d649-48fd-b528-b88673f6465g](https://user-images.githubusercontent.com/50096879/230763364-cace60b3-3721-497f-b57a-e17df94e1927.jpg)

https://user-images.githubusercontent.com/50096879/230763371-9562eb52-f21a-444f-ae6f-7912be0401c9.mp4

when the pie is small, it seems using the same color for different proportions. And when the pie turns big, it uses different colors for different proportions, which is expected.

**Comment by panda-1token** [comment]
hi, it happens again. Here is our exported data.
[data.csv](https://github.com/grafana/grafana/files/11185085/data.csv)

![correct](https://user-images.githubusercontent.com/50096879/230764390-78d33232-80a5-437d-9e1b-af10e2f3fca8.png)
![wrong](https://user-images.githubusercontent.com/50096879/230764394-f40ac2d1-b192-4aed-8359-21e75e70c062.png)

when the pie is big, it shows correct data label when the mouse hangs in. But when the pie is small, it shows wrong data label.

**Comment by zoltanbedi** [comment]
Thanks @panda-1token I was able to reproduce the issue.

https://user-images.githubusercontent.com/13729989/231988789-8028aaf6-a74c-42a8-ab6f-3791324ad0a7.mov

**Comment by supilee** [comment]
@panda-1token are you still seeing this with the newest version out there?

**Comment by supilee** [comment]
@panda-1token Verified locally and in play. everything works as expected. If the issue occurs again please reopen this one.

**Comment by zoltanbedi** [comment]
@supilee I still see this issue on play. Can you show a dashboard where it works for you?

**Comment by supilee** [comment]
thanks for the point. I see it too now. i used a smaller dataset with which it worked as expected..
