### ISSUE TITLE
grafana 3.1.1 log format different than 3.0.4

### ISSUE THREAD

**Issue by larsf** [grafana/grafana#6093]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

In 3.0.4 logging to file used this format:
2016/09/20 11:01:32 [I] Completed 10.250.50.23 admin "GET /login HTTP/1.1" 302 Found 24 bytes in 3810us

in 3.1.1 we are now seeing:
t=2016-09-21T17:35:27-0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import status=500 remote_addr=10.10.10.73 time_ns=53ns size=0

which seems consistent with log15's LogFmtFormat

I would like to retain the "syslog" type output in the log file. We only have enabled log mode == file in the ini file.

Is there a way to restore the old behavior?

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
This was mentioned as a breaking change, You can enable syslog writer (the writes to syslog), you can  also change to a more readable console output format,  it's in the config docs
