### ISSUE TITLE
Breakdown of all service in a server

### ISSUE THREAD

**Issue by yuvarajanlga** [grafana/grafana#6094]
Hi Team,

could you please let me know, how to achieve the below 

How to calculate the breakdown % of all service in a server

In a server lets say i am monitoring below service
1. ping
2. http service
3. some port
4. disk space

if there is no problem in my server. then the  breakdown result of the server is 100%
if there is any problem lets say in ping, the breakdown result would be like 96.7%

thanks in advance.

**Comment by torkelo** [comment]
Please open  questions in the mailing list, also you need to provide what time series store you have and the metric you want to use in your query.
