### ISSUE TITLE
Elasticsearch Fields  values was truncated in Templating and graph panel.

### ISSUE THREAD

**Issue by liuguoshun** [grafana/grafana#6095]
* **I'm submitting a ...**
- [ ] Bug report
(http://grafana.org/support/)
Please include this information:
- What Grafana version are you using?
3.1.1

- What datasource are you using?
elasticsearch-2.4.0

- What OS are you running grafana on?
linux 6.5

- What did you do?
Templating:
    {"find": "terms", "field": "DBname"}

- What was the expected result?
In Templating:
    the Preview of values (shows max 20):
    "DBname" is "rm-2zejkbq6", 
    or chinese characters like "你好".

- What happened instead?
In Templating:
    the Preview of values (shows max 20):
    only got a name : "rm".
    chinese characters only got name "你".
And so does in graph panel as an legend options.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
It is Elasticsearch that does this on analyzed fields. 

Consult elasticsearch docs on terms aggregation :) 

But the quick fix is to update your elasticsearch index mapping and disable analyzing on the field
