### ISSUE TITLE
Angular Unknown Provider error when use Template Variables

### ISSUE THREAD

**Issue by miry** [grafana/grafana#6096]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

v4.0.0-pre1 (commit: 6257ae0) 

- What datasource are you using?

ElasticSearch and InfluxDB

- What OS are you running grafana on?

Linux Centos via Docker container grafana/grafana:master

- What did you do?

Recently updated (do update weekly) and exists dashboard does not work. I see green notification 

```
{}
true
```

In web inspector console:

```
Error: [$injector:unpr] Unknown provider: aProvider <- a(…) true
```

- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
thanks for reporting this! fixed in next nightly (should be built within 10min)
