### ISSUE TITLE
OpenTSDB Templating unable to select pipe option

### ISSUE THREAD

**Issue by Jason-field** [grafana/grafana#6097]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1 (Latest Docker Image)
- What datasource are you using? - OpenTSDB
- What OS are you running grafana on? - Debian 8

Since the latest update (I was previously on 2.6) I can no longer select the pipe option when templating which breaks my custom types, I can modify these options in the json and reupload the dashboard 
![templating](https://cloud.githubusercontent.com/assets/4923914/18741070/1000fc6c-80a5-11e6-975d-dbb4b1d8d0f8.PNG)
![templatingjson](https://cloud.githubusercontent.com/assets/4923914/18741090/2db97680-80a5-11e6-8772-a2270bfb90f2.PNG)

Thank you,

Jason

**Comment by torkelo** [comment]
the pipe format is specified by the caller that wants interpolation done. So in the OpenTSDB code the piep format is used to interpolate tags and filters

https://github.com/grafana/grafana/blob/v3.1.1/public/app/plugins/datasource/opentsdb/datasource.js#L401

So templating should be working as before in 3.1.1 . 

Can you show how you are using the variable?
