### ISSUE TITLE
google static charts drawing bug? Still don't know...

### ISSUE THREAD

**Issue by esmeralda7** [grafana/grafana#6098]
Hi all,
I'm using grafana 3.0.2 on debian lenny. I created a simple html panel on a grafana dashboard.
I'm trying to visualize a simple pie chart using the following google code (pie chart):
Now this works. But the piechart gets drawn only once, then it disappears and if i reload the dashboard it doesn't get visualized again. 
I'm not sure whether this is a bug or else. Could anyone help me out? I'll attach the code within a txt file.

Thanks

E

[piechart.txt](https://github.com/grafana/grafana/files/486889/piechart.txt)

**Comment by torkelo** [comment]
please use the mailing list for questions. 

Since your using custom stuff in a html panel, it's not a bug in Grafana :)

**Comment by esmeralda7** [comment]
thanks for your quick reply!

E
