### ISSUE TITLE
Grafana v4 UX Improvements

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6099]
A few ideas for possible improvements:
- New User Flow / Experience 
  -  [ ] Mock Up Ideas 
- Improve Dashboard Building Experiance
  -  [ ] Mock Up Ideas
- How to make Templating More Accessible 
  -  [ ] Mock Up Ideas
- New Login Page Design
  -  [ ] Mock Up Ideas
- Navigation dropdown from top menu bar
  -  [ ] Just do it

**Comment by evanrich** [comment]
One thing that might be nice to see, not necessarily in this project, is a Dashboard editor...right now If I want to change something en-mass, I need to copy out the XML, edit it, and then past it back in (say change colors on all series).  would be nice if there was a tool to do this easier, or if the UI editor allowed this, would be a lot quicker

**Comment by Kaacz** [comment]
Will be good to have on top button moving directly to Home dashboard. :)

**Comment by pavleec** [comment]
For the Dashboards navigation improvement it would be great to have a tree-like structure navigation. If you have more then 20 dashboards defined navigation via search or tags only is not realy user friendly.

**Comment by torkelo** [comment]
When saving new dashboard (with default title), the Save As dialog will now be shown giving the user an opportunity to set name without going into dashboard settings.

**Comment by eproxus** [comment]
One particular gripe I have with dashboard building is the focus on rows and cells. I'd like a more grid-like system that would create rows and cells automatically as you move panels around. Some annoying examples:

* You cannot easily add a panel to a row by dragging and dropping
* You cannot move a panel to a temporary space when reordering
* You cannot resize a panel with the mouse
* You cannot move a row with the mouse

I think a more flexible grid system would solve this, where panels would snap to rows (existing or new ones at the bottom) and would autoresize between themselves inside a row. It would also be cool to allow even for a panel to span multiple rows.

**Comment by mattttt** [comment]
@eproxus Agreed, and has been a large part of the conversations between myself and @torkelo while in Stockholm this week. More to share on this soon, but we're not at the point of being able to overhaul the grid quite yet.

That said, I did want to clarify one bit - you can currently resize a panel with the mouse:
![resizepanelwithmouse](https://cloud.githubusercontent.com/assets/2886187/19763452/59e3d28c-9c3e-11e6-9a62-2bd54fe60d61.gif)

**Comment by eproxus** [comment]
@mattttt Oh, didn't know that. Which brings me to another feature wish, that resizes would snap to the grid. Once a bunch of panels have been resized to non-normal resizes it is a loot of work to make them align nicely again.

Great to hear that you are working on the grid!

**Comment by mattttt** [comment]
👍 I believe @torkelo just merged snap-to-grid into master (or will over the next couple days)! 

Keep everyone posted.

**Comment by Jhors2** [comment]
It would be incredibly nice to have a tree for the dashboard list.  We have a problem with dashboard sprawl that organizations don't fix for our use case well.  (Mostly because you can't straddle two organizations with one grafana user session).  It would be nice to have a tree that you can group your dashboards into for various teams or purposes.

**Comment by torkelo** [comment]
closing this in favor of specific issue for the dashboard building improvements were doing now
https://github.com/grafana/grafana/issues/6442
