### ISSUE TITLE
"grep" function not working at all

### ISSUE THREAD

**Issue by jordivanduijn** [grafana/grafana#6100]
**I'm submitting a Bug report**

Grafana version: **3.1**
Datasource: **graphite**
OS: **either Linux or Windows**

I am trying to use the **grep** function [as described in the functions documentation](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.grep), but all I get is an internal server error. I'm sure this function is very similar to the **exclude**, which works perfectly. 

I think this must be a bug, or I completely overlooked something...

**Comment by torkelo** [comment]
It's probably because the grep function is not added in the version of graphite you have. I think it is only available in graphite master

**Comment by jordivanduijn** [comment]
Thanks @torkelo, I'm sure this is the reason for the error. Would it be an idea to disable the grep function if it is not supportedoing by the Graphite datasource?

**Comment by torkelo** [comment]
there is no api to check that. Will have to add a version option to datasource edit view so the user can specify their graphite version. Then Grafana could filter so only supported functions show
