### ISSUE TITLE
export dashboard panel data json format 

### ISSUE THREAD

**Issue by Lawrancecool** [grafana/grafana#6101]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Issue contains no information on what's about, just the unmodified issue template, hit submit by accident?

**Comment by Lawrancecool** [comment]
Please Include feature in granfana export dashboard data as json format like what comes from export csv format like that
Now include only overall panel json that contains query of influx db

**Comment by torkelo** [comment]
What?

**Comment by Lawrancecool** [comment]
Add feature in grafana to export  dashboard data json

**Comment by Lawrancecool** [comment]
HI please add feature to export dashboard data  as json fomart
