### ISSUE TITLE
Teams with dashboard view permission can no longer load panels

### ISSUE THREAD

**Issue by krzd7** [grafana/grafana#61011]
**What happened**: users with viewer role can no longer view dashboard panels, making Grafana unusable for a bunch of use cases. Only editors can load panels.

**What you expected to happen**: viewers should be able to load dashboard panels.

**How to reproduce it (as minimally and precisely as possible)**: create a dashboard and add a Team with "View" only permission. Add a user to that team and login. You'll see the message "Panel plugin not found: Unable to load library panel: XYZ" for each panel.

![206810065-59c1f71a-51a8-46e1-aa19-5e537fba36a8](https://user-images.githubusercontent.com/79376156/210666876-64cfc4a4-498a-485d-bd81-d1a26997d930.jpg)

**Anything else we need to know?**: there are a bunch of bug reports for a similar issue with public dashboards (see #54802), but the problem is a lot worse and affects logged in users with view permission.

**Environment**:
- Grafana version: v9.3.1

**Comment by krzd7** [comment]
Hi @usmangt , 

I do not have a viewer permission for the dashboard, but I do have a Team permission that was working fine for loading dashboard panels prior to updating to v9.3.2.

I tried adding the Viewer permission to a specific dashboard and still my user, within the allowed Team, could not load panels. The only way I got loading panels to work was going to the folder settings and adding this Viewer permission. However, by doing this, I'm allowing any viewer to read any dashboard within the folder, which kills the use case for teams.

**Comment by torkelo** [comment]
@krzd7 strange, I tried to replicate this but could not. 

I added a user to team "Cool ops", and added "Cool ops" team to the folder that has my library panels with permission View. 

![Screenshot from 2023-01-06 09-09-57](https://user-images.githubusercontent.com/10999/210958311-f93aeb5c-2b17-4718-b68b-0ff9db352a3c.png)

Do have the team permissions set on the folder containing the library panels?

**Comment by krzd7** [comment]
Hi @torkelo, 

I do not have the team permissions set on the folder, only on the dashboard. It used to work this way. If I give the team view permissions on the folder, they will be able to access any dashboard within this folder.

**Comment by torkelo** [comment]
@krzd7 not sure what you mean, library panel permissions are only derived from the folder they are saved in .


So that sounds like a bug in the old system then

**Comment by krzd7** [comment]
Users can see the correct dashboards listed within the folder and access it, despite not having the Team view permissions for the folder. The problem is that after a recent update library load errors started.

Lets say I have multiple dashboards and two teams A and B. How can I give teams access to specific dashboards only? Considering I need to set view permissions to the entire directory. Dashboard teams view permissions becomes useless, because the folder permission will give them access to any dashboard within the folder. The only way I can see it working is having a directory for each Team and cloning dashboards that we never needed to duplicate.

**Comment by torkelo** [comment]
@krzd7 I think your confusing dashboard permissions and library panels permissions. They are different. the user you testing with clearly has access to open the dashboard. But they don't have view permissions for the individual library panels in that dashboard. For that you need to add view permissions to the folder the library panels live in to the relevant team

**Comment by krzd7** [comment]
@torkelo by library panels permissions do you mean folder permissions? Adding view permissions to the folder fixes the library panel load issue, however my team can access all dashboards within that folder, regardless of the dashboard allowing the team for view or not.

I'm really lost here, panels were loading properly prior to the update and permissions were setup just fine, I could isolate team access for each dashboard regardless of it being on the same folder or not.

**Comment by torkelo** [comment]
@krzd7 put your library panels in a special folder that only contains library panels could help then?

**Comment by krzd7** [comment]
@torkelo thanks for your suggestion, it seems to work. I've done the following:
- Created a new folder called "Library Panels", with viewer role/view permission;
- Moved all dashboards from my old folder - containing all panels - to the new "Library Panels" folder;
- After migrating the dashboards and panels I've created a new dummy dashboard on the new folder that uses all those panels in order for it to hold the panels in there;
- Moved back all dashboards except for the dummy to my old folder;
- The old folder has no View role permission, but I can isolate team access by managing dashboard permissions and panels are loading fine again;
- Deleted the dummy dashboard so the only downside is that users can see an empty Library Panels folder.

**Comment by TaitChan** [comment]
Hi @krzd7 , When you click on "Create library panel", 
the popup will say "Library panel permissions are derived from the folder permissions", 
So, if your team doesn't have access to the "library panel" folder, A member of the team looking at any dashboard that is using the "library panel" will display "Unable to load library panel".

I think you can try the following two ways to solve the problem you are currently experiencing.

One is to click on the ”Unlink library panel”
For example
- Folder dashoards
   - Library Panel A
   - Dashboard A（permissions team "My Team"）
      - Library Panel A（Unlink library panel）

or
- Folder library panels
   - Library Panel A
- Folder dashoards
   - Dashboard A（permissions team "My Team"）
      - Library Panel A（Unlink library panel）

Another is to create a folder with just "library panel" and open it to the team, like @torkelo said
For example
- Folder library panels（permissions team "My Team"）
   - Library Panel A
- Folder dashoards
   - Dashboard A（permissions team "My Team"）
      - Library Panel A

**Comment by krzd7** [comment]
thanks @TaitChan , 

I've followed the second approach, having a separate folder that holds library panels view permission.

So it seems like expected behavior and probably there was a bug with previous versions that allowed panels to load regardless. I'm closing this issue.
