### ISSUE TITLE
Derivative value on singlestat

### ISSUE THREAD

**Issue by gallart** [grafana/grafana#6102]
* **I'm submitting a ...**
- [ ] Feature request

I'm using Grafana 3.1.1 with InfluxDB database (v1.0).

I was wondering if we could display a derivative value on a singlestat panel?

Let me explain... We are storing SNMP values in InfluxDB related from network devices. As you may know, we are only storing "total octets counters" and not "bandwidth". In order to display bandwidth as a graph, we apply a derivative function and it works well.

Could we apply a derivative function on singlestat panel so instantaneous bandwidth could be displayed on top of our Grafana panel?

Thanks,
Best regards,

Gaëtan

**Comment by torkelo** [comment]
Yes. you can do any InfluxDB query in singlestat panel as well. Not sure what you question is about though. Any value you can graph in the graph panel you can show in the singlestat panel.
