### ISSUE TITLE
Fwd: Unknown column account_id - after Upgrade to Grafana 9.3.1 from Grafana 8.X

### ISSUE THREAD

**Issue by Skywalker1-CZ** [grafana/grafana#61023]
Hi,

we have the same error as Urnotprepared.

We used this syntax to make dump from default SQLite database, ten create MySQL database, start grafana-server and insert each lines from dump.

```bash
cd /var/lib/grafana/;
sqlite3 grafana.db .dump | sed "s/AUTOINCREMENT/AUTO_INCREMENT/g" | sed "s/\"/\`/g" | sed "/PRAGMA foreign_keys/d" | sed "/BEGIN TRANSACTION/d" | sed "s/TEXT NOT NULL DEFAULT 0/TEXT NOT NULL/g" | sed "s/\`for\` INTEGER/\`for\` BIGINT/g" | sed "s/\`frequency\` INTEGER/\`frequency\` BIGINT/g" | sed "s/\`epoch\` INTEGER/\`epoch\` BIGINT/g" | sed "s/\`epoch_end\` INTEGER/\`epoch_end\` BIGINT/g" | sed "s/\`created\` INTEGER/\`created\` BIGINT/g" | sed "s/\`updated\` INTEGER/\`updated\` BIGINT/g" | sed "s/\`updated\` INTEGER/\`updated\` BIGINT/g" | sed "s/TEXT NOT NULL DEFAULT \'NoData\'/TEXT NOT NULL/g" | sed "s/TEXT NOT NULL DEFAULT \'Alerting\'/TEXT NOT NULL/g" | sed "/sqlite_sequence/d" > dump.mysqldump;
```

Everythings look good, but then I ran update to v. 9.3.1 (from some version of 8.X) - via 
```bash
yum install grafana
```

And after that, we can't start grafana-server - got this error messages via journalctl:

```simpletext
Dec 15 08:58:32 vps125-dfyag.nlooud.com grafana-server[3019951]: logger=migrator t=2022-12-15T08:58:32.149602695+01:00 level=error msg="Executing migration failed" id="copy data_source v1 to v2" error="Error 1054: Unknown column 'account_id' in 'field list'"
```

but funny in this is, that the table `data_source` doesn't have column called `account_id`.

Can you please help us?

Kind regards

Filip Langer
Support L2  Linux
NETHOST s.r.o.

_Originally posted by @Hovezi in https://github.com/grafana/grafana/issues/56734#issuecomment-1352750191_

**Comment by iXingo** [comment]
same here

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @Skywalker1-CZ 

forwarding this issue to the back-end squad for further review

**Comment by ying-jeanne** [comment]
Can you do share your result of doing `SELECT * FROM migration_logs;` on both sqlite and mysql? account_id is a field for user v1, that means your user table migration is done already, but Grafana server doesn't find it in the migration and trying to do the migration to map account_id into org_id again. Otherwise you can try to rename user org_id column into account_id, but i doubt you will meet other issue afterwards.

**Comment by iXingo** [comment]
I have same issue here

**Comment by Skywalker1-CZ** [comment]
> @Skywalker1-CZ Can you share your result of doing `SELECT * FROM migration_logs;` on both sqlite and mysql? account_id is a field for user_v1, that means your user table migration is done already, but Grafana server doesn't find it in the migration logs and trying to do the migration to map account_id of user_v1 into org_id of user again.

Thanks for reply - as your request
the results of `SELECT * FROM migration_logs`:

- sqlite:
[sqlite_query.txt](https://github.com/grafana/grafana/files/10501586/sqlite_query.txt)

- mysql:
[mysql_query.txt](https://github.com/grafana/grafana/files/10501602/mysql_query.txt)

Kind regards

Filip Langer
Support L2 Linux
NETHOST s.r.o.

**Comment by ying-jeanne** [comment]
@Skywalker1-CZ it seems your migration_log table is not imported correctly, it has to be exactly the same as sqlite3 migration_log table, since at the start time, grafana would check on the ids of migration, if it is not there, grafana will rerun those missing migrations, which is causing your error. Could you check: - whether in your processed dump, you do have all the migration_log table data, - whether your import of those data are successfully done.

**Comment by ying-jeanne** [comment]
we have a tool that you can use instead, if you like to try out https://github.com/grafana/database-migrator

**Comment by iXingo** [comment]
> we have a tool that you can use instead, if you like to try out https://github.com/grafana/database-migrator

thanks, will try

**Comment by Skywalker1-CZ** [comment]
> we have a tool that you can use instead, if you like to try out https://github.com/grafana/database-migrator

Thanks for reply, I will try this, but the problem is on production server, where I can't stop grafana / MySQL for a long time, so I need try it on a copy of the production server.

I will let you if it works,
thanks

Filip Langer
Support L2 Linux
NETHOST s.r.o.

**Comment by mildwonkey** [comment]
I'm going to close this old issue; please open a new GH issue if you are still seeing any problems.
