### ISSUE TITLE
Logs: Adjust documentation for unified labels/detected-fields

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#61026]
We need to change [documentation](https://grafana.com/docs/grafana/latest/explore/logs-integration/) after https://github.com/grafana/grafana/issues/30221 is finished.

**Comment by gabor** [comment]
is https://github.com/grafana/grafana/issues/61215 a duplicate of this?

**Comment by svennergr** [comment]
> is https://github.com/grafana/grafana/issues/61215 a duplicate of this?

at least https://grafana.com/docs/grafana/latest/explore/logs-integration/#toggle-detected-fields is solved by this. live tailing isn't. I will adjust #61215
