### ISSUE TITLE
Docs: remove any mention of enable/disable permissions for data sources

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#61038]
**what/why**
enable data sources

https://grafana.com/docs/grafana/latest/administration/data-source-management/#enable-data-source-permissions

**Comment by vtorosyan** [comment]
For the context, with Grafana 9+ Data Source permissions feature is on by default - enabling and disabling it is not supported and to achieve desired behaviour RBAC should be used instead.

We should review the documentation to make it clear of how the feature works now, and what can be done as an alternative if someone wants to achieve "enable/disable" effect for datasources.

**Comment by GrafanaWriter** [comment]
@vtorosyan - can you let me know that status of the reviews here? I have this as Needs Research in the Tech docs project, but I suspect it's either In progress or Backlogged.

**Comment by vtorosyan** [comment]
@GrafanaWriter this is actually done - current docs are up to date and it does not mention enable/disable anymore. Thanks for the reminder.
