### ISSUE TITLE
Loki Query Editor: prettify query

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#61041]
In https://github.com/grafana/loki/pull/7906 an andpoint was implemented to prettify queries. This is an interesting and potentially useful feature, which we could support, for example, by adding a dedicated button or other defined behavior.

It's simple to implement, and could help to optimize workflows or reduce cognitive noise in complex/long queries.

**Comment by kavirajk** [comment]
NOTE: Prometheus support formating PromQL queries via `/format_query` endpoint as well.

https://prometheus.io/docs/prometheus/latest/querying/api/#formatting-query-expressions
