### ISSUE TITLE
Grafana Common Time Range Not Time Field Name for ElasticSearch Source

### ISSUE THREAD

**Issue by sanilveeravu** [grafana/grafana#6104]
* **I'm submitting a ...**
- [ ] Bug report

Please include this information:
- What Grafana version are you using?
3.0.4
- What datasource are you using?
Elastic Search
- What OS are you running grafana on?
Cent OS
- What did you do?
A dataset is generated with future time For example on 9/20/2016 for dates (9/20,9/21,9/22), The time field for the grafana source is defined with a predefined field which contains these 3 dates. On 9/22, when we put a 24 hour view the data for this metric does not appear, but if the view is changed to last 7 days it comes up. Hence it looks like Grafana Time Range is not able to consider the defined Time Field of the data source for the time range.
- What was the expected result?
Based on the datasource defined time field the, time range should pick the respective records.
- What happened instead?
Comes blank

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
> The time field for the grafana source is defined with a predefined field which contains these 3 dates

What do you mean? 

Please provide the raw Elasticsearch query that Grafana issues. You find this in the chrome console network tab. Look for the `_msearch` request.
