### ISSUE TITLE
error connecting influxDB influxQL

### ISSUE THREAD

**Issue by G0nz0uk** [grafana/grafana#61058]
Hello,

Not sure if this is an InfluxDB 1.8 oss issue or Grafana (version 9.2.8).  I've created many local DB's before and today I created a new one and all seems ok.  

However if I try and add it to Grafana as a new Datasource I get the error "error connecting influxDB influxQL".  It must be trying to connect as if I try changing the password in Grafana I get a 401 error so it is trying.

I'm not sure where to look next and wondered if you have seen this before.

I am able to create a new Datasource in Grafana to an existing DB that has been there for months, just not a new one.

To create it I just use this, any ideas?

CREATE DATABASE testawdb WITH DURATION 7d
CREATE USER "testawuser2" WITH PASSWORD 'temppassword1234'
GRANT ALL ON testawdb TO testawuser2

**What happened**:

When I save the new Datasource I get - "error connecting influxDB influxQL"

**What you expected to happen**:

To connect to the new databases.  As mentioned existing InfluxDBs are fine.

**How to reproduce it (as minimally and precisely as possible)**:

Possibly try on the below versions?

**Environment**:
- Grafana version:  9.2.8
- Data source type & version:  InfluxDB 1.8.10
- OS Grafana is installed on:  Ubuntu 20.0.4 LTS
- User OS & Browser: Chrome
- Grafana plugins: CSV

Thanks

**Comment by zuchka** [comment]
Thanks for creating this issue, @G0nz0uk 

Have you tried increasing the verbosity of grafana's server logs to `debug`? 

I just closed this other issue because it sounded like a config issue on the user side, but perhaps there's more to it...

https://github.com/grafana/grafana/issues/60837

**Comment by zuchka** [comment]
update: I downloaded a fresh binary in Influx 2.6 and I was able to connect it to grafana running on main. Perhaps its specific to older issues

**Comment by G0nz0uk** [comment]
Hello,

I've enabled debug mode and this is what I get now.  I'm not sure if the last line is related or not, but keep appearing.

```sudo tail /var/log/grafana/grafana.log
logger=accesscontrol.evaluator t=2023-01-06T10:54:27.495626103Z level=debug msg="matched scope" userscope=datasources:* targetscope=datasources:uid:-qh2GM2Vz
logger=secrets.kvstore t=2023-01-06T10:54:27.496279031Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=InfluxDB-TESTDB
logger=token t=2023-01-06T10:54:27.56198662Z level=debug msg=FeatureEnabled feature=accesscontrol.enforcement enabled=false licenseStatus=NotFound hasLicense=false hasValidLicense=false products=[]

logger=accesscontrol.service t=2023-01-06T10:54:27.562158173Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-11
logger=datasources t=2023-01-06T10:54:27.562647316Z level=debug msg="Querying for data source via SQL store" id=114 orgId=1
logger=token t=2023-01-06T10:54:27.563790262Z level=debug msg=FeatureEnabled feature=dspermissions.enforcement enabled=false licenseStatus=NotFound hasLicense=false hasValidLicense=false products=[]

logger=secrets.kvstore t=2023-01-06T10:54:27.563954239Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=InfluxDB-TESTDB
logger=tsdb.influxdb t=2023-01-06T10:54:27.564235439Z level=debug msg="Influxdb request" url="https://localhost:8089/query?db=testawdb&epoch=ms&q=SHOW+measurements"
logger=tsdb.influxdb t=2023-01-06T10:54:27.672245488Z level=warn msg="error performing influxdb healthcheck" err="error reading InfluxDB. Status Code: 401"

logger=context userId=11 orgId=1 uname=myadmin account t=2023-01-06T10:54:27.672912337Z level=info msg="Request Completed" method=GET path=/api/datasources/114/health status=400 remote_addr=10.23.0.101 time_ms=111 duration=111.660331ms size=72 referer=https://ourgrafanasite.com:3000/datasources/edit/-qh2GM2Vz handler=/api/datasources/:id/health
```
I just created a new datasource to an existing database and that works, it's just new ones.  The logs look similar to above on the working one too.  I wonder if Grafana doesn't like an empty DB as this working one says 'datasource is working. 1 measurements found' when I use that one.

**Comment by G0nz0uk** [comment]
Hello,  anything else I can try with Grafana, I'm on v9.2.8 and InfluxDB 1.8.10, which as I say is working fine with all the current Influx databases.  I can even create a new datasource and point to the current databases fine, it just seems to be any new ones I create, very odd.

**Comment by G0nz0uk** [comment]
The fix is to upgrade to 9.3.2, as previous versions don't like an InfluxDB (maybe 1.8.10) with 0 measurements.

**Comment by G0nz0uk** [comment]
https://github.com/grafana/grafana/commit/0b66abba1845b5d7b6f847944561580ce42f542b

**Comment by cuonghuynh** [comment]
that was my issue. you can write data to influxdb (manual insert data or from telegraf) before setup connect on Grafana if you do not want to upgrade grafana.
