### ISSUE TITLE
opentsdb, querying tags

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#61054]
Hello

When querying an opentsdb metric in grafana it shows 2 data points

![image](https://user-images.githubusercontent.com/900951/210816441-95a2165a-f01c-4bd4-b1e2-287741c871ca.png)

But query inspector shows the real data we want to plot namely under tags
![image](https://user-images.githubusercontent.com/900951/210816584-db044265-b527-4065-8abd-277d3429ad74.png)

The rest api call shows that same data
http://localhost:4242/api/query?start=1672706441&m=sum:1h-avg:car_number.opentsdb{country=US}

```
[{"metric":"car_number.opentsdb","tags":{"host":"web01","country":"US","lon":"-122.37866","lat":"47.239788"},"aggregateTags":[],"dps":{}}]
```

What could be the issue?

Grafana 9.1.5

Windows machine

opentsdb running in podman container.

Thanks

_Originally posted by @yosiasz in https://github.com/grafana/grafana/issues/60350#issuecomment-1372371041_

**Comment by bohandley** [comment]
Hello @yosiasz, thank you for bring this to our attention. I am not sure I understand the issue. Could you show us what your original query is? From your screenshot, I cannot see if you included tags or not. It seems that the original query is not producing the data you are expecting, is this the case?

Providing a har file for the query and response would be very helpful too, thank you!

**Comment by yosiasz** [comment]
Thanks

This is the original query

![image](https://user-images.githubusercontent.com/900951/210848534-866ad446-ef65-48e0-884c-f69d3f942900.png)


I am just not sure how to get the tags so I can plot it on a geomap

here is a portion of the har file, too big to post here

```
          "content": {
            "size": 529,
            "mimeType": "application/json",
            "compression": 195,
            "text": "[{\"metric\":\"car_number.opentsdb\",\"tags\":{\"host\":\"web01\",\"country\":\"US\",\"lon\":\"-122.37866\",\"lat\":\"47.239788\"},\"aggregateTags\":[],\"query\":{\"aggregator\":\"sum\",\"metric\":\"car_number.opentsdb\",\"tsuids\":null,\"downsample\":\"1h-avg\",\"rate\":false,\"filters\":[],\"percentiles\":null,\"index\":0,\"tags\":{},\"histogramQuery\":false,\"rateOptions\":null,\"preAggregate\":false,\"rollupUsage\":null,\"showHistogramBuckets\":false,\"explicitTags\":false,\"filterTagKs\":null,\"useFuzzyFilter\":true,\"rollupTable\":\"raw\",\"useMultiGets\":true},\"dps\":{\"1672704000\":18.0}}]"
          },
```

**Comment by yosiasz** [comment]
the above image attached results in data returned of dps as it is the default data time: 18, but we want the tags returned

http://opentsdb.net/docs/build/html/api_http/query/index.html

**Comment by yosiasz** [comment]
here is the data from query inspector

```
{
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/9/api/query",
    "data": {
      "start": 1670350420344,
      "queries": [
        {
          "metric": "car_number.opentsdb",
          "aggregator": "none",
          "tags": {}
        }
      ],
      "msResolution": false,
      "globalAnnotations": true,
      "showQuery": true
    },
    "hideFromInspector": false
  },
  "response": [
    {
      "metric": "car_number.opentsdb",
      "tags": {
        "host": "web01",
        "country": "US",
        "lon": "-122.37866",
        "lat": "47.239788"
      },
      "aggregateTags": [],
      "query": {
        "aggregator": "none",
        "metric": "car_number.opentsdb",
        "tsuids": null,
        "downsample": null,
        "rate": false,
        "filters": [],
        "percentiles": null,
        "index": 0,
        "tags": {},
        "histogramQuery": false,
        "rateOptions": null,
        "preAggregate": false,
        "rollupUsage": null,
        "showHistogramBuckets": false,
        "explicitTags": false,
        "filterTagKs": null,
        "useFuzzyFilter": true,
        "rollupTable": "raw",
        "useMultiGets": true
      },
      "dps": {
        "1672706441": 18
      }
    }
  ]
}
```

**Comment by yosiasz** [comment]
@bohandley I hope the above answers your quesions?

**Comment by bohandley** [comment]
Thank you for providing more information @yosiasz. I am sorry, but we do not return tag values in the query builder. We do return tag values in the [variable queries](https://grafana.com/docs/grafana/latest/datasources/opentsdb/#query-variable), but these are used with template variables. You may be able to create a new variable with the metric to use in a few [nested variable queries](https://grafana.com/docs/grafana/latest/datasources/opentsdb/#nested-templating) to get the values for  the latitude and longitude and then use those variables for the geomap.

**Comment by yosiasz** [comment]
No worries,  will just have to use api
