### ISSUE TITLE
Feature Request: User TEXT data entry OR some other 'sticky-notes' functionality

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6105]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

TEXT PANEL

Feature Request: Allow way to have USERs enter TEXT for this but not gift them EDITOR access
Kinda to offer a 'sticky-notes' feature ...

... if there was an okay data entry webform thing this wouldnt be needed
(have used TEXT box javascript for data entry but it isn't the most polished ..)

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
