### ISSUE TITLE
Alerting: reReplaceAll broken between 9.2.7 and 9.3.1 for alert labels

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#61063]
**What happened**:

In `9.2.7` I could set an Alert label as:

```
{{ reReplaceAll "^diamond\\.[^.]+\\.([^.]+).*" "$1" $labels.name }}
```
And for `diamond.dc1.roleB.hostFoo.metric` I would get a label with `roleB` as the value.

In `9.3.1` that produces:

`diamond.dc1.roleB.hostFoo.metric`

**What you expected to happen**:

For `diamond.dc1.roleB.hostFoo.metric` I would get a label with `roleB` as the value.

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert, attempt to use the `{{ reReplaceAll }}` to extract labels from dot-separated paths.

**Anything else we need to know?**:

I have not yet upgraded to 9.3.2, but I don't see any mention of this in the changelog.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: Graphite
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox on macOS
- Grafana plugins: N/A
- Others:

**Comment by mellieA** [comment]
I tried this with the example input and syntax from our docs to verify if the template function works but it is not working as documented there.  

https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/template-functions/#rereplaceall 

Another related issue, that was closed as a question: https://github.com/grafana/grafana/issues/54193

**Comment by mellieA** [comment]
Here's what I tried and the result: 

![Screenshot 2023-01-11 at 4 10 49 PM](https://user-images.githubusercontent.com/18175287/211937941-193c88d9-beef-436c-8828-c967a100b082.png)

![Screenshot 2023-01-11 at 4 10 59 PM](https://user-images.githubusercontent.com/18175287/211937950-e8dc67d7-18f5-441f-958e-65dc4a3de044.png)

![Screenshot 2023-01-11 at 4 09 25 PM](https://user-images.githubusercontent.com/18175287/211937969-0e93bb68-9a6f-4299-8acb-5bd988cc14f4.png)

**Comment by armandgrillet** [comment]
@reyjrar We were unsuccessful reproducing this issue, could you share a more complete example of an alert rule where reReplaceAll does not work? We are testing this in https://github.com/grafana/grafana/blob/5a7f38053b2742edee7a99a9c280cbffc1044dc0/pkg/services/ngalert/state/template_test.go#L335-L339 thus it is strange that this does not work anymore.

**Comment by mellieA** [comment]
@armandgrillet did you try testing it manually in the UI? I tried the example we share in our docs and it didn't work. Let me know if you spot something in my screenshots above that I might be doing wrong.

**Comment by armandgrillet** [comment]
@mellieA It seems successful from your last screenshot (the alert instance has the right `AlertValues` label), isn't it?

**Comment by JohnnyQQQQ** [comment]
We moved this to our Backlog to do an investigation, we are currently not sure why it's not the same in both places.

**Comment by yuri-tceretian** [comment]
> I tried this with the example input and syntax from our docs to verify if the template function works but it is not working as documented there.

I am not sure I understand what you mean.  Your screenshot actually confirms that this is working as expected 

![image](https://user-images.githubusercontent.com/25988953/219181328-17249235-b126-40cd-a404-9585d0e66b0f.png)

**Comment by yuri-tceretian** [comment]
I tried to reproduce the problem in Grafana 9.3.1 
I created a rule that queried Test Datasource with the label `name=diamond.dc1.roleB.hostFoo.metric` (same as in the issue)

I created an annotation with the template mentioned above and a label `name2` with the same template.

Here is the result. Works as expected.

![image](https://user-images.githubusercontent.com/25988953/219199036-315c9c50-30eb-49aa-9758-3276b47bf225.png)

Then I guessed that label rewrite got broken. I renamed rule's label from `name2` to `name` (same as in the evaluation result) and it worked as well.

![image](https://user-images.githubusercontent.com/25988953/219200571-e6133b57-7b9c-4b6b-be1e-e311b35e9c6e.png)

No bug. 

Closing this issue. Please reopen with steps to reproduce and screenshots.

**Comment by yuri-tceretian** [comment]
Also, it is worth mentioning that I tried the upgrade path: I created a rule in 9.2.7, and checked that labels are expanded correctly, then upgraded and confirmed that the expansion still happens.

**Comment by reyjrar** [comment]
FWIW: the issue appears to be related to improved handling of the `$labels.name` element. Strangely, in 9.2.7, the series names didn't match what graphite was returning. They were strange amalgamations of the query with the returned target name. IE:

```
groupByNodes(diamond.*.*.*.loadvg.01_norm,'max',1,2)
```

`$labels.name` would be something like: `max(diamond.foo.bar.*.loavavg.01_norm)`

And I had to mess with the `reReplaceAll` invocations to match.

Now in 9.3.1+, the labels are what I'd have assumed they should've been from the start:

`foo.bar`

Which is why all my `reReplaceAll()` invocations were broken.
