### ISSUE TITLE
Issue while grafana role mapping with keycloak IDP 

### ISSUE THREAD

**Issue by SURAJKALLOLI** [grafana/grafana#61079]
I am trying to setup Grafana latest with keycloak 19.0.1

I can successful login to grafana over Oauth2.
But there’s problems in that I stuck.

Role Mapping. I have three roles in Keycloak Admin, Editor and Viewer. But GF does not cover this.
The user is always in Viewer role.
And i set the path in .ini file like this

role_attribute_path = contains(roles[], 'admin') && 'Admin' || contains(roles[], '

i configured .ini file like this
[auth.generic_oauth]
name = OAuth
icon = signin
enabled = true
scopes = openid
empty_scopes = false
allow_sign_up = true
client_id = grafanatest
client_secret = ************ruwKWyF4NGaJ08R7oCzxyqeA
use_pkce = false
oauth_skip_org_role_update_sync = true
auth_url = http://host.docker.internal:8080/realms/master/protocol/openid-connect/auth
token_url = http://host.docker.internal:8080/realms/master/protocol/openid-connect/token
api_url = http://host.docker.internal:8080/realms/master/protocol/openid-connect/userinfo
role_attribute_path = contains(realm_access.roles[*], 'Grafana Admin') && 'Admin' || contains(realm_access.roles[*], 'editor') && 'Editor' || 'Viewer'
role_attribute_strict = true
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[plugins]
allow_loading_unsigned_plugins = camptocamp-prometheus-alertmanager-datasource
[users]
allow_sign_up = false
#log level
[log.file]
level = debug

**Comment by usmangt** [comment]
Hi @SURAJKALLOLI,

Thanks for opening this issue.

Though I am not an expert in the Auth area but I think this is a configuration issue. I found some similar questions on our Grafana Community Forums for e.g.

https://community.grafana.com/t/role-mapping-with-keycloak/64261
and
https://community.grafana.com/t/role-mapping-keycloak-and-grafana-9-1-1-not-successfull/71440

I suggest that you take a look in there and search in the forums (or can ask by creating a new post under the Authentication sub-category).

I will close this one for now. But feel free to reopen it if you do not find any answers.
