### ISSUE TITLE
Stats produce slow query 

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#61085]
**What happened**:
Every 4 hours grafana issues a mysql query that is really slow and use all my server CPU.

Here's the slow query :
```
SELECT
                (SELECT COUNT(*) FROM (SELECT
                (SELECT login from `user` WHERE (LOWER(login) = LOWER(u.login)) AND (login != u.login)) AS dup_login,
                (SELECT email from `user` WHERE (LOWER(email) = LOWER(u.email)) AND (email != u.email)) AS dup_email
        FROM `user` AS u) AS d WHERE (d.dup_login IS NOT NULL OR d.dup_email IS NOT NULL)) as duplicate_user_entries,
                (SELECT COUNT(*) FROM (SELECT login, email FROM `user` WHERE (LOWER(login) != login OR lower(email) != email)) AS mcu) AS mixed_cased_users;
```
According to mysql slow query log, the request takes ~20m and scans ~1 billions rows

Here's the explain of the query : 
```
+----+--------------------+------------+------------+-------+---------------+----------------------+---------+------+-------+----------+--------------------------+
| id | select_type        | table      | partitions | type  | possible_keys | key                  | key_len | ref  | rows  | filtered | Extra                    |
+----+--------------------+------------+------------+-------+---------------+----------------------+---------+------+-------+----------+--------------------------+
|  1 | PRIMARY            | NULL       | NULL       | NULL  | NULL          | NULL                 | NULL    | NULL |  NULL |     NULL | No tables used           |
|  6 | SUBQUERY           | user       | NULL       | index | NULL          | IDX_user_login_email | 1524    | NULL | 25603 |    99.00 | Using where; Using index |
|  2 | SUBQUERY           | <derived3> | NULL       | ALL   | NULL          | NULL                 | NULL    | NULL | 25603 |    99.00 | Using where              |
|  3 | DERIVED            | u          | NULL       | index | NULL          | IDX_user_login_email | 1524    | NULL | 25603 |   100.00 | Using index              |
|  5 | DEPENDENT SUBQUERY | user       | NULL       | index | NULL          | UQE_user_email       | 762     | NULL | 25603 |    90.00 | Using where; Using index |
|  4 | DEPENDENT SUBQUERY | user       | NULL       | index | NULL          | UQE_user_login       | 762     | NULL | 25603 |    90.00 | Using where; Using index |
+----+--------------------+------------+------------+-------+---------------+----------------------+---------+------+-------+----------+--------------------------+
```

**What you expected to happen**:
Not having a slow query for stats (or be able to disable this specific stat)

**How to reproduce it (as minimally and precisely as possible)**:
I currently have 26 000 users.

**Environment**:
- Grafana version: 9.2.7
- OS Grafana is installed on: rhel 8
- Database : mysql 8

**Comment by usmangt** [comment]
Hi @deathwarrior60,

Thanks for opening this issue.

It might be good to check if the problem is related to MySQL as Grafana only visualize the Data which is defined either as a Datasource or via a Plugin.

You can use a very popular tool known as [MySQL Tuner](https://github.com/major/MySQLTuner-perl) which will need to be downloaded on your MySQL node. It is basically a Perl script which does several performance-related tests and gives you a report as to what areas are good or needs improvements (with recommendations).

Please use it and see if this helps you out.

**Comment by abhijadhav20** [comment]
We are facing the same db CPU saturation issue with Postgres db. Grafana version is 9.2.2.
We can see this query different in 9.0.2 and has been observed there is no CPU issue with this version.

Thanks,
Abhijit Jadhav

**Comment by usmangt** [comment]
Thanks, everyone for reporting and giving more feedback on this issue. Since I cannot reproduce it, therefore will forward this one to our Engineers as they might be able to tell in more detail.

**Comment by natellium** [comment]
@grafana/backend-platform do you know anything about what might be causing this?

**Comment by eleijonmarck** [comment]
if it is causing issue for mysql, and for postgres, it will affect others as well. For now we will make a change to disable this `stat` until we have a more performant query that won't take long to check for similar counts.

Thank you everyone for reporting the issue! 🙏

**Comment by eleijonmarck** [comment]
@deathwarrior60 and others that have reported this. The fix will be out in the latest release of Grafana and the fix has also been backported to v9.2.x, v9.3.x . Meaning that the latest releases of Grafana in version

v9.2.x, v9.3.x, 9.4.x will not include the stats query. 🙏 
The release will be around next on the 24th

**Comment by DanCech** [comment]
To clarify, the current workaround is to disable collecting these stats via #61675.  #61674 will need to be addressed if we want to start reporting them again.  An alternative would be to remove them altogether if people are not deriving value from the stats.

**Comment by eleijonmarck** [comment]
yea we could just remove the stats, it is to be able to see if there are conflicts for users before we enforce a setting that would explicitly remove duplicates.

**Comment by eleijonmarck** [comment]
linked to - https://github.com/grafana/grafana/issues/52345
