### ISSUE TITLE
issue "Origin Not Allowed" error when accessing Grafana with azure front door Domain

### ISSUE THREAD

**Issue by VinayTalla20** [grafana/grafana#61082]
**What happened**:
     I have deployed Grafana versions 8.3.5, 9.0.4, latest on Kuberenetes cluster and configured ingress to access Grafana UI from subpath "/grafana" with public domain(Go Daddy domain) mapped to ingress controller i.e., example.dev. Coming to Azure Front Door  added Go Daddy domain(example.dev) as Backend pool any request coming from   "*.azurefd.net"  will be forworded to nginx ingress. Finally I can access Grafana and can login successfully but after some time it prompts "Origin Not Allowed". 
 
**What you expected to happen**:
    Need a fix for above, is this issue with   Azure Front Door  or  Nginx Ingress or Grafana Version Bug. 
  I need to access Grafana from Azure Front Door  Frontend Domain  *.azurefd.net/grafana like this. i have configured Go Daddy public Domain to my Grafana spec.rules.host in Nignx Ingress Rules.    
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
   I need to know whether it is issue with Azure Front Door or Grafana itself or Nginx Ingress
**Environment**:
- Grafana version:  8.3.5, 9.0.4, latest
- Data source type & version: 
- OS Grafana is installed on: Linux, Kubernetes Cluster
- User OS & Browser: Chrome, Microsoft Edge
- Grafana plugins: Promethes, Loki
- Others:

**Comment by usmangt** [comment]
Hi @VinayTalla20,

Thanks for opening this issue.

This seems to be a known issue as found an almost similar one here:

https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

(also found in our community forums: https://community.grafana.com/t/origin-not-allowed-messages-after-upgrade-to-8-3-6/60550)

Please have a look and let us know if the suggested solutions solve your problem

**Comment by VinayTalla20** [comment]
Hi, @usmangt  Thanks for your concern, I have gone through above solution but it doesn't worked for me. even  i have added csrf_additional_headers = X-Forwarded-Host,  csrf_trusted_origins = https://example.azurefd.net in my grafana.ini configuration.

my request flow 
 Frontdoor domain(example.azurefd.net)  ---->  Ingress Host Public   "example.dev" (Go Daddy public Domain)   ---->  Kubernetes Grafana ClusterIP Service ("/grafana").

**Comment by VinayTalla20** [comment]
Added Rule Engine in Azure Front Door, so that origin is overwritten to ingress host
