### ISSUE TITLE
Search all dashboards in the command palette

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#61092]
**Background**
Currently, the command palette is limited to searching 500 dashboards due to performance issues. This is not a satisfactory user experience as it limits the dashboards that can be accessed through the command palette.

**What are we building?**
To improve the user experience, we should move dashboard search to the backend. This will allow us to search all dashboards, rather than being limited to 500.

These changes, along with [integrating the command palette into the UI](https://github.com/grafana/grafana/issues/61091) should be done behind a feature toggle.

**Expected behavior**
Any dashboard in Grafana should be accessible through the command palette.

**Comment by zsofiakm** [comment]
https://github.com/grafana/grafana/issues/61091

**Comment by leeoniya** [comment]
cc @ryantxu
