### ISSUE TITLE
grafana API : playlist creation does not work on 7.5

### ISSUE THREAD

**Issue by arnaudlemaignen** [grafana/grafana#61096]
**What happened**:
when trying to create a playlist with curling grafana api it returns
{"message":"Playlist not found"}

**What you expected to happen**:
the playlist api to return the created playlist
  {
    "id": 1,
    "name": "my playlist",
    "interval": "10s"
  }
  
**How to reproduce it (as minimally and precisely as possible)**:
curl -X PUT --user "admin:admin" -H "Content-type: application/json"  http://localhost:3000/api/playlists/1 -d "@/test/play.json"

vi /test/play.json
{"name":"my playlist","interval":"10s","items":[{"id":1,"playlistid":1,"type":"dashboard_by_id","title":"1 PM DA Level ALL","value":"10415","order":1},{"id":2,"playlistid":1,"type":"dashboard_by_id","title":"3 PM DA Level Technology","value":"10417","order":2}]}

**Anything else we need to know?**:
in the grafana log
t=2023-01-06T15:13:59+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/playlists/1 status=404 remote_addr=[::1] time_ms=89 size=32 referer=

**Environment**:
- Grafana version: 7.5.15

**Comment by usmangt** [comment]
Hi @arnaudlemaignen,

Thanks for opening this issue.

Grafana's current latest stable version is 9.3.1 and version 7.5.x is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

Recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now I will now close this issue)
