### ISSUE TITLE
Create command palette documentation

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#61095]
Currently, the [search documentation page](https://grafana.com/docs/grafana/latest/search/) only documents dashboard search. We should also define the behavior of the command palette.

**Comment by zsofiakm** [comment]
Recommended changes:

1. Move the contents of "[Search dashboards](https://grafana.com/docs/grafana/latest/search/)" page under "[Dashboards](https://grafana.com/docs/grafana/latest/dashboards/)" 
2. Repurpose the [search page](https://grafana.com/docs/grafana/latest/search/) to talk about the command palette. We could title the page "Search and command palette" (though that's quite long).

**Comment by zsofiakm** [comment]
Some of the content here could be repurposed for documentation: https://grafana.com/blog/2022/06/22/new-in-grafana-9-introducing-the-command-palette/

**Comment by eledobleefe** [comment]
@chri2547 would you mind giving us feedback about these changes?

**Comment by eledobleefe** [comment]
We have agreed to do the following:

1. Keep the "[Search dashboards](https://grafana.com/docs/grafana/latest/search/)" page where it is now.
2. Add the Command Palette documentation on the Search page under an extra header.
