### ISSUE TITLE
d3-color vulnerable to ReDoS 

### ISSUE THREAD

**Issue by leonsp-ai** [grafana/grafana#61101]
**What happened**: Grafana npm packages have a dependency (d3-color, d3-interpolate) with a vulnerability rated as High severity

**What you expected to happen**: No dependencies with a high-severity vulnerability

**How to reproduce it (as minimally and precisely as possible)**:

```sh
$ mkdir npm-play
$ cd npm-play
$ npm install @grafana/data@9.3.2
$ npm audit

# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install @grafana/data@8.2.7, which is a breaking change
node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    @grafana/data  >=8.3.0-beta.1
    Depends on vulnerable versions of d3-interpolate
    node_modules/@grafana/data

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Anything else we need to know?**:

There's an automated Renovate PR to updated d3 here: https://github.com/grafana/grafana/pull/58315

It needs some attention before it can be merged

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: n/a
- OS Grafana is installed on: macOS 12.6.2
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by usmangt** [comment]
Hi @leonsp-ai,

Thanks for opening this issue.

I will forward this issue to our Engineers as they might be able to investigate it in more detail.

**Comment by usmangt** [comment]
Although initialized the [discussion](https://raintank-corp.slack.com/archives/CHQDPC970/p1673259528084049). But this issue is still unassigned to a project.

Based on the closest match the issue is linked with npm packaging used in Grafana so selecting Plugins Platform.

Incase wrong, then kindly let me know.

**Comment by tolzhabayev** [comment]
Notes for us (plugins platform):
- We have to find out what internal components are affected once we bump this library and involve the relevant teams that own them to make adjustments
