### ISSUE TITLE
Plugin readme isn't visible to non-admin users

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#6110]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-pre1
- What datasource are you using?
- What OS are you running grafana on? Ubuntu
- What did you do? Visited a plugin details page (logged in as a non-admin user)
- What was the expected result? The plugin readme should be displayed
- What happened instead? The api returned 403

**Comment by torkelo** [comment]
hmn.. the plugin details is not currently be accessible to non org admin user

**Comment by DanCech** [comment]
If you're logged in as a user with Viewer membership in an org, the Home dashboard still displays a list of installed plugins.  If you click on the name of any plugin, you can view the plugin details page.

With this patch, that page is displayed properly rather than being empty.

I do note that when viewing an app the page does show tabs for Config (which will load) and Dashboards (which won't).  These should probably be disabled.

The list on the home dashboard also shows an Enable Now link for unconfigured plugins, which will take the user to the Config tab on the plugin details page.  This should be disabled.

When clicking the worldPing app the user is taken to the worldPing Home dashboard, which doesn't properly respect the user's access level and displays UI elements for adding endpoints etc.
