### ISSUE TITLE
Annotations Break After Viewing Then Saving

### ISSUE THREAD

**Issue by jnadler** [grafana/grafana#61107]
**What happened**:
A dashboard has a working Elasticsearch Annotation.  Go to Settings > Annotations and view the Annotation.   Save the dashboard.

The annotation no longer functions.   The JSON changed so that the query is no longer used.

**What you expected to happen**:
Nothing.

**How to reproduce it (as minimally and precisely as possible)**:
There are other reports that look similar going back some time, so I expect this will be tough to reproduce.  See:
https://github.com/grafana/grafana/issues/39186
https://github.com/grafana/grafana/issues/57122

Reproduced in Chrome, Firefox, and Safari

* existing dashboard with an elasticsearch annotation
* upgraded to v9.1.6 
* annotation works fine, confirm that 'Save' finds no changes to save
* Settings > Annotations, select the Annotation (just viewing it, not touching any fields)
* 'Save Dashboard', it shows a diff even tho we didn't edit anything, go ahead and Save
* annotation no longer works:  elasticsearch is getting an empty query that fetches all records for the time range

Annotation JSON Before, Working:
```
      {
        "datasource": {
          "type": "elasticsearch",
          "uid": "000000129"
        },
        "enable": true,
        "hide": false,
        "iconColor": "rgba(255, 96, 96, 1)",
        "name": "docc updates",
        "query": "(syslog_program.raw:doccserver_$cluster OR syslog_program.raw:doccserver) AND msg.raw:\"docc event\" AND app_namespace.raw:\"$namespace\" AND app_name.raw:\"$application\" AND docc_cluster.raw:\"$cluster\" AND (docc_event.raw:\"update\" OR docc_event.raw:\"deploy\" OR docc_event.raw:\"restart\")",
        "showIn": 0,
        "tags": [],
        "tagsField": "app_name",
        "textField": "docc_event",
        "type": "tags"
      }
 ```
 
 Annotation JSON after daring to look at it in the UI, Busted:
 ```
       {
        "datasource": {
          "type": "elasticsearch",
          "uid": "000000129"
        },
        "enable": true,
        "hide": false,
        "iconColor": "rgba(255, 96, 96, 1)",
        "mappings": {},
        "name": "docc updates",
        "showIn": 0,
        "tags": [],
        "tagsField": "app_name",
        "target": {
          "query": "(syslog_program.raw:doccserver_$cluster OR syslog_program.raw:doccserver) AND msg.raw:\"docc event\" AND app_namespace.raw:\"$namespace\" AND app_name.raw:\"$application\" AND docc_cluster.raw:\"$cluster\" AND (docc_event.raw:\"update\" OR docc_event.raw:\"deploy\" OR docc_event.raw:\"restart\")",
          "refId": "annotation_query"
        },
        "textField": "docc_event",
        "type": "tags"
      }
 ```

Note the added `mappings` field, and the new `target` field that now contains our `query`, except the query isn't used anymore.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.1.6
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Using the Docker image
- User OS & Browser: MacOS, reproduced in Chrome, Firefox, and Safari
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @jnadler,

Thanks for opening this issue. Can you please;

1- Check the Elasticsearch version you are using (here is the [link](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#supported-elasticsearch-versions) to the official documentation which provides information on the supported versions)

2- Could you please try to reproduce this scenario on the latest grafana version 9.3.x?

**Comment by jnadler** [comment]
Hi @usmangt we're on Elasticsearch `7.17.7`.  I don't believe that this issue is related to Elasticsearch and instead is purely Grafana JavaScript because it is observed to occur without any network calls from the browser at all.

Yes we can try against the latest grafana release, but it will take some time.

**Comment by usmangt** [comment]
Hi @jnadler,

Got caught in some side work. Just wanted to ask if this issue is still appearing in the nwever version 9.3.x ?

Kindly let us know :slightly_smiling_face:

**Comment by ArsenyBelorukov** [comment]
I've tested on 9.3.6
and have the same behaviour:
after saving an annotation without changes it generates diff:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/52857617/221251277-2cda9701-6cb4-4aef-a847-9dd909544ff5.png">

**Comment by dprokop** [comment]
The diff you are showing is an expected one due to https://github.com/grafana/grafana/pull/49529.

@joey-grafana could you please have a look at what might have gone wrong here?

**Comment by ArsenyBelorukov** [comment]
@dprokop dashboard just hangs up, and I have to kill the tab.

**Comment by joey-grafana** [comment]
Hey @dprokop, I see @gabor added this to the logs squad which is perfect, as they are the team responsible for Elasticsearch.

**Comment by gabor** [comment]
investigation note: the changing of the JSON is caused by this generic grafana code: https://github.com/grafana/grafana/blob/6d53c87862e4ef67aa454c1b722282b5dd04b4a8/public/app/features/annotations/standardAnnotationSupport.ts#L26-L39

called from https://github.com/grafana/grafana/blob/6d53c87862e4ef67aa454c1b722282b5dd04b4a8/public/app/features/annotations/components/StandardAnnotationQueryEditor.tsx#L59-L65

so the changing of the JSON seems to be intentional (need ot check why the "new format" does not work, and to why we store it in "old format")
