### ISSUE TITLE
grafna 9, unified alerting Some notification policies do not work.

### ISSUE THREAD

**Issue by gurumee92** [grafana/grafana#61125]
**What happened**:

I am configuring an alarm using Grafana 9 unified alert. Unfortunately I've found that some notification policies didn't work.

**What you expected to happen**:

slack messages comming.

**How to reproduce it (as minimally and precisely as possible)**:

**First, normal situtation:**

my configuration is
**alert rule:**
1 set a query and alert condition
<img width="1501" alt="issue-1-set-a-query-and-alert-condition" src="https://user-images.githubusercontent.com/32067275/211239629-9212be7e-22b1-45f8-8a1a-2028668fcf05.png">

2 Alert evaluation behavior
<img width="1570" alt="issue-2-alert-evaluation-behavior" src="https://user-images.githubusercontent.com/32067275/211239637-a9ec6a34-5b49-4968-b706-1d0665abe85d.png">

3 Add details for your alert
<img width="1565" alt="issue-3-add-details-for-your-alert" src="https://user-images.githubusercontent.com/32067275/211239639-42251395-0c6f-468c-845f-849bf8334c69.png">

4 Notifications **(label "test=true")**
<img width="1573" alt="issue-4-notifications" src="https://user-images.githubusercontent.com/32067275/211239641-d67e933f-03ba-4d1c-8c9d-be26fba690e0.png">

**notification policy:**
<img width="1378" alt="issue-5-notification-policy" src="https://user-images.githubusercontent.com/32067275/211239645-d9f4d91c-581a-4ad5-b451-ecc9d61f4aa1.png">

**logs:**
```bash
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T02:59:09.517339754Z level=info msg="rules state was reset" deleted_states=1 
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T02:59:50.490222535Z level=info msg="clearing the state of the rule because version has changed" version=22 new_version=23 # i set alert condition always firing for test
logger=context userId=107 orgId=1 uname=gurumee92 t=2023-01-09T02:59:50.490251844Z level=info msg="Request Completed" method=POST path="/api/ruler/grafana/api/v1/rules/<REDATED>" status=202 remote_addr=172.17.64.74 time_ms=18 duration=18.490344ms size=45 referer="https://<REDATED>/alerting/D0ojomhVk/edit?returnTo=%2Falerting%2Flist" handler=/api/ruler/grafana/api/v1/rules/:Namespace
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T02:59:50.496156093Z level=info msg="rules state was reset" deleted_states=1
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T03:00:10.019268347Z level=info msg="rules state was reset" deleted_states=0 # taks few seconds send to slack
```
**result: (send slack message well, red blank include team name, and panel link. extra infos etc.)**
![issue-6-alert-result](https://user-images.githubusercontent.com/32067275/211239647-91142ab5-efa8-4045-86ab-d7443d9ab4e6.png)

**Second, error situation**
but, i changed alert rule’s alert label in notifications, and configured other notification policy matches this changed label.

**alert rule (same alert rule, change notification, red blank is team name):**

4 Notifications
<img width="1559" alt="issue-7-notifications" src="https://user-images.githubusercontent.com/32067275/211239648-5df2ea62-b09b-4f8c-87eb-a2675b595f95.png">

**notification policy (new notification policy, red blank is team name):**
<img width="1380" alt="issue-8-notification-policy" src="https://user-images.githubusercontent.com/32067275/211239650-bc495f0a-4573-4e84-b1ec-59e4fb4d335f.png">

**logs:**
```bash
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T03:16:05.972512538Z level=info msg="rules state was reset" deleted_states=1
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T03:16:49.411835735Z level=info msg="clearing the state of the rule because version has changed" version=24 new_version=25
logger=context userId=107 orgId=1 uname=gurumee92 t=2023-01-09T03:16:49.411875718Z level=info msg="Request Completed" method=POST path="/api/ruler/grafana/api/v1/rules/<REDACTED>" status=202 remote_addr=172.17.64.74 time_ms=11 duration=11.486339ms size=45 referer="https://<REDACTED>/alerting/D0ojomhVk/edit?returnTo=%2Falerting%2Fgrafana%2FD0ojomhVk%2Fview%3FreturnTo%3D%252Falerting%252Flist" handler=/api/ruler/grafana/api/v1/rules/:Namespace # i set alert condition always firing for test
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T03:16:49.416426683Z level=info msg="rules state was reset" deleted_states=1
logger=ngalert rule_uid=D0ojomhVk org_id=1 t=2023-01-09T03:17:07.275469816Z level=info msg="rules state was reset" deleted_states=0 # slack message not coming
```

same logs occured,  i wait long time but slack message not coming. and i checked alert state history (top is alert firing but not messags comming)
<img width="707" alt="issue-9-alert-history" src="https://user-images.githubusercontent.com/32067275/211239652-b09cf2e6-dc30-4309-9391-6a0fb33a78cd.png">

please tell me What needs to be check to resolve this issue.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: grafana/grafana 9.2.5 (docker hub)
- Data source type & version: prometheus v2.40.1
- OS Grafana is installed on: eks: v1.22.15 (instance type: r6g.4xlarge)
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by usmangt** [comment]
Hi @gurumee92,

Thanks for opening this issue.

I think this is a configuration issue. I found some similar questions on our Grafana Community Forums for e.g.

https://community.grafana.com/search?q=%22unified%20alerting%22

I suggest that you take a look at there and search in the forums (or can ask by creating a new post under the Alerting sub-category).

I will close this one for now. But feel free to reopen it if you do not find any answers.
