### ISSUE TITLE
Can't reset the slider value to the original value

### ISSUE THREAD

**Issue by RaiBnod** [grafana/grafana#61129]
**What happened**: Slider value can't reset to the original value

**What you expected to happen**: Sometimes we slide down the value on the slider and want to revert it to the original value

**How to reproduce it (as minimally and precisely as possible)**: slider value changes from the parent level but the slider value doesn't override

**Anything else we need to know?**: We need to listen to the props.value on the `Slider` component and override the value accordingly.

**Environment**:
- Grafana version: v7.5.15

### It will be useful in such cases:

**What's happening:**

https://user-images.githubusercontent.com/6800775/211265776-22b89411-dc82-4f1c-819c-2c09c3862d0a.mov

**Expected behaviour:**

https://user-images.githubusercontent.com/6800775/211266362-347a5017-dd42-4372-95e2-80b41d3aacfe.mov

**Comment by usmangt** [comment]
Hi @RaiBnod,

Thanks for opening this issue.

Grafana's current latest stable version is 9.3.1 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will now close this issue).
