### ISSUE TITLE
Pull-down for movingAverage parameters doesn't quote string values

### ISSUE THREAD

**Issue by jleader** [grafana/grafana#6114]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 2.5.0
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 12.04.5 LTS
- What did you do? Used movingAverage in the metric editor, selected a string-valued parameter from the pull-down list of parameters (i.e. 5min, 10min, 30min, 1hour).
- What was the expected result? Passes the chosen string value to Graphite
- What happened instead? Passed the unquoted value to Graphite, producing a data request error, which contained the lines "TypeError at /render" and "%d format: a number is required, not string"

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
try a newer version of Grafana. Works when I test it in Grafana 3.1
