### ISSUE TITLE
Research dependencies exposed as external to plugins and reduce their scope. e.g.: Redux, D3.

### ISSUE THREAD

**Issue by academo** [grafana/grafana#61154]
We need to know:
- What libraries should we stop exposing to plugin authors to reduce a number of dependencies that are hard to upgrade without breaking plugins (example https://github.com/grafana/grafana/issues/61101)
- Once we know and have a decision which one that would be, we have to update the migration guide https://grafana.com/docs/grafana/latest/developers/plugins/migration-guide/

**Comment by tolzhabayev** [comment]
@jackw I assume since we already bumped d3 - this is not in progress or doing? Do we want to push it forward or drop for Q1?

**Comment by leeoniya** [comment]
also Moment :(
