### ISSUE TITLE
metric with upper case undefined error

### ISSUE THREAD

**Issue by sbs081** [grafana/grafana#6117]
$db_base#Innodb_available_undo_logs/port=3306

master-baseundefinednnodb_available_undo_logs/port=3306.

How to fix it?

**Comment by torkelo** [comment]
?

**Comment by torkelo** [comment]
please provide some information :)  

The github new issue template has some information that really help us :)

**Comment by sbs081** [comment]
The upper case is escaped, How can I solve it?

**Comment by torkelo** [comment]
that is the value for the $db_base variable? 

From the github issue template 
> IMPORTANT If it relates to metric data viz:

An image or text representation of your metric query
The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

That would help greatly :)

**Comment by torkelo** [comment]
also what version of Grafana, Graphite, browser/Os are you using etc :)

**Comment by liuniansheng** [comment]
I also  get this problem. All first upper case of   variables become undefined

**Comment by wuyi5630** [comment]
@torkelo I also get this problem. All first upper case of variables become undefined

**Comment by torkelo** [comment]
please provide full Graphite query and graphite response information (and any template variable config / current values)
