### ISSUE TITLE
the first upper case letter is escaped with metric

### ISSUE THREAD

**Issue by sbs081** [grafana/grafana#6119]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
V3.1.0
- What datasource are you using?
open-falcon
- What OS are you running grafana on?
centos6.7
- What did you do?
make the graph with mysql data
- What was the expected result?
![image](https://cloud.githubusercontent.com/assets/8540577/18785725/7eeb7fda-81cc-11e6-866d-84b0cfc84896.png)

- What happened instead?
The first upper case letter is escaped.
![image](https://cloud.githubusercontent.com/assets/8540577/18785768/bca021a0-81cc-11e6-9466-e2e0e1e331d2.png)

**Comment by torkelo** [comment]
please open bug report with open falcon, probably a bug with that datasource plugin
