### ISSUE TITLE
Spurious error when changing settings of new dashboard

### ISSUE THREAD

**Issue by mure** [grafana/grafana#61194]
**What happened**:

Given a user with Viewer permissions for the org but explicit Editor permissions for a folder, going into the settings view of a new dashboard triggers a seemingly meaningless error.

![Kapture 2023-01-09 at 14 03 06](https://user-images.githubusercontent.com/9257800/211397679-04c6872f-a1b5-43e1-aaea-f9a4ae99f074.gif)

**What you expected to happen**:

No error should pop up.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new user with Viewer role in the org.
2. Create a new folder and give the user Editor permissions on that folder.
3. Sign in as new user.
4. Create a new dashboard.
5. Click the 'Dashboard settings' button.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version:
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Firefox
- Grafana plugins:
- Others:

**Comment by mure** [comment]
So I think the problem is that the settings view loads the FolderPicker component: https://github.com/grafana/grafana/blob/da18c89e917c0e09a97aae7b646e93066b218edb/public/app/features/dashboard/components/DashboardSettings/GeneralSettings.tsx#L109-L116
And the dashboard's `folderId` is 0 by default even though it doesn't technically exist yet. And then the FolderPicker tries to get the metadata for that folder, but the user doesn't have access to read it.

**Comment by mure** [comment]
The permissions seem wonky here. The user can successfully retrieve `/api/folders` but not `/api/folders/{id}`, even though the docs claim that the permission for both of them is `folders:read`.

**Comment by usmangt** [comment]
Hi @mure,

Thanks for opening this issue.

Yes, I see what you mean. To my understanding, if the user is given only Viewer permission in the Org then it is Global. 

But giving the same user in the Org an Editor option for a Dashboard seems to be conflicting with the Org global permission mapping.

This probably needs some investigation.
