### ISSUE TITLE
Field name corrupts on auto refresh

### ISSUE THREAD

**Issue by CommanderRedYT** [grafana/grafana#61209]
**What happened**:
When I have auto-refresh activated, the name of a field changes from 'foo' to '{name=foo}'.

**What you expected to happen**:
The name should stay the same

**How to reproduce it (as minimally and precisely as possible)**:
Add a panel (i've tested it with timeseries) and load some data via sql, turn on auto refresh and hover over the metric until it refreshes.

**Anything else we need to know?**:
```sql
-- query from gif
SELECT
    $timeSeries as t,
    sum(status='CLOSED') as Closed,
    sum(status='WAIT_FOR_DETAILS') as `Wait for Details`,
    sum(status='IN_PROGRESS') as `In Progress`,
    sum(status='ASSIGNED') as Assigned
FROM $table
WHERE $timeFilter
GROUP BY t
ORDER BY t DESC
```

**Environment**:
- Grafana version: Grafana OSS 9.3.1
- Data source type & version: vertamedia-clickhouse-datasource / 2.5.2
- OS Grafana is installed on: Archlinux
- User OS & Browser: Archlinux / Firefox 108.0.2
- Grafana plugins: /
- Others:

![screen_recording](https://user-images.githubusercontent.com/43087936/211516125-b4fc0080-1abc-40c6-bd7f-47cba6af57c5.gif)

**Comment by usmangt** [comment]
Hi @CommanderRedYT,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by CommanderRedYT** [comment]
I will try it in a couple of minutes, until then, here is my own instance with the dashboard from the gif: https://grafana.bobbycar.cloud/goto/D48vAA2Vz

**Comment by usmangt** [comment]
What is the value of the auto-refresh interval you set e.g. 5 sec, 10 sec etc?

**Comment by CommanderRedYT** [comment]
It is 5s. What I discovered a few minutes ago is that it also has this bug when I have a panel open in the editor and manually refresh there. It only stays "correct" after page load until the first reload of the data

**Comment by CommanderRedYT** [comment]
@usmangt  Did the link work?

**Comment by usmangt** [comment]
Though I was not able to reproduce it on my test machine but can reproduce it on your server link.

I will forward this issue to our Engineers as they might be able to tell in more detail.

**Comment by usmangt** [comment]
Hi @CommanderRedYT,

Need some more information for investigation.

1- Does this issue only occurs with the Time Series Panel or also noted with other panels as well?

2- Can you kindly send us the panel debug information by using the snapshot feature?

Here are the steps.

Go to your panel where you can open the menu -> select **More** -> then select **Get Help**

It will open a new page where you can send the debug information about the dashboard. simply click the blue button **Dashboard** which will download the file.

Either send it as an attachment (if possible) or use the Clipboard button to copy/paste it here as a complete code.

Thanks.

**Comment by CommanderRedYT** [comment]
Hi @usmangt 
> 1- Does this issue only occurs with the Time Series Panel or also noted with other panels as well?
I only noticed it with the Time Series Panel.

> 2- Can you kindly send us the panel debug information by using the snapshot feature?

[debug-Tickets-2023-01-19 23 17 20.json.txt](https://github.com/grafana/grafana/files/10461550/debug-Tickets-2023-01-19.23.17.20.json.txt)

**Comment by usmangt** [comment]
Thanks and can you please answer the 1st question i.e.



> 1- Does this issue only occurs with the Time Series Panel or also noted with other panels as well?
> I only noticed it with the Time Series Panel.

**Comment by CommanderRedYT** [comment]
@usmangt I did, I just got the markdown formatting wrong and it added my answer to the quote (Only noticed it with Timeseries)

**Comment by CommanderRedYT** [comment]
@usmangt @zoltanbedi Any updates on this?

**Comment by zoltanbedi** [comment]
no progress @CommanderRedYT sorry. but thanks for the debug panel with that I was able to reproduce this. @leeoniya

**Comment by CommanderRedYT** [comment]
Hey, how is the status?

**Comment by CommanderRedYT** [comment]
I think this might have been fixed in newer releases, at least I cannot reproduce myself anymore with v10.4.1

**Comment by zoltanbedi** [comment]
Nice, thanks for letting us know @CommanderRedYT
