### ISSUE TITLE
Migration 8.5.9 to 9.2.5 fails with dashboard migration permission issue

### ISSUE THREAD

**Issue by nitesh8860** [grafana/grafana#61205]
**What happened**:
We are trying to upgrade from v8.5.9 legacy alerting to v9.2.5 unified alerting
we are using a grafana docker container with sqlite database
we are trying to run another container with image 9.2.5 with same database
migration fails with following logs

```
logger=migrator t=2022-12-16T11:52:11.641947998Z level=warn msg="alert linked to obsolete notification channel, ignoring" alert="glc-dsb-redis01 - Redis Uptime alert" uid=ZCyZgxfMz
logger=migrator t=2022-12-16T11:52:11.641955625Z level=warn msg="alert linked to obsolete notification channel, ignoring" alert="gdc-als-re03 - SWAP Usage alert" uid=5
logger=migrator t=2022-12-16T11:52:11.64196354Z level=warn msg="alert linked to obsolete notification channel, ignoring" alert="gdc-als-re03 - SWAP Usage alert" uid=8
logger=migrator t=2022-12-16T11:52:12.481690314Z level=info msg="Executing migration" id="update dashboard_uid and panel_id from existing annotations"
logger=migrator t=2022-12-16T11:52:12.713124885Z level=info msg="Executing migration" id="dashboard permissions"
logger=migrator t=2022-12-16T11:52:12.738219442Z level=error msg="Executing migration failed" id="dashboard permissions" error="failed to migrate permissions: failed to create permissions for role: UNIQUE constraint failed: permission.role_id, permission.action, permission.scope"
logger=migrator t=2022-12-16T11:52:12.738258674Z level=error msg="Exec failed" error="failed to migrate permissions: failed to create permissions for role: UNIQUE constraint failed: permission.role_id, permission.action, permission.scope" sql="code migration"
Failed to start grafana. error: migration failed (id = dashboard permissions): failed to migrate permissions: failed to create permissions for role: UNIQUE constraint failed: permission.role_id, permission.action, permission.scope
migration failed (id = dashboard permissions): failed to migrate permission
```

**What you expected to happen**:
Successful migration to v9

**How to reproduce it (as minimally and precisely as possible)**:
upgrading from v8 legacy alerting to v9 unified alerting

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana 8.5.9 and OS centos 7
- Data source type & version: Elasticsearch 8 and Influxdb
- OS Grafana is installed on:  centos 7 and Linux 3.10.0-1062.1.2.el7.x86_64 
- User OS & Browser: Ubuntu and google chrome
- Grafana plugins: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
- Others:
This issue was first raised at grafana [community](https://community.grafana.com/t/migration-8-5-9-to-9-2-5-fails-with-dashboard-migration-permission-issue/78177/2),  
as [suggested](https://community.grafana.com/t/migration-8-5-9-to-9-2-5-fails-with-dashboard-migration-permission-issue/78177/22?u=niteshchauhan) in that issue i have raised a bug here.

**Comment by tonypowa** [comment]
forwarding issue to Auth squad since a similar[ issue](https://github.com/grafana/grafana/issues/55924) was given a fix in this [PR](https://github.com/grafana/grafana/pull/58079)

**Comment by mgyongyosi** [comment]
Upgrading to Grafana 9.3+ (with latest patch version) should solve this issue.

**Comment by nitesh8860** [comment]
Hi, I tried with 9.3.2, it fails with following type of several logs      

`logger=ngalert.sender.router rule_uid=9EP8U1o4k org_id=1 t=2023-01-23T09:51:36.351467856Z level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.sender.router rule_uid=pDU8UJT4z org_id=1 t=2023-01-23T09:51:36.359054899Z level=info msg="Sending alerts to local notifier" count=1
logger=datasources t=2023-01-23T09:51:36.362974548Z level=error msg="Failed getting data source" err="database is locked" uid=000000001 id=0 name= orgId=1
logger=ngalert.scheduler rule_uid=jE888JoVk org_id=1 version=1 attempt=0 now=2023-01-23T09:51:00Z t=2023-01-23T09:51:36.363006891Z level=error msg="Failed to build rule evaluator" error="failed to build query 'C': database is locked"
logger=datasources t=2023-01-23T09:51:36.385866056Z level=error msg="Failed getting data source" err="database is locked" uid=000000001 id=0 name= orgId=1
logger=ngalert.scheduler rule_uid=PAl88Jo4z org_id=1 version=1 attempt=0 now=2023-01-23T09:51:00Z t=2023-01-23T09:51:36.385927414Z level=error msg="Failed to build rule evaluator" error="failed to build query 'E': database is locked"
logger=ngalert.sender.router rule_uid=-eBUU1o4k org_id=1 t=2023-01-23T09:51:36.386984201Z level=info msg="Sending alerts to local notifier" count=1
logger=datasources t=2023-01-23T09:51:36.389773759Z level=error msg="Failed getting data source" err="database is locked" uid=000000001 id=0 name= orgId=1
logger=ngalert.scheduler rule_uid=a9BUUJTVz org_id=1 version=1 attempt=0 now=2023-01-23T09:51:00Z t=2023-01-23T09:51:36.389817014Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': database is locked"
logger=datasources t=2023-01-23T09:51:36.390271011Z level=error msg="Failed getting data source" err="database is locked" uid=000000001 id=0 name= orgId=1
logger=ngalert.state.manager rule_uid=gYBUU1TVk org_id=1 t=2023-01-23T09:52:54.15864651Z level=info msg="Detected stale state entry" cacheID="[[\"__alert_rule_namespace_uid__\",\"4UvitH9mz\"],[\"__alert_rule_uid__\",\"gYBUU1TVk\"],[\"alertname\",\"(********* - ****** alert\"],[\"grafana_folder\",\"Linux-Servers\"],[\"rule_uid\",\"gYBUU1TVk\"]]" state=Alerting reason=Error
`

![image](https://user-images.githubusercontent.com/13062907/214010583-b7b996a5-65ed-4d8a-a038-79f03aebd320.png)

**Comment by Jguer** [comment]
Closing as versions are not supported any longer
