### ISSUE TITLE
[bug] "min doc count" in elasticsearch query has default 0, but ES has default 1

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#6121]
- [ x] Bug report

Please include this information:
- Grafana version: 3.1.1
- datasource:  elasticsearch
- OS: Debian 8

Min Doc Count in query for Elasticsearch has default 0. But default in Elasticsearch is 1 - see in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

Value 0 leads to showing zeros in Graph for timestamps at the beginning of the selected interval if specific timestamp is not covered in ES data. And therefore we have to manually set value 1 everywhere - which reduces our fun when we use Grafana. :-)

EDIT: OK, I found one and only case when this setting makes problems - if graph has only values like 1,2,3.. But this is very rear in our case so maybe default setting for in "min doc count" in data source definition would be helpful?

**Comment by torkelo** [comment]
for time series it's usually important to have a value (0 or null) for each time slice, otherwise you cannot visualize missing data,  you can set a lower limit for your group by or change the "no document" value from zero.
