### ISSUE TITLE
LG TV WebIS access

### ISSUE THREAD

**Issue by GnomiBerlin** [grafana/grafana#61212]
**Steps to reproduce**: login to Grafana

**Actual Result**:
Browser not supported hint on screen
**Expected Result**
Access Grafana like NodeRed Dashboard on big TV screen monitor.
Worst case with switch to disable browser Chech and define default browser usage in case of unsupported one 

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 9 2.1
- Data source type & version: InfluxDB2
- User OS & Browser: webOS
- Others: I know there are closed bug reports, but there is no solution and I want to integrate this into NodeRed Dashboards, which are visible on smart TVs

**Comment by usmangt** [comment]
Hi @GnomiBerlin,

Thanks for opening this issue.

This question comes under the category of monitoring IoT devices using Grafana. For such questions, the best place is to ask in our Community Forums (while here on GitHub we focus on the issues and bugs related to Grafana).

I searched for some node-red related posts and found there are actually a good amount of posts for e.g.

https://community.grafana.com/search?q=node-red
or
https://community.grafana.com/search?q=node%20red
or
https://community.grafana.com/search?q=nodered

You can try to search if you found a post which matches your question or create a new one (please select the sub-category InfluxDB as your datasourse is InfluxDB and define the details like what you had defined here).

I will now close this issue

**Comment by GnomiBerlin** [comment]
This was misunderstood. I only referencecd NodeRed Dashboard as more flexible, BUT Grafana works NOT on a LG TV!

**Comment by GnomiBerlin** [comment]
Not closed

**Comment by usmangt** [comment]
Thanks for the quick reply


Please review the submission template and include more details (as much as possible):

* What Grafana version and what operating system are you using?
* What is your datasource?
* What visualization panel you are using e.g. time-series, bar chart, histogram etc?
* **What** are you trying to achieve?
* **How** are you trying to achieve it?
* What happened?
* What did you **expect** to happen?
* Can you copy/paste the configuration(s) that you are having problems with?
* Did you receive any errors in the Grafana UI or in related logs? If so, please tell us **exactly** what they were.
* Did you follow any online instructions? If so, what is the URL?

**Comment by GnomiBerlin** [comment]
I answered the relevant part of these questions. Grafana on Raspberry PI Debian 64bit working for Firefox and Chrome. It is a clear unsupported WebBrowser issue for which I ask for more flexibility.
Picture from TV screen.

![PXL_20230110_120226624](https://user-images.githubusercontent.com/43815556/211546768-acce6709-c442-4d4c-a75c-1d505dd6b0a4.jpg)

**Comment by usmangt** [comment]
Thanks.

Did you configure any DataSources inside Grafana? (if yes, then what is the Datasoruce name)?

OR

Do you get this message (the screenshot you shared) every time when you try to access the Grafana WebUI?

**Comment by GnomiBerlin** [comment]
As I wrote above. The data source is: InfluxDB2 on another server.
All Grafana views are running on Android mobile phones and windows  PCs using Firefox and Chrome in the same network. Only on the LG TV Grafana shows this.

**Comment by usmangt** [comment]
Ok, this is good information.

For the next steps, could you please provide us with the backend logs (the default location in Linux is `/var/log/grafana/grafana.log`) so that we can have more information about the error message?

Just try again to view the Grafana on your TV and then paste the logs here.

**Comment by usmangt** [comment]
Also which web browser you are using in your LG TV to open Grafana (and then you get that screen error message)?

**Comment by GnomiBerlin** [comment]
Hi again,
now the additional requested data: web browser details and grafana.log
I made a typo yesterday: I use Grafana 9.3.1(89b365f8b1) on Raspberry. 
I use the WebOS build in Web browser. The details from https://www.whatismybrowser.com/ are:

```
WEB BROWSER AND PLATFORM: 
NetCast on Linux
Smart TV

THEIR WEB BROWSER'S CAPABILITIES:
Is JavaScript enabled?	Yes 
Are Cookies enabled?	Yes 
Third-Party Cookies?	Yes 
Is Flash Installed?	Not installed, or disabled. 
Is Java Installed?	Not installed, or disabled. 

MORE INFO ABOUT THEIR SYSTEM:
---
Computer Screen	1920 x 1080 pixels
24 bit 
Browser Window Size	1920 x 1080 pixels 
"Do Not Track" Setting	Enabled
Using Tor?	No 

THEIR WEB BROWSER'S TECHNICAL DETAILS:
Software Type	Web Browser	Hardware Type	Tv
Browser version (full)		Operating System version (full)	
Operating Platform	Smart TV	Layout Engine	WebKit
WebKit version	537.36	Configured Languages	Deutsch (German), English
Device Pixel Ratio	1	Browser GMT Offset	+01:00
Navigator Platform	Linux aarch64	No. of logical CPU cores	4
Maximum Touch Points	1	WebGL Vendor	ARM
WebGL Renderer	Mali-G51	RAM (Gigabytes)	2
ECMA Version	11		
THEIR WEB BROWSER'S USER AGENT:
Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36 SmartTV/10.0 Colt/2.0
```

And the grafana log data:
192.168.179.30: working Win10 PC on Chrome 109
192.168.179.70: working Android 13 Chrome 108
192.168.179.29: not working LG TV browser

```
logger=cleanup t=2023-01-11T08:13:57.811230286+01:00 level=info msg="Completed cleanup jobs" duration=18.09912ms
logger=cleanup t=2023-01-11T08:23:57.804902019+01:00 level=info msg="Completed cleanup jobs" duration=12.188527ms
logger=context userId=1 orgId=1 uname=admin t=2023-01-11T08:29:18.659582623+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.179.30 time_ms=16 duration=16.608641ms size=0 referer= handler=/api/live/ws
logger=cleanup t=2023-01-11T08:33:57.81455494+01:00 level=info msg="Completed cleanup jobs" duration=21.825881ms
logger=context userId=1 orgId=1 uname=admin t=2023-01-11T08:41:30.500105109+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.179.30 time_ms=14 duration=14.56309ms size=0 referer= handler=/api/live/ws
logger=cleanup t=2023-01-11T08:43:57.813129105+01:00 level=info msg="Completed cleanup jobs" duration=20.478773ms
logger=context userId=1 orgId=1 uname=admin t=2023-01-11T08:50:37.728213531+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.179.70 time_ms=8 duration=8.35399ms size=0 referer= handler=/api/live/ws
logger=context userId=0 orgId=0 uname= t=2023-01-11T08:51:41.968956702+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.179.29 time_ms=0 duration=877.087µs size=29 referer= handler=/
logger=cleanup t=2023-01-11T08:53:57.814549379+01:00 level=info msg="Completed cleanup jobs" duration=21.578604ms
logger=context userId=1 orgId=1 uname=admin t=2023-01-11T08:56:06.424283052+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.179.70 time_ms=2 duration=2.732924ms size=0 referer= handler=/api/live/ws
logger=context userId=0 orgId=0 uname= t=2023-01-11T08:56:17.063264445+01:00 level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=192.168.179.29 time_ms=1 duration=1.135876ms size=29 referer= handler=/
pi@piGrafana:~$
```

I hope this helps.

**Comment by usmangt** [comment]
Hi @GnomiBerlin ,

Although that error message already states the possible reason for it.

But in this specific case, the possible reason is that the web browser is unsupported.

Our official [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers) provides a list of the supported browsers which work with Grafana.

If possible, try to install chrome or firefox on your LG TV and see if that resolves the issue.

**Comment by GnomiBerlin** [comment]
Hi,
This is really not new. Chrome etc  can not be installed on the TV.
This caused my question, if there is no switch possible to ignore this browser test in Grafana and allows a default browser functionality selection, that also other browsers can be used on own risk.
