### ISSUE TITLE
Feature: SAML Authentication

### ISSUE THREAD

**Issue by sc10n** [grafana/grafana#6122]
* **I'm submitting a feature reuqest for SAML authentication so that I can use other factors of authentication.

**Comment by DanCech** [comment]
This may be able to use the same basic framework as for OAuth-based authentication, via the "social" login system.

**Comment by torkelo** [comment]
closing this as there is already an issue for it, https://github.com/grafana/grafana/issues/4780

**Comment by MahadevG** [comment]
@DanCech 
Which is the best way to configure SSO between a Webapplication(PHP) and  Grafana. I tried AuthProxy, It creates the user but user has not logged in to grafana. What mistake did I do or Is there any other way to do this??

**Comment by DanCech** [comment]
@MahadevG you need to re-read how authproxy works, the user's requests have to go through the proxy and have the header added to every request.
