### ISSUE TITLE
Gv4: Plugin Description Page

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#6123]
For Grafana v4, I'd like to move the Config tab to be the default tab when loading a plugin, and change the Overview Tab to Readme, and move it to be last (after dashboards). 

Most actions for plugins are completed in the Config tab, and making someone always click to Config is an unnecessary step for the user.

**Comment by DanCech** [comment]
Need to be aware of non-admin users, and it'd be good to address the other issues outlined in [my comment](https://github.com/grafana/grafana/issues/6110#issuecomment-249184514) on #6110

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/19268999/22557790-8fb8-11e6-8ad1-9944e83ccfd8.png)
