### ISSUE TITLE
Elasticsearch error on fetching a preview does not give details about the error

### ISSUE THREAD

**Issue by ruudvanderweijde** [grafana/grafana#61246]
**What happened**:
Elasticsearch query gave an error, when trying to preview a query on a new alert. No details about the error were provided.
```
Failed to evaluate queries and expressions: failed to execute query A: Unknown elasticsearch error response
```
<img width="1726" alt="afbeelding" src="https://user-images.githubusercontent.com/3205112/211640708-9dafd878-cee3-4527-9bc1-789d2e4eafb8.png">

**What you expected to happen**:
I would expect to see the error message that Elasticsearch gives.

I looked into the browser console on the network tab, and in the server logs, but I could not find additional information about the error message. Only when debugging locally (see section below) I could find additional information.

**How to reproduce it (as minimally and precisely as possible)**:
- Create new alert
- Use elasticsearch query with multiple aggregations and a big(ger) time range, which will result in a 'too many buckets error'
- There is a error popup: "Failed to evaluate queries and expressions: failed to execute query A: Unknown elasticsearch error response"

**Anything else we need to know?**:
When debugging the format of the response I got from Elasticsearch. Elastic
```
(*simplejson.Json)(0x14001fcd8d0)({
 data: (map[string]interface {}) (len=7) {
  (string) (len=9) "caused_by": (map[string]interface {}) (len=3) {
   (string) (len=11) "max_buckets": (float64) 65536,
   (string) (len=4) "type": (string) (len=26) "too_many_buckets_exception",
   (string) (len=6) "reason": (string) (len=196) "Trying to create too many buckets. Must be less than or equal to: [65536] but this number of buckets was exceeded. This limit can be set by changing the [search.max_buckets] cluster level setting."
  },
  (string) (len=10) "root_cause": ([]interface {}) {
  },
  (string) (len=4) "type": (string) (len=32) "search_phase_execution_exception",
  (string) (len=6) "reason": (string) "",
  (string) (len=5) "phase": (string) (len=5) "fetch",
  (string) (len=7) "grouped": (bool) true,
  (string) (len=13) "failed_shards": ([]interface {}) {
  }
 }
})
```
I got this info by adding to `spew.Dump(json)` to [elasticsearch/response_parser.go](https://github.com/grafana/grafana/blob/12c4098bcdb0838691dddcab19d52b7cc80e97f3/pkg/tsdb/elasticsearch/response_parser.go#L709-L712)
```
 func getErrorFromElasticResponse(response *es.SearchResponse) string {
 	var errorString string
 	json := simplejson.NewFromAny(response.Error)
+	spew.Dump(json)
         ...
}
```

**Environment**:
- Grafana version: 5.3.2 (also reproduced on main branch)
- Data source type & version: Elasticsearch 8.0+
- OS Grafana is installed on: Kubernetes 1.25
- User OS & Browser: macOS Monterey (version 12) 
- Grafana plugins: none
- Others: Elasticsearch version 8.5.3
```
> curl -s "localhost:9200/" | jq -r .version.number
8.5.3
```

**Comment by ruudvanderweijde** [comment]
I created 2 commits https://github.com/ruudvanderweijde/grafana/commit/0d960c5161c4c77fd0614a95610a0a7426cef142 & https://github.com/ruudvanderweijde/grafana/commit/91b42ad9fce98c0593ae865f3ab53e927a25767d to improve this.

Could you provide me with feedback if this is the right way to move forward? I'm happy to add test cases after the feedback.

**Comment by mellieA** [comment]
@ruudvanderweijde had you already entered a query when you saw this error? I've noticed that the alert page sometimes runs the query before it is complete and creates misleading errors

**Comment by ruudvanderweijde** [comment]
I looked a bit deeper, and found what is causing the error.

I run the same query in the panel (bar chart and time series both run fine) as I ran when trying to create an alert. For the alert I want to query the last 24h, just like I do on the graph.

So the query works from the panel, but not from the alert. After putting debug information in the elasticsearch client in `executeRequest` method [[ref](https://github.com/grafana/grafana/blob/main/pkg/tsdb/elasticsearch/client/client.go#L133-L167)], I was able to detect a difference between the two calls.

![afbeelding](https://user-images.githubusercontent.com/3205112/212286058-79602a0e-8f42-40a5-a98a-c2b6c340d39c.png)


When running these queries against ES directly, I get the same error:

With `"fixed_interval": "120000ms",` the query works:

![afbeelding](https://user-images.githubusercontent.com/3205112/212286193-8037a73a-9a09-4efb-979d-c3f693e70136.png)
With `"fixed_interval": "1000ms",` the query fails:

![afbeelding](https://user-images.githubusercontent.com/3205112/212286226-43962aae-ad07-4a2c-a834-88935e9fee44.png)

**Comment by ruudvanderweijde** [comment]
I found a difference. In the panel/bar chart I had the query setting on min interval 1d configured. 

On the alert, I did use the 'auto' interval as well, but that of course doesn't pick up the min interval setting from the panel.

After changing the ES time interval to 1d, the query works!! Which makes sense.

I've attached a video to show it:

https://user-images.githubusercontent.com/3205112/212290412-30d098dc-96ab-48b7-9acb-eb030ecb4ea5.mp4

**Comment by armandgrillet** [comment]
I think https://github.com/grafana/grafana/pull/61471 is valid but I am removing this from the alerting board as it does not concern this part of Grafana specifically. Please assign the right reviewers to that PR but observability logs seems like the right reviewers.

**Comment by mellieA** [comment]
@ruudvanderweijde thank you for all of the work you've contributed here. I've added the observability logs squad as reviewers.
