### ISSUE TITLE
XY-Chart Min Max not working correctly

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#61244]
Dear grafana community,

on the XY-Chart the limits do not work correctly.

If Min and Max  are set in "Standard options",  x AND y axis are changed both to the new limits. In my case only the x-axis should be limited.

[example dashboard with limits min 0, max 80](https://i.ibb.co/nLdJ8dT/f.png)

**Comment by leeoniya** [comment]
can you try using field overrides to set min and max for each axis independently?

there's not really a logical way to configure multiple axes' limits using just standard options with a single pair of min/max settings.
