### ISSUE TITLE
Timezone in Table

### ISSUE THREAD

**Issue by j-Nimble** [grafana/grafana#6124]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1
- What datasource are you using?
InfluxDB v1.0.0
- What OS are you running grafana on?
Win 2008 R2
- What did you do?
Created a table to view text data.  The table has one timestamp column and two text columns.  The dashboard setting is to use local browser time.  My timezone is -4 hours UTC.  There is currently only one entry in the database, as shown below that entry is in UTC.
2016-09-23T04:00:00Z <text> <text>

- What was the expected result?
I expect the timestamp column to show the correct date / time.  Adjusted correctly for UTC to local timezone, I should have seen:
2016-09-23 12:00:00 AM <text> <text>

- What happened instead?
It appears that for the table the UTC/Local timezone adjustment is occurring twice.  What I see is:
2016-09-22 10:00:00 PM <text> <text>.

A couple of other points:
- The graphs on that dashboard show data exactly as expected.  It is only the table that is affected.
- I changed the view on the dashboard to be UTC instead of local browser, and it appears like the conversion is actually being done before it makes it to the screen.: (actually shown: 2016-09-23 12:00:00 AM <text> <text>/ should have shown: 2016-09-23 04:00:00 AM <text> <text>)
- I am using a grouping of 1d with the aggregate last() to take the last value in the set.

Interesting:
- If I remove the 1d aggregate the time is fixed.

It is possible that this is the expected behavior from the aggregates but it's not what I was expecting.

**Comment by torkelo** [comment]
It's maybe InfluxDB? Open chrome dev tools network tab, and identify the InfluxDB request and look at the response
