### ISSUE TITLE
fullRangeLogsVolume was removed

### ISSUE THREAD

**Issue by liolay** [grafana/grafana#61256]
**What happened**:
fullRangeLogsVolume was remove in new version after 8.4

**What you expected to happen**:
i think it is very useful while not every team want to deploy a front proxy for loki

**How to reproduce it (as minimally and precisely as possible)**:
no

**Anything else we need to know?**:
no

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @liolay,

Thanks for opening this issue.

Could you please try this configuration file (the default location in Linux is `/etc/grafana/grafana.ini`)

Under section;

`[feature_toggles]`

Add it like this;

```
# enable features, separated by spaces
fullRangeLogsVolume = false
```
Save the changes in the configuration file. Then restart the grafana service on the machine and check if it is then enabled.

Let us know if this helps.

**Comment by liolay** [comment]
> 

i have already use this configuration in version < 8.4 and works, but after upgrade to 9.3.2 that's not, and i found this 
https://github.com/grafana/grafana/actions/runs/1845708971/workflow

**Comment by liolay** [comment]
> Hi @liolay,
> 
> Thanks for opening this issue.
> 
> Could you please try this configuration file (the default location in Linux is `/etc/grafana/grafana.ini`)
> 
> Under section;
> 
> `[feature_toggles]`
> 
> Add it like this;
> 
> ```
> # enable features, separated by spaces
> fullRangeLogsVolume = false
> ```
> 
> Save the changes in the configuration file. Then restart the grafana service on the machine and check if it is then enabled.
> 
> Let us know if this helps.

i have already use this configuration in version < 8.4 and works, but after upgrade to 9.3.2 that's not, and i found this
https://github.com/grafana/grafana/actions/runs/1845708971/workflow

**Comment by gabor** [comment]
hi @liolay , the log-volume graph does work for me in 9.3.2, i have just tried it and i can see the log-volume-graph. there is no need to use feature-flags anymore for that feature in grafana9.

could you please describe what is missing for you? i mean, what exactly does not work? thanks!

**Comment by liolay** [comment]
@gabor this full range log volume histogram is rendered by metric query  which is expensive depending on time range queried, This query is particularly challenging for our Loki which is just one node installations

**Comment by gabor** [comment]
thanks for the info @liolay .
to avoid misunderstandings, i'd like to clarify something. there are two situations:

`A`: when you run a logs-producing query in Loki, we show those logs and also show a graph of the count of results, the log-volume-histogram, like in this screenshot (note: the log-volume-histogram section can be collapsed if you don't want it):

<img width="868" alt="logs-query" src="https://user-images.githubusercontent.com/51989/211790461-05840cb1-6714-4719-8b2b-79bf6fbc28d2.png">



`B`: when you run a metric query (a query that produces numbers), we simply show the result graph, no logs-volume happens, like in this screenshot:

<img width="902" alt="metric-query" src="https://user-images.githubusercontent.com/51989/211790954-6bf4a455-d34c-4b54-8972-2ba81b14d7a7.png">

is your problem happening in situation `A` or `B`?
and, what exactly is the problem? does it take too long for the graph to get displayed?

**Comment by liolay** [comment]
@gabor i am really sorry, it's my mistake! my situation is A, and just like you said that  log-volume-histogram will not be queried through `sum(level) by ...`  while it is collapsed, thanks!

**Comment by BaskiGIT** [comment]
With 'Logs volume' collapsed in version 9.4, logs appear only for the latest 1000 logs ( by default limit set in grafana ) irrespective of the duration of the query. Either 'Older first' or 'Newest first' will only show the latest 1000 logs

**Comment by BaskiGIT** [comment]
> hi @BaskiGIT , currently the logs are always searched in `direction=backward` , the `oldest first` and `newest first` modes just re-order the already received logs.
> 
> there is a feature request to be able to specify the direction at #56850

Thanks @gabor

**Comment by JeffCT0216** [comment]
Can we please add this back? https://github.com/grafana/grafana/pull/45286
We cannot reliable depend on user to collapse the log volume tab

**Comment by shapirus** [comment]
This issue should be reopened. #45286 has removed a very important feature.
