### ISSUE TITLE
Possible to change Metric column title for time series aggregations in table panels?

### ISSUE THREAD

**Issue by envintus** [grafana/grafana#6125]
Is it currently possible to change the column title for "Metric" when displaying time series aggregations in a table panel? If not this would be a nice to have cosmetic when creating leaderboard type visualizations.

Example of the type of query I'm running, which counts total occurrences of foo for a given user, so they can be ranked by totals:
``SELECT count("foo") FROM "bar" WHERE $timeFilter GROUP BY time(30d), "user"``

* Query formatted as ``time series``
* To table transform:``time series aggregations``
* Columns: ``Totals``
*  Override relative time: ``Last 30d``

**Comment by torkelo** [comment]
No it's currently not possible. 

Please open questions in the mailing list :) Github is for feature requests / bugs :)
