### ISSUE TITLE
Set default search limit when searching for traces with Tempo datasource

### ISSUE THREAD

**Issue by thirdeyenick** [grafana/grafana#61260]
**What happened**:

When being in the 'Explore' view and having:
* a Tempo data source selected
* set the query type to 'Search'

then there is no default search limit set in the Grafana UI. This actually indicates that all traces would be shown when doing the search. However, Tempo has a default search limit on the API side (defaults to 20), which is used whenever there is no limit set by the client (Grafana in this case). This leads to confusion.

**What you expected to happen**:

The Grafana UI sets a default search limit, which clearly indicates how many traces will be returned max.

**How to reproduce it (as minimally and precisely as possible)**:

See the steps at 'What happened'.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: Tempo
- OS Grafana is installed on:
- User OS & Browser: Mac Os 12.6, Firefox
- Grafana plugins:
- Others:

**Comment by natellium** [comment]
Hey @thirdeyenick, In 9.3.0 a placeholder was introduce in the limit field to make this clearer. I'll close this as I believe that'd solve your issue. Thanks for your report!
<img width="603" alt="Screenshot 2023-01-17 at 11 42 28" src="https://user-images.githubusercontent.com/74534993/212878609-11770a59-e2d6-4a2b-af0b-5b6624dc4436.png">

**Comment by thirdeyenick** [comment]
Thank you very much!
