### ISSUE TITLE
[BUG] Bar Chart does not show data with template query variable ALL option

### ISSUE THREAD

**Issue by web-data-sci** [grafana/grafana#6126]
Grafana Version - 1.9.1
Datasource - opentsdb
Issue details - 
1. I have a query template variable set to 'ALL' value. Possible variable values are 'true' and 'false'
2. If a chart data contains data for only for one value (either true or false), bar chart does not show any data points when 'ALL' option is selected for templating.
3. 'Points' chart displays value for the same chart with 'ALL' option. 'Line' chart does not show any data points.

**Comment by torkelo** [comment]
Can you show your metric query and response from your TSDB?

**Comment by web-data-sci** [comment]
I will not be able to share response/query details  due to data sensitivity issues. I am sorry about that.
Here are some details from chrome dev tools if it helps - 
Data from TSDB queries is returned correctly. I see timeseries data in response when template variable value  = 'true'. TSDB query with template variable value  = 'false' does not return any data. 
Bar chart shows data when query variable = 'true' but does not show any data when query variable = 'ALL' (include true and false). If I switch chart mode to 'point' instead of 'bar', chart shows data for 'ALL'

**Comment by torkelo** [comment]
There has been no similar reports on issue with bar chart.  Need the metric data you query returns to try to replicate.  Maybe you have stack enabled and there are null values returned?

**Comment by web-data-sci** [comment]
Thanks for the follow up. It turns out that data is getting to bar chart correctly but bars are too thin and are not visible for 15 minutes range. After zooming and narrowing range to 1 second, bar chart is visible.
Is there any workaround/configuration to increase bar width?

**Comment by torkelo** [comment]
@web-data-sci yes of course, the bar width can easily be changed by changing the group by time in your metric query (the size of buckets / distance betwen points in the metrics returned from your TSDB backend). 

How you do that depeneds on your TSDB (they all have different mechanics to specify interval between points)
