### ISSUE TITLE
Explore: Split screen, sync time range, close a view and sync indicator (orange color) still visible

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#61272]
Maybe this is the new intended behavior but I find it bit strange. Maybe when the user clicks the split button the sync time range should activated by default instead?

**What happened**:
![Kapture 2023-01-11 at 12 14 12](https://user-images.githubusercontent.com/562238/211792545-a5bef98a-1601-4fad-b4bd-b3b8ccdb0b3a.gif)

1. Split the Explore window
2. Click the sync time range in all views button
3. The time range sync color appears [OK]
4. Close one of the views with the close button
5. View should be closed and the time range picker should go back to normal without the synced time (orange color) indicator 

**What you expected to happen**:
Time range indicator should go back to normal?

**How to reproduce it (as minimally and precisely as possible)**:
See movie

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Play v9.3.2. 67a213dc85 but also in v9.3.2
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by Elfo404** [comment]
Thank you for reporting this Hugo! <3

Can reproduce easily on main, i agree this shouldn't happen (also i don't think automatically syncing time ranges on split is something we ever considered and i'm not aware of anyone requesting that behaviour before)
