### ISSUE TITLE
QueryEditor: Improve support for query editors when changing data source type

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#61280]
**What happened**:
During the work with https://github.com/grafana/grafana/pull/60218 I saw that we have duplicated logic for how to create and change queries. We have some logic used by alerting and some other logic being used by the dashboards/panel edit.

Currently, in alerting, we are not supporting changing data source properly.  We keep some of the values in the query model even if you change to a data source of a completely different type. This can cause the query editor to break or behave unexpectedly.

**What you expected to happen**:
I think it would be a good idea to align the logic for creating and clearing queries when changing data sources or adding a new query.  We should also apply the default values provided by the data source when clearing/adding queries.

References:
- https://github.com/grafana/grafana/pull/59625 (How to get defaults from a DS)
- https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx#L62
- https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/reducer.ts#L59

**Comment by soniaAguilarPeiron** [comment]
should we close this one?  I think this was fixed in this [PR](https://github.com/grafana/grafana/pull/66797) (see description)

**Comment by gillesdemey** [comment]
Correct, closing this one
