### ISSUE TITLE
elasticsearch derivatives  doesn't work in grafana 3.1.x 

### ISSUE THREAD

**Issue by fvigotti** [grafana/grafana#6128]
* **I'm submitting a ...**
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?  3.1.1 and 3.1.0
- What datasource are you using? elasticsearch 2.4.0
- What OS are you running grafana on? ubuntu 16.04
- What did you do?
very simple derivative query in grafana : 
I'll explain : looking around I've seen that  should be almost the same of moving Average.. 
you export a value using another standard function like f(max) on "tx" tag in example , then you apply the f(moving Average) using "Max tx" as target, 
ok, so.. moving average function works as expected... Derivative not!
I've also triend applying some unit value,  changed metrics , changed version of grafana ( supposed an introduction of some bug in 3.1.1 and moved back to 3.1.0.. )

- What was the expected result?
the line for the Average have values

- What happened instead?
the line for the Average have 0 values ( legend shows no max/min/avg/current/.. ) 
nothing gets displayed, no results.. no error in console
debugging query results in console I see that some value exists in the results ( which are full of null values ) .. but anyway probably grafana isn't able to use it...
here is an excerpt 

```json
{"key_as_string":"1474906610000","key":1474906610000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906620000","key":1474906620000,"doc_count":1,"3":{"value":1.25965819904E11},"1":{"value":null}},{"key_as_string":"1474906630000","key":1474906630000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906640000","key":1474906640000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906650000","key":1474906650000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906660000","key":1474906660000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906670000","key":1474906670000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906680000","key":1474906680000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906690000","key":1474906690000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906700000","key":1474906700000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906710000","key":1474906710000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906720000","key":1474906720000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906730000","key":1474906730000,"doc_count":0,"3":{"value":null},"1":{"value":null}},{"key_as_string":"1474906740000","key":1474906740000,"doc_count":1,"3":{"value":1.25996486656E11},"1":{"value":null}},
```

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
It works fine
http://play.grafana.org/dashboard/db/elasticsearch-derivative?panelId=1&fullscreen&edit

![image](https://cloud.githubusercontent.com/assets/10999/18845121/b25300c2-8420-11e6-873b-
85a24089bb21.png)

Double check your date histogram group by interval (you can set a lower limit in the group by time box below your queries), or maybe min_doc count can effect it.
