### ISSUE TITLE
Dashboard Search: misleading empty state message when filtering dashboards in a folder

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#61293]
**What happened**:
When using the dashboard search page, if the current folder has no starred dashboard (or in general, the search doesn't match any dashboard, ie. by filtering for tags) an empty state screen is shown informing the user that the current folder does not contain any dashboard. This is misleading as the folder does in fact contains dashboards, they just do not match the given filters.

https://user-images.githubusercontent.com/1170767/211825157-c58c429c-cf55-4d67-a638-a3deac5f7bdc.mov

Additionally, once in that state, there's no way to reset the filters without navigating away from the folder:

https://user-images.githubusercontent.com/1170767/211825573-892eea44-6b58-4e28-93df-f3afc0172f41.mov

Additionally^2, clicking on "clear search and filters" in the main page doesn't remove the starred filter.

**What you expected to happen**:
1. a different empty state message, stating that the current filters do not match any dashboard in the current folder
2. a way to clear filters from said empty state
3. clicking on "clear search and filters" should remove the starred filter.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: `main`

**Comment by joshhunt** [comment]
This only happens with old search - without the `panelTitleSearch` feature flag. New search also has a seperate problem which I'll raise seperately!

**Comment by Elfo404** [comment]
FYI
> Additionally^2, clicking on "clear search and filters" in the main page doesn't remove the starred filter.

this also happens with `panelTitleSearch` on
