### ISSUE TITLE
Grafana MySQL backend !

### ISSUE THREAD

**Issue by gugansankar** [grafana/grafana#6130]
Grafana - 3.1.1
OS - CentOS 7
Datastore - InfluxDB
Backend  - MariaDB [ for user / Dashboard ]

I tried to use MariaDB instead of Sqlite for Grafana backend. Its fresh grafana installation. I added my MariaDB setting in grafana.ini file and tried to restart it. But not working.

It shows below error

016-09-27T13:15:49+0530 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2016-09-27T13:15:49+0530 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2016-09-27T13:15:49+0530 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2016-09-27T13:15:49+0530 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2016-09-27T13:15:49+0530 lvl=info msg="Initializing DB" logger=sqlstore dbtype=mysql
t=2016-09-27T13:15:49+0530 lvl=info msg="Starting DB migration" logger=migrator
**t=2016-09-27T13:15:49+0530 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: Error 1045: Access denied for user 'grafana'@'localhost' (using password: YES)\n"**

I confirmed there is no issue on authentication:

[root@srv1 grafana]# mysql -u grafana -pgraf83#
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1345
Server version: 5.5.50-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> \q
Bye

Grafana.ini file entries for MySQL:
--------------------------------
[database]
;type = sqlite3
;host = 127.0.0.1:3306
;name = grafana
;user = root
;password =

type = mysql
host = 127.0.0.1:3306
name = grafana
user = grafana
password = graf83#

;ssl_mode = disable
ssl_mode = false

;path = grafana.db

#################################### Session ####################################
[session]

;provider = file
provider = mysql

;provider_config = sessions
provider_config = `grafana:graf83#@tcp(127.0.0.1:3306)/grafana`

;cookie_name = grafana_sess

;cookie_secure = false

;session_life_time = 86400

--------------------------------------------------------

Not sure, whats wrong in the setup. Please help on this.

**Comment by torkelo** [comment]
try quoting the value 
```
password = "graf83#"
```

**Comment by Tremorus** [comment]
The database user’s password (not applicable for sqlite3). If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
