### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zihaoyu** [grafana/grafana#6133]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  Nightly build

- What datasource are you using?
  Postgres
- What OS are you running grafana on?
  Docker on CoreOS

- What did you do?
  Save dashboards

- What was the expected result?
  Dashboards are saved

- What happened instead?
  Error. Have to try again. See a lot of this message in the log:
 ```
t=2016-09-27T19:54:03+0000 lvl=eror msg="Panic in resultDispatcher" logger=alerting.engine error="runtime error: invalid memory address or nil pointer dereference" stack="[engine.go:104 asm_amd64.s:472 panic.go:443 panic.go:62 sigpanic_unix.go:24 notifier.go:86 notifier.go:49 result_handler.go:88 engine.go:109]"
```

**Comment by Fox32** [comment]
Not sure if related, but I also get a similar error message from today nightly (also via Docker).
However in my situation in is happening while sending an alert notification:

```
t=2016-09-28T13:31:00+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=4 newState=alerting oldState=ok
t=2016-09-28T13:31:00+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=4
t=2016-09-28T13:31:00+0000 lvl=info msg=Rendering logger=png-renderer url="http://192.168.1.95/dashboard-solo/db/alerts-inter246?&panelId=1"
t=2016-09-28T13:31:03+0000 lvl=eror msg="Panic in resultDispatcher" logger=alerting.engine error="runtime error: invalid memory address or nil pointer dereference" stack="[engine.go:98 asm_amd64.s:472 panic.go:443 panic.go:62 sigpanic_unix.go:24 notifier.go:85 notifier.go:48 result_handler.go:88 engine.go:104]"
```

**Comment by zihaoyu** [comment]
@Fox32 I think they are related, because I see that both error messages were from `logger=alerting.engine`.

**Comment by Fox32** [comment]
But looks like I was running a much older version that I thought I would run. The version was already 2 weeks old, so maybe it's not relevant anymore.

**Comment by bergquist** [comment]
@zihaoyu since master is moving rapeidly it would be good to know which git commit your grafana is using. You can find it in the footer at any none dashboard page, ex /profile

**Comment by Fox32** [comment]
I updaten to a newer one yesterday, but still get an error:

```
t=2016-09-29T01:55:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=5 newState=ok oldState=alerting
t=2016-09-29T01:55:31+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=5
t=2016-09-29T01:55:31+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/alerts-inter246?&panelId=2"
t=2016-09-29T01:55:32+0000 lvl=eror msg="Panic in resultDispatcher" logger=alerting.engine error="runtime error: invalid memory address or nil pointer dereference" stack="[engine.go:104 asm_amd64.s:472 panic.go:443 panic.go:62 sigpanic_unix.go:24 notifier.go:86 notifier.go:49 result_handler.go:88 engine.go:109]"
```

I'm on ```Grafana v4.0.0-pre1 (commit: 2750c8a)```

**Comment by bergquist** [comment]
This was fixed by https://github.com/grafana/grafana/commit/1a062c52fa62064735610b6bb86d2bf1f8ad3e37 Should be available in latest build in ~10min
