### ISSUE TITLE
UI needs to respond to system theme

### ISSUE THREAD

**Issue by mateuszdrab** [grafana/grafana#61339]
Grafana does not follow the system theme when the color scheme is set to default.

This is very eye sore and inconvenient to change manually twice a day. 
Grafana should follow the preferred system scheme and adjust accordingly.

**Steps to reproduce**:
- change OS to dark mode
**Actual Result**:
- grafana does not respond
- dark theme added by dark reader causes some UI elements to be hard to read. The addon is not available on mobile devices.
**Expected Result**
- grafana responds to system's preferred color scheme
**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: N/A
- User OS & Browser: Edge on any platform
- Others:

**Comment by usmangt** [comment]
Hi @mateuszdrab,

Thanks for opening this issue.

I do not have an OS system to reproduce this case by changing the OS theme from White to Dark mode. Therefore will ask our team to have a look and get more information from them.

**Comment by mateuszdrab** [comment]
> Hi @mateuszdrab,
> 
> 
> 
> Thanks for opening this issue.
> 
> 
> 
> I do not have an OS system to reproduce this case by changing the OS theme from White to Dark mode. Therefore will ask our team to have a look and get more information from them.
> 
> 
> 
> 

No problem, I really hope it can be fixed or at least an easier way to switch the theme can be added (one click button similarly to what the default web UI of Prometheus does)

**Comment by joshhunt** [comment]
Good suggestion - I can't think of a good reason why we wouldn't offer this as an option.

**Comment by mateuszdrab** [comment]
> Good suggestion - I can't think of a good reason why we wouldn't offer this as an option.

Can't wait for that, I use Grafana daily in my home lab with a vast of tweaked dashboards and some of them look really bad in dark mode (from Dark Reader, look fine in Grafana's dark more). 
Happy to post a screenshot.
