### ISSUE TITLE
Elasticsearch data source documentation says v8.0+ is experimental

### ISSUE THREAD

**Issue by raulmarinperez** [grafana/grafana#61346]
**What happened**:
Elasticsearch data source documentation says v8.0+ is experimental and, at this moment, it's not (https://grafana.com/docs/grafana/latest/datasources/elasticsearch/)
**What you expected to happen**:
The (experimental) text should be removed.
**How to reproduce it (as minimally and precisely as possible)**:
Go to this URL: https://grafana.com/docs/grafana/latest/datasources/elasticsearch/
**Anything else we need to know?**:

**Environment**:
- Grafana version: Latest
- Data source type & version: Elasticsearch data source
- OS Grafana is installed on: -
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by gabor** [comment]
NOTE: we should also adjust the mouse-over text in the datasource-config page, when you choose the elastic-version (it also says "experimental" there)
