### ISSUE TITLE
During the building of a linux Docker image using the Dockerfile in the root the file 'ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz" cannot be found

### ISSUE THREAD

**Issue by DouglasBritton** [grafana/grafana#61347]
I have an Azure pipeline which uses an Azure agent (specification: ubuntu-latest) to build and push a linux grafana docker image to an Azure container registry. This pipeline worked for an older version of grafana that I cloned around the 15th of November and I had not made any changes to the grafana code that was built.

After I updated to the latest code in the grafana repo (commit f85a948) during the building of the image I now get the following issue
__________________________________________________________________________________________________
Step 38/68 : ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"
 ---> Running in 5d341c1fe41a
Removing intermediate container 5d341c1fe41a
 ---> 60ef4ae29475
Step 39/68 : COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz
COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist
##[error]COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Build and push an image to container registry
__________________________________________________________________________________________________
The file "grafana-latest.linux-x64-musl.tar.gz" doesn't exist in the root of the repository.

I have posted in the forums (https://community.grafana.com/t/cannot-build-docker-image-using-commit-id-4de0149/79504) but thought I'd also create it as an issue.

**Comment by DouglasBritton** [comment]
Hi @usmangt,
Thanks for reaching out.

- I am trying to build a linux based docker image using the dockerfile in the root of the repository using an Azure pipeline that uses a Azure agent on ubuntu-latest. So the image is being built on a linux agent.
- The version of grafana I am trying to build a docker image of is the repo at commit f85a948.
- I have not added any grafana configuration or provisioning to the repository. Therefore I have no datasource, visualization panel etc or other customisation except for the pipeline yaml which was required to create the pipeline. I did have this pipeline building a docker image for a version of grafana I cloned around the 15th of November 2022 (apologies I don't have the specific commit).
- I didn't follow any particular instruction to build the docker image apart from to set the pipeline up to run the dockerfile
- What I expect to happen is for the docker image to be built successfully.
- What happened was that during the building on the docker image I received this error message in the logs
Start of the build log
_________________________________________
Step 1/68 : ARG BASE_IMAGE=alpine:3.15
Step 2/68 : ARG JS_IMAGE=node:16-alpine3.15
Step 3/68 : ARG GO_IMAGE=golang:1.19.4-alpine3.17
Step 4/68 : ARG GO_SRC=go-builder
Step 5/68 : ARG JS_SRC=js-builder
Step 6/68 : FROM ${JS_IMAGE} as js-builder
16-alpine3.15: Pulling from library/node
___________________________________________________________________________________________________
Skip to the build error
___________________________________________________________________________________________________
Step 38/68 : ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"
---> Running in 5d341c1fe41a
Removing intermediate container 5d341c1fe41a
---> 60ef4ae29475
Step 39/68 : COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz
COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist
##[error]COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Build and push an image to container registry
_________________________________________
This error in the build logs suggests that the 'grafana-latest.linux-x64-musl.tar.gz' is missing from the repo but I can't find any information about this file.

I know that an issue with the docker image building was looked at here - https://github.com/grafana/grafana/issues/61134 so I've made sure that the version of grafana I am building is after that issue was fixed.

If you need any more information please let me know.

**Comment by mohamed9974** [comment]
I'm facing the same exact issue.

**Comment by mohamed9974** [comment]
found a simple work around that you remove the ``` 
ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"

COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz

# add -v to make tar print every file it extracts
RUN tar x -z -f /tmp/grafana.tar.gz --strip-components=1 ``` 

and replace them with ``` COPY grafana/public ./public
COPY ./scripts ./scripts
COPY ./plugins-bundled ./plugins-bundled

**Comment by kminehart** [comment]
I don't think this is a problem anymore after we've made a few dockerfile updates. Sorry about the inconvenience caused. If it's still an issue on main or the v9.4.x feel free to reopen.

FYI make sure you're using `docker buildx build`

**Comment by kelokeloo** [comment]
I figured out the root cause - the issue arises from the missing grafana-latest.linux-x64-musl.tar.gz file. You can download this file from https://dl.grafana.com/oss/release/grafana-latest.linux-x64-musl.tar.gz. After downloading, place the file in the root directory and then run the docker build command.
My grafana version: 11.5.1。

特别得，当你在中国大陆，你运行Dockerfile可能会非常卡，因此我对Dockerfile做了改造
1. 修改为国内源
2. 替换了Dockfile中下载glibc-bin-2.40.tar.gz的逻辑，转换为直接使用根路径的glibc-bin-2.40.tar.gz

当你docker build之前，你需要把grafana-latest.linux-x64-musl.tar.gz、glibc-bin-2.40.tar.gz下载到项目根目录，然后docker build
修改后的Dockfile见：
```Dockerfile
# syntax=docker/dockerfile:1

# to maintain formatting of multiline commands in vscode, add the following to settings.json:
# "docker.languageserver.formatter.ignoreMultilineInstructions": true

ARG BASE_IMAGE=alpine:3.20
ARG JS_IMAGE=node:22-alpine
ARG JS_PLATFORM=linux/amd64
ARG GO_IMAGE=golang:1.23.5-alpine

# Default to building locally
ARG GO_SRC=go-builder
ARG JS_SRC=js-builder

# Javascript build stage
FROM --platform=${JS_PLATFORM} ${JS_IMAGE} AS js-builder

ENV NODE_OPTIONS=--max_old_space_size=8000

WORKDIR /tmp/grafana

COPY package.json project.json nx.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
COPY packages packages
COPY public public
COPY LICENSE ./
COPY conf/defaults.ini ./conf/defaults.ini
COPY e2e e2e

# 配置国内源
RUN sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories

RUN apk add --no-cache make build-base python3

RUN yarn install --immutable

COPY tsconfig.json eslint.config.js .editorconfig .browserslistrc .prettierrc.js ./
COPY scripts scripts
COPY emails emails

ENV NODE_ENV=production
RUN yarn build

# Golang build stage
FROM ${GO_IMAGE} AS go-builder

ARG COMMIT_SHA=""
ARG BUILD_BRANCH=""
ARG GO_BUILD_TAGS="oss"
ARG WIRE_TAGS="oss"
ARG BINGO="true"

# 配置国内源
RUN sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories

RUN if grep -i -q alpine /etc/issue; then \
      apk add --no-cache \
          # This is required to allow building on arm64 due to https://github.com/golang/go/issues/22040
          binutils-gold \
          bash \
          # Install build dependencies
          gcc g++ make git; \
    fi

WORKDIR /tmp/grafana

COPY go.* ./
COPY .bingo .bingo

# Include vendored dependencies
COPY pkg/util/xorm pkg/util/xorm
COPY pkg/apiserver pkg/apiserver
COPY pkg/apimachinery pkg/apimachinery
COPY pkg/build pkg/build
COPY pkg/build/wire pkg/build/wire
COPY pkg/promlib pkg/promlib
COPY pkg/storage/unified/resource pkg/storage/unified/resource
COPY pkg/storage/unified/apistore pkg/storage/unified/apistore
COPY pkg/semconv pkg/semconv
COPY pkg/aggregator pkg/aggregator
COPY apps/playlist apps/playlist
COPY apps/investigation apps/investigation
COPY apps/advisor apps/advisor
COPY apps apps
COPY kindsv2 kindsv2
COPY apps/alerting/notifications apps/alerting/notifications
COPY pkg/codegen pkg/codegen
COPY pkg/plugins/codegen pkg/plugins/codegen

# 配置国内源
RUN go env -w GOPROXY=https://goproxy.cn

RUN go mod download
RUN if [[ "$BINGO" = "true" ]]; then \
      go install github.com/bwplotka/bingo@latest && \
      bingo get -v; \
    fi

COPY embed.go Makefile build.go package.json ./
COPY cue.mod cue.mod
COPY kinds kinds
COPY local local
COPY packages/grafana-schema packages/grafana-schema
COPY public/app/plugins public/app/plugins
COPY public/api-merged.json public/api-merged.json
COPY pkg pkg
COPY scripts scripts
COPY conf conf
COPY .github .github

ENV COMMIT_SHA=${COMMIT_SHA}
ENV BUILD_BRANCH=${BUILD_BRANCH}

RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}

# From-tarball build stage
FROM ${BASE_IMAGE} AS tgz-builder

WORKDIR /tmp/grafana

ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"

COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz

# add -v to make tar print every file it extracts
RUN tar x -z -f /tmp/grafana.tar.gz --strip-components=1

# helpers for COPY --from
FROM ${GO_SRC} AS go-src
FROM ${JS_SRC} AS js-src

# Final stage
FROM ${BASE_IMAGE}

LABEL maintainer="Grafana Labs <hello@grafana.com>"

ARG GF_UID="472"
ARG GF_GID="0"

ENV PATH="/usr/share/grafana/bin:$PATH" \
    GF_PATHS_CONFIG="/etc/grafana/grafana.ini" \
    GF_PATHS_DATA="/var/lib/grafana" \
    GF_PATHS_HOME="/usr/share/grafana" \
    GF_PATHS_LOGS="/var/log/grafana" \
    GF_PATHS_PLUGINS="/var/lib/grafana/plugins" \
    GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

WORKDIR $GF_PATHS_HOME

# 配置国内源
RUN sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories

# Install dependencies
RUN if grep -i -q alpine /etc/issue; then \
      apk add --no-cache ca-certificates bash curl tzdata musl-utils && \
      apk info -vv | sort; \
    elif grep -i -q ubuntu /etc/issue; then \
      DEBIAN_FRONTEND=noninteractive && \
      apt-get update && \
      apt-get install -y ca-certificates curl tzdata musl && \
      apt-get autoremove -y && \
      rm -rf /var/lib/apt/lists/*; \
    else \
      echo 'ERROR: Unsupported base image' && /bin/false; \
    fi

# glibc support for alpine x86_64 only
# docker run --rm --env STDOUT=1 sgerrand/glibc-builder 2.40 /usr/glibc-compat > glibc-bin-2.40.tar.gz
ARG GLIBC_TGZ="glibc-bin-2.40.tar.gz"
# 先將本地文件複製到容器內
COPY ${GLIBC_TGZ} /tmp/${GLIBC_TGZ}

RUN if grep -i -q alpine /etc/issue && [ `arch` = "x86_64" ]; then \
      tar zxf /tmp/${GLIBC_TGZ} -C / \
        usr/glibc-compat/lib/ld-linux-x86-64.so.2 \
        usr/glibc-compat/lib/libc.so.6 \
        usr/glibc-compat/lib/libdl.so.2 \
        usr/glibc-compat/lib/libm.so.6 \
        usr/glibc-compat/lib/libpthread.so.0 \
        usr/glibc-compat/lib/librt.so.1 && \
      mkdir /lib64 && \
      ln -s /usr/glibc-compat/lib/ld-linux-x86-64.so.2 /lib64; \
    fi

COPY --from=go-src /tmp/grafana/conf ./conf

RUN if [ ! $(getent group "$GF_GID") ]; then \
      if grep -i -q alpine /etc/issue; then \
        addgroup -S -g $GF_GID grafana; \
      else \
        addgroup --system --gid $GF_GID grafana; \
      fi; \
    fi && \
    GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \
    mkdir -p "$GF_PATHS_HOME/.aws" && \
    if grep -i -q alpine /etc/issue; then \
      adduser -S -u $GF_UID -G "$GF_GID_NAME" grafana; \
    else \
      adduser --system --uid $GF_UID --ingroup "$GF_GID_NAME" grafana; \
    fi && \
    mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
             "$GF_PATHS_PROVISIONING/dashboards" \
             "$GF_PATHS_PROVISIONING/notifiers" \
             "$GF_PATHS_PROVISIONING/plugins" \
             "$GF_PATHS_PROVISIONING/access-control" \
             "$GF_PATHS_PROVISIONING/alerting" \
             "$GF_PATHS_LOGS" \
             "$GF_PATHS_PLUGINS" \
             "$GF_PATHS_DATA" && \
    cp conf/sample.ini "$GF_PATHS_CONFIG" && \
    cp conf/ldap.toml /etc/grafana/ldap.toml && \
    chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
    chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

COPY --from=go-src /tmp/grafana/bin/grafana* /tmp/grafana/bin/*/grafana* ./bin/
COPY --from=js-src /tmp/grafana/public ./public
COPY --from=js-src /tmp/grafana/LICENSE ./

EXPOSE 3000

ARG RUN_SH=./packaging/docker/run.sh

COPY ${RUN_SH} /run.sh

USER "$GF_UID"
ENTRYPOINT [ "/run.sh" ]
```
