### ISSUE TITLE
Alerting: Pause alert rule

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6135]
- [ ] From Alert List 
- [ ] From Alert Tab

**Comment by Dieterbe** [comment]
what are the use cases for this?

related: surpression of alerts for planned and unplanned maintenances.  this would typically surpress alert notifications for several applicable alert rules, and "parts" of rules (like when you have a wildcard in a query and the thing being under maintenance is a subset of the values of the wildcard)

**Comment by torkelo** [comment]
Alert silence rules will be that, temporary rules with conditions (for example silence rules where alert name contains `SomeWord`, silence alert rules for category frontend,  silence alerts for metric `backend-01`, and you specify for how long the silence rule should exists (like 10min, 1hour etc). 

The pause mechanic is more a way to disable a rule completly. Maybe it's not right right now and needs to be redesigned etc. But will also act like a temporary silence feature as we do not have a silence mechanic /concept implemented yet.

**Comment by bergquist** [comment]
I'm not sure I like the idea of having call to actions on the alert list panel. I think it should have a clean layout for listing alerts. 

Should it be possible to pause alerts from the alert tab?

**Comment by torkelo** [comment]
let's only have the pause feature from alert list page to begin with
