### ISSUE TITLE
Alerting: Show panel has alert rule (and current state) 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6136]

**Comment by bulletfactory** [comment]
![alerting_enabled](https://cloud.githubusercontent.com/assets/1950595/18917939/2cc26518-8567-11e6-88c8-770a538e26bf.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/18997425/883ddc96-8734-11e6-8323-12296d0eb1e0.png)
