### ISSUE TITLE
Trace View: Export trace as JSON

### ISSUE THREAD

**Issue by adrapereira** [grafana/grafana#61377]
Requires #61373

We want to make it easier for users to share Traces while troubleshooting a problem, so let's add a button to the top right of the Trace View header that will export the current trace as JSON. When the user click the button a file should be downloaded in the format `<traceID>.json`. If it's possible to know the size of the file beforehand it would be nice to add it to the button, for example `Export (260 KB)`

![Image](https://user-images.githubusercontent.com/4313971/212081116-df9c61ee-857b-4158-832b-c1e241c7f44e.png)

Actions:

- [x] Feature tracking

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/grafana/pull/67368
