### ISSUE TITLE
Alert is not triggering if the firing condition is equals to 0

### ISSUE THREAD

**Issue by prabin-lc** [grafana/grafana#61378]
Alert is not firing even if the conditions are met

I have a metric whose value can be any of -1, 0, or 1. I have set the alert to fire if the metric value is 0.

The alert doesn't fire when the metric value is 0. The alert fires, if I set the same alert(with the same search time range and other parameters) to fire when the metric value is 1.

Have a metric whose value is 0. Set alert query as `metric == 0`.
When you run the query, the data is seen but the alert never goes to the pending or firing state.

I believe that the alert isn't firing only when it is compared with the value 0. If I set the query as (metric + 1) == 1, the same alert fires.

- Grafana version: 9.1.5
- Data source type & version: Prometheus 2.37.1
- OS Grafana is installed on: Official grafana docker image running on Ubuntu
- User OS & Browser: MacOS and Chrome
- Grafana plugins: none

https://user-images.githubusercontent.com/51957981/212086541-bff85b13-c743-4b03-979a-af5b6e589658.mov

**Comment by prabin-lc** [comment]
Hi @tonypowa,

The alert fires with the condition `metric != 0`.

On further exploring, I found that the correct query, in this case, would be:
`metric == bool 0`

The question now remains: why is `metric == 1` allowed and not `metric == 0`?
It is a bit inconsistent.

I also couldn't find the exact documentation that describes this behavior.

**Comment by tonypowa** [comment]
thanks for the reply @prabin-lc 

i am tagging the alerting squad to see if they can describe whether or not that is expected behavior

**Comment by grobinson-grafana** [comment]
Hi! :wave:

In Prometheus, queries that contain comparisons such as `==`, `>` and `<` filter the data returned from the query. They are not boolean comparisons. If we look at the example in the screenshot, `up{job="foo"} == 0` will return just the metrics where `up{job="foo"}` is `0`.

If you want to do a boolean comparison you can either add a Threshold expression, or use the `bool` modifier as explained here https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators.

**Comment by prabin-lc** [comment]
Hi George,

Apologies for reopening, But I have a question.

If this `up{job="foo"} == 0` just filters the metrics, shouldn't this trigger the alert if some metric exists? Just like when the alert triggers with the query `up{job="foo"} == 1`.

Sorry if this is trivial.

**Comment by filintod** [comment]
having the same issue, had to do the `bool` operation, even in the docs https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating, how does `InstanceDown` get triggered in grafana when `up == 0`?

running tests in promtool also works without `bool`

**Comment by ethirolle** [comment]
Perhaps the difference is whether your PromQL query returns a scalar or a vector. Per the Prometheus docs [here](https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators):

> Comparison operators are defined between scalar/scalar, vector/scalar, and vector/vector value pairs. By default they filter. Their behavior can be modified by providing `bool` after the operator, which will return `0` or `1` for the value rather than filtering.
> 
> **Between two scalars**, the `bool` modifier must be provided and these operators result in another scalar that is either `0` (`false`) or `1` (`true`), depending on the comparison result.

All alert rules are instant queries... but `up{job="foo"}` returns a scalar (i.e., a single number), while `up` returns  an "instant vector" (a set of time series containing a single sample for each time series, all sharing the same timestamp). A vector/scalar comparison does not require `bool`, so `up == 0` is fine for an alert expression. But `up{job="foo"}` returns a _scalar_, so you have to provide the `bool` modifier, like `up{job="foo"} == bool 0`.

(See https://prometheus.io/docs/prometheus/latest/querying/basics/#expression-language-data-types for definitions of vector vs scalar).
