### ISSUE TITLE
[Feature Request - Traces Visualization] Copy/Paste trace or span details as JSON and/or Markdown2

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/grafana#61391]
When troubleshooting a performance problem, I want to capture the details of a span or a trace copying all its details (incl attributes, resource attributes, and events) as JSON and/or as Markdown.
JSON would be my preference.

I would like this GUI to be consistent with:

* https://github.com/grafana/grafana/issues/61393

![image](https://user-images.githubusercontent.com/459691/212074638-4f85f2b3-863e-40bd-889e-cfd60aac2800.png)

**Comment by 09jvilla** [comment]
@cyrille-leclerc -- Now that we have the trace 'Export' button, which downloads the trace as json in OpenTelemetry Json format as defined [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto), would you consider this issue complete?

Today, the user still can't do a bulk copy of all attributes on a per-span level. They'd have to download the trace json and then pull out the details on the span they care about. Do you think this is problematic? How often do you think users want these details at a span level vs at a full trace level?

**Comment by 09jvilla** [comment]
![Screenshot 2023-08-23 at 9 11 19 AM](https://github.com/grafana/grafana/assets/9610816/d0c379a0-482f-42c9-b9e9-78c9baf85f9b)
