### ISSUE TITLE
Sending large alerts to Discord fails

### ISSUE THREAD

**Issue by adi** [grafana/grafana#61400]
**What happened**:
When using the Discord contact point some messages fail to be sent because they exceed the "content" field limit of 2000 characters.

**What you expected to happen**:
Grafana should not try to send Discord messages that are too large. The Discord payload is documented here: https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

**How to reproduce it (as minimally and precisely as possible)**:
Send a custom test Discord alert with a large enough key/value pair to make "content" exceed 2000 characters.

**Anything else we need to know?**:
When receiving a 400 Bad Request, you also receive a JSON with the reason. It would be nice to print it at least to the logs to make debugging much easier. It can also be printed in the error toast.

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: not important
- OS Grafana is installed on: not important
- User OS & Browser: not important
- Grafana plugins: none
- Others: none

**Comment by yuri-tceretian** [comment]
The fix is already there  https://github.com/grafana/grafana/pull/60592 and will be released in 9.4.0.
