### ISSUE TITLE
Unable to Save Dashboard with `validateDashboardsOnSave` Feature Toggle

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/grafana#61418]
**What happened**:

Using Grafana v9.3.2 (Enterprise), I tried to create a simple Dashboard using a single panel with the TestDataDB Datasource, but was unable to save the Dashboard.

In the logs, I see this error reported;

```
level=error msg="unable to parse dashboard" error="type assertion to []byte failed"
```

Similar also happens for a Prometheus Datasource

Screen Recording: ![Peek 2023-01-12 11-31](https://user-images.githubusercontent.com/102023327/212141044-9046f6c3-7555-421c-89be-d51f7a489272.gif)

**What you expected to happen**:

The dashboard should save, and no error returned.

**How to reproduce it (as minimally and precisely as possible)**:

- Run Grafana (tested on `v9.3.2 (21c1d14e91)` with the `validateDashboardsOnSave` Feature Toggle Enabled.
- Enable TestData DB Datasource (either manually or through provisioning)
- Create a New Dashbaord
- Select Add a New Panel
- Select TestData DB Datasource (if not default)
- Leave Values as is.
- Press Save button to Save Dashboard

**Anything else we need to know?**:

If you remove the `validateDashboardsOnSave` flag it works as expected.

Downgrading to v9.2.8, and leaving this Feature Flag enabled it also works as expected.

This is the data from the JSON Model of the Dashboard;

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "version": 0,
  "weekStart": ""
}
```

**Environment**:
- Grafana version: v9.3.2 (21c1d14e91)
- Data source type & version: TestDataDB
- OS Grafana is installed on: Linux (Manjaro), using Docker with `latest` Tag for Grafana
- User OS & Browser: Manjaro, Chrome 108.0.5359.124
- Grafana plugins: None
- Others: Run in Docker

**Comment by natellium** [comment]
@SeamusGrafana is this still an issue? I believe we no longer have that toggle

**Comment by SeamusGrafana** [comment]
Yeah, looks like the toggle has gone in current versions, so will close this.
