### ISSUE TITLE
Override Relative Time and Panel Title text layout issue

### ISSUE THREAD

**Issue by dtanner** [grafana/grafana#6142]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? influxdb
- What OS are you running grafana on?  os x
- What did you do?  Created a singlestat panel with a relative time override
- What was the expected result?  the title and relative time override text don't overlap
- What happened instead?  they overlap in common situations

![metric-time-override-issue](https://cloud.githubusercontent.com/assets/7769/18921201/8d486264-8569-11e6-848c-ed8b25c1189a.png)

The relative time override text is handy because it disappears when the override is disabled.  Singlestat panels are often fairly narrow, which makes the problem frequent for that situation.  So far the only workaround options I'm aware of to fix the issue are to use a short title, or hide the time override info.  There's room in the panel for them to both display; ideally the layout would be able to fit them both in.

**Comment by torkelo** [comment]
yes, you need to reduce the title length or increase the length of the panel so the text can fit

**Comment by yeborisov** [comment]
I also find this problematic. We must find a solution where we can align the panel title to left, right or center in order to get the correct view expectation.
