### ISSUE TITLE
Log volume: Show total number of displayed logs

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#61434]
For users it would be valuable to see amout/count of all logs displayed in log volume in Explore. We already got the data on count of logs, so it is just a matter of counting Total and figuring out where to display it.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/30407135/212178070-8fc0dd0b-a469-477b-ac2a-5ccd507878e9.png">

**Comment by ifrost** [comment]
A quick way of doing it could be using TimeSeries options (`calcs: ['sum']`) though that would give totals per each error, not totals if log volume is split by error type:

<img width="1514" alt="Screenshot 2023-01-13 at 11 59 35" src="https://user-images.githubusercontent.com/745532/212304827-7a40ca09-f55c-4932-b28e-4fdcef03b52b.png">

**Comment by ivanahuckova** [comment]
I honestly think that this is even better @ifrost!

**Comment by sladyn98** [comment]
@ivanahuckova I could take a shot at implementing this, could i get some code pointers.

**Comment by ivanahuckova** [comment]
@sladyn98 here is the place in code https://github.com/grafana/grafana/blob/main/public/app/features/explore/Graph/ExploreGraph.tsx#L171 where we need to add `(calcs: ['sum']) `,  but we would like to do this only for logs volume, not for all places where ExploreGraph is used.

**Comment by sladyn98** [comment]
@ivanahuckova Got it, I am a bit new to the codebase but  I was thinking of checking if the selcted panel here is logsVolume
and then adding the sum
```
      calcs: selectedPanel === 'logsVolume' ? ['sum'] : [],
```

Is there a way to get the selected panel ? Or am I getting the approach all wrong

**Comment by ivanahuckova** [comment]
One idea I've had would be adding a way to specify/override legend props, in the similar way as we do it with `tooltipDisplayMode`. What do you think @grafana/explore-squad?
