### ISSUE TITLE
Template variables not resolved for elasticsearch query aliases

### ISSUE THREAD

**Issue by olourkin** [grafana/grafana#6143]
* **I'm submitting a ...**
- [ X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4-1464167696
- What datasource are you using?
Elasticsearch
- What OS are you running grafana on?
CentOS 7
- What did you do?
Attempted to use a template variable in the Alias field
- What was the expected result?
resolved template variable
- What happened instead?
unresolved variable, displayed the template name instead

More info:
The template variable does resolve correctly elsewhere in the dashboard, including in the Elasticsearch query.  It just doesn't resolve in the Alias.

For example, this elasticsearch query works fine:
eventEnvironment: "$env" AND eventAction: "Job Order Detail Day deserialized for $env--Order"

But this Alias for the same query displays as is:
Job Order Detail Day deserialized for $env

**Comment by torkelo** [comment]
yes, this should definitely be implemented, 
closing this as I found an exisiting issue for it
https://github.com/grafana/grafana/issues/4075

**Comment by torkelo** [comment]
But your right, showing the UI should show staircase option when points is enabled as it works for both points and lines
