### ISSUE TITLE
Canvas: Improve connection creation UX

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#61439]
We can prevent arrows from being created on just a click on the connection point (without dragging)

https://user-images.githubusercontent.com/88068998/212171955-208521f9-eeaf-4fff-977f-8e1b7ed7c5f3.mov

See draw.io's approach to solving this below

https://user-images.githubusercontent.com/22381771/212216086-d7f45047-c75a-4a75-be08-53b6293f883e.mov

**Comment by xkilian** [comment]
This just illustrates that you are trying to redo some sort of draw.io clone as a grafana plugin. @torkelo 
This is a trap. You would need 4x times the dev ressources to even come close to implementing something that will work as a subset of what draw.io already does. It also puts the onus on the users to create all these dev heavy widgets before even getting value from the plugin.
Let draw.io create the diagram with all objects. The Canvas plugin then applies the rules, animations, data links, data mapping to the objects of the vector image. The flowcharting plugin approach is much more logical, integrated and scalable. Though it has its dev issues, it is a viable approach.
You really need to introspect and reevaluate how this plugin (Canvas) will deliver real value in an enterprise setting and not just UI candy(as is currently), even if all current open issues were to be closed as completed. If the desire is for a true draw.io clone with light dev objects (or better yet, no dev objects), then go for it, but it will be a long time coming and not a threat to all OT type visualisations platforms.
