### ISSUE TITLE
IPv6 webhook

### ISSUE THREAD

**Issue by bambooCZ** [grafana/grafana#61442]
**What happened**:

Hosted Grafana is unable to send alert webhook to IPv6:
```
Failed to send test alert.: Post "http://[2a02:xxx:3455]:8080/alert": dial tcp [2a02:xxx:3455]:8080: connect: cannot assign requested address
```

**What you expected to happen**:
I expect that the webhook works as it should.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alert contact point with IPv6 instead of domain of the webhook URL
2. Test the webhook

**Anything else we need to know?**:
IPv6 is only 12 years old feature. :face_with_head_bandage: 

**Environment**:
- Grafana version: v9.3.2-67a213dc85 (67a213dc85)
- OS Grafana is installed on: Hosted on grafana.net so IDK
- User OS & Browser: Firefox, Linux

**Comment by tonypowa** [comment]
👋  @bambooCZ  thank you for creating this issue,

 Only OSS issues should be submitted to the repo. 
 Please open a ticket with Support instead . They handle Grafana Cloud questions 👍
