### ISSUE TITLE
Create and edit label parameters in the template

### ISSUE THREAD

**Issue by chenxuyuanchen** [grafana/grafana#61453]
![image](https://user-images.githubusercontent.com/93701704/212275804-f1465e45-188c-4bfd-afd5-9c45c0e2ae49.png)
The main problem is that the label of the value in the early warning indicator is wrong. I think the picture may be clearer，
Here are the pictures I am using in detail
![_MG$F%(}YW~51JF_)0JV7MG](https://user-images.githubusercontent.com/93701704/212276897-7698dc35-98f6-48ce-a7bb-f7a0106c33e9.png)
If what I said is not correct. I hope it's a little help to add this parameter. Thank you！！！😘
I hope this page can be more detailed. It would be great if there were data in json format that alerted the return value of the template. And how to access and use it. That's really great
**Environment**:
- Grafana version:9.3
- Data source type & version:prometheus 2.37x
- OS Grafana is installed on:linux
Modify content page：https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-message-template/#keyvalue

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @chenxuyuanchen 

I have reached out to the Docs squad. Once I hear their feedback I will update this issue 👍

**Comment by tonypowa** [comment]
fyi @chenxuyuanchen a separate issue has been created to look into this.
 [here](https://github.com/grafana/grafana/issues/62019) 👍
