### ISSUE TITLE
data presentation bug in staircase mode with points enabled

### ISSUE THREAD

**Issue by anfedorov** [grafana/grafana#6146]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
v3.1.1
- What datasource are you using?
influx
- What OS are you running grafana on?
linux
- What did you do?
I graphed a bunch of data points
- What was the expected result?
extra points would not be added when I enable the staircase property on lines
- What happened instead?
extra data points where added when I turned on lines

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query

<img width="72" alt="good" src="https://cloud.githubusercontent.com/assets/9820/18179740/baa2cbd2-7038-11e6-8ca3-8366f0f61fa5.png"> good

<img width="103" alt="decent" src="https://cloud.githubusercontent.com/assets/9820/18179748/c37ea0a0-7038-11e6-8b94-98f30949ac55.png"> passable

<img width="92" alt="bad" src="https://cloud.githubusercontent.com/assets/9820/18179851/2d3c8e26-7039-11e6-8ef2-720b5722fbc7.png"> bug

as per issue #5950, it has been pointed out that this is because the implementation of staircase mode of a line modifies the dataset.

but staircase mode is the mode of a line, i.e. it is not available when the line is off. quite literally the checkbox is not in the UI when there is no line. staircase mode defines the shape of the line through the dataset, and that this implementation modifies the dataset to do so is an inelegant hack and a UX bug.

**Comment by torkelo** [comment]
closing as it's already been reported here: https://github.com/grafana/grafana/issues/5950

**Comment by torkelo** [comment]
But your right, the UI should show staircase option when points is enabled as it works for both points and lines
