### ISSUE TITLE
parse error at line 1, col 3: syntax error: unexpected IDENTIFIER, expecting = or =~ or !~ or !

### ISSUE THREAD

**Issue by alexcpn** [grafana/grafana#61472]
**What happened**:

The same problem like  - QueryFields/Input fields are broken in the recent browser #54535, in latest  loki-stack `loki-stack-2.8.9 ` which has grafana grafana:8.3.5 (helm chart)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

Installed loki-stack latest

```
helm list -n loki
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
loki    loki            1               2023-01-13 15:09:38.9407809 +0530 IST   deployed        loki-stack-2.8.9        v2.6.1
```
- Grafana version:

```
grafana/grafana:8.3.5`
```
- Others:

Corrected via downgrading grafana to 7.5.17

Updated manually the deployment to `Image: grafana/grafana:7.5.17`  as correction of https://github.com/grafana/grafana/issues/54535 and works

**Comment by usmangt** [comment]
Hi @alexcpn,

Thanks for opening this issue.

Grafana's current latest stable version is 9.3.1 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)) and the same case for Loki ([Changelog](https://github.com/grafana/loki/releases))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will now close this issue).
