### ISSUE TITLE
Maximum is below average..

### ISSUE THREAD

**Issue by Ebrink** [grafana/grafana#6148]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana 3.1.1 (commit a4d2708)

- What datasource are you using?
InfluxEnterprise 1.0.0

- What OS are you running grafana on?
Ubuntu 16.04.1

- What did you do?
For the interfaces on our core routers we are building traffic graphs for the past 12h, 24h, 1week, 1month, 1year and everything else. In these graphs we display the mean link utilisation and the maximum link utilisation. For 12h and 24h we only display the mean (5 minutes interval) utilisation, but for the other graphs we define larger intervals because queries get slow and so on. Thats why we want to know the mean utilisation and maximum utilisation of the interface.

- What was the expected result?
In our eyes, the maximum utilisation should be higher than the mean utilisation, showing this in a seperate line in the graph.

- What happened instead?
Often the maximum utilisation is lower than the mean utilisation, which we believe should not happen. See attached image.
<img width="1794" alt="screen shot 2016-09-29 at 11 06 00" src="https://cloud.githubusercontent.com/assets/20661811/18947800/cc853d64-8634-11e6-9c6f-b544559a068c.png">
Read this image as follows:
- IfHCInOctets average of an hour is drawn in the light green color that is set to fill.
- IfHCInOctets maximum of an hour is drawn in the dark green line.
- IfHCOutOctets average of an hour is drawn in the blue line.
- IfHCOutOctets maximum of an hour is drawn in pink.

You can see that the pink line drops under the average line every once in a while, which should not happen. And yes- the graphs are made to resemble the RRDtool graphs because we do not want to shock our users too much with this transition :)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
**Average InOctets query:**
SELECT non_negative_derivative(mean("ifHCInOctets"), 1s) *8 FROM "NetworkMeasurements" WHERE "agent_host" =~ /^agent_host$/ AND "ifAlias" =~ /^$CustomerName$/ AND $timeFilter GROUP BY time(1h), "ifAlias", "agent_host" fill(null)

**Maximum InOctets query:**
SELECT non_negative_derivative(max("ifHCInOctets"), 1s) *8 AS "Piek in" FROM "NetworkMeasurements" WHERE "agent_host" =~ /^agent_host$/ AND "ifAlias" =~ /^$CustomerName$/ AND $timeFilter GROUP BY time(1h), "ifAlias", "agent_host" fill(null)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
**Response:**
{"results":[{"series":[{"name":"NetworkMeasurements","tags":{"agent_host":"/^agent_host$/","ifAlias":" PRIMARY"},"columns":["time","non_negative_derivative"],"values":[[1474365600000,2.4802618923435763e+08],[1474372800000,2.418898176913021e+08],[1474380000000,1.7509107180402777e+08],[1474387200000,9.449484109675348e+07],[1474394400000,7.91157794201389e+07],[1474401600000,6.766503371602431e+07],[1474408800000,4.664826318600694e+07],[1474416000000,2.66793727846875e+07],[1474423200000,2.5434711313506946e+07],[1474430400000,2.765370576546875e+07],[1474437600000,7.845705721963541e+07],[1474444800000,2.513437020975868e+08],[1474452000000,2.989145277083333e+08],[1474459200000,2.6615256602430555e+08],[1474466400000,2.2038028124597222e+08],[1474473600000,1.123531151435243e+08],[1474480800000,7.914800725572917e+07],[1474488000000,6.558017758746528e+07],[1474495200000,3.8564908235086806e+07],[1474502400000,2.628909715638889e+07],[1474509600000,2.4191086572777778e+07],[1474516800000,2.6212404291614585e+07],[1474524000000,6.648140468505208e+07],[1474531200000,1.834105468323611e+08],[1474538400000,2.251525535024479e+08],[1474545600000,2.4811188752935764e+08],[1474552800000,2.446545977767535e+08],[1474560000000,1.3526640933277777e+08],[1474567200000,1.1836997766135417e+08],[1474588800000,5.7191157002916664e+07],[1474596000000,5.6157254540231474e+07],[1474603200000,5.758876178046299e+07],[1474610400000,9.348333510851851e+07],[1474617600000,1.9921511302898145e+08],[1474624800000,2.930208637330092e+08],[1474632000000,2.2442467233935195e+08],[1474639200000,1.6381090105259264e+08],[1474646400000,1.0023245578342584e+08],[1474653600000,7.25430384752314e+07],[1474660800000,6.984052940143527e+07],[1474668000000,6.381169861824083e+07],[1474675200000,5.730376719495361e+07],[1474682400000,5.537569581837972e+07],[1474689600000,5.5208137690185e+07],[1474696800000,6.366940276611111e+07],[1474704000000,7.900823971175943e+07],[1474711200000,8.427558294074056e+07],[1474718400000,7.537693096893528e+07],[1474725600000,7.314782080824083e+07],[1474732800000,6.836407003537028e+07],[1474740000000,6.754679560055555e+07],[1474747200000,6.680288696611111e+07],[1474754400000,5.944277988555556e+07],[1474761600000,5.5587317602592506e+07],[1474768800000,5.509620461453695e+07],[1474776000000,5.573276322912055e+07],[1474783200000,5.7791374380277775e+07],[1474790400000,6.6286366700231664e+07],[1474797600000,7.689842604907389e+07],[1474804800000,8.462190649879612e+07],[1474812000000,8.490437989050944e+07],[1474819200000,8.036356554773167e+07],[1474826400000,8.608862758370334e+07],[1474833600000,8.106148822838e+07],[1474840800000,6.5699749156712785e+07],[1474848000000,5.733324231995388e+07],[1474855200000,5.4926859100833334e+07],[1474862400000,5.658345940773112e+07],[1474869600000,9.611503280754666e+07],[1474876800000,2.734056780401633e+08],[1474884000000,2.8383399355742896e+08],[1474891200000,2.795066154643983e+08],[1474898400000,2.106973147364068e+08],[1474905600000,1.165532907471582e+08],[1474912800000,1.0539458586699057e+08],[1474920000000,9.379475919328722e+07],[1474927200000,7.350203202962945e+07],[1474934400000,6.501678991685221e+07],[1474941600000,6.2879636140647784e+07],[1474948800000,6.303362193912001e+07],[1474956000000,9.883063314435221e+07],[1474963200000,2.278098841113889e+08],[1474970400000,2.949793705693522e+08],[1474977600000,2.939960559433333e+08],[1474984800000,2.3635486119699e+08],[1474992000000,1.3793050467504665e+08],[1474999200000,1.053639324032411e+08],[1475006400000,9.400266199046224e+07],[1475013600000,6.715965532416667e+07],[1475020800000,5.990845796231554e+07],[1475028000000,5.898373475712891e+07],[1475035200000,6.711330344546333e+07],[1475042400000,9.079727126685221e+07],[1475049600000,2.2019413235083333e+08],[1475056800000,3.126085731284722e+08],[1475064000000,3.502474471954167e+08],[1475071200000,2.5267096704270723e+08],[1475078400000,1.2986464377956055e+08],[1475085600000,1.0671958925722222e+08],[1475092800000,1.1222973971463e+08],[1475100000000,1.1105629261939779e+08],[1475107200000,6.638087062671333e+07],[1475114400000,6.198610179120334e+07],[1475121600000,6.0159831549444444e+07],[1475128800000,1.0067996655388889e+08],[1475136000000,1.763239450650369e+08]]}]},{"series":[{"name":"NetworkMeasurements","tags":{"agent_host":"bor.master.surf.net","ifAlias":" PRIMARY"},"columns":["time","Uit"],"values":[[1474365600000,1.8521584746077778e+09],[1474372800000,1.8260989653966668e+09],[1474380000000,1.0144350682938541e+09],[1474387200000,3.065412143020833e+08],[1474394400000,9.419968277322917e+07],[1474401600000,5.468731896850695e+07],[1474408800000,2.4243516665625e+07],[1474416000000,1.5149483592534723e+07],[1474423200000,1.388365370388889e+07],[1474430400000,1.8997639101944443e+07],[1474437600000,3.2865061529072917e+08],[1474444800000,1.4955526645906596e+09],[1474452000000,2.1413915612418056e+09],[1474459200000,1.9331746910637152e+09],[1474466400000,1.1101403001875348e+09],[1474473600000,2.887599703325e+08],[1474480800000,1.2417695199583334e+08],[1474488000000,4.427637609052084e+07],[1474495200000,1.4151713608784722e+07],[1474502400000,1.0341798045173611e+07],[1474509600000,9.171277425208334e+06],[1474516800000,1.5486298956388889e+07],[1474524000000,3.372402339154514e+08],[1474531200000,1.3553921502055554e+09],[1474538400000,1.7533326065187848e+09],[1474545600000,1.4595151119622917e+09],[1474552800000,8.1943111162375e+08],[1474560000000,2.500414466840278e+08],[1474567200000,8.197332906590278e+07],[1474588800000,1.3473164370092591e+07],[1474596000000,1.271312999421296e+07],[1474603200000,1.5396639645509262e+07],[1474610400000,2.998207336686574e+08],[1474617600000,1.2430694272264814e+09],[1474624800000,1.3859093922210183e+09],[1474632000000,1.1273093438498611e+09],[1474639200000,4.8280347135759276e+08],[1474646400000,9.262188949791667e+07],[1474653600000,2.630113551611111e+07],[1474660800000,2.0482562711666666e+07],[1474668000000,1.4488082253796116e+07],[1474675200000,1.0468510178194445e+07],[1474682400000,9.577728106527777e+06],[1474689600000,1.030336896490777e+07],[1474696800000,1.2893791185879448e+07],[1474704000000,4.442245517537055e+07],[1474711200000,3.944353709773112e+07],[1474718400000,4.088343706662055e+07],[1474725600000,2.6645236253333334e+07],[1474732800000,1.5258245053796658e+07],[1474740000000,1.2924978265138889e+07],[1474747200000,1.521844992648112e+07],[1474754400000,1.1194735977407768e+07],[1474761600000,9.57150312546224e+06],[1474768800000,9.387835937685547e+06],[1474776000000,9.76365547087999e+06],[1474783200000,1.0090196783055555e+07],[1474790400000,1.4228911448842231e+07],[1474797600000,1.4543337827083332e+07],[1474804800000,1.9840302565972224e+07],[1474812000000,2.1029391298102215e+07],[1474819200000,1.8997931203425564e+07],[1474826400000,1.8617188281064454e+07],[1474833600000,1.9063847785e+07],[1474840800000,1.307546486861111e+07],[1474848000000,1.023613094638889e+07],[1474855200000,9.871151822593316e+06],[1474862400000,1.5107740477684462e+07],[1474869600000,2.2580501631680554e+08],[1474876800000,1.413326572706964e+09],[1474884000000,1.469885016761046e+09],[1474891200000,1.4569692363639355e+09],[1474898400000,8.391964692091883e+08],[1474905600000,2.4183362160932943e+08],[1474912800000,6.620653122046224e+07],[1474920000000,3.438048399449219e+07],[1474927200000,1.4500599871618923e+07],[1474934400000,1.0917625433148872e+07],[1474941600000,1.0147661802732205e+07],[1474948800000,1.4830864699027779e+07],[1474956000000,3.187117450906944e+08],[1474963200000,1.5073264139201844e+09],[1474970400000,2.0094816807985656e+09],[1474977600000,1.7384274068877301e+09],[1474984800000,8.930623080575477e+08],[1474992000000,2.946582204728233e+08],[1474999200000,1.3575687408384332e+08],[1475006400000,3.626947013490669e+07],[1475013600000,1.5349776581944445e+07],[1475020800000,1.3351321604767796e+07],[1475028000000,1.3056742488982204e+07],[1475035200000,2.4795122865694445e+07],[1475042400000,2.784242906145833e+08],[1475049600000,1.258741392036111e+09],[1475056800000,1.8479237360489366e+09],[1475064000000,1.7905601121912935e+09],[1475071200000,1.0282296889097092e+09],[1475078400000,2.8734417987297744e+08],[1475085600000,7.980691082291667e+07],[1475092800000,4.5881282907174475e+07],[1475100000000,5.4464124548658855e+07],[1475107200000,1.1946254483285591e+07],[1475114400000,1.0186886687825521e+07],[1475121600000,1.5641375568242187e+07],[1475128800000,2.804894436121267e+08],[1475136000000,9.727462347146875e+08]]}]},{"series":[{"name":"NetworkMeasurements","tags":{"agent_host":"bor.master.surf.net","ifAlias":" PRIMARY"},"columns":["time","Piek in"],"values":[[1474365600000,2.6677181913666666e+08],[1474372800000,2.1643670201e+08],[1474380000000,1.2726905261555555e+08],[1474387200000,7.347516457666667e+07],[1474394400000,8.164937516222222e+07],[1474401600000,5.783687883111111e+07],[1474408800000,3.385207206666667e+07],[1474416000000,2.5584775774444446e+07],[1474423200000,2.5214515216666665e+07],[1474430400000,3.274330753888889e+07],[1474437600000,1.5792962395e+08],[1474444800000,3.024682925788889e+08],[1474452000000,2.865199766111111e+08],[1474459200000,2.5524072027555555e+08],[1474466400000,1.6299453887111112e+08],[1474473600000,8.525561654111111e+07],[1474480800000,7.41755965e+07],[1474488000000,5.179098716444445e+07],[1474495200000,3.0920833035555556e+07],[1474502400000,2.438065087888889e+07],[1474509600000,2.4379987415555555e+07],[1474516800000,3.145804074111111e+07],[1474524000000,1.2007776751777777e+08],[1474531200000,2.2876917674666667e+08],[1474538400000,2.1632193432777777e+08],[1474545600000,2.751823585611111e+08],[1474552800000,1.8679650015888888e+08],[1474560000000,1.1534980431777778e+08],[1474567200000,1.1168608547222222e+08],[1474574400000,1.606132925111111e+07],[1474588800000,5.610121931888889e+07],[1474596000000,5.632948037e+07],[1474603200000,6.178370251777778e+07],[1474610400000,1.4244084948555556e+08],[1474617600000,2.6163231541555557e+08],[1474624800000,2.686850349011111e+08],[1474632000000,1.8684950516555557e+08],[1474639200000,1.4299014455555555e+08],[1474646400000,7.529948285555555e+07],[1474653600000,7.169665969555555e+07],[1474660800000,6.793677750222223e+07],[1474668000000,5.974782591888889e+07],[1474675200000,5.581002903222222e+07],[1474682400000,5.519517789e+07],[1474689600000,5.528312366e+07],[1474696800000,7.003946326444444e+07],[1474704000000,8.758333273e+07],[1474711200000,8.020898946111111e+07],[1474718400000,7.281909444444445e+07],[1474725600000,7.275226421777777e+07],[1474732800000,6.6087166656666666e+07],[1474740000000,6.819146046555555e+07],[1474747200000,6.323543294e+07],[1474754400000,5.716546672666667e+07],[1474761600000,5.501726250666667e+07],[1474768800000,5.532426733e+07],[1474776000000,5.6197225432222225e+07],[1474783200000,6.058470035222222e+07],[1474790400000,7.13453666088889e+07],[1474797600000,8.234420730666667e+07],[1474804800000,8.332381526555556e+07],[1474812000000,8.429581479444444e+07],[1474819200000,7.989413818333334e+07],[1474826400000,8.944058196777777e+07],[1474833600000,7.396657336444445e+07],[1474840800000,5.9729279263333336e+07],[1474848000000,5.578683743444444e+07],[1474855200000,5.4317394983333334e+07],[1474862400000,6.113262111444444e+07],[1474869600000,1.4847815112555555e+08],[1474876800000,3.0902299161777776e+08],[1474884000000,3.091234573422222e+08],[1474891200000,2.549867348288889e+08],[1474898400000,1.5546022422666666e+08],[1474905600000,1.0287491847888888e+08],[1474912800000,1.035534131388889e+08],[1474920000000,8.295380604555556e+07],[1474927200000,6.731540751888889e+07],[1474934400000,6.406912535555556e+07],[1474941600000,6.189296588888889e+07],[1474948800000,6.609625554777778e+07],[1474956000000,1.5042932308222222e+08],[1474963200000,2.7999372453444445e+08],[1474970400000,2.871590924622222e+08],[1474977600000,2.8444854133444446e+08],[1474984800000,1.9499547529e+08],[1474992000000,1.1185918542333333e+08],[1474999200000,1.0632084019e+08],[1475006400000,7.535362394777778e+07],[1475013600000,6.2437717906666666e+07],[1475020800000,5.872283400777778e+07],[1475028000000,6.179070201888889e+07],[1475035200000,6.788383359e+07],[1475042400000,1.4067395022333333e+08],[1475049600000,2.861736563111111e+08],[1475056800000,3.3967630841333336e+08],[1475064000000,3.1878812161777776e+08],[1475071200000,1.8296685302222222e+08],[1475078400000,1.0694078322222222e+08],[1475085600000,1.0940284384222223e+08],[1475092800000,1.2301216320444444e+08],[1475100000000,7.939703943666667e+07],[1475107200000,6.543380703888889e+07],[1475114400000,5.8770897475555554e+07],[1475121600000,6.364388406222222e+07],[1475128800000,1.575913774211111e+08],[1475136000000,1.610462159077778e+08]]}]},{"series":[{"name":"NetworkMeasurements","tags":{"agent_host":"bor.master.surf.net","ifAlias":" PRIMARY"},"columns":["time","Piek uit"],"values":[[1474365600000,1.8521584746077778e+09],[1474372800000,1.8260989653966668e+09],[1474380000000,1.0144350682938541e+09],[1474387200000,3.065412143020833e+08],[1474394400000,9.419968277322917e+07],[1474401600000,5.468731896850695e+07],[1474408800000,2.4243516665625e+07],[1474416000000,1.5149483592534723e+07],[1474423200000,1.388365370388889e+07],[1474430400000,1.8997639101944443e+07],[1474437600000,3.2865061529072917e+08],[1474444800000,1.4955526645906596e+09],[1474452000000,2.1413915612418056e+09],[1474459200000,1.9331746910637152e+09],[1474466400000,1.1101403001875348e+09],[1474473600000,2.887599703325e+08],[1474480800000,1.2417695199583334e+08],[1474488000000,4.427637609052084e+07],[1474495200000,1.4151713608784722e+07],[1474502400000,1.0341798045173611e+07],[1474509600000,9.171277425208334e+06],[1474516800000,1.5486298956388889e+07],[1474524000000,3.372402339154514e+08],[1474531200000,1.3553921502055554e+09],[1474538400000,1.7533326065187848e+09],[1474545600000,1.4595151119622917e+09],[1474552800000,8.1943111162375e+08],[1474560000000,2.500414466840278e+08],[1474567200000,8.197332906590278e+07],[1474588800000,1.3473164370092591e+07],[1474596000000,1.271312999421296e+07],[1474603200000,1.5396639645509262e+07],[1474610400000,2.998207336686574e+08],[1474617600000,1.2430694272264814e+09],[1474624800000,1.3859093922210183e+09],[1474632000000,1.1273093438498611e+09],[1474639200000,4.8280347135759276e+08],[1474646400000,9.262188949791667e+07],[1474653600000,2.630113551611111e+07],[1474660800000,2.0482562711666666e+07],[1474668000000,1.4488082253796116e+07],[1474675200000,1.0468510178194445e+07],[1474682400000,9.577728106527777e+06],[1474689600000,1.030336896490777e+07],[1474696800000,1.2893791185879448e+07],[1474704000000,4.442245517537055e+07],[1474711200000,3.944353709773112e+07],[1474718400000,4.088343706662055e+07],[1474725600000,2.6645236253333334e+07],[1474732800000,1.5258245053796658e+07],[1474740000000,1.2924978265138889e+07],[1474747200000,1.521844992648112e+07],[1474754400000,1.1194735977407768e+07],[1474761600000,9.57150312546224e+06],[1474768800000,9.387835937685547e+06],[1474776000000,9.76365547087999e+06],[1474783200000,1.0090196783055555e+07],[1474790400000,1.4228911448842231e+07],[1474797600000,1.4543337827083332e+07],[1474804800000,1.9840302565972224e+07],[1474812000000,2.1029391298102215e+07],[1474819200000,1.8997931203425564e+07],[1474826400000,1.8617188281064454e+07],[1474833600000,1.9063847785e+07],[1474840800000,1.307546486861111e+07],[1474848000000,1.023613094638889e+07],[1474855200000,9.871151822593316e+06],[1474862400000,1.5107740477684462e+07],[1474869600000,2.2580501631680554e+08],[1474876800000,1.413326572706964e+09],[1474884000000,1.469885016761046e+09],[1474891200000,1.4569692363639355e+09],[1474898400000,8.391964692091883e+08],[1474905600000,2.4183362160932943e+08],[1474912800000,6.620653122046224e+07],[1474920000000,3.438048399449219e+07],[1474927200000,1.4500599871618923e+07],[1474934400000,1.0917625433148872e+07],[1474941600000,1.0147661802732205e+07],[1474948800000,1.4830864699027779e+07],[1474956000000,3.187117450906944e+08],[1474963200000,1.5073264139201844e+09],[1474970400000,2.0094816807985656e+09],[1474977600000,1.7384274068877301e+09],[1474984800000,8.930623080575477e+08],[1474992000000,2.946582204728233e+08],[1474999200000,1.3575687408384332e+08],[1475006400000,3.626947013490669e+07],[1475013600000,1.5349776581944445e+07],[1475020800000,1.3351321604767796e+07],[1475028000000,1.3056742488982204e+07],[1475035200000,2.4795122865694445e+07],[1475042400000,2.784242906145833e+08],[1475049600000,1.258741392036111e+09],[1475056800000,1.8479237360489366e+09],[1475064000000,1.7905601121912935e+09],[1475071200000,1.0282296889097092e+09],[1475078400000,2.8734417987297744e+08],[1475085600000,7.980691082291667e+07],[1475092800000,4.5881282907174475e+07],[1475100000000,5.4464124548658855e+07],[1475107200000,1.1946254483285591e+07],[1475114400000,1.0186886687825521e+07],[1475121600000,1.5641375568242187e+07],[1475128800000,2.804894436121267e+08],[1475136000000,9.727462347146875e+08]]}]}]}

**request**
db:Database
q:SELECT non_negative_derivative(mean("ifHCInOctets"), 1s) *8 FROM "NetworkMeasurements" WHERE "agent_host" =~ /^agent_host$/ AND "ifAlias" =~ /^( PRIMARY)$/ AND time > 1443518052s and time < now() GROUP BY time(2h), "ifAlias", "agent_host" fill(null);SELECT non_negative_derivative(mean("ifHCOutOctets"), 1s) *8 AS "Uit" FROM "NetworkMeasurements" WHERE "agent_host" =~ /bor.master.surf.net|truus.master.surf.net/ AND "ifAlias" =~ /^( PRIMARY)$/ AND time > 1443518052s and time < now() GROUP BY time(2h), "ifAlias", "agent_host" fill(null);SELECT non_negative_derivative(max("ifHCInOctets"), 1s) *8 AS "Piek in" FROM "NetworkMeasurements" WHERE "agent_host" =~ /bor.master.surf.net|truus.master.surf.net/ AND "ifAlias" =~ /^( PRIMARY)$/ AND time > 1443518052s and time < now() GROUP BY time(2h), "ifAlias", "agent_host" fill(null);SELECT non_negative_derivative(mean("ifHCOutOctets"), 1s) *8 AS "Piek uit" FROM "NetworkMeasurements" WHERE "agent_host" =~ /bor.master.surf.net|truus.master.surf.net/ AND "ifAlias" =~ /^( PRIMARY)$/ AND time > 1443518052s and time < now() GROUP BY time(2h), "ifAlias", "agent_host" fill(null)
epoch:ms

**Comment by torkelo** [comment]
Maybe open the issue in the InfluxDB repo? Grafana just shows the data you InfluxDB query returns
