### ISSUE TITLE
how can I start the grafana-server of OS X

### ISSUE THREAD

**Issue by zhaojigang** [grafana/grafana#6149]
hi, all, 
I download the tar.gz package from http://grafana.org/download/ and unzip the package, then I find that i can't start the server by ./bin/grafana-server.

how can I start the grafana-server of OS X?

grafana：3.1.1
platform：OS X 10.10.5

**Comment by torkelo** [comment]
you must have missed the Linux in the tar package link:
![image](https://cloud.githubusercontent.com/assets/10999/18948640/2ca9e0de-8638-11e6-8ba3-4977a313806a.png)

To install on mac we recommend homebrew:
http://docs.grafana.org/installation/mac/

**Comment by zhaojigang** [comment]
Thanks a lot!!!@torkelo
it works!!!
