### ISSUE TITLE
Prometheus: Streaming client gives different errors than the buffered client

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#61507]
The Prometheus streaming client was made the default client in Grafana v9.3 to replace the old buffered client. Since then there have been reports that the streaming client returns different errors than the buffered client.

For example, when there is an issue with the prometheus instance itself, the error is returned as `downstreamError`. This happened in a [customer issue](https://github.com/grafana/support-escalations/issues/4629) where a prometheus instance had a timeout and returned the `plugin.downstreamError`.

Another example from a customer is shown below
Streaming client
<img width="270" alt="Screen Shot 2023-01-13 at 2 36 31 PM" src="https://user-images.githubusercontent.com/25674746/212404344-e5d979f9-312c-4a45-9ca7-219ec20eac55.png">

Buffered client
<img width="741" alt="Screen Shot 2023-01-13 at 2 37 26 PM" src="https://user-images.githubusercontent.com/25674746/212404490-8fab31f3-e2b8-4bed-bc30-8468f1316c94.png">

Currently, the feature toggle for using the buffered client can be set so that users get errors from Prometheus. 
[feature_toggles]
prometheusBufferedClient = true

Since we intend to remove the buffered client, we will investigate the difference in error handling between the streaming and buffered client.

**Environment**:
- Grafana version: v9.3
- Data source type & version: Prometheus

**Comment by itsmylife** [comment]
More information and discussion around this https://raintank-corp.slack.com/archives/C036J5B39/p1673957976977549
