### ISSUE TITLE
Notifications are difficult to create in Unified Alerting due not lack of prepopulated dropdown

### ISSUE THREAD

**Issue by freeflyerme** [grafana/grafana#61513]
**Steps to reproduce**:
Running Grafana 9.3.1 with Unified Alerting enabled.
Have a notification channel / contact available.
Create any panel with a valid datasource.
Add an alert into the panel
Navigate to the Notification section
Fill out the notification section so it can send to a contact.

**Actual Result**:
When creating an alert in the new Unified Alerting UI, the (4) Notifications Section asks for a set of Custom Labels.
In Legacy Alerting, it's easy to add pre-configured channels, e.g. slack: <Slack Channel>, OpsGenie: <OpsGenie Channel>.

However, in the new UI, the Labels fields rely entirely on freeform text input.  To correctly create an alert, one needs to type on "__contacts__" = "<CSV separated list of exact channels".

With no repopulated fields, it is very difficult to create a new alert without having an existing example to copy.  
It is especially difficult for new users to type in the right notification channels, as there is no obvious way to know what to type into these fields.  Whereas previously in Legacy Alerting, a list of notification channels can be selected from an UI.

**Expected Result**
The Labels fields (left) is re-populated with basic defaults, such as "__contacts__".  Once selected, the right side (= <Choose Value>) is populated with options for the users to select.

Note, I had to manaully type "__contacts__" into the field, as the dropdown has no values.
![Notification](https://user-images.githubusercontent.com/1756064/212425134-56d1064d-b4fe-4294-929b-f0824e796dc8.png)

**Environment**:
- Grafana version: 9.3.1-ubuntu running on Kubernetes
- Data source type & version: Postgresql
- User OS & Browser: Firefox (108.0.1), Chrome
- Others:

**Comment by mytototo** [comment]
Is it something planned soon? Manually managing labels when creating alerts is really difficult when working across multiple teams and services. Is there a work around? Or a way to set default labels?

**Comment by KaplanSarah** [comment]
Simplified routing addresses this.  
https://grafana.com/blog/2024/04/02/simplified-routing-in-grafana-alerting-easy-secure-and-powerful/
