### ISSUE TITLE
AzureAD OAuth /w CF Access

### ISSUE THREAD

**Issue by MWGMorningwood** [grafana/grafana#61519]
**What happened**: AzureAD OAuth behind a Cloudflare Tunnel reverse proxy (software not .crt) is returning HTTP-only traffic to the app registration login. This causes a mismatch between AzureADs expected redirect (HTTPS) and the one provided by Grafana (HTTP). Correcting this with the 'protocol' option results in the container failing to start entirely due to no CRT being loaded. Re-writing the root_url section itself to force HTTPS results in the SSO login timing out during MS Auth, but no error. This tells me the URL is now malformed or not responding on the Grafana end. Forcing Azure to contain HTTP:// in the URI results in AADSTS500117: The reply uri specified in the request isn't using a secure scheme.

**What you expected to happen**: For the protocol flag to be able to respect software proxies, wondering how literally every other platform makes this happen—maybe direct Cloudflare Access integration. I am not installing NGINX and intend to stay on my path with Cloudflared/Access.

**How to reproduce it (as minimally and precisely as possible)**: Configure AzureAD OAuth with no SSL cert but a software reverse proxy instead. This will occur in any configuration where direct internet access to the machine is not available, and no CRT file is added.

**Anything else we need to know?**: This might be the one thing that results in me dropping Grafana. I value Cloudflare's capabilities over alternatives more than Grafana in the same context.

**Environment**:
- Grafana version: v9.3.2 (21c1d14e91)
- Data source type & version: N/A
- OS Grafana is installed on: Official Docker image
- User OS & Browser: N/A
- Grafana plugins: None
- Others: 

_Config Snippets_

```
[server]
# Protocol (http, https, h2, socket)
protocol = http
# The ip address to bind to, empty will bind to all interfaces
http_addr =
# The http port to use
http_port = 3000
# The public facing domain name used to access grafana from a browser
domain = monitor.mw-gc.com
# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false
# The full public facing url
root_url = https://monitor.mw-gc.com:3001
# Set to true if you want to enable http strict transport security (HSTS) response header.

[security]
# HSTS tells browsers that the site should only be accessed using HTTPS.
strict_transport_security = true
# Sets how long a browser should cache HSTS. Only applied if strict_transport_security is enabled.
strict_transport_security_max_age_seconds = 86400
# Set to true if to enable HSTS preloading option. Only applied if strict_transport_security is enabled.
strict_transport_security_preload = false
# Set to true if to enable the HSTS includeSubDomains option. Only applied if strict_transport_security is enabled.
strict_transport_security_subdomains = true

[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = true
client_id = 
client_secret =
scopes = openid email profile
auth_url = https://login.microsoftonline.com//oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com//oauth2/v2.0/token
allowed_domains = mw-gc.com
allowed_groups = b2bbbb27-6abe-44fc-9506-c5e8123225ec
role_attribute_strict = false
allow_assign_grafana_admin = false
```

**Comment by MWGMorningwood** [comment]
Config snippet edited.

**Comment by MWGMorningwood** [comment]
Note: the Portainer.io project I'm using hand-in-hand with Grafana at the moment allows for the same end goal to be accomplished without issue. It has to be something with how Grafana handles the auto-generated URIs or how they're responded to when forced into this config.

I **did not** need to edit these, but a manual configuration like this may be required to allow for overriding certain fields in special configurations (like mine) 
![image](https://user-images.githubusercontent.com/2997336/212676779-68f34a42-c8ee-4b94-983f-cef156b152ba.png)

**Comment by MWGMorningwood** [comment]
If this could be set as HTTPS without a cert loaded, and the container could be started w/o error, I believe it would be a non-issue (so long as no other back-end Grafana components would break if this override were done).

```
#################################### Server ##############################
[server]
# Protocol (http, https, h2, socket)
protocol = https
```

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @MWGMorningwood 

i'm forwarding the issue to the Auth. squad. for review.

**Comment by mgyongyosi** [comment]
Hey @MWGMorningwood,

I usually use `cloudflared tunnel` for testing purposes, but I haven't seen any issue like this previously.

Just to clarify what you would like to achieve:
1. You have a host and Grafana running on port 3000
2. `cloudflared tunnel ...` running on the same host and connects to a CF tunnel
3. For the CF tunnel, In the ingress config you should have something like this (or you configured something like this on the Web UI of CF):
```
ingress:
  - hostname: monitor.mw-gc.com
    service: http://localhost:3000
````
4. So `https://monitor.mw-gc.com` requests should be proxied to the host's `http://localhost:3000` endpoint and HTTPS/SSL should be handled by Cloudflare, not Grafana so the protocol should be the default http.

I can see that the `root_url` contains a port as well which is not supported by CF by default (https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/#network-ports-compatible-with-cloudflares-proxy). Could you please try to remove that and check whether it works? `root_url = https://monitor.mw-gc.com`

On Azure side the redirect uri should be `https://monitor.mw-gc.com/login/azuread`.

I hope this will help you!
If you still have problems could you please share more info about your infra setup?

**Comment by MWGMorningwood** [comment]
> 1. You have a host and Grafana running on port 3000

Correct

> 2. `cloudflared tunnel ...` running on the same host and connects to a CF tunnel

Same docker host, separate container. One container is serving as a reverse proxy for multiple others without issue, Grafana is the only container having trouble with communication.

> 3. For the CF tunnel, In the ingress config you should have something like this (or you configured something like this on the Web UI of CF):

Rule is (as it is separate container, same host/net):
```
ingress:
  - hostname: monitor.mw-gc.com
    service: http://172.17.0.7:3000
```

> 4. So `https://monitor.mw-gc.com` requests should be proxied to the host's `http://localhost:3000` endpoint and HTTPS/SSL should be handled by Cloudflare, not Grafana so the protocol should be the default http.

Correct

> Could you please try to remove that and check whether it works? `root_url = https://monitor.mw-gc.com`

I'll give this a shot and report back!
Thanks a bunch @mgyongyosi

**Comment by MWGMorningwood** [comment]
@mgyongyosi, you're the best!

There was a strange mix of issues here, beginning with the port you mentioned.
Since this is a reverse proxy, we are open to more than just the same port ranges as regular proxying through CF. That part was OK.
The `root_url` **did** require me to remove the port entirely. I may have misinterpreted how the variables build the URL, but it appeared to be expecting a port in the mix regardless. Once removed, I began getting invalid group memberships. That ended up being an invalid ID (didn't resolve initially) **AND** requiring `force_use_graph_api` instead of the ID lookup. Not sure if this is something you guys would need to look into or just another issue that `force_use_graph_api` is working around.

At any rate, now I am getting instant authentication past the login page, including with my CF tunnel and application SSO wall active. This allows for DNS level authentication, **AND** application-level authentication, should either level fail outside Microsoft's security.

Hopefully this thread serves as help for anyone else going down the same route 😄
