### ISSUE TITLE
X axis dateformat isn't localized or follows ISO 8601

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#6151]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using?

3.1.1

- What did you do?

X axis time format isn't localized nor follows ISO 8601.

- What was the expected result?

The graph plot the date as localized dd/mm or according to ISO 8601 --mm-dd

- What happened instead?

Atm it's plots date as mm/dd.

**IMPORTANT** If it relates to metric data viz:

As far as I can tell itäs hardcoded in **function time_format(ticks, min, max)** in the file **public/app/plugins/panel/graph/graph.ts**

Personally I prefere going the ISO 8601 BUT as a easier way to do "solve" this, one could make those definable in the configuration.

**Comment by torkelo** [comment]
yea, would also like ISO 8601, closing this as there is already an issue for it, https://github.com/grafana/grafana/issues/1459
