### ISSUE TITLE
Remove feature flag `alertingNoNormalState` before Grafana 10 release

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#61518]
**What happened**:
The PR https://github.com/grafana/grafana/pull/61201 updated alerting to not maintain the Normal state: do not save transitions Normal -> Normal to the database, and do not show Normal state in UI.

That feature is controlled by the feature flag `alertingNoNormalState` as it could be considered as breaking change (presentation). 

We should remove this flag in Grafana 10 and make this logic the default.

**Comment by armandgrillet** [comment]
Closed as the 10.0 train has left the station.
