### ISSUE TITLE
Validation missing for field "name" when creating a datasource via POST

### ISSUE THREAD

**Issue by adi** [grafana/grafana#61520]
**What happened**:
If you issue a curl command to create (via POST) a datasource containing a space in its "name" field, you are allowed to do it. Other operations on the obtained datasource partially fail later.

**What you expected to happen**:
Receive the same Validation error as for the PUT method.

**How to reproduce it (as minimally and precisely as possible)**:
Run this on a fresh Grafana installation: 

```bash
curl 'http://localhost:3000/api/datasources' \
  -u admin:admin \
  -H 'content-type: application/json' \
  --data-raw '{"name":"Loki 1","type":"loki","access":"proxy","isDefault":false}'
```
You can see that you receive a newly created datasource instead of a validation error.

**Anything else we need to know?**:
You can't reproduce this in the browser because, the app automatically creates a proper name there.

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: Loki 2.7.1
- OS Grafana is installed on: Linux
- User OS & Browser: not relevant
- Grafana plugins: not relevant
- Others: none

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @adi 

can you tell us a bit more about what the name breaks? I managed to save the name with a space in the UI. Here is the json the api returns when I [GET](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#update-an-existing-data-source) `/api/datasources`

```
{
    "id": 7,
    "uid": "tmPmRzT4z",
    "orgId": 1,
    "name": "Loki 1000",
    "type": "loki",
    "typeName": "Loki",
    "typeLogoUrl": "public/app/plugins/datasource/loki/img/loki_icon.svg",
    "access": "proxy",
    "url": "http://localhost:3100",
    "user": "",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {},
    "readOnly": false
  },
```
And if i [update the datasource](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#update-an-existing-data-source) via PUT

```
{
  "datasource": {
    "id": 7,
    "uid": "tmPmRzT4z",
    "orgId": 1,
    "name": "PUT few more spaces",
    "type": "loki",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "http://localhost:3100",
    "user": "",
    "database": "",
    "basicAuth": false,
    "basicAuthUser": "",
    "withCredentials": false,
    "isDefault": false,
    "jsonData": {},
    "secureJsonFields": {},
    "version": 1,
    "readOnly": false
  },
  "id": 7,
  "message": "Datasource updated",
  "name": "PUT few more spaces"
}
```

**Comment by adi** [comment]
The datasources created with spaces in their name were throwing a Bad URL error when visited from the UI. But I can't reproduce this anymore. I think I may have misinterpreted a different issue as being a validation error. Thank you for looking into this and sorry for the wasted time.
