### ISSUE TITLE
Bug: Alerting notifications not working (runtime error)

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6152]
Hi,
There is a problem with alerting notifications in the recent builds (using 29.09.16). I've defined the following alerting test rule which is properly raporting it's state in the GUI however in the logfile a "_Runtime Error_" message appears:
![grafana_alerting](https://cloud.githubusercontent.com/assets/12551929/18953804/67988188-8650-11e6-911a-ec7cf926a743.jpg)
Log message:
```
t=2016-09-29T14:15:10+0200 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=2
t=2016-09-29T14:15:10+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/alerting-test?&panelId=2"
t=2016-09-29T14:15:11+0200 lvl=eror msg="Panic in resultDispatcher" logger=alerting.engine error="runtime error: invalid memory address or nil pointer dereference" stack="[engine.go:104 asm_amd64.s:472 panic.go:443 panic.go:62 sigpanic_unix.go:24 notifier.go:86 notifier.go:49 result_handler.go:88 engine.go:109]"
```
-

**Comment by bergquist** [comment]
Seems like we dont handle unconfigured imageuploader. https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L422 

Submitting a patch now.

**Comment by bergquist** [comment]
Thank you for reporting :)
