### ISSUE TITLE
Public key failure

### ISSUE THREAD

**Issue by tomjensendk** [grafana/grafana#61524]
**What happened**: After following the blog about update regarding CircleCI security updates we are seeing GPG error for verifying apt.grafana.com

Err:4 https://apt.grafana.com stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
Reading package lists... Done
W: GPG error: https://apt.grafana.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
E: The repository 'https://apt.grafana.com stable InRelease' is not signed.

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: 
- OS Grafana is installed on: 20.04.1-Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Starfoxfs** [comment]
Same here on Raspberry Pi Debian Bullseye 11 64bit Version
Grafana version: 9.3.2

`wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -`

Works not fine, because it get a error apt-key is deprecated

` wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
`
It works now but the Install Documentation have to be replace with a newer Method to add the Public Key.

**Comment by lnicola** [comment]
See https://github.com/grafana/grafana/issues/61491#issuecomment-1383106725.

**Comment by tonypowa** [comment]
hi @tomjensendk 👋 

Thank you for creating this issue

i have forwarded the issue regarding [circleCI security update](https://grafana.com/blog/2023/01/12/grafana-labs-update-regarding-circleci-security-updates/) to the release team to review if the Debian/Ubuntu security key instructions need any changes or additional steps. They will get back to you

**Comment by tonypowa** [comment]
**Raspberry Pi question**


> Same here on Raspberry Pi Debian Bullseye 11 64bit Version Grafana version: 9.3.2
> 
> `wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -`
> 
> Works not fine, because it get a error apt-key is deprecated
> 
> `wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add - Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)). OK` It works now but the Install Documentation have to be replace with a newer Method to add the Public Key.
> 
> I have tried to add the gpg file to `/etc/apt/trusted.gpg.d/`
> 
> Something like this but it´s not working.
> 
> `wget -q -O - https://packages.grafana.com/gpg.key | sudo tee /etc/apt/trusted.gpg.d/grafana.gpg`
> 
> Package Manager says wrong File Format for gpg File

hi @Starfoxfs 

Please see @lnicola [comment. ](https://github.com/grafana/grafana/issues/61524#issuecomment-1383626041) 🚀

**Comment by inajob** [comment]
I tried to install grafana 7.5.11 on CentOS7, but a bellow error occured.
Is this same issue? How to solve it?

```
$ LANG=C sudo yum  install grafana-7.5.11-1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.iij.ad.jp
 * extras: ftp.iij.ad.jp
 * updates: ftp.iij.ad.jp
grafana/signature                                                                                                        |  629 B  00:00:00
grafana/signature                                                                                                        | 3.0 kB  00:00:00 !!!
Resolving Dependencies
--> Running transaction check
---> Package grafana.x86_64 0:7.5.11-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================
 Package                           Arch                             Version                             Repository                         Size
================================================================================================================================================
Installing:
 grafana                           x86_64                           7.5.11-1                            grafana                            50 M

Transaction Summary
================================================================================================================================================
Install  1 Package

Total size: 50 M
Installed size: 169 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/grafana/packages/grafana-7.5.11-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 24098cb6: NOKEY
Retrieving key from https://rpm.grafana.com/gpg.key


The GPG keys listed for the "grafana" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: grafana-7.5.11-1.x86_64
 GPG Keys are configured as: https://rpm.grafana.com/gpg.key
```

**Comment by skibbipl** [comment]
I think this is a security measure in recent Debians. IMO the correct way to add the key is following:
1. Download grafana repo key and dearmor it. `cat grafana.key | gpg --dearmor > grafana.gpg`
2. Copy `grafana.gpg` into `/etc/apt/keyrings`. In releases older than Debian 12 and Ubuntu 22.04, `/etc/apt/keyrings` does not exist by default. It SHOULD be created with permissions 0755 if it is needed and does not already exist.
3. Update `/etc/apt/sources.list.d/grafana/list` and paste following:
```
deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
```
More info: https://wiki.debian.org/DebianRepository/UseThirdParty

**Comment by tonypowa** [comment]
@tomjensendk 

As @skibbipl  has pointed out, you might have missed to dearmor it

The same error `NO_PUBKEY 9E439B102CF3C0C6` was reported by another user in this [community forum post](https://community.grafana.com/t/problem-with-debian-repository-key/79788/3?u=antonio.merello)

**Comment by tomjensendk** [comment]
@tonypowa Still getting the same error after applying the dearmor suggested fix

**Comment by tonypowa** [comment]
> @tonypowa Still getting the same error after applying the dearmor suggested fix

In that case let's wait to hear the next steps from the responsible engineering team for build-packaging  (this issue is already assigned to their project)

**Comment by tonypowa** [comment]
in the meantime it would be helpful for the team if you could provide the following info, *if applicable*:

```
apt --version
gpg --version
get ubuntu: version
cat /etc/lsb-release
```

**Comment by tomjensendk** [comment]
@tonypowa 

Sure no problem, the info as requested:

apt --version: **apt 2.0.9 (amd64)**
gpg --version: **gpg (GnuPG) 2.2.19 / libgcrypt 1.8.5**
get ubuntu: version **20.04.1-Ubuntu**
cat /etc/lsb-release: **DISTRIB_ID=Ubuntu / DISTRIB_RELEASE=20.04 / DISTRIB_CODENAME=focal / DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"**

**Comment by kminehart** [comment]
I'm going to test some stuff out and I'll let you know what I try here. There's a good chance we will just update our instructions to dearmor the key.

Out of curiosity @tomjensendk what's the result of `cat /etc/apt/sources.list.d/grafana.list`?

**Comment by tomjensendk** [comment]
@kminehart 

This is what the content of the particular file is

deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main

**Comment by kminehart** [comment]
Try this:

```
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /usr/share/keyrings/grafana.key
```

Then

```
apt update
```

I think you might have just gotten caught in the middle of some conflicting instructions.

**Comment by tomjensendk** [comment]
still no luck

Err:5 https://apt.grafana.com stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
Reading package lists... Done
W: GPG error: https://apt.grafana.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
E: The repository 'https://apt.grafana.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by kminehart** [comment]
I'm not sure where it's coming from but this, `deb [signed-by=/usr/share/keyrings/grafana.key]`, points to the key, `9E439B102CF3C0C6`. Somewhere, there must be another grafana source somewhere that doesn't have that.

What results does this give?
```
sudo grep -rni "grafana/" /etc/apt/sources.list.d
```

**Comment by tomjensendk** [comment]
Only thing I find is the below:

/etc/apt/sources.list.d/grafana.list.save:1:deb https://packages.grafana.com/enterprise/deb stable main
/etc/apt/sources.list.d/grafana.list:1:deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main

**Comment by kminehart** [comment]
and `cat /usr/share/keyrings/grafana.key`? :thinking:

**Comment by tomjensendk** [comment]
gives me just a binary output

**Comment by tomjensendk** [comment]
just did a rerun of

 wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key

and now it shows the -----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGO4aiUBDAC82zo3vUyQH3yTCabQ7ZpospBg/xXBbJWbQNksIbEP/+I12CjB
zac1QcMFd27MJlyXpsTqqSo1ZHOisNy0Tmyl/WlqMyoMeChg+LmIHLNbvAK0jPOX
1Pt2OykXJWN9Ru+ZZ4uQNgdKO5nXS6C

**Comment by kminehart** [comment]
Yeah the instructions on the blog are outdated and we need to update them.

I would start by cleaning all of this up.

```
# Remove your grafana apt sources and keys.
rm /usr/share/keyrings/grafana.key /etc/apt/sources.list.d/grafana.list.save /etc/apt/sources.list.d/grafana.list

apt update

mkdir -p /etc/apt/keyrings/
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
```

**Comment by tomjensendk** [comment]
did all the above (with sudo) and end result is still the same

**Comment by kminehart** [comment]
well let me try it in a docker container with your ubuntu version and see if I get the same results. If that works for me, honestly it's going to be hard to figure out next steps.

**Comment by kminehart** [comment]
Did you get that same error on the first `apt update`?

**Comment by tomjensendk** [comment]
when I remove the files from source list etc. apt update throws no errors and seems to be working as expected

**Comment by kminehart** [comment]
okay thanks, that is helpful.

I ran this to get the same environment as you provided earlier, and it is working for me:
```
docker run --rm -it ubuntu:20.04
root@8e1b21533960:/# apt update && apt install -yq wget gpg
root@8e1b21533960:/# apt --version
apt 2.0.9 (amd64)
root@8e1b21533960:/# gpg --version
gpg (GnuPG) 2.2.19
root@8e1b21533960:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```

Copied and pasted the commands I gave you earlier:
```
root@8e1b21533960:/# mkdir -p /etc/apt/keyrings/
root@8e1b21533960:/# wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
root@8e1b21533960:/# echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
root@8e1b21533960:/#
root@8e1b21533960:/# apt update
Get:1 https://apt.grafana.com stable InRelease [5984 B]
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:3 https://apt.grafana.com stable/main amd64 Packages [111 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 117 kB in 1s (181 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
```

And I can install Grafana:

```
root@8e1b21533960:/# apt install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core libexpat1 libfontconfig1 libfreetype6 libpng16-16 ucf
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core grafana libexpat1 libfontconfig1 libfreetype6 libpng16-16 ucf
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 91.0 MB of archives.
After this operation, 303 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

My best guess so far is that there's some environment variable or something set somewhere that is messing with your set up. Is there anything else you can provide?

**Comment by tomjensendk** [comment]
The result from the last command is

gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa3072 2023-01-06 [SC] [expires: 2025-01-05]
      0E22EB88E39E12277A7760AE9E439B102CF3C0C6
uid           Grafana Labs <engineering@grafana.com>
sub   rsa3072 2023-01-06 [E] [expires: 2025-01-05]

About the environment variable or something I can't recall something special has been done but I'll try to test various other stuff to see if I can get it working

**Comment by kminehart** [comment]
i see. Everything looks good from what I can tell... you have the correct key (ends in `9E439B102CF3C0C6`) in the correct place, you have the repository list that points to the correct key. apt even sees that the repo metadata is signed with that key, but it doesn't seem to understand to look for the key specified by "signed-by" (`signed-by=/etc/apt/keyrings/grafana.gpg`).

**Comment by kminehart** [comment]
Perhaps this is something to try?

from `man 5 sources.list`.
```
It is specified as a list of absolute paths to keyring files (have to be
   accessible and readable for the _apt system user, so ensure everyone has
   read-permissions on the file
```

**Comment by tomjensendk** [comment]
Got it working now, the culprit seemed to be a permission problem on the /etc/apt/keyrings directory even that everybody had read on the directory a regular user was not able to read the grafana.gpg key file. 

A rename of the problematic directory and then creating it again and moving the grafana.gpg file back made it work

Thank you for the help, I'm not sure I had found that one myself.

**Comment by inajob** [comment]
@tonypowa 
I tried again yesterday.
Everything worked fine even if same instruction. (didn't change gpg key)

Anyway, my problem solved, thank you.

**Comment by MarrekNozka** [comment]
I had a same problem and solution is: `chmod 755 /etc/apt/keyrings/grafana.gpg`.

**Comment by knotmine** [comment]
I had an issue with redirecting `gpg --dearmor` to the grafana.gpg file. the command below did it.

`sudo wget -q -O - https://apt.grafana.com/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/grafana.gpg`
