### ISSUE TITLE
Docker container ERROR for grafana/grafana:master --- on RHEL

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#6153]
Error response from daemon: Cannot start container b077c80bacdca57cea82ddf757f6d6b898e6d71c77f2d6f1ddb72962be3d3623: [8] System error: exec: "/run.sh": stat /run.sh: no such file or directory

I already have grafana/grafana:latest image on my RHEL machine... also i pulled the image with master tag... but when i try to launch the container it gets me an error as below

$ docker run -i -p 3000:3000 grafana/grafana:master

Error response from daemon: Cannot start container b077c80bacdca57cea82ddf757f6d6b898e6d71c77f2d6f1ddb72962be3d3623: [8] System error: exec: "/run.sh": stat /run.sh: no such file or directory

* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
```
❯ docker run -i -p 3001:3000 grafana/grafana:master
t=2016-09-29T19:05:29+0000 lvl=info msg="Starting Grafana" logger=main version=4.0.0-pre1 commit=6d7061d compiled=2016-09-28T17:10:31+0000
t=2016-09-29T19:05:29+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2016-09-29T19:05:29+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2016-09-29T19:05:29+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2016-09-29T19:05:29+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2016-09-29T19:05:29+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2016-09-29T19:05:29+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2016-09-29T19:05:29+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2016-09-29T19:05:29+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
```

maybe fixed in latest container? Or something with your docker setup?

**Comment by softwareklinic** [comment]
I will try it out again.
