### ISSUE TITLE
Merge transform not working if one of the query return empty response - Azure Monitor Resource Graph

### ISSUE THREAD

**Issue by websolut** [grafana/grafana#61535]
I am trying to merge multiple Azure Resource Graph instant queries into into single table which is prerequisite to get "Merge" to work (Organize fields only works with a single frame). Intent is to list all alerts in single table, multiple queries needed to filter the alerts properly using template variables, and then sort and filter some fields using Organize fields.

Current behavior:
When all queries return one or more entry then merge works (latest Azure grafana managed)

But if one of the query return empty response then merge is not done at all and error sign as well as no data are shown.

Expected behavior:
Queries should be merged and empty response should be ignored. Otherwise merge will not work with dynamic data like alerts where some queries might be are empty.

Query type - 

`alertsmanagementresources
| join kind=leftouter (ResourceContainers | where type=='microsoft.resources/subscriptions' | project SubName=name, subscriptionId) on subscriptionId
| where type == "microsoft.alertsmanagement/alerts"
| where tolower(subscriptionId) == tolower("$sub") and properties.essentials.monitorCondition in~ ($mc) and properties.essentials.severity in~ ($sev)
and todatetime(properties.essentials.lastModifiedDateTime) >= $__timeFrom and todatetime(properties.essentials.lastModifiedDateTime) <= $__timeTo
| parse id with * "alerts/" alertId
| project name, properties.essentials.severity, tostring(properties.essentials.monitorCondition), 
tostring(properties.essentials.alertState), todatetime(properties.essentials.lastModifiedDateTime), tostring(properties.essentials.monitorService), alertId`

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @websolut 

Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

Is that empty response NULL or ZERO ? In the past if  values were null, the backend would set them to zero. They should now be null instead. Reference [here](https://github.com/grafana/grafana/pull/28126). However,  "Null point mode: null as zero" can be used if one wants to it reflected in the graph, and in the json response.

Please also include info about your environment

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by websolut** [comment]
Thanks. I do not have any option to change grafana logging level or access grafana logs.

But it seems that I am not able to reproduce the issue now since Azure updated Grafana to 9.3.2.2.

Environment:
Grafana version: 9.3.2.2
Data source type & version: Azure monitor
OS Grafana is installed on: Azure managed Grafana
User OS & Browser: Windows 11 Firefox
Grafana plugins: -
