### ISSUE TITLE
Unable to build docker image from source code

### ISSUE THREAD

**Issue by anushanagireddy0430** [grafana/grafana#61530]
Unable to build grafana docker image from source with tag v9.3.1
We are having a usecase to build grafana image with some additional packages developed by ourselves.
To acheive that we have tried to build grafana image as it is without any change, but facing issues while building.
Steps followed:
1. git clone https://github.com/grafana/grafana.git
2. git checkout tags/v9.3.1
3. sudo docker build --no-cache -t x.x.x.x/xxx/:grafana_src_1.0 .
Error:

(re)installing /go/bin/wire-v0.5.0
go: downloading github.com/google/subcommands v1.0.1
go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b
generate code from .cue files
go generate ./pkg/plugins/plugindef
go: downloading github.com/grafana/codejen v0.0.2
go: downloading github.com/grafana/cuetsy v0.1.1
go: downloading github.com/labstack/echo/v4 v4.9.0
go: downloading golang.org/x/mod v0.7.0
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading github.com/labstack/gommon v0.3.1
go: downloading github.com/valyala/fasttemplate v1.2.1
/grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
make: *** [Makefile:69: gen-cue] Error 1

Fixes tried:
running yarn install --immutable, yarn start, make deps and make build before docker build.
But unable to build successfully

Please help to solve the issue or let me know the proper steps to build docker image.

**Comment by azilly-de** [comment]
Please see #58921  and additionally [the comment](https://github.com/grafana/grafana/issues/58921#issuecomment-1332581945)

What seem strange is that you opened the same(also duplicate) issue about 2 weeks ago (#61021).  @mellieA  already mentioned #58921 there... 

How about #59666 ? Did you try that?

**Comment by azilly-de** [comment]
@tonypowa  this issue could be closed as well (duplicate like #63434)

**Comment by tonypowa** [comment]
thanks for letting us know @azilly-de 

👍
