### ISSUE TITLE
Grafana docker master

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#6154]
Please include this information:
- What Grafana version are you using? - grafana/grafana:master
- What datasource are you using? - graphite
- What OS are you running grafana on? - RHEL
- What did you do? - configured ALERT to send email 
- What was the expected result? - an email for alert
- What happened instead? - - didnt receive any email even after the test was successful and it was showing ALERTINg ... in alerts panel

**Comment by bergquist** [comment]
What does your logs say?
Have you configured SMTP? https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L272

**Comment by torkelo** [comment]
@softwareklinic have you configured you smpt server settings in your grafana.ini config file (or via ENV variables)
https://github.com/grafana/grafana/blob/master/conf/sample.ini#L257

@bergquist looks like we are missing SMTP config docs, I must have forgotten to add that when I did user invite feature back last year, will create issue for that

**Comment by softwareklinic** [comment]
maybe i didnt realize - but since im using the docker image (grafana/grafana:master) --- does that not contain the smtp server --- do i need to setup a separate SMTP server outside of my host machine>?? how will grafana use SMTP server?
