### ISSUE TITLE
Panel Header: Rewrite menu Provider to a hook

### ISSUE THREAD

**Issue by polibb** [grafana/grafana#61557]

**Comment by mellieA** [comment]
@polibb I added some labels since this showed up in triage, feel free to change/edit them :D

**Comment by polibb** [comment]
Sorry, this seems irrelevant anymore. It used to be connected to https://github.com/grafana/grafana/issues/56163, but somehow I don't remember why it was even open. Closing in favor of the plans in https://github.com/grafana/grafana/issues/63093.
