### ISSUE TITLE
Search: Filtering by starred in a folder with no stars shows all folders + dashboards from outside the folder

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#61551]
**What happened**:

With `panelTitleSearch=true` feature flag

When in a folder with no starred dashboards, checking the 'Starred' filter will incorrect show items from outside the folder.

I figure this is because the frontend makes a search for `{ query: '*', limit: 50, uids: [] }` - UIDs would normally contain the starred dashboards, which there are none of.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Have the `panelTitleSearch=true` feature flag enabled
2. Create a new folder
3. Create a new dashboard and save to that folder. Do not star the dashboard
4. Go to that folder's view and check 'Starred'
5. Observe that results will be shows for things outside that folder

https://user-images.githubusercontent.com/46142/212673283-521098e6-e309-4760-a209-2fd49e901950.mp4

**Comment by joshhunt** [comment]
Thoughts @leeoniya on how to fix this? 

I figured we should bail search and not do a search if stars API returns no results, but I guess we need to make and return an empty data frame? I'm not sure the right way to do that here (would be easier if it returned just... an array of search results?)

**Comment by adigov** [comment]
in addition to above mentioned issue, if you go to dashboards and folders landing page `/dashboards` then search for a folder it's loading appropriate dashboards. Then if we reload that folder url `/dashboards/f/<some-id>` it shows list of all dashboards. I noticed that on reload folderIds is reset to ZERO could be the issue `api/search?limit=1000&sort=name_sort&folderIds=0`. This could be happening for starred as well

**Comment by ryantxu** [comment]
@joshhunt -- yes, i think you are right.  No need to even query if stars is empty.

**Comment by leeoniya** [comment]
some odd network request behavior in general, imo: 

https://user-images.githubusercontent.com/43234/213248996-fad533f2-d97e-4b8b-b31c-8db99b161503.mp4
