### ISSUE TITLE
admin_user and admin_pass config not work

### ISSUE THREAD

**Issue by zhaojigang** [grafana/grafana#6156]
hi, I config 
admin_user = zhaojigang
admin_password = zhaojigang

but  then when I login the grafana, some error occurs in log:
lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"

I am a little confused.

**Comment by torkelo** [comment]
I know these are a bit confusing. 
But helps to read the docs:
http://docs.grafana.org/installation/configuration/#admin_password

> Set once on first-run. Defaults to admin.

**Comment by zhaojigang** [comment]
oh，I missed the "Set once on first-run". Thanks a lot!!! @torkelo
