### ISSUE TITLE
Explore: Unify panel containers

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#61563]
part of https://docs.google.com/presentation/d/1jajTZYleOW9Wdv39L-DR-uyfjupw8aO9iVbj8E2M97c/edit#slide=id.g7a34fe5133_3_198 showcases the proposed changes.

It has been brought up a few different times how panels in explore all behave and/or look differently to each other; a few example:

Node Graph:
![Image](https://user-images.githubusercontent.com/1170767/211531098-5bf7e8d3-b5bd-447e-b0db-2c3730c0bc3f.png)

Timeseries:
![Image](https://user-images.githubusercontent.com/1170767/211531118-bb5bc1df-c104-4840-b177-2e15befc7bf5.png)

Table:
![Image](https://user-images.githubusercontent.com/1170767/211531133-120b3e51-5699-40bf-bea3-a9bcaba94bb7.png)

Trace View:
![Image](https://user-images.githubusercontent.com/1170767/211531158-733fa070-4a08-4270-a492-0f040ae049c0.png)

Logs Volume + Logs View:
![Image](https://user-images.githubusercontent.com/1170767/211531251-9dd83a11-1cba-457b-90e5-3c932e69a9f4.png)

May be related to (soft blocks) [52107](https://github.com/grafana/grafana/issues/52107) if there's need to modify/create a new component

Issues:
- Titles are not consistently aligned; some panels have them centered, some others left aligned
  - Additionally, some users reported to consider panel titles useless, as it provides no actual information to users and take up valuable vertical space (debatable)
- Some panels render quick configuration button on the top-right corner (graph, promRawView). Logs panel renders them at the top, but beneath the title. Trace View renders a sticky search bar in the top-right that scrolls with the content. While we cannot control what is rendered within panels, we may want to provide some unification and APIs to render quick controls.
  - additionally, the current implementation of such quick controls is quite hacky, and makes the controls not properly aligned to the right.
- We are using the `Collapse` component for most of the panels, which renders a clickable header in the panel, however those panels (except for the logs volume) are not collapsible.
- Some panels may benefit from not having an inner padding in the container, ie: TraceView & Node Graph.
- In general, we lack guidelines for how panels should look and behave within Explore. This has caused each panel author to roll out their own custom solution to address their specific needs. 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/69175
- [ ] https://github.com/grafana/grafana/issues/69178
- [ ] https://github.com/grafana/grafana/issues/69179
- [ ] https://github.com/grafana/grafana/issues/69177
- [ ] https://github.com/grafana/grafana/issues/69176
- [ ] https://github.com/grafana/grafana/issues/70145
```

**Comment by Elfo404** [comment]
The work done here will most likely affect #52107 and #55462. if we decide to move forward with some sort of unification for panel containers in Explore, we may want to consider these issues blocked by this one.

**Comment by harisrozajac** [comment]
All containers have been unified. 🚀
