### ISSUE TITLE
Recording rule for Loki uses different Loki datasource than the configured one.

### ISSUE THREAD

**Issue by Condla** [grafana/grafana#61561]
**What happened**: Upon creating recording rules in my environment, the chosen Loki data source is not respected after saving. As you can see, I choose grafanacloud-condla2-logs as my data source for the recording rule. When I'm saving the rule the seemingly first/default Loki data source is configured instead and hence the recording rule doesn't work, as it does not contain the data requested by the query.

**What you expected to happen**:
Loki data source that I configure in the recording rule is the one that is saved and used for the recording rule.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Loki recording rule and choose a Loki data source that's not the first one in the list.

**Anything else we need to know?**:
Here's a video that shows the issue. Mind the data source I configure is not the one that is being shown in the alerts menu.

https://user-images.githubusercontent.com/4442327/212697217-34dc0e7e-8245-4d97-9481-a911226d5f5c.mov

**Environment**:
- Grafana version: [v9.3.2-67a213dc85 (67a213dc85)]
- Data source type & version: Loki
- OS Grafana is installed on: -
- User OS & Browser: MacOS and Chrome
- Grafana plugins: -
- Others: -

**Comment by konrad147** [comment]
I'm not able to reproduce the issue. 
On the recording, I noticed there are two namespaces and groups of the same name: `test > test rules`
Are you sure the second one does not come from the correct data source?

**Comment by Condla** [comment]
Yes, I'm sure it's not. The duplicates are a different issue I discovered at the same time: https://github.com/grafana/grafana/issues/61559

**Comment by Condla** [comment]
@konrad147  oh now I get it..... I just checked. One of the rules comes out with the correct source, the other with the incorrect source, that I didn't choose. Does that mean, that the recording rule is applied twice or is it just a permissions kind of thingy, where we want to make the rule visible to everything that has access to the label from an LBAC point of view? Or neither of those?

**Comment by konrad147** [comment]
I haven't been working with LBAC, but according to the docs it should have no impact on the Ruler API
> Label policies are not enforced by the alertmanager and ruler. This means that the requests that they serve contain everything for a particular tenant without applying label-based access control.

> One of the rules comes out with the correct source, the other with the incorrect source, that I didn't choose.
Do both of these sources point to the same Loki instance?

From Alerting point of view, a data source is just a proxy for Loki/Prometheus API. If you have multiple data sources pointing to the same URL, then any change made to one data source will be reflected in any other data source (because it is the same instance of Loki/Prometheus)
