### ISSUE TITLE
Grafana and ambari plugin. Internet explorer Dashboard init failed

### ISSUE THREAD

**Issue by jmlero** [grafana/grafana#6157]
I'm submitting a Bug report

Please include this information:
- What Grafana version are you using?
Grafana version: 2.6.0, commit: v2.6.0, build date: 2015-12-14 15:18:01 
- What datasource are you using?
Ambari-plugin for grafana
- What OS are you running grafana on?
Linux Centos 7
- What did you do?
Installed grafana from Apache ambari 2.4
- What was the expected result?
Metrics about a hadoop cluster using predefined dashboards
- What happened instead?
Using Chrome and firefox is working fine, but using internet explorer some dashboards are not working. The error is:
"Dashboard init failed
Template variables could not be initialized: Object doesn't support property or method 'includes'"

Altough it seems like this behavior is due to Internet explorer: https://codedump.io/share/sj4jWtz17mq3/1/ie11---object-doesn39t-support-property-or-method-39includes39---javascript-windowlocationhash

**Comment by torkelo** [comment]
maybe it's an issue with the ambari plugin? Try Grafana 3.1

**Comment by JSmith2412** [comment]
> Try Grafana 3.1

does anyone know if this suggestion works?

**Comment by daniellee** [comment]
includes is a new JavaScript function that is not supported by older browsers. I'm guessing the ambari plugin uses it somewhere. Should be easy enough to fix (could use the Lodash includes function instead). Try opening an issue for this on the ambari plugin repo: https://github.com/prajwalrao/ambari-metrics-grafana
