### ISSUE TITLE
API methods return json responses with Content-Type: text/plain

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#6160]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-pre1
- What datasource are you using? N/A
- What OS are you running grafana on? Ubuntu
- What did you do? `curl https://admin:admin@localhost:3000/api/orgs/1 -X PUT -i -d name=Main`
- What was the expected result? `Content-Type: application/json`
- What happened instead? `Content-Type: text/plain`

The `ApiSuccess` function uses `Respond` rather than `Json`, which means that the incorrect `Content-Type` header is sent in API success messages.  `text/plain` is sent but the actual content is a JSON object like `{"message":"Organization updated"}`.

In `pkg/api/common.go` line ~82 should be changed from `return Respond(200, resp)` to `return Json(200, resp)`.

**Comment by CJosePhD** [comment]
I want to incorporate a clustering algorithm into our Graphite/Grafana environment. The code is written and its format is a tuple (cluster#:dataValue). 

How should the data be sent to the pie, histogram or heat map chart?

Regards,
Carl

Sent from my iPhone
