### ISSUE TITLE
Unable to plot metricbeat data

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#6161]
Grafana is unable to view metricbeat data. It does show the labels, but does not show the actual data.

![image](https://cloud.githubusercontent.com/assets/1611494/18997566/f1b900a4-872c-11e6-8599-07f8c8d1aa50.png)

Here's an example configuration:

![image](https://cloud.githubusercontent.com/assets/1611494/18997608/2011119e-872d-11e6-8037-98f4b4687008.png)

**Comment by oazabir** [comment]
Attaching metricbeat index template.

[metricbeat.zip](https://github.com/grafana/grafana/files/503319/metricbeat.zip)

Kibana can show the graphs nicely

![image](https://cloud.githubusercontent.com/assets/1611494/18997763/c8ca058e-872d-11e6-8457-036e3bd55220.png)

**Comment by torkelo** [comment]
is the group by interval of 1m enough? Maybe try to increase it. If it is too small every real point might be surrounded by null values. The lines will not render if there is value, null, value, null. 

You can either increase the group by time, change the date histogram Min Doc Count from 0 to 1, or change the option in the display tab called "null value" , set this to "null as zero" . or "connected"   (connected will make the rendering engine ignore null values, but if you choose this option you will not be able to see missing data regions as easily as the lines will just connect over the missing data region)

**Comment by oazabir** [comment]
Thanks. Just tried all of these, getting a flat line

![image](https://cloud.githubusercontent.com/assets/1611494/18998173/5f4fe2c0-872f-11e6-8dff-63fe8de1f5a1.png)

**Comment by torkelo** [comment]
Strange, ES is returning zeros, check in Chrome dev tools the network call to ES and the ES response, anything you see that is off? No one else has reported any similar issue

**Comment by torkelo** [comment]
Also good to include grafana and ES version

**Comment by oazabir** [comment]
Found the bug. The request is:

```
{"search_type":"count","ignore_unavailable":true,"index":["metricbeat-2016.09.30.18","metricbeat-2016.09.30.19"]}
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1475258793189","lte":"1475262393189","format":"epoch_millis"}}}]}}}},"aggs":{"3":{"terms":{"field":"host","size":10,"order":{"1":"desc"}},"aggs":{"1":{"max":{"field":"system.cpu.user.pct "}},"2":{"date_histogram":{"interval":"2s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1475258793189","max":"1475262393189"},"format":"epoch_millis"},"aggs":{"1":{"max":{"field":"system.cpu.user.pct "}}}}}}}}
```

You can see a space after the field names. 

It would be good to add trim() on all the input boxes.
