### ISSUE TITLE
Nightly Builds do not build packages anymore

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#6162]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Nightly Builds do only build "Linux binary tar" since 28. No more debs and such.
Could you have a look please.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
