### ISSUE TITLE
Explore: Remove log volume settings local storage key migration

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#61626]
[Supplementary queries PR](https://github.com/grafana/grafana/pull/61298) introduced a key migration that is a breaking change. For Grafana 10.0 we can remove the migration code (search for #61626) in `loadSupplementaryQueries()` method.

**Comment by meanmina** [comment]
@ifrost this needs more context

**Comment by ifrost** [comment]
> @ifrost this needs more context

This [PR](https://github.com/grafana/grafana/pull/61298) changed the name of the key used in browser local storage to determine if log volume is "enabled" (enabled => the panel is opened and log volume loads automatically with the query / disabled => the panel is collapsed and log volume is loaded only when the user opens the panel; the setting is updated each time the panel is collapsed/opened). 

The PR also added the code to migrate the setting, which means if logs volume was enabled using the old key, it'd save the setting under a new key. The migration worked in 9.4 and 9.5 meaning users who opened Explore at least once have their settings migrated (migration happens when pane settings are loaded).

With @ivanahuckova we agreed that the migration logic is not needed to be kept longer than until Grafana 10.0.0. If this is still acceptable, we can remove [this block of code](https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/supplementaryQueries.ts#L41). 

The impact: in worst case scenario if a user had log volume disabled before 9.4 and upgraded straight to 10.0, the log volume will be enabled (as it's the default setting).

**Comment by ivanahuckova** [comment]
> With @ivanahuckova we agreed that the migration logic is not needed to be kept longer than until Grafana 10.0.0. If this is still acceptable, we can remove [this block of code](https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/supplementaryQueries.ts#L41).

Not sure if this is question for me, but I would remove it. There was already a branch off for 10, but we can do it in 10.1 🙂

**Comment by ivanahuckova** [comment]
I have created PR in https://github.com/grafana/grafana/pull/68360 and added 10.1 milestone, as it is not important if the migration is removed in 10.0 or 10.1. So backport is not really needed in this case. 🙂
