### ISSUE TITLE
KairosDB plugin adding unwanted avg aggregator

### ISSUE THREAD

**Issue by dvenza** [grafana/grafana#6163]
* **I'm submitting a ...**
- [X] Bug report

Grafana 3.1.1-1470047149 (ubuntu trusty)

I'm plotting data from KairosDB related to host status (cpu, memory, etc.)

I'm trying to generate sums, for example sum all CPU usage for all hosts of a particular subset, so that we can have a nice line that says how much load is there for real. I do not want an average.

This is the query I build:
![capture](https://cloud.githubusercontent.com/assets/5452054/18999535/6e01acc2-873e-11e6-83cb-cc1c45a5f182.PNG)

The plot shows something that is not a sum, more like an average. If I look at the request in the browser I see this:
```json
{"metrics":
  [
    {
     "name":"cpu",
     "aggregators": [
       {"name":"avg", "align_sampling":true, "sampling":{"value":"15","unit":"seconds"} },
       {"name":"sum","sampling":{"value":"10","unit":"seconds"}, "align_sampling":true }
  ],
  "tags":{"host":["bf1","bf2","bf3","bf4"],"cpu":["cpu0","cpu-total"]}}],
  "cache_time":0,
  "start_relative":{"value":"3","unit":"hours"},"end_relative":{"value":"1","unit":"minutes"}
}
```
There is my sum aggregator, but there is also an avg aggregator with an interval of 15 seconds that I have never defined.
The downsampling is also set to (NONE)

Any hint?

**Comment by torkelo** [comment]
Please open an issue in the KairosDB plugin repo
