### ISSUE TITLE
Duplicate data source results in HTTP 500

### ISSUE THREAD

**Issue by ameade** [grafana/grafana#6164]
* **I'm submitting a ...**
- [X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
   Grafana v3.1.1 (commit: a4d2708) 

- What datasource are you using?
   influxdb

- What OS are you running grafana on?
   RHEL 7server

- What did you do?
   Two POSTs to /api/datasources with same request body.
   body: {"name":"influxtemp","type":"influxdb","url":"http://localhost:8086","access":"proxy","jsonData":{},"database":"test_repository","user":"grafana","password":"temp"}

- What was the expected result?
   HTTP 200 for first request then HTTP 409 or some other sane error indicating a duplicate

- What happened instead?
   HTTP 200 then HTTP 500 error with body of {"message":"Failed to add datasource"}

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
