### ISSUE TITLE
Login failed  - Error while trying to authenticate user v9.2.5 (042e4d216b) . LDAP authentication.

### ISSUE THREAD

**Issue by player-axel007** [grafana/grafana#61656]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by player-axel007** [comment]
I have error: level=error msg="Error while trying to authenticate user" error="user already exists"

Helped me in my case


# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
member_of = "memberOf"
email =  "email"
username = "sAMAccountName"

**Comment by tonypowa** [comment]
hi @player-axel007  
thank you for creating this issue

please try to fill as much info about your environment. It will help us to troubleshoot the issue

Environment:

    Grafana version:
    Data source type & version:
    OS Grafana is installed on:
    User OS & Browser:
    Grafana plugins:
    Others:
    
Thank you!

**Comment by player-axel007** [comment]
Grafana version: v9.2.5 (042e4d216b)
Data source type & version: using ldap for authentication on Ubuntu 18.04
OS Grafana is installed on: Ubuntu 22.04 from https://hub.docker.com  - grafana/grafana:9.2.5
User OS & Browser: Windows 11  & Chrome browser
Grafana plugins: n/a 
Others: n/a

**Comment by tonypowa** [comment]
thanks for the info @player-axel007 

this might be a org_role related issue
here is a [similar issue](https://github.com/grafana/grafana/issues/51273) to yours
could you review it,  and if the solution does not work for you, share your /etc/grafana/ldap.toml file here?

**Comment by player-axel007** [comment]
my solution is 
username = "sAMAccountName"
in section
[servers.attributes]
It is worked.
full section is 
[servers.attributes]
member_of = "memberOf"
email = "email"
username = "sAMAccountName"
