### ISSUE TITLE
Docs: Add a brief of the new design of Panel Header in the 'What's new'

### ISSUE THREAD

**Issue by polibb** [grafana/grafana#61661]
We need to include a documentation of the new panel in a dashboard in What's new.
Add to this PR: https://github.com/grafana/grafana/pull/59614

Text:
https://docs.google.com/document/d/1L1W0ouT87GdwfTUhiycl_QSj-uPx97OBx_htImbBd4w/edit?usp=sharing

Example videos (use one): 
https://user-images.githubusercontent.com/13227501/216069556-080d3eb6-5a93-4195-9117-6e3b52e595d4.mov
https://user-images.githubusercontent.com/13227501/216069557-d5478116-309f-4edd-8912-05fff88a195d.mov
https://user-images.githubusercontent.com/13227501/216069558-68520d37-228a-405a-8a52-24290904d91d.mov

**Comment by natellium** [comment]
Done https://github.com/grafana/grafana/pull/59614
