### ISSUE TITLE
ElasticSearch Datasources: X-Pack Toggle Button is Broken

### ISSUE THREAD

**Issue by michael-prasil** [grafana/grafana#61665]
**What happened**:
I created a new datasource in order to access an elastic search instance with the X-Pack option enabled and saved it. That worked and i returned to the datasource overview view. Then i wanted to edit my newly created datasource and pressed edit. I noticed that the button for the X-Pack option was suddenly disabled. However, the rest api clearly shows it is on. I think this must be a display issue with the toggle button.

```
{
  "id": 9,
  "uid": "UGuMpiTVk",
  "orgId": 1,
  "name": "TEST",
  "type": "elasticsearch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://elasticsearch.my-namespace:9200/",
  "user": "",
  "database": "",
  "basicAuth": true,
  "basicAuthUser": "user",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "esVersion": "8.0.0",
    "includeFrozen": false,
    "logLevelField": "",
    "logMessageField": "",
    "maxConcurrentShardRequests": 5,
    "timeField": "@timestamp",
    "xpack": true
  },
  "secureJsonFields": {
    "basicAuthPassword": true
  },
  "version": 1,
  "readOnly": false
}
```

![image](https://user-images.githubusercontent.com/95366341/213150344-7a4d098b-e985-48d4-b4c6-71d59acdb7b3.png)

**What you expected to happen**:
The X-Pack button should stay toggled. :-)

![image](https://user-images.githubusercontent.com/95366341/213150649-e54b8185-abf7-418f-be33-91824ac04b26.png)

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: 8+

**Comment by michael-prasil** [comment]
**Hint:**
I don't know if some other buttons or fileds are affected as well. Maybe worth to check them.

**Comment by mellieA** [comment]
I wonder if this could be related. to the changes made in https://github.com/grafana/grafana/pull/52932

**Comment by svennergr** [comment]
Thanks for the issue @michael-prasil. I could reproduce it.

We are using a property to show the settings in the UI which has been deprecated in the past:

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/elasticsearch/configuration/ElasticDetails.tsx#L128 should be
```ts
value={value.jsonData.xpack || false}
```
