### ISSUE TITLE
Grafana alerting rules

### ISSUE THREAD

**Issue by day4me** [grafana/grafana#61671]
Hello. After the upgrade to the new version of Grafana, I started seeing some strange errors:
```
logger=context userId=0 orgId=2 uname= t=2023-01-18T11:05:10.898340569Z level=info msg="Request Completed" method=GET path=/api/prometheus/yiD6mUhVk/api/v1/rules status=404 remote_addr=************* time_ms=3 duration=3.832991ms size=72 referer=https://localhost:3000/alerting/list handler=/api/prometheus/:DatasourceUID/api/v1/rules

logger=context userId=0 orgId=2 uname= t=2023-01-18T11:05:10.897954976Z level=error msg="data source not found" error="data source not found" remote_addr=*********
```
Datasource with UID yiD6mUhVk does not exist and there are no alerts/rules in the second org
<img width="1499" alt="Screenshot 2023-01-18 at 14 10 30" src="https://user-images.githubusercontent.com/21221420/213168274-3c1f39a6-ffe6-4f36-afb1-1aaf993541b9.png">

In the previous version, there were no errors like that.

Previous version: 9.0.2
Current version: 9.3.1

I'm trying to understand what is causing those errors.

Would appreciate any help.

**Comment by tonypowa** [comment]
hi @day4me  and thank you for creating this issue

are you missing any datasource after the upgrade?
also, please, where are you running Grafana? (OS where Grafana is installed on)

i will try to reproduce the error from my end

**Comment by day4me** [comment]
Hi [tonypowa](https://github.com/tonypowa). Nothing changed after the upgrade, all the datasources/dashboards are the same.

I'm running Grafana 9.3.1 Alpine docker image in AWS ECS.

**Comment by santihernandezc** [comment]
Hi @day4me, a few questions:
- Does that datasource id exist in other orgs?
- Did you have alert rules that were lost after the upgrade?
- Are you running Grafana in High Availability mode? Or is it just a single Grafana instance?

**Comment by day4me** [comment]
Hi @santihernandezc
 - I do not think it is, we have a lot of orgs, so I will double check
 - There were no alert rules
 - I'm using a single Grafana instance
 
 Here are my settings for the alerting, maybe it will help: https://imgur.com/a/sMIlWLh

**Comment by santihernandezc** [comment]
The endpoint `/api/prometheus/{DatasourceID}/api/v1/rules` is queried every time you go to the "Alerts" page. If the data source exists in the DB, Grafana will try to get all rules even if you don't have any.

The error in those logs is just a 404 after the FE tries to find rules for a data source that doesn't exist. Somehow Grafana is getting that data source ID and making that query, maybe it's a leftover from some point in time before the migration took place.

Do you have any steps to reproduce this error? I was not able to do so.

**Comment by day4me** [comment]
The error disappeared a few days ago, even tho nothing changed. Hard to understand what was happening. But it's resolved now. Thanks for your help.
Still would appreciate the answer about the possibility of disabling the alert querying.

**Comment by alexmobo** [comment]
As the issue disappeared we are closing this.

> Still would appreciate the answer about the possibility of disabling the alert querying.
Not sure what you are toling about this. Did you check the docs https://grafana.com/docs/grafana/latest/alerting/?
