### ISSUE TITLE
Aggregated graph strange behavior

### ISSUE THREAD

**Issue by anthony-sticky** [grafana/grafana#6169]
Hi,

I'm submitting a:
- [x] Bug report

- What Grafana version are you using?
Grafana v3.1.0

- What datasource are you using?
InfluxDB v1.0.0

- What OS are you running grafana on?
Debian Jessie.

- What did you do?
I try to graph and aggregated Nginx request per second (collectd default plugin) graph on some servers.

- What was the expected result?
Correct values for "Max" "Avg" sum and a correct scale for my graphs.

- What happened instead?
If i cumulate certain hosts together every metrics seems well calculated and the scale is OK, but sometimes one host will ruin the whole aggregated graph.

- Hosts 6 to 9 everything is ok:
![ads6-9-aggregated](https://cloud.githubusercontent.com/assets/5138633/19020206/51a8406c-88a2-11e6-8725-5e41727201e0.png)

- Hosts 6 to 10, the aggregated graph explodes:
![ads6-10-aggregated](https://cloud.githubusercontent.com/assets/5138633/19020210/7d09c1ea-88a2-11e6-9de3-56b8d78bcde4.png)

- Host 10 alone looks like all others taken independently:
![ads10-only](https://cloud.githubusercontent.com/assets/5138633/19020213/996af93a-88a2-11e6-9ab2-49b026903d16.png)

(Every capture is taken on the same timeframe:  "Last 24 hours").

- Here's the query construction:
![query_construction](https://cloud.githubusercontent.com/assets/5138633/19020258/e9ccf2ec-88a3-11e6-8432-a7153156bdfd.png)

**Comment by torkelo** [comment]
Probably an InfluxDB issue right? Grafana just shows what your influxdb query returns. Please include the influxdb response (raw), then it might be possible to really check if this is a Grafana issue or InfluxDB issue. 

You can find the influxdb raw response by opening chrome dev tools, check network tab and find the inflxudb metrics request and look at the response. Can you find the peak there?

**Comment by anthony-sticky** [comment]
Here is the raw response for

Server #10 alone:
[query_10alone.txt](https://github.com/grafana/grafana/files/505104/query_10alone.txt)

Server #11 alone:
[query_10plus11.txt](https://github.com/grafana/grafana/files/505102/query_10plus11.txt)

Servers #10 plus #11
[query_11alone.txt](https://github.com/grafana/grafana/files/505103/query_11alone.txt)

**Comment by torkelo** [comment]
As you can see it's InfluxDB that is returning that peek

1475379900000,9.88005455e+06],

Not sure why, think you cannot use non negative derivative  like that with two series

**Comment by anthony-sticky** [comment]
I can (even with more) but it depends the servers (don't know why).
Ex: Server8 + 9 + 10 : Sum, avg, max is correct, then i add Server11 and the issue is happening.
And if i take Server11 independently, i can see no point with this king of peak.

**Comment by torkelo** [comment]
you must have missed this line  in your query_10_plus11.txt  file 
`1475379900000,9.88005455e+06],`
