### ISSUE TITLE
Y Axis Hertz Format

### ISSUE THREAD

**Issue by biancalana** [grafana/grafana#617]
Nowadays we have bits, bytes, seconds, milliseconds, etc. But I'm collecting data from VMware processor usage that unit is hertz.

**Comment by chriswiggins** [comment]
Just stumbled into this myself. How can this be implemented?

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/blob/882a988143711e551f42177fc11489dcf082db98/public/app/components/kbn.js#L386
Hertz already supported in master.

**Comment by mtanda** [comment]
@torkelo this can be closed. (sorry frequent ping)
