### ISSUE TITLE
installation on Ubuntu 14.04 from apt packages does not respect /etc/grafana/grafana.ini

### ISSUE THREAD

**Issue by andris** [grafana/grafana#6171]
I installed grafana from the apt packages following these instructions http://docs.grafana.org/installation/debian/ 

I need to change the http_port setting on my installation because that port is already in use.

When I change the setting in /etc/grafana/grafana.ini and restart, grafana still starts on default port 3000.

When I change the setting in /usr/share/grafana/conf/defaults.ini and restart, the new port setting is reflected.

I've inspected the /etc/init.d scripts, but don't see anything wrong there at first glance.

* **I'm submitting a ...**
- [ x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

 Grafana v3.1.1 (commit: a4d2708) 

- What datasource are you using?

Elasticsearch  - but not relevant to this question

- What OS are you running grafana on?

Ubuntu 14.04

- What did you do?

Installed from debian instructions here http://docs.grafana.org/installation/debian/ 

Edited http_port in /etc/grafana/grafana.ini to
;http_port = 3030

Restarted grafana with 
service grafana stop
service grafana start

- What was the expected result?

Expected to find grafana running on port 3030

- What happened instead?

Grafana continued running pon port 3000

I could only fix this by editing /usr/share/grafana/conf/defaults.ini directly

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
all setting in `/etc/grafana/grafana.ini` are commented out (to leave defaults in place)

remember to uncomment the option (remove the `;`)

**Comment by andris** [comment]
Ah thank you!  Sorry, I got tripped up by both comment styles (# and ;) being used in the same file.

This cleared up my issue - much appreciated and thanks for the fast answer!
