### ISSUE TITLE
Plugins: Make sure datasource uid are being used in datasource requests instead of id

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#61727]
**What happened**:
Grafana might throw "unable to load datasource meta data" errors on some Prometheus queries being run from a dashboard.

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:
1. Provisioning file with datasources that are repeated in deleteDatasources and datasources.
2. Load the dashboard using provisioned datasource
3. Restart Grafana
4. Refresh the data in dashboard from 2)

**Anything else we need to know?**:
Ref https://github.com/grafana/support-escalations/issues/4662

Code references that might need changes:
- https://github.com/grafana/grafana/blob/0d42edddbfd62de223e7099e5d4c50a2770aba3e/pkg/api/frontendsettings.go#L252
- https://github.com/grafana/grafana/blob/fd70f6034f076635540b2f275b8659780c8e0928/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L272-L325
- https://github.com/grafana/grafana/blob/0c4aa6d0d8e363a7a1425dbaee943c745867e11c/public/app/features/dashboard/services/DashboardLoaderSrv.ts#L135-L147
- https://github.com/grafana/grafana/blob/6dcc94ecb25b8d2836dc6982237efc99eff7442c/public/app/plugins/datasource/prometheus/datasource.tsx#L259-L288
- https://github.com/grafana/grafana/blob/6dcc94ecb25b8d2836dc6982237efc99eff7442c/public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx#L112
-

**Comment by marefr** [comment]
@andresmgot Seems like datasource routes by id have already been deprecated in the backend for OpenAPI and documentation so don't think there's anything left to do in the backend for this issue.
- https://github.com/grafana/grafana/blob/151e57df707052119772b1c6e6180ba8629733ed/pkg/api/dataproxy.go#L5-L21
- https://github.com/grafana/grafana/blob/151e57df707052119772b1c6e6180ba8629733ed/pkg/api/datasources.go#L627-L642
- https://github.com/grafana/grafana/blob/151e57df707052119772b1c6e6180ba8629733ed/pkg/api/datasources.go#L765-L779
- https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#data-source-proxy-calls-by-id
- https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#fetch-data-source-resources-by-id
- https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health-by-id

**Comment by andresmgot** [comment]
FTR @marefr, I am unable to reproduce the original issue. I provisioned a Prometheus data source via a provisioning file and created a dashboard for it. After restarting the server I don't see any error. I even added an artificial `datasourceId` to the panel but still didn't get an error.

In any case, I can update the references you found and use the data source UID instead.

**Comment by marefr** [comment]
@andresmgot the error only happens occasionally when using datasource provisioning and adding the same datasource to `deleteDatasources` and `datasources. For more information, see https://github.com/grafana/support-escalations/issues/4662. Think you need to provision, then load a dashboard, then re-provisiong while still keeping the browser open without refresh of the whole page, and then refresh a panel. 

> In any case, I can update the references you found and use the data source UID instead.

:+1:

**Comment by andresmgot** [comment]
> while still keeping the browser open without refresh of the whole page

got it, that was the trick :+1:

**Comment by andresmgot** [comment]
Completed
