### ISSUE TITLE
feature request: tying subltly different dashboard changes to corresponding software versions

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6172]
At raintank, we run many instances of [metrictank](https://github.com/raintank/metrictank), often slightly different releases or different builds from master (and in the future possibly different builds from different branches too).

As the metrictank project evolves, we often add, remove or rename metrics, or change a part of the name space.  We maintain the dashboard in correspondance to these changes, but it gets cumbersome because we have several very similar dashboards in our grafana and it's hard to know which dashboard should be used to look at which instance's data.  Worse, since the dashboard has a template variable dropdown for instance, you may select an instance that runs a different version and the dashboard breaks.  And then you have to go find the right dashboard.

I'm not sure how to solve this problem properly, but perhaps we can come up with something.
maybe the metrictank server could log its version number to a timeseries, and that timeseries could be used to switch to a different dashboard version?

**Comment by torkelo** [comment]
I am not sure how to solve it. Sounds like a very special edge case that I am not sure I understand. But feels like something that is better solved outside Grafana (or through some grafana automation / use of it's api). 

Maybe the generic dashboards that we have that let you select instance are bad if they allow you to select an instance for which the dashboard is not compatible.

**Comment by nopzor1200** [comment]
Glad you brought this up @Dieterbe we really need to make this less of a mess.

This problem seems related like it'd be solved with metrics 2.0 style metrics, no? You could just tag the metric with the version of mT? And each dashboard could just pull metrics from the appropriate version?

for now why not encode the gen/version of mT into the metric name? Then each version of your mT Dashboard can filter only looking at specific metrictanks that are appropriate for that dashboard.

**Comment by Dieterbe** [comment]
hmm that's a good idea. a version in the metric path sounds like an interesting approach. i might just persue that. isn't there a new thing in grafana that lets us specify "constants" hardcoded in the dashboard, and that constant is replaced in queries? that would be a good fit here I think.

t's probably true that grafana should not try to solve this problem, so unless torkel wants to add something, this can be closed. I think we will also try to make our versions more consistent.  we'll never be able to always run identical versions at all times.. but i like the version encoding.

**Comment by hugohaggmark** [comment]
I'm closing this issue because we're trying to limit open GitHub issues in order to better track planned work and features.
