### ISSUE TITLE
Empty string as an all value in templating for drilling down prometheus metrics in Grafana 3

### ISSUE THREAD

**Issue by daniellowtw** [grafana/grafana#6173]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? **3.1.0**
- What datasource are you using? **Prometheus 1.0.1**
- What OS are you running grafana on? **Ubuntu 16.04 LTS **

I want to be able to plot a metric (e.g. `node_cpu_used_total`) with the possibility of drilling down by node_type by choosing it from template variable.

Assume that prometheus will return the following
```
node_cpu_used_total{node_type="frontend"} 1.0
node_cpu_used_total{node_type="backend"} 2.0
```

I would like to be able to make a template variable `node_type` where the options are `all, frontend, backend` such that when I select `all`, it will return 3.0, and the respective drilldown value from the other two.

In Grafana 2.6.x, I could do this by adding an aggregation rule so that the empty label will return the sum, i.e.
```
node_cpu_used_total{node_type=""} 3.0
node_cpu_used_total{node_type="frontend"} 1.0
node_cpu_used_total{node_type="backend"} 2.0
```
And I would set the All Format to be empty or custom and use the empty string.

![allformat](https://cloud.githubusercontent.com/assets/3450274/19038047/951f48a2-8971-11e6-8bf9-ef24026c919f.png)

However, in Grafana 3 there is no way to set the custom value to be the empty string since the empty string defaults to the equivalent of `pipe` in Grafana 2.6.x. i.e. it will send the query 
```
node_cpu_used_total{node_type="frontend|backend"}
```

![newall](https://cloud.githubusercontent.com/assets/3450274/19038031/7a2bcc5a-8971-11e6-8531-bef6ed83a41e.png)

It would be nice if we can bring back the AllFormat from Grafana 2.6.x or have the option of "empty" so that it doesn't default to `pipe`

A longer term solution, without the empty label hack, is to allow different query to be executed based on the value of the variable. i.e.

```
all -> sum (node_cpu_used_total) by (node_type) 
frontend -> node_cpu_used_total{node_type="frontend"}
backend -> node_cpu_used_total{node_type="backend"}
```

**Comment by torkelo** [comment]
you can specify /.*/ as a custom all value (and change operator to =~)

**Comment by 0verc1ocker** [comment]
Thank you for the solution to specify custom all value @torkelo !

**Comment by quberok** [comment]
I specified **.*** (not /.*/) as a custom all value and changed operator to =~ and it helped
