### ISSUE TITLE
Pemission issues after upgrade from 8.5.9 to 9.3.2

### ISSUE THREAD

**Issue by azreenariff** [grafana/grafana#61744]
**What happened**:
After upgrading Grafana Enterprise from version 8.5.9 to version 9.3.2 we encountered problems like below:
- `Admin` user now like normal user - there is no shield (**Server Admin**) button, **Configuration** button only has _Plugins_ in it's menu and no **Explore** button
![2023-01-19_13-38-31](https://user-images.githubusercontent.com/54944096/213411193-45ac8afd-68e4-4419-af0c-286b99d867f1.png)
- There appears _Annotations Read_ permisson error
![2023-01-18_16-48-13](https://user-images.githubusercontent.com/54944096/213407457-3578f3c5-3b21-46d4-a3b2-d6beb44fd918.png)
- There appears _Failed to upgrade legacy queries Datasource_ error
![2023-01-19_14-08-13](https://user-images.githubusercontent.com/54944096/213407887-63a63ce1-fd19-4be5-9178-7e7dd089061b.png)
- Then, we tried to use below SQL script proposed from https://github.com/grafana/grafana/issues/54974#issuecomment-1252179049, but it did not resolve our issue
``` 
DELETE
FROM builtin_role
where role_id IN (SELECT id
                  FROM role
                  WHERE name LIKE 'managed:%');

DELETE
FROM team_role
where role_id IN (SELECT id
                  FROM role
                  WHERE name LIKE 'managed:%');

DELETE
FROM user_role
where role_id IN (SELECT id
                  FROM role
                  WHERE name LIKE 'managed:%');

DELETE
FROM permission
where role_id IN (SELECT id
                  FROM role
                  WHERE name LIKE 'managed:%');

DELETE
FROM role
WHERE name LIKE 'managed:%';

DELETE
FROM migration_log
WHERE migration_id IN ('teams permissions migration',
                       'dashboard permissions',
                       'dashboard permissions uid scopes',
                       'data source permissions',
                       'data source uid permissions',
                       'managed permissions migration',
                       'managed folder permissions alert actions repeated migration',
                       'managed permissions migration enterprise');
```
- So, now basically it is now useless and we are unable to administer Grafana

**What you expected to happen**:
We expected that the upgrade would be successful without facing any errors after upgrade

**How to reproduce it (as minimally and precisely as possible)**:
On a running Grafana Enterprise 8.5.9 - download the RPM for Grafana Enterprise 9.3.2 and install using `dnf install`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: Using MySQL as backend DB
- OS Grafana is installed on: RHEL 8
- User OS & Browser: RHEL 8 & Chrome browser
- Grafana plugins: MySQL
- Others: n/a

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @azreenariff 

Did you use [User provisioning](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-grafana-provisioning/) for creating changing or removing roles? If so, please share the steps you took.

So far, this issue seems a duplicate from the [one you referenced](https://github.com/grafana/grafana/issues/54974). However, we might keep it open to avoid mix ups since there are some slight differences between the two. 

In the meantime, I am moving this issue to the Auth squad.

**Comment by azreenariff** [comment]
Hi @tonypowa 

Thanks for replying. No we didn't use the user provisioning

**Comment by mgyongyosi** [comment]
Hi @azreenariff,

Could you please provide the migration logs? (If you didn't save it then you can restore the database of the working 8.5.9 version and start the 9.3.2 version again and you can copy the logs)

and/or the migration logs from the database by running the following:
```
select * from migration_log where error <> ''
```

Thanks

**Comment by azreenariff** [comment]
> Hi @azreenariff,
> 
> Could you please provide the migration logs? (If you didn't save it then you can restore the database of the working 8.5.9 version and start the 9.3.2 version again and you can copy the logs)
> 
> and/or the migration logs from the database by running the following:
> 
> ```
> select * from migration_log where error <> ''
> ```
> 
> Thanks

Hi @mgyongyosi 

Attached here is the migration log

[migration_log.sql.zip](https://github.com/grafana/grafana/files/10505480/migration_log.sql.zip)

**Comment by mgyongyosi** [comment]
Hi @azreenariff,

Could you please run Grafana again with the following setting once?:
```
[rbac]
reset_basic_roles=true
```

It would reset the basic roles' permissions to the default. Please don't forget to make a database backup before starting Grafana with this setting, just to be sure.

**Comment by azreenariff** [comment]
Hi @mgyongyosi ,

We have restarted Grafana with the suggested setting. However, nothing changed, the issue is still the same and the admin user still doesn't have admin permission.
