### ISSUE TITLE
[Feature request] Do not plot 0 values

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#6175]
Hello,

Would be nice to be able to avoid plotting 0 values (for lines & points).
This would avoid X axis to be overfilled by lines & points which sometimes have values >0 and most of the time are 0.

![s1](https://cloud.githubusercontent.com/assets/6764151/19053165/fff4a2ce-89b9-11e6-8742-293a17c66a29.png) ![s2](https://cloud.githubusercontent.com/assets/6764151/19053177/0deb0986-89ba-11e6-99dd-2acb1a20962a.png)

As a workaround I set Y axis minimum value to 0.1, but it is not really nice.

Thank you 👍 

Ben

**Comment by DanCech** [comment]
If you're using graphite [removeBelowValue](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeBelowValue) can translate the 0 values into nulls

**Comment by benrubson** [comment]
Thank you Dan for your advice 👍 
Unfortunately I'm using OpenTSDB.

**Comment by torkelo** [comment]
I think this is better handled by the TSDB query,
