### ISSUE TITLE
G10 Get Started: Loki (Part 2)

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#61769]
### Summary

Follow up from https://github.com/grafana/grafana/issues/57731 . In Part 1, we did an internal review through different excercises and sessions, to identify opportunities to improve the Getting Started experience when using the Loki Datasource. There, we completed several improvements.

### Problem statement

A key goal of Grafana 10 is to improve the getting started experience in Grafana, where that journey is defined as going from an empty instance to monitoring something. 

### Scope

- Further user interview.
- UX-derived tasks.

### Solution

This Part 2 is about coordination with the UX team, to implement more advanced improvements based on further research and user interviews.

### Resources
UX Discovery https://docs.google.com/document/d/1NmptkQwjfDPijA3YW7SrYtMEJ7DLgqyZcCWdFBZ2n74/edit

**Comment by liguozhong** [comment]
loki log explore add progress bar please. 
https://github.com/grafana/grafana/discussions/61598
