### ISSUE TITLE
Make it easier to use templates when creating and editing contact points

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#61762]
Right now it is very hard to know how to use templates when creating a contact point integration:

<img width="677" alt="SS 2023-01-19 at 13 12 17" src="https://user-images.githubusercontent.com/2117580/213440125-eb08b0f4-e217-4b5e-8bb6-073d7f00d275.png">

The first step here is to allow selecting a template from a dropdown (see https://github.com/grafana/grafana/issues/63468)

**Comment by soniaAguilarPeiron** [comment]
I think this one should be blocked until we have the new api from the BE. Depending on these new api we can implement the solution differently.

**Comment by gillesdemey** [comment]
Perhaps we need a default to select from your list of templates but allow manual template definitions.

**Comment by gillesdemey** [comment]
Closing this one in favor of https://github.com/grafana/grafana/issues/63468
