### ISSUE TITLE
Show the default templates in the UI

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#61761]
Show the [default templates](https://github.com/grafana/alerting/blob/b9b3de89bca2879366f023f570b787a00fe834e6/alerting/notifier/channels/default_template.go) in the UI that users can use as a reference for writing their own templates. The default templates cannot be edited or deleted.

BE endpoint is required that exposes default templates

**Comment by gillesdemey** [comment]
This one needs some help from the BE team to list the default templates we load in to Grafana.

**Comment by grobinson-grafana** [comment]
@gillesdemey I'm going to start writing a design document for this 🤗

**Comment by grobinson-grafana** [comment]
This will also be a duplicate of https://github.com/grafana/grafana/issues/61761.
