### ISSUE TITLE
Logs: Easier search and filter from log lines

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#61765]
### Summary

It's been mentioned that it would be useful for users to be able to filter log lines by clicking on parts of them which could add or remove labels from the query. It seems like a very interactive way of exploring data, which could enhance the logging experience for all of our users.

This feature was also identified during an internal UX exploration excercise.

Design doc: https://docs.google.com/document/d/1SZ6z6aI167mJY-0A0SCda204QixeBOYVoZi_SBK8ilU/edit

### Scope

We need to explore the technical feasibility of toggling filters by interacting with log lines and, with those results, work with UX to develop a proposal to support this feature.

### Solution

With the results of the technical exploration of this feature, we will work in combination with UX to come up with the best possible way to support interactive log filtering from long lines. The end result will be the availability of this feature for users, provided that UX and engineering concludes that it's something that we can support.

### Measurement

Users should interact with this feature, hopefully improving the way they filter and search through log lines. Metrics TBD.

### Resources

**Comment by gabor** [comment]
one "complexity" we should not forget about is mixed-datasources, so, in theory, you might have explore with a loki logs query and an elastic logs query, and the results from both queries are shown in the same logs-visualization.

**Comment by matyax** [comment]
We couldn't advance with this task in Q1, moving it out of it. Will reconsider during Q2 planning.
