### ISSUE TITLE
Test notification templates from within Grafana

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#61764]
### Background

Grafana users can use custom notification templates to change how their notifications look. Management of notification templates happens on the Contact points tab, and here users can create, edit, delete and duplicate notification templates.

However, whenever a user wants to test their notification templates they must first save the template by clicking the “Save template” button, either create or edit an existing contact point, reference the template from the contact point, and then click the “Test” button. If the template is incorrect, or the user would like to make further changes then this process must be repeated until the template works as intended.

We want to add a preview feature to both the Create notification template and Edit notification template pages that will allow users to preview their template, similar to how it works when testing contact points.

Design Doc: https://docs.google.com/document/d/1Q9WfGhA4SAy4Gxda98931AEXrJ6S-go4OB6_1-o_7z8

```[tasklist]
### Backend
- [ ] https://github.com/grafana/grafana/issues/66765
- [ ] https://github.com/grafana/grafana/issues/66766
- [ ] https://github.com/grafana/grafana/issues/66767
- [ ] https://github.com/grafana/grafana/issues/66768
- [ ] https://github.com/grafana/grafana/issues/66769
- [ ] https://github.com/grafana/grafana/issues/66770
- [ ] https://github.com/grafana/grafana/issues/66771
- [ ] https://github.com/grafana/grafana/issues/66772
```

```[tasklist]
### Frontend
- [ ] https://github.com/grafana/grafana/issues/67523
```

```[tasklist]
### Docs
- [ ] https://github.com/grafana/grafana/issues/67119
- [ ] https://github.com/grafana/grafana/issues/67095
- [ ] https://github.com/grafana/grafana/issues/67120
```

**Comment by gillesdemey** [comment]
Currently blocked by a missing API endpoint (and I don't want to go down the WASM road) but FE work can be done in parallel.
