### ISSUE TITLE
[xorm] quota service migrate from xorm to sqlx

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#61773]
Replace xorm with sqlx for [Quota Service](https://github.com/grafana/grafana/tree/main/pkg/services/quota) 

Background
Some context on why we are moving away from xorm and what made us chose sqlx:[Design Doc](https://docs.google.com/document/d/1vm5mBZchsr7pFjyJ9bsJkk7TXpmLS0JM79tuBSqhEFM/edit#heading=h.bt5za353e3fn)

Example & Steps
- how to migrate one service: [star service migration](https://github.com/grafana/grafana/pull/53430)
You need feature toggle to enable sqlx or xorm: [feature toggle](https://github.com/grafana/grafana/pull/53430/files#diff-60abe2baae10d14ade2ac3aac9d745bdf9129647fa7fec1411d2a13a5f396757R16)
- Reuse the same unitest as before, giving a new sqlstore implementation as [new test](https://github.com/grafana/grafana/pull/53430/files#diff-444ec9fede7931678a3e080163e1fe5607086f261ce94b38200cd73e0ad71f00R1)
- Add unittest when the store function is not well tested make sure that it is bug free

**Comment by Xilesun** [comment]
Hi @ying-jeanne , can I work on this?
