### ISSUE TITLE
[Feature request] Disablable autoescape feature for constant template

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#6179]
Please include this information:

* What Grafana version are you using?
 Grafana v3.1.1 (commit: a4d2708)
* What datasource are you using?
 Influxdb 1.0
* What OS are you running grafana on?
 RHEL 7.2
* What did you do?
 I'm automating grafana dashboard with custom templating. Trying to show aggragated link i found a trouble with autoescaping. 
 on a server side i build such template 

```
{
"multi": true,
"hide": 0,
"name": "trunk",
"refresh": 0,
"label": "Trunk",
"current": {
"text": "Eth 1/25 descr",
"selected": true,
"value": [
"(Eth 1\/25)"
],
"tags": []
},
"datasource": null,
"query": "Eth 1/25,Eth 1/26,Eth 1/27,Eth 1/28,(Eth 1/27|Eth 1/28),",
"type": "custom",
"options": [
{
"text": "All",
"selected": false,
"value": "$__all"
},
{
"text": "Eth 1/25 descr",
"selected": false,
"value": "(Eth 1\/25)"
},
{
"text": "Eth 1/26 descr",
"selected": false,
"value": "(Eth 1\/26)"
},
{
"text": "Eth 1/27 descr",
"selected": false,
"value": "(Eth 1\/27)"
},
{
"text": "Eth 1/28 descr",
"selected": false,
"value": "(Eth 1\/28)"
},
{
"text": "Ling aggregation 1",
"selected": false,
"value": "(Eth 1\/27|Eth 1\/28)"
}
],
"includeAll": true
}
```

and i want to query it like this 

```
SELECT sum("value") FROM "Interface | Load | In" WHERE "object" =~ /^switch-01$/ AND "interface" =~ /^(Eth 1\/27|Eth 1\/28)$/ AND time > now() - 6h GROUP BY time(5m), "interface" fill(null);
```

i am using it like that 
![pic!UNITO-UNDERSCORE!a7820a7820a7820](https://cloud.githubusercontent.com/assets/289277/19067574/ec0ddfb6-8a2f-11e6-9926-35ed07f7e506.png)

Of cause that code does't work because value was autoescaped.

* What was the expected result?
 graph 
* What happened instead?
 my query became overescaped 

```
SELECT mean("value") FROM "Interface | Load | In" WHERE "object" =~ /^switch-01$/ AND "interface" =~ /^\(Eth 1\/27\|Eth 1\/28\)$/ AND time > now() - 6h GROUP BY time(300s), "interface" fill(null);
```

I will be great if i can add an option that will disable autoescape feature.

**Comment by daniellee** [comment]
This is implemented. The raw option: https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#raw
