### ISSUE TITLE
User with Viewer privileges can run arbitrary queries on InfluxDB proxy datasources

### ISSUE THREAD

**Issue by marcv81** [grafana/grafana#6180]
**Type**: Bug report (security)
**Grafana** version: Grafana v3.1.1 (commit: a4d2708) (from deb package)
**Datasource**: InfluxDB proxy
**OS**: Ubuntu 16.04.1 LTS

**Steps to reproduce**

Anonymous access is configured as follows in `grafana.ini`.

    #################################### Anonymous Auth ##########################
    [auth.anonymous]
    # enable anonymous access
    enabled = true

    # specify organization name that should be used for unauthenticated users
    ;org_name = Main Org.

    # specify role for unauthenticated users
    ;org_role = Viewer

The `collectd_db` database and the `grafana` user are created as follows. The InfluxDB proxy datasource uses them.

    CREATE DATABASE collectd_db
    CREATE USER grafana WITH PASSWORD 'grafana'
    GRANT READ ON collectd_db TO grafana

The following HTTP request returns all the series from the InfluxDB `collectd_db` database.

    curl 'http://<server>:3000/api/datasources/proxy/1/query?db=collectd_db&q=SHOW%20SERIES'

**Expected behaviour**

Grafana should only proxy the InfluxDB queries it relies on. Arbitrary queries should not be allowed.

If the `grafana` user has been configured with more than `READ` permissions this bug could lead to data loss.

**Comment by torkelo** [comment]
there is no such feature currently, Grafana data proxy is only simple http proxy, it have access (login) and access to an organization with a specific data source ,then you can issue any http call to that data source. 

There is no "per query" permissions in InfluxDB, so it would almost be impossible to do what you ask. Simple regex queries / wildcard queries would easily work around any attempt at limiting what queries can be performed. 

If you need more security control, separate your data into separate InfluxDB databases, and create multiple organizations for each. 

Another way to share "view" only data is to create snapshots and share those.

**Comment by torkelo** [comment]
this would be a bit easier if there was some way for Grafana to tell influxdb what measurements/tags are allowed in a query

**Comment by marcv81** [comment]
Thanks for your reply @torkelo. I'm happy with this being closed as it is low impact and would be very complicated to fix given the current architecture. The only high impact would be if the InfluxDB Grafana user was configured with more than `READ` privileges. Maybe this deserves a warning in the "Add data source" screen?

**Comment by matthijskooijman** [comment]
I also noticed this, while I was hoping to expose only selected content to some users. Hm.

> There is no "per query" permissions in InfluxDB, so it would almost be impossible to do what you ask. Simple regex queries / wildcard queries would easily work around any attempt at limiting what queries can be performed.

Regexing or matching against browser-supplied queries is not going to work, I agree there. But is it even needed for the browser to supply a query?

I am probably missing the architectural overview here, but I would have thought that the browser just asks the backend "Please give me the results of query A for dashboard X, panel Y" and also passes any parameters (e.g. time window). The backend knows exactly what query it should run, so there is no need for the browser to specify the query at all.

Of course for users with Editor rights, or when viewers_can_edit is enabled, the user can enter arbitrary queries which the browser must supply to the backend, but in a strictly view-only case I do not see the need (though having two separate ways to execute queries is a bit cumbersome, but probably not too complicated)?

**Comment by paulwer** [comment]
could it be an option to implement a kind of inherited data-source OR data-source-filters, which alters all query/requests to an actual data-source. this sources then could be used to manage authentification for each user.

Any ideas on that?
