### ISSUE TITLE
Some metrics are not getting displayed

### ISSUE THREAD

**Issue by tesla747** [grafana/grafana#6182]
* **I'm submitting a ...**
- Bug report

Please include this information:
- What Grafana version are you using?
grafana-latest-1.x86_64.rpm -- 4.0 from nightly build

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
RHEL 6.4

- What did you do?
I have a server where I have deployed Prometheus and Grafana to monitor remote MySQL servers where I have deployed node and mysql exporters.

- What was the expected result?
All the metrics are getting scraped and not everything is getting properly visible in Grafana. No errors in Prometheus/node exporters/mysqld exporters logs. Prometheus is showing graphs of scrapes as well.

- What happened instead?

Uptime/QPS/BufferPoolSize/ is in loading state and it doesn't show up any value for those metrics::
Other metrics are showing up fine.

FYI, I have another server where I have deployed the same way but this issue doesn't crop up there.

![image](https://cloud.githubusercontent.com/assets/20291387/19074670/ede0f40c-8a5e-11e6-854d-694e8412e298.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
![image](https://cloud.githubusercontent.com/assets/20291387/19074695/05c7b4f2-8a5f-11e6-909f-af9327270884.png)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
Hoping i'm providing the right info to debug the issue. Please let me if anything else is required.

![image](https://cloud.githubusercontent.com/assets/20291387/19074737/41fc9aaa-8a5f-11e6-92ac-56f795c305f2.png)

**Comment by torkelo** [comment]
what commit / date is your nightly build ?

**Comment by torkelo** [comment]
you can see that when you start grafana (in the logs), it should print the commit

**Comment by tesla747** [comment]
Nightly Build -- 03/10/2016, 20:49:17

Grafana is already started no? Anything else needs to be checked?

**Comment by torkelo** [comment]
can you try with latest master ? unable to replicate this

**Comment by tesla747** [comment]
Let me try this -- Redhat/Centos (64bit) .rpm package	grafana-latest-1.x86_64.rpm	10/5/2016, 7:45:30 PM and will update.

**Comment by tesla747** [comment]
Yes it worked after new master installation but im facing this issue::

![image](https://cloud.githubusercontent.com/assets/20291387/19148890/97436024-8bdc-11e6-8c92-b3cdef8143b5.png)

![image](https://cloud.githubusercontent.com/assets/20291387/19148991/390a0ed0-8bdd-11e6-8bfb-15cfe679c7fe.png)

Let me know if I need to create this as a new bug or this is fine and if any more info is required to debug the same.

**Comment by torkelo** [comment]
I have test al maner of prometheus dashboards, with different template variables used in different ways cannot find any issue :(
