### ISSUE TITLE
Feature request: Maximum repetition count

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#6185]
We added datacenter fuses to Prometheus over the weekend and now have fuse counts in the four figures in there. We would obviously like to have repeat panels for some fuses, but I need to make sure I don't nuke Prometheus/Grafana/the local browser with 1000 graphs at once.

The easiest way out would be a maximum repetition limit. After X panels, just stop drawing new ones and visualize this limit, optionally with a count of omitted graphs/panels.

The best place to configure this limit would be in the repeat configuration.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by davkal** [comment]
Sounds useful still. @olbo98 is that something you want to try?

**Comment by olbo98** [comment]
> Sounds useful still. @olbo98 is that something you want to try?

Yeah sounds fun, i'll do it!
