### ISSUE TITLE
Group by Terms showing only hyphen although field is not_analyzed

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#6186]
Index template has a field which is not_analyzed.

![image](https://cloud.githubusercontent.com/assets/1611494/19082291/69800b52-8a55-11e6-99b2-1ded0d67eeda.png)

But when I put it in terms, I get only hyphens:

![image](https://cloud.githubusercontent.com/assets/1611494/19082243/3824f036-8a55-11e6-9803-87534c7d2160.png)
![image](https://cloud.githubusercontent.com/assets/1611494/19082262/4b125440-8a55-11e6-9d93-d930d6806a59.png)

Here's the graph panel config:

![image](https://cloud.githubusercontent.com/assets/1611494/19082269/57744c02-8a55-11e6-8655-f893e77f1d9f.png)

ES and Grafana are latest versions installed last week.

**Comment by oazabir** [comment]
Kibana shows the field is not analyzed as well and can group by this field nicely.

**Comment by torkelo** [comment]
please include the raw response from elasticsearch, (open chrome dev tools network tab, look for _msearch request)

**Comment by oazabir** [comment]
Request

```
{"search_type":"count","ignore_unavailable":true,"index":["ovlog-2016.10.05.06","ovlog-2016.10.05.07","ovlog-2016.10.05.08","ovlog-2016.10.05.09"]}
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"message:SBL"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1475648768907","lte":"1475659568908","format":"epoch_millis"}}}]}}}},"aggs":{"3":{"terms":{"field":"keyword","size":10,"order":{"_count":"desc"}},"aggs":{"2":{"date_histogram":{"interval":"20s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1475648768907","max":"1475659568908"},"format":"epoch_millis"},"aggs":{}}}}}}
```

Response is huge. Attached. 
[response.zip](https://github.com/grafana/grafana/files/510574/response.zip)

**Comment by oazabir** [comment]
Apology, I found the problem. The alias has a "-" on it mistakenly. 

But could you check if the response should be this big? Over 350K?

**Comment by LANRRI** [comment]
>
![image](https://cloud.githubusercontent.com/assets/16147268/20166748/db68c0d8-a751-11e6-92d4-63ad98f6a0e1.png)
i have data type like this in ES , and i can not get any data with wildcard query : "requesturl:'POST*events*'"

with query: "requesturl:'POST/events/cdc/generateeventHTTP/1.1'", it can filter what i want,

so how can i use wildcard query  in grafana ?
![image](https://cloud.githubusercontent.com/assets/16147268/20166829/7220e726-a752-11e6-8bde-ec6fcc2ec3c5.png)

**Comment by torkelo** [comment]
Check out elasticsearch  Lucerne query sybtax
