### ISSUE TITLE
Explore: some values don't display on hover

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#61866]
**What happened**:

As seen in the video, when all series are shown I cannot see the value of the yellow section on hover.
If I show just the yellow part I can see the value when I move to the top of its section.

https://user-images.githubusercontent.com/8125524/213734977-22a085a2-6d7a-4ad4-8dbe-4f56c236f70d.mp4

**What you expected to happen**:

Be able to see the value when I hover over the largest section.

**How to reproduce it (as minimally and precisely as possible)**:

If you're internal to Grafana the URL I was using is [here](https://admin-ops-us-east-0.grafana.net/stable-grafana/explore?left=%7B%22datasource%22:%22P666011C0B63BDCA4%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P666011C0B63BDCA4%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%20%28container%29%28kube_pod_container_resource_requests%7Bcluster%3D%5C%22prod-us-central-0%5C%22,%20namespace%3D%5C%22loki-prod%5C%22,%20resource%3D%5C%22memory%5C%22%7D%29%20%2F%20%281024%2A1024%2A1024%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:false,%22exemplar%22:false,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221674216646319%22,%22to%22:%221674220246319%22%7D%7D&orgId=1).

My impression is this happens on any data where there is a very thin bar above a thick bar.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.2 (21c1d14e91)
- Data source type & version: Prometheus & no idea.
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10 Version 21H2 (Build 19044.2486) & Google Chrome 109.0.5414.74 (Official Build)
- Grafana plugins: no idea how to provide this.
- Others:

**Comment by leeoniya** [comment]
the area fills are "fill below", and the cursor proximity is checked to the actual datapoints, which are at the top of each area.

if the graph is in stacked/filled mode we can probably bias this proximity test to the nearest above the cursor, not simply nearest.

**Comment by leeoniya** [comment]
actually never mind. i just re-read this not on a phone and see what you mean. if you have a stack and the series above is 0, it as the same accumulated value as the one below it, so the proximity to the cursor is the same. we should bias this to select the one with the bigger raw value.

**Comment by leeoniya** [comment]
related:

https://github.com/grafana/grafana/issues/61615
https://github.com/grafana/grafana/pull/61432

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/commit/904c9ec18adabb0b0ee6102d3287415fe15a5150 adds a focus biasing setting that should make it more natural to focus when hovering the filled area under the line rather than needing to be withing a certain proximity to the line itself.

it doesn't solve the stacking situation, but should be a nice quality of life improvement.

demo: https://leeoniya.github.io/uPlot/demos/focus-cursor.html

**Comment by leeoniya** [comment]
> it doesn't solve the stacked/0-value situation, but should be a nice quality of life improvement.

https://github.com/leeoniya/uPlot/commit/b2ba786ae5cd8ad91a69d9e488abb1195c6acce1, however, _does_ fix it. (above demo updated to exhibit the fix)

**Comment by leeoniya** [comment]
fixed.

i kept focus biasing off, since it's currently mutually exclusive with the proximity threshold. i'll fix that in a future uPlot update.
