### ISSUE TITLE
No datapoints returned from CloudWatch datasource

### ISSUE THREAD

**Issue by rossigee** [grafana/grafana#6187]
* **I'm submitting a ...**
- [ ] Bug report

Please include this information:
- What Grafana version are you using?
 Grafana v3.1.1 (commit: a4d2708)

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Linux

- What did you do?
Configured Cloudwatch using 'AWS_ACCESS_KEY_ID' and 'AWS_SECRET_ACCESS_KEY' envvars (a lot easier than the creds file approach, you should probably document it). 'Save and Test' confirms connection is OK. Create a graph containing queries for S3 metrics in the 'eu-west-1' region, as I can see from the AWS management console that I have metrics for this combination.

- What was the expected result?
To see pretty graphs.

- What happened instead?
No datapoints returned, no pretty graphs. No errors/warnings.

Request payload looks like this...

{"region":"eu-west-1","action":"GetMetricStatistics","parameters":{"namespace":"AWS/S3","metricName":"NumberOfObjects","dimensions":[],"statistics":["Sum"],"startTime":1473006868,"endTime":1475598868,"period":1800}}

Response looks like this...

{"Datapoints":null,"Label":"NumberOfObjects"}

**Comment by torkelo** [comment]
Strange, maybe something wrong with your cloudwatch account?

**Comment by torkelo** [comment]
Its not much grafana can do it the query is correct which it looks like

**Comment by mtanda** [comment]
You may need to set dimension.
Similar question, https://github.com/grafana/grafana/issues/5565 .
