### ISSUE TITLE
PanelEdit: Units: `scaledUnits` fn does not handle `undefined` data type

### ISSUE THREAD

**Issue by heliodor** [grafana/grafana#61881]
**What happened**:

A plugin (ImageIt) passes `undefined` to the value formatter. The value formatter function does not handle this value gracefully and leads to an error: `TypeError: Cannot read properties of undefined (reading 'toLocaleString')`

**What you expected to happen**:

undefined data should output either an empty string or pass through unchanged and output `undefined`.

**How to reproduce it (as minimally and precisely as possible)**:

No need. It's clear from the code that the value of `undefined` leads to a javascript error. Here's the current code crashing at
https://github.com/grafana/grafana/blob/4f2d30b1533f3965cc62ed3a23c3d0409a37c475/packages/grafana-data/src/valueFormats/valueFormats.ts#L144
```
export function scaledUnits(factor: number, extArray: string[], offset = 0): ValueFormatter {
  return (size: number, decimals?: DecimalCount) => {
    if (size === null) {
      return { text: '' };
    }

    if (size === Number.NEGATIVE_INFINITY || size === Number.POSITIVE_INFINITY || isNaN(size)) {
      return { text: size.toLocaleString() };
    }

    const siIndex = size === 0 ? 0 : Math.floor(logb(factor, Math.abs(size)));
    const suffix = extArray[clamp(offset + siIndex, 0, extArray.length - 1)];

    return {
      text: toFixed(size / factor ** clamp(siIndex, -offset, extArray.length - offset - 1), decimals),
      suffix,
    };
  };
}
```
Pass in `undefined` as the value of the parameter `size`. `isNaN(undefined)` is `true`. Go inside the `if` statement. `undefined.toLocaleString()` will crash on line 144.

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version:
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser: OSX
- Grafana plugins: ImageIt
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @heliodor 

ImageIt is a third-party plugin and it looks like it's been [archived](https://github.com/pierosavi/pierosavi-imageit-panel). 

It also looks like that is a frontend-datasource plugin and not the newer backend datasource plugins that we now ask developers to build. Is this error occuring with any other plugin?

**Comment by heliodor** [comment]
@zuchka, these details shouldn't really matter. The function of code I pointed out does not handle the `undefined` case. If this function remains exposed to the outside as an API, then it will continue to get called with the value of `undefined` in the future too.
