### ISSUE TITLE
 Remove simplejson from AzureMonitor

### ISSUE THREAD

**Issue by asimpson** [grafana/grafana#61882]
The `simplejson` library is [no longer recommended by the backend team](https://github.com/grafana/grafana/blob/main/contribute/style-guides/backend.md?plain=1#L189). Therefore the  @grafana/partner-plugins  team has decided to factor the library out of our plugins in favor of the `encoding/json` package that's part of the Go standard library.

- Previous work for Cloudwatch https://github.com/grafana/grafana/pull/51062

**Implementation guidelines**
- Do not use anonymous structs
- Existing tests should pass unless they rely on `simplejson` as well

**Comment by Vivek-Prajapatii** [comment]
Hi @asimpson, may i take this up, and i'm new to this project can you guide me up?
thank you

**Comment by asimpson** [comment]
@Vivek-Prajapatii I tagged this with `good-first-issue` for someone new to @grafana/partner-plugins not necessarily new to the codebase as a whole. The work will consist of refactoring all  instances of `simplejson` to Go structs and marshaling/unmarshaling those types into JSON.
