### ISSUE TITLE
Alias by does not work for tags, using either syntax

### ISSUE THREAD

**Issue by joelittlejohn** [grafana/grafana#6188]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
    - 3.1.1 (commit: a4d2708)
- What datasource are you using?
    - influxdb
- What OS are you running grafana on?
    - ubuntu-trusty-14.04-amd64-server-20160509.1 (ami-f9a62c8a)

I'm creating a graph that includes data with a tag key `service`. When I try to set ALIAS BY to either `$tag_service` or `[[tag_service]]`, instead of seeing the tag value in the legend I just see either `$tag_service` or `[[tag_service]]`. The expression is not resolved.

Here's what the editor looks like:

![image](https://cloud.githubusercontent.com/assets/686384/19083500/43b4269c-8a5a-11e6-9774-9711f5a131da.png)

and here's the resulting graph:

![image](https://cloud.githubusercontent.com/assets/686384/19083521/57f6e7fc-8a5a-11e6-953f-d30be556b1e1.png)

Using the Chrome dev tools network tab I can see the following response when the UI sends `SHOW TAG KEYS`:
```json
{"results":[{"series":[{"name":"jvm_memory","columns":["tagKey"],"values":[["instance"],["metricName"],["service"]]}]}]}
```

and if I try to add a new condition to the WHERE clause, then I see `service` listed in the available tag keys. So, I don't know why `$tag_service` is not resolved.

Thanks!

**Comment by torkelo** [comment]
You need to group by a tag for InfluxDB to group by it / return it

**Comment by joelittlejohn** [comment]
@torkelo Thanks for the help and apologies for the noise.

**Comment by ham1** [comment]
This info should be in the docs: http://docs.grafana.org/features/datasources/influxdb/#alias-patterns
