### ISSUE TITLE
datasource template variable not handled properly when exporting dashboard

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#6189]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-pre1
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu
- What did you do? Exported then imported a dashboard that uses a templated datasource variable
- What was the expected result? The datasource variable should work
- What happened instead? Panels & variables using the datasource variable become hard-coded

When a dashboard using templated datasource variables is exported, the datasource type should be added to the `__requires` list, and the `current` and `options` attributes of the datasources variable(s) should be scrubbed.

Currently at export grafana instead adds an entry in `__inputs` and changes all the `datasource` entries in panel and variable definitions from eg `"datasource": "$datasource",` to eg `"datasource": "${DS_MT-TEST-DEB}",`.  This means that at import time the user is prompted to select a datasource, and all the panels & non-datasource variables are then hardcoded to use that DS, so the data source selector will have no effect on the imported dashboard.

Additionally, the `current` and `options` attributes of the datasource variable(s) are not cleared out at export time, which is an information disclosure vulnerability.  These should be handled in the same way as other templated variables and cleared out at export time.

**Comment by cvielma** [comment]
I'm also experiencing this issue (Grafana 3.1.1)

**Comment by Dieterbe** [comment]
I can still reproduce this with b00e9390d34e27da1ac3aab8e27a0f535a4c75fd 

I run
```
    curl -u admin:admin \
      -H "content-type: application/json" \
      'http://localhost:3000/api/dashboards/import' -X POST -d "
        {
          \"dashboard\":
             $(cat $file),
          \"overwrite\": true,
          \"inputs\": [
            {
              \"name\": \"DS_GRAPHITE\",
              \"type\": \"datasource\",
              \"pluginId\": \"graphite\",
              \"value\": \"graphite\"
            }
          ]
        }"
```

when i open the UI i see that all the datasource settings in the panels are fixed to `graphite`, not `$datasource`.

**Comment by torkelo** [comment]
did you re-export the dashboard?

it working here.
