### ISSUE TITLE
invalid value / unknown config name: custom

### ISSUE THREAD

**Issue by SunSparc** [grafana/grafana#61893]
**What happened**:
When I specify both `type = mysql` and `ssl_mode = true` in the `[database]` section of the config file, I get this error message:
```
bash-5.1$ /local/grafana/bin/grafana-server --config=/grafana.ini --homepath=/local/grafana
INFO [01-20|23:36:34] Starting Grafana                         logger=settings version=9.3.1 commit=89b365f8b1 branch=HEAD compiled=2022-12-01T12:45:45Z
INFO [01-20|23:36:34] Config loaded from                       logger=settings file=/local/grafana/conf/defaults.ini
INFO [01-20|23:36:34] Config loaded from                       logger=settings file=/grafana.ini
INFO [01-20|23:36:34] Path Home                                logger=settings path=/local/grafana
INFO [01-20|23:36:34] Path Data                                logger=settings path=/local/data
INFO [01-20|23:36:34] Path Logs                                logger=settings path=/local/grafana/data/log
INFO [01-20|23:36:34] Path Plugins                             logger=settings path=/local/grafana/data/plugins
INFO [01-20|23:36:34] Path Provisioning                        logger=settings path=/local/grafana/conf/provisioning
INFO [01-20|23:36:34] App mode production                      logger=settings
INFO [01-20|23:36:34] Connecting to DB                         logger=sqlstore dbtype=mysql
Failed to start grafana. error: failed to connect to database: invalid value / unknown config name: custom
failed to connect to database: invalid value / unknown config name: custom
bash-5.1$
```
If I remove `type = mysql` and run the server, it proceeds. If I leave the `type`, remove `ssl_mode = true`, and run the server, it proceeds.

**What you expected to happen**:
No errors, or at least a more helpful error.

**How to reproduce it (as minimally and precisely as possible)**:
Specify both `type = mysql` and `ssl_mode = true`:
```
[database]
type             = mysql
host             = <hostname>:<port>
name             = grafana
server_cert_name = <hostname>
user             = <username>
password         = <password>
ssl_mode         = true
ca_cert_path     = /etc/ssl/certs/ca-certificates.crt
```

**Anything else we need to know?**:
I run this on a new server with an empty database.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: n/a
- OS Grafana is installed on: Linux Ubuntu 22.04.1 LTS
- User OS & Browser: n/a
- Grafana plugins: n/a
- Database: DigitalOcean MySQL 8 cluster

**Comment by zuchka** [comment]
Thanks for creating this issue, @SunSparc 

in order to help us troubleshoot this as fast as possible, can you please try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to `debug` and note any errors. For printing to console, [set the console logs to `debug`](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) as well.  thx

**Comment by zuchka** [comment]
follow up: building grafana from main on my local machine and connecting to a local mysql I did not get your error. Didn't set up SSL but got an expected error when `ssl_mode = true` that I failed to set up a CA cert. With `ssl_mode = false` it configures normally...

wondering if this has to do with DO's hosted MySQL offering...

**Comment by SunSparc** [comment]
When I put it in `debug` mode, the logs do not even get far enough to show debug information.
```
logger=settings t=2023-01-25T22:33:02.791684538Z level=info msg="Starting Grafana" version=9.3.1 commit=89b365f8b1 branch=HEAD compiled=2022-12-01T12:45:45Z
logger=settings t=2023-01-25T22:33:02.792185417Z level=info msg="Config loaded from" file=/local/grafana/conf/defaults.ini
logger=settings t=2023-01-25T22:33:02.792333663Z level=info msg="Config loaded from" file=/grafana.ini
logger=settings t=2023-01-25T22:33:02.792420246Z level=info msg="Path Home" path=/local/grafana
logger=settings t=2023-01-25T22:33:02.792456521Z level=info msg="Path Data" path=/local/data
logger=settings t=2023-01-25T22:33:02.792486215Z level=info msg="Path Logs" path=/local/grafana/data/log
logger=settings t=2023-01-25T22:33:02.792534276Z level=info msg="Path Plugins" path=/local/grafana/data/plugins
logger=settings t=2023-01-25T22:33:02.792576152Z level=info msg="Path Provisioning" path=/local/grafana/conf/provisioning
logger=settings t=2023-01-25T22:33:02.7926058Z level=info msg="App mode production"
logger=sqlstore t=2023-01-25T22:33:02.792866952Z level=info msg="Connecting to DB" dbtype=mysql

Failed to start grafana. error: failed to connect to database: invalid value / unknown config name: custom
failed to connect to database: invalid value / unknown config name: custom
```

When I comment out `ssl_mode`, I do get plenty of debug messages.

> "wondering if this has to do with DO's hosted MySQL offering..."

That is certainly possible. I was previously using a Percona XtraDB Cluster (Galera MySQL), using the same config file and it worked just fine.
