### ISSUE TITLE
Grafana Timezone convertion

### ISSUE THREAD

**Issue by darkmatter18** [grafana/grafana#61903]
![Group 1](https://user-images.githubusercontent.com/30409045/213965625-1ef96d44-12c4-4616-ae5d-7ff1d0260866.png)

I have data here that has a column named `start_timestamp`. The value is properly recognized by Grafana as Time. 

The issue is that `start_timestamp` is in GMT, but while showing the data in the chart, I want to show it in Local Time.
So is there any way in Grafana to convert the time zone of data before showing it to the user?

N.B: I am using Loki and Promtail as the data source.

**Comment by zuchka** [comment]
Thanks for creating this issue, @darkmatter18 

Our [community forum](https://community.grafana.com) is probably the best place to ask folks for solutions to problems like this. Off the top of my head I can think of two hacks, but both are just that--hacks:

Explore ways that you can manipulate table data using [transformations](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/). If you could change the time data type to a number it may (or may not) get refigured as a UNIX timestamp, which you could then perform maths on and then transform back into a time data.

Another potential hack would be to manipulate the data in that field using [the Value Mapping by regex feature](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-value-mappings/#map-a-regular-expression). But I believe for that you would also have to change the data type from time to string or number.
