### ISSUE TITLE
Alerting: Database migration failed due to slack alarm

### ISSUE THREAD

**Issue by Bowriverstudio** [grafana/grafana#61900]
**What happened**:

Database migration failed upgrading from Grafana 8.3 to 9.3.2

**What you expected to happen**:

Migration to work.

**How to reproduce it (as minimally and precisely as possible)**:

The Error log has this message:

 using the Slack chat API"
logger=migrator t=2023-01-22T23:17:01.264431306Z level=error msg="Exec failed" error="failed to validate AlertmanagerConfig in orgId 1: failed to validate receiver \"Alert Slack\" of type \"slack\": recipient must be specified when using the Slack chat API" sql="code migration"

Database has 
```sql
SELECT * FROM alert_notification;
1|1|Alert Slack|slack|{"addresses":"","autoResolve":true,"httpMethod":"POST","severity":"critical","uploadImage":false}|2021-06-30 19:06:56|2021-06-30 19:06:56|0|0|0|0|JxfOj1k7z|{}
```

**Anything else we need to know?**:
I updated the slack notification to an email one, then the migration worked. (ID 2 has email type alarm)

```sql
UPDATE alert_notification
SET
    type = (SELECT type FROM alert_notification WHERE id = 2),
    settings = (SELECT settings FROM alert_notification WHERE id = 2)
WHERE id = 1;
```

**Comment by zuchka** [comment]
Thanks for creating this issue, @Bowriverstudio 

so are you technically unblocked on this issue? alerting migrations can get a little wonky in the versions where we transitioned from the legacy alerting platform to the new unified alerting platform...

**Comment by Bowriverstudio** [comment]
Thank you for the response @zuchka 

We are unblocked by this issue.  I just wrote it here incase you wanted to test an edge case or it might help someone else.
