### ISSUE TITLE
Feature request: A 'formatted' Unit type for numbers (1,234,567)

### ISSUE THREAD

**Issue by vadimzak** [grafana/grafana#6193]
- **I'm submitting a ...**
- [X] Feature request
  (http://grafana.org/support/)

It would be great to have an additional Unit type that can display large unit-less numbers in a precise and readable way.

Say I want to display the number of page requests in the following way: 1,234,567
(Unit 'none' will display it as 1234567, which is not very readable, and Unit 'short' will display it as 1m which is not precise)

Maybe call it 'formatted'?

**Comment by karpada** [comment]
"thousands separator" 👍

**Comment by schneyra** [comment]
I'm heavily +1'ing this. Separators (language-dependend) would be great!

**Comment by macnibblet** [comment]
This would be awesome.

**Comment by ssnkhan** [comment]
+1 for this please, would love a thousand separator option.
