### ISSUE TITLE
GH Actions: GH slash command `/duplicate` not adding bot/duplicate label

### ISSUE THREAD

**Issue by tonypowa** [grafana/grafana#61942]
**What happened**:

when adding the comment command `/duplciate of #<issue number>` the grafana bot added `type/duplicate` label

**What you expected to happen**:

instead, the bot should add the  `bot/duplicate` label, which would close the issue automatically. 

Reference: #61700

**Comment by zuchka** [comment]
@tonypowa let's pair on this later this week and see if we can adjust the slash commands to trigger the bot 👍
