### ISSUE TITLE
Change references to DataQuery and DataSourceRef

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#61946]
As of #61192, the exported types from `packages/grafana-data/src/types/query.ts` were deprecated in favor of using types from grafana/schema ([src](https://github.com/grafana/grafana/pull/61192/files#diff-2c9e457cb87628517f9e0606e5d774027ff002171070b0d561de1a178bf26e15))

In the `public/app/features/explore` directory, where ever `DataQuery` and `DataSourceRef` are imported from `@grafana/data` - they should be changed to be imported from `@grafana/schema`

For pointing, we use these types extensively in Explore (79 times in 19 files for DataQuery and 9 results in 4 files for DataSourceRef)

**Comment by gelicia** [comment]
Asked when the deprecated types will be removed [here](https://github.com/grafana/grafana/pull/61192#issuecomment-1400764925) but am guessing this is not urgent and can be medium to low priority.

**Comment by gelicia** [comment]
Okay, given the answer I'd recommend a medium priority - it should be as easy as changing the import.

**Comment by Mayuresh0072** [comment]
Hey , Can u please explain the issue and assign me the issue. Thanks.

**Comment by aashish0909** [comment]
Hi, I would like to do this but I didn't understand the issue properly. 
Could you explain it and assign the issue to me.
Thank you!

**Comment by gelicia** [comment]
@Mayuresh0072 @aashish0909 - I have edited the description to be more clear on what we're looking for. If you understand the description, feel free to assign it to yourself.

**Comment by aashish0909** [comment]
@gelicia I have made the changes. 
I saw that there are some guidelines for commit messages and pull requests. 
What's the area of this issue?

**Comment by aashish0909** [comment]
hey @gelicia, when I am trying to run yarn test, this is showing up.
![image](https://user-images.githubusercontent.com/56581495/214385742-abc2b881-fa96-4e15-a93d-e508850dd747.png)

**Comment by gelicia** [comment]
@aashish0909 I don't know what to tell you - that does not happen on my environment running `yarn test` nor is it something someone has reported in this repo. I would suggest you rebase, clear any caches you may have, and double check our [developer guide](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md) to be sure your environment is set up correctly for working on Grafana. Checking to see what solutions others have for that error may also help.

**Comment by aashish0909** [comment]
> _Post was in response to a deleted comment about the front end test suite not running_
> 
> @aashish0909 I don't know what to tell you - that does not happen on my environment running `yarn test` nor is it something someone has reported in this repo. I would suggest you rebase with `main`, clear any caches you may have, and double check our [developer guide](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md) to be sure your environment is set up correctly for working on Grafana. Checking to see what solutions others have for that error may also help.

yeah it was gone after rebase with main
that's why deleted it
