### ISSUE TITLE
Loki: What log context query should loki produce

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#61973]
### Summary

Research how our users use Loki query and  re-revaluate what query should Loki produce as a context query.

### Problem statement
There is a lot of discussion about what should be the log context query. Currently, a lot of users think that the context query they are running is different from what it actually is. Moreover, some users would like to still keep some/all of the pipe operations that are present in original query. 

### Scope
Research

### Solution

This will be a research project to learn more about how our users use log context and document it. Moreover, based on findings, we should re-revaluate what query should Loki produce for users. And lastly, should this be configurable, if users are using context for different things. 

### Resources

https://github.com/grafana/grafana/discussions/45685

**Comment by stevendungan** [comment]
Making sure to add Dialpad's feedback to the mix, that they'd like to preserve line formatting in the Show Context query as well: https://docs.google.com/document/d/1qfvQdQSg36b1-nhqXw2dGpnoPmgmkXSRM7NiGfQsC50/edit?usp=sharing

**Comment by ivanahuckova** [comment]
Resolved by:

- bringing transparency do loki context query (seeing what query is executed) https://github.com/grafana/grafana/pull/67131
- adding a way to widen/narrow down search https://github.com/grafana/grafana/pull/67131
- possibility to jump to split view to edit query even more https://github.com/grafana/grafana/pull/66777
