### ISSUE TITLE
[Feature Request] Third metric set shown at X axis

### ISSUE THREAD

**Issue by isj4** [grafana/grafana#6199]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It would be useful to show a third set of binary metrics at the bottom of a graph below the normal X axis.

Concrete example: I have a building automation graph for rom showing power use (watts) on Y1, and temperature on Y2. The third metric set that would be useful to have shown is the occupancy. I have that metric (binary 0/1). Image attached of what I'm thinking of:
![third_metric_set](https://cloud.githubusercontent.com/assets/12530623/19123548/55dd6060-8b2f-11e6-8be0-8f4e4e2ea3ff.png)

Such third metric sets would necessarily be shown as binary (graphs/curves don't make much sense).

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/2615
