### ISSUE TITLE
singlestat issue displaying template variable on multi-select

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#6200]
bug report

using 3.1.1

I have run across an issue with repeating singlestat panels concerning template variables. When I use a multi-selected $var in the title just the single value for that variable is printed for that panel instance, as would be expected.

However, when I try to use the same variable in the prefix of the singlestat value, it displays _all_ of the multi-selected values for that variable.

**Comment by bergquist** [comment]
I cannot reproduce this i 4.0.0

http://play.grafana.org/dashboard/db/issue-6200?var-device=desktop&var-device=mobile&var-device=tablet
