### ISSUE TITLE
Memory leaking with panel inspect function

### ISSUE THREAD

**Issue by Nameless80** [grafana/grafana#62005]
**What happened**: I query a big number of data on a dashboard it has 4 x panels with 8 pens on each panel, and I noticed the panel inspect function never release the memory back to the host it caused the memory leak and the browser is crashing

**What you expected to happen**: Panel inspect should release after exiting the function.

**How to reproduce it (as minimally and precisely as possible)**: set the Max data point to 197486, Absolute time range to 7-days.  Mainly we are building a Grafana dashboard + InfluxDB to show 7-day raw data in a 2-second sample rate. The worst-case test is running 4 panels with 8 pens on a single dashboard with approximately 7 days of raw data (2-3 sec). In this scenario, each panel handles 1428480-2101520 data. It happens when the panel inspects function repeats to be called, the browser’s memory will keep increasing by more than 5GB then the browser will crash.

**Anything else we need to know?**: swapping the pen on the "show data frame" will cause the same issue, see the pic below.
![Grafana-Panel Inspect-memory leak](https://user-images.githubusercontent.com/81415653/214332961-5c480bc7-a1e9-41ef-bf74-ffe87081f478.png)

**Environment**:
- Grafana version: v9.3.2 (21c1d14e91) (Docker) on server
- Data source type & version: InfluxDB v2.6.1 (Docker) on server 
- OS Grafana is installed on: Server - Windows server 2022 (Docker Desktop) (CPU: Xeon E2378G RAM: 16GB)
- User OS & Browser: Microsoft Edge on Client - Windows 11 Pro (CPU: i7-12700T RAM: 16GB)
- Grafana plugins: Renderer (Docker)
- Others:

**Comment by zuchka** [comment]
what panel visualizations are you using? Are you performing any transformations on the data?

**Comment by Nameless80** [comment]
> what panel visualizations are you using? Are you performing any transformations on the data?
Time series panel.



> what panel visualizations are you using? Are you performing any transformations on the data?
 No transformations on the data.

Additional information: The max data point setting is show in the following pic.
![image](https://user-images.githubusercontent.com/81415653/214666876-e990e505-d341-4349-b958-5165b2c3df78.png)

query: 
from(bucket: "Process")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["PlantId"] == "M_PETM_A1207AX1_TOT" or r["PlantId"] == "M_PETM_A1301AX1_TOT" or r["PlantId"] == "M_PETW_A2406AX1_TOT" or r["PlantId"] == "M_PETW_A2Imp_TOT" or r["PlantId"] == "M_HDM_B1139AX1_TOT" or r["PlantId"] == "M_HDM_B1149AX1_TOT" or r["PlantId"] == "M_HNW_B2406AX1_TOT" or r["PlantId"] == "M_HNW_B2Imp_TOT" )
  |> filter(fn: (r) => r["_field"] == "DatVal")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> keep(columns: ["_time", "_value", "PlantId"])
  |> yield(name: "mean")

**Comment by Nameless80** [comment]
Use case:

1. Our system holds 2 years of data where many data values will have time stamps that reflect periods of time where the acquisition rate is every 2 seconds.
2. To simplify our system we have developed dashboards where the display period can be varied from minutes to years.
3. Additionally, some of data will be transient (fleeting spikes) which the raw data should capture, but any aggregated results may smooth. i.e. max and max calcs for raw data vs min and max for aggregated data may be different. The main use case for min and max is up to 1 week and ideally the data used within this time frame is either raw or aggregated with a time interval no more than 2 seconds.
5. The max data point value was increased so that for a queries with 8 data values for 1 week did NOT result in a time interval >2sec.

Observation:
1. The query executes OK
2. The "inspect" of the query works OK (first instance)
3. The "inspect" of the query if repeated whilst the browser session is still active will ultimately lock the Thin Client
4. Monitoring of the Thin Client memory use suggested that there was a memory step increase each time "inspect" was run
5. The memory was only released if the browser was restarted or refreshed. 
6. Regardless of the size of the data the application should manage the resources correctly or gracefully fail (e.g. error message).

**Comment by leeoniya** [comment]
> i.e. max and max calcs for raw data vs min and max for aggregated data may be different

i'm not suggesting that you do min and max from aggregated data. there are numerous algorithms that can do downsampling without losing transients. take a look at the first plot here: https://leeoniya.github.io/uPlot/bench/uPlot-10M.html. this uses min/max decimation [1], so even transient spikes are visible after the raw data is downsampled from 2M to 2K points.

there are additional alternatives for massive downsampling  such as LTTB [2] and [Douglas-Peucker](http://en.wikipedia.org/wiki/Ramer-Douglas-Peucker_algorithm) and Radial Distance [3].

it could be interesting to implement something like these in the grafana backend so the raw data does not need to hit the UI. can you zip and attach some of these data series you're talking about so i can experiment a bit (just the 200k timestamp/value pairs). CSV or JSON would be fine. you can also do this with out debug snapshot feature: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

![image](https://user-images.githubusercontent.com/43234/200391751-ca1c338a-460b-46de-b881-87ea81e55f5d.png)

that being said...

> The "inspect" of the query works OK (first instance)

we should add a warning before loading this much data into the inspect panel and see where the leak is occuring, so your data will be helpful in figuring this out as well.

[1] https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019YLKSA2&l=en-US
[2] https://github.com/ggalmazor/lt_downsampling_java8
[3] https://mourner.github.io/simplify-js/

**Comment by Nameless80** [comment]
Hi,

The data is confidential.
How do I send the data but not disclose it to public?

Thanks.

**Comment by leeoniya** [comment]
ok, this is what i'm seeing (not terribly useful at full zoom-out, if i'm being honest):

![image](https://user-images.githubusercontent.com/43234/216211763-f0c32a4f-fc0b-4e9f-9239-2b8227756f7a.png)

to make this thing much more usable, switch to Linear instead of Smooth interpolation. it is much faster (does the min-max decimation i mentioned above); Smooth adds nothing to this density of data.

![image](https://user-images.githubusercontent.com/43234/216213854-2e8c372a-1137-4697-9334-68d2757ca6af.png)

the next item in the profile is `joinDataFrames`. we may be able to skip this for situations when all time fields have identical values. EDIT: https://github.com/grafana/grafana/pull/62740 takes this down from 400ms to 17ms for your dataset.

![image](https://user-images.githubusercontent.com/43234/216214787-f41d20ab-3f98-4908-8bf7-cb759e7d36d6.png)

**Comment by leeoniya** [comment]
@kylebrandt suggested trying this strategy for downsampling in the query: https://stackoverflow.com/questions/74473308/influxdb-keep-min-max-values-while-downsampling/74486436#74486436

**Comment by natellium** [comment]
Closing this. There's a related PR here https://github.com/grafana/grafana/pull/62740
