### ISSUE TITLE
ability to suppress dashboard link icon on panel titles

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#6201]
- **I'm submitting a ...**
- [x] Feature request
- What Grafana version are you using?
  3.1.1

I am displaying a large number of repeating singlestat panels via a template variable. These panels contain links to other dashboards. when I add a link in the panel configuration this causes a link icon to be displayed in the title of each and every singlestat panel which, unfortunately causes alignment issues in my case and generally just looks busy. It would be great to have an option to suppress the link icon.

In the interim does anyone have any suggestions on some javascript I could add in a text panel that may suppress these icons?

**Comment by torkelo** [comment]
closing this as the panel link icon was changed in 4.1, it's less intrusive now (in corner and is not taking any space)
