### ISSUE TITLE
Alerting: create and edit message template docs

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#62019]
see:  https://raintank-corp.slack.com/archives/C5PG2JK8W/p1674212292826939?thread_ts=1674211158.195269&cid=C5PG2JK8W

--> it would be helpful if the [description of the templating label "$Values"](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-message-template/#keyvalue) was more detailed. At the moment it is explained more on a separate [page](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#templating-labels-and-annotations) . Maybe we could add a link to it?

see: https://github.com/grafana/grafana/issues/61453

update: https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-message-template/#keyvalue 
It would be great if there were data in json format that alerted the return value of the template. And how to access and use it.

**Comment by grobinson-grafana** [comment]
> it would be helpful if the [description of the templating label "$values"](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-message-template/#keyvalue) was more detailed. At the moment it is explained more on a separate [page](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#templating-labels-and-annotations).

Please note that these are not the same, `$values` in notification templates is different to `$values` when templating custom labels and annotations.

**Comment by brendamuir** [comment]
Here's a link to the new templating docs for 9.4. Have a look here and see if your questions are answered. Let us know if you have any further feedback!
https://grafana.com/docs/grafana/next/alerting/manage-notifications/template-notifications/
