### ISSUE TITLE
feature request: hysteresis for alerts

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6202]
hysteresis is a very fancy word, but basically it means having a different condition to go from state B to A then the condition used to go from A to B.

for example, let's say i have an alert for latency, with a threshold at 1000ms.
if the number is fluctuating around 1000 (maybe 980->1010->990->1020-> etc), then each of those will trigger a change between critical and ok. constantly flapping.

with hysterisis I could say:
- go to critical when it goes over 1000ms
- only go back to normal when it goes under 900ms.

this way it won't flap.

**Comment by kylebrandt** [comment]
Another user story here is rebooting a hardware host.

The host check pings the host, other checks are naturally dependencies on that host being up.

You might want it to alert when it goes down within say a minute. However, hardware machines with lots of memory etc the boot time can take a while. Also pings can work for a couple minutes before the OS comes up.

I've thought of this as asymmetrical alerts. In short, the recovery of something != the inverse condition of it being non-normal.

**Comment by bruceadams** [comment]
Can we have an option to use only `error_level` as the threshold for firing an alert? With this (along the existing behavior where an alert clears once it falls within `warning_level`) the user gets direct control over hysteresis.

When I first tried setting up a new alert in Grafana (earlier this week), I assumed hysteresis was already in place, since there are separate `warning_level` and `error_level` thresholds. What I expected was that a alert would fire when the `error_level` was crossed, but that the notification wouldn't auto-clear until the metric returned to OK, which means the metric moved within `warning_level`. I was quite surprised to have a PagerDuty alert fire when a metric moved outside of `warning_level`.

**Comment by bruceadams** [comment]
Maybe I'm confused here? My starting point was https://console.bluemix.net/docs/services/cloud-monitoring/alerts/rules.html which talks about:

> - _error_level_: Defines the threshold that you set to trigger an error alert.
> - _warning_level_: Defines the threshold that you set to trigger a warning alert.

Looking quickly at the Grafana code, I see neither _error_level_ nor _warning_level_.

**Comment by FX-HAO** [comment]
I've just implemented the feature similar to this. Without nice UI and design though, but it works. 
I developed it from the latest branch (5.0). It's a breaking feature, and grafana is currently being refactored currently. So I have no plan to make a PR.
If anyone wants to give it a try, the repository is https://github.com/FX-HAO/grafana. The easier way to test it: `docker run -it -d fuxin/grafana`.
![image](https://user-images.githubusercontent.com/6838487/37197557-2ef976ac-23b6-11e8-9b85-5aa324bb2dd0.png)

**Comment by haizaar** [comment]
Can someone please clarity that this issue was closed in favor of https://github.com/grafana/grafana/issues/7886? The latter AFAIU delays firing unless an alert spent enough time in alerting state, while this issue talks about being able to define separate thresholds for firing and disarming.

**Comment by bergquist** [comment]
this was closed in favor of another implementation. 

Debouncing alerts should achieve kind of similar end goal of reduced flapping alerts. Debouncing favors slow trigger and quick recovering and this favors the opposite. In which case I strongly prefer slow triggering since that reduce alert noise. Implementing both in Grafana adds to many options.

**Comment by Dieterbe** [comment]
>  this favors the opposite

I don't think this is true, as you can set each state change condition as strict or loose as you like.
(e.g. in the original example, you may just as well trigger alert when 1100ms is breached, and switch back when 1000ms is reached)

that said, I have discussed this with @bergquist and i agree these are similar approaches towards the same goal, and i'm fine with the direction choosen. we will see if there is still a need for hysteresis configuration but I don't think so.

**Comment by bruceadams** [comment]
My goal (which I have implemented by adding a shim outside of Grafana for my alerting) is for resolving an alert to have concrete meaning in the context of my application.

I think of alerting in terms of waking people up. When one of my alerts fires, things are bad enough that human attention is called for. I only want to auto-resolve that alert when things are unambiguously running fine. I want auto-resolve to mean, to the poor, sleepy person I've woken up, that they can go back to sleep without bothering to look any further.

There is often a large gap between: things are broken (the alert threshold) and things are fine (the auto-resolve threshold). Each of those thresholds are things we have documented in our on-call playbooks.

When things are in the warning range, the on-call person is expected to pay attention long enough to make a judgement call: does this need more attention now? Do things look good enough that I can manually resolve this (which re-enables the alert)? When things fall below the warning range (and the alert auto-resolves), no further immediate (middle of the night) human attention is needed.

What I've described here is quite different from debouncing alerts.

**Comment by nicolas17** [comment]
Why is this closed?? I don't see the relation between debouncing and hysteresis. In the original example around 1000ms latency, if the value _quickly_ flaps between 500 and 1500 you may not want to get an alert every time, _that_ is debouncing/delaying. Hysteresis is to prevent any alerts if it flaps between 999 and 1001 no matter how fast or slow it changes. There is no alert delay that would solve that.

**Comment by davidmparrott** [comment]
This may be working/possible with unified alerting. Priority and effort estimates are for investigating next steps.

**Comment by yuri-tceretian** [comment]
@gotjosh I wonder why you reopened the issue. Isn't it something that can be implemented using Math expressions?

**Comment by gotjosh** [comment]
@yuri-tceretian I'm hoping that when we implement a queryable alert state history, we're able to do this via expressions. As an example:

Assuming we want an alert to have `alert if $A > 40 but only resolve if $A < 30`, we could do something like:

```
$A > 40 && ($A > 30 && count(history_query("myalertname")))
```

**Comment by armandgrillet** [comment]
This has been accepted during the last Prometheus dev summit, we might do it in Prometheus first.

**Comment by caroso-de** [comment]
> This has been accepted during the last Prometheus dev summit, we might do it in Prometheus first.

That's great news. This will be a huge improvement, thanks for considering/accepting!

**Comment by yuri-tceretian** [comment]
PR #70998 introduces support hysteresis threshold (an extension of the regular threshold). It does not contain an alerting part (the implementation of the provider of the loaded metrics), which will use the state manager data for getting loaded metrics. Currently, I am working with UX\UI to come up with some simple UI. Questions, concerns, and suggestions are highly appreciated.

**Comment by gillesdemey** [comment]
Can we close this one after implementing https://github.com/grafana/grafana/pull/75189 ?

**Comment by YarekTyshchenko** [comment]
FYI hysteresis was implemented by this ticket https://github.com/grafana/grafana/pull/70998
