### ISSUE TITLE
different thresholds for different wildcard expansions

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6203]
For a query like `stats.*.latency` where the wildcard expans to things like prod-1, prod-2, qa, dev, etc, it would be nice to be able to set thresholds something like:

```
qa: 1000 # literal match
prod-*: 1500 # wildcard match
* : 2000 # everything else / default
```

**Comment by pdf** [comment]
See also: #6557

**Comment by torkelo** [comment]
new field override system will support this (in 7.0)
