### ISSUE TITLE
Grafana Zabbix Plugin (Grafana 3.0.2 - Zabbix 3.0.5) - History very short 

### ISSUE THREAD

**Issue by frankie7** [grafana/grafana#6204]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana 3.0.2 & Zabbix 3.0.5 
- What datasource are you using? Grafana Zabbix Plugin 
- What OS are you running grafana on? Debian 8.1
- What did you do? I installed the Grafana Zabbix Plugin to test my zabbix graphs under Grafana.
 Trends aren't enabled. Using http://x.x.x.x/zabbix/api_jsonrpc.php, direct access.
- What was the expected result? All graphs displayed.
- What happened instead? All graphs displayed but only 2 days history. 

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by bergquist** [comment]
Please open zabbix plugin related issues on https://github.com/alexanderzobnin/grafana-zabbix
