### ISSUE TITLE
Config: the default (commented-out) values in `sample.ini` stray from the default values in `defaults.ini`

### ISSUE THREAD

**Issue by lucastheisen** [grafana/grafana#62042]
**What happened**:

I made a copy of `sample.ini` as `/etc/grafana/grafana.ini`, then looked through all the config options and uncommented those I wanted to customize. If the commented out value was what i wanted I left it alone.  However, in `sample.ini`, you have:

```ini
#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
;data = /var/lib/grafana

# Temporary files in `data` directory older than given duration will be removed
;temp_data_lifetime = 24h

# Directory where grafana can store logs
;logs = /var/log/grafana

# Directory where grafana will automatically scan and look for plugins
;plugins = /var/lib/grafana/plugins
```

but in `defaults.ini` its:

```ini
#################################### Paths ###############################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
data = data

# Temporary files in `data` directory older than given duration will be removed
temp_data_lifetime = 24h

# Directory where grafana can store logs
logs = data/log

# Directory where grafana will automatically scan and look for plugins
plugins = data/plugins
```

The relative paths in `defaults.ini` are getting appended to my `-homepath` so my runtime is definitely not what I expected.

**What you expected to happen**:

I would expect that the commented out values are exactly in line with the defaults. 

**How to reproduce it (as minimally and precisely as possible)**:

 Something like this should be an empty diff:

```bash
diff -u defaults.ini <(sed 's/^;//g' sample.ini)
```

Especially for values that matter:

```bash
(mitre-wsl-rocky9) ltheisen@MM269697-PC ~/egit/grafana-grafana/conf
$ diff -u defaults.ini <(sed 's/^;//g' sample.ini) 2>&1 | grep -A 19 '# Paths #'
-#################################### Paths ###############################
+#################################### Paths ####################################
 [paths]
 # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
-data = data
+data = /var/lib/grafana

 # Temporary files in `data` directory older than given duration will be removed
 temp_data_lifetime = 24h

 # Directory where grafana can store logs
-logs = data/log
+logs = /var/log/grafana

 # Directory where grafana will automatically scan and look for plugins
-plugins = data/plugins
+plugins = /var/lib/grafana/plugins

 # folder that contains provisioning config files that grafana will apply on startup and while running.
 provisioning = conf/provisioning
```

**Anything else we need to know?**:

Nope

**Environment**:
- Grafana version: master branch
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by lucastheisen** [comment]
Also, the instructions to _copy `sample.ini`_ to some other location and customize are only in the Windows section of the install guide, but the seem to be equally applicable to the _tarball_ based install.  There should be some explicit documentation of that nature.

**Comment by mildwonkey** [comment]
I suspect - without proof! - that the values in the `sample.ini` are set to the most commonly overridden values. There's no obligation for the two to be the same, but perhaps we can make a note of that in the documentation. I'll re-label this as a documentation issue - thanks for reporting it, and sorry for any confusion!
