### ISSUE TITLE
Drag & Drop: Change file size from byte to kilobyte

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#62052]
The current implementation shows the max file size (200000) in bytes (see screenshot)
 when a file is dropped into the drop zone. To make it easier on the user this should be changed to kb . In this case 20 kb

![Image](https://user-images.githubusercontent.com/110845248/214469329-c222d9cb-6f45-41b8-a307-940d6e333c4e.png)

**Comment by zoltanbedi** [comment]
Fixed in #62290
