### ISSUE TITLE
bug in alerting "outside range" form validation

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6205]
when i do "alert when outside range 0.9 to 1" i get an on-hover message over 0.9 saying "Please enter a valid value. the two nearest valid values are 0 and 1".

1) i almost didn't see this message. it only shows when you happen to hover over the field.  maybe this should be a more clear validation error that marks the field in red and refuses to save the form. 

2) why am i not allowed to use 0.9 in the first place ?

**Comment by torkelo** [comment]
1) where is this hover message?

2) Not sure, not seeing any error message when I try the same range. What browser are you using?

**Comment by Dieterbe** [comment]
i can trigger it on the from and to fields by just putting a float in either or both.
i can reproduce in both chromium and firefox
couldn't take a screenie so here's a pic
![20161010_184639](https://cloud.githubusercontent.com/assets/20774/19242168/b799fdb0-8f1a-11e6-8628-41c2f253e2e0.jpg)

**Comment by torkelo** [comment]
strange, do not get that warning in chrome nor in firefox. But did google it and adding step="any" to input element should fix it
