### ISSUE TITLE
TypeError: _.all is not a function

### ISSUE THREAD

**Issue by julien591** [grafana/grafana#6206]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v4.0.0-pre1 (commit: v3.1.0-1016-gdacfa6b)

- What datasource are you using?
OpenTSDB 2.2.1

- What OS are you running grafana on?
CentOS 7

- What did you do?
Trying to create a new graph panel in dashboard with OpenTSDB's metrics. Got an error instead

- What was the expected result?
Metrics displayed in the graph

- What happened instead?
An empty graph with a red warning "_.all is not a function"

Also, everything was fine 2 days ago, the metrics were correctly displayed and all. But today I updated ("go get ...") Grafana and it's not working anymore, even with a "fresh install" (go run build.go build, etc...).
I tried on OpenTSDB, it retrieved all the points and plotted them successfully.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
Here is the exact error:
![sans titre](https://cloud.githubusercontent.com/assets/16303180/19155535/18c9403a-8bdf-11e6-97be-8c27a924cd47.png)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
![2](https://cloud.githubusercontent.com/assets/16303180/19156305/b604d416-8be1-11e6-8117-f6d6ce66f61c.png)
Just for information, the two first "Failed" errors have always been there, even though it worked fine before today

Thanks in advance

**Comment by alexanderzobnin** [comment]
Seems, it's bug in OpenTSDB datasource introduced by last lodash upgrade.
