### ISSUE TITLE
Change name result in templating

### ISSUE THREAD

**Issue by MrZabGraf** [grafana/grafana#6207]
Hi,

Im using grafana 3.0.1 with zabbix datasource on linux ubuntu.
I have a template on my main dashboard and a regex to trap only linux serveurs (Regex : /^Linux/).
The problem is i want change the value which appears and i want translate them.

ex list of my servers who appears when i click on the template button : 

site.server1_usa_newyork
site.server2_france_paris

i want translate the value "site.server1_usa_newyork" in "usa newyork" for exemple

is it possible ? 

ty for help !!

regards.

**Comment by torkelo** [comment]
no this is not possible, there are a couple of similar feature requests already open, will close this
