### ISSUE TITLE
source code not available: one of auth,cloud_api_key,oncall_access_token,sm_access_token must be specified

### ISSUE THREAD

**Issue by aydinsahin** [grafana/grafana#62096]
I want to create a grafana_rule_group resource as decribed in the official documentation: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/rule_group)

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = ">= 1.34.0"
    }
  }
}

When I run apply, I got this error. auth is working fine defined in provider "grafana"  when I create dashboard resources from json files.

│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/grafana/grafana" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/grafana/grafana"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ "auth": one of `auth,cloud_api_key,oncall_access_token,sm_access_token`
│ must be specified
╵

- Grafana version: 9.3.2

**Comment by zuchka** [comment]
please share your full HCL config file for your deployment and provide steps for reproduction. thank you!

**Comment by ramaro** [comment]
Hi am experiencing exactly the same problem using Grafana Oncall (cloud).

### Provider version 
1.34.0

### Terraform excerpts

provider tf:
```tf
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "1.34.0"
    }
  }
}

provider "grafana" {
        alias = "cloud"
        cloud_api_key = "MYCLOUDKEY"
 }
provider "grafana" {
        alias = "oncall"
        oncall_access_token = "MYONCALLKEY"
  }
```

teams data tf:
```tf 
data "grafana_oncall_team" "team1" {
        name = "team1"
 }
data  "grafana_oncall_user" "user1" {
        username = "user1"
}
```
### Terraform plan failure
```
$ terraform plan
Error: Invalid provider configuration

Provider "registry.terraform.io/grafana/grafana" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider documentation.



Error: Missing required argument

  with provider["registry.terraform.io/grafana/grafana"],
  on <empty> line 0:
  (source code not available)

"auth": one of `auth,cloud_api_key,oncall_access_token,sm_access_token` must be specified
```

### Terraform plan success
However, if I explicitly set `GRAFANA_ONCALL_TOKEN`env var to the same value of `oncall_access_token`, it works (whether I removed `oncall_access_token` from the code or not):

```
GRAFANA_ONCALL_ACCESS_TOKEN="TOKENVALUEHERE" terraform plan
<expected terraform plan output>
```

**Comment by aydinsahin** [comment]
Hi,
Here are the script I use:
`terraform {
  required_version = ">= 1.0.0"

  backend "***" {
    bucket  = "state"
    prefix  = "terraform/state"
  }

  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = ">= 1.34.0"
    }

    vault = {
      source  = "hashicorp/vault"
      version = "2.23.0"
    }
  }
}

variable "grafana_url" {
  type        = string
  description = "Grafana URL"
  default     = "https://***/"
}

locals {
  username = "***"
  password = "***"
  grafana_admin       = ["***"]
  grafana_auth        = format("%s:%s", local.username, local.password)
}

resource "grafana_organization" "org" {
  provider = grafana.base
  name     = "org"
  admins   = "***"
  viewers  = "***"
}

provider "grafana" {
  alias  = "base"
  url    = var.grafana_url
  auth   = local.grafana_auth
  org_id = grafana_organization.org.org_id
}

resource "grafana_folder" "global_alerts" {
  provider = grafana.base
  title = "Global Alerts"
}

resource "grafana_data_source" "datasource" {
  provider = grafana.base
  type     = "prometheus"
  name     = "metrics"
  url      = "https://***" //grafana url

  basic_auth_enabled  = true
  basic_auth_username = local.username
  basic_auth_password = local.password

  json_data {
    http_method = "GET"
  }
}

resource "grafana_rule_group" "test_rule" {

  name             = "test"
  folder_uid       = grafana_folder.global_alerts.uid
  interval_seconds = 60
  org_id           = grafana_organization.org.org_id


  rule {
    name           = "My Alert Rule 1"
    for            = "2m"
    condition      = "B"
    no_data_state  = "NoData"
    exec_err_state = "Alerting"
    annotations = {
      "a" = "b"
      "c" = "d"
    }
    labels = {
      "e" = "f"
      "g" = "h"
    }
    data {
      ref_id     = "A"
      query_type = ""
      relative_time_range {
        from = 300
        to   = 0
      }
      datasource_uid = grafana_data_source.datasource.uid
      model = jsonencode({
        hide          = false
        intervalMs    = 1000
        maxDataPoints = 43200
        refId         = "A"
        "expr": "probe_success{instance=\"https://***\", job=\"***\"}"
      })
    }
    data {
      ref_id     = "B"
      query_type = ""
      relative_time_range {
        from = 0
        to   = 0
      }
      datasource_uid = "-100"
      model          = <<EOT
{
    "conditions": [
        {
        "evaluator": {
            "params": [
            90
            ],
            "type": "lt"
        },
        "operator": {
            "type": "and"
        },
        "query": {
            "params": [
            "A"
            ]
        },
        "reducer": {
            "params": [],
            "type": "avg"
        }
        }
    ],
    "datasource": {
        "type": "__expr__",
        "uid": "-100"
    },
    "hide": false,
    "intervalMs": 1000,
    "maxDataPoints": 43200,
    "refId": "B",
    "type": "classic_conditions"
}
EOT
    }
  }
}`

**Comment by IgnatiusSY** [comment]
@aydinsahin For me, I had to add it to provider.tf without the alias

**Comment by aydinsahin** [comment]
Thanks for the info @IgnatiusSY . We are using alias to seperate the main provider and organizations, so we need to add it in our situation.
I tried to set GRAFANA_ONCALL_ACCESS_TOKEN as an environment variable as @ramaro described and it works

GRAFANA_ONCALL_ACCESS_TOKEN="TOKENVALUEHERE" terraform plan

I wonder why the username and password is not enough for authentication.

**Comment by aydinsahin** [comment]
Hi, This is resolved by adding the grafana organization provider to grafana_rule_group resource. So if you have different organizations, you need to add the related provider to each resource you create.
