### ISSUE TITLE
Datasource Credentials Available from Admin GUI

### ISSUE THREAD

**Issue by hland** [grafana/grafana#6213]
The Grafana admin GUI makes datasource credentials available from the GUI. This means that anyone with access to the Grafana admin interface will be able to retrieve these credentials, simply by right-clicking on the field in the browser and "inspect" it with developer tools. This is bad security practice because an attacker able to compromise the security of Grafana will then be able to get credentials for all the datasources of Grafana as well. 

My suggestion is to not return the credentials in the ```/api/datasources/:id``` calls, and put some placeholder data in the password field in the GUI instead of real passwords. 

Also, the ```Direct``` mode of communication is a major security pitfall that exposes credentials and there should be an explicit warning for configuring any plugins / datasources this way.

**Comment by torkelo** [comment]
only org admin api/views require org admin privileges. An adin that set's up a data source and specifies direct browser access will have to understand that credentials will be have to be sent from the browser.  

but I agree the password should be write only, and not included in the read operation

**Comment by torkelo** [comment]
oh, here is the dupe https://github.com/grafana/grafana/issues/2557
