### ISSUE TITLE
plugin dashboards: should be clearer if up to date

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6215]
latest master, when going to a plugin such as Worldping, dashboards tab.
it's not quite clear if they are the latest version or not. there's an update button but not sure if i should use it.

**Comment by torkelo** [comment]
Added currently imported revision and if same changed button to "re-import" 

![image](https://cloud.githubusercontent.com/assets/10999/19192765/a1584126-8ca7-11e6-872e-43e156f7489b.png)
