### ISSUE TITLE
Alerting: Grafana logs panic while evaluating rules

### ISSUE THREAD

**Issue by danstadler-pdx** [grafana/grafana#62168]
**What happened**: Prospect is evaluating self-managed Grafana Enterprise. Experiencing thousands of the attached panic log messages per day.

Top of entry as follows; will attach a complete entry.

[panic.txt](https://github.com/grafana/grafana/files/10504880/panic.txt)
logger=ngalert.eval rule_uid=cuV7uxN4z org_id=1 t=2023-01-25T23:55:07.228302767Z level=error msg="alert rule panic" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 929 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw.func1()\n\t/drone/src/pkg/services/ngalert/eval/eval.go:53 +0x86\npanic({0x34a10e0, 0x615dad0})\n\t/usr/local/go/src/runtime/panic.go:884 

**What you expected to happen**: not to see all these panics

**How to reproduce it (as minimally and precisely as possible)**: Prospect has created some basic rules in the UI - other than that, no specific user action seems correlated.

**Anything else we need to know?**:

**Environment**: 5 hosts (GCP hosts n2-highmem-48) running on Linux behind a load balancer with a mysql backend; 
- Grafana version: v9.3.2 (21c1d14e91)
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: assume OSX/Chrome but can confirm
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment]
Go version? What datasource triggers the alert?
see:

- https://github.com/grafana/grafana/issues/47339
- https://community.grafana.com/t/grafana-panic-when-expression-used/62783
- https://github.com/grafana/grafana/pull/59691
- https://github.com/grafana/tempo/issues/1440

**Comment by grahamkenville** [comment]
Data source is Google Cloud Monitoring GMP. 
User OS & Browser: Chrome 109.0.5414.119 on Mac Ventura 13.2 for me
Go version: we're running the enterprise Grafana binary version from apt-get install, so whatever version is bundled? If there's a specific command you'd like me to run please let me know.


On another note, it appears that the panic message is associated with the alert firing with "DatasourceError".  For the particular alert I'm investigating, the alert is set to test once per minute for five minutes, and the DatasourceError alert clears each time after five minutes.  Note that I ended up deleting the original alert which caused us to create this issue, and I created a new alert which is also causing these panics. So it's nothing about the particular instance of the alert definition. Also, we're seeing these DatasourceErrors from a number of different alerts across our dev and production Grafana instances. Our dev and prod are both pointing to GMP backends, although they are in different projects. Our dev and prod Grafana instances are on separate hosts (1 for dev, 5 for prod) using the same OS and similar configurations, and they're in different GCP projects. 

Does the stack trace point to anything obvious such as an empty response from the datasource? I'm wondering if this is an issue on the Grafana or GMP side. 

Thanks,
-Graham

**Comment by yuri-tceretian** [comment]
Removing alerting label because the root cause is in the data source plugin, alerting catches the panic so it does not affect the upstream logic

**Comment by aangelisc** [comment]
Hi @danstadler-pdx,

Thanks for reporting this. I'm unable to replicate the issue with the GCM datasource on the commit referenced in OSS Grafana. We may need some more information for the investigation.

For now is it possible for the user to provide us with the complete alert configuration including the GCM query they're attempting to run. This will aid us in narrowing down the issue. Thanks!

**Comment by aangelisc** [comment]
Closing this as we were unable to reproduce and there's been no response. Please reopen if needed 😊
