### ISSUE TITLE
Alerting: Configurable limit for group size

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#62160]
*What happened**:

Some users use very large groups with potentially thousands of rules, where generally a larger number of smaller groups is preferred - it more closely aligns with user expectations, and is easier for the system to handle without dropping ticks.

**What you expected to happen**:

Grafana should support a configurable limit for the maximum size of a group. This will guide users to create groups that perform better.
Administrators can raise this limit if they want via configuration.

For pre-existing groups that are over the size limit, we can choose to simply leave them as-is, so no existing user data is affected. We can allow these groups to be edited and shrink, but won't allow these groups to go any larger.

**Comment by gotjosh** [comment]
Just to clarify, by the maximum size of a group - we mean the number of rules in a group as opposed to the number of groups a tenant can have.

With that said, there are two limits we need here:

- Number of rules in a group
- Number of groups per tenant

The other thing to think about is how do quotas fit into these requirements - adding a limit and enforcing them via a configuration setting is simple (and probably not what we want as it'd require a restart) so my assumption here is that we'll enforce these limits via quotas but I'm not sure I know enough about to provide more detail at the moment.

**Comment by alexweav** [comment]
Note - rules per tenant already exists, the default is iirc 2000 or 3000. This was created back when we had 1 rule=1 group, so at the time it was also a groups per tenant limit effectively.
