### ISSUE TITLE
grafana safeguard

### ISSUE THREAD

**Issue by MrZabGraf** [grafana/grafana#6216]
Hi,

i want make a full backup for grafana config (dashboard, mysql, config etc) and i want to know if a tool exist to make this operation.

Grafana version : 3.0.1
Datasource : zabbix 3.0
Os : Linux ubuntu

ty for help

regards.

**Comment by torkelo** [comment]
No specific tools for grafana. But I am sure there a ton of backup tools for MySQL, and the grafana.ini config should be easy to backup
