### ISSUE TITLE
Grafana do not show retention-resolution 1h on dashboard when query 90days

### ISSUE THREAD

**Issue by peachwaravich** [grafana/grafana#62183]
Sorry ,In my stack grafana connect to thanos-query thanos-store and thanos-compactor

I want to query data 90days
grafana problem is not show data on thanos-query auto-downsampling 
but show "5m-downsampling" on grafana dashboard
How do I fixed it ? 

**information config**

**thanos-query**
```
--grpc-address 0.0.0.0:29190 
--http-address 0.0.0.0:29090 
--log.level debug --query.replica-label environment
--query.replica-label prometheus_replica 
--store=xxxxx:19191
--store=xxxxx:19190
--web.external-prefix=thanos-query 
--query.auto-downsampling 
--query.instant.default.max_source_resolution=1h
```
**thanos-compactor**
```
--http-address 0.0.0.0:39090 
--log.level debug --data-dir /var/lib/thanos-compactor 
--retention.resolution-raw 7d 
--retention.resolution-5m 20d 
--retention.resolution-1h 90d 
--delete-delay 72h
```

**thanos-store**
```
--log.level debug 
--objstore.config-file /etc/thanos/thanos-store.yml 
--index-cache-size 250MB 
--chunk-pool-size 2GB 
--store.grpc.series-sample-limit 0 
--store.grpc.series-max-concurrency 20
```
**image capture**
== grafana  query 90 days===
![image](https://user-images.githubusercontent.com/36033754/214816592-ba8e48e1-a1b3-4567-9994-25e21d106d77.png)

== thanos query auto downsampling===
![image](https://user-images.githubusercontent.com/36033754/214816834-6d38177b-0a75-487d-9c91-eed8f71b8348.png)

== thanos query 5m downsampling ===
![image](https://user-images.githubusercontent.com/36033754/214816853-02e47f52-01aa-4b86-a56e-d7d7ca716111.png)

if I tried edit "**Max data points = 800** " on query options grafana ,it show auto-down-sampling why ? 
![image](https://user-images.githubusercontent.com/36033754/214817011-5312a081-6720-4962-b0b5-7d55bac4a120.png)

thanks.

**Comment by peachwaravich** [comment]
grafana version 7.5.5

**Comment by zuchka** [comment]
Thanks for creating this issue, @peachwaravich 

> grafana version 7.5.5

we are only fixing in Grafana 8+

please upgrade to the newest version and see if your issue persists.

If so, please include precise steps for reproducing the bug. thank you!

**Comment by peachwaravich** [comment]
> 

Sorry , it that does not work guy. , I tried change version grafana is 9.3.1 but still the same. thank you!
![image](https://user-images.githubusercontent.com/36033754/215992522-2196bac4-61db-44a6-9776-47946a9af2f8.png)

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by peachwaravich** [comment]
Hi @zuchka thanks for solution, now I found a solution
when I’ve access to grafana dashboard (linux exporter template) show windows full screen size , I got a problem , it can’t show data 90 days

before
![image](https://user-images.githubusercontent.com/36033754/218624841-adc41d29-32fc-481e-a136-9658451f3c77.png)


but when resized panel on dashboard , I can see panel 90 days
![image](https://user-images.githubusercontent.com/36033754/218624900-d7ccd567-51a9-4f22-a4f8-9142af75b19b.png)


sorry , Do you have any solve a problem ?

**Comment by garlickim** [comment]
I also have same problem.
