### ISSUE TITLE
Elasticsearch: write article about how to setup elasticsearch + grafana

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#62199]
write an article (blog-post or documention or something else) that gives a detailed, step-by-step guide on how to:
- run elasticsearch database
- load data into elasticsearch database
- configure the elasticsearch datasource to connect to the database
- create a dashboard that queries data from the datasource

**Comment by AkshayAwate** [comment]
@gabor, I'm looking forward to work on this issue. Couple of questions:

- Can i use helm chart to deploy both ES and Grafana  ?
- Where can i share draft version of doc ?

**Comment by gabor** [comment]
hi @AkshayAwate , thanks for the offer! unfortunately, for this blog post we are planning to incorporate features still under development, so it's not possible for outside contributors to work on it, sorry.
