### ISSUE TITLE
location json dashboard

### ISSUE THREAD

**Issue by MrZabGraf** [grafana/grafana#6219]
Hi, im running with grafana 3.0.1 on linux ubuntu and im trying to locate the json file for my dashboard on the  my linux server (i need to saved them and restore them on another server) but cant find them (find, locate etc...)

Can you tell me where i can fin them please ?

ty

regards.

**Comment by torkelo** [comment]
Dashboard are stored in the sqlite or MySQL database (depending on how you configured grafana)

**Comment by MrZabGraf** [comment]
Ok ty , so if i want restore my grafana config, i need the mysql database + exporting all my dashboard too ?

**Comment by torkelo** [comment]
if you have a backup of your grafana database (and grafana.ini), you can restore you grafana server , no export/import needed

**Comment by MrZabGraf** [comment]
ty, for the answer. I have another question,  im using zabbix backend. Is grafana store data from zabbix on it own database, history etc..(here , mysql grafana table) ? Or grafana only read from zabbix source and dont store any informations ?
ty for help :)

**Comment by torkelo** [comment]
Grafana only reads from Zabbix
