### ISSUE TITLE
migrator error="failed to migrate alert"

### ISSUE THREAD

**Issue by Schechev** [grafana/grafana#62190]
**What happened**:
I would like to enable the new alert version
Added
 GF_GF_ALERTING_ENABLED=false
GF_UNIFIED_ALERTING_ENABLED=true
But when restarting the container, I get:
```
lvl=eror msg="Executing migration failed" logger=migrator id="move dashboard alerts to unified alerting" error="failed to migrate alert 10: dashboard with UID  under organisation 1 not found: %!w(<nil>)"
t=2023-01-26T11:26:02+0000 lvl=eror msg="Exec failed" logger=migrator error="failed to migrate alert 10: dashboard with UID  under organisation 1 not found: %!w(<nil>)" sql="code migration"
Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): failed to migrate alert 10: dashboard with UID  under organisation 1 not found: %!w(<nil>)
migration failed (id = move dashboard alerts to unified alerting): failed to migrate alert 10: dashboard with UID  under organisation 1 not found: %!w(<nil>)
```
I tried to install `force_migration=true`, the problem persists
What else can I do?

**Environment**:
- Grafana version:8.3.3
- Data source type & version:
- OS Grafana is installed on:Docker
- User OS & Browser:Chrome
- Grafana plugins: OnCall, grafana-piechart-panel
- Others:DB: SQLite

**Comment by zuchka** [comment]
> GF_GF_ALERTING_ENABLED=false

make sure you aren't adding the GF twice

> move dashboard alerts to unified alerting

how old is this grafana instance? how many alerts do you have? I would also strongly suggest using the newest version of grafana; 9+. The migrations for alerts are an ongoing issue and the migration code is constantly improved

**Comment by Schechev** [comment]
Sorry, the mistakes with `GF_GF_ALERTING_ENABLED=false` only here
Grafana is very old and contains over 2000 alerts
For the test, I removed more than 10 alerts directly from the .db file, and the migration passed. 

But how can I understand, for example` id=10`,  what name of alert is this? 

Thanks for the advice, I'll try to update grafana first
