### ISSUE TITLE
[Feat req]: Elasticsearch date histogram & time zone

### ISSUE THREAD

**Issue by jisaitua** [grafana/grafana#6222]
When using a date histogram aggregation and grouping by some interval (let's say 1 day), elasticsearch always groups by UTC unless you specify the “time_zone” option (see [date histogram aggregation documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html)). Grafana should pass the “time_zone” the dashboard is currently using because otherwise you get incorrect aligned time buckets (in my case the 1 day buckets were incorrectly aligned starting from 21:00 because our time zone is -03:00 and the data is stored in UTC).
This issue was already commented in [#5147](https://github.com/grafana/grafana/issues/5147#issuecomment-234918185) but that ticket was closed, so that's why I'm opening a new one.

Thanks.

My environment: Grafana 3.1.1 - Ubuntu 16.04

**Comment by jisaitua** [comment]
Hi Torkelo,

I already patched grafana locally by adding a time_zone option to "date histogram group by", but I don't know if that's the best approach. For our case, we want to show the same numbers (we are using singlestats) independently from what time zone the user is in when watching the data, so that approach works, but I guess that in most cases the user just want to use the time zone he is in, so for that cases the time_zone option should use what's defined for the dashboard.
What do you think?

**Comment by lerouxt** [comment]
Same issue. I'd consider this a bug and not a feature request.  I can't think of any reason why, when timezone pref is set to 'use browser tz', that histogram buckets should not be aligned on the browser's tz day boundaries.  I'd been banging my head against the wall trying to get "1d" to actually be aligned to what I consider a day.

**Comment by mic159** [comment]
I have also run into this issue now :(

All of the day buckets are offset and data from the same day is weirdly split between two days.
When I was using Kibana, I had no such issues.

**Comment by Swebask** [comment]
I face the same problem, not just for the 1d interval, but also custom interval I define that's greater than  1m.

**Comment by TianLangStudio** [comment]
I face the same problem too, I use grafana4.2.0 ,  I change the panel json config directly , it isn't work

**Comment by TianLangStudio** [comment]
I set interval 1y in  singlestate panel ,  https://github.com/grafana/grafana/issues/5261   but it don't work with other panel

**Comment by dhaners** [comment]
I have also faced this issue and would like to see this fixed. Is there any update on when we can expect to see this added to Grafana?

**Comment by torkelo** [comment]
waiting for PR status :)

**Comment by slooring** [comment]
i have the same problem too

**Comment by achennuru** [comment]
@jisaitua Could you please share your change/work around for this issue?
@torkelo Is there a plan to address this issue any time soon? If no, could you please share any work around for this issue?

I see similar behaviour, between 12 AM and 2 AM everyday, I don't see any data in grafana but Kibana reports this data in the same interval. So looking at the graph kibana shows steady increase but grafana shows saw-tooth graph with no date between 12 AM and 2 AM.

**Comment by torkelo** [comment]
@achennuru Strange, don't see how it relates to timezones. 

You issue sounds more like wanting to set min doc count to 1 on the date histogram?

**Comment by achennuru** [comment]
@torkelo I will test with min doc count tomorrow at the same time but the thing that bums me is why it works perfectly fine outside the 12-2 AM timeframe, it's only between this time range it does not show data.
Note: I am currently running this report in Jerusalem with UTC + 3h timezone.

**Comment by torkelo** [comment]
Maybe data is being written less frequently between 12-2 AM ? So the date histogram interval is too low and if min doc count is 0, then every data point is between null values.

**Comment by jisaitua** [comment]
Hi @achennuru, here is the patch againts v4.2.0 that I'm using: [elastic_timezone_patch](https://gist.github.com/jisaitua/1fc9b151825ce517253a109d8f10f0ad). It adds a field where you can specify which timezone (e.g: -03:00) to use for the elastic aggregation. I should still add an "auto" value, so it takes whatever timezone you have defined for your dashboard.

**Comment by torkelo** [comment]
Can you submit a PR with that patch

**Comment by jisaitua** [comment]
@torkelo Here is my first PR #8395 I hope it's ok.

**Comment by yuankui** [comment]
+1

**Comment by mosyang** [comment]
+1 on Grafana with Elasticsearch date histogram

**Comment by coseyo** [comment]
+1

**Comment by seuf** [comment]
My pull request #9902 fixe this issue. We are using this fix in our grafana version on production since one month.

**Comment by laozhang007** [comment]
+1.I have met this issue in kibana, the solution is add "time_zone" parameter.I really need this feature.

**Comment by seuf** [comment]
Maybe It's time to re-open the #9902 pull requests.

**Comment by vkozyrev** [comment]
+1

**Comment by alanwds** [comment]
+1

**Comment by CaptainVincent** [comment]
> Maybe It's time to re-open the #9902 pull requests.

Hi, @seuf I’m sorry to bother you. I want to merge your patch in local. Could you teach me how to update my grafana service when I modify my local codebase done or point somewhere I can looking for reference? Do I need rebuild my whole grafana (I am not familiar with rebuild grafana flow because I just ran it in docker with version v6.0.0 pre-3). Thanks.

**Comment by seuf** [comment]
> Hi, @seuf I’m sorry to bother you. I want to merge your patch in local. Could you teach me how to update my grafana service when I modify my local codebase done or point somewhere I can looking for reference? Do I need rebuild my whole grafana (I am not familiar with rebuild grafana flow because I just ran it in docker with version v6.0.0 pre-3). Thanks.
Yeah, you have to rebuild Grafana like explained on the Readme : https://github.com/grafana/grafana#building
When it works on your local environment you should be able to build a new Docker image

**Comment by hiephm** [comment]
For now I can work-around by using Offset = -7h (my timezone is UTC+7) and Min doc count: 1 to hide the zero count bucket

**Comment by nadanasser** [comment]
facing the same, using grafana 7.1.5 the offset work around sort it for me,the case was like this the hourly break down give correct figures with timezone, when it comes to days, it is not splitting days as per 0:0 to 0:0 time considering the dashboard timezone

**Comment by D-wenhao** [comment]
> For now I can work-around by using Offset = -7h (my timezone is UTC+7) and Min doc count: 1 to hide the zero count bucket
”offset =- 8h and min doc count : 1“ This method is useful for me at present, the current test is not sure whether there will be other problems
