### ISSUE TITLE
Histogram Visualization (min and max) option does not work

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#62237]
**What happened**:

This issue is opened after multiple community users reported it [[1]](https://community.grafana.com/t/does-min-and-max-standard-options-work-with-histograms/75380) and [[2]](https://community.grafana.com/t/histogram-charts-error-with-x-axis-min-max-values/23549).

The Histogram Visualization does not seem to pick the values from the min and max option

**What you expected to happen**:

While using the Histogram Visual panel, and setting an option for Min and Max from inside the Standard Option seems to have no effect.

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/69509548/214879043-876c8add-d3af-40fd-a26c-4bb9385c7e95.png)
![image](https://user-images.githubusercontent.com/69509548/214879075-fb954bf7-612b-478b-a23c-14c48e0d5ed8.png)

**Anything else we need to know?**:

Not 100% sure if this is a known issue, but the closest match I found is this similar issue:(https://github.com/grafana/grafana/discussions/58503#discussioncomment-4737854)

**Environment**:
- Grafana version: 8.5.10 and 9.2.3 
- Data source type & version: Any
- OS Grafana is installed on: Linux OS
- User OS & Browser: Any

**Comment by SEngelnkemper** [comment]
thanks for reporting! please let me know if you need any further info! 

cheers!
