### ISSUE TITLE
Elasticsearch hostname template issues with fqdn.

### ISSUE THREAD

**Issue by robertmbaker** [grafana/grafana#6224]
- What Grafana version are you using?

3.1.1
- What datasource are you using?

elasticsearch
- What OS are you running grafana on?

ubuntu 14.04
- What did you do?

Setup elasticsearch backend with data loaded from zabbix via a zabbix-relay instance. (https://github.com/jojohappy/zabbix-relay)
- What was the expected result?

Properly templated hostnames.
- What happened instead?

FQDN hostnames were broken up into pieces.

Given entries in the elasticsearch database like the following:
{
  "_index":"zabbix.archive-2016.10.09",
  "_type":"zabbix.archive",
  "_id":"19239fbe5c54a53882ff74aaf1c855e1a0b66665",
  "_score":1.0,
  "_source":
  {
    "@timestamp":"2016-10-09T14:00:00+00:00",
    "host":"core1.test.network.com",
    "item":"Temperature value of module 2 inlet temperature",
    "key":"ciscoEnvMonTemperatureStatusValue[module 2 inlet temperature]",
    "app":"System","min":27,"max":28,"avg":27
  }
}

I expect to be able to use templating to snag the FQDNs from the records. When I try using the following:

 {"find": "terms", "field": "host"}

My previewed results are as follows given my data:
core1
core2
test.network
network.com

And so on. It appears that the hostnames are not being parsed correctly by the plugin. Am I doing something wrong?

**Comment by torkelo** [comment]
This is how elasticsearch processes terms query on analyzed fields, update you ES index mapping and set field to non_analyzed
