### ISSUE TITLE
[Bug] Three new bugs - GUI and e-mail alerting notifications

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6225]
I'm submiting 3 new bugs exisiting in all recent builds (4.0.0-1476122502pre1 already checked):
1. Drilldown/detail link icon disappears from the panel title after dashboard refresh. However links are properly saved and visible at General tab.
2. Graph panel **Edit** options are only accessible from the main Dashboard page. It's not possible to get there by clicking **View** and then **Edit** on a selected Graph.
~~3. Alerting e-mail notification is always sent even when Webhook notification is only selected at the Graph panel **Alert > Notifications** page. E-mail notification has "**Send on all alerts**" disabled.~~

Regards

**Comment by bergquist** [comment]
Creating new issue for 3. https://github.com/grafana/grafana/issues/6228

**Comment by torkelo** [comment]
can take a look at 1) & 2)

**Comment by torkelo** [comment]
thanks for reporting this!
