### ISSUE TITLE
SSE: Adding Expression adds empty row instead of expression

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#62259]
**What happened**:
Expression is missing contents when adding an expression to a dashboard:

![image](https://user-images.githubusercontent.com/1692624/214918584-e99b082f-f9f4-4371-adbb-399ebb4af43b.png)

**What you expected to happen**:

Expression operation dropdown (as seen in previous commit):

![image](https://user-images.githubusercontent.com/1692624/214919320-f47759c3-5eac-4152-b059-f5f6fd4b4541.png)

**How to reproduce it (as minimally and precisely as possible)**:

New Dashboard, Add Panel, Add expression 

**Anything else we need to know?**:

Seems to have been introduced in https://github.com/grafana/grafana/pull/61927 based on my bisect -- 9f7ddf1f0b5234a1fd82e1f92d1444f81a794e45

**Comment by itsmylife** [comment]
When I replace this part https://github.com/grafana/grafana/blob/main/public/app/features/expressions/ExpressionDatasource.ts#L71
with
```
uid: '__expr__',
```
as suggested in the comment (https://github.com/grafana/grafana/blob/main/public/app/features/expressions/ExpressionDatasource.ts#L63-L67) it works. But I am not sure if that is the solution or not.

**Comment by jirgais** [comment]
I have this too as of version 9.3.6. In my case, I only get an empty row when I try to edit an existing expression (or add a new one).

![Screenshot from 2023-01-28 11-24-51](https://user-images.githubusercontent.com/9783959/215261640-78dac078-76c7-4ced-b51b-a8e360aabf52.png)

**Comment by JFP-SG** [comment]
Hello,

same behaviour on official Docker Grafana Alpine Image with Version 9.3.6 tested today.
Server throws Error 500:
![image](https://user-images.githubusercontent.com/87066890/215508064-6c37a047-7194-4ab7-85df-350900fa7103.png)

This happens on new and existing panels as shown by @kylebrandt.

Is there a quick workaround, eg. editing JSON?

**Comment by itsmylife** [comment]
> editing JSON?

There is no quick workaround I think. But you can try to change the expressions uid from `-100` to `__expr__`
This will be resolved in the next release.

**Comment by Vimao** [comment]
FYI this is still broken in 9.4.0-beta1, i assume it will be fixed with full release?

**Comment by perplexityjeff** [comment]
Is there any information when this is fixed maybe something of an ETA or an indication of when we can expect the update?
