### ISSUE TITLE
Remove onDatasourceChange from QueryEditorRows

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#62261]
As part of the Mixed Datasource PR, we added an override function to handle when a datasource changes. ([src](https://github.com/grafana/grafana/commit/38c1f3d054ef7ea1a86b41437004fdbe72505e3e)). A concern was noted that this could create bugs.

Remove this override function and use existing `onQueriesChange` function to do what we need.

This logic was added to handle the following scenario, so we will want to ensure this still works as expected
1. Have loki ds, two different queries
2. Change to prom ds, queries both convert
3. change to loki ds, queries both convert. queries can be imported back and forth from prometheus and loki
4. Change to mixed ds, show two prometheus queries
5. Change top query to loki, it does not convert

**Comment by ifrost** [comment]
Looks like we have two solutions for the same problem. #62271 is more performant and #62172 has cleaner API (also includes theoretical use case if multiple rows changed just the data source, though it's not used in practice).

I've tested both using test scenario provided by @gelicia and played with it a bit. Both PRs seem to produce the same result but @gelicia please have a look at #62172 as you may have more context to check if something's not missing.

Personally I'd opt for simpler API in this case (#62172) if it solves the problem.
