### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by madhur** [grafana/grafana#6227]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
**Grafana v4.0.0-pre1 (commit: 63caedb)**
- What datasource are you using?
**InfluxDb**
- What OS are you running grafana on?
**CentOS 7**
- What did you do?
**Setup Alerting**
- What was the expected result?
**Alert successfully created**
- What happened instead?
**Error message came " The datasource does not support alerting queries"**

Is InfluxDB not supported for creating alerting queries?

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/commit/63caedb0946afe4422a6cab5d59cb36f31711e71 is 13 days old. Please download the nightly build for influxdb support. http://grafana.org/builds/

**Comment by madhur** [comment]
👍

**Comment by chaitu4418** [comment]
Hi @madhur, Did you get the alerting working for InfluxDB with the latest build of Grafana. For me i get the same error "The datasource does not support alerting queries"
