### ISSUE TITLE
BarChart: cannot hide first field in tooltip

### ISSUE THREAD

**Issue by yvanarnaud** [grafana/grafana#62298]
**What happened**:
Hiding the first field in tooltip returned by a query is not possible anymore (worked in 9.3.1). Hiding other fields is working as expected.

**What you expected to happen**:
First field should be hidden in tooltip like other fields.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dummy query with several fields
- override first field name and choose to hide it in tooltip: does not work
- override other field name and chosse to hide it in tooltip: it works
- reorganise the fields in the query and check again: same behaviour

**Anything else we need to know?**:
It worked in grafana 9.3.1

**Environment**:
- Grafana version: 9.3.2/9.3.4/9.3.6
- Data source type & version: MySQL (MariaDB)
- OS Grafana is installed on: official grafana docker container
- User OS & Browser: MacOS 13.x/Firefox 109
- Grafana plugins:
- Others:

**Comment by yvanarnaud** [comment]
Here is a query example:
```mysql
SELECT
  1 as "time_range",
   "app1" as "app",
  3 as "nb"
UNION
SELECT 
  2 as "time_range",
  "app2" as "app",
  2 as "nb"
UNION
SELECT 
  1 as "time_range",
  "app2" as "app",
  1 as "nb"
GROUP BY app, time_range
ORDER BY time_range
```
Then I add a "Transform": "Grouping to matrix"
- column: "app"
- row: "time_range"
- cell value: "nb"

Tooltip mode is "all".

X axis is "time_range\app".

Then I add an override for the field name "time_range\app", add "series > Hide in area" and select "Tooltip".

I expect "time_range\app" to not appear in the tooltip but it appears. 

![Bildschirm­foto 2023-01-30 um 09 35 31](https://user-images.githubusercontent.com/16800649/215427279-c7c1dcad-93fc-4799-906c-92e534a1c279.png)


In the version 9.3.1 it disappears as expected.

**Comment by zuchka** [comment]
Thanks for creating this issue, @yvanarnaud 

reproduced here on 9.3.6:

https://play.grafana.org/d/zDbr4n04z/62298?orgId=1

**Comment by yvanarnaud** [comment]
Hi, it is still there on 9.4.3.

Please let me know if there is anything I can do to help fix this issue.

**Comment by drew08t** [comment]
I am able to replicate this, looking into it!
