### ISSUE TITLE
Alerting: Influxdb non_negative_derivative problem?

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#6231]
* **I'm submitting a ...**
- [ ] Bug report

Grafana v4.0.0-pre1 (commit: 6b16fce)
Influxdb 1.0.0 rc1
centos 7

Having problems testing alerts against the following graph query:

grafana query: 
SELECT 8 * non_negative_derivative(max("ifHCInOctets"), 1s) AS "IN" FROM "interface" WHERE "hostname" = 'switch' AND "ifDescr" = 'Vlan20' AND $timeFilter GROUP BY time($interval), "ifDescr" fill(null)

response:
{"firing":false,"timeMs":"3.162ms","error":"tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request"}

request body:
{"dashboard":{"id":11,"title":"snmp alerting","tags":[],"style":"dark","timezone":"browser","editable":true,"hideControls":false,"sharedCrosshair":true,"rows":[{"collapse":false,"editable":true,"height":308.892333984375,"panels":[{"aliasColors":{},"bars":false,"datasource":"snmp","editable":true,"error":false,"fill":4,"grid":{},"id":1,"interval":"$timeres","isNew":true,"legend":{"alignAsTable":true,"avg":true,"current":false,"max":true,"min":false,"rightSide":true,"show":true,"sideWidth":350,"sort":"max","sortDesc":true,"total":false,"values":true},"lines":true,"linewidth":1,"links":[],"minSpan":1,"nullPointMode":"connected","percentage":false,"pointradius":5,"points":false,"renderer":"flot","repeat":null,"repeatIteration":1472575188177,"seriesOverrides":[{"alias":"/IN/i","color":"#70DBED"},{"alias":"/OUT/i","color":"#5195CE","transform":"negative-Y"}],"span":12,"stack":false,"steppedLine":false,"targets":[{"alias":"$tag_ifDescr IN","dsType":"influxdb","groupBy":[{"params":["$interval"],"type":"time"},{"params":["ifDescr"],"type":"tag"},{"params":["null"],"type":"fill"}],"measurement":"interface","policy":"default","query":"SELECT 8 * non_negative_derivative(max(\"ifHCInOctets\"), 1s) AS \"IN\" FROM \"interface\" WHERE \"hostname\" = 'switch' AND \"ifDescr\" = 'Vlan20' AND $timeFilter GROUP BY time($interval), \"ifDescr\" fill(null)","rawQuery":true,"refId":"A","resultFormat":"time_series","select":[[{"params":["ifInOctets"],"type":"field"},{"params":[],"type":"distinct"},{"params":["5s"],"type":"non_negative_derivative"}]],"tags":[{"key":"agent_host","operator":"=~","value":"/^$switch$/"},{"condition":"AND","key":"ifDescr","operator":"=~","value":"/^$interface$/"}]}],"thresholds":[{"value":2000000,"op":"gt","fill":true,"line":true,"colorMode":"critical"}],"timeFrom":null,"timeShift":null,"title":"switch octets by $timeres","tooltip":{"msResolution":false,"shared":false,"sort":0,"value_type":"cumulative"},"type":"graph","xaxis":{"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"bps","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"alert":{"conditions":[{"type":"query","query":{"params":["A","5m","now"]},"reducer":{"type":"max","params":[]},"evaluator":{"type":"gt","params":[2000000]}}],"noDataState":"alerting","frequency":"60s","handler":1,"notifications":[],"name":"switch octets by $timeres alert"}}],"repeat":"switch","scopedVars":{"switch":{"selected":true,"text":"switch","value":"switch"}},"title":"Row"}],"time":{"from":"now-1h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"templating":{"list":[{"auto":true,"auto_count":500,"auto_min":"10s","current":{"text":"5s","value":"5s"},"datasource":null,"hide":0,"includeAll":false,"label":"","multi":false,"name":"timeres","options":[{"text":"auto","value":"$__auto_interval","selected":false},{"text":"1s","value":"1s","selected":false},{"text":"5s","value":"5s","selected":true},{"text":"10s","value":"10s","selected":false},{"text":"30s","value":"30s","selected":false},{"text":"1m","value":"1m","selected":false},{"text":"10m","value":"10m","selected":false},{"text":"30m","value":"30m","selected":false},{"text":"1h","value":"1h","selected":false},{"text":"6h","value":"6h","selected":false},{"text":"12h","value":"12h","selected":false},{"text":"1d","value":"1d","selected":false},{"text":"7d","value":"7d","selected":false},{"text":"14d","value":"14d","selected":false},{"text":"30d","value":"30d","selected":false}],"query":"1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d","refresh":2,"type":"interval"}]},"annotations":{"list":[]},"refresh":"5m","schemaVersion":13,"version":4,"links":[],"gnetId":null},"panelId":1}

**Comment by bergquist** [comment]
Grafana alerting does not support templating variables. Try giving ifDescr and agent_host real values

**Comment by discoduck2x** [comment]
@bergquist 
there is something cached somewhere, the dashboard is a copy of one that has template vars, i removed the template vars both from template editor and their usage from the raw metrics grafana query....saved dashboard, reloaded it clean, still produces the request above with the template variables.....

but to start 100% fresh I now copied the raw grafana query and pasted it into a new dashboard, getting the following error. 
(also, if i toggle from max() in alerting to avg() then i cant choose max() again,, it isnt in the drop down..)

response:
{"firing":false,"timeMs":"0.428ms","error":"tsdb.HandleRequest() error type assertion to string failed"}

request:
{"dashboard":{"id":12,"title":"New dashboard","tags":[],"style":"dark","timezone":"browser","editable":true,"hideControls":false,"sharedCrosshair":false,"rows":[{"collapse":false,"editable":true,"height":"250px","panels":[{"alert":{"conditions":[{"evaluator":{"params":[3000000],"type":"gt"},"query":{"params":["A","5m","now"]},"reducer":{"params":[],"type":"max"},"type":"query"}],"frequency":"60s","handler":1,"name":"Panel Title alert","noDataState":"alerting","notifications":[]},"aliasColors":{},"bars":false,"datasource":"snmp","editable":true,"error":false,"fill":1,"id":1,"isNew":true,"legend":{"alignAsTable":true,"avg":true,"current":false,"max":true,"min":true,"rightSide":true,"show":true,"total":false,"values":true},"lines":true,"linewidth":2,"nullPointMode":"connected","percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"span":12,"stack":false,"steppedLine":false,"targets":[{"dsType":"influxdb","groupBy":[{"params":["$interval"],"type":"time"},{"params":["null"],"type":"fill"}],"policy":"default","query":"SELECT 8 * non_negative_derivative(max(\"ifHCInOctets\"), 1s) FROM \"interface\" WHERE \"hostname\" = 'STO-COLT-RTR01.neonet.com' AND \"ifDescr\" = 'Vlan20' AND $timeFilter GROUP BY time($interval), \"ifDescr\" fill(null)","rawQuery":true,"refId":"A","resultFormat":"time_series","select":[[{"params":["value"],"type":"field"},{"params":[],"type":"mean"}]],"tags":[]}],"thresholds":[{"value":3000000,"op":"gt","fill":true,"line":true,"colorMode":"critical"}],"timeFrom":null,"timeShift":null,"title":"Panel Title","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"cumulative"},"type":"graph","xaxis":{"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"links":[]}],"title":"Row"}],"time":{"from":"now-15m","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"templating":{"list":[]},"annotations":{"list":[]},"schemaVersion":13,"version":3,"links":[],"gnetId":null},"panelId":1}

**Comment by bergquist** [comment]
Embarrassing... Ive forgot to add support for raw queries..... Ill fix this right now.

**Comment by bergquist** [comment]
Support for raw queries have been added.

I created a new issue for toggling between max() and avg() https://github.com/grafana/grafana/issues/6241

**Comment by bergquist** [comment]
Thank you so much for testing this! :)

**Comment by discoduck2x** [comment]
@bergquist sweet it works now! :)  , regarding templating is that not going to be supported at all for alerting?

**Comment by nnsaln** [comment]
I've tried alert notification via email and sent test email, but I still do not get the email. 
And somehow I got this error tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request
