### ISSUE TITLE
InfluxDB: Migrate deprecated database field into jsonData.dbName

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#62311]
This is a complementary task for https://github.com/grafana/grafana/issues/59115

For backward compatibility, we should be careful about this. 

- Remove database field from our database 
  - We could potentially use sql-database-migrations. So when grafana upgraded migration is done out of the box.
  - Migration should copy the data from `database` to `jsonData` -> `{"dbName":"site"}`
- We should update existing docs 
- Maybe a warning text should be shown

**A/C**
- Existing dashboards must keep working
- Existing datasources must not use database field and read this information from `jsonData`
- Nothing must be broken

**Comment by patagonaa** [comment]
Idk if this is the same issue, but upgrading from 9.0.4 to 9.4.7 broke all InfluxDB panels for me by clearing (or not migrating) the "Database" field in all InfluxDB datasources. So it seems something is broken in the 9.4.7 release already (or somewhere inbetween)

The error message was:
`"error authorizing query: <user> not authorized to execute statement 'SELECT [...]', requires READ on "`

**Comment by Infant-Rashmi** [comment]
In 9.4.7, I am also facing the same issue...InfluxDB panels "Database" field is being cleared in grafana ui

**Comment by itsmylife** [comment]
@patagonaa @Infant-Rashmi The fix we released was targeting `v9.5.0` and it is this PR https://github.com/grafana/grafana/pull/62308
So that should not affect the older versions. But to be sure about that I will try to reproduce the issue by having a dashboard on `v9.0.7` and upgrading it to `v9.4.7`

**Comment by itsmylife** [comment]
@patagonaa @Infant-Rashmi I was able to reproduce the issue and found the root cause. The problem was fixed here https://github.com/grafana/grafana/pull/62790 
So upgrading to a newer version will be viable, but unfortunately, as the migration is wrong, the information got lost in the database. 

So I can confirm that the problem is not related to this issue.
