### ISSUE TITLE
Prometheus: QueryEditor: no abs operation found in builder mode

### ISSUE THREAD

**Issue by mlcdf** [grafana/grafana#62325]
Hello :)

**What happened**: 

No [abs](https://prometheus.io/docs/prometheus/latest/querying/functions/#abs) operation found in query editor, in builder mode:
![image](https://user-images.githubusercontent.com/9364931/215099262-de6b8832-c486-4f07-a48a-2c7629ea4df5.png)

If I use the abs prometheus function in the code mode:
![image](https://user-images.githubusercontent.com/9364931/215099705-c8bfd3a4-c990-459a-8515-9b4afb7aa6ad.png)

And then switch to builder mode, I get this error:
![image](https://user-images.githubusercontent.com/9364931/215100201-b96bafd5-067d-4550-9ec8-bf0cc6296b2c.png)

**What you expected to happen**:

I expected to find the abs operation in the builder mode. And no error when using `abs` in code and switching to builder mode.

**How to reproduce it (as minimally and precisely as possible)**:

- create or update a panel
- select a prometheus datasource
- add a query with `abs` in code (ex: `abs(go_gc_duration_seconds)`), and try to switch to builder mode.

**Anything else we need to know?**:

I don't think so.

**Environment**:
- Grafana version: 9.3.6 (but this was present in 9.2.x)
- Data source type & version: Prometheus 5.0.0
- OS Grafana is installed on: Debian
- User OS & Browser: Ubuntu & Firefox

**Comment by zuchka** [comment]
Thanks for creating this issue, @mlcdf 

reproduced on main `Grafana v9.4.0-pre (e7ace4ed62)`

**Comment by kylebrandt** [comment]
Looks maybe like it needs to be added to https://github.com/grafana/grafana/blob/1dc986f9e120c46d7b2083d0c75af60b66dfd9d4/public/app/plugins/datasource/prometheus/querybuilder/operations.ts#L20
