### ISSUE TITLE
alert is not sent when the requirement is meet.

### ISSUE THREAD

**Issue by qingweiqm** [grafana/grafana#6232]
* **I'm submitting a Question**

- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
the newest version
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 7
- What did you do?
setting alert in graph using influxdb.
- What was the expected result?
when the requirement is meet, fire the alert
- What happened instead?
alert is sent sometimes,but what's the mechanism for sending the alert ?
**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

![2016-10-11 5 17 26](https://cloud.githubusercontent.com/assets/20061689/19265175/9c34f1bc-8fd6-11e6-9910-3326a2c3acf2.png)
![2016-10-11 5 17 07](https://cloud.githubusercontent.com/assets/20061689/19265177/9c6311d2-8fd6-11e6-93cd-de702e9ebb3a.png)
![2016-10-11 5 16 36](https://cloud.githubusercontent.com/assets/20061689/19265176/9c62b106-8fd6-11e6-92b6-cf32286bdbef.png)

**Comment by bergquist** [comment]
- Have you saved the dashboard?
 - Does the notification work if you use test send at "/alerting/notifications"?

**Comment by torkelo** [comment]
notifications are not sent when you test the alert, it seems to have fired for real once (seen in the alert annotation). Does the notification you have added work?

**Comment by qingweiqm** [comment]
yes, I did save the dashboard.
the notification works alright.

**Comment by torkelo** [comment]
alerts are only sent on state changes (same when annotations are created). 

Are you seeing alert state changes & annotations but no notification?

**Comment by bergquist** [comment]
@qingweiqm try changeing the threshold to get back to a normal state. Would that trigger a notification?

**Comment by whc9527** [comment]
@qingweiqm  hello,I met the same problem as you. 
![image](https://cloud.githubusercontent.com/assets/17898805/23214857/43aee1d6-f94b-11e6-97e4-dd94fa803b64.png)
my script is twenty minutes to collect data, and then inserted into the influxdb.
at my first time to add the alerting it works and send email, but when twenty minutes latter, there is no alert email any more. 
coud anybody can help me.. thx...

**Comment by bergquist** [comment]
@whc9527 did the state go back to ok? Grafana only sends new notifications when the state changes.

**Comment by whc9527** [comment]
@bergquist  Thank you very much, as you said ”Grafana only sends new notifications when the state changes”. Thx !!!!!!!!!
