### ISSUE TITLE
Folders: Admin user of a folder can't see Team permissions

### ISSUE THREAD

**Issue by vaxvms** [grafana/grafana#62336]
**What happened**:

Admin user of a folder see Team permission only if he is a part of the team.
Teams he is isn't part of are hidden.

User view :
![user1](https://user-images.githubusercontent.com/310200/215117741-eb58a5cc-db4d-42fb-baec-2f3b28bd03d8.png)

**What you expected to happen**:

An admin user of a folder should see all user and team permissions on the folder

![user2](https://user-images.githubusercontent.com/310200/215118403-29f8ea3e-5b22-4269-af25-b9e885257c4e.png)

**How to reproduce it (as minimally and precisely as possible)**:

- Create a folder
- Create user1 and user2
- Create team-test1 and test-test2
- assign user2 to team team-test-1
- assign permission to user1 as a folder Admin
- assign permission to team-test-1 a a folder admin
- assign permission to team-test-2 as a folder admin

user2 can see that :
- user1 is a admin
- team-test-1 is a admin
user2 can't see that team-test-2 is a admin

user1 can see he is an admin.
user1 can't see that team-test-1 and team-test-2 are admin 

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: N/A
- OS Grafana is installed on: Official Docker Image grafana/grafana:9.3.6
- User OS & Browser: Ubuntu 20.04 / Firefox 108
- Grafana plugins:
- Others:

**Comment by murtazaqa** [comment]
Facing the same issue. This creates confusion for users who are Admin to the folder.
