### ISSUE TITLE
"Stacked value" in hover info does not show up when using overrides to stack [3.1.1]

### ISSUE THREAD

**Issue by XANi** [grafana/grafana#6235]
Steps to reproduce:

* create graph with stacking off
* set stacking to "stack A" for specific time series in "Series specific overrides"
* option "stacked value" disappears from "hover info"

"Stacked value" should be either

* visible at all time
* visible when global OR any of series specific overrides have enabled stacking

![zaznaczenie_2016-10-11_001](https://cloud.githubusercontent.com/assets/147394/19268427/c0768b20-8fb4-11e6-8b44-4d907ee3e454.png)

**Comment by torkelo** [comment]
The stacked value hover option is only available when the whole graph has stacking enabled. If you only have some series stacked I am afraid you will have to live without this feature

**Comment by XANi** [comment]
Okay, let me rephrashe that.

The "feature" of displaying non-cumulative tooltips in that case works correctly. If I save graph under 3.0 and then read it under 3.1 it will still display correctly.

Just the field to choose that feature is not displayed when it should (and cumulative tooltip is awful default IMO)

**Comment by torkelo** [comment]
yea, agree the cumulative default is pretty bad. will change that (0bae12e4ae2ee500da84c57cb87e3807cff43687)
