### ISSUE TITLE
Drag & Drop: Enhancement - Change datasource picker to include Drag & Drop

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#62355]
Currently the drag and drop functionality is hidden and not visible for users unless they know the selection:
Datasource --> Grafana
Query --> Snapshot or Spreadsheet has to be selected

Adding the enhancement on having the additional items:
Datasource --> CSV/Spreadsheet 
With the selection the drag & drop zone should become visible in the query editor.

**Comment by oscarkilhed** [comment]
relates to: #62083
