### ISSUE TITLE
API: admin-level api key fails (not enough permissions) on /api/users, but succeeds if path changed to /api/org/users

### ISSUE THREAD

**Issue by danstadler-pdx** [grafana/grafana#62365]
**What happened**: I tested using an admin-level API key to list users against self-managed Grafana Enterprise; per docs, I should be able to call /api/users to list users, but instead I can only list users if I change the path to /api/org/users

**What you expected to happen**: call /api/users with admin api token, get list of users

**How to reproduce it (as minimally and precisely as possible)**:
deploy grafana 9.3.6 via docker -- v9.3.6 (978237e7cb)
create admin-level API key
use supplied curl call from resulting UI modal, to sanity-check that I can get dashboards - this succeeds
then change api call to /api/users
result: 
{"accessErrorId":"ACE1984073793","message":"You'll need additional permissions to perform this action. Permissions needed: users:read","title":"Access denied"}

then change api call to /api/org/users - this succeeds

curl -H "Authorization: Bearer REDACTED" http://localhost:3000/api/org/users
[{"orgId":2,"userId":1,"email":"admin@localhost","name":"","avatarUrl":"/avatar/46d...","login":"admin","role":"Admin","lastSeenAt":"2023-01-27T18:09:47Z","lastSeenAtAge":"3 minutes","isDisabled":false}]

**Anything else we need to know?**: Docs only say to use /api/users:
https://grafana.com/docs/grafana/latest/developers/http_api/user/#search-users

**Environment**:
- Grafana version:  v9.3.6 (978237e7cb) via Docker on Mac OSX
- Data source type & version: n/a
- OS Grafana is installed on: Docker / Mac OSX
- User OS & Browser: OSX/Chrome
- Grafana plugins: n/a
- Others:

**Comment by bla2ej** [comment]
I've tested it a bit and I can confirm this problem on most recent main branch grafana version.
I've tried all 3 authorization methods:

On `/api/users`:
- using Session cookie result is correctly fetched
- using Basic Auth result is correctly fetched (`curl http://admin:admin@localhost:3000/api/users`)
- using API Token with Admin privileges I get above error

On `/api/org/users`:
- all auth methods get correct response.

I'll try to dig more into this issue (unless someone else knows that this is how it should work :))

**Comment by mildwonkey** [comment]
Hello! I'm going to re-label this so it goes to the correct teams, but the general recommendation is to migrate API keys to service accounts.

**Comment by sakjur** [comment]
For what it's worth, this is expected behavior. The note at the top of [the admin HTTP docs](https://grafana.com/docs/grafana/latest/developers/http_api/admin/) is applicable here (I don't know why it isn't present on the docs for the users API too). The gist of it is that API keys must belong to an organization, and cannot use instance-wide APIs.
