### ISSUE TITLE
Spike: audit core and previously confirmed datasource plugins and take note of any querying an endpoint besides /ds/query

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#62374]
Discovered that for the Graphite datasource, queries were being send to `/api/datasources/proxy/:id/render` instead of `/api/ds/query`. This led to a user discovering issues with the Graphite datasource when executing multiple queries that had not been seen in a normal dashboard.

We should do an audit of all core/bundled datasources and determine if there are others querying alternative endpoints, then open follow-up issues to resolve each instance.

**Comment by evictorero** [comment]
Evaluate all [core data sources](https://github.com/grafana/grafana/tree/main/public/app/plugins/datasource)
For each one: 
* Does it extend `DataSourceWithBackend`?
* Does it call `super.query` or does it use a custom URL?

**Comment by juanicabanas** [comment]
| DataSource Plugin  | Calls super.query from DSWithBackend | Notes |
| ------------- | ------------- | ------------- |
| AlertManager  | ➖ | It's not supposed to be a DS plugin | 
| AlertManager  | ➖ | It's not supposed to be a DS plugin |
