### ISSUE TITLE
chore: refactor api permissions tests

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana#62377]
Permissions tests for api tests are a bit unwieldy, done differently on each endpoint, and hard to read.

For 403 cases, we won't actually call the service and we can just check the http response code.

For "successful" cases, we can verify that we did not get a 403 back.

**Comment by yuktea** [comment]
@jalevin: I would like to work on this. I'm a new contributor and I was wondering if there is an IRC or Slack where the devs/contributors talk? I had a few questions.

**Comment by insaaniManav** [comment]
Hi , is this done , I am new to contributing to grafana , if not would love to pick this up , or if theres any issue that requires immediate attention
