### ISSUE TITLE
Bug: Repeating rows don't update on template change

### ISSUE THREAD

**Issue by joscha-alisch** [grafana/grafana#6237]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
grafana-4.0.0-1476187686pre1
- What datasource are you using?
graphite
- What OS are you running grafana on?
Linux (CloudFoundry)

When I create a multi-select template (A), that depends on another template (B) and I have a row set to repeat based on template A, everything works as expected as long as I only change the selection in template A. 

As soon as I change the selection in template B, which in turn updates template A, the repeating row is stuck in it's current state and doesn't update anymore.

**Comment by torkelo** [comment]
thanks for reporting this! fixed
