### ISSUE TITLE
task: Indicate where the selected time range is coming from in public dashboard config page.

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#62381]
When sharing a public dashboard, the time range field looks like a grayed out editor component. I didn't realize that this value is derived from the dashboard default and can't be changed in the pubdash dialog. I recommend that we change the styling (changing the cursor and removing hover actions would be good) and add a tooltip explaining how to change the value.

**Comment by evictorero** [comment]
We implemented a new design and time range picker feature after this task was created, It's irrelevant now.
