### ISSUE TITLE
Spike: Research basic variable support approach

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#62389]
[Product DNA](https://docs.google.com/document/d/1QGQXa9EUod1GqqCU5dWEamGTsyEHx_EnuJMBcDznTyo/edit#) on this approach, basically look into if we can do what recorded queries does for both variables and time selection.

**Comment by natellium** [comment]
Info in https://github.com/grafana/grafana/issues/67346. Can reopen this if needed once we prioritise this project.

**Comment by chenlitchian** [comment]
what is the progress for this feature?
