### ISSUE TITLE
Feature Request: As a user, I would like to be able to control the css theme of a public dashboard

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#62387]
It looks like the dashboard sync to the org default theme, or for logged in users, your set theme. There should be more explicit control over the styling of public dashboards.

Ideas:

- When creating the public dashboard, there should be a light/dark theme toggle (stores the preferred value in the db)
- On a dashboard itself, there should be an additional toggle that just changes the theme on the front end (no db change, viz only)

**Comment by evictorero** [comment]
@thanos-karachalios do you think this is something we would like to have in a future?

**Comment by we684123** [comment]
+1

**Comment by Westy-87** [comment]
I still want this :D
