### ISSUE TITLE
Story: As an administrator I would like to limit the time range selection options on a public dashboard

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#62380]
Customers may not want consumers of public dashboards to select any time range they want.

https://github.com/grafana/grafana/issues/62380

**Comment by natellium** [comment]
@evictorero @juanicabanas reopen it if I got it wrong but I think we can close this. Right now the user can decide whether they show the timepicker or not. We can see if in the future there's a need for a more fine grained access (e.g only certain types of ranges).
