### ISSUE TITLE
Create a definition of done doc for Public Dashboards (get into Beta)

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana#62385]
Fill out beta section

https://docs.google.com/document/d/1rebhVahCJ_6K3Oa8YC4cqdpm7Iytd_papIyxeBGY_f0/edit

add findings to milestone 2 doc

**Comment by evictorero** [comment]
Duplicated, using [this](https://github.com/grafana/grafana-enterprise/issues/4717) now
