### ISSUE TITLE
Library Panels arent working with Public Dashboards

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#62390]
Steps to reproduce:
1. Add a library panel to your dashboard
2. View the dashboard's public dashboard
3. Should see a `Panel plugin not found: undefined` error

![Image](https://user-images.githubusercontent.com/20195316/188693629-5134bbda-986c-4858-93dc-f6d8131c4a9f.png)

The pubdash query endpoint is returning a 500. Looks like the problem is in `GroupQueriesByPanelId()`. The panels json look like they're missing a bunch of data (for example, no targets key).

**Comment by evictorero** [comment]
[Duplicated](https://github.com/grafana/grafana/issues/62390)
