### ISSUE TITLE
HTTP 401 error wrongly returned when uploading invalid JSON dashboard

### ISSUE THREAD

**Issue by marcv81** [grafana/grafana#6240]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

Built from source, latest master (0d4b00d)

- What datasource are you using?

None.

- What OS are you running grafana on?

Ubuntu 16.04.

- What did you do?

I setup Grafana with auth.proxy behind an NGINX reverse proxy with auth_basic. The authentication is working perfectly, this is not the problem. I went to upload a JSON dashboard, but provided a JPEG file instead.

- What was the expected result?

I should get an error.

- What happened instead?

I got an HTTP 401 error. This is not the correct error to return in this case, as there is nothing wrong with my credentials. Because I am behind a reverse proxy with auth_basic, my browser (Chrome) quite reasonably asked me to provide my credentials again. Providing my credentials just resubmits the request, which results in a 401 again.

**Comment by torkelo** [comment]
Do you have the grafana log for this? Cannot replicate it, when I pick an image file in the upload dialog I just get a Javascript error.

**Comment by marcv81** [comment]
This only happens when running behind a reverse proxy, I get a 404 when hitting Grafana directly. The first request (401) is when using the reverse proxy, and the second one (404) immediately after is when hitting Grafana directly.

```
INFO[10-12|00:16:50] Starting Grafana                         logger=main version=4.0.0-pre1 commit=v3.1.0-1072-g0d4b00d compiled=2016-10-11T22:03:00+0800
INFO[10-12|00:16:50] Config loaded from                       logger=settings file=/home/marc/data/Workspace/grafana4/src/github.com/grafana/grafana/conf/defaults.ini
INFO[10-12|00:16:50] Config loaded from                       logger=settings file=conf/sample.ini
INFO[10-12|00:16:50] Path Home                                logger=settings path=/home/marc/data/Workspace/grafana4/src/github.com/grafana/grafana
INFO[10-12|00:16:50] Path Data                                logger=settings path=/home/marc/data/Workspace/grafana4/src/github.com/grafana/grafana/data
INFO[10-12|00:16:50] Path Logs                                logger=settings path=/home/marc/data/Workspace/grafana4/src/github.com/grafana/grafana/data/log
INFO[10-12|00:16:50] Path Plugins                             logger=settings path=data/plugins
INFO[10-12|00:16:50] Initializing DB                          logger=sqlstore dbtype=sqlite3
INFO[10-12|00:16:50] Starting DB migration                    logger=migrator
INFO[10-12|00:16:50] Executing migration                      logger=migrator id="copy data account to org"
INFO[10-12|00:16:50] Skipping migration condition not fulfilled logger=migrator id="copy data account to org"
INFO[10-12|00:16:50] Executing migration                      logger=migrator id="copy data account_user to org_user"
INFO[10-12|00:16:50] Skipping migration condition not fulfilled logger=migrator id="copy data account_user to org_user"
INFO[10-12|00:16:50] Starting plugin search                   logger=plugins
INFO[10-12|00:16:50] Initializing CleanUpService              logger=cleanup
INFO[10-12|00:16:50] Initializing Alerting                    logger=alerting.engine
INFO[10-12|00:16:50] Initializing HTTP Server                 logger=server address=0.0.0.0:3000 protocol=http subUrl=
INFO[10-12|00:17:27] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/undefined status=401 remote_addr=127.0.0.1 time_ms=1.423µs size=58
INFO[10-12|00:18:16] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/undefined status=404 remote_addr=127.0.0.1 time_ms=244ns size=51
```

**Comment by marcv81** [comment]
Also I can confirm from my browser dev tools that I get a 401 when hitting http://127.0.0.1/api/gnet/dashboards/undefined (reverse proxy) and a 404 when hitting http://127.0.0.1:3000/api/gnet/dashboards/undefined (direct).

**Comment by marcv81** [comment]
@torkelo, apologies but my steps to reproduce were not correct. I have updated the description. The issue does not happen when uploading an invalid JSON but when clicking in and out of the Grafana.net dashboard field. I was somehow doing both when reproducing.

**Comment by marcv81** [comment]
PR submitted: https://github.com/grafana/grafana/pull/6243

**Comment by emmayang** [comment]
Hi @marcv81 @torkelo I still have same problem in Grafana V4.2 & V4.3. So we use an auth proxy in front of our Grafana to enable SSO, and it worked fine with basic functions, user can login and create/view dashboards. However if non-root user want to import a dashboard, there will be error reported as "Unauthorized", and from the Chrome dev console, there's this /api/login/ping call returns 401 and failed the action. 

I checked the code, and found this /api/login/ping is a required validation for some high level actions (import dashboard is one of it), and the "grafana_remember" cookie is only generated when the POST to /api/login. If we use an authproxy in the front, we will never call /api/login API, and grafana_remember cookie will not be generated and always get 401.
