### ISSUE TITLE
Metric Namespace Cloud Service (Classic)

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#62406]
**What happened**:

I am unable to query metrics for Azure resources of type Cloud Service (Classic). I am only able to see this namespace if the service being used is Logs:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/20448042/215211256-090b9013-1837-4500-a727-3dee36ee8f5d.png">

if I look at resources from metrics service, that resource is not there:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/20448042/215212355-5a67d3fa-175b-4e69-96f9-d9465321f0d9.png">

**What you expected to happen**:

for Cloud Service (Classic) when querying from Metrics 

**How to reproduce it (as minimally and precisely as possible)**:
Create a Cloud Service (Classic) resource
go to grafana and create an Azure Monitor Metrics query
Try to select the resource created above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2.2
- Data source type & version: Azure Monitor
- OS Grafana is installed on:
- User OS & Browser: Windos, Edge
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@jcolladokuri I've moved this to our partner datasource squad to confirm if this is expected. I found this information that cloud (classic) is being deprecated - I'm not sure if that's related: 

https://azure.microsoft.com/en-us/updates/cloud-services-retirement-announcement/

**Comment by kayodeprinceMS** [comment]
It's not yet deprecated and users should be able to use Grafana to visualize current utilization as part of their migration plan.

**Comment by alyssabull** [comment]
It looks like the correct namespace for the Cloud services (classic) resource is `microsoft.classiccompute/domainnames` but the namespace that [this API](https://learn.microsoft.com/en-us/rest/api/monitor/metric-namespaces/list?tabs=HTTP#metricnamespace) is returning is `microsoft.classiccompute/domainnames/slots/roles`. Can you provide insight on why this might be the case?

**Comment by jcolladokuri** [comment]
Hi @alyssabull thank you for getting back.

I checked with some teams internally and the reason for returning `microsoft.classiccompute/domainnames/slots/roles` is because metrics for classic compute are only valid at the role level, not at the top "classic compute" level, for classic cloud services we'll want to do a special case and match `microsoft.classiccompute/domainnames/slots/roles` instead

**Comment by aangelisc** [comment]
Hi @jcolladokuri, thanks for the update.

This is a little bit trickier than just substituting the metric namespace. Do you have an example query that correctly returns metric definitions and metric values for the `microsoft.classiccompute/domainnames/slots/roles` namespace? I've attempted to get this working but I can't get any data returned. 

Additionally, it'd be great to know if there are any other edge case namespaces. We're trying to automate the namespace and location retrieval as much as possible to avoid the need for us to periodically synchronise data in Grafana with Azure (leading to resources being unavailable for querying for some time). However, these edge cases make this slightly more difficult.

**Comment by RodrigoVeraRomero** [comment]
Hi @jcolladokuri 

The problem is that we can not see cloud service clasic namespace automatically like this image

![image](https://user-images.githubusercontent.com/62779771/220768648-6032f98a-b58e-433f-b4fc-e4d6070b9b37.png)

I found a workaround for this issue we may go to advance settings and set 

![image](https://user-images.githubusercontent.com/62779771/220769422-430eadb2-9322-4932-b9cb-f19aafb14823.png)

Subscription = subscriptionId
Resource Group = resourcegroupname
Namespase = Microsoft.ClassicCompute/domainNames/slots/roles
Resource Name = CloudName/Production or Staging/RoleName

Then we could see metrics.



![image](https://user-images.githubusercontent.com/62779771/220769540-a4b6efc7-9041-4071-9897-b9c8a2975cac.png)

**Comment by jcolladokuri** [comment]
@aangelisc thank you for taking a look! I have started an email thread to further look into the issues you are encountering.

**Comment by taleena** [comment]
Is this related to the current namespace issue we're tracking down also?
