### ISSUE TITLE
Cloud Watch logs datasource does not use relative time query option

### ISSUE THREAD

**Issue by softwarewright** [grafana/grafana#62415]
**What happened**: Attempted to create a panel that fetches logs over the last week `now/w`, which I need to be separate from the time range that affects rest of the dashboard. When adding `now/w` to Data source -> Query options -> Relative time the panel does not use the `Relative time` it uses the `Time range` only.

**What you expected to happen**: The panel to use `Relative time` instead of the `Time Range` of the dashboard when querying CloudWatch logs in a panel.

**How to reproduce it (as minimally and precisely as possible)**:

1. Select any CloudWatch log group
2. Perform a query
3. Set the Relative time to a longer period than the time range.

See image for example:

<img width="1719" alt="Screenshot 2023-01-28 at 6 23 20 AM" src="https://user-images.githubusercontent.com/49100831/215268741-2d46b202-2a01-4f0b-a62c-db2217243ccb.png">

**Anything else we need to know?**:

It's clear that the panel is updating the view to show the full week, it seems that the `Relative time` is not being applied to the CloudWatch log query. In addition, I noticed that when performing a query against CloudWatch metrics in a panel setting the `Relative time` query option works.

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: CloudWatch (builtin so same as grafana version)
- OS Grafana is installed on: Alpine
- User OS & Browser: Mac/Chrome
- Grafana plugins: None
- Others:

**Comment by kevinwcyu** [comment]
Hi @softwarewright. Thanks for the report. I was able to reproduce this. I've moved this issue into our team's backlog for further investigation and coming up with a fix.
