### ISSUE TITLE
query editor missing

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#62414]
Yesterday I updated to 9.3.6 and now the query editor is missing:

![grafik](https://user-images.githubusercontent.com/81651521/215264283-9c4013a0-87d6-4e50-aa89-0d4c8a3650a0.png)

any idea how to get it back ?

**Comment by zuchka** [comment]
what happens if you expand queries A, B, or C? same thing?

**Comment by caunus** [comment]
Same here. As well latest version, on a self hostet Ubuntu instance . Not possible to edit exiting queries, but possible to create new on. No difference if pane is close or open. Grafana is connect to an local InfluxDB server.

**Comment by tonypowa** [comment]
marking it as a bug and forwarding it to the dashboard squad since more users have reported this issue

**Comment by axelavargas** [comment]
Hey @Becker884  👋🏾 , thanks a lot for reporting this issue, I am closing this as a duplicate of https://github.com/grafana/grafana/issues/61710 , the fix is already in place 🥳 PR: https://github.com/grafana/grafana/pull/61927

**Comment by Becker884** [comment]
Today I got 9.4.1 and there is nox fix
