### ISSUE TITLE
Traces: dashboard will not load without setting `preferredVisualisationType`

### ISSUE THREAD

**Issue by vinaychandra** [grafana/grafana#62417]
**What happened**: If creating dashboards using traces, the data will not load if `preferredVisualisationType` is not set. This value should probably be checked in explore but not in dashboards. 
https://github.com/grafana/grafana/blob/main/public/app/features/explore/TraceView/TraceView.tsx#L140

**What you expected to happen**: Traces can be displayed using data sources without `preferredVisualisationType` in dashboards

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard with traces, use one of the non out-of-the-box trace providers but provide the data as required by the API correctly.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2.2
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Windows / firefox/chrome
- Grafana plugins:
- Others:

**Comment by BenSR** [comment]
Seconding this! Trying to get Traces working with Azure Log Analytics - table view looks OK but getting "No Data" message. Also not sure how to get the serviceTags attribute into an array of KV values from Kusto, but that's a secondary worry!

**Comment by vidommet** [comment]
I am also looking at Azure Log Analytics. The following gets the required structure but will not display because of the above setting
```
 Span
| where time > ago(1h) // Just for testing
| take 10 // Just for testing
| extend envpropsjson = parse_json(env_properties) // blob of json {"a":"b"}
| mv-apply p3 = envpropsjson on (
     mv-expand bagexpansion=array envpropsjson
    | extend kvpair = bag_pack("key", envpropsjson[0], "value", envpropsjson[1])
    | summarize taglist = make_set(kvpair)
)
| sort by startTime asc
| project traceID = traceId, spanID = spanId, parentSpanID = parentId, serviceName = name, operationName = name, startTime = TimeStamp,
 duration =  (TimeStamp - startTime) / 1ms, tags = taglist, serviceTags = '[]'
```

This provides the required structure for traces but will not give the visualization type. (Which is meant to be preferred but in this case, that shouldn't have mattered because we ask for a specific dashboard type)

**Comment by UnamedRus** [comment]
The same for ClickHouse:

```
SELECT trace_id as traceID, span_id as spanID, parent_span_id as parentSpanID, operation_name as operationName, 'clickhouse' as serviceName, [] as serviceTags, start_time_us/1000 as startTime, (finish_time_us - start_time_us)/1000 as duration  FROM cluster('all-sharded',system.opentelemetry_span_log) WHERE trace_id = 'fb40d66c-4373-7685-778d-5c549c8b8b45'
```
