### ISSUE TITLE
Grafana not showing graphs/template queries on nightly build with InfluxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#6242]
* **I'm submitting a ...**
-  Bug report

Please include this information:
- What Grafana version are you using?
grafana-4.0.0-1476202643pre1.linux-x64.tar.gz

- What datasource are you using?
InfluxDB 
- What OS are you running grafana on?
Linux healthmonitor-860059 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

- What did you do?
I installed nightly build of grafana-4.0.0-1476202643pre1.linux-x64.tar.gz, created influxdb datasources (i saw connection success message) and imported dashboards created in grafana-3.0.2-1463383025 to grafana-4.0.0-1476202643pre1.linux-x64.tar.gz

- What was the expected result?
See graphs on dashboards.

- What happened instead?

I see no data points and none of my graphs on none of dashboards (13 of them) are showing up.

Template queries are also not working.

Images:

![screen shot 2016-10-11 at 4 48 09 pm](https://cloud.githubusercontent.com/assets/406777/19292672/8fa725f4-8fd2-11e6-8839-bf73ff3f491f.png)
![screen shot 2016-10-11 at 4 47 50 pm](https://cloud.githubusercontent.com/assets/406777/19292673/8fa98ca4-8fd2-11e6-8d9e-9809ee22c9f0.png)

InfluxDB logs never got the request from GRAFANA.

**Comment by torkelo** [comment]
any errors in the chrome dev console?

**Comment by torkelo** [comment]
cannot replicate any issues locally, beside checking the chrome dev console for js errors, can you check the chrome dev tools network tab ? refresh dashboard (to trigger metric queries), look for the request to influxdb, check the response (and print here if you can)

**Comment by deepujain** [comment]
<img width="581" alt="screen shot 2016-10-11 at 10 11 57 pm" src="https://cloud.githubusercontent.com/assets/406777/19298108/c7c420fe-8fff-11e6-9446-3f59f2a3df33.png">

IS the request even going to Influx ?


InfluxDB logs shows no movement.

**Comment by deepujain** [comment]
database epjobs, ep exist.

**Comment by deepujain** [comment]
If i delete a query and click add query, it does not show drop down list of fields of influxDB measurement.
<img width="1363" alt="screen shot 2016-10-11 at 10 17 35 pm" src="https://cloud.githubusercontent.com/assets/406777/19298198/97ed1f56-9000-11e6-828e-0517f35aed0d.png">

**Comment by deepujain** [comment]
I have missed out something.

**Comment by deepujain** [comment]
<img width="982" alt="screen shot 2016-10-11 at 10 21 47 pm" src="https://cloud.githubusercontent.com/assets/406777/19298271/1f2a0cea-9001-11e6-892f-b1f0985a6bbe.png">

**Comment by deepujain** [comment]
I deleted datasources and added them again. works now.
