### ISSUE TITLE
gpg.key Not available

### ISSUE THREAD

**Issue by NightFlexer** [grafana/grafana#62432]
The command from the official installation instructions does not work:
sudo wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key

**Comment by NightFlexer** [comment]
curl -v https://apt.grafana.com/
*   Trying 151.101.2.217:443...
* Connected to apt.grafana.com (151.101.2.217) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Server finished (14):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=rpm.grafana.com
*  start date: Jan  1 11:07:56 2023 GMT
*  expire date: Apr  1 11:07:55 2023 GMT
*  subjectAltName: host "apt.grafana.com" matched cert's "apt.grafana.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: apt.grafana.com]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x56405f2e8b40)
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/2
> Host: apt.grafana.com
> user-agent: curl/7.87.0
> accept: */*
> 
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 403 
< server: Varnish
< retry-after: 0
< content-type: text/plain
< accept-ranges: bytes
< date: Sun, 29 Jan 2023 20:05:11 GMT
< via: 1.1 varnish
< x-served-by: cache-fra-eddf8230023-FRA
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1675022711.311838,VS0,VE0
< content-length: 38
< 
* Connection #0 to host apt.grafana.com left intact
Sorry, the provided token is not valid

**Comment by NightFlexer** [comment]
It's terrible, grafana blocks some countries. Complete stupidity on your part.

**Comment by a7lan** [comment]
It's very stupid! Why are you blocking everyone? Just because someone is in this country? Do you understand how stupid this is? It is enough to turn on vpn. But apart from complicating the work, your blocking does nothing!

**Comment by a7lan** [comment]
Open source out of politics? Bullshit!

**Comment by mskproger** [comment]
> It's very stupid! Why are you blocking everyone? Just because someone is in this country? Do you understand how stupid this is? It is enough to turn on vpn. But apart from complicating the work, your blocking does nothing!

That's right. This is called Nazism.
