### ISSUE TITLE
migration failed (id = copy data_source v1 to v2): Error 1054: Unknown column 'account_id' in 'field list'

### ISSUE THREAD

**Issue by iXingo** [grafana/grafana#62437]
**What happened**:
Deploye Grafana to k8s cluster failed.
logger=settings t=2023-01-30T04:05:13.614102149Z level=info msg="App mode production"
logger=sqlstore t=2023-01-30T04:05:13.614686566Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2023-01-30T04:05:14.002511032Z level=info msg="Starting DB migrations"
logger=migrator t=2023-01-30T04:05:14.116973432Z level=info msg="Executing migration" id="copy data_source v1 to v2"
logger=migrator t=2023-01-30T04:05:14.145593262Z level=error msg="Executing migration failed" id="copy data_source v1 to v2" error="Error 1054: Unknown column 'account_id' in 'field list'"
logger=migrator t=2023-01-30T04:05:14.145648165Z level=error msg="Exec failed" error="Error 1054: Unknown column 'account_id' in 'field list'" sql="INSERT INTO `user` (`version`\n, `login`\n, `company`\n, `is_admin`\n, `created`\n, `updated`\n, `id`\n, `email`\n, `name`\n, `password`\n, `salt`\n, `rands`\n, `org_id`) SELECT `version`\n, `login`\n, `company`\n, `is_admin`\n, `created`\n, `updated`\n, `id`\n, `email`\n, `name`\n, `password`\n, `salt`\n, `rands`\n, `account_id` FROM `user_v1`"
Failed to start grafana. error: migration failed (id = copy data_source v1 to v2): Error 1054: Unknown column 'account_id' in 'field list'
migration failed (id = copy data_source v1 to v2): Error 1054: Unknown column 'account_id' in 'field list'

**What you expected to happen**:
Success in deploying the Grafana to k8s cluster

**How to reproduce it (as minimally and precisely as possible)**:
use helm to deploy the Grafana to our cluster.
replicas: 3
Mysql server: Oracle Cloud, HA

**Anything else we need to know?**:
We copy the schema from staging env, since our MySQL server sql_primary_key is OFF, some tables can not be created. We use `helm install -f prod.yaml grafana-prod grafana/grafana`  to deploy the Grafana against the copied schema.

**Environment**: k8s
- Grafana version: 9.3.6
- Data source type & version: MySQL 8.0.27-u2-cloud 
- OS Grafana is installed on: K8s
- User OS & Browser: Unbuntu (Linux)/Chrome
- Grafana plugins: default
- Others:

**Comment by iXingo** [comment]
**What I found from `migration_log` table is below:**

It alerted (renamed) the existing `user` table to `user_v1` and then created a new `user` table. But I fount this new user_v2 renamed the `account_id` to `org_id` and caused the problem
![image](https://user-images.githubusercontent.com/3634305/215386321-9cfd225d-f147-4921-9a22-4117e3696c2f.png)

**Comment by cn-pdale** [comment]
Did you ever find a solution for this?
I got the same error when I upgraded to the latest docker version (OSS) and use an external Postgres DB.
