### ISSUE TITLE
Alerting Annotation improvements

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6244]
- [x] Make alert state visible (different colored lines/icons to start with)
- [x] Clear alert annotations from alert history view
- [ ] Clear alert annotations when alert is deleted

**Comment by utkarshcmu** [comment]
Can alerting annotations be optional?

**Comment by torkelo** [comment]
not right now, @utkarshcmu why? would you want to disable it? They are stored in Grafana db

**Comment by utkarshcmu** [comment]
If a service is flipping and producing too many alerts then the graph becomes messy and overloaded with alerting annotations(for example 20-25 alerts in an hour coming from the same graph or panel). IMO, panel border indicator and alert current state indicator(heart indicator) in the title are more than enough to show the current state. Also, if someone wants to see the history of the alerts, then they can always see it under Alerts tab.

So, if alerting annotations are made optional, users can see the current state without overloading the graph with more lines and colors. By default, it can be kept on but if a user has an option to disable them, then the users who does not want their graphs to be overloaded with more lines and colors can still see the graph clearly.

Here are the screenshots of heavy annotations and no annotations on a graph from play.grafana.org

<img width="698" alt="screen shot 2016-10-12 at 7 09 20 am" src="https://cloud.githubusercontent.com/assets/1019609/19313284/d00f00d0-904a-11e6-9a10-23bd75c03b74.png">

<img width="708" alt="screen shot 2016-10-12 at 7 06 58 am" src="https://cloud.githubusercontent.com/assets/1019609/19313285/d016e5ca-904a-11e6-9a3b-7b7f5ebb0cc1.png">

**Comment by torkelo** [comment]
seems like a badly designed alert rule / thresholds that flip flops that heavily :)  but I see your point.
