### ISSUE TITLE
No data for RAM used in gauge

### ISSUE THREAD

**Issue by zeleniy** [grafana/grafana#62452]
![no-data-for-ram-used-in-gauge](https://user-images.githubusercontent.com/2780617/215450391-69fd2b52-c750-4c19-8f66-826c68ceccab.jpg)

**Comment by mellieA** [comment]
@zeleniy can you share more information about the relationship between the two panels highlighted here? 

The RAM Used gauge, if you edit that panel and click on inspector or change the visualization type is there data?

**Comment by zeleniy** [comment]
> can you share more information about the relationship between the two panels highlighted here?

Unfortunately i know nothing about panels relationships. And how it works at all. Have one more screenshot:

<img width="1280" alt="Screen Shot 2023-01-31 at 10 03 40 AM" src="https://user-images.githubusercontent.com/2780617/215679811-3f8506d4-2e7f-4ee4-8a67-adfbb2da4d5a.png">

 Execution of **A** query returns some data:

```
((node_memory_MemTotal_bytes{instance="217.23.158.85:9100",job="sudostroenie.info"} - node_memory_MemFree_bytes{instance="217.23.158.85:9100",job="sudostroenie.info"}) / (node_memory_MemTotal_bytes{instance="217.23.158.85:9100",job="sudostroenie.info"} )) * 100
```
```
{instance="217.23.158.85:9100", job="sudostroenie.info"}
```
Execution of **B** data end up with no data:
```
100 - ((node_memory_MemAvailable_bytes{instance="217.23.158.85:9100",job="sudostroenie.info"} * 100) / node_memory_MemTotal_bytes{instance="217.23.158.85:9100",job="sudostroenie.info"})
```
```
Empty query result
```
But i don't know what that queries is and why them two. Also one image of **Edit**:

<img width="1280" alt="Screen Shot 2023-01-31 at 10 11 24 AM" src="https://user-images.githubusercontent.com/2780617/215680766-aeb3fd71-d0af-490d-a41f-06cf9605ae3b.png">

And a little bit about data:

<img width="1280" alt="Screen Shot 2023-01-31 at 10 14 18 AM" src="https://user-images.githubusercontent.com/2780617/215681249-aeb3ebb9-f1aa-46ee-84d8-6f376b089b4a.png">
