### ISSUE TITLE
Unified Alerting not deduplicating alerts

### ISSUE THREAD

**Issue by vincent-olivert-riera** [grafana/grafana#62453]
- Grafana version: 9.3.0

---

I'm running various Grafana servers as Docker containers, using Docker's default network mode, which means they get an IP within the 172.17-172.31 range (this information will be important later).

I configure Alerting High Availability as per the [docs](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/) (this is only the config in one server):
```
[unified_alerting]
enabled = true
ha_listen_address = "0.0.0.0:9094"
ha_peers = "172.17.0.100:9094,172.17.0.200:9094"
ha_advertise_address = "172.17.0.100:9094"
```
Similar for the other server, with the only difference of the `ha_advertise_address` which is `172.17.0.200:9094`.

With that, alert notifications are not properly deduplicated and they end up being sent twice.

A workaround to this is to use host network mode in Docker (`--net=host`), and with that, alerts are properly deduplicated.

---

Why is this happening?

I think this is happening because the underlying Alertmanager that Grafana runs is not able to find its cluster peers. According to Alertmanager's [README](https://github.com/prometheus/alertmanager/blob/main/README.md)...
> The `--cluster.advertise-address` flag is required if the instance doesn't have an IP address that is part of [RFC 6890](https://tools.ietf.org/html/rfc6890) with a default route.

And the Docker's default network range that we mentioned at the beginning is not part of it. According to [IANA](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml), it is part of RFC1918 instead.

Taking that into account, the `--cluster.advertise-address` must be used in Grafana's underlying Alertmanager in order to work properly.

---

Summarizing.

- I think the value of `ha_listen_address` in Grafana's config file should be passed to the underlying Alertmanager to be used as the value for the `--cluster.listen-address` option.
- I think the value of `ha_advertise_address` in Grafana's config file should be passed to the underlying Alertmanager to be used as the value for the `--cluster.advertise-address` option.

**Comment by mellieA** [comment]
@vincent-olivert-riera thanks for opening this issue. I'm moving this to our alerting squad to take a look.

I've noticed a discrepancy in the settings mentioned in the [doc](https://grafana.com/docs/grafana/next/alerting/set-up/configure-high-availability/#before-you-begin) and the example given further down the page for kubernetes and wonder if this is a doc issue or a product issue. I'll let the squad weigh in. 

> [unified_alerting]
enabled = true
ha_listen_address = "${POD_IP}:9094"
ha_peers = "grafana-alerting.grafana:9094"
ha_advertise_address = "${POD_IP}:9094"

**Comment by santihernandezc** [comment]
Hi @vincent-olivert-riera, how are you setting up your networking in Docker? Are you using Docker Compose or any other tools? We would like to know how you ended up with those IP addresses.
The behavior you're describing is what we'd expect to see if your containers aren't able to communicate with each other.

**Comment by santihernandezc** [comment]
About your suggestions, this is where we're passing `ha_listen_address` and  `ha_advertise_address` to the underlying Alertmanager.
https://github.com/grafana/grafana/blob/20ec54f1f9138b3f59a0fe341abb8ed4d124b85e/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L83-L84

**Comment by vincent-olivert-riera** [comment]
From: https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/#before-you-begin

> Since gossiping of notifications and silences uses both TCP and UDP port 9094, ensure that each Grafana instance is able to accept incoming connections on these ports.

My mistake was that I forgot to bind the **UDP** port in the Grafana containers.

Sorry for the noise.
