### ISSUE TITLE
Glue: Create  a simple test data scenario to test, develop and demonstrate correlations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#62462]
### Background

It's hard to quickly demonstrate data links for various use cases without a cumbersome setup of different data sources. Also not all use cases are supported yet, though we can start adding some simple use cases that will already be beneficial for testing. In the future we can add more scenarios to have full metrics/logs/traces journey covered (https://github.com/grafana/grafana/issues/57449)

### Requirements ###

High level: _Create test data scenarios for basic correlations usage_

#### Technical details

There should be a scenario that generates a simple log line that user can extract data from, and a scenario where such data can be added to.

(1) Source data scenario (logs): Scenario generating simple log lines in logfmt with various strings that can be extracted to variables. Not all logs should contain all key/value pairs, e.g.:

```
time=... app=foo request=/login traceId=123
time=... app=foo event=restarted
```

(2) Target data scenario (graph): Scenario that allows adding values from log lines to generate a graph with values in the legend (maybe we can reuse something that already exists)

#### To Do
- [ ] Scenario for source data
- [ ] Scenario for target data

🚧 Outstanding questions

* ...

<details><summary>DoR checklist</summary>

- [ ] Should our squad work on it?  ***Yes, we own the feature***
- [ ] Why is it important?  ***It will be used for development, testing and demonstrations***
- [ ] Dependencies: ***No.***
- [ ] Priority: ***Low***
- [ ] Functional requirements. ***Yes, just two scenarios needed, but up the the dev working on this to provide the data that will suit our needs***
- [ ] Non-functional requirements . ***N/A***
- [ ] Documentation requirements. ***Not needed.***
- [ ] UX design / approval. ***N/A (no new UX/UI)***
- [ ] Technical design / approval.  ***Not needed.***
- [ ] How will the outcome value of the feature be measured? ***We already have tracking for split view, we can track the usage.***
- [ ] Should we write a blog post about it?  ***No***
</details>

**Comment by gelicia** [comment]
To provide some clarification, this task is to set up a test data scenario between some popular datasources, and #57449 is about setting up test scenarios within the test datasource.

**Comment by gelicia** [comment]
Correlation Demo 1: Set up testdata datasource, demonstrate CSV Content and USA generated data scenarios, create correlation where state abbreviation from USA generated data opens up CSV Content scenario with state abbreviation carried over.
https://github.com/grafana/grafana/assets/1533128/5a8161a3-7c8f-4258-843b-866a5cd8521c

Correlation Demo 2: 
Demonstrate Logs scenario, create correlation where log's uname property is taken from the field via the logfmt transformation and moved to the CSV content scenario.
https://github.com/grafana/grafana/assets/1533128/87097ca0-fcd4-49ed-afb6-f21733019b46

**Comment by gelicia** [comment]
The issue with going from any test scenario to a graph, is all our graph scenarios do not seem to be queryable in a way that can take variables. For example the USA generated data would be perfect for this, but the droplist of state names does not let you type in and enter a `${variable}` value that would let you filter it for a correlation.

**Comment by gelicia** [comment]
We are moving this further forward with #69929.
