### ISSUE TITLE
InfluxDB + Grafana Alerts  throws 400 Bad request with latest nightly

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#6247]
* **I'm submitting a ...**
- Bug report
Please include this information:
- What Grafana version are you using?
grafana-4.0.0-1476202643pre1.linux-x64.tar.gz
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Linux -generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

- What did you do?
I installed nightly build of grafana-4.0.0-1476202643pre1.linux-x64.tar.gz, created influxdb datasources (i saw connection success message) and imported dashboards created in grafana-3.0.2-1463383025 to grafana-4.0.0-1476202643pre1.linux-x64.tar.gz

I created few templated dashboards and they are working fine.

I set up and Alert 
<img width="1394" alt="screen shot 2016-10-12 at 2 21 38 am" src="https://cloud.githubusercontent.com/assets/406777/19304699/a433d738-9022-11e6-9775-b749740fd46d.png">

Test Alert Fails with 400 bad request.

<img width="1346" alt="screen shot 2016-10-12 at 2 21 59 am" src="https://cloud.githubusercontent.com/assets/406777/19304717/b60ae460-9022-11e6-8fd3-79adeaad41b8.png">

- What was the expected result?

Was expecting alert to work with InfluxDB as there was an option to create one.

- What happened instead?
400 Bad Request error

1. As alert tab was enabled, and grafana allowed to be create alert given i was using influxDB panel data source. i assumed that alerting is supported with grafana. Is it not ?

2. How does alerting work with templated dashboards. For combination 1 a metric & its alert makes sense and for other combination of filters it does not.

Does grafana alerting support templated dashboards ?

3. I was allowed to create only one kind of alert and not like warn & critical like its shown on few alert examples. is it not supported for influxbd ?

**Comment by discoduck2x** [comment]
@deepujain template vars no supported for alreting currently , dont know if or when they will be

**Comment by bergquist** [comment]
As @discoduck2x said template variables are not supported in alerting. 

Wouldn't you want to monitor all groups rather then then only the one your viewing in the graphs?
Templated variables are great for reducing noise in dashboards but I think it would be dangerous to only alert on the result from those queries since you might miss data. We are not sure about how we want to treat template variables in alerting yet.

**Comment by discoduck2x** [comment]
@bergquist well i think having static queries kind of takes away flexibility, imagine you have X hosts/devices that suddenly are taken off from lets say a loadbalancing setup due to say mainenenc then id just deselect them in a temp var dropdown , ,, that solves not having to disable the whole alerting for that graph or changing the query to not include them..also changing that back would be timeconsuming.. dont know if i make sense?

**Comment by torkelo** [comment]
@discoduck2x we will introduce flexible silencing rules for that case

**Comment by deepujain** [comment]
@bergquist 

Templating solves the need to create individual dashboards for every group. And one can simply create one single dashboard with templates (filters).

I do want to monitor every group and metric value is different for each group and so is alert thresholds. Since my current dashboard is built around templates , how do i get alerting to work ?

1. I have 8*10 groups , so do i create 80 different dashboards. 
2. Each dashboard has 40 graphs. 
3. Do i need to create 80*40 alerts ? It does not scale. That is a different problem.

So if i have a single graph, does alerting work with InfluxDB ?

**Comment by discoduck2x** [comment]
@deepujain , just dont use $templatevariable in your grafana metric query

@torkelo but since (at least i think)most ppl prob use template variables in their dashboards today - by doing it the way you describe or the way that sounds to me will force them to rebuild dashboards for alerting purposes and filter those in a new way but keep temp vars for "eye candy" type dashboards..?

**Comment by torkelo** [comment]
Alerting focused dashboards sounds like a good idea so not a bad thing, supporting templating would be incredibly complicated and non obvious how it would work, would the alert re be executed for each value in template variable? Every combination? Just current?

**Comment by torkelo** [comment]
Alerting focused dashboards sounds like a good idea so not a bad thing, supporting templating would be incredibly complicated and non obvious how it would work, would the alert re be executed for each value in template variable? Every combination? Just current?

**Comment by deepujain** [comment]
I created a new dashboard specifically for alert. and to test with InfluxDB.


Grafana Build :  grafana-4.0.0-1476271887pre1
InfluxDB : Latest build.

As alerting with Grafana does not yet support Templates, i created a single graph for a single query.

SELECT distinct("HDFS_BYTES_READ_MAP") FROM "productionjobs" WHERE jobName =~ /EP-DETAILSERVICE-QTSESS{0,1}[a-zA-Z0-9-]*step_3_of_4_1[a-zA-Z0-9_]*/ AND state = 'SUCCEEDED' AND $timeFilter GROUP BY time($interval), "jobName" fill(none)

When i run test alert, I see result as false. For testing purpose, i flipped the condition assuming it will return true, but it continued to return false.


![screen shot 2016-10-12 at 12 56 09 pm](https://cloud.githubusercontent.com/assets/406777/19326970/a93b849c-9081-11e6-86dd-31e3e13023b6.png)

Question
1. When i run Test Rule with avg query, should it not simple compute average of the current time range data points and 

2.  What does the condition mean ?

Does it run Query A and override the time parameters ?

3. When i test i see below error in Grafana.


t=2016-10-12T12:54:46-0700 lvl=eror msg="Failed to extract alerts from dashboard" logger=alerting.extractor error=nil

t=2016-10-12T12:54:46-0700 lvl=eror msg="Failed to test rule" logger=context userId=1 orgId=2 uname=admin error="Could not find alert with panel id 1"

t=2016-10-12T12:54:46-0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=2 uname=admin method=POST path=/api/alerts/test status=500 remote_addr=10.246.241.104 time_ms=2ns size=33

**Comment by discoduck2x** [comment]
@torkelo just current i think? as "include all option" is what i usually have, but to be able to exclude or implicitly include is what makes it magical. if you say its very complicated to have it that way then i wont argue - im just very happy its in beta and the day when i can finally kick out nagios for most monitoring / alerting im buyin you champage :) thanks for the great work !
