### ISSUE TITLE
Can't add Annotations in latest Releases 9.3.1 and 9.3.4

### ISSUE THREAD

**Issue by jogrothe** [grafana/grafana#62470]
**What happened**:
- Cant't add Annotations in latest grafana releases 9.3.1 and 9.3.4. 
- The latest version, where this was working for me is 9.2.5, to which I fall back, after testing new releases.
- Not working in uptodate browsers firefox and chrome.

**What you expected to happen**:
Left click in panel should show **[ Add anotation ]** popup.
![20230130-131241-MQTT - Dashboards - Dashboards - Grafana – Mozilla Firefox v01](https://user-images.githubusercontent.com/38055293/215475464-c43b0a99-ca2d-4ab3-a481-302c9489653c.png)

**How to reproduce it (as minimally and precisely as possible)**:
Just open a dashboard and left click onto a panel.

**Anything else we need to know?**: %

**Environment**:
- Grafana version: 9.3.1 and 9.3.4
- Data source type & version: MySQL 8.0.31
- OS Grafana is installed on: Windows 10 Pro 22H2 64bit
- User OS & Browser: Windows 10 Pro 22H2 64bit – uptodate firefox / chrome
- Grafana plugins: %
- Others:

**Comment by mellieA** [comment]
@jogrothe annotations were changed with https://github.com/grafana/grafana/pull/57481 

You can turn them on by going to dashboard settings > annotations > add annotation for your datasource & click the enable check box. The change was made after we [heard a lot of feedback from users](https://github.com/grafana/grafana/issues/25580) annotations should only show for datasources when it's configured: 

![Screenshot 2023-01-30 at 3 53 54 PM](https://user-images.githubusercontent.com/18175287/215614877-36115b89-b7c0-47be-bd0d-69552254295b.png)

**Comment by jogrothe** [comment]
@mellieA 

Thanks for helping and clarifying the background! Annotations are now working as expected. Just tried with the new release 9.3.6.
