### ISSUE TITLE
[Feature Request] InfluxDB 1.0 multiple fields in templating support

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6248]
Hi,

Is it possible to add support for multiple fields selection using template variables for InfluxDB 0.9/1.0?  
Now selecting two or more fields produces a regex OR in SELECT query between each field which looks like below:

`SELECT mean("variable1|variable2") FROM "measurements" WHERE time > now() - 24h AND "tag1" = 'test' GROUP BY time(1m) fill(null)`

According to InfluxDB 1.0 documentation (https://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#the-basic-select-statement) multiple fields in the SELECT query should be comma separated only. Regex is supported only for MEASUREMENTS and TAG names but not for the FIELDS in the MEASUREMENT table that were introduced in InfluxDB 0.9. The above query should look like below then:

`SELECT mean("variable1"), mean("variable2") FROM "measurements" WHERE time > now() - 24h AND "tag1" = 'test' GROUP BY time(1m) fill(null)`

Now it's not possible to use templating variable with multi-value option which I guess should work properly since Grafana has added support for new InfluxDB 0.9/1.0 architecture?
What do you think about this?

**Comment by bergquist** [comment]
Could you describe a use case where you want to use different variables using templates?

**Comment by pavleec** [comment]
It's very simple use case - let's assume that I have the following InfluxDB data:

```
database_name: mydb
measurements table:mystats
fields_names:
variable1
variable2
variable3
other_stat1
other_stat2
```

Then I would like to use Grafana template variable with multi-value option enabled which would list all of the above fields using:
`SHOW FIELD KEYS FROM "mystats"`

![aaa](https://cloud.githubusercontent.com/assets/12551929/19310148/010d343e-9089-11e6-8641-80b9ff4fdb75.jpg)

Then from the dropdown variable menu I would like to be able to select one or many variables and display them on one graph panel using the following InfluxDB query:

`SELECT mean("$variable") FROM "mystats" WHERE time > now() - 24h AND "tag1" = 'test' GROUP BY time(1m) fill(null)`
For instance when variable1 and other_stat1 are selected the above query should expand to:

`SELECT mean("variable1"), mean("other_stat1") FROM "mystats" WHERE time > now() - 24h AND "tag1" = 'test' GROUP BY time(1m) fill(null)`

The Graph panel should like like below:
![aaa](https://cloud.githubusercontent.com/assets/12551929/19310528/ca259950-908a-11e6-85b1-e82cee569969.jpg)

**Comment by gdubicki** [comment]
I would stick with this regexp approach described in #6590 as choosing the fields using regexp is simpler and will, as you mentioned, @torkelo, work with aggregated functions.


I have tested current situation on Influx 1.2.0 and Grafana v4.1.2 (commit: v4.1.2):

"metrics" is my multi-selectable variable containing list of fields.

When I choose "metrics" variable in SELECT part of the query using visual edit mode I get the following query:

```
SELECT mean("/^$metrics$/") FROM "reports" WHERE $timeFilter GROUP BY time($interval) fill(null)
```

..and it doesn't work. But if you only remove the double quotes aroung the `/^$metrics$/`:

```
SELECT mean(/^$metrics$/) FROM "reports" WHERE $timeFilter GROUP BY time($interval) fill(null)
```

..it starts to work!

So it seems really simple to fix. I am considering creating a PR myself, but I am afraid that it would take more time to set up Grafana dev env that actually coding, so perhaps one of core devs could solve it quickly?

**Comment by elvarb** [comment]
I used the same work around few months ago like @gdubicki. Works very well.

**Comment by gdubicki** [comment]
Well, I just stumbled upon a weakness in this approach - if you choose at least 2 fields in your variable, let's say "foo" and "bar", and have fields like: "bar", "foo", "foo_something" and "foo_something_else" then all 4 will be selected by the regexp-ed query. :( Note that this doesn't happen if you choose only 1 field.

**Comment by amoussoubaruch** [comment]
Hi,
I start to use grafana and i want to create a template variable for a field with categorial value. 
I'm using influxdb for data source. I have a field hostname with 10 differents names. i want a dropdown for select in. In grafana documentation, they mentionne only the quety for select a tag. 
is possible to do that for field also? 
`SHOW TAG VALUES WITH KEY = "hostname"`
so i use this query `SHOW FIELD KEYS from metrics` i get all field of my database. that is not i want. i want to get all categorial value for specific field.

**Comment by daniellee** [comment]
@amoussoubaruch does not look like it is possible but there are some workarounds. See #5013

**Comment by laimaretto** [comment]
@amoussoubaruch you need to use the Regex to select which fields to show.

![image](https://user-images.githubusercontent.com/8891825/31203614-4c80ff58-a93e-11e7-977c-abbda3f9f68f.png)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Think with influxSQL going away being replaced with flux not sure this will be relevant 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
