### ISSUE TITLE
[Bug] Escaping values in template queries with Prometheus data source breaks

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#6250]
Grafana v3.1.1 (commit: a4d2708) with Prometheus 1.2.1 on CentOS

I am using a template query and the request in the background is wrong:

`label_values(power_consumption_joule_total{datacenter="$datacenters",room="$datacenter_rooms"},fuse)` -> `https://<foo>/api/datasources/proxy/1/api/v1/series?match[]=power_consumption_joule_total%7Bdatacenter%3D%22<bar>%22%2Croom%3D%22SV3%5C%5C.2%22%7D&start=1476184997.709&end=1476271397.709`

`label_values(power_consumption_joule_total{datacenter="$datacenters",room="SV3.2"},fuse)` -> `https://<foo>/api/datasources/proxy/1/api/v1/series?match[]=power_consumption_joule_total%7Bdatacenter%3D%22<bar>%22%2Croom%3D%22SV3.2%22%7D&start=1476184984.963&end=1476271384.963`

`$datacenter_rooms` is, of course, "SV3.2".

As you can see, the literal dot is a literal dot. In the template value version, it's replaced with `%5C%5C.`

**Comment by torkelo** [comment]
Make sure the template variable have "All" and "Multi value" disabled. If any of these two options are enabled you must use regex operator in your prometheus query.

**Comment by RichiH** [comment]
This is arguably still a bug in the escaping; alternatively, there should at least be a warning in the UI as this is highly non-obvious and quite easy to miss.

In case of `sum()` being used in PromQL, it's more or less impossible to detect errors, but the displayed data can be fundamentally, or subtly, wrong.

**Comment by torkelo** [comment]
why bug? if not escaping then multi value will generate error

**Comment by torkelo** [comment]
but I agree some info on how it works in the UI would be good

**Comment by RichiH** [comment]
A bug because this even breaks when the multi-value has only one return value.

I agree that `foo="bar|baz"` can not work, but `foo="bar"` should work.

Could you re-open this issue for now?

**Comment by torkelo** [comment]
yes, foo="bar" will work, but then you do not need multi value / all value selected
