### ISSUE TITLE
latest grafana docker is broken

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6251]
```
$ docker pull grafana/grafana
Using default tag: latest
latest: Pulling from grafana/grafana

357ea8c3d80b: Already exists 
a3ed95caeb02: Already exists 
4b548398264d: Already exists 
23d0506862b0: Already exists 
Digest: sha256:60a77e56dd621e8009880bd8f9e298d182cf8914305f9ea34a0afb79cb1f7804
Status: Image is up to date for grafana/grafana:latest
```

when I run the image and login, I get brokenness like this: (this is after clicking "add datasource")
![graf-docker-broken](https://cloud.githubusercontent.com/assets/20774/19308724/c3f36784-9089-11e6-8c95-28f4d4058701.png)

grafana version is commit: a4d2708 (a commit from aug1 ?)

**Comment by Dieterbe** [comment]
note: I get the exact same error with grafana/grafana;master , which shows ` Grafana v4.0.0-pre1 (commit: 0f2fa33)` in the UI :|

**Comment by Dieterbe** [comment]
update: strangely, it works in firefox. but not in chrome.

**Comment by torkelo** [comment]
strange, cannot replicate in chrome nor in firefox. That docker container has been used by thousands (the :latest one, which is 3.1.1)

**Comment by torkelo** [comment]
what version of chrome are you using?

**Comment by Dieterbe** [comment]
Version 53.0.2785.143 (64-bit)
chromium.
might be a bit more bleeding edge since i use arch linux which always installs the latest releases which sometimes have issues which then get solved before other distro's get updated

**Comment by torkelo** [comment]
ok, looks like a bug in chromium, it can be a bit buggy
