### ISSUE TITLE
Influx DB connection failure home assistant

### ISSUE THREAD

**Issue by teozfrank** [grafana/grafana#62524]
**What happened**:

Influx db connection cannot be established.

**What you expected to happen**:

Connection to Influx db should work.

**How to reproduce it (as minimally and precisely as possible)**:

Connection details in homeassistant (working)

![image](https://user-images.githubusercontent.com/3265598/215599709-7f2b1d13-74af-45a4-a2e3-d8cb7f0e96f3.png)

Connection details in graphana (not working):

![image](https://user-images.githubusercontent.com/3265598/215599430-44f0c31e-bec7-447c-bb56-9a1545f08bcc.png)
![image](https://user-images.githubusercontent.com/3265598/215599513-38febcfa-67d7-438c-b525-e551b81e740a.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4 - 64017e8ca6
- Data source type & version: InfluxDB 1.9.4
- OS Grafana is installed on: Home Assistant 2023.1.7, Operating System 9.5
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: Default
- Others:

**Comment by teozfrank** [comment]
Just re-tried save and test and works now. strange:

![image](https://user-images.githubusercontent.com/3265598/215602473-f609c89d-9450-4da9-9db4-d2d8fb5ee654.png)

Does graphana have a log in home-assistant?

**Comment by mellieA** [comment]
I'm glad it's working now!

The grafana log location can be configured with these settings: 

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#log
