### ISSUE TITLE
Cannot add a user to an organization

### ISSUE THREAD

**Issue by vincent-olivert-riera** [grafana/grafana#62531]
- Grafana version: 9.3.0

---

As a server admin, I want to add myself (or any other user) to an organization. I follow the official [documentation](https://grafana.com/docs/grafana/latest/administration/user-management/server-user-management/add-remove-user-to-org/#add-a-user-to-an-organization) , so I do:

1. Sign in to Grafana as a server administrator.
2. Hover your cursor over the Server Admin (shield) icon until a menu appears, and click Users.
3. Click a user.
4. In the Organizations section, click `Add user to organization`.

The problem is that the `Add user to organization` button does not exist.

---

![image](https://user-images.githubusercontent.com/6151586/215645142-c1f78780-e102-466f-a78b-277b0e2b6689.png)

**Comment by RamjiRamachandran** [comment]
Hi @vincent-olivert-riera , 

Looks like issue exist in 9.3.0 version, Community removed the package from windows download "No Windows packages available for this release."

It's working fine in 9.3.2 version, as we expected. Advice to use 9.3.2, it contains few vulnerability fix. Please find below for the screenshot 9.3.2 version
 
![image](https://user-images.githubusercontent.com/50236001/215682271-0c5729e7-ae49-4eba-9eef-5b22ea55cbf2.png)

**Comment by mellieA** [comment]
@vincent-olivert-riera the community post @RamjiRamachandran mentioned is [here](https://community.grafana.com/t/add-user-to-organisation-is-missing-after-9-1-0/70630)

Summary: use the setting [oauth_skip_org_role_update_sync](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#oauth_skip_org_role_update_sync) with grafana 9.3.x to get the button back

Community post answer: 
> The legacy external auth behavior has been that changes were allowed in the UI, but then the next time the user logged in via an external provider their settings would be overwritten by the external authentication configuration.
> 
> The new behavior introduced by [#52160](https://github.com/grafana/grafana/pull/52160) is that the buttons in the UI will disappear if the user is added by external authentication so there isn’t a false impression that the admin can use the UI to manage the user’s role persistently.
> 
> It seems that lots of users were relying on the ability to temporarily override a user’s role. This new PR adds a configurable setting that will disable the role_sync behavior and allow an admin to manage the role in the UI - [#55182](https://github.com/grafana/grafana/pull/55182)

**Comment by vikasedulab** [comment]
all button show but getting error like org not found and all but i create orgnazation already still getting same issue
