### ISSUE TITLE
set isAdmin via HTTP API

### ISSUE THREAD

**Issue by sni** [grafana/grafana#6253]
* **I'm submitting a ...**
- [X] Bug report
- [] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I am currently using latest Grafana v3.1.1 with Influxdb and Prometheus. I wanted to add an grafana admin via the http api but there is no documented way to do so. It is possible to read the isAdmin Flag, but no documented way to change it. This would be very helpful when trying to synchronize the grafana users with other sources.

Looking at the admin panel with Firebug, it seems like it is possible with /grafana/api/admin/users/<nr>/permissions but the relevant information is missing on: http://docs.grafana.org/reference/http_api/#permissions

Thanks

**Comment by torkelo** [comment]
http://docs.grafana.org/http_api/admin/#permissions

**Comment by sni** [comment]
Exactly thats what i meant, there is no word about setting the isAdmin flag. It's just an empty PUT request in the example.

**Comment by torkelo** [comment]
ah, the example body looks to be missing. Just do it from the admin ui while chrome dev tools network tab is open and you will see the API call
