### ISSUE TITLE
InfluxDB + Grafana Alerts  throws 400 Bad request with latest nightly (Non templated query)

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#6254]
I'm submitting a ...
Bug report Please include this information:
What Grafana version are you using? grafana-4.0.0-1476202643pre1.linux-x64.tar.gz
What datasource are you using? InfluxDB
What OS are you running grafana on?
Linux -generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

What did you do?
I installed nightly build of grafana-4.0.0-1476202643pre1.linux-x64.tar.gz, created influxdb datasources (i saw connection success message) and imported dashboards created in grafana-3.0.2-1463383025 to grafana-4.0.0-1476202643pre1.linux-x64.tar.gz

I created few templated dashboards and they are working fine.

I set up and Alert 

QEURY: SELECT distinct("HDFS_BYTES_READ_MAP") FROM "productionjobs" WHERE jobName =~ /EP-DETAILSERVICE-QTSESS{0,1}[a-zA-Z0-9-]*step[a-zA-Z0-9_]*/ AND state = 'SUCCEEDED' AND $timeFilter GROUP BY time($interval), "jobName" fill(none)

No template variables here.

<img width="1390" alt="screen shot 2016-10-12 at 8 30 40 am" src="https://cloud.githubusercontent.com/assets/406777/19316415/302bb62e-9056-11e6-84ab-324c2ac2bcc8.png">

This metric captures input to this particular M/R job. If it goes below 900GB , i want a alert.

When i do a test run, i see
<img width="960" alt="screen shot 2016-10-12 at 8 31 27 am" src="https://cloud.githubusercontent.com/assets/406777/19316450/530ab6fe-9056-11e6-8331-928bc5b3b73c.png">

error tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request

Is alerting not supported for InfluxDB or am i doing something incorrect ?

**Comment by deepujain** [comment]
<img width="1332" alt="screen shot 2016-10-12 at 8 33 48 am" src="https://cloud.githubusercontent.com/assets/406777/19316534/9d99ad42-9056-11e6-8c90-419f98892f1e.png">


Coming to Notification tab, is it a email notification or slack or something else ? 
How do i know so that i configure it correctly ?

I did not go through documentation, was hoping alert tab will be self explanatory.

**Comment by deepujain** [comment]
Even when i modified the query to show a single line (graph) and test alert, i still get error.

<img width="1390" alt="screen shot 2016-10-12 at 8 36 12 am" src="https://cloud.githubusercontent.com/assets/406777/19316620/ff373718-9056-11e6-9b7b-d6cde1568231.png">

**Comment by deepujain** [comment]
I am trying to build grafana dashboard to monitor M/R jobs (100 of them) and use alert to notify in case a particular M/r job generated way less output. (This can happen due to data corruption in upstream) and we want to catch it at the earliest stage in our processing pipeline.


<img width="1385" alt="screen shot 2016-10-12 at 8 38 57 am" src="https://cloud.githubusercontent.com/assets/406777/19316702/56702ec2-9057-11e6-94c4-2e4d45a279d8.png">


Alerting can really make some difference. Slack notification here will be a beast 👍

**Comment by torkelo** [comment]
try a newer build that supports raw queries (in alerting)

**Comment by torkelo** [comment]
@deepujain we already have slack notifications

**Comment by torkelo** [comment]
@deepujain you need to go to alerting main side nav, then subnav Notifications, there you can add notifications of different types (email, webhook, slack)

**Comment by torkelo** [comment]
if you have configured an image  store provider in your grafana.ini you will get images as well in your slack / email notifications:

 ```
#################################### External Image Storage ##############
[external_image_storage]
# You can choose between (s3, webdav)
provider =

[external_image_storage.s3]
bucket_url =
access_key =
secret_key =

```

**Comment by leucos** [comment]
I reproduced the initial problem with todays nightly build (Version 4.0.0-pre1 (commit: 16e7bfc) / 4.0.0-1478503472pre1)

I seems that, given the following query:

`SELECT percentile("rtime", 99.99) FROM "haproxy" WHERE "host" =~ /^haproxy/ AND "proxy" = 'bk' AND time > now() - 1m GROUP BY time(50ms) fill(null)`

the alert code produces the following query:

`SELECT percentile("rtime", 99.99) FROM "haproxy" WHERE "host" =~ '/^haproxy/' AND "proxy" = 'bk' AND time > now() - 1m GROUP BY time(50ms) fill(null)`

(note the single quotes added around `/^haproxy/` regex.

This is not supported by InfluxDB which does not like quotes around regexps:

```
> SELECT percentile("rtime", 99.99) FROM "haproxy" WHERE "host" =~ '/^haproxy/' AND "proxy" = 'bk' AND time > now() - 1m GROUP BY time(50ms) fill(null)
ERR: error parsing query: found /^haproxy/, expected regex at line 1, char 65
> SELECT percentile("rtime", 99.99) FROM "haproxy" WHERE "host" =~ /^haproxy/ AND "proxy" = 'bk' AND time > now() - 1m GROUP BY time(50ms) fill(null)
name: haproxy
-------------
time			percentile
1478518674700000000	
1478518674750000000	
...
```

So I guess this issue should be re-opened.

**Comment by torkelo** [comment]
can you show your panel json?

**Comment by leucos** [comment]
Sure
```
{
  "id": 53,
  "title": "Loadbalancer latencies test",
  "tags": [
    "saturation",
    "errors"
  ],
  "style": "dark",
  "timezone": "browser",
  "editable": true,
  "sharedCrosshair": true,
  "hideControls": false,
  "time": {
    "from": "2016-11-07T09:59:49.103Z",
    "to": "2016-11-07T11:59:49.103Z"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "templating": {
    "list": []
  },
  "annotations": {
    "list": []
  },
  "refresh": false,
  "schemaVersion": 13,
  "version": 0,
  "links": [],
  "gnetId": null,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "isNew": false,
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "d8",
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {},
          "id": 3,
          "isNew": true,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "99.99pct",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "haproxy",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "rtime"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [
                      "99.99"
                    ],
                    "type": "percentile"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=~",
                  "value": "/^haproxy/"
                },
                {
                  "condition": "AND",
                  "key": "proxy",
                  "operator": "=",
                  "value": "bk"
                }
              ]
            }
          ],
          "thresholds": [
            {
              "value": 100,
              "op": "gt",
              "fill": true,
              "line": true,
              "colorMode": "critical"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Response time (all servers)",
          "tooltip": {
            "msResolution": true,
            "shared": true,
            "sort": 0,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "ms",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "alert": {
            "conditions": [
              {
                "type": "query",
                "query": {
                  "params": [
                    "A",
                    "5m",
                    "now"
                  ]
                },
                "reducer": {
                  "type": "avg",
                  "params": []
                },
                "evaluator": {
                  "type": "gt",
                  "params": [
                    100
                  ]
                }
              }
            ],
            "noDataState": "no_data",
            "frequency": "60s",
            "handler": 1,
            "notifications": [],
            "name": "Response time (all servers) alert"
          }
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "Loadbalancer latencies",
      "titleSize": "h6"
    }
  ]
}
```

**Comment by torkelo** [comment]
thanks, opened new bug for this case, https://github.com/grafana/grafana/issues/6488

**Comment by leucos** [comment]
Thanks you @torkelo
