### ISSUE TITLE
Alerting: Supporting PUT and POST requests in Webhook Notifications

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6255]
* **I'm submitting a ...**
- [    ] Bug report
- [ x ] Feature request
- [    ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Latest Build
- What datasource are you using? Graphite
- What OS are you running grafana on? Amazon Linux

Would like to make POST and PUT webhook calls with JSON data or any data.

**Comment by bergquist** [comment]
Might as well allow GET. I think think its the correct http verb but it might help some people to get thru firewalls :)

**Comment by bergquist** [comment]
Didnt add support for GET. That would just be weird.

**Comment by utkarshcmu** [comment]
@bergquist We should also have a text-area to enter the body of the post/put request.
