### ISSUE TITLE
No Docker tag latest if beta version

### ISSUE THREAD

**Issue by corasaniti** [grafana/grafana#62569]
Why do they keep tagging latest docker if it's still in beta?
Thanks

**Comment by nappy** [comment]
Its seems 8.1.4 has been tagged latest as of now.

**Comment by mellieA** [comment]
@nappy @corasaniti I just tested this out in my own docker environment, I had to pull the new image and then got 9.3.6

There is a related issue for the website [grafana.com: Make beta and test releases not stable](https://github.com/grafana/grafana/pull/58883 )

From what I can see, this was also updated in our release repo (private) to mark the latest stable release as latest. That change was merged in Nov.

**Comment by dsotirakis** [comment]
@mellieA 👋 
Current issue about docker images latest tag is fixed here https://github.com/grafana/grafana/issues/62589.
Will investigate more and see what's happening on the API side of things.

**Comment by mellieA** [comment]
Fixed in https://github.com/grafana/grafana/issues/62589
