### ISSUE TITLE
Support regex or fuzzy matching on rule names in the alerting rule search box.

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#62587]
The alerting rule interface now has a search box with a number of supported filters:
<img width="525" alt="Screenshot 2023-01-31 at 9 48 55 PM" src="https://user-images.githubusercontent.com/1951900/215778034-afee8dcc-32f1-4733-8c8b-53f0bbe47ee0.png">

Label filters can use regular expressions in some of their matching.

It would be really helpful to have either fuzzy (ideal to me) or regular expression matching available in the `rule:` filter. When there are many alerting rules, especially nested inside a rule group or folder, fuzzy matching can quickly help you zoom into the one you're looking for.

**Comment by leeoniya** [comment]
related: https://github.com/grafana/grafana/pull/62276

feel free to reach out for help/questions.
