### ISSUE TITLE
Multi Value option not working for CPU stats

### ISSUE THREAD

**Issue by gugansankar** [grafana/grafana#6263]
Grafana Version :  v3.1.0 (commit: v3.1.0)
Datasource : InfluxDB
OS : Ubuntu 16.04 LTS

I'm trying to show CPU stats in Grafana using templating feature. There is no issue in configuration.

But When I select "All" option in templating, it shows average value of all CPUs instead of showing each cpu stats in that single graph panel [ I don't prefer Row / Panel repeat option].I would like to show all CPU core stats shown on single graph panel itself.

Is it possible ?. Please help. thanks in Advance.

If you see the below graph, I have select "proc" as "All". But its not showing CPU1 and CPU2 stats separately. Instead it shows average value.

![selection_001](https://cloud.githubusercontent.com/assets/4958813/19345225/15a57a78-915b-11e6-9ef4-3551678f5bf3.png)

**Comment by torkelo** [comment]
read up on InfluxDB query language  and how it works :) 

https://docs.influxdata.com/influxdb/v1.0/

Tip: you need to group by a tag for it split the result for each value in that tag.
