### ISSUE TITLE
Improve notification policies view

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#62650]
The current notification policies view is rather inadequate, a few idea we could implement to improve the view are;

- Show the entire tree, no longer required to keep checking policies for child policies
- Show the instances currently handled by a particular route
- Visual aid to show if continue is configured for a route (now requires editing the policy to check)
- Group timings added to the overview, no need to uncollapse a policy
- Show warnings for routes that might handle all instances without "continue"
- Show any contact point errors for a policy
- Hover states (not shown) to show more info about metadata
- Colors are the same for matchers with the same key, making it easier to see what routes will use the same label keys 
- Show what properties are inherited from the parent policy

**Comment by konrad147** [comment]
Related (or even a duplicate) https://github.com/grafana/grafana/issues/39143

**Comment by gillesdemey** [comment]
WIP https://github.com/grafana/grafana/pull/61952

**Comment by gillesdemey** [comment]
Fixed in https://github.com/grafana/grafana/pull/61952
