### ISSUE TITLE
annotation query with template variable: elasticsearch query unexpected result

### ISSUE THREAD

**Issue by mbjelac** [grafana/grafana#6265]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Grafana version: `v3.1.1 (commit: a4d2708)`

- What datasource are you using?
Elasticsearch, Prometheus

- What OS are you running grafana on?
Centos 7

- What did you do?

    1. Created a dashboard.
    2. Created some graph panels with queries (all work).
    3. Created a template variable `x`.
    4. Used `$x` in graph panel queries (all work).
    5. Added an annotation with the ES datasource and the query `myattribute="$x"`.

- What was the expected result?
I expected the annotations to be shown from results of the specified query.

- What happened instead?
It appears annotations are shown for all results, as if the query was `*`.

NOTE: When my query is just `$x` or `$x AND someOtherStuff` the query works as expected.

**Comment by torkelo** [comment]
myattribute="$x"

not sure that is a valid lucene query, try myattribute:$x

**Comment by mbjelac** [comment]
Of course ... doh, sorry.
