### ISSUE TITLE
Elastic Data Source retrieves inconsistent data for alerts

### ISSUE THREAD

**Issue by SergioBernabe96** [grafana/grafana#62677]
Hi.

We have configured an Elastic Data Source which is working fine. We have compared the values with Kibana and it is retrieving the same values.

We decided to start using alerts based on that data, but unfortunately it is not working as expected. If we use the same queries to create an alert, we receive different data for the same query with the same data source in different alerts. 

Any idea why this is happening?

![Screenshot 2023-02-01 at 11 38 19](https://user-images.githubusercontent.com/76034973/216042058-8a53a781-d047-4bdb-a143-2fc484ebb5fe.png)

![Screenshot 2023-02-01 at 11 38 27](https://user-images.githubusercontent.com/76034973/216042071-212a8c7d-fff2-4c8b-bcab-6330f770d143.png)

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Elastic (7.10+)

**Comment by mellieA** [comment]
@SergioBernabe96 it may be due to the time range in the alert vs the query. Are you able to show the full query parameters for both?

**Comment by mellieA** [comment]
@SergioBernabe96 something else to consider is how many shards the elasticsearch index you're querying has - see [Elasticsearch docs - Consistent Scoring](https://www.elastic.co/guide/en/elasticsearch/reference/current/consistent-scoring.html#consistent-scoring)

**Comment by SergioBernabe96** [comment]
> @SergioBernabe96 it may be due to the time range in the alert vs the query. Are you able to show the full query parameters for both?

Both queries have this exact same configuration:
![image](https://user-images.githubusercontent.com/76034973/216322346-b6d3efa3-1baf-40e3-ab78-309a06a3dda1.png)



> @SergioBernabe96 something else to consider is how many shards the elasticsearch index you're querying has - see [Elasticsearch docs - Consistent Scoring](https://www.elastic.co/guide/en/elasticsearch/reference/current/consistent-scoring.html#consistent-scoring)

About this, correct me if I'm wrong but I thought the Data Source collected data from the origin and exposed it to be collected by alerts and dashboards. So once the data has been collected by the data source, how can that index configuration affect the data?  This is a very good point for cases where two data sources access the same index, but we only have one datasource which is being queried by two different alerts. Does take make sense?

Perhaps I just have a misconception about how data sources connect data between origin and alerts/dashboards.

Thank you very much in advance!

**Comment by mellieA** [comment]
@SergioBernabe96 it's been awhile but I wanted to answer your question. The reason I asked is the datasource send a query to Elasticsearch to retrieve the data collected there in the index. There are cases where you can get different results from the same query in ES depending on which ES shard responds to the query and what data is stored there. 

There is also some differences in the granularity of results in grafana depending on what interval and time range is selected for the query. For example, I see that both of your alerts are using a 1m interval. What is the time range that they are evaluating? For example "now-10m". 

The screenshot of the query looks like it is a regular query panel, do you have the information for the alert?

**Comment by matyax** [comment]
@SergioBernabe96 I've seen that the reported Grafana version is 9.3. Would there be any chance to test this with a newer version? With that, please reopen if you can consistently reproduce it. Thank you!
