### ISSUE TITLE
Inconsistent behavior of unit conversion

### ISSUE THREAD

**Issue by mindprince** [grafana/grafana#6267]
- [x] Bug report

- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708)

- What datasource are you using?
OpenTSDB

- What OS are you running grafana on?
Debian Jessie

I was sending some of my metrics as nanoseconds. I specified the unit as nanoseconds in grafana and grafana helpfully displays the legend in the most reasonable unit (ms or seconds etc.)
<img width="1919" alt="screen shot 2016-10-13 at 11 25 43 am" src="https://cloud.githubusercontent.com/assets/695290/19361551/ee958d10-9137-11e6-8cba-5658955cda07.png">

I am now sending those metrics as seconds. I specified the unit as seconds in grafana but grafana doesn't display the unit as ms even if the value is too small like 4ms, instead it displays it as 0.0040s which is much harder to read.
<img width="1920" alt="screen shot 2016-10-13 at 11 26 14 am" src="https://cloud.githubusercontent.com/assets/695290/19361584/1d3daa3a-9138-11e6-8129-4c483b88ef7e.png">

Is this expected behavior? Is so, why? If not, can this be fixed?

**Comment by torkelo** [comment]
this is fixed in master / v4 nightly
