### ISSUE TITLE
[Feature Request] Dynamic dashboard "now delay" based on metric granularity 

### ISSUE THREAD

**Issue by knoguchi** [grafana/grafana#6268]
I'm using Grafana v3.1 with Druid plugin on Ubuntu14.  I would like to have an option that changes the "Now Delay" dynamically based on metrics granularity.

Problem that I want to solve:
Suppose "Now delay" in the dashboard settings is 5m in order to avoid incomplete metrics.  It works as long as the metric granularity (bucket size of aggregation) is <=5m.   However some datasource supports dynamic metric granularity based on the selected time range and resulting number of data points.  When the metric granularity is > 5m the incomplete metric appear on the graph.  I would like to exclude the incomplete metric.

Proposed solution:
Add "dynamic" checkbox to Now delay.  When "dynamic" is chosen and upon the time range is updated, the dashboard should query each panel for the granularity, find the longest (coarsest) granularity, and apply the "Now delay".

Optionally, rename "Now delay" to "min Now delay".  When the min value is specified and "dynamic" checkbox is on, the greater value is applied.  The idea is the backward compatibility for existing graph widgets that does not support querying metric granularity. 

Relevant discussions:
Issue #575 and #1241 discussed some of the design choice when the "Now Delay" feature was introduced.  To ignore the last value in the graph panel config seems to be the least invasive because the change is local to graph widgets only.   But this solution does not work for single data point e.g. average metric of full time range yields 1 data point only that includes incomplete metric in calculation.  Therefore current Now Delay design is good, and I would like to extend its functionality.

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
