### ISSUE TITLE
Alerting: Support for opentsdb in alerting

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6270]
We need help form the community if we want to support opentsdb in grafana 4.0

@utkarshcmu have started working on this and it would be great of more opentsdb users would help out to test it. Support for opentsdb should be added to the `alerting_opentsdb` branch.

ref https://github.com/grafana/grafana/pull/6269
ref https://github.com/grafana/grafana/issues/5858

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/blob/alerting_opentsdb/public/app/plugins/datasource/opentsdb/datasource.js#L105 this method needs to be implemented before merging to master.

The purpose of that method is to detect if the target used for alerting contains a queryny template variable. Since alerting dont support templating we use it to display an error in the alerttag . 

You can find the influxdb version at https://github.com/grafana/grafana/blob/alerting_opentsdb/public/app/plugins/datasource/influxdb/datasource.ts#L142

**Comment by utkarshcmu** [comment]
@bergquist - Here is the PR implementing ```targetContainsTemplate``` function for OpenTsdb: https://github.com/grafana/grafana/pull/6325

**Comment by bergquist** [comment]
Merged to master :)

**Comment by utkarshcmu** [comment]
Thanks @bergquist :)
