### ISSUE TITLE
row repeat generates superfluous panels

### ISSUE THREAD

**Issue by mbjelac** [grafana/grafana#6271]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
v3.1.1 (commit: a4d2708)

- What datasource are you using?
reproducible with demo data

- What OS are you running grafana on?
Centos 7

- What did you do?
    1. Created a dashboard
    2. Created two template variables `x` and `y` with custom values `A`, `B`, `C`, and `foo`, `bar`, `baz`, respectively
    3. Created row with one panel (dummy data)
    4. Set panel repeat on `y`, panel title `$y`
    5. Set row repeat on `x`, row title `$x`
    6. Selected `All` for `x` and `y`

- What was the expected result?
Rows with titles `A`, `B`, `C`, each containing panels `foo`, `bar`, `baz`

- What happened instead?
The expected three rows show, they contain expected three panels, but in addition they contain two panels with `y=All`

*NOTE* Not reproducible without row repeat. Panel repeat works by itself.

I attached the [dashboard as JSON](https://github.com/grafana/grafana/files/529020/grafana_repeat_bug_3.1.1.txt), also here's a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/7265651/19380926/bd6af1b8-91f9-11e6-8887-336038dddfa0.jpg)

**Comment by torkelo** [comment]
panel and row repeat combo are not working correctly in 3.1 , try 4.0 nightly build
