### ISSUE TITLE
Grafana 9.3.6 Oauth Gitlab taking too long time to login

### ISSUE THREAD

**Issue by mkarthiatgithub** [grafana/grafana#62724]
**What happened**:

Gitla O auth can be successful. However, taking too long to login,  I see that its due to 
https://github.com/grafana/grafana/blob/143ee0c49f0d56bdca0849df10acfd03471faf05/pkg/login/social/gitlab_oauth.go#L47 

I tried skip_org_role_sync = true , not much joy. 

**What you expected to happen**:

Login via Oauth should be relatively quicker. 

**How to reproduce it (as minimally and precisely as possible)**:
gitlab O auth config 

cat /etc/grafana/grafana.ini

[auth.gitlab]
allow_assign_grafana_admin = false
allow_sign_up = false
api_url = https://gitlab.com/api/v4
auth_url = https://gitlab.com/oauth/authorize
client_id = ${GITLAB_APPLICATION_ID}
client_secret = $(GITLAB_APPLICATION_SECRET)
enabled = true
role_attribute_strict = false
scopes = read_api
token_url = https://gitlab.com/oauth/token
skip_org_role_sync = true
[grafana_net]

**Anything else we need to know?**:
Tried with latest 9.3.6 image, same issue. 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@mkarthiatgithub please add more information to this issue so we can investigate: 

* how long is the login process taking? 
* how many users are in the groups

**Comment by mkarthiatgithub** [comment]
hi, 
thanks for looking at this. 

There are only 20 users in the group. ( I used a subset of the organisation group) 

it takes close to a minute or two. It fails sometimes due to mutiple get groups calls to gitlab get groups.

**Comment by SachinKSingh28** [comment]
I am getting the same issue when enabling oauth with gitlab! Once I authorise the application in gitlab with `openid`, `email`, `profile` and `read_api` scopes, grafana constantly makes group api queries and then times out trying to sign in.

**Comment by Jguer** [comment]
https://github.com/grafana/grafana/pull/72277 should have reduced the amount of groups pulled.

How many groups does your failed user belong to @SachinKSingh28 ?

**Comment by Jguer** [comment]
Closing for staleness
