### ISSUE TITLE
Test Rule Failed

### ISSUE THREAD

**Issue by whc9527** [grafana/grafana#62746]
**What happened**:
![image](https://user-images.githubusercontent.com/17898805/216274343-da30ac13-30d0-424d-92c4-171591a4d9e3.png)
![image](https://user-images.githubusercontent.com/17898805/216274514-b50e1259-bf9b-4b04-bb3b-75b9c077138f.png)
can draw normally, but the "Test Rule" fails，I found the same problem in the Grafnan 8 release

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana-9.3.6
- Data source type & version: mysql
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: mysql
- Others:

**Comment by mellieA** [comment]
@whc9527 if you are using unified alerting (introduced in Grafana 8) alert queries cannot include dashboard variables in the query. Please confirm if the rule works without the dashboard variable.

**Comment by whc9527** [comment]
@mellieA

**Comment by whc9527** [comment]
This seems like a reasonable feature, so why wasn't it added?

**Comment by mellieA** [comment]
@whc9527 the reason that dashboard template variables don't work in alert queries is that with the new implementation of grafana alerts, the dashboards and alerts are decoupled. 

I wonder if $region is a supported clickhouse query variable - separate from the dashboard. 

Many users use a mult-dimensional alert for this use case - https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule

**Comment by JohnnyQQQQ** [comment]
As mentioned by @mellieA this is not supported and we don't plan on supporting it as we decoupled from dashboards with the new alerting system. Multi dimensional alerts would be the right approach, having one query for multiple regions at once. Closing it.
