### ISSUE TITLE
[Bug] System time in graph hover info instead of metric timestamp

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6275]
I've found a bug in time displayed in hover info window. When you select a single metric on the graph the time that is shown in the hover info is the local system time which get's refreshed on every mouse move. It should be the proper timestamp of the hovered metric value instead.

![aaa](https://cloud.githubusercontent.com/assets/12551929/19385855/618b21a2-9211-11e6-814d-38037dd5a0ec.jpg)

**Comment by torkelo** [comment]
what version of Grafana are you using?

**Comment by pavleec** [comment]
Just checked the latest 4.0.0-1476432901pre1 build.

**Comment by torkelo** [comment]
@benrubson something your PR caused? https://github.com/grafana/grafana/pull/6211

**Comment by benrubson** [comment]
@torkelo I'll have a look.

**Comment by benrubson** [comment]
OK, solved by #6283 👍
