### ISSUE TITLE
Telemetry reporting to sentry.io

### ISSUE THREAD

**Issue by ollie-campbell** [grafana/grafana#62759]
__Steps to reproduce:__

1. Install influx
2. Install grafana
3. Setup a dashboard
4. Use your browsers developer console to look at network requests

__Expected behavior:__
No external contact even telemetry.

__Actual behavior:__
Requests to "https://o1313669.ingest.sentry.io/api/XXXXXX/XXXXXXX/XXXXXX" seen.

__Environment info:__

* System info: Linux 5.15.0-58-generic x86_64
* InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:53:07Z
* Grafana v9.3.6 (978237e7cb)

__Config:__
N/A

Screenshot:
![image](https://user-images.githubusercontent.com/43950743/215844201-763e7f18-6270-45ae-863e-bf81d1616cbe.png)

How can we disable telemetry reporting in Grafana please?

**Comment by mellieA** [comment]
Are you saying that there is sensitive authentication data shown or you prefer not to see the request URLs? 

I can move this issue to discussions - but I don't think there is currently a way to disable this

**Comment by mellieA** [comment]
I don't see the same thing on any of my own instances - I'm wondering if there is something outside of grafana running on this server that might be interacting with the requests. 

You can try on our demo server here: 
https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

**Comment by sakjur** [comment]
Is it possible it’s a browser extension of yours? When googling the subdomain, it seems to be associated with GoCardless in some way 🤔

**Comment by ollie-campbell** [comment]
> Is it possible it’s a browser extension of yours? When googling the subdomain, it seems to be associated with GoCardless in some way 🤔

Thanks for the pointers. After having viewed our installation through a 'private session' (no extensions) I don't see the requests. I can only presume it is an extension.

Thanks for your help
