### ISSUE TITLE
Query History: If not using remote storage, use local storage from autocomplete history

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#62757]
## Background
To enable future growth of query history, we moved query storage from local storage, which exists only on the users computer, to remote storage, which saves queries on the Grafana instance's database. 

### Code change timeline
* Introduced remote storage for query history in #44327
* Enabled by default in #49407
* Migrated local storage to remote storage in #48572
* Migration was removed in https://github.com/grafana/grafana/pull/67470

Initially, we had thought to completely deprecate storage of queries in local storage, but due to another existing feature, we should be able to leave the option in without much extra code. There are also benefits to local storage that we would not want to eliminate completely.

**Remote storage benefits**
- Persists between browsers / computers / after uses clears browser data 
- Can be shareable

**Local storage benefits**
- Usable when Grafana is stateless (the database is not persisted)
- If users at the “viewer” level can access Explore, and the people managing the instance do not want viewers to potentially add much to the database, this would give them that option
     - Potential example use case: a Grafana instance where the user base includes a large number of contracted workers that are not managed directly by the Grafana maintainers. They may be given “viewer with explore” access to keep costs/bandwidth for Grafana storage down. If a large number of users are creating a large number of entries in the database, the instance managers may wish to disable this feature. Local storage would ensure those users still have some amount of persisted query storage on their local machines.

According to our usage data, there are 0 users that are using local storage (data can be provided internally). This shouldn’t be extrapolated to mean absolutely no users use local storage, but it does mean we should prioritize it fairly low.

## Requirements

Change the autocomplete feature ([src](https://github.com/grafana/grafana/blob/main/public/app/core/utils/explore.ts#L298)) to use the query history local storage. Saving to local storage should happen regardless if remote storage is being used or not.  Reading query history should depend on the setting, and reading autocomplete should always read from local storage. Writing to remote storage should only happen if the setting is enabled.

Autocomplete does not have the concept of "starring" queries to save them for a more permanent amount of time. Disable the ability to star queries if local storage is being used, and update the documentation accordingly.

Limit this local storage to only save 100 entries. This is to not overwhelm the autocomplete feature.

Remove existing autocomplete storage functionality. 

Current Query history local storage (read/write) code is at https://github.com/grafana/grafana/blob/main/public/app/core/history/RichHistoryLocalStorage.ts 

Current autocomplete history code (write) is at 
https://github.com/grafana/grafana/blob/main/public/app/core/utils/explore.ts#L279

Ensure current autocomplete use (read) is functional
https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/utils.ts#L122

**Comment by gelicia** [comment]
Another question: if we can't remove local storage - can we remove the migration?

**Comment by ifrost** [comment]
> There's a couple pretty good reasons to not follow through with this ticket and keep saving history in local storage as well as remote storage if it is enabled.

> Importantly, we already save all query history information in local storage for autocomplete anyway, so we won't be able to completely remove this saving of data.

I'll actually add info about various query history implementations to the ticket description for more context.

**Comment by ifrost** [comment]
> We are thinking it might be a better idea to merge together the auto complete storage and the query history storage

That's an interesting idea! We could create another implementation of `RichHistoryStorage interface` that reads from  `grafana.explore.history.${datasourceId}`. This however means we still need to maintain 2 read paths (currently tests for both are kind of split). I wonder if it wouldn't be simpler to just remove the local storage for rich history 🤔

**Comment by ifrost** [comment]
It seems like we could:
- Save the query to remote storage **only** if remote storage is enabled, and also **always** save it to the local storage
- Change the implementation so for autocomplete we read from query history (passed to the query editor [here](https://github.com/grafana/grafana/blob/d3450d75a4916f29369d85f616dba6fd83077236/public/app/features/explore/QueryRows.tsx#L89))
- Change the local storage query history implementation to hold only [100 items (like the history for autocomplete)](https://github.com/grafana/grafana/blob/d5db67a0731a44706fa8fe263e62f51d26b7e2e2/public/app/core/utils/explore.ts#L40). This is to not blow the local storage with too many items (at the moment for it's [10000](https://github.com/grafana/grafana/blob/fecf4c41ad69937af5cb351bb8055f178b019140/public/app/core/history/RichHistoryLocalStorage.ts#L18)). It means when running a stateless Grafana with clean db on each restart and remote storage for history disabled, the users would be able to save only up to 100 items but since it's a low priority just to cover and edge case it should be good enough
- Remove storing query for autocomplete in `grafana.explore.history.${datasource}` in local storage ([here](https://github.com/grafana/grafana/blob/88ee7a1c6262b2067c6d76bdfbabc6775ac0aa1d/public/app/features/explore/state/query.ts#L489))

**Comment by gelicia** [comment]
@ifrost all of those make total sense, I like trashing autocomplete storage in favor of the rich history storage, as opposed to the reverse. I integrated what you have in with the original description - let me know if I missed anything.
