### ISSUE TITLE
GRAFANA do not start after upgrade to 8.5.20

### ISSUE THREAD

**Issue by Davide-1973** [grafana/grafana#62769]
**What happened**: I upgraded Grafana to 8.5.20 using yum update. After reboot, grafana-server doesn't start.

**What you expected to happen**: Grafana server starts

**How to reproduce it (as minimally and precisely as possible)**: Upgrade to Grafana 8.5.20

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.20
- Data source type & version: Zabbix 6.2.7
- OS Grafana is installed on: Oracle Linux 8.7
- User OS & Browser: 
- Grafana plugins:
- Others: This is what grafana log says:
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-02-02T12:15:11.97+0100 lvl=info msg="App mode production"
logger=sqlstore t=2023-02-02T12:15:11.97+0100 lvl=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-02-02T12:15:11.97+0100 lvl=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
logger=cli t=2023-02-02T12:15:11.98+0100 lvl=eror msg="Critical error" reason="Grafana has already been migrated to Unified Alerting.\nAny alert rules created while using Unified Alerting will be deleted by rolling back.\n\nSet force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data." stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer.func2()\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:143 +0x94\npanic({0x2d72ae0, 0x3c4c5d0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/grafana/grafana/pkg/services/sqlstore/migrations/ualert.AddDashAlertMigration(0xc000750e10)\n\t/drone/src/pkg/services/sqlstore/migrations/ualert/ualert.go:78 +0x7b6\ngithub.com/grafana/grafana/pkg/services/sqlstore/migrations.(*OSSMigrations).AddMigration(0x3529bc6, 0xc000750e10)\n\t/drone/src/pkg/services/sqlstore/migrations/migrations.go:61 +0x269\ngithub.com/grafana/grafana/pkg/extensions/migrations.(*EnterpriseMigrations).AddMigration(0xc0007661a0, 0xc000750e10)\n\t/drone/src/pkg/extensions/migrations/migrations.go:32 +0x2e\ngithub.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).Migrate(0xc000b0a480, 0x0?)\n\t/drone/src/pkg/services/sqlstore/sqlstore.go:135 +0x6f\ngithub.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0xc000ab6400, 0x18?, {0x3c54a60?, 0xc0007661a0?}, {0x3c71af0?, 0xc000750a00?})\n\t/drone/src/pkg/services/sqlstore/sqlstore.go:67 +0xdc\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc31c95c72, 0x18}, {0x0, 0x0}, {0xc00011e040, 0x4, 0x4}}, {{0x0, 0x0}, {0x7ffc31c95c95, ...}, ...}, ...)\n\t/drone/src/pkg/server/wire_gen.go:191 +0x1e9\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffc31c95c72, 0x18}, {0x0, 0x0}, {0x7ffc31c95c95, 0x23}, {0x7ffc31c95cc5, 0x3}, 0xc000074580?, {{0x3c43440, ...}, ...})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:188 +0x785\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x3c43440, 0x6}, {0x3c44760, 0xa}, {0x3c43430, 0x4}, {0x3c44750, 0xa}})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:111 +0x758\nmain.main()\n\t/drone/src/pkg/cmd/grafana-server/main.go:16 +0xb7\n"

**Comment by vincent-olivert-riera** [comment]
@Davide-1973 , the clue for your solution is here:

```
logger=cli t=2023-02-02T12:15:11.98+0100 lvl=eror msg="Critical error" reason="Grafana has already been migrated to Unified Alerting.\nAny alert rules created while using Unified Alerting will be deleted by rolling back.\n\nSet force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data." 
```

To make it more readable:

> Grafana has already been migrated to Unified Alerting.
> Any alert rules created while using Unified Alerting will be deleted by rolling back.
>
> Set force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data

For some reason, it seems that you were already using Unified Alerting, and now after your upgrade to 8.5.20 you have Grafana set up to use Legacy Alerting, hence the message above.


If you want to go back to using Legacy Alerting, do what the message says. (I do not recommend it since Legacy Alerting is already deprecated).

I would rather fix the problem by explicitly disabling Legacy Alerting and enabling Unified Alerting in `grafana.ini`:

```
[alerting]
enabled = false

[unified_alerting]
enabled = true
```

**Comment by Davide-1973** [comment]
> @Davide-1973 , the clue for your solution is here:
> 
> ```
> logger=cli t=2023-02-02T12:15:11.98+0100 lvl=eror msg="Critical error" reason="Grafana has already been migrated to Unified Alerting.\nAny alert rules created while using Unified Alerting will be deleted by rolling back.\n\nSet force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data." 
> ```
> 
> To make it more readable:
> 
> > Grafana has already been migrated to Unified Alerting.
> > Any alert rules created while using Unified Alerting will be deleted by rolling back.
> > Set force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data
> 
> For some reason, it seems that you were already using Unified Alerting, and now after your upgrade to 8.5.20 you have Grafana set up to use Legacy Alerting, hence the message above.
> 
> If you want to go back to using Legacy Alerting, do what the message says. (I do not recommend it since Legacy Alerting is already deprecated).
> 
> I would rather fix the problem by explicitly disabling Legacy Alerting and enabling Unified Alerting in `grafana.ini`:
> 
> ```
> [alerting]
> enabled = false
> 
> [unified_alerting]
> enabled = true
> ```

Hello, I enabled [alerting] section and added [unified_alerting] because it was NOT present in my grafana.ini file.
Then I restarted the service. The service still fails and in the log I only have these lines:
logger=settings t=2023-02-02T16:00:50.89+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00
logger=settings t=2023-02-02T16:00:51.22+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00
logger=settings t=2023-02-02T16:00:51.73+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00
logger=settings t=2023-02-02T16:00:52.22+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00
logger=settings t=2023-02-02T16:00:52.73+0100 lvl=info msg="Starting Grafana" version=8.5.20 commit=e9589eec36 branch=HEAD compiled=2023-01-24T18:32:04+01:00

While service grafana-server status report as follows:
[root@ZABBIX-SERVER grafana]# service grafana-server status
● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2023-02-02 15:54:29 CET; 6min ago
     Docs: http://docs.grafana.org
  Process: 38151 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=rpm cfg:default.paths.logs=${LOG_DIR} >
 Main PID: 38151 (code=exited, status=1/FAILURE)

Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: Failed to start Grafana instance.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Service RestartSec=100ms expired, scheduling restart.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: Stopped Grafana instance.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Start request repeated too quickly.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Feb 02 15:54:29 ZABBIX-SERVER systemd[1]: Failed to start Grafana instance.

[root@ZABBIX-SERVER grafana]# service grafana-server start
Starting grafana-server (via systemctl):  Job for grafana-server.service failed because the control process exited with error code.
See "systemctl status grafana-server.service" and "journalctl -xe" for details.
                                                           [FAILED]

**Comment by vincent-olivert-riera** [comment]
> Hello, I enabled [alerting] section and added [unified_alerting] because it was NOT present in my grafana.ini file.

You don't need to enable the `[alerting]` section, you need to disable it. Like this:

```
[alerting]
enabled = false

[unified_alerting]
enabled = true
```

> See "systemctl status grafana-server.service" and "journalctl -xe" for details.

Check the output of the following command:

```
journalctl -eu grafana-server
```

**Comment by Davide-1973** [comment]
Ok, my mistake, sorry.
After set:
[alerting]
enabled = false

the prblem is solved and Grafana starts correctly.

Thanks for support Vincent!!!!

Davide

**Comment by vincent-olivert-riera** [comment]
> Thanks for support Vincent!!!!

No problem 👍

**Comment by allen-davis** [comment]
> > Hello, I enabled [alerting] section and added [unified_alerting] because it was NOT present in my grafana.ini file.
> 
> You don't need to enable the `[alerting]` section, you need to disable it. Like this:
> 
> ```
> [alerting]
> enabled = false
> 
> [unified_alerting]
> enabled = true
> ```
> 
> > See "systemctl status grafana-server.service" and "journalctl -xe" for details.
> 
> Check the output of the following command:
> 
> ```
> journalctl -eu grafana-server
> ```

Thanks, I solved the problem with this solution too.
