### ISSUE TITLE
Alerting frequency validation breaks alerts

### ISSUE THREAD

**Issue by zihaoyu** [grafana/grafana#6277]
- **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
  
  > Grafana v4.0.0-pre1 (commit: 4c26c55)
- What datasource are you using?
  - Graphite
  - Prometheus
  - InfluxDB
- What OS are you running grafana on?
  Docker on CoreOS
- What did you do?
  Test alerting rules
- What was the expected result?
  Display a JSON with either `firing: true` or `firing: false`
- What happened instead?
  ![screenshot from 2016-10-14 08-20-35](https://cloud.githubusercontent.com/assets/464299/19387267/1c296e54-91e7-11e6-8647-a9c3ee7681d0.png)

This should be a re-open of #6239 . We upgraded from 501e67a to 4c26c55 in order to try out the InfluxDB alerting, but all existing alerts settings are broken. When clicking on "Test Rule" button the above screenshot shows up. Below is a valid alert setting that worked in previous version (nothing has changed):

![screenshot from 2016-10-14 08-26-24](https://cloud.githubusercontent.com/assets/464299/19387403/f68a4d34-91e7-11e6-8c80-a42ea88ec1c0.png)

**Comment by torkelo** [comment]
if you delete the alert and create it again, do you get the same error? 

Any error in chrome dev console?

**Comment by zihaoyu** [comment]
@torkelo Deleting and re-creating the alert still gives me the error. There are three errors in the dev console, please see screenshot. I can send you `.har` file in private if you'd like.

![screen shot 2016-10-18 at 10 13 32 am](https://cloud.githubusercontent.com/assets/464299/19481394/c902b874-951b-11e6-85e1-334f09bdb0ba.png)

**Comment by torkelo** [comment]
could you show the whole request body json?

**Comment by zihaoyu** [comment]
@torkelo Please see [this gist](https://gist.github.com/zihaoyu/992e5facf6a69d965a7d6406a1ad8ca7)

I was testing the alert rule on [line 352-395](https://gist.github.com/zihaoyu/992e5facf6a69d965a7d6406a1ad8ca7#file-test-json-L352-L395)

**Comment by torkelo** [comment]
try removing all the alerts from this dashboard, save and then add an alert rule, one of the alert rules in that dashboard has some old schema

**Comment by zihaoyu** [comment]
Thanks @torkelo that worked. Do you have any idea how to pinpoint which rules have old schema? Also I noticed that some rules have empty values in the `Condition` `IS ABOVE` box, could that be the reason?

**Comment by zihaoyu** [comment]
Looks like alerting for InfluxDB is giving me a 400 error.

```
t=2016-10-18T15:13:17+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.resultHandler ruleId=52 error="tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request"```

**Comment by torkelo** [comment]
you have to have a value in the threshold condition (the is above). That is required. 
What does your influxdb query look like?

**Comment by zihaoyu** [comment]
@torkelo When I click on "Test Rule" again this time it came back ok. I will keep an eye on it. Thanks for the help!
