### ISSUE TITLE
Alerting Feature: Pause all alerts at once / resume them all.

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#6278]
We had to do a maintance today and restarted our data sources to load the latest configs. This took some minutes and Grafana correctly noticed this as a "No Data" case which is configured as "Alerting" and send an email for each alert. 

This could have been avoided if I paused each alert and resumed them afterwards, however we already have 20+ alerts. 

Better would be a button on the alert list, that allows to pause all of them at once (an resume all of them).

**Comment by torkelo** [comment]
Pausing alerts is more to disable alerts for executing, the feature is not meant for notification silencing, we plan to introduce temporary silence rules for that

**Comment by Fox32** [comment]
Disable the alerts is more or less what I'm looking for. I don't want to silence the notifications. I also don't want the state changes to show up in the UI.

**Comment by torkelo** [comment]
the silence rules might be able to disable the rules from execution as well, not sure yet we haven't started on the feature yet. The main thing is that the rules are temporary. the pause feature is permanent (until you unpause it)
