### ISSUE TITLE
[Bug] Alerting - no PNG file attached in email notification

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6279]
When using an e-mail notification the graph panel PNG file is properly generated in the **/var/lib/grafana/png** directory but it's not attached in the e-mail. However it's properly attached in the notification "Sent test" message. 
I'm using latest 4.0.0-1476432901pre1 build.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/6183
