### ISSUE TITLE
Alerting filtering gives error SyntaxError: unterminated parenthetical

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/grafana#62805]
**What happened**: 
Received the following error:

```
An unexpected error happened
SyntaxError: unterminated parenthetical

71759/xa<@https://grafana.globalspec.cloud/public/build/AlertRuleListIndex.b6fc1c64cafc55fc2582.js:158:4746
c@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1207:301
u@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1207:855
WithErrorBoundary
Suspense
c@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1207:301
_c@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:8831:350
t@https://grafana.globalspec.cloud/public/build/4743.1a1d46bf2371bc56aa60.js:2:1060861
t@https://grafana.globalspec.cloud/public/build/4743.1a1d46bf2371bc56aa60.js:2:1062882
main
Cd@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:8792:6825
t@https://grafana.globalspec.cloud/public/build/4743.1a1d46bf2371bc56aa60.js:2:1057479
div
o@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1996:4308
19175/t.KBarProvider@https://grafana.globalspec.cloud/public/build/4743.1a1d46bf2371bc56aa60.js:2:271053
l@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:6143:19549
c@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1207:301
u@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:1207:855
l@https://grafana.globalspec.cloud/public/build/4743.1a1d46bf2371bc56aa60.js:2:1040511
Su@https://grafana.globalspec.cloud/public/build/2362.97a60cb324cdf48dbcc2.js:8844:115
```

**What you expected to happen**:  Nothing should have happened

**How to reproduce it (as minimally and precisely as possible)**:
Go to the Alerting, Alert Rules page (https://grafana/alerting/list)
Start typing in a filter in the Search by Label box, when you get to the parenthesis, you get taken to the error page with the error above.  You can close the parenthesis in the URL and return to the page.  You can bypass the error if you are really quick at typing both opening and closing parenthesis.  

{cluster="dts", namespace=~(

**Anything else we need to know?**:

**Environment**:
- Grafana version:  9.3.3
- OS Grafana is installed on: K8S deployment from helm
- User OS & Browser:  Mac Firefox 109
- Grafana plugins: OnCall, Zabbix

**Comment by mellieA** [comment]
@MaxDiOrio the search syntax for the alert list page shouldn't require an open parenthesis. I tried it out on 9.3.6 just in case and wasn't able to trigger an error: 

![Screenshot 2023-02-03 at 4 22 05 PM](https://user-images.githubusercontent.com/18175287/216729051-e1f78650-e58a-488b-a39c-93a36f498457.png)

**Comment by MaxDiOrio** [comment]
Here's the info box I have for search - maybe your version is newer?  I'm on 9.3.4:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/25855524/216848204-ac349fa2-c9af-4ccf-9487-3ebb454215a3.png">

"using label querying"...This would imply needing to use a regex match on multiple terms requires the parentheses, as you would do in a regular label query that uses a regex match.

In your screen shot, how does this handle matches?  Is it an exact match on the label?  IOW, do I need to use the full label value I'm filtering for?  There are plenty of times I want regex matches and the help box your showing implies I can't do that.  

In either case, the handling of a parentheses in this instance is not really user friendly.  An red-colored error should appear next to the search box, not take you to a completely different page with a verbose error message.
