### ISSUE TITLE
Grafana 9.3 API does not support AlertGroup with AlertRulev9

### ISSUE THREAD

**Issue by KacperLegowski** [grafana/grafana#62807]
**What happened**:
After generation of AlertGroup using AlertRulev9 and try to deploy it via `api/ruler/grafana/api/v1/rules/{namespace}` endpoint I'm getting 500 error with message `unexpected backend type (grafana) for payload type (lotex)`. 

**What you expected to happen**:
AlertGroup added to Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create AlerGroup with AlertRulev9 using grafanalib 0.7.0
2. Generate JSON
3. Call `api/ruler/grafana/api/v1/rules/{namespace}` endpoint with generated JSON as a body/

**Environment**:
- Grafana version: 9.3
- grafnalib: 0.7.0

**Comment by tonypowa** [comment]
👋  @KacperLegowski 

thanks for creating this issue

Have you successfully called that endpoint in the past?

**Comment by KacperLegowski** [comment]
@tonypowa I upgraded grafana from 7 to 9. Endpoint does not work also with AlertRulev8, this time I'm getting `Datasource not found` error, but this seems as a `grafanalib` bug.

**Comment by tonypowa** [comment]
thanks for the details @KacperLegowski 

could you please double check first with the `grafanalib` maintainers ? i see there were [some changes in the source code](https://github.com/weaveworks/grafanalib/pull/535) regarding creating v9 alerts not long ago

**Comment by ShaGodJi** [comment]
Grafanalib has added AlertRuleV9 to support this.
Its a possibility, there's some issue with payload or get_alert_json function.

**Comment by tonypowa** [comment]
@KacperLegowski 

any news from the grafanalib team?

@ShaGodJi 

is it still reproducible with latest grafanalib ?

if so please can you share error logs and the [repro steps and environment info](https://github.com/grafana/grafana/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md)?

thank you

**Comment by JacobsonMT** [comment]
Looks to be a schema issue in grafanalib. There's an open PR to fix it here: https://github.com/weaveworks/grafanalib/pull/544

**Comment by ShaGodJi** [comment]
Thank you
