### ISSUE TITLE
Cloudwatch source doesn't have a way to only get the coarse grain metrics?

### ISSUE THREAD

**Issue by tooptoop4** [grafana/grafana#62837]
cloudwatch has got the same metric name under 2 different grains (per cluster and per topic)
![image](https://user-images.githubusercontent.com/33283496/216511655-1808517a-66c8-4eae-a0f7-a5bce31715c9.png)

I want grafana to just see the metrics at cluster level but there doesn't seem to be an option? it seems to pick all the metrics at topic level too and then complain about too many:
![image](https://user-images.githubusercontent.com/33283496/216512398-95229bcd-e503-48f0-8db6-9d6e039a1c59.png)

adding dimensions for broker/topic don't seem to help as either they show all metrics for a topic or just one topic

**Environment**:
- Grafana version: 9.3.6

**Comment by kevinwcyu** [comment]
Hi @tooptoop4,

I have some questions to try to understand the problem as I'm not too familiar with AWS Kafka and its metrics.

1. Are you able to get the metrics you want by making the query through the Cloudwatch console?
2. Does toggling the `Match exact` toggle change anything with respect to what's returned?
3. What time range are you using? If you set it lower, does it still return the error about the number of metrics exceeding the limit?

**Comment by fridgepoet** [comment]
Closing a stale issue, feel free to reopen
