### ISSUE TITLE
Cannot set mute time end to 00:00

### ISSUE THREAD

**Issue by vfxGer** [grafana/grafana#62849]
I need a mute for my alert to be 22:00 to 07:00 UTC for my Grafana managed alerts.
I get an error when I set the time to that so I set time intervals to 
22:00 to 23:59 and 00:00 to 07:00 UTC
but now I get alerts at 23:59.
Is there a workaround for this?

- Grafana version: v9.3.6 (978237e7cb)

**Comment by mellieA** [comment]
@vfxGer did you try setting it to 22:00 to 24:00 and 00:00 to 07:00 UTC?

Our docs show 24:00 as a valid end time - https://grafana.com/docs/grafana/latest/alerting/manage-notifications/mute-timings/#time-intervals

**Comment by vfxGer** [comment]
That seems to work thanks
