### ISSUE TITLE
NPM build error

### ISSUE THREAD

**Issue by XaroRSA** [grafana/grafana#6284]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0.0-pre

- What datasource are you using?
N/A

- What OS are you running grafana on?
Tried on both Windows & Ubuntu 16.04 VM

- What did you do?
"NPM RUN BUILD"

- What was the expected result?
Successful build

- What happened instead?
Running "typescript:build" (typescript) task
>> public/app/features/dashboard/specs/dashboard_srv_specs.ts(9,21)
6: Supplied parameters do not match any signature of call target.
Warning: Task "typescript:build" failed. Use --force to continue.

Tried different node versions, Npm version, same error.

**Comment by torkelo** [comment]
sorry, committed something yesterday that broke the build
