### ISSUE TITLE
Grafana doesn't send GET request for suggest tagk for graph filter key to openTSDB(2.2)

### ISSUE THREAD

**Issue by Helene** [grafana/grafana#6286]
Hello!
* **I'm submitting a ...**
- [ x] Bug report

Please include this information:
- What Grafana version are you using?  3.0.4
- What datasource are you using?  openTSDB2.2
- What OS are you running grafana on?  windows7

- What did you do?
During graph creation I observed the GET http requests via chrome dev tools network tab. The suggest request and autocomplete for metric works fine.

![look_up_metricjpg](https://cloud.githubusercontent.com/assets/22845495/19402534/e45e1b98-9261-11e6-9e27-5c876a9769c2.JPG)

Also it works fine for filter values. I see the GET requests for tagv:
![look_up_tagv](https://cloud.githubusercontent.com/assets/22845495/19402601/2ed30260-9262-11e6-975e-1cfca917bcbe.JPG)

![look_up](https://cloud.githubusercontent.com/assets/22845495/19402681/b1cf5222-9262-11e6-82e7-b49607467662.JPEG)

But I'm missing autocomplete for filter key. I don't see any GET requests send out for suggest tagk.
![look_up_tagkjpg](https://cloud.githubusercontent.com/assets/22845495/19402731/fac0c7b8-9262-11e6-9789-f7315880aab0.JPG)

- What was the expected result?- What happened instead?

I was expecting to get suggested list for filter key. Also I tried to put template variable name instead of key string. This doesn't help. ( The template variable $tags with query tag_names = metrics(cpu_user) works fine, but not usable in the graph panel as "filter key input")
I wish have autocomplete function working for filer keys, also the option for using template variables  in graph filter "key" field .

Many thanks for your support in advance

**Comment by torkelo** [comment]
Try 3.1 or v4 nightly?

**Comment by utkarshcmu** [comment]
@Helene There is no "suggest" request send explicitly for tag/filter keys as when the correct metric is typed, it automatically brings the tags/filter keys associated with it. So, if your metric name exists and you have tags associated with it, you should be able to see the dropdown and typeahead values.

**Comment by Helene** [comment]
@utkarshcmu My problem is not tag values. I want use a template variable for tag key.

**Comment by Helene** [comment]
@torkelo  It doesn't work with 3.1.1. Do you have v4 latest build also for windows, that I can test it?

**Comment by utkarshcmu** [comment]
@Helene This should help on how to use template variable for tag key:

https://github.com/grafana/grafana/blob/master/docs/sources/datasources/opentsdb.md#templating-queries

**Comment by Helene** [comment]
@utkarshcmu thanks for the link, I'm familiar with the template feature documentation. My template variables work fine, but I can't use them as tag_key definition "in the graph query". Let me make an example.  We have "CPU_USER" metric counters cluster- or node- wide. Here you can see my template variables, showing 4 names (node names) by selecting "node"-wide viewing
![value](https://cloud.githubusercontent.com/assets/22845495/19453833/280b40f8-94b7-11e6-946d-4e8f72c96c09.JPG)
I would like to use the same variable $component in the graph query definition to make the graph:
1) flexibel as much as possible
2) limit a list of filter_values suggest results only to those of them which match the $component( tag_key).
In the current implementation of graph query, the input of filter_key by sending "GET HTTP request" is just ignored.
![filter2](https://cloud.githubusercontent.com/assets/22845495/19454285/d29f09b8-94b8-11e6-826b-fc01c51ee435.JPEG)

![filter](https://cloud.githubusercontent.com/assets/22845495/19454246/adc77ac6-94b8-11e6-9931-7bd4f47733d2.JPEG)

If I type "n" in filter "key" field I'm missing the GET request issued:
/api/suggest?max=1000&q=n&type=tagk
If I set filter $component = pm_filter($value) , groupBy = true the template variables will be resolved properly:
![post](https://cloud.githubusercontent.com/assets/22845495/19454966/7c4f376a-94bb-11e6-916f-ee352700533c.JPG)

**Comment by utkarshcmu** [comment]
Hello @Helene , the reason why suggest tag keys are not working is due to this PR: https://github.com/grafana/grafana/pull/3901

There was a previous issue which was similar to yours:
https://github.com/grafana/grafana/issues/4810

Can you please post the response of the OpenTSDB request for metric "cpu_system" without putting any tags for any timerange?

**Comment by utkarshcmu** [comment]
Also, you may sign up on slack to discuss issues with Grafana - http://slack.raintank.io/

**Comment by Helene** [comment]
Hello @utkarshcmu,

yes, it looks like the previous tickets did report the same issue.
Here is the response of the OpenTSDB request for metric "cpu_system"
![http_response](https://cloud.githubusercontent.com/assets/22845495/19498746/ffa73108-9592-11e6-97df-e63a1a582521.JPG)

**Comment by utkarshcmu** [comment]
@Helene I wanted to see the array "AggregatedTags" in the response to help you out. If you could also explain what exactly do you want to see on the dashboard may be I can help you out. Slack might be a better option to ping me and resolve the issue.
