### ISSUE TITLE
Provisioning API alert_rule validation of limits

### ISSUE THREAD

**Issue by daxroc** [grafana/grafana#62904]
**What happened**:
When creating provisioned alert rules using the API, if the uid for the alert exceeds the 40 char limit creation succeeds and the resulting uid is truncated. 

These truncated uid alert rules don't retain the provisioned status in the UI, It's not clear if that's a feature. 

The deletion of alert rules does not also truncate the incoming uid, which leads to an automated deletion problem. 

**What you expected to happen**:
Creation of an alert rule where the uid or other fields exceed the limits should fail

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert-rule using the provisioner api with a uid exceeding 40 chars

**Anything else we need to know?**:

- Grafana version: 9.3.6

**Comment by grobinson-grafana** [comment]
Hi! :wave:

Thanks for the issue! I'm afraid I've not been able to reproduce this issue on MariaDB (MySQL), postgres or sqlite3. In both MariaDB and Postgres I got an error that the UID had exceeded the maximum length of the column, while in sqlite3 it was accepted, but still kept its Provisioned status. Would you be able to share the JSON and a screenshot of the provisioned rule?

**Comment by armandgrillet** [comment]
We should reject when provisioning such an alert rule, the situation we currently have is a bug.
