### ISSUE TITLE
cell text overflow truncation stops working in tables with multiple data links

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#62907]
**What happened**:

Updated grafana from 9.3.3 to 9.4pre and now long text in table overflows it cell.

![image](https://user-images.githubusercontent.com/2304970/216682702-e6a95676-2a92-43ba-9358-5aea711eb5cf.png)

**What you expected to happen**:

Previously overflowing cells were neatly truncated with `...` suffex.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new panel. 
Change visualisation to "Table"
Add 2 data links (important)
Add some random data and render table
Resize column so text overflows

https://user-images.githubusercontent.com/2304970/216684000-a8d4a709-2f12-4cfc-96d1-015cf13d9406.mp4

**Anything else we need to know?**:

I built this panel a while ago and added multiple data links but it didn't work. It was a known issue back then and I commented on it here. (https://github.com/grafana/grafana/issues/27004) leaving the data links in place anyway. Now suddenly they are working! Yay! But in the same instant the cells now overlap. I guess multiple links has just been implemented and broke the truncation but that issue looks stale and I cant see any PR's. 

**Environment**:
- Grafana version: v9.4.0-101068pre
- Data source type & version:
- OS Grafana is installed on:Docker
- User OS & Browser: Firefox Linux
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
I was also able to reproduce this. Thanks for letting us know @bobemoe
