### ISSUE TITLE
Alerting: Integration with PagerDuty

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6291]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Would love to integrated Alerting with xMatters or PagerDuty.

**Comment by emarkham** [comment]
do want

**Comment by utkarshcmu** [comment]
This is how I am implementing for PagerDuty alerting integration.

<img width="743" alt="screen shot 2016-10-28 at 10 03 11 pm" src="https://cloud.githubusercontent.com/assets/1019609/19827318/d6c044c6-9d5a-11e6-86e2-415ee67d3a4d.png">

**Comment by utkarshcmu** [comment]
Currently here is the functionality:

1. Grafana will trigger an incident on Pagerduty.
2. Pagerduty will handle acknowledgement and resolution.
