### ISSUE TITLE
TimescaleDB not detected since query builder migration to react

### ISSUE THREAD

**Issue by maurerle** [grafana/grafana#62925]
**What happened**:

Grafana does not detect my timescaledb tables and only shows a quite useless query builder.

The previous behavior workes really good:
https://github.com/grafana/grafana/discussions/37003#discussioncomment-1028885

Since the migration, TimescaleDB does not seem supported by the query builder anymore?

**What you expected to happen**:

Get a new query builder which supports `$__timeFilter(datetime)` and `$__timeGroupAlias(datetime,$__interval,0)` and automatically adds them.
Currently the builder is quite useless a

**How to reproduce it (as minimally and precisely as possible)**:

No timefilter is applied - have to apply it manually

![image](https://user-images.githubusercontent.com/25026204/216791335-e444d3cb-9829-4530-b1d9-850363e42cd4.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: TimescaleDB, PG14
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox
- Grafana plugins: -
- Others: -

**Comment by usmangt** [comment]
Hi @maurerle,

Thanks for opening this issue.

This sounds like https://github.com/grafana/grafana/issues/61186

can you please check and if it is the same will close this one and can track it there?

**Comment by maurerle** [comment]
Yes it is the same issue.
Sorry i missed it.
It is very sad, that this functionality got lost. Hope it is fixed soon!
Thank you!
