### ISSUE TITLE
Cannot read property '1' of null(…)

### ISSUE THREAD

**Issue by szxnyc** [grafana/grafana#6293]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:

- What Grafana version are you using?
Grafana 3.1.1 (docker build)

- What datasource are you using?
Prometheus 1.2.3 (docker build)

- What OS are you running grafana on?
CentOS Linux 7 (Core) - Linux 3.10.0-327.18.2.el7.x86_64
Chrome Browser - Version 51.0.2704.106 (64-bit)

- What did you do?
I have a MySQL 5.7.12 instance being monitored by mysqld_exporter loaded into Prometheus and trying to graph it Grafana. I downloaded the MySQL_Overview.json dashboard from https://github.com/percona/grafana-dashboards/blob/master/dashboards/MySQL_Overview.json with commit id (7b5a28aedb02be67b7f7834d5eb1f371236549cd). The datasource is successfully setup and I can successfully lookup metrics but most of the pre-built percona dashboard metrics are working.

- What was the expected result?
I am expecting all the data to be pulled into Grafana but only two of the states are being pulled in properly (mysql_global_status_uptime and mysql_global_variables_innodb_buffer_pool_size). The rest show an error "Cannot read property '1' of null."

I can see the values in Prometheus just fine, but they don't show in Grafana.

![screenshot from 2016-10-16 17-18-11](https://cloud.githubusercontent.com/assets/4885464/19421176/8b3f17de-93c8-11e6-878f-3db50f220d04.png)

![screenshot from 2016-10-16 17-49-17](https://cloud.githubusercontent.com/assets/4885464/19421192/02590ff0-93c9-11e6-8bf0-e8bfea1ca872.png)

The error says Cannot read property '1' of null.

- What happened instead?
The stats have a read exclamation mark with the error Cannot read property '1' of null.

![screenshot from 2016-10-16 17-46-07](https://cloud.githubusercontent.com/assets/4885464/19421173/7a2943e8-93c8-11e6-8687-14999df1c47b.png)

```
TypeError: Cannot read property '1' of null
    at b.calculateInterval (datasource.js?bust=1476649790245:4)
    at b.eval (datasource.js?bust=1476649790245:4)
    at b (boot.1649cbaa.js:41)
    at Function.Ya (boot.1649cbaa.js:41)
    at b.query (datasource.js?bust=1476649790245:4)
    at h.f.issueQueries (boot.1649cbaa.js:41)
    at h (boot.1649cbaa.js:36)
    at boot.1649cbaa.js:36
    at n.$eval (boot.1649cbaa.js:36)
    at n.$digest (boot.1649cbaa.js:36)(anonymous function) @ boot.1649cbaa.js:36(anonymous function) @ boot.1649cbaa.js:35h @ boot.1649cbaa.js:36(anonymous function) @ boot.1649cbaa.js:36$eval @ boot.1649cbaa.js:36$digest @ boot.1649cbaa.js:36$apply @ boot.1649cbaa.js:36(anonymous function) @ boot.1649cbaa.js:37e @ boot.1649cbaa.js:35(anonymous function) @ boot.1649cbaa.js:35
boot.1649cbaa.js:41 Panel data error: TypeError: Cannot read property '1' of null(…)
```
![screenshot from 2016-10-16 17-20-36](https://cloud.githubusercontent.com/assets/4885464/19421166/5db04b8a-93c8-11e6-8a8f-aa182987bc60.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
looks like that dashboard is not compatible with Grafana 3.1.1 but requires Grafana 4.0 (which is not released, but you can try it with grafana/grafana:master docker container or nightly build)
