### ISSUE TITLE
End User Experience with file dashboards is poor

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#6295]
## I'm submitting a ...

Feature request

### What Grafana version are you using?

 Grafana v4.0.0-pre1 (commit: 4c26c55) 

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

RHEL 7

### What did you do?

Installed Grafana entirely with configuration management

### What was the expected result?

A useful or customizable home page

### What happened instead?

1. The homepage is empty as Grafana does not register the on disk dashboards you have seen
2. You can not set a default dashboard which is on disk because you can not star them

I expected that if a dashboard on disk is named 'Home', it would be the new default home -- or that is dashboards.json there was a default_dashboard settings -- but there is none.

That UX should be improved for config management users.

## What Workaround did you apply?

Apache mod_rewrite

**Comment by torkelo** [comment]
you can do all of that with automation against the HTTP API. 

But I agree working with file based json dashboards is poor. It will likely be improved by removing the feature entirely and replacing it with automatic json file dashboards -> db sync, this is already done for plugin dashboards

**Comment by roidelapluie** [comment]
How would you keep track in changes on disk?

**Comment by torkelo** [comment]
revision property in the dashboard.json , that is how it's done for plugin dashboards (that are automatically synced with db)

**Comment by roidelapluie** [comment]
Thanks!
