### ISSUE TITLE
[Bug Report]: Annotations not rendered on a timeshift graph

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#6296]
When I timeshift a graph, I don't see annotations that should show up using the timeshifted plot. I am using my bosun plugin app.

Is this a bug in Grafana's side, or should I be finding out the timestamp of the graph in a way that includes time shifts in a panel?

**Comment by torkelo** [comment]
Annotation queries are global for the whole dashboard (only queries ones per fresh) so only use the dashboard time range

**Comment by torkelo** [comment]
so will to be solved by having pane specific annotations, https://github.com/grafana/grafana/issues/717

**Comment by roscoe57** [comment]
can't come quick enough, this is really really misinforming to the user
(so many times this has to be explained...)
