### ISSUE TITLE
Plugins: Document importance of reusing clients in backend datasources

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#62974]
To be able to make use of HTTP/TCP connection reuse and not risk using up all available sockets/connection on a host it's very important that backend datasources reuses clients and not creating new ones for each query etc.  

We do have a good example, see below, for HTTP datasource:
https://github.com/grafana/grafana-plugin-examples/blob/aec2092a18fcd62e56117ebf68ede5affe56c4c3/examples/datasource-http-backend/pkg/plugin/datasource.go#L35-L48

We should document this somewhere under https://grafana.com/docs/grafana/latest/developers/plugins/.

Somewhat related to https://github.com/grafana/grafana/issues/62972 so might make sense to consider fixing that one as well.

**Comment by andresmgot** [comment]
I have added this into the "Authentication" part of the documentation, which could be not very visible but at least is there.

I think that we should write some plugin development good practices, in which things like this are explained, but that sounds kind of a bigger story.
