### ISSUE TITLE
Support converting epoch time to datetime

### ISSUE THREAD

**Issue by potchin** [grafana/grafana#6297]
I have a metric which stores a datetime in epoch format. I would like to show this as a human-readable string in singlestat

**Comment by galindro** [comment]
+1

**Comment by skebo** [comment]
+1

**Comment by wanderingnewfie** [comment]
+1

**Comment by koallen** [comment]
+1

**Comment by nagimov** [comment]
+1

**Comment by nindza** [comment]
+1

**Comment by rodrigocastrillon** [comment]
+1

**Comment by fretty** [comment]
+1

**Comment by aknapp112** [comment]
+1

**Comment by mikeyfreshh** [comment]
+1

**Comment by edwardslabs** [comment]
+1

**Comment by schbrongx** [comment]
+1

**Comment by liyuankui** [comment]
I think it's solved, just **multiply it by 1000**, and choose the type as **Date**

**Comment by kilteer** [comment]
Thanks @liyuankui. That's a quick & easy solution.

**Comment by ipsecguy** [comment]
Do we have a type Date?

**Comment by rohitnagpal88** [comment]
I am looking to do the exact same thing , display an epoch timestamp in human readable date in a singlestat. Can't seem to find the type Date . Is it there in any specific version ? Any help appreciated.

**Comment by rohitnagpal88** [comment]
I ended up using the prometheus query language itself to get the time in seconds and selected the stat as a duration in seconds (time() - singlestatquery)

**Comment by ipsecguy** [comment]
would you mind sharing the promQL snippet?

**Comment by rohitnagpal88** [comment]
time()-(process_start_time_seconds)

time() function is prometheus is used to get the current time in epoch. So you can use it to calculate the no. of seconds since the process last started. Choose the singlestat unit as time duration in seconds .

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/issues/6297 

add 3 new unit formats for dates

**Comment by karlsoon** [comment]
Hi!
How to use this?
I have this timestamp from metric: 1540655070
![grafana-unixtime](https://user-images.githubusercontent.com/3785740/38982059-10ce4252-43eb-11e8-9171-c966d4baafce.PNG)

**Comment by rafawhs** [comment]
@karlsoon use **scale** function to multiply it by 1000

<img width="424" alt="screen shot 2018-04-20 at 14 36 52" src="https://user-images.githubusercontent.com/862244/39065524-6fdf4698-44a8-11e8-8a10-aab7d0900c51.png">

**Comment by caiges** [comment]
... and how might you do this for table data?

**Comment by ResolveWang** [comment]
@rafawhs Hi,rafawhs, what's the data source? I use prometheus and i can't find the `scale` function ?

**Comment by rafawhs** [comment]
@ResolveWang Graphite!

**Comment by enzobes** [comment]
@ResolveWang @Rekhs123 
If you use Prometheus Grafana want metrics in Milliseconds.
For example : process_start_time_seconds * 1000
Then you can put your metrics in Date Format.

**Comment by cvernooy23** [comment]
anyway to convert epoch to human datetime in a table graph with a postgresql datasource?

**Comment by marefr** [comment]
@cvernooy23 use the column style date and select date format

**Comment by mjtrangoni** [comment]
@marefr How do you convert epoch to milliseconds inside a Table? This is why I can`t use the date format.

**Comment by marefr** [comment]
@mjtrangoni see [comment](https://github.com/grafana/grafana/issues/6297#issuecomment-403035980) above. If not applicable please share your query you're using.

**Comment by mjtrangoni** [comment]
@marefr Yes, sorry, I was wrong and thought it was a column from a metric label, but it turn out this is indeed the value.
JIC, what if it would have been a label and not the value itself?

**Comment by marefr** [comment]
@mjtrangoni Given you have a label with epoch timestamp in millisecond format I think it should work to use column style date. If you need to do conversion your limited to solve that using prometheus query api. For the singlestat panel the support is broader, see [demo](https://play.grafana.org/d/77d47mNik/prometheus-singlestat-label-value?orgId=1).

**Comment by vivekj11** [comment]
Hi, I want to show uptime of my container on grafana, for that I have used something like                      
(( container_start_time*1000 )) and it is working absolutely fine. My problem is, as soon as this container is down, grafana is showing 63 years/122 years for this metrics. 
I am using prometheus, cadvisor and grafana.
Any Help..!!

**Comment by CH-MN** [comment]
Putting Date and Time on a dashboard seems pretty fundamental.  How do I do that?  I used a singlestat to get Time of last point, of some arbitrary metric, which returns it in some non human readable format.  I  select  YYYY-MM-DD HH:mm:ss for Unit, which converts it to just time.  I assume it is because it is so recent?  Why would Grafana make that kind of decision.  If I wanted just time, there should be a HH:mm:ss selection!  This thread goes back and forth I never see a definitive answer yet it is closed.  

Using 6.4.1.

**Comment by harvey945** [comment]
## Hi .i solved this problem.

```bash
hwEntityManufacturedDate.67108873 = STRING: 2017-3-20,0:0:0.0
```

![image](https://user-images.githubusercontent.com/93895686/191222645-fb9e5293-45d3-4a8a-a6b9-82fc6a989145.png)

## The verification obtained by snmp is not accurate, let's correct it.
```
metrics：1493856000

[root@TDengine generator]# date -d@1493856000 +"%Y-%m-%d %H:%M:%S"
2017-05-04 08:00:00
[root@TDengine generator]# date -d "2017-3-20 0:0:0.0" +"%s"
1489939200

snmp_export metrics 1493856000 > date 1489939200
difference: 3916800
```

```PromQL
grafana PromQL：
max((hwEntityManufacturedDate{instance="xxxx"}) - 3916800 ) * 1000
```

![image](https://user-images.githubusercontent.com/93895686/191224341-00442219-604d-44cb-af67-2534fdc2ed48.png)

Thanks.
