### ISSUE TITLE
LDAP Following Aliases

### ISSUE THREAD

**Issue by hExPY** [grafana/grafana#6298]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
-- 3.1.1-1470047149
- What datasource are you using?
-- InfluxDB
- What OS are you running grafana on?
-- Debian 8
- What did you do?
-- Logging in trough LDAP with a user member of a group which is in a aliased ou.
- What was the expected result?
-- Becoming Organizational Admin role
- What happened instead?
-- Becoming Viewer

We've been using LDAP with an aliased ou object. Since using a group which is in the aliased ou we're only becoming viewer for an organization. When setting up a group in the main ou of grafana and logging in then we become org admin.

```
alias
extensibleObject
ou=org,ou=groups,dc=org,dc=de,dc=local
departments-org


```

**Comment by torkelo** [comment]
Can you enable ldap verbose logging and show what LDAP groups are returned? Do you have the memberOf extension installed for your LDAP server? have you configured the memberOr attribute?
