### ISSUE TITLE
alert return value use table names instead of field names

### ISSUE THREAD

**Issue by beizhanyong** [grafana/grafana#62995]
**What happened**:

alert return value use table names instead of  sql field names

**What you expected to happen**:

alert return value use sql field names

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
their sql is the same

alert sql return：
![image](https://user-images.githubusercontent.com/121420085/217162971-a5bd5aae-7ed8-43a7-917f-e44688fa0bfc.png)
use this value
![image](https://user-images.githubusercontent.com/121420085/217163655-a2f0ae92-a734-44f4-80ea-3297cf3863f2.png)

panel sql return：
![image](https://user-images.githubusercontent.com/121420085/217163973-bb86234f-1432-499f-86c2-395c78b4464a.png)

use this value
![image](https://user-images.githubusercontent.com/121420085/217163809-4ac9522c-d24f-4fff-84bc-8112f1a88cde.png)

**Environment**:
- Grafana version: latest
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: linux
- Grafana plugins:
- Others:

**Comment by beizhanyong** [comment]
I want to alert that the field in the table is the field of the select field in sql statement, not the name of the frame

**Comment by beizhanyong** [comment]
data.NewFrame("")
name is empty, the display is *+field name

**Comment by alexmobo** [comment]
Hi @beizhanyong!

- What datasource are you using?
- For the above screenshots, where is that code from?

**Comment by armandgrillet** [comment]
Closing due to no response from original author. Please reopen and add more details if the issue still exists.
