### ISSUE TITLE
[Feature Request] Math operation before metric in query builder

### ISSUE THREAD

**Issue by babs** [grafana/grafana#6299]
It would nice to be able to have math operation also available before the metric in InfluxDB  query builder.
Ex:

`SELECT 100 - mean("usage_idle") FROM "cpu" WHERE $timeFilter GROUP BY time($interval), "host" fill(null)`

Currently the option is to build the query then switch to Edit mode and preprend the `100 -` stanza

**Comment by torkelo** [comment]
this needs to be done in influxdb, so please open a feature request in that repo

**Comment by babs** [comment]
I'm not quite sure to understand, it's a query builder related thing, no ?

**Comment by babs** [comment]
Just to clear out any misunderstanding:

[Feature Request] Math operation before metric at the field level

This kind of calculation is supported by InfluxDB but not available via the query builder.
It would be nice to have the possibility to do such with the query editor.

Information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB 0.12 (at least) up to 1.0.2 (latest tested)
- What OS are you running grafana on? Debian Jessie

Exmaple of query used and that works:

In Grafana raw editor:
`SELECT 100 - mean("usage_idle") FROM "cpu" WHERE $timeFilter GROUP BY time($interval), "host" fill(null)`

Using a http client:
`http://influxhost:8086/query?u=a&p=a&db=telegraf&q=SELECT%20100%20-%20mean(%22usage_idle%22)%20FROM%20%22cpu%22%20WHERE%20time%20%3E%20now()%20-%201h%20GROUP%20BY%20time(2s)%2C%20%22host%22%20fill(null)&epoch=ms`

![exemple_100_minus_cpu_idle](https://cloud.githubusercontent.com/assets/117580/19452489/817eada6-94b1-11e6-9ca4-ebd12aba4ec8.png)

**Comment by babs** [comment]
An example of position and naming of a math_before stanza in the query builder (or math_prefix?)

![math_before_example](https://cloud.githubusercontent.com/assets/117580/19453503/cc34e870-94b5-11e6-8282-6f1b28b50b9d.png)

**Comment by torkelo** [comment]
ok, we  need a new editor function for InfluxDB named `"mathRightSide" with a new math render strategy, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/query_part.ts#L80 

In the meantime you might be able to do something like `* -1 + 100`

**Comment by babs** [comment]
Yep it works like a charm, it's a good workaround meanwhile :)
Thanks

**Comment by vitalca** [comment]
Is there a workaround for "1 / mean(value)" ?

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by steenstra** [comment]
> 
> 
> Is there a workaround for "1 / mean(value)" ?

1/x is the same as x^-1, but as far as I can tell, the power function is not supported.
