### ISSUE TITLE
Migrate templates from legacy alerting to Grafana Alerting

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#63008]
Templates are not re-written as Go templates during migration from old to Grafana Alerting. For example, the following template ${instance} is down is migrated as a custom annotation with the same template. However, ${instance} is down is not compatible with Grafana Alerting. It should instead be {{$labels.instance}} is down. We should fix the migration to rewrite such templates to make them compatible with Grafana Alerting.

See https://docs.google.com/document/d/1mD6zJKzndfRi5cJ8qVse1H-tOJ7HvoiJS6kq-vYzmOE/edit# for more info.

**Comment by grobinson-grafana** [comment]
You can find the design doc for this here https://docs.google.com/document/d/1mD6zJKzndfRi5cJ8qVse1H-tOJ7HvoiJS6kq-vYzmOE/edit
