### ISSUE TITLE
Grafana 3.1.1 connect to Influxdb 1.0.2 error

### ISSUE THREAD

**Issue by stevehu** [grafana/grafana#6301]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

I am using Grafana latest docker image 3.1.1 and trying to create a data source to influxdb latest docker image 1.0.2 on Ubuntu 16.04. I can create data source if I select direct but got the following error if I select proxy. My understanding is influxdb listens 8086 with http protocol not tcp. Why Grafana is trying to dial tcp? Thanks.

t=2016-10-17T23:48:07+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/query status=500 remote_addr=172.17.0.1 time_ns=1ns size=0
2016/10/17 23:48:07 http: proxy error: dial tcp [::1]:8086: getsockopt: connection refused

**Comment by torkelo** [comment]
make sure InfluxDB is accessable with the URL you specified from within the docker container
