### ISSUE TITLE
Cloudwatch Logs: Add Query Help to Cheatsheet

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#63029]
In Cloudwatch Logs in the AWS Console there is a feature called "Query Help" which documents several commands with sample queries that can then be "applied" to the query editor.
![Screenshot 2023-02-07 at 8 42 36 AM](https://user-images.githubusercontent.com/6620164/217261602-33e6295b-04e9-4576-9a79-b01981e6589e.png)

In the Grafana Plugin for Cloudwatch Logs, we already have a somewhat similar feature called a cheat sheet which is accessible via a ? button. It would be great to put this documentation and sample queries there as well:
![Screenshot 2023-02-07 at 8 17 13 AM](https://user-images.githubusercontent.com/6620164/217261700-ee38818f-9ad7-4c0c-9201-eb1501b5f848.png)

**Comment by ashutosh887** [comment]
I would like to work on this Issue @sarahzinger !!!

**Comment by ashutosh887** [comment]
@sarahzinger  Please consider

**Comment by sarahzinger** [comment]
@ashutosh887 You're always welcome to submit a PR to Grafana anytime, no need to wait for approval :) Feel free to tag me as a reviewer if you'd like!

**Comment by sarahzinger** [comment]
A note that we should test sample queries in the cheatsheet with alerting, if any don't work for alerting we should make a note saying as such otherwise it can be confusing for users: https://github.com/grafana/grafana/issues/46429

**Comment by sarahzinger** [comment]
dupped fixed in: https://github.com/grafana/grafana/pull/67161
