### ISSUE TITLE
Grafana 9 API not working properly

### ISSUE THREAD

**Issue by dbtentrust** [grafana/grafana#63026]
**What happened**:
Alerts created using the API not showing up in Grafana. Contact points configured through the API not working.

**How to reproduce it (as minimally and precisely as possible)**:
curl to api/alert-notifications posting a new alert notification, no errors reported. That new notification channel won't show up in alerting/notifications but does show up in api/alert-notifications/lookup.

Same with alerts: curl to api/v1/provisioning/alert-rules posting a new alert rule. Won't show up in alerting/list but it will in api/v1/provisioning/alert-rules/<alertUID> and alerts will be sent through email (after manually configuring an alert notification channel).

**Environment**:
- Grafana version: 9
- User OS & Browser: Windows, Chrome

**Comment by usmangt** [comment]
Hi @dbtentrust,

Thanks for opening this issue.


Please review the submission template and include more details:

* What Grafana version and what operating system are you using?
* What is your datasource?
* What visualization panel you are using e.g. time-series, bar chart, histogram etc?
* **What** are you trying to achieve?
* **How** are you trying to achieve it?
* What happened?
* What did you **expect** to happen?
* Can you copy/paste the configuration(s) that you are having problems with?
* Did you receive any errors in the Grafana UI or in related logs? If so, please tell us **exactly** what they were.
* Did you follow any online instructions? If so, what is the URL?

**Comment by dbtentrust** [comment]
Fixed, had an error creating the alerts folder
