### ISSUE TITLE
Unable to edit alerts created from Provisioning API

### ISSUE THREAD

**Issue by redacristofoletti** [grafana/grafana#63047]
**What happened**:
I recently upgraded Grafana from `v8.5.15` to `v9.3.2`. When I tried to edit the alerts, created using the Provisioning API, from the UI I found out that this is not currently possible and wanted to touch base to see what a possible solution could be.
 
I believe that updating an alert by PUT request with the whole JSON object is not as easy as changing things from the UI, especially when it comes to editing numerical values. This would significantly increase the chance of making an error thus creating problems in a production environment.
 
Could you please point me in the right direction?

**What you expected to happen**:
Being able to edit alerts from the UI like previous versions of Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
Send a POST or PUT request with the Provisioning API with Grafana v9 or above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version:
- OS Grafana is installed on: Ubuntu18.04
- User OS & Browser: MacOS and Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@redacristofoletti there is a fix for this in https://github.com/grafana/grafana/pull/58410 

> we are enabling a workaround within the Provisioning API to do it by adding the x-disable-provenance header to the following requests:
> 
> POST /api/v1/provisioning/alert-rules
> PUT /api/v1/provisioning/alert-rules/{UID}

**Comment by redacristofoletti** [comment]
Hi @mellieA and thank you for your reply.

It does work for the POST request but not for the PUT, the error I get is the following:
`cannot changed provenance from 'api' to ''`

**Comment by bgerard-cc** [comment]
Also having this issue. Create alerts with a POST using the header, that works fine. But when updating a rule group interval, everything changes back to provisioned. Can't then change it back as I receive the same error message as above.

**Comment by redacristofoletti** [comment]
Hello, are there any updates on this?

**Comment by grobinson-grafana** [comment]
Hi! :wave:

I'm quoting a reply from @alexweav:

> It should work if you use the group-based endpoint (where you replace the whole group), rather than the single rule endpoint.
> 
> Basically, rule groups cannot have mixed provenance. You can't have provisioned and non-provisioned rules in a group at the same time. So, you'll need to disable provenance on the whole group at once.
>
> I thought we added the header to all provisioning API objects, but seems like it only made it down to two of the endpoints before that issue got closed. See https://raintank-corp.slack.com/archives/C028MCV4R7C/p1676466992018229
>
> We need to make that same header check from all the endpoints, not just those two.

It sounds like we need to add the header for `/api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}`, but it likely won't be supported in `/api/v1/provisioning/alert-rules/{UID}` because then it becomes possible to mix both provisioned and non-provisioned rules in the same rule group.

**Comment by grobinson-grafana** [comment]
Hi @JamieSimon2! Do you somehow have mixed provenances in the Rule Group?

**Comment by grobinson-grafana** [comment]
In that example (the group marked as provisioned with 2 alert rules marked as provisioned) you are unable to edit or delete alert rules via the Provisioning API?

**Comment by armandgrillet** [comment]
This has been merged, will be in Grafana 9.5.1 and more recent versions.

**Comment by luisneto** [comment]
We are running Grafana `9.5.6` and we get the same error when submitting a PUT request to try with `x-disable-provenance` as `true` to Alert Rules.
The documentation of version 9.3 indicates that this should be possible.

After some research, we found [this Grafana 10 documentation page](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/#provision-grafana-alerting-resources) which indicates that that provenance can be changed in bulk by submitting a `PUT` to the Alert Group. 

We tried that against our `9.5.6` instance, and it worked. 
But nothing on the version 9 documentation specifies that that is the way to do it. 

Is there still a bug, or is the provenance supposed to be changed in bulk as the version 10 documentation specifies?

**Comment by gmartynov** [comment]
still cannot delete stucked provisioned alert in grafana 9.5.7

```
$ curl -XDELETE -H "X-Disable-Provenance" -H "Authorization: Bearer my-example-token" https://my-example-grafana.com/api/v1/provisioning/alert-rules/my-example-id
{"message":"cannot delete with provided provenance 'api', needs 'file'","traceID":""}
```

can you provide the correct command?

**Comment by maikelvl** [comment]
Also not working in the case of Alert rule group PUT's
