### ISSUE TITLE
Grafana 3.1.1 connect to graphite error

### ISSUE THREAD

**Issue by xianglaz** [grafana/grafana#6304]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

add data resource 
 access:proxy
 type:graphite

HTTP Error:Internal Server Error

URL:127.0.0.1:8000
graphite access :127.0.0.1:8000

**Comment by torkelo** [comment]
make sure graphite is accessable using that url from your grafana-server
