### ISSUE TITLE
Extending graph panel time range into the future

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#6305]
* **I'm submitting a ...**
- [X] Feature request

Please include this information:
- What Grafana version are you using?
3.1.1

While fiddeling with holt_winters predictions (from InfluxDB) I tried to use the "time range" in the graph panel to set the range to now()+1h (and variants), and well, failed...
It works if I use the main dashboards time range, but that sets it for all the graphs.

So, it would be nice if one could either set "Override relative time" to "+1h" or get a new field for it.
The specifics isn't important, but it's needed to be able to set it on a specific graph not the entire dashboard if one wants to graph predictive data.

**Comment by torkelo** [comment]
supporting "+1h" syntax should be very simple to do.
