### ISSUE TITLE
Dashboard not loading on iOS/OSX safari

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#63056]
**What happened**:
I've received some feedback from users of my website that a few weeks ago (somewhere in December) dashboards stopped loading on iOS devices.
Sometimes whole page doesn't load, other times there is a long `Fetching` status which ends by `Grafana has failed to load its application files` error.
As far as I know, this issue occurs on iPhones and iPads on Safari and Google Chrome browsers. On macOS it works fine.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, I do not have iPhone or iPad so I cannot provide more details by myself. However, my Grafana instance is publicly available: https://stacjameteommz.pl. You should be able to test that by yourself on some iOS device.
Grafana is hosted behind reverse proxy on the server.

**Anything else we need to know?**:
My public website is based on Grafana 7.5.4, however, I've noticed the same issue with online iOS test devices on my test environment which is hosted on the newest Grafana 9.4.0-beta1.

**Environment**:
- Grafana version: 7.5.4 - 9.4.0-beta1
- Data source type & version:  InfluxDB1 (InfluxQL) on Grafana 7.5.4, InfluxDB2 (Flux) on Grafana 9.4.0-beta1
- OS Grafana is installed on: Debian
- User OS & Browser: iOS; Safari and Google Chrome. Unfortunately I don't know exact system & browser versions
- Grafana plugins: `D3 Gauge v0.0.8`, `Influx Admin v0.0.5`, `Radar Graph v1.4.4`, `WindRose v.0.7.0`, `CompareQueries v1.0.0`
- Others: -

**Comment by szerwi** [comment]
Hi @usmangt,

Thanks for the suggestions. As I said, it's hard for me to investigate this issue in detail, as I do not have iOS device myself, but I'm pretty sure that JS is enabled in every browser by default, including Safari, so the users should be able to access Grafana on their devices without any changes in browser settings.

A few weeks ago I've had a temporary access to an iPhone on which I've tested my dev environment on stable Grafana version, I believe it was 9.3.2. It wasn't working either. Login page was loading successfuly, however, after logging in the dashboard has failed to load.

**Comment by usmangt** [comment]
Ok, 

Can you please do the following:

Change the default log level to debug mode. To do this go to the server where grafana is installed and edit the configuration file (/etc/grafana//grafana.ini)
There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and try to reproduce this issue again on iOS (but using the newer ver 9.4 on your test env) by asking your friends or colleagues to open it on iOS device.

Once the website does not load, provide us with the backend logs (the default location in Linux is `/var/log/grafana/grafana.log`) so that we can have more information about the error message.

**Comment by szerwi** [comment]
@usmangt Here are the results:
I have used online iOS test device for the test. I've started loading the page at around 17:13:00.
I've used IPhone 14 Pro Max with iOS 16.3.
I've enabled anonymous access in the Grafana. Actually on 9.4.0-beta1 the page was not loading at all - the screen was white, there was no top or side bar. Login page (when anonymous access was disabled) wasn't loading either.

Grafana logs:
```
logger=ngalert.scheduler t=2023-02-08T17:12:00.013361475+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.scheduler t=2023-02-08T17:12:10.013510705+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:12:10.201124346+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:12:10.201099846+01:00
logger=ngalert.scheduler t=2023-02-08T17:12:20.012150636+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=secrets t=2023-02-08T17:12:25.189255781+01:00 level=debug msg="Removing expired data keys from cache..."
logger=secrets t=2023-02-08T17:12:25.19042778+01:00 level=debug msg="Removing expired data keys from cache finished successfully"
logger=ngalert.state.manager t=2023-02-08T17:12:25.201973116+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:12:25.201954186+01:00
logger=ngalert.sender.router t=2023-02-08T17:12:25.272871273+01:00 level=debug msg="Attempting to sync admin configs" count=0
logger=ngalert.sender.router t=2023-02-08T17:12:25.273030884+01:00 level=debug msg="Finish of admin configuration sync"
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:12:25.44072655+01:00 level=debug msg="synchronizing Alertmanagers for orgs"
logger=alertmanager org=1 t=2023-02-08T17:12:25.463653191+01:00 level=debug msg="neither config nor template have changed, skipping configuration sync."
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:12:25.485913304+01:00 level=debug msg="done synchronizing Alertmanagers for orgs"
logger=ngalert.scheduler t=2023-02-08T17:12:30.013332823+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.scheduler t=2023-02-08T17:12:40.011454146+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:12:40.201420183+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:12:40.201391378+01:00
logger=ngalert.scheduler t=2023-02-08T17:12:50.012001507+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:12:55.201149671+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:12:55.201088472+01:00
logger=ngalert.scheduler t=2023-02-08T17:13:00.012833565+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=infra.kvstore.sql t=2023-02-08T17:13:02.904349239+01:00 level=debug msg="kvstore value not found" orgId=1 namespace=serviceaccounts key=hideApiKeys
logger=context userId=0 orgId=1 uname= t=2023-02-08T17:13:03.810907779+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=127.0.0.1 time_ms=23 duration=23.416089ms size=12 referer= handler=/api/live/ws
logger=accesscontrol t=2023-02-08T17:13:03.983852405+01:00 level=debug msg="resolved scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=accesscontrol t=2023-02-08T17:13:03.984215057+01:00 level=debug msg="used cache to resolve scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=dashboard.permissions t=2023-02-08T17:13:03.984283081+01:00 level=debug msg="Access denied to folder or dashboard" userId=0 id=26 permissions="action:dashboards:write scopes:dashboards:uid:1"
logger=accesscontrol t=2023-02-08T17:13:03.984363493+01:00 level=debug msg="used cache to resolve scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=dashboard.permissions t=2023-02-08T17:13:03.984414058+01:00 level=debug msg="Access denied to folder or dashboard" userId=0 id=26 permissions="action:dashboards:write scopes:dashboards:uid:1"
logger=accesscontrol t=2023-02-08T17:13:03.984453438+01:00 level=debug msg="used cache to resolve scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=accesscontrol t=2023-02-08T17:13:03.984501044+01:00 level=debug msg="used cache to resolve scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=dashboard.permissions t=2023-02-08T17:13:03.984549711+01:00 level=debug msg="Access denied to folder or dashboard" userId=0 id=26 permissions="all(action:dashboards.permissions:read scopes:dashboards:uid:1 action:dashboards.permissions:write scopes:dashboards:uid:1)"
logger=accesscontrol t=2023-02-08T17:13:03.984583396+01:00 level=debug msg="used cache to resolve scope" scope=dashboards:uid:1 resolved_scopes="[dashboards:uid:1 folders:uid:kUiHvoK4k]"
logger=dashboard.permissions t=2023-02-08T17:13:03.984629926+01:00 level=debug msg="Access denied to folder or dashboard" userId=0 id=26 permissions="action:dashboards:delete scopes:dashboards:uid:1"
logger=ngalert.api t=2023-02-08T17:13:04.10775083+01:00 level=debug msg="user does not have access to any namespaces"
logger=context userId=2 orgId=1 uname=stacja t=2023-02-08T17:13:08.178721614+01:00 level=debug msg="Updating last user_seen_at" user_id=2
logger=accesscontrol.service t=2023-02-08T17:13:08.181575952+01:00 level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-2
logger=accesscontrol.service t=2023-02-08T17:13:08.193678869+01:00 level=debug msg="cache permissions" key=rbac-permissions-1-user-2
logger=auth t=2023-02-08T17:13:08.194318493+01:00 level=debug msg="token needs rotation" tokenId=26 authTokenSeen=false rotatedAt=2023-02-08T17:07:58+01:00
logger=auth t=2023-02-08T17:13:08.197306081+01:00 level=debug msg="auth token rotated" affected=1 auth_token_id=26 userId=2
logger=context userId=2 orgId=1 uname=stacja t=2023-02-08T17:13:08.197754197+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=127.0.0.1 time_ms=53 duration=53.427089ms size=12 referer= handler=/api/live/ws
logger=ngalert.scheduler t=2023-02-08T17:13:10.011690449+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:13:10.201868801+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:13:10.201844764+01:00
logger=accesscontrol.service t=2023-02-08T17:13:12.174448134+01:00 level=debug msg="using cached permissions" key=rbac-permissions-1-user-2
logger=context userId=2 orgId=1 uname=stacja t=2023-02-08T17:13:12.174686339+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=[::1] time_ms=33 duration=33.876988ms size=12 referer= handler=/api/live/ws
logger=ngalert.scheduler t=2023-02-08T17:13:20.011860783+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=secrets t=2023-02-08T17:13:25.188615471+01:00 level=debug msg="Removing expired data keys from cache..."
logger=secrets t=2023-02-08T17:13:25.188891322+01:00 level=debug msg="Removing expired data keys from cache finished successfully"
logger=ngalert.state.manager t=2023-02-08T17:13:25.201919777+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:13:25.201887804+01:00
logger=ngalert.sender.router t=2023-02-08T17:13:25.284617383+01:00 level=debug msg="Attempting to sync admin configs" count=0
logger=ngalert.sender.router t=2023-02-08T17:13:25.284741473+01:00 level=debug msg="Finish of admin configuration sync"
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:13:25.486827507+01:00 level=debug msg="synchronizing Alertmanagers for orgs"
logger=alertmanager org=1 t=2023-02-08T17:13:25.510088347+01:00 level=debug msg="neither config nor template have changed, skipping configuration sync."
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:13:25.533491112+01:00 level=debug msg="done synchronizing Alertmanagers for orgs"
logger=ngalert.scheduler t=2023-02-08T17:13:30.011726141+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.scheduler t=2023-02-08T17:13:40.013016302+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:13:40.201386458+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:13:40.201367833+01:00
logger=ngalert.scheduler t=2023-02-08T17:13:50.011555328+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:13:55.201299716+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:13:55.201280538+01:00
logger=ngalert.scheduler t=2023-02-08T17:14:00.012990203+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.scheduler t=2023-02-08T17:14:10.012166672+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-02-08T17:14:10.201372389+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:14:10.201343977+01:00
logger=ngalert.scheduler t=2023-02-08T17:14:20.011457226+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=secrets t=2023-02-08T17:14:25.188627915+01:00 level=debug msg="Removing expired data keys from cache..."
logger=secrets t=2023-02-08T17:14:25.188858095+01:00 level=debug msg="Removing expired data keys from cache finished successfully"
logger=ngalert.state.manager t=2023-02-08T17:14:25.201337026+01:00 level=debug msg="Recording state cache metrics" now=2023-02-08T17:14:25.201313339+01:00
logger=ngalert.sender.router t=2023-02-08T17:14:25.296497157+01:00 level=debug msg="Attempting to sync admin configs" count=0
logger=ngalert.sender.router t=2023-02-08T17:14:25.296653724+01:00 level=debug msg="Finish of admin configuration sync"
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:14:25.53448011+01:00 level=debug msg="synchronizing Alertmanagers for orgs"
logger=alertmanager org=1 t=2023-02-08T17:14:25.557270121+01:00 level=debug msg="neither config nor template have changed, skipping configuration sync."
logger=ngalert.multiorg.alertmanager t=2023-02-08T17:14:25.579974726+01:00 level=debug msg="done synchronizing Alertmanagers for orgs"
logger=ngalert.scheduler t=2023-02-08T17:14:30.012380167+01:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
```

Here's also a screenshot of DevTools on the iOS emulator:
![image](https://user-images.githubusercontent.com/19311511/217592034-9d3f9850-5ee0-48b7-b061-9518162d2b95.png)

**Comment by natellium** [comment]
@szerwi sorry it took a while to get back to you. Could you check if it works when you disable anonymous access? As an alternative, you could check our alpha [public dashboards feature](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/), it's under development and has some limitations but we're actively working on it.

**Comment by szerwi** [comment]
Hi @natellium. As I mentioned in the previous comment, after disabling anonymous access it wasn't working either.

> Login page (when anonymous access was disabled) wasn't loading either.

Unfortunately public dashboards are not an option in my situation, as there is another bug reported by me that stops me from using that feature: https://github.com/grafana/grafana/issues/62431

**Comment by gelicia** [comment]
This is reproducible on Safari on OSX - the woff2 font file seems to hang, although I'm not sure how that could be different than how we serve fonts on a local instance (which is fine) or hang the whole site. This might be unrelated.

**Comment by natellium** [comment]
@szerwi sorry we don't have much to report back. We haven't heard any other reports of this happening so it's been hard to prioritise this issue. Could you try upgrading to 9.5? We had some fixes that may do something for your dashboard.

**Comment by szerwi** [comment]
Issue is still present on 9.5.1.
@natellium Have you checked whether you are able to reproduce it using my website, or is it working ok on your iOS devices?

**Comment by natellium** [comment]
I was indeed able to reproduce it on Safari OSX. @szerwi are you by any chance using Grafana Live?

**Comment by szerwi** [comment]
@natellium No, I have never used Grafana Live. Apart from normal Grafana's panels & a few plugins, I only have small script that gets data from specific URL and shows it in the text panel.
```
<html>
<body>
	<div style="display:flex; width:100%; height:100%; align-items:start; justify-content: center;">
		<div>
			<p style="font-size:18px; text-align:center; font-family:Roboto,Helvetica Neue,Arial,sans-serif; font-weight:500; color:#d8d9da;" id="sager"></p>
		</div>
	</div>
  <script>
  
	var forecastDone;
  
    document.addEventListener("DOMContentLoaded", function(){
		}); {
		timeInterval = setInterval(checkTime, 10000);
		getData();
		};
    
		function checkTime() {
			var date = new Date();
			if((date.getMinutes() % 10 == 0) && (date.getSeconds() > 10) && (forecastDone == 0)) {
				getData();
			}
			else if((date.getMinutes() % 10 != 0) && (forecastDone == 1)) {
				forecastDone = 0;
			}
		}
	
		function getData() {
			var url = 'https://stacjameteommz.pl/forecasts/minsk_mazowiecki_1.txt';
			fetch(url)
				.then(function(response) {
					response.text().then(function(text) {
						var t = document.getElementById("sager");
						t.textContent = text;
						forecastDone = 1;
					});
				});
		}
  </script>
</body>
</html>
```

**Comment by natellium** [comment]
💡 It might be Grafana Live then. I noticed an error I hadn't seen before in the console. `[Error] WebSocket connection to 'wss://stacjameteommz.pl/api/live/ws' failed: There was a bad response from the server.`

@ryantxu do you think it's related? And who could help with it?

**Comment by szerwi** [comment]
I also host Grafana behind nginx. I noticed that you recommend specific nginx config to handle WebSocket: https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-live/#websocket-and-proxies

Is it possible that incorrect nginx configuration is working ok on Windows/Android and freezes dashboard loading on macOS/iOS?

Later today I will change nginx configuration and check if it helps.

**Comment by natellium** [comment]
> Is it possible that incorrect nginx configuration is working ok on Windows/Android and freezes dashboard loading on macOS/iOS?
Idk enough about it to be able to answer this tbh. Hope my colleague above can help

> Later today I will change nginx configuration and check if it helps.
👍

**Comment by szerwi** [comment]
I have updated the nginx configuration - now WebSocket starts correctly on Chrome browser and Windows system. However, on the iOS the dashboard is still not loading. I was testing it on the iOS online device which restricts the session length to 1 minute.
I have made nginx changes on my website, so you can test it by yourself on the real Apple device.

**Comment by natellium** [comment]
@szerwi Just to confirm: you're now running 9.5.0, right?

**Comment by natellium** [comment]
@szerwi Can you check the ngnix logs and see if there's anything suspicious? A colleague manage to see an error once, but we haven't been able to reproduce it.

**Comment by szerwi** [comment]
@natellium Which error are you not able to reproduce? The Grafana Live issue, or does my dashboard load properly for you?

**Comment by natellium** [comment]
@szerwi No, the dashboard is still not working. But a colleague managed to see a 500-something error once, just hasn't been able to get that again. We're wondering if you'd be able to see that error in the ngix logs.

Another question: It seems there's some redirection happening when accessing your instance that takes you to the dashboard, how's that set up?

**Comment by szerwi** [comment]
I have also noticed 500 error twice today on Windows and Google Chrome. It started happening after my yesterday's changes, but I believe it is not related to iOS issue in specific. I think it may occur because I have enabled `multi_accept` yesterday. I have just disabled it again to see if it'll help.

Here is my current nginx config:
```
events {
        worker_connections 2048;
        #multi_accept on;
}

http {
        [...]

        map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
        }

        server {
                listen 443 ssl;
                ssl_certificate [cert_file-censored];
                ssl_certificate_key [key_file-censored];
                server_name stacjameteommz.pl www.stacjameteommz.pl;
                keepalive_timeout 60;

                location / {
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection $connection_upgrade;
                        proxy_set_header Host $host;
                        proxy_set_header X-Forwarded-Proto $scheme;

                        proxy_pass https://localhost:30016/;
                }
                location = / {
                        return 301 https://stacjameteommz.pl/d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv;
                }
                location /ads.txt {
                        root /usr/share/grafana/public;
                }
                location /app-ads.txt {
                        root /usr/share/grafana/public;
                }
                location /app_privacy_policy.html {
                        root /usr/share/grafana/public;
                }
                location /forecasts/ {
                        root /usr/share/grafana/public;
                }
        }

        server {
                listen 80;
                server_name stacjameteommz.pl www.stacjameteommz.pl;

                return 301 https://stacjameteommz.pl$request_uri;
        }
}
```

**Comment by szerwi** [comment]
@evictorero Thank you for the suggestions. Have you checked if it works on your Grafana instance with SSL turned on? May it be the problem related to using Grafana with SSL?

On my server I think there are only nginx and Grafana that may cause that issue. Other things that I have on the server are not related (InfluxDB, Telegraf, some Python scripts that run locally). I don't use any load balancer. Do you find something unusual in my nginx config that I've posted above?
Maybe the problem is that I use Grafana on non-standard port?

**Comment by evictorero** [comment]
Turn on SSL it's a pretty common use case and we don't have issues or escalations related to this, the same as using Grafana on a non-standard port.

I don't see anything unusual in your nginx configuration but I will try a fresh install with default configurations to confirm where the problem is.

**Comment by szerwi** [comment]
Hi,

I got access to a real IPhone device and I managed to get logs from the server when trying to enter my website from an IPhone.  The website was not loading indeed. Unfortunately, I wasn't able to use developer tools and get logs from the Safari browser itself.

The first unusual thing that I've noticed for now are the `Bad Request` queries to `/api/ds/query`. They also happen on Windows and Google Chrome:
```
logger=tsdb.influx_flux t=2023-04-30T00:23:25.705658078+02:00 level=warn msg="Flux query failed" err="invalid: error @1:1-1:5: undefined identifier SHOW\n\nerror @1:6-1:15: undefined identifier RETENTION\n\nerror @1:16-1:24: undefined identifier POLICIES\n\nerror @1:25-1:27: undefined identifier on" query="SHOW RETENTION POLICIES on \"undefined\""
```

I only use two InfluxDB 2.0 data sources (both set to the same localhost server, they just have different organizations set) that are set to Flux language.
Why is the Grafana sending multiple InfluxQL (`SHOW RETENTION POLICIES`) queries at every dashboard refresh? I believe it is an unexpected behaviour that may freeze the dashboard load on iOS/macOS.

Apart from this, I have not found any more unusual logs. Here are the logs from nginx (`access.log`) when IPhone is accessing the website:
```
[censored_IPhone_IP] - - [30/Apr/2023:00:23:27 +0200] "GET /d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv HTTP/1.1" 200 8093 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
[censored_IPhone_IP] - - [30/Apr/2023:00:23:28 +0200] "GET /public/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2 HTTP/1.1" 304 0 "https://stacjameteommz.pl/d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
[censored_IPhone_IP] - - [30/Apr/2023:00:23:28 +0200] "GET /public/img/grafana_icon.svg HTTP/1.1" 304 0 "https://stacjameteommz.pl/d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
[censored_IPhone_IP] - - [30/Apr/2023:00:23:28 +0200] "GET /public/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0 "https://stacjameteommz.pl/d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
[censored_IPhone_IP] - - [30/Apr/2023:00:23:29 +0200] "GET /api/dashboards/uid/1 HTTP/1.1" 200 7753 "https://stacjameteommz.pl/d/1/stacja-meteorologiczna-minsk-mazowiecki?kiosk=tv" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
```
There are no logs from the same time in nginx `error.log` file.

@evictorero @natellium Could you take a look at the above logs?

**Comment by evictorero** [comment]
We have confirmed this is not related to a particular dashboard but to the Grafana instance and the problem is this [grafana instance](https://stacjameteommz.pl/dashboards) is not loading on Safari (iOS and OS X). 
Changed labels asking for help to @grafana/backend-platform team.

**Comment by sw-lyons** [comment]
I have a similar issue, on my MacBook Pro 2018 13-inch running macOS Monterey 12.6. I run Firefox 112.0.1. It also occurs on another iPhone running Safari but I don't have the details on it. My instance is hosted on Docker(can provide config if needed) and proxied via Cloudflared. I also see that font hanging sometimes, but also I see it load sometimes.

I am able to access the instance from my android phone running Firefox, and my desktop that also runs Firefox.  I am also able to access the instance on Safari (both on mac and iphone) when I check from my local network via the ip. So I think there would be some issue with proxy stuff, but I am not well versed in that. 

Console Logs:
unreachable code after return statement 7490.cf2da2a42f577bdb1843.js:44:2653
unreachable code after return statement 7490.cf2da2a42f577bdb1843.js:44:4982
Uncaught SyntaxError: identifier starts immediately after numeric literal 7490.cf2da2a42f577bdb1843.js:187:4516
Navigated to https://grafana.dwch.xyz/
unreachable code after return statement 7490.cf2da2a42f577bdb1843.js:44:2653
unreachable code after return statement 7490.cf2da2a42f577bdb1843.js:44:4982
Uncaught SyntaxError: identifier starts immediately after numeric literal 7490.cf2da2a42f577bdb1843.js:187:4516

I ran the debug and it exceptions at "Error: No Such Storage Entry: currentUser" in content.min.js:2

**Comment by tolzhabayev** [comment]
@szerwi in your case it's the google tag manager, remove it (or block it in your browser to test) and it will run on safari and it will work, just tested it locally.

**Comment by szerwi** [comment]
@tolzhabayev Thank you for checking my case.
I have changed my Google Tag Manager script to set the viewport tag to `content="width=1024"', as I want to force the desktop Grafana view on mobiles.
Unfortunately, it seems that is is not working either on iOS. I have checked it only on the online iOS device, which limits the session length to 1 minute. Could you see it by yourself to check what's causing the issue now?

**Comment by tolzhabayev** [comment]
@szerwi It might be some other script / tag in your google tag manager, I think you can find it out by yourself. Just remove tag manager completely and see that it works, then it's up to you to go through your tags and figure out which one crashes / hangs up safari.

**Comment by szerwi** [comment]
I've found the source of the issue. Other script from my Google Tag Manager is freezing the page on iOS/macOS. The issue is with this line:
```mutation.target.textContent = "new_title"```

in script:
```
<script>
  var target = document.querySelector('head > title');
  var observer = new window.WebKitMutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      mutation.target.textContent = "new_title"
    });
  });
  observer.observe(target, { subtree: true, characterData: true, childList: true });
</script>
```

That's a bit strange, because MutationObservers are supported in Safari. However, I've changed the way to change page's title and now it is working well on both iOS and macOS.

Should we close the issue now, as other people in this issue had commented about similar issue that may be caused by Grafana itself?

**Comment by gelicia** [comment]
@szerwi Makes sense to me. Sorry this was such a frustrating experience, hopefully you can go into the weekend feeling happy you found a solution!

**Comment by szerwi** [comment]
Thank you everyone for helping me with finding the source of the issue, as my access to iOS/macOS devices was limited ;)
