### ISSUE TITLE
Queries through grafana against InfluxDB slow

### ISSUE THREAD

**Issue by Thubo** [grafana/grafana#6308]
**I'm submitting a ...**
- [x] Bug report

(Not exactly sure if it's really a bug, but I'm having a hard time identifying the bottleneck.)
The Queries, when run via curl from the commandline work fine, while queries through the GUI take a very long time. It doesn't matter if it's the simple 'Test Connection' query or more complex queries in my dashboards.

Any help debugging/identifying the issue is appreciated.

**Information**

- What Grafana version are you using?

```
# dpkg -l | grep grafana
ii  grafana                   4.0.0-1476697633pre1      amd64        Grafana
```

```3.1.1-147004``` shows the same symptoms (which is why I'm not sure if it's really a grafana issue)

- What datasource are you using?

InfluxDB 1.0.1

- What OS are you running grafana on?

Docker 1.12.1 on Ubuntu 14.04 with Convoy Devicemapper (LVM) Storage

- What did you do?

Query the InfluxDB via Grafana

- What was the expected result?

Queries should take times in the order of ms
```
root@150f8cb6d693:~# time curl -i -XPOST http://influxdb:8086/query?db=_internal --data-urlencode "q=SHOW MEASUREMENTS LIMIT 1"
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: 453720ce-950e-11e6-84d5-000000000000
X-Influxdb-Version: 1.0.1
Date: Tue, 18 Oct 2016 08:38:40 GMT
Transfer-Encoding: chunked

{"results":[{"series":[{"name":"measurements","columns":["name"],"values":[["cq"]]}]}]}

real    0m0.013s
user    0m0.009s
sys     0m0.000s
```

- What happened instead?

Queries take seconds

- An image or text representation of your metric query

<img width="1066" alt="grafana timing" src="https://cloud.githubusercontent.com/assets/4083975/19470453/eb377ad4-951f-11e6-8d1d-e40ef548f0f3.png">

- Request body 

```
Request URL:http://<MyIPHere>/api/datasources/proxy/2/query?db=_internal&q=SHOW%20MEASUREMENTS%20LIMIT%201&epoch=ms
Request Method:GET
Status Code:200 OK
Remote Address:<MyIPHere>:80
Response Headers

Content-Encoding:gzip
Content-Length:100
Content-Type:application/json
Date:Tue, 18 Oct 2016 08:29:54 GMT
Request-Id:0bf175cf-950d-11e6-bb78-000000000000
X-Influxdb-Version:1.0.1
Request Headers

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,de;q=0.6
Connection:keep-alive
Cookie:grafana_sess=fc6f5e799756a66d
DNT:1
Host:<MyIPHere>
Referer:http://<MyIPHere>/datasources/edit/2
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Query String Parameters

db:_internal
q:SHOW MEASUREMENTS LIMIT 1
epoch:ms
```

- request response

```
{"results":[{"series":[{"name":"measurements","columns":["name"],"values":[["cq"]]}]}]}
```

**Comment by bergquist** [comment]
@Thubo Could you please test restarting the service and query again? Just to see if that makes it faster. I'm not saying its a fix but it might help us understand why :)

**Comment by torkelo** [comment]
you can change in the UI from proxy to direct to make the test from the browser, any timing difference? what database do you use for Grafana? sqlite or mysql or postgres?

**Comment by Thubo** [comment]
Thanks for the quick reply.

@bergquist I killed & removed the docker container. After the 'restart' it still looks the same. The data is stored outside and mounted, however removing the data and starting with an empty grafana doesn't help either.

@torkelo A direct request is not possible, since the influxdb is only bound to 127.0.0.1 on the same host as the grafana instance. The database is sqlite (default with the docker container?).

The load of the server is close to zero, I also have approx. 5 GB of free RAM.

**Comment by torkelo** [comment]
the only thing I can think of the docker storage driver is slow or the link between the containers is slow. 

have not seen anything like this reported before so not sure what is causing the delay.

**Comment by Thubo** [comment]
@torkelo Do you have any hints/docs how to debug those? (especially within grafana, since simple curls are working as expected)

**Comment by torkelo** [comment]
are you doing the curls from within the grafana docker container? Are other grafana api calls (save/load /search dashboard for example) also slow?

**Comment by Thubo** [comment]
I'm doing the curls from the grafana to the influxdb. The grafana GUI is fine, no delays there. Only the queries (see also the screenshot) are slow.

The instance is pretty much empty, it's only for testing, playing around - so nothing critical there. Nevertheless it would be nice how to debug / investigate the issue for production systems.

**Comment by torkelo** [comment]
tcp trace, iostat, docker container monitoring. Not sure. No one else has reported anything similar and not a docker expert

**Comment by k1ng87** [comment]
I'm noticing the same thing on my end...running the queries manually in influx CLI is fast but running them in Grafana, either via proxy or direct, they are extremely slow in comparison to performance in the influx CLI. I'm not using docker, I'm using the grafana rpm.

**Comment by torkelo** [comment]
make sure dns lookup is working as expected between grafana-server and influxdb. The only reports of slow downs we have has been due to network/dns issues, otherwise the quey should not be slowed down by more than 1ms at most.

**Comment by k1ng87** [comment]
I'm using IP address for the connection string....don't have influx setup on a hostname yet so just hooked in via IP. I don't believe its Influx as the same queries in Influx's Chronograf (not installed on the same box as influx either) run fast.

**Comment by daniellee** [comment]
@k1ng87 are you sure it's the same query being run in Grafana and in Chronograph? Can you [check the Chrome network tab](https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50) to see if the query and response are the same.

**Comment by Thubo** [comment]
My apologies, apparently I forgot to post my 'solution':
I had a wrong DNS configuration, since the docker container did not inherit the correct search domain. Once I fixed that the queries worked as expected.

Sorry I can't help - but at least for me @torkelo pointed me in the right direction. (Doing a proper network analysis helped a lot.)
