### ISSUE TITLE
Table: HTML in table content

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#63100]
Grafana's `table` is missing a big feature it already had in versions 6.x and earlier. 

It was possible to render HTML content, i.e. images, in cells by using the ["Sanitize HTML" option](https://i.postimg.cc/L54YdX0M/sanitize-html.png). For a detailed explanation of the differences, see the [attached screen shot](https://i.postimg.cc/x1KSDRrL/grafana-html-support.png).

Since it was a powerful and for me essential feature of Grafana, can anyone tell me when this will be integrated back into the `table` visualisation? Or if it will ever come back?

**Comment by usmangt** [comment]
Hi @yulipumal,

Thanks for opening this issue.

This option is now moved into the backend configuration file.

You can take a look at this [community post](https://community.grafana.com/t/how-to-set-disable-sanitize-html-to-true/30404/4) as a reference on how to use it.

I hope this helps.

**Comment by yulipumal** [comment]
Hi @usmangt , thanks for your answer. 


Unfortunately, this does not solve the problem. Your link suggests to disable HTML sanitizing (against xss vulnerability). That is relevant for panels that allow HTML. However, my issue is that the `table` panel does not support HTML at all since version 7.x.

I created a grafana dashboard [demo](http://jsonblob.com/1073205951921930240).

**Comment by usmangt** [comment]
Thanks for the quick reply and for providing more information.

Well, this feature is not available and there is already an open issue (https://github.com/grafana/grafana/issues/24482) where users have the same opinion. Please follow the discussion there as there are some workarounds (e.g. [this one](https://grafana.com/grafana/plugins/marcusolsson-dynamictext-panel/)) also posted.

I will close this one

**Comment by yulipumal** [comment]
Thanks for mentioning the dynamictext-panel workaround. 

This, however, does not replace the Grafana table panel with HTML. A manually created table with this workaround needs to be filled for each column and has not the grafana build-in table features as SortByColumn, overwrites etc.

Are there any plans to make the grafana `table` panel with HTML support available again? If not, why was it withdrawn with version 7.x?

**Comment by usmangt** [comment]
Out of many, the one main reason was that in the earlier versions of Grafana, Angular technology was used for the Panel development but due to its limitations and performance issues moved to TypeScript and therefore many changes happens (on both small and big levels).

Though I see that the developer did mark it as a feature request and has not yet closed the issue so it is definitely in the radar but will have to wait for the ETA.
