### ISSUE TITLE
Graph overflowing

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6312]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? Version 3.1.1 (commit: a4d2708) (from `grafana-server -v`)
- What datasource are you using? InfluxDB shell version: 1.0.2
- What OS are you running grafana on? Ubuntu 14.04.5 LTS
- What did you do?

2 50% width (1 singlestat, one graph). Add a new item to the row, (plugin table). Then close out of the plug in table, and delete it.

- What was the expected result?

That the rows are not overflowing.
- What happened instead?

The rows overflowed.

![image](https://cloud.githubusercontent.com/assets/842974/19484818/cf2db26e-9550-11e6-91df-4bf5266ea269.png)

It fixes itself on a page request; but happens a couple of times.

**Comment by torkelo** [comment]
unable to replicate this :(

**Comment by alexbowers** [comment]
I'll try to record it

**Comment by alexbowers** [comment]
https://youtu.be/9YLqOoaXUvk

**Comment by torkelo** [comment]
thanks for doing the video, made it easy for me to replicate and find the issue! Fixed in master now!

**Comment by alexbowers** [comment]
Great. Thanks.
