### ISSUE TITLE
Improve changelog generation to avoid overly large files

### ISSUE THREAD

**Issue by zerok** [grafana/grafana#63122]
**What happened**:

The `CHANGELOG.md` has gotten so large that it can no longer be previewed on  GitHub **sometimes**. Instead, a warning is shown.

**What you expected to happen**:

The changelog should render properly at least for the most recent releases.

**How to reproduce it (as minimally and precisely as possible)**:

Sadly, it's not yet reliably reproducible.

## Proposed fix

- Move everything that is not the latest major release into the changelog archive folder
- Update the `update-changelog` GHA to handle the case where the currently-processed-release is not in the main file but inside the archive
- Alternatively, create a file *per* release and use the main changelog file to just link to those

**Comment by GrafanaWriter** [comment]
Removing the `type/docs` label as this isn't managed by the Docs team.
