### ISSUE TITLE
Hour should be plural

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6313]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB 1.0.2

This is a conversion from seconds. The number is roughly `5000` seconds

![image](https://cloud.githubusercontent.com/assets/842974/19487345/560d02a4-955a-11e6-8ed8-e8fb6953f742.png)

![image](https://cloud.githubusercontent.com/assets/842974/19487374/73e52a40-955a-11e6-878f-c0411e862908.png)

**Comment by torkelo** [comment]
this is fixed in master with a new unit named duration , the unit your using is meant for graph panel

**Comment by torkelo** [comment]
actually in think that unit type is in 3.1.1

**Comment by alexbowers** [comment]
It is, but it causes rounding which I don't want. 1.7 hours becomes 2 hours

**Comment by alexbowers** [comment]
@torkelo Is there a way to stop it rounding up in the `duration` type?

**Comment by torkelo** [comment]
not currently, it's using momentjs humanize method which has no rounding option http://momentjs.com/docs/#/durations/humanize/
