### ISSUE TITLE
Feature Request:  Support Painless for Elasticsearch scripted metric aggregations

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#6315]
Elasticsearch has adopted Painless for their scripted metric aggregations and has deprecated Groovy.  I understand Grafana requires Groovy (script.engine.groovy.inline.search: on) is enabled for its scripted metric aggregations to work.

From the ES forum:
_Groovy is a deprecated language that will be replaced with Painless over time. I'd recommend using it minimally and to have a plan to eventually replace it with Painless._

So, for this reason and better security, it would be desirable to support Painless for the scripted metric aggregations.

**Comment by torkelo** [comment]
Grafana does not specify scripting language in the query, so what ever is the default in ES should work

**Comment by sslupsky** [comment]
Hi @torkelo,

As I presently understand the situation, you must enable Groovy scripting for Grafana scripting to work.  Using the default scripting sandbox does not work (this is how I presently have my ES cluster configured).

This is a significant security concern and ES recommends against enabling wide open scripting.

I will ask you to reopen this issue.

**Comment by torkelo** [comment]
since Grafana does not specify scripting language in the query, you can just change the ES scripting language default

https://github.com/elastic/elasticsearch/pull/20017

**Comment by sslupsky** [comment]
Thanks for that ... it help understand the background of what ES may be thinking of doing with the 5.0 stack.  For the moment I suspect many Grafana users are using pre-5.0 so I think it would help if we specified the lang directive in the query as Painless so the scripts could execute in the sandbox.  It appears from this thread that specifying the language is likely to become a mandatory requirement in the future.

**Comment by torkelo** [comment]
was not aware that the painless scripting language was available in Elasticsearch versions prior to 5.x
