### ISSUE TITLE
CI fails in forks because it uses secrets unconditionally

### ISSUE THREAD

**Issue by jsoref** [grafana/grafana#63163]
**What happened**:

Lots of workflows fail when triggered in forks

**What you expected to happen**:

* workflows should declare permissions they need
* workflows should verify they have any secrets they need before trying to do work that requires them

**How to reproduce it (as minimally and precisely as possible)**:

1. create an organization
2. set the organization permissions to readonly instead of read write https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions
3. create a fork of the grafana repository
4. go to actions and enable actions (there are ways that they'll be automatically triggered)
5. you can just wait for a scheduled task to run, or you can trigger various events (e.g. creating an issue in your fork w/ a label, or creating a PR in your fork)

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
:Hi @jsoref,

Thanks for opening this issue.

I am not an expert with the GitHub workflow and automation, but the workflow will likely fail because the GitHub Secrets are not forked. 

I will pass this one to the team if they can share the guide (or documentation) as how to do it (if applicable).
