### ISSUE TITLE
Define the Cloudwatch DataSource Via the API

### ISSUE THREAD

**Issue by thelamer** [grafana/grafana#6316]
* **I'm submitting a ...**
- [X ] Feature request

Grafana: Version v3.1.1
DataSource: CloudWatch
OS: Debian Jessie

I am trying to add a cloudwatch datasource via the API and I am not able to determine the variables or structure to pass for things like : 
- Credentials profile name
- Default Region
- Custom Metrics namespace
- Assume Role ARN

I can create a non working data source using the Json: 
`{"name":"AWS","type":"cloudwatch","access":"proxy"}`

And then need to go into the web interface to set the remaining settings. 

This is either a lack of documentation or a missing feature. 

Side note, please let us define data sources using a local file or bake it into the config. Having to do it post spin up it pretty counter intuitive in the world of dockerized kill and replace micro services.

**Comment by torkelo** [comment]
You can sett everything in the http api, the UI is using the exact same api, just look at the request it makes
