### ISSUE TITLE
Multiple open db connections using Postgres datasource

### ISSUE THREAD

**Issue by n4ch04** [grafana/grafana#63179]
**What happened**:
Using Grafana with Postgres datasource we have realised that it is generating multiple db connections each time a dashboard is opened.
We had an scenario with multiple users (each one inside an organization)  with its postgresql datasource configured for each user, and while we were iterating over each organization changing dashboards the db started to fail due to the multiple opened connections coming from Grafana.

To test it we opened a dashboard, we edit 3 panels and this results in 4 new connections to the database.

The datasource is configured with default settings.

**What you expected to happen**:

We don't know if we need to set a concrete settings when configuring the datasource to avoid this behaviour, but we were expecting Grafana to send all the queries coming from a datasource using a single session/connection, instead of open a connection for each single query.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a Grafana instance with postgresql db, create an org with a user and a new dashbaord with various panels. Then checking at the same time the db opened connections, open the dashboard in a browser and start editing the panels (each panel with a query). Check how db connections begin to rise.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: Postgresql - latest for this version
- OS Grafana is installed on: Official container for that version
- User OS & Browser: MacOS - Google Chrome
- Grafana plugins: None
- Others:

**Comment by usmangt** [comment]
Hi @n4ch04,

Thanks for opening this issue.

We do have this [documentation](https://grafana.com/docs/grafana/latest/datasources/postgres/) on how to configure the PostgreSQL datasource correctly. Please have a look and let us if that helps.

**Comment by jfagoagas** [comment]
Hi @usmangt, we've reviewed the documentation you provider before opening the issue, our concern is that we think that the PostgreSQL datasource is opening a lot of DB connections, we suppose to improve the speed of the queries, but maybe the same can be achieved reusing connections and having one database session to send all the queries through them.

**Comment by usmangt** [comment]
Thanks for the detailed reply.

Can you please tell which PostgreSQL version you are using?

**Comment by jfagoagas** [comment]
Sorry, we thought that we had included it in the issue. We are using PostgreSQL 14.3.

**Comment by jfagoagas** [comment]
Hi @usmangt, I'm testing one possible workaround to fix the issue.

**Comment by usmangt** [comment]
Hi @jfagoagas,

I was away and then got diverted into other stuff. Just wanted to get some updates if you have found the workaround?

**Comment by jfagoagas** [comment]
Hi @usmangt, this PR is the workaround https://github.com/grafana/grafana/pull/63246.

I've tested it in our local environment and works fine.

Could you please take a look at it?

Thanks!

**Comment by jfagoagas** [comment]
Hi @usmangt, do we have any updates on this issue and the PR?

Thanks!

**Comment by usmangt** [comment]
Hi @jfagoagas ,

I have already assigned that PR to the right project. They will review it and update to you

**Comment by jfagoagas** [comment]
> Hi @jfagoagas ,
> 
> I have now assigned that PR to the right project. They will review it and update to you

Thanks!

**Comment by papagian** [comment]
thank you for reporting this @n4ch04 
I wonder what are the values of in the `Max idle`, `Max open` and `Max lifetime` options in the [PostgreSQL data source configuration](https://grafana.com/docs/grafana/latest/datasources/postgres/#postgresql-settings) in your setup?

**Comment by jfagoagas** [comment]
> thank you for reporting this @n4ch04 I wonder what are the values of in the `Max idle`, `Max open` and `Max lifetime` options in the [PostgreSQL data source configuration](https://grafana.com/docs/grafana/latest/datasources/postgres/#postgresql-settings) in your setup?

Hi @papagian we have the default values configured for the PostgreSQL datasource although we know that it is not a good practice and we have to properly configure it we saw that the PostgreSQL datasource opens a new database session for each query that is going to be executed, as it can be seen here: https://github.com/grafana/grafana/blob/main/pkg/tsdb/sqleng/sql_engine.go#L268-L270

Maybe fine-tuning the `Max idle`, `Max open` and `Max lifetime` options for the datasource would result in a better performance but I think it is better if all the database queries are executed using the same database session. What do you think?

Thank you!
