### ISSUE TITLE
Image rendering failed : duplicate dashboard uid

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#63187]
**What happened**:
We have several image rendering failed on alerting in logs :
```
logger=ngalert t=2023-02-09T13:39:18.504783417+01:00 level=warn msg="Failed to take an image" dashboard=bsFnDY27k panel=51 error="failed to take screenshot: failed to send request to remote rendering service: Get \"http://XXXX:8081/render?deviceScaleFactor=1.000000&domain=YYYY&encoding=&height=500&renderKey=nX9vHd73LDmTRnzbgs5jIZW1BkPYAcHC&timeout=10&timezone=&url=http%3A%2F%2FYYYY%3A3000%2Fd-solo%2FbsFnDY27k%2Ftest-bandwidth-controller%3ForgId%3D4454%26panelId%3D51%26render%3D1&width=1000\": context deadline exceeded"
```

We can see in the log that it is trying to create an image of :
panel : 51
dashboard : bsFnDY27k 
orgId : 4454

After checking there is indeed no panel 51 on this dashboard.
But there is also no alert rule configured on org 4454.
```
select * from alert_rule where org_id = 4454;
Empty set (0.00 sec)
```

If I try to search the alert rule using the dashboard uid and the panel, I found the alert rule but on another organization 
```
select id, org_id, dashboard_uid, panel_id from alert_rule where dashboard_uid = 'bsFnDY27k' and panel_id = 51;
+-----+--------+---------------+----------+
| id  | org_id | dashboard_uid | panel_id |
+-----+--------+---------------+----------+
| 344 |    731 | bsFnDY27k     |       51 |
+-----+--------+---------------+----------+
```

So I have an alert rule configured for org : 731, dashboard : bsFnDY27k and panel : 51
But it tries to take a screenshot of org : 4454, dashboard: bsFnDY27k and panel : 51

Note that I have multiple dashboards with the same uid : bsFnDY27k 
```
select org_id, uid from dashboard where uid = 'bsFnDY27k';
+--------+-----------+
| org_id | uid       |
+--------+-----------+
|    731 | bsFnDY27k |
|   4454 | bsFnDY27k |
+--------+-----------+
```

**What you expected to happen**:
Grafana should not lost track of the organization.

**Environment**:
- Grafana version: 9.2.10
- OS Grafana is installed on: RHEL8
- Others: remote image renderer v 3.6.3

**Comment by usmangt** [comment]
Hi @deathwarrior60,

Thanks for opening this issue.

Since when you started to encounter this issue e.g. after a recent update or a config change?

Also, does this happens only with this orgID or with others?

**Comment by deathwarrior60** [comment]
Hello,
It happened since we migrate from 8.1 to 9.2 and old alerting to unified alerting.
It is not specific to this orgId, we also have the issue with other org

**Comment by grobinson-grafana** [comment]
This looks like a bug to me, I've opened a pull request here https://github.com/grafana/grafana/pull/63220
