### ISSUE TITLE
Issues with Oauth login (GitHub Enterprise)

### ISSUE THREAD

**Issue by jascsch** [grafana/grafana#63184]
**What happened**:
Im currently trying to enable oauth login for grafana https://ops.dp.app.corpintra.net/grafana but it does not work.
Heres my configuration:

auth.github:
enabled: true
allow_sign_up: true
client_id: 0fdf5c35d8526383c251
client_secret: xxx
scopes: user:email,read:org
auth_url: https://git.i.mercedes-benz.com/login/oauth/authorize
token_url: https://git.i.mercedes-benz.com/login/oauth/access_token
api_url: https://git.i.mercedes-benz.com/api/v3/users
team_ids: 4370

And the error message is:
```
logger=context userId=0 orgId=0 uname= t=2023-02-09T09:58:03.604512408Z level=error msg="login.OAuthLogin(get info from github)" error="error unmarshalling user info: json: cannot unmarshal array into Go value of type struct { Id int "json:\"id\""; Login string "json:\"login\""; Email string "json:\"email\""; Name string "json:\"name\"" }"
logger=context userId=0 orgId=0 uname= t=2023-02-09T09:58:03.604983445Z level=error msg="Request Completed" method=GET path=/login/github status=500 remote_addr=192.168.0.201 time_ms=265 duration=265.920832ms size=1365 referer=https://git.i.mercedes-benz.com/ handler=/login/:name
```

**What you expected to happen**:
The oauth login should work.

**How to reproduce it (as minimally and precisely as possible)**:
I guess that the issue can be reproduced with github enterprise.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2.5
- Data source type & version: Prometheus
- OS Grafana is installed on: K8s
- User OS & Browser: it does not matter
- Grafana plugins: N/A
- Others:

**Comment by usmangt** [comment]
Hi @jascsch,

Thanks for opening this issue.

We do have this documentation on how to configure the OAuth for GitHub. The configuration you posted looks fine, but there are also some more details provided which need to be defined e.g. `root_url` (if behind a proxy), `allow_sign_up`, configuring etc. Please have a look and see if you also have all those correctly defined.


If still having issues with the above error message, then let us know

**Comment by jascsch** [comment]
thanks for the feedback.
yes, I have followed the docu here and still having issues: 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/

the root_url is configured and allow_sign_up is set to true.
It´s about this error message here:
```
logger=context userId=0 orgId=0 uname= t=2023-02-09T09:58:03.604512408Z level=error msg="login.OAuthLogin(get info from github)" error="error unmarshalling user info: json: cannot unmarshal array into Go value of type struct { Id int "json:\"id\""; Login string "json:\"login\""; Email string "json:\"email\""; Name string "json:\"name\"" }"
logger=context userId=0 orgId=0 uname= t=2023-02-09T09:58:03.604983445Z level=error msg="Request Completed" method=GET path=/login/github status=500 remote_addr=192.168.0.201 time_ms=265 duration=265.920832ms size=1365 referer=https://git.i.mercedes-benz.com/ handler=/login/:name
```
Can you please advise how to fix this?

**Comment by slillibri** [comment]
I am able to reproduce this error, when `team_ids` contains only 1 value. If it has more than one value, either by duplicating the original value or using `0`, or adding a trailing comma `,` to the single value the team match works. I am just using GitHub (not Enterprise).

To recap
`team_ids: 12345` doesn't work
`team_ids: 12345,` works
`team_ids: 12345,12345` works
`team_ids: 12345,0` works

**Comment by gamab** [comment]
I'll close this issue as it seems to be stale :slightly_smiling_face:
