### ISSUE TITLE
Alert rules are not longer applied individually when using group by Terms for elasticsearch data source

### ISSUE THREAD

**Issue by stefankaufmann** [grafana/grafana#63199]
**What happened**:
We configured an alert rule on an elasticsearch data source (7.x) which applies to multiple servers. The rule is using the group by `Terms` on the url of the server. In Grafana version `9.1.7` we got  alerts individually for every URL we are monitoring. For example: 

- The alert starts firing for server 1
- after 1 hour the alert rule also matches for server 2 (server 1 still firing)

A second alert is sent for server 2

**Now after upgrading to Grafana `9.3.x`, the second alert message is not sent anymore**

**What you expected to happen**:
We expect to get a second alert message, if an additional alert condition is fulfilled for any of the servers

**How to reproduce it (as minimally and precisely as possible)**:
This is our alert rule
![image](https://user-images.githubusercontent.com/7921443/217842342-c790d351-f0e6-4a62-ad6e-2f3e9296df59.png)

And these are the notification policies
![image](https://user-images.githubusercontent.com/7921443/217842590-61c9795a-88ce-4219-9e10-0e5205e08688.png)

To reproduce this, you need to trigger 2 entries with different `url.full` to have `summary.down` jumping from `0` to `1`. You need to wait ~ 1 minute before you trigger the second alert because of the group wait policy of 30s. 

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Elasticsearch 7.17.9
- OS Grafana is installed on: Ubuntu 20.04 (Server)

**Comment by grobinson-grafana** [comment]
Hi! Would it be possible to clarify that in Grafana 9.1.7 you were receiving multiple alerts for this rule, and now in Grafana 9.3.6 you are only receiving a single alert? The reason I ask is that Classic Conditions should never create more than one alert for an individual alert rule, so the behaviour you are seeing in 9.3.6 looks to be correct to me. If you would like to receive multiple alerts per URL you might want to consider using a Reduce + Threshold or Reduce + Math expression. You can find more information on how to set up multi-dimensional alerting in our docs.

**Comment by armandgrillet** [comment]
Closing as no answer for than 5 months, please reopen if you have more details and are still experiencing the issue.
