### ISSUE TITLE
include list of viz that support annotations

### ISSUE THREAD

**Issue by tonypowa** [grafana/grafana#63194]
in the bellow docs regarding annotations (there might be more out there), there is no mention of which visualizations (time series, etc) support annotations. 

https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/

https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/annotations/

from the community support squad we believe that it would be beneficial for users to know if they can use annotations for their use case

note: tagging multiple squads (plus the docs squad) since it looks like an overlapping topic. It be great if somebody could help listing all the viz that support annotations. 

feel free to reach out to me if any questions :)

**Comment by imatwawana** [comment]
This was addressed on PR #70208 for this page https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/

For the other page, the content is about the Annotations list visualization type, which is a visualization that shows you which annotations are in use in Grafana. So this doesn't apply in this case.

Closing this issue as complete.
