### ISSUE TITLE
Singlestat Coloring issue when thresholds is negative

### ISSUE THREAD

**Issue by Fatekiller23** [grafana/grafana#6320]
* **I'm submitting a **
- [x] Bug report

Please include this information:
version: grafana 3.1.1
datasource: influxdb
OS:             centOS 6.5
i want to set negative threshold for changing background color.
when the value is negative, the value **text color is changed** but the corresponding **background color not.**
the value text color and the background color should be **the same** in my opinion.
the image below shows my screen.
![image](https://cloud.githubusercontent.com/assets/13780769/19510497/187e0156-9616-11e6-9c81-d2b739b8ded9.png)

please help me if you great guys have any idea about that, thx

**Comment by torkelo** [comment]
unable to replicate the issue here:
http://play.grafana.org/dashboard/db/issue-6320?panelId=21&fullscreen&edit

**Comment by Fatekiller23** [comment]
![image](https://cloud.githubusercontent.com/assets/13780769/19513690/6afd23d2-9623-11e6-9a63-2a2af7412a05.png)
so my issue is still here . 
how to fix that? i mean background and text 's color  to be the same

**Comment by torkelo** [comment]
Still cant replicate, what browser and os are you using?
<img width="782" alt="screen shot 2016-10-19 at 16 08 55" src="https://cloud.githubusercontent.com/assets/10999/19522124/65e1cfc2-9616-11e6-98f2-265b42949383.png">

**Comment by Fatekiller23** [comment]
browser:chrome
os : this time is win10 
but i think the key point is not the OS and browser i use.
This issue only appeared when the value is negative .not the threshold.  
To replicate this issue:

1. change data source to test meric
![image](https://cloud.githubusercontent.com/assets/13780769/19543089/16d20e24-96a7-11e6-93d5-4700a5e9cc3b.png)
2. click refresh button until you get a negative value.
3. ten the background color is not the same as text value color.

and thanks for replying ~~

**Comment by Fatekiller23** [comment]
i found the reason.
![image](https://cloud.githubusercontent.com/assets/13780769/19561741/6cf5da46-970c-11e6-9882-2f6d98f17fe6.png)
cause the negative value is defined as NaN by q.valueRounded,so the solution here is quite simple.write the right logic or add abs() function and q.value as a condition.
thanks!
