### ISSUE TITLE
Alert rules page: "RangeError: The start of an interval cannot be after its end" when expanding folders

### ISSUE THREAD

**Issue by fabio-silva** [grafana/grafana#63205]
**What happened**: Grafana might crash on the Alert rules page (/alerting/list) when expanding the rule folders, with the following error: "RangeError: The start of an interval cannot be after its end".

**What you expected to happen**: Expanding a folder should not crash the app

**How to reproduce it (as minimally and precisely as possible)**: This is easily reproducible if Grafana runs on a remote instance.
I noticed it happens if your browser (system) time is behind the instance's time. When Grafana tries to calculate for how long a given alert has been in a given state (e.g."For: 1m"), if the browser time is behind the rule's time (which I guess comes from the Grafana server, which is remote and ahead of us), then date-fns will throw a RangeError.
This should be an actual time difference, not a timezone difference. 
The easiest way is to set the local time behind some minutes and create a rule that gets triggered. By going to the `/alerting/list` page, Grafana will crash.

**Anything else we need to know?**:
File where it happens is RuleState.tsx, when `intervalToAbbreviatedDurationString` is called. But this function is called in other places, so this problem can occur elsewhere.

**Environment**:
- Grafana version: 9.2.5
- OS Grafana is installed on: CentOS
- User OS & Browser: MacOS, Chrome

**Comment by zuchka** [comment]
is this set on your grafana's config?

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#default_timezone

what is the setting on the grafana user lever for your timezone setting?

![CleanShot 2023-02-13 at 10 12 25@2x](https://user-images.githubusercontent.com/37156449/218564872-0492d0b0-598a-471d-8f1b-1c04b06e5646.png)

which CentOS are you running?

details about the alert rule? what datasources?

Can you reproduce creating a prom alert that connects to this public endpoint?

http://demo.robustperception.io:9090/

let's try and remove as many variables as possible so the teams can quickly verify this issue. I am in the Central Pacific and connect to our internal instances running in Europe every day but I can't find a folder that will trigger this. 

I'm sure grafana is crashing for you, we just need as many details as possible. thx

**Comment by fabio-silva** [comment]
@zuchka Thanks for the reply.
I have "browser" in the config file and "Default" on the user preferences.
Grafana server run in a remote CentOS 7.9.2009 Docker image but I use my Mac to access it (Ventura).

In this case, the timezone doesn't have an effect. What causes the crash is an absolute differenc between server/browser, not a relative one caused by timezones.

Any rule can trigger this, as long as you can make it go "Pending" and "Firing", which causes the "For: X" to show up and do the time delta calculation.

If you want to try this, set the time backwards in your own machine by 5m and connect to the Europe instances. Then, cause any rule to trigger. That should do the trick.

Thank you

**Comment by fabio-silva** [comment]
P.S. I have successfully done a local fix for this, but want to know if you can reproduce it and if my fix is good to you.

**Comment by zuchka** [comment]
I would maybe go ahead and draft a PR. The alerting squad can look it over and verify your issue 👍

**Comment by soniaAguilarPeiron** [comment]
Thank you @fabio-silva for spotting this out 🙌. Alerting team is very happy to see and review your PR.
