### ISSUE TITLE
Auth: Refactor org role syncronization

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#63204]
**why/what**
We are syncronizing organization and organization roles from external providers in SAML, LDAP, and OAuth providers. Currently a lot of settings are overlapping and affecting in different steps in the implementation which causes a lot of confusion.

The following settings are involved with synchronizing a user - `oauth_skip_org_role_sync`, `skip_org_role_sync`, `auto_assign_org_role`, `auto_assign_org_id`, `auto_assign_org`, `role_attribute_strict`, `allow_signup`

These settings are check on both a surface levels as well as on calls to the db in multiple places. It would be greatly beneficial if we could simplify the implementation to have the settings less coupled.

here is an outline for an excel we have created that computes the resulting value of the org role based on different settings. https://docs.google.com/spreadsheets/d/1OPXdw2vFReoZuwq154xP6ii04379CC7leJSRsqJANkM/edit?usp=sharing

**DoD**
- [ ] first step is replicate the excel in integration/end to end tests to be able to be more  confident in how different settings affect the resulting sync
- [ ] refactor the implementation to be simpler
- [ ] pentest different flows

**Comment by faxm0dem** [comment]
How are you "syncronizing organization" ?

**Comment by eleijonmarck** [comment]
we want to have that eventually, the scope of this is change to only reflect `org_roles`

**Comment by eleijonmarck** [comment]
closing as we want to make this part of a another release later.
