### ISSUE TITLE
Use of approximate_row_count with $__timeFilter is not working anymore

### ISSUE THREAD

**Issue by philbert10k** [grafana/grafana#63201]
Hello,
I got some issues with using approximate_row_count in dashboard variables...

**What happened**:
After update of Grafana to version 3.6, the use of the command approximate_row_count with $__timeFilter is not working anymore.
Old dashboards created with the variables are still functional, but creating new ones or even modifying existing ones does not give any conclusive result. 

The content of the variable defined in Grafana:
Variable type: Query
Data source: Postgresql
Query: SELECT approximate_row_count('timescaledbtable') AS "numberoflines" WHERE $__timeFilter(time)
time is defined as PK in the table "timescaledbtable"
Refresh: On time range change

**What you expected to happen**:
Showing the result of approximate_row_count as function of the time picker in the dashboard.

**Anything else we need to know?**:
Vacuum and analyze have been run on the used table

**Environment**:
- Grafana version: 3.6
- Data source type & version: Postgresql 14.5
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, MS Edge

**Comment by zuchka** [comment]
> Grafana version: 3.6

I'm guess ing you mean 9.3.6, yes?

What version was this working on before?

please include more precise steps for reproducing this issue. thx

**Comment by philbert10k** [comment]
It seems to be a problem on the side of timescaledb while using the function with arguments.
The issue can be closed.
