### ISSUE TITLE
bug: dashboard post api broken with new "variables" for dashboard sharing. can't import metrictank dashboard

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6321]
I upgraded the [raintank devstack](https://github.com/raintank/raintank-docker) to the latest grafana `v4.0.0-pre1 (commit: v3.1.0-1118-g97008f9)` e.g. 97008f90c4dabc11c2ccd9c364c2c9ec180df712

but I run into issues when importing the metrictank dashboard, which lives at https://github.com/raintank/raintank-docker/blob/master/docker/grafana/dashboards/metrictank.json

this is probably because it now contains some extra metadata for dashboard sharing on grafana.net . in the past it just had a hardcoded `graphite` datasource name, so i could just import it and it would work with the included graphite datasource.

I import like so:
```
  curl -u admin:admin \
    -H "content-type: application/json" \
    'http://localhost:3000/api/dashboards/db' -X POST -d "{\"dashboard\": $(cat $file)}"
```
this used to work fine, but now when I load the dashboard, I get this:

```
Dashboard init failed
Template variables could not be initialized: Datasource named ${DS_GRAPHITE} was not found
```
e.g. the dashboard post api does not work well with the variables (that still need values) used by the new export/import mechanism. it just leaves the variablenames which causes breakage.

My suggestion is:
1) allow setting values that otherwise have to be choosen in UI dialogs,
e.g. if i could pass -d "datasource-graphite=graphite" or something
2) api calls that try to post dashboards but their dependencies are not met or specified, should fail.

( when i Import the dashboard through the UI it works fine, i just have to select a graphite datasource.)

**Comment by torkelo** [comment]
if your trying to import an exported dashboard you need to use the import api, not the regular "save new dashboard" api. 


```
POST /api/dashboards/import
{
  "dashboard": {
    
  },
  "overwrite": true,
  "inputs": [
    {
      "name": "DS_INFLUXPROD",
      "type": "datasource",
      "pluginId": "influxdb",
      "value": "InfluxDB"
    }
  ]
}
```

So to import a dashboard that has gone through the new export process in Grafana 3.1 (this export process templatize the dashboard). You need to use the new import api. 

If you do not wish to use this api you can just use "View JSON" and get the raw json and use the normal save dashboard api

**Comment by Dieterbe** [comment]
thanks @torkelo that seems to work perfectly.
