### ISSUE TITLE
External Users can no longer be configured with IaC 

### ISSUE THREAD

**Issue by pschulten** [grafana/grafana#63219]
**What happened**:
https://github.com/grafana/grafana/pull/58442 was merged and practitioners are no longer able to re-configure an external user from the outside, e.g. with the Grafana terraform provider. They get an error: "User info cannot be updated for external Users"
 
**What you expected to happen**:
Practitioners can still re-configure an existing Grafana user and e.g. toggle the `is_admin` flag

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure grafana.ini with `auth.gitlab`
2. Configure a user with [terraform](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/user) with `is_admin = false` 
3. Configure grafana.ini with `auth.gitlab`
4. Login with this user from gitlab
5. Run your terraform script again with `is_admin = true`

**Anything else we need to know?**:
https://github.com/grafana/grafana/pull/58442#discussion_r1101657015

**Environment**:
- Grafana version: v9.3.1

**Comment by Jguer** [comment]
Hi @pschulten 


The GitLab integration now allows mapping server admin role with the option `allow_assign_grafana_admin = true` under `[auth.gitlab]`

Example mapping: `role_attribute_path = is_admin && 'GrafanaAdmin' || 'Viewer'`

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/gitlab/#map-roles

Would this solve your issue?

**Comment by pschulten** [comment]
It does. Thanks a lot 👍
