### ISSUE TITLE
Toggling between edit modes loses the query

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6323]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1

I can not paste in a query then edit it.

https://youtu.be/DH9GnpkjmIA

**Comment by torkelo** [comment]
InfluxDB Raw Query mode is Raw, the query editor cannot parse it and translate it to its model, you have to pick one mode and use that, not jump between them :(

**Comment by alexbowers** [comment]
@torkelo The query i copied was copied from going into raw mode from a different tab

![image](https://cloud.githubusercontent.com/assets/842974/19516449/eb262d9a-95f3-11e6-970f-20b28fdf9af9.png)


becomes this:

![image](https://cloud.githubusercontent.com/assets/842974/19516453/f11e4d18-95f3-11e6-982e-76ecc73f260a.png)


Which i couldn't paste to become the formatted again.

If it came from the formatted, then it should be able to handle it?

**Comment by torkelo** [comment]
there is no way to "copy" the query for InfluxDB when using the UI query editor :(

**Comment by torkelo** [comment]
you can hit the panel menu -> hamburger --> panel json and copy the query model (under targets)

**Comment by alexbowers** [comment]
Ah i didn't see that menu before.

So what would be the best way to "duplicate" across dashboards?

I want the same panel on multiple areas, but can't find an import JSON
option
