### ISSUE TITLE
When both Row and Panel use the same variable for the repeat option, the query doesn't honor the value set by the row option

### ISSUE THREAD

**Issue by aarontams** [grafana/grafana#63231]
**What happened**:
When both Row and Panel use the same variable for the repeat option, the query doesn't honor the value set by the row option

We have a cluster label baked with the region name. For example:
- my-**use1**-dev-cluster
- my-**use1**-prod-cluster
- my-**use2**-dev-cluster
- my-**use2**-prod-cluster

#### Variable
region: use1 and use2

### Repeat option 
Row: $region
Panel: $cluster

#### query label filter
```
{cluster=~".*-$region-.*", cluster=~"$cluster"}
```

Two rows in the DB
- use1
- use2
Each row will have all four clusters.
- In use1 row, both use2 graphs have no data.
- In use2 row, both use1 graphs have no data.

**What you expected to happen**:
Two rows in the DB
- use1
- use2
Each row will have two clusters

First row **use1**
- my-**use1**-dev-cluster
- my-**use1**-prod-cluster

Second row **use2**
- my-**use2**-dev-cluster
- my-**use2**-prod-cluster

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: AMG from AWS
- Data source type & version:
- OS Grafana is installed on: AWS
- User OS & Browser: Any browser
- Grafana plugins: Time series
- Others:

**Comment by zuchka** [comment]
> How to reproduce it (as minimally and precisely as possible):

please provide simple steps so we can reproduce this. 

also please see this comment:
https://github.com/grafana/grafana/issues/19181#issuecomment-532292169

and this:
https://github.com/grafana/grafana/issues/11263

**Comment by gelicia** [comment]
This looks like it will not be a supported feature, given the two linked to comments. Closing.
