### ISSUE TITLE
JWT authentication fails with status 302

### ISSUE THREAD

**Issue by rohit-innodeed** [grafana/grafana#63254]
I want to embed iframe in my web app for which I am using jwt authentication for maintaining user identity and role checks. 

**Steps to reproduce**:

Configure grafana for jwt authentication and restart the service.

Here is my configuration:
[security]
cookie_secure = true
cookie_samesite = lax
allow_embedding = true

[auth.jwt]
enabled = true
enable_login_token = true
header_name = X-JWT-Assertion
email_claim = email
username_claim = login
jwk_set_file = /etc/grafana/jwks.json
cache_ttl = 60m
expect_claims = {"iss": "https://jwt.io/"}
auto_sign_up = true
url_login = true

Here is my jwt payload:
{
  "login": "admin",
  "email": "admin@localhost",
  "isAdmin": true,
  "iat": 1672511400,
  "exp": 1704047400,
  "iss": "https://jwt.io/"
}

**Actual Result**:

After restarting the service, when I try to hit the iframe url having query parameter 'auth_token' with jwt as value. I get the below line in logs(debug level):

t=2023-02-10T12:58:26+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/my/iframe/path/ status=302 remote_addr=127.0.0.1 time_ms=2 size=37 referer=

**Expected Result**:

The panel should open in browser after hitting the iframe url.

While searching for the solution, I found few things in which I have doubts:
- Which config key should I use between 'expect_claims' or 'expected_claims'? (Ref: https://github.com/grafana/grafana/pull/58284)
- What config value should I use for 'cookie_samesite' between lax, strict, none or disabled? (Ref: https://github.com/grafana/grafana/issues/22731)
- Is there any browser related issue while logging in with jwt? However I tried with different browsers.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: v8.3.4
- Data source type & version: Elasticsearch 8.2.1
- User OS & Browser: Ubuntu 20.04.4 LTS & Google Chrome 104.0.5112.79 (64 bit)
- Others: I am running grafana in localhost

**Comment by gamab** [comment]
Hey, thanks for reporting.

> After restarting the service, when I try to hit the iframe url having query parameter 'auth_token' with jwt as value.

Handling of the `auth_token` query param has been introduced with https://github.com/grafana/grafana/pull/52662 in Grafana 9.1.0, you'll need to upgrade to use it :slightly_smiling_face: 

> "email": "admin@localhost",

I'm assuming this is for testing purpose only, but just in case, we'd recommend not using an admin user for iframe embedding.

One final comment, with 9.1.0, "sub" is mandatory. You'll need to specify it in your jwt.
```
{
"sub": "admin@localhost",
"login": "admin",
"email": "admin@localhost",
"isAdmin": true,
"iat": 1672511400,
"exp": 1704047400,
"iss": "https://jwt.io/"
}
```

I'm going to close this issue, but feel free to re-open if you think I didn't answer correctly :+1:

**Comment by rohit-innodeed** [comment]
Thanks @gamab. It worked!

**Comment by Aurora178** [comment]
Hello, I would like to ask a question: Can I use auth_token as Headers when using auth_token to access grafana dashboards?
