### ISSUE TITLE
[Bug report] Alerting: More than one recipient in email notification doesn't work

### ISSUE THREAD

**Issue by Dadard** [grafana/grafana#6326]
It looks like having more than one recipient in the email notification for alerting doesn't work.

I tried to specify them separated by newlines, commas, none of them seemed to work.

I guess you should double check, this is probably easy to fix.

Thanks for the good work done on alerting.

**Comment by bergquist** [comment]
@Dadard You should be able to use ; for seperation after this fix. It will be available on grafana.org/builds

I'll make sure to add a better description for this on the notification edit page

**Comment by Dadard** [comment]
Thanks guys for the fast feedback, but the issue is still there:

I tried specifying "foo@bar.com;bar@foo.com" this didn't work

i got the following message in the logs :
msg="Sending alert notification to" logger=alerting.notifier.email addresses="[foo@bar.com bar@foo.com]"

On the other hand "foo@bar.com,;bar@foo.com" did work, with following logs:
msg="Sending alert notification to" logger=alerting.notifier.email addresses="[foo@bar.com, bar@foo.com]"

Have a good day !
