### ISSUE TITLE
An unexpected error happened  TypeError: u is null

### ISSUE THREAD

**Issue by lgrandotto** [grafana/grafana#63269]
Hi,

CentOS Linux release 7.9.2009 (Core)
Grafana 9.2.3 OSS
Mysql rds 8.0.31

When use administrator Manage all users and orgs, the search user bug if the "name" is wrong and no exist in database.

it be required to refresh "F5" to regain the control.

This bug is know ?

Thanks for your help.

Best regards.

<img width="764" alt="grafana1" src="https://user-images.githubusercontent.com/113979255/218128874-42ac50cf-099e-445a-8bd9-4da8ee8604ce.PNG">
<img width="478" alt="grafana2" src="https://user-images.githubusercontent.com/113979255/218128885-b1bdf81b-2f69-44a9-958f-fcf4dda6dd78.PNG">

log in grafana GUI : (no log in /var/log/grafana.log)

An unexpected error happened
TypeError: u is null
37128/W<@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/UserListAdminPage.087cea19e9d0bce92422.js:30:155
g@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/4713.9debbfba7033186a58bf.js:2:999564
Suspense
c@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/3593.68f2b385d6dfe4902410.js:1194:301
fc@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/3593.68f2b385d6dfe4902410.js:8749:362
t@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/4713.9debbfba7033186a58bf.js:2:1014882
t@https://olg-grafana.ca-central-1.dtshared.prod.fdjaws.corp/public/build/4713.9debbfba7033186a58bf.js:2:1016903

**Comment by zuchka** [comment]
can you please provide more details on how to reproduce this error? Are you saying that if username `foo` does not exist in your db, and you type `foo` into the search bar, your grafana crashes? thx

**Comment by lgrandotto** [comment]
Hi,

Yes, that exactly it.

**Comment by lgrandotto** [comment]
Hi 

You can closed ticket.

Problem solved with version 9.3.6

Thanks.
