### ISSUE TITLE
CloudWatch Datasource produces InvalidClientTokenId Error

### ISSUE THREAD

**Issue by MatrixCrawler** [grafana/grafana#6327]
* **I'm submitting a ...**
- [ ] Bug report
(http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708)

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Debian 8

- What did you do?
I added the CloudWatch Datasource and the AWS Billing Metric Dashboard. I set up the AWS IAM User with CloudWatchReadOnlyAccess and opened the Dashboard.
The query in the AWS Billing Metric Dashboard is still the default data.

- What was the expected result?
To see my Cloudwatch results in Grafana

- What happened instead?
Sometimes i get the following error:
```
t=2016-10-19T15:23:24+0200 lvl=eror msg="Unable to call AWS API" logger=context userId=5 orgId=1 uname=MYUSER error="InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 36af8417-95ff-11e6-a3e9-e1904b671b86"
t=2016-10-19T15:23:24+0200 lvl=eror msg="Request Completed" logger=context userId=5 orgId=1 uname=MYUSER method=POST path=/api/datasources/proxy/3 status=500 remote_addr=172.17.17.163 time_ns=110ns size=36
```

Other times i get THIS error:
```
t=2016-10-19T15:30:25+0200 lvl=eror msg="Unable to call AWS API" logger=context userId=5 orgId=1 uname=MYUSER error="AccessDenied: User: arn:aws:iam::<AWS_ID>:user/grafana is not authorized to perform: cloudwatch:GetMetricStatistics\n\tstatus code: 403, request id: 3185d708-9600-11e6-802c-67fd60216560"
t=2016-10-19T15:30:25+0200 lvl=eror msg="Request Completed" logger=context userId=5 orgId=1 uname=MYUSER method=POST path=/api/datasources/proxy/3 status=500 remote_addr=172.17.17.163 time_ns=286ns size=36
```

In both cases i see no data (obviously)

However, this is not reproducable in a reliable way. Sometime when i refresh the Dashboard, it shows some graphs (without data)

![aws-working](https://cloud.githubusercontent.com/assets/5767285/19520663/4d877fc6-9611-11e6-8c66-602fa946f173.PNG)

**Comment by torkelo** [comment]
what is your data source options? @mtanda any ideas?

**Comment by MatrixCrawler** [comment]
This is my current config.

![image](https://cloud.githubusercontent.com/assets/5767285/19531525/4e87c44a-9638-11e6-822c-5c9305a28215.png)

The ~/.aws/credentials contains "eu-central-1" region as well

**Comment by torkelo** [comment]
And the credentials file is located in Grafana user home? What do you mean region? Looks like you specified default, so it will look for the default section with credentials file

**Comment by MatrixCrawler** [comment]
Yes. the configuration file is located in the grafana home dir.
The profile name is "default" as in the configuration.

With region i was referring to the Default-Region the CloudWatch should querying.

**Comment by torkelo** [comment]
and your sure the credentials in (clientId ) is correct?

**Comment by MatrixCrawler** [comment]
Yes.

However i noticed that i cannot reproduce the errors today. It seems like it was a caching issue on AWS side of some sort. Everything seems to work fine now.

**Comment by torkelo** [comment]
That's great!

**Comment by mtanda** [comment]
Just leave memo about the required permission to use CloudWatch datasource plugin.
The plugin use following API.

To get metrics values.
```
cloudwatch:GetMetricStatistics
cloudwatch:ListMetrics
```

To get alert history for annotation.
```
cloudwatch:DescribeAlarms
cloudwatch:DescribeAlarmsForMetric
cloudwatch:DescribeAlarmHistory
```

To get EBS volume id info for `ebs_volume_ids` templating.
```
ec2:DescribeInstances
```

And `CloudWatchReadOnlyAccess` allow following API.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "autoscaling:Describe*",
        "cloudwatch:Describe*",
        "cloudwatch:Get*",
        "cloudwatch:List*",
        "logs:Get*",
        "logs:Describe*",
        "logs:TestMetricFilter",
        "sns:Get*",
        "sns:List*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

`ec2:DescribeInstances` is not allowed by `CloudWatchReadOnlyAccess`, the `ebs_volume_ids` templating doesn't work. But other feature should work.

I'm not sure what happen when cloudwatch API doesn't work.

AWS limit the API call count, it could block API request.
http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
To get know how many API calls, CloudTrail can help you.
