### ISSUE TITLE
Loki: Chunking causes too many queries at the same time

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#63285]
**What happened**:
In some situations too many queries are run. Also subscriptions need to probably be canceled.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. Run a query, cancel it, run again, reload page.

**Environment**:
- Grafana version: main

https://user-images.githubusercontent.com/8092184/218190469-dff8fd27-91c7-41c6-a93a-912acbd9b574.mov

**Comment by matyax** [comment]
+1, I experienced this early today, but wasn't really sure what was going on.

**Comment by gabor-grafana** [comment]
seems to be fixed now.

**Comment by gabor** [comment]
seems to be fixed now.
