### ISSUE TITLE
[Bug Report] Query reset on "toggle edit mode"

### ISSUE THREAD

**Issue by ADeane6** [grafana/grafana#6328]
Grafana Version: v3.1.1 (commit: a4d2708)
Database: InfluxDB version 1.0.2
System: Ubuntu 14.04 server

This bug occurs when creating/editing a panel in a dashboard, I create a query in raw mode and then "Toggle Edit Mode"
![Raw mode Before](https://cloud.githubusercontent.com/assets/5058093/19520807/5ff24a36-9609-11e6-8d31-e5f813ec7ffb.PNG)

Press "toggle edit mode"

![Simple Mode](https://cloud.githubusercontent.com/assets/5058093/19520808/5fff0d5c-9609-11e6-953f-e22bf0df1117.PNG)

press "toggle edit mode"

![Raw mode After](https://cloud.githubusercontent.com/assets/5058093/19520806/5fee08f4-9609-11e6-8d6f-30cc4c8894f5.PNG)

I expected the query to be kept intact and allow for editing in simple mode, but the query was reset to the default placeholder query. This can be frustrating when in the middle of creating a panel.

**Comment by torkelo** [comment]
For InfluxDB you have 2 options to write queries (two edit modes), either using the UI query editor, or using a raw textbox. 

Switching between these two edit modes and having your changes persist between them is not supported

**Comment by teedilo** [comment]
I ran into this same issue today.  I wonder whether an enhancement might be considered for at least disabling Toggle Edit Mode once the user has made a choice and actually entered data either via the UI query editor or raw textbox.  It's really a bummer to lose what you've already entered.  I'll know to be very careful when using Toggle Edit Mode in the future, but others may also have to learn this the hard way without some sort of fail safe.

**Comment by torkelo** [comment]
Yes, a warning when going from textbox mode to UI query builder would be appropriate
