### ISSUE TITLE
Calculate percents between two singlestat scopes/measurements

### ISSUE THREAD

**Issue by lukashes** [grafana/grafana#6329]
* **I'm submitting a ...**
- [ ] Feature request

Please include this information:
- What Grafana version are you using?
3.0.1
- What datasource are you using?
InfluxDB 1.0.2
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Calculate percent between two singlestat scopes

I have two measurements in influx: `metric.request.count` and `metric.response.count`. I want to do one singlestat score with information about persents between measurements (it will be discrepancy of last 1 hour).

I saw this [issue](https://github.com/grafana/grafana/issues/2474) but it does not work for influx.

**Comment by torkelo** [comment]
InfluxDB does not support nested functions or operations on whole series, unlike Graphite.  

So until that happens maybe meta queries will solve your case (separate github issue, so will close this one)
