### ISSUE TITLE
Prometheus: query-based template var: label_values doesn't work when filtering values using i.e. `>0`

### ISSUE THREAD

**Issue by atsu85** [grafana/grafana#63296]
**What happened**:
When trying to filter results of Grafana variable populated using `label_values` and Prometheus query, for example:
`label_values(trivy_image_vulnerabilities, severity)`
by trying to keep only results where value is greater than 0, using following expression:
`label_values(trivy_image_vulnerabilities > 0, severity)`
or
`label_values((trivy_image_vulnerabilities > 0), severity)`
then following warning and error are shown:
```
Validation
invalid parameter "match[]": 1:1: parse error: unexpected "("
```
```
Templating [severity]
Error updating options: invalid parameter "match[]": 1:1: parse error: unexpected "("
```
![image](https://user-images.githubusercontent.com/1206512/218264116-984ff121-5281-4535-83f7-21751d80ea86.png)

Without ` > 0` it returns in my cases 5 values for the variable as expected.

**What you expected to happen**:
As the query
`trivy_image_vulnerabilities > 0`
provided to `label_values` function is valid prometheus query, that in my case keeps 2 distinct values for `severity` lable out of original 5 values:

![image](https://user-images.githubusercontent.com/1206512/218264291-273679f7-578b-4b40-a88d-8039dc608fe9.png)

I'd expect this to work in Grafana with `label_values` function as well

**How to reproduce it (as minimally and precisely as possible)**:

You can use any other series name and label instead of `trivy_image_vulnerabilities` and `severity` in my example
`label_values(trivy_image_vulnerabilities > 0, severity)`
when creating variable that is populated based on Prometheus query

**Environment**:
- Grafana version: 8.4.10
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux

**Comment by itsmylife** [comment]
Hi @atsu85 
This is expected behavior. `label_values` query type expects a metric and a label or a label. It does not support evaluating a metric with an operator like `(trivy_image_vulnerabilities > 0)`.

Please refer to the docs https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/#use-query-variables

**Comment by MarshmallowSoup** [comment]
Is it possible to make in new grafana versions?

**Comment by itsmylife** [comment]
@MarshmallowSoup Sorry for the late reply. I will discuss this with the team and come back to you.
