### ISSUE TITLE
Grafana "Bar Chart" charshes with tooltip=Single

### ISSUE THREAD

**Issue by AutomationArbaflame** [grafana/grafana#63307]
****What happened**:**
"Tooltip Mode =Single" chrashes Bar Chart
Reported error: Cannot read properties of undefined (reading '0')
Crashes when howering the chart

**What you expected to happen**:
Show the correct tooltip and not crash

**How to reproduce it (as minimally and precisely as possible)**:
Set up a chart of the type "Bar Chart"
Set the Tooltip = Single
Move the mouse to the generated bar in the chart

**Anything else we need to know?**:

**Environment**:
- Grafana version:c v9.3.6
- OS Grafana is installed on: Cloud
- User OS & Browser: Windows 10 Pro, Chrome

![chrome_305pXDXEVQ](https://user-images.githubusercontent.com/122878901/218404738-e64397b1-7cc8-4c93-8fbb-db5e5f81e3ee.gif)

**Comment by zuchka** [comment]
Thanks for creating this issue, @AutomationArbaflame 

could you please copy and paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by drew08t** [comment]
This PR appears to address this issue:
https://github.com/grafana/grafana/pull/67872

**Comment by drew08t** [comment]
@AutomationArbaflame The @grafana/dataviz-squad is not able to reproduce this issue on https://github.com/grafana/grafana/tree/v9.3.x or main branch. If you are still experiencing this issue, please provide more details so we can further investigate, thanks!
