### ISSUE TITLE
INDEX command denied to user grafana for table 'preferences' on upgrade Grafana 8.5.13 -> 9.3.6

### ISSUE THREAD

**Issue by romanvog** [grafana/grafana#63308]
**What happened**:

Trying to upgrade from Grafana 8.5.13  to 9.3.6 while pointing to the same database
New Grafana pods fail to start due to the following error:

> logger=migrator t=2023-02-13T09:27:18.421737646Z level=info msg="Starting DB migrations"
logger=migrator t=2023-02-13T09:27:18.428533792Z level=info msg="Executing migration" id="Add preferences index org_id"
logger=migrator t=2023-02-13T09:27:18.432795571Z level=error msg="Executing migration failed" id="Add preferences index org_id" error="Error 1142: INDEX command denied to user 'grafana'@'IP' for table 'preferences'"
logger=migrator t=2023-02-13T09:27:18.432817092Z level=error msg="Exec failed" error="Error 1142: INDEX command denied to user 'grafana'@'IP' for table 'preferences'" sql="CREATE INDEX `IDX_preferences_org_id` ON `preferences` (`org_id`);"
Error: ✗ migration failed (id = Add preferences index org_id): Error 1142: INDEX command denied to user 'grafana'@'IP' for table 'preferences'

Current grafana user has the following permissions which are missing INDEX:
```mysql> show grants;
+-------------------------------------------------------------------------------------------------------------------------+
| Grants for grafana@%                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, REFERENCES, ALTER ON *.* TO 'grafana'@'%' WITH GRANT OPTION |
+-------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

**What you expected to happen**:

Would expect it to be backwards compatible or to have relevant permissions added to the database when installing grafana 9 from helm, or to have relevant documentation on any manual changes required for the upgrade

**How to reproduce it (as minimally and precisely as possible)**:

Assuming same upgrade can be reproduced manually by lunching the relevant version and upgrading to 9.3.*

**Comment by zuchka** [comment]
Thanks for creating this issue, @romanvog 

were you using legacy alerting on grafana 8?

what helm chart? do you have detailed steps for reproducing this error?

can you try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to `debug` and note any errors. For printing to console, [set the console logs to `debug`](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) as well.
