### ISSUE TITLE
How to hide the alert heart icon before panel title?

### ISSUE THREAD

**Issue by carlwang87** [grafana/grafana#63303]
I want to hide the alert heart icon on the panel? See the below picture:

![image](https://user-images.githubusercontent.com/9320929/218361417-a5389058-887f-4684-be3a-59942bf242e6.png)

Are there some way to make it come true?

Thanks.

**Comment by UlrichThiess** [comment]
I use the "Boom Theme" Plugin to modify some things. With this you can add Custom CSS.

![grafik](https://user-images.githubusercontent.com/79257887/218423788-c960359e-8508-4348-ab68-88b5c5ce5c5b.png)

I use Firefox to look into the page to find the right class and/or id.

**Comment by carlwang87** [comment]
@UlrichThiess Thank you for helping me.

**Comment by UlrichThiess** [comment]
@carlwang87 Please close this issue. Thanks.
