### ISSUE TITLE
Azure Resource Graph Query - not able to use variable in Subscription field

### ISSUE THREAD

**Issue by websolut** [grafana/grafana#63316]
**What happened**:
We would like to parametrize a number of dashboards so we can apply them to different environments.

We have a Azure resource graph query and it behave strangely.
the UI allows us to select a variable (txt subscription guid) into the Subscriptions field but next time we try to edit the same panel - it defaults to another subscription.

**What you expected to happen**:
We are able to use variables without any limitations for the 'subscriptions' field.

**How to reproduce it (as minimally and precisely as possible)**:
Try to set up an Azure Resource Graph query with selecting a var as a value for subscriptions field.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Azure managed grafana latest
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: Azure monitor
- Others:

**Comment by aangelisc** [comment]
Hi @websolut, thanks for reporting this issue! I can confirm I've reproduced it and will move it to our backlog for prioritisation.
