### ISSUE TITLE
Timeshift in Singlestat with Elasticsearch

### ISSUE THREAD

**Issue by asednev** [grafana/grafana#6331]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
 Grafana v3.1.1 (commit: a4d2708) 

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
CentOS 7.2.151

- What did you do?
created 4 singlestat panels:
1) no timeshift. value: current
2) timeshift 1m value: current
3) timeshift 2m value: current
4) timeshift 3m value: current

compare numbers with same values displayed in table.

![image](https://cloud.githubusercontent.com/assets/3236025/19539005/cf5d411c-960b-11e6-9372-8fae3a063cde.png)

![image](https://cloud.githubusercontent.com/assets/3236025/19539107/77843d8c-960c-11e6-946f-a11bc31a9113.png)

- What was the expected result?
Number on singlestat match values in table

- What happened instead?
Numbers on 2 singlestats are 0, value on another singlestate doesn't match value in the table. these values don't change historically. values displayed in the table are correct.

**Comment by asednev** [comment]
Looks similar to [Issue 5250](https://github.com/grafana/grafana/issues/5250)

**Comment by torkelo** [comment]
Can you print the raw request body sent ES and the response? Check the date filter in ES query body. Anything wrong?

**Comment by asednev** [comment]
http://pastebin.com/vKREzsf7
http://pastebin.com/XKnJz0t9
http://pastebin.com/mM8qjD3R
http://pastebin.com/gz5Cbdez
http://pastebin.com/CVxbCgXB

For this test I created refresh interval of 1 minute. Waited until refresh occurred at which point all single stats displayed 0. Table contained correct values.

**Comment by torkelo** [comment]
could you give some context to all those pastebins? Like what do you think should be displayed given the ES response? I can see that all have a `doc_count: 0`  as the last entry point (this will be used by the current stat)

**Comment by asednev** [comment]
When Singlestat refreshes at the beginning of a minute, I expect to have value 0 since no values were reported for this minute yet. However, when the next Singlestat is configured with timeshift -1m, I expect it to display value for previous minute (which I believe is 81) but displayed value is 0. Next Singlestat is configured with timeshift -2m, I expect it to display value from 2 minute back (which I believe is 104) but displayed value is 0 again.

Unless my understanding of how timeshift works incorrect. 

Unfortunately when I captured the requests, I didn't capture expected values. I can capture some new requests along with screen shots and list of expected values if you my understanding of how timeshift works in correct.

**Comment by torkelo** [comment]
was the date range filter correct in the query? Elasticsearch is returning zero at least so something is causing ES to return zero even with the timeshift

**Comment by asednev** [comment]
@torkelo value 0 for current minute is by design because once time roll over a minute and refresh occurs, no events were yet logged for the current minute. That's why I'm looking at using timeshift to look at the previous minute instead of the current minute.

**Comment by torkelo** [comment]
yes, but it does not appear to work, your ES query is still returning zero as the last time bucket. The question is it's an issue with Elasticsearch, or the Query time range, or query histogram options

**Comment by asednev** [comment]
@torkelo, query time range is "last 6 hours". query histogram is a "date histogram" that's default type of historgram. Any suggestions on what else could it be?

**Comment by asednev** [comment]
@torkelo, I was able to reproduce same issue on "Live Demo" on Grafana's website. Here's export of dashboard that I modified http://pastebin.com/LnQYmzVY.

Please see the screenshot:

<img width="1170" alt="screen shot 2016-10-25 at 7 49 16 pm" src="https://cloud.githubusercontent.com/assets/3236025/19711670/36653416-9aec-11e6-8fe6-9821b406e6bf.png">

Numbers in both single stats with timeshift 1m don't reconcile with the table. I expect to see values 3, 18, 69.69, 69.47. Instead single stats display values 3, 3, 69.69, 69.31.

**Comment by torkelo** [comment]
but the singlestat panel has current, not max? or what is the stat your showing in the singlestat?

**Comment by asednev** [comment]
More than anything I am interested in singlestat with count. Both of them show 3. 

As for max, the query that singlestat displays has max value already. I tried also setting max on siglestat but that still didn't produce the value that matches the value in table.

**Comment by torkelo** [comment]
Strange maybe an elasticsearch bug? The query time range looks right
