### ISSUE TITLE
CloudWatch Logs: CloudWatch Template Error with Multi Template Variables

### ISSUE THREAD

**Issue by stigty** [grafana/grafana#63321]
**What happened**:
Using multi template variables inside CloudWatch Logs query shows popup error, even through the query is successful. The popup error message states

>Multi template variables are not supported for fields @timestamp, @message | filter accountId in ${accountId:json} | sort @timestamp desc

**What you expected to happen**:
The popup error is not shown.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a CloudWatch datasource.
2. Create a dashboard with a Custom multi-value variable
EX: 
![Screenshot 2023-02-13 at 3 28 46 PM](https://user-images.githubusercontent.com/69319181/218568037-d0832c28-606a-4a22-b23f-c322a9d97261.png)

3. Create a panel using the CloudWatch data source, change the query to CloudWatch Logs, and change the panels visualization to Logs. 
4. Insert a query that references the multi-value variable and run it. This will generate the error popup. 
EX: 

![Screenshot 2023-02-13 at 3 20 09 PM](https://user-images.githubusercontent.com/69319181/218568868-351d9005-3e82-493e-b62e-860a1c933b45.png)

**Anything else we need to know?**:

- This error popup only occurs when data is found. If I use two variables that don't match any data, the pop up isn't observed. 
- There was a similar issue reported here: https://github.com/grafana/grafana/issues/48806 that has been merged into 9.4.0-beta1 however, it doesn't seem to have fixed this problem. 
- There are no errors when observing networking calls while the panels query is run. 

**Environment**:
- Grafana version: v9.4.0-beta1
- Data source type & version: CloudWatch v5.0.0
- OS Grafana is installed on: Mac Ventura
- User OS & Browser:  MacOS Ventura 13.2 & Google Chrome Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by katebrenner** [comment]
@stigty this is being investigated
