### ISSUE TITLE
"Last known state" as choice for "If no data points or all values are null"

### ISSUE THREAD

**Issue by auduny** [grafana/grafana#6332]
* **I'm submitting a ...**
- [X] Feature request

- What Grafana version are you using?
Grafana v4.0.0-pre1 (commit: eda442d)

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
Played with alerts when we have freezing temperatures. Problem is that sensors not always send data for the timespan and you end up with nodata. You can then choose between the states

Ok/Alert/NoData.

[
![screenshot 2016-10-20 09 46 53](https://cloud.githubusercontent.com/assets/99946/19550670/df6b24f8-96aa-11e6-8da2-34cbb2c977d9.png)
](url)

But it would make a lot of sense (atleast in this case) that the should be another options which is "last known state" So if it was OK, still be OK, if it was "Alerting" it still Alerting.

**Comment by auduny** [comment]
Well. I was too quick. keepLastValue(100) from "special" in the main query will fix this for graphite i guess.

**Comment by bergquist** [comment]
@auduny That will work for graphite users :) Added support to have it for all datasources
