### ISSUE TITLE
Standardize border radius across product

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#63342]
- identify various border radiuses used in product
- make a decision on what pixel size we are moving forward with
- communicate the decision
- update Figma components to reflect design changes
- look into code restriction

**Comment by staton-hyse11** [comment]
In https://github.com/grafana/grafana/pull/63453, it's noted that a 2px radius is standard across the product. We need to verify this and then standardize the components.

**Comment by staton-hyse11** [comment]
I've added a callout in Figma for border-radius. This is something we cannot restrict within Figma, so this will have to work for now.

**Comment by staton-hyse11** [comment]
Need to set:
theme.shape.borderRadius(N), (N => N*2 px)

@JoaoSilvaGrafana are you aware of what all needs done to set these limitations?

**Comment by L-M-K-B** [comment]
- [ ] Identify where it’s used
> - Grafana
> - Plugins
> - Custom components?
- [ ] Document use case
- [ ] Team review process
- [ ] Create tasks for the following phases and assign
- [ ]  Approach affected teams and open tasks

**Comment by L-M-K-B** [comment]
See documented use cases [here](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=0)
- [ ] Remove deviations from Explore
- [ ]
