### ISSUE TITLE
Active Directory e-mail mapping not working and other issues

### ISSUE THREAD

**Issue by markkrj** [grafana/grafana#6334]
- [x] Bug report
- What Grafana version are you using?
3.1.1
- What OS are you running grafana on?
Debian 8.6

The ldap authentication does not work with the Active Directory e-mail attribute, which is "mail" instead of "email". If I use it, I get an error when trying to log in. If I use any attribute that does not exist in the Active Directory, I can log in, but no e-mail is mapped and it uses the username as the e-mail instead.
This is my configuration:

[[servers]]
host = "ad.example.com"
port = 389
bind_dn = "CN=ldapuser,OU=USR,DC=example,DC=com"
bind_password = 'P4$$WD'
search_filter = "(sAMAccountName=%s)"
search_base_dns = [ "OU=USR,DC=example,DC=com", "OU=ADM,DC=example,DC=com" ]
group_search_filter = "(member:1.2.840.113556.1.4.1941:=%s)"
group_search_filter_user_attribute = "distinguishedName"
group_search_base_dns = [ "OU=ADM,DC=example,DC=com" ]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "distinguishedName"
email = "mail"

[[servers.group_mappings]]
group_dn = "CN=admins,OU=ADM,DC=example,DC=com"
org_role = "Admin"
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

Another issue is with the group_search_base_dns array. It only search the first DN in the array. I did it like in search_base_dns which works.
group_search_base_dns =  [ "OU=USR,DC=example,DC=com", "OU=ADM,DC=example,DC=com" ]

The second is not a big of an issue, as we can put the Grafana groups all in one OU, what is bothering me is the first one.

**Comment by torkelo** [comment]
is distinguishedName your member ship property? 

I am sorry, I haven't tested with Active Directory so do not know what settings are correct. Many have gotten it to work. So maybe ask question in mailing list? 

you can also enable verbose logging in the toml config file, will print the data returned by ldap. What is the error you get (check grafana server log file)

**Comment by markkrj** [comment]
As I said, If I let it as it is ("email") it will work, but it will just use the username as the e-mail address. The "email" attribute does not exist in Active Directory, it is "mail". 
Any attribute that exist in AD **doesn't work** in the email field. E.g. "email = userPrincipalName".
But any attribute that DOES NOT exist in AD **works**. E.g. "email = whateverDoesNotExist"

Whoever programmed the LDAP integrator, must have done it in a way that if the attribute is nonexistent or if it is not declared in the config, it fallback to "username" because Grafana does not allow users without e-mail.

Here is the debug log:
[grafana.txt](https://github.com/grafana/grafana/files/548537/grafana.txt)

And about the member attribute, in AD it's memberOf, but in the ldap.toml file comments, it say that for recursive groups I should do it this way.

**Comment by Terr4** [comment]
I have the same issue with Grafana 12.
"email" maps to nothing.

I checked my LDAP/AD attribute names and the e-mail would be in the properties "EmailAddress", "mail" or "UserPrincipalName".

None of the mappings work

email = EmailAddress
email = mail
email = UserPrincipalName

In the Grafana UI you can test the LDAP search and it always shows no value for the mail field when doing the LDAP lookup
