### ISSUE TITLE
Chained variables over repeat panels not supported?

### ISSUE THREAD

**Issue by 80027** [grafana/grafana#63363]
**What happened**:

Chained variables are not being set under 'repeat panels'.

**What you expected to happen**:

Chained variables are set under 'repeat panels'.

**How to reproduce it (as minimally and precisely as possible)**:

Given a dashboard with two variables: X and Y, where the list of values of Y is based on the value of X.

When we create a repeat panel over X then foreach repeat panel, the value of X is set (what we are repeating over), but the value of Y (based on the value of X) is not.

---

Are chained variables over repeat panels simply not supported? Should this be a feature request?

**Comment by torkelo** [comment]
This is not supported, as variable  query execution only happens at the top level for the whole dashboard.
