### ISSUE TITLE
Fix and extract metrics emission for Alertmanager components

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#63370]
We should extract and fix the Alertmanager metrics within Grafana. This is a concrete plan on how to do so:

- [x] Use `UserRegistries` et al within Granfana https://github.com/grafana/mimir/issues/4082
- [x] https://github.com/grafana/alerting-squad/issues/409, continuation of https://github.com/grafana/grafana/issues/39152
- [x] Grafana Rules are now allowed to be paused - https://github.com/grafana/grafana/pull/63454

**Comment by yuri-tceretian** [comment]
>  Grafana Rules are now allowed to be paused - can we segregate the rules metrics to indicate which are paused?

Currently, metric `schedule_alert_rules` reports all alert rules including paused, which I think is a bug:
https://github.com/grafana/grafana/blob/4d1a2c3370de307ce6b7609d009125c2d0d1a458/pkg/services/ngalert/metrics/scheduler.go#L85-L92
it should report only active rules (that are actually evaluated). There is another metric `rule_group_rules` which basically reports similar number but groups by orgID. Once we fix that metric, we would be able to calculate the number of paused alerts. 

An alternative would be a separate metric for paused rules. Probably add label to the current one, which I do not think I like.

**Comment by alexmobo** [comment]
> > Grafana Rules are now allowed to be paused - can we segregate the rules metrics to indicate which are paused?
> 
> Currently, metric `schedule_alert_rules` reports all alert rules including paused, which I think is a bug:
> 
> https://github.com/grafana/grafana/blob/4d1a2c3370de307ce6b7609d009125c2d0d1a458/pkg/services/ngalert/metrics/scheduler.go#L85-L92
> 
> 
> it should report only active rules (that are actually evaluated). There is another metric `rule_group_rules` which basically reports similar number but groups by orgID. Once we fix that metric, we would be able to calculate the number of paused alerts.
> An alternative would be a separate metric for paused rules. Probably add label to the current one, which I do not think I like.

Yes, I was in the making of achieving this. We should discuss about the best approach.
- `schedule_alert_rules` only reporting active rules.
- We could create `paused_alert_rules` to report the number of paused alert rules.
- We could add a `paused` label in `rule_group_rules` to be able to group by org and paused or not.

WDYT?

**Comment by yuri-tceretian** [comment]
I agree with the approach
