### ISSUE TITLE
Line disappears from time series graph when adjusting min/max of axis and data has spike in value

### ISSUE THREAD

**Issue by martinvoigt** [grafana/grafana#63385]
**What happened**:
I'm trying to create a panel showing a value calculated using a math expression (a ratio).
This calculated value is usually below 100, but occasionally has very high values (1e29). I only want to the usual values up to 100, so I adjusted the max value of the axis to 100. When doing this, the line disappears from the graph, but one still sees the tooltip when moving the curser to the position where the line should be, see screenshots below.
![image](https://user-images.githubusercontent.com/36659258/219335964-898270c9-8af9-45eb-abaa-3240f64ce6cb.png)
![image](https://user-images.githubusercontent.com/36659258/219336012-d713dbfd-b987-4329-b03b-640a1f788dbb.png)

**What you expected to happen**:
The time series graph should still display the line.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query of a time series that contains small numbers as well as very big ones, and try to "zoom in" using the axis min/max settings as described above. It appears this is not limited to the use of expressions - I tried using a transformation but ended up with the same result.

**Anything else we need to know?**:
A quick&dirty workaround is to filter out the extreme values in the data source already. However, this adds complications if the data source returns long tables and not wide (as in my case), so that the calculations cannot be done easily at the data source level.

**Environment**:
- Grafana version: 9.3.2.2
- Data source type & version: MSSQL
- OS Grafana is installed on: Azure managed
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by adela-almasan** [comment]
Hi @martinvoigt, thank you for taking the time to create this issue! I was able to reproduce it locally and it seems to be related to a Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1337313) that was reported a while ago, but recently had some updates - so we're hoping for a fix on their side in the near future. The issue doesn't seem to happen in other browsers.

**Comment by clapis** [comment]
Just adding a bit more info, I've checked in Safari (16.5.1) and indeed at least it shows the lines - thank you for pointing it out 👍 But it seems part of the line is still missing despite the data points being there. Bellow I have a spike at 3:00 but already missing from 2:30 onwards:

<img width="1143" alt="image" src="https://github.com/grafana/grafana/assets/7800167/b23b5658-ea10-401d-9cbf-9e98370d80e1">
