### ISSUE TITLE
Graph no displayed when data is available

### ISSUE THREAD

**Issue by KengneMabou** [grafana/grafana#6338]
Hello, I'am using graphana 3.1.1 with influxdb 1.0.2 on ubuntu 14.04.
Influxdb is well populated with data but no graph is being display in graphana. Enabling or not the stack mode does anything. I have also noticed that grafana always show the last data point. I'm almost sure that the issue is with grafana. Here is the graphana query (from query editor)

**SELECT "value" FROM "two_days"."servers.classic_servers.ubuntu14_04.falcon.cpu.0.idle" WHERE $timeFilter**

This is the raw http request:

**http://@ip:3000/api/datasources/proxy/2/query?db=grumos&q=SELECT "value" FROM "two_days"."servers.classic_servers.ubuntu14_04.falcon.cpu.0.idle" WHERE time > now() - 4h&epoch=ms**
 
The http response to this query contains data as shown below
![capture du 2016-10-20 14 51 21](https://cloud.githubusercontent.com/assets/20929761/19562613/e11b2486-96d4-11e6-8102-7526efb1dba5.png)

the dashboard is as follow
![capture du 2016-10-20 14 54 07](https://cloud.githubusercontent.com/assets/20929761/19562680/2084c8f2-96d5-11e6-80f0-f728ce39f1b3.png)

Please any help regard to this issue. Thanks in advance

**Comment by torkelo** [comment]
any error in the chrome js console?

**Comment by KengneMabou** [comment]
Torkelo sorry to reply late i have been busy these days. No error is been display in chrome js console

**Comment by torkelo** [comment]
what is the graph display options? Try enabling points in display tab, what do you see?

**Comment by KengneMabou** [comment]
Hi torkelo,
 Grafana is doing weird things. Yesterday it started showing graph but this morning it was not showing anything again. Now it has restart to show some graph. So where should i look to correct this definitely

**Comment by torkelo** [comment]
as I said enable points in display tab, might be something funny with your data or your influxdb query

**Comment by aequasi** [comment]
I'm having a similar issue too:

https://i.imgur.com/iJM7pXZ.png
https://i.imgur.com/DDj4Dax.png

**Comment by torkelo** [comment]
https://community.grafana.com/t/why-is-my-graph-empty-when-i-zoom-in/24

**Comment by aequasi** [comment]
Was actually due to a bad system time in graphite, my bad.

**Comment by LamYunfu** [comment]
So do you guys solve this problem by reset the timezone of the Grafana?
