### ISSUE TITLE
Group by regex

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6339]
* **I'm submitting a ...**
- [x] Feature request

Rather than grouping by a tag query and tag value query, being able to group by a regex and a custom label would be useful.

Use case:

We have many hosts, all following a specific structure.

For example servers follow this structure:

`PAPP01LON1`

`P` meaning Production (or `S` for staging, `D` for development etc)
`APP` meaning application server. Eg, `STO` for storage, `CAC` for cache, etc.
`01` is the server number. Increments for each server
`LON1` is the region identifier.

SO, having the ability to map `PAPP*LON1` through to `Production Application London 1` to automatically tick:

`PAPP01LON1`, `PAPP02LON1` .. `PAPP30LON1` etc, would be useful.

And then add staging as `SAPP*LON1` for `Staging Application London 1` etc.

**Comment by torkelo** [comment]
Sounds like a feature request for your time series database, not for grafana

**Comment by malake** [comment]
I would also like to see something like this. We have groups of types of servers and it would be nice to visualize the typeA servers CPU together and typeB servers CPU as a second line. Then when the avg of typeA goes through the roof, create links to drill into which host of typeA is the rotten apple.

**Comment by pilak** [comment]
I also need this feature to group by url pattern on logging external call in okhttp3 interceptor

**Comment by malake** [comment]
I kinda hacked this out in telegraf by parsing the hostnames and capturing the parts that matter. This would be a bigger problem if we had a different naming convention.
