### ISSUE TITLE
Starred | tags overflows the "Find dashboards" box

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6340]
- **I'm submitting a ...**
- [x] Bug report
  Please include this information:
- What Grafana version are you using? 3.1.1

![image](https://cloud.githubusercontent.com/assets/842974/19563290/556a81d6-96d7-11e6-846d-d171d167e090.png)

Happens regardless of browser being 1270px wide, or 2560px wide.

Chrome 53 on Mac OS X

**Comment by torkelo** [comment]
strange, was unable to verify this on OSX chrome 54, wonder what it could be

**Comment by Nailya** [comment]
I confirmed the bug. Chrome 54 and OSX
![screen shot 2016-11-17 at 11 51 10](https://cloud.githubusercontent.com/assets/4751060/20385161/fd01b99e-acbe-11e6-9215-551cab6ed0a4.png)
