### ISSUE TITLE
`gt upstack submit -u` failed. Error: `ERROR: fetch failed`

### ISSUE THREAD

**Issue by LuyaoAsana** [grafana/grafana#63408]
**What happened**:
I have 2 branchs, when I try to update both of them by `gt upstack submit -u`. I see an error: `ERROR: fetch failed`.

```
🥞 Validating that this Graphite stack is ready to submit...

✏️  Preparing to submit PRs for the following branches...
▸ branch-1 (Update)
▸ branch-2 (Update)

📨 Pushing to remote and creating/updating PRs...
branch-1: https://app.graphite.dev/github/pr... (updated)
ERROR: fetch failed
```

**What you expected to happen**:
Both PR should be updated successfully. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by LuyaoAsana** [comment]
Not sure how to gather more useful error logs. let me know how I can help.

**Comment by zuchka** [comment]
@LuyaoAsana `gt` is the Graphite CLI. I'm not sure this belongs in the Grafana repo. Did you mean to submit this here?

https://github.com/withgraphite/graphite-cli
