### ISSUE TITLE
interval variable become a "multi-value" option

### ISSUE THREAD

**Issue by ranbochen** [grafana/grafana#6341]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- Grafana v3.1.1 (1 Aug 2016)
- influxdb
- windows
- add a template variable, type Interval
- interval must be a single select value
- it turns to a multi-value select

when add a interval template variable, 
if checked the "Multi-value" check box **before** choose type to Interval,
the variable become a multi-value option. 
Interval should be single select.

**Comment by ranbochen** [comment]
![1](https://cloud.githubusercontent.com/assets/5681057/19565740/874828a0-971a-11e6-9b26-db64246b4770.png)
![2](https://cloud.githubusercontent.com/assets/5681057/19565742/8789cc88-971a-11e6-9f62-141e31a92b13.png)
![3](https://cloud.githubusercontent.com/assets/5681057/19565744/87a2abd6-971a-11e6-8e4e-0061bb77c8dc.png)

**Comment by torkelo** [comment]
Why?  What's the use case?

**Comment by ranbochen** [comment]
It's not for any use case.
Just a small bug caused by an inappropriate order of operation, and it's hard to solve.
When I create the variable , I thought 'interval' has a lot of values, so I checked that option at first!
Then choose type to Interval, the 'Multi-value' option is gone. but the variable '$interval' is busted.
It took me a lot of time to find out why "$interval" not work.

**Comment by torkelo** [comment]
ah, I see, missunderstood your issue. Think this is fixed in maser in a recent refactoring of the variable system.
