### ISSUE TITLE
"Failed to lookup data key by id" - Datasources secureJson data is being encrypted with non-existing data keys

### ISSUE THREAD

**Issue by noamApps** [grafana/grafana#63419]
**What happened**:
We have a MultiOrg Grafana setup that automatically registers datasources, all add/delete datasources actions are being done through the Golang Grafana Rest API SDK.

We see that many times (could not identify a pattern yet)  datasources are being created in a corrupted way, with the following logs 
`level=error msg="Failed to lookup data key by id"`
`level=error msg="Failed to decrypt secret" error="data key not found"`
`level=error msg="error decrypting secret value"`

I looked into the db and the code a bit, it looks like the secureJsonData of the datasource is being encrypted with a data key not present in the db, In the code it seems there is some sort of cache , my guess is that the data keys cache is out of sync with the db, and the flow that fetches datasources for the dashboards, is trying to look up the data key in the db, but it only exists in the cache.

I was able to verify with several samples that for working datasources - the data key is registered in the data_keys table, however the datasources that return the error - the data key is not there.

Deleting the datasource through the UI and re-registering it seems to fix the issue ( using a data key that appears in the Grafana database right away actually)

**What you expected to happen**:
datasources should work once created, used data keys should appear in the db /fetched from the cache if needed

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, wasn't able to reproduce it consistently yet, but happens quiet a lot :/

**Anything else we need to know?**:

**Environment**: Grafana helm chart, using a Postgresql (Amazon RDS)
- Grafana version: 9.3.2
- Data source type & version: VictoriaMetrics registered as a prometheus db, with an http header registered as a SecureJsonData.
- OS Grafana is installed on: Linux (k8s eks)
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by noamApps** [comment]
@joanlopez  I think the your PR mention this edge case in https://github.com/grafana/grafana/pull/60664, however the mentioned cases are not public.
Is there any workaround for this edge case / how to avoid it ?

**Comment by noamApps** [comment]
hi @joanlopez we've migrated to grafana 10 in the meanwhile, issue is less apparent if at all, you can close this issue as far as Im concerned

**Comment by joanlopez** [comment]
Great, I'm glad to know it! Yeah, as there has been no news, I'd also suggest to close it. 
Feel free to open a new one pointing this as background, if needed.
