### ISSUE TITLE
mysql: TLS without certificates (no client-cert, no server-cert-verify) is not possible

### ISSUE THREAD

**Issue by keiki85** [grafana/grafana#63429]
**What happened**:
Since the database was switchted to TLS only mode "--require_secure_transport=ON" I can't connect to it anymore with Grafana.
MySQL clients like Workbench or IntelliJ are automatically using TLS and connecting without any issue.
Error message:
`“logger=tsdb.mysql t=2023-01-16T10:32:40.287979533+01:00 level=error msg=“Query error” error=“Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.””`

**What you expected to happen**:
I can connect to MySQL.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure yet. I guess you need to configure a MySQL instance with said flag.

**Anything else we need to know?**:
I tried to get an answer in the forum but it didn't help https://community.grafana.com/t/cant-connect-to-mysql-datasource-since-switch-to-require-secure-transport-on-mode/79748

**Environment**:
- Grafana version: 9.3.6 (taken from arch AUR)
- Data source type & version:  dunno where to get this information
- MySQL DBMS: Report from IntelliJ connection:
```
MySQL (ver. 8.0.28-19.1)
Case sensitivity: plain=exact, delimited=exact
Driver: MySQL Connector/J (ver. mysql-connector-java-8.0.25 (Revision: 08be9e9b4cba6aa115f9b27b215887af40b159e0), JDBC4.2)

```
- OS Grafana is installed on: Arch Linux
- User OS & Browser: Endeavor OS which is based on arch
- Grafana plugins: No extra

Thank you very much.

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @keiki85 

would it make any difference to try a different method? what if you [provisioned mysql](https://grafana.com/docs/grafana/latest/datasources/mysql/#provision-the-data-source) data source (with TLS) in a yaml file?

**Comment by keiki85** [comment]
@tonypowa Thanks for the reply and sorry for my late answer. 

I get the same issue with provisioning.  With my understanding Grafana is doing the same. 

Do you have more options with provisioning which I didn't see? On [provisioning ](https://grafana.com/docs/grafana/latest/administration/provisioning/) I didn't find more options regarding TLS.

In my MySQL clients I use (MySQL workbench and IntelliJ using  JDBC underneath) I don't need to specify the use of TLS as it automatically is used.

**Comment by tonypowa** [comment]
hi @keiki85 

thanks for the additional notes

however, I am unable the replicate the same environment from my side, so i will seek help from the BI squad, that supports questions related to mysql as a datasource.

they will get in touch with you

**Comment by keiki85** [comment]
Thank you for your reply.

I got grafana working locally by using following code change:

`Index: pkg/tsdb/mysql/mysql.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/tsdb/mysql/mysql.go b/pkg/tsdb/mysql/mysql.go
--- a/pkg/tsdb/mysql/mysql.go	(revision 211a999a2a6724185acb650f7fd7ec487d460208)
+++ b/pkg/tsdb/mysql/mysql.go	(date 1678092717941)
@@ -106,6 +106,8 @@
 				return nil, err
 			}
 			cnnstr += "&tls=" + tlsConfigString
+		} else {
+			cnnstr += "&tls=preferred"
 		}
 
 		if dsInfo.JsonData.Timezone != "" {
`

**Comment by codeincarnate** [comment]
Thanks @keiki85, we'll see if we can get this fix integrated into the MySql datasource

**Comment by Shionigami** [comment]
Hi @codeincarnate 
Just wanted to know if the update was already available in the newer release of Grafana. 
In fact, our Grafana configuration is stored in MySQL and since there was an update on MySQL side (I suppose it also has something to do with TLS), I had the same issue. But, in y case, I was not able to access Grafana at all :/

Thanks!

**Comment by ricohomewood** [comment]
Is there any update on this issue? This creates a problem for Grafana deployed in Azure that uses a Azure MySQL DB

**Comment by ricohomewood** [comment]
Is there any update on this issue? This creates a problem for Grafana deployed in Azure that uses a Azure MySQL DB

**Comment by rmacian** [comment]
Does this will be assigned ? I've ran onto the same problem when trying to configure a mysql datasource when secure tranport is enabled using 9.4.17
`[xorm] [info]  2024/02/26 13:29:32.122745 PING DATABASE mysql
logger=tsdb.mysql t=2024-02-26T13:29:32.152392869Z level=error msg="Query error" error="Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON."
logger=context userId=1 orgId=1 uname=admin t=2024-02-26T13:29:32.15256`

**Comment by sauvant** [comment]
Same issue here. Please implement this as it leads to implementing insecure applications as is.

**Comment by Jasmudhar90whitbread** [comment]
Hello was this ever resolved i am getting : Error 3159: Connections using insecure transport are prohibited
