### ISSUE TITLE
API to enable plugin app/datasource

### ISSUE THREAD

**Issue by doubtingben** [grafana/grafana#6342]
* **I'm submitting a ...**
- [    ] Bug report
- [ X ] Feature request
- [    ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1 (commit: a4d2708) 
- What datasource are you using? bosun-app
- What OS are you running grafana on? Linux
- What did you do? Automated grafana provisioning and configuration
- What was the expected result? Bosun-app plugin is enabled
- What happened instead? The only way to get it enabled is to log into the web ui, unless I'm missing something.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
There is a http api, you can check what api call the UI makes when clicking the enable button

**Comment by zimmertr** [comment]
Has anyone figured out how to do this? I would like to enable & configure the `worldPing` app automatically on provisioning through API calls via Ansible.
