### ISSUE TITLE
row/cell/value coloring enhancements

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#6343]
- [x ] Feature request

We are using the table panel to create an alert console. Some enhancements to the coloring of results would be very helpful for people trying to use the table in this manner.

currently the coloring is only based on a threshold value of a number. Would it be possible to allow coloring based on a text value? I could see being able to provide a list of values along with a hex value for the color. A static list would work fine, but having the ability to generate a list via a query (similar to template vars) would be ideal.

speaking of hex values, it would be great to be able to specify them directly in the interface instead of using the color picker, which makes it difficult to keep the colors in sync between multiple dashboards if you stray from the defaults.

I am currently hacking something together by creating additional fields in influxDB that contain simple HTML to get the results we are looking for but it sure would be nice to have this in Grafana itself. 

thanks!

**Comment by torkelo** [comment]
it's a good idea, already proposed in this issue, https://github.com/grafana/grafana/issues/3601
so will close this one
