### ISSUE TITLE
Make build-docker-full failed on v9.3.1

### ISSUE THREAD

**Issue by omarmakni** [grafana/grafana#63434]
**What happened**:
I'm working on Grafana V9.3.1, I Download the repo locally then I launched "make run" and started successfully, but if I launched "make build-docker-full" it failed in the stage generation cue file :
#26 412.6 generate code from .cue files
#26 412.6 go generate ./pkg/plugins/plugindef
#26 412.8 go: downloading [github.com/grafana/codejen](http://github.com/grafana/codejen) v0.0.2
#26 412.9 go: downloading [github.com/labstack/echo/v4](http://github.com/labstack/echo/v4) v4.9.0
#26 412.9 go: downloading [github.com/grafana/cuetsy](http://github.com/grafana/cuetsy) v0.1.1
#26 413.3 go: downloading [golang.org/x/mod](http://golang.org/x/mod) v0.7.0
#26 413.3 go: downloading [github.com/xlab/treeprint](http://github.com/xlab/treeprint) v1.1.0
#26 413.3 go: downloading [github.com/labstack/gommon](http://github.com/labstack/gommon) v0.3.1
#26 413.4 go: downloading [github.com/valyala/fasttemplate](http://github.com/valyala/fasttemplate) v1.2.1
#26 413.9 /grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
#26 413.9 pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
#26 413.9 make: *** [Makefile:69: gen-cue] Error 1

**What you expected to happen**:
Build image docker successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Just download the code source of version 9.3.1 then run make build-docker-full

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: 
- Grafana plugins:
- Others:
- Go: 1.19.5
- Node: 16.19.0

**Comment by tonypowa** [comment]
closing since there is already an existing issue for this

Please see https://github.com/grafana/grafana/issues/58921 and additionally https://github.com/grafana/grafana/issues/58921#issuecomment-1332581945
