### ISSUE TITLE
Glue: When using mixed data source with multiple queries, links are getting duplicated

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#63447]
**Steps to reproduce**:

* WHEN correlations and mixed data sources are enabled:

```yaml
[feature_toggles]
correlations = true
exploreMixedDatasource = true
```

* AND a correlation is added to any data source
* AND mixed data source is used in Explore with two different data sources (one with the correlation)
* THEN a data link is created multiple times

<details><summary>Example</summary>

Correlation setup:

![Image](https://user-images.githubusercontent.com/745532/220095196-1ea6bf11-00d0-4ab4-be1e-0f74ff18d214.png)

Explore query:

![Image](https://user-images.githubusercontent.com/745532/220095225-4c26a00b-0275-44d0-bf76-728bfca3a2da.png)

</details>

**Expected result**: Data links are not duplicated

**Technical info**:

Seems like the decorator is called multiple times --> https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/decorators.ts#L88

Possibly we should attach data links only when the state is `LoadingState.Done` in decorateWithCorrelations but I've seen some cases when `LoadingState.Done` is dispatched twice.

**Comment by gelicia** [comment]
For this bug, test the following scenarios

1. Mixed datasources
2. Loki, with an absolute time range, after re-running the query
3. Test datasources
