### ISSUE TITLE
Ability to rename/alias "time" column in tables

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#6345]
- [x] Feature request

I use influxDB to store downtime incidents that I display via grafana tables. The start time for the incident is the insert timestamp. I am getting requests to rename the time column to "Start Time", or something similar but it appears I can't use aliasing to rename the time column.  It would be great to be able to rename this column similar to other columns of data.

**Comment by daniellee** [comment]
Closed by #8239
