### ISSUE TITLE
Select templates from a drop-down menu

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#63468]
Right now it is very hard to know how to use templates when creating a contact point integration:

<img width="677" alt="SS 2023-01-19 at 13 12 17" src="https://user-images.githubusercontent.com/2117580/213440125-eb08b0f4-e217-4b5e-8bb6-073d7f00d275.png">

When templating a contact point it should be possible to select templates from a drop-down menu but allow custom input too.

**Comment by soniaAguilarPeiron** [comment]
Fixed in this [PR](https://github.com/grafana/grafana/pull/87689)
