### ISSUE TITLE
Issue building from master: missing `context`

### ISSUE THREAD

**Issue by ericuldall** [grafana/grafana#6347]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? latest
- What datasource are you using? N/A
- What OS are you running grafana on? Linux version 3.16.0-30-generic (buildd@kissel) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
- What did you do? Tried to build from src: setup
- What was the expected result? That it would work
- What happened instead? Got an error about missing context

```
go run build.go build
Version: 4.0.0-pre1, Linux Version: 4.0.0, Package Iteration: 1477000119pre1
rm -r dist
rm -r tmp
rm -r /root/go/pkg/linux_amd64/github.com/grafana
rm -r ./bin/grafana-server
rm -r ./bin/grafana-server.md5
go version
go version go1.6 linux/amd64
go build -ldflags -w -X main.version=4.0.0-pre1 -X main.commit=v3.1.0-1161-geda442d -X main.buildstamp=1476938710 -o ./bin/grafana-server ./pkg/cmd/grafana-server
pkg/cmd/grafana-server/server.go:4:2: cannot find package "context" in any of:
	/root/go/src/github.com/grafana/grafana/vendor/context (vendor tree)
	/usr/local/go/src/context (from $GOROOT)
	/root/go/src/context (from $GOPATH)
exit status 1
exit status 1
```

I've followed the steps to build from my fork in the readme and symlinked my code into src/github.com/grafana/grafana

Is there something  i'm missing?

**Comment by ericuldall** [comment]
go version go1.6 linux/amd64

**Comment by utkarshcmu** [comment]
You need to upgrade go to 1.7 I think.

**Comment by ericuldall** [comment]
I'll try that.

**Comment by ericuldall** [comment]
That did the trick. I overlooked the Go version dependency in the README. My Fault. TY!
