### ISSUE TITLE
 Alert tab only shown for the Timeseries panel type

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#63481]
**What happened**:

Alert tab is shown only for `Time Series `panel type.
The Bar chart, Gauge, and others hide this tab instead.

**What you expected to happen**:
Alert tab should be shown independently of the visualisation type.

**How to reproduce it (as minimally and precisely as possible)**:

Create a panel, and select `Time series` visualisation type. Alert tab is shown.
<img width="428" alt="SS 2023-02-21 at 10 13 23" src="https://user-images.githubusercontent.com/2117580/220300809-8fcdbd03-8cea-424d-90e2-9014f1009ed1.png">

Change the visualisation type to `Bar chart` and the alert tab is gone.
<img width="381" alt="SS 2023-02-21 at 10 13 28" src="https://user-images.githubusercontent.com/2117580/220300860-e94620b1-0fa8-46d3-b802-05698432535e.png">

**Comment by konrad147** [comment]
This is by design. Displaying threshold on other types of panels would be confusing.
