### ISSUE TITLE
Add Edit mode for OpenTSDB queries

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6348]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

We should have edit mode for OpenTSDB queries as well similar to graphite. Once done, it will be a good base for supporting expressions. #3805

**Comment by digrich** [comment]
+1

**Comment by bergquist** [comment]
Since support for alerting is merged to master this would have to be fixed on both frontend and backend.

**Comment by utkarshcmu** [comment]
Yes, this is not trivial but it would help us later on to support expressions in Grafana for OpenTSDB.

**Comment by jregovic** [comment]
+1

**Comment by widewing** [comment]
+1

**Comment by ocarino** [comment]
+1

Any progress on this? I just updated our opentsdb to 2.3.0-RC2, so expressions exist in opentsdb, only grafana is missing...

**Comment by utkarshcmu** [comment]
@ocarino No progress yet!

**Comment by utkarshcmu** [comment]
This is not trivial, have to change how OpenTSDB is queried without breaking the current dashboards. Have started some work, hopefully its done by next week.

**Comment by johann8384** [comment]
Supporting gexp this way would actually be a lot more straightforward than the exp support. The query parameter just becomes sum (metric1, metric2), etc. Much like a Graphite query.

**Comment by johann8384** [comment]
http://opentsdb.net/docs/build/html/api_http/query/gexp.html

**Comment by utkarshcmu** [comment]
I am going to hold off on this one until OpenTSDB support is much better, but support for gexp is provided in #7118 !

**Comment by gnydick** [comment]
I've incorporated your patches into v5.3.1 and am cutting a PR. I also fixed an issue. Variables weren't being interpolated in gexp queries, but I took care of that.

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
