### ISSUE TITLE
Stat Panel: Graph does not display if hidden due to panel size at dashboard load

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#63485]
**What happened**:

By design, the Stat panel will not render its graph if the panel is too small. [See docs](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/stat/#automatic-layout-adjustment):

> The panel automatically adjusts the layout depending on available width and height in the dashboard. It automatically hides the graph (sparkline) if the panel becomes too small.

However, if a panel is 'too small' to show the graph on dashboard load, and it's later resized (by resizing either the browser or panel), the graph is not displayed.

**What you expected to happen**:

The graph shows once there's room for it

**How to reproduce it (as minimally and precisely as possible)**:

1. Load [this dashboard](https://play.grafana.org/d/nGUHAr1Vz/stat-panel-graph-does-not-display-if-hidden-due-to-panel-size-at-dashboard-load?orgId=1)
   1. Alternatively, create a Stat Panel using time series data (for a graph), and size the panel small enough so the graph does not show)
2. Resize the panel to make it significantly larger.
3. _Observe the graph is not shown._
5. Save the dashboard and refresh the page
3. _Observe the graph is shown shown._ If you resize the panel down to hide the graph, and then make it big again, the graph will show.

If you save the play dashboard, please remember to revert your changes :)

**Comment by danielbprice** [comment]
I filed this issue via Grafana service; this has affected a number of our dashboards-- the part which is especially painful is that the look & feel of the dashboard for my end users is different depending on the size of their browser window when they load the dashboard.  Users (like me) who tend to have tall narrow browser windows will never see the stat panel sparkline display, even after resizing to make the browser wider.  Thanks for looking into it.
