### ISSUE TITLE
grafana text edit panel toggle not visible

### ISSUE THREAD

**Issue by jjanderson** [grafana/grafana#63490]
I am not sure if this is related, but I am not able to view the text edit toggle button when editing panels.

This is a new Grafana install running in the following environment:

Ubuntu
Docker
Grafana v9.3.6

Grafana is sat behind NGINX reverse proxy

I have looked everywhere and came across this which I am not sure is related https://github.com/grafana/grafana/issues/18037

I am using influxdb2 as the datasource and queries running in flux against this datasource.

I have tried in different browsers and pretty much exhausted by debugging and hence raising on here with a hope to get this resolved.

**Comment by tonypowa** [comment]
Thanks for creating this issue, @jjanderson 

>not able to view the text edit toggle button when editing panels.

this is at dashboard level, before you view/edit a panel, right?

> I have looked everywhere and came across this which I am not sure is related https://github.com/grafana/grafana/issues/18037

i haven't found any recent issues regarding this.

i understand that it is a fresh Grafana install but, could this be a permission-related issue? can you share the dashboard permissions? Let's start with that 🔍   👍
