### ISSUE TITLE
Graph hover info sort order breaks metric highlighting.

### ISSUE THREAD

**Issue by andrewmcgilvray** [grafana/grafana#6350]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 

3.1.1

- What datasource are you using? 

Graphite

- What OS are you running grafana on? 

Linux

- What did you do? 

On a graph with mutltiple metrics :
1. Set Graph->Display->Hover Info->Sort Order = Decreasing
2. Hover mouse over the top most datapoint on the graph.

- What was the expected result?

The metric of hovered datapoint should be highlighted on the hover list. Here is how it looks with Sort Order = None :
<img width="650" alt="sort_none" src="https://cloud.githubusercontent.com/assets/1414394/19583375/87170dd2-977f-11e6-9503-c4880c710ec3.png">

- What happened instead?

The metric at the position the desired metric would have been if the Sort Order = None was highlighted.
<img width="655" alt="sort_decreasing" src="https://cloud.githubusercontent.com/assets/1414394/19583380/8dbef8de-977f-11e6-98ef-2c708ed83a25.png">

**Comment by andrewmcgilvray** [comment]
I think this may have been fixed in master : 
https://github.com/grafana/grafana/commit/f7124f1638913feba6fddf552ec10d31f90d59e9#diff-fc43a7f9f8423d7c750133dbe29291d4

**Comment by torkelo** [comment]
fixed in master
