### ISSUE TITLE
Saga; Alert examples are difficult to read

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#63500]
In Saga, the alert examples are difficult to read because of the how small they must scale to fit the space provide.

![Image](https://user-images.githubusercontent.com/101748563/220361056-2b059975-af9b-4bd9-acd9-d56b5248c07e.png)

We can address this in a few ways:

1. Make the images more narrow to allow for the content to be easier understood
2. Pivot how we do do/don't examples to not include actual content but to provide a generalized image that depicts the layout better so users don't get hung up on the content

![Image](https://user-images.githubusercontent.com/101748563/220361751-0f61a0ce-7628-4f08-9e34-4ce12327f8a6.png)

**Comment by natydej** [comment]
Changes in the [branch](https://github.com/grafana/design-system/compare/main...ndj-alert-pages), waiting for review/merge

Also, here is the [figma](https://www.figma.com/file/Ft7z7ysVzVhtCf7SFlvzyN/Site-Assets?node-id=104%3A977) file with the Assets sizes updated, for all the content that we have in Saga for now.

**Next steps:**

Update visual assets for the next pages:

- [ ] Button
- [ ] Tooltip
- [ ] Border Radius

**Comment by natydej** [comment]
**Notes for Border radius:**

- The token `shape.radius.default` is **2px**

- We can expand our 3 tokens (`.default`,` .circle`, `.pill`) to include a fourth; maybe `.large` for defined areas of use
Besides this screen, where else would/could this be used?

- Using **8px** is good at a glance to keep the 8pt grid methodology at the core of the UI
