### ISSUE TITLE
Duplicating a notification template shows "Edit notification template" instead of "Create notification template"

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#63503]
**What happened**:

Clicking Copy template on a notification template shows "Edit notification template" instead of "Create notification template".

**What you expected to happen**:

The UI should show "Create notification template". This would be consistent with copying an alert rule which says "Add rule" instead of "Edit rule".

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by chethan27** [comment]
hi @grobinson-grafana , can you assign this to me . i want to work on this

**Comment by armandgrillet** [comment]
@chethan27 We would like to resolve this issue fast as it is an easy fix to land, if you are unable to have a PR by the end of the week we will reassign this to someone else on Monday. Sorry for the time constraint!

**Comment by chethan27** [comment]
https://github.com/grafana/grafana/pull/63771 Hi, @armandgrillet . Raised the pr. Please review and merge it

**Comment by soniaAguilarPeiron** [comment]
could you please add the link to your PR? @chethan27 
Thank you!
