### ISSUE TITLE
Tooltip doesn't work with autolayout

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#63516]
When resizing the tooltip, the text does not resize accordingly. The autolayout properties need to be adjusted

https://user-images.githubusercontent.com/5264102/220410898-c6c1f732-94b1-457b-906d-3cb7a1326ea6.mov

**Comment by natydej** [comment]
Merged and publish the Figma library with these changes:

- Added a fixed-width (400px) variant that aligns with Storybook
- Added the documentation link and description for the Component Configuration
