### ISSUE TITLE
auth.generic_oauth fails to get info; unsupported protocol scheme

### ISSUE THREAD

**Issue by garthk** [grafana/grafana#6351]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? `grafana/grafana:master`(`062b81fb4a2b`) from Docker Hub
- What datasource are you using? N/A
- What OS are you running grafana on? Ubuntu
- What did you do? Try to log on
- What was the expected result? Success
- What happened instead? `Server side error :(`; `login.OAuthLogin(get info from generic_oauth)`

Config:

```
[auth.generic_oauth]
enabled = true
client_id = …
client_secret = …
scopes = openid email nickname
auth_url = https://…/authorize
token_url = https://…/oauth/token
allowed_domains = …
allow_sign_up = true
```

Log message:

```
grafana_1  | t=2016-10-21T02:26:24+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=192.168.0.179 time_ms=0s size=330
grafana_1  | t=2016-10-21T02:26:26+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="Get : unsupported protocol scheme \"\""
grafana_1  | t=2016-10-21T02:26:26+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=192.168.0.179 time_ms=19ns size=716
```

Nearby code: [`pkg/api/login_oauth.go#L111`](https://github.com/grafana/grafana/blob/eda442dbf938ab53175c8d965875d06d7edbcf20/pkg/api/login_oauth.go#L111)

```go
	// get user info
	userInfo, err := connect.UserInfo(client)
	if err != nil {
		if err == social.ErrMissingTeamMembership {
			ctx.Redirect(setting.AppSubUrl + "/login?failCode=1000")
		} else if err == social.ErrMissingOrganizationMembership {
			ctx.Redirect(setting.AppSubUrl + "/login?failCode=1001")
		} else {
			ctx.Handle(500, fmt.Sprintf("login.OAuthLogin(get info from %s)", name), err)
		}
		return
	}

	ctx.Logger.Debug("OAuthLogin got user info", "userInfo", userInfo)
```

Also: [`pkg/social/generic_oauth.go#L162)`](https://github.com/grafana/grafana/blob/master/pkg/social/generic_oauth.go#L162)

```go
func (s *GenericOAuth) UserInfo(client *http.Client) (*BasicUserInfo, error) {
	var data struct {
		Name       string              `json:"name"`
		Login      string              `json:"login"`
		Username   string              `json:"username"`
		Email      string              `json:"email"`
		Attributes map[string][]string `json:"attributes"`
	}

	var err error
	r, err := client.Get(s.apiUrl)
	if err != nil {
		return nil, err
	}
```

The code suggests `api_url` is not optional, yet the [documentation](https://github.com/grafana/grafana/blob/master/docs/sources/installation/configuration.md#authgeneric_oauth) doesn't mention it:

> ```
[auth.generic_oauth]
enabled = true
client_id = YOUR_APP_CLIENT_ID
client_secret = YOUR_APP_CLIENT_SECRET
scopes =
auth_url =
token_url =
allowed_domains = mycompany.com mycompany.org
allow_sign_up = false
```

Workaround:

Set `api_url = https://…/userinfo` if your OAUTH2 provider has an OpenID Connect compatible `userinfo_endpoint`.

Definition of "fixed":

* Need for `api_url` documented
* Error emitted if `api_url` is absent

**Comment by torkelo** [comment]
thanks for heads up! fixed the docs!

**Comment by Louis-7** [comment]
Hi,  

What if I don't have a user info endpoint?

**Comment by visualhu** [comment]
How to config request  `api_url = https://…/userinfo` via POST?

**Comment by marefr** [comment]
@visualhu maybe [this](https://grafana.com/docs/auth/generic-oauth/#set-up-oauth2-with-non-compliant-providers) is related for your use case?
