### ISSUE TITLE
E-Mail Error

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#6353]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
 Grafana v4.0.0-pre1 (commit: 96008c9) via Docker
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
Alert is triggered
- What was the expected result?
E-Mail is send
- What happened instead?
No E-Mail was send. The log contains some strange output. Note that I have to E-Mails addresses in a single handler:

```
grafana_1                 | t=2016-10-21T11:28:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=17 newState=alerting oldState=no_data
grafana_1                 | t=2016-10-21T11:28:30+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=17 Amount to send=1
grafana_1                 | t=2016-10-21T11:28:30+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/alerts?&panelId=13"
grafana_1                 | t=2016-10-21T11:28:33+0000 lvl=info msg=uploaded logger=alerting.notifier url=
grafana_1                 | t=2016-10-21T11:28:33+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=4 isDefault=false
grafana_1                 | t=2016-10-21T11:28:33+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[o@example.de\nm@example.de]"
grafana_1                 | t=2016-10-21T11:28:33+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="gomail: could not send email 1: gomail: invalid address \"=?UTF-8?q?o@example.de=0Am@example.d?= =?UTF-8?q?e?=\": mail: expected single address, got \"@example.d?= =?UTF-8?q?e?=\""
```

**Comment by torkelo** [comment]
what does your notification settings look like (please blur out email adddress)

**Comment by torkelo** [comment]
did you specify multiple email addresses?

**Comment by torkelo** [comment]
think your problem was how you specified mulitple addresses, I added support to split the address list by `,` newline and `;`  so I think your issue is fixed in latest master / nightly

**Comment by Fox32** [comment]
I'm using new line, I will check if it works on monday.
