### ISSUE TITLE
timeshift on graphs

### ISSUE THREAD

**Issue by inoculator** [grafana/grafana#63544]
**What happened**:
Grafana dashboard miss 1 hour of data in time series

**What you expected to happen**:
Dashboard displays all data in the given time range.

**How to reproduce it (as minimally and precisely as possible)**:
install Grafana RPI 9.3.6 on a Raspberry Pi with Raspbian 11 bullseye and MariaDB server 10.5.15.
set timezone on raspbian to CET (UTC+1)
Set timezone in MariaDB to "System"
Push data into a appropriate table using UTC Timestamps
Create a Dashboard reading that data and select any time range to display.
If you select less or equal an hour, no data gets displayed at all.
If you select more than an hour, always the first hour on the time series will not be displayed:
![image](https://user-images.githubusercontent.com/14196051/220562314-0eb5986a-616d-49d1-9418-f3e2f71f6e52.png)
Example from a temperature sensor.

**Anything else we need to know?**:
Regardless of the time settings in the browser (CET/UTC), the gap stays.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: MYSQL (MariaDB 10.5.15)
- OS Grafana is installed on: Raspbian 11 bullseye
- User OS & Browser: Windows 10; Chrome
- Grafana plugins: None
- Others: 
Uploading query (data is provided by a SDR reader -utctimestamp is the essential column.
```
ThisQuery="insert into "$dbtable" (utctimestamp,devicename,devicevalue,deviceunit,zone,battery,devicechannel,deviceid) values ("
ThisQuery+="'$(date --utc '+%Y-%m-%d %H:%M:%S')'"
ThisQuery+=",'$SNAME'"
ThisQuery+=",'$SVALUE'"
ThisQuery+=",'$SUNIT'"
ThisQuery+=",'$SZONE'"
ThisQuery+=",'$SBATT'"
ThisQuery+=",'$SCHAN'"
ThisQuery+=",'$SID'"
ThisQuery+=");"
```
Grafana Query (assume $Sensor as 'Außen'):
```
SELECT
  utctimestamp AS "time",
  devicevalue AS "Temperatur"
FROM sensordata
WHERE
  $__timeFilter(utctimestamp) AND
  zone = '$Sensor' AND
  deviceunit = "°C"
ORDER BY utctimestamp;
```
Testing results by manual query:
```
SELECT   utctimestamp AS "time",   devicevalue AS "Temperatur" FROM sensordata WHERE   utctimestamp >= convert_tz(date_sub(now(), interval 3 hour),'+01:00','+00:00') AND   zone = 'Außen' AND   deviceunit = "°C" ORDER BY utctimestamp desc;
+---------------------+------------+
| time                | Temperatur |
+---------------------+------------+
| 2023-02-22 08:11:15 |        6.2 |
| 2023-02-22 08:10:36 |        6.1 |
| 2023-02-22 08:10:01 |        6.1 |
| 2023-02-22 08:09:21 |        6.1 |
| 2023-02-22 08:08:44 |        6.1 |
| 2023-02-22 08:08:22 |        6.1 |
| 2023-02-22 08:07:35 |          6 |
| 2023-02-22 08:07:00 |          6 |
| 2023-02-22 08:06:30 |          6 |
| 2023-02-22 08:05:50 |          6 |
[snip]
| 2023-02-22 05:17:39 |        4.3 |
| 2023-02-22 05:17:06 |        4.3 |
| 2023-02-22 05:16:31 |        4.3 |
| 2023-02-22 05:15:59 |        4.3 |
| 2023-02-22 05:15:19 |        4.3 |
| 2023-02-22 05:14:45 |        4.3 |
| 2023-02-22 05:14:10 |        4.3 |
| 2023-02-22 05:13:35 |        4.3 |
| 2023-02-22 05:12:59 |        4.3 |
| 2023-02-22 05:12:26 |        4.3 |
| 2023-02-22 05:11:51 |        4.2 |
+---------------------+------------+
```
Result returns 3 hours of data, starting 05:11am to 08:11am, but Grafana Dashboard displays only 07:11am to 09:11am (translated in CET).

**Comment by gabor** [comment]
hi @inoculator , thank you for reporting the issue. i suspect there may be some timezone-related configuration problem here.
questions:

1.  the timezone setting in the time-picker, what value is it set to? does it help if you adjust it?
<img width="596" alt="timezone" src="https://github.com/grafana/grafana/assets/51989/9335cd00-af49-492c-b82d-8c83261c80ca">

2. the timezone setting in the datasource config page, what value is it set to? does it help if you adjust it?
<img width="354" alt="tz2" src="https://github.com/grafana/grafana/assets/51989/f7a99c37-8067-42db-8385-71b44e10c5a0">

3. could you try with a newer grafana version?
4. in your database schema, what type exactly is the `utctimestamp` field?
5. in your dashboard panel, open the query inspector (click on the triple-dot in the corner, and select `inspect` then `data`). what kind of timestamps do you see there?

**Comment by gabor** [comment]
hi, as we got no response for a long time, we're closing the issue. if we get new info, of course we'll reopen the issue. thanks!
