### ISSUE TITLE
Inappropriate HTTP response code for some requests

### ISSUE THREAD

**Issue by peqi-ms** [grafana/grafana#63543]
**What happened**:
We have seen many cases that grafana returned inappropriate status code to our clients.
Cases listed below:
| url  | error msg | current status code |
|:-----|:----------| :-----------------|
| **/api/v1/eval**| Failed to evaluate queries and expressions: failed to execute query D: no handler found for query type '' | 500 |
| **/api/v1/eval**| Failed to evaluate queries and expressions: input data must be a wide series but got type not (input refid) '' | 500 |
| **/api/folders**| invalid API key | 500 |
| api/prometheus/.../api/v1/rules| unexpected content type from upstream. expected JSON, got text/html | 500 |
| **/api/dashboards/db| data source not found | 500 |

**What you expected to happen**:
Based on the error messages, it appears that all the failed requests were caused by client errors. Therefore, we should anticipate the appropriate status code to be returned, rather than a generic 500 Internal Server Error.e.g. 4##;

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2.2
- Data source type & version: promethues
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

```[tasklist]
### Issue Tracking
- [ ] https://github.com/grafana/grafana/issues/65828
- [ ] https://github.com/grafana/grafana/issues/65830
- [ ] https://github.com/grafana/grafana/issues/65831
- [ ] https://github.com/grafana/grafana/issues/67195
- [ ] https://github.com/grafana/grafana/issues/68168
```

**Comment by tonypowa** [comment]
thanks for creating this issue @peqi-ms 

i have run a few test against my local instance of Grafana (v9.3.2) where i have Prometheus installed. I couldn't repro those response codes. Perhaps I am missing something? Please feel free to add any additional info to help troubleshooting this issue.

Assuming I got the GET,POST actions right, here are my results. 

> /api/v1/eval

reference: [prometheus instant queries api](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) 

**GET**

_ /api/v1/query?query=up&time=2015-07-01T20:10:51.781Z

Response status 200 OK

> /api/folders | invalid API key | 500

reference : [prometheus api rules](https://prometheus.io/docs/prometheus/latest/querying/api/#rules) 

even with no folders i **GET** a 200 OK response with an empty string []  in the response body representing no folders

>/api/dashboards/db

**POST**
body sent:

```
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0,
    "refresh": "25s"
  },
  "folderId": 0,
  "message": "Made changes to xyz",
  "overwrite": false
}
```

Response status 200 OK

**Comment by peqi-ms** [comment]
Hi @tonypowa , thanks for your quick response!
Unfortunately, such failed requests came from our external customers, so we cannot repro those response code either from our side. 
From my opinion, according to Grafana logs and error msg, we can tell if such errors were caused by customer side without repro failed cases. Based on this, you can set appropriate response code according to that.

Taking first one as example, I searched "Failed to evaluate queries and expressions" in Gafana source code, it only occurs in api_testing.go:(https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/api_testing.go#L141), according to function name,  it looks like used for testing alert rule queries. If error in Line 141 match customer error case, is it ok to set ErrResp as http.StatusBadRequest? 

![image](https://user-images.githubusercontent.com/106532917/220929524-8ee04daf-eac1-4dc2-988d-f544b749306e.png)

**Comment by tonypowa** [comment]
thanks for taking the time to look into the code @peqi-ms 

i am adding this issue to the backend squad's board for review

**Comment by peqi-ms** [comment]
The same issue also happened to following endpoints:
| url  | error msg | current status code |
|:-----|:----------| :-----------------|
| **PUT /api/datasources/uid/{UID}**| [Failed to evaluate queries and expressions: failed to execute query D: no handler found for query type ''](pq: duplicate key value violates unique constraint \"UQE_data_source_org_id_name\) | 500 |
| **POST /api/ruler/grafana/api/v1/rules/Legacy Alerts**| failed to update rule group: failed to add rules: a conflicting alert rule is found: rule title under the same organisation and folder should be unique
 | 500 |

**Comment by tolzhabayev** [comment]
@tonypowa thanks for routing, please use this board https://github.com/orgs/grafana/projects/96 for backend platform related issues. I'll take a look at the other one and maybe archive it. Will make sure first to deal with the issues in ToDo.

**Comment by sakjur** [comment]
Note: We need to split this up to different squads, this belongs to very diverse parts of the code (in particular some belong to Grafana's embedded Alertmanager, which is a separate API alltogether).

**Comment by tonypowa** [comment]
one more new related issue here: 
```
GET /api/v1/provisioning/alert-rules/{UID}
```
500 response code returned


https://github.com/grafana/grafana/issues/66249

**Comment by peqi-ms** [comment]
Hi @tolzhabayev add another one, not sure which squad it should redirect to:
| url  | error msg | current status code |
|:-----|:----------| :-----------------|
| **/api/serviceaccounts/6/tokens/1**| Failed to delete service account token | 500 |

Dive into code, this is error thrown when delete service account token:
![image](https://user-images.githubusercontent.com/106532917/233832727-4588070c-ac5e-4647-a23b-8918041795bc.png)

the implement for extract service account token came from :
![image](https://user-images.githubusercontent.com/106532917/233832847-1717be66-10a1-48ba-88a6-0a5fabee1d76.png)

Not sure for this case, customer should expected 4## status code?

**Comment by eleijonmarck** [comment]
i have failed to replicate the issue with the service accounts, I am setting up a service account and then deleting a non-existing token. we get 404. we did change the code 2 months ago with this PR - https://github.com/grafana/grafana/pull/64299

Do we still see this error in newer versions of grafana?

**Comment by mengjie-ms** [comment]
Thanks @eleijonmarck! Our customers' Grafana workspace with version 9.4.12 still return 500 with "service account token not found". I checked the source code of v9.4.2, it doesn't include the fixed PR. I also checked the v9.5.1 and other 9.5.x, they have included the fix and returned correct 404 status.

**Comment by nikimanoledaki** [comment]
@peqi-ms, are you still seeing the 500 errors for the services below? I'm not able to replicate the errors unfortunately. Any additional steps or info on which operations led to this error would be great, thank you! 

| url  | error msg | current status code |
|:-----|:----------| :-----------------|
| **/api/folders**| invalid API key | 500 |
| **/api/dashboards/db| data source not found | 500 |

**Comment by mengjie-ms** [comment]
Hi @nikimanoledaki, could you please help to find the fix PR for the below two services? I didn't find the fix PR. 
url | error msg | current status code
-- | -- | --
/api/folders | invalid API key | 500
**/api/dashboards/db | data source not found | 500

**Comment by taleena** [comment]
@tolzhabayev Closing this epic now that all tasks are completed, please reach out if that is incorrect!
