### ISSUE TITLE
embed issue

### ISSUE THREAD

**Issue by p0nts** [grafana/grafana#6355]
[*] Bug report

- What Grafana version are you using? Version 3.1.1 (commit: a4d2708)
- What datasource are you using? influxdb
- What OS are you running grafana on? Debian Wheezy 7.11

I am trying to embed graphs into my icinga2 installation, for some reason it never shows data from the actual host (templating) I specify in the URL, but instead uses the host that is on the dashboard after a save, please see screenshots for example:

templating for host:
http:///shot.xsnews.nl/stefan/f95316fec79c1225.png

icinga2-cpu-load graph in grafana, with feeder04 as selected and saved host in the templating:
http:///shot.xsnews.nl/stefan/9128ec19018d2b63.png

icinga webinterface, together with host / graph / data:
http:///shot.xsnews.nl/stefan/4c6a0c0dcc869d68.png

As you can see on the latest screenshot in the top of the screenshot I watch information for server with the name "fsa032".

The graph should have data from "fsa032" in its graph, but for some reason it uses the data from "feeder04" which is also shown in the second screenshot.

When I look at the share link of that graph, it shows:

http://localhost:3000/render/dashboard-solo/db/icinga2-cpu-load?panelId=2&var-hostname=**fsa032**&from=1477039316077&to=1477053416077&var-host=**feeder04**&width=1000&height=500 (its local so not working, just for the URL)

So for some reason it first uses my templating hostname, but adds the default saved templated host at the end of the link...

This whole configuration was working with version 3.1.0, so this seems to be something that came after 3.1.1 was installed.

**Comment by p0nts** [comment]
add:

In the source of the page, the second var-host=* is not even there:

http:///shot.xsnews.nl/stefan/9845765caad20761.png

So it seems to go add _"&from=1477039316077&to=1477053416077&var-host=feeder04&width=1000&height=500"_ after the link is clicked or something ...

**Comment by torkelo** [comment]
cannot replicate it here
http://play.grafana.org/dashboard/db/elasticsearch-templated?var-source=site&var-host=server1

The share & embedd urls contain the current template variable.

**Comment by p0nts** [comment]
Yes its very weird, because when I look in the source of the page I dont see 2 hosts defined in the iframe url, but when I check the iframe itself with the share option suddenly a second template variable is included along with a few other variables.

shown here: http:///shot.xsnews.nl/stefan/9845765caad20761.png


thank you for the help btw.

**Comment by p0nts** [comment]
Yes its very weird, because when I look in the source of the page I dont see 2 hosts defined in the iframe url, but when I check the iframe itself with the share option suddenly a second template variable is included along with a few other variables.

in this screenshot you can see that the source of the page does not state a second host variable
http:///shot.xsnews.nl/stefan/9845765caad20761.png

In the bottom of this screenshot, you can see the share url that have a second host variable from a graph when I click share:
https://www.dropbox.com/s/gsztk3daxx1df5i/Screenshot%202016-10-22%2009.08.46.png?dl=0

thank you for the help btw.

**Comment by torkelo** [comment]
>  but when I check the iframe itself with the share option suddenly a second template variable is included along with a few other variables.

I am sorry I do not follow you. What does your query look like and what is query is being issued?

**Comment by p0nts** [comment]
Ok, in the following screenshot you can see the source of the page with the embeded iframe:
http:///shot.xsnews.nl/stefan/9845765caad20761.png
As you can see in this source, there is only one "var-host" variable stated in the URL.

When you look at the second screenshot, you can see the share settings of the same graph. But for some reason there are 2 "var-host" variables stated in the share URL.

https://www.dropbox.com/s/gsztk3daxx1df5i/Screenshot%202016-10-22%2009.08.46.png?dl=0

So for some reason, the default "var-host" variable is put inside the url, which causes my graphs to show the data from the lastly added "var-host" variable in the graph.

The second "var-host" variable that gets added, is the host that you can find as soon as you browse the dashboard that has this graph in the select menu. The same way you can save a template with certain refresh values, this url shows the "var-host" variable that is saved within the dashboard.

Hope this will help.

**Comment by p0nts** [comment]
Whoops I found the issue, I had a typo in the URL.

I am so sorry to use your time on this, this topic can be closed!
