### ISSUE TITLE
Glue: Feature Tracking

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#63559]
### Background

We need proper feature tracking in order to measure how correlations are used and to have tools to make decisions in the future.

### Requirements ###

High level: _Add feature tracking required to decide how successful is the feature and help deciding about improvements in the future_

We need to surface the data referenced in this dashboard https://ops.grafana-ops.net/d/b90d1899-a5d5-4bf5-8b2c-bfed2371443a/grafana-correlations-adoption-stats?orgId=1

Required events - more info in[ the doc](https://docs.google.com/document/d/1-Bun_Gvhx97Y8AfTrJSihl3NECM3fjg-IfR6CxsOi8g/edit#)

```[tasklist]
### Todo
- [ ] #64224
- [ ] #63940
- [ ] #64223
```

**Comment by meanmina** [comment]
Surface the data referenced in this dashboard https://ops.grafana-ops.net/d/b90d1899-a5d5-4bf5-8b2c-bfed2371443a/grafana-correlations-adoption-stats?orgId=1
