### ISSUE TITLE
Query Editor: dropdown menu overflowing the screen when positioned near the bottom

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#63558]
**What happened**:
When there is a `Select` component near the bottom of the page with the dropdown menu opened, the last options of the list are not available as they are overflowing the screen.

**What you expected to happen**:
The `Select` menu should calculate where to position itself correctly.

**How to reproduce it (as minimally and precisely as possible)**:
1.- Reduce your window height. You can also reduce the height of the builder/editor component when editing the panel.
2.- Edit a panel with a `Loki` datasource.
3.- Open the label selector and scroll to see the last option.

https://user-images.githubusercontent.com/65417731/220601842-374b8a52-6d69-43d3-8dd2-9f3f34b6fb8a.mov

**Anything else we need to know?**:

1.- This occurs using both `Loki` and `Prometheus`, although we should also check this behaviour in the rest of the data sources.
2.- This issue was raised by [the escalation 5087](https://github.com/grafana/support-escalations/issues/5087)
3.- There was a similar bug working with `InfluxDB`, which was fixed by #60087.

**Environment**:
- Grafana version: 9.x
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by doanbutar** [comment]
Hello @eledobleefe, Just a quick follow-up to see if there is any update on this issue or if you may know a rough ETA when this issue will be fixed?

**Comment by eledobleefe** [comment]
Hello @doanbutar! We are focusing on other projects at the moment. Having the solution for the similar bug found as criteria, it could be an easy fix so we will tag it as "help wanted" and be open to PRs from the community to fix it.

**Comment by doanbutar** [comment]
Hi @eledobleefe, It seems there has been no response from the community for over a month. I guess it's normal but I am wondering if in any way we can continue to review the issue and work on a fix?

**Comment by joshhunt** [comment]
See also this snippet

https://github.com/grafana/grafana/blob/969ad1b/packages/grafana-ui/src/components/Select/SelectBase.tsx#L157-L172
