### ISSUE TITLE
Regression 9.4.0-beta1; allow_org_create creates org, but doesn't add user to it. Adds user as Admin on orgID=1 instead.

### ISSUE THREAD

**Issue by niclash** [grafana/grafana#63562]
**What happened**:
OSS Edition, configured to auto create organizations and NOT add user to `orgID=1`.

Organization is created when user is registering, either with GitHub or GMail or "Sign up" buttons. User is NOT added to the organization that is created, and instead added to OrgId=1

**What you expected to happen**:
That the created user is NOT added to the  `orgID=1` and that the user IS ADDED to the organization that the user just created.

**How to reproduce it (as minimally and precisely as possible)**:
```
sudo dpkg --purge grafana
sudo rm -rf /var/log/grafana/ /var/lib/grafana/ /etc/grafana/

wget https://dl.grafana.com/oss/release/grafana_9.4.0~beta1_amd64.deb
sudo dpkg --install grafana_9.4.0~beta1_amd64.deb 
sudo vi /etc/grafana/grafana.ini
```
change to;
```
allow_sign_up = true
allow_org_create = true
auto_assign_org = false
auto_assign_org_id = 1
auto_assign_org_role = Viewer
```
and then
```
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable grafana-server
sudo systemctl start grafana-server
```

WAIT for grafana to complete first start up. `tail -f /var/log/grafana/grafana.log`

Then on start page, do "Sign up". I get to ?orgId=1 on 9.4.0-beta1 but to ?orgId=3 on 9.3.6

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.0-beta1
- Data source type & version: Irrelevant
- OS Grafana is installed on: Linux Debian
- User OS & Browser: Shouldn't matter
- Grafana plugins: Irrelevant
- Others:

**Comment by niclash** [comment]
I think I have located the problem, and the root cause is a combination;
1. In `store.go` line 79, an `sess.insertOne()` is called, and the variable name is marked `orgID` for one return value, when that is something else (number of records/beans?) as xorm has no idea about a `orgID`
1. That is called on the last line (98) `GetIDForNewUser()` in `orgimpl/org.go` , which is called from line 89 in `user.go`

Changing line 98 in orgimpl/org.go to
```golang
	_, err := s.store.Insert(ctx, &orga)
	return orga.ID, err
```
seems to work.

**Comment by niclash** [comment]
That said; it seems that even earlier versions have this faulty code, so it doesn't explain that it seems to work in 9.3.6.

**Comment by niclash** [comment]
There is the same naming issue in `func (ss *sqlStore) InsertOrgUser(ctx context.Context, cmd *org.OrgUser) (int64, error)`, but faulty return value is not used.

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @niclash  and for all the details you provided of your own research 👏 

i'm forwarding this issue to the authentication squad

**Comment by Jguer** [comment]
Hey @niclash , I started looking at reports of this and fixing it without seeing your issue but I want to tell you your research was spot on :+1:.

I could not reproduce this in 9.3.6 and 9.2.10 which include the same line of code and we're still looking for the secondary sanity check that was probably removed in 9.4.0 for the bug to manifest itself.

- Users having been created, without valid email and "never" logged in
- Users disappearing from organizations. This was last observed yesterday, after I had removed some such invalid users.

can you give us some more info on these? Are you using any external authentication provider?

**Comment by niclash** [comment]
I have set up GitHub, GMail and "Sign Up" to the public instance. I am using Postgresql as backend. No LDAP or other user management is present.

I have noticed it on my public instance twice (I don't look very often), and each time half a dozen of these bizarre users, that I just proceeded to remove. However, last time I did it, was the time when OrgUsers disappeared from the major customer's Organization, hence suspicion that it is somehow related, but no idea how. 

I should probably open a separate issue when I have more information.

**Comment by Jguer** [comment]
So `[auth.google]` and `[auth.github]` then :+1: 

bizarre users - if you have examples it would be great, maybe it's users that signed up but never confirmed their email?

Please open a separate issue if you can provide more information, you can tag me on it

**Comment by niclash** [comment]
Confirmation is not required. Email (& Name) field was just a random sequence of characters.
