### ISSUE TITLE
 InfluxDB Error: undefined

### ISSUE THREAD

**Issue by rollin-s** [grafana/grafana#6357]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? influxDB
- What OS are you running grafana on?Debian
- What did you do? I tried to add a data Sources, but I keep having the same error : InfluxDB Error: undefined
- What was the expected result? My Data sources is added
- What happened instead? Error --> InfluxDB Error: undefined

![capture du 2016-10-21 16-17-35](https://cloud.githubusercontent.com/assets/19536465/19601542/0ffd2512-97aa-11e6-9053-4b7df71720f3.png)

I am Running grafana on a external server.. I'm not sure, but maybe the "localhost" doesn't work, because I am not in the same server than the browser.. 

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
make sure you can acccess influxdb from http://localhost:8086 from the same machine grafana-server is running on

**Comment by rollin-s** [comment]
Hrm. If i enter http://my-ip;8086, I get a 404 page not found.

Do I have to do something special on my server to make 8086 port working ?

**Comment by torkelo** [comment]
no, that the default influxdb port. InfluxDB 0.8x is not supported by the default InfluxDB data source.

It is very old and InfluxDB completely changed their query API in 0.9x

The old 0.8x plugin is here:
https://grafana.net/plugins/grafana-influxdb-08-datasource

But it might be buggy, no one has developed / fixed bugs in the plugin for a while
