### ISSUE TITLE
loki: query splitting: empty query does not clear results

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#63579]
how to reproduce:
1. make sure the `lokiQuerySplitting` feature-flag is enabled
2. go to explore
3. choose a loki datasource, `code` mode.
4.  run a logs-producting loki query
5. logs-results will appear
6. now clear the logql query from the text-field, so it is completely empty
7. run the query
8. the logs-results do not disappear

when running without loki-query-splitting, in step-8 the logs-results do disappear.

**Comment by gabor** [comment]
notes (i consider the `explore` use-case here, but i assume the `dashboard` use-case has the same root cause:
1. we do send a `subscriber.next()` with an empty dataframe-array. so that part is correct.
2. somehow that `next()` does not reach the `next()` at https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L530 , i think this is why the bug exists.
3. `runRequest.ts` does a thing where it automatically adds a loading-state-step, if the datasource's query takes a long time and the datasource did not do such a thing at: https://github.com/grafana/grafana/blob/main/public/app/features/query/state/runRequest.ts#L171 . if i change that line into `return dataObservable`, then the bug goes away.

**Comment by matyax** [comment]
Fixed in https://github.com/grafana/grafana/pull/64053
