### ISSUE TITLE
Passing the Grafana logged in user Details to DataSource Rest API

### ISSUE THREAD

**Issue by vganjare** [grafana/grafana#6359]
Hi,

While configuring any datasource (e.g. Elastic Search DataSource, grafana version V3.1.1), we can specify http_auth with either Basic Auth or with Credentials. Both these configurations can be specified in Direct Mode or Proxy Mode access.

The Basic Auth works as expected and uses the username and password provided for accessing the REST API (in current case Elastic Search)

The With_Credentials options is not working as expected. In direct mode or proxy mode, it does not pass any credential information to the datasource rest API.

Is it possible to pass the grafana logged in user details to Elastic Search as well?

Thanks,
Vishal

**Comment by olsky** [comment]
+1 

I think, it is very useful feature not only for the ElasticSearch, I'd love to have it for InfluxDB.

**Comment by vishnunkk** [comment]
i vote for this one

**Comment by txiaoyi** [comment]
vote for all data source in general.

**Comment by Foxeronie** [comment]
+1
We limit access to indices in Elasticsearch with Search Guard. It would be very helpful, if the Grafana credentials could be passed to Elasticsearch, so every user can access his/her own data without creating a source for every person with some seperate credentials configured in Search Guard.

**Comment by bergquist** [comment]
Looks like search guard can support any header. https://docs.search-guard.com/latest/proxy-authentication
So solving #15931 would also solve this.

**Comment by aocenas** [comment]
With https://github.com/grafana/grafana/pull/15998 merged you can set `send_user_header = true` in config and Grafana will send `X-Grafana-User` header with current users username (if user isn't anonymous). This is done only in proxy (server) mode.

That should work for your usecase but if not please let us know.
