### ISSUE TITLE
Docs: Update plugin.json documentation

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#63614]
**What happened**:

The current [plugin.json documentation](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/). Some descriptions are not complete enough, leading to confusion. We should make sure that the documentation reflected there is complete an up to date.

TODO:

- [ ] Update plugin.schema.json
- [ ] Update plugindef
- [ ] Regenerate docs

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tolzhabayev** [comment]
Just if we want to: we could potentially also generate plugin.schema.json out of plugindef and then docs out of plugin.schema.json in some automated way or at least via makefile / commit hooks.

**Comment by andresmgot** [comment]
> Just if we want to: we could potentially also generate `plugin.schema.json` out of `plugindef` and then docs out of `plugin.schema.json` in some automated way or at least via makefile / commit hooks.

Each of those steps `.cue` > `.json` and `.json` > `.md` (or `.cue` > `.md`) would require us to write a custom parser. The step from `plugin.schema.json` to `readme.md` seems more valuable to me but still quite complicated because of how the structure of the readme is at the moment (with subsections and extra descriptions). An easier thing to do would be to at least write a unit test to verify that the files are in sync so we are not missing fields and the descriptions match.

**Comment by andresmgot** [comment]
Turns out there is already a mechanism to go from `plugindef.cue` to `plugin.schema.json`:

https://github.com/grafana/grafana/blob/main/pkg/plugins/plugindef/gen.go#L93

But it generates a JSON with a quite different schema so it not seems ready to be used. Anyway, good for the future.

For generating the `metadata.md` file, there is also a template file but it's mostly empty:

https://github.com/grafana/grafana/blob/main/docs/sources/developers/plugins/metadata.md.tpl

Anyway, good starting points for the future. I am going to leave as the scope of this issue to do manual changes.

**Comment by tolzhabayev** [comment]
For the https://github.com/grafana/grafana/blob/main/docs/sources/developers/plugins/metadata.md generation, I think we are using https://github.com/marcusolsson/json-schema-docs

**Comment by andresmgot** [comment]
> For the https://github.com/grafana/grafana/blob/main/docs/sources/developers/plugins/metadata.md generation, I think we are using https://github.com/marcusolsson/json-schema-docs

yeah, I saw that reference but I don't see anyplace in which it's actually plugged in together. In fact I see that the current schema and the docs are already out of sync so I suspect that was removed at some point.

**Comment by GrafanaWriter** [comment]
@josmperez - can you please take a look?
