### ISSUE TITLE
Docs: Document how NPM dependencies work for plugins

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#63622]
**What happened**:

The sytem that replaces NPM dependencies from a plugin depending of the Grafana version running is not documented. As far as I know, it involves the [webpack configuration](https://github.com/grafana/grafana/blob/main/packages/grafana-toolkit/src/config/webpack.plugin.config.ts#L166) and the [plugin loader](https://github.com/grafana/grafana/blob/main/public/app/features/plugins/plugin_loader.ts#L92-L115) so there should be documentation for plugin developers to know how to work with that.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

```[tasklist]
- [x] Draft content for NPM dependency doc
- [x] Edit/review content for NPM dependency doc
```

**Comment by josmperez** [comment]
@andresmgot - Hi Andres - Can you suggest a developer with the necessary expertise to draft a PR or Google Doc with this information?

**Comment by andresmgot** [comment]
I think people within @grafana/plugins-platform-frontend should be able to write about this. In particular @mckn is working on the possibility of bundling @grafana/ui with a plugin which is also relevant.

**Comment by mckn** [comment]
> I think people within @grafana/plugins-platform-frontend should be able to write about this. In particular @mckn is working on the possibility of bundling @grafana/ui with a plugin which is also relevant.

Yeah, I'm happy to help out with some documentation for this when I'm done with some of the work that I currently have ongoing.

**Comment by josmperez** [comment]
@mckn - Let's collaborate on this in Q4. If you could get us started with draft content, that would be great.

**Comment by jackw** [comment]
I've put a quick draft [google doc](https://docs.google.com/document/d/13-NExUeRl7hT3XcZfFGn5SphqW4cWll4hk9LDCoXlmM/edit) together to help out here. Feel free to comment / edit it as you need.

**Comment by mckn** [comment]
> @mckn - Let's collaborate on this in Q4. If you could get us started with draft content, that would be great.

Sounds good! I will go and add a couple of things in the doc @jackw has linked.
