### ISSUE TITLE
Docs: Plugin good practices

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#63625]
**What happened**:

Right now there are no single place that plugin developers can look in order to verify that their plugin is following  recommended good practices. These good practices may already be documented but they are scattered among:

 - The current [documentation](https://grafana.com/docs/grafana/latest/developers/plugins/)
 - The plugin [examples](https://github.com/grafana/grafana-plugin-examples/tree/main/examples)
 - (maybe?) Current grafana-owned plugins

**What you expected to happen**:

To have an index of good practices, linking to other documentation pages or examples for extra information.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

There is also the Grafana Plugin Tools page:

https://grafana.github.io/plugin-tools/

This may serve as a good starting point to create an index of good practices.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by josmperez** [comment]
@sympatheticmoose - I am inclined to ask one developer to take point in starting this list and then seeking contributions in Slack and in the PR review process. Would this work, or would you suggest a different procedure for building the content for this topic?

**Comment by josmperez** [comment]
@andresmgot - Would you help by drafting some of the content for this PR some time in Q4? I have in mind also that I will draft some content and we can also group source this for additional ideas.

**Comment by sympatheticmoose** [comment]
There's two sides to best practices that I think we need to cover, code vs publishing.

For the former, by all means start to gather that draft content but we will need to consider where it gets folded into our documentation. Is it part of the general flow a developer follows through our docs where we encourage progressively incorporating best practice, or a catch-all checklist style document which acts more as an index to other content? 

For the latter, I think it very much is just a single page, _similar_ to https://grafana.com/blog/2021/01/21/6-tips-for-improving-your-grafana-plugin-before-you-publish/. Suggest a new ticket for this which I'll be happy to help author in Q4.
