### ISSUE TITLE
Alerting: Show top K alert transitions by volume over time

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#63658]
We can use state history to show a `topk` pareto of firing alerts over time. We could also show how this compares to, say, the previous week.

We could ship a canned dashboard for this, or also create a bespoke UI component.

Miro: https://miro.com/app/board/uXjVPohieI0=/?moveToWidget=3458764545777496807&cot=14
Votes: 2

**Comment by VikaCep** [comment]
This panel shows top most fired alerts over the last one day:

https://admin-dev-us-central-0.grafana.net/directory-alerting/grafana-statehist-alerting-ops/d/IhbCPI04k/state-history-dashboard?orgId=1&viewPanel=4

It would be a nice addition to also show most fired alerts over previous days (or weeks) and show a trend.
