### ISSUE TITLE
Alerting: Improved history view of an individual alert rule

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#63656]
We can use state history to improve on the existing history view of an individual alert rule. We can add dynamic filtering or better label hierarchy, for instance.

Miro: https://miro.com/app/board/uXjVPohieI0=/?moveToWidget=3458764545777496807&cot=14
Votes: 3

**Comment by gillesdemey** [comment]
We should try to get some folks from Incident and OnCall involved in some of the decision making here so we can share components and libraries to help get alert state history implemented.

**Comment by gillesdemey** [comment]
This currently depends on redesigning the alert detail view so we can fit all of this information.

**Comment by gillesdemey** [comment]
After some deliberation we've settled on implementing Alert State History in the existing alert history modal – but using the new history API endpoint.

Sharing our approach here

## Approach

- [x] Start with RTK implementation; fetch history from “/api/v1/rules/history”
- [x] Show different modal when using “loki” backend
- [x] Group records by “instance” (which is unique set of labels)
- [x] Render logs for each instance (transform JSON data frame to a log line)
- [ ] Render viz
    - Either transform JSON data frames to work with timeline viz
    - Figure out how to do this with Loki query
- [ ] Allow filtering by instance
- [ ] render a “expore” button so users can do custom metric queries
- [ ] Make it pretty and stuff

**Comment by gillesdemey** [comment]
We hit some technical roadblocks implementing the "explore" button since matching the loki instance endpoint to an existing data source can't happen in the front-end. We're exploring options to move this logic to the back-end but this means that particular feature will likely not make it in the first release.
