### ISSUE TITLE
Singlestat panel + Graph panel: Make a difference between current and last

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#6366]
In singlestat panel and graph panel, «current» means «last». It means that if there is no current value, it will display the last one.

Proposal to add a maximum age to the last value, after which the current values is displayed as null.

**Comment by torkelo** [comment]
yes, the name for current should probably be "last". 

But depending on your TSDB and query you can get "NA" (or null) as the last value and then the "current" value will be null, so you can see that there is no value
