### ISSUE TITLE
Alerting: Troubleshooter for alert rules driven by state history

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#63660]
If state history detects that a rule is flapping Normal->Firing->Normal->Firing a lot (over some threshold), we can flag it to the user and offer a tooltip or troubleshooter in the UI. This can be a simple message that just brings the rule to a user's attention and suggests next steps, like:
1. Maybe the datasource behind this rule is flaky and needs investigation
2. Maybe the query in the rule could use some refinement
3. Maybe the `for` period is incorrectly tuned.

Miro: https://miro.com/app/board/uXjVPohieI0=/?moveToWidget=3458764545777496807&cot=14
Votes: 2

**Comment by benoittgt** [comment]
Hello

We are in this situation and it's hard for us to investigate. 

Alerting is defined like that:

![Screenshot_2023-11-08_at_21_18_29](https://github.com/grafana/grafana/assets/8417720/92fe4c81-a453-42c4-9d63-fa0b3197057b)

![Screenshot 2023-11-08 at 21 18 24](https://github.com/grafana/grafana/assets/8417720/4aad00c2-1a7b-49cc-a75e-863e010f0d87)

But we get "normal" event even if the data is always 0.

State changes:

![Screenshot_2023-11-08_at_20_59_07](https://github.com/grafana/grafana/assets/8417720/4661dfd3-5598-42e1-9a48-a204b51d6c6d)

But if we look at graph for the day.

![Explore_-_Prometheus_-_Grafana](https://github.com/grafana/grafana/assets/8417720/0b8181c5-13c6-47a1-9a40-1f86e6126c6d)


Alerts are updated every 30min via [API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/). But there is very rarely changes that would explain the "normal" state.
