### ISSUE TITLE
Variables definition page is not updating.  

### ISSUE THREAD

**Issue by jars99** [grafana/grafana#63679]
On the Variables page, there is a preview of the variable definition.  This is showing a config that I had previously defined, and isn't updating when I change that variable query.  

Here's what the preview looks like:
<img width="828" alt="Screenshot 2023-02-23 at 11 11 02 AM" src="https://user-images.githubusercontent.com/4067216/220995880-dc38ec52-4de4-4afc-ba88-9611bd8b0d39.png">

Here's what the variable is actually configured as:
<img width="1113" alt="Screenshot 2023-02-23 at 11 11 21 AM" src="https://user-images.githubusercontent.com/4067216/220995903-6ed42c07-7025-4b63-b107-4cc5027bd1f5.png">

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: CloudWatch 5.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome and Safari
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @jars99 

Could you try to get the preview and see what the logs say? That could be helpful

You can increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/
