### ISSUE TITLE
Replace go-multierror with errors package in Go 1.20

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#63686]
We should replace usage of `go-multierror` with the errors package once Grafana moves to Go 1.20. For example, using https://pkg.go.dev/errors#Join and `fmt.Errorf` with more than one `%w`.

**Comment by sankeerth125** [comment]
Hi @grobinson-grafana, can I work on this issue?

**Comment by ashutosh887** [comment]
@grobinson-grafana I would like to work on this. I've set up the code on my system

**Comment by ashutosh887** [comment]
@grobinson-grafana Should I start?
