### ISSUE TITLE
Prometheus annotation query ranges break apart when viewing more than a ~2h time range

### ISSUE THREAD

**Issue by dqsully** [grafana/grafana#63687]
**What happened**: With Prometheus-based annotation queries enabled on a dashboard, zooming out too far causes the annotation range to be processed instead as individual annotations, specifically when the annotation query time interval is greater than 60s.

Screenshot of an affected graph at a 3h time range:
![Screenshot_20230223_142251](https://user-images.githubusercontent.com/9079721/221033377-46fd18ef-ba85-492a-aed2-5e88651c291a.png)

**What you expected to happen**: Prometheus-based annotations should respect the time interval returned from the query, rather than assuming it's 60s or less.

Screenshot of the same graph, but at a 2h time range:
![Screenshot_20230223_142312](https://user-images.githubusercontent.com/9079721/221033535-651e49b9-d439-4657-b024-dc80d1527ba7.png)

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard with a graph panel (any size), add a Prometheus-based annotation query to the dashboard, view a range where the annotation query is active, leave the "min step" field unset, and zoom out to a 3h range or greater.

**Anything else we need to know?**: This line appears to be the culprit. It assumes that the annotation's "min step" setting is the interval that the data source will also return data at, which causes problems when data is returned more sparsely: [plugins/datasource/prometheus/datasource.tsx:827](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L827). I'm not familiar enough with the Grafana codebase to know exactly what the fix is though.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Prometheus 2.39.1
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox 111
- Grafana plugins: defaults for Grafana Cloud
- Others:

**Comment by tonypowa** [comment]
reproduced the issue as described
-> forwarding issue to the dashboard  and observability metrics squad

Note: my prom based annotation was simply `up{instance="localhost:9090"}`
repro:

last 3h display multiple annotations of "up":
![image](https://user-images.githubusercontent.com/45235678/221153984-6e93afc2-2643-4c3f-89ad-8de9198fe3d7.png)

last 2h shows as a single annotation (as it should be because the instance above was up all that time range):

![image](https://user-images.githubusercontent.com/45235678/221154096-ab166688-560f-43f0-8176-85b2ace77637.png)

| Panel | graph @ 9.3.2 |
| Grafana | 9.3.2 (21c1d14e91) // Open Source |
| prometheus: v2.41.0 |

**Comment by dprokop** [comment]
@tonypowa thanks for heads up. Seems like this should land in @grafana/observability-metrics pond given the interval based batching is implemented directly in the Prometheus data source. @grafana/observability-metrics - please let me know if there is anything Dashboards squad can help you with.

**Comment by fdomain** [comment]
I've just run into the same issue, do you have any update on this, or is there a workaround to display the annotation correctly ? Thanks

**Comment by nlowe** [comment]
@bohandley is there an issue I can follow for that work? I'd love to get notifications when a solution for this is available.

**Comment by bohandley** [comment]
@leeoniya do you have a link for the dataviz squad work for annotation ranges?

**Comment by bohandley** [comment]
Reopening this issue @nlowe, this issue should be solved by this [feature request](https://github.com/grafana/grafana/issues/55187#issuecomment-1890273620), and dataviz has offered to take it on.

**Comment by bohandley** [comment]
@grafana/dataviz-squad Do you have a link to the work for annotations you are doing around annotations grouping?

**Comment by robhamnett** [comment]
+1 this bug makes annotations almost unusable

**Comment by konstantin-kornienko** [comment]
Trying at least to fix the usage of variables in the `min step` field ^^^.
