### ISSUE TITLE
Alerts are going to everyone and not to specified recipients

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6369]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Nightly Build
- What datasource are you using? Graphite/OpenTSDB
- What OS are you running grafana on? Amazon Linux
- What did you do? Setup an alert and did not configure any notification recipient.
- What was the expected result? No one should be notified about it.
- What happened instead? Everyone got notified. :(

**Comment by torkelo** [comment]
What does your notification options look like? (in the notifications / edit view). Is the "Send on all alerts" checkbox checked?

**Comment by utkarshcmu** [comment]
@torkelo No the "Send on all alerts" is not checked. I also checked the db tables and the "isDefault" column is set to 0. So, I am not sure why Grafana is sending an alert. Here are some logs:

```
t=2016-10-25T00:16:31+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=1 isDefault=false
t=2016-10-25T00:16:31+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=2 isDefault=false
t=2016-10-25T00:16:31+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[utkarsh.cmu@gmail.com]
t=2016-10-25T00:16:31+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=11 notification=slack-channel
```

**Comment by torkelo** [comment]
and the alert definition? what does it look like? (json) anything in notifications array?

**Comment by utkarshcmu** [comment]
Here is the alert definition:

```
"alert": {
    "conditions": [
      {
        "type": "query",
        "query": {
          "params": [
            "A",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "type": "avg",
          "params": []
        },
        "evaluator": {
          "type": "gt",
          "params": [
            100
          ]
        }
      }
    ],
    "noDataState": "no_data",
    "frequency": "15s",
    "handler": 1,
    "notifications": [],
    "name": "Some test alert"
  }
```

Notifications array is empty but all the notification recipients are receiving alerts.

**Comment by torkelo** [comment]
I guess there is an issue when reading notifications and there are none you get all :)

**Comment by utkarshcmu** [comment]
The problem was in mysql query. It was searching for:
```is_default="true/false"``` instead of ```is_default="0/1"```
