### ISSUE TITLE
loki: query splitting: instant queries are split wrong

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#63696]
when running metric instant queries, the chunking is wrong.

probably caused by:
a loki instant query "needs" only a single-timestamp. so we use the grafana-time-range-end-timestamp ( https://github.com/grafana/grafana/blob/main/pkg/tsdb/loki/api.go#L73-L77 ).
but the query-chunking code does not know this, so it considers the whole grafana-time-range to create chunks.

so we should skip them and not-chunk them

**Comment by matyax** [comment]
Fixed in https://github.com/grafana/grafana/pull/64049
