### ISSUE TITLE
${__user.name} variable doesn't work

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#63709]
**What happened**:
I'm trying to get tje user logged name using ${__user.name} but it doesn't work. I use a query type with mysql. So the variable's syntax is:
SELECT  '${__user.name}'

**What you expected to happen**:
To get the usar's name

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: phpmyadmin 5.2.0
- OS Grafana is installed on:  Windows
- User OS & Browser: windows, chrome
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @DonatoD 

are you able to run the query without wrapping the variable with quotation marks? 

are there any error messages or feedback when you run the query?

Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by DonatoD** [comment]
I have tryed in all format available within the doc: with/without quotation marks, with single or double ones, with/without brace, ecc. Nothing. As a result I always get "1". But I think it's just because the code is not executed. In Fact I get this result even with a completely wrong syntax. Until some versions ago it was easier to understand if something was wrong, now you don't see anything.
I just notice one think: nn the console I always get this error whatever dashboard I start:
![image](https://user-images.githubusercontent.com/51508670/221540790-38428cdd-0a1c-41c2-bce9-1f1ccd5cc5c2.png)
Even if I simply go to the browser tab, i get this error
![image](https://user-images.githubusercontent.com/51508670/221541368-a07e5ee4-038c-436f-a19b-2300a4e68c20.png)
I don't know it this is related, but, I already rised another issue always regarding variables
https://github.com/grafana/grafana/issues/59453

**Comment by DonatoD** [comment]
Anyway, writing the correct syntax I don't see any error it just returns 1
![image](https://user-images.githubusercontent.com/51508670/221551177-3c2c3fa1-d707-4409-a834-22074b713b1a.png)

**Comment by tonypowa** [comment]
thanks for info @DonatoD  

> Even if I simply go to the browser tab, i get this error

i wasn't able to repro this one

however, since this issue might be related to the other one you referenced (https://github.com/grafana/grafana/issues/59453) i am sending it to the BI squad 

in the meantime, it could be helpful if you could look for logs (if there are any) 👍  :  
>Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors.

**Comment by zoltanbedi** [comment]
I'm going to close this one as this is not related to the other issue. We are going to investigate that one.

**Comment by DonatoD** [comment]
Sorry, Mybe you are missunderstanding each other, with your collegue. Why did you close this without any response/solution?

**Comment by DonatoD** [comment]
@zoltanbedi sorry, but ${__user.name} and ${__user.login} shouldn't return two differnet information? Name and Username, respectively?
![image](https://user-images.githubusercontent.com/51508670/222807604-4cbb1145-17b5-4ba8-b2fa-08191bd64af8.png)

**Comment by zoltanbedi** [comment]
@DonatoD the name property is not supported. Please open a feature request if you want to see this supported.

The only supported properties are: id, login and email.

**Comment by DonatoD** [comment]
OK, thanks for the clarification
