### ISSUE TITLE
v.windowPeriod not correctly expanded when used in grafana variable

### ISSUE THREAD

**Issue by MarcoPignati** [grafana/grafana#63713]
**What happened**:
In this minimal example, I want to create a variable in grafana that contains the current window period. I will compare this value with the same query run inside of a table panel.

**What you expected to happen**:
The content of the variable should always match the value inside the table panel.

**How to reproduce it (as minimally and precisely as possible)**:
I am using Grafana 9.3.6 and influxdb as datasource

Create a template variable in Grafana (screenshot below)
```sh
import "array"
array.from(rows: [{stringWindowPeriod: string(v: v.windowPeriod) }])
|> keep (columns:["stringWindowPeriod"])
```
![image](https://user-images.githubusercontent.com/35630931/221166930-611b34d6-f30d-469f-a858-0f8ea2d7b6b7.png)

Create a table panel with the same query
![image](https://user-images.githubusercontent.com/35630931/221167784-b5f152c1-b916-4780-8117-078fb6b1caf1.png)

As it can be seen below the values in the variable and in the table panel are different. The table panel is correct and it changes as expected.  The content of the variable is always to 1s, regardless of the chosen timeRange.
![image](https://user-images.githubusercontent.com/35630931/221166434-f2d7bf6d-10a8-4d86-8317-4553f67359d2.png)

**Anything else we need to know?**:
Variable is configured to refresh on time change.

I suspect that, while in the panel, the "panel size" is known and can be used for computing the v.windowPeriod, in the "variable menu", the "panel size" does not mean anything, so the developers hardcoded 1s. This is my wild guess.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: InfluxDB 
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: Chrome
- Grafana plugins: not used 
- Others:

**Comment by mellieA** [comment]
@MarcoPignati that's a good guess. Based on this PR for window period for alerting I think it's possible that you're right: 

https://github.com/grafana/grafana/pull/27463 

In the panel, the interval is calculated by the browser using the time period and number of data points. 

Can you share your use case or the problem you're trying to solve by setting a variable to the value of windowPeriod?

**Comment by MarcoPignati** [comment]
Thanks for your response. 
I am using InfluxDB as datasource. In short, I have a certain number of buckets where I place measurements with a certain resolution (say 20ms, 1s, 1min). Buckets have different retention policies. The one with higher resolution has obviously a shorter retention policy.

In grafana variable definition menu, via a flux query, I can already dynamically choose the bucket to use according to the timerange chosen by the user. I would like to get the information about the value of the v.windowPeriod (or $__interval) because this would allow me to further refine the selection of the bucket.

As an example, consider the case in which both the 1s and the 1min bucket contains data that can be used (they satisfy all the criteria e.g., timerange is fully contained in retention policy, etc). If I know, when defining the variable, that the windowPeriod is going to be 5m, I can safely say that the bucket to use is the one with 1m resolution. The objective is, for performance reasons, to use the bucket with less data that still fully contains all the data of interest. The variable "$bucket" will then be used for all the panels in the dashboard.  

- A workaround (what I have been using in the last years) is to assume a certain pixel value and from there compute an estimation of the windowPeriod and use that to refine the bucket choice (not the best as it is not scalable)
- Another idea would be to perform the bucket selection query inside of each single panel (rather than only once as variable). In that case the v.windowPeriod is available. However, I feel it is not great in terms of performance.

I hope I was clear. Any suggestion? Thanks!

**Comment by MarcoPignati** [comment]
Hello, do you have a feedback on this?
