### ISSUE TITLE
Loki: Implement `CheckHealth` method in backend

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#63726]
**What happened**:
Loki does not have a `CheckHealth` method in the backend code implemented. This makes calls to the `/health` endpoint not working. 

Ref:
- https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health
- https://grafana.com/tutorials/build-a-data-source-backend-plugin/#add-support-for-health-checks

**What you expected to happen**:

- `/api/datasources/uid/:uid/health` to return valid information

**How to reproduce it (as minimally and precisely as possible)**:
Call `/api/datasources/uid/:uid/health` with the `uid` set to a Loki ds.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.0

**Comment by svennergr** [comment]
@tharun208 Thank you! 🚀

Basically it should be a copy of this functionality https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/datasource.ts#L842-L872 in the Loki backend plugin code. Do you have any plans when/how long you would work on this?

**Comment by tharun208** [comment]
@svennergr I will come with a PR by tomorrow
