### ISSUE TITLE
Unable to query cloudwatch AWS/Logs dimension_values

### ISSUE THREAD

**Issue by jeekajoo** [grafana/grafana#6374]
- What Grafana version are you using?
3.1.1
- What datasource are you using?
cloudwatch
- What OS are you running grafana on?
official docker image
- What did you do?
trying to query cloudwatch dimension_values
- What was the expected result?
values returned
- What happened instead?
no values returned

![screenshot_2016-10-25_12-39-13](https://cloud.githubusercontent.com/assets/1882534/19682989/6b0c9f88-9ab0-11e6-92ed-bf6ea570080a.png)

Thanks

**Comment by torkelo** [comment]
please issue questions to the mailing list

**Comment by torkelo** [comment]
Oh, and please open chrome dev tools and look at the network requests being sent to AWS and the response, see anything wrong?

**Comment by jeekajoo** [comment]
My query was missing a metric name like `IncomingBytes` :
Working query: `dimension_values(eu-central-1,AWS/Logs,IncomingBytes,LogGroupName)`
