### ISSUE TITLE
Feature request: Enable customizable User-Agent header in outgoing data requests

### ISSUE THREAD

**Issue by zhichli** [grafana/grafana#63767]
Issue description is in discussion [Enable customizable User-Agent header in outgoing data requests (e.g. by make BuildVersion customizable in ini file) #58714](https://github.com/grafana/grafana/discussions/58714#discussioncomment-4351906)

**Comment by mellieA** [comment]
@marefr can you take a look at this feature request submitted by @zhichli issue and the related PR?
