### ISSUE TITLE
Canvas: Set flashing value mapping color

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#63761]
User suggested that it might be valuable to set a value mapping color that flashes (animated) to better indicate something is wrong with their system. This could be a feature that could be expanded to other visualization types to improve visibility of when things are going wrong / are off to users.

[From canvas github discussion](https://github.com/grafana/grafana/discussions/56835?sort=new#discussioncomment-5048647)

![220044875-82be2a51-9dea-48ae-b811-64b3465e1a92](https://user-images.githubusercontent.com/22381771/221276300-6441b58c-04a9-465a-b1ca-08dfa5b2b56f.gif)

**Comment by hexatronic-inone** [comment]
I add my voice, this is very much needed
