### ISSUE TITLE
Export to PNG

### ISSUE THREAD

**Issue by primoitt83** [grafana/grafana#6376]
* **I'm submitting a ...**
- [X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? CentOS 7
- What did you do? Trying to export a graph to PNG file
- What was the expected result? Same as dashboard
- What happened instead? No data on graph

Package fontconfig-2.10.95-7.el7.x86_64 is already installed

Here's my current dashboard

![grafana1](https://cloud.githubusercontent.com/assets/18406286/19687468/39bc5254-9aa4-11e6-90f5-a23603460e35.jpg)

And now my exported png file

![grafana2](https://cloud.githubusercontent.com/assets/18406286/19687503/5b73475e-9aa4-11e6-8517-af110e96f047.jpg)

Thanks in advance

**Comment by torkelo** [comment]
strange, 

try 

````
yum install fontconfig
yum install freetype*
yum install urw-fonts
```

**Comment by primoitt83** [comment]
@torkelo it's perfect now!!

Thanks a lot man!!

![new-dashboard1](https://cloud.githubusercontent.com/assets/18406286/19687842/e1652782-9aa5-11e6-9b45-ddd3f5f2f9b4.png)
