### ISSUE TITLE
Resolved message does not work

### ISSUE THREAD

**Issue by lipusik** [grafana/grafana#63778]
**What happened**:

In short: When i add custom "Summary and annotations" and populate a field using golang template (for example: "Alert. Present value: {{ $values.C0 }}" ), the resolved message isn't sent to Telegram-chat

**What you expected to happen**:

I was expecting to get firing/resolved message with the text "Present value 'value of metric'"

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Telegram chat, Telegram bot.
2. Create and set up contact point with the type "Telegram"
3. Add notification policies for this contact point
4. Create a panel with any metric (I used node_filesystem_free_bytes)
5. Create alert rule for this panel. 
 - You should add new summary with text "Present value: {{ $values.C0 }}" C0 - is value of yours metric.
![image](https://user-images.githubusercontent.com/77787762/221373304-3846831c-a6be-4183-aaea-21c2604499f9.png)
![image](https://user-images.githubusercontent.com/77787762/221373366-f1e2eced-0059-48bd-8f35-9ef6d782bf6e.png)
6. Make the alert state 'Normal'. Then take up disk space on the server whose metric you are using for the alert to fire. It can be RAM memory or something else.
7. Wait for a message with a firing signal, and then free up disk space (or something else). And you won't get a resolved message, but alert state will be "Normal".

**Anything else we need to know?**:

I can get resolved message if i use structure if-else (golang templates). For example: {{ if $values.C0 }}{{ $values.C0 }}{{ else }}no value{{ end }} 

**Environment**:
- Grafana version: Version 9.3.6
- Data source type & version: node_exporter, version 1.5.0 
- OS Grafana is installed on: ubuntu 22.04
- User OS & Browser: google chrome
- Grafana plugins: no plugins
- Others:

**Comment by mellieA** [comment]
@lipusik do you get any resolved notification? 

Just to be sure, have you checked in the telegram contact point that this box to disable the resolved notification is not checked: 

![Screenshot 2023-02-27 at 6 40 53 PM](https://user-images.githubusercontent.com/18175287/221730821-f2060698-52c8-4302-be9a-cceea943410f.png)

**Comment by lipusik** [comment]
@mellieA 
I get resolved messages when i don't use golang templates in the alert. Or when i use an if-else structure in custom field.
Yes, i checked "Notification settings". This checkbox is not checked

**Comment by armandgrillet** [comment]
The fact that it works with an if-else structure is definitely peculiar. Could you please enable [debug logs](https://grafana.com/docs/grafana/latest/cli/#enable-debug-logging) and send us what Grafana returns when sending such notifications? Thank you!

**Comment by lipusik** [comment]
@armandgrillet 

I changed log.level to debug and tryed alert with default template in "Contact points". And I wrote "Present value: {{ $values.B0 }}" in "Summary and annotations" in custom field "message". That I got in log:

logger=datasources rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.000748494Z level=debug msg="Querying for data source via SQL store" uid=a4eabe51-44d7-40cf-b9e2-dff71e660bdd orgId=1
logger=secrets.kvstore t=2023-06-25T09:26:15.001520939Z level=debug msg="got secret value" orgId=1 type=datasource namespace=Prometheus
logger=tsdb.prometheus rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.001602263Z level=debug msg="Sending query" start=2023-06-25T08:26:10Z end=2023-06-25T09:26:10Z step=15s query="up{instance=\"node-exporter:9100\", job=\"node\"}"
logger=expr rule_uid=sDwCLuu4z org_id=1 datasourceType=prometheus t=2023-06-25T09:26:15.002836745Z level=debug msg="expression datasource query (seriesSet)" query=A
logger=ngalert.scheduler rule_uid=sDwCLuu4z org_id=1 version=1 attempt=0 now=2023-06-25T09:26:10Z t=2023-06-25T09:26:15.002873184Z level=debug msg="Alert rule evaluated" results="[{Instance: State:Normal Error:<nil> Results:map[] Values:map[] EvaluatedAt:2023-06-25 09:26:10 +0000 UTC EvaluationDuration:5.002870168s EvaluationString:}]" duration=2.201706ms
logger=ngalert.state.manager rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.002902109Z level=debug msg="State manager processing evaluation results" resultCount=1
logger=ngalert.state.manager rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.003032776Z level=debug msg="Setting alert state"
logger=ngalert.state.manager rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.003041513Z level=debug msg="Saving alert states" count=1
logger=ngalert.state.historian rule_uid=sDwCLuu4z org_id=1 t=2023-06-25T09:26:15.011243179Z level=debug msg="Done saving alert annotation batch"
logger=ngalert.scheduler t=2023-06-25T09:26:20.000885531Z level=debug msg="No changes detected. Skip updating"

But the Resolve message did not arrive.




And I tried using grafana:9.5.2 and "Present value: {{ $values.B0 }}" in "Summary and annotations" in the custom field "message" and with default template in "Contact points". I got:

logger=datasources rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 t=2023-06-25T08:57:00.00102795Z level=debug msg="Querying for data source via SQL store" uid=a4eabe51-44d7-40cf-b9e2-dff71e660bdd orgId=1
logger=secrets.kvstore t=2023-06-25T08:57:00.001671063Z level=debug msg="got secret value" orgId=1 type=datasource namespace=Prometheus
logger=tsdb.prometheus rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 t=2023-06-25T08:57:00.001762076Z level=debug msg="Sending query" start=2023-06-25T08:52:00Z end=2023-06-25T08:57:00Z step=15s query="up{instance=\"node-exporter:9100\", job=\"node\"}"
logger=expr rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 datasourceType=prometheus queryRefId=A datasourceUid=a4eabe51-44d7-40cf-b9e2-dff71e660bdd datasourceVersion=2 t=2023-06-25T08:57:00.002901913Z level=debug msg="Data source queried" responseType="series set"
logger=ngalert.scheduler rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 version=1 fingerprint=6f5a718ab48ea3a6 attempt=0 now=2023-06-25T08:57:00Z t=2023-06-25T08:57:00.00295323Z level=debug msg="Alert rule evaluated" results="[{Instance: State:Normal Error:<nil> Results:map[] Values:map[] EvaluatedAt:2023-06-25 08:57:00 +0000 UTC EvaluationDuration:2.946928ms EvaluationString:}]" duration=1.989462ms
logger=ngalert.state.manager rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 t=2023-06-25T08:57:00.003001011Z level=debug msg="State manager processing evaluation results" resultCount=1
logger=ngalert.state.manager rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 instance= t=2023-06-25T08:57:00.003178649Z level=debug msg="Setting next state" handler=resultNormal
logger=ngalert.state.manager rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 instance= t=2023-06-25T08:57:00.00318966Z level=debug msg="Keeping state" state=Normal
logger=ngalert.state.manager rule_uid=f2d1d985-dc13-425d-94eb-22dd99b1185a org_id=1 t=2023-06-25T08:57:00.003199959Z level=debug msg="Saving alert states" count=1
logger=ngalert.state.manager t=2023-06-25T08:57:06.737615915Z level=debug msg="Recording state cache metrics" now=2023-06-25T08:57:06.737607058Z
logger=accesscontrol.service t=2023-06-25T08:57:08.964974123Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-1
logger=accesscontrol.service t=2023-06-25T08:57:08.965839308Z level=debug msg="cache permissions" key=rbac-permissions-1-user-1
logger=live t=2023-06-25T08:57:08.965997599Z level=debug msg="Publish API cmd" user=1 channel=grafana/dashboard/uid/c084f835-389f-4e7e-9775-24ca657bb4a3
logger=live t=2023-06-25T08:57:08.96601929Z level=debug msg="Found cached channel handler" channel=grafana/dashboard/uid/c084f835-389f-4e7e-9775-24ca657bb4a3
logger=accesscontrol.evaluator t=2023-06-25T08:57:08.966544298Z level=debug msg="matched scope" userscope=dashboards:* targetscope=dashboards:uid:c084f835-389f-4e7e-9775-24ca657bb4a3
logger=live t=2023-06-25T08:57:08.966614692Z level=debug msg="Publication successful" user=1 channel=grafana/dashboard/uid/c084f835-389f-4e7e-9775-24ca657bb4a3
logger=accesscontrol.service t=2023-06-25T08:57:09.211110686Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
logger=datasources t=2023-06-25T08:57:09.211247446Z level=debug msg="Querying for data source via SQL store" uid=a4eabe51-44d7-40cf-b9e2-dff71e660bdd orgId=1
logger=secrets.kvstore t=2023-06-25T08:57:09.211865221Z level=debug msg="got secret value" orgId=1 type=datasource namespace=Prometheus
logger=tsdb.prometheus t=2023-06-25T08:57:09.211958759Z level=debug msg="Sending resource query" URL="api/v1/label/__name__/values?start=1687682530&end=1687683430"
logger=accesscontrol.service t=2023-06-25T08:57:09.265286042Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
logger=accesscontrol.service t=2023-06-25T08:57:09.265620017Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
logger=accesscontrol.evaluator t=2023-06-25T08:57:09.266535858Z level=debug msg="matched scope" userscope=datasources:* targetscope=datasources:uid:a4eabe51-44d7-40cf-b9e2-dff71e660bdd
logger=accesscontrol.evaluator t=2023-06-25T08:57:09.266625168Z level=debug msg="matched scope" userscope=datasources:* targetscope=datasources:uid:a4eabe51-44d7-40cf-b9e2-dff71e660bdd
logger=accesscontrol.service t=2023-06-25T08:57:09.321495023Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
logger=accesscontrol.service t=2023-06-25T08:57:09.321511514Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
logger=secrets.kvstore t=2023-06-25T08:57:09.321670757Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=Prometheus
logger=secrets.kvstore t=2023-06-25T08:57:09.321716214Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=Prometheus
logger=tsdb.prometheus t=2023-06-25T08:57:09.32172995Z level=debug msg="Sending resource query" URL=api/v1/labels
logger=tsdb.prometheus t=2023-06-25T08:57:09.321785335Z level=debug msg="Sending resource query" URL=api/v1/metadata
logger=ngalert.scheduler t=2023-06-25T08:57:10.00070262Z level=debug msg="No changes detected. Skip updating"


And message contained Value of metric

**Resolved**

Value: [no value]
Labels:
 - alertname = Panel Title
 - grafana_folder = test
Annotations:
 - message = Present value: [no value]

In 9.5.2 we may not use if-else in templates, but I think that this behavior is still weird because I'm expecting to get the metrics value, not the string "[no value]"

**Comment by armandgrillet** [comment]
The original complaint is resolved, getting `[no value]` is a different problem.
