### ISSUE TITLE
Loki query builder: Support for disable operation action & state

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#63785]
### Discussed in https://github.com/grafana/grafana/discussions/52095

<div type='discussions-op-text'>

<sup>Originally posted by **ivanahuckova** July 12, 2022</sup>
Support for disable operation action & state in Loki and Prometheus query builder.</div>

**Comment by bohandley** [comment]
How will we be disabling operations? Can we have an example of what this would look like? Thank you!

**Comment by ivanahuckova** [comment]
Imagine I have this query `{agent="promtail"} |= "error"`. And operation would have disable operation button. And then if I disabled `Line contains` operation, I'd only have `{agent="promtail"}` query. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/30407135/221927076-17e5a4fc-89f8-4be6-8a87-95619aeaed9a.png">
