### ISSUE TITLE
Mixed data source: Changing data source row keeps stale results on the page

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#63781]
**Steps to reproduce**:

1. Open Explore
2. Select Elastic data souce
3. Run a Logs query
4. Add a new query. New empty query is run automatically and time series panel shows up.
5. Change the second query to Loki
6. Time series panel from the previous Elastic query remains on the screen

**Expected result**:

Stale result should be removed. Maybe we need to run all queries after data source changes? Note: Loki doesn't run the query automatically so Explore page is not refreshed after changing data source type, but is refreshed after running the query.

https://user-images.githubusercontent.com/745532/221434237-d144c047-d7c1-4077-86f1-f5a913bd937c.mov

**Comment by ifrost** [comment]
> Stale result should be removed. 

We probably cannot just remove stale results as all results are merged in multiple panels. Re-running queries is tricky as it may cause running the query twice if the editor runs them automatically on load (like Elastic). In theory, we could emulate remove+add behavior when changing the data source (we already re-run queries on delete), but that could be an overkill.

The current behavior is consistent with dashboards. However, in Dashboards it happens in edit mode so it's more expected that the user needs to run a query. 

I think we could also add some better UI to inform the user that queries changed since the last run and to get fresh results "Run button" needs to be run again. WDYT? (cc @diegoadams)

**Comment by Elfo404** [comment]
This is related to https://github.com/grafana/grafana/issues/51979, and probably another point in favor of not allowing plugins to run queries

**Comment by ifrost** [comment]
This is actually expected behavior as changing the data source changes the query and we do not automatically re-run all queries on change. Queries are re-run only when clicking Run button, removing a query or when called by the data source plugin.
