### ISSUE TITLE
Explore mysql failed to query bigint type

### ISSUE THREAD

**Issue by CodyGuo** [grafana/grafana#63782]
**What happened**:
Explore-Mysql query big int 15783287073902532070

![image](https://user-images.githubusercontent.com/10672966/221495958-829d330e-251c-43bc-a718-b59551db22bb.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/10672966/221496905-3d69740c-f2fe-4565-9803-2f81bb221623.png)

**How to reproduce it (as minimally and precisely as possible)**:
1.  create table log
```sql
create table `log` (
   `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
   `guid` bigint(20) unsigned NOT NULL COMMENT 'guid',
   PRIMARY KEY `pk_id`(`id`) USING BTREE
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```
2. insert into values
```sql
insert into `log`(guid) values(4964452252723547056);
insert into `log`(guid) values(15783287073902532070);
```

**Anything else we need to know?**:
math.MaxInt64 = 9223372036854775807 < 15783287073902532070
may be use big.Int type

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: mysql 5.7.37
- OS Grafana is installed on: centos 7.4
- User OS & Browser: windows 10 chrome
- Grafana plugins:
- Others:

**Comment by baldm0mma** [comment]
Yep; looks like the `ParseInt` functions is erroring due to the fact that it's designed parses signed integers - yours are unsigned. Also, the maximum signed integer - as you mentioned - is 9223372036854775807, and at least one is larger than said max. We probably need to call `ParseUint` to parse unsigned integers instead.

**Comment by gabor** [comment]
hi, i can verify this not working in grafana9.1.6, but it is working now in the newest grafana releases (10.1.x). closing the issue.

(if it did not fix your problem, just comment and we can reopen the issue).
