### ISSUE TITLE
The User profile Sessions, with responsive problems on the layout.

### ISSUE THREAD

**Issue by fl4viooliveira** [grafana/grafana#63797]
**What happened**:
![](https://media.giphy.com/media/7Pu8ftP2yYiPOHdR2c/giphy.gif)

As you can see on .gif, the Session table cross the layout if you reduce the screen or use it on mobile.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce, after the login, access `/profile`, and reduce the screen, you can notice that the session table not rearrange.
Same happens on: `https://<username>.grafana.net/profile`

**What you expected to happen**:
We expected that the table would change the orientation vertically on small screens.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v9.5.0-pre`
- Data source type & version: Develop and production
- OS Grafana is installed on: macOS 13.2.1
- User OS & Browser: macOS - Chrome & Android - Chrome
- Grafana plugins: none
- Others: none

**Comment by mellieA** [comment]
I wasn't able to reproduce this on a desktop browser, but I did see the issue when logging in on mobile with 9.4.1: 

![IMG_F95A222C84FE-1](https://user-images.githubusercontent.com/18175287/221748137-c4722a05-837e-42c4-8363-0b731b1901b2.jpeg)

**Comment by fl4viooliveira** [comment]
The issue happens mainly on mobile, Desktop browser, will happen if you reduce the size of the screen, you can check it on Chrome DevTools
