### ISSUE TITLE
interval template var not always used in ES query

### ISSUE THREAD

**Issue by jacobweber** [grafana/grafana#6379]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? CentOS 6.8
- What did you do? Create an $interval template variable, using the default settings. Then create a Graph with: group by Date Histogram, with interval $interval. Finally, select a value for $interval, like 1h.
- What was the expected result? Graph updates and uses the new interval value in its query.
- What happened instead? Graph updates, but the query always uses a 1m interval, e.g. `{"date_histogram":{"interval":"1m"...`. It works if you set the "group by" interval to "auto", and then set "Group by time interval: $interval". But it's unclear why this should be the case.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Pick another name for the interval variable, think the ES query build  is using and internal one with same name.

**Comment by jacobweber** [comment]
Thanks, that fixed it. It would probably be a good idea not to allow internal variables when naming a template variable. You may also want to update the documentation, since [some pages](http://docs.grafana.org/reference/templating/) use $interval as an example.
