### ISSUE TITLE
Docs: update pubdash docs after modal redesign

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#63798]
Update [public dashboards documentation](https://github.com/grafana/grafana/blob/main/docs/sources/dashboards/dashboard-public/index.md) to reflect modal redesign changes from [PR](https://github.com/grafana/grafana/pull/63211)

**Comment by juanicabanas** [comment]
Checking it with @imatwawana

**Comment by imatwawana** [comment]
> Checking it with @imatwawana

I've added suggestions to the docs file of the PR.
