### ISSUE TITLE
Legend wrongly abbreviates large numbers when focussing on individual metrics

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#6380]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? a4d2708 (version 3.1.1)
- What datasource are you using? Graphite

Standard view:
<img width="477" alt="screen shot 2016-10-25 at 18 57 41" src="https://cloud.githubusercontent.com/assets/156867/19697863/f61a3ee4-9ae4-11e6-9dc6-48aee977e341.png">

Viewing one metric by clicking its name in the legend: 
<img width="480" alt="screen shot 2016-10-25 at 18 57 50 1" src="https://cloud.githubusercontent.com/assets/156867/19697864/f61b7980-9ae4-11e6-93b5-86d031a897c9.png">

Then, suddenly the Left Y labels no longer make any sense.

I tried working around it by setting Decimals to 0 instead of auto, but it doesn't make much difference (other than moving the decimal separator one digit to the left)

**Comment by torkelo** [comment]
Since min and max of all series drawn change, and you have auto y-max and log base y axis it looks OK. Maybe the auto-y max value is a bit high. Do you want log base to change when only one series is enabled? 

I cant see wrongly abbreviated legend, it looks to multiply by 10 every step

**Comment by Krinkle** [comment]
@torkelo The min and max have not changed. In both pictures it goes from 0 to 10B.

For as long as I can remember, Grafana has never changed the graph rendering after selecting individual metrics when in log mode. The line stays exactly the same and continues to reserve the left over space where the other lines were drawn. Nothing moves. The only thing that changed recently is that the legend is now broken, which is what this bug report is about.

Why is it displaying "10.00000000B" instead of "10B"?

Live example: <https://grafana.wikimedia.org/dashboard/db/mysql-aggregated?panelId=8&fullscreen>

**Comment by torkelo** [comment]
it's just a decimals issue, when you only select one series the auto decimals algorithm is not great in 3.1, it has been improved in 4.0 / master so I think this issue is solved in master
