### ISSUE TITLE
Improve template/variable input dialog UI

### ISSUE THREAD

**Issue by cmclaughlin** [grafana/grafana#6381]
I'm submitting a Feature request..

Grafana version: v3.1.1
Datasource: Graphite
OS:  AWS Linux

When entering text into a template variable's input box, the width seems to be dynamic based on the width of the sting when the page loaded.  I'd like the ability to set that when creating/editing the variable definition.

Here's an example... I have this dashboard where `hosts` defaults to `*`.

![screen shot 2016-10-25 at 5 36 29 pm](https://cloud.githubusercontent.com/assets/1061109/19709282/297cf9f8-9ada-11e6-9238-630a796b720d.png)

When I type in a long hostname, the box is very small and I can't read what I'm typing.

![screen shot 2016-10-25 at 5 41 38 pm](https://cloud.githubusercontent.com/assets/1061109/19709317/61a19f5a-9ada-11e6-9e2d-7a87c395d41b.png)

If I reload the page, the text input box is bigger.

![screen shot 2016-10-25 at 5 43 13 pm](https://cloud.githubusercontent.com/assets/1061109/19709350/aa1b85ac-9ada-11e6-9210-0eb1a3fa2592.png)

When you edit a second time it would also be nice to leave the previously inputed value.  I like how the default is easily accessible here though - wouldn't want that to change. 

![screen shot 2016-10-25 at 5 45 09 pm](https://cloud.githubusercontent.com/assets/1061109/19709392/f7e081fc-9ada-11e6-804a-133bbe0b9586.png)

**Comment by torkelo** [comment]
This is fixed in master / v4 nightly build
