### ISSUE TITLE
So Far 7 Days ago on Panel

### ISSUE THREAD

**Issue by warezWally** [grafana/grafana#6382]
Hi,

I've tried copying the "This Day Last Week" Syntax to the time override on a panel. Yet this isnt working "now-7d/d" Is this something that can be done or am I requesting a new feature?

**Comment by torkelo** [comment]
think it's a new feature :)

**Comment by daniellee** [comment]
This seems to work now. Not sure which change solved this. There have been a few changes to the rangeutils class recently: https://github.com/grafana/grafana/blob/master/public/app/core/utils/rangeutil.ts
