### ISSUE TITLE
Bug: Library Panels - JSON Model breaks on panels with large or improperly escaped models

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#63834]
**What happened**:
Large panels stored in library element database sometime lead to issues when being retrieved due to JSON not marshalling properly.

<img src="https://user-images.githubusercontent.com/49911675/215732814-b7e9fc47-8996-41c9-b7fd-428504e68e3e.png" />

**What you expected to happen**:
- The "broken" panel should be rejected on save 
- alternatively when listing the panels the "broken" library panels are either skipped (not the best choice) or still displayed but marked as broken so that the user can still delete them

**How to reproduce it (as minimally and precisely as possible)**:
- Did not find the way to reproduce it from scratch, but take a look at linked customer escalation it has database dumps that you can use to reproduce

See https://github.com/grafana/support-escalations/issues/5153
**Environment**:
- Grafana version: tested on 9.4.1, main
- Data source type & version: https://grafana.com/grafana/plugins/volkovlabs-image-panel/, 
https://grafana.com/grafana/plugins/marcusolsson-static-datasource/

**Internal support issue*
- https://github.com/grafana/support-escalations/issues/4939

**Anything else we need to know? (ignore this part)**:
- Some customers have quite large panel models that outgrow the limits of what we set for [library_element.model](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/libraryelements.go#L21) when running on mysql. Currently we set `TEXT` but  their setup would require `MEDIUMTEXT`. Consider if `MEDIUMTEXT` by default would be a better choice. 
   - This is solved via https://github.com/grafana/grafana/pull/63856

**Comment by tobikris** [comment]
I have the same issue with a broken library panel. The suggested cause "panel JSON too large" matches my observations as I was adding details to a former working panel when it got broken.
Especially annoying is that you cannot even rollback the change as library panels are not saved as part of the history of the dashboard.

For reference, I am using this plugin: https://github.com/algenty/grafana-flowcharting.
