### ISSUE TITLE
Azure Resource Graph Query - Unable to save alerts without selecting minimum one subscription

### ISSUE THREAD

**Issue by audunsolemdal** [grafana/grafana#63831]
**What happened**:

When you create a dashboard, you have the option to press the X in the subscription dropdown in order to deselect any subscription. This is useful when you want to run Azure Resource Graph queries at the top level. Deselecting and pressing "save dashboard" works fine. 

When doing the same on alerts, a subscription is automatically readded, essentially making the alert useless or in need of mass duplications to work. (One per subscription)

**What you expected to happen**:

Able to store alerts without any default subscription being readded

**How to reproduce it (as minimally and precisely as possible)**:

Create new resource alert
Select type resource graph query from Azure Monitor
Add any query giving number values
Press X on the selected subscription
Save alert

![image](https://user-images.githubusercontent.com/21334768/221791683-63c2521e-b714-4266-862c-8374699e464c.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.6
- Data source type & version: Azure Monitor - assuming latest version
- OS Grafana is installed on: Helm chart on AKS cluster
- User OS & Browser: microsoft edge
- Grafana plugins: 
- Others:

**Comment by konrad147** [comment]
Legacy alerting is no longer supported. Please migrate to unified alerting

**Comment by audunsolemdal** [comment]
Forgive me, I upgraded to Grafana 9.4.7 now and created a new alert. The same issue occurs. Am I missing something obvious or am I not using unified alerting?

**Comment by timo-42** [comment]
The same issue occurs when using a graph query ad variable value selector.
It is fine for v9.5.0-ubuntu, but does not work in v9.5.1-ubuntu container image. In both cases I use a provisioning with a datasource.yaml and a Managed Identity on Azure.

Environment:
- Grafana version: v9.5.1
- Data source type & version: Azure Monitor - assuming latest version
- OS Grafana is installed on: AKS cluster with custom Deployment
- User OS & Browser: Firefox


Background: I use a graph query to fill a variable with subscriptions, which fulfill a certain criteria (example: contains "Microsoft.DBforPostgreSQL/flexibleServers")
