### ISSUE TITLE
SingleStat time of event

### ISSUE THREAD

**Issue by txisme** [grafana/grafana#6383]
* **I'm submitting a ...**
- [ ] Bug report
- [x ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? CentOS

I think it would be nice if SingleStat panel would show the time of when that max/min/wherever happened. Anyone agrees?

**Comment by torkelo** [comment]
is that not shown in the time picker for the dashboard?  (the time range for the dashboard)

**Comment by txisme** [comment]
the time picker of the dashboard shows the time range of when the max/min/whatever happened, but i meant the exact time that it happened. For example the time picker can say "Last 1 hour" but i want to know that the max shown in single stat occurred at 13:34:49.
