### ISSUE TITLE
Time Series Logarithmic View Tick issue when ticks for decades<= 1e-09 needed

### ISSUE THREAD

**Issue by rolf-epking** [grafana/grafana#63840]
![image](https://user-images.githubusercontent.com/16209467/221812854-991f5681-d282-4417-9160-70a2e1bd2be1.png)
![image](https://user-images.githubusercontent.com/16209467/221812930-0ce6c2c9-bb04-4c96-ad73-dc3ddd5cbcf3.png)
![image](https://user-images.githubusercontent.com/16209467/221820782-3f2d6594-5c8c-46eb-9f2a-7c0623f5b453.png)

When using logarithmic (base 10) y-axis and the axis has to print ticks, which are smaller than 1e-09 every subtick will get a label, which ends in an unreadable mess of tick labels.

I'm expecting a tick-label for every decade.

Another Issue: Min Max must be specified - Auto does not work and results in a range from 1e0 to 1e2

DataSource MySQL ([v9.3.6 (978237e7cb)]
OS: Rocky9
Browser: Chrome Version 110.0.5481.105  (64-Bit)

DataSample: 
| 2023-02-27 16:03:17 | 0.00000000003162278 |
| 2023-02-27 16:03:22 | 0.00000000003162278 |
| 2023-02-27 16:03:27 | 0.00000000003162278 |
| 2023-02-27 16:03:32 | 0.00000000003162278 |
| 2023-02-27 16:03:37 | 0.00000000003162278 |
| 2023-02-27 16:03:42 | 0.00000000003162278 |
| 2023-02-27 16:03:47 | 0.00000000003162278 |
| 2023-02-27 16:03:52 | 0.00000000003162278 |
| 2023-02-27 16:03:58 | 0.00000000003162278 |

![image](https://user-images.githubusercontent.com/16209467/221817645-a6cec8c3-37d8-4e48-bc88-5eff36afa042.png)

**Comment by briend** [comment]
We're still seeing this in Grafana `9.4.7`.  Having just the `0 B/s` mark is not helpful.  If we resize the panels a bit taller then it is fine, but we'd rather keep the real estate.

![image](https://user-images.githubusercontent.com/6015639/235252302-1dc40995-cf35-4af2-a4a5-7958ecccbecb.png)

**Comment by leeoniya** [comment]
this is now fixed upstream in uPlot, so will land with the next dep update in a week or two. maybe in time for 10.0, but could be in a follow-up 10.0.x release.

**Comment by rolf-epking** [comment]
In version 10.1.5 the error is still present

**Comment by leeoniya** [comment]
@rolf-epking can you try a nightly build?

https://grafana.com/grafana/download/nightly?edition=oss

**Comment by rolf-epking** [comment]
In the nightly it seems to work!

![image](https://github.com/grafana/grafana/assets/16209467/89df4723-2a20-41ea-bc24-e108bb5fd2f6)

**Comment by leeoniya** [comment]
:+1:
