### ISSUE TITLE
Max from constant and series

### ISSUE THREAD

**Issue by Stas0n** [grafana/grafana#6384]
Hi,

is it possible to show maximum from constant and series on graph?
Sometimes one series can has a negative values. Is it possible to border it with zero constant to make it non-negative? 

I mean smth like this: maxSeries(series, 0)

**Comment by txisme** [comment]
You can show the maximum of the data plotted in a graph if you edit the graph and go to Legend tab. Then check Options->Show and Values-> Max

![image](https://cloud.githubusercontent.com/assets/10253258/19721374/da4932e4-9b69-11e6-8bae-fe235b8365c1.png)

The value will appear right under the graph, or if you want it can appear to the right (Check Options->To the right)

-----------------------------------------------------------------------------------------------------

As for the negative values, i am not sure what you mean, but i think the easiest way would be to to an absolute function before going to grafana.

**Comment by Stas0n** [comment]
ok, thanks
