### ISSUE TITLE
granafa3.1+elasticsearch2.0+logstash2.3 the time filed is which format 

### ISSUE THREAD

**Issue by yubei61200** [grafana/grafana#6386]
* **I'm submitting a bug**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I post data to elasticsearch2.0 with logstash2.3, the data contains time and @timestamp, when I show the data in grafana with garph panel, the chart only show @timestamp, when I configure time filed with time in database source, it still not work.
I want to know if my time's format is wrong, I use timestamp like "1477238400".

**Comment by torkelo** [comment]
please issue questions to the mailing list https://groups.io/g/grafana

make sure your index mapping is correct (and the @timestamp field is mapped as date)

**Comment by yubei61200** [comment]
yes, I already mapped time as date, but still not work.
