### ISSUE TITLE
Wrong Role for new user

### ISSUE THREAD

**Issue by MarcusCaepio** [grafana/grafana#6387]
I'm submitting a Bug/Question
ii  grafana                              3.1.1-1470047149                    amd64        Grafana
ii  influxdb                             1.0.2-1                             amd64        Distributed time-series database.
Ubuntu 16.04.1 LTS \n \l

Hi all,

I'm just starting with grafana and testing it.
So I have an Organisation where user can login via Active directory.
When a new user logs in, I want that he always get assigned to the fedault oragnisation (works) as Role Viewer (works not).
New Users are always assigned as admins, although I have the config set to:
```
[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Default role new users will be automatically assigned (if disabled above is set to true)
auto_assign_org_role = Viewer

# Background text for the user field on the login page
login_hint = Active Directory User + Password

# Default UI theme ("dark" or "light")
;default_theme = dark
```

I have imported the Icinga2 Dashboard and I want that every user has this dashboard as default and he shall not edit it. How do I have to realise this?

**Comment by torkelo** [comment]
if your using LDAP you assign role in the ldap configi

**Comment by MarcusCaepio** [comment]
And how?
A little help would be nice...

**Comment by torkelo** [comment]
Check the docs page for ldap, the member mapping where you map ldap group to grafana org role

**Comment by MarcusCaepio** [comment]
Now I got it. Typically Newbie mistake. Thanks a lot!
