### ISSUE TITLE
Folder service registry

### ISSUE THREAD

**Issue by zserge** [grafana/grafana#63872]
Related to #56880 (Nested Folders)

# Folder Service Registry

Folders is one of a few entity types that may contain other entities.

Nested Folders are assumed to contain other folders, dashboards, playlists, alerts, library elements.

From the UX perspective it is also required to count such contained items, to list them, to evaluate their permissions and to remove them recursively.

## How it currently works

Entity kinds are hardcoded. And not only in the Folder service. Current Folder service literally injects the Dashboard service and calls its methods directly. NGAlert service injects the Folder service and calls it directly in its turn. There is no easy way to count all objects within a folder or to delete them.

Pros: somehow this seems to work, as long as no changes required we could all have a day off.
Cons: to support another entity kind that may reside in the folders we would have to update lots of code in various packages. So -- no day off. Testing it all is yet another type of pain.

## Some boring theory

In a broader sense, we need to track relationships between entity kinds. The two most common relationship types are:

* Association (parent/child)
* Reference (non-parent/child)

Folders is an example of association (and it seems to be the only association relationship in Grafana, apart from maybe Orgs). Playlists, Library Elements, Tags, Stars are all examples of the second relationship type (they refer to dashboards).

While it can be tempting to generalise these two relation types, they remain quite different. Associated child can not exist if its parent gets removed. Child permissions strongly depend on the parent access rules. A reference relationship on the other hand does not have such implications and is much "weaker": broken references can exist just fine in most cases.

Thus, instead of solving two problems with a single solution, let's focus on Association problem first and limit its scope to the Folder service specifically. Let's keep Reference manager/registry for later.

## A registry of child services

Make some generic `ItemService` interface and let Folder service keep a registry of them. Folder service would call other services using this interface to get certain information about the contained items.

```go
type ItemService interface {
    Count(c context.Context, orgID int64, UID string) (int64, error)
    Delete(c context.Context, orgID int64, UID string) error
    List(c context.Context, orgID int64, UID string) ([]string, error)
    Kind() string
    ...
}
```

Here `UID` is a Folder UID. It is assumed that one service handles one kind of entities.

Pros: easy to add new item kinds, very easy to implement. Allows separation of storage between the folder service and the child/item services.

Cons: without caching it might be slow (every call requires an additional query that can not be JOINed with the folder SQL query). Not reusable for other relationship types.

## A registry of child UIDs

Make a reusable registry service that would keep relationships between the objects?

```
+-----+---------+--------------+
| uid | rel_uid |   rel_type   |
+-----+---------+--------------+
|  a  |    b    | contains     |
|  b  |    a    | is_contained |
|  b  |    c    | reference    |
...
```

Here we don't expose an interface with the specific methods, but rather duplicate information about UIDs/GRNs of the related entities in the "parent" service.

Folder service could use this to store UIDs of dashboards, alerts, playlists etc and count/list/delete them in its own manner. Playlist service could use this to handle dashboard removals. Library elements + dashboards could also use this to track the relationships/references between the entities.

Pros: flexible, fast and not too hard to implement. Seems to be reusable.
Cons: might be an overkill and causes data duplication -- how to keep such data in sync?

## Conclusion

Go with a registry of interfaces for Folder service, see how that works in practice, how easy to is to introduce new "folder items" (i.e. playlists, library elements). If all goes well - see if we can make it a reusable pattern.

```[tasklist]

- [x] What interface is suffucient for folder item services?
- [x] Let dashboard service implement it
- [x] Should folder service implement it, too?
- [ ] Fix deletion via service registry
- [ ] Fix counting via service registry
- [ ] Measure, benchmark, decide
```

**Comment by suntala** [comment]
Candidate for registry service?: 

> If a dashboard panel is using a datasource, and then that datasource is deleted, there is no way to automatically clean that up, right?

([source](https://raintank-corp.slack.com/archives/C03PR38JWBA/p1680075647730969))

**Comment by suntala** [comment]
We may want to add methods for bulk actions. For example bulk deletion.

**Comment by suntala** [comment]
Future improvement/todo. Remove "user" from the signature of DeleteInFolder in the folder RegistryService

https://github.com/grafana/grafana/pull/69149/files#diff-21abf435d33e5475945c8b5b71c3016c56aab9d246be3f45a4ce3050cbd12622R284-R289

**Comment by suntala** [comment]
The task list isn't showing up in the description for some reason:

- [x] What interface is suffucient for folder item services?
- [x] Let dashboard service implement it
- [x] Should folder service implement it, too?
- [ ] Fix deletion via service registry: : https://github.com/grafana/grafana-backend-platform-squad/issues/32
- [ ] Fix counting via service registry
- [ ] Measure, benchmark, decide
