### ISSUE TITLE
Error: ✗ contact points: could not find object using provided id and hash when provisioning Microsoft Teams contact point

### ISSUE THREAD

**Issue by SamuraiPrinciple** [grafana/grafana#63894]
**What happened**:

Grafana fails to start with the following error:

2023-02-28 17:35:09 Error: ✗ contact points: could not find object using provided id and hash

**What you expected to happen**:

Grafana to start successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Provision Microsoft Teams notification point using files, for example:

apiVersion: 1

contactPoints:
  - orgId: 1
    name: Microsoft Teams
    receivers:
      - uid: Microsoft Teams
        name: Microsoft Teams
        type: teams
        settings:
          url: https://xxx.webhook.office.com
          title: |
            {{ template "default.title" . }}
          sectiontitle: ''
          message: |
            {{ template "default.message" . }}

**Anything else we need to know?**:

When new contact point is provisioned Grafana starts successfully, but it cannot be restarted because it fails to update (because it cannot find it by hash). 9.3.6 does not have this issue. webhook contact point *can* be provisioned (haven't tried other, we only use these two).

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: Not relevant
- OS Grafana is installed on: Linux
- User OS & Browser: Not relevant
- Grafana plugins: standard
- Others:

**Comment by jakubvojacek** [comment]
we are also experiencing this issue while updating mute timing via the provisioning API. What worked in older grafana throws a weird error in 9.4.1.

**Comment by mellieA** [comment]
@SamuraiPrinciple have you tested whether the contact point works as expected if you configure it in the UI? I'm wondering if this is related to provisioning only or both?

**Comment by SamuraiPrinciple** [comment]
Hi mellieA,

I have just tried adding a Microsoft Teams contact point from the UI and that seems to work (I could stop and start Grafana container without issues).

**Comment by alexmobo** [comment]
Hello! We have a solution at https://github.com/grafana/grafana/pull/64070 merged. If you have a database backup from before the upgrade you might consider downgrading to last 9.3 version, otherwise 9.4.4 will contain the bugfix.

**Comment by SamuraiPrinciple** [comment]
Wonderful, thank you.
