### ISSUE TITLE
Chore: Update Dashboards banner

### ISSUE THREAD

**Issue by GrafanaWriter** [grafana/grafana#63897]
On the page https://github.com/grafana/grafana/blob/main/docs/sources/dashboards/_index.md which publishes as https://grafana.com/docs/grafana/latest/dashboards/ we have a banner pointing to our prebuilt dashboards. 

Because the banner is being managed by our CTA tracking tool, it is not being indexed for SEO purposes. 

**What is the chore?**:
Update the markdown file to use a manual CTA, which is evergreen. 

**Is there anything else we need to know?**:
The structure of the banner should look like this:

**Note:** Looking for prebuilt Grafana dashboards? [Check out our full library of dashboards and more→](https://grafana.com/grafana/dashboards/?pg=docs-grafana-latest-dashboards)

**Comment by AnneB-SEO2** [comment]
Hi @Eve832 & @imatwawana This is closed but the banned hasn't been updated - it's still the old messaging. Does it need to be reopened?

**Comment by imatwawana** [comment]
> Hi @Eve832 & @imatwawana This is closed but the banned hasn't been updated - it's still the old messaging. Does it need to be reopened?

It was closed automatically when my PR was merged. Reopening until the automated banner is removed.

**Comment by imatwawana** [comment]
> @AnneB-SEO2 , it was my understanding that you would kick off the process of getting the automated banner removed after we added the manual one. If that's not the case, should we ping @nate-walters-grafana ?

@Eve832 - There are several notes added on the PR. @AnneB-SEO2 pinged @meganmilan on there.

**Comment by AnneB-SEO2** [comment]
@Eve832 we were under the impression that the banned had been moved to Adobe Target, but after some digging we found that it had not

**Comment by GrafanaWriter** [comment]
Fixed with [#64072](https://github.com/grafana/grafana/pull/64072)
