### ISSUE TITLE
Alert created in another folder

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#63899]
**What happened**:
After having migrated from Grafana v8 to v9, my alert rules got sorted in a new `General Alerting` folder, whil my dashboard lie in the `General` folder.

Trying to change the namespace from the group containing my rules back to `General` yields the following error:
> Failed to update namespace / group: folder not found

**What you expected to happen**:
Have alert rules being sorted where the dashboard are.

**How to reproduce it (as minimally and precisely as possible)**:
Try to set alerts up from dashboard sorted in the `General` folder

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.6
- Data source type & version: Compiled from v9.3.6 tag on GitHub
- OS Grafana is installed on: Debian-like
- User OS & Browser: Relevant?
- Grafana plugins: `Pie Chart (old)`, probably resulting from uogrades
- Others:

**Comment by mellieA** [comment]
@Berbe which version of grafana 8 did you upgrade from? 
Were you using unified alerting on version 8? I think this is the result of migrating from legacy alerting to unified alerting. 

The General folder should not be visible to hold alerts - there is a PR to disable it from the list here https://github.com/grafana/grafana/pull/61277 

After the migration from Legacy Alerting to Unified Alerting If there are no dashboard permissions and the dashboard is under the General folder, then the rule is linked to the General Alerting folder, and the rule inherits the default permissions.

[Alert migration differences & limitations](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/migrating-legacy-alerts/#differences-and-limitations )
