### ISSUE TITLE
Import dashboard bug

### ISSUE THREAD

**Issue by jchauncey** [grafana/grafana#6390]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)
- Version - grafana_3.1.0-1468321182_amd64.deb
- Datasource - Influx
- OS - Ubuntu

Repro Steps:
- Click import dashboard
- Select a file
- You will be prompted for a name
- Do not fill in the name text field instead just hit save and close
- You will get a 404 page but a blank dashboard is created which you cannot delete because it 404s.

**Comment by utkarshcmu** [comment]
This bug creates a dashboard with no name and the only way to delete the dashboard is the to go to the db and delete the entry from the table.
