### ISSUE TITLE
Query editor is missing for Prometheus datasource

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#63904]
I´ve wait since end of january for a fix of this problem:
https://github.com/grafana/grafana/issues/62414 
today I installed 9.4.1 and there is no fix.
same problem: query editor is missing.
Do I have to create all my dashboards again from zero ?
:-( 

**How to reproduce it**

1. Import the following dashboard
[Elektro 1-1677653074995.json.txt](https://github.com/grafana/grafana/files/10857860/Elektro.1-1677653074995.json.txt)
2. Try to edit the chart
3. The editor doesn't appear

![Captura de pantalla 2023-03-01 a las 17 02 08](https://user-images.githubusercontent.com/5699976/222194431-26429824-76b1-4fad-ad0a-4de57f2e4962.png)

**Comment by mellieA** [comment]
@Becker884 Can you share a screenshot or video of what you're seeing with 9.41? I tried this out on play.grafana.net (9.4.1) and it seems to work there using this dashboard json that previously reproduced the issue: 


```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-azure-monitor-datasource",
        "uid": "${query0}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-azure-monitor-datasource",
            "uid": "${query0}"
          },
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "revision": 1,
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "Azure Monitor",
          "value": "Azure Monitor"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "query0",
        "options": [],
        "query": "grafana-azure-monitor-datasource",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Test Datasource Variable",
  "version": 0,
  "weekStart": ""
}
```
![Screenshot 2023-02-28 at 5 25 24 PM](https://user-images.githubusercontent.com/18175287/222013977-6520f909-3fdb-4df0-8c63-15389cf7e424.png)

**Comment by Becker884** [comment]
Screen record:
https://user-images.githubusercontent.com/81651521/222063866-1ce82b7d-45d6-4618-a69a-c09ea793c84e.mp4

"time" is also broken, but I can fix this by myself. (Time -> time)

you see all old queries are missing in the editor.

in "Batterie" you can see 3 queries which are shown -> I recently added these (at 9.3.6)
all old querys are missing!

here my dashboard "Elektro" for you to test: 
[Elektro 1-1677653074995.json.txt](https://github.com/grafana/grafana/files/10857860/Elektro.1-1677653074995.json.txt)

**Comment by ivanortegaalba** [comment]
Hi @Becker884, here Ivan.

I'm debugging the error.
It seems the query editor state has a different datasource UID than the UID coming from props. So the component keeps waiting for the correct datasource to be fetched. 
The one in the state is the correct one, the one coming from props is not correct. 

**There is a workaround for this**, select again the datasource in the picker, and the editor appears again. Obviously not ideal, but just for you to keep moving.

I'll try to reproduce this, deterministically, and see why we receive from props a different datasource UID.

**Comment by Vimao** [comment]
I noticed the same thing happening in the query editor for alert rules that were based on Elasticsearch data source, but it was seemingly random and the workaround with reselecting the data source worked there too

**Comment by Becker884** [comment]
thx, this are the changes:
![grafik](https://user-images.githubusercontent.com/81651521/222269585-9530e00e-bb7c-4e89-b304-65ac74fd2f1c.png)

**Comment by ivanortegaalba** [comment]
@Becker884 is there any chance you've changed recently your data sources? And the panels were pointing to a data source that doesn't exist anymore?

**Comment by ivanortegaalba** [comment]
This is solved with https://github.com/grafana/grafana/pull/62617
