### ISSUE TITLE
isolation_level config for Mysql 8 connections doesn't work

### ISSUE THREAD

**Issue by rverenich** [grafana/grafana#63916]
**What happened**:
grafana.ini
```
[database]
type = mysql
isolation_level = READ-COMMITTED
```
https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L125-L129

doesn't work for Mysql 8.0.x connections
```
Unknown system variable 'tx_isolation'
```

**What you expected to happen**:
connection with config above works

**How to reproduce it (as minimally and precisely as possible)**:
setup mysql DB 8.0.x
add in grafana.ini 
```
[database]
type = mysql
...
isolation_level = READ-COMMITTED
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.8

**Comment by mellieA** [comment]
@rverenich do you see a difference if you put the value in double quotes `isolation_level = "READ-COMMITTED"`

**Comment by rverenich** [comment]
nope, the roots are here : https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/sqlstore.go#L296-L299
