### ISSUE TITLE
Issue with unified_alerting.execute_alerts setting

### ISSUE THREAD

**Issue by SaiUmeshKumar** [grafana/grafana#63911]
**What happened**:
I am trying to setup grafana with separate deployment for alerting. One deployment will have  `unified_alerting.execute_alerts` as `false` (this is the one i am exposing as a service - service pods) and one with this setting to be `true` (this will not be exposed as service - alerting pod). Both are connecting to same postgres database. I am able to get the alert using this deployment pattern from the alerting pod. But if i open the Ui via service pods, the state is not updated. I have a similar setup and it is working for 7.x version

**What you expected to happen**:
Opening UI via service pods should be showing the state change for the alert.

**How to reproduce it (as minimally and precisely as possible)**:
Have two deployments, one with `unified_alerting.execute_alerts` as `false` and one with `true`. Create an alert and once it's triggered, check the UI via deployment with `unified_alerting.execute_alerts` as `false`

**Anything else we need to know?**:

**Environment**: Kubernetes
- Grafana version: 9.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: 
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@SaiUmeshKumar the supported way to enable high availability alerting is documented here: https://grafana.com/docs/grafana/next/alerting/set-up/configure-high-availability/ 

If you wanted to set up the pods to use an external alertmanager, that configuration has also changed and is documented here:  https://grafana.com/docs/grafana/next/alerting/set-up/configure-alertmanager/
