### ISSUE TITLE
Support for Amazon application load balancers

### ISSUE THREAD

**Issue by sherl0k** [grafana/grafana#6391]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708) 
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
CentOS 6
- What did you do?
Add an application load balancer to query metrics from
- What was the expected result?
Application load balancers are not listed.
- What happened instead?
I only get classic load balancers to retrieve metrics from.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html#load-balancer-metrics-alb references the AWS/ApplicationELB namespace, which is not listed in the dropdown. Specifying it manually does not work either.

**Comment by mtanda** [comment]
Hi,
Next Grafana version will support it.
https://github.com/grafana/grafana/pull/5802

**Comment by sherl0k** [comment]
fantastic, thank you!
