### ISSUE TITLE
All alerts rule paused after upgrading to 9.4.1

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#63927]
**What happened**:
After upgrade to 9.4.1 which introduced the pause evaluation feature all existing alert rules are in status paused. On large environments it is an extreme chore, and less cautious user might not even notice that the alert rules are paused
**What you expected to happen**:
Alert rules are not paused by default after upgrade
**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from 9.3.0 to 9.4.1 with alert rules existing in Grafana
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: Not important
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Unimportant
- Grafana plugins: Unimportant
- Others:

**Comment by armandgrillet** [comment]
@Vimao Can you tell us more about your alerts in 9.3.0? Were they migrated from legacy alerting earlier? Trying to understand where this could be coming from.

**Comment by Vimao** [comment]
We actually migrated to NGAlerting while it was still an opt-in feature, and kept up-to-date constantly.  We have a mix of rules that were migrated when the NGAlerting was introduced in 8.0, and a mix of rules that were created once NGAlerting was implemented. 

One specific thing we have is that each of our alert rules has it's own group. This is because we misunderstood the alert group functionality at the beginning, and just went with how we did it in the beginning (we are chaning this soon though ;) ). So we have more than 300 alert groups, some of them were migrated, some of them are fresh.

We also use 3 datasources: Elasticsearch, Cloudwatch and Prometheus, if that might be of any help.

**Comment by armandgrillet** [comment]
@Vimao Thank you for these details! The alerting team will take a look and post an update this week.

**Comment by grobinson-grafana** [comment]
Hi! 👋 We have confirmed that this bug affects PostgreSQL. MySQL/MariaDB and sqlite3 are not affected. You can run the following SQL to fix the database while we fix this in Grafana:

```
ALTER TABLE alert_rule ALTER COLUMN is_paused SET DEFAULT false;
ALTER TABLE alert_rule_version ALTER COLUMN is_paused SET DEFAULT false;
UPDATE alert_rule SET is_paused = false;
UPDATE alert_rule_version SET is_paused = false;
```
