### ISSUE TITLE
Previously exsisting custum InfluxDB queries don't show selected columns after upgrade 9.3.8 -> 9.4.1

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#63923]
**What happened**:

When upgrading from 9.3.8 to 9.4.1 previously exsisting custum InfluxDB queries don't show selected columns (mean, last, ..).
When switching to query editor mode and back to raw query mode, then the table shows the column.

If creating new query the issue is not present (because we go through query editor mode first).

P.S. Once the column is shown, it shows "mean" (because it was selected in query editor) even tho the data is actually "last" as written in custom query.

Panel: Table
Format as: Table

Additional info: this issue was not present when upgrading previous versions, for instance upgrading 9.3.6 -> 9.3.8.

GIF:
![Grafana](https://user-images.githubusercontent.com/66313770/222118440-01c50044-884f-45c3-b59c-c005ef3b36b6.gif)

**Comment by auwaerter** [comment]
Not sure if smh related, but i'm also having [issues](https://github.com/grafana/helm-charts/issues/2243) with the provisioning of InfluxDB since grafana 9.4.1

**Comment by jdmaloney** [comment]
I'm seeing similar issues as @edin008 with my table panels that query InfluxDB.  I'm only getting the first column returned and it's being named "mean" even thought it's not a mean (just a normal "select $col_1_name,$col_2_name....").

**Comment by mellieA** [comment]
@jdmaloney @auwaerter @edin008 there's another similar issue I've assigned to our dev squad to take a look at. I'm going to close this one to make sure we can gather all of the context of the issue in one place. 

Please follow along and contribute to the conversation in https://github.com/grafana/grafana/issues/63842
