### ISSUE TITLE
Error messages since instalation of 9.4.1 (upgrade from 9.3.6)

### ISSUE THREAD

**Issue by jpgpi250** [grafana/grafana#63920]
installed (updated) grafana from 9.3.6 to [v9.4.1 (fd67ab151d)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) → success

wget https://dl.grafana.com/oss/release/grafana_9.4.1_armhf.deb
sudo dpkg -i grafana_9.4.1_armhf.deb
following error messages appeared after a while (repeats every 15 min), I haven’t got any grafana alerts defined:

logger=alertmanager org=1 t=2023-03-01T09:21:17.76653514+01:00 level=error msg="Running maintenance failed" err="context canceled"
logger=alertmanager org=1 t=2023-03-01T09:36:17.766832842+01:00 level=error msg="Running maintenance failed" err="context canceled"
noticed (webmin monitoring) change in running processes:

which grafana-server says:
/usr/sbin/grafana-server
systemd sevice file says:
ExecStart=/usr/share/grafana/bin/grafana server                                     \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}
webmin running processes says:
  29704	grafana	43 minutes ago	/usr/share/grafana/bin/grafana server --config=/etc/grafana/grafana.ini --pidfil ...
      29819	grafana	42 minutes ago	/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_arm
      29828	grafana	42 minutes ago	/var/lib/grafana/plugins/redis-datasource/redis

see also https://community.grafana.com/t/error-messages-since-instalation-of-9-4-1/82863

**Comment by mellieA** [comment]
@jpgpi250 it looks like there were some changes made to the alertmanager recently that could be creating this new log entry. Is everything working as expected? 

I'm curious if you create an alert if this will clear? Reading the code the maintenance cycle looks like it checks for alert notifications and silences.

**Comment by jpgpi250** [comment]
> I'm curious if you create an alert if this will clear?

I haven’t got any grafana alerts defined

I searched, found and followed [these](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/disable-alerting/) instructions, the error message no longer appears.

**Comment by tonypowa** [comment]
@jpgpi250 deactivating alerting is perhaps a bit of a hard fix 😅 

 i just have been informed that this is actually a [known issue](https://community.grafana.com/t/running-maintenance-failed-of-alertmanager/81268/4) that gets fixed by upgrading to 9.4.3
