### ISSUE TITLE
Grafana 9.4 proxy issue (Cloudflare)

### ISSUE THREAD

**Issue by hyperbart** [grafana/grafana#63934]
**What happened**:
Running a simple Grafana instane in a Docker on Ubuntu 22.04
Protected by Cloudflare Tunnel
Upgraded grafana from 9.3 to 9.4
Grafana doesn't load anymore, shows an error page:
"If you're seeing this Grafana has failed to load its application files"

**What you expected to happen**:
Grafana to load

It does load via the direct IP+port internally, so I understand one would think that Cloudflare is the issue, however the upgrade is the thing that breaks it, so I am looking for the breaking change and how to reconfigure Cloudflare if needed.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy standard cloudflare tunnel
Deploy docker container for grafana 9.4

If i revert the image to 9.3 it works perfectly.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4
- Data source type & version: 
- OS Grafana is installed on: Ubuntu LTS 22.04
- User OS & Browser: Firefox  110
- Grafana plugins: none
- Others:

**Comment by spkis** [comment]
I can confirm this.
It happens with 9.4.0-Beta Release and also the 9.4.1 release (this looks for me like a "broken" versioning that the jump happened to 9.4.1).
This is definitely an issue of the upgrade - I did run into this issue on multiple machines. 
I had to roll back to 9.3.6 otherwise it was not possible to use Grafana with cloudflare.

**Comment by trim21** [comment]
I have the same problme, is there any workaround currently?

**Comment by JustArchi** [comment]
> I have the same problme, is there any workaround currently?

I've added a page rule with:

> Cache Level: Bypass, Disable Performance

Did the trick. Definitely a workaround, but at least it works.

**Comment by hyperbart** [comment]
> I have the same problme, is there any workaround currently?

Downgrade for a while also works.

**Comment by trim21** [comment]
> > I have the same problme, is there any workaround currently?
> 
> Downgrade for a while also works.

yes 8.5.21 works

**Comment by trim21** [comment]
> > I have the same problme, is there any workaround currently?
> 
> I've added a page rule with:
> 
> > Cache Level: Bypass, Disable Performance
> 
> Did the trick. Definitely a workaround, but at least it works. You might need CTRL+F5 afterwards.

another solution is to disable JavaScript Auto Minify

**Comment by krzd7** [comment]
I'm experiencing the same issue after migrating to v9.4.1

**Comment by spkis** [comment]
The 9.4.2 release in combination with the page rules, still doesn't work for me...

**Comment by spkis** [comment]
@trim21 
I have set the page rules "cache level bypass, disable performance" but still it doesn't work. I will try it again with a demo installation - maybe it's just a cloudflare delay until the settings get active.

**Comment by trim21** [comment]
> @trim21 I have set the page rules "cache level bypass, disable performance" but still it doesn't work. I will try it again with a demo installation - maybe it's just a cloudflare delay until the settings get active.

try purge cache

**Comment by spkis** [comment]
> > @trim21 I have set the page rules "cache level bypass, disable performance" but still it doesn't work. I will try it again with a demo installation - maybe it's just a cloudflare delay until the settings get active.
> 
> try purge (cloudflare and browser) cache, grafana response js files with 1y cache-control header

Nope - still doesn't work using Grafana 9.4.2. I purged cache multiple times.

**Comment by spkis** [comment]
> > Nope - still doesn't work using Grafana 9.4.2. I purged cache multiple times.
> 
> I just disable javascript auto minify and it works...

The setting did help - even 9.4.3 doesn't fix it without turning off the mimfy setting in cloudflare and purging cache.

**Comment by trim21** [comment]
> The setting did help - even 9.4.3 doesn't fix it without turning off the mimfy setting in cloudflare and purging cache.

And for the second time, [my PR](https://github.com/grafana/grafana/pull/63980) is not merged yet

**Comment by spkis** [comment]
Relax Jesus - it looked like it would come:
![image](https://user-images.githubusercontent.com/114989348/222679042-6625f5db-a2a4-45cc-887d-59d706d17844.png)
But seems it still has open merge issues.

**Comment by hyperbart** [comment]
I can confirm that the following actions result in a working Grafana 9.4.2 installation with CloudFlare protection again:

1. Deploy latest image
2. Go to CF dashboard, https://dash.cloudflare.com, go to Speed, Optimization, uncheck "JavaScript" in Minify section
3. Go to the dashboard of CF again, open your site/domain, click on Caching, Configuration, perform a Complete Purge
4. Open Firefox and clear all data https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox for the Grafana site you are working with

I will leave the debate on "where this should be fixed" to the SME's.

**Comment by TheRealJayjayli** [comment]
> I can confirm that the following actions result in a working Grafana v9.4.3 ([cf0a135](https://github.com/grafana/grafana/commit/cf0a1355955cc2d1d2365efc47d3f91a0ddc4158)) installation with CloudFlare protection again:
> 
> 1. Deploy latest image
> 2. Go to CF dashboard, https://dash.cloudflare.com, go to Speed, Optimization, uncheck "JavaScript" in Minify section
> 3. Go to the dashboard of CF again, open your site/domain, click on Caching, Configuration, perform a Complete Purge
> 4. Open Firefox and clear all data https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox for the Grafana site you are working with
> 
> I will leave the debate on "where this should be fixed" to the SME's.

I can confirm this workaround works for me - just needed to restart my browser as well as clearing all data. Thank you!

**Comment by aanthonyrizzo** [comment]
Can also confirm that changing CF rules worked for us. Needed to have cloudflare specifically clear `/public/build/512.6743f01f38a1921b4ef9.js` as mentioned previously.

**Comment by mecampbellsoup** [comment]
> Cloudflare didn't minify js code correctly on file `/public/build/512.6743f01f38a1921b4ef9.js`.

Is it because it's already minified or something?

**Comment by trim21** [comment]
> > Cloudflare didn't minify js code correctly on file `/public/build/512.6743f01f38a1921b4ef9.js`.
> 
> Is it because it's already minified or something?

yes

**Comment by tete17** [comment]
Hey @jackw 

We are also affected by this bug. Do you think is worth it to track down the source of the problem. Even if you minify an already minified file it should still be valid as long as the original final is valid.

To me the problem could be in any of the 3 places:
 * The original js is not correct and as a subtle bug/syntax error
 * Webpack messed up while minifying
 * Cloudflare messed up while minifying

I highly suspect it is the latter since disabling that last step recovers the functionality.

I also understand debugging a double minified/obscured file is not realistic but I leave it up to since this is more of mitigation efforts in my eyes rather than a fix. 

Maybe @cloudflare may want to know about this

**Comment by trim21** [comment]
> * The original js is not correct and as a subtle bug/syntax error
> * Webpack messed up while minifying
> * Cloudflare messed up while minifying

original js and webpack minified js are all correct, but cloudflare doesn't handle it correctly.

**Comment by podarok** [comment]
This helped
![image](https://user-images.githubusercontent.com/563412/227161188-513f0e5b-6975-4cd8-a03c-3b59055b0fc0.png)

**Comment by MaximilianGaedig** [comment]
I spent so many hours debugging this, to fix this issue disable JavaScript in Speed>Optimization>Auto Minify

It doesn't minify the first request and at first stuff might seem to work but then it breaks, such an awful issue.

**Comment by tolzhabayev** [comment]
summarized quite well above, closing

**Comment by jibrilsharafi** [comment]
> This helped ![image](https://user-images.githubusercontent.com/563412/227161188-513f0e5b-6975-4cd8-a03c-3b59055b0fc0.png)

I can confirm that doing this alone solved my issue as well.

**Comment by stanislavZemek** [comment]
You can try to disable feature below: 
HTTP/2 to Origin
Enable HTTP/2 requests between Cloudflare's edge and your origin

In cloudflare it is under the "Speed" settings.
