### ISSUE TITLE
Chore: Create a data plane contract for tracing/nodeGraph/profiles

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#63941]
Create a definition of data contract for tracing, nodeGraph and profile data based on what already exists in https://github.com/grafana/dataplane/tree/main/docs/contract.

Even though all these basically work with tree or directed graph data they have different way to encode this in a DataFrame so seems like best way short term is to create 3 different contracts, one for each, mirroring current state.

There is already some documentation around data formats in the main Grafana docs.
- https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/node-graph/#data-api
- https://grafana.com/docs/grafana/latest/explore/trace-integration/#data-api
- https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/flame-graph/#data-api

Tasks
- [ ] trace
- [ ] nodeGraph
- [ ] profile

**Comment by kylebrandt** [comment]
Note: Docs moved to https://github.com/grafana/dataplane/tree/main/docs/contract
