### ISSUE TITLE
Azure Monitor: Query variables stop working after 9.4 upgrade

### ISSUE THREAD

**Issue by asimpson** [grafana/grafana#63943]
**What happened**:
The error: `Error updating options: Cannot add property resources, object is not extensible.` is thrown after upgrading to 9.4.

**How to reproduce it (as minimally and precisely as possible)**:
1. In 9.3.x create a template variable, e.g. 
```kql
AzureActivity
| where SubscriptionId == "$subs"
| distinct ResourceGroup
| project Value = tostring(ResourceGroup), Text = tostring(ResourceGroup)
```
2. Upgrade to 9.4
4. Load the variables editor and note the error
![image](https://user-images.githubusercontent.com/1048831/222171264-2cea3012-4d87-44f3-b471-4d28e7c21c7c.png)

The issue appears to be that the `query` object is not `writeable` during query migration which means creating the `resources` property fails.

**Comment by hermanocabra** [comment]
I'm facing same error
