### ISSUE TITLE
Glue: Measure impact of Correlations Editor UX improvements

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#63940]
### Background

Correlations editor is complex and hard to understand. We would like to have a way to measure if improvements we're working on https://github.com/grafana/grafana/issues/55371 are good. 

One way of doing it by checking if we manage to reduce time spent on creating a correlation, but the time depends on some many factors that this way it's hard to give any useful data.

Alternatively we can track completion rate: how many users start and finish adding a correlation. 

#### Requirements

High level: _Measure impact of Correlations Editor improvements._

- ~Define baseline and target levels~
- ~Track how many seconds/minutes a user spend between clicking "Add" and "Save" in Correlations Page~
- Track when a correlation adding started, and when it finished
- Editing should not be included
- Create a dashboard showing how long it takes to create a correlation and what the failure ratio (how many times it's not finished)

**Comment by ifrost** [comment]
There seem to be no benefit in tracking time spent in the wizard. It will not tell us much:

* There's no baseline to compare with
* Time spent depends on many factors that we may not be able to measure: for example reading documentation while adding, switching tabs to compare with the data in Explore, 
* The actual setup of a correlation may involve multiple add/edit/edit... actions - it's quick to set up a dummy link just to see if it works and then tweak it later

**Comment by ifrost** [comment]
As an alternative approach we can measure completion rate: how many users started vs how many finished adding a correlation.

**Comment by radiorental** [comment]
Would a round of usability testing help here?  There is also Fullstory for cloud users that we could observe passively after release.

**Comment by ifrost** [comment]
> Would a round of usability testing help here? There is also Fullstory for cloud users that we could observe passively after release.

Yes! 🎉
