### ISSUE TITLE
Convert field type problems - out of a Loki datasource

### ISSUE THREAD

**Issue by JoachimSchiewek** [grafana/grafana#63947]
**I have a problem to convert the filed type to number as the  datasource is from Loki**:

**As an example I get 3 Values from an ordinary grafana.log**:
Value 1 is a DATE, The user-ID stands for NUMBER 1 and the duration for NUMBER 2. Just to have some numbers.

Out of Loki,  all the values are string type values. 
To create a graph, I have to convert them to numbers.

**Here is what happend..**:

![Test_1](https://user-images.githubusercontent.com/94972393/222177531-6d7593c1-de98-4e9b-bc07-1d04183deaa7.gif)

when I convert them to number - it crashed. Cant do that. 

This problem occures since Grafana  9.3.6

[more examples in the community](https://community.grafana.com/t/grafana-9-3-6-update-problem-with-transformations/80659) 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser:
- Grafana plugins:
- Others:

Hope someone can help and fix the situation.
In my case I can fix the problem by convert to json and not to number.

**Comment by matyax** [comment]
@grafana/dashboards-squad could you please a look at this one?

**Comment by matyax** [comment]
@grafana/dashboards-squad could you please a look at this one? If there’s anything we can help with, just ping us. Thanks!

**Comment by ivanahuckova** [comment]
I removed Loki label as this seems like an issue with transformations and not issue with Loki data source.

**Comment by mckamyk** [comment]
It appears the file `grafana/packages/grafana-data/src/transformations/transformers/convertFieldType.ts` has the following function.
```js
function fieldToNumberField(field: Field): Field {
  const numValues = field.values.toArray().slice();

  // in my case, numValues appears to be [undefined, "2.3", undefined, "12.1", ...]

  const valuesAsStrings = numValues.some((v) => typeof v === 'string');

  for (let n = 0; n < numValues.length; n++) {
    let toBeConverted = numValues[n];

    if (valuesAsStrings) {
      // some numbers returned from datasources have commas
      // strip the commas, coerce the string to a number
      toBeConverted = toBeConverted.replace(/,/g, '');
    }

    const number = +toBeConverted;

    numValues[n] = Number.isFinite(number) ? number : null;
  }

  return {
    ...field,
    type: FieldType.number,
    values: new ArrayVector(numValues),
  };
}
```

This does not account for sparse data, where some of the records have `undefined` as the value for the targetted field. the 
```js
if (valuesAsStrings) {
  // some numbers returned from datasources have commas
  // strip the commas, coerce the string to a number
  toBeConverted = toBeConverted.replace(/,/g, '');
}
```
errors as `cannot read property ".replace" of undefined.`

Could this be simply remedied with the following snipped?

```js
if (valuesAsStrings && toBeConverted) { // check toBeConverted exists.
  // some numbers returned from datasources have commas
  // strip the commas, coerce the string to a number
  toBeConverted = toBeConverted.replace(/,/g, '');
}
```

**Comment by zoltanbedi** [comment]
Fixed in https://github.com/grafana/grafana/pull/66807 The fix will be out in Grafana 10
