### ISSUE TITLE
Glue: Limit number of correlations that can be created

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#63955]
### Background

As a part of feature roll-out we should ensure that we have input bounds in place. At the moment there's no limit to number of created correlations. 

### Requirements ###

High level: _Define limits for correlations stored in the database_

#### Technical details

* Limits should be part of the configuration with no limit as default.
* The limit defines how many correlations can be defined per data source. Throw an exception when more is being added.

**Comment by gelicia** [comment]
@ifrost Where are you thinking this should go? 

Datasources? https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L404 
Usage quotas? https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L879 
Explore? https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L1080

Its own section? Somewhere else?

**Comment by ifrost** [comment]
I think it should be part of usage quotas Usage quotas? https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L879 👍
