### ISSUE TITLE
Security: Grafana slack alerts should go only to a particular team and not outside the team.

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6395]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Grafana alerts when sent to slack should only go the channels and users belonging to a particular team and not outside it.

OR

Admin should allow the teams to which Grafana alerts can go.

**Comment by torkelo** [comment]
You can setup any number of slack notifications that go to different channels,

**Comment by torkelo** [comment]
What do you mean by team? There is no such thing in grafana? And where the slack webhook goes you configure in slack

**Comment by utkarshcmu** [comment]
By team I meant slack account. For example, if I can restrict my alerts to go to individuals or channels only for "raintank.slack.com", it might be better as per security as then we are not sending the Grafana URLs outside the tools which we have authorized according to the security.

I know its hard to setup something like this but if the admin can configure that slack alerts can go either to any slack (*.slack.com) or something specific (raintank.slack.com).

**Comment by torkelo** [comment]
Not sure why, you don't trust your org admin? You could do this with some firewall rules as well
