### ISSUE TITLE
Azure Monitor: Custom dimensions are not accessible in "Metrics" query

### ISSUE THREAD

**Issue by stoney95** [grafana/grafana#63962]
**What happened**:
I am using `opencensus-ext-azure` python library to send metrics to an Application Insights instance. I use a tag map to define custom dimensions as described [here]. The custom dimensions are tracked in Application Insights. When querying the metric in Grafana, I can not see any of my custom dimensions in the "Dimension" field.

**What you expected to happen**:
I expect to see the tags I define in my python code as Dimensions I can use for filtering

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Here is a snippet from Application Insights. In "customDimensions" you can see the tags I defined. The defined tags are only used for the purpose of testing:
<img width="1226" alt="Screenshot 2023-03-01 at 17 48 29" src="https://user-images.githubusercontent.com/34100018/222206667-3fd21029-6e4d-4ca9-b95b-158836a07a69.png">

These dimensions are not found in Grafana:
<img width="1297" alt="Screenshot 2023-03-01 at 17 49 35" src="https://user-images.githubusercontent.com/34100018/222206952-fc9a2045-e232-40e9-8745-8912a0424e92.png">

**Environment**:
- Grafana version: v9.3.6 (Azure Managed Grafana)
- Data source type & version: Azure Monitor v1.0.0
- OS Grafana is installed on: -
- User OS & Browser: MacOS 12.6.3 & Firefox 110.0.0
- Grafana plugins: -
- Others: -

**Comment by bossinc** [comment]
closing as duplicate [#6045](https://github.com/grafana/grafana/issues/60450)
