### ISSUE TITLE
Template variable "nesting" not working - Maybe related to Pull Req 4970

### ISSUE THREAD

**Issue by kerk1v** [grafana/grafana#6397]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-pre-1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Centos 7.2
- What did you do? I needed Elasticsearch 5 support, so i cloned the latest master from github and patched https://github.com/grafana/grafana/pull/4970 changes for ES 5.0 in locally, then built the .rpm package and installed it
- What was the expected result? Elasticsearch 5.0 Data Source supported and template variables working as before
- What happened instead? All fine, except "nested" template variable no longer work as expected, as explained below: 

I had a dashboard with two template variables:

    $prov {"find": "terms", "field": "province"}
    $loc {"find": "terms", "field": "location", "query": "province: $prov"}

so when I selected a province in $prov variable, it would only show $loc values actually located in $prov. Now regardless of the value of $prov it always shows all possible values of $loc. Sort of impractical, since there is a list of more than 800 possible values for $loc :(

Maybe someone who doesn't have only Elasticserarch 5.0 right now could test this without patching the source, and see if the error repeats there?

If some DEV wants access to my Grafana install, let me know, and I'll create a temporary user and password for you. 

I have also made a comment on this issue on the pull request. 

Thanks all!

**Comment by lpic10** [comment]
Hello @kerk1v ,

Indeed it was an issue with #4970 , should be working now, thanks for the report.

**Comment by kerk1v** [comment]
Wow, that was mighty quick, thanks a lot!

**Comment by kerk1v** [comment]
Built and tested!  All OK. Also did a quick manual regression on some ES 2.x Data Source and all is fine!
