### ISSUE TITLE
LCD gauge option setting bar or mode

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#63971]
### Discussed in https://github.com/grafana/grafana/discussions/38275

[Related discussion here](https://github.com/grafana/grafana/discussions/37297) (to also consider as part of addressing this)

<div type='discussions-op-text'>

<sup>Originally posted by **PetersPlace** May  5, 2021</sup>

**What would you like to be added**:
The LCD gauge works great but nice would be the option to set bar or dot mode.

**Why is this needed**:
This is nice if you want to monitor al value  between lets say 40 to 60 %, we set the tresholds green color between  40 and 60
Below 40 and above 60 is red color
With bar the 0-40 is always red colored, so i would be nice if only the green dots wil light up is the signal is between 40 and 60

![lcd-gauge](https://user-images.githubusercontent.com/35110891/117111623-3027bc00-ad88-11eb-9514-840be2079771.jpg)

</div>

**Comment by zoltanbedi** [comment]
Let's see if more people are looking forward for this feature.
