### ISSUE TITLE
Creating data source with existing name returns HTTP 500 Internal Server Error instead of 409 Conflict

### ISSUE THREAD

**Issue by thecosmicfrog** [grafana/grafana#6398]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

- What Grafana version are you using? - Version 3.1.1 (commit: a4d2708)
- What datasource are you using? - InfluxDB
- What OS are you running grafana on? - Amazon Linux 4.4.5-15.26.amzn1.x86_64
- What did you do? - Using API, create data source with name that already exists in system.
- What was the expected result? - API should return a useful HTTP status code, such as 409 (Conflict).
- What happened instead? - API returned HTTP status code 500 (Internal Server Error).

Put simply, I am using the Grafana API to create a new data source called "NewDatasource". However, I expect that, if I try to create another data source with the same name, the server would return a useful HTTP status code such as 409, to make it clear that this name (key) already exists in the system and we cannot create another one. Instead, the API returns 500, which suggests the server has a catastrophic issue. This makes it difficult to test.

The reason I expect this is for idempotency. We want to be able to repeatedly attempt data source creation without it changing the system, but in order to test this correctly, we need a valid HTTP status code (not 500).

This behavior is already in place for Organization creation. If we attempt to create an Organization with a name that already exists, we get a 409 Conflict - exactly what we expect - with a useful message returned also: "message": "Organization name taken".

**Comment by torkelo** [comment]
this is fixed in master I think

**Comment by thecosmicfrog** [comment]
@torkelo Could you please point us to a commit hash for this fix before closing? Is there an ETA on the fix being released as stable?

**Comment by torkelo** [comment]
Not Eta, v4 Beta release is within   2 weeks so will not be a 3.1.2 release unless critical issue arise

**Comment by thecosmicfrog** [comment]
@torkelo Thanks. Can you please point me to the commit hash with the fix?
