### ISSUE TITLE
Alerting: Email template appears broken in Outlook's desktop client

### ISSUE THREAD

**Issue by MarNicGit** [grafana/grafana#63996]
**What happened**:
I upgraded from Grafana 9.2.0 to 9.4.1

**What you expected to happen**:
Email alerts would continue to look clear and functional

**How to reproduce it (as minimally and precisely as possible)**:
1. Create email contact point
2. Send a test alert to this contact point using the "Test" button

**Anything else we need to know?**:
After upgrading to 9.4.1, my alert emails now look like this:
![image](https://user-images.githubusercontent.com/47538428/222359499-1767856b-3b8d-49eb-809e-6ff9b1c237d8.png)

While they used to look like this:
![image](https://user-images.githubusercontent.com/47538428/222359548-260fa200-5466-4f5f-b9bf-fd3d1ff42577.png)

Is this expected behavior? The new email template looks stretched out and have a _lot_ of whitespace. Real alerts also show the buttons stacked on top of each other, while I'd expect them to be next to each other:
![image](https://user-images.githubusercontent.com/47538428/222360347-67884e99-4d2a-4c17-b950-f3030813ae57.png)

At first I thought I might've had a broken template installed, but the email templates in my installation all appear stock: 
![image](https://user-images.githubusercontent.com/47538428/222360919-6e9a0e77-dab2-4999-ac02-a350f24a687b.png)

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: N/A
- OS Grafana is installed on: Windows Server 2016 v1607
- User OS & Browser: Windows 11 21H2, Outlook version 2301 (Build 16026.20200)
- Grafana plugins: N/A
- Others: N/A

**Comment by MarNicGit** [comment]
I've done some more research and it appears as if this is isolated to just Outlook 2301. I've opened the same mail using the outlook webclient (outlook.com) and it shows up exactly like the screenshots in the initial template PR (#57751).

**Comment by MiggL** [comment]
Did some research myself and it seems like all html (conditional) comments, including the Outlook conditionals, are stripped when generating the final html that is sent.

The email template (in my case stored in `/usr/share/grafana/public/emails/ng_alert_notification.html`) contains code such as
```
<!--[if mso]>
...
<![endif]-->
```
This is code that is supposed to run only in Outlook.
But if I view the source of one of the alert emails sent to Outlook by Grafana 9.4.3, all these conditionals, including the content, are just empty lines.

If I manually add back the conditionals in the source and make a dummy .eml-file to open in Outlook, all the buttons are correctly placed next to each other.

**Comment by MiggL** [comment]
@gillesdemey Will you be able to look into this?

**Comment by gillesdemey** [comment]
Yea it does look like the HTML comments are stripped after compiling the `.html` file, curiously I can't think of any step in the pipeline that would do this after we've compiled the MJML source in to the HTML artifacts. 

I've downloaded the `.eml` for the mails that I receive and all comments do seem to be absent.

**Comment by gillesdemey** [comment]
At first glance it looks like HTML comments [are being stripped](https://github.com/golang/go/issues/28628) by the Golang `template/html` package and this is very much intentional (and undocumented).

**Comment by gillesdemey** [comment]
I've created [a PR](https://github.com/grafana/grafana/pull/64546) that allows to preserve the HTML comments necessary to render properly in MS Outlook.

I'm also attaching a `.eml` file of what is now being sent if anyone wants to validate this with their email client :)

[gy3y616R.correct.eml.zip](https://github.com/grafana/grafana/files/10934297/gy3y616R.correct.eml.zip)

**Comment by MarNicGit** [comment]
@gillesdemey This looks great on my end, thanks!
