### ISSUE TITLE
JWT authentication should ignore keys it does not understand within a JWKS

### ISSUE THREAD

**Issue by timw6n** [grafana/grafana#64009]
**What happened**:

Newer versions of Pomerium expose a JWKS key set to Grafana including a key with curve "X25519". When Grafana loads this JWKS URL (in order to validate the JWT header) it fails with the error `square/go-jose: unknown curve X25519`.

Note that the key used to actually sign the JWT passed in the header is there also, and in a format that Grafana can understand.

**What you expected to happen**:

Grafana will disregard keys that it does not understand and use the remaining keys to validate passed tokens. 

This behaviour is a "should" in https://www.rfc-editor.org/rfc/rfc7517#section-5.

**How to reproduce it (as minimally and precisely as possible)**:

Ask Grafana to load a JWKS URL including (in addition to the key it can read) a key it cannot, e.g. 

```
 {
      "kty": "OKP",
      "kid": "pomerium/hpke",
      "crv": "X25519",
      "x": "[snip]"
    }
```

**Anything else we need to know?**:

Have raised this to the Pomerium maintainers as https://github.com/pomerium/pomerium/issues/4029 as I suspect they didn't intend to break a load of integrations in the way they have. Nonetheless it is exposing bugs in multiple apps/libraries that read JWKS files.

**Environment**:
- Grafana version: grafana/grafana-oss:9.4.1

**Comment by mgyongyosi** [comment]
@timw6n Thank you for the report. Grafana depends on the go-jose library to parse json web key sets, verify tokens, etc and after an investigation it seems that go-jose does not support X25519 as a `"crv"` value (https://github.com/go-jose/go-jose/blob/878ec67363eb6dc8487e1d7ef3a5408d591979fd/jwk.go#L230). X25519 as a crv value is specified in a [RFC8037](https://datatracker.ietf.org/doc/html/rfc8037) which is in proposed state and has not been implemented by the go-jose library.

The best would be if pomerium could remove this key from the keyset. (And it seems they have a PR to remove the problematic key from their keyset: https://github.com/pomerium/pomerium/pull/4044.)

**Comment by timw6n** [comment]
Thanks for investigating this. Agreed that that Pomerium PR is probably the quickest and most pragmatic solution to the problem at hand. 

That said, I think there may be value in making Grafana's JWKS file parsing a bit more tolerant of unknown properties / keys / curves etc in the longer term -- appreciate that may not be easily possible if the relevant logic is within the go-jose library though.

**Comment by mgyongyosi** [comment]
@timw6n We are going to look into how to improve JWKS parsing in Grafana!

**Comment by bluecmd** [comment]
Unless I am missing something, go-jose seems to have PR opened to fix this; https://github.com/go-jose/go-jose/pull/26
Maybe worth poking the maintainer about merging this if Grafana wants this.
