### ISSUE TITLE
[Feature Request] Add Offset to Influxdb Query Editor

### ISSUE THREAD

**Issue by unixninja92** [grafana/grafana#6401]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  Influxdb
- What OS are you running grafana on?
  offical docker image

When calculating derivatives and non-negative-derivatives on counts with influxdb the first data point will periodically be way off because it thinks the first data point is a zero and is then jumping to the count. To combat this, it is useful to use OFFSET to drop the first data point. I'd think it would go best on it's own row after GROUP BY in the query editor as it is appended on the end of queries and is independent of GROUP BYs. It might make sense to also include support for SOFFSET, LIMIT, and SLIMIT at the same time. I could see LIMIT being quite useful when working with tables.

**Comment by rikkuness** [comment]
I've just added offset as a 2nd param of time() as part of PR #7040 , it isn't entirely elegant as I can't see how to make it an optional param, I've set the default to match $interval though which seems to work fine.

**Comment by burdandrei** [comment]
we're affected too, maybe https://github.com/grafana/grafana/pull/7796 can be merged? @torkelo

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
