### ISSUE TITLE
proxy authentication render endpoint fails

### ISSUE THREAD

**Issue by fragfutter** [grafana/grafana#6402]
grafana 3.1.1 behind apache 2.4.6

apache is handling the authentication and passing the username via headers. 

```
ProxyPass /grafana http://127.0.0.1:3000
ProxyPassReverse /grafana http://127.0.0.1:3000
RequestHeader set X-WEBAUTH-USER %{REMOTE_USER}s
```

in grafana auto signup is enabled and everything works as expected.

Now i have a fixed host which should not require a login. For this host i set the header to a dummy value, the apache config now looks like

```
ProxyPass /grafana http://127.0.0.1:3000
ProxyPassReverse /grafana http://127.0.0.1:3000
<If "-R '192.168.10.11/32'">
RequestHeader set X-WEBAUTH-USER fixedhost
</If>
<Else>
RequestHeader set X-WEBAUTH-USER %{REMOTE_USER}s
</Else>
```

accessing the api via curl works. For example

`curl http://monitoringhost/grafana/api/user`

returns a json document with the fixedhost user in it.

I can also open a dashboard, but it can't load the datapoints

i see that grafana receives the correct user, but it will deny the request

`t=2016-10-27T17:50:11+0200 lvl=info msg="Request Completed" logger=context userId=15 orgId=1 uname=fixedhost method=POST path=/render status=401 remote_addr=192.168.10.11 time_ns=19ns size=381
`

It looks like the render endpoint does not work with the proxy authentication.

**Comment by torkelo** [comment]
Do you have basic auth on your apache server? Need to block that header from reaching grafana
