### ISSUE TITLE
XY Chart: Bug with threshold

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#64027]
Dear grafana community,

when using the XY Chart and setting a threshold, it is not displayed.

cheers,
yulipumal

**Comment by JohnBolander** [comment]
I have the same issue on Grafana 9.4.3

**Comment by nmarrs** [comment]
Hi @yulipumal, what axes are you setting the threshold for? (x vs y?) Do you have an example panel json you could share with this problem?

**Comment by JohnBolander** [comment]
You can recreate with the current grafana play https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&editPanel=1&tab=transform
`{
  "datasource": {
    "uid": "000000001",
    "type": "graphite"
  },
  "description": "",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "show": "points",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 60
          }
        ]
      },
      "unit": "short"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "backend_01"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "purple",
              "mode": "palette-classic"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "backend_02"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "green",
              "mode": "palette-classic"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "backend_02"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "blue",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "web_server_01"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "#EF843C",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "web_server_02"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "#EAB839",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "web_server_03"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "#508642",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "web_server_04"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "#E24D42",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 7,
    "w": 18,
    "x": 0,
    "y": 0
  },
  "id": 1,
  "maxDataPoints": 400,
  "pluginVersion": "8.0.0-beta1",
  "targets": [
    {
      "refCount": 0,
      "refId": "A",
      "target": "aliasByNode(scaleToSeconds(apps.backend.backend_01.counters.requests.count, 1), 2)",
      "textEditor": false,
      "datasource": {
        "uid": "000000001",
        "type": "graphite"
      }
    },
    {
      "hide": false,
      "refCount": 0,
      "refId": "B",
      "target": "aliasByNode(scaleToSeconds(apps.backend.backend_02.counters.requests.count, 2), 2)",
      "datasource": {
        "uid": "000000001",
        "type": "graphite"
      }
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Simple graph",
  "type": "xychart",
  "options": {
    "seriesMapping": "auto",
    "series": [],
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "dims": {
      "frame": 0
    }
  },
  "transformations": [
    {
      "id": "joinByField",
      "options": {}
    }
  ]
}`

**Comment by leeoniya** [comment]
@yulipumal can you try our new Trend panel thresholds will work there, and is probably what you want with your data shape: https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/trend/

**Comment by ffisc** [comment]
> @yulipumal @JohnBolander can you try our new Trend panel? thresholds will work there, and is probably what you want with your data shape: https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/trend/

@leeoniya is the Trend panel available in v9.4? I cannot find it (and I use an AWS-managed instance so I can't upgrade to v10)

**Comment by Davidkramer1999** [comment]
I'm intrested  if this is till the case? It's really weird that you provide an option for Threshold and then you say it doesn't work go checkout Trend panel ?
