### ISSUE TITLE
Update REAMDE to reflect `node v6+` requirement

### ISSUE THREAD

**Issue by ichekrygin** [grafana/grafana#6403]
* **I'm submitting a documentation update issue**
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using: 
current master https://github.com/grafana/grafana/commit/b382d17e3495b1a36d6045af80b22713279e6d2a

- What datasource are you using: N/A

- What OS are you running grafana on?
Linux 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- What did you do? 
Followed build instructions in README https://github.com/grafana/grafana#building-frontend-assets

- What was the expected result?
Build passes

- What happened instead?
⋊> ~/g/s/g/g/grafana on master ⨯ npm run build                                                                                                                                                               09:38:19

> grafana@4.0.0-pre1 build /home/illya/go/src/github.com/grafana/grafana
> grunt

Version 4.0.0-pre1
Loading "sass.js" tasks...ERROR
>> Error: Missing binding /home/illya/go/src/github.com/grafana/grafana/node_modules/node-sass/vendor/linux-x64-46/binding.node
>> Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x
>> 
>> Found bindings for the following environments:
>>   - Linux 64-bit with Node.js 6.x
>> 
>> This usually happens because your environment has changed since running `npm install`.
>> Run `npm rebuild node-sass` to build the binding for your current environment.

Upgrading to latest node (v6.9.1) fixes this issue

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
it should work fine with v4, v5, and v6, you don't need v6, v5 works fine (if you build node-sass following the instructions), npm rebuild node-sass
