### ISSUE TITLE
Logs volume: When zooming in logs volume “from” time changed but “to” time was incorrect

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#64043]
**What happened**:

When using logs volume to zoom in on specific time, the "from" time was correctly changed, but "to" time was incorrectly set. See
https://drive.google.com/file/d/1YPOprw8f9qADc7P0qTTRmJBFfOEfFhLn/view?usp=sharing (14:30) for example.

**Environment**:
- Grafana version: 9.4/main

**Comment by matyax** [comment]
Tried to reproduce this with no luck. I think if this happened consistently it would have been reported at least once. Feel free to reopen if you can think of an scenario where this could happen.
