### ISSUE TITLE
Column names of table getting sorted by default

### ISSUE THREAD

**Issue by jayannah** [grafana/grafana#6405]
- [ ] Bug report

When we create dashboard table with InfluxDB query such as select * from measurement_name where time > now() - 1h group by ROOT, BRANCH1, BRANCH2, BRANCH3

The output column will have ROOT as last column after BRANCH1,2,3.. Grafana automatically sorts the column names chronographically. 

Expected behavior: Grafana should retain the same column order mentioned in the query.

Please include this information:
- What Grafana version are you using?  3.0.4
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Linux
- What did you do? Created a dashboard with table
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
can you show the influxdb response? The column order is the same as what influxdb returns
