### ISSUE TITLE
Cannot login via LDAP second time if `username` parameter case is different from LDAP directory

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#6408]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
grafana-3.1.1-1470047149

- What datasource are you using?
n/a

- What OS are you running grafana on?
Linux CentOS/7

- What did you do?
Configured LDAP with the `servers.attributes` `username` parameter set to `samAccountName` while the LDAP directory returns `sAMAccountName`.
Logged in which auto created a new user.
Logged out.
Tried to log in again.

- What was the expected result?
To log in successfully.

- What happened instead?
```
t=2016-10-27T16:40:41-0400 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.email"
```

- Additional info:
The sqlite database has this:
```
id|version|login|email|name|password|salt|rands|company|org_id|is_admin|email_verified|theme|created|updated
6|0||MyUser@mycompany.com|First Last|||||1|0|0||2016-10-27 20:44:57|2016-10-27 20:44:57
```
Notice that the `login` field is empty.

Setting the correct case for the `username` config param resolves the issue (after deleting the user).

**Comment by torkelo** [comment]
thanks for reporting this. Think it's fixed in master (empty login field will not be accepted)

**Comment by indigo423** [comment]
With Active Directory we where able to solve this problem by setting `username = "cn"`
