### ISSUE TITLE
string data not aligned with numeric data when processing data links in time series panel with multiple series

### ISSUE THREAD

**Issue by jmholzinger** [grafana/grafana#64088]
**What happened**:
Data links that reference string data do not work correctly when a times series panel has multiple series and the time column data is not the same in all the series.

**What you expected to happen**:
Data links should correctly reference the string data associated to a given data point, even when the time column is not perfectly aligned across all the series.

**How to reproduce it (as minimally and precisely as possible)**:

Consider the following data table (`DEVICE_DATA`).
| TIMESTAMP           | DEVICE | METRIC | REPORT       |
|---------------------|--------|--------|--------------|
| 2023-03-02T00:00:00 | A      | 5      | report1.html |
| 2023-03-02T01:00:00 | B      | 3      | report2.html |
| 2023-03-02T02:00:00 | C      | 8      | report3.html |
| 2023-03-02T03:00:00 | A      | 12     | report4.html |
| 2023-03-02T04:00:00 | B      | 7      | report5.html |
| 2023-03-02T05:00:00 | C      | 42     | report6.html |

Here there are three different devices (`A`, `B`, and `C`) which have a metric recorded at some time. Each metric also references a detailed report where more information can be found. I would like to graph the device data for each device with data links to the detailed report.

So I create a time series panel with three series, one for each device.
```
SELECT TIMESTAMP, METRIC AS "A", REPORT FROM DEVICE_DATA WHERE DEVICE = 'A'
SELECT TIMESTAMP, METRIC AS "B", REPORT FROM DEVICE_DATA WHERE DEVICE = 'B'
SELECT TIMESTAMP, METRIC AS "C", REPORT FROM DEVICE_DATA WHERE DEVICE = 'C'
```

Then I configure a data link "Detailed Report" to drill into the report from each data point.
```
http://hostname.com/reports/${__data.fields['REPORT']}
```

But when I go to click the data link for many of the data points most of them don't work, the data link URL resolves to:
```
http://hostname.com/reports/
```

**Why does this happen?**:

When multiple series are defined in a time series panel the data frames are aligned into a single data frame for rendering in the panel. This alignment joins the time column from all the series into a single column and "pads" the numeric data with `undefined` at time points that did not exist for a column before the data frames were aligned. This alignment process only applies to the numeric data, the non-graphable string data is ignored during the alignment process. Since this string data is not included in the alignment it is attached to a temporary data frame that is created when generating the link suppliers for the aligned data frame. However, when the string data is attached to the temporary data frame it is not correctly aligned to the data with which it is associated (e.g. no padding with `undefined` values). This means that when the data links are being generated the index at which we look for the string data is outside the bounds of the array which contains the string data.

I traced the problem described above to the `regenerateLinksSupplier` method defined in:
```
public/app/plugins/timeseries/utils.ts
```

To help visualize this, consider how the aligned data frames would look using the example above.
| TIMESTAMP           | A         | B         | C         |
|---------------------|-----------|-----------|-----------|
| 2023-03-02T00:00:00 | 5         | undefined | undefined |
| 2023-03-02T01:00:00 | undefined | 3         | undefined |
| 2023-03-02T02:00:00 | undefined | undefined | 8         |
| 2023-03-02T03:00:00 | 12        | undefined | undefined |
| 2023-03-02T04:00:00 | undefined | 7         | undefined |
| 2023-03-02T05:00:00 | undefined | undefined | 42        |

Then when the link suppliers are being generated for the data frame of the "A" series.
| TIMESTAMP           | A         | B         | C         | REPORT       |
|---------------------|-----------|-----------|-----------|--------------|
| 2023-03-02T00:00:00 | 5         | undefined | undefined | report1.html |
| 2023-03-02T01:00:00 | undefined | 3         | undefined | report2.html |
| 2023-03-02T02:00:00 | undefined | undefined | 8         |              |
| 2023-03-02T03:00:00 | 12        | undefined | undefined |              |
| 2023-03-02T04:00:00 | undefined | 7         | undefined |              |
| 2023-03-02T05:00:00 | undefined | undefined | 42        |              |

If the string data was properly aligned with the relevant numeric data the data frame should look like this.
| TIMESTAMP           | A         | B         | C         | REPORT       |
|---------------------|-----------|-----------|-----------|--------------|
| 2023-03-02T00:00:00 | 5         | undefined | undefined | report1.html |
| 2023-03-02T01:00:00 | undefined | 3         | undefined | undefined    |
| 2023-03-02T02:00:00 | undefined | undefined | 8         | undefined    |
| 2023-03-02T03:00:00 | 12        | undefined | undefined | report2.html |
| 2023-03-02T04:00:00 | undefined | 7         | undefined | undefined    |
| 2023-03-02T05:00:00 | undefined | undefined | 42        | undefined    |

**Environment**:
- Grafana version: v9.3.6
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by leeoniya** [comment]
very thorough investigation  @jmholzinger :1st_place_medal: , sounds about right.

**Comment by leeoniya** [comment]
by the way, you may be interested in the [Partition by values](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#partition-by-values) transformation which would allow you do just a single query: `SELECT TIMESTAMP, DEVICE, METRIC, REPORT FROM DEVICE_DATA`

(this won't solve the issue you're reporting here)

**Comment by leeoniya** [comment]
i refactored data link gen in https://github.com/grafana/grafana/pull/83654, including a fix for misaligned series handling.
