### ISSUE TITLE
Dynamic Text with InfluxDB

### ISSUE THREAD

**Issue by Kamilloos** [grafana/grafana#64102]
Query inspector (good one):
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "fnXOV6nnk"
          },
          "refId": "A",
          "policy": "default",
          "resultFormat": "table",
          "orderByTime": "ASC",
          "tags": [
            {
              "key": "name",
              "value": "P11",
              "operator": "="
            }
          ],
          "groupBy": [],
          "select": [
            [
              {
                "type": "field",
                "params": [
                  "RE_T"
                ]
              }
            ],
            [
              {
                "type": "field",
                "params": [
                  "PF_T"
                ]
              }
            ]
          ],
          "measurement": "modbus",
          "query": "SELECT \"PF_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND $timeFilter",
          "rawQuery": false,
          "alias": "",
          "adhocFilters": [],
          "limit": "",
          "slimit": "",
          "tz": "",
          "datasourceId": 10,
          "intervalMs": 200,
          "maxDataPoints": 1116
        }
      ],
      "range": {
        "from": "2023-03-03T06:47:10.409Z",
        "to": "2023-03-03T06:52:10.409Z",
        "raw": {
          "from": "now-5m",
          "to": "now"
        }
      },
      "from": "1677826030409",
      "to": "1677826330409"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "modbus.RE_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE \"name\" = 'P11' AND time >= 1677826030409ms and time <= 1677826330409ms ORDER BY time ASC"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.RE_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677826046000,
                  1677826138000,
                  1677826229000,
                  1677826257000
                ],
                [
                  3837.34,
                  3840.03,
                  3842.68,
                  3843.48
                ]
              ]
            }
          },
          {
            "schema": {
              "name": "modbus.PF_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE \"name\" = 'P11' AND time >= 1677826030409ms and time <= 1677826330409ms ORDER BY time ASC"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.PF_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677826046000,
                  1677826138000,
                  1677826229000,
                  1677826257000
                ],
                [
                  0.93,
                  0.93,
                  0.93,
                  0.93
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}`

Query inspector (bad one, raw query mode ("Time" key only)):
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "fnXOV6nnk"
          },
          "refId": "A",
          "query": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND $timeFilter",
          "rawQuery": true,
          "alias": "",
          "resultFormat": "table",
          "adhocFilters": [],
          "limit": "",
          "measurement": "",
          "policy": "",
          "slimit": "",
          "tz": "",
          "datasourceId": 10,
          "intervalMs": 200,
          "maxDataPoints": 1116
        }
      ],
      "range": {
        "from": "2023-03-03T08:05:03.712Z",
        "to": "2023-03-03T08:10:03.712Z",
        "raw": {
          "from": "now-5m",
          "to": "now"
        }
      },
      "from": "1677830703712",
      "to": "1677831003712"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "modbus.RE_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND time >= 1677830703712ms and time <= 1677831003712ms"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.RE_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677830788000,
                  1677830847000,
                  1677830910000,
                  1677830940000
                ],
                [
                  3965.17,
                  3965.19,
                  3965.21,
                  3965.22
                ]
              ]
            }
          },
          {
            "schema": {
              "name": "modbus.PF_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND time >= 1677830703712ms and time <= 1677831003712ms"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.PF_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677830788000,
                  1677830847000,
                  1677830910000,
                  1677830940000
                ],
                [
                  0.45,
                  0.41,
                  0.38,
                  0.47
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}`

Query inspector (bad one, raw query mode ("Time" and "mean" as keys)):
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "fnXOV6nnk"
          },
          "refId": "A",
          "policy": "default",
          "resultFormat": "table",
          "orderByTime": "ASC",
          "tags": [],
          "groupBy": [
            {
              "type": "time",
              "params": [
                "$__interval"
              ]
            },
            {
              "type": "fill",
              "params": [
                "null"
              ]
            }
          ],
          "select": [
            [
              {
                "type": "field",
                "params": [
                  "value"
                ]
              },
              {
                "type": "mean",
                "params": []
              }
            ]
          ],
          "query": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND $timeFilter",
          "rawQuery": true,
          "alias": "",
          "adhocFilters": [],
          "limit": "",
          "measurement": "",
          "slimit": "",
          "tz": "",
          "datasourceId": 10,
          "intervalMs": 200,
          "maxDataPoints": 1116
        }
      ],
      "range": {
        "from": "2023-03-03T08:06:09.672Z",
        "to": "2023-03-03T08:11:09.672Z",
        "raw": {
          "from": "now-5m",
          "to": "now"
        }
      },
      "from": "1677830769672",
      "to": "1677831069672"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "modbus.RE_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND time >= 1677830769672ms and time <= 1677831069672ms"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.RE_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677830788000,
                  1677830847000,
                  1677830910000,
                  1677830940000
                ],
                [
                  3965.17,
                  3965.19,
                  3965.21,
                  3965.22
                ]
              ]
            }
          },
          {
            "schema": {
              "name": "modbus.PF_T",
              "refId": "A",
              "meta": {
                "executedQueryString": "SELECT \"RE_T\", \"PF_T\" FROM \"modbus\" WHERE (\"name\" = 'P11') AND time >= 1677830769672ms and time <= 1677831069672ms"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "config": {
                    "displayNameFromDS": "modbus.PF_T"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1677830788000,
                  1677830847000,
                  1677830910000,
                  1677830940000
                ],
                [
                  0.45,
                  0.41,
                  0.38,
                  0.47
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}`

Same query, same plugin, same versions, same dashboards, different steps, different result...

![image](https://user-images.githubusercontent.com/45430631/222651932-067514cb-ca42-4603-9d9c-6477b5d1542d.png)
![image](https://user-images.githubusercontent.com/45430631/222652040-6ec7eb2e-550d-4866-b7d9-e01044d96c5a.png)
![image](https://user-images.githubusercontent.com/45430631/222658945-250d3f92-873f-49dc-98ed-ae0e8dfd0f16.png)
![image](https://user-images.githubusercontent.com/45430631/222659073-1646e125-ee3b-44ac-ab4e-1c353a2da38b.png)
The query: SELECT "RE_T", "PF_T" FROM "modbus" WHERE ("name" = 'P11') AND $timeFilter

I copied the query from good result to a different panel and I've got bad data.

To get good data, I need to use builder, and then:
- select datasource (Influx)
- change format from 'Time series' to 'Table'
- remove Grouping (GROUP BY time($__interval) fill(null))
- select measurement
- set the "where" condition
- set field
- set another field (optionally)

To get bad data:
- use raw query mode:
-- create new panel; set plugin; set datasource (influx); to raw mode; paste query (from query builder that works); change from 'Time series' to 'Table'
--- Result: array of objects with only "Time" key, value key does not exist
---- [{"Time": 1677806879000}, {"Time": 1677806908000}]
-- create new panel; set plugin; set datasource (influx); change from 'Time series' to 'Table'; to raw mode; paste query
--- Result: array of objects with Time and mean keys:
---- [{"Time": 1677806908000, "mean": 3295.09 }, {"Time": 1677807057000, "mean": 3299.2}]
- use builder mode with grouping (alias doesn't work)

Query and result that works properly on 9.3.6 version but not on the latest:
![image](https://user-images.githubusercontent.com/45430631/222663217-f2a27652-5268-4376-9d2d-3708e478ecfc.png)

**Environment**:
Grafana OSS 9.4.3
Data source: InfluxDB 5.0.0
OS Grafana is installed on Windows Server 2012 r2, using IIS reverse proxy
User OS & Browser: Google Chrome | 110.0.5481.178
=> does not work on latest Firefox either
Plugin: Dynamic Text 3.0.0 From Marcus Olsson
=> I tested on 1.7 and 1.9 plugin version as well, no differences

**Comment by vincent-olivert-riera** [comment]
I wonder if this issue is related to this: https://github.com/grafana/grafana/pull/64058
