### ISSUE TITLE
[Bug report] Unable to display "overwrite" tags 

### ISSUE THREAD

**Issue by studentna123** [grafana/grafana#6410]
I'm currently using a Windows operating system, Grafana 3.1, and Grafanas API to automate making dashboards. I have noticed I can create a dashboard with tags and also overwrite a dashboard and the information inside the dashboard will update. The issue I seem to be having is that when I search for the dashboard in my dashboard list it does not display the updated tags. If I had previous tags in there it is keeping them or if I had none it displays none even though when I go into the settings of the particular dashboard it shows the new tags.

**Comment by torkelo** [comment]
unable to replicate this, so far thousands have used 3.1 without this bug so somtething strange is likely going on here. 

what database are you using (sqlite3, mysql, postgres)? can you show content of your dashboard_tag table? Also show the json your positing to the API when your updating the dashboard

**Comment by studentna123** [comment]
So the example dashboard name was alex_test1S and it originally had two tags. I updated the template(I don't think its relevant to the issue but I have attached it anyways) and proceeded to use python to push the json to Grafana. I then got the proper return code of 200 and then when I went and looked at my dashboard it was not updated. Today I looked(3 days later) and it was updated making me think that the issue is it needs time to update. To further prove my point I have repeated what I thought would produce the same error and got the same initial portion. Instead of trying to change the tag I instead deleted a dashboard and got the same error. I deleted my test dashboard and was still able to locate it in grafana, click on the dashboard and even though it redirected me to the url, it did show it was empty saying "Not found". I also noticed an issue(idk if I would consider it an actual issue though) when I was providing the URL path that involves the capital S. I used a capital S originally in the url name because I named it with a capital S, but URL is not case sensitive from what I have read. Is there a way to have your side factor that in when sending it so future users don't spend hours trying to figure out what the issue is? I have provided pictures(word document) of a successful deletion of my dashboard along with still being able to locate the dashboard when searching through my dashboard list. I can provide the actual python code but I have skinned it down to what is important for the discussion. 
[delete dashboard.txt](https://github.com/grafana/grafana/files/562782/delete.dashboard.txt)

[issues with grafana.pdf](https://github.com/grafana/grafana/files/562794/issues.with.grafana.pdf)

**Comment by torkelo** [comment]
Your probably using the api wrong, do you get the same issue when you delete dashboard from UI? UI is using same http api

**Comment by studentna123** [comment]
I'm skeptical about that since I'm receiving the proper 200 return along with getting the same issue when I delete the dashboard from the UI as well. It looks to me like it just takes a certain amount of time for it to be removed from the dashboard list, which could be because we have 100's of dashboards. I'll spin up a docker image and see what happens when I have less dashboards. Also I have attached a picture of what happens when I deleted the dashboard and go back to the dashboard and tried to delete it again. It registers that the dashboard is gone through the "Dashboard not found" when you try to do anything with it, but it is still allowing me to go to the dashboard and look at its characteristics. 
![dashboard](https://cloud.githubusercontent.com/assets/23109515/19900157/8d629986-a030-11e6-80aa-c3699fac521b.PNG)

**Comment by torkelo** [comment]
Very strange, of the many thousands of users of 3.1 none gave encountered this, which was why I was skeptical.  What sql database do you use for grafana db? 100 dashboards is not many, some have many thousands with quick milliseconds search and load times.  But you could test v4 nightly  if you think dashboard search is slow, it has been optimized recently
