### ISSUE TITLE
Alerting: Add VictorOps Notification Integration

### ISSUE THREAD

**Issue by ichekrygin** [grafana/grafana#6411]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

VictorOps is a hub for centralizing the flow of information throughout the incident lifecycle. Driven by IT and DevOps system data, VictorOps provides a unified platform for real-time alerting, collaboration, and documentation (https://victorops.com/)

Please add alerting notification support for VictorOps via POST to [REST API](http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/)

**Comment by ichekrygin** [comment]
PR: https://github.com/grafana/grafana/pull/6409

**Comment by ichekrygin** [comment]
Hi guys, just checking on the status of this?

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/6421 

Thank you for contributing!
