### ISSUE TITLE
Send alarm message error

### ISSUE THREAD

**Issue by valbendan** [grafana/grafana#6412]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

Git version: "b382d17e3495b1a36d6045af80b22713279e6d2a"
- What datasource are you using?

No data source.
- What OS are you running grafana on?

CentOS 6.0 (Maybe with slight modify).
Go version: 1.7.3
Node version: 4.6.0
- What did you do?

Send test alarm message.
- What was the expected result?

Got the test alarm message
- What happened instead?

The error log file have the log message:
t=2016-10-28T15:52:20+0800 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="template: alert_notification.html:239:5: executing \"alert_notification.html\" at <ne .State \"ok\">: error calling ne: invalid type for comparison"

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
could you show your panel json? also have you used Grafana v4 pre release build before git commit b382d17e3495b1a36d6045af80b22713279e6d2a? or was this a new rule created in this commit?

**Comment by valbendan** [comment]
![c464 tm](https://cloud.githubusercontent.com/assets/1709816/19803698/af64e328-9d3c-11e6-955b-665f8edacb69.png)

Click the "Send Test" button.

No git commit except I edit the conf/defaults.ini (but I think this is irrelevant).
It seems that the Grafana v4 pre release works well on my desktop(OpenSUSE 42.1, Go 1.7.3, node 4.6.0).

**Comment by torkelo** [comment]
try beta1 release
