### ISSUE TITLE
Upgrade to Grafana 9.4.x broke query A of every panel using GCP StackDriver

### ISSUE THREAD

**Issue by UnrealCraig** [grafana/grafana#64130]
**What happened**:
We upgraded from Grafana 9.3.1 to 9.4.3
Many panels using stackdriver broke.
Panels with only 1 query get "No Data" and red error.
Panels with multiple queries only lost results for query A, queries B & C still get correct results.
It seems every query A has an erroneous "AND" appended to it which causes invalid queries to be sent to stackdriver.

![Extra AND breaks stackdriver in GF 9 4 3](https://user-images.githubusercontent.com/16457598/222719841-4c23bc2c-59e2-4ae0-b503-2fc785583b06.png)
![JSON model showing broken stackdriver configuration](https://user-images.githubusercontent.com/16457598/222720129-aca06847-e3da-428f-976d-68dce9acad0a.png)
![Screenshot 2023-03-03 at 13 14 43](https://user-images.githubusercontent.com/16457598/222720345-3c9ae4bc-0120-44ea-806a-7e8be105013c.png)

**What you expected to happen**:
Everything should continue to work

**How to reproduce it (as minimally and precisely as possible)**:
Try the upgrade

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: stackdriver (Google Cloud Monitoring) 9.4.3 by Grafana Labs
- OS Grafana is installed on: Ubuntu (official Docker image)
- User OS & Browser: Not applicable

**Comment by bossinc** [comment]
I am not able to reproduce this issue. When you remove the ANDs and save, does it add the ANDs back after refreshing?

**Comment by whuut** [comment]
Same happened to us with apt upgrade from 9.3.2 to 9.5.1.

> When you remove the ANDs and save, does it add the ANDs back after refreshing?

For us, removing the erroneous AND fixed the panel.

But we also had panels with 3 queries showing "No Data" anymore because the "Filter" expression was empty, as well as the "Service" and "Metric name" field. So basically, the whole query definition was gone. All other fields, like "Project" or the whole "group by" and alias line at the bottom, were left intact.

**Comment by aangelisc** [comment]
Hi @saifulwebid, apologies for the delayed response. Is this the case if you migrate to 10.x+?

**Comment by saifulwebid** [comment]
Hi @aangelisc. We don't know, as we haven't migrated our instances to 10.x+ yet. Should it be solved on that version? Can we see the corresponding logic that does the "migration" part on 10.x+?

**Comment by UnrealCraig** [comment]
@aangelisc your reproduction steps are not for this issue.
9.4 does not experience this issue when importing dashboards; it only happens when upgrading a pre-9.4.3 installation to 9.4.3 (and probably newer 9.x builds)
I have not tried a pre-9.4 x >>> 10.x as all 10.x installations I've tried started with newer versions of 9.x or were fresh installs.

Main point: Importing dashboards != upgrading a Grafana instance (which includes automatic migrations to existing dashboards etc)

**Comment by aangelisc** [comment]
@UnrealCraig my apologies I mistyped in my comment. I created a dashboard in 9.3.0 and upgraded to 9.4.x and opened the dashboard. The migration seemed to work fine and I did not have the additional filter shown in the original screenshot. I also attempted this from 9.3.0 to 10.0.0 and that was also fine.

**Comment by UnrealCraig** [comment]
@aangelisc Understood.

Considering #63491 plus how old 9.4.3 now is, then this issue should probably be closed.

**Comment by aangelisc** [comment]
Agreed, if you're still experiencing this issue in a newer version of Grafana please open another issue referencing this one. Thanks all!
