### ISSUE TITLE
Glue: Pagination for Correlations page

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#64144]
### Background

In theory users may have thousands of correlations. If that really happens we may need to add extra filtering/search capabilities but for now we just need to make sure the UI won't crash with too many correlations on the screen.

### Requirements ###

High level: _Implement pagination for correlations table_

#### Technical details

* API should contain `TotalCount`, `PerPage` and `Page` and accept `Page` as GET param (similar to query history and administration pages)
* UI should display paged result using pagination buttons: https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-pagination--with-pages
* Add it to Explore, then review with Design System Squad how to promote it (Please create a follow up ticket about making pagination part of grafana ui)
* If interactive table's client side sorting does not work well with pagination, we should disable sorting and create a separate ticket to deal with sorting and pagination.

**Comment by gelicia** [comment]
The backend portion of this is done, in #65241
