### ISSUE TITLE
repeated panels are not displayed when dashboard is loaded from URL

### ISSUE THREAD

**Issue by calestyo** [grafana/grafana#64170]
**What happened**:

Based on a panel from https://grafana.com/grafana/dashboards/1860-node-exporter-full/ I've set up a fresh dashboard, that repeats the selected (and copy&pasted) panel from Node Exporter Full for a multi value variable (with the repeat variable being the host - so effectively I just print one panel for n hosts).
Just as described here: https://community.grafana.com/t/selection-presets-for-multi-value-varables/83105

That works just fine, when I go into the panel and actually click and select (multiple) variable values (or "All").<br>
For each of them a separate panel is generated with the e.g. CPU values for the respective host.

It also changes the URL, appending a `&var-node=hostname` for each of the selected hosts (or a single `&var-node=All` if "All" is selected).

Problem is, if I copy&paste such URL, e.g. one with `?orgId=1&var-node=host1.example.org:9100&var-node=host2.example.org:9100` it does not work, but rather shows me just one panel (and not even for any of the hosts given in the URL, but simply for the first one that would be in the websites drop down list).

**What you expected to happen**:
I'd expect it to select the hosts (respectively multiple variable values) just as given in the URL.

**How to reproduce it (as minimally and precisely as possible)**:

I've created the dashboard just as I've described in a question at: https://grafana.com/grafana/dashboards/1860-node-exporter-full/

Then select a number of hosts from the drop down, copy the URL and open it in a new tab.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian
- User OS & Browser: Debian / Firefox
- Grafana plugins: based on https://grafana.com/grafana/dashboards/1860-node-exporter-full/

Thanks,
Chris.

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @calestyo 

i'm forwarding your question to the dashboard squad

**Comment by calestyo** [comment]
Hey.

Actually, I have to rescind my report... when now doing the same, it works.

No idea why it didn't work before, cause I haven't really changed anything in the meantime (no apache/prometheus/grafana config changes... and at best very minor changes to the dashboard).

Anyway,... sorry for the noise... closing the ticket now.

Cheers,
Chris.
