### ISSUE TITLE
LOKI: Ad hoc filters are not working for ingeter values

### ISSUE THREAD

**Issue by aishyandapalli** [grafana/grafana#64172]
Ad hoc filters with integer values are being treated as string and query is failing with the below error

`syntax error: unexpected STRING, expecting BYTES or NUMBER or DURATION`

For example, if add `requestTime = 365` as an adhoc filter for Loki datasource, it's being treated as string and appending `requestTime = '365'` which fails the query.

- Create a dashboard
- Add a panel with Loki datasource
- Add an adhoc filters with Loki datasource
- Add an integer adhoc filter and we can see the query failing

- Grafana version: v9.1.x
- Data source type & version: Loki datasource

**Comment by tonypowa** [comment]
hello @aishyandapalli 
thank you for creating this issue

i am forwarding this issue to the observability logs squad for review

**Comment by aishyandapalli** [comment]
Hey Thanks for a quick reply @tonypowa

**Comment by ivanahuckova** [comment]
Hello @aishyandapalli could you please provide us with `Query results from the inspect drawer (data tab & query inspector)` and  `Panel settings can be extracted in the panel inspect drawer JSON tab` and also what query are you running?

**Comment by aishyandapalli** [comment]
@ivanahuckova This is the query from the query tab 

`"sum(count_over_time({_namespace_=\"<namespace>\", _schema_=\"<schema>\", operation=~\"<operation>\"} | logfmt | requestTime>`10` [$__interval]))"`

From the above query, `requestTime` is the adhoc filter that we added and the value `10` is given as integer but it's taken as a string which is giving the below error

`parse error at line 1, col 4156: syntax error: unexpected STRING, expecting BYTES or NUMBER or DURATION`

**Comment by aishyandapalli** [comment]
Data tab keeps loading but couldn't find any information

**Comment by ivanahuckova** [comment]
@aishyandapalli I was able to reproduce. Ad hoc filters with `>` and `<` operators should not be wrapped with quotes/backticks. 
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/30407135/226347767-56cd4b11-08fb-491f-b4ed-c80c3c202d9a.png">
