### ISSUE TITLE
Cloudwatch: Variables not being interpolated in expression when Expression query is active

### ISSUE THREAD

**Issue by idastambuk** [grafana/grafana#64176]
**What happened**:
The variables in code editor  are not being interpolated when expression query is added.  It works when using the builder mode of the query editor - the issue is only with the editor in code mode.
The reason for this is [a recent change in code](https://github.com/grafana/grafana/pull/57921/) whereby the expression field is no longer replaced from the ExpressionDatasource.
We need to add the "expression" field [here](https://github.com/grafana/grafana/blob/254577ba568d8010dcc96446e788866d618c96c8/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L99) in order to get it working again. 
Also, `sqlExpression` should probably not be checked for multi, and this function should look more like [this one](https://github.com/grafana/grafana/blob/254577ba568d8010dcc96446e788866d618c96c8/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts#L178)

**What you expected to happen**:

Variables in the query should be replaced with values. 

**How to reproduce it (as minimally and precisely as possible)**:

1. create a Cloudwatch query using a template variable with the query editor in code mode
2. add an expression and run the query
3. observe that the variable is not being replaced in the request anymore

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: 9.4.1
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by fridgepoet** [comment]
Maybe related? https://github.com/grafana/grafana/issues/63735
