### ISSUE TITLE
Alertmanager include image not working

### ISSUE THREAD

**Issue by OlegShal** [grafana/grafana#64193]
While using docker grafana with this env vars:
```
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_UNIFIED_ALERTING_ENABLED: "true"
      GF_ALERTING_ENABLED: "false"
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
      GF_FORCE_MIGRATION: "true"
```
on grafana:8.1.0 all works fine, sharing screenshot on dashbord and "include image" in contact point BUT! on grafana:9.1.0 or 9.4.6 sharing screenshot on dashbord is fine, but there is no option "include image" at all, can't debug it cause it's not an error, option is just do not exists

**Comment by vincent-olivert-riera** [comment]
> on grafana:8.1.0 all works fine, sharing screenshot on dashbord and "include image" in contact point BUT! on grafana:9.1.0 or **9.4.6**

Grafana 9.4.6 has not yet been release. I guess you mean 9.3.6.

> sharing screenshot on dashbord is fine, but there is no option "include image" at all, can't debug it cause it's not an error, option is just do not exists

This problem has been discussed in the past. Support for attached panel screenshots on (Slack) notifications was added on 9.4.0. Read this thread: https://github.com/grafana/grafana/issues/58872#issuecomment-1322566515 (it starts with Legacy Alerting by ends with Unified Alerting, so read it until the end).
And have a look at this PR (which is also linked in the above thread): https://github.com/grafana/grafana/pull/59163

**Comment by nonamef** [comment]
I have a similar setup to the above and also have this issue for Grafana 9.4.3. I can see the screenshot get generated in the logs, but I never see it in Slack.

```
logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:08.460370632Z level=debug msg="Requesting screenshot"
logger=rendering renderer=http t=2023-03-08T22:08:08.476110193Z level=info msg=Rendering path="d-solo/XXX/test-alarms?from=now-1h&orgId=1&panelId=14&to=now"
logger=rendering renderer=http t=2023-03-08T22:08:08.491083741Z level=debug msg="calling remote rendering service" url="http://grafana-image-renderer.grafana.svc.cluster.local:8081/render?XXX-FULL-URL"
...
logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:11.320388925Z level=debug msg="Took screenshot" path=/var/lib/grafana/png/cYKiH8NrqVsxxx.png
logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:11.327530598Z level=debug msg="Saved image" token=xxxxxxd83-05b1-EXAMPLE-TOKEN
```
I looked at #59163, but it looks like the code has been rewritten agin for https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/slack.go. I don't see in the logs that the image is being sent or has failed.

**Comment by vincent-olivert-riera** [comment]
> I have a similar setup to the above and also have this issue for Grafana 9.4.3. I can see the screenshot get generated in the logs, but I never see it in Slack.
> 
> ```
> logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:08.460370632Z level=debug msg="Requesting screenshot"
> logger=rendering renderer=http t=2023-03-08T22:08:08.476110193Z level=info msg=Rendering path="d-solo/XXX/test-alarms?from=now-1h&orgId=1&panelId=14&to=now"
> logger=rendering renderer=http t=2023-03-08T22:08:08.491083741Z level=debug msg="calling remote rendering service" url="http://grafana-image-renderer.grafana.svc.cluster.local:8081/render?XXX-FULL-URL"
> ...
> logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:11.320388925Z level=debug msg="Took screenshot" path=/var/lib/grafana/png/cYKiH8NrqVsxxx.png
> logger=ngalert.image rule_uid=XXX org_id=1 dashboard=XXX panel=14 t=2023-03-08T22:08:11.327530598Z level=debug msg="Saved image" token=xxxxxxd83-05b1-EXAMPLE-TOKEN
> ```
> 
> I checked out #59163, but it looks like the code has been rewritten agin for https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/slack.go. I don't see in the logs that the image is being sent or has failed.

I guess @grobinson-grafana, who wrote the PR to fix the issue, could confirm if it's working or not.

**Comment by nonamef** [comment]
I was using webhooks and now have updated it to use bot tokens. It is now working as expected, thanks for the comment.
On a side note: Using **test** on the contact point  did not work with an image, even though **Dashboard UID**and  **Panel ID** were included.

**Comment by Knud3** [comment]
I hope this helps someone with this issue https://github.com/grafana/grafana/issues/58872#issuecomment-1462666895

**Comment by joys1006** [comment]
Hi, I'm using Grafana version 9.5.2, but I couldn't find the 'include image' option in the notification settings. Has it not been added yet?

**Comment by Knud3** [comment]
> Hi, I'm using Grafana version 9.5.2, but I couldn't find the 'include image' option in the notification settings. Has it not been added yet?

You won't find it.

Include `capture = true` to `[unified_alerting.screenshots]` in `grafana.ini` and include `Dashboard UID` and `Panel ID` to alert rule details.

Check my comment for full details: https://github.com/grafana/grafana/issues/58872#issuecomment-1462666895

**Comment by JohnnyQQQQ** [comment]
We are closing this for now. Feel free to open a new issue if you still face problems with the latest grafana versions.
