### ISSUE TITLE
fixed scale for singlestat sparklines

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#6419]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.1.1-1470047149
- What datasource are you using?
  Prometheus
- What OS are you running grafana on?
  Linux
- What did you do?
  Multiple singlestat with sparklines, each with a percentage
- What was the expected result?
  Being able to have singlestat sparklines have all the same scale
- What happened instead?
  Singlestat sparklines show trends over time but each with its own scale

At Wikimedia Foundation we are using singlestat and sparklines to show CPU utilization across many clusters of machines, to get a better sense of what's going on it'd be nice to have sparklines all with the same scale, in this case 0 -> 1. See also attached screenshot.

thanks!

![image](https://cloud.githubusercontent.com/assets/93906/19817307/f5bf75fa-9cff-11e6-84fa-004babbb99ed.png)

**Comment by torkelo** [comment]
this is fixed
