### ISSUE TITLE
Old graph panel does not pass tracing headers

### ISSUE THREAD

**Issue by GiedriusS** [grafana/grafana#64197]
**What happened**:

After https://github.com/grafana/grafana/pull/60301, I have expected always to see these headers. However, I have noticed that some "old" visualizations don't pass those headers to the backend. Most notably, `Graph (old)` does not pass `x-dashboard-uid` but passes some of the other ones like `x-panel-id`. I know that it is a legacy visualization however, most of the panels still use that visualization here, and that kind of defeats the purpose of my change.

My guess is that there are multiple ways of sending a request to the backend in TypeScript code however I haven't had enough time to dig into it and find where the headers are added. If someone would point me to that place then I could try opening up a pull request with the fix.

**What you expected to happen**:

To see `x-dashboard-uid` header passed in requests made by `Graph (old)` visualization.

**How to reproduce it (as minimally and precisely as possible)**:

- Open Grafana > 9.3.0
- Open the network tab in your browser
- Open up a panel with `Graph (old)` visualization
- Check the request to `/query` and see that there is no `x-dashboard-uid` header
- Switch the panel's visualization to the new `Time series` and check the `/query` request again
- See that `/query` request got `x-dashboard-uid` header

**Anything else we need to know?**:

**Environment**:
- Grafana version: > 9.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by tonypowa** [comment]
hi @GiedriusS 

thanks for for creating this issue

based on the referenced [PR](https://github.com/grafana/grafana/pull/60301) , i am forwarding this issue to the back-end squad for review

**Comment by tolzhabayev** [comment]
Since we are in the process of migrating more and more users away from the Graph panel we will not invest more time into this issue.

**Comment by GiedriusS** [comment]
@tolzhabayev maybe there are some plans on when the old graph plugin will be removed in favor of the new one?
