### ISSUE TITLE
9.4.1 - Cannot create user after removing default org

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#64218]
**What happened**:
After upgrade to 9.4.1 i cannot create new users on Grafana, due to "Organization Not Found" error. This does not work from UI and from Terraform Provider for the same reason.

I am attaching the details from the request and a screenshot confirming existence of multiple organizations

![image](https://user-images.githubusercontent.com/47415312/223106272-fb592cbf-6ae4-4534-ad3f-1a6f5d2c6afb.png)

![image](https://user-images.githubusercontent.com/47415312/223106396-7dddd513-b8b0-48ab-843b-a53aaef5536e.png)

![image](https://user-images.githubusercontent.com/47415312/223106745-221a9da2-cc25-41a1-af95-5de5be5a5cd4.png)

![image](https://user-images.githubusercontent.com/47415312/223106833-70dbc534-7da0-4159-b5e7-a951fce442f8.png)

![image](https://user-images.githubusercontent.com/47415312/223106872-826727fd-3637-4a16-a3b0-799523c8d169.png)

**What you expected to happen**:
User creation to be successfull
**How to reproduce it (as minimally and precisely as possible)**:
Create a new grafana instance, create a new organization, delete the Main Org. with ID "1", try to create a new user.
**Anything else we need to know?**:

Grafana has PostgreSQL attached as storage.

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: Unimportant
- OS Grafana is installed on: Ubuntu 22.04 
- User OS & Browser: Edge
- Grafana plugins: Basic plugins only
- Others: PostgreSQL backend, no Main Org. (ID 1)

**Comment by UnrealCraig** [comment]
You need to reconfigure the default org to whichever new org you wish to use; the setting is called `auto_assign_org_id`

**Comment by Vimao** [comment]
This is a really confusing implementation for some fringe cases like mine, where i migrate an existing by hand deployment to code.

This creates a situation for me where i create an organization by code, and only after that i will know the Org_ID that i will want to auto_assign (because some orgs were already created and deleted, and Grafana incrementing the Org_ID), so i need to change the setting from code and reboot the instance. 

I kind of understand why it is like it is, but it's still confusing.

**Comment by mellieA** [comment]
@Vimao there is a feature request tracking interest in this: 

https://github.com/grafana/grafana/issues/12119

This other issue had some helpful context I wanted to share: 
 
https://github.com/grafana/grafana/issues/46666#issuecomment-1416204632 comment: 

> it is not possible to create any resource until the organization is created. Currently, it is not possible to provision organizations, and it is tracked at https://github.com/grafana/grafana/issues/12119
