### ISSUE TITLE
Advise file provisioning users to migrate their files to use the new expression UIDs

### ISSUE THREAD

**Issue by alexmobo** [grafana/grafana#64214]
We need to let our users know in the file provisioning documentation to update their provisioning files to use the new expression datasource UID __expr__ instead of -100.

**Comment by GrafanaWriter** [comment]
@brendamuir - would you please take a look?

**Comment by brendamuir** [comment]
Hey @alexmobo can you provide me more context on this?

**Comment by brendamuir** [comment]
@alexmobo has this been done?

**Comment by alexmobo** [comment]
> @alexmobo has this been done?

AFAIK, it hasn't been done

**Comment by grobinson-grafana** [comment]
@brendamuir lets fix this together! 🙂

**Comment by brendamuir** [comment]
Updated here https://grafana.com/docs/grafana/next/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules
