### ISSUE TITLE
"Grouping to matrix" transform breaks "Convert field type" and footer sum

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [grafana/grafana#64226]
**What happened**:

In a table panel, when the datasource query results are formatted using a `Grouping to matrix` transform, the cell values are converted to the string type for one reason or the other.

Nevertheless, trying to convert said cell values back to `Numeric` using a `Convert field type` transform will fail and throw an error:

![Screenshot 2023-03-06 at 14 29 25](https://user-images.githubusercontent.com/4224802/223125851-d9106c44-520f-4b4a-a8ab-2148d0781b7b.png)

**What you expected to happen**:

I would expect the value to be converted to `Numeric` and the `Total` footer aggregation to be calculated instead of concatenating the cell values as strings.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a table panel
2. Query a data source where the cell value is numeric
3. Use a `Grouping to matrix` transform
4. Follow up with a `Convert field type` transform with data type `Numeric` on the cell column specified in the grouping stage

If you look at your console, you will see an error with the message: `s.replace is not a function`.
Additionally, if you enable the table footer feature and set the aggregation to be `Total`, the result will be the concatenated string values instead of the sum of all values.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Google Chrome on OSX Apple Silicon
- Grafana plugins: N/A
- Others: -

**Comment by tonypowa** [comment]
hi @Mickael-van-der-Beek 

:wave: Thanks for creating this issue

could you please copy and paste all relevant data using the panel --> more --> get help workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

**Comment by Mickael-van-der-Beek** [comment]
@tonypowa I did find the issue in the end.

This is due to NULL values not being correctly handled by the transform.

I will close the issue for now.
