### ISSUE TITLE
issue in terraform when deleting contact point

### ISSUE THREAD

**Issue by romkimchi1002** [grafana/grafana#64229]
**What happened**:
I am using terraform to manage alerts in grafana, I encountered a bug,
I got this error while running terraform apply:
status: 500, body: {"message":"contact point 'XXX' is currently used by a notification policy","traceID":""}

**What you expected to happen**:
I expected the notification policy resource to be updated before the contact point is deleted

**How to reproduce it (as minimally and precisely as possible)**:
create a contact point
create notification policy that uses the contact point
delete both contact point and the policy that uses the contact point

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- OS Grafana is installed on: ubuntu
- Others: grrafana terraform module version: v1.35.0

**Comment by mellieA** [comment]
@romkimchi1002 can you share more about how you're managing the resources (which API or provisioning files) you're using to delete the contact point and notification policy?

**Comment by romkimchi1002** [comment]
i found the same here
https://github.com/grafana/terraform-provider-grafana/issues/769
ill follow up there
