### ISSUE TITLE
Glue: Track clicking on a correlation data link

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#64223]
### Background

We added tracking for split view, but it doesn't show the full picture of how correlations are used. We'd like to track how often a data link that is clicked was configured by correlations.

### Requirements ###

High level: _Track correlations clicks_

#### Technical details

To narrow down clicks originating from Explore we can wrap [splitOpenFn](https://github.com/grafana/grafana/blob/v9.4.3/public/app/features/explore/utils/links.ts#L136) to additionally provide a tracking event, e.g.:

```typescript
onClickFn: () => {
  if (link.configOrigin === DataLinkConfigOrigin.Correlations) {
    reportInteraction('correlations_clicked');
  }
  splitOpenFn?.();
},
```

We also need to add `origin` property to `DataLink` interface to indicate where the link was created with possible options:

```typescript
enum DataLinkConfigOrigin {
  Datasource = 'Datasource',
  Correlations = 'Correlations',
} 
```

We need to set the origin when a data link is created out of correlation settings: https://github.com/grafana/grafana/blob/v9.4.3/public/app/features/correlations/utils.ts#L37

**Comment by gelicia** [comment]
Draft PR pointing to log line branch available here https://github.com/grafana/grafana/pull/64720
