### ISSUE TITLE
provide the current backend-traceID to the frontend

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#64245]
it would be very useful if the frontend (in browser code) would receive the current traceId in the http-response of a datasource request:
- we could show the current traceId in error-messages, allowing the users to easily look up the trace for the error
- we could also provide this info for non-error-messages (perhaps somewhere in the query inspector)

questions:
- is it always one or zero traceIds for 1 ajax-request? can somehow 2 or more traceIds "happen"?

**Comment by marefr** [comment]
> is it always one or zero traceIds for 1 ajax-request? can somehow 2 or more traceIds "happen"?

At most once

**Comment by gabor** [comment]
it seems we already do it for "error" cases: https://github.com/grafana/grafana/blob/c006df375a3a6056f9cbeeaf2f28f87ce86823a2/pkg/api/response/response.go#L82-L90

i tried to modify that code to always set a http-header with the traceId, but .. it worked for non-datasource-requests, but datasource-requests did not get the traceId.

**Comment by marefr** [comment]
> i tried to modify that code to always set a http-header with the traceId, but .. it worked for non-datasource-requests, but datasource-requests did not get the traceId.

What if you add the header somewhere here (below)?
https://github.com/grafana/grafana/blob/e4d591fc0161ed42d703b46052540eb5ddbe4a86/pkg/middleware/middleware.go#L37

**Comment by gabor** [comment]
> > i tried to modify that code to always set a http-header with the traceId, but .. it worked for non-datasource-requests, but datasource-requests did not get the traceId.
> 
> What if you add the header somewhere here (below)?
> 
> https://github.com/grafana/grafana/blob/e4d591fc0161ed42d703b46052540eb5ddbe4a86/pkg/middleware/middleware.go#L37

that worked, thanks 👍

**Comment by gabor** [comment]
i'll work on a PR that does this (and also the frontend part), and will post it here for feedback, if that's fine with the backend-squad.

**Comment by gabor** [comment]
@tolzhabayev sorry for the confusion here, i moved this issue to the observability-logs-squad, there's already a PR to fix this at https://github.com/grafana/grafana/pull/64903 , which will be merged soon (got approved by backend-squad too).

i hope this is acceptable.
