### ISSUE TITLE
SMTP TLS

### ISSUE THREAD

**Issue by ric79** [grafana/grafana#6425]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  v3.1.1 (commit: a4d2708
- What OS are you running grafana on?
  Centos7
- What did you do?
  I configured SMTP in this way:

```
[smtp]
enabled = true
host = smtp.mycompany.it:25
user = MYCOMPANY\XYZ
password = pass
;cert_file =
;key_file =
skip_verify = true
from_address = testautomation@mycompany.it

[emails]
welcome_email_on_sign_up = true
```

From logs, I get:

```
t=2016-10-29T09:48:11+0200 lvl=eror msg="Async sent email 0 succeed, not send emails: riccardo.russo@mycompany.it err: 530 5.7.1 Client was not authenticated%!(EXTRA []interface {}=[])"
```

In http://x.x.x.x:3000/admin/settings I can confirm those values are ok. Maybe is it something related to tls? For example, here there is the working config for smtp in my gitlab:

```
# SMTP server  
gitlab_rails['gitlab_email_enabled'] = true  
gitlab_rails['gitlab_email_from'] = 'testautomation@mydomain.it'  
gitlab_rails['gitlab_email_display_name'] = 'testautomation'  
gitlab_rails['smtp_enable'] = true  
gitlab_rails['smtp_address'] = "smtp.mydomain.it"  
gitlab_rails['smtp_port'] = 25  
gitlab_rails['smtp_user_name'] = "MYCOMPANY\XYZ"  
gitlab_rails['smtp_password'] = "pass"  
gitlab_rails['smtp_domain'] = "mydomain.it"  
gitlab_rails['smtp_authentication'] = "login"  
gitlab_rails['smtp_enable_starttls_auto'] = true  
gitlab_rails['smtp_tls'] = false  
gitlab_rails['smtp_openssl_verify_mode'] = 'none'  
gitlab_rails['smtp_ca_path'] = "/etc/ssl/certs"  
gitlab_rails['smtp_ca_file'] = "/etc/ssl/certs/ca-certificates.crt"  
```
- What was the expected result?
  I thinks that you are forcing TLS. My SMTP require smtp_tls to false. If I'm right, you should provide a flag in grafana.ini
- What happened instead?

**Comment by bergquist** [comment]
**530** is the error code for authentication required.
Could you please try using` MYCOMPANY\\XYZ` instead of `MYCOMPANY\XYZ`

**Comment by ric79** [comment]
Hello

Tried to change as you wrote

`t=2016-11-02T09:29:53+0100 lvl=eror msg="Async sent email 0 succeed, not send emails: riccardo.russo@mydomain err: 530 5.7.1 Client was not authenticated%!(EXTRA []interface {}=[])"
`

On web interface, now I have double "\\"
![2016-11-02_093243](https://cloud.githubusercontent.com/assets/6887824/19921690/651da290-a0df-11e6-8f18-fd029f68ed94.png)

**Comment by bergquist** [comment]
@ric79 is this still not working? does the password contain a `#` or `;` char?

**Comment by ric79** [comment]
Hello, the password contains "-"
Can be a problem?
