### ISSUE TITLE
Unrecognized character escape

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#6426]
Good morning, 
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana 3.1.1 (and tested with Grafana 4.0.0-pre1)
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Docker (grafana/grafana)
- What did you do? Trying to display graph with field name containing \ (backslash).
- What was the expected result? Display graph with field name containing \ (backslash).
- What happened instead? Error like this : **"Unrecognized character escape 'letter'.."**

This is my template : 
![templating1](https://cloud.githubusercontent.com/assets/23166349/19851268/51c91752-9f5d-11e6-9796-401679369a19.png)

This is the result : 

![result2](https://cloud.githubusercontent.com/assets/23166349/19851508/9613732a-9f5e-11e6-9a43-f2aa8b659269.png)
![result1](https://cloud.githubusercontent.com/assets/23166349/19851512/991d7c14-9f5e-11e6-92ac-26f880c2f683.png)

This is the conf loaded from Elasticsearch : 
![json1](https://cloud.githubusercontent.com/assets/23166349/19851604/0d92abfa-9f5f-11e6-9694-2403e5aabf2d.png)

Thank you for your help.

**Comment by torkelo** [comment]
Please test grafana 4.0 nightly build, think this is fixed in master

**Comment by ChamMach** [comment]
Thank you for your reply. But I tried with the nightly build and I've the same error.

**Comment by marefr** [comment]
@ChamMach have you tried this lately using a recent Grafana version?

**Comment by torkelo** [comment]
think this is fixed
