### ISSUE TITLE
legend error when alias contains tag value and the value contains '|' on opentsdb dashboard

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#6427]
![selection_003](https://cloud.githubusercontent.com/assets/8777671/19853143/80a4d9e0-9fa2-11e6-84fd-8925b2b3fc3e.jpg)

**Comment by torkelo** [comment]
You need to upgrade OpenTSDB, in i think 2.3 or after that they added ability to match series to queries, without that OpenTSDB feature grafana cannot match series to query reliably
