### ISSUE TITLE
UI prompts saving dashboard to "General" folder even if user doesn't have access

### ISSUE THREAD

**Issue by mure** [grafana/grafana#64270]
**What happened**:

I have a user that only has Editor privileges to certain folders. It's role is Viewer for the whole organization. When creating and saving a dashboard, the default folder is General, even though the user can't save to that folder.

https://user-images.githubusercontent.com/9257800/223274846-b6cfd82f-38ca-4c42-b94a-ca1da89c6f82.mp4

**What you expected to happen**:

The user should not see the General folder as an option when saving a dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a user with Viewer permissions in the org.
2. Create a new folder and give the user Edit permissions to it. 
3. Login as that user and then try to create and save a new dashboard.

**Anything else we need to know?**: All of our users have this permissions set up and frequently get confused by this issue.

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: n/a
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS / Firefox
- Grafana plugins: n/a
- Others:

**Comment by IevaVasiljeva** [comment]
Hi @mure, thanks for reporting the issue and providing reproduction steps!

As @mellieA said above, we're aware of it and tracking it internally, but I'll leave this external ticket open so we can update you on the progress here.

We're currently working on a large folder-related project, which might change the way `General` folder is used. Therefore we'll hold off on fixing this until we have some more clarity on the future of the `General` folder, but I'll make a note to update this issue once we get there.
