### ISSUE TITLE
Graph > Axis > unit "percent (0.0 - 1.0)" does not make sense.

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6429]
percent is by very definition a number between 0 and 100.

**Comment by bergquist** [comment]
But the result of the calculation is mostly around 0.0 -> 1.0 ex 33/66 == 0.5 == 50%

I think the use case for having both 0.0 -> 1.0 and 0 -> 100 makes sense but there might be a better description for it.

**Comment by torkelo** [comment]
Well that unit is pretty self explanatory to me, show a value of 0-1 as percentage (which as you said is 0-100). Why did you find it confusing, I mean there are other more straight forward percentage units

**Comment by torkelo** [comment]
Oh, forgot to ask,  do you have a better name suggestion?

**Comment by Dieterbe** [comment]
ah so now I understand.. :  what this option does is actually convert a number to a percentage.
It is the only option in the units menu where the name of the "unit" in the menu (some of them are not actually units but that's a different story) means **convert *to* this unit**, as opposed to **the data is in this unit** which is what all the other options do.
E.g. any other option, let's say Watt or Bytes means "this data is in W/B". if the number is 5 it will say 5W or 5B and if the number is 5000 it will say 5kW or 5kB.
The "percent 0-100" option also means "this data is a percentage", 5 is displayed as 5%. and 5000 is displayed as 5000% (you could show it as 5k % to make it easier on the eyes, btw)

but the "percent (0.0 - 1.0)" option effectively means *please convert this number to a percentage*.
Grafana will process the data and turn it into a percentage (and display it as a percentage).

**Comment by torkelo** [comment]
Yes, but percentage is extremely commonly represented as 0-1, especially popbabilities

**Comment by Dieterbe** [comment]
a probability is a number between 0 and 1 yes, but this is not a percentage.
Maybe you should call the option "probability (0-1) to %" for reasons i explained above.
