### ISSUE TITLE
Trying to display graphs with multi-value option activated.

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#6432]
Good afternoon,
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana 3.1.1 (and tested with Grafana 4.0.0-pre1 + nightly)
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Docker (grafana/grafana)
- What did you do? Trying to display graphs with multi-value option activated.
- What was the expected result? Display one or more graph.
- What happened instead? Grafana displays nothing or almost.

This is my template : 
![templating2](https://cloud.githubusercontent.com/assets/23166349/19858300/3ff9d7b8-9f81-11e6-82df-0747be5bb296.png)

This is the result when I try with one value : 
![result3](https://cloud.githubusercontent.com/assets/23166349/19858336/5ab20058-9f81-11e6-9119-2da539d3ed08.png)

And now, this is the result when I try with the multi-values option activated : 

![result4](https://cloud.githubusercontent.com/assets/23166349/19858432/ae4af7ba-9f81-11e6-872b-fe474201427a.png)

![result5](https://cloud.githubusercontent.com/assets/23166349/19858434/b120f39a-9f81-11e6-8331-bcc6fd27f42e.png)

Thank you for your help.

**Comment by torkelo** [comment]
Multi value variable only works when filtering, not when used in metric aggregation or bucket aggregation
