### ISSUE TITLE
Cloudwatch: Ui bug in template variables

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#64339]
**What happened**:
Log Group Prefix input field is too long on certain screen sizes:
![Screenshot 2023-03-07 at 11 25 45 AM](https://user-images.githubusercontent.com/6620164/223485330-72416701-9bd7-426d-bb94-b748b18f04e6.png)

**Environment**:
- Grafana version:  I see it in main, I think it's been around a while, at least 9.4

**Comment by natejsimonsen** [comment]
What page are you seeing this bug?

**Comment by ashutosh887** [comment]
I would like to work on this Issue
@natejsimonsen

**Comment by natejsimonsen** [comment]
Go for it!

**Comment by khushijain21** [comment]
I'd like to work on this issue - if you can direct to the file location

**Comment by ashutosh887** [comment]
Yes @natejsimonsen even I'd posted to work on it if you can guide me to the component/issue

**Comment by sarahzinger** [comment]
Hey folks, anyone is welcome to submit a PR and the team will review. No need to "assign". The issue is located on the Variable Editor Page in the cloudwatch plugin. If you look for "log group prefix" in our repo you should be able to find the component

**Comment by iSatVeerSingh** [comment]
@sarahzinger Please, can you take a look at this?
