### ISSUE TITLE
2 issues with summarize(1d) and stacked bar charts

### ISSUE THREAD

**Issue by jeromegit** [grafana/grafana#6433]
- [x ] Bug report

I'm using Grafana 3.1.1 with Graphite on CentOs 2.6.
I'm using the following data query:
   aliasByNode(summarize(XYZ.US.sql.exec_per_fe_type.*.shares:5m, '1d', 'sum', false), 4)
in order to capture the daily sum of some interval metrics (every 5 minutes).
It works great except for 2 things:
   1. there's s disconnect between the legend title (2016-10-30, in red) vs the x-axis value (10/31 in yellow). The yellow is the correct date. See attached image below.
   2. more importantly, when I zoom in to only show today, hovering shows me the values but no chart is being displayed.

![image](https://cloud.githubusercontent.com/assets/552382/19865513/cb7e3cd4-9f59-11e6-9492-1508fb85d680.png)

Please help.
Thanks!

**Comment by torkelo** [comment]
please include the timestamps returned by your Graphite query, you can find the raw data response from Graphite by opening chrome dev tools, network tab, look for graphite /render request
