### ISSUE TITLE
[Docs] Add note about downloading specific plugin using the CLI

### ISSUE THREAD

**Issue by unixninja92** [grafana/grafana#6434]
The third party histogram plugin on grafana.net was recently updated to support grafana 4.x.x, but this broke compatibility with grafana 3.x.x. I recently updated this plugin on my 3.x.x grafana install and now the plugin no longer works and there is no way to revert to the previous version of the plugin. It would be nice if the grafana cli either let you specify the version of the plugin you want to install or only install the latest version of a plugin that supports your version of grafana (the new version of the plugin is listed as requiring 4.x.x).

**Comment by DanCech** [comment]
Specifying the version to install is already supported in master

**Comment by unixninja92** [comment]
Ok, I had only checked [here](http://docs.grafana.org/v3.1/plugins/installation/)

**Comment by DanCech** [comment]
You can manually install the earlier version by downloading it manually, download the zip file from https://grafana.net/plugins/mtanda-histogram-panel/download?version=0.1.5 and extract it into your data/plugins directory, then restart grafana.
