### ISSUE TITLE
Alerting: Orphan rules are scheduled but not queryable through main API regardless of permissions

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#64357]
**What happened**:

Orphaned rules (rules whose folder does not exist) are allowed, and are even scheduled correctly and will continue to execute.

However, there's no way to access these rules through the main API. This is because all API endpoints first do a folder lookup for RBAC checks. If the folder does not exist the route immediately returns a 404 and will not proceed. For the endpoints that fetch all rules across folders, orphaned rules get excluded from the results.

This means you end up with rules that are running, consuming server resources and potentially notifying you, but it's impossible to see them or edit them or delete them. It's annoying, especially if the rules are firing, and users get the impression that their data is deleted.

We should investigate adding a special scope or separate action for orphaned rules. Or, alternatively, we could allow orphaned rules to be queried if you have `rules:read` in any scope. This is preventing the UI from being able to show orphaned rules in a clean way - it cannot fetch them.

Right now the only way to see these rules is the provisioning API, but that's a separate thing and is not used by the UI.

**What you expected to happen**:

I expected to be able to get rid of (or edit) my orphaned rule as a server administrator.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create orphaned rules through any means. One way is to update UID of folder.
2. Be an administrator
3. Try to access those rules. You can't.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by tstibbs** [comment]
Possibly related: if you use the API to create an alert rule but don't specify a folderUID, the response suggests that the rule has been created but the rule isn't visible through the API or UI.
