### ISSUE TITLE
Panel does not display error

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#64365]
**What happened**:

My datasource returned e500 but panel displays No data

<img width="1596" alt="image" src="https://user-images.githubusercontent.com/327717/223575324-b484e3e7-cde7-40b4-82a8-cbad598ed08a.png">

**What you expected to happen**:

There's no way to distinguish between error (e.g. e500) and empty data response

**How to reproduce it (as minimally and precisely as possible)**:

Make datasource throw error, panel does not show any error

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: https://grafana.com/grafana/plugins/simpod-json-datasource/ 0.6.1
- OS Grafana is installed on: macos/debian
- User OS & Browser: chrome

**Comment by tonypowa** [comment]
thanks for creating this issue @simPod 

in your case, how are you making the error happen?

Also please try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) to debug as well.-

**Comment by simPod** [comment]
I realised it's because of the way datasource handles errors. Thanks!
