### ISSUE TITLE
An unexpected error happened in trace view

### ISSUE THREAD

**Issue by dacevedo12** [grafana/grafana#64366]
**What happened**:

Expanding tags or process causes a crash

![Peek 2023-03-07 18-42](https://user-images.githubusercontent.com/29694570/223580879-41fd2b5c-861c-45bf-b04d-1f4c8b83454e.gif)

**What you expected to happen**:

Show tags without crashing

**How to reproduce it (as minimally and precisely as possible)**:

This happenes in AWS managed grafana with a simple x-ray datasource

**Anything else we need to know?**:

Amazon controls the version of the plugins and the version of grafana itself. There's no possibility for the users to change it.

**Environment**:
- Grafana version: 8.4.7
- Data source type & version: Xray data source from AWS data sources v1.8.0
- OS Grafana is installed on: unknown
- User OS & Browser: elementary OS 6.1, Google Chrome

**Comment by dacevedo12** [comment]
Sorry, I can't seem to find the `get help` button in the traces visualization. The only way I can access it is via a query in "Explore", so it's not a panel I added into my dashboard.

**Comment by iwysiu** [comment]
Hi @dacevedo12 ! can you send a screenshot of the query instead then? (with any sensitive information blocked out of course)

**Comment by dacevedo12** [comment]
there isn't much to show here... it's just a basic query by trace id in the "explore" tab. I get there by clicking the trace id link in the trace list table (https://grafana.com/grafana/plugins/grafana-x-ray-datasource/)

![image](https://user-images.githubusercontent.com/29694570/224147448-faac3954-99e3-4eda-a380-1862f4d62466.png)

**Comment by iwysiu** [comment]
Hi @dacevedo12 , thanks answering! I haven't been able to reproduce the error yet. Are you sure that the x-ray plugin version was 1.8.0? I don't think we released a 1.8.0 version.

**Comment by dacevedo12** [comment]
AWS data sources 1.8.0 includes AWS x-ray data source, not the one from grafana labs.

With X-Ray 2.1.0 (grafana labs) the exact same error happens

**Comment by dacevedo12** [comment]
I was able to gather more info
```
react-dom.production.min.js:216 ReferenceError: useStyles2 is not defined
    at zt (KeyValuesTable.tsx:120:18)
    at rs (react-dom.production.min.js:157:137)
    at Wi (react-dom.production.min.js:267:460)
    at Sc (react-dom.production.min.js:250:347)
    at kc (react-dom.production.min.js:250:278)
    at wc (react-dom.production.min.js:250:138)
    at hc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ho (react-dom.production.min.js:122:325)
```
![image](https://user-images.githubusercontent.com/29694570/224191317-2c210a17-3b8e-4d9b-a443-23740c631f86.png)

props passed to that component:
```
{
    "data": [
        {
            "key": "name",
            "value": "myapp"
        },
        {
            "key": "hostname",
            "value": "1.2.3.4"
        }
    ]
}
```

Maybe this is a case of amazon installing an incompatible version? Not sure whether useStyles2 is available in grafana 8.4.7

**Comment by iwysiu** [comment]
Hi @dacevedo12 thanks for your patience! I've talked to AWS about it and they're working on a fix for it.

**Comment by dacevedo12** [comment]
Fixed, thank you!!
