### ISSUE TITLE
Annotation table in Grafana grows beyond established limits

### ISSUE THREAD

**Issue by JoiKKo** [grafana/grafana#64374]
**What happened**: 
The annotation table of the Grafana database is growing beyond the established limits.

**What you expected to happen**:
That annotations are deleted when they exceed the established limit and do not accumulate.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Prometheus, ElasticSearch
- OS Grafana is installed on: Kuberentes through the helm chart
- User OS & Browser: Chrome, Firefox, Safari
- Grafana plugins:
- Others:

Configuration:

[alerting]
concurrent_render_limit = 8
enabled = false
max_annotation_age = 15d
max_annotations_to_keep = 100000
[annotations]
cleanupjob_batchsize = 20000
[annotations.dashboard]
max_age = 6M
max_annotations_to_keep = 15
[annotations.api]
max_age = 6M

Query:

SELECT COUNT(*) FROM annotation;

269707

**Comment by tonypowa** [comment]
👋  thanks for creating this issue @JoiKKo 

could you share what is the limit for "`max_annotations_to_keep =`" under [`[annotations.api]`](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#max_annotations_to_keep-1) ?

>SELECT COUNT(*) FROM annotation;
>269707

considering the limits in your config, i am wondering if we can distinguish which of those 269k + annotations are alerting annotations, dashboard annotations and api annotations 

as for the alert annotations, i know you can get how many there are by calling this [api endpoint](https://grafana.com/docs/grafana/v9.4/developers/http_api/annotations/#find-annotations):  `api/annotations?type=alert` 


in the meantime, i will forward this issue to the dashboard's squad for review

**Comment by JoiKKo** [comment]
Hi @tonypowa 

Thanks for your answer, the limit for "max_annotations_to_keep =" is 0.
I think most of the annotations are generated by alerts, I have tried to execute the command you indicate to the API and it returns common alerts, but it does not return an exact number.

Regards!

**Comment by wkshare** [comment]
I have a same issue.

**Comment by wkshare** [comment]
```
[alerting]
enabled = false
max_annotations_to_keep = 3000

[annotations]
cleanupjob_batchsize = 100

[annotations.dashboard]
max_annotations_to_keep = 3000

[annotations.api]
max_annotations_to_keep = 3000
```

```
# select count(*) from annotation;
 count
-------
 72319
(1 row)
```

**Comment by papagian** [comment]
> Hi @tonypowa
> 
> Thanks for your answer, the limit for "max_annotations_to_keep =" is 0. 

@JoiKKo 
zero [disables](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#max_annotations_to_keep-) annotation cleanup:
https://github.com/grafana/grafana/blob/982939111bad7b7a9ad27d5a208a21f681a7753b/pkg/services/annotations/annotationsimpl/xorm_store.go#L488-L494
you have to set it to a non zero value

**Comment by JoiKKo** [comment]
Hi @papagian 

Thanks for your answer! I have already modified it, could you help me with another question regarding the annotations? Is it possible to limit the annotations for a specific organisation?

Thank you very much.

**Comment by papagian** [comment]
> 

do you mean during cleanup deleting only annotations from a specific organisation? no

**Comment by papagian** [comment]
@wkshare can you check your logs for `failed to clean up old annotations` error messages? or if debug log level in on for `Deleted excess annotations` messages?

**Comment by danielthedm** [comment]
Closing as no response, please reopen if you have a follow-up.
