### ISSUE TITLE
[Feature request] Dot size graphs

### ISSUE THREAD

**Issue by asuwarnapati** [grafana/grafana#6439]
[ Dot size graphs] Feature request

Grafana 3.1.0
Data source : Elasticsearch
OS : rancherOS

I am trying to create a graph in which got multiple lines, where the second metric is represented by the dot size.

Example:

graph A (time series)
line 1 :contain server A's cpu util percentage
line 2: contain server B's cpu util precentage

I would like to add on memory metrics to that graph A, in the form of a dot size. The bigger the dot size represents the bigger memory.

line 1 : contain server A's cpu util percentage AND every data point will have vary dot size represents the memory percentage at that specific time.

line 2 : contain server B's cpu util percentage AND every data point will have vary dot size represents the memory percentage at that specific time.

Thanks.

**Comment by willguxy** [comment]
would like to follow up on this feature request. Any plan on implementing this in the near future?

**Comment by daniellee** [comment]
Not in the near future. Here is our [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md). 

A better description and an image to illustrate what a dot size graph might make this feature request more popular (it currently has no :+1: 's).

**Comment by BitonicEelis** [comment]
I am also very interested in this functionality. I want to visualize trades that occur on an exchange, and would like to make a graph where each trade is shown as a point whose y value is the trade price, and whose point size reflects the traded volume.

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
