### ISSUE TITLE
Datasource Onboarding: Possible flaky test in EmptyStateNoDatasource

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#64402]
As per the [latest build fail analysis](https://docs.google.com/spreadsheets/d/1eQzu8VYrfI1sZu_5H08cbCb892QH9x4fVjQSeKRxyCI/edit#gid=59750982), there's a test failure in EmptyStateNoDatasource.

more details about the failed test: https://drone.grafana.net/grafana/grafana-private-mirror/5484/2/6

**Comment by gelicia** [comment]
This code is shared responsibility between dashboards and Explore, if you pick up this task, please assign yourself to it so it doesn't get done twice.
