### ISSUE TITLE
[Feature Request] sum value of stacked graphs

### ISSUE THREAD

**Issue by pfmd86** [grafana/grafana#6440]
* **I'm submitting a ...**
- [x] Feature request

Hi,
I have an feature request for stacked Graph. 
It would be very helpful to show the sum value in tooltiop and optinal in legend.

![2016-11-01 08_03_09-grafana - game server phlupp org](https://cloud.githubusercontent.com/assets/8144485/19881899/f5ff79a4-a009-11e6-8d22-8dd3a11be858.png)

used version: Garafana v3.1.1 a4d2708

**Comment by jadrovski** [comment]
Want this feature ! :)

**Comment by gauravmakkar** [comment]
Is it fixed?

**Comment by sandynomad** [comment]
Interested in being able to display the "sum" of stacked values of a table. For the sum there is nothing to draw - just a "total" option under the last row of the table is required. (total only makes sense for "current"; for other values "min / max / average" is probably less useful.)

**Comment by sandynomad** [comment]
something like this:

![Screen Shot 2020-05-15 at 7 46 51 pm](https://user-images.githubusercontent.com/4227864/82075572-1ad40080-96e5-11ea-9aeb-c0dca71a7aad.png)

**Comment by thomas-kaltenbach** [comment]
+1

**Comment by skupjoe** [comment]
How is this not possible

**Comment by m-yosefpor** [comment]
@skupjoe 

It is actually possible in recent grafana versions.

1. Add Total:
Transform > Add field from calculation > Calculation Total

2. Hide total in stack series:
Overrides > Add field override > Field with Name = Total > Add override property = Stack series > off

You may want to optionally set opacity and line width to 0 for Total:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/47300215/135605897-ae60ebd0-adef-421d-a0b9-1b974893e85a.png">


The result:

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/47300215/135605822-53d1d472-a7e9-4bfb-b83b-5c43af1cbe65.png">


I think this issue can be closed.

**Comment by MKrabs** [comment]
For version 8.1.x, refer t othis > https://github.com/grafana/grafana/issues/40171#issuecomment-942127054

**Comment by WismaxX** [comment]
> @skupjoe
> 
> It is actually possible in recent grafana versions.
> 
>     1. Add Total:
>        Transform > Add field from calculation > Calculation Total
> 
>     2. Hide total in stack series:
>        Overrides > Add field override > Field with Name = Total > Add override property = Stack series > off
> 
> 
> You may want to optionally set opacity and line width to 0 for Total:
> 
> <img alt="image" width="399" src="https://user-images.githubusercontent.com/47300215/135605897-ae60ebd0-adef-421d-a0b9-1b974893e85a.png">
> 
> The result:
> 
> <img alt="image" width="1351" src="https://user-images.githubusercontent.com/47300215/135605822-53d1d472-a7e9-4bfb-b83b-5c43af1cbe65.png">
> 
> I think this issue can be closed.



> @skupjoe
> 
> It is actually possible in recent grafana versions.
> 
>     1. Add Total:
>        Transform > Add field from calculation > Calculation Total
> 
>     2. Hide total in stack series:
>        Overrides > Add field override > Field with Name = Total > Add override property = Stack series > off
> 
> 
> You may want to optionally set opacity and line width to 0 for Total:
> 
> <img alt="image" width="399" src="https://user-images.githubusercontent.com/47300215/135605897-ae60ebd0-adef-421d-a0b9-1b974893e85a.png">
> 
> The result:
> 
> <img alt="image" width="1351" src="https://user-images.githubusercontent.com/47300215/135605822-53d1d472-a7e9-4bfb-b83b-5c43af1cbe65.png">
> 
> I think this issue can be closed.

Hi, I'm new to using Grafana and I can't get this implementation to work for me. I'm trying to get the sum of three queries by querying the data in InfluxDB but instead I get the highest value it finds among the three queries. It's as if it doesn't perform the sum and instead returns the highest value. The behaviour is the same as when I select the Max option.
Thanks in advance.
