### ISSUE TITLE
Invite Users: Duplicate header

### ISSUE THREAD

**Issue by matejkubinec** [grafana/grafana#64417]
**What happened**:

Duplicate headers and descriptions on Invite Users page.

**What you expected to happen**:

Just one set of header/description should be visible.

**How to reproduce it (as minimally and precisely as possible)**:

1. Login as admin
2. Navigate to **Configuration** -> **Users**
3. Click the **Invite** button

**Anything else we need to know?**:

Screenshot:
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/32638572/223741410-0a225be2-0f52-4505-9006-06e068b3c18c.png">

**Environment**:
- Grafana version: 9.4.3
- OS Grafana is installed on: Docker (MacOS)
- User OS & Browser: MacOS Firefox

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @matejkubinec 

reproduced in 9.3.8

forwarding issue to the appropriate team
