### ISSUE TITLE
Library panel list no longer applies filter by folder after deleting library panel while filter is sill active

### ISSUE THREAD

**Issue by Grrrolf** [grafana/grafana#64418]
**What happened**:
Folder selection of library panels is lost after deleting a library panel after selection was made. The selection is still visible in the filter input form, but the resulting list shows all panels across all folder now.

**What you expected to happen**:
I would expect the panel overview/list keeps applying the folder filter.

**How to reproduce it (as minimally and precisely as possible)**:
* have multiple library panels stored in multiple folders.
* go to the library panels list
* filter on one folder
* delete a library panel

See this animating gif:
![library_panels](https://user-images.githubusercontent.com/10052794/223739407-e7f3a37f-cb9f-48ce-9a0a-e45c9d403239.gif)

**Anything else we need to know?**:

The **same behaviour shows** when using the **"filter by type"** filter.

**Environment**:
- Grafana version: 9.4.3 (open source) and 9.4.3 (Grafana Cloud)
- Data source type & version: n/a
- OS Grafana is installed on: 9.4.3 open source installed on intel mac - Grafana Cloud, OS unknown to me
- User OS & Browser: Brave/Google Chrome
- Grafana plugins: n/a
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @Grrrolf 
I’m forwarding this issue to the Dashboard squad

reproduced in OS Ubuntu - (Docker) - Firefox 110.0.1 (64-bit)
