### ISSUE TITLE
wrong lookup query on openTSDB when using templating with multi-select + nested

### ISSUE THREAD

**Issue by tomcfoglio** [grafana/grafana#6443]
Found a possible bug on grafana 3.1.0 and 3.1.1 running on centOS 7 using openTSDB 2.2 as datasource.

Note: I found an issue with the conditional query of the drop-downs when using template, the actual query for the time series works as expected.

I am using template in a dashboard with the following variables:

![variables](https://cloud.githubusercontent.com/assets/6042514/19894896/e3ee0696-a035-11e6-89fd-2518a6a3032b.png)

If Multi-Select **IS NOT** checked on the $server variable Grafana executes this query (the correct one)

`
/api/search/lookup?limit=3000&m=ps.jstat{jstat_instance=*,host=hearth1}
`

If Multi-Select **IS** checked on $server variable Grafana executes this query (the wrong one) which makes the instance drop-down empty.

`
/api/search/lookup?limit=3000&m=ps.jstat{jstat_instance=*,host={hearth1,hearth2}}
`

As far as I know, the correct query would be:

`
/api/search/lookup?limit=3000&m=ps.jstat{jstat_instance=*,host=hearth1,host=hearth2}
`

Thank you very much for your help!

**Comment by torkelo** [comment]
looks like templating format is not specified in the replace call 

here:https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/datasource.js#L247

@utkarshcmu something you can look at?

**Comment by utkarshcmu** [comment]
Verified, this is a bug. Will fix this asap!
