### ISSUE TITLE
PNG rendering (/render/dashboard-solo) has poor performance

### ISSUE THREAD

**Issue by dmartinpro** [grafana/grafana#6445]
* **I'm submitting a ...**
- [*] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB 1.0.2
- What OS are you running grafana on? Debian Jessie
- What did you do? Try to generate a PNG
- What was the expected result? something as fast as the dashboard is
- What happened instead? really long image generation: >10 seconds
- Architecture: ARMv7 (Raspberry pi 2)

The query is really simple (select a single value in influxdb, containing right now very few data)

Is there a way to boost performance for static image generation?

**Comment by bergquist** [comment]
PNG rendering spins up phantomJS in the background to render then image you have requested. So its expected to be kind of slow. I'm sure there are minor speed improvements to be found in the flow but nothing major.

**Comment by torkelo** [comment]
The performance has been greatly improved in v4 / master

**Comment by dmartinpro** [comment]
Hi, just tried 4.0 beta 2 and the performance is just the same (around 11 seconds for the exact same graph).
Can you develop if needed about the performance gain? Does it rely on a specific configuration?

**Comment by torkelo** [comment]
how long does the query take? Doing png rendering adds about 2-3 seconds for me (which is due to booting up phantomjs and loading grafana and then fetching data, then rendering the graph). 

So testing locally I get pngs back for panels in about 1-3 seconds.
