### ISSUE TITLE
XY Chart: X-axis formatting not impacted by Field Overrides nor Standard Options

### ISSUE THREAD

**Issue by chs820** [grafana/grafana#64462]
**What happened**:
It looks like overrides to format the data in our x-axis don't apply - for instance in the screenshot below, I'd love for the Population Growth to be a percentage, but it doesn't seem to be carrying through.

**What you expected to happen**:
As a user, I'd certainly expect Field Overrides to impact X-axis value formatting (though I totally understand why that's a departure from our usual panels...though I wonder how Bar Chart panels do this), and I somewhat would've thought Standard Options would've impacted the X-axis too.

**How to reproduce it (as minimally and precisely as possible)**:
https://play.grafana.org/d/_KUTfkjnk/gapminder-ish-hans-rosling?orgId=1&viewPanel=20

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/14276197/223822653-e87c6a7d-8d76-423a-aea6-cd9ec0ffa18e.png)

![image](https://user-images.githubusercontent.com/14276197/223822914-5a905cb1-dc33-46a5-ab6d-2b32d5e0e480.png)

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jasuade** [comment]
Hello @chs820, we have also noticed the same misbehavior when either applying **min/max** directly via Standard Option or via Overrides. The x-axis does not get the change and moreover, the Panel becomes unresponsive.

I was able to reproduce [locally in my instance](https://jarasudek8s.grafana.net/d/dbaefdb0-8275-4f16-97f9-13c2df9d4772/xy-panel-x-axes-standard-options?from=1682424000000&to=1686039828331&orgId=1).\

![image](https://github.com/grafana/grafana/assets/25328174/66734a1e-5643-429d-ae46-3e788676f005)

Please, let us know if there is a timeline for x-axis formatting fixes. Thank you!

**Comment by gefaila** [comment]
This affects me too and I've submitted a bug. However, it beats me why an X-Y chart doesn't just have separate fields for min-x, min-y, max-x, max-y that affect the specified axis.  This is how any other x-y plotter works.  How is a customer supposed to know that changing something called "Standard Options" will operate on the X or the Y axis.  
I think it needs to be designed to be used by people who are expecting intuitive behaviour that they'd expect from a charting application.  It looks like something as straightforward as setting limits on an axis has been mangled into something totally un-intuitive.

**Comment by leeoniya** [comment]
@jasuade @gefaila 

opened https://github.com/grafana/grafana/pull/70202 to hopefully suss out what we want to do going forward. the UX situation for sure could use some improvement, but also duplicating all the options that can already be handled with overrides doesnt feel great either (from a code complexity/maintenance/docs viewpoint).

**Comment by jasuade** [comment]
Thank you @leeoniya ! I understand the duplication part, but it would not be the same applying the 2 overrides as having the options for each axes? on the backend I mean.
I guess if it is too complex we can hold on and see if there is a strong need between many users.
