### ISSUE TITLE
XY Chart: Point color does not seem to be impacting the chart

### ISSUE THREAD

**Issue by shih-chris** [grafana/grafana#64463]
**What happened**:
I've tried passing Grafana both an rgb value, as well as a regular series value, but the Point color doesn't seem to be working. In this example, I'd want the selected country to be Purple, and the rest to be Grey (to replicate the panel in the body of the linked dashboard).

**What you expected to happen**:
I expected the color to either take as input a rgb value, or decide for me based on another regular column (e.g., [this is an example in altair](https://altair-viz.github.io/gallery/scatter_tooltips.html) that I like using in Python)

**How to reproduce it (as minimally and precisely as possible)**:
https://play.grafana.org/d/_KUTfkjnk/gapminder-ish-hans-rosling?orgId=1&viewPanel=20

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/14276197/223823850-cf75e70a-e7f1-46e5-bae7-2347ac924ec6.png)

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by martin3000** [comment]
I don't understand how colors work. I have got a time value for the x-axis, a temperature for the y-axis and a color for each point. But what does the color value mean, for example if it is 50? I does not seem to react to the tresholds because I guess the thresholds are for the y-value and not for the color value.

**Comment by coltspackers** [comment]
This is not solved. There are bugs in the XY Chart that make this panel type inconsistent in applying color. I have an XY Plot in one dashboard that colors beautifully, and another that's the exact same in another dashboard, that refuses to color no matter what you try.

**Comment by leeoniya** [comment]
new xychart should work correctly. we dont currently plan to add support for color strings in the data
