### ISSUE TITLE
Prometheus query builder does not keep its order

### ISSUE THREAD

**Issue by oneoneonepig** [grafana/grafana#64478]
**What happened**:

For a query like `count(node_systemd_unit_state{...} == 0)`, the query builder should display **Equal to -> Count**

![before save](https://user-images.githubusercontent.com/13197632/223913252-00c9713a-3ac3-4611-9969-d066f8390021.png)

After leaving the panel and re-opening the panel, the query builder shows **Count -> Equal to**. The actual query was the same as before

![after save](https://user-images.githubusercontent.com/13197632/223913354-350a011f-af84-47e9-88d2-64164aa40ea6.png)

**What you expected to happen**:

Although does not affect the actual query, Grafana should not re-order the query builder order in any way

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a query like `count(node_systemd_unit_state{...} == 0)`
2. Make sure the query builder is in correct order, **Equal to** then **Count**
3. Apply and close the panel, then re-open the panel
4. The query remains the same, but the query builder becomes **Count** then **Equal to**

**Environment**:
- Grafana version: v9.4.3
- Data source type & version: Prometheus v2.42.0
- OS Grafana is installed on: Docker CE 23.0.1 on Ubuntu 22.04 LTS
- User OS & Browser: Microsoft Windows 10 22H2, Chrome 110.0.5481.180

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @oneoneonepig 

reproduced behaviour in OS Ubuntu - (Docker) - Firefox 110.0.1  (even though i can't say whether it's unexpected or not)

in any case, i am sending this issue to the o11y metrics squad for review

**Comment by parthvnp** [comment]
I would like to contribute to a fix for this issue!

**Comment by parthvnp** [comment]
@tonypowa Is a fix still needed for this issue?

**Comment by tonypowa** [comment]
apologies @parthvnp  I totally missed your previous message

> Is a fix still needed for this issue?
@gtk-grafana  @grafana/observability-metrics
