### ISSUE TITLE
Dashboard import responses HSTS header even when disabled in configuration

### ISSUE THREAD

**Issue by oneoneonepig** [grafana/grafana#64486]
**What happened**:

The configuration `security.strict_transport_security` is disabled, most of the responses do not provide `Strict-Transport-Security` header.

![normal without hsts](https://user-images.githubusercontent.com/13197632/223961775-c6d39ed3-647f-4789-bca2-9ddf003ee61d.png)

But when we import a dashboard through id, the response replies with a HSTS header

- Request: `https://my-grafana-server:3000/api/gnet/dashboards/1`
- Response Header: `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

![with hsts](https://user-images.githubusercontent.com/13197632/223961841-b962b04f-d027-4ad5-ba38-94f26258cfba.png)

> Server name `my-grafana-server` and dashboard id `2` are placeholders

**What you expected to happen**:

When HSTS is disabled in configuration, no responses should provide HSTS header, since it is a one way configuration and you will have to wait until it expired, or remove it manually in `chrome://net-internals/#hsts`

**How to reproduce it (as minimally and precisely as possible)**:

On Grafana with configuration `security.strict_transport_security` unset or set to false, import a dashboard through id

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.4.3
- Data source type & version: Prometheus v2.42.0
- OS Grafana is installed on: Docker CE 23.0.1 on Ubuntu 22.04 LTS
- User OS & Browser: Microsoft Windows 10 22H2, Chrome 110.0.5481.180

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @oneoneonepig 

Reproduced on Ubuntu 22.04.2 - Grafana 9.3.8 (@ Docker 23.0.1) 

Forwarding issue to the Dashboards team (please reroute if needed)

**Comment by sakjur** [comment]
Thank you for the clear and precise bug report 🙏 I've proposed a fix for this in #67279.
