### ISSUE TITLE
Update documentation based on Microsoft and Google style guide suggestions

### ISSUE THREAD

**Issue by dugalp** [grafana/grafana#64480]
**What is the chore?**:

Review, merge, and apply the PR I submitted, https://github.com/grafana/grafana/pull/64367 to cleanup the documentation. Updates documentation to reflect correct English usage according to Microsoft and Google style guides for the word **on-premise** and replaces with correct usage in Grafana documentation.

**Is there anything else we need to know?**:

No

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @dugalp 

I will forward this issue to our Docs team

**Comment by GrafanaWriter** [comment]
Fixed by https://github.com/grafana/grafana/pull/69997
