### ISSUE TITLE
Alerting- Alerts not not meeting all conditions, still alerting.

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6449]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-1477649752pre1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubuntu 
- What did you do? Set multiple conditions for alert
- What was the expected result? That both conditions must be met to trigger alert.
- What happened instead? Alerts are being triggered by first condition only.

I am using the alerts for a temperature sensor.  Setting first condition to alert when above a certain temp.  Then setting another condition that the temp must be below a higher temp so that we can ignore a spike in temp that happens twice a day.  Alerts are being set off as soon as the first condition is met and ignoring the second.  I have tried every combination I can think of and still same result.  Not sure if I am just doing something wrong or if this is a bug.

![image](https://cloud.githubusercontent.com/assets/20861450/19930010/aa4363d0-a0dc-11e6-8eff-206821793948.png)

**Comment by bergquist** [comment]
@chipper110 Please click the test rule button and paste the logging.

**Comment by chipper110** [comment]
![image](https://cloud.githubusercontent.com/assets/20861450/19932024/ed59155e-a0e4-11e6-8af5-43c93d5df2ee.png)

**Comment by torkelo** [comment]
says firing false, and you can expand the logs and  see the metric data returned from your conditions

**Comment by chipper110** [comment]
![image](https://cloud.githubusercontent.com/assets/20861450/19932182/784360f2-a0e5-11e6-84b5-6f51c6b86875.png)

**Comment by chipper110** [comment]
Here is one that is firing as true even though only one of the conditions is met.

![image](https://cloud.githubusercontent.com/assets/20861450/19935348/21f567bc-a0f0-11e6-9c29-987de20d1c67.png)

**Comment by chipper110** [comment]
The Original now it is in alert with only one condition met.
![image](https://cloud.githubusercontent.com/assets/20861450/19936462/d8ada002-a0f3-11e6-8943-8a9a1f2adf5a.png)

**Comment by bergquist** [comment]
The bug is fixed and should be available for download shortly at grafana.org/builds

**Comment by torkelo** [comment]
As you can see your query return -129

**Comment by OverWorldD** [comment]
Yes, but why? With those settings it is supposed to look from now and back 10s right? The value has been well above -100 for quite some time, and it should not return -129. Most definitely not if its looking only 10s back from now(). Grafana timezone is set to browser based, but i have a feeling the alarm query looks at the wrong time. Its strange that my query produces a correct graph, correctly aligned in time but the same query used in the alarm function gives me this behavior.

**Comment by OverWorldD** [comment]
Yes, but my question is why :) at that point my values had been about -60, -70 for hours, so i dont understand why the function returns an average value of -129 based on the last 10minutes, except if it looks at the wrong part of the data.

**Comment by OverWorldD** [comment]
hmm... it seems for me it does not accept the time interval (the 2nd variable), no matter what I set it to it seems it just checks for average / min / max and so on over the whole query result.

**Comment by marefr** [comment]
@OverWorldD what datasource are you using? Seems to me you maybe using influxdb or a sql datasource and has forgotten to filter by time in your query.

**Comment by OverWorldD** [comment]
Yes! That might be it. I'm using MySQL and I have not managed to get the time filtering to work for my graph query because the time stamp is in UNIX time. I thought the alarm did its own query that is automatically timefiltered, but I see now how these two problems would be related. 

I have just asked for help here https://community.grafana.com/t/using-sql-timefilter/1686/16 regarding the time filtering.

Maybe the UNIX time is not working correctly with the alarms?

I have managed to get around this problem by using the last() function for the alarm instead of avg() as this works regardless of epoch, but it would be nice to get the filtering sorted.

Perhaps I simply should add a time column in the database that is "normal time" formatted. (I use Node Red to get the values into the db)
