### ISSUE TITLE
Alerting - OpenTSDB getting strange behavior and emails not sending 

### ISSUE THREAD

**Issue by bischofs** [grafana/grafana#6450]
* **I'm submitting a ...**
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana v4.0.0-pre1 (commit: 578507a)
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Ubuntu 16.04
- What did you do? Created new alerts
- What was the expected result? Get an email
- What happened instead? didnt

I created a simple alert and the alert never returns any values in the test button. It seems like it never really moves to the alerting state. Looking at the logs I also get ->
```

t=2016-11-02T14:35:16-0400 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=1 isDefault=true
t=2016-11-02T14:35:16-0400 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[test@test.com]
t=2016-11-02T14:35:26-0400 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp: i/o timeout"
```

![alerting](https://cloud.githubusercontent.com/assets/1606648/19942661/db2aa912-a10a-11e6-86bc-bf82a07b9398.png)

**Comment by utkarshcmu** [comment]
Please check you smtp settings in Grafana and smtp daemon. The logs itself tells you the error:

```
t=2016-11-02T14:35:26-0400 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp: i/o timeout"

```

**Comment by bischofs** [comment]
The email settings work as the test send sends an email

`t=2016-11-02T16:40:47-0400 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2016-11-02T16:40:47-0400 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[test@test.com]
`

**Comment by bischofs** [comment]
Also the "Alert State" is active 

![1](https://cloud.githubusercontent.com/assets/1606648/19946823/da5f6516-a11b-11e6-8b66-bf20dcd80d4a.png)

however most firings of the alert (every ten seconds) dont trigger anything

![2](https://cloud.githubusercontent.com/assets/1606648/19946841/e9a599a0-a11b-11e6-9a14-905dc675036f.png)

**Comment by utkarshcmu** [comment]
Grafana won't trigger anything if the state of the alert does not change. If the state of the alert was "Alerting" 19 mins ago, Grafana should have notified on the email 19 mins ago.

Just to give a shot again on alerting, change the threshold so that alert goes to OK state. Then the state will change and you should get an email. :)

**Comment by bischofs** [comment]
so `firing=false` implies no state change versus the alerting state is true?

**Comment by utkarshcmu** [comment]
Yes, firing=false means no alert will be fired whenever alert is checked the next time.

The state has to change for the notification to go out.

Also, i noticed that in the alert above that when there is no data points the setting is select to "Keep Last" so if there is no data coming for the specified time in the alert query , alert won't change its state and will still keep its last state.

**Comment by bischofs** [comment]
Ok I got it to switch to the "OK" state but I think just because I changed the no data points selection. I moved the data back into the threshhold but It wont flip over to "Alerting" state. Im guessing because my data is lagging behind "now" a bit but I set it to query for "max" value of the last minute (my data should be no less than a minute behind) so It should flip into the state. Not sure what I am doing wrong 

![4](https://cloud.githubusercontent.com/assets/1606648/19947592/33403068-a11f-11e6-8424-a5caebb165d0.png)

**Comment by bischofs** [comment]
Looks like it only changes state when i switch the "SET STATE TO" selector which is  implying that my queries aren't returning anything.

**Comment by utkarshcmu** [comment]
Yeah. So, can we close this issue or you still want to test more?

**Comment by bischofs** [comment]
I will close it for now and see what you guys come up with for the release version.
