### ISSUE TITLE
Alerting: Integration with HipChat

### ISSUE THREAD

**Issue by Gelob** [grafana/grafana#6451]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: Would love to see notification support for sending to HipChat via API v2.

**Comment by alexzorin** [comment]
Hi,

Anybody working on this? I will be needing it at $employer, so I've hacked together a branch to get things started.

Here it is: https://github.com/grafana/grafana/compare/master...alexzorin:hipchat_alerting

I'm not too keen on taking on the whole feature myself, so if anybody else wants to jump on (or is already doing it in parallel) that would be super.

It uses the v2 API to send an 'Application'-style card notification. 

Unfortunately I had to mess with Grafana a little bit so I could set `Content-Type` header in webhook request - sorry!

Here's how it looks in the client:

![screeny](http://i.imgur.com/UCveHZi.png)

**Comment by utkarshcmu** [comment]
I am working on it, soon there will be a PR, most probably in next 24 hours!

**Comment by dinoocch** [comment]
@alexzorin It'd be nice if we could send graphs as well. [This](https://gist.github.com/dinoocch/8d13401ad5745d1aaf51167b19394920) is some python code that I'm using to do something similar.  I haven't had a chance to poke at the grafana http alert code yet, but I believe the slack endpoint has this functionality (although slack presents a much more standard api...)

`https://api.hipchat.com/v2/room/{room}/share/file` endpoint per [the documentation](https://www.hipchat.com/docs/apiv2/method/share_file_with_room)

**Comment by alexzorin** [comment]
@dinoocch I agree, the graph would be nice. The icon in the screenshot is actually the graph, haha (but useless because it's just a thumb).

 I struggled to figure out how to do it in a single 'message'. There is a 'media'-style card where we could send the graph but then we cannot send the metrics data. 

`/share/file` can be sent with a message, but I am not sure whether it can be sent with a card.

**Comment by utkarshcmu** [comment]
I ll try to work on HipChat alerting here https://github.com/utkarshcmu/grafana/tree/alerting_hipchat
and will submit a PR asap.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/tree/alerting_hipchat is open. Please create Pull requests to that branch.

**Comment by jregovic** [comment]
<img width="791" alt="hipchatnot" src="https://cloud.githubusercontent.com/assets/1158525/22309965/20c6e9f0-e313-11e6-9621-529022d79648.png">

**Comment by jregovic** [comment]
I think I stuffed it on the pull request. Should I just redo the whole thing?

**Comment by lbrictson** [comment]
+1 for this feature!  Very excited

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/7484
