### ISSUE TITLE
Explore: Use number for panelIds when building query transaction

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#64515]
a `DataQueryRequest` has an optional field, `panelId` defined as a number: https://github.com/grafana/grafana/blob/46ab9e9252e48eba7f6c5acbd76cf94b55db9b6b/packages/grafana-data/src/types/datasource.ts#L510

when a request is created in explore-mode, it also gets a panelId value, but it is a string:
https://github.com/grafana/grafana/blob/46ab9e9252e48eba7f6c5acbd76cf94b55db9b6b/public/app/core/utils/explore.ts#L146-L148 (it's an UUID-ish string value).

this causes problems for consumers of `.panelId`, who assume it is a number.

(please note that this value is also sent in every backend-datasource-ajax-request, so the number of consumers is not limited to the javascript-in-browser)

**Comment by gelicia** [comment]
@gabor how many consumers are impacted by this? We're wondering this for prioritization purposes.

**Comment by Elfo404** [comment]
trying to wrap my head around this, it looks like `panelId` should only be used for tracking purposes (and maybe other things in dashboards). request cancellation (which i assumed was the usecase for `panelId`) should be based on `requestId` instead, given `panelId` is an optional property (like `dashboardId`) i think we should simply remove it altogether. Prometheus however bases query caching on top of it: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querycache/QueryCache.ts#L325 but 1) is it even a problem for Explore where query caching doesn't probably make much sense? 2) is basing the cache logic on `panelId` correct in the first place?

cc @grafana/observability-metrics

**Comment by gtk-grafana** [comment]
We need the panel ID to differentiate the query caches within a dashboard, so if that string is empty, the cache will still work as long as there is only a single query per dashboard Id. So if explore stops sending this string, the query cache should still work appropriately (although I'd like to test this), but we'll need a panelId or something else that differentiates queries in the dashboard still.
CC: @leeoniya

**Comment by leeoniya** [comment]
i think with the recent Show Me The Code hackathon we made additional (resource) queries from Explore to another DS. also with profiling/tracing we have separate queries for FlameGraph vs TimeSeries above it. i dont know if removing it is a good idea if it's possible for there to be more datasources/panels in the future. i think there is more risk in removing it than leaving it. cc @aocenas
