### ISSUE TITLE
Design System: add PageBanner as Alert/Banner in grafana-ui

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#64528]
**What is the chore?**:

- [ ] Figure out if PageBanner is shown only on the page it is requested on or in every page. If it is every page need to make a decision if we want to let everyone use this or if we need to be more strict.
- [ ] Add [PageBanner](https://github.com/grafana/grafana-enterprise/blob/37f2896da89e16357c75d3395bd7f7d0b3385bac/src/public/banners/PageBanner.tsx) (Cloud) to `grafana-ui` as `Banner`(Alert).
- [ ] Create documentation in Storybook.

**Is there anything else we need to know?**:
Expected hiccups for when the work starts (e.g. buttons styling is custom)

**Comment by staton-hyse11** [comment]
This is no longer needed. Cloud banner (PageBanner) wont be moving into grafana-ui
