### ISSUE TITLE
Alerting: Contact point name in edit page URL encoded

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#64530]
**What happened**:

When it displays the existing contact point name at the top of the edit page, that string appears incorrectly URL-encoded at the top of the page.

![2023-03-09-090930_1059x592_scrot](https://user-images.githubusercontent.com/8410871/224066711-970d3c24-4cac-4f32-859d-e1928c4ed6d3.png)

**What you expected to happen**:

I expected it to display "test #test"

**How to reproduce it (as minimally and precisely as possible)**:

1. Create any contact point with a special character. I used "test #test"
2. Edit the contact point
3. Look at the top of the page

**Anything else we need to know?**:

**Environment**:
- Grafana version:main
- User OS & Browser: firefox

**Comment by BitProcessor** [comment]
Note that the issue is also visible in the Webpage title

![image](https://user-images.githubusercontent.com/50638541/224152031-9815f2e2-73de-4705-8d00-9dd26cc8e356.png)

**Comment by soniaAguilarPeiron** [comment]
> Note that the issue is also visible in the Webpage title
Thank you @BitProcessor !, with this PR, this is also fixed.
<img width="256" alt="Screenshot 2023-03-10 at 10 58 24" src="https://user-images.githubusercontent.com/33540275/224286283-caf56dfe-61d4-4d4b-89a6-3452fd16c157.png">

**Comment by BitProcessor** [comment]
Looking good! 🚀
