### ISSUE TITLE
Saga - Toggletip [design]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#64558]
We need to build a Figma component for the rest of the team to leverage as needed.

**Comment by bruno-caldeira1** [comment]
@staton-hyse11 I've created a branch of the Dark theme Figma file with the component included. Let me know if that's ok or if I need to change anything. Thank you.

**Comment by staton-hyse11** [comment]
@bruno-caldeira1 last we spoke, there were some adjustments that needed to be addressed. How is the progress on those?

**Comment by bruno-caldeira1** [comment]
@staton-hyse11 I've finished all the changes and I'm doing some tests to make sure it works and does not break when changing the content. I will commit the changes on Monday. Thank you

**Comment by natydej** [comment]
Reviewed and ready to merge the latest updates made by @bruno-caldeira1:
- Removed auto-width version and kept a single option.
- Added a min-width element of 400px. 
- Added a content component that won't be able to be selected from the assets menu (added a "." at the beginning). 
- Small auto-layout fixes to prevent it from breaking when changing the content component."
