### ISSUE TITLE
Relative time override for templating

### ISSUE THREAD

**Issue by sradco** [grafana/grafana#6457]
* **I'm submitting a ...**
- [X] Feature request

- What Grafana version are you using?
3.1.1
- What datasource are you using?
Elasticsearch
- What OS are you running grafana on?
Red Hat Linux

I would like to have the option to have relative time override for templating.
So I can use the records in the data source, by the templats, regardless of the time period picked.

We have a data source that holds metadata/parent documents and we want to use the templating for filtering and display related timeseries/child metrics that are filtered eventually by the ids filtered by the templates.
This can simulate the parent-child relationship of Elasticsearch.

**Comment by torkelo** [comment]
closing this as it sounds like a duplicate of https://github.com/grafana/grafana/issues/4583
