### ISSUE TITLE
Unable to login to grafana behind traefik proxy after updating to latest version. Last working version 9.3.2

### ISSUE THREAD

**Issue by gathecageorge** [grafana/grafana#64571]
**What happened**:
After upgrading grafana to version 9.4.3 me and my colleagues are unable to login to grafana behind traefik proxy

**What you expected to happen**:
Expected that should login like normal. If a user is already logged in, they are not affected. But after log out, then the issue is seen

**How to reproduce it (as minimally and precisely as possible)**:
Setup grafana behind traefik proxy. You need to be logged out. Try accessing grafana url, you are redirected to login page but sees this error.
![image](https://user-images.githubusercontent.com/8780168/224175923-05f70b9b-8186-49ae-a375-ff60c355169d.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: normal grafana
- OS Grafana is installed on: Linux
- User OS & Browser: Am using Chrome (Version 111.0.5563.65 (Official Build) (64-bit)) and Edge (Version 110.0.1587.63 (Official build) (64-bit))  both latest versions
- Grafana plugins: none
- Others:

**Comment by yorickdowne** [comment]
In testing this works with Firefox 110.0.1 but break with Chrome.

It may be unrelated to proxy access.

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @gathecageorge 

I'm forwarding this issue to the Auth team for review

**Comment by yorickdowne** [comment]
We tested this with 9.4.7, issue persists

**Comment by gathecageorge** [comment]
New information: This issue is related to cloudflare and not grafana. A fix is available here https://github.com/grafana/grafana/issues/63934#issuecomment-1489934010
