### ISSUE TITLE
Alerting: Add rule message to slack when alert state is ok.

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6458]
* **I'm submitting a ...**
- [] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Why have we turned off alert rule message when state becomes OK for slack?

https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/slack.go#L74

In the message, we have "@channel" identifier which should be sent to the channel when the alert goes back to OK. :|

**Comment by bergquist** [comment]
Posting the complete message again feels to chatty. The purpose of the alert message is to give people ideas about why something is wrong and how to fix it. If that message is long it would be annoying to have it double posted in channels while talking to others.

Perhaps the slack notifier should have an extra field for highlighting people in channels etc. It would be possible to include the highlight part in every slack notification but only add the alert message when something is wrong.

**Comment by utkarshcmu** [comment]
Should I work on a PR to add this feature?

**Comment by bergquist** [comment]
@utkarshcmu great work :) as always!

**Comment by utkarshcmu** [comment]
@bergquist Thanks for being so responsive and the development is super quick! I appreciate it. 👍
