### ISSUE TITLE
can't delete/modify alerts when datasource is deleted

### ISSUE THREAD

**Issue by locomoco28** [grafana/grafana#64593]
**What happened**:

We set up a new Loki instance and wanted to delete the old datasource in Grafana and update the alerts. Deleting the datasource was successful, but we can't modify/delete and alerts as there's an error "datasource not found"

**What you expected to happen**:

Be able to modify the alerts with a new datasource or delete them

**How to reproduce it (as minimally and precisely as possible)**:

- start a grafana instance
  - e.g. in a docker container without persistence
    ```
    docker run -p 3000:3000 grafana/grafana
    ```
- log in and go into datasources
- Create a test data datasource
- Go into alerts
- Create an alert rule with test data datasource
- **Create another alert rule**
  - the bug only happens when you have more than 1 alert rule accessing the data source
- Go back into datasources
- Delete test datasource
- Create new test datasource (gets a new ID)
- Go back into alerts
- Try to modify or delete the alert
  - alert not found

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on: Kubernetes & locally on Docker
- User OS & Browser: Windows 10/Firefox
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
@locomoco28  thanks for creating this issue

Reproduced error in Grafana 9.4.3 - Ubuntu 22.04.2 LTS (Docker 23.0.1) 

error logs when trying to delete an alert

```
logger=ngalert.scheduler rule_uid=xLwocAa4k org_id=1 version=1 attempt=0 now=2023-03-13T14:01:00Z t=2023-03-13T14:01:05.025069593Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': data source not found"
logger=ngalert.sender.router rule_uid=xLwocAa4k org_id=1 t=2023-03-13T14:01:05.037817977Z level=info msg="Sending alerts to local notifier" count=1
logger=context userId=1 orgId=1 uname=admin t=2023-03-13T14:01:35.013004058Z level=error msg="invalid rule specification at index [0]: failed to validate condition of alert rule test2_: failed to build query 'A': data source not found" error="invalid rule specification at index [0]: failed to validate condition of alert rule test2_: failed to build query 'A': data source not found" remote_addr=172.17.0.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-03-13T14:01:35.013087043Z level=info msg="Request Completed" method=POST path=/api/ruler/grafana/api/v1/rules/tests_ status=400 remote_addr=172.17.0.1 time_ms=33 duration=33.718421ms size=167 referer="http://localhost:3000/alerting/l2ehc0-Vk/edit?returnTo=%2Falerting%2Flist" handler=/api/ruler/grafana/api/v1/rules/:Namespace
```


forwarding issue to alerting team (please reroute if needed)

**Comment by locomoco28** [comment]
Can you think of a workaround to (at least temporarily) resolve the issue @tonypowa ?
We silenced our alerts until we can reconfigure them, it'd be great if we could enable our alerting again.

**Comment by tonypowa** [comment]
okay i think i found a workaround 

you can update the alert rules via API. You can even update the datasource UID and overcome the error !


 1. get the JSON of the alert rule(s) [via endpoint](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-get-alert-rule)  `api/v1/provisioning/alert-rules/`
 
 note: the UID of the alert appears in the URL of the browser when editing the alert via UI

2. get the UID of the new [data source](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/) /api/datasources/name/TestData via endpoint `/api/datasources/name/TestData`

3. send [(PUT)](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-put-alert-rule) the JSON of the alert rule  to `/api/v1/provisioning/alert-rules/{UID}`

Note:

Once you update the alert rule via API, you won't be able to edit the API-provisioned alert rule from the Grafana UI.
In order to enable editing in the UI, add the `x-disable-provenance` header in your PUT request

the body of my PUT request with the new  alert rule `"datasourceUid"`

``` json 
{
    "id": 1,
    "uid": "BAVK0_-4z",
    "orgID": 1,
    "folderUID": "v2JP80a4k",
    "ruleGroup": "test",
    "title": "test333",
    "condition": "C",
    "data": [
        {
            "refId": "A",
            "queryType": "",
            "relativeTimeRange": {
                "from": 600,
                "to": 0
            },
            "datasourceUid": "tvK80la4k",
            "model": {
                "hide": false,
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "refId": "A"
            }
        },
        {
            "refId": "B",
            "queryType": "",
            "relativeTimeRange": {
                "from": 0,
                "to": 0
            },
            "datasourceUid": "__expr__",
            "model": {
                "conditions": [
                    {
                        "evaluator": {
                            "params": [],
                            "type": "gt"
                        },
                        "operator": {
                            "type": "and"
                        },
                        "query": {
                            "params": [
                                "B"
                            ]
                        },
                        "reducer": {
                            "params": [],
                            "type": "last"
                        },
                        "type": "query"
                    }
                ],
                "datasource": {
                    "type": "__expr__",
                    "uid": "__expr__"
                },
                "expression": "A",
                "hide": false,
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "reducer": "last",
                "refId": "B",
                "type": "reduce"
            }
        },
        {
            "refId": "C",
            "queryType": "",
            "relativeTimeRange": {
                "from": 0,
                "to": 0
            },
            "datasourceUid": "__expr__",
            "model": {
                "conditions": [
                    {
                        "evaluator": {
                            "params": [
                                0
                            ],
                            "type": "gt"
                        },
                        "operator": {
                            "type": "and"
                        },
                        "query": {
                            "params": [
                                "C"
                            ]
                        },
                        "reducer": {
                            "params": [],
                            "type": "last"
                        },
                        "type": "query"
                    }
                ],
                "datasource": {
                    "type": "__expr__",
                    "uid": "__expr__"
                },
                "expression": "B",
                "hide": false,
                "intervalMs": 1000,
                "maxDataPoints": 43200,
                "refId": "C",
                "type": "threshold"
            }
        }
    ],
    "updated": "2023-03-17T12:24:35Z",
    "noDataState": "NoData",
    "execErrState": "Error",
    "for": "5m",
    "isPaused": false
}
```

back to the UI i can see the update worked since the TestData datasource is present for alert test333

![image](https://user-images.githubusercontent.com/45235678/225908494-5b32c226-cfcd-43e1-9776-a9ed1b43ac6a.png)

good luck and let us know if it worked for you!

**Comment by locomoco28** [comment]
Thanks for the very helpful response. I got to replace the datasource, but I can't disable the provisioned state, the header doesn't seem to do anything.

I'm simply deleting the alert using the API as I have duplicate ones anyways (I previously had multiple Lokis for multiple K8s clusters, now I have a single Loki instance for all, so I can delete all alerts and keep just one and reconfigure it for multiple clusters :) )

**Comment by tonypowa** [comment]
the team has confirmed that the reason the header, `x-disable-provenance  `,  didn't work in the **update** was that the alert that you were modifying was not originally provisioned.  This is done to prevent having mixed provisioned status in the same rule group where some are provisioned and others aren't.  If you **create** an alert rule with the header, it can be used afterwards.

**Comment by locomoco28** [comment]
Ooh I see, that makes sense, appreciate it :)

I already simply deleted the affected alerts though and just got to set up new alerts with our new Loki source, deleted the old ones. Appreciate your assistance!

The issue stays open for the bug, right?

**Comment by tonypowa** [comment]
no problem @locomoco28 

> The issue stays open for the bug, right?

i believe so. You should hear from the team as soon as they can look into it ;)
