### ISSUE TITLE
Constant template values can no longer be changed without entering the templating menu

### ISSUE THREAD

**Issue by rbak1** [grafana/grafana#6459]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? master as of Oct. 10 (commit 519100f1bd50dbca749c7ca9f362070ba7da9839)
- What datasource are you using? Monasca
- What OS are you running grafana on? Ubuntu
- What did you do? Created a constant template, saved and reloaded dashboard, then attempted to click on the dropdown for the template to change the value.
- What was the expected result? In the past this has allowed users to enter their own value for the template.
- What happened instead?  No response in the browser, but an error message in the console.  See the error below.  Constant templates do not load a default 'options' value and so the dropdown is broken unless you update the template triggering updateOptions()

```
TypeError: Cannot read property 'slice' of undefined
    at Object.vm.show (value_select_dropdown.js?bust=1478189584081:31)
    at fn (eval at compile (angular.js?bust=1478189584081:NaN), <anonymous>:4:254)
    at expensiveCheckFn (angular.js?bust=1478189584081:15906)
    at callback (angular.js?bust=1478189584081:25885)
    at Scope.$eval (angular.js?bust=1478189584081:17682)
    at Scope.$apply (angular.js?bust=1478189584081:17782)
    at HTMLAnchorElement.eval (angular.js?bust=1478189584081:25890)
    at HTMLAnchorElement.dispatch (jquery.js?bust=1478189584081:5110)
    at HTMLAnchorElement.elemData.handle (jquery.js?bust=1478189584081:4918)
```

**Comment by bergquist** [comment]
The purpose of the constant template variable is not be changed by the user in the GUI. I think what you might be looking for is custom template variable. Which allows you to define one or many variable options.

**Comment by bergquist** [comment]
But error should OFC be handled much better :)

**Comment by rbak1** [comment]
My fix for this was merged a couple days ago so this can be closed.  https://github.com/grafana/grafana/pull/6460

For our use case custom templates weren't the right option either.  The goal was to have a dashboard that, without going out of your way into other menus, would load with a blank hostname (and therefore not waste time loading data). Then users could type hostname they wanted.  query type didn't work because you couldn't set no value, custom wouldn't work because we have far too many hosts to enter all of them by hand, and constant without this ability required people to understand the templating and how to navigate those menus.  From what I've seen of the upcoming adhost templates, those might be an option for us in the future.
