### ISSUE TITLE
Grafana 9.3.6->9.4.3 upgrade fails to provision dashboards with _ in their folder name

### ISSUE THREAD

**Issue by SuperMatt** [grafana/grafana#64603]
**What happened**: Tried to upgrade Grafana from 9.3.6 to 9.4.3 but it failed due to the following error message:

```
Error: ✗ *provisioning.ProvisioningServiceImpl run error: Failed to provision dashboards: failed to provision config foo_bar: Error 1062: Duplicate entry '1-0-foo_bar for key 'UQE_dashboard_org_id_folder_id_title'
```

Some investigation suggests that the provisioning fails when there is an underscore in the folder title. Thus `foo_bar` does not work, while `foo-bar` does.

**What you expected to happen**:

I expect this to keep working as before and continue allowing underscores in provisioning folder names.

**How to reproduce it (as minimally and precisely as possible)**:

Provision a folder with an underscore in the name

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by tonypowa** [comment]
hi @SuperMatt 
thank you for creating this issue

the following provisioning template worked for me okay.
```

apiVersion: 1

providers:
 - name: 'test'
   orgId: 1
   folder: 'folder_2'
   type: 'file'
   updateIntervalSeconds: 30
   options:
     path: /etc/grafana/provisioning/dashboards
```

how i tested it:

` docker run  -v ./my_grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards -p 3000:3000 -e GF_LOG_MODE=console  grafana/grafana`

```
logger=provisioning.alerting t=2023-03-13T16:57:04.392625056Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2023-03-13T16:57:04.39280853Z level=info msg="finished to provision alerting"
```

please share your provisioning file and we will have a look

**Comment by scottzhlin** [comment]
I encountered a similar situation where I got the same error when upgrading Grafana from v9.3.x to v9.5.0-xxx (main), but the difference is that my file name contains Chinese characters.

Error Details:
```
Error: × *provisioning. ProvisioningServiceImpl run error: Failed to provision dashboards: failed to provision config xxx_dashboards: can't provision folder "你好2" from file system structure: Error 1062: Duplicate entry '1-0-你好2' for key UQE_dashboard_org_id_folder_id_title'
```

**Comment by tonypowa** [comment]
thanks for your input   @SuperMatt  @scottzhlin 

i am not sure what is causing this so I will forward this issue to the dashboard squad for further review

**Comment by tonypowa** [comment]
thanks for giving visibility to others about how the issue is affecting you
let's wait to hear the team's feedback in #64595

**Comment by Joey777210** [comment]
@scottzhlin Maybe you encountered this issue? #66373 I'm working on it.

**Comment by tonypowa** [comment]
@SuperMatt 
it should have been fixed already
https://github.com/grafana/grafana/issues/64595#issuecomment-1486572162

if not, please feel free to reopen.
thank you
