### ISSUE TITLE
SimpleJson datasource does not indicate the provisioned state of 

### ISSUE THREAD

**Issue by Lroy** [grafana/grafana#64618]
**What happened**:
I successfully provisioned a SimpleJson datasource, but the datasource configuration display does not indicate the correct setting for skipTLSVerify.

**What you expected to happen**:
I expected the skipTLSVerify to indicate 'True'.

**How to reproduce it (as minimally and precisely as possible)**:
Create yaml file for datasource, set tlsSkipVerify to True.

**Anything else we need to know?**:
Datasource works without TLS, as expected.  This appears to be a problem with display of the flag.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: SimpleJson 1.4.2
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10
- Grafana plugins: SimpleJson
- Others:None
<img width="728" alt="Screen Shot 2023-03-10 at 9 49 02 AM" src="https://user-images.githubusercontent.com/290178/224349399-3101cd28-5c93-4f6a-9010-dea21c4c80eb.png">
<img width="570" alt="Screen Shot 2023-03-10 at 9 51 07 AM" src="https://user-images.githubusercontent.com/290178/224349418-6af4a7b1-5eca-4745-90e4-8add945d9083.png">

**Comment by tonypowa** [comment]
hi @Lroy 

thank you for creating this issue


could you share where you got that config template file? 
thank you!

**Comment by sympatheticmoose** [comment]
SImpleJson is deprecated in favour of [Infinity](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/)
