### ISSUE TITLE
Icon needed - corner grip

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#6461]
We need to create a proper corner grip for panel resizing. 

Currently we're using fa-signal, which is passable:

<img width="457" alt="screenshot 2016-11-03 23 07 38" src="https://cloud.githubusercontent.com/assets/2886187/19993214/5bde6494-a21a-11e6-9ea8-402481cdbcd0.png">

But we can easily add a new font to the grafana font and have it look much better. Propose something like this:
<img width="445" alt="screenshot 2016-11-03 23 07 42" src="https://cloud.githubusercontent.com/assets/2886187/19993230/70ffd6c8-a21a-11e6-9eca-608d4fb8eea3.png">

@bulletfactory can you lend a hand making this?

**Comment by torkelo** [comment]
and icon for the new panel `Alert List`

**Comment by bulletfactory** [comment]
This is all complete
