### ISSUE TITLE
influxdb / grafana network traffic sum

### ISSUE THREAD

**Issue by p0nts** [grafana/grafana#6462]
I seem to have a problem calculating interface traffic from multiple instances and sum them, the problem seems to be that with the check interval grafana is using sometimes it happens that not all values in the influxdb are already there which cause a drop in the graph.

Is there any possibility to let grafana query influxdb 5 minutes before the actual time? So for example at the time of 15:55 retreive metric values from influxdb from 15:50?

Or is there any other solution to this problem?

**To show an example:**

Here is a graph that is having the traffic drops:
http:///shot.xsnews.nl/stefan/1336c9706219d939.png

And here I added a count of the amount of metrics each run has, the total metric count should always be 18 but as you can see the yellow line is not constant and misses allot of metrics almost every run.
http:///shot.xsnews.nl/stefan/6a2fb60f9dc6baec.png

**Comment by bergquist** [comment]
You could set the timerange for the dashboard to `from: now-3h, to: now-5min`

**Comment by p0nts** [comment]
Thank you for your input, that unfortunatly only allows me to now show the last value in the graph. But this problem also affects the sum's in the history of the graph.

Also the now-5m option does not work when you use "GROUP BY time(5m)" because it will then just not show the latest measurement.

I need something for the whole time range, not only for the last metric.
