### ISSUE TITLE
bug: time in hover popup incorrect when other values are null

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6464]
see https://www.youtube.com/watch?v=KhgdcD3vvhk&feature=youtu.be

the timestamp when hovering over the data is incorrect, it it somehow affected by the presence of null values. when i transform null to zero, it works.

this is a recent 4.0-pre build

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/6946  (will be fixed soon in new graph panel)
