### ISSUE TITLE
after upgrading from 9.3.1 to 9.4.3 Time Series panel with  logarithmic and min=0 stopped rendering

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#64656]
**What happened**:
after upgrading from 9.3.1 to 9.4.3 Time Series pannels stopped rendering

**What you expected to happen**:
Time series should continue working after upgrade

**How to reproduce it (as minimally and precisely as possible)**:
Create time series dashboard with logartithmic scale and set min value (not soft min) to 0 

**Anything else we need to know?**:
<img width="1769" alt="Screen Shot 2023-03-12 at 12 00 52" src="https://user-images.githubusercontent.com/4352719/224537758-4cec1b93-1e8b-4201-ad28-2d55f6c36aec.png">
**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: debian
- User OS & Browser: Google Crhome Version 110.0.5481.177 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by vbichov** [comment]
we've ended up deleting and recreating the dashboard :(

**Comment by vbichov** [comment]
pannel json that reproduces the isssue
```
{
  "datasource": {
    "type": "prometheus",
    "uid": "blablabla"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "log",
          "log": 2
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "unit": "short",
      "min": 0
    },
    "overrides": []
  },
  "gridPos": {
    "h": 6,
    "w": 6,
    "x": 12,
    "y": 7
  },
  "id": 29,
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "desc"
    },
    "legend": {
      "showLegend": false,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "blablabla"
      },
      "editorMode": "code",
      "expr": "sort_desc(sum(rate(vm_promscrape_scraped_samples_sum{job=~\"vmagent-.+\"}[$__interval])) by (dc)\n+ sum(rate(vmagent_rows_inserted_total{job=~\"vmagent-.+\"}[$__interval])) by (dc)) ",
      "range": true,
      "refId": "A"
    }
  ],
  "title": "samples per DC",
  "type": "timeseries"
}
```

**Comment by leeoniya** [comment]
hmm, i think [the fix](https://github.com/grafana/grafana/pull/59758) missed the 9.4.3 cut-off, so should be in 9.4.4 or 9.4.5 (probably this week). you can try a nightly build if you'd like to verify: https://grafana.com/grafana/download/nightly?edition=oss

given that 0 is not a valid log scale limit, you should be able to work around this error in your version by setting the min to a power of 2 or power of 10, depending on if you use log2 or log10.

**Comment by leeoniya** [comment]
> Can this please be re-opened until the fix is actually released in an official release rather than a nightly?

we dont have the capacity to monitor these things manually. if there was a way to auto-close this upon release, then we would do that, but it's not a thing Github can do AFAIK. probably it's possible to set up some github-action to watch for labels/milestones but that doesnt exist today.

how would leaving this open help impacted users if they're unwilling to use a nightly? :thinking: 

the solution/work-around is simple: don't use an invalid log scale limit with log scales.

**Comment by ericmustin** [comment]
> how would leaving this open help impacted users if they're unwilling to use a nightly? 🤔

I've pulled in [the changes from the PR you mentioned above]( https://github.com/grafana/grafana/pull/59758 ) on our fork. For some organizational reasons it's not an option for me to to run beta/nightly's on production.

> we dont have the capacity to monitor these things manually

No worries, I don't have any expectations, if it's the policy to close when merged rather than released, that's fine, it's just easier to track if open. Cheers
