### ISSUE TITLE
UX: Revamped Keyboard shortcuts

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6465]
New keyboard shortcut lib has enable sequence style shortcuts. Also a new "hover" focus on panels allows for shortcuts applicable to panel being hovered. 

New Shortcuts (Please give feedback)

Global:
- `g h`  -> Go to home dashboard
- `g p` -> Go to profile
- `g a`  -> Go to alerting list
- `s s` -> Search starred 
- `f` -> open search

Dashbord shortcuts
- `d r` -> Refresh all panels
- `d s` -> Open dashboard settings 
- `t z` -> Zoom out dashboard time
- `t left` -> move time left
- `t right` -> move time right

Shortcuts for focused panel (hover)
- `e`  -> Toggles Panel Edit View
- `v` -> Toggles Panel View 
- `p r` -> Remove Panel
- `p s` -> Share panel 
- `r c` -> Delete focused row (row for focused panel)
- `r d` -> Delete focused row

Not sure what to do with the existing shortcuts like CTRL+H for hide controls, CTRL+O for toggle shared crosshair, CTRL+S save dashboard

Feedback on this issue would be great!

**Comment by Dieterbe** [comment]
* maybe we can make all global "go to X" start with g? open search would then be `g s` and search starred could be `g S` or `g *`
* refresh could be just `r`. not a lot of words start with `r` so we won't find a better use for it soon. plus it will be a common operation, deserving a single letter.
* we could also adopt vim-style. where `dX` deletes something. x could be r for row, p for panel. `sX` colud be for sharing panel or dashboard.

would it make sense to make these configurable? maybe in the server config, or perhaps better, in the users profile/config ?

**Comment by torkelo** [comment]
> maybe we can make all global "go to X". 

The thinking was that `g` should be used for navigation. so navigating (Going) to different pages. opening/giving focus to search is not navigation. github has only  `s` to give search focus. 

> refresh could be just r. 

Since we have rows I want to reserve `r` for row actions, and `p` for panel actions.

**Comment by daniellee** [comment]
Can we get a shortcut for search tagged? I use that much more often than starred. Maybe `s t`?

**Comment by torkelo** [comment]
<img width="691" alt="screen shot 2016-11-04 at 17 07 09" src="https://cloud.githubusercontent.com/assets/10999/20012854/38a40438-a2b1-11e6-858f-90d0dc25aa9a.png">

Latest shortcuts ^ (zoomed out modal to fit in screenshot)

**Comment by luke-powers** [comment]
I'd love to have the ability to configure them, or the ability to disable them, in the profile menu.

**Comment by torkelo** [comment]
@luke-powers maybe sometime in the far future :)

**Comment by torkelo** [comment]
<img width="787" alt="screen shot 2016-11-05 at 12 20 05" src="https://cloud.githubusercontent.com/assets/10999/20029646/387f905c-a352-11e6-80ec-4c964f6bd29d.png">

updated the design again

**Comment by EdisonSu768** [comment]
Is there a way to disable all th keyboard shortcuts?
