### ISSUE TITLE
UX: Getting started flow / panel

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6466]

**Comment by torkelo** [comment]
@mattttt if you have time to checkout https://github.com/grafana/grafana/tree/getting-started-panel, would like to merge it to master, but feels like it needs some more thought polish. 

But if we skip thinking about what to show for non org admins it could be merged fairly quickly to master

**Comment by mattttt** [comment]
This is looking solid, made a few style changes to polish things a bit. 

### Some outstanding things that need to be done

1 - While testing, I invited an additional user to the org but the "Invite Users" item was still upcoming. 
![screenshot 2016-12-07 14 40 37](https://cloud.githubusercontent.com/assets/2886187/20983618/223d5052-bc8b-11e6-869d-41e6ad716cfa.png)

Correct behavior should be to mark that step as completed:
![screenshot 2016-12-07 14 41 23](https://cloud.githubusercontent.com/assets/2886187/20983657/40f8affa-bc8b-11e6-8a1f-4d3a4e333222.png)


2 - When hovering on upcoming items, both the icon & text should change to `color: $link-hover-color`. Currently, it's only one or the other. 

3 - Considering writing some microcopy that will appear over the icon on hover, being slightly more descriptive. Will write the copy first and we can add it if we like it. This shouldnt hold up the deployment though, we can always add it in the future.

4 - For non-admins, I like the docs link a lot, but we should use a different format to show them to the user. To present this as a progress bar that the user cannot make progress on is mixing metaphors. Worst case, let's launch without the non-admin version and meanwhile I'll work on a variant for this.

**Comment by torkelo** [comment]
The invite user check currently check if they have accepted invitation (checks for registered users), not sure what is correct for that check. Maybe check for invitations and registered users. 

Yea, the linear progress for non org admin does  not make sense.  Will try to merge tomorrow

**Comment by mattttt** [comment]
That's odd - in that first screenshot, you can see there are two fully registered users. 

Perhaps a bug.

**Comment by torkelo** [comment]
oh, the does not check future steps. Since data source has not been added it stops the checks there.

**Comment by mattttt** [comment]
I'd really like to have it check all steps at once - we display it as a linear process, as it's the best change of success, but I dont want to have the interfacing sending mixed messages if they've completed an action (users have been invited, but it's still showing it as not completed).

Is this a difficult amount of effort? This goes beyond my baby-like JS abilities.

**Comment by mattttt** [comment]
Updated changes in PR: https://github.com/grafana/grafana/pull/6882
