### ISSUE TITLE
Response to a Prometheus query have to have keys in a certain order.

### ISSUE THREAD

**Issue by rdittrich97** [grafana/grafana#64693]
**What happened**:
Responding to a query with `{"status": "success", "data": {"resultType": "vector", "result": []}}` returns `unknown result type:`

**What you expected to happen**:
Return empty response `[]`

**How to reproduce it (as minimally and precisely as possible)**:
Respond to a query with `{"data": {"result": [], "resultType": "vector"}, "status": "success"}` returns the expected response
Respond to a query with  `{"status": "success", "data": {"resultType": "vector", "result": []}}` returns `unknown result type:`

**Anything else we need to know?**:
I'm not sure if this is a bug or expected behavior. I couldn't find documentation related to it.
I think this is where the behavior comes from https://github.com/grafana/grafana/blame/main/pkg/util/converter/prom.go#L109

**Environment**:
- Grafana version: v9.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

**Comment by tarlitongodoy** [comment]
Steps to reproduce it:

```go
package querydata

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"testing"

	"github.com/grafana/grafana/pkg/tsdb/prometheus/models"
	"github.com/grafana/grafana/pkg/tsdb/prometheus/querydata/exemplar"
	"github.com/stretchr/testify/assert"
)

func TestQueryData_parseResponse(t *testing.T) {
	qd := QueryData{exemplarSampler: exemplar.NewStandardDeviationSampler}

	t.Run("success-resultType-before-result", func(t *testing.T) {
		res := &http.Response{Body: io.NopCloser(bytes.NewBufferString("{\"data\":{\"resultType\":\"vector\", \"result\":[{\"metric\":{\"__name__\":\"some_name\",\"environment\":\"some_env\",\"id\":\"some_id\",\"instance\":\"some_instance:1234\",\"job\":\"some_job\",\"name\":\"another_name\",\"region\":\"some_region\"},\"value\":[1.1,\"2\"]}]},\"status\":\"success\"}"))}
		result := qd.parseResponse(context.Background(), &models.Query{}, res)
		assert.Nil(t, result.Error)
		assert.Len(t, result.Frames, 1)
	})

	t.Run("error-resultType-after-result", func(t *testing.T) {
		res := &http.Response{Body: io.NopCloser(bytes.NewBufferString("{\"data\":{\"result\":[{\"metric\":{\"__name__\":\"some_name\",\"environment\":\"some_env\",\"id\":\"some_id\",\"instance\":\"some_instance:1234\",\"job\":\"some_job\",\"name\":\"another_name\",\"region\":\"some_region\"},\"value\":[1.1,\"2\"]}],\"resultType\":\"vector\"},\"status\":\"success\"}"))}
		result := qd.parseResponse(context.Background(), &models.Query{}, res)
		assert.Error(t, result.Error)
		assert.Equal(t, result.Error.Error(), "unknown result type: ")
		//assert.Nil(t, result.Error)
		//assert.Len(t, result.Frames, 1)
	})
}

```

Tested on main branch.

**Comment by itsmylife** [comment]
@tarlitongodoy Thanks for the unit tests. They helped a lot! I merged the PR to the `main` branch and backported to `v10.1.x` and `v9.4.x`. Backport PRs are not merged yet. Next week we will have them in place. The fix will be landed with the next patch releases of those versions.
