### ISSUE TITLE
Not able to see newly installed plugins in Windows 10.

### ISSUE THREAD

**Issue by anilhk** [grafana/grafana#6470]
I am submitting a bug report. I have installed grafana 3.1.1 for windows on Windows 10. I was able to start the server on port 8080. When I try to install the new plugin, the plugin gets installed but I am not able to see the plugin in the plugins option.

I installed the following plugins. 

grafana-clock-panel
grafana-piechart-panel

I restarted grafana by stoping and starting the grafana-server.exe but still I am not able to see the plugin on the dashboard. 

I can see that the plugins are installed in the grafana-3.1.1/data/plugins directory. 

Can some one please help what is going wrong. ?

![grafana](https://cloud.githubusercontent.com/assets/8183342/20021968/9dd44636-a295-11e6-8c50-6cb66ce00051.png)

**Comment by torkelo** [comment]
Make sure you start grafana with working dir relative data dir so not bin but the root package dir.  For example start grafana by bin/grafana-server.exe

**Comment by anilhk** [comment]
yes, I am doing that. eg. to start grafana from the command prompt I do this.

c::\Users\yc03ak1\Downloads\grafana-3.1.1.windows-x64\grafana-3.1.1\bin>grafana-server.exe
```
INFO[11-04|13:39:49] Starting Grafana                         logger=main version=3.1.1 commit=v3.1.0+19-ga4d2708 compiled=2016-08-01T03:20:16-0700
INFO[11-04|13:39:49] Config loaded from                       logger=settings file=C:\\Users\\yc03ak1\\Downloads\\grafana-3.1.1.windows-x64\\grafana-3.1.1/conf/defaults.ini
INFO[11-04|13:39:49] Config loaded from                       logger=settings file=C:\\Users\\yc03ak1\\Downloads\\grafana-3.1.1.windows-x64\\grafana-3.1.1\\conf\\custom.ini
INFO[11-04|13:39:49] Path Home                                logger=settings path=C:\\Users\\yc03ak1\\Downloads\\grafana-3.1.1.windows-x64\\grafana-3.1.1
INFO[11-04|13:39:49] Path Data                                logger=settings path=C:\\Users\\yc03ak1\\Downloads\\grafana-3.1.1.windows-x64\\grafana-3.1.1\\data
INFO[11-04|13:39:49] Path Logs                                logger=settings path=C:\\Users\\yc03ak1\\Downloads\\grafana-3.1.1.windows-x64\\grafana-3.1.1\\data\\log
INFO[11-04|13:39:49] Path Plugins                             logger=settings path=data/plugins
INFO[11-04|13:39:49] Initializing DB                          logger=sqlstore dbtype=sqlite3
INFO[11-04|13:39:49] Starting DB migration                    logger=migrator
INFO[11-04|13:39:49] Starting plugin search                   logger=plugins
INFO[11-04|13:39:49] Server Listening                         logger=server address=0.0.0.0:8080 protocol=http subUrl=



```

**Comment by anilhk** [comment]
Ok I got what you are saying.. fixed. closing it. thanks a bunch grafana community.

**Comment by torkelo** [comment]
but there is a bug there as well, plugins path not using home path on windows but working path, fixed in master / v4 nightly build

**Comment by anilhk** [comment]
thanks. where can I download the nightly build .exe file for windows ?
