### ISSUE TITLE
Metric Encyclopedia Modal: Label the switches. Move inline switches in text browser to below the test browser input.

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#64713]
Label the switches in the Metric Encyclopedia modal and display them inline below the inputs they are near. The switches currently have tooltips and no text.

Labels:
1) **Browse by type, description, and name**
    - This toggle combines name + type + description for the fuzzy search haystack.
    - This is the haystack we search with the input when the switch is enabled
```
[
  "go_goroutines gauge a gauge that describe the number of go routines running",
  "ALERTS gauge a gauge of the alerts",
  "grafana_histogram histogram a sampling of things put into a histogram"
]
```
and looks like this when the switch is disabled, searching a haystack of only names
```
[
  "go_goroutines",
  "ALERTS",
  "grafana_histogram"
]
```
2) **Backend Browse**
    - This uses the Prometheus match[] api, sending the search input to the actual Prometheus instance to return metric names that match the regex string the user types.
    - This api only returns names and not type nor description so the filtering by type and fuzzy search by metadata should be disabled/cannot work
 
3) **Exclude results with no metadata**
    - Some results have no type or description. I am always including these from the start, when a user search by text or by type. I am erroring on the side of caution by including them. A user may know they need a counter, but the admin who created the metric may not have included a type, so I include them just in case.
<img width="776" alt="Screenshot 2023-03-13 at 2 22 28 PM" src="https://user-images.githubusercontent.com/25674746/224795207-2495c419-1d7c-44d3-9c98-6e2082019c78.png">

Move 1 & 2 to below the "Browse text" input. Does 3 belong belong below the "Type filter?" I think it could also be placed below the "Browse text" input for now, but if it looks crowded, we can put it below the "Type filter."

Future work depending on mockup: Place switches near the results section.

**Comment by gtk-grafana** [comment]
Add to epic?

**Comment by bohandley** [comment]
Completed with https://github.com/grafana/grafana/pull/64816
