### ISSUE TITLE
Does Graphite comes with Grafana ?

### ISSUE THREAD

**Issue by anilhk** [grafana/grafana#6471]
Hi all,

I have installed grafana 3.1.1 on windows and I want to use Graphite as a data source. 

Can someone please guide me to my following questions.

1. Do I need to install Graphite for windows seperately or its included in the Grafana 3.1.1. 
2. Can some one point to me some links to install Graphite installation 

I am completely new to Grafana and having troubles figuring things out.

I have successfully installed the graphite plugin datasource but when I do a test it fails.

any help would be appreciated.

**Comment by anilhk** [comment]
Update: I read that the graphite is included with grafana. But when I try to connect to the graphite  datasource at http://localhost:8080  I get HTTP Error Not Found

My grafana is also running on port 8080. is that the problem ?

**Comment by utkarshcmu** [comment]
@anilhk Where did u read that graphite is included with Grafana?

**Comment by anilhk** [comment]
right here : https://grafana.net/plugins/graphite/installation 

and it says that I dont need to install it. Now when I am trying to connect to port 8080 to test the data source  i get HTTP ERROR . Not Found.

Grafana is running on port 3000.

any help ?

**Comment by utkarshcmu** [comment]
Graphite plugin comes with Grafana and not Graphite tool. Graphite plugin is needed for connecting to Graphite from Grafana. For installing graphite, you need to look into Graphite installation - http://graphite.readthedocs.io/en/latest/install.html
