### ISSUE TITLE
Metric Encyclopedia Modal: Implement upper limit on results per page, 1000

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#64712]
Add an upper limit to the # of search results a user can choose to display. Let's start at 1000 for now.

Add a tooltip or title to let users know the results per page are being limited.

<img width="1295" alt="Screenshot 2023-03-13 at 2 17 54 PM" src="https://user-images.githubusercontent.com/25674746/224793660-e4929049-4b4b-42c4-ab4e-920e98b61729.png">

**Comment by gtk-grafana** [comment]
Add to epic?

**Comment by bohandley** [comment]
Completed with https://github.com/grafana/grafana/pull/64816
