### ISSUE TITLE
Alerting: Send notification based on the time of the day or Snooze notifications depending on time

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6472]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It would be great if we can have the option of sending the notification based on the time of the day. Standardizing on UTC would be great. By default it can be 24 hours, but if someone do not want to get alerted between Midnight and 8 am, he can preconfigure that in the alert.

**Comment by bergquist** [comment]
This will be covered once we start working on https://github.com/grafana/grafana/issues/5856
