### ISSUE TITLE
influxdb datasource+grafana

### ISSUE THREAD

**Issue by jedidah1** [grafana/grafana#64736]
**What happened**:
I was adding influxdb as a data source. When changing the query type to flux, I got an error
![image](https://user-images.githubusercontent.com/67008177/225002175-e5642274-1f96-471f-b8c2-4a6e7764781c.png)

**What you expected to happen**:
The query language should accept flux as a query language and If successful you’ll see a green message saying data source added
**How to reproduce it (as minimally and precisely as possible)**:
Create grafana cloud account.
Add a influxdb as a data source then change the query language to flux
**Anything else we need to know?**:
No
**Environment**: cloud
- Grafana version: Grafana cloud
- Data source type & version: Influxdb
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome on Windows11
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @jedidah1,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my Grafana cloud environment.

Do you have a free Grafana Cloud account or a Paid one?

**Comment by jedidah1** [comment]
hello. I am using the free version

**Comment by usmangt** [comment]
Please provide the following information

1. What is your Grafana Cloud username?
2. Please reproduce this issue again and then send us the date and time when this issue occurs again
3. Before doing Step#2, Open the browser developer tool (e.g. on Chrome it is available by pressing F12) and when reproducing the error, see for any errors in the Console Tab and also in the Network Tab
