### ISSUE TITLE
Stat Panels - Trouble With String Values?

### ISSUE THREAD

**Issue by fatalbyte** [grafana/grafana#64748]
**What happened**:
Since upgrading from 9.3.6 to 9.4.3, some of my Stat panels are no longer working and return "No Data"

**What you expected to happen**:
Return string values.

**How to reproduce it (as minimally and precisely as possible)**:
Downgrading to 9.3.6 resolves the issue.

**Anything else we need to know?**:
In reviewing the Grafana logs I've found the following:

`logger=context userId=1 orgId=1 uname=admin t=2023-03-14T10:29:07.282095261-04:00 level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=x.x.x.x time_ms=298 duration=298.184013ms size=123 referer="http://ip.address:3000/d/8VtkyrtMk/apc-ups-dashboard?editPanel=12&inspect=12&inspectTab=query&orgId=1&refresh=1m" handler=/api/ds/query`

`logger=context userId=1 orgId=1 uname=admin t=2023-03-14T10:30:42.350962951-04:00 level=error msg="Request error" error="interface conversion: interface {} is nil, not string" stack="/usr/local/go/src/runtime/iface.go:262 (0x41231b)\n/drone/src/pkg/tsdb/influxdb/response_parser.go:103 (0x30c546b)\n/drone/src/pkg/tsdb/influxdb/response_parser.go:40 (0x30c3a33)\n/drone/src/pkg/tsdb/influxdb/influxdb.go:145 (0x30be2e3)\n/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:85 (0x315b337)\n/drone/src/pkg/plugins/plugins.go:285 (0x10e4e97)\n/drone/src/pkg/plugins/manager/client/client.go:48 (0x317cb73)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:42 (0x317b5ef)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:103 (0x317c4ef)\n/drone/src/pkg/plugins/manager/client/client.go:44 (0x317c4c8)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go:71 (0x318115f)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/cookies_middleware.go:90 (0x31804eb)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go:100 (0x3181bbb)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/clear_auth_headers_middleware.go:48 (0x317fc03)\n/drone/src/pkg/services/pluginsintegration/clientmiddleware/tracing_header_middleware.go:53 (0x3182213)\n/drone/src/pkg/plugins/manager/client/decorator.go:35 (0x317dde3)\n/drone/src/pkg/services/query/query.go:236 (0x1d28eff)\n/drone/src/pkg/services/query/query.go:84 (0x1d275e7)\n/drone/src/pkg/api/metrics.go:55 (0x2a79057)\n/drone/src/pkg/api/routing/routing.go:17 (0x171dad7)\n/drone/src/pkg/api/response/web_hack.go:40 (0x10af7f7)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:134 (0x10a480b)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/services/contexthandler/contexthandler.go:221 (0x170c5eb)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/render.go:44 (0x10a53a3)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/macaron.go:140 (0x10a48af)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/middleware/csrf/csrf.go:64 (0x1e342ef)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/middleware/recovery.go:171 (0x171895b)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/middleware/logger.go:42 (0x17163ff)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/middleware/request_metrics.go:59 (0x17196c7)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/middleware/request_tracing.go:88 (0x171ac73)\n/usr/local/go/src/net/http/server.go:2109 (0x74d6f7)\n/drone/src/pkg/web/context.go:49 (0x10a3213)\n/drone/src/pkg/web/router.go:155 (0x10a675f)\n/drone/src/pkg/web/router.go:211 (0x10a732f)\n/drone/src/pkg/web/macaron.go:166 (0x10a4cdb)\n/usr/local/go/src/net/http/server.go:2947 (0x75062b)\n/usr/local/go/src/net/http/server.go:1991 (0x74c4e3)\n/usr/local/go/src/runtime/asm_arm64.s:1172 (0x475b43)\n"`

This is listed under the Query Inspector.
`InfluxDB Error: Internal Server Error - Check the Grafana server logs for the detailed error message.`

In the troubleshooting I was able to do, it seems when an integer value is returned, it works fine.  But when it's a string is when it will error out with "No Data".

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10 (Raspberry Pi)
- User OS & Browser: Mac OSX / Chrome
- Grafana plugins: InfluxDB 
- Others: N/A

<img width="838" alt="Screenshot 2023-03-14 at 11 15 52 AM" src="https://user-images.githubusercontent.com/52629807/225047772-63f0550d-eeca-47d6-8adc-b118077a2e0f.png">

**Comment by usmangt** [comment]
Hi @fatalbyte,

Thanks for opening this issue.

Could you please provide the following information:

- What is your InfluxDB version?
- Are you using InfluxDB with Telegraf?
- Does this happens with a specific query or reproducible with any query?
- Is Anything noted in the InfluxDB logs?

**Comment by fatalbyte** [comment]
**What is your InfluxDB version?** 
InfluxDB shell version: 1.8.10

**Are you using InfluxDB with Telegraf?**  
Yes.

**Does this happens with a specific query or reproducible with any query?** 
Seems to only be with string values being returned.  When I test it with integers, it runs the query and returns the results as expected.

**Is Anything noted in the InfluxDB logs?**
Nothing noted.

**Comment by fatalbyte** [comment]
I was able to fix this by deleting the "GROUP BY time" in my query and now the data is returning successfully.

Found this [fix here](https://community.influxdata.com/t/influxdb-error-unsupported-mean-iterator-type-query-booleaninterruptiterator/23140).

**Comment by usmangt** [comment]
Great to hear this :+1:  

I will now close this issue.
