### ISSUE TITLE
Alerting: Migrate PagerDuty integration from V2 to V3

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#64743]
The V2 API for PagerDuty is getting deprecated (no date yet).
V2 still works, but we should migrate to V3 soon. PagerDuty provides a [migration guide](https://support.pagerduty.com/docs/webhooks#migration-guide) alongside a [migration script](https://github.com/PagerDuty/public-support-scripts/tree/master/migrate_webhooks_to_v3) we could use.

![image](https://user-images.githubusercontent.com/41638679/225039562-6f48e8c0-cd2c-4d02-bac9-7b5ce57d2b13.png)

**Comment by alexweav** [comment]
We don't use webhook extensions, this seems to only apply to that subset of their API. Instead we use the events API which does not have a V3: https://developer.pagerduty.com/docs/ZG9jOjQ2NDA2-introduction#events-api
