### ISSUE TITLE
UX: Navbar search & dashboard menu changes

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6475]
Think we can improve the navbar by having a separate search button. Then the dashboard "title button" can be changed into a settings & dashboard actions dropdown, with similar look to the sidemenu/row menu. 

<img width="855" alt="screen shot 2016-11-05 at 11 29 47" src="https://cloud.githubusercontent.com/assets/10999/20029479/5c64c032-a34d-11e6-8f71-69a589dee1a2.png">

So in the above mockup I have removed the dashboard settings and star, share/save icons. These need to find place inside the dropdown, maybe have a 2 column dropdown, with some actions like Star, Share, Help on one side and Settings, Templating, etc on the other.  If that feels strange I think we can add star and share back to the navbar to the right of the title button. 

This is a very ruff mock up of how the search button would work, it would replace the rest of the top nav with search input & filter actions, the result dropdown below would like "sort of" similar to sidemenu/row menu items. 
 
<img width="829" alt="screen shot 2016-11-05 at 11 40 29" src="https://cloud.githubusercontent.com/assets/10999/20029481/606b7ec8-a34d-11e6-9d13-ca34b64957b5.png">

The idea is also to have the search button present on all pages. These changes are not at all thought through / polished so any feedback, further mockups is required. 

@mattttt

**Comment by mattttt** [comment]
I was able to dig up a mockup idea from ~Winter 2015:

<img width="639" alt="screenshot 2016-11-05 09 31 18" src="https://cloud.githubusercontent.com/assets/2886187/20030437/4f88230c-a33b-11e6-9d9c-01bc3b338e78.png">

I really like the idea of making that search area also serve the role of a breadcrumb. We could even extend it to support folders when implemented, making navigation within a folder super easy:

<img width="598" alt="screenshot 2016-11-05 09 45 28" src="https://cloud.githubusercontent.com/assets/2886187/20030486/992f16c2-a33c-11e6-81d3-ac0851f9e128.png">

Naturally, not fully thought through either (from so long ago), but I think this gives us more room to grow.

**Comment by torkelo** [comment]
All pages are updated, and this is now in a mergable state. Further refinements will be done in master.

![image](https://cloud.githubusercontent.com/assets/10999/26724807/a2af8796-479b-11e7-9333-14ec15130517.png)
