### ISSUE TITLE
Cloudwatch: Cross Account Observability Documentation is a bit weird in 9.4

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#64750]
**What happened**:
in 9.3 we have a section in our docs called Cross-Account observability: https://grafana.com/docs/grafana/v9.3/datasources/aws-cloudwatch/query-editor/#cross-account-observability

in 9.4. it looks like the header disappeared https://grafana.com/docs/grafana/v9.4/datasources/aws-cloudwatch/query-editor/#getting-started 

Let's ensure the docs on this feature are up to date and clear.

**Comment by lwandz13** [comment]
Added section back, fixed a few broken links
