### ISSUE TITLE
Daylight saving time affected dashboards

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6478]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Daylight saving time changed 30 mins back here in the US and this is what I saw on my dashboard:

Tested this on Chrome and Safari on Mac OS.

<img width="688" alt="screen shot 2016-11-06 at 1 26 42 am 2" src="https://cloud.githubusercontent.com/assets/1019609/20036579/7ce28240-a3c0-11e6-88f8-1c99ff3fa4cc.png">

Data is current but on the graph its shows 1 hour delayed. Also, 1:00 PM is shown twice.

**Comment by utkarshcmu** [comment]
Looks like I need to restart my computer to fix this.

**Comment by torkelo** [comment]
could be a backend issue as well, had issues with Graphite with daylight time saving, but that was fixed in 0.9.12 I think, and since then I have had no reports on issues in Grafana
