### ISSUE TITLE
Alerting: Contact points, custom templates, notification policies disappeared after alert rule editing

### ISSUE THREAD

**Issue by dorinpirvu** [grafana/grafana#64798]
**What happened**:
Contact points, Custom templates and Notification policies "disappeared"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Not sure.
I was editing multiple alert rules (approx 40 alerts, not at the same time, one after another). I received multiple times some errors stating the database is locked and was forced to sign in again (admin account). After I finished editing the alerts, when I checked the tabs of Contact Points and Notification Policies, they're empty....
Last email per the Contact Points, Notification Policies, custom alert templates was received at ~10:48, I noticed the missing info at ~11:15.
How I edited alert rules: right click on the edit button, open in new tab, do the edit, click save, wait for the rule updated message, close tab, go to next rule and repeat...

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 22.04
- User OS & Browser: Win 10 Pro, Edge 
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @dorinpirvu,

Thanks for reporting this issue.

I think I understand what happened. Basically the error **"database locked"** is coming from the Grafana backend DB (which is SQLite by default).

SQLite does have some limitations and is error-prone and therefore not recommended to use in a Production Environment.

Alternative Backend DB supported for Grafana are MySQL and PostgreSQL which performs better under high load and cause fewer issues when monitoring lots of devices or having many alerts.

We do have a script to migrate from SQLite to MySQL ([Database Migrator](https://github.com/grafana/database-migrator)).

While for this you will need to create a lab environment before doing this on production.

Therefore for now, what you can do is add this extra configuration parameter in your `grafana.ini` configuration file:

```
# For "sqlite3" only. Enable/disable Write-Ahead Logging, https://sqlite.org/wal.html. Default is false.
 wal = true
```
Then do a restart and it should perform better. (Link to the similar issue I worked on today https://github.com/grafana/grafana/issues/64664#issuecomment-1471414001)

I hope this helps.

**Comment by dorinpirvu** [comment]
Hello @usmangt , thanks for the answer.
I will have to check with our system administrator about switching to MySQL or PostgreSQL, until then I will forward your recommendation about the .ini modification.

Best regards,
