### ISSUE TITLE
update process broken due to missing dependency (OSS 15.4 / chkconfig)

### ISSUE THREAD

**Issue by 18info** [grafana/grafana#64801]
Hi!

**What happened**:
I needed to break dependencies during update due to missing "chkconfig"

**What you expected to happen**:
To don't need to break it, have a normal update process.
`chkconfig` is already installed.

**How to reproduce it (as minimally and precisely as possible)**:
update Grafana for ex from 9.3.0 to 9.4.3

**Anything else we need to know?**:
```
# cat /etc/zypp/repos.d/grafana_yum.repo 
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```
```
# zypper up grafana
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'chkconfig' which is needed for the grafana-9.4.3-1.x86_64 item to be installed
 Solution 1: do not install grafana-9.4.3-1.x86_64
 Solution 2: break grafana-9.4.3-1.x86_64 by ignoring some of its dependencies

Choose one of the above solutions by typing its number or cancel by typing 'a' [1/2/a/d/?] (a): 2
Resolving dependencies...
Resolving package dependencies...

The following package will be updated:
  grafana

1 package to update.
Total download size: 79.7 MiB. Already cached: 0 B. After the operation, 13.6 MiB of additional disk space will be used.
Continue? [y/n/v/...? displays all options] (y): y
Downloading grafana-9.4.3-1.x86_64 package (1/1), 79.7 MiB (295.3 MiB unpacked)
Downloading grafana-9.4.3-1.x86_64.rpm ......................................[done (12.9 MiB/s)]

Search for file conflicts: ................................................................[done]
(1/1) Installation of: grafana-9.4.3-1.x86_64 ..............................[done]
POSTTRANS: Running script
Running scripts %posttrans .........................................................[done]
```
```
# whereis chkconfig
chkconfig: /usr/bin/chkconfig /sbin/chkconfig /usr/share/man/man8/chkconfig.8.gz

# which chkconfig
/sbin/chkconfig

# ls -hal /sbin/chkconfig
lrwxrwxrwx 1 root root 18  4 oct.  17:42 /sbin/chkconfig -> /usr/bin/chkconfig

# ls -hal /usr/bin/chkconfig
-rwxr-xr-x 1 root root 20K  4 oct.  17:42 /usr/bin/chkconfig
```

**Environment**:
- Grafana version: `9.3.0 -> 9.4.3`
- Data source type & version: `prometheus 2.32 from official OS repo`
- OS Grafana is installed on: `openSUSE 15.4`
- User OS & Browser: `openSUSE 15.4 / FF up to date`
- Grafana plugins:` N/A`
- Others: `Grafana works as wanted after this`

**Comment by usmangt** [comment]
Hi @18info,

Thanks for opening this issue.

We will check this one and get back to you once we have more updates.

**Comment by 18info** [comment]
Hi @usmangt,
Thank you very much!
Stand-by, on watching ;)

**Comment by kminehart** [comment]
Unfortunately we don't explicitly support OpenSUSE. Any change that we make to the rpm package has to support CentOS & RHEL, and any OpenSUSE support is just because SUSE supports RPM packages. Luckily you're able to overcome this issue easily since I think chkconfig is included in the systemd installation on OpenSUSE. I'm sure that there's a way that we can remove the chkconfig dependency now that systemd is the default on RPM and CentOS.

Thank you for submitting this and I'll have a chat with the team and see if we should remove our sysvinit scripts.

**Comment by 18info** [comment]
Yes, `chkconfig` is a "natural" part of an openSUSE oftb.
Thanks you so much to answer and take a look at.
I keep on watching.
Cheers!

**Comment by tectumopticum** [comment]
> Unfortunately we don't explicitly support OpenSUSE. Any change that we make to the rpm package has to support CentOS & RHEL, and any OpenSUSE support is just because SUSE supports RPM packages. Luckily you're able to overcome this issue easily since I think chkconfig is included in the systemd installation on OpenSUSE. I'm sure that there's a way that we can remove the chkconfig dependency now that systemd is the default on RPM and CentOS.
> 
> Thank you for submitting this and I'll have a chat with the team and see if we should remove our sysvinit scripts.

We have the same issue on SLES / SUSE Linux Enterprise Server 15 (SP3+4).
Even though the package which provides "chkconfig" is installed, the rpm-installation shows the missing-dependency-error:

`zypper se --provides chkconfig
[...]
Loading repository data...
Reading installed packages...

S | Name     | Summary               | Type
--+----------+-----------------------+--------
i | aaa_base | openSUSE Base Package | package

Information for package aaa_base:
---------------------------------
Repository     : sles15sp3-default-sandbox-SLE-Module-Basesystem15-SP3-Updates for x86_64
Name           : aaa_base
Version        : 84.87+git20180409.04c9dae-150300.10.3.1
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 271.7 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : aaa_base-84.87+git20180409.04c9dae-150300.10.3.1.src
Summary        : openSUSE Base Package
Description    :
    This package installs several important configuration files and central scripts.`

**Comment by 18info** [comment]
Hi!
I've just upgraded an instance from 10.0.3 to 10.1.1: No more alert about dependence. I keep an eye on but I think it's solved.
Thank you so much :)
