### ISSUE TITLE
Grafana crashes with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hkailantzis** [grafana/grafana#64807]
**What happened**:

Installing grafana helm chart, (with image: 9.4.3), (Chart version: 6.51.2) on K8s cluster, pod starts crashing after some time.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e0a398]
goroutine 1693 [running]:
github.com/grafana/grafana/pkg/services/datasources/service.(*CacheServiceImpl).GetDatasourceByUID(0xc000de34a0, {0x4e5c4c8, 0xc00367f230}, {0xc002a888a0, 0xf}, 0xc002934380, 0x0)
/drone/src/pkg/services/datasources/service/cache.go:104 +0x3d8
github.com/grafana/grafana/pkg/services/ngalert/eval.getExprRequest({{0x4e5c4c8?, 0xc00367f230?}, 0xc002934380?}, {0xc003706180, 0x3, 0xe0?}, {0x4e3f658, 0xc000de34a0})
/drone/src/pkg/services/ngalert/eval/eval.go:273 +0x403
github.com/grafana/grafana/pkg/services/ngalert/eval.(*evaluatorImpl).Create(0xc000c9b410, {{0x4e5c4c8?, 0xc00367f230?}, 0xc002934380?}, {{0xc002a886b0, 0x1}, {0xc003706180, 0x3, 0x4}})
/drone/src/pkg/services/ngalert/eval/eval.go:630 +0x86
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3({0x4e5c4c8, 0xc00367f230}, 0x4?, 0xc000d365c8, {0x4e6c990, 0xc003bc6030})
/drone/src/pkg/services/ngalert/schedule/schedule.go:362 +0x4b5
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5.2(0x48?)
/drone/src/pkg/services/ngalert/schedule/schedule.go:499 +0x951
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0xc002180050)
/drone/src/pkg/services/ngalert/schedule/schedule.go:428 +0x5b
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5(0xc00185ed46?, 0xc00183aa90, {0x1?, {0xc0030056f0?, 0x9?}}, 0xc000d365c8, 0xc0001abe88, 0xc001761ef8, {0x4e6f350, 0xc0022e08d0}, ...)
/drone/src/pkg/services/ngalert/schedule/schedule.go:472 +0x1d6
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc00183aa90, {0x4e5dd10, 0xc0023a2c60}, {0x0?, {0xc0030056f0?, 0x14?}}, 0xc001283e60, 0xc001283ec0)
/drone/src/pkg/services/ngalert/schedule/schedule.go:505 +0x825
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).processTick.func1()
/drone/src/pkg/services/ngalert/schedule/schedule.go:247 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1()
/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**What you expected to happen**:
Grafana pod shouldn't crash.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Also, ```logger=datasources t=2023-03-15T11:28:12.483583872Z level=error msg="Failed getting data source" err="database is locked" uid=xxxx id=0 name= orgId=xxxx```, error appears before the crash. takes about 1hr for the 1st crash to happen after clean install.

- alerts, contactpoints, notification policies are provisioned via sidecar and official config
- custom plugin checkmk provisioned via custom initcontainer
- dashboards provisioned via official dashboard provider config and dashboard configmap
- datasource provisioned via official config.

**Environment**:
- Grafana version: 9.4.3, Helm chart: 6.51.2, local/default DB, ie. -> sqlite
- Data source type & version: Prometheus - Thanos
- OS Grafana is installed on: K8s cluster
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hkailantzis** [comment]
hi @usmangt , 

thanks very much for the hints, and yes I'm using SQLlite,  I'm aware of the benefits of using PostgresSQL or MySQL, but why the "database locked error," should cause these sequential "invalid memory address or nil pointer reference" and crashes with "signal SIGSEGV: segmentation violation" ?. Is sounds more like a bug to me with 9.4.x, because with 9.3.8, the crash, doesn't seem to be happening. A hint that I missed to mention, is that these crashes are way more frequent, when "foldersFromFilesStructure: true", for the dashboards provisioning. The stack trace error though in this case is something about the creation of the dashboard folder...and not the "GetDatasourceByUID". Please advise, if you require more info, like configs etc...Thanks very much in advance!.

**Comment by usmangt** [comment]
Hi @hkailantzis ,

While I was working on another similar GH issue related to database locked. A user found a solution to this. (see https://github.com/grafana/grafana/issues/64664#issuecomment-1471414001)

I suggest that you try this out and see if that works.

On the other side, I will definitely ask Engineers to have a look at your issue.

**Comment by hkailantzis** [comment]
hi @usmangt , thanks for the hints and updates!, I think I tried the wal setting, and was crashing still. By the way, reverted to 9.3.8 (same config in helm chart), and no crashes so far like the one described the last 3hours. it seems that something related with 9.4.x... I hope it helps.

**Comment by hkailantzis** [comment]
hi @usmangt, a brief update, with 9.4.3 seems that with wal:true on the database attribute, things are more stable...will be monitoring and update accordingly.

**Comment by usmangt** [comment]
This is good to hear. I had already raised this SQLite database lock issue in my team and we are thinking of updating our Docs and adding more info that for Production Env best is to use MySQL and PostgreSQL (and probably highlight the SQLite limitations).

But yes, please keep monitoring and keep us updated. Thanks for your quick responses !!

**Comment by hkailantzis** [comment]
@usmangt a positive update, no crashes since 17Hrs..seems that wal:true, did the trick. Thanks for that!. Please let me know if we close the issue or we keep open for reference.

**Comment by usmangt** [comment]
I will now close this one

**Comment by 8** [comment]
Hi,
we just had the same issue with grafana crashing.

We are running the docker image `grafana/grafana-oss` with sha256:944e84f25bc7d7675c54716465f81f6c1c144db5395ce44cad10939f2ce739a0

The log shows:
```log
logger=datasources t=2023-03-24T12:32:12.526265529Z level=error msg="Failed getting data source" err="database is locked" uid=PBFA97CFB590B2093 id=0 name= orgId=1
logger=sqlstore.transactions rule_uid=alert_cpu org_id=1 t=2023-03-24T12:32:12.526321529Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1 code="database is locked"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e0a398]

goroutine 1713 [running]:
github.com/grafana/grafana/pkg/services/datasources/service.(*CacheServiceImpl).GetDatasourceByUID(0xc0015647b0, {0x4e5c4c8, 0xc002a17830}, {0xc002944cc0, 0x11}, 0xc0023d8ee0, 0x0)
        /drone/src/pkg/services/datasources/service/cache.go:104 +0x3d8
github.com/grafana/grafana/pkg/services/ngalert/eval.getExprRequest({{0x4e5c4c8?, 0xc002a17830?}, 0xc0023d8ee0?}, {0xc001166900, 0x3, 0xe0?}, {0x4e3f658, 0xc0015647b0})
        /drone/src/pkg/services/ngalert/eval/eval.go:273 +0x403
github.com/grafana/grafana/pkg/services/ngalert/eval.(*evaluatorImpl).Create(0xc0016af530, {{0x4e5c4c8?, 0xc002a17830?}, 0xc0023d8ee0?}, {{0xc001ac9658, 0x5}, {0xc001166900, 0x3, 0x4}})
        /drone/src/pkg/services/ngalert/eval/eval.go:630 +0x86
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3({0x4e5c4c8, 0xc002a17830}, 0x4?, 0xc000504988, {0x4e6c990, 0xc0029fbf90})
        /drone/src/pkg/services/ngalert/schedule/schedule.go:362 +0x4b5
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5.2(0x48?)
        /drone/src/pkg/services/ngalert/schedule/schedule.go:499 +0x951
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0xc0031be780)
        /drone/src/pkg/services/ngalert/schedule/schedule.go:428 +0x5b
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5(0xc002465d46?, 0xc0016560d0, {0x1?, {0xc0009661a0?, 0x9?}}, 0xc000504988, 0xc0005dae88, 0xc002345100, {0x4e6f350, 0xc001c01ef0}, ...)
        /drone/src/pkg/services/ngalert/schedule/schedule.go:472 +0x1d6
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc0016560d0, {0x4e5dd10, 0xc001fd8030}, {0xc0015d6d00?, {0xc0009661a0?, 0xc0019b5d30?}}, 0xc00161fd40, 0xc00161fda0)
        /drone/src/pkg/services/ngalert/schedule/schedule.go:505 +0x825
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).processTick.func1()
        /drone/src/pkg/services/ngalert/schedule/schedule.go:247 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

If I read the thread correctly, the recommended fix is to update the grafana.ini file to include `wal = true`?

Thank you!

Take care,
Martin

**Comment by hkailantzis** [comment]
@8 , correct, this is what fixed it for me, in grafana.ini:

```
database:
  wal: true
```

**Comment by 8** [comment]
Thnx a lot, I will try that as well! :)

Take care,
Martin
