### ISSUE TITLE
Grafana exposed over WAN cannot connect to backend data sources

### ISSUE THREAD

**Issue by awakefie** [grafana/grafana#6482]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
InfluxDB 1.0
- What OS are you running grafana on?
Docker on CentOS, Ubuntu Container
- What did you do?
Exposed Grafana over the internet using port forwarding.
- What was the expected result?
Grafana would work as normal
- What happened instead?
The data sources do not work when accessed from the WAN.  They work when I access from the LAN

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Make sure you have enabled proxy access in the Grafana data source config view, that way the data source is accessed via grafana. If you have enabled "direct" access mode you need to expose your datasources to WAN as well

**Comment by awakefie** [comment]
I have tried this option and all I get is a 'InfluxDB Error Response: Internal Server Error'  I am connecting directly to the IP (http://<IP>:8086).  I have tried the auth options as well.  If I don't change anything but just switch to direct the connection works.

**Comment by awakefie** [comment]
Im going to work through the backend networking and then if I am still having issues I will reach back out
