### ISSUE TITLE
Task: Fill Definition of Done document

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#64820]
Already [started](https://docs.google.com/document/d/1BRImxVy1evFc6oTeYo67I42JjtavFc6BW4nJkOdkIY4)

**Comment by natellium** [comment]
@evictorero Thoughts on closing this and leaving a TODO in the Epic for the what’s new? The current state of the doc is good IMO and not sure it adds value to have this one around until whenever we work on the what’s new?

**Comment by evictorero** [comment]
Agree, the document it's ready and we will be adding more info on the next project phases.
