### ISSUE TITLE
InfluxDB: raw query responses are parsed incorrectly

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#64835]
In migrating InfluxDB to the backend, a response parser was built to handle table responses. This parser did not correctly add columns in a number of cases that include

- group by labels
- `*`
- aliases
- individual fields

The parser originally was looking for 'selected fields' object which is only present in the query builder. Because that object is no long present for the raw query, many queries are missing columns.

[This is a begininng fix but does not solve all the issues.](https://github.com/grafana/grafana/pull/64058)

These are a few of the issues where customers are affected
https://github.com/grafana/support-escalations/issues/5134
https://github.com/grafana/grafana/issues/63842
https://github.com/grafana/grafana/issues/63923
https://github.com/grafana/support-escalations/issues/5242
https://github.com/grafana/support-escalations/issues/5315

**Comment by zekena2** [comment]
Hi, Any updates on this one?

**Comment by bohandley** [comment]
@zekena2 New update! This issue was the result of removing a feature toggle which caused a number of issues. The feature toggle has been reintroduced along with the code that fixes this issue and will be released in v9.4.6 https://github.com/grafana/grafana/pull/64842

**Comment by staeglis** [comment]
The latest version is 9.4.3. So I would have expected the fix for 9.4.4. When we can expect the release of 9.4.6?
