### ISSUE TITLE
Alert List panel does not display rules that don't have alert instances and causes confusion

### ISSUE THREAD

**Issue by VikaCep** [grafana/grafana#64837]
Alert panels in Grafana 9 only show rules that contain alert instances. In the case of cloud rules, "Normal" state alerts are not shown because this means they have 0 alert instances so they're omitted by design. However, these alerts can be seen from the alert list view which creates confusion between the two views as they are inconsistent.

While some users have requested to hide alert rules without instances from this list when the alert is firing, others expect to see them when they have a normal state. A possible solution would be to create some sort of exception to the "hide if 0 instances" rule for cloud rules. Additionally, we should consider splitting the filters so that the difference between alert rules and alert instances is more clear. 

One last important thing to consider is to remain backwards compatible with the current configuration that users have.

![image](https://user-images.githubusercontent.com/6271380/225384832-eec1982e-98c7-435f-bf97-a3b45e207e5c.png)
Screenshot from the Alert List view, where Normal state rules are shown when filtering by `Prometheus-1` datasource.

![image](https://user-images.githubusercontent.com/6271380/225384851-5b660d93-62f0-4e77-b366-9f017f7f33b7.png)
Screenshot from the Alert Panel, where only Firing/Pending alerts are shown, and Normal state ones are hidden when filtering by `Prometheus-1` datasource.

**Comment by michaelpeterswa** [comment]
Would love to see 

> some sort of exception to the "hide if 0 instances" rule

Encountered this issue for the first time today, and it took quite a while to track down why certain alerts don't appear but others do. At the very least, it would be nice to have some sort of tooltip next to the "Alert state filter" dropdown that specifies what you noted above (where 0 instances won't show no matter what). Thanks!
