### ISSUE TITLE
request: dynamic threshold on arbitrary selection of past data

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6483]
bosun has a neat banding feature.
let's say you want to monitor traffic, but traffic is highly seasonal, perhaps a daily and weekly trend.
let's say you want to look at the last 10min of traffic, which depending on the current hour, or which day of the week it is, could be very high or low.
let's say it's 8AM, with bosun you can use band() or graphiteBand() to select 7-8AM from the past days, or from the same day of the week, the last few weeks. (e.g. a week ago, 2 weeks ago, 3 weeks ago).
that data should be representative of expectations for current data, though you may not necessarily want to graph it.
you could potentially use timeShift() here but then you're forced to also visualize that way and modeling your query as a "current series" / avg(timeshift(1week ago), timeshift(2weeks ago), timeshift(3weeks ago)) becomes a bit clunky. never mind many tsdb's may not support it

another thing that is needed, is we start supporting querying for banded data like this, we have to exclude past timeranges during which there was an outage, (e.g. during which we know the alert state was not ok), because those would skew the data.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
