### ISSUE TITLE
Alerting: replace rule version with rule's hash in Scheduler\State manager 

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#64843]
Currently, when a rule is updated API increases the version of the rule as well as versions of all other rules in the group the rule belongs to. This is done to facilitate concurrent operations on the whole group. 
Also, the rule version is used in state management (but it is part of the scheduler). When the rule version is changed alerting resets the existing state and starts from scratch. This leads to the problem https://github.com/grafana/grafana/issues/64256 when an update of a single rule (we still show them individually in UI) leads to a reset of all states of all rules in that group. 
The reason for resetting the state is that when the rule gets changed the next evaluation of results can produce a different state. Every time rule is evaluated the result can contain many dimensions each dimension is identified by a unique key - the state labels, which is a composition of rule labels, result labels, and extra labels. 

https://github.com/grafana/grafana/blob/0c8876c3a2dcf3bf88a83f11be3e676a2e3b133f/pkg/services/ngalert/state/cache.go#L72

https://github.com/grafana/grafana/blob/0c8876c3a2dcf3bf88a83f11be3e676a2e3b133f/pkg/services/ngalert/state/cache.go#L105-L109

If we do not reset the state then when the rule is changed and fields that are used to calculate labels are changed the state key becomes different and the rule state will get twice more states: created from a previous version of the rule and ones created from the current version of the rule. 

Therefore, we need to use a more stable indicator of when the rule changed than just the version number.

My proposal is to stop using the version field in state management and replace it with something more stable - a fingerprint of the rule (similar to how we identify a state and alertmanager identifies alert). The fingerprint is a hash that includes all information used to calculate the state excluding its variable part, which is the evaluation result.
Therefore, in the general case, the fingerprint should include: 
- rule definition except for version. 
- folder name because it is used in state calculation.
That hash will identify a particular version of a rule - the static component of the state calculation. When any field of the rule is changed (except version) - the rule's state gets reset. This will guarantee that even version of the rule is changed in the database but the rule definition was not changed, then the state is not reset.

### Optional part ###
However, with that hash, we can go even further and improve the user experience even more by excluding fields that do not affect state calculation. For example, ID of the rule (UID is still used), group, group index, annotations, interval, `for` interval, state mapping options. Therefore, the fingerprint contains only fields that are used during state calculation:
- UID
- Title
- Namespace\Folder UID
- Namespace\Folder Name
- Labels
- Query

Thus, when the user changes, for example, just the evaluation interval and "for" interval, the state is not reset, the user still sees it in UI, and the state manager applies the next evaluation on top of it.

**Comment by menukagurung** [comment]
Hi @yuri-tceretian has there been any progress on this issue?

**Comment by yuri-tceretian** [comment]
@menukagurung, we're still discussing whether this approach makes sense.

**Comment by kerrygibian** [comment]
hi @yuri-tceretian sorry to bug you but I'm meeting with a customer again today who is really interested in this as they're impacted by https://github.com/grafana/grafana/issues/64256, have there been any updates on this discussion?

**Comment by yuri-tceretian** [comment]
Yes, yesterday we met and decided to implement this proposal. Unfortunately, this has little chance to land in 9.5.0. Most likely the next patch release.

**Comment by armandgrillet** [comment]
This will not land in 9.5.0 as the milestone has been cut already.

**Comment by kerrygibian** [comment]
hi @yuri-tceretian confirming if this is still slotted for the next patch release?

**Comment by yuri-tceretian** [comment]
The PR https://github.com/grafana/grafana/pull/66531 is in review and will go in Grafana 10 by default. I will discuss with the team including it in the next patch for 9.5.x.

**Comment by kerrygibian** [comment]
Hi Yuri,

Were you able to discuss with the team and confirm if you're able to
include this in the next patch for 9.5.x?

Thank you,
Kerry

**Comment by yuri-tceretian** [comment]
Fixed in https://github.com/grafana/grafana/pull/66531 backported to 9.5.x, and will be released in 9.5.2
