### ISSUE TITLE
Feature request - Influxdb query timeout config / max points etc

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#6484]
* **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using? Grafana v4.0.0-pre1 (commit: b887911)
- What datasource are you using? Influxdb 1.0.2
- What OS are you running grafana on? centops 7
- What did you do? configured influxdb to kill long running queries with query-timeout = "30s" in influxdb.conf
- What was the expected result? influxdb kills the queries
![image](https://cloud.githubusercontent.com/assets/12600004/20053035/044501b0-a4d7-11e6-8239-9c75276cdb50.png)
![image](https://cloud.githubusercontent.com/assets/12600004/20053142/809c1ca8-a4d7-11e6-9896-86cfd248f6ed.png)

- What happened instead?
but grafana dashboard just shows "no datapoints" - i would like the get the result into grafana so you can see the reason , for example you can also configure max points/series etc which would be nice to catch

**Comment by torkelo** [comment]
what's the HTTP response code from influxdb?

**Comment by discoduck2x** [comment]
@torkelo 

![image](https://cloud.githubusercontent.com/assets/12600004/20054971/5d48efe4-a4df-11e6-9fe2-ca1a2735ce7e.png)

**Comment by torkelo** [comment]
seems like InfluxDB is returning the wrong status code, should not return 200 OK on a timeout

**Comment by discoduck2x** [comment]
@torkelo  ok thanks i´ve raised an issue over at their end

**Comment by discoduck2x** [comment]
@torkelo see reply from influxteam:

_jsternberg commented 16 hours ago_
_The status code mostly just indicates if the query itself executed. Errors in query execution are returned as part of the JSON body and require parsing that JSON. Since query timeouts are an error during query execution and not the preparation, you get a 200 OK and the error shows up in the JSON body._

_Does this make sense?_
