### ISSUE TITLE
[Feature Request] Add support for floating header

### ISSUE THREAD

**Issue by bogdanveres** [grafana/grafana#6485]
Hi, can you add support for floating header? I know there was a simillar request (https://github.com/grafana/grafana/issues/1562) . In the current version you need to scroll up if you have multiple graphs if you want to change the template or the time range. 
![2016_11_07_12_33_21_grafana_statistics](https://cloud.githubusercontent.com/assets/3493668/20054768/ea101b26-a4e6-11e6-97ac-f6a84416067c.jpg)

**Comment by sbengo** [comment]
Would be awesome,
I also did the FR with some mockups (but only asking for fixed navbar) on issue #4670

Regards

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/4670
