### ISSUE TITLE
Alerting: support images in Mimir

### ISSUE THREAD

**Issue by luistilingue** [grafana/grafana#64865]
**What happened**:
When I try to access the `.ImageURL` (generated with URL of a **remote storage** - GCP **GCS**) of the array of alerts in **Go template** it is inaccessible and I need of that to input it as parameter in URL of a **webhook**.

`{{ (index .Alerts 0).ImageURL }}` that way doesn't work as well.

**What you expected to happen**:
Got the value of `.ImageURL` to use inside contact points.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new Contact Point of Webhook type, use `{{ (index .Alerts 0).ImageURL }}` template in Message or in URL parameter and try it/use it.

**Anything else we need to know?**:
Based on https://github.com/grafana/alerting/blob/main/templates/template_data.go it should be accessible.

Printing everything of the .Alerts context, I'm getting the ImageURL, but I can't use it.

>channels.ExtendedAlert{Status:"firing", Labels:template.KV{"alertname":"yyyyyy", "grafana_folder":"yyyyy", "rule_uid":"tetetetete"}, Annotations:template.KV{"message":"xxxxxxxxxxxxxx."}, StartsAt:time.Date(2023, time.March, 16, 3, 50, 0, 0, time.Local), EndsAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), GeneratorURL:"redacted", Fingerprint:"123456", SilenceURL:"redacted", DashboardURL:"redacted", PanelURL:"redacted", Values:map[string]float64{"B":1779.8827351489622}, ValueString:"[ var='B0' metric='Posts Nacked' labels={} value=1779.8827351489622 ]", ImageURL:"https://storage.googleapis.com/.../redacted...", EmbeddedImage:""}

Based on https://github.com/grafana/grafana/discussions/44334#discussioncomment-3924674, it should be available to use in URL parameter.

As you can see, the field `ImageURL` is de facto populated with GCS URL but I can't use it.

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Mimir 2.6.0
- OS Grafana is installed on: GKE 1.24
- User OS & Browser: Linux and Google Chrome
- Grafana plugins: None
- Others: N/A

**Comment by grobinson-grafana** [comment]
This looks like a mistake in the code as these fields are not supposed to be templatable at this time. The reason it's blank is because the ImageURL is loaded after the template is expanded.

**Comment by luistilingue** [comment]
So, is there any way to fix that code, onde docs states webhook supports image?

**Comment by grobinson-grafana** [comment]
The ImageURL is included in all webhooks. You want to look for the `ImageURL` field for each alert in the JSON.

**Comment by luistilingue** [comment]
yes, it is empty.

**Comment by luistilingue** [comment]
Which version are you using?

**Comment by grobinson-grafana** [comment]
I tested on Grafana 9.4.3, 9.4.7 and 9.5.0

**Comment by armandgrillet** [comment]
Are you still affected by this on Grafana 10? We have improved templating since the time the issue was created https://grafana.com/blog/2023/04/05/grafana-alerting-a-beginners-guide-to-templating-alert-notifications/.

**Comment by armandgrillet** [comment]
Are you using Mimir managed alerts' contact point of type webhook? There is no imageUrl there.

**Comment by armandgrillet** [comment]
Feature requests are now issues thus we will keep the discussion happening here.

Last comment from @yuri-tceretian :
Interesting idea, that might help users that do not want to configure publicly available storage for images to use the feature.
I think it would be reasonable to let the user choose in what format the image should be included for each integration, i.e. via a new option in the webhook integration settings.
