### ISSUE TITLE
Adding already-existing user to organization returns 500 Internal Server Error instead of useful HTTP code

### ISSUE THREAD

**Issue by thecosmicfrog** [grafana/grafana#6486]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?	Grafana v3.1.1 (commit: a4d2708)
- What OS are you running grafana on? Amazon Linux
- What did you do? Added a user to an organization when that user already exists in said organization.
- What was the expected result? Expect a useful HTTP response code, such as 409 Conflict.
- What happened instead? Received 500 Internal Server Error.

I POST'd to /api/orgs/:orgId/users with a JSON block for a user that already exists (user1) in that given organization ID, e.g.

    {
        "loginOrEmail": "user1",
        "role": "Admin"
    }

I expect, for reasons of idempotency, that the server would return a useful HTTP response code such as 409 Conflict. Instead, the server returns 500 Internal Server Error, which makes it difficult to test if a user was added successfully.

**Comment by dpavlos** [comment]
Hi @bergquist, a fix has been pushed to master. I think we can close the issue.

**Comment by thecosmicfrog** [comment]
Excellent, thanks @dpavlos!

**Comment by bergquist** [comment]
@dpavlos thank you!
