### ISSUE TITLE
Corrupt HTML responses on page load (overlaps with previous response)

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#6487]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana v3.1.1 (commit: a4d2708)
- What datasource are you using? (Graphite, Elasticsearch)
- What OS are you running grafana on? (RHEL 6.4) (multiple machines)
- What did you do? (Create a dashboard and refresh the page)
- What was the expected result? (The page should render correctly)
- What happened instead? (The HTML response is corrupted)

**IMPORTANT** If it relates to metric data viz:
[new-dashboard.response.txt](https://github.com/grafana/grafana/files/575280/new-dashboard.response.txt)

**Comment by torkelo** [comment]
strange, I am unable to replicate, and so far this has never been reported for 3.1. 

Can you specify the steps you do? Do you save the new dashboard after creating it? can you replicate it every time?

**Comment by benthorner** [comment]
The issue only happens occasionally. Sometimes it doesn't happen for ages and then we get multiple bursts. We have saved the dashboard - we're just refreshing the page.

We're currently provisioning a machine from scratch to try and isolate what might cause it to occur more (difficult as we can't reproduce it every time!). It's like the Go server is re-using a buffer across requests - how else would data from one request end up in another?

One more thing - when the issue happens, the page loads briefly with JSON in the body, then reloads with the response I've uploaded. Perhaps it's the first response that's invalid/incomplete?

**Comment by benthorner** [comment]
Closing as we can't reproduce this issue consistently. It seems to be caused when Grafana is set to use HTTPS, and happens more often when we clear website data in the browser. For now, our solution is to disable HTTPS in Grafana and use a proxy to terminate SSL elsewhere.
