### ISSUE TITLE
Provide release notes for users who have made backwards-incompatible changes with Influx in 9.4

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#64878]
In https://github.com/grafana/grafana/issues/64825 we are reverting the backend migration of Influx introduced in 9.4. However, at least adding new transformations on Influx after upgrading to 9.4 is incompatible with this reversion. Those users will need to take corrective action once upgrading to a version with the backend migration reversion.

Please investigate which user-initiated additions while in backend mode will break with an upgrade to a version that re-introduces the feature flag. Please document these in the release notes for that version.

**Comment by itsmylife** [comment]
See the Release Notice section in 
- https://github.com/grafana/grafana/pull/64829
- https://github.com/grafana/grafana/pull/64842
