### ISSUE TITLE
ElasticSearch information compiling error "Count 0".

### ISSUE THREAD

**Issue by Lowkkii** [grafana/grafana#64891]
**What happened**:
After a couple of weeks using grafana and configuring the datasource for elasticSearch, during a weekend, specifically in a saturday, after 14 day os usage exactly, the grafana "shutdown" the graphic compiler, or at least, stopping to deal the data received. After some changes and attempts, nothing works, and after four days after this, grafana doens't come any information about it.
The grafana is used in docker container properly by, no modifications are made by docker compose or custom image, and the containers are grouped is ElasticSearch 7.13.1, Graylog-4.0, and a mongoDB. 

**What you expected to happen**:
The error start 1:15AM, so isn't sound a knowing proccess.

**How to reproduce it (as minimally and precisely as possible)**:
I can't explain how is possbile to be reproduce, because doesn't have any registry or log in time range which can describe what happened.

**Anything else we need to know?**:
at the moment, i try to make this procedures:
`systemctl start firewalld` `firewall-cmd --add-port=9200/tcp`
`sudo iptables -t filter -N DOCKER`
`curl -X GET http://x.x.x.x:9200/graylog_0/_search` PS: the internet communications happen, i saw the API response, just the grafana don't process it, and elasticsearch container just can be call by container ip address, not in bridge.
`docker network create force -d bridge` 
rerun docker and restart containers after changes.
back some grafana versions and distros: **9.3.4, 9.1.4, ubuntu-latest**
``docker logs --since 100h --until 48h elasticsearch`` 
``docker logs -f grafana`` 
tried use explore in grafana to debug attempts.

**Environment**:
- Grafana version: 9.4.3 / latest.
- Data source type & version: ElasticSearch 7.10+;
- OS Grafana is installed on: centOS, container is alpine.
- User OS & Browser: Windows 11, tested in firefox, Opera, Edge and Chrome.
- Grafana plugins: none.
- Others: if needed, i'll send in this tread some images to try identify error.

```[tasklist]

```

**Comment by usmangt** [comment]
Hi @Lowkkii,

Thanks for opening this issue.

It sounds like the issue could be the Docker network container env.

Please create a new post at our community forums under Elasticsearch [category](https://community.grafana.com/c/support/elasticsearch/14) by providing some details (in case if you missed any) so that our community members can help you out.

If they say that this is an issue in Grafana then report us back here and we will definitely take a look.

For now, I am closing this issue.
