### ISSUE TITLE
Heatmap logarithmic scale doesn't work

### ISSUE THREAD

**Issue by kkolyan** [grafana/grafana#64912]
Before click "Logarithmic"
![image](https://user-images.githubusercontent.com/3194236/225663967-ba65873c-f42c-435f-a79a-316d8efb20e2.png)
After click
![image](https://user-images.githubusercontent.com/3194236/225664096-5ef083e2-7b73-4eb3-8ce9-d95e83bf5b88.png)

**What happened**:
* I've selected heatmap in dropbox at the right top
* I've set "Calculate from data" to Yes in Heatmap section
* I've clicked Logarithmic at "Y Bucket scale" selector
* Linear persists to be selected and obfuscated error seen in JS console

**What you expected to happen**:
* It's selected and makes heatmap's Y axis scale logarithmic

**How to reproduce it (as minimally and precisely as possible)**:
See "What happened"

**Anything else we need to know?**:

**Environment**:
    Grafana version: Version 9.3.6 (commit: 978237e7cb, branch: HEAD)
    Data source type & version: victoriametrics-datasource 0.1.2, https://github.com/VictoriaMetrics/grafana-datasource
    OS Grafana is installed on: CentOS Linux release 7.7.1908 (Core)
    User OS & Browser: macOS Version 11.5.2 (Build 20G95); Google Chrome | 110.0.5481.177
    Grafana plugins: 
        ae3e-plotly-panel @ 0.5.0
        agenty-flowcharting-panel @ 0.9.1
        bessler-pictureit-panel @ 1.0.1
        blackmirror1-singlestat-math-panel @ 1.1.8
        grafana-clock-panel @ 2.1.3
        grafana-piechart-panel @ 1.6.4
        grafana-worldmap-panel @ 1.0.3
        knightss27-weathermap-panel @ 0.3.5
        marcusolsson-json-datasource @ 1.3.2
        victoriametrics-datasource @ 0.1.2
        vonage-status-panel @ 1.0.11

**Comment by usmangt** [comment]
:Hi @kkolyan,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine. :+1: 

This seems to be also reproducible on play.grafnaa.com with TestDB as Data Source

There are no errors found in the backend logs but at least in the Chrome Dev tools found this in the Console log:

```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'log')
    at onChange (axis.tsx:163:71)
    at RadioButtonGroup.tsx:43:11
    at Object.Ve (react-dom.production.min.js:52:317)
    at Un (react-dom.production.min.js:52:471)
    at nr (react-dom.production.min.js:53:35)
    at Or (react-dom.production.min.js:100:68)
    at yi (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Bt (react-dom.production.min.js:292:189)
    at Kt (react-dom.production.min.js:50:57)
onChange @ axis.tsx:163
(anonymous) @ RadioButtonGroup.tsx:43
Ve @ react-dom.production.min.js:52
Un @ react-dom.production.min.js:52
nr @ react-dom.production.min.js:53
Or @ react-dom.production.min.js:100
yi @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Bt @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:50
Ta @ react-dom.production.min.js:105
Ze @ react-dom.production.min.js:75
Se @ react-dom.production.min.js:74
b.unstable_runWithPriority @ scheduler.production.min.js:18
Ts @ react-dom.production.min.js:122
or @ react-dom.production.min.js:292
Er @ react-dom.production.min.js:73

```

So this seems to be a Frontend issue in my opinion. and will be forwarding it to the team for further investigation.

**Comment by jcdauchy-moodys** [comment]
Same on version 9.4.7 :(

**Comment by dead-claudia** [comment]
Any update?

**Comment by leeoniya** [comment]
huh, this used to work. i wonder when it broke, and why TypeScript does not complain about `value` possibly being `undefined` :thinking: 

![image](https://github.com/grafana/grafana/assets/43234/cd5856fc-fd84-4b3c-be9a-793b83196831)
