### ISSUE TITLE
Multiple templating variables do not update/refresh

### ISSUE THREAD

**Issue by acjackson** [grafana/grafana#6492]
- What Grafana version are you using?  Grafana v3.1.1 (commit: a4d2708)
- What datasource are you using? graphite

- What did you do?
  Use multiple templating variables
- What was the expected result?
  automatically refresh the following templating variables
- What happened instead?
  no refresh. If I use F5 the variable is updated and metrics are displayed.

I've tried "Reload on Dashboard Load" or "Never", but I could not see any difference.

Another strange thing: If I try a metric query (or in the template variable editor) the query url is:
`.../api/datasources/proxy/1/metrics/find/?query=foo.%7Bbar%7D.*`
with no results.

If I do a refresh with the variable SELECTED the query is fine and I get results:
`.../api/datasources/proxy/1/metrics/find/?query=foo.bar.*`

I've used the feature pre3.0, but never experienced such a strange behavior.

**Comment by bergquist** [comment]
I'm not 100% sure I understand you. But when I update template variables on http://play.grafana.org/dashboard/db/issue-6492?var-app=backend&var-app=fakesite&var-server=All&var-interval=$__auto_interval they update correctly. 

One difference between multi and single value is that multi value templates reload once the template menu is closed and not directly when adding/removing one template value. Perhaps that was the problem?

**Comment by acjackson** [comment]
Your example works perfectly.

> One difference between multi and single value is that multi value templates reload once the template menu is closed and not directly when adding/removing one template value. Perhaps that was the problem?

No it is not that. :(

On my Dashboard: If I select the first variable, the second won't get updated. If I select 'All' there are no values on the second variable.
If I edit the second templating variable it works once until the next reload. It is really strange.

I have refresh 'never' on both of my templating variables.

I think I'll do a snapshot of my vm and try Grafana 4 beta1 :)

**Comment by bergquist** [comment]
@acjackson Can you reproduce the problem in grafana 4 beta1?

**Comment by bergquist** [comment]
@acjackson Could you reproduce this problem in grafana 4.0.1?

**Comment by acjackson** [comment]
I got the same issue with 4 beta1 and 4.0.1.

To clarify my problem I attached some screenshots.
![fail](https://cloud.githubusercontent.com/assets/8512902/21009296/2d0bc390-bd46-11e6-839e-35b4f764b549.png)
![success](https://cloud.githubusercontent.com/assets/8512902/21009297/2d0f19a0-bd46-11e6-860e-637e3e449610.png)




The first variable 'site' works as expected. 
![first_variable](https://cloud.githubusercontent.com/assets/8512902/21008942/5c781036-bd44-11e6-8b13-33497616ac4f.png)

But if I use this first variable on my second variable, I get NO results (almost every time, sometimes it works).
![second_variable_no_values](https://cloud.githubusercontent.com/assets/8512902/21008943/5c7a42e8-bd44-11e6-8f93-b98fca4f7557.png)

If I edit the query and use a valid value (see first variable) instead of the variable it works.
![second_variable_wo_first_works](https://cloud.githubusercontent.com/assets/8512902/21008944/5c7e1b7a-bd44-11e6-92f0-b4a83ae54dbb.png)


Browsing the db with the graphite composer everything looks fine.

**Comment by torkelo** [comment]
This is strange, no one else has reported any issue with updating template variables and unable to replicate this.

**Comment by dellis23** [comment]
I am having the same issue.  This only seems to have popped up recently when I changed from updating "Never" to updating "On Dashboard Load."  Now I can't seem to get the values of the secondary template variable to come back.  I am also using version 3.1.1.

@acjackson Did you ever come up with a workaround?

**Comment by torkelo** [comment]
Yes upgrade to grafana v4.1

**Comment by lmt73** [comment]
I seem to be experiencing this in 4.6.2-1.

**Comment by machytkafitanalytics** [comment]
Hi, I have this problem on v4.6.1 (commit: cac8b97) - datasource PostgreSQL.
I defined 2 template variables:

![image](https://user-images.githubusercontent.com/17564930/34722800-8c1ab928-f548-11e7-94bf-43da310c920a.png)

When I change "Shop" then Grafana refreshes both second template variable "Country" (with proper list of countries for given shop) and dashboard too.
But when I only change "Country" for already chosen "Shop" Grafana does not refresh dashboard and I have to do it manually. 

Which is currently quite difficult problem for us because - although we tried very hard - people are somehow not willing to accept that "it does not work automatically"...

**Comment by torkelo** [comment]
strange, unable to replicate, can you have chrome  dev tools open when you change Country? Check developer console, and network tab, anything?

**Comment by machytkafitanalytics** [comment]
Well, looks like there is something unstable about PostgreSQL datasource - at least we did not have these problem on any other datasource (we use Elasticsearch, InfluxDB, MySQL too). 
I tested problem described above in different ways and in different browsers and I got very strange erratic behavior. 

- In Chrome window which was opened for a longer time I had still the same error with second temp variable not refreshing dashboard - it simply did not do anything in network tab in dev tools (no xhr.send call)
- When I opened new Chrome tab with this dashboard I got error telling me that my postgresql datasource does not exist (not true of course). But when I did "hard" reload this tab with CTRL+F5 several times everything suddenly started to work. And I am unable to repeat even error with second temp variable I sent you.
- When I opened dashboard in Firefox window I got strange error "error near $". It too persisted over several hard reloads of the tab and then suddenly all started to work.

So now (after several "hard" reloads of each browser window) everything works and I feel like a real fool because I am unable to repeat it even on any machine where it previously did not work too.

OK. I will instruct people to do "hard" reload with CTRL+F5 of the browser window until everything works. This is more or less acceptable. I am sorry for alarm I should test more in the first place...

**Comment by echotao** [comment]
I was have the same issue with IE, after I change to Chrome it is gone.

**Comment by xxwassyxx** [comment]
I to am seeing this exact same issue with 5.1
I can set both variables to load on time or even on dashboard load and the result is the same. Variables are never re-queried to see if there are new values. Only the initial call is made. Looking at dev tools I can see that my query that I set for he variable is never again called.

**Comment by owengo** [comment]
Same issue on v5.2.0-pre1 (commit: 75993971c), with Zabbix datasource.
I have 2 variables: $Env and $Service , $Env is chosen between 'prod' and 'preprod' , $Service is a regexp like /.*-([a-z]+-$Env)-.*/  . When I change en Env variable the service list is not refreshed.

**Comment by vandenbosch** [comment]
I am running into the same (or similar) issue with grafana-5.1.3-1.
I have several instances up:

Original: grafana-2.5.0-1 (local graphite-web-0.9.13, carbon-0.9.13, whisper-0.9.13).  This is a single box with a single instance of carbon running

Test:  grafana-5.1.3-1 (local graphite-web-0.9.16-2, python-carbon-0.9.16-1, python-whisper-0.9.16-1). This is a single box with a 2 instances of carbon running behind a local realy.

“Original” -> “Original” graphite-web works as expected
“Original” -> “Test” graphite-web does not work
“Test” -> “Test” graphite-web does not work
“Test” -> “Original” graphite-web works as expected

This leads me to think it my "graphite-web" instance running my "Test" box.  But I cannot see any issues with that (though there still might be).  I am getting the non-updated variables independent to what refresh configuration I chose.  If I reload the page (F5) it updates and data is shown.

**Comment by marefr** [comment]
Would recommend trying out [v5.3-beta1](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#530-beta1-2018-09-06) that has some changes/fixes for template variables.

**Comment by osimar-medeiros** [comment]
I am running PostgreSQL 10 as datasource for Grafana v5.3.1 (08c7908) and that same behavior is happening.

'Dependant' variable only refreshes when I force to time range change refresh. Or the dashboard itself.

Either way, the variable does not refresh automatically.

**Comment by marefr** [comment]
@osimar-medeiros we did a fix in v5.3.2, see #13600. If you're still experience problems please open a new issue and we'll take it from there. Thanks

**Comment by kodybrown** [comment]
(I found this thread looking for something else..)
I ran into this when I started using Grafana v6.0.1 (0c44a04) with a Postgres datasource. (Dev Edge and Chrome)

I got around it by including the first variable in the second variable's query. Do this, even if the value isn't necessary in the second variable. I think by just referencing the first variable in the second's query, the system knows it needs to update the second variable whenever the first changes.

`Var1 = 'select name from table where type_id = 1 order by upper(name);'`

`Var2 = 'select name from table2 where type_id = 2 order by upper(name) and '${Var1:raw}' != 'All';'`

`Var3 = 'select name from table3 where type_id = 3 order by upper(name) and '${Var1:raw}' != '' and '${Var2:raw}' != '';'`

Maybe that will help..

**Comment by jstrelka** [comment]
Still getting the same error of a dashboard variable not updating in Grafana v6.4.3.

**Comment by shehrozeee** [comment]
facing the same issue on 6.4.3

**Comment by sahare92** [comment]
Getting the same error on Grafana v6.6.0

**Comment by gatopeich** [comment]
Facing this issue on v6.6.1 with a SimpleJson datasource.
First of the ad-hoc filter vars only refreshes when user starts typing on it, not by clicking with mouse. The second one seems fine.
Seems to happen more often if the back-end service is heavily loaded.
Seems to stop happening if there is a default value stored with the dashboard / passed in link.

**Comment by allenlongbaobao** [comment]
meeting the same issue
version: Grafana v7.2.1 (72a6c64532)
i copy other's existing workspace. when i change the variable's value, new values can't make sense.
my solution: 
1. delete all old variables, then save, you can get the result in chrome dev tool network line.
2. add the new variables, then save
3. refresh the page, my issue is gone.

my conjecture:
   is it possible grafana backend handles copied wordspace updated request, missed the variables change when it has old values. maybe it's an easy bug to fix.
hope helpful!

**Comment by louiszhanghaibin** [comment]
facing the same issue here in ver6.6.2
It's kind of annoying that once I upload my templates automatically by script, I still should refresh the variables by hand.
Does any one have a workaround for current ver?
Please fix this issue!

**Comment by RaananHadar** [comment]
I have the same issue on Grafana cloud with ver 7.3.3 (2489dc4d3a), I think this issue needs to be re-opened.

**Comment by jeremypeters** [comment]
Same issue on 7.4.2. Frustrating stuff.
