### ISSUE TITLE
Got grunt error when building Grafana 3.1.1 from source

### ISSUE THREAD

**Issue by danielmorlock** [grafana/grafana#6493]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- **What Grafana version are you using?**
  Git Tag v3.1.1
- **What datasource are you using?**
  graphite
- **What OS are you running grafana on?**
  Gentoo
- **What did you do?**
  Cloned the repo and built as described in the README.
- **What was the expected result?**
  Successful build without fatal grunt errors
- **What happened instead?**
  Build stopped with the build.log.txt and grunt.log.txt
[build.log.txt](https://github.com/grafana/grafana/files/576033/build.log.txt)
[grunt.log.txt](https://github.com/grafana/grafana/files/576032/grunt.log.txt)

**Comment by daniellee** [comment]
Closing this. If you are still having problems with grunt I can reopen the issue.
