### ISSUE TITLE
Add support for AWS GovCloud through the CloudWatch data source

### ISSUE THREAD

**Issue by rogerswingle** [grafana/grafana#6494]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

AWS has a separate region for government workloads, [US-Gov-West-1](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/whatis.html).  It would be awesome if the CloudWatch data source could pull metrics for GovCloud.

Please include this information:
- What Grafana version are you using?
    3.1.1
- What datasource are you using?
    CloudWatch
- What OS are you running grafana on?
   RHEL 7.2
- What did you do?
   Went to set up a cloudwatch connection
- What was the expected result?
   I'd have the ability to connect to AWS GovCloud
- What happened instead?
  I did not have the ability to connect to AWS GovCloud

**Comment by bergquist** [comment]
closed by #6495
