### ISSUE TITLE
Organization Filter harms discoverability

### ISSUE THREAD

**Issue by alexzorin** [grafana/grafana#6496]
**I'm submitting a ...** 
- [x] Feature request

`grafana-4.0.0-1478529331pre1.x86_64`

Relates to #2609 and #5408

So, in our case (hosting provider), we might use a single Grafana instance to house many dozens of projects (as Organizations). We need to do this because we need the datasource isolation, which is part of what makes Grafana so great.

Before the org. filter, I (or rather, my colleagues, who a less intimately familiar with what data and dashboards are available) could quickly see if something is present or not. Now it is a bit of a guessing game with the filter.

So, my feature request would be to get the previous 'discoverability' back. 

Possible implementation ideas:

- Organization list widget for home dashboard
- Add an 'infinite scroll', in addition to the search filter.
- Make the maxOrgs = 10 limit not hardcoded.

Thanks!

**Comment by bergquist** [comment]
Organisation list panel sounds like a good long term solution. 

Im not sure about making maxorgs configurable. What limit would you set?

**Comment by alexzorin** [comment]
I changed it to 100 in our deployment. I only suggest it as a short-term escape hatch for myself (that does not require hacking compiled assets). I am fine with shooting myself in the foot by setting it high, but sure, it's not a real long-term solution.

I'm in favor of infinite scroll idea to be honest, because on the face of it, it appears to be a relatively minor variation to the current approach, and regains the ability to 'parouse'.

**Comment by torkelo** [comment]
how do you get the ` datasource isolation` part? Separate InfluxDB databases? 

Multi org setups are not a very high prio right now so we are not likely spending any time on improving that part. We might introduce user teams and dashboard folders to help large Grafana setups.

**Comment by torkelo** [comment]
but I am fine removing the org search, was never really happy that :)
