### ISSUE TITLE
Legacy Alerting: Failed to save `annotation` and/or `alert` when data exceeds supported column values

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#64968]
In the legacy alerting, we execute two writes when an alert is evaluated:

- One for the `eval_data` field in the `alert` table
- One for the `data` field in the `annotations` table

Both of these columns are of the type `DB_Text` and thus have a size limit in the amount of data they can hold. 

We'll fail both of these writes when the amount of data doesn't fit into the column with:

```
logger=alerting.resultHandler t=2023-03-17T13:46:01.105742699Z level=error msg="Failed to save annotation for new alert state" error="Error 1406: Data too long for column 'data' at row 1"
```

and

```
logger=alerting.resultHandler t=2023-03-17T13:46:01.086997238Z level=error msg="Failed to save state" error="Error 1406: Data too long for column 'eval_data' at row 1"
```

We should fix this; some ideas are:

- Truncate the data (then, how do we let the user know?)
- Increase the column size (should we?)
- Do nothing (this is legacy and thus we should not fix)

**Comment by grobinson-grafana** [comment]
How much data was being written in the example above?

**Comment by gotjosh** [comment]
Good shout, I forgot to include that, the series being alerted one had:

- 300 series
- The label set of each series had roughly 250 characters (no unicode characters there the same in runes)
