### ISSUE TITLE
Alerting: Permissions needed: users:read

### ISSUE THREAD

**Issue by iculda** [grafana/grafana#65005]
**What happened**: When i tried to create an alert on save or on cancel i got this
You'll need additional permissions to perform this action. Permissions needed: users:read
My role is admin and login is performed via azure_auth
I tried the same with admin account and i'ts working good
This started to happend after upgrade from 9.2.2 to 9.4.3
I noticed that in console there is a call to /api/users/32 (not sure what 32 means i assume that is user id) with 403 error code   

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: Try to create a new alert and click save

**Anything else we need to know?**:

**Environment**: AKS (grafana official helm chart)
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
> AKS (grafana official helm chart)

sorry @iculda--what specific helm chart are you using? There are several.

**Comment by zuchka** [comment]
also, could you please try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to `debug` and note any errors. For printing to console, [set the console logs to `debug`](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) as well.

**Comment by iculda** [comment]
@zuchka we are using helm chart version: 6.52.4
and in the errors i can see the following 
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-20T22:54:49.986600569Z level=info msg="Request Completed" method=GET path=/api/users/32 status=403 remote_addr=10.188.4.151 time_ms=13 duration=13.028741ms size=160 referer=https://xxx.com/alerting/new handler=/api/users/:id

logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-20T22:54:49.986248468Z level=info msg="Access denied" userID=32 accessErrorID=ACE1654714549 permissions="action:users:read scopes:global.users:id:32"

logger=cleanup t=2023-03-20T22:45:48.53389585Z level=info msg="Completed cleanup jobs" duration=262.134314ms

logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-20T22:45:20.152365374Z level=info msg="Request Completed" method=GET path=/api/users/32 status=403 remote_addr=10.188.4.145 time_ms=14 duration=14.227244ms size=160 referer=https://xxx.com/alerting/new handler=/api/users/:id

logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-20T22:45:20.152249073Z level=info msg="Access denied" userID=32 accessErrorID=ACE0080087467 permissions="action:users:read scopes:global.users:id:32"

Tomorrow i will try to upt app in debug mode and give you another set of logs
Thank you

**Comment by iculda** [comment]
Hello again
Here are logs in the debug mode
`logger=ngalert.scheduler t=2023-03-22T11:31:30.013495943Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-03-22T11:31:24.958036363Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:31:24.958022963Z
logger=ngalert.scheduler t=2023-03-22T11:31:20.014321864Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.api t=2023-03-22T11:31:19.666103916Z level=debug msg="user does not have access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:31:19.651196816Z level=debug msg="cache permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:31:19.634177159Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-32
logger=ngalert.scheduler t=2023-03-22T11:31:10.013505248Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-03-22T11:31:09.957791298Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:31:09.957765597Z
logger=ngalert.scheduler t=2023-03-22T11:31:00.012487032Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.api t=2023-03-22T11:30:59.649134664Z level=debug msg="user does not have access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:30:59.635711315Z level=debug msg="cache permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:30:59.621892652Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-32
logger=ngalert.multiorg.alertmanager t=2023-03-22T11:30:55.116668024Z level=debug msg="done synchronizing Alertmanagers for orgs"
logger=alertmanager org=1 t=2023-03-22T11:30:55.088571666Z level=debug msg="neither config nor template have changed, skipping configuration sync."
logger=ngalert.multiorg.alertmanager t=2023-03-22T11:30:55.064206183Z level=debug msg="synchronizing Alertmanagers for orgs"
logger=ngalert.sender.router t=2023-03-22T11:30:54.997522159Z level=debug msg="Finish of admin configuration sync"
logger=ngalert.sender.router t=2023-03-22T11:30:54.997489758Z level=debug msg="Grafana is configured to send alerts to the internal alertmanager only. Skipping synchronization with external alertmanager" org=1
logger=ngalert.sender.router t=2023-03-22T11:30:54.997421857Z level=debug msg="Attempting to sync admin configs" count=1
logger=ngalert.state.manager t=2023-03-22T11:30:54.958509084Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:30:54.958496484Z
logger=secrets t=2023-03-22T11:30:54.7075066Z level=debug msg="Removing expired data keys from cache finished successfully"
logger=secrets t=2023-03-22T11:30:54.7074625Z level=debug msg="Removing expired data keys from cache..."
logger=ngalert.scheduler t=2023-03-22T11:30:50.012774982Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.scheduler t=2023-03-22T11:30:40.012833648Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-03-22T11:30:39.958228095Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:30:39.958201194Z
logger=ngalert.api t=2023-03-22T11:30:39.627284874Z level=debug msg="user has no access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:30:39.61344853Z level=debug msg="cache permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:30:39.600438612Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-32
logger=ngalert.scheduler t=2023-03-22T11:30:30.013853888Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-03-22T11:30:24.958432878Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:30:24.958409777Z
logger=ngalert.scheduler t=2023-03-22T11:30:20.013607123Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.api t=2023-03-22T11:30:19.626766764Z level=debug msg="user does not have access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:30:19.61227729Z level=debug msg="cache permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:30:19.599088058Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-32
logger=ngalert.scheduler t=2023-03-22T11:30:10.014078818Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.state.manager t=2023-03-22T11:30:09.958698241Z level=debug msg="Recording state cache metrics" now=2023-03-22T11:30:09.958684741Z
logger=ngalert.scheduler t=2023-03-22T11:30:00.015851757Z level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0
logger=ngalert.api t=2023-03-22T11:29:59.578342378Z level=debug msg="user has no access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:29:59.564998322Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-22T11:29:59.508736795Z level=info msg="Request Completed" method=GET path=/api/users/32 status=403 remote_addr=10.188.4.151 time_ms=13 duration=13.070448ms size=160 referer=https://bbb.xxx.com/alerting/new handler=/api/users/:id
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-22T11:29:59.508644792Z level=info msg="Access denied" userID=32 accessErrorID=ACE7249535591 permissions="action:users:read scopes:global.users:id:32"
logger=accesscontrol.service t=2023-03-22T11:29:59.508343882Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=ngalert.api t=2023-03-22T11:29:58.342945118Z level=debug msg="user has no access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:29:58.328581931Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:29:58.320542559Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=live t=2023-03-22T11:29:56.596671341Z level=debug msg="Client connected" user=32 client=0e1185e4-6dee-459f-b532-01fe134d5ea8
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-22T11:29:56.453844501Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=10.188.4.148 time_ms=39 duration=39.27023ms size=0 referer= handler=/api/live/ws
logger=accesscontrol.service t=2023-03-22T11:29:56.453579792Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=ngalert.api t=2023-03-22T11:29:56.353242092Z level=debug msg="user does not have access to any namespaces"
logger=accesscontrol.service t=2023-03-22T11:29:56.339396323Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=avatar t=2023-03-22T11:29:56.205294779Z level=debug msg="avatar update" err="gravatar unreachable: Get \"https://secure.gravatar.com/avatar/1b080c6c1a898963e2c889e2e61467fd?d=retro&r=pg&size=200\": EOF"
logger=avatar t=2023-03-22T11:29:56.170258791Z level=debug msg="Fetching avatar url with parameters" url="https://secure.gravatar.com/avatar/1b080c6c1a898963e2c889e2e61467fd?d=retro&r=pg&size=200"
logger=avatar t=2023-03-22T11:29:56.170185289Z level=debug msg="avatar.fetch(fetch new avatar)" url=https://secure.gravatar.com/avatar/1b080c6c1a898963e2c889e2e61467fd?
logger=accesscontrol.service t=2023-03-22T11:29:56.170025183Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:29:55.167891224Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32
logger=accesscontrol.service t=2023-03-22T11:29:55.15566781Z level=debug msg="cache permissions" key=rbac-permissions-0-user-32
logger=accesscontrol.service t=2023-03-22T11:29:55.140186185Z level=debug msg="fetch permissions from store" key=rbac-permissions-0-user-32
logger=infra.kvstore.sql t=2023-03-22T11:29:55.121373247Z level=debug msg="kvstore value not found" orgId=1 namespace=serviceaccounts key=hideApiKeys
logger=ngalert.multiorg.alertmanager t=2023-03-22T11:29:55.063106673Z level=debug msg="done synchronizing Alertmanagers for orgs"
logger=accesscontrol.service t=2023-03-22T11:29:55.055607319Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-32`
Thank you

**Comment by yuri-tceretian** [comment]
In my memory, this action has never been required. 
```
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-22T11:29:59.508736795Z level=info msg="Request Completed" method=GET path=/api/users/32 status=403 remote_addr=10.188.4.151 time_ms=13 duration=13.070448ms size=160 referer=https://bbb.xxx.com/alerting/new handler=/api/users/:id
logger=context userId=32 orgId=1 uname=aaa@xxx.com t=2023-03-22T11:29:59.508644792Z level=info msg="Access denied" userID=32 accessErrorID=ACE7249535591 permissions="action:users:read scopes:global.users:id:32"
```
from logs I see that there is API call to users endpoint... Probably UI does something in the background. @konrad147 @gillesdemey do you have any idea?

**Comment by konrad147** [comment]
It might be this issue https://github.com/grafana/grafana/pull/64544
It's been already fixed, not sure if released

**Comment by reuvygroovy** [comment]
Has this been fixed? I still have this error in Grafana v9.5.1

**Comment by liangxinshang** [comment]
i also have this question in Granfana v9.5.2.  I try to use Admin token to get all userlist

**Comment by thomasbromkapsdata** [comment]
I did some test across differents versions of Grafana 9.3.2, 9.5.0, 9.5.9 with endpoint api/users and i always got this kind of error with an admin service account:
"{\"accessErrorId\":\"ACE5125539562\",\"message\":\"You'll need additional permissions to perform this action. Permissions needed: users:read\",\"title\":\"Access denied\"}".
On the other hand, by example, endpoint: api/dashboards/home work perfectly.
No news on that ?

**Comment by marinnedea** [comment]
> I did some test across differents versions of Grafana 9.3.2, 9.5.0, 9.5.9 with endpoint api/users and i always got this kind of error with an admin service account: "{"accessErrorId":"ACE5125539562","message":"You'll need additional permissions to perform this action. Permissions needed: users:read","title":"Access denied"}". On the other hand, by example, endpoint: api/dashboards/home work perfectly. No news on that ?

Please check:
* https://github.com/grafana/grafana/issues/72103#issuecomment-1651684041
* https://grafana.com/docs/grafana/latest/developers/http_api/user/#user-api
