### ISSUE TITLE
linux "make run " error

### ISSUE THREAD

**Issue by wgh728** [grafana/grafana#65015]
![image](https://user-images.githubusercontent.com/7524530/226225114-17c8a991-0a54-4089-a00f-fe9ac5f46046.png)

As shown in the figure, when building the local environment of Grafana and starting compilation, the above error is reported by ```make run ```. The same error occurs in ubuntu and centos

```
root@DESKTOP-NPDR6E4:~/grafana# go run build.go setup
Version: 9.5.0, Linux Version: 9.5.0, Package Iteration: 1679275614pre
go install -v ./pkg/cmd/grafana-server
github.com/grafana/grafana/pkg/util/cmd
github.com/grafana/grafana/pkg/cmd/grafana-server
root@DESKTOP-NPDR6E4:~/grafana# go run build.go build
Version: 9.5.0, Linux Version: 9.5.0, Package Iteration: 1679275626pre
building binaries build
building grafana ./pkg/cmd/grafana
rm -r ./bin/linux-amd64/grafana
rm -r ./bin/linux-amd64/grafana.md5
go build -ldflags -w -X main.version=9.5.0-pre -X main.commit=ae07bf7ce5 -X main.buildstamp=1679082313 -X main.buildBranch=main -o ./bin/linux-amd64/grafana ./pkg/cmd/grafana
# github.com/grafana/grafana/pkg/services/sqlstore/migrator
pkg/services/sqlstore/migrator/sqlite_dialect.go:132:24: undefined: sqlite3.Error
pkg/services/sqlstore/migrator/sqlite_dialect.go:143:24: undefined: sqlite3.Error
pkg/services/sqlstore/migrator/sqlite_dialect.go:151:41: undefined: sqlite3.ErrConstraintUnique
exit status 1
exit status 1
root@DESKTOP-NPDR6E4:~/grafana#

```

**Comment by gabrielthomasjacobs** [comment]
Hello @usmangt, I'm also seeing this issue.  

Here's some extra info:  
- I'm using windows running the environment in WSL  
- Using the main branch of Grafana  
- [url to instructions](https://grafana.com/blog/2021/03/03/how-to-set-up-a-grafana-development-environment-on-a-windows-pc-using-wsl/)

**Comment by kminehart** [comment]
This error happens when CGO_ENABLED=0.

**Comment by TJChong92** [comment]
with CGO_ENABLED=1, new error pop out as below.
![image](https://github.com/grafana/grafana/assets/76833412/a2b56005-710b-40a1-8862-aaead1a93c60)
