### ISSUE TITLE
Allow ldap.toml file using relative path in config.ini

### ISSUE THREAD

**Issue by changhuixu** [grafana/grafana#6502]
* **I'm submitting a ...**
- [x] Feature request/ or improvement

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
Promethus
- What OS are you running grafana on?
Windows
- What was the expected result?
Currently, we have to put a full path for ldap.toml .
Could you modify "/pkg/setting/setting.go" 
```
LdapConfigFile = ldapSec.Key("config_file").String()
```
to be
```
LdapConfigFile = makeAbsolute(ldapSec.Key("config_file").String(), HomePath)
```

Thanks a lot.

**Comment by daniellee** [comment]
Think this was fixed a long time ago. Closing.

**Comment by daniellee** [comment]
Maybe I was too fast - is this different on Windows? A relative path works on Linux.
