### ISSUE TITLE
With DataSourceVariableSupport, Query Editor not displaying error messages and access Panel Data

### ISSUE THREAD

**Issue by hardikbajaj** [grafana/grafana#65038]
**What happened**:

Using Datasource query editor for variable query support, by extending DataSourceVariableSupport, and adding it in `this.variables` of the datasource.ts. The query editor is working fine, but is not able to use the `Panel Data`, which is a part of `QueryEditorProps`. This works fine in Explore, but not in Variable Query Editor. Also, the error messages sent from backend are not being displayed

**What you expected to happen**:

Variable Query Editor is not displaying error messages sent by response. The Error messages should be displayed as Popover Alerts whenever the query failed. Also, the `Panel Data` (data)  from  `QueryEditorProps` should also be accessible inside the Default Datasource Query Editor, so that Frame response, Loading State etc can also be accessed

**How to reproduce it (as minimally and precisely as possible)**:

- Add DataSourceVariableSupport to your datasource
- Run the queries and see if the expected error message is being displayed.

**Anything else we need to know?**:

Looks like response Panel Data is not being populated inside query editor in VariableQuerySupport

**Environment**:
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: 
- Others:

```[tasklist]

```

**Comment by hardikbajaj** [comment]
Hey @zuchka , can anyone from Plugin platforms look into it, as this way of adding the variables support to query support is in `alpha`, I couldn't find any good documentations and references.

**Comment by tolzhabayev** [comment]
Not sure we are the right squad to look at it @grafana/dashboards-squad ?

**Comment by hardikbajaj** [comment]
Hey @tolzhabayev , can you tag someone from @grafana/dashboards-squad who might have some insights on it?

**Comment by evictorero** [comment]
Hi @hardikbajaj sorry for the delay. I don't fully understand the issue. 
Can you reproduce this issue in [Grafana Play](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) or is it related to plugin development instead of a Grafana implemented feature?
