### ISSUE TITLE
How to use aliasByNode in grafana ?

### ISSUE THREAD

**Issue by dongfand** [grafana/grafana#6503]
I want to simplify the query metics by aliasByNode, but I don;t know how to use it ?
![capture](https://cloud.githubusercontent.com/assets/23330137/20090035/a514ca32-a5c5-11e6-9224-4ea9090748d5.PNG)
as above picture, the character string in blue line  is of no meaning , how to not show this string  by aliasByNode ?  what I want to get is like :NCIR.rs.queue-depth.1.block-size.16384.169-254-100-27.jobs.1.read.iops , just leave out the string, which makred in blue line 

thanks

**Comment by bergquist** [comment]
That's not possible using aliasByNode. But you could remove it with the aliasSub function. https://graphite.readthedocs.io/en/0.9.10/functions.html#graphite.render.functions.aliasSub
