### ISSUE TITLE
XY Chart: problems with tooltip

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#65042]
Dear grafana community,

grafana is no longer able to display all values of the query in the tooltip compared to v9.1.6. Previously, additional queried columns were displayed in the tooltip. With 9.4.3, only the x and y values are displayed, but no additional query values.

See [this screenshot](https://i.ibb.co/LJKz03F/comparison-grafana.png), performed with the same data but the different Grafana versions.

@leeoniya mentioned this in already in #57221 (issue was closed by mistake)

Thank you

**Comment by zuchka** [comment]
@leeoniya do you have any input here? thx

**Comment by leeoniya** [comment]
sorry about that, should be fixed by https://github.com/grafana/grafana/pull/65027
