### ISSUE TITLE
{"find": "terms", "field": "@xxx"} doesn't work on Grafana 4

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#6505]
Good morning,

* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana 4.0 nightly build
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Docker (grafana/grafana)
- What did you do? Trying to find terms with a specific field.
- What was the expected result? Find all the terms that I found on Grafana 3.1.1.
- What happened instead? Nothing appeared.

This is working on Grafana 3.1.1 : 
![1](https://cloud.githubusercontent.com/assets/23166349/20092269/7b101d6e-a597-11e6-835e-b27adf02dce2.png)

On Grafana 4.0 nightly build it's doesn't work: 
![2](https://cloud.githubusercontent.com/assets/23166349/20092286/97e9c890-a597-11e6-9c15-b4b8531751e4.png)

But, this is working :
![3](https://cloud.githubusercontent.com/assets/23166349/20092335/dd415430-a597-11e6-86ff-905d424299cb.png)

Thank you for your help.

**Comment by bergquist** [comment]
Works fine on http://play.grafana.org/dashboard/db/elasticsearch-templated Could you please open chrome dev tool and see if you get an error in the console?

**Comment by ChamMach** [comment]
I have just these errors when I load Grafana 4 (I don't have them on Grafana 3.1.1) : 

![4](https://cloud.githubusercontent.com/assets/23166349/20100252/f556c558-a5bc-11e6-86cb-8c2ea3f09037.png)

**Comment by bergquist** [comment]
@ChamMach what browser are you using?

**Comment by ChamMach** [comment]
I use Google Chrome and I downloaded the latest version (54.0.2840.87 m). Now I don't have any error on chrome dev tool but the problem is still present.

**Comment by bergquist** [comment]
Could you please paste the dashboard.json? From the error in devtools it fails to parse some json. Could it be possible that the template query contains some broken char?

**Comment by ChamMach** [comment]
```
{
  "id": 1,
  "title": "New dashboard",
  "tags": [],
  "style": "dark",
  "timezone": "browser",
  "editable": true,
  "sharedCrosshair": false,
  "hideControls": false,
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "text": "All",
          "value": "$__all"
        },
        "datasource": "elasticsearch",
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "test",
        "options": [
          {
            "text": "All",
            "value": "$__all",
            "selected": true
          }
        ],
        "query": "{\"find\":\"terms\",\"field\":\"@metric\"}",
        "refresh": 0,
        "regex": "",
        "sort": 0,
        "tagValuesQuery": null,
        "tagsQuery": null,
        "type": "query"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "schemaVersion": 13,
  "version": 1,
  "links": [],
  "gnetId": null,
  "rows": [
    {
      "collapse": false,
      "height": "250px",
      "isNew": false,
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": "elasticsearch",
          "editable": true,
          "error": false,
          "fill": 1,
          "id": 1,
          "isNew": true,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 2,
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "bucketAggs": [
                {
                  "id": "2",
                  "settings": {
                    "interval": "auto"
                  },
                  "type": "date_histogram"
                }
              ],
              "dsType": "elasticsearch",
              "metrics": [
                {
                  "id": "1",
                  "type": "count"
                }
              ],
              "refId": "A",
              "timeField": "@timestamp"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeShift": null,
          "title": "Panel Title",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "Dashboard Row",
      "titleSize": "h6"
    }
  ]
}
```
I'm not sure about that, even if I write and rewrite the right query I have the same error. And, I noticed that I have the same error with the field "@value ".

**Comment by bergquist** [comment]
Just to confirm. http://play.grafana.org/dashboard/db/elasticsearch-templated?editview=templating is working for you?

**Comment by ChamMach** [comment]
Yes it's working for me.

**Comment by ChamMach** [comment]
I found a solution if you have the same problem : 

Create a query like this (with unique count) : 
![sol1](https://cloud.githubusercontent.com/assets/23166349/20103932/28833eca-a5cc-11e6-9517-762f288404a7.png)

After that, go on your template variable and rewrite your query : 
![sol2](https://cloud.githubusercontent.com/assets/23166349/20103982/63db4cec-a5cc-11e6-8745-146995e2a920.png)

I think it's because Grafana could not load data. Thank's @bergquist for your help and your time.

**Comment by AkshayAwate** [comment]
same thing does not work on grafana 7.4.3, ES 6.8.2
