### ISSUE TITLE
mssql: query variable returns empty the variable keeps the last non null value

### ISSUE THREAD

**Issue by kosza** [grafana/grafana#65053]
**What happened**:
If a query variable returns from mssql without row the values of this variable keeps the previous non null value and Grafana shows an error:
 
![grafana_templating_error_001](https://user-images.githubusercontent.com/31093540/226345869-987c3ec2-5905-473d-9873-f18dc9e1a5ac.png)

**What you expected to happen**:
In case when no return value the variable should be empty.

**How to reproduce it (as minimally and precisely as possible)**:
Create
- variable, var1, text box
- variable, var2, query, `select city_id from dbo.cities where city_name = '$var1'`
- panel, text, content: ${var2}
- panel, table, table_city_id, `select city_id from dbo.cities where city_name = '$var1'`
- panel, table, table_streets, `select street_name from dbo.streets where city_id = '$var2'`

Do
- type a city name into var1, you will see the $var2 in the text, the list of the streets in the tabe_streets and the city_id in the table_city_id (table_city_id is the same value as $var2)
- type a non exists city name, you will get an error about var2, table_city_id will be empty but in the text and table_streets will show the previous values

Or just create a query variable from mssql with `select 'grafana' from dbo.abc where 2=1` and the templating error will be showed.

**Anything else we need to know?**:
This behavior appeared from 9.4.1.
It seems that the problem is in the query variables. In the panel query it works properly.

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: MSSQL Server 13.0.5102.14
- OS Grafana is installed on: Ubuntu 18.04.6 LTS
- User OS & Browser: Windows 10, Opera 96.0.4693.50, Chrome 111.0.5563.65
- Grafana plugins: native mssql, 5.0.0

**Comment by zuchka** [comment]
Thanks for creating this issue, @kosza 

could you please copy and paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by kosza** [comment]
Hi @zuchka ,

I think it won't be useful because in the `troubleshooting help` you will see the previous values in the panel query. It would be better a similar `get help` about the dashboard (variables, panels).
