### ISSUE TITLE
How to use aliasSub function  in grafana to remove a string ?

### ISSUE THREAD

**Issue by dongfand** [grafana/grafana#6506]
I want to simplify the query metics by aliasSub function , but I don;t know how to use it ?
![capture](https://cloud.githubusercontent.com/assets/23330137/20092373/ca12f3b0-a5d2-11e6-9208-d6d6b63ea1f0.PNG)
as above picture, the character string in blue line is of no meaning , how to not show this string  ? what I want to get is like :NCIR.rs.queue-depth.1.block-size.16384.169-254-100-27.jobs.1.read.iops , just leave out the string, which makred in blue line
It is really appreciate if you can help me .thanks

**Comment by torkelo** [comment]
please no questions on github, use mailing list instead :)
http://grafana.org/support/

**Comment by Data-drone** [comment]
there is only commercial support there? is there a free mailing list?

**Comment by torkelo** [comment]
Commercial support services: https://grafana.com/services/support
Community site for questions: https://community.grafana.com/

**Comment by torkelo** [comment]
You can use our worldping service for that: https://grafana.com/cloud/worldping

**Comment by torkelo** [comment]
sorry wrong issue
