### ISSUE TITLE
Alerting: Docs: `values` property is not documented in webhook notifier response body

### ISSUE THREAD

**Issue by aSemy** [grafana/grafana#65070]
**What happened**:

I set up a custom server to handle a webhook alert from Grafana.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/897017/226422495-ee867709-9309-4681-9d8a-da9dc95cf712.png">

During decoding, I received an error because of an unexpected property that is not documented.

**What you expected to happen**:

The documentation includes `values`

https://github.com/grafana/grafana/blob/93bcc3b26c4ee14671f627eab07bd5616b83340c/docs/sources/alerting/manage-notifications/webhook-notifier.md

**How to reproduce it (as minimally and precisely as possible)**:

This is the data I received.

Note that `$.alerts[0].values` is defined.

```json
{
  "receiver": "example",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "example alert",
        "grafana_folder": "examples"
      },
      "annotations": {},
      "startsAt": "2023-03-20T00:00:00Z",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://localhost:3000/alerting/grafana/dtZJd3-4k/view?orgId=1",
      "fingerprint": "b2eb7cb93a20cd62",
      "silenceURL": "http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matcher=alertname%3DFFT+noise\u0026matcher=grafana_folder%3Dfft+noise",
      "dashboardURL": "http://localhost:3000/d/R-Kle9-Vk?orgId=1",
      "panelURL": "http://localhost:3000/d/R-Kle9-Vk?orgId=1\u0026viewPanel=10",
      "values": {
        "data-avg": 5.9313207278709505
      },
      "valueString": "[ var='data-avg0' metric='avg_over_time(...)' labels={} value=5.9313207278709505 ]"
    }
  ],
  "groupLabels": {
    "alertname": "example alert",
    "grafana_folder": "examples"
  },
  "commonLabels": {
    "alertname": "example alert",
    "grafana_folder": "examples"
  },
  "commonAnnotations": {},
  "externalURL": "http://localhost:3000/",
  "version": "1",
  "groupKey": "{}/{}:{alertname=\"example alert\", grafana_folder=\"examples\"}",
  "truncatedAlerts": 0,
  "orgId": 1,
  "title": "[FIRING:1] example alert examples ",
  "state": "alerting",
  "message": "**Firing**\n\nValue: data-avg=5.9313207278709505 ..."
}
```

While `valuesString` is defined, `values` is not:

https://github.com/grafana/grafana/blob/93bcc3b26c4ee14671f627eab07bd5616b83340c/docs/sources/alerting/manage-notifications/webhook-notifier.md?plain=1#L106-L118

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.4.3 (cf0a135595)
- Data source type & version: Prometheus
- OS Grafana is installed on: https://hub.docker.com/r/grafana/grafana-oss
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

```[tasklist]

```

**Comment by brendamuir** [comment]
@grobinson-grafana -- should we add the values property - and could you give me a description for it? thanks

**Comment by grobinson-grafana** [comment]
Yes we should add it! I think we can use the same definition from the Customize Notifications documentation on the Reference page.

**Comment by brendamuir** [comment]
hey @grobinson-grafana which one https://grafana.com/docs/grafana/next/alerting/manage-notifications/template-notifications/reference/ the Data or KV values description?

**Comment by brendamuir** [comment]
PR here: https://github.com/grafana/grafana/pull/67956

**Comment by brendamuir** [comment]
Closing this - as this is being tracked and updated in the pr above.
