### ISSUE TITLE
Alerting: alert provisioning notification returns 500

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#65072]
**What happened**:
got 500 when attempting to delete  contact point (thru /api/v1/provisioning/contact-points)

**What you expected to happen**:
deletion successful

**How to reproduce it (as minimally and precisely as possible)**:
use HTTP API to do the following:
1. create a contact point, 
2. add contact-point to notification policy
3. try deleting the contact point

**Anything else we need to know?**:
there is a tight coupling between `/api/v1/provisioning/contact-points` and `/api/v1/provisioning/policies` API-s. 

This tight coupling makes usage of those APIs very cumbersome.

**Context**:
We have multiple teams and manage ownership and notification preferences in a 3rd party system so in order to notify the relevant team of SLO violations we're using the above API to generate contact points and notification policies to route alerts to those teams via their chosen notification method. Now initial creation of contact points and their incorporation into notification policies is pretty straightforward, create contact points and then update the policies. The problem happens when we try changing the notification point type (I.E from slack to opsgenie), we can't delete the old contact point and just create a new one because the old one is currently used so we need to do 3 API calls, create a new contact point, update notification policy, remove old contact point. Trying to delete the old contact point before removing it from the policies results in an error.

I'm not sure what would be a better solution but the current one is not user-friendly. 

**Environment**:
- Grafana version: 9.4.3

**Comment by vbichov** [comment]
sorry - updated

**Comment by armandgrillet** [comment]
Indeed the deletion is failing because the contact point is being used, this is expected. You could edit the contact point and change its type, the only thing you could not replace is the contact point's name: https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-put-contactpoint

One bug when facing this issue is that the endpoint should not return a 500 but a 400 in this situation.
