### ISSUE TITLE
graphite annotations hardcoded maxDataPoints 100

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6509]
I see that grafana currently uses maxDataPoints=100 when requesting data from graphite for annotations.

this triggers consolidation in metrictank (and also in graphite), which makes the resolution of the data inaccurate, even when the amount of annotation makers would have been way less than 100 anyway.

Not sure what is the best solution, perhaps making maxDataPoints configurable in the options for graphite annotations

**Comment by torkelo** [comment]
can't you control the consolidation by using consolidateBy ? more than 100 annotations per graph will make it very slow, the annotations are currently quite costly to draw

**Comment by Dieterbe** [comment]
> can't you control the consolidation by using consolidateBy 

that affects only the choice of consolidation function, which isn't relevant to this problem.

I think the main problem here is that maxDataPoints is used for two things:
this parameter was originally intended to restrict the resolution of metrics data, under the assumption that null points were rare and should be counted as points as far as maxDataPoints is concerned.
However, using it for annotations is reasonable because it also gives you that certainty that there won't be any more than what MDP says, however like i said, it does easily trigger consolidation because graphite/metrictank can't know in advance that most of the points will be null.
e.g. if the store only has 1 point and the rest is nulls, then MDP 100 will still trigger consolidation, which will make the results less accurate, even though we wouldn't have violated MDP 100 if we hadn't specified the restriction.

**Comment by torkelo** [comment]
that sounds like a problem in graphite-api though

**Comment by aocenas** [comment]
@Dieterbe is this still relevant? If so is this something to be changed on grafana side considering @torkelo s last comment?

**Comment by Dieterbe** [comment]
seems like a very niche problem. let's close
