### ISSUE TITLE
Alert Email: Use Metric Alias instead of Metric name

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6510]
* **I'm submitting a ...**
- [ ] Bug report
- [x ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?v4.0.0-pre1
- What datasource are you using?InfluxDB
- What OS are you running grafana on?Ubuntu 16
- What did you do?
- What was the expected result?
- What happened instead?

Would like the alert email to use the Metric "Alias By" in Metrics Tab, instead of metric name form InfluxDB.

**Comment by bergquist** [comment]
Almost complete. Still missing support for "$1 - $9 = replaced with part of measurement name (if you separate your measurement name with dots)" pattern

**Comment by bergquist** [comment]
Closed by #6515
