### ISSUE TITLE
Grafana 9.4.3 Math Expression breaks Report

### ISSUE THREAD

**Issue by Ycallaer** [grafana/grafana#65116]
Hi team,
We encountered an issue going to grafana 9.4.3 with an existing report. Please find the necessary info below.

**What happened**:
We are migrating an existing grafana report (v9.1.8) to Grafana (9.4.3) on AKS.
The report has a math expression and we found 2 issues with this math expression.
The first issue is the definition of the datasource for an expression, in our old report this is defined as

```
"datasource": {
        "type": "__expr__",
        "uid": "__expr__"
}
```
However, if the datasource is in this format then the query fails with the following error
![image](https://user-images.githubusercontent.com/6471886/226633237-d5236a68-6e9f-4c0f-94f8-6885f3da152a.png)

A workaround is that you change the datasource to this format:
`"datasource":  "__expr__",`
 
Secondly is that the math expression is incorrectly calculated.
I created a simple dashboard based on 2 queries against some prometheus metrics. If I take the result of query B and multiply it by 1 I get completely different values, rather than the same line

![image](https://user-images.githubusercontent.com/6471886/226634777-edba04a5-5000-46e4-8eb2-c00c0c046a23.png)

**What you expected to happen**:
For the datasource, even if you create a new panel with a math expression I expect the datasource to default to the correct expression.
For the math expr $B *1, I would expect a line similar to B query

**How to reproduce it (as minimally and precisely as possible)**:
I will upload the "Get Help" output so that you can verify

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Elastic Search
- OS Grafana is installed on: Kubernetes Operator

**Comment by Ycallaer** [comment]
[help_dashboard.txt](https://github.com/grafana/grafana/files/11029318/help_dashboard.txt)

Attached file from the "Get Help" export

**Comment by Ycallaer** [comment]
Hi team,
Any update on this issue or do you require further info ?

**Comment by itsmylife** [comment]
@Ycallaer thanks for the detailed explanation. The first problem is addressed already by those PRs
- https://github.com/grafana/grafana/pull/65006
- https://github.com/grafana/grafana/pull/65950

I am gonna check the second issue and keep you posted.

**Comment by itsmylife** [comment]
@Ycallaer I cannot reproduce the second issue. If that is still happening could you please provide me `panel.json` and `.har` file so I can check the `request/response` and what we have in the panel?
