### ISSUE TITLE
Alert Notification:  Make the value formatting match graph settings

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6511]
Value in email shows 14 decimal places, can it match what the graph shows?  In my case no decimal places.

**Comment by torkelo** [comment]
tricky to use the same as in graph as that is dynamic based on the min/max of the series for the whole time range in the dashboard (which is usually not the same time range as in the alert query). 

But I think the same logic as is used by singlestat can be used.

**Comment by bergquist** [comment]
@torkel are you referring to this function? https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L138

**Comment by torkelo** [comment]
Yes

**Comment by CyBeRoni** [comment]
Matching the graph settings makes sense for this. For example if I have a graph that shows free disk space on servers, which is reported in bytes, then I'll set the graph to 'bytes' and the graph will neatly show "3.7GB". The alert however uses the raw number from the aggregation function, and in this case even shows non-sensical decimal places: "3780878882.1333".

It should be possible to just use the 'bytes' setting from the graph's Y-axis in that case, and apply the same formatting logic, no?

**Comment by ancker010** [comment]
I see this is removed from 4.4.0 milestone. Is this an indication that it won't be completed/fixed?

**Comment by sanchomuzax** [comment]
Similar problem as the https://github.com/grafana/grafana/issues/11372 issue.

**Comment by Ramalama2** [comment]
This is really annoing here too...

I have an emailqueue check, and i get an output of 10.000 (but that means 10)
if i look to the email, it shows 10.000 ....

That was just an example, but there is much more, where you get shocked sometimes in emails :-)

**Comment by bluefish6** [comment]
Upvoting. Examples that show that this issue is not limited to "decimal places in emails" but all types of alerting outputs can be found in #14592 .

**Comment by RamSet** [comment]
![9A1890F8-C861-4296-B8D6-10B67CF8F3E7](https://user-images.githubusercontent.com/20760161/57977143-32cc5380-79af-11e9-9607-060ced46181d.jpeg)
Adfin my 2 cents to this. 

Any way of patching this on my side ‘till it gets implemented?

**Comment by lazycoder-ru** [comment]
Any progress?

**Comment by nsowen** [comment]
Bump.

**Comment by thenecroscope** [comment]
+1

**Comment by Zeka13** [comment]
still waiting

**Comment by warhazer** [comment]
Any Update on issue?

**Comment by Quicksy** [comment]
+1

**Comment by M0rdecay** [comment]
+1

**Comment by AndresJz** [comment]
+1

**Comment by igncam** [comment]
+1

**Comment by eFeSist** [comment]
+1

**Comment by mugebudakwindlog** [comment]
+1

**Comment by mr-yaky** [comment]
+1

**Comment by RamSet** [comment]
Opened in 2016 ... 2020 and still no one that has to say anything about this ...

**Comment by Zeka13** [comment]
@RamSet you know, my friend, you can open PR =)

**Comment by RamSet** [comment]
@Zeka13 I would have done it a long time ago if i would have known where to look, what to change and what to update. Unfortunately, I do not ...

**Comment by hyperfraise** [comment]
+1

**Comment by CorentinB** [comment]
+1

**Comment by joepolcari** [comment]
no updates?

**Comment by nsowen** [comment]
Guten Tag und vielen Dank für Ihre Nachricht!

Ich bin ab dem 13. Juli 2020 wieder für Sie erreichbar. Bitte wenden Sie sich an Christian Scharmach (cs (at) 2scale.net).

Viele Grüße,

Nils Sowen

**Comment by Eraac** [comment]
This will be so much pleasure to have. I guess my problem is the same for everyone, we've alert in "second" or "percent (0.0-1.0)" format it's hard to read when the value is high

![image](https://user-images.githubusercontent.com/5497623/89528225-f9b61400-d7ea-11ea-8b39-679c15021ef2.png)
![image](https://user-images.githubusercontent.com/5497623/89528369-34b84780-d7eb-11ea-84cc-6d48b84fc65a.png)

**Comment by SFBorland** [comment]
Any updates on this?

**Comment by nsowen** [comment]
Guten Tag und vielen Dank für Ihre Nachricht!

Ich bin ab dem 28. September 2020 wieder für Sie erreichbar. Bitte wenden Sie sich an Christian Scharmach (cs (at) 2scale.net).

Viele Grüße,

Nils Sowen

**Comment by skrabadiloseidon** [comment]
And updates? An easier solution could be to allow define the unit in the alarm panel.

**Comment by AndresJz** [comment]
+1

**Comment by bdbusch** [comment]
+1

**Comment by lopezllu** [comment]
any update??

**Comment by acidos** [comment]
+1

**Comment by Zeka13** [comment]
bet what be released first, HL 3 or this bugfix

**Comment by AkaiNoCat** [comment]
+1

**Comment by chandresh364** [comment]
disk value showing not in Gb Grafana Alerts

**Comment by nitobosch** [comment]
+1

**Comment by Neerols** [comment]
+1

**Comment by tifling85** [comment]
bump..

**Comment by mehdibenfeguir** [comment]
percentage is coming like this
Please fix this issue 
![image](https://user-images.githubusercontent.com/7837335/130760085-92f6fd2d-ba9a-4c72-a88e-ab5e43fc0d54.png)

**Comment by mehdibenfeguir** [comment]
> percentage is coming like this
> Please fix this issue
> ![image](https://user-images.githubusercontent.com/7837335/130760085-92f6fd2d-ba9a-4c72-a88e-ab5e43fc0d54.png)

I found a workaround, in the metrics just put ceil(here your metrics function) and it will work

**Comment by danueb1991** [comment]
@mehdibenfeguir 

Thanks for your tip - but where can this be set? I am facing the same problem.

**Comment by mehdibenfeguir** [comment]
![image](https://user-images.githubusercontent.com/7837335/141676882-acb5ff14-083e-43d9-8fc4-f0119cfeb50b.png)

**Comment by danueb1991** [comment]
@mehdibenfeguir 

Thank you. However, I have a MySQL query.

**Comment by wookiist** [comment]
Any update? 5 years passed..

**Comment by Zeka13** [comment]
@wookiist put ceil(here your metrics function)

**Comment by wookiist** [comment]
> @wookiist put ceil(here your metrics function)

Sorry, but I didn't want any workaround.
I have the same purpose as why this issue was created.
I just want the alert unit to appear the same as the unit I set in grafana.

**Comment by Zeka13** [comment]
> > @wookiist put ceil(here your metrics function)
> 
> @Zeka13 Sorry, but I didn't want any workaround. I have the same purpose as why this issue was created. I just want the alert unit to appear the same as the unit I set in grafana.

This is open source, please notify us when you done

**Comment by ccoenen** [comment]
@Zeka13 you are not being helpful, you are just adding noise here. Also, great move deleting your downvoted reply ;-) surely nobody is gonna notice that now. Ooops.

**Comment by Zeka13** [comment]
@ccoenen cry me a river 🤡

**Comment by Himura2la** [comment]
signing up into the wait-list

**Comment by yyang-congruex** [comment]
Any update?

**Comment by sqkysqnt** [comment]
Just ran into this problem. Off to find a work around because it seems grafana doesn't care about this issue

**Comment by RamSet** [comment]
Still valid, shouldn't be stale should be looked into.

**Comment by rwader-swi** [comment]
I don't have problem with decimal places as you can use the humanize function in alert templating. But I can't figure how should I add units to my data as i want it to be dynamic in MBs/GBs/TBs 😐

**Comment by rwader-swi** [comment]
use humanize() for reducing decimals to 3 places and humanize1024() for data in KB/MB/GB etc. functions in notification's annotation

**Comment by armandgrillet** [comment]
As stated in the last comment and https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#print-the-humanized-value-of-a-query, using `humanize()` is how to do this in Grafana Alerting. Alert rules are not tied to specific panels anymore, they can but do not have to, thus the original request of matching graph settings does not match the way our product works anymore.
