### ISSUE TITLE
Error invite user

### ISSUE THREAD

**Issue by dyvol777** [grafana/grafana#65119]
**What happened**:
After inviting user that already exist, there is error when adding another users
`level=error msg="Failed to save invite to database" error="UNIQUE constraint failed: temp_user.id`

**How to reproduce it (as minimally and precisely as possible)**:
1. Invite user that already exist (by email)
2. Try invite another user 
3. Get error
4. Clear table `delete from temp_user;`
5. Try invite user - success
6. Try invite another user  - error 

Manual insertion to this table works well

**Environment**:
- Grafana version: 9.4.3
- OS Grafana is installed on: kubernetes
- Database : sqlite

**Comment by eledobleefe** [comment]
We found this similar [issue](https://github.com/grafana/grafana/issues/63995). It was fixed, although the most recent Grafana version - 9.4.3 - doesn't include this fix, when a later version is released later this month it should include it, as it is said [here](https://github.com/grafana/grafana/pull/64149#issuecomment-1471808501). 
Therefore, we are going to close this issue.
