### ISSUE TITLE
gauge with "config from query result" transformation shows different values based on 

### ISSUE THREAD

**Issue by nickper** [grafana/grafana#65131]
**What happened**: 
The gauge value shows an inconsistent value and only shows it (but not always) after I have entered the edit mode and back to dashboard. Somethimes it stays at the correct value, somethimes it reverts back to its previous lower value.
![gauge config from query result bug](https://user-images.githubusercontent.com/8981951/226669859-c4367ea5-0ad7-4637-90b8-305927ac1d94.gif)

**What you expected to happen**:
I expect it to show the maximum value of incomming and outgoing, but instead it shows a lower value. For example for incomming the value shown does correspond to neither the first or latest value in the dataset which are ~1.21 Tb and ~1.03 Tb.

**How to reproduce it (as minimally and precisely as possible)**:
I have 3 queries to (in my case) Zabbix's postgress db. I pull the incomming traffic, the outging traffic and the speed as documented and perform a small transformation.
![image](https://user-images.githubusercontent.com/8981951/226672423-be4193ea-22b1-4ef2-bd4b-64decfb06c6c.png)
In the transform tab I managed to set the threshold(50%) as maximum of the gauge's.
![image](https://user-images.githubusercontent.com/8981951/226672923-fba55938-d0db-432e-b7ae-535bc48dd79f.png)

Than I had this issue when saving the dashboard and reloading the page.

**Anything else we need to know?**:
The speed table does contain less entries to safe storage. Therefor the choice for Max but Last* gives the same behavior..

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: Zabbix 5.4.9
- OS Grafana is installed on: dockerized on ubuntu
- User OS & Browser: win11 - Edge and Firefox
- Grafana plugins: grafana-zabbix v4.2.10 (https://github.com/alexanderzobnin/grafana-zabbix)
- Others: -

**Comment by nickper** [comment]
[github panel export.txt](https://github.com/grafana/grafana/files/11037993/github.panel.export.txt)
of cource, here it is.

**Comment by oscarkilhed** [comment]
Was not able to reproduce this. We can reopen this if there are more instances of this issue or if it's reproducible on https://play.grafana.org/
