### ISSUE TITLE
Grafana Pulling Data From Incorrect Time Range

### ISSUE THREAD

**Issue by BitByteBitConsulting** [grafana/grafana#65139]
**What happened**:
I am running a query as follows using a date range defined in grafana as 2023-03-16 00:00:00 to 2023-03-16 23:59:59. The data I was returned was starting at 2023-03-15 19:03:20

![image](https://user-images.githubusercontent.com/57151446/226731211-64a53b29-7cc2-4d98-b455-bedc8c97500c.png)

`SELECT
  agent_name AS Computer,
  last_logged_in_user AS Username,
  status as Status,
  last_check_in_time AS "Last Check-in",
  commit_timestamp AS "Timestamp"
FROM
  CCR.agent_data
WHERE
  commit_timestamp BETWEEN $__timeFrom() AND $__timeTo()
  AND (
    last_logged_in_user LIKE CONCAT('%', '${username}', '%')
  )
ORDER BY
  commit_timestamp ASC`

**What you expected to happen**:

I get data between the specified time stamps. The first correct time stamp is 2023-03-16 00:03:20

**How to reproduce it (as minimally and precisely as possible)**:

Use the previously mentioned SQL query against a MySQL database table with the following structure

`CREATE TABLE agent_data (
    agent_name TEXT,
    last_logged_in_user TEXT,
    computer_name TEXT,
    last_check_in_time DATETIME,
    domain_workgroup TEXT,
    public_ip TEXT,
    status TEXT,
    commit_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);`

**Anything else we need to know?**:
If I add 5 hours to the query it will pull the correct time
Both Grafana and the Database are utilizing the America/Chicago TZ.
If I take the query from the query inspector and input it directly into MySQL it will return the correct data.
![image](https://user-images.githubusercontent.com/57151446/226734662-63758763-cdfc-4755-8b12-ff0c48f83964.png)
![image](https://user-images.githubusercontent.com/57151446/226735050-6baf87f8-d617-47e9-a844-123480b04b2d.png)

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64
- OS Grafana is installed on: Ubuntu 22.04
- User OS & Browser: Windows10/Chrome
- Grafana plugins: None
- Others:

**Comment by zuchka** [comment]
what does the timezone setting say in your user profile settings?

![CleanShot 2023-03-21 at 15 32 03@2x](https://user-images.githubusercontent.com/37156449/226778943-57c1d90b-6825-43c6-a0dd-9ff4de554c0b.png)

**Comment by BitByteBitConsulting** [comment]
Hello,

I have it as the following:

![image](https://user-images.githubusercontent.com/57151446/226784800-bab97176-0205-4fa0-a7e0-89167d81953b.png)

**Comment by BitByteBitConsulting** [comment]
So it appears that since the data in my database is already in UTC-05:00. Grafana is attempting to convert it again and subtracts another 5 hours. Which explains why the data is so far out of scope. If I set Grafana to assume the time is already in UTC it will work. Whilst this can be fixed by ingesting data as UTC into my database, there should be an option to explain what format the database is in. Am I missing a setting that can do that in Grafana?

**Comment by zuchka** [comment]
I believe we always suggest that DBs use UTC internally. This is a super common scenario. If keeping the DB in UTC is not an option I would check our community forum for related threads

https://community.grafana.com/t/time-zone-settings/42253/2?u=mattabrams

https://community.grafana.com/search?q=db%20timezone%20utc
