### ISSUE TITLE
/api/ds/query in Variables not work in 9.4.0+

### ISSUE THREAD

**Issue by Mr-Xzz** [grafana/grafana#65159]
In the variable configuration screen, the aliyun-log-service-datasource plugin is used, and the data can be accessed normally through /api/ds/query in 9.3.0, but in 9.4.0 and above, it reports an error
![image](https://user-images.githubusercontent.com/36269266/226847301-4d084781-5fef-42a8-8a79-7f575b2caf1e.png)
![image](https://user-images.githubusercontent.com/36269266/226847723-ce14948a-90c7-46f9-9be0-95c1ca60d01f.png)
![image](https://user-images.githubusercontent.com/36269266/226848402-ed519c27-2dd0-428f-ac8d-8eb9b4136e72.png)

Did you make any relevant changes?

**Environment**:
- Grafana version: 9.4.0+
- Data source type & version: aliyun-log-service-datasource plugin 2.27
- OS Grafana is installed on: docker
- User OS & Browser: Mac + Edge
- Grafana plugins: aliyun-log-service-datasource plugin 2.27
- Others:

**Comment by Mr-Xzz** [comment]
![image](https://user-images.githubusercontent.com/36269266/226857198-7c89f62c-bc65-4b89-943f-0c55c4546ec6.png)
![image](https://user-images.githubusercontent.com/36269266/226857780-90712af5-64e9-4ed7-90b2-c12e9e5e8412.png)

**Comment by zuchka** [comment]
this repo does not support bugs within community-built datasources. I would suggest filing an issue in the aliyun-log repo instead 👍
