### ISSUE TITLE
Plugin descriptions in the pop-out nav menu are cut-off in grafana <v9.5

### ISSUE THREAD

**Issue by joeyorlando** [grafana/grafana#65157]
It appears to cut-off the Grafana OnCall's `info.description` from its [`plugin.json`](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/plugin.json#L7):
```
Collect and analyze alerts, escalate based on schedules and deliver them to Slack, Phone Calls, SMS and others.
```

<img width="334" alt="Screenshot 2023-03-16 at 15 17 27" src="https://user-images.githubusercontent.com/9406895/226838700-f110607f-bf90-4716-ad08-61d7b61ba1f0.png">

I think the text should either be wrapped, or neatly cut-off w/ something like a `...`

**Comment by sympatheticmoose** [comment]
I don't believe this bug still presents itself in the new navigation, please re-open if still an issue 🙏
