### ISSUE TITLE
error UNIQUE constraint failed when inviting more than 1 user

### ISSUE THREAD

**Issue by bLd75** [grafana/grafana#65155]
**What happened**:

Admin is unable to send more than 1 invite, error message issue in logs
`level=error msg="Failed to save invite to database" error="UNIQUE constraint failed: temp_user.id" remote_addr= traceID= `

Forum post relating the same problem: https://community.grafana.com/t/failed-to-save-invite-to-database-error-unique-constraint-failed-temp-user-id/83574/4

**What you expected to happen**:

Being able to save more than one invite

**How to reproduce it (as minimally and precisely as possible)**:

- Create a 1st user invitation -> OK
- Create a 2nd user invitation -> KO

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: none
- OS Grafana is installed on: Debian GNU/Linux 11 (bullseye)
- User OS & Browser: Pop!_OS 22.04 LTS / Firefox 111.0

**Comment by CyberHippo** [comment]
I think your issue duplicates https://github.com/grafana/grafana/issues/63995 which has been fixed by https://github.com/grafana/grafana/pull/64160.

**Comment by bLd75** [comment]
Yes it is thanks!
I couldn't find this issue actually, and seems like v9.4.7 wasn't set to latest release until yesterday.
