### ISSUE TITLE
Grafana Alerting does not use configured "Authorization Header - Scheme"

### ISSUE THREAD

**Issue by laugmanuel** [grafana/grafana#65154]
I wanted to test Grafana Alerting and created an alert which should use a WebHook as contact point.

For the target API, I need to set a custom Authorization Header in the form: `Authorization: <AppSpecificScheme> <API-Key>`

I've tried the "Authorization Header - Scheme" field but it seems like the field does not have any impact and `Bearer` is used regardless what I configure.

I've changed the API-URL to a listening netcat instance and saw the following request:

```sh
HTTP/1.1
Host: localhost:8080
User-Agent: Grafana
Content-Length: 1317
Authorization: Bearer <API-Key>
Content-Type: application/json
Accept-Encoding: gzip

[payload...]
```

The contact point is configured like this:
![image](https://user-images.githubusercontent.com/5444009/226834282-e7ba3eca-2b59-4ab3-9272-53531144a598.png)

**What happened**:

"Authorization Header - Scheme" field is not used in Webhook request.

**What you expected to happen**:

Custom scheme schould be used instead of `Bearer`

**How to reproduce it (as minimally and precisely as possible)**:

- Create a new contact point and configure:
  - URL to `http://localhost:8080`
  - Authorization Header - Scheme to `CustomAuthScheme`
  - Authorization Header - Credentials to `API-KEY`
- Start a test server using netcat: `nc -kl 8080`
- Click the `Test` button in Grafana
- Observe the request in the shell

**Anything else we need to know?**:

**Environment**:
- Grafana version: [v9.4.3 (cf0a135595)]
- Data source type & version: n/a
- OS Grafana is installed on: RHEL8
- User OS & Browser: MacOS & Edge 
- Grafana plugins: n/a
- Others: n/a

**Comment by grobinson-grafana** [comment]
Hi! Thank you for opening this issue! I think this is a bug. We will take a look and create a fix if required.

**Comment by grobinson-grafana** [comment]
Hi! I've just tested this and replicate this bug in 9.4.3. However, I can also confirm is fixed in 9.4.7 and later so I will close this issue! Thanks for taking the time to report this bug! 🙂

**Comment by laugmanuel** [comment]
Hi @grobinson-grafana , thank's for reporting back.

I can confirm that v9.5.1 does work fine. Do you have the corresponding fix PR so it is referenced in this issue?

**Comment by grobinson-grafana** [comment]
Hi! Here is the original fix https://github.com/grafana/alerting/pull/59
