### ISSUE TITLE
Ability to define graphs statically, in a configuration file read at startup

### ISSUE THREAD

**Issue by michalrus** [grafana/grafana#6517]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

- What Grafana version are you using? → 3.1.0
- What datasource are you using? → InfluxDB+collectd
- What OS are you running grafana on? → NixOS

We should be able to define graphs statically, in a configuration file read at startup. This functionality would be in line with immutable approach, e.g. in NixOS.

Even better, these “static” charts should not be modifiable at runtime.

Thank you!

**Comment by torkelo** [comment]
you can make dashboard that are not editable (by setting editable false). You can also easily setup a file watcher that syncs file based json dashboard into the grafana database using the HTTP api. 

There are similar issues for this so will close this.

**Comment by michalrus** [comment]
Thanks!
