### ISSUE TITLE
Colors of stacked lines are misleading when values are 0

### ISSUE THREAD

**Issue by Mycleung** [grafana/grafana#6519]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? 3.1.1 (commit: v3.1.0+21-g3921cc7-dirty)
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 7
- What did you do?
Created a graph with multiple stacked values, some of which are zero.
![grafana-alarms](https://cloud.githubusercontent.com/assets/3316508/20140556/bd65ae8a-a683-11e6-905c-51931e668459.PNG)

- What was the expected result?
The blue line for Major should be clear at the top of the graph, since there are 4 Major alarms but 0 Critical alarms.

- What happened instead?
The Critical alarm line hides the Major line, because it's stacked on top of Major. I've changed the color of Major to blue to highlight this effect more (normally it's orange, which means the tiny specs of blue peeking out also can't be made out). Surely the order in which these are arranged in the Z axis should be reversed?

**Comment by torkelo** [comment]
you could sort the series so the series with zeroes are first in the stack. Series sorting is up the metric query and TSDB backend

**Comment by torkelo** [comment]
you can also manually set Z-order in display overrides section of graph panel

**Comment by Mycleung** [comment]
Reversing the Z-order results in the same issue for a different statistic. The underlying problem is that a line with value of 0 will always overlap (and hide) the line directly underneath it in the graph. See how the Info line now obscures the Minor line in the screenshot below.

![grafana-alarms2](https://cloud.githubusercontent.com/assets/3316508/20141309/a73cbfe6-a687-11e6-8bab-c3b8259eeb94.PNG)

Sorting by magnitude of statistic isn't an option either, since one of the requirements of the graph is that the metrics stay in the same order (e.g. ascending/descending order of severity).

**Comment by torkelo** [comment]
I don't see a way to solve it other than disable stacking

**Comment by jgitlin-bt** [comment]
I have run into this issue as well, and I find there's no easy solution. The best fix I have found is to set a line width of 0 and increase fill. This produces a reasonable alternative. Example, before, see how we have a green line for a zero metric:

<img width="591" alt="screen shot 2018-11-06 at 8 30 44 pm" src="https://user-images.githubusercontent.com/30709042/48104819-00bd8600-e203-11e8-8d9b-1d938c389771.png">

Increasing fill and removing the lines makes the data more clear (at least to me)

<img width="562" alt="screen shot 2018-11-06 at 8 33 15 pm" src="https://user-images.githubusercontent.com/30709042/48104886-4da15c80-e203-11e8-966b-666300b26c19.png">

It might be nice if Grafana had an option to stop drawing stacked lines (and points) for zero values, but I find that using a more dense fill value and setting a 0 width line is a viable alternative
