### ISSUE TITLE
grafana_session' is missing. This can be set in the WhiteListed Cookies text-box on

### ISSUE THREAD

**Issue by cooperspencer** [grafana/grafana#65195]
**What happened**:
The Oracle Enterprise Manager App doesn't work with Grafana 9.3.2 (also tried version 9.4.3).
We always get "Required cookie 'grafana_session' is missing. This can be set in the WhiteListed Cookies text-box on" even though we set that.

**What you expected to happen**:
For it to work.

**Anything else we need to know?**:
if you remove those three lines in `pkg/util/proxyutil/proxyutil.go` it works:
```go
for _, v := range skipCookiesNames {
 delete(keepCookies, v)
}
```
https://forums.oracle.com/ords/apexds/post/required-cookie-grafana-session-is-missing-this-can-be-set-2810

**Comment by cooperspencer** [comment]
this was introduced with #57399. Before that, this plugin seemed to work fine.

**Comment by DWebb0** [comment]
I'm registering my interest here @DWebb0

**Comment by 6fears7** [comment]
Experiencing this issue as well, Grafana v10.1.0

**Comment by 6fears7** [comment]
Fixed my issue by upgrading the plugin to the latest version (in this case, it was version 4 which supported Grafana versions 9.2+)

**Comment by sympatheticmoose** [comment]
Believe this is more of an issue with the Oracle Enterprise Manager application which is an unsigned plugin.

**Comment by cooperspencer** [comment]
My issue was fixed with Grafana 11 and running the latest version of the OEM plugin.

**Comment by tacobellenthusiast** [comment]
Unfortunately Im running Grafana 10.1.0 and the latest version of the OEM plugin is not working with it. It works with my 9.2.4 version though.

**Comment by sympatheticmoose** [comment]
@tacobellenthusiast - for help with this plugin you'll need to get in touch with Oracle I'm afraid
