### ISSUE TITLE
Exported dashboards leak template variable values

### ISSUE THREAD

**Issue by MatMeredith** [grafana/grafana#6520]
Running  Grafana v3.1.1 (commit: v3.1.0+21-g3921cc7-dirty)  

I have a dashboard with repeated panels which I am trying to export using the Web UI Share Dashboard: Export option.

The exported JSON contains the values of the template variable from the first panel in each case.   E.g. I have a panel that repeats over each node in my deployment (using a template variable "node" which contains the IP addresses of all my nodes).   In the exported JSON I have a single panel definition...
```
      "panels": [
        {
<snip>
          "repeat": "node",
          "scopedVars": {
            "node": {
              "text": "10.225.20.168:161",
              "value": "10.225.20.168:161",
              "selected": false
            }
          },
<snip>
```
The exported JSON includes the value of node from the first instance of the panel at the time the dashboard was exported, thereby leaking my IP addresses into the exported dashboard.   I can manually remove these scopedVars from the exported JSON, in which case the dashboard still imports fine, but next time I export it they are back again...   I use repeated panels extensively and so I'm loathed to have to manually remove these scopedVars from all of them every time I export...

**Comment by torkelo** [comment]
testing this in master and looks like this has been fixed

**Comment by dpavlos** [comment]
Hi @torkelo ,  I see the same behaviour in v6.4.2 no matter whether the `Export for sharing externally` option is enabled or not.

**Comment by torkelo** [comment]
make sure you set "Refresh on dashboard load" in the template variable options

**Comment by dpavlos** [comment]
@torkelo I think I found the culprit. If the dashboard consists of panels in multiple rows you have to collapse all the rows first and then try to export it. Otherwise, the variables as well as the repeated panels aren't cleaned up properly.
