### ISSUE TITLE
Alert:  Incorrect value in fired alert compared to graph

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#6521]
* **I'm submitting a ...**
- [ x] Bug report

Grafana version: 4.0beta
OS: Centos7

Trying to use a non_negative_derivative to keep track of memorygrowth of processes but the value of the fired alert is including the 1st decimal into its value? so below,, instead of just having a derivative of 7mb im getting an alert of that its 70mb , above threshold set to 20mb

![image](https://cloud.githubusercontent.com/assets/12600004/20141180/7f7102b2-a68f-11e6-9453-ac577f07a994.png)

**Comment by bergquist** [comment]
Weird. I will try to reproduce this

**Comment by bergquist** [comment]
Could you please show me your query tab?

**Comment by discoduck2x** [comment]
@bergquist 

![image](https://cloud.githubusercontent.com/assets/12600004/20143023/7c8d462a-a697-11e6-88f4-18cebef0538b.png)

**Comment by bergquist** [comment]
if you click logs -> data -> 0 -> points in the debug log. Can you see the number?

I dont understand how the number can be interpreted as 10x higher...

**Comment by discoduck2x** [comment]
@bergquist yes...its there,, could it be something with fill(null) ? since all other points that has no "derivative change" shows 0,,, so looks like the correct value gets inserted ontop/prefix to the 0:s maybe,,, laymans theory iknow ;)

**Comment by discoduck2x** [comment]
@bergquist this is only happening for me with non_negative_derivative function - if checking just current mem values the alerting gets the correct values - same as graph

**Comment by bergquist** [comment]
I was able to reproduce this locally once... Then it disappeared next time I was trying to query the same interval. Frustrating!!!

I don't understand how rerunning the same query again does not result in the same values.. When using max in the influxdb query and alerting aggregation values should not change over time.

**Comment by discoduck2x** [comment]
@bergquist and thats not coz the alret interval has its own interval? i kept missing reproducing since my graph was set / save to bigger interval and alert had 1min, now

**Comment by torkelo** [comment]
I think this is related to non_negative_derivate, lots of people are still reporting issues and strange behavior with this function (in the mailing list). maybe fill(null) is good with this function, not sure. I know people are reporting strange flip flopping and peaks in data with this function

**Comment by discoduck2x** [comment]
@torkelo im not sensing any other strangness round non_negative_derivate than that the alert query result points gets x10. I have my testbench still running Grafana v4.0.0-pre1 (commit: 1ce0b8f)  , with an alert attached to a non_negative and that one is NOT doing the same thing (also influx 1.0.2 datasource).
@bergquist

**Comment by torkelo** [comment]
@discoduck2x when you test the rule you can expand and show the raw data being returned from InfluxDB, can you show that?

**Comment by discoduck2x** [comment]
@torkelo @bergquist  , like this? or u mean in dev tools chrome?

![image](https://cloud.githubusercontent.com/assets/12600004/20176841/f678ed38-a749-11e6-94a2-6b9a5d8f4819.png)

but in graph:

![image](https://cloud.githubusercontent.com/assets/12600004/20176867/23fea810-a74a-11e6-91bf-c2754f0bf9c2.png)

**Comment by torkelo** [comment]
that is fine, so you get a peak value of 11 million, threshold is at 15 million and when you test the alert it says its firing? do you always get this? (please show result of Rule Test run  result as well as expand data points)

**Comment by bergquist** [comment]
The tooltip says 11440128. alert result says 11440128**0**

**Comment by discoduck2x** [comment]
@torkelo , yes , 

![image](https://cloud.githubusercontent.com/assets/12600004/20177161/a12b7dda-a74b-11e6-96e2-5db5b5577b74.png)


thinking of upgrading my test to 4beta aswell ot see if that breaks

**Comment by torkelo** [comment]
can you show the panel json? (it contains the alert model)

**Comment by discoduck2x** [comment]
i did save as another dashboard,,, then it doesnt happen....didnt change anything else,, wtf,, must test some more

**Comment by torkelo** [comment]
might have been the alert model that was old (we have changed it a bit during alpha stage)

**Comment by bergquist** [comment]
I just found a bug regarding rawquery usage. That might have caused the problem if you switched back of forth between rawquery and normal query. https://github.com/grafana/grafana/commit/a948dfe5149a9845edde752d36f0e9b9d38a3be9

**Comment by discoduck2x** [comment]
hmm think i started with it as normal and then changed to raw,, not going back though,

cool , ill recreate the dashboards and report back in a few ! thanks for your help so far (should always try remember save as etc....)

**Comment by discoduck2x** [comment]
once recreated / re-saved as new the problem dissappeared.... :)

**Comment by Pooja2589** [comment]
@torkelo 
I am getting this weird issue where in the graph, the current value is showing as 11 but when I am trying to put alert on it, its JSON response log is showing value as 1 and so the Alert is not getting fired. Request your help, attaching screenshot for reference.
![alertissue](https://user-images.githubusercontent.com/42452384/47753075-9ed5ad00-dc53-11e8-801e-9388173c1589.png)

![image](https://user-images.githubusercontent.com/42452384/47753089-a7c67e80-dc53-11e8-92b5-521b69a102dd.png)

**Comment by bergquist** [comment]
You're using a very short time range. `now-10s -> now`. Is that as expected? 
Could you share your metric query? Perhaps the visualised query aggregates to larger "time buckets"
