### ISSUE TITLE
Geomap: Advanced Route Tooltip

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#65226]
1.  Interpolation for interaction between points
2.  Option to show / hide routes connected to a point
3.  Reconcile crosshair handling as the array of layers causes issues with state management

**Comment by alex-tate** [comment]
Will this issue address a problem seen when scrolling along a timeseries graph with shared crosshairs enabled? With a geomap panel showing a route with many points, it appears that the shared cursor moves smoothly along the route as you move the primary cursor along the timeseries. However, if you zoom in (time-wise) you can see that the shared cursor actually 'bounces' around along the route as you move along the timeseries. I noted this a while back but was reminded about it when viewing the excellent demo recently put up by @MatinF - see https://grafana.csselectronics.stellarhosted.com/d/yBc5x90nk2/css-playground-kia-ev6?orgId=1

**Comment by MatinF** [comment]
I'm not sure if this is directly related, but we're also experiencing some issues with the route layer when using Amazon Athena as the data source - I've described this here: https://github.com/grafana/grafana/issues/60407#issuecomment-1761436694
