### ISSUE TITLE
Prometheus: Raw or Table choice not persisted in explore URL

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#65228]
**What happened**:
Looks like in https://github.com/grafana/grafana/pull/60479/files, I didn't add the selected table or raw view state into the explore url.

**What you expected to happen**:
The view the user selected in explore would persist in the explore URL.

**How to reproduce it (as minimally and precisely as possible)**:
Make any prometheus instant query, select table view, copy URL, open in a new tab.

**Anything else we need to know?**:

**Comment by gtk-grafana** [comment]
Oh, I was gonna try to find time to fix this since it was my ****up. 

After chatting with @gelicia a bit, we've noticed that everything in the query editor seems to persist in the URL, but everything in the panel persists in local storage. Right now this new toggle isn't persisting in either and always displays the default option (the new UI added in https://github.com/grafana/grafana/pull/60479).

So I guess it's not as simple as adding the state of that toggle to the URL, a decision needs to be made!

**Comment by gtk-grafana** [comment]
Should we save the users preference for table vs raw in local storage, and keep it consistent for each user? Or do we want it to be tied to the query and sharable via the URL?

**Comment by Sin4wd** [comment]
Is there any way to change the default way to table view? raw view is often less useful.
