### ISSUE TITLE
Alert for InfluxDB not alerting anymore

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6523]
* **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?grafana_4.0.0-1478700301beta1_amd64.deb
- What datasource are you using?InfluxDB
- What OS are you running grafana on?Ubuntu 16

No longer alerting, last build to to alert was grafana_4.0.0-1478548471pre1_amd64.deb.

![grafana](https://cloud.githubusercontent.com/assets/20861450/20141453/6870c934-a65e-11e6-9beb-b00a9f029fba.PNG)

**Comment by bergquist** [comment]
@chipper110 Whats the interval for the panel? (set in the bottom of the metric page) 

Could you please include all the log data from the test result?

**Comment by chipper110** [comment]
Time interval is 10s.  Here are the logs.

![image](https://cloud.githubusercontent.com/assets/20861450/20143367/c06d6a54-a666-11e6-8be5-db50d81ddf65.png)

**Comment by bergquist** [comment]
Could you try to increase the alert range a bit? lets say 5min - now?
Data being empty makes me believe that the data is lagging. 

Could you also show med your metric tab so I can see the query?

**Comment by chipper110** [comment]
Sure, here is the alert with time increase.

![image](https://cloud.githubusercontent.com/assets/20861450/20143687/0291d400-a668-11e6-9de2-593d44bae08b.png)

**Comment by chipper110** [comment]
Here is the Metric page
![image](https://cloud.githubusercontent.com/assets/20861450/20143744/206764b8-a668-11e6-8be9-a04db29a927f.png)

**Comment by chipper110** [comment]
The same thing is happening to other panels with times out to 1h.  Also when i revert back to older version the same panel alerts properly.  I can go back to older version and send logs if needed.

**Comment by chipper110** [comment]
Here is the same panel with version grafana_4.0.0-1478266398pre1_amd64.deb
grafana_4.0.0-1478266398pre1_amd64.deb

**Comment by chipper110** [comment]
![image](https://cloud.githubusercontent.com/assets/20861450/20144312/34f71566-a66a-11e6-8ebf-e7bb5c0a2da2.png)

**Comment by bergquist** [comment]
@chipper110 No worries I should be able to find the problem :)

**Comment by chipper110** [comment]
Great,  Thanks

**Comment by bergquist** [comment]
in https://github.com/grafana/grafana/commit/56340bfdfbb84a7899ee9b2e0c6ec4ebd2bf668b#diff-68ac528a9cb411a36074808dc10bec13 We changed how tags are created in the query to influxdb. Which is the only difference in the two versions your testing. 

Since your are using a number in the where clause this will now be rendered as a number and not a string in the later version. In other words. `host = '10001'` will be rendered as `host = 10001`. But since the graph is working the alert query is doing something wrong... It would be great if you could help us get some logging. Could you please enable extra logging as describe in http://docs.grafana.org/alerting/rules/#troubleshooting and paste the content from the /data/log/grafana.log file. 

And get the raw graph query that influxdb creates. You can get that by clicking `Toggle edit mode` in the query editor 
![image](https://cloud.githubusercontent.com/assets/618863/20172125/fd4fc8ea-a733-11e6-9d19-60672d8d802f.png)

**Comment by chipper110** [comment]
Here is the raw graph query, working on getting the logs.

![image](https://cloud.githubusercontent.com/assets/20861450/20182137/cb275856-a72e-11e6-8140-1ecc0cf52703.png)

**Comment by bergquist** [comment]
@chipper110 would be great if you could try the latest build. We hade 3 patches on alerting support for influxdb today http://grafana.org/builds/

**Comment by chipper110** [comment]
Sorry but same result with newest build.  But you were right about the Hostname.  I tested with hostname of SN10003a and it would alert as expected.  I can work on getting those logs for you.

**Comment by chipper110** [comment]
Here are the logs.

t=2016-11-10T14:47:06-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:47:16-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:47:26-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:47:36-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:47:46-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:47:56-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:48:00-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Milk Temp alert" id=1
t=2016-11-10T14:48:00-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT moving_average(\"value\", 10)  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND \"raw voltage\" = 'true' AND time > now() - 15m"
t=2016-11-10T14:48:00-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+moving_average%28%22value%22%2C+10%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+$
t=2016-11-10T14:48:00-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.954 alertId=1 name="Milk Temp alert" firing=false
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="DL Temp 1m/20m Avg" id=2
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="DL Temp 1m/20m Avg alert" id=15
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\")  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND time > now() - 1m GROUP BY time(10s) fill(null)"
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\")  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND time > now() - 5m GROUP BY time(10s) fill(null)"
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+mean%28%22value%22%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+10001+AND+time+%$
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+mean%28%22value%22%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+10001+AND+time+%$
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.973 alertId=2 name="DL Temp 1m/20m Avg" firing=false
t=2016-11-10T14:48:06-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=6.041 alertId=15 name="DL Temp 1m/20m Avg alert" firing=false
t=2016-11-10T14:48:11-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Bulk Tank Temp 1m/20m Avg" id=12
t=2016-11-10T14:48:11-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\") * .2175 - 152.5 FROM \"Pin_5\" WHERE \"host\" = 10002 AND time > now() - 1m GROUP BY time(1m) fill(null)"
t=2016-11-10T14:48:11-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10002&epoch=s&q=SELECT+mean%28%22value%22%29+%2A+.2175+-+152.5+FROM+%22Pin_5%22+WHERE+%22host%22+%3D+10002+AND+time+%3E+$
t=2016-11-10T14:48:11-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.785 alertId=12 name="Bulk Tank Temp 1m/20m Avg" firing=false
t=2016-11-10T14:48:16-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-10T14:48:17-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Bulk Tank Temp 1m/20m Avg alert" id=13
t=2016-11-10T14:48:17-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\") * .2175 - 152.5 FROM \"Pin_5\" WHERE \"host\" = 10002 AND time > now() - 1h GROUP BY time(1m) fill(null)"
t=2016-11-10T14:48:17-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10002&epoch=s&q=SELECT+mean%28%22value%22%29+%2A+.2175+-+152.5+FROM+%22Pin_5%22+WHERE+%22host%22+%3D+10002+AND+time+%3E+$
t=2016-11-10T14:48:17-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=6.756 alertId=13 name="Bulk Tank Temp 1m/20m Avg alert" firing=false
t=2016-11-10T14:48:18-0500 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2016-11-10T14:48:18-0500 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=2
t=2016-11-10T14:48:18-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\")  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND time > now() - 5m GROUP BY time(10s) fill(null)"
t=2016-11-10T14:48:18-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+mean%28%22value%22%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+10001+AND+time+%$
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Bulk Tank Temp 1m/20m Avg alert" id=16
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="DL Temp 1m/20m Avg alert" id=14
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\")  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND time > now() - 15m GROUP BY time(10s) fill(null)"
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+mean%28%22value%22%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+10001+AND+time+%$
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\") * .2175 - 152.5 FROM \"Pin_5\" WHERE \"host\" = 10002 AND time > now() - 1h GROUP BY time(1m) fill(null)"
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10002&epoch=s&q=SELECT+mean%28%22value%22%29+%2A+.2175+-+152.5+FROM+%22Pin_5%22+WHERE+%22host%22+%3D+10002+AND+time+%3E+$
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.073 alertId=16 name="Bulk Tank Temp 1m/20m Avg alert" firing=false
t=2016-11-10T14:48:24-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.936 alertId=14 name="DL Temp 1m/20m Avg alert" firing=false

**Comment by bergquist** [comment]
Seems like I forgot to handle some error that influxdb returns. Would be very appreciated if you could try the latest build and see if the logs are more informative. 

The new build should be available at grafana.org/builds within 20min

**Comment by chipper110** [comment]
Still same result.

t=2016-11-11T09:14:10-0500 lvl=info msg="Starting Grafana" logger=main version=4.0.0-beta1 commit=a87fd11 compiled=2016-11-11T08:04:38-0500
t=2016-11-11T09:14:10-0500 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2016-11-11T09:14:10-0500 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2016-11-11T09:14:10-0500 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2016-11-11T09:14:10-0500 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2016-11-11T09:14:10-0500 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2016-11-11T09:14:10-0500 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2016-11-11T09:14:10-0500 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2016-11-11T09:14:10-0500 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2016-11-11T09:14:10-0500 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2016-11-11T09:14:10-0500 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2016-11-11T09:14:10-0500 lvl=info msg="Starting DB migration" logger=migrator
t=2016-11-11T09:14:10-0500 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2016-11-11T09:14:10-0500 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2016-11-11T09:14:10-0500 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2016-11-11T09:14:10-0500 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2016-11-11T09:14:10-0500 lvl=info msg="Starting plugin search" logger=plugins
t=2016-11-11T09:14:10-0500 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2016-11-11T09:14:10-0500 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2016-11-11T09:14:10-0500 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
t=2016-11-11T09:14:11-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:14:21-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:14:31-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:14:41-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:14:51-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:14:55-0500 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2016-11-11T09:14:55-0500 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=6
t=2016-11-11T09:14:55-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\")  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND time > now() - 5m GROUP BY time(10s) fill(null)"
t=2016-11-11T09:14:55-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+mean%28%22value%22%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+10001+AND+time+%$
t=2016-11-11T09:15:00-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Milk Temp alert" id=1
t=2016-11-11T09:15:00-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT moving_average(\"value\", 10)  * .149116 - 147.5 FROM \"Pin_6\" WHERE \"host\" = 10001 AND \"raw voltage\" = 'true' AND time > now() - 15m"
t=2016-11-11T09:15:00-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10001&epoch=s&q=SELECT+moving_average%28%22value%22%2C+10%29++%2A+.149116+-+147.5+FROM+%22Pin_6%22+WHERE+%22host%22+%3D+$
t=2016-11-11T09:15:00-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.009 alertId=1 name="Milk Temp alert" firing=false
t=2016-11-11T09:15:01-0500 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=9
t=2016-11-11T09:15:02-0500 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Bulk Tank Temp 1m/20m Avg alert" id=13
t=2016-11-11T09:15:02-0500 lvl=dbug msg="Influxdb query" logger=tsdb.influxdb raw query="SELECT mean(\"value\") * .2175 - 152.5 FROM \"Pin_5\" WHERE \"host\" = 10002 AND time > now() - 1h GROUP BY time(1m) fill(null)"
t=2016-11-11T09:15:02-0500 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://10.1.1.25:8086/query?db=10002&epoch=s&q=SELECT+mean%28%22value%22%29+%2A+.2175+-+152.5+FROM+%22Pin_5%22+WHERE+%22host%22+%3D+10002+AND+time+%3E+$
t=2016-11-11T09:15:02-0500 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.885 alertId=13 name="Bulk Tank Temp 1m/20m Avg alert" firing=false

**Comment by wei-hai** [comment]
+1, I encountered the same issue

**Comment by torkelo** [comment]
Is this still an issue? If so try latest v4 build.

If still a problem, show expanded output (with data points) when you hit Test Rule

is it not firing when it should? 

Keep ion mind that the alert query condition time range can effect the data returned, so a low time range like now-1m might not return the same values as you see on the graph (depending on data, aggregation functions etc)

**Comment by bergquist** [comment]
This seems to be caused by https://github.com/grafana/grafana/issues/6626 
Fix will soon be in master!
