### ISSUE TITLE
Singlestat text value thresholds

### ISSUE THREAD

**Issue by perbly** [grafana/grafana#6524]
* **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using?
3.1.1

Hi, i would like to have the ability to have thresholds for text values.
For example if the text is "up" it should be green and "down" should be red.

![image](https://cloud.githubusercontent.com/assets/5936850/20143641/0c471672-a69a-11e6-9f79-2a42d570f9e3.png)

**Comment by bergquist** [comment]
I wonder if it makes more sense to have this under the value mapping options 
![image](https://cloud.githubusercontent.com/assets/618863/20175084/5f2ed0f8-a741-11e6-9146-b559276c6304.png)

**Comment by perbly** [comment]
Yes i would. 
A "text to value" option would be fine also. 
up > 1
down > 0

**Comment by sunnos9** [comment]
5638 does this ?

**Comment by perbly** [comment]
Awesome, thanks @sunnos9
