### ISSUE TITLE
Unable to add new cluster storage box

### ISSUE THREAD

**Issue by Aravind1980** [grafana/grafana#6525]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v2.5.0
- What datasource are you using? OCUM
- What OS are you running grafana on? Linux
- What did you do?  
Added new storage box in netapp harvest , But it is not reflecting in gui.
And some of the volumes has been moved to another svm . in that svm the volume is not showing
- What was the expected result? 0
- What happened instead? No information got  Please can you help asap

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
Please open issue with ocum / netapp

**Comment by Aravind1980** [comment]
In grafana existing netapp c-dot filers is opening , but new filer is added  in Netapp harvest it is not getting updated. Or please can you able to share me steps to by steps to add new storage box after that what services need to do .it will be help ful for me
