### ISSUE TITLE
Dashboard List Visual Bug after patching to 9.4.7

### ISSUE THREAD

**Issue by hcshy** [grafana/grafana#65256]
**What happened**:
Updating from 9.3.8 to 9.4.7 manually resulted into a visual bug of dashboard links.

![Bugged](https://user-images.githubusercontent.com/127315762/227183485-0ba5cd83-fb23-4e6e-9ec5-e3beab0d1d90.png)

**What you expected to happen**:
The dashboard links layout being consistent after the patch as shown below.

![Expected](https://user-images.githubusercontent.com/127315762/227183151-8feb4861-3739-4eb8-9b3b-5ebfe7cba726.png)

**How to reproduce it (as minimally and precisely as possible)**:
Updating from 9.3.8 to 9.4.7 on windows server 2019 with dashboard links.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version:
- OS Grafana is installed on: Windows server 2019

- User OS & Browser: Windows 10, Google Chrome, Microsoft Edge
- Grafana plugins: Dashboard List
- Others:

**Comment by gdubroeucq** [comment]
I don't think you should use 9.4.7, the release looks bugged (185 commits difference and 4 versions jump from the latest version aka 9.4.3).

--> go to 9.4.3 instead

**Comment by HenrikRolandHansen** [comment]
I observe the same issue on raspberry pi 9.4.3 and on windows 10 version. List is shown as links and not as buttons like in version prior to 9.4.x

**Comment by JoaoSilvaGrafana** [comment]
Hi @hcshy , thank you for raising this!
This is actually an intended visual change that has been agreed with designers (see these two PRs: [one](https://github.com/grafana/grafana/pull/60140) [two](https://github.com/grafana/grafana/pull/61282)).
It still behaves the same way, as in you can click any part of the card and go to that dashboard, but the design has been tweaked. We appreciate your feedback though and will keep it in mind as we make these design changes.

**Comment by torkelo** [comment]
@HenrikRolandHansen well, they are no buttons but are in fact http links, so the new designs should be more accurate to what they are :)
