### ISSUE TITLE
Redirect singlestat-panel to grafana-singlestat-panel and update README

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#65254]
Since https://grafana.com/grafana/plugins/grafana-singlestat-panel/ is deprecated and we have https://grafana.com/grafana/plugins/stat/ as an alternative. 

We should mark the grafana-singlestat-panel as deprecated in README so that it's clear that it should not be used anymore.
And redirect https://grafana.com/grafana/plugins/grafana-singlestat-panel/ to stat

```[tasklist]
### Tasks
- [x] Update Readme on GCOM
- [x] Redirect `grafana-singlestat-panel` to `stat`
```

**Comment by ryantxu** [comment]
While futzing with the catalog, make the related change:

https://grafana.com/grafana/plugins/heatmap-new/
should redirect to:
https://grafana.com/grafana/plugins/heatmap/

and likely have the correct icon
