### ISSUE TITLE
Date_trunc() function with Postgresql not working

### ISSUE THREAD

**Issue by flavioaraujozup** [grafana/grafana#65261]
* **What** are you trying to achieve? 

- Use DATE_TRUNC() Function with Postgresql and Grafana

* What Grafana version and what operating system are you using? 8.4.2  dea7d4996a  

* **How** are you trying to achieve it? |  

* What happened? 

When I run the following query on Dbeaver or DataGrip, the result is like expected, but in Grafana, its subtracting -1 day in the month and showing the last day otf the month. 

**Query**  

``` 
select DATE_TRUNC('month', t.updated_at) as reference, 
count(distinct id) as quantity, 
status 
from table t 
where status = 'X' 
group by reference, status 
order by reference desc; 
``` 

 **Results in Grafana**  

2023-02-28 21:00:00.000
2023-01-31 21:00:00.000
2023-01-31 21:00:00.000
2022-11-30 21:00:00.000
2022-07-31 21:00:00.000

 **And the results in Dbeaver or DataGrip (The result that I expect to see in Grafana) **

'2023-03-01 00:00:00.000000', 
'2023-02-01 00:00:00.000000', '
'2023-01-01 00:00:00.000000', 
'2022-12-01 00:00:00.000000', 
'2022-08-01 00:00:00.000000'

But I changed in Grafana the query add 1 day and that worked fine, but I think that it's not correct

``` 
select (date_trunc('month', t.updated_at)) + '1 day'::interval as reference,
count(distinct id) as quantity, 
status 
from table t 
where status = 'X' 
group by reference, status 
order by reference desc; 
``` 

And now the results are:

'2023-03-01 21:00:00.000000', 
'2023-02-01 21:00:00.000000', '
'2023-01-01 21:00:00.000000', 
'2022-12-01 21:00:00.000000', 
'2022-08-01 21:00:00.000000'

**Comment by mdvictor** [comment]
Hey @flavioaraujozup ! Thank you for opening this issue! We will investigate this situation asap and return with a resolution as soon as we have one.

**Comment by flavioaraujozup** [comment]
Thank you @mdvictor !!!

**Comment by gabor** [comment]
hi @flavioaraujozup , i think there may be a timezone issue here. some ideas that could help:
1. please try a newer version of grafana, `8.4.2` is very old.
2. look at the timezone setting in your grafana-dashboard's time-picker, maybe it needs to be adjusted:
<img width="596" alt="timezone" src="https://github.com/grafana/grafana/assets/51989/e18e5ee2-064a-47e2-9166-80c3da731638">

3. you can open the query-inspector in grafana, go to the `data` tab, and you should see the timestamps here. they will be shown as large numbers (unix-epoch-milliseconds). could you show us those numbers? (also, the corresponding normal, time-formatted output from grafana).
thanks!

**Comment by gabor** [comment]
as we received no new info for a long time, i'm closing the issue. if we get new info, we can reopen it. thank you.
