### ISSUE TITLE
Need to add new storage in netapp harvest

### ISSUE THREAD

**Issue by Aravind1980** [grafana/grafana#6527]
Please include this information:

What Grafana version are you using? v2.5.0
What datasource are you using? OCUM
What OS are you running grafana on? Linux
What did you do?
Added new storage box in netapp harvest , But it is not reflecting in gui.
And some of the volumes has been moved to another svm . in that svm the volume is not showing
What was the expected result? 0
What happened instead? No information got Please can you help asap

In grafana existing netapp c-dot filers is opening , but new filer is added in Netapp harvest it is not getting updated. Or please can you able to share me steps to by steps to add new storage box after that what services need to do .it will be help ful for me

**Comment by torkelo** [comment]
Please open issue with netapp
