### ISSUE TITLE
Discord alerts via webhook fail, return HTTP/400

### ISSUE THREAD

**Issue by alchemydc** [grafana/grafana#65270]
**What happened**:
Adding a new Discord contact point to Grafana AlertManager results in HTTP/400's being returned from Discord when the contact point is tested or alerted to.

Console logs this error:
`logger=ngalert.notifier.discord t=2023-03-23T13:36:38.285587067Z level=error msg="failed to send notification to Discord" error="webhook response status 400 Bad Request"`

**What you expected to happen**:
The notification should be delivered via the Discord webhook successfully and a HTTP/200 or HTTP/204 response code should be returned.

**How to reproduce it (as minimally and precisely as possible)**:
Go to alerting -> notifications -> contact points and add a new Discord contact point.  Specify a valid Discord webhook URI, leave other options as default.
Click on 'test', and 'Send test notification', using the predefined notification message.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: any
- OS Grafana is installed on: Debian11
- User OS & Browser: Chrome/OSX
- Grafana plugins: AlertManager
- Others:

**Comment by grobinson-grafana** [comment]
Thanks for reporting this bug, we will take a look!

**Comment by Sinderella** [comment]
Hi @grobinson-grafana 

I've got the following log, not sure if it's any help.

```
2023-04-26 21:25:19 | logger=accesscontrol.service t=2023-04-26T20:25:19.572682624Z level=debug msg="using cached permissions" key=rbac-permissions-1-user-1
2023-04-26 21:25:19 | logger=ngalert.notifier.discord t=2023-04-26T20:25:19.575425959Z level=error msg="Missing receiver"
2023-04-26 21:25:19 | logger=ngalert.notifier.discord t=2023-04-26T20:25:19.575611062Z level=error msg="Missing group labels"
2023-04-26 21:25:19 | logger=notifications t=2023-04-26T20:25:19.577156287Z level=debug msg="Sending webhook" url=https://discord.com/api/webhooks/<redacted>/<redacted> httpmethod=POST
2023-04-26 21:25:19 | logger=notifications t=2023-04-26T20:25:19.749311947Z level=debug msg="Webhook failed" url=https://discord.com/api/webhooks/<redacted>/<redacted> statuscode="400 Bad Request" body="{\"embeds\": [\"0\"]}"
2023-04-26 21:25:19 | logger=ngalert.notifier.discord t=2023-04-26T20:25:19.74936318Z level=error msg="failed to send notification to Discord" error="webhook response status 400 Bad Request"
```

I tried to capture the HTTP request's body and this is what I've got.

```json
{
  "username": "Grafana",
  "content": "**Firing**\n\nValue: [no value]\nLabels:\n - alertname = TestAlert\n - instance = Grafana\nAnnotations:\n - summary = Notification test\nSilence: http://<hostname>:3000/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana\n",
  "embeds": [
    {
      "title": "[FIRING:1]  (TestAlert Grafana)",
      "type": "rich",
      "url": "http://<hostname>:3000/alerting/list",
      "color": 14037554,
      "footer": {
        "text": "Grafana v9.5.1",
        "icon_url": "https://grafana.com/static/assets/img/fav32.png"
      }
    }
  ]
}
```

I just noticed that using the same image locally on docker works just fine. The instance that doesn't work for me is hosted on k8s. I hope any of this helps. Thank you for looking into it!

**Comment by Sinderella** [comment]
@grobinson-grafana after a few attempts, it seems like the `url` within `embeds` cannot be a hostname (possibly without a TLD). In my case, localhost or any domain name works. However, hostnames like `grafana` wouldn't work.

**Comment by armandgrillet** [comment]
There is no validation of this in Grafana nor Prometheus Alertmanager, we believe this is a limitation of the Discord API. We should log these errors and document this for users to be aware of the need to use a TLD for URLS within `embeds`.

**Comment by grobinson-grafana** [comment]
I'm going to update Grafana so the reason for the error is logged. I'm not sure about adding validation for this right now as the validation rules for `URL` are not well documented in [Discord's developer docs for embeds](https://discord.com/developers/docs/resources/channel#embed-object).

**Comment by grobinson-grafana** [comment]
I just checked the code and it appears to be logged:

```go
if err := d.ns.SendWebhook(ctx, cmd); err != nil {
	d.log.Error("failed to send notification to Discord", "error", err)
	return false, err
}
```

but the error in `err` is not useful.

The issue here is that it uses `SendWebhook` which is generic, and so it doesn't understand how to decode the JSON response for the Discord API. We'll need to do what Slack does and use it's own `http.Client` instead of `SendWebhook`.

**Comment by emmachase** [comment]
Just noting for anyone coming here from Google that in my case, it was failing because the labels attached to the alerts were way too long for the Discord embed title length limit. Changing the notification title template in the "Contact points" configuration to only include the count of firing/resolved alerts resolved it.

```
{{- if eq .Status "firing" -}}
  🔥 {{ len .Alerts.Firing }} Firing
{{- else -}}
  ✅ {{ len .Alerts.Resolved }} Resolved
{{- end -}}
```

**Comment by cocuba** [comment]
> Just noting for anyone coming here from Google that in my case, it was failing because the labels attached to the alerts were way too long for the Discord embed title length limit. Changing the notification title template in the "Contact points" configuration to only include the count of firing/resolved alerts resolved it.
> 
> ```
> {{- if eq .Status "firing" -}}
>   🔥 {{ len .Alerts.Firing }} Firing
> {{- else -}}
>   ✅ {{ len .Alerts.Resolved }} Resolved
> {{- end -}}
> ```

thanks, i removed the labels and i can send to discord!

**Comment by yuri-tceretian** [comment]
PR https://github.com/grafana/alerting/pull/218 updates the Discord integration to log the response from the API + return code and message from the response. I think this should cover this issue.
