### ISSUE TITLE
Graph not visible

### ISSUE THREAD

**Issue by iwalz** [grafana/grafana#6529]
## **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request

## What Grafana version are you using?
3.1.1
## What datasource are you using?
influxdb
## What OS are you running grafana on?
coreos 1185.3.0
## What did you do?
I've created a new dashboard, added a new template (host) and created a new graph and visualize the following query with an influxdb data source:

```
SELECT mean(used_percent) FROM "mem" WHERE "host" =~ /$host$/ AND $timeFilter GROUP BY time($interval), host
```
So far so good:
![image](https://cloud.githubusercontent.com/assets/2069984/20154572/470f75e6-a6c8-11e6-9cd9-202a77ce454e.png)

The template query looks as follows:
```
SHOW TAG VALUES FROM "cpu" WITH KEY = "host"	
```

After I closed the edit mode and went back to the dashboard, the graph and the legend overlaps:
![image](https://cloud.githubusercontent.com/assets/2069984/20154662/b18a388e-a6c8-11e6-91f6-879be1f6272b.png)

After hitting F5, the graph only contains the legend:
![image](https://cloud.githubusercontent.com/assets/2069984/20154689/d161f9b2-a6c8-11e6-8956-1373ff2d9e57.png)

The data comes exactly as expected:
![image](https://cloud.githubusercontent.com/assets/2069984/20154738/15545e44-a6c9-11e6-8d9a-b0e6a58e2766.png)

Since this could be only related to client side stuff, here's some information about my environment:

Chrome: 51.0.2704.103
OS: Ubuntu 16.06

This is reproducable in around 1 of 3 cases and if it happens, it also survives restart of the container & wiping the dashboard and import it again. Re-do the action seems to be an option, but only on a new dashboard. Everytime I have this situation, I have to re-create the dashboard, copy&paste around and hope it doesn't happen again. 

Grafana runs in kubernetes and uses EBS from AWS for storing the sqlite stuff.

## What was the expected result?
Show the graphs as it shows if I click `view`:
![image](https://cloud.githubusercontent.com/assets/2069984/20154935/e8b0f8a6-a6c9-11e6-83d1-fb3f0584743a.png)

btw.: PUT a json blob to api/dashboards/import that was exported from the UI (so missing dashboard: and input: json keys) let grafana panic - probably a nice error message would be helpful, just a side-note.

**Comment by torkelo** [comment]
Very strange, thousands have use 3.1.1 with InfluxDB without issues, so think it could be a browser problem. What browser are you using, please open chrome dev tools and look at console, any errors?

**Comment by iwalz** [comment]
Indeed, this is strange ...
I get the following error in the console:
![image](https://cloud.githubusercontent.com/assets/2069984/20155876/2fd7d1c4-a6ce-11e6-8360-ae65a32b48cd.png)

As mentioned above, Chrome 51.0.2704.103 on Ubuntu 16.06.
I have been using exact this grafana version for a while now and this just started to happen about a week ago - sometimes kubernetes just moves the containers, but also inspecting the logs doesn't give a better hint than height 0 in this message.

But this is not even the only graph in this row, adjusting the height changes nothing:
![image](https://cloud.githubusercontent.com/assets/2069984/20155977/a5e4393e-a6ce-11e6-9874-ae6b9693cf24.png)

The same situation in firefox ...
![image](https://cloud.githubusercontent.com/assets/2069984/20156057/f9af8a0a-a6ce-11e6-9d98-777e79c32203.png)

**Comment by torkelo** [comment]
The legend on the right needs to have table mode enable to align properly, looks like there is not much room for the graph, with that wide legend on the side and another graph on the row

**Comment by iwalz** [comment]
The legend is now correctly formatted, but the graph still doesn't show up:
![image](https://cloud.githubusercontent.com/assets/2069984/20168441/904db6c8-a722-11e6-81b2-86e4c997ce75.png)

This is the inspected HTML on the empty element:
![image](https://cloud.githubusercontent.com/assets/2069984/20168530/f485592a-a722-11e6-871d-6b165f3e7f29.png)

And the non-empty:
![image](https://cloud.githubusercontent.com/assets/2069984/20168576/36cd70ba-a723-11e6-941c-d970bfb91d18.png)

**Comment by torkelo** [comment]
and if you reduce the width/span of the other graph to make room for the right graph?

**Comment by iwalz** [comment]
This doesn't change anything - somethines this even happens if this is the only graph in the row.
And this inspection looks like its more about the height than the width ...

![image](https://cloud.githubusercontent.com/assets/2069984/20170669/83e3487a-a72d-11e6-818a-0ade9bb9ed05.png)

**Comment by torkelo** [comment]
and the only error you get is the `flot invalid dimenssions`, no other error?

Can you show the raw response from InfluxDB when you get the error?

**Comment by iwalz** [comment]
Yes, that's the only error. The response looks fine. Since the same query is working in 1 of 3 cases, and the response only looks like this, I don't think this is somehow important.

I've pasted it to pastebin: http://pastebin.com/JbA6ee38

**Comment by torkelo** [comment]
cannot replicate it with your data in v4-beta1 (master), 

<img width="838" alt="screen shot 2016-11-10 at 10 38 34" src="https://cloud.githubusercontent.com/assets/10999/20171647/efb67596-a731-11e6-8808-4abfe23613d9.png">

Try updating chrome to latest, or if that does not work try v4-beta1

**Comment by iwalz** [comment]
Same situation in 4-beta1 for me:
![image](https://cloud.githubusercontent.com/assets/2069984/20183276/0d34e322-a765-11e6-9ea3-659ffdde1294.png)

Upgrading chrome didn't made a difference, but since it happens in firefox too, this doesn't seem to be browser related. I think that during the chart creation something went wrong - and it keeps this 0 height information across deleting / re-importing dashboard (which makes sense, I want to have what I just exported).

Any hints, what operations can be height related? I'm gonna try hacking the HTML source and do some tests on 4.0-beta1.

I'm getting the same error in V4: `Invalid dimensions for plot, width = 274.109375, height = 0`

**Comment by torkelo** [comment]
can you show the panel json? maybe you specified height 0 in the panel general tab?

**Comment by iwalz** [comment]
This is indeed interesting ... There was a 0 in the height, but since I haven't even seen this setting (just the height of the row) I'm quiete sure I haven't added it ... Removing that value fixes that ... *headbang*

Let me check if that's happening again and I try to verify where this 0 comes from - in the meanwhile: thanks for the support!
