### ISSUE TITLE
BarChart: legend colors do not correspond to bar colors

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#65299]
**What happened**:
BarChart legend colors do not correspond to bar colors
https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&viewPanel=15

**What you expected to happen**:
Bar colors should be the same as legend colors

**How to reproduce it (as minimally and precisely as possible)**:
Just see https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&viewPanel=15

**Environment**: play.grafana.org
- Grafana version: 9.4.7

**Comment by vincent-olivert-riera** [comment]
> Grafana version: latest

@GrzegorzLyp , "latest" is an inaccurate term. The "latest" version of today will be different than the "latest" version of tomorrow. To be precise, could you please specify the exact version? Perhaps `v9.4.7 (4add91f03d)`?

**Comment by GrzegorzLyp** [comment]
Updated: Version: 9.4.7
I used term "latest" because it corresponds to "play.grafana.org" that has actually latest version.

**Comment by vincent-olivert-riera** [comment]
I think this bug is pretty important. Having charts presenting wrong information is worse than having no information at all. One could take actions based on what they see on the chart, but if the chart is wrong so are the actions.

@zuchka , is not possible to have this bug fixed ASAP and get the current release (9.4.7) fixed, maybe releasing a 9.4.7.1? Basically, the bar charts on the current release cannot be trusted, and they are probably causing confusion (or important mistaken actions) to everyone using them.

**Comment by GrzegorzLyp** [comment]
Please include this problem with BarChart.
https://github.com/grafana/grafana/issues/63917

**Comment by leeoniya** [comment]
https://user-images.githubusercontent.com/43234/229305141-7f4a7742-484e-44d5-9556-ecb800117879.mp4

this looks like an issue with the way value mappings are applied. the ones in the linked play dashboard are kind of nonsense (true/false), but there's still a bug here. it does not appear to be critical enough to rush it into 9.5, which is feature freezing on monday, but we'll work on a fix for 9.5.x and backport it to the next 9.4.x release.

things looks like they work okay in the dashboard below, though the Legend could use some work (what do you show when a single bar series can be a rainbow via mappings? i guess the legend needs to become mappings? what if you have multiple bar series with different maappings for each series? :exploding_head:):

https://play.grafana.org/d/barchart-thresholds-mappings/barchart-thresholds-and-mappings?orgId=1

**Comment by torkelo** [comment]
Hmm this sounds strange, legend shows series / Fields. While value mappings color values

**Comment by Lroy** [comment]
This same problem exists with line charts on TimeSeries.  I have reported under another issue awhile ago.

**Comment by vincent-olivert-riera** [comment]
> This same problem exists with line charts on TimeSeries. I have reported under another issue awhile ago.

Could you provide a link to that issue?
Could you provide an example from https://play.grafana.org ?

**Comment by Lroy** [comment]
I just tried the time series charts on play.grafana.org, and I cannot get the same results.  I wonder if the issue was fixed but not reported in the release notes?

The original issue that I reported was:

https://github.com/grafana/grafana/issues/62883

**Comment by Lroy** [comment]
I wonder if the play.grafana.org time series charts have had the legend colors forced to some color, which causes the issue to go away.  I just tried my 9.2.2 with time series, and the problem is definitely there, unless I force the series colors to something specific.

**Comment by GrzegorzLyp** [comment]
@adela-almasan can You add also https://github.com/grafana/grafana/issues/63917 to the epic?

**Comment by GrzegorzLyp** [comment]
Solved in 10.0.1 
https://github.com/grafana/grafana/pull/69931
