### ISSUE TITLE
'List' tab in 'Annotations' not rendered properly in 4.0.0-beta1

### ISSUE THREAD

**Issue by kyloon** [grafana/grafana#6530]
![screenshot](https://cloud.githubusercontent.com/assets/8691956/20157817/00df8426-a68c-11e6-9d12-a8ce384944fa.png)

Similar issue observed in both Chrome and Safari.

**Comment by torkelo** [comment]
Cannot replicate in Chrome 54.0.2840.98 (64-bit) on Mac, but Safari does seem to have a problem with the border image

`border-image: linear-gradient(to right, rgba(255, 213, 0, .7) 0, rgba(255, 68, 0, .7) 99%, rgba(255, 68, 0, .7) 100%);`

Need to search why this has stopped working in Safari

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
