### ISSUE TITLE
Can you give some detail steps for guys who uses elasticsearch as data source?

### ISSUE THREAD

**Issue by zhangjh** [grafana/grafana#6532]
I setuped grafana and elasticsearch ,but I can not add data to the graph. I read the docs and googled many times but helped little.

I think the official document is not very helpful to the beginners. Many key steps is very simple in the document. Such as the add data source using elasticsearch section.

Below is my data source setting. I wondered that how grafana get data from elasticsearch.

![](http://ww3.sinaimg.cn/mw690/62d95157gw1f9mzzj1gy9j20t30npmyq.jpg)

![](http://ww4.sinaimg.cn/mw690/62d95157gw1f9mzzjm0khj20l106gmxi.jpg)

If I can get data using : "http://es.alibaba.net:9200/commandar/resource/_search", how can I input the QUERY field to get "cost_time" from elasticsearch and display the graph.

English is not my mother tongue, May you get my point.

**Comment by torkelo** [comment]
the query field is where you can specify an elasticsearch lucene query string to filter the data.

**Comment by torkelo** [comment]
for the future please post question to the mailing list
https://groups.io/g/grafana
