### ISSUE TITLE
The Annotation List panel is not automatically refreshed when a variable's value changes

### ISSUE THREAD

**Issue by GuillemCastro** [grafana/grafana#65349]
**What happened**:

I created an annotation with a tag named "ABC",

![Screenshot from 2023-03-27 14-42-55](https://user-images.githubusercontent.com/9038611/227946249-eb58a45e-3dc5-45ad-a740-6120277d2eb5.png)

Then, I created a new dashboard with a variable named "tag",

![Screenshot from 2023-03-27 14-44-43](https://user-images.githubusercontent.com/9038611/227946324-2ca70c14-771b-4e0f-978b-c75ff661a4dc.png)

To said dashboard I added an Annotation list with a tag filter, filtering by the value of the $tag variable,

![Screenshot from 2023-03-27 14-45-34](https://user-images.githubusercontent.com/9038611/227946439-f14725ec-82b6-44d0-86b4-8fb8abe83b67.png)

Nothing happens if you change the value of the variable, the annotation list is not being filtered by the new value of the variable. In order for the filter to be applied you have to refresh the browser page,

[Screencast from 2023-03-27 14-48-17.webm](https://user-images.githubusercontent.com/9038611/227946608-ea84c1e8-528d-41c6-98e7-a3ed27eeb37e.webm)

**What you expected to happen**:

The annotation list should automatically refresh after a variable changes value

**How to reproduce it (as minimally and precisely as possible)**:

See the steps I followed above. The JSON of the dashboard with the annotation list if the following,
```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 18,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "limit": 10,
        "navigateAfter": "10m",
        "navigateBefore": "10m",
        "navigateToPanel": true,
        "onlyFromThisDashboard": false,
        "onlyInTimeRange": false,
        "showTags": true,
        "showTime": true,
        "showUser": true,
        "tags": [
          "$tag"
        ]
      },
      "title": "Panel Title",
      "type": "annolist"
    }
  ],
  "refresh": "",
  "revision": 1,
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "",
          "value": ""
        },
        "hide": 0,
        "name": "tag",
        "options": [
          {
            "selected": true,
            "text": "",
            "value": ""
          }
        ],
        "query": "",
        "skipUrlSync": false,
        "type": "textbox"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Anotations",
  "uid": "7-NNDBBVk",
  "version": 3,
  "weekStart": ""
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version:
- OS Grafana is installed on: Official Docker image (`grafana/grafana:9.4.3`)
- User OS & Browser: Windows/Linux & Chrome/Firefox
- Grafana plugins:
- Others:

**Comment by JoaoSilvaGrafana** [comment]
Hi @GuillemCastro 👋  Thanks for raising this, I have managed to reproduce it, so will be putting it into our team backlog.
I have created the dashboard here as well so we can test it when developing: https://play.grafana.org/d/7-NNDBBVk/65349-annotation-list-not-updating
