### ISSUE TITLE
quicker way to add new row in arbitrary places

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6535]
let's say i have a dash with 10 rows and i want to add a row between row 4 and 5. now i always have to go the bottom, hit "new row" and then bring it up step by step.  

some ideas:
* in the row menu that automatically comes up on the left now, add options like "add new row below" and "add new row above"
* have a new menu that comes up when you hoover on the left *between rows* with an option "add new row here"

**Comment by torkelo** [comment]
Yes, feel the same pain here. and your suggestions are pretty good. Just need to add support for submenu's in the new slide out row menu. 

@mattttt thoughts?

**Comment by bulletfactory** [comment]
I like this personally. I think it will be really useful and more efficient.

**Comment by torkelo** [comment]
Rows are not as needed anymore and can in v5 be dragged around as well so closing this.
