### ISSUE TITLE
GLDS- Saga Website: Use grafana theme for the styling

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#65359]
We are now using emotion in the Saga website ([PR](https://github.com/grafana/design-system/pull/7/files)) in order to be able to use the grafana theme tokens. However, there are several places in Saga that do not use values that match any token, we should change those places to use a theme token.

One of the key questions is around the font size though, as the base font size for grafana ui is 14px, but in Saga it is 16px. We don't want to make the font for docs too small, so might need to consider how we adapt the tokens in that case?

**Comment by staton-hyse11** [comment]
this seems to be complete.
