### ISSUE TITLE
Loki Docs: Ambiguous instructions for Label browser buttons

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65364]
In the [Loki query editor](https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/) docs page, the “Label browser” section could be more explicit about the purpose of the “Show logs” and “Show logs rate” buttons. The user might not yet be familiar with the “metric query” concept.

We also don't specifically say anything about rate, and instead we talk about "metric query".

![Image](https://user-images.githubusercontent.com/1069378/227969368-ddcbf183-fe20-4f13-890e-271c25856b5e.png)

Point 3 could do a better job explaining the outcome of each button:

![Image](https://user-images.githubusercontent.com/1069378/227969605-77ce0b1e-700d-498c-b2e6-54d2a5997a6e.png)

Part of https://github.com/grafana/grafana/issues/65370

**Comment by GrafanaWriter** [comment]
FYI @JStickler

**Comment by GrafanaWriter** [comment]
Actually, @lwandz13 - I think this one is yours.

**Comment by lwandz13** [comment]
I approved the PR
