### ISSUE TITLE
Loki Docs: Remove mentions of "raw query"

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65367]
In the [Loki query editor](https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/) docs page. The “Raw query” concept no longer exists as before, we show it by default.

![Image](https://user-images.githubusercontent.com/1069378/227971318-ce0877f7-a785-4de2-8d71-8c25c53324b6.png)

Part of https://github.com/grafana/grafana/issues/65370

**Comment by GrafanaWriter** [comment]
FYI @JStickler
