### ISSUE TITLE
Loki Docs: Confusing icon description for Operations of Builder Mode

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65366]
In the [Loki query editor](https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/) docs page, The “Operations” section inside “Builder mode” has a table describing “v”, “info”, and “x” buttons, which aims to describe the following icons:

![Image](https://user-images.githubusercontent.com/1069378/227970632-664876e0-cc1d-41d1-a4fa-0b94c06f983f.png)

Docs:

![Image](https://user-images.githubusercontent.com/1069378/227970715-916748d4-e26f-4b79-aa33-402d00c0ce4d.png)

We should use different terms or illustrate it with images so the message is more clear.

Part of https://github.com/grafana/grafana/issues/65370

**Comment by GrafanaWriter** [comment]
FYI @JStickler
