### ISSUE TITLE
row "show" option is confusing

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6536]
in the left hover row options menu, there is a "show" option.
since you're in the row options menu one would deduce this means whether to show the row or not. but it instead it has these 2 effects:
1) the row title becomes visible.
2) the row can be collapsed. 

We should tie the option closer to the title option, make it obvious that all options here relate to the row title, make some sort of section.
or rename the option to "show title", or perhaps "collapsable" which makes effect 2 more clear, but effect 1 becomes more unclear/implicit.

@mattttt thoughts?

**Comment by torkelo** [comment]
I mean it's next to Title & Size option, and when you click it the row title appears. It has nothing to do with collapse or not (you can do that from row menu as well). 

But I agree, maybe not clear enough. Maybe a section heading for those 3 options could be in order. or change the checkbox label to "Show title when the row is expanded"

**Comment by torkelo** [comment]
row show option is no more, now in v5 all rows must have visible title
