### ISSUE TITLE
Loki Docs: Deadlinks in Query Editor page

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65362]
In the [Loki query editor](https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/) docs page, the “log” and “metric” links in the first paragraph are dead links.

![Image](https://user-images.githubusercontent.com/1069378/227966971-dd7c0fe0-cba0-4890-8faf-689d2c908293.png)

**Comment by GrafanaWriter** [comment]
FYI @JStickler
