### ISSUE TITLE
Loki Docs: Expand Logs Context section

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65368]
In the [Loki query editor](https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/) docs page, in the Logs Context section, it’s not clear that “Show log context” points to a hover option over log lines.

![Image](https://user-images.githubusercontent.com/1069378/227972594-6a7905a2-7a76-4465-9b4a-ad4c2e2a4c41.png)

We could also expand a little bit more the description about Logs context and its purpose, which is one of the most useful features when exploring logs.

It also says "When using a search expression as detailed above", when there's no search expression detailed near the section.

Part of https://github.com/grafana/grafana/issues/65370

**Comment by matyax** [comment]
FYI @svennergr

**Comment by GrafanaWriter** [comment]
FYI @JStickler

**Comment by GrafanaWriter** [comment]
And FYI @lwandz13 as part of the work on data sources.

**Comment by ivanahuckova** [comment]
Closing this as in https://github.com/grafana/grafana/pull/67202 we updated logs context documentation for loki
