### ISSUE TITLE
Loki: Improve UI for empty status

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65374]
The empty state could do a better job communicating the current situation. It currently displays “no data” when you haven’t run any query. E.g. “Enter a query” or “No logs selected”.

![Image](https://user-images.githubusercontent.com/1069378/227978133-9063d29f-b366-4268-a1e2-f9e3de724734.png)

Part of https://github.com/grafana/grafana/issues/65370

**Comment by matyax** [comment]
What do you think @niat22 @marybelvargas

**Comment by niat22** [comment]
@matyax AKN.
