### ISSUE TITLE
going out of "row options" is too hard. escape key bind?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6537]
in left hover options menu, when you hit row options, and then you want to leave, you need to take the mouse all the way to the right to hit the x button.

we should support hitting esc to leave again. similar to how we support going in and out of panels

**Comment by torkelo** [comment]
agree, @mattttt also talked about other ways to make it easier (having Add Panel and Row Options tabs on the left side, with X icons so you do not have to move the mouse to right side).

But sadly no time to improve that.

**Comment by torkelo** [comment]
fixed in master (row options in modal)
