### ISSUE TITLE
fail to start session... "dial unix data/sessions: connect: no such file or directory"

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#6539]
-  Bug report

- grafana 4.0 beta1
- linux

- Installed 4beta1 with memcache sessions and provider config
- Attempted to login as admin

- What was the expected result? Expected to log in.
- What happened instead? Got a redirect loop.  Chrome or Safari, clearing cookies doesn't help.

Logs say:

t=2016-11-10T17:19:04+0000 lvl=eror msg="Failed to start session" logger=context error="dial unix data/sessions: connect: no such file or directory"

**Comment by blysik** [comment]
I ended up switching to postgres sessions, but I couldn't solve this with redis based sessions at all.

**Comment by bergquist** [comment]
What does your provider_config value look like?

**Comment by blysik** [comment]
Previously, I was passing a redis:// url.  Before 4.0 that seemed to work.  But looking at the docs now, that isn't the right format.

**Comment by blysik** [comment]
So it was something like:

redis://redisdb:lheL4wiqD-RrifQ_WMD3YsOtkSb-lErvQRsvw0a140w@myhostname:39855/0

**Comment by bergquist** [comment]
"Installed 4beta1 with _memcache_ sessions and provider config" I guess you meant redis?

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L95 the session configuration should look like that.
