### ISSUE TITLE
Down arrow appearing when it shouldn't while using topnav

### ISSUE THREAD

**Issue by callmehyde** [grafana/grafana#65394]
**What happened**:
While using an instance with `topnav` enabled I experienced an arrow that (to me) indicates there's scrollable content, but in reality there's no additional content to scroll. This feels like a bug and is a confusing user experience.

**What you expected to happen**:
I would expect the down-scroll-arrow to only appear when there's actually scrollable content.

**How to reproduce it (as minimally and precisely as possible)**:

Using Safari 16.3 do the following...

1. Set browser zoom to 85%
2. Login to a Grafana instance with `topnav` enabled
3. Open the navigation
4. Collapse any open headers so they're all closed
5. Open just the "Dashboards" heading
6. (**Problem should be visible here**) A slight overlay with a down-scroll-arrow should appear over the "Administration" heading

**Anything else we need to know?**:
I _assume_ the issue is related to the page zoom in some way. When I flip between 85% zoom and 100% zoom I experience different behavior. At 100% zoom the navigation and down-scroll-arrow work as expected.

Here's a screen recording of me replicating the behavior. Note, when the video starts my browser is at 85% zoom and I go up and down using cmd +/-.

https://drive.google.com/file/d/1Lht7DzlOqScwh2IZ9crGus2wvEZAgkKq/view?usp=sharing

**Environment**:
- Grafana version: Grafana v9.5.0-53754pre
- User OS & Browser: 2021 14-inch MacBook Pro (`13.2.1 (22D68)`) with Safari (`16.3`)
- Others: I'm using Safari with 85% page zoom instead of 100%.

**Comment by ashharrison90** [comment]
still can't repro 😭 

13.2.1, safari 16.3, starting with 85% zoom:

https://user-images.githubusercontent.com/20999846/228217195-4c2680f0-0c31-4173-a700-7f2373472679.mp4
