### ISSUE TITLE
Single panel shared view

### ISSUE THREAD

**Issue by jordanrinke** [grafana/grafana#654]
I would like to be able to share a single panel in a non-editable format condenced form (zoom and date range on the panel itself). Think PNG sharing/embedding but better. My specific use case is embedding a specific panel in a customer facing portal (using nginx basic auth to protect the path)

**Comment by bbinet** [comment]
I think this is now addressed in the great snapshot sharing feature of grafana v2.

**Comment by torkelo** [comment]
True!

**Comment by Dieterbe** [comment]
@torkelo just noticed this ticket is still open for the 2.0-beta1 milestone, which has been closed.
you might want to close this ticket, or move it to a more recent, open milestone

**Comment by torkelo** [comment]
yes, this is already implemented
