### ISSUE TITLE
Pausing Grafana alerting rules from Mobile app (React Native) through Grafana API

### ISSUE THREAD

**Issue by Yoslandy** [grafana/grafana#65405]
**What happened**:

I'm trying to use the grafana API to pause and unpause grafana alerts via a mobile app in React-Native and Expo. following the documentation, with postman, the states are changed correctly, but when I make the app calls I can unpause the alerts but I can't pause them. My grafana workspace is in AWS Managed Grafana

This is my function to change state
`const changeAlertsStatus = (item) => {
    var state = {
      paused: item.state === "paused" ? false : true,
    };

    console.log(state);
    const URL = `${myURL}/api/alerts/${item.id}/pause`;
    try {
      fetch(URL, {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: SynergyGrafanaApiKey,
        },
        body: state,
      })
        .then((response) => response.json())
        .then((json) => {
          console.log(json);
          getAlertsList();
        });
    } catch (error) {
      console.log(error.message);
    }
  };`

This is the console logs
`LOG  {"paused": true}
 LOG  {"alertId": 20, "message": "Alert is already un-paused", "state": "un-paused"}

 LOG  {"paused": true}
 LOG  {"alertId": 6, "message": "Alert is already un-paused", "state": "un-paused"}

 LOG  {"paused": false}
 LOG  {"alertId": 20, "message": "Alert un-paused", "state": "unknown"}`

And this is how the app looking
![image](https://user-images.githubusercontent.com/34694121/228070165-03428def-2904-4780-baed-c7ce4aacd504.png)

**What you expected to happen**:

I would like to understand why if the alert is paused, the status changes without difficulty, but when I try to pause it, it doesn't allow me and returns that message in the second photo. The call is being made, but for some reason it doesn't change it.

**How to reproduce it (as minimally and precisely as possible)**:
I dont have idea what this means

**Anything else we need to know?**:
Any other question feel free to ask. I would like to solve this problems. Thanks in advance

**Environment**:
- Grafana version: AWS Managed Grafana v8.4.7
- Data source type & version:  Using Sitewise as Data Sourses
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by Yoslandy** [comment]
Hi, Any comment concerning with this matter please. Thanks?

**Comment by Yoslandy** [comment]
Hi, Any result, Any suggestion?

**Comment by k3vl4rAtAirside** [comment]
How about in version 9 alerting?  There isnt even an option to pause alerting?

**Comment by Yoslandy** [comment]
Hi @k3vl4rAtAirside. I dont really understand what you mean. Could you be more specific?

**Comment by k3vl4rAtAirside** [comment]
Apologies I do see inside of the alert configuration there is a "Pause" toggle.

**Comment by armandgrillet** [comment]
This is legacy alerting which we do not support since Grafana 9, the logs indicate that the alert is already unpaused thus this seems a frontend issue related to the custom implementation you have.
