### ISSUE TITLE
Alert for condition being met for a length of time.

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6540]
* **I'm submitting a ...**
- [ ] Bug report
- [ x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I have a need to alert only after my value is over a threshold or within a range for a length of time. Example, alert when average temp is over 41 degrees for 15 minutes.  Right now it alerts if over 41 degrees anytime in the last 15 minutes.

**Comment by bergquist** [comment]
This could also be solved by setting the alert query to 15min - now and use the min aggregator.
Then the query will alert once the lowest value the last 15min is above 41 degress.

Does this make sense?

**Comment by torkelo** [comment]
yes, just pick the correct aggregation function (min, or avg)

**Comment by chipper110** [comment]
I am sorry I didn't give enough information.  I need it to alert only after the temperature has been within a range continuously for a given amount of time.  Using the min or avg still alerts as soon as the temp lands in that range.  The temperature that I am monitoring can have short spikes,  I would like to ignore those short spikes and only alert when it is consistently in that range for my desired period of time.  I have gotten it to work by setting 15 conditions that check every minute for 15 minutes. Example, avg-1m to now within range 41-70, and avg-2m to now within range 41-70, and so on.  It does work but it is quite a messy alert and notification.  
![image](https://cloud.githubusercontent.com/assets/20861450/20219532/de1f77ee-a7f7-11e6-9b78-53744d4854de.png)

**Comment by torkelo** [comment]
I am sorry don't understand how you can't solve it with a alert condition checking last 15m, the query could do a 15min moving average if you want the average to have been above 41 for 15 minutes

**Comment by chipper110** [comment]
When using a moving average short spikes and drops can put the average in the alert range and it sends an alert as soon as that average hits in the range.  I need to  ignore those spikes and drops.  That is why I can't use an average, I need to know when all my data points are within a range for 15m.  An alert condition when "all" of "A,15m,now within range" would work great for monitoring different kinds of sensors, which is what I am using Grafana for.

**Comment by torkelo** [comment]
Blank aggregation function like all does not work, as they take in values and return a single value.

You could add two conditions, one with minimal aggregation and one with max

**Comment by chipper110** [comment]
I will give that a try, thanks.

**Comment by chipper110** [comment]
Thanks using the min and max works for what i was looking to do.
