### ISSUE TITLE
Alertlist: Fetch alerts from any dashboard!

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6541]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It would be great if we can fetch alerts from any dashboard and display in one panel.

**Comment by bergquist** [comment]
The support for organizing/categorizing alerts in Grafana is very limited at the moment. We will work on this in upcomming relases and thereby make things like this easier. This might be one way to make that easier.

**Comment by CyBeRoni** [comment]
Doesn't the alert list panel already do this? I'd like to see the reverse actually, be able to set the alert list panel to only fetch alerts from certain dashboards.
