### ISSUE TITLE
Grafana UI: FilterPill inconsistency

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#65412]
**Problem**:
The FitlerPill that is used in Connections has more features and a different look than the one exposed by Storybook.
![image](https://user-images.githubusercontent.com/1438972/228155510-e5cc35df-0168-4036-a605-e1f2142c548d.png)

Storybook:
![image](https://user-images.githubusercontent.com/1438972/228155942-c0b8a652-6147-40f7-927f-85b4f85e20c0.png)

- [ ] Identify the additional features with Connections
- [ ] See if these features can be implemented in Grafana UI

**Comment by staton-hyse11** [comment]
This has been addressed with https://github.com/grafana/grafana/pull/70245#event-9651649121
