### ISSUE TITLE
improve query-inspector/queries tab to handle multi-request queries

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#65424]
there's a new feature in the Loki data source (currently behind the `lokiQuerySplitting` feature flag), where a single Loki `datasource.query()` call may execute multiple ajax-requests. these multiple responses are then combined together to resolve the `datasource.query()` call.

in such a case, the Query Inspector's "queries" tab will only show the latest ajax-request. would be nice if it somehow handled this situation better.

**Comment by JoaoSilvaGrafana** [comment]
Hey @gabor 👋  if I understand correctly this is about the panel inspector? If so, this should be with @grafana/dashboards-squad as they are now responsible for anything dashboard/panel model related. I will put it on their board, but let me know if I read it wrong!

**Comment by axelavargas** [comment]
Hey @gabor 😄 , I think improving the query inspector would be great, but unfortunately, we don't have any immediate plans to work on it. However, I'll add it to our backlog for future consideration. If you think it's an essential requirement for the new feature flag of Loki, please let us know. We can discuss it further in our next Q planning session with the team.

Thanks! 🙏🏾

**Comment by gabor** [comment]
hi @axelavargas , no, it is not an essential requirement, so your plan is totally fine with me 👍 .

**Comment by gabor** [comment]
this is still actual.
