### ISSUE TITLE
Add timestamp of the earliest firing instance of an alert rule

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#65423]
All alert rules indicate for how long they've been on a firing state. For this to work, we need to provide the timestamp of the earlier firing instance from the list.
![Screenshot 2023-03-28 at 10 41 25](https://user-images.githubusercontent.com/231583/228196259-ed0c2be0-c5f9-4a9c-ac36-328265ee128b.png)

**Comment by grobinson-grafana** [comment]
We added an `activeAt` field to the alert rule, similar to the `activeAt` field for alerts.
