### ISSUE TITLE
Help with Grafana and Influxdb - Display data on a graph

### ISSUE THREAD

**Issue by anilhk** [grafana/grafana#6542]
Hi,

I know this is not an issue, it's more of a question if this can be done in grafana or not.
Hopefully someone would point me in the right direction. I am new to grafana and trying to learn.

I have some data stored in influxdb which looks something like the below.

```
time                    branch  build   caldate                         dateRun         failed  passRate        passed
1478815326194000000     16O     103     Thu Nov 10 00:00:00 PST 2016    1475132400000   15      79.73           59
1478815326246000000     16O     101     Wed Nov 09 00:00:00 PST 2016    1475046000000   10      86.49           64
1478815326322000000     16O     100     Wed Nov 09 00:00:00 PST 2016    1475046000000   11      85.14           63
1478815326345000000     16M     97      Wed Nov 09 00:00:00 PST 2016    1474873200000   52      29.73           22
1478815326378000000     16M     96      Wed Nov 09 00:00:00 PST 2016    1474873200000   54      27.03           20
```

I wanted to know if you could display a graph of maximum value of (passRate) vs DateRun in grafana for each of the day.

**Comment by torkelo** [comment]
it depends on what you mean with vs. 

you can pick the passRate field and get a series of it over time , you need to use the time column for time in InfluxDB not custom column (in you case dateRun). So you need to change the way you write data to influxdb. 

Please use the mailing list for questions. 
http://grafana.org/support/
