### ISSUE TITLE
Template variable substitution with  passing special character in extravars does not work

### ISSUE THREAD

**Issue by Shreyas123symc** [grafana/grafana#6543]
I am using command line to peform operation on remote server.
ansible-playbook -i hosts site.yml --tags copy_password --extra-vars "dbPassword=abc$cd"
below is template content,
cat pass.j2
{{ dbPassword }}
I am copying this template file on remote server .and I found that due to "$" its not getting overwrite exactly. 
file content from remote server : 
cat pass.j2
abc --- where as I am expecting here abc$cd the value which I have passed in extravars. 
Can you please help with this issue.

**Comment by Shreyas123symc** [comment]
Please help

**Comment by torkelo** [comment]
Not sure I understand this issue.  Can you please explain in more detail? I can see something about ansible in the question but not seeing how this question relates to what your doing in Grafana.  

Please include full template variable setting,

**Comment by Shreyas123symc** [comment]
No this related to ansible only.

**Comment by Shreyas123symc** [comment]
I am new to this. how to move it to ansible section

**Comment by torkelo** [comment]
you cannot move issues between github repos.
