### ISSUE TITLE
Navigation: Expose ability to define create actions to plugins

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#65448]
with new navigation, there's a set of quick actions defined here:
![image](https://user-images.githubusercontent.com/20999846/228246094-0c0e9d1b-bb9b-49e9-ba45-e9dfcfdb9bb8.png)

this can only be controlled via an internal prop currently. it would be good to expose this prop (or some other mechanism) to plugins, so they are able to place themselves in this menu

**Comment by anavss** [comment]
Hey @ashharrison90 is there anything we could do to "manually" add "declare incident" to the quick actions whilst the prop exposure is not prioritized? It would be helpful for incident users to be able to declare incidents from anywhere in Grafana, and the quick actions would help with that. 

cc: @amy-super @reemtariqq

**Comment by ashharrison90** [comment]
hi @anavss 

apologies for the delayed reply, somehow missed this 😕 

we can of course just hardcode it in the grafana backend
```typescript
if (plugin.id === 'grafana-incident') { 
  // set isCreateAction to true
}
```
but i **really** think we should not do that. it's just creating technical debt for ourselves and doesn't scale.

if it's something you really feel like is needed, let's use that as an impetus to prioritise doing the work to expose it properly.

**Comment by leventebalogh** [comment]
This sounds like a candidate for [UI extensions](https://grafana.com/developers/plugin-tools/ui-extensions/create-an-extension-point) (although we probably talked about it already on other forums).

**Comment by sympatheticmoose** [comment]
Closing as we probably don't want to clutter this, the command palette extension point also provides a way to expose these kind of interactions from anywhere in Grafana
