### ISSUE TITLE
Change singlestat's module.ts 

### ISSUE THREAD

**Issue by 3tinkers** [grafana/grafana#6545]
Hello, I have a question when I want to change singlestat's module.ts.As I want to add a child element in singlestat, I change the singlestat's module.ts and excute tsc module.ts.But it displays as before without my new child element.Should I need to change other settings?
Grafana Version: 3.1.1
OS: CentOs 7.0
Thanks for your any reply

**Comment by torkelo** [comment]
you need to clone github repo and follow the building from source guide
http://docs.grafana.org/project/building_from_source/
