### ISSUE TITLE
Unable to install grafana plugins in windows os 

### ISSUE THREAD

**Issue by venkatmatta1** [grafana/grafana#6548]
I am grafana 3.1.1 and Influxdb Datasources

Issues :- I am trying to install the  plugins but i am a getting below error
grafana-cli plugins install mtanda-histogram-panel

←[31mError←[0m: Get https://grafana.net/api/plugins/repo/mtanda-histogram-panel:
 dial tcp 107.178.222.220:443: i/o timeout

NAME:
   Grafana cli plugins install - install <plugin id>

I tried to install multiple plugin but for all the plugins i am getting same issue . Please let us know whether i need to modify any config changes 

Regards,
Venkat

**Comment by bergquist** [comment]
@venkatmatta1 The grafana-cli is broken on windows in 3.1.1 Please upgrade to 4.0 Beta.
