### ISSUE TITLE
Alerts not working until the first time saving the dashboard

### ISSUE THREAD

**Issue by sweskipper** [grafana/grafana#6549]
* **I'm submitting a ...**
- [ X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? grafana-4.0.0-1478693311beta1.x86_64.rpm
- What datasource are you using? Prometheus 1.3.0
- What OS are you running grafana on? RHEL 6
- What did you do? 
I created a new dashboard and added prometheus uptime graph. After that I added an alert which was really simple. Alert if uptime is below 1.
- What was the expected result?
result
firing false
timeMs 1.927ms
logs [ [object Object], [object Object] ]

- What happened instead?
a Notice popped up:
"Problem!
Failed to test rule"

I tried again after saving this new dashboard, and now the Alert rule was added without any issue.

**Comment by torkelo** [comment]
strange, testing a rule before saving it used to work, must have been regression in alpha

**Comment by torkelo** [comment]
added a check for this and better error message. So you need to save the dashboard at least once, but then you can test the rule, but you do not need to save between each test, but a dashboard id needs to exist.
