### ISSUE TITLE
In the panel variable settings, select tempo as the data source, and there is no option for query

### ISSUE THREAD

**Issue by chenshijian73-qq** [grafana/grafana#65503]
**Steps to reproduce**:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/116276614/228438487-a2e0ec04-8e8c-4b68-9db4-88ac829b9324.png">

**Expected Result**
Hope to add a function similar to Promethues
<img width="703" alt="image" src="https://user-images.githubusercontent.com/116276614/228438721-e8cff9a3-d10d-422e-9bc4-110c1ffb0c3f.png">

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: tempo
- User OS & Browser: chrome
- Others:

**Comment by usmangt** [comment]
Hi @chenshijian73-qq,

Thanks for opening this issue.

Can you please tell us your Tempo version?

**Comment by chenshijian73-qq** [comment]
> Hi @chenshijian73-qq,
> 
> Thanks for opening this issue.
> 
> Can you please tell us your Tempo version?

Tempo 2.0

**Comment by abhi1287** [comment]
Hello, do you have any update?
I still don't see this with Grafana 9.5.1.

**Comment by chenshijian73-qq** [comment]
> 
still dont have query with Grafana 9.5.1.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/116276614/236615543-b50054b7-993b-48d1-b3c2-fef2a09cd794.png">

**Comment by NicolasKarnick** [comment]
Are there any Updates on this?

**Comment by aocenas** [comment]
This should be implemented already


![Image](https://github.com/grafana/grafana/assets/1014802/7cdb937d-d0ac-48c9-9f51-5ad5d9d17bfa)
