### ISSUE TITLE
Improve HTTP response code for user updating data source 

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#65509]
**What happened**:
When user trying to change the name of a data source to the name of another existing data source, the server returns code 500.

**What you expected to happen**:
This is caused by user behavior, returning 500 Internal Server Error is inappropriate.
**How to reproduce it (as minimally and precisely as possible)**:
Have two data sources ready, name them as ds1 and ds2. Then change the name of ds1 to ds2 then click save, the server will return 500 with error message: pq: duplicate key value violates unique constraint "UQE_data_source_org_id_name"
**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.8
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @MingjieZhuEmily,

Thanks for opening this issue. I also get the same response in the logs:

`logger=context userId=1 orgId=1 uname=admin t=2023-03-30T12:46:56.130991806+02:00 level=error msg="Failed to update datasource" error="UNIQUE constraint failed: data_source.org_id, data_source.name" remote_addr=192.168.122.1 traceID=
`
I will forward this one to our Engineers to get more feedback from them if they have already planned an improvement in the next release or is already on the roadmap.
