### ISSUE TITLE
"Toggle legend" hotkey on Graph (old) doesn't work

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#65501]
**What happened**:
`p l` hotkey for legend toggle no longer works on Graph (old) component

**What you expected to happen**:
`p l` should toggle legend

**How to reproduce it (as minimally and precisely as possible)**:
1. go to https://play.grafana.org/d/RsNPTx2nz/promql
2. hover over panel and hit `p l`

**Anything else we need to know?**:
  * legend toggle by context menu works
  * other hotkeys like `p r` work
  * `p l` works on new Time series component

**Environment**:
- Grafana version:  v9.4.7

**Comment by usmangt** [comment]
:Hi @belm0,

Thanks for opening this issue :+1: 

Yes, I can also see that `p l` does work on other panels e.g. Time Series which turn on and off the legends but does not work with Graph (old).

I will forward this one to our Engineering team.

**Comment by JoaoSilvaGrafana** [comment]
Hi @belm0 thank you for raising this. Even though we understand this is a bug, we are no longer supporting changes to the Graph (old) panel. We strongly encourage you to migrate to the time series panel if you can where this functionality works. Do let us know if you have any issues trying to migrate 👍
