### ISSUE TITLE
alerting outside range to somehow allow MIN for lower range & MAX for upper range

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6550]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request

Please include this information:
- What Grafana version are you using? 4beta

I know you plan to enhance the queries for alerting but woud like some way instead of using AVG or a single ABOVE with a MAX to allow the OUTSIDE Range to use both MAX/MIN valves in the query

**Comment by torkelo** [comment]
This will not be possible I am afraid as the aggregation/reducer function can only return a single value.

**Comment by torkelo** [comment]
you can put two query conditions, one use min aggregator and the other user max

**Comment by roscoe57** [comment]
not tried as I may have misunderstood the AND for the second condition

is it really an OR ?

**Comment by roscoe57** [comment]
hmm tried it you can do the alert for equivaent of WITHIN RANGE
cant figure how to do an OUTSIDE range

Also with multiple conditions only the 1st is displayed as a graphical
threshold bar
