### ISSUE TITLE
NestedFolders: Move checkbox outside of SearchItem card

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#65514]
Checkbox for SearchItem cards in the Folder view of Browse Dashboards is inside of the clickable card, which is very frustrating because I often misclick and I'm navigated to the Dashboard instead, and I lose all my selections

![image](https://user-images.githubusercontent.com/46142/228515282-c98546f3-6b26-4bdc-9f7f-9d6c4c621177.png)

The checkbox should not be inside a clickable target. It should be moved outside of the card, to be _something_ like this (I'll leave actual implementation/design for whoever picks this up)

![image](https://user-images.githubusercontent.com/46142/228515920-93d940e2-1caf-42ca-bf30-826d968c84cb.png)

**Comment by tskarhed** [comment]
Idea: instead of moving the checkbox outside of the card, could we expand the checkbox area to cover the entire height of the card and width as a square?

**Comment by amy-super** [comment]
I think the problem with this approach is that the rest of the card will still be clickable with a different behavior - and so as a user it will be tricky to know where "click to select checkbox" starts and ends since the area will be invisible. Unless you're thinking some kind of hover decoration?

**Comment by tskarhed** [comment]
@amy-super Fair enough! Any thoughts on Josh's initial suggestion? I have a PR that basically implemets that

**Comment by radiorental** [comment]
I wonder if a little visual trickery might work here.  The 'expanded hitbox' idea with better visual affordance as to this hitbox... 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/3299847/228569804-3ff58c57-5584-44b3-b8e7-1740ac59d40a.png">

**Comment by staton-hyse11** [comment]
I agree with @radiorental: expanding that click target for checkboxes would be good and the visual change he proposes solves the "where do I click?" question.  It visualizes the start and end of the corresponding target spaces.

**Comment by amy-super** [comment]
For what it's worth, this will be a bit of a temporary state for dashboards until we shift to the nested tree or flat list structure for dashboard lists. So I think either the initial proposal or @radiorental's idea will work here. Are there other places where we do a card + checkbox? We'll want to make sure the direction we pick works there as well.
