### ISSUE TITLE
Alerting Query to allow multiple level triggering

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6551]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- What Grafana version are you using? 4beta

Would like ability somehow to have multi step level triggers, a simple example would be
Temperature 
 < 8 ... warning
 < 3 ... prepare
 < 0 ... really do something

**Comment by torkelo** [comment]
We are trying to keep the alerting system on the simple side when it comes to severity & different states. We originally had Critical & Warning thresholds, then moved that to a severity option per alert rule (so only one severity level per alert), we then removed that option completely.

To discuss feature requests like this I opened an issue for that
https://github.com/grafana/grafana/issues/6553
