### ISSUE TITLE
Alerting: Rule Category / Tags?

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6552]
### Alert Rule Categorization

Right now there is no way to organize a large set of alert rules and the annotations (i.e. state change history) they create. The only thing that approaches categorization is notifications, where each alert can have it's own set of notifications. But these are not handled as proper categorization properties as there is no way to filter/group by notifications, nor is this something included in the alert annotation (state change event). This seems like it can quickly become a problem for even medium sized Grafana installs where more than one team is using the Alert feature. 

Possible solutions:
1) Use notification groups but index them and include it as a filterable property, and include it in alert annotations
2) Use dashboard tags
3) Use new concept alert tags that are set on each alert rule (like dashboard tags). 
4) Introduce new concept `Alert Category` that can work like a single tag. But we can here allow users to create these alert categories, specify options for each (color, defaults, message template, default notifications). 

Of all these solutions `Alert category` is probably a lot easier/less complex to implement compared against using tags. Tags requires a many to many lookup table between alert and alert category as well as for the tables annotation and annotation category. Searching and filtering tables with many to many relations in SQL is a PITA.

**Comment by ddhirajkumar** [comment]
@torkelo Is this something that you are going to work on in the next release? On that note, is there a published roadmap for Grafana?
Following is the reason I am asking the above question:
We are looking for a feature 'ability to set tags for alerts' similar to the 'tags on dashboards'. Wanted to know the timelines, so that if it's not something that is being worked on, we could start working on this sub-feature (with your collaboration) and then submit a PR for this.

**Comment by torkelo** [comment]
Will add a roadmap soon, but to answer your first question, I do not think this is something we will have time to do in the next 2-3 months

**Comment by ddhirajkumar** [comment]
@torkelo Thanks for the heads-up

**Comment by mstaalesen** [comment]
@torkelo "Tags for Alerts", is that the field tags in the webhook documentation? http://docs.grafana.org/alerting/notifications/

"evalMatches": [
    {
      "metric": "requests",
      "tags": {},
      "value": 122
    }
  ]

**Comment by torkelo** [comment]
No that is for metric  queries that return tags

**Comment by mstaalesen** [comment]
Oh, ok. And that is not the same as a label in prometheus, correct?

**Comment by torkelo** [comment]
it is , but not sure the Prometheus time series backend supports returning labels & label values yet.

**Comment by alimousazy** [comment]
I'm trying to add tags for alerts, Please see the below screen shot, I'm done with Frontend works, please  let me know if there are any feedbacks [here](https://ibb.co/hrBROv)

**Comment by lucklucif** [comment]
@torkelo : so which solutions will you choose ? 
I will try to do a pull request about that

**Comment by torkelo** [comment]
Tags would be best

**Comment by bascarsija** [comment]
@lucklucif/@alimousazy: have either of you had an opportunity to consider this feature further or make any progress?

**Comment by Eraac** [comment]
@torkelo any plans to improve alert list panel as describe in #7764 with the 7.1?

**Comment by armandgrillet** [comment]
Grafana Alerting support labels and that can be used when searching an alert rule.
![SS 2024-01-25 at 17 17 10](https://github.com/grafana/grafana/assets/2117580/f3603709-0f5b-4511-b9dc-db8183db4562)
