### ISSUE TITLE
Cloudwatch Partially working in 4.0-beta

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#6554]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0-beta

- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
CentOS 6.6
- What did you do?
I have dashboard that displays AWS Billing information. It stopped working after the upgrade from 3.1 to 4.0-beta.
- What was the expected result?
- What happened instead?
I get this error in the log:

`t=2016-11-11T13:13:43-0600 lvl=eror msg="Unable to call AWS API" logger=context userId=7 orgId=1 uname=xxxxxx error="InvalidParameterCombination: You have requested up to 43,260 datapoints, which exceeds the limit of 1,440. You may reduce the datapoints requested by increasing Period, or decreasing the time range.\n\tstatus code: 400, request id: f67ddc06-a842-11e6-89c6-9f165c46f54b"`

I have second instance of grafana 3.1 and dashboard works just fine with exactly same configs.

**Comment by torkelo** [comment]
This is fixed in latest nightly build, and will be in beta2
