### ISSUE TITLE
Cannot edit prometheus queries in any chromium browser

### ISSUE THREAD

**Issue by PrestonTaylor** [grafana/grafana#65565]
**What happened**: Any time I add a character to the prometheus plugin query field in any way EXCEPT copy paste my cursor is immediately moved to the end of the query and ufeff BOM characters have been added to the query such that it can no longer execute. I must edit the query externally then copy paste in order for it to work.

I have tested this in latest Chrome, Brave, Edge, fresh installs with incognito and no extensions and all have same issue, Firefox Does not have the issue.

This error shows up in console after inserting a single character anywhere in the query and clicking away so that it refreshes.
"\"error when executing query=\\\"sum by\\\\ufeff(\\\\ufeffinstance\\\\ufeff,\\\\ufefftmnxNa...

Screen record: https://imgur.com/rXkyzCT
**What you expected to happen**: cursor doesn't move unexpectedly, unnecessary special characters not added.

**How to reproduce it (as minimally and precisely as possible)**: use chromium 

**Anything else we need to know?**:  #29850

**Environment**:
- Grafana version: 8.2.7
- Data source type & version:  Victoria Metrics latest stable
- OS Grafana is installed on: Centos 8
- User OS & Browser: Windows 10, Chromium
- Grafana plugins: Prometheus
- Others:

**Comment by usmangt** [comment]
Hi @PrestonTaylor,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine. I have tested this on play.grafana.com which is using Grafana version 9.4.7 and there it seems to work fine.

Therefore, the recommended solution would be to update to the latest stable version.
