### ISSUE TITLE
Alerting is in Pending State if dashboard is saved with raw minimized

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#6556]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0-beta1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.6
- What did you do?
Setup alert on a dashboard that uses a lot of minimized raws. Looks like this prevents alerts from being generated and alert is displayed as Pending (if I create alert on a graph panel minimize raw and then save dashboard)...

**Comment by AGirin** [comment]
User error. Closing.

**Comment by cdalexndr** [comment]
@achilles42 Check the [for](https://grafana.com/docs/alerting/rules/#for) setting for the alert. It needs to be invalid for the configured **for** interval until an alert is send.
