### ISSUE TITLE
Build failing on Ubuntu 14.04 LTS server (32 bit)

### ISSUE THREAD

**Issue by theopensourcerer** [grafana/grafana#6559]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  Pulling from github source
- What datasource are you using?
  n/a
- What OS are you running grafana on?
  Ubuntu 14.04 server LTS (32bit)
- What did you do?
  Followed the build instructions
- What was the expected result?
  A built Grafana :-)
- What happened instead?
  The Build crashed

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

I have tried this twice with the same result:
alord@vimes:~/grafana$ go get github.com/grafana/grafana
package github.com/grafana/grafana
	imports github.com/grafana/grafana
	imports github.com/grafana/grafana: no buildable Go source files in /home/alord/grafana/src/github.com/grafana/grafana
alord@vimes:~/grafana$ cd $GOPATH/src/github.com/grafana/grafana
alord@vimes:~/grafana/src/github.com/grafana/grafana$ go run build.go setup
Version: 4.0.0-beta1, Linux Version: 4.0.0, Package Iteration: 1479068392beta1
go get -v github.com/kardianos/govendor
github.com/kardianos/govendor (download)
github.com/Bowery/prompt (download)
github.com/dchest/safefile (download)
github.com/google/shlex (download)
github.com/pkg/errors (download)
Fetching https://golang.org/x/tools/go/vcs?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/vcs?go-get=1 (status code 200)
get "golang.org/x/tools/go/vcs": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/vcs?go-get=1
get "golang.org/x/tools/go/vcs": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
github.com/Bowery/prompt
github.com/kardianos/govendor/prompt
github.com/kardianos/govendor/cliprompt
github.com/dchest/safefile
github.com/kardianos/govendor/internal/pathos
github.com/kardianos/govendor/internal/vos
github.com/kardianos/govendor/internal/vfilepath
github.com/kardianos/govendor/pkgspec
github.com/kardianos/govendor/vcs
github.com/kardianos/govendor/vendorfile
github.com/pkg/errors
golang.org/x/tools/go/vcs
github.com/kardianos/govendor/context
github.com/kardianos/govendor/migrate
github.com/kardianos/govendor/help
github.com/google/shlex
github.com/kardianos/govendor/run
github.com/kardianos/govendor
go install -v ./pkg/cmd/grafana-server
pkg/cmd/grafana-server/server.go:4:2: cannot find package "context" in any of:
	/usr/src/pkg/context (from $GOROOT)
	/home/alord/grafana/src/context (from $GOPATH)
pkg/login/settings.go:7:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/src/pkg/github.com/BurntSushi/toml (from $GOROOT)
	/home/alord/grafana/src/github.com/BurntSushi/toml (from $GOPATH)
pkg/services/notifications/codes.go:9:2: cannot find package "github.com/Unknwon/com" in any of:
	/usr/src/pkg/github.com/Unknwon/com (from $GOROOT)
	/home/alord/grafana/src/github.com/Unknwon/com (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:11:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:12:2: cannot find package "github.com/aws/aws-sdk-go/aws/awsutil" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws/awsutil (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws/awsutil (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:13:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws/credentials (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:14:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:15:2: cannot find package "github.com/aws/aws-sdk-go/aws/ec2metadata" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:16:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/aws/session (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/aws/session (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:17:2: cannot find package "github.com/aws/aws-sdk-go/service/cloudwatch" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/service/cloudwatch (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/service/cloudwatch (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:18:2: cannot find package "github.com/aws/aws-sdk-go/service/ec2" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/service/ec2 (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/service/ec2 (from $GOPATH)
pkg/api/cloudwatch/cloudwatch.go:19:2: cannot find package "github.com/aws/aws-sdk-go/service/sts" in any of:
	/usr/src/pkg/github.com/aws/aws-sdk-go/service/sts (from $GOROOT)
	/home/alord/grafana/src/github.com/aws/aws-sdk-go/service/sts (from $GOPATH)
pkg/services/alerting/engine.go:7:2: cannot find package "github.com/benbjohnson/clock" in any of:
	/usr/src/pkg/github.com/benbjohnson/clock (from $GOROOT)
	/home/alord/grafana/src/github.com/benbjohnson/clock (from $GOPATH)
pkg/login/ldap.go:11:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
	/usr/src/pkg/github.com/davecgh/go-spew/spew (from $GOROOT)
	/home/alord/grafana/src/github.com/davecgh/go-spew/spew (from $GOPATH)
pkg/login/ldap.go:12:2: cannot find package "github.com/go-ldap/ldap" in any of:
	/usr/src/pkg/github.com/go-ldap/ldap (from $GOROOT)
	/home/alord/grafana/src/github.com/go-ldap/ldap (from $GOPATH)
pkg/api/api.go:4:2: cannot find package "github.com/go-macaron/binding" in any of:
	/usr/src/pkg/github.com/go-macaron/binding (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/binding (from $GOPATH)
pkg/middleware/util.go:6:2: cannot find package "github.com/go-macaron/gzip" in any of:
	/usr/src/pkg/github.com/go-macaron/gzip (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/gzip (from $GOPATH)
pkg/middleware/recovery.go:27:2: cannot find package "github.com/go-macaron/inject" in any of:
	/usr/src/pkg/github.com/go-macaron/inject (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/inject (from $GOPATH)
pkg/setting/setting.go:17:2: cannot find package "github.com/go-macaron/session" in any of:
	/usr/src/pkg/github.com/go-macaron/session (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/session (from $GOPATH)
pkg/middleware/session.go:7:2: cannot find package "github.com/go-macaron/session/memcache" in any of:
	/usr/src/pkg/github.com/go-macaron/session/memcache (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/session/memcache (from $GOPATH)
pkg/middleware/session.go:8:2: cannot find package "github.com/go-macaron/session/mysql" in any of:
	/usr/src/pkg/github.com/go-macaron/session/mysql (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/session/mysql (from $GOPATH)
pkg/middleware/session.go:9:2: cannot find package "github.com/go-macaron/session/postgres" in any of:
	/usr/src/pkg/github.com/go-macaron/session/postgres (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/session/postgres (from $GOPATH)
pkg/middleware/session.go:10:2: cannot find package "github.com/go-macaron/session/redis" in any of:
	/usr/src/pkg/github.com/go-macaron/session/redis (from $GOROOT)
	/home/alord/grafana/src/github.com/go-macaron/session/redis (from $GOPATH)
pkg/services/sqlstore/sqlstore.go:19:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/src/pkg/github.com/go-sql-driver/mysql (from $GOROOT)
	/home/alord/grafana/src/github.com/go-sql-driver/mysql (from $GOPATH)
pkg/log/log.go:15:2: cannot find package "github.com/go-stack/stack" in any of:
	/usr/src/pkg/github.com/go-stack/stack (from $GOROOT)
	/home/alord/grafana/src/github.com/go-stack/stack (from $GOPATH)
pkg/services/sqlstore/alert.go:8:2: cannot find package "github.com/go-xorm/xorm" in any of:
	/usr/src/pkg/github.com/go-xorm/xorm (from $GOROOT)
	/home/alord/grafana/src/github.com/go-xorm/xorm (from $GOPATH)
pkg/api/live/conn.go:7:2: cannot find package "github.com/gorilla/websocket" in any of:
	/usr/src/pkg/github.com/gorilla/websocket (from $GOROOT)
	/home/alord/grafana/src/github.com/gorilla/websocket (from $GOPATH)
pkg/models/dashboards.go:8:2: cannot find package "github.com/gosimple/slug" in any of:
	/usr/src/pkg/github.com/gosimple/slug (from $GOROOT)
	/home/alord/grafana/src/github.com/gosimple/slug (from $GOPATH)
pkg/plugins/update_checker.go:12:2: cannot find package "github.com/hashicorp/go-version" in any of:
	/usr/src/pkg/github.com/hashicorp/go-version (from $GOROOT)
	/home/alord/grafana/src/github.com/hashicorp/go-version (from $GOPATH)
pkg/log/file.go:17:2: cannot find package "github.com/inconshreveable/log15" in any of:
	/usr/src/pkg/github.com/inconshreveable/log15 (from $GOROOT)
	/home/alord/grafana/src/github.com/inconshreveable/log15 (from $GOPATH)
pkg/log/log.go:17:2: cannot find package "github.com/inconshreveable/log15/term" in any of:
	/usr/src/pkg/github.com/inconshreveable/log15/term (from $GOROOT)
	/home/alord/grafana/src/github.com/inconshreveable/log15/term (from $GOPATH)
pkg/components/imguploader/s3uploader.go:11:2: cannot find package "github.com/kr/s3/s3util" in any of:
	/usr/src/pkg/github.com/kr/s3/s3util (from $GOROOT)
	/home/alord/grafana/src/github.com/kr/s3/s3util (from $GOPATH)
pkg/services/sqlstore/migrator/migrator.go:9:2: cannot find package "github.com/lib/pq" in any of:
	/usr/src/pkg/github.com/lib/pq (from $GOROOT)
	/home/alord/grafana/src/github.com/lib/pq (from $GOPATH)
pkg/services/sqlstore/migrator/migrator.go:10:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
	/usr/src/pkg/github.com/mattn/go-sqlite3 (from $GOROOT)
	/home/alord/grafana/src/github.com/mattn/go-sqlite3 (from $GOPATH)
pkg/tsdb/prometheus/prometheus.go:14:2: cannot find package "github.com/prometheus/client_golang/api/prometheus" in any of:
	/usr/src/pkg/github.com/prometheus/client_golang/api/prometheus (from $GOROOT)
	/home/alord/grafana/src/github.com/prometheus/client_golang/api/prometheus (from $GOPATH)
pkg/tsdb/prometheus/prometheus.go:15:2: cannot find package "github.com/prometheus/common/model" in any of:
	/usr/src/pkg/github.com/prometheus/common/model (from $GOROOT)
	/home/alord/grafana/src/github.com/prometheus/common/model (from $GOPATH)
pkg/services/eventpublisher/eventpublisher.go:12:2: cannot find package "github.com/streadway/amqp" in any of:
	/usr/src/pkg/github.com/streadway/amqp (from $GOROOT)
	/home/alord/grafana/src/github.com/streadway/amqp (from $GOPATH)
pkg/social/social.go:7:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/src/pkg/golang.org/x/net/context (from $GOROOT)
	/home/alord/grafana/src/golang.org/x/net/context (from $GOPATH)
pkg/services/notifications/webhook.go:11:2: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
	/usr/src/pkg/golang.org/x/net/context/ctxhttp (from $GOROOT)
	/home/alord/grafana/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
pkg/social/generic_oauth.go:11:2: cannot find package "golang.org/x/oauth2" in any of:
	/usr/src/pkg/golang.org/x/oauth2 (from $GOROOT)
	/home/alord/grafana/src/golang.org/x/oauth2 (from $GOPATH)
pkg/services/alerting/engine.go:9:2: cannot find package "golang.org/x/sync/errgroup" in any of:
	/usr/src/pkg/golang.org/x/sync/errgroup (from $GOROOT)
	/home/alord/grafana/src/golang.org/x/sync/errgroup (from $GOPATH)
pkg/services/notifications/mailer.go:20:2: cannot find package "gopkg.in/gomail.v2" in any of:
	/usr/src/pkg/gopkg.in/gomail.v2 (from $GOROOT)
	/home/alord/grafana/src/gopkg.in/gomail.v2 (from $GOPATH)
pkg/tsdb/models.go:5:2: cannot find package "gopkg.in/guregu/null.v3" in any of:
	/usr/src/pkg/gopkg.in/guregu/null.v3 (from $GOROOT)
	/home/alord/grafana/src/gopkg.in/guregu/null.v3 (from $GOPATH)
pkg/log/log.go:13:2: cannot find package "gopkg.in/ini.v1" in any of:
	/usr/src/pkg/gopkg.in/ini.v1 (from $GOROOT)
	/home/alord/grafana/src/gopkg.in/ini.v1 (from $GOPATH)
pkg/middleware/auth.go:7:2: cannot find package "gopkg.in/macaron.v1" in any of:
	/usr/src/pkg/gopkg.in/macaron.v1 (from $GOROOT)
	/home/alord/grafana/src/gopkg.in/macaron.v1 (from $GOPATH)
exit status 1
exit status 1

**Comment by torkelo** [comment]
You need go 1.7
