### ISSUE TITLE
Explore content outline: Help users navigate Explore content

### ISSUE THREAD

**Issue by thanos-karachalios** [grafana/grafana#65594]
One of the most common use cases of Explore is troubleshooting. Usually troubleshooting workflows involve multiple queries of both metrics, logs and traces that result to an extended content that it is time consuming to navigate. Under this observation, we aim to help users navigate their Explore content more efficiently and help them achieve their task faster.

[Product DNA](https://docs.google.com/document/d/1ysz2dlIIRfrh4IzmudqEOGmhEuBqpuOYlMemc08aZRo/edit#heading=h.cqjpvn7kzt88)

This volume of work should be approached as an easy to design and implement

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/65598
- [x] Design review
- [ ] https://github.com/grafana/grafana/issues/66753
```

**Comment by diegoadams** [comment]
Here is the updated prototype. This should be good to test with some internal users. Let me know if you have any feedback.:slightly_smiling_face:
The split-view interactions took a while to configure:kirby-type: I will turn off the highlight cues when user testing.
[Normal View (1366px)](https://www.figma.com/proto/ORGdyXLOajGxrkVE5DZw3j/Content-Outline?node-id=215-20920&scaling=min-zoom&page-id=31%3A809&starting-point-node-id=215%3A20920)
[Split View (1366px)](https://www.figma.com/proto/ORGdyXLOajGxrkVE5DZw3j/Content-Outline?node-id=205-33168&scaling=min-zoom&page-id=31%3A809&starting-point-node-id=205%3A33168)
[4:44](https://raintank-corp.slack.com/archives/C0511G9LU8N/p1681742695852989)

**Comment by diegoadams** [comment]
I have also started assembling a [User Testing Doc](https://docs.google.com/document/d/1gMliX3hHRm54QunIrlwq1ra_SoIZx9_IkkcmRL1uvb4/edit#). I will tag you on some questions I may still have.

**Comment by Elfo404** [comment]
in the context of this iteraation, @diegoadams to prepare dev handover and close this issue

**Comment by diegoadams** [comment]
I have completed the designs and created a UX->DEV handover doc to help whoever picks this up.

Please find the
[Handover Doc](https://docs.google.com/document/d/1bf4Ho567Jrfyl6y3bIErzZvnwT-Ul7FNXYNPM0bz1I4/edit#)
[Figma File](https://www.figma.com/file/ORGdyXLOajGxrkVE5DZw3j/Content-Outline?type=design&node-id=601-34292&t=vlMQilyKJz1PrwK8-0)
[Prototype](https://www.figma.com/proto/ORGdyXLOajGxrkVE5DZw3j/Content-Outline?type=design&node-id=658-37830&scaling=scale-down&page-id=601%3A34292&starting-point-node-id=658%3A37830&show-proto-sidebar=1)

**Comment by gelicia** [comment]
This seems comprehensive to me! There's only one detail, which is how this sidenav should behave with the existing global sidenav but I also think it's worth letting that get specified in development so if the navigation changes between now and then, the details aren't confusing.

**Comment by diegoadams** [comment]
Thanks @gelicia , the global side nav shouldn't affect anything as it would simply overlay the user's view even if the Content Outline is active.  I have updated the [prototype](https://github.com/grafana/grafana/issues/65594#:~:text=Video%0AFigma%20File-,Prototype,-%E2%9D%A4%EF%B8%8F) to reflect this, just simply hover over the menu to see what it would look like.

Here is also a video to show

https://github.com/grafana/grafana/assets/95694434/73c55ea4-ce2b-4b4a-9f46-4fce0069a894
