### ISSUE TITLE
Grafana 4.0.0-beta1 - Alerting Bug: Multiple series in InfluxDB regex query not firing alert

### ISSUE THREAD

**Issue by berglh** [grafana/grafana#6560]
- [x ] Bug report

- What Grafana version are you using?
 Grafana v4.0.0-beta1 (commit: a87fd11) Docker Container
- What datasource are you using?
InfluxDB v0.13.0
- What OS are you running grafana on?
Oracle Enterprise Linux
- What did you do?
Created an alert to fire when max value 3m time frame exceeds value of 3000 for a regex query that returns multiple InfluxDB series, any series exceeding 3000 should trigger the alert.
- What was the expected result?
Any series should trigger the alert, as per @torkelo 's description of the alerting feature.
- What happened instead?
When I have the query for only one series selected, the alert fires as expected on dashboard save.
![going-red-with-single-series](https://cloud.githubusercontent.com/assets/12455338/20250125/56c147e0-aa55-11e6-9237-8579836efafb.png)

However, when I change the query to regex and return values from five series, the alert then turns green, even though multiple series have exceeded the threshold.
![going-green-with-multiple-series](https://cloud.githubusercontent.com/assets/12455338/20250135/af1f5634-aa55-11e6-9f8c-371c9f85368a.png)

The test result matches false condition; even though obviously multiple series exceed. Even if there is one, or all series exceeding the threshold, it still does not return a true state unless I remove the regex query and only supply one series in the InfluxDB query. 
![alert-result-multiple-series](https://cloud.githubusercontent.com/assets/12455338/20250191/f854abd2-aa56-11e6-9c54-6456e49ccb02.png)

I'm speculating this has something to do specifically with the InfluxDB data source, as I haven't seen any other complaints regarding this so far. Getting closer to useful alerts though :+1:

**Comment by bergquist** [comment]
Will be available for download shortly on grafana.org/builds

**Comment by berglh** [comment]
@bergquist thank you - working as intended on Grafana v4.0.0-beta1 (commit: 6e94cce)
