### ISSUE TITLE
Provisionined influx InfluxQL datasource missing database field

### ISSUE THREAD

**Issue by ecksun** [grafana/grafana#65603]
**What happened**:

Provisioning an influx v2 InfluxQL datasource does not include the `database` field even though it is included in the yaml.

This issue seems to have been introduced in grafana 9.4.0

**What you expected to happen**:

Provisioning an influx datasource works when the yaml is correct, specifically that the database field from the datasource yaml should be included in the UI.

**How to reproduce it (as minimally and precisely as possible)**:

I use the example from [datasources/influxdb Provisioning examples](https://grafana.com/docs/grafana/latest/datasources/influxdb/#provisioning-examples) to reduce the likelihood I incorrectly configured the datasource:

```bash
#!/bin/bash

mkdir -p provisioning/datasources
cat > provisioning/datasources/datasources.yaml <<EOF
apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://localhost:8086
    # This database should be mapped to a bucket
    database: site
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token <token>'
EOF

docker run -p 3000:3000 --volume "$PWD/provisioning:/etc/grafana/provisioning" grafana/grafana-oss:9.4.7-ubuntu
```

Navigate to http://localhost:3000/datasources and edit the dashboard, notice how the `database` field is not populated:

![missing-database](https://user-images.githubusercontent.com/135807/228807450-06a6f6a2-0258-46df-b00f-56b6a0f581c0.png)

With an influx database configured correctly you get the following error when trying to test it:

> database name required error reading influxDB

![missing-database-error](https://user-images.githubusercontent.com/135807/228807874-362de6c3-c590-4ddb-bc58-0fae7d128580.png)

**Anything else we need to know?**:

The issue seems to be somewhat intermittent, as in I have been able to start grafana and have it work as expected. That is rare though.

Reproducable in both our kubernetes setup and for me locally using podman as in the reproduction above

Working versions:
- 8.2.3-ubuntu
- 9.0.0-ubuntu
- 9.2.0-ubuntu
- 9.3.0-ubuntu
- 9.3.11-ubuntu

Broken versions:
- 9.4.0-ubuntu
- 9.4.7-ubuntu

**Comment by 0x0agon** [comment]
I'm seeing the same issue described above.

**Comment by 0x0agon** [comment]
I'm seeing the same issue as described above.

**Comment by nat45928** [comment]
I believe this is related. https://github.com/grafana/grafana/pull/62308

**Comment by itsmylife** [comment]
Related issue: https://github.com/grafana/grafana/issues/64795
Solution: https://github.com/grafana/grafana/pull/62790

This was a known issue and it wasn't backported to `v9.4.x`. Backporting is done here https://github.com/grafana/grafana/pull/65037

The next version of `v9.4.x` and `v9.5.x` will have it.

cc: @zoltanbedi 


I am closing this issue since we have a solution.
