### ISSUE TITLE
Cannot choose data option for Geomap layers

### ISSUE THREAD

**Issue by yugako** [grafana/grafana#65615]
Hello everyone!

**What happened**:

I am using a built-in Geomap plugin and trying to use different layers to visualize data from a few queries.
But, the problem is that I cannot choose the right data option. 

![image](https://user-images.githubusercontent.com/27961118/228848866-06275a23-3432-4d61-81cc-4f314ba96fc1.png)

I believe it's related to the `undefined` properties in the dropdown list. And after some research, I came to the conclusion that it's related to the unset query name. But, here is another problem I cannot set it either.

![image](https://user-images.githubusercontent.com/27961118/228849984-0aac03e8-fdeb-4718-a52a-fec9acab75dc.png)

**What you expected to happen**:

I can set the query name and choose a data option for different map layers without any problems.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Cognite Data Fusion Plugin
2. Create a new data source with public data
3. Get any geospatial data and try to duplicate the query.
4. Try to choose different data for different layers.

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: Cognite Data Fusion
- User OS & Browser: macOS Ventura 13.2.1 
- Grafana plugins: Cognite Data Fusion plugin, built-in Geomap panel

**Others**
Here is a link to [related](https://community.grafana.com/t/how-to-set-query-name/82276) unresolved issue

**Comment by zuchka** [comment]
is this issue reproducible without using that third party datasource? https://grafana.com/grafana/plugins/cognitedata-datasource/?

**Comment by yugako** [comment]
> is this issue reproducible without using that third party datasource? https://grafana.com/grafana/plugins/cognitedata-datasource/?

I tried with the different data sources, issue still remained

**Comment by dincho** [comment]
I can confirm the same issue with Prometheus data source. Changing the default query names (A/B) to something else has no effect.
