### ISSUE TITLE
Hide (top row) Template Variables & Annotation Select

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6562]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v4 beta
- What datasource are you using? infuxdb

Is there any way (apart from deleting them ! eck) that you can request the top banner showing any template variables & annotations from being displayed ?

Can't seem to see anything

**Comment by torkelo** [comment]
you can hide template variables on an individual basis (option on template variable edit view). Annotations do not have that option.

**Comment by patoroco** [comment]
It sound a little bit hacky, but we're using grafana on a TV, so we going to add this line to https://github.com/grafana/grafana/blob/master/public/views/index.html:

```php
$('.submenu-controls').hide();$('.navbar').hide()
```

**Comment by daniellee** [comment]
@patoroco Kiosk mode already hides the navbar - so that part is unnecessary. Press  `d` then `k` to switch to kiosk mode.

http://docs.grafana.org/guides/whats-new-in-v4/#tv-mode-kiosk-mode

**Comment by roscoe57** [comment]
@daniellee (I know you were responding to other comments but )
it is NOT the top-top nav banner, I was referring to, but the 2nd down containing any template variables & annotations from being displayed

**Comment by patoroco** [comment]
@daniellee as @roscoe57 pointed, I'm meaning to anotations line, which is showed also in kiosk mode. 
In our case, we're using a LG TV, and keyboard is only valid to input URLs, so kiosk mode neither is possible here :(

**Comment by daniellee** [comment]
@patoroco yeah, I was just pointing out that half of your change was not needed if you used kiosk mode (`$('.navbar').hide()` does what kiosk mode does).

I was thinking that we would add a Keyboard Shortcut to hide the submenu. But that would not work for you then?

**Comment by patoroco** [comment]
Yep, in our TV we aren't able to use hotkeys, so I think that a solution would be to have a menu-button for that or also a config at dashboard-level which enable / disable this kiosk mode (hiding two bars: menu and anotations).

What do you think about that approach @daniellee ?

**Comment by daniellee** [comment]
@patoroco if this option was in the dashboard settings then it would lock the dashboard to kiosk mode. This means that the dashboard settings would not be available/hard to find so I think a menu button would be a better alternative. I'll have to consult our UX guy - we are trying to limit the number of options in the UI.

**Comment by torkelo** [comment]
@daniellee this FR is not about navbar but submenu (template variable dropdowns, annotations, dashboard links)

**Comment by daniellee** [comment]
@torkelo I seem to be writing unclearly as I now have 3 people telling me that this FR is about the submenu :-) 

Anyway, back to the point. If we are going to implement a "hide submenu" function, then I presume the first step would be implement it as a hot key. The same way we currently do for the kiosk mode.

But (and this is where kiosk mode comes in) it is difficult to switch to to another mode (kiosk mode or "hide submenu" mode) on a TV without a keyboard. Implementing it as a dashboard setting would also introduce some UX strangeness. A button for kiosk mode and a button for "hide submenu" mode might be an option but that would increase the number of options in the dashboard UI.

**Comment by patoroco** [comment]
@daniellee a button should be enough to me! 👍 

I think that a compromise solution could be to allow to fetch this config from a GET param in the URL, something like http://yourgrafana.com/dashboard/dashboard1?hide_annotations=true or something else, this should be (easily) possible?

**Comment by daniellee** [comment]
@patoroco yeah, a querystring parameter is a good idea.

**Comment by patoroco** [comment]
How can I help @daniellee ?

**Comment by daniellee** [comment]
@patoroco if you have the time, a PR with this feature as a query string and as a shortcut key would be great!
