### ISSUE TITLE
sticky/fix banner & selectable row

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6563]
* **I'm submitting a ...**
- [ ] Bug report
- [ X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v4beta

I presume this has mentioned already.  Looking for feature to make the TOP Banner 
AND I have a Row of SINGLESTATs

would be great if Row Settings had an option to define them as sticky to act like a header that stays on screen at the top even when you scroll down ?

**Comment by torkelo** [comment]
yes, sticky header has already been requests (there is an issue for that)

**Comment by roscoe57** [comment]
still can't find it ?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/4670
