### ISSUE TITLE
Provide better label auto-complete in the Phlare explore view

### ISSUE THREAD

**Issue by simonswine** [grafana/grafana#65634]
**What is the improvement?**:

Currently when typing a label selector in the query window, it will always use all possible series available as suggestions (which it gets by querying `/series?matcher={}`)

As someone typing the query it would great if we could reduce the labels suggested (like the prometheus query window does).

An example:

* User starts explore and selects profile type:
  ![image](https://user-images.githubusercontent.com/223048/228891109-32bfa4f0-27d9-460d-bb82-ae37e12b8285.png)
* Now going to the label selector field we should only show the series that actually have this profile type. Can be queried using `/series?matcher={__profile_type__="process_cpu:cpu:nanoseconds:cpu:nanoseconds"}`
* Now the user types `{namespace="prod", pod=`, rather than show all pod name values, we should fire another request and gather values that already match `namespace="prod"` either by reusing the previous result or firing a new request to the series endpoint.

**Is there anything else we need to know?**:

This is how it works in Loki/Prometheus explore already (I think)

**Comment by aocenas** [comment]
@simonswine when changing the backend to support both pyroscope and phlare I changed this so we use LabelNames and LabelValues API, so we don't get all the possible series at once (which at some occasions was >30mb response) but for each label on demand. This means we cannot use the /series api with the matcher but would be nice if the LabelNames and LabelValues have such param which they don't it seems.
