### ISSUE TITLE
[Feat Req]: SingleStat & support for non time series data

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#6564]
I'm submitting a  Feature request

What Grafana version are you using?
v3.1.0

What datasource are you using?
ElasticSearch, Non-timeseries search index (ie. an actual search index for an application)

What OS are you running grafana on?
CentOS 7

What did you do? 
I want to show a SingleStat with the (Unique?) Count of the number of items in a certain index. I'm assuming that Grafana is expecting record with a timestamp. As this is a simple search index, this is not the case.
I currently show this SingleStat in a Kibana dashboard, see attached screenshot.

What was the expected result?
Show the (unique?) count of indexed records

An image or text representation of your metric query
![Unique metric](https://ibin.co/31wUgjfMrXjM.png)

**Comment by torkelo** [comment]
you can use unique count, just pick a very large date histogram interval (like 1y)

**Comment by Duologic** [comment]
Thanks for the quick response, I've tried it immediately but I didn't manage to get any data back.

How would that work if I don't have a 'Time field name'/@timestamp? 

![](https://ibin.co/31x09A5OxkqD.png)

**Comment by torkelo** [comment]
it would not I am afraid, you would need a timestamp field

**Comment by Duologic** [comment]
Then I'd like to re-open this feature request... :)

**Comment by FFalcon** [comment]
I'd like to get an update on the status of this request : For a similar use case, I have to show the unique count of a field. I tried using a very large GroupBy interval (1y) for 2 months data, but the result I get from using that is different from what I get from using a search query directly in ElasticSearch. I checked and the gte/lte timestamps correspond to the selected period. But elasticsearch still returns a wrong result to the grafana query.

Grafana query (gives count 1717):
`{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": "1480156322997",
                  "lte": "1482748322997",
                  "format": "epoch_millis"
                }
              }
            }
          ]
        }
      }
    }
  },
  "aggs": {
    "2": {
      "date_histogram": {
        "interval": "1y",
        "field": "@timestamp",
        "min_doc_count": 0,
        "extended_bounds": {
          "min": "1480156322997",
          "max": "1482748322997"
        },
        "format": "epoch_millis"
      },
      "aggs": {
        "2":{
          "cardinality": {
            "field": "FieldToCount"
          }
        }
      }
    }
  }
}`

ElasticSearch query (gives count 1837):
`{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "*",
          "analyze_wildcard": true
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": 1480156322997,
                  "lte": 1482748322997,
                  "format": "epoch_millis"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "aggs": {
    "1": {
      "cardinality": {
        "field": "FieldToCount"
      }
    }
  }
}`

Note that the I used the same timestamps for both requests.

**Comment by daniellee** [comment]
Closed by 8874be4c663a089a2e01998c7c9753731c459665 and a49ef90a1df3592d717cf7dd75b7902fecd77b9d and  6160978019e9a43843de062d3af0e36a9b6503d4
