### ISSUE TITLE
[Docs] The Grafana panel "Traces" is not documented and is hard to use

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/grafana#65645]
# Documentation Problem

The [Grafana "Traces" panel](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/traces/) is not much documented and it's hard to use, I fail to make it work.

I would like to understand in the docs:
* What is this panel is about? 
   * As it's the plural form "traces", it's probably about listing traces rather than displaying a single trace but as there is no "Trace" panel, singular, maybe this panel does both.
   * How can I make the query parameters editable. I guess through dashboard parameters
   * Screenshots would help me
* How can I use it

## Current documentation doesn't help much

> <img width="200" alt="image" src="https://user-images.githubusercontent.com/459691/228661489-4c27645b-c6de-49a9-a4e5-a4ee80c3c1cb.png">

## Traces doesn't work in my dashboard

> ![image](https://user-images.githubusercontent.com/459691/228662810-46540728-28df-440b-bea2-301b20829857.png)

**Comment by joey-grafana** [comment]
Closed in https://github.com/grafana/grafana/pull/70204
