### ISSUE TITLE
v4 Beta Bug: Stacking an null values 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6566]
Stacked series followed by a null period looks buggy due change in stacking logicl. 

![image](https://cloud.githubusercontent.com/assets/10999/20266880/5cf23642-aa78-11e6-88b9-000e2b07c9b1.png)

Will try to create a new test graph for this case in the Test Data App dashboard. 

@benrubson

**Comment by benrubson** [comment]
@torkelo how would have you liked this case to be represented ?

**Comment by torkelo** [comment]
I think if all series are null then nothing should be rendered
added a new graph to the test data dashboard. 

![image](https://cloud.githubusercontent.com/assets/10999/20359182/039f1106-ac2f-11e6-85ee-7169874cdc4d.png)

The first series gets a gap but the series above gets a connecting line even though all series have nulls in the same spots (all series have the same values)

**Comment by benrubson** [comment]
OK yes I agree, I'll find a better solution.

**Comment by benrubson** [comment]
Corrected by #6639 👍

**Comment by benrubson** [comment]
An example :

![screen](https://cloud.githubusercontent.com/assets/6764151/20454173/ba4fd40c-ae38-11e6-9231-3734adf047d0.png)
