### ISSUE TITLE
User-Invitation by E-Mail worked although only LDAP signups were allowed

### ISSUE THREAD

**Issue by PaulKlumpp** [grafana/grafana#6567]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
v3.1.1 (commit: a4d2708)
- What datasource are you using?
Elasticsearch/InfluxDB
- What OS are you running grafana on?
Linux
- What did you do?
I invited a User by an E-Mail-Address. Only LDAP signups are allowed and general user signup is disallowed.
- What was the expected result?
It would deny my Invite if I gave an E-Mail-Address. It would allow my Invite if I gave an LDAP-User. 
- What happened instead?
It created a new user with an E-Mail-Address as user name. That user can even login and was then part of that organization he was invited to.

**Comment by torkelo** [comment]
there is no way to disable invites right now. The option allow_sign_up only controls if users can self register, it does not control if an organization admin can invite new users or not.
