### ISSUE TITLE
URLs including page headings don't take you to the page heading

### ISSUE THREAD

**Issue by christineywang** [grafana/grafana#65671]
When I navigate through the **On this page** sidebar and click on the different sections, I am taken to the correct section (such as **Group by**. However, when I copy the URL hash/fragment and paste in a new browser, it does not take me to the right section. Example: `https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#join-by-field`

**Comment by GrafanaWriter** [comment]
@christineywang - I'm unable to replicate this issue using Chrome on MacOS. Can you please confirm the issue? If you are able to reproduce, please log the issue for the website team in the website repo.
