### ISSUE TITLE
View rule - Rule could not be found.

### ISSUE THREAD

**Issue by Roberto6969** [grafana/grafana#65677]
Hello.

I have some inaccessible rules, which still generates alarms.
![image](https://user-images.githubusercontent.com/21200507/229065874-984fb412-da28-4601-aa5a-23de36d1c752.png)

Rules are listed under Groups, but  "See source" button shows: 
![image](https://user-images.githubusercontent.com/21200507/229065957-1bfe63db-6605-48cf-a943-89840423e73d.png)

How can I view as well as delete those rules?

Thank You!

**Comment by tonypowa** [comment]
thank you for creating this issue @Roberto6969 

Let's check if there are any erros when clicking on See Source by increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level). For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

could also you try to use this [API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-get-alert-rule) to gather the JSON of those inaccessible alerts?

GET `/api/v1/provisioning/alert-rules/{UID}`

**Comment by Roberto6969** [comment]
@tonypowa thank you for your feedback. It is appreciated due to huge amount of false alarms, I had receiving all the time.

After carefully cleaning all orphan rules with API calls as you suggested, problem has gone. I have no more alerts, which couldn't display "See source".

The only numerous error still remains in log is:
msg="Rule declares one or many reserved labels. Those rules labels will be ignored" labels="alertname=Apparent_Power_alert"

Which labels are "reserved", anyway?

Thank You
Robert

**Comment by tonypowa** [comment]
@Roberto6969 
Thanks for the feedback !

>msg="Rule declares one or many reserved labels. Those rules labels will be ignored"  labels="alertname=Apparent_Power_alert"


it seems that is being discussed in this other issue:  
https://github.com/grafana/grafana/issues/55670#issuecomment-1488959960
I would advise to monitor that logging error from there

I am closing this issue. Feel free to reopen if needed.
