### ISSUE TITLE
Rendering values problem on timeseries panel

### ISSUE THREAD

**Issue by acappelletti** [grafana/grafana#65680]
**What happened**:
I got a dash with many panels from google sheet datasource. In one of this
![image](https://user-images.githubusercontent.com/43847440/229083061-3387c50b-59de-485c-a665-2693e601385b.png)
the mouse pointer never change the values of the graph.
The overlay always show the last one.

**What you expected to happen**:
I expected that as in all the other panels I have on the page the value changes for each point

**How to reproduce it (as minimally and precisely as possible)**:
Look my images... the end of the line...
![image](https://user-images.githubusercontent.com/43847440/229083675-9770bb92-c5c3-451c-bb26-08566c582b92.png)

now I point at the middle and beginning... same value and same date
![image](https://user-images.githubusercontent.com/43847440/229083975-eac39ad3-85c7-4116-a583-09143544cbe4.png)

**Anything else we need to know?**:
My dash has many panels and only in the two that I highlight do I have the problem
![image](https://user-images.githubusercontent.com/43847440/229084779-4764e0f3-4b30-4255-b983-98a6095949a2.png)

**Recording**:
![problem_panel](https://user-images.githubusercontent.com/43847440/229085421-37e34bcd-2751-42a4-846a-c35cfac766cc.gif)

**Environment**:
- Grafana version: cluod version
- Data source type & version: Google Sheet
- User OS & Browser: Chrome

**Comment by acappelletti** [comment]
Here the recording...
![problem_panel](https://user-images.githubusercontent.com/43847440/229085421-37e34bcd-2751-42a4-846a-c35cfac766cc.gif)

**Comment by leeoniya** [comment]
make sure your data is sorted by datetime in increasing order (oldest -> newest). if you cannot do this in the query or datasource, you can use the [Prepare time series transform](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#prepare-time-series)

**Comment by acappelletti** [comment]
> make sure your data is sorted by datetime in increasing order (oldest -> newest). if you cannot do this in the query or datasource, you can use the [Prepare time series transform](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#prepare-time-series)

**Comment by acappelletti** [comment]
Data is just sorted... but I forced on panel...
![image](https://user-images.githubusercontent.com/43847440/229088221-33b82a5f-5283-44fa-9df3-68a45ee24bf0.png)

**Comment by acappelletti** [comment]
I try with a value of 11 day and it run ok, why???
![image](https://user-images.githubusercontent.com/43847440/229088971-9571ff5f-cf31-4c0a-9254-71c9a27d315c.png)

**Comment by acappelletti** [comment]
With 11 days it run ok...
sincerely, I don't  know because...

![image](https://user-images.githubusercontent.com/43847440/229089519-144bbfd2-6630-4f88-b6ee-2cd0fea7c53a.png)
