### ISSUE TITLE
Support more external image stores for alerting

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6568]
The alerting 'external image store' works fine for me, no complaints, s3 if fairly easy, webdav, yuck

anyway, just like the share dashboard uses raintank infrastructure, I thought it would be better/easier for users if you could have a default 'external image store' setup in the ini that is freq deleted/wiped, saves a bit of time (obv big-boy users or commercial/sensitive stuff will want there own)

ease of use ?

**Comment by torkelo** [comment]
we have actually talked about this internally, definitely something we will try to do

**Comment by CyBeRoni** [comment]
Since grafana is these days a web server, wouldn't it make sense to have a "local" option that just serves them off local disk?

**Comment by torkelo** [comment]
Yes, local is also something we should add

**Comment by bergquist** [comment]
@CyBeRoni That would be fairly easy to do. But Slack requires the image to be public and if you want to access the images outside your corp network it have to be publicly accessible.

We will definitely add local storage of images. I just wanted to explain why we added s3/webdav first :)

**Comment by wei-hai** [comment]
It would be better to support retention policy when it comes to local storage in order to wisely utilize disk space.
