### ISSUE TITLE
Dashboard previews removal

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#65693]
We are deprecating the [dashboard previews feature](https://grafana.com/docs/grafana/latest/search/dashboard-previews/) in v9.5, and removing it in v10

remove
- [ ] docs
- [ ] image renderer experimental mode + docs
- [x] backend service
- [ ] backend renderer service clean up
- [x] frontend
- [ ] HG deployments

add
- [ ] v10 upgrade path docs
- [x] v9.5 deprecation notice https://github.com/grafana/grafana/pull/65692
- [x] doc deprecation notice https://github.com/grafana/grafana/pull/65698

**Comment by GrafanaWriter** [comment]
FYI - @imatwawana

**Comment by GrafanaWriter** [comment]
@imatwawana and @ArturWierzbicki - I'm going to mark this as closed as it's listed as In progress for docs, but it's been in that state for a while and I see two linked PRs. Please re-open if there's more to do here.
