### ISSUE TITLE
VizLegend Component [design]

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#65697]
**Goal:**

This component needs to be aligned with [Storybook](https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-vizlegend--with-no-values).

**Comment by staton-hyse11** [comment]
Provided feedback in Figma:

- restructure the base component as our discussion. This will simplify it's structure and make it more usable

**Comment by natydej** [comment]
Figma [branch](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Grafana-design-system---Dark-theme?node-id=8444-13518) merged and published.
