### ISSUE TITLE
Permission denied on a plugin enabling

### ISSUE THREAD

**Issue by MethyleneBlu** [grafana/grafana#6570]
Hello guys,

I'm currently working with grafana 3.1.1, I just installed it on a server with no Internet access and copied two plugins github in /var/lib/grafana/plugins:
- grafana-zabbix-app-master (I need a zabbix datasource)
- piechart-panel-master

When I go to "dashboard > Installed Apps > Zabbix" OR "dashboard > Installed Apps > Pie Chart" I have a message "Permission Denied" in an orange box and I don't know why because the directory plugins is owned by grafana;grafana.

I would like to have this two plugins enabled for all my users,  including "Viewers" but for the moment no one seems to work. Do you know where the problem could be ?

I know it's maybe not the best place for support, so sorry if I didn't post in the good place.

Thank you by advance,

**Comment by torkelo** [comment]
Your Grafana user needs to be an org admin to enable apps.

The link to the plugin page from the home dashboad for non org admins is a known bug.

**Comment by MethyleneBlu** [comment]
Ok, great, thank you for the explanation.
Actually I think I found a solution with the author of the plugin himself here : https://github.com/alexanderzobnin/grafana-zabbix/issues/306

It seems that a plugin have to be enabled on each org, however I've separated my users in several Orgs mapped on a LDAP with a dynamic creation of orgs and no admin in each, so is there a mechanism to automate the enabling of a plugin on all orgs ?

I tried this without any sucess in the end of grafana.ini

`[plugin.zabbix]`
` enabled = true`
