### ISSUE TITLE
Search: Add clear search button to the input bar

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#65705]
Let's add a "Clear" button to the search bar so that it is easier to reset the content of it.

Adding a button similar to the one in time picker:
<img width="242" alt="Screenshot 2023-03-31 at 14 21 22" src="https://user-images.githubusercontent.com/100691367/229131746-29f50dd5-427f-42cc-8355-8b9461a48ad1.png">

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by JoaoSilvaGrafana** [comment]
Hi @tarunsamanta2k20 , that's great! I will assign you to it, feel free to open a PR when you are ready 😄

**Comment by tarunsamanta2k20** [comment]
@JoaoSilvaGrafana please let me know the location of this file.

**Comment by JoaoSilvaGrafana** [comment]
It would be adding a "Create" button in this "Search for dashboards" input, which I believe lives in `ManageDashboardsNew.tsx`

<img width="1627" alt="Screenshot 2023-03-31 at 17 30 16" src="https://user-images.githubusercontent.com/100691367/229177704-126d95f4-d539-4c77-9ab0-f51cbc186143.png">

**Comment by khushijain21** [comment]
i'd like to work on this, is it open

**Comment by JoaoSilvaGrafana** [comment]
Hi @khushijain21 , I am not sure if @tarunsamanta2k20 is still working on it. If they are not then you are free to work on it 👍

**Comment by khushijain21** [comment]
@JoaoSilvaGrafana this is my first PR - let me know if any changes required. Thanks
