### ISSUE TITLE
Loki: Show user status of log context queries in Explore 

### ISSUE THREAD

**Issue by chodges15** [grafana/grafana#65719]
**What happened**:
When looking at context for a slow query, the UI displays `Found 0 rows.` without any indication that there is a query in progress. This leads users to believe that the feature is not working.

![loki-context](https://user-images.githubusercontent.com/24880218/229145466-48264230-5d5a-41c3-acdc-f4c28b6902dc.gif)

**What you expected to happen**:
`Found 0 rows.` should not appear until the context queries have completed. Ideally I would see something like a spinner to let me know that the context panes are waiting for data. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Issue a Loki query that has a text filter and has not been recently cached
2. Set network throttling in browser devtools to more easily recreate
3. Click the expand context
4. Observe `Found 0 rows.` in pre and post context

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.4.7
- Data source type & version: Loki
- OS Grafana is installed on: Using grafana playground
- User OS & Browser: Safari

**Comment by gabor** [comment]
thank you for reporting this issue 👍 

this should be fixed by the new changes coming to the logs-context-view (for example: https://github.com/grafana/grafana/pull/65939). 
if you think the fix is not good enough, feel free to reopen the issue.
