### ISSUE TITLE
Search: Navigating to a dashboard from search should not clear the filters

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#65710]
**What happened**:

When you are searching for a dashboard, if you get a long list of results you might click one, but then if it is not the correct one and you navigate back to search you have lost your previous search term (and any other filters):

https://user-images.githubusercontent.com/100691367/229136349-4634ea97-177c-4a2a-9907-25d1940e1b67.mov

**What you expected to happen**:

I expect to be able to go back to search and still get the same list of results.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to search https://play.grafana.org/dashboards
2. Search for a term and click one of the results
3. Using the breadcrumbs click on "Dashboards" to go to search again

**Anything else we need to know?**:

If you search for a term and then navigate to a different page, like "Playlists" and then back to "Dashboards" it will maintain your search term, it is only if you select a dashboard that it clears the filters.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by khushijain21** [comment]
I'd like to work on this issue - can you guide?

**Comment by torkelo** [comment]
think if we want filters to be preserved when going back we should probably add them the URL , so we use URL as the authoritative source of truth / state for filters

**Comment by torkelo** [comment]
because this way if you come back to the search later via menu you likely don't want those search terms and filters to be active

**Comment by JoaoSilvaGrafana** [comment]
@torkelo this is already what happens though 😅  if you type something in the search, then navigate away and go back to search, it keeps the filters. We figured this out from an escalation and the only place where it didnt work was when you navigated to a dashboard from search. So when discussing it with the team we agreed that we should just make it consistent and keep search filters also when selecting a dashboard.

https://user-images.githubusercontent.com/100691367/233599288-1c4e0bbe-d4e8-4612-aeee-91ce5c9fe2fd.mov

**Comment by torkelo** [comment]
>  if you type something in the search, then navigate away and go back to search, it keeps the filters. 

sounds like a bug then :)

**Comment by JoaoSilvaGrafana** [comment]
> > if you type something in the search, then navigate away and go back to search, it keeps the filters.
> 
> sounds like a bug then :)

Yeah that's what we debated at first and then decided to just make it consistent and have that apply across the board. The use case for this specific scenario of going to a dashboard and going back to search is that you might have clicked the wrong dashboard and want to go back with the same filters to try the next one. We would want this to work with back button and using breadcrumbs as well, so if this is not what we want across the board we can bring the discussion up again in the navigation channel?

**Comment by torkelo** [comment]
@JoaoSilvaGrafana yea, when coming via breadcrumb it makes sense :+1:

**Comment by khushijain21** [comment]
I opened a PR to fix it, let me know
