### ISSUE TITLE
[Feature request] Support template variable in alerting panel

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#6572]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Suppose there are 300 servers and each server has 40 cpu cores, and I have a graph that monitors these 40 cpu cores for specific server. The SQL statement shall look like:
`select cpu-usage from tb1 where time > now() - 5m group by time(1m), host, cpu where host=$HOST`
I usually set $HOST to single server instead of multiple servers because the graph will be very messy otherwise, however, if I want to alert on multiple servers I have to set host to point to multiple servers and that will mess up the graph. I suggest that the template variable $HOST shall be configurable in alerting panel and it does not affect the one in metrics panel. With this feature, the alerting rule is able to monitor cpu cores on multiple servers while the graph only shows data for one server.

**Comment by CyBeRoni** [comment]
#6557

**Comment by bergquist** [comment]
@wei-hai  300 servers with 40 cores each :) I'm very curious about your Grafana usage. If you would like to share, please send me an email at carl@raintank.io about it.

As stated by CyBeRoni this seems like a dupelicate of #6557 so Im closing it.
