### ISSUE TITLE
[Bug report] hoover highlighting is wrong in v4 beta

### ISSUE THREAD

**Issue by Runamook** [grafana/grafana#6573]
Grafana: Version 4.0.0-beta1 (commit: v4.0.0-beta1)
Datasource: graphite, influxDB 1.0.2, ES 2.2.0
OS: CentOS Linux release 7.2.1511 (Core) 

When hoover "mode" is "All Series" and "sort order" is not "None" (either "increasing" or "decreasing")
Hoovering over a graph highlights wrong metric.

If "sort order" is "None" highlighting works fine.

**Comment by benrubson** [comment]
Solved by #6578 👍
