### ISSUE TITLE
Telegram contract point integration does not accept "<" character in label value

### ISSUE THREAD

**Issue by wackazong** [grafana/grafana#65769]
**What happened**: Error when delivering alert notification via Telegram contact point integration

**What you expected to happen**: Receive telegram notification

**How to reproduce it (as minimally and precisely as possible)**: use a < character in a custom label value

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version: irrelevant
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome
- Grafana plugins: none
- Others: none

**Comment by wackazong** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/67227/229445180-adb4d2d1-589c-470b-8aca-229064d0dbcf.png">

**Comment by mellieA** [comment]
@wackazong I tried this with a real alert, it appears to work, but then doesn't send the notification and there is no UI error. 

<img width="1051" alt="Screenshot 2023-04-03 at 6 15 24 PM" src="https://user-images.githubusercontent.com/18175287/229654015-85bcc61c-b26b-4c7b-839b-7ba921d9415f.png">

Logs show the `bad request` error:

```
logger=alertmanager org=1 t=2023-04-03T18:41:43.292308-06:00 level=error component=alertmanager orgID=1 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="telegram/telegram[0]: notify retry canceled due to unrecoverable error after 1 attempts: failed to send telegram message: webhook response status 400 Bad Request"
```

The`bad request` error is only shown in the UI when adding the label as a custom value in the test notification. Putting quotes around the value does not help. This only affects `<` the `>` sign works

**Comment by armandgrillet** [comment]
Thanks for reporting this, we are not sure about the right way to handle this contact point limitation yet but there is definitely a bug.
