### ISSUE TITLE
Alerts in imported dashboards are not executed.

### ISSUE THREAD

**Issue by idpwf** [grafana/grafana#6577]
When importing a dashboard with alerts, the alerts are not scheduled for execution until "save dashboard"  is pressed in the UI. Not even restarting Grafana triggers these alerts.

Version: 4.0.0. beta1

**Comment by bergquist** [comment]
That's intended. When importing a dashboard from another system we figured you would want to setup naming, notifications and description before create and execute an alert. Don't you agree?

**Comment by idpwf** [comment]
In my use case (generating some dashboards offline, for a total of a couple hundred alerts, and then batch-importing them), this adds an unnecessary step.

**Comment by torkelo** [comment]
@idpwf for that you can use the normal save dashboard api (which will create alerts). The import api is used when importing a dashboard from another instance or publicly shared dashboard on grafana.net, an import process where you need to specify what data source to use etc

**Comment by daniellee** [comment]
Closing this, I can reopen if Torkel's suggestion did not work for you.

**Comment by schoofsc** [comment]
Hello, everyone, 
I have the same problem. 
Dashboards are exported (without export for sharing externally) and these are edited in a script (uid, id, notification channel etc.) and are then loaded in this script in Grafana into the appropriate folder. 
My problem is that I would like to set the dashboards as editable:false. However, this is not possible if the alerts are not started automatically. 

I used Grafana 6.4.3

**Comment by Hronom** [comment]
+1 same, how to trigger save dashboard from API? Need this to make alerts starts executing...
