### ISSUE TITLE
Disable or remove Angular plugins from catalog when `angular_support_enabled=false`

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#65795]
We should prevent users from being able to attempt an install of a plugin which is not compatible with their Grafana instance.

**Option A: Remove install option (Grafana version incompatibility model)**
- Pro: Gives the user full context on why the plugin is disabled
- Con: May waste users time navigating into the card 

**Option B: Remove from catalog (alt model)**
- Pro: Only shows the user what they can install
- Con: May cause confusion if searching for a known plugin / seeing a smaller list than expected with no clear indication of why.
  -  Potential mitigation of help text e.g. "This list shows plugins compatible with your version and configuration of Grafana, for the full catalog please see grafana.com/plugins"

**Comment by xnyo** [comment]
Implemented option A in https://github.com/grafana/grafana/pull/69084
