### ISSUE TITLE
Feature toggle removal: prometheusWideSeries

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#65807]
Added in https://github.com/grafana/grafana/pull/48792, on May 6, 2022. Consider whether we should release, including steps needed to validate readiness, or remove.

**Comment by itsmylife** [comment]
@kylebrandt could you please take a look at this if we are good to remove this feature toggle?

**Comment by itsmylife** [comment]
Removed in here https://github.com/grafana/grafana/pull/73751
