### ISSUE TITLE
Unable to save after influxdb error

### ISSUE THREAD

**Issue by breeswish** [grafana/grafana#6581]
Hi, I'm using telegraf + influxdb + grafana and this is [my dashboard config](https://gist.github.com/breeswish/9b400a9bf309ebc58dd0622c7935ed8d), which is modified from [telegraf metrics dashboard](https://grafana.net/dashboards/61).

I have successfully setup this stack several days ago and some days later it was broken.. I'm unable to see disk inodes and usage in the dashboard. Those queries becomes ERR_CONNECTION_RESET.

Now here is the issue: I tried to delete the broken panel (succeeded in UI) but it failed when saving (unexpected error). I can see ERR_CONNECTION_RESET in the JavaSciprt Developer Console. However I cannot see any useful information in the grafana console logging output even when I set log level to `debug`.

I also tried to edit the broken panel.. But it cannot be saved as well. Finally I deleted the whole dashboard, which is succeeded.. But I can no longer add it back by importing JSON:  still ERR_CONNECTION_RESET.

I'm using a custom built grafana on 32bit Ubuntu 14.04. version=4.0.0-beta1 commit=v4.0.0-beta1+30-g4fdfee7 compiled=2016-11-14T15:48:19+0800.

Update 1:

It's wired that I have dropped the whole influx database.. but still failed to import the dashboard..

Update 2:

Here is a much simplified [dashboard JSON](https://gist.github.com/breeswish/1a83947667429112704eb19fa8de5b15):

- Failed to directly import the dashboard JSON as a new dashboard (ERR_CONNECTION_RESET).
- Succeeded to import panel JSON one by one (and the graph is shown without any problems) but failed to save dashboard later:
   1. Success when importing dashboard JSON without any rows.
   2. Success when creating a new row.
   3. Success when saving the dashboard.
   4. Success when creating a new panel from the panel JSON in the dashboard JSON. The graph is working.
   5. Error when saving the dashboard now.. (ERR_CONNECTION_RESET)

**Comment by torkelo** [comment]
I managed to import that dashboard without any error .

ERR_CONNECTION_RESET error seems to be a connectivity issue in your browser, maybe it cannot reach grafana api or you data source.

**Comment by breeswish** [comment]
I don't think it's an browser issue.. only those related to database didn't work, in some scenarios. For example, creating the panel from JSON works and the graph is correct ----> data source seems Ok. However when saving the panel, the request becomes CONNECTION_RESET..

**Comment by torkelo** [comment]
ok, never seen an issue like this reported before, must be something with your setup / networking config. 

 I have no idea what could be the cause. Some proxy you have infront of Grafana? I mean the CONNECTION_RESET error is a browser connectivity error

**Comment by breeswish** [comment]
Yes I agree with you. I'm running grafana behind nginx. I was using Chrome.

When using Firefox, those CONNECTION_RESET requests do have a respond body but without any status code.. (and UI works). I copied request command to curl and it gave me "curl: (52) Empty reply from server".

I remember that it was CONNECTION_RESET as well when I directly access the go backend.. So it might not be a nginx issue. I'm still digging further to see what's going on :P

**Comment by torkelo** [comment]
must be something wonky with the nginx server then
