### ISSUE TITLE
Feature toggle removal: traceToMetrics

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#65811]
Added in https://github.com/grafana/grafana/pull/46298, on Mar 7, 2022. Consider whether we should release, including steps needed to validate readiness, or remove.

**Comment by Hackmeat** [comment]
Hi, is it still possible to enable to traceToMetrics feature? i am running on Grafana 10.3.3

**Comment by joey-grafana** [comment]
Hello, yes you can enable the feature in 10.3.3 using the `traceToMetrics` feature toggle, however, it has been [removed](https://github.com/grafana/grafana/pull/82884) in the Grafana 11 preview.

**Comment by ErikRosic** [comment]
hello @joey-grafana i tried it in Grafana 10.4 and not working. is it correct? 
![image](https://github.com/grafana/grafana/assets/70690126/4ad286ad-eebc-447e-94fc-4d63c23b6c5e)

**Comment by ErikRosic** [comment]
if am i correct, there should be button next to logs for this span to show metrics, right? 
![image](https://github.com/grafana/grafana/assets/70690126/905d5569-1c0d-4aed-a0fb-c5e97b867d25)

**Comment by joey-grafana** [comment]
You will need to ensure that your datasource is configured correctly. We have detailed documentation for configuring trace to metrics at [this link](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#trace-to-metrics).

**Comment by ErikRosic** [comment]
im not using datasource TNS Tempo but Jaeger. I dont see docs for this type of datasource ..  can you please give an advice for configuration? Thank you

**Comment by Hackmeat** [comment]
@joey-grafana Hi, i am running of grafana 10.3.3 and tryed many ways to implement tracetometrics in the helm values.yaml but non of those worked and i cann't find any information on it in any documentation. Can you help me out?

**Comment by Hackmeat** [comment]
Okay i found the correct config
grafana.ini:
  feature_toggles:
    enable:  traceToMetrics
    
How will this work after 11.0.0?

**Comment by ErikRosic** [comment]
not working for me in version 10.4
