### ISSUE TITLE
Feature toggle removal `datasourceQueryMultiStatus`

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#65815]
Added in https://github.com/grafana/grafana/pull/48550, May 3, 2022

TODO: Release GA, currently waiting for a rollout and some more input from @bergquist

**Comment by bergquist** [comment]
@tolzhabayev I think we agreed to keep code for now so perhaps we can close this?

**Comment by tolzhabayev** [comment]
yep, closing
