### ISSUE TITLE
Inappropriate HTTP response code - Alerting

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#65828]
Splitting up from the [main issue](https://github.com/grafana/grafana/issues/63543) so that separate squads can take a look at their areas.

|Endpoint| Error | Status code current
-- | -- | --
|/api/v1/eval | Failed to evaluate queries and expressions: failed to execute query D: no handler found for query type '' | 500
|/api/v1/eval | Failed to evaluate queries and expressions: input data must be a wide series but got type not (input refid) '' | 500
| POST /api/ruler/grafana/api/v1/rules/Legacy Alerts| failed to update rule group: failed to add rules: a conflicting alert rule is found: rule title under the same organisation and folder should be unique| 500 |

**Comment by tonypowa** [comment]
one more new related issue here:

GET /api/v1/provisioning/alert-rules/{UID}

500 response code returned

**Comment by taleena** [comment]
Hello all: looks like this was fixed in one area for the link above, but there is more to do, any other updates here?

**Comment by taleena** [comment]
@tonypowa is there a new gh issue for the one you found above?

**Comment by tonypowa** [comment]
@taleena i think we are good to close this one :)
