### ISSUE TITLE
Inappropriate HTTP response code - Datasources

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#65831]
Splitting up from the [main issue](https://github.com/grafana/grafana/issues/63543) so that separate squads can take a look at their areas.

|Endpoint| Error | Status code current
-- | -- | --
| **PUT /api/datasources/uid/{UID}**| [Failed to evaluate queries and expressions: failed to execute query D: no handler found for query type ''](pq: duplicate key value violates unique constraint \"UQE_data_source_org_id_name\) | 500 |
| **POST /api/datasources**,  **PUT /api/datasources/uid/{UID}**| [error](pq: value too long for type character varying(255)) | 500 |

Regarding "[error](pq: value too long for type character varying(255))" returning 500 when updating datasource if setting value longer than 255. Referring to Grafana source code, updating datasource is to set new value in PostgreSQL after getting the datatsource by uid. And it uses [XORM](https://xorm.io/) package to operate database,  struct "DataSource" auto mapping to a database’s table, and _string_ type map to _Varchar(255)_ in table. So if user set string value such as "Name", "URL" longer than 255 characters, this error will occur.

  - appropriate status code to be returned, rather than a generic 500 Internal Server
  - Grafana should add check logic for string value when updating SQL database,  avoid _value too long_ error

**Comment by marefr** [comment]
For PUT /api/datasources/uid/{UID} and PUT /api/datasources/{ID}

Probably need to add some validation around here and validate that datasource by name does not exists or is the same as the datasource being updated:
https://github.com/grafana/grafana/blob/68796a9f3190e807ebef8ee6cf34fb2a5c5e81dd/pkg/services/datasources/service/datasource.go#L232-L244
