### ISSUE TITLE
Metrics query does not work with negative lookahead

### ISSUE THREAD

**Issue by jz5168** [grafana/grafana#6583]
* **I'm submitting a ...**

- [ ] Bug report

Please include this information:
- What Grafana version are you using?

Version 3.1.1 (commit: a4d2708)

- What datasource are you using?

InfluxDB

- What OS are you running grafana on?

RedHat

- What did you do?

Define a query like this: select mean(value) from /^xyz.(?!all).*.ok.count/ where $timeFilter group by time($interval)

- What was the expected result?

Query come back with data.

- What happened instead?

It comes back with error:

{
  "error": "error parsing query: error parsing regexp: invalid or unsupported Perl syntax: `(?!` at line 1, char 24",
  "message": "error parsing query: error parsing regexp: invalid or unsupported Perl syntax: `(?!` at line 1, char 24"
}

Googling it revealed this discussion:

https://github.com/grafana/grafana/issues/1750

This needs to be fixed.  The regular expression is fine and tested.  It's just Grafana doesn't like about the negative look ahead.

**Comment by torkelo** [comment]
the error is from InfluxDB not grafana
