### ISSUE TITLE
Inappropriate HTTP response code - Dashboards and Folders

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#65830]
Splitting up from the [main issue](https://github.com/grafana/grafana/issues/63543) so that separate squads can take a look at their areas.

|Endpoint| Error | Status code current
-- | -- | --
| /api/folders| invalid API key | 500 |
| /api/dashboards/db | data source not found | 500 |

**Comment by taleena** [comment]
I see this is confirmed - if there is any indication that this won't get done in Q3, please let me know!

**Comment by taleena** [comment]
@tolzhabayev I'm closing this per the above comment.
