### ISSUE TITLE
Add Rudderstack events to the different items

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#65833]
@thanos-karachalios the events for the new screens and UI elements are pending to be defined.

![Image](https://user-images.githubusercontent.com/5699976/229519199-d3daa481-3617-4608-8da9-91e66f59279a.png)

**Comment by thanos-karachalios** [comment]
@ivanortegaalba the rudderstack events are documented here: https://docs.google.com/document/d/1CkV87S6n9oLVr8cG-Aapc6pVQxQtotfxWOBsZ05-vJY/edit#

**Comment by ivanortegaalba** [comment]
Fixed in #67060
