### ISSUE TITLE
[feature request] expose engine type for database operations

### ISSUE THREAD

**Issue by jbergstroem** [grafana/grafana#6585]
Please expose changing `Engine` while creating/updating tables. `skip-innodb` is pretty common for MariaDB installs, which makes the sql migrator break.

Tested on Grafana 3.1.1 on FreeBSD 11p2 behind nginx 1.10.2.

> t=2016-11-15T20:44:37+0100 lvl=eror msg="Exec failed" logger=migrator error="Error 1286: Unknown storage engine 'InnoDB'" sql="CREATE TABLE IF NOT EXISTS `migration_log` (\n`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL\n, `migration_id` VARCHAR(255) NOT NULL\n, `sql` TEXT NOT NULL\n, `success` TINYINT(1) NOT NULL\n, `error` TEXT NOT NULL\n, `timestamp` DATETIME NOT NULL\n) ENGINE=InnoDB DEFAULT CHARSET UTF8 ;"
> t=2016-11-15T20:44:37+0100 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: Error 1286: Unknown storage engine 'InnoDB'\n"

**Comment by jbergstroem** [comment]
I guess an alternate approach would be checking if innodb actually is supported in `supportsEngine()` via `show engines`. I personally think that avoiding propagating engine and letting the user change default engine is the most sane approach (other than actually providing a feature for setting it).

**Comment by daniellee** [comment]
The skip innodb option is deprecated: https://dev.mysql.com/doc/refman/5.7/en/innodb-turning-off.html

so closing this issue.
