### ISSUE TITLE
Upon saving the dashboard, do not store values of variables with refresh

### ISSUE THREAD

**Issue by timtofan** [grafana/grafana#6586]
Currently upon saving the dashboard, all variables values are saved as part of the dashboard.
This leads to "HTTP 413 Request Entity Too Large" error when amount of values is huge.

Separated from [issue 3176](https://github.com/grafana/grafana/issues/3176).

**Comment by torkelo** [comment]
for anyone who is interested in helping the relevant place to remove the options before saving is here, https://github.com/grafana/grafana/blob/master/public/app/features/templating/query_variable.ts#L50
