### ISSUE TITLE
Different Fieldnames in non-default Retention Policy (InfluxDB)

### ISSUE THREAD

**Issue by mnietz** [grafana/grafana#6587]
I'm using Grafana 3.1.1 with InfluxDB 1.0.2 on Debian 8.

When using a continuous query to downsample all measurements, influxdb automatically prefixes the new field-names with the aggregate function used.

For example load1 field becomes mean_load1 when using mean(*).

The problem is, that when selecting the different retention policy in grafana it does not show up the new field-names and still shows the one from the original dataset. I can input the field-name manually but i think there must be a better solution to achieve this.

Steps to reproduce:

```
Create new Retention Policy:

create retention policy rp_test_5m on monitoring duration 365d replication 1

Create Continuous Query to downsample system-measurement using all tags:

create continuous query "cq_avg_5m" on "monitoring" begin select mean(*) into "monitoring"."rp_test_5m".:MEASUREMENT FROM system group by time(5m),* end

Original Dataset:
> select * from system limit 1
name: system
------------
time                    load1   load15  load5   n_cpus  n_users uptime    uptime_format
2016-11-15T13:33:00Z    0.59    0.44    0.53    24      0       44165618  511 days,  4:13

New Dataset:

> select * from rp_test_5m.system limit 1
name: system
------------
time                    mean_load1              mean_load15             mean_load5      mean_n_cpus    mean_n_users        
2016-11-16T07:00:00Z    2.148333333333333       2.108999999999999       2.161           2              0.26666666666666666
```

Now select the new retention policy: rp_test_5m on the webinterface and open the selection of fields. It still shows up load1, load5 instead of mean_load1, mean_load5 and so on.

**Comment by torkelo** [comment]
this is an issue for InfluxDB to solve I think, maybe this issue will help, 
https://github.com/influxdata/influxdb/issues/7198
