### ISSUE TITLE
[Docs] Create organisation via HTTP API

### ISSUE THREAD

**Issue by geckogecko** [grafana/grafana#6588]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

I am recently using the HTTP API a lot. But what I am missing is a way to create organisations via it.

**Comment by bergquist** [comment]
POST /api/orgs
`
{
 "name": "new org"
}
`
