### ISSUE TITLE
The permission table is not recognized.

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [grafana/grafana#65883]
Hello,

Before starting the Grafana service, we added a role to the permission table.

Like this

![image](https://user-images.githubusercontent.com/95339676/229704626-5a69d258-20a8-449a-9eeb-d2e1c114847a.png)

However, if you check permission in the dashboard after starting the Grafana service, it will be empty as follows.

![image](https://user-images.githubusercontent.com/95339676/229704913-d59afd82-d3f3-4c7e-b16b-3b771e0d7e86.png)

Curiously, the dashboard link expresses itself.

![image](https://user-images.githubusercontent.com/95339676/229705152-e67de38d-e2ec-45bb-8afe-661f36af8da6.png)

I want to show the screen to an anonymous user.

As expressed in the manual, I gave true whether to use anonymous users.

![image](https://user-images.githubusercontent.com/95339676/229705366-652ff5fd-4f0c-4960-8a1a-3d20b26ecde5.png)

Why is the permission table not recognized? ...

**Comment by mellieA** [comment]
@YoonSungHyun-inzent manually editing the permissions table is not recommended. To enable anonymous access you'd want to follow the instructions [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/#anonymous-authentication)

There are more settings to add to the config file to specify the org and role that anonymous users get. For further help with questions, we ask that you use our community forum at community.grafana.com
