### ISSUE TITLE
Alertmanager HA peer reconnect timeout with multiple deployments across namespaces

### ISSUE THREAD

**Issue by daxroc** [grafana/grafana#65891]
Given the scenario where you may want to run 
- Many grafana deployments in HA in a single namespace
- Many grafana deployments in HA in multiple namespaces

Both using shared subnets 

The default reconnect timeout of 6h is far to long, as it will enable a condition where unrelated alertmanagers can gossip if a previously used IP is reused and no additional controls are in place.

The fix was included in [PR-42300](https://github.com/grafana/grafana/pull/42300) but not released

**What happened**:

HA Grafana alertmanagers reconnect enables a scenario where unrelated alertmanagers can gossip when IPs are reused within the 6h default.

Once non cluster members join, alertmanager starts to behaving odd intermitent alerts, delayed resolves. 

**What you expected to happen**:

The reconnect window to be adjustable and allow operator choice as to what it should be. This may not be enough.

**How to reproduce it (as minimally and precisely as possible)**:

Start several grafana HA deployments within a small subnet using a headless service for the HA configuration. 
Restart the deployments several times, once the IPs start to be reused the `alertmanager_cluster_members` metric will grow beyond the desired cluster size. 

**Anything else we need to know?**:

**Environment**: k8s
- Grafana version: 8.x, 9.x
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by JohnnyQQQQ** [comment]
Hey, thanks for opening this well researched issue. What you need is called labels in memberlist. In [this](https://grafana.com/blog/2022/09/28/inside-the-migration-from-consul-to-memberlist-at-grafana-labs/) blog post we explain what it is (section `Why memberlist labels matter`). TL;DR: each cluster has a unique label (simple string) and will reject any messages that do not have the correct label. We discussed it internally and I will spin up a PR that adds support for it.
