### ISSUE TITLE
Alerting: Pause all alerts via API or a button

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6589]
Would like to pause all alerts if there is any issue with the datasource/grafana or when datasource is in maintenance.

**Comment by torkelo** [comment]
I think a better way would be to pause the alerting engine, instead of pausing all alerts

**Comment by bergquist** [comment]
Might be cases where you want to pause alerts for just one data source.

**Comment by torkelo** [comment]
yes, but then you don't pause all alerts. and you come close the territory of silence mechanics.

**Comment by utkarshcmu** [comment]
IMO, for v4.0.0, we can have 1 single API or button for Admin which can pause the alerting engine or the scheduler for all alerts. Whenever admin is pausing the alerting engine, he can notify all the stakeholders that Grafana alerting is in maintenance mode due to XYZ reason.

**Comment by ichekrygin** [comment]
+1 on pausing alerts for a specific data source
Use-case: I want to upgrade my TSDB instance, and need to pause all alerts associated w/ that data source to during the maintenance window.

**Comment by mchesler** [comment]
👍  Hadn't realized this feature was missing until I upgraded our TSDB yesterday and set off quite a few unintentional alarms

**Comment by bergquist** [comment]
Closed by #6996

**Comment by utkarshcmu** [comment]
Awesome, thanks @bergquist 👍

**Comment by ichekrygin** [comment]
Thank you :+1:

**Comment by TrymBeast** [comment]
Shouldn't this be documented in the Alerting API documentation?

**Comment by daniellee** [comment]
@TrymBeast is it not already documented: http://docs.grafana.org/http_api/admin/#pause-all-alerts

**Comment by TrymBeast** [comment]
@daniellee thanks for the reference, I didn't knew it was in the Admin API
