### ISSUE TITLE
Mysql: every update brings new issues

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#65901]
Why instead to fix the existing issues, each Grafana updating brings new issue with MySql?
It's impossible to go ahead in this way. Instead of working we have to spend time  find each time a new workaround.
There are several problems with mysql that since time make impossible to update with the last version. For instance, one of my reported bug was this one, still existing
https://github.com/grafana/grafana/issues/59453
Now a new situation. If a Mysql statement doesn't return any records, the query and its ID simply disappear and the following query takes its place.In this way all the panel that uses this approach, like "ctrl.data[X]" cannot work anymore.
If I have 3 queries and the second one doesn't return any records, the results of query [1] and [2] don't exist any more beecause in their sequence "ctrl.data[2]" became ctrl.data[1] and ctrl.data[2] simply doesn't exist any more. Of course this is a mess within the code :-(

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: mysql/phpmyadmin
- OS Grafana is installed on: Windows/linux
- User OS & Browser: chrome
- Grafana plugins: html
- Others:

**Comment by mellieA** [comment]
@DonatoD can you share a screenshot or sample of the query result and your use case for referencing the query number?

**Comment by DonatoD** [comment]
1)  --------------------------------
This is a simple table
![image](https://user-images.githubusercontent.com/51508670/230792681-82f83878-16d4-4b5b-8690-bd1fe40ac7cc.png)
2)  --------------------------------
In Grafana I write these queries that all provide at least a record for each
A) SELECT * FROM test1 WHERE timing > "2023-04-05 10:00:00" ORDER BY timing DESC LIMIT 1
B) SELECT C1, D1 FROM test1 WHERE timing > "2023-04-05 10:00:00"
C) SELECT C1 FROM test1 WHERE timing > "2023-04-07 10:00:00" ORDER BY timing DESC LIMIT 1
Since MYSQL returns at least one record for each query, all of them can be called in the html panel as:
ctrl.data[0].rows[0] --> query's A result
ctrl.data[1].rows[0]  --> query's B result
ctrl.data[2].rows[0] --> query's C result
![image](https://user-images.githubusercontent.com/51508670/230793100-f53388df-1747-47b8-83de-8a1c1dfbc037.png)
3)  --------------------------------
if the query B become
SELECT C1, D1 FROM test1 WHERE timing < "2023-04-01 10:00:00"
MYSQL doesn't return any record. Differently from the previous version, now Grafana doesn't show NULL as result for this query, but it get simply ignored
![image](https://user-images.githubusercontent.com/51508670/230793453-16241377-1214-4ef7-a56a-23456963ac7f.png)
Now all the code is messed up
ctrl.data[0].rows[0] --> query's A result
ctrl.data[1].rows[0]  --> query's C result (before it was query's B result)
ctrl.data[2].rows[0] --> doesn't exist anymore  (before it was query's C result)

And this is just one more thing that breaks dashboards from working when MYSQL is involved :-(

**Comment by gabor** [comment]
hi @DonatoD, this should work starting with grafana `10.1.0`, i was able to reproduce the problem (with the builtin `table` panel) in `10.0.0`, but it worked in `10.1.0`. (of course, i recommend going with the current newest grafana version).

if this does not solve your problem, please write back and we can reopen the issue.
