### ISSUE TITLE
[Feat Req]: Support Multi valued variables in InfluxDB field select clause

### ISSUE THREAD

**Issue by erSitzt** [grafana/grafana#6590]
* **I'm submitting a ...**
- [ x] Bug report

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708)
- What datasource are you using?
InfluxDB 1.1.0
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Created a template for the query field (fyi datasource name is still influx0.9, but influx is v1.1.0)
`SHOW FIELD KEYS from /.*/`
![image](https://cloud.githubusercontent.com/assets/1625376/20340373/84d61ed4-abe1-11e6-9aad-dc5166115bc0.png)

and used it in the query editor
![image](https://cloud.githubusercontent.com/assets/1625376/20340320/4295972a-abe1-11e6-9681-f7d7067114d1.png)

- What was the expected result?
The expected result should match the documentation for the InfluxDB SELECT-Statement.
For a list of fields:
`SELECT "metrics.metric","metrics.service" FROM imageproxymetrics.autogen./^(\/neo\/artikel\/v0\.9\.2)$/ WHERE time > now() - 1w GROUP BY host`
or for regex
`SELECT /^(metrics.metric|metrics.service)$/ FROM imageproxymetrics.autogen./^(\/neo\/artikel\/v0\.9\.2)$/ WHERE time > now() - 1w GROUP BY host`

- What happened instead?
The query is a mixture of both, containing quotation marks and curly braces
`SELECT "/^{metrics.metric,metrics.service}$/" FROM imageproxymetrics.autogen./^(\/neo\/artikel\/v0\.9\.2)$/ WHERE time > now() - 1w GROUP BY host`

**Comment by torkelo** [comment]
seems like support for regex in field name was recently merged into InfluxDB. https://github.com/influxdata/influxdb/pull/7442  part of future InfluxDB 1.1 release

It also requires support in Grafana.

**Comment by erSitzt** [comment]
Yes, regex support is new, but multi value in the SELECT statement via template should work without it.

**Comment by torkelo** [comment]
it should, how?

**Comment by erSitzt** [comment]
Regex are not needed for multi value select based on a template. It's just a comma separated list of the template values.

`SELECT "field1","field2" FROM xxx`

Sorry if i'm mistaken, havent had time to look at the query generation code.

**Comment by torkelo** [comment]
that does not work with aggregation functions which 99.9% of all queries use

**Comment by torkelo** [comment]
but your right, when not using any function it's just a quoted csv list

**Comment by ra88github** [comment]
+1
For me keys in templates is last missing feature after migration from Graphite to InfluxDB.

> that does not work with aggregation functions which 99.9% of all queries use

Now it's easy to be done using regex, but for release before 1.1 it's also simple:
`SELECT function("field1"),function("field2") FROM xxx`

Also this request is the same as #6248

**Comment by torkelo** [comment]
Ok, closing it since there already is an issue
