### ISSUE TITLE
Alerting on anomalies

### ISSUE THREAD

**Issue by CyBeRoni** [grafana/grafana#6591]
* **I'm submitting a ...**
Feature request

I'm trying to consider ways to alert on anomalous data. That is, I could have, for example, a graph of website requests/sec or logins or something, the actual data points of which could vary wildly during the day. Suppose my website is not visited at all at night and peaks in visitors at noon, and I want to know if suddenly that drops to zero during the day. I can't set an alert on "req/sec == 0" or something to that effect, because that would trigger every night. 

As it is I see two options: 
- Allow an alerting query to be compared to another query, so that one could say "alert if the difference between query A and query B is more than X". Query A could be an alert query as it exists now, and query B could be a moving average, or a time-shifted query so that I can compare today's data with the data from yesterday or a week ago. (Caveat: what if a week ago there was a problem but not today?)
- Allow for schedule-based alerting. I could set an alert to only trigger if the reqs/sec is 0 during the day, but not at night. 

Perhaps someone has more ideas.

**Comment by torkelo** [comment]
yes, we hope to do what your suggesting some time in the future, 

opened two issues to discuss that further:
Query condition that can compare two queries:
https://github.com/grafana/grafana/issues/6593

Time of day restrictions:
https://github.com/grafana/grafana/issues/6592

**Comment by CyBeRoni** [comment]
Clearly I suck at searching. Glad it was already on the radar.
