### ISSUE TITLE
reset AD permission when login

### ISSUE THREAD

**Issue by Allen-yan** [grafana/grafana#6594]
* **I'm submitting a ...**
- Bug report

Please include this information:
- What Grafana version are you using?
3.0.1
- What datasource are you using?
- What OS are you running grafana on?
ubuntu-12.04
- What did you do?
logoff, then login
- What was the expected result?
the permission is still the same I last login(Editor)
- What happened instead?
the permission is always reset to Viewer

**Comment by torkelo** [comment]
For ldap you control your org role in the mapping ls defined in ldap.toml

**Comment by Allen-yan** [comment]
Is that mean I must config the permission in org level, not a single person?

**Comment by torkelo** [comment]
no, you can map ldap groups to grafana org role

**Comment by Allen-yan** [comment]
Can I set permission for single person in ldap?

**Comment by torkelo** [comment]
maybe if you set memberOf attribute to cn, you can treat the cn as user group and then specify group mappings per user
