### ISSUE TITLE
Singlestat: Template variables don't work correctly in prefix/postfix fields

### ISSUE THREAD

**Issue by tischenko** [grafana/grafana#6595]
I'm submitting a bug report.

Grafana 3.1.1 with Prometheus.

I'm trying to use variables in prefix/postfix fields of Singlestat widget, it works, but not correctly. 

![screen shot 2016-11-16 at 12 33 32](https://cloud.githubusercontent.com/assets/1525190/20345875/70289f30-abf9-11e6-96a5-6547469e3e30.png)
I use the same variable $site in widget's title and prefix fields. As you see, it works as expected in the title, but in prefix field I see additional braces. This is the first issue.

![screen shot 2016-11-16 at 12 39 30](https://cloud.githubusercontent.com/assets/1525190/20345983/01992c14-abfa-11e6-91e0-970f6841bb58.png)
When I add another widget with the same variable, the situation becomes worse. I see all possible values of $site variable on each widget separated by comma.

Expected behavior is to see "build.myhostname.com OK" on the first widget and "confluence.myhostname.com OK" on the second one.

**Comment by torkelo** [comment]
fixed!
