### ISSUE TITLE
Update Moment-Timezone  of 0.5.41 to 0.5.43

### ISSUE THREAD

**Issue by sagoyanfisic** [grafana/grafana#65972]
**What happened**:
Using Grafana 9.3.1, Mexico City appears to be UTC-5:00, while it is supposed to be UTC-06:00, as Mexico no longer observes daylight saving time (DT) . Also, the time zone offset for Mexico City should be written as "-06:00" 

**Anything else we need to know?**:
Upgrade Moment-Timezone 0.5.41  to 0.5.43
Generate a new image on Docker Hub so that Helm and other repositories can update their images with this fix. 

**Environment**:
Grafana version:  9.3.1,
Data source type & version: any
OS Grafana is installed on: Docker
User OS & Browser: Google Chrome
Grafana plugins:
Others:

**Comment by andrearota** [comment]
Hi, it is related to this #65934. The fix seems to be already in Grafana 10.0.0 pre-release, but not in in the latest versions of 9 and 8.

**Comment by mellieA** [comment]
Closing in favor of #65934
