### ISSUE TITLE
/api/datasources/uid/:uid/health api doesn't work for prometheus datasources 

### ISSUE THREAD

**Issue by harish422** [grafana/grafana#65970]
Hi Grafana Team,

Can someone clarify why the below datasource health api results in "message: Not found" ? for prometheus datasource. The same works fine for influxdb datasource though. When I looked at the network calls from UI for influxdb and prometheus datasource connectivity test , I don't see health api invoked for prometheus datasource unlike influxdb. But both were successful from UI. from API call's only influxdb health api can be verified.

The api seems to be correct as per the reference link : https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health

<img width="930" alt="Screen Shot 2023-04-04 at 1 23 08 PM" src="https://user-images.githubusercontent.com/23487589/229932770-4ad9debe-5f36-4487-9b2f-790d485a9f74.png">

I could also confirm removing "health" at the end does return the datasource details.:

<img width="908" alt="Screen Shot 2023-04-04 at 1 26 30 PM" src="https://user-images.githubusercontent.com/23487589/229932818-8f188680-1089-46ce-8d74-1551ac14149b.png">

**Comment by gtk-grafana** [comment]
https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#check-data-source-health

> Makes a call to the health endpoint of data source identified by the given uid. **This is not mandatory** - every plugin author has to [implement support for health checks](https://grafana.com/tutorials/build-a-data-source-backend-plugin/#add-support-for-health-checks) in their plugin themselves.

Prometheus hasn't implemented a health check yet, currently we're calling the query endpoint and verifying that a sample query goes through (1+1) and returns valid results.

**Comment by biloocabba** [comment]
Any updated or workaround , i am getting the same issue when I run health check 

https://grafana..../api/datasources/uid/2zN3EWPGk/health
Failed to check health for data source WATCHER  (UID: 2zN3EWPGk)
Status Code: 503
Response: {"message":"Plugin unavailable","traceID":""}

**Comment by bohandley** [comment]
Hi @biloocabba, the health check was implemented in v10.0.0. What is your Grafana version and what are you using for auth in the Prometheus config?

**Comment by biloocabba** [comment]
Hi @biloocabba  we are using Grafana Entriprise v9.5.9  ( Docker image ) , As I remember I updated to 10.0.0 but we had an issue with Ldap authentication, so I rolled back.
