### ISSUE TITLE
Elasticsearch plugin is not listing all the fields in Terms.

### ISSUE THREAD

**Issue by nrajan1989** [grafana/grafana#6597]
All the fields defined in elasticsearch are not getting displayed in Grafana. Even though we have defined around 60 fields we are able to see only 4 fieds in terms. Please suggest how to access all the fields defined in elastic search.
We are also trying to setup a docker statistics dashboard in Grafana to have the docker memory usage grouped by container_name. Can anyone help with the lucene query to setup the same?

**Comment by torkelo** [comment]
can you show the raw request and response from Elasticsearch? (see this in chrome dev tools network tab)

**Comment by nrajan1989** [comment]
![capture-grafana](https://cloud.githubusercontent.com/assets/23500704/20350129/9413d6aa-ac33-11e6-8eb5-bc436adb72c3.PNG)

**Comment by torkelo** [comment]
when you click on the field dropdown, at the same time open chrom dev tools network tab, then in that tab click on response,  so we can see what Elasticsearch response is

**Comment by nrajan1989** [comment]
{"cadvisor":{"mappings":{"stats":{"properties":{"container_Name":{"type":"string"},"container_stats":{"properties":{"cpu":{"properties":{"cfs":{"properties":{"periods":{"type":"long"},"throttled_periods":{"type":"long"},"throttled_time":{"type":"long"}}},"load_average":{"type":"long"},"usage":{"properties":{"per_cpu_usage":{"type":"long"},"system":{"type":"long"},"total":{"type":"long"},"user":{"type":"long"}}}}},"diskio":{"properties":{"io_merged":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"io_queued":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"io_service_bytes":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"io_service_time":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"io_serviced":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"io_time":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Count":{"type":"long"}}}}},"io_wait_time":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Async":{"type":"long"},"Read":{"type":"long"},"Sync":{"type":"long"},"Total":{"type":"long"},"Write":{"type":"long"}}}}},"sectors":{"properties":{"major":{"type":"long"},"minor":{"type":"long"},"stats":{"properties":{"Count":{"type":"long"}}}}}}},"filesystem":{"properties":{"available":{"type":"long"},"base_usage":{"type":"long"},"capacity":{"type":"long"},"device":{"type":"string"},"has_inodes":{"type":"boolean"},"inodes":{"type":"long"},"inodes_free":{"type":"long"},"io_in_progress":{"type":"long"},"io_time":{"type":"long"},"read_time":{"type":"long"},"reads_completed":{"type":"long"},"reads_merged":{"type":"long"},"sectors_read":{"type":"long"},"sectors_written":{"type":"long"},"type":{"type":"string"},"usage":{"type":"long"},"weighted_io_time":{"type":"long"},"write_time":{"type":"long"},"writes_completed":{"type":"long"},"writes_merged":{"type":"long"}}},"memory":{"properties":{"cache":{"type":"long"},"container_data":{"properties":{"pgfault":{"type":"long"},"pgmajfault":{"type":"long"}}},"failcnt":{"type":"long"},"hierarchical_data":{"properties":{"pgfault":{"type":"long"},"pgmajfault":{"type":"long"}}},"rss":{"type":"long"},"swap":{"type":"long"},"usage":{"type":"long"},"working_set":{"type":"long"}}},"network":{"properties":{"interfaces":{"properties":{"name":{"type":"string"},"rx_bytes":{"type":"long"},"rx_dropped":{"type":"long"},"rx_errors":{"type":"long"},"rx_packets":{"type":"long"},"tx_bytes":{"type":"long"},"tx_dropped":{"type":"long"},"tx_errors":{"type":"long"},"tx_packets":{"type":"long"}}},"name":{"type":"string"},"rx_bytes":{"type":"long"},"rx_dropped":{"type":"long"},"rx_errors":{"type":"long"},"rx_packets":{"type":"long"},"tcp":{"properties":{"Close":{"type":"long"},"CloseWait":{"type":"long"},"Closing":{"type":"long"},"Established":{"type":"long"},"FinWait1":{"type":"long"},"FinWait2":{"type":"long"},"LastAck":{"type":"long"},"Listen":{"type":"long"},"SynRecv":{"type":"long"},"SynSent":{"type":"long"},"TimeWait":{"type":"long"}}},"tcp6":{"properties":{"Close":{"type":"long"},"CloseWait":{"type":"long"},"Closing":{"type":"long"},"Established":{"type":"long"},"FinWait1":{"type":"long"},"FinWait2":{"type":"long"},"LastAck":{"type":"long"},"Listen":{"type":"long"},"SynRecv":{"type":"long"},"SynSent":{"type":"long"},"TimeWait":{"type":"long"}}},"tx_bytes":{"type":"long"},"tx_dropped":{"type":"long"},"tx_errors":{"type":"long"},"tx_packets":{"type":"long"}}},"task_stats":{"properties":{"nr_io_wait":{"type":"long"},"nr_running":{"type":"long"},"nr_sleeping":{"type":"long"},"nr_stopped":{"type":"long"},"nr_uninterruptible":{"type":"long"}}},"timestamp":{"type":"date","format":"strict_date_optional_time||epoch_millis"}}},"machine_name":{"type":"string"},"timestamp":{"type":"long"}}}}}}

This is what we are getting when we are hitting the dropdown

**Comment by torkelo** [comment]
the autocomplete does not show nested fields right now.

Here is the open issue for that feature:
https://github.com/grafana/grafana/issues/3772
