### ISSUE TITLE
Update emicklei/go-restful to latest

### ISSUE THREAD

**Issue by bischoje** [grafana/grafana#65974]
**What is the chore?**:  Please update emicklei/go-restful version to at least 3.10.0 to address PRISMA-2022-0227.

**Is there anything else we need to know?**: See: https://github.com/emicklei/go-restful/issues/497

**Comment by Ankit-Kumar-Singh-01** [comment]
@sakjur Here is the dependency chain of `github.com/emicklei/go-restful/v3`
```
$ go mod why -m github.com/emicklei/go-restful/v3

# github.com/emicklei/go-restful/v3
github.com/grafana/grafana/pkg/services/ngalert/sender
github.com/prometheus/prometheus/config
github.com/prometheus/prometheus/config.test
github.com/prometheus/prometheus/discovery/kubernetes
k8s.io/client-go/kubernetes
k8s.io/client-go/discovery
k8s.io/client-go/openapi
k8s.io/kube-openapi/pkg/handler3
k8s.io/kube-openapi/pkg/common
github.com/emicklei/go-restful/v3
```

`github.com/emicklei/go-restful/v3` is a transitive dependency of `github.com/prometheus/prometheus v1.8.2-0.20211217191541-41f1a8125e66` package in [go.mod](https://github.com/grafana/grafana/blob/6e4fe51fe8f0da7719eb933ef77c6e8b46dae126/go.mod#L95) file. 

We have a couple of options to update `github.com/emicklei/go-restful/v3`:
1. Update `github.com/prometheus/prometheus` to the latest version i.e. `v0.43.0` (This tag may be confusing but it represents their latest release v2.43.0, [read more here](https://github.com/prometheus/prometheus/blob/24d7e5bd49dd26a45c2123a897c6cac5ac7c47f0/go.mod#LL110C2-L110C55)), which will update `go-restful/v3` to `v3.10.1`. Moreover updating it will update some of its other transitive dependencies as well.
2. Add `github.com/emicklei/go-restful/v3 v3.10.1 // indirect` under the `require` block in the go.mod file. Just like it is in the [Prometheus](https://github.com/prometheus/prometheus/blob/24d7e5bd49dd26a45c2123a897c6cac5ac7c47f0/go.mod#LL110C2-L110C55) repository.

**Comment by sakjur** [comment]
That chain goes through an external test package, to see what's ever in use by Grafana you should add `-vendor` (see https://go.dev/ref/mod#go-mod-why).

It'd still be good to upgrade the version of Prometheus for a number of reasons, but go-restful is still not a package that's ever used by Grafana.

**Comment by DavidOhsie** [comment]
Upgrade of prometheus was addressed in this merge request: https://github.com/grafana/grafana/pull/67853

**Comment by sakjur** [comment]
Yes, closing this now as completed based on 👆

https://github.com/grafana/grafana/blob/a5d6136bcf71fe0081211d0b09a3d1ff58ebddf3/go.mod#L324
