### ISSUE TITLE
Upgrade to 9.4.7 failed : unable to create Alertmanager for org

### ISSUE THREAD

**Issue by BloberSh** [grafana/grafana#65998]
**What happened**:
After upgrade from 9.3.6 to 9.4.7, grafana startup failed with error message :  
`logger=ngalert.multiorg.alertmanager t=2023-04-05T11:33:43.950544618+02:00 level=error msg="unable to create Alertmanager for org" org=7800 error="error reading file 'silences' from database: context deadline exceeded"
logger=cli t=2023-04-05T11:33:43.950958208+02:00 level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:181 +0x9c\npanic({0x3d4c240, 0x70bb390})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc0013a6e70?)\n\t/drone/src/pkg/services/ngalert/notifier/alertmanager.go:232 +0xf5\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc0001c2a80, {0x4dfc668, 0xc0016e0c60}, {0xc000f5e000, 0x30e, 0xc0010ae648?})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc0001c2a80, {0x4dfc668, 0xc0016e0c60})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc0015489c0)\n\t/drone/src/pkg/services/ngalert/ngalert.go:176 +0x486\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x4e13728, ...}, ...)\n\t/drone/src/pkg/services/ngalert/ngalert.go:101 +0x5a9\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc5ea1eb9b, 0x1f}, {0x0, 0x0}, {0xc0005865f0, 0x5, 0x5}}, {{0x0, 0x0}, {0x7ffc5ea1ebc5, ...}, ...}, ...)\n\t/drone/src/pkg/server/wire_gen.go:431 +0x4a85\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4db4540, 0x5}, {0x4db57a0, 0xa}, {0x4db4538, 0x4}, {0x4db5790, 0xa}, 0xc000a0fa80})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc000b45b00?)\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5\ngithub.com/urfave/cli/v2.(*Command).Run(0xc0010dbe60, 0xc000a0ef40)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc00116eb60, {0x4dfc630?, 0xc00012a000}, {0xc000126000, 0x9, 0x9})\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main()\n\t/drone/src/pkg/cmd/grafana/main.go:39 +0x27d\n"`

**What you expected to happen**:
Grafana started

**Environment**:
- Grafana version: 9.4.7
- OS Grafana is installed on: RHEL 8
- Others: MySQL 8

**Comment by mellieA** [comment]
@BloberSh we have a report of another user running into something like this in https://github.com/grafana/grafana/issues/65163

Can you provide the steps you used for the upgrade? Is there anything unique about your alertmanager or environment that might help us to understand more?

**Comment by BloberSh** [comment]
Hello @mellieA ,

To upgrade we use ansible with the yum plugin on all front servers.
No specifications on alertmanager side.

We are running grafana in a cluster active/active with haproxy for front and active/passive for DB.

**Comment by alexweav** [comment]
How many connections are there in the database pool? Could we try increasing that?

Another angle - how big is the silences file? Are there any silences at all?

The panic downstream from the database error is definitely a bug that we can look into. However, it won't solve the original issue, it'll just prevent the downstream issue.

**Comment by BloberSh** [comment]
Hello @alexweav ,

For max connections : 
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 350   |
+-----------------+-------+

+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 10    |
+-------------------+-------+

So we are way far from the limit.

No silences file (no silences).

However, we did update 2 of the 4 servers with succes to the latest version. 
(the 2 that fails at startup are still the same and same error)
__________
For more precision, both 4 servers have identical configuration and OS.
There is 2 geographical site.

Site A : 
2 fronts (errors on update)
1 database (primary)

Site B : 
2 fronts (update OK)
1 database (secondary)

Primary database is backed up on the secondary one so all fronts are connected to the primary one.

**Comment by andrewbierbaum** [comment]
Hello @alexweav , I'm seeing the same issue failing to upgrade from 9.3.1 to either 9.3.11 or 9.4.7.

I'm seeing `Server lock for secret migration already exists`

```
logger=settings t=2023-04-20T17:33:31.648725608Z level=info msg="Starting Grafana" version=9.3.11 commit=f9548d33f8 branch=HEAD compiled=2023-03-16T23:16:52Z
logger=settings t=2023-04-20T17:33:31.648969125Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-04-20T17:33:31.648989404Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/custom.ini
logger=settings t=2023-04-20T17:33:31.649002016Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-04-20T17:33:31.649028961Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-04-20T17:33:31.649042806Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-04-20T17:33:31.649057692Z level=info msg="Config overridden from Environment variable" var="GF_SERVER_ROOT_URL=http://localhost:3000"
logger=settings t=2023-04-20T17:33:31.649070067Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_TYPE=mysql"
logger=settings t=2023-04-20T17:33:31.649084517Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_HOST=mysqlhost1:3306"
logger=settings t=2023-04-20T17:33:31.649106276Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_USER=jenga"
logger=settings t=2023-04-20T17:33:31.649131802Z level=info msg="Config overridden from Environment variable" var="GF_DATABASE_PASSWORD=*********"
logger=settings t=2023-04-20T17:33:31.649145485Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-04-20T17:33:31.649157602Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-04-20T17:33:31.649177191Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-04-20T17:33:31.649200155Z level=info msg="Path Plugins" path=/grafana/plugins
logger=settings t=2023-04-20T17:33:31.649224435Z level=info msg="Path Provisioning" path=/grafana/dockers/grafana/provisioning/
logger=settings t=2023-04-20T17:33:31.649286965Z level=info msg="App mode production"
logger=sqlstore t=2023-04-20T17:33:31.649408736Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2023-04-20T17:33:31.675061307Z level=info msg="Starting DB migrations"
logger=migrator t=2023-04-20T17:33:31.683121179Z level=info msg="migrations completed" performed=0 skipped=464 duration=760.3µs
logger=plugin.loader t=2023-04-20T17:33:31.85492733Z level=info msg="Plugin registered" pluginID=input
logger=plugin.loader t=2023-04-20T17:33:33.852229977Z level=info msg="Plugin registered" pluginID=grafana-piechart-panel
logger=plugin.loader t=2023-04-20T17:33:33.852339107Z level=info msg="Plugin registered" pluginID=grafana-simple-json-datasource
logger=plugin.loader t=2023-04-20T17:33:33.852373633Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-datasource
logger=plugin.alexanderzobnin-zabbix-datasource t=2023-04-20T17:33:33.860334118Z level=info msg=Profiler enabled=false
logger=plugin.alexanderzobnin-zabbix-datasource t=2023-04-20T17:33:33.86205971Z level=warn msg="Plugin process is running with elevated privileges. This is not recommended"
logger=plugin.loader t=2023-04-20T17:33:33.862096542Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-triggers-panel
logger=plugin.loader t=2023-04-20T17:33:33.86211229Z level=info msg="Plugin registered" pluginID=marcusolsson-json-datasource
logger=plugin.loader t=2023-04-20T17:33:33.862125056Z level=info msg="Plugin registered" pluginID=alexanderzobnin-zabbix-app
logger=plugin.loader t=2023-04-20T17:33:33.862137241Z level=info msg="Plugin registered" pluginID=blackmirror1-singlestat-math-panel
logger=plugin.loader t=2023-04-20T17:33:33.862151549Z level=info msg="Plugin registered" pluginID=boazreicher-sierraplot-panel
logger=plugin.loader t=2023-04-20T17:33:33.862164116Z level=info msg="Plugin registered" pluginID=flant-statusmap-panel
logger=secrets t=2023-04-20T17:33:33.862589671Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=query_data t=2023-04-20T17:33:33.865077331Z level=info msg="Query Service initialization"
logger=live.push_http t=2023-04-20T17:33:33.868190477Z level=info msg="Live Push Gateway initialization"
logger=infra.usagestats.collector t=2023-04-20T17:33:34.474727565Z level=info msg="registering usage stat providers" usageStatsProvidersLen=2
logger=server t=2023-04-20T17:33:34.474918457Z level=info msg="Writing PID file" path=/highland/grafana/tmp/pids/server.pid pid=124
logger=provisioning.alerting t=2023-04-20T17:33:43.690347737Z level=warn msg="file has invalid suffix 'README' (.yaml,.yml,.json accepted), skipping"
logger=provisioning.alerting t=2023-04-20T17:33:43.691062039Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2023-04-20T17:33:43.691090635Z level=info msg="finished to provision alerting"
logger=ngalert.state.manager t=2023-04-20T17:33:43.691494596Z level=info msg="Warming state cache for startup"
logger=grafanaStorageLogger t=2023-04-20T17:33:43.691836497Z level=info msg="storage starting"
logger=secret.migration t=2023-04-20T17:33:43.693569288Z level=error msg="Server lock for secret migration already exists"
logger=http.server t=2023-04-20T17:33:43.693766389Z level=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
logger=ngalert.state.manager t=2023-04-20T17:33:43.696980899Z level=info msg="State cache has been initialized" states=0 duration=5.481082ms
logger=ticker t=2023-04-20T17:33:43.69705647Z level=info msg=starting first_tick=2023-04-20T17:33:50Z
logger=ngalert.multiorg.alertmanager t=2023-04-20T17:33:43.69709042Z level=info msg="starting MultiOrg Alertmanager"
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Grafana server is running with elevated privileges. This is not recommended
```
and then I see grafana attempt to start again, but fail because the above with `Server lock for secret migration already exists` and the pervious `0.0.0.0:3000` is already in use.
```
logger=settings t=2023-04-20T17:33:45.073958312Z level=info msg="Starting Grafana" version=9.3.11 commit=f9548d33f8 branch=HEAD compiled=2023-03-16T23:16:52Z

logger=secret.migration t=2023-04-20T17:33:57.691036258Z level=error msg="Server lock for secret migration already exists"
logger=server t=2023-04-20T17:33:57.692481377Z level=error msg="Stopped background service" service=*api.HTTPServer reason="failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: address already in use"
```

**Comment by alexweav** [comment]
Hey @andrewbierbaum this does sound like a migration bug but it appears to be unrelated to the current one. I think filing a new issue is the quickest path to resolution on that issue, since we can get it routed to the appropriate group.

**Comment by BloberSh** [comment]
@alexweav , We did update to 9.4.9 with success and the error is no more present.

**Comment by iXingo** [comment]
same here in 11.0
