### ISSUE TITLE
newPanelChromeUi - Panel titles get cut off too early

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#65992]
**What happened**:
After updating to Grafana 9.4.7 and enabling feature toggle `newPanelChromeUI`. Existing dashboards with long panel titles get cut off prematurely with an ellipsis.

Grafana 9.4.7 with newPanelChromeUI enabled on left. Grafana 9.3 on right.
The panel itself has plenty of space to allow more of the title content to be present.
![image](https://user-images.githubusercontent.com/89977373/230025081-c5a96999-5a6a-425f-8098-2b217f3cc269.png)
Often important information is left in end of the title, for example the unit of measurement or metadata such as `(stacked/aggregated/per_user/etc)` to indicate if graphs are stacked on top of each other.

**What you expected to happen**:
Panel titles can be as long as the panel itself.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel, set title longer than 55 characters.

**Environment**:
- Grafana version: 9.4.7
```
[feature_toggles]
enable = newPanelChromeUI 
```

**Comment by mellieA** [comment]
@hterik thank you for reporting this. I tested this on a pre-release version of Grafana v10.0.0-54184pre (37eaf50197) and it is working as you expect. I was able to make the panel larger and the ellipses disappeared. 

![image](https://user-images.githubusercontent.com/18175287/230267691-53e0226a-ba0d-4932-94d8-e35551e1ec0d.png)

**Comment by torkelo** [comment]
This is fixed in 9.5
