### ISSUE TITLE
How to find incompatible syntax

### ISSUE THREAD

**Issue by songxiaosheng** [grafana/grafana#65997]
**What happened**:
When I import the dashboard into the official dashboard library, the following error will be prompted, how to find the incompatible language

![image](https://user-images.githubusercontent.com/81170548/230042326-3f4334ca-a471-441f-83ee-59f0f24ef4b7.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
-my grafana is 9.4.7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
dashboard json
[dashboard.json](https://github.com/songxiaosheng/post/blob/master/Dubbo%20Application%20Dashboard-1680687430096.json)

**Comment by mellieA** [comment]
@songxiaosheng I was able to import the dashboard but it is complaining about legacy components that it couldn't convert because there wasn't a datasource.  There are a lot of panels in this dashboard, I'm not aware of a trick that would show you where the legacy panels are. 

How did you export the dashboard?

**Comment by songxiaosheng** [comment]
> @songxiaosheng I was able to import the dashboard but it is complaining about legacy components that it couldn't convert because there wasn't a datasource.  There are a lot of panels in this dashboard, I'm not aware of a trick that would show you where the legacy panels are. 
> 
> How did you export the dashboard? 
> 

Thank you for your reply. I exported the dashboard through the dialog box that popped up with the share button on the top line. Is there a way to modify this panel to support importing into the official panel library

**Comment by mellieA** [comment]
@songxiaosheng have you tried using the option "export for sharing externally"? 

I also noticed that when I removed the HTML code in the first panel title the legacy errors disappeared. I replaced it with the variables that it looked like you used to create the hardcoded title: 

<img width="632" alt="Screenshot 2023-04-06 at 1 14 13 PM" src="https://user-images.githubusercontent.com/18175287/230473571-5b02443f-ccbd-44ee-a311-e3c85942248f.png">

**Comment by songxiaosheng** [comment]
> @songxiaosheng have you tried using the option "export for sharing externally"? 
> 
> I also noticed that when I removed the HTML code in the first panel title the legacy errors disappeared. I replaced it with the variables that it looked like you used to create the hardcoded title: 
> 
> <img width="632" alt="Screenshot 2023-04-06 at 1 14 13 PM" src="https://user-images.githubusercontent.com/18175287/230473571-5b02443f-ccbd-44ee-a311-e3c85942248f.png">
> 

thanks  i would try it🥰

**Comment by songxiaosheng** [comment]
@mellieA  
Thank you very much. I finally understand the reason. When exporting, I had to click on the "Export for sharing externally" option, but I ignored it
![image](https://user-images.githubusercontent.com/81170548/230754950-be27797e-e60f-4c0c-ac4f-54ba6aa38807.png)
