### ISSUE TITLE
Time Series panel does not fire DataHoverEvent

### ISSUE THREAD

**Issue by CSantosM** [grafana/grafana#65995]
I’m trying to create a custom plugin panel for listening events from others panel like a DataHoverEvent.
I’ve followed this official guide [How to subscribe to Grafana application events - #2 by csantosm](https://community.grafana.com/t/how-to-subscribe-to-grafana-application-events/59147/2) for doing that.

The problem is DataHoverEvent and LegacyGraphHoverEvent are not fired from this panel.
When I emit a DataHoverEvent manually from my plugin panel, the subscription is retrieved so my code is working properly.
I think this is a Time Series Panel bug. Could you check it out ?

Is it a panel bug? Is there something I need to set up for this working fine?

INFO:
Docker compose with

Grafana: grafana/grafana:9.2.15-ubuntu
MySQL: mysql:latest

The DataHoverEvent is only fired when I hover the legend, which is useless… 
![8bb188830b2156f785d326631c6da355296c0078](https://user-images.githubusercontent.com/10628395/230037841-b1437df7-038a-4a1b-ba9e-b0c4de629be7.gif)

**Comment by mellieA** [comment]
@CSantosM I'm not sure if there is a bug here, I'll let the squad comment on that. I'm wondering if the missing hover events could be related to https://github.com/grafana/grafana/pull/33433

**Comment by amarant** [comment]
@CSantosM did you activated shared crosshair in the dashboard options ?

**Comment by CSantosM** [comment]
That was the problem. Thank you.
