### ISSUE TITLE
Separate Notification Group for "No Data and Execution Errors"

### ISSUE THREAD

**Issue by chipper110** [grafana/grafana#6600]
* **I'm submitting a ...**
- [ ] Bug report
- [x ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?4.0 Beta
- What datasource are you using?InfluxDB
- What OS are you running grafana on?Ubuntu

It would be great to be able to send notifications for "no data" or "execution errors" to a separate notification group.  Usually no data or errors are a hardware or networking issue.  I would like to be able to inform my technicians that there is an issue for them.  They do not need to be alerted on data just as the team monitoring the data can't do anything about network or hardware issues.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
