### ISSUE TITLE
Grafana Alert - Error 1264: Out of range value for column 'for' at row 1

### ISSUE THREAD

**Issue by LincolnG4** [grafana/grafana#66002]
**What happened**:
Every time that I try to add a Alert rule with Alert evaluation behavior `for` greater than `0s` I got the error` "Failed to save rule: failed to update rule group: failed to add rules: failed to create new rules: Error 1264: Out of range value for column 'for' at row 1"`. I've already tried to run different queries and different database source but it still happening the same issue. I don't know if it is a bug or a miss configuration.

when I try to use for example evaluate every 1m and for 5m (or any other value different of 0s for `for`) :
![image](https://user-images.githubusercontent.com/59087790/230053296-8102e29e-5192-4439-9567-793043b7411a.png)

 It's only works when I use `0s` on `for`
![image](https://user-images.githubusercontent.com/59087790/230052758-1b4cef19-91e8-4bc5-beb8-490739a49143.png)

This the query that I'm trying to use.
![image](https://user-images.githubusercontent.com/59087790/230052174-34a79f99-aa56-48d6-84f2-5f4176bce941.png)

![image](https://user-images.githubusercontent.com/59087790/230052280-eb8187b2-6613-419a-8a6e-f665b2ebd6c1.png)

**What you expected to happen**:

I expect to use with any value in `evaluate every` and `for` respecting the rules of alerting

![image](https://user-images.githubusercontent.com/59087790/230053296-8102e29e-5192-4439-9567-793043b7411a.png)

**How to reproduce it (as minimally and precisely as possible)**:

Steps above

**Environment**:
- Grafana version: v9.3.1
- Data source type & version: Azure Data explorer and MySQL
- OS Grafana is installed on: Docker container (grafana/grafana-oss:9.3.1) running in Web App service from Azure
- User OS & Browser: Windows 10 - Chrome

**Comment by EricDylan47** [comment]
how you deal with it finally

**Comment by EricDylan47** [comment]
I updated the ·for·  value of alert_rule table on my database server，and it works，1000000000=1s
![84hQ5FTjA3](https://github.com/grafana/grafana/assets/96399633/9dfdc532-fb05-4502-814c-af352af8039d)
![Ms7jtAWdtp](https://github.com/grafana/grafana/assets/96399633/7df49b18-9d51-4158-9908-6bcb7bdcc234)

**Comment by LincolnG4** [comment]
In my case, it was a bad data type assigned to the value in the database during the migration from SQLite to MySQL. So, I just updated the data type on the table

**Comment by EricDylan47** [comment]
Yeah, what kind of data type should I switch to?I changed it from int（11）to bigint，this did not take effect

**Comment by LincolnG4** [comment]
I've changed to BIGINT in 3 tables and it fixed my issue:
ALTER TABLE alert_rule MODIFY  'for' BIGINT NOT NULL DEFAULT 0;
ALTER TABLE alert MODIFY  'for' BIGINT NOT NULL DEFAULT 0;
ALTER TABLE alert_rule_version MODIFY  'for' BIGINT NOT NULL DEFAULT 0;
