### ISSUE TITLE
Alerting: Data source problem

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6601]
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- What Grafana version are you using? v4beta
- What datasource are you using? INFLUXDB

I see in ALERTING there is a field 'If execution error or timeout', now I had this to alerting.  then on upgrading DataSource I got a ton of annoying alerts, so I thought can this be a TEMPLATE variable to switch off, no it can't.

Then I thought, is there no a better way maybe under the Data Source cfg that an ALERT can be specified to notify if your Data Source is unavailable, would be a better solution.

**Comment by torkelo** [comment]
will be solved by silence feature
https://github.com/grafana/grafana/issues/5856

Will allow you to temporary silence or pause a group of alerts (for example all that use a data source)

**Comment by roscoe57** [comment]
it would still be a nice feature to simply alert if the data source is not
reachable ?

**Comment by torkelo** [comment]
you can add such an alert yourself, the only issue then is to silence other alert rules that use that data source. 

We will see, there is a million things that could be done to further refine and improve alerting, but next step is temporary silence rules so when you shut down your data source or do other maintenance you can disable notifications (or rule evaluation)
