### ISSUE TITLE
Megabits/sec data rate unit displayed as "Mbits" instead of "Mbps"

### ISSUE THREAD

**Issue by scjoiner** [grafana/grafana#6602]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.2
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Docker
- What did you do?
Created a dashboard to display data rate in Mbps using "Unit: megabits/sec"
- What was the expected result?
The units would display as Mbps
- What happened instead?
The units displayed as Mbits

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
SELECT mean("bitrate") FROM "sentry" WHERE "sentryip" = '10.7.127.33' AND $timeFilter GROUP BY time($interval), "portname" fill(null)
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
![screen shot 2016-11-16 at 10 19 38 am 2](https://cloud.githubusercontent.com/assets/4303855/20352713/47303434-abe6-11e6-8293-09203f039629.png)

**Comment by torkelo** [comment]
your right, fixed!
