### ISSUE TITLE
Transformations: support more true join behavior

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#66032]
Feature request: Transformations support more true JOIN behavior like selecting a field and joining on dataframes that have different amounts of overlapping values and display more that unique joined on values.

Transformations has a few JOIN like transformations but they are all very particular. Merge joins on all field names that match, join by fields allows a user to select a single field to join on for inner and outer joins. Join by fields allow for selecting a field to join on but only create rows for the unique values in the selected field. Each of these get close to behaving like a true JOIN but do not cover all cases due to requirements.

[The customer from this escalation](https://github.com/grafana/support-escalations/issues/5362) is looking to join two frames with overlapping field values and join on a specific field. Neither merge nor join by fields supports this behavior. This does not work because they wish to select a field to join on that has 2 unique fields but with the results shown would create more than two rows. 

***note: This could be extended into an epic to create a true SQL join transformation but we will not be able to implement that until the dataplane contract has been implemented and we have more standardization across dataframes.

- [x] join on a field that has duplicates https://github.com/grafana/grafana/pull/72176

**Comment by bohandley** [comment]
Needs to be in a separate option for the JOIN transformation

**Comment by jasuade** [comment]
Hello @bohandley!  wanted to ask about the status of this Epic, is there some timeline about when it would be available? thank you in advance!

**Comment by jasuade** [comment]
Hey @bohandley, just checking in about the status of this feature, may I ask what is the progress and if there is more or less a timeline, so we can update customers accordingly? thank you in advance!

**Comment by bohandley** [comment]
@jasuade see [this PR](https://github.com/grafana/grafana/pull/72176) for the customer request. We will require a significant amount more testing for this so I see it as taking at least a month to get enough feedback to make sure it is working correctly and then another month to have it available for all users.

**Comment by jasuade** [comment]
Hello @bohandley thank you for the update on the status! Let us know if we or the customer can help with the testing of expected behavior.

**Comment by bohandley** [comment]
Thank you @jasuade, I will update you for further testing. I will be in contact and feel free to ping me for any customer updates. 

@samjewell Thank you for checking in but no, your issue with the transformation is that the multiple datasources queries both fields in each query, org_id, are of two different types, one is string and one is a number. If they are both a number, the inner join will work. See the example to use the "convert field type" below. Then each org_id is the number and the frames can be inner joined on that field value.
![Screenshot 2023-07-24 at 1 53 41 PM](https://github.com/grafana/grafana/assets/25674746/380970dc-b5fe-4e67-b7bd-ad15f244f9a5)

**Comment by bohandley** [comment]
Keep in mind
- [ ] allow user to select different fields to join on for the tabular outer join.

**Comment by cobolbaby** [comment]
>  allow user to select different fields to join on for the tabular outer join.

Hello @bohandley! I want to ask about the status of this Epic, is there some timeline about when it would be available? thank you in advance!

**Comment by bohandley** [comment]
Hello @cobolbaby! this work is currently on hold as the @grafana/grafana-bi-squad has taken on transformations. There is no ETA for this, thank you for your patience.
