### ISSUE TITLE
NestedFolders: API for returning total count of descendants of a folder

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#66038]
To make sure users understand the impact of Deleting and Moving folders, we would like to show the count of all ***nested*** descendants of a folder.

![image](https://user-images.githubusercontent.com/46142/230120488-8d78427a-4ffb-47ad-a80d-d4d9bd821208.png)

The frontend would request an API like `GET /api/folder/{uid}/counts` to return counts of all descendants for each type of child.

**Comment by ashharrison90** [comment]
@papagian @suntala is this now complete? 🤔 afaik we now have dashboard, folder, alert rule and library panel counts being returned

**Comment by suntala** [comment]
All backend changes for this are complete ✔️
