### ISSUE TITLE
[Grafana 9.4] Error updating options: Cannot assign to read only property 'resources' of object '#<Object>'

### ISSUE THREAD

**Issue by mwilfried** [grafana/grafana#66036]
**What happened**:
After upgrade to Grafana 9.4.1   (from version 9.3.1), a dashboard based on worldmap plugin and json to api datasource is no more working.  The dashboard use a variable that is based on query from Azure Datasource + a regex  as mentionned in this tuto https://medium.com/@tomjohnburton/visualising-a-distributed-network-c36871da52af

Since the upgrade, the variable is no more working  and I get the following message 
"Templating [ip]
Error updating options: Cannot assign to read only property 'resources' of object '#<Object>'"
![image](https://user-images.githubusercontent.com/32105900/230117505-d9d8289b-a020-449b-a776-106160734aea.png)

![image](https://user-images.githubusercontent.com/32105900/230118514-1326365d-88a3-4f61-a3c4-783da4fe89a0.png)

The issue is not reproduced on version 9.3.x

The proxy mode is enable for the datasources : 
- json to api 
- Azure Monitor

The configuration of the variable
![image](https://user-images.githubusercontent.com/32105900/230120054-8dc734db-337c-4bb1-ba9b-d46c37a436df.png)

**What you expected to happen**:

Same behaviour thant 9.3 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.x 
- Data source type & version: Azure Monitor (latest)
- OS Grafana is installed on: container 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mfmbarros** [comment]
same here on 9.4.7

**Comment by mellieA** [comment]
There is a fix here that was added in 9.4.4: [AzureMonitor: Fix query variable migration](https://github.com/grafana/grafana/pull/63991 ) that might help for you @mwilfried 

@mfmbarros is what you're seeing exactly the same on 9.4.7 or are there any small differences?

**Comment by mwilfried** [comment]
@mellieA  I have the exactly same issue in 9.4.7 also.
Regarding the fix, sorry I don't understand the workaround -_-

**Comment by mfmbarros** [comment]
@mellieA it looks like the same as @mwilfried reported:

![Screenshot 2023-04-06 at 23 07 22](https://user-images.githubusercontent.com/14133426/230504699-9640cef8-8c60-4590-9089-acf4f132714c.jpeg)

**Comment by bossinc** [comment]
@mwilfried @mfmbarros https://github.com/grafana/grafana/pull/63991 will be in the 9.4.8 release. This issue is fixed in the main branch.
