### ISSUE TITLE
Check Layout and unify with or add Stack component

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#66035]
In grafana-ui we have a `Layout` component which can be used separately and is also used in `HorizontalGroup` as well as `VerticalGroup`. `Layout` is currently not shown as a component in Storybook.

Additionally there are two `Stack` components: 
- First one is used in some plugins (please find the component [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/parca/QueryEditor/Stack.tsx)).
- Second one from [grafana-experimental](https://github.com/grafana/grafana-experimental/blame/main/src/QueryEditor/Stack.tsx) and it is widely used in grafana

**In order to set better standards we need to do the following:**
- [ ] Check what these components `Layout`, `HorizontalGroup`, `VerticalGroup` offer
- [ ] Check how `Layout`, `HorizontalGroup`, `VerticalGroup` are used in grafana (features and plugins)
- [ ] Clarify what standard is required with the UI/UX team
- [ ] Document the standard
- [ ] Check whether the `Stack` components are providing something that is not yet covered by the available components in grafana-ui
- [ ] If applicable add `Stack` to grafana-ui and limit options by setting props
- [ ] If applicable add documentation for the new `Stack` component

**Comment by staton-hyse11** [comment]
@L-M-K-B was this complete when we created the new Stack component?

**Comment by Clarity-89** [comment]
Yes, this is completed.
