### ISSUE TITLE
Images in the email Alerts are not redenred correctly

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#6604]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v4.0.0-beta1 
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.6
- What did you do?
Setup Alerts to email me.
- What was the expected result?
Fully rendered image in the email
- What happened instead?
Got this:
![image](https://cloud.githubusercontent.com/assets/5177657/20355011/8589af36-abe5-11e6-9dca-bbe609dfff0d.png)

I was expecting to see full image but looks like it is missing name an value. I am using S3 to store images (probably does not matter but want to make sure this is reported as well)

**Comment by torkelo** [comment]
you need to install font pages, google font packages phantomjs centos

**Comment by AGirin** [comment]
I appreciate the fast response. But it is installed. How do I actually verify that grafana finds that font?

**Comment by torkelo** [comment]
its not grafana that needs to find it, its phantomjs

try this 
```
yum install fontconfig
yum install freetype*
yum install urw-fonts
```

**Comment by AGirin** [comment]
That worked. I was missing freetype* and urw-fonts. Thanks a lot!

**Comment by tmalkowski** [comment]
No possibility of these becoming prerequisites, is there? I have a very nice cluster all dynamically built out, with minimal packages. Kind of weak that I have to install prerequisites manually. Would much rather have had these added as dependencies when this feature rolled out, so the prerequisites would be automatically installed.

**Comment by torkelo** [comment]
@tmalkowski Yes, I agree, might be some issue with the packages not being available on all platforms/archs so not not sure I want to make that rpm change right before stable release (doing 4.3 stable release soon). 

But created a PR with the rpm change, https://github.com/grafana/grafana/pull/8442 will merge after next stable release.
