### ISSUE TITLE
Time Series: variable point size

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#66048]
Hi,
currently, the point size of the graph can only be set statically.
Is there the plan to implement the point size dynamically, depending on a query column?
This is possible for example in XYChart.

Thanks for the answer

**Comment by mellieA** [comment]
@yulipumal I don't see any open feature requests or gh issues for a change like this yet. You can [open a feature request in Discussions](https://github.com/grafana/grafana/discussions) to submit the idea.
