### ISSUE TITLE
Alert rule buttons overflow to a new row

### ISSUE THREAD

**Issue by nkkowa** [grafana/grafana#66044]
**What happened**:

With the introduction of the new Copy Alert button in 9.4, on certain displays, the alert rule buttons overflow to a new row when zoomed out. Ex on a 1920x1080p external display at 90% zoom:

![image](https://user-images.githubusercontent.com/83962080/230133513-ad7eac86-a9e5-49e8-aee4-ca46f8717e86.png)

This is present in the 'Groups', 'List', and 'State' views.

**What you expected to happen**:

The buttons to take up one row, like they do on my main Macbook screen:
![image](https://user-images.githubusercontent.com/83962080/230132687-91677b36-5f4e-485c-aa95-bd19b4d0aba4.png)

**How to reproduce it (as minimally and precisely as possible)**:

Not sure precisely how to reproduce aside from creating an alert rule and testing with various display sizes.

**Anything else we need to know?**:

Adjusting either the width or padding by two pixels seems to fix it.

**Environment**:
- Grafana version: v9.4.7 (4add91f03d)
- Data source type & version: N/A
- OS Grafana is installed on: Debian 11
- User OS & Browser: MacOS Ventura, Chrome 111.0.
- Grafana plugins: N/A
- Others: N/A

**Comment by soniaAguilarPeiron** [comment]
The Copy and Delete buttons have been relocated to a `More` button in this [PR](https://github.com/grafana/grafana/pull/74522/files#diff-93c8fc7b76c103cca8ce8b1f1c3a8cdd790b833e76fefdc3de0937cdeee151c6R150-R155). Thanks to this change, the overflow issue has been resolved



![Image](https://github.com/grafana/grafana/assets/33540275/4a09ff9a-c139-4565-acb9-33f4e8919fa6)
