### ISSUE TITLE
Some Contact Points show "no attempts" even though alerts were delivered

### ISSUE THREAD

**Issue by VikaCep** [grafana/grafana#66058]
**What happened**:

The Health, Last delivery attempt and Duration columns show empty status/no attempts after a notification policy stops using that contact point even though it fired earlier.

Notice the "OK" status after a notification was sent for "Email contact point"
<img width="1203" alt="Screen Shot 2023-04-05 at 15 21 08" src="https://user-images.githubusercontent.com/6271380/230170667-791de485-2b5c-4ac4-88e2-66b311a00fd7.png">

Now it shows "No attempts" after the notification policy changed its contact point even though it was successfully executed a few minutes ago.
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/6271380/230170610-c025e409-e830-4c9d-b0bf-9c0daaa00bc9.png">

**What you expected to happen**:

The last status for a contact point should not be lost.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a contact point and a notification policy that uses it. 
2. Corroborate that the contact point is used when the alert is firing and the Contact Points table shows an OK health status.
3. Change the notification policy to use a different contact point and wait for the next evaluation. 
4. Check the status of the contact point in the Contact Points table. Health shows `No attempts` even though the contact point was used correctly earlier.

**Anything else we need to know?**:
- Grafana version: 9.5.x

**Comment by grobinson-grafana** [comment]
I have noticed similar behaviour when updating contact points too. I think what is happening is that whenever the Alertmanager configuration is changed it is also reloaded, and when this happens the health of each contact point is reset. @santihernandezc does this seem plausible?

**Comment by yuri-tceretian** [comment]
Yes, when the configuration is reloaded, the integrations, routes are re-created.
