### ISSUE TITLE
No Alerts on 1 min query

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#6605]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v4.0.0-beta1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.6
- What did you do?
Setup Alert to run every 60 seconds with this parameters:

![image](https://cloud.githubusercontent.com/assets/5177657/20355179/15705ca8-abe6-11e6-9435-1b376c1c7e6b.png)

- What was the expected result?
I was expecting to get email alerts
- What happened instead?
Nothing. No alerts were generated. I changed 1m to 5m in the conditions and alerts came in on the next threshold crossing. 

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
What's the metric data response when you hit Test Rule (with duration set to 1m). After you hit Test Rule, expand the response until you see that data points that came from the query

**Comment by AGirin** [comment]
Well - this is exactly what I see

![image](https://cloud.githubusercontent.com/assets/5177657/20359186/58989c4e-abf4-11e6-885d-5990e58d4ad2.png)

The rule evaluates to false even though it suppose to evaluate to true. I think it is a race condition between 60 sec in Evaluation and 1m in Conditions.

**Comment by torkelo** [comment]
you need to expand the logs so you can see what the metric queries are returning

**Comment by torkelo** [comment]
Below Test Rule you can expand the result so you see why the conditions result in false

**Comment by AGirin** [comment]
I know :-). But why does it work with 5 min interval? Same stuff but it alerts if I change to 5 m. I'll get you the exact data points with 1m in a moment.

**Comment by AGirin** [comment]
![image](https://cloud.githubusercontent.com/assets/5177657/20360547/bde2a306-abf9-11e6-898d-de8a281b82c5.png)

**Comment by AGirin** [comment]
The above happened at the moment I got this threshold crossing:

![image](https://cloud.githubusercontent.com/assets/5177657/20360582/e4ccc9ce-abf9-11e6-928c-bde9cbb5961d.png)

**Comment by AGirin** [comment]
So... I think it might be related to this?

![image](https://cloud.githubusercontent.com/assets/5177657/20360618/0853c640-abfa-11e6-932a-742fcbc09711.png)

Basically it says AND - does it mean that BOTH metrics need to cross the threshold? Can I change it to OR?

**Comment by AGirin** [comment]
I removed one query - and no alerts still. Not sure what I am doing wrong.

**Comment by torkelo** [comment]
test image from the test rule shows only zeros being returned from your metric query. 

regarding OR, we are working on adding that

**Comment by AGirin** [comment]
But it does not make sense - I see data point and run test - and it gives me all 0s? How does grafana then displays it if it got 0? You see what I mean?

**Comment by AGirin** [comment]
Again - just switched condition to 5m and it magically works. Something about that 1m does not work properly. I also mentioned that 5m is the default. Any reason for that? Maybe it was never tested with 1m?

**Comment by AGirin** [comment]
After switching to 5 m:

![image](https://cloud.githubusercontent.com/assets/5177657/20363010/36e90228-ac03-11e6-96bb-a45b75a399aa.png)

**Comment by torkelo** [comment]
I am gettting tired of asking for the data returned by the 1m query, think I have asked 3 times now, without it I cannot identify if this is a simple problem with your query or not. I mean we have hundreds of rules with 1min or below wokring fine, so it's likley something with the query. Have you Hit the test rule button and expanded the metric data points when using 1m ? what are the datapoints returned? Are they greater than 1? If your using avg as the reucer and getting 5 values back and only one is 1 then the average is below 1

**Comment by torkelo** [comment]
what does your query look like?

**Comment by torkelo** [comment]
This is in the issue template:

very important info that really helps me help you
> IMPORTANT If it relates to metric data viz:
An image or text representation of your metric query
The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by AGirin** [comment]
Sorry - did I not post it above in this thread? You might have missed it or I am not getting what you need to see. I'll repost again in a couple of minutes.

**Comment by AGirin** [comment]
This is actually what I posted: 

![image](https://cloud.githubusercontent.com/assets/5177657/20364141/9e76e3d4-ac07-11e6-8c2d-b9bf8c861e76.png)

**Comment by AGirin** [comment]
And these are my exact queries:

![image](https://cloud.githubusercontent.com/assets/5177657/20364205/dae8826e-ac07-11e6-94fc-043cec79142d.png)

**Comment by torkelo** [comment]
well as I said when you pasted that was that it shows only showed zeros, so am not sure what you expect Grafana to do when your query only returns zeros :( 

Your using a nonNegativeDerivate function which requires a time range so it gets two values (so it can calculate a derivative) 

ave you tried putting the dashboard time range to now - 1m ? do you get any values?

**Comment by AGirin** [comment]
Well - I don't get any results with now - 1m. I guess my confusion comes from the fact that the actual graph shows me the values (since it has previous value I guess) but Alert was not picking this up - probably because of NonNegativeDerivative function. I think we can stop here. I'll just use 5 min as it works in my case. 

Maybe it needs to be stated in the documentation somewhere to avoid confusion for other people.

Thanks a lot for taking time to troubleshoot it with me. I really appreciate it.

**Comment by torkelo** [comment]
I think that the nonNegativeDerivate is documented in the graphite docs, and you could have easily tested to change time range in the dashboard, and the Test rule features showed you very clearly that It was you query that was at fault,  it shows your exactly what graphite is returning,
