### ISSUE TITLE
Implementation is not saved to Alertmanager datasource

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#66056]
**What happened**:
When user creates a new data source of type Alertmanager, the UI let user choose the implementation: Mimir, Cortex or Prometheus.  
![image](https://user-images.githubusercontent.com/25988953/230164413-d8b9ad21-9c31-4c40-8631-19f711759d4d.png)

When the user changes the value in dropbox it sets a field `implementation` in the data source's `jsonData` field. However, when user does not change the dropdown, the field is not populated.

In the backend, the absence is treated as Prometheus implementation. 

**What you expected to happen**:
The field `jsonData.implementation` should always be populated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Related to https://github.com/grafana/grafana/pull/63676/files

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sladyn98** [comment]
Here the default value for jsonData.implementation is always set to mimir. 

```
<div className="gf-form-inline">
          <div className="gf-form">
            <InlineFormLabel width={13}>Implementation</InlineFormLabel>
            <Select
              width={40}
              options={IMPL_OPTIONS}
              value={options.jsonData.implementation || AlertManagerImplementation.mimir}
              onChange={(value) =>
                onOptionsChange({
                  ...options,
                  jsonData: {
                    ...options.jsonData,
                    implementation: value.value,
                  },
                })
              }
            />
          </div>
        </div>
```

@yuri-tceretian Do we want it to be prometheus by default ? because It is always populated even if it is null

**Comment by yuri-tceretian** [comment]
I think it is ok if the default implementation is Mimir. When I was testing, UI displayed Mimir but the POST payload did not have any field.
