### ISSUE TITLE
Row Hover Hit Area (v4)

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#6607]
On rows following a smaller row, the menu being triggered when hovering left of the row title is for the row above it. 

![row-hover-area](https://cloud.githubusercontent.com/assets/2886187/20359691/f18ee1c4-abfe-11e6-9d35-db8390079c3c.gif)

![screenshot 2016-11-16 13 20 56](https://cloud.githubusercontent.com/assets/2886187/20359893/bf47b7c6-abff-11e6-8823-13a6731c7775.png)

**Comment by torkelo** [comment]
well the row slide menu and dots icon is below the row header so not a critical issue but still annoying for those who use visible row headings. 

No idea how to solve it though. maybe overflow hidden on the row menu (but on hover turn on overflow auto)

**Comment by torkelo** [comment]
closing this as the row menu is going away in 5.0
