### ISSUE TITLE
[Feature Request] Allow to customize Quick Ranges Menu

### ISSUE THREAD

**Issue by n-zeed** [grafana/grafana#6608]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
   Grafana v3.1.1 (commit: a4d2708) 
- What datasource are you using?
  Graphite
- What OS are you running grafana on?
  CentOS
- What did you do?
   Change the time range frequently using the quick ranges option
- What was the expected result?
   Allow for customization so that I can add my own ranges
- What happened instead?
   I have defaults that many I don't use and ones I require are not present

Please consider Adding a way to customize the quick ranges menu for a user defined one. Thanks!

**Comment by torkelo** [comment]
yes, definitely something we want to do in the future, 

duplicate  https://github.com/grafana/grafana/issues/2417

**Comment by Sulomus** [comment]
Any updates on this yet?

**Comment by litao09h** [comment]
Any updates on this yet?
