### ISSUE TITLE
Docs feedback: /fundamentals/_index.md

### ISSUE THREAD

**Issue by AyanBhadury** [grafana/grafana#66081]
Add other open-source products of the Grafana ecosystem similar to Loki & Tempo.

- Grafana Mimir
- Grafana onCall

**Comment by chri2547** [comment]
PR https://github.com/grafana/grafana/pull/72042 addresses this issue.

**Comment by chri2547** [comment]
PR https://github.com/grafana/grafana/pull/72042 merged and backported. Issue closed.
