### ISSUE TITLE
Documentation unclear about required service account roles for Google Cloud Monitoring

### ISSUE THREAD

**Issue by leonboot** [grafana/grafana#66096]
In the documentation for Google Cloud Monitoring, there is a page that epxlains how to authenticate Grafana to Google Cloud Monitoring by creating a service account in Google IAM. It states to then ["choose the roles required by the specific plugin"](https://github.com/grafana/grafana/blob/main/docs/sources/datasources/google-cloud-monitoring/google-authentication/index.md?plain=1#L35). But this is the documentation for that specific plugin; the Google Cloud Monitoring data source. The documentation link for that data source actually links to this page.

Shouldn't this page provide the reader with the actual GCP roles required for the Grafana data source plugin to do its work? I cannot find this information anywhere else.

**Comment by mellieA** [comment]
@leonboot I think the information you're looking for is further down that page here: 

https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/#configure-a-gcp-service-account

**Comment by asimpson** [comment]
Closing this now since it sounds like all was resolved. If that's untrue feel free to re-open @leonboot
