### ISSUE TITLE
[Feat Req]: Graph Panel - Support for mixing alert thresholds & display only thresholds 

### ISSUE THREAD

**Issue by CyBeRoni** [grafana/grafana#6610]
Currently in 4.0.0-beta, thresholds are disabled if you have an alert enabled. (Presumably because the alert uses a threshold to display where it'll fire?)

That doesn't make a lot of sense to me because there can only be one alert per panel, but multiple thresholds. I think instead, having an alert should fill in an unmodifiable threshold and still allow me to set more.

Example use-case: response-time monitoring where you want to show in the graph what is an 'ok' response time and what is 'too high', yet only send alerts when the response time is exceeded by some margin.

**Comment by torkelo** [comment]
think mixing will be confusing, so I am inclined to leave it as it is.

**Comment by CyBeRoni** [comment]
How would it be confusing?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
