### ISSUE TITLE
Too many tab crashes with Loki as a datasource

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#66101]
**What happened**:
After the upgrade to `9.4.3` I've been experiencing a lot of tab crashes of the `Explore` view with a Loki datasource.
Even for queries for a short time, for example `Last 5 min`.
There a couple of `his page is slowing down firefox...` warnings from Firefox and a tab crashes finally.

This happens for queries that have been OK before the upgrade.

**What you expected to happen**:
No tab crashes, query results as usual.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser: UIbuntu, Firfox 111.0.1 (64-bit)
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@hawran can you share an example of the query and expected volume of results

What does the resource utilization look like in the browser at the time of the crash, a HAR file could be helpful to debug this.

**Comment by hawran** [comment]
> @hawran can you share an example of the query and expected volume of results
> 
> What does the resource utilization look like in the browser at the time of the crash, a HAR file could be helpful to debug this.

Hi, sorry for the delay.

Meanwhile we've upgraded to `9.5.` version (on `9.5.3' at the moment) and it seems to be OK now, so I'm closing the issue.
