### ISSUE TITLE
[Bug Report] | Table panel scroll bug when has lots of columns

### ISSUE THREAD

**Issue by dannyZhou** [grafana/grafana#6611]
env: 
- OS: linux 
    - distribution: archlinux 
    - kernel version: 4.8.6-1-ARCH
- Browser: 
    - chrome version: 55.0.2882.0 (Official Build) dev (64-bit)
- Grafana version:  
    - command: grafana-server -v 
    - result: version 3.1.1 (commit: v3.1.0+20-g2bfccd7)
- Install method:
    - pacman -S grafana 
 - DataSource:
    - influx:
        - version: v1.1.0

Step:
1. Add dataSource.
2. New a dashboard.
3. Add a table panel. 
4. Add a query: `SELECT "count" FROM "autogen"."orders" WHERE  time > now() - 1d GROUP BY "restaurantName"`.
5. Horizontal scroll the table bar.
6. Horizontal scroll the browser bar.
![screenshot from 2016-11-17 02-54-23](https://cloud.githubusercontent.com/assets/6329191/20376195/85c86a34-acbf-11e6-8a70-cf4d6ca3cc08.png)

Info: 
- I have more than 300 restaurantName. 

Actual:
![screenshot from 2016-11-17 02-57-56](https://cloud.githubusercontent.com/assets/6329191/20376234/d309478c-acbf-11e6-8bcf-c2399265c3fa.png)

Expected:
1. Do not have browser bar.
2. The table title should scrolled with table body.

**Comment by torkelo** [comment]
The table panel is not built to support horizontal scrolling, the columns must fit with in the bounds of the table. You will have to split the table panel into multiple. 

This feature request might help you (if it gets implemented)
https://github.com/grafana/grafana/issues/5309

Or this:
https://github.com/grafana/grafana/issues/5309

**Comment by kim0** [comment]
Not really sure how this is not regarded as a bug tbh :) .. if `The table panel is not built to support horizontal scrolling`, then this is precisely the bug! Imagine if excel could only display ten columns. Thanks for Grafana though, great code.

**Comment by torkelo** [comment]
Grafana dashboards are usually designed with having all information visible and no scrolling requires this design focus has made it incredibly popular for TVs for example , this was one reason that horizontal scroll was not deemed essential when the table panel was first build . And no PR that adds support for horizontal scroll has been submitted yet

**Comment by b42thomas** [comment]
there should still be some control over columns header. right now you can't format the column widths which makes it difficult sometimes to display the data in an easy way to read.  It at least makes sense to allow headers to scroll in the edit view of a table because other I have switch back to a different database query interface to pull out all the columns from a table to see what a table consists of.  that whole process defeats the point of having a single, easy to use data query interface and visualizer.
