### ISSUE TITLE
CloudWatch LogGroup variable giving error: Unexpected token 'u', "unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by anuj-scanova** [grafana/grafana#66141]
**What happened**:
Creating a variable to display list of CloudWatch log groups to select from
<img width="796" alt="Screenshot 2023-04-06 at 10 07 27 PM" src="https://user-images.githubusercontent.com/105233146/230441873-7d7070f2-24b6-43ce-a80e-7ea8ff0a5d6f.png">

But it is giving error when **Query Type** is changed to **Log Groups**
<img width="790" alt="Screenshot 2023-04-06 at 10 08 06 PM" src="https://user-images.githubusercontent.com/105233146/230442071-2d740ab8-5aac-4a0a-b6e3-9635a2bac299.png">

Checked network tab which is calling the endpoint `/api/datasources/1/resources/all-log-groups?region=ap-south-1&logGroupNamePrefix=` with response
```
unexpected error InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DescribeLogGroupsInput.LogGroupNamePrefix.
null
```

**What you expected to happen**:
Log groups should be displayed in the variable without error

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a variable with Query Type **Log Groups**

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2.0 (c7eea48209)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux (Ubuntu)
- User OS & Browser: Mac OS (Google Chrome)
- Grafana plugins: 
- Others:

**Comment by mellieA** [comment]
@anuj-scanova there is a fix for this in the latest release of 9.2.x

https://github.com/grafana/grafana/pull/57483
