### ISSUE TITLE
Timestamp not supported in InfluxDB Metrics Push

### ISSUE THREAD

**Issue by mattsimonsen** [grafana/grafana#66152]
I believe that I’ve found a mistake in https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-influxdb/push-from-telegraf/ based on feedback from Grafana support.

The mistake is that in influxdb protocol to Grafana Cloud does not support timestamps at all. So, there is no backfilling of data, to Cloud Prometheus/Mimir.

I’d be happy to find I’m wrong, however I could not get the backfill to work and believe I tried every possible way to make it work.
The docs pretty clearly say that you can in fact send a timestamp in nanoseconds, with storage in milliseconds. But that isn’t true, according to Grafana cloud support.

**Comment by adamduren** [comment]
@mattsimonsen I'm encountering something similar but I find that timestamps work as long as they're as recent 10 minutes from now. Anything after that gets rejected. Did you have any luck?

**Comment by mattsimonsen** [comment]
I was unable to ever insert historical data via InfluxDB & at a conference one of the Mirmir maintainers seemed to confirm this was expected on Grafana cloud. 

I never heard anything back and the docs still appear to be wrong.
