### ISSUE TITLE
Grafana fails to load

### ISSUE THREAD

**Issue by hayk96** [grafana/grafana#66156]
**Grafana failed to load UI**:
After upgrading Grafana from version `9.3.1`  to `9.4.*` getting the following error on the browser  

```
If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.
. . . 
```
My `grafana.ini` file includes the following lines as well:
```
[server]
domain = example.com
root_url = https://example.com/
...
```

Grafana service is running behind `ingress-nginx-controller`. This issue is visible in all `9.4.*` releases.

**Environment**:
- Deployment method: [Helm](https://github.com/grafana/helm-charts/tree/main/charts/grafana) / Kubernetes
- Grafana version: 9.4.*
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS/Chrome
- Grafana plugins: N/A

**Comment by mellieA** [comment]
@hayk96 you might find some help in our tutorial at https://grafana.com/tutorials/run-grafana-behind-a-proxy/ or the community at community.grafana.com

There are other potential causes for this error as well, including unsupported browsers

**Comment by hayk96** [comment]
Thanks, I'll check it again. Actually, I came here after discussing this in the community :)

**Comment by sachasmart** [comment]
Did you find solution for this? I've been running into this on a Kubernetes cluster on an off with a Traefik Ingress Route. Nothing on the Grafana docs have solved this

**Comment by hayk96** [comment]
I discovered that this issue appears when I use Cloudflare on top of it. I found [this issue](https://github.com/grafana/grafana/issues/63934) that really helped me. Disabling `JavaScript Auto Minify` from CF for Grafana helped.

**Comment by arashkhavari** [comment]
I was using something other than Cloudflare and I had a problem
My reverse proxy was nginx and I had this problem
I solved the problem by putting this option in my location blocks
`proxy_buffering off;`
