### ISSUE TITLE
Traffic Manager resources for Azure Monitor are not showing up in the resource picker

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#66150]
**What happened**: I tried selecting a traffic manager resource from the resource picker UI and the resource was not there:

![image](https://user-images.githubusercontent.com/20448042/230475546-78598ae5-5b0c-4fdb-812f-f2d1e4b9f815.png)

However, if I type the resource directly in the search box, the resource shows up:

![image](https://user-images.githubusercontent.com/20448042/230475640-07f334c2-75df-4b58-8e20-30edb8eeac88.png)

**What you expected to happen**: for traffic manager resources to show up on the UI without the need to type the name in.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a traffic manager resource on Azure Monitor
2. Try to select the above resource via the dropdowns in the resource picker.

**Anything else we need to know?**:

I was able to verify that the first ARG query made to get the number of resources per resourceGroup is correct (3), however, when I run the second ARG query (one that actually fetches the resource names), I am only able to see two resources and traffic manager profile resource is missing.

I was able to narrow down that the reason the resource is missing is because of the additional region filter done in the second query (I removed most namespaces from the type filter for easier reading):

```
resources
| where id hasprefix "jcolladokuri-test"
| where type in ("microsoft.network/trafficmanagerprofiles","microsoft.network/expressroutecircuits","microsoft.network/vpngateways") and
location in ("eastus","eastus2","westus","centralus","northcentralus","southcentralus","northeurope","westeurope","eastasia","southeastasia","japaneast","japanwest","australiaeast","australiasoutheast","brazilsouth","southindia","centralindia","westindia","canadacentral","canadaeast","westus2","westcentralus","uksouth","ukwest","koreacentral","koreasouth","francecentral","francesouth","australiacentral","southafricanorth","centraluseuap","eastus2euap","australiacentral2","southafricawest","uaecentral","uaenorth")
 ```

Seems like the region "global" is missing in the filter, which is the region for my traffic manager profiler resource.

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: Azure Monitor
- OS Grafana is installed on: NA
- User OS & Browser: Windows, Edge
- Grafana plugins: NA
- Others: NA

**Comment by aangelisc** [comment]
This should be fixed by grafana/grafana#66502 and should be available in the next 9.4.x release 😊
