### ISSUE TITLE
Repeating Panels/Rows do not function correctly with template variables based on Cloudwatch datasource

### ISSUE THREAD

**Issue by bfhobbes** [grafana/grafana#6615]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0.0-beta1
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
Docker for Windows and Amazon ECS
- What did you do?
I attempted to use the repeat panel or repeat row functionality based on a multivalue templating variable returned using dimension_values() ( problem also exhibits using ec2_instance_attribute )
- What was the expected result?
A Single graph for each of the template variable values.
- What happened instead?
A graph appears for each value of the template variable, but each graph includes a trace for each of the values. 

I originally encountered this trying to use ec2_instance_attribute to pull out the instance ID's for a particular autoscalinggroup, but to simplify reproduction I've replicated the same issue using a simpler dimension_keys cal to list all EC2 instances and show a graph of CPU utilization. ( Test dashboard attached 
[CloudwatchPanelRepeatProblem.zip](https://github.com/grafana/grafana/files/596577/CloudwatchPanelRepeatProblem.zip) )

**Comment by torkelo** [comment]
did you try to change the selected values in the template variable or reload the dashboard after setting repeat option? 

@mtanda any idea what could be the cause? scoped vars is used in the relevant places, so not sure why it wont work for @bfhobbes

**Comment by mtanda** [comment]
@torkelo sorry, this is a bug caused by https://github.com/grafana/grafana/pull/5003 .
I should check the repeat option whether the datasource plugin should expand template variables or not.
I make a PR (https://github.com/grafana/grafana/issues/6618) for fixing this issue.

**Comment by bfhobbes** [comment]
@torkelo - I changed values, and saved the dashboard and refreshed the page but got the same results. It sounds like @mtanda has a handle on the problem though. Thanks!!
