### ISSUE TITLE
Render graphic from snapshot lost all colors from legend

### ISSUE THREAD

**Issue by Arkote** [grafana/grafana#6616]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
RHEL
- What did you do?
render graphic from snapshot
- What was the expected result?
- What happened instead?
lost all colors from legend
this only happens when rendering a snapshot, a variety of settings, do not bring results.**

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

![1_1_1478263631674_1478264349516](https://cloud.githubusercontent.com/assets/14886425/20380045/a081a480-acb0-11e6-97a6-bc5fd4b782b4.png)

**Comment by torkelo** [comment]
strange, never seen this reported before for RHEL so something unique about your setup must be at work.

try installing font packages

**Comment by Arkote** [comment]
@torkelo 
Fonts not resolve problem.
Probliem fix if i check Legend -> Options -> To the right.
If legend align left (As table or not) - colors is lost.

**Comment by torkelo** [comment]
strange, working for others, what version of RHEL are you using and what font packages have you installed?

**Comment by Arkote** [comment]
@torkelo 
Version: Linux version 2.6.32-573.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Wed Jul 1 18:23:37 EDT 2015
Fonts: font-awesome-4.7.0
what else packages you recommend to install?

**Comment by torkelo** [comment]
```
yum install fontconfig
yum install freetype*
yum install urw-fonts
```

**Comment by Arkote** [comment]
@torkelo 
I install this packages, but nothing change, no colors. This problem only in snapshots, if i render from dashbord - all good.
Help please :(

**Comment by Arkote** [comment]
@torkelo 
I try to update for 4 version grafana, try to install to another unix\windows OS, but problem still actually. 
Data source also does not matter, the problem persists on a standard source - Grafana -. From dashboard render is ok, from snapshot - no colors.

**Comment by Arkote** [comment]
@torkelo
I got to reproduce the problem in http://play.grafana.org/
1) I got snapshot from this dashboard: http://play.grafana.org/dashboard/db/1-promcon-dashboard?panelId=1&fullscreen
2) This snapshot: http://play.grafana.org/dashboard/snapshot/aj5u5YeaQBX6M9pGflivdrek96BsbMb2
3) Try to render image from this graph, and you get the image without legend colors: http://play.grafana.org/render/dashboard-solo/snapshot/Z6gm9GeCXjdJ6105nvgob6o3eznLr2Nb?from=1484905377133&to=1484907177134&panelId=1&width=1000&height=500

This problem apears if colors in dashboard not selected manually and then in time creating snapshot aliasColors:{} is empty,

please reopen this bug, it's critical problem in my project, Thanks.
