### ISSUE TITLE
[Feat Req Table Panel]: Column style that preserves formatting/indentation (like pre tag)

### ISSUE THREAD

**Issue by Elufimov** [grafana/grafana#6617]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 
3.0.1
- What datasource are you using? 
Elasticsearch
- What OS are you running grafana on? 
Ubuntu 14.04
- What did you do? 
Visualize logs with stacktraces
- What was the expected result?
Stacktrace message render with indents and hyphenations
- What happened instead?
Stacktrace message render in one line

![](https://i.gyazo.com/74762cab5e9739b8d5d4c85d880b2e00.png)
![](https://i.gyazo.com/6aa788f3116894ca189c3f64e1505289.png)

**Comment by torkelo** [comment]
We can get it to fit on one line, by trimming the text, 

https://github.com/grafana/grafana/issues/5475

**Comment by Elufimov** [comment]
I am so sorry about it! I was confused the expected and current result! I edited issue body.

**Comment by jonesn** [comment]
+1
