### ISSUE TITLE
Users see "Permission denied" every time they load explore & new dashboard pages

### ISSUE THREAD

**Issue by erin-noe-payne** [grafana/grafana#66181]
**What happened**:

I have users reporting that they see a "Permission denied" popup every time they load the explore page. It does not impact their ability to do anything on the page, but its confusing. I cannot recreate; I am an org admin, they are not.

![image (2)](https://user-images.githubusercontent.com/918178/230643870-daa6471c-0835-441b-ac44-8dc248914adf.png)

What is happening:
- In 9.4, two new calls were added to `useLoadDataSources`. Those locations are [EmptyStateWrapper in explore](https://github.com/grafana/grafana/blob/main/public/app/features/explore/EmptyStateWrapper.tsx#L13) and [NewDashboardPage](https://github.com/grafana/grafana/blob/afc9925dbfa55886cc85a9a2106ed9892d7df239/public/app/features/dashboard/containers/NewDashboardPage.tsx#L13). Previously, `useLoadDataSources` was only called from the [DataSourcesList admin view](https://github.com/grafana/grafana/blob/afc9925dbfa55886cc85a9a2106ed9892d7df239/public/app/features/datasources/components/DataSourcesList.tsx)
- This makes a call to `/api/datasources`. This endpoint is access controlled in at least 2 places [[1](https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L90), [2](https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L395)]. If RBAC is disabled, like in my deployment, access is limited to org admins only.
- All users who are not org admins (most of them), get a 403 response from the server + permission denied popup.

**What you expected to happen**:

No permission denied popups. UX exposed to all users on explore & new dashboard pages doesn't depend on endpoints only available to org admins.

**How to reproduce it (as minimally and precisely as possible)**:

- Run grafana RBAC disabled
- Login as a user who is not an org admin
- Go the the explore page
- See permission denied.

**Comment by ifrost** [comment]
I was able to reproduce it in current main, but it renders an empty page. The same happens when a user tries to create a new dashboard (cc @grafana/dashboards-squad)

**Comment by ifrost** [comment]
cc @grafana/grafana-authnz-team

**Comment by mgyongyosi** [comment]
Hi @erin-noe-payne,

Thank you for the report, we investigated and fixed the "Permission denied" issue. It will be available in the next release.

By the way, is there any particular reason you haven't enabled RBAC yet?

**Comment by erin-noe-payne** [comment]
> By the way, is there any particular reason you haven't enabled RBAC yet?

My understanding from [the docs](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/) is that RBAC is only available in Grafana Enterprise / Cloud.

**Comment by mgyongyosi** [comment]
@erin-noe-payne Thank you for the feedback! We are gonna update our documentation to better surface the difference between RBAC in OSS and in Enterprise version. 

To clarify things, in OSS if you turn on RBAC (which is turned on by default) then it uses the underlying role-based access control functionality, but only with the basic roles (Admin, Editor, Viewer), on the other hand Grafana Enterprise adds additional features like provisioning roles, creating custom roles, assigning roles like Data Source Reader to users, teams, and service accounts.

Turning RBAC on in OSS does not have any impact.

More info: 

- https://grafana.com/blog/2022/06/27/new-in-grafana-9-role-based-access-control-rbac-is-now-ga#how-the-grafana-rbac-feature-benefits-users
- https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/#basic-roles
