### ISSUE TITLE
v8.5 dashboard update HTTP API does not respect `id` or `uid` set in the request

### ISSUE THREAD

**Issue by natewang341124** [grafana/grafana#66194]
**What happened**:
[v8.5 Grafana HTTP update API](https://grafana.com/docs/grafana/v8.5/http_api/dashboard/#create--update-dashboard) doesn't seem to respect the `id` or `uid` set in the payload from an existing dashboard. Instead, it updates a dashboard with the same `title` instead.

Here is my attempt updating title of a dashboard to be the same as another dashboard **in the same folder**:
![Screenshot 2023-04-07 at 5 33 17 PM](https://user-images.githubusercontent.com/10676667/230695557-a92423c9-4555-4d3a-a870-6b22d8e20aea.png)
(as you cam see in the last print statement, `O3Pnl5Y4z` was the uid of the dashboard I'm trying to update and used in the json payload, `hwq-lqb4k` is what actually got updated)

Here is another attempt, the only difference from the previous run is that I did not update the title of the dashboard:
![Screenshot 2023-04-07 at 5 35 31 PM](https://user-images.githubusercontent.com/10676667/230695652-d5e77044-81c2-4324-b294-88f6eebc83a5.png)

**What you expected to happen**:
when I update a dashboard, it should find the dashboard via `id` or `uid` in the request payload.

**How to reproduce it (as minimally and precisely as possible)**:
1. create two dashboards with different titles (A and B)
2. update the title of A to B, while specifying A's `id` and `uid` in the payload, with `overwirte` to be `true`
3. observe that the update response is success(200), but with B's `id` and `uid` returned.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
"@grafana/data": "^8.5.10",
"@grafana/experimental": "^1.0.2",
"@grafana/runtime": "^8.5.10",
"@grafana/ui": "^8.5.10",
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
hi and thanks for creating this issue @natewang341124 

can you share your JSON payload? I am having trouble using the endpoint `/api/dashboards/db` (PUT) at the moment

thank you

**Comment by tonypowa** [comment]
ps. to safely share your data, you can copy a modified version of the original data using the panel --> more --> get help workflow in the panel's dropdown menu

![alt text](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by tonypowa** [comment]
👋 
if the problem is still relevant, feel free to reopen providing the requested info
