### ISSUE TITLE
scripted dashboard for panel thresholds

### ISSUE THREAD

**Issue by chenatu** [grafana/grafana#6619]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0.0
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 6.5
- What did you do?
develop scripted template to set threshold for graph panel
- What was the expected result?
set threshold array by scripted dashboard
- What happened instead?
panel threshold is reset to empty array by `public/app/features/model.ts` at line 508

use `_.isUndefined()` to check whether `panel.thresholds` is undefined.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
just specify a schemaVersion (13 is latest), and none of the schema upgrade logic will run
