### ISSUE TITLE
[Feat Req] Reverse sort option in Grafana Templating query

### ISSUE THREAD

**Issue by andyxning** [grafana/grafana#6620]
- [ ] Bug report
- [-] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.0
- What datasource are you using?
InfluxDB 0.13
- What OS are you running grafana on?
Debian Jessie
- What did you do?
When using InfluxDB in Grafana Template, as InfluxDB can not work with SHOW TAG VALUES and ORDER BY time, so we can not make the result in descending order. It seems by default it is in ascending order. I am wondering if you can add a new option "reverse" for reversing the order of the result according to neither alphabetical nor numerical, just reverse the order. As PR #5129 has added some sorting method, this should not be so difficult. :)
- What was the expected result?
Add a new "reverse" option for sort 
- What happened instead?

**Comment by torkelo** [comment]
think this is best handled by InfluxDB

**Comment by andyxning** [comment]
Yeh. 
* After i seem PR #5129, i think it is easy to add this functionality. 
* This may not only be the problem for InfluxDB, some other datasource may also encounter this.
