### ISSUE TITLE
influxdb null values treated as zero for alert based on avg()

### ISSUE THREAD

**Issue by pabl0rg** [grafana/grafana#6621]
* **I'm submitting a ...**
- [X] Bug report

v4.0.0-beta1
influxDB
ubuntu 16.04

I tried configuring an alert when the last hour's average of a metric is less than 50.  However, it seems that empty time-slot values are being treated as zeros, therefore although the chart shows the metric to be well above 50, the alert fires.

<img width="539" alt="screen shot 2016-11-17 at 3 47 33 am" src="https://cloud.githubusercontent.com/assets/10501896/20384472/991adcde-ac79-11e6-9de0-08c358b47a30.png">

**Comment by pabl0rg** [comment]
I got it to work by setting fill(none) in the query's group-by line (on the metrics tab)

<img width="441" alt="screen shot 2016-11-17 at 4 08 12 am" src="https://cloud.githubusercontent.com/assets/10501896/20385042/7abee1c0-ac7b-11e6-9893-2bbc6331ca4d.png">

I suspect this was just my mistake.  It may be more intuitive when using graphite.

**Comment by donnlee** [comment]
I just got stung by this.  It seems the default is fill(null) which, as you said, totally throws off avg().
Using fill(none) worked for me too.
