### ISSUE TITLE
Unable to log into Grafana after changing password using Change Password function on Grafana page or using the Grafana CLI

### ISSUE THREAD

**Issue by cumcke** [grafana/grafana#66223]
**What happened**:
After resetting the admin password using either the Grafana UI (log in, click on user icon -> Change Password) or using the Grafana CLI and restarting the Grafana pods, I'm unable to log in with either the new or the old password.

**What you expected to happen**:
I expect to be able to log into Grafana with the new password that I created.

**How to reproduce it (as minimally and precisely as possible)**:
The easiest way was in Grafana:
1. Deployed Grafana using the kube-prometheus-stack Helm chart - we have a random generated password created for our users (in this case - NGE4MTFmNTFkNDJiZTlmODFkMDkwMmFk). Was able to confirm that I was able to log in with that password.
2. Click on the User Icon -> Change password.  Updated password to **BrandNewPassword**.
3. Deleted the Grafana pod:
kubectl delete pods -n monitoring v4m-grafana
4. Tried logging in with new password (BrandNewPassword) and get "Invalid username or password" error.
![image](https://user-images.githubusercontent.com/90708015/230982639-1e7b0853-9219-4be4-bc88-e1e4211a044c.png)

I checked the Kubernetes secret for Grafana and it had the new password:
"admin-password":"QnJhbmROZXdQYXNzd29yZA==", (BrandNewPassword)
“admin-user”:“YWRtaW4=” (admin)

I also checked the environment variables on the new Grafana pod and it showed the updated password, as well:
kubectl exec -n monitoring v4m-grafana-79cbdfc558-46m6k – printenv
Defaulted container “grafana-sc-dashboard” out of: grafana-sc-dashboard, grafana-sc-datasources, grafana, init-chown-data (init)
PATH=/app/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=v4m-grafana-79cbdfc558-46m6k
…
**REQ_USERNAME=admin
REQ_PASSWORD=BrandNewPassword**
…

**Anything else we need to know?**:
- Grafana was deployed using the Kube-Prometheus-Stack 41.7.3 and Grafana 9.2.3 (was able to reproduce the error with the latest releases)
- Was able to successfully update the password and the password persisted when done using Grafana 9.0.3.
- In my investigation, I saw error messages like the one below after restarting the Grafana pods - it looks like the password is not being updated everywhere it needs to be updated and causing the account to be locked:
{"error":"too many consecutive incorrect login attempts for user - login for user temporarily blocked","level":"error","logger":"context","msg":"invalid username or password","t":"2023-04-10T18:50:51.453773084Z","traceID":""}
{"duration":"4.023555ms","level":"info","logger":"context","method":"POST","msg":"Request Completed","orgId":0,"path":"/api/admin/provisioning/dashboards/reload","referer":"","remote_addr":"[::1]","size":56,"status":401,"t":"2023-04-10T18:50:51.453989724Z","time_ms":4,"uname":"","userId":0}

**Environment**:
- Grafana version:  Grafana 9.2.3
- Data source type & version:
- OS Grafana is installed on:  Kubernetes (deployed by Kube-Prometheus-Stack Helm chart)
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
It looks like calling that endpoint was introduced by https://github.com/grafana/helm-charts/pull/2062 and it's presumably using the wrong password enough times to get the user rate limited before you're able to provide the correct new password (or you're not persisting the database with the new password when restarting, that's also a possibility when running Grafana as a container).

Can you open a report with https://github.com/grafana/helm-charts ? They have the domain knowledge re: Helm to either help you debug and resolve the problem or make it sufficiently clear to us over here in the Grafana project what we could do to fix this problem 🙂
