### ISSUE TITLE
Datagrid: Column width changes when drag and dropping the column

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#66229]
When dragging & dropping a column in the datagrid the column width adjusts to be the width of the column it got moved to.

Steps to reproduce:
1. Select any column and change the column width as needed
2. drag the same column and drop it at another position

Expected result:
I expected that the column width remains as set before moving the column

Actual result:
The column width adjusts to be the one of the column where the column has been moved (see video)

https://user-images.githubusercontent.com/110845248/231016077-29f464dc-137d-4d3e-8ab4-b4782b264ebf.mov

**Comment by mdvictor** [comment]
Fixed
