### ISSUE TITLE
Datagrid: Select all and delete rows does not delete all at once

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#66225]
When using the select all/delete all functionality of the datagrid, only half of the entries are being deleted. 
It has to be repeated until the whole table is empty.

Steps to reproduce"
1. create a datagrid with several entries
2. click into the in the top left box of the grid
3. perform a right mouse click
4. select "remove all rows"

Expectes result:
I expected all rows to be removed leaving an empty grid

Actual result:
Only half of the rows are being removed and this has to be repeated multiple times until the grid is empty. (see video)

https://user-images.githubusercontent.com/110845248/231008073-8aeeecfd-3bb2-46c2-affd-72de99840a31.mov

**Comment by mdvictor** [comment]
Fixed
