### ISSUE TITLE
Datagrid: Bar chart is not immediately updating when entering a numerical value in grid

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#66226]
When adding a new row with a value, the value is not updating in the link barchart. The value needs to be entered/changed 2 times in order to show it correctly in the barchart.

Steps to reproduce:
1. create a barchart with a datagrid dashboard as source
2. in the datagrid table, add a new row
3. enter the new values 

Expected result:
i expected the new entry to be visible in the barchart

Actual result:
The new category is being shown in the x-axis but the entered value is not. After activating the value field (changing or just select and hit enter) the bar chart is updated showing the correct value (see video)

https://user-images.githubusercontent.com/110845248/231008875-7cd8b165-d193-47a5-ad59-e45eb8e0bd27.mov

**Comment by mdvictor** [comment]
Fixed
