### ISSUE TITLE
Service Graph not displaying LCD gauge

### ISSUE THREAD

**Issue by gyz2009** [grafana/grafana#66220]
**Describe the bug**
Service Graph not displaying LCD gauge (horizontal bar graph)

![image](https://user-images.githubusercontent.com/30786213/230361528-8406fef6-8256-499a-b580-b2a7ba3ea940.png)

**Additional Context**
version: 2.0.1
grafana version:  9.4.2

**Comment by joey-grafana** [comment]
Fixed in https://github.com/grafana/grafana/pull/64875
