### ISSUE TITLE
 Graph panel future time range : allow templates

### ISSUE THREAD

**Issue by VJean** [grafana/grafana#6623]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0-beta1

While #6309 (closing #6305) allows the use of the "+1h" syntax in the graph panel time range override option, it doesn't support the use of templated variables. Being able to write "+$duration" would be nice.

**Comment by torkelo** [comment]
I think it does, the override field supports template variables

**Comment by VJean** [comment]
@torkelo writing "$duration" is accepted, but writing "+$duration" is not (the border gets orange)

**Comment by torkelo** [comment]
well just add + to your template variable, but I can add + to the validator so it is allowed as well

**Comment by VJean** [comment]
The fact is that I use this variable in my query and in the override field, which makes it impossible for me to add + to the template variable (it would break my query).

So yes, please, it'd be nice to add this use case to the validator.
