### ISSUE TITLE
Datagrid: Deleted column reappears after leaving editing mode

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#66232]
When removing a column in edit mode of a datagrid, the column reappears after saving.

Steps to reproduce:
1. go into editing mode of a datagrid
2. select a column, perform right mouse click and select "delete column"
3. Save the changes

Expected result:
I expected the dashboard to be updated and show the datagrid table without the deleted column.

Actual result:
the column, that has been deleted in editor mode, is still visible in the dashboard (see video)

https://user-images.githubusercontent.com/110845248/231050094-e317931c-75b9-4740-b436-b0a2ff0e520b.mov

**Comment by mdvictor** [comment]
Fixed
