### ISSUE TITLE
Misleading HTTP status code when calling endpoint `GET /api/v1/provisioning/alert-rules/{UID}` - Alerting

### ISSUE THREAD

**Issue by usommerl** [grafana/grafana#66249]
**What happened**:
The Grafana server responds with HTTP status code 500 when calling endpoint `GET /api/v1/provisioning/alert-rules/{UID}` with an unknown rule UID.

**What you expected to happen**:
The server responds with HTTP status code 404 if no rule with the provided UID exists.

**How to reproduce it (as minimally and precisely as possible)**:
```
> http -a "$GF_USER:$GF_PASS" get "http://localhost:3000/api/v1/provisioning/alert-rules/UNKNOWN-UID"

HTTP/1.1 500 Internal Server Error
Cache-Control: no-store
Content-Type: application/json
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
Date: Tue, 11 Apr 2023 08:17:34 GMT
Content-Length: 52

{
  "message": "could not find alert rule",
  "traceID": ""
}
```

**Environment**:
- Grafana version: v9.4.7
- Data source type & version: none
- OS Grafana is installed on: Linux
- User OS & Browser: Linux / Chrome
- Grafana plugins: none
- Others: none

**Comment by tonypowa** [comment]
hi @usommerl 
thanks for creating this issue
i have added a comment to the issue above, where other users have reported wrong HTTP status codes
I'd recommend to monitor the progress from there 👍

**Comment by grobinson-grafana** [comment]
Thanks for opening this issue. Do you think you can contribute a pull request with a fix? If not we can try to prioritize it in the coming weeks.
