### ISSUE TITLE
[Feature Request] Alerting. Option to use OR Filters

### ISSUE THREAD

**Issue by ratchetnclank** [grafana/grafana#6624]
It would be useful if the filters on alerting could trigger on multiple definitions where all conditions aren't met rather than the current implementation where all conditions must be met.

Would it be possible to get a OR logic as well as the current AND?

**Comment by CyBeRoni** [comment]
https://github.com/grafana/grafana/pull/6579

**Comment by bergquist** [comment]
Closing since its a dupe.
