### ISSUE TITLE
v4 signature support for S3 external storage

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#6625]
* **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request

I'm on grafana 4.0.0-beta1

Trying to use the s3 support with Ceph as a backend (Using S3 as a protocol, obviously), I get 403 forbidden despite correct keys. Our storage guy tells me the v2-version of the signature that Grafana uses is a legacy-version, which could be the reason why it doesn't work with our ceph backend.

As for what we are using, since this is hardly my speciality, I asked and was told, and I quote:

- apache 2.4 -> rados gateway -> ceph ... rados gateway and ceph is on version 10.2.3 (jewel) which supports aws sig 4

**Comment by CyBeRoni** [comment]
Some actual Amazon S3 regions also require this.

**Comment by torkelo** [comment]
We will have to wait for Amazon to implement it in their lib:
https://github.com/aws/aws-sdk-go/issues/400

**Comment by CyBeRoni** [comment]
Torkelo: that issue is for the reverse.

**Comment by torkelo** [comment]
oh, sorry was mistaken we actually use another lib for s3 uploads, 

It has an issue for v4 signuare 
https://github.com/kr/s3/issues/31

**Comment by torkelo** [comment]
it's not closed

**Comment by aphawk** [comment]
I cant use S3  feature too.  Grafana stable 4.1.1,AWS Beijing , cn-north-1 . 
https://github.com/kr/s3
last commit was like three years ago.

**Comment by aphawk** [comment]
I noticed that in the latest source code this https://github.com/kr/s3 dependency replaced by https://github.com/aws/aws-sdk-go .

**Comment by whereisaaron** [comment]
Ahh... thanks you @KristianLyng this explains what is going on. I've been running in circles for a couple hours trying to get external S3 images working, trying different regions and settings, reviewing [the code](https://github.com/grafana/grafana/blob/master/pkg/components/imguploader/s3uploader.go), updating to 4.2.0-pre1, updating to master. I puzzled why 'aws s3 cp' worked fine, but Grafana using the same credentials, bucket, and policy failed with: `AccessDenied: Access Denied\n\tstatus code: 403`

```
t=2017-02-15T21:23:06+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="AccessDenied: Access Denied\n\tstatus code: 403, request id: 3CB71F2346628B40"
```

@torkelo until this can be resolved, could you please update the [website manual](http://docs.grafana.org/installation/configuration/#external-image-storage-s3) just to say S3 isn't working right now (maybe link to this ticket) just so people don't waste time trying to troubleshoot it?

@aphawk I am using the a grafana master branch build with the 'aws-sdk-go' reference but it still fails in the same manner. I tested a couple of regions including 'us-east-1' but the credentials that work fine with 'aws s3 cp' on the CLI still fails with Grafana 4.2.0.

The code only seems to require 'PutObject' and the bucket policy certainly has that and works with the aws CLI.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-grafana-images"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-grafana-images/*"
            ]
        }
    ]
}
```

I am use environment variables to configure Grafana (neat system BTW 👏 ). The error suggests it is finding the bucket but then being rejected. (If deliberately but the wrong bucket name in I get a different error.)
```
t=2017-02-15T21:20:36+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=s3"
t=2017-02-15T21:20:36+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL=https://my-grafana-images.s3.amazonaws.com/"
t=2017-02-15T21:20:36+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_ACCESS_KEY=AK123456789012"
t=2017-02-15T21:20:36+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_EXTERNAL_IMAGE_STORAGE_S3_SECRET_KEY=*********"
```

**Comment by whereisaaron** [comment]
I updated my build to the current daily build (commit [70b36a0](https://github.com/grafana/grafana/commit/70b36a02af3601862d00720d1410398a3f83cf3b)) but it did not change the error, I still get `AccessDenied: Access Denied\n\tstatus code: 403`. Using the same AWS key/secret with the CLI and 'aws s3 cp' works just fine. I even enabled public access for PutObject and it still gets this error.

**Comment by whereisaaron** [comment]
I worked this out and it wasn't the V2/V4 signature. There permission error is were the Grafana code tried to apply and ACL to the image. Even if the bucket is 'public-read', the code will try to apply 'public-read' to the file, and requires 's3:PutObjectAcl' for that. The following policy is sufficient for Grafana to work.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::my-grafana-images/*"
            ]
        }
    ]
}
```

**Comment by whereisaaron** [comment]
I created PR #7623 to add the missing information we needed into the documentation.
