### ISSUE TITLE
cert_file config for SMTP does not provide reasonable errors

### ISSUE THREAD

**Issue by Schmoho** [grafana/grafana#66263]
We run our own mailserver, which uses a certificate which is issued by a pretty big and common CA.

Grafana runs as the `grafana/grafana:9.4.7` Docker image.

Analogous config in the prometheus alertmanager suggested to me that the
```
[stmp]
cert_file = [...]
```
config expects a path to a copy of said certificate.
However, whenever this path points to any specific file (certificate or not) trying to send a test mail from Grafana returns an error:

> Failed to send test alert.: could not load cert or key file: open : no such file or directory

Pointing to any non-existing file gives the error

> Failed to send test alert.: could not load cert or key file: open /path/to/nonexisting/file : no such file or directory

So first thing is, the error message in case the config option points to an actual file is wrong, the file pointed to by the config definitely exists. There is the extra weirdness to it that in case the file exists, the path is not included in the error message.

This occurs both with files that are owned by the grafana user and the root user and both when the file is mounted to the container and copied to the Dockerfile, and both when the path in the .ini is quoted (`'/path/to/cert.crt'`, `"/path/to/cert.pam"`) or unquoted.

Finally I would very much appreciate any hint what the correct way to configure this is, because the only (non-)solution I have found so far is to just skip tls_verify.

**Comment by tonypowa** [comment]
hello @Schmoho 
thank you for this issue

what values have you set in your grafana.ini ?
```
protocol
cert_key
```

**Comment by Schmoho** [comment]
Default values, so it should be

```
protocol = http
cert_key = empty
```

TLS offloading for http traffic is done via proxy, so there was no necessity to configure this so far.

The SMTP config is
```
[smtp]
enabled = true
host = <my-mailserver>:25
;user =
;password =
cert_file = /path/to/cert
;key_file =
;skip_verify = true
from_address = admin@grafana.value-marktdaten.de
from_name = Grafana
```

**Comment by tonypowa** [comment]
forwarding issue to back-end squad for further review (please reroute if needed)

**Comment by sakjur** [comment]
Grafana picks up root CA's from the system's certificate stores and you shouldn't need to provide the certificate issued to your mail server.

The `cert_file` is related to mTLS. You need to provide both the certificate and the private key files, the error refers to the key file being empty and not found. I'd agree both the documentation and error messages are lacking here, we should fix that.

**Comment by jastBytes** [comment]
I am having the same issue with our SMTP Server using a custom CA which is not in the system's certificate store. If  `cert-file` is wrong, how to fix this?
