### ISSUE TITLE
V4_beta1 Alerting query bug

### ISSUE THREAD

**Issue by icecode** [grafana/grafana#6626]
**alerting **
- [✓] Bug report

version:grafana-4.0.0-1478693311beta1.linux-x64
backend:influxdb_1.1.0_amd64

metric  query:
`SELECT sum(value) FROM monitor.autogen."httpwatch-counters" WHERE entity = 'test-com' AND status = '500' AND time > now() - 15m GROUP BY time(10s)`

alert query:
`SELECT sum(value) FROM monitor.autogen."httpwatch-counters" WHERE entity = 'test-com' AND status = 500 AND time > now() - 10s GROUP BY time(10s)`

Missing '(status =500), causing the result to be empty

**Comment by torkelo** [comment]
thanks for reporting this! a bug in the backend query builder. It should not quote tag values unless `>` or `<` operator is used.
