### ISSUE TITLE
Env provider in ldap.toml is not working

### ISSUE THREAD

**Issue by duj4** [grafana/grafana#66265]
**What happened**:
Enabled env provider in ldap.toml to replace the plain text password as below:
`bind_password = '$__env{obs_ldap_password}'`.

In log file, it complained "LDAP Result code 1"

However, login failed. Once I changed back to plaintext, the login passed.

**What you expected to happen**: Env provider is working.

**How to reproduce it (as minimally and precisely as possible)**:
1. Save the password in environment variable, in my case, I tried echo $obs_ldap_password=<password> and the predefined environment variable in .bash_profile
2. In ldap.toml, turn on env provider as "bind_password = '$__env{obs_ldap_password}'"
3. Restart service
4. Try to login

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: N/A
- OS Grafana is installed on: RHEL 8.7
- User OS & Browser: Browser
- Grafana plugins: N/A
- Others:

**Comment by tonypowa** [comment]
hi @duj4 
thanks for creating this issue

could you please provide any logs ?

Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by duj4** [comment]
Hi @tonypowa ,
Thanks for your reply.
Please check the attachment for the screenshot and log snippet.

[github_66525.zip](https://github.com/grafana/grafana/files/11220996/github_66525.zip)

**Comment by tonypowa** [comment]
thank you @duj4 

forwarding this issue to the auth squad for review

ps: copy-pastyinng the logs provided  for visibility:

```
logger=ldap t=2023-04-13T18:04:49.069966132+08:00 level=info msg="LDAP enabled, reading config file" file=/d/d1/monitoring/grafana/conf/ldap.toml
logger=ldap t=2023-04-13T18:04:49.086651808+08:00 level=debug msg="LDAP SearchRequest" searchRequest="&{BaseDN:ou=Users,ou=MSMS,dc=oa,dc=hkintegrationlab,dc=com Scope:2 DerefAliases:0 SizeLimit:0 TimeLimit:0 TypesOnly:false Filter:(|(sAMAccountName=dujas)) Attributes:[sAMAccountName sn mail givenName memberOf] Controls:[]}\n"
logger=context userId=0 orgId=0 uname= t=2023-04-13T18:04:49.087450757+08:00 level=error msg="Error while trying to authenticate user" error="LDAP Result Code 1 \"Operations Error\": 000004DC: LdapErr: DSID-0C090A5E, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000" remote_addr=10.233.252.60 traceID=


bind_password = $__env{obs_ldap_password}
logger=context userId=0 orgId=0 uname= t=2023-04-13T18:10:33.135149665+08:00 level=error msg="Error while trying to authenticate user" error="Failed to get LDAP config: Failed to load LDAP config file: toml: line 30 (last key \"servers.bind_password\"): expected value but found '\\n' instead" remote_addr=10.233.252.60 traceID=
```

**Comment by mgyongyosi** [comment]
Hey @duj4, could you please try with `bind_password = '${obs_ldap_password}'`?

**Comment by duj4** [comment]
hi @mgyongyosi , thanks for the reply, I have tired that before as it shows in the screenshot:
![provider](https://user-images.githubusercontent.com/19278537/231923836-5c740af4-66bf-469f-8913-155a6eb0e9d9.PNG)

**Comment by duj4** [comment]
> thank you @duj4
> 
> forwarding this issue to the auth squad for review
> 
> ps: copy-pastyinng the logs provided for visibility:
> 
> ```
> logger=ldap t=2023-04-13T18:04:49.069966132+08:00 level=info msg="LDAP enabled, reading config file" file=/d/d1/monitoring/grafana/conf/ldap.toml
> logger=ldap t=2023-04-13T18:04:49.086651808+08:00 level=debug msg="LDAP SearchRequest" searchRequest="&{BaseDN:ou=Users,ou=MSMS,dc=oa,dc=hkintegrationlab,dc=com Scope:2 DerefAliases:0 SizeLimit:0 TimeLimit:0 TypesOnly:false Filter:(|(sAMAccountName=dujas)) Attributes:[sAMAccountName sn mail givenName memberOf] Controls:[]}\n"
> logger=context userId=0 orgId=0 uname= t=2023-04-13T18:04:49.087450757+08:00 level=error msg="Error while trying to authenticate user" error="LDAP Result Code 1 \"Operations Error\": 000004DC: LdapErr: DSID-0C090A5E, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000" remote_addr=10.233.252.60 traceID=
> 
> 
> bind_password = $__env{obs_ldap_password}
> logger=context userId=0 orgId=0 uname= t=2023-04-13T18:10:33.135149665+08:00 level=error msg="Error while trying to authenticate user" error="Failed to get LDAP config: Failed to load LDAP config file: toml: line 30 (last key \"servers.bind_password\"): expected value but found '\\n' instead" remote_addr=10.233.252.60 traceID=
> ```

Thanks @tonypowa , we really need this function as it is not allowed to save password in plaintext, looking forward to the update.

**Comment by mgyongyosi** [comment]
Hi @duj4, I have just tested it and the env parsing seems to be working properly (tried with `$__env{variable}` and `${variable}` as well). I could reproduce the issue when I did set `bind_password = ${LDAP_PASSWORD}` (note the missing apostrophes) and the environment variable was missing.

So please ensure that the environment variable is set correctly and try with this setting: `bind_password = '${obs_ldap_password}'`. After that, if it's still not working then please share the relevant part from the logs.

**Comment by duj4** [comment]
Thanks @mgyongyosi .
If you checked the screenshot, I did set the password binding like `bind_password = '${obs_ldap_password}'` and I tried it again, still no luck, please check the screenshot as below:
Set a temp environment variable:
![new_password](https://user-images.githubusercontent.com/19278537/232262243-1f56a9ce-b54b-4a4c-8768-cd1e20643153.PNG)
Configuration:
![conf](https://user-images.githubusercontent.com/19278537/232262256-bd0ec2b7-6cef-4987-93a0-8e266be71324.PNG)
Log:
![log_0416](https://user-images.githubusercontent.com/19278537/232262258-a1df2280-9489-4fc8-8796-e0b30c713c87.PNG)

**Comment by duj4** [comment]
I added EnvironmentFile into the systemd unit file:
![systemd](https://user-images.githubusercontent.com/19278537/232265333-1d3cf5a5-2c01-4b0a-b5cb-e263cddb557a.PNG)
In that file I am trying to set the password via a shell script, it runs like:
![env_script](https://user-images.githubusercontent.com/19278537/232265351-2fcbde26-be60-4847-b8f4-1e9a43f22334.PNG)

Still no luck unless I set the password in plain text.

**Comment by duj4** [comment]
@mgyongyosi , here is the latest config:
![latest_variables](https://user-images.githubusercontent.com/19278537/232266012-0d875802-a4f5-4a81-aabe-cb21a91aa71f.PNG)
![latest_config](https://user-images.githubusercontent.com/19278537/232266018-43b87e88-406e-40e4-96b9-e945123b6593.PNG)

Same error :(, exhausted here...

**Comment by duj4** [comment]
hi @mgyongyosi , indeed it works via this way, I have to set the environment variable inside grafana's "namespace"

**Comment by duj4** [comment]
Hi @mgyongyosi , does it mean that the provider only works when I set the environment variable with password in plaintext inside the .env file or systemd unit file?

**Comment by mgyongyosi** [comment]
Hi @duj4, yes, it means that Grafana's env variable provider works correctly, so you need to specify the password in plain text in the .env file. The way you specify the plain text depends on you, but afaik an`.env` file is not expected to execute shell scripts.

**Comment by duj4** [comment]
> 

Thanks @mgyongyosi for your help on this case.
