### ISSUE TITLE
Template variables used in annotations not working with graphite.

### ISSUE THREAD

**Issue by h4wkmoon** [grafana/grafana#6628]
Hi, 
I think I've found a like something.

* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
         Latest docker container.
- What datasource are you using?
         Graphite
- What OS are you running grafana on?
         The one shipped with the container.
- What did you do?
          Create an annotation with a tag based on template variable.
- What was the expected result?
          Only the matching events appear.
- What happened instead?
          Nothing is shown.

The reason behind that is grafana sends the requests with {} around the tag, and it should not.

Not working (and currently done by grafana) 
http://localhost:3000/api/datasources/proxy/1/events/get_data?from=-5min&until=now&tags={example2}
Working
http://localhost:3000/api/datasources/proxy/1/events/get_data?from=-5min&until=now&tags=example2

Could you please look into that ?

**Comment by torkelo** [comment]
you need to disable multi value on the variable. The graphite tags filter does not support glob expressions.
