### ISSUE TITLE
[alerting] two grafana FEs behind vip equal double notifications

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#6629]
* **I'm submitting a ...**
-  Bug report

Please include this information:
- What Grafana version are you using? 4-beta1
- What datasource are you using? graphite
- What OS are you running grafana on? linux
- What did you do? Configured grafana behind a load balancer on two front-ends with alerting enabled. 
- What was the expected result?  I expect grafana to understand it is installed with multiple instances, and only send one alerts.
- What happened instead? I receive two notifications per alert.

**Comment by torkelo** [comment]
This is mentioned in the alerting  docs, we do not have cluster support right now, will add in future release, right now the only way to now get duplicate notifications is to only enable the alerting scheduler on one of the servers, this you can do in grafana.ini

**Comment by blysik** [comment]
Great, thanks!
