### ISSUE TITLE
Issues grafana alerting when there are no data points

### ISSUE THREAD

**Issue by timothyakampa** [grafana/grafana#6631]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

- Grafana version: **Grafana v4.0.0-beta1**
- Datasource: **Influxdb**
- OS: **grafana/grafana docker container running on ubuntu**

I am trying to setup an alert that will get triggered when there are no data points, forexample in cases where the system goes down and stops sending metrics.
<img width="640" alt="screen shot 2016-11-17 at 6 55 11 pm" src="https://cloud.githubusercontent.com/assets/5243093/20412886/86c22302-acf7-11e6-93c1-8e8a900825a6.png">

I expect the alert to get triggered when there are no data points but it doesn't seem to be getting triggered.
<img width="244" alt="screen shot 2016-11-17 at 6 59 23 pm" src="https://cloud.githubusercontent.com/assets/5243093/20412977/2dd0aac4-acf8-11e6-9bdf-ae18a521a448.png">

**Comment by bergquist** [comment]
Please press the 'Test rule' button, expand the complete answer and attach to this issue.

**Comment by timothyakampa** [comment]
I saved the dashboard and tried it multiple times on different graphs. This is what the answer looks like. The data array is empty. 
<img width="380" alt="screen shot 2016-11-18 at 5 23 00 pm" src="https://cloud.githubusercontent.com/assets/5243093/20448834/e677733a-adb3-11e6-8180-9b7b0f3c9f16.png">

**Comment by bergquist** [comment]
This is working as we intended. But I'm not sure we described it correctly. 

NoData will only trigger if the query returns series that contains no data. Not if the query no series at all. 

Could you please describe the scenario when you want to alert on such scenario?

**Comment by timothyakampa** [comment]
I am collecting docker container metrics using cadvisor which forwards them metrics to influxdb. When a container goes down, cadvisor stops sending container metrics to influxdb. I need my grafana alerts to trigger when there is no data streaming in, so that I can infer that the container is down. Currently the graph just stops plotting and no alerts are triggered.

**Comment by bergquist** [comment]
Turns out that we misunderstood how influxdb returns data in ranges where there is no data. We expected it to return empty series. 

Considering that we will make the NoData option trigger for no series as well.

Thank you for reporting this!

**Comment by bergquist** [comment]
Found a bug regarding no data! Should be available shortly at grafana.org/builds

Thank you for reporting this! :)

**Comment by timothyakampa** [comment]
You are welcome :)

**Comment by quantonganh** [comment]
I'm running 4.4.2.

I got the same problem as @timothyakampa described (except that we're using `telegraf` insteaf of `cadvisor`): our ElasticSearch container goes down due to OOM but no alerts are triggered.

If I click on the Test rule button:

```
result
firing false
state alerting
conditionEvals false = false
timeMs 8.863ms
logs
0
message Condition[0]: Query Result
data [ ]
1
message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
data null
```

> NoData will only trigger if the query returns series that contains no data. Not if the query no series at all.

So, does Grafana send an alert if the query returned no series at all (because the container has just exited for some reasons)?

**Comment by torkelo** [comment]
Not sure, @bergquist can you check how no data state is arrived at? What happens when no series are returned?

**Comment by quantonganh** [comment]
I saw a lot of this message in the logs:

> t=2017-09-15T16:23:15+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalHandler ruleId=21 name="CPU $container alert" changing state to=alerting

As you can see:

> changing state to=alerting

Looks like it does not match with "Test Rule" result:

> firing false

**Comment by quantonganh** [comment]
By looking at the history of `pkg/services/alerting/conditions/query.go`, I found this: https://github.com/grafana/grafana/commit/d354f3a8afa49420085dd73044da566617ab0e5f#diff-7f9d28372c0a7e9598426d3e361638f6

So, I added a condition to alert when HAS NO VALUE:

<img width="629" alt="screenshot 2017-09-15 23 46 02" src="https://user-images.githubusercontent.com/1568504/30493983-84cc17e4-9a70-11e7-81cd-876fe04c4bab.png">

Test Rule:

```
result
firing true
state alerting
conditionEvals [false OR true] = true
timeMs 17.357ms
matches
0
metric NoData
value null
logs
0
message Condition[0]: Query Result
data [ ]
1
message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
data null
2
message Condition[1]: Query Result
data [ ]
3
message Condition: Eval: true, Query Returned No Series (reduced to null/no value)
data null
```

**Comment by quantonganh** [comment]
It's weird that I updated the condition to `query (B, 1m, now)` but still get no alerts after 15 minutes.

**Comment by quantonganh** [comment]
@bergquist Do you have any idea about this?

**Comment by bergquist** [comment]
@quantonganh Seems like the change you made in https://github.com/grafana/grafana/issues/6631#issuecomment-329838186 fixed this issue. Right?

if your using influxdb I strongly suggest you use a longer range then 1m since influxdb will only return series that's available in that time range. Which means its impossible to notice the difference between missing series or no series.

**Comment by quantonganh** [comment]
> @quantonganh Seems like the change you made in #6631 (comment) fixed this issue. Right?

No, as I said in https://github.com/grafana/grafana/issues/6631#issuecomment-329843142

> if your using influxdb I strongly suggest you use a longer range then 1m since influxdb will only return series that's available in that time range. Which means its impossible to notice the difference between missing series or no series.

I changed it to 2m, test rule result:

```
result
firing true
state alerting
conditionEvals [false OR true] = true
timeMs 32.135ms
matches
0
metric NoData
value null
logs
0
message Condition[0]: Query Result
data [ ]
1
message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
data null
2
message Condition[1]: Query Result
data [ ]
3
message Condition: Eval: true, Query Returned No Series (reduced to null/no value)
data null
```

but still got no alert.

PS: "Send Test" email works fine as I just tried one more time to be sure.

**Comment by bergquist** [comment]
Have you added a notifier for that alert? ex
![image](https://user-images.githubusercontent.com/618863/30859552-8189f036-a2c4-11e7-8b3f-5d00a8c32df0.png)

**Comment by quantonganh** [comment]
Sure:

<img width="773" alt="screenshot 2017-09-26 19 21 59" src="https://user-images.githubusercontent.com/1568504/30860109-3523242a-a2f0-11e7-94d0-8da6a44e8bf7.png">

**Comment by bergquist** [comment]
Strange.. if you go to ```/alerting/list``` is ```CPU $container alert``` listed as alerting?

Grafana will only (atm) send notifications once per state change.

**Comment by quantonganh** [comment]
Thanks, you saved my week.

<img width="967" alt="screenshot 2017-09-26 19 47 03" src="https://user-images.githubusercontent.com/1568504/30861035-aef4475e-a2f3-11e7-9925-93aaffcd2c34.png">

I just pressed Pause/Unpause, then I got the alerting email.

**Comment by bergquist** [comment]
@quantonganh no worries :) questions in good feedback. Its obvious that this experience can be improved.

**Comment by quantonganh** [comment]
Something's wrong.

I started the ElasticSearch container, waited for some minutes but there is no "back to OK" email alert.

If I go to `Alerting/list`, pause/unpause that alert, then I got this email:

<img width="683" alt="screenshot 2017-09-26 20 24 37" src="https://user-images.githubusercontent.com/1568504/30862581-bfa4cb82-a2f8-11e7-97cf-2f85616ce3a5.png">

Why "No Data" while you can see the metric obviously?

```
result
firing true
state alerting
conditionEvals [false OR true] = true
timeMs 17.447ms
matches [ [object Object] ]
logs
0 { message: Condition[0]: Query Result, data: , $$hashKey: object:315 }
1
message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
data null
2 { message: Condition[1]: Query Result, data: , $$hashKey: object:317 }
3
message Condition: Eval: true, Query Returned No Series (reduced to null/no value)
data null
```

Why does Grafana still evaluated my second condition as `true`?

**Comment by bergquist** [comment]
@quantonganh What version of Grafana are you using? This have been fixed in 4.6.3 https://github.com/grafana/grafana/issues/9318

**Comment by Wang-Kai** [comment]
> Did you save the dashboard after changing the value in the dropdown?
> 
> Please press the 'Test rule' button, expand the complete answer and attach to this issue.

Thanks for your answer, it solved my problem. But i still misunderstand the difference between `apply` and `save` button, can you explain them for me ?

**Comment by nehas247** [comment]
Hi All,

I am facing difficulties in Alert functionality of Grafana. I have done the settings put the conditions and rule but I am not receiving emails. I tried testing the rule and got below error message. Please suggest some solutions.
![TestRuleError](https://user-images.githubusercontent.com/38423756/96085737-e0160480-0ede-11eb-973d-b8115a1921ad.PNG)
