### ISSUE TITLE
Attempting to navigate to an Exemplar from a dashboard panel does not work

### ISSUE THREAD

**Issue by hedss** [grafana/grafana#66328]
**What happened**:
In a timeseries graph panel using exemplar enabled Prometheus data, selecting the appropriate exemplar's trace link does nothing. However, browser support to 'Open in a new tab' (both FF and Chrome tested) will open the Explorer page with the trace, as expected. As such the correct URL is being generated, but the exemplar link is not being opened.

Curiously, selecting an exemplar using the same data in an Explorer page will work correctly. So this affects only dashboard panels.

**What you expected to happen**:
Selecting an exemplar's trace link should take you to an Explorer page with the relevant trace ID filled in and the trace visualised.

**How to reproduce it (as minimally and precisely as possible)**:
Use any `grafana:main`, `grafana:latest` or the current Grafana Cloud version (Grafana v9.5.0-cloud.2.f143d34 (efe95b4c21)) to see this and select any panel with exemplar data, attempting to follow the link.

![image](https://user-images.githubusercontent.com/8259026/231322041-3e3be8c4-963d-47f6-b662-6c28393d671c.png)

Use https://sedemo.grafana.net/d/blw4HrB4k/mythical-inc-top-level-endpoints-red-mlt-traceql?orgId=1 as an example.

**Anything else we need to know?**:
Nope.

**Environment**:
- Grafana version: Grafana v9.5.0-cloud.2.f143d34 (efe95b4c21), `grafana:latest`, `grafana:main`
- Data source type & version: Prometheus / Tempo
- OS Grafana is installed on: Grafana Cloud/MacOS
- User OS & Browser: https://www.whatsmybrowser.org/b/5EU7W
- Grafana plugins: Not relevant.
- Others:

**Comment by LudoVio** [comment]
You have a few example of exemplar dashboard on ops. Canm you try there?
https://ops.grafana-ops.net/d/fdfcabd4-586d-4bb9-89ea-d63154db3511/exemplar-bug-test?orgId=1

Maybe your browser have an  extension or something. Or maybe it has been fixed

**Comment by gtk-grafana** [comment]
@hedss I just [tested](https://sedemo.grafana.net/d/blw4HrB4k/mythical-inc-top-level-endpoints-red-mlt-traceql?orgId=1) this out on the sedemo link you provided and it's working as expected. Closing, but let us know if you are still seeing this locally
