### ISSUE TITLE
Grafana to support Sharded influx db instances

### ISSUE THREAD

**Issue by keep94** [grafana/grafana#6632]
* **I'm submitting a ...**
- [ X] Feature request

- What datasource are you using? Influx DB
- What OS are you running grafana on? Linux, Ubuntu

We use sharded influx db data instances in our data store:

1. Last 24 hours; 30s resolution, expensive, high performing hardware
2. 1 to 30 days ago; 15m resolution.
3. 30 days to 5 years ago; 4h resolution.

We see the following issues using grafana with this configuration:

1. Grafana users have to know in advance what data source to use with each query they run.
2. If a grafana user wants data from 6 hours to 2 days ago, they have to do 2 queries: One against shard #1 and one against shard #2. Then they have to merge the two resulting datasets together in their minds.

What we would like is a way to produce a generic data source that makes our three data sources appear as one. Then.

1. User runs a grafana query
2. Grafana queries one or more influxdb backends to satisfy the query
3. Grafana merges the results together so that user sees a single graph.

We would be more than happy to do the work and create a pull request. Would this be something that the Grafana team would be interested in?

**Comment by bergquist** [comment]
Not sure if this belongs in Grafana or some sort of query proxy.

**Comment by rgooch** [comment]
Note that the proposal, while referencing InfluxDB, is not limited to it. The same approach is applicable to OpenTSDB. In some environments it may even make sense to have different implementations for different resolution&retention back-ends. 

It seems to me that it's cheaper to do this in Grafana, which already has the code to read from different back-end databases (InfluxDB and OpenTSDB). A proxy would need to duplicate that code. Also, putting this in Grafana would reduce the amount of data having to be moved around.

**Comment by gabor** [comment]
to do this with the current grafana version:
- add all the shards as separate data sources
- in a dashboard-panel, add a separate query for every shard
- adjust the series-colors so that the "same series" between the quries has the same color

**Comment by gabor** [comment]
this does not seem to be something Grafana should be doing, so closing this one.
