### ISSUE TITLE
Parent span time not matching with total time of individual child spans.

### ISSUE THREAD

**Issue by pswami-conga** [grafana/grafana#66332]
Parent span time not matching with total time of individual child spans.
![image](https://user-images.githubusercontent.com/91658402/231378439-0f507747-b677-44f4-aabc-671d4c6a400f.png)

Here the parent span time is not correct. it should be the sum of individual child spans duration.

**Environment**:
- Grafana version: Grafana v9.4.3
- Data source type & version: Tempo

**Comment by joey-grafana** [comment]
A parent does not technically need to be the sum of its child span durations. Concurrent requests can take more time than the parent to complete, for example.
