### ISSUE TITLE
crash 4.0beta1 when starting

### ISSUE THREAD

**Issue by noamcohen** [grafana/grafana#6636]
I'm submitting a Bug report
(sorry for the markdown - didn't see where to turn it off)
I downloaded and installed the 4.0 beta according to instructions in the site. no problems here.
when tried to run, got SEGV consistently.

NOTE: this ubuntu is a docker image that runs graphite + grafana 3.1 succesfully

NOTE: as a reference, on my ubuntu 16.04, the installation/run went smooth.

# /usr/sbin/grafana-server -v                              
Version 4.0.0-beta1 (commit: v4.0.0-beta1)

# lsb_release -a                                                                                                                      
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	**14.04**
Codename:	trusty

root@1fa5dd86bf69:/grafana# /usr/sbin/grafana-server --config=/etc/grafana/config.ini
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f0e8b]

goroutine 1 [running]:
panic(0xd216c0, 0xc420010090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc420125de8)
	/go/src/github.com/grafana/grafana/pkg/setting/setting.go:362 +0x18b
github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc420125de8, 0x1, 0xc420125df8)
	/go/src/github.com/grafana/grafana/pkg/setting/setting.go:460 +0x54
main.initRuntime()
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:69 +0xd5
main.(*GrafanaServerImpl).Start(0xc4201ca570)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:52 +0x5f
main.main()
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:61 +0x12c
**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by bergquist** [comment]
Thank you for reporting this.

Close by https://github.com/grafana/grafana/commit/5dea0fda51fe0cc7ce1e2fdb17f2dabe16b7213f

**Comment by jamiek23** [comment]
Not sure if this is relevant, but seeing a very similar issue with beta2:
<pre>Nov 21 17:03:29 environment grafana-server[15228]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 21 17:03:29 environment grafana-server[15228]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f09fd]
Nov 21 17:03:29 environment grafana-server[15228]: goroutine 1 [running]:
Nov 21 17:03:29 environment grafana-server[15228]: panic(0xd23800, 0xc420010070)
Nov 21 17:03:29 environment grafana-server[15228]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 21 17:03:29 environment grafana-server[15228]: github.com/grafana/grafana/pkg/setting.loadSpecifedConfigFile(0x7ffe994c0d83, 0x18, 0x3, 0xc4201ca420)
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/setting/setting.go:327 +0xed
Nov 21 17:03:29 environment grafana-server[15228]: github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc4200fdde8)
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/setting/setting.go:374 +0x1ee
Nov 21 17:03:29 environment grafana-server[15228]: github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc4200fdde8, 0x1, 0xc4200fddf8)
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/setting/setting.go:460 +0x54
Nov 21 17:03:29 environment grafana-server[15228]: main.initRuntime()
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:69 +0xd5
Nov 21 17:03:29 environment grafana-server[15228]: main.(*GrafanaServerImpl).Start(0xc4201a27e0)
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:52 +0x5f
Nov 21 17:03:29 environment grafana-server[15228]: main.main()
Nov 21 17:03:29 environment grafana-server[15228]: /go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:61 +0x12c
</pre>

Environment is Debian 8/Jessie, as opposed to Ubuntu 14.04. Was installed via apt/dpkg - `grafana_4.0.0-1479719016beta2_amd64.deb`.

Let me know if this would be better as a separate bug report!
