### ISSUE TITLE
Slack-alerting fails if s3-uploads fails

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#6638]
* **I'm submitting a ...**
- [X] Bug report

grafana 4.0.0-beta1, official docker image, set up with working slack integration.

I reported #6625 yesterday, and as a side effect I've realized a flaw: When the s3 upload fails, there are no alerts at all. This utterly unrelated to #6625, it just made the issue visible.

Means s3-outages will disable alerting, which shouldn't happen.

**Comment by bergquist** [comment]
Thank you for reporting this!
