### ISSUE TITLE
Datasource Test button reports Mimir/Cortex for vanilla Prometheus

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#66384]
**TEST** button on the data source settings page reports vanilla Prometheus **Alertmanager** as Mimir or Cortex one

**Comment by khushijain21** [comment]
Can you guide on how to reproduce this and elaborate on the issue?

**Comment by soniaAguilarPeiron** [comment]
I cannot reproduce this issue. Could you please provide more details? @konrad147
