### ISSUE TITLE
Bug: Prometheus Query Field block user input unnecessarily

### ISSUE THREAD

**Issue by qingwei91** [grafana/grafana#66402]
**What happened**:
Prometheus query field is blocked by autocomplete suggestions. Below is a gif recording what happened when I tried to type multiple character quickly in the query field.

![type-err](https://user-images.githubusercontent.com/6303687/231516294-81cfefad-65da-4a86-9d14-a12bc44216f7.gif)

**What you expected to happen**:
Prometheus query field to not blocked by autocomplete suggestions

**How to reproduce it (as minimally and precisely as possible)**:
I have a branch that can simulate the issue: https://github.com/qingwei91/grafana/commit/0705288316fb7577d82e92e16d89ba5a79c7019e
To reproduce, you can
1. Pull my branch
2. Setup prometheus locally by running `docker run -p 9090:9090 prom/prometheus`
3. Run grafana locally using `yarn start`
4. Open grafana from browser, install prometheus datasource to `http://localhost:9090`
5. Go to `explore` view, type something like `rrrr` consecutively.

**Anything else we need to know?**:
This is mainly a problem with large number of metric names, the same problem might exists for other datasource too, but I havent tested that out.

**Environment**:
- Grafana version: 9.4.3 to 9.4.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: Prometheus
- Others:

----------------
**Discussion**:

I am keen to help fix this assuming we agree this is not desired, I wish to get your thoughts on what's the best way on fixing this.

Ideally, I think we should avoid blocking user input. I am not a frontend expert, I can think of a few naive way:

1. Move the compute to web worker
2. Chunk the computation into smaller pieces so that we can queue them separately to the event loop
3. Make use of the CancelationToken from Monaco editor, similarly we need to chunk the computation to give chance to cancel computation, but Monaco editor isnt very well documented on this front, so I am not entirely what triggers a cancelation.

I don't fully understand the Monaco code, its not easy to track because apparently it comes from vscode directly, so I am not sure how the suggestions produced by our `completionProvider` is used. One easier fix might be to limit the no of suggestion produced upstream, in my case, our deployed prometheus has 30 millions metric name, maybe auto-complete can be imperfect and just make use of top N results.

Kind regards

**Comment by tonypowa** [comment]
hi @qingwei91 
thanks for creating this issue

Apologies if I am missing the point completely, but what is the autocomplete blocking exactly? From my end, i can see what I am typing.

![prom](https://user-images.githubusercontent.com/45235678/232021892-28743c7f-895c-46a2-83cc-8e788a14127d.gif)

**Comment by qingwei91** [comment]
Hi @tonypowa , thanks for taking a look at this.

I believe the issue is only observable when there's a lot of metrics, in our deployment, we have millions of metric name.

Were you able to use the branch I made? I added an artificial lag in the completion provider to illustrate that problem, not sure if that makes sense?

**Comment by tonypowa** [comment]
@qingwei91 

no, i used my own Grafana installation for the test,  but I see what you mean.

let's wait to hear what the engineers at the Metric's squad think about this

**Comment by qingwei91** [comment]
Hi @tonypowa , I spent more time on this, and got to the bottom of it. I've posted a relevant SO here since that's the official way to get help for VS Code: https://stackoverflow.com/questions/76288460/how-to-make-vscode-completion-model-work-with-large-amount-of-candidates?noredirect=1#comment134536134_76288460

It boils down to the fact that our prometheus has at least 160k metrics name, and running all of them through VS Code's fuzzy scorer is probably too slow.

From what I've seen in other monaco editor usage, for example in Java, they solve it by limiting the no of CompletionItems passed to monaco. What do you (or any other core contributor) think about providing a configuration to optionally limit no of CompletionItem?

The consequence is that auto-complete might not be perfect, ie. it might not show suggestions that should exist.

**Comment by leeoniya** [comment]
> I believe the issue is only observable when there's a lot of metrics, in our deployment, we have millions of metric name.

millions will never work well. this many metric names is usually a sign that the metric names contain unique ids which properly belong in labels.

that being said, we do have a rendering performance issue with he dropdown as well and plan to support ~100k items without slowdowns. i'm not sure what the ETA is, but "months, not years" is ballpark.

internal threads:

https://raintank-corp.slack.com/archives/CV10FUN6N/p1683843852379019

https://github.com/grafana/observability-metrics-squad/issues/47

cc @gtk-grafana

**Comment by qingwei91** [comment]
Hi @leeoniya , thanks for getting back to this issue.

And yes I can confirm this happens even with 100K ++ metric name, we used to have around 800k, we've now reduced it to 100k but still facing the same issue.

What do you think about exposing a configuration to control the no of metrics used in auto-complete suggestion code? I am happy to make this patch if its something we're onboard with.

**Comment by gtk-grafana** [comment]
Yeah having a config option to set the max number of completions passed in is a good idea, and shouldn't be too much work. Any help would be greatly appreciated on this @qingwei91!

**Comment by NWRichmond** [comment]
Good news! This (and https://github.com/grafana/grafana/issues/84612) have been fixed in https://github.com/grafana/grafana/pull/85396.

Starting in Grafana 11.1, the Code Mode performance improvements will be available behind the new [experimental feature toggle](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/feature-toggles/#experimental-feature-toggles) `prometheusCodeModeMetricNamesSearch` feature toggle.
