### ISSUE TITLE
Method to distribute internal datasource

### ISSUE THREAD

**Issue by huydx** [grafana/grafana#6640]
* **I'm submitting a ...**
- [x] Feature request

Please include this information:
- What Grafana version are you using? : 3.1.1
- What datasource are you using? : Custom datasource
- What OS are you running grafana on? : Centos

- What did you do? : 
  - I wrote a custom datasource for support our internal monitoring tool. The datasource is distributed using .tar.gz format. Every time we update our datasource, we have to notice our users (many teams, have their own grafana server), and asked them to download the artifact, uncompress, and place to their grafana server manually, which is really inconvenience. Moreover, if we change the API of our monitoring backend to fix bug etc, old datasource will not work as well. Note that we can't distribute our datasource using grafana.net.

- What was the expected result?
  - I expect there is a better way to distribute internal datasource. I'm thinking about method that we can specify an manifest file which include latest version, and location to the artifact. We than have a button (Update button etc) that support to update datasource to latest version (which simply just look at manifest file, download and place to plugin folder)

### Note
If we're able to come to conclusion here, I can implement it too.

**Comment by torkelo** [comment]
you can distribute external plugins with grafana-cli (plugins hosted on grafana.net), for interna plugins, maybe a configuration management (puppet/chef) or deploy tool can do the job.

**Comment by huydx** [comment]
@torkelo Personally I still think more general way (use manifest file which specify version, and where to download the datasource) will be a good option to consider (and user just need to click a button, to update latest datasource). Asking every team/user to run chef (some team even doesn't use chef)  is a not a good solution IMHO.
