### ISSUE TITLE
Unable to change channel on Slack alert

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#66416]
**What happened**:
I duplicated a slack contact point and the channel was not editable. Channels on existing contact points cannot be edited. 

**What you expected to happen**:
The duplicate button seems like a great addition to this feature. It allows creating a new Slack channel without having to go find the webhook URL. Except the channel cannot be changed.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to change the channel on a new or duplicated slack contact point.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7

**Comment by tonypowa** [comment]
thank you for creating this issue @davidnewhall 

i will forward it to the Alerting team

Note for the squad:

inspecting the duplicated Recipient field (id=`items.1.settings.recipient`), you can see the attribute `readonly=""`. If you remove it, the field becomes editable.

Field made editable:

![image](https://user-images.githubusercontent.com/45235678/232015968-2b4afd55-57f0-4844-89f3-b6a729ec0010.png)

**Comment by soniaAguilarPeiron** [comment]
This recipient field is readonly not only when duplicating but when editing the contact point. The reason for that is that this field depends on the url field. So, if you want to edit it, you can click `clear` on the webhook url input. Then this field is cleared and it becomes editable again.
<img width="670" alt="Screenshot 2023-05-02 at 10 35 53" src="https://user-images.githubusercontent.com/33540275/235620736-ec3bc9ea-521a-459c-9f1b-ebc6c50f421c.png">

**Comment by davidnewhall** [comment]
> The reason for that is that this field depends on the url field. 

This is untrue. I use the same URL with hundreds of channels.

**Comment by soniaAguilarPeiron** [comment]
Hi @davidnewhall , are you using [legacy incoming webhooks](https://api.slack.com/legacy/custom-integrations/messaging/webhooks)?

**Comment by soniaAguilarPeiron** [comment]
The same behaviour can be achieved by using a [bot token](https://github.com/grafana/grafana/pull/65185#issuecomment-1538484211)

**Comment by davidnewhall** [comment]
> Hi @davidnewhall , are you using [legacy incoming webhooks](https://api.slack.com/legacy/custom-integrations/messaging/webhooks)?

Yes.

> You can achieve the same behaviour by using a bot token, see this PR discussion for https://github.com/grafana/grafana/pull/65185#issuecomment-1538484211 .

This PR looks like some behavior was changed, but I'm not fully understanding it. We provision new slack channels with direct API calls. The app I wrote pulls the web hook URL from a secret store. It would be ideal if I didn't need the secret store and I could just copy an existing notification and update the recipient channel. Before the URL was encrypted (many versions ago now), I copied the URL from an existing channel. Since it was encrypted I can no longer do that.

If I use a bot token, do we have the same problem? Or will I be able to copy a notification channel and change the slack channel on it?

**Comment by soniaAguilarPeiron** [comment]
> If I use a bot token, do we have the same problem?
With tokens you can override the channel  👍

**Comment by soniaAguilarPeiron** [comment]
Let us know, @davidnewhall if you can succeed using this option.
As we (Grafana) would love to avoid adding support for legacy configurations of the integrations we support, and this behaviour can be achieved by using bot tokens, we are going to close this issue.
