### ISSUE TITLE
Alerting: Source URL in alert created outside of dashboard/panel in multi-org environment does not contain orgId

### ISSUE THREAD

**Issue by aos** [grafana/grafana#66427]
**What happened**:

This is similar to #47424. When an alert is created in a multi-org environment, outside of a dashboard or panel, by going through Alerting -> New Alert rule, the generated alert URL will not have the `orgId` parameter attached to it. This causes an "alert not found" within multi-org environments.

This was fixed for **dashboard and panel URLs** but not alerts created outside of those context in #57123. The logic should extend to creating alerts manually.

**What you expected to happen**:

Alerts created via Alerts -> New alert rule should include the appropriate source URL with the `orgId`  parameter in a multi-org environment.

**How to reproduce it (as minimally and precisely as possible)**:

1. Be in a multi-org environment
2. Create an alert via Alerts -> New alert rule
3. Fire the alert
4. Notice that the `Source` URL in the alert notification does not contain the correct `orgId` and will not go to the appropriate organization/alert.

**Anything else we need to know?**:

It looks like all the alerting logic was moved to the repo: https://github.com/grafana/alerting in `main` and `v9.4.x`, but it's still here in `v9.3.x`.

- Logic now resides here: https://github.com/grafana/alerting/blob/4a7ecc241d722072bbf26156d56e6ebf9955e95e/templates/template_data.go#L113-L115
- `v.9.3.x` in this repo: https://github.com/grafana/grafana/blob/b34f9779fd1d062d8685ad87a31930f0f970ce30/pkg/services/ngalert/notifier/channels/template_data.go#L107-L109

I think the change should be simple enough and I'm fine with cutting a PR for this, but I wasn't sure where the change should go. If it's in v9.4.x, and I make a PR to https://github.com/grafana/alerting, we'd have to also bump the `go.mod` here, correct?

**Environment**:
- Grafana version: 9.3.8
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: N/A

Thanks!

**Comment by tonypowa** [comment]
hi @aos 

thank you for creating this issue

I am forwarding it to the Alert squad. They will get back to you with the next steps

**Comment by alexweav** [comment]
Yes, the grafana/alerting repo is the right place for this fix. We bump its version periodically, but we'd also happily accept an external PR to bump its version once your original PR goes in.

Thank you for reporting this!

**Comment by meyerder** [comment]
Will or can this make it into 9.5 as well?  Hopefully soon?

**Comment by yuri-tceretian** [comment]
I have found a similar bug with silence URL. https://github.com/grafana/alerting/pull/98 fixes it. Once it is merged I will backport both to v10 branch and update imports.

**Comment by yuri-tceretian** [comment]
Unfortunately, both fixes will not be in 10.0.0 as the PR that updated alerting module was merged too late. The fixes will be in the next patch release.
