### ISSUE TITLE
Bars mode cannot be overriden in "Series Override" tab

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#6643]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
4.0-beta1

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Linux

- What did you do?
Create a new graph panel, add one metric.
Set in Display tab: Lines: true
Go to "Series Override" and set for the metric above, Bars: true
- What was the expected result?
Bars show in series graph.

- What happened instead?
No bars show up. 
Note that when Bars are enabled in global Display tab they are correctly rendered.

**Comment by benrubson** [comment]
Related to #6528 ?

**Comment by torkelo** [comment]
seems to work fine in master & latest nightly build
