### ISSUE TITLE
[BUG] Invalid Y axis when enabling logarithmic scale 

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#6645]
* **I'm submitting a ...**
- [X] Bug report

Please include this information:
- What Grafana version are you using?
**4.0.0-beta1**

- What datasource are you using?
**Graphite**

- What OS are you running grafana on?
**Centos 7**
- What did you do?
Enable log scale on Y axis.

- What was the expected result?
Y axis should display ticks for large values. 1, 10, 1k, 1MIL, 10MIL,etc
![image](https://cloud.githubusercontent.com/assets/728853/20463902/dcdfb2ae-af45-11e6-99bb-fc726b1a4531.png)

- What happened instead?
Last tick on Y axis is 1K
![image](https://cloud.githubusercontent.com/assets/728853/20463895/a4165fae-af45-11e6-9552-8075de19fbce.png)

**Comment by torkelo** [comment]
already reported and fixed :) 
https://github.com/grafana/grafana/blob/master/CHANGELOG.md#bugfixes
