### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by santhoshmathsca** [grafana/grafana#6646]
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
    3.1.1
- What datasource are you using?
- What OS are you running grafana on?
   Ubuntu 14
- What did you do?
  Build from source
- What was the expected result?
   Build success
- What happened instead?
    Following error

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana@3.1.1~prebuild: grafana@3.1.1
6 silly lifecycle grafana@3.1.1~prebuild: no script for prebuild, continuing
7 info lifecycle grafana@3.1.1~build: grafana@3.1.1
8 verbose lifecycle grafana@3.1.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle grafana@3.1.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/santhosh/app/goprojects/src/github.com/grafana/grafana/node_modules/.bin:/home/santhosh/app/goprojects/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/santhosh/app/gradle-2.13/bin:/home/santhosh/app/java/jdk1.7.0_79/bin
10 verbose lifecycle grafana@3.1.1~build: CWD: /home/santhosh/app/goprojects/src/github.com/grafana/grafana
11 silly lifecycle grafana@3.1.1~build: Args: [ '-c', 'grunt' ]
12 silly lifecycle grafana@3.1.1~build: Returned: code: 1  signal: null
13 info lifecycle grafana@3.1.1~build: Failed to exec build script
14 verbose stack Error: grafana@3.1.1 build: `grunt`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid grafana@3.1.1
16 verbose cwd /home/santhosh/app/goprojects/src/github.com/grafana/grafana
17 error Linux 3.13.0-100-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error grafana@3.1.1 build: `grunt`
22 error Exit status 1
23 error Failed at the grafana@3.1.1 build script 'grunt'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grafana package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grafana
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grafana
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by torkelo** [comment]
could not replicate it on node v5.11 ,  try that. 

Also try 3.1.x branch, just pushed a build fix there

**Comment by santhoshmathsca** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v5.11.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v5.11.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.8.6
3 info using node@v5.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana@3.1.1~prebuild: grafana@3.1.1
6 silly lifecycle grafana@3.1.1~prebuild: no script for prebuild, continuing
7 info lifecycle grafana@3.1.1~build: grafana@3.1.1
8 verbose lifecycle grafana@3.1.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle grafana@3.1.1~build: PATH: /root/.nvm/versions/node/v5.11.1/lib/node_modules/npm/bin/node-gyp-bin:/home/santhosh/app/goprojects/src/github.com/grafana/grafana/node_modules/.bin:/root/.nvm/versions/node/v5.11.1/bin:/root/.nvm/versions/node/v5.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/santhosh/app/android-sdk-linux/bin
10 verbose lifecycle grafana@3.1.1~build: CWD: /home/santhosh/app/goprojects/src/github.com/grafana/grafana
11 silly lifecycle grafana@3.1.1~build: Args: [ '-c', 'grunt' ]
12 silly lifecycle grafana@3.1.1~build: Returned: code: 1  signal: null
13 info lifecycle grafana@3.1.1~build: Failed to exec build script
14 verbose stack Error: grafana@3.1.1 build: `grunt`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid grafana@3.1.1
16 verbose cwd /home/santhosh/app/goprojects/src/github.com/grafana/grafana
17 error Linux 3.13.0-100-generic
18 error argv "/root/.nvm/versions/node/v5.11.1/bin/node" "/root/.nvm/versions/node/v5.11.1/bin/npm" "run" "build"
19 error node v5.11.1
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error grafana@3.1.1 build: `grunt`
22 error Exit status 1
23 error Failed at the grafana@3.1.1 build script 'grunt'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grafana package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grafana
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grafana
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
