### ISSUE TITLE
Regex isn't working with Influxdb variable for creating key value pairs.

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana#66468]
**What happened**:

I referred below documentation for creating key value pairs in Grafana variable with Influxdb but unable to achieve it.

https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#filter-and-modify-using-named-text-and-value-capture-groups

With Prometheus it is working as expected but not with Influxdb.

![image](https://user-images.githubusercontent.com/89400147/231770175-8573a808-4c4e-4e8b-8aec-c12aad8aa6b4.png)

Regex Used: `/device_name="(?<text>[^"]+)|agent_host="(?<value>[^"]+)/g`

**What you expected to happen**:

It should display the output as below

```
Display Name => device_name
Value => agent_host
```

Note:Both device_name and agent_host are Tags here.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: influxdb:2.4.0
- OS Grafana is installed on: Ubuntu 22
- User OS & Browser: Windows - firefox
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
hello @Dhyanesh97 

Thanks for creating this issue,

however, GitHub is mostly for reporting bugs/errors
You are welcome to ask any general questions in our community forum.

I see you have already[ posted this question the forum](https://community.grafana.com/t/regex-isnt-working-with-influxdb-variable-for-creating-key-value-pairs/85880) . Great!  👍 

Closing this issue.
