### ISSUE TITLE
Can't add a new user to an organization

### ISSUE THREAD

**Issue by jeromegit** [grafana/grafana#6647]
- [ x] Bug report
I'm using Grafana 3.1.1 with Graphite on CentOs 2.6.

I'm trying to set up a new user with a new organization for which I already have at least 2 users.
I asked the new user to login using his AD (LDAP) creds.
As the Grafana admin, I do see the new user with the correct username, name and email since I'm using
[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

I have no problem adding the organization to the user and I do see the user when I look at the users associated with that organization.

However, when the new user logs in again, he doesn't see the new organization as part of his list of organizations. And as admin when I look at the user's profile the organization is gone and when I look at the organization, the user is gone.

What am I missing?

Please help.
(Thanks again for such a cool product, BTW!)

**Comment by torkelo** [comment]
when using LDAP you need to define mappings between ldap group and grafana organization,

http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync

**Comment by jeromegit** [comment]
Thanks, Torkelo!
