### ISSUE TITLE
ID 257467: [Supporting Platform - Simon - Annotations>Edit]: Horizontal scroll bar appears on the 'Annotations>Edit' screen after setting the pixels at 320*256 view port.

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#66487]
### **User Experience:** 
Low vision users will not be able to navigate through all the controls properly and might face challenges while navigating on the controls present on the page as the user would need to scroll a lot due to two-dimensional scrolling.
_Note: User credentials should not be included in the bug._

### **Pre-Requisite:** 
Achieve viewport 320 X 256 by adjusting the browser. (Open the developer's tool, resize, and zoom the browser to achieve viewport 320 X 256). 

### **Repro Steps:** 

1. Open #URL: [play.grafana.org](https://play.grafana.org/).  Sign in with valid credentials. "Home" page appears.  
2. Navigate the Feature Showcase pane heading and select it. 
3. Navigate the expanded Dropdown and select the "Edit" menu item. 
4. Navigate the page "Edit Panel" page which appears. 
5. Navigate to "Settings" button and select it. 
6. Navigate the "Annotations" tab item and select it.  
7. Navigate the "Annotations>Edit" screen. Verify the issue.

**Actual Result:** 
A horizontal scroll bar appears after setting the pixels at 320*256 view port on the 'Annotations>Edit' screen.

**Expected Result:** 
Horizontal scroll bar should not appear on the 'Annotations>Edit' screen after setting the pixels to 320*256 viewport. There should only be Vertical scroll bar on the page.
_Note: The same issue exists with "Variable" and "variable>New" screens. (Home>feature showcases>edit>setting>Variable). The same issue exists with "Alerting'" screen. e.g.  "Silences" tab (Home page>Alerting>Silences tab)_

### Severity:
`SEV2`

### **Area:**
?

**Comment by juanicabanas** [comment]
Gonna take a deeper look after another task

**Comment by juanicabanas** [comment]
This is also something related to Alerting team. See description @grafana/alerting-frontend

**Comment by torkelo** [comment]
Alerting???

**Comment by juanicabanas** [comment]
@torkelo it says in the description:
` The same issue exists with "Alerting'" screen. e.g. "Silences" tab (Home page>Alerting>Silences tab)`

Taking a quick look, /alerting/silences has a responsive bug
