### ISSUE TITLE
[bug] Hover with sort order = none with more than 10 metrics doesn't follow defined metrics order.

### ISSUE THREAD

**Issue by MarkBarbieri** [grafana/grafana#6648]
Grafana: Version 4.0.0-beta1 (commit: v4.0.0-beta1)
Datasource: influxDB 1.1.0
OS: Debian 8.6

When I add more than 10 metrics to the chart, the hover view displays the metrics in a jumbled order.

The display sort order is set to none.

When I remove 1 metric (leaving 10) the hover sort order shows as per the metrics order in edit mode

I expect when more than 10 metrics exist, this default sorting to the metrics order should persist

**Comment by benrubson** [comment]
Do you have 2 Y-axis in your graph ?
When you set sort order to none, series are at least ordered by Y-axis (so that tooltip first shows series from the left Y-axis, then from the right Y-axis).

**Comment by MarkBarbieri** [comment]
I do have 2 y-axis, but only one measure on left axis, all others on right axis.

If I disable 1 measure then the hover displays correctly and matches the Metric definition order.

If I enable back the last Metric, the order gets messed up.  It doesn't matter which one I disable, as long as only 10 or less are enabled.

**Comment by benrubson** [comment]
I have a 2 Y-axis graph with 10 series, series are first order by Y-axis, then by series letter (A, B, C, D, ...) from `Metrics` edit tab.

Do you have some screenshot from your use case ?

**Comment by MarkBarbieri** [comment]
What happens if you add an 11th metric to your chart?

10 Metrics (da4 is disabled).. Order matches the order in the editor
![10 metrics](https://cloud.githubusercontent.com/assets/18496759/20476238/0a1e8270-b024-11e6-8297-790a7711c629.PNG)

11 Metrics (note how the order is changed)
![11 metrics](https://cloud.githubusercontent.com/assets/18496759/20476239/0a7fe038-b024-11e6-8cab-0ed36dbec7e0.PNG)

**Comment by benrubson** [comment]
Still OK with 11 metrics.

10 metrics :
![screen shot 2016-11-21 at 10 00 34](https://cloud.githubusercontent.com/assets/6764151/20476509/893e7ac2-afd1-11e6-907e-44164121511d.png)

11 metrics :
![screen shot 2016-11-21 at 10 00 13](https://cloud.githubusercontent.com/assets/6764151/20476480/72f80ec2-afd1-11e6-9377-e67014dc15ee.png)

**Comment by benrubson** [comment]
What about legend labels ?
They should correspond to tooltip order when setting sort order to none.

**Comment by MarkBarbieri** [comment]
So I wonder what's causing my issue?  How do you suggest I try narrowing this down?

**Comment by MarkBarbieri** [comment]
![image](https://cloud.githubusercontent.com/assets/18496759/20476679/48f831c4-b026-11e6-8842-cc8d5d96f5f0.png)

**Comment by MarkBarbieri** [comment]
OK, I just added a new row in the same Dashboard and created a new Graph.
I added the same 11 metrics.
The only setting I changed was to add the legend to the right.
The metrics are in the order they were entered (ie: no manually moving metrics up or down)
All metrics are on the single (left) y-axis.

These metrics are from a mixed datasources, both InfluxDB.  Could multiple datasources be part of the problem?

Same problem

![image](https://cloud.githubusercontent.com/assets/18496759/20477787/71a4c43e-b02b-11e6-97f2-4b181a78ef90.png)

**Comment by MarkBarbieri** [comment]
New graph on same dasboard
Add the same measure 10 times, using single (not mixed) source
Named each metric 1-9, then AA,BB, etc
No other change
![image](https://cloud.githubusercontent.com/assets/18496759/20478103/d2775d02-b02c-11e6-9736-b66ed3adad3a.png)

Now duplicate the last line and add 11th called BB
Now number order is screwed up
![image](https://cloud.githubusercontent.com/assets/18496759/20478160/007fd67a-b02d-11e6-8046-2340431444f8.png)

**Comment by MarkBarbieri** [comment]
Definition of metrics, they're all the same, just different Alias BY
![image](https://cloud.githubusercontent.com/assets/18496759/20478222/461fba42-b02d-11e6-9814-d870c21a4ab9.png)

**Comment by MarkBarbieri** [comment]
If you look at all my mixed up version compared to the originals, the mix-up is the same
1st Legend item is 2nd on hover
2nd is 6th......
3rd,4th,5th didn't move
6th is 1st
The rest are OK

**Comment by MarkBarbieri** [comment]
And confirmed with a brand new dashboard.

**Comment by torkelo** [comment]
found the issue and fixed it :)

**Comment by benrubson** [comment]
@torkelo, you managed to reproduce this issue ?

**Comment by torkelo** [comment]
Yes, stacking with a bunch of series

**Comment by torkelo** [comment]
I don't think it has to with number of series, but how Javascript array sort works when compare returns zero, seems like it can still change order

**Comment by benrubson** [comment]
Yes, sounds like, it may alors depend on the browser used...
We should try to find a workaround.

**Comment by benrubson** [comment]
I think I've found something :)

**Comment by benrubson** [comment]
Solved by #6683 :)

**Comment by MarkBarbieri** [comment]
Thanks, looking forward to testing this
