### ISSUE TITLE
time series: hangs and won't render

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#66493]
**What happened**:

I converted an old time series visualisation to a new one, and now it won't render and hangs for 10s when interacting with it.

![image](https://user-images.githubusercontent.com/9749173/231815362-6a8eb704-0f5d-4779-85b5-845cf6d80d44.png)

![image](https://user-images.githubusercontent.com/9749173/231815389-8d431a8f-fcfa-4cce-8861-812f8477f0f9.png)

**What you expected to happen**:

The time series should render and not hang.

**How to reproduce it (as minimally and precisely as possible)**:

See the dashboard json: https://gist.github.com/uhthomas/901f92458a51f27e4dd8ae088a9314ae

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.3.6
- Data source type & version: Time Series
- OS Grafana is installed on: Linux (Kubernetes)
- User OS & Browser: chromium linux
- Grafana plugins: N/A
- Others:

**Comment by uhthomas** [comment]
Okay, so I've figured out what's causing it but I don't get why.

Given this dashboard: https://gist.github.com/uhthomas/b4cd2fb31192b27f374f9f8fce8a853b

Find the "PGs State" panel and set "Min" to "0". Then it freezes?

**Comment by leeoniya** [comment]
most likely it was fixed in 9.4.4+ by this: https://github.com/grafana/grafana/pull/59758

**Comment by uhthomas** [comment]
Possibly. I'll update Grafana and see if it's fixed.

**Comment by tonypowa** [comment]
hi @uhthomas 

if the update @leeoniya  referenced doesn't fix it , please feel free to reopen 👍
