### ISSUE TITLE
Adblok / uBlock Origin prevents loading plugins

### ISSUE THREAD

**Issue by oryband** [grafana/grafana#6649]
* **I'm submitting a Bug report**
- Version: `grafana-docker:3.1.1-1470047149`
- Ubuntu 14.04
- Docker 1.12.3

When trying to add several plugin graphs in any dashboard, specifically [grafana-heatmap-epoch-panel](https://github.com/mtanda/grafana-heatmap-epoch-panel), while using [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) (a popular [AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom) alternative), causes grafana to throw an error.

Disabling uBlock for our grafana domain fixes this. I've also seen this happen with [other plugins](https://github.com/savantly-net/grafana-heatmap), so this is probably not the fault of the plugin developer.

Perhaps until this issue is solved you should put a "please disable adblock" in bold somewhere in the tutorial and docs.

Error:
![grafana](https://cloud.githubusercontent.com/assets/115387/20481641/d2a717e0-aff0-11e6-87d7-6f6427c56398.png)

Chrome dev tools console output:
```
https://xxx.xxx.xxx/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js?bust=1479728395018 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
boot.1649cbaa.js:22 Plugin component error Error: Error: XHR error loading https://xxx.xxx.xxx/public/plugins/mtanda-heatmap-epoch-panel/heatmap.js?bust=1479728395018(…)
```

**Comment by torkelo** [comment]
is this just because the plugin contains the word heatmap?

**Comment by daniellee** [comment]
Can confirm this. I checked about 10 other plugins including Cal-Heatmap and they all work fine. Looking at the uBlock logger while testing a dashboard with heatmap-epoch, I got this warning:

![image](https://cloud.githubusercontent.com/assets/434655/25518944/18cb1808-2bf6-11e7-9c8c-84eb51d1bc63.png)

**Comment by daniellee** [comment]
A solution would be to get it whitelisted by sending a PR for the easylist EasyPrivacy list: 

https://github.com/easylist/easylist/blob/cd14bcf18c6572b61112ecf982cdc1d89bfe4381/easyprivacy/easyprivacy_whitelist.txt

**Comment by trinitronx** [comment]
This whitelist exception filter appears to work for uBlockOrigin:

    @@||grafana.example.com^*/heatmap.js$~third-party,xmlhttprequest

Fixes the blocked elements by allowing them, as long as the domain matches `grafana.example.com`.

Users will have to place this into the "My filters" page using the domain name they have set up for Grafana in order for it to work.
