### ISSUE TITLE
Fix bug that doesn't preserve time range selection when switching from Explore to Dashboard view

### ISSUE THREAD

**Issue by alyssabull** [grafana/grafana#66503]
When switching from a Google Cloud Monitoring query in Explore mode to Dashboard mode the selected time range is not preserved.

**Comment by khushijain21** [comment]
I'd like to work on this - how can I reproduce this ?

**Comment by asimpson** [comment]
@aangelisc @alyssabull this got resolved yes?

**Comment by aangelisc** [comment]
@asimpson this bug still exists but I don't believe it's an issue with GCM, I think this should be moved to either @grafana/explore-squad or @grafana/dashboards-squad

**Comment by ifrost** [comment]
> @asimpson this bug still exists but I don't believe it's an issue with GCM, I think this should be moved to either @grafana/explore-squad or @grafana/dashboards-squad

We have a task to address this in our backlog here: https://github.com/grafana/grafana/issues/72085. It's planned to be done in this quarter (by the end of October).

**Comment by asimpson** [comment]
Thanks @ifrost
