### ISSUE TITLE
Hide options in templating ignored - scripted dashboard

### ISSUE THREAD

**Issue by MrGreenRUS** [grafana/grafana#6650]
* **I'm submitting a ...**
- [*] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1

- What datasource are you using?
graphite

- What OS are you running grafana on?
SUSE 12.0

- What did you do?
scripted dashboard

- What was the expected result?
Try to use hide options in scripted dashboard.

- What happened instead?
Hide options ignored when dashboard loaded.

I use scripted dashboard, and i'm trying to use template with hide options, like
```
dashboard.templating = {
  enable: true,
  list: [
    {
        name: 'fqdn',
        query: fqdn,
        refresh: true,
        options: [''],
        current: {
          text: fqdn,
          value: fqdn
        },
        type: 'custom'
    },
    {
        name: 'fqdn_hidden',
        query: fqdn,
        refresh: 1,
        options: [''],
        current: {
          text: fqdn,
          value: fqdn
        },
        type: 'custom',
        hide: 2,
    }
  ]
};
```
but when dashboard loaded hide option is set in 0, and variable isn't hidden.

**Comment by torkelo** [comment]
you need to specify schemaVersion: 13  otherwise Grafana will think the dashboard schema is old and try to upgrade it (hide variable was previously name differently).
