### ISSUE TITLE
Firing an alert does not update 'alerts' table 'state' column from 'ok' when mysql backend is used.

### ISSUE THREAD

**Issue by psusan** [grafana/grafana#6651]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?

grafana_4.0.0-1479734199beta2

- What datasource are you using?

influxdb

- What OS are you running grafana on?

Ubuntu 14.04.5 LTS

- What did you do?

Creating any alert works well, it fires well, but it keeps alerting - ok - alerting - ok, till the trigger matches... I've checked the mysql table 'alerts' and the 'state' field, and it is keeping the 'ok' state, the alert does not change it, it stays 'ok', so it notifies again, as there is a "state change"...

The 'paused' state is updated properly.

- What was the expected result?

The state should be changed to alerting, or firing instead of keeping the ok state. 

It is the same behaviour regardless of the query or dashboard we're using.

**Comment by bergquist** [comment]
Not sure I understand this issue.

- Created a blank mysql database.
- Created a dashboard with an alert
- Executed with state "OK"
- Set a very low threshold value
- The alert triggered and was set to "Alerting"
