### ISSUE TITLE
Datasource variables are no longer implicit

### ISSUE THREAD

**Issue by keck-in-space** [grafana/grafana#66511]
**What happened**:

I recently updated my Grafana instance from 9.0.2 to 9.4.7. When I did this, my queries no longer worked if the database wasn't explicitly specified in the query. Previously, the query would succeed by referencing the datasource variable and the database name would be inferred. This no longer happens and I must specify that the variable be used in the query by using `$Database.`.

**What you expected to happen**:

My existing dashboards would work correctly upon updating, or this breaking change would be more clearly communicated in the docs. I searched "What's New" for every version beyond 9.0 and did not see this.

**How to reproduce it (as minimally and precisely as possible)**:

Create a query that depends on a data source variable to specify the database and do not put it in the query. The query will fail.

**Anything else we need to know?**:

**Environment**: RHEL 8
- Grafana version: 9.0.2 -> 9.4.7
- Data source type & version: MySQL
- OS Grafana is installed on: RHEL8
- User OS & Browser: Firefox Windows 10
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
hi @keck-in-space 👋 

thank you for creating this issue

is this happening with MySQL ? Any other datasource that you have tested?

also could you share one query and a screenshot of the variable configuration?

**Comment by tonypowa** [comment]
closing issue
if more help is needed, please provide more info and reopen
