### ISSUE TITLE
Grafana does not respect saved span with repeated panels

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#6653]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- **What Grafana version are you using?**
- 4.0.0-beta2
- **What datasource are you using?**
- InfluxDB, OpenTSDB
- **What OS are you running grafana on?**
- Ubuntu 16.04
- **What did you do?**
- Created templating query and two repeated panels with span = 6 using this template
- **What was the expected result?**
- With just one selection in template, it should provide 2 panels with span = 6 each
- **What happened instead?**
- Two panels with span = 12 generated

**Comment by torkelo** [comment]
you need to set the minSpan property

**Comment by rlex** [comment]
minSpan is set to 6, but this ticket is more about maxSpan

**Comment by robinsonjj** [comment]
have you tried saving the dashboard and refreshing? I sometimes find I have to do that when changing things on repeating panels.

**Comment by rlex** [comment]
Yeah, i tried. But turns out this is feature, not a bug: https://github.com/grafana/grafana/issues/2503

I ended up using repeated rows instead of repeated panels, and dashboard looks even better now.
