### ISSUE TITLE
Replace husky/lint-staged with nodejs-less precommit hooks

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#66547]
Using Husky/Lint-staged has a few downsides, mainly with yarn pnp it requires your node_modules be up to date in order to commit, which isn't great if you're not making frontend changes. I also think it would be faster to use a hook manager that doesn't have to 'pay the cost' of starting up nodejs.

[Lefthook ](https://github.com/evilmartians/lefthook) is an alternative that I've briefly investigated that could be useful. Importantly, it's a go-based precompiled binary that avoides nodejs/yarn pnp if not needed.

**Comment by joshhunt** [comment]
Also open to the idea of not auto-installing precommit hooks, and leaving it up to individual developers to install lefthook if they want.

**Comment by jdbaldry** [comment]
> Also open to the idea of not auto-installing precommit hooks, and leaving it up to individual developers to install lefthook if they want.

I'd be in favor of this. I find it to be both inconvenient for power users and a source of confusion for first time contributors.
I'd especially like to see the removal of any precommit hooks that make changes and stage those changes silently. I've seen a number of contributors confused that their Markdown has changed semantically without their knowledge.
