### ISSUE TITLE
Gauge Panel: Repeat options/Repeat by variable + Transform/Config from query results does not set maximum correctly only for the first value

### ISSUE THREAD

**Issue by anatoly-spb** [grafana/grafana#66544]
**What happened**:

Gauge panel sets maximum value only for the first value of the repeated variable with Transform/Config from query.

**What you expected to happen**:

I expect that maximum value from query will set correctly for all values of the repeated variable

**How to reproduce it (as minimally and precisely as possible)**:

Here are the details [Gauge Panel: Repeat options/Repeat by variable + Transform/Config from query results does not set maximum correctly](https://community.grafana.com/t/gauge-panel-repeat-options-repeat-by-variable-transform-config-from-query-results-does-not-set-maximum-correctly/85707)

**Anything else we need to know?**:

Let me know what else to share

**Environment**:
- Grafana version: v9.4.7 (4add91f03d) 
- Data source type & version: Prometheus 2.43.0
- OS Grafana is installed on: Desktop Docker For Windows 4.18.0
- User OS & Browser: Windows 10 Pro 64bit, Chrome
- Grafana plugins: default installation based on the official Grafana Docker image [grafana/grafana ](https://hub.docker.com/r/grafana/grafana)
- Others:

**Comment by tonypowa** [comment]
hi @anatoly-spb 
thank you for creating this issue

can you send us a snapshot of your panel's data?

this will help us mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by anatoly-spb** [comment]
hi @tonypowa 

thank you for your attention!

here is the [debug.json.txt](https://github.com/grafana/grafana/files/11252636/debug-rolis-coordinator%40postgres-distributed-2023-04-17.18_40_25.json.txt) debug file

**Comment by tonypowa** [comment]
no problem 👍  @anatoly-spb 

thanks for the debug json

this issue has been added to the Metric's squad board. They will get in touch with you with next steps

**Comment by gtk-grafana** [comment]
I think this belongs to @grafana/grafana-bi-squad (or maybe dashboards) as this appears to be a problem with the gauge panel options not being applied consistently to all panels when using repeating panels, and not anything unexpected in the data source.
