### ISSUE TITLE
Dashboards: Internal data links in dashboards don't navigate to Explore

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#66565]
### Background

In dashboards `splitOpenFn` is not passed, instead generated URL and href link is used. When we added tracking for internal data links in #65221 we changed the behavior so that onClickFn is always passed when generating the model. 

### Issues and steps to reproduce

* Create an internal data link with Loki
* Go to dashboards
* Click on a data link
* Nothing happens; Expected: the user is navigated to Explore

### Possible solutions

To bring back the previous behavior we skip the onClickFn if the split function is not provided.

**Comment by gelicia** [comment]
The PR referencing this wasnt linked properly when it was merged, but since it was merged I will close this ticket.
