### ISSUE TITLE
Invisible editor tabs in v4.0 Beta 2

### ISSUE THREAD

**Issue by alexanderlauster** [grafana/grafana#6657]
* **I'm submitting a ...**
- [X ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0.0 Beta 2
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Debian 8 x64
- What did you do?
Update to the new version from 3.1.1
- What was the expected result?
Tabs for editing graphs should be visible
- What happened instead?
No tabs are displayed and a JS issue appears in the console:
https://gist.github.com/alexanderlauster/e33ec4eadeaf33bb5d084bfbe35d31e9

![image](https://cloud.githubusercontent.com/assets/13642741/20499698/e2bd568e-b032-11e6-9de4-123ace429e5c.png)

**Comment by torkelo** [comment]
I am unable to replicate, what browser are you using?

**Comment by torkelo** [comment]
do you get tabs here?
http://play.grafana.org/dashboard/db/annotations?panelId=1&fullscreen&edit

**Comment by alexanderlauster** [comment]
I'm using Chrome 54 and yes, I get tabs on the demo side.
I tried to clear the cache etc, but nothing helps.

**Comment by torkelo** [comment]
did you restart grafana server after upgrade? play.grafana.org site is running beta2 (also upgraded from 3.1.1)
