### ISSUE TITLE
"Add to Dashboard" button in Grafana Explore doesn't add new panel

### ISSUE THREAD

**Issue by Condla** [grafana/grafana#66574]
**What happened**:
When I want to add a vis via “Add to dashboard” button in the explore mode, the dashboard opens, but there’s no panel, just an empty (or existing dashboard)

**What you expected to happen**:
A new panel is added with the query that I had entered in explore mode.

**How to reproduce it (as minimally and precisely as possible)**:
* Apparently this happens when the user an admin and can't be reproduced as Editor.
* Also it only happens, when the dashboard is opened in a new tab.
* it doesn't seem to be related to the query or data source (tested with a metrics and a logs query)
* Click Add to Dashboard in Explore mode --> Open in New Tab
* See screen recording attached.

https://user-images.githubusercontent.com/4442327/232033180-b9f31085-c5b8-4c5f-960d-87d41855e7f9.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v9.5.0-cloud.4.a016665c
- Data source type & version: Prometheus/Loki, not tested with others
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome/MacOS
- Grafana plugins:
- Others:

**Comment by juanicabanas** [comment]
This bug was fixed thanks to [this PR ](https://github.com/grafana/grafana/pull/66372/files)
