### ISSUE TITLE
Correlations: Revisit data link tracking

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#66570]
See https://github.com/grafana/grafana/pull/66567 for more context. 

We should map all possible flows and rethink how AppCore is passed for tracking. At the moment we set it to Explore, but there's no guarantee that the consumer of the link is in the context of Explore. At the moment we should be getting correct stats for Explore data links but current solution won't scale in the future.

**Comment by Elfo404** [comment]
Closing this as after removing tracking for correlation links this doesn't seem relevant anymore. If needed we most likely have to rethink how tracking correlation link clisk would work from the ground up.
