### ISSUE TITLE
ES2.3.5 cann't query

### ISSUE THREAD

**Issue by heijiu** [grafana/grafana#6659]
I Insert into ES2 like this
POST /test2/logs
{"method":"POST","ip":"10.0.0.100","url":"/index.php/index","status":200,"length":156,"ua":"Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; Redmi Note 3 Build/LMY47V) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30","referer":"","time":1479792241,"msec":1479792241163}

I setting Grafana data source
index name:test2
Pattern:no
Time field name:msec

in dashboard
add a table
query: status:200
metric: raw Document

it's OK

add a graph
query: status:200
Metric: count
Group by: date histogram msec
 
is error

{
    "root_cause": [
        {
            "type": "aggregation_execution_exception",
            "reason": "Invalid number format [epoch_millis#]"
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "test2",
            "node": "JDpza8ByRMy-SIGUQUW9Zg",
            "reason": {
                "type": "aggregation_execution_exception",
                "reason": "Invalid number format [epoch_millis#]"
            }
        }
    ]
}

I get request is

{"search_type":"count","ignore_unavailable":true,"index":"test2"}
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"status:200"}},"filter":{"bool":{"must":[{"range":{"msec":{"gte":"1479789842312","lte":"1479789902312","format":"epoch_millis"}}}]}}}},"aggs":{"2":{"date_histogram":{"interval":"50ms","field":"msec","min_doc_count":0,"extended_bounds":{"min":"1479789842312","max":"1479789902312"},"format":"epoch_millis"},"aggs":{}}}}

how fix it?

**Comment by torkelo** [comment]
Make sure you time field msec has index type of dare in your ES index mapping

**Comment by heijiu** [comment]
I Insert into ES like this( is a C program auto insert)
POST /test2/logs
{"method":"POST","ip":"10.0.0.100","url":"/index.php/index","status":200,"length":156,"ua":"Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; Redmi Note 3 Build/LMY47V) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30","referer":"","time":1479792241,"msec":1479792241163}

I Changed to ES 1.7 ,is OK, not change anymore
