### ISSUE TITLE
[Bug]: Server side PNG rendering does not use specified http_addr when doing local render call 

### ISSUE THREAD

**Issue by TimAldejohann** [grafana/grafana#6660]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
   Grafana v4.0.0-beta1 (commit: 61bb9cb)
- What datasource are you using?
   InfluxDB
- What OS are you running grafana on?
   Ubuntu 14.04.3 LTS
- What did you do?
   Tried to send Slack Alerts / Tried to export to PNG
- What was the expected result?
   Slack alerts  / Export of image
- What happened instead?
   No alerts were sent / Timeout 
Error in the Grafana log:
   `PhantomRenderer::renderToPng timeout (>30s)`

Debugging more, I located the exact `phantomjs` command via `ps` and execute it directly:

`/usr/share/grafana/vendor/phantomjs/phantomjs --ignore-ssl-errors=true /usr/share/grafana/vendor/phantomjs/render.js url=http://localhost:80/dashboard-solo/db/backups?from=1479709134948&to=1479709434948&panelId=1&width=1000&height=500 width=1000 height=500 png=/var/lib/grafana/png/6b3MoqgJYEQv7QPAM05p.png domain=example.com renderKey=xyz`

Which yields:

`[3] 21671`
`[4] 21672`
`[5] 21673`
`[6] 21674`
`[4]   Done                    to=1479709434948`
`[5]-  Done                    panelId=1`
`root@box2:/usr/share/grafana/vendor/phantomjs# url=<url> png=<filename> width=<width> height=<height> renderKey=<key>`

The process then hangs. After hitting enter it yields:

`[3]-  Done                    /usr/share/grafana/vendor/phantomjs/phantomjs --ignore-ssl-errors=true /usr/share/grafana/vendor/phantomjs/render.js url=http://localhost:80/dashboard-solo/db/backups?from=1479709134948`
`[6]+  Done                    width=1000`

It seems like the parsing of the arguments in `render.js` is reading the url parameters which leads to an error and stops `PhantomJS`. Replacing the url manually in the `PhantomJS` command with a url without parameters in it makes it working again. 

For our setup it is additionally needed that `localhost:80` is replaced with the hostname, otherwise `PhantomJS` will not be able to load the page with success. Could you add that to the Grafana configuration file?

**Comment by torkelo** [comment]
have you specified a http_addr in grafana.ini so localhost won't work?

**Comment by TimAldejohann** [comment]
Yes http_addr is specified with the right ip address.
