### ISSUE TITLE
Duplicate names in legend after aliasing

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#6661]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? v3.1.1
- What datasource are you using? influxDB
- What OS are you running grafana on? Windows 7
- What did you do? Used an alias which mapped many different names to one name
- What was the expected result? One entry on the legend (and preferably one colour for all lines)
- What happened instead? Multiple entries on the legend all with the same name

**Comment by bergquist** [comment]
If the query returns multiple series before you added the alias it will continue to do so.
You can use the alias pattern http://docs.grafana.org/datasources/influxdb/#alias-patterns to get a more informative name for each serie.

**Comment by robinsonjj** [comment]
I'm not sure you understood my problem (or maybe I am missing a trick!). I am deliberately using an alias which will reduce the number of uniquely named series so I don't want a more informative name.  I still expect the same number of series and the same number of lines on the graph, however I would expect them to be grouped in the legend so that the name only appears once given that they share the same name. If not a bug, at the very least this seems like a reasonable feature request? If there are multiple entries in the legend with the same name and same colour (using series specific overrides) I cannot see how this can possibly be helpful :/

For the time being I can get around this by using series specific overrides, which is what I am doing to ensure they are all the same colour as well. But this does limit the aliasing I can use since I need to be able to set one line to still appear in the legend, so I still need to have something in the alias to differentiate between the lines and hence the entry in the legend. 

E.g. I would like to be able to use the alias 'Monte Carlo Paths' but instead will have to use 'Monte Carlo Path $tag_path' so that I can set one of them to appear in the legend and hide the rest which means that the legend will then read 'Monte Carlo Path 0' despite representing all
