### ISSUE TITLE
Dropdown screen frozen in Ops

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#66619]
**What happened:**
When clicking on dropdown doing an override, the screen gets frozen

**What you expected to happen:**
The dropdown should be opened without freezing the screen

**How to reproduce it (as minimally and precisely as possible):**

- Go to any dashboard, override a field and open and click on `add override property` button

[See this thread](https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1681495273202529)

**Anything else we need to know?:**
A similar bug is happening in Explorer 
https://raintank-corp.slack.com/archives/CPP8JCNSE/p1681246325909089

Environment:

Grafana version: latest main (v10.0.0-54390pre at the time of testing)
Data source type & version: any
OS Grafana is installed on: Cloud
User OS & Browser: Chrome
Grafana plugins: any
Others:

**Comment by evictorero** [comment]
This was fixed on https://github.com/grafana/grafana/pull/66668
