### ISSUE TITLE
[Bug] Legend colors should be consistent across repeating panels

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#6662]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Windows 7
- What did you do? Used repeating panels where there was data missing for series
- What was the expected result? Expecting series to always have the same colours
- What happened instead? Same colour was inconsistently used for different series

I know that this has been mentioned before (#5509, #3250) but opening a fresh issue in the hope that this might be easier to solve in the restricted case of repeated panels and since they have been closed.

**Comment by torkelo** [comment]
series color is automatically assigned based on the order of the series returned, make sure you define a order in your metric query so they are returned in the same order for each panel. 

your can assign colors to series, this is done by linking the series name to color. You can also use series override to specify a series name regex to color mapping. 

to get the series name to match across panels is very hard as the data is coming in at different times, and for this to be implemented grafana would have to wait for all panels to complete before starting to render panels. 

https://github.com/grafana/grafana/issues/221
