### ISSUE TITLE
OpenTSDB metrics no long editable.

### ISSUE THREAD

**Issue by weiwu-sre** [grafana/grafana#66624]
**What happened**:
We upgraded Grafana from 8.3.x to 9.4.7. Our OpenTSDB metrics name no long editable.

**What you expected to happen**:
User should able to view full metrics name and edit existing metrics without re-typing entire metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Always reproducible.

**Anything else we need to know?**:

We have metrics name with template value, there is no way to edit the metrics name other than using dropdown + auto completion. Since there is template value, it will be more usable to make metric name field editable instead of using dropdown+autocompletion.

Is there any workaround or feature flag I can set to change back to old behavior/edittext ?

Please see attached video.

**Here is an example on 9.4.7**

https://user-images.githubusercontent.com/62574090/232169893-ae16fe31-9d6a-466b-9d98-92c79e614759.mp4

**Here is an example on 8.3.x**

https://user-images.githubusercontent.com/62574090/232169933-2276e955-5e9c-495b-88d0-0f049c01b1c8.mp4

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: OpenTSDB
- OS Grafana is installed on: Container runs on EKS / Amazon Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by weiwu-sre** [comment]
Looks like it is related to this change.

https://github.com/grafana/grafana/pull/54677

**Comment by bohandley** [comment]
Confirming that the metric component does not allow a user to edit the custom value entered.

The async select is the best option Grafana to both load options from an API call and to allow a custom value. The component does not allow for highlighting and editing of the value. 

I will reach out to our frontend development team to see if there is a better component or to see if we can update the SelectBase component the async is built with to allow for editing the value.

**Comment by foreverm10** [comment]
Has this problem been solved

**Comment by nitishgoyal13** [comment]
Is there any update on this? We are facing a similar issue. It's very difficult for developers to re enter the entire metric name which has templating enabled for the metrics

**Comment by bohandley** [comment]
Hi all! This problem has not been solved yet. We see the value in supporting developers' ease of use in editing the input with templating (variables). Unfortunately, changing the current implementation of the select input is outside the scope of the metrics squad and so we can ping the @grafana/frontend-ops so we cannot promise a fix, nor time estimate for this in the near future. 

We encourage the community to look into coming up with a solution for this UI issue though.
