### ISSUE TITLE
Permission on grafana

### ISSUE THREAD

**Issue by vermakush** [grafana/grafana#6663]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? 2.0
- What datasource are you using? graphite
- What OS are you running grafana on? centos

Hi, I don't want to show all Dashbord URL to user need to show limited dashboard to user like for production and admin created dashboard will only show production

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/2132
