### ISSUE TITLE
UX:  expand "Name" column width in dashboard list

### ISSUE THREAD

**Issue by kfirfer** [grafana/grafana#66635]
### Background / Why we're doing this

Capability to set a fixed expand width by grafana setup settings the `Name` column when scrolling to pick a dashboard

image:
![Screenshot from 2023-04-15 16-13-58](https://user-images.githubusercontent.com/7741545/232226131-f7e40066-55c0-487e-9644-2030f09af91d.png)

### Is there existing research for this?

Yes, I have linked it

### Problems or tasks

- A problem we're trying to solve
- A task the user needs to accomplish
- …

### Deliverables

- Figma mockup
- Miro board
- …

**Comment by StianOvrevage** [comment]
This is a huge problem since it's almost impossible to find the correct dashboard when using the widely used default dashboards that come bundled with `kube-prometheus-stack` (https://github.com/prometheus-community/helm-charts).

**Comment by StianOvrevage** [comment]
This is also a problem in the title of Dashboards as well (even on a 5000px+ wide screen):

![image](https://github.com/grafana/grafana/assets/6630005/e950d6a3-43fa-4c14-9e93-b9bb8707e08e)

**Comment by kfirfer** [comment]
seems like you fixed 
using version v10.2.2
