### ISSUE TITLE
[Bug] -  Problems with the values presented in grafana in singlestat

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [grafana/grafana#6664]
- What Grafana version are you using?
grafana-3.1.1-1470047149.x86_64

- What datasource are you using?
zabbix server 2.4 - alexanderzobnin-zabbix-app @ 3.1.2
![screenshot from 2016-11-22 11-35-16](https://cloud.githubusercontent.com/assets/19329445/20525792/369f9472-b0a8-11e6-9e2c-8ce06d0d924f.png)

- What OS are you running grafana on?
https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/
with epel centos 6.8 packages

- What did you do?
Get pfree disk space - vfs.fs.size[/,pused] - https://www.zabbix.com/documentation/2.4/manual/config/items/itemtypes/zabbix_agent

- What was the expected result?
    zabbix_get -s xxx.xxx.xxx.xxx -k vfs.fs.size[/,pused] = 61.421483
    zabbix_get -s xxx.xxx.xxx.xxx -k vfs.fs.size[/,pfree]  = 38.579115

- What happened instead?
The data collected by zabbix are correct but at the time of presenting them in grafana singlestat the value is incorrect.

![screenshot from 2016-11-22 11-30-53](https://cloud.githubusercontent.com/assets/19329445/20525586/4f4b3a90-b0a7-11e6-84a8-3a971187fc3e.png)

**Comment by torkelo** [comment]
can you show you singlestat options and chrome dev tools network tab (show response from zabbix)
