### ISSUE TITLE
Errors in datasource evaluation seem to result in NoData alerts

### ISSUE THREAD

**Issue by mmarko08154711** [grafana/grafana#66647]
**What happened**:
We upgraded from Grafana 9.2.5 to 9.4.7. Since then, we intermittently receive NoData errors but at all times a data series was available. In 9.2.5 we never receive such errors, although we always had throttling exceptions from time to time. The assumption is now, that such execution errors falsely trigger a NoData alert. This is bad for the one alert rule we have, which relies on a proper NoData error handling and expects alerts only on "real" NoData situations.

Unfortunately, we  are not able to easily verify this assumption, the only related info from the Grafana logs is this:
logger=expr rule_uid=<id> org_id=1 datasourceType=cloudwatch queryRefId=D datasourceUid=<uid> datasourceVersion=2 t=2023-04-14T00:52:10.299969674Z level=warn msg="Can't find response by refID. Return nodata" responseRefIds=[]

There is no information about eventual execution errors present.

**What you expected to happen**:
NoData must not be triggered when an error in the datasource evaluation happens.

**How to reproduce it (as minimally and precisely as possible)**:
For us it is happening with the Cloudwatch datasource, not sure how we could reproduce evaluation errors here.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: Cloudwatch 5.0.0
- OS Grafana is installed on: Debian
- User OS & Browser: Windows 11, Edge 112
- Grafana plugins: -
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @mmarko08154711 

try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to `debug` and note any errors. For printing to console, [set the console logs to `debug`](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1) as well.

**Comment by mmarko08154711** [comment]
Hi!
Sorry for the delayed answer.
It turned out, that this was fixed with https://github.com/grafana/grafana/pull/65574.
Therefore closing this ticket.
Thank you.
