### ISSUE TITLE
The datasource does not support alerting queries (CloudWatch)

### ISSUE THREAD

**Issue by shencan** [grafana/grafana#6665]
I'm submitting a ...
[x ] Bug report
 Feature request
 Question / Support request: Please do not open a github issue. Support Options
Please include this information:

What Grafana version are you using?
 Grafana v4.0.0-beta2 (commit: 56156fc)
What datasource are you using?
Cloudwatch
What OS are you running grafana on?
CentOS 6
What did you do?
Setup Alerting
What was the expected result?
Alert successfully created
What happened instead?
Error message came " The datasource does not support alerting queries"
Is Cloudwatch not supported for creating alerting queries?

**Comment by shencan** [comment]
![image](https://cloud.githubusercontent.com/assets/11796215/20530566/c47ba630-b10e-11e6-9d42-c4b94bc5cbbb.png)

**Comment by shencan** [comment]
Alter List  found error message 
tsdb.HandleRequest() error Could not find executor for data source type: cloudwatch

**Comment by bergquist** [comment]
Cloudwatch is not supported. https://github.com/grafana/grafana/issues/5858

**Comment by Bhawan23** [comment]
Hi @bergquist grafana dashboard is great, but please implement alerts for cloudwatch also as soon as possible.

**Comment by Stef3478** [comment]
And for elasticsearch as well please!

**Comment by erigaut** [comment]
+1 for elasticsearch alerting !

**Comment by starcwang** [comment]
And for zabbix as well please!!

**Comment by tom-experitest** [comment]
Just bumping up the request for elastic and cloudwatch 👍 
P.S - Grafana is awesome

**Comment by rayl15** [comment]
Anything yet over this?

**Comment by torkelo** [comment]
@rayl15 ? cloudwatch alerting support was added in v4.5

**Comment by rayl15** [comment]
I am sorry about this I was using $region variable in query hence facing issues.Resolved.Thanks

**Comment by sachinerosnow** [comment]
can you clarify what is $region variable
