### ISSUE TITLE
MariaDB: $__timeGroup error when combined with FROM_UNIXTIME

### ISSUE THREAD

**Issue by spencerw67** [grafana/grafana#66657]
**What happened**:
Read a MariaDb database table and group values by time (1d / 1h). My sql worked until the underlying structure of the table changed. The original grouping column (created) was of type datetime(6) and then a new column (created_ts) was added of type double. This original column’s values were all changed to null and the new column became unix time (e.g. 1681124411.7901478). Here is an example of a query that worked before the table change:
```
SELECT
  $__timeGroupAlias(created,1d),
  state AS "Grid"
FROM homeassistant.statistics
WHERE
  metadata_id = 168
GROUP BY 1
ORDER BY $__timeGroup(created,1d)
```
Because the original column now had null values, this now only returned 1 row.

I then tried the following, using the new column:
```
SELECT
  $__timeGroupAlias(FROM_UNIXTIME(created_ts),1d),
  state AS "Grid"
FROM homeassistant.statistics
WHERE
  metadata_id = 168
GROUP BY 1
ORDER BY 1
```
and received the following error: **interpolation failed: macro __timeGroup needs time column and interval.**

To check that the data was valid, I ran the following sql:
```
SELECT
  FROM_UNIXTIME(created_ts) AS "time",
  state AS "Grid"
FROM homeassistant.statistics
WHERE
  metadata_id = 168
GROUP BY 1
ORDER BY 1
```
and multiple rows were returned with datetime as e.g. 2022-06-20 16:00:11

**What you expected to happen**:
I expected the $__timeGroupAlias macro to be able to interpret the FROM_UNIXTIME result as a valid time column.

**How to reproduce it (as minimally and precisely as possible)**:
Create Mariabd table with at least "created_ts" type double and "state" type double.  Populate "created_ts" with unixtime values such as 1681725610.8492322.  

**Anything else we need to know?**:
I exported the table structure and some rows to a Mariadb running in Docker and used the above SQL in a separate Grafana instance also running in Docker and get the same error.  Docker is running on Debian hosts.

**Environment**:
- Grafana version: v9.4.7
- Data source type & version: Mariadb 10.6.10
- OS Grafana is installed on: Running as Home Assistant add-on (Home Assistant Operating System - Debian-based)
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by codeincarnate** [comment]
Unfortunately we don't have support for functions nested within macros. It requires parsing the SQL, a complicated problem that would require a massive effort relative to the payoff. Going to close this. May revisit if this becomes a priority.
