### ISSUE TITLE
UX: Add generated users initials in case if user doesn't have uploaded avatar

### ISSUE THREAD

**Issue by raphael-batte** [grafana/grafana#66679]
### Background / Why we're doing this

I noticed that if the user does not have an avatar in the enterprise dashboards, we show the initials in UI. Will be nice to implement this component as part of Grafana repo to allow reuse it as storybook component. 
![image](https://user-images.githubusercontent.com/102970268/232499420-cd5036f6-9e2a-4f64-8811-5917b485b7a5.png)

This will be good improvement step for OnCall schedules. Right now we use just gravatars. 
![image](https://user-images.githubusercontent.com/102970268/232500064-740ea2af-b758-4f61-bcc5-8bcfae49ac45.png)

### Problems or tasks

- A problem we're trying to solve
Better users representation and visibility across UI

### Deliverables

- Figma mockup

**Comment by staton-hyse11** [comment]
this work was complete
