### ISSUE TITLE
[Bug] Error message: Failed to save alerts

### ISSUE THREAD

**Issue by zax-slaughter** [grafana/grafana#6668]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? v4.0.0-beta2 (commit: c643466)
- What datasource are you using? https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.0-1479719016beta2_amd64.deb
- What OS are you running grafana on? Ubuntu 14.04.5 LTS
- What did you do? Made changes to existing alert (say changed duration in seconds) and clicked save button
- What was the expected result? No error message
- What happened instead? Error message appeared "Failed to save alerts." On consequent attempts a dialog "Someone else has updated this dashboard. Would you still like to save this dashboard?" appears with Cancel and Overwrite options. If Overwrite is chosen, "Failed to save alerts" appears again. Good thing that all changes seem to be saved, regardless of the error messages.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

![failed](https://cloud.githubusercontent.com/assets/5177922/20538557/9b94dbaa-b0a6-11e6-96c6-8562b93b3a27.png)
![overwrite](https://cloud.githubusercontent.com/assets/5177922/20538567/a0996832-b0a6-11e6-8e37-9e99fee48993.png)

**Comment by bergquist** [comment]
Please show the alert tab config page so we can see if the alert is correct.

**Comment by torkelo** [comment]
It looks like you do not have a threshold defined,  the other error looks the same as this https://github.com/grafana/grafana/issues/6576

**Comment by zax-slaughter** [comment]
I have setting HAS NO VALUE that doesn't ask for a threshold. Should I
upload screen capture to #6576
<https://github.com/grafana/grafana/issues/6576>?
