### ISSUE TITLE
User can see and in some cases install redundant deprecated plugins

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#66692]
## What happened:

As shown in this screenshot - 
<img width="1229" alt="Screenshot 2023-04-17 at 16 44 06" src="https://user-images.githubusercontent.com/19860021/232539473-2f1c14ae-4870-42b1-8243-a512b1584b1f.png">

Searching for "stat" on a new Grafana Cloud or OSS instance shows the user 3 different grafana lab provided plugins (amongst others):
- Singlestat (arrow logo)
  - overview claims "The Singlestat Panel is included with Grafana.", but as far as I can tell this is not the case. I believe this was the older angular plugin replaced by Singlestat 12.4, but left in for migrations? 
- Singlestat (12.4 logo)
  - overview claims "Note: Singlestat has been superseded by the Stat panel and is no longer available from Grafana 8.0." But in Grafana 9.5 I can still see "Install via grafana.com" and install into my instance.
- Stat

## What you expected to happen:

- New users should not see the deprecated plugins
- Users who already have these plugins installed from previous versions should be able to see them
- Overview/Readme text for Singlestat(arrow logo) is accurate i.e. when it _is indeed present_ it is there for compatibility and that users should migrate to the new Stat panel

## Anything else we need to know?:

Follow up to https://github.com/grafana/grafana/pull/66399

## Environment:
- Grafana version: 9.5 Cloud / 9.4.3 OSS
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tolzhabayev** [comment]
this solved by https://github.com/grafana/website/pull/13349
