### ISSUE TITLE
query inspector in explore, bottom of stats-panel not visible

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#66694]
if you run a query in Explore,  then open the query-inspector, choose the stats-panel, and there is so much data in the stats-panel that it will have scrollbars in it, it is not possible to scroll to the bottom of it. i mean, the last item in the stats's panel's contents will not be visible.

if you enlarge the query inspector & your browser window so that the stats panel does not need to have scrollbars in it, the last item will become visible.

this problem does not appear in dashboard-mode.

**Comment by Elfo404** [comment]
For whoever is gonna look at this, you don't need a huge set of data to reproduce this, reducing the inspector size is enough,  the content should def be easily accessible by scrolling
