### ISSUE TITLE
"View rule" page actually queries *all* rules every time, not just the rule requested

### ISSUE THREAD

**Issue by eamonryan** [grafana/grafana#66701]
## What happened: 
I am loading the page for a single alert rule and it can take a very long time to load if there are a lot of rules because it is querying for all the alert rules in the background instead of just the rule I asked for.

## What you expected to happen: 
I expect Grafana to only load the rule I asked for.

## How to reproduce it (as minimally and precisely as possible): 

- Setup Grafana with more than one alert rule (Prometheus/Mimir type in my case)
- Click on a single alert rule in the UI
- Check the developer console and see there is a request to `rules` that returns ALL rules / rule groups, not just the one you clicked on

## Anything else we need to know?:
Once you are at a high scale (thousands of rules) this becomes extremely noticeable. It's also counter-intuitive because if you jump to a page for a specific rule you expect it to load fast - not that it queries every single rule when you didn't ask for that.

## Environment:
- Grafana version: 9.4.x
- Data source type & version: Prometheus/Mimir/GEM/Grafana Cloud Metrics latest (true in all versions to date)
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox / Chromium
- Grafana plugins:
- Others:

Example screenshot showing I have loaded the page for a single rule, but the dev console shows many groups being returned:
![image](https://user-images.githubusercontent.com/11842311/232583974-6f60c48e-7fbb-4fc3-90da-ad12f275c862.png)

cc @gotjosh @johnheywardobrien 
```[tasklist]
```

**Comment by armandgrillet** [comment]
This will need backend changes before the frontend can work that way, which would make total sense BTW.

**Comment by grobinson-grafana** [comment]
I think the API in question here is `api/prometheus/grafana/api/v1/rules`. Unless we do a quick fix for just GMA, I think we will need to propose a new API for Prometheus, Mimir, Loki and Grafana that supports all these kinds of use cases, including filtering and searching like we did for GMA just last week.

**Comment by gotjosh** [comment]
We have completed the Prometheus changes in: https://github.com/prometheus/prometheus/pull/12270

The mimir changes are pending in https://github.com/grafana/mimir/issues/4792

Loki is a good shout - I think they don't get it for free anymore since they copied over the ruler files, so let me file an issue there.

**Comment by jquick** [comment]
Looks like this is fixed for navigation in the UI but still painfully slow on direct links. Sometimes we can see over 1.5m on a view load. Is it possible to use the new flow on direct links somehow?

**Comment by gotjosh** [comment]
I believe we've fixed this entirely - @konrad147 can you confirm on which version will the new changes ship?

@jquick what version of Grafana are you running?

**Comment by jquick** [comment]
After upgrading to v10.1.1 it seems its better but still around 10s to load:
![Screenshot 2023-09-21 at 7 50 44 AM](https://github.com/grafana/grafana/assets/574637/97584aca-eb41-4de6-8e3c-9d1c5fe41769)
Hitting a direct link:
https://grafana.pardot.dev/alerting/grafana/dd16ce7b-1bd8-4328-8056-03147f3926e0/view?orgId=1
