### ISSUE TITLE
Website: Build a plugin links to broken links

### ISSUE THREAD

**Issue by academo** [grafana/grafana#66720]
1. Go to https://grafana.com/docs/grafana/latest/developers/plugins/#ui-library
2. Click the `[Grafana UI library](https://grafana.com/ui).` link under the `UI Library section`
3. Observe the broken link

**Comment by tolzhabayev** [comment]
Seem to be fixed in `next` already https://grafana.com/docs/grafana/next/developers/plugins/#ui-library

**Comment by marefr** [comment]
I updated the issue description to denote it's latest that is wrong, next is correct as @tolzhabayev points out

**Comment by tolzhabayev** [comment]
ok both next and latest are now correct, closing this issue
