### ISSUE TITLE
[Bug] Template variable of measurement with ifluxDB not work

### ISSUE THREAD

**Issue by windery** [grafana/grafana#6672]
* Grafana version : 3.1.1
* Database : influxdb
* OS : Ubuntu 14.04 64bit
* Data Collector: collectd
* DB Measurements : cpu_, df_, disk_, irq_ ...
* DB Tags : host, instance, type ...

**Problem** : 

I create a template variable called `measurements`  with query `show measurements` and output of preview show the expected output: cpu_, df_ and so on. 
Then I create another variable called `host` with query `show tag values from $measurements with key = host;` and it reports an error "Templating Template variables could not be initialized: error parsing query: found (, expected identifier at line 1, char 22".

 I cannot use the variable `$measurements` to build other variables. But it shows the expected output when I execute the query "show tag values from cpu_,df_ with key = host;" on the web page of influxdb.

I just want to use measurements and tags as filters and I can choose it flexiblely. 

![bug](https://cloud.githubusercontent.com/assets/2854201/20551028/90eb771a-b176-11e6-86ae-ea5c3ac0cc3c.png)

**Comment by bergquist** [comment]
try `show tag values from "$measurements" with key = "host"`
