### ISSUE TITLE
Docs: does the keyword `auth` mean _authentication_, _authorization_, or both?

### ISSUE THREAD

**Issue by osg-grafana** [grafana/grafana#66736]
... does `auth` mean _authentication_, _authorization_, or both? I recommend spelling out this / these keywords.

_Originally posted by @osg-grafana in https://github.com/grafana/grafana/pull/66728#discussion_r1169785219_

**Comment by GrafanaWriter** [comment]
This is related to a keyword for search. Closing as wontfix.
