### ISSUE TITLE
[Bug]: Create dashboard API returns 500 if datasource does not exist but creates a dashboard!

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6673]
Please include this information:
- What Grafana version are you using? master
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Mac
- What did you do? I created a dashboard via HTTP API from json file using /api/dashboard/db api
- What was the expected result? Either dashboard should be imported with response status code is 200 OR dashboard should not be imported with response status code 412.
- What happened instead? dashboard was created and response status code sent back is 500.

This is happening because the datasource for my panels does not exist.

**Comment by utkarshcmu** [comment]
To reproduce the bug:
1. export any dashboard as json file.
2. change datasource field to something non-existent in grafana datasources.
3. use http api to create/update the dashboard.

**Comment by torkelo** [comment]
Can you print then error from grafana.log?

**Comment by torkelo** [comment]
Oh, and dashboard.json gist to reproduce would be great

**Comment by utkarshcmu** [comment]
This is the error from grafana.log:
```
EROR[11-22|23:15:19] Failed to save alerts                    logger=context userId=1 orgId=1 uname=admin error="Data source not found"
EROR[11-22|23:15:19] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db/ status=500 remote_addr=127.0.0.1 time_ms=50ns size=35
```
Because my dashboard has alerts in it and Grafana is able to save the dashboard but is not able to save the alerts as it cannot find the datasource.

**Comment by torkelo** [comment]
ok, fix the alerts then? 

The root issue for saving both dashboard and alerts in same backend call (where alerts fail):
https://github.com/grafana/grafana/issues/6576
