### ISSUE TITLE
PublicDashboards: Logs in public dashboard don't have any details

### ISSUE THREAD

**Issue by EdwardKuenen** [grafana/grafana#66750]
## What happened:
After publishing a dashboard as public the details of the logline are not shown. You get the message "No details available" instead.

## What you expected to happen:
When enabling the option 'Enable log details' it will be shown in the public dashboard.

## How to reproduce it (as minimally and precisely as possible):
Make a new dashboard and add a Logs panel with Loki as the datasource.
Make the dashboard public
View the details of the logline in the public dashboard.

## Environment:
- Grafana version: 9.3.4
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows / Chrome
- Grafana plugins: -
- Others: -

- In public dashboard
![no-details](https://user-images.githubusercontent.com/48517365/232760733-539833fe-e181-4052-8780-5ca16c63d520.PNG)
-In source for public dashboard
![with-details](https://user-images.githubusercontent.com/48517365/232760745-2f7374a4-4f5c-45f4-9eb5-dac6f054cff6.PNG)

**Comment by gabor** [comment]
when the loki datasource's backend-part generates the dataframes with the logs-data, it sets a custom attribute on the dataframe: `frame.custom.frameType="LabeledTimeValues"`. when running the dashboard as a public dashboard, this field is not received from the public-dashboard-backend. this causes the missing-details problem.

based on this info i think this should be handled by the @grafana/dashboards-squad . if you disagree, or need any info from the logs-squad, just ping. thanks!

**Comment by dprokop** [comment]
@evictorero seems like we are [intentionally sanitizing metadata on frame](https://github.com/grafana/grafana/blob/main/pkg/services/publicdashboards/service/query.go#L318). Why's that?

**Comment by evictorero** [comment]
We took this approach to not leak any sensitive information that the Metadata could contain. In this particular case, I think it makes sense to not sanitize this value. I will take a look as soon as possible.

**Comment by evictorero** [comment]
Related [PR](https://github.com/grafana/grafana/pull/55269). I have confirmed that not overriding this field fix this issue.

**Comment by evictorero** [comment]
Thanks for the context @gabor. This issue triggered an investigation about the actual reason for removing this field from Public dashboards response. We don't have control over how each data source is using it but it seems it is being used in the frontend and not containing sensitive info so we shouldn't remove it.
