### ISSUE TITLE
[Feature request] Show timestamp for last alert check

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#6677]
(I seem to be flooding you with issues :D)

In the alert overview, I want to display when an alert was last tested/executed.

E.g. "Ok for 19 hours. Last checked one minute ago....".

Two reasons I want this: 

1. #6599 - Makes it more visible that things are (or are not working)
2. If someone accidentally adds an alert with a 2 hour check interval it's nice to know.

**Comment by critikaster** [comment]
+1

**Comment by jkv** [comment]
It would also be nice to show when the next time the alert is expected to be checked.

"OK for 19 hours. Last check 15 minutes ago. Next check in 45 minutes."

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
