### ISSUE TITLE
[Bug]: HTTP API for deleting org returning incorrect message for a non-existing org

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6679]
- What Grafana version are you using? master
- What did you do? Ran following command where 45 is a non-existing org id:
```
curl -X DELETE http://admin:admin@localhost:3000/api/orgs/45
```
- What was the expected result? Output:
```
{"message":"Organization not found"}
```
- What happened instead? Output:
```
{"message":"Organization deleted"}
```

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/6722
