### ISSUE TITLE
ERROR : input data must be a wide series but got type not (input refid)

### ISSUE THREAD

**Issue by sherfyehia** [grafana/grafana#66809]
####################################It is working as dashbroad###################################
![2023-04-18_021001](https://user-images.githubusercontent.com/109470170/232914973-e5449023-7b99-4b48-bb53-36a428213c9a.PNG)

####################################It is NOT working as alert same query###################################
![2](https://user-images.githubusercontent.com/109470170/232915065-965b9ed1-47df-42e6-a2c8-f364fdd122ae.PNG)

## Environment:
- Grafana version: 9.4.7
- Data source type & version: sql database
- OS Grafana is installed on: Ubuntu 22.04.1 LTS
- User OS & Browser: root & root
- Grafana plugins:
- Others:

**Comment by zzz-iii** [comment]
As you can see [here](https://github.com/grafana/grafana/issues/46429), Grafana unfortunately doesn't support non-numeric alert data.

**Comment by sherfyehia** [comment]
I don't understand what happened but it is working ...

![3](https://user-images.githubusercontent.com/109470170/233148568-ba814e0c-0254-4afb-a21f-c865a7aabba2.PNG)

**Comment by saketbairoliya2** [comment]
@sherfyehia / @zzz-iii  - How did the above worked? Any idea - since Grafana doesn't support non-numerical values - above query should have failed with the error - correct?

**Comment by sherfyehia** [comment]
@saketbairoliya2  Really I don't know , but as you see column 1 >> string - column 2 >>> string - column 3 >>> int

**Comment by saketbairoliya2** [comment]
@sherfyehia  - This data is following the defined format for numeric data on Grafana: https://grafana.com/docs/grafana/latest/alerting/fundamentals/evaluate-grafana-alerts/#alerting-on-numeric-data-1

This is the reason that this worked.
