### ISSUE TITLE
[Bug?] Plugin Datasource - credentials not returned from server

### ISSUE THREAD

**Issue by petrslavotinek** [grafana/grafana#6681]
- What Grafana version are you using?
Master

- What datasource are you using?
Custom datasource - copy of InfluxDb with small changes

- What OS are you running grafana on?
Windows 10

- What did you do?
I created custom datasource plugin by copying existing InfluxDB datasource. (I just want to have an ability to include measurement name among columns in table output format.)
I converted all .ts files to .js.
Now I try to create a new datasource in Grafana. It works well, everything is saved into database.
However when the datasource is returned via api method GET /api/frontend/settings, the credentials are not returned - see the image.
When sending the request to create the datasource to api method POST /api/datasources, the credentials are there. They are also stored in the database. The request payload looks exactly the same as for native InfluxDB datasource.

![image](https://cloud.githubusercontent.com/assets/2470728/20569643/13c3ad72-b1a1-11e6-9e39-a96739e80292.png)

It looks like an issue in backend? Or did I do anything wrong?
Source: https://github.com/petrslavotinek/ene-grafana-influxdb 

- What was the expected result?
Credentials stored for custom datasource should be returned.

- What happened instead?
Credentials stored for custom datasource are not being returned.

Any help is really appreciated.
Thanks!

**Comment by torkelo** [comment]
The InfluxDB credentials are not returned for security reasons when using proxy access mode

**Comment by petrslavotinek** [comment]
Thanks for your reply. I'm using direct mode. Sorry I didn't mention it.
When I switch to native InfluxDB datasource it works.

![image](https://cloud.githubusercontent.com/assets/2470728/20570759/3300f7e0-b1a5-11e6-95e4-36bbf2caeadc.png)
