### ISSUE TITLE
Prometheus buildinfo is not deserialized correctly on the datasource setting page

### ISSUE THREAD

**Issue by mgyongyosi** [grafana/grafana#66827]
## What happened:

I clicked on the `Save & test` button then a success message appeared but its Details part is not properly deserialized.
<img width="1591" alt="Screenshot 2023-04-19 at 12 04 41" src="https://user-images.githubusercontent.com/1585112/233042751-6a270f4d-4f98-4c4d-ab0e-e00a76868f95.png">
## What you expected to happen:
I can see information related to the Prometheus server.

## How to reproduce it (as minimally and precisely as possible):
Go to the add new Prometheus datasource, fill in the required information, click `Save & test` and in the Success alert box click on the Details.
## Environment:
- Grafana version: 10.0.0-pre
- Data source type & version: Prometheus 2.43.0
- OS Grafana is installed on: Mac (development system)
- User OS & Browser: Mac, Chrome
- Grafana plugins: Prometheus
- Others:

**Comment by Yelmor** [comment]
This alert is removed since #66198, so no longer a problem.
