### ISSUE TITLE
When saving a Prometheus datasource the /api/v1/status/buildinfo req doesn't contain the Authorization header

### ISSUE THREAD

**Issue by mgyongyosi** [grafana/grafana#66829]
## What happened:
On the Prometheus datasource page, when I click on `Save & test` then a new request is initiated to Prometheus' `/api/v1/status/buildinfo` endpoint. Unfortunately, it doesn't go through the `AzureMiddleware`thus it doesn't contain the mandatory `Authorization` header. It can cause a slight issue (it doesn't break the functionality) when there is a auth proxy in front of Prometheus.

## What you expected to happen:
The outgoing request to the `/api/v1/status/buildinfo` contains the `Authorization` header.

## How to reproduce it (as minimally and precisely as possible):
Go to the Prometheus datasource page, setup the datasource, then click on `Save & test` then a new request is initiated to Prometheus' `/api/v1/status/buildinfo` endpoint. 

You can use the `auth/prometheus_oauth2_proxy_azure` devenv (make sure to remove the `skip_auth_routes` from the oauth2-proxy.cfg)
## Environment:
- Grafana version: 10.0.0-pre
- Data source type & version: Prometheus 2.43.0
- OS Grafana is installed on: Mac (development system)
- User OS & Browser: Mac, Chrome
- Grafana plugins: Prometheus
- Others: "Azure Authentication" is configured on the datasource page

**Comment by gtk-grafana** [comment]
@bohandley I think this might be resolved by the work you're doing on the health check, since we're moving that to the BE it should get treated like any other resource call now?

**Comment by bohandley** [comment]
It should! The work in this [PR](https://github.com/grafana/grafana/pull/66198) for the health check on the backend should go through the middleware, use any auth including Azure and return a clear error messages for unauthorized or incorrect auth configs.
