### ISSUE TITLE
[Bug?] Plugin Datasource - credentials not returned from server

### ISSUE THREAD

**Issue by petrslavotinek** [grafana/grafana#6682]
I'm sorry to re-open closed issue #6681 but the answer wasn't relevant. (I'm using direct access mode)

- What Grafana version are you using?
Master

- What datasource are you using?
Custom datasource - copy of InfluxDb with small changes

- What OS are you running grafana on?
Windows 10

- What did you do?
I created custom datasource plugin by copying existing InfluxDB datasource. (I just want to have an ability to include measurement name among columns in table output format.)
I converted all .ts files to .js.
Now I try to create a new datasource in Grafana. It works well, everything is saved into database.
However when the datasource is returned via api method GET /api/frontend/settings, the credentials are not returned - see the image.
When sending the request to create the datasource to api method POST /api/datasources, the credentials are there. They are also stored in the database. The request payload looks exactly the same as for native InfluxDB datasource.
**I'm using direct access mode. When I just switch to native InfluxDB datasource it works.**
The behavior is same when uploaded to our Ubuntu server where we run version 3.1.1.

![image](https://cloud.githubusercontent.com/assets/2470728/20569643/13c3ad72-b1a1-11e6-9e39-a96739e80292.png)

![image](https://cloud.githubusercontent.com/assets/2470728/20570759/3300f7e0-b1a5-11e6-95e4-36bbf2caeadc.png)

It looks like an issue in backend? Or did I do anything wrong?
Source: https://github.com/petrslavotinek/ene-grafana-influxdb 

- What was the expected result?
Credentials stored for custom datasource should be returned.

- What happened instead?
Credentials stored for custom datasource are not being returned.

Any help is really appreciated.
Thanks!

**Comment by torkelo** [comment]
username and password are currently restricted properties only special data source plugin ids gets access to the in frontend, but you can use jsonData object (in the data source edit page) to set custom properties, all will be accessible from fontend. 

See  
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/partials/config.html#L22

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.js#L18
