### ISSUE TITLE
Dashboard: All panels refresh when navigating from edit panel to dashboard page

### ISSUE THREAD

**Issue by shubh28** [grafana/grafana#66838]
I am using grafana version v9.3.2. We are pulling some data from amazon athena datasources and queries are quite large. We do not want these queries to be running automatically since there is cost associated with each time we query database. For this we have disabled the Refresh live dashboards option inside the dashboard settings. We have also enabled Hide time picker option from same set of settings. But still the dashboard refreshes when we navigate from edit panel screen to dashboard page. Is there a way this can be disabled? I want the dashboard to refresh panels only when we ask it to and not automatically. Does this have to do with configuration of grafana or version of it?

Edit: This seems to be happening after this change https://github.com/grafana/grafana/pull/51718/files

**Comment by axelavargas** [comment]
Hey, @shubh28 👋🏾 , thank you for reporting this issue 🙌🏾 . I was able to reproduce it, and I am moving it to our backlog to be prioritized. 

https://user-images.githubusercontent.com/239999/234592435-f7832885-5927-4bd6-9388-d78627e90cbe.mp4
