### ISSUE TITLE
Documentation of Azure Auth in Prometheus datasource

### ISSUE THREAD

**Issue by mgyongyosi** [grafana/grafana#66832]
Extend the documentation of the [Prometheus datasource ](https://grafana.com/docs/grafana/latest/datasources/prometheus/)with the Azure Authentication settings (it is behind the feature flag called `azure_auth_enabled`). 

Make sure that the documentation contains that `Azure Authentication` doesn't work correctly when `Forward OAuth Identity` is enabled.

More info: The `Authorization` header that has been set by the `ApplyAzureAuth` middleware gets overwritten with the `Authorization` header set by the `OAuthTokenMiddleware` here: https://github.com/grafana/grafana/blob/main/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go#L53

**Comment by itsmylife** [comment]
@lwandz13 Could you please provide an update about this?

**Comment by lwandz13** [comment]
I am out of the office 7/11/23 - I can look at adding this on 7/12 when I am back.

**Comment by itsmylife** [comment]
@mgyongyosi Do you think we need to clear OAuth related fields when azure auth is enabled?

**Comment by mgyongyosi** [comment]
> Do you think we need to clear OAuth-related fields when Azure auth is enabled? Or at least set that flag to false?

Do you mean the `X-ID-Token`? It shouldn't cause any issue, but I guess it can be removed. Just to be sure, could you please implement a test or test it on a development environment?

**Comment by itsmylife** [comment]
@mgyongyosi No, not that. Just setting the flag (`oauthPassThru`) in `jsonData` as false. So it will have no effect.
