### ISSUE TITLE
[Feature request]: Hide Graphs when no data points are present

### ISSUE THREAD

**Issue by siddhanathan** [grafana/grafana#6684]
Grafana shows the following message when no data points are returned by the query:

![screenshot from 2016-11-23 10-27-56](https://cloud.githubusercontent.com/assets/933964/20574019/94104c9a-b180-11e6-8bf4-a6618c6a08d5.png)

It would be useful if there was an option to hide the graph completely in such situations, so that it doesn't take up any space on the screen.

**Comment by torkelo** [comment]
closing as it similar to https://github.com/grafana/grafana/issues/4470  (can be solved together)
