### ISSUE TITLE
Azure Monitor metrics query not using correct dimension label

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [grafana/grafana#66858]
## What happened:
After upgrading to v9.4.7 noticed that the various panels in the included Azure/Insights/Cosmos DB dashboard are not using the appropriate label from the Dimension grouping on CollectionName. Instead of displaying the CollectionName as the label for the data series, the Resource name is being used for all of the labels.

![image](https://user-images.githubusercontent.com/14931768/233092016-3cb4eba6-d6fd-4fce-b1e3-2f8c2e0df6ea.png)

In the query inspector, I can see the collectionname level is present and correct.
![image](https://user-images.githubusercontent.com/14931768/233096608-933271e0-cfca-47e4-ad7e-15ee9074f5a0.png)

## What you expected to happen:
The unique CollectionName should show up for each of these data series.

## How to reproduce it (as minimally and precisely as possible):
Simply import the included Cosmos DB dashboard and point it to an Azure CosmosDB resource with multiple collections (or even a single collection for that matter).

## Anything else we need to know?:
NA

## Environment:
- Grafana version: v9.4.7
- Data source type & version: Azure Monitor v1.0.0
- OS Grafana is installed on: Linux (container)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins:
- Others:

**Comment by Blackbaud-ChrisBlythe** [comment]
After digging through the open issues, I believe this might be a dup of https://github.com/grafana/grafana/issues/63633

**Comment by Blackbaud-ChrisBlythe** [comment]
FWIW - This was working in Grafana v9.3.6.

**Comment by aangelisc** [comment]
This is a duplicate issue so I'll close this in favour of #63633 😊
