### ISSUE TITLE
[Feature request] Alert notifications to OpsGenie WebAPI

### ISSUE THREAD

**Issue by StianOvrevage** [grafana/grafana#6687]
Would much appreciate the possibility of sending alert notifications to OpsGenie (a service similar to but much cheaper than PagerDuty).

**Comment by nhproject** [comment]
Hi guys,

Amazing work on the new version!!
Any insight when the OpsGenie notifications integration will be available?

Keep up your phenomenal work!

Nitz

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/6856

**Comment by Duologic** [comment]
I was testing the OpsGenie integration on 4.1.2 but it doesn't seem to work:

```
Feb 20 21:06:44 log1.mv.redbee.nl grafana-server[1294]: 
t=2017-02-20T21:06:44+0100
lvl=eror 
msg="Failed to send notification to OpsGenie" 
logger=alerting.notifier.opsgenie 
error="Webhook response status 401 Unauthorized" 
body="{\"alias\":\"alertId-0\",\"apiKey\":\"[removed]\",\"description\":\"Test notification - http://grafana.internal/\\nSomeone is testing the alert notification within grafana.\",\"details\":{\"image\":\"http://grafana.org/assets/img/blog/mixed_styles.png\",\"url\":\"http://grafana.internal/\"},\"message\":\"Test notification\",\"source\":\"Grafana\"}"
```

Any chance this is a bug? :)

**Comment by dugeem** [comment]
Grafana 4.1.1 - OpsGenie integration is not working:

>t=2017-03-15T09:06:15+1100
lvl=eror 
msg="Failed to send notification to OpsGenie" 
logger=alerting.notifier.opsgenie 
error="Webhook response status 401 Unauthorized" 
body="{\"alias\":\"alertId-0\",\"apiKey\":\"https://api.opsgenie.com/v1/json/grafana?apiKey=removed\",\"description\":\"Test notification - http://fqdn.removed:80/\\nSomeone is testing the alert notification within grafana.\",\"details\":{\"image\":\"http://grafana.org/assets/img/blog/mixed_styles.png\",\"url\":\"http://
fqdn.removed:80/\"},\"message\":\"Test notification\",\"source\":\"Grafana\"}"

We were successfully able to push alerts to OpsGenie by using Alert type Webhook instead.

**Comment by DanCech** [comment]
@dugeem your log output appears to indicate that your config is incorrect, the apiKey should just be a string like "eb243592-faa2-4ba2-a551q-1afdf565c889" not a url like "https://api.opsgenie.com/v1/json/grafana?apiKey=eb243592-faa2-4ba2-a551q-1afdf565c889"

**Comment by kshcherban** [comment]
Have the same issue that OpsGenie integration throws 401

```
Sep  8 16:56:28 localhost docker/grafana[643]: t=2017-09-08T14:56:28+0000
lvl=eror msg="Failed to send notification to OpsGenie" 
logger=alerting.notifier.opsgenie error="Webhook response status 401 Unauthorized" body="{\"alias\":\"alertId-0\",\"apiKey\":\"some-api-key-secret-id\",
\"description\":\"Test notification - https://grafana.prod.example.com/\\nSomeone is testing the alert notification within grafana.\",
\"details\":{\"image\":\"http://grafana.org/assets/img/blog/mixed_styles.png\",
\"url\":\"https://grafana.prod.example.com/\"},\"message\":\"Test notification\",\"source\":\"Grafana\"}"
```

**Comment by daniellee** [comment]
@kshcherban are you sure your API Key is correct?

**Comment by kshcherban** [comment]
@daniellee yes, key was correct.

**Comment by cglrkn** [comment]
@kshcherban OpsGenie has 2 different Grafana integrations. GrafanaV1 works with "Webhook" option and GrafanaV2 works with "OpsGenie" option. It is not possible to use it another way since the endpoints that OpsGenie receives are different in each option so authentication fails when the wrong option is selected. OpsGenie released its webhook based integration first and later Grafana added OpsGenie as a native integration but they did not use the Grafana endpoint that OG set for GrafanaV1 Integration, they used the OpsGenie's Alert API endpoint. Thus, OpsGenie released GrafanaV2 integration to support the native OpsGenie integration in Grafana. I hope that information will solve your problem.

**Comment by kshcherban** [comment]
@cglrkn that actually explains the issue. GrafanaV1 integrations works correctly with latest stable 4.4 Grafana
