### ISSUE TITLE
Plugins: Refactor loading/initializing of plugins

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#66885]
Lots of things are going on in the [plugin loader](https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/loader/loader.go) and it's hard to extend it with new functionality without introduce lots of if/else/then checking plugin types and/or plugin classes (core, bundled, external) etc. A new thing we possibly want to add there is [OAuth service registration](https://github.com/grafana/grafana/pull/64981). 

Current things we do there among other things: 
- Initializer, only for backend plugins: https://github.com/grafana/grafana/blob/7808e74260037a63dfd1188363125f242818b4d8/pkg/plugins/manager/loader/loader.go#L165 
- Declare plugin roles: https://github.com/grafana/grafana/blob/7808e74260037a63dfd1188363125f242818b4d8/pkg/plugins/manager/loader/loader.go#L169 
- Process manager, only for backend plugins: https://github.com/grafana/grafana/blob/7808e74260037a63dfd1188363125f242818b4d8/pkg/plugins/manager/loader/loader.go#L218

Can we find a better way that would allow us to add new functionality when loading plugins without having to make changes to the loader and by that increasing separation of concerns? This should allow separating the loading of plugins (loader) and the running of backend plugins (initializer, process manager). Should also allow to write tests easier. 

This might also open up opportunities to refactor the [backend provider](https://github.com/grafana/grafana/blob/main/pkg/plugins/backendplugin/provider/provider.go) which currently dictates how backend plugins are instantiated. That could allow us to separate how different types of backend plugins decides how they're instantiated/started, e.g. app/datasource, secret manager, image renderer.

Some ideas worth exploring:
- Hooks-based approach. Introduce hooks for plugin loaded and plugin unloading (before it's being unloaded) that can have multiple implementations. 
- Event-based approach. Use the [bus](https://github.com/grafana/grafana/blob/7808e74260037a63dfd1188363125f242818b4d8/pkg/bus/bus.go#L43) and publish plugin loaded and plugin unloading events which can have multiple listeners. 

Some examples what this could look like using either hooks or an event-based approach:
- start backend plugin when a plugin with type=backend has been loaded
- stop backend plugin when a plugin with type=backend are being unloaded
- declare plugin roles when a plugin with roles has been loaded
- register with oauth service when a plugin has been loaded

**Comment by bhks** [comment]
This is a really great initiative which would also help us build solution for HA Grafana based installation for plugins. Let me know if I can help or join forces.

**Comment by marefr** [comment]
Fixed by #71438

**Comment by marefr** [comment]
There might be things mentioned above that is still not solved, eg. refactor the backend provider but might pick that up at a later stage since it's not stressing right now.
