### ISSUE TITLE
Prometheus: Add Victoria Metrics to prometheus type dropdown

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#66899]
**What is the chore?**:
Add victoria metrics to the dropdown options in prometheus data source config UI.

**Is there anything else we need to know?**:
Need to research if any VM versions don't support label/${name}/value endpoints with match[] parameters, and gate as needed.

**Comment by PatMis16** [comment]
I absolutely vote for this pull request.

**Comment by gtk-grafana** [comment]
Looks like VM added support for label/.../values match[] parameter in [v1.24.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.24.0), so we'll need dropdown values to differentiate before and after 1.24.0.
