### ISSUE TITLE
[Bug] Auto refresh not working

### ISSUE THREAD

**Issue by veerareddyganta** [grafana/grafana#6689]
- What Grafana version are you using? 3.1.1
- What datasource are you using? Influx db
- What OS are you running grafana on? centos
- What did you do?  Created a dashboard to monitor cpu using telegraf.
- What was the expected result? It should be refreshed every 5 seconds automatically as per auto refresh value -"5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
- What happened instead? Dashboard is not getting refreshed automatically.

**Comment by torkelo** [comment]
Strange, about 20 thousands installs of 3.1.1 and no report on auto refresh not working. 

- Can you check chrome dev tools for js errors? 
- Can you show the content of your chrome dev tools network tab after a few seconds, no requests?

- Does it say time picker look like this?
![image](https://cloud.githubusercontent.com/assets/10999/20589662/2f4b44a6-b21e-11e6-9e6a-79542aea9a9f.png)

**Comment by veerareddyganta** [comment]
It is not showing "Refresh every 10s" in my dashboard.
![dashboard](https://cloud.githubusercontent.com/assets/22466502/20590242/01f2d22e-b248-11e6-8452-8d723939939b.png)

**Comment by torkelo** [comment]
so if you click the Last 6 hours, you get a dropdown, there you have an option, Refresh every:  pick the refresh rate and hit apply button

**Comment by veerareddyganta** [comment]
Thanks.  It is working now.

**Comment by mrtristan** [comment]
just found this out the hard way too. please have an info tooltip or something next to the "auto-refresh" time options that says that these will be the selectable auto refresh intervals when selecting the auto-refresh in the dashboard time selector or something of that nature.

**Comment by frontalicious-martijn** [comment]
> so if you click the Last 6 hours, you get a dropdown, there you have an option, Refresh every: pick the refresh rate and hit apply button

I also wondered why auto refresh was not working, is it true that it only auto refreshes when you have a custom range?
