### ISSUE TITLE
Unable to compile from Source package !

### ISSUE THREAD

**Issue by VasantharajRajendran** [grafana/grafana#6690]
Grafana Version : Latest build 4.0

While trying to compile Grafana from Source, it shows error message. I tried to compile  Grafana lower versions too. but no luck, All failed with node-sass package install. Even I tried to install lower version of node-sass.

npm ERR! node-sass@3.13.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 install script 'node scripts/install.js'.

step followed to install:
1. go get github.com/grafana/grafana
2. cd $GOPATH/src/github.com/grafana/grafana
3. go run build.go setup
4. go run build.go build
5.npm install  
       Error comes when run this command

Version Details:
Go -> 1.7.2
Node -> 6.9.1
Npm -> 3.10.8

Someone please help

**Comment by bergquist** [comment]
What nodejs version do you use?

**Comment by VasantharajRajendran** [comment]
nodejs -> 6.9.1

**Comment by bergquist** [comment]
I guess you have tried npm install multiple times? 

Works fine for me and our buildserver at circle.ci :/

**Comment by VasantharajRajendran** [comment]
Ok, can you please how to fix it ?.

More detail Error message:
> node-sass@3.13.0 install /root/Projects/Grafana/src/github.com/grafana/grafana/node_modules/node-sass
> node scripts/install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/Projects/Grafana/src/github.com/grafana/grafana/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by torkelo** [comment]
just tested this on ubuntu 16 with nodejs 6.9.1,  npm install runs without error .

try removing node_modules dir and running npm install again

**Comment by VasantharajRajendran** [comment]
I'm using Ubuntu 14.04 LTS. 
I removed node_modules multiple times and run npm install. But no luck. still stuck with above mentioned error. 

is the error specific to OS ?.

**Comment by torkelo** [comment]
dont know, try installing with more npm logging

**Comment by MahekPavagadhi** [comment]
@torkelo 
I made few front end changes and tried to build it using 
npm install -g yarn
yarn install --pure-lockfile
npm install -g grunt-cli
grunt

npm version: 4.5.0
node version : v4.8.3 

On this step : 

> npm install -g grunt-cli

```
npm ERR! path /usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/once/node_modules/wrappy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/once/node_modules/wrappy'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/once/node_modules/wrappy']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/once/node_modules/wrappy' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/#####/.npm/_logs/2017-05-11T19_04_47_814Z-debug.log
```

Please help

**Comment by Chris7** [comment]
Two npm packages are not being installed, to fix it: `npm install node-sass phantomjs-prebuilt`

**Comment by MahekPavagadhi** [comment]
I did that. Still same error

**Comment by torkelo** [comment]
access denied error. Maybe wrong permissions on your "local global npm" folder. Fix the permissions or try `sudo npm install -g grunt-cli"

**Comment by MahekPavagadhi** [comment]
@torkelo It worked. Thanks!
