### ISSUE TITLE
change contact points often get exception

### ISSUE THREAD

**Issue by bossjie** [grafana/grafana#66907]
## What happened:
Edit a contact point,  toggle the "Disable  resolved message" on.  click button of "Save contact point" 
gets error like below pic

## What you expected to happen:
save successfully

## How to reproduce it (as minimally and precisely as possible):
Assume you have a list of contact points( 10 buckets)
Edit a contact point,  toggle the "Disable  resolved message" on.  click button of "Save contact point" 
it throws error at right top.  reclick that button. it succeeds.    I met several times, almost each time.

## Environment:
- Grafana version: 9.4.7
- Data source type & version: NA
- OS Grafana is installed on: centos 8
- User OS & Browser: chrome
- Grafana plugins: NA
- Others: NA

![image](https://user-images.githubusercontent.com/8426828/233275048-82200473-7fdd-4333-b4cc-2c53d796f470.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @bossjie 

I'm not sure I understand. can you please clarify? That error message seems very helpful, no?

**Comment by grobinson-grafana** [comment]
I've noticed this can happen when editing multiple contact points in different tabs at the same time. Is that what you experienced too?

**Comment by bossjie** [comment]
@grobinson-grafana yes, I did try open new tabs for different contact poins edit, from the contact points list.    From tech sense scope, it should be sinked into DB directly.  or any buffer/cache used on this section?

**Comment by armandgrillet** [comment]
This is due to all the contact points being saved all at once instead of one at a time, that's why we have this check. This is a limitation from the Prometheus Alertmanager API. We are now improving the error message in https://github.com/grafana/grafana/pull/67895
