### ISSUE TITLE
iPhone SE: Graphs disappear after refresh

### ISSUE THREAD

**Issue by eMobit** [grafana/grafana#66936]
## What happened:
We experience an issue while opening our Grafana dashboards using an iPhone SE (scrennshot_1.JPEG, scrennshot_2.JPEG).

Some of the graphs are disappearing while refreshing.
I can`t reproduce it with any other device and it seems to occur since we updated to this Grafana version.

Is there any known issue with this version / device?

## What you expected to happen:
We expect, all graphs (scrennshot_3.PNG) are visible after refresh

## How to reproduce it (as minimally and precisely as possible):
 iPhone SE, dashboard Link can't be provided because of company security policy

## Anything else we need to know?
In the .ZIP Archive you can find the Grafana Logs of the time interval (17.02. from 13:00 to 13:15), when the issue appears.

## Environment:
- Grafana version: Grafana V9.3.2 (21c1d14e91)
- Data source type & version: Azure Monitor
- OS Grafana is installed on: iPhone SE
- User OS & Browser: Google Chrome Version 112.0.5615.70, Safari iOS 16.4.1
- Grafana plugins: None
- Others: None

![scrennshot_1](https://user-images.githubusercontent.com/129160577/233333922-447d5e47-c8cd-4146-93bf-c2cd408e11a2.jpeg)

![scrennshot_2](https://user-images.githubusercontent.com/129160577/233333938-6991b339-8cd8-406e-acd9-00e5152148f4.jpeg)

![scrennshot_3](https://user-images.githubusercontent.com/129160577/233333961-1fd9290c-2ea8-4df8-aa32-c5b94d19b2ae.png)

[grafana.log.zip](https://github.com/grafana/grafana/files/11285051/grafana.log.zip)

**Comment by usmangt** [comment]
Thanks @eMobit,

This seems like a similar issue as already reported by other community users https://github.com/grafana/grafana/issues/63056
