### ISSUE TITLE
[Feature request] Google Analytics integration

### ISSUE THREAD

**Issue by rmsys** [grafana/grafana#6694]
- What Grafana version are you using?
 Grafana v4.0.0-beta2 (commit: 51f80af)

- What datasource are you using?
none

- What OS are you running grafana on?
AWS AMI (CentOS 6 x64)

- What did you do?
Integrate API Google Analytics

- What was the expected result?
Show Real Time users and others statistics

I searched for options to make this integration but nothing at all.
Is there any forecast of a datasource for this?

**Comment by torkelo** [comment]
no, but we hope to do a plugin for GA some day.

**Comment by rmsys** [comment]
There are any workaround for this? Maybe, using another recurse/app to make a 'bridged' between services?

**Comment by venkmanpeter** [comment]
a google analytics and maybe even google fireplace plugin would be great!

**Comment by gabosvk** [comment]
any update?

**Comment by lekkerdriveway** [comment]
Without native access in place pushing the GA stats to influxDB then pulling them into Grafana from there might work? See https://www.npmjs.com/package/analytics2influx

**Comment by vmadman** [comment]
+1
We're looking at https://www.npmjs.com/package/gatographite to see if that's a viable solution, for now.

**Comment by yamlCase** [comment]
+1

**Comment by sgovaard** [comment]
+1

**Comment by thangbn** [comment]
+1

**Comment by nbluis** [comment]
+1

**Comment by ratio91** [comment]
+1

**Comment by lucianopeixoto** [comment]
+1

**Comment by aramhakobyan** [comment]
+1

**Comment by unnisathyarajan** [comment]
+1

**Comment by zimmertr** [comment]
+1

**Comment by c00n84** [comment]
+1

**Comment by jleclanche** [comment]
Can you folks stop the +1s please, it's creating a lot of noise for the users who subscribed to this issue to actually be kept up to date with the issue. Use the 👍 reaction on the OP instead. And if you really want to see this, there's probably nothing more effective than contributing a PR.

**Comment by gengisb** [comment]
a quick question can't we just use the json plugin and expose google API rest webservices through another in-house webservice that will convert the data into expected json format?
