### ISSUE TITLE
[grafana] Alerts Migrated to Unified alerting show unhelpful values.

### ISSUE THREAD

**Issue by Desolar1um** [grafana/grafana#66953]
Hello all,

I've upgraded from v8.5.11 to v9.4.7 yesterday, and a lot of alerts were affected by the following:

Example: 

```
query: sum(logback_events_total{maintainer="team",level="error"})  by (service)
alert condition: classic_conditions: diff(A) > 0
```

Legacy alerting reports the following when an alert triggers
```
[[Alerting] Errors on the last 30s]
Value {service=service_name}
1
```

Unified alerting reports:
```
[[FIRING:1] Errors on the last 30s (id)]
**Firing**
Value: B0=1
Labels:
- alertname = Errors on the last 30s
- grafana_folder = folder
- rule_uid = id
```

Is this output with value: B0=1desired behaviour? As it would be very helpful for my team to continue to see the service name instead of B0. I managed to show it in a different part of the alert using {{ $values.B0.Labels.service }}, but ideally `Value` field should show inherited labels from the query if possible.

**Comment by grobinson-grafana** [comment]
Hi! A simple fix for the time being would be to change the alert rule from using a Classic Condition to Reduce expression. This will create one alert per service that exceeds the alert condition, and the service name will be included as a label.
