### ISSUE TITLE
Prometheus: Using template variables for labels in the code editor breaks autocomplete

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#66964]
Using template variables in the code editor breaks autocomplete. This is similar to [this issue](https://github.com/orgs/grafana/projects/112/views/22?filterQuery=prometheus+autocomplete&pane=issue&itemId=19087994).

1. using a template variable in a label value makes the subsequent label value not autocomplete.
2. using a template variable in a label name makes the subsequent label name not autocomplete and sometimes the label value of the template variable label name does not complete either.

https://user-images.githubusercontent.com/25674746/233386052-d099c965-4dbd-45b0-8b47-0dba11478600.mov

**Comment by itsmylife** [comment]
I cannot reproduce this on main. My setup is 
- I have a dashboard with a variable
<img width="561" alt="image" src="https://github.com/grafana/grafana/assets/820946/d8a08630-3d52-4ed9-95ed-3c44e1fd5a62">
- I have a panel and I am using that template and trying to have autocomplete, which works.

Am I missing something?

**Comment by bohandley** [comment]
@ismail, the issue is in interpolating already defined variables in the Prometheus code editor when writing a query.

If I am writing a query, 

`go_goroutines{instance="$myvariable"}`

The next label value will not show autocomplete results. It will stay blank (see video above).

`go_goroutines{instance="$myvariable", job=""}` <= the 'job' label should have a dropdown for label values autocomplete.

**Comment by itsmylife** [comment]
@ismail 👋
