### ISSUE TITLE
[Cloudwatch] Make it possible to specify access and secret key on the data source config page

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6697]
Makes it easier to start using the cloudwatch plugin and users wont require access to the server running Grafana.

**Comment by torkelo** [comment]
this seems very broken, Cloudwatch plugin edit page does not load :(  

js error, no encryptedFields on new/empty data source model. When did change from json secureJsonData?

**Comment by torkelo** [comment]
this is strange, frontend is still using seureJsonData but backend expects encryptedFields

**Comment by torkelo** [comment]
I do not understand the encryptedFields thing and TLSAuth, on the Datasource dto. They seem to both serve the same purpose of informing frontend of what encrypted properties have values. 

https://github.com/grafana/grafana/blob/master/pkg/api/dtos/models.go#L84

**Comment by torkelo** [comment]
think I found a simple way to refactor encrytedFields and TLSAuth into a secureJsonFields map[string]bool 
https://github.com/grafana/grafana/commit/330c1b945e4d6d9be2edfde2971fc6404ee73b1e

:)
