### ISSUE TITLE
Add option to Traces Visualization to remove/hide "Logs for Span" Button

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#66996]
## What happened:
The Trace Visualization has a button to link to corresponding logs, but not every plugin that supports traces is going to have corresponding logs to connect to. Right now it seems a bit strange to have a disabled button on every single span. Would be nice to have some way to hide these buttons in some cases.

<img width="622" alt="Screenshot 2023-04-20 at 2 00 20 PM" src="https://user-images.githubusercontent.com/6620164/233449792-43fbffae-42fd-4c49-9c96-04004544f3ef.png">

Code for this happens here: https://github.com/grafana/grafana/blob/main/public/app/features/explore/TraceView/components/TraceTimelineViewer/SpanDetail/index.tsx#L222

## Environment:
- Grafana version: 9.4.7
- Data source type & version: X-ray, Opensearch, probably others

**Comment by fabrizio-grafana** [comment]
Hey @sarahzinger 👋 !

We discussed about this in our squad and we thought that the easiest solution is simply to remove the button, without providing an option to whether it should be disabled or removed. [Here is the proposed change](https://github.com/grafana/grafana/pull/71448), if you want to have a look at it. Do you agree it could be OK, at least for now?

**Comment by sarahzinger** [comment]
@fabrizio-grafana makes sense to me! Thanks for taking a look!
