### ISSUE TITLE
CloudWatch plugin does not manage AWS/ApplicationELB metrics

### ISSUE THREAD

**Issue by yesteph** [grafana/grafana#6699]
Hello,

Grafana version : 3.1.1
OS :Centos 7
DataSource : SQLITE3

With a CloudWatch DataSource, in the list of metrics, I do not see "AWS/ApplicationELB", only "AWS/ELB" is present to monitor LoadBalancers.

See attached screenShot.
<img width="1342" alt="screen shot 2016-11-24 at 16 35 56" src="https://cloud.githubusercontent.com/assets/1999342/20603972/55994ce8-b264-11e6-882d-65bfa41d1668.png">

Thank you.

**Comment by torkelo** [comment]
you need 4.0 for that, was added after 3.1
