### ISSUE TITLE
Spinner component [design]

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#67003]
**Goal:**

Add this interactive component in our Figma, to match [Storybook](https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-spinner--basic).

**Comment by khushijain21** [comment]
I'd like to work on this, is it open?

**Comment by natydej** [comment]
[Branch](https://www.figma.com/file/Ogk0GbZ58Q5diaCIdFgLjc/Spinner-and-LoadingPlaceholder-Component?node-id=8444-13515) ready to review
-Added `Spinner` component to be interactive.

**Comment by natydej** [comment]
Branch merged and published

Next steps:

- [ ] Add this component to the **Light theme library**.
