### ISSUE TITLE
CloudWatch plugin does not manage IAM role inside ECS

### ISSUE THREAD

**Issue by yesteph** [grafana/grafana#6700]
Hello,

Grafana version : 3.1.1
OS : ECS service (official grafana/grafana docker image)
DataSource : RDS PostgreSQL

I run grafana as an ECS service with official Docker image : grafana/grafana.
The ECS service "grafana" has an IAM role "ecsGrafanaRole".
My ECS service is running on ECS container instances (EC2 VM) with an instance role "ecsInstanceRole".

My problem is when running in an ECS task, grafana tries to retrieve permissions as if it was running on a standard EC2 VM, not like an ECS service. 
I conclude this because the grafana logs refers to ecsInstanceRole, not ecsGrafanaRole : "AccessDenied: User: arn:aws:sts::XXXXXXXXX:assumed-role/ecsInstanceRole/i-XXXXXXX is not authorized to perform: cloudwatch:ListMetrics"

Documentation  indicates CloudWatch plugin uses AWS SDK : "Currently all access to CloudWatch is done server side by the Grafana backend using the official AWS SDK. If you grafana server is running on AWS you can use IAM Roles and authentication will be handled automatically."

AWS documentation indicates the authentication on ECS should be transparent if a recent SDK is used (July 2016) : [http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task-iam-roles-minimum-sdk](url). 

Maybe this is not the case ?

To get things working, I must update IAM policy of the ECS container instances which is bad!

Thank you.

**Comment by mtanda** [comment]
Hi, 

Grafana backend overwrite default credential chain.
https://github.com/grafana/grafana/blob/v4.0.0-beta2/pkg/api/cloudwatch/cloudwatch.go#L59

I think need to change these line like following.
https://github.com/aws/aws-sdk-go/commit/9aaa151e05c6ce19f588b41d43178ee38b141704#diff-45fe98a2ff006cc79efd984a1cf9a648R93

**Comment by yesteph** [comment]
Yes, need to use ecsCredProvider.
