### ISSUE TITLE
[TraceQL] Support new scoped tags endpoint

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#67011]
Tempo recently added a new tags endpoint that returns tag names organized by scope.

https://github.com/grafana/tempo/pull/2282

Example:
```
$ curl -G -s http://localhost:3200/api/v2/search/tags  | jq
{
  "scopes": [
    {
      "name": "span",
      "tags": [
        "article.count",
        "http.flavor",
        "http.method",
      ]
    },
    {
      "name": "resource",
      "tags": [
        "k6",
        "service.name"
      ]
    },
    {
      "name": "intrinsic",
      "tags": [
        "duration",
        "kind",
        "name",
        "status"
      ]
    }
  ]
}
```

This will allow better intellisense when a user has typed `resource.` or `span.`

cc @09jvilla

**Comment by 09jvilla** [comment]
Thanks for creating this @joe-elliott ! Excited about this issue and how it will improve the new TraceQL search!
cc @adrapereira
