### ISSUE TITLE
docs: provide guidance on use of PanelProps for plugin developers

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#67026]
Currently we only have a tutorial https://grafana.com/tutorials/build-a-panel-plugin/ which provides a very brief reference and then links to [3 year old code](https://github.com/grafana/grafana/blob/747b546c260f9a448e2cb56319f796d0301f4bb9/packages/grafana-data/src/types/panel.ts#L27-L40) which has changed.

We should look to provide guidance within our main documentation, ideally with sample code.
```[tasklist]
- [ ] Need update for "Build a panel plugin" doc
```

**Comment by josmperez** [comment]
@sympatheticmoose -Has the recent update to the panels tutorial satisfied this issue? Please close this or clarify what remains to be done.

**Comment by josmperez** [comment]
@oshirohugo - Would you look at the panels tutorial to see if this issue is adequately resolved, and (if not) assist me in drafting updates to the examples/tutorials? Some time in Q4 would be great.

**Comment by sympatheticmoose** [comment]
@josmperez - no, we still don't explain this particularly well.

Suggest grabbing time with someone from @grafana/plugins-platform-frontend to discuss https://github.com/grafana/grafana/blob/a546db4b3a8267a2da25e7e36a14a0df1eb9e58d/packages/grafana-data/src/types/panel.ts#L74C1-L122C2 

From that discussion, try to decide if "Working with PanelProps" warrants a docs page in its own right, or whether it could be folded into other content. I think its likely that it would be beneficial to describe these in a little more detail and provide/link to examples of their usage. I believe the eventBus in particular could use more guidance given we have restrictions on its usage by plugins.

**Comment by josmperez** [comment]
@academo - Can you please take a look at this issue and we can discuss next week?

**Comment by academo** [comment]
@josmperez ping me in slack and we can arrange what work we can provide to clarify it

**Comment by josmperez** [comment]
Esteban and I met to discuss PanelProps and we agreed to begiin with a small task of improving the relevant code comments. This may be all that is required; will evaluate when that's done.

**Comment by sympatheticmoose** [comment]
Looking at the code comments PR, this particular concern remains:
>  I believe the eventBus in particular could use more guidance given we have restrictions on its usage by plugins

**Comment by sympatheticmoose** [comment]
@academo we still offer no guidance on the eventbus?

**Comment by josmperez** [comment]
I've opened https://github.com/grafana/grafana/issues/79431 for handling leftover task.
