### ISSUE TITLE
Resource peaks in Grafana every 5 minutes

### ISSUE THREAD

**Issue by JAAnguloCanovas** [grafana/grafana#67035]
## What happened:
Hello,

We currently have Grafana version 9.3.6 with unified_alerting enabled deployed through Helm Chart in Kubernetes. We use victoria-metrics for querying and storing metrics and we found while checking the resources of both Grafana and VictoriaMetrics that every 5 minutes there are considerable spikes in the CPU and memory usage of both tools.

We think it is due to alerting, but we are not sure and we would like to solve this problem as the resource consumption is very high.

Can you help us?

Thank you very much.

## What you expected to happen:

We would like the resource consumption of both Grafana and Victoria Metrics to be stable and not have peaks every 5 minutes.

## Anything else we need to know?:

![image](https://user-images.githubusercontent.com/128470256/233603461-0c98a96a-41f2-4bfd-8bfa-08dcd4a89b94.png)

![image](https://user-images.githubusercontent.com/128470256/233604125-e7dcc1aa-8a4a-44d1-9e10-7e912a0fc4f4.png)

## Environment:
- Grafana version: 9.3.6
- Data source type & version:
- OS Grafana is installed on: Kubernetes / Helm Chart
- User OS & Browser: Chrome / Firefox / Safari / Edge
- Grafana plugins: 
- Others:

Configmap from Grafana

_apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: grafana
  uid: ae81f8d7
  resourceVersion: '1125841717'
  creationTimestamp: '2023-03-03T10:52:35Z'
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.3.6
    helm.sh/chart: grafana-6.50.6
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: grafana
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-03-23T12:11:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:grafana.ini: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
    - manager: node-fetch
      operation: Update
      apiVersion: v1
      time: '2023-04-05T08:40:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:plugins: {}
  selfLink: /api/v1/namespaces/grafana/configmaps/grafana
data:
  grafana.ini: |
    [alerting]
    concurrent_render_limit = 8
    enabled = false
    max_annotation_age = 24h
    [analytics]
    check_for_updates = true
    [annotations]
    cleanupjob_batchsize = 20000
    [annotations.api]
    max_age = 6M
    [annotations.dashboard]
    max_age = 6M
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [plugins]
    allow_loading_unsigned_plugins = goshposh-metaqueries-datasource
    [server]
    domain = grafana.domain.com
    enable_gzip = true
    [unified_alerting]
    enabled = true
    ha_advertise_address = ${POD_IP}:9094
    ha_listen_address = ${POD_IP}:9094
    ha_peers = grafana-headless:9094
  plugins: >-
    instana-datasource,farski-blendstat-panel,yesoreyeram-boomtable-panel,yesoreyeram-infinity-datasource,jdbranham-diagram-panel,natel-discrete-panel,agenty-flowcharting-panel,pierosavi-imageit-panel,simpod-json-datasource,marcusolsson-json-datasource,grafana-piechart-panel,natel-plotly-panel,vonage-status-panel,grafana-worldmap-panel,https://github.com/GoshPosh/grafana-meta-queries/archive/refs/tags/0.0.9.zip;goshposh-metaqueries-datasource,flant-statusmap-panel,grafana-athena-datasource,grafana-timestream-datasource,grafana-oncall-app,grafana-redshift-datasource
binaryData: {}_

**Comment by gillesdemey** [comment]
Hi! Have you tried disabling `unified_alerting` to narrow down if this is the culprit? Can you share some more details on what kind of alert rules you have configured – how much data is being queried and what contact points are set up?

**Comment by JAAnguloCanovas** [comment]
Hi @gillesdemey gracias por tu respuesta!

We cannot disable unified_alerting as it is a production environment and would affect many machines.

On the other hand, we have configured alerts for prometheus datasources, elasticsearch datasources and Instana datasources.

We query several teras of data and have thousands of alerts configured, if you need I can make the query you tell me to the database to extract any kind of information

Regards!

**Comment by grobinson-grafana** [comment]
Hello! 👋 It's possible that this is related to Grafana Alerting, in particular if your alerts are using range queries instead of instant queries. Do you know which kind of query you are using?

**Comment by JAAnguloCanovas** [comment]
Hello @grobinson-grafana, I think it's related to what you say, most queries are of the range type

![image](https://user-images.githubusercontent.com/128470256/234497406-687eefbd-e424-4c26-90d1-fef203ad9b25.png)

Thanks for the answer! Do you know of any way to alleviate this? I don't think we can modify the query type

**Comment by JAAnguloCanovas** [comment]
Thanks!! I will talk to the teams and we will change the type of alert to see if we can reduce the load, thank you very much!

**Comment by JAAnguloCanovas** [comment]
@grobinson-grafana Maybe you can help me with this problem too 
![image](https://user-images.githubusercontent.com/128470256/234555814-1869fd0f-83cf-4003-b926-614ca60d41ef.png)

We are trying to eliminate the datasources that return these errors for each organisation, do you know if I can extract this information from the database, so we don't have to go organisation by organisation pointing the names of the datasources?

Thanks in advance!

**Comment by grobinson-grafana** [comment]
Could you make a separate issue for that please? :slightly_smiling_face:

**Comment by VikaCep** [comment]
Sounds like this issue was solved.
