### ISSUE TITLE
Cannot delete alert rules with File Provisioning

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#67036]
## What happened:

It seems that you cannot delete alert rules that were provisioned using file provisioning with file provisioning. You have to manually use the Provisioning API instead.

**What I tried:**

1. Deleting the Yaml file
2. Changing the Yaml file to contain an empty Rule Group with no rules

```
apiVersion: 1
groups:
    - orgId: 1
      name: Test
      folder: Test Folder
      interval: 1m
      rules: []
```

In both examples my provisioned rules were still there after restarting Grafana. 

## Environment:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by chenjie4255** [comment]
Is this issue fixed? I tested both grafana 9.5.2 and grafana 10.0.0, and the rules are still there even if the provisioned file is deleted or the corresponding rule is removed from the provisioned file.

**Comment by tsvetko-work** [comment]
There is a section in the sample.yaml file called:
deleteRules

You need to add the orgId and uid of the corresponding rule in that list.
Tested on Grafana 9.5.2.

**Comment by JohnMops** [comment]
Any plans to implement auto deletion when the congimap is deleted, same as dashboards?

**Comment by gittyabhay** [comment]
Did anyone figure out the solution here, i am not able to delete the provisioned alert using both the method:
1. using the API DELETE /api/v1/provisioning/alert-rules/{UID}
2. by delete the alert provision file

**Comment by IvanaH8** [comment]
We are experiencing the same issue. We used Grafana previously without persisting anything to a database but only using file provisioning. Then we upgraded to Grafana version 10.1 and started also using the database. Now we would like to delete the alerts created and provisioned way before but it does not seem to work using the `deleteRules` in the configuration file for deleting alert rules as documented under [provision alert rules](https://grafana.com/docs/grafana/v10.1/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules).

However, when I created a new rule via UI recently and provisioned it, I was able to delete it using the above approach. But this rule had a uid in the from of UUID (coming from the database), while our ancient provisioned alerts have very simple 8 character uid.

How can we delete those alerts from Grafana?

**Comment by timo1707** [comment]
+1
on the api or postgres db i also cannot find those alerts.
the deleteRules in the helm chart had neither effect.

**Comment by xdoncalvox** [comment]
Have anyone figure out a solution?

**Comment by IvanaH8** [comment]
We have just managed to delete the provisioned resources with `deleteRules`, etc. Our Grafana is deployed with helm charts and kubernetes workloads on internal Google Cloud. It turned out that it was not picking up the changes in the kubernetes generated config maps. Restarting the pod in which Grafana runs did the trick and it is now again picking up any changes to config maps

**Comment by timo1707** [comment]
@IvanaH8 : can you please share your deleteRules part from your values.yaml? 
I tried that but wasn't working. I assume you add the orgID and rule uid?

**Comment by IvanaH8** [comment]
@timo1707 indeed, I created a `delete_rule.yaml` file (which I added to kustomization.yaml file for kubernetes to include it in building config maps) and it contains exactly what is said just under [Provision alert rules](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules) with `NtMLUTl4k` being the uid of the rule I wanted to delete:

```python
# config file version
apiVersion: 1

# List of alert rule UIDs that should be deleted
deleteRules:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> unique identifier for the rule
    uid: NtMLUTl4k
```

Note that I also deleted this rule from `alert_rules.yaml` file which contains our provisioned rules.

**Comment by YunanJeong** [comment]
Comments above are helpful to me. I'll also share same cases in helm chart.(kube-prometheus-stack, grafana/grafana)

You can find the target rule information(orgid, uid) at the `json config of Web UI`.

```yaml
# values.yaml

(...)

grafana:
  alerting: # {}
    delete_rules.yaml:
      deleteRules:
        - orgId: 1
          uid: xxxxxxxx-00c7-4cde-b12f-60d8xxxxxxxx
        - orgId: 1
          uid: xxxxxxxx-870f-4342-abee-5121xxxxxxxx
  rules.yaml:
    (...)
  contactpoints.yaml:
    (...)

(...)
```
```sh
helm upgrade my-release myhelmchart -f values.yaml
```
