### ISSUE TITLE
[Doc] Changelog incorrectly states multiple AWS account support from 3.0.3

### ISSUE THREAD

**Issue by tomhaigh** [grafana/grafana#6704]
The changelog states that support for multiple AWS account support was introduced in 3.0.3, but the changes introduced (https://github.com/grafana/grafana/pull/5065) don't appear to exist prior to the 3.1.1 tag. This is a bit confusing.

Thanks

**Comment by torkelo** [comment]
the support was added in 2.6 according to changelog which is correct. 
https://github.com/grafana/grafana/pull/3053

**Comment by tomhaigh** [comment]
I think you are referring to the support via profiles and credentials in the credentials file. But I am talking about the support via assumeRole: "CloudWatch: Support for Multiple Account by AssumeRole" - this is stated in the changelog as being available in 3.0.3, but is actually only available >= 3.1.1. So this is incorrect and unrelated to v2.6.
