### ISSUE TITLE
Time Series graph shows the wrong values

### ISSUE THREAD

**Issue by keesoldgithub** [grafana/grafana#67054]
Hi there,

Description of the bug:
The measurements voltage, power etcetera are stored in a MariaDB database, every 5 minutes. MariaDB is part of the LAMPP package including Apache2 and the Operating system is Ubuntu 22.04. I am displaying the data in time series graphic. The time zone used is Europe/Amsterdam UTC+2 (the panel graph and the dashboard). I have include a gif file video to explain the problem more clearly.

The error: The graph shows the values 2 hours in the past starting on the most right date (current date). In other words the current date does not correspond with the current value.

In the video I show you a value in MariaDB on 14:54:29 which is 311. The current date is a couple of seconds later So I expect that this value 311 is displayed at the far right of the graph at 14:54:29. The graph shows 317 at 14:59:15 and 320 at 14:54:14, these 2 values do not match any data of the MariaDB so it seems. Knowing now You will see that the 311 value will be displayed exactly  2 hours later in the graph namely at 16:54:29 - 311. 

When looking at the settings of the graph in **_table view_**, you will notice that the values are shifted 2 hours. The second line in the table is 16:54:29 value 311. Remember at the moment of the video it is a little bit, couple of minutes, later than 14:54.

Changing time zones in Grafana like default dutch do not have any effect.

**Time zones**
Ubuntu, Apache2 = Europe/Amsterdam and MariaDB = SYSTEM is Europe/Amsterdam

**Versions**
XAMPP 8.2.0
Apache2 2.4.54
MariaDB 10.6
PHP 8.2.0
Ubuntu 22.04
Grafana 9.4.7
The video
![Peek 2023-04-21 15-01](https://user-images.githubusercontent.com/131456105/233660152-982f7b17-a85d-46d8-b0c6-99f138bbbdb5.gif)

Kin Regards

Kees van Harselaar

**Comment by leeoniya** [comment]
does it work okay if you adjust your query to use `UNIX_TIMESTAMP(read_date) AS read_date`?

**Comment by keesoldgithub** [comment]
Hi Leeoniya,

Thanks for the quick response. I changed that in the query of the grafana graph but I get a message "Data is missing a time field". It looks like grafana is interpreting the UNIX_TIMESTAMP as an integer. If I check/convert the value of UNIX_TIMESTAMP to date then it display the correct date time in the table view.

Complete syntax checked
SELECT actual_usage,  UNIX_TIMESTAMP(read_date) AS read_date FROM arduino.power_p1_meter ORDER BY  read_date DESC LIMIT 288

Kind Regards Kees van Harselaar

**Comment by leeoniya** [comment]
maybe try `UNIX_TIMESTAMP(read_date) * 1000 AS read_date` to get milliseconds instead of seconds.

if that doesnt work you can add a Convert field type transformation: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#convert-field-type
