### ISSUE TITLE
CentOS + 9.4.7: Upgrade causes issues with systemd process restart

### ISSUE THREAD

**Issue by moxious** [grafana/grafana#67057]
## What happened:

Post-upgrade to Grafana 9.4.7, `systemctl restart grafana-server` failed to restart the service.  

The following systemd message is logged periodically. Grafana process re-spawns, so process id changes each time. Additionally, there is MySQL message error also.

This bug report is a carry-over of two related reports from [the community forum](https://community.grafana.com/t/grafana-lates-stuck-in-activating/85405) which after consultation with `#grafana-delivery` was deemed probably a bug.   

```
Apr 9 11:44:28 localhost systemd: Got notification message from PID 3804, but reception only permitted for main PID 3803
Apr 9 11:48:56 localhost mysqld: 2023-04-09 11:48:56 66 [Warning] Aborted connection 66 to db: ‘grafana’ user: ‘grafana’ host: ‘localhost’ (Got an error reading
communication packets)
```

A work-around was posted by a user, note the possible hint about `notify`.

> We hit a similar situation when we updated to the latest version of Grafana. I think there is an issue with the server process not forking correctly on startup. We ended up changing the systemd service type from notify to simple as a workaround. I tried installing an empty Grafana on a clean CentOS 7.9 machine and it installed with the notify type. The service started as expected so I think there might be an issue with the upgrade process.

## What you expected to happen:

Normal restart.

## How to reproduce it (as minimally and precisely as possible):

Unknown; see below.

## Environment:
- Grafana version: 9.4.7
- Data source type & version: N/A
- OS Grafana is installed on: Centos7, Centos 7.9
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by madogan** [comment]
We are having this issue for 9.2.17 and RedHat 9.0
