### ISSUE TITLE
[Feature request] Extra dialog box/warning when deleting panel with alert

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#6705]
I'd like it make it more explicit when a user is about to delete a panel with an alert attached in case it happens by accident. Since there is already a dialog box for just deleting the panel, I'm not sure if an other one will just add noise, but it beats nothing at all. I suppose there are other alternatives too, but I leave that to you.

Ideally I'd also like to see that in the "alert history" so others can track it, but that's somewhat secondary to just reducing accidental alert removal.

**Comment by torkelo** [comment]
we do have an extra confirm step when dealing a dashboard with alerts. 
![image](https://cloud.githubusercontent.com/assets/10999/20620845/053bbe28-b2fc-11e6-88ca-1c4c8461471a.png)

Maybe something similar for panel deletes

**Comment by KristianLyng** [comment]
That would do the trick indeed.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/d56b9a720a5de170db0a3e46294b94b1087852bd#diff-86658626db55a2eda81043a9792b6000
