### ISSUE TITLE
[Bug] Dot-delimited tags in ALIAS BY

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#6706]
- What Grafana version are you using?
4.0.0-beta2
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Created metric and tried to set alias using dot-delimited tag
- What was the expected result?
Alias should appear with proper name
- What happened instead?
Alias won't take variable past first dot

Here you can see full request using underscore-delimited tag, everything working as expected:
<img width="1301" alt="screen shot 2016-11-25 at 02 58 00" src="https://cloud.githubusercontent.com/assets/84462/20611449/8b1eae42-b2bb-11e6-96ea-eaf656053f83.png">
And here i'm trying to use tags provided by rancher for certain docker containers. As you can see, it looks like parse error: undefined.rancher.container.name
<img width="803" alt="screen shot 2016-11-25 at 02 58 27" src="https://cloud.githubusercontent.com/assets/84462/20611447/8b1b407c-b2bb-11e6-969c-86e8d7343592.png">
And i can use this dot-delimited tags in query (just to check):
<img width="1326" alt="screen shot 2016-11-25 at 02 59 51" src="https://cloud.githubusercontent.com/assets/84462/20611448/8b1b9be4-b2bb-11e6-9d4c-f23303015a3d.png">

**Comment by torkelo** [comment]
Use alternative syntax [[tag_tagname]]

**Comment by jacobtomlinson** [comment]
This was helpful for me.

**Comment by MicahZoltu** [comment]
Example syntax in case others like me got stuck:
```
[[tag_io.rancher.container.name]]
```
