### ISSUE TITLE
[ISSUE] Network interface traffic mismatch

### ISSUE THREAD

**Issue by amazen123** [grafana/grafana#6707]
Good Day,

Can you tell me why my grafana graph is different from my other 2 monitoring tools.
Grafana
![grafana](https://cloud.githubusercontent.com/assets/23717456/20611667/a33a0516-b2e9-11e6-9011-4ba19764fced.png)
`SELECT non_negative_derivative("value", 10s) FROM "snmp_rx" WHERE "host"='host' AND "type"='if_octets' AND "type_instance"='interface' AND $timeFilter`
`SELECT non_negative_derivative("value", 10s) FROM "snmp_tx" WHERE "host"='host' AND "type"='if_octets' AND "type_instance"='interface' AND $timeFilter`

Cacti and PRTG has similar data
Cacti
![cacti](https://cloud.githubusercontent.com/assets/23717456/20611650/9cbeed5a-b2e9-11e6-9b19-bcbdc932eb8e.png)
PRTG
![prtg](https://cloud.githubusercontent.com/assets/23717456/20611668/a532e95a-b2e9-11e6-83fb-f5f05b3e2609.png)

All the interface in my grafana is 10-20% higher than cacti and prtg

I'm using grafana version 3.1.1
OS : CentOS 7
Database : InfluxDB 1.1.0
Collector : Collectd 5.6.0

This issue is similar to issue [#363](https://github.com/grafana/grafana/issues/363) but it doesn't have a solution so i created a new thread

Thanks.

**Comment by DanCech** [comment]
Well, you're taking a measurement in octets per second and graphing the delta of that counter over 10 second intervals, that won't result in bits per second, it'll result in octets per 10 seconds which you'll expect to be 25% higher than bits per second.

To graph it as bits per second in Grafana you'll want something like:
`SELECT 8 * non_negative_derivative("value", 1s) FROM "snmp_rx" WHERE "host"='host' AND "type"='if_octets' AND "type_instance"='interface' AND $timeFilter`

**Comment by amazen123** [comment]
Thank you @DanCech.
I'm fairly new to grafana so thanks for the very well explanation how my graph works.
