### ISSUE TITLE
MSSQL: Change `denisenkom/go-mssqldb` to `microsoft/go-mssqldb`

### ISSUE THREAD

**Issue by EccentricVamp** [grafana/grafana#67071]
**What is the chore?**:

Replace references to https://github.com/denisenkom/go-mssqldb with https://github.com/microsoft/go-mssqldb.

Namely this one: https://github.com/grafana/grafana/blob/afc9925dbfa55886cc85a9a2106ed9892d7df239/pkg/tsdb/mssql/mssql.go#L13

**Is there anything else we need to know?**:

Microsoft's fork is more actively maintained. The readme in [denisenkom/go-mssqldb](https://github.com/denisenkom/go-mssqldb) explicitly states

> For more recent updates, see the [Microsoft fork](https://github.com/microsoft/go-mssqldb).

This would add several features that denisenkom's version is missing, like named pipes.

**Comment by zoltanbedi** [comment]
Hey @EccentricVamp,

Thanks for bringing this up, we will work on this in the near future.

**Comment by mattrussi** [comment]
Having krb5 support from this driver would be extremely useful as well.
