### ISSUE TITLE
Alert  firing/registering when threshold is not met

### ISSUE THREAD

**Issue by yinbucheng** [grafana/grafana#67079]
## What happened:
Alert  firing/registering when threshold is not met

## What you expected to happen:

do not send alert

## How to reproduce it (as minimally and precisely as possible):

My grafana alarm configuration is as follows
![image](https://user-images.githubusercontent.com/30992273/233836808-2321f439-d92d-4449-8e81-d58738a47ffb.png)
The function I want to achieve is to alarm when the log exceeds the specified number

## Anything else we need to know?:
Alarm content template configuration
![image](https://user-images.githubusercontent.com/30992273/233836874-b4bd3593-bdd5-4f97-ae7a-9c171e3a0f7f.png)

The following are error conditions, which should not have been alerted
![image](https://user-images.githubusercontent.com/30992273/233836936-871063d8-59f6-42cc-b7b2-2a3b662fd6ba.png)

## Environment:
- Grafana version:  9.3.8
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@yinbucheng What do you have configured for "No data and error handling"?

<img width="483" alt="Screenshot 2023-04-24 at 6 37 49 PM" src="https://user-images.githubusercontent.com/18175287/234147211-ab60456a-61e6-416b-9484-e383d0562260.png">
