### ISSUE TITLE
Cloudwatch Logs: The log insights query result is a timeseries struct, but can get the result on Alerting

### ISSUE THREAD

**Issue by mappei** [grafana/grafana#67083]
## Background
I want to be alerted by the value of a field in the CloudWatch log, assuming I have the following log structure:

|Timestamp|Message|
|-|:-|
|2023-04-14T09:18:50.486+08:00|{ "timestamp": "2023-04-14 01:18:50,486+0000", "level": "INFO", "message": { "F1": "value1", "F2": "value1.1", "data": 123 }, "cold_start": true, "function_name": "xxx", "function_memory_size": "128", "function_arn": "arn:aws:lambda:ap-southeast-1:xxx:function:xx", "function_request_id": "fdd28a87-79e2-4240-8c33-64ca40e8d453", "xray_trace_id": "1-6438a9f7-dd2721fe9371f16dbf6f445a" }|
|2023-04-14T09:18:50.486+08:00|	{ "timestamp": "2023-04-14 01:18:50,486+0000", "level": "INFO", "message": { "F1": "value2", "F2": "value2.2", "data": 55 }, "cold_start": true, "function_name": "xxx", "function_memory_size": "128", "function_arn": "arn:aws:lambda:ap-southeast-1:xxx:function:xx", "function_request_id": "fdd28a87-79e2-4240-8c33-64ca40e8d453", "xray_trace_id": "1-6438a9f7-dd2721fe9371f16dbf6f445a" }|
|2023-04-14T09:18:50.486+08:00|{ "timestamp": "2023-04-14 01:18:50,486+0000", "level": "INFO", "message": { "F1": "value3", "F2": "value3.3", "data": 4 }, "cold_start": true, "function_name": "xxx", "function_memory_size": "128", "function_arn": "arn:aws:lambda:ap-southeast-1:xxx:function:xx", "function_request_id": "fdd28a87-79e2-4240-8c33-64ca40e8d453", "xray_trace_id": "1-6438a9f7-dd2721fe9371f16dbf6f445a" }|

I wrote the following statement in the query of the alert rule to query the Cloudwath log:
```
fields concat(F1,":", F2) as label
| stats sum(data) as count by bin(1h), label
```

**BUT** I got an error message: `Failed to evaluate queries and expressions: failed to execute conditions: input data must be a wide series but got type long (input refid)`

Then I put this query to the dashboard with time-series type, then no error is reported and there are three data points in the chart.

1. At 2023-04-14T09:00:00, label named value1:value1 count, with value 123
2. At 2023-04-14T09:00:00, label named value2:value2.2 count, with value 55
3. At 2023-04-14T09:00:00, label named value3:value3.3 count, with value 4

## What happened:
Ran example and custom CloudWatch Log queries and they fail with "wide series" error.

## What you expected to happen:
Query returns all matching log entries and allows me to define alerts based on them.

## How to reproduce it (as minimally and precisely as possible):

1. Use AWS Lambda to print some logs and output in the CloudWatch log group, where one field is a number.
2. Use log insight to do a query in Grafana alert rule.
3. Use **_stats_** function to do aggregate operations on time and _some fields_ respectively like, `stats sum(data) as count by bin(1h), Fields `

## Anything else we need to know?:
None
## Environment:
- Grafana version: 9.0.4
- Data source type & version: CloudWatch Logs
- OS Grafana is installed on: Docker image: grafana/grafana-enterprise:9.0.4
- User OS & Browser: ubuntu/chrome
- Grafana plugins: None
- Others: None

**Comment by mellieA** [comment]
@mappei alerting can only evaluate numeric data. The error you've shared is expected if a string is returned in the query result. Can you share a screenshot of the alert configuration page where you're seeing this error?
