### ISSUE TITLE
[Bug] Connection to the DB server is executed on client browser exposing datasource user and password

### ISSUE THREAD

**Issue by Daverkex** [grafana/grafana#6709]
- What Grafana version are you using?
3.1.1 (happens in 4.0 too)
- What datasource are you using?
InfluxDB (happens with all datasources)
- What OS are you running grafana on?
Ubuntu 16.04.1
- What did you do?
Reload dashboard with network inspector (F12 on Chrome)
- What was the expected result?
The DB petition ran in server and the client on Grafana only receive representation data
- What happened instead?
The DB petition is being requested from the browser to the datasource exposing the authentication data. This makes it vulnerable to an sniffer.

Remove this from issue template and move the info to debug log:

`- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)`

**Comment by torkelo** [comment]
when you add a data source in grafana you are giving the option to have "direct" (ie browser -> data source) or "proxy" access (via grafana backend), in the proxy case the influxdb username and password is not exposed to the browser

**Comment by Daverkex** [comment]
Thank you!
