### ISSUE TITLE
[Feature request] Show timestamp on SingleStat

### ISSUE THREAD

**Issue by PaulGrimshaw** [grafana/grafana#6710]
![image](https://cloud.githubusercontent.com/assets/4194874/20620338/1f2f28de-b2f1-11e6-9000-2d22069d5f68.png)

We use Grafana for displaying weather measurements offshore.  However these measurements commonly fall behind due to date collection issues.  We show the latest recorded values using the SingleStat component, but what would be really useful is to see the timestamp that this value was recorded at, or even better a smart duration ("4min ago").

Our charts also show future data (forecasts) so it is hard to pick up whether the measurement has fallen behind or not.

Our datasource is influxdb

**Comment by inselbuch** [comment]
This is an excellent idea. And this could be implemented fairly easily. Where you can currently select the stat as "min,max,avg, etc." you could simply add another stat which is timestamp.

**Comment by aabrodskiy** [comment]
This would be awesome to have!

**Comment by geckogecko** [comment]
+1

**Comment by neilchalk** [comment]
+1

**Comment by royemmerich** [comment]
Being able to alert if the time difference is greater than a certain period would be great to have too.

**Comment by torkelo** [comment]
Implemented in https://github.com/grafana/grafana/pull/9298 

You can now select "Time of last point" as Stat (ops there is no check that the last point is null, this needs to be filtered out in the query). 

3 new unit date formats are available (no custom date formats)

![image](https://user-images.githubusercontent.com/10999/30694232-6bdcefb2-9ed3-11e7-968b-5092fcb881de.png)

**Comment by voiprodrigo** [comment]
Can this be used to define a threshold on the elapsed time since the time of the value?
I can use the From now date format, and that seems to translate fine, but I to have red/green/yellow depending on the number of seconds elapsed (now - time of value)

**Comment by inselbuch** [comment]
I played with that with limited success… it’s not clear what values you should use for the thresholds… should they be milliseconds? seconds? nanoseconds?


Frank Inselbuch, President
Unix Edge, Inc.
713-701-5421



Can this be used to define a threshold on the elapsed time since the time of the value?
I can use the From now date format, and that seems to translate fine, but I to have red/green/yellow depending on the number of seconds elapsed (now - time of value)

**Comment by alrghods** [comment]
+1

**Comment by vcandeau** [comment]
Hi, 

Did you find some solution to get working threshold on (now - time of value)

Best regards,

**Comment by liamdiprose** [comment]
@vcandeau I think the plan is to rework the conditional formatting, which mentions support for "date and duration" values.  https://github.com/grafana/grafana/issues/11418
