### ISSUE TITLE
Version of KairosDB plugin

### ISSUE THREAD

**Issue by dvenza** [grafana/grafana#6711]
Trying to investigate a bug in the KairosDB data source plugin, I found out that the version I installed via the Grafana installer is different from the master HEAD of the plugin's github repo.

On the plugin webpage it states there are three versions 0.9.0, 1.0.0 and 1.0.1, but there are no tags on the plugin repository, so I have no idea to which commit those versions correspond.

Is the "official" version of the kairosdb plugin older than the master HEAD? If so which commit is it?

I'm opening an issue here because apparently there is no maintainer for the plugin and its issue tracker feels abandoned.

**Comment by torkelo** [comment]
I think the published plugin (on grafana.net) is a bit older than master on github repo. 

The plugin definitely needs a maintainer

**Comment by dvenza** [comment]
Looking at the changelog the plugin on grafana.net is at least 15 commits (including many merges) behind the master. One of those commits fixes the bug that I was trying to fix myself, so I lost a bunch of time.

Either remove the outdated plugin from grafana.net or release a new version. At least put a notice NOT to use the grafana.net version, it's buggy and outdated.
