### ISSUE TITLE
[Feature request] add dewpoint function

### ISSUE THREAD

**Issue by Lord-of-Kerry** [grafana/grafana#6712]
We would like to let grafana calculate the dewpoint from a given temperature and humidity reading by using a grafana function.

- We are using Grafana 3.1.1
- Our Datasource is Graphite

![grafana](https://cloud.githubusercontent.com/assets/22909825/20620758/8d9dfdd6-b2fb-11e6-8c0e-63634a33fa0a.JPG)

**Comment by torkelo** [comment]
grafana function? you mean graphite? I think you should open this issue in the graphite project, the query functions are executed in graphite
