### ISSUE TITLE
[Bug] Grafana insert '\' before '.' in templates variables

### ISSUE THREAD

**Issue by ragonlan** [grafana/grafana#6713]
Grafana insert \ before . in templates variables and influxdb fails in the searching:

Grafana version: 3.1.1-1470047149    amd64  
Datasource :  Influxdb 1.0.1-1
OS:  Debian 8.6
What I do: 
![captura](https://cloud.githubusercontent.com/assets/2271285/20622635/248fa25a-b304-11e6-9371-7c18196a9e23.PNG)

Grafa try to get from Influx:
/query?db=telegraf&epoch=ms&p=[REDACTED]&q=SHOW TAG VALUES FROM "interfaces" WITH KEY = "alias"  WHERE "agent_host" = '**vasa3\\.acens\\.priv**'&u=admin HTTP/1.1" 400 ...

and InfluxDB respond a 400 Error (Bad Request). It showul try this query:

 /query?db=telegraf&epoch=ms&p=[REDACTED]&q=SHOW TAG VALUES FROM "interfaces" WITH KEY = "alias"  WHERE "agent_host" = '**vasa3.acens.priv**'&u=admin HTTP/1.1" 200 ...

**Comment by torkelo** [comment]
change to use regex operator in your query ` WHERE "agent_host" =~ /$host/`

**Comment by ragonlan** [comment]
It worked!! thank you very much!
