### ISSUE TITLE
[Bug] renderToPng fails with template variables on 3.1.1

### ISSUE THREAD

**Issue by johngilden** [grafana/grafana#6715]
- Grafana:  3.1.1 commit=a4d2708 compiled=2016-08-01T10:20:16+0000
- Datasource: InfluxDB 1.0.2
- OS: Docker (grafana/grafana:latest)
- What did you do: "Direct link rendered image"
- Expected result: Rendered PNG
- Instead: Rendered PNG without graphs and with warning

So, rendering **works** for dashboards/graphs which do **not** have **any** template variables. When a dashboard has any template variables, rendering **fails** with like this:

![nsq](https://cloud.githubusercontent.com/assets/10496846/20631246/f41e317c-b335-11e6-87f0-9583d7bc6b06.png)

Console output:
```
docker[13317]: [object Object]
docker[13317]:   http://localhost:3000/public/app/boot.1649cbaa.js:36
```

**Comment by torkelo** [comment]
could you look in the InfluxDB logs for errors there? Looks like InfluxDB is returning an error

**Comment by johngilden** [comment]
I have, and InfluxDB returns a HTTP 200 for the query, which is the same I get when I do the same query in my browser. Again, the query works fine in the regular dashboard, just not when I export it to PNG. I can even see the template variable being included in the query to InfluxDB.

**Comment by johngilden** [comment]
Nevermind, I figured it out, it looks like it was due to some Access-Control-Allow-* headers on the InfluxDB nginx frontend. Still strange that it worked without template variables, but not with.
