### ISSUE TITLE
[BUG] Grafana does not display available data

### ISSUE THREAD

**Issue by jvannier** [grafana/grafana#6716]
Grafana version: grafana/grafana:3.1.1
Using InfluxDB influxdb:1.1.0-alpine

I set up Grafana to connect to my Influxdb (which it seems to do fine), and I expect that the data should display on the graph. It doesn't. Any ideas?

<img width="1440" alt="screen shot 2016-11-26 at 1 11 17 am 1" src="https://cloud.githubusercontent.com/assets/5264453/20638432/ca2d5ccc-b375-11e6-87de-02db6e0929e8.png">

Stack is NOT enabled.

**Comment by torkelo** [comment]
Looks like null values between each value, increase the group by time interval (you can set low limit below queries using >10s  syntax.   Or change query fill option

**Comment by jvannier** [comment]
Even when I change the group by to be larger it doesn't seem to affect anything. Neither does changing the fill option. 

<img width="1433" alt="screen shot 2016-11-26 at 9 38 28 pm" src="https://cloud.githubusercontent.com/assets/5264453/20645114/b47f9d80-b420-11e6-80d9-add3c78d52f6.png">

**Comment by jvannier** [comment]
case and point
<img width="1433" alt="screen shot 2016-11-26 at 9 47 52 pm" src="https://cloud.githubusercontent.com/assets/5264453/20645130/e648a5b8-b421-11e6-97b1-be58dcbdee3a.png">

**Comment by jvannier** [comment]
On further study it seems like it IS displaying data, but at the completely incorrect time (I can't see why it would be at that time). Please Advise?

<img width="1434" alt="screen shot 2016-11-26 at 10 46 54 pm" src="https://cloud.githubusercontent.com/assets/5264453/20645362/295f80b2-b42a-11e6-8e33-ea8d4d1cec72.png">
