### ISSUE TITLE
Segmentation fault / invalid memory pointer error

### ISSUE THREAD

**Issue by mlsmithjr** [grafana/grafana#67171]
## What happened:

Grafana will not start under docker after Ubuntu 23.04 upgrade.

## What you expected to happen:
Clean startup.

## How to reproduce it (as minimally and precisely as possible):
Docker pull and run

## Anything else we need to know?:

I have removed the container and image, re-pulled and recreated.  Same issue.

## Environment:
- Grafana version: grafana/grafana:latest
- Data source type & version:
- Prometheus
- OS Grafana is installed on:
- Ubuntu Desktop 23.04 as docker container
- User OS & Browser:
- Grafana plugins: none
- Others:

logger=settings t=2023-04-24T23:33:31.884050722Z level=info msg="Starting Grafana" version=9.4.7 commit=4add91f03d branch=HEAD compiled=2023-03-16T23:56:52Z
logger=settings t=2023-04-24T23:33:31.884150042Z level=warn msg="\"sentry\" frontend logging provider is deprecated and will be removed in the next major version. Use \"grafana\" provider instead."
logger=settings t=2023-04-24T23:33:31.884155755Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-04-24T23:33:31.884158273Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-04-24T23:33:31.884159974Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-04-24T23:33:31.884161694Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-04-24T23:33:31.88416413Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-04-24T23:33:31.884165701Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-04-24T23:33:31.884167873Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-04-24T23:33:31.884170322Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-04-24T23:33:31.884171928Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-04-24T23:33:31.884173322Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-04-24T23:33:31.884175054Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-04-24T23:33:31.884176902Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-04-24T23:33:31.884178531Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-04-24T23:33:31.884179953Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-04-24T23:33:31.884181316Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-04-24T23:33:31.884182829Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-04-24T23:33:31.884184333Z level=info msg="App mode production"
logger=sqlstore t=2023-04-24T23:33:31.884210994Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2023-04-24T23:33:31.884216613Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-rw-rw- expected=-rw-r-----
logger=migrator t=2023-04-24T23:33:31.894029503Z level=info msg="Starting DB migrations"
logger=migrator t=2023-04-24T23:33:31.89675139Z level=info msg="migrations completed" performed=0 skipped=481 duration=211.358µs
logger=plugin.finder t=2023-04-24T23:33:31.914451064Z level=warn msg="Skipping finding plugins as directory does not exist" path=/usr/share/grafana/plugins-bundled
logger=plugin.loader t=2023-04-24T23:33:31.934742549Z level=info msg="Plugin registered" pluginID=grafana-piechart-panel
logger=plugin.loader t=2023-04-24T23:33:31.934749009Z level=info msg="Plugin registered" pluginID=grafana-worldmap-panel
logger=secrets t=2023-04-24T23:33:31.934766738Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=query_data t=2023-04-24T23:33:31.935578143Z level=info msg="Query Service initialization"
logger=live.push_http t=2023-04-24T23:33:31.937820404Z level=info msg="Live Push Gateway initialization"
logger=ngalert.multiorg.alertmanager t=2023-04-24T23:33:31.969723437Z level=error msg="unable to create Alertmanager for org" org=1 error="error writing file notifications: open /var/lib/grafana/alerting/1/notifications: permission denied"
logger=cli t=2023-04-24T23:33:31.970518938Z level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:181 +0x9c\npanic({0x3d50ba0, 0x72bc0f0})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc001be1170?)\n\t/drone/src/pkg/services/ngalert/notifier/alertmanager.go:232 +0xf5\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc00158e000, {0x4e00fc8, 0xc001cea8a0}, {0xc001e60140, 0x1, 0x4e02650?})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc00158e000, {0x4e00fc8, 0xc001cea8a0})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc001ba9a00)\n\t/drone/src/pkg/services/ngalert/ngalert.go:176 +0x486\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x4e18088, ...}, ...)\n\t/drone/src/pkg/services/ngalert/ngalert.go:101 +0x5a9\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc25b2bd39, 0x18}, {0x7ffc25b2bd1d, 0x12}, {0xc000e37320, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)\n\t/drone/src/pkg/server/wire_gen.go:431 +0x4a85\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4db8ea0, 0x5}, {0x4dba100, 0xa}, {0x4db8e98, 0x4}, {0x4dba0f0, 0xa}, 0xc000507340})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc0007f8180?)\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5\ngithub.com/urfave/cli/v2.(*Command).Run(0xc0007e3e60, 0xc000506000)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0004fcea0, {0x4e00f90?, 0xc000078040}, {0xc0000740a0, 0xa, 0xa})\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main()\n\t/drone/src/pkg/cmd/grafana/main.go:39 +0x27d\n"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x224a9f5]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:182 +0x17e
panic({0x3d50ba0, 0x72bc0f0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc001be1170?)
	/drone/src/pkg/services/ngalert/notifier/alertmanager.go:232 +0xf5
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc00158e000, {0x4e00fc8, 0xc001cea8a0}, {0xc001e60140, 0x1, 0x4e02650?})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc00158e000, {0x4e00fc8, 0xc001cea8a0})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc001ba9a00)
	/drone/src/pkg/services/ngalert/ngalert.go:176 +0x486
github.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x4e18088, ...}, ...)
	/drone/src/pkg/services/ngalert/ngalert.go:101 +0x5a9
github.com/grafana/grafana/pkg/server.Initialize({{0x7ffc25b2bd39, 0x18}, {0x7ffc25b2bd1d, 0x12}, {0xc000e37320, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
	/drone/src/pkg/server/wire_gen.go:431 +0x4a85
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4db8ea0, 0x5}, {0x4dba100, 0xa}, {0x4db8e98, 0x4}, {0x4dba0f0, 0xa}, 0xc000507340})
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc0007f8180?)
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5
github.com/urfave/cli/v2.(*Command).Run(0xc0007e3e60, 0xc000506000)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8
github.com/urfave/cli/v2.(*App).RunContext(0xc0004fcea0, {0x4e00f90?, 0xc000078040}, {0xc0000740a0, 0xa, 0xa})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36
github.com/urfave/cli/v2.(*App).Run(...)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/drone/src/pkg/cmd/grafana/main.go:39 +0x27d

**Comment by mellieA** [comment]
@mlsmithjr there's a [similar issue](https://github.com/grafana/grafana/issues/65998) with this stack trace. But what I notice is different is that there's a permission denied error for this file right before the panic. 

`Alertmanager for org" org=1 error="error writing file notifications: open /var/lib/grafana/alerting/1/notifications: permission denied"`

Have you checked the permissions for that path/mount point?

**Comment by mlsmithjr** [comment]
Yes, the permissions on the directory mounted to docker is rwx for the owning user, same as the user/group designated in the container's environment.
However, just for kicks I opened up the directory to 777 and now it works. It should not have mattered but it did. This container has been running for weeks with several restarts in between and no changes to the mapped host filesystem so I can't explain it, but it's working so I'm good now.
Thanks for your prompt reply.

**Comment by grobinson-grafana** [comment]
It looks to me like the data dir is `/var/lib/grafana` but it wasn't writable from Grafana? If so I will close the issue as it looks like a mis-configuration. Please feel free to re-open if this is with the default configuration in the docker image.
