### ISSUE TITLE
long numbers on left Y

### ISSUE THREAD

**Issue by yosefy** [grafana/grafana#6717]
- What Grafana version are you using?
Version 3.1.1 (commit: a4d2708)
- What datasource are you using?
prometheus
- What OS are you running grafana on?
linux
- What did you do?
added repeated panel
- What was the expected result?
short values ol left Y ( with 2 decimals as i set in legend)
- What happened instead?
some are short and some not
(when pointing on the graph , its 2 decimals, as expected from legend page config)
![image](https://cloud.githubusercontent.com/assets/12940013/20641919/754ed898-b40b-11e6-9b5c-38a3a377e1c9.png)

prometheus query:
$couchbase_cluster_storage{instance=~"$server"}

its repeted by query with regex:
metrics(couchbase_cluster_storage.*)

**Comment by torkelo** [comment]
This is fixed in master / v4
