### ISSUE TITLE
Panels won't snap into place in the dashboard

### ISSUE THREAD

**Issue by Boulder08** [grafana/grafana#67179]
## What you expected to happen: There is enough space for the panels, so I expected them to be placed where I wanted them to be. I have checked the JSON code of the panels in the dashboard, but cannot find anything occupying the space. The panels are 3 "points" wide and the x coordinates for the nearest existing panels are 6, 9, 12 and 18 so the new copies should snap into 15 easily. The whole bottom right corner of the dashboard seems to be off limits.

![image](https://user-images.githubusercontent.com/11799308/234193202-0325b48c-b8fa-4483-ad18-1bbb06134849.png)
![image](https://user-images.githubusercontent.com/11799308/234193239-5a335f38-dac7-46d8-bfae-37d6cbfb8243.png)

## Environment:
- Grafana version: 8.5.22
- Data source type & version:
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Firefox
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@Boulder08 can you [share a copy of your dashboard json ](https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/#export-a-dashboard)so we can try to reproduce it? Have you tried this with the latest version of Grafana to see if it's already fixed?

**Comment by Boulder08** [comment]
[PV-1682480222773.zip](https://github.com/grafana/grafana/files/11328784/PV-1682480222773.zip)
Here's the JSON file.

I have not yet tested upgrading to Grafana 9, but I can do that during the next weekend.

**Comment by Boulder08** [comment]
I've tested upgrading to the latest Grafana build, but it did not fix the issue.
