### ISSUE TITLE
Azure Monitor resource picker doesn't select multiple resources when using a multi-value variable

### ISSUE THREAD

**Issue by avidhanju** [grafana/grafana#67178]
## What happened:
When using a multi-select variable with Azure Monitor resource picker's Advanced option, the resulting Log Analytics query always fails because the picker doesn't parse the comma-separated list of resource ids.

## What you expected to happen:
Log Analytics queries successfully execute against multiple resources selected in the multi-select variable.

## How to reproduce it (as minimally and precisely as possible):
Here is a screenshot that shows the issue:
![image](https://user-images.githubusercontent.com/10158691/234188495-ca775655-026d-48a4-8e07-d4ff64243dc5.png)

Please note that I am not using actual resource ids in the variable in order to protect PII.

## Environment:
- Grafana version: 9.4.8
- Data source type & version: Azure Monitor data source
- OS Grafana is installed on: Linux
- User OS & Browser: Windows & Edge
- Grafana plugins:
- Others:

**Comment by bossinc** [comment]
Thank you for your submission!
I can reproduce this issue. I'll make a fix for it soon.

**Comment by avidhanju** [comment]
@bossinc great! Let me know if you need help.
