### ISSUE TITLE
Alerting: Can't set alert rule's query params time range

### ISSUE THREAD

**Issue by novy4** [grafana/grafana#67191]
## What happened:
I am trying to migrate alert rules from old fashion Grafana setup to unified alerting. I have some queries like A, and B where I need to specify the time range, for example, A(5m, now). I can't do it in a unified alerting UI. There is no such option for time range anymore.

## What you expected to happen:
The expected behavior is that I can specify the time range for alerting rule. 

## How to reproduce it (as minimally and precisely as possible):
Go to unified alerting, create a rule, and try to specify a time range in query parameters.

## Environment:
- Grafana version: 9.3.8
- Data source type & version: elasticsearch
- OS Grafana is installed on: prometheus-stack

**Comment by mellieA** [comment]
@novy4 for questions, we recommend that users ask in our forum at https://community.grafana.com/

The time range is selectable next to the datasource in the alert definition: 

<img width="904" alt="Screenshot 2023-04-25 at 7 06 49 PM" src="https://user-images.githubusercontent.com/18175287/234440096-f86c9bba-0471-48e5-b94f-7f488b125859.png">
