### ISSUE TITLE
[Doc] HTTP API documentation links are missing

### ISSUE THREAD

**Issue by markusr** [grafana/grafana#6719]
The HTTP API documentation has only 1 menu item: `Users` 
![grafik](https://cloud.githubusercontent.com/assets/1866703/20647899/03f41fda-b499-11e6-972b-41bb79b68f8f.png)

The other pages are missing from the menu. The pages are still there but I only found them via google:
`http://docs.grafana.org/http_api/overview/`

**Comment by bergquist** [comment]
@markusr thank you for noticing!

Fixed

**Comment by markusr** [comment]
Maybe move the `overview` page to the top of the submenu?

It also seems that `overview` page breaks the menu. You cannot scroll to the rest of the menu entries.

![grafik](https://cloud.githubusercontent.com/assets/1866703/20649453/eba9d118-b4c0-11e6-8194-947fdf3a0c79.png)

**Comment by bergquist** [comment]
Good point. Made the overview content appear when going to /http_api/
