### ISSUE TITLE
Silence button missing in the alert details view

### ISSUE THREAD

**Issue by lukas-unity** [grafana/grafana#67192]
## What happened:

It seems that after https://github.com/grafana/grafana/pull/62133 was merged `Silence` button in no longer available in the alert list view.
![image](https://user-images.githubusercontent.com/64898324/234234663-8728b210-4aec-4727-aa58-24d0ae32ace8.png)

## What you expected to happen:

Silence button should be available, as it's more convenient to silence alerts this way.

![image](https://user-images.githubusercontent.com/64898324/234233022-f04ed736-5fc4-4183-8fcd-7576e84bc33a.png)

## How to reproduce it (as minimally and precisely as possible):

Run Grafana container -> Add Mimir Prometheus and Alertmanager datasources -> Create a new alert rule -> Trigger the alert.

## Environment:
- Grafana version: 9.4.7
- Data source type & version: Prometheus(Mimir)
- OS Grafana is installed on: Grafana container in K8s
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@lukas-unity the button was removed because it could only control silences for the built-in grafana alertmanager. The button was only removed for external alertmanagers. 

> This would create the silence in the internal Alertmanager and it wouldn't do anything to silence their alert rule.

**Comment by TaylorMutch** [comment]
> @lukas-unity the button was removed because it could only control silences for the built-in grafana alertmanager. The button was only removed for external alertmanagers.
> 
> > This would create the silence in the internal Alertmanager and it wouldn't do anything to silence their alert rule.

Hi @mellieA - I understand the rationale but however this did in fact work for a alertmanagers which were linked to Prometheus datasources. This did in fact work when, in the prometheus datasource, the field `alertmanagerUid` was set in the Prometheus datasource definition to the associated external alertmanager. This allowed for alerts to be silenced on the external alertmanager easily for our developers.

This is how our developers mute alerts on our Mimir backend, so removing the silence button is a real issue for us.

**Comment by TaylorMutch** [comment]
@mellieA Please consider reopening this issue for further investigation

**Comment by Laakso** [comment]
Could you please @mellieA consider re-opening this feature? As @TaylorMutch said earlier, this feature has been working for them and it was also working for us. Our org is also using an external alertmanager and we can confirm that this feature was indeed working for us as well.

**Comment by chloehabitat** [comment]
Adding to this, we were also using prometheus alertmanager as a datasource and the silence button worked great for us. It's now quite inconvenient to have to manually create a silence with the correct label inputs and makes it harder to use for our non-technical users.

@mellieA please consider reviewing your decision

**Comment by Swaps76** [comment]
We are using mimir alertmanager and I also cannot see a silence button in the Grafana - Alert Rules section
![image](https://github.com/grafana/grafana/assets/16971751/b9b97447-45ce-4e8e-9c71-a801c7dd401b)

**Comment by stefanandres** [comment]
Please add this back. Also: On the /alerting/groups URL you still can use the silence action button. So now it's inconsistent and confusing to users.

**Comment by morremeyer** [comment]
Reopened this as a feature request in #81644.
