### ISSUE TITLE
[Feature Request] SingleStats panel on mobile phone

### ISSUE THREAD

**Issue by florentvaldelievre** [grafana/grafana#6720]
SingleStats panel takes the full width of mobile phone screen.
Below, an example with 3 SingleStats on a mobile phone. They are all collapsing to take the full width for each panel.
Ideally, I'd like them to be on the same row(Horizontally). 

1. Is it possible ?
2. Are you planning to support it ?
3. Is there any CSS trick to do it ?

Grafana 3.0.1

![Mobile phone SingleStats](https://s17.postimg.org/v5e33tbx9/Screenshot_2016_11_26_22_40_45.png?dl=1&_ga=1.76048145.504818174.1480245984)

**Comment by torkelo** [comment]
does not look like they would fit nicely on the same row, would be very squished and small. The responsive style rules change the panel layout so all panels are laid out vertically

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/512
