### ISSUE TITLE
Grafana Does not Expand `server.custom_response_headers` from Environment Variables

### ISSUE THREAD

**Issue by virgofx** [grafana/grafana#67230]
When specifying environment variables for `server.custom_response.headers` using the format below, they do not get added into the server response headers section. _(Note: File INI format does work)_

```
GF_SERVER_CUSTOM_RESPONSE_HEADERS_SERVER = "Test"

````
Reference : https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#servercustom_response_headers

In the above example, one would expect the `server: test` header to be configured in Grafana in the corresponding section

### Additional Details
- Tested both using "GF_SERVER.CUSTOM_RESPONSE_HEADERS_SERVER" as well as the underscored case which is the expected format as documented
- This may have something to do with the values in this section as being 100% dynamic as these are user defined

![image](https://user-images.githubusercontent.com/739719/234346111-f1475f25-adb9-4687-b682-6c5f80f24751.png)

## Environment:
- Grafana version: 9.4.7
- Data source type & version: SQLite
- OS Grafana is installed on: Docker `grafana/grafana-oss:9.4.7@sha256:0f937ad695e3dd2029d111003d29d789c0ee06af3043b18c3010dffaf7db1366`

**Comment by mellieA** [comment]
@virgofx the config parameter name is `GF_SERVER_CUSTOM_RESPONSE_HEADERS`, have you tried using just that and passing a value? 

GF_SERVER_CUSTOM_RESPONSE_HEADERS = "Server = Test"

**Comment by virgofx** [comment]
@mellieA Tested that and it also did not work.

**Comment by mellieA** [comment]
@virgofx thanks for trying! I'll move this one to the config team

**Comment by virgofx** [comment]
It would be great once this is fixed to update the documentation in the configuration section for this one as well with the expected format. I'd expect it to include an example of multiple environment variables as well and how they should be delimited (e.g. using a comma or semi-colon)

**Comment by sakjur** [comment]
> This may have something to do with the values in this section as being 100% dynamic as these are user defined

It does, yeah. I'm trying to think of a way to make that work, it's somewhat tricky since environment variables (as we're using them) are defined to be all upper case and replaces dots and dashes with `_` — the former isn't a big problem with headers since they're case insensitive and Go normalizes them, but the latter is a problem since it's ambiguous which of the characters should be used for the header. `SERVER_CUSTOM_RESPONSE_HEADERS_CONTENT_TYPE` can become `Content_Type`, `Content-Type`, and `Content.Type` and they're afaict all valid options, even though only the middle one is conventional.

**Comment by sakjur** [comment]
Yeah, I'm leaning the same way. I _think_ I might go for a cheat here and allow `X-Custom: ABC, X-Custom2: DEF` and `{"X-Custom": "ABC", "X-Custom2": "value; with; semicolon", "X-Custom3": ["Maybe", "even", "lists?"]}`. We have a similar scheme elsewhere for using JSON lists if simple comma separated lists are insufficient.
