### ISSUE TITLE
[HELP] How to access grafana dashboard on network

### ISSUE THREAD

**Issue by amazen123** [grafana/grafana#6723]
Good Day,

Can someone teach me on how can I access grafana on different computer?
I already installed apache but when i access the grafana server IP it shows me the apache test page.

OS : Centos 7
Apache version 2.4.6
Grafana version 3.1.1

Thanks.

**Comment by jifwin** [comment]
First of all are you sure you need apache as a proxy? You can connect to Grafana directly (port 3000 by default).

**Comment by amazen123** [comment]
I can't connect to grafana using http://grafana-server-ip:3000.
Do i need to add something on grafana .ini file so i can access it on another network?

**Comment by torkelo** [comment]
Maybe check firewall, 

Please use mailing list for questions

**Comment by amazen123** [comment]
Good Day,

@torkelo thanks, i will check the firewall setting later.
Also what do you mean by mailing list, sorry I'm fairly new here.

**Comment by riddhi2910** [comment]
Hi, did you make changes on grafana(custom.ini) remotely?
