### ISSUE TITLE
No 9.5.x branch "nightly" builds on dockerhub anymore?

### ISSUE THREAD

**Issue by tillsteinbach** [grafana/grafana#67246]
I was expecting to find nightly" builds of 9.5.x branch on dockerhub here: https://hub.docker.com/r/grafana/grafana-oss-dev/tags?page=2 but they end 22 days ago (probably when the builds for 10.0.0 started).  What would be the way to get images for 9.5.0 to preview compatibility?

**Comment by tillsteinbach** [comment]
And the same is true for the downloads page: https://grafana.com/grafana/download/9.5.0-109039pre?edition=oss&platform=windows

**Comment by dsotirakis** [comment]
Hello @tillsteinbach and thanks for raising this issue!

There are two separate issues for this one:
* We don't post the nightly builds anymore.
* We don't push docker images for the versioned branches.
