### ISSUE TITLE
[Bug] Grafana 4.0 Beta Docker Problem! Unauthorized

### ISSUE THREAD

**Issue by infinitydon** [grafana/grafana#6726]
Hi,

I am getting "Problem! Unauthorized" when i try to login with the default username/password of admin/admin

Please include this information:
- What Grafana version are you using?
**_grafana:4.0.0-beta2 (Docker)_**
- What datasource are you using?
**_None yet, I can't even login to the Dashboard to create a data source_**
- What OS are you running grafana on?
**_Docker on Ubuntu 16_**

**Comment by infinitydon** [comment]
Seems this is also the same issue when I install directly on Ubuntu 16...

Is anyone else having this issue?

**Comment by torkelo** [comment]
Strange, unable to replicate, suspect some docker volume  permission issue, Can you show the grafana server log?

**Comment by Yackip** [comment]
I have the same Issue Here I the log:
`EROR[01-07|13:06:50] Invalid username or password             logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"                                                                                                 
INFO[01-07|13:06:50] Request Completed                        logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 rem                                                                                               
ote_addr=192.168.1.130 time_ms=42ns size=42                                                                                                                                                                                               
INFO[01-07|13:06:50] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status                                                                                               
=401 remote_addr=192.168.1.130 time_ms=12ns size=26`

And the web GUI says: "Problem! Unauthorized"
