### ISSUE TITLE
data proxy timeout is not working?

### ISSUE THREAD

**Issue by shezhangzhang** [grafana/grafana#67269]
## What happened:
This is my data proxy conf:
```ini
[dataproxy]
timeout = 300
dialTimeout = 10
keep_alive_seconds = 120
tls_handshake_timeout_seconds = 10
logging = false
send_user_header = true
```
but the timeout is 60s?
![image](https://user-images.githubusercontent.com/26793777/234534512-528fbfe1-989f-41eb-9891-527f7e99b8a0.png)
```log
26T15:49:25.481382982+08:00 level=info msg="Request Completed" method=POST path=/api/datasources/proxy/2183/query status=499 remote_addr=58.248.231.139 time_ms=59986 duration=59.986519874s size=0 referer="http://xxx.xxx.com/d/xxx/xxx?editPanel=8&inspect=8&inspectTab=query&orgId=1&tab=query" handler=/api/datasources/proxy/:id/*
logger=data-proxy-log userId=1 orgId=1 uname=xxx path=/api/datasources/proxy/2183/query remote_addr=xxx referer="http://xxx.xxx.com/d/xxx/xxx?orgId=1&editPanel=8&tab=query&inspect=8&inspectTab=query" t=2023-04-26T15:49:25.481296857+08:00 level=debug msg="Proxy request cancelled by client"
```
## What you expected to happen:
The timeout is 300s, not 60s
## Environment:
- Grafana version: v9.2.2
- Data source type & version: 
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@shezhangzhang there's a similar issue here https://github.com/grafana/grafana/issues/35505 

Can you check that: 

- There's not a datasource query timeout that is set to a shorter time period? 
- That you're editing the correct .ini file if there is more than one in your config path
- Use a network monitoring tool to see if there is anything else in the network that could be timing out?

**Comment by shezhangzhang** [comment]
sorry, finally I had found that it was my nginx timeout setting problem, sorry to bother you !
