### ISSUE TITLE
TabsBar: make component responsive

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#67278]
A [workaround](https://github.com/grafana/grafana/pull/66805) will be merged in order to let the TabsBar be scrollable when is mobile.
However, we should work in a better approach as it is described in that PR

**Comment by khushijain21** [comment]
I'd like to work on this - is it open and can you describe the requirement more?

**Comment by iSatVeerSingh** [comment]
@juanicabanas I think a select option is a good idea.

**Comment by juanicabanas** [comment]
Hi @khushijain21  and @iSatVeerSingh . There's no decision yet about how to fix it but you can read these comments about what would be the final idea https://github.com/grafana/grafana/pull/66805. Basically, when it's mobile, make a select component.
