### ISSUE TITLE
[Bug] Table plugin date rendering

### ISSUE THREAD

**Issue by hrr888** [grafana/grafana#6728]
Hi
I'm using grafana 3.0.2 with elasticsearch 2.4.
I've created table panel to display data witch includes some columns with 'date' style applied. But not all docs from elasticsearch have all date fields. Table plugin in that case displays current date, which is very confusing.
I looked at sources, and I think problem is in public/app/plugins/panel/table/renderer.ts, in createColumnFormater method. For 'date' column style, there is no check for empty/undefined value. Instead, value is directly rendered with moment.js, which returns current date with empty/no argument provided.
I would be nice to validate date for null/empty values and display empty string, or '-', as it is in case of unformated columns, or with 'number' style.

**Comment by bergquist** [comment]
Thank you for reporting this.
