### ISSUE TITLE
[Bug] scale bytes measurement

### ISSUE THREAD

**Issue by fragpit** [grafana/grafana#6730]
version: 3.1.1
DataSource: InfluxDB

When I choose unit of Axe Y on graph to data->bytes, Grafana scales 3975892992 bytes to 3.7 GB. 
When I choose  data rate->bytes/sec it scales to 3.9GB/sec

I expect the first result to be also 3.9GB instead of 3.7

**Comment by torkelo** [comment]
the default bytes unit uses the IEC International Standard, but the rates are using Metric. 

This has been expanded and improved in 4.0, you can now select Metric byte unit as well (which will align with the rate byte unit)
