### ISSUE TITLE
using $__rate_interval in min step is broken in Grafana 9.5.0/1

### ISSUE THREAD

**Issue by mindw** [grafana/grafana#67304]
## What happened:
Using Grafana cloud - noticed that all panels with "min step" set to `$__rate_interval` are empty. Both query interval and step are set to **interval**. When "min step" is empty $__rate_interval value is as expected.

## What you expected to happen:
Panels to show data as "Min step" is set to rate_interval as in 8.5.x-9.4.x

## How to reproduce it (as minimally and precisely as possible):
create a panel with two identical queries using `$__rate_interval` - `rate(node_intr_total[$__rate_interval])`. Put `$__rate_interval` into "Min step" of the second. open the query inspector. see the madness.

## Anything else we need to know?:
This seems to be a regression in 9.5

## Environment:
- Grafana version: Grafana v9.5.0-cloud.5.a016665c (b2a5d45589)
- Data source type & version: Prometheus Mimir (Grafana cloud)
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Win10 Chrome
- Grafana plugins: Grafana Cloud - standard timeseries panel
- Others:

![grafana_rate_interval_bug](https://user-images.githubusercontent.com/578872/234631177-4dc9bd0c-a257-4df3-9ef2-e5bfd25a559e.png)

**Comment by mellieA** [comment]
Thanks for opening this issue, I'm seeing this too

**Comment by mindw** [comment]
Closed by https://github.com/grafana/grafana/pull/67460
