### ISSUE TITLE
Kiosk TV mode does not hide all top bar icons in v9.5.1

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#67319]
## What happened:
After redesign of Grafana's top bar, `kiosk=tv` mode is pretty useless. It only prevents from opening the top search/login bar, but the arrow to open it does not disappear in that mode. Clicking that arrow in TV mode does nothing - you need to exit TV mode by pressing Esc and only then you can expand the search bar.
![image](https://user-images.githubusercontent.com/19311511/234669649-9ba516a5-f27e-40a9-b887-dbb00c87ba2c.png)

## What you expected to happen:
To keep the TV mode functional, this mode should hide arrow in top right corner and hide hamburger menu in top left corner which expands side navigation menu

## How to reproduce it (as minimally and precisely as possible):
1. Enable dashboard in TV mode by adding `&kiosk=tv` parameter in the link
2. Check `Toogle top search bar` button behaviour

## Environment:
- Grafana version: v9.5.1

**Comment by tonypowa** [comment]
hi @szerwi 

thank you for creating this issue

forwarding this issue to the dashboard team for review

**Comment by torkelo** [comment]
the tv mode works as designed, hides the top section of the navbar, same behavior as the chevron. But your right clicking the chevron down should work and it does not (it should exit TV mode).
