### ISSUE TITLE
Azure Datasource :: Availability Tests :: Dimensions are not displayed properly

### ISSUE THREAD

**Issue by websolut** [grafana/grafana#67317]
## What happened:
After the latest upgrade of managed Grafana our dashboard for Availability tests is broken. Dimensions are listed as 'Availability + app_insights_name'

Another example:
![image](https://user-images.githubusercontent.com/13100077/234721979-80d7562a-008a-42ed-b8c7-d5f1b391158e.png)

## What you expected to happen:
Previous versions displayed correct dimension names

## How to reproduce it (as minimally and precisely as possible):
Add a metric panel with app insights as a source
Type - State Timeline
Metric name - Availability (Average, time grain - Auto)
Dimension == null

## Anything else we need to know?:
Workaround:
Add a transformation - Label to field by column

## Environment:
- Grafana version: 9.4.8
- Data source type & version: Azure Metric
- OS Grafana is installed on: Azure managed grafana
- User OS & Browser: Windows Firefox
- Grafana plugins:
- Others:

**Comment by bossinc** [comment]
@websolut The default legend label format has changed. Here is documentation on how to customize the legend labels. [Format legend aliases](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/query-editor/#format-legend-aliases)

Feel free to reopen the issue if this does not solve the problem. 🙂
