### ISSUE TITLE
Alerting with CloudWatch plugin missing data when intermediate queries are hidden

### ISSUE THREAD

**Issue by toraora** [grafana/grafana#67320]
## What happened:
Alerts built from panels with hidden queries fail to fetch data unless ID overrides are provided

## What you expected to happen:
Alerts should work with hidden intermediate queries

## How to reproduce it (as minimally and precisely as possible):
1. Create a panel with a CloudWatch source that has hidden queries A and B, and an expression C
2. Create an alert based on the panel with a threshold on C
3. Alert does not execute queries and displays "No data"

## Anything else we need to know?:
In [AlertingQueryRunner](https://github.com/grafana/grafana/blob/release-9.4.9/public/app/features/alerting/unified/state/AlertingQueryRunner.ts#L57) there is a check against the datasource as to whether a query should be run or not. The [CloudWatch datasource](https://github.com/grafana/grafana/blob/release-9.4.9/public/app/plugins/datasource/cloudwatch/datasource.ts#L75) implements this check, allowing either non-hidden queries or queries with an ID to pass. A single query that fails this check causes the entire alert to not execute. This is perhaps more of a UI/UX issue rather than a technical one, but I think either
- the query should be run regardless for alerting purposes, or
- the fact that the query is hidden isn't obvious or changeable from the alert editor, and the option should be made available there

## Environment:
- Grafana version: 9.4.7
- Data source type & version: CloudWatch
- OS Grafana is installed on: Debian
- User OS & Browser: MacOS Firefox / Safari
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
Closing as no answer from original author. Please reopen if you can provide more information in the future.
