### ISSUE TITLE
PanelHeader: Fixed header in shown on mobile devices

### ISSUE THREAD

**Issue by edvandreas** [grafana/grafana#67322]
**Steps to reproduce**:
Create a dashboard with panels and open on a tablet or phone. The Panel Header will take away some space on top of the panel.
see picture

**Actual Result**:
Panel Header resizes the actual panel

**Expected Result**
Panel Header can be hidden or is automaticaly hidden like in older versions

**Environment**:
- Grafana version: 9.5.1 and main branch
- Data source type & version: influxdb 2.7.0
- User OS & Browser: Android Chrome & iPhone Safari
- Others:

![sample](https://user-images.githubusercontent.com/58737595/234673358-50d144ac-e5b2-429e-8b5c-97855852e22b.png)

**Comment by fheck** [comment]
I second this. Some smaller panels are now virtually unusable.

**Comment by UnrealCraig** [comment]
Yes, the updated UI doesn't adapt well to smaller screens

**Comment by dprokop** [comment]
Hi folks, sorry for the trouble. We did that to improve the accessibility, but indeed missed the aesthetics an UX of the change. We will reverti this change in a bit, and approach solving the a11y issue in a different way.

**Comment by edvandreas** [comment]
Thank you! Looks so much better now.
