### ISSUE TITLE
Trace and Node Graph Suggestions are Missing

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#67328]
## What happened:
If you try to open an individual trace in one of our datasources (ex Opensearch or Xray) in the dashboard query editor, you won't see the Trace visualization listed as a suggestion:
<img width="1419" alt="Screenshot 2023-04-26 at 3 58 11 PM" src="https://user-images.githubusercontent.com/6620164/234688698-c608da4a-c79a-40a8-8d52-76bafb34e794.png">

## What you expected to happen:
I expected to see a little preview of the traces visualization that would show as an option in Suggestions, particularly because as a plugin developer I'm passing a meta data property on the dataframe for the preferredVisualisationType to be trace. 

I took a little look at the code and I think we just haven't gotten around to writing a suggestions supplier. Here's an example for Logs: 
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/logs/suggestions.ts
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/logs/module.tsx#L85

Would be awesome if we had something similar for Traces. I suspect it's not a super common experience to want to create a dashboard for an individual trace but I also could see someone playing around with the plugin, not yet seeing the Explore tab and it seems a bit hard to find. 

## How to reproduce it (as minimally and precisely as possible):
- Use any datasource that has traces
- try querying for a single trace in a dashboard query editor
- notice that the Traces view does not come up in the suggestion, even if you look at the preferred visualization field in the dataframe you'll notice trace is listed there.

## Anything else we need to know?:
The same happens for Node Graph, and I could see that being an easier to miss but more useful feature that one might actually use in a dashboard. Happy to demo this for someone with X-ray if it's helpful.

## Environment:
- Grafana version: ~9.5?
- Data source type & version: Opensearch, X-Ray probably any other datasource that uses a traces visualization

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/grafana/pull/83311 and https://github.com/grafana/grafana/pull/83089
