### ISSUE TITLE
[Feature request] Shared Crosshair locking.

### ISSUE THREAD

**Issue by mcaleavya** [grafana/grafana#6732]
Hi would it be possible when having a dashboard with multiple graphs to lock the crosshair for all graphs when looking at a specific time frame. It would also be good if each chart would then have the tooltip with the values shown for easy point in time analysis.

**Comment by torkelo** [comment]
you can have shared crosshair (enable in dashboard settings or with shortcut mod+o .

Not sure what you mean by locking
