### ISSUE TITLE
Google Cloud Monitoring data source

### ISSUE THREAD

**Issue by oryband** [grafana/grafana#6733]
Google Cloud Platform is a major cloud provider nowadays, and I'd like to centralize our graphs in Grafana, instead of having to manage multiple graph backend (in this case Google Stackdriver).

Google [has made Stackdriver generally available](https://cloudplatform.googleblog.com/2016/10/Google-Stackdriver-Generally-Available.html), and has a [metrics API](https://cloud.google.com/monitoring/docs/apis).

Please add support for fetching metrics from Google Cloud Monitoring, similar to [AWS CloudWatch data source](http://docs.grafana.org/datasources/cloudwatch/).

**Comment by utkarshcmu** [comment]
@torkelo/@bergquist Would you like to have Google Cloud Monitoring data source as a separate plugin or a part of Grafana core?

**Comment by torkelo** [comment]
separate plugin

**Comment by utkarshcmu** [comment]
Thanks, will start the work here asap - https://github.com/utkarshcmu/google-cloud-platform-datasource.

**Comment by oryband** [comment]
@utkarshcmu any updates?

**Comment by utkarshcmu** [comment]
@oryband nothing yet 😞

**Comment by utkarshcmu** [comment]
I am working on #6348 currently. As soon as I complete #6348, will start working on this issue.

**Comment by utkarshcmu** [comment]
If anyone wants to give a start to this, you may start contributing to the repo(https://github.com/utkarshcmu/google-cloud-platform-datasource). As soon as I get some time from other issues/tasks, I will start some work on this feature request.

**Comment by tomboxme** [comment]
+1. Love this idea.

**Comment by mtanda** [comment]
FYI. I made very basic implementation.
https://github.com/grafana/grafana-plugin-repository/pull/152

**Comment by Depado** [comment]
Any news on this one ? 😄 
Thanks for the great work by the way, Grafana team 😃

**Comment by daniellee** [comment]
@Depado The ball is in my court - mtanda has done a lot of work on this already. I will hopefully be able to get it published next week.

**Comment by Depado** [comment]
Awesome @daniellee !

**Comment by danslimmon** [comment]
I sure could use this data source! How's it going @daniellee? Want help testing or anything?

**Comment by daniellee** [comment]
@danslimmon it got stuck on my todo list (a lot of Grafana 5.0 work at the moment) but I will be getting around to it very soon. Help with testing would be appreciated - I can ping you once we get a bit further.

**Comment by jaingaurav** [comment]
@danslimmon: Any way for us to test this out in a beta form?

**Comment by jonomacd** [comment]
We are pretty keen in getting this as well. Happy to help with testing.

**Comment by mlauter** [comment]
Hi! any updates on the status of this? Happy to help with testing also.

**Comment by deimosfr** [comment]
Could be interresting to get this one: https://github.com/mtanda/grafana-google-stackdriver-datasource

**Comment by AndrewFarley** [comment]
+1   I mean, come on guys... this is pretty lame at this point.  A stable, integrated (by default) data provider needs to happen for StackDriver.  That one above form mtanda is rife with problems and very poor documentation.  Can we please get some attention here?  Google Cloud is a fairly serious contender in the cloud arena and I'd love to have sexy integrations with it for my clients like I can do with CloudWatch.

**Serious note:** I'll sponsor someone with a gift card to somewhere online if you can put your foot down and make this happen ASAP.  Say, $100?  Not a joke, I've followed through on a few of my other offers here on Github to help sponsor progress.  I wish I had the time I'd do it myself.  Lets make this happen!

**Comment by AndrewFarley** [comment]
@mtanda I'd love to see this happen, but (just my opinion) I think the plugin still needs some  refining.  There is poor/no error debugging on why things fail when you try to connect up the data source (not visually in grafana, you have to use the console to debug, you just see a exclamation point and a red pop up with no errors), the metrics screen does have some help which is useful and has some auto complete, but the drop downs for sorting/aggregation still use key names instead of human readable terms.  But even with those errors it's definitely usable, and I really appreciate your work and anyone's work on the topic.  I'd like to see it refined and brought into mainstream, so whatever it'll take.  I can help test things and provide more direct feedback if necessary to you, and/or from Grafana maintainers.  But lets try to make this happen eh?

**Comment by mtanda** [comment]
@AndrewFarley Thanks for your feedback. I agree with the point, it lacks useful error notification.
When I have a time, I can work on improving quality.

But, I guess Grafana core team doesn't want to add new datasource.
Like Azure datasource, they want to provide plugin as a separate distribution.
https://github.com/grafana/azure-monitor-datasource/

@torkelo @daniellee Please tell us, your opinion.

**Comment by Reifier** [comment]
Yeah, pretty please.

**Comment by mtanda** [comment]
Grafana Labs seems to start stackdriver datasource implementation.
https://github.com/grafana/grafana/tree/stackdriver-plugin/public/app/plugins/datasource/stackdriver

**Comment by daniellee** [comment]
Still some work to do but the Stackdriver datasource is now merged to master and will be included in Grafana 5.3 as a beta datasource.

**Comment by daniellee** [comment]
A huge thanks to @mtanda for his plugin which has provided a lot of the inspiration for this implementation.
