### ISSUE TITLE
9.4.9 changelog is basically empty

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#67339]
I think there were dozens of fixes backported to the v9.4.x branch since 9.4.7, but the changelog only lists 9.4.9 and one change: "Upgrade Go".

Was there an intermediate 9.4.8 section that listed all the changes, and then got deleted?

https://github.com/grafana/grafana/blob/main/CHANGELOG.md#949-2023-04-24

![Screen Shot 2023-04-27 at 11 01 14 AM](https://user-images.githubusercontent.com/1708631/234740950-44f101f2-4c32-4f15-82ec-e912b47b34cc.png)

**Comment by usmangt** [comment]
Hi @belm0,

Thanks for opening this issue.

No, it is correct as I double-checked that in 9.4.9 only Go package got updated and there was no 9.4.8 release (at least not for public users).

**Comment by usmangt** [comment]
Please ignore my previous message as it is not correct. I got to talk with one of the Engineers and Yes, there are many changes which got released in 9.4.7 (link [here](https://github.com/grafana/grafana/issues?q=is%3Aclosed+milestone%3A9.4.9))

**Comment by zerok** [comment]
Just a bit of background: The changelog (in the repository here and also on https://community.grafana.com) is generated based on what PRs are attached to a specific milestone (9.4.9 in this case) and which of those have the label "add to changelog" set.

Sadly, in this case that list got condensed down to only that single PR. That's a topic of ongoing discussion how we can improve the situation here. Sorry that I cannot offer anything more useful at this time 🙁

**Comment by zerok** [comment]
Fixed now 🙂
