### ISSUE TITLE
Monitoring for Azure Machine Learning Endpoint in Grafana not shown in resource picker

### ISSUE THREAD

**Issue by maciejglowackimg** [grafana/grafana#67345]
## What happened:
I wanted to set up monitoring for Azure Machine Learning Endpoint in Grafana. Unfortunately, I don’t see any Endpoints on the dropdown list. I have Gitlab version 15.8.0 and Grafana version 9.4.7. Has anyone tried monitoring ML Endpoints through Grafana?

request visible in console is:
GRAFANA_URL/api/datasources/uid/UID/resources/azuremonitor/subscriptions/SUBSCRIPTION_ID/resourceGroups/MaciejML/providers/microsoft.machinelearningservices/workspaces/ENDPOINT_NAME/onlineendpoints//providers/microsoft.insights/metricdefinitions?api-version=2018-01-01

but it should be:
GRAFANA_URL/api/datasources/uid/UID/resources/azuremonitor/subscriptions/SUBSCRIPTION_ID/resourceGroups/MaciejML/providers/microsoft.machinelearningservices/workspaces/WORKSPACE_NAME/onlineendpoints/ENDPOINT_NAME/providers/microsoft.insights/metricdefinitions?api-version=2018-01-01

and I am not able to get this with different values in “Namespace” and “Resource Name” values that I’ve tried

seems like it is connected to “azure_monitor/url_builder.ts”, but I didn’t dig into code enough to track it down

querying resource with curl (according to [Azure monitoring REST API walkthrough - Azure Monitor | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/rest-api-walkthrough?tabs=portal) )
works correctly.

curl --location --request GET '[https://management.azure.com/subscriptions/****/resourceGroups/MaciejML/providers/microsoft.machinelearningservices/workspaces/MaciejML/onlineendpoints/orders23/providers/microsoft.insights/metricDefinitions?api-version=2018-01-01’](https://management.azure.com/subscriptions/****/resourceGroups/MaciejML/providers/microsoft.machinelearningservices/workspaces/MaciejML/onlineendpoints/orders23/providers/microsoft.insights/metricDefinitions?api-version=2018-01-01%27) --header ‘Authorization: Bearer ****’

## What you expected to happen:

I would like to monitor endpoints, see them on a list, and display metrics

## Anything else we need to know?:

https://community.grafana.com/t/monitoring-for-azure-machine-learning-endpoint-in-grafana-i-dont-see-any-endpoints-on-the-dropdown-list/86424/2

## Environment:

grafana cli --version
grafana version 10.0.0-112993pre

![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/131944141/234769744-79661540-6228-49d2-bf17-a51fedc57ff0.png)

**Comment by mellieA** [comment]
@maciejglowackimg the community is the right space for this kind of discussion. We use github for potential bugs & feature requests.

**Comment by mellieA** [comment]
Discussion in the community and reading https://github.com/grafana/grafana/issues/50239 it sounds like this resource should show up.

There is a workaround to manually enter it, if we suggest this often, should we document it?

**Comment by aangelisc** [comment]
This is a valid issue we can look at investigating.

**Comment by taleena** [comment]
We're tracking namespaces here also: https://github.com/grafana/grafana-enterprise-mirror-shared-microsoft/issues/152

**Comment by neilmca-inc** [comment]
+1 here for supported Azure Machine Learning resources in the resource picker please (Grafana Cloud user here)

We require this for ENDPOINTS and DEPLOYMENTS (connected to the Endpoints) - thanks
