### ISSUE TITLE
changing root policy or restarting grafana would retrigger firing alert

### ISSUE THREAD

**Issue by bossjie** [grafana/grafana#67344]
## What happened:
1.someone changes the root policy
2. OPS team restart grafana for some purpose like OS bundle upgrade
## What you expected to happen:
firing alert would not be triggered as they have been notified before.

## How to reproduce it (as minimally and precisely as possible):
make an firing alert with email contact point
change root policy or restart grafana
then email would be retriggered

## Anything else we need to know?:
I raise up another ticket for permission issue, for #1, if it's fixed, then it would be ok.
but #2  for now, I have to create silence for ALL alerts. before this action, I have to append a label to controll all of them.
then I could create silence to make them silent.  would like to learn what's the best practise for this case.

## Environment:
- Grafana version:  9.4.7
- Data source type & version: NA
- OS Grafana is installed on: centos8
- User OS & Browser: chrome
- Grafana plugins: NA
- Others: NA

**Comment by armandgrillet** [comment]
The alerting team was unable to reproduce both situations mentioned (restart and change of the root policy), please reopen this issue with more details if you get some.
