### ISSUE TITLE
Alert Rule notification add more than one label doesn't work

### ISSUE THREAD

**Issue by yxStory** [grafana/grafana#67347]
## What happened:
I have added two different labels in alert rule notification, one is webex team space, another is pagerduty, but I only receive one alert in webex team space.
![Screenshot 2023-04-27 at 13 59 52](https://user-images.githubusercontent.com/26163471/234772708-c43910b9-ab91-43cd-b9f2-0c2cecbae3c2.png)

## What you expected to happen:
I want to receive alerts what I assigned in notification.

## How to reproduce it (as minimally and precisely as possible):
1. create two different labels
2. create a new alert rule
3. add two labels created in step1 in notification
4. trigger the alert, check the alert you received

## Anything else we need to know?:
How to send alerts to different place at the same time

## Environment:
* Grafana version: 9.4.7
* Data source type & version: NA
* OS Grafana is installed on: centos8
* User OS & Browser: chrome
* Grafana plugins: NA
* Others: NA

**Comment by yuri-tceretian** [comment]
It depends on the notification policy you created. If you have two notification policies that are direct children to root policy, and first matches one label, and the second matches another label - then by default, only the first will process the notification. To send notification to both policies, the first policy should have setting `continue` set to true.

**Comment by yxStory** [comment]
Thanks, it works.

**Comment by omerfarukavci** [comment]
I set 2 notification policies and connected them to contact points. I set the "Continue matching subsequent sibling nodes" option to true. But for some reason it doesn't send to either e-mail. What can I do?

![image](https://github.com/grafana/grafana/assets/45371275/0b7980a4-0eb7-426c-80ce-0b7c3fd41703)
