### ISSUE TITLE
Datagrid: Add column btn on hover styling issue

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#67365]
Color is off in the add column btn when hovering

![Screenshot 2023-04-27 at 12 15 09](https://user-images.githubusercontent.com/36818606/234817964-0382ea75-708a-4300-9c86-0ff957b8f41d.png)

**Comment by supilee** [comment]
Seems still off or a different issue. when hovering from the last column to the add column it now has both, the last and the + column highlighted.

https://user-images.githubusercontent.com/110845248/234966481-6a7ca4d2-70d2-4445-9d39-3513d9f40b89.mov

**Comment by mdvictor** [comment]
Closing this as fixed. The problem in the last video is tied to an upstream bug and tracked here: https://github.com/grafana/grafana/issues/67689
