### ISSUE TITLE
Shortcut toggle all panel legens doesn't work with timeseries

### ISSUE THREAD

**Issue by frenkye** [grafana/grafana#67378]
## What happened:
Just started to play around with shortcuts and notice that, toggle all panel legens only worked on Graph(old) panels and not on timeseries. When I migrate panel to timeseries toggle stop working.

## What you expected to happen:
I would expect it would work on all panels when labels says all panels.

## How to reproduce it (as minimally and precisely as possible):
Create timeseries panel and try the shortcut. Video attached.

## Environment:
- Grafana version: 9.5.1 and 9.4.7 when first noticed
- Data source type & version: Prometheus v2.42.0
- OS Grafana is installed on: Debian Bullseye
- User OS & Browser: MacOS Ventura 13.2.1. Tested on latest Firefox and Chrome. 
- Grafana plugins:
```
$ grafana-cli plugins ls
installed plugins:
camptocamp-prometheus-alertmanager-datasource @ 1.0.0
grafana-image-renderer @ 3.4.1
grafana-piechart-panel @ 1.6.2
grafana-worldmap-panel @ 0.3.3
vertamedia-clickhouse-datasource @ 2.4.2
```

https://user-images.githubusercontent.com/13994937/234840659-72048eee-17ac-44a1-8885-d1c5c12569b6.mov

**Comment by mellieA** [comment]
There was an external PR for this but it was closed before it got merged because the community contributor couldn't test with old graph panels once they were deprecated. 

https://github.com/grafana/grafana/pull/60754
