### ISSUE TITLE
[Bug] Some of the graphs stuck after upgrade to 4.0 beta2

### ISSUE THREAD

**Issue by alyan2008** [grafana/grafana#6737]
Grafana version - 4.0 beta2
Datasource - Influxdb 1.1
OS - Ubuntu 14.04
What did you do? - Grafana was upgraded from 3.1.1 to 4.0 beta2
What was the expected result? - At least everything should work properly, like I had in previous version.
What happened instead? - Some of the graphs stopped loading. In influxdb logs I see that grafana doesn`t send any requests for some metrics. 

For example:

I have screen for server performance. Currently on the screen I can see statistics - connections stats

![screen_1](https://cloud.githubusercontent.com/assets/7196207/20678726/73eb4c7a-b5a0-11e6-990a-f5a931c1533c.JPG)

In debug tool I can see the query only for tcp_established and tcp_close_wait metrics:

![image](https://cloud.githubusercontent.com/assets/7196207/20678817/d596d642-b5a0-11e6-9728-d94a3c0c97d6.png)
![image](https://cloud.githubusercontent.com/assets/7196207/20678824/e0933ce8-b5a0-11e6-940d-3bd86c9fd9e9.png)

Also in console I have found this error:

![image](https://cloud.githubusercontent.com/assets/7196207/20678869/0c4f989a-b5a1-11e6-8758-7a8dc9b6da11.png)

Please check it.

**Comment by alyan2008** [comment]
It starts working after remove - Group by time inetrval variable:

![image](https://cloud.githubusercontent.com/assets/7196207/20679374/4762e2b4-b5a3-11e6-8903-71e116065e45.png)

Please check it

**Comment by bergquist** [comment]
whats the value for $inter when the panel breaks?

**Comment by alyan2008** [comment]
We don`t use this variable. Looks like if we don`t have the variable grafana doesn`t know how to generate the query. In the previos version it worked without any problem.

**Comment by alyan2008** [comment]
I have removed that variable from all graphs on the screen and don`t see any errors in the debug console:
![image](https://cloud.githubusercontent.com/assets/7196207/20679587/3b40fa10-b5a4-11e6-9113-462de20b834b.png)

**Comment by bergquist** [comment]
Not sure if I think this is a bug.

If $inter is used as interval but not set I don't think Grafana should fallback to some default value. It should throw an error. But I guess the error could be improved.

**Comment by torkelo** [comment]
using a interval variable set to auto in the group by time field should work:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?var-datacenter=America&var-host=server1&var-host=server2&var-summarize=$__auto_interval

try recreating the variable, or provide the json for your dashboard

**Comment by bergquist** [comment]
Seems to me that your not using grafana 4beta2. 

The width on "Group by time interval" label is from an older version.
