### ISSUE TITLE
Elasticsearch: Refactor configuration page following the new best practice guidelines

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#67383]
the goal is to improve the elasticsearch datasource config page:
- adjust the page based on the recommendations in https://docs.google.com/document/d/11XMaYHSMSra8AoN2-yVW-5QPbjEXgkAFbTIF6N84cGE/edit#
    - as an example, [a pr doing the same for loki](https://github.com/grafana/grafana/pull/66216)
- https://github.com/grafana/grafana/issues/62209
- https://github.com/grafana/grafana/issues/62207

Pending tasks:
- [x] [HTTP Settings](https://github.com/grafana/grafana-experimental/blob/main/src/ConfigEditor/migrating-from-datasource-http-settings.md).
- [x] Tooltips.
- [x] Error messages

**Comment by matyax** [comment]
Will link this to the epic. https://github.com/grafana/grafana/issues/65294

**Comment by matyax** [comment]
Work completed after https://github.com/grafana/grafana/pull/72840
