### ISSUE TITLE
[Bug] windows phantomjs distribution

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#6738]
Using Grafana v4.0.0-beta2 on Windows 7 Embedded.  I tried testing an alert with 'external_image_storage.s3' enabled.  I got:

```
t=2016-11-28T12:50:01-0800 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="exec: \"C:\\\\path\\\\grafana-4.0.0-beta2\\\\vendor\\\\phantomjs\\\\phantomjs.exe\": file does not exist"
t=2016-11-28T12:50:01-0800 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=1 isDefault=false
```

When I rename the file:
`C:/path/grafana-4.0.0-beta2/vendor/phantomjs/phantomjs`
To
`C:/path/grafana-4.0.0-beta2/vendor/phantomjs/phantomjs.exe`

everything works fine.

**Comment by torkelo** [comment]
strange that there are no other reports on this and that this used to work before, cannot see anything that caused it to break.

**Comment by torkelo** [comment]
Maybe something with windows 7 embedded?
