### ISSUE TITLE
[9.5.1] [Elasticsearch Backend Data Source] "Invalid date" when viewing Elasticsearch Logs

### ISSUE THREAD

**Issue by trexx** [grafana/grafana#67391]
## What happened:
Upon updating from 9.4.7 to 9.5.1, when viewing logs via our Elasticsearch datasource in Explore, we do not see log entries dated and instead see "invalid date" 

Before:
![image](https://user-images.githubusercontent.com/874158/234866518-d7549a42-81fb-4f65-8475-94b45666a136.png)
After:
![image](https://user-images.githubusercontent.com/874158/234866468-babf44e3-35a5-4f6b-bdeb-49fe87e16b3e.png)

If we go to a dashboard displaying logs, we can see dates there. So the problem seems localised to the Explore view.

![image](https://user-images.githubusercontent.com/874158/234866911-1a2d4bf3-2b8b-42a5-90c5-416774638866.png)

## What you expected to happen:
We wanted to see dates along side our message when viewing logs in Explore

## How to reproduce it (as minimally and precisely as possible):
I downloaded a windows version of 9.4.7 and configured our datasource as approperate, taking note to set the time field name to @timestamp. I confirm it was working as expected.
I then downloaded 9.5.1, copied the data directory from 9.4.7 in to the extracted folder and executed grafana-server. Upon viewing logs, "invalid date" was in place of where we expected to see timestamps.

## Anything else we need to know?:
Our @timestamps are using the date_nano field type. Our timestamps are formatted as epoch_millis. "1682602574704.8618" is how they are stored in the data frame in 9.4.7.

Other logs that are using date field type seems to display as expected.

Kibana renders the timestamp fine.

## Environment:
- Grafana version: 9.5.1
- Data source type & version: Elasticsearch (Running 7.10.2)
- OS Grafana is installed on: Kubernetes (Reproducible on Windows)
- User OS & Browser: Windows Edge
- Grafana plugins: N/A
- Others: N/A

**Comment by trexx** [comment]
Looks like this is due to **https://github.com/grafana/grafana/pull/65339**
Upon adding disableElasticsearchBackendExploreQuery to feature flags, I get timestamps back again. We'll keep it disabled for now.

**Comment by ivanahuckova** [comment]
@trexx thank you for creating the issue! 🧡 I was trying to reproduce this, but unfortunately I wasn't able to. So I'd like to ask you for couple more things that would help me investigate:
- for version 9.5.1 when you get `invalid date`, could you please share the query response using query inspector (Inspect button > Query tab). I'd like to learn how backend processes the time field and why does it return incorrect format
- for version 9.4.0, or 9.5.1 with disabled `disableElasticsearchBackendExploreQuery` (when you get valid date), could you please do the same and share the response. I'd like to learn how data arrive directly from the elasticsearch.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/30407135/235677584-395310de-59f2-475e-854a-c0bb8452821c.png">

This would help me tremendously to figure out what is the difference between those responses and how to fix it. 

Thank you!

**Comment by trexx** [comment]
@ivanahuckova Thanks for taking the time to help me.
Here's the data you requested as gists.
9.5.1 Invalid Dates -> https://gist.github.com/trexx/6171e2aff6e05f047a3393ec200a8607
9.5.1 with disableElasticsearchBackendExploreQuery -> https://gist.github.com/trexx/48bf1a35f64b08625a90886e63cf759f

Hopefully those will be of some use.

**Comment by ivanahuckova** [comment]
Thank you! This helped a lot! I will work on fix, and in the meantime, please use `disableElasticsearchBackendExploreQuery` flag to remove the issue for you.
