### ISSUE TITLE
[Feat Req] Metrics from AWS Cloudfront

### ISSUE THREAD

**Issue by ricardclau** [grafana/grafana#6739]
- What Grafana version are you using? 3.1.1
- What datasource are you using? Cloudwatch
- What OS are you running grafana on? Ubuntu 16
- What did you do? Try to graph Cloudwatch metrics from Cloudfront

Hi

I was trying to use Grafana to plot some Cloudwatch metrics from Global Services and I don´t seem to be able to. These services are supposed to generate metrics in a fake region called "Global" but when I set the region to it I can see Grafana is trying to contact https://monitoring.Global.amazonaws.com/ in the logs which obviously does not exist

I have even added full access to any cloudfront resource from the Grafana EC2 instance on top of the required GetMetricStatistics / ListMetrics with no success

Is this a known limitation / bug? Any hints on what can I do (if anything) to get these metrics shown in Grafana?

**Comment by torkelo** [comment]
@mtanda do you know anything about this?

**Comment by mtanda** [comment]
We don't use Cloudfront, I don't know it.
According to docs, the region is looking like dimensions.
http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html

I think the region field in CloudWatch datasource config page should be like `us-east-1`, not `Global`.
And set `Region` dimensions to `Global` may work.

**Comment by ricardclau** [comment]
I am sorry, the docs were a bit misleading and now I can finally display Cloudwatch metrics

I am posting a screenshot for reference in case someone else has similar issues

![image](https://cloud.githubusercontent.com/assets/613725/20816994/21a4563a-b81d-11e6-89a2-6375d49c19d5.png)

So, essentially, region must be us-east-1 as this is where the data is stored (https://monitoring.us-east-1.amazonaws.com/) and you need to specify Region: Global in metrics as the docs state

Sorry about opening this and the issue can be closed!
