### ISSUE TITLE
[Feature request] Internal Metrics publisher for common ingestion systems

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#6742]
Please instrument Grafana.

Especially things like query runtimes, access rates per dashboard, etc are interesting.

I suspect @bergquist already has a mental model of what he would want to see there.

While I only care about Prometheus, it might make sense to also support Graphite in Grafana.

**Comment by RichiH** [comment]
FYI, I will be running Prometheus & Grafana at Congress this year; ideally, I would want to have metrics about the usage of the public dashboard by that time.

**Comment by bergquist** [comment]
We already support instrumenting grafana using graphite. 

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L404

**Comment by torkelo** [comment]
This should be quick to implement for anyone who wish to help. 

Just implement the MetricPublisher interface. 
https://github.com/grafana/grafana/blob/master/pkg/metrics/settings.go#L5

**Comment by mtanda** [comment]
To implement this, need to vendoring client_golang, https://github.com/prometheus/client_golang/tree/master/prometheus .
Is it acceptable?
If so adding the publisher should be quite easy.

**Comment by bigkraig** [comment]
@mtanda I'd assume so, seems like the only way and logical

**Comment by bigkraig** [comment]
@torkelo Is implementing the MetricsPublisher what we want? Prometheus works by scraping target URLs, so normally we would expose an endpoint like /api/metrics but it would be in the Prometheus format. They make this very easy with the library that @mtanda mentioned.

**Comment by RichiH** [comment]
https://github.com/grafana/grafana/issues/8357 could be start of data to export, even without proper integration of a full client.

**Comment by RichiH** [comment]
To address https://github.com/grafana/grafana/pull/6872 : It would be possible to use the Prometheus library to collect all data and then grab said data for a push while enabling normal Prometheus scraping. As that would also move to live data, this might solve those issues on the collection side, at least.

**Comment by RichiH** [comment]
Pulling @brian-brazil into this issue as he was active in the PR, but not here.

**Comment by brian-brazil** [comment]
Many Prometheus clients (including Go) have an example of pushing data to graphite included, so it'd be possible to switch to client_golang while keeping the existing Graphite support.

It's easy to convert pull to push, the other way round not so much.

**Comment by bergquist** [comment]
If we want to implement support for more then graphite I think we should use a generic library that support multiple datasources. Ex https://github.com/go-kit/kit/tree/master/metrics

**Comment by RichiH** [comment]
I do hope that this will be generic soon(tm)

  https://github.com/RichiH/OpenMetrics

**Comment by brian-brazil** [comment]
The generic library for that would be the Prometheus client_golang :)

**Comment by torkelo** [comment]
The current metrics lib supports multiple publishers, but prometheus one looks better, except not sure it supports counters properly (the way I want to use counters), nor how easy and accurate the graphite publisher is for the prometheus lib

**Comment by brian-brazil** [comment]
The graphite bridge takes the raw Prometheus data and munges the labels into the metric name. You'll end up with the raw counter, which you could use `nonNegativeDerivative` with.

**Comment by bergquist** [comment]
I suggest we should rename this issue "[Feature request] Multiple support for internal metrics". I'm kinda ashamed that we don't give our users good metrics already.. Considering what Grafana is built for..

I think should at least support graphite, influxdb and prometheus.

**Comment by torkelo** [comment]
Prometheus is so hard to support because its so different than every other tsdb though, but I like parts of its metrics lib :)

**Comment by torkelo** [comment]
But I agree, internal metric support needs to be expanded to those tsdbs

**Comment by bergquist** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Internal metrics support Prometheus](https://trello.com/c/L3kNJjwv/12-internal-metrics-support-prometheus)

**Comment by RichiH** [comment]
@bergquist: The link to that trello.com scorcard is private.

**Comment by bergquist** [comment]
Graphite and Prometheus is now supported. Still missing Influxdb.

**Comment by bergquist** [comment]
Closing this since there is another issue for adding support for influxdb. https://github.com/grafana/grafana/issues/5596
