### ISSUE TITLE
Hide URL variables with hash

### ISSUE THREAD

**Issue by flistonfr** [grafana/grafana#67445]
Hi!

It will be nice to make a hash of the url to hide variables values. 
Sometimes you would like to send a link with custom variables, but don't want the user to change them.

Example: 

Original: 

**https://play.grafana.org/d/YMRptAzGz/query-via-url?orgId=1&var-query=TEST** Where 'query' variable has value 'TEST'

**https://play.grafana.org/d/YMRptAzGz/XXXXXXXXXX** Where 'XXXXXXXXXX' is the hash that grafana will decode as 'query-via-url?orgId=1&var-query=TEST'

**Comment by mrsdoa** [comment]
Hi, did you manage to find a solution?

**Comment by flistonfr** [comment]
> Hi, did you manage to find a solution?

Unfortunately no.

Any ideas?
