### ISSUE TITLE
[Bug] Grafana dashboard once gets into error "Annotations error, Influx Error: undefined", it never refreshes out of it until the page is manually refreshed.

### ISSUE THREAD

**Issue by samdd** [grafana/grafana#6744]
Grafana Version : v3.1.1 (commit: a4d2708) 
Datasource : Influxdb
OS : Ubuntu 14.04.4

Here is snapshot of the error attached. network logs for chrome do not have mush details except, "Influx Error: undefined" error. 

![screen shot 2016-11-29 at 10 01 11 am](https://cloud.githubusercontent.com/assets/19291010/20724140/ebbc2e50-b621-11e6-9887-fa7d7695a45c.png)

**Comment by torkelo** [comment]
Can you open chrome dev tools and network tab, please check what the request and response is from InfluxDB

**Comment by samdd** [comment]
Okay. I figured out whats happening. So this error occurs when grafana fails to connect to influxDB. 

But my concern is, once grafana is out of this error condition i.e. when it reconnects to influxDB fine,  this error pop-up (alert window) still stays there on the dashboard until you refresh the page manually.  

I expect this pop-up(alert window) to get closed after the error condition is cleared.

**Comment by samdd** [comment]
@torkelo could you please take a look at the updated comment above ?

**Comment by torkelo** [comment]
Yes, error popup should be cleared after some timd

**Comment by samdenty99** [comment]
@samdd Hey there! Was wondering if I would be able to have your username? I understand if you say no

Thanks!
