### ISSUE TITLE
[Bug?] Unable to load datasource meta data / InfluxDB error: undefined.

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#6745]
Please include this information:
- What Grafana version are you using?
4.0.0-beta2, also observed on 3.1.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Opened dashboard with big amount of graphs
- What was the expected result?
Graphs should load correctly
- What happened instead?
InfluxDB error: undefined.
Nothing in error message, "request", "response", js stacktrace - they are completely empty.

Dig up those in grafana logs:
```
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=6ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=8ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=4ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=1ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=1ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=1ns size=49
t=2016-11-29T21:47:01+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-29T21:47:01+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=1ns size=49
```

Enabled influxdb tracing and turns out those requests does not even hit influx http interface.
So far, i tried:
1) Switching from sqlite3 to postgresql (fresh install, no migration)
2) Using grafana without nginx as reverse proxy
3) Using direct connection without proxy to influx

So far, that's how it happens:
I have dashboard with alot of metrics from mysql (using it as draft). Half of metrics are in minimized row, and when i open them, they appears with that "undefined" error. After some time, even metrics that was loaded correctly fails to load with same error. If i copy/paste this non-working graph to other dashboard with no other graphs, it loads correctly and very fast.

I suspected that was something with influxdb, but it's not throwing any errors (had it with http / query tracing running for some time).

**Comment by torkelo** [comment]
This is very strange. Maybe something wrong with disk io. This has been reported before, but extremely rare, think only one other person had this, but never discovered the cause. what grafana database do you use? can you show content for your datasource table? 

Do you have multiple tabs open and logged in using different users & organizations?

**Comment by rlex** [comment]
>Maybe something wrong with disk io.  

Nothing i'm aware of, at least it seems so looking at graphs.

>This has been reported before  

Yep, i found those tickets and tried every solution provided in them, sadly wasn't able to solve main issue.

>what grafana database do you use?

Primary sqlite (not a huge amount of dashboards, so i decided to leave it "as is"), but i tried with postgresql as well.

>can you show content for your datasource table?

Do you need whole content or line with datastore i'm using will be enough?

```
12|1|0|influxdb|InfluxDB telegraf|proxy|http://localhost:8086|password|login|database|0|||0|{}|2016-11-17 11:43:57|2016-11-24 21:48:41|0|
```


>Do you have multiple tabs open and logged in using different users & organizations?

mmm... i do not have multiple tabs open, but i might have opened tab at my work notebook. And yes, there is moments when i have multiple tabs opened from several locations, sometimes with different orgs (i have just 2) as well.

**Comment by rlex** [comment]
Ok, on second pass of tests...
 
It works without nginx as reverse proxy, 100% stable.
It even works with nginx if i access it by http, also 100% stable.
But when it comes to https it suddenly starts to throw this errors.

How it looks: first everything is OK, i can open dashboard and can keep it stable even by pressing refresh in grafana several times per second. Then i open additional graphs (hidden row), and they starts to fail - even those that was working correctly before.
First connection to proxy closes with "ERR_CONNECTION_CLOSED", followed by alot of "ERR_CONNECTION_RESET" and 500s.

I think i _might_ be hitting some internal limits here, but it's not obvious why it only affects https.

**Comment by rlex** [comment]
(And at the same time, i see those grafana-server errors):
```
t=2016-11-30T03:22:28+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=1 uname=lex error="Data source not found"
t=2016-11-30T03:22:28+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=lex method=GET path=/api/datasources/proxy/14/query status=500 remote_addr=1.2.3.4 time_ms=20ns size=49
```

**Comment by torkelo** [comment]
think this is related to using multiple orgs in different tabs
