### ISSUE TITLE
Docs: "Publish a plugin" FAQ: What kind of metrics are available?

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#67458]
## What happened:

FAQ on this page says no plugin metrics are available

## What you expected to happen:

It may be that this isn't true given anyone can get downloads from the API and some plugins show as one of their shields. Research. Consider writing a new topic.

## How to reproduce it (as minimally and precisely as possible):

Go to https://grafana.com/docs/grafana/latest/developers/plugins/publish-a-plugin/

**Comment by sympatheticmoose** [comment]
This should only be considered as part of a wider look at the API from which these are available

**Comment by josmperez** [comment]
Moving to icebox until we look at documenting plugins API.
