### ISSUE TITLE
TraceView: Data sources that return JSONified strings instead of arrays are unable to show tags, logs, etc...

### ISSUE THREAD

**Issue by joeyj** [grafana/grafana#67454]
## What happened:

After https://github.com/grafana/grafana/pull/64920 was deployed, we've been attempting to adopt the TraceView in our grafana cloud instance. We ran into a problem with how the ADX data source returns JSONified strings for all dynamic fields. TraceView expects the raw arrays to be preserved. 

## What you expected to happen:

In order to keep backwards compatibility with how certain data sources behave, TraceView should utilize arrays as JSONified strings when encountered.

## How to reproduce it (as minimally and precisely as possible):

Any query using the ADX data source and a `dynamic` field will be treated as a string when returned from the grafana backend. Source: https://github.com/grafana/azure-data-explorer-datasource/blob/1d37cbfa4dd2a41654f1045607675032f4e01d52/pkg/azuredx/models/table.go#L75

## Environment:
- Grafana version: Grafana v9.5.0-cloud.5.a016665c (b2a5d45589)
- Data source type & version: ADX 4.2.0
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joeyj** [comment]
> 

TraceView has a pretty rigid set of expectations when it comes to data it will present. For example, if you include `logs` or any other field it expects as a list, it just throws an error (`o.logs?.map is not a function`) rendering the entire TraceView unusable.

The ADX data source treats dynamic fields as raw JSON. I think it would be preferable to change this behavior but I wasnt sure if this would break anything else down the line.

**Comment by aangelisc** [comment]
I don't think it'd make sense to change this behaviour in the datasource because the dynamic fields can be non-JSON. Would it make sense to attempt to parse the fields in TraceView if there is an error and if they can't be parsed then just make the user aware?

**Comment by joeyj** [comment]
I think that's similar to the PR I created: https://github.com/grafana/grafana/pull/67456

**Comment by aangelisc** [comment]
I'm going to transfer this to @grafana/observability-traces-and-profiling. Let me know if this should be moved back to our squad if the issue is identified as being datasource specific 😊

**Comment by aocenas** [comment]
> TraceView has a pretty rigid set of expectations when it comes to data it will present. For example, if you include logs or any other field it expects as a list, it just throws an error (o.logs?.map is not a function) rendering the entire TraceView unusable.

Well yes :D. I mean not sure we want to go in a direction where we will be more lenient. I mean this particular example, logs part is a list of something that hopefully is well shaped log item. We try to align with OTLP as much as possible in this and seems like most trace backends also go that direction.

So I wonder why ADX data source cannot supply the data parsed @aangelisc? I mean if there is some issue with the parsing of the raw json it's probably easier to handle/fix in the ADX data source than in trace view visualization where there may not be enough context. If it even isn't json as you mention then why even pass it down to visualization if it's already clear it cannot do anything with it?

**Comment by aangelisc** [comment]
@aocenas the reason it'd be challenging to supply the data parsed in an appropriate format for `TraceView` is because it isn't clear what shape the data may be. A `dynamic` type column in ADX can contain data of any shape e.g. arrays, objects, scalar values, etc. They can also be mixed.

@joeyj have you attempted to do any parsing of the data? Could you supply us with a set of example data and query? ADX isn't a traditional tracing backend which is why it isn't expected for this to work OOB.

**Comment by aocenas** [comment]
But what should trace view do about it? I mean you can see here https://grafana.com/docs/grafana/latest/explore/trace-integration/#data-api the logs is `TraceLog[]` where:
```
type TraceLog = {
  // Millisecond epoch time
  timestamp: number;
  fields: TraceKeyValuePair[];
};
```

If it isn't in this shape then we don't have a way to present it and by the meaning of the log in a trace it needs to be some data attached to a timestamp. So I really don't see how it would make sense to accept any kind of jsonString for that, we would still need to check if it has the right shape and if it doesn't discard it but at that point why should visualization have that responsibility? The data source itself has more information about the data and can decide whether it should be discarded or whether some transform can be done that makes sense. Visualization does not have that context.

**Comment by joeyj** [comment]
> @aocenas the reason it'd be challenging to supply the data parsed in an appropriate format for `TraceView` is because it isn't clear what shape the data may be. A `dynamic` type column in ADX can contain data of any shape e.g. arrays, objects, scalar values, etc. They can also be mixed.
> 
> @joeyj have you attempted to do any parsing of the data? Could you supply us with a set of example data and query? ADX isn't a traditional tracing backend which is why it isn't expected for this to work OOB.

I created a PR to go along with this issue :) https://github.com/grafana/grafana/pull/67456

**Comment by joeyj** [comment]
> Yep I agree with you there @aocenas that's a great point. I think we'll have to look into adding support for the TraceView visualisation at some point.

I'm unsure the exact contracts here but it could make sense to not stringify the dynamic fields and instead let them be objects then the TraceView could use type inspection to see if they are the expected type. This would allow for end-users to have the flexibility to adapt to the model expected by TraceView without much interference from the datasource impl.

**Comment by joeyj** [comment]
We exclusively use ADX for our logging and are currently blocked on using TraceView. Is there a minimal change to my PR that could help us get unblocked?

**Comment by aocenas** [comment]
Sorry @joeyj your PR probably works I am just a bit reluctant to make the visualization data contract more lenient as that is not the direction we want to go most of the time.

I am looking at the code, how we do this for Tempo and we send the fields as `json.RawMessage` type from backend which then seems to be automatically parsed when it gets deserialized on the front end. So this deserialization process actually is happening for tempo too just automatically.

Still wondering though if this would make sense to be pushed to the data source. It would mean datasource would have to know which fields to parse. I assume they are just string fields, so there is no metadata to indicate otherwise? If not, then ADX could try it on every string field but that probably does not make that much sense. One option would be to have a `format` switch in the query editor as a way for user to indicate what the data represents (we have that for example in Prometheus to do some formatting on the response) but that does not seem like the best UX for the user.

So maybe making the fields type to be `object | json string` makes sense. @joey-grafana what is your opinion on this, you work on the traceView a bit more than I atm.

**Comment by joey-grafana** [comment]
Honestly wherever has the best context to decide what to do with the data, should probably parse the data there into a format that can be visualised.

Would consider if the parsing is done in the visualisation, is that enough to work for other data sources too. There may be many cases where a data source sends data that does not conform to the requirements in the visualisation, over time this can build up much custom logic for the visualisation which may not be necessary if/when the data source is discontinued or the format in which the data source sends its data changes.

If the parsing is done in the data source, do we know more about how to transform the data into a format that the visualisation can accept. If the data source return format changes, it can be handled there, without the need to update the visualisation.

**Comment by joeyj** [comment]
I know I'm an outsider, but I think the datasource not stringifying the json object would be the cleaner approach.

**Comment by joey-grafana** [comment]
Could you elaborate a bit why you think this parsing is better handled in the visualisation and not the data source?

**Comment by joeyj** [comment]
Unsure if the question is targeted at me... but I'll respond just in case. I actually think handling in the datasource is better but I don't have context on the downstream effects of changing the behavior of the datasource. I didn't make a PR for that due to the concern listed so I went with the most practical/safe approach by parsing in the UI.

**Comment by aocenas** [comment]
I think @aangelisc is working on a solution specific for ADX for now, is that right? We may decide to support JSON strings as a different way of encoding at some point but that may come a bit later as we are currently just creating more concrete contracts for visualizations and the data formats they support. @aangelisc btw I am removing this from our squad board so please move this wherever this is appropriate.

**Comment by joeyj** [comment]
@aangelisc do you happen to know if this is active work? We'd really like to start using this in Grafana and are happy to help in any way :)

**Comment by aangelisc** [comment]
Hi @joeyj, this is active work and I'm looking at getting my changes reviewed 😊

**Comment by joeyj** [comment]
Thanks to everyone for helping this get across the finish line! We are beyond grateful.

**Comment by aangelisc** [comment]
No worries @joeyj 😊 this will be going out in the next release of ADX, please let me know if you have any issues

**Comment by joeyj** [comment]
@aangelisc I've attempted to utilize 4.6.0 and I'm getting a 500 returned from the datasource api call in grafana. I've attempted to narrow down the repro but can't seem to find a working scenario even with empty arrays defined for `tags` or `logs`. When I remove those fields, the error goes away.

**Comment by joeyj** [comment]
I found out the root cause. The data source can't handle empty objects or empty arrays and expects them to be null instead. Could we get this documented or allow for empty objects and arrays?

**Comment by aangelisc** [comment]
Great catch @joeyj, PR up [here](https://github.com/grafana/azure-data-explorer-datasource/pull/604) 😊
