### ISSUE TITLE
Error on "Alert rules" if "null" value exists in JSON as a result of GET /api/v1/rules

### ISSUE THREAD

**Issue by kakkotetsu** [grafana/grafana#67463]
## What happened:

Error on "Alert rules" if "null" value exists in JSON as a result of `GET /api/v1/rules`.

For example, an error occurs when the following response is returned.  
I use Prometheus compatible VictoriaMetircs the data source.  
```json
{
  "status": "success",
  "data": {
    "groups": null
  }
}
```
```json
...
      {
        "name": "mds",
        "rules": null,
        "interval": 60,
        "lastEvaluation": "2023-04-28T03:12:17.320533579Z",
        "type": "prometheus",
        "id": "5324614860393267221",
        "file": "/etc/alerts/alert.rules.ceph.yml",
        "concurrency": 1
      },
...
```

Prometheus with the same alert settings will have empty data as follows, so no error occurs in Grafana.
```json
...
      {
        "name": "mds",
        "file": "/etc/prometheus/alert.rules.ceph.yml",
        "rules": [],
        "interval": 15,
        "limit": 0,
        "evaluationTime": 3.665e-06,
        "lastEvaluation": "2023-04-28T03:12:11.913780266Z"
      }
...
```
RFC8259 allows null values and I would like Grafana to be able to handle this.

## What you expected to happen:

Grafana alerts can handle null values correctly.

## How to reproduce it (as minimally and precisely as possible):

1. install Grafana `9.5.1`
2. create Prometheus type data source. Anything that uses a null value on `GET /api/v1/rules`. (e.x. VictoriaMetrics `1.90.0` + vmalert `1.90.0`)
3. access Grafana's "Alert rules"

## Environment:
- Grafana version:  docker `grafana-oss:9.5.1` and  `grafana-oss:9.4.7`
- Data source type & version: VictoriaMetrics `1.90.0` + vmalert `1.90.0`
- OS Grafana is installed on: Ubuntu `22.04.1`
- User OS & Browser: Windows 10 + Chrome `Version 112.0.5615.138 (Official Build) (64-bit)`
- Grafana plugins: `vonage-status-panel`
- Others:

**Comment by kakkotetsu** [comment]
It's error example when a `GET /api/v1/rules` result containing a null value
![alert_rules_null_victoriametrics](https://user-images.githubusercontent.com/8026416/235063878-8186844d-1a9a-4ae4-9887-5ac0f6febabd.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @kakkotetsu 

> I use Prometheus compatible VictoriaMetircs the data source.

This repo does not cover the VictoriaMetrics Datasource plugin. That's a third-party offering ❤️
