### ISSUE TITLE
Duplicate alert happens when I use Integration Contact Point

### ISSUE THREAD

**Issue by yxStory** [grafana/grafana#67462]
## What happened:
Because of this issue: https://github.com/grafana/grafana/issues/67347
I create a new Integration Contact Point contains webex teams and pagerduty, I received duplicate alerts in team space.

## What you expected to happen:
I want to receive correct alert both in space and pagerduty.

## How to reproduce it (as minimally and precisely as possible):
1. create an Integration contact point adding cisco webex teams and pagerduty.  <img width="679" alt="Screenshot 2023-04-28 at 11 05 04" src="https://user-images.githubusercontent.com/26163471/235044771-588ed0d9-892a-4211-9123-e0af0a230d83.png">
2. I already created a 'cisco webex teams' contact point same as step1 before
3. create a new alert rule using step1's contact point, don't contains step2's label 
4. trigger the alert, check the alert in team space

## Anything else we need to know?:
How to send alerts to different place at the same time and also can get the correct alerts.

## Environment:
- Grafana version: 9.4.7
- Data source type & version: NA
- OS Grafana is installed on: centos8
- User OS & Browser: chrome
- Grafana plugins: NA
- Others: NA

**Comment by yxStory** [comment]
Received duplicate ale
<img width="482" alt="Screenshot 2023-04-28 at 13 19 52" src="https://user-images.githubusercontent.com/26163471/235060881-9649e198-42e1-409a-87e5-57c378054395.png">
rts

**Comment by yuri-tceretian** [comment]
Can you provide a screenshot or JSON of the notification policy you use?

**Comment by armandgrillet** [comment]
Closing as no answer for more than a month. Please reopen if you can provide more context.
