### ISSUE TITLE
SQL statement in request URL

### ISSUE THREAD

**Issue by viswa-devops947** [grafana/grafana#6746]
I am using Grafana version grafana-3.0.2  and Influxdb 1.0.0 on CentOS Linux release 7.1.1503.
when i ran burp suite i see SQL statement in request URL's.

is there anyway that i can stop this happening.

Request:
GET /api/datasources/proxy/1/query?db=mydb&q=SELECT%20value%20FROM%20%2F.cpu*%2F%20WHERE%20time%20%3E%20now()%20-

**Comment by torkelo** [comment]
this is not a SQL statement but metric request to InfluxDB. Grafana is data visualization tool, you build queries attached to panels, the queries are sent through grafana to the time series store (in your case InfluxDB)
