### ISSUE TITLE
Can't use alertmanager as a datasource in a dashboard.

### ISSUE THREAD

**Issue by mentholpopsicle** [grafana/grafana#67461]
## What happened:
I added alertmanager as a data source so I can use it in a dashboard but it doesn't show up as data source I can pick. I'm not sure if it's supposed to be this way since there are dashboards in the Grafana website.
<img width="877" alt="image" src="https://user-images.githubusercontent.com/127915079/235044114-2eb8b46e-97b8-4c7c-9976-76466f820ac3.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/127915079/235043882-5b911293-f259-41a1-89c1-22e57ef91e7e.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/127915079/235045096-f69ebdba-247a-4ea1-a064-d5055784320e.png">

## What you expected to happen:
I was expecting to be able to pick alertmanager as a datasource once I added it to grafana.
## How to reproduce it (as minimally and precisely as possible):
Add alertmanager as a datasource in grafana webgui. Create a new dashboard and new panel, open the data source dropdown for the panel.
## Environment:
- Grafana version: 9.4.7
- Data source type & version: Alertmanager ver. 0.25.0 
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Win11 , Google Chrome
- Grafana plugins: Default Plugins only
- Others:

**Comment by sebastianschauenburg** [comment]
@mentholpopsicle running into the same issue, and am wondering how this was fixed. Would you mind sharing? (I didn't see a committ or link to a fix, would be appreciated)

**Comment by darks00ul** [comment]
I have the same issue... is this a expected behavior?
I'm trying to use this [dashboard](https://grafana.com/grafana/dashboards/12947-open-alerts-of-alertmanager/) but I cannot use my alertmanager as datasource running Grafana v10.2.2

**Comment by nliakm** [comment]
You first have to install following alertmanager data source as a plugin to make the dashboard work: https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/
