### ISSUE TITLE
Azure monitor metrics split metrics based on dimensions but can't read dimensions name

### ISSUE THREAD

**Issue by lombardialess** [grafana/grafana#67473]
Azure monitor plugin don't show dimensions content values so all data on the graph are shown splitted but all with the same name

## What happened:
![image](https://user-images.githubusercontent.com/16349053/235089579-04e68068-9379-4765-b3b2-7549a12dfbac.png)

## What you expected to happen:

to see data splitted but with the dimension name, like was some time ago and like it is on Azure portal metrics

## How to reproduce it (as minimally and precisely as possible):
like the example in the image above or taking any metrics from a resource that have dimensions 

## Environment:
- Grafana version: 9.4.7
- Data source type & version: Azure monitor 1.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome
- Grafana plugins: zabbix
- Others:

**Comment by mellieA** [comment]
@lombardialess can you use the [Get Help](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/#send-a-panel-to-grafana-labs-support) option on the panel or dashboard to export a copy to share with us? With that option, you can choose to anonymize the data.

**Comment by lombardialess** [comment]
[GRAFANAISSUE.TXT](https://github.com/grafana/grafana/files/11381007/GRAFANAISSUE.TXT)
this is how I visualize
![image](https://user-images.githubusercontent.com/16349053/235874782-7d64d9ba-6aa4-4933-b2bf-fbced69071b4.png)
I found a way to fix it but was not like this before:
![image](https://user-images.githubusercontent.com/16349053/235875189-3b2d29e1-e762-4b53-a325-d2d841586a28.png)

**Comment by aangelisc** [comment]
This has been fixed in #67050 and the fix was released in 9.5.1. If you can upgrade and test you should be able to make use of the fix 😊 I'm going to close this issue but if it's still present in 9.5.1 please re-open!
