### ISSUE TITLE
Duplicate names inside Install Grafana pages "Redhat, RHEL, or Fedora"

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#67474]
Docs feedback: /docs/sources/setup-grafana/installation/_index.md

Inside the Install Grafana page.

There seems to a typo mistake with the page names as 2 pages says same i.e. "Redhat, RHEL, or Fedora"

![image](https://user-images.githubusercontent.com/69509548/235091879-8c2cb32e-150e-436d-ae7b-ccc6c4c41fcc.png)

However, the 1st page does tell about "Redhat, RHEL, or Fedora"

While the 2nd page should be renamed as Install Grafana on SUSE or OpenSUSE as also shown in the above screenshot

**Comment by chri2547** [comment]
Fixed in #https://github.com/grafana/grafana/pull/67511
