### ISSUE TITLE
Error Invite users - back button

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#67481]
## What happened:
When I pressed "Back"-button in Invite page is says "404 error page not found"
## What you expected to happen:
Getting back to Organisation Users-page
## How to reproduce it (as minimally and precisely as possible):
Press Invite, press back
## Anything else we need to know?:
I have only ONE Org.
## Environment:
- Grafana version: 9.5.1
- Data source type & version: InfluxDB 2.7.1
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows 11 Edge
- Grafana plugins: none
- Others: -
- 
![image](https://user-images.githubusercontent.com/21694965/235114735-73e305a2-3074-422f-9cdc-b96157ae2069.png)

**Comment by mellieA** [comment]
@flopp999 thanks for reporting this. I am able to reproduce this error on Edge, it works as expected on Chrome
