### ISSUE TITLE
[Bug] Slack notification doesn't come with snapshot

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#6748]
Please include this information:
- What Grafana version are you using?
v4.0 beta
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 6
- What did you do?
trigger an alert
- What was the expected result?
slack shall received notification with snapshot
- What happened instead?
slack received text only

[![Screen Shot 2016-11-29 at 3.07.03 PM.png](https://s15.postimg.org/5i342dgq3/Screen_Shot_2016_11_29_at_3_07_03_PM.png)](https://postimg.org/image/sjjp84gdj/)

**Comment by bergquist** [comment]
You need to configure an external image store to get snapshots of the panel in the slack notifications

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L413
