### ISSUE TITLE
Cannot add user to organization after update to 9.5

### ISSUE THREAD

**Issue by Igorgro** [grafana/grafana#67497]
## What happened:
I can no longer add users to organization. Our Grafana instance uses Keycloack OAuth authorization and due to this it is impossible to add user to organization. There is the following message on the user edit page: "This user's role is not editable because it is synchronized from your auth provider. Refer to the Grafana authentication docs for details.". In previous version could add users to organization by opening "Organization>Users" and clicking "invite" there, but in the 9.5 there is no such such button on none of three user screens (Users>All users, Users>Organization users and Organization > Organization users). The link from the message also doesn't provide any useful information

## What you expected to happen:
I can invite user to organization at least the same as I could do in previous version

## How to reproduce it (as minimally and precisely as possible):
1. Install Grafana 9.5
2. Enable Keycloack (or probably any other) OAuth authorization
3. Configure two ore more organizations and make one of them to be default for newly created users
4. Try to add user to non-default organization

## Anything else we need to know?:
Before some 8.x version it was also possible to manage user organizations directly on user edit page 

## Environment:
- Grafana version: 9.5.1
- Data source type & version: doesn't matter
- OS Grafana is installed on: Debian 11
- User OS & Browser: Google Chrome/Firefox
- Grafana plugins: -
- Others: -

**Comment by mellieA** [comment]
@Igorgro if you want to manually update a user's role outside of Oauth, you can use the setting [skip_org_role_sync ](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#skip-organization-role-sync)

Note: A user needs to have the server administrator (higher than admin) permission or organization administrator permission to invite users into another org.
