### ISSUE TITLE
Multidimensional Queries for an Alert do not work in Math Expression

### ISSUE THREAD

**Issue by neinkob15** [grafana/grafana#67496]
## What happened:
The Math Expression displays "No data" when combining two multi-dimensional Expressions in a alert-rule.
I am using Grafana 9.5.1 and the Graphite Datasource.

For example, I have this constellation:
Query A: returns the number of current connections of two firewalls
Query B: returns the current connection limit of the same two firewalls

Each firewall has a different number of current connections and also a different connection limit.

Expressions:
![image](https://user-images.githubusercontent.com/34396326/235141582-7fd9c35d-3433-4705-bbdd-6d0c146676ef.png)

Expression E and C reduce these two series by using the 'last'-function.

Now I want to trigger an alert, when C gets bigger than E (when the current connections number gets bigger than the limit). 
But unfortunately the Math Expression D does not work correctly. It simply shows "No data".

## What you expected to happen:
Instead I expected the Expression D to compare these two multi-dimensional expressions correctly and trigger a multi-dimensional alert respectively.

## How to reproduce it (as minimally and precisely as possible):
1. Have two series, each containing more than one series (multidimensional). 
2. Reduce both to only get the last values.
3. Try to use the reduced values in a math expression, f.e. by comparing them.

## Anything else we need to know?:

What surprisingly did work was: 
In Math Expression D: Comparing expression C with itself has a result (f.e. $C > $C), same by using only E with itself. 
Using a one-dimensional expression did work, so f.e. if queries A and B each only return one series (f.e. only firewall1), the math expression did work correctly

## Environment:
- Grafana Version: 9.5.1
- Data source type & version: Graphite Version 1.1.x
- OS Grafana is installed on: RHEL
- User OS & Browser: Windows/Chrome
- Grafana plugins: -
- Others: -

**Comment by yuri-tceretian** [comment]
The reason it does not work is that expression `C` has suffix "A" in labels, e.g. "name=firewall1 A" and `E` - suffix "B" (e.g.
name=firewall1 B`). When a math expression performs a `union` operation, it cannot find the intersection between those two sets and returns NoData. 

According to the code, those labels come from the plugin that wraps user queries with alias

https://github.com/grafana/grafana/blob/3abaf32cf26bc5dc4ecd54dd89c614cce6aebb83/pkg/tsdb/graphite/graphite.go#L229-L231

Handing over to the team that owns Graphite plugin.

**Comment by yuri-tceretian** [comment]
I think we can update the Graphite plugin to append suffixes only when there are multiple queries in a single request. This will work because in SSE DSNode is created per RefID and therefore plugin is called multiple times.

**Comment by bohandley** [comment]
Closing this as the solution in the escalation linked above was to provide a warning message. See link for more information. Thank you!

**Comment by bohandley** [comment]
Reopening this issue to track it for a customer.

There are two possible solutions for this.

One, add a transformation to rename labels before using the expression. I don't think this would work, though, if it requires alerting. 

Two, allow users to select labels to join on in the expressions union.

**Comment by kheisler-fetch** [comment]
We are on version 11.1.4 and this is still an issue. This issue prevents multi-dimensional alerts for graphite datasources. 

I see that they try to clean the added refId when they are processing the data
[grafana/pkg/tsdb/graphite/graphite.go](https://github.com/grafana/grafana/blob/3abaf32cf26bc5dc4ecd54dd89c614cce6aebb83/pkg/tsdb/graphite/graphite.go#L275-L279)

However the updated target name still shows up in the name label within the results
![Image](https://github.com/user-attachments/assets/471350c3-9dd5-442c-ae8b-a0ff49e19946)

Could this be addressed by simply adding the following at line 298?
`if name == "name" {
				value = target
			}`

[grafana/pkg/tsdb/graphite/graphite.go](https://github.com/grafana/grafana/blob/3abaf32cf26bc5dc4ecd54dd89c614cce6aebb83/pkg/tsdb/graphite/graphite.go#L296-L303)
