### ISSUE TITLE
[Bug] nil pointer dereference on my arm build of v4.0.0

### ISSUE THREAD

**Issue by fg2it** [grafana/grafana#6749]
I have this problem with v4.0.0 (but not with v4.0.0-beta2) on raspberry pi 2 (and 3). I build v4.0.0 from the repo inside a docker (go 1.7.3) without problem but at start (with default config) I have : 
```
INFO[11-30|00:37:15] Initializing Alerting                    logger=alerting.engine
INFO[11-30|00:37:15] Initializing CleanUpService              logger=cleanup
INFO[11-30|00:37:15] Initializing HTTP Server                 logger=server address=0.0.0.0:3000 protocol=http subUrl=
EROR[11-30|00:37:16] Scheduler Panic: stopping alertingTicker logger=alerting.engine error="runtime error: invalid memory address or nil pointer dereference" stack="[engine.go:54 asm_arm.s:429 panic.go:458 panic.go:62 sigpanic_unix.go:24 asm_linux_arm.s:109 64bit_arm.go:20 gauge.go:76 reader.go:62 engine.go:67 engine.go:42 errgroup.go:58]"
``` 
(I don't have for the official build for x64). 
Nevertheless, I can add datasource and dashboard.

I have the same problem if I try a crossbuild (for both armv6 and armv7) version.

edit : in fact, I don't have this problem with 2bdb2f79ec5b53ef155043b7137c44289ce4ef0c. So, checking [diff](https://github.com/grafana/grafana/compare/2bdb2f79ec5b53ef155043b7137c44289ce4ef0c...v4.0.0) beetween v4.0.0 and 2bdb2f79ec5b53ef155043b7137c44289ce4ef0c and due to the `reader.go:62` in my log, I would incriminate something related to the [change](https://github.com/grafana/grafana/compare/2bdb2f79ec5b53ef155043b7137c44289ce4ef0c...v4.0.0#diff-a0c357be167e15884cd1685a4b54be37R62) from `Inc` to `Update`  and the deeper [change](https://github.com/grafana/grafana/compare/2bdb2f79ec5b53ef155043b7137c44289ce4ef0c...v4.0.0#diff-7cbe8e056d62a2de30c7066e359bd9c9L108) in `M_Alerting_Active_Alerts`.

**Comment by bergquist** [comment]
Weird.... I cannot reproduce this behavior in my dev env. I wonder what differ for an ARM processor.

**Comment by fg2it** [comment]
The problem seems due to [`StandardGauge.Update()`](https://github.com/grafana/grafana/blob/v4.0.0/pkg/metrics/gauge.go#L75) itself. It uses `atomic.StoreInt64` and official [doc](https://golang.org/pkg/sync/atomic/#Value.Store) says

> Bugs
[...]
On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned. 

I don't see anything to take care of that, so I guess this is the point and can be expected to happen also on x86-32.

**Comment by fg2it** [comment]
@bergquist by the way, it should have been [obvious for you](https://github.com/grafana/grafana/commit/22407fc8974f89b34b71b697bb5411db30e05b25#diff-dd162f8cb80f8be506faa715ede438f8R32) 😉

**Comment by bergquist** [comment]
@fg2it haha yes ;) this will go into 4.0.1
