### ISSUE TITLE
MSSQL: Change encrypt default value to false

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#67492]
**What is the chore?**:

In the MSSQL data source config page the default value for the encrypt field is disabled but the tooltip and the docs says it is false. We should change the default value to false.

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/mssql/configuration/ConfigurationEditor.tsx#L189

**Is there anything else we need to know?**:

**Comment by tanishk-agarwal** [comment]
Can I please be assigned to this issue ?

**Comment by zoltanbedi** [comment]
here you go @tanishk-agarwal

**Comment by Shrillx** [comment]
Hey @zoltanbedi can I take this issue as well this is probably my first github issue, if you allow we can connect for this as well

**Comment by zoltanbedi** [comment]
Hey @Shrillx,
Thanks but @tanishk-agarwal already created a PR for this.

**Comment by zoltanbedi** [comment]
I'm open to accept another PR for this.

**Comment by Soham-glitch** [comment]
I would like to work on this issue. please assign this issue to me
