### ISSUE TITLE
[Bug] Bar width multiple series in different resolutions

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#6751]
After upgrading to the latest stable version of Grafana, v4.0.0, using the graphite data source,

Using a panel with multiple metric resolutions breaks the bar width rendering (causes all bar to render at the lowest width).

To recreate: 
Create graph panel with bars using either series override or the global option.

Add two metric series, one at an hourly interval and one at a minute interval.
Each series should be plotted with bar width that corresponds to the metric resolution, but instead both metrics are rendered at the lowest resolution.

Proper bar width:
![screenshot 40](https://cloud.githubusercontent.com/assets/11908736/20744641/21ef4942-b6ab-11e6-82b6-08b8d2fd5397.png)

Bar width with multiple series:
![screenshot 41](https://cloud.githubusercontent.com/assets/11908736/20744643/24e251d0-b6ab-11e6-93dd-389a78e560a9.png)

**Comment by benrubson** [comment]
Yes bar width calculation has been updated (in #6287) so that it is calculated according to the smallest interval, over all series.
As you can see in the code, previous behaviour was to take the interval of the first series only, which could also lead to strange results.

We could think about applying each bar series its own width, or at least calculating a shared bar width only using bar series (so excluding line series in your example).

**Comment by benrubson** [comment]
As a workaround perhaps you could ask all your series (on Grafana side of course) to use the same downsampling value ?

**Comment by linar-jether** [comment]
Thanks for the quick response!

Downsampling to the same resolution would not make much sense for us, for example, we're plotting the hourly trade volume along with a commodity's spot price.

Each bar series having its own width would be most convenient, but excluding the line series from the width calculation would also be good enough... (it may be a bit weird showing bars of different width for the same timestamp).

**Comment by benrubson** [comment]
> Downsampling to the same resolution would not make much sense for us, for example, we're plotting the hourly trade volume along with a commodity's spot price.

This would make the bars more visible in your graph, but for sure this would only be a temporary workaround.

> (it may be a bit weird showing bars of different width for the same timestamp).

Totally agree,

> (...) excluding the line series from the width calculation would also be good enough...

so seems to be the right way yes 👍

**Comment by benrubson** [comment]
Solved by #6756 👍

**Comment by benrubson** [comment]
@linar-jether issue should be solved in [4.1-beta1](https://github.com/grafana/grafana/releases/tag/v4.1.0-beta1) :)
