### ISSUE TITLE
[Bug] Template var groups/tags not working

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#6752]
Seems to be broken in latest stable version V4.0.0.

No matter what (clicking on update/change the refresh method/recreate the template), grafana doesn't execute the group/tags queries (Tested using the chrome developers console)

**Comment by lymichaels** [comment]
I'm seeing the same issue and I upgraded from 3.1.1

**Comment by lymichaels** [comment]
Anyone find a workaround or fix for this? It's still broken in 4.0.2

**Comment by linar-jether** [comment]
I think this is an important feature of grafana, as without it selecting multiple template variables from large lists is almost impossible

**Comment by tfylling** [comment]
useTags seems to not be stored in the json structure at all, probably meaning it will always evaluate as false.

**Comment by RomainBelorgey** [comment]
Got the same issue since upgrading on 4.0.1. 

Possible to force the useTags value ?

**Comment by directionless** [comment]
As I mentioned over in https://github.com/grafana/grafana/issues/6906
It's broken on the example http://play.grafana.org/dashboard/db/templating-value-groups It looks okay, but if you click anything the tags are gone.

**Comment by stevenh** [comment]
Confirmed this was broken here when we updated to 4 as well.
When entering the template editor most the time (not all) the experimental feature has been disabled

**Comment by miketwenty1** [comment]
+1

**Comment by trondvh** [comment]
+1

**Comment by Farfaday** [comment]
+1

**Comment by novegit** [comment]
+1

**Comment by VinceTT** [comment]
+1

**Comment by paloaltorickyrem** [comment]
+1

**Comment by Keleir** [comment]
+1

**Comment by wyzssw** [comment]
+1 broken in 4.6.3
