### ISSUE TITLE
Loki: Make query splitting generally available

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#67547]
This issue is to track rolling out query splitting to the widest possible audience, and clearing any blockers therein. Some notes [here](https://docs.google.com/document/d/1qm2k_O7MWTiIqAc-jNYAYDhaAd8r22XKY0XsFTnnE64/edit#heading=h.2567nn2d4qkf).

NOTE: we should also re-evaluate whether the custom-timeout-support for logs-volume-histogram is still needed, considering query-splitting should help a lot there. ( i mean the https://github.com/grafana/grafana/blob/fcb14d2548d68dadb981f24dd76489088dd232d7/docs/sources/explore/logs-integration.md#logs-visualization document, where it deals with the `X-Query-Tags` header)

**Comment by matyax** [comment]
Current consensus is to wait until we have an endpoint to get the correct or ideal value for the split duration (1 day, or more, or less), and then do GA.

**Comment by matyax** [comment]
Query splitting is GA.
