### ISSUE TITLE
Loki: Investigate how query splitting should work with end user query limits

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#67548]
Work with the Loki squad to figure out how end user limits should map to query splitting (e.g. 10G limit, 11G of data spread over 30d range).

**Comment by gabor** [comment]
(based on previous discussions).. it may be that it is enough to improve the info-messages.
so for example, we show the message "This query will process approximately 500GB.", and maybe, when we know it will be split, modify the text to  something like "This query will process approximately 500GB. (Note: the query will be split into multiple parts and executed progressively. Query limits will only apply to the parts"
