### ISSUE TITLE
[BUG] Snapshot does not preserve date range

### ISSUE THREAD

**Issue by stevenroose** [grafana/grafana#6755]
- What Grafana version are you using?
v4.0.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
The docker container (Debian I guess)
- What did you do?
Create a snapshot of a dashboard that contains a graph with a date range of 30 days.
- What was the expected result?
The graph in the snapshot also shows a range of 30 days.
- What happened instead?
The graph in the snapshot shows a range of ~2 days.

**Comment by stevenroose** [comment]
Any news on this. It still persists. Here is the bug in action:
https://gastracker.sanlab.io/dashboard/snapshot/YUWlXZZQLmp5bLciGVLmn1hyMbys0YVt

The graph on the bottom has a 30-day range configured, that is not preserved in the snapshot.

**Comment by daniellee** [comment]
Just to clarify, you mean that the snapshot contains 30 days of data but that the time picker is zoomed in to only show 2 days?

**Comment by stevenroose** [comment]
@daniellee. No, the original dashboard contains 30 days and has a view (zoom) of 30 days. The snapshot only shows 2 days.

I know you can click the graph and zoom out and them select all 30 days to have to show something reasonable, but it is called a "snapshot", it should show exactly what the dashboard shows, i.e. a 30-day graph.

**Comment by daniellee** [comment]
What I mean is that the snapshot contains all the data it should but that the zoom level is incorrect. Is that a correct description of the bug?

**Comment by stevenroose** [comment]
Exactly :)

**Comment by daniellee** [comment]
@stevenroose I cannot reproduce this locally. Do you see any errors in the Chrome dev tools console when you take the snapshot? Can you try taking a new snapshot and extending the timeout to 30 seconds or longer?

![image](https://cloud.githubusercontent.com/assets/434655/23716708/7b764d2a-0431-11e7-8e71-276d01a88844.png)

**Comment by stevenroose** [comment]
@daniellee It's been a while since I deployed that dashboard. I'll have to go take a look and probably update as well. It might be solved already.

**Comment by torkelo** [comment]
We could replicate it if we changed we closed the snapshot modal and changed dashboard time range during snapshot, then got the snapshot link via the snapshots page. 

Was this how you managed to do this?
