### ISSUE TITLE
Transformations: Convert Field Type: YYYY-MM-DD does not work

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#67550]
## What happened:
When using transformation to convert a field to time & format : YYYY-MM-DD it does not convert it
## What you expected to happen:
That the formatting works
## How to reproduce it (as minimally and precisely as possible):
![image](https://user-images.githubusercontent.com/900951/235213390-0fcbc12c-6d05-4f14-b333-ea2f68d67296.png)

## Environment:
- Grafana version: 9.5.1
- Data source type & version: github
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: github
- Others:

Thanks

**Comment by zuchka** [comment]
Hi @yosiasz 

> it does not convert it

I think this is a common misconception. Input format will not format the outputted value, but helps the parser recognize the timestamp that you input.

@grafana/observability-metrics might have more insight

**Comment by bohandley** [comment]
@grafana/observability-metrics here! That is correct, the input format will not format the outputted value to that input, but will read that format.

For example, the string "12-06-2010" can be converted to a date by entering the input format MM-DD-YYYY but does not output that date format in the table.
<img width="572" alt="Screenshot 2023-04-28 at 4 56 14 PM" src="https://user-images.githubusercontent.com/25674746/235253054-39fa135c-4f7e-45c2-98e3-7df340e05f2c.png">
<img width="761" alt="Screenshot 2023-04-28 at 4 57 59 PM" src="https://user-images.githubusercontent.com/25674746/235253082-235d4b3e-ab64-41f2-8613-d0b06ad88f83.png">

**Comment by yosiasz** [comment]
Ah got it!
What can one use to strip off the timestamp in order to be able to group by date 2023-04-28?

**Comment by bohandley** [comment]
@yosiasz Unfortunately we do not have a transform or expression that can format the date in that way, or even a value substring transform. I did see a transformation in the works that may be able to help you. @codeincarnate 
 is this something your WIP may be able to help? https://github.com/grafana/grafana/pull/67469
