### ISSUE TITLE
[Feature request] Limit graph to a time window on top of the time range

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#6757]
I'm not sure how to describe it in a single sentence, so the subject line sounds a bit ambiguous.

I currently graph the number of tickets we have in our queue. As the graph only changes during working hours, this doesn't deliver any interesting data outside the business hours.

Problem statement: I'd like to get an overview of how we did in the past week, so I select the past week, but this also displays outside business hours. I don't want to show the outside business hours.

I want to limit the graph to only show data generated in a time window (for ex. between 08:00 and 18:00) or to exclude data between a time window (18:00 till 08:00). This should work on top of the time ranges.

As a result, we can show the last week with only the data between 08:00 and 18:00 of every day in that week, and hiding/squeezing the data between 18:00 and 08:00.

Thanks for your time reading this, it is probably mostly a front end thing, so I have no clue on how much work this would generate.

**Comment by torkelo** [comment]
closing this as it's similiar to this issue https://github.com/grafana/grafana/issues/5930
