### ISSUE TITLE
Support adaptive widths for Content and Data textareas

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#67574]
**What**

It would be amazing if we could make the width of the Content and Data textareas adaptive so it fits on the same line in `1600x900`. We should also test `1920x1080` and `1366x768`.

Here with the menu expanded Data is pushed onto the next line:

<img width="1440" alt="Screenshot 2023-04-29 at 13 03 56" src="https://user-images.githubusercontent.com/85952834/235301746-6a84b9ab-7e02-41ef-b60a-74b093001fc2.png">

Here with the menu collapsed both textareas are on the same line:

<img width="1440" alt="Screenshot 2023-04-29 at 13 04 07" src="https://user-images.githubusercontent.com/85952834/235301748-ef912d39-c2d0-4101-9bcd-1a349d1575ee.png">

It would be awesome if we could make the textareas adaptive so both fit on the same line even with the menu expanded:

<img width="1440" alt="Screenshot 2023-04-29 at 13 03 56" src="https://user-images.githubusercontent.com/85952834/235301903-7639144e-e582-4473-b66f-b20c7280b104.png">

**Comment by iSatVeerSingh** [comment]
@grobinson-grafana @soniaAguilarPeiron Please take a look at my PR.

**Comment by soniaAguilarPeiron** [comment]
Hi @iSatVeerSingh , thank you for your contribution! we opened a [PR](https://github.com/grafana/grafana/pull/67967) where you will see that the idea is about filling all the available space with the editors depending on the screen width (adaptive). And we set at minimum width so the editors don't become too tight.
