### ISSUE TITLE
Change order of buttons below Data textarea

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#67575]
**What**

I think we should change the order of the buttons below the Data textarea to:

1. Make the reset button red and move it to the far right
2. Switch the order of "Choose alert instances" and "Add alert data"
3. Rename "Add alert data" to something like "Add custom alerts" so its more consistent that we are adding alerts

<img width="707" alt="Screenshot 2023-04-29 at 13 13 52" src="https://user-images.githubusercontent.com/85952834/235302196-a7cda0d3-c126-493a-a173-2e698dab7af7.png">

Here is an example of what I think it could look like:

<img width="673" alt="Screenshot 2023-04-29 at 13 18 27" src="https://user-images.githubusercontent.com/85952834/235302200-fff7ab03-0788-4e51-9817-a387bb63098e.png">

**Comment by brendamuir** [comment]
alerts is alert rules or instances?

**Comment by gillesdemey** [comment]
We're only working with "alert instances" in the template editor :)
