### ISSUE TITLE
Grafana 9.5 - unable to log in with JWT

### ISSUE THREAD

**Issue by vCra** [grafana/grafana#67582]
## What happened:

Post upgrade to Grafana 9.5, logging in with JWT auth fails.

Error in the browser:
`{"message":"Invalid JWT","traceID":""}`

Error in Server:
```
{"level":"debug","logger":"auth.jwt","msg":"Parsing JSON Web Token","t":"2023-04-30T13:08:10.075393909Z"}
{"error":"invalid character 'ÿ' looking for beginning of value","level":"debug","logger":"context","msg":"Failed to verify JWT","t":"2023-04-30T13:08:10.077344612Z"}
{"error":"invalid character 'ÿ' looking for beginning of value","level":"warn","logger":"context","msg":"Invalid JWT","t":"2023-04-30T13:08:10.077383595Z","traceID":""}
{"duration":"2.213017ms","level":"info","logger":"context","method":"GET","msg":"Request Completed","orgId":0,"path":"/","referer":"","remote_addr":"<ip>","size":39,"status":401,"t":"2023-04-30T13:08:10.077468631Z","time_ms":2,"uname":"","userId":0}
```

## What you expected to happen:

Logging in with JWT works as it does in v9.4

## How to reproduce it (as minimally and precisely as possible):

Setup Grafana 9.5 with the following JWT config

  auth.jwt:
    enabled: true
    header_name: Cf-Access-Jwt-Assertion
    auto_sign_up: true
    jwk_set_url: https://<org>.cloudflareaccess.com/cdn-cgi/access/certs
    cache_ttl: 60m
    username_claim: email
    email_claim: email

## Environment:
- Grafana version: 9.5.0/9.5.1

**Comment by rspier** [comment]
Also seeing this using Pomerium (https://www.pomerium.com/docs/guides/grafana)  (down to the same ÿ chracter)

```
logger=context t=2023-04-30T22:25:35.811568039Z level=warn msg="Invalid JWT" error="invalid character 'ÿ' looking for beginning of value" traceID=
```

**Comment by dm3ch** [comment]
Facing the same issue

**Comment by mgyongyosi** [comment]
@vCra @rspier @dm3ch Thank you for the report. We updated the go-jose package in 9.5.x to the latest, but I wouldn't expect any error because of this, because the error is probably coming from the `scanner.go` file and that file has not been changed since 2016.

The `ÿ` character is suspicious: that is the first character of the UTF-16 (LE) BOM decoded into UTF-8 (https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding), but it is very unlikely that the JWT was generated from an UTF-16 encoded octet stream..

Could you please provide a failing example access token that doesn't contain sensitive information?! Because I tried with Keycloack + oauth2-proxy and it seems to be working correctly.

**Comment by vCra** [comment]
Hey - I can provide a har with a minimal failing request? What's the best way of sending it securely?

**Comment by vCra** [comment]
Okay okay I think it's something to do with upgrading - I can't reproduce the issue on a fresh install of 9.5.1, but I can when upgrading fro 9.4 to 9.5

Using this config

```
[auth.jwt]
auto_sign_up = true
cache_ttl = 60m
email_claim = email
enabled = true
header_name = Cf-Access-Jwt-Assertion
jwk_set_url = https://<company>.cloudflareaccess.com/cdn-cgi/access/certs
url_login = true
username_claim = email
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.anonymous]
enabled = false
org_name = Company Name
[auth.basic]
enabled = true
[log]
mode = console
[log.console]
format = json
[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Editor
viewers_can_edit = false
```

Start current version of grafana - works as expected
docker run -p 3000:3000 -v grafana-storage:/var/lib/grafana -v ./grafana.ini:/etc/grafana/grafana.ini grafana/grafana:9.5.1
Start old version of grafana - also works as expected
docker run -p 3000:3000 -v grafana-storage:/var/lib/grafana -v ./grafana.ini:/etc/grafana/grafana.ini grafana/grafana:9.4.1
Revert to to 9.5.1
docker run -p 3000:3000 -v grafana-storage:/var/lib/grafana -v ./grafana.ini:/etc/grafana/grafana.ini grafana/grafana:9.5.1

Error appears

**Comment by mgyongyosi** [comment]
@vCra Thanks, it's strange! Unfortunately I cannot reproduce this issue based on the provided steps. Could you please verify that the JWT token is in the correct format following this: https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#verify-the-jwt-manually? 

Does it happens intermittently or constantly? Could you please try to login from an incognito window?

**Comment by vCra** [comment]
Yep jwt.io verifies the signature, so the JWT is correct here. 
I think I've figured it out. In cache_data, we store the cache key in the same format, but in 9.4, data begins with `0x20ff`, and in 9.5 the data begins with `{"keys": [{"kid": ...`
Looks like the format we store this in has changed, and 9.5 tries to read it in the old format and fails. Removing this cache key fixes the issue

**Comment by mgyongyosi** [comment]
@vCra Thanks, You are correct, I investigated this and the caching part changed in 9.5: https://github.com/grafana/grafana/pull/62930

So, removing the cache key would solve the issue for others too.

**Comment by rspier** [comment]
I confirm that deleting the `auth-jwt...` entry from cache_data solves the issue.

**Comment by mhr3** [comment]
> I confirm that deleting the `auth-jwt...` entry from cache_data solves the issue.

Sorry, how can we do that? Where is this cache_data stored?

**Comment by rspier** [comment]
> > I confirm that deleting the `auth-jwt...` entry from cache_data solves the issue.
> 
> Sorry, how can we do that? Where is this cache_data stored? (we're using grafana from docker hub)

For us, it's stored in a mysql table.  We're using helm to run, and the mysql is in the values.yaml under 

```
grafana.ini:
  database:
    url: ...
```

**Comment by mgyongyosi** [comment]
@mhr3 @rspier If you use "database" as the remote cache store (which is the default) then in the DB there is a `cache_data` table and you need to remove the record where the `cache_key` is like `auth-jwt:jwk-%`. For `memcached` and `redis` you need to find the same key and remove it.

**Comment by mhr3** [comment]
I'm sorry, but we use the default sqlite backend, and it's a massive pain to try to do any changes to it inside the container. Shouldn't grafana be able to deal with breakage in its own cache system instead of failing to load with an "Invalid JWT" error?

**Comment by alexmv** [comment]
This is still affecting anyone who upgrades from earlier than 9.5.0, and uses `jwk_set_url` in their configuration.

#62930 was missing some kind of migration to purge the cache of the old format.  And it's not too late to add one -- it would solve some upgrade headaches, at the extremely trivial cost of having to re-fetch the JWK.

Users of the default `sqlite3` storage backend can purge this manually via:
```
sqlite3 /var/lib/grafana/grafana.db "delete from cache_data where cache_key like 'auth-jwt:jwk-%'"
```

**Comment by sep2** [comment]
Sorry, this issue took me a whole day to debug in 2025. Please add a purge cache when the cached version is invalid.
