### ISSUE TITLE
Canvas: Showing "Field not found" when using influxDB or flux as data source

### ISSUE THREAD

**Issue by UdoRat** [grafana/grafana#67580]
## What happened:
After updating to 9.5.1 (I do ot remember what I had before, must be 9.4.x) all fileds show "Field not found" when using influxDB or flux as data source. In table view the values are shown.

Using Mysql as source everything works fine.

The value-based coloring still works:
![image](https://user-images.githubusercontent.com/35660000/235337141-28bef17b-0c20-4efe-8847-10b920b94528.png)

![image](https://user-images.githubusercontent.com/35660000/235337436-80609953-4234-4a00-89d3-2b41df9fdbc5.png)

## What you expected to happen:
The values are shown.

## How to reproduce it (as minimally and precisely as possible):
Create a Canvas dashboard using influxdb as source.

## Anything else we need to know?:
See https://github.com/grafana/grafana/discussions/56835#discussioncomment-5754578

I expect it is caused by this commit:
https://github.com/grafana/grafana/commit/a8adfe83b56798eb3842e8c2d72ccd33877e19f5

## Environment:
- Grafana version: 9.5.1
- Data source type & version: influxDB
- OS Grafana is installed on: Debian / Arm
- User OS & Browser: Chrome, Opera
- Grafana plugins: Canvas
- Others:

**Comment by multilectical** [comment]
Having the same issue. In my case, I can get the field value of only the first query if I select ```Value (base field name)```. Selecting ```Time``` also shows a value.

Also using influxdb as a db

In my case using Firefox on Ubuntu and grafana 9.5.1 on a raspberry pi / raspbian 11

**Comment by alexisantos** [comment]
The same behavior appears with zabbix datasource when adding more than two metrics, as link above.

**Comment by chi-miel** [comment]
Hello,

I'm testing canvas panel, it seems i have that same problem: "Field not found".

My datasource type is Prometheus and My Grafana is in v9.5.1 (bc353e4b2d).


![canvas_pb_prometheus](https://github.com/grafana/grafana/assets/12559914/e1c7d654-1efc-4bfb-84de-859a3e14fae2)

or not related ?

**Comment by UdoRat** [comment]
Succesfully tested with actual https://dl.grafana.com/oss/release/grafana_10.0.0~preview_armhf.deb
@adela-almasan Thany you very much.

**Comment by dima-lvs** [comment]
I can confirm the same issue. And grafana 10.2.0 works as expected! Thanks. Brilliant! 💎

**Comment by rwader-swi** [comment]
same issue, I'm using latest grafana and influxQL

**Comment by KasperKorsholmChristiansen** [comment]
Same issue I am using Grafana v10.2.2
