### ISSUE TITLE
[Bug] Connection leak with Prometheus in 4.0.0

### ISSUE THREAD

**Issue by pimeys** [grafana/grafana#6759]
Hi,

We found an issue today when updating from 4.0.0 beta2 to 4.0.0 stable. We use Prometheus as our data source and I have a dashboard with 22 functions run in Prometheus to render data. In 4.0.0 beta2 this took 2 connections to Prometheus and stayed there, the stable version takes 22 connections with every render of the page, causing a server crash when all the file descriptors are used.

We downgraded back to beta2 which seems to work fine.

**Comment by bergquist** [comment]
I think this is due to https://github.com/grafana/grafana/commit/56b7e2dfaf0a38161a7f62490505d2ba5a39d113#diff-2ce5b8fd7c5c41aeaf1e8b12a3163b80 Setting a new transport for every request could potentially sidestep the connection pool.

**Comment by thenayr** [comment]
Yes I encountered this very issue this morning

**Comment by samlabs821** [comment]
Same issue here, too much open files.

**Comment by sodabrew** [comment]
Is Grafana actively keeping the just-used-once connections alive, too?

In a way, this exposes a flaw in Prometheus that it failed to cut off client connections before becoming completely starved of filehandles. I have a three-hour hole in my data as a result of Prometheus going into a sort-of-wedged state rather than actually crashing or handling the situation gracefully.

**Comment by samlabs821** [comment]
this problem appeared after upgrading to grafana 4.0. 
lsof -i shows that connections not closing to prometheus

**Comment by warmfusion** [comment]
Would this also explain #6774 ?

We're seeing a simliar issue but with the ElasticSearch backend

**Comment by machytkafitanalytics** [comment]
we have the same problem with prometheus after upgrade to grafana 4.0

**Comment by pimeys** [comment]
We're using 4.0.0 beta2 here without trouble. It's easy to downgrade to that version and wait for this bug to be fixed.

**Comment by 7lives83** [comment]
same issue here.

**Comment by Raghu-Gurrala** [comment]
Same Issue Here with OpenTSDB as Datasource. 
After upgrading to Grafana v 4 stable. There is some kind of connection leak which is causing to hit openfile limit.

We have increased openfile limit from 1024 to 32764 to 100000

Still it reaches the openfile limit(ulimit) and makes opentsdb stall.

Attached is the openfiles monitoring graph on the server.
sudden drops is the time when restart of opentsdb happened.

Opentsdb and Grafana are both on same server in this case.

Specs: 8cores, 60gb memory.
![capture1](https://cloud.githubusercontent.com/assets/20206958/20800877/9dfcb98c-b7ac-11e6-95b7-cc3183a61163.JPG)

**Comment by bergquist** [comment]
If you encounter this problem we suggest that you rollback to beta2. We will release 4.0.1 with a fix for this shortly

**Comment by bergquist** [comment]
Should be available shortly
