### ISSUE TITLE
[Bug] CloudWatch plugin does not support brand new percentile metrics for ApplicationELB

### ISSUE THREAD

**Issue by jpfuentes2** [grafana/grafana#6762]
Firstly, thanks for the new 4.0 beta release. We're already on it, testing out alerts, and now we have ALB metrics! Unfortunately, grafana does not offer one of the most important *new* ALB metric: [percentiles of request latencies](https://aws.amazon.com/blogs/aws/amazon-cloudwatch-update-percentile-statistics-and-new-dashboard-widgets/).

Please include this information:
- What Grafana version are you using? 
4.0 beta
- What datasource are you using? 
CloudWatch
- What OS are you running grafana on?
 Linux
- What did you do?
Setup a graph using `TargetResponseTime`
![image](https://cloud.githubusercontent.com/assets/87429/20761151/0acb4c1c-b6f0-11e6-9295-301327e88fc8.png)

- What was the expected result?
I expected to see `pN.N` percentiles available as a stats per the AWS docs:
> TargetResponseTime	
The time elapsed, in seconds, after the request leaves the load balancer until a response from the target is received. This is equivalent to the target_processing_time field in the access logs.
>
> Statistics: The most useful statistics are Average and pNN.NN (percentiles).
- What happened instead?
No percentile stats available.

It looks like the `pN.N` percentile stats need to be added to the [CloudWatch UI here](https://github.com/grafana/grafana/blob/05d43999dc83c2adc5bda27eb8e41e0b762c35ea/public/app/plugins/datasource/cloudwatch/query_parameter_ctrl.js#L63-L72).

**Comment by jpfuentes2** [comment]
Looking further, found an open issue trying to implement this feature #6634.

**Comment by torkelo** [comment]
not sure this is a bug, more like a feature request?

**Comment by jpfuentes2** [comment]
Wasn't entirely sure what your project considers it. I could certainly label it as a feature request. Did you want me to do that? Are we closing so that it can just be handled in #6634?
