### ISSUE TITLE
Epic: Datagrid formatting

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#67629]
The new Datagrid panel should be capable of supporting various formatting options. The following issue list will address this:

- [ ] https://github.com/grafana/grafana/issues/67623
- [ ] https://github.com/grafana/grafana/issues/67620
- [ ] https://github.com/grafana/grafana/issues/67624

**Comment by supilee** [comment]
Note: This goal is depending on a storage solution. If there is no solution available in Q3, this item will be moved to Q4
