### ISSUE TITLE
Bug: Grafana removes LDAP users from custom organizations.

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#6764]
Please include this information:
- What Grafana version are you using?
Master (09e49f0)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
CentOS/7

- What did you do?
Configured grafana to use LDAP for user authentication & role mapping.
Logged in as an LDAP user.
Created new organization for which I became the sole admin.
Logged out.
Tried to log in.

- What was the expected result?
Success

- What happened instead?

    t=2016-11-30T12:13:28-0500 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="Cannot remove last organization admin"

- Additional information:
If I add another admin to the organization, then upon login grafana removes me from the org.
Also I am removed from all other organizations which I am not an admin.

Also grafana will update users roles if they don't match what the LDAP mapping says they should be.

In my opinion, Grafana shouldn't touch any changes to users/orgs/roles after the user has been imported from LDAP. Otherwise it's going to clash with manual changes.

**Comment by torkelo** [comment]
This is sadly how the LDAP integration works. you need to specify User orgs and org roles in the ldap mapping file. Not idea, but how it works now. Will likely revamp the LDAP integration sometime next year.

**Comment by bortek** [comment]
@torkelo Any planer to revamp this this year or early next year ? It would be really good to have this working.
