### ISSUE TITLE
[Bug]Multiple Metric Queries for InfluxDB break for $interval

### ISSUE THREAD

**Issue by zezuladp** [grafana/grafana#6765]
Grafana 4.0.0
InfluxDB datasource
Ubuntu 14.04 OS for Grafana
Multiple metric queries for a graph breaks the syntax of the query for at least the second query (possibly all after the first.)
if interval is set to >10m in the UI (per the suggestions):
The `GROUP BY time($interval)` for the first query becomes
`GROUP BY time(10m)` But the second query becomes:
`GROUP BY time(>10m)` This gives a error parsing the query:
`ERR: error parsing query: found >, expected identifier, string, number, bool at line 1, char 156`

My guess is that the interval string is not being formatted correctly when input into multiple queries.

My workaround: remove `$interval` and manually input it.

**Comment by torkelo** [comment]
unable to replicate this:

http://play.grafana.org/dashboard/db/influxdb-templated-queries-copy?panelId=1&fullscreen&edit

Are you sure you specified `>10m` in the group by time field below your queries?

**Comment by zezuladp** [comment]
Here's a screen shot:
![screen shot 2016-12-01 at 10](https://cloud.githubusercontent.com/assets/5467520/20806752/f94b1082-b7b0-11e6-9456-01e0c27609e4.png)

The request from the inspector:
`SELECT count("status") FROM "<measurement>" WHERE "status" =~ /2\d\d/ AND time > 1480579200s and time < now() GROUP BY time(10m) fill(null);SELECT count("status") FROM "<measurement>" WHERE "status" =~ /[45]\d\d/ AND "status" != "404" AND time > 1480579200s and time < now() GROUP BY time(>10m) fill(null)`

Note the `>10m` in the second `GROUP BY` clause.

And the inspector response:
`{
  "error": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 302",
  "message": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 302"
}`

This didn't happen initially. Maybe something else triggered this bug?

**Comment by jgerschk** [comment]
I'm going to add something to this.  I have this issues as well, and I can consistently reproduce the issue, but ONLY when using ALERTING tab.

If you don't create an alert, the bug does not seem to happen.  

As with @zezuladp that is how my query looks like, the group by time( always has >xx mean always has a greater than sign which makes InfluxDB toss the error.

**Comment by milesich** [comment]
I have the same problem and deleting alert did not help.

**Comment by torkelo** [comment]
This is strange, unable to replicate this: 

Here is 2 query pane with `>10m` group by time  (and an alert defined)
http://play.grafana.org/dashboard/db/influxdb-group-by-time?panelId=1&fullscreen&edit

**Comment by jgerschk** [comment]
What version of InfluxDB are people using, if there is that difference.  I have not been able to reproduce it on play.grafana.org either.

I'm going to try and come up with a good step by step use case here to see if we can't nail this down.

@milesich Just deleting the alert is not, you need to a) modify the $interval in the query, or remove the group by time setting so that it has nothing, and thing should start working again with/without the alert.

As for version of influxdb, me, I'm 1.1.0.

**Comment by jgerschk** [comment]
Hmmm... this is the start of it breaking on play...

![image](https://cloud.githubusercontent.com/assets/7864285/20854339/a78256f8-b8b8-11e6-8e5c-7a5e5e53518e.png)


See that error on the bottom...

400 bad request.

Once you get into that state, save the dashboard, reload it, things really go down hill from there.

**Comment by gkoh** [comment]
I have just run into this with my setup:
Grafana 4.0.1
InfluxDB 1.1.0

The same error response is given where it appears the "Group by time interval" is pasted directly into the 'GROUP BY time()' clause.

In my case, I had the following:
 - single series
 - single alert configured

I had to have the alert **active** to have it break, after which it needed to be completed deleted and reconfigured to fix.
I also had to save the dashboard, something I cannot do on play.grafana.org.
Although, I am also seeing the '400 bad request' on play.grafana.org that @jgerschk noted.

**Comment by stephanstapel** [comment]
I can confirm this parsing error bug with Grafana 4.1.1 and InfluxDB 1.1.0. Is there anything I could do to help tracking this down?

**Comment by bergquist** [comment]
@stephanstapel please try our latest build from http://grafana.org/builds/

We fixed a bunch of issues for influxdb queries in alerting in master.

**Comment by stephanstapel** [comment]
@bergquist sorry to ask but is it possible that you share a Windows build?

**Comment by bergquist** [comment]
@stephanstapel sure! You can use this link to download it https://grafanarel.s3.amazonaws.com/builds/grafana-4.2.0-pre1.windows-x64.zip

**Comment by stephanstapel** [comment]
Still working fine. Looks you have fixed it!

**Comment by torkelo** [comment]
great
