### ISSUE TITLE
Function `Last` in `Reduce` expression behaves like Last non-null value instead of Last value

### ISSUE THREAD

**Issue by Hronom** [grafana/grafana#67665]
### 
# What went wrong?

**What happened**:

I'm trying to setup Grafana alert for this query:
```
100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m])) * 100)
```

Function `Last` in `Reduce` expression behaves like `Last`(Last non-null value) instead of `Last`(Last value).

This makes `Mode` not usable as value always returned "non-null". 

This is critical for the alerts as you need to drop series that don't have data anymore as instance de-provisioned.
During provisioning/de-provisioning it can have high usage of CPU.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/429993/235699431-85bf78fe-dc25-4ef2-b25c-987be2540280.png)

**What did you expect to happen**:

Expected to have behavior of `Last`(Last value). 
Same as two variants of last for Legend in dashboard:
![image](https://user-images.githubusercontent.com/429993/235709890-cd716e13-a666-4708-9a95-ade87a8b13e6.png)

So if `Last`(Last value) will return null and `Mode - Drop Non-numeric Values` will drop value, so spike during de-provisioning not run longer then expected.

### 
# How do we reproduce it?

Try to setup alert for metrics gathered by node-exporter.

And setup Grafana alert for this query:
```
100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m])) * 100)
```

Set query time range `now-15m to now`.

Set `Alert evaluation behavior` to 5m and set some threshold, for example `80%`. And evaluate every `5s`.
You can use set of `expression` from my first screenshot.

Send data for `node_cpu_seconds_total` above threshold 80% for some instance and then stop send data to simulate that it starts to return null(e.g. instance deprovisioned).

After several minutes of not having data alert will still `fire` as `Last` will return "last successful value" instead of "real last value" which is null.

### 
# What Grafana version are you using?

Grafana v9.5.1 (bc353e4b2d)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

**Comment by Hronom** [comment]
Updated section `How do we reproduce it?`

**Comment by yuri-tceretian** [comment]
Hi @Hronom, 

>Function Last in Reduce expression behaves like Last(Last non-null value) instead of Last(Last value).
> This makes Mode not usable as value always returned "non-null".

In the screenshot, I see that Reduce is in mode `Drop Non-Numeric Values`, which means that _before_ reduction the input series will be filtered and only numbers will be used in Reduce operation. 
For example, a series of points `1,null,0,1,2,3,null,null` will be converted to `1,0,1,2,3` and then a reduction operation will be applied to this collection.
`Strict` mode does not filter the input series and takes the last point, which is `null` in the example. Can you try to use that mode and see if it works for you?

**Comment by Hronom** [comment]
@yuri-tceretian you not get my problem correctly.
Related to this:
```
For example, a series of points 1,null,0,1,2,3,null,null will be converted to 1,0,1,2,3 and then a reduction operation will be applied to this collection.
```
Issue here that before Reduce applying mode - it get series of points from somewhere, right?
In my case I use Function `Last`, my expectation that I will get from `Last` function next series of points `1,null,0,1,2,3,null,null`(in legend for example this function called `Last` instead of `Last *`) and on top of it will apply selected mode as you described.

But instead of this expected behavior I got series `1,0,1,2,3` where function `Last` return "Last non-null value" which cannot contain null's.

In order to understand, I would recommend to check description of two functions for dashboards legend:
![image](https://user-images.githubusercontent.com/429993/236689163-751df528-4ab9-4aa5-b05b-9ebda3f98c87.png)
As you can see there two variants of functions:
1. `Last *` - Last non-null value
2. `Last` - Last value

Unfortunately Reduce function use `Last *`(Last non-null value) from first variant, which makes modes useless. 
Expectation to use second variant e.g. `Last` - Last value.

Does it make sense now?

**Comment by yuri-tceretian** [comment]
The Prometheus data source does not fill the response with `null` values for missing points in the requested interval, and therefore Reduce operation in alerting, operates in a mode that looks like `Drop Non-Numerical Values` even if mode is `Strict`.

Basically, in the screenshot above the highlighted point is the only point for that metric\dimension in the selected interval.

As a workaround we can use Resample operation that will fill the gaps with NaN and then reduce in mode `Replace Non-Numeric Values` because NaN will be considered as Alerting state.

![image](https://user-images.githubusercontent.com/25988953/236929445-44490f9d-1d34-4b39-9509-c6c4806cdb1c.png)

However, I would also recommend take a different approach to the creation of the rule and use `instant` query type. 


Using irate's, rule evaluation, and `for` intervals you can achieve what you need and at the same time significantly reduce cost of the query. 


@grafana/observability-metrics I wonder if it is possible to let the user control 
do you know if there is anything we can recom

**Comment by yuri-tceretian** [comment]
sorry, accidentally closed issue

**Comment by Hronom** [comment]
Also there some nuance related to usability when you use alert with type `instant`. Especially when it send alert to slack.

When you click on slack link it will navigate you to the alert in grafana UI, but compared to the type `range` you will not see histogram that will show where query hit the barrier.

Because with `instant` you need to use something like this:
```
  sum(rate(istio_requests_total{destination_service=~"service-a.services.svc.cluster.local",
  reporter="destination", response_code=~"4.*"}[$__rate_interval])) /
  sum(rate(istio_requests_total{destination_service=~"service-a.services.svc.cluster.local",
  reporter="destination"}[$__rate_interval])) * 100 > 70
```
it's basically embeds the threshold to the query.

Comparing to the approach that I described in ticket where you see histogram and you also see redline(barieri) that it needs to bridge.

**Comment by leeoniya** [comment]
we're currently figuring out what to do here. possibly adding an option to the Join transformer to fill with `null` vs filling with `undefined` as it does now.

**Comment by torkelo** [comment]
Hm... feels like a problem with the Prometheus query mechanics, it is not returning any more values so Last is showing the last value correctly 

@Hronom 
> it's basically embeds the threshold to the query

This is the best practice way to write Prometheus alerts, using instant queries

**Comment by Hronom** [comment]
It's more UX(skipping all technical nuances). Having histogram and red line barrier is a way better for a user when it get alerts VS info that you get with instant type(again skipping tech nuances and related recommendations).
