### ISSUE TITLE
[Feat Req]: InfluxDB - Lock metric editor mode

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#6767]
Using Grafana 3.1 with InfluxDB 1.1...

To provide for capabilities beyond that of the standard UI, it is possible to "switch editor mode".

Unfortunately this can have an undesired side effect: when going from "raw" to "cooked", details can be lost. A good example of a lost detail would be changing a regex from /^$varname$/ to /^$varname.*$/. To avoid this happening by accident, it would be useful to "Lock" the editor mode.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
