### ISSUE TITLE
Datagrid: Bug Bash - '+' column is being highlighted when hovering from previous colum to "+" column

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#67689]
When hovering from the last column to the "+" column, both column headers are being highlighted.

Steps to reproduce:
1. load a datagrid
2. hover over the last colum
3. hover over the "+" column

Expected Result:
I expected that only the "+" column header is being highlighted

Actual Result:
Both, the last and "+", column headers are being highlighted (see video)

Grafana Version: v10.0.0-55187pre (https://github.com/grafana/grafana/commit/ea536411f1100cf2f70034aeb5c00f4b4a49af97)
Chrome Version: 112.0.5615.137 (Official Build) (arm64)
macOS: 13.3.1 (22E261)

https://user-images.githubusercontent.com/110845248/235786998-8d73887a-fd28-4844-ab2c-8e8187ce92ec.mov

**Comment by mdvictor** [comment]
I think this might be an upstream issue, as per the library examples here:

https://user-images.githubusercontent.com/36818606/235890165-313102ff-100f-4ab0-991c-b4081899ccee.mov

Will look into opening an issue about this
