### ISSUE TITLE
Metric query CloudWatch AWS/Lamb "!=" create Other in Alert, and alert does not work

### ISSUE THREAD

**Issue by memberA** [grafana/grafana#67694]
### 
# What went wrong?

**What happened**:
![image](https://user-images.githubusercontent.com/91407250/235840217-43699649-2a88-430f-9382-80096147084f.png)

### 
# How do we reproduce it?

I have two Lambda

![image](https://user-images.githubusercontent.com/91407250/235840069-d901ff92-13e7-4703-80d4-36f8596d0166.png)

I want to create an Alert without "us-east-1.TF-PROD-Frontend-Sign-S3-Request", but it generates for me "Other" FunctionName, and Alert does not work 

![image](https://user-images.githubusercontent.com/91407250/235840204-b9f42524-6529-42df-aa7d-f358abac2b27.png)

If i set "=", then it's even more interesting

![image](https://user-images.githubusercontent.com/91407250/235840462-8fc41004-987d-4131-bb62-a869c48604e3.png)

### 
# What Grafana version are you using?

Grafana v9.4.7, v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by memberA** [comment]
> hi @memberA
> 
> thanks for creating this issue
> 
> are you able to create an alert using different operators and/or expressions (part B in the rule condition) ?

hi, what do you want to check exactly?

in Metric Query with `=` I see a double result:
![image](https://user-images.githubusercontent.com/91407250/236772426-4a3decb1-1336-4a68-80e3-899f04184132.png)
![image](https://user-images.githubusercontent.com/91407250/236772486-e2c1b092-1cd6-44ea-9b02-bc6eaa73da53.png)
![image](https://user-images.githubusercontent.com/91407250/236772753-c2da1eb2-5718-4e0d-98f2-5adc56b3585c.png)
![image](https://user-images.githubusercontent.com/91407250/236772808-b3d0aff8-dfd7-4604-9029-6b9845c77161.png)

if I want to see both at the same time it shows nothing
![image](https://user-images.githubusercontent.com/91407250/236773092-b5b331d9-6c04-4c6d-bd0f-2c3e01eaef72.png)

here I have 15 lambdas. if I don't want to see one or several of them using `!=`, is created `Other ` and I still see them in the alerts
![image](https://user-images.githubusercontent.com/91407250/236775122-92431680-d2fd-4451-8213-3e7f45592065.png)
![image](https://user-images.githubusercontent.com/91407250/236775197-f6c24ce5-b576-42ee-918f-fa93974f7582.png)
![image](https://user-images.githubusercontent.com/91407250/236776107-0574ef1d-ac83-4028-81d6-78f8f929b951.png)

**Comment by tonypowa** [comment]
thanks for the info @memberA 

let's wait to hear the input from the Alerting / AWS db team

**Comment by memberA** [comment]
Hi, @kevinwcyu 
everything works `With schema`, except for the case where two or more `=` values are selected
![image](https://github.com/grafana/grafana/assets/91407250/350b28b9-aed0-4f12-901d-67018793e6b0)
these work fine:
![image](https://github.com/grafana/grafana/assets/91407250/06c61dc6-fa72-40a8-9a09-bc18f855d1f2)
![image](https://github.com/grafana/grafana/assets/91407250/08247238-99ae-40f9-ba4f-ec524e233e97)
![image](https://github.com/grafana/grafana/assets/91407250/d911f72a-4406-4ae0-b3d8-68ebb6360e08)

**Comment by kevinwcyu** [comment]
> Hi, @kevinwcyu everything works `With schema`, except for the case where two or more `=` values are selected ![image](https://user-images.githubusercontent.com/91407250/237287985-350b28b9-aed0-4f12-901d-67018793e6b0.png)

Hi @memberA, the query you posted with two `=` filters is working as intended. 

In the `WHERE`clause of generated query `... WHERE FunctionName = 'TF-prod-submission-report-processCentre" AND FunctionName = 'TF-prod-email-notification-emailSendingHandler' ...` it's filtering with an `AND` on the `FunctionName` so there wouldn't be any matches since the `FunctionName` can be two things at once. For further details, see the AWS docs section on the "Supported operators" here https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-querylanguage.html. They only support `AND` in the `WHERE` clause, so you'll likely have to have separate queries for each of the `FunctionName`s

**Comment by memberA** [comment]
Hi @kevinwcyu, thank you very much for the explanation
