### ISSUE TITLE
[Bug] PhantomRenderer::renderToPng renders image of login screen when using enforce_domain true

### ISSUE THREAD

**Issue by sleepinggenius2** [grafana/grafana#6769]
- What Grafana version are you using? Grafana v4.0.0 (commit: v4.0.0)
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubuntu 14.04
- What did you do? Clicked "Direct link rendered image" to share panel
- What was the expected result? Image of graph panel
- What happened instead? Got an image of the login screen

Related config:
```
# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = example.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true
```

**Comment by fsidnenko** [comment]
I have got the same bug. By disabling enforce_domain does not fix the problem.

**Comment by fdelapena** [comment]
This also happens to me with `enforce_domain = false` and with `http_addr = 127.0.0.1`

**Comment by milesich** [comment]
This works for me `;http_addr = 127.0.0.1` and `;enforce_domain = false`

**Comment by torkelo** [comment]
fixed!
