### ISSUE TITLE
TiDB instead of MySQL: ON condition doesn't support subqueries

### ISSUE THREAD

**Issue by krzd7** [grafana/grafana#67692]
### 
# What went wrong?

**What happened**:

  - I've tried to setup grafana with TiDB instead of MySQL as the backend database. It seems to be working fine, except for the admin/users page that is unable to list users because TiDB returns:
  `msg="Failed to fetch users" error="Error 1105: ON condition doesn't support subqueries yet"`

  - The "Organization users" tab works. It fails for "All users" only.

**What did you expect to happen**:

  - I understand that TiDB is not supported and this is not really a Grafana issue. Just wondering if that subquery can be rewritten or if it is really necessary, because it seems to work as a MySQL replacement.

### 
# How do we reproduce it?

Setup Grafana to use a TiDB server and go to the admin/users page.

### 
# What Grafana version are you using?

9.5.1

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by tonypowa** [comment]
Hello @krzd7 

Thank you for creating this issue

This topic has been already brought up, (see https://github.com/grafana/grafana/issues/12058)

You are welcome to start a new conversation around using TiDB in GitHub[ discussions](https://github.com/grafana/grafana/discussions).

**Comment by krzd7** [comment]
Hello @tonypowa ,

Thanks for your response. 

I've checked the issue you mentioned, but they are talking about grafana upgrades and schema changes. The issue I've opened is about a single query that uses "ON condition subquery" and it would be great if someone could take a look and see if it can be rewritten in order for it to work with TiDB.
