### ISSUE TITLE
Dashboard: Data links on a table is wrongly encoded

### ISSUE THREAD

**Issue by sebv7** [grafana/grafana#67701]
### 
# What went wrong?

**What happened**:

  - Since Grafana v9.5.0 the data links on a table is seems wrongly encoded or templated. 
  - The URL ist taken from a Query and refered to in "Data links" wither ${__data.fields.url}
  - In the table cell the URL is correctly shown: https://mysecondurl.corp.com/ui
  - If click on the table and want to open the link a 404 page is displayed. The URL seems strange:
    https://grafana.corp.com/https%3A%2F%2Fmysecondurl.corp.com%2Fui

**What did you expect to happen**:

  - I expect that the new tab opens "https://mysecondurl.corp.com/ui/" if I click on the table cell

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create a table with an URL.

**Step 2**:

- Configure a data link which referes to the cell with the url in it.
- Also configure to open the url in a new tab

**Step 3**:

- Save the dashboard

**Step 4**:

- Click on the table row to open the url

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Windows 10 22H2

### Is this a Regression?

None

### Are Datasources involved?

JSON API

**Comment by torbenaa** [comment]
Same problem here. Upgrading to 9.5.1 broke the link

**Comment by evictorero** [comment]
@juanicabanas can you confirm [this PR](https://github.com/grafana/grafana/pull/67291) fixes this issue and would be on `9.5.2`?

**Comment by tonypowa** [comment]
closing issue since there is a fix in place
feel free to reopen if the issue persists
