### ISSUE TITLE
Elasticsearch: switch metadata-lookup from `_mapping` to `_field_caps`

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#67704]
to find info about what fields exist in the given elastic index, we use the [_mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) API endpoint.
unfortunately this does not work when you have remote indexes. (when you use cross-cluster-search).

we should switch to a different API, [_field_caps](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html), which works even for remote indexes.

this is an often-requested feature ( https://github.com/grafana/grafana/discussions/56259 )

we can make a call like `_field_caps?fields=*` to get info about all fields. we will have to filter out metadata-fields based on the `metadata_field` boolean variable in the response. alternatively, we can just make the call like `_field_caps?fields=*&filters=-metadata` to only get what we want.

NOTE: based on some quick testing, this endpoint only produces usable info (to be able to decide between metadata/not-metadata fields) starting with elastic `7.13.0`.

we should make sure this new API endpoint provides all the info we need.

**Comment by cpmoore** [comment]
Any idea if this is planned? We have a large number of indexes and the _mapping api is very slow.  The _field_caps provides better response time

**Comment by idastambuk** [comment]
Closing this in favour of https://github.com/grafana/grafana/issues/72353
Will link this there too
