### ISSUE TITLE
depricated github.com/golang/protobuf package present in latest grafana

### ISSUE THREAD

**Issue by ahrycej** [grafana/grafana#67713]
### 
# What went wrong?

**What happened**:
depricated code present
[  - ](https://github.com/golang/protobuf)

**What did you expect to happen**:
to replace github/golang/protobuf with google code
  - 

### 
# How do we reproduce it?

**Step 1**:

Verify versions of protobuf present

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by papagian** [comment]
can you point me where `github.com/golang/protobuf` is used?
I don't see any reference of it in [go.mod](https://github.com/grafana/grafana/blob/v9.5.1/go.mod)

**Comment by ahrycej** [comment]
our security test tool (Anchore Enterprise) detects it in:
/usr/share/grafana/bin/grafana

**Comment by tolzhabayev** [comment]
Thank you @ahrycej for bringing this up, we will add it to our backlog. 
Since it's just a deprecation, not a security vulnerability it will be a low priority for us but if we work on the code in this area we will consider migrating away from the deprecated package.

**Comment by ahrycej** [comment]
by updating proactively you can avoid potential hassle in case the critical or high CVE will be reported

**Comment by ahrycej** [comment]
@tolzhabayev would yu have any (good) news for this item?

**Comment by ahrycej** [comment]
any update to this issue? grafana 10.2.2 stil have depricated golang protobuf, there were no new tags since v1.5.3
