### ISSUE TITLE
[bug?]Templating failed in Graph's Y-axe Label

### ISSUE THREAD

**Issue by berlinsaint** [grafana/grafana#6771]
i want to create an dynamic templating , the doc say that you can use the variable throughout the Dashboard.
i creat an custom var, in the graph's general option , i use $Title in the title input, and it is rendered success with my custom value. But in axes option , when i use the $YLNAME (which i have already defined) in the  lefty Lable input , the graph dose not work right. it doesnt renderd my custom value .
is there something wrong with my method ?
add a comment . my grafana version is 4.0.0

**Comment by berlinsaint** [comment]
add a comment . my grafana version is 4.0.0

**Comment by torkelo** [comment]
This feature has not been implemented yet. Closing as there is already a feature request for this, https://github.com/grafana/grafana/issues/5652
