### ISSUE TITLE
[Feat Req] Support paging in user HTTP api 

### ISSUE THREAD

**Issue by grantzhanghao** [grafana/grafana#6772]
1. We can only get first 1000 users, how can we get all users once？
2. Is there a method to get the user by user name, or check if it is already exist by user name?

request: localhost:3000/api/users
version: 3.1.1

![capture](https://cloud.githubusercontent.com/assets/18324433/20779668/e07a4d98-b7b0-11e6-9879-d76e5f56ccc7.PNG)

**Comment by daniellee** [comment]
This has been implemented: https://grafana.com/docs/grafana/latest/http_api/user/#search-users-with-paging
