### ISSUE TITLE
[Bug] "chown: invalid user" error when grafana service is started

### ISSUE THREAD

**Issue by veerareddyganta** [grafana/grafana#6773]
- Grafana version - 3.1.1
- Datasource - Influxdb
- OS - Linux 2.6.32-642.1.1.el6.centos.plus.x86_64 #1 SMP Wed Jun 1 03:11:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- What did you do? - I tried to restart grafana service after making the following changes to grafana.ini.
```
   enabled = true
   org_role = Admin

```
- What was the expected result? - Grafana service should be started with out errors.
- What happened instead?

I am getting the following error when I start grafana-server.

```
$  sudo service grafana-server start
Starting Grafana Server: .... chown: invalid user: `grafana:grafana'
chown: invalid user: `grafana:grafana'
OK

```

I started using grafana for the last 1 week and I never go this error before.  The only I change I can think of in my PC is "go" is installed yesterday to export grafana dashboard to pdf.

**Comment by veerareddyganta** [comment]
Found the root cause.  Grafana user got deleted after unix admin refreshed user list on our machines.  This caused the problem.  After adding grafana user,grafana group and linking it to corresponding pids, issue got resolved.

Is there anyway to start grafana-server process as the logged-in user instead of grafana user?

**Comment by torkelo** [comment]
yes, look at the init.d script / systemd service file to see how to start grafana server
