### ISSUE TITLE
Explore: Create design doc for query auto-run

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#67745]
Create a design doc explaining the issues around standardization when queries run, including possible alternatives.

It will be a long form version of the following comment:
https://github.com/grafana/grafana/issues/51979#issuecomment-1531387539

**Comment by gelicia** [comment]
Worked with @codeincarnate 's previous design doc https://docs.google.com/document/d/1G62nVl3PNoot3mH9Ir74fLFzCKMftkd52dFATQsSxUo/edit#

**Comment by Elfo404** [comment]
We need to investigate whether is it possible to "trap" `shift+enter` to run queries

**Comment by ifrost** [comment]
Related issue and PR that tried to implement global shift+enter handler: https://github.com/grafana/grafana/pull/37386#issuecomment-900141735. One of the problems was that query editors debounce onQueryChange and in some cases using the global shortcut lead to running the query before it's updated. There was also a problem with running a query twice (though this would be mitigated if plugins are not allowed to call onRunQuery). There was some problems to make it work in Explore and Dashboards.

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
