### ISSUE TITLE
NestedFolders: Checkboxes not shown for child folders

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#67741]
steps to reproduce:
- go to `Dashboards`
- click the text of a folder to go to the view of just that folder
- observe no checkboxes due to some bug in our permissions logic:
![image](https://user-images.githubusercontent.com/20999846/235959006-12a2d810-63a6-49f4-ac4c-33604053bac4.png)

**Comment by joshhunt** [comment]
Cause for this is the API not returning the `accessControl` metadata in the GetFolder response, which is what is tested to judge permissions for folder

https://github.com/grafana/grafana/blob/2ecc1802e7397a23c4f42f93837a88d74f22e260/public/app/core/services/context_srv.ts#L133-L141

Swagger spec seems to suggest it should be there, but it's not. Unsure why
 
![image](https://user-images.githubusercontent.com/46142/235979551-d8b5ccd4-4ba6-4c23-902c-7b6de6822b87.png)

**Comment by joshhunt** [comment]
Oh. We just need to send ?accesscontrol=true with the GetFolders request
