### ISSUE TITLE
Unable to plot CloudWatch metrics. 

### ISSUE THREAD

**Issue by SiddharthMalhotra** [grafana/grafana#6775]
I have downloaded the and extracted grafana on my windows desktop at the following location C:\Users\Administrator\Desktop\Grafana\grafana-4.0.0.windows-x64\grafana-4.0.0

Where do we have to place the aws credentials file? Currently I am storing it C:\Users\Administrator\Desktop\Grafana\grafana-4.0.0.windows-x64\grafana-4.0.0\ .aws\credentials, is that correct? 

I am able to see all the instance details including instance-id on the annotations tab. 

However, plotting is not working. No data points are getting collected. 

Where exactly does the credentials file have to be placed in windows environment?

**Comment by torkelo** [comment]
if you get instance id's the auth is probably working. 

What does your query look like? Have you specified a dimension? Open chrome dev tools network tab and show cloudwatch request and response
