### ISSUE TITLE
Password isn't load into Grafana datasources when using curl command

### ISSUE THREAD

**Issue by asaf1602** [grafana/grafana#67764]
### 
# What went wrong?

**What happened**:
I'm using Grafana v7.5.15 on an EC2 on AWS.
I have data sources for Cloudera manager in a json file as following:
{
    "name": "ClouderaManager",
    "type": "foursquare-clouderamanager-datasource",
    "access": "proxy",
    "url": "https://<HostIP>:7183",
    "user": "admin",
    "secureJsonData": {
        "password": "XXXXXXX"
    },
    "database": "",
    "basicAuth": true,
    "isDefault": false,
    "jsonData": {
        "cmAPIVersion": "v11+",
        "keepCookies": []
    },
    "readOnly": false
}

I load the datasources with following from ksh script with curl command as below:
curl -XPOST -H "Content-Type: application/json" -H "Accept: application/json" --data-binary "$(cat <CM JSON_FILE> )" ${GRAFANA_CONNECTION}/api/datasources 2>/dev/null | ${JQ_TOOL} -r '.message'

The message from jq is "Datasource added"
When I check in Grafana (http://<Grafana IP>:3000/api/datasources/384) I see password isnt load as u can see below:
{
"id": 384,
"uid": "n5cLXayVz",
"orgId": 2,
"name": "ClouderaManager",
"type": "foursquare-clouderamanager-datasource",
"typeLogoUrl": "",
"access": "proxy",
"url": "https://<HostIP>:7183/",
**"password": "",**
"user": "admin",
"database": "",
"basicAuth": true,
"basicAuthUser": "",
"basicAuthPassword": "",
"withCredentials": false,
"isDefault": false,
"jsonData": {
"cmAPIVersion": "v11+",
"keepCookies": []
},
"secureJsonFields": {
"password": true
},
"version": 1,
"readOnly": false
}

**What did you expect to happen**:

Password will populate in the data source.

### 
# How do we reproduce it?

**Step 1**:

Create json file with the data as above.

**Step 2**:
Run the curl command from a ksh script 

**Step 3**:
Check data source in the Grafana 

### 
# What Grafana version are you using?

v7.5.15 

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Anything else to add?

$ uname -s      
Linux
$ uname -r
4.18.0-305.el8.x86_64
$ uname -v
#1 SMP Thu Apr 29 08:54:30 EDT 2021
$ uname -m
x86_64
$ uname -p
x86_64
$ uname -i
x86_64
$ uname -o
GNU/Linux
$

**Comment by tonypowa** [comment]
Hi @asaf1602 and thank you for creating this issue 

Can you try to reproduce the issue, are share more details, in a supported version of Grafana?  
Grafana v.7 is no longer supported.

**Comment by tonypowa** [comment]
closing issue
if more help is needed, please provide more info and reopen 
:wave
