### ISSUE TITLE
[Bug] WebDav upload not working

### ISSUE THREAD

**Issue by m-messiah** [grafana/grafana#6779]
I am using Grafana 4.0.0 (as Debian Jessie pkg) and try to use alerting, but my webdav configuration not working.

I have tried:
```
[external_image_storage]
provider = webdav

[external_image_storage.webdav]
url = https://dav.box.com/dav/
username = user@gmail.com
password = pass
```

also have tried
```
[external_image_storage]
provider = webdav

[external_image_storage.webdav]
url = https://webdav.yandex.ru
username = user
password = pass
```

But all times get errors about authentication.

I have just opened webdavuploader sources /pkg/components/imguploader/webdavuploader.go and saw, there is no any usage of credentials, so all requests sent unauthenticated.

**Comment by flyersa** [comment]
Are you sure your webdav endpoint is working ok? because webdav upload from the alerts module works flawless for us with apache and webdav mod

**Comment by m-messiah** [comment]
@flyersa is your WebDAV use auth? 'Cause mentioned go file does not use it, as I see.

**Comment by flyersa** [comment]
oh yeah you are right, its indeed not auth. Well that might explain the issue then ;)

**Comment by augi** [comment]
Is this fix contained in 4.0.1 release, please?

**Comment by towolf** [comment]
No, it's not. Important for me to. Set up all the webdav shenanigans, and then it doesn't even work.

**Comment by bergquist** [comment]
Currently you need to run master to get this fix. But I will cherry-pick this into our next 4.0.x release.

4.0.1 was a emergency fix for broken tcp connection pooling so we only included a fix for that.

**Comment by bergquist** [comment]
We build and package grafana from every commit. So you can easlily download an early version from http://grafana.org/builds/
