### ISSUE TITLE
Navbar resets to dashboard state when opening the advanced DS modal picker

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#67805]
https://user-images.githubusercontent.com/5699976/236148536-a09f825d-dc18-4a6b-bfbb-3e7c4f7bb992.mov

Notes from Torkel
> we had the same issue with the drawer, I think it's triggering a render of DashNav somehow which resets the nav toolbar content

**Comment by juanicabanas** [comment]
The problem is that the DashNav is using the ModalContext to render the ShareModal. 
Because of the fact the ds modal is opened, that context is updated, which makes a rerender of the DashNav and, therefore, an update of the app-chrome
