### ISSUE TITLE
Monaco Editor: ctrl+s not triggering save

### ISSUE THREAD

**Issue by yoyo421** [grafana/grafana#67829]
### 
# What went wrong?

**What happened**:
Im clicking ctrl+s and the onSave function is not triggering

**What did you expect to happen**:
onSave should be triggered when clicking ctrl+s when modifying a monaco editor

### 
# How do we reproduce it?

**Step 1**:
<details>
  <summary>Load the dashboard</summary>
  
```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 384,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "jn0bdEb1234"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "countRows": false,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "9.4.9",
      "targets": [
        {
          "csvContent": "a,b\n1,1",
          "datasource": {
            "type": "testdata",
            "uid": "jn0bdEb1234"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        },
        {
          "csvContent": "c,d\n2,2",
          "datasource": {
            "type": "testdata",
            "uid": "jn0bdEb1234"
          },
          "refId": "B",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "refresh": "",
  "revision": 1,
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "MonacoBug",
  "uid": "U7LaRPy4k",
  "version": 2,
  "weekStart": ""
}
```
</details>

**Step 2**:

Go to edit the panel

**Step 3**:

Edit the query 'A', in the 'CSV Content' change the second line to `2,2`
!DONT CLICK OUTSIDE OF THE EDITOR AS THE onBlur will be triggering!

**Step 4**:

press 'ctrl+s' and see that the table stay the same

[**edit**] this is the bug, it should get updated, but it isn't

**Step 5**:

change the panel to view query 'B'

**Step 6**:

Edit the query 'B', in the 'CSV Content' change the second line to `4,4`
!DONT CLICK OUTSIDE OF THE EDITOR AS THE onBlur will be triggering!

**Step 7**:

press 'ctrl+s' and see that the table changed to be `4,4`

### 
# What Grafana version are you using?

v9.4.7

### 
### Grafana Platform?

Docker

### Is this a Regression?

None

### Anything else to add?

I have found that the problem lies in the use of `editor.addCommand` in the code. This event is applied to all editors loaded onto the page, causing the onSave function to save the value of the last editor loaded instead of the intended one.

in `packages/grafana-ui/src/components/Monaco/CodeEditor.tsx:107`

replace the 
```js
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, this.onSave);
```
with this
```js
editor.onKeyDown((e) => {
  if (e.keyCode === 49 /** KeyCode.KeyS */ && e.ctrlKey) {
    this.onSave();
  } 
});
```

Would fix the issue as `editor.addCommand` is global to all editors and `editor.onKeyDown` is local

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @yoyo421 

I reproduced the bug 🐛 

Forwarding the issue to our Engineering team
