### ISSUE TITLE
Dashboard: Query Variable Drop-down doesn't refresh according to the selected time range

### ISSUE THREAD

**Issue by ToronTorog** [grafana/grafana#67832]
### 
# What went wrong?

**What happened**:

  - Create a Query Variable on a tag from an InfluxDB V2 Bucket:
     
![image](https://user-images.githubusercontent.com/107122439/236126879-3309246f-f266-48bd-b0db-8300d5e3faa0.png)

  - If the InfluxDB Bucket does not contain any values for the default timerange from the Dashboard:
![2023-05-04_08h21_08](https://user-images.githubusercontent.com/107122439/236128430-680461e0-e15b-4dc9-a9ba-e98c0f529838.png)
  - as expected the drop-down shows the available options for the selected timerange to choose from(in this case nothing):
![2023-05-04_08h20_58](https://user-images.githubusercontent.com/107122439/236128859-1b30cc7e-b921-4a4e-8c45-119749af3ed8.png)

  - But if you proceed to extend the timerange to a point where it should contain values: 
![2023-05-04_08h21_36](https://user-images.githubusercontent.com/107122439/236130195-0afbb26b-5e9b-4b3a-962e-096b107fc5e9.png)
  - the drop-down did not get refreshed: 
![2023-05-04_08h21_23](https://user-images.githubusercontent.com/107122439/236130942-699bc58b-b5a8-48c8-b847-ab5f73f6ae39.png)

  - If the page gets refreshed, the drop-down contains the correct values.

**What did you expect to happen**:

  - The variable drop-down should display all the values within the selected time range.

![image](https://user-images.githubusercontent.com/107122439/236131670-dc5aacd2-a64c-4461-8a11-340cc4c0f49e.png)

### 
# How do we reproduce it?

**Step 1**:

- Create a Query Variable with the time-range: |> range(start: v.timeRangeStart, stop: v.timeRangeStop)

**Step 2**:

- Change the time-range to a interval, that contains other data.

### 
# What Grafana version are you using?

v9.5.1 (bc353e4b2d)

### 
### Grafana Platform?

Docker

### User's OS?

Windows 10 Enterprise 22H2

### User's Browser?

Google Chrome Version 112.0.5615.138 (64-Bit)

### Is this a Regression?

No

### Are Datasources involved?

InfluxDB V2

### Anything else to add?

**Workaround**

  - Instead of 
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  - Use:
  |> range(start: 0001-01-01, stop: v.timeRangeStop)

  - The Problem with this solution is that all values of the variable are loaded to the drop-down. When the Bucket does not contain any Values for the selected time-range an empty Panel is created.

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @ToronTorog 

>Is this a Regression?
>Yes

what was the previous version in which the drop-down refreshed properly?

**Comment by ToronTorog** [comment]
I tried to see if the problem also occurs with Grafana in Docker version 8.0.0 / 8.3.0 / 8.5.13 and indeed it was present in those versions as well. So it is not a regression.

**Comment by itsmylife** [comment]
@ToronTorog Could you please check if you set the `Refresh` option correctly on the Variables editor 
<img width="383" alt="image" src="https://github.com/grafana/grafana/assets/820946/ad87403c-8937-4c77-987b-0528138ec54b">

**Comment by ToronTorog** [comment]
Thank you very much, I didnt see that option there. Now everything works.
