### ISSUE TITLE
InfluxDB Alerting and Authentication not working. 401 Unauthorized

### ISSUE THREAD

**Issue by flyersa** [grafana/grafana#6784]
Hi,

when we enabled Alerting for InfluxDB it only works if we configure influxdb to disable authentication on its http port. If we enable authentication on influxdb then grafana can show the dashboards but the alerts will not use the credentials for the datasource and instead return 401 Unauthorized:

t=2016-12-01T17:40:30+0100 lvl=eror msg="Alert Rule Result Error" logger=alerting.resultHandler ruleId=6 name="MySQL Connections alert" error="tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 401 Unauthorized" changing state to=keep_state

why does the alerting module not use the authorisation data that grafana uses to render the dashboards via proxy?

**Comment by torkelo** [comment]
what does your datasource settings look like?

**Comment by flyersa** [comment]
Hi Torkelo,

like this:

<img width="405" alt="ds-settings" src="https://cloud.githubusercontent.com/assets/4366335/20804041/a78891a2-b7f1-11e6-90b6-930ac9ce7e8e.png">

**Comment by bergquist** [comment]
Thats a bug in the influxdb alerting datasource. It overrides the basic auth header with the influxdb username and password. Are you using both for authentication?

**Comment by flyersa** [comment]
@bergquist right now we run it with authentication off. When i enable influxdb authentification i get http auth windows popping up in the browser in grafana thats why i added the basic auth details. In the basic auth details i added a normal influxdb username and password.  So even if it overrides the basic auth header with the influx user and password that should work or not?

**Comment by torkelo** [comment]
If you have influxdb auth enabled you just need to specify the influxdb user / password, influxdb supports using basic auth to send username password. So you do not need to use both
