### ISSUE TITLE
[Bug?] Request to previous datasource from dashboard and "Unable to load datasource meta data" message

### ISSUE THREAD

**Issue by mbliznikova** [grafana/grafana#6787]
**- What Grafana version are you using?**
3.1.1 

**- What datasource are you using?**
InfluxDB

**- What OS are you running grafana on?**
ubuntu/trusty64

**- What did you do?**
1. Create and delete datasource and associated with it dashboard(s) with graph(s) several times using python script with python.requests. 
2. Create another datasource and associated with it dashboard(s) with graph(s) using same script.
3. Reload page.

**- What was the expected result?**
Graphs work, data from datasource displays

**- What happened instead?**
"InfluxDB Error: undefined". In Inspector, Request details, Url was '/api/datasources/proxy/3/query', so ID of current datasource was 4. It reproduced several times.
So error message appeared: "Unable to load datasource meta data". 
After reloading graphs work, data from datasource displays.

**Comment by torkelo** [comment]
yes, if you remove and read a data source your need to reload a dashboard that use it.
