### ISSUE TITLE
[Bug] Upgrade 3.1.1 -> 4.0.0, template variables used in regexp in InfluxDB raw queries no longer escaped

### ISSUE THREAD

**Issue by jeredfloyd** [grafana/grafana#6788]
- What Grafana version are you using?

4.0.0

**- What datasource are you using?**

InfluxDB 1.1

**- What OS are you running grafana on?**

Debian 8.6 (jessie)

**- What did you do?**

Upgraded from 3.1.1 to 4.0.0 from official repository.

**- What was the expected result?**

No breaking changes.

**- What happened instead?**

InfluxDB queries using template variables in regexps where the variable can assume a value containing a "/" (or other regexp character) do not have the variables escaped when in "raw query" mode.  "Query builder" mode behaves as expected.

Escaping now seems dependent on the state of "rawQuery".

I attempted to find if a particular change was the obvious culprit, but I am not familiar with Go nor the layout of the Grafana project.  I will investigate further as time allows, but am filing this bug report in case it immediately rings any bells with others.

**Comment by torkelo** [comment]
can you show your panel json model and the query grafana sends to InfluxDB?

**Comment by jeredfloyd** [comment]
Yes, here are two "identical" metrics in the same graph (edited to remove irrelevant metrics B-D).  Running through diff, the only difference between the two targets are the values of "refId" and "rawQuery":

**Panel targets JSON:**
          "targets": [
            {
              "alias": "max",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "hide": false,
              "measurement": "nrpe",
              "policy": "default",
              "query": "SELECT mean(\"max\") FROM \"nrpe\" WHERE \"metric\" =~ /^$disk$/ AND \"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^nrpe-disk/ AND $timeFilter GROUP BY time($interval) fill(null)",
              "rawQuery": false,
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "max"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "metric",
                  "operator": "=~",
                  "value": "/^$disk$/"
                },
                {
                  "condition": "AND",
                  "key": "hostname",
                  "operator": "=~",
                  "value": "/^$hostname$/"
                },
                {
                  "condition": "AND",
                  "key": "service",
                  "operator": "=~",
                  "value": "/^nrpe-disk/"
                }
              ]
            },
            {
              "alias": "max2",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "hide": false,
              "measurement": "nrpe",
              "policy": "default",
              "query": "SELECT mean(\"max\") FROM \"nrpe\" WHERE \"metric\" =~ /^$disk$/ AND \"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^nrpe-disk/ AND $timeFilter GROUP BY time($interval) fill(null)",
              "rawQuery": true,
              "refId": "E",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "max"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "metric",
                  "operator": "=~",
                  "value": "/^$disk$/"
                },
                {
                  "condition": "AND",
                  "key": "hostname",
                  "operator": "=~",
                  "value": "/^$hostname$/"
                },
                {
                  "condition": "AND",
                  "key": "service",
                  "operator": "=~",
                  "value": "/^nrpe-disk/"
                }
              ]
            }
          ]

**InfluxDB query:**

SELECT mean("max") FROM "nrpe" WHERE "metric" =~ /^\/$/ AND "hostname" =~ /^monitor$/ AND "service" =~ /^nrpe-disk/ AND time > now() - 12h GROUP BY time(1m) fill(null);SELECT mean("max") FROM "nrpe" WHERE "metric" =~ /^/$/ AND "hostname" =~ /^monitor$/ AND "service" =~ /^nrpe-disk/ AND time > now() - 12h GROUP BY time(1m) fill(null)

Note that the first target (rawQuery: false) properly escapes the "/" value resulting from the interpolated value of $disk, while the second target (rawQuery: true) does not.

**Comment by torkelo** [comment]
unable to replicate this :(

http://play.grafana.org/dashboard/db/influxdb-raw-query-template-var

What is the value / options for the disk variable ?

**Comment by jeredfloyd** [comment]
The $disk variable gets values like "/" or "/mnt/backup".  In the example query it gets "/".

I'm looking through the TypeScript source now to see if I can track down the issue.  I believe it has to do with the change in public/app/plugins/datasource/influxdb/influx_query.ts:204 which used to be (in the case of rawQuery && interpolate):
`        return this.templateSrv.replace(target.query, this.scopedVars, 'regex');`

and is now:
`        return this.templateSrv.replace(target.query, this.scopedVars, this.interpolateQueryStr);`

**Comment by jeredfloyd** [comment]
Yes, I have identified that this is the problem.  In commit 83b9db51e3434466cd2a01d06549ad95c44a798b you make the above change, and the difference between interpolateQueryStr() and the default 'regex' replace function is the addition (in influx_query.ts:186-190) of:
```
    // if no multi or include all do not regexEscape
    if (!variable.multi && !variable.includeAll) {
      return value;
    }
```

This change is not correct -- regexEscape must be done in cases where neither multi nor includeAll are selected.   I believe that this portion should be reverted.  What was the intent of this change?

**Comment by torkelo** [comment]
yea, your right looks incorrect The intent is to only do regex escaping for variables with multi select, or with all value

**Comment by jeredfloyd** [comment]
Unfortunately it's necessary to regexEscape even in single-value cases as those values may still contain unsafe characters.  Would you like me to generate a pull request, or will you handle this internally?

**Comment by torkelo** [comment]
for that case you need to escape yourself, no way to know for grafana is you want to specify a regex expression or just want text

**Comment by jeredfloyd** [comment]
I don't follow your logic? This change is a regression from 3.1.1. 

Are you suggesting that the user intent might be to include an actual regex as a value in the template variable?

**Comment by torkelo** [comment]
yes, for raw queries, only multi and include all will be automatically regexed, because those need it. Many also use variables for custom filter and want to be able to specify a custom value (in the variable input) and use regex.

**Comment by jeredfloyd** [comment]
OK, if you want to keep this change then:
1) Behavior when using the query builder must be the same.  This means the function argument change should also be made in the calls to templateSrv.replace() that appear in renderTagCondition() and getMeasurementAndPolicy(), and 

2) Release note this as a breaking change.  

Note that this is rather challenging to work around, because there's no easy way to "unescape" the variable for the graph label.  So, even if I change my DB to store "\/mnt\/backups" (for example), then my graph title becomes "Disk \/mnt\/backups", which is unpleasant.

So, if you are intent on keeping this change, then I would suggest adding another checkbox to the Templating configuration page that allows the user to determine if single-value interpolation should be regex-escaped.

**Comment by jeredfloyd** [comment]
(Also, I believe that "Closed" is no longer the correct disposition of this ticket.)

**Comment by jeredfloyd** [comment]
#6789 suggests there are users who do want the effects of the change (although they are currently inconsistent across raw query vs. query builder) so a separate checkbox is likely the best solution.

**Comment by torkelo** [comment]
could you describe why are you using the regex operator in this case? 

If you want more control over regex escaping use the query builder, it will always regex escape when the operator is a regex match. The problem is that in raw query mode Grafana does not know what operator is used so only does regex escaping when it know it's required (due to multi select, etc)

**Comment by jeredfloyd** [comment]
Oooh, now *that* is a good question.  And I have a very bad answer for it, which is that I started with the shared Icinga2 dashboard (https://grafana.net/dashboards/381) which uses the regex operator for exact matches in its queries.  There is definitely no good reason for that, and I can easily stop.

I think it is still questionable that Grafana is still escaping the interpolated values when the query builder is in use.  I now understand the case for storing regex in the data source, and in that case the capability should be available when using the query builder as well.
