### ISSUE TITLE
Subpath missing in Table Data links

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#67885]
### 
# What went wrong?

After updating to version 9.5.1, my links in a table no longer work. This has nothing to do with #67701, because in my case it is due to the fact that I am using a reverse proxy and therefore my SubPath needs to be inserted. This is missing.

Data Link:
/d/${__dashboard.uid}?orgId=${__org}${__data.fields.url}

Result:
https://www.zoomsoft.de/d/banuwomo?orgId=1%26from%3Dnow%2Fd%26to%3Dnow%2Fd%26refresh%3D10s

Should:
https://www.zoomsoft.de/grafana/d/banuwomo?orgId=1%26from%3Dnow%2Fd%26to%3Dnow%2Fd%26refresh%3D10s

custom.ini:
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

### 
# How do we reproduce it?

.

### 
# What Grafana version are you using?

9.5.1 on Windows with reverse proxy

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by Nemric** [comment]
I'd like to add a kind of clue about that
Since 9.5.1, links like "http://github.com" in table cell are now seen as "http://grafana.local/http://github.com"
Hope this will help

**Comment by UlrichThiess** [comment]
Fixed with 9.5.2.
Thanks. Maybe with #67701
