### ISSUE TITLE
[Bug] Constant 502 Bad Gateway from Grafana After 4.0 Upgrade

### ISSUE THREAD

**Issue by willneumob** [grafana/grafana#6790]
>What Grafana version are you using?

4.0.0

>What datasource are you using?

Graphite

> What OS are you running grafana on?

Ubuntu 16.04, behind nginx reverse proxy on same system.

> What did you do?

Load a dashboard and leave it open for a few minutes.

> What was the expected result?

Not have every panel error on refresh.

- What happened instead?
After I leave any dashboard open for more than a few minutes, all panels get errors. Once I refresh the page, the panels load. Did not have any such problems before 4.0 upgrade.

>An image or text representation of your metric query

```aliasByNode(summarize(removeBelowValue(highestCurrent(sys.*.statsd.gauge-mygauge.total_something, 10), 1), '$Interval', 'avg'), 1)```

>The raw query and response for the network request

```[pid  6684] write(139, "HTTP/1.0 502 Bad Gateway\r\nDate: Fri, 02 Dec 2016 00:28:56 GMT\r\nContent-Length: 0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n", 125 <unfinished ...>```

Grafana itself is returning 502 (not nginx), and even with logging set to `Debug` for `file`, there is no meaningful data or errors reported in `/var/log/grafana/grafana.log`. I realize there's a lack of good debugging information here, but without logs, I'm not really sure how to narrow it down. 

I'm okay with downgrading, but can't find any documentation with regard to schema changes and if a downgrade would cause things to break. I can provide more debugging information if pointed in the right direction. Thanks!

**Comment by SamuraiPrinciple** [comment]
We're having the same issue - it also happens when you keep refreshing the dashboard. We're also seeing much higher cpu load than with v3.2.1. Would you be able to check cpu load (our would sometimes jump to as high as 30, it's typically below 0.5).

Many thanks,
damjan

**Comment by willneumob** [comment]
Our load and CPU usage looks relatively normal. I deployed 4.0 the morning after it came out, and here are graphs for the preceding weeks until now:

<img width="591" alt="screen shot 2016-12-02 at 3 41 24 am" src="https://cloud.githubusercontent.com/assets/17169241/20832840/5cb8ab26-b841-11e6-8d08-827448632a31.png">
<img width="589" alt="screen shot 2016-12-02 at 3 39 45 am" src="https://cloud.githubusercontent.com/assets/17169241/20832839/5cb69944-b841-11e6-87fe-7ca3e7d53300.png">

**Comment by torkelo** [comment]
This is related to a connection issue with the data source proxy that was introduced after v4.0.0-beta2, sorry about this. We are pushing a new patch 4.0.1 patch release now:

https://github.com/grafana/grafana/issues/6759

**Comment by willneumob** [comment]
Thanks @torkelo, I'll deploy it as soon as the package hits the APT repository.

**Comment by willneumob** [comment]
Installed 4.0.1, and so far the issue seems fixed. Thanks again.

**Comment by SamuraiPrinciple** [comment]
Same here - 4.0.1 indeed fixes the issue. Many thanks.

**Comment by orngeno** [comment]
I am using grafana  latest version v4.5. I am also getting the same error.But I have given data source as "prometheus". 
![image](https://user-images.githubusercontent.com/31848376/30274309-8263bc9a-971a-11e7-9a57-32009a5ecb88.png)
Please find the details in the screenshot.

**Comment by torkelo** [comment]
strange that your prometheus server is returning Bad Gateway status code after upgrade. Not seeing the same, wonder what could be the cause. ..

**Comment by daniellee** [comment]
@orngeno did it work in a previous version of Grafana? Can you navigate to http://192.168.99.100:9090 in your browser and see the Prometheus admin page?

**Comment by orngeno** [comment]
Hi @daniellee 
It is working now.As I dont know what are the images that we need to add in docker when we use this tools to run.For this, I got solution from stephenprodan blog where he gave complete information about configuring these tools and monitoring.

Thanks for your concern.:)

**Comment by huseyinkozan** [comment]
Same here:
```
gui_1             | PUT /g/api/datasources/2 200 47.753 ms - 57
gui_1             | GET /g/api/frontend/settings 200 6.308 ms - -
grafana_1         | t=2017-11-09T20:43:28+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=2 username=admin datasource=influxdb uri="/api/datasources/proxy/2/query?db=db&q=SHOW%20DATABASES&epoch=ms" method=GET body=
grafana_1         | 2017/11/09 20:43:28 http: proxy error: context canceled
gui_1             | GET /g/api/datasources/proxy/2/query?db=db&q=SHOW%20DATABASES&epoch=ms 502 6.517 ms - 0
grafana_1         | t=2017-11-09T20:43:28+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=2 uname=admin method=GET path=/query status=502 remote_addr=172.25.0.1 time_ms=1 size=0 referer=http://console.creasens.io/g/datasources/edit/2
```
Using 4..6.1 docker image behind a nginx proxy (console.example.com) and behind [http-proxy](https://www.npmjs.com/package/http-proxy) (console.example.com/g/). Auth proxy is enabled over email. DB is `influxdb:1.3-alpine` docker image. All machines are at the same bridged network at docker-compose env. Machines have static IPs. `curl influxdb:8086/ping` command at Grafana bash gives no error.

Trying to find more info, but got only above for now. Can you guide me to resolve problem ?

**Comment by rakode** [comment]
Cuando me conecto con grafana a influxdb me sale este error  network error:Bad Gateway (502)
