### ISSUE TITLE
template  var not work in elasitcserach luence query input 

### ISSUE THREAD

**Issue by berlinsaint** [grafana/grafana#6792]
Grafana version :4.0.0
datasource : elasticsearch

when using template var in  query input, and my var is a custom string ,it dosent work well.
it does well in metric input.is it a problem?
by the way, in the below json, in metric field, template var works well ,the it is a query type  var: $num
but when i define an custom var, and use it in Query input it dosent work

my pannel json is 

{
  "aliasColors": {},
  "bars": false,
  "datasource": "logcenter",
  "editable": true,
  "error": false,
  "fill": 1,
  "grid": {},
  "id": 2,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 2,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 6,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "",
      "bucketAggs": [
        {
          "fake": true,
          "field": "producerAppName",
          "id": "7",
          "settings": {
            "order": "asc",
            "orderBy": "_term",
            "size": "10"
          },
          "type": "terms"
        },
        {
          "fake": true,
          "field": "createTime",
          "id": "6",
          "settings": {
            "interval": "auto",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "dsType": "elasticsearch",
      "hide": false,
      "metrics": [
        {
          "field": "$num",
          "id": "1",
          "meta": {},
          "settings": {},
          "type": "avg"
        },
        {
          "field": "$num",
          "id": "3",
          "meta": {},
          "settings": {},
          "type": "max"
        },
        {
          "field": "$num",
          "id": "4",
          "meta": {},
          "settings": {},
          "type": "min"
        }
      ],
      "query": "$custom",
      "refId": "A",
      "timeField": "createTime"
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "$Title 响应时间统计",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": "$Lyn",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}

**Comment by torkelo** [comment]
What is the value of query? Is it a valid lucene query? 

Please show Elasticsearch query and Elasticsearch response, also template variable options/model might help
