### ISSUE TITLE
[Bug] Layout broken when a lot of templating

### ISSUE THREAD

**Issue by xluffy** [grafana/grafana#6793]
> - What Grafana version are you using?

4.0.0. I upgrade from 3.x

> - What datasource are you using?

ES and Zabbix

> - What OS are you running grafana on?

CentOS 6.8

> - What did you do?

Load a dashboard

> - What was the expected result?

Templating sort in multiple lines

> An image or text representation of your metric query

http://imgur.com/a/JzM6d

If my dashboard has some templating. It's show beautiful.

**Comment by torkelo** [comment]
We only support templating variables that fit on one line
