### ISSUE TITLE
Cannot update information in Grafana 2

### ISSUE THREAD

**Issue by vicsun2007** [grafana/grafana#6794]
Hello, 

This is Victor, I can not update any information into Grafana 2, I'm install Grafana 2 before setup zabbix 2.2,  that is ok to create new graph when i add graph in the first time, but after I click "save" button there is nothing in "Data sources", besides, I was try to create new user in Grafana this was failed too.

below information for you reference:
- https://grafanarel.s3.amazonaws.com/builds/grafana-2.1.1-1.x86_64.rpm
- data source from zabbix server
- the OS is Centos 6.5

If any details you want, please let me know.
Looking forward your feedback.
Thanks.

**Comment by torkelo** [comment]
Not sure what could be wrong. No reports like this before, maybe something wrong with the grafana database, permissions to save data?  

Try newer Grafana release, check permissions to grafana database (if you use default sqlite3)
Please open questions to the mailing list.
