### ISSUE TITLE
Documentation: postgres ssl_mode possible values are incomplete

### ISSUE THREAD

**Issue by jroper** [grafana/grafana#67971]
The docs for `ssl_mode` for postgres in the Grafana ini file, see here:

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#ssl_mode

state that when using Postgres:

> For Postgres, use either `disable`, `require` or `verify-full`.

This is incomplete, it actually accepts any valid Postgres ssl mode described [here](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS), ie `disable`, `allow`, `prefer`, `require`, `verify-ca`, `verify-full`. Some of the other supported modes are quite useful, for example, `verify-ca` is very commonly used when using cloud database providers, because the server name they present usually doesn't even resolve, and is not interesting from a security perspective.

The docs should be updated, probably with a link to the postgres docs rather than having to repeat a description of all the modes, perhaps to say:

> For Postgres, use any [valid libpq `sslmode`](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS), eg `disable`, `require`, `verify-full`, etc.

**Comment by usmangt** [comment]
Hi @jroper,

Thanks for opening this issue.

I will forward it to our documentation team so that they can take it from here. :+1:

**Comment by zoltanbedi** [comment]
I think that what you suggest make sense @jroper. We are open for a PR from anyone with the suggested changes.

**Comment by Soham-glitch** [comment]
I want to contribute to this issue. Please assign me.

**Comment by Soham-glitch** [comment]
I have a few questions.
instead of the following
`For Postgres, use either disable, require, or verify-full.`

I have to add this 
For Postgres, use any [valid libpq sslmode](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS), eg disable, require, verify-full, etc.
so I think I  have to update the `index.md` file

right?

**Comment by zoltanbedi** [comment]
Yes @Soham-glitch, that sounds good.

**Comment by Soham-glitch** [comment]
I have raised a PR for this issue. Kindly check it.
