### ISSUE TITLE
[Feature request] HTTP proxy support for alerting

### ISSUE THREAD

**Issue by deniszh** [grafana/grafana#6798]
Grafana uses direct HTTP calls for calling PD / Slack / Webhook / S3  notifications/uploads, which is not working with isolated environments. Some support for outgoing http(s) proxy will be great!

**Comment by torkelo** [comment]
should be possible if you set standard environment http proxy settings:

env http_proxy=proxy-url
env https_proxy=proxy-url

**Comment by deniszh** [comment]
Ah, sorry, forgot about that. Will create PR for proper change in initscripts.

**Comment by torkelo** [comment]
why change in init scripts? there is a defaults file for ubuntu / debian, a sysconfig file for centos/rpm/rel  where you can specify/override environment variables

**Comment by deniszh** [comment]
Ah, defaults just insourcing in start script. My bad, I was blind.¯\_(ツ)_/¯

**Comment by deniszh** [comment]
Just tried approach above - it didn't go well because Grafana tries to connect to Graphite also through a proxy (which is obvious), but it's better to send only alert URLs through the proxy, and not all HTTP requests.
Could you please open issue again?

**Comment by deniszh** [comment]
Ah, I'm too fast again. Of course, `no_proxy`  is there, and you just need to exclude Graphite (or any other HTTP connected datasource) from connecting through a proxy.

**Comment by jeremyjwan** [comment]
Hello, I am running into this exact problem, where it seems I'm not able to set my grafana's outbound proxy. How did you set that url?

**Comment by alvarolmedo** [comment]
+1

**Comment by skytrackingAdmin** [comment]
+1
