### ISSUE TITLE
[BUG]: v4.0.0 Alert returned no data

### ISSUE THREAD

**Issue by iowelinux** [grafana/grafana#6800]
Hi,

I see the following in the log:
> t=2016-12-02T14:04:31+0300 lvl=info msg="Alert Rule returned no data" logger=alerting.resultHandler ruleId=5 name="Cisco CPU Usage alert" changing state to=alerting

As a result there are no metric's name and metric's value at the alert message.
Please have a look at the [screenshot](https://scr.pics/16t40hs.png)

It's just a simple alert that check the last state of a value, that's all.

**Comment by torkelo** [comment]
looks like the are null values for the most recent data points. what is your alert aggregation method? 

Can you show output when you hit Test Rule (expand everything so you see data points). Can you show the alert definition? Screenshot or panel json

**Comment by iowelinux** [comment]
[Screenshot of the rule](https://scr.pics/16j22yz.png)

Also here is the query for metric A:
`SELECT 8 * non_negative_derivative(mean("value"), 1s) FROM "snmp_rx" WHERE "host" = 'cisco.local' AND "type_instance" = 'TenGigabitEthernet3_1' AND $timeFilter GROUP BY time($interval) fill(null)`

I don't know the reason there is no data in the alert but graphs works correctly and the metric is visualized.

**Comment by torkelo** [comment]
you query seems to not be returning any data points. the non negative derivate needs two values, maybe you need to increase the alert query time range?
