### ISSUE TITLE
[Bug]Grafana service fails to start. Hangs at Http server initialization

### ISSUE THREAD

**Issue by adityacs** [grafana/grafana#6801]
Grafana service fails to start. Hangs at Http server initialization. Using rhel-7.2 with Grafana-4

![grafana](https://cloud.githubusercontent.com/assets/7681197/20838826/3e8cbfa4-b8d0-11e6-8a5c-b4cee4630b0a.PNG)

**Comment by torkelo** [comment]
what do you mean it hangs? That is the end of the init phase (last log message after successful start) Have you tried accessing grafana via port 3000?

**Comment by adityacs** [comment]
Now it's working. In the logs I was not able to see anything after http server initialization. Now everything is fine.

**Comment by dethakur** [comment]
@adityacs Hi how did you get it to work , even mine grafana installation with docker is stuck at t=2017-01-08T00:24:16+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=

**Comment by torkelo** [comment]
It's not stuck at that line, that is the last log line after successfull start

**Comment by adityacs** [comment]
@dethakur It's not an error/issue. The log means that grafana has started properly. Check your firewall settings once and check if port 3000 is open. From grafana side everything is fine.

**Comment by dethakur** [comment]
@adityacs @torkelo Indeed it wasnt a grafana problem. My grafana works fine. Thanks for your response guys.
