### ISSUE TITLE
[Bug] Email address won't save

### ISSUE THREAD

**Issue by deric** [grafana/grafana#6802]
I'm using Grafana from Debian package `4.0.0-1480439068`. I've created an alert. It gets evaluated, everything works fine, except setting "send to" address.

![grafana](https://cloud.githubusercontent.com/assets/138573/20839055/5ee70306-b8ab-11e6-87de-dd9f9059052c.png)

The email address is kept there when I'm staying on the "Alert" tab. Saving the whole dashboard doesn't help. When I switch to another tab the "send to" value is lost. I've set log level to `trace`, but nothing suspicious shows up. 
```
t=2016-12-02T15:23:01+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=17.703 alertId=1 name="Check if all agents are running" firing=true
t=2016-12-02T15:23:02+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-02T15:23:12+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
```

**Comment by torkelo** [comment]
Open the grafana side menu and hover over the Alerting menu option, then hit the Notifications menu options. There you can setup a notification that you then use from your alert rules.

**Comment by deric** [comment]
Oh, sorry mine fault, I overlooked that :( It might be worth to add there some UX hint, something like "No notification target defined".

**Comment by AAbouZaid** [comment]
I still think this needs some enhancements in terms of UX. Because I almost know no one tried to use Grafana alerting for first time and didn't fall in this pitfall.
