### ISSUE TITLE
elasticsearch datasource does not close or reuse filedescriptor's

### ISSUE THREAD

**Issue by ThomasADavis** [grafana/grafana#6803]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?

grafana.x86_64 0:4.0.0-1480439068

- What datasource are you using?

elasticsearch 2.4

- What OS are you running grafana on?

CentOS7
- What did you do?

start server, let run, watch the number of fd's climb, and climb, finally stopping at the 10k limit.

- What was the expected result?

Filedescriptors should be either re-used or closed if not needed.

- What happened instead?

Filedescriptors are never reused, never closed.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by ThomasADavis** [comment]
Here is what v3.1 does:

[root@grafana ~]# netstat -tanp | grep grafa
tcp        0      0 192.168.85.240:36242    192.168.85.240:9200     ESTABLISHED 14593/grafana-serve 
tcp        0      0 192.168.85.240:54548    151.101.40.133:443      ESTABLISHED 14593/grafana-serve 
tcp        0      0 192.168.85.240:36228    192.168.85.240:9200     ESTABLISHED 14593/grafana-serve 
tcp6       0      0 :::3000                 :::*                    LISTEN      14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58174    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:57998    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58010    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58188    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58058    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58068    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58180    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58082    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58184    ESTABLISHED 14593/grafana-serve 
tcp6       0      0 192.168.85.240:3000     192.168.85.253:58032    ESTABLISHED 14593/grafana-serve 

[root@grafana ~]#netstat -tanp | grep grafana | wc -l
32

Here is what v4.0 does, using the same dashboard:

gulp, I am not inserting 3k+ lines.

[root@gt4 ~]# netstat -tanp | grep grafana | wc -l
3812

**Comment by bergquist** [comment]
This was fixed in a point release today. http://grafana.org/download/

ref https://github.com/grafana/grafana/issues/6759
