### ISSUE TITLE
[Bug] Empty space

### ISSUE THREAD

**Issue by willemdh** [grafana/grafana#6804]
- What Grafana version are you using?
4.0.0-1480439068
- What datasource are you using?
InfluxDB 1.1.0-1
- What OS are you running grafana on?
CentOS 7
- What did you do?
Add a text panel with span 12. Add a pie panel. Move the pie panel.
- What was the expected result?
The pie panel is properly removed, no empty space
- What happened instead?
![image](https://cloud.githubusercontent.com/assets/6462991/20846984/78df31ae-b8cc-11e6-84b8-b7f8495dd57e.png)
Although I set the text panel to 12, the Empty space just moves beneath the text panel. There seems to be no way to delete the empty space.

**Comment by willemdh** [comment]
Managed to make the empty space go away by dragging the right south corner over it.

**Comment by MrMMorris** [comment]
saw this with 4.1.2.

I was able to make it go away by increasing the size of a panel on the same row until it took up the empty space and then decreasing the size to how it was.
