### ISSUE TITLE
[Feature request] alerting web hook doesn't include the message in the post/put requests

### ISSUE THREAD

**Issue by matthew-kruse** [grafana/grafana#6807]
It would be incredibly helpful on the alerting web hooks for the message body to be included in the post/put requests.

Please include this information:
Using grafana 4.0
OpenTSDB 2.3
Running on Centos 6

Example of what I mean
![image](https://cloud.githubusercontent.com/assets/13338550/20849015/f32ee2c8-b891-11e6-897d-fd057df5255d.png)

**Comment by bergquist** [comment]
Will be available in 4.1.0

**Comment by matthew-kruse** [comment]
@bergquist Thanks!

**Comment by bergquist** [comment]
This have been cherry picked into 4.0.2
