### ISSUE TITLE
[Feature request] Include opentsdb tag name values in alert body

### ISSUE THREAD

**Issue by matthew-kruse** [grafana/grafana#6808]
Using:
Grafana 4.0
OpenTSDB 2.3
CentOS 6

Below is the test result of running an OpenTSDB query that returns 4 series of data for load average.  Each series represents a distinct host's load average.  The alert payload doesn't include the opentsdb host tag name.  For many things that could potentially alert off of opentsdb data including the tag names associated with the metric name and data points is critical.

I used an OpenTSDB query like the following:
{
	"start": 1480717833126,
	"queries": [{
		"metric": "proc.loadavg.15min",
		"aggregator": "avg",
		"downsample": "2s-avg",
		"tags": {
			"host": "*"
		}
	}],
	"msResolution": false,
	"globalAnnotations": true,
	"showQuery": true
}

The test output from the alerts ui returned:
{
	"firing": true,
	"conditionEvals": "true = true",
	"timeMs": "-22.755ms",
	"matches": [{
		"metric": "proc.loadavg.15min",
		"value": 3.5199999809265137
	}, {
		"metric": "proc.loadavg.15min",
		"value": 3.7699999809265137
	}, {
		"metric": "proc.loadavg.15min",
		"value": 4.050000190734863
	}, {
		"metric": "proc.loadavg.15min",
		"value": 3.369999885559082
	}, {
		"metric": "proc.loadavg.15min",
		"value": 3.8399999141693115
	}],
	"logs": [{
		"message": "Condition[0]: Query Result",
		"data": [{
			"name": "proc.loadavg.15min",
			"points": [
				[3.5199999809265137, 1480720800]
			]
		}, {
			"name": "proc.loadavg.15min",
			"points": [
				[3.7699999809265137, 1480720800]
			]
		}, {
			"name": "proc.loadavg.15min",
			"points": [
				[4.050000190734863, 1480720800]
			]
		}, {
			"name": "proc.loadavg.15min",
			"points": [
				[3.369999885559082, 1480720860]
			]
		}, {
			"name": "proc.loadavg.15min",
			"points": [
				[3.8399999141693115, 1480720800]
			]
		}]
	}, {
		"message": "Condition[0]: Eval: true, Metric: proc.loadavg.15min, Value: 3.520",
		"data": null
	}, {
		"message": "Condition[0]: Eval: true, Metric: proc.loadavg.15min, Value: 3.770",
		"data": null
	}, {
		"message": "Condition[0]: Eval: true, Metric: proc.loadavg.15min, Value: 4.050",
		"data": null
	}, {
		"message": "Condition[0]: Eval: true, Metric: proc.loadavg.15min, Value: 3.370",
		"data": null
	}, {
		"message": "Condition[0]: Eval: true, Metric: proc.loadavg.15min, Value: 3.840",
		"data": null
	}]
}

**Comment by trojanman190** [comment]
Could this actually be a **bug** and not a feature request?  

According to the webhook section of Grafana's [alert notification doc](http://docs.grafana.org/alerting/notifications/) tags are already supposed to be sent with the webhook request:
```
{
  "title": "My alert",
  "ruleId": 1,
  "ruleName": "Load peaking!",
  "ruleUrl": "http://url.to.grafana/db/dashboard/my_dashboard?panelId=2",
  "state": "Alerting",
  "imageUrl": "http://s3.image.url",
  "message": "Load is peaking. Make sure the traffic is real and spin up more webfronts",
  "evalMatches": [
    {
      "metric": "requests",
      "tags": {},
      "value": 122
    }
  ]
}
```
However, I am getting ```tags: null``` on alerts generated from queries that use tags, making it somewhat difficult to do meaningful stuff with the alerts.

**Comment by trojanman190** [comment]
Just verified that this issue is still present in Grafana 4.2.0.  Perhaps this is actually a bug and not a feature request? Again, I site the fact that the example in the docs clearly shows tags being returned but that doesn't actually happen.

**Comment by torkelo** [comment]
waiting for OpenTSDB community to contribute here, 

There is a open bug regarding alerting and series names (and alias patterns): https://github.com/grafana/grafana/issues/7309

and WIP PR that seems to have stalled: 
https://github.com/grafana/grafana/pull/7436

**Comment by trojanman190** [comment]
Ah, very much appreciate the response!

**Comment by torkelo** [comment]
closing this as it's similar to https://github.com/grafana/grafana/issues/7309
