### ISSUE TITLE
[Feature request] Generic oauth: Optionally verify oauth scopes

### ISSUE THREAD

**Issue by jmcarp** [grafana/grafana#6809]
When we authenticate a user via generic oauth, we can ask for scopes, but we don't verify that the user actually has those scopes. It would be useful to optionally verify that the user has the requested scopes by decoding the access token and inspecting the scopes. This would be a more generic way of limiting access than checking teams and organizations, since not all oauth providers have those concepts. See https://github.com/concourse/atc/pull/112 for an example on a different project.

If you're interested in this feature, I'd be happy to send a pull request.

**Comment by DanCech** [comment]
Sounds like a good idea to me!

**Comment by marcelfischer** [comment]
+1

**Comment by robmatear** [comment]
Are there any plans to address this request?

**Comment by rodrigocastrillon** [comment]
+1
