### ISSUE TITLE
Evaluation group selection improvement

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#68097]
<img width="720" alt="Screenshot 2023-05-10 at 12 30 08" src="https://github.com/grafana/grafana/assets/33540275/931b3966-c113-49ff-8962-a89da53a7d75">

**New evaluation group selection modal**

Be able to select folder and group in one go:

<img width="779" alt="Screenshot 2023-05-10 at 12 29 24" src="https://github.com/grafana/grafana/assets/33540275/4623b517-f387-4003-b517-5b43212d0f29">

**Comment by VikaCep** [comment]
There's a new proposal for this redesign that we can address sooner:

https://www.figma.com/proto/AYMboJsnYgSAAdYM9hoMLn/Alerting?page-id=0%3A1&type=design&node-id=1316-29390&viewport=145%2C-16060%2C0.66&scaling=min-zoom&starting-point-node-id=1322%3A29730&t=zoCmAfhAftS5r6FI-1

![image](https://github.com/grafana/grafana/assets/6271380/6cd7b51e-a927-43a9-b2bf-3291c3a38d7d)
