### ISSUE TITLE
the mysql password contain special charactors like # the grafana server cannot connect to mysql server properly

### ISSUE THREAD

**Issue by youerning** [grafana/grafana#6810]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by youerning** [comment]
the log:
2016/12/03 04:16:41 [I] Database: mysql
2016/12/03 04:16:41 [I] Migrator: Starting DB migration
2016/12/03 04:16:41 [log.go:84 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1045: Access denied for user 'grafana'@'IPxxxx' (using password: YES)

**Comment by bergquist** [comment]
I think its due to # having special functionallity in the ini lib we are using. Should be possible to solve by getting raw value.

**Comment by bergquist** [comment]
`#` is the comment char in ini files so it will remove the # char and anything after.
How ever if you wrap the password in the ini files with in `"""` it wont be threated as a password

ex
`password = """#password"""`

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/464553a453c12d41a938aca7ce0beab6078cfedb
