### ISSUE TITLE
[Bug] "too many open files" - Elasticsearch data source connection leak

### ISSUE THREAD

**Issue by conzyor34** [grafana/grafana#6812]
Hello. After upgrading from grafana-4.0.0-1478693311beta1 to the release version  grafana-4.0.0-1480439068  on RHEL7, I encountered a problem with connections not being closed from the Elasticsearch data source. I have a dashboard that uses 7 Elasticsearch queries and auto-refreshes. Every refresh, 8 new connections are opened to Elasticsearch and not closed. Eventually Grafana stops working with log messages containing "too many open files":

```t=2016-12-02T11:39:24-0600 lvl=eror msg="Failed to start session" logger=context error="open /var/lib/grafana/sessions/5/7/577c5a1e31701f54: too many open files"```

Running lsof showed over 10,000 TCP connections open at the time Grafana stopped working. The TCP connections were all to the ElasticSearch machine.

This chart shows the connections growing over time as the dashboard continually refreshes. The number of connections returned to 0 when I restarted grafana-server, but quickly grew again as the users had the dashboard opened.

![tcp_connections](https://cloud.githubusercontent.com/assets/2005463/20860903/bd4280c2-b948-11e6-89a6-ce220401b565.png)

Lsof output:

...snip...
grafana-s 76810 grafana   37u     IPv4            8292711      0t0     TCP hgsplogna02:33546->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   42u     IPv4            8292859      0t0     TCP hgsplogna02:33564->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   43u     IPv4            8292112      0t0     TCP hgsplogna02:33566->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   44u     IPv4            8292860      0t0     TCP hgsplogna02:33568->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   47u     IPv4            8292115      0t0     TCP hgsplogna0233570->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   48u     IPv4            8292863      0t0     TCP hgsplogna02:33572->hgspellna01:wap-wsp (ESTABLISHED)
grafana-s 76810 grafana   49u     IPv4            8294404      0t0     TCP hgsplogna02:33576->hgspellna01:wap-wsp (ESTABLISHED)
...snip...

The server hgspellna01 is the Elasticsearch host and hgsplogna02 is the host running Grafana.

**Comment by bergquist** [comment]
Its bug in 4.0.0 please upgrade to 4.0.1

**Comment by conzyor34** [comment]
Yes, it looks like it is fixed in 4.0.1. Thanks. Apologies for the duplicate bug report.
