### ISSUE TITLE
Task: change public dashboard audit table design

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#68136]
Change design to use the card component

New design: https://www.figma.com/file/rPzflElZXoRp3PAtDiYicZ/Share-dashboard?type=design&node-id=640-6252&t=axeonLT2EwRsYpLT-0

**Comment by khushijain21** [comment]
I'd like to work on this - is it open?

**Comment by natellium** [comment]
Hey @khushijain21 great to see you want to contribute! Unfortunately this task is already being worked on as you can see in this [PR](https://github.com/grafana/grafana/pull/68137), but feel free to pick up anything from our team's [help wanted list](https://github.com/orgs/grafana/projects/202/views/8) :)
