### ISSUE TITLE
Docs: On 'Add support for annotations' topic, ensure proper link

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#68147]
### 
# What went wrong?

**What happened**:

  - At top: "This guide explains how to add support for [annotations]({{< relref "../../dashboards/build-dashboards/annotate-visualizations/#querying-other-data-sources " >}}) to a data source plugin."

**What did you expect to happen**:

  - But this page talks about adding to panels, not alerts. Ensure correct info.

### 
# How do we reproduce it?

Go to https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/

### 
# What Grafana version are you using?

9.5

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by Eve832** [comment]
Hi @josmperez, can you please update the status of this ticket in your view in https://github.com/orgs/grafana/projects/69/
