### ISSUE TITLE
[Bug] Singlestat and filter variables

### ISSUE THREAD

**Issue by messier51a** [grafana/grafana#6815]
Do they work ok together?. I'm trying to display the "current" value of my series in a Singlestat using filter variables and refreshing every N seconds, but the value in the Singlestat doesn't change. It does change when I go and select a time range, but as soon as I change back to "refresh every N seconds" it stops updating. Any ideas?

**Comment by torkelo** [comment]
Can you show your singlstate option, your template variable option. 

Also please open chrome dev tools and show the metric requests being sent (the raw requests and the response), please investigate these your self, anything strange with the queries sent or the metric data points returned compared to what the singlestat shows?

**Comment by messier51a** [comment]
Ok I see the problem in the query going out to Influx.

SELECT "Flow" FROM "Burner" WHERE "Area" =~ /^A-1$/ AND "Line" =~ /^L-1$/ AND "Fce" =~ /^(F-1)$/ AND "Burner" = 'B-1' AND time > now() - 5m

it seems to be missing the upper limit <= now(), otherwise the "current" value on any control (not only an issue with Singlestat) will show the last record of the series which doesn't correspond to what is being displayed.

Or maybe I am not understanding how to use Grafana.  All I want is to have a "live" chart refreshing every n seconds and showing the current value.

Any suggestions would be appreciated.

Thanks!

**Comment by messier51a** [comment]
To reproduce the behavior, fill your database with data points extending a bit into the future and set the chart to auto refresh. I understand this is a very particular and uncommon scenario.  I am running simulations with a predictive model that is up to 5 minutes ahead of real-time, and that's screwing up the "current" value because it is showing me the last record available in the database, not the last record between now()-T and now(). Sorry for the confusion!

**Comment by torkelo** [comment]
To get accurate time range filter you need to use $timeFilter variable in the where clause, see how UI query builder builds queries,

**Comment by messier51a** [comment]
I toggled the metrics to raw mode I can see the $timeFilter variable there:

SELECT "Flow" FROM "Burners" WHERE "Area" =~ /^$Areas$/ AND "Lines" =~ /^$Line$/ AND "Fces" =~ /^$Fces$/ AND "Burner" = 'B-1' AND $timeFilter

But the query going out to Influx looks like this (missing time <= now() ):

SELECT "Temperature" FROM "Fces" WHERE "Area" =~ /^A-1$/ AND "Line" =~ /^L-1$/ AND "Fce" =~ /^(F-1)$/ AND time > now() - 5m

So it is returning also the points that are ahead in the future, messing up the "current" value as shown in the screenshot, so it doesn't match the series being plotted:

![temp](https://cloud.githubusercontent.com/assets/20779219/20908344/d9d822c8-bb19-11e6-9528-5f513c098262.png)

**Comment by torkelo** [comment]
Make sure the time is correct and in sync  in your browser and in your InfluxDB machine

**Comment by messier51a** [comment]
I'm running everything local, time is in sync.  I tried modifying datasource.ts for influxdb and it is working as  expected now. 

`    if (until === 'now()' && !fromIsAbsolute) {
      return 'time > ' + from + ' and time <= now()';
    }`
