### ISSUE TITLE
[Bug] Graph update 2 mintue lag (influxdb)

### ISSUE THREAD

**Issue by 2000jago** [grafana/grafana#6816]
Hi, 
-  Grafana Version:  Grafana v4.0.1 (commit: v4.0.1) 
- Datasource:  InfluxDB V1.1.0
- Grafana OS:  Ubuntu Server  16.04.1 LTS
- Action:  Created new graph.
- Anticipated Result:  Graph would update (almost) immediately after datasource updates
- Actual Result:  Graph update lags almost 2 minutes behind creation of new datapoints in influxdb.

Fresh installation.  Have only ONE data point in influx.  (temperature measurement).  A remote temp reading is being sent via UDP to influxdb.  I can see by refreshing "select * from temp" that influx is receiving the data and logging it virtually instantly.

In grafana, I have 5 second auto-refresh set and it takes 2-3 MINUTES before changes reflected in the logged influxdb data is reflected on the graph.

What is interesting however is that in the graphs configuration options, I go to "legend" and enable "current".  This value updates as expected.  ie as soon as data changes on influx, this value is updated in grafana on the next (5sec) refresh.  Only the actual GRAPH itself lags behind terribly.

Group by time interval is:  >5s
I never had this issue prior to upgrading to Grafana 4x.  Graphs used to update almost immediately.

**Comment by torkelo** [comment]
this is probably due to a time difference between your browser computer time and the time of the sensor  or influxdb server

**Comment by 2000jago** [comment]
I had hoped it would be something so simple, but no.  The the device that sends the udp packet to influx is not time aware.  Influx timestamps the entry in the database the moment it's received.  Influxdb and grafana are running on the same machine and it's time is derived from NTP sync.  
The machine my browser runs on is synched to the same NTP server.  Times are confirmed identical.

Another "strange" behavior I have since noticed:
If I disable the device sending the UDP packet, obviously influxdb stops receiving data immediately and the graph stops accordingly.  
If I then reactivate the device, packets are immediately sent to influx again and it starts writing them to the database. In grafana however, only the "current" value (in the legend beneath the graph) is updated and in instantaneous sync with the values in influx.  It takes some time (about 2 minutes) for the graph to start graphing again.
I can "force" it to start working by restarting the server and grafana will immediately start graphing as soon as influxdb is started.  

I don't understand how it's possible that the legend "current" value is able to read the values from influx in near real-time, yet the graphing function itself lags terribly.

**Comment by torkelo** [comment]
Please open chrome dev tools and network tab and inspect data returned from your query.
