### ISSUE TITLE
Alerting: Telegram contact point options

### ISSUE THREAD

**Issue by MattKobayashi** [grafana/grafana#68167]
**What is the chore?**:
Several [parameters](https://core.telegram.org/bots/api#sendmessage) for the Telegram API's `sendMessage` method are unable to be configured in Grafana when using Telegram as a contact point for alerts. Useful ones to be able to configure would be `disable_web_page_preview` and `protect_content`.

**Comment by usmangt** [comment]
Hi @MattKobayashi,

Thanks for opening this issue.


Please review the submission template and include more details:

* What Grafana version and what operating system are you using?
* What is your datasource?
* **What** are you trying to achieve?
* **How** are you trying to achieve it?
* What happened?
* What did you **expect** to happen?
* Can you copy/paste the configuration(s) that you are having problems with?
* Did you receive any errors in the Grafana UI or in related logs? If so, please tell us **exactly** what they were.
* Did you follow any online instructions? If so, what is the URL?

**Comment by grobinson-grafana** [comment]
Hi! 👋 Thanks for reporting this issue! I don't see a reason we shouldn't support this in Grafana. Would you like to open a pull request in [github.com/grafana/alerting](https://github.com/grafana/alerting) for this change and we would be more than happy to review it 🙂
