### ISSUE TITLE
bug - connection to datasource hangs

### ISSUE THREAD

**Issue by CJosePhD** [grafana/grafana#6817]
I just built grafana 4.0.1 build completed fine no issues. but when I try to connect to a data source grafana hangs - no errors - just hangs. 

I built grafana v3 no connection issues with that build.

Any suggestions?

**Comment by CJosePhD** [comment]
The build is on a mac running El Capitan

**Comment by bergquist** [comment]
Any info in the log file? You can find it in data/logs

**Comment by CJosePhD** [comment]
I looked info messages only nothing to indicate a problem.

**Comment by torkelo** [comment]
Closing this due to lack up updates / info.
