### ISSUE TITLE
Time range and max data points wrapped in options

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#68190]
Have a read-only summary of time range and max data points. When the options button is clicked, a popup appears where these can be edited.
Use the Time selector that is used for Dashboards.

<img width="624" alt="Screenshot 2023-05-10 at 12 07 33" src="https://github.com/grafana/grafana/assets/33540275/06cf2ef7-0286-4948-bd08-e75ef33744b6">

**Comment by VikaCep** [comment]
> Use the Time selector that is used for Dashboards.

We can't use the same time picker that is used in Dashboards as that one allows for absolute time intervals which is something we don't support in Alerting. For this query editor, we need to use the `RelativeTimeRangePicker` as we've been using before. More info here https://raintank-corp.slack.com/archives/C04LG9N6R4J/p1688066124283789
