### ISSUE TITLE
[Feat Req]: InfluxDB Use retention policy when doing explore queries (lookup fields / tags)

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#6819]
Using Grafana v4.0.0 and influx v1.1.1 as the source if you try to build a query on a retention policy other than the default the query builder fails to work.

The reason for the failure is it doesn't include the specified retention policy in the build queries.

For example if you set the retention policy to autogen (one of the names for the default retention policies) then it still sends metadata queries such as the following without the given retention policy:
```SHOW TAG KEYS FROM "nginx"```
This returns no results.

Instead it should use the provided retention policy:
```SHOW TAG KEYS FROM "autogen"."nginx"```

The same happens for fields too which should be:
```SHOW FIELD KEYS FROM "autogen"."nginx"```

**Comment by torkelo** [comment]
if you use a default retention policy then it wont be added to the query

Sounds similar to
https://github.com/grafana/grafana/issues/4347

**Comment by usdin** [comment]
I am facing same issue.In Influxdb 1.1 show field keys query returns keys for specific retention-policy, and grafana doesn't pass retention policy in get tags/fields query. Here I am writing points to non-default retention policy **thirty_days**.
![influxsc](https://cloud.githubusercontent.com/assets/17239584/20881559/ecfecc9c-bb02-11e6-9ae6-3ba3e9d8a737.png)

**Comment by torkelo** [comment]
and if you select thirty_days in the retention field, is that retention policy not used when fetching keys or fields?

**Comment by stevenh** [comment]
Confirmed, even if you select the retention policy in the retention field it doesn't fetch data for the explore queries using that retention policy.

If you manually create the query using edit mode it all works as expected its purely the explore queries which don't.

To make it simple I'd say its acceptable to have it always use the retention policy listed in the retention field. Otherwise you'd need to constantly check if the policy was the default or not as its not name based its a property on the retention policy so you can have a retention policy named "default" which isn't actually the default.

As an extension to this it would be nice to be able to set the default retention policy on influx datasources.

**Comment by mnietz** [comment]
I can also confirm the behaviour.

Also for field names and older Version of Grafana and InfluxDB, see: #6587 for details.

**Comment by omki2005** [comment]
I can also confirm this behaviour. Are there any plans to implement this?

**Comment by phemmer** [comment]
Just FYI, this got duplicated in #9473 and resolved by 37409163b9a2a823298762f28d0d4b5e61ea4ca1
