### ISSUE TITLE
MSSQL Datasource not working with Public Dashboards

### ISSUE THREAD

**Issue by julb** [grafana/grafana#68237]
### 
# What went wrong?

**What happened**:

I have a dashboard using MSSQL Datasource to render some charts.
The dashboards works perfectly.
When I share it publicly with a link, no data is showing up and an error is raised with "Internal Server Error". 

The grafana logs:

```
logger=publicdashboards.service t=2023-05-10T14:50:35.425490743Z level=error msg="Error querying datasources for public dashboard" error="data source not found" datasources=[mssql]

logger=context userId=1 orgId=1 uname=admin t=2023-05-10T14:50:35.425618937Z level=error msg= error="unexpected error type [*errors.errorString]: data source not found" remote_addr=[redacted] traceID=

logger=context userId=1 orgId=1 uname=admin t=2023-05-10T14:50:35.42571335Z level=error msg="Request Completed" method=POST path=/api/public/dashboards/[redacted]/panels/5/query status=500 remote_addr=[redacted] time_ms=403 duration=403.946117ms size=48 referer="https://[redacted]/public-dashboards/[redacted]?orgId=1&refresh=5m" handler=/api/public/dashboards/:accessToken/panels/:panelId/query
```

**What did you expect to happen**:

The dashboard should work when shared publicly.

### 
# How do we reproduce it?

**Step 1**:

- Provision a MSSQL Server datasource using config file.

**Step 2**:

- Create a dashboard and insert a chart using the MSSQL datasource.

**Step 3**:

- Share the dashboard publicly. You should see Internal Server Error.

### 
# What Grafana version are you using?

v9.5.1 (bc353e4b2d)

### 
### Grafana Platform?

Kubernetes

### User's OS?

MacOS Big Sur

### User's Browser?

Google Chrome

### Is this a Regression?

None

### Are Datasources involved?

Microsoft SQL Server

### Anything else to add?

Both datasource and dashboards are actually provisioned.
We tested by creating it manually and we face the same issue.

**Comment by usmangt** [comment]
Hi @julb,

Thanks for opening this issue.

Is it only reproducible on MSSQL Data Source OR also on others e.g. MySQL etc?

**Comment by usmangt** [comment]
Could you please copy/paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu?

This will help us mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. 

Thank you!

Here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by julb** [comment]
After digging, we managed to make it work. If it can help someone:

On the image below:
- Left is working fine with classic dashboards & public dashboards
- Right is working fine with classic dashboards but NOT with public dashboards
![image](https://github.com/grafana/grafana/assets/502505/4059515d-5f25-4e0e-bbf0-95f589d34e53)

Everything is OK by relying exclusively on UIDs.

Apologies for the false positive and thanks again for your help.

Regards,

**Comment by Centaro0** [comment]
That's it!
