### ISSUE TITLE
[Feature request] The query quantity should be extended beyond the length of English alphabet

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#6824]
My use case requires me to add over a hundred of hidden queries for later use their refId inside sumSeries().
It seems to be impossible to do so as the refId is limited to 26 letters of English alphabet.
![image](https://cloud.githubusercontent.com/assets/12322967/20877293/b1da2f1e-bad8-11e6-95c0-d2f57fc989bf.png)

**Comment by torkelo** [comment]
26 metric queries per panel seems like a high limit. Especially given that all time series support some form of wildcard / regex / glob expression that allows you to query multiple series in one query. 

https://github.com/grafana/grafana/issues/2087
