### ISSUE TITLE
Cannot reach the login screen of grafana.

### ISSUE THREAD

**Issue by sonsamuels** [grafana/grafana#6826]
Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

Grafana v4.0.1 
Graphite
Debian jessie

Tried to follow this installation guide: 
https://www.linode.com/docs/uptime/monitoring/deploy-graphite-with-grafana-on-ubuntu-14-04

expected result:
Installed grafana

Nothing happend.

Hello guys,
I am completely new on this forum so please dont burn me if I post wrong topic or issue.
The thing is that I am trying to install the grafana for two days right now and still cannot get the grafana page loaded in my browser. I went through the guide mentioned above but still no success.
The working point where I ended was that I could create a sample data in Graphite and see new test cound metric (step before grafana installation). 

But once I instal the grafana, I cannot see login page of it when I write localhost, or 127.0.0.1 ip or tried to reach from outside IP. used all ports which were mentioned in the guide: 80,8080,3000,5432.... 
Nothing helped.

Do you have any hints where should I have a look ? or how to check if the grafana was installed correctly ?

Many thanks for all reply.

**Comment by torkelo** [comment]
please issue questions to the mailing list, https://groups.io/g/grafana
