### ISSUE TITLE
Stat Panel: Ability to hide fields but still reference them in data links

### ISSUE THREAD

**Issue by raj-shah14** [grafana/grafana#68275]
**Why is this component needed**: This is currently supported in Table panel, can it be supported in Stat Panel

___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
Would allow Data links to open a specific deployment using this Id when clicked on Stat panel having value Completed/Failed.
___
- [x] Post screenshots possible.
- [ ] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

![image](https://github.com/grafana/grafana/assets/25533503/ca0863fd-eeff-4df4-8fef-da9b8c882d94)
I can hide the Guid value using Transform but not able to reference that in data links using ${__data.fields.RolloutId} if it is hidden.

**Comment by DeclanGS** [comment]
This is very needed, i'm really surprised the issue closed without additional people backing up the demand. Doesn't seem like it would even be hard to fix.
