### ISSUE TITLE
[Bug] Permanent load of some graphs

### ISSUE THREAD

**Issue by leoleovich** [grafana/grafana#6827]
- What Grafana version are you using? - 4.0.1-1480694114 (same problem was in 3.1)
- What datasource are you using? - Graphite
- What OS are you running grafana on? - Debian Jessie
- What did you do? - I have a dashboard with absolutely the same graphs, but with different time resolution. (Daily, Weekly, Monthly). Query is totally the same. Only the last (Monthly) graphs are loaded. If I click *Edit* on one of these (unloaded) graphs and then click on refresh sigh (↺), data will be shown.
- What was the expected result? - see dashboard fully loaded
- What happened instead? - 499. Part of graphs (always the same) refused to load
![image](https://cloud.githubusercontent.com/assets/4749052/20882575/facc7f8e-bae1-11e6-9b3d-f622be5e76a7.png)

In nginx logs I see:

```
212.53.182.234 - leoleovich [05/Dec/2016:11:52:58 +0100] "POST /api/datasources/proxy/3/render HTTP/1.1" 499 0 "https://gentime.domain.com/dashboard/db/dashboard-g" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 YaBrowser/16.10.0.2309 Safari/537.36"
212.53.182.234 - leoleovich [05/Dec/2016:11:52:59 +0100] "POST /api/datasources/proxy/3/render HTTP/1.1" 200 13678 "https://gentime.domain.com/dashboard/db/dashboard-g" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 YaBrowser/16.10.0.2309 Safari/537.36"
```

You can also see error on JS side:
![image](https://cloud.githubusercontent.com/assets/4749052/20882868/545da27a-bae3-11e6-8c31-1574a6e2a61a.png)

Nothing helpful in logs of grafana.

**Comment by torkelo** [comment]
looks like query failures, have you checked the logs from your time series database?

Also in chrome dev tools look at the response from those red (failed queries)

**Comment by leoleovich** [comment]
@torkelo, I enabled Debug logging on graphite itself, no errors. Furthermore, the error is 499 and it is clearly says: cancelled, which means client side closed a connection before.

**Comment by leoleovich** [comment]
@torkelo, answering your question - "response" is empty, because client did not want for finishing the request.

**Comment by torkelo** [comment]
strange, can you share the json of the dashboard? are you using row repeats? not seeing any time range override in the graphs, so how are they targeting different time ranges?

**Comment by leoleovich** [comment]
@torkelo, thank you, you gave me a good hint!
I am generating this dashboards and *id* of a graphs was repeating from Panel to Panel.
1) 1 2 3 4
2) 1 2 3 4
3) 1 2 3 4
That is why it loaded only the last one and cancelled the first 2.
I wonder how it worked before update (3.0 it worked) and if it is needed to have those ids really different on different Panels.

BTW, time override is hidden (nice checkbox).

**Comment by torkelo** [comment]
ok, mixing panel repeat and row repeat is not fully supported
