### ISSUE TITLE
Dashboard: panel's tooltip is not responsive

### ISSUE THREAD

**Issue by anavss** [grafana/grafana#68288]
### 
# What went wrong?

**What happened**:

  - As shown on the screenshots below (1440px and 1024px),the panel's tootip is not acting responsively. 

![Screenshot 2023-05-11 at 11 24 26 AM](https://github.com/grafana/grafana/assets/86568531/37c3caba-26e7-4412-94ef-2fd3aed55f9d)
![Screenshot 2023-05-11 at 11 23 58 AM](https://github.com/grafana/grafana/assets/86568531/6ddc7b4f-1146-468f-8b33-fd27b150c574)

**What did you expect to happen**:

  - To either wrap the text when the viewport changes, or align to the right so that it's positioned within the boarders of the panel 

### 
# How do we reproduce it?

**Step 1**:

- Open t[his dashboard](https://ops.grafana-ops.net/goto/GsxjwI84g?orgId=1)

**Step 2**:

- Hover over the MMTR panel's tooltip on the first row

### 
# What Grafana version are you using?

Grafana v10.1.0-55602pre (8ec5527479)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by polibb** [comment]
After looking into this, I got to 2 possible solutions: 
1. Adjust the [max width of the tooltip](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/utils/tooltipUtils.ts#L48). E.g. set the max width of the tooltip to be the width of the panel, and position the tooltip to start where the panel starts. Or less than the width of the panel, and position the tooltip within that much distance of the panel's most left border. 
2. Figure out if `react-popper-tooltip` supports using `preventOverflow` by [popper.js](https://popper.js.org/docs/v2/faq/#my-popper-is-bigger-than-the-viewport-what-do-i-do). It seems to me that this is not the case. 
They [do use VirtualElement](https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/usePopperTooltip.ts#L231) ([more about it](https://popper.js.org/docs/v2/virtual-elements/)), but it only acts on the tooltip positioning _after_ the tooltip is visible. 
So you can see that the tooltip is positioned correctly after a mouse move while it is open:

https://github.com/grafana/grafana/assets/13227501/1414a372-f6af-403f-8595-2c2deab66790

**Comment by iSatVeerSingh** [comment]
@anavss @polibb Please tell me how to reproduce this issue in the development environment.

**Comment by iSatVeerSingh** [comment]
@polibb I have reproduced this. I want to work on this. Please assign me.

**Comment by iSatVeerSingh** [comment]
I think You should use "react-popper" instead of "react-popper-tooltip" for the tooltip. Also "react-popper" is the official react wrapper from Popper.js and "react-popper-tooltip" hasn't been updated since last year. This issue may be happening because of react-popper-tooltip.

**Comment by polibb** [comment]
Maybe you're right, we are using 'react-popper' in most other places. Try it out and let's see how it goes 🙂

**Comment by iSatVeerSingh** [comment]
@polibb can you assign me. I want to work on this.
