### ISSUE TITLE
GeoMap: Marker symbol wrong size in Safari

### ISSUE THREAD

**Issue by rwdigia** [grafana/grafana#68296]
### 
# What went wrong?

**What happened**:

  - Marker symbol painted to canvas is same as source marker SVG and error "ResizeObserver loop completed with undelivered notifications." appeared in console.

**What did you expect to happen**:

  - Marker symbol shrunk to fit, no error in console.

Chrome
![chrome](https://github.com/grafana/grafana/assets/100279520/6e41bc2c-d45d-49a0-af1a-7df64b7b4ce9)

Safari (before reload)
![safari_before_reload](https://github.com/grafana/grafana/assets/100279520/ee5a13a0-c7a1-47c4-a942-1e156052df17)

Safari (after reload)
![safari_after_reload](https://github.com/grafana/grafana/assets/100279520/48d3b9e3-ea3e-468b-96d9-f01d84460455)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add a GeoMap panel with a datasource for markers.

**Step 2**:

- Add attached SVG as a marker icon.

![background](https://github.com/grafana/grafana/assets/100279520/3d0f0cc9-83b8-4d35-b91f-40b8f9ee9432)

**Step 3**:

- Load the page in Safari.

### 
# What Grafana version are you using?

v8.5.15

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

MacOS Monterey 12.5.1

### User's Browser?

Safari 15.6.1 (17613.3.9.1.16)

### Is this a Regression?

None

**Comment by usmangt** [comment]
Hi @rwdigia,

Thanks for opening this issue :+1: 

I will forward this to our Engineers so that they can investigate it and provide more information.
