### ISSUE TITLE
How to include current timestamp in Email subject line

### ISSUE THREAD

**Issue by shafeeq2207** [grafana/grafana#68299]
### 
# What went wrong?

Hi

Im trying to include the current timestamp or incident start time in email subject line so that each email is received as separate mail instead of mail thread.

### 
# How do we reproduce it?

The template that i tried.
```
{{ define “email.subject” }}
{{ .Status | toUpper }} - {{ .CommonLabels.alertname }} {{ .Alerts.Firing.StartsAt.Format “Monday, 2 January 2006 at 3:04PM” }}
{{ end }}
```

Subject that I see: I’m getting only the “FIRING - TestAlert”

This `{{ .Alerts.Firing.StartsAt.Format “Monday, 2 January 2006 at 3:04PM” }}` part of the template is just returning empty in actual mail subject alert.

Any help in this would be appreciated. Is there any another option to send each email as separate one.

Grafana version: v9.4.3
OS: Ubuntu 20.04

**Comment by usmangt** [comment]
Hi @shafeeq2207,

No, this is currently not possible at the moment.


However, what you can try something like the following.

`{{ .Status | toUpper }} - {{ .CommonLabels.alertname }} {{ (index .Alerts.Firing 0).StartsAt.Format "Monday, 2 January 2006 at 3:04PM" }}`

The thing here is that the `.StartsAt` is available on an individual Alert not the ExtendedData structure. 

See [reference](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/reference/) for more details.

**Comment by grobinson-grafana** [comment]
Hi! :wave: @usmangt is correct! You can include the StartsAt timestamp of the first, or all alerts, in the notification - but not the current time when the notification was sent.
