### ISSUE TITLE
AzureMonitor: Current resource selection grows over resource selection table

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#68306]
### 
# What went wrong?

**What happened**:

  -  When choosing multiple resources using the resource picker, eventually the current selection grows beyond the table where you can select new resources, leading to the inability to select more.

**What did you expect to happen**:

  - Any number of resources should be selectable.

### 
# How do we reproduce it?

Using the Azure resource picker continue selecting resources of the same type and eventually you will not be able to select more.

### 
# What Grafana version are you using?

Latest

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by eleijonmarck** [comment]
I found a relevant document that mentions a bug fix related to the Azure resource picker:

1. [Bug fixes - AzureMonitor: Fix issue where resource group name is missing on the resource picker
button.](https://github.com/grafana/grafana/pull/36400)

However, this document does not directly address the issue of selecting multiple resources using the resource picker. The previously provided
issue and PRs might be more helpful in this case:

1. Issue: [Azure Monitor: Allow selection of multiple resources of the same type](https://github.com/grafana/grafana/issues/55372)
2. PR: [Azure Monitor: Add support for multiple template variables in resource picker](https://github.com/grafana/grafana/pull/46215)
3. PR: [Azure Monitor: Add search feature to resource picker](https://github.com/grafana/grafana/pull/48234)

Please review these resources to see if they provide a solution or any relevant information for your issue.

**Comment by aangelisc** [comment]
Hey @eleijonmarck, sorry this is an internal issue I've already forwarded it on to my squad 😄 I'll add images to make it clear!

**Comment by eleijonmarck** [comment]
in case it helps :D

**Comment by eleijonmarck** [comment]
@aangelisc could you share with me if these links were helpful, if any?
