### ISSUE TITLE
[Feature Request] Dashboard Query

### ISSUE THREAD

**Issue by txisme** [grafana/grafana#6830]
Hey, anyone thinks that it s good idea to have a query place for all graphs in a dashboard? Something like Kibana has, a place to put an expression that affects all graphs in a dashboard the same way.

For example i am monitoring several machines and have a dashboard per machine. But every time i create a new dashboard for a new machine, i have to change the machine name in all the graphs.

In a similar way, also would be useful to have a query for all queries of one graph. For example, instead of adding the same filter in all queries of a graph, there could be a place where we have an option like "apply all".

**Comment by torkelo** [comment]
Something like this as existed in Grafana for a very long time, almost v1 I would say. 

The feature is called templating. allows you to create variables / filters that you can use in your queries to quickly change what metric all graphs look at, or change group by, time span bucket, query filter etc anything. 

http://docs.grafana.org/reference/templating/

Example graphite:
http://play.grafana.org/dashboard/db/graphite-templated-nested

Example elasticsearch:
http://play.grafana.org/dashboard/db/elasticsearch-templated

**Comment by txisme** [comment]
Yeah i tried that and although all the machines appear in the list, when i go through them the graph doesn't change, it simply show the average of the value of all machines.

**Comment by torkelo** [comment]
then your query is wrong. You need to group by the field/tag if you want a series per value (in field/tag)

**Comment by txisme** [comment]
yeah i fixed it, thank you!
