### ISSUE TITLE
Azure Monitor link back to portal broken for Log analytics queries

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#68342]
### 
# What went wrong?

**What happened**:

  - After crafting a dashboard with either Log Analytics and using the in built link to take me back to portal, the page is broken and failing to select the right scope

<img width="866" alt="image" src="https://github.com/grafana/grafana/assets/20448042/a7ba2ac9-8c4e-4b09-83cc-1a74be8431bb">

**What did you expect to happen**:

  -  For the link to pass the right scope to Azure portal

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and wright Azure Monitor Logs query

**Step 2**:

- click on any data point so that you can be linked back to portal

### 
# What Grafana version are you using?

9.4.10

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows 11

### User's Browser?

Edge

### Is this a Regression?

Yes

### Are Datasources involved?

Azure Monitor Datasource

**Comment by usmangt** [comment]
Hi @jcolladokuri,

Thanks for opening this issue.

Could you please provide us with the backend logs (the default location in Linux is `/var/log/grafana/grafana.log`) so that we can have more information about the error message?

**Comment by avidhanju** [comment]
@usmangt we see this happening in Azure Managed Grafana where customers don't have access to backend logs. Also, could you explain how this is a backend issue? Seems like the link back to Azure Portal is not selecting the correct resource. If anything, this seems like an Azure Monitor plugin's frontend/resource picker issue.

**Comment by usmangt** [comment]
Thanks, I was just interested to see if anything gets recorded in the logs. I have now forwarded it to the team so that they can look into it.

**Comment by aangelisc** [comment]
The fix for this was in #65482, however due to what may have been a GitHub outage the backport was never created. I've manually backported this in #68523 and it should be available in the next release of 9.4.x. If there are no other concerns we can close this issue 😊

**Comment by avidhanju** [comment]
@aangelisc feel free to close this. Will wait for 9.4.9 or 9.4.10 to validate.
