### ISSUE TITLE
[v9.5.2] AzureMonitor: Fix template variables in subscription field

### ISSUE THREAD

**Issue by timo-42** [grafana/grafana#68341]
### 
# What went wrong?

**What happened**:

Same issue as #63831

The same issue occurs when using a graph query and variable value selector.
It is fine for v9.4.9-ubuntu/v9.5.0-ubuntu, but does not work in v9.5.1-ubuntu/v9.5.2-ubuntu container image. 
In both cases I use provisioning with a datasource.yaml and a Managed Identity on Azure(Also doesn't work with a Service Principal locally).

Environment:
- Grafana version: v9.5.1/v9.5.2
- Data source type & version: Azure Monitor - assuming latest version
- OS Grafana is installed on: AKS cluster with custom Deployment
- User OS & Browser: Firefox

Background: I use a graph query to fill a variable with subscriptions, which fulfill a certain criteria

Example:
`
Resources
| where type=~ "Microsoft.DBforPostgreSQL/flexibleServers"
| distinct subscriptionId
| join kind=inner (
            resourcecontainers
                    | where type == 'microsoft.resources/subscriptions'
                    | project subscriptionId, subscriptionName = name)
    on subscriptionId
| project subscriptionName
`

**What did you expect to happen**:

Graph query is per executed on all subscriptions, not on the randomly(or manually) chosen one.
<img width="562" alt="Screenshot 2023-05-11 at 23 35 39" src="https://github.com/grafana/grafana/assets/10377071/0f317919-3801-46f4-a7d4-8956dac5ccb6">

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add Azure Monitor as a datasource

**Step 2**:

- Create a Dashboard and add a variable with Data Source = Azure Monitor and Query Type = Resource Graph
- Let Subscription Empty
- Add the query from above

**Step 3**:

- Run query
- 

### 
# What Grafana version are you using?

v9.5.2

### 
### Grafana Platform?

Kubernetes

### User's Browser?

Firefox

### Is this a Regression?

Yes

### Are Datasources involved?

Azure Monitor

**Comment by timo-42** [comment]
Found the problematic commit: https://github.com/grafana/grafana/commit/900c18ef5b997ba05e0ad75783a0dfdc1a3f478e

**Comment by aangelisc** [comment]
Ideally it sounds like a default `All` option is preferred. At the moment a workaround is to use a template variable containing all subscriptions as the value in this field.

**Comment by aangelisc** [comment]
Fixed by #79582
