### ISSUE TITLE
CloudWatch: Insights query fails in Grafana if math expression used

### ISSUE THREAD

**Issue by anurag-patnaik** [grafana/grafana#68340]
### 
# What went wrong?

**What happened**:

  - When we create a Cloudwatch metric query in a Grafana panel with custom variable for region, the query works. However, if we add a math expression to the query, the query fails with "Query Data Error" because according to the query inspector the region variable cannot be resolved.

**What did you expect to happen**:

  - We expect the query with a math expression to complete successfully.
![03_screenshot_of_the_dashboard](https://github.com/grafana/grafana/assets/949305/40100d0c-39b4-4dd4-bf1e-7863242d899d)

### 
# How do we reproduce it?

**Step 1**:

- Create a dashboard with 3 panels that display "CloudWatch - PutmetricData" call counts from the "AWS/Usage" metric.

**Step 2**:

- The first panel uses the "$region" variable in the target definition and works fine.

**Step 3**:

- The second panel adds a simple "$A + 500" math expression with fixed region - ex: "eu-west-2" - and works.

**Step 4**:

- The third panel is the same as the second one, but replaces the fixed region with the "$region" variable. And it does not work. More precisely: Math expression does not work on a source that uses variables.

### 
# What Grafana version are you using?

v8.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's OS?

Amazon Linux 2

### User's Browser?

Google Chrome - Version 112.0.5615.137 (Official Build) (x86_64)

### Is this a Regression?

No

### Are Datasources involved?

CloudWatch

**Comment by usmangt** [comment]
Hi @anurag-patnaik,

Thanks for opening this issue.

This seems to be a known [issue](https://github.com/grafana/grafana/issues/63227) which was fixed in v9.4.7

Please update to the above-mentioned version (or higher) and then it should get resolved on your server.
