### ISSUE TITLE
[Bug] - built Grafana 4.0.1 from source can't connect to datasource, screen hangs

### ISSUE THREAD

**Issue by CJosePhD** [grafana/grafana#6835]
running on Mac El Capitan - 

The build worked fine no errors

grafana started not issues when I tried to update data source, just hung.

There are no errors in the log.

I have two datasources, graphite and opentsdb, running an a test server named opentsdb. but work from Grafana v3, which I built from source also., neither work in the new release.

**Comment by bergquist** [comment]
@torkelo any chance you could test this on your macbook?

**Comment by CJosePhD** [comment]
what additional information do you need?

**Comment by torkelo** [comment]
strange, works on Mac here, will check what version. Can you open chrome dev tools check network tab for error and console for errors?
