### ISSUE TITLE
Zooming shotcut command not working 

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#6837]
Please include this information:
- What Grafana version are you using?    4.0
- What datasource are you using?           InfluxDB
- What OS are you running grafana on? Linux
- What did you do?

I opened a graph from 2 dyas ago until now. Then I pressed "t z" to zoom out (Note: the toolbox still says to press Ctl-Z, but this does not seem to work anymore). 

- What was the expected result?

Zoom from now till 4 days ago.

- What happened instead?

The zoom range went from=NaN&to=NaN. No graph was shown.

**Comment by utkarshcmu** [comment]
+1
