### ISSUE TITLE
Navigation: Breadcrumbs do not update when navigating between two dashboards with the same name

### ISSUE THREAD

**Issue by pbrissaud** [grafana/grafana#68384]
### 
# What went wrong?

**What happened**:

- In the new UI, when navigating from a dashboard to another dashboard **named the same but in an another folder**, the breadcrumb isn't refresh so it display the wrong folder
  
**What did you expect to happen**:

  - The breadcrumb is refreshed after each navigation and show the current folder

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and go a dashboard called "X" in the folder "A"

**Step 2**:

- The breadcrumb shows *Dashboard > A > X*
- Go a dashboard  named "X" in the folder "B"

**Step 3**:

- The breadcrumb always shows *Dashboard > A > X*
- Go a dashboard named "Y" in the folder "B"

**Step 4**:

- The breadcrumb shows *Dashboard > B > Y*
- Return to  dashboard named "X" in the folder "B"

**Step 5**:

- The breadcrumb always shows *Dashboard > B > X*

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

MacOS Venture 13.3.1

### User's Browser?

Arc Browser (Chromium)

### Is this a Regression?

None

### Anything else to add?

Screen recording of the bug : 

https://github.com/grafana/grafana/assets/27202456/f4228263-50f6-4262-947b-b75465415433

**Comment by usmangt** [comment]
Hi @pbrissaud,

Thanks for opening this issue.

Is it only reproducible when using the quick search bar?

**Comment by pbrissaud** [comment]
Hi,

Can't reproduce the bug using the sidebar so I think it's only using the quick search bar !

**Comment by PatrickBaus** [comment]
I can confirm the bug to be also present when clicking links configured via Settings->Links.

This only happens when the dashboard name, configured via Settings->General->Name, is identical. When the dashboards have a different name it works as intended.

Running Grafana v9.5.2 (cfcea75916).

**Comment by tskarhed** [comment]
There seems to be two causes for this issue.
1. When the navigation happens, the updated `pageNav` does not have the updated URL, but it has the updated parent folder
2. `navItemsAreTheSame` does not take the parent into account.

Fixing 2 would solve this issue, but it would be good to know why the URL doesn't get updated.
