### ISSUE TITLE
plugins: grafanaDependency changes on install

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#68395]
### 
# What went wrong?

**What happened**:

  - [ImageIt](https://grafana.com/grafana/plugins/pierosavi-imageit-panel/) v1.0.7 (latest) declares its `grafanaDependency` as `>=7.x.x <=8.x.x`.
  - When viewing in the catalog for Grafana 9.5.1, it detects latest compatible version as 1.0.5 with the dependency as `>7.x.x`
  - After install, the shown dependency expands to `>=7.x.x <=8.x.x`

**What did you expect to happen**:

  - Should present a consistent Grafana Dependency 

**Additional information**

This video shows the experience locally

https://github.com/grafana/grafana/assets/19860021/24c1d887-d860-4d3a-a6bc-113f84e1ce7f

In Grafana Cloud

- After finding ImageIT in the catalog and installing via Grafana.com you are presented with the success message:
<img width="877" alt="Screenshot 2023-05-18 at 16 00 47" src="https://github.com/grafana/grafana/assets/19860021/b0f81718-0340-427c-b87b-0fbff36e3398">

This implies its 1.0.7 installed, which is not compatible...

and possibly as a result, navigating back to the catalog, it is not showing as installed.
<img width="809" alt="Screenshot 2023-05-18 at 16 02 44" src="https://github.com/grafana/grafana/assets/19860021/f0b44c5d-94de-42a3-ab37-e4b59c267f87">

### 
# How do we reproduce it?

See description

### 
# What Grafana version are you using?

9.5.1 locally, Grafana v9.5.2-cloud.2.0cb5a501 (cfcea75916) in Cloud

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by tolzhabayev** [comment]
Not a bug, explained in our internal chat...

**Comment by sympatheticmoose** [comment]
Original issue was indeed not a bug, yet more be lurking 😄 updated the issue description.

**Comment by tolzhabayev** [comment]
Probably related https://github.com/grafana/grafana/issues/68397

**Comment by oshirohugo** [comment]
The first part was solved in https://github.com/grafana/grafana/pull/75074

The second part, the problem in grafana cloud, is lack of version validation in grafana.com. As we don't do the installation with the latest compatible version and neither validate it, hosted-grafana performs the whole installation process with the wrong version. All the data is saved as the plugin had been installed, the new instance starts in the background, when the new instance starts, the actual installation is attempt (according to the persisted data) and it fails. As we still have the old instance, we can't see it, and as the data is already persisted, we see the plugin as installed in grafana.com.

To solve the second part we would need to add a compatible version find in grafana.com catalog before installation, and also it would be good to do a validation in the backend to check if the plugin version is compatible with grafana version. The first part would be automatically done once we do https://github.com/grafana/grafana-plugins-platform-team/issues/21 and the second part would be easier to implement if we solve https://github.com/grafana/grafana-plugins-platform-team/issues/21 as well. So I propose to wait for it until we fully solve this issue.

@sympatheticmoose @tolzhabayev thoughts?

**Comment by sympatheticmoose** [comment]
Its perfectly reasonable to wait 👍

**Comment by tolzhabayev** [comment]
@oshirohugo @sympatheticmoose  https://github.com/grafana/grafana-plugins-platform-team/issues/21 is done, not sure if we can now do it more easily now.
