### ISSUE TITLE
Grafana returning wrong query result after upgrading to 9.5

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#68390]
### 
# What went wrong?

I have a panel with the following Influx 1.8 query:
````
SELECT * from (
SELECT last("percent_packet_loss") as packetloss FROM "ping" WHERE ("bucket" = 'switches' ) AND $timeFilter
) where "packetloss" > 0
GROUP BY "name"
````

When using grafana 9.3, with STAT PANEL, it works fine. Currently returning "13".

I upgraded to grafana 9.5 and this query is now broken., It keeps oscilating the returned value. from 1, 3, 6, 8, every time the dashboard refreshes.

Downgreading to grafana 9.3 fixes the issue.

![image](https://github.com/grafana/grafana/assets/8555749/6b8757bc-a033-4d07-b5f2-93ec72cca940)

### 
# How do we reproduce it?

See explanation above

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

panel json:

````
{
  "id": 32,
  "gridPos": {
    "h": 4,
    "w": 3,
    "x": 21,
    "y": 5
  },
  "type": "stat",
  "title": "Total Switches DOWN",
  "transformations": [
    {
      "id": "calculateField",
      "options": {
        "mode": "reduceRow",
        "reduce": {
          "reducer": "count"
        },
        "replaceFields": true
      }
    }
  ],
  "datasource": {
    "uid": "_rojVbO4k",
    "type": "influxdb"
  },
  "pluginVersion": "9.3.14",
  "timeFrom": "1m",
  "hideTimeOverride": true,
  "fieldConfig": {
    "defaults": {
      "mappings": [
        {
          "options": {
            "0": {
              "index": 0,
              "text": "0"
            }
          },
          "type": "value"
        },
        {
          "options": {
            "match": "null+nan",
            "result": {
              "index": 1,
              "text": "0"
            }
          },
          "type": "special"
        }
      ],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "#0086aa",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 1
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "unit": "none"
    },
    "overrides": []
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "textMode": "value",
    "colorMode": "background",
    "graphMode": "none",
    "justifyMode": "center",
    "text": {}
  },
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "_rojVbO4k"
      },
      "query": "SELECT * from (\nSELECT last(\"percent_packet_loss\") as packetloss FROM \"ping\" WHERE (\"bucket\" = 'switches' ) AND $timeFilter\n) where \"packetloss\" > 0\nGROUP BY \"name\"",
      "rawQuery": true,
      "refId": "A",
      "resultFormat": "time_series"
    }
  ],
  "transparent": true
}
````

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 22.04

### User's Browser?

Firefox

### Is this a Regression?

Yes

### Are Datasources involved?

InfluxDB 1.8

**Comment by usmangt** [comment]
Hi @yurividal,

Thanks for opening this issue.

 
Could you please copy/paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu FOR BOTH versions i.e. v9.3 and v9.5?

This will help us mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. 

Thank you!

Here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by yurividal** [comment]
Here are both debug files:

[9.5-debug-Total Switches DOWN-2023-05-21 20 35 44.json.txt](https://github.com/grafana/grafana/files/11525374/9.5-debug-Total.Switches.DOWN-2023-05-21.20.35.44.json.txt)

[9.3-debug-Total Switches DOWN-2023-05-21 20 32 55.json.txt](https://github.com/grafana/grafana/files/11525375/9.3-debug-Total.Switches.DOWN-2023-05-21.20.32.55.json.txt)

**Comment by yurividal** [comment]
@usmangt is this data enough for what you need? I need to rollback to 9.3, so if you need anything else, i wont be able to provide.

**Comment by usmangt** [comment]
Thanks.

I can see the status of this issue as it is already queued and now our Engineers will have a look and might be able to tell more details about it.

**Comment by codeincarnate** [comment]
Removing the stat panel label from this. There's no transformation of that sort in the stat panel that would cause the value to change. Almost certainly this is due to a change in InfluxDB.

**Comment by yurividal** [comment]
> Removing the stat panel label from this. There's no transformation of that sort in the stat panel that would cause the value to change. Almost certainly this is due to a change in InfluxDB.

The influxDB version wasn't changed between these 2 tests.

**Comment by codeincarnate** [comment]
Thanks Yuri! Sorry, I didn't mean InfluxDB itself but rather the InfluxDB datasource which is where I suspect the problem is here. The stat panel itself is pretty dumb actually! 😆 

It renders this using the `BigValue` component [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/stat/StatPanel.tsx#L35) which simply displays the given formatted display value. I doubled checked and [history wise](https://github.com/grafana/grafana/commits/33fd83f7e3c9f3f22d338499dfe204802d7a8dbc/public/app/plugins/panel/stat/StatPanel.tsx) there haven't been any significant changes to the panel (as far as I can tell) for quite awhile. Pretty sure this is due to a change in the datasource plugin or perhaps in how the macro in your query is working.

**Comment by gtk-grafana** [comment]
@itsmylife is this another issue from the backend migration we attempted with 9.5?

**Comment by itsmylife** [comment]
@gtk-grafana No it is not related. I am investigating it further.

**Comment by itsmylife** [comment]
It looks like the problem is related to transformations. Based on the json's provided here https://github.com/grafana/grafana/issues/68390#issuecomment-1556270783 

But just to make sure that the transformations is culprit @yurividal could you please remove the transformation and compare the results? If they are the same we can only focus on the transformations side. 
Also another check might be sharing the data you get from network. So what I am asking is, with the existing configuration of the panel when you refresh what you get from the backend. You can see it over the network tab. Sharing both results for 9.3 and 9.5 will be helpful.

**Comment by yurividal** [comment]
@itsmylife it indeed seems to be an issue with the transformation.
These are screenshots of the panel with the transformation removed. They seem to be identical.

![image](https://github.com/grafana/grafana/assets/8555749/5a66ce66-4141-419e-b10b-edd56582c616)

![image](https://github.com/grafana/grafana/assets/8555749/0eeaa7f7-ea7e-44b5-ab96-d4efc05cd2e5)

**Comment by yurividal** [comment]
By the way, issue is still present in Grafana 10.0.1

**Comment by itsmylife** [comment]
@bohandley @LudoVio Could you please help me with this one?

**Comment by LudoVio** [comment]
can you send the data before and after transformation on both version ?

**Comment by yurividal** [comment]
> can you send the data before and after transformation on both version ?

Sure. Can you please describe the steps to pull the data you need? Im happy to do it

**Comment by LudoVio** [comment]
Where you got the previous data, you can have this tab too:

![image](https://github.com/grafana/grafana/assets/9373203/e93823f5-d72d-4cb2-906d-bf19bda68cf9)

There is a switch to see the data with or without transformation. And there is a button to download as csv.

Thanks

**Comment by yurividal** [comment]
Is there an email i can send it to? Im just a bit concerned because currently, the query results might include some sensitive info (hostnames and IPs). (Which was not the case when i first opened the bug report)

**Comment by LudoVio** [comment]
Can you create a minimal example and  obfuscate the data?

**Comment by yurividal** [comment]
[9.3_with_transformations.csv](https://github.com/grafana/grafana/files/12100366/9.3_with_transformations.csv)
[9.3_no_transformations.csv](https://github.com/grafana/grafana/files/12100367/9.3_no_transformations.csv)
[9.5_no_transformations.csv](https://github.com/grafana/grafana/files/12100368/9.5_no_transformations.csv)
[9.5_with_transformations.csv](https://github.com/grafana/grafana/files/12100369/9.5_with_transformations.csv)


Ok, here is the data.
At the moment, we have 2 switches down. The counter properly shows 2 on v9.3 but shows 1 on v9.5 (and above)

**Comment by LudoVio** [comment]
I checked with your data via "testdata" on versions: 
- 9.3.14 and 9.3.16
- 9.5.2 and 9.5.6

The results were all the good ones => 2

If the problem only appear on influxdb, I think you should definitely try to upgrade from 9.5.2 to 9.5.6 first.

It might be related to a field name matching conflict for influxdb datasource. To try if it is the case, manually select the fields you want the transformation to be applied on.

So here for example if you want only the 2 last columns, without the time one:
![image](https://github.com/grafana/grafana/assets/9373203/5de12348-e667-4db4-a59b-3edda64d0062)

**Comment by LudoVio** [comment]
Just to clarify, transformation is 100% frontend. Also the "reduce row" transformation is a row based operation, so interval should not be related

Is manually selecting fields change the result?

I tested with your csv data as input on the different version and always got the same result, which is 2.

I suspect that different data is sent to the transformation when the output is different.

Can you send the dataframe data as json ? CSV might have remove the important bit

![image](https://github.com/grafana/grafana/assets/9373203/9bd8a371-7cbd-406a-a7a2-e7a475fee349)

**Comment by LudoVio** [comment]
"Panel data" would also be useful

**Comment by yurividal** [comment]
I currently have zero downed switches in my environment, so unfortunately, I can't pull that data for you from my live environment. 
But, this should be really easy to replicate ony test environment, it's a simple ping sensor on telegraf, polling each switch with pings.

````
[[inputs.ping]]
  interval = "1s"
  method = "native"
  urls = ["192.168.31.111"]
  count = 3
  ping_interval = 0.3
  [inputs.ping.tags]
     name = "Name Of This Switch"
     type = "switch"
     bucket = "Building Name"
````

All you need is one of these for each IP you want to ping.

**Comment by leeoniya** [comment]
if the problem is frontend (transformations or viz panel) you can attach a panel debug snapshot that embeds the raw frame data as it comes out of the datasource frontend code.

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

**Comment by yurividal** [comment]
Ok, I've changed my visualiztion to show the total number of switches UP, instead of down, to be able to collect the data for you.

Here is a short video of the issue happening on v9.5
![ezgif-1-6e92d8aa78](https://github.com/grafana/grafana/assets/8555749/d55980cf-53ea-4126-9842-6f19c8b9ddca)


I have manually selected all 192 devices in the transformation, and indeed, it stops the mis-readings. Which further points into the the transformation being the issue.

**Comment by yurividal** [comment]
Ok, quick update:

I changed my query from:
````
SELECT * from (
SELECT last("percent_packet_loss") as packetloss FROM "ping" WHERE ("bucket" = 'switches' ) AND $timeFilter
) where "packetloss" > 0
GROUP BY "name"
````
to
````
SELECT COUNT("percent_packet_loss") FROM "ping" WHERE ("bucket" = 'switches') AND ("percent_packet_loss" > 0) AND $timeFilter
GROUP BY "name"
````
And it seems to be working now. 
Still doesn't explain why it worked on all previpus grafana versions and stoped working from version 9.5+

But, for me, i',=m just glad its working with this query, and i'll be able to keep my grafana up-to-date.

**Comment by LudoVio** [comment]
it could be due to the fields name coming from influxdb. If you dont specify any fields in the transformation, it tries to do some magic and decide which ones to use using some field matchers heuristic. Try to alias each field with specific names and see if there is a difference between version.

**Comment by itsmylife** [comment]
@yurividal Do you use `influxdbBackendMigration` enabled? Also could you please share a `.har` file with the query you had (problematic one) and the other one you updated (the one you get proper data)? I am happy that you found a workaround but I want to make sure everything is alright one our side.
