### ISSUE TITLE
[Bug] Ad-Filter from different dashboard leaks into another.

### ISSUE THREAD

**Issue by tevjef** [grafana/grafana#6839]
**- What Grafana version are you using?**
4.0.1

**- What datasource are you using?**
InfluxDB

**- What OS are you running grafana on?**
Linux

**- What did you do?**
One of my dashboards has an Ad-hoc filter. On 2 occasions when adding a new graph in an entirely separate dashboard I kept getting no results from my datasource. On further troubleshooting I noticed an errant `AND` in the `WHERE` clause (that's not in the edit mode string) which seems to corresponds to an aways activated ad-hoc filter in the other dashboard. The ad-hoc filter is connected to the same datasource as the new graph I was trying to add.

Leaving the dashboard an reentering seems resolves the problem. Refreshing does not.

**Comment by torkelo** [comment]
This is fixed in master and v4. 0.x branch, can't find the other issue right now, on mobile.  Check changelog
