### ISSUE TITLE
Not all roles are synced when using AzureAD

### ISSUE THREAD

**Issue by duj4** [grafana/grafana#68407]
### 
# What went wrong?

**What happened**:
I have LDAP authentication enabled with local AD, mapping between AD group and Grafana org is set. User A was added as admin to multiple AD groups as well so that it can switch among different orgs. This is working as expected.
Today I enabled Azure AD authentication as well, Azure AD is syncing with local AD, thus all groups defined in local AD are in AAD as well. Once I logged into Grafana via Azure AD authentication with user A, it only shows in one group (Grafana Server Admin group) with Server Admin role but not others. And I checked other groups, user A is not there.

**What did you expect to happen**:
User A could also show in other groups but the most privileged group only.

### 
# How do we reproduce it?

**Step 1**:

- Created 2 groups in local AD: group A is mapping to Org with Grafana Server Admin role, group B is mapping to normal Group with Admin role. 
- Add user A to both group A and B
- Enable LDAP
- Log into Grafana, user A should appear in both org A and org B, it can switch between them.

**Step 2**:

- Set up Azure AD
- Add manifest with Admin role and Grafana Server Admin role (turn on allow_assign_grafana_admin)
- Log into Grafana with Azure AD authentication, user A should only appear in org A
- Log file and config file are attached

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A downloaded binary

### User's OS?

RHEL 8.7

### Is this a Regression?

None

### Anything else to add?

[azuread_config.txt](https://github.com/grafana/grafana/files/11466457/azuread_config.txt)
[grafana-server.log](https://github.com/grafana/grafana/files/11466458/grafana-server.log)

**Comment by duj4** [comment]
Screenshots of user info of logging in via different ways:
![user_aad](https://github.com/grafana/grafana/assets/19278537/04aa6a68-d053-44d3-96d8-b3ce3142afad)
![user_ldap](https://github.com/grafana/grafana/assets/19278537/5aa207ba-5ab9-4e72-8c0e-d51d3c0e0f0b)

**Comment by duj4** [comment]
Users info of loggin in via different ways:
![user_aad](https://github.com/grafana/grafana/assets/19278537/3f63958c-3d85-476e-b694-19c929120314)
![user_ldap](https://github.com/grafana/grafana/assets/19278537/abbfb72b-f136-4e54-adae-50fbd6925870)

**Comment by duj4** [comment]
Will try groups_attribute_path later.

**Comment by usmangt** [comment]
Hi @duj4,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by duj4** [comment]
Thanks @usmangt .

**Comment by duj4** [comment]
hi @usmangt , may I have any update for this one? Well for now what I did is replace those orgs with one org instead, this will work as expected. However, we do need a org mapping like LDAP does.

**Comment by usmangt** [comment]
Hi @duj4 ,

I can see that this issue is now lined up in the Authentication team space. They will get back to you.

**Comment by Jguer** [comment]
Hi @duj4, you should avoid configuring LDAP and OIDC for the same overlapping users as the different sync mechanisms will compete with each other.

If you want to just control role assignments via LDAP, prefer using `skip_org_role_sync=true` in your `auth.azuread` settings

**Comment by duj4** [comment]
Thanks @Jguer , never expected further update of this issue.

I had already abandoned LDAP but OIDC only, and as I noticed that org mapping in OIDC is not supported so far in Grafana, we just created only 1 org in our config, it is working fine.
