### ISSUE TITLE
Cloudwatch: Performance issue with dimension-keys

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#68408]
### 
# What went wrong?

**What happened**:

A customer reported that requests to /dimension-keys took about 30-50 seconds to load every time they opened a new query, even if the query editor was empty.

I haven't been able to recreate this myself, but I believe this will happen on larger accounts with many metrics. It might instead make sense to either not request dimension keys until maybe a further filter is selected (ex Namespace), or to fetch the hardcoded list or provide clues for user's in the ui/documentation that they may wish to change https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#configure-the-data-source-with-grafanaini if they are running into performance issues on dimension-keys. The default is 500 pages of metrics, which we then seem to loop through a few times to get dimension keys out of those metrics which I think is causing the performance issues. 

**What did you expect to happen**:

I would expect that all endpoints would return in less than a second or two on an empty query page.

### 
# How do we reproduce it?

- Was originally seen when migrating from 9.1.8 to 9.3.2 but is also in 9.4.7 and likely greater than that. 
- Create a cloudwatch datasource instance that has many potential dimension keys
- Open network tab and a blank explore tab, notice that /dimension-keys takes significantly longer than many other endpoints

### 
# What Grafana version are you using?

9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Are Datasources involved?

Cloudwatch

**Comment by eleijonmarck** [comment]
I found some relevant information in the Grafana documentation. Here's a summary:

Relevant documentation:
1. [Cloudwatch data source
enhancements](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#configure-the-data-source-with-grafanaini): This document
mentions adding a page limit to the List Metrics API call to improve speed and reduce memory consumption. You can change this limit by
entering a higher value in `list_metrics_page_limit` in the Grafana configuration file.

2. [Configure the data source with grafana.ini](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#aws): This document
explains how to configure data source options in the Grafana configuration file.

3. [Configure CloudWatch settings](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#configure-the-data-source): This
document provides information on configuring timeout specifically for CloudWatch Logs queries.

Based on this information, you can try adjusting the `list_metrics_page_limit` in the Grafana configuration file to improve the performance of
the `/dimension-keys` endpoint. Additionally, consider configuring the timeout settings for CloudWatch Logs queries if needed.

**Comment by katebrenner** [comment]
closing since customer escalation was closed - this will not get prioritized in next 6 months
