### ISSUE TITLE
[Bug] ElasticSearch Proxy Error

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#6840]
Please include this information:
- What Grafana version are you using?
Grafana v4.1.0-pre1 (commit: 09e49f0) via Docker
- What datasource are you using?
Elasticsearch in a docker-compose network
- What OS are you running grafana on?
Ubuntu 16
- What did you do?
Having a dashboard playlist running on a device
- What was the expected result?
Graphs using elasticsearch queries should work 24/7
- What happened instead?
After some time, proxy request to elastic search start to fail. Restarting grafana fixes the problem. Elasticsearcg itself is still able to execute queries manually via the api.

```
grafana_1                 | t=2016-12-06T07:44:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/_msearch status=502 remote_addr=192.168.1.112 time_ms=41ns size=0
grafana_1                 | 2016/12/06 07:44:06 http: proxy error: dial tcp 172.18.99.8:9200: connect: cannot assign requested address
```

I think the whole problem started a bit after the 4.0 release, but not sure about the exact version...

**Comment by torkelo** [comment]
try a newer build sounds related to the data source proxy connection pool issue we had in 4.0.0  (fixed in 4.0.1 and in master last friday). https://github.com/grafana/grafana/issues/6759
