### ISSUE TITLE
Docs: Investigate discrepancy between setup instructions

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#68420]
### 
# What went wrong?

**What happened**:

  - Difference between instructions in create-plugin and procedures in "Developing with local Grafana"
  - Whether you **need** to refresh the browser after a change in frontend code of a plugin.
  - 

**What did you expect to happen**:

  - The same
  - See https://github.com/grafana/grafana/pull/68159#pullrequestreview-1421071893

**Comment by josmperez** [comment]
Duplicate.

**Comment by GrafanaWriter** [comment]
Given Joe's comment that this is a duplicate, I will close this issue. Please reopen if that is incorrect.
