### ISSUE TITLE
Explore view with elasticsearch plugin: log panel not correctly updated when limit option is changed

### ISSUE THREAD

**Issue by fmassot** [grafana/grafana#68428]
### 
# What went wrong?

**What happened**:

I'm querying an elasticsearch datasource with query type `logs` in the explore view. I enabled the feature `enableElasticsearchBackendQuerying`.
When updating the `limit` option from 500 to 10 for example, the logs displayed in the log panel are not updated correctly.  I'm still seeing hundreds of logs. And worse, when I try to click on some log lines, nothing happens.

This also happens when I'm selecting consecutively different time windows in the log volume panel, after a few updates, the log panel doesn't show the logs I'm expected to see.

The current workaround is to refresh the page. After that, everything works as expected.

**What did you expect to happen**:
 
When I update the limit option from 500 to 10, I'm expecting to see only 10 log lines in the log panel.

### 
# How do we reproduce it?

**Step 1:**

- Start Grafana with the feature `enableElasticsearchBackendQuerying` enabled. I suspect it does even without the feature.

**Step 2:**

- Open the explore view
- Select an elasticsearch datasource
- Select the logs query type
- Run first a query with the default limit (default to 500), your query must return several log lines.
- Run a second query with a limit to 1.
- Look at the log panel and see that you have more than 1 log line.

### 
# What Grafana version are you using?

10.1.0-116348pre-ubuntu

### 
### Grafana Platform?

Docker

### User's OS?

macOS Monterey

### User's Browser?

Google Chrome Version 112.0.5615.137 (Official Build) (arm64)

### Is this a Regression?

None

### Are Datasources involved?

Elasticsearch

**Comment by fmassot** [comment]
More info: I started Grafana in development mode (`yarn start` and `make run`) and I get the following error in the console when I have more than one log line in the log panel:

```
Warning: Each child in a list should have a unique "key" prop.
```

When looking at the code, I saw that the key for the `LogRow` component is defined by `row.uid`.
But in my example, `row.uid` is always `undefined`.

If I change the code of the `UnThemedLogRows` and use a unique ID as the key, it solves the issue.

I don't know yet what should be the value of `row.uid` and why it's undefined.

**Comment by ivanahuckova** [comment]
Thank you @fmassot for creating this issue. In this case, I suspect that the issue is that both queries return data (log lines) with the same `id` property. And we expect `id` to be unique and use it as `key` when rendering log lines. And duplicated `key` breaks the ui. I'll investigate and create a fix.

**Comment by fmassot** [comment]
Cool. I knew this issue was serious :)

**Comment by fmassot** [comment]
Impressed by the speed of the fix, thanks.
