### ISSUE TITLE
[Feature Request]: Add support to render panels to PDF

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6843]
Created feature request issue from closed PR. 

There was a PR for this. 
https://github.com/grafana/grafana/pull/6028

**Comment by IldarMinaev** [comment]
+1 ;-)
I need PDF weekly report from Grafana. This PR help me, I can create crontab job which just download PDF from Grafana dashboard and send it to mail.

**Comment by yuakop** [comment]
Seems useful to export all information from dashboard in png / pdf

**Comment by ldktta** [comment]
+1

**Comment by digrich** [comment]
+1 
This would help in making daily/weekly reports with cool graphs. And in future if we add the support within grafana at the dashboard/panel level to send out these reports automatically to different email addresses, that would be great.

**Comment by marcelfischer** [comment]
+1

**Comment by FFalcon** [comment]
+1

**Comment by mgehre** [comment]
+1

**Comment by jscott0918** [comment]
+1

I pull data from Grafana dashboards and hate having to retain detailed information long term.  Exporting the detailed dashboard into a single report would help me cut down on data retention without losing the detailed view.

**Comment by utkarshcmu** [comment]
@jscott0918 You can track this issue if you need PDF report generated out of Grafana dashboards:

https://github.com/utkarshcmu/wizzy/issues/33

**Comment by utkarshcmu** [comment]
I am working on it currently and should release it very soon.

**Comment by maraev** [comment]
+1

**Comment by horgi2012** [comment]
+1 important in our proj save and send by e-mail

**Comment by rogersinel** [comment]
+1

**Comment by randomeleven** [comment]
+1
It's best to make it automated as well. User should set up scheduled report and have them delivered via email weekly/daily/etc.

**Comment by wvos** [comment]
+1
which branch/feature request is this code being committed to?  Quite interested in this functionality.

**Comment by gnuhpc** [comment]
+1

**Comment by kylehadland** [comment]
+1

**Comment by scottglazier** [comment]
+1

**Comment by cicciopizza** [comment]
+1

**Comment by IldarMinaev** [comment]
Hi @torkelo, any plans to add scheduled reports support to Grafana or just PDF export?

**Comment by torkelo** [comment]
yes, maybe sometime next year

**Comment by rskonieczka** [comment]
+1

**Comment by brunomagalhaes** [comment]
+1

**Comment by george-marcel** [comment]
+1

**Comment by meyju** [comment]
+1

**Comment by doncovski** [comment]
+1

**Comment by sonnylaskar** [comment]
+1 Very much needed

**Comment by atrotossavainen** [comment]
+1, pnp4nagios does this and migration from icinga to icinga2 is partially dependent on being able to do this in grafana

**Comment by Negwoh** [comment]
+1

**Comment by Fettstorch** [comment]
+1

**Comment by yan-oreshchenkov** [comment]
+1

**Comment by marcusboden** [comment]
+1

**Comment by nischalsamji** [comment]
+1

**Comment by daniellee** [comment]
As no one has mentioned it here before: https://github.com/IzakMarais/reporter

**Comment by SlodeSoft** [comment]
+1

**Comment by LucasSegersFabro** [comment]
+1

**Comment by calvinbrewer** [comment]
+1

**Comment by VitaliyDemchuk** [comment]
+1

**Comment by mcmxii** [comment]
+1

**Comment by IzakMarais** [comment]
Check out https://github.com/IzakMarais/reporter, which can create pdf reports from grafana dashboards.

**Comment by devcode2** [comment]
+1

**Comment by ifutant** [comment]
+1

**Comment by olivernz** [comment]
+1

**Comment by mwasyou** [comment]
+1

**Comment by GobinathPandurangan** [comment]
+1

**Comment by naorw** [comment]
+1

**Comment by perplexityjeff** [comment]
+1

**Comment by HeaverNothing** [comment]
+1
If it could generate a PDF and also save each panel as an individual JPG  in a zip file that would be so helpful!

**Comment by adansbrow** [comment]
+1

**Comment by niallcro** [comment]
+1

**Comment by cicciopizza** [comment]
+1

**Comment by cpmbailey** [comment]
+1

**Comment by kantsuw** [comment]
+1 
I think it would be easy for monitoring, if we can have cron screen shot report

**Comment by IzakMarais** [comment]
@kantsuw Since the reporter (https://github.com/IzakMarais/reporter) exposes an HTTP API for fetching a pdf, you could easily use curl or wget in your cron job to fetch pdf reports on a schedule.

**Comment by salvq** [comment]
+1

**Comment by EliasReuter** [comment]
+1

**Comment by KlDec** [comment]
+1

**Comment by fruchtee** [comment]
please push this
