### ISSUE TITLE
Regression: Alerting + Google Cloud Monitoring: Query/Datasource nil-pointer issue after upgrade to v9.4.1

### ISSUE THREAD

**Issue by OscarVanL** [grafana/grafana#68443]
### 
# What went wrong?

**What happened**:

  - After upgrading Grafana from v9.2.3 to v9.4.1 alerts that depend on GCM as a datasource stopped working.
  - Dashboards that relied on GCM continued to work, but the query editor for those dashboards gets an Internal Server Error (with nil-pointer stack trace in Grafana's logs.).

**What did you expect to happen**:

  - Alerts and query editors should continue to work after the upgrade.

### 
# How do we reproduce it?

**Step 1**:

- Create GCM alert using query builder on Grafana v9.2.3
- Create GCM dashboard using MQL editor on Grafana v9.2.3

**Step 2**:

- Upgrade to v9.4.1

**Step 3**:

- Alert stops firing. 
    - When clicking "Edit" on the alert, initially all the previously-selected query builder values appear, but upon changing any value an error `Cannot display the query preview. Some of the data sources used in the queries are not available.` appears and then all selected options get reset. 
    - Re-selecting the previously selected options and re-saving the alert then fixes it (note: this is even with the datasource unchanged, so it seems the data source is not unavailable/broken as the error message may suggest).
- GCM panels continue to display data, but clicking the 'Explore' tab button on a GCM panel gets the error: `Query error - Internal Server Error - Check the Grafana server logs for the detailed error message.`
    - Copying this GCM panel via the context menu `More -> Copy` and pasting it onto a new dashboard fails immediately with the same Internal Server Error.

Specifically the API that fails is `POST` `https://<grafana FQDN>/api/ds/query`

The error stack trace is:
```
runtime error: invalid memory address or nil pointer dereference

0: "/usr/local/go/src/runtime/panic.go:260 (0x4513d5)"
​
1: "/usr/local/go/src/runtime/signal_unix.go:835 (0x4513a5)"
​
2: "/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:587 (0x2e95997)"
​
3: "/drone/src/pkg/tsdb/cloudmonitoring/utils.go:89 (0x2ea070a)"
​
4: "/drone/src/pkg/tsdb/cloudmonitoring/utils.go:98 (0x2ea09a5)"
​
5: "/drone/src/pkg/tsdb/cloudmonitoring/utils.go:152 (0x2ea1bd1)"
​
6: "/drone/src/pkg/tsdb/cloudmonitoring/time_series_query.go:40 (0x2e9dced)"
​
7: "/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:358 (0x2e93b50)"
​
8: "/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:350 (0x2e93904)"
​
9: "/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:85 (0x3507dd0)"
​
10: "/drone/src/pkg/plugins/plugins.go:285 (0x1208234)"
​
11: "/drone/src/pkg/plugins/manager/client/client.go:48 (0x352cb51)"
​
12: "/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:42 (0x352b55e)"
​
13: "/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:103 (0x352c4f5)"
​
14: "/drone/src/pkg/plugins/manager/client/client.go:44 (0x352c4d0)"
​
15: "/drone/src/pkg/services/pluginsintegration/clientmiddleware/httpclient_middleware.go:71 (0x3531a7e)"
​
16: "/drone/src/pkg/services/pluginsintegration/clientmiddleware/cookies_middleware.go:90 (0x3530cbb)"
​
17: "/drone/src/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go:100 (0x353263c)"
​
18: "/drone/src/pkg/services/pluginsintegration/clientmiddleware/clear_auth_headers_middleware.go:48 (0x353024a)"
​
19: "/drone/src/pkg/services/pluginsintegration/clientmiddleware/tracing_header_middleware.go:53 (0x3532e0a)"
​
20: "/drone/src/pkg/plugins/manager/client/decorator.go:35 (0x352dfe8)"
​
21: "/drone/src/pkg/services/query/query.go:236 (0x1f83601)"
​
22: "/drone/src/pkg/services/query/query.go:84 (0x1f81991)"
​
23: "/drone/src/pkg/api/metrics.go:55 (0x2d9d64b)"
​
24: "/drone/src/pkg/api/routing/routing.go:17 (0x19035e1)"
​
25: "/drone/src/pkg/api/response/web_hack.go:40 (0x11d0eb5)"
​
26: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
27: "/drone/src/pkg/web/macaron.go:134 (0x11c5a94)"
​
28: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
29: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
30: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
31: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
32: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
33: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
34: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
35: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
36: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
37: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
38: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
39: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
40: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
41: "/drone/src/pkg/services/contexthandler/contexthandler.go:221 (0x18f0af9)"
​
42: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
43: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
44: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
45: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
46: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
47: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
48: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
49: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
50: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
51: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
52: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
53: "/drone/src/pkg/web/render.go:44 (0x11c6655)"
​
54: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
55: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
56: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
57: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
58: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
59: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
60: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
61: "/drone/src/pkg/web/macaron.go:140 (0x11c5b3b)"
​
62: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
63: "/drone/src/pkg/middleware/csrf/csrf.go:64 (0x209f365)"
​
64: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
65: "/drone/src/pkg/middleware/recovery.go:171 (0x18fdf61)"
​
66: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
67: "/drone/src/pkg/middleware/logger.go:42 (0x18fb6c1)"
​
68: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
69: "/drone/src/pkg/middleware/request_metrics.go:59 (0x18fed89)"
​
70: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
71: "/drone/src/pkg/middleware/request_tracing.go:88 (0x19004da)"
​
72: "/usr/local/go/src/net/http/server.go:2109 (0x7a514e)"
​
73: "/drone/src/pkg/web/context.go:49 (0x11c43fd)"
​
74: "/drone/src/pkg/web/router.go:155 (0x11c7bcd)"
​
75: "/drone/src/pkg/web/router.go:211 (0x11c8835)"
​
76: "/drone/src/pkg/web/macaron.go:166 (0x11c5fb0)"
​
77: "/usr/local/go/src/net/http/server.go:2947 (0x7a854b)"
​
78: "/usr/local/go/src/net/http/server.go:1991 (0x7a3c26)"
​
79: "/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46f100)"
```

### 
# What Grafana version are you using?

v9.4.1 (fd67ab151d)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

^ Sorry this is way too big, over 200KB of JSON that hasn't been properly anonymised even when checking the anonymisation boxes. It seems there's no way to export the JSON just for a specific panel, only the whole dashboard.

### Grafana Platform?

Kubernetes

### User's OS?

MacOS Ventura 13.3.1

### User's Browser?

Firefox 112.0.2

### Is this a Regression?

Yes

### Are Datasources involved?

Google Cloud Monitoring

### Anything else to add?

Could possibly be related to https://github.com/grafana/grafana/issues/65884

**Comment by yuri-tceretian** [comment]
I do not think this is alerting area, the symptoms look like a problem with the data source plugin. I will try to reproduce the problem anyway. 
@OscarVanL do you use legacy alerting or new Grafana alerting?

**Comment by OscarVanL** [comment]
We use new new Grafana alerting, the affected alert was created not too long ago (AKA, via the new "alerting" tab, as opposed to the old way which was inside panels/dashboards?)

**Comment by yuri-tceretian** [comment]
I see that you mentioned 9.4.1? Did you try to upgrade to the latest patch?

**Comment by OscarVanL** [comment]
I asked our SRE team to upgrade our grafana instance, we're now running **9.5.2** and it appears I cannot reproduce the 500 behaviour.

When clicking Explore on the same panel instead of a 500 error I get an error:
`query failed: { "error": { "code": 400, "message": "Invalid project ID.", "status": "INVALID_ARGUMENT" } }`

In this case, the project ID was being templated in the dashboard with a variable, but on the explore tab this is no longer present. I guess before this scenario was not being handled, hence the 500/nil-pointer exception, now this appears to be properly handled with an informative error message 😁 

I'm happy with this issue being closed.

**Comment by yuri-tceretian** [comment]
Great, thanks for reporting back, @OscarVanL!
