### ISSUE TITLE
[BUG] Metrics: broken state

### ISSUE THREAD

**Issue by vitaly-zdanevich** [grafana/grafana#6845]
![screen shot 2016-12-06 at 12 01 23](https://cloud.githubusercontent.com/assets/3514015/20919315/2de37d76-bbac-11e6-884c-31270c3452ca.png)

I can not remove any of this - push to the recycle bin ico do nothing.

At js-console I see error:
`boot.fdf40765.js:38 TypeError: Cannot read property 'panelCtrl' of undefined`

Grafana version: 4.0.1-1480694114
Ubuntu 16.04 x64

This is just after installing - I tried to figuring out what I can do here.

**Comment by torkelo** [comment]
what datasource are you using?

**Comment by vitaly-zdanevich** [comment]
when datasource is incorrect

**Comment by torkelo** [comment]
?

**Comment by vitaly-zdanevich** [comment]
but this is the incorrect behavior of application - nothing happen after a click to the recycle bin ico

**Comment by torkelo** [comment]
I am unable to help if you don't say what data source type your using. 

Since your are the only one who has reported this issue with 4.0.1 you must be doing something different, maybe using a data source plugin, or something else strange, old browser maybe.

**Comment by vitaly-zdanevich** [comment]
I tried to choose source Grafana Live, no plugins, up-to-date Chrome.

**Comment by torkelo** [comment]
Grafana Live is not ready for usage, sorry, it should no even be possible to add it. Is a bug that it is available

**Comment by vitaly-zdanevich** [comment]
I glad that I found bug for your great product :)
