### ISSUE TITLE
Alerting not accepting non-public-CA-signed certificate from Prometheus

### ISSUE THREAD

**Issue by jensbaitingerbosch** [grafana/grafana#6846]
Hi, 

we are using Grafana in combination with Prometheus. Prometheus is using a certificate that was signed by a company internal CA. That CA root certificate is rolled out to our client PCs and I can use this Prometheus server within my Grafana instance. When I configure an alert and test the rule, I get the following error message:

    firing true
    conditionEvals = true
    timeMs 34.909ms
    error tsdb.HandleRequest() error Get https://my-prometheus/api/v1/query_range?end=2016-12-06T10%3A20%3A10.895820445Z&query=some-query&start=2016-12-06T10%3A15%3A10.895820445Z&step=20.000: x509: certificate signed by unknown authority

How can I configure the root certificate?

**Comment by torkelo** [comment]
you should be able to add a root CA on your ĺinux system (depending on distro). 

You can also specify them in the grafana data source options view under auth
