### ISSUE TITLE
[Bug] Alerts to slack are not sending images

### ISSUE THREAD

**Issue by narfeta** [grafana/grafana#6848]
When an alert is fired, i received the alert with no image in it (test works ok)  

Thnx!

Please include this information:

- What Grafana version are you using?
   
      4.0.0-1480439068_amd64

- What datasource are you using?

      Influxdb 

- What OS are you running grafana on?
   
      Ubuntu 16.04

- What did you do?

      Set an alert and when fired no image was with the message in the slack channel

- What was the expected result?

      an image with the message

- What happened instead?

      no image

---------------------------------------------------------------------------------

(
one thing that i found i dont know if is related or not, is that direct links rendered that has the "fullscreen" param in it are returning black png. 

    dashboard graph -> view -> share -> direct link rendered NOT WORK
    dashboard graph -> share -> direct link rendered WORSK OK
)

**Comment by bergquist** [comment]
You need to configure the external image storage to upload images to slack. http://docs.grafana.org/installation/configuration/#external-image-storage
