### ISSUE TITLE
legacy provisioned alert missing in grafana 9.4.7

### ISSUE THREAD

**Issue by ZhixiangRenCompass** [grafana/grafana#68489]
### 
# What went wrong?

**What happened**:

  - we recently upgraded our grafana from v7.5.15 to v9.4.7. we opt out and enable Legacy by setting GF_ALERTING_ENABLED=true and GF_UNIFIED_ALERTING_ENABLED=false, I can see the alert in the dashboard but I can’t see them from the Admin Alerting rules page, and those legacy alerts are not working anymore in v9.4.7. 

**What did you expect to happen**:

  - legacy alerts should work.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by zuchka** [comment]
Thanks for creating this issue, @ZhixiangRenCompass 

Legacy Alerting is deprecated and will be entirely removed in Grafana 10.
