### ISSUE TITLE
docs: sign plugin page is out of sync with policy

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#68483]
Signature levels and description here https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#plugin-signature-levels doesn't match whats in https://grafana.com/legal/plugins/

As with the publishing page, we can probably remove the table from our docs and instead reference the legal page.

**Comment by josmperez** [comment]
I'm torn between linking to the legal doc and just ensuring that the current documentation matches the legal doc. Linking gets rid of duplcation and reduces the possibility of discrepancies arising. However, keeping the table in our documentation is more user-friendly because a lot of users won't follow the link but they need to know this info. 

And for the users who follow the link, they might have to scan through a lengthy page to find the applicable information (might be wrong about this, but this page is not on the doc site and doesn't seem to have bookmarks for headings).

Let's weigh the pros/cons.

**Comment by Eve832** [comment]
Hi @josmperez, can you please update the status of this ticket in your view in https://github.com/orgs/grafana/projects/69/

**Comment by josmperez** [comment]
For doc plan phase 3.

**Comment by josmperez** [comment]
This was done earlier in the site migration.

**Comment by sympatheticmoose** [comment]
> Let's weigh the pros/cons.

@josmperez I don't think we've done this?

We're still maintaining both locations and have to remember to update both to stay in sync.

**Comment by josmperez** [comment]
Right. From a user-focused perspective, my reluctance to simply link to Legal's list of signature levels is that the content is buried on a larger page. Also, judging from the appearance of the page, there isn't already an anchor on the signature levels section to allow us to link directly to that section of the document. It would be a simple task for someone to add an anchor right there, but it's outside of our control.

We could initiate a conversation with the Legal page maintainer to see if they're willing to add an anchor directly to this section, and then we could remove the duplicate content when they do so.

**Comment by josmperez** [comment]
> I don't think we've done this?

Right. From a user-focused perspective, my reluctance to simply link to Legal's list of signature levels is that the content is buried on a larger page. Also, judging from the appearance of the page, there isn't already an anchor on the signature levels section to allow us to link directly to that section of the document. It would be a simple task for someone to add an anchor right there, but it's outside of our control.

We could initiate a conversation with the Legal page maintainer to see if they're willing to add an anchor directly to this section, and then we could remove the duplicate content when they do so.

**Comment by sympatheticmoose** [comment]
@josmperez we can update that page, I've done so a few times.

**Comment by josmperez** [comment]
@sympatheticmoose - I don't see a GitHub repo for Legal. How do I update the page?

**Comment by josmperez** [comment]
We decided to link to Legal. Doc is clearner and no redundancy.
