### ISSUE TITLE
docs: Plugins - publish plugin - fix 2 broken links

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#68486]
### 
# What went wrong?

**What happened**:

  - Two links broken

**What did you expect to happen**:

  - Links working

### 
# How do we reproduce it?

Go to https://grafana.com/docs/grafana/next/developers/plugins/publish-a-plugin/ in Grafana v10

### 
# What Grafana version are you using?

v 10.0

**Comment by Eve832** [comment]
Hi @josmperez, can you please update the status of this ticket in your view in https://github.com/orgs/grafana/projects/69/
