### ISSUE TITLE
[Bug] Grafana sent false alerts

### ISSUE THREAD

**Issue by kylejvrsa** [grafana/grafana#6849]
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxdb 1.1.0
- What OS are you running grafana on? Debian 8
- What did you do? 
I upgraded to grafana 4.0.1 from 4.0.0 yesterday. I created the dashboards and alert rules on grafana 4.0.0 and they have been running fine for a couple of days.
- What was the expected result?
I expected to get alerted when it reached my configured threshold.
- What happened instead?
I got alerted on multiple graphs and it was nowhere near the threshold

If it relates to *alerting*
- An image of the test execution data fully expanded.
![grafana_alert](https://cloud.githubusercontent.com/assets/2302861/20927958/6532106a-bbcc-11e6-9359-9d0811859800.png)
![grafana_influx_query](https://cloud.githubusercontent.com/assets/2302861/20927980/74c5d80e-bbcc-11e6-9777-df1e70d2d9c2.png)

**Comment by bergquist** [comment]
Could you please change the dashboard to view the timerange for when the alert triggered?
`(alert trigger timestamp - 15m)` to `alert trigger timestamp`

**Comment by kylejvrsa** [comment]
Hi @bergquist ,

Thanks for responding! I hope this is what you want, if not let me know!

![grafana_alert_time_range](https://cloud.githubusercontent.com/assets/2302861/20930062/dbf6d714-bbd4-11e6-85c5-a7c7e8082d3f.png)

**Comment by kylejvrsa** [comment]
The other graph I have is a load graph and it's state just never got updated to OK after that, even though the "heart" is green.

![grafana_alert_state_not_updated](https://cloud.githubusercontent.com/assets/2302861/20931241/25a84718-bbd9-11e6-85c1-5f8f5ab486c3.png)

**Comment by torkelo** [comment]
@bergquist could they be execution errors? How do you identify that currently?

**Comment by kylejvrsa** [comment]
I just got this again on 3 of my graphs. Will be happy to supply any relevant details you require.

**Comment by daniellee** [comment]
I can confirm that we are seeing this in production here at Raintank/GrafanaLabs too. It seems to occur sometimes when the alert is triggered due to an error.

Never got an OK:

![image](https://cloud.githubusercontent.com/assets/434655/23709657/72278ac0-041a-11e7-8bc6-3b66056fbb3f.png)

But the alert is green:

![image](https://cloud.githubusercontent.com/assets/434655/23709724/a510e81e-041a-11e7-991a-0060821eeacc.png)

Here is the notification for the error. The query returned a 404:
![image](https://cloud.githubusercontent.com/assets/434655/23709831/ffe1065c-041a-11e7-8ad2-c46a83e4c841.png)

Alert settings:

![image](https://cloud.githubusercontent.com/assets/434655/23709929/4fc157c6-041b-11e7-8524-78cf93a9bfc7.png)

**Comment by torkelo** [comment]
@kylejvrsa  could they be execution errors? when you hover over the "false alert" annotation what does it say? What does your query look like? have you gotten this again? your panel has a lot of timeshift, this is confusing for an alert panel.

**Comment by kylejvrsa** [comment]
Hi,

I attached the images.
I actually switched it off as it was alerting every other day like this, so there was no way to trust it. I can switch it back on and let you know, if you want? Happy to provide more details just let me know what you need

![screenshot_20170411_142443](https://cloud.githubusercontent.com/assets/2302861/24909244/6640dce8-1ec3-11e7-8457-45f18f92e55c.png)

**Comment by torkelo** [comment]
So the InfluxDB query returns and error every other day? Try changing the execution error option to keep last state

**Comment by ianbamforth** [comment]
I had the same problem as this, and @torkelo's solution fixed it, thanks.

**Comment by kylejvrsa** [comment]
I can no longer reproduce this issue with Grafana 4.2. Not sure what changed but glad it's not happening anymore thanks!
