### ISSUE TITLE
Docs: clarify discrepancy between plugin 'develop locally' doc with plugin-tools docs

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#68500]
### 
# What went wrong?

**What happened**:

  - Investigate this discrepancy: https://github.com/grafana/grafana/pull/68159#discussion_r1190153758

**What did you expect to happen**:

  - 'Develop locally' doc should match procedures in plugin-tools repo.
  - Compare docker-compose file shown here https://grafana.com/docs/grafana/latest/developers/plugins/get-started-with-plugins/development-with-local-grafana/#run-grafana-with-docker-compose with https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/common/docker-compose.yaml

**Comment by Eve832** [comment]
Hi @josmperez, can you please update the status of this ticket in your view in https://github.com/orgs/grafana/projects/69/

**Comment by josmperez** [comment]
Awaiting completion of doc plan phases 1 and 2 for researching and fixing.

**Comment by josmperez** [comment]
Ah,  as @sympatheticmoose reminded me some time ago, we jointly decided to remove the 'develop locally' topic when we transitioned the site from Hugo to Docusaurus last summer, and we don't intent to return it. The reason is that we don't want to encourage this approach to development. 

The https://grafana.com/developers/plugin-tools/get-started/set-up-development-environment doc is living, and if there is a need to document local development in the future the let us know and we'll look at it then.
