### ISSUE TITLE
UX: New Row - Add First Panel

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#6851]
When adding your first panel into a new row, it automatically adds it at Span: 12, which effectively halts the row creation process and lands you at a dead end. After the interface blinks and the new panel appears, you dont realize you can re-size the new panel, nor do you realize you need to resize it in order to add another panel:

![new-dash-panel](https://cloud.githubusercontent.com/assets/2886187/20931138/2c55a8fc-bb9e-11e6-8bda-87a5f7021fdd.gif)

I propose we default panels to be added at a width of Span: 6 or Span: 4, which will retain the Empty Space for people to drag multiple panels - and when we finally add hint.js, we can immediately trigger a hint on the draggable bottom-right corner of the panel to show that functionality.

**Comment by mattttt** [comment]
Or even better, I think the ideal solution could be to include a few empty areas, but I believe this would be a bit of effort:

![screenshot 2016-12-06 10 48 47](https://cloud.githubusercontent.com/assets/2886187/20932189/c05e53fc-bba1-11e6-8fa7-6647555e291b.png)

**Comment by torkelo** [comment]
closing as this is not (that) relevant in v5+
