### ISSUE TITLE
Grafana managed alert cannot be routed to external alertmanager in multiorganization setup

### ISSUE THREAD

**Issue by srindal** [grafana/grafana#68539]
### 
# What went wrong?

We're running Grafana OSS 9.5.2. We have two organizations inside Grafana and we manage alerts using an external Alertmanager. In organization 1 we have multiple alerts handled by Mimir and external Alertmanager and that works perfectly. If I create a "Grafana Managed Alert" in Org 1 that alert will be routed to the External Alertmanager. 

However, when you switch to organization 2 which has an Alertmanager configuration identical to org 1, suddenly my alerts are handled by the internal Grafana Alertmanager and the log says: 

In the startup log I see this:
logger=ngalert.sender.router t=2023-05-16T11:44:14.906943665Z level=info msg="Creating new sender for the external alertmanagers" org=1 alertmanagers=[http://prometheus-alertmanager.prometheus:80]

And then when alerts trigger in Org 2 this is written in the log:
logger=ngalert.sender.router rule_uid=f361a4f4-1fd3-4a28-a8b1-cba1a3d0f307 org_id=2 t=2023-05-16T11:45:00.144520876Z level=info msg="Sending alerts to local notifier" count=1

If I disable "Receive grafana alerts" for the alertmanager i org 1 and restart grafana then "Creating new sender ..." does not occur in the log. 

It seems like routing grafana alerts to external alertmanager is only supported in Organization 1.

**What did you expect to happen**:

I expected to be able to route grafana managed alerts from multiple organizations into the same external alertmanager instance.
  - 

### 
# How do we reproduce it?

**Step 1**:

Creating a second org.

**Step 2**:

Add external alertmanager datasource and tick "receive grafana Alerts"

**Step 3**:

Configure an alert this fire immediately

**Step 4**: 

Verify that it is not routed to the external alertmanager by opening alert groups and see that the new alert occurs in "grafana" only.

### 
# What Grafana version are you using?

v9.5.1, v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Windows

### User's Browser?

Firefox

### Is this a Regression?

None

### Are Datasources involved?

Prometheus, Prometheus Alertmanager

### Anything else to add?

I noticed this bug in 9.5.1. But I'm not sure when it stopped working.

**Comment by srindal** [comment]
I have done some more investigation and my overall conclusion is that when I configure an alertmanager in an organization then the toggle: "Receive Grafana Alerts" only takes effect in org 1. 

When I toggle the switch in organization 1 the log clearly states that the feature is enabled/disabled but in the other orgs nothing happens.

Disabling in org1:
```
logger=ngalert.sender.router t=2023-05-17T08:52:23.24179341Z level=info msg="No external alertmanager(s) configured, sender will be stopped" org=1
logger=ngalert.sender.router t=2023-05-17T08:52:23.241817863Z level=info msg="Stopping sender" org=1
logger=ngalert.sender.external-alertmanager org=1 cfg=1 t=2023-05-17T08:52:23.241825354Z level=info msg="Shutting down communication with the external Alertmanager group"
logger=ngalert.sender.external-alertmanager t=2023-05-17T08:52:23.241834315Z level=info msg="Stopping notification manager..."
logger=ngalert.sender.router t=2023-05-17T08:52:23.241846226Z level=info msg="Stopped sender" org=1
```
Enabling in org 1:
```
logger=ngalert.sender.router t=2023-05-17T09:00:23.249270384Z level=info msg="Creating new sender for the external alertmanagers" org=1 alertmanagers=[http://prometheus-alertmanager.prometheus:80]
logger=ngalert.sender.external-alertmanager org=1 cfg=1 t=2023-05-17T09:00:23.249397808Z level=info msg="Synchronizing config with external Alertmanager group"
logger=ngalert.sender.external-alertmanager org=1 cfg=1 t=2023-05-17T09:00:23.249454643Z level=info msg="Initiating communication with a group of external Alertmanagers"
```
The same actions on alertmanagers in the other orgs do not generate any log. And the disable/enable logs for org 1 looks the same no matter how the alertmanagers in the other orgs are configured.

**Comment by gotjosh** [comment]
@JohnnyQQQQ Any chance this can be related to https://github.com/grafana/grafana/pull/63819, could you please take a look at your earlier convenience?

**Comment by JohnnyQQQQ** [comment]
@srindal I wasn't able to reproduce it. Can you please check in your admin tab that you have the proper selection on this option: 
![Screenshot 2023-05-26 at 11 21 34](https://github.com/grafana/grafana/assets/3528218/bae8b78f-3b13-49fd-81b5-42bfcb71655d)

**Comment by srindal** [comment]
Hi Johnny. Thanks for the investigation. It works as expected now. The problem was finding the settings, and maybe this turns into a UI suggestion instead.

In the admin tab. When I select "Alertmanager" in the top drop down, then the External Alertmanager options in the bottom of the screen disappears. It's only visible when I select the "Grafana" alertmanager option. But since I want to use an external alertmanager, it never occured to me that I had to select: "Grafana", and then scroll beyond the default config to enable the external alertmanager. 

I suggest that the block is moved to the top - or that it is always visible.

Brgds
Søren

**Comment by JohnnyQQQQ** [comment]
Thanks, I have forwarded this to our frontend team. They will take a look at how we can improve discoverability.

**Comment by JohnnyQQQQ** [comment]
@srindal based on your feedback we have added https://github.com/grafana/grafana/pull/69150 as an interim solution.

**Comment by srindal** [comment]
@JohnnyQQQQ nice. Thanks.
