### ISSUE TITLE
[Bug]  Same rounding applied to values with different measure units

### ISSUE THREAD

**Issue by dstreppa** [grafana/grafana#6853]
- What Grafana version are you using?
Grafana 4.0.0

- What datasource are you using?
InfluxDB 1.1.0

- What OS are you running grafana on?
Centos 6.7

- What did you do?
Setting the "decimals" parameter I noted a problem referred to the rounding of the values (see attached images, the first with decimals=3, the second decimals=0). 
The same rounding is applied also if the unit measure is not the same (W and kW in the images)

![selection_008](https://cloud.githubusercontent.com/assets/11214654/20933522/9b46bc44-bbd8-11e6-81cb-273e2119ec49.jpg)
![selection_009](https://cloud.githubusercontent.com/assets/11214654/20933521/9b462072-bbd8-11e6-9668-707f2cb1a985.jpg)

- What was the expected result?
Referring to the images, I expected to have 3770 W for the Main signal.

- What happened instead?
I had 4 kW (4000 W instead of 3770).

**Comment by torkelo** [comment]
well as the first screenshot shows it as 3.770 kW , so if you change to 0 decimals then that is going to be rounded to 4.

**Comment by dstreppa** [comment]
@torkelo the problem is exactly the same rounding both on the kW and on the W values. In the example with decimals=0 I have 4 kW instead of 3.77 kW (6% error caused by rounding), instead the other signals (PV, Battery PM, etc.) in W are not affected by the rounding error.

**Comment by torkelo** [comment]
that is why the auto decimals uses 3 decimals, so if you force 0 decimals that is what grafana will use

**Comment by dstreppa** [comment]
Ah...OK, thank you, now it's clear
