### ISSUE TITLE
NodeGraph: Implement better layout algorithm

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#68540]
Currently the node graph uses d3-force package and it's physics-based force layout algorithm. This is good for general layout without knowing much about the overall structure but can create too random looking layouts. We also did alter some configuration to make it "nicer" for the service graph usecase but this can alse create some non-intuitive layouts (see https://github.com/grafana/grafana/issues/49988 for example).

During recent hackathon I tried using different layout algorithms and [GraphViz DOT](https://graphviz.org/docs/layouts/dot/) seemed most promising as it gives nice layered structure that better represents usual service graph usecase.

Current layout (graph with multiple distinct subsection)
![Image](https://github.com/grafana/grafana/assets/1014802/cec7968d-9607-420e-a5e7-23d60c8fb79d)

GraphViz (orientation changed for better comparison)
![Image](https://github.com/grafana/grafana/assets/1014802/7cdf876a-68b3-48b8-87b9-07c927bf1290)

As the graphviz layout can be slow for higher number of nodes, it would make sense to use some hybrid approach with some node count threshold where the force layout would be still used for bigger graphs.

**Comment by libinyl** [comment]
I'm waiting for this feature so badly...  When will it be released ? thank you very much

**Comment by man0s** [comment]
It's going to be 🔥
Great idea @aocenas

**Comment by aocenas** [comment]
Implemented in https://github.com/grafana/grafana/pull/78957
