### ISSUE TITLE
Select: Multi select component fixes

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#68542]
- When the `isMulti`  prop is applied, the component should be accepting `Array<SelectableValue<string>>`  while is still accepts only `SelectableValues<string>` . This calls for a type casting whenever `isMulti` is applied, to be able to loop through the options and get the values, because natively the react-select will accept `Array<SelectableValue<string>>`
- When selecting multiple values and the tags are displayed in two rows, the margins between the tags and top & bottom borders become razor thin which does not look nice.
![Screenshot 2023-05-12 at 15 33 03](https://github.com/grafana/grafana/assets/100691367/575624d5-f025-4ddd-afea-88041141041e)

(created from comments in [slack message](https://raintank-corp.slack.com/archives/CT7S455SP/p1683899822586659))

**Comment by vivshaw** [comment]
Are you looking for outside contributions on this? I'd be happy to PR something here!

**Comment by JoaoSilvaGrafana** [comment]
> Are you looking for outside contributions on this? I'd be happy to PR something here!

Hey @vivshaw ! Yes we are open to contributions so feel free to open a PR 😄  Thanks!!
