### ISSUE TITLE
Chart cell: add numerical value display

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#68541]
Add ability to display numeric value next to the sparklien for chart cells: 
![image](https://github.com/grafana/grafana/assets/847684/b1173e20-3bbc-4446-8481-4ea4e8e0036e)

- Time series table transform should allow optionally configuring what value to pick for each data frame containing field: last, avg, median
- ~~Stretch: also allow picking value from another numerical field (and removing), thereby allowing separate query to fetch the value?~~
- Allow configuring unit in field config
- Table should be sortable by chart cell column. Likely requires inventing `ValueAndDataFrame` field type
- Values & sparklines in a column should be neatly aligned

**Comment by torkelo** [comment]
Looks good. 

> Stretch: also allow picking value from another numerical field (and removing), thereby allowing separate query to fetch the value?

I don't think this makes sense. Wil make the transform really complex. It's better you do this in a11y app via custom transform
