### ISSUE TITLE
New Panel Type: Mini-Dashboards w/ Alerts

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#6855]
While having breakfast with a Grafana user this morning, a common alerting issue came to mind: I know I have a bunch of alerts, but I really dont know what dashboards I should be looking at. This got me thinking about how we can increase the data density of dashboards with alerts enabled, and let the user quickly decide which dashboard to drill down into.

**Note**: These are mockups only to explore functionality, dont get hung up on design. We can make this look super nice.

#### Here is an initial exploration of that idea.

![alerting-overview-dash](https://cloud.githubusercontent.com/assets/2886187/20935316/3797aa54-bbac-11e6-80d7-5f83d4c2ce47.png)

1. This is illustrating the panels in an Alerting Overview dashboard.
1. It mimics the exact layout of the dashboard, minimized. We draw boxes based on width & height of panels & rows. I know this may be imperfect, but having a recognizable layout to the user is critical. 
1. Clicking anywhere on the panel will drive you into the target dashboard.
1. Related Question: Can we say the Alert name on hover? Would that be terrible to implement? It'd be very useful - though introduces some complication on hit areas (see above)
1. We could compress this even a bit more and on a decent size screen, you'd easily be able to get 18+ dashboards viewable
6. Panels in alerting state would pulse, similar to the full dashboards - but the whole red box would pulse. 
1. Lightening bolt is intentional for accessibility (color blindness). 
1. We have to decide how a mini-dashboard could appear on this Alert Overview dash. Tags? A new classification of starred?
1. Related to the above: How can the user re-order these dashboards themselves to make the most sense? Order and organization feels very important here. **Maybe we dont do it automatically initially, and just create the mini-dashboard panel and let people create/arrange it themselves.**
1. When we implement something like gridster in the future, the density increases even further. Woo.

#### Some additional ideas that came from the initial mockup:
- The ability to include one of these panels on any dashboard. You might want to include other related dashboards you're alerting on as an easy way to drilldown/navigate around. 
- Even if alerting isnt enabled, it makes a really nice hit area for drilling down into other dashboards:

![image](https://cloud.githubusercontent.com/assets/2886187/20935255/f3690300-bbab-11e6-964c-cc709702a3d0.png)

**Comment by mattttt** [comment]
And if we wanted to get crazy, could you open a specific panel in a modal?!? Oh man, this could be awesome, then click through to the dashboard.

![new-dash-panel-panel-modal](https://cloud.githubusercontent.com/assets/2886187/20939082/718fe65e-bbbb-11e6-82ce-0d109094e7e7.gif)

**Comment by alexanderzobnin** [comment]
I think it's a good idea in general. Let's look at grafana as monitoring engineer. We should to have a way to determine state of our system. And every system consist of number of subsystems. It's like a tree of components and we should have a final answer in the root: is our system alive? So this panel can became one of this option.

**Comment by yesoreyeram** [comment]
@mattttt  I have a consolidated dashboard for my compay where i display all the metrics we are interested in few tables with some conditions and some sorting logic.  So that engineers see entire infra stats with a single dashboard as binray (green/red). (We have 1000+ servers in a single dashboard to give some bird eye view). This works pretty well for us for atleast last 12 months.

![image](https://user-images.githubusercontent.com/153843/37555871-44f1d964-29e6-11e8-8ba0-53c687d80770.png)

Now, we would like to have a consolidated alerts dashboard for specific teams https://github.com/grafana/grafana/issues/11287

![image](https://user-images.githubusercontent.com/153843/37555913-0a0d942c-29e7-11e8-8e89-f3c987a032b7.png)

**Comment by torkelo** [comment]
Closing this, but great idea
