### ISSUE TITLE
Docs feedback: /docs/sources/setup-grafana/configure-security/configure-authentication/azuread/index.md

### ISSUE THREAD

**Issue by lionelmarksgrafana** [grafana/grafana#68589]
Clarify AzureAD OrgID placement. It links to:
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-team-sync/

but that link specifies LDAP DNs.. can be confusing to first time users attempting to setup AzureAD.

Step3 on the above link could show some examples of how to enter an AzureAD specific value.

**Comment by linoman** [comment]
After analyzing the problem with @vesnadean we reached a consensus to make some changes to the Team Sync page.

1. Under the team's name, replace the subtitle with

> Manage members and settings. Visit our documentation to learn more about [supported providers for Team sync](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-team-sync/#supported-providers).

2. Remove the tooltip next to the input field for the Team ID sync.
