### ISSUE TITLE
Trace View: Label of "Logs for this span" button can be misleading

### ISSUE THREAD

**Issue by jonatan-ivanov** [grafana/grafana#68596]
### 
# What went wrong?

**What happened**:
When you use the `tracesToLogs` feature and configure it to use the traceId and only the TraceId as a filter, the label of the button in Tempo's Trace View is `Logs for this span` which is misleading because in that case the functionality of the button is rather `Logs for this trace`, not span:
```
filterByTraceID: true
filterBySpanID: false
```

**What did you expect to happen**:
I think one expectation could be automatically labeling the button based on the `filterByTraceID` and `filterBySpanID` flags (use the word trace if only that one is true and use span otherwise).

Another one could be letting the user defining the label, like it is possible in case of the `tracesToMetrics` feature.

But I think the best would be completely removing the `filterByTraceID` and `filterBySpanID` flags and having an extra button on top of the trace view (or on the root span) that only filters the traceId and keeping the buttons on the individual spans that filters the spanId.
By the way I think filtering by traceId (across all operations of all apps) is a much more important feature than filtering by spanId (a single operation of an app).

Btw I'm not sure I'm getting why there are two "Logs for this span" buttons for each span (see screenshots below).

### 
# How do we reproduce it?

**Step 1**:
- Add Tempo and Loki datasources
- Configure `tracesToLogs` feature: `filterByTraceID: true` and `filterBySpanID: false`

**Step 2**:
- Send some spans (and logs)
- Go to Tempo, click on a trace, find the "Logs for this span" buttons (there are two of them for each span)

![Screenshot 2023-05-16 at 11 45 12](https://github.com/grafana/grafana/assets/3044070/774389d8-e7a5-45f2-8e60-34afafc60519)
![Screenshot 2023-05-16 at 11 45 20](https://github.com/grafana/grafana/assets/3044070/650fe64e-2ce1-445f-b3a3-2f66dc1ea56f)

**Step 3**:
- Click on the button that says "Logs for this span" and see the logs for the entire trace not only for that single span.

### 
# What Grafana version are you using?

v9.5.2 (latest)

### 
### Is the bug inside a Dashboard Panel?

N/A

### Grafana Platform?

Docker

### User's OS?

N/A

### User's Browser?

N/A

### Is this a Regression?

No

### Are Datasources involved?

Tempo, Loki

### Anything else to add?

Here's a sample configuration that reproduces the issue: [datasource.yml](https://github.com/jonatan-ivanov/teahouse/blob/a4e27451998d05480f236d93d49842cac750ecc1/docker/grafana/provisioning/datasources/datasource.yml#L36-L49)

This issue might be a little related: https://github.com/grafana/grafana/issues/66996

**Comment by aocenas** [comment]
We renamed the label on the link to `Relevant logs` here https://github.com/grafana/grafana/pull/67160. Not saying that solves everything but hope it's a bit less confusing.

Regarding the filter by trace/span ID options, we have to consider cases where you don't want to filter by those because it's possible that not all the relevant logs will contain the IDs and so this is useful depending on your setup and that is why it's an optional setting.

Having a single button per trace that would be relevant to the whole trace is an interesting idea, but would need some more changes on the design of the feature because of the mentioned consideration. If you feel strongly about that please create a separate issue for that and we can discuss it there. cc @adrapereira @joey-grafana

**Comment by jonatan-ivanov** [comment]
@aocenas Thank you! I created a UX ticket for the extra button, I'm not sure if this is the best label/place for it, could you please help me to add the right labels, move it to the right place if needed? https://github.com/grafana/grafana/issues/68908

**Comment by aocenas** [comment]
@jonatan-ivanov thank you, added some label and added to our board but as mentioned this is probably not going to be a high priority atm and we would need to figure out whether it maps to all usecases we want to support.
