### ISSUE TITLE
Cloudwatch: Explore adding a Refresh Trusted Advisor API

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#68590]
A User was making a request with the Cloudwatch Datasource under the Trusted Advisor namespace like so:
![Screenshot 2023-05-16 at 2 07 07 PM](https://github.com/grafana/grafana/assets/6620164/ab5a2be7-d252-4e6d-965f-2f445034ba0d)
and they are getting inconsistent result depending on whether they have recently hit this RefreshTrustedAdvisor API endpoint: https://docs.aws.amazon.com/awssupport/latest/APIReference/API_RefreshTrustedAdvisorCheck.html

Would be interesting to see if there's a way to support doing this in the Cloudwatch Query Editor, or document some way to do this in the Code section of the QueryEditor.

**Comment by sarahzinger** [comment]
Talking with the AWS team about this to see if they have additional suggestions

**Comment by katebrenner** [comment]
this is a feature request that we will not get to in the next 6 months
