### ISSUE TITLE
[Bug] Can't add new dependency

### ISSUE THREAD

**Issue by ASimpson87** [grafana/grafana#6860]
Grafana 4.1.0beta

I'm trying to create a timeline for a PR but i need to include angular-vis as a dependency , i have a working local copy .... but when i build the package with build.go build package it fails and gives me these errors.

edit: This is all happening during karma:test.

WARN [web-server]: 404 /base/angular-vis.js
WARN [web-server]: 404 /base/angular-aria.js
WARN [web-server]: 404 /base/angular-animate.js
WARN [web-server]: 404 /base/angular-material.js
Fatal error: (msg | | " ").replace is not a function
exit status 3
exit status 1.

If i remove my dependencies , it builds , This is all working on the local server .. how can i bypass this to get the package built...

This is how included the dependencies.

**system_conf.js** 
paths = {
"angular-vis": "vendor/angular-visjs/angular-vis"
}

**app.ts**
import 'angular-vis'
this.ngModuleDependencies = {
'ngVis'
}

I also did bower install angular-vis

Any possible solutions would be greatly appreciated.

Thanks.

**Comment by torkelo** [comment]
add it to the test system conf as well 
https://github.com/grafana/grafana/blob/master/public/test/test-main.js#L12

**Comment by ASimpson87** [comment]
Thank you torkelo , you are a legend sir!
