### ISSUE TITLE
[Bug]Got several issues during "build from source"

### ISSUE THREAD

**Issue by wangmzdl** [grafana/grafana#6862]
I used branch v4.0.x as the source.

_What different between v4.0.x and v4ux?_

I use docker linux system base on Windows7,  go 1.7.4 and node 6.9.2 in the container linux system

**Issues below when I run "npm install"**:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch
okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})
npm ERR! Linux 4.4.17-boot2docker
npm ERR! argv "/node/node-v6.9.2-linux-x64/bin/node" "/node/node-v6.9.2-linux-x6
4/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path ../acorn/bin/acorn
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall symlink

npm ERR! rofs EROFS: read-only file system, symlink '../acorn/bin/acorn' -> '/go
/src/github.com/grafana/grafana/node_modules/.bin/acorn'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

Note: I could use "ln -s" command on my docker container linux system.
Issue after run "npm run build" 
Version 4.0.1
>> Local Npm module "grunt-sass-lint" not found. Is it installed?
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/go/src/github.com/grafana
/grafana/node_modules/node-sass/vendor'

Running "phantomjs" task
Warning: Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file
 (Error code: ENOENT). Use --force to continue.

**Comment by torkelo** [comment]
not sure, looks like a permissions problem you have running npm. 

v4ux is an old ux feature branch
