### ISSUE TITLE
DataSource API: API ignores orgId when creating DataSource

### ISSUE THREAD

**Issue by davidgubler** [grafana/grafana#68620]
### 
# What went wrong?

**What happened**:

I have a setup with multiple Grafana organizations. I am creating a data source for one organization via the API. However Grafana ignores the "orgId" setting in the request Json and assigns the datasource to another organization instead (probably the last organization that has been used via the web interface).

```
$ cat datasource.json 
{
  "name":"test_datasource",
  "type":"graphite",
  "url":"http://mydatasource.com",
  "access":"proxy",
  "basicAuth":false,
  "orgId": 4
}

$ curl -s --user "admin:passw0rd" -X POST -H "Content-Type: application/json" -d "$(cat datasource.json)" https://mygrafana/api/datasources
{"datasource":{"id":3,"uid":"c25a473a-dfe1-4518-b4a6-8792e26f5ec7","orgId":43,"name":"test_datasource","type":"graphite","typeLogoUrl":"","access":"proxy","url":"http://mydatasource.com","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":false,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":3,"message":"Datasource added","name":"test_datasource"}
```

Note how the datasource.json has orgId 4 and Grafana API returns orgId 43.

**What did you expect to happen**:

Grafana creates a DataSource for orgId 4 as specified in the request json.

### 
# How do we reproduce it?

**Step 1**:

- Create a bare-bones Grafana instance with an admin account

**Step 2**:

- Create several organizations

**Step 3**:

- Create a datasource for one organization using the example above.

I think the behavior of the Grafana datasource API depends on which organization was last visited by the "admin" user, hence you may need to switch the web interface to a different organization in order to reproduce the problem.

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Grafana Platform?

Docker

### Are Datasources involved?

Yes but it does not seem to matter which datasource type I use.

**Comment by zuchka** [comment]
Thanks for creating this issue, @davidgubler 

I believe you need to set the User Context for the Signed-In User first:

`curl -X POST http://admin:admin@localhost:3000/api/user/using/<id of new org>`

[api docs here](https://grafana.com/docs/grafana/latest/developers/http_api/user/#switch-user-context-for-signed-in-user)

[example here](https://grafana.com/docs/grafana/latest/developers/http_api/create-api-tokens-for-org/)
