### ISSUE TITLE
Override "Field with values" - series Hide in Area "All Nulls" doesn't affect tooltip

### ISSUE THREAD

**Issue by GedPL** [grafana/grafana#68627]
### 
# What went wrong?

**What happened**:
I'm using newly added "Field with values" override with property "Series-> Hide in area" for hiding null and zero values.

![image](https://github.com/grafana/grafana/assets/31762538/80fb0404-eaac-4f27-be11-dc2d50cf9790)

Tooltip mode is set to "All"
Zero values are not shown in tooltip which is correct, but series with nulls values are still visible.

![image](https://github.com/grafana/grafana/assets/31762538/5ef38eff-6aad-4a8c-853a-016dd7ef7758)

**What did you expect to happen**:
Expecting not see to series with null values in tooltip

### 
# How do we reproduce it?

1. Create panel containing series having null and not null values in selected time range.
2. Add "Field with values" override as described in "What went wrong" section
3. Set tooltip mode to "All"
4. Move mouse pointer over one of points on graph to show tooltip.

### 
# What Grafana version are you using?

v.9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A downloaded binary

### User's OS?

Red Hat Enterprise Linux 7

### User's Browser?

Version 113.0.5672.93 (Official Build) (64-bit)

### Is this a Regression?

No

### Are Datasources involved?

Google Cloud Monitoring

**Comment by leeoniya** [comment]
i cannot reproduce this when creating a new panel on https://play.grafana.org/. please attach your data, as the issue template asks.

![image](https://github.com/grafana/grafana/assets/43234/44299500-82d6-470f-a437-79ed4553769d)

https://github.com/grafana/grafana/assets/43234/a8902bb9-9770-4e78-9718-7d99e1d47df8

here's the frame data i'm using:

```json
[
  {
    "schema": {
      "refId": "A",
      "fields": [
        {
          "name": "time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time",
            "nullable": true
          },
          "config": {}
        },
        {
          "name": "value",
          "type": "number",
          "typeInfo": {
            "frame": "int64",
            "nullable": true
          },
          "config": {}
        },
        {
          "name": "value2",
          "type": "number",
          "typeInfo": {
            "frame": "int64",
            "nullable": true
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          1684310000000,
          1684360000000
        ],
        [
          0,
          0
        ],
        [
          null,
          null
        ]
      ]
    }
  }
]
```

**Comment by GedPL** [comment]
Thank you for quick response !
I cannot share data in public so I've just sent it to your email.

**Comment by leeoniya** [comment]
i think you sent me the wrong panel. i got a stat panel with no sparkline (where there is no tooltip, and no overrides are defined). you can send the panel with the issue to my [work email](mailto:leon.sorokin@grafana.com).

![image](https://github.com/grafana/grafana/assets/43234/7edcef95-ad53-416d-b58e-86000860cf45)

**Comment by GedPL** [comment]
You're right - sorry.
I've sent correct data.

**Comment by leeoniya** [comment]
(the new data had no zeros or nulls in any fields)

**Comment by GedPL** [comment]
I'll work on this and send new data.

**Comment by leeoniya** [comment]
our new tooltips no longer show null-valued series when hovering. no special config is necessary any more.
