### ISSUE TITLE
docs: updates for plugin submission based on Toolkit deprecation

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#68635]
We want to further encourage users of Toolkit, which is deprecated, to migrate to `create-plugin`. 

As part of this we are introducing a new check in the plugin validator for detecting its usage. This will start as a warning, but the intent is to turn this into an error in the future as Toolkit becomes increasingly out of date.

We should ensure all relevant documentation is updated to warn users of this before they attempt to submit a plugin built with Toolkit.

Docs to update (please add/edit as appropriate):
- [ ] https://grafana.com/docs/grafana/latest/developers/plugins/publish-a-plugin/#frequently-asked-questions - add new FAQ 
  - Q. Can I submit plugins built with Toolkit?
  A. Toolkit is deprecated, please [migrate to create-plugin](https://grafana.github.io/plugin-tools/docs/migrating-from-toolkit). In the future, we will reject submissions based on Toolkit as it becomes increasingly out-of-date.
- [ ] https://grafana.com/docs/grafana/next/developers/plugins/sign-a-plugin/#sign-a-plugin - add a note referring to the deprecation of Toolkit

**Comment by Eve832** [comment]
@josmperez can you please update the status of this ticket?

**Comment by josmperez** [comment]
For Plugins doc plan phase 3.
