### ISSUE TITLE
stackdriver group_by shows wrong label

### ISSUE THREAD

**Issue by msillence** [grafana/grafana#68634]
### 
# What went wrong?

**What happened**:
using the stack driver and the mql query:
```
fetch k8s_container
| metric 'kubernetes.io/container/restart_count'
| align rate(1m)
| every 1m
| filter value.restart_count > 0.0
| group_by [metadata.user_labels.app], max(value.restart_count)
```

I get the result showing all the different metrics labeled as value_restart_count_max

**What did you expect to happen**:

I wanted to see each of the app names that were used in the group by

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a google datasource using stackdriver

**Step 2**:

- add a new dashboard and graph
- select the mql tab
- past in the query above

**Step 3**:

- The result in the preview will show value_restart_count_max for every graph

### 
# What Grafana version are you using?

9.3.1

### 
### Is the bug inside a Dashboard Panel?

![grafana-mql-labels](https://github.com/grafana/grafana/assets/1208867/13eed86c-ace0-4593-8fb6-35c6e3f101b1)
![gcp-metrics-label](https://github.com/grafana/grafana/assets/1208867/fa58725d-2a17-4f35-8241-2805c71daa86)

it looks like the metric label is in the field `labels."metric.label.name"`

also I have the following json:

```
          {
            "schema": {
              "refId": "A",
              "meta": {
                "custom": {
                  "labels": {
                    "metric.label.name": "account-xxxxx",
                    "metric.name": "value_restart_count_max"
                  }
                },
                "executedQueryString": "fetch k8s_container\n| metric 'kubernetes.io/container/restart_count'\n| align rate(1m)\n| every 1m\n| group_by [metric.name: metadata.user_labels.app], max(value.restart_count)\n | graph_period 200ms | within d'2023/05/17-09:50:25', d'2023/05/17-09:55:25'"
              },
              "fields": [
                {
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  },
                  "config": {
                    "interval": 200
                  }
                },
                {
                  "name": "value_restart_count_max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64"
                  },
                  "labels": {
                    "metric.label.name": "account-xxxx",
                    "metric.name": "value_restart_count_max"
                  },
                  "config": {
                    "displayNameFromDS": "value_restart_count_max",
```

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

### Are Datasources involved?

stackdriver

**Comment by msillence** [comment]
verified same behaviour in 9.5.2

**Comment by mellieA** [comment]
@msillence what do you see if you group_by only metadata.user_labels.app? I can see that it works in GCP metrics explorer. Are the labels shown in metrics explorer that are partially obscured coming from metadata.user_labels.app?

**Comment by mellieA** [comment]
Also found this similar issue - https://github.com/grafana/grafana/issues/60171

> My solution was to put {{metric.label.request_rule}} in the "Alias by" input. Not sure why that was needed given that I grouped by metric.request_rule, but it works!

Let us know if that works for you too. It might be something we should document or fix

**Comment by msillence** [comment]
> 



> 



> @msillence what do you see if you group_by only metadata.user_labels.app? I can see that it works in GCP metrics explorer. Are the labels shown in metrics explorer that are partially obscured coming from metadata.user_labels.app?

They are the values of metadata.user_labels.app.

Look at the json in the query explorer the correct labels seem to be under fields."metric.label.name" I've not tried to grok the code but I was wondering if it was using fields."metric.name" which seems to have the value "value_restart_count_max" ?

**Comment by msillence** [comment]
I tried the mapping as an override and again I get the literal value `{{metadata.user_labels.app}}`

![group-by-override](https://github.com/grafana/grafana/assets/1208867/cc264344-2f21-4d92-9e9c-b965ec69dbe9)

**Comment by ChristopherWriight** [comment]
@msillence Inspect the panel you shared and view the DataFrame JSON for your label syntax. In some cases Grafana does weird things with labels. E.g. {{metadata.user_labels.app}} may be reporting as {{metadata.user.labels.app}} within Grafana. No idea why, sharing my experience using the pluging :)
