### ISSUE TITLE
Data Source Http Error

### ISSUE THREAD

**Issue by MairtinO** [grafana/grafana#6863]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.0.0
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Windows 10
- What did you do?
added graphite as a data source,
clicked save & test
- What was the expected result?
Not to get a "Http Error"
- What happened instead?
Got a HTTP Error

I just installed grafana and have no experience of using it so I am not too sure if I missed something during the installation.

Thanks
Martin

![badgateway](https://cloud.githubusercontent.com/assets/24318236/20962775/07cad660-bc6b-11e6-94ec-a27227b2ff21.png)

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
make sure you can access graphite via http://localhost:8080 from the grafana-server

**Comment by jackeylhm** [comment]
![grafana_add_datasource_graphite_error](https://cloud.githubusercontent.com/assets/8953102/25647839/44800598-2ff8-11e7-8846-ea60bca049f0.png)

I'm using grafana-4.2.0 on CentOS 7 and I kept getting "HTTP Error Bad Gateway" while I tried to add graphite data source. 
The error message in  /var/log/grafana/grafana.log is as follows:

t=2017-05-03T11:59:02+0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/metrics/find status=502 remote_addr=192.168.56.1 time_ms=1ns size=0

Please advise how to solve this.
Thanks

**Comment by daniellee** [comment]
@jackeylhm HTTP Error Bad Gateway means that the Graphite server is not reachable from 192.168.56.102. Is Graphite installed on the same machine as the Grafana server? Can you navigate to Graphite web on http://192.168.56.102:8080 in your browser?

As this is not a bug in Grafana, in future could you please ask your question on the community site instead -> https://community.grafana.com

**Comment by jackeylhm** [comment]
Hi Daniel


I also popped this question to community, not sure if anyone will answer me.

As I do not know how to install Graphite and neither the document instructed us the need to install Graphite,

please light the way.



Appreciate.


Regards

Jackey


[X]


________________________________
寄件者: Daniel Lee <notifications@github.com>
寄件日期: 2017年5月3日 下午 01:03
收件者: grafana/grafana
副本: jackeylhm; Mention
主旨: Re: [grafana/grafana] Data Source Http Error (#6863)


@jackeylhm<https://github.com/jackeylhm> HTTP Error Bad Gateway means that the Graphite server is not reachable from 192.168.56.102. Is Graphite installed on the same machine as the Grafana server? Can you navigate to Graphite web on http://192.168.56.102:8080 in your browser?

As this is not a bug in Grafana, in future could you please ask your question on the community site instead -> https://community.grafana.com

**Comment by daniellee** [comment]
@jackeylhm these issues are for bugs/problems with Grafana.  Grafana is a totally separate product to Graphite. We can't provide support for setting up Graphite and monitoring in this forum. Here are some articles to help get you started:

- [Graphite](https://graphiteapp.org/#gettingStarted)
- [InfluxDB[(https://www.digitalocean.com/community/tutorials/how-to-monitor-system-metrics-with-the-tick-stack-on-centos-7)
- [StatsD](https://www.digitalocean.com/community/tutorials/how-to-configure-statsd-to-collect-arbitrary-stats-for-graphite-on-ubuntu-14-04)
- [Prometheus](https://www.digitalocean.com/community/tutorials/how-to-use-prometheus-to-monitor-your-ubuntu-14-04-server)

**Comment by jackeylhm** [comment]
Hi Daniel


Thanks, I also have done my work and figured that as a DBA, to use Grafana need to cover quite many areas.


Thanks again.


Jackey


[X]


________________________________
寄件者: Daniel Lee <notifications@github.com>
寄件日期: 2017年5月3日 下午 04:26
收件者: grafana/grafana
副本: jackeylhm; Mention
主旨: Re: [grafana/grafana] Data Source Http Error (#6863)


@jackeylhm<https://github.com/jackeylhm> these issues are for bugs/problems with Grafana. Grafana is a totally separate product to Graphite. We can't provide support for setting up Graphite and monitoring in this forum. Here are some articles to help get you started:

  *   Graphite<https://graphiteapp.org/#gettingStarted>
  *   [InfluxDB[(https://www.digitalocean.com/community/tutorials/how-to-monitor-system-metrics-with-the-tick-stack-on-centos-7)
  *   StatsD<https://www.digitalocean.com/community/tutorials/how-to-configure-statsd-to-collect-arbitrary-stats-for-graphite-on-ubuntu-14-04>
  *   Prometheus<https://www.digitalocean.com/community/tutorials/how-to-use-prometheus-to-monitor-your-ubuntu-14-04-server>

**Comment by unrealTomas** [comment]
Yes, I think the issue is that the Graphite installation is not mentioned at the main install page   http://docs.grafana.org/installation/rpm/   . That misleads tons to people including myself. Only grafana.<version>.rpm is mentioned there to install. Start the service and that is all.

When I nmap my grafana server I see that the 8080 port is not open despite the fact the grafana-server is running(grafana-server opens the port 3000). 
That, indeed, suggest the fact the Grapite component - which is not mentioned clearly - that I guess open the socket <grafanaIP>:8080   ..need to be installed/onlined.
