### ISSUE TITLE
[Feature request] Alerting - Add option If no data or all values are null SET STATE TO "OK"

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#6866]
Sometimes no value returned by a query means everything is ok.
It would be useful to have this option in the Alerting tab:
 If no data or all values are null SET STATE TO "OK"

**Comment by bergquist** [comment]
@amuraru Wouldn't this be the same as `Keep last state`?

**Comment by f1nger** [comment]
I also need it. I have a graph with some errors, where 100 errors - it is an alert, but 0 errors (no data) - that's OK.
Now 0 errors after Alert - is state "No Data" or still state Alert (Keep Last State).

**Comment by amuraru** [comment]
> Wouldn't this be the same as Keep last state?

Not quite @bergquist - imagine you have a graph where only errors are graphed. Then if last state is kept an error alert would be fired.

**Comment by joostfaassen** [comment]
@bergquist It looks like SET STATE TO "OK" was there, but was removed in this commit:

https://github.com/grafana/grafana/commit/489f087fbdbb03eebf57e2b4ec536cf6817f8370

Hopefully this helps in restoring the feature

**Comment by svenmueller** [comment]
Yes, we also have the usecase where we want to alert in case of responses with status code `5xx` but not when having no `5xx` response (= all fine).

**Comment by bergquist** [comment]
Will be available in 4.1.0

**Comment by svenmueller** [comment]
Thx for the heads up 👍
