### ISSUE TITLE
Alerting: Unnecessary default alert settings

### ISSUE THREAD

**Issue by yosshi825** [grafana/grafana#68670]
### 
# What went wrong?

**What happened**:

If I prepare `grafana.ini` , when starting grafana(container image : grafana/grafana-oss:9.5.2) I get an error message.

```
logger=alertmanager org=1 t=XXXX level=error component=alertmanager orgID=1 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: SMTP not configured, check your grafana.ini config file's [smtp] section"
```

**What did you expect to happen**:

When I start Grafana, there are the following alert settings by default.

```
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "route": {
      "receiver": "grafana-default-email",
      "group_by": [
        "grafana_folder",
        "alertname"
      ]
    },
    "templates": null,
    "receivers": [
      {
        "name": "grafana-default-email",
        "grafana_managed_receiver_configs": [
          {
            "uid": "",
            "name": "email receiver",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "<example@email.com>"
            },
            "secureFields": {}
          }
        ]
      }
    ]
  }
}
```

I think it would be good if the setting of `grafana-default-email`was commented out as in sample.yaml below.

- https://github.com/grafana/grafana/blob/33af88481c659e5c67f5556d0ebc9c22d19831d8/conf/provisioning/alerting/sample.yaml#L103

The container image contains a file in `/ usr/share/grafana/conf/provisioning/alerting/sample.yaml` with the settings commented out, but only the settings related to `grafana-default-email` are included when grafana is started.

### 
# How do we reproduce it?

**Step 1**:

- Create a grafana.ini` that you did not set in the '[smtp] section'.

**Step 2**:

- Start the container image(grafana/grafana-oss:9.5.2) by mounting your own file, 'grafana.ini', in'/etc/grafana/'.

**Step 3**:

- Check container logs.

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

None

**Comment by gotjosh** [comment]
Thank you very much for reporting this; two things: 

a) We designed the default configuration to try a provide an out-of-the-box experience with as minimal change as possible. As such, when you start Grafana, and you want to have alerts delivered - all you need to do is configure your SMTP server and edit the destination email on the contact point.

What that achieves is the fact that you don't have to figure out how to do Alertmanager (or contact point, or routing) specific configuration.

b) Changing the default configuration is no small feat, and we consider that a breaking change as such, we'd like to avoid it if the benefits don't offset the complexity.

**Comment by godber** [comment]
Everyone should be aware that the ACTUAL out of the box experience is:

If you configure the outbound SMTP server without knowing you need to reconfigure that default address any alerts will go to the REAL email address `example@email.com`.

So this has the effective of inadvertently leaking potentially sensitive internal operational information to whoever OWNs that email address.  Currently the email address is bouncing email.

**Comment by m4rc77** [comment]
The problem gets even worse when using alert configuration provisioning. 
See https://github.com/grafana/grafana/issues/66087#issuecomment-2414403978

**Comment by gw0** [comment]
This default contact point is still bad in Grafana 12... If a default is needed, it should be named `default` (with a hard-coded UID), the contents of `grafana_managed_receiver_configs` should be removed (a contact point with no delivery method), and preferably provisioned from a file (easy to override).

**Comment by ikosta** [comment]
Here is the solution: https://github.com/grafana/grafana/issues/66087#issuecomment-2875443648
