### ISSUE TITLE
don't use "null value -> connected" by default

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6868]
connected:
* makes it hard to see spots where there is no data,
* is very deceiving when you have nulls, it can make graphs lie to you
* will not show points that can't be connected to a neighbour. e.g. valid points that have a null on both left and right side will simply not show

null as zero can make sense for infrequent statsd counters, but otherwise "null as null" is the winner in my book with the most accurate and useful visualization, so it should be the default.

**Comment by Dieterbe** [comment]
wooohoo!! thanks T

**Comment by adrianlzt** [comment]
With settings by default, this breaks lot of low sampling graphs.

We, for example, take metrics from Icinga, one each 10 minutes. I have to take zoom out to more than 10 days to see something (until _time(auto)_ changes to 10m).

For beginners this is hard, you choose your data and hope to see something.

Related with #7253

**Comment by torkelo** [comment]
Yea, agree that changing this default might have been a mistake, tricky for new users

**Comment by Dieterbe** [comment]
@adrianlzt in your example, is there a point each 10 minutes? or are some of them null? or is the resolution returned by the datasource like minutely so that you end up with 9 nulls for each non-null point ?

I don't understand what's the problem here, sounds like your datasource is returning data in a higher resolution then what your data is, which is probably the real problem?

**Comment by adrianlzt** [comment]
I have a point each 10 minutes (is the performance data returned by the checks executed by Icinga).
Yes, InfluxDB return one point for each period of time defined by _group by time(X)_.
This _X_ is defined automatically by Grafana depending on the timespan and screen resolution (if I remember correctly).

So, if you have one point each 10m, and grafana sets _group by time(10s)_, influxdb will return lots of nulls.

**Comment by torkelo** [comment]
@adrianlzt you can set a low limit for the auto group by time interval using `>10m` syntax. But tricky for new users to have to find that info

**Comment by adrianlzt** [comment]
Yes, and it is also possible to modify the "Null value" or use fill.
But I think the point is if default values should be set for beginners or for advanced users.

**Comment by copenlc** [comment]
I'm running into the same issues as adrianlzt with Icinga2 and InfluxDB.  Is there anyway to change the default setting back to connect vs. null ?

**Comment by mguthrie88** [comment]
Could the default for this be configurable somewhere?

**Comment by adrianlzt** [comment]
Today spending some time trying to understand why some graphs were not shown and hit, one more time, with this.
Maybe could be an option as suggested by @mguthrie88 ?

**Comment by seanlaff** [comment]
I constantly have "empty" graphs because connect-nulls isn't the default. If we don't want to change the default again, allowing a datasource to control this setting would also be helpful.
