### ISSUE TITLE
Time series: logarithmic scale does not work for negative values

### ISSUE THREAD

**Issue by nagylzs** [grafana/grafana#68695]
### 
# What went wrong?

**What happened**:

  - I have a time series panel, where there are negative and positive values
  - I want to switch to logarithmic scale, because the values are on different magnitudes
  - when I change the scale to logarithmic, all points and lines disappear from the panel, it displays nothing

**What did you expect to happen**:

  - any y=f(x) value should be changed to sgn(x)*abs(log(f(x)) before displaying it
  - this would allow logarithmic scaling for positive and negative values at the same time

### 
# How do we reproduce it?

**Step 1**:

- create a time series panel with many points that have negative values

**Step 2**:

- edit the panel, go to axis/scale and change the scale to logarithmic

**Step 3**:

- all points disappear from the panel

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 22.04

### User's Browser?

Chrome 113.0.5672.126

### Is this a Regression?

No

**Comment by leeoniya** [comment]
you should use the Symlog for this case since it is not possible to draw a continuous Y axis through the 0-crossover point.

it should still not draw nothing in the mixed case though, but look like this:

https://leeoniya.github.io/uPlot/demos/log-scales2.html

![image](https://github.com/grafana/grafana/assets/43234/37667a9e-e561-4099-92d2-1ed75029d904)

**Comment by nagylzs** [comment]
Symlogs seems to be working, it handles 0 crossover point.

![image](https://github.com/grafana/grafana/assets/15814836/85ce34f8-d426-49c9-a20e-fafcedd3f4e0)

It might still be a problem that symlog is linear between [-1,1], so if the data is always within that range, then one must apply a transformation on the data to make it log-scale.

Thank you for your help, I'm closing this.

**Comment by leeoniya** [comment]
FWIW, that threshold is adjustable, but will still be static once configured:

![image](https://github.com/grafana/grafana/assets/43234/e908d077-41b4-4634-ada6-37b743be2f80)
