### ISSUE TITLE
[Bug] Incorrect returnvalue on api update datasource

### ISSUE THREAD

**Issue by Griesbacher** [grafana/grafana#6869]
Hi,

when using the api to update an datasource, I got a non JSON object back("<*api.NormalResponse Value>") instead of: "{"message":"Datasource updated"}". Creating works as documented.
Below the form.

Thanks and greetings,
Phillip

- What Grafana version are you using?
4.0.1

- What OS are you running grafana on?
Debian8-64

- What did you do?
Update a datasource:
curl -X PUT localhost:123/api/datasources/5 -H 'Content-Type: application/json' -d '{"id":4,"orgId":1,"name":"asdf","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://127.0.0.1:123","password":"123","user":"123","database":"123","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"jsonData":{},"tlsAuth":{"tlsCACertSet":false,"tlsClientCertSet":false,"tlsClientKeySet":false}}'

- What was the expected result?
{"message":"Datasource updated"}

- What happened instead?
<*api.NormalResponse Value>

**Comment by bergquist** [comment]
Thank you for reporting this!

**Comment by bbinet** [comment]
It seems the fix has not been included in v4.0.2 which was released yesterday.
Any chance this fix could be included in a new release soon?

**Comment by bergquist** [comment]
@bbinet we dont have any plants for 4.0.3 yet. Unless we find more bugs we will most likley release 4.1.0-beta instead.
