### ISSUE TITLE
Fix SQL tests that are running on windows

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#68704]
Please verify the following integration tests are running on windows
pkg/tsdb/mysql
pkg/tsdb/postgres

[Epic](https://github.com/grafana/grafana/issues/67974)
[Example drone run](https://drone.grafana.net/grafana/grafana/117194/1/4)

**Comment by baldm0mma** [comment]
On it.

**Comment by baldm0mma** [comment]
Looks like there are some [failing](https://drone.grafana.net/grafana/grafana/117194/1/4) backend tests.

**Comment by baldm0mma** [comment]
Failures:
- github.com/grafana/grafana/pkg/tsdb/mssql
- github.com/grafana/grafana/pkg/tsdb/mysql
- github.com/grafana/grafana/pkg/tsdb/postgres
