### ISSUE TITLE
SparklineCell: freezes browser if there's only one value in data frame

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#68702]
If sparkline data frame contains a single value, it can freeze browser because uPlot gets into an infinite loop here: https://github.com/leeoniya/uPlot/blob/91b459fbcb86d39d1e7dfafd16ee5db9872987f7/dist/uPlot.esm.js#L1328

Setting `sparkline.timeRange` would fix it,  but time range is currently not available for table panel cells.

Also: should probably null-fill sparkline data. Currently if there's data not for the entire time range, sparkline will misleadinly render across entire X axis, as illustrated below:

![image](https://github.com/grafana/grafana/assets/847684/c6b05bc5-3c3d-48dc-857d-22f5ee3539de)

**Comment by mdvictor** [comment]
Hey folks, I'll have a look into null-filling the data

**Comment by domasx2** [comment]
Thanks a lot @mdvictor
