### ISSUE TITLE
Nested folders analytics

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#68707]
To understand how dashboards are managed, including the nested folders experience, we would like to add a set of Rudderstack events.

Feature | Event Name | Event Properties | Description | Visual
-- | -- | -- | -- | --
Folder created | grafana_manage_dashboards_folder_created | **is_subfolder**: true/false (based on whether it has a parent_id) **folder_depth** (if we can calculate this): 0 if it's in the root, 1 for a level deeper etc. | Clicked "Create" to add new folder. |  ![Image](https://github.com/grafana/grafana/assets/97596715/6cbf57b4-b9e9-49a9-9759-45b0eca9240f)
Item deleted | grafana_manage_dashboards_item_deleted | **item_type**: folder,dashboard,alert,library_panel (comma separated list of items in the delete operation), **source**: tree,folder_actions | Clicked "Delete' to delete items from the Browse Dashboards view. |  ![Image](https://github.com/grafana/grafana/assets/97596715/54f35710-e078-4e4e-ac2c-1b28156b3117)
Item moved | grafana_manage_dashboards_item_moved | **item_type**: folder,dashboard,alert,library_panel  (comma separated list of items in the delete operation) | Clicked "Move' to move items in the Browse Dashboards view. |  ![Image](https://github.com/grafana/grafana/assets/97596715/2482272c-adca-4365-96bb-5733b2c63cbd)
New button clicked | grafana_menu_item_clicked | **from**: "dashboard_page" | Clicked "New" on the browse page. |  |

- [ ] ensure we don't regress previous emitted events from the old view e.g. `search_query_submitted`, `search_result_clicked` (these are probably fine) and `browse_item_clicked` (this one probably doesn't exist)

**Comment by yaelleC** [comment]
Should we prefix our events with `grafana_` to follow [RS best practices](https://docs.google.com/document/d/1MTS5O5qsxtDptzN6AvdMRRGP38pvFc1NULsQKQN_z2U/edit#bookmark=id.z50v0471q8l7)?

Also do we have frontend logs for errors? It feels a bit wrong having a user interaction event for an error.

Alternatively we could add props to `manage_dashboards_item_deleted` like a boolean for `success` and/or a string of `error`. That way we could easily get the % of successful delete actions without joining tables 😛
