### ISSUE TITLE
Add support for the new webhook auth format in Alertmanager

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#68706]
Webhook contact point for external Alertmanagers only supports the old format of bearer authentication configuration
```
http_config: {
  bearer_token: '__TOKEN__',
  bearer_token_file: '__TOKEN_FILE_PATH__',
}
```

This format has been deprecated in favour of the new one:
```
http_config: {
  authorization: {
    type: 'Bearer' // default
    credentials: '__TOKEN__',
    credentials_file: '__TOKEN_FILE_PATH__',
  }
}
```

The UI should support both formats and encourage users to migrate from the old to the new one
Prometheus documentation of `http_config` field https://prometheus.io/docs/alerting/latest/configuration/#http_config
Prometheus HttpConfig code https://github.com/prometheus/common/blob/main/config/http_config.go#L287-L312

We should identify the oldest version of Prometheus that supports the new format. If it's old enough (Grafana might have some requirements about the oldest version of Prometheus) we can deprecate the old way of configuration

**Comment by khushijain21** [comment]
Hello, I'd like to work on this, can you direct me to the file location? and where in the UI is this configurable?
