### ISSUE TITLE
Dashboard API: Export and import dashboard , problem with folder reuse

### ISSUE THREAD

**Issue by Shamilen** [grafana/grafana#68708]
### 
# What went wrong?

**What happened**: 
I'm trying to create automatization of export dashboards, folders, datasources. 
- Trying to export dashboard from folder "Test" via api
- Delete dashboard via UI
- Trying to import dasboard via api
- Open UI Grafana, dashboard was recreated at "General" folder. 

**What did you expect to happen**:

  - Open UI Grafana, dashboard was recreated at "Test" folder. 

### 
# How do we reproduce it?

Reference was taken from https://gist.github.com/crisidev/bd52bdcc7f029be2f295
- Login to Grafana, create folder "Test" and in this folder dashboard "Test_dashboard".
- Login to Orgs, get list of dashboards via api
```
curl --silent -u $user:$pass "${grafanaurl}/api/search?query=&" | jq -r '.[] | select(.type == "dash-db") | .uid'
```
- Download dashboard via curl 
```
curl --silent -u $user:$pass "${grafanaurl}/api/dashboards/uid/$dash" | jq -r . >${dash}.json
```
- Delete dashboard from UI Grafana.
- Import this dashboard to Grafana via curl 
```
cat $FILE | jq '. * {overwrite: true, dashboard: {id: null}}' | curl -X POST -H "Content-Type: application/json" -u $user:$pass "$grafanaurl/api/dashboards/db" -d @- ;
```
- Open UI Grafana, dashboard was recreated at "General" folder. 

### 
# What Grafana version are you using?

v9.5.2

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by zuchka** [comment]
I think the better place for this discussion on that Gist's thread. that thread has been going for years and it is exactly the place for this kind of question. Then everyone can benefit from the answer, more so than here

**Comment by zuchka** [comment]
also, I would highly recommend using Terraform for this kind of work

**Comment by sfranzis** [comment]
Folder information in the export is not were import API expects it to be. You have to refactor the json a bit.

`
for dash in $(curl -s -k -H "Authorization: Bearer $KEY" $HOST/api/search\?query\=\& | jq -r '.[] | select(.type == "dash-db") | .uid'); do
  curl -s -k -H "Authorization: Bearer $KEY" $HOST/api/dashboards/uid/$dash \
    | jq '. |= (.folderUid=.meta.folderUid) |del(.meta) |del(.dashboard.id) + {overwrite: true}' \
    > dashboards/${dash}.json
  echo "Dashboard: ${dash} saved."
done
`

Details see here: https://medium.com/@stefan4all/grafana-export-import-of-dashboards-39cc502faa2c

**Comment by saibug** [comment]
@sfranzis same pb with me, I tested export and import scripts, and all dashboards are pushed into the wrong destination :(
