### ISSUE TITLE
Feature Request: Custom Annotation Step Size

### ISSUE THREAD

**Issue by ericuldall** [grafana/grafana#6871]
I think that being able to customize the step size of an annotation would be nice to have. Is there any reason this feature would not be accepted as a PR?

I'd be interested in working on it, but don't want to spend any dev time if it's going to be rejected.

**Comment by ericuldall** [comment]
It seems this has been added in PR #6168 , but the OP closed it.
Considering the simplicity of the change, why  not let the client customize step size?

**Comment by ericuldall** [comment]
For more context...

We are having an issue where the step size is different from a graph. Graph is running a 5s step size, so at certain zoom levels the annotations just disappear, which is very inconsistent behavior. If I set my graph step size to 60s, the annotations show up at any zoom level, but we sacrifice data resolution, so it's a bit of trade off.

**Comment by ivanahuckova** [comment]
It seems that thee steps for annotation was already implemented
![image](https://user-images.githubusercontent.com/30407135/120321012-17f18100-c2e3-11eb-8f82-20bc2e61908c.png)
