### ISSUE TITLE
Docs: Open TSDB docs invalid table format

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#68723]
Take a look at:
https://grafana.com/docs/grafana/latest/datasources/opentsdb/

The table is all wonky
<img width="847" alt="image" src="https://github.com/grafana/grafana/assets/109082771/232026b4-930b-481e-83b3-1fdd510e2a73">

**Comment by Eve832** [comment]
@lwandz13 can you please take a look at this and update the ticket status in our [Doc team board](https://github.com/orgs/grafana/projects/69)?

**Comment by lwandz13** [comment]
Merged PR:

https://github.com/grafana/grafana/pull/69281
