### ISSUE TITLE
Dashboard: datetime variables apply timezone inconsistently

### ISSUE THREAD

**Issue by markalex2209** [grafana/grafana#68748]
### 
# What went wrong?

I’m trying to use hour’s part of datetime variable in query, like this `${__from:date:HH}`. It returns hours in timezone local to my browser.

But `${__from:date}` or `${__from:date:iso}` returns date in UTC.

I expect them to behave similarly, either both UTC, or both local. Or at least clear indication of behavior specifics at the documentation.

Also, same behavior is happening to any custom variable containing timestamp.

### 
# How do we reproduce it?

Paste into panel name, for example, the following `${__from:date:iso} ${__from:date:HH}`. 

If your timezone differs from UTC, you'll see different hours. 

![Screenshot from 2023-05-17 00-42-46](https://github.com/grafana/grafana/assets/55829038/65916c0f-5325-4838-8ead-ce6405b29417)

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

None

### Anything else to add?

I'm not sure which timezone config at play.

I can see same behavior at play.grafana.com too, though timezone of my account there is selected as UTC.

**Comment by ivan-srsen** [comment]
Same issue here

**Comment by mellieA** [comment]
@markalex2209 there was a similar feature request opened here: https://github.com/grafana/grafana/discussions/38175 

The comments indicate that it's expected that custom time will be in the local timezone since :date and :iso default to UTC. 

The [docs](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__from-and-__to) don't explicitly state that custom time format will follow the browser time. Is that what you'd like to see as an outcome for this issue?

**Comment by markalex2209** [comment]
@mellieA I agree with linked feature request.

> Is that what you'd like to see as an outcome for this issue?

Yes. At least until mentioned feature request is not implemented, it would be nice to describe this behavior in official documentation.

**Comment by mellieA** [comment]
@markalex2209 added a PR related to this issue to fix the docs. I'll move this issue to the dashboard squad

**Comment by mellieA** [comment]
https://github.com/grafana/grafana/pull/69016 updates the docs with the current behavior

community comments indicate they would like to be able to choose whether the custom date format uses UTC or browser time.

**Comment by ivan-srsen** [comment]
I would like to have the ability to specify the desired timezone for a variable's return value. For instance, if my dashboard time is set in CET (Central European Time), I would like the option to use the variable as UTC (Coordinated Universal Time), and vice versa.
