### ISSUE TITLE
Dashobard: word value appears on legend

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#68746]
### 
# What went wrong?

**What happened**:

  -  the word value appears in legend as prefix 

**What did you expect to happen**:

  - the word value not to appear

### 
# How do we reproduce it?

See this thread

https://community.grafana.com/t/sql-queries-that-used-to-work-no-longer-do/87911/4

Create a time series dashboard

Install ms sql server plugin

Using sql server pkugin create a query with

Time
Metric
Value

Select table and not time series

Using transformation choose wide time series

Notice the legend

### 
# What Grafana version are you using?

Lates v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows

### User's Browser?

Chrome 

### Is this a Regression?

None

### Are Datasources involved?

Ms sql server 

### Anything else to add?

✌

**Comment by torkelo** [comment]
> Select table and not time series

Why not use time series? 

> Using transformation choose wide time series

If you want to graph it I think you need to choose Multi-frame time series.
