### ISSUE TITLE
Grafana queries mysql using the $__unixepochfilter macro function, causing the index to take effect

### ISSUE THREAD

**Issue by hehua2018** [grafana/grafana#68758]
### 
# What went wrong?

Grafana queries mysql using the $__unixepochfilter macro function, causing the index to take effect

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

ubuntu

### Is this a Regression?

None

### Anything else to add?

Grafana queries mysql using the $__unixepochfilter macro function, causing the index to take effect

**Comment by mellieA** [comment]
@hehua2018 can you share an example of what you're seeing in the query versus what you expected to see? A screen recording or screenshots with sensitive data masked are very helpful for us to understand the context of what is going wrong.

**Comment by gabor** [comment]
as we got no response in a long time, we're closing the issue. if we get new info in the future, we can reopen it.
