### ISSUE TITLE
[Bug] annotations fail if applied on a timespan of 30 days or more

### ISSUE THREAD

**Issue by davidkarlsen** [grafana/grafana#6876]
Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? prometheus
- What OS are you running grafana on? docker on RHEL linux 7.3
- What did you do? add an annotation, which seems to work fine, until I set timespan to 30 days for panel, then I get 400 bad request
- What was the expected result? do render the graph, including any annotations
- What happened instead? the graps render, but I get a red box in the upper right corner telling me bad request

annotation:
ALERTS{alertstate="firing"}

**Comment by torkelo** [comment]
maybe a bug in prometheus? what does prometheus returns? Please open chrome dev tools network tab and inspect the response from prometheus

**Comment by mtanda** [comment]
Sorry, this is a bug of datasource plugin.

Need to calibrate step before calling `performTimeSeriesQuery()` in annotation query.
https://github.com/grafana/grafana/blob/v4.0.2/public/app/plugins/datasource/prometheus/datasource.ts#L187

The check code is like following.
https://github.com/grafana/grafana/blob/v4.0.2/public/app/plugins/datasource/prometheus/datasource.ts#L91-L95

The calibrated step is referred at other place, so just moving the code to `performTimeSeriesQuery()` cause side effect.
https://github.com/grafana/grafana/blob/v4.0.2/public/app/plugins/datasource/prometheus/datasource.ts#L239-L253

I agree with datasource plugin code need refactoring...

**Comment by davidkarlsen** [comment]
Too many series are returned:
```
{status: "error", errorType: "bad_data",…}
error
:
"exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)"
errorType
:
"bad_data"
status
:
"error" 
```

It seems mtanda is indicating it is a bug with the plugin?

**Comment by davidkarlsen** [comment]
@torkelo  ping?
