### ISSUE TITLE
[Feature request] Add query builder to make template variables with complex datasource queries

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#6877]
Datasources used: Graphite, Elasticsearch, Zabbix, InfluxDB
OS: Ubuntu, SLES, Solaris x64, Solaris Sparc v9

When doing queries on graphite, template queries are easy. For other datasources like elasticsearch providing the lucene query is hard, or other brutal queries is hard. It would be ideal to add the query builders to the templating panel, just like they are in the main queries in panels.

**Comment by hugohaggmark** [comment]
This feature request is one step closer to being implemented with #28217.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
