### ISSUE TITLE
[Feature request] Ability to lock time range selection for dashboard

### ISSUE THREAD

**Issue by CarusDave** [grafana/grafana#6878]
This might sound like an odd request, but for some of our dashboards, we don't want a user that is viewing "live" data to move away from a predetermined time selection.
So having the option to lock the time would be very useful to improve the end user experience.
I'd thought an option like this might exist under the Time picker settings tab.

**Comment by torkelo** [comment]
is this for performance reasons (not overloading data backend?)

**Comment by yesoreyeram** [comment]
It would be nice to have something similar to "time picker" in dashboard settings. So dashboard admins can specify what time ranges can user select from quick range and also it would be nice to maximum value for "From" in time range selection.

**Comment by CarusDave** [comment]
Certainly reducing unnecessary load on databases is desirable. Unlike experienced dashboard users, it's surprisingly common to have a casual user pick a time range that doesn't suit the data and breaks the intended design of a particular dashboard.  I think as a dashboard editor you should have the options to control the user experience. So, in this case, we have a dashboard with an array of singlestat panels to show current live stats and want to guarantee the user sees the correct data.

**Comment by torkelo** [comment]
closing this as it is similar to this issue, https://github.com/grafana/grafana/issues/4288
