### ISSUE TITLE
[Bug] Alias pattern applies pattern for query A for all queries (B, C, D, ...)

### ISSUE THREAD

**Issue by rohit01** [grafana/grafana#6880]
Summary: Incorrect values in graph legend (textual representation) due to alias.

- We are using the following grafana versions (issue happening on both):
    - 3.0.4-1464167696
    - 4.0.0-1479463563beta1

- Datasource: OpenTSDB
- OS: Ubuntu 14.04
- Created dashboard on top of metrics. The dashboard behavior is uncertain. A lot of times, the legend in graph is distorted due to incorrect alias value being displayed.
- Alias pattern for all queries must be distinct from each other. The pattern for query A should not be applied to query B.
- Getting duplicate values in legend with different lines. Graph is confusing. Screenshot attached.

Incorrect Scenario:
<img width="1667" alt="incorrect-scenario" src="https://cloud.githubusercontent.com/assets/1710801/21012308/5f290b82-bd7b-11e6-85f3-1137154c7dc8.png">

Working Scenario:
<img width="1668" alt="working-scenario" src="https://cloud.githubusercontent.com/assets/1710801/21012314/6659c7ca-bd7b-11e6-8e4c-18221e43ff35.png">

Not exactly sure, why it sometimes work and sometimes not.

**Comment by torkelo** [comment]
this is a bug in OpenTSDB (or a limitation). But if you upgrade to OpenTSDB 2.3+ (I think) it should work

**Comment by rohit01** [comment]
@torkelo Thanks for the update. OpenTSDB 2.3 is still not released (its RC2). Could you point us to the issue as well.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1876
