### ISSUE TITLE
Panel: Alert list - Alert instance label

### ISSUE THREAD

**Issue by FLeven** [grafana/grafana#68804]
### 
# What went wrong?

**What happened**:

  I tried to filter a specific job from the alert list panel:
  `job!="printer"`

**What did you expect to happen**:

Get a list of all alerts except the ones from the job "printer", a positiv query for only getting alerts from the job="printer", works.

### 
# How do we reproduce it?

**Step 1**:

Add a "Alert list" Panel to your dashboard

Got to **Filter** and **Alert instance label**
_Filter alert instances using label querying, ex: {severity="critical", instance=~"cluster-us-.+"}_

Add:
  `job!="printer"`

**Step 2**:

Click to another setting and you see alerts disappearing from the list that do not qualify for the filter.

### 
# What Grafana version are you using?

9.5.2

### 
### Is the bug inside a Dashboard Panel?

yes, Alert List

_No response_

### Grafana Platform?

Docker

### User's OS?

Windows 2019

### User's Browser?

Edge 113.0.1774.50

### Is this a Regression?

None

### Are Datasources involved?

Prometheus

**Comment by armandgrillet** [comment]
I see this working in Grafana 10:
<img width="1298" alt="SS 2023-06-09 at 11 15 17" src="https://github.com/grafana/grafana/assets/2117580/1c4433e5-8bc2-4759-b2ce-7b0f5a802a0d">
This might be due to https://github.com/grafana/grafana/pull/66267 having been merged in Grafana 10 and fixing the issue. Grafana 10 should be available next week.

**Comment by FLeven** [comment]
Try **!=** or is this not implemented ?

**Comment by armandgrillet** [comment]
The last part of the filter is that: `pod!="aggregator-0"`.

**Comment by FLeven** [comment]
Ok, I am not sure if I like to test 10 the next weeks, my issues was based on grafana alerts.

**Comment by FLeven** [comment]
works, in version 10.x, thx.
