### ISSUE TITLE
[Bug] AWS datasource cannot select or group by single dimension

### ISSUE THREAD

**Issue by yesman85** [grafana/grafana#6881]
Using Grafana v4.0.0 (commit: v4.0.0) I am using a AWS Datasource.

I want to show uptime per HealthCheckId in a separate graph, so I setup templating like this:

`dimension_values(us-east-1,AWS/Route53,HealthCheckStatus,HealthCheckId)` as $Sites with All and Multi-Value selected.

this will give me a list of all the HealthCheckIds (unfortunately they are just ID's so a little useless).

And my query looks like this:
![image](https://cloud.githubusercontent.com/assets/1142915/21019773/f5a77906-bd2e-11e6-8b16-1d34a412d56d.png)

Problem is that is when I select multiple values, it will show me multiple graphs, but it will also show all dimensions in each of the graphs.

It looks like it's making multiple requests to the server and then aggregating the results together in the graph.

There is no option to group by just a single dimension per graph like other data sources.

**Comment by mtanda** [comment]
Sorry it's a bug of datasource plugin.
This issue might be fixed by https://github.com/grafana/grafana/pull/6618 .
Please try latest Grafana version.
