### ISSUE TITLE
[Bug] Multiple Grafana Docker containers conflicting authentication

### ISSUE THREAD

**Issue by scjoiner** [grafana/grafana#6883]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.01 and 3.0.2 containers
- What datasource are you using?
InfluDB
- What OS are you running grafana on?
Docker on Synology
- What did you do?
Created multiple Grafana containers with different ports and attempted to log on to both containers to compare dashboards
- What was the expected result?
Being logged in to both instances simultaneously
- What happened instead?
Both grafana instances log out immediately

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by fg2it** [comment]
@scjoiner  Strange. I do the same thing with 3.1.1 and 4.0.1 and I don't face this problem. To have this working multiple grafana docker containers on same host, you surely have to use different ports, but you probably have to use different data volumes too for `/var/lib/grafana`. I would look this way to explain your problem.
For example, if you strictly follow the [recommended way](https://github.com/grafana/grafana-docker#grafana-container-with-persistent-storage-recommended) to start grafana docker but only change port and tag, I wouldn't surprise this could lead to what you see.

**Comment by torkelo** [comment]
Cookies ignore ports(browser  limitation) , so if you need this your have to change session cookie name (grafana config option)
