### ISSUE TITLE
$__from variable wrong time format

### ISSUE THREAD

**Issue by ivan-srsen** [grafana/grafana#68878]
### 
# What went wrong?

$__from variable displays dashboard time, but $__from:HH displays browser hours.

$__from variable should display dashboard time in both cases.

### 
# How do we reproduce it?

Open grafana and use a variable somewhere

### 
# What Grafana version are you using?

v9.2.4

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by mellieA** [comment]
@krishnaduttPanchagnula Thank you for noting that this is a duplicate. I'll close it in favor of the first one if you want to follow #68748
