### ISSUE TITLE
[Bug] Template variables from Prometheus have extra escape characters added

### ISSUE THREAD

**Issue by seanhoughton** [grafana/grafana#6888]
When using templates with Prometheus datasources it looks like period characters are escaped which causes incorrect value lookups.

Here's a comparison of the ajax queries Grafana is making with the following query
`rate(wmi_cpu_time_total{instance="$wmi_instance", mode="$wmi_cpu_mode"}[1m])`

**Working -** without using templates, manual value:
`rate(wmi_cpu_time_total%7Binstance%3D%22shoughton-10.redacted.com%22%2C%20mode%3D%22user%22%7D%5B1m%5D)`

**No data** - when using a template, selecting the same value (note the %5C backslash charactrers)
`rate(wmi_cpu_time_total%7Binstance%3D%22shoughton-10%5C%5C.redacted%5C%5C.com%22%2C%20mode%3D%22user%22%7D%5B1m%5D)`

My template query looks like this:

`label_values(wmi_cpu_time_total, instance)`

Data source: wmi_exporter at https://github.com/martinlindhe/wmi_exporter
Grafana: v4.0.2 stock docker container from dockerhub
Prometheus: v1.4.1 stock docker container from dockerhub

**Comment by torkelo** [comment]
Try using the =~  operator in your prometheus query. Or change the template variable options and remove the Multi & All options (they cause the values to be regex formated as that is the only way multi values can be filtered)

**Comment by dormunis** [comment]
any progress with this issue?

**Comment by cybervedaa** [comment]
> Try using the =~ operator in your prometheus query. Or change the template variable options and remove the Multi & All options (they cause the values to be regex formated as that is the only way multi values can be filtered)

Removing the "All" option would mean that we cannot use it in conjunction with Grafana's "Repeat Panel" functionality.
Simple example - If i am trying to show a dashboard with singlestat panels for all instances in my prometheus job.

**Comment by torkelo** [comment]
Use regex operator in query or ${varnade:raw}

**Comment by cybervedaa** [comment]
Thank you for the quick response!
Going thru the documentation on variables found here -
http://docs.grafana.org/reference/templating/ , under the "Advanced
Formating options"
I noticed glob, regex, pipe, csv, distributed, lucene. But didnt realize
there was a type "raw" to force it back to it's original format
I will give it a try

**Comment by abhty822** [comment]
> Use regex operator in query or ${varnade:raw}

thank you it's really helpful to me!

**Comment by johanjvv089** [comment]
> Use regex operator in query or ${varnade:raw}

This worked for me!  I wanted to select multiple "applications" to show on my dash.
my full query before the fix: `rate(application_httprequests_transactions_count{env="$environment",app="$application",server="$server"}[1m])*60`
after the fix:
`rate(application_httprequests_transactions_count{env="$environment",app="${application:raw}",server="$server"}[1m])*60`
