### ISSUE TITLE
[Bug] Images attached to alert e-mails shows no graph

### ISSUE THREAD

**Issue by martbhell** [grafana/grafana#6889]
Please include this information:
- What Grafana version are you using? 4.0.2
- What datasource are you using? graphite
- What OS are you running grafana on? CentOS6
- What did you do? Generated an alert e-mail.
- What was the expected result? To get the image of the graph attached in the e-mail
- What happened instead? I got an e-mail with the attached image, but there's no line in the graph, there is only the name of the graph and the "loading" symbol in the top right corner. The image looks the same in /var/lib/grafana/png (http://imgur.com/a/EpUUW). In grafana the graph looks as it should (also in http://imgur.com/a/EpUUW ). No extra information as far as I could see in the "trace" level log.

If it relates to *alerting*
- An image of the test execution data fully expanded. http://imgur.com/a/EpUUW

And the part of grafana.log
<pre>
t=2016-12-09T07:47:17+0200 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:5000 protocol=http subUrl=/grafana
t=2016-12-09T07:47:18+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:47:22+0200 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2016-12-09T07:47:28+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:47:38+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2016-12-09T07:47:38+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=1
t=2016-12-09T07:47:38+0200 lvl=dbug msg=GetAlerts logger=alerting.extractor
t=2016-12-09T07:47:38+0200 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=1
t=2016-12-09T07:47:38+0200 lvl=dbug msg="Alert updated" logger=sqlstore name="Alewrts! alert" id=1
t=2016-12-09T07:47:38+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:47:48+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:47:58+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:48:01+0200 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Alewrts! alert" id=1
t=2016-12-09T07:48:02+0200 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=ok prev state=alerting
t=2016-12-09T07:48:05+0200 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=1 sent count=1
t=2016-12-09T07:48:05+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/alert-testing?&panelId=6"
t=2016-12-09T07:48:08+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2016-12-09T07:48:17+0200 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/CttFfuDXfz0Lsof0T9uh.png
t=2016-12-09T07:48:17+0200 lvl=info msg=uploaded logger=alerting.notifier url=
t=2016-12-09T07:48:17+0200 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=1 isDefault=false
t=2016-12-09T07:48:17+0200 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[me@example.com]
t=2016-12-09T07:48:17+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-771.030 alertId=1 name="Alewrts! alert"
 firing=false
</pre>

With grafana 4.0.1 it was the same.

Actually the problem might be related to phantom - if I click on "direct shared image" I get the above kind of image - and it does take over 10 seconds for it to show up. We have an Apache httpd proxypass to http://localhost:5000 for
<pre> root_url = %(protocol)s://%(domain)s/grafana/
</pre>

**Comment by torkelo** [comment]
strange, should work with nginx http proxy here.

**Comment by martbhell** [comment]
The direct images are working for some graphs, but not for all, the first URL below does not work (show any lines in the graph).

grafana.log says "image rendered" for both working and non-working in trace log.
The direct image that works takes 1-4seconds and the one that doesn't take 12s.
phantomjs command (from ps) only has a different panelId, renderKey and png filename.

From "direct graph" link the URL is longer but the first one here does not work:
https://URL/grafana/render/dashboard-solo/db/alert-testing?panelId=6

And this works: https://URL/grafana/render/dashboard-solo/db/alert-testing?panelId=3

I've been trying to launch phantomjs manually from the CLI with debug=true while the image is loading and it seems to be a way to reproduce the error:

<pre>
# /usr/share/grafana/vendor/phantomjs/phantomjs --debug=true --ignore-ssl-errors=true /usr/share/grafana/vendor/phantomjs/render.js url="http://localhost:5000/dashboard-solo/db/alert-testing?panelId=6" width=1000 height=500 png=/tmp/g5.png domain=localhost $(ps fu -ea|grep [p]hantomjs|awk '{print $20}') >/tmp/not_working_id6.log 2>&1
</pre>

Then I took out the timestamps and debug level from the logs and did a diff -u.

In the one that's not working I see:
<pre>
+WebPage - evaluateJavaScript "(function() { return (function () {\n        if (!window.angular)
+WebPage - evaluateJavaScript result QVariant(Invalid)
+Network - Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" ) URL: "https://ourgraphiteDNS.example.com/render"
+WebPage - evaluateJavaScript "(function() { return (function () {\n        if (!window.angular)
+WebPage - evaluateJavaScript result QVariant(Invalid)
+Object]
+TRACE:
+http://localhost:5000/public/app/boot.85c49108.js: 38
+
+phantomjs://code/render.js:46 in onError
+WebPage - evaluateJavaScript "(function() { return (function () {\n        if (!window.angular)
+WebPage - evaluateJavaScript result QVariant(Invalid)
</pre>

and a lot more of these:
<pre>
+WebPage - evaluateJavaScript "(function() { return (function () {\n        if (!window.angular)
+WebPage - evaluateJavaScript result QVariant(Invalid)
</pre>

So maybe some network issue still?

If I do a
<pre>
curl https://ourgraphiteDNS.example.com/render
</pre>

I get a .PNG nicely.

**Comment by martbhell** [comment]
Got images working in the alert e-mails if I changed the data source to proxy for http://localhost:80 instead of a direct to https://URL.example.com 

On localhost:80 we run another apache httpd proxy of graphite but for localhost only - without ssl.

I'll close this. But if you want me to look at some more things please just write in here.
