### ISSUE TITLE
[TraceQL] Support new return value from /api/search

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#68894]
Tempo has made some backwards compatible adjustments to the return of `/api/search` that we would like Grafana to support.

PR here: https://github.com/grafana/tempo/pull/2490

The 3 changes are:
1) Added a `spanSets` field next to the `spanSet` field. `spanSet` is deprecated. With the addition of grouping to the TraceQL language a given trace can now return multiple spansets. Before a single trace was guaranteed to only ever return 1 spanset. The old `spanSet` field will continue to be populated to support old versions of Grafana for now.
2) Added attributes at the spanSet level. operations like `avg()`, `by()` can now attach attributes to the spanset. These need to be rendered.
3) The "matched" field is now correct. We would like to display it.

Example:
```
    {
      "traceID": "473e4aa02bb86b638cadf2e844d46335",
      "rootServiceName": "shop-backend",
      "rootTraceName": "list-articles",
      "startTimeUnixNano": "1684847482395359206",
      "durationMs": 620,
      "spanSet": {
        "spans": [
          {
            "spanID": "bc044ad6510eb2d3",
            "startTimeUnixNano": "1684847482395359206",
            "durationNanos": "620306265",
            "attributes": [
              {
                "key": "service.name",
                "value": {
                  "stringValue": "shop-backend"
                }
              }
            ]
          },
        ],
        "matched": 3,                                                   ### This field is now correct. We would like it displayed at the spanset lvl.
        "attributes": [                                                    ### These attributes are new. We would like them displayed at the spanset lvl.
          {
            "key": "by(resource.service.name)",
            "value": {
              "stringValue": "shop-backend"
            }
          }
        ]
      },
      "spanSets": [                                                    ### spanSets are new and should be displayed instead of spanSet
         ... 
      ]
    }
```

**Comment by joey-grafana** [comment]
Added support for `spanSets` in https://github.com/grafana/grafana/pull/71953. Also still supports `spanSet`.
