### ISSUE TITLE
[Feature request] Is possible to develop a plugin for alerting notifications?

### ISSUE THREAD

**Issue by pfctgeorge** [grafana/grafana#6890]
The alerting in Grafana is easy but powerful.

We want to develop something like a plugin to support more notification types, like SMS alerting. But these notification types may not fit for all of users in Grafana.

So is possible to develop a plugin to support our customized alerting notification type?

**Comment by torkelo** [comment]
we need to develop support for backend plugins first. https://github.com/grafana/grafana/issues/6841

But this can also be done by supporting alert notifications executed via local shell command (which can then do the SMS work)

**Comment by ddhirajkumar** [comment]
@torkelo The referenced issue #6841 does not talk about 'notifiers'. Could you include that in the ticket description?
We are looking at exactly this same thing @pfctgeorge  mentioned. If the plug-in mechanism is extended to 'notifiers' then that would be really helpful.

Also, could you elaborate more on the local shell command approach? I can definitely write a notifier which executes a shell command (and this can in-turn do anything that I want), but this capability isn't yet available in Grafana, right?

**Comment by bergquist** [comment]
@ddhirajkumar its not available yet. 

You could write your own webserver that receives webhooks from grafana and pass the notification to what ever service you like :) Webhooks are currently available in Grafana.

**Comment by ddhirajkumar** [comment]
@bergquist I had explored this option :-) Only downside is that I need to host and manage this intermediate service.

**Comment by luislobo** [comment]
@ddhirajkumar you can use https://zeit.co/now

**Comment by surajtripathi** [comment]
@bergquist is to possible to develop a plugin for alert notifications with grafana version [7.0](https://grafana.com/blog/2020/05/18/grafana-v7.0-released-new-plugin-architecture-visualizations-transformations-native-trace-support-and-more/#plugins-platform)?
webhook does not satisfy our requirement for custom payload #6956

**Comment by bergquist** [comment]
Pluggable alert notifiers are not implemented yet
