### ISSUE TITLE
Prometheus: Create endpoint checker for api calls

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#68907]
We have different versions of Prometheus and different flavors of Prometheus like Mimir, Thanos, Cortex, etc. Some of those are supporting particular endpoints and some of them are not. Like `labelsMatch` endpoint or `rules` endpoint. 

In order to handle API calls properly we need to know if the given flavor and version of Prometheus is supporting a particular endpoint. We should not make calls to a non-supported endpoint. It is just a waste of resources. 

Related Issues:
- https://github.com/grafana/grafana/pull/68801

**Comment by gtk-grafana** [comment]
I'm almost thinking a much simpler config field that just allows folks to build a deny-list for api endpoints, the use-cases don't always match up with the type/version.

**Comment by gtk-grafana** [comment]
Related: https://github.com/grafana/grafana/pull/70903
