### ISSUE TITLE
News Visualization: RSS Feed 

### ISSUE THREAD

**Issue by neillfontes-klar** [grafana/grafana#68906]
### 
# What went wrong?

**What happened**:

  - I tried to add two different atom feeds to the source data of the news visualizer and ended up with an exception:
    - https://github.com/junit-team/junit5/releases.atom
    - https://github.com/karatelabs/karate/releases.atom

**What did you expect to happen**:

  - The feeds would be visible on the dashboard

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create a new dashboard

**Step 2**:

- Set the visualization for "News" 

**Step 3**:

- Add `https://github.com/junit-team/junit5/releases.atom` as the URL input 

**Step 4**:

![image](https://github.com/grafana/grafana/assets/76950991/b01808d3-ea4f-44c8-a733-52ed5117366a)

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

MacOS

### User's Browser?

Version 113.0.5672.92 (Official Build) (x86_64)

### Is this a Regression?

None

**Comment by tskarhed** [comment]
This is the expected behavior, but I do think we need a better error message with some guidance what to do about it.

**Comment by neillfontes-klar** [comment]
@zuchka I might as an alternative. Thanks.

@tskarhed How so? My expectation would be for it to simply work, as Atom feeds are clearly stated as supported. 

For reference: 

[JUnit Atom feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgithub.com%2Fjunit-team%2Fjunit5%2Freleases.atom)

**Comment by tskarhed** [comment]
I agree with you, it would be nice if it just simply worked. However, you need a CORS proxy for it to work. https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/news/

**Comment by neillfontes-klar** [comment]
I agree with the proposal implemented in https://github.com/grafana/grafana/pull/69060, otherwise it's very hard to understand it's a pre-requirement. I will give it a try in a local install as well. Thanks for the feedback @tskarhed.
