### ISSUE TITLE
[Bug] Grafana 4.0.2 ldap login fails

### ISSUE THREAD

**Issue by usdin** [grafana/grafana#6892]
Grafana v4.0.2
Os: Ubuntu 16.04 and centos 6.8

We've updated grafana from 3.1.0 to 4.0.2, earlier ldap was working fine, it is failing with version 4.0.2. Our bind_password have special character, which worked fine with v3.1.0. 

We get following with trace logging.

`t=2016-12-09T17:00:49+0530 lvl=info msg="Ldap User Info: [(#$login.ldapUserInfo)(0xc42067d2d0)({\n DN: (string) (len=120) \"CN=#$#$,OU=users,OU=Technology,OU=#$#$#$,OU=India,OU=Users,OU=UserId&Rooms,DC=#$#$#$#$,DC=local\",\n FirstName: (string) (len=11) \"#$#$#$\",\n LastName: (string) (len=6) \"#$#$\",\n Username: (string) (len=18) \"#$#$\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=6 cap=8) {\n  (string) (len=109) \"CN=#$#$#$,OU=Technology,OU=#$#$#$,OU=India,OU=Users,OU=UserId&Rooms,DC=#$#$#$,DC=local\",\n .....\"\n }\n})\n]" 
t=2016-12-09T17:00:49+0530 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2016-12-09T17:00:49+0530 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=127.0.0.1 time_ms=11ns size=42`

**Comment by kidmock** [comment]
I am having the same problem it finds the user but denies login. I've been racking my head for hours, glad it's not not just me.

```
t=2016-12-10T20:03:45+0000 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc4201421c0)({
 DN: (string) (len=46) \"uid=*******,ou=*****,ou=People,dc=mcorp,dc=net\",
 FirstName: (string) (len=7) \"*******\",
 LastName: (string) (len=9) \"*********\",
 Username: (string) (len=7) \"*******\",
 Email: (string) (len=17) \"*******@mcorp.com\",
 MemberOf: ([]string) (len=7 cap=8) {
  (string) (len=48) \"cn=*****,ou=**********,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=46) \"cn=*********,ou=****,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=43) \"cn=******,ou=****,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=46) \"cn=*********,ou=****,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=43) \"cn=******,ou=****,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=42) \"cn=*****,ou=****,ou=Groups,dc=mcorp,dc=net\",
  (string) (len=42) \"cn=*****,ou=****,ou=Groups,dc=mcorp,dc=net\"
 }
})
]"
t=2016-12-10T20:07:39+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"

```

**Comment by stbondarenko** [comment]
I have the same problem with grafana 4.0.2-1481203731:
```
t=2016-12-15T09:27:18+0300 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc4201278f0)({\n 
DN: (string) (len=61) \"\",\n FirstName: (string) (len=18) \"\",\n 
LastName: (string) (len=20) \"\",\n Username: (string) (len=20) \"\",\n 
Email: (string) (len=33) \"\",\n MemberOf: ([]string) (len=10 cap=16) {\n  
(string) (len=50) \"\",\n  (string) (len=45) \"\",\n  
(string) (len=49) \"\",\n  (string) (len=59) \"\",\n  
(string) (len=53) \"\",\n  (string) (len=54) \"\",\n  
(string) (len=50) \"\",\n  (string) (len=49) \"\",\n  
(string) (len=48) \"\",\n  (string) (len=56) \"\"\n }\n})\n]"
t=2016-12-15T09:27:18+0300 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
```

**Comment by rbo** [comment]
I have an similar error in grafana 4.0.1 (docker container)
```
INFO[12-15|09:49:36] Ldap User Info: [(*login.ldapUserInfo)(0xc420113570)({
 DN: (string) (len=48) "CN=Robert Bohne,xxxxxxxxxxxx",
 FirstName: (string) (len=6) "Robert",
 LastName: (string) (len=5) "Bohne",
 Username: (string) (len=3) "xxxx",
 Email: (string) (len=22) "Robert.Bohne@consol.de",
 MemberOf: ([]string) (len=1 cap=1) {
xxxxxxxxxxx
 }
})
]
EROR[12-15|09:49:36] Invalid username or password             logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
```

**Comment by maxifrdz** [comment]
I have the same error in Grafana 4.0.2 in Debian Jessie

```
t=2016-12-21T16:51:24-0300 lvl=info msg="Ldap User Info: [(*login.ldapUserInfo)(0xc420786150)({
 DN: (string) (len=137) \"CN=***,OU=***,OU=***,OU=***,OU=***,OU=***,OU=***,DC=***,DC=com,DC=ar\",
 FirstName: (string) (len=21) \"***\",
 LastName: (string) \"\",
 Username: (string) (len=21) \"***\",
 Email: (string) (len=23) \"***@***.com.ar\",
 MemberOf: ([]string) (len=22 cap=32) {
 *********
 }
 })
 ]"
t=2016-12-21T16:51:24-0300 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
```

**Comment by kidmock** [comment]
Looks like this may be a just a bug in logging.

I upgrade to 4.1.0-beta and error was clear "ldap allow signup = false"

So I set the ldap block to 

```
[auth.ldap]
enabled = true
allow_sign_up = true
config_file = /etc/grafana/ldap.toml
```

I then downgraded to 4.0.2 LDAP Auth is working. Just needed to set "allow_sign_up = true"

At least that's what worked for me...

**Comment by rbo** [comment]
Thanks @kidmock this has solved my problem!

**Comment by prawinlives** [comment]
Hi All, 

i can get the ldap auth work. 

enabled as below 

[auth.ldap]
enabled = true
allow_sign_up = true
config_file = /etc/grafana/ldap.toml 


but still no luck. 

Grafna log are set to trace , this is what i get in grafana log 

#####

t=2017-01-11T11:54:28-0600 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2017-01-11T11:54:28-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=<ldap host ip> time_ms=4ns size=42
t=2017-01-11T11:54:28-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=<ldap host ip  time_ms=0s size=26

##### 

Service account used for ldap auth is correct. 

Not sure why it tries the reference as uid=0 root .

All our linux server are PAM authenticated. 

>> I ahve also added AD user to the sudoers list too. 

Could you help in increasing the logging level and logs to be looking for ldap auth mechanism ? 

regards
Praveen

**Comment by ybizeul** [comment]
I just noticed DNs are case sensitive for some reason. I think it's a grafana bug as I'm not aware of LDAP being case sensitive by nature, would it be possible that's what people are experiencing here?

**Comment by 3cham** [comment]
@prawinlives make sure that your bind_dn and bind_password is correct. 

@ybizeul I experienced the same problem as @kidmock changing *allow_sign_up* to *true* solved this problem. If I understand correctly, this variable enables creating new user if it is found in AD but not exists in grafana DB yet. From my perspective, this variable should not exist because:
- Its name is a bit misleading, user might think that it allows to create new AD user, most of us will set to false
- Intuitively, new user should be automatically created when they use their AD account

**Comment by jiangshengwu** [comment]
agree to @3cham 
I encountered the same problem.
If my memory didn't cheat me, it would work fine in version 3.x even if I set `allow_sign_up` to `false`, because I've never changed the config.

**Comment by torkelo** [comment]
closing this, the allow_sign_up option is a bit unintuitive I agree but documented very well now and no new reports on this in 2 years, https://grafana.com/docs/auth/ldap/#enable-ldap
