### ISSUE TITLE
[Feature Request]: Shared Crosshair without shared tooltip

### ISSUE THREAD

**Issue by trevorndodds** [grafana/grafana#6894]
4.1 latest build. 

I have many graph panels within one dashboard and having the shared tooltip seems to slow down the dashboard and at the same time too many tooltip pop-up windows appear. Can this feature be turned off/on with the shared crosshair?

I prefer how it was previously with the shared crosshair and the tooltip would only activate on the active panel.

Thanks

**Comment by towolf** [comment]
I raised the same point under the PR that merged these features. So :+1: from me.

**Comment by ralphm** [comment]
The PR in question, along with @torkelo's comment on his refactoring that caused this to be single option is here: https://github.com/grafana/grafana/pull/6274#issuecomment-265122084. I too hope we can have both options.

**Comment by torkelo** [comment]
maybe we can have both, or a single option with 3 possible values, like "Graph Tooltip": [Single, Shared Crosshair, Shared Tooltip],  the keyboard shortcut can cycle between the options.

**Comment by sslupsky** [comment]
Hi, and an option to sort the tool tip so the highlighted item is at the top of the tool tip?  When you have a large number of series, it is possible that the series of interest is not displayed in the panel.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/21183928/6cd50ca2-c20a-11e6-8e76-24e6eb76dade.png)

**Comment by trevorndodds** [comment]
Thanks!

**Comment by towolf** [comment]
Yeah, thank you.
