### ISSUE TITLE
Alerting: Datasource error appears periodically

### ISSUE THREAD

**Issue by dorinpirvu** [grafana/grafana#68941]
### 
# What went wrong?

**What happened**:

  - Every day there is a Datasource Error that appears at the same time. 

**What did you expect to happen**:

  - It shouldn't appear

### 
# How do we reproduce it?

Not sure how to reproduce. 
There are two datasources for which alerts are defined. 
One Datasource is Microsoft SQL Server, one is InfluxDB.
From InfluxDB there are around 175 alerts defined, for SQL Server there is only one alert defined.
The alert defined for data coming from SQL Server is attached to an email contact point, the others are attached to a webhook CP.
Everyday (for around 2 weeks now), at the same hour, there are Datasource Error alerts generated, for both datasources (i receive an email for the first one, i catch the webhook for the second one).

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Not in a dashboard panel

### Grafana Platform?

A downloaded binary

### User's OS?

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-70-generic x86_64)

### User's Browser?

Microsoft Edge Version 112.0.1722.39 (Official build) (64-bit)

### Is this a Regression?

None

### Are Datasources involved?

InfluxDB, Microsoft SQL Server

**Comment by tonypowa** [comment]
hi @dorinpirvu 
thank you for creating  this issue

could you share the error and increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. 

More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by dorinpirvu** [comment]
[grafana_log_2023-05-24.txt](https://github.com/grafana/grafana/files/11561443/grafana_log_2023-05-24.txt)
hello, thanks for the response. i attached a sample of the log file with verbosity set to INFO. i will change the verbosity to DEBUG today and upload the new log file tomorrow.
The error appears at local time 21:38. Usually recovers min 5m and max 10m later.

**Comment by dorinpirvu** [comment]
[grafana.log.2023-05-26.txt](https://github.com/grafana/grafana/files/11574942/grafana.log.2023-05-26.txt)
log extract with verbosity set to DEBUG.
Issue appears at 21:40 local time. I receive the resolve message around 21:46

**Comment by tonypowa** [comment]
thank you for the logs @dorinpirvu 

is this the error that you are referring to?

```
logger=sqlstore.transactions rule_uid=QsPdt3x4k org_id=1 t=2023-05-25T21:40:13.325643176+03:00 level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1 code="database is locked"
```

**Comment by dorinpirvu** [comment]
I can not pinpoint the exact moment, unfortunately
I can see several messages "Failed to build rule evaluator", "Database locked, sleeping then retrying" and "Failed to save alert states". They appear also before the line you mention, but indeed they appear more often after that line.
I would understand the line as a message from the SQL plugin, but I also receive DatasourceError also from the InfluxDB plugin, so I'm at a loss. There's only one alert defined for an SQL datasource, more than 150 for InfluxDB. This (the message of Datasource Error) appears only once per day, same time. 
InfluxDB and SQL machines seem to be up all the time, InfluxDB is on Ubuntu, SQL is on Win10Pro.

**Comment by tonypowa** [comment]
`rule_uid=6aFV1ZaVz`

could you check what is the datasource associated to this alert?

**Comment by dorinpirvu** [comment]
sorry, i don't know how to do that :(
if i write in the browser:
https://grafana_url/api/v1/provisioning/alert-rules/6aFV1ZaVz
it leads to a page that seems to have a json answer.
Seems to be one of the alerts with InfluxDB datasource:
`{"id":114,"uid":"6aFV1ZaVz","orgID":1,"folderUID":"NKuuE3J7k","ruleGroup":"ConsumAer","title":"232xv6692","condition":"E","data":[{"refId":"A","queryType":"","relativeTimeRange":{"from":300,"to":0},"datasourceUid":"kWf4Fu6nz","model":{"hide":false,"intervalMs":1000,"maxDataPoints":43200,"query":"SELECT PTF23_AirFlow FROM \"AerPtf23\" WHERE $timeFilter and PTF23_232xv6692_S=true\n","rawQuery":true,"refId":"A","resultFormat":"time_series"}},{"refId":"B","queryType":"","relativeTimeRange":{"from":300,"to":0},"datasourceUid":"kWf4Fu6nz","model":{"datasource":{"type":"influxdb","uid":"kWf4Fu6nz"},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"query":"SELECT Air_Limit FROM \"AerPtf23\" WHERE $timeFilter","rawQuery":true,"refId":"B","resultFormat":"time_series"}},{"refId":"C","queryType":"","relativeTimeRange":{"from":300,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"A","intervalMs":1000,"maxDataPoints":43200,"reducer":"min","refId":"C","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"D","queryType":"","relativeTimeRange":{"from":300,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"B","intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"D","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"E","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"$C \u003e= $D","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"E","type":"math"}}],"updated":"2023-05-29T08:42:54+03:00","noDataState":"OK","execErrState":"Error","for":"5m","annotations":{"AlertLimit":"{{ $values.D.Value }}l/h","AlertValues":"{{ $values.C.Value }}l/h","__dashboardUid__":"NoiBK9N4z","__panelId__":"1","description":"Canal CIP T266","summary":"Canal CIP T266"},"labels":{"Debitmetru":"3","Platforma":"2","User":"Mecanic"},"isPaused":false}`

**Comment by tonypowa** [comment]
that's right thank you !

I will tag the alerting team for further review

**Comment by grobinson-grafana** [comment]
Hi! :wave: This error should be the cause of the `DatasourceError` alert:

```
logger=ngalert.scheduler rule_uid=CyHD_rL4k org_id=1 version=7 fingerprint=d125e36e14dd91c9 attempt=0 now=2023-05-25T21:40:00+03:00 t=2023-05-25T21:40:10.611441835+03:00 level=error msg="Failed to evaluate rule" error="failed to convert datasource instance settings: [sqlstore.max-retries-reached] retry 1: database is locked" duration=6.754138466s
```

It looks like the database is locked when Grafana attempts to read the datasource configuration from the database. I see you are using Microsoft SQL server as a datasource, but what database are you using for Grafana? Is it also Microsoft SQL server?

**Comment by dorinpirvu** [comment]
Grafana database is sqlite3, if that is what you are asking

**Comment by grobinson-grafana** [comment]
Is your sqlite3 database in WAL or journal mode? You might want to set `wal` to `true`:

```
[database]
type = sqlite3
wal = true
```

I'd recommend also taking a backup of the sqlite3 database first just in case.

**Comment by dorinpirvu** [comment]
in the ini file i can see:
```
;type = sqlite3
wal = true
```
I am understanding that grafana is using the default database type (sqlite3) and wal is enabled - i've had the issue of database locked before, the behavior was happening when adding multiple alerts very fast in the UI, I received the suggestion to enable `wal`.

**Comment by dorinpirvu** [comment]
ok, i will give it a try and do the modifications you suggest. 
Unfortunately at this moment switching to either MySQL or PostgreSQL is not an option. 
On the other hand, at least we know what to take into consideration.
I'll post the outcome tomorrow, since the issue seems to be happening only during evening.

**Comment by dorinpirvu** [comment]
Hello everyone!
I did not receive datasource errors yesterday and I just finished skimming through the logs.
I searched for `DatasourceError` and `Database locked` terms in the logs (did not check each individual line) and there were **none**.
At least not in a roughly 5 hour interval surrounding the time I was used to receiving the errors.
So this is good news and thank you @grobinson-grafana for the suggestions.
It is clear for us that in the long run we need to switch to another database type for Grafana.

Until then, are there any maximum values for `query_retires` and `transaction_retries` that we could take into consideration (values after which it has no added impact to further increase them)?
Thanks again!

**Comment by grobinson-grafana** [comment]
> Until then, are there any maximum values for query_retires and transaction_retries that we could take into consideration (values after which it has no added impact to further increase them)?

There are a lot of variables involved here, and I'd recommend adjusting these according to what you see on your own Grafana installation. In general, the tradeoff being made here is higher query latency for higher certainty that queries will succeed, but since you only have a couple 100 of alerts in this specific case I don't think this is an issue. I would keep `query_retries=3` and `transaction_retries=5` unless you start to see other issues in Grafana. 

> Another question would be how many alerts could I define until i get the error again?

It's hard to give an exact number because it's not the number of alerts that affects sqlite, it's how long it takes the average transaction to commit or abort. The cause of these errors is slow transactions blocking all other transactions, and some of those slow transactions might not even be Alerting related.

> What could I do to avoid getting the error? Maybe assign the alerts to different timings? Or?

The Grafana alerting scheduler will evaluate alert rules at the 0th second, so this might not help much. The main factor in as mentioned above: how long it takes the average transaction to commit or abort.

We will also update our docs with better information and guidance on using sqlite3 with Grafana Alerting.

**Comment by dorinpirvu** [comment]
Thank you very much for all the info and help provided!
It's already been several days without the problem, so we can consider this issue solved.
