### ISSUE TITLE
Icons in Figma - Update icons to match Storybook

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#68957]
**Goal**

Add to our [Figma library](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=10389-13951) the next **list of Icons** to match Storybook:

- [ ] at
- [ ] arrow-to-right
- [ ] calendar-slash
- [ ] capture
- [ ] check-square
- [ ] circle-mono
- [ ] corner-down-right-alt
- [ ] discord
- [ ] expand-arrows
- [ ] font
- [ ] google-hangouts-alt
- [ ] hipchat
- [ ] layers-alt
- [ ] line
- [ ] list-ol
- [ ] pagerduty
- [ ] gf-movepane-left
- [ ] gf-movepane-right

**Comment by Aires-Grafana** [comment]
@staton-hyse11 this sounds like an easy issue to move forward quickly and close.
I believe I have most of these icons already in the new iconography. I can add them easily to the current library of Saga.
Thoughts?
