### ISSUE TITLE
Variables lose some filter

### ISSUE THREAD

**Issue by yuxuejiao** [grafana/grafana#68954]
### 
# What went wrong?

**What happened**:
We define variable like "regexp_like(SM_C_product_version\,'^${clientVersion:regex}.*') and SM_C_value_event_locusSessionType in (${locusSessionType})
and ${clusters:glob}
and ${pairedDevice:lob}..."
We produce a Shorten link, then visit it and find lose some filter in Query inspector

**What did you expect to happen**:
All filters defined in variable exit in Query inspector in shared shorten link.

### 
# How do we reproduce it?

**Step 1**:

Define variables described in above. 

**Step 2**:

Produce a shorten link.

**Step 3**:

Visit shorten link, then open Query inspector, and confirm whether filters defined in variable lose or not.

### 
# What Grafana version are you using?

v9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by mellieA** [comment]
@yuxuejiao I tried this by adding two template variables as a custom variable: 

<img width="1098" alt="Screenshot 2023-05-25 at 4 38 37 PM" src="https://github.com/grafana/grafana/assets/18175287/91523ee2-ff13-4d12-b5e4-66f3d59570ad">

Saved the dashboard
Clicked Share & copied the link - the link opens with the variables selected the same as they are in the source dashboard
Toggled to the short link and got the same result
Tried in another browser to make sure the context wasn't cached and the correct variables came selected

Can you let me know if any of my steps sound like they're incorrect?
I'm using Grafana 9.5.3

**Comment by yuxuejiao** [comment]
Then you can update the variables, and save the dashboard again. Then you visit the previous shorten link, the variable are not updated.
