### ISSUE TITLE
Loki: Improve logs volume experience

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#68956]
Often logs volume times out for our users. We should look at it and see if there are:

- Fast fixes we could do (e.g. open in split view button)
- Investigate that query splitting helped
- Re-evaluate all design decisions, such as:
  - Always running logs volume query and not using button/action to run it
  - Always starting with open logs volume query/remembering how user left it

**Comment by JeffCT0216** [comment]
Can we please add this back? https://github.com/grafana/grafana/pull/45286
We cannot reliable depend on user to collapse the log volume tab

**Comment by stevendungan** [comment]
@JeffCT0216 can you tell us a bit more about "impacting our loki performance greatly"? What's the specific pain it's causing your users, and what's the pain it is causing you? Would love to make sure we are understanding deeply!

**Comment by shapirus** [comment]
https://github.com/grafana/grafana/pull/45286 has made it impossible to disable the expensive a numerous high-rate `sum by (level)(count_over_time()` requests made to loki whose only purpose is to render the log volume rate histogram.

This is very noticeable for queries that need to download (from e.g. S3 storage) gigabytes of logs for a long time span. Fetching the log lines alone is already an expensive task, and then we add the rate queries to it which aren't always necessary.

Disabling this should be configurable. Ideally per-query, with the option to configure the default state, but per-datasource would also work.

Disabling this by hiding the histogram widget does not work: this widget isn't even shown before the query is made, and there is no way for the user to know that hiding is the way to prevent the rate queries from being made.

**Comment by jtackaberry** [comment]
IMO Grafana desperately needs some sort of configurable adaptive logic with respect to whether the log volume histogram is enabled for a given query.

I would like to be able to configure an upper bound on the query data volume (as reported by the initial stats query that feeds the "This query will process approximately X" text) that adaptively enables/disables the log volume histogram.

If a user runs a log search and the stats query says it's going to process 100G of logs, say, I'm ok with the log volume histogram queries at my scale.  If they're doing a 1 month search that's going to scan 50 TB of logs, I really don't want the queriers burning away for 20 minutes on a zillion metric subqueries that the user certainly isn't going to bother waiting for as they're scrolling through the first page of results.

**Comment by ivanahuckova** [comment]
@jtackaberry In documentation, it mentions how to prevent this
> [!NOTE]
> Note: In Loki, this full range log volume is rendered by a metric query which can be expensive depending on time range queried. This query can be particularly challenging to process for smaller Loki installations. To mitigate this, we recommend using a proxy like [nginx](https://www.nginx.com/) in front of Loki to set a custom timeout (for example, 10 seconds) for these queries. Log volume histogram queries can be identified by looking for queries with the HTTP header X-Query-Tags with value Source=logvolhist; these headers are added by Grafana to all log volume histogram queries.

 More in: https://grafana.com/docs/grafana/latest/explore/logs-integration/#logs-volume

**Comment by jtackaberry** [comment]
> More in: https://grafana.com/docs/grafana/latest/explore/logs-integration/#logs-volume

@ivanahuckova ah, thanks for the tip. I was going to do this based on the query path (where the requestId query parameter includes `logs_volume` as a substring) but the header approach is more robust.

Still, it's a blunt instrument.  I'd much rather the adaptive logic I proposed above (based on data volume from the stats query), because it would provide a better UX (by waiting allowing waiting a bit longer than the timeout threshold if needed) and reduce infrastructure load (by skipping the metric query altogether when it knows it's massive), so I hope that idea can be considered.

Thanks!

**Comment by nhippe-ds** [comment]
> @JeffCT0216 can you tell us a bit more about "impacting our loki performance greatly"? What's the specific pain it's causing your users, and what's the pain it is causing you? Would love to make sure we are understanding deeply!

I came across this searching into why my Loki read instances (simple scalable deployment / single tenant) were getting hammered after an initial large query. For example, if I were to run a simple query like:
{environment="produs", source="k8s" over let's say, 12h (this is a very large amount of logs) my first 1000 lines get returned within seconds. I get the "Log volume is loading..." (Grafana 9.4.3). After awhile the Log Volume loads but depending on how scaled my read path is this can range from seconds to many minutes, or even timing out (5m timeout). Depending on caching and other things a bunch of concurrent initial large queries could bog down the Loki cluster. 

With all of that being said, maybe that's what @JeffCT0216 may be referring to. I'm seeing something similar during my load testing of my read path. I'm not sure how the Logs Volume queries work and if they use any concurrency/parallelism settings from the core Loki install but I could see how a few users running heavy queries could effectively bog down a Loki cluster that isn't tuned properly on the read path (caching, concurrency, parallelism, etc etc).

**Comment by ivanahuckova** [comment]
> Perhaps having a way to toggle or allow users a way to opt in/out before query execution could help?

@nhippe-ds You can toggle-off logs volume panel that prevents from running logs volume queries.

**Comment by nhippe-ds** [comment]
> > Perhaps having a way to toggle or allow users a way to opt in/out before query execution could help?
> 
> @nhippe-ds You can toggle-off logs volume panel that prevents from running logs volume queries.

@ivanahuckova Can you share how to toggle-off logs volume panel? I know the nginx workaround is documented but if I'm reading this thread correctly the `fullRangeLogsVolume` toggle was removed?

**Comment by jtackaberry** [comment]
> Can you share how to toggle-off logs volume panel? 

@nhippe-ds  in terms of allowing individual users to opt in or out of the logs volume panel, they can just collapse/expand it by clicking on the arrow beside "Logs volume"

![image](https://github.com/grafana/grafana/assets/1280551/14204bc9-8e40-4bbe-9bf3-fa5170ed0ecf)

This capability hasn't been removed, only the ability for the admin to disable it globally.

This issue is meanwhile, hopefully, about balancing user experience with system load in a more intelligent way.

**Comment by nhippe-ds** [comment]
Thanks @jtackaberry! I didn't realize collapsing that actually canceled in progress volume queries.

**Comment by paulojmdias** [comment]
Is there any plan to improve this experience?
IMO this is an essential feature in which disabling or collapsing the panel is a bad UX, but with a huge data volume, the Loki deployment even with a lot of resources, can't survive these queries.

**Comment by matyax** [comment]
We're actively working on improvements for the logs volume experience. In the data source part, we added support for retrying timed out requests, and with https://github.com/grafana/grafana/issues/95233, currently under the feature flag `lokiShardSplitting`, we're experimenting with executing log volume queries using stream shards if they are available in the Loki instance.

In the mean time, remember that you can collapse the Logs Volume panel as soon as it appears (cancelling any pending query), and we'll remember this state on your next session.

Your feedback and patience is much appreciated! You can expect an overall improved experience in upcoming Loki and Grafana versions.
