### ISSUE TITLE
[Bug] - Panel JSON not displaying in 4.0.1

### ISSUE THREAD

**Issue by markunsworth** [grafana/grafana#6896]
Grafana Version: 4.0.1
OS: Ubuntu 14.04
Datasource: Tested on panels that use Graphite and Elasticsearch as a datasource

I try to open Panel JSON for any panel by:
1. clicking panel name
2. then clicking the hambuger icon 
3. then clicking on "Panel JSON"

I expect to get a panel at the top  showing the Panel's JSON for editing/copying.

Nothing happens, the panel's JSON window didn't display

**Comment by torkelo** [comment]
strange, unable to reproduce that here. What browser are you using? What grafana user role do you have?

**Comment by torkelo** [comment]
Also please open chrome dev tools and console, any js errors?

**Comment by markunsworth** [comment]
It works perfectly now. 

I'll put it down to Chrome having a breakdown at the end of last week
