### ISSUE TITLE
Grafana Alerting - Authorization Header - Scheme" isn't working

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana#68998]
### 
# What went wrong?

**What happened**:
I configured contact point using webhook with below details
Integration : webhook
URL : API Gateway URL
Authorization Header - Scheme : x-api-key
Authorization Header - Credentials : API Key

and tested alert contact point. IT gives me below error 
![image](https://github.com/grafana/grafana/assets/89400147/7968ba77-5cfe-4d90-84c4-f6303794a2ca)

Failed to send test alert.: webhook response status 403 Forbidden

URL is working with x-api-key in header with postman.

**What did you expect to happen**:

 It should call the Api gateway URL without any issues.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and open contact points in alerting

**Step 2**:

I have created api gateway endpoint with api key.

- Create new contact point and add below details

Integration : webhook
URL : API Gateway URL
Authorization Header - Scheme : x-api-key
Authorization Header - Credentials : API Key

**Step 3**:

click on Test

### 
# What Grafana version are you using?

Grafana v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 20.04.5 LTS (Focal Fossa)

### User's Browser?

Firefox

### Is this a Regression?

None

### Anything else to add?

grafana image - grafana/grafana:9.5.1-ubuntu

**Comment by mellieA** [comment]
@Dhyanesh97 Can you confirm that you are using Grafana 9.4.7 or later - it looks like it should have been fixed here: https://github.com/grafana/alerting/pull/59

It could be a regression, but I just want to confirm.  Other users have reported in https://github.com/grafana/grafana/issues/65154#issuecomment-1527052406 that it works on 9.5.1.

**Comment by Dhyanesh97** [comment]
![image](https://github.com/grafana/grafana/assets/89400147/1f5cb670-3d7c-403b-a351-a812100264de)

yes I am using Grafana v9.5.1

**Comment by Dhyanesh97** [comment]
Hi @mellieA, Could we able to fix this issue in upcoming release ?
Without Authorization it is working as expected. But with custom Authorization header it is giving an issue.

**Comment by gillesdemey** [comment]
Hi! Tested this on Grafana 10 and seems to work as expected. Keep in mind that the scheme is going to be part of the `authorization` header and for the built-in webhook receiver we do not support custom headers.

Here's a screenshot of my configuration
<img width="598" alt="image" src="https://github.com/grafana/grafana/assets/868844/5bf4feb6-1647-431c-a19f-6a1f675bc4d0">

And here is a link to the HTTP request that was received by the webhook endpoint (notice the header)

`authorization: x-api-key foobar`

https://webhook.site/#!/9504cc86-78da-4e32-bd52-84965efc79fd/8c5270c1-bb3b-45a8-b0b0-fa222339cc3b/1

**Comment by Dhyanesh97** [comment]
Tried with Grafana v10.1.0-120722pre docker image as well. Receive same error.
Without authorization it is working as expected but with custom authorization it is giving an issue. 
With postman custom authorization is working as expected but not with grafana.

Note: I am using API gateway endpoint.

<img width="853" alt="api_gateway_error" src="https://github.com/grafana/grafana/assets/89400147/ff1f1fda-4e28-46b5-b007-dc1b0d384bb6">

**Comment by gillesdemey** [comment]
Can you dump a HAR or cURL command that your Postman client generates? I have a feeling there is a misunderstanding here for how the `authorization` header gets constructed.

**Comment by Dhyanesh97** [comment]
[api_gateway.postman.co.har.zip](https://github.com/grafana/grafana/files/11724093/api_gateway.postman.co.har.zip)

**Comment by gillesdemey** [comment]
Ok so there's definitely some confusion here, the `Authorization header – Scheme` field does _not_ add a new HTTP header, instead it will be used in the value for the standard `authorization` header (see my previous screenshot for what the value for the `authorization` header looks like.

Custom headers, like `x-api-key`, are currently not supported, see https://github.com/prometheus/alertmanager/issues/739

**Comment by Bieber-888** [comment]
Hi @gillesdemey , I faced similar problem . But for me , I configured HTTP Basic Authentication - Username, HTTP Basic Authentication - Password.  When test I got 401 error.  I am using grafana 10.0.3.  do you have any idea on this?
