### ISSUE TITLE
Grafana Download is Blocked as virus...

### ISSUE THREAD

**Issue by dp106** [grafana/grafana#68993]
### 
# What went wrong?

The latest version of Grafana 9.5.2 was blocked by our AV (McAfee/Trellis) as a suspected virus. 
![image](https://github.com/grafana/grafana/assets/29710771/f39d54ed-5a59-469b-8eb1-b2f9f3109cf7)

  - 

I was hoping to get the latest update :)

  - 

### 
# How do we reproduce it?

Attempt to download the Grafana update:

https://dl.grafana.com/enterprise/release/grafana-enterprise-9.5.2.windows-amd64.zip

### 
# What Grafana version are you using?

We are currently on 9.4.7

### 
### Grafana Platform?

None

### User's OS?

Windows 10

### User's Browser?

Edge

### Is this a Regression?

None

**Comment by mellieA** [comment]
@dp106 is there something you think we need to change to address this?

**Comment by dp106** [comment]
> @dp106 is there something you think we need to change to address this?

@mellieA I was hoping you could tell me 😀 I don't understand exactly what is going on here but for some reason McAfee identifies grafana-cli.exe as a potential virus. Is there something you can change your end, or register it with McAfee as a safe file?

**Comment by dp106** [comment]
> Just to add to this a few months later, both grafana CLI and server are being flagged by several AV clients
> 
> https://www.virustotal.com/gui/file/6fc03714c3525c466e617c5c770fd977236fa6f22b39db6bd50d713782723358/detection https://www.virustotal.com/gui/file/c780a11e6fb763d1ecce634778e280baa72915fc1d8816f074f1c66332ecdab0/detection

At least I'm not the only one then. Struggling to download grafana 10.0.2 at the moment, trying to find someone in my office that will help unblock it!

**Comment by mellieA** [comment]
@dp106 @pvares I'm not sure if there is anything to do from our end, but I'll ask our release engineering squad to take a look and comment.
