### ISSUE TITLE
With anonymous mode enabled, many INSERT INTO cache_data already exists errors

### ISSUE THREAD

**Issue by amarant** [grafana/grafana#69008]
### 
# What went wrong?

**What happened**:
I enabled anonymous mode I get many errors in postgres (the database of grafana) in the cache_data table, probably at each user connection :

````
2023-05-24 16:44:19.894 UTC [37447] ERROR:  duplicate key value violates unique constraint "cache_data_pkey"


2023-05-24 16:44:19.894 UTC [37447] DETAIL:  Key (cache_key)=(anon-session:<redacted>) already exists.


2023-05-24 16:44:19.894 UTC [37447] STATEMENT:  INSERT INTO cache_data (cache_key,data,created_at,expires) VALUES($1,$2,$3,$4)
````

**What did you expect to happen**:

  No sql error.

### 
# How do we reproduce it?

**Step 1**:

- Setup grafana with a postgres database

**Step 2**:

- Enable anonymous access

**Step 3**:

- in postgres an insert into error at each user connection

### 
# What Grafana version are you using?

v9.5.1

### 
### Grafana Platform?

Docker

### User's OS?

Ubuntu 22.04

### Is this a Regression?

None

**Comment by amarant** [comment]
I get this in the database logs and I can't see relevant errors from the db now as it is cluttered with this error every minutes, instead of doing exception oriented programming why not just do an upsert at the [insert into](https://github.com/grafana/grafana/blob/6cb1a5e36877b1e518093c9611e26dc5dc493699/pkg/infra/remotecache/database_storage.go#LL94C11-L94C85) ?

````sql
INSERT INTO cache_data (cache_key,data,created_at,expires) 
VALUES(?,?,?,?) 
ON CONFLICT (cache_key)
DO UPDATE SET
    data = EXCLUDED.data,
    created_at= EXCLUDED.created_at,
    expires= EXCLUDED.expires;
````

**Comment by suntala** [comment]
Didn't realise this ticket was on another board as well. Sorry about that. Reopening it.
