### ISSUE TITLE
[Bug] Table Display Pagination (Page size) input is too wide in Firefox

### ISSUE THREAD

**Issue by connection-reset** [grafana/grafana#6900]
Table -> Options -> Table Display -> Pagination (Page size) input is too wide in Firefox, looks fine in Chromium. 
Grafana built from HEAD (https://github.com/grafana/grafana/commit/02392e5189df6e26f18d9d7ca69f3468b60d49ad)

How it should (and does in Chromium 55.0.2883.75) look like:
![2016-12-09_17-44-28](https://cloud.githubusercontent.com/assets/6831775/21056734/2d873cd6-be37-11e6-9c55-95e11a7a8c2a.png)
How it looks in Firefox 50.0.2:
![2016-12-09_17-41-30](https://cloud.githubusercontent.com/assets/6831775/21056718/20f04e4a-be37-11e6-9c67-bcea86a144e5.png)
![2016-12-09_17-41-45](https://cloud.githubusercontent.com/assets/6831775/21056716/1d59e7e6-be37-11e6-8e2d-48f10a4e395f.png)

**Comment by torkelo** [comment]
thanks for reporting this, will fix!
