### ISSUE TITLE
[Bug] Yum package not suitable for unattended updates

### ISSUE THREAD

**Issue by yves-vogl** [grafana/grafana#6901]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?

```
Name        : grafana
Arch        : x86_64
Version     : 4.0.2
Release     : 1481203731
Size        : 118 M
Repo        : installed
From repo   : grafana_stable
Summary     : Grafana
URL         : http://grafana.org
License     : "Apache 2.0"
Description : Grafana
```

- What datasource are you using?

```N/A```

- What OS are you running grafana on?

```CentOS Linux release 7.2.1511 (Core) ```

- What did you do?

```Installed yum-cron for unattended updates and let it install an update.```

- What was the expected result?

```Being able to use Grafana at the latest version.```

- What happened instead?

```A broken layout was shown. Also I could not relaunch the service (Warning: grafana-server.service changed on disk. Run 'systemctl daemon-reload' to reload units.)```

See screenshot.

![screen shot 2016-12-09 at 19 27 39](https://cloud.githubusercontent.com/assets/21128/21060223/892bebf4-be46-11e6-95c6-fcb25fbb478c.png)

**Comment by torkelo** [comment]
> Restarting services when packages are installed is not standard behavior for RPMs, or redhat/fedora based distros. Restarting the service would cause an interruption. And what if the config file were no longer compatible with the new version? The restart would fail and your service would be down.

https://github.com/grafana/grafana/issues/5742

If you want to enable auto restart you can configure it yourself.
https://github.com/grafana/grafana/blob/master/packaging/deb/default/grafana-server#L17

But the current behavior is not optimal either (leaving Grafana in a broken state). But at least in that broken state it is possible to rollback upgrade. If grafana restarts automatically then  the Grafana database schema will upgraded during startup and unless a database backup has been done a downgrade might not be possible/easy.

But I am open for a PR that changes this behavior.
