### ISSUE TITLE
[Feature Request] Ability to specify Slack url in config file

### ISSUE THREAD

**Issue by evanccnyc** [grafana/grafana#6902]
Currently, if you add a slack "Alert notification" you have to enter the webhook url for each one. It would be nice if we could specify that in the config file (like the smtp server). That way end users wouldnt have to know it to create an alert notification they want to hit.

**Comment by utkarshcmu** [comment]
I agree that specifying the webhook URL only once would be better but I am guessing that we are waiting for Golang 1.8 to have SLACK as a backend plugin...

**Comment by utkarshcmu** [comment]
Or how about having slack.ini under config directory for now, and which can later be plugged into a separate backend plugin?

**Comment by marcantoine-bibeau** [comment]
Any development on that front?

**Comment by 0xbron** [comment]
Any progress on this?

**Comment by bergquist** [comment]
This will be solved by alert notification provisioning. https://github.com/grafana/grafana/issues/10487
So I'm closing this.
