### ISSUE TITLE
GLIBC version requirement changed after Grafana version 9.1.6 on Amazon Linux 2 OS running on Graviton Instance Types

### ISSUE THREAD

**Issue by mourya92** [grafana/grafana#69030]
### 
# What went wrong?

**What happened:** 

We were running Grafana on AWS EC2 instance using Amazon Linux 2, the GLIBC version is 2.26 (https://aws.amazon.com/amazon-linux-2/faqs/)

Q. What are the core components of Amazon Linux 2?

The core components of Amazon Linux 2 are:

A Linux kernel tuned for performance on Amazon EC2.
A set of core packages including systemd, GCC 7.3, Glibc 2.26, Binutils 2.29.1 that receive Long Term Support (LTS) from AWS.
An extras channel for rapidly evolving technologies that are likely to be updated frequently and outside the Long Term Support (LTS) model.
Grafana was running fine until we upgraded Grafana passing version 9.1.6

We got this error :

grafana-server: /usr/sbin/grafana-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/grafana-server)

**What you expected to happen:** 

Grafana should be running fine on Amazon Linux 2.

**Anything else we need to know?:** 

We are using m6g.4xlarge instance family, which is ARM based, but most probably this is irrelevant.

**Environment:**

Grafana version: 9.2.6
Data source type & version:
OS Grafana is installed on: Amazon Linux 2
User OS & Browser:
Grafana plugins:
Others:

### 
# How do we reproduce it? 

1. Install any ARM64 version of Grafana beyond 9.1.6
2. Try to run it on a Graviton instance(ARM based) running Amazon Linux 2.
Command : `./bin/grafana-server`

### 
# What Grafana version are you using?

v9.2.6

### 
### Grafana Platform?

v9.2.6

### User's OS?

Amazon Linux 2 on m6g.4xlarge instance type

### Is this a Regression?

Yes

### Anything else to add?

There is a duplicate issue : https://github.com/grafana/grafana/issues/57157 

But it was never resolved or had any useful info from Grafana team. So, I am re-opening the issue with details about my environment.

**Comment by mellieA** [comment]
@mourya92 I've reopened the duplicate issue and will close this one. Thanks for letting us know!
