### ISSUE TITLE
Traces Dashboard element: cannot use any form of query

### ISSUE THREAD

**Issue by Joibel** [grafana/grafana#69050]
### 
# What went wrong?

**What happened**:

I created a traces dashboard visualisation. I selected Tempo as the source and in the TraceQL box put {.scheduleid=169698834} which does match a trace in the time window selected.

What was shown was that it had found the trace as the trace id is in the trace, but the spans are all missing.
![image](https://github.com/grafana/grafana/assets/1827156/3d57ac99-bac8-494c-abd4-f5d4daf71707)

**What did you expect to happen**:

I'd expect a full trace to be shown as the TraceQL query matches exactly one trace id.
If I just put the trace id directly into the TraceQL box, this shows as hoped.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana with a connected Tempo with traces in it.

**Step 2**:

- Find a trace in explore and note the trace id, and an attribute. Write a query to find the trace by attribute `{.attributename=.attributevalue} and check it works.

**Step 3**:

- Create a new dashboard and add a visualisation. Ensure the timespan covers your trace. Change the type to traces and put the trace id in the TraceQL box. Enjoy the visualised trace.

**Step 4**:

Add another visualisation to your dashboard of type traces. Put the search you determined in Step 2 as your TraceQL query. Be disappointed that the trace doesn't match the one you saw in Step 3.

**Step 5**:

Wonder how you're supposed to use the traces dashboard element.

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Grafana Platform?

Kubernetes

### User's OS?

Fedora 37

### User's Browser?

Firefox 112.0.1

### Is this a Regression?

None

### Are Datasources involved?

Tempo 2.1.1

**Comment by Joibel** [comment]
An alternative valid dashboard would perhaps have been the traces table view. This is visible whilst editing the visualisation, but it doesn't stick, and so you always end up with the view shown above.

**Comment by joey-grafana** [comment]
This is actually the expected behaviour, although not very user friendly.

> A TraceID query results in the TraceView being shown, while the TraceQL query results in a table with a list of matches traces/spans being shown.

Even if there is only one TraceQL result, it still returns data in a different format than querying with the TraceID. I've created an issue to explore how we can improve the UX here and added more info in [the issue.](https://github.com/grafana/grafana/issues/69245)
