### ISSUE TITLE
InfluxDB Datasource: Bad Request 400 shown in developer tools on refresh

### ISSUE THREAD

**Issue by Daddelion** [grafana/grafana#69069]
### 
# What went wrong?

**What happened**:

 Getting  BAD REQUEST 400 on every Refresh, but data is still loaded

**What did you expect to happen**:

Not getting the Fetch Request Error

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add Influxdb as a Datasource

**Step 2**:

- Create Timeseries with created Datasource

**Step 3**:

- Check Console of Browser

### 
# What Grafana version are you using?

Grafana v9.5.1 (bc353e4b2d)

### 
### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 22.04.2 LTS

### User's Browser?

Version 113.0.5672.126 (Official Build) unknown (64-bit)

### Is this a Regression?

None

### Are Datasources involved?

Influx 2.4.0

**Comment by mellieA** [comment]
@Daddelion thanks for reporting this! I reproduced on play.grafana.org

<img width="1787" alt="Screenshot 2023-05-26 at 10 21 02 AM" src="https://github.com/grafana/grafana/assets/18175287/852b749b-bd80-450c-b367-0e4c68108165">

**Comment by gtk-grafana** [comment]
This has been fixed in a more recent version. @itsmylife has more details...

**Comment by itsmylife** [comment]
This is fixed here https://github.com/grafana/grafana/pull/67722
The most recent version has the fix.
