### ISSUE TITLE
Webapp crash when clicking on a dropdown

### ISSUE THREAD

**Issue by Bixilon** [grafana/grafana#69068]
### 
# What went wrong?

I tried to add a data source (see https://github.com/Checkmk/grafana-checkmk-datasource/issues/194) for more details.

Everytime I click on a dropdown, it crashes with
```
act-dom.production.min.js:216 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Wl (react-dom.production.min.js:237:48)
    at ec (react-dom.production.min.js:170:408)
    at index-a86253bb.esm.js:677:7
    at je (floating-ui.dom.browser.min.mjs:1:6624)
    at index-a86253bb.esm.js:692:28
    at index-a86253bb.esm.js:702:5
    at Rd (react-dom.production.min.js:259:307)
    at g.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at nu (react-dom.production.min.js:122:325)
    at lc (react-dom.production.min.js:252:279)
```

### 
# How do we reproduce it?

I am going to `Connections` -> search of `influxdb` -> blue button `Create new datasource` -> click on any dropdown

### 
# What Grafana version are you using?

Version 9.5.2 (commit: cfcea75916, branch: HEAD) 

### 
### Is the bug inside a Dashboard Panel?

No

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Linux alcala 5.15.92-bcm2711 #23.02.2 SMP PREEMPT Fri Feb 17 22:42:10 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux, Armbian 22.04

### User's Browser?

113.0.5672.126 (Official Build, ungoogled-chromium) (64-Bit) 

### Is this a Regression?

None (maybe, installed a fresh instance)

### Are Datasources involved?

Checkmk data source, but that is where I initially found the bug

### Anything else to add?

It is probably arm64 related? No clue.

Thanks

**Comment by mellieA** [comment]
@Bixilon opening this issue in the developer's repo is the right thing to do since they are the maintainer of the plugin. I'll close this request from the grafana side.

**Comment by Bixilon** [comment]
@mellieA I think you got me wrong. I already did, and afer investigation, it is not a problem on their side. It happens with ALL gui dropdowns. You can try adding an influx db data source for example.


It is a grafana on chromium issue.

**Comment by Bixilon** [comment]
@mellieA Can you please reopen this issue?
