### ISSUE TITLE
[Change Req]: Org role overriden by default role when user logins via LDAP

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6907]
- What Grafana version are you using? Master
- What did you do? As an org admin, changed a user's role to be Admin instead of Editor (being the default role in LDAP config). It updated DB as expected.
- What was the expected result? Once someone is made Admin, should remain Admin until he is changed to another role.
- What happened instead? But when that user logs in, his role becomes as Editor (default from LDAP config) again instead of remaining an Admin.

**Comment by utkarshcmu** [comment]
How about this:
When we syncOrgUser in https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go#L202, we only update when group.OrgRole is above then org.Role?

This is a better solution as compared to just replacing the default ROLE for a user.

Any feedback?

**Comment by torkelo** [comment]
sounds like a good option. But think the whole LDAP  -> Org role sync needs to overhauled or redesigned.

**Comment by RichiH** [comment]
How is this not a bug?

FTR, we are being bitten by this as well, but thought it was our fault and didn't upstream this because of that assumption.

**Comment by torkelo** [comment]
@RichiH what do you mean? This is described in the LDAP docs, http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync

>  you can map an LDAP group to a Grafana organization and role. These will be synced every time the user logs in, with LDAP being the authoritative source. So, if you change a user’s role in the Grafana Org. Users page, this change will be reset the next time the user logs in. If you change the LDAP groups of a user, the change will take effect the next time the user logs in.

I agree that it is not a very good behavior and the LDAP membership -> Grafana org role sync can be much improved. Infact I think it needs to be redesigned or overhauled quite a bit. The whole LDAP integration could be much improved I think.

**Comment by RichiH** [comment]
@torkelo Sorry, I missed that bit in the docs.

As to the desired behaviour, the quick fix would be to optionally allow initial sync the first time a user tries to access Grafana and then not change anything, any more.

Without having looked at the code, this should be do-able with minimal effort, no?

**Comment by torkelo** [comment]
yes, it should I think.

**Comment by bkez322** [comment]
I would very much like to see this bug finally addressed as well. It's causing a big problem for my deployment.

**Comment by bastischubert** [comment]
+1 this is a really annoying as @RichiH pointed out - maybe #7565 is worth looking at and giving a try

**Comment by chrim5** [comment]
+1

**Comment by gavol** [comment]
+1

**Comment by martinm82** [comment]
Just got hit by the problem as well. Are there any plans to address this issue?

**Comment by torkelo** [comment]
you remove the group mappings from the ldap.toml file the user will get the default role for the default org (1) and no org role sync will happen

**Comment by bastischubert** [comment]
@torkelo thx - fixed my issue

**Comment by acerest** [comment]
Finally We have developed an OAuth 2.0 SSO Login System to solved it....................
