### ISSUE TITLE
Manual SQL query on dashboard not filtering datetime fields

### ISSUE THREAD

**Issue by Sc0ot3r** [grafana/grafana#69081]
### 
# What went wrong?

**What happened**:

  - Using a SQL Server query WHERE statement like "dateTimeField >= DATEADD(minute, -30, GETDATE())" used to filter and show results properly (ie filter the dateTimeField by the last 30min from now) but is no longer working. Instead it shows all results in the table

**What did you expect to happen**:

  - This WHERE statement should only show the last 30 minutes of table entries based on the dateTimeField and the current datetime value. This runs fine from any other SQL interface to the same table, but no longer works within a table dashboard panel (but used to)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a dashboard panel with Table visualization. Select SQL data source and then switch Query to 'Code'

**Step 2**:

- Enter a SQL query to a table where there is a datetime field, and enter a query like the following: ""SELECT * FROM myTable WHERE dateTimeField >= DATEADD(minute, -30, GETDATE())

**Step 3**:

- The returned query / table will not have any errors, but will not properly display only the last 30 minutes of data from the table based on the datetime formatted dateTimeField

### 
# What Grafana version are you using?

9.4.1 and 9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

RHEL 8.6

### User's Browser?

Google Chrome Version 113.0.5672.93

### Is this a Regression?

No

### Are Datasources involved?

Microsoft SQL Server 5.0.0

### Anything else to add?

This was previously working on version 9.4.1. We have since upgraded one of the servers to 9.5.2 and the issue persists. There has been no change to any of the data or table in the SQL data source.

**Comment by zoltanbedi** [comment]
Hey @Sc0ot3r,
Please help me understand this issue better. You are expecting to see the values from the table that are exactly 30 minutes before?

**Comment by Sc0ot3r** [comment]
s that is correct. To be a little more specific, I have a table that gets results dumped into it every 15 minutes. As a part of this, there is a column in the SQL Server table (MSSQL 2019) that holds a datetime value named 'checkTime'.

In my Grafana dashboards, I have been using the 'SELECT * FROM myTable WHERE checkTime>= DATEADD(minute, -30, GETDATE())' statement for the past year or so in order to display ONLY those rows in which the checkTime field is within the last 30 minutes of the current time. At some point in 9.4.1 I noticed that instead this query is now returning all of the rows from the table instead of just those within the last 30 minutes (using a table visualization). No changes had been made to the data store connector or settings within my Grafana setup and nothing has been changed within the MSSQL DB either. 

I am running grafana in HA with a PostgresDB so I decided to upgrade one of the servers to the latest version (9.5.2) in order to see if that resolved the issue but it did not. I get the same results. Making the exact same SQL query from any other ODBC connector or on the SQL server itself yields the correct results so I know it is not an issue with the query itself.

**Comment by zoltanbedi** [comment]
Thanks for the explanation @Sc0ot3r I'll take a look at it.

**Comment by Sc0ot3r** [comment]
@zoltanbedi any update on this?

**Comment by aangelisc** [comment]
Hi @Sc0ot3r, I'm really sorry that this fell through the cracks. I've tested this on the latest version of Grafana and can confirm that the function used in the query is now respected. I'm going to close this issue but feel free to re-open if this is still a problem for you 😊
