### ISSUE TITLE
Logs: Display older logs (pagination?) in dashboard panels

### ISSUE THREAD

**Issue by oussamazi** [grafana/grafana#69099]
### 
# What went wrong?

We have created a dashbord for logging on grafana with Loki, but  we can't show older logs with the Button that we have on Explorer Grafana :  

![image-grafana](https://github.com/grafana/grafana/assets/76183055/a17cc7a3-3954-46fd-9be4-d5c0327ddf0a)

we expect to have the same "Start of range" and "Older logs" on the dashbord as we have on the Explorer 

  - 

### 
# How do we reproduce it?

1- Use grafana 9.1.7 and data source Loki
2- Create dashbord based on the panel  below.
3- try to find "older logs" on the right of the log panel to display older ones like we do when we use Explorer instead of dashbord

### 
# What Grafana version are you using?

Grafana version : 9.1.7

### 
### Is the bug inside a Dashboard Panel?

This is the JSON MODEL : 
{
    "annotations": {
      "list": [
        {
          "builtIn": 1,
          "datasource": {
            "type": "grafana",
            "uid": "-- Grafana --"
          },
          "enable": true,
          "hide": true,
          "iconColor": "rgba(0, 211, 255, 1)",
          "name": "Annotations & Alerts",
          "target": {
            "limit": 100,
            "matchAny": false,
            "tags": [],
            "type": "dashboard"
          },
          "type": "dashboard"
        }
      ]
    },
    "description": "",
    "editable": true,
    "fiscalYearStartMonth": 0,
    "graphTooltip": 0,
    "id": 8,
    "links": [],
    "liveNow": true,
    "panels": [
      {
        "datasource": {
          "type": "loki",
          "uid": "QpeYgA84k"
        },
        "gridPos": {
          "h": 17,
          "w": 24,
          "x": 0,
          "y": 0
        },
        "id": 2,
        "options": {
          "dedupStrategy": "none",
          "enableLogDetails": true,
          "prettifyLogMessage": false,
          "showCommonLabels": true,
          "showLabels": false,
          "showTime": false,
          "sortOrder": "Descending",
          "wrapLogMessage": true
        },
        "targets": [
          {
            "datasource": {
              "type": "loki",
              "uid": "QpeYgA84k"
            },
            "editorMode": "builder",
            "expr": "{env=\"$Loki_env\", job=\"$Loki_job\"} |= `$Loki_filter`",
            "hide": false,
            "maxLines": 5000,
            "queryType": "range",
            "refId": "A",
            "resolution": 10
          }
        ],
        "title": "Loki logs",
        "type": "logs"
      }
    ],
    "refresh": false,
    "schemaVersion": 37,
    "style": "dark",
    "tags": [],
    "templating": {
      "list": [
        {
          "allValue": "env1,env2",
          "current": {
            "selected": false,
            "text": "env1",
            "value": "env1"
          },
          "datasource": {
            "type": "loki",
            "uid": "QpeYgA84k"
          },
          "definition": "label_values(env)",
          "hide": 0,
          "includeAll": false,
          "label": "Env",
          "multi": false,
          "name": "Loki_env",
          "options": [],
          "query": "label_values(env)",
          "refresh": 1,
          "regex": "",
          "skipUrlSync": false,
          "sort": 1,
          "type": "query"
        },
        {
          "current": {
            "selected": false,
            "text": "job1",
            "value": "job1"
          },
          "datasource": {
            "type": "loki",
            "uid": "QpeYgA84k"
          },
          "definition": "label_values({env=\"$Loki_env\"}, job)",
          "hide": 0,
          "includeAll": false,
          "label": "Job",
          "multi": false,
          "name": "Loki_job",
          "options": [],
          "query": "label_values({env=\"$Loki_env\"}, job)",
          "refresh": 1,
          "regex": "",
          "skipUrlSync": false,
          "sort": 0,
          "type": "query"
        },
        {
          "current": {
            "selected": false,
            "text": "",
            "value": ""
          },
          "hide": 0,
          "label": "Filter",
          "name": "Loki_filter",
          "options": [
            {
              "selected": true,
              "text": "",
              "value": ""
            }
          ],
          "query": "",
          "skipUrlSync": false,
          "type": "textbox"
        }
      ]
    },
    "time": {
      "from": "2023-05-15T01:47:09.000Z",
      "to": "2023-05-29T01:47:09.000Z"
    },
    "timepicker": {
      "hidden": false
    },
    "timezone": "",
    "title": "dashboard for logs",
    "uid": "He-YLrU4k",
    "version": 80,
    "weekStart": ""
  }

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Red hat 8.7

### User's Browser?

Google Chrome

### Is this a Regression?

No

### Are Datasources involved?

Loki go1.19.5

**Comment by mellieA** [comment]
@oussamazi the logs visualization panel is different than explore. I can submit this as a feature request for now.

**Comment by oussamazi** [comment]
@mellieA  Thank you :)

**Comment by matyax** [comment]
@oussamazi Thank you for opening this feature request! May I ask you what is your usecase for looking for older logs in dashboards? For dashboards, the usual approach is to change the current time range to see older data, so it will be hepful to know how this would be useful for you.

**Comment by oussamazi** [comment]
@matyax because its more easy espacially for developper team by scrolling instead of changing time range. and we hope getting the same as explore. 
Thank you

**Comment by matyax** [comment]
Makes sense! Thanks for the feedback.

**Comment by shchuko** [comment]
Hi!
I've also tried to create a logs dashboard and bumped into the same problem - it's hard to "load older logs". Can the issue be re-opened please @matyax

**Comment by matyax** [comment]
Hey @shchuko ! We now have infinite scrolling in dashboards. If you enable infinite scrolling and sort by newest first, you'll get older logs by scrolling to the bottom. Let me know if this works for you.

**Comment by shchuko** [comment]
@matyax hi, thanks for the quick response!

It turned out that  Grafana setup we use is outdated (v10) and we don't have the 'infinite scroll' feature available. We'll update our Grafana and check, thanks!
