### ISSUE TITLE
Zipkin view does not support shared id spans?

### ISSUE THREAD

**Issue by rmannibucau** [grafana/grafana#69098]
### 
# What went wrong?

Using spring-sleuth i get (default settings) spans with the same id (supports-join=true by default so server/client can share the id), in this case grafana skips one span in the zipkin rendering, would be neat to support it.

### 
# How do we reproduce it?

Here are the trace data:

```
[{"traceId":"57e9c09b49aff293","parentId":"57e9c09b49aff293","name":"function","id":"b22880ad43601aa0","timestamp":1685028734790516,"duration":1371471,"localEndpoint":{"serviceName":"back","ipv4":"10.244.0.39"}},{"traceId":"57e9c09b49aff293","parentId":"b22880ad43601aa0","name":"post /api/1","id":"443618b938df4730","timestamp":1685028734793653,"duration":1368882,"localEndpoint":{"serviceName":"back","ipv4":"10.244.0.39"},"tags":{"http.method":"POST","http.path":"/api/1"},"kind":"CLIENT"},{"traceId":"57e9c09b49aff293","parentId":"b22880ad43601aa0","name":"post /api/1","id":"443618b938df4730","timestamp":1685028734806157,"duration":1355303,"localEndpoint":{"serviceName":"duplicated-span","ipv4":"10.244.0.149"},"tags":{"http.method":"POST","http.path":"/api/1","mvc.controller.class":"MyController","mvc.controller.method":"get"},"kind":"SERVER","shared":true},{"traceId":"57e9c09b49aff293","name":"post","id":"57e9c09b49aff293","timestamp":1685028734788962,"duration":1373740,"localEndpoint":{"serviceName":"back","ipv4":"10.244.0.39"},"tags":{"http.method":"POST","http.path":"/app/api/1"},"kind":"SERVER"}]
```

### 
# What Grafana version are you using?

9.3.2

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by usmangt** [comment]
:Hi @rmannibucau,

Thanks for opening this issue.

Can you please provide the steps of reproduction so that the community can also try to reproduce it on a test machine? 

Thanks.

**Comment by rmannibucau** [comment]
@usmangt the simplest is to inject the shared (JSON) trace in zipkin and open it with grafana - or mock zipkin/grafana zipkin client to serve these data.
A more complex setup - mine - is to use spring-cloud-sleuth with default settings to collect traces in a microservice (server+client) setup which will create a set of "joined" spans (`shared:true` in the trace) so some spans will share the same id.

**Comment by rmannibucau** [comment]
can still be good to support zipkin/spring tracing OOTB if it was not fixed in between
