### ISSUE TITLE
[Bug] RPMs should restart service

### ISSUE THREAD

**Issue by alexpdp7** [grafana/grafana#6909]
> What Grafana version are you using?

grafana-4.0.2-1481203731.x86_64

> What OS are you running grafana on?

CentOS 7

> What did you do?

Upgrade the RPM package

> What was the expected result?

A working updated Grafana

> What happened instead?

Grafana website does not load incorrectly. Also:

```
$ sudo systemctl restart grafana-server
Warning: grafana-server.service changed on disk. Run 'systemctl daemon-reload' to reload units.
# this restores the website, but is annoying
```

**Comment by bergquist** [comment]
> Restarting services when packages are installed is not standard behavior for RPMs, or redhat/fedora based distros. Restarting the service would cause an interruption. And what if the config file were no longer compatible with the new version? The restart would fail and your service would be down.

https://github.com/grafana/grafana/issues/5742

If you want to enable auto restart you can configure it to do so.
https://github.com/grafana/grafana/blob/master/packaging/deb/default/grafana-server#L17

**Comment by alexpdp7** [comment]
@bergquist I used to think so, but I think that is no longer true:

https://fedoraproject.org/wiki/Packaging:Scriptlets#Systemd

> On upgrade, a package may only restart a service if it is running; it may not start it if it is off. Also, the service may not enable itself if it is currently disabled.
> ...
> The systemd package provides a set of helper macros to handle systemd scriptlet operations. These macros support systemd "presets", as documented in Features/PackagePresets. The %systemd_requires macro is a shortcut for listing the per-scriptlet dependencies on systemd.

, and it seems that indeed the httpd package in CentOS is using that to restart the service on upgrades:

https://git.centos.org/blob/rpms!httpd!/92bb46ca7c37ce73ddd26da323d0f24258980da8/SPECS!httpd.spec#L581

However, given that you provide the `RESTART_ON_UPGRADE` this is not a priority for me; for correctness sake you might want to look up the sources above to verify if they are truly authoritative and act accordingly.
