### ISSUE TITLE
Docs for Mimir: Strangely formatted TOC

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#69102]
### 
# What went wrong?

**What happened**:

  - User of Mimir docs reports strangely formatted TOC. See https://raintank-corp.slack.com/archives/C5PG2JK8W/p1684968875624659
  - In same Slack thread, Jack says some headings are probably skipped

**What did you expect to happen**:

  - Properly formatted TOC

### 
# How do we reproduce it?

See Slack thread above.

### 
# What Grafana version are you using?

9.5

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by Eve832** [comment]
@josmperez this ticket should probably be moved to the `mimir` repo. @osg-grafana can make that decision

**Comment by osg-grafana** [comment]
Looks like this was fixed by https://github.com/grafana/mimir/pull/5082.
