### ISSUE TITLE
Bug Bash: Final definition documented and communicated

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#69116]
Define an "official" definition of what the bug-bash is about. 
This shall include the why, what, when, how a bug bash is being performed.

**Comment by supilee** [comment]
Current definition progress can be seen [here](https://docs.google.com/document/d/1XSX9eqSagb0pN9ksUBnNiC8vaP_X9qW6Rc-W8gkmOgI/edit#heading=h.n7edjn8rk7vn)

**Comment by supilee** [comment]
@margotphelps - can you please review and add/comment where needed?

**Comment by margotphelps** [comment]
@supilee this document looks good to me. Let's share it out.
