### ISSUE TITLE
Disable all plugin signature validation for dev mode

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#69133]
At the moment, only if a plugin doesn't have a signature (or if the signature is valid), it is allowed to be installed when running Grafana in `dev` mode. The rest of signature issues (invalid, modified, etc) cause that the plugin is discarded. 

This behavior should be consistent so it makes sense that `dev` mode ignores (but logs) signature issues.

**Comment by sympatheticmoose** [comment]
We may want to revisit how `dev` mode works in the future, but for now we will leave as is
