### ISSUE TITLE
Show/Hide legend when rendering graph PNG

### ISSUE THREAD

**Issue by oryband** [grafana/grafana#6913]
# Bug - Grafana 4.0.1

Looking at #306, there's should be a feature that allows you to show/hide the legend when using graph PNG rendering (sharing) using the `hideLegend` parameter. However, this no longer works. I couldn't even find the file that was committed in #306.

Our graphs usually show the legend on-hover and hide the legend bar below/on the side of the graph. This means that by default PNG rendering is missing the legend. I can't seem to "force show" them using this feature (Also no documentation regarding this).

Looks like a regression? Please bring back this feature.

**Comment by gadisr** [comment]
👍

**Comment by torkelo** [comment]
hide legends is a graphite PNG rendering parameter, Grafana does use / support graphite PNG rendering but renders the panel it self via phantomjs, if your panel is configured without legend, the  PNG will also not have legend

**Comment by torkelo** [comment]
That should read does NOT use %)
