### ISSUE TITLE
[Feature request] json5 as dashboard.json

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#6915]
Hi! 
I am automating grafana with scripted dashboards. 
My tooling consists of python, jinja2 templating. So i am creating something like jinja templates for grafana's templates. Sometimes with rich data, that is not coded in metrics database (ip address, interface descriptions etc..)
Main problem that i'd encountered with all that stuff is that it is very annoying trouble of `last comma`.
Json 5 was designed to be human readable and writable. especially writable. Maybe there are possibility to add json 5 or similar json alternative as grafana's json. 

Tnx!

**Comment by torkelo** [comment]
json5 sounds interesting. Closing this for now as we can re-open it when json5 has good browser support / shims.

**Comment by bergquist** [comment]
@torkelo this could be limited to the backend only if we transform it between vintage json and json5. I  think this would be great for revisioning and dashboard history. 

Unfortunately I cant find any good lib for it
