### ISSUE TITLE
[Feature request] objects for templated vars

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#6916]
Hi!

I am automating grafana with scripted dashboards.
My tooling consists of python, jinja2 templating. So i am creating something like jinja templates for grafana's templates. Sometimes with rich data, that is not coded in metrics database (ip address, interface descriptions etc..)
One of problems that i've encountered was select list behavior. It will be much better if i can extend simple k/v list of 

```
{
"selected": false,
"text": "172.18.55.137",
"value": "558"
}
```

to something like that 

```
{
"selected": false,
"text": "172.18.55.137",
"value": "558",
"description": "My description",
"area": "City Name"
}
```

and than access that vars in text panel with dotted notation.
Tnx!

**Comment by daniellee** [comment]
The scripted dashboards feature is deprecated and will be replaced with something different - so closing this feature request and hopefully we will have something better that can handle cases like this.
