### ISSUE TITLE
[Feature request] Make server-side rendered images cleanup configurable

### ISSUE THREAD

**Issue by on99** [grafana/grafana#6917]
[Current implementation](https://github.com/grafana/grafana/blob/master/pkg/services/cleanup/cleanup.go#L67) is limited to cleanup images older than 1 day.

Can you make it configurable?

**Comment by bergquist** [comment]
@on99 Im curious. Why do you want to configure it? :)

**Comment by on99** [comment]
@bergquist I do not want to use AWS S3 to persist images for Slack. 1 day expiration is somehow too long for me. XD

**Comment by bergquist** [comment]
That implementation is only for cleaning images on the server running Grafana. Grafana renders the panel using phantomjs, persists it to local disk and then uploads the images to S3. 

Grafana never deletes the images from S3 only from the server running grafana.

**Comment by torkelo** [comment]
You can configure S3 TTL in your s3 bucket settings.

**Comment by on99** [comment]
Yes I know that. Basically what I want is that Grafana serve these images statically and returned image_url to `hubot-grafana` so it can be viewed by anyone in our Slack channel. I do not want to introduce AWS S3 because we have no access to S3 here.

**Comment by on99** [comment]
We even do not want to setup a webdav server 🤕

**Comment by bergquist** [comment]
I think you case is an edge case and we want to avoid adding to many settings for edge cases.

Perhaps you could.. do something nasty.. *cough* like write a cronjob to copy the files to another directory on the machine and set hubot to serve the files from the dir?

**Comment by on99** [comment]
Yes it's not a common use case. Maybe I can fork `hubot-grafana`, and serve it using nginx if grafana is not planning to serve these images statically.

BTW, 
```r.Get("/render/*", reqSignedIn, RenderToPng)```
creating image seems not so idiomatic.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/issues/6922
