### ISSUE TITLE
Spacing Tokens [design]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#69184]
```[tasklist]
### Tasks
- [ ] Create tokens for implementation in Figma
- [ ] Connect Figma components to the spacing tokens
```

**Comment by staton-hyse11** [comment]
@Aires-Grafana do we have these accounted for in Figma?

**Comment by Aires-Grafana** [comment]
Yes @staton-hyse11, this will be part of our new [Layout foundations file](https://www.figma.com/file/REcIXiadej5hgfXmx32nNZ/Saga-Layout?type=design&node-id=0%3A1&mode=design&t=cNNOdBH9q5G8NLai-1), under the page [Spacing and Sizing](https://www.figma.com/file/REcIXiadej5hgfXmx32nNZ/Saga-Layout?type=design&node-id=1-3&mode=design).

**Comment by Aires-Grafana** [comment]
@staton-hyse11 this issue can be closed once this is addressed in https://github.com/grafana/grafana/issues/78870
