### ISSUE TITLE
hi , i want install plagin in to my grafana panel (AJAX Panel for Grafana)

### ISSUE THREAD

**Issue by h0x00i** [grafana/grafana#6919]
hi , i want install plagin in to my grafana panel (AJAX Panel for Grafana)
but

`sudo grafana-cli plugins install ryantxu-ajax-panel
Failed to send requesterrorGet https://grafana.net/api/plugins/repo/ryantxu-ajax-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.net/api/plugins/repo/ryantxu-ajax-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
Grafana cli plugins install - install <plugin version (optional)>

USAGE:
Grafana cli plugins install [arguments...]

**Comment by h0x00i** [comment]
hi , i want install plagin in to my grafana panel (AJAX Panel for Grafana)
but 

`sudo grafana-cli plugins install ryantxu-ajax-panel
Failed to send requesterrorGet https://grafana.net/api/plugins/repo/ryantxu-ajax-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.net/api/plugins/repo/ryantxu-ajax-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
`

**Comment by bergquist** [comment]
What version of grafana are you using? The error message says that you get a timeout. What kind of connection does your server have?

**Comment by h0x00i** [comment]
grafana 4.0.1 on ARM raspberry pi 3
