### ISSUE TITLE
Generic OAuth: Redirect URL does not respect server.root_url setting

### ISSUE THREAD

**Issue by sclu1034** [grafana/grafana#69218]
### 
# What went wrong?

**What happened**:

When attempting to set up OAuth via [Authelia](authelia.com/) as generic OAuth in Grafana, the `redirect_uri` parameter passed to the authorization flow always uses HTTP, while Authelia wants HTTPS:

```
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Redirect URL is using an insecure protocol, http is only allowed for hosts with suffix 'localhost', for example: http://myapp.localhost/.
```

Both Authelia and Grafana run behind NginxProxyManager as reverse proxy and TLS termination. Grafana itself runs HTTP.

The description for the `server.root_url` setting, and multiple issues here where that setting was mentioned, suggests that it should be capable of forcing the prefix/base that the redirect URL is built from. But regardless of what values I set, the resulting URL never reflected any of it.

Even when I removed any mention of the outside domain from the config file (e.g. `server.domain`), the generated URL still didn't change, suggesting that something like the `X-Forwarded` headers take precedence in build that value.

**What did you expect to happen**:

I'd expect that `server.root_url` is used to build the `redirect_uri` query parameter and takes precedence over any automatic URL guessing when set.

### 
# How do we reproduce it?

Set up Grafana, Authelia and NginxProxyManager using https://www.authelia.com/integration/proxies/nginx-proxy-manager/ and https://www.authelia.com/integration/openid-connect/grafana/.

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Grafana Platform?

Docker

### Is this a Regression?

None

**Comment by sclu1034** [comment]
Here's the config: https://gist.github.com/sclu1034/584494f756127478936658a13ad62390.

**Comment by wrightbradley** [comment]
I've also experienced this behavior with Grafana and Okta. I've had to configure Okta to use `http` instead of `https` for the protocol for the redirect URI. Otherwise, I was hitting a HTTP 400 from Okta complaining that the provided redirect_uri was invalid. I'm currently running this version of Grafana: v9.5.2 (cfcea75916)

**Comment by usmangt** [comment]
Hi @wrightbradley 

So If I understand you correctly, you resolve this by changing `https` instead of `http` and then it worked?

**Comment by sclu1034** [comment]
The way I understand _wrightbradley_, they were able to work around the issue by letting Okta accept a redirect URL with `http`. I.e. Grafana would still send `redirect_uri=http://...` as a query parameter, but Okta would be fine with that.

That's not an option for me, as Authelia hard codes the aforementioned restriction of "http is only allowed for hosts with suffix 'localhost'"

**Comment by maurerle** [comment]
I have this problem too using Grafana 10.x running and **docker** and configuring it with Keycloak.
Settings in the grafana.ini are not respected, but adding it to the docker compose works:

```
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=True # to be used in iframe
      - GF_AUTH_ANONYMOUS_ENABLED=True
      - GF_SERVER_DOMAIN=grafana.example.com
      - GF_SERVER_ROOT_URL=https://grafana.example.com
```

I still have an issue with keycloak not accepting the redirect_url which now is: `http://grafana.example.com/login/generic_oauth`
But this is unrelated to grafana..?

**Comment by sclu1034** [comment]
> I still have an issue with keycloak not accepting the redirect_url which now is: `http://grafana.example.com/login/generic_oauth`
> But this is unrelated to grafana..?

No, that is _exactly_ the problem. You're telling Grafana that its external URL uses HTTPS, but it sets HTTP for the redirect URI anyways (which the user will eventually navigate to, i.e. it is such an external URL).
Neither does it seem to consider headers like `X-Forwarded-Proto`, `X-Forwarded-Ssl` or `X-Original-Url`.

**Comment by maurerle** [comment]
Sorry for my misinformation, it is actually `https` in my redirect:
I click on "Sign in with Example-OIDC" and I get redirected to a page with url:
`https://auth.example.com/realms/master/protocol/openid-connect/auth?client_id=grafana&redirect_uri=https%3A%2F%2Fgrafana.example.com%2Flogin%2Fgeneric_oauth&response_type=code&scope=profile+email+groups&state=xxx`.
This page then says `Invalid parameter: redirect_uri` even though I allow `*` as redirect_uris in keycloak (for now, production envs should not do this)
