### ISSUE TITLE
[Feature request] Add support for internal image store

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6922]
Grafana only support S3 and webdav storage for alert notification images. It should be possible to setup Grafana to use itself as image storage as well. 

This will not work with any current alert notifiers but since people can setup custom flows with webhook notifiers it would be a good thing to support this use case.

This would also require making the cleanup of data/pngs configurable to allow images to stay for a longer period of time. 

ref https://github.com/grafana/grafana/issues/6568
ref https://github.com/grafana/grafana/issues/6917

**Comment by jleclanche** [comment]
I'm running a web server on the same server Grafana is running on; it's a bit confusing why it's not possible to set up a special directory and path on and from which the images will be available.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10059

**Comment by Siddhu1096** [comment]
Hi @bergquist ,
I tried adding external_image_store to local. But still the image of the graph is not showing up in the notifications which is been shot to Microsoft Teams. Can you please tell me why? Thoughts? 

Here is the link of the bug I've posted on GitHub : https://github.com/grafana/grafana/issues/15997

**Comment by bergquist** [comment]
For Microsoft teams you need external images storage. So their service can download the image.

**Comment by Siddhu1096** [comment]
Okay . Thanks berg!
