### ISSUE TITLE
Requests to grafana-image-render should include the labels of the alert value if asked to

### ISSUE THREAD

**Issue by astrolemonade** [grafana/grafana#69220]
### 
# What went wrong?

**What happened**:

  - Wrong screenshot of panel is sent to alerts.

**What did you expect to happen**:

  - The screenshot of panel should adapt to the alert value labels.

### 
# How do we reproduce it?

**Step 1**:

- have a Grafana panel that monitors some metric that is dependent of a variable that can have multiple values(the type of variable is label values).

**Step 2**:

-  have an alert rule that has the dashboard and the panel linked to it and sends the alert to Slack. The alert should not filter out the label set on the grafana panel

**Step 3**:

- have the grafana-image-renderer set

**Step 4**:

- trigger the alert that happens to not be the default value of the variable(the first in alphabetical order)

**Step 5**:

- see that the screenshot sent does not take the labels that are common to the alert value and the panel in consideration.

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 22.04

### User's Browser?

Firefox 113.0.2 (64-bit)

### Is this a Regression?

None

### Are Datasources involved?

Prometheus 2.37.0

### Anything else to add?

I think it could be easily fixed by having a way to provide the list of labels to forward to the screenshot capture tool.
Instead of this:

```
http://localhost:3000/render/d-solo/aa6a5ecf-d447-4546-ab8d-11a46f9c95aa/panel?orgId=1&from=1685341815224&to=1685363415224&panelId=3&width=1000&height=500&tz=Europe%2FBucharest
```
call this:
```
http://localhost:3000/render/d-solo/aa6a5ecf-d447-4546-ab8d-11a46f9c95aa/panel?orgId=1&var-os=window&var-other-label=something-else&from=1685341815224&to=1685363415224&panelId=3&width=1000&height=500&tz=Europe%2FBucharest
```
notice the `var-os=window&var-other-label=something-else` addition to the render call.

I checked and the renderer completely ignores the variables that do not exist on the panel.

Grafana Image Renderer version: 3.7.1

**Comment by grobinson-grafana** [comment]
Hi! At this current time, taking a screenshot of the entire panel instead of just the series is on purpose because of how much work is required to take screenshots. We might be able to accommodate this in future as a feature request depending on how much demand there is for it 🙂 

My recommendation for the time being would be to open a discussion similar to https://github.com/grafana/grafana/discussions/38030.
