### ISSUE TITLE
[Bug] Elasticsearch 5.x: this.datapoints[a][1] is undefined

### ISSUE THREAD

**Issue by bqk-** [grafana/grafana#6923]
Please include this information:
- What Grafana version are you using? **Grafana v4.1.0-pre1 (commit: ee6cd72)** 
- What datasource are you using? **Elasticsearch 5.x**
- What OS are you running grafana on? **Debian**
- What did you do? **Tried to set a count**
- What was the expected result? **See the count**
- What happened instead? **Error**

Request I am trying to setup: 
![image](https://cloud.githubusercontent.com/assets/2953722/21097538/3aa46382-c065-11e6-9107-4a32050b9eaa.png)

Actual request result:
![image](https://cloud.githubusercontent.com/assets/2953722/21097592/84784a8c-c065-11e6-8abe-195bd012c038.png)

Executed query:
`{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"packetbeat-*"}
{"size":0,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1481537650887","lte":"1481541250888","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"http.response.code:\"500\""}}]}},"aggs":{"2":{"terms":{"field":"@timestamp","size":10,"order":{"_term":"desc"}},"aggs":{}}}`

Result in grafana:
![image](https://cloud.githubusercontent.com/assets/2953722/21097569/5fddbae0-c065-11e6-9cc3-bfd171418ab4.png)

**Comment by torkelo** [comment]
have you specified ES version in data source settings?

**Comment by bqk-** [comment]
Yes, as you can see it is executing the right request, an aggregation and not a count (https://github.com/grafana/grafana/issues/6238).

**Comment by torkelo** [comment]
Your doing a terms aggregation on Timestamp field, is this the table panel? (The graph panel only supports date histograms)

**Comment by bqk-** [comment]
Indeed, it was the issue, thank you.
