### ISSUE TITLE
[Bug] Axes labels are horizontal on rendered Images

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#6924]
Hi,

after the update to 4.0.2 the axes labels are horizontal instead of vertical on a rendered image, not in the dashboard view.

Grafana 4.0.2
Ubuntu 16.04
Graphite Source
The axes labels should be vertical on a rendered image
The axes labels are horizontal on a rendered image

View in Dashboard:
![capture1](https://cloud.githubusercontent.com/assets/10115997/21098461/a02433f0-c069-11e6-9de9-33390607ac07.PNG)

Rendered Image:
![capture2](https://cloud.githubusercontent.com/assets/10115997/21098460/a0205758-c069-11e6-9df8-3a30aadf6414.PNG)

**Comment by torkelo** [comment]
Fixed!
