### ISSUE TITLE
Improve UX of TraceID / TraceQL queries (which both use a single input but display different results)

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#69245]
In the Tempo data source we allow users to enter either a TraceID or a TraceQL query into the TraceQL tab (as shown below).

A TraceID query results in the TraceView being shown, while the TraceQL query results in a table with a list of matches traces/spans being shown. Each visualisation shown is based on different data formats in the TraceID and TraceQL query responses.

There has been at least one bug and some discussion around the implications of combining these queries into a singe input. This issue is a reminder to investigate how we might improve this workflow from a UX perspective.

![Screenshot 2023-05-30 at 09 04 27](https://github.com/grafana/grafana/assets/90795735/f4a56c7b-18e8-41a6-8364-1aa0dfdc890d)

**Comment by Joibel** [comment]
For me, with a single trace in the result (I haven't tried with multiple traces), I don't get the table (or cannot work out how to get the table), and instead get a useless trace as illustrated in #69050. Getting the table would be more useful than what I get, so any guidance on what the dashboard should look like for that would be helpful.

**Comment by jamesorlakin** [comment]
One of my usecases is to have a dashboard allowing an unrelated ID to be entered as a text box variable, and then loading everything related to that ID in various panels from Postgres,  Prometheus, Loki and Tempo for the purposes of triage. I can easily concoct a TraceQL query to filter to the correct (single) trace ID based on tags, but unfortunately from what I can tell Grafana doesn't seem to have a mechanism to really move forward from there.

I attempted to use a variable as a workaround to feed the trace ID directly into the Traces panel. However, the Tempo data source doesn't seem to provide a mechanism to perform a TempoQL query to populate the variable's values like other datasources can: https://github.com/grafana/grafana/issues/65503. The trace ID is output in my logs so being able to query for it and capture it would be immensely useful for other panels.

For this issue I feel Grafana needs a mechanism to force a TraceView from a TraceQL query, perhaps running the query and then requesting the trace contents if only one trace is returned? Of course the scenario where a query matches more than one trace would need some consideration but I think an error is acceptable in such a case. I'm almost imagining a little switch in the options panel to trigger this behaviour, e.g.:
![image](https://github.com/grafana/grafana/assets/7294642/22104973-9caa-41d9-bbbd-efa673e53dd6)
