### ISSUE TITLE
SMTP: 535 Error for password with Special Characters

### ISSUE THREAD

**Issue by slrwin** [grafana/grafana#69257]
### 
# What went wrong?

**What happened**:

  - When configured SMTP with the Email Server, User name and password with Speacial characters @, $, !, getting 535 Authentication failed message. Tried to enclose the password in double quotes which not helped.

**What did you expect to happen**:

  - SMTP Should be enabled and authenticated

### 
# How do we reproduce it?

**Step 1**:

- Edit Grafana SMTP settings and deploy the grafana.

**Step 2**:

- Go to Contact points

**Step 3**:

- Add a email address and try to send the email.

### 
# What Grafana version are you using?

v 9.2.4 (64017e8ca6)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

None

**Comment by slrwin** [comment]
@usmangt Hi, We are using the grafana provided Mail transfer Agent(MTA), Could you please point where the MTA configurations can be found.

**Comment by armandgrillet** [comment]
The alerting part of Grafana hands over emails to our shared MTA, removing alerting labels from this issue.

**Comment by slrwin** [comment]
> 

Could you please advise how can we access MTA settings?

**Comment by usmangt** [comment]
Hi @slrwin 

You need to check this configuration option in your MTA. The MTA is located on your server infrastructure and probably need to contact the admin who manages it. Grafana does not own the MTA part.

**Comment by alianman** [comment]
https://github.com/grafana/grafana/issues/74358#issuecomment-1791949383
This comment helped me resolve this issue. Password has to be escaped in triple double quotes.

**Comment by gelicia** [comment]
This looks to be solved by escaping special characters. Closing.
