### ISSUE TITLE
disebale login request in grafana

### ISSUE THREAD

**Issue by h0x00i** [grafana/grafana#6927]
I want to disable login request with entering to home panel or another page 

i trying to disable this  
------------------------------------------------------------------------------------------------------------------
    

        [users]
        # disable user signup / registration
        ;allow_sign_up = false
        # Allow non admin users to create organizations
        ;allow_org_create = true

        # Set to true to automatically assign new users to the default organization (id 1)
        ;auto_assign_org = true

        # Default role new users will be automatically assigned (if disabled above is set to true)
       ;auto_assign_org_role = Viewer

       # Background text for the user field on the login page
       ;login_hint = email or username

--------------------------------------------------------------------------------------------------------------- 
grafana  >> ver: 4.0.2
os >> ubuntu 16.04

**Comment by torkelo** [comment]
login request? 

Not sure I understand, do you want to disable so that users can't sign up? 
Then **uncomment** this line

```ini
 allow_sign_up = false
```

the `;` is a comment symbol, means the line is commented out / ignored

**Comment by h0x00i** [comment]
I want to be able to see all :)

**Comment by h0x00i** [comment]
I want to see active alarms (JSON file) and send via SMS to my user,
That's what I want to do
