### ISSUE TITLE
Dashboards: same UID dashboard permissions removed when one is deleted in any org

### ISSUE THREAD

**Issue by rmrustem** [grafana/grafana#69277]
### 
# What went wrong?

**What happened**:

  - Dashboards in different Orgs can share the same UID, but when I delete a dashboard in one Org, all the dashboards in the other Orgs with the same UID lose their permissions. That usually happens with popular downloaded dashboards that are added into many Orgs: i.e. - Node Exporter Full. In this case users with Reader/Editor role won't see the dashboards and will assume that someone had deleted them. However re-creating (re-downloading or uploading them) will fail because the dashboards do exist, but cannot be seen and modified.

**What did you expect to happen**:

  - Dashboards with the same UID in different Orgs do not share the same permissions and if one dashboard is removed, the others are not affected.

### 
# How do we reproduce it?

**Step 1**:

- Run a new Grafana from scratch, e.g. as a container on localhost and bind it to localhost:3000
- Open localhost:3000, log in as admin/admin and skip changing the admin password

**Step 2**:

- Go to `Server admin` → `Organizations`
- Click `New org` and create a new Org named `test`
- You are now in this `test` Org

**Step 3**:

- Click `Dashboards` → `New dashboard`
- Add a new panel — random walk example will do
- Click `Save` and save it as `New dashboard`
- Click `Dashboard settings` → `JSON Model` and copy the source code

**Step 4**:

- Go back, click `Profile`→ `Switch organization` and switch to the `Main Org.`
- Click `Dashboards` → `Import`
- Paste the source code from step 3, click `Load` and `Import`
- Now you have 2 dashboards with the same UID in different Orgs.

**Step 5**:

- Click `Dashboard settings` → `General`, scroll down, click the red `Delete Dashboard` button and confirm by clicking `Delete`.
- The dashboard is deleted in the `Main Org.`

**Step 6**:
- Click `Profile`→ `Switch organization` and switch to the `test` Org
- Open the `New dashboard` - it should be available in the recently viewed.
- Click `Dashboard settings` → `Permissions`
- ... and all the permissions but Admin are gone.

### 
# What Grafana version are you using?

9.2.4

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

AlmaLinux 8.7

### User's Browser?

Google Chrome 109.0.5414.119

### Is this a Regression?

No

### Are Datasources involved?

No

**Comment by usmangt** [comment]
Hi @rmrustem,

Thanks for opening this issue.

I am trying to reproduce this issue but the **Step 4** is not clear for me where you wrote:

Paste the source code from step 3, click Load and Import
Now you have 2 dashboards with the same UID in different Orgs.

When I try to paste the JSON code, I get this error message that the Dashboard name and also the UID are same.

![image](https://github.com/grafana/grafana/assets/69509548/661f8c22-6a29-46b8-ad52-a6704a3c33ec)


Did you modify it?

Aksing, because to be sure to follow your exact steps!

**Comment by rmrustem** [comment]
@usmangt Hello, It looks like you stayed in the same org where you created the dashboard (test), so it does not allow importing the same dashboard to the same org. You need to switch to another org (Main Org) first.

**Comment by usmangt** [comment]
Thanks for identifying it.

I was able to proceed further (i have now used Grafana version 10) and now I see this in the permission 

![image](https://github.com/grafana/grafana/assets/69509548/0ffd23aa-a814-479b-abdf-5ddafc3db025)


Is this what you meant? as to me it is not v.clear what exactly you meant by:
"... and all the permissions but Admin are gone."

Can you please update?

Thanks

**Comment by rmrustem** [comment]
Hello @usmangt , yes, that's the exact problem: the permissions are cleared and no one except for Admin is able to see the dashboard. The main issue here is that removing a dashboard in one Org cleares the permissions in another Org.

**Comment by usmangt** [comment]
Thanks for the quick reply.

I will now forward this issue to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by Jguer** [comment]
Hey @rmrustem , we might have found the issue, will update as soon as we've figured out a good way to fix it
