### ISSUE TITLE
[Feature request] align query time range to improve the cache hit ratio

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#6930]
I use Prometheus as TSDB. The Prometheus itself doesn't have query cache.
So I use nginx as a cache of Prometheus. The cache key is requrest url with query time range.

To improve the cache hit ratio, I want to align query time range for Prometheus.
For example, align query time range to fit 1 min alignment.

related PR and discussion.
https://github.com/grafana/grafana/pull/6178
https://github.com/grafana/grafana/pull/5954

**Comment by bergquist** [comment]
This is something we want to address somehow but we are not sure about how to implement it. I guess the big question is how it should be configured?

- Per datasource?
- Per org?
- Per instamce?
- Per dashboard?

**Comment by bergquist** [comment]
ping @iksaif

**Comment by mtanda** [comment]
I think "per datasource" is a good choice, because other configuration point is hard to control.
But, I think there are other demand, so providing this with overriding option is more better.

**Comment by iksaif** [comment]
I also think per datasource is a good choice

**Comment by mtanda** [comment]
I found related/similar issue.
https://github.com/grafana/grafana/issues/5190

**Comment by davkal** [comment]
This has now been merged as standard behavior for Prometheus data sources via #10434 . Please try it out and either reopen this one with feedback, or create a new issue.
