### ISSUE TITLE
[Bug] error logging not working

### ISSUE THREAD

**Issue by KlavsKlavsen** [grafana/grafana#6931]
Grafana version: grafana-3.1.1-1470047149.x86_64 (rpm) - on CentOS 7
app_mode = development

/etc/grafana/grafana.ini
[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
[server]
protocol = http
http_port = 3000
domain = example.org
root_url = https://graphs.example.org/grafana02/
[database]
type = sqlite3
[session]
provider = file
[users]
allow_sign_up = false
auto_assign_org = true
[auth.anonymous]
enabled = false
[auth.basic]
enabled = true
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
[log]
mode = console, file
level = Trace

ldap.toml - is exactly like https://github.com/grafana/grafana/issues/2447#issuecomment-128133254

But no matter what I try with this, the server logs its startup messages, and 1 line when I attempt to visit it:
t=2016-12-12T16:03:22+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=401 remote_addr=172.16.66.71 time_ns=69ns size=47

- which means auth fails.. but I get nothing else..  :(

I've checked daemon is restarted, and everything I can think of. I also checked output from journalctl -xe - and i gets the exact same and nothing more.

any tips appreciated.. IMHO it should find some error in the config and tell me about it, instead of just being silent :(

**Comment by torkelo** [comment]
Maybe you have a reverse http proxy in-front of grafana? Maybe something that has basic auth? If your sending basic auth headers to grafana and they do not validate then you will get a 401. 

Try grafana 4.x it has improved logging
