### ISSUE TITLE
Webapp crash when clicking on a dropdown, Minified React error #185

### ISSUE THREAD

**Issue by Bixilon** [grafana/grafana#69324]
Followup of https://github.com/grafana/grafana/issues/69068 beacuse it was closed with no reason

**Comment by reggermont** [comment]
Same on my side on ungoogled-chromium, cannot reproduce on Firefox

```
Minified React error #185: 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

@Bixilon can you add it again in the title, like your previous ticket for visibility purposes

**Comment by Bixilon** [comment]
@reggermont Done!
