### ISSUE TITLE
[Bug] Stale graphs in alerts

### ISSUE THREAD

**Issue by arodland** [grafana/grafana#6935]
Grafana 4.0.2 on Linux, Graphite backend. Alerting through Slack with image upload to S3.

This image sums it up:

http://i.imgur.com/94VL0JS.png

At first I thought it was falsely alerting, but then I realized, it's the same graph image every time, and the timestamps on the graph don't match the alert. Somehow or other it's re-sending the same rendered graph (or re-rendering the same old data) over and over for each alert instead of attaching a current graph.

**Comment by torkelo** [comment]
Maybe you accidentally stored the dashboard with an absolute time range? The image will use the saved dashboard time range
