### ISSUE TITLE
Loki: Lezer LogQL breaks with labels matching LogQL keywords

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#69374]
iI you have a label name that matches some of the LogQL keywords, the Lezer parsing breaks. Discovered while working with Distinct.

Examples:

![Image](https://github.com/grafana/grafana/assets/1069378/e7c01fa9-daca-430c-b83f-bea1e417c5a5)

![Image](https://github.com/grafana/grafana/assets/1069378/26920ad1-d9c7-4a39-a7c2-d56492528af2)

Notice the error nodes pointing to Distinct and Logfmt.

**Comment by ivanahuckova** [comment]
I don't think this is an issue in lezer parser, because using `logfmt` as label name/value does not produce valid query also according to Loki: 

![Image](https://github.com/grafana/grafana/assets/30407135/69a1860c-8c8b-4a19-82ae-47ce0d7e7fb4)

**Comment by matyax** [comment]
So we can consider this expected behavior. I wonder if we should document somewhere (if there isn't a reference) and/or let the user know that labels cannot match LogQL keywords.

**Comment by ivanahuckova** [comment]
Yeah, you can create an issue in `grafana/loki` repo to figure out if that is expected and if it should be documented or fixed.

**Comment by matyax** [comment]
Sounds good, thanks!

**Comment by matyax** [comment]
Update from a recent conversation: they see it as a bug in Loki and will fix it at some point.

**Comment by ivanahuckova** [comment]
This is not an issue with Loki data source, as it behaves consistently with Loki db. Therefore closing.
