### ISSUE TITLE
hide panel title on click popup

### ISSUE THREAD

**Issue by fredsimumind** [grafana/grafana#6937]
I am embedding grafana panel into iframe. But I found when I click on the panel title, it pops up an small tool bar window. Wondering how to hide it. The url I used is dashboard/file/aaa-dashboard.json?panelId=15&fullscreen. Following is the screen shot.

![121](https://cloud.githubusercontent.com/assets/24533726/21120612/13b43adc-c07d-11e6-8aff-dbfab3e7b9fd.PNG)

**Comment by torkelo** [comment]
yes, it's the panel menu. Not sure we can hide it in the iframe easily. Is this really a big problem?

**Comment by fredsimumind** [comment]
hi torkelo, thanks for replying. 
I am using grafana to monitor some of my cluster services. But the panel menu has some additional function such as export json files which i want to hide from users. It will be nice if I can have a option not showing the bar when embedding into iframe.

**Comment by torkelo** [comment]
why do you want to hide it from users? They are able to see it anyway if they just open chrome dev tools and look at the ajax calls.

**Comment by fredsimumind** [comment]
the end user might not use chrome dev tools. If there`s no way i can hide it on UI its fine. Thanks anyway.

**Comment by hanynowsky** [comment]
@torkelo  It's indeed a feature request. It's a matter of end user UI display and not the possibility to perform some actions as 'Export CSV or View Json'.
The  panel title should have an "editable": false/true, option at least
The ideal is to have:
"enableTitleActions": false/true,

Thanks in advance

**Comment by starlilyth** [comment]
For exporting real time graphs to a web application, Grafana provides a superior solution no one else does. 
Turning off menu controls for anon users seems a simple and obvious feature. I simply cannot understand the consistent refusal to implement an oft requested and seemingly trivial function.

**Comment by starlilyth** [comment]
Ah hah! Appending "&inactive" did the trick for putting it in "TV Mode". 
This is not well documented, it took me forever to find it.

**Comment by meghna-singh** [comment]
@starlilyth I appended "&inactive" but after a minute again the pop comes. Can you tell why this happened?
