### ISSUE TITLE
[Feature request] Graph Panel with rules according interval value

### ISSUE THREAD

**Issue by ldktta** [grafana/grafana#6938]
- What Grafana version are you using?
4.0.2

- What datasource are you using?
Elasticsearch 2.4.2

- What OS are you running grafana on?
Oracle Linux 7

- What did you do?
I would like to be able to change the graph panel graph automatically Draw Modes lines to Draw Modes bars according to the value of $interval. 
Example: 
$Interval  < 1d then Draw Modes in lines and Stack option false
$Interval  > 1d then Draw Modes in bars and Stack option true

- What was the expected result?
In search of one month, the graph panel is much simple to understend in bars. 
The interval for a month is usually one day. In lines is not so simple to see. 

Really recently I use grafana, but really is very good tool simple, dynamic and with great potential.
Thank you very much for all, grafama makes my work much simpler and efficient.

**Comment by torkelo** [comment]
This will likely not be implemented, you can enable stair case mode if you want to visualize the interval mode, makes it easier to see the "bars" when using line mode and interval is higher
