### ISSUE TITLE
Select the last used DS by default when adding a panel to a dashboard

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#69435]
**Problem**
> it feels kind of bad that the second panel I create (which does not show the data source picker), selects the default data source, and not the one I previously selected for the first panel I added. Wonder if we should auto-select the previously selected data source instead of the default?

**Solution**
* Select the previously selected DS instead of the default when adding multiple panels to a dashboard
* For the first panel, select the default DS
* The last DS will be kept per dashboard

**Comment by axelavargas** [comment]
Research Notes:

* The `QueryGroup` component is responsible for rendering the `DataSourcePicker -> DataSourceDropdown`. We've observed that even when we create a new visualization, the `datasource` prop always comes either with the `default` datasource or with the user-configured `datasource` if the panel is in the Edit state. 
* We'll use local storage to save the dashboard and the last datasource used. This property will be overridden every time a user edits a panel in a dashboard using `buildQueryOptions` in `PanelEditorQueries`.
