### ISSUE TITLE
After restarting my grafana pod, my user's permissions in dashboards disappear.

### ISSUE THREAD

**Issue by pulsarrrr** [grafana/grafana#69431]
### 
# What went wrong?

**What happened**:

  - After restarting my grafana pod, my user's permissions in dashboards disappear. In my circumstance, I can only find this kind of situation in k8s dashboards like the following ones.Besides, permissions won't go away in my loki dashboard or node-exporter dashboard.
![image](https://github.com/grafana/grafana/assets/120615592/6ddf219b-1127-4843-ae54-15bfb92b61ab)

**What did you expect to happen**:

  - I hope the permissions won't disappear after restarting grafana pod.

### 
# How do we reproduce it?

This is one of my k8s dashboard json file: Kubernetes / Compute Resources / Namespace (Pods)
[k8s dashboard.txt](https://github.com/grafana/grafana/files/11633334/k8s.dashboard.txt)

### 
# What Grafana version are you using?

Grafana v9.3.6(978237e7cb)

**Comment by usmangt** [comment]
Hi @pulsarrrr,

Thanks for opening this issue.

Please answer the following questions:

1- Was this restart made after updating grafana version?

2- Are you using grafana helm charts or some other method for running grafana on K8s?

3- Anything suspicious noted in the logs after this occured?

**Comment by pulsarrrr** [comment]
Hi @usmangt ,
Thanks for reply.

1- I didn't update grafana;

2-Yes! I'm using helm-charts-kube-prometheus-stack-43.0.0, it has a grafana dependency.

3-I didn't see any suspicious logs

Here is more info of my circumstance:
I have 4 organizations and there are 2 isolated orgs(let's call them bdp and cmi) using same dashboards,they can query different namespaces. To achieve this purpose, I copy one of bdp's dashboard(json file) and import it in cmi,then I just change the dashboard‘s variable(namespace) to limit the scope of query,I didn't change the uid.
Is it necessary to change the uid of each dashboard?

**Comment by usmangt** [comment]
Sending this issue to @grafana/grafana-authnz-team as I feel that this is the best match due to permission issue for the user. If not please let me know so I move it to the Dashboard team.

**Comment by mgyongyosi** [comment]
> Is it necessary to change the uid of each dashboard?

Could you please try changing the UID of the dashboard before the import? Did you see any warning before you imported the dashboard?

**Comment by mgyongyosi** [comment]
Similar issue (using the same helm-chart): https://github.com/grafana/grafana/issues/54086

**Comment by waovu** [comment]
i got this issue and i have solution as code for dashborad folder and control permission of grafana with python code. So, when grafana pod is restart, you can keep dashboard + folder + permission to view folder

**Comment by pulsarrrr** [comment]
I changed the UID of dashboards as @mgyongyosi mentioned , this sloved my problem and changing the UIDs by myself is easier  to categorize these dashboards for me.
