### ISSUE TITLE
[Bug] Grafana SMTP error: "Failed to send alert notification email"

### ISSUE THREAD

**Issue by scjoiner** [grafana/grafana#6944]
Please include this information:
- What Grafana version are you using?
4.0.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Docker
- What did you do?
Attempted to set up SMTP and send test notification
- What was the expected result?
Grafana to send test email to stated address
- What happened instead?
Grafana throws errors:

t=2016-12-13T14:59:22+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false                                                                                                         
t=2016-12-13T14:59:22+0000 lvl=info msg="Sending alert notification to"logger=alerting.notifier.email addresses=[root@****]                                                                                      
t=2016-12-13T14:59:22+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="Grafana mailing/smtp options not configured, contact your Grafana admin" 

SMTP config:

#################################### SMTP / Emailing ##########################                                 
[smtp]                                                                                                          
;enabled = true                                                                                                 
;host = 10.7.127.12                                                                                             
;user =                                                                                                         
;password =                                                                                                     
;cert_file =                                                                                                    
;key_file =                                                                                                     
;skip_verify = true                                                                                             
;from_address = grafana@**.*.* 

--

Our SMTP server is set up to accept all incoming requests, so the config ought to suffice for forwarding.

**Comment by bergquist** [comment]
Remove the `;` char. That's the comment char in ini files.

**Comment by fzhanghr** [comment]
hello
       what does mean the (host,user,password) in the smtp
