### ISSUE TITLE
[Auth - JWT]: `username/email_claim` don't support array values

### ISSUE THREAD

**Issue by ulken** [grafana/grafana#69451]
### 
# What went wrong?

I'm trying to use [JWT authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#configure-jwt-authentication) for an embedded iframe. The JWT token in question is provided by Azure AD B2C, which unfortunately isn't entirely standard compliant (surprise) and instead of containing an `email` claim, holds a string array `emails`.

For generic OAuth you support [`email_attribute_path`](https://github.com/grafana/grafana/blob/e789c2bf03f33569dab4be3b9882f3d5b11f87c9/pkg/login/social/generic_oauth.go#L323-L330C3), which allows for selecting the first element of the array by using: `emails[0]`. Would it be possible to extend `email/username_claim` to support such paths as well?

Either by keeping the same set of properties, but accepting more kinds of input, or by adding explicit properties `email/username_claim_path`.

I'm thinking something along the lines of replacing:

```go
if key := h.Cfg.JWTAuthUsernameClaim; key != "" {
    query.Login, _ = claims[key].(string)
    extUser.Login, _ = claims[key].(string)
}
```

with

```go
if key := h.Cfg.JWTAuthEmailClaim; key != "" {
    email := s.searchJSONForStringAttr(key, json.Marshal(claims)).(string)
    query.Email, _ = email
    extUser.Email, _ = email
}
```

and the same for `JWTAuthUsernameClaim`. With added error handling, of course. I realize [`searchJSONForStringAttr()`](https://github.com/grafana/grafana/blob/e789c2bf03f33569dab4be3b9882f3d5b11f87c9/pkg/login/social/common.go#L96) isn't available in the given scope, but you get the gist of it, I hope.

Thoughts?

### 
# How do we reproduce it?

There's really not much to test/reproduce here, I think you can quite easily verify the behavior by just looking at the relevant code.

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

No

### Grafana Platform?

Docker

### User's OS?

macOS Ventura 13.3.1

### User's Browser?

N/A

### Is this a Regression?

No

### Are Datasources involved?

No

**Comment by ulken** [comment]
I've never written a line of Go in my life, but I'll happily submit a PR if if this is something you'd be willing to support and we can settle on a specification.

**Comment by usmangt** [comment]
Hi @ulken,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by ulken** [comment]
@usmangt Thank you for your swift reply. Looking forward to the engineers' view on the matter. Let me know if I can help out in any way.

**Comment by ulken** [comment]
@usmangt would be nice to have an update whether this is going to be addressed or not. Like I said, I'd be willing to work on a PR, but I would need a 👍 from your part.

**Comment by usmangt** [comment]
Hi @ulken ,

I can see that this issue has been already assigned to our Authentication team and is already in their queue. I am sure that by next week you will get an update on this. But incase not let me know here.

**Comment by ulken** [comment]
@usmangt I highly appreciate your attentiveness!

**Comment by ulken** [comment]
@usmangt letting you know ☺️

**Comment by ulken** [comment]
> @ulken I don't see any issue with having an `email_attribute_path` and `login_attribute_path` properties for JWT Authentication. I'll add this issue to our backlog for now, but if you would like to implement it and contribute to Grafana then please open a PR and I will gladly review it!

All right, cool 😎 I'll look into it when I find the time (vacation now 🏖️). 

Just to be clear, you prefer adding _another_ property, instead of extending the behavior of the current one? Should the current one be deprecated then? Generic OAuth only has one, right?

> Some hints:
> 
> [email_attribute_path in generic_oauth](https://github.com/grafana/grafana/blob/main/pkg/login/social/generic_oauth.go#L272)
> 
> And probably you can reuse [this](https://github.com/grafana/grafana/blob/main/pkg/services/authn/clients/jwt.go#L189) function to search using JMESPath

Yeah, I've seen and referenced them above, thanks.

**Comment by mgyongyosi** [comment]
> Just to be clear, you prefer adding another property, instead of extending the behavior of the current one? Should the current one be deprecated then? Generic OAuth only has one, right?

Yes, for backwards compatibility I think adding another property is the way. Thanks!

**Comment by ulken** [comment]
> Yes, for backwards compatibility I think adding another property is the way. Thanks!

Right, but extending the existing properties wouldn't break backwards compatibility?

**Comment by mgyongyosi** [comment]
> Right, but extending the existing properties wouldn't break backwards compatibility?

Nope, because the `JWTAuthUsernameClaim` will stay intact and you are gonna add a new config settings for specifying an email attribute path.

**Comment by ulken** [comment]
> Nope, because the JWTAuthUsernameClaim will stay intact and you are gonna add a new config settings for specifying an email attribute path.

We're talking past each other here. I meant if we were to keep the _existing properties_ and _extend_ the behavior of those, we won't break backwards compatibility either.

But never mind, let's go with what you propose.

**Comment by abhinavms** [comment]
Hi @mgyongyosi, Since "emails" is not a standard field and only applicable to Azure, can we just modify the azureClaims structure to add the "emails" JSON field and then modify extractEmail?

```
func (claims *azureClaims) extractEmail() string {
	if claims.Email == "" {
		if claims.PreferredUsername != "" {
			return claims.PreferredUsername
		} else if len(claims.Emails) != 0 {
			return claims.Emails[0]
		}
	}

	return claims.Email
}
```
Do you see any possible issues with this approach?

**Comment by mgyongyosi** [comment]
Hey @abhinavms,

Thanks for your question! The dedicated Azure AD OAuth integration strictly follows OIDC standard claims that are documented [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-token-claims-reference) and it is working correctly for B2B users.

I spent some time investigating the reason for the missing `email` claim and I found out that this is by design for Azure B2C: https://github.com/MicrosoftDocs/azure-docs/issues/16566 (you can find a workaround in the issue)

If you use the Azure AD integration of Grafana then please take a look at the previously posted link and consider applying the workaround.

**Comment by abhinavms** [comment]
Got it. Thanks for the info!

**Comment by navneetbz** [comment]
Hey @mgyongyosi are there any updates on this issue? otherwise I would like to contribute to this.

**Comment by mgyongyosi** [comment]
Hey @navneetbz, that would be awesome! Feel free to open a PR and assign me as a reviewer! :) Thanks!

**Comment by linoman** [comment]
You can now look for nested attributes or a specific element in a list with the help of jmespath and 2 new configuration variables `email_attribute_path` and `username_attribute_path`.

**Comment by ulken** [comment]
> You can now look for nested attributes or a specific element in a list with the help of jmespath and 2 new configuration variables `email_attribute_path` and `username_attribute_path`.

Fantastic!

**Comment by ulken** [comment]
Am I right to assume this won't be back-ported to 9.X?

**Comment by linoman** [comment]
@ulken this is part of a new feature implemented for Grafana 11.x as the backport shows. We are not planning on backporting this feature.
