### ISSUE TITLE
[Feature Request] Better Support for KairosDB

### ISSUE THREAD

**Issue by ehatch90** [grafana/grafana#6945]
- Grafana version: 3.1.0, but we would like to use Grafana Current
- Datasource: KairosDB
- Operating System: CentOS

We would like to use the up-to-date versions of Grafana with new features etc. but the support for the KairosDB plugin often lags behind the support for the other datasource plugins. 

Now that datasource plugins have been unsupported entirely we are wondering what options we will have with the KairosDB datasource moving forward. Will Grafana/Raintank continue to provide any support for KairosDB as a datasource? It seems that the KairosDB Plugin doesn't currently work with Grafana 4.x. Our organization uses KairosDB extensively and we were previously excited to see support for it in Grafana. We need to know if this will be supported or if we should be looking for a new visualization tool. 

We use other services for alerting so we don't really need that we just want the datasource plugin to actually work.

**Comment by torkelo** [comment]
I have given away commit rights to https://github.com/grafana/kairosdb-datasource 
so maybe it will start seeing some changes soon.

**Comment by brianhks** [comment]
To whom did you give the access rights?

**Comment by torkelo** [comment]
to https://github.com/jifwin

**Comment by brianhks** [comment]
Can you give me commit rights to that repo?  I'm the creator of KairosDB and I would like to get some movement on this plugin.  I also have some testing resources that can help as well.

**Comment by torkelo** [comment]
@brianhks of course!! 

I told @jifwin that when your ready and merged a few fixes and want to update the plugin that is listed on grafana.net (that is installed on via grafana-cli), please submit PR to the plugin-repository, and add a new version entry here: https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json#L282

**Comment by jifwin** [comment]
@brianhks 

You are welcome to contribute to https://github.com/grafana/kairosdb-datasource repository. I'm currently cleaning up that plugin.
