### ISSUE TITLE
Show only active series under the cursor in tooltip

### ISSUE THREAD

**Issue by nvartolomei** [grafana/grafana#6946]
Would like a new option to enable displaying of only active series under cursor when hovering a chart.

Hover info: [All series, Single, Present] or something like that.

![screen shot 2016-12-13 at 18 33 44](https://cloud.githubusercontent.com/assets/543193/21149076/ee8f3964-c162-11e6-87b8-d961b52c3ec8.png)

**Comment by sslupsky** [comment]
Hi, you can presently do this in the Display settings for the graph panel.  See the screen shot below.


![screen shot 2016-12-13 at 3 05 17 pm](https://cloud.githubusercontent.com/assets/16888734/21161423/c63233e4-c145-11e6-9543-ecdbf290c638.png)

**Comment by nvartolomei** [comment]
@sslupsky I want the behaviour of **All series**. But on the hover to see only series that exists under cursor vertical line. Look again at screenshot i provided above. On the graph where I'm hovering are only 4 active series, but on hover i see all series every existed on the graph.

**Comment by sslupsky** [comment]
@nvartolomei Hmmm, ok, I think I understand now.  Would this work in the general case or only work at the end of the series?  In my experience where the series ends is generally random.  As I understand the hover, the info in the hover box is the value of the series at the points where the circles are, not where the vertical line is.

**Comment by nvartolomei** [comment]
@sslupsky should work in general case, because you can have a series start at the middle but you hover at the start. 

> info in the hover box is the value of the series at the points where the circles are, not where the vertical line is
Exactly.

**Comment by metalmatze** [comment]
This is something we are running into. We have a graph with a lot of Kubernetes namespaces. At a certain point the tooltip is just too big, so it doesn't fit the screen anymore.
We would like to only show the value for the namespace series being hovered.

**Comment by daveselan** [comment]
This missing feature is still an issue for us.

"single" mode isn't suitable when there are multiple values tightly grouped together on the graph.
"All series" shows everything, even values not represented in that area of the graph.

We still need a mode that sits between these two and shows only values found under the cursor.
A "Not null or zero" mode?  Could this be made a feature request.

Thanks.

**Comment by Dieterbe** [comment]
+1. I also wonder if it would make sense to still show the stale values, but visualize them differently.
e.g. the tooltip could have a section for current values, and a section for "stale" values.

I personally have no need for it (the suggested solution would be great for me), just throwing out the idea...

**Comment by Onepamopa** [comment]
+1 option to hide values with 0s (or less than X) on hover tooltip.

**Comment by hansthinhle** [comment]
Yes, pleaseee, I've been waiting for this option for such a long time, hope this could be implemented soon :D

**Comment by phemmer** [comment]
> Dieterbe:
> +1. I also wonder if it would make sense to still show the stale values, but visualize them differently.
> e.g. the tooltip could have a section for current values, and a section for "stale" values.

I have interest in the "hide null" functionality, but what you describe would not work for me, as my use case is the opposite. I have series which show up later, and thus it's the earlier time period which is missing. I want to hide the series when mousing over the earlier period where it doesn't exist.

**Comment by pawadski** [comment]
+1

When I hover over the graphs I expect to see what is under my cursor. Current behavior shows **everything that ever was** instead of what I'd like to see when I hover, and this is frustrating when you have a lot of metrics in a graph. :(

**Comment by patrick-GH** [comment]
+1  

would like to see only current results for where my cursor is at on the graph. makes trying to see when changes occur in the network harder as stagnate data is appearing for the same hop.

![Screen Shot 2020-07-22 at 12 35 41 PM copy](https://user-images.githubusercontent.com/39420482/88221646-a56f3980-cc19-11ea-9db7-63d825e79591.png)

**Comment by Eraac** [comment]
Once again, feature asked from years ... still no implementation

**Comment by Dieterbe** [comment]
> Once again, feature asked from years ... still no implementation

Out of all the items of work needed to achieve an implementation, the asking for it part is fairly minor.

If you want this to happen, you can make a concrete proposal or implementation, or pay someone (e.g. Grafana Labs) to do it for you.

**Comment by lightClouds917** [comment]
> +1
> 
> 当我将鼠标悬停在图形上方时，我希望看到光标下方的内容。当前行为显示的**是过去的所有内容，**而不是我在悬停时想要看到的**一切，**当图表中有很多指标时，这令人沮丧。:(
 I have the same problem

**Comment by lovasoa** [comment]
@Dieterbe as an opensource maintainer, I agree with you in general, but in this case someone opened a PR fixing the issue in november 2020 (https://github.com/grafana/grafana/pull/29405), noone answered until February 2021, and then they just closed the PR.

I understand that external contributors do not want to take time to implement anything in this context.

**Comment by leeoniya** [comment]
this is actually a really tricky issue to get right for everybody without adding a bunch of extra settings.

if you have unaligned datapoints, it becomes very frustrating when you can only hover a single point where the difference can be in milliseconds or fractional screen pixels.

i have a PR that brings back the old Graph behavior to the new Time series panel but with a narrower left/right scan margin (10px): https://github.com/grafana/grafana/pull/34552

please watch the videos in that PR read carefully through the linked issues lined from it.

a possible additional setting that may work for different use cases:

closest non-null threshold:
  - milliseconds
  - pixels

if that setting is 0, then it would only show exactly aligned datapoints, but it's really complicated to reason about what happens when you have multiple panels in a dashboard with a synchronized cursor, dozens of un-alinged series, and and potentially different thresholds for each panel.

**Comment by lovasoa** [comment]
Yes, I think you are talking about a related but different issue. This one is about what is displayed once you hovered over a set of points, not about deciding which set of points you hovered.

**Comment by leeoniya** [comment]
i'm confused what the distinction is, the tooltip display is synchronized to the highlighted/hovered points display. doing anything else seems really confusing and counter-intuitive, especially when there are lots of series and colors can be very similar.

**Comment by sslupsky** [comment]
You might want to consider rendering the vertical bar as a line with transparency and a width that is determined by the scan threshold.  That would make it clear which pixels it is "capturing".

**Comment by leeoniya** [comment]
i have considered that, actually :)

you know the immediate request after that, though: give us a way to configure the scan distance :D. if we decide to give users control over this, then i think this will be an easier sell, otherwise people will be frustrated with the inability to adjust this, and also those who have nicely-aligned datasets, or a single series will consider it a nuisance and will ask for an option to disable it.

**Comment by sslupsky** [comment]
indeed, for sure both issues you mentioned would need to be addressed.

**Comment by juarinu** [comment]
This request is "open" from 2016 and there is no resolution.... unbelievable!!!!

**Comment by contentfree** [comment]
Here is another illustration of the problem: 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/10958/209993692-bc664ae8-ee0e-41b9-b2ef-40ab39742950.png">

We want to see a tooltip containing _only_ the series that have data for the currently-hovered time (only the first seven series in the example screenshot).

**Comment by contentfree** [comment]
The above is manageable but we have other panels that have hundreds of series…

**Comment by Onepamopa** [comment]
Maybe they're planning a surprise fix for this @ the "Pro" version ...

**Comment by adela-almasan** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/81421. Thanks everybody!

**Comment by zhangjiongwx** [comment]
> This should be fixed by #81421. Thanks everybody!

not work when using a single query to display multiple serises，serises that don't have data for the currently-hovered time are still  shown in tooltip
