### ISSUE TITLE
Plugin Install: app_tls_skip_verify_insecure is ignored at Grafana startup

### ISSUE THREAD

**Issue by tp-jssk** [grafana/grafana#69462]
### 
# What went wrong?

**What happened**:

  - Grafana container exits with an error code when GF_INSTALL_PLUGINS, GF_PLUGIN_URL, GF_PLUGINS_APP_TLS_SKIP_VERIFY_INSECURE are set
  - Error: tls: failed to verify certificate: x509: certificate signed by unknown authority

**What did you expect to happen**:
  - TLS should be ignored when app_tls_skip_verify_insecure is set to true
  - Grafana installs the plugin zip file stored in the GF_INSTALL_URL

### 
# How do we reproduce it?

**Step 1**:

- Set  GF_PLUGIN_URL to s3 bucket location
- GF_INSTALL_PLUGINS to "grafana-athena-datasource"
- GF_PLUGINS_APP_TLS_SKIP_VERIFY_INSECURE to "true"

**Step 2**:

- Redeploy helm chart

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Alpine Linux

### Is this a Regression?

None

### Are Datasources involved?

grafana-athena-datasource

### Anything else to add?

I am running in Air-gap environment.

**Comment by usmangt** [comment]
Hi @tp-jssk,

Thanks for opening this issue.

Could you please provide us with the backend logs (the default location in Linux is `/var/log/grafana/grafana.log`) so that we can have more information about the error message?

**Comment by usmangt** [comment]
Thanks for the quick response.

I think you can ask for help and references at our community forums for [plugins](https://community.grafana.com/c/plugin-development/30)

I will now close this issue :+1:
