### ISSUE TITLE
Datasource provisionioning: Basic Auth field always checked despite provisioned value

### ISSUE THREAD

**Issue by academo** [grafana/grafana#69461]
### 
# What went wrong?

**What happened**:

When provisioning a datasource, regardless of the value set for "basicAuth". Grafana will always show the field check
![image](https://github.com/grafana/grafana/assets/227916/fabc8694-727f-451b-94df-c628f4eb37ae)

**What did you expect to happen**:

If `basic auth` is set to false (or not set) this should be not-checked in the UI. 

### 
# How do we reproduce it?

* Provision a datasource that uses the grafana standard http configuration component. e.g.: Prometheus
* Add the configuration to the provision datasources file
* Set `basicAuth` to false
* Open the configuration page after starting grafana
* observe the field is checked even if set to false or not set.

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Linux

### User's Browser?

Firefox

### Is this a Regression?

None

**Comment by marefr** [comment]
Error in a plugin so closing this
