### ISSUE TITLE
[Bug] Alerting: email alert does not identify or link to the organization

### ISSUE THREAD

**Issue by alexzorin** [grafana/grafana#6948]
> - What did you do?

Received an Grafana alert email 

> - What was the expected result?

I should be able to identify what organization and dashboard the alert has come from.

Clicking on the "View your alert rule" and "Go to alerts page" links should take me to the correct organization and dashboard.

> - What happened instead?

Email does not specify what organization the dashboard is on.

Clicking the links takes me to whatever organization I am currently logged into, which is most likely the wrong one, as we lean on the multi-organization capability of Grafana quite heavily.

So, clicking on the links just leads to "dashboard not found" and the only other way to find what alerted is to go through each organization by hand.

Alternatively I'd have to annotate each alert with the organization name but this is not a realfix.

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/issues/1613

**Comment by alexzorin** [comment]
I see. Quite a messy discussion.

I think, for now, I will patch my Grafana deployment with something like https://github.com/alexzorin/grafana/commit/6f837ad2f2243776a7d81e36c3ba333d20c89871.

Maybe it is not suitable for mainline Grafana, but it's killing our usage of it today, so I'd prefer to just merge it myself.

Would you be able to review it (it is very short) and LMK if it is doing anything particularly egregious or dangerous?

TIA

**Comment by bergquist** [comment]
@alexzorin That looks good. 

But I think it would make more sense to name the querystring just `orgid` and not delete it from the url. Then people could share the dashboard they are looking at.

**Comment by lafrech** [comment]
I'm facing the same issue with Grafana 8.3.3.

I just got an alert email with a link to

    https://domain.tld/alerting/list?alertState=firing&view=state

and ended up in the wrong org.

Thanks to the comments here and in #1613, I heard about `orgId` query argument and I checked that

    https://domain.tld/alerting/list?alertState=firing&view=state&orgId=1

does work.

Shouldn't `orgId` be included in the link in the alert email?

I think this is what is meant in https://github.com/grafana/grafana/issues/1613#issuecomment-281790485 so IIUC it should be there.

Or perhaps it used to be there but got lost in the alert feature rework?

**Comment by jlange-koch** [comment]
@lafrech 
We are facing the same Problem in Grafana 9.1.3 with our Alert notifications to Microsoft Teams.

Our workaround is to edit the default messaging template to include the orgId, like so:

`{{ if gt (len .GeneratorURL) 0 }}Source: [{{ .GeneratorURL }}?orgId=2]({{ .GeneratorURL }}?orgId=2)
{{ end }}`
