### ISSUE TITLE
[Bug] Failed to send alert notification email

### ISSUE THREAD

**Issue by voqk** [grafana/grafana#6949]
**Grafana version:** 4.0.2-1481203731 installed via apt-get
**Datasource:** InfluxDB 1.1.1-1
**Os:** Ubuntu 14.04.5 LTS

What did you do?
===========

I upgraded to Grafana 4 via apt-get and installed Postfix

What was the expected result?
===================

I wanted to send and receive a Test Alert Notification.

What happened instead?
================

No test email was sent. *Note* that I hadn't previously installed Postfix on this machine so I've never successfully sent any email from Grafana.

The log ouput shows the following:

```
lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses[<my email>]
lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="open : no such file or directory"
```

I changed grafana.ini under [log]

```
level = trace
filters = alerting.notifier.email:trace
```

but no additional information was output to the log.

Looking at `services/alerting/notifiers/email.go` I'm guessing it's something to do with not having `evalContext.ImagePublicUrl` and `os.Stat(evalContext.ImageOnDiskPath)` not being found. What is the ImageOnDiskPath? 

Bug
----
No debug / trace logging to alerting.notifier.email logger on email notification errors.

**Comment by bergquist** [comment]
Could you please share your smtp settings?

**Comment by voqk** [comment]
@bergquist here are the smtp settings. The cert is self signed for host GB0010APP06. Are you thinking this is the issue? 

```
#################################### SMTP / Emailing ##########################
[smtp]                                                                         
enabled = true                                                                 
host = GB0010APP06:25                                                          
;user =                                                                        
;password =                                                                    
cert_file = /home/hwright/ssl/certificate.pem                                  
cert_key = /home/hwright/ssl/key.pem                                           
;skip_verify = false                                                           
from_address = noreply@grafana.pcl                                             
                                                                               
[emails]                                                                       
welcome_email_on_sign_up = true                                                
```

I have tested email functionality by running

```
hwright@GB0010APP06:~$ echo "Test email body" | mail -s "Test email subject" <my email>
```

And received it in my inbox from hwright@GB0010APP06.

**Comment by bergquist** [comment]
Are the cert files readable for the grafana user?
`open : no such file or directory`

**Comment by voqk** [comment]
@bergquist I believe so. Both of the following commands exit with 0
```
hwright@GB0010APP06:~/ssl$ sudo -u grafana test -r certificate.pem; echo $?
hwright@GB0010APP06:~/ssl$ sudo -u grafana test -r key.pem; echo $?
```
I'm also able to read both files in vim if I `sudo -su grafana`

**Comment by bullardza** [comment]
Do you have postfix or something like it installed on the host?

**Comment by bergquist** [comment]
@voqk Could you try grafana 4.1.0-beta1 and see if the problem still exists?

**Comment by robin112** [comment]
i got the same error, i tired it with the ipaddress rather than giving localhost.

**Comment by torkelo** [comment]
@voqk  do you still have this issue? have you tested 4.1 ? the error handling is updated to give you a more specific error if there is an issue opening the cert files

**Comment by torkelo** [comment]
closing this due to lack of update

**Comment by jiargei** [comment]
Hej!
I also exposed this issue... getting 

Problem!
Failed to send alert notifications

I tried on hosted grafana as well as on self hosted, same behavoir for

- webhook
- slack

both are not working.... by cURLing the slack json, everything works well!

please support!
