### ISSUE TITLE
[Feature request] Singlestat: Ability to hide values that don't meet threshold

### ISSUE THREAD

**Issue by hanej** [grafana/grafana#6950]
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
InfluxDB 1.1.0
- What OS are you running grafana on?
RHEL 7.2

I would like to build a NOC dashboard that only shows areas of interest.  To do so I need to filter out all "good" states and only show the "warning" or "critical" states.  For the Singlestat plugin I would like the ability to not show the metric at all unless it meets the minimum threshold.  This is useful when repeating panels based on hostname.

Also if it's possible to sort the panels based on value instead of by title that would be fantastic.  This way we can bubble up all of the highest offenders to the beginning of the row.

**Comment by torkelo** [comment]
closing this as it is similar to https://github.com/grafana/grafana/issues/4470

**Comment by hanej** [comment]
It's not the same as #4470 though.  In my use case the panels are not empty.  They have values but if the value doesn't meet the threshold they don't display.  This way only those metrics that need attention will show.  Basically hide all green metrics and show yellow and red ones.

**Comment by jportoles** [comment]
+1 Ability to filter what is shown in a graph would be useful for graphs with a very large amount of labels where the query language of InfluxDB falls short. "Show only labels whose aggregated value for this time period and interval meet this threshold" would fill that gap.

**Comment by Emmadiv** [comment]
+1
Good day! I have the same need for implementation. We have 76 metrics, with values on the panels in the dashboard, and this is too much, especially if we add more data, we won't keep track of anything, it's hard to read.
Because of this, the panel needs to be displayed only when the threshold is exceeded.
@hanej Tell me, could you find a solution to your question, I faced the same problem?
Thank you in advance

**Comment by YunaBraska** [comment]
+1 I am also missing this feature to see only the critical parts. There could be multiple ways like sorting or hiding panels. Everything would be good for me, currently we have a lot of manual work to do to check if everything is up and running. E.G. go through several dashboards, scroll through them to see the panel of interest,... I really would like to see on one view what's broken or critical without scrolling
