### ISSUE TITLE
core: server takes a while to be available

### ISSUE THREAD

**Issue by asarubbo** [grafana/grafana#69517]
### 
# What went wrong?

**What happened**:

  I'm running this grafana since 3 years. Now I'm at 9.5.1 and I noticed that it takes a while for start the service.
  I have increased the log to debug and I can see that it 'loses' 17 seconds between:
  logger=ngalert.sender.router t=2023-06-03T21:44:18.884424854+02:00 level=debug msg="Finish of admin configuration sync"
logger=accesscontrol t=2023-06-03T21:44:35.412319053+02:00 level=debug msg="adding scope attribute resolver" prefix=annotations:id:

I'm attaching the full log.

**What did you expect to happen**:

  - 

### 
# How do we reproduce it?

**Step 1**:

- Start the grafana service

### 
# What Grafana version are you using?

Version 9.5.1 (commit: bc353e4b2d, branch: HEAD)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Gentoo

### Is this a Regression?

Yes

### Anything else to add?

[grafana.log](https://github.com/grafana/grafana/files/11644118/grafana.log)

**Comment by papagian** [comment]
@grafana/grafana-authnz-team can you have a look

I confirm that `adding scope attribute resolver` takes the longest time: this is the list with the 10 longer tasks:
```
(datetime.timedelta(seconds=16, microseconds=527900), 'logger=accesscontrol t=2023-06-03T21:44:35.412319053+02:00 level=debug msg="adding scope attribute resolver" prefix=annotations:id:')
(datetime.timedelta(seconds=10, microseconds=4900), 'logger=ngalert.scheduler t=2023-06-03T21:50:50.007491242+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=1000), 'logger=ngalert.scheduler t=2023-06-03T21:47:50.002080011+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=800), 'logger=ngalert.scheduler t=2023-06-03T21:46:50.003386757+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=600), 'logger=ngalert.scheduler t=2023-06-03T21:54:20.002214297+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=500), 'logger=ngalert.scheduler t=2023-06-03T21:45:20.002713513+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=500), 'logger=ngalert.scheduler t=2023-06-03T21:52:20.003227972+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=400), 'logger=ngalert.scheduler t=2023-06-03T21:45:50.002804972+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=10, microseconds=100), 'logger=ngalert.scheduler t=2023-06-03T21:55:20.002344715+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')
(datetime.timedelta(seconds=9, microseconds=999900), 'logger=ngalert.scheduler t=2023-06-03T21:46:20.002387421+02:00 level=debug msg="Alert rules fetched" rulesCount=0 foldersCount=0 updatedRules=0')```

**Comment by kalleep** [comment]
@papagian I am pretty sure that adding a scope resolver is not the cause of this, it only adds a function to a map https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/resolvers.go#L46-L49.

I guess there are other stuff going on between 
```
logger=ngalert.sender.router t=2023-06-03T21:44:18.884424854+02:00 level=debug msg="Finish of admin configuration sync"
logger=accesscontrol t=2023-06-03T21:44:35.412319053+02:00 level=debug msg="adding scope attribute resolver" prefix=annotations:id:
```

That is not being logged?
