### ISSUE TITLE
Docker Swarm secrets not working with docker enviroment 

### ISSUE THREAD

**Issue by darks00ul** [grafana/grafana#69522]
### 
# What went wrong?

**What happened**:

  - The stack starts but it not take the password defined using `echo "mypassword" | docker secret create password.pwd -` and it still use the default “admin” password
  - If I connect to my docker using docker exec -it xxxxxxxxx bash I can see the expected password with cat /run/secrets/password.pwd

**What did you expect to happen**:

  - I expected that the grafana take the enviroment `- GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/password.pwd`
  - If I use `- GF_SECURITY_ADMIN_PASSWORD=mypassword` it works

### 
# How do we reproduce it?

**Step 1**:

- Setup a docker swarm enviroment 

**Step 2**:

- With Docker Swarm created, create a secret using `echo "mypassword" | docker secret create password.pwd -`

**Step 3**:

- Modify docker compose to use the secret like this: 

version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.5.2
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/password.pwd
    secrets:
      -
        source: password.pwd
        target: /run/secrets/password.pwd
        mode: 0444
secrets:
  password.pwd:
    external: true
volumes:
  grafanadata: {}

### 
# What Grafana version are you using?

9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 22.04

### Is this a Regression?

None

### Anything else to add?

I followed this guide 
[https://efrecon.github.io/docker-secrets-with-grafana/](url)

**Comment by usmangt** [comment]
Hi @darks00ul,

Thanks for opening this issue.

I just answered this question on the community forum in [this](https://community.grafana.com/t/docker-swarm-secret-file-not-working-with-grafana/88921/2) post.

Please check my answer there and let us know if that helps you out.

**Comment by darks00ul** [comment]
> 

Hi @usmangt, thank you so much, your reply help me fixing this issue...
For everyone that got stuck like me, the solution is:

> Try it seems that you are missing one additional underscore “_” as it requires 2 underscore between PASSWORD and FILE i.e. GF_SECURITY_ADMIN_PASSWORD__FILE
