### ISSUE TITLE
Error: different links for different organisations

### ISSUE THREAD

**Issue by homonto** [grafana/grafana#69553]
### 
# What went wrong?

**What happened**:

  - I have created 2 organisations but while switching between them one is always ok https://192.168.1.43:3000), while second goes to localhost:3000 so nothing is there

**What did you expect to happen**:

  - both to go to https://192.168.1.43:3000

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and login

**Step 2**:

- change organisation

### 
# What Grafana version are you using?

msg="Starting Grafana" version=9.5.2 commit=cfcea75916 branch=HEAD compiled=2023-05-04T09:56:30Z

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

debian 11

### User's Browser?

safari, chrome, firefox

### Is this a Regression?

None

### Are Datasources involved?

no

### Anything else to add?

continuation of the topic with Antonio C Merello from here:
https://community.grafana.com/t/error-different-links-for-different-organisations/88207/3

check the logfile here:
https://papio.uk/grafana.log

screenshots:
https://global.discourse-cdn.com/grafana/original/3X/b/f/bf162298ec90165615e137b815ba5cef60b24e59.png
https://global.discourse-cdn.com/grafana/original/3X/b/a/ba82f48b9508c663fbb502fabea81ae57338bb23.png
https://global.discourse-cdn.com/grafana/original/3X/6/0/60a764a99bacccb16ad59ebb6c09886159a3c159.png
https://global.discourse-cdn.com/grafana/original/3X/f/e/fe042edce4ce3bd7000c1ff06d8c95d66cd55e8d.png

**Comment by homonto** [comment]
I can give you credentials so that you can see how that works - you would have to send me email to mine:
homonto@gmail.com 
so that I can share with you

**Comment by sakjur** [comment]
Have you set the [server.domain](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#domain) setting in your grafana.ini configuration file to 192.168.1.143? I believe it's located in `/etc/grafana/grafana.ini`, you can also set it as an environment variable when starting the service `GF_SERVER_DOMAIN=192.168.1.143`.
