### ISSUE TITLE
Improve Clustering support & Alerting rule execution distribution 

### ISSUE THREAD

**Issue by Civil** [grafana/grafana#6957]
We have several dozen of grafana instances and it seems that now each grafana instance do all the checks and sends all the alerts and notifications.

Is there any way to cluster alerting stuff for grafana?

**Comment by bergquist** [comment]
That's currently not possible. 

But you can turn off the alert engine on all instances except one to avoid sending multiple notifications.
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L396

**Comment by jaimegago** [comment]
+1

**Comment by pdf** [comment]
@jaimegago please stop making `+1` comments.  If you wish to add your `+1`, use the reaction icon on the original issue post, you may subscribe to issues on the right without posting a comment.  Adding useless comments just spams everyone who is subscribed to an issue.

**Comment by jaimegago** [comment]
@pdf I'm with you on the using the +1 reaction as I'm being "+1 spammed" myself on issues I've filed or started watching more than a year ago. The problem is the "+1 reaction" github button is not AFAIK the official way for this project to track interest in issues as I have yet to read a comment from one of the main contributors "outlawing" +1 comments hence my decision. Honestly they're not that bad and I can see arguments in favor of the them but I diverge and flaming is not my intention.

**Comment by iksaif** [comment]
Turning off the alert feature in most instances makes it quite hard to build a reliable system on top of Grafana. https://github.com/grafana/grafana/issues/7534 could be a solution but it's probably not enough for people that don't use prometheus.

Most clustered installation already use a shared database. Maybe this could be used to either:
* Provide a leader-election mechanism based on transactions
* Simply de-duplicate notifications

cc: @Thib17

**Comment by SimenB** [comment]
Should this be closed? #7632

**Comment by daniellee** [comment]
@SimenB No, dedupe only partially solves it. We also want to load balance alerting between different servers.

**Comment by SimenB** [comment]
Ah, gotcha. Is there a separate issue for supporting multiple servers in HA, ref changelog for 4.2 ("Next up for a better HA situation is to add support for workload balancing between Grafana servers.")? Or is this a good issue to track?

Or issue specifically is that it seems like logging in doesn't propagate across replicas, reducing to a single replica removed the error for us

**Comment by daniellee** [comment]
I do not think there is separate issue for HA (I couldn't find one at least).

Regarding your second point, what are you using for sessions? Maybe this will help: 

http://docs.grafana.org/tutorials/ha_setup/#user-sessions

**Comment by SimenB** [comment]
Ah, we'll try to get the sessions into a cache, thanks!

**Comment by SimenB** [comment]
To report back, sticking the session into a db worked great 😄

**Comment by jomenxiao** [comment]
Hi 
`Clustering support`  is going?

**Comment by tehlers320** [comment]
Any update on when this may be a priority? I see Walmartlabs tried to make a merge but wouldn't sign the CLA https://github.com/grafana/grafana/pull/8657

**Comment by jifwin** [comment]
I'd like to propose a solution to distributed alerting. 

Let's use existing alerting table as a queue for alerts scheduling. Instead of fetching the entire "alert" table, let's select them one by one, like this:
```
BEGIN;
SELECT * FROM alert WHERE now()-last_execution > frequency ORDER BY last_execution LIMIT 1 FOR UPDATE;
```
That query returns the next alert that should be executed. If it exist, we update its last_execution:
```
UPDATE alert SET last_execution = CURRENT_TIMESTAMP where alert_id = ALERT_ID
END
```
If transaction is successful, we execute the alert on that machine, otherwise we try to get next alert (after configurable sleep. This should work with multiple instances of Grafana, as long as the number of alerts is not huge (it could cause congestion). Anyway, it's definitely better than selecting the full table.

@torkelo @bergquist Please share your options on this. If this sounds ok to you, I will begin the implementation.

**Comment by bergquist** [comment]
It would be quite hard to know if all rules are evaluated as expected at the given interval. Accounting for slow responses/timeouts. 

I would prefer a solution where we shard alert rules among servers based in ID instead.

**Comment by jifwin** [comment]
We could use a separate table for alerts reports. 

If we go with sharding, how would you rebalance alerts across servers when machine is added or removed?

**Comment by bergquist** [comment]
My current thinking is that it should be possible to write heartbeats to the database and use jump hashing or something similar to distribute the alerts among servers.

**Comment by jifwin** [comment]
Then we probably need a leader responsible for distribution, right?

**Comment by tehlers320** [comment]
This is how seyren scales on the [Expedia fork ](https://github.com/ExpediaInc/seyren-1)
SEYREN_WORKER_COUNT=3
SEYREN_WORKER_INDEX=1 (and then 2,3 on 2 more nodes)

It's not ideal but it does work and may be an easy way to get started without allot of complication. I do not think it's a long term solution though.

**Comment by bergquist** [comment]
@tehlers320 yea that might be a good start. But I'd like to use the database for finding out the worker index to make it easier to operate.

**Comment by jifwin** [comment]
@bergquist Do you mean storing ids for workers in db?

**Comment by bergquist** [comment]
Something like that would be good. 

But I'm not sure we need a leader. If all Grafana servers send a heartbeat to the database I think we could rely on the sort order in that table and distributed the alert rules based on what position each server have in that sort order.

**Comment by johntdyer** [comment]
Any thoughts on this ? Its currently a big problem for us... really disappointed to see #8657 closed due to a CLA issue

**Comment by armandgrillet** [comment]
When running Grafana Alerting (not legacy alerting) in high availability mode, you can disable the execution of alerts on certain Grafana instances to avoid receiving multiple alerts: https://github.com/grafana/grafana/blob/fb2b9f33d238b4029cb9c1a5f8465b46c895d08a/conf/defaults.ini#L1165
