### ISSUE TITLE
Prometheus: Disable recording and alerting rules api endpoint

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#69586]
The [rules API](https://prometheus.io/docs/prometheus/latest/querying/api/#rules) for some instances can be expensive. 

Allow users to configure and disable recording rules.

**Comment by Massakera** [comment]
Sorry I'm still new to Grafana codebase, can you point to where the recording rules is setted? I see that we have a `recording.yml` file but I don't know if its the right file

**Comment by thesixpathguy** [comment]
Hi, I am interested to work on this issue. Can you please elaborate the issue once?

**Comment by shantanualsi** [comment]
Hi @gtk-grafana can you please check the PR for the fix you described? I need some help in framing the right sentences for the documentation.

**Comment by gtk-grafana** [comment]
@shantanualsi everything is looking great, thanks so much for taking the time to add this!
