### ISSUE TITLE
Changelog is displayed weirdly starting from the end of 10.0.0-preview

### ISSUE THREAD

**Issue by jmaixl** [grafana/grafana#69589]
### 
# What went wrong?

**What happened**:

  - Changelog Markdown shows up incorrectly. Example below. 
  - 
![image](https://github.com/grafana/grafana/assets/47194854/8635c385-2f43-442f-a824-980d29e3fa06)

### 
# How do we reproduce it?

**Step 1**:

- Navigate to https://github.com/grafana/grafana/blob/main/CHANGELOG.md

### 
# What Grafana version are you using?

n/a

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by Soham-glitch** [comment]
what kind of incorrection is it ? Can you elaborate a little bit

**Comment by tonypowa** [comment]
thank you for crating this issue @jmaixl 

i see the problem with the markdown starts in line 184 
 https://github.com/grafana/grafana/edit/main/CHANGELOG.md

I am tagging the release engineering team

**Comment by zerok** [comment]
Hi :) Thanks for bringing this to our attention! Looks like there is a stray backtick flying around in there. I'm not yet sure where in the process this got introduced but will look into it now.

**Comment by zerok** [comment]
Formatting is now solved and now we run into a size limit ^_^ Working on it, though 🙂

**Comment by zerok** [comment]
Should work again. Thank you 🙂
