### ISSUE TITLE
[BUG] Template variables with custom cloudwatch namespaces "Unable to call AWS API"

### ISSUE THREAD

**Issue by Pbants** [grafana/grafana#6958]
- What Grafana version are you using?
Version 4.0.2 (commit: v4.0.2)
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
CentOS 6.8 with HVM updates on Amazon EC2
- What did you do?
Created a metric() query template that works with all namespaces except the custom namespaces generated when using detailed monitoring in cloudwatch.
- What was the expected result?
When using the metric(namespace) query a list of metrics in that namespace should be displayed.
- What happened instead?
Receive an error Unable to call AWS API and no metrics are shown.  If I switch to a built in namespace such as AWS/EC2 it works fine, it only fails with custom namespaces.  I have tried different naming conventions etc. with no luck.

**Comment by torkelo** [comment]
@mtanda what's your thoughts?

**Comment by carlossilva** [comment]
Would be nice to be able to retrieve custom cloudwatch namespaces as these are the only way to store your own metrics in cloudwatch.

**Comment by mtanda** [comment]
Sorry, I forgot the detail.
You may need to specify the region like `metric(namespace, region)`.
It is little bit tricky, but the region is required for custom metrics.
