### ISSUE TITLE
Bug - graph displaying wrong numbers

### ISSUE THREAD

**Issue by miketwenty1** [grafana/grafana#6959]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? - 4.0.1
- What datasource are you using? - influxdb
- What OS are you running grafana on? - OS X El Capitan 10.11.16 / Chrome 
- What did you do? - template variables with query. group by variables - see images for details
![screen shot 2016-12-14 at 1 08 59 pm](https://cloud.githubusercontent.com/assets/7761473/21194826/5ce97c2a-c1ff-11e6-94e8-5b0443b4a750.png)
![screen shot 2016-12-14 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/7761473/21194832/61264e1c-c1ff-11e6-937c-3041c7d1f479.png)

- What was the expected result? correct graph
- What happened instead? incorrect graph - but correct numbers

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by miketwenty1** [comment]
also like to note.. data in influxdb looks good and meshes numbers on the pop-up,  seems that the upper line for some reason is summing both counts, instead of displaying them individually.

**Comment by torkelo** [comment]
check tooltip option for stacking, you have it set to cumulative, meaning if stacking is enabled tooltip will show stacked value. You can change this in display tab
