### ISSUE TITLE
Alerting: Alert using Cloudwatch metric query with GROUP BY is not labeling correctly

### ISSUE THREAD

**Issue by jmaixl** [grafana/grafana#69591]
### 
# What went wrong?

**What happened**:

  - Using a Cloudwatch Metric Query that uses GROUP BY results in the group-by field not being set to the corresponding value. Instead, all results are set to one identical value. The initial query/graph looks fine, but when applying mathematical expressions on the query, the correct label changes.

![image](https://github.com/grafana/grafana/assets/47194854/3991960d-1adb-44a9-b0c2-de080f34447b)

### 
# How do we reproduce it?

**Step 1**:

- Create an alert using CloudWatch Metrics, specifically Metric Query using a Group By clause.

**Step 2**:

- Apply math expression to query result like mean.

**Step 3**:

- Run/preview the query

### 
# What Grafana version are you using?

v9.4.7

### 
### Grafana Platform?

Docker

### User's Browser?

Chrome, Firefox, Opera

### Is this a Regression?

None

### Are Datasources involved?

Cloudwatch

**Comment by kevinwcyu** [comment]
Hi @jmaixl, I believe this issue is related to https://github.com/grafana/grafana/issues/66221 where the label for metric queries is not being set.

**Comment by jmaixl** [comment]
I can believe that since they both are bugs with Cloudwatch metric query labeling. The bug observed here is a little different since I'm observing it in a mathematical expression. Better if they're both the same issue though!

**Comment by dvallejo89** [comment]
Hi

I am experiencing the same problem. When I use the metric query expression in alerts, and perform the reduction, the label name gets overwritten as Series1.


![Image](https://github.com/grafana/grafana/assets/92951193/96633be5-8742-461b-a92e-2d03a2b71f97)
