### ISSUE TITLE
[Feature request] Add mode to WHEN condition of alerting

### ISSUE THREAD

**Issue by brianfeucht** [grafana/grafana#6964]
I have a data series I'm trying to build alerting around.  The query I'm using is either on or off and I want to be alerted when over a time period it is in a broken state the majority of the time.  None of the existing calculation methods are letting me setup this alert as expected.  I believe that using mode vs median or average would give me what I need.

![image](https://cloud.githubusercontent.com/assets/1063445/21203348/e337ffac-c206-11e6-88b4-e93d597eff1a.png)

**Comment by bergquist** [comment]
@brianfeucht What version of grafana are you using? Do you get data points when its off or just null values?

**Comment by brianfeucht** [comment]
We are on 4.0.2 and the data source is Graphite, I'm using a query like ```aliasByNode(Production.MonitoringService.Missing.*, 3)``` 

Since I created this ticket I have removed the null data.  I now have this setup to be either 0 if in a good state or an int greater than 0 if in a bad state.  Making this change has allowed median to work for me.  I'm closing this for now.
