### ISSUE TITLE
Dashboards: Template variable doesn't escape double-dash properly in ClickHouse query

### ISSUE THREAD

**Issue by vlovich** [grafana/grafana#69651]
### 
# What went wrong?

**What happened**:
I have a query like this:

**What did you expect to happen**:
I expect the expansion to properly escape the `--` embeded within a string so that the query isn't corrupted.

### 
# How do we reproduce it?

**Step 1**:

Create a multi-value template variable `$columnFilter` where one of the values generated is `TOQN0tx--kWK`.

**Step 2**:

Create a ClickHouse query like this:

```
SELECT $timeSeries as t,
  if(column IN (${columnFilter}), column, 'long tail') as columns,
  count() / $interval as rps
FROM $table
GROUP BY t, columns
ORDER BY t
```

**Step 3**:

Open the generated query and notice the `--` is interpreted as a comment instead of part of a string literal & the panel fails to load.

``` 
SELECT     (intDiv(toUInt32(timeslot), 10) * 10) * 1000 as t,     if(column IN ('TOQN0tx     count() / 10 AS rps FROM open.table     WHERE timeslot BETWEEN toDateTime(1686040904) AND toDateTime(1686062446)     AND GROUP BY t, columns ORDER BY t
```

### 
# What Grafana version are you using?

v9.4.9

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Are Datasources involved?

ClickHouse

**Comment by mdvictor** [comment]
Hey @vlovich. Thanks for opening this issue, we will further investigate.

@grafana/partner-datasources can you also have a look over this issue, since it seems to be clickhouse related? Thank you!
