### ISSUE TITLE
Search: navigation bar search very slow for non-admins

### ISSUE THREAD

**Issue by csquire** [grafana/grafana#69659]
### 
# What went wrong?

**What happened**:
After upgrading our grafana instance from 9.4 to 9.5.2, users have started reporting slowness when searching via the new nav bar. Searches are typically taking 12 seconds or longer for both authenticated and non-authenticated users. For authenticated administrators, nav bar searches perform very quickly though.

Searching from the dashboard search page seems fine though. We don't currently have slow query logs enabled on our database.

The below issue seems similar, but our database appears to have the index that was added as the resolution.
https://github.com/grafana/grafana/issues/25688 

Our system has about:
- 4200 dashoards
- 650 users

**What did you expect to happen**:
I expect searches using the nav bar to be performant when non-admins search.

### 
# How do we reproduce it?

**Step 1**:

- Click in the top nav bar and start typing a search while unauthenticated

**Step 2**:

- Wait for the search request to complete and update the results

![grafana_query](https://github.com/grafana/grafana/assets/677724/b5c55f13-7226-4e60-ae2d-022937a5fd09)

### 
# What Grafana version are you using?

v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's Browser?

Chrome, Firefox and Edge all act the same

### Is this a Regression?

None

**Comment by torkelo** [comment]
@csquire do you have any feature toggles enabled? for example panelTitleSearch?

**Comment by xmm1989218** [comment]
any progress？we also meet same problem.

**Comment by aishyandapalli** [comment]
We have the same problem too. Any progress?

**Comment by kalleep** [comment]
What database are you using for grafana? Based on benchmarks the query is performing bad on mysql 5.7 but has no problem on on either postgres 12+ , mysql 8 or sqlite. 

Benchmarks is running with around 80k dashboards and 500k permissions. We are not sure we will do any fixes to mysql 5.7 due to it being EOL soon.

If you are using any other database could you please provide that you are using?

**Comment by xmm1989218** [comment]
> What database are you using for grafana? Based on benchmarks the query is performing bad on mysql 5.7 but has no problem on on either postgres 12+ , mysql 8 or sqlite.
> 
> Benchmarks is running with around 80k dashboards and 500k permissions. We are not sure we will do any fixes to mysql 5.7 due to it being EOL soon.
> 
> If you are using any other database could you please provide that you are using?

mariadb10.1

**Comment by aishyandapalli** [comment]
We are facing the same issue with MySQL v8

**Comment by aishyandapalli** [comment]
Apologies, we are also on MySQL v5.7

**Comment by knuzhdin** [comment]
I have the same issue on 10.1.5 grafana. Backend is MySQLv8 (8.0.31-23 Percona Server)

**Comment by sjoeboo** [comment]
Also seeing this. Just promoted a user who was seeing 20s latency on searches to admin and they immediatly went down to what I as admin see of sub 100ms latencies.
