### ISSUE TITLE
[Bug] Grafana loads multiple json file with the same name but only displays the first one found

### ISSUE THREAD

**Issue by ajorgensen** [grafana/grafana#6965]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
This [commit](https://github.com/grafana/grafana/commit/19552450fa9706f5ed94de40c33a2fc2c7e7bb0e) at the time of writing
- What datasource are you using?
None
- What OS are you running grafana on?
OSx
- What did you do?
The json loading task will start at the root of the path given and recursively load json files all the way down the tree. If you create two json files with the same name, for example
`/tmp/dashboards/foo.json` and `/tmp/dashboards/bar/foo.json`, it will load both of in the UI but you can only click on the first one that was loaded. Clicked on the second will load the first one again. 

![image](https://cloud.githubusercontent.com/assets/509779/21203355/1635448c-c220-11e6-95f1-47f87b18c55d.png)

This is definitely an edge case but this can be a bit confusing because there is no indication why clicking on the "Other foo.json" link in this example does not do anything.

- What was the expected result?
I'm not sure what the best way to handle this is, there should at least be a warning in the UI that a duplicate index entry was found or you could index based on the relative path from the root so it would be unique.

- What happened instead?

`Other foo.json` is clickable but loads the dashboard for `first foo.json` instead because the url is not able to differentiate the keys for them.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by daniellee** [comment]
I think this is referring to the old `dashboards.json` config setting that you could use to load dashboards from file. That has been replaced with the provisioning feature since Grafana v5.x.

Closing this issue but let us know if it is still an issue.
