### ISSUE TITLE
Setup: configure HTTPS > can't self-generate certificate

### ISSUE THREAD

**Issue by toralf** [grafana/grafana#69664]
### 
# What went wrong?

https://grafana.com/docs/grafana/latest/setup-grafana/set-up-https/

this command does not works, because  grafana.csr has no path:
```
openssl x509 -req -days 365 -in grafana.csr -signkey /etc/grafana/grafana.key -out /etc/grafana/grafana.crt
Can't open grafana.csr for reading, No such file or directory
```

### 
# How do we reproduce it?

run the command 

### 
# What Grafana version are you using?

asdf

### 
### Is the bug inside a Dashboard Panel?

asfd

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @toralf 

could you specify the Grafana version,  Grafana platform (How are you running/deploying Grafana? ) user OS with version

thank you

**Comment by toralf** [comment]
> hi @toralf
> 
> could you specify the Grafana version, Grafana platform (How are you running/deploying Grafana? ) user OS with version
> 
> thank you

The bug is in the doc - see the link. It must be
```
-in /etc/grafana/grafana.csr
```

Despite that I do use 9.5.1 under a stable hardened Gentoo Linux.

**Comment by tonypowa** [comment]
Thank you @toralf 

Dear AuthNZ team, please reroute if needed

**Comment by mgyongyosi** [comment]
@grafana/backend-platform Could you please take a look at this?
