### ISSUE TITLE
Prometheus: inconsistent quantile (le) format

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#69660]
### 
# What went wrong?

**What happened**:

Quantile formats are inconsistent between legend format and the new prometheus raw view. E.g. the chart legend shows `le="24.999999999999996"` but the list view has `le="25.0"`.
![image](https://github.com/grafana/grafana/assets/109082771/9752fb89-9d36-45ae-8437-5bb37bc4f300).

Additionally larger values will display in exponential notation while the raw view does not
<img width="354" alt="image" src="https://github.com/grafana/grafana/assets/109082771/e5b9f04c-7aff-4d35-83e5-b30723d14735">

We should also check other numeric label values as well.

  - 

**What did you expect to happen**:
Formats should be consistent.
  - 

Thanks to @bboreham for the heads up

### 
# How do we reproduce it?

View series that has quantile (le) label in explorer, note differences between panel legend and raw view.

### 
# What Grafana version are you using?

v10

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by bboreham** [comment]
Can I just note that I found it very surprising that the one getting modified is the one labelled "raw".
To me "raw" means unmodified.
