### ISSUE TITLE
Text Panel: HTML Details tag doesn't show expander

### ISSUE THREAD

**Issue by avidhanju** [grafana/grafana#69661]
### 
# What went wrong?

**What happened**:

  - HTML Details tag is not displayed property by the Text panel visualization. You can see the expander is not displayed:
  
![image](https://github.com/grafana/grafana/assets/10158691/9ef6fbde-000f-4454-b392-96c952b25b71)

**What did you expect to happen**:

  - Here is the same html displayed in [W3Schools example](https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_details):
![image](https://github.com/grafana/grafana/assets/10158691/7198cb55-8509-4a59-b95d-f54e53025be7)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add a text panel to a dashboard.

**Step 2**:

- Select the HTML  and paste the follow HTML
```
<details>
     <summary>Epcot Center</summary>
     <p>Epcot is a theme park at Walt Disney World Resort featuring exciting attractions, international pavilions, award-winning 
      fireworks and seasonal special events.</p>
</details>
```
**Step 3**:

- Click Apply.

### 
# What Grafana version are you using?

v9.4.12

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's OS?

Windows

### User's Browser?

Microsoft Edge for Business Version 114.0.1823.37 (Official build) (64-bit)

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @avidhanju 


From my end the description toggles (as expected) upon clicking the text .

Make sure you have selected the HTML mode 
![image](https://github.com/grafana/grafana/assets/45235678/d232731d-5584-44cf-ac69-a5da145f5e09)


![text_pan_html](https://github.com/grafana/grafana/assets/45235678/6b613e8e-811e-4564-93f0-81a928c31a20)

**Comment by avidhanju** [comment]
@tonypowa the description expansion works fine but the horizontal caret symbol (>) doesn't show right next to the summary text. I tried to inspect the element directly and if I remove the `display: block` css property, it seems to show up.

https://github.com/grafana/grafana/assets/10158691/e706394e-713c-49d5-8827-a61fb46707af

**Comment by tonypowa** [comment]
thanks for the video. I see it now!

moving the issue forward to the appropriate squad

**Comment by joshhunt** [comment]
Thanks for the report!

**Comment by avidhanju** [comment]
@joshhunt is this going to be backported to 9.x?

**Comment by avidhanju** [comment]
@tonypowa @joshhunt can we backport this fix to 9.x?

**Comment by tonypowa** [comment]
@avidhanju 
afaik, the release teams no longer accept backports for 9.5 or older unless its a critical security fix or other critical bug. If you go to the linked[ pull request](https://github.com/grafana/grafana/pull/70133), you will see it's backported to v10.0.x
