### ISSUE TITLE
Unable to select Templated Variable on Metric Type when querying Label Values

### ISSUE THREAD

**Issue by ChristopherWriight** [grafana/grafana#69672]
### 
# What went wrong?

**What happened**:

  - Using the GCM datasource, Query Variable I'm unable to select a Templated Variable for 'Metric Type' when 'Query Type' > 'Label Values' is selected.

https://github.com/grafana/grafana/assets/37227781/63a869a4-813c-4699-abf8-bc2e77d9fb88

**What did you expect to happen**:

  - To be able to use a Template Variable as the 'Metric Type'

### 
# How do we reproduce it?

**Step 1**:

- Create a Query Variable Type and another Variable as your template variable.

**Step 2**:

- Select the GCM datasource.

**Step 3**:

- Select 'Label Values' and attempt to add your template variable to 'Metric Type'

### 
# What Grafana version are you using?

v9.5.1

### 
### Grafana Platform?

Kubernetes

### User's OS?

13.3.1 (a)

### User's Browser?

Google Chrome Version 113.0.5672.126 (Official Build) (arm64)

### Is this a Regression?

No

**Comment by ChristopherWriight** [comment]
Similar issue when using query type - Label Keys. Service and Metric Type fields do not retain a selected variable.

**Comment by aangelisc** [comment]
Hi all, apologies for the delay, I've created a PR to resolve this issue 😊
