### ISSUE TITLE
[Bug] init.d script grafana-server doesn't work on some systems

### ISSUE THREAD

**Issue by hotsnow** [grafana/grafana#6968]
The new version of grafana init.d script doesn't work since the change: https://github.com/grafana/grafana/pull/4926

Because it uses a new function "action" to run the command. Unfortunately, this function doesn't support by all of the Linux systems. So it won't start/stop/status on some of the systems. the follow message show that why:

Debian and Ubuntu have /lib/lsb/init-functions ; SuSE has /etc/rc.status ; none of them are compatible with the others. In fact, some distributions don't use /etc/init.d at all, or use it in an incompatible way (Slackware and Arch occur to me off the top of my head; there are others)

I checked Debian 7 and SLE 11,12, both of them don't contain action function. So the init script won't work on Debian 7 and SLE 11, 12

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by colinbclark** [comment]
Is there a workaround for this?  I'm getting the same error using RHEL 7.3.

**Comment by colinbclark** [comment]
As a follow up, I removed and re-installed the rpm and was able to get up and running.

**Comment by torkelo** [comment]
this seems to have been uncommon issue as this is the only report on this, so closing

**Comment by AlexandrosV** [comment]
I've been trying to start Grafana on Suse Linux Enterprise Server 11.4. Seems like the init.d scrip is not compatible. While debugging the script:

**+ ulimit -n 10000
+ cd /usr/share/grafana
+ action 'Starting Grafana Server: ...' su -s /bin/sh -c 'nohup /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins >> /dev/null 3>&1 &' grafana
+ return=127
+ '[' 127 -eq 0 ']'
+ exit 127**

Furthermore when testing **action** and **status** commands:

   **If 'action' is not a typo you can run the following command to lookup the package that contains the binary: command-not-found action
-bash: action: command not found**

Any piece of advise ?
