### ISSUE TITLE
Table Visualization: Merge transform not working if one of the query return empty response

### ISSUE THREAD

**Issue by lgirault** [grafana/grafana#69701]
### 
# What went wrong?

A pannel with a table visualization has multiple queries. One of them return an empty result 
![image](https://github.com/grafana/grafana/assets/1417074/adde0160-7609-4a21-ba75-4772f2efedd0)

**What happened**:

  - merge does not work

**What did you expect to happen**:

  - drop the empty query result and merge the others

### 
# How do we reproduce it?

A closed issue describing the exact same problem already exists (https://github.com/grafana/grafana/issues/26890). It looks like a regression 

### 
# What Grafana version are you using?

v9.5.3 (916d9793aa)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

archlinux

### User's Browser?

tested on Firefox 113.0.2 (64-bit) and Chromium Version 114.0.5735.90 (Official Build)

### Is this a Regression?

None

### Are Datasources involved?

Postgres and Prometheus

**Comment by mdvictor** [comment]
Hey @lgirault. Thanks for opening this issue! We've taken a look over this but it would really help if you could send us an example dataset to reproduce this.

I've looked over this [issue](https://github.com/grafana/grafana/issues/26890) you mentioned, but it seems a bit of a different scenario from my understanding. I tested that fix and it still works as expected.

**Comment by lgirault** [comment]
Thanks for looking into it. I'll post you a request/payload example as soon as possible

**Comment by lgirault** [comment]
Hey @mdvictor . It took a while, but here is an example dataset: 
https://github.com/lgirault/grafana-issue-69701

**Comment by mdvictor** [comment]
Hey @lgirault. Thank you for taking the time to give me an example. I tested and managed to reproduce, but I don't believe this is a bug. The transformation expects the data to have common fields across all frames to merge properly. I think what should be done here is add better error messages and docs. I've opened an [issue](https://github.com/grafana/grafana/issues/77782) for this that we will tackle later on.

In the meantime, you can disable the query that returns the empty frame and the transformation should work properly.

I will close this in favor of the message/docs issue linked above. Thank you once again for opening this issue and let me know if there is anything else I can help with!

**Comment by liujin1993** [comment]
@mdvictor I encounter this problem too. I think this is a bug. Null queries shouldn't be considered. In my scene, I want to show node's total cpu 、total memory and total gpu in one row. But some node doesn't hava gpu. It results in merge's failure.

**Comment by tekert** [comment]
Same, this was supposed to be fixed in https://github.com/grafana/grafana/pull/27362 , how do we merge if only one query is NaN? the completed response makes no logical sense, this is outside of our control.
