### ISSUE TITLE
[Build] Published packages consumes to much space

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6970]
We currently package and publish grafana on every successful build which consumes to much space on S3. We need to decrease the amount of packages published to S3 some how.

One suggestion would be to start doing night builds that publishes the packages.

**Comment by torkelo** [comment]
removed the "nightly build" trigger as it causing a million builds per day and I have to do manual cleanup that finally caused an issue like this https://github.com/grafana/grafana/issues/7147 . 

Maybe for release packages we should move them to another s3 folder before release? I have been wanting to do that but it adds another step to the already complicated release process

**Comment by bergquist** [comment]
Closing this in favor of #7404
