### ISSUE TITLE
[Bug] PhantomJS dashboard rendering does not hide the side menus

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6971]
I am using phantomjs to render a grafana dashboard and it works perfectly except it renders the row menus too. :(

I tried rendering http://play.grafana.org/dashboard/db/advanced-layout using PhantomJS

![google](https://cloud.githubusercontent.com/assets/1019609/21219492/e1d9de24-c269-11e6-8162-25ad1df58ef0.jpg)

If we can make these side menus go away, it would be great! :)

If any of you can give me some guidance on how to fix it, I can work on a PR.

**Comment by torkelo** [comment]
Grafana does not support rendering dashboards only single panels

**Comment by torkelo** [comment]
I know the render endpoint can be used for it but that feature has never been officially supported / made available in UI

**Comment by utkarshcmu** [comment]
Thanks for the /render api, thats what I was looking for :)
