### ISSUE TITLE
Variables: Show description instead of definition in variables table

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#69721]
While working on https://github.com/grafana/grafana/pull/69703 I noticed, that in template variables table, we display `Name` and `Definition` of variable as columns. `Definition` is basically just a [query string or query.query string if query is an object](https://github.com/grafana/grafana/blob/main/public/app/features/variables/query/QueryVariableEditor.tsx#LL95C3-L95C16). 

However, if data source doesn't have `query` or `query.query` in `string` format,  then definition is basically empty. And quite a lot of data sources that were migrated to the new templating have query as an object that does not have query property  - e.g. Loki, Cloudwatch,  Cloud Monitoring, Azure Monitor. So I am wondering, if `Definition` still make sense here, or if we should replace if with `Description`, that would be useful for all variables, not just the ones that have string format. 

<img width="1612" alt="image" src="https://github.com/grafana/grafana/assets/30407135/561fc7a6-fe6e-4262-a774-749cca37a17c">

**Comment by torkelo** [comment]
@ivanahuckova this does not really fix it, just leaves it blank after editing (edited the level variable) 

![image](https://github.com/grafana/grafana/assets/10999/602dba3b-8cdd-47b7-aadc-43bcffc7c326)

**Comment by ivanahuckova** [comment]
Or another idea [onQueryChange](https://github.com/grafana/grafana/blob/main/public/app/features/variables/query/QueryVariableEditor.tsx#LL95C3-L95C16) could accept `definition` as second optional param?

**Comment by torkelo** [comment]
@ivanahuckova ah, sorry. yes was meant for the PR :)

**Comment by torkelo** [comment]
@ivanahuckova yea, I agree. It's probably best to show description here instead of definition
