### ISSUE TITLE
[Inconsistency] Row menus are not hidden for bottom rows when Side menu is Pinned

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6972]
To see the UI inconsistency/bug Go to http://play.grafana.org/dashboard/db/graph-styles, pin the side menu and scroll down. You will see that row menus are not hidden for the rows which are at bottom but are hidden for the top rows.

**Comment by torkelo** [comment]
fixed in master (as there are no row menus anymore)
