### ISSUE TITLE
[Feature request] Allow Time range change on single query in panel

### ISSUE THREAD

**Issue by pascalre** [grafana/grafana#6973]
Please include this information:
- What Grafana version are you using? Grafana v4.0.2 (commit: v4.0.2)
- What datasource are you using? Elasticsearch 
- What OS are you running grafana on? Linux

Currently, when you set the "Override relative time"-field, it changes the time range for all queries in the panel. Having the possibility to set the time shift according to single queries would be a nice feature.

Example scenario: Users would have the opportunity to correlate a metric (e. g. count of logins) in a current time range with previous days in a single panel.

**Comment by torkelo** [comment]
timeshift is currently handled by the time series query & backend. For example Graphite has a timeshift function. Think it is the only TSDB that supports timeshifts.

Other time series databases that do not support it will have to implement it or wait until Grafana Meta Queries is implemented, that might open up support for time shift and other transformations that can be applied to any data source query.

https://github.com/grafana/grafana/issues/3677
