### ISSUE TITLE
Select component doesn't update state when receiving a new value from outside the component

### ISSUE THREAD

**Issue by ckbedwell** [grafana/grafana#69732]
### 
# What went wrong?

When using the `<Select />` component from `@grafana/ui`, if you provide it a new value from outside of the component the state in the input field doesn't update.

### 
# How do we reproduce it?

I have created a Stackblitz to demonstrate the error: https://stackblitz.com/edit/react-ts-rl82sr?file=App.tsx

In this example there are two Selects: one to select a person and one to select a team to assign them to. The team you can assign them to is dependent on your first selection. You are supposed to access them in order however if you have selected values for both selects but then go back to the first one and change the person, the state remains displayed in the second select even though we have cleared it in the onChange handler.

This screenshot demonstrates it displaying an impossible state.
<img width="858" alt="image" src="https://github.com/grafana/grafana/assets/6906380/8a129978-4340-4ac6-8dbe-4174240ac686">

### 
# What Grafana version are you using?

grafana/ui@9.5.3

**Comment by angel1254mc** [comment]
This is more of a workaround but you could use `null` instead of `undefined` and that should update the component on the next render :).

```
...
        onChange={({ value }) => {
          setPerson(value);
          setTeam(null); // This should successfully reset the dependent select on the next re-render :)
        }}
...
```

**Comment by Clarity-89** [comment]
This is the intended behavior of the Select component, I've documented it in the Storybook based on this discussion.
