### ISSUE TITLE
[Feature request]: set generic oauth login button name 

### ISSUE THREAD

**Issue by Starefossen** [grafana/grafana#6974]
It would be nice to be able to set the name for the generic oauth login button, currently it looks like this:

<img width="447" alt="screen shot 2016-12-15 at 12 23 35" src="https://cloud.githubusercontent.com/assets/968267/21222349/ab57a630-c2c1-11e6-98ce-2028667118af.png">

I have tried to set the `GF_AUTH_GENERIC_OAUTH_NAME` environment variable but it appears not to have any effect for this button.

**Comment by torkelo** [comment]
thanks for reporting this! fixed
