### ISSUE TITLE
OpenApi3 Specs are unavailable due to CORS (Grafana Cloud)

### ISSUE THREAD

**Issue by paulwer** [grafana/grafana#69757]
### 
# What went wrong?

**What happened**:

  - CORS Errors

**What did you expect to happen**:

  - having a suiteable cors setup, to access these pages

### 
# How do we reproduce it?

Open play.grafana.com/swagger-ui OR play.grafana.com/openapi3

### 
# What Grafana version are you using?

play / cloud

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by papagian** [comment]
I can reproduce it also in my own cloud instance
