### ISSUE TITLE
[Feature request] Support customized subjects

### ISSUE THREAD

**Issue by stefanosala** [grafana/grafana#6975]
Hi there,
we're using the new shiny Alerting feature and it's working very well.

We'd like to integrate it with [StatusPage.io](http://help.statuspage.io/knowledge_base/topics/getting-started-with-email-automation), but it requires the alert emails to have these words in the subject: `DOWN` / `UP` instead of `Alerting` / `OK`.

I'd like to have the possibility to change Alerting and OK, so if you could help me pointing where to look in the code, I'll be happy to help.

Cheers!
Stefano

**Comment by torkelo** [comment]
I do not think we can customize the terminology (UP/DOWN) vs Alerting/OK, but maybe we can have some status page integration or this can be handled via custom webhook (that you then implemented and you write app that sends email to status page)

**Comment by stefanosala** [comment]
Hi @torkelo, thanks for your reply.
I did something you suggested at the end and released it open source: https://github.com/getconversio/grafana-statuspage

cheers
Stefano

**Comment by torkelo** [comment]
nice
