### ISSUE TITLE
Plugins: Incorrectly dropping the original check health error

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#69765]
When returning an error from `CheckHealth` the original error (coming from a backend plugin) is dropped/lost which makes it hard for users/operators to understand what the original error is. The code in question:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/plugins/manager/client/client.go#L199

The API error handling:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/api/plugins.go#L504-L506

Currently, the Grafana log message becomes the following, notice the error:
"logger=context orgId=1 t=2023-05-25T21:50:53.22+0200 lvl=eror msg="Plugin health check failed" error="failed to check plugin health: health check failed""

Should be noted that the original error would be logged if the following logic evaluates to true:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/pkg/plugins/backendplugin/instrumentation/instrumentation.go#L84
Which is based on the following setting:
https://github.com/grafana/grafana/blob/e0ce6c3a9496750c4e012e903bb1bc8b81586c49/conf/defaults.ini#L1401

**Comment by kousikmitra** [comment]
Hi @marefr , is the idea here to wrap actual error into `ErrHealthCheckFailed` and return?

**Comment by marefr** [comment]
@kousikmitra yeah, basically

**Comment by kousikmitra** [comment]
raised a PR
