### ISSUE TITLE
Bug Y Axis Auto Scale Fails on Negative Metrics

### ISSUE THREAD

**Issue by hixxy89** [grafana/grafana#6980]
- What Grafana version are you using? 
V4.02
- What datasource are you using? 
Graphite
- What OS are you running grafana on? 
Debian Jessie
- What did you do? 
Configured a graph to use a metric that is negative for the duration of the timescale displayed.  Y axis scale left as auto.
- What was the expected result? 
To display the graph
- What happened instead? 
Y axis failed see attached screenshot - Duct Pressure

![grafana bug](https://cloud.githubusercontent.com/assets/24304311/21233629/c20b64a4-c2e7-11e6-9ab7-1a61b6766417.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/21254610/b5c4c7f6-c366-11e6-8fad-ae066f1d769d.png)


I am unable to replicate this. Please very that the Duct Pressure graph queries acutually return any data (open chrome dev tools network tab)

**Comment by hixxy89** [comment]
Hi Torkelo,

I've been able to replicate on http://play.grafana.org/dashboard/db/grafana-trend.

The issue occurs when the entire metric is negative and Y-axis min and max are both set to auto.

I modified the user count graph to the following:
- Removed existing metrics
- Y axis min of auto
- Y axis max of auto
- Added constant line of -25

![screencapture-play-grafana-org-dashboard-db-grafana-trend-1481883801509](https://cloud.githubusercontent.com/assets/24304311/21259704/87030d88-c37a-11e6-89ac-a2e0d98d6770.png)

![screencapture-play-grafana-org-dashboard-db-grafana-trend-1481883768457](https://cloud.githubusercontent.com/assets/24304311/21259710/8b98dc9c-c37a-11e6-8828-b1e4433c7d14.png)

Yet when I change the constant line to be 25 it works:

![screencapture-play-grafana-org-dashboard-db-grafana-trend-1481883860650 1](https://cloud.githubusercontent.com/assets/24304311/21259734/a799a700-c37a-11e6-8b97-2f9d6bdb3a1c.png)

**Comment by hixxy89** [comment]
@torkelo I haven't examined the code yet but it appears as if the min and max are set the wrong way around, for example; min = -10 and max = -50. 

Perhaps an absolute value is used. 

This worked fine in earlier versions so I'll be able to compare.

**Comment by torkelo** [comment]
it's strange auto y works fine with any series I try (just using scale(-1) to negate it), but I do get the error with the constantLine. maybe something with constantLine and it only returns two points with same value so min/max is the same

**Comment by torkelo** [comment]
found and fixes issue, only happens when data min == max , then the auto y min/max tries to expand the window a bit (by 25%) this needed a Math.abs() to account for negative max

**Comment by hixxy89** [comment]
Great! Thank you
