### ISSUE TITLE
Query History: Update datasource filter when datasource changes

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#69806]
In the query history pane, if in a non mixed scenario and the current selected datasource filter matches the current datasource, change the datasource filter if the selected datasource changes. 

We should assume in this scenario the user would want to keep their query history filter in sync with their selected datasource.

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
