### ISSUE TITLE
Dashboards: Legend value of MQL query broke after upgrading  to grafana 9.5.3

### ISSUE THREAD

**Issue by mitrshashwat** [grafana/grafana#69828]
### 
# What went wrong?

**What happened**:

  - There is no Aliasby option in grafana-9.5.3 for google cloud monitoring MQL queries

**What did you expect to happen**:

  - Should be able to Aliasby in grafana 9.5.3
  
  Old version Grafana-9.2.0
  
![image](https://github.com/grafana/grafana/assets/38601045/cb7c2e9b-fc40-48a4-9e24-37dd30d049ef)

  New version Grafana- 9.5.3
  
  - 
![image](https://github.com/grafana/grafana/assets/38601045/355af71c-8f67-4013-a16c-8c5965f4537c)

  

### 
# How do we reproduce it?

**Step 1**:

- Install grafana 9.5.3 via recommended method in centos 7 

**Step 2**:

- Create a new dashboard, then create a new visualisation with Google cloud monitoring as a data source

**Step 3**:

- In builder we'll be able to see Aliasby, but when we use dropdown to change query method to MQL there is no aliasby option

### 
# What Grafana version are you using?

v9.5.3

### 
### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 20.04

### User's Browser?

Mozilla Firefox 113.0(64-bit)

### Is this a Regression?

Yes

### Are Datasources involved?

Google Cloud Monitoring

**Comment by asimpson** [comment]
It does indeed look like this was dropped accidentally. Let me double check with the team and we'll get it sorted.

**Comment by asimpson** [comment]
- Fixed in #73116
