### ISSUE TITLE
gauge: value mapping color setting not applied

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#69824]
### 
# What went wrong?

**What happened**:

  - When using value mapping on gauge the Display Text does work but not the color

**What did you expect to happen**:

  - Grafana to respect the color for the value mapping

![image](https://github.com/grafana/grafana/assets/900951/18d5cd98-7d99-481f-846e-deb64c61b256)

### 
# How do we reproduce it?

1. create a gauge visualization
2. use this data set
```
metric,temp
21-,56.4
22-,33.9
23-,37.2
24-,55.5
```
3. Create value mapping and colors as follows
![image](https://github.com/grafana/grafana/assets/900951/030d6eca-b1d7-4c30-af07-97179c330143)

### 
# What Grafana version are you using?

9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A downloaded binary

### User's OS?

Windows

### User's Browser?

Chrome

### Is this a Regression?

None

### Are Datasources involved?

Infinity

### Anything else to add?

No

**Comment by gelicia** [comment]
@yosiasz - I think you did find a bug, but it isn't the one you're wanting to be fixed. With the data you have, you have a field name coming from the metric data that looks like `21-`, `22-`, and so on, and your values are the other set of numbers like 56.4, 33.9, etc. Value mapping should only affect the value, not the field name. 

Take a look at the docs here https://grafana.com/docs/grafana/latest/panels-visualizations/configure-value-mappings/
In that example, the field name is `A-series`, `A-series1` and the value is some number in the range of 50-65. The series names, the lowest text, is unaffected by the value mapping, but the value has the text and color change as described in the mapping.

So in your example, the text should have never been changed at all. The value mapping should only work against your temperature values. I tried reproing what you have on the latest version of Grafana and couldn't so maybe that was fixed.

Grafana has a couple things that will let you do what you want, if I'm understanding correctly. From field overrides, you can select the field you want to override and set the color there. The "Organize fields by name" transformation will let you rename your fields. 

<img width="1136" alt="Screenshot 2024-02-07 at 4 23 18 PM" src="https://github.com/grafana/grafana/assets/1533128/df1958d3-a094-4289-9c37-818273cfa547">

Does that help?

**Comment by yosiasz** [comment]
let me try that, sorry just saw this

**Comment by yosiasz** [comment]
@gelicia so let's say I have 100 metrics, that approach does not scale to manually enter all 100 (exaggerating of course) but does not feel dynamic.

**Comment by yosiasz** [comment]
Agreed. I would say by the data source providing hez color coded and grafana using that to color per metric. Will create another thread. Thanks
