### ISSUE TITLE
[Feature request] Slack do not get webdav grafana png

### ISSUE THREAD

**Issue by clhlc** [grafana/grafana#6984]
I upgrade grafana to 4.0.2 and fixed grafana send png to webdav， but slackbot do not get webdav png，

nginx return 401， Help me how to fix it。 thx

**Comment by clhlc** [comment]
webdav log：

172.17.42.1 - username [16/Dec/2016:03:34:52 +0000] "PUT /1MG5CT9zyiedEDkV63uU.png HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
54.89.92.4 - - [16/Dec/2016:03:34:53 +0000] "GET /1MG5CT9zyiedEDkV63uU.png HTTP/1.1" 401 194 "https://slack.com" "Slackbot 1.0 (+https://api.slack.com/robots)"

**Comment by bergquist** [comment]
Is the webdav server accessable from the internet? with the same url that grafana posted to?

**Comment by clhlc** [comment]
@bergquist  yes, the webdav server port is open, i used username and passwd can login my webdav, grafana also can, you can see the first log , grafana PUT the png to webdav "200".

 So i guess slackbot can not use username and passwd access th webdav ,so is 401.

**Comment by torkelo** [comment]
slack needs the url to be public & without auth

**Comment by clhlc** [comment]
@torkelo  so, th auth in webdav is not work？ why in grafana.ini  and grafana 4.0.2 fixed?

**Comment by torkelo** [comment]
@clhlc auth is for upload (PUT), but to GET the image there can be no auth, otherwise slack will not be able to access it

**Comment by clhlc** [comment]
@torkelo @bergquist  thx , nginx.conf fixed it!
