### ISSUE TITLE
Dashboards: azure monitor logs don't follow specified time range in the dashboard. 

### ISSUE THREAD

**Issue by tasdmg** [grafana/grafana#69853]
### 
# What went wrong?

**What happened**:

  - I have run this query against azure monitor choosing the service: logs(not metrics) and no matter how I set the time range the results are all the same.
  - This is a query against IOT hub.
// Devices with most throttling errors 
// Identify devices that made the most requests resulting in throttling errors. 
// To create an alert for this query, click '+ New alert rule'
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.DEVICES" and ResourceType == "IOTHUBS"
| where ResultType == "429001"
| extend DeviceId = tostring(parse_json(properties_s).deviceId)
| summarize count() by Category
| order by count_ desc

![9 5 0_bad](https://github.com/grafana/grafana/assets/136085045/677c76cb-e5c2-4eef-90c0-28ae63e61146)
![9 5 0_bad2](https://github.com/grafana/grafana/assets/136085045/8cefdb62-880e-4c5a-882d-7c08896f8318)

**What did you expect to happen**:

  - I expected the result to vary based on the time range I have set. 
![9 4 12_good](https://github.com/grafana/grafana/assets/136085045/c8826483-bd81-49c9-89e4-b7ebba9a6927)
![9 4 12_good2](https://github.com/grafana/grafana/assets/136085045/3739e4f6-4566-4cba-b994-b96f0b0b5409)

 
  - This works in grafana 9.4.12 but from 9.5.0 in all version its broken.

### 
# How do we reproduce it?

- Open Grafana and create a dashboard. 
- use Azure monitor as data source and chose service: logs
- use the query or your own to get data from IOT hub. 
- Change the timerange for a diffrent time and watch how many results are there. 

### 
# What Grafana version are you using?

9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's Browser?

Edge latest

### Is this a Regression?

Yes

### Are Datasources involved?

Azure monitor

**Comment by asimpson** [comment]
:wave: Hi! I believe a fix for this will be in 9.5 eventually but I'm not sure when. The [docs have been updated](https://github.com/grafana/grafana/pull/69987) to reflect how this will be handled going forward.

**Comment by aangelisc** [comment]
#71278 has clarified this behaviour and will be released in the next 10.x version so I'm going to close this issue 😊
