### ISSUE TITLE
Alert state history failed 

### ISSUE THREAD

**Issue by Abhinav9720** [grafana/grafana#69851]
Dear all,

We are facing the alert state history issue in Grafana alert so,
Pls support to sort this issue if anyone knows how to resolve.

Thanks

![Screenshot_2023-06-09-17-54-11-600-edit_com microsoft teams](https://github.com/grafana/grafana/assets/110819922/9e42dd48-83d0-4b39-b634-8811370c9c26)

**Comment by tonypowa** [comment]
closing issue
if more help is needed, please provide more info and reopen 
:wave:
