### ISSUE TITLE
[Feat Req]: Graph Panel & Options for staircase line visualization

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#6986]
Please include this information:
- What Grafana version are you using?
4.0.1
- What datasource are you using?
InfluxDB 1.1
- What OS are you running grafana on?
ubuntu 16.04 x64 server
- What did you do?
Real time energy data visualization
- What was the expected result?
I would like that for the staircase line visualization, the curve goes in the other side (see the image). My request comes from the fact that I use energy data and a value at a timestamp is the mean of the values between this timestamp and the timestamp-1.
- What happened instead?
The currently visualization considers that the value at a timestamp is the mean of the values between this timestamp and the timestamp+1.

![dash1](https://cloud.githubusercontent.com/assets/20662503/21255978/b82dfc52-c36f-11e6-9d07-5a2342c69934.png)

**Comment by gwuillou** [comment]
Furthermore, I would like the same for the case of the bar visualization (as in the image). Perhaps it exists a way to do  that but I didn't find.

Thank you for the great job that you are doing,

![dash2](https://cloud.githubusercontent.com/assets/20662503/21256150/e8b5d8e4-c370-11e6-97dc-714a6d08fa98.png)

**Comment by torkelo** [comment]
I think your best bet is to timeshift data as your write them or query them, not sure InfluxDB has such a feature.

**Comment by gwuillou** [comment]
Hello, 

No because, the data are on the correct timestamp. It is just a question of visualization. If I shift the data then it will be wrong. 

For example if I have at 8:00 the value 100, in my case it is representing the mean value between 7:46 and 8:00. It is a little bit strange I now but I can not change this interpretation sorry! 

Thank you

**Comment by torkelo** [comment]
ok, I see. If you can't change the data or timeshift the data in the query then your out of options. I would not expect Grafana to change staircase & bar render mode any time soon unless this issue gets lots of votes :)

**Comment by joakimberglund** [comment]
Might be off here..

But did you try with a shorter group by time, like 10s, and use fill(linear) instead of default fill(null)?

**Comment by gwuillou** [comment]
Hello, 

I tried without success. 

Thank you for help

**Comment by ioanszilagyi** [comment]
Hello, any news on this?

I think that, when using staircase there should be another option to chose how these extra points are added. Given two points (v0, timestamp-1) and (v1, timestamp) there are (at least) two options to add the necessary extra points for building the staircase :
1. adding (v0, timestamp) or;
2. adding (v1, timestamp-1).

I would add that, most of the time, the value at _timestamp_ is an average over the (timestamp-1 => timestamp) duration, and therefore the option 2 should be better suited.

If this issue don't get lots of votes/attention... could someone point me to the code responsible for this ?

Thank you,
Ioan

![screen shot 2017-05-24 at 15 45 32](https://cloud.githubusercontent.com/assets/1081098/26406459/a10f8ecc-4098-11e7-9234-0203a1b2043a.png)

**Comment by Sineos** [comment]
#7941

**Comment by d3banjan** [comment]
the issue of [filling in missing values](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html)  or [interpolating](http://pandas.pydata.org/pandas-docs/version/0.16.2/generated/pandas.DataFrame.interpolate.html) from pandas is relevant here. 

The two kinds of filling @ioanszilagyi mentioned are referred to as forward and backward fill respectively.

**Comment by alexism7hz** [comment]
> 
> 
> Hello, any news on this?
> 
> I think that, when using staircase there should be another option to chose how these extra points are added. Given two points (v0, timestamp-1) and (v1, timestamp) there are (at least) two options to add the necessary extra points for building the staircase :
> 
>     1. adding (v0, timestamp) or;
> 
>     2. adding (v1, timestamp-1).
> 
> 
> I would add that, most of the time, the value at _timestamp_ is an average over the (timestamp-1 => timestamp) duration, and therefore the option 2 should be better suited.
> 
> If this issue doesn't get lots of votes/attention... could someone point me to the code responsible for this ?
> 
> Thank you,
> Ioan
> 
> ![screen shot 2017-05-24 at 15 45 32](https://cloud.githubusercontent.com/assets/1081098/26406459/a10f8ecc-4098-11e7-9234-0203a1b2043a.png)

Hi, 

I'd like to make a contribution that might help as a little trick, because this feature is not released yet. Also as an other way to explain what @ioanszilagyi wrote.

I'm computing 5-minute average values of a sensor giving data every second. Considering the following data points:
- Between 10:45AM and 10:50AM, `averageValue = 106.9` (**so the 10:45 to 10:50 period should have the value 106.9**)
- Between 10:50AM and 10:55AM, `averageValue = 105.7` (so the 10:50 to 10:55 period should have the value 105.7)
- Between 10:55AM and 11:00AM, `averageValue = 105.8` (so the 10:55 to 11:00 period should have the value 105.8)

In my database, I have in every row the timestamp of the beginning (`timestamp_begin`) and the end (`timestamp_end`) of the 5 minutes period, with the corresponding `averageValue`.

I ran two queries:
- In yellow: I query the data by selecting `timestamp_begin`
- In green: I query the data by selecting `timestamp_end`

You can see in the picture that the yellow one (selecting the timestamp of the beginning of the period) displays correctly what I want, whereas the green one (selecting the timestamp of the end of the period) displays the wrong plotting.

Please let me know if that makes sense! 

![image](https://user-images.githubusercontent.com/45498062/73092264-41f29200-3eaa-11ea-9085-9b58e7d7e21b.png)

**Comment by stefaanv** [comment]
Same issue there.
Calculating average power consumption from S0 counters.  The average is calculated at the end of each period but Grafana is plotting them as if they were calculated in the beginning (which is obviously not possible).
Seems like an obvious option to visualise the stair step before of after the value.  I would expect before to occur as often as after

**Comment by leeoniya** [comment]
this will be available in the new graph panel. see https://github.com/grafana/grafana/pull/29593.

**Comment by martin3000** [comment]
So there is a new option to switch between forward/left/before staircase and backward/right/after staircase?
Where is it?

**Comment by leeoniya** [comment]
Step before and Step after:

https://grafana.com/docs/grafana/next/visualizations/time-series/graph-time-series-as-lines/

**Comment by martin3000** [comment]
Oh thank you. You have to switch from Visualization->Graph to Visualization->Time series and then switch from the "Panel" tab to the "Field" tab.
