### ISSUE TITLE
Dashboards: Switching orgs from anywhere except the standard homepage throws an error

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/grafana#69916]
### 
# What went wrong?

**What happened**:
  - Upgraded to v.9.5.2 and v.9.5.3, when performing a switch of org a TypeError is thrown.

**What did you expect to happen**:
- Switch org without an error

**Firefox**
[firefox.txt](https://github.com/grafana/grafana/files/11723713/firefox.txt)

**Chrome**
[chrome.txt](https://github.com/grafana/grafana/files/11723711/chrome.txt)

### 
# How do we reproduce it?

Firefox:
Perform an org switch from anything but the standard homepage (any other dashboards, alerting menu)

Chrome:
Perform an org switch from any dashboard that isn't the grafana standard dashboard (switching from a non-dashboard page does not fail)

### 
# What Grafana version are you using?

v9.5.3

### 
### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

MacOS Ventura

### User's Browser?

Firefox 114.0 - Chrome 114.0.5736.106

### Is this a Regression?

Yes

**Comment by michael-sawczuk** [comment]
Hi @tonypowa, cheers for your reply.

I'm not seeing any errors in the log, here is the log snippet at the time of switching.

[grafana_log.txt](https://github.com/grafana/grafana/files/11733784/grafana_log.txt)

**Comment by Jguer** [comment]
Closing as outdated, feel free to comment if this is still ongoing in the latest Grafana version
