### ISSUE TITLE
[Bug] 4.1 pre1 All hover tooltips are displaying instead of only active one

### ISSUE THREAD

**Issue by Petyas** [grafana/grafana#6991]
I didn't found same Bug, that's why i'm creating new one.

Please include this information:
- Grafana v4.1.0-pre1 (commit: df3adbc)
- ElasticSearch/Zabbix
- CentOs
- Mouse move over the graphs
- Display only active hover tooltip
- It's displaying all tooltips from all graphs

![image](https://cloud.githubusercontent.com/assets/1658590/21257828/6430ba94-c37a-11e6-9a39-96785d968add.png)

**Comment by Petyas** [comment]
It's not problem actually. It's missing default value in settings of dashboard. After i've seted, it's ok.

![image](https://cloud.githubusercontent.com/assets/1658590/21258245/6213ab16-c37c-11e6-94db-bf0747261a34.png)

**Comment by torkelo** [comment]
yea, but the default should be set to Default on new dashboards, so it's a bug, will fix soon  :)

**Comment by Petyas** [comment]
Another comment. The default value isn't possible to set. Only two values is possible set with dashboard Shared crosshair or Shared tooltip.

**Comment by torkelo** [comment]
yea, that is the bug that this issue is about

**Comment by torkelo** [comment]
fixed in master now
