### ISSUE TITLE
Glue: Add correlations scenario to test datasource

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#69929]
Add a "Correlations" scenario to the TestData datasource

This scenario should have a dropdown with the following visualization items
- Logs
- Service Map
- Trace View
- Table data
- Timeseries data

There is a lot of ambiguity here on specifics of what this data should contain, but the end goal for this scenario is to create a set of data that can demonstrate visualizations with highly linkable data between them. This will be used for demonstrating and testing correlations. Data will all be hardcoded and should be similar to data we encounter in standard logs/traces/metrics setups.

An overall view of the relationship in the data in this scenario:
![Untitled (17)](https://github.com/grafana/grafana/assets/1533128/81725dc9-36ca-4218-a2fa-0de287608aac)

---
#### Logs
This will pull up the log view. There should hardcoded logs that have the following data in them (not every log line needs every piece of data, feel free to separate into more frontend/backend logs that would reflect actual logs).

- traceIDs
- usernames
- containerIDs
- serviceNames

There should be 4 text fields, one for each of the data items listed above, that allow you to filter the hardcoded logs with typed in data. 

#### Service map
This will pull up the service map/node graph view. The service map data should contain the following, with relationships however seems plausible
- serviceNames
- containerIDs

There should be 2 text fields that let you filter the data above.

#### Trace View
This will pull up the trace view. There should be hardcoded trace/span data that contain the following data
- traceIDs
- containerIDs

You should be able to filter data by traceID and/or containerID.

#### Table Data
This will show some hardcoded, generic user data. This will need to contain usernames, and you should be able to filter based on username. 

#### Timeseries data
This will show some hardcoded, generic metrics-esque data. It will need to contain a containerID, and you should be able to filter based on containerID

**Comment by ifrost** [comment]
@gelicia Do you think it's still worth doing?

**Comment by gelicia** [comment]
@ifrost I think if it was something that would be more useful, we would have gotten more feedback from solutions engineers. Closing, feel free to comment if you would like to see this done.
