### ISSUE TITLE
[Bug] Too many slash in POST _msearch (Elasticsearch)

### ISSUE THREAD

**Issue by mNantern** [grafana/grafana#6993]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
grafana-3.1.1-1470047149.x86_64

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
CentOS Linux release 7.1.1503 (Core)

- What did you do?
I want to change an ES Query in Templating:

![grafana_templating](https://cloud.githubusercontent.com/assets/1544226/21260755/cbebe534-c387-11e6-8344-faaa9a25cefc.png)

- What was the expected result?
See the result of the query

- What happened instead?
An HTTP 301 send back by the proxy because the input url has 2 slashes:

```
curl -v 'https://..../grafana/api/datasources/proxy/1//_msearch?search_type=count' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Content-Type: application/json;charset=utf-8' -H 'Authorization: Basic *****'
```

It's the exact same issue as in #3485 . I open a new issue only because [a comment](https://github.com/grafana/grafana/issues/3485#issuecomment-163845240) says that it should be fixed in 2.6.

**Comment by torkelo** [comment]
looks like the fix is merged and included in 4.0
https://github.com/grafana/grafana/commit/010dbddf5933fdd2034e259ad8d49692203d2d9b
