### ISSUE TITLE
AZURE Monitor datasource: does not load my subscriptions, and does not find log analytics workspace

### ISSUE THREAD

**Issue by tarekhamouda** [grafana/grafana#69940]
### 
# What went wrong?

**What happened**:
i deployed grafana from public docker hub to azure web app and added azure monitor as a datasource but it fails to load the subscription and it does'nt find the log analytics workspace.
i use app registration and i asigned Reader role at subscription level resource group and so on.
when i click of save& test
i get the following:

1.    Successfully connected to azure monitor endpoint
2.    No log analytics workspace found
3.   error connecting to azure Resource Graph endpoint: {"error"{"code":"BadReques","message" ...............timestamp and corelationId "code": subscriptionContainsInvalidGuids:

  - 

**What did you expect to happen**:

  - Connect to azure log analytics and be able to query metrics

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and go to connection / your connection and add azure data source

**Step 2**:

- add your tenant id , client id (aftre registering it creating SP) secret.

**Step 3**:
Click on Save & Test 

### 
# What Grafana version are you using?

tried several versions and getting same issue currently using v9.5.3(916d9793aa)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

None

**Comment by zuchka** [comment]
> using v9.5.3(https://github.com/grafana/grafana/commit/916d9793aa81c2990640b55a15dee0db6b525e41)

can you please try v10 as well?

**Comment by PierreGode** [comment]
I have this issue now. 
![Image](https://github.com/user-attachments/assets/e4b2e260-5e31-417e-91dc-3ee16541656b)
Grafana v11.2.0 (2a88694fd3)
