### ISSUE TITLE
[Feature Request] Add option to not make 'All' the default selected value when include All option is enabled

### ISSUE THREAD

**Issue by rolandkool** [grafana/grafana#6995]
- What Grafana version are you using?
3.1

- What datasource are you using?
Graphite

- What OS are you running grafana on?
RHEL6

- What did you do?
Enabled the include All option for a template variable. The option is included in the list and is always selected as the default.
It would be nice to allow making the next value in the list the default in stead of 'All' when it is enabled.

**Comment by reecewebb** [comment]
+1 for this. Zabbix is our datasource with its hundred's of thousands of items, having the default "All" causes a major slow down when loading a dashboard.

**Comment by hugohaggmark** [comment]
This seems like a great feature request to me.
