### ISSUE TITLE
cue and generated golang structs are insufficient to define a dashboard variable with multi-value query and custom allValue

### ISSUE THREAD

**Issue by ellisda** [grafana/grafana#69952]
The dashboard's `VariableModel` golang struct ([pkg/kinds/dashboard/dashboard_spec_gen.go#L915](https://github.com/grafana/grafana/blob/819041c7324cc194dd3be3ccadc0f970fc555438/pkg/kinds/dashboard/dashboard_spec_gen.go#L915)) and it's [kinds/dashboard/dashboard_kind.cue#L191](https://github.com/grafana/grafana/blob/266751b96d59ff1ecafb8d38502d54e32a1579ff/kinds/dashboard/dashboard_kind.cue#L191) seem to be missing some options. We're unable to use [grafana/grok](https://github.com/grafana/grok) types to generate our dashboards with the variables, so trying to report on our issue here, so that grok can benefit from improved structs when they re-enable golang struct generation in the future.

The SLO squad at Grafana is interested in using grok golang structs to programmatically generate our grafana dashboards, but the `VariableModel` objects don't appear to be feature complete for our use case. We're using prometheus `label_values` query variables to populate some multi-value dropdowns at the top of our dashboard. Specifically the "id" field is causing us issues, and there does not appear to be any way to set the custom `allValue`.

Issues with VariableModel:

1. not sure what to populate for the "id" field, but our attempts cause the dashboard variables to load in an error state (see image below)
2. `includeAll` and `allValue` are missing from the golang structs
    1.  we want to set `"allValue" : ".+"
4. `sort` is missing from the golang structs, though a `#VariableSort` appears in [dashboard_kind.cue#L251](https://github.com/grafana/grafana/blob/266751b96d59ff1ecafb8d38502d54e32a1579ff/kinds/dashboard/dashboard_kind.cue#L251)
5. `query *interface{}` is very loosely typed in the golang structs - with Grafana v 9.5.3, I can look at existing dashboards and then use a `map[string]any` like the one below, but it's a point of confusion.

I can populate the `query *interface` with a json object like this:
```
var query interface{} = map[string]any{
    "query": "label_values(metric_name,cluster)",
    "refId": "PrometheusVariableQueryEditor-VariableQuery",
}
```

Figure (dashboard variables showing yellow alert icon when we provide an "id" value in the VariableModel)
![image](https://github.com/grafana/grafana/assets/5599664/ae4872f3-3baa-4674-8263-90c4c060e105)

**Comment by ivanortegaalba** [comment]
I have this PR where I implemented all the variable PRs. It is pending to get some love to solve conflicts.
https://github.com/grafana/grafana/pull/62142

I found a small problem there when creating the Variable types. When adding 3 inheritance levels, and I run make get-cue it gets stuck. I reported it here https://raintank-corp.slack.com/archives/C03BH67DS2J/p1685013465550279. 

For example, doing something like `BaseVariable -> VariableWithOptions -> MultiValueVariable -> QueryVariable`  it gets stuck.
I could try, copy-pasting without inheritance to generate those types and try to get that PR merged, but I don't have much capacity 😢  I'll try my best to unblock you with this.

**Comment by ellisda** [comment]
Thanks for the quick response, @ivanortegaalba (and sorry for not seeing it right away). We're not blocked, we have a workaround with hand-edited golang struct types ;-), so no worries there. I'm happy to hear you've got work in progress on this, though. Thank you!
