### ISSUE TITLE
Docs: Edit content of plugin examples for Grafana style

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#69968]
Looking ahead: 
edit plugin examples repo: editing READMEs and code comments, then evaluate for moving/blending in with rest of docs. https://github.com/grafana/grafana-plugin-examples

**Comment by ojuschugh1** [comment]
Hi, Is this issue still open, I am interested in working on it.

Thanks and Regards

**Comment by josmperez** [comment]
@ojuschugh1 - thanks so much for reaching out. I'm still in the planning/eval stage of this issue. I'd welcome your thoughts to help inform the planning, and would be happy to include you in the process.

**Comment by ojuschugh1** [comment]
Hi thanks,i am glad to work with you :)

**Comment by josmperez** [comment]
Moving as a duplicate.
