### ISSUE TITLE
[Bug] Alerting error: Influxdb returned statuscode invalid status code: 400 Bad Request

### ISSUE THREAD

**Issue by ScubaDrew** [grafana/grafana#6997]
Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influx
- What OS are you running grafana on? ubuntu
- What did you do? setup a standard graph and attempted to set an alert
- What was the expected result? 
- What happened instead? Influxdb returned statuscode invalid status code: 400 Bad Request

If it relates to *alerting*
- An image of the test execution data fully expanded.

![image](https://cloud.githubusercontent.com/assets/18055237/21270394/4e99158c-c36b-11e6-96d3-82481a51a9bd.png)

![image](https://cloud.githubusercontent.com/assets/18055237/21270425/7f6db802-c36b-11e6-8fa3-a70bfc404eba.png)

**Comment by bergquist** [comment]
Could you please share the panel json?

If click the panel title to open the mini menu you can navigate to the hamburger menu and select `panel json`

**Comment by ScubaDrew** [comment]
`{
  "aliasColors": {},
  "bars": false,
  "datasource": "telegraf",
  "editable": true,
  "error": false,
  "fill": 1,
  "id": 2,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 6,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "auto"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "jolokia",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Kafka_MessagesInPerSec_OneMinuteRate"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Messages/min",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "none",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}`

**Comment by 7lives83** [comment]
Same errors here. 400 bad request.

**Comment by bergquist** [comment]
@ScubaDrew the json you pasted doesnt contain the alert rule. You need to save the dashboard first and the copy the json.

@7lives83 Please provide the panel json with the failing alert.

**Comment by ScubaDrew** [comment]
@bergquist 

{
  "aliasColors": {},
  "bars": false,
  "datasource": "telegraf",
  "editable": true,
  "error": false,
  "fill": 1,
  "id": 2,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 6,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "auto"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "jolokia",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Kafka_MessagesInPerSec_OneMinuteRate"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [
    {
      "value": 50,
      "op": "gt",
      "fill": true,
      "line": true,
      "colorMode": "critical"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Messages/min",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "none",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "alert": {
    "conditions": [
      {
        "type": "query",
        "query": {
          "params": [
            "A",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "type": "avg",
          "params": []
        },
        "evaluator": {
          "type": "gt",
          "params": [
            50
          ]
        },
        "operator": {
          "type": "and"
        }
      }
    ],
    "noDataState": "no_data",
    "executionErrorState": "alerting",
    "frequency": "60s",
    "handler": 1,
    "notifications": [],
    "name": "Messages/min alert"
  }
}

**Comment by bergquist** [comment]
I found the bug...

The alerting backend didn't handle group by time('auto') correctly. The quick fix for this is to change `time(auto)' to `time($interval)'

I'll commit a patch to handle time(auto) correctly but I'm not sure when we will release it.

**Comment by bergquist** [comment]
The commit is now available in master so it should be available shortly at grafana.org/builds

or in 4.0.3 if we release it before 4.1.0

**Comment by bergquist** [comment]
Thank you for reporting this! :)

**Comment by ScubaDrew** [comment]
Thanks Carl! You guys rock.

Drew

**Comment by marefr** [comment]
@mbrostami template variables like $inter you're using are not supported in alerting, see #6557
