### ISSUE TITLE
Explore: Explore split-view remembers old result

### ISSUE THREAD

**Issue by the-it** [grafana/grafana#69982]
### 
# What went wrong?

**What happened**:

  - I had a split view for query A (left) and query B (right) both with shown graphs
  - I closed the split view screen with the button over query A
  - I explored a bit more with different queries
  - I opened split-view again
  - on the right I see now the duplicated query from the left side, BUT the graph from the right side, before I closed the split-view in step 2
  - 
![Screenshot from 2023-06-13 09-28-26](https://github.com/grafana/grafana/assets/2553019/b5f86a17-ca46-4d1c-bfc5-61df535e4254)

**What did you expect to happen**:

  - see the same graph like the left query or no graph at all
,
![Screenshot from 2023-06-13 09-28-26](https://github.com/grafana/grafana/assets/2553019/b5f86a17-ca46-4d1c-bfc5-61df535e4254)

### 
# How do we reproduce it?

**Step 1**:

- see What happened, that should work as reproduction

### 
# What Grafana version are you using?

Grafana v10.1.0-56792pre (387cf7ec60)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Ubuntu 23-4

### User's Browser?

Chromium Version 114.0.5735.106 (Official Build) snap (64-bit)

### Is this a Regression?

None

**Comment by ifrost** [comment]
We couldn't reproduce the issue. We've investigated what could potentially be causing this but we didn't find anything obvious. Please re-open when it happens again. Ideally it'd be great to have a stable reproducible scenario.
