### ISSUE TITLE
[Request] 3.1.1 RPM not available to download

### ISSUE THREAD

**Issue by rajatjindal83** [grafana/grafana#6999]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
3.1.0
- What datasource are you using?
Elastic Search
- What OS are you running grafana on?
Cent OS
- What did you do?
Trying to upgrade to 3.1.1
- What was the expected result?
Was expecting 3.1.1 RPM to be available for download
- What happened instead?
3.1.1 RPM is not available to download

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by bergquist** [comment]
grafana.org should be updated. 

You can find the package at https://packagecloud.io/grafana/stable for now.

**Comment by torkelo** [comment]
@bergquist but he is right, the 3.1.1 is gone from grafana.org/download

**Comment by torkelo** [comment]
restored the download page for 3.1.1 from github history, was accidently written over when we released 4.0.0, 

http://grafana.org/download/3_1_1/
