### ISSUE TITLE
empty evalMatches in webhook alert

### ISSUE THREAD

**Issue by h0x00i** [grafana/grafana#7001]
Hi, I want to send the alert system to my site, I using webhook method for send alerting system but when use this method can not see value or tags in _'evalMatches'_.

my log system:
 {u'evalMatches': [], u'title': u'[Alerting] Voltage alert', u'ruleId': 2, u'state': u'alerting', u'ruleUrl': u'http://localhost:3000/dashboard/db/power?fullscreen&edit&tab=alert&panelId=1', u'ruleName': u'Voltage alert'}

sorry for bad English :) 

Please include this information:
- What Grafana version are you using? 4.0.2
- What datasource are you using? influx
- What OS are you running grafana on? raspbian jessie lite 

If it relates to *alerting*
- An image of the test execution data fully expanded.

![xxxxx](https://cloud.githubusercontent.com/assets/4295831/21293176/d17fde3c-c531-11e6-9288-ac1570aa1574.png)
![111](https://cloud.githubusercontent.com/assets/4295831/21293188/17dae610-c532-11e6-80bf-63465982c021.png)

**Comment by h0x00i** [comment]
I updating garfana to 4.0.2 and my problem is ok :) but when alert in okay webhook JSON evalMatches parameter is empty!!!

when ok alert
![1](https://cloud.githubusercontent.com/assets/4295831/21294455/0a001086-c552-11e6-9c7b-3fd0a502d690.png)
 
when alerting 
![2](https://cloud.githubusercontent.com/assets/4295831/21294460/2f78dd7a-c552-11e6-8e89-fa3e4e59738f.png)

**Comment by torkelo** [comment]
yes, eval matches only contains info on conditions that passed the condition.

**Comment by h0x00i** [comment]
@torkelo I want to eval marches not empty when the state is ok, Is it possible?

**Comment by torkelo** [comment]
not sure, maybe.

**Comment by bergquist** [comment]
If we want to include all series used for the evaluation it should be another property.

**Comment by h0x00i** [comment]
@bergquist I think it could be better to add this feature, because it makes general propose communication between grafana and other services.
Do you think it's possible in future versions there?

**Comment by bluefish6** [comment]
+1 - we're sending alerts via sms and we're only able to get information that will allow us to send:
```
[ALERTING] Alert Name. Incorrect metric: <eval_matches_name>: <eval_matches_value>
```
and
```
[OK] Alert Name. We have no idea what is the current value, because no alerting conditions evaluate to true.
```

It would be great to have either:
- `evalMatches` and `evalNotMatches` (which values are within limits)
- or `evalMatches` and `evalResults` (all values, no matter if they triggered the state change or not)

Any chance of putting this to backlog? :)

**Comment by gogoods** [comment]
+1

**Comment by yh882317** [comment]
Hi, I got empty evalMatches with alerting state
`{'title': '[Alerting] Alarm used penel alert', 'ruleId': 1, 'ruleName': 'Alarm used penel alert', 'state': 'alerting', 'evalMatches': [], 'orgId': 1, 'dashboardId': 21, 'panelId': 6, 'tags': {}, 'ruleUrl': 'http://localhost:3000/d/-oAJhFdnz/cephosd?tab=alert&viewPanel=6&orgId=1', 'message': 'test'}` 
This happens with Grafana 8.2.7 but works well with 7.5.1
