### ISSUE TITLE
[bug] Can't remove a Blank Dashboard 

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [grafana/grafana#7002]
I'm using the Grafana 4.0.2,then, I build a blank dashboard unexpectedly,like this:

![1](https://cloud.githubusercontent.com/assets/18111540/21303327/a5ad7900-c5f8-11e6-8c5d-1dd7e22cc508.png)
![2](https://cloud.githubusercontent.com/assets/18111540/21303341/b7eb0a7e-c5f8-11e6-8168-fa1f90b06f67.png)
so,the question is how can i remove the blank dashboard?
Thanks all

**Comment by Chentongxuedefanhua** [comment]
@torkelo so,how can i remove it?

**Comment by utkarshcmu** [comment]
@Chentongxuedefanhua Do you have access to the database? If yes, please go into the "dashboard" table and delete the row where name is empty.

**Comment by Chentongxuedefanhua** [comment]
@utkarshcmu Oh,i see,thank you~

**Comment by utkarshcmu** [comment]
Please close this issue when you are done resolving. Thanks!
