### ISSUE TITLE
Expressions: Query errors are not properly shown when expressions are used.

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#70026]
### 
# What went wrong?

**What happened**:

  - For any panel that contains more than one query and any number of expressions, if an error gets thrown by any of the queries:;
  1. The entire panel fails
  2. No meaningful error is displayed, only a 500 error is shown to the user.

Here both query A and B work as expected, so does the expression:

![image](https://github.com/grafana/grafana/assets/20448042/dad96f12-4165-4be0-9337-163bcf93fc0b)

As soon as I add a query that contains an error, the entire panel fails with 500 error (failing to surface the proper error for the query):

![image](https://github.com/grafana/grafana/assets/20448042/a1b7e3ab-4f56-4ec2-a70a-1b9928217dfb)

As soon as I remove the expression, the right error is surfaced, and if any queries succeed, their data is shown:

![image](https://github.com/grafana/grafana/assets/20448042/b0a3e029-9e3b-4f92-a43d-4e863918cd09)

**What did you expect to happen**:

  - Two scenarios are expected here:
  1. For the expression query to not eat up the error thrown by other queries and properly display it (like in image 2)
  2. For successful queries to still run even if there are failing queries when expressions are added.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a panel with multiple queries in it (any datasource may be used for repro purposes)
- Make sure that you add an expression

**Step 2**:

- Force an error in any of the queries that are not being referenced in the expression

**Step 3**:

- Wait for the panel to break with 500 error

### 
# What Grafana version are you using?

9.4.10

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows

### User's Browser?

Edge

### Is this a Regression?

None

### Are Datasources involved?

Any datasource

**Comment by zuchka** [comment]
you should also check out using Grafana's built-in transformations which are client-side instead of server-side. In my opinion they are much more robust, better developed and less buggy than expressions, which are server-side. That's why the verbose error message is not going through

https://grafana.com/docs/grafana/latest/panels/transform-data/

**Comment by avidhanju** [comment]
@zuchka it is not very easy (or probably not possible at all) to do math operations on time series with transforms.

I understand that the server-side code might be more buggy but that is why we have opened this issue to fix those bugs.

Were you able to look at why the underlying error is being eaten up by the expressions code? And how to let the queries run that are not part of the expression?

**Comment by zuchka** [comment]
@avidhanju from the looks of your dashboard, I might check out this blog post about the new alerting UI in the meantime:

https://grafana.com/blog/2023/07/10/how-we-improved-grafanas-alert-state-history-to-provide-better-insights-into-your-alerting-data/?mdm=social&utm_source=li&utm_medium=social

**Comment by avidhanju** [comment]
@zuchka thanks for the info but we are not using expressions in alerts. These are just being used in dashboard panels to do math operations.

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#math

**Comment by zuchka** [comment]
sorry @avidhanju, looks like that alerting dashboard belongs to @jcolladokuri  😄

**Comment by avidhanju** [comment]
@zuchka I work with @jcolladokuri. We are using expressions in dashboard panels for math operations on time series data. We are not using expressions in alerts.
