### ISSUE TITLE
Provisioning: SecureJSONData in datasource does not null empty fields on update

### ISSUE THREAD

**Issue by dreamlibrarian** [grafana/grafana#70035]
### 
# What went wrong?

**What happened**:

  - As part of rollout of grafana enterprise, we updated the default datasource to use basicAuth instead of TLS Certificate auth. This involved removing the keys tlsClientCert and tlsClientKey from the secureJSONData field of the datasource in our datasources.yaml.
  - When the TLS certificate expired, the datasource broke, requiring us to delete and recreate it to recover service.

**What did you expect to happen**:

  - We expected the database representation of the datasource to have the tlsClientCert and tlsClientKey fields deleted when they were deleted from the config file.

### 
# How do we reproduce it?

**Step 1**:

- Create a datasource using datasources.yaml. set a key in the secureJsonData field. 

**Step 2**:

- Note in the database that the field is now set - eg `SELECT secure_json_data FROM "data_source" WHERE name='mimir';` will show the key exists.

**Step 3**:

- Delete the key from secureJsonData in datasources.yaml and apply the config file. Note that the secureJsonData continues to contain the affected field.

### 
# What Grafana version are you using?

v9.5.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

### Anything else to add?

We can work around by deleting the datasource and allowing recreation for now.

**Comment by zuchka** [comment]
> datasources.yaml

please provide more details here about how you are provisioning.  Note: provisioning Grafana resources without using some configuration management tool like Terraform is not best practice

**Comment by dreamlibrarian** [comment]
We're providing datasources in the provisioning/datasources dir per http://docs.grafana.org/administration/provisioning/#datasources, managed as part of the helm chart we're deploying in a file called datasources.yaml. Apologies for the lack of clarity!

**Comment by JoaoSilvaGrafana** [comment]
I managed to reproduce this locally with the `devenv` datasources. If you remove something from `jsonData` it gets correctly deleted from the database, but not if you remove it from `secureJsonData`. Not sure how to debug what's happening though, @grafana/backend-platform might be able to help more.

**Comment by papagian** [comment]
I was able to reproduce it as well by removing the `password` field from the `gdev-mysql` datasource. 

I forward it to @grafana/plugins-platform-backend who [own](https://github.com/grafana/grafana/blob/5f63d1a5cb9bd16a8af701ab3017fda33eef19ab/.github/CODEOWNERS#L652) it.
