### ISSUE TITLE
[Feature Request] Log scale for Singlestat Gauges

### ISSUE THREAD

**Issue by XedMada** [grafana/grafana#7003]
Logarithmic scales are currently available in the graph panel. Applying them to the gauge in a singlestat panel would be particularly useful for throughputs such as disk and network.

**Comment by dozzman** [comment]
I'm also interested in having this feature. We have a service uptime gauge which's main measurement is 'number of nines' e.g. 99.999% vs 99.99%. This is a logarithmic scale so we cannot appropriately display this on a gauge (yet).

**Comment by bklebel** [comment]
I am interested in this too - some physical parameters, like vacuum pressure, go across a few orders of magnitude, where the smallest numbers are the most important in the end. in the current way, these are the ones least observable.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
