### ISSUE TITLE
Dashboard: Cannot query for data that is outside the dashboard time range

### ISSUE THREAD

**Issue by yves-chan** [grafana/grafana#70034]
### 
# What went wrong?

**What happened**:

  - I have a Azure Monitor log analytics query that queries for some data that is outside of the dashboard time range. Instead, all the data returned is within the dashboard time range

**What did you expect to happen**:

  - I should be able to see the data outside the dashboard time range if it's specified in query
  
  

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add a panel for Azure Monitor datasource, configure the service to Logs

**Step 2**:

- Select a Logs Analytics Workspace resource.

**Step 3**:

- On a table with data, query for `TimeGenerated > {a time outside the time range of the dashboard}`

example:
```
// cannot see data past $__timeFrom()
let lookTimeBefore = $__timeFrom() + -6h;

Usage
| where TimeGenerated > lookTimeBefore
| summarize count() by TimeGenerated
```

**Step 4**:
- Observe data that is returned is always within the dashboard time range

![TimeRangeBug](https://github.com/grafana/grafana/assets/7664931/11ba6923-60ce-4b36-8fde-b6c4c36d756c)

### 
# What Grafana version are you using?

v9.4.12

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's Browser?

Edge

### Is this a Regression?

None

### Are Datasources involved?

Azure Monitor

### Anything else to add?

Unsure if this was a regression, but maybe it is?

**Comment by zuchka** [comment]
have you tried hiding the timepicker in the dashboard options?

![CleanShot 2023-06-19 at 09 43 01@2x](https://github.com/grafana/grafana/assets/37156449/15e9ee14-97c9-4279-996d-f30f71662e52)

**Comment by yves-chan** [comment]
hi @zuchka , I'm not sure what hidding the time picker on the dashboard option does here? In the example above, I'm using `$__timeFrom` global variable. The data that is always returned is from $__timeFrom to $__timeTo. I was wondering if it was possible or if there was some workaround to get data outside of that range. In the example, gif, I have a look back time of '5h' but wondering if this can be dynamic as well.
