### ISSUE TITLE
[Bug] Annotations not showing in graph with future time range

### ISSUE THREAD

**Issue by t-pfaff** [grafana/grafana#7004]
I'm using Grafana 4.0.2 with InfluxDB.

In my graphs with positive time series override (e.g., +7d) to show future values, annotations referring to the same future time range are not shown.

I use the following InfluxDB query: `SELECT "event" FROM measurement_name`
(explicitly avoiding `WHERE $timeFilter`)

**Comment by torkelo** [comment]
not including the $timeFilter seems very dangerous (very easy to hang browser that way). 

Can you show there response from InfluxDB and your annotation config? Does the graph show annotations for "past" time ranges?

**Comment by t-pfaff** [comment]
Yes, the graph shows annotations for "past" time ranges.
OK, I added the `WHERE $timeFilter` again (doesn't change anything, anyway).

**Comment by torkelo** [comment]
ok, and influxdb response does include future events?

**Comment by t-pfaff** [comment]
Yes, I guess so.  A numeric column in the events measurement is shown in a table:
![grafik](https://cloud.githubusercontent.com/assets/7511568/21315966/dbf6e0a4-c5fe-11e6-88dd-54eb51319f10.png)

**Comment by torkelo** [comment]
The image you pasted does not show the annotation query, nor the response from InfluxDB. You can see the query being sent to influx and the raw response from influxdb by openening chrome dev tools network tab, click on the request that corresponds to the annotation query and check the response from influxdb.

**Comment by t-pfaff** [comment]
Sorry, didn't know to look there for the query and response.
Query is: `SELECT "event" FROM muenster WHERE time > 1477954800s and time < 1480546800s`
Still looking for the response...

**Comment by torkelo** [comment]
and your annotation config? (field mappings)

**Comment by t-pfaff** [comment]
Response is:
`{"results":[{"series":[{"name":"muenster","columns":["time","event"],"values":[[1479254400000,"Die 3 Nikoläuse (Jubiläumsweihnachtsrevue, Gassi)"]]}]}]}`

Without `WHERE $timeFilter`: `SELECT "event" from muenster`
And response:
{"results":[{"series":[{"name":"muenster","columns":["time","event"],"values":[[1479254400000,"Die 3 Nikoläuse (Jubiläumsweihnachtsrevue, Gassi)"]]}]}]}

So the event on Dec 24 is not returned.

Do you mean column mappings? Or is field mappings something different?
Column mappings are empty

**Comment by torkelo** [comment]
Yea, meant field mappings. Ok, they are empty, not sure annotations will work then unless the defaults are working for you. 

Well if your query is not returning the events you want then Grafana cannot show them.

**Comment by t-pfaff** [comment]
Ha, works now with: `SELECT * FROM muenster WHERE time < now() + 30d`
