### ISSUE TITLE
Alerting: Inappropriate status code for alerting

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#70048]
### 
# What went wrong?

For following paths we see logs from Grafana:
for path : /api/v1/provisioning/folder/
error: 
![image](https://github.com/grafana/grafana/assets/36128312/c15dabc3-5f8a-4ee9-b748-304706254d5f)
for path: /api/v1/provisioning/alert-rules
![image](https://github.com/grafana/grafana/assets/36128312/0074bafd-5d68-46ca-9542-982b2523867e)
Both cases return http code 500

These are triggered by user behavior, setting code to 500 server error is inappropriate.

### 
# How do we reproduce it?

Using the message and path stated above and the server will return 500.

### 
# What Grafana version are you using?

9.4.12

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by shantanualsi** [comment]
@MingjieZhuEmily Can you post the exact curls that you are trying for the problematic requests? The mentioned path `/api/v1/provisioning/folder/` is not present in the source code. If I understand it correctly, it should return a 404. 

I've made a fix on the second API - [POST] `/api/v1/provisioning/alert-rules` in a draft PR for now

A complete curl request of both APIs would be really helpful for testing

**Comment by MingjieZhuEmily** [comment]
According to the log I see, the first curl is : PUT /api/v1/provisioning/folder/uhucqRlVz/rule-groups/slack

**Comment by MingjieZhuEmily** [comment]
Hi, we are still seeing similar issues about alert rule returning inappropriate 500 code. Yesterday we see the following error
![MicrosoftTeams-image](https://github.com/grafana/grafana/assets/36128312/20880ab0-6d69-4b2e-a196-2c1ffe2eeca2)
And the path about folder can be found in your doc https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#parameters-16
![image](https://github.com/grafana/grafana/assets/36128312/0582ce79-a548-4754-92b5-720280d2ab87)
Given that there are multiple inappropriate 500 error about alerting, especially about conflicting rules. Is that possible for you to fix them altogether in one shot?

**Comment by timlevett** [comment]
@yuri-tceretian any update on this one?

**Comment by yuri-tceretian** [comment]
according to the PR https://github.com/grafana/grafana/pull/76396, This should be fixed in the latest patch of 10.2.
