### ISSUE TITLE
[Feature request] Bearer Token auth for web interface

### ISSUE THREAD

**Issue by vpetersson** [grafana/grafana#7005]
We're looking at ways to add support for Grafana in [Screenly](https://github.com/wireload/screenly-ose/) as an easy way to show Grafana dashboards on the wall using just a Raspberry Pi.

It is already possible to do this if Grafana is configured to use Basic Auth. However, in many (most?) situations, this is not the case.

The API already supports both Bearer Token and Basic Auth, which is great. However, it would be great if Token access could be used to authenticate (and bypass) the regular web view as well. That way, the user would not have to switch the entire system to Basic Auth.

**Comment by torkelo** [comment]
you mean you want to use a login token in the url you load grafana with?

**Comment by vpetersson** [comment]
Either in the URL or as an HTTP header.

**Comment by vpetersson** [comment]
@torkelo If we were to contribute this code, would it be accepted upstream?

**Comment by torkelo** [comment]
maybe not sure, depends on how much code / code complexity / code tests, how many else are interested. But it sounds like a good feature to have.

**Comment by vpetersson** [comment]
Yes, of course -- assuming good code quality / tests.

**Comment by torkelo** [comment]
sound like the same as https://github.com/grafana/grafana/issues/3752

**Comment by nbayramberdiyev** [comment]
Here is my workaround using Grafana's Generic OAuth Authentication and PHP: https://github.com/nbayramberdiyev/grafana-generic-oauth

Hope this will help you.
