### ISSUE TITLE
Plugins: Make grafana CLI flexible in working with command arguments

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#70056]
Grafana CLI is currently limited in how it accepts command arguments

For example, this works:

`grafana cli --debug --pluginsDir=../data/plugins plugins install opennms-helm-app 8.0.2`

But this does not:

`grafana cli --debug plugins install opennms-helm-app 8.0.2 --pluginsDir=../data/plugins`

It would be nice for this arguments to be accepted after the command, or at the very least, warn the user about the fact that it is ignored.

**Comment by mohamedelghaouth** [comment]
Hello, I would like to work on this, can it be assigned to me, please.
