### ISSUE TITLE
[Bug]selecting "All" of template variable now sends the whole list rather than * to Graphite

### ISSUE THREAD

**Issue by kohpinngee** [grafana/grafana#7006]
Grafana version: 4.0.x
Datasource: Graphite
OS: Ubuntu 14:04 in docker container

On version 3.1.1 when selecting "All" for a metrics using templating, say a.$name.c, grafana was sending a.*.c to graphite.
However, with 4.0.x, grafana is sending the whole collection back - example a.{b1,b2,b3,...}.c 
This generates URL string which can get too long for graphite to handle.

**Comment by torkelo** [comment]
You can set custom All value in templating options, so in your case specify `*`

**Comment by kohpinngee** [comment]
This helped. Appreciate your super fast reply.
