### ISSUE TITLE
Canvas: Improve tooltip interactions

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#70079]
The hovering events are interfering with one another when the elements are positioned too close. 

https://github.com/grafana/grafana/assets/88068998/91c817ad-cf2b-433c-882d-1663d861b25e

**Comment by kasaranenikarthik** [comment]
@adela-almasan @Hipska 
I'm using the latest 10.1.5 (not cloud ..local instance) and I'm facing the same issue. It's annoying to see the tooltip disappear as we move our cursor towards it.

**Comment by Hipska** [comment]
https://github.com/grafana/grafana/issues/71021#issuecomment-1776637343
> @kasaranenikarthik a workaround for this is to first click on the element, then the popup stays visible.
> 
> @nmarrs More people are having this issue, I would take another look into this..
