### ISSUE TITLE
i18n: Outstanding navigation strings

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#70082]
Some of the strings in Grafana's navigation are not marked up for translation:

- Connections
- Performance testing
- Reporting (Enterprise)
- Items under IRM (Alerting, OnCall, Incidents, Machine Learning, SLO)
- Items under Observability (Kubernetes, Application, Profiles, Frontend, Synthetics)

We should extract these stings into the string files so that they can be translated thought the GitHub automation with Crowdin.

[Internationalization how-to.](https://github.com/grafana/grafana/blob/813ebf988d354bf23e981e00c9c8458995774c21/contribute/internationalization.md)

**Comment by RoxanaAnamariaTurc** [comment]
@zsofiakm  Hi, can you please let me know how I can add the following on my Grafana dev environment to be able to check and mark up for translation?: 
Performance testing
Reporting (Enterprise)
Items under IRM
Items under Observability
The Connections section is done.

**Comment by amy-super** [comment]
@RoxanaAnamariaTurc I updated the items under IRM and Observability. One thing I'm wondering though - with something like OnCall, that's the actual name of the product. Would we translate it into other languages? I'm sure others have considered this (maybe in Marketing?) so we should be able to follow their lead.

**Comment by zsofiakm** [comment]
I would say all strings need to be marked up. We have a glossary with Translated (they are the agency doing the translations) where we mark which terms do not need translation (since they are product names). OnCall would be one of them.
