### ISSUE TITLE
i18n for managing dashboards

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#70085]
As we've updated the UI for managing folders, there are strings that need to be marked up for translation, and not hard coded. This is required for the GA release.

Folder view:
<img width="1143" alt="image" src="https://github.com/grafana/grafana/assets/97596715/d0b03333-36f6-47c6-bf85-b05981f321d3">

Move/Delete dialogs:
<img width="736" alt="image" src="https://github.com/grafana/grafana/assets/97596715/ef5fb481-2816-41e9-8c84-9a5bbe309b0a">
<img width="489" alt="image" src="https://github.com/grafana/grafana/assets/97596715/2780f5fb-50ab-43c1-9c57-0e6dec1c6e36">
(note: for the word they need to type, I expect it needs to stay "delete"

New folder drawer:
<img width="381" alt="image" src="https://github.com/grafana/grafana/assets/97596715/966ce772-c41f-4c67-aabb-173fd7b35a80">

**Comment by tarunsamanta2k20** [comment]
May i know more about the issue?

**Comment by Bohdanator** [comment]
Hello! I would like to contribute to this project and I am completely new to Grafana. I would be happy to receive some pointers about the frontend architecture, there didn't seem to be much in the `contribute` docs (or I missed it).

**Comment by Bohdanator** [comment]
Should the translation IDs be also created or do they exist? I'm assuming to look for them in `grafana.json`.
