### ISSUE TITLE
Auth: change user info parsing to support the well-known OpenId config

### ISSUE THREAD

**Issue by IevaVasiljeva** [grafana/grafana#70081]
**What is the issue?**:

https://github.com/grafana/grafana/issues/69520 tracks updating the default OAuth config to use [well-known/openid-configuration](https://accounts.google.com/.well-known/openid-configuration). However, https://openidconnect.googleapis.com/v1/userinfo user info endpoint returns data in a slightly different format than https://www.googleapis.com/oauth2/v1/userinfo, which is our current default config. We expect user info to contain an `id` field ([relevant code](https://github.com/grafana/grafana/blob/v10.0.0-preview/pkg/login/social/google_oauth.go#L21)), while the new user info endpoint passes this information in `sub` field.

We should extend our implementation to support both `id` and `sub` fields.

Make sure to also check data returned by the other new endpoints (ie, `verified_email` seems to be `email_verified` for the new API).

We should also try to test Google's user info parsing, to make sure we don't accidentally break it.

**Is there anything else we need to know?**:

Related issue: https://github.com/grafana/grafana/issues/69520
Related PR: https://github.com/grafana/grafana/pull/69521#pullrequestreview-1479715485

**Comment by mgyongyosi** [comment]
It has been implemented by https://github.com/grafana/grafana/pull/70140
