### ISSUE TITLE
[Bug] I can't define more than two conditions on the query

### ISSUE THREAD

**Issue by dragonxtek** [grafana/grafana#7008]
I'm using Grafana 4.0.0-beta1, with Influxdb on Ubuntu 16.04 64 bits.
I trying to add other condition, like WHERE topology = AttMpls AND src = 0 AND dst = 1, but I can't.
When I click on plus icon after the second condition it doesn't load Influxdb variables.

![selection_052](https://cloud.githubusercontent.com/assets/10552658/21328158/5eaf17f2-c611-11e6-8b43-0c9188390af1.png)

How I can add more conditions to my query?

**Comment by torkelo** [comment]
I am unable to replicate this in 4.0.2 or in master. 

Can you check your chrome dev tools for errors or for calls to influxdb? What is the response from influxdb (it will do a tags lookup when you hit plus button)
