### ISSUE TITLE
Port of container used instead of reverse proxy public port

### ISSUE THREAD

**Issue by aMU5Ed** [grafana/grafana#70103]
### 
# What went wrong?

**What happened**:

  - After upgrading from 9.5.3 to 10.0.0 in an unraid docker environment using the grafana/grafana:latest repository the url which worked in 9.5.3 https://externaldomain/grafana/d/.... looks in 10.0.0 https://externaldomain:3000/grafana/d/.... Port 3000 is the container port.
  - Grafana and nginx is configured like in the docs https://grafana.com/tutorials/run-grafana-behind-a-proxy/ with running in a sub-path
  - When forcing version 9.5.3 in the docker container everything runs like expected. No changes in nginx done.

**What did you expect to happen**:

  - Reverse proxy config in 10.0.0 working like in 9.5.3.

### 
# How do we reproduce it?

**Step 1**:

- Configure grafana working a reverse proxy/subpath environment in version 9.5.3

**Step 2**:

- Switch to latest repository

**Step 3**:

- Use the same path like in 9.5.3 in the version 10.0.0

### 
# What Grafana version are you using?

10.0.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

unraid 6.12 rc8

### User's Browser?

Chrome 115

### Is this a Regression?

Yes

### Are Datasources involved?

no

**Comment by zuchka** [comment]
see also: https://github.com/grafana/grafana/issues/70110

**Comment by mgyongyosi** [comment]
https://github.com/grafana/grafana/issues/70110#issuecomment-1597403289

**Comment by aMU5Ed** [comment]
Comment from @torkelo by updating the grafana config fixed it for me.

**Comment by aMU5Ed** [comment]
Comment from @torkelo by updating the grafana config fixed it for me.
