### ISSUE TITLE
Update from 9.5.3 to 10.0.0 breaks the redirect when serving grafana behind reverse proxy (nginx)

### ISSUE THREAD

**Issue by thiagosanches** [grafana/grafana#70110]
### 
# What went wrong?

**What happened**:

After the update to the 10.0.0 version, the redirect it's not working as before (9.5.3). Now, it's considering the configured domain from the `grafana.ini` file and using it as part of the `Location` header.

As we can see on the following screenshot, I did an upgrade to the 10.0.0 version.

![image](https://github.com/grafana/grafana/assets/5191469/fb1493e0-e155-4e50-927e-88495c09af2c)

**What did you expect to happen**:

I would expect to serve the same content as the previous version (9.5.3). I've tried to look at the official documentation to see if something needs to be changed on NGINX side (https://grafana.com/tutorials/run-grafana-behind-a-proxy/), but got no lucky.

![grafana-evidence-1](https://github.com/grafana/grafana/assets/5191469/533767d1-39b2-45cc-9e9b-20208c24c391)

### 
# How do we reproduce it?

**Step 1**:

- Update to the 10.0.0 version.
- Perform a curl request to your installation (ex: http://localhost:3000).
- It's showing the `Location` header with the domain and the HTTP(s) schema and not a relative path anymore.

### 
# What Grafana version are you using?

v10.0.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Debian GNU/Linux 11 (bullseye)

### Is this a Regression?

None

**Comment by thiagosanches** [comment]
My `grafana.ini` server section:
![grafana-evidence-3](https://github.com/grafana/grafana/assets/5191469/ca688fe8-ac7b-421d-96b7-4506ae5fca0d)

**Comment by thiagosanches** [comment]
Right now, I'm rolling back to the 9.5.3 version and it's working fine!

```bash
sudo apt-get purge grafana
sudo apt-get install grafana=9.5.3
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl status grafana-server
```

**Comment by sabady** [comment]
Facing the same problem, is there a fix or work around?

**Comment by aMU5Ed** [comment]
> Facing the same problem, is there a fix or work around?

Downgrading to 9.5.3 fixed it for me.

**Comment by saruter** [comment]
same here, Grafana behind Apache Reverse Proxy, downgrading to 9.5.3 fixes problem.

**Comment by 2-5** [comment]
Same problem, I use Grafana behind NGINX proxy and it doesn't work anymore since 10.0 upgrade.

Chrome error: `ERR_TOO_MANY_REDIRECTS`

**Comment by codymhorton** [comment]
Same issue, watchtower updated Grafana to 10. I rolled back to 9.5.3 and that fixed it. Grafana is behind Nginx, I didn't get the error ERR_TOO_MANY_REDIRECTS but got refused connection I believe or something similar.

**Comment by NTsvetkov** [comment]
Ubuntu, apache 2, Grafana 10.0.0, reverse proxy. Confirm, not working.
Chrome error: ERR_TOO_MANY_REDIRECTS

**Comment by sstamm** [comment]
Same here, getting a 301 to https://XXX.com:3000/grafana/ iIguess because Grafana is running at http://localhost:3000. 
But right would be https://XXX.com/grafana/, so redirecting to the port seems to be wrong

**Comment by suntala** [comment]
@thiagosanches thank you for reaching out about this issue and the clear description you included. Is there a docker-compose file you could provide which could be used to reproduce the issue?

**Comment by MylesJohnson** [comment]
Same problem. Ubuntu 22.04 and Nginx, setup following the official tutorial here: https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by TheOldMan2000** [comment]
Hi all, 

I’m reverse proxying with Apache, not NginX and I also have the too many redirects error after auto upgrading to v10.

“Safari can’t open the page. Load cannot follow more than 20 redirections.”

In fact I had it already occur after Grafana updated itself to v10 beta, despite me having it configured to ignore the beta versions (I double checked), and the only way I could finally get it working again was to completely remove it all and start again with v9.5.2. It auto updated to the full v10 release and hey presto, the same problem is back again.

CentOS v7.9.2009 STANDARD virtuozzo 
WHM/Cpanel 110.0.7
PHP-FPM v8.1.20
6GB RAM
48 core Cloud VPS

**Comment by thiagosanches** [comment]
> @thiagosanches thank you for reaching out about this issue and the clear description you included. Is there a docker-compose file you could provide which could be used to reproduce the issue?
Hi @suntala , thanks for your reply. Unfortunately I don't have a docker-compose for that, cause I'm using the package distributed by APT.

**Comment by torkelo** [comment]
Sorry for this, the run Grafana behind proxy guide was updated last year with url rewrite config erroneously. We have updated the guide (and docs) with more clear instructions:

https://github.com/grafana/grafana/pull/68608

**Comment by TheOldMan2000** [comment]
Thank you @torkelo ! 

`you should not set serve_from_sub_path = true `

That fixed it immediately! 🫶

**Comment by thiagosanches** [comment]
Yes! It's working fine, as @torkelo suggested, I've updated that flag to `false`.
![image](https://github.com/grafana/grafana/assets/5191469/970c0770-b722-453c-92e4-27bf83b95500)

**Comment by aMU5Ed** [comment]
Thanks @torkelo - fixed it for me as well!

**Comment by tolzhabayev** [comment]
@thiagosanches I guess this can be closed now then?

**Comment by thiagosanches** [comment]
yes, we can close it @tolzhabayev ! thank you again!

**Comment by Hipska** [comment]
@torkelo what if I still want to serve Grafana from sub_path? It seems setting back to false disables the option to go directly to port 3000 (in case of problems with the proxy)

**Comment by yosiasz** [comment]
so has anything changed with the doco on this ?
https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by yosiasz** [comment]
My compose file is as follows @suntala. I am using `podman`
```
# Use root/example as user/password credentials
version: "3.1"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    ports:
      - 8080:80
    volumes:
      - "./conf_nginx/default.conf:/etc/nginx/nginx.conf:ro"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    volumes:
      - ./conf_grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    ports:
      - 5000:3000
```

**Comment by nofacer** [comment]
delete serve_from_sub_path works for nginx ingress

**Comment by dawidpstrak** [comment]
For grafana with apache this worked for me.

1. Configure Apache
```
<Location "/grafana">
    ProxyPass "http://localhost:3001"
    ProxyPassReverse "http://localhost:3001"
</Location>
```

2. Set env
```
GF_SERVER_ROOT_URL = domain.com/grafana
```

3. Make sure to remove or set to false: `GF_SERVER_SERVE_FROM_SUB_PATH`

**Comment by petkozma** [comment]
Issue still persists, unfortunately similar update from 9.1.5 to 10.4.9 grafana.  Grafana endpoint is behind the nginx reverse-proxy, ingress rule:
`spec:
  ingressClassName: nginx
  rules:
  - host: rancher.web.ui
    http:
      paths:
      - backend:
          service:
            name: rancher-monitoring-grafana
            port:
              number: 80
        path: /grafana(/|$)(.*)
        pathType: ImplementationSpecific
`
