### ISSUE TITLE
Router Network interface traffic monitoring.

### ISSUE THREAD

**Issue by yuvarajanlga** [grafana/grafana#7012]
Hi,

I am using sensu plugin to collect metrics of network devices and store it in graphite.

When i configure the raw metrics in grafana, yaxis units are showing wrong and the graphs are not same with my nagios graph. 

From the grafana, after i use the derivative() function atleast i can see the yaxis unit as bits/sec. But the values are not showing in the graph. am i doing any thing wrong. please guide me. thanks.

![screen shot 2016-12-20 at 6 32 59 am](https://cloud.githubusercontent.com/assets/21257627/21331752/258412de-c67f-11e6-94fb-1d4ff83782af.png)

**Comment by torkelo** [comment]
please issue questions to the mailing list.
