### ISSUE TITLE
Concurrent API calls interacting with Sqlite DB result in table lockdown

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#7013]
Using Grafana master's branch.

When I fire 6 concurrent datasource create/update calls, I get the following errors for some:
```
EROR[12-19|17:57:11] Failed to update datasource              logger=context userId=1 orgId=1 uname=admin error="database table is locked"
EROR[12-19|17:57:11] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/4 status=500 remote_addr=127.0.0.1 time_ms=36ns size=41
EROR[12-19|17:57:11] Failed to update datasource              logger=context userId=1 orgId=1 uname=admin error="database table is locked"
EROR[12-19|17:57:11] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/6 status=500 remote_addr=127.0.0.1 time_ms=40ns size=41
```

I can definitely put some retries on my end and it will just work, but I think Grafana API should retry in few milliseconds to handle the request if table is locked and timeout after "n" attempts.

**Comment by utkarshcmu** [comment]
I am not sure how Grafana would like to handle concurrent requests which can result in "table lockdowns". Some ideas:
1. retries
2. sleep and retry

**Comment by torkelo** [comment]
never seen this, even in my benchmark tests that use the sqlite db. 

What db & disk storage did you use?

**Comment by utkarshcmu** [comment]
I am using my local mac and sqlite db. Even I am seeing this first time.

**Comment by bergquist** [comment]
@utkarshcmu Are you using any tool for viewing/updating the sqlite data? I know some of those tools can sometimes create locks on the database while open.

**Comment by utkarshcmu** [comment]
Yeah, I was using "sqlitebrowser. I thought the same so I closed that application and re-tested. Still I see this error. Will try to troubleshoot more and post my findings. :|

**Comment by utkarshcmu** [comment]
Also, i ran `fuser data/grafana.db` to see which process is locking the db and its the 'grafana-server' process.

**Comment by torkelo** [comment]
do you have script that you use that we can try and replicate with? Do you have any alerts configured? (how many and how frequent evaluations)

**Comment by utkarshcmu** [comment]
Here is the gist which I am using to reproduce the error:
Please replace the username and password if its different from the default
https://gist.github.com/utkarshcmu/acc773d0579148e8d7582eee31e95af5

**Comment by utkarshcmu** [comment]
This is the code which calls the API - https://github.com/utkarshcmu/wizzy/blob/master/src/grafana.js#L354

**Comment by torkelo** [comment]
I get the same error running on linux, so definitely not something related to mac/disk but just how sqlite works, strange that there has been no other similar reports.

**Comment by utkarshcmu** [comment]
Also, if you comment out - https://github.com/utkarshcmu/wizzy/blob/master/src/grafana.js#L396
and uncomment 'sync-request' block -  https://github.com/utkarshcmu/wizzy/blob/master/src/grafana.js#L390

And run "node src/index.js export datasources", it will work fine as the requests are made one after another using "sync-request".

**Comment by bergquist** [comment]
I think it would be best to run insert/updates in sync or max ~3 requests at the time. 
I just don't think its worth the effort to optimize the insert/updates for datasources in grafana. Optmizing it would probably require dropping transactions and that's not something I would like.

**Comment by torkelo** [comment]
and given that this is sqlite3, I would imagine that mysql or postgres would handle this contention better

**Comment by utkarshcmu** [comment]
Not getting the error with mysql. Its just sqlite. 👍

**Comment by bergquist** [comment]
So any action for this issue?

**Comment by utkarshcmu** [comment]
I don't think so. I'll close it.
