### ISSUE TITLE
PanelChrome: Allow panel to be collapsed

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#70145]
### Requirements ###

Extend PanelChrome API to allow the panel to be collapsed / expanded in a similar way like `Collapse` component.

### Background

As part of #61563 Explore squad attempted to start using PanelChrome in Explore visualizations. However, `NodeGraph`, `LogsVolume` and `LogsSample` can be in some cases collapsed so to PanelChrome, it needs to support collapsing.

First attempt (#69562) tried to re-use existing `Collapse` component but that won't allow to add more header options to a collapsed panel in the future, so the decision was made to add collapsing functionality to `PanelChrome` itself.

Why it's important? It can provide consistent behavior across Explore and Dashboards. It can also be use in the future by Scenes framework.

#### Details

At the moment PanelChrome supports two display modes switched by setting a flag `hoverHeader: boolean` (see more details in https://github.com/grafana/grafana/pull/69562#pullrequestreview-1469742196)

__Non-functional requirements__

* Documentation should be updated
* Story should be updated

__Functional requirements__

* 3 independent modes for the panel: for normal, hover and collapsible state
* Indicate collapsed/expanded state the same way as in Collapse component
* The panel can be collapsed/expanded by clicking on the chevron or the title

__Stakeholders__

@grafana/explore-squad: implementation
@grafana/dashboards-squad: technical approval
@Ijin08: UX approval
@grafana/design-system: feedback

**Comment by ifrost** [comment]
@Ijin08 - could you please provide feedback on this from UX - perspective

@grafana/dashboards-squad @axelavargas - please share your feedback as well :)

**Comment by ifrost** [comment]
Thanks a lot @axelavargas 🙌 

I'll update the outstanding questions as follows:

> What to show in the header when the panel is collapsed? Probably we can show all items that are also included in hoverHeader=false , but then the question is which part of the header should be clickable?

* Show all items that are available in `hoverHeader` state.
* Use chevron and the title to expand the panel

> How to indicate visually that component is in collapsed/expanded state? Maybe the same way as in Collapse component?

* Use the same pattern as in `Collapse` component

> How the panel should be expanded/collapsed? By clicking on the chevron or entire header (depends on other items in the header)

* Clicking on the chevron or the title

> Should hoverHeader and collapsible state be independent (i.e. could be set both at the same time) or should they be different options of the display mode?

* We should have 3 different, independent display modes: `normal`, `hover`, `collapse` (you can choose different names, whatever works best)

@Ijin08 / @grafana/dashboards-squad please let me know if you disagree with anything above, anything is missing or not clear.

**Comment by ifrost** [comment]
@grafana/design-system let us know if you have any feedback on this

**Comment by Ijin08** [comment]
Hey!
I think @axelavargas feedback was spot on.

I think the collapsable panels needs to have header section. Since the angle/chevron icon needs to always be visible. 
Regarding using the same patter as the collapse component @catherineymgui is working on a redesign of the collapse so that pattern might change.

This feature is good for Explore and apps that use panels. For dashboards there are some issues. Panels commonly aren't full width so collapsing a panel can affect a dashboard in weird ways. Also in dashboards panels are dragged so a panel with collapse with very long title might not be movable.

**Comment by Ijin08** [comment]
Yes
