### ISSUE TITLE
[Bug] No more notification configured but still continue to receive them

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#7014]
- What Grafana version are you using?
4.0.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS

- What did you do?
In order to not receive anymore notifications coming from an Alert in our Slack, I remove the notification configuration.

- What was the expected result?
To not receive anymore alerts in our slack channels regarding this graph and this alert.

- What happened instead?
We style receive alerts notifications in our slack even if the notification configuration is empty (have a look at the attachment).

![grafana_no_more_notif_but_still_continue_to_receive_them](https://cloud.githubusercontent.com/assets/2543381/21346403/8f9918b6-c6a4-11e6-9378-af602669c51a.png)

![still_notifications_alerts_on_slack](https://cloud.githubusercontent.com/assets/2543381/21346413/93eb7d96-c6a4-11e6-9c58-8c13a3b63778.png)

Thanks! :-)

**Comment by torkelo** [comment]
did you save the dashboard after you removed the notifications from the alert rule?

**Comment by scraly** [comment]
Yes i saved it.
I can test again this night in order to confirm this.

**Comment by torkelo** [comment]
Also make sure that no notification is flagged as send on all alerts:

![image](https://cloud.githubusercontent.com/assets/10999/21346942/d68f3938-c6a6-11e6-8c3e-d23a815191bf.png)

**Comment by scraly** [comment]
Yes i've checked this details this morning and the checkbox is unchecked.
I'll take you inform tomorrow morning if the problem still appears or not.
Thanks for your reactivity Torkel.

**Comment by scraly** [comment]
Bugs no appear anymore so I closed it.
Thanks.
