### ISSUE TITLE
[Feature Request] Allow use Key/Value pair separately

### ISSUE THREAD

**Issue by jonatanhosp** [grafana/grafana#7015]
I would like to have a variable which uses Key/Value pair and let use key and value separately.

Example:
Kubernetes service deployed as name 'blablabla-blabla' and service name used by metrics 'blublu'.
Create a variable <Key/Value> like <blablabla-blabla/blublu>.
Use $variable.key to shown deployed dates and $variable.value to get metrics.

Result:
Select the service and show metrics and deployment dates.

**Comment by torkelo** [comment]
could you describe more what the template variable config would look like?

sounds similar to:
https://github.com/grafana/grafana/issues/3478
https://github.com/grafana/grafana/issues/1988

**Comment by jonatanhosp** [comment]
Template variable config:
![seleccion_099](https://cloud.githubusercontent.com/assets/7037610/21354245/9c268fbc-c6c9-11e6-8edd-a3509b0e3758.png)

As you can see, '$service'it's hlrlookup-service and '$deployment' it's hlr-lookup.

What I'm requesting:
Create a key/value pair (list would be nice) named for example '$service' with key pair value hlr-lookup/hlrlookup-service. When a different '$service' was selected, apply on certain graphs '$service' key (hlr-lookup) and in other ones '$service' value (hlrlookup-service), so no need to create separated variables for probably same values (in our case, only few services have different deployment name than service name, caused by name length limitation on deployment one, but need to duplicate it in order to create a general rule with our variables).
