### ISSUE TITLE
Use short units in Explore

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#70166]
https://raintank-corp.slack.com/archives/C036J5B39/p1682510152907529

To avoid having this (long number on Y axis)...

![Image](https://user-images.githubusercontent.com/745532/245925715-4f49fcad-b223-49c0-a041-17845acf5fbe.png)

We could  use short unit like this:

![Image](https://user-images.githubusercontent.com/745532/245925804-8655dc5f-a8cc-4ba1-b88f-aad4b63cad39.png)

**Comment by Elfo404** [comment]
the second screenshot uses a specific unit, we should probably use a short notation but always treat is as a scalar value

**Comment by kodurimohan** [comment]
can I work on this? I'm not authorized to access the slack link. Where should I contribute?

**Comment by Elfo404** [comment]
@kodurimohan sure thing. the slack thread is not important, it just highlight the issue.
the idea is to use the `short` unit in the ExploreGraph component, which could probably be set by modifying the default options in https://github.com/grafana/grafana/blob/main/public/app/features/explore/Graph/ExploreGraph.tsx#L102

<img width="1092" alt="Screenshot 2023-09-29 at 16 57 08" src="https://github.com/grafana/grafana/assets/1170767/54ea0392-edc6-4849-8d47-3bf84ef01a62">

i'll assign this to you, let me know if you have any other question

**Comment by kodurimohan** [comment]
I'm new bee here. It's too hard to set up dev environment. Please help me.

**Comment by Elfo404** [comment]
you can follow the guide in https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md, it should get you up and running. if there's anything that doesn't work please let me know

**Comment by ifrost** [comment]
@kodurimohan please let us know if  you are still interested in working on this issue 🚀

**Comment by kodurimohan** [comment]
I'm quitting, assign to someone else.
