### ISSUE TITLE
Elasticsearch: Remove mentions of "Access" in basic configuration

### ISSUE THREAD

**Issue by gwdawson** [grafana/grafana#70173]
the access configuration option seems to have been removed from the elastic datastouce config page, this can now be removed from the docs

---

### Set the data source’s basic configuration options:

Name   | Description
--     | --
...    | ...
...    | ...
...    | ...
Access | Don’t modify Access. Use Server (default) or the data source won’t work.

**Comment by Eve832** [comment]
Not sure when @lwandz13 will get to Elasticsearch, but I'll leave it up to her to triage
