### ISSUE TITLE
[Bug] "ADD ROW" button missing when side menu is pinned

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#7017]
- What Grafana version are you using? Master Branch
- What did you do? Pinned side menu
- What was the expected result? Should still see "ADD ROW" button.
- What happened instead? But "ADD ROW" button was missing. :(

<img width="233" alt="screen shot 2016-12-20 at 3 35 20 am" src="https://cloud.githubusercontent.com/assets/1019609/21349197/677eff24-c665-11e6-9c14-496cddfd145c.png">

<img width="389" alt="screen shot 2016-12-20 at 3 35 24 am" src="https://cloud.githubusercontent.com/assets/1019609/21349203/755133a6-c665-11e6-9d69-cec74bee9165.png">

**Comment by utkarshcmu** [comment]
Steps to reproduce:
1. Have only 2 rows in your dashboard.
2. Pin the side menu and unpin it, you will see the UI bug.

1. Have only 5 rows in your dashboard.
2. Pin the side menu and you will see "ADD ROW" button in the side menu space at the bottom left of the page.

**Comment by torkelo** [comment]
thanks for the heads up
