### ISSUE TITLE
Explore Links with incorrect datasource UID's blank out the query

### ISSUE THREAD

**Issue by Pokom** [grafana/grafana#70194]
## Context

In https://github.com/grafana/deployment_tools/issues/56134, we were informed that a number of our links in runbooks and documentation did not have uid's for the data sources. In a subsequent PR, we added a unique uid to all of our data sources. Shortly after, existing links to Grafana dashboards broke.

See https://raintank-corp.slack.com/archives/C02TXB92G6T/p1686843307476749 for internal conversation with actual links to explores to further triage.

## Problem 

- Version: `Grafana v10.1.0-56978pre (cc72fe17d5)`

Let's say you have this explore link(`https://${GRAFANA_SLUG}/grafana/explore?left=%7B%22datasource%22:%22totalfantasy%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22read_commit_proc_issued%7Bcluster%3D%5C%22some-cluster%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22fantasy-uid%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D&orgId=1`) that has an incorrect data source. In this example we purposefully made it nonsensical, but this is to illustrate the scenario where the datasource uid has changed. Our expectation was that:
- The datasource would change to the default for the Grafana instance
- The query would remain intact and populate in the explore

What we're experiencing is that the datasource gets updated to the default data source but the query gets stripped from the URL and does not get populated. In stable(`Grafana v10.0.0 (81d85ce802)`), there is a console error. In latest there is none.

## Goals

For Prometheus data sources, I would expect
- The query to be preserved if the UID/datasource is replaced
- Notification to the user that the UID was incorrect/non-existent
- Or some error propagated to the user to it's clear _why_ the query was stripped

**Comment by Elfo404** [comment]
Closing this as we feel like - by fixing this - we'll lead to other confusing scenarios. We'll instead improve error handdling so that it's clear to the user what happened and why in such cases.
