### ISSUE TITLE
[Feature request] Download node_modules without npm

### ISSUE THREAD

**Issue by CJosePhD** [grafana/grafana#7021]

**Comment by CJosePhD** [comment]
[Feature request]

I need to build from source in order to add custom functions to grafana gfunc.js. The issues is my proxy npm install. How can implement a manual npm install?

**Comment by bergquist** [comment]
Then someone with access to npm would have to run `npm install` with the exact same version you intend to build and send the `node_modules` folder to you.

**Comment by torkelo** [comment]
not seeing how we can do this.
