### ISSUE TITLE
Logs: Show log row actions also after eye-button click

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#70217]
**What happened**
Log users in Explore usually see a menu with the show-context button and a copy button when they hover over log lines in Explore. When users use the "eye-button" from LogDetails those actions disappear from the hovering state.

**Normal behaviour:**
<img width="1351" alt="image" src="https://github.com/grafana/grafana/assets/8092184/b1d8fae5-59c2-4432-bf14-9c6a22ef592f">

**Broken behaviour:**
<img width="1361" alt="image" src="https://github.com/grafana/grafana/assets/8092184/54f8decd-5332-4e17-abd7-6277b0dcd4b0">

**Comment by matyax** [comment]
I don't think this qualifies as a bug, but rather as missing implementation.
