### ISSUE TITLE
[Feature Request] datasource instanceSettings access to directURL

### ISSUE THREAD

**Issue by solugebefola** [grafana/grafana#7022]
Grafana version: 4.0.1
datasource: iobeam
OS: macOS Sierra

I am attempting to construct a datasource that accesses the iobeam service through the REST APIs.  For my `testDatasource` function, my `datasource.js` file needs access to the directURL that is in the config page for the datasource, which would ordinarily be accessed through `instanceSettings.url`

(datasource.js)
```
export class GenericDatasource {

    constructor(instanceSettings, $q, backendSrv, templateSrv) {
        this.instanceSettings = instanceSettings;
        this.type = instanceSettings.type;
        this.url = instanceSettings.url;
        this.name = instanceSettings.name;
        this.username = instanceSettings.jsonData.iobeam_username;
        this.password = instanceSettings.jsonData.iobeam_password;
        this.q = $q;
        this.backendSrv = backendSrv;
        this.templateSrv = templateSrv;
    }
...
```

however, when the http settings access is set to `proxy` the `frontendsettings.go` file is overwriting the url with the proxy url:

(frontendsettings.go)
```
for _, ds := range orgDataSources {
		url := ds.Url

		if ds.Access == m.DS_ACCESS_PROXY {
			url = "/api/datasources/proxy/" + strconv.FormatInt(ds.Id, 10)
		}
```

I would like a separate `directUrl` attribute added for generic datasources, the same way it is set up for Prometheus.

**Comment by bergquist** [comment]
If you run the data source in `direct mode` instead of `proxy` you will get the full in the frontend. Is that what your looking for?

**Comment by torkelo** [comment]
For this you need to add another property to your data source plugin (add it on jsonData). 

exposing the URL even when using proxy mode is a security issue and we cannot accept that :(

**Comment by solugebefola** [comment]
Actually, the reason that I need access to that parameter is that for proxy mode, when I ping the datasource, I cannot tell whether the scheme is `http` or `https`, so my source will respond with a 200 to the ping even for `http`, even though it will not accept any requests unless the scheme is `https`

@torkelo I am afraid that I don't understand the security problem related to the reveal of the url?  For direct mode, the url is already exposed.  What are the consequences of showing the datasource url?

**Comment by seanlaff** [comment]
I want to provide a "click-back" link in the same manner as the prometheus plugin. For my datasource, masking the origin url is not a concern. 

Here is a work around.
Add a config_ctrl.ts file to your plugin.
```typescript
export class MyConfigCtrl {
  static templateUrl = 'partials/config.html';

  constructor($scope) {
    $scope.$watch('ctrl.current.url', (newUrl, oldUrl, scope) => {
      scope.ctrl.current.jsonData.url = newUrl;
    })
  }
}
```
This will watch the `url` input for changes, and persist them into the jsonData for your plugin. This will give you the desired behavior without making the user input the url into two separate boxes for your datasource plugin.
