### ISSUE TITLE
Elastic: Ad-hoc filters: Colon in Key causes query to fail

### ISSUE THREAD

**Issue by haelekuin** [grafana/grafana#70230]
### 
# What went wrong?

[Kooha-2023-06-16-11-48-41.webm](https://github.com/grafana/grafana/assets/86392447/54d0d58b-9994-421b-8a87-94135a5e5b0c)

**What happened**:

  - When adding an ad-hoc filter where the Key contains a colon, it causes the query to fail. This issue appears to be exclusive to Elasticsearch datasources, but I have been unable to extensively verify it.

**What did you expect to happen**:

  - The ad-hoc filter filters for my desired Key-Value pair.

### 
# How do we reproduce it?

**Step 1**:

- Open a Dashboard with an Elasticsearch datasource and ad-hoc filters for this datasource.

**Step 2**:

- Add an ad-hoc variable with a field that contains a colon and any value.

**Step 3**:

- Inspect the panel to see the root cause of the error

```
data:"{
    \"root_cause\": [
        {
            \"type\": \"query_shard_exception\",
            \"reason\": \"Failed to parse query [elas_field:name:\\\"Value\\\"]\",
```

### 
# What Grafana version are you using?

9.5.3 (broken)
9.5.2 (broken)
9.1.2 (functional)

### 
### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

6.3.7-arch1-1

### User's Browser?

Firefox 114.0.1 (64-bit)

### Is this a Regression?

Yes

### Are Datasources involved?

Elasticsearch 7.10+

### Anything else to add?

```
grafana-host# lsb_release -a

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Query Information**:

Inspecting the query in Grafana version 9.5.3 (broken) returns the following Elas query:

```
data:"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"stag-*\"}
{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"created_at\":{\"gte\":1686886557518,\"lte\":1686908157521,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"test:query:\\\"asd\\\"\"}}]}},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"created_at\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1686886557518,\"max\":1686908157521},\"format\":\"epoch_millis\",\"fixed_interval\":\"20000ms\"},\"aggs\":{}}}}
```

In a different Grafana instance on 9.1.2 (functional) the following Elas query is returned:

```
data:"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"stag-*\"}
{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1686907314680,\"lte\":1686908214680,\"format\":\"epoch_millis\"}}}],\"must\":[{\"match_phrase\":{\"test:query\":{\"query\":\"asd\"}}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"event.type\",\"size\":500,\"order\":{\"_key\":\"asc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1686907314680,\"max\":1686908214680},\"format\":\"epoch_millis\",\"fixed_interval\":\"10s\"},\"aggs\":{}}}}}}
```

As far as I am aware, `analyze_wildcard` is not set to `true` by default, but has been explicitly set in newer version. 

A workaround is to escape the colon with a backslash.

**Comment by matyax** [comment]
@haelekuin Thank you for the detailed bug report! It should be fixed by https://github.com/grafana/grafana/pull/70611
