### ISSUE TITLE
[Feature request] Asciidoc(tor) support in text panel

### ISSUE THREAD

**Issue by nickbabcock** [grafana/grafana#7024]
Apps I write use asciidoctor for official documentation. It would be nice if I could copy + paste this documentation into the dashboards, so there isn't an intermediate conversion stage.

Incoming PR.

**Comment by bergquist** [comment]
Whats the upside with asciidoc compared to markdown?

Not sure we want to maintain yet another mark up language unless its very valuable.

**Comment by torkelo** [comment]
This will not likely be implemented in the core text, if this is a requirement you have it could be easily done in a plugin.

**Comment by nickbabcock** [comment]
Thank you for the directions, I'll look to publish a plugin (and report back here)

But in case you are still curious @bergquist, one of my main goals is to use template variables inside a Text panel, and asciidoc supports variables. As well as AsciiMath and LatexMath notation. Advanced tables, theming, etc.
