### ISSUE TITLE
[Bug] Email alert not rendering text

### ISSUE THREAD

**Issue by nikozc** [grafana/grafana#7026]
- What Grafana version are you using? 

4.0.1
- What datasource are you using? 

Influxdb
- What OS are you running grafana on? 

CentOS 7
- What did you do? 

Triggered an email alert
- What was the expected result? 

I expected to receive an email with all the information, similar to the "Test notification alert".

![test-notification](https://cloud.githubusercontent.com/assets/891188/21370969/b90e8784-c6f5-11e6-8621-76211e43f38a.png)

- What happened instead?

The email I received was missing some important information like metric names, values, legends and axes values. I also have this same issue in all my other alerts.

![index](https://cloud.githubusercontent.com/assets/891188/21370899/4bafc842-c6f5-11e6-9e06-7ec4b345899b.png)

**Comment by bergquist** [comment]
You need to install some font packages on the server

http://docs.grafana.org/installation/rpm/#server-side-image-rendering

**Comment by aiwyn** [comment]
if my OS is Debian. How can I install some font packages？

**Comment by biello** [comment]
If I run it in docker, should I install these font packages inside the container or on my host OS?

**Comment by marefr** [comment]
@biello if your using docker you shouldn't need to install anything additional.
