### ISSUE TITLE
[feature request] Can  delete graphs without data Automatically?

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [grafana/grafana#7027]
Please include this information:
- What Grafana version are you using?  **4.0.2**
- What datasource are you using?  **Influxdb**
- What OS are you running grafana on? **Centos**

such as :
![1](https://cloud.githubusercontent.com/assets/18111540/21375009/9d574a2e-c765-11e6-98ab-57fffe6dde91.png)
**How to delete graphs  Automatically when there is no data for A few hours or days?**

Thanks all

**Comment by utkarshcmu** [comment]
There is an issue for Dashboards TTL which is still open - https://github.com/grafana/grafana/issues/2911

Until then you can use 'wizzy' - a command line tool to interact with Grafana, to delete your dashboards.

**Comment by Chentongxuedefanhua** [comment]
@utkarshcmu thank you for the reply, I'd like to have a try

**Comment by bergquist** [comment]
This would be very tricky to implement. We would not want to delete dashboards just because the data source is available/broken for some period of time.

I think this should be solved with TTL or deleting dashboards that have not been viewed for a certain time. 

I'm closing this in favor of #2911
