### ISSUE TITLE
Explore: Tempo TraceToLogs - Logs for Span link Disabled after upgrading Grafana 9.4 to 9.5

### ISSUE THREAD

**Issue by jlcrow** [grafana/grafana#70279]
### 
# What went wrong?

**What happened**:
  - After upgrading to Grafana 9.5 the Link to Loki Logs from Tempo Traces is disabled despite it working on 9.4 with the current configuration. Log Icons along side of Traces are also missing.

**What did you expect to happen**:

  - The Link to continue to work since the TraceID pattern hasn't changed and is still configured in the Datasource

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana in Explore tab and search for a Trace

**Step 2**:

- Click on Trace and Expand the Trace - the Logs for this Span link is Disabled and Log Icon that was previously in left bar of traces is missing - I'm not able to get to the trace without going specifically to Loki in Explore and search for the traceID

### 
# What Grafana version are you using?

9.5.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by ifrost** [comment]
Seems to be related to Tempo datasource, cc @grafana/observability-traces-and-profiling

**Comment by aocenas** [comment]
@jlcrow Hey can you send us a screenshot of your link configuration? Also, can you try this with grafana 10 if this has the same behavior?

**Comment by jlcrow** [comment]
@aocenas <img width="1346" alt="image" src="https://github.com/grafana/grafana/assets/4369807/a9104ebc-d129-4ead-b37b-8e16386d8977">

**Comment by jlcrow** [comment]
@aocenas
10.0.1 Has the same behavior as 9.5

<img width="755" alt="image" src="https://github.com/grafana/grafana/assets/4369807/61c3fba9-8485-40d3-a3ec-5acfd9aad724">

9.4.3 works with the same configuration and backend for Loki/Tempo
<img width="673" alt="image" src="https://github.com/grafana/grafana/assets/4369807/fa40c4bc-415a-4940-81f9-26bb1db64f2a">

**Comment by jlcrow** [comment]
@aocenas @ifrost Looking for some sort of resolution here - for me the functionality of linking tempo traces to loki logs is completely broken beyond version 9.4.x of Grafana - honestly one of the only reasons I'm using Loki at all, my traceId's are present in my logs and searchable in Loki. Any more information I can provide I'm happy to provide.

**Comment by ifrost** [comment]
@aocenas - will [this one](https://github.com/grafana/grafana/pull/71372) fix this issue in 10.1?

**Comment by jlcrow** [comment]
@ifrost @aocenas Actually I think I just stumbled on a fix - both my Tempo traces and Loki logs have a common tag called cluster, which in previous versions must have been auto connected because of them being the same, I was about to write a custom query and try that option and I just simply added cluster as a Tag to the tracetologs settings in the Tempo datasource and now things seem to be working correctly again.

<img width="623" alt="image" src="https://github.com/grafana/grafana/assets/4369807/a4e88ea2-f2f5-439f-b3c3-3f50209ec088">
