### ISSUE TITLE
[Bug?] Total Traffic min max legend seems inaccurate

### ISSUE THREAD

**Issue by rwrocket** [grafana/grafana#7028]
Grafana 4.0.2-1481203731
Ubuntu 14.04
Influxdb capturing data from fastnetmon

![fastnetmon_graph](https://cloud.githubusercontent.com/assets/24306959/21376957/82264ee4-c78d-11e6-9f35-631d10b54195.png)

I am brand new to Grafana so bare with me.
I managed to get the following graph setup to show incoming and outgoing traffic which appears to be working. However when I change the time from last 30minutes to last hour or today etc. my Min & Max is different every time.

How can this be correct if I know for a fact that the biggest traffic spike was 5 minutes ago for example but if I set the time to "Today" it shows the Max as less than that if I set it to Last 5 minutes????????

**Comment by bergquist** [comment]
Min and max is calculated in the frontend and not by the data source itself. 

Using queries with aggregations will only give the aggregated value and not all the values used to calculate it. This means that min and max will be the highest/lowest mean value for the serie. not the highest/lowest value. If you want the correct data points for min and max you need to add one query for min and one for max per serie. 

Does this answer make any sense? :)

**Comment by bergquist** [comment]
Closing this issue for now but if anything is unclear I will reopen it again.
