### ISSUE TITLE
docs: Add documentation for disconnect feature

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#70282]
Add documentation for new disconnect feature

This feature is available in three panels:
 
[Time series](https://github.com/grafana/grafana/pull/70097)
[State timeline](https://github.com/grafana/grafana/pull/70610)
[Trend](https://github.com/grafana/grafana/pull/70616)

**Comment by GrafanaWriter** [comment]
Hi @drew08t - this issue is three weeks old; is there a plan to work on the documentation for this feature? I see the task is noted as Done for DataViz, so perhaps the docs were provided, but I don't see the linked PR for the documentation.

**Comment by nmarrs** [comment]
Hi @GrafanaWriter - we are planning on writing up initial documentation this week as this feature will be going out in v10.1 👍
