### ISSUE TITLE
[Feature request] Documented HTTP API for import functionality

### ISSUE THREAD

**Issue by LiranVonage** [grafana/grafana#7029]
Referring to issues [6321](https://github.com/grafana/grafana/issues/6321) & [6322](https://github.com/grafana/grafana/issues/6322)  - 

I am using the http API to upload a dashboard that contains datasource vars and templates that should be repeated. So I am using the import API (_POST /api/dashboards/import_) rather than the documented create/update API (_POST /api/dashboards/db_).

If the import API is a supported workflow - it should be documented in the HTTP API reference page.
Alternatively, support and document an http API for import functionality, such as datasource vars and template repeating, that is currently not supported through the documented API.

Using Grafana version v3.1.1 (commit: a4d2708) on mac OS.

**Comment by torkelo** [comment]
The import api does not support repeating templates. It only supports replacing data source variables.

**Comment by LiranVonage** [comment]
Well, it works for me...

**Comment by torkelo** [comment]
not following you.

> http API for repeating templates.
There is no such feature :) 

1. There is Dashboard template variables that can be used to repeat panels or rows. 
2. There is a TOTALLY different variable that grafana creates when you export a dashboard. It will "templatize" all data source instance names when you export the dashboard, so you can import it to another grafana instance that might have different data source instance names.

**Comment by LiranVonage** [comment]
Yes, I am talking about 2 totally different features, one is datasource vars, second is template repeating. Sorry if it wasn't clear enough.

I am currently importing (with import API) a dashboard that has few panels that are repeated many times with templates. This is working for me with the import API (/import), but not with the create/update API (/db).

**Comment by torkelo** [comment]
strange, I would have assumed it would be the other way around. 

The import api is only for dashboards you have exported via the UI, and the import api requires data source name inputs.

**Comment by LiranVonage** [comment]
You are right.
Let me explain what I did:
1. Exported a dashboard via the UI.
2. Imported it back via the UI.
3. Tracked the http request with chrome networking - that gave me the http request with the dashboard json containing the inputs section.
4. I am using this dashboard-with-inputs for occasional imports via the http API.

All I'm saying is that if import is a officially supported workflow, let's have it in the http API reference page, so devs will not be needing to hack it, and have it as a trusted API can is less likely to be broken.

**Comment by torkelo** [comment]
since the export is only a UI process (that tempetize data source names), the import is mostly a UI only action, hence the lack of HTTP api docs for this action as it requires UI in the workflow.

**Comment by LiranVonage** [comment]
Well, 
1. I am using a one-time exported dashboard as a reference for importing and re-importing dashboards in my ongoing process. It doesn't mean that each import requires a UI export operation.
2. It would be nice to have an http API also for export :)

Bottom line - It would be great to have an http API for uploading a dashboard with templates, that also does the repeating.

**Comment by abadyan-vonage** [comment]
@torkelo 
I would just like to understand the status of the /import endpoint. It is not in the official API, yet it is the only way to perform some of the operations.
Did you close the ticket because there is no intention of putting it in the official API? Is there another way to achieve creating a dashboard with repeating templates without going through the UI?

**Comment by torkelo** [comment]
Sorry, There is no way to do repeating templates during import currently, the import api is mainly for UI use, hence missing in the  api docs, the regular save dashboard api is documented and recommended for programmatic use

**Comment by discordianfish** [comment]
I also don't know what template variables have to do with the import api, yet I also wish for that API to be documented. It's not the first time I need to import dashboards automatically via the API and it won't be the last time :)
