### ISSUE TITLE
Alerts list: big labels on alerts do not fit the screen

### ISSUE THREAD

**Issue by freak12techno** [grafana/grafana#70290]
### 
# What went wrong?

**What happened**:

When using Alerts list panel, and having alerts with really long labels, they do not fit the screen. See screenshot:
<img width="1440" alt="изображение" src="https://github.com/grafana/grafana/assets/83376337/e3cf8e96-39eb-4c9a-a898-de8f9fccb89e">

**What did you expect to happen**:
Alerts labels should fit the screen or there should be a line break, so all of the labels would be visible.

### 
# How do we reproduce it?

**Step 1**:

- Have an alert with really long label and firing (probably also ok alerts will do)
- Create a dashboard with Alerts list panel
- Labels would not fit the screen

### 
# What Grafana version are you using?

Version 10.0.0 (commit: 81d85ce802, branch: HEAD)

### 
### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 20.04

### User's Browser?

Firefox

### Is this a Regression?

Yes

### Anything else to add?

I think this was broken with Grafana v10, before it seemed to work correctly.

**Comment by armandgrillet** [comment]
> I think this was broken with Grafana v10, before it seemed to work correctly.

We have checked and this was not working in Grafana 9 too. The user experience is not great right now, we will work on revamping the details panel in a future release. In the meantime, you can see the full labels on the details view.

**Comment by freak12techno** [comment]
Thanks for investigating and answering.

> we will work on revamping the details panel in a future release.
Is there an issue on that here?

**Comment by gillesdemey** [comment]
We're tracking the epic here https://github.com/grafana/grafana/issues/70606 – currently no milestone attached
