### ISSUE TITLE
Dashboards: Time Range Selector From/To Calendar widgets should not both set both fields

### ISSUE THREAD

**Issue by buzzware** [grafana/grafana#70299]
### 
# What went wrong?

**What happened**:

  - Customer complained that they could only select a single date for the time range
  - On investigation, I understand their confusion, and agree that there is a UX bug here
  - For example, if you want to set the range from June 1-4, its reasonable for a user to :
  1. Open the time range selector
  2. Tap the From calendar button
  3. Tap June 1. They might notice that From has not changed, and double tap it which does change it. A single tap should probably set the field. To also changes, which is ok to keep the range valid
  4. Tap the To calendar button
  5. Double tap June 4. 
  6. Observe both From & To are set to June 4 hence their confusion.

**What did you expect to happen**:

  - A single tap should be sufficient to set the field you opened the calendar for
  - Step 5 above should only affect the To field

I believe this needs attention from an internal UX designer to balance expectations from the developers, existing and future users. I understand you are supposed to tap June 1 and then June 4, but having two calendar buttons misleads the user to think they are individual fields, when in fact I think either button puts you into the same context of setting the range for both.

### 
# How do we reproduce it?

See above

### 
# What Grafana version are you using?

v9.5.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

MacOS

### User's Browser?

Chrome

### Is this a Regression?

No

### Are Datasources involved?

no

### Anything else to add?

<img width="752" alt="image" src="https://github.com/grafana/grafana/assets/28285/205a98f4-e180-458d-956c-e1825774c3e7">

**Comment by zuchka** [comment]
fwiw it's worth I've seen complaints about this behavior for years

**Comment by L-M-K-B** [comment]
Added to our TimePicker epic.
