### ISSUE TITLE
Timestamp formatting on Grafana 10.0 is not working anymore

### ISSUE THREAD

**Issue by vbulbul** [grafana/grafana#70301]
### 
# What went wrong?

On bar gauage naming, I was using timestamp with formatting time value with` ${__cell_0:date:DD.MM} `,but on new release 10.0 it returns query itself.
`$__cell_0` instead of `${__cell_0:date:DD.MM}` is working without formatting.
`${__from:date:DD.MM}` is still works but how to format `$__cell_0` ? 

### 
# How do we reproduce it?

On Bar Gaugae edit section try yo set Display Name to ${__cell_0:date:DD.MM}
![image](https://github.com/grafana/grafana/assets/39090711/bfe58cbb-4148-4543-8080-194aa3ddb9ae)

It looks like this on version 10.0.0
![image](https://github.com/grafana/grafana/assets/39090711/7274c07a-cbc1-4c45-8a98-d5d822dfb0d4)

But on previous releases it was 
![image](https://github.com/grafana/grafana/assets/39090711/2c2badd0-0291-421a-a562-7562d55e1304)

### 
# What Grafana version are you using?

v10.0.0

### 
### Is the bug inside a Dashboard Panel?
On every panel that bar gauge exist 

### Grafana Platform?
Docker

### User's OS?
raspbian

### User's Browser?
Chrome

### Is this a Regression?
Yes

**Comment by zuchka** [comment]
@vbulbul I can't read your description. I think there was an error in your markdown syntax. Please describe your issue again and please provide steps for reproduction.

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by vbulbul** [comment]
@zuchka Is the description enough now ?

**Comment by kmcrawford** [comment]
I'm having the same issue after upgrading to 10.0.2 
`${__cell_0}` displays 
<img width="1323" alt="image" src="https://github.com/grafana/grafana/assets/40531/39e7a62f-aed9-42d7-809c-bbe60663e4b1">
but as soon as you try a date format like `${__cell_0:date:dddd}`  you get:
<img width="1315" alt="image" src="https://github.com/grafana/grafana/assets/40531/f4c8a0a6-d126-4011-9dad-0a1d68b6edf3">

**Comment by zuchka** [comment]
@kmcrawford  do you think you could try and replicate this on our public sandbox, https://play.grafana.org/? 🙏

**Comment by kmcrawford** [comment]
@zuchka I created this on the playground:
<img width="1749" alt="image" src="https://github.com/grafana/grafana/assets/40531/705d4528-20ea-4335-9c1b-c7c20962c589">

**Comment by natellium** [comment]
Probably caused by https://github.com/grafana/grafana/pull/65324

**Comment by vbulbul** [comment]
In which version will be fixed ?

**Comment by jlcrow** [comment]
I still see this as broken as of 10.1.5, formatting is not applied when using ${__cell_0:date:DD.MM} it just reflects back the format itself.

**Comment by jlcrow** [comment]
This kind of got worse with 10.2, now formatting is applied but date is lost and just displays incorrect Date everywhere

No format applied
<img width="1327" alt="image" src="https://github.com/grafana/grafana/assets/4369807/6aa43048-6843-4043-93fa-ade1bb1c25b9">

format applied
<img width="1520" alt="image" src="https://github.com/grafana/grafana/assets/4369807/2e0f98ab-2ff8-47b3-ba45-f415c0e0e28b">

@kaydelaney

**Comment by vbulbul** [comment]
As @jlcrow mentioned "${__data.fields[0]:date}" gives 01.01.1970 as date issue is not resolved.

**Comment by kmcrawford** [comment]
I think I was able to fix it by using a conversion
<img width="1266" alt="image" src="https://github.com/grafana/grafana/assets/40531/b46925ab-398c-498a-b242-d2aa9362829a">
