### ISSUE TITLE
Grafana 10: Password reset link misleading

### ISSUE THREAD

**Issue by UweSauter** [grafana/grafana#70304]
### 
# What went wrong?

**What happened**:

I'm running Grafana behind a Nginx reverse proxy that does TLS termination and internally talks to Grafana on port 3000.
Nginx/Grafana is setup so that Grafana is served in a subpath.

Nginx itself will tell all clients that connect to port 80 to go and retry on port 443:

```
  server {
    listen       80;
[…]
    location ~ ^/ {
      return 301 https://$host$request_uri;
    }
}
```

And Nginx config for Grafana:
```
  upstream grafana {
    server [::1]:3000;
  }
  […]
  server {
    listen       443 ssl http2;
    listen       [::]:443 ssl ipv6only=on http2;
    server_name  my-host.example.com;
    root         /usr/share/nginx/html;

    ssl_certificate           "/etc/nginx/certs/my-host.example.com_fullchain.crt";
    ssl_certificate_key       "/etc/nginx/certs/my-host.example.com.key";
    ssl_session_cache         shared:SSL:1m;
    ssl_session_timeout       10m;
    ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:!AES128;
    ssl_prefer_server_ciphers on;
    ssl_protocols             TLSv1.3 TLSv1.2;

# OCSP Stapling ---
# fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 127.0.0.53;

# HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload" always;
    add_header Content-Security-Policy "connect-src 'self'; default-src 'self'; font-src 'self' data:; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data:; media-src 'self'; object-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';";
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff";
    add_header X-Download-Options "noopen";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Permitted-Cross-Domain-Policies "none";
    add_header X-Robots-Tag "none";
    add_header X-XSS-Protection "1; mode=block";

    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    error_page 404 /404.html;
      location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
      location = /50x.html {
    }

        location /grafana/ {
      proxy_set_header Host $http_host;
      proxy_pass http://grafana;
    }

    location /grafana/api/live/ {
      proxy_http_version 1.1;
      proxy_set_header upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $http_host;
      proxy_pass http://grafana;
    }
  }
  ```

And relevant parts of `grafana.ini`:
```console
[server]
protocol = http
http_addr = [::1]
domain = my-host.example.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

These configuration options are taken from [the official tutorial](https://grafana.com/tutorials/run-grafana-behind-a-proxy/).

Now the issue: if I request a password reset link I will get an email that contains a link that

1. begins with `http://`. This might be ok because Nginx will tell the client to try `https://` instead but can be considered insecure.
2. uses the (only locally reachable) port 3000. But because Grafana is behind Nginx the link will not work.

**What did you expect to happen**:

Instead of getting a link that points to an externally non-available port, e.g.
`http://my-host.example.com:3000/grafana/user/password/reset?code=202306190939000120b3fabfee000cec5698a66ff916771c109dd4bdd90b84667201988a988c714b9d6870637361757465`
I expected to get a link that is working, e.g.
`https://my-host.example.com/grafana/user/password/reset?code=202306190939000120b3fabfee000cec5698a66ff916771c109dd4bdd90b84667201988a988c714b9d6870637361757465`

Is this a misconfiguration on my side? Should `[server] root_url` be `https://%(domain)s/grafana/`? What implication would that change have?

### 
# How do we reproduce it?

**Step 1**:

- Install Grafana to run behind Nginx in a subpath. Configuration see above.

**Step 2**:

- Try to reset your password by requesting a reset link.

**Step 3**:

- Try to open the received link. -> Grafana cannot be reached.

**Step 4**:

- Edit the received link so that `https://` is used. Drop the `:3000` port part of the URL. -> Password can be reset.

### 
# What Grafana version are you using?

Grafana 10.0.0-1 installed by yum/dnf from the official repository.

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Rocky 9

### Is this a Regression?

None

**Comment by mgyongyosi** [comment]
@UweSauter Thanks for your report. Could you please try with the following config?
```
[server]
http_addr = [::1]
domain = my-host.example.com
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
```

**Comment by UweSauter** [comment]
Hi @mgyongyosi,

thanks for getting back so quickly.

Both versions of
```
[server]
protocol = http
http_addr = [::1]
domain = my-host.example.com
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
```

```
[server]
http_addr = [::1]
domain = my-host.example.com
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
```

create a correct link in the sent email:

`https://my-host.example.com/grafana/user/password/reset?code=<long string>`

while

```
[server]
protocol = https
http_addr = [::1]
domain = my-host.example.com
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
```

fails due to missing certificates (which seems logical).

I think `root_url` needs to be changed in the tutorial to account for the situation that Grafana is run behind a reverse proxy.

**Comment by UweSauter** [comment]
Would you care to update the tutorial as well or at least add a paragraph that mentions that root_url might need this change in certain configurations?
