### ISSUE TITLE
feature request: data sources sorted by frequency of use

### ISSUE THREAD

**Issue by shenxingbo** [grafana/grafana#70312]
I have a lot of prom data sources, and I have to search every time I use them, which is very inconvenient to use, so can grafana support sorting by the frequency of use of data sources

**Comment by JoaoSilvaGrafana** [comment]
Hi @shenxingbo , thanks for raising this feature request! Could you let us know where in the platform would you like to see them sorted by frequency of use? Do you mean in the datasource picker of the query editor or somewhere else?

**Comment by shenxingbo** [comment]
Thanks a lot for attention to my needs, I am referring to this place below：
![image](https://github.com/grafana/grafana/assets/10804319/478e49ba-c0ec-40fc-9884-c00420b26369)
@JoaoSilvaGrafana

**Comment by JoaoSilvaGrafana** [comment]
Thanks for getting back to us! Moving this to @grafana/plugins-platform-frontend since you are the codeowners of the folder with the DataSourcePicker. Let us know if this is wrong and someone else should be looking into this.

**Comment by shenxingbo** [comment]
Sorry, I don't quite understand what you said, please explain how I should deal with it 🤝@JoaoSilvaGrafana

**Comment by JoaoSilvaGrafana** [comment]
> Sorry, I don't quite understand what you said, please explain how I should deal with it 🤝@JoaoSilvaGrafana

Don't worry @shenxingbo there is nothing else you need to do right now, I was just moving it to the relevant team 😄

**Comment by shenxingbo** [comment]
ok，thank you very much！

**Comment by natellium** [comment]
Hey @shenxingbo in Grafana 10 we released a [new datasource picker](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-0/#select-data-sources-more-easily). Based on your screenshot it looks like you're still on the previous one. In the new picker the first 4 datasources are sorted based frequency of use. We will also soon work on adding a new functionality that will keep the last used datasource selected as default per dashboard, you can follow the progress of this here https://github.com/grafana/grafana/issues/69435

I think this would cover your request, so I'll proceed to close the issue. Please let us know if you have any further feedback! :)

**Comment by shenxingbo** [comment]
Thanks a lot, this function solved my problem. But clicking the datasourcer picker one more time will make the user feel inconvenient. I hope there will be a better solution in the future 💐 @natellium
