### ISSUE TITLE
[Bug] Graph: Line fill only draws down to zero, if y-axes has a negative minimum

### ISSUE THREAD

**Issue by coolchip** [grafana/grafana#7031]
Version: Grafana v4.0.2 (commit: v4.0.2)
Datasource: InfluxDB
OS: Ubuntu 16.04.1 LTS

Hello,
at my graph I use one y-axe from -20 to 100. I added two data rows. One draws only a line (temperature) and another draws a line with a filling (huminity). The filling below the huminity line only goes down to zero. I expected, that it draws down to -20.

![graph](https://cloud.githubusercontent.com/assets/7850591/21380970/ef1d05a4-c758-11e6-8020-5fd502dfbec5.png)
![overrides](https://cloud.githubusercontent.com/assets/7850591/21380971/f2588ac2-c758-11e6-9d20-40630d4481cf.png)
![options](https://cloud.githubusercontent.com/assets/7850591/21380972/f39dd748-c758-11e6-8629-31217def1abe.png)

**Comment by torkelo** [comment]
sorry, line fill will always draw to zero.

**Comment by coolchip** [comment]
Is there any possibility or trick for me to draw it down to -20?

**Comment by torkelo** [comment]
if you had a series that was a straight line at -20, then you could use the series override style "fill below to" and you can select the series that it at -20

**Comment by coolchip** [comment]
Unfortunately this is also not working... 
![fillbelow](https://cloud.githubusercontent.com/assets/7850591/21386079/55ecbe9c-c771-11e6-8a9c-ba72c8353a88.png)

**Comment by coolchip** [comment]
Sorry... obviously I have to remove the line fill setting. But then...
![fillbelow_nofill](https://cloud.githubusercontent.com/assets/7850591/21386343/a542e772-c772-11e6-828a-0ef2453efb04.png)

If I set fill below to temperaure, the filling works fine.
