### ISSUE TITLE
Dashboards: non-monospaced fonts cause flickering on refresh

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#70323]
### 
# What went wrong?

**What happened**:

  - when a dashboard refreshes, the open filter char of the filters at the top changes to a refresh symbol. Unfortunately, it's not a monospaced font. The result is a screen flickering.
 Just checked the preview of the 10 release, and it is still there, please change that

**What did you expect to happen**:

  - 

### 
# How do we reproduce it?

**Step 1**:

- Add a parameter or two to a dashboard

**Step 2**:

- Press the refresh button

**Step 3**:

- Get annoyed

### 
# What Grafana version are you using?

10.0-preview (but all 4 major release as well)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

fedora

### User's Browser?

chrome

### Is this a Regression?

None

### Anything else to add?

I think it was changed for the worse around Grafana 7

**Comment by juanicabanas** [comment]
Hi @amnonh . 
Could you please give us further information?
A screenshot or video would really help.

Thanks!

**Comment by amnonh** [comment]
@juanicabanas have you tried? it should be visible in all dashboards containing a template variable, just press the refresh and see the flickering.
A sceenshot will not work, it's too quick to catch, I can try a video.

**Comment by evictorero** [comment]
@amnonh what do you mean by `the open filter char of the filters at the top changes to a refresh symbol`?
Can you reproduce it in a dashboard in [play.grafana.org](https://play.grafana.org/) ?
A screenshot of the portion of the dashboard that is flickering could help (if you can't record a video).

Thanks!

**Comment by amnonh** [comment]
This is the upper part of a dashboard with template parameters. As you can see, next to the template parameters filter, there's a little symbol that opens the drop-down menu.

![dashboard](https://github.com/grafana/grafana/assets/2118079/71bdf7da-370c-43bc-a6d0-1531cfd827e6)

Whenever the dashboard refresh, for example, when you press the refresh button (top right corner)

![refresh](https://github.com/grafana/grafana/assets/2118079/11ade6ac-6cc2-448c-a730-0d9eb005b7d7)

That down arrow changes for a second to the refresh symbol. Because they are not the same width,  the screen flickers

This symbol:
![image](https://github.com/grafana/grafana/assets/2118079/3210bacf-b745-4e73-8861-3ed79e6d2bad)

And this symbol:
![image](https://github.com/grafana/grafana/assets/2118079/079eb698-e927-4dd6-9513-d3271d53a6b5)

Should have the same size (width)

To reproduce, create a dashboard with a few template variables, press the refresh button, and see how the screen flickers.

**Comment by evictorero** [comment]
Thanks for the explanation, I could reproduce under certain conditions.
The template variable type must be of type `query` and the refresh must be set to `on time range change`.
This is the [dashboard](https://play.grafana.org/d/000000056/templated-dynamic-dashboard?orgId=1) I used 

https://github.com/grafana/grafana/assets/20256983/6cd43fa4-f50c-4795-a179-6a989e6799ea
