### ISSUE TITLE
Internal Tracing: Jaeger sampling params have no effect

### ISSUE THREAD

**Issue by midN** [grafana/grafana#70331]
### 
# What went wrong?

**What happened**:

  - Enabled internal tracing described [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#tracingjaeger). Set jaeger sampler_type and sampler_param to 0.1 (10%) and still received traces for 100% of the requests. Tested with env variables as well.

**What did you expect to happen**:

  - Only 1/10 requests made should have produced a trace.

### 
# How do we reproduce it?

**Step 1**:

- Enable tracing with `[tracing.opentelemetry.jaeger]` or `[tracing.jaeger]` and add `sampler_type = probabilistic` and `sampler_param = 0.1`

**Step 2**:

- Make exactly X requests to a random page/dashboard

**Step 3**:

- Check tracing backend and see exactly X traces for given requests instead of X/10 traces

### 
# What Grafana version are you using?

v9.5.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A downloaded binary

### Is this a Regression?

No

### Anything else to add?

Tried both setting params, setting params in different config options, setting ENVs `JAEGER_SAMPLER_TYPE` and so on.
The sampling rate is still 100% in all cases and traces don't have "sampling" related tags usually set by Jaeger when configured properly.

Tried setting sampler type to `const` and disabling traces with `0`, still no effect at all.

**Comment by sakjur** [comment]
Grafana 10 replaced the internals for the Jaeger tracer to instead use OpenTelemetry (see https://github.com/grafana/grafana/pull/67200), it's possible that that'd fix this.

I'll take a look and get back, but it might be worth trying upgrading and seeing if that fixes your problem 🙂

**Comment by mildwonkey** [comment]
There hasn't been any activity on this issue in a few months, so I'm going to close it. If you are still seeing an issue with the Jaeger settings, please open a new issue with a detailed reproduction case. Thanks!
