### ISSUE TITLE
Dashboards: expressions break entire panels when one of the queries used does not return data

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#70356]
### 
# What went wrong?

**What happened**:

  - I have 3 query steps (A, B and C), A and B are used in an expression, C is not. A and B return data, C does not, however, C not returning any data is causing the entire panel to break when the expression is present:

![image](https://github.com/grafana/grafana/assets/20448042/3e325d81-4bc3-4667-ab82-5204368148c0)

Removing the expression, allows the panel to load and show the data for whichever query steps do return data:

![image](https://github.com/grafana/grafana/assets/20448042/7a413643-a733-4e63-9478-6888a4bd4b50)

The above behavior also happens when the query that does not return any data is used in the expression itself.

**What did you expect to happen**:

  - For the panel to load data where data is returned and simply ignore the frames that do not return any data, regardless of whether a query is used in the expression or not

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana create a working query (A) with any datasource

**Step 2**:

- Add an expression using query A, notice how this query will work

**Step 3**:

- Create a query (B) that does not return any data, notice how adding this will break the entire panel

### 
# What Grafana version are you using?

9.4.87

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows

### User's Browser?

Edge

### Is this a Regression?

None

### Are Datasources involved?

Any datasource will repro this issue

**Comment by jcolladokuri** [comment]
Hi @kylebrandt, it is just a generic 500 error:

![image](https://github.com/grafana/grafana/assets/20448042/4cec4c46-72ec-4c82-bded-556750c66b97)

**Comment by taleena** [comment]
@kylebrandt have you been able to look into this at all from your end, or have a sense of when this might be something we can dig into?

**Comment by taleena** [comment]
@kylebrandt it looks like maybe this is now captured in https://github.com/grafana/grafana/issues/80406, is that right?

**Comment by kylebrandt** [comment]
> There was no way to pass "raw" time range which allows to pass relative time ranges and is being used by Explore. Without this prop, plugins cannot create data links with a time range in backend.
@taleena  Yes I think that is correct
