### ISSUE TITLE
[Bug] Cancelling works for every second request

### ISSUE THREAD

**Issue by jifwin** [grafana/grafana#7037]
Please include this information:
- What Grafana version are you using?
3, but probably 4 has the same issue.
- What datasource are you using?
KairosDB (but it applies to all of them)
- What OS are you running grafana on?
Linux
- What did you do?
Using backendSrv::datasourceRequest
- What was the expected result?
cancelling all previous requests
- What happened instead?
cancelling every second request

There is a bug in cancelling mechanism. Take a look at this flow:
1. Call datasourceRequest
Canceller does not exist, so nothing is cancelled
2. Call datasourceRequest (before the first finishes)
Canceller exist so canceler.resolve() is trigger. There is a race here. A new canceller is created and put into inFlightRequests before .finally blocks. The finally block is triggered for the cancelled request, but removes the new one. inFlightRequests should contain the new request, instead it is empty.

3. Call datasourceRequest
Canceller does not exist, so nothing is cancelled

In result there are two requests going on, because the second one was not cancelled.

My proposition to fix that is to remove the finally block. Cleaning up requests is not really necessary. Resolving already resolved requests does not cause any exception or error.

**Comment by torkelo** [comment]
You need to set a request ID that is unique to dashboard, look at some of the core data sources for reference, 

Think most use panel id and query as request id

**Comment by jifwin** [comment]
I am aware of that. However i'm quite convinced it is not related to that, since I'm testing it on single panel and single query. To support my thesis I include screenshots of requests and some logging I've added to find the race.

This should be reopened.
<img width="519" alt="zrzut ekranu 2016-12-27 o 22 58 04" src="https://cloud.githubusercontent.com/assets/5750402/21509323/1116c36e-cc88-11e6-8a17-aac8d8cc2d1d.png">
<img width="571" alt="zrzut ekranu 2016-12-27 o 22 55 13" src="https://cloud.githubusercontent.com/assets/5750402/21509325/1cab60ea-cc88-11e6-9438-4b8fa7997fdb.png">

**Comment by torkelo** [comment]
If you have a single panel and single query, do you issue multiple request for that query, does each request have a unique request id? No other datasource plugin has reported an issue with request cancelation. 

Can you double check that each datasource request has a unique id?

**Comment by jifwin** [comment]
Take a look at that: https://giphy.com/gifs/26ybvLKqr6GNOhP0Y .
I've recorded this with play.grafana.org using Graphite plugin. I've added "very slow" throttling to make requests hang for a while. It results in the same bug.

**Comment by torkelo** [comment]
But that looks correct, if you try to refresh (and issue new queries) before the old query has finished the old query is cancelled.

**Comment by jifwin** [comment]
Yes, but it cancels every second request. In the gif I clicked 10 times, so the previous 9 should get cancelled. In this example only 1st, 3rd, 5th and 7th are cancelled. 2nd, 4th, 6th and 8th are continuing, pending, not cancelled (these are not OPTIONS requests).

**Comment by torkelo** [comment]
ah, I see what I you mean. You seem to have identified the race condition, can you submit a PR?

**Comment by jifwin** [comment]
Yes. Are you OK with removing the finally block (cleaning seems redundant and causing the race) or would you like to solve it in other way?

**Comment by torkelo** [comment]
maybe, but wont that cause a minor leak? and if there is no cleanup completed requests will still have a canceller in the inflight lookup hash

**Comment by jifwin** [comment]
#7457

**Comment by jifwin** [comment]
Merged.
