### ISSUE TITLE
Dashboards: Only one alerts list panel on dashboard shows alerts even with mutually exclusive filters

### ISSUE THREAD

**Issue by cursedclock** [grafana/grafana#70383]
### 
# What went wrong?

**What happened**:

I have a dashboard with multiple alerts list panels, each filtering for alerts from a specific layer using label filters. Even when there is at least one alert for each layer, only one panel actually shows alerts. Furthermore this seems to be quite random, on refresh and switching to the panel edit window and back sometimes two panels show alerts and sometimes the panel that shows alerts changes. This issue has been recreated with both using the repeat option and manually creating panels for each layer+severity combination.

The following images are from the same dashboard without any modifications one before and one after switching to the edit panel page and switching back:
![alerts_1_blurred](https://github.com/grafana/grafana/assets/66743811/30f61771-d5fa-435f-89c8-5802d4e0bd48)
![alerts_2_blurred](https://github.com/grafana/grafana/assets/66743811/b7fb25df-bd90-4973-becf-6f8c254f651e)

**What did you expect to happen**:

Each panel should be populated with the appropriate alerts with the desired "layer" label.

### 
# How do we reproduce it?

**Step 1**:

- Create two alert list panels in a dashboard, each filtering for different values of a label:
```
alert 2 : {label1="X"}
alert 1 :  {label1="Y"}
```

**Step 2**:

- Make sure there currently are alert instances firing for both these label values.

**Step 3**:

- Reload dashboard and observer changes.

### 
# What Grafana version are you using?

v10.0.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Debian 10

### Is this a Regression?

None

**Comment by mellieA** [comment]
Reproduced this on Grafana v10.0.1-cloud.3.f250259e (5a30620b85) 

Created two alerts in firing status with different names
Created two panels, filter on each one on a unique alert name
Both panels are filtered by one panel's filter criteria - which makes the second panel blank if it is filtered to show a different value.
