### ISSUE TITLE
Installing 4.1.0-beta1 on Mac OSX

### ISSUE THREAD

**Issue by 0111sandesh** [grafana/grafana#7038]
How would I install 4.1.0-beta1 on Mac OSX? Brew still points to 4.0.1.

**Comment by rikkuness** [comment]
It builds okay straight off the repo on OSX, not as convenient as a brew install of course but it works just fine!

**Comment by bergquist** [comment]
Not sure about how to add beta releases to brew. But it seems like we missed to update brew to 4.0.2

**Comment by torkelo** [comment]
try:

```
brew install --HEAD grafana
```

I do not think homebrew supports pre release versions.
