### ISSUE TITLE
Grafana 10.x: Alert list panel only showing alerts after clicking on "Alert Rules" view

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#70397]
### 
# What went wrong?

**What happened**:
Alert list panel on dashboards is not showing configured alerts (even if I enable all alert state filters).
After clicking to "Home - Alerting - Alert Rules" and reopening the dashboard all alerts will be shown.
Alternatively I can click to another dashboard where alerts are visible in an Alert list pannel.

**What did you expect to happen**:

Alerts should always be shown in the panel (as configured)

1) Opening the dashboard the first time:
![SCR-20230620-qyrz](https://github.com/grafana/grafana/assets/14274103/e1af2909-0ca6-4b87-9a44-3ae9c937fc1b)

2) clicking to Alert rules
![SCR-20230620-qyyl](https://github.com/grafana/grafana/assets/14274103/f301ec85-229f-4da4-a954-29f14d67281f)

3) reopen the dashboard after clicking Alert rules:
![image](https://github.com/grafana/grafana/assets/14274103/06ce2f46-5fda-4adb-a33d-08413f756fd7)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and open a dashboard with configured "Alert list panel"

**Step 2**:

- No alerts are visible

**Step 3**:

- Click to "Home - Alerting - Alert Rules" and back to the dashboard
- Alternatively I can click to another dashboard where the alerts are visible.

**Step 4**:

- All alerts are visible afterwards.

### 
# What Grafana version are you using?

v10.0.0 (81d85ce802)

### 
### Is the bug inside a Dashboard Panel?

Panel config:

{
  "datasource": {
    "type": "datasource",
    "uid": "grafana"
  },
  "gridPos": {
    "h": 10,
    "w": 12,
    "x": 0,
    "y": 56
  },
  "id": 18,
  "options": {
    "viewMode": "list",
    "groupMode": "default",
    "groupBy": [],
    "maxItems": 10,
    "sortOrder": 3,
    "dashboardAlerts": true,
    "alertName": "",
    "alertInstanceLabelFilter": "",
    "stateFilter": {
      "firing": true,
      "pending": true,
      "noData": false,
      "normal": true,
      "error": true,
      "alerting": true,
      "execution_error": true,
      "no_data": true,
      "ok": false,
      "paused": true
    },
    "dashboardTitle": "",
    "folder": "",
    "showOptions": "current",
    "tags": []
  },
  "pluginVersion": "8.5.3",
  "title": "POOL ÜBERWACHUNG / ALARME",
  "type": "alertlist"
}

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 20.04 LTS

### User's Browser?

Safari, Chrome

### Is this a Regression?

Yes

### Are Datasources involved?

InfluxDB

**Comment by jostrasser** [comment]
Looks like that only one dashboard is affected but cannot find the root cause:

[AQUACONTROL - POOL ÜBERSICHT-1687283043215.json.zip](https://github.com/grafana/grafana/files/11804628/AQUACONTROL.-.POOL.UBERSICHT-1687283043215.json.zip)

**Comment by mellieA** [comment]
For me it seems like your test panel is working in both instances. Was this seen after an upgrade?  What happens if you import the same test dashboard into your environment - do they both work still? I'm wondering if something broke in the existing panel during the upgrade.

**Comment by jostrasser** [comment]
Hi @mellieA 

I can't say exactly after which version update the problem occurred. But yes, the panels have worked in the past.
I imported the test dashboard again and can reproduce the following:

1) the test dashboard is working after importing it
![image](https://github.com/grafana/grafana/assets/14274103/df823648-5c20-41f5-a141-cd88e956489c)

2) then I deleted the "working one" with the name "QNAP Monitoring Alerts"

3) after a browser refresh, the second one is running into the problems
![image](https://github.com/grafana/grafana/assets/14274103/261ff4c2-694c-42bc-a176-0c9d09c03aa6)

So I am able to reproduce it.
On the original dashboard I am experiencing the same issues.
If I copy a existing panel from another dashboard (as example the QNAP) then all is working fine.
If I create a new one then it is broken.

**Comment by mcoenengd** [comment]
I alos have the same issue. I added a alert list. on isert it shows data. but after a dashboard refresh (manual and automatic) it shows no data at all. Also after importing the dashboard above it has the same issue after refreshing it shows no data anymore.

**Comment by jostrasser** [comment]
FYI: no difference with [Grafana 10.0.1](https://github.com/grafana/grafana/releases/tag/v10.0.1)

**Comment by konrad147** [comment]
Hey, this issue should have been fixed in https://github.com/grafana/grafana/pull/70482 and backported to v10.0.2
