### ISSUE TITLE
[BUG] InfluxDB legend series labels don't show when query returns no records

### ISSUE THREAD

**Issue by jsheely** [grafana/grafana#7039]
When using the InfluxDB data source and you query for a data point that would return no records the legend alias labels don't show up on the graph.

I would expect the Legend >Hide series options to be honored and only hide the legend if the available options are checked.

You can see this issue in action on the playground. 
http://play.grafana.org/dashboard/db/influxdb-issue-5544

![image](https://cloud.githubusercontent.com/assets/1424946/21409240/1c00bce8-c7a7-11e6-8f3c-d5a7fc12b660.png)

![image](https://cloud.githubusercontent.com/assets/1424946/21409215/f48b8594-c7a6-11e6-8b6e-fa96f29e3e07.png)

![image](https://cloud.githubusercontent.com/assets/1424946/21409227/0576c83c-c7a7-11e6-9cb5-6b3fc73af7c6.png)

**Comment by torkelo** [comment]
This is how InfluxDB works, it returns no meta information when there is no data

**Comment by jsheely** [comment]
Doesn't mean that grafana can't be smart about it. We know what the labels are because we entered them in grafana. 

What information do we not have to just display the legend? If you get no information why can't we presume nulls as zero?

**Comment by torkelo** [comment]
A singe InfluxDB query can return any number if series, with any number of tags and tag values, Grafana can't know what the series name should be (in the majority of cases)

**Comment by jsheely** [comment]
Fair enough. There are scenarios where the values will be unknown. But
there are simple scenarios where it can work.

I don't feel like it's an all or nothing. We can do a best effort using the
Alias. Which will provide many people with the desire effect.

If the legend is solely based on the results then we could be out of luck
but at least it's a reasonable degradation.
