### ISSUE TITLE
integral() function does not work in InfluxDB Datasource (flux)

### ISSUE THREAD

**Issue by Denis1983** [grafana/grafana#70402]
### 
# What went wrong?

**What happened**:

integral() function does not work in InfluxDB Datasource (flux)

**What did you expect to happen**:

integral() function works in InfluxDB Datasource (flux)

### 
# How do we reproduce it?

**Step 1**:

Create a query InfluxDB (flux)
Example:
from(bucket: "smarthome")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "power_consumption_solar")
  |> filter(fn: (r) => r["_field"] == "value")
  |> integral(unit: 1h)

**Step 2**:

integral is not calculated.

### 
# What Grafana version are you using?

10.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### Is this a Regression?

None

### Are Datasources involved?

InfluxDB

### Anything else to add?

It works in the Data Explorer in the InfluxDB v2.6.1

**Comment by itsmylife** [comment]
I created a separate issue and closing this since the integral function is working. 
https://github.com/grafana/grafana/issues/80941
