### ISSUE TITLE
Azure AD B2C Oauth2 endpoint not detected as version 2

### ISSUE THREAD

**Issue by astromasoud** [grafana/grafana#70414]
### 
# What went wrong?

**What happened**:

Most probably related to Fixes: #56667 

Returns an error message for Azure B2C URLs that the endpoint is not v2.0:

> Login Failed
AzureAD OAuth: version 1.0 is not supported. Please ensure the auth_url and token_url are set to the v2.0 endpoints.

Config:

> [auth.azuread]
name = Azure AD
icon = microsoft
enabled = true
allow_sign_up = true
client_id = (Client ID)
client_secret = (Client Secret)
scopes = openid email profile (client_id)
auth_url = https://(Tenant).b2clogin.com/(Tenant).onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/authorize
token_url = https://(Tenant).b2clogin.com/(Tenant).onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/token
;tls_skip_verify_insecure = true
;email_attribute_path = emails[0]

I've explained it in detail here: https://community.grafana.com/t/azure-ad-b2c-oauth2-version-error/89956

**What did you expect to happen**:

 As the URLs for B2C endpoints are already v2.0 and as Grafana's debug logs are reporting that it's getting the token, it should proceed the login but this error prevents it.

### 
# How do we reproduce it?

**Step 1**:

- Create an application on Azure B2C and set the redirect URL as https://grafana.somedomaine.com/login/azuread

**Step 2**:

- Config Grafana for Azure AD under `[auth.azuread]` using the B2C endpoints and enable it

**Step 3**:

- On the login page click the Azure login
- Proceed the login on Azure B2C page
- Get redirected to https://grafana.somedomaine.com/login/azuread
- An error appears on the page and in debug logs with this message:
- > Login Failed
AzureAD OAuth: version 1.0 is not supported. Please ensure the auth_url and token_url are set to the v2.0 endpoints.

### 
# What Grafana version are you using?

v10.0.0 (81d85ce802)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 20.04

### User's Browser?

Chrome Version 114.0.5735.134 (Official Build) (64-bit)

### Is this a Regression?

None

**Comment by astromasoud** [comment]
As suggested and tested under the community thread, currently using the `[auth.generic_oauth]` instead of `[auth.azuread]` is a workaround as this version-check is not enforced in that method.
https://community.grafana.com/t/azure-ad-b2c-oauth2-version-error/89956

**Comment by mellieA** [comment]
Related to https://github.com/grafana/grafana/pull/58088

**Comment by Jguer** [comment]
Hey @astromasoud , thanks for reporting this, we'll see if we can provide better support for azure B2C in auth.azuread 

leaving this documentation here for now:
https://learn.microsoft.com/en-us/azure/active-directory-b2c/application-types
https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant

**Comment by Jguer** [comment]
Hi @astromasoud can you share a censored version of the jwt token claims present in the id token of your azure B2C app?

**Comment by Jguer** [comment]
according to the documentation https://learn.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#claims , it seems at least `oid` and `tid` are not shipped in these tokens. This would make it incompatible with the implementation of the `auth.azure_ad` provider.

If the claims described in the documentation are the only ones available, it would be advisable to use generic_oauth instead. 

Closing this issue. Will reopen if the necessary claims are included in the token
