### ISSUE TITLE
[Feature request] Support splitting tag for alias

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7041]
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
centOS

Suppose there are 3 legends on the graph grouped by hostname and the hostnames are `server001.example.com`, `server002.example.com` and `server003.example.com`. When I set `ALIAS BY` to `$tag_hostname` it shows the servers' full name, however, I would like to use `server001`, `server002` and `server003` as alias names instead. Please let me know if it is doable, if not, please consider to add this feature, e.g., making it by using `$tag_hostname[1]` or `[[tag_hostname.1]]`

**Comment by torkelo** [comment]
For this you need to change how you store data in ES,  there is a templating issue that requests a syntax for regex transforms which could solve this if grafana ever implements it, so there is hope, but that feature is not on any roadmap
