### ISSUE TITLE
Explore: add documentation for query parameters and URL schema

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#70432]
With https://github.com/grafana/grafana/pull/69692 we introduced strong versioning for URL schemas. We should document explicitly and define a contract on what's expected to be in the URL and how to generate them in case external tools rely on that logic.

**Comment by gelicia** [comment]
What's expected from schema version 0 and schema version 1. The schema is already defined, so it's a matter of getting that copied over and adding some descriptive doucmentation

**Comment by GrafanaWriter** [comment]
Hi @Elfo404 - Moving this to Backlog on the Docs Team board as the issue is three weeks old.
