### ISSUE TITLE
[Bug] - ElasticSearch Data Source Month off-by-one in 4.1.0beta1

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#7044]
Running Grafana 4.1.0beta1 with the ElasticSearch Datasource against 2.x or 5.x data sources on Linux.  I get an off-by-one month in the index check when clicking "Save & Test".

Index Pattern is: [security-ashburn-]YYYY.MM.DD

UTC Current Date is 2016-12-22, I am getting attempts to verify 2016.11.22?

```
{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"security-ashburn-2016.11.22","index_uuid":"_na_","index":"security-ashburn-2016.11.22"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"security-ashburn-2016.11.22","index_uuid":"_na_","index":"security-ashburn-2016.11.22"}
```

**Comment by torkelo** [comment]
Strange, unable to replicate it here. The month used in the index is the current one. Sure the date is correct on the computer your running the browser on?

**Comment by torkelo** [comment]
it looks like it's using the time range of the last dashboard you visited.

**Comment by fabianlee** [comment]
I have the same issue as the original poster.  The last dashboard I visited has the date range set to "Last 2 days", so when I try to create an ElasticSearch index using a daily pattern it tries to validate an index from 2 days ago (which does not exist).

The workaround is to go back to the dashboard and set the date range to something like "Last 5 minutes", then go back to the data source creation page.
