### ISSUE TITLE
Grafana Edit Panel: Label "Resample to" overflows out of the container

### ISSUE THREAD

**Issue by neel1996** [grafana/grafana#70469]
### 
# What went wrong?

The "Resample to" label "Edit panel" page overflows out of the parent container

![image](https://github.com/grafana/grafana/assets/47709856/e4f6fa9a-bb43-4efa-8b45-7587de315f76)

### 
# How do we reproduce it?

- Go to "Home -> Dashboard -> New Dashboard -> Add visualization". This will open the "Edit panel" page
- Choose a data source (Loki was the data source selected when I spotted this bug)
- Click on `+ Expression` CTA to add a new expression
- Select **Resample** from the "**Operation**" dropdown

### 
# What Grafana version are you using?

Grafana v10.0.0 (81d85ce802)

### 
### Grafana Platform?

Docker

### User's OS?

Windows 11

### User's Browser?

Chrome

### Is this a Regression?

None

**Comment by usmangt** [comment]
Hi @neel1996,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine while using Grafana version 10.

I will forward this issue to our Engineers so that they can have a look and analyze it.

**Comment by neel1996** [comment]
@usmangt Thanks for the update. I have contributed to grafana datasource screen before and have some context around it. If I get bandwidth, I'll try to fix the bug and raise a PR for the same

**Comment by neel1996** [comment]
A new PR #71011 has been raised to fix this issue

**Comment by itsmylife** [comment]
PR is approved and merged. Thanks for the contribution!
