### ISSUE TITLE
Grafana InfluxDB Flux query `buckets()` doesn't return all buckets

### ISSUE THREAD

**Issue by palto42** [grafana/grafana#70464]
### 
# What went wrong?

**What happened**:

  -  I used `buckets()` in a dynamic variable and after adding some more buckets in InfluxDB, I found that the function doesn't return all buckets from the connected database. I can access all the buckets directly in the Grafana flux queries though.
  -  I created a test dashboard using teh visualization `table` and run the buckets()  query.  It lists the first 18 buckets from alphabetical order. If I add or delete buckets in InfluxDB, the returned list in Grafana is still maximum 18.
    ![image](https://github.com/grafana/grafana/assets/12280188/1e2d9bf5-d02a-4b0b-a7e1-ab4a58cc3597)

**What did you expect to happen**:

  -  `buckets()` should return the full list of available buckets like directly in InfluxDB
    ![image](https://github.com/grafana/grafana/assets/12280188/3e4befba-e378-4b03-8b5e-0896a3027683)

### 
# How do we reproduce it?

1. Configure more than 18 buckets in InfluxDB
2. Open Grafana and configure a dashboard panel using  "table" visualization
3. Chose the flux datasource and run query `buckets()
4. Compare the reported list of buckets with the actually configured buckets in InfluxDB 
5. Change the name of a bucket listed in the Grafana dashboard to move it at the end of the alphabetical list (e.g. add a prefix `X_`), then run the query in Grafana again to confirm that the list of 18 buckets has changed accordingly

### 
# What Grafana version are you using?

Grafana v10.0.0 (81d85ce802)

### 
### Grafana Platform?

Docker

### Are Datasources involved?

InfluxDB v2.6.1

**Comment by palto42** [comment]
A similar issue was reported 2 years ago in #32744, this user got 78 out of 95 buckets in the result. That issue was closed due to information missing/inactivity.

**Comment by gpinkos** [comment]
Using InfluxDB OSS 2.6.1 and Grafana OSS 9.4.3

I created 20 buckets and all appeared in Grafana:
![image](https://github.com/grafana/grafana/assets/97072938/6802bdf3-c984-45d0-8ce0-dad02e4f3ab2)

I then changed the name of bucket01 to x_bucket01 in InfluxDB (and OK'd past the warning...note that I did not have any data stored in bucket01):
![image](https://github.com/grafana/grafana/assets/97072938/8a0e6c03-6b1e-449e-9c4d-540f035f1ed4)

![image](https://github.com/grafana/grafana/assets/97072938/07e682ef-2163-4b65-88b0-407afaef3d64)

and here is the same query in Grafana:
![image](https://github.com/grafana/grafana/assets/97072938/2399e82d-78b1-4988-ba13-52e528af1557)

I do not see any issue here with Grafana v9.4.3.  I plan to update to v10 over the coming days and will see if the described issue appears.

**Comment by palto42** [comment]
Updated to Grafana version 10.0.1 and still same issue.

**Comment by LudoVio** [comment]
I cannot reproduce this issue on any version.

try this suggestion from @gabor 

> try running this query in the influxdb native ui and see if it shows all the buckets or not:
>
> * go to the influxdb native ui
> *  go to Explore mode there
> *  click on script editor to write a raw query
> *  enter buckets()
> *  choose the Table visualization
> *  [submit] the query
> *  check if you can see all the buckets or not

Are you able to reproduce the issue using a basic setup with local influxdb and grafana via docker ?
The issues might be related to your infra/setup. Maybe some authorization flag on the buckets.

**Comment by palto42** [comment]
@LudoVio I tried this already and it provided the full list, but the reason was that the login I use for the InfluxDB native UI is not the same token based access as from Grafana.

I now tried the flux query `bucket()` from CLI using the token based access and see that same behaviour as in Grafane, which means that this is an issue with InfluxDB related to the token somehow. 

```console
docker exec -it influxdb2 influx query -t "$INFLUX_TOKEN" -o home "buckets()"
```

It's still not fully clear to my why the flux query with the token used in Grafane is not providing the full list of buckets, but since it's now clear that this is no Grafane issue, I'm closing it here,

**Comment by palto42** [comment]
I found that the InfluxDB access token required read permission for "Other Resources" "All Orgs" to provide the complete list of all buckets. Not sure if this is expected behavior, but at least I now know how to get it working.

![image](https://github.com/grafana/grafana/assets/12280188/a6e2038e-0566-40b1-823d-5cf22c709b9f)
