### ISSUE TITLE
Grafana 4.0.2 Alerting not working with templated datasource

### ISSUE THREAD

**Issue by yellowmegaman** [grafana/grafana#7047]
Hello!

- What Grafana version are you using? `4.0.2-1481203731`
- What datasource are you using? `influxdb`
- What OS are you running grafana on? `debian jessie`
- What did you do? `Enabled alerting`
- What was the expected result? `Working alerting`
- What happened instead? `Failed alerting`

I'm using templated datasource and got in logs:

```
t=2016-12-22T13:36:40+0300 lvl=eror msg="Failed to test rule" logger=context userId=1 orgId=1 uname=admin error="Data source not found"
t=2016-12-22T13:36:40+0300 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alerts/test status=500 remote_addr=127.0.0.1 time_ms=2ns size=33
```

after trying to test-run alerts. Switching to non-templated datasource brings back alerts.

P.S. Datasource template configured as mentioned here: https://github.com/grafana/grafana/issues/816#issuecomment-215504832

**Comment by yellowmegaman** [comment]
Same thing in Grafana v4.1 beta

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/6557
