### ISSUE TITLE
[Feature request] render graph image and notification API

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7048]
If this method is provides as Web API, it might be useful.
https://github.com/grafana/grafana/blob/v4.1.0-beta1/pkg/services/alerting/notifier.go#L77

The use case:
- Get alert notification
- Want to know current status
- Request new graph image and notification from chat (like https://github.com/stephenyeargin/hubot-grafana)
- If the server status becomes healthy, resolve the alert at PD

**Comment by torkelo** [comment]
you can get current status of alert via alerts API (check network call when visiting alert list page), there is also an api for alert state history. 

There is also a render panel api. Can you describe in detail what it is your missing?

**Comment by mtanda** [comment]
I want a handy API to render the panel and upload the captured image to S3.
Currently, the render API itself doesn't upload the image to S3.
I'm not sure which is better, "add option to current render API", or "add new API".

Anyway, current chat integration require S3 access key, it is not secure.
If Grafana provide such API, we can use IAM role, it becomes more secure.
https://github.com/grafana/grafana/issues/6985

**Comment by torkelo** [comment]
but what does this request have to do with #6985 ? 

I do agree that a general "share panel" to slack/hipchat etc integration would be great, but that has nothing to do with alerting but more an enhancement of current share features

**Comment by torkelo** [comment]
closing this due to similar to https://github.com/grafana/grafana/issues/7076

**Comment by Gelob** [comment]
Also related to https://github.com/grafana/grafana/issues/6451

**Comment by mtanda** [comment]
@torkelo Sorry for confused you.
Actually, https://github.com/grafana/grafana/issues/6985 is not necessary for this feature.

When I look the chat bot implementation, I think using access key is not secure.
https://github.com/stephenyeargin/hubot-grafana/blob/v1.4.9/src/grafana.coffee#L273-L281

If the Grafana provide API for uploading image to S3, chat bot can use the API, and reduce the risk to leak the access key.
And if Grafana use IAM role, it becomes more secure.
Providing the API is pre-condition for avoid to use access key.

If https://github.com/grafana/grafana/issues/7076 is provided as web api, it will cover my use case.

**Comment by torkelo** [comment]
Not sure what you mean access key, are you talking a out hubot grafana s3 config, can't hubot grafana use IAM? 

You want an api to render and upload a panel? Not sure how that feature relates to the alerting notifications & alert status mentioned in the issue description. 

I think such an api could be made part of the general share feature I linked to

**Comment by mtanda** [comment]
Sorry again.
hubot can use IAM role if it is running on EC2.
I think the Grafana provide API and hubot use it is better.
But using IAM role is out of scope for this issue.

So, please ignore following part. It confuse you...
> Not sure how that feature relates to the alerting notifications & alert status mentioned in the issue description.

This API is my requirement.
> You want an api to render and upload a panel?

My requirement is little bit similar to https://github.com/grafana/grafana/issues/6685 .
By repeating the notification, ops engineer can view latest graph, and predict the alert will be continued or resolved.

But repeating notification is very noisy, so I want to add update button for the alert notification message (in Slack).
When ops engineer click the update button, Grafana render the latest graph, upload image, and then post new message.
To implement this flow, I want handy API to do that by one API call.

This is what I want to do.

**Comment by torkelo** [comment]
So you want a button/api that resends a new notification? (Rerenders panel and sends out notification). Is that not the same as  https://github.com/grafana/grafana/issues/7076  (or simiar)

**Comment by mtanda** [comment]
Yes, that's right.
