### ISSUE TITLE
Explore: URL/state management refactoring follow-up

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#70486]
The following are follow-up items we identified when completing the work for Explore's URL state management refactoring:
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/69686
- [ ] https://github.com/grafana/grafana/issues/69689
- [ ] https://github.com/grafana/grafana/issues/69690
- [ ] https://github.com/grafana/grafana/issues/70432
- [ ] https://github.com/grafana/grafana/issues/70427
- [ ] https://github.com/grafana/grafana/issues/74687
```

**Comment by ifrost** [comment]
Should we also do better error handling here? I'm thinking about the case when a URL with a non-existing data source is loaded. We can show a message explaining why the URL is invalid.
