### ISSUE TITLE
cannot get username when authenticating with proxy-auth and apache/mod_auth_mellon 

### ISSUE THREAD

**Issue by metebilgin** [grafana/grafana#7049]
Grafana: 4.1.0-1482230757beta1
Grafana: 4.0.2

I configured grafana and apache with mod_auth_mellon to use saml login. I can login but name, username and email getting null.

Apache: conf.d/grafana.conf
LoadModule auth_mellon_module modules/mod_auth_mellon.so
<VirtualHost graf.example.com:80>
        RequestHeader set X-WEBAUTH-USER "%{MELLON_username}e"
        ServerName graf.example.com
        ProxyPassInterpolateEnv On
        ProxyPass /login/saml !
        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000/
        ProxyRequests Off
        <Location /login>
                MellonEnable "auth"
                #MellonSecureCookie Off
                MellonMergeEnvVars On
                MellonCookieDomain graf.example.com
                MellonCookiePath /
                MellonEndpointPath "/login/saml"
                MellonDefaultLoginPath "/"
                MellonNoCookieErrorPage "http://example.com/no_cookie.html"
                MellonSPentityId "http://graf.example.com"
                MellonSPPrivateKeyFile /etc/httpd/mellon/http_graf.example.com.key
                MellonSPCertFile /etc/httpd/mellon/http_graf.example.com.cert
                MellonIdPMetadataFile /etc/httpd/mellon/idp-metadata.xml
                MellonAuthnContextClassRef "urn:federation:authentication:windows"
                MellonAuthnContextClassRef "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
        </Location>
</VirtualHost>

"/etc/grafana/grafana.ini"
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
;ldap_sync_ttl = 600
;whitelist = 192.168.1.1, 192.168.2.1

**Comment by torkelo** [comment]
auth proxy currently only syncs one property (username or email). 

There is an issue to extend this:
https://github.com/grafana/grafana/issues/6083

**Comment by metebilgin** [comment]
When logged in, in profile section is like the picture.
![image](https://cloud.githubusercontent.com/assets/1327137/21449997/8c35a9a6-c8fb-11e6-9d3a-f938596d71fc.png)
