### ISSUE TITLE
[Feature Request] - Show legend labels for influxDB when no meta data is received

### ISSUE THREAD

**Issue by jsheely** [grafana/grafana#7050]
I would very much like the ability while using InfluxDB to have the legend labels visible even when InfluxDB returns no data. 

See reference to: https://github.com/grafana/grafana/issues/7039

Without the legend labels it makes the graph difficult to convey its purpose without seeing what it is suppose to be showing.

I am also open to any suggestions on other ways I could get this effect now in the product using series overrides or annotations.

**Comment by torkelo** [comment]
Closing this as it has to be solved in InfluxDB
