### ISSUE TITLE
Tooltip: behaviour of `show` property

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#70514]
Following some changes introduced in https://github.com/grafana/grafana/pull/54586 the behaviour of the `show` property seems to have changed.

The previous behaviour (9.1.x) was as follows

| value | behaviour |
|---|---|
|`show={undefined}` | tooltip shown on hover, hidden when no longer hovering |
| `show={true}` | tooltip is always shown, never hidden |
| `show={false}` | tooltip is never shown (effectively disabled) |

We're currently using it in https://github.com/grafana/grafana/blob/baf83e241e34889bdf0c9526f29c0e77827f112b/public/app/features/alerting/unified/components/rule-editor/query-and-alert-condition/QueryAndExpressionsStep.tsx#L298 and have noticed that hovering over the button shows the tooltip despite passing `show={false}`.

You can play around with the current behavior here https://developers.grafana.com/ui/latest/index.html?path=/story/overlays-tooltip--basic&args=show:true where `show` acts more like a `defaultShow` property but hovering over it makes it disappear.

There are several ways to proceed here, I've no particular opinion so instead I'm writing down my findings to defer the decision to the owners of the `Tooltip` component :)

## 1. Implement previous behaviour

This seems pretty straight-forward, `react-popper-tooltip` allows passing `null` to the `trigger` property so we can replicate the old behaviour that way if `show` is a boolean value but not `undefined`.

## 2. Remove support for the prop

After some code digging in Grafana (admittedly I haven't checked any other consumers of `@grafana/ui`) the component linked above seems to be the _only_ instance where we use the `Tooltip` component with the `show` property so we can also think about remove support for it altogether and make the necessary changes in the `QueryAndExpressions` step to conditionally wrap with `Tooltip`.

This is technically a breaking change.

## 3. Do nothing

We can also choose to do nothing, we'll make the required changes and explicitly state that the behaviour of `show` is just to show the tooltip by default when it's `true`, any other value like `false` or `undefined` has no impact on the component's behaviour.

I'm tagging a few folks who made changes to it last – apologies if I'm adding noise to your GitHub notifications, feel free to tag other folks :)

**Comment by eledobleefe** [comment]
We have a discussion pendant to evaluate if there is a need for a new prop that manages the behaviour we want. We will keep this issue open in Saga Design System backlog.
