### ISSUE TITLE
[Feature request] Option to send notifications about alerting state periodically until OK

### ISSUE THREAD

**Issue by FZambia** [grafana/grafana#7053]
Hello, thanks a lot for Grafana - it's just a masterpiece.

- What Grafana version are you using?
4.0.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Linux

- What did you do?
We are sending alert notifications via webhook

Our internal monitoring system works with alerts this way: it receives alert, displays it, then after some time it clears alerts which have not been reconfirmed (in reasonable interval). 

Grafana sends one notification via webhook when metric enters alerting state, then one notification on OK state. So while alerting state lasts for several hours alert in our alert system only lives (displayed) for short amount of time and then disappears. 

What we ask here is an option to send alerting state notification every time rule evaluated and firing is `true`. This will allow to reconfirm alert we already display and prevent it from being cleared as non-actual. 

This can also be useful if our alert system missed first alert webhook for some reason - it will receive it again after 1min for example.

This is not very suitable for email notifications of course, but as this is optional and off by default - users can decide which behaviour they want.

P.S. Sorry, I skipped several issue template options as they do not fit well for my request.

**Comment by torkelo** [comment]
This sounds like a good idea, 

closing this as I think it's the same as https://github.com/grafana/grafana/issues/6685

**Comment by kaushalmodh** [comment]
I am using grafana v4.2.0 and prometheus v1.6.0 .
I have created webhook to scale up the container if cpu usage is >70%.
when this condition satisfies...it trigger alert notification which scale up container....works fine...
but when cpu become less than 70%  then it will changed state to OK....that time also webhook calls...
I dont want to call webhook when state changes from  Alerting---->OK
Only call webhook when state change from OK-->Alerting.
Please reply asap

**Comment by torkelo** [comment]
@kaushalmodh there is a feature request for that: https://github.com/grafana/grafana/issues/6696
