### ISSUE TITLE
Metric query: Broken suggestions system for Prometheus datasource

### ISSUE THREAD

**Issue by ohmcm** [grafana/grafana#70562]
### 
# What went wrong?

**What happened**:

  - Grafana version after 6.1.6 break the suggestions system for query with selectors

**What did you expect to happen**:

  - Suggestion system should be able to suggest the query even with selector.

Grafana 10 from the [Demo](https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m&editPanel=1)
![image](https://github.com/grafana/grafana/assets/96239195/1812b113-ebcb-4eb2-a81a-6710082c139f)

Grafana 6.1.6 from my local install
![image](https://github.com/grafana/grafana/assets/96239195/6612d872-69fe-4ee2-9cf8-bf18cb47ab4c)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a new dashboard with Prometheus as datasource and with node_exporter setup so the query below is available. (But, really.. you can try with any other query)

**Step 2**:

- try `sum by(mode)(irate(node_cpu_second{job="node", instance=~"$node:.*", mode!="idle"}[5m])) > 0` query
 now try the query suggestion for the `node_cpu_second` (Ctrl + Spacebar)
  

**Step 3**:

- You'll see "No suggestions" for any version after 6.1.6

### 
# What Grafana version are you using?

Any of the version after 6.1.6

### 
### Grafana Platform?

Docker

### User's OS?

-

### User's Browser?

-

### Is this a Regression?

Yes

### Are Datasources involved?

Prometheus

### Anything else to add?

It amazes me how this has been broken for so long but no one really cares or has a look at this issue.. or did I do something wrong and something changed from 6.1.6 to the current version. Is there a newer better way for Grafana to suggest the query for the user?

How do you all write the new query with Grafana for so long without a suggestions system?

**Comment by usmangt** [comment]
Hi @ohmcm,

Thanks for opening this issue.

I see that it does not show the suggestions as you explained. But I am not sure what changed from version 6.x to 10.x

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by gtk-grafana** [comment]
It looks as though the autocomplete isn't working when the cursor is at the end of the metric, the application currently doesn't know anything about what text is selected.
<img width="1194" alt="image" src="https://github.com/grafana/grafana/assets/109082771/8051227d-ba38-4446-af6e-fdbdbe90f40c">

As a workaround if you delete the existing metric: 
<img width="1082" alt="image" src="https://github.com/grafana/grafana/assets/109082771/82e9711f-ade8-4019-8c2a-ca191af2f463">

or just place the cursor at the start of the metric:
<img width="1404" alt="image" src="https://github.com/grafana/grafana/assets/109082771/c0c2aad9-6aa4-4c9e-9740-8e00959ed13f">

Then the autocomplete should return results.

I'll take a look to see if we can use the start of selected text as the cursor location before parsing promQL

**Comment by gtk-grafana** [comment]
Interestingly, Monaco takes the selected text into consideration when searching available matches, and will return matching results that (fuzzily) match the current text selection, and also keep in mind that it can only return labels which are available for the current query, so sometimes you still need to delete labels before you can get autocomplete results that you are looking for, all this means is that selecting text will still give you different results then simply placing the cursor at the start of a metric, or deleting what you are planning on replacing.
Selecting the `node_cpu_seconds_total` metric
<img width="1273" alt="image" src="https://github.com/grafana/grafana/assets/109082771/69b96366-44f9-4b1d-b723-51fc28948dd5">

Placing the cursor before the `node_cpu_seconds_total` metric
<img width="944" alt="image" src="https://github.com/grafana/grafana/assets/109082771/c76c1af9-b2db-4310-a873-cb8462b57bac">

**Comment by ohmcm** [comment]
Also found this very similar issue reported

https://github.com/grafana/grafana/issues/44522

**Comment by Igorgro** [comment]
Mys suggestion is to use the language server I referenced in mentioned issue. It has much more powerful autocomple than the current grafana query editor and has no all the drawbacks from this issue. The only downside is it is currently unmaintained, but this should not be a problem for grafana team, who can continue it's development.

**Comment by gtk-grafana** [comment]
@ohmcm Thanks for reporting this, a fix has been merged into 10.1.x.

**Comment by ohmcm** [comment]
@gtk-grafana Thank you very much for the quick fix, sir.
