### ISSUE TITLE
Overwrite flag appears to be ignored in HTTP API (v3.1.1)

### ISSUE THREAD

**Issue by mshillinger** [grafana/grafana#7056]
Runnning Grafana 3.1.1 on Ubuntu 16.04 against Prometheus

When updating a dashboard via the HTTP API, I am providing json where "overwrite"=false and the dashboard ID and title match an existing dashboard.  Based on the API documentation, I would expect to get a 412 response code.  Instead I get a 200 and the existing dashboard is replaced.

Seems like a bug to me. Perhaps I am misreading the API, or the API docs are not accurate?

**Comment by torkelo** [comment]
It depends on the version property and I'd property, the overwrite flag is for scenarios when another dashboard with another ID but same title exists, or when same dashboard id exists but with newer version (meaning someone else has updated dashboard),  

So if you try to post dashboard with id and same version as in db, then it will update dashboard even when overwrite is false
