### ISSUE TITLE
Explore: Datasource picker overflows in certain scenarios

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#70598]
Not sure if this is an issue we would want to address here, but I think the calculations on when to split into overflow actions gets interfered with. Under some widths, the right "widen pane" button gets cut off by the database picker. This doesn't happen in play under the same width, it splits to the kebab menu as expected. 
![issue1](https://github.com/grafana/grafana/assets/1533128/19a12cf7-bf06-4ef9-afbf-dc8b278adebb)

This is an issue both here and play, but the following is a very minor, edge case UI bug I noticed
1. In split view with the secondary action kebab button on both panes, open right pane's kebab menu
2. On the left pane, click the kebab menu and select close
3. In this single pane view, click split. The left pane's kebab menu will initialize as open

_Originally posted by @gelicia in https://github.com/grafana/grafana/issues/70396#issuecomment-1601403961_

the new DS picker behaves weirdly in Explore when resizing panes. we should investigate more on why that is happening and how to fix this.

**Comment by harisrozajac** [comment]
@Elfo404 I wasn't able to reproduce this. Does this happen only at a specific width?

**Comment by gelicia** [comment]
I can't repro it anymore either. I'm fine closing this.
