### ISSUE TITLE
Silences: after restarting, Silences are gone

### ISSUE THREAD

**Issue by fechmistrz** [grafana/grafana#70593]
### 
# What went wrong?

**What happened**:

  - I am using self-hosted Grafana 9.5.2 with MySQL database version 5.7.41 to store persistent data (like alerts). I have multiple orgs configured there and created Silences for some of them. After restarting it, Alerts and Orgs configuration is present (as expected) but all Silences are gone.

**What did you expect to happen**:

  - Silences should be stored (persistently) in database.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create Silence.

**Step 2**:

- Now list all active Silences and verify that one from step 1 is present.

**Step 3**:

- Wait few minutes and restart Docker container with Grafana. Silence is no longer listed.

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Arch Linux

### Is this a Regression?

None

**Comment by fechmistrz** [comment]
I am aware of https://github.com/grafana/grafana/issues/36099 and https://github.com/grafana/grafana/pull/36808 and https://github.com/grafana/grafana/commit/39a3bb8a1c9a45a0d256d5f909cb5d79ff7bfa8b.

If it helps, here are tables that I see: alert; alert_configuration; alert_configuration_history; alert_image; alert_instance; alert_notification; alert_notification_state; alert_rule; alert_rule_tag; alert_rule_version; annotation; annotation_tag; api_key; builtin_role; cache_data; correlation; dashboard; dashboard_acl; dashboard_provisioning; dashboard_public; dashboard_snapshot; dashboard_tag; dashboard_version; data_keys; data_source; entity_event; file; file_meta; folder; kv_store; library_element; library_element_connection; login_attempt; migration_log; ngalert_configuration; org; org_user; permission; playlist; playlist_item; plugin_setting; preferences; provenance_type; query_history; query_history_star; quota; role; secrets; seed_assignment; server_lock; session; short_url; star; tag; team; team_member; team_role; temp_user; test_data; user; user_auth; user_auth_token; user_role.

If I am wrong and silences are written to the database, which table stores them?

**Comment by fechmistrz** [comment]
I asked the same question on Grafana forums and got the answer: https://community.grafana.com/t/which-grafana-database-table-stores-silences-data/90210

> Apologies, I stand corrected. I forgot about that pull request. Silences are stored in a table called kv_store.

**Comment by thomaspetit** [comment]
> I asked the same question on Grafana forums and got the answer: https://community.grafana.com/t/which-grafana-database-table-stores-silences-data/90210
> 
> > Apologies, I stand corrected. I forgot about that pull request. Silences are stored in a table called kv_store.

@fechmistrz how did you resolve the issue.. we're currently seeing a similar issues where we have Grafana running in HA where one instance is connecting properly to the DB and loading the silenced alerts while the other one doesn't.

**Comment by fechmistrz** [comment]
@thomaspetit I no longer work for a company that faced this issue and can't verify what's in my "kv_store" table.

We were self-hosting Grafana through ECS in AWS and we noticed that Silences appear/disappear if the instance count is at least 2, depending on which instance we have been connected to by load balancer. Even worse, if all instances have been recycled, the alerts disappeared completely.

I think we have reduced the instance count to 1 and (as an ugly workaround...) stored Silences definition outside Grafana. Then they were enforced periodically using Grafana API calls: I believe that in 9.4.x (maybe earlier too) you can list existing with a GET request and then POST whatever you believe should be there but is not listed. Ugly, I know.

I am not sure what the final solution was for reasons explained in 1st sentence.

**Comment by thomaspetit** [comment]
It is actually rather simple.. I found the solution here:
https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/

It turns out the DB is filled up but it doesn’t seem to be used (except for maybe backup purposes?). You need to configure Grafana to allow gossip between the instances. The helm chart has support for it (but don’t forget to also set the grafana.ini too.
