### ISSUE TITLE
[BUG] Alerting: i/o timeout when using S3

### ISSUE THREAD

**Issue by wilshire461** [grafana/grafana#7059]
- What Grafana version are you using?

Version 4.0.2

- What datasource are you using?

InfluxDB 1.1.0

- What OS are you running grafana on?

RH 7.3 : Kernel 3.10.0-514.el7.x86_64

- What did you do?

I setup an alert that would contact a slack channel via slack webhook to alert us, with a externally hosted screenshot from S3.

- What was the expected result?

That we would receive a slack message with screenshot of graph.

- What happened instead?

When the alert threshold is crossed we can see in the grafana log the following as it fails to fire the webhook completely.

```
t=2016-12-22T13:38:01-0700 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=1 sent count=1
t=2016-12-22T13:38:01-0700 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/summit-gateway-network-stats?&panelId=1"
t=2016-12-22T13:38:32-0700 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Post https://grafana-alert-charts.s3-website-us-west-2.amazonaws.com/lTsvuS4zw8GppcXp8Xuy.png?uploads: dial tcp 52.218.160.55:443: i/o timeout"
t=2016-12-22T13:38:32-0700 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=1 isDefault=true
t=2016-12-22T13:38:32-0700 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Grafana Alerts"
t=2016-12-22T13:38:32-0700 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook="Grafana Alerts"```

**Comment by torkelo** [comment]
make sure the server where you run grafana-server on has access to s3
