### ISSUE TITLE
[Feature request] Support template variables in alert queries

### ISSUE THREAD

**Issue by clhlc** [grafana/grafana#7060]
Hi，now graphite4.0.2 is not support template variables in alert queries， but there are a lot of grafana grafs used templates which is very useful and perfect. So support template variables in alert queries is useful and do not change grafs used now. thx.

![image](https://cloud.githubusercontent.com/assets/10704095/21445941/36494d04-c8fb-11e6-936c-31dfe93a8313.png)

**Comment by torkelo** [comment]
This is not on the road map currently, we have yet to figure out a way to do it that would be intuitive and not so confusing, and it would be very complicated to implement as well. So do not expect it  any time soon. 

Closing this as it is a duplicate

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/6557
