### ISSUE TITLE
[Bug] Every day at midnight an alert is generated

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#7061]
Please include this information:
- What Grafana version are you using?
4.0.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOs 7

- What did you do?
Configured an alert in a trafic chart

- What was the expected result?
No error and no notification alert

- What happened instead?
Every day at 00h00 we received a notification about the alert in our slack channel with an error:
"
Error message
tsdb.HandleRequest() error Request failed status: 500 INTERNAL SERVER ERROR
"

I don't have this error in others charts only in this chart.

![grafana_slack_mignight](https://cloud.githubusercontent.com/assets/2543381/21449027/38af4cea-c8e9-11e6-8049-baf2023545df.png)

**Comment by torkelo** [comment]
looks like your TSDB is returning 500 errors at midnight

**Comment by scraly** [comment]
We don't use TSDB but Graphite :-(.

**Comment by scraly** [comment]
Here the logs:

t=2016-12-26T00:00:03+0100 lvl=info msg="Request failed" logger=tsdb.graphite status="500 INTERNAL SERVER ERROR" body="<body style=\"background-color: #666666; color: black;\">\n<center>\n<h2 style='font-family: \"Arial\"'>\n<p>Graphite encountered an unexpected error while handling your request.</p>\n<p>Please contact your site administrator if the problem persists.</p>\n</h2>\n<br/>\n<div style=\"width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;\">\n\n</div>\n\n<div style=\"width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;\">\n<pre>\nTraceback (most recent call last):\n  File &quot;/usr/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 122, in renderView\n    seriesList = evaluateTarget(requestContext, target)\n  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 10, in evaluateTarget\n    result = evaluateTokens(requestContext, tokens)\n  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens\n    return evaluateTokens(requestContext, tokens.expression)\n  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 28, in evaluateTokens\n    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]\n  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 21, in evaluateTokens\n    return evaluateTokens(requestContext, tokens.expression)\n  File &quot;/opt/graphite/webapp/graphite/render/evaluator.py&quot;, line 24, in evaluateTokens\n    return fetchData(requestContext, tokens.pathExpression)\n  File &quot;/opt/graphite/webapp/graphite/render/datalib.py&quot;, line 372, in fetchData\n    dbResults = dbFile.fetch(startTime, endTime, now)\n  File &quot;/opt/graphite/webapp/graphite/storage.py&quot;, line 331, in fetch\n    return whisper.fetch(self.fs_path, startTime, endTime, now)\n  File &quot;/usr/lib/python2.7/site-packages/whisper.py&quot;, line 714, in fetch\n    fh = open(path,&#39;rb&#39;)\nIOError: [Errno 2] No such file or directory: &#39;/opt/graphite/storage/whisper/xx/yyy/comment/toto.wsp&#39;\n\n</pre>\n</div>\n\n</center>\n"
t=2016-12-26T00:00:03+0100 lvl=eror msg="Alert Rule Result Error" logger=alerting.resultHandler ruleId=2 name="Flux entrant Facebook alert" error="tsdb.HandleRequest() error Request failed status: 500 INTERNAL SERVER ERROR" changing state to=alerting
t=2016-12-26T00:00:03+0100 lvl=info msg="New state change" logger=alerting.resultHandler alertId=2 newState=alerting prev state=ok
t=2016-12-26T00:00:03+0100 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=2 sent count=1
t=2016-12-26T00:00:03+0100 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/monitoring?&panelId=1"

is it possible to not display it's a TSDB error but a graphite error for example or to not be alerted when there is an issue with a data source?
Thanks.

**Comment by arun2803** [comment]
I am also having same problem
Using Graphite and getting same tsdb error
Can someone tell me how to get rid of it ?

**Comment by torkelo** [comment]
you can in alert rule options specify how query errors should be handled (if they should be ignored or not)

**Comment by gdubicki** [comment]
I am having a similar problem too.

Using Grafana 4.1.2 and Graphite + InfluxDB as sources (**no OpenTSDB!**).

I get this error each time I test a new alert in one of my graphs. I have 3 queries in this graph. Query C is using A and B as parameters, like this:

```
absolute(diffSeries(smartSummarize(#A,"5min"), smartSummarize(#B, "5min")))
```

When testing the alert on query A or B it works correctly, I get:

```
result
   firing false
   conditionEvals false = false
   timeMs 42.495ms
   logs [ [object Object], [object Object] ]
```

But if I choose query C I get the dreaded:

```
result
   firing true
   conditionEvals = true
   timeMs 18.369ms
   error tsdb.HandleRequest() error Request failed status: 500 INTERNAL SERVER ERROR
```

Here's a screenshot:

![screenshot 2017-02-26 20 31 04](https://cloud.githubusercontent.com/assets/566632/23342925/2e908938-fc63-11e6-9edb-db548f9822b4.png)

**Comment by gdubicki** [comment]
Please reopen, @torkelo . Something is clearly wrong here. Neither @scraly nor me use OpenTSDB. And even if we would then ignoring query errors is not a solution - I want to be notifies about backend issues too with my Grafana alerts.

**Comment by gdubicki** [comment]
I have tried to copy query A and B to query C instead of using "#A" and "#B" and testing alert worked correctly.

**Comment by luislobo** [comment]
Same is happening here. Just Graphana and Graphite

**Comment by beniaminduca** [comment]
Same here, only Graphite+Grafana. is there a fix? 
I'm running  Grafana v4.5.2 (commit: ec2b0fe)
![2017-10-30_1116](https://user-images.githubusercontent.com/8181998/32163108-e05e67b8-bd63-11e7-91ce-8ee52c95115d.png)

**Comment by torkelo** [comment]
Have you checked your graphite server for logs? Maybe it reboots at midnight? Or something else is causing graphite to return error once a day
