### ISSUE TITLE
Annotations: Google Cloud Metrics annotation title and text not displayed

### ISSUE THREAD

**Issue by ajcutshall** [grafana/grafana#70612]
### 
# What went wrong?

**What happened**:

  -  When adding a dashboard annotation using the Google Cloud Metrics datasource, the "Title" and "Text" fields are not rendered (see screenshot). This behavior is present in versions 9.5.3, 10.0.0, and 10.0.1.

![Screenshot 2023-06-23 at 11 25 47](https://github.com/grafana/grafana/assets/1294226/9b3f3db4-531b-4478-98c8-f2d4b8deda86)

**What did you expect to happen**:

  - Title and text should be rendered for the annotation

### 
# How do we reproduce it?

**Step 1**:

- Add a GCM-backed annotation to a dashboard

**Step 2**:

- Attempt to add a title or text to the annotation using the provided fields.

**Step 3**:

- The annotations do not include the values from the title or text field.

### 
# What Grafana version are you using?

v9.5.3, v10.0.0, v10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

macOS Ventura 13.4

### User's Browser?

Google Chrome 114.0.5735.133

### Is this a Regression?

Yes

**Comment by ajcutshall** [comment]
Hi @usmangt,

Apologies for not having been more clear about my environment in my original post. This instance is running as a Docker container on [Google Cloud Run ](https://cloud.google.com/community/tutorials/serverless-grafana-with-iap), so I do not have direct access to the `/var/log/grafana/grafana.log` file.

After setting the console log level to `debug` and navigating to the annotation settings page for the dashboard in question and testing the query, I do not see any relevant logs. Is there a particular pattern I could search my logs for that would help here?

Thanks!

**Comment by asimpson** [comment]
Fixed in https://github.com/grafana/grafana/pull/71888
