### ISSUE TITLE
Frontend: Select/AsyncSelect component allowCustomValue has incorrect copy when not the only option

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#70635]
### 
# What went wrong?

In Prometheus query builder, users can filter select options by typing in the '@grafana/ui' `Select` and `AsyncSelect` components.

But they can also enter in regex to the query:
<img width="596" alt="image" src="https://github.com/grafana/grafana/assets/109082771/2b5a9103-4a1a-4107-8c6d-e4298018f61a">

And when you see the text "Hit enter to add" you would expect hitting enter would add the custom text, but instead it just returns the element that is focused, which by default is the first element. Another problem is sometimes the regex people write returns many results, so they cannot see the last element, and think that the select is not capable of taking custom input. [Relevant internal grafana slack link](https://raintank-corp.slack.com/archives/C036J5B39/p1687523726817089).

<img width="370" alt="image" src="https://github.com/grafana/grafana/assets/109082771/0de5c1e9-adda-4b74-8626-5352000a037d">

So there's two use cases I want to address
1. I want to select the first element that returns from my search by pressing enter
2. I want to enter the text I've just typed into the query

For prometheus, we know when folks are writing regex because the label filter operator needs to specify regex input: 
<img width="333" alt="image" src="https://github.com/grafana/grafana/assets/109082771/9b3b8379-441a-4e3b-8338-9ba411b403a2">

So ideally consumers can define when we want the component to place the custom option on top, depending on the current state of other components. 
Another potential direction: @bohandley had the great idea to use the sticky footer (datasource picker link) in the select, which is another potential solution, although that component is not [keyboard accessible yet](https://github.com/grafana/grafana/issues/69109).

Also can we change the copy when there is more than one option in the select? "Hit enter to add" is a lie if they are focused on anything else, and this gets really confusing

### 
# How do we reproduce it?

**Step 1**:

- Go to [this play link](https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22grafanacloud-prom%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

**Step 2**:

- Enter in a regex `.+` to the label value input
<img width="435" alt="image" src="https://github.com/grafana/grafana/assets/109082771/26380039-1b90-4587-ac65-1347a9c9745e">

**Step 3**:
- See your sad regex pushed all the way to the bottom, you have to scroll down to see it!
<img width="219" alt="image" src="https://github.com/grafana/grafana/assets/109082771/4bdb0d1b-9702-4729-8bdf-1b4ddbabfc89">

- Notice that "hitting enter" to add will not enter your text, but instead add the first element, or whatever you've selected with the keyboard (or hovered over with the mouse).

** Step 4**:
???

** Step 5**:
Profit

### 
# What Grafana version are you using?

9+

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Anything else to add?

Reach out to @gtk-grafana or @bohandley if you have any questions or want to ideate.

**Comment by sni** [comment]
Since i cannot access your internal discussion, is there any news on this? While on it, it would really be great to keep the current value in the input field if `allowCustomValue` is set. Otherwise the user has to enter the hole text over and over again just to change a single character. But i can open a separate issue for this if you like.

**Comment by NWRichmond** [comment]
@sni we're working on this issue now, and I expect that the fix for the order of regex values in the Prometheus query builder's filter values will be included in Grafana 11.1.x :)

With respect to this part:
> While on it, it would really be great to keep the current value in the input field if allowCustomValue is set. Otherwise the user has to enter the hole text over and over again just to change a single character. But i can open a separate issue for this if you like.

I totally hear you. I looked into it, and it appears to be a quirk of [the underlying `<Select />` component](https://grafana.com/developers/saga/components/select/#creating-custom-values)'s behavior when `allowCustomValue` is enabled, and isn't something we can control in the implementation of the `<Select />` in the Prometheus data source.

> But i can open a separate issue for this if you like.

That would be very helpful!

**Comment by NWRichmond** [comment]
To see what the solution looks like, check out the video in the **After** section in the description of https://github.com/grafana/grafana/pull/87360.
