### ISSUE TITLE
[Feature request] Conditional queries

### ISSUE THREAD

**Issue by biancalana** [grafana/grafana#7063]
Please include this information:
- What Grafana version are you using?
 4.0.2

- What datasource are you using?
 Graphite

- What OS are you running grafana on?
 Linux Centos 6 & 7

- What did you do?
 I have a dashboard using some query template variables, our metrics are structured like "prod.storage.<DC>.<Storage_Name>" the variables are used to see metrics from different Datacenters and Storages, the equipment are almost the same but there are some mior variations on metrics available. ie: One have only SAS Disk tier and other SATA Disk Tier.
There's one graph where I did percentileOfSeries of each tier, how Graphite does not allow something like GroupByNode using percentile function, I need to specify one query per tier.

- What was the expected result?
I expected to see that graph with the data of the queries that exists

- What happened instead?
The graph isn't displayed because Graphana do one request with all the queries together and Graphite return a 500 error code.
That could be solved with a way to condition which queries are used based on some query template variables.

**Comment by torkelo** [comment]
If the query returns an error, then I am not sure what Grafana can do in this case. 

You have a templated dashboard and one graph is not always working (depending on what values you select in the template variable). So would you like to specify an "ignore" condition for each query? Sounds very complicated. 

Maybe better to do a scripted dashboard?

**Comment by geronime** [comment]
Ignore condition makes sense to me - let's say I have a dashboard with a hostname template. I'd like to have a graph that shows results of one or two queries depending on what hostname is selected:
1. query without hostname constraint (shown always)
2. query with the hostname constraint, shown only unless _all_ option is selected -> the result would be just clear overlap with the first query
Is this possible somehow?
