### ISSUE TITLE
valueFormats: Turkish Lira (₺) Support

### ISSUE THREAD

**Issue by flightlesstux** [grafana/grafana#70659]
**What is the chore?**:
The chore is to add support for the Turkish Lira (₺) in Grafana. Currently, Grafana supports various currencies, but Turkish Lira is not one of them. This can be limiting for users in Turkey or those who deal with the Turkish Lira in their data visualizations. The idea is to extend the existing currency formatting options in Grafana to include the Turkish Lira.

**Is there anything else we need to know?**:
The Turkish Lira is the official currency of Turkey and its symbol is ₺. Support for this currency would involve updating the relevant sections of the codebase to include it as a formatting option. I am willing to contribute to this change myself if needed. I believe this addition will enhance the usability of Grafana for users dealing with financial data in Turkish Lira.

**Comment by flightlesstux** [comment]
Closed.

**Comment by usmangt** [comment]
Hi @flightlesstux,

Thanks for opening this issue.

There was this exact question asked on our community forum which has an answer. Please check [here](https://community.grafana.com/t/display-turkish-lira-currency-symbol/89318) for reference. 

I will close this issue :+1:
