### ISSUE TITLE
Dashboards: Charts are blurry in dashboard view

### ISSUE THREAD

**Issue by shrx** [grafana/grafana#70652]
### 
# What went wrong?

**What happened**:

  - After updating from 9.2.5 to 10.0.1 the charts in my dashboard are now blurry. If I go to a chart editing page the charts are not blurry.

Screenshot from dashboard:
![screenshot-dashboard](https://github.com/grafana/grafana/assets/810337/418f29d6-7ee5-4411-8efd-a3e9f68b07a4)

Screenshot from panel editor:
![screenshot-editor](https://github.com/grafana/grafana/assets/810337/a7c20512-d2d2-431f-a754-a2fa752f8d8e)

**What did you expect to happen**:

  - The charts shouldn't be blurry.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and go to a dashboard view

### 
# What Grafana version are you using?

Grafana v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

no

### Grafana Platform?

A package manager APT

### User's OS?

Windows 10

### User's Browser?

Waterfox G5.1.7 (64-bit), devicePixelRatio 1.25, zoom level 100%

### Is this a Regression?

Yes

**Comment by shrx** [comment]
I did a bisection of the releases, the issue was introduced in 9.3.0, it's not present in 9.2.20.

**Comment by usmangt** [comment]
Hi @shrx,

Thanks for opening this issue.

What Panel visualization you are using? 

Also, can you please provide step-by-step instructions so that the community can also try to reproduce it on a test machine? 

Thanks.

**Comment by shrx** [comment]
Hi @usmangt, I tested it with a Time Series and a Bar Chart, but it looks like a general issue with all panels, since the axes labels are blurry as well.

Minimum reproducible example:

1. create a new dashboard
2. add a new time series panel
3. select Data Source: Grafana and Query Type: Random Walk
4. refresh the dashboard so that the panel is populated with a random walk

The resulting panel is blurry

**Comment by shrx** [comment]
@usmangt do you still need some additional info?

**Comment by usmangt** [comment]
Hi @shrx ,

We have tried various OS and browsers but still cannot reproduce it.

Also just noticed that you are using Waterfox G5.1.7

Please note that we only support the following browsers as listed on this [page](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers)

If you can reproduce this on any of the above then kindly do let us know.

**Comment by shrx** [comment]
Hi, indeed I can't reproduce the issue with current versions of Chrome and Firefox, looks like Waterfox rendering is causing the issue.

**Comment by shrx** [comment]
I played around a bit and I can fix the issue if I add the following CSS style to the canvas and the axis label divs:

```css
image-rendering: crisp-edges;
```

**Comment by shrx** [comment]
It seems that different browsers have different default values for canvas `image-rendering`. Does grafana explicitly define this anywhere?

Anyway no worries, since I'm using an unsupported browser I'm fine with applying this fix myself.
