### ISSUE TITLE
Alertmanager peerReconnectTimeout failing

### ISSUE THREAD

**Issue by jquick** [grafana/grafana#70657]
### 
# What went wrong?

We are using Grafana in HA with alerting in kubernetes. This enables the alertmanager gossip network.
Alertmanger has a default of:
```
--cluster.reconnect-timeout value: length of time to attempt to reconnect to a lost peer (default: "6h0m0s")
Ref: https://github.com/prometheus/alertmanager/blob/main/cmd/alertmanager/main.go#L230
```

In high-dynamic environment like kubernetes, it's possible that grafana pods come and go on intervals.  The default timeout value of 6h is not suitable in that case as alertmanager will keep trying to reconnect to a non-existing pod over and over until it gives up and remove that peer from the member list. During this period of time, the cluster is reported to be in a degraded state due to the missing member.

The typical deploy flow in kubernetes is to spin up new pods and then terminate the old ones after they are healthy. This will result in the old pods joining the gossip network before termination.

EX:
New pod starts, and picks up the current list from the headless server (which will be updated soon)
```
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.619195431Z level=debug msg="resolved peers to following addresses" peers=172.30.0.220:9095,172.30.87.182:9095,172.
30.55.111:9095
```
The old ones and the new ones join
```
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.61960676Z level=debug received=NotifyJoin node=01H3QTG3TBEP8TR6HF1G12S6X6 addr=172.30.35.236:9095
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.642083989Z level=debug received=NotifyJoin node=01H3QTFYN1FEDAGEKW35CFX1JP addr=172.30.55.111:9095
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.64212015Z level=debug received=NotifyJoin node=01H3QB42JZQYNZ1456WF6EA1EM addr=172.30.1.172:9095
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.64213347Z level=debug received=NotifyJoin node=01H3QB4DE0HV30Y0R8XEBQDWGX addr=172.30.87.182:9095
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:48.642148411Z level=debug received=NotifyJoin node=01H3QB46X9S2YK5GEVR1B3QXSJ addr=172.30.0.220:9095
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:05:54.592747269Z level=debug received=NotifyJoin node=01H3QTG9KC7FC4YSR1KMV0A9MC addr=172.30.12.121:9095
```
The old pods terminate, and since they joined, alertmanager will try them for 6hrs
```
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:06:51.755409396Z level=debug memberlist="2023/06/24 23:06:51 [DEBUG] memberlist: Failed to join 172.30.1.172:9095: dial tcp 172.30.1.172:9095: connect: no route to host\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:06:51.755433266Z level=debug msg=reconnect result=failure peer=01H3QB42JZQYNZ1456WF6EA1EM addr=172.30.1.172:9095 err="1 error occurred:\n\t* Failed to join 172.30.1.172:9095: dial tcp 172.30.1.172:9095: connect: no route to host\n\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:06:55.456545766Z level=debug memberlist="2023/06/24 23:06:55 [DEBUG] memberlist: Initiating push/pull sync with: 01H3QTFYN1FEDAGEKW35CFX1JP 172.30.55.111:9095\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:00.517027035Z level=debug memberlist="2023/06/24 23:07:00 [DEBUG] memberlist: Stream connection from=172.30.55.111:54848\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:01.75649538Z level=debug memberlist="2023/06/24 23:07:01 [DEBUG] memberlist: Failed to join 172.30.0.220:9095: dial tcp 172.30.0.220:9095: i/o timeout\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:01.75652471Z level=debug msg=reconnect result=failure peer=01H3QB46X9S2YK5GEVR1B3QXSJ addr=172.30.0.220:9095 err="1 error occurred:\n\t* Failed to join 172.30.0.220:9095: dial tcp 172.30.0.220:9095: i/o timeout\n\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:11.75756974Z level=debug memberlist="2023/06/24 23:07:11 [DEBUG] memberlist: Failed to join 172.30.87.182:9095: dial tcp 172.30.87.182:9095: i/o timeout\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:11.757594971Z level=debug msg=reconnect result=failure peer=01H3QB4DE0HV30Y0R8XEBQDWGX addr=172.30.87.182:9095 err="1 error occurred:\n\t* Failed to join 172.30.87.182:9095: dial tcp 172.30.87.182:9095: i/o timeout\n\n"
logger=ngalert.multiorg.alertmanager component=clustering t=2023-06-24T23:07:15.494534901Z level=debug memberlist="2023/06/24 23:07:15 [DEBUG] memberlist: Initiating push/pull sync with: 01H3QTFYN1FEDAGEKW35CFX1JP 172.30.55.111:9095\n"
```
<img width="618" alt="Screenshot 2023-06-24 at 6 36 23 PM" src="https://github.com/grafana/grafana/assets/574637/21460a78-289b-4c79-8292-89dfad2c3dd7">

I didn't see an easy way to edit/change this setting in grafana but it should be configurable to reduce the load/errors.

Here is where they also fixed this issue for `prometheus-operator`: https://github.com/prometheus-operator/prometheus-operator/pull/3436

Thanks for your help!

### 
# How do we reproduce it?

**Step 1**:

- Setup Grafana in a HA setup on kubernetes or another vm manager.

**Step 2**:

- Roll a few pods so that they rebuild

**Step 3**:

- Grafana instances will now be trying to connect to the old nodes for 6 hrs. This can be seen in the debug logs or `alertmanager_cluster_failed_peers` metrics

### 
# What Grafana version are you using?
v10.0.1

**Comment by mellieA** [comment]
@jquick I'm not sure where this one belongs. The setting was added as part of the prometheus project here https://github.com/grafana/prometheus-alertmanager/commit/fad796931b792fc30f35bb18a580ae7323ef0241

Will refer to our alerting squad to chime in

**Comment by armandgrillet** [comment]
There is no way to change the value from Grafana itself, as we can see in https://github.com/grafana/grafana/blob/751b982d9ce18eb4f4660ddfb932b408bc58cad7/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L130C61-L130C84 we only use the default value. This is a feature request but the use case described in this issue makes sense.

**Comment by lumaks-redox** [comment]
If someone ends up here like me, seems like it's possible to overwrite timeout setting in grafana now https://github.com/grafana/grafana/blob/0567ef29beee0e82ea8d4da6cd4e3511d277324f/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L223
