### ISSUE TITLE
Backporting: v9.5.5 does not contain commits from 9.5.x branch

### ISSUE THREAD

**Issue by darkleaf** [grafana/grafana#70667]
**What is the chore?**:
There is [Chore: remove pre tags from DOMPurify config #68512](https://github.com/grafana/grafana/pull/68512).
The changes was backported to the 9.5.x branch but ones don't exist in the v9.5.5 release.

+ [v9.5.**5**](https://github.com/grafana/grafana/blob/v9.5.5/packages/grafana-data/src/text/sanitize.ts#L42) 
+ [v9.5.**x**](https://github.com/grafana/grafana/blob/v9.5.x/packages/grafana-data/src/text/sanitize.ts#L42)

**Comment by usmangt** [comment]
Hi @darkleaf,

Thanks for opening this issue.

I see that you did rightly by commenting on the original issue and also informing @ryantxu about it. I am sure the team will pick it up and will update you.

**Comment by darkleaf** [comment]
fixed in  9.5.7
