### ISSUE TITLE
[Bug] cannot refresh the dashboard

### ISSUE THREAD

**Issue by yelangchs** [grafana/grafana#7067]
I have install grafana version Grafana v4.0.2 (commit: v4.0.2), but i do some config like this picture for attach file

i use influxdb datasource, and i run in my linux for centos 6.5
i finish my dashboard, but when i add new panel, the panel cannot refresh.
the error, please see the file.
![error](https://cloud.githubusercontent.com/assets/3895987/21472252/c78edcfa-cb0a-11e6-84d8-346565b9ae8a.png)

my config json file is below.

[config.txt](https://github.com/grafana/grafana/files/672273/config.txt)

**Comment by torkelo** [comment]
Could you show your panel json?

**Comment by torkelo** [comment]
please provide panel or dashboard json
