### ISSUE TITLE
Thresholds in override with repeating panels not working

### ISSUE THREAD

**Issue by PhilippDehner** [grafana/grafana#70683]
### 
# What went wrong?

**What happened**:

  - I have a dashboard Custom variable.
  - I have a query in a panel which is using the dashboard variable
  - The panel is repeating by the dashboard variable
  - The panel have threshold overrides, which are based on the query results, which are grouped by a variable which contains the dashboard variable
  - The thresholds are not shown (except for the first panel)

**What did you expect to happen**:

  - The thresholds of the respective override (which depends on the query result which depends on the dashboard variable) should be shown.

### 
# How do we reproduce it?

Requirements:

- Available (InfluxDB) datasource with different tags / names

Steps: 

1. Open Grafana
2. Create a new dashboard 
3. Create a dashboard variable (Custom)
4. Add the values which contains the tags / names in the data
5. Add a new panel
6. Query the data, grouped by the tag / name which contains the values of the dashboard variable
7. Set threshold overrides to each series.
8. Enable the panel repeating by the dashboard variable

### 
# What Grafana version are you using?

v8.3.4

### 
### Grafana Platform?

A downloaded binary

### User's OS?

Windows Server

### User's Browser?

Firefox

### Is this a Regression?

None

### Are Datasources involved?

InfluxDB

**Comment by PhilippDehner** [comment]
Hi @usmangt, unfortunately I couldn't create a new dashboard on [https://play.grafana.org/](https://play.grafana.org/). There is no "+ Button"

**Comment by usmangt** [comment]
Yes that is a small limitation. Then I would suggest to try to reproduce this using Grafana ver 10

**Comment by PhilippDehner** [comment]
Query:
`SELECT "value" FROM "autogen"."testMeasurement" WHERE ("machine"::tag =~ /^$Machines$/) AND $timeFilter GROUP BY "machine"::tag`

I have defined thresholds for every field: 
![grafik](https://github.com/grafana/grafana/assets/49042626/d666d5a3-ec76-41d0-8574-4aece7f12cfa)

---

Dashboard variable: 
![grafik](https://github.com/grafana/grafana/assets/49042626/2eb7daec-af62-4abc-8daa-ac122b0c15e5)

--- 

The result is: 
![grafik](https://github.com/grafana/grafana/assets/49042626/ebf6a871-5244-44d7-b9f3-340efe9b2205)

---

I added the dashboard json (in a txt file, json is not allowed).
[Dashboard.txt](https://github.com/grafana/grafana/files/11982522/Dashboard.txt)

**Comment by itsmylife** [comment]
I removed myself and the project. It looks like it is related to the dashboards squad. Feel free to ping us back if you think otherwise.
