### ISSUE TITLE
Units: mOhm missing

### ISSUE THREAD

**Issue by PhilippDehner** [grafana/grafana#70680]
### 
# What went wrong?

**What happened (Scenario 1)**:

  - I have values with unit mOhm.

**What did you expect to happen (Scenario 1)**:

  - mOhm is not a option in the unit selector

**What happened (Scenario 2)**:

  - I have values with unit mOhm and divided them by 1000
  - I selected Ohm as unit

**What did you expect to happen (Scenario 2)**:

  - I expected 5 mOhm as shown value, not 0.005 Ohm

### 
# How do we reproduce it?

1. Open Grafana and create a new dashboard and add a new panel
2. Use a time series panel
3. open the unit options

### 
# What Grafana version are you using?

v9.1.6

### 
### Grafana Platform?

Docker

### Is this a Regression?

None

### Are Datasources involved?

InfluxDB

**Comment by usmangt** [comment]
Hi @PhilippDehner,

Thanks for opening this issue.

Looking at the tile of this issue "Units: mOhm missing" was it available in the previous version of Grafana? if yes, then what is that version?

Also, please test your case in the new Grafana version 10. You can use play.grafana.com for testing.

**Comment by PhilippDehner** [comment]
I think if it was available in an older version, I should find it here, but there are no results: 
https://github.com/search?q=repo%3Agrafana%2Fgrafana%20mOhm&type=code

**Comment by PhilippDehner** [comment]
I checked it also in Grafana 10:
![grafik](https://github.com/grafana/grafana/assets/49042626/1b87cc67-6c44-4ab0-9660-02c8d2008512)

**Comment by PhilippDehner** [comment]
Missing units:

- mOhm (mΩ)
- (?)

**Comment by usmangt** [comment]
What I did is copy-paste this unit into the Standard Option and then it seems to pick it up.

![enery-custom-unit](https://github.com/grafana/grafana/assets/69509548/d20a1192-4576-4248-b545-d329f80eb9f5)


Does this solution work for you?

**Comment by PhilippDehner** [comment]
![mOhm-as-custom-unit](https://github.com/grafana/grafana/assets/49042626/67c0d1ba-e282-46bb-a0e5-4945187e7207)

It's not really a good solution, because the benefit of the units cannot be used (for big values it should be shown in Ohm, not in mOhm. This is the reason why I don't want to use custom units.

**Comment by usmangt** [comment]
Thanks for attaching the screencast and also the details. I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by PhilippDehner** [comment]
Okay thanks!
I can create a PR if this is a good idea. 

The files which must be changed are 

- packages/grafana-data/src/valueFormats/valueFormats.test.ts
- public/app/core/utils/kbn.test.ts
- packages/grafana-data/src/valueFormats/categories.ts

**Comment by ivanortegaalba** [comment]
Please, @grafana/dataviz-squad can you help here? Thank you! 🙏
