### ISSUE TITLE
[Feature request] Dashboard not accessible if user is not logged in

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#7069]
- What Grafana version are you using?
4.0.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS 7

- What did you do?
Created a dashboard for one type of user (supervisor and admin)

- What was the expected result?
This dashboard should only visible/accessible to logged users, not for guest users

- What happened instead?
Every user, logged or not logged, can access to this dashboard

In our Grafana instance, we have severals dashboards for trafic, activities, server and some dashboards in order to check employees performances. We don't want that employee can access to this/theses dashboard(s).

Thanks.

**Comment by torkelo** [comment]
Unless you have enabled anonymous, all users must log in to access dashboard. 
http://docs.grafana.org/installation/configuration/#auth-anonymous

If you have enabled anonymous access then all users can access all dashboard in that Grafana org (anonymous is enabled for only one Grafana Organization), you can create a separate organization for the dashboards you only wish specific people should be able to see.
