### ISSUE TITLE
InfluxDB: "time < now()" is not added to Influxdb queries when time range is "Last X ..."

### ISSUE THREAD

**Issue by stopmachine** [grafana/grafana#7071]
If you add an annotation from an Influxdb datasource with the mandatory "where $timeFilter", Grafana emits queries without an upper limit on the time for "Last X .." ranges. If you select "Today" or "This week" for example, it limits the result's time appropriately.

This slows the interface down when you have future events stored in influxdb (for example business hours). Influxdb has to fetch and send all these irrelevant events, then Grafana needs to go over them and filter all future events.

Adding "and time < now()" or "and time < now() + 24h" to the annotation query solved the issue, but I think this should be handled seamlessly by Grafana (generated by $timeFilter). 

Grafana version 4.0.2 on Ubuntu 14.04.4 LTS
Influxdb version 1.1.1

**Comment by calebsmac** [comment]
Is there a workaround for this bug? It is actually quite severe as it completely breaks singlestat panels (they show far future data)

**Comment by aocenas** [comment]
This is still happening with influx flavor, does not happen with Flux flavor. In Flux we add the precise `from` and `to` time range. In the influx we do just `WHERE time >= now() - 6h` so it isn't bound in the future.
