### ISSUE TITLE
[Bug] Hovering label box outside of visible area

### ISSUE THREAD

**Issue by flypenguin** [grafana/grafana#7075]
## MY STEPS

- Grafana v4.0.2
- Prometheus data source
- Running on Ubuntu 16.04 LTS
- Hover with mouse over a graph with "many lines"

## EXPECETD RESULT

A label box which I can see fully, or at least the top rows if it really does not fit the screen.

## ACTUAL RESULT 

The top of the label box is outside of the viewing area of the browser (see attached image). I cannot read the topmost labels. (which you also can see by the rounded black corners in the bottom of the hovering label box, and the cut-off straight edges on top where it hits my bookmark bar)

This is really annoying cause I cannot see the top-"performers" on a graph with a single glance, in this one occation I pretty much only the the "0"s ...

## TEST DASHBOARDS

I downloaded them as-is from grafana.net and tried it out. Happens with each of them.

* (The one I used): https://grafana.net/dashboards/395
    * Graph "Available Memory on Node", 1st row, 2nd from right
    * Graph "System load on node"
* Also: https://grafana.net/dashboards/893 
    * Available memory graph, 2nd row, 2nd from the right)

## IMAGE

<img width="501" alt="bildschirmfoto 2016-12-27 um 14 17 30" src="https://cloud.githubusercontent.com/assets/5030694/21500609/d5361c6a-cc40-11e6-8081-adbd4cf52c4a.png">

**Comment by torkelo** [comment]
There is some limits to what can fit in the the all series tooltip, if you have too many series switch to the single mode tooltip that only shows the series you hover over

**Comment by flypenguin** [comment]
well.

it WOULD fit on the screen, it's just not properly positioned.
also the top rows probably contain the most important informaiton, given that most people I know sort "descending". 
also (third) switching to single mode leads to a completely different (and in a lot of use cases I would say less optimal) way of interpretation process.

so saying "use single one" is kinda the most unhelpful answer ever and feels extremely ignorant to me, because I really think this is a valid usability issue. 

I can also think of a couple of workarounds, but given this answer I really don't believe you're at all interested.

**Comment by torkelo** [comment]
Sorry, your screenshot did not show that there was space available

**Comment by flypenguin** [comment]
all right. I was a bit snappy as well probably. also sorry for replying so late, I was taken down by a virus last week.

still think the placement of the box is unfortunate :)
