### ISSUE TITLE
Share Panel To Slack/Hipchat/etc (including link and current image)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7076]
Share panel to slack, hipchat etc.

**Comment by Gelob** [comment]
I wonder if there was some work done for alerting already that could be re-used or perhaps kill two birds with one stone? https://github.com/grafana/grafana/issues/6451

**Comment by torkelo** [comment]
Of course a lot of the stuff made for alerting can be reused when implementing this

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by davidnewhall** [comment]
Doesn't this feature... already exist? Curious how this proposal differs from the current image-share feature present in the slack notifications.
