### ISSUE TITLE
Bug Bash: Go/No-Go Decision Template

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#70762]
Create Go/No-Go decision template

**Comment by supilee** [comment]
communicated to mteam-grafana, awaiting feedback

**Comment by supilee** [comment]
@margotphelps anything you want to change? else i'll close it.

**Comment by margotphelps** [comment]
Looks good to me!

**Comment by supilee** [comment]
Perfect. Closing. 
Next step: add to Bug Bash Comms. / Pin to bug bash channel / ask EMs to communicate
