### ISSUE TITLE
Add a Floating navbar for variables on larger dashboards

### ISSUE THREAD

**Issue by jlynch93** [grafana/grafana#70771]
**Why is this component needed**:
Add a floating variable bar This would help with navigating larger dashboards that require scrolling. Please see attached photo of the change being asked.
___
 - [X] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
This could be used on larger dashboards, this could be used as a float with the top nav or a seperate floating nav bar
___
- [X] Post screenshots possible.
- [ ] It has a single use case.
- [X] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

![image](https://github.com/grafana/grafana/assets/53448444/53575536-53af-4960-8ef6-a12817d1680b)

**Comment by natellium** [comment]
Hey @jlynch93, this seems like the same use case as https://github.com/grafana/grafana/issues/11166 I'll close this one as a duplicate to keep the info centralised. Good news, as we mentioned in that issue we're planning on releasing this feature in the upcoming months :)
