### ISSUE TITLE
Dashboards do not resize automatically when resizing Firefox window

### ISSUE THREAD

**Issue by Pokom** [grafana/grafana#70776]
- version: `Grafana v10.1.0-57399pre (c9c357fc19)`
- Firefox 114.0.2 (64-bit)
- Ubuntu 22.04

This happens on the _latest_ build for Grafana that I believe is a regression. This does not happen on Grafana v10.0.0 (81d85ce802). Scenario is I have Firefox at half my screen and everything looks fine. If I maximize Firefox, the dashboards do not resize themselves. This _does not_ happen when I'm in explore mode. I have to force a refresh of the page for the dashboards to grow to the size of the viewport. 

I've attached a video as it's a lot easier to visualize. 

https://github.com/grafana/grafana/assets/1080566/cffb8e9b-4e10-4ffe-a205-d461ea28a7b0

This can be also reproduced if you open up inspector and try to resize the viewport.

**Comment by ivanortegaalba** [comment]
I'm not able to reproduce it.

![2023-06-28 15 24 47](https://github.com/grafana/grafana/assets/5699976/675cf9bb-dc99-42c9-9361-9b78c476ee4e)

I'm using the latest version of Firefox (same than yours), but in MacOS.

**Comment by Pokom** [comment]
Ah that's interesting. Maybe it's a Linux only issue, let me see if I can ask in #desktop-linux for others to try and reproduce.

**Comment by Pokom** [comment]
@ivanortegaalba no one else can reproduce this, so I'll close this. Thanks for triaging and glad it's not a regression 🙏🏻

**Comment by ulrichSchreiner** [comment]
Just for documentation: I have the same problem with FF/linux but only when i use a different zoom-factor for the page. when using 100% everything works, but as soon as i use 100% or 90% the resizing stops to work (making smaller works, but make the window bigger does not resize the content).
