### ISSUE TITLE
[Feature request] Text input template option

### ISSUE THREAD

**Issue by ericuldall** [grafana/grafana#7077]
I'm currently finding it desirable to use a text input in my template options, but don't see any way to do it. Is this something that would be a well received PR?

**Current Use Case**

I have a dashboard that monitors an ELK stack using the Elasticsearch datasource. In this dashboard I have a graph that shows all the logs coming in and allows me to group on any property using a template dropdown (this part is very helpful).

**What is missing?**

Lets say I wanted to show stats on all logs that have a certain string in the message, for instance... 
```
message=~"MalBot 1.0"
```
Now, arguably I could just create a custom template field with an exhaustive list of everything I determine should be a filter keyword, however it would be much easier to simply allow a custom text input that can be used as a template variable.

**Pros**

- [x] Allows fast improvisational searching over large metric sets
- [x] Reduces administrative intervention to add trivial search terms to custom inputs
- [x] Allows synchronization with other apps that have search boxes (Kibana, in my case)

**Cons**

- [x] Possible SQL Injection risk
- [x] User can possibly break graph due to incorrect input (PEBCAK)
- [x] Lack of textual feedback in graphs does not give strong guarantee that search is being honored as expected

...I'm sure there are other pros and cons I have not considered. I'd be interested to hear why this is not yet a feature and if it's desired on any level or in the works.

**Suggested Implementation**

Allow a text box option as a template variable with an option to use a default text when the box is left empty.

![screen shot 2016-12-27 at 6 05 19 pm](https://cloud.githubusercontent.com/assets/3223296/21512209/34fc4142-cc5f-11e6-89cc-c319ac8ddc77.png)

![screen shot 2016-12-27 at 6 01 07 pm](https://cloud.githubusercontent.com/assets/3223296/21512217/48a80398-cc5f-11e6-8959-09c479d9683b.png)

Any feedback on this?

**Comment by torkelo** [comment]
Not sure what is stopping you from doing this today, with say a custom variable (you can specify any value in a text box when you click it). 

But what sounds even better is the new ad hoc filter template variable that allows you do add ad hoc filter that get automatically added as filters to all queries

**Comment by ericuldall** [comment]
Ah, I never knew the Custom field could take user input. It does seem a bit confusing and in this case I wouldn't want the drop down, but it won't let me create the input without providing at least 1 custom value.

The ad hoc filter is cool, but seems like more of a power user feature. Just a simple text box value that can be placed as a template variable is ideal, and I can certainly use the Custom field, now that i know it accepts text, but it would be nice to just have a text box without the dropdown.

**Comment by ericuldall** [comment]
Correction, I've used the all option in place of an empty value and used sql injection style query to make it do what I need.

Query:
```
message=~"$mquery"
```

Custom All Value:
```
" or message =~* or message =~ "
```

this works well enough for now. When All is selected I get a normal wildcard query and when another option is passed it filter by only that query.

**Comment by faxm0dem** [comment]
I think the original request is still valid. The drop-down hack seems too user-unfriendly to me

**Comment by pdu** [comment]
+1 for this feature, I only realize the "custom" drop-down can accept the text input after reading this thread.

**Comment by benley** [comment]
Even knowing that the Custom dropdown type accepts text input, it's still fairly inconvenient to use; half the time when I enter something there and hit enter, it's unclear whether or not it actually had an effect until I reload the page.

**Comment by marefr** [comment]
Duplicate of #3173

**Comment by marefr** [comment]
Available in latest release, i.e v5.3.1
