### ISSUE TITLE
Grafana 7.6.2 version - Okta SSO Integration not working

### ISSUE THREAD

**Issue by vmanju123** [grafana/grafana#70782]
### 
# What went wrong?

**What happened**:
We are trying grafana OKTA SSO integration, did the required app configuration in Okta and also relevant okta configuration in grafana.ini
Observations
we have 2 grafana servers
Server 1 is in public internet with a public DNS name and proper SSL cert - Okta SSO integration works here without any issues
we are using the redirect_url as https://<server dns name>/login/okta in Okta app configuration
Server 2 is in our internal local network behind a Firewall/NAT and has a local DNS name and proper SSL cert - Okta SSO integration doesnot work here and results in 404 error

we are using the redirect_url as https://<server dns name>/login/okta in Okta app configuration
  - 

**What did you expect to happen**:
SSO integration to work
  - 

### 
# How do we reproduce it?

**Step 1**:

- Setup grafana internally behind a firewall/NAT

**Step 2**:

- Follow instructions here to setup okta integration
- https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/

**Step 3**:

- Setup app configuration in your okta account and then the grafana.ini as per instructions above
- check if the integration works and if you can do sign on to grafana using okta user credentials

### 
# What Grafana version are you using?

7.6.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A downloaded binary

### User's OS?

Ubuntu 22.04

### User's Browser?

Chrome/Edge

### Is this a Regression?

None

### Are Datasources involved?

No

### Anything else to add?

None

**Comment by usmangt** [comment]
Hi @vmanju123,

Thanks for opening this issue.

Grafana's current latest stable version is 10.0 and the version you are using is no longer supported. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will now close this issue).

**Comment by vmanju123** [comment]
We got this resolved
the documentation is wrong
it needs 3 more settings in grafana.ini
the domain and root_url parameter in grafana.ini needs to be un commented and should have exact URl as the one in redirect URI set in okta app
also uncomment serve_from_sub_path parameter and make it true

For eg:
if your redirect URI is https://xyz.com:443/ in okta app 

in grafana.ini set
domain = xyz.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/
serve_from_sub_path = true

restart grafana-server and try

**Comment by vmanju123** [comment]
You can close this issue, thanks

**Comment by usmangt** [comment]
Thanks for the reply. I am reopening this issue to get the documentation get rechecked as you found out that some steps are missing.

Sending it to the Docs and Auth team

**Comment by Jguer** [comment]
Closing as a lot has changed since v7 to 1:1 document. 
We're currently revising oauth documentation, pinging @linoman @IevaVasiljeva for awareness.
Happy that you got it solved though :smile:
