### ISSUE TITLE
Prototype UI for admin page

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#70784]
After meeting with the UX team, they provided some specific component suggestions and encouraged us to prototype a UI in Grafana directly and share it with them. 

Create a branch and begin implementing a rough front-end in Grafana, using dummy data to seed the page.

**Comment by IbrahimCSAE** [comment]
[feat/feature-toggle-admin-page-prototype](https://github.com/grafana/grafana/tree/feat/feature-toggle-admin-page-prototype)

A prototype has been implemented in this branch.

![After](https://github.com/grafana/grafana/assets/93064150/935ba5db-d71c-4ffc-84c8-d74a41c4cc0b)

**Comment by torkelo** [comment]
If we are to show them in the UI might be good to introduce a display name (and rename current Name prop to ID) to give the feature toggles better display friendly names instead of string ids

**Comment by mmandrus** [comment]
Thanks for the feedback @torkelo! We will be adding descriptions and/or links to the official feature toggle docs. Good idea regarding display names!

FYI you can see the design doc for this [here](https://docs.google.com/document/d/1Spcwl8UBNPp0aUNa44gQPvacqZnTesdTeKBSBmGfS-U/edit#heading=h.5sybau7waq2q). We're working with UX to refine the page over time. Please let us know if you have any other feedback or ideas.

**Comment by IbrahimCSAE** [comment]
Prototype updated with descriptions for each feature toggle! we will continue refining it with the UX team, thanks a lot for the feedback

![image](https://github.com/grafana/grafana/assets/93064150/5deb7492-01a5-4e73-a16f-4bcdc5461bb8)
