### ISSUE TITLE
Grafana Auth proxy Does not let the user log in automatically 

### ISSUE THREAD

**Issue by pramit46** [grafana/grafana#7080]
I am trying to achieve the following:
when end-user hits a link for grafana, the call first goes to nginx (which listens to port 80) who then first make a callback to the calling application to check if the userid is valid and upon getting 'true' in return, it would direct the call to grafana otherwise redirect the call to some other login screen. Now, if the user name exists in grafana then the username should not be validated again and grafana should pull up the home dashboard of the user. 

My problem is, grafana pulls up the default screen of the existing user and not the userid being passed. Let's say the user id 'admin' is logged in right now, and the end-user calls the following URL (right now, it's GET request for testing purpose): http://IP:Port/username=nuid. Now, I would expect to see the default screen of 'nuid' (assuming the id is present in grafana and also authenticated by the calling system), but grafana brings up the screen of 'admin'. This does not happen when I use basic authentication: 
`proxy_set_header Authorization "Basic X3JpGUZV5tXNlcjpPYYPzd59yZC1x"` 

I tried to suppress the authorization header from the http-header:
```
proxy_redirect off;
proxy_set_header Authorization "";
```
But it does not help, either.

Following is my nginx config excerpt:

```
 upstream grafana {
                server <<Grafana IP>>:3000;
                keepalive 15;
        }

server {
                listen     80;
                server_name <<end-user IP>>;
                access_log  /var/log/nginx/access.log grafana;
                error_log  /var/log/nginx/error.log debug;

                if ($request_uri ~* username=(.+)) {
                        set $usrname $1;
                }
                if ($request_uri !~* username=(.+)) {
                        set $usrname nuid;
                }

 location / {
                        #internal;
                        auth_request  /_auth;
                        auth_request_set $user $upstream_http_x_user;

                        proxy_pass http://grafana/;
                        #proxy_pass_request_body off;

                        proxy_set_header X-WEBAUTH-USER $user;
                        #proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        #proxy_set_header Authorization "Basic X3JpGUZV5tXNlcjpPYYPzd59yZC1x";
                        proxy_redirect off;
                        proxy_set_header Authorization "";
                        #proxy_set_header Proxy "";

                        #proxy_pass http://grafana/;
                        #proxy_pass_request_body off;
                }
                #############:CHECK WITH AUTH FOR SESSION:###############
                location = /_auth {
                        internal;
                        proxy_pass http://<<AUTH-IP>>/laravel41/public/userValidityCheckForGrafana?username=$usrname;
                        #proxy_pass_request_body off;
                        #proxy_set_header Content-Length "";
                        #proxy_set_header X-Original-URI $request_uri;
                }

                ####################:ERROR PAGE:#######################
                error_page  404 500 402 403 @authenticate;

                location @authenticate{
                        return 302 http://<<AUTH APP IP>>/path/to/log/back/in/;
```

Following is the excerpt of my grafana.ini:

```
#################################Generic Auth##############################
[auth]
disable_login_form = true

#################################### Basic Auth ##########################
[auth.basic]
enabled = false

#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

```

Can someone help me achieving this?

**Comment by torkelo** [comment]
Are you trying to send the username via query parameter? It needs to be in a http header. 

Looks like you transform the query parameter to header in your nginx. 

It's good that you try to remove the authorization header, that is important.  You need to troubleshoot this yourself, look at the http calls being made between nginx and grafana.  Something is wrong with your setup as there are no r

**Comment by pramit46** [comment]
I take the username out of the URL and set that to  X-WEBAUTH-USER. 
`proxy_set_header X-WEBAUTH-USER $user`

I also tried to remove the Authorization header: 
`proxy_set_header Authorization "";`

It did not help.

**Comment by pramit46** [comment]
I also see that you were writing something in your comment which you could not finish. Can you please complete that? Perhaps, that can help me. :)

**Comment by torkelo** [comment]
I was just saying no one has reported any issue with auth proxy feature, so something is wrong with nginx config

**Comment by pramit46** [comment]
Okay. Can you just help me out in dropping the auth header. I guess if I can do that and stop the headers to reach grafana, my job will be done. I don't want to use basic authentication, either.

**Comment by krishnakanthpps** [comment]
@pramit46  any success with your auth proxy with nginx? 

I have been trying to do auth proxy with Apache for a while. If it is working with nginx, I would love to know how you have been able to achieve it.

**Comment by pramit46** [comment]
hi @krishnakanthpps 
Yes, it worked for me. But in my case, the requirement is little different. Instead of authenticating the user in nginx or grafana, I'm checking whether or not any session for that user exists. So by calling /_auth, I am letting the calling system let me know if the session exists, in boolean way. 

If no, it goes to error page (which is the login page of calling system), else go to grafana.. I set the captured userid (as of now, I get it from url for testing purpose, but soon we will move that to request object) to the X-WEBAUTH-USER header and send to grafana.

But if you want to authenticate the user directly in nginx.conf, then you can use the basic authorization mechanism.

Refer this URL. It helped me. See if it helps you:
[(https://blog.raintank.io/authproxy-howto-use-external-authentication-handlers-with-grafana/)]

**Comment by senthil-telsiz** [comment]
Hi @pramit46,

I am trying out auth proxy in grafana using SSO and I followed your post to set the nginx.conf but I am still facing issue in the authentication. Can you post your updated nginx conf file.

**Comment by roy651** [comment]
https://community.grafana.com/t/how-to-use-auth-proxy-with-nginx/2257/3

**Comment by a459295360** [comment]
you can use "curl -H "X-WEBAUTH-USER:  admin"  http://ip:port/   " to check the auth.proxy is used, and  it can return html to you when the auth.proxy is enable .
