### ISSUE TITLE
Allow wildcard and regex queries on Elasticsearch non_analyzed fields

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#7081]
If you have not_analyzed fields in ElasticSearch index, you cannot make wildcard queries like message:*Hello* as it generates a regular match query. It needs to generate a wildcard query to ES, as following:

```
{
  "wildcard": {
    "message": "*Hello*"
  }
}
```
Similarly, for regex, it needs to generate queries to ES in this format:

```
{
    "regexp":{
        "name.first": "s.*y"
    }
}
```
Quite often we cannot specify the exact text in the query that we want to find in the logs. In those scenarios, we need to have the feature to perform partial search.

**Comment by torkelo** [comment]
Do you have a proposal for how this should be done? Given that the current query model only supports one lucene query string.

**Comment by oazabir** [comment]
Could you introduce a + button beside the search box, which behaves just like the way adding more group by clauses work today, where we can select the type of the query from the dropdown? 

It should support all the types which are listed here:

https://www.elastic.co/guide/en/elasticsearch/reference/2.3//term-level-queries.html

**Comment by seawhite** [comment]
Not sure if this is the same thing you're talking about but the same queries I make in Kibana, do not work in Grafana. Both applications use Lucene but Grafana doesn't seem to like regex queries. For example, the following works in Kibana but not in Grafana:

IPv4\ Source:192.168.1.0\/24

**Comment by torkelo** [comment]
why is IPv4_Source:192.168.1.0/24  not working in Grafana? If that is proper lucene syntax then it should work, or is kibana doing something special here and querying ES in a specific way?

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/7451  (better describes the problem)
