### ISSUE TITLE
Plugin Details Page: overflow: auto causes fields' outline to be cut off

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#70820]
in https://github.com/grafana/grafana/pull/58741 an `overflow: auto` rule is added to the plugin details page, which causes outlines on fields to be cut out when focused

![Screenshot 2023-06-28 at 12 29 23](https://github.com/grafana/grafana/assets/1170767/e9473a63-b6e2-4893-ba47-b4ffb884c1fd)

removing the rule in `public/app/features/plugins/admin/components/PluginDetailsPage.tsx` fixes the issue, however i'm not sure if it ha any unwanted side effect

**Comment by nayeem01** [comment]
@tolzhabayev Hi, is it still open to work?

**Comment by tolzhabayev** [comment]
Maybe @leventebalogh can take a look

**Comment by academo** [comment]
@Elfo404 I took a look at this and I could not see any change removing or adding the overflow: auto in this page. 

I also tried this same component `DataSourcePicker` in another place it looks the missing padding is also there. So I assume this is something to fix in `@grafana/runtime` or `@grafana/ui`

**Comment by academo** [comment]
@Elfo404 I was looking at something completely different. I can reproduce the issue now. I'll see if I can fix it.
