### ISSUE TITLE
Execute saved queries on ElasticSearch

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#7082]
Since Kibana has powerful query interface, we usually build complex queries on Kibana and save them. We need a way to execute those saved queries on Grafana. 

The saved queries are stored under .kibana index. You can do a GET on /.kibana/search/_search and it will return the saved queries:

```
{ -
        "_index": ".kibana",
        "_type": "search",
        "_id": "MCIR:-Failed-response-to-ESB",
        "_score": 1,
        "_source": { -
          "title": "MCIR: Failed response to ESB",
          "description": "",
          "hits": 0,
          "columns": [ -
            "_source"
          ],
          "sort": [ -
            "@timestamp",
            "desc"
          ],
          "version": 1,
          "kibanaSavedObjectMeta": { -
            "searchSourceJSON": "{"index":"mcir-*","query":{"query_string":{"query":"source:\"MCIRWebAPIResponseTrace.csv\" AND category:verbose AND data:\"responsecode:false\"","analyze_wildcard":true}},"filter":[],"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}},"require_field_match":false,"fragment_size":2147483647}}"
          }
        }
      }
```

On Grafana, if we could get a drop down of all saved queries and pick from them, it would make it very easily to build complex queries and plot them using Grafana. This will bridge the gap between grafana and kibana's query features.

**Comment by torkelo** [comment]
This is going to be tricky, as Grafana need to support the kibana query model.  

You best bet is to write a conversation tool that takes a saved kibana query and translates it into a Grafana one.

**Comment by oazabir** [comment]
I am afraid with the current ability to put only one terms query on the search box, we cannot use all the different types of queries elasticsearch supports, eg wildcard, regex etc. That's where Kibana comes handy. 

A quick win could be that you introduce a special syntax on the search box, which tricks grafana into retrieving a saved query from .kibana index and then executing the real query on elasticsearch. Something like:

[saved query name]

Would make grafana fetch the saved query and then execute that on ES directly, instead of building its own query.
