### ISSUE TITLE
Dashboards: cannot create folder using Folder HTTP API

### ISSUE THREAD

**Issue by kaskaz** [grafana/grafana#70837]
### 
# What went wrong?

**What happened**:

  - When calling the endpoint _POST /api/folders_ with body _{"uid":"f0d69838123","title":"f0d69838123"}_ (as example) the folder is not created. Instead, returns a list of the existing folders.
  - Creating folders using the Dashboard is possible.

**What did you expect to happen**:

  - The folder is created, and a similar response is returned:
```
  {
    "id": 25,
    "uid": "f0d69838123",
    "title": "f0d69838123",
    "url": "/dashboards/f/f0d69838123/f0d69838123",
    "hasAcl": false,
    "canSave": true,
    "canEdit": true,
    "canAdmin": true,
    "canDelete": true,
    "createdBy": "Anonymous",
    "created": "2023-06-28T12:54:30.669692467Z",
    "updatedBy": "Anonymous",
    "updated": "2023-06-28T12:54:30.669692517Z",
    "version": 1
}
```

### 
# How do we reproduce it?

**Follow the next HTTP calls**:

- create an organization with basic auth and keep the returned org_id - _POST /api/orgs_ with body _{"name":"Org A"}_
- switch to the created organization - _POST /api/user/using/{org_id}_
- create an auth key with basic auth - _POST /api/auth/keys_ with body _{"name":"some name","role":"Admin"}_
- create a folder with Bearer token auth using the previoulsy created auth key - _POST /api/folders_ with body _{"uid":"some-uid","title":"some name"}_

### 
# What Grafana version are you using?

v9.4.7 (4add91f03d)

### 
### Grafana Platform?

Docker

### Is this a Regression?

None

### Are Datasources involved?

Postgres datasource

### Anything else to add?

The Folder HTTP API is working correctly in my local environment, but not in DEV and PROD.
Using DEBUG logs I cannot find any useful information.

**Comment by usmangt** [comment]
Hi @kaskaz,

Thanks for opening this issue.

Does your DEV and PROD env. uses the same version as in your local env. i.e. v9.4.7 ?

**Comment by kaskaz** [comment]
I did a fresh deploy both on Local and Dev environments and I'm experiencing the same behavior.
I did it to debug, because the Dev instance could be in a bad state.

**Comment by kaskaz** [comment]
My problem is solved!
I could figure out through Grafana logs that calls from Postman were done with HTTP instead of HTTPS.
By receiving a redirect Postman reverts to POST to GET calls.
