### ISSUE TITLE
[Feature request] Drop invalid values

### ISSUE THREAD

**Issue by mje-nz** [grafana/grafana#7083]
I have various sensors logging to InfluxDB approximately (but not exactly) every half hour, with a dashboard showing line graphs of the values over time. Sometimes the sensors **give invalid readings**, in which case I don't want to plot that point and don't want the line to connect across the gap. InfluxDB does not support `null` or `nan` values; the InfluxDB idiom for invalid or missing data is to add a field like `invalid=1`.

As far as I can tell there isn't a way of working with schemas like that in Grafana at the moment. I propose the InfluxDB query editor could have an option to replace a point with `null` if it meets a given condition (e.g. field greater than threshold, field equal to sentinel value, etc). Here's a mockup:

<img width="671" alt="drop if mockup" src="https://cloud.githubusercontent.com/assets/6166539/21517729/611fc4e6-cd46-11e6-82d3-cdc03166a830.png">

I'd be happy to implement this (or something similar if anyone has a better suggestion) if someone could point out where to start in the codebase.

**Comment by torkelo** [comment]
I think the drop if part need to be in InfluxDB query language and not processed by grafana, make more sense. 


Have you tried adding a where condition and filtering out invalid values? Then have a fill(null)
