### ISSUE TITLE
Cannot rename/alias column that shows count

### ISSUE THREAD

**Issue by pramit46** [grafana/grafana#7084]
I have the following query: 
SELECT count("score_count") AS "Score Count" FROM "autogen"."Score" WHERE score_count>0 GROUP BY "score_type"

If I Alias them as $tag_CI, then I see the following table:
```
                      values
score_type_I             2
score_type_II            5

```

How can I rename the 'values' column to give it some other name (Score Count)?

**Comment by torkelo** [comment]
Try $col

**Comment by pramit46** [comment]
if I use $col, it shows:
```
                     values
Score Count             2
Score Count             5

```

I need to rename the column header 'values', not the rows

**Comment by torkelo** [comment]
What are your Table panel options?

**Comment by pramit46** [comment]
![capture_pie](https://cloud.githubusercontent.com/assets/6136856/21522639/77415c8a-cd2d-11e6-92a0-5fcfeb13e0d2.PNG)

**Comment by pramit46** [comment]
Apologies. I should have mentioned that I'm showing the table as part of a pie chart. So the table has very limited options.

**Comment by torkelo** [comment]
ok, dont think that panel supports changing the legend value header.

**Comment by pramit46** [comment]
Then what is the work around? Can I submit a feature request?
