### ISSUE TITLE
Grafana: Migration Error because of a wrong query

### ISSUE THREAD

**Issue by danielmichalichyn** [grafana/grafana#70849]
### 
# What went wrong?

**What happened**:

  - A upgrade from version 8.5 to version 9.4 cause a migration error.

**What did you expect to happen**:

  - The new version be migrated correctly

### 
# How do we reproduce it?

Migrate from version v8.5 to version v9.4.13

### 
# What Grafana version are you using?

v9.4.13

### Anything else to add?

Investigating a little bit on this, the following code seems to have a bug on the SQL Query:
- pkg/services/sqlstore/migrations/accesscontrol/admin_only.go
![image](https://github.com/grafana/grafana/assets/52325588/ce6cfed8-d825-4fbf-b59e-4d329cf3cbe7)

The GROUP BY on the query is wrong.
This is log and the error that is thrown when the migration is executed:

```
logger=migrator t=2023-06-28T14:50:15.301284943Z level=debug msg="Skipping migration: Already executed" id="managed folder permissions alert actions repeated migration"
logger=migrator t=2023-06-28T14:50:15.302062541Z level=info msg="Executing migration" id="admin only folder/dashboard permission"
logger=migrator t=2023-06-28T14:50:15.302098591Z level=debug msg="Executing code migration" id="admin only folder/dashboard permission"
logger=migrator t=2023-06-28T14:50:15.304197074Z level=error msg="Executing migration failed" id="admin only folder/dashboard permission" error="pq: column \"dashboard.uid\" must appear in the GROUP BY clause or be used in an aggregate function"
logger=migrator t=2023-06-28T14:50:15.304229652Z level=error msg="Exec failed" error="pq: column \"dashboard.uid\" must appear in the GROUP BY clause or be used in an aggregate function" sql="code migration"
Error: ✗ migration failed (id = admin only folder/dashboard permission): pq: current transaction is aborted, commands ignored until end of transaction block

```

**Comment by linoman** [comment]
A few things to consider.

1. Could you verify that the `dashboard.id` is a Primary Key? The `dashboard.id` should be the Primary Key. Please set it as PK.
2. Can you migrate to 9.5 instead of 9.4?

**Comment by JuliaAlves** [comment]
Hey @danielmichalichyn, how did you solve this problem? I am facing the same error

**Comment by JuliaAlves** [comment]
For future reference, I just changed the `dashboard` table to use `id` as the primary key and it worked perfectly
(`ALTER TABLE dashboard ADD PRIMARY KEY (id);`).
