### ISSUE TITLE
[Feature request] Add option to not connect lines over missing data

### ISSUE THREAD

**Issue by mje-nz** [grafana/grafana#7086]
I have various sensors logging to InfluxDB approximately (but not exactly) every half hour, with a dashboard showing line graphs of the values over time. Sometimes the sensors **do not respond**, in which case I don't want the line to connect across the gap. I realise that this is straightforward with `SELECT mean(value) GROUP BY time($interval) fill(null)` and that's a perfectly reasonable way to do it with higher-frequency data, but in my case I'd have to downsample to hourly or less which would leave me without very much data to graph.

I propose an option to insert a null when there's a gap of longer than a given time. Here's a mockup:
<img width="263" alt="max gap mockup" src="https://cloud.githubusercontent.com/assets/6166539/21518538/0d74518a-cd4c-11e6-80be-4fab6395852b.png">

I'd be happy to implement this (or something similar if anyone has a better suggestion) if someone could point out where to start in the codebase.

**Comment by torkelo** [comment]
think this makes more sense as a feature in the Time series query & transformation engine (so in the TSDBs), could also be done via Grafana Meta Queries (future feature) https://github.com/grafana/grafana/issues/3677

**Comment by alexinthis** [comment]
Mej, did you ever get this working? I am after the same feature.

**Comment by simonettoa** [comment]
Hey @mje-nz  or @alexinthis; a feature like this could be awesome! Did you find any workaround? thanks

**Comment by simonettoa** [comment]
thanks for the reply. 
I know that feature, the problem is that we have sensors that send values but it could be that there is a time gap between the values and it goes, i.e. from 34, then no communication for 1h and then back and send to 40; the timeseries is connecting that points; so I don't have in the db any null values.
 
I've tried to use the function `$__timeGroup(datetime,'4m', NULL) AS "time"` as you can see in the image attached but is changing the datetime and is not what we want.

![2022-09-09_08-22](https://user-images.githubusercontent.com/7147626/189285321-b3a0542a-e89b-439f-b89c-ae451af7fc92.png)

**Comment by alexinthis** [comment]
Hey, sorry my message wasn't  very helpful. I am not totally sure if it will fix your way of doing it but it might put you in the right direction. I am also using InfluxQL to pull my data. No idea why I am doing it this way, everything just updated and it seemed like the way to do it even though I find it 1000 times more confusing. 

I just fixed mine up by changing the createEmpty from false to true, so I assume that means on my graph I am creating empty readings of NULL value even if there is no data there to aggregate. 

Hope this helps. 

![image](https://user-images.githubusercontent.com/56566006/189289122-e157457c-5b22-4c27-b700-35eb84c86e2e.png)

**Comment by simonettoa** [comment]
We're using Timescale db to save the data (based on Postgres). I don't know if I can apply similar queries to our data; I'll will try.

As you can see the problem using these sort of data "aggregator" functions is that they change the datetime from the original value and we don't want it. As you can see in the first image in the "stack_1_power" column, there is a gap of the data of about 14h; but it goes from zero value to 63.1.
 
![2022-09-09_09-08](https://user-images.githubusercontent.com/7147626/189293152-699c881b-478c-4913-bbc8-1e71fc6f5a91.png)


![2022-09-09_09-09](https://user-images.githubusercontent.com/7147626/189293175-f01b1c01-4e6a-43ca-afa2-171ea67011af.png)

**Comment by leeoniya** [comment]
we actually have a way to do this internally (disconnect over threshold): https://github.com/grafana/grafana/blob/14f8e18978b0631fbc1bf00705b7163b8a7b923f/packages/grafana-ui/src/components/GraphNG/nullInsertThreshold.test.ts#L55

but it's not currently exposed to users as settable config option. we were still thinking about how to expose this setting alongside the current Connect values setting without it bein super confusing :)

**Comment by simonettoa** [comment]
Hey @leeoniya ! If I've interpreted it in the right way that above is a functionality in Grafana not exposed to the users yet?

At the beginning I thought that the actual function wasn't working properly, I mean the 'Graph style'.'Connect null values' because I misinterpreted that it means null values in time; but I get it could be confusing; at the same time as exposed above the user could have points connected even if there's a 'hole' of time.

thanks.

**Comment by leeoniya** [comment]
yeah. you may want to do _both_, connect across nulls < maxThreshold and disconnect across spans > minThreshold.

we made a couple internal mockups of a possible combined UI, but i feel like it needs to be more clear that Disconnect does not require nulls in the data (only a big enough 'hole') to draw a gap, but Connect will ignore nulls in your data and _not_ draw the gap.

![image](https://user-images.githubusercontent.com/43234/189360011-49bff41e-1f0f-4552-aeb1-13b538026956.png)

**Comment by shrx** [comment]
How about naming the options "Connect across null values" and "Disconnect gaps between values"? This makes it clearer to the user where null values are expected in the data.

**Comment by cesuper** [comment]
> yeah. you may want to do _both_, connect across nulls < maxThreshold and disconnect across 'holes' > minThreshold.
> 
> we made a couple internal mockups of a possible combined UI, but i feel like it needs to be more clear that Disconnect does not require nulls in the data (only a big enough 'hole') to draw a gap, but Connect will ignore nulls in your data and _not_ draw the gap it would normally draw.
> 
> ![image](https://user-images.githubusercontent.com/43234/189360011-49bff41e-1f0f-4552-aeb1-13b538026956.png)
> 

Hello! Is this feature available in any grafana release? How can I try it on my dataset?

**Comment by leeoniya** [comment]
it will be available in v10.1
