### ISSUE TITLE
Dashboards: Deep links do not carry over information about selected time range in a query

### ISSUE THREAD

**Issue by JohnJMartins** [grafana/grafana#70865]
### 
# What went wrong?

**What happened**:

 A user of the Azure Monitor plugin for Grafana reported this issue. It exists with deep links that link from a dashboard panel to an outside source, which in this case, is a panel with an azure monitor query linking out to the Azure Portal.

![image](https://github.com/grafana/grafana/assets/77704161/78b825ea-45d9-4156-8c9c-64fd883bd3d5)

Seen here is the "View in Azure Portal" link that is clicked, and the fact that a time frame has been set in the query as well in Grafana UI. When the link is clicked, the Azure Portal is opened with the correct query input correctly, yet it defaults to a 24 hour timeframe in all cases.

![image](https://github.com/grafana/grafana/assets/77704161/15152b18-1224-48b5-9422-de6e1d5a1252)

**What did you expect to happen**:

  If possible, we would like to see the query time frame automatically set to the Grafana timeframe from the dashboard panel or the timeframe that is set in the query.

![image](https://github.com/grafana/grafana/assets/77704161/98a468f1-6c8b-42c8-9db7-739e3c2b01b4)

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a dashboard with a panel that uses a query with a set timeframe. 

**Step 2**:

- Create a deep link from the dashboard that carries the query across and check to see if any information is about the timeframe is transferred over with the deep link.

### 
# What Grafana version are you using?

v9.4.12

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows 11

### Is this a Regression?

None

### Are Datasources involved?

Azure Monitor

**Comment by usmangt** [comment]
Hi @JohnJMartins,

Thanks for opening this issue.

Can you please try to reproduce this in the current stable version of Grafana i.e. version 10?

Also, if this is reproducible in version 10 then please provide a sample query for testing.

**Comment by srisakthimaheswari** [comment]
Hi @usmangt,
This issue is in Azure Managed Grafana instance. I don't see any option to change the version while creating the resource.

**Comment by aangelisc** [comment]
Hi, I've replicated this locally and have a fix in #71841

**Comment by srisakthimaheswari** [comment]
Thanks for the fix!
