### ISSUE TITLE
Docs: Consider moving "work with data frames" from "extend a plugin" to "develop a plugin"

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#70873]
In the plugins reorganization PR, part 1, we are moving "Work with data frames" to the "extend" rather than "develop" subfolder. Received feedback that the task is so fundamental that it should be put under develop. I'd like to consider this further for the next reorg.

Relates to: 
https://github.com/grafana/grafana/pull/69864

**Comment by GrafanaWriter** [comment]
@josmperez - should this move to Blocked, Backlog, or Needs Research? The issue is two weeks old.

**Comment by josmperez** [comment]
This will be resolved with merger of https://github.com/grafana/plugin-tools/pull/417
