### ISSUE TITLE
[Bug] moving_average return error

### ISSUE THREAD

**Issue by kolargol** [grafana/grafana#7087]
Grafana: 4.0.2
Datasource: Influx 1.1.1
OS: Linux

Setting moving_average returns Influx ERROR:
 "error": "error parsing query: aggregate function required inside the call to moving_average",

query:

SELECT moving_average("commands_insert", 10) FROM "mysql" WHERE "host" = 'somehost.com' AND time > now() - 24h GROUP BY time(5m) fill(null)

**Comment by torkelo** [comment]
You need an aggregation function as well
