### ISSUE TITLE
Managed Alerting UI: RefID Hidden with Narrow Window View

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#70900]
### 
# What went wrong?

**What happened**:

RefID gets hidden from view, should be "A":

![image](https://github.com/grafana/grafana/assets/1692624/038c8712-37c2-4c21-87d4-af8cb0c34305)

![image](https://github.com/grafana/grafana/assets/1692624/873a8366-77c9-424c-ab54-934e6692b550)

Or Partly Cut off:

![image](https://github.com/grafana/grafana/assets/1692624/903cf5cc-b415-4740-a715-d63f758e3a9f)

**What did you expect to happen**:
To look like either "A" or "B" (The box around B looks nicer to me):

![image](https://github.com/grafana/grafana/assets/1692624/cd695802-6f5d-4d2b-aed7-b90536bbcb18)

### 
# How do we reproduce it?

See screenshots in what happened

### 
# What Grafana version are you using?

703bf4afcc0

**Comment by soniaAguilarPeiron** [comment]
We are currently addressing [this issue](https://github.com/grafana/grafana/issues/68190), and it might potentially resolve the problem. If it doesn't, we can include the fix within the same pull request since we are already redesigning the header.
