### ISSUE TITLE
[Bug] 401 with nginx reverse proxy basic auth

### ISSUE THREAD

**Issue by uschtwill** [grafana/grafana#7090]
- What Grafana version are you using?
**4.0.2**
- What datasource are you using?
**Prometheus**
- What OS are you running grafana on?
**Docker / Ubuntu 14.04**
- What did you do?
**Put jwilder's nginx reverse proxy (https://github.com/jwilder/nginx-proxy) in front of Grafana and enables SSL and Basic Auth.**
- What was the expected result?
**See the Grafana login screen after filling in the basic auth credentials.**
- What happened instead?
**The browser keeps asking for basic auth credentials, as long as I put them in. Once cancelled, it throws a 401.**

Seems very similar to this one: https://github.com/grafana/grafana/issues/1673

**Comment by torkelo** [comment]
Make sure you filter out the basic auth header so it never reaches grafana, or / and disable basic auth in Grafana

**Comment by czerasz** [comment]
Adding `GF_AUTH_BASIC_ENABLED=false` helped
