### ISSUE TITLE
Grafana Don't get the detailed data of 14 days ago

### ISSUE THREAD

**Issue by shencan** [grafana/grafana#7091]
Please prefix your title with [Bug] 

Please include this information:
- What Grafana version are you using?
  ```grafana-3.0.4-1464167696```
- What datasource are you using?
 ``` cloudwatch```
- What OS are you running grafana on?
 ``` Centos 6.5 ```
- What did you do?
 ``` Query data before 14 days ```
- What was the expected result?
 ``` Can Not Get data```

**Comment by shencan** [comment]
Now AWS Cloudwatch  It can store the data of 90 days. I use the cloudwatch API to obtain the data to 14 days before is ok.

**Comment by mtanda** [comment]
please check this.
https://github.com/grafana/grafana/pull/6547
 Will be supported.

**Comment by shencan** [comment]
@mtanda  thank you  I have found the reason
