### ISSUE TITLE
[Feature request] Export of json in predictable keyword order

### ISSUE THREAD

**Issue by cbos** [grafana/grafana#7092]
We have a template of the dashboard in Git. 
Based on some variable we generate a new dashboard and upload it via the REST API.

We we then make modifications and view the json again and compare that with the original, then the json is in a different order, that makes it hard to see what is changed. 
If the keys are in alphabetical order then the order is always the same, which makes the compare easy.

**Comment by DanCech** [comment]
Good point, I can see how this will become an issue as people build more workflows like this.
