### ISSUE TITLE
Enable query editor builder for Mimir/Loki rules

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#70940]
We've recently enabled the query editor builder for recording rules

We should do the same for Mimir/Loki alerting rules to keep the experience consistent

**Comment by gillesdemey** [comment]
Here are some of the features GMA editor has in additional to what we have currently;

**That don't apply to cloud rules**
- [x] Time range selection (does not apply to cloud, they're all instant vectors)
- [x] Max data points and min interval (does not apply)
- [x] Set as alert condition (does not apply, it's always the alert condition)
- [x] Run queries button (there's already preview button ¯\_(ツ)_/¯ )
- [x] Options like legend, min step, format (time series / table / heatmap) and type (range / instant) these don't apply either

**That we could add**
- [ ] Kick start and explain
- [ ] Switching between builder and code

There's generally two approaches we can take to bridge that gap;

1. We add a bunch of config parameters to the Prometheus editor to omit whatever isn't relevant in the context of a Prometheus alert – makes the component harder to reason about and makes the component a shared maintenance burden for several teams.
1. We re-build the existing editor minus what doesn't apply using composition of the internal components that make up the Prometheus editor.
