### ISSUE TITLE
Queries with Azure monitor not working

### ISSUE THREAD

**Issue by MalinSchei** [grafana/grafana#70941]
### 
# What went wrong?

**What happened**:

  - We use a lot of azure monitor (application insights) for our dashboards. We recently just upgraded from 8.4 to 10.0.1 due to all the new tools. Now our dashboard tiles shows the same information for startofday, 7 days and last year. When you click on the query you get correct information in portal.azure

**What did you expect to happen**:

  - I expect the respected tiles to show accurate information. 

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and go to our Azure monitor dashboard

**Step 2**:

- When data loads it looks like this:
- 
![image](https://github.com/grafana/grafana/assets/91475810/2a20bca7-8438-497e-bedd-a55c94f5023d)

Here is top left tile:
![image](https://github.com/grafana/grafana/assets/91475810/9658baf1-48cc-41e1-b7f3-38bcb8d51650)

Here is left mid tile:
![image](https://github.com/grafana/grafana/assets/91475810/7009c6bb-d0de-4793-aea9-820b9a1cf583)

Here is bottom left tile (this one uses the variables at the top):
![image](https://github.com/grafana/grafana/assets/91475810/f4c2f305-dcda-47ce-822d-75e7284b69da)

**Step 3**:

- There are no error messages in the developer console:
- 
![image](https://github.com/grafana/grafana/assets/91475810/7c795767-447a-4117-9be0-d379b45f8a18)

This is what I get if I click on the last 7 days (left middle tile) in Azure - which is the result I should be getting:
![image](https://github.com/grafana/grafana/assets/91475810/0fe1cf97-66f4-4c40-b3f9-d1c6ca8394e1)

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Windows 11

### User's Browser?

Opera GX

### Is this a Regression?

Yes

### Are Datasources involved?

Azure monitor - logs

**Comment by MalinSchei** [comment]
After some further inspection, it seems like now the timestamp I'm using in the variables and queries gets ignored if the time range is set to 15 minutes etc:
![image](https://github.com/grafana/grafana/assets/91475810/8e62ae86-8366-446c-8d10-0a0511746fec)

![image](https://github.com/grafana/grafana/assets/91475810/c007f6de-d08f-4335-9d54-fcbc6c6c46b8)

This still kind of poses an issue due to the fact that Grafana now completely ignores what's in the queries.

**Comment by ludokriss** [comment]
Hey,
I noticed the same thing and the reason could be what the infobox here refers to:
https://grafana.com/docs/grafana/latest/datasources/azure-monitor/query-editor/#logs-query-examples

All azure monitor data gets automatically filtered due to the "Implicit dashboard time range usage". Not 100% sure it's what you see, but quite similar to what got me at least

**Comment by aangelisc** [comment]
Hi @MalinSchei, @ludokriss is correct. To improve the efficiency of queries an update was made to make use of the dashboard time range by default. If you then specify a time range directly in the query the intersection of the two will be used (as per the Azure documentation). 

From what I can see the above doesn't seem to be holding true. I will investigate this further.

**Comment by MalinSchei** [comment]
@aangelisc I think the data rings true, I just had the wrong time selected in the 2 screenshots. You can completely disregard this post as when I select "This year so far" I get the correct numbers

**Comment by aangelisc** [comment]
Thanks @MalinSchei! I'll close this issue 😊
