### ISSUE TITLE
Alerting: No Grafana notifications for Prom Alert Rules from Prometheus datasource 

### ISSUE THREAD

**Issue by didil** [grafana/grafana#70952]
### 
# What went wrong?

I have a grafana instance set up that is connected to a prometheus instance as datasource. It pulls alert rules from the prometheus instance and I can see the alerts and their status in the grafana UI.
However the grafana alert notifications are not sent for those alert rules. But I do receive alert notifications for the other alerts that are defined directly in the Grafana UI. 

### 
# How do we reproduce it?
- Set Alert rules in a Prometheus instance
- Setup Grafana with email alert notifications for all alerts 
- Connect Grafana to the Prometheus instance as a datasource
- Make Prometheus alert rules fire

### 
# What Grafana version are you using?

v9.5.3 

### 
### Grafana Platform?

Kubernetes

### User's OS?

bottlerocket linux

### Is this a Regression?

None

### Are Datasources involved?

Prometheus

**Comment by grobinson-grafana** [comment]
Hi! :wave:

When a Prometheus datasource is configured in Grafana that also has alert rules, the alerts for those rules are not sent to Grafana. Grafana in this case just acts as a user interface for Prometheus. You'll either need to set up an Alertmanager for Prometheus or move the Prometheus rules to Grafana Managed Alerts.

**Comment by didil** [comment]
Thanks @grobinson-grafana ! That's what we realized after a while. Your explanation is very clear and I feel like it would be a great addition to the docs.

**Comment by ohdearaugustin** [comment]
This would be a really nice addition to the docs, it is absolutely not clear and the interface even show firing alerts.
