### ISSUE TITLE
[Bug] Graph doesn't display data for last days of the month 

### ISSUE THREAD

**Issue by peterdk** [grafana/grafana#7096]
Please include this information:
- What Grafana version are you using? Version 4.1.0-beta1 (commit: v4.1.0-beta1)
- What datasource are you using? InfluxDB 1.1.1
- What OS are you running grafana on? Ubuntu 14.04 LTS 64 bit
- What did you do? Open dashboard with graphs, with range selected as last 30 days
- What was the expected result? Graphs that display data from last 30 days
- What happened instead? Graphs stop at 27 December, and lets 28,29 December empty.

Normally, when I display the graphs for the last 30 days they render perfectly until the current day. However, when we reach the end of the month, suddenly the data does not get displayed for the last days of that month. After the 1st of the next month rendering resumes and also these last days of previous month get displayed ok.

I had this issue last month, but it solved itself after reaching 1st of the month. This month however it happens again.

It only happens to the graphs with a 'non-negative-derivative(data,1d)'. Another graph that just uses value('mean') has it's data displayed correctly.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
![cutoff_graph](https://cloud.githubusercontent.com/assets/668007/21547637/aa1c56e0-cde7-11e6-8e22-0e24adac008e.png)
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
Request:

> Request URL:https://grafana.private.com/api/datasources/proxy/1/query?db=telegraf&q=SELECT%20non_negative_derivative(mean(%22value%22)%2C%201d)%20FROM%20%22private.backend.ruby.sidekiq.scan_result_worker%22%20WHERE%20time%20%3E%20now()%20-%2030d%20GROUP%20BY%20time(1d)%20fill(null)%3BSELECT%20non_negative_derivative(mean(%22value%22)%2C%201d)%20FROM%20%22private.backend.ruby.preferred_apps.requests%22%20WHERE%20time%20%3E%20now()%20-%2030d%20GROUP%20BY%20time(1d)%20fill(null)%3BSELECT%20non_negative_derivative(mean(%22value%22)%2C%201d)%20FROM%20%22private.backend.ruby.appdata.submit.requests%22%20WHERE%20time%20%3E%20now()%20-%2030d%20GROUP%20BY%20time(1d)%20fill(null)&epoch=ms
> Request Method:GET
> Status Code:200 OK
> Remote Address:37.97.195.15:443
> Response Headers
> view source
> Access-Control-Allow-Origin:*
> Connection:keep-alive
> Content-Encoding:gzip
> Content-Length:1073
> Content-Type:application/json
> Date:Thu, 29 Dec 2016 15:47:03 GMT
> Request-Id:0b3dc194-cdde-11e6-8077-000000000000
> Server:nginx
> X-Influxdb-Version:1.1.1
> Request Headers
> view source
> Accept:application/json, text/plain, */*
> Accept-Encoding:gzip, deflate, sdch, br
> Accept-Language:en-US,en;q=0.8,nl;q=0.6
> Authorization:Basic cGV0ZXI6NDAxQUlLdXM=
> Connection:keep-alive
> Cookie:grafana_sess=2a55cda27d4cf290; grafana_user=admin; grafana_remember=bff2303dfbbf28475003a2e90f93bccaf74421adfba910bf
> Host:grafana.private.com
> Referer:https://grafana.private.com/dashboard/db/daily-stats?panelId=4&fullscreen
> User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> Query String Parameters
> view source
> view URL encoded
> db:telegraf
> q:SELECT non_negative_derivative(mean("value"), 1d) FROM "private.backend.ruby.sidekiq.scan_result_worker" WHERE time > now() - 30d GROUP BY time(1d) fill(null);SELECT non_negative_derivative(mean("value"), 1d) FROM "private.backend.ruby.preferred_apps.requests" WHERE time > now() - 30d GROUP BY time(1d) fill(null);SELECT non_negative_derivative(mean("value"), 1d) FROM "private.backend.ruby.appdata.submit.requests" WHERE time > now() - 30d GROUP BY time(1d) fill(null)
> epoch:ms

Response:
`{"results":[{"series":[{"name":"private.backend.ruby.sidekiq.scan_result_worker","columns":["time","non_negative_derivative"],"values":[[1480377600000,3655.3784301062115],[1480464000000,4948.4942129629635],[1480550400000,4717.467708333337],[1480896000000,3884.777199074074],[1480982400000,4505.381481481482],[1481068800000,4901.2571759259245],[1481155200000,5303.647337962964],[1481241600000,5213.857638888887],[1481328000000,5065.644675925927],[1481414400000,4604.593171296296],[1481500800000,4326.149884259263],[1481587200000,4750.648611111108],[1481673600000,4954.457175925927],[1481760000000,5336.320254629631],[1481846400000,5820.058449074073],[1481932800000,5240.156134259254],[1482019200000,4646.485879629632],[1482105600000,4432.620486111118],[1482192000000,4961.52534722221],[1482278400000,4819.7065972222335],[1482364800000,4794.768750000003],[1482451200000,4646.243171296286],[1482537600000,4275.361921296295],[1482624000000,3819.286226851851],[1482710400000,3772.3466435185255],[1482796800000,3847.7145833333343]]}]},{"series":[{"name":"private.backend.ruby.preferred_apps.requests","columns":["time","non_negative_derivative"],"values":[[1480377600000,3787.8556448368035],[1480464000000,5176.819097222222],[1480550400000,4900.657986111095],[1480896000000,4031.6697916666667],[1480982400000,4680.968518518519],[1481068800000,5106.500925925926],[1481155200000,5461.163888888888],[1481241600000,5364.8499999999985],[1481328000000,5220.595254629632],[1481414400000,4783.953587962958],[1481500800000,4495.607523148152],[1481587200000,4901.037152777775],[1481673600000,5113.570370370369],[1481760000000,5440.228935185187],[1481846400000,5958.779976851853],[1481932800000,5345.737384259257],[1482019200000,4830.827430555553],[1482105600000,4607.049074074079],[1482192000000,5175.3032407407445],[1482278400000,5007.156018518523],[1482364800000,4961.6024305555475],[1482451200000,4848.246527777781],[1482537600000,4435.453819444447],[1482624000000,4004.844791666663],[1482710400000,3975.3388888888876],[1482796800000,4097.527199074073]]}]},{"series":[{"name":"private.backend.ruby.appdata.submit.requests","columns":["time","non_negative_derivative"],"values":[[1480377600000,881.8501506156172],[1480464000000,1327.5232638888847],[1480550400000,1463.0542824074073],[1480896000000,1092.6268518518518],[1480982400000,1297.4490740740744],[1481068800000,1431.948611111111],[1481155200000,1490.2476851851852],[1481241600000,1446.3420138888887],[1481328000000,1430.2399305555555],[1481414400000,1288.772222222222],[1481500800000,1175.104398148149],[1481587200000,1351.4831018518526],[1481673600000,1411.6212962962945],[1481760000000,1418.7797453703715],[1481846400000,1494.993171296297],[1481932800000,1299.9245370370372],[1482019200000,1188.2483796296292],[1482105600000,1208.9442129629606],[1482192000000,1389.4943287037058],[1482278400000,1410.6090277777766],[1482364800000,1439.5335648148139],[1482451200000,1380.3927083333365],[1482537600000,1269.2826388888861],[1482624000000,1077.7099537037066],[1482710400000,1053.3128472222197],[1482796800000,1085.8040509259263]]}]}]}
`

**Comment by torkelo** [comment]
since your query contains `WHERE time > now() - 30d` you should at least get 30 days of data. If you don't then maybe it's a bug in InfluxDB. The data from influxDB you pasted shows the last timestamp at 
Tue Dec 27 2016 01:00:00 GMT+0100 (CET) which is the same as what Grafana shows
