### ISSUE TITLE
Add PromQL to Google Cloud Monitoring

### ISSUE THREAD

**Issue by asimpson** [grafana/grafana#70962]
Use the monocao editor package to create something like the [QueryField in Prometheus](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/components/PromQueryField.tsx). 

Alternatively, we use a text input for now that allows rudimentary `PromQL` but no additional features like syntax highlighting or tab completion but allows us to ship quicker and iterate down the road. 

Maybe https://github.com/prometheus-community/monaco-promql helps here?

**Comment by Helloworld-can** [comment]
Is someone working on this?

**Comment by asimpson** [comment]
@Helloworld-can yep, @bossinc is going to tackle this.

**Comment by nickmoorman** [comment]
Hello!  I was wondering what release(s) we can expect to see this in, and if there's any ETA on said release(s).  Thanks in advance!

**Comment by asimpson** [comment]
@nickmoorman 10.2 should be coming soon!

**Comment by holmesb** [comment]
v10.2 is [here](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#1020-2023-10-24) minus this PR. 

![old_GCM](https://github.com/grafana/grafana/assets/5072156/1465c484-7b2b-4460-8ee3-037e035d490a)

Why was it omitted?

**Comment by holmesb** [comment]
v10.2 is here and so is PromQL in GCM 🎉

**Comment by asimpson** [comment]
@holmesb Currently, GCM doesn't have the concept of a default query type. You are also correct that would be a new issue :smile:

**Comment by roberth1988** [comment]
Awesome :) - but it seems on the "Variables" area PromQL is missing

**Comment by asimpson** [comment]
@roberth1988 that is true, however MQL isn't supported in the template variable area either.
