### ISSUE TITLE
[Bug] New Data Only

### ISSUE THREAD

**Issue by 5k3105** [grafana/grafana#7097]
Using grafana-4.0.0-beta1 on windows, influxdb-1.0.2-1.

Hi!

My plots start to get really slow after a days worth of data. Set to refresh every ten seconds I notice the queries sent to the database request all information for say the past day, every ten seconds. However, after the first query - I don't need the entire days data since it is already plotted, I just need the last five seconds to add to that plot. So instead of querying for the past days data every ten seconds, I want it to query that day only at the start of the session, and as it incrementally updates the plot, query for only the last ten seconds of data to add to it.

So either I didn't read the documentation right (which seems to be out of date many times) or grafana keeps querying the database for more information than it really needs.

Thanks - and great work on this! It helps the scientist here customize plots which would otherwise be left to the developers.

**Comment by torkelo** [comment]
For a large set of queries this is not possible (for example queries that apply transformation & analytics like forecasting, moving averages, integrals etc). 

If the query is slow make sure you have a reasonably group by time.

**Comment by 5k3105** [comment]
Hi Thanks - but 'group by' requires I have an aggregate function and I don't need an aggregate.

**Comment by torkelo** [comment]
you dont? why is that? Are you looking at very short time period or very few data points? But if that is the case then it makes no sense why your query takes time. Your query takes time make me think that it hits many data points and takes a long time for InfuxDB to process and return and for Grafana to process. if you do not have a group by time and an aggregation function and InfluxDB query can easily return many hundreds or millions of data points and hang your browser.

**Comment by 5k3105** [comment]
Your right. Sorry. Thank you!
