### ISSUE TITLE
[Bug] Graph panel Y Axis display

### ISSUE THREAD

**Issue by msteggink** [grafana/grafana#7099]
Please include this information:
- What Grafana version are you using? grafana-4.1.0-1482853587beta1.x86_64
- What datasource are you using? InfluxDB-1.1.1-1
- What OS are you running grafana on? CentOS7.3.1611
- What did you do? Add long description to the Y Axis
- What was the expected result? Stay within borders, as much as possible
- What happened instead?
It overflows into another graph. With a long description, it was bound to overflow the graph boundaries, but I'd expect it to use as much space inside the graph as possible.

Current graph height is 232px.
<img width="185" alt="screen shot 2016-12-30 at 15 54 58" src="https://cloud.githubusercontent.com/assets/13614464/21566964/a19236cc-cea8-11e6-8167-f9ab84f1fe40.png">

Also hiding the Y Axis still shows the label. This is confusing:
Deselecting "Show" hides the "Label" text field, but still shows it in the graph. I'd expect it to stay visible (not to be hidden, if the label is displayed anyway).

<img width="200" alt="screen shot 2016-12-30 at 15 55 34" src="https://cloud.githubusercontent.com/assets/13614464/21566992/d71f87b8-cea8-11e6-80fc-23f26a926c88.png">
<img width="332" alt="screen shot 2016-12-30 at 15 55 38" src="https://cloud.githubusercontent.com/assets/13614464/21566995/daeb382e-cea8-11e6-9fe9-c30c4f26c069.png">

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/083a42942fcaf7507515a95c862b1e64564088c5
