### ISSUE TITLE
reduce 5 second refresh graph update jank

### ISSUE THREAD

**Issue by ceeaspb** [grafana/grafana#710]
Hello, I'm looking at live stats that are updated in the backend every second.
the update frequency of 5 seconds provides the most "real time" experience, but as it updates the visual effect is a "jank" which is distracting.

flot should allow you to set the x axis min/max without querying or updating the data.

so the proposal would be to update the data the same as before, every 5 seconds,
but in between, every X ms (to be determined /configurable, but possibly 200ms) the current x axis min/max is updated more frequently and chart redrawn to make the lines appear to move across the chart smoothly.

this will not impact the metrics server, but there will be cpu burn from the flot and browser executing the translation. lower powered clients may need a slower update to reduce cpu for example.

this would provide a smooth user experience to live charts, and less cognitive distraction from the jank.

WDYT?

**Comment by Dieterbe** [comment]
> You can add 1s as an option in the auto refresh option. This is done in the dashboard settings, timepicker tab. 

cool! did not know this. works great

**Comment by torkelo** [comment]
closing due to lack of interest

**Comment by poleguy** [comment]
This would be nice when demonstrating the software to the CEO levels. (I'm about to do that.) You only have seconds to wow them, and waiting 5 second between update chunks is an eternity when you have a room full of people looking at a screen after you press "go" on your demo.

Basically I see this suggestion as a way to have one second data updates, sub one-second screen updates for averages, etc, and maintain 5 second granularity for grafana (is that what's happening in the background?). But you could essentially have what appear to be very fast/frequent updates.

The tradeoff would be  5 seconds of latency (delay from real-time). That might be a good tradeoff, as nobody actually could tell it was delayed without a reference to the real world.

Obviously not a high priority, but if someone wants to code it up and do a PR I'd give them a thumbs up. (Any bored CS students with too much time out there?)

Just my two cents.

**Comment by Dieterbe** [comment]
@ryantxu has done some work on streaming in general and smoothly sliding a chart by means of high frequency rerendering in particular.

**Comment by suikast42** [comment]
Is there a regression with 7.0 ? 
![image](https://user-images.githubusercontent.com/5046525/82559868-a4198600-9b70-11ea-8af4-9c193928e60a.png)

![image](https://user-images.githubusercontent.com/5046525/82559903-b0054800-9b70-11ea-9717-d9100baf0d86.png)

**Comment by aknuds1** [comment]
@suikast42 Do you mean you've uncovered a bug? In that case, you might want to open an issue?

**Comment by lrosser2103** [comment]
Same here.  Changed in settings, but not available in drop down.
![Capture](https://user-images.githubusercontent.com/58376503/82737511-1d42e580-9cf7-11ea-8072-03b67ef2d2e6.PNG)
![Capture2](https://user-images.githubusercontent.com/58376503/82737532-4794a300-9cf7-11ea-8c01-16884cbeca5d.PNG)

**Comment by torkelo** [comment]
There is a new server setting to limit refresh (for admins to make sure users do not set this super low) , check docs config page for min refresh interval

**Comment by lrosser2103** [comment]
open grafana.ini with vi or nano and edit:
![Capture](https://user-images.githubusercontent.com/58376503/82740629-56d41a80-9d10-11ea-93e8-50c30d5bafd0.PNG)
restart grafana

**Comment by gulbulut** [comment]
changed in grafana.ini min_refresh_interval = 1s but still not available in drop down. Has anyone reached the solution?

**Comment by erichuang2013** [comment]
same here. still 5s in the drop down of refresh time.

**Comment by erichuang2013** [comment]
I know why now.  from [configuration.md](https://github.com/grafana/grafana/blob/9486f960d175b5c13fe55afa89829fe71188da8b/docs/sources/administration/configuration.md), "If you want to change a setting, you must delete the semicolon (;) in front of the setting before it will work." 

need to delete the leading semicolon.

**Comment by lucas-bremond** [comment]
Is there any way to configure Grafana to add `1s` to the _Auto refresh_ list by default today?

(so that I don't have to modify the settings of every single dashboard?)

Thanks!

**Comment by shinton-ps** [comment]
Appears to be a regression in v.9.3.1. I have confirmed that my 'min_refresh_interval' is 1s per below screenshot. If I try to change the possible intervals on a dashboard by adding an 'Xs' option where X is < 5, it will not accept that and my minimum possible update rate in the refresh drop-down menu is still 5s.

![image](https://user-images.githubusercontent.com/102676156/210663806-0b00805b-bf0f-46db-aa95-416c77f9bdf9.png)

**Comment by synapsedata** [comment]
Whats the path to grafana.ini file?

**Comment by jufy111** [comment]
Docker users can use the following environmental variable to set this without having to modify the grafana.ini file.
`GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s`

**Comment by sreevatsank1999** [comment]
Has this been resolved? 
None of the solution in here work. 
I am using `Version 11.0.0 (commit: 277ef258d4b9a5acdf2932347c6a4ca72d739b28, branch: HEAD)`

**Comment by Ramin-NXWF** [comment]
Im using Azure managed Grafana , how can I add 3s and 1s to the refresh list ? I dont have access to grafana.ini !

**Comment by HaojieGU1988** [comment]
> Docker users can use the following environmental variable to set this without having to modify the grafana.ini file. `GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s`

Does it work? I added that env in my yml file, but it still failed when i tried to change the 1s as interval
