### ISSUE TITLE
Alerting: File provisioning documentation should cover escaping $variables

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#71007]
Context: https://github.com/grafana/grafana/issues/70484
Docs: https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/

Alerting file provisioning supports interpolation of environment variables using the `$variable` syntax in most fields. This is mentioned in the [general provisioning documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables) but not in the alerting-specific one.

We should improve the documentation by covering:

1. How to interpolate environment variables in your alerting provisioning files.
2. How to avoid interpolation using `$$`.
3. Which fields are interpolated and which aren't. (ex. Labels are interpolated but Annotations aren't)

**Comment by GrafanaWriter** [comment]
@brendamuir - please triage and move into Backlog or In Progress?

**Comment by brendamuir** [comment]
Hey @JacobsonMT can you help me update the docs for this one? I am not sure what to add - it would be great if you could add it and tag me for review. Thanks!

**Comment by brendamuir** [comment]
Hey @JacobsonMT i've updated the provisioning docs with the new features for 10.2 - would be great to get this info in. Do you have any bandwidth to help?

**Comment by brendamuir** [comment]
@yuri-tceretian @alexweav can you help me with content for this ticket? thanks
