### ISSUE TITLE
Grafana: Application layer is hardcoding the port

### ISSUE THREAD

**Issue by mydailypuff** [grafana/grafana#71014]
### 
# What went wrong?

The issue is in grafana image: grafana/grafana:9.4.3
The container port is 80. I had given health ports as 80. But the application was not healthy.
When I changed the health ports to 3000(same as target port of service), the container was up and running and pod became healthy. It should pick the health port as container port

### 
# How do we reproduce it?

#deployment.yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"grafana","app.kubernetes.io/instance":"app-sbox-2x0-app-grafana","chart":"grafana-1.17.2","heritage":"Helm","release":"grafana"},"name":"grafana","namespace":"grafana"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"grafana"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"0%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"grafana","chart":"grafana-1.17.2","heritage":"Helm","release":"grafana"}},"spec":{"containers":[{"env":[{"name":"admin-user","valueFrom":{"secretKeyRef":{"key":"admin-user","name":"grafana"}}},{"name":"admin-password","valueFrom":{"secretKeyRef":{"key":"admin-password","name":"grafana"}}}],"envFrom":[{"configMapRef":{"name":"grafana-config-dashboards"}},{"configMapRef":{"name":"grafana"}}],"image":"grafana/grafana:9.4.3","livenessProbe":{"httpGet":{"path":"/api/health","port":3000,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":10},"name":"grafana","ports":[{"containerPort":80,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/api/health","port":3000,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":10},"resources":{"limits":{"cpu":0.1,"memory":"100Mi"},"requests":{"cpu":0.05,"memory":"50Mi"}}}],"serviceAccountName":"grafana-service-account"}}}}
  creationTimestamp: '2023-06-30T15:07:38Z'
  generation: 7
  labels:
    app: grafana
    app.kubernetes.io/instance: app-sbox-2x0-app-grafana
    chart: grafana-1.17.2
    heritage: Helm
    release: grafana
  name: grafana
  namespace: grafana
  resourceVersion: '154501292'
  uid: f29ed814-fa52-4216-8377-a9722a0a6864
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
        chart: grafana-1.17.2
        heritage: Helm
        release: grafana
    spec:
      containers:
        - env:
            - name: admin-user
              valueFrom:
                secretKeyRef:
                  key: admin-user
                  name: grafana
            - name: admin-password
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: grafana
          envFrom:
            - configMapRef:
                name: grafana-config-dashboards
            - configMapRef:
                name: grafana
          image: 'grafana/grafana:9.4.3'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: grafana
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: [80](url)
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: grafana-service-account
      serviceAccountName: grafana-service-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-07-03T06:16:00Z'
      lastUpdateTime: '2023-07-03T06:16:00Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-07-03T06:13:33Z'
      lastUpdateTime: '2023-07-03T06:16:00Z'
      message: ReplicaSet "grafana-575b6fbf75" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

#service.yaml

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"app-sbox-2x0-app-grafana","service":"grafana"},"name":"grafana","namespace":"grafana"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000}],"selector":{"app":"grafana"}}}
  creationTimestamp: '2023-06-30T17:57:41Z'
  labels:
    app.kubernetes.io/instance: app-sbox-2x0-app-grafana
    service: grafana
  name: grafana
  namespace: grafana
  resourceVersion: '153248198'
  uid: 803a2423-88c2-47d6-ae9d-613643ea5342
spec:
  clusterIP: 172.23.90.104
  clusterIPs:
    - 172.23.90.104
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

### 
# What Grafana version are you using?

grafana/grafana:9.4.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

**Comment by sakjur** [comment]
This sounds like a Helm problem? Please report problems with the Grafana Helm chart to https://github.com/grafana/helm-charts, those are developed independently of Grafana itself.
