### ISSUE TITLE
Dashboard: Problem showing distributions from heatmap

### ISSUE THREAD

**Issue by leahoswald** [grafana/grafana#71017]
### 
# What went wrong?

**What happened**:

Instead of seeing my panel I get an error since the upgrade to 10.0.0 (persists with 10.0.1).

> Prometheus heatmap transform error: data should be a time series

The panel is a bar gauge and the query looks like this

![Screenshot2023-07-03_10-35-20](https://github.com/grafana/grafana/assets/1292551/b9f08f19-b907-4d7f-980c-3d4303ff72e2)

**What did you expect to happen**:

Instead I would expect to see a graph like this from my Prometheus histogram metric.

![screenshot2021-03-25_14-56-22](https://github.com/grafana/grafana/assets/1292551/92d98130-6c88-4d5a-a4b5-647e562853e8)

### 
# How do we reproduce it?

- Create a panel of type bar gauge 
- Change Format to Heatmap
- See error from above

### 
# What Grafana version are you using?

Grafana v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Debian 11

### User's Browser?

Firefox 114.0.2 (64-Bit)

### Is this a Regression?

Yes

### Are Datasources involved?

Prometheus

**Comment by JPThorne** [comment]
Hello, did you find a solution to this at all?

**Comment by leahoswald** [comment]
Nope, still open

**Comment by gtk-grafana** [comment]
Should be fixed in the next release (was backported to v10.x). As a workaround you can disable the `prometheusDataplane` feature flag which should also prevent this error from being thrown.

**Comment by fzyzcjy** [comment]
I am seeing the same bug, when will the next backport release? Thanks!

**Comment by dron-dronych** [comment]
it seems to have been fixed as stated in https://github.com/grafana/grafana/pull/71971

**Comment by leahoswald** [comment]
But it isn't in a release yet. (as far as I can see)
