### ISSUE TITLE
Logs Panel: Field overrides not available

### ISSUE THREAD

**Issue by jontro** [grafana/grafana#71020]
### 
# What went wrong?

**What happened**:

I cannot add field overrides to the logs panel. This makes it impossible to add custom data links for at least Cloudwatch

**What did you expect to happen**:

Being able to add overrides as with other panels and being referenced as the only way to add data links in other issues.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and add a logs panel

**Step 2**:

- No field overrides choice is available

### 
# What Grafana version are you using?

v10.0.1

### 
### Grafana Platform?

Kubernetes

### Is this a Regression?

No

**Comment by tonypowa** [comment]
hi @jontro 

at the moment, field override is not an available option in the logs panel. However, the observability team has added this feature request to their backlog, and will investigate the feasibility of implementing field override.

thank you for your contribution !
