### ISSUE TITLE
[Feature Request] Repeat within panel

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7102]
* Current Beta package (4.1)
* Promtheus
* Debian

Same as you can repeat rows and panels on templates, I would like to be able to repeat on templates within a single query within a single panel.

This is useful for when wildcard/regex queries don't cut it and you don't want to build a dozen similar queries by hand.

**Comment by dannyk81** [comment]
@torkelo have just hit this myself and was looking if a feature request for this already exists 😄 (kudos to GitHub for adding the "Related Issues" thingy)

Here's our use case:
1) we have a cluster of nodes running MySQL
2) we define a `cluster` template variable based on the `wsrep_cluster_name` label
3) we generate a `cluster_nodes` template variable with the `instance` values of the nodes that are part of the selected `cluster`.
4) we want to have a single panel that shows the CPU usage of all the nodes in the selected `cluster`, alas the `cluster_nodes` variable will either have the `All` option or just the first node select (if we use multi-select, without `All`).

if we go ahead and select manually the individual nodes in the `cluster_nodes` drop-down, the panel will show all three, but there isn't a way to get this done automatically.

One workaround is to use more complex Queries to filter the required instances (nodes) using PromQL Joins but this complicates the panel queries quite a bit.

**Comment by hugohaggmark** [comment]
Closing this issue as some of our Panels now support this feature and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
