### ISSUE TITLE
[Docs] Update images for how to add datasources

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#7103]
ex http://docs.grafana.org/features/datasources/graphite/

**Comment by zoltanbedi** [comment]
Probably here https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/

**Comment by oddlittlebird** [comment]
Yes, all the data sources need updated images. This is not a small ask. We have 16 data sources, most of which are not new, all of which need to have documentation images evaluated.  

Please break this into multiple issues and assign them to the squads that own the particular integration. That will be much faster and more efficient than waiting for the documentarians to learn enough about each data source to recreate the screenshot with the current Grafana AND update an documentation affected by image changes.

**Comment by oddlittlebird** [comment]
@achatterjee-grafana, something to be aware of as we work on data sources.

**Comment by oddlittlebird** [comment]
This is a duplicate
