### ISSUE TITLE
AzureMonitor: Add `All` option for subscriptions in ARG queries

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#71034]
### 
# What went wrong?

Before #66890 was merged users could create an ARG query with the subscription field empty that would lead to querying all subscriptions. However, this led to some unexpected UI side-effects that the original PR fixed. However, it is clear users would like the ability to query all subscriptions in both Explore and Alerting which do not support template variables. An `All` option should be added to allow this functionality.

### 
# How do we reproduce it?

Attempt to query all subscriptions in an ARG query.

### 
# What Grafana version are you using?

Latest

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by abhiShandy** [comment]
How do you think I should solve this issue?

Can I add "All" in the subscription options here: https://github.com/grafana/grafana/blob/28c0fb1cfd4aa520f767b0e9e91e83a1931eee38/public/app/plugins/datasource/azuremonitor/components/ArgQueryEditor/SubscriptionField.tsx#L19

and handle it in the `onChange` function?
