### ISSUE TITLE
[Bug] Alias does not work in specific case and "edit mode"

### ISSUE THREAD

**Issue by tomekit** [grafana/grafana#7105]
Please include this information:
- What Grafana version are you using?
 Grafana version: 3.0.4, commit: v3.0.4, build date: 2016-05-25 10:46:55

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Docker: https://github.com/kamon-io/docker-grafana-graphite

- What did you do?
Set alias to custom query:
`sumSeries(scale(#B, -1), #A).alias(diff)`

- What was the expected result?
Alias shall be set

- What happened instead?
Alias didn't apply

![alias_issue_grafana](https://cloud.githubusercontent.com/assets/7759113/21587805/98b9cf76-d0e0-11e6-9949-c95852188e20.png)

**Comment by torkelo** [comment]
`sumSeries(scale(#B, -1), #A).alias(diff)` is not a valid graphite query. When you are in text edit mode you need to use proper (nested) graphite syntax. 

`alias(sumSeries(scale(#B, -1), #A), 'diff)` 

Is there a reason your doing this in raw edit mode and not using the query editor? add a new query and instead of selecting any metric, click plus button to add the sumSeries function, specify #A and #B as parameters. (add the scale -1 to B query or create a query C with the scale function.

**Comment by tomekit** [comment]
Thanks for your help @torkelo, I had some issues with the custom queries.
E.g. when used `maxSeries(#A, #B) in a new row and non-edit mode my arguments were not preserved even when dashboard was saved. After that I've got just the `maxSeries()`. 
I would have to spend some time to reproduce the problem and describe it.

**Comment by torkelo** [comment]
strange, never seen that (nor had it reported). If you do encounter it please open chrome dev console and look if there is any js error.

**Comment by torkelo** [comment]
Or rather maxSeries has been flagged as not supporting nested queries in grafana so you it is impossible for you to specify maxSeries(#A, #B) in the query editor (you can in text edit mode but that is a different mode). Not sure maxSeries supports multiple series list, maybe it should be marked similar to asPercent and divideSeries in grafana function definition file

**Comment by tomekit** [comment]
Checked the Graphite source code:
https://github.com/graphite-project/graphite-web/blob/4fe3474a834616575a9685b46b0a857e1efa5da0/webapp/graphite/render/functions.py#L388

It looks like both minSeries/maxSeries support multiple arguments and it really works OK to me in "Edit mode".

I've also updated Grafana to 4.0.2, as I've wanted to try out alerts.
The alert query can't select any datapoints when diffSeries/minSeries or maxSeries is used like this:
![rule](https://cloud.githubusercontent.com/assets/7759113/21618286/7e29636e-d1ea-11e6-8ee1-6256349a0320.png)
![maxmin](https://cloud.githubusercontent.com/assets/7759113/21618287/7e433b40-d1ea-11e6-9d66-3fb06d59e9f0.png)
It works ok though if the function is `scale` instead of `maxSeries`, even though is used in Toggle mode as well. Is it related to the definition file or shall I create new issue?

**Comment by tomekit** [comment]
For `#K` row there is such a query created (extracted from the XHR request, `target` parameter):
```
alias(diffSeries(maxSeries(multiplySeries(maxSeries(stats.gauges.stock.{stock1,stock2}.offers.*EUR*.bid.*), averageSeries(stats.gauges.stock.currency.alior.*.EUR.PLN)),maxSeries(stats.gauges.stock.{stock1,stock2}.offers.*PLN*.bid.*)), minSeries(multiplySeries(minSeries(stats.gauges.stock.{stock1,stock2}.offers.*EUR*.ask.*), averageSeries(stats.gauges.stock.currency.alior.*.EUR.PLN)),minSeries(stats.gauges.stock.{stock1,stock2}.offers.*PLN*.ask.*))), 'diff')
```
I've pasted it in a new row and now the alerting can query it. Not sure where might be the issue.
