### ISSUE TITLE
Geomap: GeoJSON style rule doesn't work with variable

### ISSUE THREAD

**Issue by vsile** [grafana/grafana#71054]
### 
# What went wrong?

**What happened**:
 
![изображение](https://github.com/grafana/grafana/assets/9244347/de8f6643-aee2-42ff-93c9-1d8c2b59a6d5)

I created a variable ("cn") to be able to choose one of the properties, which match to custom geoJSON properties.
Now I want to use this variable inside style rule (see attachment)
But it doesn't work ("not found" error).

**What did you expect to happen**:

GeoMap style rule should work with variable

### 
# How do we reproduce it?

**Step 1**:

- Open [Geomap Multi Layers Dashboard](https://play.grafana.org/d/geomap_multi-layers/panel-tests-geomap-multi-layers) on Grafana Playground.

**Step 2**:

Create custom variable "country" with values: 
![изображение](https://github.com/grafana/grafana/assets/9244347/37d47338-dcef-4b33-9b62-f9652ab169b4)

**Step 3**:

Open Panel settings and try to insert "$country" in the field instead of Canada
![изображение](https://github.com/grafana/grafana/assets/9244347/aee1b6b7-1f57-4140-800e-e15c4d441a40)

### 
# What Grafana version are you using?

v9.5.1

**Comment by yosiasz** [comment]
would really help if one can use own css (inline or a file pointer) for styling and somehow have grafan pick it up

or

allow geomap to pick up styling from geojson file itself, hence dynamic styling.

**Comment by Bender-OS** [comment]
Push !
