### ISSUE TITLE
Saga - Dev portal Redesign

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#71069]
**Goal**

Design a **start / landing page** for the Dev Portal for linking to subpages like Plugins docs, UI components, Saga, Scenes, Data plane...

Example of the landing page [here](https://devportal.grafana-dev.net/)

**Issues related:**

- [Update dev portal design to match Saga](https://github.com/grafana/plugin-tools/issues/270)
- [Dev Portal connection improvements](https://github.com/grafana/grafana/issues/66522)

**Comment by staton-hyse11** [comment]
related: https://github.com/grafana/plugin-tools/issues/270

**Comment by jackw** [comment]
FYI - this afternoon we went live with the dev portal at https://grafana.com/developers. This is the first release and still a little rough around the edges. I think there's certainly some UX issues with some of the action states (currently links in content and right hand sidebar aren't all that obvious) that we should likely address in future.

**Comment by sympatheticmoose** [comment]
To echo what Jack is saying above. See this example - `string` is regular text, `object` is a hyperlink to content further down in the document. It's going to be very difficult for a user to spot that 🦅 

<img width="927" alt="Screenshot 2023-08-15 at 11 18 57" src="https://github.com/grafana/grafana/assets/19860021/590308ef-ecc1-410d-b78b-6a8d458d0a8c">
