### ISSUE TITLE
[Feature request] Multiply multiple wildcard series just by another series, don't multiply all of them

### ISSUE THREAD

**Issue by tomekit** [grafana/grafana#7106]
Please include this information:
- What Grafana version are you using?
Grafana version: 3.0.4, commit: v3.0.4, build date: 2016-05-25 10:46:55
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Docker: https://github.com/kamon-io/docker-grafana-graphite
- What did you do?
Imagine you have multiple series speficied in #A row using wildcard.
Now you would like to multiple each individual series by another series #B.
Example usage: You have few metrics which provide a value of something in EUR currency #A. You would like to multiple each metric by the currency exchange rate #B to transform the currency to e.g. PLN.

- What was the expected result?
When used: `multiplySeries` like function you get `n` output metrics, each of them multiplied by the #B.

- What happened instead?
All metrics have been multiplied together, creating one combined metric.

![currency_multiply](https://cloud.githubusercontent.com/assets/7759113/21587999/74613694-d0e2-11e6-95b5-a7c41ea71e6a.png)

**Comment by torkelo** [comment]
this issue seem to be opened in the wrong github project. 

Here is the graphite github project:
https://github.com/graphite-project/graphite-web

**Comment by torkelo** [comment]
you could possibly use this function http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.multiplySeriesWithWildcards

**Comment by tomekit** [comment]
Thanks @torkelo 
I probably need to open a Graphite issue. 
My understanding is that `multiplySeriesWithWildcard` would do, if I have all series under the same namespace. E.g. `stats.{server01,server02}.metric.{cpu,ram,hdd}` and would like to multiply e.g. CPU for all servers or all metrics (cpu, ram, hdd) per server. Obviously that's just an example and multiplying these values wouldn't make sense like this. 

I've got a list of series on one side #A and one series #B. I would like to multiple each item in #A by #B. 

EDIT:
Referenced the similar `graphite` issue / use case.
