### ISSUE TITLE
[Feature Request] Thresholds for Right Y axis

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7107]
Grafana 4.1 beta.

I can only define thresholds for Left Y axis, not Right Y axis.

**Comment by jenrg** [comment]
+1
I would also like to be able to set thresholds for right Y axis.

**Comment by chooko** [comment]
+1

Would like to see this feature added.

**Comment by psellers89** [comment]
+1

Would be very nice to get this

**Comment by fsauer65** [comment]
+1

**Comment by Eloo** [comment]
+1

**Comment by piloe** [comment]
+1

**Comment by Pelleplutt** [comment]
+1

**Comment by sp-ricard-valverde** [comment]
+1

**Comment by zicklam** [comment]
+1

**Comment by hanshchou** [comment]
+1

**Comment by Pyronious** [comment]
+1

**Comment by akamez** [comment]
+1

**Comment by SkeletonRocky** [comment]
+1

**Comment by arnolde** [comment]
@ilgizar @bergquist I'm confused, I see this was fixed in 2018 but I'm using Grafana 5.4.1 and still don't see any way to align an alert to a right-hand Y-axis value?
