### ISSUE TITLE
Alerting: The message template is behaving strangely with migration 9.2.5 to 9.4.10

### ISSUE THREAD

**Issue by gurumee92** [grafana/grafana#71108]
### 
# What went wrong?

**What happened**:

  - I recently updated my version of Graphana from 9.2.5 to 9.4.10. After that, alarm messages that were working fine before started behaving strangely.

**What did you expect to happen**:

  - Here's my alert rule's configuration:

A:
```promql
sum(aws_networkelb_healthy_host_count_minimum) by (load_balancer)
```
B:
Conditions: WHEN max() OF A IS BELOW 1

For an alert rule created in the previous 9.2.5, it works like this:

You can see the results of expression B in the alert rule.
<img width="1000" alt="normal-1" src="https://github.com/grafana/grafana/assets/32067275/f9f3e04f-0765-4171-b6db-7a32ae5bef51">

You can see that the values in B are mapped to the names of the values in the load_balancer that A's aggregation was based on.
<img width="1000" alt="normal-2" src="https://github.com/grafana/grafana/assets/32067275/6ee9e27b-ceb6-453e-b3cf-833c61257134">

However, after 9.4.10, alert rules created with the same alert rule configuration behave as follows.

You can see the results of expression B in the alert rule.
<img width="1000" alt="abnormal-1" src="https://github.com/grafana/grafana/assets/32067275/cb7a82b7-fa01-4cd6-be5e-95e5da9a1df5">

However, as in 9.2.5, the values in B do not map to the values in the load_balancer.
<img width="1000" alt="abnormal-2" src="https://github.com/grafana/grafana/assets/32067275/5b6230f9-8b27-4219-a559-5867cbd7cc26">

### 
# How do we reproduce it?

**Step 1**:

- make alert rule in grafana 9.2.5 (I call this "alert rule A")

**Step 2**:

- upgrade grafana version 9.4.10

**Step 3**:

- make alert rule in grafana 9.4.10 with same configuration "alert rule A" (I call this "alert rule B")

**Step 4**:

- check your contact point output, "alert rule A" will behave as it did in 9.2.5, even when updated to 9.4.10. However, you can see that "alert rule B" has strange templating behavior even though it has the same configuration.

I noticed that the response in "alert rule A" has a "metric" in the "valueString" field, but alert rule B does not. Is this an issue caused by a version difference?

### 
# What Grafana version are you using?

v9.4.10 (migrate from v9.2.5)

### 
### Grafana Platform?

Kubernetes

### User's OS?

mac os ventura 13.1(22C65)

### User's Browser?

google chrome  v114.0.5735.198 (x86_64)

### Is this a Regression?

None

### Are Datasources involved?

prometheus / thanos

**Comment by armandgrillet** [comment]
It seems that your first alert rule is using a custom template whereas the second one is using the default template. Could you check that the second alert rule uses the same custom template as the first one? The templates are set in the contact points view, we can see in your screenshot that your alerts have different labels thus they might use different contact points.

**Comment by gurumee92** [comment]
Oh Thank you. I missed the configuration.

I matched the configuration and the alert works the same! Thank you @armandgrillet  🙇
