### ISSUE TITLE
[Feature Request] Rabbit MQ Notifier

### ISSUE THREAD

**Issue by RichardGreen-IS2** [grafana/grafana#7110]
Add the ability for grafana to send alert data to an exchange on rabbitmq. 

This will allow integration into existing systems that use pub/sub (via rabbitmq) for alerting.

**Comment by Speedy1991** [comment]
Kinda late, but you can fork and revert this commit: https://github.com/grafana/grafana/commit/dea631bedca9f24c86cd4b3ce56f27c917c3382c
Info: https://github.com/grafana/grafana/issues/9645

**Comment by mgiammarco** [comment]
Actually I need to integrate Grafana with other systems. Grafana can create alerts in easy and powerful way. Unfortunately usually other system accept rest or amqp inputs.
And REST json in Grafana is not customizable. And then you remove amqp/rabbit support.
It seems strange to remove features that can be so important.
