### ISSUE TITLE
[Bug] label table is cut off in image export

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7111]
Grafana 4.1 beta on Prometheus and CoreOS

Similar to https://github.com/grafana/grafana/issues/4959 but different, this happens when using the legend in table format:

![labels_cut_off_second_attempt](https://cloud.githubusercontent.com/assets/754723/21591098/783af4de-d101-11e6-9487-3ea491eb6544.png)

**Comment by torkelo** [comment]
there is a scrollbar, need to make the image higher to show more legend items
