### ISSUE TITLE
[Feature request] Elasticsearch Term aggregation limit

### ISSUE THREAD

**Issue by FFalcon** [grafana/grafana#7112]
- What Grafana version are you using? 4.1
- What datasource are you using? elasticsearch
- What OS are you running grafana on? windows server 2012
Term aggratation is hard limited to 500 entries which makes templates less powerful.
In the code the limit is hardcoded and I feel like it's necessary to let the user configure such a limit depending on their use case

Part of the code (public/app/plugins/datasource/elasticsearch/query_builder.js) :
`query.aggs =  {
      "1": {
        "terms": {
          "field": queryDef.field,
          "size": 500,
          "order": {
            "_term": "asc"
          }
        },
      }`

**Comment by torkelo** [comment]
Not sure  a template variable with more than 500 entires is a good idea. But maybe that limit should be possible to override.

**Comment by FFalcon** [comment]
To be honest the weird thing is that this change was suddenly made between 3.1.1 and 4.0.
I checked as I have a 3.1 instance running that doesn't have that restriction

Code in 3.1.1 branch (public/app/plugins/datasource/elasticsearch/query_builder.js):
`query.aggs =  {
      "1": {
        "terms": {
          "field": queryDef.field,
          "size": 0,
          "order": {
            "_term": "asc"
          }
        },
      }`

**Comment by lpic10** [comment]
For more info about this change, see https://github.com/grafana/grafana/pull/4970#issuecomment-235398819

**Comment by towolf** [comment]
Nice to see this has been filed before.

Set the setting to "Group By" "Terms" "Size" "No Limit", and then I needed to break out the tcpdump to find this:

```

**Comment by novegit** [comment]
Environmanent: RHEL7, Elasticsearch 2.4
 
I have in some stages more than 2000 servers. With Grafana 4.0.2 all servers were selectable with a server-template variable, (without any perfomance issues). 
With grafana 4.1.1 the server template results seems  limited to 500, for me this limit is a grave regress.

**Comment by torkelo** [comment]
this should be very easy to add a size property to the template variable query.

**Comment by 1tft** [comment]
The "size property to the template variable query" would be very usefull. We are also confronted with template variables of more than 500 values and so these variables are not working correctly with grafana 4.x any longer.

**Comment by FFalcon** [comment]
I can do the change on this but I'm have no experience in node.js development. So if you have any idea on where I should start tell me so that I'll have a PR ready soon.

**Comment by 1tft** [comment]
Hello, sry I can't help regarding node.js development.
For my own I created a local workaround: I changed the 500 value in /public/app/boot.*.js for my installation.

**Comment by FFalcon** [comment]
Maybe @torkelo or @lpic10 can help ?

**Comment by lpic10** [comment]
For now I see 2 separated but related issues: 

1. Template variables are now limited to 500 items;
2. Graphs with group by terms set to "'No limit" is now limited to 500 despite the label;

For the first there is no workaround, and this is maybe what should be priority to fix, but I have no idea how it needs to be implemented. Maybe a new setting per template variable? 

For the second you can just type any other number in the input, but the "No limit" option is still there and it does not make sense anymore. Should we just rename "No limit" ? How to treat the previous graphs using "No limit"?
