### ISSUE TITLE
Loki: add support for new `logfmt` features

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#71121]
the LogQL `logfmt` got new features:
- the `--strict` flag ( https://github.com/grafana/loki/pull/9626 )
- the `--keep-empty` flag
- support for parameters

(see https://grafana.com/docs/loki/next/query/log_queries/#logfmt for details)

We should add these to:

- [x] lezer parser 
- [x] make sure autocompletion query editor works
- [x] make sure query validation works
- [x] add it to query builder
- [x] add it to query parser that translates logql to visual query model

**Comment by gabor** [comment]
(note: updated the github-issue to cover more logfmt-changes)
