### ISSUE TITLE
Grafana init / systemd script missing dependency to (My)SQL server -> fails to start

### ISSUE THREAD

**Issue by mirko** [grafana/grafana#7113]
When Grafana is being configured to use (My)SQL as a storage backend, it should make sure the backend is started before grafana attempts to start, or at least do not give up on first failed attempt.

This is the case for the official grafana 2.x packages provided by the Debian repository as well as the 4.1 beta package provided by grafana.org.

Excerpt from the log file:

```
t=2017-01-02T19:23:31+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=mysql
t=2017-01-02T19:23:31+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-01-02T19:23:31+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: dial tcp 127.0.0.1:3306: getsockopt: connection refused\n"
```

**Comment by torkelo** [comment]
Grafana does not require mysql, it can use postgres or embedded sqlite3 as well. 

If you need this dependency I recommend you create a custom systemd service file or init script

**Comment by mirko** [comment]
Well, I'm aware of Grafana supporting multiple optional backends.
No offense, but your response and prompt closing seems a bit like a "works for me"-one to me.
Especially because Grafana supports several backends - which don't even need to be installed and running on the same machine as Grafana - I'd expect Grafana to not fail at first failed connection attempt but keep on trying.
Consider it as a feature request for the Grafana init script / systemd file.
Grafana is fine to "crash" if it can't reach the database host, systemd could take easily care of that and retry with a one-liner[1]

[1] https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

**Comment by mirko** [comment]
Another thing to consider - for backend and Grafana running on the same host - is, to just "Want=" all supported services (mysql, postgresql, etc.) by systemd.
It's not a hard dependency so whatever is available will be ensured to be up and running before Grafana starts.

**Comment by torkelo** [comment]
Sorry closing so quickly

**Comment by towolf** [comment]
@torkelo with systemd you do not need to add a dependency (i.e. `Wants=`, or `Requires=`), but an ordering relation would be very helpful (i.e. `After=`).

In the latter case it just means, "if the other service starts, then I want to start after it", if not then not.

So, I just added this drop-in and that made Grafana start in the proper sequence:
```# /etc/systemd/system/grafana-server.service.d/01-after-mysql.conf
[Unit]
After=mysql.service```


Icinga for example also supports multiple DB backends and it just has this:
```
[Unit]
Description=Icinga host/service/network monitoring system
After=postgresql.service mariadb.service carbon-cache.service mysql.service syslog.target
```

**Comment by torkelo** [comment]
ok, I see that seems like a good solution. @towolf have time to do a PR with that?

**Comment by towolf** [comment]
@torkelo, that was simple enough to do.

**Comment by mirko** [comment]
Thanks for having taken another look on this - I highly appreciate that!
