### ISSUE TITLE
[Feature request] - when creating users via API allow association with existing (non-default) org

### ISSUE THREAD

**Issue by sfitts** [grafana/grafana#7114]
Version - 4.0.2

Configure the server with the `auto_assign_org` option set to `false`.

When creating users via the HTTP API (POST to `/api/admin/users`) each user will also attempt to create its associated organization.  As a result if you try to create 2 users in the same org, the second one will fail because of the attempt to create a duplicate organization.  For our use case (which I will explain below) it would be better if `getOrgIdForNewUser` in [user.go](https://github.com/grafana/grafana/blob/v4.0.2/pkg/services/sqlstore/user.go) checked for an existing organization in this case, just as it does when assigning to org id 1.

The upshot is that with auto assign turned off every user created will also create a new organization.  This was a bit surprising, so I'm not sure if this is intended or a bug.  It also means that it is impossible to directly create 2 users in the same organization.

---------------

For background, the use case we are trying to implement is a multi-tenant system where the users/organizations are created automatically using the API (instead of via the Grafana UI).  Ideally for each tenant we would like to create an organization with 2 users in it (one editor and one viewer).  As a workaround we will set `auto_assign_org` to `true` and let the system assign users to org 1.  Then we will issue the API calls needed to add the user to a new organization and remove them from org 1.  This should get us to the same place, but it would be cleaner if this were possible with one API call (the change to `getOrgIdForNewUser` seems simple, but I'm not sure what other impacts it might have since I don't fully understand the current behavior).

**Comment by torkelo** [comment]
When you create a user auto_assign_org off then each user will get their own organisation (as most multi tenant system do). 

After you create the first user (User A), if you want to invite another user to that user's org then you can use the invite API. But I agree, the admin create user api could have org selection as well so grafana admins can create users without their own org but directly assign them to an already created org.

**Comment by sfitts** [comment]
For us using the invite system is problematic since we don't actually want there to be a 1-1 correspondence between users in our system and Grafana users.  Instead we want to transparently provision Grafana with some fixed users.  AFAICT invites require user interaction since there is a web page used to complete the invite process (we want to all of this using just the HTTP API)

We are proxying access to Grafana and using `auth_proxy` mode to select which user is appropriate based on their authenticated identity in our system.

**Comment by digrich** [comment]
We have pretty much similar use case where we want our existing users to get authenticated in the different platform and via auth proxy allowing them to access Grafana. Before redirecting the user to Grafana, we are provisioning Grafana for the logged in user using admin API. We create an organization and a new user but by default newly created user get associated to MAIN org and then we need to make few more api calls to associated that user to newly created org. 

@torkelo As you suggested, it would be much easier if admin creates user api allows to select the parent organization and associate the user to its parent organization on the same call.
Do you have any tentative plan when we can have this feature?

**Comment by Sytten** [comment]
We also have the same use case as @digrich, I think it would be a good improvement.

**Comment by mubeta06** [comment]
Same problem. As a work around for the fact that generic oauth integration drops users directly into orgId=1 we are having to make multiple API calls to shuffle users between organisations also.

**Comment by Sytten** [comment]
I pushed a first implementation, hopefully we can this merged quickly. Stay tuned @mubeta06 @digrich @sfitts
