### ISSUE TITLE
[bug] Alert email error - EOF

### ISSUE THREAD

**Issue by twomore** [grafana/grafana#7116]
- What Grafana version are you using?
**v4.0.2**
- What datasource are you using?
**Graphite**
- What OS are you running grafana on?
**Linux**
- What did you do?
**Tried to send a test mail for alerting**
- What was the expected result?
**Email send via SMTP settings used in grafana.ini file**
- What happened instead?
**Although the message on the display says: "Test notification sent" the mail is not send and an error is mentioned in the logfile:**
**_msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF_**

**grafana.ini**
[smtp]
enabled = true
host = smtp-aa.wps.xxx.net:25
;user =
;password =
;cert_file =
;key_file =
;skip_verify = false
#;from_address = admin@grafana.localhost
from_address = abc@xxx.nl

**Test mail:**
![image](https://cloud.githubusercontent.com/assets/24888302/21601444/1db8a058-d18b-11e6-92bf-d7e9b2bbf34b.png)

**grafana.log:**
t=2017-01-03T08:03:04+0100 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-01-03T08:03:04+0100 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[twomore@xxx.nl]
t=2017-01-03T08:03:05+0100 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF

**Comment by torkelo** [comment]
strange no one else has reported a similar issue. maybe some error accessing the email template (located in /usr/share/grafana/public/emails I think)

**Comment by twomore** [comment]
Changed the file permissions of the following files to 777 (full control):
alert_notification_example.html
alert_notification.html

But still the same error....

**Comment by twomore** [comment]
Same issue with Grafana v4.1.0-beta1

**Comment by thomazrhel** [comment]
Hi torkelo, thank you for your help.

I changed the file permissions as twomore told, but I'm having the same problem.

Also, I checked my SMTP server ports and we only use port 25, see below.

![image](https://cloud.githubusercontent.com/assets/24945143/21717243/f9ed18f2-d3f6-11e6-9009-12317cbedbe9.png)

Do you have any other idea? 

Thanks,

**Comment by torkelo** [comment]
no :(

**Comment by thomazrhel** [comment]
Hi Torkelo,

Now I'm able to send emails, we have an internal smtp server and we don't use authentication to send emails.

I was trying to send emails without authentication and I believe the Grafana doesn't have this feature yet.

After configure my SMTP server to accept TLS, I'm able to send emails.

Many thanks!!! :)

**Comment by bergquist** [comment]
Seems like a bug. That should be possible.

**Comment by bergquist** [comment]
Opened #7189 and closing this

**Comment by Metamathematics** [comment]
Yes, we have the same problem. BUT
I changed the permissions of the templates. No chages. 
We do not use TLS and its very hard to change.
Port 25 is working. But the test still do not work.
What could be the problem?

grafana.log:
t=2017-06-06T17:22:08+0200 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-06-06T17:22:08+0200 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[sg@loyaltypartner.com]
t=2017-06-06T17:22:08+0200 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF
t=2017-06-06T17:22:08+0200 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=3 uname=admin error=EOF
t=2017-06-06T17:22:08+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=3 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=[::1] time_ms=5 size=48

SMTP config:
#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = 127.0.0.1:25
;user =
;password =
;cert_file =
;key_file =
skip_verify = true
from_address = admin@grafana.localhost
from_name = Grafana

**Comment by falanger** [comment]
The possible reason is system-wide enabled ipv6, which gmail resols to.
```
connect(9, {sa_family=AF_INET6, sin6_port=htons(9), inet_pton(AF_INET6, "2607:f8b0:400c:c06::6c", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}
, 28) = -1 ENETUNREACH (Network is unreachable)   
```
Possible workaround
http://terokarvinen.com/2016/prefer-ipv4-on-ubuntu-16-04-lts-xenial-etcgai-conf-precedence-ffff0096-100
