### ISSUE TITLE
404 for sign-a-plugin.md page

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#71163]
Google https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

404. Alias not working?

**Comment by robbymilo** [comment]
At https://github.com/grafana/grafana/blob/main/docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md?plain=1#L4-L5 aliases should be:
```
aliases:
  - ../sign-a-plugin/
```
