### ISSUE TITLE
Dashboard to visualized nested folder events

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#71176]
Related to https://github.com/grafana/grafana/issues/68707

Create a dashboard on our bi or ops instance to visualize the above events.

**Comment by yaelleC** [comment]
Can use: https://ops.grafana-ops.net/d/d6036630-029c-496d-90bd-93be9b3a06d2/rollout-and-success-metrics?orgId=1&from=1689847323796&to=1690452123796&var-plan=All&var-feature=nestedFolders as starting point

**Comment by L-M-K-B** [comment]
@yaelleC @zsofiakm suggested another dashboard to me yesterday which is this one: https://ops.grafana-ops.net/d/ff12963b-e917-4e81-b737-db12b0aba450/fe-platform---subfolders?orgId=1&from=now-30d&to=now
I added the new panels there. Would you like me to move them to the other board?

**Comment by L-M-K-B** [comment]
Done. Added panels to dashboard mentioned above.
Follow up task to be found here: https://github.com/grafana/grafana/issues/72528
