### ISSUE TITLE
Alerts changes don't refresh with sidecar

### ISSUE THREAD

**Issue by grubyhs** [grafana/grafana#71178]
### 
# What went wrong?

After adding changes to the config map with alerts I don't see the changes in grafana:
1. I have PVC for var/lib/grafana folder
2. I am using sidecar to reload alerts http://localhost:3000/api/admin/provisioning/alerting/reload
3. Everything works for dashboards
  - 

I except to see refreshed alerts

  - 

### 
# How do we reproduce it?

**Step 1**:

- I am using kubectl apply -f configmap_alerts.yaml

**Step 2**:

- Changes are on cluster in config map but not in grafana

### 
# What Grafana version are you using?

9.5.5

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Windows 11

### User's Browser?

Chrome

### Is this a Regression?

No

**Comment by JacobsonMT** [comment]
Hi @grubyhs, thanks for the bug report! Is it possible to get a bit more information on your setup, specifically:

- Can you gives us a more specific set of instructions to reproduce the issue?
- Where are the alerting provisioning files being add? They will need to be in a specific subfolder called `provisioning/alerting`.

**Comment by grubyhs** [comment]
`grafana:
  enabled: true
  namespaceOverride: ""
  env:
    GF_INSTALL_PLUGINS: flant-statusmap-panel
    GF_SERVER_ROOT_URL: there_is_url_from_script
  persistence:
    type: pvc
    enabled: true
    storageClassName: rook-ceph-block
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
    mountPath: /var/lib/grafana
  ## ForceDeployDatasources Create datasource configmap even if grafana deployment has been disabled
  ##
  forceDeployDatasources: false
  deploymentStrategy: 
    type: Recreate
  ##
  alerting: 
    contactpoints.yaml:
      file: grafana/contact-points/contact-points-${CLUSTER_STAGE_OR_PROD}.yaml
  notifiers:    
    notification-policies.yaml:
      file: grafana/notification-policies/notification-policies-${CLUSTER_STAGE_OR_PROD}.yaml
  extraSecretMounts: 
    - name: grafana-tls
      mountPath: /etc/grafana/certs
      secretName: grafana-tls
      readOnly: true
      subPath: ""
  ## ForceDeployDashboard Create dashboard configmap even if grafana deployment has been disabled
  ##
  forceDeployDashboards: false

  ## Deploy default dashboards
  ##
  defaultDashboardsEnabled: true

  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: utc+2

  adminPassword: prom-operator

  rbac:
    ## If true, Grafana PSPs will be created
    ##
    pspEnabled: false

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: false

    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    # ingressClassName: nginx

    ## Annotations for Grafana Ingress
    ##
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts: []

    ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: {}
      multicluster:
        global:
          enabled: false
        etcd:
          enabled: false
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
    alerts:
      enabled: true
      env: 
        REQUESTS_CA_BUNDLE: "/etc/grafana/certs/ca.crt"
        REQ_TIMEOUT: 30
        REQ_RETRY_CONNECT: 10
        REQ_SKIP_TLS_VERIFY: true
      label: grafana_alert
      labelValue: "1"
      folderAnnotation: grafana_folder
      searchNamespace: ALL
      reloadURL: "http://localhost:3000/api/admin/provisioning/alerting/reload"
      extraVolumes:
        - name: grafana-tls
          secret:
            secretName: secret
            defaultMode: 0400
            items:
              - key: ca.crt
                path: /etc/grafana/certs
              - key: tls.crt
                path: /etc/grafana/certs
              - key: tls.key
                path: /etc/grafana/certs
      extraMounts:
        - name: grafana-tls
          mountPath: /etc/grafana/certs
          readOnly: true
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
    notifiers:
      enabled: true
      label: grafana_notifier
      reloadURL: "http://localhost:3000/api/admin/provisioning/notifications/reload"

    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true

      uid: prometheus

      ## URL of prometheus datasource
      ##
      url: http://kube-prometheus-stack-prometheus:9090/

      ## Prometheus request timeout in seconds
      # timeout: 30

      # If not defined, will use prometheus.prometheusSpec.scrapeInterval or its default
      # defaultDatasourceScrapeInterval: 15s

      ## Annotations for Grafana datasource configmaps
      ##
      annotations: {}

      ## Set method for HTTP to send query to datasource
      httpMethod: POST

      ## Create datasource for each Pod of Prometheus StatefulSet;
      ## this uses headless service `prometheus-operated` which is
      ## created by Prometheus Operator
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/0fee93e12dc7c2ea1218f19ae25ec6b893460590/pkg/prometheus/statefulset.go#L255-L286
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
      labelValue: "1"

      ## Field with internal link pointing to existing data source in Grafana.
      ## Can be provisioned via additionalDataSources
      exemplarTraceIdDestinations: {}
        # datasourceUid: Jaeger
        # traceIdLabelName: trace_id
      alertmanager:
        enabled: false
        uid: alertmanager
        handleGrafanaManagedAlerts: true
        implementation: prometheus

  # extraConfigmapMounts:
  # - name: grafana-alerting
  #   mountPath: /etc/grafana/provisioning/contact-points
  #   configMap: grafana-contact-points
  #   readOnly: false
  deleteDatasources: []
  # - name: example-datasource
  #   orgId: 1

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources: []
  # - name: prometheus-sample
  #   access: proxy
  #   basicAuth: true
  #   basicAuthPassword: pass
  #   basicAuthUser: daco
  #   editable: false
  #   jsonData:
  #       tlsSkipVerify: true
  #   orgId: 1
  #   type: prometheus
  #   url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
  #   version: 1

  ## Passed to grafana subchart and used by servicemonitor below
  ##
  service:
    portName: http-web

  serviceMonitor:
    # If true, a ServiceMonitor CRD is created for a prometheus operator
    # https://github.com/coreos/prometheus-operator
    #
    enabled: true

    # Path to use for scraping metrics. Might be different if server.root_url is set
    # in grafana.ini
    path: "/metrics"

    #  namespace: monitoring  (defaults to use the namespace this chart is deployed to)

    # labels for the ServiceMonitor
    labels: {}

    # Scrape interval. If not set, the Prometheus default scrape interval is used.
    #
    interval: ""
    scheme: http
    tlsConfig: {}
    scrapeTimeout: 30s

    ## RelabelConfigs to apply to samples before scraping
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

## Flag to disable all the kubernetes component scrapers
##
kubernetesServiceMonitors:
  enabled: true
`
