### ISSUE TITLE
ServeFromSubPath: infinite redirect

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#71182]
### 
# What went wrong?

**What happened**:

  - Getting infinite redirect loop when loading Grafana from sub path

`ERR_TOO_MANY_REDIRECTS`

When I revert [this commit](57701fd2f28f95f545569e6173b90050dc0e2913) it works fine.

**What did you expect to happen**:

  - Grafana load

This worked in v9 but does not work in v10.

### 
# How do we reproduce it?

**Step 1**:

Start grafana via docker compose with following variables:

```
      GF_LIVE_ALLOWED_ORIGINS: https://*my.domain.com
      GF_SERVER_ROOT_URL: https://sth.my.domain.com/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
```

**Step 2**:

- Load grafana from subpath (https://sth.my.domain.com/grafana/) as it gives infinite redirect loop

### 
# What Grafana version are you using?

57701fd2f28f95f545569e6173b90050dc0e2913

### 
### Grafana Platform?

Docker

### User's OS?

Macos, Linux

### User's Browser?

Chrome

### Is this a Regression?

Yes

**Comment by tonypowa** [comment]
hi @simPod 

thanks for opening this issue

check out this other issue https://github.com/grafana/grafana/issues/70110#issuecomment-1597403289 since it might be related to your problem 

in the meantime I am forwarding this issue to the backend squad

**Comment by simPod** [comment]
GF_SERVER_SERVE_FROM_SUB_PATH false does the trick. Thannks.

**Comment by Roemer** [comment]
Don't you then always get a warning when editing a graph (but it works anyway)?
