### ISSUE TITLE
UX: Add smart searches in "Search quick ranges" 

### ISSUE THREAD

**Issue by Aracki** [grafana/grafana#71188]
### Background / Why we're doing this

* Would be nice to have an option in Grafana's "Search quick ranges" to type `30d` instead of `Last 30 days`
* Would be nice after typing 30d to be able to just press enter, so it quicky change time range without using a mouse

Similar experience can be found in GCP Logs Explorer. 
https://cloud.google.com/logging/docs/view/building-queries#time-range

<img width="304" alt="image" src="https://github.com/grafana/grafana/assets/6129986/b1ff3414-039c-48cc-b2c0-20cf60dcece3">

### Is there existing research for this?

No research yet

**Comment by L-M-K-B** [comment]
Added to our TimePicker epic.
