### ISSUE TITLE
[Bug] 'Direct link rendered image' for a templated dashboard is not working

### ISSUE THREAD

**Issue by cbos** [grafana/grafana#7120]
For a Graph, you can request for the direct link rendered image.
That is working fine for most dashboards, but not for templated dashboards.

On the play.grafana.org environment it is not working either.
There is this dashboard:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?var-datacenter=America&var-host=All&var-summarize=$__auto_interval

Default datacenter is America, when you then ask for the image, it is fine.

But when you switch to Africa or Asia and request for the link you can a link like this:
http://play.grafana.org/render/dashboard-solo/db/influxdb-templated-queries?var-datacenter=Africa&var-host=All&var-summarize=%24__auto_interval&from=1483452694354&to=1483454494354&panelId=1&width=1000&height=500

But requesting it does not give a proper image, on the play environment it displays 'no datapoints'. 
In our environment it gives the data from the default selected value, that would be America in this case.

We could use this with the Hubot integration as described here: http://docs.grafana.org/tutorials/hubot_howto/ 
`hubot graf db graphite-carbon-metrics host=carbon-a`
Get a templated dashboard with the $host parameter set to carbon-a
But that is not working, and regards what you give, it takes the default in our environment.

**Comment by torkelo** [comment]
make sure the variables have a refresh property set "on dashboard load"

**Comment by cbos** [comment]
That fixed the issue indeed, thanks! 
Probably good to add that to the documentation on http://docs.grafana.org/tutorials/hubot_howto/
