### ISSUE TITLE
Tracing Opentelemetry Jaeger no longer working in Grafana 10.0.1

### ISSUE THREAD

**Issue by chewrocca** [grafana/grafana#71205]
### 
# What went wrong?

**What happened**:

  - Upgrading from Grafana 9.5.5 to 10.0.1 seems to have broken `tracing.opentelemetry.jaeger`

**What did you expect to happen**:

  - I expected tracing to continue to work

### 
# How do we reproduce it?

**Step 1**:

- Set `GF_TRACING_OPENTELEMETRY_JAEGER_ADDRESS = "https://tempo-distributor-jaeger-thrift-http.${domain}/api/traces"`

**Step 2**:

- start Grafana with v10.0.1
- no other config changes were made other than upgrading from 9.5.5 -> 10.0.1

**Step 3**:

- view logs to see

```bash
logger=tracing t=2023-07-07T12:48:26.545113124Z level=error msg="OpenTelemetry handler returned an error" err="UDP connection not yet initialized, an address has not been resolved"
```

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by chewrocca** [comment]
Is it possible this is related? https://github.com/grafana/grafana/pull/67200

**Comment by zserge** [comment]
The fix in the linked PR, in the meantime I may suggest to add a port number to the URL as a workaround.
