### ISSUE TITLE
[Feature request] Email templating in Alert engine

### ISSUE THREAD

**Issue by maciejasembler** [grafana/grafana#7121]
**- What Grafana version are you using?**
4.0.1
**- What datasource are you using?**
OpenTSDB
**- What OS are you running grafana on?**
CentOS 7.2

I would like to congratulate for including alerting feature in Grafana 4, this is just what I needed to create alerts for things that our monitoring did not cover. To make email alerting more flexible I would propose to create simple mail templating engine:

**Current Use Case**
We setup alert thresholds and alert recipient as well as static text which informs about the cause, incomplete Graph (no text, no legend) is also added

**What is missing?**
However I think that the email engine lacks templating option (or documentation on this feature if it is possible). What I would like to request is:
- formatting the metric value with units or just manipulate it via variable
- ability to use some HTML tags / BB code / custom grafana rules for text formatting (at least support for generating links)
- use of dasboard-specific variables such as query alias, graph title, dashboard title or template variables defined in dashboard (could be used as a temporary workaround since alerts do not work with template vars in queries), date of alert triggering - this is mainly for customizing links which Grafana could generate when alert occurs
- Create PNG from the graph state when alert triggered - currently no text is drawn onto the graph making it quite unreadable - exact PNG image from configured view would have been sufficient if possible
- Subject templating - simple textbox with variable support

Pros:
- make alerts customizable, lazy users will not be forced to create new mail filters
- make messages clear to understand - at least by formatting it to the unit used in graph - for instance in rates measured in byte difference but displayed in Mbit/s

Cons:
- can't think of any, except somebody has to write some code and docs on it

Keep up the good work !

**Comment by pdf** [comment]
See also potential extended usage: https://github.com/grafana/grafana/issues/6553#issuecomment-272602289

**Comment by jaimegago** [comment]
+1

**Comment by ddhirajkumar** [comment]
+1

**Comment by rlueckl** [comment]
I would like to add:
 * an option to disable the upload of the graph to an external server (make the "fallback" - attaching/embedding the image the default!)
 * don't load resources from external providers (like the logo in the header)

Most of us are using Grafana in an internal network and uploading our metrics to an external site could be fatal. I don't understand how this is the default (and currently the only) option. The only thing saving us currently, is that the servers are not allowed to communicate with the outside world and Grafana is therefore forced to use the fallback method of embedding the picture in the e-mail.

Pros:
 * everybody could decide if his data is sent through the Internet or not

Cons:
 * can't think of any

**Comment by bergquist** [comment]
@rlueckl Grafana will not upload images of the graphs unless you configured the external image storage in your config. 

That said I think your raising a valid point. I'll create an issue for making image uploads configurable in 4.2

**Comment by rlueckl** [comment]
@bergquist: Thanks for the info. It seems I've misunderstood the homepage: "Email notification will upload an image of the alert graph to an external image destination if available or fallback on attaching the image in the email."

What about the Grafana logo? Could it be also attached (or left out)?

**Comment by bergquist** [comment]
@rlueckl I'll rewrite that text to make it more clear. 

I'll make sure the logo is attached as well.

**Comment by rlueckl** [comment]
Thank you very much!

Sorry for @maciejasembler for hijacking his thread.

**Comment by maciejasembler** [comment]
No problem :P

**Comment by Flyweightt** [comment]
Hi Yes 
For me the option to allow to create your own email templates would be great.
This will allow me to forward the alert to our ticket system.
Or we also have a email2sms gateway so we could notify the oncall people if needed by sms.
And this without the need of pagerduty.

- the tempting should allow custom text in the top of the body in my case
- possibility for text only alerts

Cheers,

**Comment by sanchomuzax** [comment]
+1

**Comment by rpelau** [comment]
+1

**Comment by mike-sol** [comment]
Huge +1 here, otherwise we're stuck having to use Elastalert to do alerting, which while powerful is a big pain to configure.

**Comment by Izmenoff** [comment]
+1

**Comment by rlueckl** [comment]
Please stop writing "+1" in the comments. If you want to move the issue forward either add a thumbs up/smiley/heart to the initial post or contribute yourself. ;)

**Comment by m2b** [comment]
Best thing is to allow the email HTML to be editable with fields that refer to the metric, limit, etc

**Comment by uduwerella** [comment]
+1

**Comment by abhay-fareye** [comment]
I am eagerly waiting for this feature.

**Comment by mkjmkumar** [comment]
+1

**Comment by filipeestacio** [comment]
This would certainly be a very good feature. Being able to customize the email's subject is really important to tighten the integration with ticketing systems.

**Comment by matrog** [comment]
what's the status of this point?

Subject templating - simple textbox with variable support

html email templates are available in latest Grafana version but still no Subject customization

**Comment by jbarotin** [comment]
Is any news about this issue?

We just switched to the new alert system and the alert name in the email title we're missing a lot. We're thinking this feature might fix this point.

**Comment by anwu** [comment]
+1 :)

**Comment by jbarotin** [comment]
A workaround in order to get back to one email by alert as the old system did is to `Edit` the `Root Policy` in the `Notification policies` tab and add group by `alertname` clause.

**Comment by joeblubaugh** [comment]
@matrog 

We now have email subject templating: https://github.com/grafana/grafana/pull/49742
