### ISSUE TITLE
[Feature Request] Allow getting a user by login via HTTP API

### ISSUE THREAD

**Issue by sfitts** [grafana/grafana#7122]
Version - 4.0.2

It would be convenient to be able to GET a user by the `login` property in much the same way the organizations can be referenced by their name.  Something like a GET on `/api/users/login/<loginValue>`.  Since login is unique this URI should be unambiguous.

**Comment by sfitts** [comment]
Actually, this appears to be a dup of #3743

**Comment by dpavlos** [comment]
This one can be closed. It was resolved by #7334 .

**Comment by marefr** [comment]
Fixed by #7334
