### ISSUE TITLE
[Feature request]  Refresh every X seconds to be in the URL

### ISSUE THREAD

**Issue by parkesy** [grafana/grafana#7124]
Grafana version I'm using: 4.0.2
Datasource: InfluxDB
OS: Ubuntu 16.04
What did I do: I saved my browser window layout (ie URLS and window positions). Then shutdown my browsers. Reloaded the layout. 
I expected that: All the grafana views would reload with their settings. 
What happend: All the grafana views loaded but they were missing the referesh every X settings. 

Notes: https://groups.io/g/grafana/message/2643

**Comment by torkelo** [comment]
if anyone wants to take a stab at this here is the relevant parts in the code:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/timeSrv.js#L65

https://github.com/grafana/grafana/blob/2da2d5df568e02f8a8d6d247e6c537647d9a95e4/public/app/features/dashboard/timeSrv.js#L77

**Comment by parkesy** [comment]
OMG this is great Thanks :D
