### ISSUE TITLE
transform: add field from calculation: reduce row produce incorrect result in 10.0.1

### ISSUE THREAD

**Issue by mangkoran** [grafana/grafana#71259]
### 
# What went wrong?

**What happened**:

  - Add field from calculation>Reduce row produce incorrect result (and label apparently) in Geomap visualization

**What did you expect to happen**:

  - Reduce row produce correct result

### 
# How do we reproduce it?

1. Have a Loki data source
2. Create a new Geomap visualization
3. Try to create a new field by "combining" 2 field using Add field from calculation>Reduce row.

Note: Sorry but this is as far as I could to create the MWE as it involves processed data source.

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

[debug-Network Access-2023-07-08 11_46_39.json.txt](https://github.com/grafana/grafana/files/11987585/debug-Network.Access-2023-07-08.11_46_39.json.txt)

### Grafana Platform?

Docker

### User's OS?

Debian 12

### User's Browser?

Chrome 114.0.5735.199

### Is this a Regression?

Yes

### Are Datasources involved?

Loki

### Anything else to add?

Take a look at Coordinate and Location field.

Working fine in 9.5.5
![image](https://github.com/grafana/grafana/assets/57625126/c922155c-b70b-4946-b349-33aa3c5f8fd8)

Broken in 10.0.1
![image](https://github.com/grafana/grafana/assets/57625126/58680301-6f41-4822-a41d-cc9f1d57bd31)

**Comment by oscarkilhed** [comment]
```
"{\"appname\":\"filterlog\",\"dst_geoip\":{\"city_name\":\"Moondarra\",\"continent_code\":\"OC\",\"country_code\":\"AU\",\"country_name\":\"Australia\",\"latitude\":-38.0248,\"longitude\":146.371,\"metro_code\":null,\"postal_code\":\"3825\",\"region_code\":\"VIC\",\"region_name\":\"Victoria\",\"timezone\":\"Australia/Melbourne\"},\"facility\":\"local0\",\"filter_action\":\"nat\",\"filter_dir\":\"out\",\"filter_dstip\":\"1.0.0.1\",\"filter_dstport\":\"53\",\"filter_iface\":\"igb0\",\"filter_ipver\":\"4\",\"filter_proto\":\"udp\",\"filter_srcip\":\"10.10.1.7\",\"filter_srcport\":\"52404\",\"host\":\"opnsense1\",\"hostname\":\"opnsense1.home.arpa\",\"message\":\"4,,,0,igb0,match,nat,out,4,0x0,,62,21664,0,DF,17,udp,70,10.10.1.7,1.0.0.1,52404,53,50\",\"meta\":{\"sequenceId\":\"140\"},\"procid\":6425,\"severity\":\"info\",\"source_ip\":\"10.10.1.1\",\"source_type\":\"syslog\",\"src_geoip\":null,\"version\":1}"
```

Looks like the lat long from this data is corrupt. `latitude\":-38.0248,\"longitude\":146.371,`

**Comment by oscarkilhed** [comment]
I'm unable to reproduce this with the supplied data with the latest version of Grafana. 

![image](https://github.com/grafana/grafana/assets/468940/672dab87-7c2d-498b-89e8-bb9b896a4d7c)
