### ISSUE TITLE
Auth:  US Government Azure AD OAuth URL not supported

### ISSUE THREAD

**Issue by douglasryanadams** [grafana/grafana#71252]
### 
# What went wrong?

**What happened**:

  - Using https://login.microsoftonline.us URLs for auth_url results in a 500 with error log "unable to extract tenant ID from URL"

**What did you expect to happen**:

  - Using https://login.microsoftonline.us URLs for auth_url allows OAuth to proceed as expected

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and select Azure AD SSO login option

**Step 2**:

- Provide Azure AD SSO credentials to your AD service

**Step 3**:

- Error message appears

### 
# What Grafana version are you using?

10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Anything else to add?

I am working on a PR to fix the regex statement that's causing this error. The code's updated and tested but I'm making sure I go through the process correctly (which is why I created this issue).

**Comment by Jguer** [comment]
Hi @douglasryanadams , thanks for reporting this issue and for contributing the fix. We'll try and confirm the difference in domain doesn't affect other functionality

**Comment by danfinn** [comment]
When can this fix be expected in your dockerhub repo?
