### ISSUE TITLE
[Feature Request] Additional Single Stat panel customization

### ISSUE THREAD

**Issue by cr42** [grafana/grafana#7126]
Please include this information:
- What Grafana version are you using? 4.02
- What datasource are you using? influx
- What OS are you running grafana on? windows

I have a dashboard consisting of about 50 single stat panels. I'd like to have them all fit in one screen (so it can display nicely as a single screen summary). However getting these panels to fit nicely on the page is challenging. Suggest the following additional options be made available for this panel to make this use case possible.

 - Adjustable font size, color etc for the title.
 - Option to hide the icon indicating there is a detail URL link available.
 - Reduce or eliminate the minimum height and width allowed to make the boxes smaller than 1 span wide and ~100 pixels high.

**Comment by torkelo** [comment]
Thanks for submitting your feature request & feedback. 

- Panel title font & color change, don't think this sounds a good idea. Want some conformity & minimum expected look for how panel and panel title row should look (important for other info shown in title row errors, time override, panel info icon).

- option to hide drill down link icon: this can be hidden automatically in "in active view mode". Please open a separate issue for this. 
- a minimum height of 100 pixels for panels seems reasonable. I think you need a new "multi stat" panel that works looks similar to singlestat but can show multiple series in stat form in a grid

**Comment by mattttt** [comment]
This is pretty interesting actually, and was actually the original inspiration for Issue: https://github.com/grafana/grafana/issues/6855, which was seeing how you can compress a lot of alerting data (in @cr42's case, single stats functioning as essentially alerts).

@cr42 Take a look at that issue, curious if you feel it is in the same vein.

**Comment by cr42** [comment]
Hi,
Thank you for the response.

The justification I see to allow font color customization for the title is that the background color of the single stat box can be arbitrary based on the threshold selection. The title should therefore also be arbitrary color to allow sufficient contrast to read it.

@torkelo I don't see the "mult stat" panel you refer to. However, I'm not trying to show multiple series of the same parameters. Basically my problem is I have a hardware system that has many different monitoring parameters, eg temperature, pressure, voltage etc. Each parameter has a different spec range and I would like to summarize in a one page indicate if any of these parameters are out of the range. 

A threshold in a table panel doesn't work since the thresholds are different for each parameter. The only current implementation I found that works is the single stat panel. If you have advice on an alternative implementation I'd appreciate it.

An example of what I'm trying to do is below.

![image](https://cloud.githubusercontent.com/assets/18017377/21653340/7034a216-d265-11e6-8716-95f19fc84753.png)

**Comment by mattttt** [comment]
@cr42 Like a version of this? https://www.facebook.com/notes/facebook-engineering/monitoring-cache-with-claspin/10151076705703920

**Comment by cr42** [comment]
@mattttt Yes something like that. 

Basically I have the above dashboard set up so that each box represents a monitored parameter and they are grouped by subsystem. The user can click a box and get a scripted dashboard with the trend of the parameter along with threshold limits in new tab. But as you can see I can't fit very many parameters on one screen.
