### ISSUE TITLE
UI: Typing "straw" into Cmd+K search bar shows all admin pages

### ISSUE THREAD

**Issue by tobiasmuehl** [grafana/grafana#71265]
### 
# What went wrong?

**What happened**:

  - I typed in "straw" to the Cmd+K search bar with the hopes of finding my dasbhoard "strawberry juice
 ". It did show up, but only after all Administration pages showed up.

**What did you expect to happen**:

  - Admin pages don't seem related to the search query
<img width="802" alt="Screenshot 2023-07-09 at 17 48 05" src="https://github.com/grafana/grafana/assets/3341826/d5be2db5-8e73-45e8-8e35-8f3f8cc90744">
 "straw", so they shouldn't show up

### 
# How do we reproduce it?

cmd+k, enter "stra" or "straw"

### 
# What Grafana version are you using?

Grafana v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's Browser?

Chrome

### Is this a Regression?

None

**Comment by zuchka** [comment]
redproducible on play. thanks for reporting, @tobiasmuehl
