### ISSUE TITLE
Explore: How does grafana to query the logs of LOKI storage in the background?

### ISSUE THREAD

**Issue by jjiiee11** [grafana/grafana#71266]
Granfa 9.4.7 and Loki 2.7.3
I found that the results of the query in the Explore section and the query directly using the Loki http API are inconsistent.
I noticed in the Explore section, when I select the label and add additional filters to query the log stored by loki, the actual request executed is api/ds/query, and the datasource type is loki.
While the query http APIs exposed by loki are /loki/api/v1/query and /loki/api/v1/query_range, I wonder if grafana is calling loki’s http api directly? Is there additional processing?
Do you guys have any good suggestions? :smile:

**Comment by ifrost** [comment]
cc @grafana/observability-logs

**Comment by gabor** [comment]
hi @jjiiee11 , i'm sorry, could you describe the problem? are you getting different results from Grafana, compared to calling the loki http api directly?

could you describe an example? 
1. what logql query are you running in grafana (or a screenshot of the query-editor), and it's results
2. the direct api query (perhaps using `curl`), and it's results

(grafana does call the `/loki/api/v1/query` and `/loki/api/v1/query_range` endpoints, just not directly from the browser)

**Comment by jjiiee11** [comment]
The results of calling the Loki HTTP API are not sorted by time, even with the addition of the Direction option.
So I'm wondering what Grafana does after calling the Loki HTTP API to sort the data by time.

**Comment by gabor** [comment]
hi @jjiiee11 , when the data arrives in the browser, Grafana will sort the results based on the `display results: newest first/oldest first` setting:

<img width="440" alt="ordering" src="https://github.com/grafana/grafana/assets/51989/ae040617-9b24-490a-83bb-5d46d08cb88b">

(please note: this does not affect the `direction` loki option. we always do `direction=backward`, this only effect the sort order of the logs received in the browser).

is there an use-case for you where this sorting is not suitable?
(the loki-api-results are grouped by the stream-selector, so they are not really sorted in any way)

**Comment by jjiiee11** [comment]
Hi @gabor 
In fact, when I look up in Grafana, the display Results Setting is in effect. 
How does the display results setting work?
