### ISSUE TITLE
[Bug] ES 4.1 beta: Template variables could not be initialized: undefined

### ISSUE THREAD

**Issue by jacobweber** [grafana/grafana#7127]
Please include this information:
- What Grafana version are you using?  4.1.0-1482230757beta1 (upgraded from 4.0.0; data sources were configured before upgrading)
- What datasource are you using? Elasticsearch 5.1.1
- What OS are you running grafana on? CentOS 6.8
- What did you do?
Added a template variable, selected ES data source, entered query `{"find": "terms", "field": "foo"}`, left other fields as defaults.
- What was the expected result?
Template variable shows all unique values of field "foo".
- What happened instead?
Alert appeared with "Template variables could not be initialized: undefined"

Caused by an XHR:
```
POST /api/datasources/proxy/6/_msearch?search_type=count

{"search_type":"count","ignore_unavailable":true,"index":["logstash-2017.01.03","logstash-2017.01.04"]}
{"size":0,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1483467343108","lte":"1483488943108","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"foo","size":500,"order":{"_term":"asc"}}}}}
```

with response:
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [count]"}],"type":"illegal_argument_exception","reason":"No search type for [count]"},"status":400}
```

**Comment by lpic10** [comment]
Normally the search_type would be "query_then_fetch" instead of "count" on version 5.x 

Did you check whether your Elasticsearch datasource is set to version 5.x?

**Comment by jacobweber** [comment]
Ah, didn't realize there was a setting for that. Works now.
