### ISSUE TITLE
[Bug] Email graph image is not using the same Timezone as Grafana's dashboard

### ISSUE THREAD

**Issue by sergiogarcia94** [grafana/grafana#7128]
**- What Grafana version are you using?**
  Grafana 4.0.2
**- What datasource are you using?**
  Influxdb 1.0.0
**- What OS are you running grafana on?**
  Ubuntu 14.04

I got grafana's timezone setting set to "Local browser time" which in my case is GTM +01:00, 
however email graph is using UTC. And both services (grafana and email sender) are running on the same host. Am I missing something?

**Grafana image:**
![grafana timezone](https://cloud.githubusercontent.com/assets/17526738/21638524/fdfe134c-d26b-11e6-94d9-a0950d8f507c.png)

**Mail image:**
![mail timezone](https://cloud.githubusercontent.com/assets/17526738/21638554/14223f18-d26c-11e6-9c11-f8af1f38ec06.png)

**Comment by torkelo** [comment]
Since your dashboard is using local time zone, rendered images get the timezone configured on the server (which is the local browser timezone on the server).

**Comment by sergiogarcia94** [comment]
Ok, i should change host configuration. Thx.
