### ISSUE TITLE
Alerting: Support deleting an alert group

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#71286]
Just like the title says, we should allow deleting an entire alert group since users might give some semantic meaning to a group (like a service, or part of a system being monitored is decommissioned or refactored).

This assumes we have a confirmation dialog that goes a bit beyond what we have today – we should display how many rules are going to be affected and maybe want the user to type something to confirm (some design efforts are ongoing parallel to support this).

**Comment by yuri-tceretian** [comment]
Grafana Alerting API provides an endpoint to delete all rules in a group `DELETE /api/ruler/grafana/api/v1/rules/{Namespace}/{Groupname}`

**Comment by gillesdemey** [comment]
Closing this one as it has been implemented quite a while ago :D
