### ISSUE TITLE
Bug: discrepancy in graph steps for public dashboard

### ISSUE THREAD

**Issue by alfredo-d** [grafana/grafana#71291]
### 
# What went wrong?

**What happened**:

  - Same graph steps for public dashboard, in either public (accessed using public dashboard url) or standard (accessed  by logging in to grafana instance) view

**What did you expect to happen**:

  - There is discrepancy for graph steps for public dashboard view.
  - Further testing lead to finding that this issue appears when `Min Interval` in query options is left to auto. Look at the additional comment for screenshot.

*Tested with InfluxDB datasource.*
This is the sample screenshot from my instance.
**NOTE**: Top graph is standard view accessed by logging in to the instance, bottom graph is public view accessed from public url

- Discrepancy with auto `Min Interval`
![image](https://github.com/grafana/grafana/assets/109958902/84f19a93-6d49-4fc0-b197-b3e297329a67)
![image](https://github.com/grafana/grafana/assets/109958902/b5df19b9-9c45-43c3-b18f-48b208a85f12)

- Problem solved with fixed `Min Interval`
![image](https://github.com/grafana/grafana/assets/109958902/9fa7c9e6-e3f2-40eb-a269-78f47888f154)
![image](https://github.com/grafana/grafana/assets/109958902/b83e1558-4e05-454e-b159-43a2a802f5da)

### 
# How do we reproduce it?

**Step**:

1. Create any dashboard with timeseries panel
2. Choose InfluxDB (this is what I'm using in my test)
3. Leave `Min Interval` empty
4. Set dashboard time range to fix date and time to prevent potential changes of steps update because of time range
5. Save dashboard
6. Share dashboard to public
7. Using browser incognito, access the public URL
8. Observe the graph between public view in incognito mode and standard view.

### 
# What Grafana version are you using?

Grafana v10.0.2-cloud.1.94a6f396 (b2bbe10fbc), v9.5.2 (cfcea75916)

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by kaydelaney** [comment]
Tested and confirmed

**Comment by AgnesToulet** [comment]
Closing as it seems to have been fixed in the latest version. Please reach out if you are able to reproduce on 10.2+.
