### ISSUE TITLE
[Bug] Displaying dashboard or single chart in Android WebView don't work.

### ISSUE THREAD

**Issue by zwieja** [grafana/grafana#7129]
Please include this information:
- What Grafana version are you using?
**v4.0.2**

- What datasource are you using?
**InfluxDB**

- What OS are you running grafana on?
**Raspbian**

- What did you do?
**I made simple WebView app on Android and I tried to display my created dashbaord and single chart. Problem affects also grafana demo site. 
I also tested other WebView apps from Google Play.**
  
- What was the expected result?
**Dashboard or single chart should appear on screen.**

- What happened instead?
**Displaying white screen.**

Logs from Android Studio.
 I/chromium: [INFO:CONSOLE(51)] "Loading app module failed: ", source: http://192.168.0.17:3000/public/app/boot.85c49108.js (51)

 I/chromium: [INFO:CONSOLE(51)] "Loading app module failed: ", source: http://play.grafana.org/public/app/boot.34fac4c9.js (51)

**Comment by torkelo** [comment]
Strange, works in chrome on android

**Comment by wborn** [comment]
The default settings of the Android WebView are pretty restricted and not HTML5 compliant. I got this same error and resolved it by using the approach outlined at: http://stackoverflow.com/a/10599794
