### ISSUE TITLE
Logrus v1.9.0 PRISMA-2023-0056

### ISSUE THREAD

**Issue by dpericaxon** [grafana/grafana#71309]
**What is the chore?**:
Bump github.com/sirupsen/logrus v1.9.0 to the latest v1.9.x version to remediate PRISMA-2023-0056. This came out as a result of a twistlock report. More information is located here: https://github.com/sirupsen/logrus/issues/1370

**Comment by papagian** [comment]
```
go mod why github.com/sirupsen/logrus
# github.com/sirupsen/logrus
github.com/grafana/grafana/pkg/services/ngalert/metrics
github.com/weaveworks/common/instrument
github.com/weaveworks/common/user
github.com/weaveworks/common/logging
github.com/sirupsen/logrus
```

@grafana/alerting-squad can you evaluate this, thank you!
