### ISSUE TITLE
Transformations: Reduce with reduce fields don't work with wide-timeseries dataframes

### ISSUE THREAD

**Issue by isaqueprofeta** [grafana/grafana#71303]
### 
# What went wrong?

**What happened**:

  - Using a multi-query from same data source I tried to do a combo of transforms using Reduce(Reduce Fields) + Labels to fields + Merge + Organize fields to simulate the usage of yesoreyeram/yesoreyeram-boomtable-panel natively.

    ![image](https://github.com/grafana/grafana/assets/5015741/7bc98607-5157-4941-924e-a0f5524e8b3f)

   - Works fine on some panels, but on others I find out that some of the Reduce(Reduce Fields) wasn't working as expected. Debugging a little I find out that a "wide" object was been created on the data frame.

  - Searching for a bit [on docs I find out that the Wide Series happens](https://grafana.com/docs/grafana/latest/developers/plugins/introduction-to-plugin-development/data-frames/#wide-format) when there's data being collected on the same time of the time frame.

  - Bellow the Reduce(Reduce Fields) in a "wide format" time series wrongly transforming all data on multiple columns on one line.

    ![image](https://github.com/grafana/grafana/assets/5015741/86fd9dbe-4adf-4173-a132-dd3699c8c95f)

**What did you expect to happen**:

  - Reduce(Reduce Fields) should behavior equally on Wide Series as it is for Long Series

  - Bellow the Reduce(Reduce Fields) in a "long format" time series transforming all data on multiple series that can be correctly manipulated o subsequent transforms.
 
    ![image](https://github.com/grafana/grafana/assets/5015741/bb7c3ec0-2dc3-4e4a-b6f7-10cead75a897)

### 
# How do we reproduce it?

**Step 1** (**Unexpected behavior**:):

  - Add a Zabbix datasource and ensure that it **have** more than 1 value of data collected on the same time.

**Step 1** (**Expected behavior**):

  - Add a Zabbix datasource and ensure that it **don't** have more than 1 value of data collected on the same time.

**Step 2**:

  - Add a Table panel with 2 or more queries on that datasource for two diferent items.

**Step 3**:

  - Add a Transform of Reduce with the Mode of Reduce fields

**Step 4** 

**Unexpected behavior**:

  - Multi column table with repeated columns for the data for each Host/Item

**Expected behavior**:

  - One line per query data on a multi frame per Host

### 
# What Grafana version are you using?

v8.5.4, v10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Centos7 and RHEL8

### User's Browser?

Firefox 114.0.2

### Is this a Regression?

No

### Are Datasources involved?

Zabbix, Table Panel

### Anything else to add?

1. I believe that any datasource will have this problem, since [the code](https://github.com/grafana/grafana/blob/8a6c6c3285093cfea4dd48772ca29df69d6a81a9/packages/grafana-data/src/transformations/transformers/reduce.ts#L210) for the function does not test for the type of the dataframe (I'm not really a OO Programer, I could be wrong here)

2. Doing a "Prepare time series" with "Multi-frame time series" give me a workarround here, but I lose all the labels and built-in overrides from the datasource (timestamp configuration for example).

**Comment by isaqueprofeta** [comment]
Just marking @jpkrohling as asked on the Telegram Community.

**Comment by oscarkilhed** [comment]
This honestly seems like the expected behavior to me. Reduce fields on multiple fields of a single frame should return the equal amount of fields, but reduced, in a single frame.

I'm closing this for now. We can reopen it if there's compelling evidence this should be addressed.

**Comment by isaqueprofeta** [comment]
> This honestly seems like the expected behavior to me. Reduce fields on multiple fields of a single frame should return the equal amount of fields, but reduced, in a single frame.
> 
> I'm closing this for now. We can reopen it if there's compelling evidence this should be addressed.

I honestly think that two different returns from a transformation is as confusing than two return types in a function in programing. And this behavior isn't on the docs, I myself lost about a full day looking at code and advanced docs to find out.

But if the team considers that the dual behavior is expected, IMHO at least it should be better documented.
