### ISSUE TITLE
[Bug] moving_average is not available for Elasticsearch 5

### ISSUE THREAD

**Issue by olexij** [grafana/grafana#7130]
Grafana: 4.1 beta
Elasticsearh: 5.1.1
OS: RHEL 7.2

I'm trying to create chart on a numeric value, which includes moving_average with time window equal to 7 days. There is no possibility to add 'Moving average' metrics to the chart as it was with configuration elasticsearch-2.4.2-1.noarch and grafana-4.0.2-1481203731.x86_64.

**Comment by torkelo** [comment]
have you specified version in you Grafana data source ES config?

**Comment by olexij** [comment]
Nothing special I'm aware of, just installed RPM packages and tried. Moving average is not visible as in 4.0.2 and oder Elasticsearch.

**Comment by torkelo** [comment]
in you Grafana ES data source edit view what version have you specified? I can see moving average in metric selection

**Comment by olexij** [comment]
There is no version parameter for ES. I just pointed to the URL and named the index. It's

{
  "name" : "5INSYKG",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ZSgfdkKIQqK1CvzZqWFk-w",
  "version" : {
    "number" : "5.1.1",
    "build_hash" : "5395e21",
    "build_date" : "2016-12-06T12:36:15.409Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}


![image](https://cloud.githubusercontent.com/assets/20337380/21645262/a020f408-d291-11e6-87b0-5f92e056e968.png)

**Comment by olexij** [comment]
Here is a screenshot of the graph, moving average metric is missing:
![grafana](https://cloud.githubusercontent.com/assets/20337380/21646037/d17a6432-d294-11e6-924e-fd793775cdb0.png)

**Comment by olexij** [comment]
Ok, I found it, a didn't specified the version of Elasticearch as you suggested. Now it works, thanks!
