### ISSUE TITLE
Invalid link at the Microsoft SQL Server Data source plugin page

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#71311]
### 
# What went wrong?

**What happened**:

  - When visiting the official Microsoft SQL Server at: https://grafana.com/grafana/plugins/mssql/
  - At the bottom where it says:
    For more information, check the [docs](http://docs.grafana.org/).
    However, that link is not correct

**What did you expect to happen**:

  - The correct link should be there so that can view this page:
     https://grafana.com/docs/grafana/latest/datasources/mssql/

### 
# How do we reproduce it?

See above in description

### 
# What Grafana version are you using?

any version

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's OS?

NA

### User's Browser?

NA

### Is this a Regression?

No

### Are Datasources involved?

Microsoft SQL Server Data source plugin

**Comment by lwandz13** [comment]
Please reach out tot he Content team to get this updated.
