### ISSUE TITLE
[Feat Req]  Add back support for Elasticsearch1.7

### ISSUE THREAD

**Issue by XciD** [grafana/grafana#7131]
- What Grafana version are you using? 
4.0.0 and 4.1 beta
- What datasource are you using?
Elaticsearch 1.7 / 2.0 / 5
- What OS are you running grafana on?
Debian
- What did you do?
Try to use 4.1 with ES 1.7
- What was the expected result?
Working
- What happened instead?
Not working because of https://github.com/grafana/grafana/commit/99c5f7d571dd69169f09daf466e7a53046d2bee1

Why did you removed the support for ES1.7 ? We have multiple cluster with different version and now we have to install multiple grafana :-1: 

Can we have the ES 1.7 Back ?

Thanks

**Comment by torkelo** [comment]
Sorry, there is no easy way to support all versions. If you can't upgrade your ES cluster then you have to keep an old version of Grafana.

**Comment by piotr1212** [comment]
@XciD Seems that just reverting the mentioned patch restores functionality for 1.x. Not sure if it breaks 2.x/5.x and for how long this will stay working, at least it gives me some time to update ES.

**Comment by bawgeneric** [comment]
Which versions of grafana are compatible with ES 1.X ?

**Comment by torkelo** [comment]
@bawgeneric 2.5 - 3.x

**Comment by Ostaer** [comment]
I have a same issue, I have to  update my elasticsearch cluster.

**Comment by marefr** [comment]
Due to the low interest in this issue plus that I find it unlikely that we'll add back support for this really old version I'm closing this. Our main goal is to try to only have relevant issues for the project open. If a lot of people upvotes this feature we'll consider reopen the issue.
