### ISSUE TITLE
Alerting: Provisioning API request url in Swagger UI is wrong when I try to use

### ISSUE THREAD

**Issue by nellaG** [grafana/grafana#71327]
### 
# What went wrong?

**What happened**:

  - I tried to use provisioning API in Swagger UI
  - Tried to use GET api/v1/provisioning/contact-points api via UI button
  - got 404 error and request url is created wrongly: 
  ```
http://{local-grafana-address}/api/api/v1/provisioning/contact-points
  ```
  - Found that `api` prefix is doubly inserted in request url

**What did you expect to happen**:

  - API request url is made correctly and Swagger makes 200 response

### 
# How do we reproduce it?

**Step 1**:

- Access to swagger ui page (both http://{local-grafana-address}/swagger-ui and http://{local-grafana-address}/openapi3 are make this error)

**Step 2**:

- use provisioning API for example `GET api/v1/provisioning/contact-points`

**Step 3**:

- The request returns 404 not found error 

### 
# What Grafana version are you using?

10.0.0

### 
### Grafana Platform?

Docker

### User's OS?

macOS ventura 13.0

### User's Browser?

Google Chrome 114.0.5735.198 (arm64)

### Is this a Regression?

No

**Comment by JacobsonMT** [comment]
Hi @nellaG, thanks for the bug report. Confirmed that I can reproduce this.

We probably want to:

- Remove the `/api` in the alerting swagger definitions.
- Replace the alerting `/api/v1` base path with `/api`.
- Add the `/api` base path back during code generation.

**Comment by yuri-tceretian** [comment]
This has been fixed https://github.com/grafana/grafana/pull/79025
