### ISSUE TITLE
Data Source: Session being closed for databricks connector

### ISSUE THREAD

**Issue by bartvdooren** [grafana/grafana#71321]
### 
# What went wrong?

**What happened**:

  - When using the databricks connector from the Azure Managed Grafana service (Version 9.4.12), the connector is working fine up untill the next day. Then we get an error for each of our graphs stating the following:
  - error querying the database: execute statement request error: Post "https://adb-XXXXX.XX.azuredatabricks.net:443/sql/1.0/warehouses/XXXX": BAD_REQUEST: Invalid SessionHandle: Session [XXXXXX] is closed.
  - The only way to solve the issue above is to re-instate the session by reloading the data connector. Each visual will not load upon doing that.
  - The connector is connected using a PAT token.

**What did you expect to happen**:

- That when using the databricks connector, an admin doesn't have to login each day to refresh the connector. It should keep working.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a data source, with PAT token, for the databricks connector.

**Step 2**:

- Create a simple graph (or table) with this connector.

**Step 3**:

- Wait untill the next day to see that the session from that connector has been closed.

### 
# What Grafana version are you using?

v9.4.12 (Azure Managed Grafana)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows 10

### User's Browser?

Firefox

### Is this a Regression?

No

### Are Datasources involved?

Databricks

**Comment by aangelisc** [comment]
I think this is one for @timlevett's squad maybe? This doesn't sound like an Azure Monitor datasource issue

**Comment by timlevett** [comment]
Databricks is owned by @grafana/enterprise-datasources. I think the fact its on Azure Managed Grafana is irrelevant other than the version number.

**Comment by aangelisc** [comment]
Thanks @timlevett, I'm transferring this to @grafana/enterprise-datasources 😊

**Comment by bartvdooren** [comment]
After some contact with Microsoft support, they see it's an issue that has been resolved in the open source connector. Is it possible to also include his health check in the current version of the connector?

Source links: [Added logic to refresh the connection if they receive the Invalid SessionHandle error](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmullerpeter%2Fdatabricks-grafana%2Fpull%2F8%2Ffiles%23diff-fc137d62147eb6a9c89c0566479ff219320ca691f2505631ebacbe513bcc8108R71-R89&data=05%7C01%7Csupportmail0%40microsoft.com%7C2582f58249f345809f5a08db88358b46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253535811826313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bPuW4xtukIoLN2SVzsk51H74QAKS18kA67Y0%2FBLS64Y%3D&reserved=0)
    [A dummy query, "SELECT 1", checking the connection health](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmullerpeter%2Fdatabricks-grafana%2Fpull%2F8%2Ffiles%23diff-fc137d62147eb6a9c89c0566479ff219320ca691f2505631ebacbe513bcc8108R217&data=05%7C01%7Csupportmail0%40microsoft.com%7C2582f58249f345809f5a08db88358b46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253535811826313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z9A%2FqGtNm65I1CdSWahtZTx1HVJq0RTcaJvOqNNbyaU%3D&reserved=0))
    
Thanks in advance for the help!

**Comment by sasklacz** [comment]
Does it require waiting over 24hrs or just after midnight to reproduce this ?

**Comment by bartvdooren** [comment]
To be specific, it takes 8 hours, as then the SQL warehouse has made a new session "under water", and this causes the connector to fail. We used a SQL warehouse that is running 24/7. The 8 hours is also the respond we received from Microsoft about this issue.

**Comment by scottlepp** [comment]
@bartvdooren what do you have retries set to?  With the latest version of the plugin it should retry/reconnect on that error if you have retries set.

**Comment by bartvdooren** [comment]
We assumed it was 5 by default, as this is the grayed out value. I will set it to 5 myself and see if this helps, will post an update when I have the results.

**Comment by bartvdooren** [comment]
Update: Setting the retry to 5, doesn't resolve the issue, the issue persist.
Still the Session is closed, and only pressing "save & test" within the connector solves the issue.

**Comment by shelldandy** [comment]
@bartvdooren do you know what version of the databricks plugin they're using? this should be fixed since `v.0.3.8` onwards

**Comment by bartvdooren** [comment]
Hi @shelldandy,

Thanks for the response, I see we are using `v.0.3.6 `, however, are unable to upgrade due to it being Azure Managed Grafana.
I suppose we then have to wait until Azure also includes the upgraded version. I will get in contact with them!
