### ISSUE TITLE
[Bug] Grafana & zabbix-app plugin - not showing any data.

### ISSUE THREAD

**Issue by bentzys** [grafana/grafana#7132]
Grafana Version: 4.0.2
Datasource: Zabbix
OS: Ubuntu 16.04.1 LTS

Steps:
1. Installed grafana server - at the same instance where zabbix-server (+ agent) are running.
2. Installed alexanderzobnin-zabbix-app plugin
3. Zabbix plugin configuration:
![grafanaissue1](https://cloud.githubusercontent.com/assets/1905243/21642771/4b6c3e9e-d28d-11e6-800b-1f2aed7e7963.jpeg)

Got:
![grafanaissue2](https://cloud.githubusercontent.com/assets/1905243/21641318/acfd0dd2-d283-11e6-82f4-dfd2b14a481c.jpeg)

Request:
GET /dashboard/db/zabbix-server-dashboard HTTP/1.1
Host: ip-10-150-1-29.ec2.internal:3000
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=1b6a4e6bdb4ca947; grafana_user=admin; grafana_remember=81c74b938a5b85b801ab7efb77e67f85b2f36ddb0c80ca47

Response:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana</title>

		<link href='/public/css/fonts.min.css' rel='stylesheet' type='text/css'>

		
		  <link rel="stylesheet" href="/public/css/grafana.dark.min.c7b017c5.css">
		

    <link rel="icon" type="image/png" href="/public/img/fav32.png">
		<base href="/" />

	</head>

	<body ng-cloak>
		<grafana-app class="grafana-app">

			<aside class="sidemenu-wrapper">
				<sidemenu ng-if="contextSrv.sidemenu"></sidemenu>
			</aside>

			<div class="page-alert-list">
				<div ng-repeat='alert in dashAlerts.list' class="alert-{{alert.severity}} alert">
					<button type="button" class="alert-close" ng-click="dashAlerts.clear(alert)">
						<i class="fa fa-times-circle"></i>
					</button>
					<div class="alert-title">{{alert.title}}</div>
					<div ng-bind='alert.text'></div>
				</div>
			</div>

			<div ng-view class="main-view"></div>
			<footer class="footer">
				<div class="row text-center">
					<ul>
						<li>
							<a href="http://docs.grafana.org" target="_blank">
								<i class="fa fa-file-code-o"></i>
								Docs
							</a>
						</li>
						<li>
							<a href="https://grafana.net/support/plans" target="_blank">
								<i class="fa fa-support"></i>
								Support Plans
							</a>
						</li>
						<li>
							<a href="http://grafana.org/community" target="_blank">
								<i class="fa fa-comments-o"></i>
								Community
							</a>
						</li>
						<li>
							<a href="http://grafana.org" target="_blank">Grafana</a>
							<span>v4.0.2 (commit: v4.0.2)</span>
						</li>
						
					</ul>
				</div>
			</footer>
		</grafana-app>

	<script>
		window.grafanaBootData = {
			user:{"isSignedIn":true,"id":1,"login":"admin","email":"admin@localhost","name":"admin","lightTheme":false,"orgId":1,"orgName":"Main Org.","orgRole":"Admin","isGrafanaAdmin":true,"gravatarUrl":"/avatar/46d229b033af06a191ff2267bca9ae56","timezone":"browser","locale":"en-US"},
			settings: {"allowOrgCreate":true,"appSubUrl":"","authProxyEnabled":false,"buildInfo":{"buildstamp":1481202248,"commit":"v4.0.2","env":"production","hasUpdate":false,"latestVersion":"4.0.2","version":"4.0.2"},"datasources":{"-- Grafana --":{"meta":{"type":"datasource","name":"Grafana","id":"grafana","info":{"author":{"name":"","url":""},"description":"","links":null,"logos":{"small":"public/img/icn-datasource.svg","large":"public/img/icn-datasource.svg"},"screenshots":null,"version":"","updated":""},"dependencies":{"grafanaVersion":"*","plugins":[]},"includes":null,"module":"app/plugins/datasource/grafana/module","baseUrl":"public/app/plugins/datasource/grafana","annotations":true,"metrics":true,"alerting":false,"builtIn":true,"mixed":false,"app":""},"name":"-- Grafana --","type":"grafana"},"-- Mixed --":{"meta":{"type":"datasource","name":"Mixed datasource","id":"mixed","info":{"author":{"name":"","url":""},"description":"","links":null,"logos":{"small":"public/img/icn-datasource.svg","large":"public/img/icn-datasource.svg"},"screenshots":null,"version":"","updated":""},"dependencies":{"grafanaVersion":"*","plugins":[]},"includes":null,"module":"app/plugins/datasource/mixed/module","baseUrl":"public/app/plugins/datasource/mixed","annotations":false,"metrics":true,"alerting":false,"builtIn":true,"mixed":true,"app":""},"type":"mixed"},"ZabbixDS":{"jsonData":{"password":"zabbix","trends":true,"username":"Admin"},"meta":{"type":"datasource","name":"Zabbix","id":"alexanderzobnin-zabbix-datasource","info":{"author":{"name":"Alexander Zobnin","url":"https://github.com/alexanderzobnin/grafana-zabbix"},"description":"","links":null,"logos":{"small":"public/plugins/alexanderzobnin-zabbix-datasource/img/zabbix_app_logo.svg","large":"public/plugins/alexanderzobnin-zabbix-datasource/img/zabbix_app_logo.svg"},"screenshots":null,"version":"","updated":""},"dependencies":{"grafanaVersion":"*","plugins":[]},"includes":null,"module":"plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module","baseUrl":"public/plugins/alexanderzobnin-zabbix-app","annotations":true,"metrics":true,"alerting":false,"builtIn":false,"mixed":false,"app":""},"name":"ZabbixDS","type":"alexanderzobnin-zabbix-datasource","url":"/api/datasources/proxy/1"}},"defaultDatasource":"ZabbixDS","panels":{"alertlist":{"baseUrl":"public/app/plugins/panel/alertlist","id":"alertlist","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/alertlist/img/icn-singlestat-panel.svg","large":"public/app/plugins/panel/alertlist/img/icn-singlestat-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/alertlist/module","name":"Alert List","sort":5},"alexanderzobnin-zabbix-triggers-panel":{"baseUrl":"public/plugins/alexanderzobnin-zabbix-app","id":"alexanderzobnin-zabbix-triggers-panel","info":{"author":{"name":"Alexander Zobnin","url":"https://github.com/alexanderzobnin/grafana-zabbix"},"description":"","links":null,"logos":{"small":"public/img/icn-panel.svg","large":"public/img/icn-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"plugins/alexanderzobnin-zabbix-app/panel-triggers/module","name":"Zabbix Triggers","sort":100},"dashlist":{"baseUrl":"public/app/plugins/panel/dashlist","id":"dashlist","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/dashlist/img/icn-dashlist-panel.svg","large":"public/app/plugins/panel/dashlist/img/icn-dashlist-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/dashlist/module","name":"Dashboard list","sort":6},"graph":{"baseUrl":"public/app/plugins/panel/graph","id":"graph","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/graph/img/icn-graph-panel.svg","large":"public/app/plugins/panel/graph/img/icn-graph-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/graph/module","name":"Graph","sort":1},"pluginlist":{"baseUrl":"public/app/plugins/panel/pluginlist","id":"pluginlist","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/pluginlist/img/icn-dashlist-panel.svg","large":"public/app/plugins/panel/pluginlist/img/icn-dashlist-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/pluginlist/module","name":"Plugin list","sort":100},"singlestat":{"baseUrl":"public/app/plugins/panel/singlestat","id":"singlestat","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/singlestat/img/icn-singlestat-panel.svg","large":"public/app/plugins/panel/singlestat/img/icn-singlestat-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/singlestat/module","name":"Singlestat","sort":2},"table":{"baseUrl":"public/app/plugins/panel/table","id":"table","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/table/img/icn-table-panel.svg","large":"public/app/plugins/panel/table/img/icn-table-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/table/module","name":"Table","sort":3},"text":{"baseUrl":"public/app/plugins/panel/text","id":"text","info":{"author":{"name":"Grafana Project","url":"http://grafana.org"},"description":"","links":null,"logos":{"small":"public/app/plugins/panel/text/img/icn-text-panel.svg","large":"public/app/plugins/panel/text/img/icn-text-panel.svg"},"screenshots":null,"version":"","updated":""},"module":"app/plugins/panel/text/module","name":"Text","sort":4}}},
			mainNavLinks: [{"text":"Dashboards","icon":"icon-gf icon-gf-dashboard","url":"/","children":[{"text":"Home","url":"/"},{"text":"Playlists","url":"/playlists"},{"text":"Snapshots","url":"/dashboard/snapshots"},{"divider":true},{"text":"New","icon":"fa fa-plus","url":"/dashboard/new"},{"text":"Import","icon":"fa fa-download","url":"/dashboard/new/?editview=import"}]},{"text":"Alerting","icon":"icon-gf icon-gf-alert","url":"/alerting/list","children":[{"text":"Alert List","url":"/alerting/list"},{"text":"Notifications","url":"/alerting/notifications"}]},{"text":"Data Sources","icon":"icon-gf icon-gf-datasources","url":"/datasources"},{"text":"Plugins","icon":"icon-gf icon-gf-apps","url":"/plugins"},{"text":"Zabbix","img":"public/plugins/alexanderzobnin-zabbix-app/img/zabbix_app_logo.svg","children":[{"text":"Zabbix Server Dashboard","url":"/dashboard/db/zabbix-server-dashboard"},{"text":"Template Linux Server","url":"/dashboard/db/template-linux-server"},{"divider":true},{"text":"Plugin Config","icon":"fa fa-cog","url":"/plugins/alexanderzobnin-zabbix-app/edit"}]},{"text":"Admin","icon":"fa fa-fw fa-cogs","url":"/admin","children":[{"text":"Global Users","url":"/admin/users"},{"text":"Global Orgs","url":"/admin/orgs"},{"text":"Server Settings","url":"/admin/settings"},{"text":"Server Stats","url":"/admin/stats"}]}]
		};
	</script>

	<script src="/public/app/boot.85c49108.js"></script>

	

	

	</body>
</html>

**Comment by torkelo** [comment]
please open this in issue the zabbix plugin repo
