### ISSUE TITLE
bug: plugins catalog displays HTML comments in readme

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#71358]
see https://grafana.com/grafana/plugins/joshhunt-destiny-datasource/ as an example
![image (1)](https://github.com/grafana/grafana/assets/19860021/69490d45-86ae-454b-b038-d8a5bc95bac3)

and (`<br>`) from https://grafana.com/grafana/plugins/boazreicher-mosaicplot-panel/
<img width="586" alt="Screenshot 2023-07-13 at 14 32 24" src="https://github.com/grafana/grafana/assets/19860021/474c389c-ba2d-462f-9d91-7090f4196bf4">

Note this shows in both Grafana.com and within the Grafana UI

**Comment by oshirohugo** [comment]
We fixed the issue that was creating wrong readmes, so new or updated plugins won't have this issue and
we run a script to update the readme on every plugin that has a package in was alraedy in prod, therefore we are closing this as completed.
