### ISSUE TITLE
[Bug] Incompatible Fields filtered by type {"find": "fields", "type": "string"} Elasticsearch 5.1

### ISSUE THREAD

**Issue by vvp83** [grafana/grafana#7135]
Grafana  Grafana v4.1.0-beta1 (commit: 9dc4264)
Source - Elasticsearch 5.1
OS - docker pull grafana

Create Templating -> Variables -> New
Source elastic-1
 
In Query field - {"find": "fields", "type": "string"}
![issue1](https://cloud.githubusercontent.com/assets/24292154/21648256/64d9fc10-d2ae-11e6-9a78-36a8de3faab4.JPG)

No one DATA in Preview of values (shows max 20)

But in Chrome debugger:
![issue2](https://cloud.githubusercontent.com/assets/24292154/21648621/aafaf626-d2af-11e6-8cf5-4c47f595b19a.JPG)

Im try  
In Query field - {"find": "fields", "type": "text"}
But 
![issue3](https://cloud.githubusercontent.com/assets/24292154/21648653/c29e0e9e-d2af-11e6-96b7-8ec976ac3a9c.JPG)

FROM official site https://www.elastic.co/guide/en/elasticsearch/reference/current/string.html
The string field is unsupported for indexes created in 5.x in favor of the text and keyword fields. Attempting to create a string field in an index created in 5.x will cause Elasticsearch to attempt to upgrade the string into the appropriate text or keyword field.

**Comment by vvp83** [comment]
At my issue i do it - see at issue please!!!
**Im try**
**In Query field - {"find": "fields", "type": "text"}**

**Comment by torkelo** [comment]
> At my issue i do it - see at issue please attentively!!!

What? 

>  {"find": "fields", "type": "text"}

So that did not work I take it? You english is hard to understand.

> strange logic.

I do not understand you english here :( 

Do you wish grafana to change string -> text?
