### ISSUE TITLE
[Bug] Elasticsearch 5.1 - no more type string 

### ISSUE THREAD

**Issue by vvp83** [grafana/grafana#7136]
Grafana Grafana v4.1.0-beta1 (commit: 9dc4264)
Source - Elasticsearch 5.1
OS - docker pull grafana

According  #7135 since Elasticsearch 5.1 not have type String so any operations with this type incompatible

**Comment by torkelo** [comment]
Any reason for opening a duplicate? #7135 looks like the same issue, not sure what Grafana can do here.  Does filtering by type text work?

**Comment by vvp83** [comment]
This not duplicate! It s mean that in grafana must replace string to text for Elasticsearch 5.1!!
Please be more attentively

**Comment by torkelo** [comment]
can you describe the difference? (between this issue and https://github.com/grafana/grafana/issues/7135)
