### ISSUE TITLE
[Bug] API: User document returned by /api/users/:id differs from that returned by /api/users

### ISSUE THREAD

**Issue by sfitts** [grafana/grafana#7137]
Version - 4.0.2

Not entirely sure if this is a bug or intended behavior (in which case I guess this is a feature request), but the JSON properties returned for a user differs when you fetch an individual user by id vs. fetching all users. 

For example:

GET on `/api/users/1` yields:

```
{
    "email": "admin@localhost",
    "isGrafanaAdmin": true,
    "login": "admin",
    "name": "",
    "orgId": 1,
    "theme": ""
}
```

But GET on `/api/users` yields:

```
[
    {
        "email": "admin@localhost",
        "id": 1,
        "isAdmin": true,
        "login": "admin",
        "name": ""
    }
]
```

This is a bit unexpected and makes it harder to implement code which manipulates users via the API since we have to first normalize the output.

**Comment by torkelo** [comment]
This is pretty normal, one returns a list and reduced info.  If you use an ID you get the full info

**Comment by sfitts** [comment]
The fact that one contains `orgId` and one doesn't is fine, but why does the property that indicates if it is an admin change names (`isAdmin` vs `isGrafanaAdmin`).  Same information, different name.

Also, the one fetched with the `id` doesn't contain the `id` property (the argument probably being that you have it in your hands, which is true for the code that does the API call, but might not be for code that is provided the object.

Anyway, not a huge deal, just something that IMO makes the API harder to use than it should be.
