### ISSUE TITLE
[Bug] 4.1b: "Templating: Repeat panel" does not take over whether a graph belongs to the left or right Y-axis

### ISSUE THREAD

**Issue by mirko** [grafana/grafana#7138]
Well, there's not much to add to the title.
I just experience that the assignment of graphs within a panel to the left / right Y axis will not be "repeated".
All graphs in the repeated panels are assigned to the left Y axis and changing a panel only changes it for that particular one.

**Comment by mirko** [comment]
Same with colors for the individual graphs.

**Comment by torkelo** [comment]
The assignment of colors and y-axis is a configuration that is saved using the series name as identifier, that is the only thing Grafan has to go by  (beside series index). 

You can also specify y-axis and series color by using series override & regex (in graph display tab)
