### ISSUE TITLE
Datasources (postgres): can't connect to Neon databases

### ISSUE THREAD

**Issue by shahargl** [grafana/grafana#71408]
### 
# What went wrong?

**What happened**:

When I try to connect to a postgres databases hosted by Neon, I get the following:
  
![image](https://github.com/grafana/grafana/assets/12069200/418a35da-856a-4dc9-afd2-1457b60cfb97)

And there isn't any way to add a connection string parameter to the data source configuration.

**What did you expect to happen**:

  - I expect the connection to work.

### 
# How do we reproduce it?

**Step 1**:

- Create a Neon database (I created it by using the Vercel postgres integration which under the hood uses Neon)

**Step 2**:

- Fill the details in the postgres datasource integration

**Step 3**:

- Click "save and test"

### 
# What Grafana version are you using?

10.0.2-cloud.1.94a6f396

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

I use Grafana Cloud

### Is this a Regression?

None

**Comment by rustyb** [comment]
+1 for this one been doing some prototyping and would be useful to be able to connect to neon and visualise some data from there.

**Comment by san26v** [comment]
+1

**Comment by gabor** [comment]
hi, the `neon.tech` website provides notes on how to fix the `The endpoint ID is not specified` problem at https://neon.tech/docs/connect/connection-errors#the-endpoint-id-is-not-specified.

from these i recommend the `Specify the endpoint ID in the password field` option at: https://neon.tech/docs/connect/connection-errors#d-specify-the-endpoint-id-in-the-password-field

in short, let's say:
- your password is `mypassword`
- your endpoint id is `ab-cdef-something-123456`

you enter this into grafana's password field:  `endpoint=ab-cdef-something-123456;mypassword`.

this way i was able to connect to a neon-hosted postgres database.

hope this helps, if there are still problems, feel free to reply, and we can reopen the issue.
