### ISSUE TITLE
docs: recommend use of semver for plugin versioning

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#71411]
Just to provide guidance that this is a good way to indicate the nature of changes between versions at a glance for consumers. 

Should update `plugin.json` description(s) https://grafana.com/docs/grafana/latest/developers/plugins/metadata/

**Comment by josmperez** [comment]
Hi @academo - I've looked for help in Slack on this a while back, but nobody stepped up. Would you be able to draft a minor change to plugin.json to bring this PR to a close?

**Comment by josmperez** [comment]
> [@josmperez](https://github.com/josmperez) I can gladly help. which PR do you refer to?

Sorry, note about had typo. There's no PR yet, only this issue. We need to open a new PR for this.
