### ISSUE TITLE
[Bug] Not working Group by terms - Elasticsearch 5.x

### ISSUE THREAD

**Issue by vvp83** [grafana/grafana#7142]
Grafana grafana_4.1.0-1483558077beta1_amd64.deb
Source - Elasticsearch 5.1
OS - docker pull grafana

Try get SUM by field free Group by name

![issue4](https://cloud.githubusercontent.com/assets/24292154/21674401/a2ae5b86-d33e-11e6-967d-2363a0df1cdd.JPG)

**Get - Result - NULL**

Debug in Chrome 
![issue5](https://cloud.githubusercontent.com/assets/24292154/21675228/1557c458-d342-11e6-8a0c-01d23188f398.JPG)
![issue6](https://cloud.githubusercontent.com/assets/24292154/21675231/1750c110-d342-11e6-89b9-eda20a27bf18.JPG)

## RAW ES query
curl -XGET 'http://localhost:9200/logger/mem/_search?&pretty=true&size=90' -d '
{"size":0,"query":{"bool":{"must":[{"range":{"timestamp":{"gte":"1483537733769","lte":"1483546961673","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"free:>0"}}]}},"aggs":{"2":{"terms":{"field":"name","size":10,"order":{"_count":"asc"}},"aggs":{"1":{"sum":{"field":"free"}}}}}}
'
## ANSWER
{
  "took" : 22,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 5,
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "logger",
        "_type" : "mem",
        "_id" : "AVlt5aK5rSQAObeZZg0g",
        "_score" : 2.0,
        "_source" : {
          "timestamp" : 1483542128579,
          "free" : 22,
          "free1" : 25,
          "free2" : 28,
          "free3" : 31,
          "name" : "f2"
        }
      },
      {
        "_index" : "logger",
        "_type" : "mem",
        "_id" : "AVlt5ZxBrSQAObeZZg0c",
        "_score" : 2.0,
        "_source" : {
          "timestamp" : 1483542108059,
          "free" : 1,
          "free1" : 11,
          "free2" : 14,
          "free3" : 17,
          "name" : "f1"
        }
      },
      {
        "_index" : "logger",
        "_type" : "mem",
        "_id" : "AVlt5ZzcrSQAObeZZg0d",
        "_score" : 2.0,
        "_source" : {
          "timestamp" : 1483542128579,
          "free" : 2,
          "free1" : 12,
          "free2" : 15,
          "free3" : 18,
          "name" : "f1"
        }
      },
      {
        "_index" : "logger",
        "_type" : "mem",
        "_id" : "AVlt5Z1grSQAObeZZg0e",
        "_score" : 2.0,
        "_source" : {
          "timestamp" : 1483541082252,
          "free" : 20,
          "free1" : 23,
          "free2" : 26,
          "free3" : 29,
          "name" : "f2"
        }
      },
      {
        "_index" : "logger",
        "_type" : "mem",
        "_id" : "AVlt5Z3lrSQAObeZZg0f",
        "_score" : 2.0,
        "_source" : {
          "timestamp" : 1483542108059,
          "free" : 21,
          "free1" : 24,
          "free2" : 27,
          "free3" : 30,
          "name" : "f2"
        }
      }
    ]
  },
  "aggregations" : {
    "2" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "f1",
          "doc_count" : 2,
          "1" : {
            "value" : 3.0
          }
        },
        {
          "key" : "f2",
          "doc_count" : 3,
          "1" : {
            "value" : 63.0
          }
        }
      ]
    }
  }
}

## Model in ES
{
  "mem": {
    "properties": {
      "timestamp": {
        "type": "date"
      },
      "free": {
         "type": "float"
       },
    "free1": {
         "type": "integer"
      },
     "free2": {
         "type": "long"
      },
    "free3": {
         "type": "double"
      },
     "name": {
         "type": "text",
         "fielddata": true
      }
    }
  }
}
'

**Comment by lpic10** [comment]
Just checking here, I see no issue in "terms aggregation" as long as you keep the "Date histogram" group by as well. 

That seems to be the cause, as looking at the query and response sent there is no "Date histogram" aggregation (as this is a graph over time I believe this information is mandatory for the x-axis).

**Comment by vvp83** [comment]
Ok. But i dnt need group by time. It group by terms value. It like SQL query select sum from ... group by....
Please dnt comment if u dnt know.  
Aggregation by time (histogramm) working but this  it no what need. It aggregation by time period!  Not terms value. Please see attentioly my bug - in answer from server at picture you can find that 2 value presents - 3 and 63.  Its right. So this must be 2 value at grafana plot in axis value free and free1 . As XY plot. But this is no datapoint.

**Comment by torkelo** [comment]
Graph panel only supports time series at the moment, you need a group by time. 

https://github.com/grafana/grafana/issues/7158

**Comment by vvp83** [comment]
Its cool but group by not timeseries - very important feature.
