### ISSUE TITLE
Logs: Table visualisation improvements

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#71461]
### Summary
With https://github.com/grafana/grafana/issues/68053 we added an experimental version of a table visualisation for logs in Explore. This issue should iterate on the first version and e.g.:

- Add functionality to show/hide certain columns.
  - this should be done by adding e.g. a button in explore besides the table visualisation, which shows all available labels
  - every label is a column in the table
  - the list of labels has checkboxes which control their visibility
  - column visibility can be controlled by adding transformations to the table frame: https://github.com/grafana/grafana/blob/54050be9f639ae50d27186234c1f5d954e3e17a7/public/app/features/explore/Logs/LogsTable.tsx#L102-L129
- Support filter for/out (like log details)
  - add a `onCellFilterAdded` property to the `Table` in `LogsTable`: https://github.com/grafana/grafana/blob/54050be9f639ae50d27186234c1f5d954e3e17a7/public/app/features/explore/Logs/LogsTable.tsx#L159-L164
  - that method should be used to either call `modifyQuery` or `onClickFilterLabel`, `onClickFilterOutLabel`
  - 
### Scope
Implementation

### Solution
The table visualisation currently does not support show/hide of certain columns. However with logs in Explore - especially if those logs have quite a lot of labels - a lot of columns will be generated. Users might not be interested in all of those columns but just a few.
This PR should create a solution that can show/hide certain columns in the Logs Table visualisation in Explore. -That can either be done via extending the table visualisation and working together with DataViz, or by creating a dedicated version for Logs in Explore.-

**Comment by stevendungan** [comment]
@RamblingCookieMonster if i'm understanding correctly you are looking to see specific fields in a query result? do [logql template functions](https://grafana.com/docs/loki/latest/query/template_functions/), specifically `line_format,` meet your need?
