### ISSUE TITLE
docs: confusing tier availability for usage insights

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#71465]
This page: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/export-logs/

Shows the shields for being available in OSS and Enterprise, but then immediately below claims support in Enterprise and Cloud Pro only.

<img width="790" alt="Screenshot 2023-07-12 at 15 11 15" src="https://github.com/grafana/grafana/assets/19860021/8acb8879-9af8-4912-b984-f4b065dfa99b">

**Comment by GrafanaWriter** [comment]
This will be fixed with https://github.com/grafana/grafana/pull/71548/
