### ISSUE TITLE
Alerting: invalid legacy channel configs fail migration

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#71466]
If a legacy notification channel fails to pass validation when converted to a receiver in UA, the migration will fail.

Currently, the only remedy is to fix or remove the legacy channels before migration, however there may be more we can do.

Some ideas:

- [ ] Do not fail to migrate or start UA embedded alertmanager when there are invalid receivers that aren't used in any notification policy. 
  - https://github.com/grafana/alerting/pull/110
  - https://github.com/grafana/grafana/pull/71500
  - [ ] Optionally, still prevent API POSTS from creating these unused invalid receivers. https://github.com/grafana/grafana/pull/71499
- [ ] If we can be sure the notification channel was not working in legacy alerting anyways, we can likely migrate it to an empty receiver to be populated at a later time.

The above still doesn't cover what to do if there are legacy channels that might work in legacy alerting but don't pass UA validation. I have yet to see an example of this though.

**Comment by yuri-tceretian** [comment]
If a notification setting cannot be migrated then almost certainly it did not work in legacy alerting and was failing (silently!). I think in G11 we should skip "broken" settings which automatically make alerts be delivered to the default contact points, which, in my opinion, is better than silently fail.
