### ISSUE TITLE
[Bug] consistent dips in line graph - false data

### ISSUE THREAD

**Issue by jsirianni** [grafana/grafana#7146]
Please include this information:
- Grafana 4.0.2
- Datasource: localgraphite
- Ubuntu 16.04 LTS
- Datapoints should be +- 100 from 4000
- I have datapoints that are between 1000-2000

Hello, I have a script running on my server that gathers information about our environment, specifically memory consumption. We have several teams that are plotted to individual graphs and we also have a graph that is the sum of all teams' memory consumption. Example data is bellow

Team1 : 500GB
Team2: 500GB
Team3: 1000GB
Team4: 1000GB
Total: 4000GB

Grafana is correctly displaying each team's data. 

Grafana is not correctly displaying the graph that displays the total value for the total graph. My script logs the total metric before sending it to graphite, the value is always between 3500 and 4500, however, grafana shows 1300 - 1500 at random times. An example screenshot is attached. 

Are there any settings that would causes grafana to "average" or "aggregate" the data that might cause this? I am 100% certain that I am not sending the wrong data to grafana and none of my team graphs are behaving this way. 

The software that gathers data, calculates, and sends to graphite works like this.

`
1) Gather data and put into text file
2) Create total variable
3) Create array from text file
4) Iterate through array and send graphite metrics for each team (100% working), increment total value during each iteration
5) Log total value once loop completes (100% working, log shows correct values between 3500-4500)
6) Send total value to graphite
 `

**Graph settings for my "Total" graph**

**Metric**: memconsump.totalram   //this is the metric being sent as the total and verified to be correct
**Axis Left Y**: Show, gigabytes, linear, ymin = 0, ymax = 6000
**Axis Right Y**: Show = false
**X Axis**: Show, Mode = Time
**Legend Options**: Show, As Table
**Legend Values**: Min, Avg, Max, Current    //min shows the false value, decimals = 3
**Hide Series**: With only null = FALSE, With only zeros = FALSE   
**Display Draw Modes**: Lines, Points.
**Mode Options**: Fille = 3, Line width = 2, Point Radius = 2
**Hove Info**: Mode = All series, sort order = none
**Stacking and null value**: Stack = FALSE, Null value = connected
**Alert**: not used
**Time Range**: not used (using global setting at top of screen)

As you can see from the picture, this happens somewhat consistently but not always. It was happening every 30 minutes but later only started happening every hour. Its not 100% predictable. The data for the total graph is accurate except for the obvious dips. 

![screen shot 2017-01-05 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/23043836/21691505/d52fde56-d346-11e6-9076-d2fe66001cee.png)

Thank you for any help.

**Comment by torkelo** [comment]
Please open questions in mailing list.  Thus I'd probably due to Graphite rollup aggregation, check you graphite config.

**Comment by DanCech** [comment]
Null = connected is likely the source of the discrepancy, if you change that to null = null you'll most likely see dips on the individual graphs also because graphite is missing data.
