### ISSUE TITLE
[Bug] 4.1 beta download link broken

### ISSUE THREAD

**Issue by jacobweber** [grafana/grafana#7147]
On http://grafana.org/download/4_1_0/, the link to download v4.1.0-beta1 as a Linux .tar.gz file points to https://grafanarel.s3.amazonaws.com/builds/grafana-4.1.0-1482230757beta1.linux-x64.tar.gz, which returns an error page.

**Comment by torkelo** [comment]
@bergquist do you have the file backed up? I accidentally removed it while doing nightly build cleanup

**Comment by bergquist** [comment]
Closing this since we wont publish a new beta build.
