### ISSUE TITLE
Bug:  X-Axis Mode Series Max is set to Min

### ISSUE THREAD

**Issue by dyu1** [grafana/grafana#7148]
Graphana version 4.0.2
DataSource ElasticSearch
Redhat 6

Axes Tab --> X-Axis changed the mode to Series and Value to Max
The chart would show Min Values instead of Max.  Other values work (Avg, Min, current, etc)

**Comment by torkelo** [comment]
already reported and fixed :)
https://github.com/grafana/grafana/issues/6926

Fix available in 4.1 beta
