### ISSUE TITLE
[Bug] Test Alert Rule is not testing result handler (where no data & exec error rules are handled)

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#7149]
Please include this information:
- What Grafana version are you using? Master
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Amazon Linux
- What did you do? Created and tested an alert and set alerting if no datapoints in last 1 min
- What was the expected result? firing = true as there were no datapoints in last 1 min
- What happened instead? firing = false

If it relates to *alerting*
- An image of the test execution data fully expanded.
<img width="1412" alt="screen shot 2017-01-05 at 11 31 32 am" src="https://cloud.githubusercontent.com/assets/1019609/21694543/b15c32d8-d33a-11e6-9a16-3c8138ca0e4d.png">
<img width="345" alt="screen shot 2017-01-05 at 11 31 39 am" src="https://cloud.githubusercontent.com/assets/1019609/21694549/b87e0b72-d33a-11e6-9b56-53fdefa8cef4.png">
<img width="595" alt="screen shot 2017-01-05 at 11 31 47 am" src="https://cloud.githubusercontent.com/assets/1019609/21694552/bba06a8e-d33a-11e6-8e13-1efbd4bc5b6b.png">

**Comment by torkelo** [comment]
Interesting, it might be just the test rule code that is not looking at the no data option.  That part is in the result handler and if I remember correctly that is no run when testing a rule

**Comment by utkarshcmu** [comment]
I'll look into it and fix the bug! Also, today I updated my Grafana setup with the latest build and I was getting false alerts (not obeying alert settings). So, had to roll back to a previous version of the Grafana build. Will find and fix them asap!

**Comment by torkelo** [comment]
> not obeying alert settings

Do you have an example / test case?

**Comment by utkarshcmu** [comment]
One bug which I saw was when the alert state was "OK" initially and my setting was to "Keep the last state" when there is "No Data", I still got alerts of "No Data".

**Comment by utkarshcmu** [comment]
Simply speaking, Grafana is sending an alert when it should not be sent and does not sends when an alert should be sent, in case of "No Data".

**Comment by torkelo** [comment]
ok, strange. Not sure I have seen that. Will try to replicate. 

Regarding this issue. The test rule "firing" property only relates to the alert conditions. The No data and execution error rule is not tested. 

To solve this issue would require a bit of refactoring, moving parts of the result handler state evaluation into the alert context and removing the "firing" property from the test rule and replace that with a state property instead. 

@bergquist thoughts?

**Comment by utkarshcmu** [comment]
I'll work with @bergquist on resolving this issue and will provide concrete steps to reproduce this issue.

**Comment by jaimegago** [comment]
@bergquist @torkelo I'm seeing somewhat similar behavior except that in my case it "works" when I save the dashboard with the null based alert.
