### ISSUE TITLE
Dashboard Browser: Starred Dashboard Utility Not Working as Expected

### ISSUE THREAD

**Issue by JohnJMartins** [grafana/grafana#71516]
### What happened?

First Issue: Starred select box in the "Dashboards" browser menu stays selected despite moving between menus and returning to normal "Dashboards" menu:
![starredbox](https://github.com/grafana/grafana/assets/77704161/a8c2a1a8-cfa1-4665-8b7e-1ab9f5da4e82)
Second Issue: "Starred" menu does not open when selecting to navigate to it from the normal "Dashboard" browser menu:
![starredmenu](https://github.com/grafana/grafana/assets/77704161/3ee42dd0-ada3-42e4-824e-ee919ef6609e)

### What did you expect to happen?

For the first issue: 
a. Click “Starred dashboards”. The "Starred" checkbox is selected.
b. Navigate to another menu like "Explore" and click “Dashboards” from the other menu. The "Starred" checkbox is unselected.
For the second issue:
a. While on the "Dashboards" menu, click the "Starred" option from the side bar to get to the starred dashboards menu.
b. Should see the starred dashboards with the "starred" option box checked.

### Did this work before?

Unsure as to whether or not this has been an issue with past versions or not, but the current version this is showing up on is 9.4.7.

### How do we reproduce it?

First issue:
- Navigate to the "Dashboards" menu in Grafana. Click the "starred" option box in this menu so that it is checked. Navigate to another menu such as "Explore". Click back to the "Dashboards" menu from the new menu
Second issue:
- Navigate to the "Dashboards" menu in Grafana. Click the "Starred" option in the side bar to try to navigate to the starred dashboards menu and notice that nothing happens.

### Is the bug inside a dashboard panel?

No, this bug appears in the dashboard browser/starred menus and side bar

### Environment (with versions)?

Grafana: 9.4.7
OS: Windows 11
Browser: Edge

### Grafana platform?

None

**Comment by axelavargas** [comment]
Hey @JohnJMartins 👋🏾, thank you for reporting this issue. I am forwarding this issue to the  @grafana/grafana-frontend-platform team, who are responsible for this area.  😄

**Comment by L-M-K-B** [comment]
Hi @JohnJMartins 🙋‍♀️, Thanks a lot for your report. I checked it and would like to let you know that we solved the mentioned issues with Grafana's new navigation which is enabled by default since version 9.5.0 🙌
Please reach out to me or my team (@grafana/grafana-frontend-platform) in case you have any further questions.
