### ISSUE TITLE
Correlations: Add documentation around variable exceptions

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#71511]
When building data links for explore, we had logic that says if a variable is left uninterpolated, as in it didn't have a value match, the data link would be considered invalid and hidden. Our assumption at the time was that an uninterpolated variable would mean an invalid query, and we wouldn't want to show a link for a query that didn't work.

However, as pointed out, some datasources actually injest a static list of variables and interpolate them when running. So they query will keep the uninterpolated variable, send it to the datasource, which will interpolate it behind the scenes. The query does not change in this case.

In #71372 , we added a hardcoded list of variables that would be persisted to be handled in this manner: https://github.com/grafana/grafana/pull/71372/files#diff-34124cfc17041c548a030f411bb98e2ea07cb19541fddd48d2593c01ee551764R237

We will want to add this list to the correlation documentation as it will act differently than other variables and we may get questions about it.

**Comment by GrafanaWriter** [comment]
@gelicia - Thanks for reaching out to the technical writing team with this issue. 

We don’t have a dedicated writer for this area. 

Please don’t let us be a blocker - use [our Writers' Toolkit](https://grafana.com/docs/writers-toolkit/) to create the PR and reach out for review. If the PR isn't reviewed by the time you need to merge, please move forward.
