### ISSUE TITLE
Dashboards: Share Link dialog creates broken link with boolean variables

### ISSUE THREAD

**Issue by lkretzschmar** [grafana/grafana#71517]
### What happened?

In dashboards that use a boolean variable that is set to true, the URL initially contains `&var-myvarname=true`, but if you then change a time range, the URL in the browser changes to `&var-myname`, which works fine if you copy paste that URL.

However, the Share dialog recalculates the URL in `ShareLink.tsx`, line 59, it calls `buildShareUrl`, which is in `utils.ts`. 
On line 63, the `params` array is generated by parsing `window.location.search` into a `URLSearchParams` instance, creating an entry with a key, but no value.
On line 64, this function calls `search.toString()` and `URLSearchParams` outputs this valueless entry as `&var-myvarname=`. This URL is placed in the Share dialog.

When another user pastes this URL into the browser, Grafana parses it and sets the variable `myvarname` to an empty value (not to `true`).

### What did you expect to happen?

Grafana's Share Dialog should generate a correct URL to share with people.

### Did this work before?

No, it's been broken for a while.

### How do we reproduce it?

- Create a dashboard with a simple graph panel
- Create a variable named `isreadwrite`, labelled `Read/Write` with `true` and `false` values.
- Save variable.
- Switch `Read/Write` dropdown to `true`
- Note `&var-isreadwrite=true` in the browser URL (correct)
- Zoom into a time range
- Note the URL changed to `&var-isreadwrite&from...` 
- Click on the Share button for the dashboard
- Note that the URL in the Link tab is incorrect and contains `&var-isreadwrite=&from....`

### Environment (with versions)?

Grafana: v8.5.20
OS: Ubuntu 20.04
Browser: Chrome 114.0.5735.198

### Grafana platform?

A downloaded binary

**Comment by axelavargas** [comment]
Thank you for reporting this issue @lkretzschmar 🏅 , I was able to reproduce it in [Grafana Play](https://play.grafana.org/d/a4e02280-2abc-48f2-9323-14a39d74c396/6f6d1059-e383-5dba-8100-c2c633cc7556?orgId=1&var-isreadwrite=true). 

I am moving this issue to the @grafana/sharing-squad :)

**Comment by juanicabanas** [comment]
Hey @axelavargas thanks for taking this!

I just checked this is not an issue related to the Link feature, but to the Panel zoom.
Before making the zoom, if you check the browser URL, it's correct.
When you make the zoom, the URL is modified (because of the time range query params) and the query param `var-isreadwrite` is also affected.
Then, the Link feature code just takes that URL.

Is @grafana/dataviz-squad the correct squad?
