### ISSUE TITLE
[Feature request] Show percent number in addition to the real value when Percent is checked

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7152]
Please include this information:
- What Grafana version are you using?
v4.0.2
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS 6
- What did you do?
Display legends as percent
- What was the expected result?
When checking `Display` -> `Stacking & Null Value` -> `Percent`, show percent number of each legend for both `Legend`->`Values` and `Display` -> `Hover Info`, for example, when checking `Current` under `Legend` -> `Values`, it should display `LegendA Current: 20, Percent: 20%, LegendB Current:80, Percent: 80%`, in the Hover Info dialog, it should display `LegendA 20 (20%)`
- What happened instead?
The graph only shows real values when `Percent` is checked

**Comment by torkelo** [comment]
This is not currently possible (in a easy way). The percent display option is likely going away, to be replaced with query transformations (so percent calculation is done in query step and not at display time)

**Comment by wei-hai** [comment]
@torkelo Thank you for the information, may I know if this new feature you mentioned applies to specific or all kinds of datasources? And is there a ticket number or milestone for it?
