### ISSUE TITLE
Alerting: old states after upgrade

### ISSUE THREAD

**Issue by driv** [grafana/grafana#71523]
### What happened?

After upgrading from 9.1.6 to 9.5.5
Some alerts are showing old states

![image](https://github.com/grafana/grafana/assets/2446353/6c5b0762-bff7-4379-a94f-134e16e19dbd)

### What did you expect to happen?

The old states should not be there.

### Did this work before?

Yes. The old states were not visible before the upgrade.

### How do we reproduce it?

1. 
2.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: docker.io/bitnami/grafana:9.5.5-debian-11-r0 
OS: Linux
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Promethesu and Loki

**Comment by driv** [comment]
Is there any way to clear the alert states without deleting and re-creating the alert?

**Comment by driv** [comment]
Most of the alerts have been migrated fine. Only a few came with old states that are not being cleared.

**Comment by JacobsonMT** [comment]
Hi @driv, do the old states go away eventually once the alert rule is evaluated? If not, does updating the alert rule fix the problem?


> Is there any way to clear the alert states without deleting and re-creating the alert?

Basically any change to the alert rule definition should clear the alert states.

**Comment by driv** [comment]
Now I'm not entirely sure if it was an issue, because alerts evaluation was disabled when this happened.

I was testing a new instance before upgrading by importing the database of the old instance.

And at least in that situation, editing the alert did not clear the states.

**Comment by JacobsonMT** [comment]
>Now I'm not entirely sure if it was an issue, because alerts evaluation was disabled when this happened.

Ah, that makes sense. I haven't tested this myself, but I could easily see this causing old states to stay since the process for them to clear is not running.

If you want to be sure yourself, 9.5.5 has alert rule pausing so if these are grafana-managed alerts, you can pause your individual alerts (or create a silence on a catch-all like `alertname~=.+`) and re-enabled alerting at the grafana level.

**Comment by armandgrillet** [comment]
No answer for more than a month thus closing the issue, please reopen if you have more details.
