### ISSUE TITLE
Improve the "Public" tag functionality

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#71539]
### Background / Why we're doing this

The tag for "Public" makes it look like it’s a button. But might be solved by using the badge component, using an outline style. 

### Problems or tasks

The "Public" tag looks like a button, but is not clickable:
![image (23)](https://github.com/grafana/grafana/assets/51436795/0e86c45d-6ca7-427b-94b4-4ca15d714313)

Need to investigate if this is an actual problem where this tag needs to be a button or just change its style and not look like a button.

### Deliverables

- Figma mockup
```[tasklist]
### Tasks
- [x] UX: research options
- [x] Design Mockups
- [x] Feedback from DS squad
```

**Comment by thanos-karachalios** [comment]
@natydej @natellium I think this needs a bit more thought. One point is about the label of a public dashboard and the other one is about improving the overall UX of the sharing experience. 

• The label is just a badge indicating the dashboard is Public. Do we want to be clickable? and what should be the action?

• The second point of improving the overall sharing experience is larger and should aligned with the work of the toolbar as well (new design of sharing button, placement, behaviour in smaller screens etc). 

We can have two separate issues on this one

**Comment by natydej** [comment]
@thanos-karachalios  Yes, exactly, this issue is just to solve the first point that you mentioned (About the badge indicating that is Public). Later, we are going to create another epic for the whole sharing experience modal...

**Comment by natellium** [comment]
@natydej Maybe we rephrase the first part of the epic then to scope it only to the public tag. As we discussed yesterday as well, we don't have a lot of feedback atm that says this is a problem, so we may wanna also wanna rephrase that part as we'd need to figure out if that's an actual problem :)

**Comment by natydej** [comment]
Connecting this [issue](https://github.com/grafana/grafana/issues/63509) to the labels/tags/badges unification.

I did some research to complete that audit above to propose some ideas about how can we use a badge
Link [Doc](https://docs.google.com/document/d/1aR2WtbrQXHJXNHK8bwDaocWsNQQ4EOVLNt5E1Cjqnno/edit)

**Outcome:**

Badges are a low-attention indicator
The purpose of this is to be informational
Highly recommend not using an icon when is not actionable - also is not adding any value here

**Next Steps:**

Unify this UI style with the upcoming changes on this Design System component - sync with @zizzpudding  to share with her these proposals.

[Figma link](https://www.figma.com/file/rPzflElZXoRp3PAtDiYicZ/Share-dashboard?type=design&node-id=1108-15939&mode=design)

**Comment by natydej** [comment]
While we have to wait for the implementation of the new design of our badges, we can change this `tag` to be a `badge` (neutral one), to be consistent with the usage of this component, which is a **read only** and it will not have the prominence that a button has.

Current
<img width="1444" alt="Before" src="https://github.com/grafana/grafana/assets/51436795/4eb4716f-d9e2-4a51-b35a-b4c22079ce71">

Proposal
<img width="1444" alt="After" src="https://github.com/grafana/grafana/assets/51436795/d967d2c0-cd48-42a7-9eff-3417040fc20e">


[Figma Link](https://www.figma.com/file/rPzflElZXoRp3PAtDiYicZ/Share-dashboard?type=design&node-id=1108-15939&mode=design)

cc @evictorero @juanicabanas

**Comment by natydej** [comment]
Follow up this issue by this [PR](https://github.com/grafana/grafana/pull/77563)

**Comment by natydej** [comment]
Follow up this issue with this [PR](https://github.com/grafana/grafana/pull/77563)
