### ISSUE TITLE
Feature request - Add support for different models, settings in moving average

### ISSUE THREAD

**Issue by vaibhavinbayarea** [grafana/grafana#7153]
Presently, the moving average option options tab did not expose the various knobs and settings that are available. The various settings and their values can be found here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-movavg-aggregation.html 

I have a patch that will update the options panel based on the model selected etc. 

![screen shot 2017-01-05 at 3 27 02 pm](https://cloud.githubusercontent.com/assets/4401392/21701609/774635dc-d35b-11e6-8d4d-2856d421ecc8.png)

![screen shot 2017-01-05 at 3 28 29 pm](https://cloud.githubusercontent.com/assets/4401392/21701625/a7a06e00-d35b-11e6-920c-2a5670843318.png)

- What Grafana version are you using?
Version 4.1.0-beta1 (commit: v3.1.0-1929-g6505721)

- What datasource are you using?
Elasticsearch

Will be creating a pull request soon

**Comment by marefr** [comment]
Fixed by #7154
