### ISSUE TITLE
i18n: Mark up Correlations for translations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#71535]
### Requirements ###

Add support for i18n in Correlations components (`features/correlations`). All text presented in the UI should have i18n keys.

### Background

This is required for the feature to be GA.

#### Details

* No translations need to be provided, just i18n keys
* Follow guidelines described in https://github.com/grafana/grafana/blob/main/contribute/internationalization.md
* Add `<Trans i18nKey ...` to all components in `features/correlations` 
* Prefix `i18nKey` with `correlations.`
* Don't change translation files. After adding new `<Trans i18nKey ...` run `yarn i18n:extract`

#### Notes

* Change the language in user profile
* Translations are saved in public/locales/

🚧 Outstanding questions

...

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/75444
- [ ] https://github.com/grafana/grafana/issues/75445
```

**Comment by khushijain21** [comment]
Hello, can I work on this?
