### ISSUE TITLE
Can't edit panel in Chrome in Grafana 8.2.0

### ISSUE THREAD

**Issue by limabing** [grafana/grafana#71556]
### What happened?

Clicking the triangle next to the panel title doesn't open a menu in Chrome

### What did you expect to happen?

That it opens a menu, as it does 

### Did this work before?

i use grafana-6.5 before,Grafana-6.5worked correctly

### How do we reproduce it?

1.i don't know
2.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:8.2.0
Browser: edge 114.0.1823.79 and google chrome 114.0.5735.199 
OS:Windows 11 Family Chinese Version 22000.2176

### Grafana platform?

A downloaded binary

### Datasource(s)?

TDengine

**Comment by zuchka** [comment]
we no longer support grafana 8. please upgrade to v9 or v10 and test your issue again. thanks!

**Comment by limabing** [comment]
> we no longer support grafana 8. please upgrade to v9 or v10 and test your issue again. thanks!

ok,thanks for your reply!
