### ISSUE TITLE
row count is wrong

### ISSUE THREAD

**Issue by lucas7617** [grafana/grafana#71568]
### What happened?

when we apply a filter inside the panel, the count of rows continues counting all items outside the filter

### What did you expect to happen?

when applying a filter within the panel, the Rows should only show the count of the amount with the filter

### Did this work before?

no

### How do we reproduce it?

1.apply filter inside the panel
2. the rows must count the quantity of the items again
3.rows display the correct values

### Is the bug inside a dashboard panel?

all panels

### Environment (with versions)?

Grafana:9.5
OS:Enterprise 
Browser: chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by zuchka** [comment]
please list the exact panel visualization that you are using. thanks!

**Comment by lucas7617** [comment]
row count example:

![image](https://github.com/grafana/grafana/assets/134515828/ee03437b-23c0-4f0a-9402-79906ca2d244)

when we filter it does not adjust the count

![image](https://github.com/grafana/grafana/assets/134515828/40e3ce3b-399e-4527-83d8-27c63b69c01a)

**Comment by lucas7617** [comment]
this also happens when we are going to export to excel, for example in the first image it has all the results, let's say I want the results 7, when we export to excel it stopped exporting with a filter and exports all the results, if I'm not mistaken this worked until to 9.0.1

**Comment by codeincarnate** [comment]
I've been able to confirm this, we'll put it in the backlog as part of our ongoing table panel enhancements.

**Comment by lucas7617** [comment]
thanks

**Comment by Falco68** [comment]
Hello,
I have the same issue, slightly different.
With the first filter count is OK, but the count don't change after applying a second filter.
Tested with versions v10.4.0 and v10.3.3
![image](https://github.com/grafana/grafana/assets/36880495/f1c2fa77-ac28-4a61-873c-3395d07197c6)

**Comment by Falco68** [comment]
A small precision, in my example, if I filter first on third column and then in the first one, the count is OK, 11.

**Comment by drew08t** [comment]
> Hello, I have the same issue, slightly different. With the first filter count is OK, but the count don't change after applying a second filter. Tested with versions v10.4.0 and v10.3.3 ![image](https://private-user-images.githubusercontent.com/36880495/334748028-f1c2fa77-ac28-4a61-873c-3395d07197c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzYzMDgsIm5iZiI6MTcxODAzNjAwOCwicGF0aCI6Ii8zNjg4MDQ5NS8zMzQ3NDgwMjgtZjFjMmZhNzctYWMyOC00YTYxLTg3M2MtMzM5NWQwNzE5N2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE2MTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNzViOGJmNTU3ODEyMmJkM2Q1ZDRiNThiMzQzNDhkMTU2ZmUyODdmODA3NjVmMTY5ZjE1ZDI4OThkYWI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_lofcRBXfllk8BFornutLas9sY49AGv7716C2LZgsE)

I am able to replicate this behavior. As you pointed out, this only occurs when the first column is filtered first followed by a second filter.
