### ISSUE TITLE
not exporting to excel correctly

### ISSUE THREAD

**Issue by lucas7617** [grafana/grafana#71563]
### What happened?

When we are going to export in excel, if we apply the filter inside the panel it exports all the data, or when we are going to apply a filter in the column inside the export tab it just closes, this is a bug

### What did you expect to happen?

When we are going to export in excel, if we apply the filter inside the panel to export data the filter it exports all the data, or when we are going to apply a filter on the column inside the export tab it just closes, this is a bug

### Did this work before?

that it exports to excel according to the filter inside the panel

### How do we reproduce it?

1. select the filter in the panel
2. click export
3. export is closed or when it doesn't happen, it exports all data

### Is the bug inside a dashboard panel?

não

### Environment (with versions)?

Grafana: 10.0.1
OS: ENTERPRISE
Browser: chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

all data source

**Comment by starkie-projetos** [comment]
Same problem on OSS 10.0.3

**Comment by starkie-projetos** [comment]
***@***.***
[TOTVS]
JULIANO IDOGAWA / planejamento e gestão
(11) 99383-3393
www.starkie.com.br<http://www.starkie.com.br/>
***@***.******@***.***>
PARCEIRO HOMOLOGADO:
***@***.***


De: Alexa V ***@***.***>
Enviada em: quinta-feira, 27 de julho de 2023 13:03
Para: grafana/grafana ***@***.***>
Cc: Juliano Idogawa ***@***.***>; Comment ***@***.***>
Assunto: Re: [grafana/grafana] not exporting to excel correctly (Issue #71563)


Hey, @lucas7617<https://github.com/lucas7617> 👋🏾 , thank you for reporting this issue, unfortunately, I am unable to reproduce the issue. Is it possible that you to provide a screenshot/video showing the problem?
Maybe you can try using https://play.grafana.org/ if you are working with sensitive data 😄.

Thank you 🙏🏾

**Comment by lucas7617** [comment]
Hi Alexa, nice to meet you!
There are several Bugs in one video,

1st the lines do not adjust the number according to the filter
2nd data export can't export what we put in the dashboard filter
3rd since 9.1 has this bug that when clicking on a filter within the list closes the export out of nowhere.

when I put it in the 12.9 filter it should only count the one that only 12.9 in rows and when exporting it should export only that single result, it was working until 9.1 but it started to give several bugs from 9.3 to 10.0.3

Here is an example video.


link in 720p : https://drive.google.com/file/d/1_YvAhBwCd6FDJwVSgsu6h5CAWMQNDHLE/view
________________________________
De: starkie-projetos ***@***.***>
Enviado: quinta-feira, 27 de julho de 2023 18:10
Para: grafana/grafana ***@***.***>
Cc: Lucas Oliveira ***@***.***>; Mention ***@***.***>
Assunto: Re: [grafana/grafana] not exporting to excel correctly (Issue #71563)



***@***.***
[TOTVS]
JULIANO IDOGAWA / planejamento e gestão
(11) 99383-3393
www.starkie.com.br<http://www.starkie.com.br/>
***@***.******@***.***>
PARCEIRO HOMOLOGADO:
***@***.***


De: Alexa V ***@***.***>
Enviada em: quinta-feira, 27 de julho de 2023 13:03
Para: grafana/grafana ***@***.***>
Cc: Juliano Idogawa ***@***.***>; Comment ***@***.***>
Assunto: Re: [grafana/grafana] not exporting to excel correctly (Issue #71563)


Hey, @lucas7617<https://github.com/lucas7617> 👋🏾 , thank you for reporting this issue, unfortunately, I am unable to reproduce the issue. Is it possible that you to provide a screenshot/video showing the problem?
Maybe you can try using https://play.grafana.org/ if you are working with sensitive data 😄.

Thank you 🙏🏾

**Comment by lucas7617** [comment]
Hi Alexa, nice to meet you!
There are several Bugs in one video,

1st the lines do not adjust the number according to the filter
2nd data export can't export what we put in the dashboard filter
3rd since 9.1 has this bug that when clicking on a filter within the list closes the export out of nowhere.

when I put it in the 12.9 filter it should only count the one that only 12.9 in rows and when exporting it should export only that single result, it was working until 9.1 but it started to give several bugs from 9.3 to 10.0.3

Here is an example video.


link in 720p : https://drive.google.com/file/d/1_YvAhBwCd6FDJwVSgsu6h5CAWMQNDHLE/view

**Comment by lucas7617** [comment]
> Ei,@lucas7617👋🏾 , obrigado por relatar este problema, infelizmente não consigo reproduzi-lo. É possível que você forneça uma captura de tela/vídeo mostrando o problema? Talvez você possa tentar usar https://play.grafana.org/ se estiver trabalhando com dados eficazes😄.
> 
> Obrigado 🙏🏾

Hi Alexa, nice to meet you!
There are several Bugs in one video,

1st the lines do not adjust the number according to the filter
2nd data export can't export what we put in the dashboard filter
3rd since 9.1 has this bug that when clicking on a filter within the list closes the export out of nowhere.

when I put it in the 12.9 filter it should only count the one that only 12.9 in rows and when exporting it should export only that single result, it was working until 9.1 but it started to give several bugs from 9.3 to 10.0.3

Here is an example video.


link in 720p : https://drive.google.com/file/d/1_YvAhBwCd6FDJwVSgsu6h5CAWMQNDHLE/view

**Comment by evictorero** [comment]
Hi @lucas7617 thanks for this detailed video. I couldn't reproduce issues 2 and 3 in [play.grafana.com](https://play.grafana.org/) probably because on Grafana 10.1 the filter in the export tab [was removed](https://github.com/grafana/grafana/pull/71226). Can you try the latest version?
I would check with UX about the first issue you mentioned about the pagination numbers.

**Comment by evictorero** [comment]
Hi @natydej . This image has applied an inline filter that returns only 1 row but the entire dataset has 1426 rows (along 9 pages).
What should be displayed in the pagination controls? Is it wrong to be explicit about the dataset being bigger but there is a filter applied? Or should we display 1 page and 1 row?

![image](https://github.com/grafana/grafana/assets/20256983/4c1888d6-92a3-4202-b097-d219646bba79)

**Comment by lucas7617** [comment]
> Oi@natydej. Esta imagem aplicou um filtro embutido que retorna apenas 1 linha, mas todo o conjunto de dados tem 1426 linhas (ao longo de 9 páginas). O que deve ser exibido nos controles de paginação? É errado ser explícito sobre o conjunto de dados ser maior, mas há um filtro aplicado? Ou devemos exibir 1 página e 1 linha?
> 
> ![imagem](https://user-images.githubusercontent.com/20256983/261410756-4c1888d6-92a3-4202-b097-d219646bba79.png)


Hey,

wow, what a shame that they removed the filters in the export to excel part, that must be why problem 3 happens.

**Comment by juanicabanas** [comment]
Hey @lucas7617 . As @evictorero said, the filter in the export tab was removed. However, our team will be working on this feature as you can see [here](https://github.com/grafana/support-escalations/issues/6562).
