### ISSUE TITLE
 [Bug] Install Script in Ubuntu is not working

### ISSUE THREAD

**Issue by ihipop** [grafana/grafana#7156]
- What Grafana version are you using?
Want to Install Latest
- What datasource are you using?
None
- What OS are you running grafana on?
ubuntu xenial
- What did you do?
https://packagecloud.io/grafana/stable/install#bash
Run the Install Script 
- What was the expected result?
Can install the latest grafana via Apt Command
- What happened instead?
Apt din't show any latest version of grafana after `apt-get update`  but the 2.6.x shipped with the distribute
The Content in `/etc/apt/sources.list.d/grafana_stable.list`
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/grafana/stable

deb https://packagecloud.io/grafana/stable/ubuntu/ xenial main
deb-src https://packagecloud.io/grafana/stable/ubuntu/ xenial main

```
which seems right and the same with the API https://packagecloud.io/install/repositories/grafana/stable/config_file.list?os=Ubuntu&dist=xenial&source=script

After adding the debian one, then it shows up but it's the debian one
`deb https://packagecloud.io/grafana/stable/debian/ jessie main`

![image](https://cloud.githubusercontent.com/assets/423077/21705985/702a6a5e-d3fe-11e6-961a-f171f52f4708.png)

**Comment by torkelo** [comment]
please follow the install instructions: 
http://docs.grafana.org/installation/debian/#apt-repository

We do not publish separate packages for each distro & version
