### ISSUE TITLE
OKTA:  Okta login failing after upgrade to 10.0.1

### ISSUE THREAD

**Issue by ArcticSnowman** [grafana/grafana#71570]
### What happened?

When a user clicks on the "login with otka" button the screen refreshes back to the login screen.

The following is in the logs 

```
Jul 13 09:25:28|intkas006-prod3| logger=context userId=0 orgId=1 uname= t=2023-07-13T13:25:28.944323962Z level=info msg="Request Completed" method=GET path=/login/okta status=302 remote_addr=172.16.2.41 time_ms=10 duration=10.834063ms size=290 referer=https://grafana.grantstreet.com/login handler=/login/:name
Jul 13 09:25:28|intkas006-prod3| logger=oauth t=2023-07-13T13:25:29.22991848Z level=info msg="state check" queryState=5c762bd1735165f9d2b73d8140988fa9d4b22a86838cdd2c5564de7f5bdbf37e cookieState=5c762bd1735165f9d2b73d8140988fa9d4b22a86838cdd2c5564de7f5bdbf37e
Jul 13 09:25:29|intkas006-prod3| logger=secrets t=2023-07-13T13:25:29.724838279Z level=error msg="Failed to get current data key" error="Error 1062: Duplicate entry '' for key 'PRIMARY'" label=2023-07-13/root@secretKey.v1
Jul 13 09:25:29|intkas006-prod3| logger=context userId=0 orgId=1 uname= t=2023-07-13T13:25:29.725103625Z level=warn msg="Error 1062: Duplicate entry '' for key 'PRIMARY'"
Jul 13 09:25:29|intkas006-prod3| logger=secrets t=2023-07-13T13:25:29.745396974Z level=error msg="Failed to get current data key" error="Error 1062: Duplicate entry '' for key 'PRIMARY'" label=2023-07-13/root@secretKey.v1
Jul 13 09:25:29|intkas006-prod3| logger=http.server t=2023-07-13T13:25:29.745514889Z level=error msg="Failed to set encrypted cookie" err="Error 1062: Duplicate entry '' for key 'PRIMARY'"
Jul 13 09:25:29|intkas006-prod3| logger=context userId=0 orgId=1 uname= t=2023-07-13T13:25:29.745579972Z level=info msg="Request Completed" method=GET path=/login/okta status=302 remote_addr=172.16.2.41 time_ms=522 duration=522.19025ms size=29 referer= handler=/login/:name
```

### What did you expect to happen?

Should log me in..

### Did this work before?

Worked with 8.5.2

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.0.1
OS:  Ubuntu 20.04 Container in Kube
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by ArcticSnowman** [comment]
https://github.com/grafana/grafana/blob/95620cdd34a5ea4d796c6eb39427df99b359c2be/pkg/services/secrets/database/database.go#L36-L39

**Comment by ArcticSnowman** [comment]
I copied the value from name to id and that seem to fix the issue. 

Maybe the pkg/services/sqlstore/migrations/secrets_mig.go needs a check that the "id" column check that the value is not null and sets to the the name column if missing

**Comment by joanlopez** [comment]
Hi @ArcticSnowman,

This is indeed weird. Is the screenshot you shared the state of your database after upgrading to v10.0.1?

What surprises me is that you have an `id` column while you should not (see [here](https://github.com/grafana/grafana/blob/95620cdd34a5ea4d796c6eb39427df99b359c2be/pkg/services/sqlstore/migrations/secrets_mig.go#L69)).
Moreover, that hasn't changed since a year ago, so even more surprising.

Did you upgrade from v8.5.2 to v10? Looks like something went wrong while executing these migrations.

**Comment by ArcticSnowman** [comment]
The screen shot is from the database after running 10.0.1 for the first time.   Something must have gone wrong as out 'test" deployment of grafana the database table does not have ID col and `name` is the primary key

**Comment by ArcticSnowman** [comment]
Checking migration_log I see 
```
rename data_keys name column to id	ALTER TABLE `data_keys` CHANGE `name` `id` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
add name column into data_keys	alter table `data_keys` ADD COLUMN `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' 
copy data_keys id column values into name	UPDATE data_keys SET name = id
rename data_keys name column to label	ALTER TABLE `data_keys` CHANGE `name` `label` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
```

**Comment by PovilasV1** [comment]
Having the same issue after upgrading Grafana from v8.5.21 to v10.0.2. My data_keys table structure:
```
mysql> describe data_keys;
+----------------+--------------+------+-----+---------+-------+
| Field          | Type         | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+-------+
| id             | varchar(100) | NO   | PRI | NULL    |       |
| active         | tinyint(1)   | NO   |     | NULL    |       |
| scope          | varchar(30)  | NO   |     | NULL    |       |
| provider       | varchar(50)  | NO   |     | NULL    |       |
| encrypted_data | blob         | NO   |     | NULL    |       |
| created        | datetime     | NO   |     | NULL    |       |
| updated        | datetime     | NO   |     | NULL    |       |
| label          | varchar(100) | YES  |     | NULL    |       |
| name           | varchar(100) | NO   |     |         |       |
+----------------+--------------+------+-----+---------+-------+
9 rows in set (0.00 sec)

```
The id is also empty:
```
mysql> select id from data_keys;
+----+
| id |
+----+
|    |
+----+

```
Google oauth login fails with these error messages:
```
logger=secrets t=2023-08-02T06:34:08.195224448Z level=error msg="Failed to get current data key" error="Error 1062: Duplicate entry '' for key 'PRIMARY'" label=2023-08-02/root@secretKey.v1
logger=context userId=0 orgId=0 uname= t=2023-08-02T06:34:08.195336874Z level=warn msg="Error 1062: Duplicate entry '' for key 'PRIMARY'"
logger=secrets t=2023-08-02T06:34:08.208685624Z level=error msg="Failed to get current data key" error="Error 1062: Duplicate entry '' for key 'PRIMARY'" label=2023-08-02/root@secretKey.v1
logger=http.server t=2023-08-02T06:34:08.208774393Z level=error msg="Failed to set encrypted cookie" err="Error 1062: Duplicate entry '' for key 'PRIMARY'"
```

**Comment by joanlopez** [comment]
> Having the same issue after upgrading Grafana from v8.5.21 to v10.0.2. 

Hi @PovilasV1,

Again, looks like something went wrong when executing the database migrations to upgrade from `v8.5.x` to `v10.0.x`. Could you look at and share the Grafana logs when these migrations were executed, in order to see if there's any insight pointing to what went wrong while executing them, please?

Thanks!

**Comment by PovilasV1** [comment]
Sadly the logs have been rotated and we no longer have them. Updating the table structure seems to have helped.

**Comment by joanlopez** [comment]
> Sadly the logs have been rotated and we no longer have them. 

Ouch! That will make this research harder, but we'll try to reproduce it anyway. Thanks!

> Updating the table structure seems to have helped.

Glad to know! :)
