### ISSUE TITLE
[Bug] regex in templating variable not working in Grafana 4.0

### ISSUE THREAD

**Issue by ronnevo** [grafana/grafana#7157]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.0
- What datasource are you using?
InfluxDB 1.0
- What OS are you running grafana on?
Ubuntu 12
- What did you do?
I have a template variable that is multi-select. 
Tried to use a regex in the templating variable. it used to work on Grafana 2.6. 
Using "Access.*" I got information for all the ports that started with "Access" 
Now it ignores the input or put something else there. 

- What was the expected result?
The expected result was to get the counters from all the ports that start with "Access"

- What happened instead?
Nothing really, it either ignores the input, selects the one on 
It looks like there was some change in grafana 3.0 where the option to specific "regex/glob/pipe" was removed. but it's not clear if it was replaced by something else, or there is no way to retrieve regex based variables. 

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
`Access.*` is not a valid influxdb query. 

Are you using something like `HOW TAG VALUES WITH KEY = "hostname" WHERE "datacenter" =~ /^Access.*/ `  ?  

That is working here

**Comment by ronnevo** [comment]
I'm trying to use the "/^Access.*/" in one of the metrics queries as in:
![image](https://cloud.githubusercontent.com/assets/23202531/21708571/018130c0-d38f-11e6-9e64-036eace89815.png)

I'm trying to replace the "p_nm =~ /^Access.*/" in "p_nm = /^$port/" 
it used to be in Grafana 2.6 that $port would take any regex, but it doesn't seem to work in Grafana 4.0.
As far as I can tell the query adds escape chars to the "." and "*"

**Comment by torkelo** [comment]
p_nm = /^$port/" wont work as that is not valid InfluxDB. you need regex operator `=~`

**Comment by ronnevo** [comment]
yes, it's a typo on my part. Even with "p_nm =~ /^$port/" it doesn't work.
i used to be able to set the port variable in the template to Access.* by typing the string at the top and this was passed to influx. Now it looks like when I type Access.* in the text box it looks like grafana passes to influx Access\.\* instead which influx doesn't take as a regex.

**Comment by torkelo** [comment]
Template variables does not currently support custom values that are not escaped, if the values need to be escaped (single thing  variable supports multi and I'd used with regex operator) all query values need to be regex escaped before being interpolated in the query, and custom values specified in the template variable value drop down is no different

**Comment by ronnevo** [comment]
That's too bad. It's a major de-feature compared with grafana 2.6. 
What was the reason?
It doesn't scale well when there is a need to select 10, 20 or more items. For example it was possible to use the regex option as a CIDR equivalent, such as selecting the IP range 10.10.10..* (10.10.10.0/32). It's not really practical to select them one by one.

Are there plans to put it back in?
Or do you have a pointer on how to change it on our systems?

**Comment by torkelo** [comment]
I am not sure how to implement it as the escaping happens on demand when a string is being interpolated , and no way to know when to escape and when not to. Maybe if manually entered value gets marked as manual then the interpolation engine can take that into account

**Comment by ronnevo** [comment]
It used to be that the multi-value selection had the options regex/blob/pipe
from http://docs.grafana.org/datasources/influxdb/ 

![image](https://cloud.githubusercontent.com/assets/23202531/21752242/a095b6ee-d589-11e6-8e79-f648e195c97f.png)

was this extra information used to control the escaping?

It looks like part of the breaking changes in 3.0 included:
from: http://grafana.org/blog/2016/03/31/grafana-3.0-beta-released/ 
====
Breaking changes
Dashboards from v2.6 are compatible; no manual updates should be necessary. There could be some edge case scenarios where dashboards using templating could stop working. If that is the case just enter the edit view for the template variable and hit Update button. This is due to a simplification of the variable format system where template variables are now stored without any formatting (glob/regex/etc), this is done on the fly when the variable is interpolated.
====

Is that the reason that the control of interpolation isn't working?

**Comment by torkelo** [comment]
Yes, the templating system was refactored / rewritten in 3.0 one of  the things that was simplified was improved as well as the removal of that formatting option as it caused many issues for users. Users got the setting wrong, and it also made a template variable's applicability limited to only one data source. For example you could not use the same variable in different data sources that required different formating. Now the formating is done on demand by the calling code, so InfluxDB interpolates variables using regex for mult format, and Graphite uses glob etc.

**Comment by ronnevo** [comment]
In that case, how come the InfluxDB treats the regex different if I write it in the query vs. it gets if from the template?
The string "Demo.*" works fine when it's part of the query, but if it comes from the template it is being escaped. Shouldn't it behave the same in both cases?

**Comment by Scott-Phosphore** [comment]
@ronnevo Have you found a solution for this problem ?

**Comment by ronnevo** [comment]
nope, in some cases we embed the regex as part of the query of a specific metric but didn't find a way to make them part of the template variables

**Comment by bjett3** [comment]
@torkelo So because the ability to use globbing, regex and wildcards in Template variables "confused" people it was decided to re-code to remove this feature. That sounds like the dumbest reason to remove a feature that is essential when creating the dynamic graphing and dashboards that make grafana so relevant and powerful in today's marketplace.

Re-coding a feature to fix an educational issue seems ridiculous. Could grafana allow an option to define the templating varibles type as string if the globbing is confusing.

**Comment by torkelo** [comment]
>  That sounds like the dumbest reason to remove a feature that is essential when creating the dynamic graphing and dashboards that make grafana so relevant and powerful in today's marketplace.

Say's the guy who does not has to answer hundreds of questions from confused & angry users :) 

Having this as a template variable option did not make any sense as it forced you to only be able to use it in one context (or for once data source). You might have a variable that you want to use in an Graphite query and Elasticsearch query, and show in a title all require different formatting. So now the context (the caller of interpolation) decides how a value is to be formatted, so Elasticsearch datasource interpolating a query before sending it will interpolate it using lucene multi value syntax & escaping rules, Graphite data source will use globbing etc. 

There are some edge cases where the use needs more control over this I agree but think this should be done not as a template variable option but when you use it. Something like this: `$servers.formatAsRegex()`

**Comment by bjett3** [comment]
Torkelo,

Will admit I was pretty perturbed when I wrote the comment. I agree angry users are the worst! :) I have to agree your reasoning does hold water and now that I am calmer makes sense in retrospect. so if I call the variable with .formatAsRegex() will the elasticsearch query treat it as such. That would fix a lot.
