### ISSUE TITLE
Alerting: The Alert list won't be refreshed automatically after upgrade to 10.0.2

### ISSUE THREAD

**Issue by ErfanDL** [grafana/grafana#71593]
### What happened?

The Alert list won't be refreshed automatically after upgrade to 10.0.2

### What did you expect to happen?

should be automatically refreshing the Alert list.

### Did this work before?

working without issue on 10.0.1

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 10.0.2
OS: Debian 11 ARM64 on RaspberryPi 4
Browser: Chrome, FireFox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by konrad147** [comment]
I reproduced the issue, I can confirm this is a bug

**Comment by ErfanDL** [comment]
I updated to version 10.0.3 but the problem still persists !
