### ISSUE TITLE
[Change]: Rename "Alert Notification" concept to Notification Channel

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7159]
I am thinking we can make the concept of `Alert Notifications` more clear if we rename it to `Notification Channel`.

![image](https://cloud.githubusercontent.com/assets/10999/21713819/16c9de7e-d3fc-11e6-8655-b78b05cfdf01.png)

I just think it's a bit confusion with `Notifications` page under alerting that don't contain actual notifications. 

![image](https://cloud.githubusercontent.com/assets/10999/21713869/56179de6-d3fc-11e6-8426-08ff178829dd.png)

thoughts @mattttt , @bergquist ?

**Comment by utkarshcmu** [comment]
+1 to this... I mentioned the same thing 3 months back in this issue - https://github.com/grafana/grafana/issues/6314#issue-183781719

"Notification Channel" is more intuitive... 👍

**Comment by jaimegago** [comment]
Yes yes yes.
