### ISSUE TITLE
Docs feedback: /docs/sources/setup-grafana/configure-security/configure-authentication/saml/index.md

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#71621]
On my Macbook, to base64 encode my cert files, these commands on [this docs page](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/saml/#example-of-how-to-generate-saml-credentials) did not work:

```
$ base64 -w0 key.pem > key.pem.base64
$ base64 -w0 cert.pem > cert.pem.base64
```

But this command did:

```
$ openssl base64 -in <infile> -out <outfile>
```

Source: https://superuser.com/questions/120796/how-to-encode-base64-via-command-line

Update to use openssh for all the key and cert generation examples?

**Comment by eleijonmarck** [comment]
We have a note for MacBook users but we can clearly make that more notable
