### ISSUE TITLE
[Feat]: Make alert notifiers more like pugins

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7162]
Want to make notifiers more like plugins so the code can be one one place and you dont have to update both backend and frontend parts. 

It works like this (in alerting/nofitiers/email.go in backend):

```go
func init() {
        alerting.RegisterNotifier(&alerting.NotifierPlugin{
Type: "email",
Name: "Email",
Description: "Sends notifications using Grafana server configured STMP settings",
Factory: NewEmailNotifier,
OptionsTemplate: `
<h3 class="page-heading">Email addresses</h3>
<div class="gf-form">
<textarea rows="7" class="gf-form-input width-25" required ng-model="ctrl.model.settings.addresses"></textarea>
</div>
<div class="gf-form">
<span>You can enter multiple email addresses using a ";" separator</span>
</div>
`,
        })
}
```

The notifications edit page gets the notifiers types and info & options template from a new api resource. So adding a new notifications is just adding a new go file, no need to modify any existing file (neither in backend or in frontend).

**Comment by bergquist** [comment]
Great!
