### ISSUE TITLE
[Bug] Template variable interval not working on v4.1.0-beta1

### ISSUE THREAD

**Issue by svetlina** [grafana/grafana#7163]
I am using influxdb datasource, grafana is installed on Ubuntu 14.04.5 LTS. I was using template variable interval. After update to current version, it is not working. When opening dashboard, default it is using 12h interval. After I choose something else, it becomes constantly 1d. It should take the value of the chosen input.

**Comment by torkelo** [comment]
Strange, I am unable to replicate this here. Can you show me your dashboard json, or template interval settings and how you use it?

**Comment by svetlina** [comment]
Yes, of course. I am setting the template from the web as shown in the attached screenshot.

![templating](https://cloud.githubusercontent.com/assets/9678348/21718972/b69c707a-d423-11e6-9aff-6725f48c5ee0.png)

After that I am using query that has GROUP BY time($interval) fill(0).

From the json file of the dashboard: 

"templating": {
    "list": [
      {
        "auto": false,
        "auto_count": 30,
        "auto_min": "10s",
        "current": {
          "text": "1h",
          "value": "1h"
        },
        "hide": 0,
        "label": "Time interval",
        "name": "interval",
        "options": [
          {
            "text": "1h",
            "value": "1h",
            "selected": true
          },
          {
            "text": "1d",
            "value": "1d",
            "selected": false
          },
          {
            "text": "1w",
            "value": "1w",
            "selected": false
          }
        ],
        "query": "1h, 1d, 1w",
        "refresh": 2,
        "type": "interval"
      }
    ]
  },


and the query 

"query": "SELECT count(\"totalTransactionAmount\")  FROM \"partnerBalanceTransfer\" WHERE $timeFilter AND transactionName = 'Renewal' AND totalTransactionAmount != 0 and type='Cash' GROUP BY time($interval) fill(0)".

I made screenshot of the query that is send to influx also
![query](https://cloud.githubusercontent.com/assets/9678348/21719043/32d24084-d424-11e6-8f08-a56012171857.png)

Can I help with any further information?

**Comment by torkelo** [comment]
you need to name it something else than $interval,  $interval is reserved variable used by the InfluxDB query editor

**Comment by tankywoo** [comment]
@torkelo Hi, I also happened this problem, which upgrade from 3.x to 4.1. In 3.x, I remembered the template `$interval` is the default template, and worked fine, but in 4.1, it doesn't work, and if I try to duplicate to another name, it works, as you said above, but when does `$interval` be reserved in InfluxDB?
