### ISSUE TITLE
Plugins CDN: Certain plugins fail to load with appSubUrl

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#71635]
Leaving this bug report here for the future.

Older angular plugins make use of `$scope.appSubUrl` or `$scope.$root.appSubUrl` to prepend paths prior to loading assets. When loading from a cdn this fails due to creating urls like `/grafanahttps://my-cdn.com/path/to/base/of/hosted/plugin/file.js`.

The hacky fix is to reset the properties prior to running `$compile`. e.g.

```typescript
if (componentInfo.baseUrl.startsWith(config.pluginsCDNBaseURL)) {
  scope.appSubUrl = '';
  scope.$root.appSubUrl = '';
}

$compile(child)(scope);
```

**Comment by sympatheticmoose** [comment]
closed given "I can't imagine we'll be running the CDN from a suburl in the next year"
