### ISSUE TITLE
question for a demo grafana

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#7164]
i wanna build a demo with grafana ,i wanna show  a real time data and i have no es  or influx as a db, is there any simple way to show the data  demo?
if is there a way to show the data with grafana only?

**Comment by torkelo** [comment]
you can enable the testdata app (under plugins), it adds some test data dashboards and data source

**Comment by tonyC2016** [comment]
can the testdata app  provides a change data ,and it seems like a real time data
@torkelo
