### ISSUE TITLE
[Feat]: Dashboard loading screen

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7165]
Show dashboard loading screen that shows progress initialing template variables. Template variable queries that take a long time can block dashboard loading which results in an blank page right now with no feedback on which template variable query that is pending.

**Comment by djmattyg007** [comment]
Grafana seems to lack any loading indicators at all. If you're on a slow or unresponsive network connection, such as mobile data, requests can time out and you'd have no idea that it even attempted anything in the first place, let alone that the request seemed to fail.
