### ISSUE TITLE
Incorrect client time causes graphing issues

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#7168]
When the clients time is incorrect then the generated graphs are incorrect.

For example if clients clock is two minutes behind real time then the first two minutes of the graph are simply missing e.g.
![image](https://cloud.githubusercontent.com/assets/104239/21720688/6daec0b8-d41c-11e6-8b9e-c419eac34420.png)
Correcting the client time fixes this e.g.
![image](https://cloud.githubusercontent.com/assets/104239/21720730/adb07a3a-d41c-11e6-8cff-41170fc0d535.png)

We're running Grafana version 4.0.2 against influx.

Looking at the generate requests I believe the issue is due to the graph dimensions being calculated by the client and the data being generated by the server so for example:
* Period is last 5mins
* Time is 13:00 
* Client time is 12:58
* Graph axis is 12:53 - 12:58
* Server data is 12:55 - 13:00

The result is that the first 2mins of the generated graph are missing and the last two minutes of the data returned from the server are not graphed.

If a timeshift is applied then the issue doesn't happen as instead of using server based relative times in the queries e.g. `time > now() - 5m` absolute times generated by the client are used e.g. `time >1483712692s`.

Potential fixes include:
1. Make use of the response `Date` header to determine server / client offset and adjust the graph time axis as needed.
2. Always graph between response ranges, which may have issues if incomplete results are returned.
3. Always use client calculated offset for influx queries.

#3 way well be the easiest fix.

**Comment by torkelo** [comment]
yes, local browser time must be in sync with server time since many queries are relative (now() - 1h) etc

**Comment by stevenh** [comment]
I appreciate having the client in sync is always the ideal solution however given this caused significant time lost investigating why data was missing here, I wouldn't be surprised if other users have this issue so it would be good to address it in one way or another.

Could we at least consider putting a warning if the client time is not in sync with the server?

**Comment by torkelo** [comment]
yes, should be a warning, used to be, will check why it's not showing
