### ISSUE TITLE
[Feature request] Table transform to both rows and columns 

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#7169]
Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxdb
- What OS are you running grafana on? windows

I'm trying to build a table from an influxdb query. The query groups by 2 tags (with say m and n unique values respectively). 

If I understand correctly, at the moment I can either display the data as columns or rows where there is a column/row for each combination of the two tag values (m x n values). 

It would be amazing if there could something like a pivot option where the user could choose to use some tags on rows and some tags on columns so that rather than a 1 X (m x n) table you could get an m X n table.

Hope this makes sense!

**Comment by torkelo** [comment]
could you describe how it would work?

So you would have 2 sets of time series and you want to plot series as rows and columns. Could you describe the config and how the rows & columns are generated & matched?

**Comment by robinsonjj** [comment]
Supposing I had a single field called value in an influxdb measurement with tags A and B. The set of values for tag A is {a1, a2, a3} and the set of values for tag B is {b1, b2}.

My query would be something like: `"select sum(value) from measurement where $time group by A, B"`

I would like to be able to say that I want to use tag A on rows and B on columns.  Grafana would look at the returned values to find the unique values of A and B, as above, and would therefore know that the resulting table should have 3 rows and 2 columns.

Grafana would then go back through each series and fill in the table according to the values of the A and B tags of each series.

**Comment by torkelo** [comment]
The `select sum(value) from measurement where $time group by A, B` query would result in 6 time series {a1-b1, a1-b2, a2-b1, b2-b2, a3-b1, a3-b2} ´, assuming the combination exist for all tags and the series alias is `$tag_A-$tag_B`

So the panel gets 6 time series with those names. How do you generate rows columns then? If you select Format as Table then you would get 

A   B value
a1 b1  10
a1 b2 14
a2 b1 10
a2 b2 14
a3 b1 10
a3 b2 10

This is easier for the table panel to work with and do something interesting with. You want to turn this into

```
     b1 b2
a1 10  20
a2 15  20
a3 20 30
```

am I understanding you correctly? Wonder what the configuration needed, maybe select 2 column names, and a value column. What if there are more columns, what do we do with them?

**Comment by robinsonjj** [comment]
Yes, that's exactly what I was trying to get at and I think the configuration you suggested makes sense. I think just supporting 2 column vales and a value column would be a great start, but if you wanted to support more columns then I guess it could look something like (A, C being the row tags and B being the column tags):

```
A   C   b1   b2
a1 c1 10    20
a1 c2 30    10
a1 c3 5      15
a1 c4 40    10
a2 c1 8      20
```

and so on

**Comment by sslupsky** [comment]
Hi.  This is a good idea.  We implemented a crude custom table panel where were added the ability to add rows and columns to the table.  I have attached a couple screen shots below.  It is cumbersome to set it up but when you do, you can generate a nice 2D visualization of the data.  We added a gradient to the 2D visualization so you could create something that looked like a heat map.  I included a screen shot of that as well.

I like the idea of using tags.  Would it also be possible to use a portion of the metric name?  We have adopted the recommended dot format for metrics names.  For example, "mote.ca.x1.y2".  We use a regex in the query to grab all the x and y values (ex:  /mote.ca.*/ ).  It would be very helpful if there was a way to pick off the "x" and "y" values from the metric name and use those for the row and column headers.


![screen shot 2017-01-27 at 11 36 56 am](https://cloud.githubusercontent.com/assets/16888734/22383002/43edf02c-e485-11e6-9335-2b0a2239db34.png)



![screen shot 2017-01-27 at 11 37 49 am](https://cloud.githubusercontent.com/assets/16888734/22382980/26ca141c-e485-11e6-9c52-713293460fa6.png)

**Comment by PeterWeiler** [comment]
The proposed style of table is exactly what I'm looking for to provide a Grafana-based dashboard for telegraf's ping plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping).  For my use case, rows would be the host tag and columns would be the url tag.  Metrics within the table would be the average latency or loss aggregated over the selected time period.  This style of table would also work nicely with the http_response and net_response plugins.

**Comment by sslupsky** [comment]
Hi Peter,

I have been working on a different approach.  I focused on the heat map aspect of what we did earlier and improved the method used to specify the coordinates.  Moreover, I transitioned away from a modification of the table plugin.  Here are a few screenshots.  My new approach doesn't use tags though.  I use a regex to filter the series names and extract the 2D coordinates from the series name.

I have attached some screen shots.  Let me know if this is useful to you.
![screen shot 2017-02-21 at 7 59 27 am](https://cloud.githubusercontent.com/assets/16888734/23170342/15f448fc-f80c-11e6-9ed3-8850b232e6e1.png)
![screen shot 2017-02-21 at 7 58 31 am](https://cloud.githubusercontent.com/assets/16888734/23170343/180037a0-f80c-11e6-8449-f72b2faf37c5.png)
![screen shot 2017-02-21 at 8 01 34 am](https://cloud.githubusercontent.com/assets/16888734/23170345/1abae774-f80c-11e6-9bbe-fb8ec6b6ed5f.png)

**Comment by JavierDelgadoFernandez** [comment]
As GitHub has already notified here, there is a PR that aims to provide this transformation (#8492). We would be very thankful if you can provide us some feedback there ;)

**Comment by sslupsky** [comment]
Hi @cubranic 

I have the heatmap code up in a Bitbucket repo.  I think it is public.  Could you please check and let me know?

https://bitbucket.org/scanimetrics/scanimetrics-heatmap-panel

The table panel mods do not work in grafana 4 which was the motivation to build the new heatmap panel.

**Comment by cubranic** [comment]
It's public, thanks!

**Comment by yellowpattern** [comment]
This looks like a really good improvement to the Table. Seems like Table doesn't get much love when compared to the graphs :(

**Comment by asieraguado** [comment]
We have a PR open for this feature (we have a long story trying to add this feature, since the PR #8492). We succeeded to implement this for InfluxDB, but it would be great is someone helps us with other data sources!

**Comment by yesoreyeram** [comment]
If I understood the problem correctly, this can be achived with [Boom Table Plugin](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel)

![Boom Table - Sample Panel](https://raw.githubusercontent.com/yesoreyeram/yesoreyeram-boomtable-panel/master/dist/src/img/panel.png)

**Comment by yellowpattern** [comment]
I suggest people checkout Boom Table:

https://grafana.com/plugins/yesoreyeram-boomtable-panel

**Comment by diegoscarabelli** [comment]
This suggested panel would be great to have!

**Comment by scroodj** [comment]
+1

**Comment by kazeborja** [comment]
Following the new transformers components I was able to structure the data into a "matrix" like object that can be visualised using the Grafana table plugin.

It doesn't depend on the datasource since it works directly in the data as structured by Grafana.

![after-matrix](https://user-images.githubusercontent.com/2511477/97863136-ccec9c80-1d06-11eb-85c5-7d7397f8666f.png)
![transformer](https://user-images.githubusercontent.com/2511477/97863141-cd853300-1d06-11eb-9fb4-7fe80da29047.png)
![beforematrix](https://user-images.githubusercontent.com/2511477/97863139-cd853300-1d06-11eb-865b-5a0b1d76fc73.png)

The PR may still require some expert eyes to make sure nothing is being missing.
