### ISSUE TITLE
Provide possiblity to download flamegraph in pprof format

### ISSUE THREAD

**Issue by simonswine** [grafana/grafana#71705]
Currently there is no way to display the source file information (like line numbers & source file).  The only way to gather those currently is by using the `SelectMergeProfile` https://github.com/grafana/phlare/blob/77b3af589da71d44621edcbab819b65b21aad83a/api/querier/v1/querier.proto#L14 api call which is also used by profilecli.

We should provide an "download pprof" button as part of the explore experience.

**Comment by cyriltovena** [comment]
See https://github.com/grafana/grafana/pull/61537 why it's not done already.

https://github.com/grafana/grafana/pull/61537#pullrequestreview-1261388294

**Comment by yongjichen** [comment]
Is there a plan to add this feature?

**Comment by 100vlx** [comment]
I also have such a need
