### ISSUE TITLE
Integer values displayed with floats

### ISSUE THREAD

**Issue by bh4rtp2023** [grafana/grafana#71703]
### What happened?

Many integer metrics are shown as floats after grafana started an hour or fresh the display frequently. I copy the metrics variable and query in prometheus graphs, it is ok. But in grafana, the query result is still a float.

### What did you expect to happen?

a integer value, i.e. 43, grafana shown value should be equal to prometheus.

### Did this work before?

Grafana is ok when just starts. I don't know why a float value is shown and queried.

### How do we reproduce it?

1. pull grafana:9.5.6 and prom/prometheus:v2.45.0
2. start a hyperledger fabric swarm
3. display `ledger_block_processing_time_count`
```
{
      "datasource": {
        "type": "prometheus",
        "uid": "P1520529137AF6314"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "max": 100,
          "min": 0,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "blue",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 5,
        "w": 6,
        "x": 0,
        "y": 13
      },
      "id": 18,
      "interval": "",
      "options": {
        "displayMode": "basic",
        "minVizHeight": 10,
        "minVizWidth": 0,
        "orientation": "horizontal",
        "reduceOptions": {
          "calcs": [
            "mean"
          ],
          "fields": "",
          "values": false
        },
        "showUnfilled": true
      },
      "pluginVersion": "9.5.6",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "P1520529137AF6314"
          },
          "expr": "ledger_block_processing_time_count",
          "interval": "",
          "legendFormat": "{{channel}}",
          "refId": "A"
        }
      ],
      "title": "ledger_block_processing_time_count",
      "type": "bargauge"
    }
```

### Environment (with versions)?

Grafana: 9.5.6
OS: SLES 12 SP2
Browser: Firefox

### Grafana platform?

Docker

**Comment by mellieA** [comment]
@bh4rtp2023 do you have a simplified use case for us to test this? Can you share a sample dashboard using the panel "get help" option to export with randomized sample data?

**Comment by bh4rtp2023** [comment]
Solved, I upgraded grafana and calculate method default to be Mean. Select Last* can solve this issue.


------------------ Original ------------------
From: Melori Arellano ***@***.***&gt;
Date: Wed,Jul 19,2023 9:30 AM
To: grafana/grafana ***@***.***&gt;
Cc: bh4rtp2023 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [grafana/grafana] Integer values displayed with floats (Issue#71703)





 
@bh4rtp2023 do you have a simplified use case for us to test this? Can you share a sample dashboard using the panel "get help" option to export with randomized sample data?
