### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by franklfdo** [grafana/grafana#7171]
Hello and good day
- What Grafana version are you using?
Grafana version 4.0.2

- What datasource are you using?
MYSQL

- What OS are you running grafana on?
Debian 8 jessie

- What did you do?
I download the package from https://packagecloud.io/grafana/stable, and I have the error:

After this operation, 124 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  grafana
Install these packages without verification? [y/N] N
E: Some packages could not be authenticated

- What was the expected result?
I want verificate the key, but nos funtion, give this error, 

- What happened instead?
I need verificate de key, because that the key on site, not function well, and I test with two keys:
with that : curl https://packagecloud.io/gpg.key | sudo apt-key add -
and 
curl -L https://packagecloud.io/grafana/stable/gpgkey | sudo apt-key add -

And any key not function, if you can help me???

Regards and good day Frank Luis

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
please read the install instructions:
http://docs.grafana.org/installation/debian/#apt-repository

```
curl https://packagecloud.io/gpg.key | sudo apt-key add -
```

did this return an error?

**Comment by franklfdo** [comment]
Yes, I test with this instructions, when I want install the package, this key not verificate, give me that warning:
WARNING: The following packages cannot be authenticated!
  grafana
Install these packages without verification? [y/N] N

And I dont know why, because, I use this direction on my script for install the grafana version:
This is my code:

apt-get install -y curl || {
	echo "Error install Curl"
	exit 3
}

curl -L https://packagecloud.io/grafana/stable/gpgkey | sudo apt-key add - || {
	echo "Error download apt-key"
	exit 4
}

I trie with the two keys and not function, the bouth give the same warning.

**Comment by torkelo** [comment]
and did the key install successfully?

**Comment by franklfdo** [comment]
Yes, the key install ok.
