### ISSUE TITLE
[Bug] Size of chart container changes magnitude data shown

### ISSUE THREAD

**Issue by braznaavtrav** [grafana/grafana#7173]
Grafana Version: 3.1.0
Datasource: InfluxDB
Host OS: Ubuntu 14.04.4 
Browser: Chrome 55.0.2883.95

When viewing the same chart embed with a hardcoded timestamp at different sizes, the magnitude of the data displayed changes.

![image](https://cloud.githubusercontent.com/assets/1715486/21735821/6ff5c6a0-d43a-11e6-90c2-dd6c41bda125.png)

![image](https://cloud.githubusercontent.com/assets/1715486/21735844/a4a5b3a6-d43a-11e6-81d8-48e9c6597372.png)

The url format of the embed is https://[our_grafana_server]/dashboard-solo/db/[dashboard_slug]?panelId=[panel_id]&fullscreen&theme=light&from=1483651782938&to=1483738182938

When viewing the chart in its grafana dashboard the same thing happens:

![image](https://cloud.githubusercontent.com/assets/1715486/21735995/8c198532-d43b-11e6-8a4e-ff193b744248.png)

![image](https://cloud.githubusercontent.com/assets/1715486/21736009/aaccb4cc-d43b-11e6-8ed9-eb6c3ee6f03f.png)
 

Let me know if there is any other information I can provide in order to help debug this.

**Comment by DanCech** [comment]
You'll need to provide the query, odds are very good you're summing data by interval and the width of the graph is changing the number of intervals (points) being requested from graphite.

**Comment by torkelo** [comment]
since your using influxdb, maybe your using Sum aggregation function? Then the number of data points for each pixel will be different depending on time range and hence the value

**Comment by braznaavtrav** [comment]
@torkelo @DanCech thanks for the quick feedback. The issue was that the `Group by time interval` option was blank in the chart definition. Filling this in fixed the issue.
