### ISSUE TITLE
Alerting: having more than one cloudwatch query results in no data

### ISSUE THREAD

**Issue by tstibbs** [grafana/grafana#71753]
### What happened?

When adding multiple cloudwatch queries in an alert rule, only the first query gets any results.

### What did you expect to happen?

All queries should be able to retrieve data.

### Did this work before?

Unknown.

### How do we reproduce it?

1. Deploy Grafana version 9.4.7 (I'm using the docker image `grafana/grafana-oss:9.4.7-ubuntu`)
1. Go to 'Alerting' / 'Create alert rule'
1. In the query that appears by default, select your cloud watch data source
1. Select the region
1. Select "CloudWatch Logs"
1. Choose some log groups
1. Select a time window that you know contains some logs for the selected groups
1. Enter the following query: `stats count()`
1. Press run queries
1. Select 'table' on the output view
**Note** you will now see a one column, one row table containing a count of the logs in that period, which is expected.
1. Press the 'duplicate query' button
1. Press 'run queries'

Result: only the first query returns any results. The second shows 'no data' even though it's clearly identical so should also have some results. (Note that it doesn't have to be identical to reproduce this bug

### Environment (with versions)?

Grafana: v9.4.7 (4add91f03d)
OS: Backend=Ubuntu 20.04.5 LTS, UI=MacOS 13.4.1
Browser: Chrome v114

### Grafana platform?

Docker

### Datasource(s)?

CloudWatch 5.0.0

### Impact

Prevents the creation of alerts which require more than one cloudwatch query element.

### Notes

Debugging the requests made by the browser shows that the queries are identical when sent to the backend.

Server debug log contains the following (noting that 'A' is the query that gets results, 'D' is the query that doesn't):
```
logger=expr datasourceType=cloudwatch queryRefId=D datasourceUid=<redacted> datasourceVersion=3 t=<redacted> level=warn msg="Can't find response by refID. Return nodata" responseRefIds=[A]
logger=expr datasourceType=cloudwatch queryRefId=D datasourceUid=<redacted> datasourceVersion=3 t=<redacted> level=debug msg="Data source queried" responseType=unknown
logger=expr datasourceType=cloudwatch queryRefId=A datasourceUid=<redacted> datasourceVersion=3 t=<redacted> level=debug msg="Data source queried" responseType="number set"
```

**Comment by kevinwcyu** [comment]
Hi, this was fixed in Grafana v9.5.1
