### ISSUE TITLE
Error Verification Key when enable repos Zabbix and Grafana at the same time

### ISSUE THREAD

**Issue by franklfdo** [grafana/grafana#7176]
Hello 

- What Grafana version are you using?
4.0.2
- What datasource are you using?
MYSQL
- What OS are you running grafana on?
Debian Jessie
- What did you do?
Install Grafana on server Zabbix 3.2.0
- What was the expected result?
When I have enable at the same time the Zabbix repo and Grafana, give me error
and when disable the Zabbix repo, then function well, I can install Grafana.

Error:
Length: 3889 (3.8K) [application/octet-stream]
Saving to: 'gpgkey'

gpgkey                            100%[==============================================================>]   3.80K  --.-KB/s   in 0s    

2017-01-06 19:15:13 (154 MB/s) - 'gpgkey' saved [3889/3889]
gpg: no valid OpenPGP data found.

This are the repos:

Zabbix Repo:
deb http://repo.zabbix.com/zabbix/3.2/debian jessie main
deb-src http://repo.zabbix.com/zabbix/3.2/debian jessie main

Grafana Repo:
deb https://packagecloud.io/grafana/stable/debian/ jessie main
deb-src https://packagecloud.io/grafana/stable/debian/ jessie main

- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
Try executing this:

```
curl https://packagecloud.io/gpg.key | sudo apt-key add -
```
