### ISSUE TITLE
Docs: Restore missing useful info to the build a streaming data source plugin

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#71766]
The tutorial for building a data streaming plugin is missing material that it used to be there, as noted in the webarchive version. See this Slack discussion:

https://raintank-corp.slack.com/archives/C024NL6AEJH/p1689593780877789?thread_ts=1689593413.234799&cid=C024NL6AEJH

Hugo writes: " all the item Add streaming capabilities from the archived tutorial is very useful and is missing in the current one."

**Comment by josmperez** [comment]
Related to https://github.com/grafana/grafana/issues/67566

**Comment by josmperez** [comment]
@oshirohugo - Can you confirm for me that the new streaming tutorial covers the topic that you felt was missing in the old tutorial? I think that is the case. If so, I'll close this issue out. If not, please make a suggestion for how we can add whatever material may be missing.

**Comment by oshirohugo** [comment]
I'm confirming that the new streaming tutorial covers the missing information.

Therefore I'm closing this issue in favor of https://github.com/grafana/plugin-tools/pull/629
