### ISSUE TITLE
[Bug] Grafana Timezone request response expectation mismatch

### ISSUE THREAD

**Issue by ambud** [grafana/grafana#7177]
Grafana sends request in UTC but interprets response in Local time. 

_I know that there was a lot of discussion about grafana's timezone support in the past but this behavior is plain-old painful as it's inconsistent. I have program my custom API to respond to local time only however I have no way of knowing the correct timezone offset to respond with in the current behavior._

Working on writing my own datasource for a custom TSDB.

Please include this information:
- What Grafana version are you using?
3.x.x (master branch)

- What datasource are you using?
Custom datasource (application)

- What OS are you running grafana on?
Ubuntu 16.10

- What did you do?
Grafana issues queries to through the sample data source code in UTC format. The server replies back in UTC but Grafana interprets that as local time. Dashboard->Settings->Timezone setting doesn't help with this. So data being returned doesn't render correctly unless I drop the UTC concept from my system all together.

- What was the expected result?
Grafana must interpret the results sent by server based on the either (UTC default) or the setting of the dashboard. 

- What happened instead?
Grafana doesn't display data because it's offset by the timezone offset.

Background:

I am working on my own TSDB and working on Grafana integration by writing a custom data source so Grafana can interact with my database. 

The Database runs a Dropwizard API that is programmed with an API compatible with Grafana's protocol.

I am using http://docs.grafana.org/plugins/datasources/ and the grafana-json-datasource example to build my custom datasource. There pretty much nothing changed in the example code except for a few API paths (minor change for health check api location)

**Comment by torkelo** [comment]
Grafana sends time range in UTC, and expects UTC epocs back. 

It then shows that time series data in either UTC or local time depending on you profile or dashboard time zone setting. This is working as expected for all other data sources so you must not be returning proper UTC epocs.

**Comment by ambud** [comment]
Thank you, I re-investigated issue on my end, seems like the clocks were offset by a bit.
