### ISSUE TITLE
SSE: Contain Errors so one error doesn't make everything error

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#71772]
Problem:

If any data source query or expression returns an error, all expressions and datasource queries will fail.

This is annoying when trying to write expressions, and also makes it less useful with dashboards as things become more fragile.

How to improve:
- For each "group", will only the fail the group. Where a "group" is a single graph as parsed by server side expressions. Or to put it another way - any stand alone expression or data source query. Or an expression and its dependencies.
- Fancier would be within a group, we walk the graph as far as we can until blocked by errors

I'm not quite sure how difficult this will be. I think the main things:
 - Make sure things don't execute if there inputs have errored, and return some sort of dependency error
 - Making this a return type. As I expect this will lead to a feature request of being able to replace errors with some sort of value.

**Comment by timlevett** [comment]
>If any data source query or expression returns an error, all expressions and datasource queries will fail.

Does this happen within a given panel, or across multiple panels for you?

**Comment by kylebrandt** [comment]
@timlevett All queries and expressions within an expression request to `api/ds/query` - which in my understanding maps to to per panel (unless the dashboard datasource is used).
