### ISSUE TITLE
[Feature request] Dynamic value above bar graph

### ISSUE THREAD

**Issue by wardboumans** [grafana/grafana#7178]
Please include this information:
- What Grafana version are you using? 
4.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Win

Request:

- I would like to see the value of the bar graph above the bar itself
- And to be able to specify an 'operation' that would be apply to this value. In my case multiply with a fixed value.

My usecase would be energy monitoring. The graph holds the KwH usage (per week/month) and multiplying it with my energy tariff I could see how much money I spend.

![example](https://cloud.githubusercontent.com/assets/9028898/21742219/3abc60ce-d4ea-11e6-8946-4b0dfb2f397b.png)

**Comment by alphabraga** [comment]
Was anything done?

**Comment by karol27** [comment]
I want it too. It seems very usefull

**Comment by MietekW** [comment]
This still doesn't seem to be possible?
I would really like this feature, also for my Gas usage, easier to read on mobile.
