### ISSUE TITLE
Alerts: Preview when creating alert shows "No Data" 

### ISSUE THREAD

**Issue by andrewbierbaum** [grafana/grafana#71795]
### What happened?

When creating a simple alert off of an elasticsearch datasource, the alert shows data on 9.5.3. After upgrading to 10.0.2, starting to create an alert shows "No Data" when attempting to preview data
<img width="1328" alt="Screenshot 2023-07-17 at 3 47 39 PM" src="https://github.com/grafana/grafana/assets/44590433/d63184c0-4b41-4a56-8e29-d1d8f96cbb0c">

### What did you expect to happen?

still be able to preview data on an elasticsearch alert

### Did this work before?

yes, 9.5.3

### How do we reproduce it?

1. make a simple Elasticsearch datasource dashboard
2. click on the alert tab of the graph
3. click preview on the new alert

### Environment (with versions)?

Grafana: 10.0.2
OS: ubuntu
Browser: safari

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch 7.17.10

**Comment by mellieA** [comment]
@andrewbierbaum can you share what the alert configuration looks like in the new "no data" alert?

**Comment by gabor** [comment]
i tried and could not reproduce it unfortunately, so waiting for the info requested in https://github.com/grafana/grafana/issues/71795#issuecomment-1641272204

**Comment by andrewbierbaum** [comment]
<img width="1624" alt="Screenshot 2023-07-19 at 9 46 19 AM" src="https://github.com/grafana/grafana/assets/44590433/ae69b446-1e0e-41bf-a429-231beac98037">
@mellieA @gabor Here is the same panel on the same dashboard after clicking to make an alert and clicking preview just upgraded 9.5.3 to 10.0.2. Preview doesn't load any data for the user to check their alert off of.

**Comment by konrad147** [comment]
@andrewbierbaum coud you check if the same happens in Explore?

**Comment by andrewbierbaum** [comment]
@konrad147 
<img width="1623" alt="Screenshot 2023-07-21 at 12 24 20 PM" src="https://github.com/grafana/grafana/assets/44590433/b6c7bc1f-4a7c-4dfe-b7d5-98014ba24379">
<img width="1619" alt="Screenshot 2023-07-21 at 12 24 40 PM" src="https://github.com/grafana/grafana/assets/44590433/5677e487-33f4-47e0-b45b-be299f8bc47e">
There is data looking at the panel, all I do is click the alert tab and then "create alert rule from this panel", then "preview", it returns "No Data

**Comment by gabor** [comment]
hi @andrewbierbaum thanks for the info. could you please try one more test?
it will not fix the problem, in fact, it will make things worse, but it will help us identify where the problem is (because currently we cannot reproduce it).

can you temporarily enable a feature-toggle on that instance?
could you enable the `enableElasticsearchBackendQuerying` feature-toggle, and try to run the query in dashboard or explore?

adding something like this to the grafana config should do the trick:
```
[feature_toggles]
enableElasticsearchBackendQuerying = true
```
this will tell grafana to run explore/dashboard queries the same way as it runs aleret queries.

my assumption is that now the query will fail everywhere, in dashboard/explore too, not just in alerting.

could you check this? does it fail the same way? does it perhaps show a better error message?

thanks!

**Comment by andrewbierbaum** [comment]
@gabor yes, when I enable that flag and reload grafana, the panel no longer shows any data. 
<img width="1611" alt="Screenshot 2023-07-24 at 10 34 24 AM" src="https://github.com/grafana/grafana/assets/44590433/f955d871-5d9f-415a-89cd-6c0e7f5f3d83">

I monitored the logs while reloading the panel, and it doesn't appear to by anything of interest in them that I could tell
```
Jul 24, 2023 @ 10:36:31.353 | 10.72.16.175 - - [24/Jul/2023:15:36:31 +0000] "GET /api/datasources/proxy/uid/000007639// HTTP/1.1" 200 341 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"
-- | --

  | Jul 24, 2023 @ 10:36:31.102 | 10.72.16.175 - - [24/Jul/2023:15:36:31 +0000] "POST /api/ds/query?ds_type=elasticsearch&requestId=Q100 HTTP/1.1" 200 33 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"

  | Jul 24, 2023 @ 10:36:30.838 | 10.72.16.175 - - [24/Jul/2023:15:36:30 +0000] "GET /api/ruler/grafana/api/v1/rules?subtype=cortex&dashboard_uid=c0bfba12-3250-4bef-bc7c-6df10065cffd&panel_id=1 HTTP/1.1" 200 2 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"

  | Jul 24, 2023 @ 10:36:30.834 | 10.72.16.175 - - [24/Jul/2023:15:36:30 +0000] "GET /api/prometheus/grafana/api/v1/rules?dashboard_uid=c0bfba12-3250-4bef-bc7c-6df10065cffd&panel_id=1 HTTP/1.1" 200 41 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"

  | Jul 24, 2023 @ 10:36:30.362 | 10.72.16.175 - - [24/Jul/2023:15:36:30 +0000] "GET /api/search?limit=5&dashboardUID=c0bfba12-3250-4bef-bc7c-6df10065cffd&dashboardUID=kube-services&dashboardUID=logs-observability&dashboardUID=rabbitmq-metrics&dashboardUID=mysqlnext-metrics HTTP/1.1" 200 1720 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"

  | Jul 24, 2023 @ 10:36:30.293 | 10.72.16.175 - - [24/Jul/2023:15:36:30 +0000] "GET /api/user/orgs HTTP/1.1" 200 47 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"

  | Jul 24, 2023 @ 10:36:30.235 | 10.72.16.175 - - [24/Jul/2023:15:36:30 +0000] "GET /avatar/3083c0c22b0b386c9a5c4ca7caa742f7 HTTP/1.1" 200 705 "https://grafana.integ.skytap.com/d/c0bfba12-3250-4bef-bc7c-6df10065cffd/testing-log-alerts?orgId=1&editPanel=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"
```

**Comment by gabor** [comment]
thanks for the info @andrewbierbaum,  it's great that you found that index-pattern-problem, i'll look into it why it does not work in alert-mode 👍 

(note:  technically we do not support cross-cluster-search yet (we have a github issue at https://github.com/grafana/grafana/issues/72353 for that), but i understand it should mostly work (i think select-boxes will not get populated with values and things like that))

**Comment by gabor** [comment]
@andrewbierbaum actually, i think this may have been fixed already in the newest release, could you try this in Gafana `10.0.3` ? 

(i think this was fixed in this pull request: https://github.com/grafana/grafana/pull/71284)

**Comment by andrewbierbaum** [comment]
yes, this fixes the issue I was having. Thanks!
