### ISSUE TITLE
Grafana 2.0: Prevent users from overwriting each others changes

### ISSUE THREAD

**Issue by feangulo** [grafana/grafana#718]
Most Grafana users keep their browsers open with a few dashboards for constant monitoring. Every once in awhile a user will make a change to a dashboard and save it.

1. Those changes that were saved will never be reflected on the other user's browsers unless the page is refreshed.
2. If another user modifies the same dashboard (without the previous user's changes having been refreshed) and then saves, the dashboard will lose some of the revisions.

We use Elasticsearch as our dashboard data source. Before trying to save any changes, or even making any changes, Grafana should check whether the current dashboard has a newer revision stored in Elasticsearch.

This way we avoid dashboard overwrites with older versions.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/6450828/ece74e2e-c12a-11e4-8e8c-32a8c591f8a7.png)

And the other case when you rename a dashboard or create a new with a title that already exists. 
![image](https://cloud.githubusercontent.com/assets/10999/6450833/01d2b602-c12b-11e4-8120-db8cd118e187.png)
