### ISSUE TITLE
failed to load application files after upgrade to 9.5

### ISSUE THREAD

**Issue by abhishek-nslhub** [grafana/grafana#71809]
### What happened?

As of Now we have deployed grafana in kubernetes and version is 9.3 but when we are trying to upgrade above 9.5 , then we are not to access grafana url , all the pods and everything is healthy but url is not accessible , says failed to load it's application files

![Screenshot 2023-05-02 154751](https://github.com/grafana/grafana/assets/127202496/2e97efe0-8d3a-40b5-b072-99a5534445e8)

### What did you expect to happen?

Url should be accessible

### Did this work before?

No

### How do we reproduce it?

1. You can produce by upgrading grafana over 9.3 , not sure

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by mvkrishna86** [comment]
The same behavior from 9.5 to 10.X. 
It works on some browsers and gives this error on some browsers.

**Comment by mellieA** [comment]
@mvkrishna86 this error has several potential causes, one of which is an unsupported browser

I'd also suggest checking out this old github issue where a number of users found that it was related to their cloudflare cache or an error in their config file. 

https://github.com/grafana/grafana/issues/65759

**Comment by abhishek-nslhub** [comment]
It worked Thanks alot

**Comment by paradox1573** [comment]
https://github.com/rancher/rancher/issues/24841
