### ISSUE TITLE
False Alert: No data Alert for all the alerts

### ISSUE THREAD

**Issue by mourya-satyam-888** [grafana/grafana#71815]
### What happened?

I am getting no data alert for all the alert rules irrespective of condition and metrics used in the alerts, I tried finding the logs didn't got anything usefull.

### What did you expect to happen?

No data alert must not being sent as there is present data

### Did this work before?

Kube Prometheus stack 35.0.0 I am using It was not that frequent before but now its too frequent

### How do we reproduce it?

No steps I have even data is there but getting false alert

### Environment (with versions)?

Kube Prometheus stack 35.0.0
Grafana version 8.4.6

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus
### useful logs:
`lvl=eror msg="error getting dashboard for alert annotation" dashboardUID=xyx alertRuleUID=xyx error="database is locked"`

how to fix its bug its getting data but due to database lock it should not give no value alert

**Comment by mellieA** [comment]
@mourya-satyam-888 have you resolved the locked database issue? 

You might check the alert configuration. The ["no data" handling is defined in the alert configuration](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#configure-no-data-and-error-handling).

If you suspect a bug, can you share the following and mask any sensitive data: 

- alert configuration 
- what does the alert preview show?
- what do you see in the alert state history?

**Comment by mourya-satyam-888** [comment]
@mellieA I am using default db for grafana and its locking around each 15s and I get in logs as db locked retries, but in when alert and locking time matches there is no retry mechanism in alert for db which in turn triggers the false alert.

So the main reason is locking of data how can I resolve this issue. I have almost 200 alert rules and the default alert rules are also 200

**Comment by alshain** [comment]
@mellieA We're experiencing the same issue since going from ~5 to 18 alerts. There's a single Grafana process accessing the built-in SQLite process and the different alerts now randomly go into an error state, and it's always 

    failed to build query 'A': [sqlstore.max-retries-reached] retry 1: database is locked

The errors resolve themselves but reappear sporadically every few minutes.
