### ISSUE TITLE
[Bug] No error message displayed when config file cannot be read due to permissions

### ISSUE THREAD

**Issue by lf-** [grafana/grafana#7182]
- What Grafana version are you using?

v4.0.2

- What datasource are you using?

InfluxDB

- What OS are you running grafana on?

Fedora

- What did you do?

I accidentally set broken permissions on the config that denied the grafana user access to read it.

- What was the expected result?

An error message was displayed giving pointers to why grafana wouldn't start.

- What happened instead?

It exited with the status 1 without logging anything.

**Comment by torkelo** [comment]
Cannot replicate this

I get this in grafana.log (and stdout), 
![image](https://cloud.githubusercontent.com/assets/10999/21748576/a8adc1b0-d588-11e6-9f54-1c5d901235fa.png)

**Comment by lf-** [comment]
That's incredibly strange. It was fixed by unbreaking the mode. The broken
mode used was 640 decimal.

**Comment by lf-** [comment]
@torkelo OK, the bug is not that it isn't logged at all, it's that it ends up in the log file and not the console even though both are configured as per defaults.
