### ISSUE TITLE
Login: Show oAuth error messages inline in form instead of in toasts

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#71835]
In https://github.com/grafana/grafana/pull/70266 we updated login errors to show above the login form, instead of temporary toasts. However errors from oAuth/SSO/etc come from [a different source](https://github.com/grafana/grafana/blob/37ef4e9/public/app/core/components/Login/LoginCtrl.tsx#L58-L60) ([backend](https://github.com/grafana/grafana/blob/37ef4e9/pkg/api/login.go/#L107-L116)) and are still shown in toasts, which are bad because they can disappear before the user reads them.

We should show oauth error messages inline just like regular login errors.

 - In LoginCtrl set `state.loginErrorMessage` based on `config.loginError`
 - Might help getting oauth running locally for dev https://github.com/grafana/grafana/tree/main/devenv/docker/blocks/auth/oauth

Ideally we would translate the error based on an error code, like we do for the other login errors, but at the moment the frontend does not get an error code for these. For oauth errors:

 - the backend [sets a cookie](https://github.com/grafana/grafana/blob/37ef4e9/pkg/api/login.go/#L399-L403) based on the [error _message_](https://github.com/grafana/grafana/blob/37ef4e9/pkg/api/login.go/#L439-L444)
 - Maybe we could put both the error code and message in the cookie, like a comma-delimited string?
 - Then the [backend](https://github.com/grafana/grafana/blob/37ef4e9/pkg/api/login.go/#L107-L116) would unpack this and set seperate properties on the frontend settings for error code + message. Thoughts... @sakjur ?

**Comment by sakjur** [comment]
I'm not sure the cookie is even needed, we could also pass the message in query parameters. I think the AuthNZ team might want to work on improving these things a bit. Regardless, the backend could definitely provide an error code using some kind of mechanism (especially since we know they're always three bytes long when represented as ASCII integers 🙂).

**Comment by Jguer** [comment]
Couldn't that be used for phishing attempts @sakjur? ex: `https://demo.grafana.net/login?message_id="auth.failed"&message="Unable to connect to your instance. Please send email with your login credentials to phishy@grafana.com"`. How you suggest solving that?

**Comment by joshhunt** [comment]
Right - I think it is important the backend still sends a fallback message to be shown if the frontend does not have a translation for it. See how we handle the password auth error api responses

https://github.com/grafana/grafana/blob/9b6c7b74c7d554e3ed682cf0341f147e7b3d72c5/public/app/core/components/Login/LoginCtrl.tsx#L167-L181

**Comment by Jguer** [comment]
there you're directly getting the message from the backend response if I'm not mistaken, making harder to falsify. 

Adding a nonce in cookie that the frontend can check could work, but I wonder if can be solved in a simpler way

**Comment by sakjur** [comment]
@Jguer Good point. I'd say something like HMAC.
