### ISSUE TITLE
[bug] Compilation on illumos: "term.go:41: undefined: terminal"

### ISSUE THREAD

**Issue by dewi-ny-je** [grafana/grafana#7183]
Compiling from source on illumos. go-1.7.1, NodeJS 6.7.0
sqlite3 is already installed.
GccGo is not available.

$ go get github.com/grafana/grafana
package github.com/grafana/grafana: no buildable Go source files in ~/src/go/src/github.com/grafana/grafana
$ cd $GOPATH/src/github.com/grafana/grafana
$ go run build.go setup
Version: 4.2.0-pre1, Linux Version: 4.2.0, Package Iteration: 1483919906pre1
go get -v github.com/kardianos/govendor
github.com/kardianos/govendor (download)
github.com/kardianos/govendor/vendor/github.com/Bowery/prompt
github.com/kardianos/govendor/prompt
github.com/kardianos/govendor/vendor/github.com/dchest/safefile
github.com/kardianos/govendor/internal/pathos
 # github.com/kardianos/govendor/vendor/github.com/Bowery/prompt
../../kardianos/govendor/vendor/github.com/Bowery/prompt/term.go:41: undefined: terminal
github.com/kardianos/govendor/internal/vos
github.com/kardianos/govendor/pkgspec
github.com/kardianos/govendor/vendorfile
github.com/kardianos/govendor/vendor/github.com/pkg/errors
github.com/kardianos/govendor/internal/vfilepath
github.com/kardianos/govendor/vcs
github.com/kardianos/govendor/vendor/golang.org/x/tools/go/vcs
github.com/kardianos/govendor/vendor/github.com/google/shlex
github.com/kardianos/govendor/context
github.com/kardianos/govendor/migrate
github.com/kardianos/govendor/help
exit status 2
exit status 1

I can provide additional info if needed.

**Comment by bergquist** [comment]
Skip the `go run build.go setup` step and try `go run build.go build`

**Comment by torkelo** [comment]
looks like govendor is not compiling on illumos

**Comment by dewi-ny-je** [comment]
@bergquist doesn't work either.
@torkelo I submitted the bug report to govendor, I didn't notice it was an external package.

**Comment by bergquist** [comment]
@dewi-ny-je what error do you get when running `go run build.go build` ?

**Comment by dewi-ny-je** [comment]
```
Version: 4.2.0-pre1, Linux Version: 4.2.0, Package Iteration: 1484173243pre1
rm -r dist
rm -r tmp
rm -r ~/src/go/pkg/solaris_amd64/github.com/grafana
rm -r ./bin/grafana-server
rm -r ./bin/grafana-server.md5
go version
go version go1.7.1 solaris/amd64
go build -ldflags -w -X main.version=4.2.0-pre1 -X main.commit=v4.1.0-beta1+61-g7c376f2 -X main.buildstamp=1483864997 -o ./bin/grafana-server ./pkg/cmd/grafana-server
vendor/github.com/inconshreveable/log15/root.go:6:2: no buildable Go source files in ~/src/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/term
exit status 1
exit status 1
```

Also, why is "Linux version" showing up? I'm under illumos kernel, OmniOS operating system:
`SunOS OmniOS-Xeon 5.11 omnios-bed3013 i86pc i386 i86pc`
