### ISSUE TITLE
Organizations: On switch the redirect URL is wrong

### ISSUE THREAD

**Issue by FStefanni** [grafana/grafana#71848]
### What happened?

Hi,

when I switch between two organizations, wrongly grafana adds the 3000 port to the url.
E.g:
```
https://myserver.com:3000/the_rest_of_the_url
```

Extra info:
* I use Traefik as reverse proxy in front of grafana
* I have set the following vars:
  * `domain = myserver.com`
  * `root_url = %(protocol)s://%(domain)s:%(http_port)s/mysubpath`
  * `serve_from_sub_path = true`
  * Grafana is exposed on its default port, internally, but the reverse proxy exposes grafana on standard https port 443
  * I have fond a discussion, but no bug report about this issue, so I have open this. Here the link: https://community.grafana.com/t/organizations-redirect/87313
  * As a workaround, I have changed the root url, by removing the port part, as suggested in the linked discussion: 
      * `root_url = %(protocol)s://%(domain)s/mysubpath`

Regards

### What did you expect to happen?

A correct redirect URL:

```
https://myserver.com/the_rest_of_the_url
```

Please note the missing port

### Did this work before?

It always worked, till 8.x.x.
I never used the 9.x.x series.
Today I installed the 10.0.2, and it does not work.

### How do we reproduce it?

1. Put Grafana behind a reverse proxy which uses port 443.
2. Create two or more organizations
3.Switch between them

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.0.2
OS: Docker on Linux VM
Browser: Firefox & Chrome

### Grafana platform?

Docker

**Comment by mellieA** [comment]
possibly related to https://github.com/grafana/grafana/issues/21400

**Comment by mildwonkey** [comment]
This also may be related to https://github.com/grafana/grafana/pull/66724 - the behavior (and documentation) changed in 10.0.  

I believe this is expected, and what was posted as the workaround is actually the correct configuration: if you don't want the port `:3000` in the URLs, don't include it in the `root_url`. 

There are other tickets that cover this topic, so I'm going to close this one and encourage anyone with this issue to comment on https://github.com/grafana/grafana/issues/72577, to consolidate this discussion.
