### ISSUE TITLE
Data sources: Data source dashboards page's nav is broken

### ISSUE THREAD

**Issue by mikkancso** [grafana/grafana#71843]
### What happened?

Under a data source's edit page, when I open the DatasourceDashboards page and reload it, the nav tree gets broken:
- the "Dashboards" tab is not visible anymore
- if I click on the (active) "Settings" tab, I get a page that is broken even more: no title, no content, the URL is broken.

This behaviour is very similar under Admin/Data sources and Connections/Data sources. The only additional bug under Connections is when I first click on the "Dashboards" tab, then the side nav gets hidden and the "Dashboards" tab does not get selected.

[Screencast from 2023-07-18 14-52-50.webm](https://github.com/grafana/grafana/assets/13637610/87fc3f84-1e59-4257-9998-ab526b8b0d97)

### What did you expect to happen?

The active tab should always be selected.
The side nav should not get hidden upon a click on a tab.
If I reload any of these pages, the nav tree should be correct.

### Did this work before?

I'm not aware of it working before

### How do we reproduce it?

1. Navigate to either Admin/Data sources or Connections/Data sources
2. Click on an already configured data source to open its Edit page
3. Click on the "Dashboards" tab
4. Refresh
5. Click on the "Settings" tab

### Environment (with versions)?

Grafana: main (as of 2023-07-18) Somewhere before 10.1.0
OS: Fedora 38
Browser: Firefox 115.0

### Grafana platform?

Other

**Comment by JoaoSilvaGrafana** [comment]
Hi @mikkancso ! Thanks for raising this, I have managed to reproduce it and will put it into our team's board to look into 👍
