### ISSUE TITLE
Prometheus: Autocomplete bug in code builder

### ISSUE THREAD

**Issue by LudoVio** [grafana/grafana#71846]
### What happened?

When you are in the query builder of a prometheus query with existing filters using regexp matching and start typing on a metric input, the autocomplete is broken.

The autocomplete query send all other filter as being literal matching, just = instead of =~

### What did you expect to happen?

The auto complete to work

### Did this work before?

Not sure. But it is here on main

### How do we reproduce it?

1. Create a prometheus query with at least one label filter that use a regexp matching (=~), and that make use of special regexp character so it doesnt match any real label value)
2. Type in the metric input
3.  See the autocomplete list is empty

### Is the bug inside a dashboard panel?

Yes, everywhere

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Prometheus

**Comment by bohandley** [comment]
Need to verify that this is related to lezer parser.

**Comment by itsmylife** [comment]
I cannot reproduce this. It seems it is working now.
