### ISSUE TITLE
[Bug] Graph showing Nan

### ISSUE THREAD

**Issue by usdin** [grafana/grafana#7186]
Grafana: v3.1.1
Datasource: InfluxDB
Os: Centos

Created graph for kafka metric. 
Lines are not drawn, and hovering shows Nan.Infinity and Nan. 
![screenshot from 2017-01-09 15-26-00](https://cloud.githubusercontent.com/assets/17239584/21763072/013d6282-d682-11e6-8a02-ed37c5842796.png)

Values returned by InfluxDB (in proxy mode) is attached in https://gist.github.com/usdin/1c3ddbf6450fcb298e1266442321be59

**Comment by usdin** [comment]
I've replicated same, by writing very small values in InfluxDB, using shell script.
```
while true; do
        curl -i -XPOST 'http://127.0.0.1:8086/write?db=test' --data-binary 'tm,h=a val=1e-307';
        curl -i -XPOST 'http://127.0.0.1:8086/write?db=test' --data-binary 'tm,h=b val=1e-309';
        sleep 10;
done
```

And Screenshot of query and graph.
![grafana-scr](https://cloud.githubusercontent.com/assets/17239584/21797236/e4e7e8de-d733-11e6-9791-cc90a8c6bb2f.png)

**Comment by usdin** [comment]
@torkelo Please have look here.

**Comment by daniellee** [comment]
Those values are smaller than what Grafana can handle at the moment.
