### ISSUE TITLE
Canvas SVG icons picklist not showing all icons

### ISSUE THREAD

**Issue by gamer22026** [grafana/grafana#71877]
### What happened?

Pick list for svg icons (in this case unicons) only displays a small subset of icons (from **0-plus.svg** down to **assistive-listening-systems.svg**. There are 1208 icons in the unicons directory but only the first 98 are shown. Also searching for icons that don't appear on the pick list returns nothing even though the icons exist in the unicons directory. Running in k8s but also tried 10.0.2 running locally via docker and observed same behavior.

### What did you expect to happen?

All svg icons in the unicons directory would be available to select.

### Did this work before?

Unknown, never tried canvas before 10.x

### How do we reproduce it?

1.Create canvas
2.Add icon from unicons folder
3. Observe only a small subset of icons is shown.

### Environment (with versions)?

Grafana: 10.0.2
OS: Ubuntu
Browser: All

### Grafana platform?

Kubernetes

**Comment by mellieA** [comment]
@gamer22026 thanks for reporting this. I'm seeing the same thing. I tried typing the name of a bundled .svg icons that isn't listed and it isn't found either. 

Screenshot of the last icon displayed in the UI pick list:  
![Screenshot 2023-07-19 at 5 01 59 PM](https://github.com/grafana/grafana/assets/18175287/60292e5e-2abd-4e69-b03e-88716960c2ca)

**Comment by drew08t** [comment]
This is being caused by pagination in the directory listing response. We need to look into a way to request the comprehensive list or handle pagination during scroll / search in the icon picker UI.

![Image](https://github.com/grafana/grafana/assets/60050885/bc3498cb-8094-43cc-a06d-886c3fee887d)
