### ISSUE TITLE
[Feature request] Url params input for links is way to small

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#7187]
Please include this information:
- What Grafana version are you using?
 Grafana v4.1.0-beta1 (commit: 6960fb4)
- What OS are you running grafana on?
via Docker

Entering somthing into the "Url params" input (e.g. for drill down links) is very difficult as the field's width is to small to be useful. My screen is big and there is enough white space on the right to use for this. Currently I can only see the name of one parameter, not even the value:

![image](https://cloud.githubusercontent.com/assets/648527/21764027/43c548d4-d661-11e6-9089-a969e181bc13.png)

**Comment by daniellee** [comment]
Closing this feature request as this has been totally been re-implemented since you submitted this feature request. Hopefully it works better now.
