### ISSUE TITLE
Storybook: SegmentAsync story looks poorly

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#71875]
Perhaps with the font change to Inter, but the SegmentAsync stories currently looks pretty bad. The label wraps, and the control itself is so narrow. When you click the button to create a new entry, the text box is only wide enough for one letter

![Image](https://user-images.githubusercontent.com/46142/253605357-cc4ae20e-d19a-4b05-83bc-0d52c9dc2978.png)

https://developers.grafana.com/ui/latest/index.html?path=/story/data-source-segment-segmentasync--array-options

**Comment by ssama88** [comment]
@JoaoSilvaGrafana  I'm new to Grafana and would like to contribute if still open

**Comment by JoaoSilvaGrafana** [comment]
Hey @ssama88 ! Thanks for volunteering to contribute 😄  the issue is still open yes so I will assign it to you!

**Comment by ssama88** [comment]
Is this issue relating to just the appearance in the storybook or the components themselves?

**Comment by JoaoSilvaGrafana** [comment]
The issue itself is just about the story, to make it look more visually pleasing instead of everything squished like it is

**Comment by ssama88** [comment]
@JoaoSilvaGrafana should the target branch be main?

**Comment by JoaoSilvaGrafana** [comment]
@ssama88 Yep it should be main! Thanks for the contribution 🎉
