### ISSUE TITLE
GrafanaUI: FileDropzone does not register full area as a drop target

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#71880]
When dropping a file onto the FileDropzone, it only registers as a file being dragged over (or dropped on) when dropping on the very center of the control, rather than the full area.

Reproducable in Grafana:

 - Go to Dashboard Import /dashboard/import
 - Drag a file to the right side of the drop area 

![Image](https://user-images.githubusercontent.com/46142/253611611-86b2b9f4-fd68-4e34-8d28-df51807d1ffb.png)

Expected:
 - control should highlight if a file is dragging over any of the box

Actual:
 - control only highlights when dragged over the very centre of the element

**Comment by kunxl-gg** [comment]
can I work on this issue

**Comment by JoaoSilvaGrafana** [comment]
@kunxl-gg Yes feel free to pick it up! I have assigned it to you

**Comment by kunxl-gg** [comment]
Why is this stuck after yarn start. I was following the docs for local setup 
<img width="1440" alt="Screenshot 2023-07-20 at 11 07 57 PM" src="https://github.com/grafana/grafana/assets/105335204/eab2c6f6-9ee9-48e4-82c1-e2826c6d5e88">

**Comment by JoaoSilvaGrafana** [comment]
Hi @kunxl-gg , I am not sure why it is so slow for you... For this specific issue you could try to do it with storybook only. If you run `yarn install` and `yarn storybook` is that stuck too?

**Comment by kunxl-gg** [comment]
https://github.com/grafana/grafana/issues/46977
lololol

**Comment by kunxl-gg** [comment]
> Hi @kunxl-gg , I am not sure why it is so slow for you... For this specific issue you could try to do it with storybook only. If you run `yarn install` and `yarn storybook` is that stuck too?

I resolved the error. Will make a PR shortly
