### ISSUE TITLE
Conditional image/text panel based on metrics

### ISSUE THREAD

**Issue by pkkummermo** [grafana/grafana#719]
Hi, and thanks for great metrics dashboard!

This is a feature request to show a set of different images or text based on metrics. Here's our situation:

Several servers with different services connected to them, all reporting metrics in terms of load, requests etc. What we would like is a way to display different statuses (all good, something fishy, all developers on deck) on these servers based on different criterias based in metrics reported from them. 

You think it could be possible to add a type of panel ("status"-panel mayhaps?) which has a set of metrics which in terms gives a status? The status can again be connected to an image or text to display. It would give us a great overview of our systems and if something looks out of place by just glancing at the dashboard. :) 

Again, thanks for an awesome dashboard. Greatly appreciated.

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/1999
