### ISSUE TITLE
The mapped field setting color in the table plugin is not displayed

### ISSUE THREAD

**Issue by lushuan** [grafana/grafana#71902]
### What happened?

version: v9.2.6

- set color red but not appear
- database is mysql
![329df4f62a2c518652885ce061b8b8e](https://github.com/grafana/grafana/assets/20624169/8e269cda-4966-40c2-a694-750deee2ce94)

### What did you expect to happen?

set color red will appear
![image](https://github.com/grafana/grafana/assets/20624169/53a6e5b7-73d0-41a4-8a64-549ce9b8e1af)

### Did this work before?

new version appear

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 9.2.6
OS:  CentOS Linux Version 7
Browser: chrome 103.0.5060.114 

### Grafana platform?

Docker

### Datasource(s)?

MySQL 5.7.38-log

**Comment by mellieA** [comment]
@lushuan is the color working as expected for you with the "value" based value mapping?

**Comment by codeincarnate** [comment]
I just tested this out, and it indeed appears to be not working.  From a cursory glance it appears that this may not have been implemented for the table panel. We'll add this to the roadmap and see what we can find out.
