### ISSUE TITLE
Embedding Grafana with Iframe causes lagging (Memory Leak?)

### ISSUE THREAD

**Issue by ZTjack** [grafana/grafana#71901]
### What happened?

I embedded the system via an iframe, but when I reused the site the next day I noticed severe lag. I used the Memory tool inside Chrome's Devtools to take a snapshot of memory every so often, and I found that memory was slowly rising

![image](https://github.com/grafana/grafana/assets/20082885/c8ea912d-46f8-405a-b91d-d00eaefd0ff8)

But when I open a grafana page alone I find that the lag is much better

### What did you expect to happen?

If there are some strategies not work in iframe? I expect it runs smoothly also in an iframe.

### Did this work before?

It's not fit for this problem

### How do we reproduce it?

1. open two pages, one open a grafana directly, another make grafana in a iframe
2. Detect their memory usage

### Environment (with versions)?

Grafana: 9.2.15
OS: MacOS
Browser: Chrome

### Grafana platform?

None

**Comment by mellieA** [comment]
I'm not sure which squad could best address this one, so please help me re-route it. I've added to backend platform and frontend platform projects to start 😄

**Comment by ZTjack** [comment]
I believe this issue is more on the front-end platform side. The main problem to solve is that when the same Grafana link is opened separately and embedded in an iframe, after a long time, the Grafana embedded in the iframe becomes significantly more sluggish. I suspect my own website has a memory leak, but I verified it with Chrome's Memory tool and the new detached content points to Grafana's js (by the way, the output of the Memory tool is C++ code which is quite unreadable). So I'm raising this issue here first, hoping you can also help take a look. I will do more testing and try to find the root cause myself in the near future.

**Comment by L-M-K-B** [comment]
This issue may be related to another open issue (https://github.com/grafana/grafana/issues/56316). After consulting with @axelavargas I'm going to add it to the board of @grafana/dashboards-squad and they will discuss further.

**Comment by dprokop** [comment]
Closing this one in favor of #56316. Linking for reference.

In the meantime @ZTjack - can you please provide more details about your dashboard that caused the issue? Ideally the dashboard JSON.
