### ISSUE TITLE
Can't enable Server Admin when skip_org_role_sync = true in Azure AD oauth

### ISSUE THREAD

**Issue by gavinwoolley** [grafana/grafana#71919]
### What happened?

When we upgrade to Grafana 9.4 > the Azure AD Auth component can no longer map the server admin role to a user.
In all previous versions, we can map the server admin role using `allow_assign_grafana_admin: true`
whilst also having either `oauth_skip_org_role_update_sync: true` or `skip_org_role_sync: true`

This enables us to make our admin team, Server Admins with default org Viewer role. 
They can grant themselves org level permissions manually or automated, because they have server admin role. 

But now when `skip_org_role_sync: true` is set. 
We are no longer ServerAdmins and just a Viewer in the default org. 
If we set server admin via UI, and logout and back in again, it gets removed from us.

To allow us to have server admin, we have to set `skip_org_role_sync: false` but this in turn resets the org level permissions for everyone.

We would like to be able to have server admin rights as before.

It looks like this commit is what caused the issue by wrapping the `grafanaAdmin` role in an `if` statement based on `skipOrgRoleSync` https://github.com/grafana/grafana/commit/c5e74ee607ebd07f27dbe10444a296be94be2485#diff-1932ec0f0e9483143b8e2d48df6f864540ae8a15a938d40011e5ca2712391077

Since Grafana Admin is not an Org role, but a Server role. I dont think this `if` should be here

### What did you expect to happen?

I expect to have Server Admin (Grafana Admin) role even when `skip org role sync` is set to `true`. 
Because Grafana Admin is not an org role.

### Did this work before?

All versions prior to 9.4 this worked

### How do we reproduce it?

1.Setup Grafana 9.2.5 with azure AD auth and `[auth.azuread]` `allow_assign_grafana_admin: true` and `[auth]` `oauth_skip_org_role_update_sync: true` you will have server admin, but no org role sync
2.upgrade to 9.4 > you will lose server admin and have no role sync

### Environment (with versions)?

Grafana: 9.4
OS: container
Browser: chrome or firefox

### Grafana platform?

Kubernetes

**Comment by gavinwoolley** [comment]
It looks like the other oauth packages also do the same, but throw a better error when these two conditions are `true` 
https://github.com/grafana/grafana/blob/3a50d7ea84ee355e153fc938aafcec08718126b5/pkg/login/social/gitlab_oauth.go#L141C1-L143C3
```
if s.allowAssignGrafanaAdmin && s.skipOrgRoleSync {
		s.log.Debug("allowAssignGrafanaAdmin and skipOrgRoleSync are both set, Grafana Admin role will not be synced, consider setting one or the other")
	}

I still believe this is not correct, since `GrafanaAdmin` is a Server Role - not org role

**Comment by Jguer** [comment]
Hi Gavin, we've determined server admin to be an hierarchical role above Org Admin. 

Being ServerAdmin is the equivalent of Org Admin, as a ServerAdmin can elevate themselves to Org Admin in any organization. We want to highlight this by linking the two definitions and as such skipping role syncing to Admin reduces the visibility for other org admins that Server Admins also have access to it.  

Thanks for pointing out the missing reference in the documentation and lack of warning in the azure AD provider. We will fix those.
