### ISSUE TITLE
Docs: Plugins tutorials improvements

### ISSUE THREAD

**Issue by oshirohugo** [grafana/grafana#71920]
## Tutorials don't mention docker compose
All the tutorials in:
https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/
don't mention docker compose as an way to run grafana with the plugin in development.
We have the `server` script when we create our plugin with `@grafana/create-plugin` that uses docker compose that can be used.

It worth to notice that the `server` script assumes we have `docker-compose` standalone instead of the current [standard syntax](https://docs.docker.com/compose/install/standalone/#on-linux) `docker compose`.

The `server` script is mentioned in the in progress Docusaurus docs:
https://grafana.github.io/plugin-tools/docs/docker

## Docs recommend a mix of `npm` and `yarn`
All the docs from:
https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/
creates plugins using `npx @grafana/create-plugin@latest`.

The created `package.json` has `"packageManager": "npm@<version>"`. But following the tutorial it recommends you to use `yarn` to install dependencies and run scripts.

Doing it out of the box gives us the error:
```sh
	Usage Error: This project is configured to use npm

	$ yarn ...
```
The new [docs](https://grafana.github.io/plugin-tools/docs/creating-a-plugin?current-package-manager=yarn) have an specific usage of `yarn` to create a plugin:
```sh
yarn create @grafana/plugin
```
But trying it with `yarn@3.6.0` gives us a dependency error:
```sh
/tmp/xfs-1a979e21/dlx-41965/.pnp.cjs:11947
      Error.captureStackTrace(firstError);
            ^

Error: @grafana/create-plugin tried to access minimist, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: minimist
...
```
The easiest way of using `yarn` so far is to remove `"packageManager": "npm@<version>"` from `package.json`.

## Incompatible (outdated) code
The code from this [tutorial](https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/build-a-panel-plugin/#use-the-new-option) is not compatible with the code created by `@grafana/create-plugin`. `theme.palette` is not available though `useTheme2` only thought `useTheme` which is deprecated.

The text from [data source backend tutorial](https://grafana.com/docs/grafana/latest/developers/plugins/create-a-grafana-plugin/develop-a-plugin/build-a-data-source-backend-plugin/) are also outdated compared to the current state of the template generated by `@grafana/create-plugin`. It references a file (`/pkg/plugin/plugin.go`) and a structure (`SampleDataSource`) that don't exist

**Comment by sympatheticmoose** [comment]
Possible additional issue https://github.com/grafana/plugin-tools/discussions/131#discussioncomment-5099307

**Comment by GrafanaWriter** [comment]
@zuchka - can you take a look? We don’t have a dedicated writer for this area.

@Eve832 - FYI

**Comment by sympatheticmoose** [comment]
> @zuchka - can you take a look? We don’t have a dedicated writer for this area.
> 
> @Eve832 - FYI

@GrafanaWriter - these are plugin tutorials and we'll be moving them to the dev portal with the help of @josmperez

**Comment by zuchka** [comment]
hey all, LMK if you want me to jump in here. :)

**Comment by josmperez** [comment]
@oshirohugo - I've assigned this one to myself and will be coordinating corrections/improvements to the tutorial.

@zuchka - Thanks for the offer, I'll loop you in.

**Comment by josmperez** [comment]
@oshirohugo - Do you have bandwidth to work with me on this issue?

**Comment by sympatheticmoose** [comment]
This has all been resolved
