### ISSUE TITLE
[bug] bar graph - lowest values are not visible

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#7193]
Please include this information:
- What Grafana version are you using? - both 3.1.1 and 4.0.1
- What datasource are you using? - elasticsearch
- What OS are you running grafana on? - Debian jessie
- What did you do? - bar graph
- What was the expected result? - to see all values :-)
- What happened instead? - lowest value is not visible although is present see bellow

Problem was already discussed on Stackoverflow (http://stackoverflow.com/questions/39892936/grafana-bar-graph-sorting-lower-values-not-visible) but in our case we cannot use stacked graph.

When points are activated it is clear lowest value is there. And when I hower over bars lowest value is shown in different colour. Looks like problem is just in order in which bars for values are displayed.

**Comment by torkelo** [comment]
for bar charts you need to enable stack if you want to see them all otherwise the will draw over each other

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/870

**Comment by machytkafitanalytics** [comment]
stacked bars are in this case confusing, it would we enough to just display bars in DESC order...
