### ISSUE TITLE
Datasources: dataproxy.timeout seems to be ingored

### ISSUE THREAD

**Issue by andrewmitchell-21** [grafana/grafana#71946]
### What happened?

When querying the Amazon Athena datasource via the explore tab within Grafana, queries seem to timeout at 60 seconds regardless of what is set in `dataproxy.timeout`

### What did you expect to happen?

Queries don't timeout until the timeout threshold has been met, in my case 600 was set. 

### Did this work before?

Not noticed issues before so hard to say

### How do we reproduce it?

1. Add Amazon Athen Datasource to Grafana
2. Query the datasource using the explore tab and execute long running query against Athena, i.e. >60s
3. Observe error output from the query inspector 

My query takes 6 minutes to complete via the Athena UI in AWS

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:10.0.2 (commit: b2bbe10fbc, branch: HEAD)
OS:Ubuntu 20.04.6 LTS
Browser: Chrome Version 114.0.5735.198 

### Grafana platform?

A downloaded binary

### Datasource(s)?

Amazon Athena 
```[tasklist]
### Tasks
```

**Comment by mellieA** [comment]
@andrewmitchell-21 there's a similar conversation in https://github.com/grafana/athena-datasource/issues/99 

That issue was closed with this comment: 

> To solve this, timeout needs to be increased in AMG.

**Comment by dcram** [comment]
We are also experiencing very slow Athena dashboard loading, every morning on the first loading.

After 5-10 minutes of manual reloads and several `504 Gateway Timeout` errors, we finally get all our dashboards working fine for the rest of the day.

**Comment by katebrenner** [comment]
@dcram because this issue is closed, your issue is being tracked here https://github.com/grafana/athena-datasource/issues/319
