### ISSUE TITLE
[Bug] LDAPS - Error authenticating to Active Directory with Grafana ONLY when using TLS

### ISSUE THREAD

**Issue by bfgoodrich** [grafana/grafana#7194]
**AUTHENTICATION WORKS WITHOUT TLS/SSL**

*only* change to configuration is:

change to enable ssl: "use_ssl=true" 
change to the TCP port: "port = 636"

Please include this information:
- What Grafana version are you using?
   grafana-4.0.1
- What datasource are you using?
   grafana-zabbix
- What OS are you running grafana on?
   Red Hat Enterprise Linux Server release 7.3 (Maipo)
- What did you do?
   setup LDAP for LDAPS to Active Directory
- What was the expected result?
   I can authenticate with Active Directory users/groups
- What happened instead?
   Error Message:

```
t=2017-01-09T08:47:22-0700 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 200 \"\": read tcp 172.x.x.x:57824->172.x.x.x:636: read: connection reset by peer"
t=2017-01-09T08:47:22-0700 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=172.x.x.x time_ms=102ns size=77
```

LDAP Configuration:

(grafana.ini)
```
#################################### Auth LDAP ##########################
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
```
(/etc/grafana/ldap.toml)

```
# Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "host.organization.com"

# Default port is 389 or 636 if use_ssl = true
#port = 389
port = 636

# Set to true if ldap server supports TLS
#use_ssl = true
use_ssl = true

# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false

# set to true if you want to skip ssl cert validation
ssl_skip_verify = true

# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = /path/to/certificate.crt
root_ca_cert = "/etc/pki/tls/root.pem"

# Search user bind dn
bind_dn = "CN=svc_account,OU=Accounts,DC=organization,DC=com"

# Search user bind password
bind_password = "<password>"

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(sAMAccountName=%s)"

# An array of base dns to search through
search_base_dns = ["DC=organization,DC=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
```

**Comment by bfgoodrich** [comment]
Also, I can connect using LDAPS test connection using the certificate in question and JXplorer on Mac OS X and I can test the certificate with OpenSSL using the same root CA - the result with OpenSSL is "Verify return code: 0 (ok)" (openssl s_client -connect host.organization.com:636 -CAfile /etc/pki/tls/root.pem)

**Comment by bfgoodrich** [comment]
I thought I could work around this by using start_tls on the default port, apparently start_tls is being ignored by Grafana. The user authentication was sent over the wire in clear text to the Active Directory server. I will open up a separate bug regarding the issue with start_tls.

**Comment by utkarshcmu** [comment]
If there is a bug its in this function - https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go#L48

**Comment by marefr** [comment]
@bfgoodrich does changing port to 3269 work for you? See comment [here](https://github.com/grafana/grafana/issues/10040#issue-278128207) for details.

**Comment by jessabe** [comment]
Going to close this issue as there's been no response in over 2 years. If you're still having this issue please comment and we can re-open it. Thank you!
