### ISSUE TITLE
[Bug]: No data source details in Error - [dataproxy.go:78 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found

### ISSUE THREAD

**Issue by jayannah** [grafana/grafana#7196]
Grafana v0.3.0.4

We do see lots of these errors in grafana logs /var/log/grafana/grafana.log file

2017/01/09 13:23:59 [dataproxy.go:78 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found

But there is no information on which data source is not found? We have many data source created in Grafana for InfluxDB databases. 
How do understand which data source is not found and identify the rootcause here?

I do see many people have posted question why these logs are coming and there is no proper rootcause or solution explained.

please let me know if any information required.

**Comment by torkelo** [comment]
Are you using multiple organizations and have grafana open with same user but different organizations? 

Yes this has been reported before but only way to replicate is to have multiple tabs or browsers logged in as same user, then switch active organization
