### ISSUE TITLE
Pyroscope datasource: Deep flame graphs fail to render

### ISSUE THREAD

**Issue by oehme** [grafana/grafana#71960]
### What happened?

When I tried to visualize a CPU flame graphs with deep stack traces, the flame graph view breaks:

![broken](https://github.com/grafana/grafana/assets/1191797/985745eb-455d-4fb0-9436-bfde1c8c00ef)

### What did you expect to happen?

The flame graph should render correctly.

### Did this work before?

The same flame graph renders fine in the UI of the Pyroscope server.

![working](https://github.com/grafana/grafana/assets/1191797/0f072d3d-a517-43f4-bdbb-10eb4919a767)

### How do we reproduce it?

Here's a simple main class that reproduces the issue. 

```
package org.example;

import java.math.BigInteger;

import io.pyroscope.http.Format;
import io.pyroscope.javaagent.EventType;
import io.pyroscope.javaagent.PyroscopeAgent;
import io.pyroscope.javaagent.config.Config;

public class Main {
    public static void main(String[] args) {
        PyroscopeAgent.start(
                new Config.Builder()
                        .setApplicationName("factorial")
                        .setProfilingEvent(EventType.ITIMER)
                        .setFormat(Format.JFR)
                        .setServerAddress("http://localhost:4040")
                        .build()
        );
        while(true) {
            System.out.println(fac(BigInteger.valueOf(1000)));
        }
    }

    public static BigInteger fac(BigInteger n) {
        if (n.equals(BigInteger.ZERO)) {
            return BigInteger.ONE;
        }
        return n.multiply(fac(n.subtract(BigInteger.ONE)));
    }
}
``` 

### Environment (with versions)?

Grafana v10.0.2 
Pyroscope: v0.37.2
Browser: Chrome 114.0.5735.198 

### Grafana platform?

Docker

### Datasource(s)?

Pyroscope

**Comment by aocenas** [comment]
So far no luck with consistently reproducing this. Tried to do something similar (with js app) and at some point reaching >1000 nodes of nesting both grafana and pyroscope flamegraph started glitching in this way. Coming back to it later it seems like it works fine.


https://github.com/grafana/grafana/assets/1014802/01271811-ac7d-413b-90af-ae58760ceb43

**Comment by aocenas** [comment]
Ah just noticed this was on 10.0.2 and I tested on current 10.1 beta. We did some changes and some optimizations so it seems like that may have helped. Can you try it to see if you case renders with 10.1 beta? Obviously there will be some limits still, but together with the `Max Nodes` in the query editor options this could be manageable.
