### ISSUE TITLE
Pyroscope datasource: Recursive stack traces break duration calculation

### ISSUE THREAD

**Issue by oehme** [grafana/grafana#71962]
### What happened?

In an application with deep stacktraces, the "total time" of the deeply nested function is larger than the "total" profiled application time.

![wrong-total](https://github.com/grafana/grafana/assets/1191797/26c18ca4-c6ff-4ff1-8f8d-f8b767d2a18b)

### What did you expect to happen?

The numbers for `fac` and `toString` should be smaller than the `total`. It looks like the code is just adding up all the numbers for recursive calls

### Did this work before?

No, the same bug appears in the UI of the Pyroscope server:

![wrong-total-pyroscope](https://github.com/grafana/grafana/assets/1191797/b6e3ba47-57f5-4522-aa9c-f5c3da99d691)

### How do we reproduce it?

Here's a main class that triggers this issue:

```
package org.example;

import java.math.BigInteger;

import io.pyroscope.http.Format;
import io.pyroscope.javaagent.EventType;
import io.pyroscope.javaagent.PyroscopeAgent;
import io.pyroscope.javaagent.config.Config;

public class Main {
    public static void main(String[] args) {
        PyroscopeAgent.start(
                new Config.Builder()
                        .setApplicationName("factorial")
                        .setProfilingEvent(EventType.ITIMER)
                        .setFormat(Format.JFR)
                        .setServerAddress("http://localhost:4040")
                        .build()
        );
        while(true) {
            System.out.println(fac(BigInteger.valueOf(1000)));
        }
    }

    public static BigInteger fac(BigInteger n) {
        if (n.equals(BigInteger.ZERO)) {
            return BigInteger.ONE;
        }
        return n.multiply(fac(n.subtract(BigInteger.ONE)));
    }
}
``` 

### Environment (with versions)?

Grafana v10.0.2
Pyroscope: v0.37.2
Browser: Chrome 114.0.5735.198

### Grafana platform?

Docker

### Datasource(s)?

Pyroscope

**Comment by aocenas** [comment]
So I don't think I would classify this as a bug. Or maybe a better explanation is I don't know what would be non-bugy behavior if this was a bug.

In the table we group symbols by their name so for each name you have only one row even if they are multiple times in different places in the profile. We just sum up the values of total and self metric. So yeah all the totals can add up to more than the overall total of the root (or width of the flame graph) which I think is sort of expected. With recursive function, this behavior can be much more apparent but it is the same as for any other symbol.

In general sorting by self in the table probably makes much more sense for most usecases and for it, the summed value makes also intuitive sense. We could not show the total value of symbols in the table but I feel like this isn't such a big issue to change what we show right now. Alternatively, we may change what "total" symbol means, right now it's just an artificial root node, we can do whatever with that but not sure what change would make this all clearer.

**Comment by oehme** [comment]
>So yeah all the totals can add up to more than the overall total of the root (or width of the flame graph) which I think is sort of expected

If the program has a total of 13s of CPU time, it is impossible for a function to have a total time of 42min. It can at most be 13s.

My guess is that Grafana is counting every occurrence of a symbol, even within a single stack trace. To get the correct total time, it should only count the first occurrence in each stack trace and then sum up those first occurrences. In pseudo Java:

```
val totalTimeBySymbol = Map<String, Int>
for (trace: traces) {
    val localTimeBySymbol = Map<String, Int>
    for (symbol: trace.symbols) {
         //only counting the first, not every occurrence in a single trace
         localTimeBySymbol.putIfAbsent(symbol, trace.count)
    }
    totalTimeBySymbol.merge(localTimeBySymbol, ::add)
}
```

You can also see this working correctly in this [async-profiler flame graph](https://github.com/grafana/grafana/files/12195628/async-profiler-flames.html.zip). You can use the search bar to search for any symbol and it will give you the correct percentage of the total time. It correctly says `fac` accounted for 55% of the total time (~7s), not the 42min that Grafana claims.

**Comment by oehme** [comment]
This is still an issue in the latest version, please reopen.
