### ISSUE TITLE
Upgrading to from 9.x to 10.x breaks Azure AD authentication in Azure Gov Cloud

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#71973]
### What happened?

We are working on upgrade from 9.5.2 to 10.0.2.  We have several grafana instances in Azure commercial cloud that we were able to upgrade without issues.  We use Azure AD for authentication.  Today I went to do the same upgrade in our Azure Gov environments and I noticed I was not able to login to grafana after upgrading.

We are getting the following errors when trying to login:
```
logger=context t=2023-07-19T17:41:53.6840194Z level=warn msg="failed to look up session from cookie" error="user token not found"
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:41:53.684281Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=x.x.x.x time_ms=0 duration=574.101µs size=29 referer= handler=/
logger=context t=2023-07-19T17:41:53.794927552Z level=warn msg="failed to look up session from cookie" error="user token not found"
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:41:53.796363753Z level=info msg="OAuth auto login enabled. Redirecting to /login/azuread"
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:41:53.796405553Z level=info msg="Request Completed" method=GET path=/login status=307 remote_addr=66.210.48.81 time_ms=1 duration=1.701301ms size=50 referer= handler=/login
logger=context t=2023-07-19T17:41:53.910388007Z level=warn msg="failed to look up session from cookie" error="user token not found"
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:41:53.910732407Z level=info msg="Request Completed" method=GET path=/login/azuread status=302 remote_addr=x.x.x.x time_ms=0 duration=567.8µs size=367 referer= handler=/login/:name
logger=context t=2023-07-19T17:41:54.881212167Z level=warn msg="failed to look up session from cookie" error="user token not found"
logger=oauth t=2023-07-19T17:41:54.881488267Z level=info msg="state check" queryState=810a528d3635115f88b57e08f19ebd7ec3e764c80870d9fff943eaf3b222d150 cookieState=810a528d3635115f88b57e08f19ebd7ec3e764c80870d9fff943eaf3b222d150
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:42:00.337117604Z level=error msg="login.OAuthLogin(get info from azuread)" error="error retrieving jwks: unable to extract tenant ID from URL"
logger=context userId=0 orgId=0 uname= t=2023-07-19T17:42:00.337436205Z level=error msg="Request Completed" method=GET path=/login/azuread status=500 remote_addr=x.x.x.x time_ms=5456 duration=5.456451438s size=1366 referer= handler=/login/:name
```

If I revert to 9.5.2 with no other changes everything works as expected so something has changed in 10.x that is breaking this.  Here is the relevant section of our grafana.ini:

```
[auth.azuread]
allow_sign_up = true
auth_url = https://login.microsoftonline.us/___TENANT_ID___/oauth2/v2.0/authorize
auto_login = true
client_id = __CLIENT_ID___
client_secret = ${AZUREAD_CLIENT_SECRET}
enabled = true
name = Azure AD
scopes = openid email profile
token_url = https://login.microsoftonline.us/__TENANT_ID___/oauth2/v2.0/token
```

It's interesting that the error says "unable to extract tenant ID from URL" when the tenant ID is specified in both the auth_url and the token_url.

### What did you expect to happen?

Azure AD authentication to keep working as it previously had

### Did this work before?

Yes, we have been using this for quite some time, since 7.x.

### How do we reproduce it?

1.  Upgrade grafana to 10.0.2

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.0.2
OS: FROM grafana/grafana:10.0.2
Browser: tried both chrome and safari

### Grafana platform?

Kubernetes

### Datasource(s)?

no

**Comment by danfinn** [comment]
Looks like this may be a duplicate of https://github.com/grafana/grafana/issues/71252

**Comment by mellieA** [comment]
@danfinn yes, I think you're right that this is a duplicate. The fix is merged for release https://github.com/grafana/grafana/pull/71254 which is marked for 10.1.x.

**Comment by danfinn** [comment]
@mellieA when can I expect that to make it to docker hub?

**Comment by danfinn** [comment]
@mellieA can you please let me know when to expect this to be available in a container image?

**Comment by danfinn** [comment]
@mellieA can someone please let me know when 10.1.x container images are expected?  As far as I can tell this was "released" on August 24th, a few weeks ago.
