### ISSUE TITLE
[Share Panel]: Flash required, switch to clipboard.js

### ISSUE THREAD

**Issue by xiaoxue999** [grafana/grafana#7198]
Is the button made by flash?
![4](https://cloud.githubusercontent.com/assets/22721577/21794893/4e6733dc-d739-11e6-8c5d-30867cb23d4b.png)

**Comment by torkelo** [comment]
Yes, for copy to clipboard, requires flash, think there is ways to do it without flash now.

**Comment by torkelo** [comment]
Will need to switch clipboard lib to https://clipboardjs.com/
