### ISSUE TITLE
[Bug] Grafana in Mac OS X dying with no output

### ISSUE THREAD

**Issue by JordiPolo** [grafana/grafana#7199]
Please include this information:
- What Grafana version are you using?
```
$ grafana-server  -v
Version 4.0.1 (commit: unknown-dev)
```
- What datasource are you using?
None yet
- What OS are you running grafana on?
Mac OS El capitan
- What did you do?
`brew install grafana`
`grafana-server`
- What was the expected result?
A running webserver
- What happened instead?
the grafana-server process just finishes

Maybe is a configuration issue but grafana-server installed clean in a mac OS X will just finish.
It will be good if the default configuration file would make the grafana-server not finish and do something instead or would at least print out the problem. 
As it is now as a new user, I have no idea of what's the issue

**Comment by daniellee** [comment]
Closing this but I can reopen if you are still having this problem. Sorry about the lack of response to your issue.
