### ISSUE TITLE
Dashboard Variables from Azure Monitor query not working as expected

### ISSUE THREAD

**Issue by itsjusth** [grafana/grafana#71994]
### What happened?

I have a dashboard with a query type variable.  I'm using the Azure Monitor plugin to query a custom log in a Log Analytics Workspace for distinct values.  Records are loaded once per day.  I am seeing no results at all.  I believe it may have something to do with how old the records are but I am not sure.  Some other variables that query a different Custom Log _are_ working as expected but records in that custom log flow in when specific events occur.

My KQL is something like the following:
```
my_item_inventory_CL
| where TimeGenerated >= ago(1d)
| distinct Type_s
```

This issue was observed ONLY after updating to Grafana 10.0.2.  I have downgraded to Grafana 9.5.6 and the issue is no longer present.

### What did you expect to happen?

Results are available to select in the dashboard.

### Did this work before?

Currently working as expected in Grafana 9.5.6.

### How do we reproduce it?

1. Populate a Log Analytics custom log with records.
2. Wait some time (12 hours) should be enough.
3. In Grafana 10.0.2, using Azure Monitor plugin, create a query type variable.
4. Get a property from the record.

### Environment (with versions)?

Grafana: 10.0.2
OS: Windows
Browser: Firefox and Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Azure Monitor

**Comment by mellieA** [comment]
https://github.com/grafana/grafana/issues/69940 possibly related

**Comment by aangelisc** [comment]
This is due to #67914. The behaviour has been clarified in #71278 (which hasn't been released yet) and a switch has been added to allow the user to control how timespans behave 😊 Please let me know if you need any more details otherwise I'll close this issue.

**Comment by asimpson** [comment]
Closing this for now, @mellieA feel free to re-open if things are still broken. Thanks!
