### ISSUE TITLE
[Bug] New user logins to default Org instead of mapped in ldap.toml

### ISSUE THREAD

**Issue by AlexMaksimkin** [grafana/grafana#7200]
We use LDAP auth with org mapping:
[[servers.group_mappings]]
group_dn = "grafana_editor"
org_role = "Editor"
org_id = 3

After new user logins for the first time(thru LDAP) - current organization for him still "1" but he don't have a rights for default Org and that cause error "Org missing" in main menu(near user name and avatar).
Only after manual change of current organization to mapped in ldap value(id = 3) it works as expected.

Is there any ways to force set current Org for first time logged user same as mapped in ldap.toml?
Or (best way) to fist organization for which user have an access?

ver: grafana-3.1.1-1470047149
Thanks

**Comment by Ostaer** [comment]
I have pulzzed on this too,I have try to match wildcard,
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
org_id = 1

Now the new user will login with default org_id = 1,
but when I enable the group mapping functions, The role will be synced every time the user logs in, so it will over any changes in web GUI

**Comment by trent** [comment]
+1

**Comment by reecewebb** [comment]
+1000

This is a major problem for us. LDAP org mapping is great, but it's really confusing for users when they login for the first time and don't see anything.

**Comment by noret** [comment]
+1

**Comment by pmdz** [comment]
+1

**Comment by danochoa** [comment]
+1

**Comment by valentinul** [comment]
Any progress on this ?

**Comment by tsn77130** [comment]
Hi, I have same behavior, even on grafana 5.
Did someone found  solution to deal with this ?

**Comment by rda0** [comment]
+1

Probably related: #11311 see [comment](https://github.com/grafana/grafana/issues/11311#issuecomment-376617873).
Looks like the Grafana team [is working on it](https://community.grafana.com/t/ldap-based-authentication-for-multiple-organizations/5988).

**Comment by marefr** [comment]
Have  #11311 fix included in v5.1.3 resolved this problem?

**Comment by servergeeks** [comment]
@marefr no, this is still an issue...

**Comment by xlson** [comment]
Closing this as it's no longer an issue in 7.2.0, I presume it has been working for quite some time.
