### ISSUE TITLE
Add Go client support for retrying queries

### ISSUE THREAD

**Issue by nikimanoledaki** [grafana/grafana#72001]
The existing functionality in the current client is [here](https://github.com/grafana/grafana-api-golang-client/blob/303710b3b781ad67f845d344fa2e5afe30db7f31/client.go#L88-L128).

The retrying of requests could be done by customizing and wrapping the generated client using [custom templates](https://github.com/go-swagger/go-swagger/blob/master/docs/generate/templates.md).

If feature parity is not feasible, this would be a breaking change from the manual client. Feedback from @julienduchesne: 
> Retrying is definitely a very important feature on the client, but I guess that if we can inject our own net/http Client, we could implement the retrying logic from the provider side

**Comment by zserge** [comment]
Retries are useful, but I don't think that client should be responsible for the retry logic. Generated client has an option of providing a custom [transport](https://pkg.go.dev/github.com/go-openapi/runtime?utm_source=godoc#ClientTransport) which is very similar to the `request` method of the hand-written Grafana Go client and can be wrapped with retries in mind. If that would work for the Terraform use case - I'd rather keep the client as dumb as possible, without any magic under the hood (i.e. the calling side might want to have different retry logic for different APIs, the calling side might want to instrument the retries to simplify debugging etc).

**Comment by nikimanoledaki** [comment]
The retry logic could be copied from the manual client and wrapped around the `transport.Submit` method using this custom template (which is used to generate every client): https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/client.gotmpl#L81-L85

**Comment by nikimanoledaki** [comment]
Sorry, I re-read your comment and now I understand that your suggestion is to add the retry logic to the transport of the client when it is initialised in the Terraform Provider, not on the client generation itself.

With the retry logic of the manual client, the user is able to configure the number of retries when initialising the client. The retry logic depends on this configuration: https://github.com/grafana/grafana-api-golang-client/blob/303710b3b781ad67f845d344fa2e5afe30db7f31/client.go#L89

The user could choose to not set this field. I think this still supports the use cases that you mentioned:
> i.e. the calling side might want to have different retry logic for different APIs, the calling side might want to instrument the retries to simplify debugging etc
