### ISSUE TITLE
Data in cookies 

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#72004]
### What happened?

I'm testing Grafana in multiple scenarios and reach a sequence that causes a problem.
I first connected to a system that uses security tokens, I reach that system using ssl tunneling so in practice my browser was pointing to the local host.
I then run grafana locally, probably there is something left in the cookies becasue I get this errors.
![Screenshot from 2023-07-20 12-04-08](https://github.com/grafana/grafana/assets/2118079/db2a7a37-a412-4aee-8390-fd5a8f541bfa)

When I open the same page in incognito it works as expected.

### What did you expect to happen?

dashboard should work as expected

### Did this work before?

yes

### How do we reproduce it?

1. Connect to a grafana server usign authentication, 
2. shut it down
3. Connect to the same Ip withut authentication

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.0.2 (but tested also with 9.5.6)
OS: Container
Browser: chrome

### Grafana platform?

Docker

**Comment by mellieA** [comment]
@amnonh I'd like to try this out, but can you give more details about the reproduction steps: 

1. Connect to grafana with authentication 
2. Shut it down - does this mean close the browser, the tab, or shut down the grafana service?
3. Connect to the same IP without authentication - do you mean open a new browser tab and the user will still be logged in?

**Comment by amnonh** [comment]
> @amnonh I'd like to try this out, but can you give more details about the reproduction steps:
> 
> 1. Connect to grafana with authentication
> 2. Shut it down - does this mean close the browser, the tab, or shut down the grafana service?
Shut down the grafana server
> 3. Connect to the same IP without authentication - do you mean open a new browser tab and the user will still be logged in?
I mean connect to the newly started server
