### ISSUE TITLE
[Feature request] Allow customization of organization filtering in Generic Oauth

### ISSUE THREAD

**Issue by kri5** [grafana/grafana#7201]
Using grafana 4.0.1 on debian, and after following some issues on github, i attempted to configure gitlab oauth with the generic oauth provider, and it's working.

The issue is that the generic oauth provider waits for the Oauth API you want to log-in against to have the same routes as the Github one. That leads to the fact that you cannot filter on the gitlab groups, which is the equivalent of the github organizations, because the routes and attributes does not match.

So if you're running against gitlab.com, which is a shared instance of gitlab, you simply cannot use Oauth.

**Comment by torkelo** [comment]
Can you describe you would implement this? How does the generic auth know what gitlab groups the user has? (needs to be generic oauth 2 standard)
