### ISSUE TITLE
[Bug] Templating OpenTSDB

### ISSUE THREAD

**Issue by Minims** [grafana/grafana#7202]
Hello,

 - Gafana 4.0.2 & Gafana 4.1 beta
 - DataSource OpenTSDB (All versions has the problem)
 - Linux Debian Jessie.

## TEMPLATING
$os: tag_values(load.gauge, os)
os can be debian and others
$host : tag_values(load.gauge, host, os=$os)

## ERROR
Template variables could not be initialized: can't parse query param 'm=load.gauge{host=*,os=d,os=e,os=b,os=i,os=a,os=n}'

## EXPECTED
if $os is 'debian' , the string has not to be split in chars
'm=load.gauge{host=*,os=debian}'

**Comment by utkarshcmu** [comment]
Similar issue was fixed on Nov 3 - https://github.com/grafana/grafana/pull/6455

**Comment by utkarshcmu** [comment]
But this is a bug again, looks like there was some code change somewhere... will take a look asap!

**Comment by utkarshcmu** [comment]
Fixed the issue!
