### ISSUE TITLE
Alerting: Image not loaded in Microsoft Teams webhook due to URL contains "&amp;" instead of "&"

### ISSUE THREAD

**Issue by Elpatii** [grafana/grafana#72033]
### What happened?

When using Grafana (v10.0.2) with Alerting, image rendering and a Microsoft Teams webhook as the contact point, the image URL generated for the alert contains `&amp;` instead of just `&`. This causes the image to fail loading in Microsoft Teams. However, when accessing the URL directly in a browser by removing `amp;`, the image loads correctly. This issue is specific to the Microsoft Teams webhook, as the problem does not occur when using email as the contact point.
The URL of the image in Teams is retrieve with integrated dev tool.

Behavior in Teams:
![teams](https://github.com/grafana/grafana/assets/4057711/a606f91d-30ca-4c30-b9dd-4a32b13a7391)

Behavior in Email:
![email](https://github.com/grafana/grafana/assets/4057711/39ba39b2-a524-48b0-ad0d-ae7ad88668c4)

### What did you expect to happen?

The image URL generated for the Microsoft Teams webhook should contain `&` instead of `&amp;`, allowing the image to load correctly in Microsoft Teams.

### Did this work before?

No.

### How do we reproduce it?

1. Configure Grafana with Alerting and a Microsoft Teams webhook as the contact point.
2. Trigger an alert that includes an image generated by Grafana rendering.
3. Receive the alert in Microsoft Teams and observe that the image fails to load due to the incorrect URL format.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: v10.0.2
OS: Ubuntu 22.04
Browser: Chrome

Docker configuration:
```
- GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true
- GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE=true
- GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=azure_blob
- GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_NAME=<truncated>
- GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_KEY=<truncated>
- GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_CONTAINER_NAME=<truncated>
- GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_SAS_TOKEN_EXPIRATION_DAYS=30
```

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

### Comments

Removing `GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_SAS_TOKEN_EXPIRATION_DAYS` environment and making the Azure Blob Storage container public allows the image to be well loaded in Teams. However, it's less secure as the URL doesn't contains SAS token and the container is public instead of private.

**Comment by usmangt** [comment]
Hi @Elpatii,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by yuri-tceretian** [comment]
@Elpatii, I could not reproduce the problem on my local machine using Grafana 10.0.2 and the latest version.
I could not find any signs of escaping the URL on our side either. According to the code 
https://github.com/grafana/grafana/blob/025b2f3011821bb7e6ab4781e252f3a1ecd19130/pkg/components/imguploader/azureblobuploader.go#L114-L137
the URL is built by using the tools provided by the Azure SDK and then it is passed through without changes. 

To troubleshoot it further I would recommend:
1. Check whether the URL is stored with encoded `&` in the database, table `alert_image`. The alternative is to enable debug log and `[database].log_queries`, wait for the screenshot to be taken, find a message "INSERT INTO `alert_image`" in the logs and see whether the URL contains the encoded symbol.
2. Configure Teams contact point but use webhook debugger service, for example `webhook.site`. Wait until you get any message, and check whether the symbol is encoded there.

If you find anything, I would appreciate it if you can report back. It will help us isolate the problem and perhaps fix it.

**Comment by KaplanSarah** [comment]
Closing as stale.
