### ISSUE TITLE
[Bug] Table legend not scrolling anymore

### ISSUE THREAD

**Issue by exbane** [grafana/grafana#7204]
This feature used to work fine but now after upgrading to 4.2beta it seems to have stopped working properly. 

Please include this information:
- What Grafana version are you using? 4.2 Nightly Build
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS7
- What did you do? Upgraded from 4.0.2 to 4.2beta
- What was the expected result? A scroll bar on the table legend
- What happened instead? no scroll bar after the upgrade

![grafana-legend-scrollbar](https://cloud.githubusercontent.com/assets/12447405/21817053/76728aa6-d730-11e6-9f19-433a75aebfd0.PNG)

**Comment by torkelo** [comment]
thanks for reporting this, I forgot about this. Was trying to fix another bug with the legend table (the scrollbar was always visible), and introduced this. https://github.com/grafana/grafana/issues/6828#issuecomment-270456263 

@bergquist sorry, might need to do a quick fix for this and do another build for 4.1 stable :(
