### ISSUE TITLE
Unable to disable grafana live

### ISSUE THREAD

**Issue by AshishVerma7690** [grafana/grafana#72072]
### What happened?

Below are my live settings

```
#################################### Grafana Live ##########################################
[live]
# max_connections to Grafana Live WebSocket endpoint per Grafana server instance. See Grafana Live docs
# if you are planning to make it higher than default 100 since this can require some OS and infrastructure
# tuning. 0 disables Live, -1 means unlimited connections.
max_connections = 0

# allowed_origins is a comma-separated list of origins that can establish connection with Grafana Live.
# If not set then origin will be matched over root_url. Supports wildcard symbol "*".
allowed_origins = *
```

I am trying to disable the grafana live on my setup.

### What did you expect to happen?

Grafana live should be disabled.

### Did this work before?

No

### How do we reproduce it?

1. Start grafana
You can see multiple ws  live call in the logs

`2023-07-21T10:10:50.474186+05:30 hac-verma-1 grafana_0: {"timestamp":"2023-07-21T04:40:50.468559Z","host":"hac-verma-1","container":"fbd06a7dfdff","msg":"duration=24.488ms handler=/api/live/ws level=info logger=context method=GET msg=Request Completed orgId=1 path=/api/live/ws referer= remote_addr=10.124.6.201 size=10 status=403 time_ms=24 uname= userId=0","priority":7,"namespace":"grafana-server"}`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 9.4.3
OS:  ubuntu
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

graphite

**Comment by usmangt** [comment]
Hi @AshishVerma7690,

Thanks for opening this issue.

Try to put a semicolon ";" in front of the grafana live [configuration section](https://github.com/grafana/grafana/blob/8afd2163970c959500b1ff83a91a5da7fe88ede2/conf/defaults.ini#L1442-L1462)

Then do a restart and let us know if this helps. Also, comment out its configuration from the web server e.g. Nginx, Apache etc.

**Comment by AshishVerma7690** [comment]
@usmangt  Thanks for answering. 
I have tried this in env and it is working and grafana live msgs are not there.  I need to know where this environment variable is used, Is there any official doc for the same? 
Also, I have tried this using grafana ini file (setting max_connections = 0) and it did not work.

**Comment by usmangt** [comment]
Here is the link to the documentation: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables :slightly_smiling_face:

**Comment by KihyeokK** [comment]
This issue seems to be still ongoing. I've tried setting `max_connections: 0` as suggested by the Grafana docs, and also tried setting env var `GF_LIVE_MAX_CONNECTIONS=0` instead, but neither of the approaches disables Grafana Live. 

I also see other people unable to disable Grafana Live:
- https://stackoverflow.com/questions/79269488/why-am-i-still-seeing-grafana-live-api-calls-despite-setting-max-connections-to
- https://community.grafana.com/t/unable-to-disable-grafana-live-api/138191

Would appreciate it a lot if this issue can be investigated again!

**Comment by KihyeokK** [comment]
@usmangt Would appreciate it a lot if you can reopen this issue again 🙏

**Comment by hamadodene** [comment]
I have same issue  with 11.4.0.
I have tried GF_LIVE_MAX_CONNECTIONS=0 but not disable grafana live. 
As a workaround the block the requests reverse proxy side.

**Comment by KonVei82** [comment]
Same issue here with Grafana v11.4.1

max_connections = 0 is set in custom.ini yet the grafana logs report:
`logger=live.push_http t=2025-02-09T01:09:29.236630092Z level=info msg="Live Push Gateway initialization"`
