### ISSUE TITLE
"Add to dashboard" should preserve time-range from Explore

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#72085]
the "Add to dashboard" from Explore should really preserve the start and end times that I've chosen in the time-picker.

This gets me every time, it's super confusing :confounded: and really breaks my flow. Once I've recovered from the confusion I'm then simply annoyed :weary:

I think the same behaviour makes sense for existing dashboards too: move the time range to match the recent explore.
That gives the user the most freedom to decide what to do next, and I think is also less surprising too, as the panel they just added will actually be recognised as identical to the viz that they saw a moment ago on the explore.

Then when they come to save the dashboard they have the checkbox and can choose “also save this time range as the default”.

**Comment by chauchausoup** [comment]
@samjewell @Elfo404 so the proper solution would be to have a uniform time picker value once set from any of the routes/window throughout the app ? Or just on the above mentioned routes/windows ?

**Comment by samjewell** [comment]
> any of the routes/window throughout the app

What other routes are there through the app? Do you have a full list?

I can't think of any other routes right now. But I think my answer is "Yes" - let's go with the uniform time-picker for all routes as a first improvement - we can always polish it further if we find some that aren't working well.

**Comment by Elfo404** [comment]
One way to achieve this for this use case is to look into public/app/features/dashboard/state/initDashboard.ts initDashboard function to check how the timeSrv is initialized, we should pass the current time range explore is using when creating the object in local storage that dashboards use to init
