### ISSUE TITLE
Datasource Query Audit Log

### ISSUE THREAD

**Issue by Ricky-N** [grafana/grafana#7210]
For info security purposes, it is critical to have an audit log to understand which users are hitting which datasources, hopefully down to more specific information about data in those datasources. This will enable us to track back who might have been exposed to protected but leaked data in the event of an issue.

**Comment by Ricky-N** [comment]
Draft of fix #7209

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/7209
