### ISSUE TITLE
[Bug] 4.1 beta: ES 5.1.1 templating value tagging cannot be enabled

### ISSUE THREAD

**Issue by dachenbach** [grafana/grafana#7211]
- What Grafana version are you using? 4.1.0-1482230757beta1
- What datasource are you using? Elasticsearch 5.1.1
- What OS are you running grafana on? CentOS 7.2.1511
- What did you do?
  - Select existing dashboard
  - Manage Dashboard -> Templating
  - Create new Multi-value "Query" variable
  - Enable "Value groups/tags" and provide "Tags query" and "Tag values query"
- What was the expected result?
  - "Value groups/tags" stays enabled and the drop down box for the variable displays the tags
- What happened instead?
  - No tags are displayed
  - After leaving and going back to the dashboard, the tag queries are still there, but the tags option is disabled
  - Re-enabling and repeating the process always results in the option being disabled when going back to the dashboard.
  - It is behaving like it is never enabled even though the checkbox for it to be enabled stays until I leave the dashboard.

Here is the relevant JSON:

```
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "text": "**********",
          "value": "*********"
        },
        "datasource": "*********",
        "hide": 0,
        "includeAll": false,
        "label": "Server",
        "multi": true,
        "name": "server",
        "options": [],
        "query": "{\"find\": \"terms\", \"field\": \"beat.hostname\", \"query\": \"mdc_env:$environment\"}",
        "refresh": 1,
        "regex": "",
        "sort": 1,
        "tagValuesQuery": "{\"find\": \"terms\", \"field\": \"beat.hostname\", \"query\": \"mdc_service:$tag\"}",
        "tagsQuery": "{\"find\": \"terms\", \"field\": \"mdc_service\"}",
        "type": "query"
      }
    ]
  },
```

Note that the JSON does not change between enabling the option and leaving the dashboard and coming back (at which time the option shows as disabled). Also, if I enable the option, don't save the dashboard and leave the dashboard, I am not prompted to save like I normally would be after making a change.

After I enable the tags option:
![image](https://cloud.githubusercontent.com/assets/19396787/21825868/4b9894ba-d73a-11e6-8093-7c4bb0ee7f8a.png)

After I save, leave the dashboard, and come back:
![image](https://cloud.githubusercontent.com/assets/19396787/21825891/5ffb0d2a-d73a-11e6-832d-1c6a036d51af.png)

**Comment by torkelo** [comment]
try 4.1 stable released today, it contains a fix for template variable groups
