### ISSUE TITLE
Feature toggle removal: exploreScrollableLogsContainer

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72148]
Added in https://github.com/grafana/grafana/pull/69371, on June 15, 2022. Consider whether we should release, including steps needed to validate readiness, or remove.

Improves the scrolling behavior of logs in Explore.
Gather feedback from loki users, remove feature flag if the feedback is good. (maybe release along with infinite scroll).

**Comment by matyax** [comment]
To be done after https://github.com/grafana/grafana/pull/76348
