### ISSUE TITLE
Product Area: renderChart func does not work

### ISSUE THREAD

**Issue by HandsomeBrother** [grafana/grafana#72165]
### What happened?

when I use  Stat component, renderChart func does not work, I found the renderChart has 2 useless definitions

### What did you expect to happen?

renderChart could run, here is my pr : https://github.com/grafana/grafana/pull/72120

### Did this work before?

no

### How do we reproduce it?

```
<template>
    <StatVue
          v-if="SnapshotDataR"
          :data="SnapshotDataR"
          :config="config"
          width="120"
          height="120"
          :options="Statopts"
          :fidle-config="fidleConfig"
        />
</template>
<script setup lang="tsx"></script>
import { applyPureReactInVue } from 'veaury'
const StatVue = applyPureReactInVue(StatPanel)
  const SnapshotDataR = ref()
  const Statopts = ref({
    colorMode: 'value',
    graphMode: 'area',
  })
  const fidleConfig = {
    mappings: [],
  }

```

### Environment (with versions)?

Grafana:10.1.0
OS: 12.1 (Apple M1)
Browser:版本 114.0.5735.198（正式版本） (arm64)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/72120
```

**Comment by usmangt** [comment]
Hi @HandsomeBrother,

Thanks for opening this issue.

Just to get more information. Is this more of a frontend issue or the Stat plugin ?

**Comment by HandsomeBrother** [comment]
@usmangt I noticed that it seems to be a problem with the BigValue component, and here is the pr I mentioned：https://github.com/grafana/grafana/pull/72120/files

**Comment by nmarrs** [comment]
Hi @HandsomeBrother - thanks for the issue / PR. Looking into this I am missing some context. Can you describe / provide some screenshots of what is breaking on your end with the Stat panel? What is your desired use case for the stat panel?

Thanks!

**Comment by nmarrs** [comment]
Hi @HandsomeBrother - just checking in again :) are you still having this issue? Are you able to provide any more context as I am not sure how to reproduce what you are experiencing. Thanks!
