### ISSUE TITLE
Issue with Dimension Values in Alerting with CloudWatch Datasource

### ISSUE THREAD

**Issue by OriMeyuhas** [grafana/grafana#72172]
### What happened?

Hello,

I'm currently using Grafana version 9.4.7 with AWS CloudWatch as my data source. I have a panel where I'm monitoring the `SumOffsetLag` metric from the `AWS/Kafka` namespace. I have three dimensions in my setup: `Cluster Name`, `Consumer Group`, and `Topic`.

I'm trying to create an alert based on this panel. However, I'm encountering an issue with the dimension values in the alert configuration. Instead of getting individual values for each dimension, I'm getting all the dimension values concatenated together.

For example, instead of getting:

```
Cluster Name = Cluster Name
Consumer Group = Consumer Group
Topic = Topic
```

I'm getting:

```
Cluster Name = Cluster Name + ConsumerGroup + Topic
Consumer Group = Cluster Name + Consumer Group + Topic
Topic = Cluster Name + Consumer Group + Topic
```
![Grafana Issue](https://github.com/grafana/grafana/assets/107118002/1777c7ba-425c-44dd-89d1-da0cfc6ddf95)

This is causing issues with my alert configuration, as I'm not able to correctly reference the individual dimension values in the alert message.

I've tried various configurations and syntaxes, but I haven't been able to resolve this issue. I would appreciate any guidance or suggestions on how to correctly reference the individual dimension values in the alert configuration.

Thank you in advance for your help.

### What did you expect to happen?

I expected to be able to reference the individual dimension values in the alert message using the `$labels.<label_name>` syntax. Specifically, I expected to get individual values for each dimension, like Cluster Name = Cluster Name, Consumer Group = Consumer Group, and Topic = Topic. This would allow me to create alerts that are specific to each combination of Cluster Name, Consumer Group, and Topic.

### Did this work before?

First time tried.

### How do we reproduce it?

1. Set up the data source: I'm using AWS CloudWatch as my data source in Grafana version 9.4.7. The CloudWatch metrics are from the AWS/Kafka namespace.

2. Create a panel: I created a panel where I'm monitoring the SumOffsetLag metric. I have three dimensions in my setup: Cluster Name, Consumer Group, and Topic. I'm using a wildcard '*' for each dimension to cover all possible values.

3. Create an alert: I tried to create an alert based on this panel. In the alert configuration, I attempted to reference the individual dimension values in the alert message using the $labels.<label_name> syntax.

4. Observe the issue: Instead of getting individual values for each dimension, I'm getting all the dimension values concatenated together as mentioned.

### Environment (with versions)?

Grafana: 9.4.7

### Grafana platform?

Kubernetes

### Datasource(s)?

CloudWatch

**Comment by usmangt** [comment]
Hi @OriMeyuhas,

Thanks for opening this issue.

Grafana's current latest stable version is 10.0.2 and the version you are using is just slightly old. The Grafana version 10.x contains numerous bug fixes and improvements.

Therefore, the recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here.

Thank you

**Comment by OriMeyuhas** [comment]
Hi @usmangt , 

Thank you for your response. I have upgraded my Grafana to the latest stable version, 10.0.2, as you suggested. However, I'm still encountering the same issue with the dimension values in the alert configuration.

When using wildcards in dimensions, instead of getting individual values for each dimension, I'm getting all the dimension values concatenated together. This is causing issues with my alert configuration, as I'm not able to correctly reference the individual dimension values in the alert message.
<img width="1789" alt="Grafana issue 2" src="https://github.com/grafana/grafana/assets/107118002/36defc32-ee2d-4849-b25d-6d941f84b1c0">



In addition to reporting this issue, I'd like to suggest a potential feature that could solve this problem and add more flexibility to Grafana's alerting capabilities. It would be very helpful if Grafana could support variables in the alert dimension values. This way, users could dynamically set the dimension values based on the context of the alert. For example, if an alert is triggered for a specific `Consumer Group`, the alert message could reference the name of that `Consumer Group` using a variable.

This feature would be particularly useful in scenarios where there are multiple potential dimension values, and the user wants to create a single alert rule that covers all of them. I believe this feature would greatly enhance Grafana's alerting capabilities and make it more flexible and powerful.

I would appreciate any further guidance on the issue I'm facing and hope you'll consider this feature suggestion.

Thank you.

**Comment by sarahzinger** [comment]
@OriMeyuhas Thanks so much for this very detailed Bug Report! We really appreciate it!

I just tried this myself with the main branch of Grafana and was able to reproduce it in `aws/usage` as well. I don't think it's kafka related, seems to be specifically related to cloudwatch dynamic labels and alerting. 

My repro steps:
- I made the following selections in the query editor:
<img width="980" alt="Screenshot 2023-07-27 at 2 32 44 PM" src="https://github.com/grafana/grafana/assets/6620164/4ed2beaa-2067-4c98-a9b6-7db83a8a4da1">
It's a bit cut off there but I used the label `${PROP('Dim.Service')} - ${PROP('Dim.Resource')} - ${PROP('Dim.Type')}`
- This returned back well-formatted labels:
<img width="972" alt="Screenshot 2023-07-27 at 2 34 06 PM" src="https://github.com/grafana/grafana/assets/6620164/ae685790-d8b1-4721-b876-4fe236c7f2c8">
- I then turned that query into an alert, and noticed that while the labels in the graph still show fine, the reduce expression is not interpreting the dimensions correctly:
<img width="557" alt="Screenshot 2023-07-27 at 2 36 38 PM" src="https://github.com/grafana/grafana/assets/6620164/5c617054-d0f2-4f1a-be10-dfd7a7ff1f88">

I haven't dug into the code to see why this may be happening yet but I think we have good repro steps and should hopefully be able to prioritize this issue in an upcoming sprint. Thanks again for you contribution!

**Comment by OriMeyuhas** [comment]
Hi @sarahzinger ,

Thank you for looking into this issue. I'm glad to hear that you've been able to reproduce and understand the problem. I appreciate your efforts and look forward to any updates or fixes in the upcoming sprints.

Also, thank you for considering my feature suggestion. I believe it could add significant flexibility to Grafana's alerting capabilities.

**Comment by Tadimsky** [comment]
We're having the same issue with this. We're on Grafana Cloud v10.2.0-59981
I had to specify a custom label to fix this:

![image](https://github.com/grafana/grafana/assets/1149244/d1c26d08-7323-462a-b9cc-644ab7c8f384)
