### ISSUE TITLE
[Feature request] suppress refresh while tab is background

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7218]
I want to stop the "auto refresh" if the user doesn't watch the dashboard.
`Page Visibility` API can detect such status.
http://caniuse.com/#search=Page%20Visibility

**Comment by irandom** [comment]
@mtanda Is there a place in Grafana to store a bit of settings to enable or disable this behaviour? Such a feature is obviously not for every circumstance or every person, and I'd like to make an improvement.

**Comment by mtanda** [comment]
@irandom Sorry, there is no settings.
If you want to disable this by settings, it might be better to open Feature Request.
