### ISSUE TITLE
Set grafana alert on restarted containers

### ISSUE THREAD

**Issue by win5923** [grafana/grafana#72201]
**What is the chore?**:
Hi, I am using `Prometheus` , `Grafana` , `Cadvisor` to monitor docker containers status. I want to set up a `Grafana Alert` to detect if the same container fails to restart within 200 seconds and send an alert. However, I noticed that after the container restarts, cadvisor generates new metrics. How can I determine if the container is functioning normally after a restart?

![image](https://github.com/google/cadvisor/assets/56353753/a9cc268f-2103-4279-8496-e73a59d41e79)

The alert will generate a large number of errors due to `container_label_restartcount`, and it is inevitable that the container before the restart will exceed the time threshold since its metrics are distinct from those after the restart.

![image](https://github.com/google/cadvisor/assets/56353753/4ca39599-f2ad-4b7c-9780-de10e1fc3222)

Thanks in advance.

**Is there anything else we need to know?**:

cadvisor Version: v0.47.2
Grafana Version: v10.0.2 
Prometheus Version: 2.45.0
Node-Exporter Version: 1.6.1

**Comment by usmangt** [comment]
Hi @win5923,

Thanks for opening this issue.

I am not sure as it sounds like that CAdvisor configuration sends new metrics to the Alerting component. I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by win5923** [comment]
hi @usmangt ,
I came to this rule
`count by (instance, name) (count_over_time(container_last_seen{name!="", container_label_restartcount!=""}[15m])) - 1 >= 5`
it can count unique records for each instance and name now.
thanks!
