### ISSUE TITLE
[Bug] templated variables list looks strange with many items

### ISSUE THREAD

**Issue by r0bj** [grafana/grafana#7222]
grafana version: 4.1.0
datasource: influxdb
OS: grafana from docker image

Having many templated variables dashboard looks a little strange:

<img width="1272" alt="screen shot 2017-01-11 at 15 16 48" src="https://cloud.githubusercontent.com/assets/1297747/21851929/8024a390-d811-11e6-8d3a-e3794fa93c0f.png">

Is it supposed to look like this?

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630). We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
