### ISSUE TITLE
SMTP helo domain name

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#7223]
I cant send smtp notifications due to grafana is using 'localhost' to identify itself with the HELO command,

Jan 11 16:11:22 mailgw02 postfix/smtpd[30833]: NOQUEUE: reject: RCPT from grafana01[10.0.0.96]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=<grafana@foobar.com> to=<alerts@foobar.com> proto=ESMTP helo=<localhost>
Jan 11 16:11:22 mailgw02 postfix/smtpd[30833]: disconnect from grafana01[10.0.0.96]

I found in the source code it uses 'localhost', https://github.com/grafana/grafana/blob/5bf5ed68e17dabb8c3aa957c6a0b6a9e3e117817/vendor/gopkg.in/gomail.v2/smtp.go#L33-L35

I would like this to be a config option under [smtp] and maybe use the hostname by default.

**Comment by bergquist** [comment]
Would be great if we could avoid adding an extra setting for this. 

Using `instance_name` would be a preferred solution.

**Comment by thz** [comment]
Commenting on this closed issue for clarification:

We use SMTP-relay from a provider and we need to set HELO name to a domain we have with them. That domain is not the same as the hostname grafana is running on.

For that reason the InstanceName as HELO name does not work for us.

Would a PR adding an option to override the HELO name have any chance for acceptance?

(mentioning @bergquist )
