### ISSUE TITLE
[Bug] Display both left and right axes with one data series

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/grafana#7226]
- What Grafana version are you using?
V4.0.2 (32-bit and 64-bit from source, 64-bit precompiled) , V4.1.0 (32-bit from source)
- What datasource are you using?
SimpleJSON v1.2.4
- What OS are you running grafana on?
nix
- What did you do?
Ticked both 'show' check boxes for 'Left Y' and 'Right Y' on the 'Axes' tab while editing a graph(left all settings default on both). Only one data series is set-up on the 'Metrics' tab. Data is retrieved correctly and shown on the graph.  
- What was the expected result?
Both axes to be displayed continuously, with the same scale. 
- What happened instead?
Only one axis is displayed, whichever one the data series is assigned to.

**Comment by torkelo** [comment]
you need a series on the right Y axis for it to show up.

**Comment by ikkemaniac** [comment]
I understand, but why can i check both axes if it doesn't apply? If you allow a user to select 'show' while it won't it makes it very confusing.

**Comment by torkelo** [comment]
Its there to hide the axis, when you have a series on right-y

**Comment by ikkemaniac** [comment]
I understand, but you guys 'hide' everything when the option is irrelevant; why not with this? Based on the behaviour of the other controls this just doesn't make sense to me.
