### ISSUE TITLE
Failed to send alert.: failed to send notification to email addresses: <organization emaild>: 535 Authentication failed

### ISSUE THREAD

**Issue by hareeshkumaragnur** [grafana/grafana#72261]
### What happened?

Hi,

I was trying to send test email alert to my organization email address and getting this error in grafana
**"Failed to send test alert.: failed to send notification to email addresses: **organizationemailaddress**: 535 Authentication failed"**

I have updated the SMTP section as below 

[smtp]
enabled = true
host = **organizationsmtphostadddress**
user = **organizationemailaddress**
password = **organizationemailpassword**
cert_file =
key_file =
skip_verify = true
from_address = **organizationemailaddress**
from_name = Grafana
ehlo_identity =

### What did you expect to happen?

I would a test alert email should be sent

### Did this work before?

never tried

### How do we reproduce it?

1. Update the smtp section as mentioned above
2. test the alert email on clicking "Test" from the "contact points" section under "Alerting"

### Is the bug inside a dashboard panel?

dashboard

### Environment (with versions)?

Grafana: 10.0.2 (deployed as an azure app service) 
OS: windows
Browser: chrome

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @hareeshkumaragnur,

This is neither Grafana or Alerting issue but the error message is coming from SMTP. According to the error code

> The “SMTP error 535 authentication failed” message may occur if you mistakenly enter the wrong username or password into your program.

I would recommend to test if the email can be send out via [telnet](https://www.thomas-krenn.com/en/wiki/Test_TCP_Port_25_(smtp)_access_with_telnet) command.

Also highly recommend searching for similar issues at our community forum in the [Alerting category](https://community.grafana.com/c/support/alerting/60) OR ask a question by creating a new post.

I will now close this issue.

Thank you for your understanding :pray:
