### ISSUE TITLE
[Bug] 'grafana-server' version commit-info incorrect

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/grafana#7227]
- What Grafana version are you using?
V4.0.2 (32-bit and 64-bit from source, 64-bit precompiled) , V4.1.0 (32-bit from source)
- What datasource are you using?
SimpleJSON v1.2.4
- What OS are you running grafana on?
nix
- What did you do?
`$ grafana-server -v` 
- What was the expected result?
`Version 4.0.2 (commit: GIT_COMMIT_HASH[-dirty])`
- What happened instead?
`Version 4.0.2 (commit: GIT_TAG[-dirty])` displayed examples:
`Version 4.0.2 (commit: v4.0.2)`
`Version 4.0.2 (commit: v4.0.2-dirty)`
`Version 4.1.0-beta1 (commit: v4.1.0-beta1)` 
-Cause:
grafana uses the [`getGitSha` function in `build.go` ](https://github.com/grafana/grafana/blob/v4.1.0-beta1/build.go#L431) which calls `git describe --always --dirty`.
```
$ git --version 
git version 1.7.9.5
```
From `man git describe` 
> --always  _____ Show uniquely abbreviated commit object as fallback.
Git will not display a hash necessarily, but it will describe the current state uniquely.

_*** I have to say that while digging deeper and deeper into this while writing the issue i actually found out that the output produced by the git cmd, with more than only the tag ofcourse, can directly be used in a `git checkout GIT_DESCRIBE_ALWAYS_OUTPUT` so this is not really an issue but maybe a misunderstanding of what is meant with commit because this is so often used to display the commit SHA***_

But when not on a 'tagged' commit (32bit) `NA` is shown while the `git describe` shows a lot more:
```
$ ~/grafana/grafana-src/src/github.com/grafana/grafana/bin$ ../../../../../bin/grafana-server -v
Version 4.1.0 (commit: NA)
$ ~/grafana/grafana-src/src/github.com/grafana/grafana/bin$ git describe --always --dirty
v4.1.0-beta1-23-gd662961
```
- Cause
2) ? no suggestion, sorry

**Comment by torkelo** [comment]
strange, maybe some issue in this code:

https://github.com/grafana/grafana/blob/master/build.go#L431
