### ISSUE TITLE
[BUG] Legend height lost scroll?

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#7229]
Please include this information:
- What Grafana version are you using? 4.0.1 - 4.1.0
- What datasource are you using? elasticsearch 2.4.3

What happened to the legend height beeing shrunk to the same height as the panel and adding a scrollbar to it? I used to run a beta or nightly build prior to 4.0.1 but now upgraded and i get this behaviour with the full legend table beeing shown - which of course causes the dashboard to go tits up! :)

expected behaviour: the legend would end by the arrow - and when hovered over you could scroll down through the legend

![image](https://cloud.githubusercontent.com/assets/12600004/21868682/42a081fe-d854-11e6-92b4-9fbab294c9de.png)

**Comment by timbutler** [comment]
This was just fixed in #7221, I've installed the latest build (grafana-4.1.0-1484145312) and the issue is resolved for me.

**Comment by discoduck2x** [comment]
@timbutler thanks for the info, cant believe i didnt find that one when i searched for similar issues. I´ll await that to be built for windows then as thats where im testing locally right now
