### ISSUE TITLE
[Feature request] Alerts timezone

### ISSUE THREAD

**Issue by digitalmess03** [grafana/grafana#7230]
![alerting issue](https://cloud.githubusercontent.com/assets/25071119/21875886/4608e7fc-d84d-11e6-9619-440ed27a2f9f.PNG)
- What Grafana version are you using?
4.1.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16
- What did you do?
Set alerts on data source
- What was the expected result?
Alert was configured to check against last 5 minutes.
- What happened instead?
Shows no data.

If you create an alert against latest data that's written using time.ctime() it shows no data. Would be nice if your logging this way, that you could set within the alert to offset by timezone. If I set to evaluate against the last 6h then the alerting finds data and alerts properly. The easy solution is to simply write your data time to the database as UTC instead of local time, which I'll do, just to keep things up to speed. But would be a nice feature to add to alert settings.

**Comment by torkelo** [comment]
you should always write data in UTC to a time series database. 

Sorry closing this.
