### ISSUE TITLE
Fails to save alerts with error "failed to build query 'A': data source not found" - while the data source works in the rule edit page

### ISSUE THREAD

**Issue by zoltan-fedor** [grafana/grafana#72314]
### What happened?

After restarting Grafana certain alerts report error due to their datasource not being available. Even after updating the data source in the alert rule edit page - which data source is obviously available as it shows the metrics in the graph in the alert (see screenshot below) -, it still doesn't allow saving the rule with the "failed to build query 'A': data source not found" error.

![image](https://github.com/grafana/grafana/assets/3887295/249bda89-6768-4b11-93dc-83847ac2a5aa)

Same thing happens if I try to recreate the alert from scratch.
Other alerts are happily using the same datasource (after their datasource needed to be updated, those alerts did not throw this nonsensical error when saving them).

### What did you expect to happen?

I would expect that the alerts would not be throwing nonsensical error messages.

### Did this work before?

Yes

### How do we reproduce it?

1. Don't know what is causing it, so I can't tell you how to reproduce it.
2.
3.

### Environment (with versions)?

Grafana: 9.3.2
OS: All
Browser: All

### Grafana platform?

None

**Comment by zoltan-fedor** [comment]
Funny, somehow this error is triggered by the Evaluation Group - in that group all alerts throw this error.
Same alert in a different Evaluation Group is fine.

How does the Evaluation Group causes the data source being not found????

You can see how the same error is thrown even if I just try to rename the Evaluation Group:
![image](https://github.com/grafana/grafana/assets/3887295/24edcfa6-63fe-4ac7-a2c0-127d5e45b3a6)

**Comment by zoltan-fedor** [comment]
I ended up moving these alerts into a different Evaluation Group - then I was allowed to save them, that error about data sources was not popping up anymore.
This makes no sense, but it is what it is.

**Comment by usmangt** [comment]
:Hi @zoltan-fedor,

Thanks for opening this issue.

We need the following information.

1. Grafana's current latest stable version is 10.0.3 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)).

The recommendation would be to test this in the recent stable version and if that does not work then provide information asked in Step 2 and 3


2. Is the Prometheus Data source is also on the same machine where Grafana is running? (wondering if incase it is and when you restart the node, does the Prometheus endpoint is available at that time or after a delay).

3. Could you please change the default log level to debug mode? 

To do this go to the server where grafana is installed and edit the configuration file (`/etc/grafana/grafana.ini`)

There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again.

**Comment by usmangt** [comment]
Based on the above comment, closing this issue.

Can be re-opened if it occurs again!
