### ISSUE TITLE
[Bug] Do we have any other variable other than $timeFilter to be used in Query (like $timeFrom and $timeTo)?

### ISSUE THREAD

**Issue by GVHitHub** [grafana/grafana#7231]
Please include this information:
- What Grafana version are you using? - 4.0.2-s11.5
- What datasource are you using? - InfluxDB
- What OS are you running grafana on? - Ubuntu
- What did you do? - Creating a dashboard with Influx DB query and looking for options for time in influxdb query (from and to) rather than using $timeFilter
- What was the expected result? Need more variables like $timeFrom and $timeTo instead of just $timeFilter
- What happened instead? NA

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
not yet https://github.com/grafana/grafana/issues/1909
