### ISSUE TITLE
UI: Tags on Dashboard List page not sorted

### ISSUE THREAD

**Issue by MarcBridner** [grafana/grafana#72318]
### What happened?

Tags belonging to dashboards on the dashboard list do not appear to be sorted when viewing dashboard folders on `/dashboards`, see attached image.
![image](https://github.com/grafana/grafana/assets/3307536/88acc362-8c2b-4d6a-bcfb-5b70f380542d)

Looking at the network traffic it appears that `/api/search?limit=1000` always returns the tags sorted, while `/api/search?limit=1000&sort=name_sort&type=dash-db&folderIds=20` does not.

When loading `/dashboards` both requests are made, `/api/search?limit=1000` loading everything with sorted tags and `/api/search?limit=1000&sort=name_sort&type=dash-db&folderIds=20` loading a subset with unsorted tags

My dashboards are mostly identical except for some parameters, and they were created using the Dashboard API, from the same source, so they all have the tags in the same order in the HTTP POST to Grafana

### What did you expect to happen?

I expected the tags to be sorted per https://github.com/grafana/grafana/issues/2091

### Did this work before?

Don't know, I assume so based on https://github.com/grafana/grafana/issues/2091

### How do we reproduce it?

1. Create 20-50 dashboards with the same tags and put them in a folder
2. Keep reloading the dashboard list view
3. Examine `/api/search?limit=1000&sort=name_sort&type=dash-db&folderIds=20` vs `/api/search?limit=1000` 

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.0.1 (5a30620b85)
OS: Ubuntu
Browser: Firefox 102

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @MarcBridner,

Thanks for opening this issue.

We will investigate this and will come back to you once we have more information.

**Comment by usmangt** [comment]
Hi @MarcBridner,

Please see the above link for issue https://github.com/grafana/grafana/pull/72872 which will also fix this issue as well
