### ISSUE TITLE
[Feature request] Support influxdb's SLIMIT Feature

### ISSUE THREAD

**Issue by ryanjin** [grafana/grafana#7232]
Is it possible to support influxdb's SLIMIT Feature?

https://docs.influxdata.com/influxdb/v1.1//query_language/data_exploration/#the-limit-and-slimit-clauses

It is useful ,ie if somebody want to show the top 10 high avg load pc from the whole datacenter.

**Comment by Kaacz** [comment]
Why to use complex "select .. order by .. slimit ..", when function top() exists? For this case to show top-ten table I use simply:
`SELECT top("load","hostname", 10) AS load FROM "servers" WHERE $timeFilter`
and Override relative time last 2m for 1m sampling...

**Comment by exbane** [comment]
+1 for this.. The TOPN function doesn't seem to work properly for InfluxDB data. Even if you say TOP 10 it still lists every object in the dataset.

**Comment by Liugart123** [comment]
@exbane Maybe you can use "limit 10" at the end of your query to show only the first 10 numbers.
