### ISSUE TITLE
Transformation: `extractFields` might lead to duplicated fields with the same name

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#72331]
Using Elasticsearch, when you switch to table view a warning appears in the console pointing out duplicated field names.

![Image](https://github.com/grafana/grafana/assets/1069378/3bed4b49-c951-4f0e-9815-7342ff1bc595)

Steps to reproduce:

- `make devenv sources=elastic`
- Go to Explore
- Switch to "Logs" tag 
  ![imagen](https://github.com/grafana/grafana/assets/1069378/30231085-c55d-4ec6-83ae-00c813f612a3)
- Switch to "Table" view. 
  ![imagen](https://github.com/grafana/grafana/assets/1069378/fed24802-6811-4d30-b7e3-04c3c23c5d20)
- See warning:
  ![imagen](https://github.com/grafana/grafana/assets/1069378/579715ad-799d-4e43-bdfe-bf5f23653769)

![Demo](https://github.com/grafana/grafana/assets/1069378/e4c545c6-f47c-4f71-beb7-cde6d2057679)

Reproduce: https://play.grafana.org/d/cdb29b74-3f7c-4aee-8bd7-99f5897c2950/%2372331-extractfields-with-same-fieldnames?orgId=1

**Comment by svennergr** [comment]
Hey @matyax,

I can't reproduce this with the current `elastic` devenv. Could you check if you can repro and maybe add the relevant steps?

Thanks.

**Comment by matyax** [comment]
@svennergr Updated the issue description.

**Comment by matyax** [comment]
@svennergr That is correct, but 1) it's not a required field in the configuration and 2) even with it configured I can still repro.

![imagen](https://github.com/grafana/grafana/assets/1069378/f5b9f44d-08f9-4752-b88b-1474056a0b0f)

![imagen](https://github.com/grafana/grafana/assets/1069378/ec148b02-b2e8-4630-bdc5-b48f7493aad0)

**Comment by svennergr** [comment]
For context: this looks like a potential issue with the `extractFields` transformation.
https://raintank-corp.slack.com/archives/C02UC0KCSF4/p1692014237412629
