### ISSUE TITLE
[Feature request] `diff` aggregate on singlestat panel

### ISSUE THREAD

**Issue by oliverpool** [grafana/grafana#7234]
Just like https://github.com/grafana/grafana/pull/6740 implemented some aggregates, I think it would be nice to have a `diff` aggregate (which would be `current - first`) for gauges (which may go up and down).

I you are ok with it, I may start a PR with this.

**Comment by oliverpool** [comment]
btw, there is a typo in the [documentation](http://docs.grafana.org/reference/singlestat/#singlestat-panel):

`average` - The average of all the non-null values in the series

=> `avg` should be there instead

**Comment by bergquist** [comment]
@oliverpool a pr would be appreciated.

**Comment by bergquist** [comment]
Closed by #7238
