### ISSUE TITLE
Grafana support for rest api

### ISSUE THREAD

**Issue by ArslanSaleem** [grafana/grafana#7235]
Hi,
Is grafana has support for java rest api as a data source. I developed an Apache Spark and Cassandra RESTful  api but now i want to visualize its data using grafana. Is there any plugin available for grafana to fetch data from REST api.

**Comment by torkelo** [comment]
since there is no single REST api standard for time series metrics, there is no single data source for "REST api". I mean all time series databases uses some form of HTTP/rest.

You can look at this as simple reference implementation:
https://github.com/grafana/simple-json-datasource

**Comment by ArslanSaleem** [comment]
Thanks torkelo, 
It means that if i have a rest api that returns JSON, i can use grafana to visualize its data?
