### ISSUE TITLE
Nested Folders: Select all checkbox bugs when searching

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#72354]
comment in this PR might help understand problems: https://github.com/grafana/grafana/pull/70814

- [x] inconsistent indeterminate state behaviour between tree view and search view (clicking when indeterminate selects/unselects)
- [x] unselecting doesn't always work (e.g. if you select something, search for something else and try to unselect)

**Comment by amy-super** [comment]
Capturing what we discussed for posterity: We'd like to create a standard that clicking the indeterminate checkbox deselects items rather than selects (which is what it's doing today in the tree view).
