### ISSUE TITLE
Elasticsearch: implement cross cluster search

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#72353]
users and customers requested the possibility to use cross-cluster-search: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html

 ~~in general this means that we have access to only a restricted subset of the elastic API. we need to check if that restricted API is enough for grafana or not. i do not remember what minimal-elastic-version is required for using the _field_caps API, maybe we support versions of elastic without _field_caps?
We you can check https://www.elastic.co/support/eol, and if 7.17.x supports _field_caps ..(some initial investigation suggests that it may be enough, but needs more thorough checking)~~
Edit: All versions we support, support field_caps and the metadata field(https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-field-caps.html)https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#supported-elasticsearch-versions

(we need to replace `_mapping` with `_field_caps`, `_field_caps` returns an is-field-metadata, with that we should be able to extract the info that we are currently extracting from `_mapping`)

(requested by the users in https://github.com/grafana/grafana/discussions/56259)

Additional info for local development: https://docs.google.com/document/d/1O95G-VdelmEDpyAQAvR5izzm5EAc8J9Y8qCgvZqXP5c/edit?usp=sharing
Also in this ticket: https://github.com/grafana/grafana/issues/67704

**Comment by JAAnguloCanovas** [comment]
Hi!

Is there any news on this? Where can we see the progress?

Thank you very much for your help!

Best regards

**Comment by adurmax** [comment]
Hello, much appreciate your work on Grafana project. 
I wonder what's an ETA for implementation? I can't find current roadmap to relate.

Thank you again, cheers :)

**Comment by idastambuk** [comment]
Hi @adurmax and @JAAnguloCanovas, this feature is next in our pipeline; however we don't have an exact ETA for it yet. Thanks for your patience!

**Comment by iwysiu** [comment]
Hi, thanks for all the patience! This will roll out in public preview behind the `elasticsearchCrossClusterSearch` feature flag in 11.5.0 and slowly into hosted grafana.
