### ISSUE TITLE
[Bug] Dashboard links don't work with multiple tag entries

### ISSUE THREAD

**Issue by jean-baptiste-manuele** [grafana/grafana#7237]
- Grafana version: 4.1.1
- Datasource: graphite
- OS: CentOS 7

I create a link on dashboard via settings->links->[add link].
I insert some tags to get access to other dashboards.
The dashboards exist and have the right tags.
The link is created but doesn't work.
if i insert only one tag the link behaves like expected.

**Comment by torkelo** [comment]
Does a dashboard exist that have all tags defined (the tag filter requires all tags to exist)

**Comment by jean-baptiste-manuele** [comment]
Yes, I created 3 dashboards with example tag1, tag2, tag3 and put this tags in the link.

For the request /api/search?limit=100&tag=tag1&tag=tag2&tag=tag3 i get an empty result

For the request /api/search?limit=100&tag=tag1 i get 
[{
    "id":1116,
    "title":"Test_dashboard",
    "uri":"db/test_dashboard",
    "type":"dash-db",
    "tags":["DISK","tag1","tag1DISK"],
    "isStarred":false
}]

**Comment by shotmonkey** [comment]
I think I'm encountering this issue from another angle:

I'm trying to add dashboard links using a single tag, where the dashboards I want to display in the links actually have multiple tags.

no dashboard links appear, whether I use one of the two tags they have or both.

I can successfully get dashboard links to appear if I use one tag on both the link and the dashboard itself.

The dashboard links are searching for dashboards with: `/api/search?limit=7&tag=mytag` and returns nothing, but adding a single letter query to this (e.g. `/api/search?limit=7&tag=mytag&query=a`) will make the API return the expected dashboards.

**Comment by torkelo** [comment]
This looks like it's fixed
