### ISSUE TITLE
PromQL parsing (epic)

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#72397]
Summary:
lezer-promql is no longer supported for Grafana's use case, see https://github.com/prometheus/prometheus/pull/11333
We'll need another parsing solution as PromQL evolves.

Links:
https://github.com/grafana/grafana/pull/69656

https://github.com/grafana/grafana/pull/37251

```[tasklist]
### Tasks
- [ ] Remove lezer-promql from renovate: https://github.com/grafana/grafana/pull/69656#issuecomment-1580895139
- [ ] Find new parser, or fork existing
```

**Comment by itsmylife** [comment]
Closing this in favor of this https://github.com/grafana/grafana/issues/77879
