### ISSUE TITLE
Alerting: when specifying template message for an email contact point, the panel's screenshot is no longer sent in the email's body.

### ISSUE THREAD

**Issue by luca131996** [grafana/grafana#72392]
### What happened?

When sending an alert to a contact point via email, no image is sent in the email body if I'm using a template message. However, the Panel's screenshot is sent if I'm not modifying the  "Message" textbox in the contact point.

Example 1:
When sending an alert to a contact point via email, if the "Message" textbox is kept empty the panel's screenshot is sent, embedded in the email body. However, it includes just the last 1 hour of data, even though I'm specifying "last seven days" in the alert editor.
Message textbox:
![image](https://github.com/grafana/grafana/assets/100410429/5e575971-044f-429f-8628-34a711b89981)
Generated E-mail:
![image](https://github.com/grafana/grafana/assets/100410429/12c68c78-f03d-4fc2-af2b-7dbb752b31bb)

Example 2:
When specifying a template message in the "Message" textbox, the message is correctly rendered, but the image is no longer sent in the email's body (even looking at the source HTML code of the email, no img is imported other than the Grafana logo)

Message textbox:
![image](https://github.com/grafana/grafana/assets/100410429/dd982c43-e109-4114-83c3-e0b7500b77ce)
Generated E-mail:
![image](https://github.com/grafana/grafana/assets/100410429/cfd41906-cade-4dca-9474-dcb7dda1d426)

I don't believe there's any problem with my configuration, since the image is sent when I'm not specifying any template message (I have configured GF_UNIFIED_ALERTING_SCREENSHOT_CAPTURE=true).
I already looked at the documentation, and it is not specified how to include images in template messages.

### What did you expect to happen?

A screenshot of the panel is sent with the alert in the email's body, wheter or not a template message is specified for an email contact point.

### Did this work before?

I'm now updating our grafana stack to the new unified alerting, with the legacy alerting it was easy to generate the correct alert message and send the panel's screenshot.

### How do we reproduce it?

1. Run Grafana version 9.5.6.
2. Generate an alert linked to a panel in a dashboard.
3. Generate a contact point (email) and write a template message.
4. Verify that no image is embedded to the email's body.

### Is the bug inside a dashboard panel?

No, the bug is related to unified alerting.

### Environment (with versions)?

Grafana: Docker image with grafana/grafana: 9.5.6 and grafana/grafana-image-renderer 3.6.0, running with Kubernetes
OS: Docker on Linux
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @luca131996,

Thanks for opening this issue.

Grafana's current latest stable version is 10.0.3 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here.

**Comment by luca131996** [comment]
Thank you for the answer @usmangt. I've tried to update Grafana to version 10.0.3, and the behavior is identical to the one with grafana 9.5.6 (see following image).
![image](https://github.com/grafana/grafana/assets/100410429/2702d5a3-008c-421d-8cc8-6404a2bc11ad)

**Comment by rwwiv** [comment]
We don't think this is ideal, but it is a difficult problem to solve. As an interim solution we could instead use attached images when using a custom message template.
