### ISSUE TITLE
hostname is in the format "/account/token", its a single string for hostname, I took reference earlier issue of parsing slash but invain. Please help

### ISSUE THREAD

**Issue by Palrawat** [grafana/grafana#7239]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
please do not open questions on github (it's in the issue template which you seem to have used without reading it or changing it).

http://grafana.org/support/
