### ISSUE TITLE
[Bug] Coloring Background on siglestat panel

### ISSUE THREAD

**Issue by Liugart123** [grafana/grafana#7242]
Hi all, i'm using grafana version 3.1.1 (don't know if this happen on v4) and i discover something weird with the coloring background option. I made a gif to explain what happen. I'm using influxdb as a datasource.

![bug grafana](https://cloud.githubusercontent.com/assets/15464338/21906797/89492ea8-d958-11e6-90b0-7027f5d6e869.gif)

If you see the color on the "Value" checkbox and the color on the "Background" checkbox are different (understand they have to be the same color). I guess the "Value" checkbox is the correct (for me).

**Comment by torkelo** [comment]
strange, unable to replicate:

![image](https://cloud.githubusercontent.com/assets/10999/21920477/9c1b683a-d961-11e6-9793-76c2da6a546f.png)

**Comment by torkelo** [comment]
Can you provide the exact data you had? (the response from your metric query)

**Comment by Liugart123** [comment]
Sure, the exact data i have for that example (GIF) is: 0.89
I change the Unit box as "percent (0.0 - 1.0)" to make this date show as %

**Comment by torkelo** [comment]
yes, I used that as well. I mean the actual data returned from your time series query. 

Can you replicate it again?

**Comment by Liugart123** [comment]
i was looking again and made changes on the example to replicate it. I discover this only happends if you modify the Decimals and make it zero. The actual data returned from my time series query is 0.891.

**Comment by daniellee** [comment]
Looks like this was fixed by #8334
