### ISSUE TITLE
Explore: Long span/resource name labels in TraceQL search are not handled properly in UI

### ISSUE THREAD

**Issue by vainikkaj** [grafana/grafana#72431]
### What happened?

After adding custom OTEL resources to new Search form

![image](https://github.com/grafana/grafana/assets/661992/0bef6489-428b-4f94-9a6d-4027283b8a28)

Long names break UI flow and make the form hard to read

![image](https://github.com/grafana/grafana/assets/661992/39f61859-04fe-4a8c-a544-92ba6a6b1910)

### What did you expect to happen?

Everything to be clear and readable

### Did this work before?

N/A

### How do we reproduce it?

See 'What happened'

### Environment (with versions)?

Grafana: Grafana v10.2.0-128316pre (b019ef9a89)
OS: Linux
Browser: Google Chrome

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @vainikkaj,

Thanks for opening this issue. I am not an expert in using TraceQL (or to say Tempo DS) so will require more step-by-step instructions.

OR

You can try to reproduce this same issue on https://play.grafana.org/ and then share either a screencast or step-by-step instructions.

Thanks

**Comment by usmangt** [comment]
I am triaging it as I was not able to reproduce it but it seems like a possible improvement.
