### ISSUE TITLE
Alerting email notification templates are not wide enough and the "Grouped by" title is confusing when empty

### ISSUE THREAD

**Issue by JDA88** [grafana/grafana#72447]
### What happened?

The width of the text zone of the email template looks to be fixed to 600px which is quite small on modern desktop standard and cause unwanted line return

Furthermore when you disable the "Group by" on the "Notification policie" the folder icon and the "Grouped by" title are still present in the email

### What did you expect to happen?

The width of the text zone should not be fixed and allow to text > 600px
The "Grouped by" title should be removed if the "Group by" option is disable

### Did this work before?

no

### How do we reproduce it?

Send a email notification with a large text and no grouping

### Environment (with versions)?

Grafana: 9.5.7
OS: Docker
Browser: Edge & Chrome + Outlook 365

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @JDA88,

Thanks for opening this issue.

Can you please share a screenshot or a small screencast/gif file so that we can get more clarity?

Thanks

**Comment by JDA88** [comment]
**Alerting rule:**
A simple SQL query that get a value, a title and a instance field

**Notification template:**
A template that display the alert as a list each line begining with a `•`
```
{{ define "message_email_simple_v3" }}
  {{- if gt (len .Alerts.Firing) 0 -}}
    {{- len .Alerts.Firing }} Active:
    {{ range .Alerts.Firing }} 
      • [{{ .Labels.instance }}]: {{ .Labels.title }}
    {{- end -}}
  {{- end -}}
  {{- if gt (len .Alerts.Resolved) 0 -}}
    {{- len .Alerts.Resolved }} Resolved:
    {{ range .Alerts.Resolved }}
      • [{{ .Labels.instance }}]: {{ .Labels.title }}
    {{- end -}}
  {{- end -}}
{{ end }}
```

**Notification policies:**
Basie Email policy with the default  `Group by` set to empty
![image](https://github.com/grafana/grafana/assets/67072186/b96231da-d04e-4804-b66b-47736386cd7c)


**Result email:**

- `Grouped By` Is displayed with nothing behind hit
- The lines are too long for the 600px limit and are displayed on multiple lines (Except for the first one)

![image](https://github.com/grafana/grafana/assets/67072186/08048ada-f9fc-4d8a-8ed1-c46bccabf4e3)

Hope this is more clear. 

Thank you for your time

**Comment by JDA88** [comment]
Thank you for that!
