### ISSUE TITLE
[Bug] Alerting HAS NO VALUE is not working

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#7244]
- What Grafana version are you using?
4.1.1 (same behavior with 4.0.2)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.n
- What did you do?
Created a new dashboard
Created a new graph panel in new dashboard
Created a graphite target query that returned all null values
Created an alert with when sum() of ... "HAS NO VALUE"
Set the "If no data or all values are null" state to "alerting" in the alert
Clicked "Test Rule"
- What was the expected result?
The alert should fire since all values are nulls
- What happened instead?
The alert did not fire during testing (firing:false), it did however work as expected when the dashboard was saved (i.e. it went into "firing" state)

![screen shot 2017-01-12 at 1 26 28 pm](https://cloud.githubusercontent.com/assets/1704368/21909658/b23c947a-d8cd-11e6-8681-5c073854b9eb.png)

**Comment by utkarshcmu** [comment]
Similar to #7149

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/pull/7247

**Comment by mohddanish211** [comment]
Hi, I am still facing issue with HAS NO VALUE condition in Grafana. The alert is not working after receiving null or 0. Grafana version 8.1.
