### ISSUE TITLE
Syntax error in multiple queries when upgrading from version 9.2.3 to 10.0.1.

### ISSUE THREAD

**Issue by evjmp** [grafana/grafana#72460]
### What happened?

I had Grafana 9.2.3 with a set of configured Dashboards. I have upgraded to version 10.0.1, and I am getting a syntax error in multiple queries. The error is always the same:

Status: 500. Message: db query error: pq: syntax error at or near "AS"

![image](https://github.com/grafana/grafana/assets/139141634/b08e3714-87d8-459e-863c-f7e6383fa63c)
![image](https://github.com/grafana/grafana/assets/139141634/789dabe5-999c-4e01-8317-565bf3303834)
![image](https://github.com/grafana/grafana/assets/139141634/699c8ea9-506a-46a6-bdbf-cb5490c6e6c6)

Upon review, I noticed that the Query being executed is missing a closing parenthesis in the timestamp.strftime function, but I am using the same query as before.

### What did you expect to happen?

To function normally, as it did before the update.

### Did this work before?

Yes, it was working with version 9.2.3.

### How do we reproduce it?

1. Create a dashboard with a similar query.

### Environment (with versions)?

Grafana: 10.0.1
OS: Red Hat 7.9
Browser: Mozilla

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Postgres 11

**Comment by evjmp** [comment]
For information, I have reverted to the previous version (v.9.2.3) and now the Dashboard works.

**Comment by codeincarnate** [comment]
Going to close this for now as we haven't had further reports and this appears to be as expected. We can re-open if we get any further info/reports.
