### ISSUE TITLE
[Bug] "Direct link rendered image" shows 404 when using scripted dashboard and http_proxy

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#7246]
Please include this information:
- What Grafana version are you using?
v4.1.0-beta1
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Ubuntu 14.04

- What did you do?
0. Set trace logging on grafana-server, http_proxy, https_proxy. Set no_proxy to server_hostname,localhost,ip. Confirmed these are working with alerting through proxy and database pulls outside proxy.
1. Create a scripted dashboard under /usr/share/grafana/public/dashboards/scripted.js.
2. Browse to http://grafana-site/dashboard/script/scripted.js
3. Click a title of a graph and click "Share"
4. Click "Direct link rendered image"
5. Notice: Browser shows a url such as, http://grafana-site/render/dashboard-solo/script/scripted.js?x=y, y=z,span=2&from=1484264019711&to=1484267619711&var-colo=foo&panelId=2&width=1000&height=500
6. User is shown, "404 page not found"
7. Checking the logs:
t=2017-01-12T16:37:40-0800 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/script/scripted.js?x=y,y=z,span=2&from=1484264019711&to=1484267619711&var-colo=foo&panelId=2&width=1000&height=500"
t=2017-01-12T16:37:40-0800 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/dashboard-solo/script/scripted.js status=200 remote_addr=127.0.0.1 time_ms=2ns size=2352
t=2017-01-12T16:37:51-0800 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/NQOEx2u1N07TYVPv2ZCl.png
t=2017-01-12T16:37:51-0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=user method=GET path=/render/dashboard-solo/script/scripted.js status=404 remote_addr=192.168.1.200 time_ms=10.827µs size=43
8. Note: Rendering a graph from a dashboard that is not from a script is working correctly.
9. Comment out no_proxy, http_proxy, https_proxy and restart grafana-service.
10. Re-attempt steps 2-5.
11. Notice: Image is shown.

- What was the expected result?
User is shown a graph image similar to how a dashboard from the database is generated.

- What happened instead?
   * User is shown, "404 page not found"
   * It appears the log shows an image is rendered at /var/lib/grafana/png, but the image does not exist.  Images do exist for database dashboard direct image renders.
   * Commenting out no_proxy, http_proxy, https_proxy causes scripted dashboard's phantomjs direct images to work correctly.

Let me know if you need more info -- Thanks.

**Comment by torkelo** [comment]
not sure how to get phantomjs to use those environment variables.

**Comment by gerrickw** [comment]
Was poking around phantomJS github issue repo and noticed there were a number of issues surrounding no_proxy for phantomjs, although the last comment on https://github.com/ariya/phantomjs/pull/12863 states 2.1.1 now works with no_proxy environment variable.  Are we using the latest phantomJS build?

**Comment by torkelo** [comment]
then it should work as Grafana 4.x has been using PhantomJS 2.1.14

**Comment by gerrickw** [comment]
I am confused, was this fixed in the latest release? It was mentioned it should work if on phantom 2.1.14, but it was not last I checked in grafana.

**Comment by torkelo** [comment]
Sorry, misread your comment

**Comment by hugohaggmark** [comment]
Grafana doesn't support PhantomJS any longer, so I'm going to close this.

Thank You to you for taking the time to create this issue!
