### ISSUE TITLE
old screenshots on the Explore documentation homepage

### ISSUE THREAD

**Issue by bbrandys** [grafana/grafana#72466]
The screenshot in "To access Explore:" is outdated. 
Please update to the latest version of Grafana and accessing explore.

**Comment by usmangt** [comment]
Hi @bbrandys,

Thanks for opening this issue.

Can you send us the link to the page? Also, send a screenshot of the image so we can know for sure.

**Comment by chauchausoup** [comment]
@usmangt I think @bbrandys  is referring to the screenshots shown in this page.
https://grafana.com/docs/grafana/latest/explore/

**Comment by usmangt** [comment]
@chauchausoup Thank you for the feedback

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by GrafanaWriter** [comment]
Hi @usmangt - this issue is still in Needs triage after two weeks; is there a plan to fix or should we move to backlog?

**Comment by Elfo404** [comment]
@GrafanaWriter created a PR for this in https://github.com/grafana/website/pull/14833, i'm moving this to in review in your board
