### ISSUE TITLE
[Bug] Alert issue (Failed to unmarshal graphite response)

### ISSUE THREAD

**Issue by nspiegl** [grafana/grafana#7248]
Please include this information:
- What Grafana version are you using? : Grafana v4.1.0-beta1
- What datasource are you using?: Graphite
- What OS are you running grafana on?: Ubuntu 14.04.5 LTS
- What did you do?: Added alert to graph
- What was the expected result?: For the alert not to go into an alerting state
- What happened instead?: Alert went into an alerting state

Log Extract:
[Grafana Log.txt](https://github.com/grafana/grafana/files/703815/Grafana.Log.txt)

![metric query](https://cloud.githubusercontent.com/assets/25097788/21922818/7d73b9d8-d9ab-11e6-94f5-aee1b3bee4c1.PNG)

![alert config](https://cloud.githubusercontent.com/assets/25097788/21922774/3acb1d06-d9ab-11e6-8f8b-9f81ddb89e71.PNG)

![expanded test](https://cloud.githubusercontent.com/assets/25097788/21922773/3acb0208-d9ab-11e6-93c2-a485c53ee306.PNG)

![state history](https://cloud.githubusercontent.com/assets/25097788/21922775/3ad0c2f6-d9ab-11e6-905f-8138a9896c20.PNG)

**Comment by torkelo** [comment]
you condition says IS ABOVE 450000  (450K),  but the data is only 60K

**Comment by nspiegl** [comment]
That is correct the data is only 60K so why did the alert go into an "alerting" state. It should only go into an alerting state when it IS ABOVE 450000 (450K). As you can see **it has triggered an alert** and if you check the log you can see an error.

The test shows there **should not** have  been an alert but in fact there is as you can see from the history and the grafana.log

**Comment by torkelo** [comment]
Sorry, read the report wrong. 

Your graphite server seems to be returning invalid json (which is usually doing when it encounters an error). Can you check your graphite error logs? 

What is your Grafana log level? The graphite tsdb query processing should print any marshal errors if you have log level >= Info.

**Comment by nspiegl** [comment]
This is what the Grafana log has in it:

t=2017-01-13T18:31:06+1100 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="MSNSW01-SYD DDB" id=41
t=2017-01-13T18:31:06+1100 lvl=info msg="Failed to unmarshal graphite response" logger=tsdb.graphite error="invalid character '\\u0089' looking for beginning of value" status="200 OK" **body="�PNG**\r\n^Z\n^@^@^@\rIHDR^@^@^AJ^@^@^@�^H^B^^
@^@^@H���^@^@^@^FbKGD^@�^@�^@�����^@^@^E�IDATx���M�Ue^\��sG�▒~\@�|^[kQ�F��N^TY�^Pm,�\"�▒~L^Q٢EH.^\�▒| E!Q3^U�`^D��\"!........ more rubbish

This is what I found in one of the graphite logs (rendering.log):

Fri Jan 13 18:30:18 2017 :: Retrieval of aliasByMetric(cv.summary.ddb.ddbDiskSize.mswa03-per.S.TotalUsedSpaceMB) took 0.006038
Fri Jan 13 18:30:24 2017 :: Retrieval of aliasByMetric(cv.summary.ddb.ddbDiskSize.msnsw1-mv.S.TotalUsedSpaceMB) took 0.002995
Fri Jan 13 18:30:29 2017 :: Rendered PNG in 0.011172 seconds
Fri Jan 13 18:30:29 2017 :: Total rendering time 0.012750 seconds
Fri Jan 13 18:30:29 2017 :: Rendered PNG in 0.012812 seconds
Fri Jan 13 18:30:29 2017 :: Total rendering time 0.015473 seconds
Fri Jan 13 18:30:48 2017 :: Retrieval of aliasByMetric(cv.summary.ddb.ddbDiskSize.mstas1-hba.S.TotalUsedSpaceMB) took 0.002341
**Fri Jan 13 18:31:06 2017 :: Returned cached response in 0.000627**
Fri Jan 13 18:31:10 2017 :: Returned cached response in 0.000649
Fri Jan 13 18:31:16 2017 :: Retrieval of aliasByMetric(cv.summary.ddb.ddbDiskSize.msvic08-cl.S.TotalUsedSpaceMB) took 0.004728
Fri Jan 13 18:32:20 2017 :: Retrieval of aliasByMetric(cv.summary.ddb.ddbDiskSize.msact05-cdc.D.TotalUsedSpaceMB) took 0.002400

So for some reason it seems to return a PNG image instead of JSON and it seems to happen at random, it has also happened with other graphs as well with regards to alerting. 

We are running an old Graphite version, maybe that might be causing it?
graphite-carbon  0.9.12-3
graphite-web 0.9.12

**Comment by nspiegl** [comment]
I think I have found the issue:
https://github.com/graphite-project/graphite-web/issues/576

Looks like its time for me to upgrade our graphite server.

Many Thanks for your help on this and efforts on the Grafana project. Its much appreciated.

**Comment by torkelo** [comment]
ah, the old PNG response from json api issue, that is an old classic graphite bug :)
