### ISSUE TITLE
[Bug] No datapoints in last time with correct range

### ISSUE THREAD

**Issue by cortwave** [grafana/grafana#7251]
- What Grafana version are you using?
Grafana 4.1.1
- What datasource are you using?
InfluxDB 1.1.1
- What OS are you running grafana on?
official grafana docker image (4.1.1-1484211277)
- What did you do?
set up graph with last 1h range
- What was the expected result?
last hour datapoint
- What happened instead?
no datapoints message

For example at 13:15 I'm setting up range to last hour (12:15-13:15 at that moment). Result - no datapoints message. When I set up range as now-1h:now+1h (12:15-14:15 at that moment) it shows datapoints in range now-1h:now(12:15-13:15 at that moment).

now-1h:now+1h (with datapoints in result) request:

http://localhost:3000/api/datasources/proxy/1/query?db=riemann&q=SELECT%20mean(%22value%22)%20FROM%20%22cpu%22%20WHERE%20time%20%3E%20now()%20-%201h%20and%20time%20%3C%201484306313822ms%20GROUP%20BY%20time(5s)%20fill(null)&epoch=ms

now-1h:now (with no datapoints in result) request:

http://localhost:3000/api/datasources/proxy/1/query?db=riemann&q=SELECT%20mean(%22value%22)%20FROM%20%22cpu%22%20WHERE%20time%20%3E%20now()%20-%201h%20GROUP%20BY%20time(2s)%20fill(null)&epoch=ms

Screenshots:

last hour

![image](https://cloud.githubusercontent.com/assets/8936357/21926576/65c314ea-d993-11e6-8ccc-a222f73546f6.png)

now-1h:now+1h

![image](https://cloud.githubusercontent.com/assets/8936357/21926603/8bdad21c-d993-11e6-9ee6-5e911ff9589b.png)

bug reproduces with any profile timezone settings

**Comment by torkelo** [comment]
Probably due to time difference between your InfluxDB server and your browser. 

If you please include InfluxDB response and you browser time (in utc)

**Comment by cortwave** [comment]
Sorry you was absolutely right, my docker containers time was unsynchronized with browser ~30min
