### ISSUE TITLE
Pausing alerts should add an annotation.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#7252]
**Updated 2017-12-19**

When pausing/unpausing an alert we should create an annotation about it for that alert. 

ex

```go
// save annotation
item := annotations.Item{}
annotationRepo := annotations.GetRepository()
if err := annotationRepo.Save(&item); err != nil {
return err
}
```

**Comment by utkarshcmu** [comment]
IMO, if we are annotating pausing, we should annotate un-pausing too. So, that we know for how much time the alerts were paused.

**Comment by bergquist** [comment]
@utkarshcmu when rules are un paused they will go into pending state until executed. Once executed an annotation will be created with the result from the first execution since the alert rule is un paused. 

 So there will be an annotation. But from the alert engine rather then the un pause action.

**Comment by utkarshcmu** [comment]
So, even if the state goes to 'OK' an annotation will be created by alert engine?

**Comment by bergquist** [comment]
No it wont.. your right...

hum hum hum...
This might call for a new alertstate... Not sure.

**Comment by nnedkov** [comment]
Hi @bergquist,

Indeed, it would be very useful to know when an alert was paused. I see this issue was assigned more than a year ago. Has there been any progress?
Cheers

**Comment by orojina** [comment]
@nnedkov @bergquist 
In case you find this useful I created a script to pause and resume alerts. It accepts arguments to add annotations when pausing/resuming alerts. You can put it in a cron job or a pipeline and manage schedules there. As a temporary solution


https://github.com/orojina/grafana-cli

**Comment by armandgrillet** [comment]
This is the case in Grafana Alerting.
