### ISSUE TITLE
[Bug] Graph renders no curve and points

### ISSUE THREAD

**Issue by cortwave** [grafana/grafana#7253]
- What Grafana version are you using?
Grafana 4.1.1
- What datasource are you using?
InfluxDB 1.1.1
- What OS are you running grafana on?
official grafana docker image (4.1.1-1484211277)
- What did you do?
I created graph with all default settings from influxdb as datasource. Datapoints were shown as expected. After I changed time range to last hour, now-1h:now+1h, last 3 hours, last 30 minutes. All was good before 30 minutes range.
- What was the expected result?
Last 30 minutes graph.
- What happened instead?
Graph with no rendered datapoints and curve. But I can select them in graph and see datapoint value (they just not rendered).

![image](https://cloud.githubusercontent.com/assets/8936357/21928191/7099876c-d99a-11e6-96ea-ccec03ac93c8.png)

![image](https://cloud.githubusercontent.com/assets/8936357/21928211/884d5d98-d99a-11e6-9608-75b62192f2d9.png)

I tested this case with both dark and light themes. Browser console has no errors. Chrome Version 55.0.2883.95 (64-bit)

**Comment by torkelo** [comment]
what is your query? do you have a fill(null) in query? then you need a low limit to your group by time interval so that it does not group by time lower than the rate at which you write values. In that case InfluxDB insert null values between points
