### ISSUE TITLE
Transformations: Format Time upkeep/bugs

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#72536]
The [new format time transformer is awesome](https://github.com/grafana/grafana/pull/72319), but needs a little love. Here is a list of the work that needs to be done.

- [x] missing docs
- [x] missing illustration used in new transformers UI
- [x] labeled as in alpha and GA state (this is in conflict according to Mitch
- [x] Mitch asked for an update with a tooltip and link to more docs to help out

**Comment by codeincarnate** [comment]
Moving this over to myself 😄

**Comment by codeincarnate** [comment]
I think the GA state was my accident with what's new, in my haste I copied the wrong line for availability 😬 . I think we can update that one 🙂

**Comment by codeincarnate** [comment]
Draft PR here #72571. One question @bohandley, was curious about sources for illustration. I have a grasp on it, but was hoping to match style if sources otherwise exist. Thanks! 🙏

**Comment by codeincarnate** [comment]
There's a separate process for the what's new GA label so will address that separately.

**Comment by bohandley** [comment]
@codeincarnate considering the illustration, @LudoVio and @catherineymgui, how did you all come up with the illustrations?

I feel something similar to Convert field type would be good, but it looks like the format Format Time transformation could use a brand new one.
![Screenshot 2023-07-31 at 4 18 07 PM](https://github.com/grafana/grafana/assets/25674746/5e93a810-5799-46ac-bde8-7e6099192554)

**Comment by bohandley** [comment]
Considering the tooltip, @mjseaman asked for the following

"In the info tooltip next to Format, I would love a link to the time formats supported by moment.js. Saves me having to google them. An alternative would be to link to our own docs, which link to moment.js."

I would suggest an interactive tooltip with a link embedded. The tip persists long enough for the user to click the link. You might have already seen this but here's an example of an interactive tooltip with a link added. https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx/#L180-L193

**Comment by codeincarnate** [comment]
Awesome, thanks so much @bohandley! 🙏  Definitely agreed on that point, I'll add the tooltip with the link :)

**Comment by catherineymgui** [comment]
> I feel something similar to Convert field type would be good, but it looks like the format Format Time transformation could use a brand new one.

I'm thinking of just smth like this? Similar to yours. If this is good I can send to @LudoVio to add. cc @codeincarnate 

<img width="396" alt="Screenshot 2023-07-31 at 17 15 31" src="https://github.com/grafana/grafana/assets/5264102/55b8c743-c5a7-4c3f-9dd4-af7112ab64d3">

**Comment by codeincarnate** [comment]
Yep looks great!

**Comment by codeincarnate** [comment]
I checked and the what's new was updated to indicate public preview. I've also fixed up that message, currently running that past Quynton now. The changes for that are [here](https://github.com/grafana/grafana/commit/1c81910f5328c2d372ee61aea608cb253e8a6644).

Otherwise added the interactive tooltip and updated docs, going to wait for Ludovic on the image for the transformation.

**Comment by LudoVio** [comment]
https://github.com/grafana/grafana/pull/72673
