### ISSUE TITLE
Grafana On-Call: Latest Docker image broken

### ISSUE THREAD

**Issue by brngates98** [grafana/grafana#72542]
### What happened?

When attempting to update Grafana On-Call with sudo docker-compose pull && sudo docker-compose up-d i receive the following error:

```
Creating on-call_redis_1 ... done
Creating on-call_oncall_db_migration_1 ... done

ERROR: for engine  Container "1129db889dbd" exited with code 1.

ERROR: for celery  Container "1129db889dbd" exited with code 1.
ERROR: Encountered errors while bringing up the project.
```

I deployed a fresh ubuntu server and attempted a vanilla install also, and received the same error on a fresh setup.

### What did you expect to happen?

To update the grafana on-call back end 

### Did this work before?

yes 7 days ago i updated to 1.3.16 

### How do we reproduce it?

1.  sudo docker-compose pull engine && sudo docker-compose up -d 
2. follow instructions for fresh install also errors out when you run sudo docker-compose pull && sudo docker-compose up -d
3.

### Environment (with versions)?

Grafana: 10.0.0.2
OS: Ubuntu Server 22.04
Browser: Google Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @brngates98,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.
