### ISSUE TITLE
Dashboard: Custom variable expansions adding un-necessary escapes

### ISSUE THREAD

**Issue by johnhtodd** [grafana/grafana#72555]
### What happened?

I have created a custom variable called "Country".  The custom variable values (simplified example) are this:

us : |iad|mci|ord|,fr : |cdg|lys|, uk : |lhr|edi|

Goal: to match (via PromQL) three-digit airport codes in my queries using expansion when a particular country is selected. I would like to be able to select multiple countries at once to create an expansion set that is inclusive of all three-letter city codes for all nations that I have selected, based on hand-entered mapping of key:value sets.

This expansion **works correctly when I do not have "Multi-Value" or "Include All" option selected** for the variable.  As soon as I select either of those options in the variable, my queries fail due to what appears to be overly aggressive /unexpected escaping of pipes inside the combined result.  

### What did you expect to happen?

When picking two or more values (fr, us) in my constant variable list, I would expect to see this in the Query Inspector:

`expr:"uptime{loc=~\"|cdg|lys||iad|mci|ord|\"}"`

But instead, looking at the Query Inspector I find this:

`expr:"uptime{loc=~\"(\\\\|cdg\\\\|lys\\\\||\\\\|iad\\\\|mci\\\\|ord\\\\|)\"}"`

For some reason, four backslashes are being added before every pipe. That is causing the query to not match.

### Did this work before?

Unknown if it works on other versions.

### How do we reproduce it?

1. Create a constant variable with syntax similar to mine.
2. Add it to a PromQL query to create an expansion (e.g.: `uptime{sitecode=~"$Country"}` ) 
3. Turn "Multi-Value" on and off and then observe the Query Inspector for what is sent to the database (Expand all) 

### Environment (with versions)?

Grafana: 8.5.5
OS: MacOS 11.7.8
Browser: Chrome 114.0.5735.198

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Not specific to datasource

**Comment by tonypowa** [comment]
thank you for creating this issue @johnhtodd 

tagging the dashboard and metrics' squads for review

**Comment by dprokop** [comment]
@johnhtodd - it seems like you are using quite an old version of Grafana. Any chance you update your instance?

**Comment by dprokop** [comment]
Related and possible solution https://github.com/grafana/grafana/issues/50211
