### ISSUE TITLE
[Feature request] alerting - state history information

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#7257]
ALERTING feature
A nice-to-have would be some more information on the state history tab, eg:
* result from the query when triggered
* button to zoom to this point
* who was notified, how, and status of the notification

**Comment by bergquist** [comment]
Remaning
 * link to when ever an alert was triggerd
 * see who was notified.

**Comment by wei-hai** [comment]
it would be better to include the cause of alert, for example, by indicating whether the alert is triggered by condition, timeout or execution error.

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/8383
