### ISSUE TITLE
Behavior of "serve_from_sub_path" changes in Grafana v10

### ISSUE THREAD

**Issue by gfrankliu** [grafana/grafana#72577]
### What happened?

When using reverse proxy to serve Grafana from a sub path, we've been setting `serve_from_sub_path` to true in Grafana v7, v8 and v9. When upgrading to v10, the behavior of this parameter changes, and now we need to set it to false. Is there a reason to have this behavior change and break the backward compatibility?

### What did you expect to happen?

Keep backward compatibility if possible. We are hoping to keep the same configuration in our environments where we have a mixture of v9 and v10 installations. Is it possible to revert back to the old behavior?

### Did this work before?

Yes in v9 and all earlier versions.

### How do we reproduce it?

1. Test Grafana using v9 and v10, with exact same reverse proxy setup.
2. See the different behavior of `serve_from_sub_path`

**Comment by tonypowa** [comment]
hi @gfrankliu 

thank you for creating this issue

could you give more details about your setup? (safely share more details of the [server] section
what is the behavior of setting serve_from_sub_path  in v10?

**Comment by gfrankliu** [comment]
Hi @tonypowa 

Thanks for the reply! I don't have any special setup (I will post a bit later), just same setup as others reported, eg:

[a community post](https://community.grafana.com/t/problem-with-reverse-proxy-after-update-to-grafana-10-0/89589/2)

[another bug report](https://github.com/grafana/grafana/issues/70110)

The suggested fix in those posts were to change the "serve_from_sub_path" from true to false. I am not sure if this behavior change introduced in v10 was to fix another bug, add a new feature or is just a regression.

**Comment by gfrankliu** [comment]
```
    [server]
    root_url = https://site.com/grafana/
    serve_from_sub_path = false
    #serve_from_sub_path = true
    enforce_domain = false
```

**Comment by gfrankliu** [comment]
Here are some more findings:

If I set `serve_from_sub_path = true` to serve from sub path /grafana and curl test directly against grafana without reverse proxy:

1) In grafana v9 and earlier:
- for UI: curl localhost:3000/grafana and curl localhost:3000/  BOTH works
- for API: curl localhost:3000/grafana/api/.. and curl localhost:3000/api/..  BOTH works

2) in grafana v10
- for UI: curl localhost:3000/grafana works but curl localhost:3000/  gets 301 redirect to /grafana
- for API: curl localhost:3000/grafana/api/.. and curl localhost:3000/api/..  BOTH works

So the behavior change is only for UI , not API.

Now, adding reverse proxy and since reverse proxy strips subpath /grafana, I will see infinite 301 redirects.

**Comment by tonypowa** [comment]
@gfrankliu 

see  https://github.com/grafana/grafana/issues/70110#issuecomment-1597403289

if the solution proposed in the comment does not work for you, I will forward the issue to the back-end team

**Comment by gfrankliu** [comment]
Yes, I've been using the suggestions from those comments for now, but am trying to understand to understand the reason behind this behavior change in v10 that breaks the compatibility. If it is a regression, can it be fixed to help easier transition to upgrade to v10?

**Comment by tonypowa** [comment]
thanks @gfrankliu  for helping us to better understand your inquiry

> the reason behind this behavior change in v10 that breaks the compatibility. If it is a regression, can it be fixed to help easier transition to upgrade to v10?

in order to answer this question, I will forward the question to the back-end team

**Comment by mkuf** [comment]
This does also seem to affect the metrics endpoint. 

When `serve_from_subpath` is enabled, internal requests from e.g. prometheus get redirected to the defined root_url.  
This is causing prometheus to not be able to scrape metrics because it accesses grafana via the kubernetes service name and is then redirected to the public url, which is in our case behind a oauth2 proxy.  

When `serve_from_subpath` is disabled, no redirect is happening and prometheus can successfully scrape the service endpoint. 

`enforce_domain` is set to `false` in both cases. 



We use the grafana helm chart to serve grafana via a subpath. 
The grafana.ini was set to 
```ini
[server]
serve_from_sub_path  = true
root_url = https://host.tld/grafana
```

The ingress was simply configured to serve the subpath like this, without any redirects/rewrites. 
```yaml
ingress:
  enabled: true
  hosts:
    - host.tld
  path: /grafana
```

To work around this behaviour change, we removed the `serve_from_sub_path` from the grafana.ini and set a rewrite-target in the ingress
```yaml
ingress:
  enabled: true
  hosts:
    - host.tld
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  path: /grafana/?(.*)
```
