### ISSUE TITLE
[Bug] 4.1: ES 5.1.1 - Graphs not being drawn with interval set to auto (or 10s) with time range under 3 hours

### ISSUE THREAD

**Issue by dachenbach** [grafana/grafana#7260]
- What Grafana version are you using? 4.1.1-1484211277
- What datasource are you using? Elasticsearch 5.1.1
- What OS are you running grafana on? CentOS 7.2.1511
- What did you do?
   - In a dashboard with several graphs, If I set them to use a 1 minute interval, I can select any time range, and all graphs are drawn properly. If I set any graphs to use 10s (or auto with a time range that uses 10s) and set the time range to anything under 3 hours, graphs no longer draw anything, but the legend updates as I move the cursor around the graph.
- What was the expected result?
   - Graphs should be drawn regardless of interval or time range.
- What happened instead?
   - Graphs aren't being drawn.

Interval set to 1m for all graphs:
![image](https://cloud.githubusercontent.com/assets/19396787/21943013/3c76e012-d984-11e6-957e-f70f3ad5d5fc.png)
![image](https://cloud.githubusercontent.com/assets/19396787/21943027/504773ea-d984-11e6-8536-819cca5dd0aa.png)

Interval set to auto for all graphs:
![image](https://cloud.githubusercontent.com/assets/19396787/21943072/8c6f3074-d984-11e6-9f86-b7f97ef1e47c.png)
![image](https://cloud.githubusercontent.com/assets/19396787/21943131/bf1d94de-d984-11e6-8929-4d973d75cc49.png)

**Comment by torkelo** [comment]
What is the date histogram setting / min doc count, and what is you graph null value option. 

If the date histogram interval is lower than the actual data, the there might be null values between each real value, so no lines get drawn, enable points in graphs display tab to see the points, and either change date histogram options or null value mode, or set lower limit for date histogram auto interval, this can be done below your queries in the date interval option, or you can specify a lower limit in the data source edit page

**Comment by dachenbach** [comment]
My metrics update every 10 seconds, which is indicated by showing points. That said, setting the auto interval to >10s fixed the issue, so maybe it looks like 10 seconds but is slightly over? Changing the null value mode to "connected" fixed it too, but I don't like that enabled. Thanks for the information.

**Comment by jordanarseno** [comment]
We too are getting this behaviour in 4.1 when plotting Line Graph w/ *Group by time interval* left empty. Setting the time interval to the minimum (10m periodicity for us) restores the line graph.

**Comment by torkelo** [comment]
@jordanarseno yes, this is due to grouping by time smaller then there are documents, if your date histogram Min Doc Count option is `0` then elasticsearch will return null buckets for time intervals where there are no documents, so the time series will be filled with null values between each actual value. You can ignore the null values in display option, (set null value option), or change the min doc count option to 1. Or if you know there are ES documents every 1 minute for example you can set a lower limit for the group by time interval with `>1m` (in the group by time option below the queries)

**Comment by jordanarseno** [comment]
I should have mentioned.. we are using InfluxDB as a data source. 

The data we capture is in strict 10 minute intervals down to the second.

In previous Grafana versions we plotted many graphs and never observed this behaviour.. we could always leave the "group by time interval" empty and observe a trending. Only our upgrade to 4.x seems to have caused this (can't say for sure if 4.0 or 4.1 at this time)

**Comment by torkelo** [comment]
Strange, and you haven't  upgraded InfluxDB? What is the graphs null value option (display tab)? 

If you only collect data every 10min interval you should set lower limit on group by time in metrics tab or in data source edit options
