### ISSUE TITLE
[Feature Request] Show computed value for "auto" interval templating variable

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#7262]
It would be nice if the computed value for an "auto" interval templating variable was printed somewhere (maybe in brackets behind "auto"). In case you are using the InfluxDB `difference` function, it might be nice to know for which time interval the difference is computed, when using the variable in the group by time clause.

**Comment by elvarb** [comment]
Also to add to this, be able to scale the auto value. For example if you are viewing a dataset and the auto will be 1m but in some cases that is too small, so you change it to 10m. When you are viewing a longer period with auto it might become 10m there but that is still too small so you change it to 1h.

To be able to have a few auto options would be a nice bonus. For example "Auto", "Auto+" and "Auto++" Especially useful when working with bar charts.

**Comment by daniellee** [comment]
The calculated auto value is now shown in the query editor in the query options section:

![image](https://user-images.githubusercontent.com/434655/98597226-f8f4b880-22d8-11eb-828c-38a911a8d620.png)

Closing this issue as this is implemented.
