### ISSUE TITLE
[Feature Request] Diff based Time series requests

### ISSUE THREAD

**Issue by parkesy** [grafana/grafana#7263]
**Grafana version:** 4.0.1
**Datasource:** InfluxDB
**OS:** Ubuntu16.04 
**What did you do?** I have a number for TS being requested very 2 seconds (refresh trigger by the auto refresh in the application) for a realtime system report. There are about 23 Time series being requested in each report. 
**What was the expected result?** I thought that due to the nature of the requests the code would simply request the difference between what has been already displayed and what is required to be displayed. 
For example; if I last displayed data from time A to B and now I need to display the same data from A to C then I the application would request the new data from B to C and append it to its internal dataframe to create A to C.
**What happened instead?** For each time series and each report refresh, data is being requested from the datasource in its entirety (A-C) . This is very heavy on network I/O and prevents me from using this application as a realtime report system across our environments.

**Comment by torkelo** [comment]
This only works a for a subset of queries.

It does not work for analytical queries that apply a moving average, holt winters forecast, integral functions etc. 

But it does work in many cases, so I think an option to turn it on would be interesting to explore.

**Comment by parkesy** [comment]
Yeah this type of feature would be indescribably beneficial to the framework. For use cases with many reports per view with high density timeseries, grafana would become a viable option for businesses. The current, nice and simple, request the time range again approach make grafana not scalable and greatly impacts browser performance.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
