### ISSUE TITLE
Using "#" character SMTP alert config within grafana.ini

### ISSUE THREAD

**Issue by harriswong** [grafana/grafana#7265]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.1.1

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Debian Jessie 

- What did you do?
I tried to setup the SMTP email alert in the grafana.ini. The SMTP email password has a "#" in it. 

- What was the expected result?
It should authenticate.

- What happened instead?
Failed to authenticate. I believe the "#" needs to be escaped but I can't find a way to escape it in the `.ini` file. Tried '\'. Haven't tested with other special chars. 

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by bergquist** [comment]
Thanks for reporting this!

If the password contains `#` or `;` you have to wrap it with trippel quotes. Ex `"""#password;"""`

Added this note to docs, default.ini and sample.ini

**Comment by lukaszgryglicki** [comment]
Seems like it is not possible to set password with # in provider_config for [[session]] for Postgres.
I was trying ' '' ''' " "" """ etc.

**Comment by daniellee** [comment]
@lukaszgryglicki spaces probably do not work either. We just got a PR merged for the ORM framework that we use in Grafana so I will be fixing this in the near future.

**Comment by lukaszgryglicki** [comment]
OK no problem, I've updated all my passwords.
I've seen comment few lines above about enclosing password with triple """ for [database] section, so I expected something similar for [sessions] - but it didn't work.
Thanks for the info.

**Comment by tle-huu** [comment]
What if it contains double quote?
