### ISSUE TITLE
Loki Explorer: show context bad request when label contains escape character

### ISSUE THREAD

**Issue by phantomedc** [grafana/grafana#72676]
### What happened?

loki explorer show context bad request when label contains escaped character:

the original query like:
![image](https://github.com/grafana/grafana/assets/15801693/05452be0-da3b-41ad-ad94-cc80f868e088)
the raw request like:
![image](https://github.com/grafana/grafana/assets/15801693/037c32f5-15f7-42c6-8334-2eadf4e43037)

but when show context, the raw request like:
![image](https://github.com/grafana/grafana/assets/15801693/0f530b44-9b4d-48c1-b9d3-64a06fda81aa)
![image](https://github.com/grafana/grafana/assets/15801693/d81ffdd7-5d92-4793-8545-417ec600561f)
![image](https://github.com/grafana/grafana/assets/15801693/a59956b6-ebed-45da-8bfb-d13208b099e9)

### What did you expect to happen?

show context logs

### Did this work before?

works when label does not contain escape character
![image](https://github.com/grafana/grafana/assets/15801693/c48e06c0-d897-4168-9237-74ab5b437577)

### How do we reproduce it?

1. build a label with escape character for logs
2. output log to loki
3. search this log with line filter
4. click show context

### Is the bug inside a dashboard panel?

in explorer module

### Environment (with versions)?

Grafana:9.1.0
OS:windows 10
Browser: chrome 114.0.5735.199 x64

### Grafana platform?

A downloaded binary

### Datasource(s)?

Loki

**Comment by svennergr** [comment]
Hey @phantomedc,
unfortunately Grafana 9.1.0 is not supported for bug fixes. Could you please check if you can reproduce this on a more recent version such as Grafana 10?

Thank you,
@svennergr

**Comment by phantomedc** [comment]
> Hey @phantomedc, unfortunately Grafana 9.1.0 is not supported for bug fixes. Could you please check if you can reproduce this on a more recent version such as Grafana 10?
> 
> Thank you, @svennergr

i tried it on Grafana 10，it was solved, thank you, we will upgrade to the latest version
