### ISSUE TITLE
[Bug] Regression when displaying multiple annotation tags from single database field

### ISSUE THREAD

**Issue by amotl** [grafana/grafana#7267]
Dear @torkelo, @bergquist and the whole Grafana team and contributors,

first things first: Thanks for conceiving this great project and the excellent work on it!

We experienced a minor issue when upgrading from version 3.0.1 to the brand new 4.1.1 (currently updated on dev by pulling from Docker Hub) and can confirm the issue is a regression from 3.0.1 by switching back and forth again. It's probably related to #4550, but different (inverse) to #2903. The current behavior seems to be like the issue in #1474, again.

The facts:
- What Grafana version are you using?
   > 4.1.1 `"buildInfo":{"buildstamp":1484210883,"commit":"v4.1.1","env":"production","hasUpdate":false,"latestVersion":"4.0.2","version":"4.1.1"}`
- What datasource are you using?
   > InfluxDB 1.1.1
- What OS are you running grafana on?
   > Mac OS X / Boot2Docker version 1.13.0-rc7
- What did you do?
   > Create an annotation with multiple space- or comma-separated values inside the single field `"tags"`. Annotation setup was done as usual with basic column mappings (Title: `title`, Tags: `tags`, Text: `text`) and a regular query of `"SELECT * FROM area_33_node_1_events WHERE $timeFilter"`.
   >
```
> select time, title, tags from area_33_node_1_events
name: area_33_node_1_events
---------------------------
time			title	tags
1484526744697682416	123	one two three
1484526956596704950	123	one,two,three
```
- What was the expected result?
   > We can confirm Grafana 3.0.1 did a split on the value in the `"tags"` field. It worked with space and comma as separator as resolved per #1474:
   > ![image](https://cloud.githubusercontent.com/assets/453543/21967952/c5771b54-db8f-11e6-8b94-cfcfc9ee66c0.png)
- What happened instead?
   > Grafana 4.1.1 shows a different behavior, it seems to skip the split and uses the field value verbatim: 
![image](https://cloud.githubusercontent.com/assets/453543/21968111/7d40b9ec-db91-11e6-99e1-4b998ad4c1d0.png), 
![image](https://cloud.githubusercontent.com/assets/453543/21968113/82fe0a60-db91-11e6-9e73-db2ec440423e.png)

With kind regards,
Andreas.

**Comment by amotl** [comment]
Maybe @adrianlzt could help out here?

**Comment by adrianlzt** [comment]
In this [PR](https://github.com/grafana/grafana/pull/7289) I have splitted in different _bubbles_ when the value has commas.
But I don't know if is a good idea to split by spaces.

**Comment by amotl** [comment]
Thanks a bunch for the quick fix!
