### ISSUE TITLE
Debian Package: Grafana Service Fails to Start (grafana.db)

### ISSUE THREAD

**Issue by gesker** [grafana/grafana#72684]
### What happened?

On fresh install of Debian 12 grafana fails to start. Syslog indicates:

```
Error: ✗ failed to connect to database: failed to create SQLite database file "/usr/share/grafana/grafana.db": open /usr/share/grafana/grafana.db: read-only file system
```

Have confirmed that the filesystem is not read-only.
/usr/share/grafana directory created by install package is owned by root and permissions are set to 755

### What did you expect to happen?

grafana-server to initialize and start without error.

### Did this work before?

yes

### How do we reproduce it?

1. Fresh install of Debian 12 (Bookworm)
2. Add grafana repoistory ```deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main```
3. apt install grafana
4. systemctl start grafana-server

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.0.3
OS: Debian 12 (Bookworm)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by evan-chaney** [comment]
What happens if you do `sudo touch  /usr/share/grafana/grafana.db` ?

**Comment by gesker** [comment]
perfect!
