### ISSUE TITLE
[Bug] Regression when displaying annotations as table

### ISSUE THREAD

**Issue by amotl** [grafana/grafana#7268]
Dear @torkelo, @bergquist and the whole Grafana team,

along #7267, we found another thing to be broken in 4.1.1 compared to 3.0.1: When trying to display annotations as table, nothing shows up. We just tested it against the very same InfluxDB database instance (identical data).

The facts:
- What Grafana version are you using?
   > 4.1.1 `"buildInfo":{"buildstamp":1484210883,"commit":"v4.1.1","env":"production","hasUpdate":false,"latestVersion":"4.0.2","version":"4.1.1"}`
- What datasource are you using?
   > InfluxDB 1.1.1
- What OS are you running grafana on?
   > Mac OS X / Boot2Docker version 1.13.0-rc7
- What did you do?
   > Create table panel with no metrics and "*Table Transform: Annotations*". Annotation setup was done as usual with basic column mappings (Title: `title`, Tags: `tags`, Text: `text`) and a regular query of `"SELECT * FROM area_33_node_1_events WHERE $timeFilter"`.
   >
```
> select time, title, tags from area_33_node_1_events
name: area_33_node_1_events
---------------------------
time			title	tags
1484526744697682416	123	one two three
1484526956596704950	123	one,two,three
```
- What was the expected result?
   > The annotation table was propagated with appropriate content from the database. We can confirm it worked in Grafana 3.0.1 by switching back and forth again.
- What happened instead?
   > Grafana 4.1.1 displays an empty table just showing the table headers "Time", "Title", "Text" and "Tags".

With kind regards,
Andreas.

**Comment by bergquist** [comment]
Thank you for reporting this!

It will be available in our nightly release and 4.1.2 (if and when we release it. might skip ahead at release 4.2.0 first)
