### ISSUE TITLE
Service Graph: Changing filters do not run the query automatically

### ISSUE THREAD

**Issue by Mkrummz** [grafana/grafana#72685]
### What happened?

when I use the regex pattern ```service =~ xxx```
it tells me the service is not found. In order to get it to actually search with a regex pattern I have to click out of the box and press refresh. This is not intuitive.

### What did you expect to happen?

I do the regex expression and it tells me to press enter and then the service graph refreshes 

### Did this work before?

unknown

### How do we reproduce it?

1. got to explore 
2. select tempo datasource
3. click on the service graph tab
4. select something to filter on
5. change the = to =~ 
6. type in a regex expression

### Environment (with versions)?

Grafana: Cloud 10.1.0
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Tempo

**Comment by L-M-K-B** [comment]
@Mkrummz This issue is related to Tempo and therefore I'm going to hand it over to @grafana/observability-traces-and-profiling.

**Comment by aocenas** [comment]
I think in general the common behaviour is that you set your filter/query/options and have to run/refresh the query to see the effect. Not sure if `it tells me the service is not found` means that something was run before or if that was from different query. We should at least take a look that the behaviour is consistent with other datasources.
