### ISSUE TITLE
[Feature request] Button for enable/disable vertical scrollbar in alert list

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#7269]
**Grafana version:** 4.1.1
**Datasource:** Prometheus
**OS:** Debian Jessie
**What did you do?** I have an alert list in my dashboard with last 3 alerts and I would like to hide the scrollbar from the alert list. The scrollbar looks ugly on my TV, where is playlist of my dashboards. (screenshot)
**What was the expected result?** I would like to show last 3 alerts in a box without scroll bar
**Solution:**  I suggest to create a function, for hide or unhide the scrollbar. 

![screenshot_20170116_112126](https://cloud.githubusercontent.com/assets/8748774/21979361/e6853aca-dbde-11e6-8a7d-21f8267b3224.png)

**My solution:**
I deleted "_overflow-y: scroll;_". 
```
.panel-alert-list {
       #overflow-y: scroll;
}
```
_When I will need a dashboard with scrollbar and dashboard without scrollbar, I will need a function to enable or disable it._ 

Thank you and sorry for my English..

**Comment by torkelo** [comment]
this should be auto, strange
