### ISSUE TITLE
Dashboards: Inspect > Data does not permit series selection when there are multiple time series

### ISSUE THREAD

**Issue by hilgarj** [grafana/grafana#72694]
### What happened?

[grafana-inspect-bug.zip](https://github.com/grafana/grafana/files/12231449/grafana-inspect-bug.zip)

In play.grafana.com, go to the time series graphs example, simple graph.
Click on three dots, then Inspect > Data.
A pop-up window appears.
Expand the Data Options
Below "Show data frame" click on the downward-pointing arrow in order to choose the desired time series.
The pop-up window vanishes.

This behavior also happens in our Grafana instance.
I have only tested this with the time series visualization.

### What did you expect to happen?

Expected behavior is for the pop-up window to remain and display a drop-down list of available time series.

Note that if I use alternates to mouse use, such as use of TAB, SPACE, arrow key, then and ENTER, then the expected results do  occur!!

### Did this work before?

No

### How do we reproduce it?

1. Follow steps in What Happened.
2.
3.

### Environment (with versions)?

Grafana: 10.0.0
OS: Ubuntu 20.04.6
Browser: Edge 115.0.1901.183 running on Windows 10 21H1

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
thank you for creating this issue @hilgarj 

can you reproduce it with another browser
I could not repro it on Firefox 115.0.3 (64-bit)

![play-series](https://github.com/grafana/grafana/assets/45235678/e8e1c50b-39b9-484a-b04d-c6293d8eb7f1)

**Comment by hilgarj** [comment]
Hi Tony(?),

Admittedly, this was diagnosed on my work computer where they have tinkered with the environment a little bit (Group Policy and what-not). So I tried it just now on my clean home PC. Windows 10.0.19045 Home Edition. FF 116.0 (I upgraded to the most recent Firefox version).

Still, the exact same issue of the disappearing window occurs when I click on the place where I would get to choose the time series.

Regards,
John Hilgart
Global Digital Services Internet Web Security and Visibility

Phone: +1 973 245-7078, Email: ***@***.***
Postal Address: BASF Corporation, 100 Park Avenue, Florham Park, NJ 07932, USA
***@***.***
BASF Corporation

From: tonypowa ***@***.***>
Sent: Thursday, August 3, 2023 5:38 AM
To: grafana/grafana ***@***.***>
Cc: John M Hilgart ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [grafana/grafana] Dashboards: Inspect > Data does not permit series selection when there are multiple time series (Issue #72694)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

thank you for creating this issue @hilgarj<https://github.com/hilgarj>

can you reproduce it with another browser
I could not repro it on Firefox 115.0.3 (64-bit)

[play-series]<https://user-images.githubusercontent.com/45235678/258069846-e8e1c50b-39b9-484a-b04d-c6293d8eb7f1.gif>

-

**Comment by tonypowa** [comment]
thank you for the details John

Could you increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors?  More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by hilgarj** [comment]
Were the logs I sent helpful or were there no errors there? I've never really looked at Grafana logs.

Any ideas how to continue? Shall I poll more people to see who sees the error and who does not to find the commonalities?

Regards,
John Hilgart
Global Digital Services Internet Web Security and Visibility

Phone: +1 973 245-7078, Email: ***@***.***
Postal Address: BASF Corporation, 100 Park Avenue, Florham Park, NJ 07932, USA
***@***.***
BASF Corporation

From: tonypowa ***@***.***>
Sent: Friday, August 4, 2023 4:28 AM
To: grafana/grafana ***@***.***>
Cc: John M Hilgart ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [grafana/grafana] Dashboards: Inspect > Data does not permit series selection when there are multiple time series (Issue #72694)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

thank you for the details John

Could you increase the verbosity of the Grafana server logs<https://grafana.com/docs/grafana/latest/administration/configuration/#level> to debug and note any errors? More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

-

**Comment by hilgarj** [comment]
Hopefully this link to a Google Drive file with the recording will be accessible for you:
https://drive.google.com/file/d/1uJVudeZVXoa0rXkJgRzkVphGvzJzuE34/view
I will look at the developer's console next and let you know.

**Comment by hilgarj** [comment]
One thing that pops out in Developer Tools is that event returns with a 422 status unprocessable entity about three times.
<img width="515" alt="event-422-Capture" src="https://github.com/grafana/grafana/assets/97632117/5c1a97a5-9476-404a-87a0-f63934e5f2ae">

**Comment by hilgarj** [comment]
Yeah you're right.

**Comment by dprokop** [comment]
Should be fixed with https://github.com/grafana/grafana/pull/73557
