### ISSUE TITLE
Alerting: status code 500 received with log Error in expanding template

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#72708]
### What happened?

We see log 
![image](https://github.com/grafana/grafana/assets/36128312/e4f1278d-3a98-47f5-b6e2-7c7afc91a4bf)
Is this caused by user behavior or server error? If user behavior, server should not return 500.

### What did you expect to happen?

correct status code

### Did this work before?

not sure

### How do we reproduce it?

Need RCA for this

### Environment (with versions)?

Grafana: 9.4.12
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
note for the reviewer: see https://github.com/grafana/grafana/issues/72764

**Comment by rwwiv** [comment]
The `humanize...` template functions are sourced from upstream Prometheus, so an issue would need to be opened upstream here: https://github.com/prometheus/prometheus/issues

As a quick fix you can add an `if` check around this value to check it for `nil`.

**Comment by rwwiv** [comment]
We could also ensure values are non-`nil` before they are passed to the template function.

**Comment by MingjieZhuEmily** [comment]
Hi, so is this server error? It sounds like it's caused by user data being nil. If this is the case correct error message should be provided instead of returning 500.
