### ISSUE TITLE
[Bug] Automatic Importing of Dashboards through /var/lib/grafana/dashboards.

### ISSUE THREAD

**Issue by gerritavenant** [grafana/grafana#7270]
It could be that this is not a bug but just my understanding, but this is wat I am doing:
I am using Grafana v4.1.0 (commit: 98b648d), with an influxdb database and Telegraf.

When I export my dashboard, and I want to recreate my Grafana setup on a different machine, I put my dashboard.json in /var/lib/grafana/dashboards, and enable this feature in the grafana.ini. On the new machine, the dashboard is automatically available and when I open it, but I get the error: 
```
Templating init failed
Datasource named ${DS_MYDB} was not found
```
When I import the the dasboard via the Import feature, it is setup correctly - using the same .json file.

**Comment by torkelo** [comment]
Dashboards exported via UI needs to imported via UI. 

Export is for sharing dashboards to another instance (or shared on grafana.net).  

If you just want to save dashboard to json file use "View JSON" from dashboard cogs menu.
