### ISSUE TITLE
[Bug] Elasticsearch Singlestat Panel Unique Count on string field

### ISSUE THREAD

**Issue by JohhnyP** [grafana/grafana#7271]
Also posted on #4231 but creating a new issue since the precision threshold it's not the source of this (i think)

Please include this information:
- What Grafana version are you using? **4.1.1**
- What datasource are you using? **Elastic 5**
- What OS are you running grafana on? **CentOS 7**
- What did you do? 
Created a singlestat panel in order to count the unique occurrences of a string field for the past X minutes.
In Kibana you can simply count unique text fields like this

![Kibana](http://i.imgur.com/bjpRcbK.png)
**Kibana Request**
`{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*",
            "analyze_wildcard": true
          }
        },
        {
          "range": {
            "timestamp": {
              "gte": 1484300616021,
              "lte": 1484301516021,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "1": {
      "cardinality": {
        "field": "gameDsc.keyword"
      }
    }
  }
}`

**Kibana Response**
`{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 15812,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "1": {
      "value": 12
    }
  },
  "status": 200
}`

I can't find a way to do the same in Grafana.
I think the groupBy is not needed in this case and there is no way to remove it.

![Grafana](http://i.imgur.com/0PPgH63.png)

**Comment by torkelo** [comment]
currently the singlestat and graph panel only support time series data so the date histogram is required. 

But you can change the date histogram interval to 1y which basically does the same as removing it (ie only creating one bucket).

**Comment by dkulichkin** [comment]
@torkelo what if my data is spread for more than a year? I can't specify currently anything longer than "1 year" interval to emulate one bucket for calculating an absolute total

**Comment by torkelo** [comment]
does 2y not work?

**Comment by mihirthatte** [comment]
@torkelo it doesn't seem to be working for me as well. I tried with 1 year, 2year, and 1M intervals. The results are just not correct - 

Grafana result - 
![snip 2018-02-16 12 26 37](https://user-images.githubusercontent.com/10900218/36320577-a9e4c338-1314-11e8-88e5-13f27a8bc8dd.png)


Actual Elasticsearch result - 
![snip 2018-02-16 12 22 17](https://user-images.githubusercontent.com/10900218/36320473-507509f2-1314-11e8-990f-78d306a93003.png)

**Comment by torkelo** [comment]
A bug in elasticsearch then ?

**Comment by nbraem** [comment]
Elasticsearch doesn't support year as an interval:
https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units

But you can use days: e.g. "730d" for 2 years.

This workaround works for me. Use Unique Count as metric, a large number of days as interval. You'll get one value in your time series, so you can then use "Current", "Average" or "Total" stat, to get the total unique count over the selected time range.

**Comment by manojpardeshi** [comment]
+1 I need this feature.

**Comment by benjoz** [comment]
+1 need this as well

**Comment by M0rdecay** [comment]
+1 I need this too

**Comment by mathieu-rossignol** [comment]
+1 Yes workaround is working, but it just so strange, took me one hour to have a single correct metric displayed and finally come to this place :(. Bad for feeling about the product when somebody trying to do his first dashboard with ES....Thank you for the workaround.

**Comment by StefanosHP** [comment]
+1 to have this

**Comment by duylong** [comment]
Even if a solution has been brought, it is a shame that this ticket is closed, because we can still improve the operation of the Singlestat.

**Comment by montanaflynn** [comment]
This was really confusing for me to figure out, finally finding this github issue witht he workaround got it working as expected. I think the issue should be re-opened and real unique count single stat counting should be added to grafana.

**Comment by shamsunisha** [comment]
@torkelo Even with the workaround, unique count in grafana is not matching it with the ES.
for example with the interval 730d and current. if i search the dashboard with the template variable as "aaa". and time filter as 6 months, then current filter bring me data as "0" in singlestat. but it should be "1" if i select "total" instead of "current" then i see as "1" not "0" Kibana shows correct data in metric. If i select 1 year time filter,  then i see current as "0" Total as "1"

For the second application if i select "bbb"  from template variable and apply time filter as 1 year, with Current it shows "1"  and "2" for Total.
Eventhough it is for one qpplication only.  dont understand why unique count is showing it as "2" not "1".
I checked it in kibana  metric 1 year or 6 months data is showing correct . i validated with search query and from application itself.
So Data is mismatching it with Grafana and Kibana.
Can you please reopen this issue and validate from your end again.
