### ISSUE TITLE
Epic: Unify sharing options

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#72716]
### What

We are focussing on increasing the adoption of sharing options in dashboards. The key goals are to:

- Promote the act of sharing
- Craft a streamlined and simple experience of the sharing dialogue that is focused on user needs rather than the features themselves

### Requirements & Caveats
* Should we account for import dashboards as part of the sharing flow? Right now it takes you to a diff page and it doesn't allow you to go back

### Task list

- [x] [Unification of cards components for public dashboards, reporting, library panels, playlists, snapshots](https://github.com/grafana/grafana/issues/74053)
- [x] https://github.com/grafana/grafana/issues/62376
- [x] #78316
- [x] #77560
- [x] #77562

### Resources
[Product DNA](https://docs.google.com/document/d/1KsOho6-7FiHXwH991_15VAiUn4W9WhNGoFKfkVrupHE/edit?usp=sharing)

**Comment by evictorero** [comment]
Design is done, we are implementing it in this [issue](https://github.com/grafana/grafana/issues/85240)
