### ISSUE TITLE
Epic: Increment adoption of the sharing button

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#72714]
### What
Improve the adoption of sharing dashboards
### Requirements & Caveats

Task list

- [x] https://github.com/grafana/grafana/issues/71539
- [x] #72741
- [x] Add analytics to the sharing button to have a benchmark

### Resources
Links to Product DNA, Figma, design docs…

**Comment by natydej** [comment]
[Panel](https://ops.grafana-ops.net/d/e6ec0bf0-c369-414a-b99e-619c6d0efa70/dashboards-sharing?orgId=1&viewPanel=26&from=1705146361512&to=1707738361512) for the share option analyitics
