### ISSUE TITLE
[Bug] Missing graph edit tabs

### ISSUE THREAD

**Issue by Joannou1** [grafana/grafana#7272]
Initially, the tabs would show normally.
At some point in the last day, the tabs no longer show.
Appending &tab=axes for example, will load the axes tab, but I can't see any other tabs.

Here's a JS error in the console:

`2boot.b8fccc44.js:35 Error: [ngRepeat:iexp] Expected expression in form of '_item_ in _collection_[ track by _id_]' but got 'tab in::ctrl.editorTabs'.
http://errors.angularjs.org/1.5.8/ngRepeat/iexp?p0=tabNaNn%3A%3Actrl.editorTabs
    at https://*redacted*/public/app/boot.b8fccc44.js:33:9703
    at Object.compile (https://*redacted*/public/app/boot.b8fccc44.js:38:8302)
    at $ (https://*redacted*/public/app/boot.b8fccc44.js:34:14198)
    at S (https://*redacted*/public/app/boot.b8fccc44.js:34:7803)
    at S (https://*redacted*/public/app/boot.b8fccc44.js:34:7934)
    at S (https://*redacted*/public/app/boot.b8fccc44.js:34:7934)
    at S (https://*redacted*/public/app/boot.b8fccc44.js:34:7934)
    at S (https://*redacted*/public/app/boot.b8fccc44.js:34:7934)
    at N (https://*redacted*/public/app/boot.b8fccc44.js:34:6736)
    at https://*redacted*/public/app/boot.b8fccc44.js:34:9817`

And here's what it looks like:
![db6b5](https://cloud.githubusercontent.com/assets/997747/21989759/033800ee-dbc1-11e6-93b9-6a16642f7340.png)

Version: 4.1.1
Data Source: InfluxDB
OS: Ubuntu

**Comment by torkelo** [comment]
Installed any plugins? Does this happen in all browsers? And it just started appearing? So it did work before with same version?

**Comment by Joannou1** [comment]
No plugins, I tried with FireFox, same issue.
And yep, I imported a dashboard from another grafana 4.1.1 on a different server (which does show the tabs at the moment).

Both of the Grafana installs are a few days old at most.
Creating a new dashboard doesn't fix it as well.

**Comment by torkelo** [comment]
Unable to replicate this, must be something specific with your install as thousands have already downloaded 4.1.1 and no other reports on missing tabs :( 

do you have any proxy infront of grafana that might be causing issues?

**Comment by Joannou1** [comment]
Sorta, it's an Nginx port proxy, so we can have a subdomain for the site.
Although I just heard from a friend that it was working earlier this morning.

**Comment by Joannou1** [comment]
Things got a bit weirder, said friend can still edit fine and has the tabs.
I asked him to log in with my account and he can also see the tabs.

Just tried with IE and Edge as well.
Also just tried with my laptop, with different browsers and on my neighbors wifi (completely different ISP).

Hands are being thrown in the air lol.

**Comment by torkelo** [comment]
closing this, if you identify anything that we can do let me know and I will open it again

**Comment by duckman** [comment]
I know this is closed but I had this issue and it seems to have gone away when i disabled cloudflare's auto minification setting. So Joannou1, if you use cloudflare try that out.

**Comment by Joannou1** [comment]
That worked, @duckman - thanks!
@torkelo - Any idea how to get around this without disabling minification for the whole site?

**Comment by torkelo** [comment]
No, grafana already is minified and optimized, the cloud flare minification must be corrupting something

**Comment by Wundark** [comment]
If the JS/CSS is already minified, could the filename not include **.min.** in there? Cloudflare will attempt to detect if the check the filename first to test for evidence of minification and will not attempt to minify the JS/CSS if **.min.** is in the file name.

If you need any more compatibility/integration information with Cloudflare, please let me know.

**Comment by torkelo** [comment]
It has a hash in the name, and should be easy for cloudflare to detect that it is minified. Is there no option to disable this cloudflare feature?

**Comment by Wundark** [comment]
A hash in the file name doesn't necessarily mean that the file is minified. It would require more processing power to: Read the JS, determine if it is minified, if minified: skip, if not minified: minify. The _determine if it is minified_ step can take a lot of time and can slow down the page loading time. A file name check is much quicker and can provide a more valid answer.

Whatever JS builder you are using, would it not be possible to add **.min.js** after the build and minification is complete?

**Comment by torkelo** [comment]
sure that would be easy
