### ISSUE TITLE
SegmentFrames unavailable

### ISSUE THREAD

**Issue by michiel2002v** [grafana/grafana#72738]
### What happened?

I would like to create a QueryEditor for my datasource plugin. In doing so, I looked around on grafana for components that seemed most convenient for me to use in the Query Editor. Through GrafanaLabs Storybook, I came across all the possible components that could be used. Unfortunately, I wanted to try SegmentFrame, but it is not importable.... Yet for almost all types of Segments, these frames are used.
I am using version 10.0.3 of grafana/ui.
What can I do to solve this?

### What did you expect to happen?

.

### Did this work before?

.

### How do we reproduce it?

just try to import a SegmentFrame from grafana/ui

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by academo** [comment]
Hi @michiel2002v `SegmentFrame` is a helper variable for the storybook stories and not a re-usable component. You can see it defined in several stories [here](https://github.com/search?q=repo%3Agrafana%2Fgrafana%20SegmentFrame&type=code) and it is not always the same.

You can use the storybooks code as inspiration and directly use the other `Segment*` components that are exported inside `@grafana/ui` such as `SegmentAsync`, `Segment`, `SegmentSection` and `SegmentInput`
