### ISSUE TITLE
Failed to send alert notifications

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#7273]
Hey,

Please include this information:
- What Grafana version are you using?
Version 4.1.1
- What datasource are you using?
InfluxDB & Cloudwatch
- What OS are you running grafana on?
Centos 6
- What did you do?
I tried to configure Grafana to send alert email notifications but it didn't work.
1. First I've configured the Grafana.ini file with the following parameters:
[smtp]
enabled = true
host = email-smtp.us-east-1.amazonaws.com:587
user = XXXX
password = XXXX
;cert_file =
;key_file =
skip_verify = true
from_address = admin@grafana.localhost

2. Restarted the Grafana-server service
3. Added new notification email - my work email.
4. Tried to send a test notification to my email.
5. Received the error : "Failed to send alert notifications"
6. Tracked the Grafana log and found the following error:
t=2017-01-16T15:53:03+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="gomail: could not send email 1: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: admin@grafana.localhost"
t=2017-01-16T15:53:03+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=84.111.60.122 time_ms=1.345µs size=48

Here are some images regarding the configurations setting and error outputs:

![image](https://cloud.githubusercontent.com/assets/24862189/21990214/a474369e-dc16-11e6-8952-59b3f2dfc422.png)

![image](https://cloud.githubusercontent.com/assets/24862189/21990238/bb76e2b0-dc16-11e6-8683-cd82ddd3ee3c.png)

**Comment by torkelo** [comment]
your smtp server is not allowing emails being sent from "admin@grafana.localhost", change the from address to an allowed from address
