### ISSUE TITLE
Audit data sources

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#72757]
Go through and check the status of our data sources that are being handed over.
Can use the [plugin evaluation criteria](https://docs.google.com/document/d/1Us-WHcRLdFklGuTPMlFbmv2A6fyGModzadwytusxaX0/edit) checklist.

---

- [x] Postgres `review done, all that's missing is either tracked in another issues already`
- [x] MySQL `complete, nothing stands out as needing immediate work`
- [x] GitHub
- [x] GoogleSheets
- [x] Zabbix
- [x] JSON
- [x] CSV

**Comment by gabor** [comment]
we already familiarized ourselves with these datasources, closing the issue.
