### ISSUE TITLE
ID 260523: [Keyboard Navigation - Simon -Annotations]: Focus is lost after selecting the "Deploys" checkbox under "Annotations" screen.

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#72750]
### **User Experience** :  
Keyboard dependent users might get disoriented if focus gets lost on selecting the checkbox and they would need to navigate extra steps to regain the focus on desired control.
 
_Note: User credentials should NOT be included in the bug._

### Repro Steps: 
1. Open #Url: [play.grafana.org](https://play.grafana.org/) Sign in with valid credentials. "Home" page appears. 
2. Navigate to the left navigation bar and select the "Dashboard" button.  New page appears, Select the "Playlists" tab item. 
3. Navigate the "Playlists" tab.  
4. Navigate to one of the created playlists and select "Start Playlist" button. 
5. Navigate the controls of "Start Playlist" pop-up 
6. Make necessary changes and select the "Start Lobby" button. 
7. Navigate the lobby page which appears. Verify the issue

**Actual Result:** 
Issue: Focus is lost after selecting the "Deploys" checkbox under "Annotations" screen. 

**Observation:** 
After selecting the "Deploys" checkbox focus is not moving to 'Deploy' checkbox, it is getting lost and on pressing tab focus is moving to other control such as "Outages" checkbox under "Annotations" screen. 

**Expected Result:**

After selecting the "Deploys" checkbox, the focus should remain on the same checkbox, instead of getting lost or invisible.

### **Severity:**
`SEV3`

### **Area:**
`Dashboard Annotations`

**Comment by ckbedwell** [comment]
This appears to be fixed as of Grafana 10.2.0.
