### ISSUE TITLE
Add new graph to existing dashboard via API

### ISSUE THREAD

**Issue by alyan2008** [grafana/grafana#7275]
Hi

I am trying to add new graph to my dashboard in Grafana via API but it just replace the dashboard (previous graphs were removed). I have specified the "id" of the dashboard which should be updated and "overwrite" parameter was set to "true" (I have cheked - "overwrite: false" but I have got error - 412).

So, the question is - how can I add one new graph to existing dashboard via API?

**Comment by torkelo** [comment]
You should just be able to add the panel json to the dashboard api, and then use the save dashboard api. That is what the frontend does. You need to add it to dashboard model (so keep the current panels, otherwise you will remove all panels)

**Comment by utkarshcmu** [comment]
You can do this using import and export commands of https://github.com/utkarshcmu/wizzy
