### ISSUE TITLE
Extract SQL data sources from core Grafana

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#72759]
Look into how to externalize data sources by initially:
- Keeping in same repo
- Cutting core Grafana deps

for reference, the epic dealing with this for the test datasource: https://github.com/grafana/grafana/issues/68973

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/72892
- [ ] https://github.com/grafana/grafana/issues/72893
- [ ] https://github.com/grafana/grafana/issues/77629
```

**Comment by gabor** [comment]
mysql is done, and postgres looks like it will wait a longer term, i think we can close this one and just use the https://github.com/grafana/grafana/issues/72892 to track the postgres postgres.

(if anyone would prefer to keep this alive i can of course reopen it)
