### ISSUE TITLE
humanize: can't convert template.Value to float

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#72764]
### What happened?

Alert annotation `AlertValues` contains Go template that calls [humanize](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#humanize) on a value and the following error happens:

```
 level=error msg="Error in expanding template" error="failed to expand template '{{- $labels := .Labels -}}{{- $values := .Values -}}{{- $value := .Value -}}{{ with $values }}\n{{ range $k, $v := . }}\n   Provider: {{ $v.Labels.provider }}\n   Value: {{ humanize $v }}\n{{ end }}\n{{ end }}': error executing template __alert_MyAlertName: template: __alert_MyAlertName:4:13: executing \"__alert_MyAlertName\" at <humanize $v>: error calling humanize: can't convert template.Value to float"
```

This is the value of the annotation:

```
{{ with $values }}
{{ range $k, $v := . }}
   Some_label: {{ $v.Labels.some_label }}
   Value: {{ humanize $v }}
{{ end }}
{{ end }}
```

The value is a number.

### What did you expect to happen?

The value from $values is humanized.

### Did this work before?

N/A

### How do we reproduce it?

1. Create alert with annotation that contains Go template code that uses humanize function
2. Reference the annotation from the notification template
3. Trigger the alert to generate a notification

### Environment (with versions)?

Grafana: 10.0.2

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
thank you for creating this issue @gtirloni 

the team will get back to you with next steps

note for the alerting team: see related issue https://github.com/grafana/grafana/issues/72708
