### ISSUE TITLE
State timeline collapses short states on big time ranges

### ISSUE THREAD

**Issue by tekert** [grafana/grafana#72775]
### What happened?

![grafanaissue](https://github.com/grafana/grafana/assets/9638444/940e0a6c-985c-497d-9af5-430fadaf45bd)

### What did you expect to happen?

Have an option so that short timelapses of data are not collapsed on big timeframes, for example, showing a pixel representing that data is there.
Edit: for example choosing a state to prevail over all others when merging pixels at big timeframes.

### Did this work before?

No

### How do we reproduce it?

1. Have a time series like this `[<many zeroes>, 1 to 10 ones every second, <many zeroes>, repeat]`
2. Use a Timeline to spot on and off trends over the last days, weeks or months.

### Environment (with versions)?

Grafana: Grafana v10.0.1 (5a30620b85)
OS: Windows 10
Browser: Firefox

### Grafana platform?

A downloaded binary

### Datasource(s)?

Prometheus

**Comment by leeoniya** [comment]
we should probably clamp the minimum size down to 1px

**Comment by whimSYZ** [comment]
Hi! I'm someone new who wants to start on contributions to Grafana. Has this issue been fixed?

**Comment by leeoniya** [comment]
i dont think so, feel free to pick it up :)
