### ISSUE TITLE
[Question] Alert notify only once ? 

### ISSUE THREAD

**Issue by xudawei** [grafana/grafana#7277]
In the latest Version .  I am interesting in how the alert work ?  Just send only once notification to webhook when it was firing unit metrics is 'OK' .  What would grafana do if send failed . maybe something wrong in webhook.  Lost it?
Why doesn't  grafana send more the one time of notification?

**Comment by torkelo** [comment]
Grafana sends notifications on state changes, so OK -> Alerting, Alerting -> OK,  OK -> NoData, etc

**Comment by saikatharryc** [comment]
in this case we wont get notification, when needed, say the when percentage if gets more than 80%, i need to send a webhook notification.
in this case state change does not help really.
