### ISSUE TITLE
[Feature request] Support "min_doc_count" for "Group by Terms" of Elasticsearch Backend

### ISSUE THREAD

**Issue by frostynova** [grafana/grafana#7278]
**Grafana version:** 4.1.1
**Datasource:** Elasticsearch 5.x
**OS:** CentOS 7.2
**What did you do?** We want to add a table to show the slowest http request from elasticsearch. But do not want to see those requests which count below 100
**What was the expected result?** "Group by Terms" has a "min_doc_count" option
**What happened instead?** This option only support "Group by Date Histogram"

**Comment by torkelo** [comment]
There is such an option, just click the options link (interval)   to expand options on the date histogram row

**Comment by frostynova** [comment]
@torkelo I know "Date Histogram" has this option, but what i want is "Terms" also support it.

**Comment by torkelo** [comment]
ah, sorry misunderstood
