### ISSUE TITLE
The Grafana variable queries the response data from the VictoriaMetrics, which contains data outside of this time range, and querying through Grafana explore is work

### ISSUE THREAD

**Issue by kubeop** [grafana/grafana#72782]
### What happened?

The Grafana variable queries the response data from the VM, which contains data outside of this time range, and querying through Grafana explore is work

### What did you expect to happen?

The Grafana variable queries the response data from the VM only containing data within this time range

### Did this work before?

yes

### How do we reproduce it?

1./api/datasources/uid/P1809F7CD0C75ACF3/resources/api/v1/series?match%5B%5D=kube_pod_info%7Bjob%3D%22kube-state-metrics%22%2C%20cluster%3D%22k8s%22%2C%20namespace%3D%22monitoring%22%7D&start=1691039225&end=1691041025

2.This data is historical data
        {
            "__name__": "kube_pod_info",
            "namespace": "monitoring",
            "cluster": "k8s",
            "job": "kube-state-metrics",
            "instance": "172.30.190.26:8443",
            "pod": "node-exporter-9rpbd",
            "container": "kube-rbac-proxy-main",
            "created_by_kind": "DaemonSet",
            "created_by_name": "node-exporter",
            "prometheus": "monitoring/k8s",
            "prometheus_replica": "prometheus-k8s",
            "uid": "83543ceb-b0a8-49ca-a3c3-d88cc266afa8"
        },
3.

### Environment (with versions)?

Grafana: 9.5.7
OS: 
Browser: chrome 115
VictoriaMetrics： 1.91.2

### Grafana platform?

None

### Datasource(s)?

victoriametrics

**Comment by zuchka** [comment]
sorry, you'll need to bring this issue to the VM folks ❤️
