### ISSUE TITLE
legend current shows empty - v4.1.1

### ISSUE THREAD

**Issue by anudeepmk** [grafana/grafana#7280]
First of all I am very new to grafana. I am using v4.1.1
My setup is as follows:
Grafana, collectd and graphite on the same server.Grafana is feeded by graphite
Collectd server listens from multiple collectd clients
I’ve setup dashboards for cpu, nginx status on all servers.
I am unable to see the legend for “current” but I can see legends for max, min, avg

All my machines are on debian jessie

Please advise!!

<img width="709" alt="screen shot 2017-01-17 at 5 17 50 pm" src="https://cloud.githubusercontent.com/assets/20853848/22021905/159d6a08-dcd9-11e6-8afa-56e3a8f34d01.png">

**Comment by torkelo** [comment]
add a now delay (in dashboard settings). The reason current is not showing might that graphite is returning null for the last data point as it has not been reported yet. You can go into dashboard settings and specify a now delay to compensate 

![screen shot 2017-01-17 at 14 18 04](https://cloud.githubusercontent.com/assets/10999/22021875/ccec9e14-dcbf-11e6-8956-d63d14feeb88.png)

**Comment by anudeepmk** [comment]
Still its the same.
I added the now delay.The other legends do show.

My storage-schemas.conf for collectd

[collectd]
pattern = ^collectd.*
retentions = 10s:1d,1m:7d,10m:1y

and the Interval from collectd clients is 10s.
Am I missing anything?
<img width="833" alt="screen shot 2017-01-17 at 5 31 23 pm" src="https://cloud.githubusercontent.com/assets/20853848/22022347/032c402c-dcdb-11e6-90d7-a563a803d24d.png">

**Comment by torkelo** [comment]
Can you open chrome dev tools / network tab and look at the raw response from your Graphite query?

**Comment by anudeepmk** [comment]
it gives kind of this response

1484661030], [2889678848.0, 1484661040], [2889777152.0, 1484661050], [2933350400.0, 1484661060], [2889789440.0, 1484661070], [2880450560.0, 1484661080], [2880262144.0, 1484661090], [2880258048.0, 1484661100], [2880348160.0, 1484661110], [2931331072.0, 1484661120], [2880016384.0, 1484661130], [2879913984.0, 1484661140], [2879881216.0, 1484661150], [2879905792.0, 1484661160], [2880352256.0, 1484661170], [2927423488.0, 1484661180], [2880466944.0, 1484661190], [2880159744.0, 1484661200], [2880106496.0, 1484661210], [2880131072.0, 1484661220], [2880057344.0, 1484661230], [2880643072.0, 1484661240], [null, 1484661250], [null, 1484661260], [null, 1484661270], [null, 1484661280], [null, 1484661290], [null, 1484661300], [null, 1484661310], [null, 1484661320], [null, 1484661330], [null, 1484661340], [null, 1484661350], [null, 1484661360], [null, 1484661370], [null, 1484661380], [null, 1484661390], [null, 1484661400], [null, 1484661410], [null, 1484661420], [null, 1484661430]]}]

I do not know if I gave you the proper response :)

**Comment by torkelo** [comment]
it looks like Graphite returns a bunch of null values for the last ~30

**Comment by anudeepmk** [comment]
could you please advise on this regard?
Do I need to tweak config for graphite or collectd?

**Comment by torkelo** [comment]
I would check your graphite server time, make sure your graphite server uses UTC time zone, and make sure your browser time is in sync

**Comment by anudeepmk** [comment]
Yes , My graphite server uses "Etc/UTC" timezone , but my browser and grafana server are in local time zone(UAE).
Pls advise! I really need to set this thing up and running

**Comment by anudeepmk** [comment]
I changed grafana server time in dashboard to use the default , still no luck!

**Comment by anudeepmk** [comment]
Below are the carbon config files

/etc/carbon/storage-schemas.conf

[carbon]
pattern = ^carbon\.
retentions = 60:90d

[collectd]
pattern = ^collectd.*
retentions = 10s:1d,1m:7d,10m:1y

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d

------------------------------------
/etc/carbon/storage-aggregation.conf

[min]
pattern = \.min$
xFilesFactor = 0.1
aggregationMethod = min

[max]
pattern = \.max$
xFilesFactor = 0.1
aggregationMethod = max

[sum]
pattern = \.count$
xFilesFactor = 0
aggregationMethod = sum

[default_average]
pattern = .*
xFilesFactor = 0.5
aggregationMethod = average

-----------------------------------------------

Could you suggest me on this?

**Comment by torkelo** [comment]
not sure I have time to help more, maybe try the mailing list for help? 

http://grafana.org/support/

**Comment by anudeepmk** [comment]
Sure I will do that.
Thank you!
