### ISSUE TITLE
[Bug] Shrinking/resizing panels with mouse 

### ISSUE THREAD

**Issue by rterrettaz** [grafana/grafana#7281]
Hi, 
With the previous version of Grafana, when I resize a panel with the mouse, it was fixed.
Now, the width of the panel is "magneted" on 1 or 2, etc... columns.
I want to display on the same row 8 panels, with the same width... 
I tried to modify in panel json, but it don't work. How to proceed ?
Thank You very much for your answer.

- Grafana version : 4.0.2
- Datasource : Zabbix

**Comment by torkelo** [comment]
The panel layout is a grid of 12, and a panel can be 1 wide, so you can have 12 panels in a row. 

The snap to grid is so that panels can easily be aligned

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/22031222/569a3444-dce0-11e6-86b7-ea7b881c1a7f.png)

**Comment by rterrettaz** [comment]
Thanks a lot for your quick reply, but I wish that my panels measure 1.5 wide columns. and not span 1 or span2 columns.
thank you

**Comment by rterrettaz** [comment]
Hi, 

Thanks a lot for your quick reply, but I wish that my panels measure 1.5 wide columns. and not span 1 or span2 columns.
Before the update, i can resize each panel with my mouse, or the span value in the json panel.

Now, with 4.0.2, the width of each panel is forced on 1 or 2, etc… columns.

thank you

Romain

 

 

De : Torkel Ödegaard [mailto:notifications@github.com] 
Envoyé : mardi 17 janvier 2017 18:12
À : grafana/grafana
Cc : rterrettaz; Author
Objet : Re: [grafana/grafana] [Bug] Shrinking/resizing panels with mouse (#7281)

 

 <https://cloud.githubusercontent.com/assets/10999/22031222/569a3444-dce0-11e6-86b7-ea7b881c1a7f.png> image

**Comment by torkelo** [comment]
that is not possible currently. Maybe when we redo the grid / layout system sometime next 1-2 years

**Comment by rterrettaz** [comment]
sorry to insist, but this feature was working on the V3. 
Do you agree? 
On the top line, each Panel is 1 column. On the bottom line, we see that we can set the width as you like.
Thank you very much for your answer.
![image](https://cloud.githubusercontent.com/assets/20288589/22068013/e170e5a0-dd93-11e6-878a-a828137a54e0.png)

**Comment by torkelo** [comment]
that was a bug in v3 that allowed that, fixed in v4. Sorry if this causes you issues. But enforcing panel width to align with grid is important.
