### ISSUE TITLE
[Feature request]Add play slide show (auto slide) mode in kiosk status

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7283]
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS

When the dashboard is in kiosk status, make each graph fill the screen and display them like slide show, instead of put them in one screen.

**Comment by bergquist** [comment]
Show one panel at the time as a slideshow is an interesting idea.
