### ISSUE TITLE
[Feature request] Row and/or Column styles in Table

### ISSUE THREAD

**Issue by cwesterfield** [grafana/grafana#7286]
Couldn't find this anywhere else so I'll request it.

When mapping a great many values (temp sensors in a server), you may need to set each row with its own threshold. As is, this is only possible with columns. Is it possible to make column styles selectable for either column OR row when you add a new one?

In my example, each Temp has a different threshold, which is not possible when using the "Time series aggregation" option. http://imgur.com/a/izxvi

**Comment by cr42** [comment]
+1
This would help in displaying many metrics with different thresholds #7126

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.
