### ISSUE TITLE
[Feature request] Is grafana support elasticsearch alert?

### ISSUE THREAD

**Issue by YunSangJun** [grafana/grafana#7287]
Is grafana alerting engine support elasticsearch data soures?

http://docs.grafana.org/alerting/rules/
https://github.com/grafana/grafana/issues/5893

**Comment by bergquist** [comment]
Not yet.

Dupe of #5893

**Comment by rwagner-inf** [comment]
Hi guys!

Is there any estimate for grafana to work with alerts for elasticsearch?
