### ISSUE TITLE
[Accessibility reflow issue] - Explore page has a minimum width of 600px causing a horizontal bar for smaller screens (MAS ID: 259081) 

### ISSUE THREAD

**Issue by ckbedwell** [grafana/grafana#72879]
**Steps to reproduce:**
Go to the Explore page. Resize screen to less than 600px. See horizontal scrollbar.

**Actual Result**:
Horizontal scrollbar appears on the Explore page.

**Expected Result**
The content should reflow vertically so that users using smaller screens or screen magnifying software, etc. do not have to scroll horizontally to access all information. 

![image](https://github.com/grafana/grafana/assets/6906380/9f53fd97-6073-4c42-a243-209a36193fc9)

**Comment by ckbedwell** [comment]
I spoke to @Elfo404 about this issue last Friday and it was pointed out to me that when this issue was filed, it wasn't taken into account for the query being run and a data visualisation present. Often queries will return data tables as their visualisations and tables are exempt from needing to avoid horizontal flow as they can increase in complexity rather than reduce it with keeping horizontal scrolling.

With that said, we agreed this issue will stay open and it will be reconsidered whether the Query editor form without a visualisation present could be improved with having reduced horizontal scroll at smaller viewports.

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
