### ISSUE TITLE
[Feature Request] Switch org using API

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#7288]
I am trying to use `http://localhost:3000/profile/switch-org/2` via CURL but getting 404 back. Looks like this URL needs cookie information to work. 

Anyway, it would be great if a user can switch org using an api.

**Comment by torkelo** [comment]
Should work using basic auth with /api/user/using/:orgid

**Comment by utkarshcmu** [comment]
Thanks @torkelo , it works! 👍
