### ISSUE TITLE
templating dashboard with opentsdb DataSource

### ISSUE THREAD

**Issue by NitinRanjan** [grafana/grafana#7292]
I want to use one value of one template variable in other.

**Comment by utkarshcmu** [comment]
See `Nested Templating` under https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/opentsdb.md

**Comment by torkelo** [comment]
Yes, this can be done

**Comment by NitinRanjan** [comment]
when i am doing that i am getting this error:
Template variables could not be initialized: undefined

i am doing it like this:
tag_values(apc.dbConnections.Connections, node, setup=$setup)

**Comment by utkarshcmu** [comment]
which version of Grafana are you using?

**Comment by utkarshcmu** [comment]
https://github.com/grafana/grafana/pull/7208

**Comment by NitinRanjan** [comment]
3.1.1

**Comment by utkarshcmu** [comment]
This issue was fixed 8 days back. It will be available in 4.2.0 or use the master branch!

**Comment by NitinRanjan** [comment]
ok thnx

**Comment by NitinRanjan** [comment]
It is not working after using 4.2 also.
out of these fubctions:
metrics(prefix)     tag_names(cpu)      tag_values(cpu, hostname)   suggest_tagk(prefix) suggest_tagv(prefix)

only these are working for me:  
metrics(prefix) suggest_tagk(prefix) suggest_tagv(prefix)
