### ISSUE TITLE
[Bug] [AWS Cloudwatch] It is not possible to get a single tag value by its key

### ISSUE THREAD

**Issue by chrootLogin** [grafana/grafana#7294]
It seems that it is not possible that you can get single tag values from AWS cloudwatch.

Please include this information:
- What Grafana version are you using?
4.2
- What datasource are you using?
CloudWatch and Graphite
- What OS are you running grafana on?
Docker on CentOS
- What did you do?
I tried to create a template variable with the content of the EC2 instance name tag. I tried different queries but it didn't work. The only thing I found out was that I can get the indexes by their id, as example:
```
ec2_instance_attribute(eu-central-1, Tags[0].Value, {"instance-id": ["$instanceid"]})
ec2_instance_attribute(eu-central-1, Tags[1], {"instance-id": ["$instanceid"]})
```
But the order isn't the same all the time, so this is no solution. 

- What was the expected result?
I can get the value from an single ec2 instance tag by the name of the key. I want something like this:
```
ec2_instance_attribute(eu-central-1, Tags[Name].Value, {"instance-id": ["$instanceid"]})
```

- What happened instead?
I can only get all tags of an EC2 instance as JSON object, but I'm not able to get only one tag.
In the end I want the value of the tag with the key "Name", in the following example "models-int-p".

## Some screenshots
![bildschirmfoto_2017-01-18_17-40-46](https://cloud.githubusercontent.com/assets/4862947/22075245/83bc6aca-ddab-11e6-925f-f621a3e2bf61.png)
The identifier of our systems is the AWS EC2 Instance Id which I can get from Graphite. The JSON with the tags from AWS is displayed weird.

![bildschirmfoto_2017-01-18_17-41-52](https://cloud.githubusercontent.com/assets/4862947/22075244/836b356a-ddab-11e6-8e40-3ca4672bf063.png)
Here you can see the query. It seems that Grafana gets some JSON object from AWS.

Thanks for fixing that in advance.

**Comment by torkelo** [comment]
The syntax is like this: 

```
ec2_instance_attribute(us-east-1, InstanceId, { "tag:Environment": [ "production" ] })
```

**Comment by chrootLogin** [comment]
@torkelo But I have the Instance Ids already. I want the according name tag (or another one) from an Instance Id. 
As you can see in the first thread I want to do something like this:

> `ec2_instance_attribute(eu-central-1, Tags[Name].Value, {"instance-id": ["$instanceid"]})`

But this seems not supported at the moment.

**Comment by torkelo** [comment]
No it's not supported. If you created another variable that contain tag names then you could ec2_instance_attribute(eu-central-1, $myOtherVariable, {"instance-id": ["$instanceid"]})

**Comment by mdeora** [comment]
@chrootLogin did you find any workaround to this ?

**Comment by chrootLogin** [comment]
No, I ended up with writing a python script which creates one dashboard per server via the JSON REST API.

**Comment by paco3346** [comment]
I just opened a PR to address this. #8307

**Comment by sksiit** [comment]
@chrootLogin Could you please share that python script with us?

**Comment by chrootLogin** [comment]
@sksiit Unfortunately I can't, because it's a huge mess. But I can share what I did: I created a sample dashboard through the Grafana GUI, then I exported the JSON of it and transformed it into a python object. Then I wrote some code to modify this object according to the server config. This object then gets uploaded via a grafana API key.

To walk through the AWS instances you can look at this script: https://github.com/SchweizerischeBundesbahnen/aws-tools/blob/master/aws-jinja2.py
