### ISSUE TITLE
CanCAD: File Import - file browser

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#72945]
Add file browser to file import button and allow contents to be stored appropriately. Consider working off of examples of import already present in the code, for example:

![Image](https://github.com/grafana/grafana/assets/60050885/f482b960-5d1b-4724-bdca-660b5f97f6d9)

**Comment by rwwiv** [comment]
Grafana has a [FileUpload](https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-fileupload--basic) component that gives us the button, and we can do what we need to with the file after that.
