### ISSUE TITLE
Organizations: when change current organization, `Location` header contain an absolute URL

### ISSUE THREAD

**Issue by kirychukyurii** [grafana/grafana#72968]
### What happened?

When change organization,  `Location` response header contain info about an absolute URL. 
But with configured reverse proxy there is an issue - we receive redirect to `localhost:3000` instead of `https://sub.example.com/grafana/?orgId=5`, from which user can't get a response:
```
> GET /grafana/?orgId=5 HTTP/1.1
> Host: sub.example.com
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/8.2.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx/1.24.0
< Date: Sat, 05 Aug 2023 20:33:18 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 61
< Connection: keep-alive
< Cache-Control: no-store
< Location: http://localhost:3000/grafana/?orgId=5
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< 
<a href="http://localhost:3000/grafana/?orgId=5">Found</a>.
```

### What did you expect to happen?

`Location` contains relative link to redirect when changes organization:
```
> GET /grafana/?orgId=5 HTTP/1.1
> Host: sub.example.com
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/8.2.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx/1.24.0
< Content-Type: text/html; charset=utf-8
< Content-Length: 61
< Connection: keep-alive
< Cache-Control: no-store
< Location: /grafana/?orgId=5
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< 
<a href="/grafana/?orgId=5">Found</a>.
```

### Did this work before?

Not sure.

### How do we reproduce it?

1. Insert into Grafana config: `root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana`
2. Configure NGINX reverse proxy:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location ~ ^/grafana(/?)(.*) {
        rewrite ^/grafana(/?)(.*) /$2 break;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
   }
}
```
3. Create multiple organizations in Grafana Admin 
4. Try to change current organization in Grafana Admin

### Environment (with versions)?

Grafana: 10.0.2-1
Browser: Microsoft Edge Version 114.0.1823.82 (Official build) (64-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by mildwonkey** [comment]
@kirychukyurii 

We recently updated the documentation and tutorial on running Grafana behind a proxy - can you verify that you have the required configuration for the reverse proxy? You shared the configured root URL, but that's not the only setting that you need: 

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#root_url
https://grafana.com/tutorials/run-grafana-behind-a-proxy/

We use GitHub for tracking issues and feature requests; The [Grafana Community](https://community.grafana.com/) is a better place to ask questions or for support.
