### ISSUE TITLE
[Bug] Graph rendered differently 4.0.2 vs 4.1.x

### ISSUE THREAD

**Issue by jkv** [grafana/grafana#7297]
- What Grafana version are you using?
4.0.2 vs 4.1.0 and 4.1.1
- What datasource are you using?
graphite
- What OS are you running grafana on?
ubuntu 12.04
- What did you do?
Upgraded grafana from 4.0.2 to 4.1.1
- What was the expected result?
The graphs in the newer version have a lot of holes in the data. If I downgrade back to 4.0.2 the holes disappear.
- What happened instead?
There are holes of missing data in the newer version.

**Old:**
<img width="1322" alt="old" src="https://cloud.githubusercontent.com/assets/385531/22087444/1594cb8c-de32-11e6-885e-5a14a0ef6f25.png">
metric1: stats.timers.serverX.service_name.latency.mean
metric2: summarize(averageSeries(timeShift(stats.timers.serverX.service_name.latency.mean, '7days')), '1min', 'avg', false)

**New**
<img width="1325" alt="new" src="https://cloud.githubusercontent.com/assets/385531/22087443/15360886-de32-11e6-9ae1-b6bd605f154a.png">
metric1: stats.timers.serverX.service_name.latency.mean
metric2: summarize(averageSeries(timeShift(stats.timers.serverX.service_name.latency.mean, '7days')), '1min', 'avg', false)

**Comment by torkelo** [comment]
Can you show the data returned from your query? (Open chrome dev tools network tab). 

What is your graph display option `Null value` (in display tab). Is stack enabled?

**Comment by jkv** [comment]
@torkelo Ah that was it. The `Null value` option defaults to `Connected` in 4.0.x and to `Null` in 4.1.x. Was that on purpose?

Thanks!

**Comment by torkelo** [comment]
Yes, but only default for new panels, existing dashboards should not be affected, unless maybe manually crafted json dashboards that did not have a option defined for null value
