### ISSUE TITLE
Request for ASP MVC 5 sample in C# with grafana

### ISSUE THREAD

**Issue by weedkiller** [grafana/grafana#7298]
Hello, this is a request for a sample to learn gafana in the ASP community, and port to grafana

**Comment by torkelo** [comment]
Use a metrics library, like https://github.com/etishor/Metrics.NET or similar that can send metrics to Graphite, Prometheus or InfluxDB. 

Then download Grafana http://grafana.org/download/  add your data source and start adding graphs

**Comment by weedkiller** [comment]
Not sure why this was closed, it suggests a patch fix to make it work.

My point is simply that you have many samples for other languages, with the exception of .NET ASP MVC!

**Comment by torkelo** [comment]
Patch for what? The docs site? We do not have any examples for metrics collection / library. 

I definitely would like a tutorial for how get started with metrics library for. NET and how to get important metrics for ASP.NET but it's bit out of scope for this repo.

**Comment by Larry57** [comment]
You can use the SimpleJSON datasource and study this [git repo](https://github.com/GoldenCrystal/aspnetcore-grafana-simplejson-backend) as an example :

**Comment by weedkiller** [comment]
@torkelo I am hoping you will take this request a little more seriously for the sample.

@Larry57 many thanks, I tried the sample, since its static text data, how would I generate the data that maybe stored from sql server, how can I send it in a format that conforms to grafana? is there a small checklist on what I need to do to pump custom KPI data.

Also how did you relay the user or security or session context from ASP to grafana? was this done just as a general dashboard? I am trying to ensure the asp user is able to view this basd on his role

```
target =>
						{
							DataSeriesGenerators.TryGetValue(target.Target, out var dsg);
							return (Name: target.Target, Repository: dsg);
						}
```

**Comment by torkelo** [comment]
??? Not sure what your asking : trying to do.

This issue was a question for help how to instrument MVC app and send data to a TSDB (Grafana is not a time series database)

**Comment by salimi-hamza** [comment]
Hello, I have a project where I should display the data stored in influxdb in grafana using asp dot net MVC, I don't have any idea how can retrieve data from influxdb in an MVC architecture?

**Comment by marefr** [comment]
@salimi-hamza Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

I would guess just google asp.net mvc influxdb would give you a lot of information. Maybe this could be useful? https://www.app-metrics.io/reporting/reporters/influx-data/

**Comment by weedkiller** [comment]
@salimi-hamza I am in the same boat, there is no proper reference sample for C# ASP with grafana. I would love to showcase to my team how this could be used, but there is simply too steep a learning curve, and no reference sample to follow

**Comment by salimi-hamza** [comment]
@weedkiller Hi, I find a library called Vibrant https://github.com/MikaelGRA/InfluxDB.Client/tree/master/samples/Vibrant.InfluxDB.Client.SimpleSample
I find it a good example to start with influxdb .

**Comment by fasteddys** [comment]
Hello @salimi-hamza @weedkiller I have a similar issue, where I want embed Graphana `inside/with ASP MVC core app`, but the guidance is limited, a sample would have been a great start.

I saw sailimi to do it with a basic ASP MVC view, since its mainly HTML Layouts

**Comment by balajisiva123** [comment]
How to create application like Graphana dashboard at simple level using c# mvc in vs?Looking for guide
