### ISSUE TITLE
ui: when the value within options is a Boolean,the Select component fails to display the initial value.

### ISSUE THREAD

**Issue by chenyingkeai** [grafana/grafana#72982]
### What happened?

I'm developing a data source plugin using Grafana-UI, and I encountered a problem with the Select component. Specifically, when the value within options is a Boolean, the Select component fails to display the initial value.

### What did you expect to happen?

If I use strings or numbers instead of Booleans for the value within options, everything functions as expected

### Did this work before?

When I was developing plugins using Angular, I did not encounter this issue.

### How do we reproduce it?

const checkedGroup = [
    { label: '是', value: true },
    { label: '否', value: false },
];
<Select
    onChange={(value, event) => onChangeQuerySelect(value, event, 'checked')}
    options={checkedGroup}
    value={query.checked}
    width={8}
/>

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Docker

**Comment by tolzhabayev** [comment]
Moving to @grafana/grafana-frontend-platform

**Comment by tskarhed** [comment]
@chenyingkeai Have you considered using a RadioButtonGroup for this use case? It fits better with Boooleans.

**Comment by tskarhed** [comment]
I tried with the options in your example

```
<Select
onChange={...}
options={checkedGroup}
value={checkedGroup[0]}
/>
```

This seemed to work. Is `query.checked` a `SelectableValue`, or just a boolean? You need the entire object for it to be selected.

**Comment by ashharrison90** [comment]
believe this is working as expected. if you still feel like there's a problem and can provide more information please leave a comment and we'll reopen the investigation 👍
