### ISSUE TITLE
[Feature Request] Option to disable dashboard dropdown in nav-bar

### ISSUE THREAD

**Issue by kotwal13aditya** [grafana/grafana#7299]
[Feature Request] Option to disable dashboard dropdown in nav-bar

In my dashboard, I have a drop down (right side in the attached screenshot) which allows users to navigate to different dashboards carrying with them various variables like time stamp range and entity names.

<img width="1422" alt="screen shot 2017-01-18 at 11 09 07 pm" src="https://cloud.githubusercontent.com/assets/19351144/22096925/2a8fd69e-ddd3-11e6-88f6-bb9146f6e612.png">

Now, some users are not using that drop down, instead are using the dashboards drop down on the navigation bar (top left in the screenshot). This confuses them as time stamps and variables are lost. I would like to request grafana community to allow disabling this nav-bar dashboard dropdown. It would be even better if we could add a flag in the dashboard JSON itself to control this drop down selections. If not possible using JSON, it would be great if it could be set via API.

Thank,
Ady

P.S.: Environment information:
- Grafana Version: 3.1.1
- Data source - Influx DB
- OS: PhotonOS

**Comment by torkelo** [comment]
we are not going to allow disabling dashboard search, as that is also where you create / import dashboards and navigate to home dashboard. 

Navigation between dashboard is something we want to improve (like keeping time range & variables) when using dashboard search. Also relevant to your case is Dashboard Folders, which is something we want to start implementing soon, https://github.com/grafana/grafana/issues/1611

**Comment by kotwal13aditya** [comment]
Sounds good. Thanks for the prompt reply!
