### ISSUE TITLE
[Feature Request] cloudwatch datasource not support RE

### ISSUE THREAD

**Issue by clhlc** [grafana/grafana#7300]
when I used cloudwatch datasource， not supprt RE in cloudwatch grap  * is not support，
![2017-01-19 15-16-54](https://cloud.githubusercontent.com/assets/10704095/22097130/6dfcf4e8-de5a-11e6-81fa-6442b2ecfcf2.png)

**Comment by torkelo** [comment]
Don't think CloudWatch query API support it
