### ISSUE TITLE
Grafana 10 - failed to convert datasource instance settings: [sqlstore.max-retries-reached] retry 1: database is locked

### ISSUE THREAD

**Issue by skinfrakkiirid** [grafana/grafana#73018]
### What happened?

Getting several database locked errors. Happening since moving to Grafana 10.

### What did you expect to happen?

Database not to lock up

### Did this work before?

Yes

### How do we reproduce it?

1. Use Grafana
2. Random lock up
3. Restart MySQL database

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by suntala** [comment]
Hi @skinfrakkiirid, thank you for this. Would you be able to provide more detailed reproduction steps? More information regarding your environment could also be helpful.

**Comment by suntala** [comment]
Hi again @skinfrakkiirid, I'm actually going to go ahead and close this issue for now. Please feel free to open one again if you have more detailed reproduction steps to provide.

**Comment by skinfrakkiirid** [comment]
Just happened again updating an alert rule. It is random:

logger=sqlstore.transactions t=2023-08-16T21:15:21.408045611Z level=info msg="Database locked, sleeping then retrying" error="failed to query for existing provenance status: database is locked" retry=1 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:21.439507545Z level=info msg="Database locked, sleeping then retrying" error="[sqlstore.max-retries-reached] retry 1: failed to query for existing provenance status: database is locked" retry=1 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:26.749006478Z level=info msg="Database locked, sleeping then retrying" error="failed to query for existing provenance status: database is locked" retry=1 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:26.769139493Z level=info msg="Database locked, sleeping then retrying" error="[sqlstore.max-retries-reached] retry 1: failed to query for existing provenance status: database is locked" retry=2 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:32.818711687Z level=info msg="Database locked, sleeping then retrying" error="failed to query for existing provenance status: database is locked" retry=1 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:32.844071823Z level=info msg="Database locked, sleeping then retrying" error="[sqlstore.max-retries-reached] retry 1: failed to query for existing provenance status: database is locked" retry=3 code="database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:35.206938705Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1 code="database is locked"
logger=ngalert.scheduler t=2023-08-16T21:15:35.207048156Z level=error msg="Failed to update alert rules" error="[sqlstore.max-retries-reached] retry 1: database is locked"
logger=sqlstore.transactions rule_uid=dc35b353-ca05-4619-a647-2100c463a210 org_id=1 t=2023-08-16T21:15:36.337150865Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1 code="database is locked"
logger=ngalert.state.manager rule_uid=dc35b353-ca05-4619-a647-2100c463a210 org_id=1 t=2023-08-16T21:15:36.33725551Z level=error msg="Failed to save alert state" labels="Hostname=, __alert_rule_namespace_uid__=b0bd09e6-76e4-4b64-bf8f-fffdecdb8f86, __alert_rule_uid__=dc35b353-ca05-4619-a647-2100c463a210, alertname=CPU Usage, grafana_folder=Hosts, host=rh8" state="unsupported value type" error="[sqlstore.max-retries-reached] retry 1: database is locked"
logger=sqlstore.transactions t=2023-08-16T21:15:38.118766836Z level=info msg="Database locked, sleeping then retrying" error="failed to update rules: failed to update rule [dc35b353-ca05-4619-a647-2100c463a210] CPU Usage: database is locked" retry=4 code="database is locked"

**Comment by TitoufTeam** [comment]
I have the same problem, one time a day/ 2 days !!
Alert name is : "DatasourceError" implicit alert not define by user.
