### ISSUE TITLE
Canvas Panel: Enable Button as alpha feature

### ISSUE THREAD

**Issue by tichribra** [grafana/grafana#73027]
### What happened?

I tried to enable the button as an alpha feature of the canvas panel, by setting the 'enable_alpha' settting of the [plugins]-section to true and remove the semicolon in the grafana.ini-File. But the button doesn´t appear. Setting the 'enable_alpha' as environment variable does not work too. (GF_PLUGINS_ENABLE_ALPHA=true)
Daria from VolkovLabs also tried it. => https://www.youtube.com/watch?v=ZIjUOr_HYFQ (look at the comments section)

### What did you expect to happen?

Activate the button of the canvas panel by setting the 'enable_alpha' of the [plugins]-section to true. 
you should achieve this by:
- manually change the grafana.ini
- set the environment variable to true (GF_PLUGINS_ENABLE_ALPHA=true)
![cutout_of_grafana ini](https://github.com/grafana/grafana/assets/135816321/0ef588f1-9fb5-4df4-9f6e-2091d4d727f2)

### Did this work before?

no

### How do we reproduce it?

1. remove the semicolon of the 'enable_alpha' setting in the [plugins] section of the grafana.ini and set enable_alpha to 'true'
2. restart grafana
3. try to add a button as element to the canvas panel (button is not selectable => look picture)
![button_not_selectable](https://github.com/grafana/grafana/assets/135816321/3c2293d3-a3d9-4b38-9f89-7299d987aefc)

### Environment (with versions)?

Grafana: 10.0.3
OS:  Ubuntu 22.04.2 LTS with Docker 24.0.4
Browser: Google Chrome 115.0.5790.111

### Grafana platform?

Docker

**Comment by adela-almasan** [comment]
Closing this as the button functionality was promoted to Beta in 10.2.
