### ISSUE TITLE
[Bug] OpenLDAP authentication group search issue: "user does not belong in any of the specified ldap groups"

### ISSUE THREAD

**Issue by hiscal2015** [grafana/grafana#7302]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? v4.1.1
- What datasource are you using? sqlite
- What OS are you running grafana on? Docker
- What did you do? Enable openldap authentication
- What was the expected result? use login with correct group role
- What happened instead? ldap search can find correct group but say "user does not belong in any of the specified ldap groups"

Details:

part of my ldap.toml:
search_filter = "(uid=%s)"
search_base_dns = ["dc=cloud,dc=demo,dc=com,dc=cn"]
group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
group_search_base_dns = ["ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
email =  "email"
member_of = "cn"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=DevOps,ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

#[[servers.group_mappings]]
#group_dn = "cn=DevOps,ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn"
#org_role = "Editor"

#[[servers.group_mappings]]
## If you want to match all (or no ldap groups) then you can use wildcard
#group_dn = "*"
#org_role = "Viewer"

my use and group infomation from ldap:
# DevOps, Groups, cloud.demo.com.cn
dn: cn=DevOps,ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn
objectClass: posixGroup
cn: DevOps
gidNumber: 5000
memberUid: u123456

# u123456, DevOps, Groups, cloud.demo.com.cn
dn: uid=u123456,cn=DevOps,ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
uid: u123456
sn: Name
givenName: My
cn: My Name
displayName: My Name
uidNumber: 10000
gidNumber: 5000
gecos: My Name
loginShell: /bin/bash
homeDirectory: /home/u123456

Logs:
1/19/2017 3:41:02 PMt=2017-01-19T07:41:02+0000 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc4208fabd0)({\n DN: (string) (len=69) \"uid=u123456,cn=DevOps,ou=Groups,dc=cloud,dc=demo,dc=com,dc=cn\",\n FirstName: (string) (len=4) \"Yong\",\n LastName: (string) (len=5) \"Zhang\",\n Username: (string) (len=7) \"u123456\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=1 cap=1) {\n  (string) (len=6) \"DevOps\"\n }\n})\n"
1/19/2017 3:41:02 PMt=2017-01-19T07:41:02+0000 lvl=info msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=u123456 groups=[DevOps]
1/19/2017 3:41:02 PMt=2017-01-19T07:41:02+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"

From above logs, seems grafana can successfully find my group DevOps, but why it still says "user does not belong in any of the specified ldap groups"?

Thanks.

**Comment by torkelo** [comment]
For some reason the memberOf is just the group name and not the full dn, which is what you specified group mappings. think the config is wrong, but have not used the group search looking feature so not sure.

**Comment by hiscal2015** [comment]
@torkelo Thank you Torkelo, you're right, I changed value group_dn = "DevOps" then everything works fine!

**Comment by andrewgreenwood** [comment]
I've just been struggling with this as well, after a fresh install of Grafana. I checked the documentation, double-checked what I'd put in the config file, then checked against an old config where I had this working fine, even went as far as copying the ldap.toml file across from that without success.

Found this issue, changed the "group_dn" to just have the group name (in my case "grafana-admins") as suggested, and it works now. I didn't think of doing this sooner because of the setting name (i.e. it looked like it had to be a DN).

Specifying a DN used to work, I am not sure when this changed and whether it was intended or not.

**Comment by maxdevyatov** [comment]
Same here. Broke after I upgrade to a new version.
Fixed it by keeping only the group name.

**Comment by 31bbb** [comment]
A heads up; this is no longer relevant. I had to use `member_of = "memberOf"`. I am using `389-ds` though for LDAP. With that being said, to use Grafana LDAP at all I had to enable the `MemberOf` plugin within the LDAP server and rebuild all users `memberOf` attributes to even use LDAP in Grafana.

**Comment by hiscal2015** [comment]
@31bbb You don't have to, use below group_search_filter instead
```
group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
email =  "email"
member_of = "cn"
```

**Comment by 31bbb** [comment]
@hiscal2015 I tried that but it would not work.
