### ISSUE TITLE
Docs: Deadlink in Get started with Grafana plugins

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#73036]
Page: https://grafana.com/docs/grafana/latest/developers/plugins/get-started-with-plugins/

Dead links:
- [Get started with creating a plugin](https://grafana.github.io/plugin-tools/docs/getting-started)
- [Set up your development environment](https://grafana.github.io/plugin-tools/docs/development/docker)

**Comment by josmperez** [comment]
Hi @matyax - Sorry about that. We're reorganizing the site containing those files right now and fixes to these links are in progress. Meanwhile, you can find the content you're looking for at https://grafana.github.io/plugin-tools/

**Comment by matyax** [comment]
Thanks! I just wanted to raise awareness about it, as I was browsing the docs for App plugins. Feel free to close this one if you're already working on it.
