### ISSUE TITLE
Problem in creating Template Var

### ISSUE THREAD

**Issue by NitinRanjan** [grafana/grafana#7304]
Grafana version: 4.2
datasource: openTSBD 2.2

I want to create a template var. 
out of these functions:
metrics(prefix) tag_names(cpu) tag_values(cpu, hostname) suggest_tagk(prefix) suggest_tagv(prefix)

only these are working for me:
metrics(prefix) suggest_tagk(prefix) suggest_tagv(prefix)

I am using function like:
tag_values(GlobalThreadPoolExecutor.reservedThreads.Default123, node)

and when i use this function like:
tag_values(GlobalThreadPoolExecutor.reservedThreads.Default123, node,setup = $setup)

it shows error: **Template variables could not be initialized: undefined**

and i have criated setup var:
suggest_tagv(_) 
 
and the content of this matric is like:

{"metric":"GlobalThreadPoolExecutor.reservedThreads.Default123","timestamp":1468931460000,"value":200.0,"tags":{"node":"sys-182","setup":"_Solutions-Sanity"} 

My same related issue [#7292 ](https://github.com/grafana/grafana/issues/7292)is also not solved.
Please guide me as I am using Grafana First Time

**Comment by torkelo** [comment]
Can you show the response from OpenTSDB for the tag_values query? 

have you enabled meta data options? http://opentsdb.net/docs/build/html/user_guide/metadata.html 
tag_values and tag_names require realtime meta

**Comment by NitinRanjan** [comment]
Hii,
Solved the problem..
Thanx for the support
