### ISSUE TITLE
Dasboards provisioning: Could not resolve dashboards uid

### ISSUE THREAD

**Issue by lutskevich** [grafana/grafana#73043]
### What happened?

We have a lot error messages like
`msg="failed to save dashboard" file=/tmp/dashboards/service-proxy/service-proxy.json error="could not resolve dashboards:uid:IQhiINgzoNZWEhUB: Dashboard not found"`

### What did you expect to happen?

successful dashboards provision

### Did this work before?

Nope

### How do we reproduce it?

1. Provision dasbords from configmaps

### Environment (with versions)?

Grafana: 9.4.10

### Grafana platform?

Kubernetes

**Comment by andrejshapal** [comment]
Hello, 
Same here:
`<html>
<body>


2023-08-10 12:47:01.216 | logger=provisioning.dashboard type=file name=sidecarProvider t=2023-08-10T09:47:01.216821105Z level=error msg="failed to save dashboard" file=/tmp/dashboards/QA/loading-screen.json error="could not resolve dashboards:uid:qXswhGCnk: Dashboard not found"
-- | --



</body>
</html>`
Using latest grafana 9 build.

**Comment by lutskevich** [comment]
But error message is not clear enough

**Comment by andrejshapal** [comment]
@lutskevich There is somewhere bug report about this (like few years old). 
In order to solve this without too many actions, we are trigerring this endpoint:
POST /api/admin/provisioning/dashboards/reload
Or just restarting POD))

**Comment by andrejshapal** [comment]
Hello, 
Maybe this is worth to fix...

**Comment by ManishJain-TomTom** [comment]
> We found that this happens when a dashboard UID changes inside a json file. When the dashboard with uid aaaa (from same cm and json) is already created in grafana.db, and When cm is update with a another uid like bbbb. To solve need to recreate cm/json (delete and create after dashboard with the "old" uid will be removed from db)

Is there a way to fix this? Should I first remove the dashboard configmap from my helm deployment and then re-add it for this to work properly?
