### ISSUE TITLE
Dashboards: Alert list panel does not refresh

### ISSUE THREAD

**Issue by radeonsk** [grafana/grafana#73046]
### What happened?

Alert list panel does not refresh with the rest of the dashboard. Refreshing whole page (pressing F5) will refresh also Alert list panel.

### What did you expect to happen?

Alert list panel will refresh with the rest of the dashboard (by clicking on Refresh button in Grafana, or automatically when auto-refresh interval is set).

### Did this work before?

Worked with Grafana v8.5.3 (409e9bc9a5)

### How do we reproduce it?

1. Add Alert list panel to dashboard
2. Wait for alert change (new alert firing, or resolved)
3. Click on Refresh button in Grafana (or wait when auto-refresh is enabled)
4. Alert list panel is not updated

### Environment (with versions)?

Grafana: v10.0.3 (eb8dd72637)
Browser: Firefox 116.0.1

### Grafana platform?

Kubernetes

**Comment by armandgrillet** [comment]
This has been fixed in Grafana 10.1: https://github.com/grafana/grafana/pull/72242
