### ISSUE TITLE
[Bug] InfluxDB template variable interpolation different in raw mode 

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#7306]
Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxDB
- What OS are you running grafana on? Windows
- What did you do? 

I have a measurement with a tag which has values ['a', 'ab', 'c'] for example. I template on this tag and then choose options 'a' and 'c'

- What was the expected result?

Data series would be pulled from influxdb with tags 'a' and 'c'

- What happened instead?

Data series are pulled from influxdb with tags 'a', 'c' AND 'ab'

Note this doesn't happen if only 'a' is selected. 

Thanks.

**Comment by torkelo** [comment]
make sure your tag regex match is matching on whole tag using proper start / closing string markers

for example: `=~ /^$myvariable$/`   you can make that more readable if you use the alternative template interpolation syntax `=~ /^[[my_variable]]$/`

**Comment by robinsonjj** [comment]
I can confirm that it is. 

I've looked at the influxdb queries and when I'm having the above issue, granfana sends a query like `"select value from "db".retention.tmp where myvariable =~ /^a|c$/ ...` and when it's working as I would expect then the query is: `"select value from "db".retention.tmp where myvariable =~ /^(a|c)$/ ...`  note the brackets in the working query.

 I'm struggling to work out what makes this happen - if it isn't obvious to you then I'll continue to try and narrow down what is causing this. Do you mind re-opening the issue please?

**Comment by robinsonjj** [comment]
I've narrowed it down. This problem (i.e. the brackets are missing in the regex) happens when the query is typed in manually. It is fine when the query builder mode is used.

**Comment by torkelo** [comment]
So in raw mode there a special interpolation function that only applies regex escaping when All or Multi value is enabled on the variable. When formatting the regex it does not enclose it in parenthesis (which the normal regex formater does).

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/influx_query.ts#L196

**Comment by robinsonjj** [comment]
In case anyone comes across this issue, an easy temporary fix is to put the brackets in manually when in raw mode, e.g. `=~ /^($myvariable)$/`

**Comment by torkelo** [comment]
closing this as we have now ways to control the formatting of variables
