### ISSUE TITLE
Grafana Alerting - Getting this error: "Failed getting data source"

### ISSUE THREAD

**Issue by SaiUmeshKumar** [grafana/grafana#73079]
### What happened?

We are running grafana 7.5.17 with postgres as backend and we are running into below alerting errors

lvl=eror msg="Failed getting data source" logger=sqlstore err=EOF uid= id=9 name= orgId=1
lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=18903 name="<ALERT_TITLE>" error="could not find datasource: EOF" changing state to=alerting

Checked the database and the datasource is present in db in data_source table and also validated that the datasource is present in the api/datasources API response

For the alerts that had set If execution error or timeout as Alerting, alert is triggered with Error: could not find datasource: EOF

We are seeing this for all kinds of datasources - prometheus, elasticsearch, stackdriver and postgres

Why are we getting this error and what to do to fix this ?

### What did you expect to happen?

These errors shouldn't occur as the database has these datasources

### Did this work before?

Yes

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 7.5.17
OS: NA
Browser: NA

### Grafana platform?

Kubernetes

### Datasource(s)?

No... we are seeing this for all kinds of datasources -  prometheus, elasticsearch, stackdriver and postgres

**Comment by armandgrillet** [comment]
Please retry on a supported version of Grafana, i.e. Grafana 10. It still supports legacy alerting if you don't want to migrate your alerts: https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/#stay-on-legacy-alerting
