### ISSUE TITLE
Loki: Transformations with query splitting returns error

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#73089]
When query splitting is enabled and users use some of the transformations it produces errors. 

Related to https://github.com/grafana/support-escalations/issues/6982
Related to https://github.com/grafana/support-escalations/issues/6989

https://github.com/grafana/grafana/pull/72981 partly fixes some issues

**Comment by gtk-grafana** [comment]
So on the loading indicator point above, the annotation frame blocks out each section that hasn't been loaded yet, as long as this continues to work even if the panel throws an error for a partial query transform we shouldn't need to implement another loading indicator as it's already indicating the progress.

**Comment by gtk-grafana** [comment]
So taking a look at those escalations, it looks like they are all using the extract fields and organize fields transforms, but they are running log queries `| json`, so I'm confused as to how disabling query splitting fixed those dashboards, as query splitting only runs with metric queries?

**Comment by ivanahuckova** [comment]
> as query splitting only runs with metric queries

Query splitting runs with log queries as well

**Comment by gtk-grafana** [comment]
🤦 I was hitting my log line limit before I could get a second "page" of logs. 
Thank you! I was finally able to reproduce this error on main in the logs panel just with the "Extract fields" transformation, extracting all labels
<img width="1725" alt="image" src="https://github.com/grafana/grafana/assets/109082771/4260b8d0-b363-4c77-95de-f588159496c9">
With a somewhat sparse query with a 2 day range, a split duration of 1 hour, and max lines of 1000

**Comment by gtk-grafana** [comment]
Another issue with query splitting is that it breaks the query inspector, only displays the last request in the batch.
