### ISSUE TITLE
[Bug] Graph locked on invalid query ... 

### ISSUE THREAD

**Issue by FarnazMostowfi** [grafana/grafana#7308]
It seems like if a chart is configured incorrectly (for example settings for null values or wrong aggregations), Grafana is not as intuitive in returning no results or throw a descriptive error explaining the issue; instead the graph seems locked and the only possible solution for this behaviour seems to be deleting the chart and recreating it from scratch.

- What Grafana version are you using? 4.1.1
- What datasource are you using? Elasticsearch 5.x
- What OS are you running grafana on? Official Docker on linux  

![screen_shot_2017-01-16_at_13_44_07](https://cloud.githubusercontent.com/assets/2988824/22110853/295ac45a-de55-11e6-8d1f-9e7a628f1dd5.jpg)

**Comment by torkelo** [comment]
Can you describe what steps you did to get into this state? Did you modify json manually?

**Comment by FarnazMostowfi** [comment]
@torkelo Sorry for the delay in reply.
Do you mean the Elasticseach json files? I haven't touched any json files.

So this is how I can regenerate the issue, on the dashboard
1- Add Panel > Table/Graph 
2- Edit > Select data Source , everything still looks fine
![grafana_-_app_server_os_metrics](https://cloud.githubusercontent.com/assets/2988824/22254102/96948a66-e24b-11e6-92ff-ac7d3e51ae6f.jpg)

3- Update the Metric from `Count` to `Raw Document`  , the attribute list disappears and then: 
![grafana_-_app_server_os_metrics](https://cloud.githubusercontent.com/assets/2988824/22254293/0ee6a97c-e24c-11e6-9a1e-266bcd69224d.jpg)

**Comment by torkelo** [comment]
strange, cannot replicate that issue following the exact steps you take. 

Can you replicate on http://play.grafana.org/ ?

**Comment by torkelo** [comment]
what browser are you using? Any errors in chrome dev console?

**Comment by FarnazMostowfi** [comment]
I get the same behaviour on Chrome and Safari.

What version of Grafana is behind this demo? My local Grafana is 4.1.1 and seems like it's missing this error:

![screen shot 2017-01-24 at 16 47 22 2](https://cloud.githubusercontent.com/assets/2988824/22257129/00ab5d0e-e255-11e6-9881-746fcdd2150f.png)

**Comment by maxtar** [comment]
I have the same problem too :(

**Comment by FarnazMostowfi** [comment]
Are you connecting to Elasticsearch? and if yes, how did you populate the data in Elasticsearch, did you use logstash? ... I wonder if it is something to do with the ES JSON format

**Comment by maxtar** [comment]
Yes, I am connecting to elasticsearch. We write data to elastic directly, without logstash. JSON our own format.

**Comment by daniellee** [comment]
On the data source page can you double check that the Time field name matches your mapping (whether the field name starts with @ or not).

![image](https://cloud.githubusercontent.com/assets/434655/23995240/017800a4-0a49-11e7-9e83-a229a4d2f503.png)

**Comment by maxtar** [comment]
@daniellee I,ve checked. Mapping is correct. Our field named "dateTime" (without @)

**Comment by daniellee** [comment]
@maxtar can you show the response you are getting from the query:

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by maxtar** [comment]
@daniellee This is not depends of source. Error appearing when I select Raw and return back to any value (count, average, etc.) I see state from the first screenshot.

**Comment by torkelo** [comment]
After selecting Raw Document, the only way currently to reset the query to default (which includes a group by) is to remove the query and add a new one

**Comment by maxtar** [comment]
@torkelo Yep, I think this is not usable :)
