### ISSUE TITLE
OpenTSDB: Backend response handling does not apply series alias patterns 

### ISSUE THREAD

**Issue by gkissand** [grafana/grafana#7309]
Grafana 4.1.1
datastore: opentsdb

I measure for apache connections on 10 web servers, all in one graph
I configure alerting if connections above 10.000 to send an alert notification with message

What i get is a screenshot, the metric name eg apache.apache.apache_connections.value and the value

If i have 10 or in some cases 20 servers it will be very useful to be able to configure a custom tag in the alert notification message, like I can do it in the metric/Alias with $tag_host or whatever $tag_<customtag>, to know which host is the alert for

I tested it but i get "Apache connections reaching limit for host $tag_host"

![unnamed 2](https://cloud.githubusercontent.com/assets/25226373/22111393/7881c182-de5f-11e6-9c90-1bd06131962f.png)
![unnamed 1](https://cloud.githubusercontent.com/assets/25226373/22111394/78832c7a-de5f-11e6-9ac2-f448cd875056.png)
![unnamed](https://cloud.githubusercontent.com/assets/25226373/22111395/788d4ac0-de5f-11e6-9e0c-a616c3ec3405.png)

**Comment by torkelo** [comment]
@utkarshcmu Have some reports of users using OpenTSDB & alerting that their Alias settings are not used in the alert notifications. Have you seen this?

**Comment by torkelo** [comment]
looks like alias patterns are ignored here:
https://github.com/grafana/grafana/blob/master/pkg/tsdb/opentsdb/opentsdb.go

**Comment by utkarshcmu** [comment]
This is be a bug, I think. Will try to fix this asap!

**Comment by utkarshcmu** [comment]
@torkelo is there an example of any other datasource doing this?

**Comment by torkelo** [comment]
Yes,  InfluxDB and Prometheus

**Comment by trojanman190** [comment]
Any progress on this?

**Comment by yednaps** [comment]
I may be having a similar issue when I try to alias the names of queries with OpenTSDB data source. It seems like it uses the value for the first one for everything:

No alias set:
![image](https://user-images.githubusercontent.com/1047967/37057498-9381580a-2155-11e8-9da4-6044773b9767.png)

Unique aliases set for each, but the alias from query A is used for all three:
![image](https://user-images.githubusercontent.com/1047967/37057527-abac482c-2155-11e8-987c-cc1ddade7bc7.png)

**Comment by paulsson** [comment]
Any update on this @torkelo ?
Year and a half later we're running Grafana 5.2.2 and this still does not work.  Would be great if we could reference tag values in the notifications that are sent out.

**Comment by dynamik7** [comment]
Still no update?
I run grafana-7.1.1-1 with opentsdb.

In alerting, alias does not work at all.
It is same results, even if I set alias with a static string.

![image](https://user-images.githubusercontent.com/35594326/115504522-1039c800-a2b3-11eb-99a6-aee207f1177d.png)
