### ISSUE TITLE
space between bar in bar chart

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#7311]
Hello,

- What Grafana version are you using?
4.0.0
- What datasource are you using?
INfluxdb
- What OS are you running grafana on?
Unbuntu
- What did you do?
bar chart
- What was the expected result?
![bar_plot](https://cloud.githubusercontent.com/assets/20662503/22113839/e75b41e8-de67-11e6-8bde-cfc1c722164e.png)
- What happened instead?
![bar_plot - copie](https://cloud.githubusercontent.com/assets/20662503/22113809/d3cb2936-de67-11e6-935a-6762a0c3610e.png)

I have 15 minutes data from influxdb and I want that the bar goes on all the 15 minutes. Instead that, The bar goes only 10 minutes then there is a space. Is it a problem, I do not know, but it would be nice to have the possibility to complete this space.

Thank you

**Comment by torkelo** [comment]
If there is no space between the bars you wont be able to see them clearly. 

There is an option named "Staircase" for line graphs that look similar to what you wish
