### ISSUE TITLE
Dashboards: Dashboard init failed

### ISSUE THREAD

**Issue by carat-johyun** [grafana/grafana#73134]
### What happened?

<img width="1511" alt="image" src="https://github.com/grafana/grafana/assets/103920913/e6f87eba-a0ab-4b61-95e2-6fa162102811">

- console log
Pathname "/d/VGFuqfwnz/%8carat-dashboard" could not be decoded. This is likely caused by an invalid percent-encoding.

I want to get all of my queries..
Is there any solution to get my queries from this dashboard?

### What did you expect to happen?

The dashboard open.

### Did this work before?

The dashboard opened fine. But now..

### How do we reproduce it?

1. go to this url : https://paradot.grafana.net/d/VGFuqfwnz/carat-dashboard?orgId=1&from=now-90d&to=now

### Environment (with versions)?

Grafana: Grafana v10.2.0-59422pre (25690811)
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

**Comment by evictorero** [comment]
This is probably related to a [known issue](https://github.com/grafana/grafana/issues/72341) that was fixed last week, can you try again once your instance gets updated?

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana/pull/73164. Feel free to re-open if you still encounter the problem.
