### ISSUE TITLE
stats.grafana.org used every 15 seconds

### ISSUE THREAD

**Issue by icf20** [grafana/grafana#73140]
### What happened?

there is a connection to stats.grafana.org every 15 seconds

### What did you expect to happen?

this to happen one time per day

### Did this work before?

no idea

### How do we reproduce it?

look at network lol

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Docker

**Comment by papagian** [comment]
thank you for reporting this: can you provide some additional information:
which grafana version do you use?
could you provide your grafana configuration?

**Comment by icf20** [comment]
it was the image: grafana/grafana so latest docker

> could you provide your grafana configuration?

is the default "config" i nuked the container 

stats.grafana.org get blocked by adguard so likely the time get lower if it fails connect

**Comment by icf20** [comment]
@papagian  i did set another container, `grafana/grafana:latest`,  is exactly what you guys ship, here is that I got for a week
![imagen](https://github.com/grafana/grafana/assets/17784575/414ce374-b2c6-48e1-b25c-150b597b1e1d)



![imagen](https://github.com/grafana/grafana/assets/17784575/8b9d0490-ced7-472d-b5cd-ad13c19a0030)
