### ISSUE TITLE
Enterprise plugin installation on grafana cloud free tier is unintuitive 

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#73157]
**Problem**
After expanding the Free tier of Grafana Cloud to include access to enterprise plugins in g10 ([announce blog](https://grafana.com/blog/2023/06/13/grafanacon-2023-a-guide-to-all-the-big-announcements-from-grafana-labs/)), the UX has not been updated in the catalog and is now quite unintuitive to the point of making it seem like they are not available.

1. (optional) From Connections if you hover over an enterprise plugin you are presented with `Install Now`
<img width="1224" alt="Screenshot 2023-08-10 at 15 13 03" src="https://github.com/grafana/grafana/assets/19860021/5adc1d58-6bc3-4faf-8a52-fa74be50a92a">

2. This takes you to Admin > Plugins > $plugin. Where you are presented with what appears to be a warning or restriction that the plugin would require an enterprise license. 
<img width="637" alt="Screenshot 2023-08-10 at 13 56 57" src="https://github.com/grafana/grafana/assets/19860021/68ed8330-11ae-492d-9f1a-01cb1dc38885">

You don't have an `Install via Grafana.com` 

Instead, the only CTA is to learn more on the lack of the enterprise license. Which is not particularly promoted and could easily be missed or the user will just assume that they are not able to install the plugin as not entitled to it.

3. IF the user clicks learn more, they are taken to the plugins page on Grafana.com/plugins/$plugin. Here they discover that actually, yes, they can seem to install it.
<img width="1045" alt="Screenshot 2023-08-10 at 13 57 03" src="https://github.com/grafana/grafana/assets/19860021/edf74e5d-051e-4750-94ce-d9ab37c21bbd">

4. IF they try this given the previous experience, the plugin will successfully install. But when viewing again within the catalog, the user is still presented with this "warning" about the lack of an enterprise license. 

<img width="1255" alt="Screenshot 2023-08-10 at 14 01 06" src="https://github.com/grafana/grafana/assets/19860021/f42021aa-6301-4df3-8a2b-f69e2e2fd614">

**Proposal**
- Add the install button for Enterprise Plugins in Grafana Cloud from a plugin's details page
- Remove the message regarding enterprise license in Grafana Cloud **only** - this check/functionality is _probably_ still ok on on-premise

**Open questions**
- ~What to do in the case of a Pro tier subscription. Whether there is existing logic we can hook into to detect that the user already has an enterprise plugin, and if so whether to present a warning or block installation.~ Punt for now
- If we make the above changes, there will be no indication on the plugin **details** page that a plugin is Enterprise. We could look at changing the "Level" to `Enterprise` if we get that from `Status: Enterprise`. This would then match the behaviour on gcom.
- Should we provide a link to Pricing or something like https://grafana.com/docs/plugins/ or https://grafana.com/docs/grafana-cloud/introduction/find-and-use-plugins/#find-and-use-grafana-plugins and retain the learn more once we get Install back working again
- general comment - enterprise isn't a tier on Grafana Cloud so this was already a bit confusing.
 
 
 Raising as an enhancement, but this is almost a bug.

**Comment by ddorman16** [comment]
@sympatheticmoose 👍 on the proposal, every word. Lots of rough edges.

**Comment by ddorman16** [comment]
> What to do in the case of a Pro tier subscription. Whether there is existing logic we can hook into to detect that the user already has an enterprise plugin, and if so whether to present a warning or block installation.

The current plan is to remove the Pro single-enterprise-plugin add-on as an option. I'm okay with punting on this specific one for a bit.

**Comment by tolzhabayev** [comment]
Link to https://github.com/grafana/grafana-plugins-platform-team/issues/21

**Comment by Ukochka** [comment]
This bug is related with license token. Will not be fixed from plugin-platform team
"When we create the license we also have a job that creates the license token. That may have failed for some reason or something along those lines"
"we weren't able to see why the token failed to get created, we handle it automatically when creating/updating the license but the logs are possibly too far back to see what the issue might have been"

**Comment by sympatheticmoose** [comment]
This turned out to be a licensing issue which is hopefully resolved.
