### ISSUE TITLE
[BUG] Elasticsearch Templating bug

### ISSUE THREAD

**Issue by txisme** [grafana/grafana#7315]
- What Grafana version are you using? 4.1.1
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Cent OS 7.2
- What did you do? Created graphs from elastisearch stored data and changed time range
- What was the expected result? To see the data plotted 
- What happened instead? Data is not plotted

Recently upgraded to new grafana and the graphs that previously were working flawlessly now are creating problems like if i move a lot the time range, it stopps plotting data and shows the following error message:

![image](https://cloud.githubusercontent.com/assets/10253258/22147324/e8ff1fb8-deff-11e6-80b2-897f3b830942.png)

AND

![image](https://cloud.githubusercontent.com/assets/10253258/22147381/4521e6cc-df00-11e6-9f5d-04a9263cf336.png)

So it seems that grafana can't connect to the database, but this is not a database problem as when i change the time range to last 12h or 24h it works again. But then again zoom in and it goes haywire.

-------------------------------------------------------------------------------------------------------

UPDATE:

After removing the templating variable, everything works fine so this is a BUG related to the templating that when zoomed in it can't read the variable used in this template

-------------------------------------------------------------------------------------------------------

UPDATE 2:

Noticed that the problem can be avoided by not refreshing the template variable on every time range change.
Anyway, this seems like a bug to me, and i would prefer to refresh template variables every time i change the time range. Can someone look into this?

Briefly, refreshing template variables on every time range change causes the template variables to be sometimes empty when they really are not.

**Comment by torkelo** [comment]
If you have enabled variable refresh on time range, then Grafana will issue template variable query for each zoom/time range change, and maybe for one time range you do not get any values for the host variable. which creates an empty value for that variable, and a non valid ES query. 

Change your template variable to refresh on dashboard load

**Comment by txisme** [comment]
Yes that is correct but what happens is that i'm sure i have values for the selected time range.
