### ISSUE TITLE
[Bug] Reload datasource settings if grafana returns `Datasource is not configured to allow this database`

### ISSUE THREAD

**Issue by peay** [grafana/grafana#7316]
Using:
```
Grafana 4.0.2
InfluxDB datasource (possibly other)
Docker image `grafana/grafana:4.0.2`
```

To reproduce the issue,
- Create influxdb data source, with database `A`
- Create dashboard, make a graph using the data source
- Update database to `B` for the datasource, click `Save & Test`
- Attempt to create a template, such as `SHOW TAG VALUES WITH KEY = xxx`

This produces the error message: `Datasource is not configured to allow this database` from https://github.com/grafana/grafana/blob/76c9f62265e74331ca8a0304d87c127f8571e3f4/pkg/api/dataproxy.go#L94.

Instead, this should correctly create the template.

The `Database` property of InfluxDBExecutor (actually, this may be an issue for all data sources) appears not to be updated when the datasource corresponding to the executor is updated. I believe a new executor should be created, or the current executor should be updated.

Thank you,

**Comment by bergquist** [comment]
The datasource settings (in this case the db name) are loaded into your browser. Updating the datasource settings in the background while the grafana session is still active wont reload the settings. 

So to avoid this you need to reload the dashboard after updating the database name. Its a tricky bug to get ride of since we dont want to query grafana for datasource settings everytime we send a request to the tsdb.

**Comment by peay** [comment]
Right -- maybe it'd be enough to refresh the datasource settings when we get the `Datasource is not configured to allow this database` error (and then retry)?

**Comment by qli-aa** [comment]
Still see it in Grafana 4.6.2
I enabled auth proxy, save & test always failed when I add or update datasource
Grafana show 'Network Error: undefined(undefined)'
use curl will see '{"message":"Datasource is not configured to allow this database"}'

any update for this issue ?

**Comment by torkelo** [comment]
closing this, not sure there is much we can do for this scenario
