### ISSUE TITLE
Cloudwatch: Meta Inspector Needs Updating

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#73170]
Recently noticed that Cloudwatch has a "Meta Inspector" that I think we've been neglecting a bit:

<img width="615" alt="Screenshot 2023-08-10 at 3 26 52 PM" src="https://github.com/grafana/grafana/assets/6620164/cbac5aae-2500-468e-9c1e-471eaea92759">

To get to it, go to the query editor in a dashboard and click Query Inspector and then click Meta Data

I notice for example that I can't seem to get the Metric Data Query ID to show and Metric Data Query Expression only seems to show for me some of the time. I think we might want to revamp this at some point to make sure all datapoints show (and to see if perhaps there are other data points we'd like to show). Curious what the experience is like for Logs vs Metrics, Search Vs Query, Code builder vs query builder, etc.

**Comment by fridgepoet** [comment]
Next step: Can we more clearly define what we want for this one?
