### ISSUE TITLE
[Feature request]Pause/Resume all alert rules with one click

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7319]
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS

In panel `Alerting` -> `Alert List`, add button(s) to pause/resume all alert rules.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/6500
