### ISSUE TITLE
[Feature request] Builtin alert condition "metric.foo.bar" is above Y for N minutes

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#7320]
Grafana 4.1.1 with Graphite as datasource

I'd like to setup an alert for a metric (graphite datasource) following this logic :

Firing state: above Y for N Minutes

e.g. metric.foo.bar is above 100 for 5 minutes

The least complicated way I have found to do this is to apply the _removeAboveValuegraphite_ function and then use "has no value". While this works it feels quite convoluted, in addition because of "reverse" logic, when the alert gets into firing state the graph is empty. 

Currently all the aggregating functions return a single value thus it's impossible to check each data point returned by the original query against a threshold value.

Maybe a "map" or "for each" function could be added to the aggregating functions ?

While I have been able to achieve the functionality by using Graphite functions, I do think "alert me when foo is above Y for N minutes" is such a common use case that there should be a <overloaded_term>simple</overloaded_term> way to do this using Grafana alerting engine without having to overlay with a Graphite function.

**Comment by torkelo** [comment]
I think the median aggregation function is the one that comes closest to doing what your looking for (but not 100% there)

**Comment by jaimegago** [comment]
Unfortunately the *median* aggregating function, as you mentioned, does not allow for an exact representation of "above Y for N minutes" which means false alarms and is therefore not a viable solution.

**Comment by bergquist** [comment]
@jaimegago we are currently consider how to make "above Y for N minutes" easier to setup. But you can with median() if you set the time-range to N * 2. This means that when halv of all numbers returned in the query are above Y it will trigger.

Does it make sense? Ive started writing a docs post about this.

**Comment by magnuspwhite** [comment]
This is a feature that would be extremely useful in a wide number of use cases allowing for thresholds to be reached or exceeded but not trigger an alert until x minutes into that state.

@bergquist would be very interested to read those docs once complete as I've tried to use median to emulate the requested functionality with little success balancing false positives and real spikes.

**Comment by jaimegago** [comment]
@bergquist nice trick the time range set to N * 2, it does make sense! @magnuspwhite I don't think you need to wait for the doc, he said it all with using median() and a time-range set to N * 2,  just try it on paper, it's pretty straight forward.
So technically you can do it with median without layering a graphite function on top of your query and that's great. There is however a major caveat to this solution as it means doubling the IO load to get the necessary data points for median to work.

**Comment by torkelo** [comment]
And it is only work around until we can solve it 100%,   as it is not the exact same thing

**Comment by jaimegago** [comment]
@torkelo @bergquist @magnuspwhite  Sooooo median with N * 2...I think it actually does *not* work even as a work around, or maybe again I missed something.

Firing state: above 5 for 3 minutes
resolution: 1 data point per minute

We apply our N * 2, so 3 x 2 = 6 and we get 6 data points (see resolution), let's consider the following set : [10,10,2,10,2,4], the median is 7 (mean of [4,10]) which since 7 > 6 would put the state to firing when actually it is not matching the original "above 5 for 3 minutes".

Thus removeAboveValue remains the only exact way I've found to do "aboe N for Y minutes"

**Comment by torkelo** [comment]
@jaimegago it is by not exactly "above N for Y minutes", it was only a suggestion of what you can do now that gets you closer to that

**Comment by bergquist** [comment]
If you only have 6 data points median becomes tricky. 

Another approach might be to use `min()` instead of `median()`. Meaning that all points within a range have to above the threshold.

**Comment by haizaar** [comment]
Another possible [workaround](https://github.com/grafana/grafana/issues/7777#issuecomment-327336821): how about defining 

IF avg() of 5m,now is above X
AND avg() of 10m,now-5m is above X

I.e. splitting alert period in two, with first one being a time threshold.
