### ISSUE TITLE
HTML escaping error on telegram notifications

### ISSUE THREAD

**Issue by tobiasmuehl** [grafana/grafana#73210]
### What happened?

Telegram api returned 400 error:
lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=my-telegram-bot

This is the same bug as the one already reported #8302. Multiple users report this bug even after the issue has been closed

### What did you expect to happen?

Message from telegram bot in group chat

### Did this work before?

no

### How do we reproduce it?

make alert with `<` in the description field and send to telegram with a `HTML` message template

### Environment (with versions)?

Grafana 10, Chrome, Ubuntu 20

### Grafana platform?

Docker

**Comment by tobiasmuehl** [comment]
According to the [docs](https://grafana.com/docs/grafana/latest/alerting/fundamentals/alert-rules/message-templating/#html-in-notification-templates), HTML is escaped, but in this case, it's not

**Comment by tobiasmuehl** [comment]
Changing the message notification template and message format to Markdown works. The legacy Markdown format requires the least character escaping. But it will easily trip up on `grafana_folder` and other uses of underscore

**Comment by tobiasmuehl** [comment]
It can be fixed by updating your notification template to escape the alert description with \` character. That makes the text in Telegram monospaced and red, but symbols like `<` and `_` are allowed to render. Only the \` character itself needs to be escaped

**Comment by tobiasmuehl** [comment]
[Telegram docs on message formatting](https://core.telegram.org/bots/api#formatting-options)

**Comment by armandgrillet** [comment]
This error is coming from `./pkg/services/alerting/notifiers/telegram.go` which is only used by legacy alerting. Can you please retry with Grafana Alerting as legacy alerting is deprecated? Here are the docs regarding how to update: https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/

**Comment by armandgrillet** [comment]
Grafana 10 contains both alerting systems, please check the documentation link I have previously shared and confirm via the config file or a screenshot that you're not on legacy alerting which we do not support anymore.

**Comment by tobiasmuehl** [comment]
Here's a screenshot, is this still legacy?

<img width="1512" alt="Screenshot 2023-08-19 at 10 17 28" src="https://github.com/grafana/grafana/assets/3341826/e8b54ccb-a290-4134-abea-2cd87a0f5d54">

**Comment by armandgrillet** [comment]
This is Grafana Alerting, thanks for confirming 👍 .
