### ISSUE TITLE
Authentication: Unable to update local user when using Generic Oauth

### ISSUE THREAD

**Issue by raspreet-vunet** [grafana/grafana#73214]
### What happened?

Trying to login with a user from oauth raises a "user already exists" error in the UI. This only happens when a user with the same email/login already exists in grafana's db.

### What did you expect to happen?

The local user should be updated and possibly converted to an oauth user if it has the same email/login.

### Did this work before?

Yes, I recently upgraded to v10 and started seeing this issue. I was previously using v8.5.26 and it used to work just fine.

### How do we reproduce it?

Prerequisite: Generic oauth should be configured

1. Create a local user using the UI or the Admin API.
2. Login with a user that has the same email/login in the Oauth db.
3. An error saying "user already exists" is shown on the screen.

### Environment (with versions)?

Grafana: v10
OS: NA (using docker image)
Browser: Chrome

### Grafana platform?

Docker

**Comment by IevaVasiljeva** [comment]
Hi @raspreet-vunet! Could you try temporarily enabling `oauth_allow_insecure_email_lookup` configuraiton option (you can disable it again after all the users have logged in once).

https://github.com/grafana/grafana/issues/70203 provides more context on the security change that is causing the behaviour that you see. Especially [this comment](https://github.com/grafana/grafana/issues/70203#issuecomment-1603895013) and [this comment](https://github.com/grafana/grafana/issues/70203#issuecomment-1609850174).

I hope this helps. Feel free to reopen this issue if it doesn't.
