### ISSUE TITLE
[Bug] ElasticSearch {{term fieldname}} Alias Pattern not replaced when value is numeric zero (0)

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#7323]
Grafana 4.2 pre

Elasticsearch source

I have a "Terms" "Group By" variable `client` which can have the values 0, 1, 2, and 3. Whenever the value is 0, my Alias pattern `{{client}}` is not replaced with the character `0` but instead the string `{{client}}` shows in the data series. This looks like a bug to me.

Please see screenshot

![image](https://cloud.githubusercontent.com/assets/345210/22174294/007021b6-dfdb-11e6-9995-7bd07dfb2aa2.png)

**Comment by towolf** [comment]
Sweet thanks!

**Comment by LeThuyVN** [comment]
sorry, may you describe detail how to solve this issue?

**Comment by towolf** [comment]
@LeThuyVN if you have the same issue, then you need to upgrade to the latest Grafana. The bug was fixed long ago.

Otherwise, I do not know what you are asking.

**Comment by LeThuyVN** [comment]
hii towolf,
I want to create dynamic value for field, when the variable change the value in field will change automatically. Like

$field {"find": "fields", "type": "keyword"}    >>> List all fields we have with type = keyword
when we chose value of fields we have corresponding results for $query
$query {"find": "terms", "field": "$field"}

for example if $field is source.keyword
$query is /usr/share/filebeat/customerLogs/counters1
/usr/share/filebeat/customerLogs/counters2
/usr/share/filebeat/customerLogs/counters3
/usr/share/filebeat/customerLogs/counters4
.....

similar if the value of $field changes to hostname.keyword, server.keyword, ... we have values for $query
