### ISSUE TITLE
explore: many gf-show-context.svg request

### ISSUE THREAD

**Issue by lovesharepc** [grafana/grafana#73256]
### What happened?

query loki log will generate many `/public/img/icons/custom/gf-show-context.svg` request
![image](https://github.com/grafana/grafana/assets/1570732/cc48c03e-0e39-4560-9af8-55c1ff7d9ecd)

### What did you expect to happen?

there should 1  gf-show-context.svg request

### Did this work before?

in grafana 9.4
ther is no problem

### How do we reproduce it?

just use grafana query loki log

### Environment (with versions)?

Grafana: 10.0.3
Loki: 2.8.3
OS: ubuntu 22.04
Browser: chrome

### Grafana platform?

Docker

**Comment by lovesharepc** [comment]
@mellieA  yes I still seeing this problem 
my grafana is use docker to run
grafana version: 10.0.3
loki version: 2.8.3

**Comment by svennergr** [comment]
Hi @lovesharepc,

thanks for reporting this. This should be solved by https://github.com/grafana/grafana/pull/71354 and you should see this from Grafana 10.1.

Best regards,
@svennergr
