### ISSUE TITLE
Config database host example includes port

### ISSUE THREAD

**Issue by halt-hammerzeit** [grafana/grafana#7325]
```
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = sqlite3
host = 127.0.0.1:3306
name = grafana
```

```
pq: unknown response for startup: 'J'
```

I was having this error with Grafana and `host = 127.0.0.1:3306`.
When I changed it to `host = 127.0.0.1` it seemed to work.

**Comment by torkelo** [comment]
if you use sqlite3 is should not matter, that option is not looked at. 

fo rmysl or postgres it is looked at

**Comment by halt-hammerzeit** [comment]
So why are you providing a knowingly wrong configuration example for a user there?
Do you deliberately want to waste their time and confuse them?

**Comment by torkelo** [comment]
not sure what you mean, it is not wrong if you change to mysql. And if you use the default db type (sqlite3) the option is completely ignored. 

I do not think the problem you had with `host = 127.0.0.1:3306` and changing to `host = 127.0.0.1` had anything to do with each other. But that is my guess, could be wrong. It's just that the default has always been `host = 127.0.0.1:3306` and so far no one has had an issue with that value.

**Comment by halt-hammerzeit** [comment]
Oh, ok, that turned out to be not Grafana error indeed, it's just my database listening on 5432 instead of 3306.
False alarm then.
