### ISSUE TITLE
[Feat Req] MetricSegments are not debounced

### ISSUE THREAD

**Issue by fzakaria** [grafana/grafana#7326]
Please include this information:
- What Grafana version are you using?
V4.0

- What datasource are you using?
Custom

- What OS are you running grafana on?
OSX & Linux (Ubuntu)

- What did you do?
Write a datasource plugin that uses a metric segment

- What was the expected result?
The expected result is that the `get-options` should be debounced.

- What happened instead?
I have the `get-options` hooked up to an angular REST call and it makes the call every keystroke!

**Comment by daniellee** [comment]
We won't be fixing this bug as we have ported the MetricSegment component from Angular to React. This Angular component will eventually be phased out. You can see the new React Segment component here https://developers.grafana.com/ui/latest/index.html?path=/docs/data-source-segment-segmentasync--array-options

There is also a new cascader component that overlaps with the old segment component: https://developers.grafana.com/ui/latest/index.html?path=/story/forms-cascader--simple
