### ISSUE TITLE
Cloudwatch: Unexpected token error when creating a new datasource

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#73294]
![Screenshot 2023-08-15 at 12 36 05 PM](https://github.com/grafana/grafana/assets/6620164/906f581a-8e7f-4a46-9eeb-37b05a242092)

To recreate:
- update custom.ini to:
```
[aws]
allowed_auth_providers = keys
```
(this mimics what happens in Grafana Cloud
- create a new datasource

This happens because we are loading regions before we have the auth to do so and not properly handling the error.

**Comment by danfoxley** [comment]
I'm getting similar when working with Variables.

**Comment by sarahzinger** [comment]
@danfoxley thanks so much for reporting this issue! I believe what's happening is similar issue to the one above but slightly different.

In both cases our backend is throwing an error as a string rather than as an error object, and our frontend code is trying to parse it as json which means we never see the original error message and instead get this nonsense about not being about to parse json. But the root error messages are different. In the first here when creating a new datasource, it happens reliably every time. In your situation, I haven't been able to recreate it so I'm not sure where that error is being thrown.

If you open your network tab it will probably show the original error as a string. If you can open up a new ticket with that error message that will help us to identify what's happening and help to fix the experience.

**Comment by danfoxley** [comment]
@sarahzinger 

>  If you can open up a new ticket

Is that a new issue in Github, or a ticket with Grafana? I'm a cloud customer, but this is on OSS Grafana.

**Comment by sarahzinger** [comment]
@danfoxley a new ticket in Grafana would be great since this is OSS! Thanks again
