### ISSUE TITLE
alert error

### ISSUE THREAD

**Issue by hellwen** [grafana/grafana#7331]
grafana 4.1.1

metrics: SELECT mean(load5) as load5 FROM "system" WHERE "host" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc

"Test rule" in alert, the grafana log:

DBUG[01-23|17:00:20] Influxdb request                         logger=tsdb.influxdb url="http://139.199.73.164:32003/query?db=telegraf&epoch=s&q=SELECT+mean%28load5%29+as+load5+FROM+%22system%22+WHERE+%22host%22+%3D~+%2F%5E%24server%24%2F+AND+time+%3E+now%28%29+-+1m+GROUP+BY+time%2850ms%29%2C+%2A+ORDER+BY+asc"

alert rule does not deal the $server variable

if i repalce the $server to a string , the alert is going to work..

**Comment by hellwen** [comment]
i finded the answer in : http://docs.grafana.org/alerting/rules/

**Comment by bergquist** [comment]
Closing since you found the answer.
