### ISSUE TITLE
Logs: Create unit test for LogsContainer

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#73328]
`<LogsContainer>` is the higher level component we have when Logs are used in Explore, analog to `<LogsPanel>` for dashboards. We don't have any coverage for this component, and it is the ideal place to create an integration test for all children components, asserting things such as:

- Loading states
- Log rendering
- Log details
- Log details filters (hide, show, receive callbacks from the component, etc).

**Comment by TharinduBalasooriya** [comment]
@matyax Hi , I would like to work on this , can you assign this to me

**Comment by matyax** [comment]
Hey @TharinduBalasooriya ! Thank you for your interest in this task! Just as an FYI, adding tests to this component is not going to be trivial, because of the context and mocking required. So if you're looking for some low hanging fruit or a relatively simple task, this might not be it. If you're up to the challenge, feel free to submit the PR, we'll gladly review it.
