### ISSUE TITLE
grafana failded

### ISSUE THREAD

**Issue by h0x00i** [grafana/grafana#7332]
I do not know what happened. But after a few days work. it broke down

![image](https://cloud.githubusercontent.com/assets/4295831/22197630/13a9d57c-e168-11e6-9661-79a5367d6f0a.png)

Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxdb
- What OS are you running grafana on? Linux / rasbian
- What did you do? sensor monitoring 
- What was the expected result?
- What happened instead? failed on start service

**Comment by bergquist** [comment]
Could you please attach grafanas log file?

**Comment by h0x00i** [comment]
![image](https://cloud.githubusercontent.com/assets/4295831/22197966/9c31f586-e169-11e6-83b1-620bd63cd808.png)

**Comment by h0x00i** [comment]
I do not use these ports :3000

**Comment by h0x00i** [comment]
grafana.ini

![image](https://cloud.githubusercontent.com/assets/4295831/22198130/66a20626-e16a-11e6-8baf-56af137a4331.png)

**Comment by torkelo** [comment]
> I do not use this port:3000 

What do you mean? your config file has not changed the default 3000 port. You mean something else is not using it? But something is using port 3000.
