### ISSUE TITLE
[Bug] Wrong escape sequence with prometheus data-source

### ISSUE THREAD

**Issue by homelessnessbo** [grafana/grafana#7333]
Huy, guys!

Thank you for your product! 

- Grafana v4.1.1
- Prometheus datasource
- Running in grafana/grafana:4.1.1 docker image
- What I did: I've created single stat panel with simple query that return single value, example:
`my_prometheus_metric{label1="$grafana_var1", label2='$grafana_var2'}`, where `grafana_var2` - is fqdn of some host. 
- What I expected: current value
- What I got: null
- What I see in console: `linkToPrometheus` variable take a value that I can use to check how it was generated. So, when I paste it into address string of my browser to check it inside prometheus web interfecae - I can see that $grafana_var2 which is supposed to be a fqdn - takes a value of 'my\\\\.host\\\\.domain' instead of 'my.host.domain' (dots are double-backslashed), and prometheus could not parse it as valid request.
- Workaround: change `label2='$grafana_var2'` to `label2=~'$grafana_var2'` (make it regexp), so prometheus is able to parse it.

So, as I said there is small workaround for this, but anyway I think it's not the way it should work.

**Comment by bergquist** [comment]
If the template variable is a multi select or contains the all options the query will be rendered as an regexp. Which requires =~ 

I guess we could make this more obvious. But I'm not sure how.

**Comment by homelessnessbo** [comment]
ok, got you. So its not a bug, but expected behavior, right?

But is there a symbol of the start line and the end of it in that regexp? (Im sorry, I tried to read source code here: https://github.com/grafana/grafana/blob/05d43999dc83c2adc5bda27eb8e41e0b762c35ea/public/app/plugins/datasource/prometheus/query_ctrl.ts, but Im not strong with js )

Because if there is no startline-endline symbols - its possible 'multiple result' errors for single-value panels.

Example: I have hosts 'host' and 'host1', when I chose 'host' as a template variable value - regexp will match both. Isn't it?

**Comment by bergquist** [comment]
No there is not start/stop char by default. But you can add that yourself if you like to.

ex ```$queries{app=~"/$app/"}```

**Comment by homelessnessbo** [comment]
Ok. Thank you for explaining!

**Comment by bergquist** [comment]
NP :)
