### ISSUE TITLE
format date error

### ISSUE THREAD

**Issue by xiazemin** [grafana/grafana#73354]
### What happened?

 ${__from:date:'YYYY-MM-DD HH:mm:ss'}
${__to:date:'YYYY-MM-DD HH-mm-ss'}

got
'2023-08-17 10  
AND
 '2023-08-17 10-51-59'

### What did you expect to happen?

 ${__from:date:'YYYY-MM-DD HH:mm:ss'}
${__to:date:'YYYY-MM-DD HH-mm-ss'}

got
'2023-08-17 10:51:59'
AND
 '2023-08-17 10-51-59'

### Did this work before?

not

### How do we reproduce it?

1.: support transform

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by qmonitoring** [comment]
@xiazemin there is a workaround, see this post
https://community.grafana.com/t/global-variable-fromyyyy-mm-ddthhss-not-working/79645

**Comment by xiazemin** [comment]
```
${__from:date:YYYY-MM-DDTHH}:${__from:date:mm}:${__from:date:ss}
```
works for me but it looks ugly

**Comment by mellieA** [comment]
@xiazemin it's behaving as expected, but I can mark this as a feature request
