### ISSUE TITLE
Alerting: 9.2.x silenced alert is still sending notifications

### ISSUE THREAD

**Issue by luixx** [grafana/grafana#73356]
### What happened?

We have alerts which are working fine. We send the alerts to zuilip and the messages are arriving as expected. We know want to silence the alert. The alerts are still producing messages. In the silence tab is doesn't show that any alert is affected. The silences are also not showing up at the beginning when you open the tab. After refreshing the page a couple times they show up.

### What did you expect to happen?

The expectation is that the alert messages are not delivered when the we put a silence on it. Also i would expect that it shows the connected alert in the silence tab.s
![silence](https://github.com/grafana/grafana/assets/66642/11c2cce1-bb83-4c53-b886-498f3d0e0b79)

### Did this work before?

We started working with it in our current version 9.2.17 so i can not say if this worked before. 

### How do we reproduce it?

1. Create a alert
2. Open the alert on the page alert page and press the silence button
3. create the silence with the configuration it suggest (just put a longer time range e.g. 2 days)
4. force the alert to be triggered

### Environment (with versions)?

Grafana: 9.2.17
OS: Docker/Linux
Browser: Firefox 116.0.2

### Grafana platform?

Docker

**Comment by mellieA** [comment]
Tried this out on Grafana 10.2 and it's working as expected. Are you able to give the newer version a try? 

![Screenshot 2023-08-17 at 2 12 24 PM](https://github.com/grafana/grafana/assets/18175287/e00cdd7e-9d99-45b8-acef-a3e352c4b918)

**Comment by luixx** [comment]
Thank you for trying this out. i will discuss this if it is possible to switch to a newer version.

**Comment by luixx** [comment]
We can no switch so easy to a newer version. Is there a possibility to test this with a 9.x version so someone can confirm that it is a bug. If it is a bug will be there a fix?  Thanks
