### ISSUE TITLE
[BUG] Templating ES 5.x

### ISSUE THREAD

**Issue by txisme** [grafana/grafana#7335]
Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Cent OS 7.2
- What did you do? Updated Grafana and Elasticsearch
- What was the expected result? To see the data plotted using a template variable 
- What happened instead? Template query fails

Recently upgraded Elastic Search and grafana and now templating does not work at all.

![image](https://cloud.githubusercontent.com/assets/10253258/22201869/80e94ca4-e15d-11e6-86e6-fded16ac4e75.png)
![image](https://cloud.githubusercontent.com/assets/10253258/22201890/8ea4321e-e15d-11e6-8a71-c0f63d5d1f45.png)
![image](https://cloud.githubusercontent.com/assets/10253258/22201908/9ee64dce-e15d-11e6-932a-0e337a99bb8f.png)

I am sure that there are values that should be returned, this was working before correctly and there is correct data in ES. What is causing this?

Is templating not working for ES 5.x?

**Comment by torkelo** [comment]
Have you specified ES version in your grafana datasource options?

**Comment by txisme** [comment]
yes i have. Everything works fine if i dont use the template variable.

**Comment by txisme** [comment]
If anyone is interested i managed to solve the problem.

Due to the new ElasticSearch 5.x, Text fields are no longer considered "fielddata", and they have to be if you want any query (like on grafana) to work.

You can read more about it here: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/fielddata.html

And here is how to enable fielddata on a specific text variable:

curl -XPUT 'localhost:9200/my_index/_mapping/my_type?pretty' -d'
{
  "properties": {
    "my_field": { 
      "type":     "text",
      "fielddata": true
    }
  }
}
'
