### ISSUE TITLE
DateTimePicker: doesn't trigger change event when input is updated

### ISSUE THREAD

**Issue by asimonok** [grafana/grafana#73358]
### What happened?

Hi Grafana Team,
We faced an issue with DateTimePicker component - https://github.com/grafana/grafana/blob/98f3b5fecb148f886fdec8c999684536e29e6598/packages/grafana-ui/src/components/DateTimePickers/DateTimePicker/DateTimePicker.tsx#L209C8-L209C8

By the code, the component should allow enter date through input field, but changes within the field don't trigger onChange function. Selecting date in the popover works as expected.
Please look at the video with the issue.

https://github.com/grafana/grafana/assets/15867703/fe6add8e-6193-45cc-8ab5-97e92f9aba3d

Probably there is an code logic problem. 

`isDateTime(internalDate.value)` is always `false` because `internalDate.value` is a string

```
const onChangeDate = useCallback((event: FormEvent<HTMLInputElement>) => {
  const isInvalid = !isValid(event.currentTarget.value);
  setInternalDate({
    value: event.currentTarget.value,
    invalid: isInvalid,
  });
}, []);
    
const onBlur = useCallback(() => {
  if (isDateTime(internalDate.value)) {
    onChange(dateTime(internalDate.value));
  }
}, [internalDate.value, onChange]);
```

### What did you expect to happen?

On Change function should be triggered by input change as how it works for date selection within the popover. Also would be great to add ability to clear value.

### Did this work before?

No

### How do we reproduce it?

1. Open DateTimePicker in Storybook - https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-datetimepicker--basic
2. Enter any valid value `2023-08-16 09:35:16` into the input
3. Click outside the input

### Environment (with versions)?

Grafana: Latest
OS: Mac OS
Browser: Google Chrome 115.0.5790.170 

### Grafana platform?

None

**Comment by mellieA** [comment]
If you use the dropdown to select the new input and then click to the side there is an **apply** button to update the time

https://github.com/grafana/grafana/assets/18175287/4a47fff7-156c-43c6-a60d-61fd10e3881b

**Comment by mikhail-vl** [comment]
@mellieA Dropdown works. The same time input allows to update the value which is not saved properly, which is confusing for end users.

**Comment by mellieA** [comment]
@asimonok even though this works, I'm going to have the dev squad for storybook take a look. It's not initially clear that you need to click outside of the time dropdown to see the apply button.

**Comment by tolzhabayev** [comment]
Moving to @grafana/grafana-frontend-platform
