### ISSUE TITLE
Grafana 10 > Alerting > Add Silence > bad matcher format when label contains dot

### ISSUE THREAD

**Issue by fkalinowski** [grafana/grafana#73369]
### What happened?

Since Grafana 10, when I add a new Silence to a triggerd Alert, instead of getting the "Affected alert instances" I've got the following error:

> Preview not available
> Error occured when generating affected alerts preview. Are you matchers valid?

If I look into the HTTP request performed I can see that the following request
`GET /api/alertmanager/grafana/api/v2/alerts?filter=label.with.dots.and.slash%5Ctest%3Dwarning` returns the following error **HTTP-400**: `
{
    "message": "bad matcher format: label.with.dots.and.slash\\test=warning: unable to retrieve alerts",
    "traceID": ""
}
`

The problem seems due to the '.' (dot character) present in my label. If I use labels without dot I have no problem.

Since I use an ElasticSearch datasource, it is very common to have dots or even slashes in my labels.

Even if I've got an error while generating affected alerts preview, I'm able to submit my Silence and it will work as expected

### What did you expect to happen?

I expect no error and having displayed the affected alerts preview.

### Did this work before?

This problem appeared when I've upgrade to Grafana 10.0.3.
I've downgraded to Grafana 9.5.1 and the problem don't occur.

### How do we reproduce it?

1. Go to "Home"
2. Go to "Alerting"
3. Go to "Silences"
4. Click on button "+ Add Silence"
5. Fill a Matching labels with following fields (without double quote)
 * Label: "label.with.dots" 
 * Operator: "="
 * Value: "test"
==> then the popup message `bad matcher format: label.with.dots=test: unable to retrieve alerts` will appear and you won't have any preview of the affected alert instances

### Environment (with versions)?

Grafana: 10.0.3
OS: Linux
Browser: Brave 1.56.20

### Grafana platform?

Kubernetes

**Comment by mellieA** [comment]
@fkalinowski I'm seeing the same problem with my test scenario for dots. 

I use {{ index $labels "netflow.ipv4_dst_addr" }} in an annotation to get the labels, but then they are created with dots and I'm not able to use that label to match silences.

**Comment by armandgrillet** [comment]
This will require https://github.com/prometheus/alertmanager/pull/3453 to be merged and then our Prometheus dependencies to be updated. Assigning this to @grobinson-grafana as he is working on the Alertmanager PR.

**Comment by fkalinowski** [comment]
Hi @armandgrillet, @grobinson-grafana 

The PR https://github.com/prometheus/alertmanager/pull/3453 has been merged.
When do think it can be brought into Grafana ?

**Comment by grobinson-grafana** [comment]
Hi! 👋 We also need to link it up to amtool and then Alertmanager server before we can bring it into Grafana. Here is the issue tracking this work https://github.com/prometheus/alertmanager/issues/3486.

**Comment by yordanmanov** [comment]
Hello,
We are experiencing the same issue on Grafana v10 running on ec2 instance.
<img width="1710" alt="Screenshot 2023-12-21 at 14 24 29" src="https://github.com/grafana/grafana/assets/65708360/48b0314c-9c9a-401e-a630-e4f66926bdc0">
<img width="1706" alt="Screenshot 2023-12-21 at 14 24 40" src="https://github.com/grafana/grafana/assets/65708360/d25cf962-11ea-40c0-9c48-db2ebd655585">
We tried escaping the dot with a \ before it, but still it errors.

**Comment by grobinson-grafana** [comment]
This is being tracked in https://github.com/grafana/alerting/pull/155 and https://github.com/grafana/grafana/pull/81512.

**Comment by grobinson-grafana** [comment]
I'm closing this as this is available in Grafana 11 and Grafana Cloud.
