### ISSUE TITLE
grafana db migration not working

### ISSUE THREAD

**Issue by varunsrinath** [grafana/grafana#7337]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?-  4.0
- What datasource are you using? - sql lite
- What OS are you running grafana on? - linux
- What did you do?
I am trying to upgrade the grafana from 2.3 to to new 4.0 version, was trying to copy the existing sqllite db into the new version 
- What was the expected result?
the db migrations scripts run fine, I can see all the existing dashboards. However when I try to create a new dashboard it say problem , Dashboard not found
- What happened instead?
not able to save any new dashboard, I ensure the user and group is proper as per https://github.com/grafana/grafana/issues/4418.  Copying the .db file to the new location and server restart should do the trick? am i missing something?

**Comment by varunsrinath** [comment]
one more point to add is, even when i am saving the dashboard for the first time , it always pop's out save-as window. on ctrl+s it always shows save-as modal pop u.

**Comment by torkelo** [comment]
Did you get any error during startup? You said db migration is not working but not seeing any migration error, did you check grafana.log and see a migration error? 

You say you get an error when you create new dashboard, what does the grafana.log say? 

When you copied the database from the old installation did you make sure it had the right user / group permissions (needs write/read permission from the grafana user)

**Comment by varunsrinath** [comment]
No I don't get this error during start up. I don't see any migration errors in the log files. Grafana log just print 404 for the API call and does not print anything else. I did check the permissions on the db user and group as mentioned earlier I am able to update an existing dashboard . I am just not able to create one.

**Comment by varunsrinath** [comment]
Can I migrate th from 2.0 version to 4.0 without having migrate it to 3.0? Do you think that could be the issue ?
