### ISSUE TITLE
Alerting: webhook (test) alert error

### ISSUE THREAD

**Issue by dorinpirvu** [grafana/grafana#73380]
### What happened?

When testing a webhook CP that has worked until recently, I get the error: "failed to validate integration "test" of type "webhook" both HTTP basic authentication and Authorization Header are set and only 1 is permitted".
See attached photos from which I don't understand that both options would be selected...
_The problem is that without this test working, I have no guarantee real alerts are sent via the webhook.
And i haven't received alerts in 1-2 weeks, not sure if there were really no alerts, or if it's the webhook CP not working_.

![webhook_cp_settings](https://github.com/grafana/grafana/assets/127939087/580b2742-f19c-451d-88a0-bcb6242d4bc4)
![webhook_cp_error](https://github.com/grafana/grafana/assets/127939087/fd041df8-24cb-4e6f-ba5d-419bf67b6143)

### What did you expect to happen?

not receive the error

### Did this work before?

yes, it worked before

### How do we reproduce it?

have no idea how to reproduce

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.0.3 (eb8dd72637)
OS: Ubuntu 22.04.2 LTS
Browser: Edge (Version 114.0.1823.79 (Official build) (64-bit))

### Grafana platform?

A downloaded binary

### Datasource(s)?

nothing specific as far as can be determined

**Comment by mellieA** [comment]
@dorinpirvu is there anything (spaces or other characters) in the authorization header credentials box? 

I tested on my instance and the webhook test works if there aren't any characters in the header text boxes.

**Comment by dorinpirvu** [comment]
@mellieA there are no characters in either of the Authorisation Header boxes.
More than that, if i enter anything in both boxes, I can not save the CP.
On the other hand, I just received an alert that was passed via this webhook, so that's good news, it seems to have something only with the testing, not the actual execution.
I'm not sure if this error message appears because the Grafana mechanism checks something or if it is a response from the REST server

**Comment by dorinpirvu** [comment]
I have just upgraded Grafana to version v10.0.3 (eb8dd72637) and the issue no longer appears (no other modifications done to CP).
I will monitor this for ~1 week and if it no longer appears I will close the issue.
Thanks!
