### ISSUE TITLE
[Bug] Empty Dashboard name => Impossible to delete

### ISSUE THREAD

**Issue by lyrixx** [grafana/grafana#7339]
> - What Grafana version are you using?

4.1.1 (at least in CLI)

> - What datasource are you using? 

influxdb

> - What OS are you running grafana on? 

ubuntu

> - What did you do? 

I think my issue came from the fact I imported a bad `json` file (yes without name nor extension, just `json`).

> - What was the expected result?

An error

> - What happened instead?

And "empty" dashboard was imported. and now I can not delete it.

![screenshot1](https://cloud.githubusercontent.com/assets/408368/22228369/f79f26e8-e1d0-11e6-9ba2-fb604e050f82.png)

When I click on it (url `grafana.com/dashboard/db/`):

![screenshot3](https://cloud.githubusercontent.com/assets/408368/22228405/3ceacc5c-e1d1-11e6-9794-6947ec892a5b.png)

**Comment by utkarshcmu** [comment]
For now, just go into your Database and delete the row from the dashboard table which has empty slug column.

**Comment by lyrixx** [comment]
@utkarshcmu thanks. I tried to do that, but at the first glance it was all in JSON. I will have a better look this evening.

**Comment by lyrixx** [comment]
`delete from dashboard where slug='';` does the trick, thanks.

**Comment by utkarshcmu** [comment]
Awesome. 👍

**Comment by jessabe** [comment]
It's no longer possible to create empty dashboards. If you are still having problems with this though, feel free to open another issue, or comment on this and we can re-consider. Thanks!
