### ISSUE TITLE
Dashboard Snapshot Cleanup Job

### ISSUE THREAD

**Issue by joepallotta39** [grafana/grafana#73410]
### What happened?

The Grafana Cleanup Job to remove expired dashboard snapshots impacts Grafana performance and spikes DB resource consumption.
We do not store many snapshots, so this really should be a light weight job.
- Grafana 9.5.1
- MySQL Aurora DB
- Snaphots stored locally, not externally. 

Impact: (Enabled -> Disabled Job)
CPU Usage (30% -> 11%): 2/3 of CPU utilization were the snapshot expire job.
Memory Usage(Available memory went from 1.5gb -> 4.5gb): 3x more available memory after disabling the job
Read IOPS: (600/second -> < 1/second): This seems to be the larger issue
Queries: (~225/second -> ~125/second)
Read Throughput: (10M/second -> ~125k)
Select Throughput: (~75/second -> ~38/second)
Delete Latency: (~60seconds -> 0 after disabling)

### What did you expect to happen?

There seems to be a lot of issues with the cleanup job:
The job accounted for >50% of all DB Reads, and ~99% of read throughput. 
The Delete operation is slow, and needs to be fixed but I think the larger impact is from the [reads.

### Did this work before?

Unclear when the regression started, we just upgraded to Grafana 9, and did not use the expire snapshot cleanup feature in the past. 

### How do we reproduce it?

1. Enable Snapshot expire job
2. Profile Database Metrics
3. 

### Environment (with versions)?

Grafana: 9.5.1
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

MySQL Aurora RDS

**Comment by mellieA** [comment]
@joepallotta39 thank you for sharing the profiling information and description of the issue. Can you tell us what the hardware configuration is for the DB server? 

CPU cores & speed: 
RAM: 
Disk Type:
Disk speed:

**Comment by joepallotta39** [comment]
Hi @mellieA ! We're running Grafana on AWS Aurora MySQL 5.7
R4.large 
1xCore, 2vCPU
15.25 GiB Mem
10 Gbps
Unfortunately I don't have any error logs, and we since disabled the job.
