### ISSUE TITLE
Table Panel: Colorize Rows in Table Panel

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73428]
### Discussed in https://github.com/grafana/grafana/discussions/38151

<div type='discussions-op-text'>

<sup>Originally posted by **mertbakir** September 11, 2020</sup>
**What would you like to be added**:

1. Banded Rows (for easy read)
2. Select a category variable (field) and let users set colors for each value and colorize whole row. 
Values can be text or numeric. For example I've a table and a column which can contain numbers 0 1 2. I should be able to set 
0 = green
1 = yellow
2 = red.

Similarly I might have a table and column which contains categorical text field eg. ok warning critical. I should be able to set
ok = green
warning = yellow
critical = red

3. One more improvement over the 2. suggestion. We can have many categories instead of (ok, warning, critical) and these can be nominal instead of ordinal. For example, it can be name of cities. DC, New York, Istanbul, Madrid, Barcelona...
It would be great if grafana can set colors for each category with explicitly saying "Istanbul = Red, Madrid = Purple".

**Why is this needed**:

I open this issue over [this one](https://github.com/grafana/grafana/issues/27530). I think table panel is very important yet very limited compared to other features grafana provides.</div>

**Comment by bernierherve** [comment]
+1

**Comment by FeDLviv** [comment]
+1

**Comment by codeincarnate** [comment]
Oh boy, this has been a requested feature for awhile 😓 https://github.com/grafana/grafana/issues/11418

Sadly, it's been bumped by higher priority items. Can't say at the moment when exactly we'll be able to get to this but it's very much on the radar. Going to close this one in favor of the outstanding issue.

Definitely agree that there's more work to be done here and this is unfortunately lacking.

**Comment by autodepo** [comment]
+1

**Comment by Wakaij1n** [comment]
+1

**Comment by AhmedAburady** [comment]
+1

**Comment by warisp** [comment]
+1

**Comment by YuhanunCitgez** [comment]
Was this done?... it's closed

**Comment by creyl-seg** [comment]
+1

**Comment by AxelPatron** [comment]
+1

**Comment by josevu3e** [comment]
+1

**Comment by kerniston** [comment]
Hello.
Any updates?
