### ISSUE TITLE
Logs: Logs panel throwing error with transform

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#73425]
### What happened?

As part of research into https://github.com/grafana/grafana/issues/73089. We noticed that the logs panel can throw errors when receiving split queries.

`logsModel.ts:335 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')`

logsModel.ts:335:
`const ns = timeField.nanos[index].toString().padStart(6, '0');`

### What did you expect to happen?

Logs panel wouldn't throw errors

### Did this work before?

I can only reproduce this with extract fields transformation and split queries 

### How do we reproduce it?

1. Enable `lokiQuerySplittingConfig` and `lokiQuerySplitting` feature flags
2. Create a sparse loki query over a relatively long duration with json output `| json`
3. set the "Split Duration" (which should be "Split duration") to a shorter duration so you get your query split up a bit
4. create Extract fields transformation, with labels for source, and replace all fields/keep time are checked.

### Is the bug inside a dashboard panel?

[debug-Panel Title-2023-08-17 14_06_59.json.txt](https://github.com/grafana/grafana/files/12372794/debug-Panel.Title-2023-08-17.14_06_59.json.txt)

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by matyax** [comment]
https://github.com/grafana/grafana/pull/73505 should have resolved the error on the logs side.
