### ISSUE TITLE
Auto change light/dark theme based on system settings

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73429]
### Discussed in https://github.com/grafana/grafana/discussions/44521

<div type='discussions-op-text'>

<sup>Originally posted by **tommyip** January 27, 2022</sup>
Both MacOS and Windows support system-wide dark mode and can be toggled on/off based on the current time. It would great if there is an option in Grafana to automatically change the theme according to system preference. This can be done using CSS media query [perfers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).</div>

**Comment by mateuszdrab** [comment]
This can be closed as it was implemented in response to my issue https://github.com/grafana/grafana/issues/61339

**Comment by gelicia** [comment]
@mateuszdrab thank you for the update!

**Comment by 13xforever** [comment]
Currently there's no event listener for `prefs-clolor-scheme` change, nor styles have the `@media` selectors, as a result, you have to manually refresh the page to update the styles, which is not ideal.

**Comment by mateuszdrab** [comment]
That is true, perhaps an improvement can be made to this feature to make it respond to theme changes without reloading the page.
