### ISSUE TITLE
[Feature request] Allow actions from grafana dashboard

### ISSUE THREAD

**Issue by BinyaminSchein** [grafana/grafana#7343]
The point of monitoring and alerting is to detect and act,
I think it would be nice to have an option to run scripts from grafana, or attach a script to a custom button,
perhaps a console that can save the commands to create a script.

**Comment by jaimegago** [comment]
-1 I'd use the webhook notification to trigger a job using an orchestration framework/tool (e.g. Rundeck or Ansible). Keep Grafana as a "do one thing well" tool.

**Comment by BinyaminSchein** [comment]
Webhooks are only the answer when you know exactly what you want to happen, but complex actions that are to much work to script aren't solved that way. 
Proprietary monitoring software will always have ability to take relevant action if the administrator wants to - why shouldn't a generic monitoring system have the same ability? 
I understand the "do one thing well" philosophy but i think this is doing one thing - monitoring in it self is not complete without the actions the stem from said montiring, we have to think from the user's point of view what is one thing and not from the developer's point of view.

**Comment by utkarshcmu** [comment]
we can use webhook with "salt api" to trigger actions from Grafana!

**Comment by benitogf** [comment]
maybe related: https://community.grafana.com/t/button-in-dashboard/1556 :wave:

**Comment by benitogf** [comment]
works great with iframes too :+1: 

`<iframe title="The Wikipedia page for Avocados" src="https://en.wikipedia.org/wiki/Avocado"></iframe>`
