### ISSUE TITLE
State timeline panel: Pagination or scroll view support

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73436]
### Discussed in https://github.com/grafana/grafana/discussions/38303

<div type='discussions-op-text'>

<sup>Originally posted by **ashleyjlive** June 16, 2021</sup>
**What would you like to be added**:
Add pagination **or** scroll view support to state timeline panel.

**Why is this needed**:
State timeline has the potential to be a very powerful and valuable tool for monitoring uptime of a large number of nodes. In my initial testing I found that for a high number rows the view tends to squish and fit all rows into the fixed view - which makes it very hard if not impossible to read [1]. It would be better to either:
• Have pagination (page numbers, etc)
• Allow overflow and provide a scroll view within the window rather than trying to fit everything in the window

My preference is for a scroll view as that fits more with the style of what the graph and time series does when their legends contain more data than what can fit within the window.

[1]
![image](https://user-images.githubusercontent.com/9400511/122309256-5331b800-cf51-11eb-8417-b74c7e5dc302.png)</div>

**Comment by vfilter** [comment]
This has been open forever it seems and there is no interest from Grafana to fix it? Any hints as to what the priority of this might be?

**Comment by lkeijser** [comment]
The oldest issue I could find is from 2017.

The "let's move this to the discussion section" comment apparently meant something like: "that's interesting, please wait right there and I'll be with you shortly"

**Comment by tristanwl** [comment]
I would love to see support for this as well. This really isn't usable past 10 or so series :/

**Comment by aloubiex38** [comment]
+1

**Comment by CRASH-Tech** [comment]
+1

**Comment by nivaldodev** [comment]
+1

**Comment by maksimuimin** [comment]
+1

**Comment by nbahar-intel** [comment]
+1

**Comment by marcelus-oldoni** [comment]
+1

**Comment by stascooper** [comment]
+1

**Comment by Space2Man** [comment]
Can you please fix this issue? Since the discrete plugin is Angular based it won't be available as working alternative for ever ...

**Comment by yuis-ice** [comment]
I want scroll feature rather pagination. In pagination I cannot see the whole fields at a glance.

**Comment by yuis-ice** [comment]
@gelicia Thank you 🙏
