### ISSUE TITLE
Alerting: Unified Alerting doesn't have a way to see alert config history

### ISSUE THREAD

**Issue by evan-chaney** [grafana/grafana#73435]
### What happened?

In the legacy alerting world you could see the history of an alerts threshold/query using the dashboard version history, but this is no longer an option with Unified Alerting.

### What did you expect to happen?

I expected to be able to see configuration history for alerts.

### Did this work before?

Grafana 6.x

### How do we reproduce it?

Try and find what a threshold was a couple revisions ago.

### Environment (with versions)?

Grafana: 9.5.1
OS: CentOS 7
Browser: Google Chrome 114.0.5735.198

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by mellieA** [comment]
@evan-chaney in the new version of Grafana alerting 8.x + the dashboards and alerts are independent of each other. But I understand how a version of history could be helpful. For now, I'll mark this as a feature request.

**Comment by Karsonito** [comment]
> @evan-chaney in the new version of Grafana alerting 8.x + the dashboards and alerts are independent of each other. I understand how a version of history could be helpful. For now, I'll mark this as a feature request.

Any news about versioning of alert rules?
Still no reaction in discussion (
https://github.com/grafana/grafana/issues/73936
