### ISSUE TITLE
[Bug] Auth proxy breaks on upgrade to 4.x if user is not in LDAP

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#7344]
**- What Grafana version are you using?**
4.1.1
**- What OS are you running grafana on?**
Centos 7
**- What did you do?**
Upgraded to 4.1.1 from 3.x
**- What was the expected result?**
Auth proxy would keep working for Grafana-local users
**- What happened instead?**
If the user sent in auth proxy does not exist in the configured LDAP server, authentication fails.

Our setup is that normal users sign in with their AD credentials using the Grafana login page, but our dashboard screens (identified by being in a certain IP block) get the auth proxy header. They were then logged in as a Grafana-local user (ie one that does not exist in the AD).
[This PR](https://github.com/grafana/grafana/pull/6895) seems to add the requirement that any user logging in with auth-proxy also exists in LDAP. This is either a bug, or a non-documented breaking change.

**Comment by torkelo** [comment]
yes, sorry, this is a non-documented breaking change. 

LDAP enabled now requires that auth-proxy users also need to exist in ldap

**Comment by torkelo** [comment]
will add a notice to changelog

**Comment by torkelo** [comment]
btw, sorry if this is causing you upgrade issues, is there any chance you can setup a "dashboard-viewer" user in LDAP?

**Comment by carlpett** [comment]
That's what we ended up doing. It goes against the local policy to have such accounts, but all the black screens around the office made it possible...

**Comment by carlpett** [comment]
By the way, was it actually intentional to do this? I found it pretty useful to be able to have local users as well. The local admin account seems to still work, is that managed another way?
