### ISSUE TITLE
Canvas: Inline editor breaks when notification banner is present

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#73445]
A user noticed that they were unable to edit with the inline editor when a banner notification was present. It seems like that banner element takes precedence and removes the inline editor's selected state when trying to click on it.

While investigating we also noticed similar behavior when DevTools are enabled (though I have not been able to replicate this 🤔)

https://github.com/grafana/support-escalations/assets/107340764/f731ef48-f7a5-4205-a15c-63da739b1ff3

See https://github.com/grafana/support-escalations/issues/6915

**Comment by marybelvargas** [comment]
Hi @nmarrs,

As requested please find attached the recording while reproducing the issue with Dev Tools enabled. Please let me know if you need anything else from our side.

https://github.com/grafana/grafana/assets/107340764/e5b88ff7-5cf9-4b16-8928-ac6572c3e165
