### ISSUE TITLE
Add ability to map OAuth users to Grafana organizations

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73448]
### Discussed in https://github.com/grafana/grafana/discussions/39102

<div type='discussions-op-text'>

<sup>Originally posted by **treydock** April  9, 2020</sup>

**What would you like to be added**:

The ability for OIDC authentication to map people to a organization based on the claims returned during authentication.  This would be very similar to `role_attribute_path`.

Example:

```
org_attribute_path = contains(groups[*], 'staff') && 1 ||  3
```
**Why is this needed**:

Right now the only way to do anything close to this is use `auto_assign_org_id` then for people who need a different org, assign them to that org manually.  This doesn't actually work, see #22605.

This feature request may also resolve #16763</div>

**Comment by hbjydev** [comment]
:+1:

**Comment by sathieu** [comment]
There was a PR for this before. See https://github.com/grafana/grafana/pull/23661 which was refused.

What is the current Grafana Labs position on Multi-Org support ? Could https://github.com/grafana/grafana/pull/23661 be back ?

**Comment by hbjydev** [comment]
I'd like to bump this please.

**Comment by sathieu** [comment]
I think adding an `org_attribute_path` will be limited. What we want, it potentially several org to role mappings.

I propose to improve `role_attribute_path` to accept objects as return value.  Something like:

```ini
role_attribute_path = contains(groups[*], 'superadmin') && 'GrafanaAdmin' ||  [{OrgName: 'Main Org.', Role: 'Viewer'}, {OrgName: 'Another Org', Role: 'Editor'}]
```

WDYT?

**Comment by sathieu** [comment]
Proposed PR: https://github.com/grafana/grafana/pull/77683 (see the included example).
