### ISSUE TITLE
[Bug] - Alerting S3 Storage Franckfurt

### ISSUE THREAD

**Issue by JulienChampseix** [grafana/grafana#7345]
Hi Team,

I'm currently having an issue about s3 storage on alerting system.

- **Grafana version** : version=4.1.1 commit=v4.1.1 compiled=2017-01-12T08:48:03+0000
- **Datasource** : Influxdb
- **OS** : Ubuntu 16.04.1 LTS
- **Action** : Alerting using s3 storage based in Franckfurt
- **Result awaited** : storing image of alerting system on s3 Franckfurt
- **Result received** : `lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="unwanted http status 400: \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>XXX</RequestId><HostId>XXXXX</HostId></Error>\""`

If i change the s3 location to Ireland it's working so the problem looks based on authentification for Franckfurt.

Thanks for your help.

**Comment by mtanda** [comment]
I know the S3 behavior in Frankfurt is little strange.
But I think aws-sdk should handle it correctly.

https://github.com/grafana/grafana/pull/7058 may fix your problem.

**Comment by torkelo** [comment]
can you try 4.2-pre release build and see if your problem is solved?
