### ISSUE TITLE
Saga - Documentation DoD

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#73484]
We need to establish how documentation looks for Saga and a discussion of the minimum requirements needed to consider documentation done for now before iterating on it in the future.
```[tasklist]
### Tasks
- [x] Build 1-2 components out as examples
- [x] Update template to include agreed on minimum requirements
```

**Comment by JoaoSilvaGrafana** [comment]
[Documentation Template](https://docs.google.com/document/d/1wTaSWYif6Kz-2aBuP4R-HUkj9JwFsyYIwZroALQTQOs/edit#heading=h.k7kv6iubst6n)
