### ISSUE TITLE
Datasource Connection

### ISSUE THREAD

**Issue by tausif-bi** [grafana/grafana#7348]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? Grafana 4.1.1
- What datasource are you using? Postgres
- What OS are you running grafana on? Windows 10

I am new to Grafana, i need to use postgres as my data source from which i can fetch tables and make graphs accordingly.
Please help with the same.

**Comment by torkelo** [comment]
Postgres is not listed in the list of built in supported data sources: 
http://docs.grafana.org/datasources/ 

Nor is there an external plugin for it yet, but we are working on adding SQL support soon
