### ISSUE TITLE
[Feature request] Don't make queries to backend for a panel if old request is still in-flight

### ISSUE THREAD

**Issue by jsbali** [grafana/grafana#7349]
Not sure if it is currently available in grafana or not. 
So the requirement is we should be able to limit calls going from grafana to dataseries backend 
if the previous call for that panel hasn't completed yet. 
This requirement arises because say if the backend store is loaded then what happens is we effectively add more load on it by making calls by automatic refreshing or manual refresh.

Apologies if this is something which is in pipeline or I have missed anything

**Comment by torkelo** [comment]
Current in-flight request are cancelled if a panel issues queries before the old requests have completed.

**Comment by jsbali** [comment]
This cancellation is done on client end but the query is still being processed at the backend. 
I think we should wait for the previous query to run instead of cancelling this query and firing a new one. 
This way we are still doing redundant work in case of timeout from the data series but still we are giving enough time for our backend to recover. Your thoughts

**Comment by torkelo** [comment]
I don't think that is correct, network issues could then stall panels for a long time

**Comment by jsbali** [comment]
So the issue we are facing is say getting data for a long series is taking time greater than the refresh   time then we are just adding more misery to the system.
Also for network issues mostly all the queries will suffer and we still will be doing redundant work.  
Any other way we can solve for this.

**Comment by torkelo** [comment]
Not sure how to.
