### ISSUE TITLE
[Bug] Zoom doesn't show time series with group by (auto) < sampling interval

### ISSUE THREAD

**Issue by strocode** [grafana/grafana#7350]
Problem: I have data have a sampled every 5 minutes.
If I have the group by (auto) enabled in the query window, and I zoom into a region of < 1 day or so, the series disappears. Looking at the JSON reply, the data are  in there (interspersed with a lot of nulls) but the series isn't displayed.

Grafana grafana_4.1.1-1484211277_amd64.deb
Datasource: influxdb 1.1.1
OS: Linux ubuntu 4.8.6-x86_64

- What did you do?
Click and drag a region on a graph to indicate a zoom window.

- What was the expected result?
The series appears and is zoomed in

- What happened instead?
The series disappeared.

Workaround: set the group by query interval to 5m

- Working request:
GET /api/datasources/proxy/1/query?db=aemo&q=SELECT%20max(%22rrp%22)%20FROM%20%22dispatch_price%22%20WHERE%20%22regionid%22%20%3D%20%27SA1%27%20AND%20time%20%3E%201440731287019ms%20and%20time%20%3C%201441198699531ms%20GROUP%20BY%20time(5m)%20fill(null)&epoch=ms HTTP/1.1
Host: 139.162.32.79:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Referer: http://139.162.32.79:3000/dashboard/db/spot-prices?from=1440731287019&to=1441198699531
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=047449e50b45c0ed; grafana_user=admin; grafana_remember=eaa26ab653e40c08e7cc853edad78a29f8fa2ee0e3691192

{"results":[{"series":[{"name":"dispatch_price","columns":["time","max"],"values":[[1440731100000,null],[1440731400000,null],[1440731700000,null],[1440732000000,null],[1440732300000,null],[1440732600000,null],[1440732900000,null],[1440733200000,null],[1440733500000,null],[1440733800000,null],[1440734100000,null],[1440734400000,null],

... Lots more null values ....

[1440893100000,null],[1440893400000,61.76129],[1440893700000,54.99004],[1440894000000,54.99004],[1440894300000,54.99004],[1440894600000,54.98992],[1440894900000,54.99018],[1440895200000,54.99012],[1440895500000,54.99018],

.... Lots more data values:

After selecting a smaller region

GET /api/datasources/proxy/1/query?db=aemo&q=SELECT%20max(%22rrp%22)%20FROM%20%22dispatch_price%22%20WHERE%20%22regionid%22%20%3D%20%27SA1%27%20AND%20time%20%3E%201440949528246ms%20and%20time%20%3C%201440964993275ms%20GROUP%20BY%20time(10s)%20fill(null)&epoch=ms HTTP/1.1
Host: 139.162.32.79:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Referer: http://139.162.32.79:3000/dashboard/db/spot-prices?from=1440949528246&to=1440964993275
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=047449e50b45c0ed; grafana_user=admin; grafana_remember=eaa26ab653e40c08e7cc853edad78a29f8fa2ee0e3691192

{"results":[{"series":[{"name":"dispatch_price","columns":["time","max"],"values":[[1440949520000,null],[1440949530000,null],[1440949540000,null],[1440949550000,null],[1440949560000,null],[1440949570000,null],[1440949580000,null],[1440949590000,null],[1440949600000,null],[1440949610000,null],[1440949620000,null],[1440949630000,null],[1440949640000,null],[1440949650000,null],[1440949660000,null],[1440949670000,null],[1440949680000,null],[1440949690000,null],[1440949700000,null],[1440949710000,null],[1440949720000,null],[1440949730000,null],[1440949740000,null],[1440949750000,null],[1440949760000,null],[1440949770000,null],[1440949780000,null],[1440949790000,null],[1440949800000,45.99004],[1440949810000,null],[1440949820000,null],[1440949830000,null],[1440949840000,null],[1440949850000,null],[1440949860000,null],[1440949870000,null],[1440949880000,null],[1440949890000,null],[1440949900000,null],[1440949910000,null],[1440949920000,null],[1440949930000,null],[1440949940000,null],[1440949950000,null],[1440949960000,null],[1440949970000,null],[1440949980000,null],[1440949990000,null],[1440950000000,null],[1440950010000,null],[1440950020000,null],[1440950030000,null],[1440950040000,null],[1440950050000,null],[1440950060000,null],[1440950070000,null],[1440950080000,null],[1440950090000,null],[1440950100000,45.99004],[1440950110000,null],[1440950120000,null],[1440950130000,null],[1440950140000,null],[1440950150000,null],[1440950160000,null],[1440950170000,null],[1440950180000,null],[1440950190000,null],[1440950200000,null],[1440950210000,null],[1440950220000,null],[1440950230000,null],[1440950240000,null],[1440950250000,null],[1440950260000,null],[1440950270000,null],[1440950280000,null],[1440950290000,null],[1440950300000,null],[1440950310000,null],[1440950320000,null],[1440950330000,null],[1440950340000,null],[1440950350000,null],[1440950360000,null],[1440950370000,null],[1440950380000,null],[1440950390000,null],[1440950400000,45.99004],[1440950410000,null],[1440950420000,null],[1440950430000,null],[1440950440000,null],[1440950450000,null],[1440950460000,null],[1440950470000,null],[1440950480000,null],[1440950490000,null],[1440950500000,null],[1440950510000,null],[1440950520000,null],[1440950530000,null],[1440950540000,null],[1440950550000,null],[1440950560000,null],[1440950570000,null],[1440950580000,null],[1440950590000,null],[1440950600000,null],[1440950610000,null],[1440950620000,null],[1440950630000,null],[1440950640000,null],[1440950650000,null],[1440950660000,null],[1440950670000,null],[1440950680000,null],[1440950690000,null],[1440950700000,45.99004],[1440950710000,null],[1440950720000,null]

etc.. i.e. a non-null value every 300000 times

**Comment by torkelo** [comment]
Set a lower limit in the group by time option below your queries or in data source options to set it globally for that data source. In your case set `>5m`
