### ISSUE TITLE
[Bug] ip address variable not resolving correctly in prometheus query

### ISSUE THREAD

**Issue by amacrae2** [grafana/grafana#7351]
I'm trying to use a query template variable that represents various ip addresses (eg. 172.17.0.1). 

The template variable appears correctly when I reference it in the title of a panel. For example if my title is `ip = $ip`, I get `ip = 172.17.0.1`. However, if I use the variable in a Prometheus query, I get "no datapoints" (even if there should be datapoints available). I can verify that datapoints are available for the given ip because replacing `$ip` in the prometheus query with 172.17.0.1 produces the expected datapoints. 

Specifically, the prometheus query I am working with is:

time_hist_bucket{ip='$ip'}  <-- Doesn't work

time_hist_bucket{ip='172.17.0.1'}  <-- works

**Comment by torkelo** [comment]
Try disabling All and multi value in template variable options, as you are not using a regex operator so the variable can only contain single value,

**Comment by amacrae2** [comment]
Dissabling multi value in variable options does allow `$ip` to resolve correctly in the prometheus query. However, the template variable can indeed have more that one value (as it comes from a separate `label_values(ip)` prometheus query). My end goal is to have a row of panels that repeats on selected values of my `ip` variable, so I would need to have multi value enabled (which brings me back to my original question), correct?

**Comment by torkelo** [comment]
if you have multi values enabled you need to use a regex operator for it to work otherwise Prometheus query language wont accept it. so time_hist_bucket{ip=~/$ip/}

**Comment by amacrae2** [comment]
Thanks, ended up getting it working with `time_hist_bucket{ip=~'$ip'}`
