### ISSUE TITLE
Threshold Line has wrong orientation when Bar Chart is horizontal

### ISSUE THREAD

**Issue by cholzer79** [grafana/grafana#73534]
### What happened?

When a Bar Chart is set to Orientation=horizontal, the Threshold Line orinettaion stays in vertical

**Bar Chart Orientation=horizontal (Threshold Line orientation WRONG)**
![Screenshot 2023-08-21 075852](https://github.com/grafana/grafana/assets/64579423/2645a8b6-4d90-4eb4-9619-ad0ab79a3590)

**Bar Chart Orientation=vertical (Threshold Line orientation correct)**
![Screenshot 2023-08-21 075902](https://github.com/grafana/grafana/assets/64579423/62e7570e-f036-46e7-aa6b-9567d38ed78b)

### What did you expect to happen?

Orientation of Threshold Line follows Orientation of Bar Chart

### Did this work before?

I just started using Grafana

### How do we reproduce it?

1. create Bar Chart
2. add threshold line
3. change orientation of Bar Chart

### Environment (with versions)?

Grafana: 10.0.3 OSS
OS: Ubuntu
Browser: Chrome (Windows and Android)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by garnbleiche** [comment]
Any news on this?

Grafana version 11.2.0 still contains the bug.
