### ISSUE TITLE
[feature-request] Alerting: Expand/Collapse All buttons only show with a filter applied

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#73530]
### What happened?

The "Expand all" and "Collapse all" buttons only show if you apply a filter:

![image](https://github.com/grafana/grafana/assets/5902830/212026c9-1dd6-4efb-a1f9-685f505587f9)

Without a filter, the default view does not have them:

![image](https://github.com/grafana/grafana/assets/5902830/60a6363d-1b21-434b-84b2-c8d77f22b371)

### What did you expect to happen?

The buttons would show in normal view.

### Did this work before?

No idea.

### How do we reproduce it?

1. Go to Alerting > Alert rules
2. Notice there is no collapse/expand button
3. Apply any filter (e.g. `label:a=b`)
4. Notice there is a collapse/expand button
5. Clear the filter
6. Notice there is no collapse/expand button anymore

### Environment (with versions)?

Grafana: 10.0.2
OS: Debian 12
Browser: Chrome 115

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @gtirloni,

Thanks for opening this issue.

This seems to be an expected behavior and even for me makes sense to only show this button once there are any rules as otherwise a new user who just starts using Alerting, probably gets confused as to why any rules are not visible even though the button appears.

I hope this answer is helpful

**Comment by gtirloni** [comment]
@usmangt thanks, that makes sense. Having the option to expand all rules upon first opening the alerts list would be useful too, IMHO.

**Comment by usmangt** [comment]
Since it is not a bug or an issue, therefore will mark this as a feature request and will inform the team so that they can tell more.

**Comment by armandgrillet** [comment]
This is by design, if you have a lot of alert rules and expand all it can make the UI very unresponsive.
