### ISSUE TITLE
how to feed Citrix monitoirng data to Grafana dashboad

### ISSUE THREAD

**Issue by sivameti** [grafana/grafana#7355]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
3.1
- What datasource are you using?
Citrix Xenapp Monitoring
- What OS are you running grafana on?
Linux
- What did you do?
Citrix monitoirng data to Grafana dashboad
- What was the expected result?
how to feed Citrix monitoirng data to Grafana dashboad
- What happened instead?
Just created Citrix dash board struck with data feed kindly advice how feed the data to Grafana dash board.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
This data source `Citrix Xenapp Monitoring` is not something we know of. So if we need to get data into that data source you better ask the creators of that data source
