### ISSUE TITLE
Update docs with available settings

### ISSUE THREAD

**Issue by wingZero21** [grafana/grafana#7356]
Hi,

Is it possible to update the documentation for the ldap.toml files to ensure that all the available options are hashed out what can be used.

We had some trouble getting the ldap group's working and we believe that after adding this setting it looks to have sorted it as I believe it is set to false as default.

Details:
```
search_in_groups = true
```

Found from https://github.com/grafana/grafana/pull/2746/commits/9f3d799e0204b521434d4aa5b5b0ed44c18c420a

Cheers
Mark

**Comment by torkelo** [comment]
that PR was never merged so that option does not exist.
