### ISSUE TITLE
Metrics: grafana_alerting_alerts doesn't match UI values

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#73581]
### What happened?

Querying Grafana's `/metrics` endpoint returns this data:

```
# HELP grafana_alerting_alerts How many alerts by state.
# TYPE grafana_alerting_alerts gauge
grafana_alerting_alerts{state="alerting"} 8
grafana_alerting_alerts{state="error"} 0
grafana_alerting_alerts{state="nodata"} 0
grafana_alerting_alerts{state="normal"} 1392
grafana_alerting_alerts{state="pending"} 0
```

But the UI shows very different information:

![image](https://github.com/grafana/grafana/assets/5902830/4f02bdbb-c609-4e95-8c7b-06916f078861)

### What did you expect to happen?

The numbers in the metrics would match what's shown in the UI.

### Did this work before?

N/A (recently upgraded from Grafana 8 to 10)

### How do we reproduce it?

1. curl http://grafana:3000/metrics | grep grafana_alerting_alerts
2. Visit http://grafana/alerting/list?view=list
3. Compare numbers

### Environment (with versions)?

Grafana: 10.0.2 (3 replicas in Kubernetes, configured gossip protocol)
OS: Debian 12
Browser: Chrome 116

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by gtirloni** [comment]
This might be a UI issue afterall.

```
grafana_alerting_rule_group_rules{org="1",state="active"} 146
grafana_alerting_rule_group_rules{org="1",state="paused"} 2
```

The UI doesn't show anything `paused`, only that there are `148 rules` but it seems these are actual `rule groups`, which the metrics are exposing.

Should the UI be modified to make it clear that rules and rule groups are different things?

**Comment by gtirloni** [comment]
The rules can have multiple instances, which the metrics are calling `grafana_alerting_alerts`.

After expanding all rules in the UI, I can see the instances and they match the count in `grafana_alerting_alerts`.

But if I don't expand them, I think there are only 6 alerts firing when in fact I got 9 issues.

**Comment by usmangt** [comment]
Hi @gtirloni,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by gtirloni** [comment]
@usmangt thank you. I'm still getting used to alerting in Grafana 10 so it might all just be a misunderstanding on my part but some things are getting me by surprise. IMHO, there are certain UI objects that still represent things from the legacy alerting days.

**Comment by armandgrillet** [comment]
The metrics are about alert instances whereas the UI is about alert rules. An alert rule can contain many alert instances, which is why the metrics reported are higher numbers than the numbers in UI (which again, do not represent the same thing).

The UI is indeed complex to grasp, we are working on improvements to the alert list view for Grafana 10.2.
