### ISSUE TITLE
WebSocket API: Datasource not working

### ISSUE THREAD

**Issue by guenter-ms** [grafana/grafana#73582]
### What happened?

![Bildschirmfoto 2023-08-21 um 18 04 41](https://github.com/grafana/grafana/assets/6253315/14763679-8e6e-4a26-b7b7-1e87f4f665d0)

### What did you expect to happen?

I like to feed grafana dashboard with live data from my nodered server, running on same machine.

### Did this work before?

Is new installation.

### How do we reproduce it?

1. Create a Datasource "WebSocket API"
2. Create a simple Webservice using nodered
3. Create a dashboard panel using the Datasource

Datasource:

![Bildschirmfoto 2023-08-21 um 17 58 52](https://github.com/grafana/grafana/assets/6253315/850ca914-cfad-4910-89ef-badf966fe7c3)

Create a simple Webservice in node-red:

![Bildschirmfoto 2023-08-21 um 17 57 32](https://github.com/grafana/grafana/assets/6253315/b3393c12-2509-4a39-8ee7-be25417cc613)

Test the Webservice using a browser:

![Bildschirmfoto 2023-08-21 um 17 58 23](https://github.com/grafana/grafana/assets/6253315/0d3310c4-2c0d-4ae4-9e2f-8c6e52991963)

Create a dashboard panel using the Datasource

![Bildschirmfoto 2023-08-21 um 20 08 31](https://github.com/grafana/grafana/assets/6253315/e4897bc5-8872-4981-b22d-887ae9fa3465)

NO difference if I use wws:// or http:// 

Logdata:

![Bildschirmfoto 2023-08-21 um 20 02 51](https://github.com/grafana/grafana/assets/6253315/8d2c0a14-6ebc-4a3c-9e5c-8e96ee6fd17e)

### Is the bug inside a dashboard panel?

yes, see above

### Environment (with versions)?

Browser: Chrome

![Bildschirmfoto 2023-08-21 um 18 34 41](https://github.com/grafana/grafana/assets/6253315/bf7bd25d-d257-4d49-93e2-ea4e68d3bd3a)

### Grafana platform?

Other

### Datasource(s)?

WebSocket API

**Comment by usmangt** [comment]
Hi @guenter-ms,

Thanks for opening this issue.

I checked about this plugin and it seems to be a community plugin as described on the plugin page (that means, it is not maintained by us).

Therefore, the suggestion would be to report this by opening a new issue to their official GitHub page so that they can check it.

Luckily, there is a forum post that reports the same problem but a couple of community members provided some alternative solutions. Please check:

https://community.grafana.com/t/how-used-grafana-websocket-plugin-get-data-from-binance-websocket-api/100452

**Comment by guenter-ms** [comment]
Hi @usmangt ,

Thank you for fast reply.

I followed your link and had no success. Its very complicated.

May I ask for an easy way out-of-the-box-no-third-party-plugins how to feed a panel with live data?

The easiest way for me is to use MQTT. But that plugin didn't work, see https://github.com/grafana/mqtt-datasource/issues/66#issuecomment-1685928212
A member replied in that issue: I contacted Grafana support about this issue, who have confirmed that the MQTT data source has been deprecated and will not be developed any further. Is that true?

The 2nd best way was WebSocket API, but this didn't work, see this issue.

Can you offer an easy way?

Best
Guenter

**Comment by usmangt** [comment]
REOPENING this issue as already in talk with the team and will provide an update by next week

**Comment by guenter-ms** [comment]
Hi, any news?
