### ISSUE TITLE
[Bug]? Grafana-server fails to start on boot because postgresql isn't ready yet 

### ISSUE THREAD

**Issue by n1els** [grafana/grafana#7359]
Please include this information:
- What Grafana version are you using? Latest 4.1.1 stable 
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu server 16.04
- What did you do? Installed latest grafana with postgresql as db
- What was the expected result? Services start automatically on boot 
- What happened instead?
Actually it worked fine on a clean install, then after adding some dashboards and users to grafana I noticed it had failed to start on boot. 

Grafana-server encounters a fatal error because postgresql doesn't reply fast enough. Manually starting the grafana service (sudo service Grafana-server start) resolves the issue. 

While searching I found that this behavior is referenced in issue 2915, but this would be for a much lower version. 

I still tried to find the mentioned Grafana-server.service file but I can't find it.

**Comment by torkelo** [comment]
Yes, the sql database needs to be available at startup. Not sure if this qualify as a bug.

**Comment by n1els** [comment]
So the wait for postgresql option as mentioned in issue 2915 is no longer
valid? Is this something I can add if this is not / no longer implemented?

**Comment by torkelo** [comment]
it has never been implemented. You can make a copy of the systemd service file grafana ships with (or modify the one it installs but that could be problematic on upgrade), add add the dependency there.
