### ISSUE TITLE
HTTP-API: Admin api token faces access permissions issue when trying to get a user by name/email

### ISSUE THREAD

**Issue by shehrozeee** [grafana/grafana#73602]
### What happened?

I am trying to use this api end point using a service account and also via api key
Get single user by Username(login) or Email
GET /api/users/lookup?loginOrEmail=use@mygraf.com

however I am getting an error in response that says '{"accessErrorId":"ACE5424049007","message":"You\'ll need additional permissions to perform this action. Permissions needed: users:read","title":"Access denied"}\n'

my api has the admin role

### What did you expect to happen?

I expected to get the actual user detail for the user I was trying to lookup 

### Did this work before?

dont know, this is the first time I needed to do this 

### How do we reproduce it?

1.create an api account
2.send an http request 
GET /api/users/lookup?loginOrEmail=user@mygraf.com HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
replace the user@mygraf.com with a username that is in the system
3.see the error

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: v9.1.2 (3c13120cde)
OS: ubuntu
Browser: n/a

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @shehrozeee,

Thanks for opening this issue.

I cannot found this API listed in the HTTP API Admin documentation (https://grafana.com/docs/grafana/latest/developers/http_api/admin/)

From where you find this is API which is for the Admin?

**Comment by shehrozeee** [comment]
https://grafana.com/docs/grafana/latest/developers/http_api/user/#get-single-user-by-usernamelogin-or-emailthis is the api I am trying to use. Sent from Mail for Windows From: Usman AhmadSent: Tuesday, August 22, 2023 4:04 PMTo: grafana/grafanaCc: shehrozeee; MentionSubject: Re: [grafana/grafana] HTTP-API: Admin api token faces access permissions issue when trying to get a user by name/email (Issue #73602) Hi @shehrozeee,Thanks for opening this issue.I cannot found this API listed in the HTTP API Admin documentation (https://grafana.com/docs/grafana/latest/developers/http_api/admin/)From where you find this is API which is for the Admin?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by shehrozeee** [comment]
[The link](https://grafana.com/docs/grafana/latest/developers/http_api/user/#get-single-user-by-usernamelogin-or-email)

this is the api I am trying to use.

**Comment by hmehta** [comment]
We are facing this issue as well when trying to use Bearer authentication (service account token) with API calls or using Terraform.

If we use Basic authentication instead (which we would love to avoid for obvious reasons), everything works as expected and we do not get the permission error.
