### ISSUE TITLE
[Feature request] per dashboard reusable query results 

### ISSUE THREAD

**Issue by lucadistefano** [grafana/grafana#7360]
In some dashboards we show same data in different panels. This data is used to create 'filled areas' in graphs.
It could be useful (for performance and for simplify the graph creation) add a template that performs a query on timerange changes and stores the result in a reusable variable.

The same variable can be used in different panels as datasource instead of the query, avoiding to perform the same query for each panel.

**Comment by torkelo** [comment]
interesting idea!

**Comment by cattt84** [comment]
+1

**Comment by sunnos9** [comment]
+1

**Comment by sandopolus** [comment]
Was just googling for this functionality as Librato had a similar feature of linked queries which could be used over multiple dashboards.
Either global or per dashboard queries would be good to have.
+1

**Comment by CarusDave** [comment]
Most our dashboards have areas that are using the same queries for different panels, definitely a very useful feature!

**Comment by jonesn** [comment]
+1

**Comment by chrisjschultz** [comment]
+1

**Comment by sunnos9** [comment]
+1

**Comment by mohanraj1939** [comment]
+1

**Comment by temamagic** [comment]
Something new?

**Comment by opwvhk** [comment]
Another reason to want this, is that I frequently (in some dashboards always) see wildly different results from the same (set of) queries.

For example one panel (a pie chart) lists 45 slices with value 1, and a second panel sums these (by issuing an identical query #A and using sumSeries on that) to 3...

**Comment by torkelo** [comment]
Read up on maxDataPoints and consolidateBy to fix that

**Comment by a6sondhi** [comment]
+1

**Comment by suikast42** [comment]
+1

**Comment by bijwaard** [comment]
Having dashboard-queries would indeed improve the performance and alignment of query results in different panels.

**Comment by buchupally** [comment]
This feature would help performance quite a bit for us. We have multiple panels querying the same table but retrieving different columns. Would be nice to make one query for all the columns and reuse it.

**Comment by AFMiziara** [comment]
+1

**Comment by xXCalleManXx** [comment]
+1

**Comment by suikast42** [comment]
+1

**Comment by sakjur** [comment]
This was implemented in Grafana v6.4 using the **-- Dashboard --** datasource https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#share-query-results-between-panels
