### ISSUE TITLE
Transformations: "Partition by values" drop-down options view identical for all partitions

### ISSUE THREAD

**Issue by adirmatzkin** [grafana/grafana#73608]
### What happened?

When we try to use the "Partition by value" transformation on a tabular data, the generated partitions names (in the drop-down menu) are not the partitions actual names.

### What did you expect to happen?

Partitions names will be the name of the partition.

### Did this work before?

Yes,
I encountered this issue after upgrading Grafana from 9.3.2 to 10.0.3.

### How do we reproduce it?

1. Create a dashboard panel of some tabular data (in our simple reproduction example we used CSV File from TestData datasource).
2. Add a "Partition by value" transformation and select some field to partition by (in our example "State" was selected).
3. Have a look at the partitions drop-down menu 🥲

### Environment (with versions)?

Grafana: 10.0.3
OS: Ubuntu
Browser: Chrome 114

### Grafana platform?

Docker

### Datasource(s)?

TestData

**Comment by usmangt** [comment]
Hi @adirmatzkin,

Thanks for opening this issue.

We will take a look into this issue and will get back to you soon

**Comment by usmangt** [comment]
Sorry for a bit of delay on this, Just tested it out, and yes seems like it's not the same and sounds like a bug.

Here is the screenshot for Grafana version 9.3.2

![grafana-9 3 2](https://github.com/grafana/grafana/assets/69509548/49d06ff0-f2ce-43ad-9ceb-a4a8c7b9244e)


And here is the screenshot for Grafana version 10.1.1

![grafana-10 1 1](https://github.com/grafana/grafana/assets/69509548/9397a630-fc78-46d7-8358-6d52eb3d3094)


Both are using TestDB and CSV File and the filename is `flight_info_by_state.csv`
