### ISSUE TITLE
Task: Add tracking dashboard toolbar options

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#73610]
**Goal**

Need to track users' actions on the toolbar to measure usage and take some steps to improve the "share" button in the toolbar.

**Task list**

- [x] Favorites 

- [x]  Insights

- [x] Settings 

- [x] Refresh

- [x] Time_picker

- [x] Zoom_out_time_range

**Definition for these tracking events**

```
reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'favorites'
)

reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'insights'
)

reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'settings'
)

reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'refresh'
)

reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'time_picker'

reportInteraction(
Event: 'dashboards_toolbar_actions_clicked',
item: 'zoom_out_time_range'
```

**Comment by juanicabanas** [comment]
After a talk with @grafana/dashboards-squad, we will take this task 😃
