### ISSUE TITLE
[Bug] Month interval does not work

### ISSUE THREAD

**Issue by tsn77130** [grafana/grafana#7361]
- What Grafana version are you using? 
4.0.1

- What datasource are you using? 
Influxdb

- What OS are you running grafana on? 
docker debian container

- What did you do? 
I've set a time interval of 1M (should be posible according to time units definitions of documentation), for having month to month sums on a year.

- What was the expected result? 
On a "Previous year" quick range period, when I pick up 1M interval, it should display sum of values month to month (12 values in a year)

- What happened instead? 
I only got 1 value, at the beginning of the year, with the sum of all values of the year.

I tried to get around by setting 30d interval, but as month are not always 30d, it gaves me incorrect results.

Thanks 
Thomas

**Comment by torkelo** [comment]
Cant find Month interval listed in InfluxDB docs, they seem to only support week as the biggest interval. 

https://docs.influxdata.com/influxdb/v1.2/query_language/spec/#durations

**Comment by tsn77130** [comment]
hum, you're right , I mixed informations with grafana docs apparently 
http://docs.grafana.org/reference/timerange/

Thanks for your answer
