### ISSUE TITLE
Annotations: Issues switching datasources if there is overlap in query properties

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#73639]
When switching between datasources that may share query properties the query editor may fail to load correctly. For example, the Timestream and Azure Data Explorer datasources both share the property `database`. When switching from a configured ADX annotation to a Timestream annotation the ADX database property is still present.

The annotations query editor should reset all properties when switching from a datasource to one where `oldDatasource.uid !== newDatasource.uid` to avoid clashes.

**Comment by axelavargas** [comment]
Fixed by [Annotations settings: Do not preserve query properties when changing data source #77422
](https://github.com/grafana/grafana/pull/77422 )
