### ISSUE TITLE
Tutorial: Play with Grafana Mimir goes to localhost

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#73644]
### What happened?

When clicking on Queries here

https://grafana.com/tutorials/play-with-grafana-mimir/?pg=oss-mimir&plcmt=hero-btn-1

it takes me to localhost ?
http://localhost:9000/d/b3abe8d5c040395cc36615cb4334c92d/mimir-queries

Thanks

### What did you expect to happen?

for it not to go to localhost unless that is where it is supposed to go

### Did this work before?

No idea

### How do we reproduce it?

1. to go https://grafana.com/tutorials/play-with-grafana-mimir/?pg=oss-mimir&plcmt=hero-btn-1
2. Click Queries

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by moxious** [comment]
I attempted to replicate this but cannot.   The missing piece I believe is that you have to git clone mimir first, change to a directory, and then `docker-compose up -d`.  When I did those steps, the Query link functioned as advertised.

<img width="1300" alt="image" src="https://github.com/grafana/grafana/assets/5471710/bf395e8b-3ee3-4dbf-903d-59af976b6da0">

@yosiasz can you confirm whether you were running the docker stack at the time?  If you weren't, this would be expected.  If you were, then might need to debug what went wrong with the stack and file an issue on the mimir repository where the example is hosted.

By the way, the other links in that doc section also go to localhost, so if one of them fails, they likely all fail (if not running the stack locally)
