### ISSUE TITLE
[Feature request] Include dashboard screenshot(s) with alert emails

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#7364]
The image is super helpful in the alert message - however, it would be great to quickly see other information directly in the email.

Perhaps a new "Screenshots" section in the alert configuration that lets you configure a list of dashboards (and/or panels?) with a time offset. perhaps something like:

==============================
‣Dashboard 
‣ Panel 
‣ From 
‣ ?
------------------------------
this 
 this 
 -10m 
 [yes/no] 
------------------------------
dashboard1 
 all 
 -5m 
 [x]
------------------------------
dashboard2 
 panel title (14) 
 -1h 
 [x]
------------------------------
dashboard2 
 panel title (14) 
 -5m 
 [x]
------------------------------
[dropdown] 
 [dropdown] 
 [-5m] 
 [+]
==============================

All of these images would be included in the notification.

- - -
If this feature sounds interesting, I can take a stab at the UI/config, but would need some help with the Go backend

**Comment by bergquist** [comment]
This is something we been wanting to do for quite some time. Would be awesome if you want to help out.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
