### ISSUE TITLE
Dashboards Panel Title: Have more descriptive tooltip for alerting icon

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73653]
**Why is this needed**:

The 'alerting is alerting' tooltip on the dashboard panel title looks strange.

**What would you like to be added**:

Maybe having it include the alerting rule name would be better, or maybe just report the status and remove the "alerting is" portion.

**Who is this feature for?**

People who have alerting links in dashboards. 

Developer notes: 
The line of code is here https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderTitleItems.tsx#L25

**Comment by nayeem01** [comment]
@gelicia Hello, I would like to work on this.

**Comment by otilor** [comment]
I wanted to jump on this but I see it has been closed via #73659. Why is it still open? Is there any other thing that need to be added? I'd like to add if there is.
