### ISSUE TITLE
[BUG]  Can't drill down  with multi value variable

### ISSUE THREAD

**Issue by daianmartinho** [grafana/grafana#7367]
Please include this information:
- What Grafana version are you using? 4.1
- What datasource are you using? sqlite
- What OS are you running grafana on? debian 8.5
- What did you do? drilldown passing url param var-hosts=$multiHosts
- What was the expected result? var-hosts=host1&var-hosts=host2
![capturar2](https://cloud.githubusercontent.com/assets/8451484/22315035/6aac3286-e34b-11e6-932e-fdfadcdff27e.PNG)

- What happened instead? var-hosts=host1,host2
![capturar](https://cloud.githubusercontent.com/assets/8451484/22315034/6aabe52e-e34b-11e6-8272-c7bef3949c8e.PNG)

**Comment by torkelo** [comment]
templating is string interpolation, so `var-hosts=$multiHosts` cannot   be turned into `? var-hosts=host1&var-hosts=host2`  

There already is a specific option to include all current template variable values in drilldown links

**Comment by daianmartinho** [comment]
i have some singlestat panels, each one with its own variable of multiple "hosts".
all panels drilldown to the same dashboard2, that will receive values at $hosts variable and replicate row on it.

i can't see a way to do that if all values are included, Is that possible?

can't split that array appending with last parameter?

![capturar3](https://cloud.githubusercontent.com/assets/8451484/22327983/126eb1ba-e3a1-11e6-8e6e-4f1e423cb91b.PNG)
