### ISSUE TITLE
Dashboards: for panels without a title, the tooltip with move and more icon is displayed below preceding panel.

### ISSUE THREAD

**Issue by lukasztyrala** [grafana/grafana#73670]
### What happened?

https://github.com/grafana/grafana/assets/141744/dc0891ca-8cd8-4c77-8075-6ef24c5a6886

### What did you expect to happen?

The tooltip with a move icon and three dots for the menu to be shown above the preceding panel.

### Did this work before?

Yes, before `f091e8f` it worked.

### How do we reproduce it?

1. Edit panel
2. Remove a title of a panel
3. See how the move + more tooltip hides below the preceding panel.

### Is the bug inside a dashboard panel?

"Copy to clipboard failed Snapshot is too large, consider download and attaching a file instead" :-)

### Environment (with versions)?

Grafana: Grafana Cloud v10.2.0-59765 (de118a37)
OS: macOS 13.5.1 (22G90)
Browser: Chrome Version 116.0.5845.110 (Official Build) (arm64)

### Grafana platform?

I use Grafana Cloud

**Comment by polibb** [comment]
This is now fixed by reverting a previous change: https://github.com/grafana/grafana/pull/73677

We need to add this change (descending z-index of panels in a dashboard) without causing this bug ^.
