### ISSUE TITLE
Transformations: "All values" calculation returns the last entry for all rows of the table

### ISSUE THREAD

**Issue by DK6v** [grafana/grafana#73676]
### What happened?

After upgrade 9.3.6 => 10.0.3

"All values" calculation within "Add field from calculation" transformation in reduce row mode returns the last entry for all rows of the table (the column value is the same for all rows).

Workaround is to use "All unique values" calculation.

![Capture](https://github.com/grafana/grafana/assets/56519965/44be97f3-8e84-4ab7-8464-a6d7a8f8d74c)

### What did you expect to happen?

The field value must be calculated for each row separately.

### Did this work before?

Yes, 9.3.6

### How do we reproduce it?

1. Create "Add field from calculation" transformation, use "Reduce row" mode
2. Select "All values" calculation for one or seral fields
3. Check calculated values

### Is the bug inside a dashboard panel?

Table panel (other?)

### Environment (with versions)?

Grafana: 10.0.3, 10.2.0
OS: Linux
Browser: Firefox 113.0.2

### Grafana platform?

Docker

### Datasource(s)?

Any? (Elasticsearch, Graphite, ...)

**Comment by DK6v** [comment]
Hi @usmangt,

Thank you for your quick response.

The "myColumn" contains an array of "battery" and "temp" fields, the calculation is performed by rows and this is the expected behavior.

![image](https://github.com/grafana/grafana/assets/56519965/5afeae9d-4d8a-4e21-9509-e25dbac3a9ce)

**Comment by Totalus** [comment]
Seems like this condition is the source of the issue.

https://github.com/grafana/grafana/blob/a0e8cf8b66d6023767b0b867de8c1551a34139b2/packages/grafana-data/src/transformations/matchers/nameMatcher.ts#L121

Possibly in the scope of #72045
