### ISSUE TITLE
Remove toolkit from grabpl and plugin drone extension

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#73681]
Grabpl areas that are using toolkit:

Before doing anything in those areas - make sure we know how, **IF**, and where they are used:

**Grabpl**
- https://github.com/grafana/build-pipeline/blob/9ed16d630e40b625273e01937207f5a39dd7a179/test/plugin-package.sh#L50-L54
- https://github.com/grafana/build-pipeline/blob/9ed16d630e40b625273e01937207f5a39dd7a179/pkg/subcmd/plugin/e2etests.go#L176-L179

**Drone Extension**
- https://github.com/grafana/grafana-drone-extension/blob/main/pluginjson/pipeline-ci.go#L77
- https://github.com/grafana/grafana-drone-extension/blob/9b67b28162e8c2be9bd5d9dbcefb341c21d984e4/testdata/pluginjson/plugin-w-backend.drone.yml#L50
- https://github.com/grafana/grafana-drone-extension/blob/9b67b28162e8c2be9bd5d9dbcefb341c21d984e4/testdata/pluginjson/plugin-w-backend-fork.drone.yml#L50
- https://github.com/grafana/grafana-drone-extension/blob/9b67b28162e8c2be9bd5d9dbcefb341c21d984e4/testdata/pluginjson/plugin-w-backend-fork.drone.yml#L50
- https://github.com/grafana/grafana-drone-extension/blob/9b67b28162e8c2be9bd5d9dbcefb341c21d984e4/testdata/pluginjson/plugin-app.drone.yml#L50

**Comment by tolzhabayev** [comment]
@Ukochka and @jackw please take a look at those and consult @yesoreyeram if necessary.

**Comment by jackw** [comment]
Maybe I'm missing something (I've been through this list twice now) but I'm not sure we should touch any of these with regard to removing toolkit from the Grafana repo. The toolkit packages will remain on NPM but any changes to remove it from CI will likely result in plugins using toolkit to fail to build if the CI is updated. 🤔

**Comment by tolzhabayev** [comment]
Yep, deprecating on npm not removing it completely.

Thanks for checking the list and we can get back to this once everyone internally has moved to `create-plugin` tooling
