### ISSUE TITLE
Tags are not saved on initial dashboard

### ISSUE THREAD

**Issue by tliefheid** [grafana/grafana#73696]
### What happened?

Upon saving a newly created dashboard with tags, those tags are not saved

### What did you expect to happen?

i expected the tags to be saved

### Did this work before?

not sure

### How do we reproduce it?

1. start to create a new dashboard
2. go to gear icon and add tags
![image](https://github.com/grafana/grafana/assets/26207844/99be509a-10ea-4bb3-aa5a-d988c8d5dda8)

4. then hit save dashboard, the dashboard is saved but without the newly added tags
![image](https://github.com/grafana/grafana/assets/26207844/3048113c-9199-411d-9449-a7dc903cb199)

5. tags are not saved for this dashboard
![image](https://github.com/grafana/grafana/assets/26207844/0b9586bb-6450-44aa-90b6-8702042c1c04)

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: v10.0.3 (eb8dd72637)
OS: macOs ventura 13.5
Browser:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @tliefheid,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine.

I am using Grafana v10.1.0 (ff85ec33c5) and after clicking save Dashboards, then tags were still there.

Can you please retest this on the current latest version?

**Comment by tliefheid** [comment]
can confirm indeed that in Grafana v10.1.0 (ff85ec33c5) this seems to work as expected. 

apologies for not testing in lastest version
