### ISSUE TITLE
ignore not fully computed points [graphs]

### ISSUE THREAD

**Issue by mradamczyk** [grafana/grafana#737]
If we group by some time (let's say $time) and aggregate entries with sum (or count) , the last point of the graph is not correct (because there are not enough entries yet). We should just ignore it, until all entries from  last $time are in database.

For example,
![x](https://cloud.githubusercontent.com/assets/2982247/4097583/d6a7466a-2fd9-11e4-99d9-edd0d2ca3886.png)
here is a sum of some entries grouped by 1m. The value for last point is much smaller, because we don't  have all data from the last minute yet.

I could imagine that this value is although usually ok for other aggregating functions (like mean).

**Comment by txaj** [comment]
That's the same issue as the one reported on #374 bug suggesting a different solution

**Comment by jpbarron** [comment]
This might be a good way to potentially resolve the issue I reported in #374

**Comment by txaj** [comment]
@jpbarron I find the solution of #374 more elegant. If we ignore the n lasts time periods because one series is missing the lasts points, we may ignore them for too long if for example one host is not reporting data (during maintenance or so)

**Comment by torkelo** [comment]
you can now specify a now delay in time picker options which solves this case

**Comment by sebastienluquet** [comment]
@torkelo 
> I think an option in the display styles "Ignore last point" would be an ok solution for this.

I think that it would have been a better solution:
- It can be configured per metric
- It works even when to: param in global timeframe is in the future
