### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gkissand** [grafana/grafana#7370]
Grafana 4.1.1
Datasource opentsdb

When i copy a graph that has an alert, the new graph has problem

On the new graph you can see the redline where the alert was set but the alert configuration is empty
In some cases that i haven't find out the conditions, you can't configure a new alert and you get the message

t=2017-01-26T14:16:18+0100 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Failed to extract alert.Reason: Alert on PanelId: 14 refers to query(A) that cannot be found "
![capture](https://cloud.githubusercontent.com/assets/25226373/22332984/042cab9c-e3d4-11e6-9839-fb4dba970761.JPG)

**Comment by torkelo** [comment]
yes, the alert definition is removed when you duplicate a graph. But the thresholds that the alert rule conditions added to the graph are kept. You can remove these in the graph display tab. 

The error you got looks like you have an alert rule that referes to a Query `A` but the panel has no query with that letter.

**Comment by gkissand** [comment]
ok
I copied graph added a C metric and deleted the other two

query A in metrics not in alerts

clear

Not a bug after all :)

thank you

**Comment by krainboltgreene** [comment]
This can also happen if:

  1. You've recently upgraded to the alerts version but haven't refreshed your page before trying to create an alert
  2. Your alert has template variables
