### ISSUE TITLE
How to be compatible with the old version of chrome browser?

### ISSUE THREAD

**Issue by yylbfyl** [grafana/grafana#73728]
**Why is this component needed**:
The embedded browser version of some of our industrial equipment is the old chrome 60 and them can't upgrade chrome version, so we can't access the new grafana v9.3.6. However, due to the needs of production business, we hope that the later versions of grafana v9 will add the functions compatible with the browser access of the old version. There is the error information.

If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help

5. Check if you are using a non-supported browser. For more information, refer to the list of [supported browsers](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers).
___
 - [ yes] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
Our  industrial equipment.

[![pPYRqyR.md.jpg](https://s1.ax1x.com/2023/08/24/pPYRqyR.md.jpg)](https://imgse.com/i/pPYRqyR)

**Comment by leeoniya** [comment]
Chrome 60 is [6 years old](https://developer.chrome.com/blog/new-in-chrome-60/) -- an eternity in internet years. there's no practical way to support browsers this old. the chance of this happening is effectively zero.
