### ISSUE TITLE
Dashboards: Share panel text has &nbsp;

### ISSUE THREAD

**Issue by aditipatelpro** [grafana/grafana#73729]
### What happened?

When clicking on Share panel option, a warning box is shown. In the warning text, &nbsp character is shown instead of space.
<img width="735" alt="image" src="https://github.com/grafana/grafana/assets/20130692/96c0ad35-5966-41bd-b10f-82ea714ea4f8">

### What did you expect to happen?

The text should have non-breaking space.

### Did this work before?

No

### How do we reproduce it?

1. Create a Dashboard with any test data
2. Create a panel with test data
3. Click on three dots and open the share panel

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana:
OS: Mac
Browser: Chrome

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @aditipatelpro,

Thanks for opening this issue.

What is the Grafana version you are using?
