### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by gkissand** [grafana/grafana#7373]
Grafana 4.1.1
datasource opentsdb

usecase
I want on the same graph httpd rates for 40x 50x and 20x
I want to configure alert for http error codes 40x 50x and 20x

if 40x or 50x is above 10 then trigger alert
if 20x is below 90 then trigger alert
As it is now i can't 

In detail
I would like to have in Alerts -> Alert Config -> Condition for each rule to configure the metric i am interested in eg
WHEN avg() OF 30m IS ABOVE 10 FOR METRIC httperrrate40x (or all)
OR
WHEN avg() OF 30m IS ABOVE 10 FOR METRIC httperrrate50x (or all)
OR 
WHEN avg() OF 30m IS BELOW 90 FOR METRIC httperrrate50x (or all)

thank you

**Comment by torkelo** [comment]
you can do that if each metric is in'ts own query
