### ISSUE TITLE
[Feature request] Annotations per graph, not per dashboard

### ISSUE THREAD

**Issue by essigke** [grafana/grafana#7375]
Dear developers,

please consider my feature request!

Please include this information:
- What Grafana version are you using? Grafana 4.1.1
- What datasource are you using?  Prometheus 1.4.1
- What OS are you running grafana on? Scientific Linux 7.2 (~RHEL 7.2)
- What did you do?
I have a template dashboard with "multi-value" for "instance", i.e. I can show data for one or more hosts. I added annotations with "ALERTS{instance=~"$node",alertstate="firing"}" as search expression to show prometheus alerts.
- What was the result?
Annotations are shown if ANY of the selected instances is in alert state.
- What should happen instead?
Annotations should only be shown in a graph, if the instance plotted in the graph is in alert state (or part of an aggregation). 

The root of the problem is IMHO, that annotations are a feature of the dashboard, not of the graph.

![grafana_single_host](https://cloud.githubusercontent.com/assets/22471386/22340408/b17ffc04-e3ed-11e6-8694-08498d671942.png)
Load of a single host is displayed. Alerts are shown (for testing: load1 >12) with a 1m delay before prometheus starts firing. This can be useful information.

![grafana_multiselect](https://cloud.githubusercontent.com/assets/22471386/22340407/b17831e0-e3ed-11e6-9b1e-600200b5d3e6.png)
Load of two hosts is displayed. Alerts are shown in both graphs in the same regions (matching the regex in the annotation specification), but the information seems useless.

I want to monitor large clusters and need the annotation to identify quickly the host with problems. In my test case all graphs turn red if I display a few nodes.

Thank you very much!

Timm

**Comment by torkelo** [comment]
good suggestion, already requested (https://github.com/grafana/grafana/issues/717) so will close this
