### ISSUE TITLE
oauth: skip_org_role_sync behavior for existing users: user's organization is reset since 10.1

### ISSUE THREAD

**Issue by tobhv** [grafana/grafana#73752]
### What happened?

when an existing oauth user logs in that is a member of multiple different organizations that were assigned to the user in the grafana UI the organization of the user reset to 1.

I see this behavior since version 10.1.0

### What did you expect to happen?

as the documentation states:
"With skip_org_role_sync set to true, when a user logs in for the first time, Grafana sets the organization role based on the value specified in auto_assign_org_role and forces the organization to auto_assign_org_id when specified, otherwise it falls back to OrgID 1"
and:
"
Use this setting when you want to manage the organization roles of your users from within Grafana and be able to manually assign them to multiple organizations, or to prevent synchronization conflicts when they can be synchronized from another provider."
source: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#skip_org_role_sync 

As such, before 10.1 this behavior worked exactly as is written out above:

- keycloak / oauth User logs on for first time: it gets organization 1.
- in the grafana UI the user is made a member of other organizations.
- next time the user logs in membership of organizations i retained.

### Did this work before?

9.x, any version before 10.1

### How do we reproduce it?

1. install grafana 10.0.1
2. setup oauth
3. set skip_org_role_sync=true within the oauth config in grafana (see also my example)
4. create organization orgB
5. create keycloak user, login to keycloak with that user.
6. as grafana admin make the user member of orgB
7. let keycloak user logoff, logon. validate user is member of orgB
8. upgrade grafana to 10.1
9. login as keycloak user > user is not member of orgB anymore.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1
OS: docker container
Browser: firefox or chrome latest.

oauth config:
``` #################################### Generic OAuth ##########################
[auth.generic_oauth]
enabled = true
name = Keycloak-OAuth
allow_sign_up = true
client_id = grafana
client_secret = **** REMOVED ******
scopes = openid email profile offline_access roles
;empty_scopes = false
skip_org_role_sync = true
;email_attribute_name = email:primary
;email_attribute_path =
;login_attribute_path =
;name_attribute_path =
;id_token_attribute_name =
email_attribute_path = email
login_attribute_path = username
name_attribute_path = full_name
auth_url = https://mykeycloak.host.name/realms/apps1/protocol/openid-connect/auth
token_url = https://mykeycloak.host.name/realms/apps1/protocol/openid-connect/token
api_url = https://mykeycloak.host.name/realms/apps1/protocol/openid-connect/userinfo
```

### Grafana platform?

Docker

**Comment by usommerl** [comment]
We have run into this as well and needed to downgrade to 10.0.x. We also use the generic OAuth functionality and have many organisations and users. We needed to restore the user/organisation relationship manually for a couple of users after the downgrade. Over time, this issue would slowly destroy our user's affiliation with its organisations.

**Comment by eleijonmarck** [comment]
Thank you for reference this issue.

**Comment by eleijonmarck** [comment]
@tobhv @usommerl the fix is inplace, and the functionality that was introduced in [PR](https://github.com/grafana/grafana/pull/72752) will be available in the next patch release `v10.1.1`, which is scheduled for September 26 (preliminary) as a public release.

**Comment by usommerl** [comment]
@eleijonmarck Awesome! Thanks for the info.

**Comment by tobhv** [comment]
hi. yes thanks a lot for confirming the issue and cause. looking forward to september. thanks again.

**Comment by usommerl** [comment]
TIL: `v10.1.1` is already out, and I can confirm that the fix is working. Thanks again!  :tada:

**Comment by sathieu** [comment]
This issue should be closed I think.

**Comment by tobhv** [comment]
yes. i agree.
