### ISSUE TITLE
Exporting issues for /dashboard-solo/db/query-period

### ISSUE THREAD

**Issue by makareth** [grafana/grafana#7376]
Grafana 4.0.2
Ubuntu 16.04
InfluxDb 0.9

I'm unable to export my dashboards properly. My objective is to use the [dashboards.json]  so that I can script the provisionning of dashboards when I setup a new machine.
The grafana.ini configuration part looks ok, since Grafana shows the dashboards in the list.
However, it keeps saying that datasource ${DS_TSDB} was not found.

I tried two different procedures for exporting my dashboards.

Procedure 1:
I tried the "View JSON" option and then pasted the content into a dashboard.json file I created in var/lib/grafana/dashboards.
The graphana site on port 3000 sees the new dashboard and actually displays it correctly with real data.
The issue is that when accessing the dashboard through dashboard-solo, the graph says that the dashboard was not found.

Procedure 2:
I used the export feature to generate a dashboard.json file I copied into /var/lib/grafana/dashboards.
The graphana asite on port 3000 tells me that the datasource ${DS_TSDB} was not found.

I tried using templating to create a variable DS_TSDB, constant type and whose value is tsdb (the actual name of my datasource), but this doesn't work neither, the datasource is still not found.

Is it a bug, a misconfiguration ?

**Comment by torkelo** [comment]
If you export through procedure 2 then you have to use the import api. The export process makes a dashboard more portable to other instances and is not usable with the json files feature directly. 

After doing procedure 1, click on a graph and then the "Rendered image link" does that also give you not found error?

**Comment by torkelo** [comment]
`dashboard-solo/db/query-period` that url looks wrong if you have a json file dashboard should be `dashboard-solo/file/query-period`
