### ISSUE TITLE
InfluxDB: Remove `remove` button when you click the items on query builder

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#73778]
Since we have this explicit delete button in place https://github.com/grafana/grafana/pull/72825, we don't need the `remove` buttons in the pop-up. 
It should be removed.

![Image](https://user-images.githubusercontent.com/820946/263020364-a8cb8504-c472-48c5-b6e6-c630ec176f36.png)

**Comment by Jhanvi12** [comment]
Can you please assign this to me , I will try to work , contribute and raise MR for this.

**Comment by itsmylife** [comment]
@Jhanvi12 I did. Thanks for your contribution in advance!

**Comment by rakesh-venkata** [comment]
Hey,Is this issue completed.If not,I will work on it.

**Comment by Jhanvi12** [comment]
Hey, thanks for reaching out. I am working on it and will push the code by end of the week after my final secure code review.

**Comment by siddhikhapare** [comment]
@itsmylife My local repository is up to date after fetching the latest updates from the remote repository, and there are no new changes in my local directory. I re-cloned it  to address other issues.  I've created this new pull request with the required changes. Please take a look when you have a moment. Thank you for your guidance.

**Comment by itsmylife** [comment]
@siddhikhapare I will check it today. Thanks for all.

**Comment by rothardo** [comment]
is this issue still open? @itsmylife may I work on it?
