### ISSUE TITLE
Alerting: Navigating away from a partially created alert clears entered info

### ISSUE THREAD

**Issue by evan-chaney** [grafana/grafana#73785]
### What happened?

If you click the Create New Alert button, fill out the page and then accidentally click Notification Policies (or any other outgoing link) it happily takes you there and there is no way to regain all the configuration that you entered.

### What did you expect to happen?

I sometimes get an "ARE YOU SURE?" dialog when navigating away from a dashboard after making changes; I would expect the same to happen for alerts.

### Did this work before?

Not sure

### How do we reproduce it?

1. Click create new alert button
2. Make some changes
3. Click Notification Policies on the left sidebar

### Environment (with versions)?

Grafana: 9.5.1
OS: CentOS 7
Browser: Google Chrome 114.0.5735.198

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @evan-chaney,

Thanks for opening this issue.

We will take a look into it and will reply to you soon.

**Comment by usmangt** [comment]
Just tested this on the grafana-oss-version 10.1.1 and it seems as expected.

This sounds like a feature-request. I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by armandgrillet** [comment]
We should indeed either warn about leaving the page with content set in it or use e.g. local storage to allow going back on the page and having the previous data in the form.
