### ISSUE TITLE
Transformations: Help button doesn't activate uncollapse collapsed transformation

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#73796]
![Screenshot 2023-08-24 at 4 24 46 PM](https://github.com/grafana/grafana/assets/199847/3cbe0f02-21b0-483e-a771-01bce5a5a3ab)

When using the help button on a collapsed transformation it will toggle the help state but it will also _not_ uncollapse the transformation. This makes for a confusing user experience as in the case it appears that the help button is not doing anything.

**Comment by baldm0mma** [comment]
Looking into this!
