### ISSUE TITLE
Docker: ubuntu flavour base image is inconsistent among different tags

### ISSUE THREAD

**Issue by sxm51** [grafana/grafana#73799]
### What happened?

Since Grafana v10.0.4, It appears that the `grafana/grafana` docker image with tags `10.0.4-ubuntu`, `10.1.0-ubuntu` ,`latest-ubuntu` are using Ubuntu v22.10.

And tags `main-ubuntu`, `10.0.3-ubuntu` and versions before it, are using Ubuntu v20.04.

As far as I can work out from changelog and the build scripts, we expect to use Ubuntu v20.04.

* `10.1.0-ubuntu` (Base - ubuntu 22.10) : https://hub.docker.com/layers/grafana/grafana/10.1.0-ubuntu/images/sha256-fe682d3cc1008b413ccd8460fbf93aed9acf9f67f93776a4a4d4a08684157e5e?context=explore
* `10.0.4-ubuntu` (Base - ubuntu 22.10) : https://hub.docker.com/layers/grafana/grafana/10.0.4-ubuntu/images/sha256-71fd5481f641c6ca0d1f0057158fb0ccc095bfca0cd057a2d26eb6519695b8f4?context=explore
* `latest-ubuntu` (Base - ubuntu 22.10) : https://hub.docker.com/layers/grafana/grafana/latest-ubuntu/images/sha256-fe682d3cc1008b413ccd8460fbf93aed9acf9f67f93776a4a4d4a08684157e5e?context=explore
* `main-ubuntu` (Base - ubuntu 20.04): https://hub.docker.com/layers/grafana/grafana/main-ubuntu/images/sha256-9a3fba7145e61a3388223976eca383129bc3b2cc32b3197a62c0f4c2ec163b30?context=explore
* `10.0.3-ubuntu` (Base - ubuntu 20.04): https://hub.docker.com/layers/grafana/grafana/10.0.3-ubuntu/images/sha256-3fe2c2d06e7888c7376859a45e91d36ef44ff83ad285c0c844eb84a16d7c3466?context=explore

### What did you expect to happen?

As far as I can tell from changelog and the build scripts, we expect Grafana image to be based on Ubuntu v20.04.

### Did this work before?

Yes. Docker tags `main-ubuntu`, `10.0.3-ubuntu` and versions before it, are based on Ubuntu v20.04.

### How do we reproduce it?

In order to find the ubuntu release, run: `docker run -it --rm --entrypoint sh grafana/grafana:$TAG -c 'cat /etc/lsb-release'`.
Tags in question are mentioned above.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.1.0, 10.0.4
OS: Linux, Docker
Browser:

### Grafana platform?

Docker

### Datasource(s)?

N/A

**Comment by usmangt** [comment]
Hi @sxm51,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by kminehart** [comment]
This was intentional, we're slowly transitioning to an entirely different build process that's decoupled from the Grafana source code. Is upgrading our docker base image causing any particular issue for you?

**Comment by sxm51** [comment]
It'd be good if the changes are communicated via change-log or such.
In my case, Grafana docker image is used as the base and add a few customisations is added on top. (_layering_)
One of the customisation is dependant on the base image flavour/release.

Also, clarifying - Ubuntu v22.10 is a short support release, Are we moving away from LTS versions.

**Comment by kminehart** [comment]
hmm I'll look into this. I believe we upgraded because our docker images would no longer build with 22.04 but I'll make sure tomorrow.

If you're going to use Grafana as a base image maybe it would be better to do a multistage build and copy the binaries and such into your own image that way our base image changing doesn't affect your build process.

**Comment by kminehart** [comment]
I'll chat with the rest of the team about what our expectations are with docker image bases.

Typically the upgrade base images because we're constantly getting reports about vulnerable package dependencies.

**Comment by kminehart** [comment]
We decided to stick to the LTS versions (22.04) for future releases. Good catch.
