### ISSUE TITLE
Transformations: Better Debug

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#73797]
Currently the debug button on transformation shows two data frame objects alongside of each other.

![Screenshot 2023-08-24 at 4 35 13 PM](https://github.com/grafana/grafana/assets/199847/0a2a49aa-36ca-45f1-a1e4-11f1b3c0be5e)

This is less than ideal in terms of displaying what is happening and assumes that the user has the knowledge and capability to understand data structures underlying the transformation. Ideally we could use some variation on the table display that we're already using.

**Comment by baldm0mma** [comment]
@codeincarnate do you mean, instead of the json data structures, show 2 tables, one with data from before the transformation, one with the data after?

**Comment by codeincarnate** [comment]
We've moved debug into a drawer so considering this one fixed. We'll come back with further improvements here.
