### ISSUE TITLE
Task: Increase title length before truncation

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#73790]
Titles longer than 35 characters are getting truncated. This is too short and we have plenty of space to display a longer title on Desktop. Keep this length for mobile and change it to make it responsive on desktop. 
![image](https://github.com/grafana/grafana/assets/20256983/f3433f9e-656e-4a13-bbef-e5bd76055cda)

**Comment by aditipatelpro** [comment]
Hi @natellium, I would like to contribute to this issue. Could you please assign it to me?

**Comment by aditipatelpro** [comment]
Hi @juanicabanas, @natellium @evictorero , I have completed working on this issue. Could you please review the PR, #73972 ?
