### ISSUE TITLE
How to avoid retriggering firing unified alert again during helm upgrade

### ISSUE THREAD

**Issue by bossjie** [grafana/grafana#73801]
### What happened?

I have 2 instances(9.4.7) and set up HA alerting. backend db is PG.
during the helm upgrade for grafana, the firing alerts would be retriggered. I consider when pod gets inited, it cannot touch/detect well with rest of pods at startup.
in grafana, we have a lot of monitoring. It’s hard to make a batch silence for all alerts as they are matched by tags.
I even enarge the "for" param to 5m, it's still retriggered.

### What did you expect to happen?

not retrigger

### Did this work before?

no

### How do we reproduce it?

as desc

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:  9.4.7
OS: centos 8
Browser: chrome

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @bossjie,

Thanks for opening this issue.

Did you try to use the silence option to silence your rules during the update/upgrade process?

**Comment by bossjie** [comment]
@usmangt   yes, but you know, users have variety of tags they customize.  even we ask them to use one common tag to manage, it's still a soft rule.   Also it's a choice to only pick up firing alerts but it's also taking efforts everytime.
what we did is to update database to add a common tag if the alert rule does not have this tag.   But it's just a workaround with manul work.

**Comment by bossjie** [comment]
thanks for following up. not sure if there is any plan to figure it out.
