### ISSUE TITLE
Alerting: datasource not set when switching to Prometheus

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#73814]
### What happened?

I have a default Grafana datasource which is a Prometheus datasource. When creating a new alert, it is a Grafana managed alert. When clicking on the switching button to create a Prometheus alert rule, the datasource is not selected anymore.

### What did you expect to happen?

The correct datasource should be selected.

### Did this work before?

The new UI did not exist pre 10.1

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Mimir

**Comment by gillesdemey** [comment]
Confirmed to be a bug – this seems to only occur when the default data source supports data source managed alerts.
