### ISSUE TITLE
[Bug] Numerical template sorting breaks on empty value

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7382]
Grafana v4.1.1 (commit: v4.1.1) with Prometheus 1.5.0

My template query returns:

````
All
8
6
5
3
1
14
7
2
13
10
4
  << this here be empty
12
11
9
15
16
````

which makes Grafana unhappy:

````
Templating
Template variables could not be initialized: Cannot read property 'match' of undefined
````

While I could regexp away the empty string, I would argue that this is a common occurence and should be handled properly.

**Comment by bergquist** [comment]
Removing empty values when sorting numbers makes sense. But how should we handle empty values when sorting strings? 

Should we allow template values that are empty? Sounds useless to me but I would not be surprised if someone template values for something like that.

**Comment by torkelo** [comment]
Not sure sorting should remove values, maybe just not throw error if encounters an empty string

**Comment by RichiH** [comment]
Sorting MUST NOT (in the IETF sense) change values.

**Comment by bergquist** [comment]
makes sense. Fix inc.

**Comment by RichiH** [comment]
PS: Please be consistent in where you sort empty values. I think it's standard to put them at the front (as they have zero length, thus come first), but I don't really care how you do it as long as you stick to it in _all_ the places.

**Comment by bergquist** [comment]
Having a hard time reproducing this. 

Seems like the query template sorting can handle all cases I throw at it: 
https://github.com/grafana/grafana/blob/927b39fa63c0ba8f4132d8f205da2cf52c24db8b/public/app/features/templating/specs/query_variable_specs.ts#L51
