### ISSUE TITLE
[Feature request] Make tooltip toggleable or selectable

### ISSUE THREAD

**Issue by sacasumo** [grafana/grafana#7384]
It would be really useful to make the selection or display of tooltips selectable or editable from the top row (next to the annotations, or on the right next to the external links?)

Gives the option of quickly selecting the level of detail on a metric, rather then go into the dashboard settings.

**Comment by torkelo** [comment]
Not sure i understand. 

You want to be able to select tooltips? how does that change level of detail?

**Comment by sacasumo** [comment]
not exactly, tooltips give a lot of detail which is great for troubleshooting, however that level might not always be necessary when you're looking at the graphs and investigating. Currently to toggle the tooltips on or off, you need to go to th cog, settings, general, panel options, and select it or remove it from there.

If that could be extended to the row above the top panel(s) - next to the templating selector / annotations / dashboard list, it would be quicker to toggle between these modes.

**Comment by torkelo** [comment]
you mean the shared crosshair and shared tooltip options (that show tooltips on all graphs at the same time?) .

You want to completely remove the tooltips so they are not visible when you hover over the graphs? What does this have to do with selectable & selecting detail on a metric??? 

The options in the settings menu for shared tooltip and shared crosshair already has keyboard shortcuts

**Comment by sacasumo** [comment]
aha didn't know about the keyboard shortcut, that's even better, thanks!
