### ISSUE TITLE
Impossible to enter label value queries for dashboard variables

### ISSUE THREAD

**Issue by igors** [grafana/grafana#73858]
### What happened?

A recent Grafana Cloud update changed the UX of dashboard variable label value queries, which made it next to impossible to create them due to timeouts. Specifically, the old UX allowed us to enter the label query pretty much manually; the only option in the new UX is using the query builder and it takes forever to load and times out most of the time trying to do that for us. I'll try to attach a screen recording but trying to select an option from "Metric" dropdown results in a spinning wheel that takes forever to finish if at all and typing a known metrics name there doesn't work at all - it won't take it until the spinning wheel is done. To make matters worse, the query/spinning wheel is terminate the moment I switch the windows so I'm stuck staring at the screen until it almost inevitably times out.

I asked about this in [Grafana slack](https://grafana.slack.com/archives/C0Y4TLW74/p1692042036900509) and using Series query was mentioned as a possible alternative. It indeed helps a little (as in - it makes it at least physically possible to create a label values query for a variable) but is still a pain. That is, Grafana toggles back to “Label values” UI the moment you hit tab/enter/change the screen etc, with no way of going back to the series query. I.e., you’ll need to start over from scratch if you don’t type your query exactly right. It’s better than nothing but still rather inconvenient and is a significant regression compared to the old UX.

### What did you expect to happen?

I expect to be able to create dashboard variable label values query without major pain

### Did this work before?

Yes. I don't remember the version it worked in; the first version I know it got broken in is v10.2.0-59422pre (25690811) but I can't guarantee that was the first ever version to break this.

### How do we reproduce it?

1. Screen recording is attached but, generally, just try to create a dashboard variable label query with a slowish thanos data source

https://github.com/grafana/grafana/assets/147591/f11ee5dc-4025-4b87-9b17-adb27fdb928b

### Is the bug inside a dashboard panel?

Not exactly, it's inside dashboard's Configuration->Variables screen

### Environment (with versions)?

Grafana: v10.2.0-59585pre (24978eff)
OS: OSX
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

thanos

**Comment by usmangt** [comment]
Hi @igors,

Thanks for opening this issue.

1- Is this only specific for Thanos Data source or also reproducible with others too?

2- Is anything different noted while using other browsers e.g. Google Chrome?

3- Can you please send us the HAR file by capturing the web session traffic once you write the up query? Here, is a reference [link](https://support.google.com/admanager/answer/10358597?hl=en) as how to capture it using Chrome DevTools.

**Comment by igors** [comment]
1. thanos is the only source I can test against atm
2. I get the same exact behavior in Chrome
3. Is there a way to send it privately and/or expunge our private data from it?
