### ISSUE TITLE
[Bug] Using a template variable in another template variable for OpenTSDB query doesn't work anymore.

### ISSUE THREAD

**Issue by Helene** [grafana/grafana#7385]
Please include this information:
- What Grafana version are you using? 4.1.1 latest
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Windows
- What did you do?
I'm using Graph dashboard with 3 template variables:
myMetrics =metrics(gpfs_pool.*)
myFilter=tag_names($myMetrics)
byValue=tag_values($myMetrics, $myFilter)
which helps me to select the metric and put the filter for the graph dynamically. This did work fine with Grafana 3.0.4 and 3.1.1
![templating3 0 4](https://cloud.githubusercontent.com/assets/22845495/22370929/537931fa-e494-11e6-951c-046fcf25337d.JPG)

Now I upgraded my Grafana environment with the latest available package 4.1.1. 

- What was the expected result?
The same dashboard with the same template variables doesn't work properly anymore. 
- What happened instead?
I have already checked the datasource connection and refreshed all settings, but the $myFilter and $byValue variables doesn't return values:

![templating4 1 1jpg](https://cloud.githubusercontent.com/assets/22845495/22371050/0205d0c0-e495-11e6-92d7-dfa023ea34f3.JPG)

My observation:

in Grafana 3.x the REST API, GET request lookup for tag_names($myMetrics) did properly resolve the $variable with its value from selection menue. Somehow this is broken in Grafana 4. Compare REST API url in the next screenshots:

Grafana 3
![grafana3 1 1](https://cloud.githubusercontent.com/assets/22845495/22371174/e76a26ac-e495-11e6-9dae-c2ec74ceaba7.JPG)

Grafana 4.1.1 latest
![grafana4 1 1](https://cloud.githubusercontent.com/assets/22845495/22371183/f8fed3f4-e495-11e6-8904-d73e8f4dc65e.JPG)

**Comment by Udayrakesh** [comment]
If you remove the .* part from $myMetrics the template variables should work.
So just change myMetrics =metrics(gpfs_pool)

**Comment by utkarshcmu** [comment]
There was a templating bug fix recently for OpenTSDB - https://github.com/grafana/grafana/pull/7208 

This should be rolled out in 4.2.0. Also, if you want you can use the nightly build from Grafana!

**Comment by Helene** [comment]
With the latest nightly build all template variables work as expected. Many thanks for support!
