### ISSUE TITLE
Grafana 10.1.0: high cpu load + login failed

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#73859]
### What happened?

Hi, today I´ve updated two RPi to Grafana 10.1.0.
After it I wondered about the CPU load:
![efd463686ce77f8f2e43898ff7886285c78f1136](https://github.com/grafana/grafana/assets/81651521/027078b3-dd92-4621-adcd-dc48dd50ec08)
![5ef9c81fb5e0b5af666c2d0c2c6256bc1d5e2e96](https://github.com/grafana/grafana/assets/81651521/024d7d95-a74f-407a-bf39-2678626f4299)
the red line is the cpu load before the update.

further I can´t login:
![grafik](https://github.com/grafana/grafana/assets/81651521/ec6fe5be-8183-4a03-907a-e9a4126ef07c)

So I installed the last version of grafana, with reboot, but the CPU load stays high.
now I'm at a loss

### What did you expect to happen?

no high cpu load, login possible

### Did this work before?

yes!

### How do we reproduce it?

update to 10.1.0

### Environment (with versions)?

Grafana: [v10.1.0 (838218ba20)
OS: Linux raspberrypi 6.1.21-v8+
Browser: firefox

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @Becker884,

Thanks for opening this issue.

So we might be 2 issues here

1- For the login
2- High CPU load

So lets break it step by step. Please provide the following information:

1- What was your previous Grafana version before you updated it to v10.1.0?
2- About the login issue, what account you are trying to log-in i.e. admin or some other account?
3. Could you please change the default log level to debug mode? 

To do this go to the server where grafana is installed and edit the configuration file (`/etc/grafana/grafana.ini`)

There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again for the Login.

**Comment by Becker884** [comment]
Hi,
I found the Issue #73781   https://github.com/grafana/grafana/issues/73781#issuecomment-1691980658 
with pre-pre version all right.

on a Linux VM (x86) the new Grafana runs without problems.

**Comment by usmangt** [comment]
Good to hear that you found the known issue. I worked on a couple of similar issue yesterday and yes looks like yours is same as https://github.com/grafana/grafana/issues/73781 

Therefore closing it as duplicate.
