### ISSUE TITLE
Alerting CloudWatch: Metric Query Builder - metric name may need quoting

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#73868]
### What happened?

When defining CloudWatch alert in `Metric Query` `Builder` mode and selecting a metric name with special chars (e.g. `%`) the metric name must be quoted or no results are returned.

### What did you expect to happen?

Results being returned when using the CloudWatch `Metric Query` `Builder` independently of the selected metric name.

### Did this work before?

n/a

### How do we reproduce it?

1. Create a CloudWatch Alert with `Metric Query` `Builder` mode, e.g.:
```
Namespace=AWS/RDS
WithSchema=true
Schema labels=DBInstanceIdentifier
Metric name=EBSByteBalance%
Aggregation=MIN
Group by=DBInstanceIdentifier
```
and the generated code for the config above is:
```sql
SELECT MIN(EBSByteBalance%) FROM SCHEMA("AWS/RDS", DBInstanceIdentifier) GROUP BY DBInstanceIdentifier
```
2. Click Run queries - NO RESULTS returned.
3. Switch from `Builder` to `Code` and update the query so the metric name is enclosed by double quotes:
```sql
SELECT MIN("EBSByteBalance%") FROM SCHEMA("AWS/RDS", DBInstanceIdentifier) GROUP BY DBInstanceIdentifier
```
4. Click Run queries - RESULTS show as expected. 

### Environment (with versions)?

Grafana: v10.1.0 (ff85ec33c5) - official docker image
OS: linux/amd64
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

CloudWatch 5.0.0

**Comment by fridgepoet** [comment]
Thanks @salavessa for reporting this issue, I was able to reproduce it exactly with the steps you've detailed. 
On a Grafana Cloud instance v10.2.0-59882 (3ee26df4):
I see a syntax error in Builder mode:
`message: "metric request error: \"ValidationError: Error in expression 'query...': Invalid syntax near '%) FROM SCHEMA(\\\"AWS/RDS\\\", DBI...'\\n\\tstatus code: 400, request id: ...\"`

I do not observe that after adding the quotes in Code mode.

**Comment by salavessa** [comment]
I just found that when a metric name starts with a number it's also required to enclose it with double quotes, e.g. `SELECT SUM("4xx") FROM SCHEMA("AWS/ES", DomainName, ClientId) GROUP BY DomainName`
