### ISSUE TITLE
10.1.0 Login fails: cannot remove last organization admin

### ISSUE THREAD

**Issue by Netherwhal** [grafana/grafana#73866]
### What happened?

After upgrading to 10.1.0 I receive following error:

> Login failed
> cannot remove last organization admin

The following environment variable is set:

```
GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC      = "true"
GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP     = "true"
```

Upon login it is trying to downgrade my role from Admin to Viewer, then the error happens.
My expectation of the settings above is to not sync the roles and leave me as Admin, as my generic oauth does not have a role-mapping configuration yet.

### What did you expect to happen?

Login should work

### Did this work before?

Yes

### How do we reproduce it?

1. Upgrade to 10.1.0
2. Login

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.0
OS: Docker
Browser: Edge

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @Netherwhal,

Thanks for opening this issue.

What was the previous Grafana version you were using before updating it to v10.1.0?

Also, can you please change the default log level to debug mode? 

To do this go to the server where grafana is installed and edit the configuration file (`/etc/grafana/grafana.ini`)

There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again.

**Comment by carsten-re** [comment]
I had a similar behaviour. I'm using Authelia for authentication.
I fixed it with:

- added in Authelia a group for my user: "GFadmin"
- added in Grafana docker-compose: GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC=true
- added in grafana.ini (below [auth.generic_oauth]): 
  role_attribute_path = contains(groups[*], 'GFadmin') && 'Admin' || contains(groups[*], 'GFeditor') && 'Editor' || 'Viewer'

**Comment by chrisliebaer** [comment]
I have observed the same behavior with Authentik on a freshly installed Grafana instance. It appears that `GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC` is not implemented properly. Setting it to `true` allows me to manually set user roles, but does not prevent Grafana from resyncing roles with my OpenID provider. What @carsten-re proposes is not a fix, as it actually WILL configure role sync, leading to a situation in which Grafana supposedly allows manual overrides, but resets them upon each login.

**Comment by kalleep** [comment]
This was fixed in https://github.com/grafana/grafana/pull/72752. But for some reason it did not make it into 10.1.0.
@eleijonmarck I can see that we did backport it to 10.1.x so it should be included in next 10.1 release correct?

**Comment by eleijonmarck** [comment]
Yes this will be in the next public release on September 26th (preliminary)

**Comment by pseudocoder** [comment]
This does not seem to have been fixed in 10.1.4 ?

**Comment by usmangt** [comment]
Hi @pseudocoder ,

Can you please the new logs if this is still reproducible on version 10.1.4?

**Comment by pseudocoder** [comment]
Sorry my mistake, I forgot to add back in the oauth_skip_org_role_update_sync=true setting, it does now work on 10.1.4

**Comment by usmangt** [comment]
Reopening and triaging it to the Auth team

**Comment by owenfiscus** [comment]
Here is the environment variable mapping to implement this change if you are running Grafana in Docker.

``` yaml
- GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC=true
```

**Comment by fuomag9** [comment]
> ```yaml
> - GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC=true
> ```

Thank you, I had to add this with authentik as well
