### ISSUE TITLE
[Bug] "Failed to create user specified in auth proxy header"

### ISSUE THREAD

**Issue by solugebefola** [grafana/grafana#7387]
Grafana version: 4.1.1 (docker image)
datasource: iobeam (custom) 
OS: Debian:jessie (from grafana/grafana-docker

I set up grafana with auth proxy enabled and it is working fine for most cases(usernames).  For some reason, when I try to send the username `support@iobeam.com`, I get the server-side error with the message "Failed to create user specified in auth proxy header".  

The login process works normally for any other username I have tried, including other usernames with `@iobeam.com` suffixes.  
Also, when I run a local copy outside of a docker container, `support@iobeam.com` works fine.

I noticed #6903 and some older bugs, but nothing related to inconsistency in user creation.

Cheers

**Comment by torkelo** [comment]
strange, no idea why.  Maybe someone else already has that email. Can you check the database and the user table?

**Comment by solugebefola** [comment]
Yup, you were right.  A separate user had the same email.
