### ISSUE TITLE
Packaging: conffiles control file missing in debian package for 10.1.0 and 10.0.4

### ISSUE THREAD

**Issue by rbfnet** [grafana/grafana#73870]
### What happened?

Installed 10.1.0 via package manager download from apt.grafana.com, /etc/default/grafana-server (which I had customized) was overwritten with grafana-server from the package..

Cause appears to be that the "conffiles" control file is missing in the 10.1.0 deb package.  I looked at 10.0.4 and it's also missing there.  It is present in 10.0.3.

### What did you expect to happen?

Customized /etc/default/grafana-server to remain in place

### Did this work before?

Yes.  All upgrades (via package manager download from apt.grafana.com) in the past have left the customized configuration files in place.

### How do we reproduce it?

1. Install 10.0.1 debian package from apt repository
2. Customize /etc/default/grafana-server
3. Install 10.0.3 debian package from apt repositoy
4. Observe that customized /etc/default/grafana-server remains in place (i.e. file was NOT replaced with the file from the package)
5. Install 10.1.0 from apt respository
6. Observe that customiziations in /etc/default/grafana-server were lost (i.e. file was replaced with the file from the package)

Can also reproduce by downloading and expanding the packages and observing that "conffiles" control file is present in 10.0.3 but not 10.1.0.  (I also observed it is absent from 10.0.4.)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.0
OS: Ubuntu 22.04
Browser: n/a

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

n/a

**Comment by kminehart** [comment]
Thanks for letting us know. We'll look into this.

**Comment by kminehart** [comment]
We've identified and resolved the issue in our build process. This will be resolved in the next release :)
