### ISSUE TITLE
Alerting: Mute timing time selector is subpart compared to the one for silences

### ISSUE THREAD

**Issue by JDA88** [grafana/grafana#73882]
### What happened?

The time (and timezone) selector when creating a new `Mute Timings` from `Alerting` > `Notification policies` > `Mute Timings` is confusing:
![image](https://github.com/grafana/grafana/assets/67072186/81649514-1685-41c5-a90c-dde506f5b3b4)

Comparing to the standard one, from silence for example:
![image](https://github.com/grafana/grafana/assets/67072186/724485ea-2b59-42d4-a40d-ee27a5b80be6)

It doesn’t display the +XX from UTC, country and time zone name

### What did you expect to happen?

Similar behavior’s between all times range pickers.

### Did this work before?

no

### How do we reproduce it?

Create a new `Mute Timings` from `Alerting` > `Notification policies` > `Mute Timings`

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2
OS: Grafana Cloud
Browser: Edge / Chrome

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
thank you for your feedback @JDA88 

That's a good question. I am not sure why timezone might be not so relevant in silences. Perhaps silences don't need to care about the time zone, but only that they match the label of an alert? (at least that's the API that is being reached).

In any case, I will forward your comments on the lack of UTC, country and time zone name in the creation of Silences to the Alerting team.

**Comment by armandgrillet** [comment]
The user is complaining about the mute timing time selector not being the default one, which looks like this:

<img width="546" alt="SS 2023-08-30 at 11 14 28" src="https://github.com/grafana/grafana/assets/2117580/288dd511-a1c7-401d-aed7-583dc2bc6b4b">

The mute timing time selector is indeed not as good as it does not show the time in UTC and just the region, this is due to the fact that we are restricted by the mute timing implementation in the Prometheus Alertmanager.

**Comment by JDA88** [comment]
> ...this is due to the fact that we are restricted by the mute timing implementation in the Prometheus Alertmanager.

Indeed, and Alertmanager been a "system" service it does not need to be as user friendly as Grafana.
I just think the interface in Grafana should be consistent when it deals with similar data types (time range in this case)

PS: Thank you for making the title clearer
