### ISSUE TITLE
[Feature request] - Legend names shortening/regex

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#7389]
- What Grafana version are you using? - 4.1
- What datasource are you using? - Prometheus
- What OS are you running grafana on? - Centos 7 64 bit
- What did you do? - Added a graph with long legend names
- What was the expected result? - Be able to extract part of variable
- What happened instead? - No known option 

I have the following graph panel representing CPU usage for some services. I use the {{name}} variable from Prometheus to populate the legend. 

Would it be possible to extract part of a variable instead of the whole {{name}}. For example If I have the name as "ThisServiceNameIsReallyReallyLong" - How can I extract with regex part of the name? i.e. I want to display "Service" instead of the whole thing.

![selection_057](https://cloud.githubusercontent.com/assets/12910496/22380400/3b0f6c76-e4b5-11e6-9afe-cae47b03d164.png)

**Comment by torkelo** [comment]
This is feature that some other databases implement in the query language, but Prometheus has left it up to the UI. So Grafana will have to implement something like this. We are currently figuring out how to best support this scenario. 

https://github.com/grafana/grafana/issues/3545
https://github.com/grafana/grafana/pull/6627
