### ISSUE TITLE
Invalid Grafana-managed alert rule labels suggestions

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#73890]
Custom labels editor provides incorrect suggestions for Grafana-managed alert rules

![Image](https://github.com/grafana/grafana/assets/6293563/005d5366-788f-4e79-97d6-9e731130e205)

The suggestions are based on the `/api/ruler` response from the selected data source. While this behavior is correct for Mimir/Loki rules it's wrong for Grafana-managed rules

Grafana-managed rules should use the `/api/ruler/grafana` response to populate suggestions no matter what data sources are selected in the queries section

**Comment by gillesdemey** [comment]
I'm wondering if perhaps we should _merge_ the labels when creating a Grafana Managed alert rule with a Prometheus / Mimir data source? 🤔

**Comment by konrad147** [comment]
I'd say no. Labels defined on alert rules in Mimir/Prometheus may have nothing in common with the rules you have defined in Grafana-managed rules. Keep in mind we provide the suggestions from rules' labels, not from data source labels
