### ISSUE TITLE
When I use Stat charts and set the value of min to exceed max through the inputNumber step method, it will trigger a page crash

### ISSUE THREAD

**Issue by HandsomeBrother** [grafana/grafana#73907]
### What happened?

When I use Stat charts and set the value of min to exceed max through the inputNumber step method, it will trigger a page crash

### What did you expect to happen?

When the min value set by the user exceeds the max value, the front-end will add some verification prompts to improve the user experience, and here  is my solution: https://github.com/grafana/grafana/pull/73902

### Did this work before?

no

### How do we reproduce it?

1.Simply enter a panel editing page
2.Switch chart type to Stat
3.Click on inputNumber to 1 for min
4.Click the increase button of max until the value is 1
5.Page Stuck Until Crash

### Environment (with versions)?

Grafana:10.2.0-pre
OS:MacBook Pro (13-inch, M1, 2020)
Browser:116.0.5845.96（正式版本） (arm64)

### Grafana platform?

None

**Comment by tonypowa** [comment]
thank you for reporting this issue and for your contribution ! @HandsomeBrother 

I could reproduce it and so I have added the issue to the engineer's project board

they will get back to you as soon as business allows

**Comment by HandsomeBrother** [comment]
@tonypowa How's the progress going

**Comment by tonypowa** [comment]
Hi ! there is work in progress here
https://github.com/grafana/grafana/pull/73902

i will ping the engineers to know more details
