### ISSUE TITLE
Alerting: Grafana Mute Time Range Error: ‘bad request data’

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#73912]
### Discussed in https://github.com/grafana/grafana/discussions/73355

<div type='discussions-op-text'>

<sup>Originally posted by **jagan985** August 17, 2023</sup>
I want to send mail alert from Grafana only by 11 AM IST and 5 PM IST. Which is 5:30 AM UTC and 11:30 AM UTC respectively. But I don’t see any specific time to mention. But I found the mute time range. I provided the mute time range as below in UTC,
IST::: 11:05 - 16:55
UTC::: 05:35 - 11:25

IST::: 17:05 - 10:55
UTC::: 11:35 - 05:25

But Grafana considers only the first-time range. If I provide the 2nd time range or add 'Another time interval', it gives error as ‘Error: bad request data’.
pls help to resolve this. 
</div>

**Comment by jagan985** [comment]
pls let me know once this gets fixed.

**Comment by armandgrillet** [comment]
You cannot go over 00:00 UTC with a mute time range. Your mute timing should thus be:

- 00:00 - 11:25
- 11:35 - 23:59

The latest version of Grafana (10.1) tells you that you cannot do what you were initially trying to avoid creating a bad request
