### ISSUE TITLE
[Bug] InfluxDB:  no datapoints

### ISSUE THREAD

**Issue by mlukjani** [grafana/grafana#7392]
Hi !
I have spend few evenings to get it working without success :(
Platform is Raspberry Pi2 with InfluxDB 1.2.0 (previously 1.1.0) and Grafana 4.1.1, configured with std ports and parameters.
IfluxDb is properly configured and has data in.

![obraz](https://cloud.githubusercontent.com/assets/16481042/22396196/537ec1b4-e553-11e6-9245-f70068be22c6.png)

CLI also shows data under sine_wave measurement.

Grafana can see Db:
![obraz](https://cloud.githubusercontent.com/assets/16481042/22396207/8afac1d8-e553-11e6-9285-3871c5d1f2e3.png)

Unfortunately under Dashboards simple query shows no datapoints:

![obraz](https://cloud.githubusercontent.com/assets/16481042/22396216/d5344b16-e553-11e6-8653-16ed2219749f.png)

Logs shows only:
`t=2017-01-28T12:05:28+0100 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-01-28T12:05:38+0100 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0`

InfluxDB's ports are open:

```
root@raspberrypi:/home/pi# sudo netstat -naptu | grep LISTEN | grep influxd
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN      31519/influxd
tcp        0      0 0.0.0.0:8086            0.0.0.0:*               LISTEN      31519/influxd
tcp        0      0 0.0.0.0:8088            0.0.0.0:*               LISTEN      31519/influxd
```

I have same with previous version of InfluxDB.

**Comment by rovincent** [comment]
I'm a newbi so no idea if this helps was looking for another problem.

However reading your post one thing i notice is on my side the query for the graph module does not like mine.

SELECT last("value") FROM "********/*******/******/FirstSolarCell" WHERE $timeFilter GROUP BY time($interval) fill(null)

No idea if this helps but good luck.

**Comment by markusr** [comment]
Maybe this related to this bug:  https://github.com/influxdata/influxdb/issues/7879 ?

**Comment by mlukjani** [comment]
@rovincent 

I am using as simplest query as it possible just SELECT * FROM "sine_wave" 

@markusr 
No it is not same problem. I have never seen any graph on my dashboard, just "no datapoints". It was same on 1.1.0.
Problem seems to be with connection, but all necessary ports are open, Grafana also can connect with my DB.

**Comment by torkelo** [comment]
if InfluxDB is not returning any datapoints, strange not sure why. 

But never use a query without Group by time and WHERE $timeFilter   (better use the UI query builder)

**Comment by torkelo** [comment]
Please do not use Github for questions (this is in the issue template), the mailing list is good for questions :)

**Comment by rovincent** [comment]
will do. 

----- Original Message -----

**Comment by rovincent** [comment]
HI Torkel, 

Thanks for the response. I only use the gui query builder so i will find out what or how i made the mistake, again thanks. 

----- Original Message -----
