### ISSUE TITLE
[Bug] Strange graph behavior not sure if its a bug?

### ISSUE THREAD

**Issue by rovincent** [grafana/grafana#7393]
I'm new to Grafana and have only been using it around 6 months (fantastic tool by the way). So not sure if this is a bug or just my missing something obvious but I've tried several things and can not understand whats going on. 

Please include this information:
- What Grafana version are you using? 4.1.1-1484211277
- What datasource are you using? 1.2.0-1
- What OS are you running grafana on? Ubuntu 16.04
- What did you do? Using graph module to display multiple queries
- What was the expected result? All data should show on graph and be shown in all time frames
- What happened instead? In 1 hour i get full data, in 24 hour i get full data but in intermediate time intervals i get partial data on one query: However in a separate graph with the same query the data is there in all time intervals. Both graphs have the same options and settings see screen shots below. 

The image below shows a graph with several data points that all print well. Yet the tempAtPump data point truncates on this graph (i have removed it and re-added it and tried most options with no success).
 
![grafana-potenial bug1](https://cloud.githubusercontent.com/assets/9094518/22397432/32c59038-e53f-11e6-9f18-ad4a9662e375.png)

The image below shows the same time frame but in its own graph and it display all data, on all time intervals? the only deviation I'm making from a default graph is to change the selector to "last" instead of mean. ? (ive tried putting it back and not joy).

![grafana-potenial bug2](https://cloud.githubusercontent.com/assets/9094518/22397440/50088ed4-e53f-11e6-9d3a-8dec2b70b6b3.png)

Any help would be appreciated.

**Comment by rovincent** [comment]
As you can see from the screen below at the 1hour interval all of the data shows on the combine graph as well as the single graph (bottom) 

![grafana-potenial bug3](https://cloud.githubusercontent.com/assets/9094518/22397501/c3f51a78-e540-11e6-9a83-2560b2a1c5ed.png)

**Comment by torkelo** [comment]
I do not see a difference between the single graph and the combined. 

This is likely a InfluxDB query issue, you can inspect the queries Grafana sends and the response from InfluxDB in the chrome dev tools network tab.

**Comment by torkelo** [comment]
Sorry, now I see the difference. Looks strange. You should definitely investigate what InfluxDB returns for that series when all queries are sent at once
