### ISSUE TITLE
Add delay (or throttling / debouncing) in Search tab

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#73943]
In the Search tab, when typing in the Duration field (and probably any other field of type Input), a spinner is shown near some other fields at every keystroke, which is a little annoying:
https://github.com/grafana/grafana/assets/135109076/50632afd-8795-4573-8e8e-7e40dde6c5a0

We should probably have some delay / throttling / debouncing / ...

**Comment by Ciggzy1312** [comment]
Hey @fabrizio-grafana if this issue is still up for grabs I would like to give this a try
My question is how much of a delay are we asking for the debounced function

**Comment by Ciggzy1312** [comment]
[Screencast from 01-09-23 04:28:30 PM IST.webm](https://github.com/grafana/grafana/assets/65884232/ab5fa8c6-7c88-468d-acf6-1c4dd3dd0131)

I have added a delay of 500ms as it seems to be the minimal amount to avoid the spinner at every keystroke
Should I make a PR?

**Comment by Ciggzy1312** [comment]
Made a PR for this
