### ISSUE TITLE
[BUG] user email invite link not working behind reverse proxy

### ISSUE THREAD

**Issue by mkohns** [grafana/grafana#7394]
- What Grafana version are you using?
4.1.1

- What OS are you running grafana on?
linux

- What did you do?
trying to invide new user with email
Setup is grafana behind nginx reverse proxy as described here
http://docs.grafana.org/installation/behind_proxy/

- What was the expected result?
invite links are correctly set

- What happened instead?
instead of http://foo.bar/invite/3hoXWMR6e2Jbjrn9rhF1uHsAGWlgHz
the port is added
http://foo.bar:3000/invite/3hoXWMR6e2Jbjrn9rhF1uHsAGWlgHz

nginx is reverse proxy from 80->3000

**Comment by torkelo** [comment]
make sure your grafana.ini has the correct value set for root_url , it should be the public facing url you use in the your browser
