### ISSUE TITLE
[Feature request] Data proxy logging setting

### ISSUE THREAD

**Issue by jaylinski** [grafana/grafana#7395]
## Information

- What Grafana version are you using?
master edba465a75e0a73a745970201e74b6728cc60f42
- What datasource are you using?
/
- What OS are you running grafana on?
/
- What did you do?
Tried to enable data proxy logging.
- What was the expected result?
Enable data proxy logging by setting `GF_SERVER_DATA_PROXY_LOGGING` as described in `config/sample.ini`.
- What happened instead?
I had to set `GF_DATAPROXY_LOGGING` as described in `config/defaults.ini`.

## Feature request
Are these two settings the same?

If yes, please remove the deprecated one to avoid confusion.

If not, please clarify the difference in the docs.

Thank you! :chart_with_upwards_trend:

**Comment by torkelo** [comment]
> Enable data proxy logging by setting GF_SERVER_DATA_PROXY_LOGGING as described in config/sample.ini.

Where did you find that? I can only find 

```ini
#################################### Data proxy ###########################
[dataproxy]

# This enables data proxy logging, default is false
;logging = false
```
Which means that the ENV variable name should be `GF_DATAPROXY_LOGGING`

**Comment by jaylinski** [comment]
@torkelo I found it inside the `sample.ini` file:

https://github.com/grafana/grafana/blob/master/conf/sample.ini#L53

**Comment by torkelo** [comment]
good catch must have been left during the development of that feature, will remove
