### ISSUE TITLE
Legend: Support hiding series with the same name

### ISSUE THREAD

**Issue by PhracturedBlue** [grafana/grafana#73960]
### What happened?

I have 2 queries that each produce multiple values with the same series name:
![image](https://github.com/grafana/grafana/assets/3126449/b000dcb0-1347-495d-a59c-67b79506bc63)
![image](https://github.com/grafana/grafana/assets/3126449/4813aeb9-8faa-4e32-9357-6b49545cd437)

If I click on one of the series in the legend, it filters to show both queries.  This is the behavior I want:
![image](https://github.com/grafana/grafana/assets/3126449/62e45ace-3aea-4cbf-bd08-8b7deff05c92)

However, I want it so that the legend is not duplicated (i.e. only one occurrence each of 'series', 'series1', 'series2').

I can get this by setting a panel override on `Query: B` with series->hide in area->legend
![image](https://github.com/grafana/grafana/assets/3126449/e003c7df-11d5-48bb-ab2f-50e085df47b0)

This looks exactly like I'd like.  However, now when I try to filter by clicking on a series in the legend, nothing happens (here I've clicked on series2):
![image](https://github.com/grafana/grafana/assets/3126449/b7170542-34f4-408b-a3a9-cecf949a65a0)

Note that a new 'Override2' was created, automatically

Note that my actual datasource is prometheus, but I've reproduced the problem using TestData for conveneince

### What did you expect to happen?

I expect to still be able to filter by legend after applying the `series: B` override

### Did this work before?

Unknown

### How do we reproduce it?

The images should show all configuration needed.
Use TestData datasource.
Create 2 queries each with 3 series
use a regex transform to rename the queries to have the same names
Apply a 'hide in area->legend' override to query B
Try to filter by series by clicking on the legend

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.0.3
OS: linux (using the stock grafana container)
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

No

**Comment by tonypowa** [comment]
@PhracturedBlue 
thank you for creating this issue and for the clear repro steps
I am sending this issue over to the dashboard's team for review

**Comment by tonypowa** [comment]
note for the reviewer:


once you create the override "Fields returned by query" on Query: B with series->hide in area->legend, and you click on a legend, you can see another override is applied automatically to stop certain series from being graphed. Perhaps this is a undesired behavior that has something to do ?

![legend_hide_test](https://github.com/grafana/grafana/assets/45235678/60ab9c40-56cc-4e3b-93dc-328215672a88)

**Comment by dprokop** [comment]
This is working as expected, however, it's funky. The filtering is solely done based on exact match against field names that need to be unique. 

In order to support your case, we need to improve the system override created when clicking on the legend (the one that appears at the end of the overrides list) to use some more information to identify the label being clicked. We could for instance use the frame/field index which is part of the `VizLegendItem` that's passed into leggend toggle handler.

We don't plan to work on this in the short term future, but any contributions are highly appreciated!
