### ISSUE TITLE
Data source config: CustomHeadersSettings saving does not show headers as configured

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#73966]
Data source agnostic, this issue with any configuration using the DataSourceHttpSettings component. This is not particular to InfluxDB, we just found it here @itsmylife 

When configuring a data source and adding custom headers, we expect the headers to show as "configured" when the data source is saved.

***not in the new custom auth only in DataSourceHttpSettings (older)

![Image](https://user-images.githubusercontent.com/25674746/263814759-c27f66c7-f0c7-4285-ade3-1321fc5fca87.png)

Currently though, clicking "Save & test" does not update the custom headers to show as configured. We continue to see the hidden inputs. Only when we refresh the page do we see the custom headers UI show "configured."

https://user-images.githubusercontent.com/25674746/263815826-9b8d2453-1ac1-4300-8f97-0b314889e4f3.mov

**Comment by L-M-K-B** [comment]
> Once the new auth component (has custom headers implemented) has been fully tested
@bohandley Do you have a related issue that we can link here to better keep track?

**Comment by bohandley** [comment]
Following up with @cletter7, is there an official issue that tracked testing the auth component and that it is clear for usage?

**Comment by cletter7** [comment]
@bohandley there is an open thread in slack regarding this topic

**Comment by itsmylife** [comment]
We don't need this since we have a task that will update the whole configuration page of InfluxDB https://github.com/grafana/grafana/issues/76996
