### ISSUE TITLE
[Feature Request] Support multiple measurements for InfluxDB queries

### ISSUE THREAD

**Issue by whereisaaron** [grafana/grafana#7396]
Please include this information:
- What Grafana version are you using? **4.02**
- What datasource are you using? **InfluxDB v1.1.1**
- What OS are you running grafana on? **Linux**

InfluxDB supports [selecting multiple measurements per query](https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#example-6-select-all-data-from-more-than-one-measurement), e.g.
```
SELECT * FROM "h2o_feet","h2o_pH"
```
The Grafana query editor kind of appears to support this too, in that if you enter a single quoted, comma separated list, the expected query appears to work fine, but then the results don't appear to get parsed. (Note double quotes do not work, Grafana escapes the double quotes with single quotes in the resulting query.)
```
'default'.'cpu/usage','default'.'memory/usage'
```
My motivation and use case here was to get two columns for two measurements into a standard table panel. I couldn't find anything in the Grafana documents about how to do this, so I was trying to reverse engineer the required query. Am I taking the wrong approach? I tried adding multiple queries to the table panel, but the table panel appears to ignore all but the first query.

**Comment by torkelo** [comment]
you can use a regex to get multiple measurements, just enter `/^(h2o_feet|h2o_pH)/`  in the measurement field

**Comment by whereisaaron** [comment]
Thanks for the tip about the alternative query syntax @torkelo, a very useful trick to know.

That gets results in Grafana, but alas the Table Panel displays duplicate rows, one for each measure. Worse, in this case the fields from both measures are called 'value' so they can't be differentiated in any manner.

Essentially I realize I am asking either InfluxDB or Grafana to do a join between two results, neither of which is capable that, AFAIK. Seems like an extreme feature request too, so I'll leave this closed. Maybe it is something an enhanced Table Panel which multiple query support could tackle one day.

```
> select * from /^(cpu\/limit|memory\/usage)$/ where time > now() - 3m and container_name = 'def-web-backend'
name: cpu/limit
time			container_base_image				container_name	host_id			hostname			labels								namespace_id				namespace_name	nodename			pod_id					pod_name				pod_namespace	type		value
----			--------------------				--------------	-------			--------			------								------------				--------------	--------			------					--------				-------------	----		-----
1485736080000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	10
1485736140000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	10
1485736200000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	10

name: memory/usage
time			container_base_image				container_name	host_id			hostname			labels								namespace_id				namespace_name	nodename			pod_id					pod_name				pod_namespace	type		value
----			--------------------				--------------	-------			--------			------								------------				--------------	--------			------					--------				-------------	----		-----
1485736080000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	1736704
1485736140000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	1736704
1485736200000000000	gcr.io/google_containers/defaultbackend:1.2	def-web-backend	i-00448f2b4390c5950	ip-172-25-128-139.ec2.internal	app:def-web-backend,env:system,pod-template-hash:2955303472	a4cc1958-e368-11e6-b0f6-0e2bdc357a9a	ingress		ip-172-25-128-139.ec2.internal	a5a48bd0-e368-11e6-b0f6-0e2bdc357a9a	def-web-backend-2955303472-1v90f	ingress		pod_container	1736704
```

**Comment by impulsemk** [comment]
+1

**Comment by Gauravshah** [comment]
+1 looking for similar solution on top of druid

**Comment by wyzssw** [comment]
+1  looking for sum two measurements value like
"select sum(value) from /^(h2o_feet|h2o_pH)/ "

**Comment by Gauravshah** [comment]
github.com/GoshPosh/grafana-meta-queries can be used to do that

**Comment by shivam-bidgely** [comment]
+1
