### ISSUE TITLE
Grafana 10.1.0 RPM Packaging Regression on RHEL 9.2

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#73970]
### What happened?

Installed RPM via `sudo dnf install ./grafana-10.1.0-1.x86_64.rpm` and it attempted to install `chckconfig` which is not going to work on a systemd system.

### What did you expect to happen?

Installation without dependencies.

### Did this work before?

Yes, 10.0.3 installed without pulling in `chkconfig`

### How do we reproduce it?

1. On AlmaLinux|Rocky 9: `sudo dnf remove chkconfig` (generally absent on minimal installs)
2. Download and verify the SHA256 checksum for Grafana 10.1.0
3. `sudo dnf install ././grafana-10.1.0-1.x86_64.rpm`

Watch as `chkconfig` is pulled in.

### Environment (with versions)?

Grafana: 10.1.0
OS: AlmaLinux 9.2
Browser: N/A

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by kminehart** [comment]
ah you're absolutely right. This will be fixed in the next patch release some time this week. Thanks for the report!

**Comment by kminehart** [comment]
This should be resolved with the 10.1.1 rpm package.

```
wget https://dl.grafana.com/oss/release/grafana-10.1.1-1.x86_64.rpm && rpm -qpR grafana-10.1.1-1.x86_64.rpm
warning: grafana-10.1.1-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 10458545: NOKEY
/bin/sh
/bin/sh
/sbin/service
fontconfig
freetype
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
urw-fonts
```

**Comment by kminehart** [comment]
Please let me know if you continue to have issues. Thanks!

**Comment by reyjrar** [comment]
Awesome! Thanks! :)
