### ISSUE TITLE
[Feature request] Third Y Axis

### ISSUE THREAD

**Issue by parkesy** [grafana/grafana#7397]
Grafana version: 4.0.1
Datasource: InfluxDB
OS: Ubuntu16.04
What did you do? I select a time series to override and plot against a third Y axis.
What did I expect to happen? I'd be able to plot the time series over a third Y axis.
What happened? There is a limit of 1 and 2 Y axis options.

**Comment by coussej** [comment]
Maybe this feature request should be renamed to 'Multiple Y axis? Wouldn't it be more relevant to implement the possibility to add as much axis as one wants?

**Comment by thaddeusmt** [comment]
I found this closed issue via Google, which people are still commenting on, so I'll link it here: #1893 

This would be a very helpful feature. We are graphing volume and revenue and average order value, and 3 Y-axis scales is necessary for it to be useful and look correct.

**Comment by Orfait** [comment]
+1 for this feature request

**Comment by clowrey** [comment]
+ 1

**Comment by Aqueum** [comment]
+1 for multiple y axis

**Comment by anirudh-ramesh** [comment]
+1

Absolutely essential for plots of different units and scales e.g. voltage/current/temperature over time on one panel.

**Comment by EvgenyG1** [comment]
+1

**Comment by dmitry-ee** [comment]
sure, +1

**Comment by lfroment0** [comment]
+1

**Comment by PackElend** [comment]
+1

**Comment by MarkusBe** [comment]
I am also looking forward to see this feature in the nearer future! 
+1

**Comment by nelgi** [comment]
I'd love to have multiple Y-axes as well, essential to be able to show BME280 (temp, humidity, pressure) or BME680 (temp, humidity, pressure, air quality) data on a single graph.

**Comment by MaxPowderson** [comment]
this would be such a useful feature - especially for industrial applications!!!!
+1

**Comment by Crashtein** [comment]
Me too! I wonder why it is still not implemented! I would truly appreciate this option.

**Comment by jwblaney** [comment]
+1

**Comment by veesahni** [comment]
+1

We have many services, each with their own dedicated dashboards.  It would be nice for our "Home" dashboard to have 1 chart per service, graphing a handful of key metrics each with their own scale.   The goal here is to provide a quick visual that a human could use to say "something is not right on this one" and use that as a starting point to dig deeper.

**Comment by YoannCollinSubiron** [comment]
Hi! +1
I am wondering if as a first step we could add a "multiple scales" option where all the scales of each queries are in auto mode.  I would recommand for the first version just hide the scales, show option to OFF because as describe in the comments we want to the visualize differente metrics, indicators or sensors.
![image](https://user-images.githubusercontent.com/34068335/73196230-8e023880-412f-11ea-96ae-6bfda50059eb.png)

**Comment by towingie** [comment]
+1

**Comment by UBehrens** [comment]
I believe, having multiple Y-Axes would be a very useful feature. Personally, I see many advantages here, although I also understand the challenges in building a proper user interface (creating an easy-to-understand binding between different curves and scales, and always being able for the user to switch the context). GUI-design is always hard, but I really like the idea!

**Comment by Fragggy** [comment]
+1 I also need this.

**Comment by pls68** [comment]
+1 this would be very useful

**Comment by TomasVojacek** [comment]
+1 this would be very useful

**Comment by sergiodegrazia** [comment]
+1 please make this happen

**Comment by fraxinas** [comment]
+1 for multiple y-axes

**Comment by no-nerd** [comment]
+1 important feature

**Comment by DENSarjan** [comment]
+1 i would use this a lot

**Comment by frogale** [comment]
+1 very important.. humidity, temperature, linkquality, voltage etc.. it could be on single graph..

**Comment by borlaugen** [comment]
+1 This would make Grafana a more usefull tool for the IoT industry

**Comment by mpw-eng** [comment]
+1 IoT and process control often requires various signals with different engineering units to be plotted on the same chart, e.g. Steam Pressure (0-20 MPa), Steam Temperature (0-600 DegC), Turbine Speed (0 - 4000 rpm).  With only two y-axis scales, I need another chart to clearly plot one of these three variables.

**Comment by thomkedc** [comment]
+1

**Comment by louloizides** [comment]
+1
It'd be nice to add as many axes as possible. They don't have to be on both sides of the plot either, it's perfectly acceptable to have multiple scales on the same side of the plot.

**Comment by madamak** [comment]
+1
As many axes as possible indeed!

**Comment by xyReaper** [comment]
+1 Please and thank you.

**Comment by lkerck** [comment]
+1

**Comment by HogeBlekker** [comment]
Would Grafana be willing to accept a pull request for this functionality into the (new) standard graph panel?

If so, how would this fit in the migration to React-based [graphs](https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/graph2) and the experiments with [uPlot](https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/graph3)?

Most SCADA systems make this possible with multiple Y-axes, each with a distinct color and mostly on the left side but can be both, with each trend having the same color as the corresponding Y-axis. Each y-axis has its own UoM and scaling. An example included, copy pasted from https://community.grafana.com/t/custom-graph-panel-zooming-behaviour-for-rest-of-dashboard/33834/5

![image](https://user-images.githubusercontent.com/1174064/99989901-762d2c80-2db3-11eb-97df-c37ec1a24e73.png)

**Comment by leeoniya** [comment]
Status update for everyone waiting on this feature:

This is something which will be available in the new uPlot-based graph panel, but not immediately. Our priority is to first reach feature parity with the current Flot-based panel, and we're making steady progress towards this. The timeline will become more clear once the new panel has been run through its paces.

This is definitely on the roadmap; my current best guesstimate is "months, not years".

Stay tuned!

**Comment by Matthias-O** [comment]
+1, multiple (not limited) y-axis would be extremely helpful!
Are there any plugins which make multiple y-axis yet possible?

**Comment by dominic-miglar** [comment]
> Status update for everyone waiting on this feature:
> 
> This is something which will be available in the new uPlot-based graph panel, but not immediately. Our priority is to first reach feature parity with the current Flot-based panel, and we're making steady progress towards this. The timeline will become more clear once the new panel has been run through its paces.
> 
> This is definitely on the roadmap; my current best guesstimate is "months, not years".
> 
> Stay tuned!

Nice 💪 , looking forward to a beta-test version 😎

**Comment by psmgeelen** [comment]
+1

**Comment by ryantxu** [comment]
This is not supported in our new timeseries panel that will be released in 7.4 -- each unique unit gets its own axis.  See also #1893

**Comment by castillo92** [comment]
> This is now supported in our new timeseries panel that will be released in 7.4 -- each unique unit gets its own axis. See also #1893
> 
> ![image](https://user-images.githubusercontent.com/705951/104382734-81fbbc00-54e3-11eb-9d66-ed5ebcb6685b.png)

Thanks you, it is important that no matter size, different query, override the metric with different position.... The way to separate into two axis is different unit

**Comment by adamkdean** [comment]
> This is now supported in our new timeseries panel that will be released in 7.4 -- each unique unit gets its own axis. See also #1893

Is it possible to do this when two units are the same? The old graphs allowed the separation of scales, with smaller values on one Y-axis, and larger values on the other Y-axis, stopping smaller values from being squashed.

**Comment by psmgeelen** [comment]
Should work, yet you would still end up with additional axis to accommodate for the different ranges.

**Comment by adamkdean** [comment]
> Should work, yet you would still end up with additional axis to accommodate for the different ranges.

How would one go above configuring a separate axis without a different unit? The only way so far I've been able to do it is by changing the unit but when the units are the same they appear on the same axis. Thanks

**Comment by leeoniya** [comment]
are you using 8.3.0+ ? this was only added back recently https://github.com/grafana/grafana/pull/41635

**Comment by adamkdean** [comment]
Ah, that'll do it, I'm a couple of minors behind. Thanks @leeoniya!
