### ISSUE TITLE
Geomap: unwanted "1" in tooltip in v10.1.0 after migration from v9.5.1

### ISSUE THREAD

**Issue by vsile** [grafana/grafana#73976]
### What happened?

In v9.5.1 the tooltip of GeoJSON layer was correct.
![изображение](https://github.com/grafana/grafana/assets/9244347/a3487309-02b8-476f-bc39-3cb9871fe9a5)

In v10.1.0 the tooltip has unwanted "1" next to properties fields.
![изображение](https://github.com/grafana/grafana/assets/9244347/a40672e1-c14c-4fdc-aca4-01616762db6f)

### What did you expect to happen?

The fields in tooltip box should not contain unwanted symbols "1"

### Did this work before?

There is no issue in v9.5.1

### How do we reproduce it?

Just go to play.grafana.org -> [Panel Tests - Geomap](https://play.grafana.org/d/panel-geomap/panel-tests-geomap).

You can also create the simple CSV content

foo,bar,lat,lon,data
hello,world,35.687,-105.938,"TEST"

![изображение](https://github.com/grafana/grafana/assets/9244347/ac7394ed-ace4-4069-a7db-44374df779f7)

**Comment by tonypowa** [comment]
thank you for opening this issue

i have reproduced it in v10.2.0 on Firefox 116.0.3

![image](https://github.com/grafana/grafana/assets/45235678/0a8ffcc7-a2c8-44ee-94b8-425cd4fd25d1)
![image](https://github.com/grafana/grafana/assets/45235678/c425c16f-ec48-46e8-8f3c-b07458af30c3)

Adding the issue to the dataviz squad's board

**Comment by jzgrzebnicki** [comment]
same on v10.0.2

**Comment by nmarrs** [comment]
Hi @vsile - thank you for reporting this regression! We have confirmed this issue and will address it for v10.2 (most likely with a backport for v10.1.x)
