### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node' in Grafana v.9.4.3 on Microsoft Edge

### ISSUE THREAD

**Issue by canogretic** [grafana/grafana#73982]
### What happened?

Hi, we have a problem with the display of a State Timeline Chart in Microsoft Edge.

If the translation of the website is active, after a short time (chart is already displayed), this error appears:

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

As a workaround we can disable the translation on the page, then everything seems to work so far.

### What did you expect to happen?

I did not expect any error due to translations

### Did this work before?

I don't know.

### How do we reproduce it?

1. Open Dashboard with State Timeline Chart without any translation
2. Enable Edge Translation to German
3. Refresh Dashboard or load it again and aftzer a short time the error occur

### Is the bug inside a dashboard panel?

yes we see it only in State Timeline Chart. Another Pie Chart works

### Environment (with versions)?

Grafana: v.9.4.3
OS: Windows 11
Browser: Microsoft Edge Version 116.0.1938.62

### Grafana platform?

Docker

### Datasource(s)?

MySql

**Comment by tonypowa** [comment]
hi @canogretic 

Thank you for creating this issue

I have tried to reproduce the error in previous and later versions of Grafana than 9..4.3 but I wasn't successful 
I also have used the latest Edge Version 116.0.1938.62 (Official build) (64-bit)

Could you please try to reproduce it in [grafana play](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) ?
Also could you record your screen as you reproduce the error?

**Comment by canogretic** [comment]
Hi @tonypowa,

I can reproduce it with this Chart 

[grafana play](https://play.grafana.org/d/iZ5dkx3Mz/state-timeline22?orgId=1)

To reproduce it you must activate the translation of the Microsoft Edge Browser to some english different language.

If you start the debug Console the translator starts with the message "Edge Translation started".
After a short time on chart loading the DOMException message comes to the Debug Console.

**Comment by tonypowa** [comment]
Yep, you are correct. I immediately got the error when reproducing the error on play . Nice!
![image](https://github.com/grafana/grafana/assets/45235678/8f92555b-c4d9-48e4-ba85-457507df1cbf)

I will add this to the engineering team's board for review

thank you

**Comment by canogretic** [comment]
Thanks for the quick reply. It seems only the Edge browser is affected. 

With the Chrome browser and the translation, the view seems to work so far.
