### ISSUE TITLE
Dashboard variable interpolation for service graph panel when navigating to Explore

### ISSUE THREAD

**Issue by zalegrala** [grafana/grafana#74015]
**Why is this needed**:

User is using dashboard variables for data source and service name in Service Graph. Clicking the kebab menu and choose to view the panel in Explore fails to work correctly because the dashboard variables are not being interpolated.

**What would you like to be added**:

When navigating from a dashboard with variables to explore, users would like the currently selected dashboard variables to be interpolated into the explore query.

When using no variables, viewing the panel in Explore works just fine. If using service name variable, it pre-selects service graph tab but does not interpolate the variable. If using a variable for the datasource, it doesn't even pre-select the service graph correctly, it defaults to Search.

**Who is this feature for?**

Users of Service Graph, but potentially other areas of Grafana.

**Comment by 09jvilla** [comment]
Note the issue seems to specifically be with the service graph panel and variables. If I'm using a table panel that uses a tempo variable and then click explore, it works fine.

**Comment by 09jvilla** [comment]
We can debate about this if we want but I would think this is more of a bug than a feature request? I would expect the ability to go from a service graph panel to a pre-populated explore view to work since it works for other panel types.

**Comment by 09jvilla** [comment]
^The above is a video demonstrating the issue.

**Comment by joey-grafana** [comment]
Note the behaviour in the video above was present in Grafana v10.2.2 wherein if you have a datasource variable configured and used and a service graph template variable that is not interpolated then you get taken to the TraceQL tab and not the Service graph tab (when you click explore from a dashboard panel that is set to the Service graph tab).

The above behaviour is not seen in the latest version of Grafana main (v10.3.0-pre (4ed6e8e037)). In this version even with the above missing service graph template interpolation and datasource variable set, you are still taken to the correct tab i.e. Service graph (when you click explore from a dashboard panel that is set to the Service graph tab).

The fix PR linked to this issue fixes the variable interpolation for the service graph only (but overall the scenario expressed in this issue appears to be fixed too). It looks like the issue mentioned above in this comment has been fixed sometime between 10.2.2 & v10.3.0-pre (4ed6e8e037).

**Comment by 09jvilla** [comment]
Got it - thanks Joey. So it sounds like I should expect everything to work upon upgrade to Grafana v10.3? 

Namely: 
- jumping to service graph in explore from a panel that has a datasource variable should work
- jumping to service graph in explore from a panel that has a datasource variable and a tempo dashboard variable should work

Is that right?

**Comment by joey-grafana** [comment]
No problem. I've been testing with the latest main and both of those scenarios are working :)

**Comment by 09jvilla** [comment]
Awesome!

**Comment by 09jvilla** [comment]
That means I would expect that when 10.3 goes out, both those scenarios will work (since right now the latest release is 10.2.2, so anything that's gone in since then I would expect to land in 10.3).
