### ISSUE TITLE
[Bug] Custom builded release package (Debian) won't start

### ISSUE THREAD

**Issue by dvotion** [grafana/grafana#7403]
I'm trying to make a custom Debian release package build. I'm planning to do some development, but first want to make sure I can build and release it. Building the frontend and backend goes fine, the same goes for the build process of the package. When I run the grafana locally on my mac it also runs fine.

Then when I install the custom pkg in Debian (Docker) and try to start the Grafana server it fails. Unfortunately I also get no error logs, so it's hard to pinpoint what is wrong with the release build.

I'm not sure if it's a bug or something I'm doing wrong.

The steps I'm doing are
- go run build.go build
- go run build.go build package

Thanks for pointing me in the right direction

**Comment by torkelo** [comment]
go run build.go build package

this gets you a .deb package in dist folder which you install using `dpkg -i ` I presume? 

how are you starting grafana? Any logs in `/var/log/grafana`?

**Comment by dvotion** [comment]
Yes, that's right, I'm installing it with dpkg.

I start grafana with service grafana-server start and no logs in the /va/log directory. Of course tried to modify the ini file, but it ignores the logfile. Any other routes in getting the right log information so I can see why Grafana isn't starting?

**Comment by torkelo** [comment]
Try starting grafana-server binary with 

`--pidfile=${PID_FILE} --config=${CONF_FILE} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.plugins=${PLUGINS_DIR}`


as the grafana user

**Comment by torkelo** [comment]
those parameters needs to correct of course (and not env variables)

**Comment by dvotion** [comment]
When I run 
/usr/sbin/grafana-server
It complains about: cannot execute binary file: Exec format error

**Comment by dvotion** [comment]
Thanks for helping btw :)

**Comment by torkelo** [comment]
That usually indicates your binary is not correct for the OS (for example 64bit on 32bit OS)

**Comment by dvotion** [comment]
Ok, that's weird, because I use the exact same (Debian) version when building the Docker image. I only change to Grafana pkg install location. In both situations I use the amd 64bit version. 

Could it be that when custom building the created filename says ...amd64bit but the buildprocess did a 32 bit build somehow?

**Comment by torkelo** [comment]
maybe. 

This is the docker container we use when building the official packages:
https://github.com/grafana/grafana-packer/blob/master/Dockerfile

**Comment by dvotion** [comment]
Here is my dockerfile

`RUN \
    apt-get update && apt-get -y install \
        adduser \
        ca-certificates \
        sudo \
        curl \
        wget \
        supervisor \
        apt-transport-https \
        libfontconfig && \
    apt-get clean

RUN \
    wget https://grafanarel.s3.amazonaws.com/builds/grafana_3.1.1-1470047149_amd64.deb && \
    sudo dpkg -i grafana_3.1.1-1470047149_amd64.deb

RUN \
    echo "deb https://packagecloud.io/grafana/stable/debian/ wheezy main" >> /etc/apt/sources.list

RUN \
    curl https://packagecloud.io/gpg.key | sudo apt-key add -

RUN \
    sudo apt-get update && \
    sudo apt-get install grafana && \
    sudo update-rc.d grafana-server defaults 95 10


EXPOSE 3000

CMD service grafana-server start && supervisord -n

ENV TZ=Europe/Amsterdam
ENV DOCKER_IMAGE_VERSION=0.1`

**Comment by dvotion** [comment]
Why did you close it? Looks like when running the buildprocess something is going wrong in the Grafana buildprocess

**Comment by torkelo** [comment]
because it must be something wrong with your docker container. 

Does this build work? 
https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana_4.2.0-1485770110pre1_amd64.deb

**Comment by torkelo** [comment]
it was built from our new built process today, https://github.com/grafana/grafana/tree/master/scripts/build

**Comment by dvotion** [comment]
Hi Torkel,
Nope, that build gives the following error when creating the Docker image

`Preparing to unpack grafana_4.2.0-1485770110pre1_amd64.deb ...
Unpacking grafana (4.2.0-1485770110pre1) ...
Setting up grafana (4.2.0-1485770110pre1) ...
Adding system user `grafana' (UID 106) ...
Adding new user `grafana' (UID 106) with group `grafana' ...
Not creating home directory `/usr/share/grafana'.
Failed to connect to bus: No such file or directory
dpkg: error processing package grafana (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu7) ...
Errors were encountered while processing:
 grafana
The command '/bin/sh -c wget https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana_4.2.0-1485770110pre1_amd64.deb &&     sudo dpkg -i grafana_4.2.0-1485770110pre1_amd64.deb' returned a non-zero code: 1`

**Comment by dvotion** [comment]
Also checked the system, but it's certainly 64bit. I'm using the phusion/baseimage for the docker image.

So when using the *.deb production build everything goes fine. But when trying using a non-production build (yours and also my local one) it errors running the grafana-server.

**Comment by torkelo** [comment]
managed to find the issue in the deb post install script when installing in docker container

**Comment by dvotion** [comment]
Ah, cool! Will try it later today or tomorrow morning

**Comment by dvotion** [comment]
Just did a new build and created a new container, but still the same issue :(

**Comment by torkelo** [comment]
Do you have the install log?

**Comment by dvotion** [comment]
Do you mean the console output of building the .deb file or the console output of the docker build or ....

**Comment by torkelo** [comment]
the file output of dpkg install

**Comment by torkelo** [comment]
I mean the output of the dpkg installation

**Comment by torkelo** [comment]
looking at your Docker file it looks like you install grafana twice. 

That means the package upgrade code will run. please set RESTART_ON_UPGRADE in /etc/default/grafana-server to false or make sure you run docker so that systemd is available

**Comment by dvotion** [comment]
Yes, I also noticed monday, that second install row is already gone. Also tried to install it using a modified clone of your Docker build scripts. Nonetheless, just created a docker image without the Grafana installation, only copied in the .deb file. Then I logged in to the running container and did the install, below you can see the output. 

![image](https://cloud.githubusercontent.com/assets/16036341/22494932/2a3cb7de-e83c-11e6-85d6-0e1246ea921a.png)

**Comment by torkelo** [comment]
is it you typing `sudo /bin/systemctl start grafana-server` ? 

If you want to use systemd inside a docker container then you have to go through some hoops (lots on google on this, search if you really want to use systemd inside the container). 

The official docker container starts grafana using this:
https://github.com/grafana/grafana-docker/blob/master/run.sh

**Comment by dvotion** [comment]
Yes I typed it to show you the response as the output instructed to start the server that way. In the working Docker situation we just start the server with service grafana-server start which works fine. 

From my perspective the issue isn't related to anything outside Grafana (like systemd, Docker, etc) because when using a production .deb build from Grafana (v3) everything goes fine. The problems start when targeting a custom builded deb file (used in exact the same Docker setup).

**Comment by torkelo** [comment]
Everything is working fine in the official docker container, with custom built packages. If you want to use systemd inside the container you need to follow guides for how to do that. Its outside the scope here, we can't support custom docker setups. 


`sudo /bin/systemctl start grafana-server ` wont work for v3 either, as the error you get is related to systemd

**Comment by dvotion** [comment]
You can try it by doing the following:
- I used the Phusion Base image and then the following docker items in the Dockerfile to create the image
- After creating the image, start the container en loging using docker exec
- Then run command shown in screenshot

Dockerfile:

`RUN \
    apt-get update && apt-get -y install \
        adduser \
        ca-certificates \
        sudo \
        curl \
        wget \
        supervisor \
        apt-transport-https \
        libfontconfig && \
    apt-get clean

COPY \
    grafana_4.2.0-1485877776pre1_amd64.deb /

RUN \
    echo "deb https://packagecloud.io/grafana/stable/debian/ wheezy main" >> /etc/apt/sources.list

RUN \
    curl https://packagecloud.io/gpg.key | sudo apt-key add -


EXPOSE 3000

CMD supervisord -n

ENV TZ=Europe/Amsterdam
ENV DOCKER_IMAGE_VERSION=0.5`

**Comment by torkelo** [comment]
Hm.. why adding the package repository when copy over the file? Not seeing that you install the package nor how you start grafana.

**Comment by dvotion** [comment]
I did the install & starting manually to show you the log, in the screenshot of the console you see me typing dpkg.....

**Comment by dvotion** [comment]
Package repo is some leftover I forgot to get rid of in the test and not related, originally fetching from repo that's why it's still there but of course is unneeded

**Comment by torkelo** [comment]
> I did the install & starting manually to show you the log, in the screenshot of the console you see me typing dpkg.....

yes I saw you starting it manually using systemd inside a docker container. Did you start the container in such a way so that systemd is available? It is very tricky (not commonly not recommended).

Please us the run script from the official docker container.

**Comment by dvotion** [comment]
I start it with "service grafana-server start"

**Comment by torkelo** [comment]
yes, that is using systemd / initd (depending on linux version) and is tricky to use inside docker container which is why most docker container uses custom launch scripts.

**Comment by dvotion** [comment]
Ok, will try it (again)
But why is this working fine with the production build?

**Comment by torkelo** [comment]
it isnt for me. same systemd error

**Comment by dvotion** [comment]
Ok. We have it running in production (Awesome dashboard btw :)
Going to try it the other way and let you know

**Comment by dvotion** [comment]
Allright, still no luck :(

I created a new Dockerfile based on the Grafana Dockerfile, only difference is that I copy the local .deb file in and install that one. The run.sh is in the same directory and an exact copy of https://github.com/grafana/grafana-docker/blob/master/run.sh

 When starting the docker container I get the error: 
"error: exec failed: exec format error"

**Docker file:**
`FROM debian:jessie

RUN \
    apt-get update && apt-get -y --no-install-recommends install \
        libfontconfig \
        curl \
        ca-certificates && \
        apt-get clean

COPY \
    grafana_4.2.0-1485877776pre1_amd64.deb /tmp/grafana.deb

RUN \
    dpkg -i /tmp/grafana.deb && \
    rm /tmp/grafana.deb && \
    curl -L https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64 > /usr/sbin/gosu && \
    chmod +x /usr/sbin/gosu && \
    apt-get remove -y curl && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"]

EXPOSE 3000

COPY ./run.sh /run.sh

RUN chmod +x /run.sh

ENTRYPOINT ["/run.sh"]

ENV TZ=Europe/Amsterdam
ENV DOCKER_IMAGE_VERSION=0.5`

**Comment by torkelo** [comment]
strange, some other error now, your binary must be corrupt :( no idea why

**Comment by dvotion** [comment]
I think it's the problem all the time and those other messages just distractions from the core of the issue.

**Comment by dvotion** [comment]
Any ideas how we can work around this? Really like to start developing, but unsure if this is the right path

**Comment by torkelo** [comment]
Try building inside the container, as the binary you build is not compatible with the OS inside the container

**Comment by dvotion** [comment]
On which platform do you build the releases? Somehow there it does work.

With binary, you specifically mean the grafana-server right? Maybe overwrite the binary with a production build after installing it in the container is also a way? I'm mainly focussing on adding functionalities to the frontend.

Building in the Docker needs a complete go installation with everything needed there, that way, you don't need to build anymore because you just can start the server within the container bypassing the need for a deb file. The whole purpose of building that deb file is to make installs easier right?

**Comment by torkelo** [comment]
What os are you building on now? (os and kernel)

**Comment by torkelo** [comment]
And glibc version, that can be important for binary compatibility between Linux versions

**Comment by torkelo** [comment]
That is why we build release packages in centos 6 for maximum binary compatibility with different Linux versions and distros

**Comment by dvotion** [comment]
I'm doing the builds on MacOs Sierra

**Comment by torkelo** [comment]
@dvotion ok, last time I checked binaries built on Mac won't work on Linux. Just a heads up :) that is why you get exec error as your mac binaries only work on mac. The container you try to run it in runs on linux.

**Comment by dvotion** [comment]
Alright, approached it from another direction and I have a working fork running in Docker. I created a new Docker image, installed Go, Node, Git, Clone, etc and made it working. Creating the image with the deb file is nicer, but this works. 

Thanks for helping! Maybe a good idea to update the docs with some notes about creating those builds.

**Comment by torkelo** [comment]
yea, maybe good to point out that mac binaries are not linux compatible
