### ISSUE TITLE
[Feature request] Document POST /api/alerts/test endpoint

### ISSUE THREAD

**Issue by augi** [grafana/grafana#7405]
I can see that Grafana UI uses `POST /api/alerts/test` endpoint when clicking on `Test Rule` button when editing alert.

I would like to use this endpoint but I'm not sure what are required inputs ([source here](https://github.com/grafana/grafana/blob/master/pkg/api/alerting.go#L105)).

It would be nice if the only required inputs were `orgId`, `dashboardId` and `panelId` only.

**Comment by torkelo** [comment]
you can see how the frontend use that api endpoint. It is not really easy to use outside from a dashboard as you need to pass in the dashboard as well as you can test rules that have yet to be persisted.
