### ISSUE TITLE
[Feature Request] Select text

### ISSUE THREAD

**Issue by medberry** [grafana/grafana#7407]
In many views of grafana, the ability to select a specific "label" for a graph line would be handy (to feed that into some other sort of query system, ie, find out more about it OUTSIDE of Grafana for instance) but I see no way to do that. 

https://www.dropbox.com/s/vfvedaugmjvw709/Screenshot%202017-01-30%2010.24.41.png?dl=0

In that link (or the attached snapshot), I'd like to be able to select the text of:
4a20cf.... so that I can pass it into a keystone (OpenStack) query.

**Comment by medberry** [comment]
![screenshot 2017-01-30 10 24 41](https://cloud.githubusercontent.com/assets/4364740/22433762/b96eb4c8-e6d6-11e6-9fe8-9dffda827fb4.png)

**Comment by torkelo** [comment]
This is due to drag and drop of panels (which disables select-ability in browsers), https://github.com/grafana/grafana/issues/2083 

There a small (not great) workaround you can do and that is enter view/edit mode, then drag and drop panel is disabled and you can select text
