### ISSUE TITLE
[Bug] Panel missing sensors after upgrade to 4.1.1

### ISSUE THREAD

**Issue by liquidox** [grafana/grafana#7408]
After upgrading InfluxDB and Grafana to the latest versions, one of my panels seems to suddenly be restricted to showing 7 sensors instead of the usual 9 I had visible.

Shown clearly here:
https://i.imgur.com/dtkFWGd.png

Running on CentOS 7:
influxdb.x86_64                         1.2.0-1                  @influxdb
grafana.x86_64                          4.1.1-1484211277         @grafana

**Comment by torkelo** [comment]
Probably an issue with InfluxDB. Have you checked the response from InfluxDB? (open chrome dev tools network tab and inspect the response from your query). Is all 9 series returned from InfluxDB?

**Comment by liquidox** [comment]
This does not look like an InfluxDB issue at all. First of all, if I change the order of sensors, it still shows the first 7 only. The data is clearly there.

Furthermore, I now noticed that I can make the others appears by changing the graph size. For example, making it less wide, and the full set of sensors may appear. Stretching it wider, boom they disappear. Really quite buggy.

**Comment by torkelo** [comment]
No, it's an issue with your query.  The group by time interval changes (if you have auto inferval) so your query must be dependent on group by time interval

**Comment by liquidox** [comment]
You're right that it appears sensors disappear/appear based on time range, thanks for that tip! However, seems arbitrary, why does it ever only hide whichever sensors happens to be lowest in the sensor order?

And why does it behave like this?

Time range override setting:
36h, all sensors show
24h, only top 7 show
18h, all show
12h, only top 7
3h, all show
2h, only top 7

And why was this never a problem before Grafana 4.1.1? Been using the older version without problem for months.

**Comment by torkelo** [comment]
Maybe a change in how InfluxDB works? 1.2 has a ton of changes, some breaking changes. 
https://github.com/grafana/grafana/issues/7380 

Maybe set max-row-limit to zero?
influxdata/influxdb#7879

**Comment by liquidox** [comment]
This appears to be the fix for this problem, thanks so much!
