### ISSUE TITLE
[Bug] Adding an alert to a Graph Panel with 'Group by time interval' lower limit (e.g. '>60s') and group by 'time($interval)' corrupts panel

### ISSUE THREAD

**Issue by whereisaaron** [grafana/grafana#7409]
- What Grafana version are you using? **4.02**
- What datasource are you using? **InfluxDB**
- What OS are you running grafana on? **Linux**
- What did you do? **Added an Alert to a Graph Panel**
- What was the expected result? **Graph Panel with Alert**
- What happened instead? **Broken Graph Panel, Deleting the Alert again does not fix it**

Adding an Alert to some Graph Panels will irrevocably breaks the graph. Deleting the alert still leaves the corrupted state. The affects at least Graph Panels with group by `time($interval)` and a 'Group by time interval' lower limit, e.g. `>60s`.

**Steps to recreate:**
1. Add a Graph Panel with work query, set the 'Group by time interval' to e.g. '>60s', and ensure the query has a group by `time($interval)`
2. Observe Graph is working and displaying data
3. Export the JSON of the working panel for comparision
4. Add any Alert to the panel and Save the Dashboard
5. Observe Graph is failing with error like:
```
"error": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 116",
```
due to `group by time(>60s)` in the query:
```
SELECT mean("value") * 100 FROM "cpu/node_utilization" WHERE "type" = 'node' AND time > now() - 30m GROUP BY time(>60s), "nodename" fill(linear)
```
6. Delete the Alert and Save the Dashboard
7. Observe that the Graph is still failing with the same error
8. Export the JSON and diff with the JSON from step 3, note that the only difference is the version number and that `"interval": ">60s"` has been injected into the `targets` section.
```
--- 1713,1723 ----
                      "linear"
                    ],
                    "type": "fill"
                  }
                ],
+               "interval": ">60s",
                "measurement": "cpu/node_utilization",
                "policy": "default",
                "refId": "A",
                "resultFormat": "time_series",
                "select": [
***************
```
9) At this stage there appears no way to fix the chart (from the UI), you can delete the group by `time($interval)` and the graph will display, but if you add it back again it will break again.

**Comment by torkelo** [comment]
This is fixed in master and latest 4.2 builds (try nightly build) 
https://github.com/grafana/grafana/issues/6765
