### ISSUE TITLE
[Feature request] Variable threshold values in Singlestats panel

### ISSUE THREAD

**Issue by fredrik84** [grafana/grafana#7411]
Hi,
Would be nice to be able to create variables with dynamic latest values of a metric.
I see most use for thresholding in singlestats panel, where dynamic thresholds or gauges could be used based on a "total" metric as roof or a calculation (variable minus X) for thresholding.

**Comment by tehdirector** [comment]
I would love to see the ability to make the threshold populate based on a query or static value. Specifically for the gauge display, when my data is dynamic setting a static threshold doesn't always work.

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.

**Comment by lingjingwei** [comment]
动态阈值的问题一直没人解决吗？

**Comment by bmfmsd** [comment]
+1

**Comment by Gammenon** [comment]
+1

**Comment by gcezaralmeida** [comment]
+1
