### ISSUE TITLE
[Bug] Chart with points (5min) becoming line (60min)

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#7412]
A point should be displayed as a point (otherwise you would choose for a line) regardless of the 'zoom' level. 

So i guess, they should be drawn related to the 'zoom' level. Maybe skip

CentOS release 6.8 (Final)
grafana-4.1.1-1484211277.x86_64

5min view
![5-min](https://cloud.githubusercontent.com/assets/13450219/22457921/6b044ce8-e79a-11e6-8071-c6c288646fdd.png)

30min view
![30-min](https://cloud.githubusercontent.com/assets/13450219/22457925/6eb78544-e79a-11e6-9150-c31bf0effb36.png)

60min view
![60-min](https://cloud.githubusercontent.com/assets/13450219/22457929/712b9c02-e79a-11e6-95b0-bd9bd2a48375.png)

**Comment by torkelo** [comment]
welcome to physics 101, points close together form a line when looked from afar.

**Comment by torkelo** [comment]
Sorry, just not sure what you expect grafana to do. each metric point is drawn as a point here. If you want to still get dots you need to increase your group by time (decrease number of data points) when you zoom out

**Comment by f1-outsourcing** [comment]
You are indeed a physics genius! Now I will not have to worry about your applied logics knowledge.

Grafana is a charting tool. So if users choose it draw points, they expect it draw points (and thus expect grafana to take into account, when indeed points become a line). 

As suggested

> So i guess, they should be drawn related to the 'zoom' level.

Skip plotting points in between, maybe add graph variable with % of the chart width?

I do not think it is nice to resolve this in the metrics area (if that is what you indicate). I also dont know to much of Grafana to judge if this is the best way to resolve this. 
I thought it is related to how your data is displayed and thus, I would choose something where eg. "Points Radius" is given. On the other hand, skipping data to be displayed, is also not nice for a chart, but then again, a user can decide if he wants to use this option or not. And you also have this issue where you have 200 samples to be displayed on a 100px chart width.
