### ISSUE TITLE
Datasource Rest API - Can't update custom header values

### ISSUE THREAD

**Issue by ryanshaut** [grafana/grafana#74121]
### What happened?

I created a data source manually and created 2 custom http headers. Then I tried to update the value of both headers from the API, but the data source does not get updated. 

Calling PUT /api/datasources/uid/$dashboardUID with this payload should update the value of the custom headers configured on the data source.

```
{
  "id": 16,
  "uid": "b8a11687-2cd4-4f1c-b971-1feeed9b8972",
  "orgId": 1,
  "name": "Test-GraphQL",
  "type": "fifemon-graphql-datasource",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://redacted:8000",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "httpHeaderName1": "Authorization",
    "httpHeaderName2": "X-Auth-Last-Updated"
  },
  "secureJsonFields": {
    "httpHeaderValue1": "Bearer $secretToken",
    "httpHeaderValue2": "2023-08-29T11:39:20Z"
  },
  "version": 121,
  "readOnly": false
}

```

### What did you expect to happen?

secureJsonFields are updated with the values provided. Instead the values are not updated in Grafana.

### Did this work before?

Unknown

### How do we reproduce it?

I'm running Grafana in docker, so adjust your URL as needed

1. Create a new data source of type InfluxDB, Prometheus, or GraphQL Data Source. It's possible others are impacted too, but I only tested these 3
2. Set the URL to http://host.docker.internal:8000
3. Add Custom header called Authorization with a random value ("abc123")
4. Run a HTTP server locally so that you can see the request sent from Grafana
```
#/usr/bin/python3
from http.server import BaseHTTPRequestHandler, HTTPServer

class MyRequestHandler(BaseHTTPRequestHandler):
  def do_GET(self):
    print(self.headers)
    self.send_response(200)
    self.end_headers() 
  def do_POST(self):
    print(self.headers)
    self.send_response(200)
    self.end_headers() 

httpd = HTTPServer(('127.0.0.1', 8000), MyRequestHandler)
try:
  httpd.serve_forever()
except KeyboardInterrupt:
  print('Goodbye.')
5. Back in Grafana, Click Save and Test. In the console where the http server is running, you can see that the Authorization header is sent with the value you provided.
```

![image](https://github.com/grafana/grafana/assets/4265693/1512a075-d96b-4066-9091-f45f80869f5f)

```
7. Call the Grafana API to update the data source (Need to update fields as needed for your environment). Response should be 200 OK
8. 
PUT /api/datasources/uid/b8a11687-2cd4-4f1c-b971-1feeed9b8972
{
  "id": 16,
  "uid": "b8a11687-2cd4-4f1c-b971-1feeed9b8972",
  "orgId": 1,
  "name": "Wiz",
  "type": "fifemon-graphql-datasource",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://host.docker.internal:8000",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "httpHeaderName1": "Authorization",
    "httpHeaderName2": "X-Auth-Last-Updated"
  },
  "secureJsonFields": {
    "httpHeaderValue1": "Bearer secretToken",
    "httpHeaderValue2": "2023-08-29T11:39:20Z"
  },
  "version": 121,
  "readOnly": false
}

9. Refresh the data source page in Grafana and run Save and Test again. In the http server, you'll see the original Authorization value, not the updated value. 

### Is the bug inside a dashboard panel?

No. 

### Environment (with versions)?

Grafana: v10.0.0 (81d85ce802) and Grafana v10.1.0 (838218ba20)
OS: Windows 10
Browser: Edge v116


### Grafana platform?

Docker

### Datasource(s)?

InfluxDB, Prometheus, GraphQL Data Source

**Comment by tonypowa** [comment]
thank you for creating this issue @ryanshaut 

after playing for a while, I decided to check the docs. 😅  It turns out that in order to update the auth fields of a datasource via the Grafana API `PUT /api/datasources/uid/:uid` endpoint, you actually need to include the `secureJsonData` section instead of ` secureJsonFields`

Example:

``` json
,
    "secureJsonData": {
        "httpHeaderValue1": "newtoken",
```
Successful request in command line:

![image](https://github.com/grafana/grafana/assets/45235678/60b8800d-bcfd-4d47-b2aa-7521a0530090)


Reference:
https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#examples-7

Hope that solves your problem!

**Comment by ryanshaut** [comment]
D'oh! 

`secureJsonData` works for me. Appreciate the quick response
