### ISSUE TITLE
[Feature Request] Does Grafana have a dashboard sharing feature that includes a query?

### ISSUE THREAD

**Issue by YunSangJun** [grafana/grafana#7413]
Does Grafana have a dashboard sharing feature that includes a query?

For example..
-Grafana share url 
http://xxx/dashboard/db/test?from=1485849978750&to=1485853578750

-Kibana share url 
http://xxx/app/kibana#/dashboard/test?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now)),query:(query_string:(analyze_wildcard:!t,query:'@app_id:%22ef157fe7-c33a-40a0-a047-e05273e968cd%22')) ...

Please include this information:
- What Grafana version are you using?
4.0.0
- What datasource are you using?
Elasticsearch
- What OS are you running grafana on?
Ubuntu

**Comment by torkelo** [comment]
not currently but it's an interesting feature we might implement some day:

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/5594
