### ISSUE TITLE
[Feature request] Alerting & OK notification: Condition; timeframe in link

### ISSUE THREAD

**Issue by Dominik-K** [grafana/grafana#7414]
It would be nice if you could add some things for the new alerting feature which I like very much.

* In the alert notification (we use e-mails), add the condition which triggered the alert. 
We often use two or more conditions, concatenated via “OR”. So, it would be good to know in the notification itself which condition is fulfilled.

* In the alert notification (we use e-mails), add an timeframe in the link of the “View your Alert rule” button, e.g. 1h.
Some alerts don’t need immediate reaction, so looking at them sometimes later, it would ease the workflow a little bit ;-)

* In the [OK] notification, add the same information as in the alert notification, also with the triggered condition.
Sometimes two different alerts or the same alert fires more than one time in a short time period. So it’s easier to understand which alert & condition is already resolved.

Keep up the good work.

- What Grafana version are you using? 
4.1.1 
- What datasource are you using? 
Prometheus
- What OS are you running grafana on? 
Docker image 79deadd58a50 (it's actually not the 4.1.1 tag), so debian:jessie

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
