### ISSUE TITLE
[Feature request] SSO-CAS authentication 

### ISSUE THREAD

**Issue by lipoteFR** [grafana/grafana#7415]
Bonjour,
J'utilise Grafana/influxDB pour mon client et j'adore.
 - Django/oracle pour les écrans et le référentiel
 - XWiki pour la documentation 
 - Jenkins pour ordonnancer 
 - zabbix, birt, php...
Tous ces outils sont derrière un CAS sauf Grafana :(

I'm using Grafana in an "eco-system" with many other framwork and tools that are all SSO-CAS complient.
Could you please, starting a SSO-CAS plugin section.

**Comment by torkelo** [comment]
You can get this working today by using a SSO-CAS module in apache or nginx and then use the auth proxy feature in grafana (where nginx or apache sends the user name in a trusted header to grafana)

**Comment by lipoteFR** [comment]
Hi to all,
No way to have SSO-CAS module, :(, grrr..... ça aurait été bien/it would have been cool.

Actually my website is working under an Apache 2.4.
  <my_web_site>.fr is accessible unsigned (part of php)
  <my_web_site>.fr/django is SSO-CAS
  <my_web_site>.fr/xwiki is SSO-CAS
  <my_web_site>.fr/grafana people should sign again (grrr)

I know it is an apache question but may be you can help : 
   if i activate "auth proxy", how can i do it only for /grafana/*

In my apache conf i have something like :
<VirtualHost  <ip of the dns my_web_site>:443>
...
    ProxyPass           /grafana        http://<machine_with_grafana>:3000
    ProxyPassReverse    /grafana        http://<machine_with_grafana>:3000
...
Lot of mercis
Léopold
