### ISSUE TITLE
Bug: Potential Security Issue - Debian init file does not place values in double quotes

### ISSUE THREAD

**Issue by raphaelcohn** [grafana/grafana#7416]
Please include this information:
- 4.1.1-1484211277_amd64.deb
- N/A
- Debian
- N/A
- N/A
- N/A

When setting the value of `WORK_DIR` from `GRAFANA_HOME`, the debian init script does not properly quote the value of `GRAFANA_HOME`. This is a potential security vulnerability as well as causing problems depending on the value of `IFS` and the presence of spaces in the path. As a mindset, I'd suggest always quoting environment values when using them in POSIX-compatible shell scripts.

Likewise, the `DAEMON_OPTS` variable also suffers from the same issue. Instead, use `set -- --pidfile="${PID_FILE}" --config="${CONF_FILE}" cfg:default.paths.data="${DATA_DIR}" cfg:default.paths.logs="${LOG_DIR}" cfg:default.paths.plugins="${PLUGINS_DIR}"

As an aside, it's probably better practice to avoid using `touch` to create empty files; it's just a side effect. Just using `printf '' >/path/to/file`. Indeed, minimising dependencies, and, better, avoiding them (eg creating `/var/log/xxx` in the first place in an init script when it should happen on package install) makes your application more robust in a hostile environment. And a hostile environment can be one with a broken PATH because something else went wrong, like the administrator...

**Comment by torkelo** [comment]
Could you prepare a PR ?

**Comment by torkelo** [comment]
can you describe in what way it is a security issue ?

**Comment by raphaelcohn** [comment]
"In what way is it a security issue?" You've got something running as root where compromising an environment variable (eg by tricking an user to include a path with a space or semicolon in it) could let an attacker inject arbitrary shell code... Think of it as a SQL injection attack waiting to happen...

I'm currently busy working on packaging grafana for Libertine Linux, and, as it's my employer's time, I don't at this time have the opportunity to create a PR. What's needed is a complete re-write of the init script. It's concerning that there are other signs that suggest the code here isn't as good as it could be; the useful of backticks for shell escapes; the lack of quoting, and the inconsistent indentation style.

**Comment by torkelo** [comment]
The init script was inspired from may other init scripts (elasticsearch among others) but I had limited experience with initd scripts at the time and if you have constructive help that would be great (beside the use change to the deemon opts line) 

I can update the initd script with that soon change tomorrow if you don't have time. 

Since you seem to know Linux security, maybe you can  comment on this PR https://github.com/grafana/grafana/pull/7279

**Comment by mcandre** [comment]
> The init script was inspired from may other init scripts

So the risk was copied over many times across many other dauntless scripts. Should probably quote protect just in case.
