### ISSUE TITLE
Alerting: aggregate functions have no documentation

### ISSUE THREAD

**Issue by GiedriusS** [grafana/grafana#74171]
### What happened?

We have an alert on a time series that went from around 2000 to 100. Our condition is:

```
WHEN percent_diff_abs() OF query (A, 15m, now) IS ABOVE 300
``` 

The use case is to get an alert if the value drops significantly in comparison to the previous values.

### What did you expect to happen?

For the alert to trigger. If I try to calculate this manually using https://github.com/grafana/grafana/blob/485f07cb7d73b4daee1fdcfd7eeb6f2aca6d9cf4/pkg/expr/classic/reduce.go#L201 then the result is:

https://go.dev/play/p/gJPZ-bylYPq

`math.Abs((300-2000) / 2000 * 100)`

Result: 85. In this case 85% means that 1700 makes up 85% of the original 2000 value. But this isn't at all what I wanted to calculate.

I expected to see 666.66% here because 300 is 6 2/3 times smaller than 2000.

Perhaps this is intended but then it's misleading and this function can only be used to calculate increases, not decreases. It's hard to tell due to no documentation: https://github.com/grafana/grafana/issues/29980.

### Did this work before?

Don't think so.

### How do we reproduce it?

1. Add alert condition using `percent_diff_abs`
2. Make the time series value go down enough so that the condition should be triggered i.e. difference expressed in % should be enough to trigger the alert
3. See that the alert doesn't get triggered

### Environment (with versions)?

Grafana: 9.5.3
OS: N/A
Browser: N/A

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by armandgrillet** [comment]
This looks like a SSE issue, @kylebrandt do you have an opinion on this issue?

**Comment by gillesdemey** [comment]
@kylebrandt do you have any thoughts on this one?

**Comment by armandgrillet** [comment]
The behavior is to be expected but there is indeed a lack of docs on this, we should give a short explanation for all these functions:

- avg()
- max()
- min()
- sum()
- count()
- last()
- median()
- diff_abs()
- diff()
- percent_diff()
- percent_diff_abs()
- count_non_null()

**Comment by brendamuir** [comment]
@armandgrillet does this document cover some of what you are asking above? 
https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#operations

**Comment by brendamuir** [comment]
Fixed with https://github.com/grafana/grafana/pull/78893.
