### ISSUE TITLE
Feature Request: Data Source description

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#7418]
Something that our users would find very usefull would be a description for a Data Source
Aka a user supplied description for the Data Source that is shown i the tile.

For ex:

![tile](https://cloud.githubusercontent.com/assets/12084305/22471655/442bcafe-e7d3-11e6-8a26-ce4a49b5527a.jpg)

The address can be removed from the tile in my view... doen't say much and is usually truncated anyway..

**Comment by bergquist** [comment]
image seems broken?

**Comment by joakimberglund** [comment]
doh, okie should be fixed.

Thanks for the heads up :)

**Comment by daniellee** [comment]
I think this feature has already been implemented, so we’re going to go ahead and close this.

![image](https://user-images.githubusercontent.com/434655/98598819-538f1400-22db-11eb-8740-616895c8ff31.png)
