### ISSUE TITLE
Transformations: Make it harder to select unusable transformations from UI

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#74199]
Currently all transformations will be shown in the UI regardless of the underlying data. This can end up presenting confusing situations, especially if someone isn't aware of the underlying operation of transformations.

For instance, the _Merge_ transformation requires multiple data frames. However it can still be added even when there is only a single frame:

<img width="1144" alt="Screenshot 2023-08-31 at 10 13 41 AM" src="https://github.com/grafana/grafana/assets/199847/c492f992-2016-47c0-aced-d0073120cb56">

We should apply a method to hide or disable these in appropriate situations. In the basic case with a single data series _Merge_ can never be applied so it's a bit of a shame we present that as an option. Another good candidate would be _Format Time_ as it requires a time field to function.

**Comment by catherineymgui** [comment]
Proposal:

https://www.figma.com/file/bhPMG2Cm3lj83lOBE0OuZe/Transformations?type=design&node-id=1764%3A112199&mode=design&t=65SFmkF6wWKdOXp3-1

- (We can talk about this in our sync) I know we talked about moving disabled items to the bottom of the list, however I recommend just keeping them in the same alphabetical order. If only a couple of them are disabled, and they're moved to the bottom - users may not know if they ever existed and it would be confusing if the ordered list keeps changing. If there are scenarios where A LOT of transformations are disabled, maybe we could potentially add some filter but I want to see when those scenarios appear

<img width="1366" alt="Transformations - Disabled V2" src="https://github.com/grafana/grafana/assets/5264102/695ef558-cf92-478c-a82c-b2035eabbbc3">
