### ISSUE TITLE
Devenv: Provision a lot of folders

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#74190]
We have examples where performance or display of a lot of folders may be of interest. We should be able to provision this with a denenv script. Consider making one for nested folder and one for non-nested.

Provision script will:
 - accepts number of folders as an argument (defaults to 1,000)
 - generate that number of folders with a three dashboards in each

**Comment by eledobleefe** [comment]
I'm interested on working on this issue 🙂

**Comment by tskarhed** [comment]
Maybe we can pair up on this?
