### ISSUE TITLE
Transformations: Move transformation addition to a drawer

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#74197]
The current tab UI transformations leaves the transformations hanging out in a sea of text.

<img width="1600" alt="Screenshot 2023-08-31 at 10 05 35 AM" src="https://github.com/grafana/grafana/assets/199847/d36c53ec-cc75-4011-a6e0-78f57af062a0">

In this situation for those not familiar with Grafana design language it may be difficult to notice that this is a clickable UI element as it appears to be a text label because of its relative positioning. 

We're using this to track some experiments to see if we can make this look a bit more clickable.

**Comment by codeincarnate** [comment]
Draft PR with experiments here: https://github.com/grafana/grafana/pull/74240

**Comment by codeincarnate** [comment]
Current:

https://github.com/grafana/grafana/assets/199847/99441a3b-3035-4903-94cd-46af7f7fb7f5

**Comment by torkelo** [comment]
@codeincarnate we use the same tab design as GitHub and many websites, so I doubt this is a big issue, but if it improves the design of tabs and works everywhere we show tabs, then maybe. I wish we could have more rounded corners, Grafana is so angular :(

**Comment by codeincarnate** [comment]
Currently working on some issues with tab position messing up 😢 

![Image](https://github.com/grafana/grafana/assets/199847/f47218ce-1176-4b00-b7ee-87152dfe1ae1)
