### ISSUE TITLE
Transformations: Expand inline help

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#74201]
Current transformation help shows the description of the transformation with a link to the transformation documentation on the Grafana site.

<img width="1134" alt="Screenshot 2023-08-31 at 10 22 02 AM" src="https://github.com/grafana/grafana/assets/199847/9c27394c-a12e-4874-a547-0fcf29effe10">

This makes life hard for folks as most transformations are difficult to understand without referencing documentation. We're exploring different options to inline the documentation so that it can be referenced directly alongside of the transformations.

**Comment by baldm0mma** [comment]
This has been tackled by this PR -> https://github.com/grafana/grafana/pull/74052, and also fixes -> https://github.com/grafana/grafana/issues/74062
