### ISSUE TITLE
[Feature request] Support new relic as built-in datasource

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7421]
Please include this information:
- What Grafana version are you using?
v4.0.2

There is already a 3rd-party plugin (https://github.com/wevanscfi/grafana-newrelic-apm-datasource) for Grafana to fetch data from new relic, however, it is only tested for Grafana v3.0.0 so it doesn't support alerting feature. Please consider supporting new relic as built-in datasource with alerting feature.

**Comment by torkelo** [comment]
We are working on a official supported plugin for it 
https://grafana.net/plugins/grafana-newrelic-datasource

**Comment by wei-hai** [comment]
@torkelo Thank you for the information, is there an estimated release date for this plugin?

**Comment by jvendryes** [comment]
Any update on when this will be released?

**Comment by mic159** [comment]
@torkelo that link is a 404.
I believe the correct link is https://grafana.com/plugins/grafana-newrelic-app
When will it be available for general use, or is it perpetually going to be premium only?

**Comment by samlinbris** [comment]
praying this plugin will be available to the public too 🙏

**Comment by PXMYH** [comment]
Looks like it's only available in Enterprise support... Any plans in the future to open it up?

**Comment by torkelo** [comment]
Not really, need to support this project somehow :)

**Comment by phawzy** [comment]
@torkelo  I was reading in the official plugin to decide if it will fulfill my needs or not so i get the premium account
Does it support alerts - will the alerts tab be working and i can create grafana alerts in it or only use the Annotations to get alert events from newrelic
also a parameter like error percentage will i be able to find it as a metric in the plugin or just the Error/all metric.
