### ISSUE TITLE
[Bug] Rich Slack Notification (with Image) is Not Sent (with an http method)

### ISSUE THREAD

**Issue by aedahl** [grafana/grafana#7422]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
v4.1.1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu 16.14

- What did you do?
1 - Added a Slack Incoming Webhook Integration to my channel
2 - Created a new Alert Notification in Grafana of Type "slack"
3 - Added the URL to the field 'URL' in Slack Settings
4 - Selected 'Save' and then 'Send Test'
5 - I then added a new alert with a simple notification message for one of my panels, for when a packet loss value went below a last() query as a trigger
6 - I then disconnected the monitored client to trigger the query

- What was the expected result?
1 - Alert is triggered, notification behavior commences
2 - Image is generated and sent to /var/lib/grafana/png, then PUT to external image source (WebDAV)
3 - The image is then included in a message that is sent to Slack
4 - Notification appears in Slack

- What happened instead?
2 - Image is generated and sent to /var/lib/grafana/png, then PUT to external image source (WebDAV) - I can go to the other http://server/dav and see all of the generated .png images
3/4 - I receive the message as either "[Alerting] PanelTitle alert" with whatever message I wrote in plain text, or "[OK] PanelTitle alert" depending on the state

![2imagegen_webdav](https://cloud.githubusercontent.com/assets/401297/22489287/6e43eee6-e7cb-11e6-95a3-d20c82065f1c.PNG)
![2imagegen_put](https://cloud.githubusercontent.com/assets/401297/22489288/70c036ac-e7cb-11e6-80c8-96ca59a0de92.PNG)
![4slacknotification](https://cloud.githubusercontent.com/assets/401297/22489291/73795d42-e7cb-11e6-9f83-47fda7863a2a.PNG)

**Comment by torkelo** [comment]
Is your webdav server accessible publicly so slack can fetch them? They need to be public and accessible from the internet using anonymous access as slack will try to fetch it from their servers

**Comment by aedahl** [comment]
Sorry for not getting back to you in time - time differences.  I am aware of this issue, but the WebDAV server is readable by the public. 

I *do* have basic authentication set as well, since the external image source module requires it, in addition to the address of the WebDAV server.

Please advise.

**Comment by aedahl** [comment]
Oh - I see what you mean by public. My WebDAV server is on a corporate intranet, a private domain - and yeah, I have not gone to great lengths to open up access to the internet. Got it. Thank you for your patient reply.

**Comment by luart12** [comment]
Hi, i have this problem too, how can i change the place where the image is uploaded.

I configure everything, the image is getting uploaded to box fine (also test on 4shared), but the url grafana tries to access to the same url base as the webdav but box and 4 shared external path is not the same as the webdav uri, how can i change only the url base where to search the image.  

dav.box.com/image --> webdav box
external --> not dav.box.com/image more something like box.com/externallink/image

**Comment by daniellee** [comment]
@luart12 use the [public_url](http://docs.grafana.org/installation/configuration/#public-url) setting in the `[external_image_storage.webdav]` section in the grafana config file.
