### ISSUE TITLE
[Feature request] Graph Panel - Line color different to fill color

### ISSUE THREAD

**Issue by mic159** [grafana/grafana#7423]
Please include this information:
- What Grafana version are you using? 
  - grafana_4.1.1-1484211277
- What datasource are you using? 
  - simplejson
- What OS are you running grafana on?
  - Heroku cedar-14
- What did you do?
  - Make a stacked area graph
- What was the expected result? 
  - Filled areas with black lines between
- What happened instead?
  - Line color is the same as the area color.

I would like to be able to have black lines on a filled, stacked graph.

Like this:
![black_lines](https://cloud.githubusercontent.com/assets/849426/22488146/99b90a9a-e864-11e6-8ebf-9059231e0fd7.png)

But in Grafana, the line color is the same fill:
![grafana_graph](https://cloud.githubusercontent.com/assets/849426/22490613/5631b58e-e872-11e6-9852-115d3f756b07.png)

Would it be possible to get a line color override setting?

**Comment by torkelo** [comment]
should be possible with a minor çhange to flot line rendering so you can change stroke color. 

![image](https://cloud.githubusercontent.com/assets/10999/22496546/e7a701ae-e84a-11e6-9c9b-b3907c00aca4.png)

**Comment by torkelo** [comment]
The above screenshot was just made with a manual code change to change line stroke color to see the effect :)

**Comment by mic159** [comment]
I think it looks quite nice

**Comment by redlus** [comment]
Is there any progress on this feature?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
