### ISSUE TITLE
[Feature Request] Bar graph panel for Grafana

### ISSUE THREAD

**Issue by BhavyaLight** [grafana/grafana#7424]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?  
 4.1.1
- What datasource are you using?   
Graphite

- Wish to graph categorical data to find total counts (like failure count) over a time period. For example, for a data source like xx.server*.count_failure i'd like to plot a bar graph that shows a count of all failures over two weeks like so 

```
|  
|                       *  
|                       *                   *  
|   *                   *                   *  
|   *                   *                   *  
 -----------------------------------------------  
  server 1        server2      server3
```

**Comment by torkelo** [comment]
you can do this in axes tab. 

Change x-axis mode to Series. 

![Uploading Screen Shot 2017-02-01 at 14.33.57.png…]()
