### ISSUE TITLE
[Bug] Upgrade influxdb 1.1.0 -> 1.2.0 unable to find "stations" in TypesDB

### ISSUE THREAD

**Issue by cy8aer** [grafana/grafana#7425]
- What Grafana version are you using? 4.1.1
- What datasource are you using? collectd/cadvisor
- What OS are you running grafana on? alpine/docker - 3.5.1
- What did you do?

Upgrade influxdb from 1.1.0 -> 1.2.0 (alpine packages)

- What was the expected result?

just normal logging on influxdb side

- What happened instead?

Log entries - unable to find "stations" in TypesDB when working with grafana (like opening the site, changing dashboards or template parameters in the dashboards)

When going back to 1.1.0 everything works fine again.

**Comment by torkelo** [comment]
Please provide more information, what does Grafana do that is a bug? 

Can you include the query sent to InfluxDB and the InfluxDB response? Maybe there was an error in your InfluxDB upgrade? looks like "stations" is missing

**Comment by cy8aer** [comment]
I am sorry, messages still arrive, when grafana is stopped. So this is a problem of collector -> influxdb not influxdb -> grafana. Grafana itself did not show any missing data or wrong behaviours.

**Comment by BlackZork** [comment]
I have the same issue with collectd.

influx 1.7.3 is installed on local machine with collectd 5.8.1

"unable to find "stations" in TypesDB" is logged when another collectd (version 5.5.3) from OpenWRT router is sending data from iwinfo plugin.
