### ISSUE TITLE
Metric Namespace Not Queryable

### ISSUE THREAD

**Issue by JohnJMartins** [grafana/grafana#74252]
### What happened?

Customer reported that they were not able to see metrics from the metric namespace seen in the following photos (microsoft.hybridcompute). They are able to see and choose the metric namespace as an option but are unable to actually query metrics from it. When trying to use it from the alerts creation page, they are faced with this:
![image](https://github.com/grafana/grafana/assets/77704161/ad314146-aa55-45b1-b743-a2bf4d4e44ad)
When trying to query it directly, there are met with this error, which lists out all of the available metric namespaces, which microsoft.hybridcompute is not included in:
![image](https://github.com/grafana/grafana/assets/77704161/fd080366-1742-418d-ab34-197aef47aa44)

### What did you expect to happen?

To be able to choose the metric namespace specified above and actually query metrics from it

### Did this work before?

Unsure

### How do we reproduce it?

1. Create a new Grafana panel querying azure monitor
2. Try to either query metrics or set an alert from the resource and metric namespace seen in the photo above

### Environment (with versions)?

Grafana:
OS: Windows
Browser: Edge

### Grafana platform?

None

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
I have deployed an Azure Arc resource (connected to a Linux VM running the Azure Monitor agent) and I cannot see the `microsoft.hybridcompute` namespace as an option even for selection. [This](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/metrics-index) resource also indicates hybrid compute is not supported with Azure Monitor. Do you have any more insight @JohnJMartins?

**Comment by aangelisc** [comment]
I believe this is not a Grafana issue but rather just something that is not supported by Azure Monitor

**Comment by aangelisc** [comment]
@JohnJMartins any update on this?

**Comment by avidhanju** [comment]
@aangelisc getting more info around this namespace. Will keep you posted soon.

**Comment by alyssabull** [comment]
Closed due to inactivity.
