### ISSUE TITLE
GEOMAP - GeoJSON from Query (postgresql)

### ISSUE THREAD

**Issue by alexl04** [grafana/grafana#74257]
Currently, GEOMAP only supports GeoJSON data from flat files that are saved into the public folder of the Grafana instance which is inconvenient (only server admins can add files) and not dynamically adjustable (it is not possible to load only part of a very large GeoJSON file).

**Why is this needed**:
GeoJSON data from a query would allow:
1. to dashboard data from GeoJSON files without having them saved in the public folder which can only be done by server admins and this is far from ideal in a large setup (big company)
2. dashboard editors to create GeoJSON files on the fly which enables to update the data in the GeoJSON files more frequently and allows them to optimize the amount of data to be loaded

**What would you like to be added**:
Add the possibility to use GeoJSON data from a query to for example PostgreSQL.

**Who is this feature for?**
Everyone

**Comment by andnofence** [comment]
This would be a very useful feature and I'm surprised it doesn't exist yet. 

For anyone coming to this issue you may be interested to know that the Orchestra Cities Map already offers GeoJSON marker layers: https://grafana.com/grafana/plugins/orchestracities-map-panel/

**Comment by kerness** [comment]
I agree, this is exactly what I need now.

**Comment by yosiasz** [comment]
the way I handled, if it helps for now, is to spin up a nodejs/express api that reads from postgres and using infinity plugin to fetch and display dynamic mapping with orchestracities plugin. Would have been nice if one could do styling to color full and boundary

![image](https://github.com/grafana/grafana/assets/900951/eff9fdfe-26de-49a7-8ee6-902fb5eb0757)
