### ISSUE TITLE
DB Support: PGBouncer connectivity for Grafana DB

### ISSUE THREAD

**Issue by RamyaRohidas** [grafana/grafana#74260]
### What happened?

I am using Postgres as the DB source for Grafana and I am switching to PgBouncer to manage the connections better. Currently I am facing below issue while trying to Grafana using the PGBoucer Port no 6432.

level=error msg="Failed to get last sent time" error="pq: bind message supplies 3 parameters, but prepared statement \"\" requires 2"
level=error msg="Failed to update alert rules" error="failed to get alert rules: failed to fetch a list of folders that contain alert rules: pq: unnamed prepared statement does not exist"

### What did you expect to happen?

The port 6432 changes to connect to pgBouncer instead of PostGres should work and the grafana pods should be able to initialize properly

### Did this work before?

This was not tried before, this is the first time connect to pgBouncer on the default port 6432.

### How do we reproduce it?

Configure postgres as DB for grafana 

[database]
type = postgres
host = {postgres serve}:6432  # instead of  {postgres serve}:5432 
name = grafana
user = postgres

Redeploy grafana with the changed configurations in grafana.ini

### Is the bug inside a dashboard panel?

No, its when we are deploying grafana with connection string changed from postgres to pgbouncer.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by merlinj1** [comment]
Hello, in which pool mode is the pgBouncer running? Default mode is **session**, which needs some additional settings for supporting prepared statements. Please check the pgBouncer FAQ for further details: https://www.pgbouncer.org/faq.html

**Comment by RamyaRohidas** [comment]
Setting the pgBouncer connection pool mode to session works, it was by default set to transaction mode, thank you. However, I had to make an additional change for ignore_startup_parameter for extra_float_digits, hope it doesn't affect the functionality in any way.

**Comment by nikimanoledaki** [comment]
Hi! @RamyaRohidas could you confirm whether the solution above fixes the issue so that this issue can be closed, please? Thanks :)

**Comment by RamyaRohidas** [comment]
Thank you for the support, this issue can be closed.

**Comment by applejag** [comment]
Adding a note here in case it helps someone in the future who also went on a big debug case.

When using Grafana -> PgBouncer -> PostgreSQL, then you need to set `binary_parameters=yes` on your connection string.

This means you need to use the `url` config field in the [`[database]` section](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#database) to be able to set this parameter. For example:

```ini
# snippet from the grafana.ini file
[database]
type = postgres
url = postgres://grafana:$__file{/var/run/secrets/grafana/postgresql/password}@grafana-postgresql-pooler-rw:5432/grafana?sslmode=require&binary_parameters=yes
```

Or if you're like me and deploy Grafana using the [Grafana Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana), then you set the following Helm values:

```yaml
# snippet from the values.yaml file
grafana.ini:
  database:
    type: postgres
    url: postgres://grafana:$__file{/var/run/secrets/grafana/postgresql/password}@grafana-postgresql-pooler-rw:5432/grafana?sslmode=require&binary_parameters=yes

extraSecretMounts:
  - name: postgresql
    mountPath: /var/run/secrets/grafana/postgresql
    secretName: my-secret-containing-the-password
    readOnly: true
```

I'm glad the [`$__file{...}` syntax](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#file-provider) works in the `url` field too, so I don't have to include the password in plain text in the config.

Ref:

- https://github.com/grafana/xk6-sql/issues/31#issuecomment-1427831261
- https://stackoverflow.com/a/53225070/3163818
- This works with a CloudNativePG cluster using PgBouncer as pooler, with all default settings.
- You can't mix the `url` config with `host`, `name`, `user`, etc. If `url` is set, it takes precedence, and the other fields are ignored. Therefore the `url` must contain the username and password info too. Source: https://github.com/grafana/grafana/blob/6fbb35736e338dc5729722f7fd545fe010f07ab3/pkg/services/sqlstore/database_config.go#L71-L99
