### ISSUE TITLE
How does relabeling work for Grafana agent

### ISSUE THREAD

**Issue by jyotsna2499** [grafana/grafana#74271]
### What happened?

I have been trying to install Grafana agent over Kubernetes cluster, to monitor metrics and logs. I want to reduce the active series for my metrics. I will paste my values.yaml file below.
cluster:
  name: "cluster"

externalServices:
  prometheus:
    host: "url"
    basicAuth:
      username: "username"
      password: "password"
    writeRelabelConfigRules: |-
      write_relabel_config {
        source_labels = ["__name__"]
        regex = "node_filesystem_device_error|kube_job_status_failed|kube_replicaset_annotations|kube_replicaset_created|kube_replicaset_labels|kube_replicaset_metadata_generation|kube_replicaset_spec_replicas|kube_replicaset_status_fully_labeled_replicas|kube_replicaset_status_observed_generation|kube_replicaset_status_ready_replicas|kube_replicaset_status_replicas|kube_job_complete|kube_pod_container_status_restarts_total|ALERTS|kube_job_annotations|kube_job_created|kube_job_info|kube_job_labels|kube_job_owner|kube_job_spec_completions|kube_job_spec_parallelism|kube_job_status_succeeded|node_filesystem_files|node_filesystem_files_free|node_filesystem_free_bytes|node_filesystem_readonly|kube_pod_start_time"
        action = "drop"
      }

  loki:
    host: "<url>"
    basicAuth:
      username: "username"
      password: "password"

metrics:
  kube-state-metrics:
    extraMetricRelabelingRules: |-
      rule {
        source_labels = ["namespace"]
        regex = "my-namespace"
        action = "keep"
      }
      
opencost: {enabled: false}

### What did you expect to happen?

As shown above, I expected to get metrics only for a particular namespace "my-namespace", but I still see merics for all the namespaces, also there is a set of unused metrics that i wanted to drop, but I still see that also.

### Did this work before?

No, it did not.

### How do we reproduce it?

1. Please help me understand, how exactly does relabeling work in Grafana.
2. The steps that I followed, what is exactly incorrect in that.
3. also suggest steps, how to reduce the number of active series for my instance in the Grafana cloud. I followed the official doc, but I am not very clear how exactly to use relabelings

### Environment (with versions)?

Grafana:
OS: Windows
Browser: Microsoft edge

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Kubernetes cluster sending to Prometheus and Loki in Grafana cloud

**Comment by SimardeepSingh-zsh** [comment]
Check Configuration Syntax: Ensure that your values.yaml file is correctly formatted. YAML files are sensitive to indentation and formatting. Double-check that there are no syntax errors.

Recheck Regex Patterns: Review the regex patterns used in your writeRelabelConfigRules and extraMetricRelabelingRules sections. Make sure they match the labels or metrics you want to include or exclude accurately. The regex patterns should be tested to ensure they work as expected.

Verify Namespace Label: In the extraMetricRelabelingRules section, you are using a regex pattern to match the namespace. Ensure that the namespace label you are trying to match (in this case, "my-namespace") is correctly configured in your Kubernetes setup. Labels in Kubernetes should match the exact names used in your configuration.

Inspect Prometheus Configuration: Check your Prometheus configuration to ensure it's scraping the Grafana Agent correctly. Prometheus should be configured to scrape metrics from the Grafana Agent, and any relabeling or filtering should be done within Prometheus configuration, if applicable.

Debugging: Grafana Agent provides logs that can be helpful for debugging. Check the logs to see if there are any error messages related to relabeling rules. You can access logs by running the Agent with increased verbosity or checking the container logs if you're running it in Kubernetes.

Prometheus Queries: In Grafana, you can use Prometheus queries to test whether your relabeling rules are working as expected. Use the Prometheus query interface to run queries against the scraped metrics and see what is being retained or dropped.

Grafana Cloud Support: If you are using Grafana Cloud, consider reaching out to their support or consulting their documentation for specific guidance on configuring Grafana Agent and relabeling in the Grafana Cloud environment. They may have specific recommendations for their setup.

Community Support: Grafana has an active community, and you can also seek help on the Grafana Community forum or GitHub repository. Other users and developers may have encountered similar issues and can provide assistance.

**Comment by SimardeepSingh-zsh** [comment]
Lastly, when you talk about reducing the number of active series, one way to do this is by carefully configuring what metrics are scraped and stored in Prometheus. The relabeling rules can help with this, but you should also review your Prometheus configuration and adjust scraping targets to limit the metrics you collect, especially in a multi-namespace setup.

**Comment by tonypowa** [comment]
Many thanks for stepping in @SimardeepSingh-zsh 👍 

@jyotsna2499  If you needed additional help, please open a [support ticket](https://grafana.com/contact) instead, since you are using Grafana Cloud
