### ISSUE TITLE
[Feature request] Allow max db connection pool configuration

### ISSUE THREAD

**Issue by jkubrynski** [grafana/grafana#7427]
Currently, it's not possible to configure max pool size (SetMaxOpenConns) which causes problems when having many Grafana instances.

**Comment by torkelo** [comment]
should be easy, there is a nn option SetMaxOpenConns xorm (and the underlying goland std sql lib)

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/7520
