### ISSUE TITLE
Breadcrumb: Parent folder link does not work when grafana is served from sub path /dashboard

### ISSUE THREAD

**Issue by merlinj1** [grafana/grafana#74275]
### What happened?

Similar to this bug [#70047](https://github.com/grafana/grafana/issues/70047) the issue is still occuring with grafana version 10.1.1 and the subpath _/dashboard_.

So when viewing a dashboard, I tried to open the parent folder from the top left breadcrumb navigation in a new tab ( Home > Dashboards > **ParentFolder** > DashboardXYZ.
Hovering on the link shows the following URL: `https://<domain>/dashboards/f/<parentFolderId>`
When I click on the link, I will be redirected to:  `https://<domain>/dashboard/s/f/<parentFolderId>`
The correct link for our settings would be:  `https://<domain>/dashboard/dashboards/f/<parentFolderId>`

It seems, that the /**dashboards**/ url path is somehow replaced by /**s**/

### What did you expect to happen?

When I click on a parent folder link, the parent folder page opens.

### Did this work before?

Not for our setup

### How do we reproduce it?

Step 1:

Open Grafana served from sub path /dashboard.

Step 2:

Create a folder. (The General folder is not included in the breadcrumb navigation)

Step 3:

Create a dashboard in this folder, save it.

Step 4:

From the dashboard page, try to open the parent folder in a new tab from the breadcrumb navigation.
Or, try to copy the link.
Or, just look at the link url at the bottom of your browser while hovering the parent folder lin

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.1
OS: Linux
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by merlinj1** [comment]
Hi, enabling the feature toggle _nestedFolders_ solved the problem on our side. That is fine for me, so I will close this issue. Thanks anyway for your effort!

**Comment by merlinj1** [comment]
Unfortunately we cannot use the _nestedFolders_ Feature at the moment, so i had to deactivate it again. Without that feature toggle activated, the issue is still existing with Grafana 10.1.5.
I attached a screen record to show the actual issue:

https://github.com/grafana/grafana/assets/89360266/07a6c478-7859-4ab4-a06b-885ff8a725be

**Comment by paladium** [comment]
I agree, this bug occurs on our self-hosted Grafana version. Sometimes, it is annoying clicking on link and opening it in a new tab and not seeing Grafana :(
