### ISSUE TITLE
Design the error message when the request for AI is not responding

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#74287]
**Goal**

Show the user with a notification that there is an error generated within the AI feature and they need to retry.

**Tasks**

- [x] Design the best placement for an inline-banner

**Comment by natydej** [comment]
Having the error message above both inputs will tell the user that everything AI related is not working. Design below:
<img width="539" alt="GenerateTitle-Error" src="https://github.com/grafana/grafana/assets/51436795/7a98f063-a916-442a-b710-ef2a38f64e45">


[Figma link](https://www.figma.com/file/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=603-285&mode=design)

**Comment by ivanortegaalba** [comment]
In this case, I'm ok with this one. It would be easier for us to have it in the button, but the banner is fine.
