### ISSUE TITLE
[Feature request] coloring string fields in table panel

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#7428]
It would be nice to be able to map colors to different string values.
For example, we're monitoring a load balancer, and one of the fields we store is a string with a few possible values ("UP", "DOWN", "MAINT", etc). We would like to color code "UP" to green, "DOWN" to red, "MAINT" to yellow, etc.

In addition to colorizing the field, it might be nice to use the color for the entire row as well (a different field would be able override its own color).

Please include this information:
- What Grafana version are you using?
4.1.1
- What datasource are you using?
InfluxDB

**Comment by torkelo** [comment]
there already is a feature request for this (and PR I think) https://github.com/grafana/grafana/issues/3601
