### ISSUE TITLE
Transformations: Rename by regex has the same description as the reduce transform

### ISSUE THREAD

**Issue by halleystar** [grafana/grafana#74297]
### What happened?

![image](https://github.com/grafana/grafana/assets/5334156/58fe9162-21e6-4458-a3ad-db6c53021037)
the desc is same as Reduce transferm

### What did you expect to happen?

the desc issue

### Did this work before?

yes

### How do we reproduce it?

open transform panel

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Other

**Comment by halleystar** [comment]
i mean the description of  the Reduce and Rename by regex are the same. They are all "Reduce all rows or data points to a single value(ex.max, mean)"

**Comment by tonypowa** [comment]
Oh, sorry I see it now!  😓 Many thanks for clarifying that !
I will add the issue to the BI squad's board
