### ISSUE TITLE
github enterprise auth gets redirected to github.com

### ISSUE THREAD

**Issue by maneeshmp** [grafana/grafana#7429]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
  4.1.1
- What datasource are you using?
zabbix and cloudwatch
- What OS are you running grafana on?
linux
- What did you do?
  I was trying to enable authentication with github
- What was the expected result?
      I should be able to login to grafana using my github enterprise creds
- What happened instead?
    Ridrect url redirects me to github.com
   https://github.com/login/oauth/authorize?access_type=online&client_id=66249c8b443323324322&redirect_uri=http%3A%2F%2Fgrafana.abc.com%2Flogin%2Fgithub&response_type=code&scope=user%3Aemail%2Cread%3Aorg&state=XF%2FvqzsPIeaWuNwQ5PdhNSADFwrewerWEE3pw%3D

Here is the grafana ini configruation 
#################################### Github Auth ##########################
[auth.github]
enabled = true
;allow_sign_up = true
client_id = 66249c452352352633732
client_secret = e831sdfsf424231ab4cdbf15a917cb4f7e5
scopes = user:email,read:org
;auth_url = https://github.abc.com/login/oauth/authorize
;token_url = https://github.abc.com/login/oauth/access_token
api_url = https://github.abc.com/api/v3
;team_ids =
;allowed_organizations =
------------------------------------------------------------------------

GHE configration
  call back URL : http://grafana.abc.com/login/github

**Comment by bergquist** [comment]
You need to remove the `;` sign infront of `auth_url` and `token_url`

**Comment by maneeshmp** [comment]
@bergquist I did try enabling that URLs as well, then I get another error

Server side error :(
login.OAuthLogin(get info from github)

Redirect URL : http://grafana.abc.com/login/github?code=f4ab5294534gsdfsde31&state=ho04WPwN%2Fg3dKVq7gW0sdfgsdfg452323rZrbC%2F1lDpN30s%3D

Log File: 
t=2017-02-02T15:14:33+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="json: cannot unmarshal object into Go value of type []social.Record"
t=2017-02-02T15:14:33+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=71.68.252.14 time_ms=691ns size=702
