### ISSUE TITLE
i18n: Mark up Flame Graph for translations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#74309]
### Requirements ###

Mark up https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/FlameGraph components for translations

### Background

Please follow #70957 for more info and guidelines.

**Comment by ashutosh887** [comment]
@ifrost Let me work on this issue

**Comment by ifrost** [comment]
> @ifrost Let me work on this issue

Thanks @ashutosh887 🙌  This component is owned by  @grafana/observability-traces-and-profiling squad. 

@grafana/observability-traces-and-profiling do you have the capacity to provide help/review on this one?

@ashutosh887 Thank you for your interest in other issues! Please make sure you pick one at the time.

**Comment by ngken0995** [comment]
Hello @ifrost and @joey-grafana,

This is my first time contributing to an open source project. I took a look at [FlameGraph](https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/FlameGraph) folder and notice there is a [wrapper](https://github.com/grafana/grafana/tree/v10.1.0/public/app/plugins/panel/flamegraph/components).  It contains a header and additional files with phrases. Please advise if I'm going on the right steps.

**Comment by joey-grafana** [comment]
Hello and thank you for your interest in submitting a PR!

You are on the right track. As mentioned in the description of this issue, the FlameGraph component is the file to mark up for translation.

**Comment by ngken0995** [comment]
Hello @joey-grafana and @ifrost,

The [dataTranform](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/flamegraph/components/FlameGraph/dataTransform.ts) file throw a couple of error as a phrase. Should I add i18n to those errors?

**Comment by ifrost** [comment]
After an internal discussion, we concluded that unfortunately, we need to postpone translating Explore's core visualizations as they (or some of their parts) may require externalizing to separate plugins. I18n is available only to core functionalities. There's no i18n support for external plugins, so translating Explore's visualizations now would create technical debt by creating dependencies with core, slow down further improvements, and very likely some of the work would need to be rolled back eventually.
