### ISSUE TITLE
i18n: Mark up Trace View panel for translations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#74308]
### Requirements ###

Mark up https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/TraceView components for translations

### Background

Please follow #70957 for more info and guidelines.

**Comment by subhajit20** [comment]
@ifrost Want to help. Can you give some details that how I can fix it?

**Comment by ifrost** [comment]
> @ifrost Want to help. Can you give some details that how I can fix it?

Thanks @subhajit20 🙌 This component is owned by @grafana/observability-traces-and-profiling squad.

@grafana/observability-traces-and-profiling do you have the capacity to provide help/review on this one?

> Can you give some details that how I can fix it?

The issue requires marking up https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/TraceView components for translations (without dependencies outside of this folder).  Please check https://github.com/grafana/grafana/issues/70957 for more info and guidelines. You can also check existing issues and related PRs to see some examples.

**Comment by joey-grafana** [comment]
Yes I would say once a PR is opened we can take a look!

**Comment by ifrost** [comment]
After an internal discussion, we concluded that unfortunately, we need to postpone translating Explore's core visualizations as they (or some of their parts) may require externalizing to separate plugins. I18n is available only to core functionalities. There's no i18n support for external plugins, so translating Explore's visualizations now would create technical debt by creating dependencies with core, slow down further improvements, and very likely some of the work would need to be rolled back eventually.
