### ISSUE TITLE
the alert rule added via http provisioning API cannot be found in Ui

### ISSUE THREAD

**Issue by dudufan** [grafana/grafana#74304]
### What happened?

My alert history exists, but cannot view the alert rule added via http provisioning API . The rule can also be found via http API
version: grafana-10.0.3
![image](https://github.com/grafana/grafana/assets/17895346/7c459c64-62c5-4764-9d24-d7b9e998ee54)
![image](https://github.com/grafana/grafana/assets/17895346/4bca828d-8d5d-4eb5-b4b4-34ff4535a1dc)
![image](https://github.com/grafana/grafana/assets/17895346/930c06cf-7b9e-4c5c-8664-a00690a9b845)

### What did you expect to happen?

the alert rule can be found via UI

### Did this work before?

always no 

### How do we reproduce it?

1. create  the alert rule via http provisioning API and can query it via api.
2.  alert history in Alerting -> Groups can be found
3. alert rule cannot be found in  Alerting -> Alert Rules

### Environment (with versions)?

Grafana: grafana-10.0.3
OS: centos7.9
Browser: Microsoft Edge

### Grafana platform?

A downloaded binary

**Comment by blacktig3r** [comment]
I have setup the environment with above exact versions and trying to reproduce the issue.
I am able to create the rules using provision api for my prometheus dataset and it is visible in Grafana UI/Alerting section.
![image](https://github.com/grafana/grafana/assets/31062473/37d3fa82-e19b-45c8-9d2b-b512a572cf87)
![image](https://github.com/grafana/grafana/assets/31062473/9f3643b9-ea62-4278-9a83-4ae061075729)
**here is the sample api command I used to create rules..**
`curl -X POST --insecure  -H "Authorization: Bearer *<api token>*"   -H "Content-Type: application/json"   -d '{
    "orgID": 2,
    "folderUID": "fc608986-65b6-48f6-a9b3-144e67d5d602",
    "ruleGroup": "a",
    "title": "tes2222",
    "condition": "A",
    "data": [
      {
        "refId": "A",
        "queryType": "",
        "relativeTimeRange": {
          "from": 600,
          "to": 0
        },
        "datasourceUid": "d0973168-b2db-4c90-9f85-5aeab34d11d0",
        "model": {
          "editorMode": "builder",
          "expr": "avg(prometheus_http_requests_total{code=\"200\", handler=\"/\", instance=\"localhost:9090\", job=\"prometheus\"}) > 20",
          "hide": false,
          "instant": true,
          "intervalMs": 1000,
          "maxDataPoints": 43200,
          "range": false,
          "refId": "A"
        }
      }
    ],
    "noDataState": "NoData",
    "execErrState": "Error",
    "for": "5m",
    "isPaused": false
  }
}
'   http://localhost:3000/api/v1/provisioning/alert-rules`

**Comment by dudufan** [comment]
> I have setup the environment with above exact versions and trying to reproduce the issue. I am able to create the rules using provision api for my prometheus dataset and it is visible in Grafana UI/Alerting section. ![image](https://user-images.githubusercontent.com/31062473/265518538-37d3fa82-e19b-45c8-9d2b-b512a572cf87.png) ![image](https://user-images.githubusercontent.com/31062473/265518776-9f3643b9-ea62-4278-9a83-4ae061075729.png) **here is the sample api command I used to create rules..** `curl -X POST --insecure -H "Authorization: Bearer *<api token>*" -H "Content-Type: application/json" -d '{ "orgID": 2, "folderUID": "fc608986-65b6-48f6-a9b3-144e67d5d602", "ruleGroup": "a", "title": "tes2222", "condition": "A", "data": [ { "refId": "A", "queryType": "", "relativeTimeRange": { "from": 600, "to": 0 }, "datasourceUid": "d0973168-b2db-4c90-9f85-5aeab34d11d0", "model": { "editorMode": "builder", "expr": "avg(prometheus_http_requests_total{code=\"200\", handler=\"/\", instance=\"localhost:9090\", job=\"prometheus\"}) > 20", "hide": false, "instant": true, "intervalMs": 1000, "maxDataPoints": 43200, "range": false, "refId": "A" } } ], "noDataState": "NoData", "execErrState": "Error", "for": "5m", "isPaused": false } } ' http://localhost:3000/api/v1/provisioning/alert-rules`

**Comment by dudufan** [comment]
> I have setup the environment with above exact versions and trying to reproduce the issue. I am able to create the rules using provision api for my prometheus dataset and it is visible in Grafana UI/Alerting section. ![image](https://user-images.githubusercontent.com/31062473/265518538-37d3fa82-e19b-45c8-9d2b-b512a572cf87.png) ![image](https://user-images.githubusercontent.com/31062473/265518776-9f3643b9-ea62-4278-9a83-4ae061075729.png) **here is the sample api command I used to create rules..** `curl -X POST --insecure -H "Authorization: Bearer *<api token>*" -H "Content-Type: application/json" -d '{ "orgID": 2, "folderUID": "fc608986-65b6-48f6-a9b3-144e67d5d602", "ruleGroup": "a", "title": "tes2222", "condition": "A", "data": [ { "refId": "A", "queryType": "", "relativeTimeRange": { "from": 600, "to": 0 }, "datasourceUid": "d0973168-b2db-4c90-9f85-5aeab34d11d0", "model": { "editorMode": "builder", "expr": "avg(prometheus_http_requests_total{code=\"200\", handler=\"/\", instance=\"localhost:9090\", job=\"prometheus\"}) > 20", "hide": false, "instant": true, "intervalMs": 1000, "maxDataPoints": 43200, "range": false, "refId": "A" } } ], "noDataState": "NoData", "execErrState": "Error", "for": "5m", "isPaused": false } } ' http://localhost:3000/api/v1/provisioning/alert-rules`

Thank for your help! Referenced to official doc, I had set folderUid to a folder name wrongly. Now I create a correct rule via UI and export it to yaml, I see the correct folderUid and it works!
![image](https://github.com/grafana/grafana/assets/17895346/c48b6a4e-05c7-4750-816b-1342c7a8f78b)
https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-post-alert-rulespan-create-a-new-alert-rule-_routepostalertrule
Can you tell me where can I find the examples or demo for provisioning http api?

**Comment by blacktig3r** [comment]
unfortunately I am also not able to find out the examples over the internet. I have a workaround for this.
**The way I am able to get example is:**

1. create a alert rule using grafana UI.
2. use api GET command to list all rules 
`curl -X GET -H "Authorization: Bearer <token>" http://localhost:3000/api/v1/provisioning/alert-rules|jq .`
3. use the required fields from the json output (as shown in above image of red bracket)

**Comment by dudufan** [comment]
> unfortunately I am also not able to find out the examples over the internet. I have a workaround for this. **The way I am able to get example is:**
> 
> 1. create a alert rule using grafana UI.
> 2. use api GET command to list all rules
>    `curl -X GET -H "Authorization: Bearer <token>" http://localhost:3000/api/v1/provisioning/alert-rules|jq .`
> 3. use the required fields from the json output (as shown in above image of red bracket)

Thank for your advice. I think it is effective!
