### ISSUE TITLE
i18n: Mark up Graph for translation

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#74311]
### Requirements ###

Mark up https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/Graph components for translations.

### Background

Please follow #70957 for more info and guidelines.

**Comment by akarsh-jain-790** [comment]
@ifrost can you assign this issue to me?

**Comment by ifrost** [comment]
> https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/Graph

Sure! Feel free to open a PR for it. Thank you! 🚀

**Comment by chauchausoup** [comment]
@ifrost whats the status of this issue ? Are we still looking for PRs ?
