### ISSUE TITLE
i18n: Mark up Table for translations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#74312]
### Requirements ###

Mark up https://github.com/grafana/grafana/tree/v10.1.0/public/app/features/explore/Table components for translations.

### Background

Please follow #70957 for more info and guidelines.

**Comment by ahsanghalib** [comment]
@ifrost hello, I can work on i18n issues?

**Comment by ifrost** [comment]
> @ifrost hello, I can work on i18n issues?

Sure thing! Would like to work on this specific item or something else?

**Comment by michiboo** [comment]
@ifrost  i opened a pr for this issue, can you please review? thanks
