### ISSUE TITLE
[Bug] Series colors swapped when stacking

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#7432]
Using the latest grafana docker image with InfluxDB data source. When I toggle the "stack" setting in the Display tab, the series colors swap. The numbers shown in hovering over are correct. The numbers from InfluxDB are correct. Fails with stacked lines as well as bars.

![image](https://cloud.githubusercontent.com/assets/11174694/22549164/469ce318-e94a-11e6-8192-6757ed5ea2ee.png)
![image](https://cloud.githubusercontent.com/assets/11174694/22549206/73e56a16-e94a-11e6-97e3-23fc30209ed7.png)

**Comment by torkelo** [comment]
could you show the data returned from influxdb? (open chrome dev tools network tab)

**Comment by torkelo** [comment]
looks correct now that I test it with similar data. The problem is that Y-min is auto so the green User series is cut of and you only see the top of the bars. Go to Axes and set Y-min to 0

![image](https://cloud.githubusercontent.com/assets/10999/22583042/c81a9282-e9ea-11e6-9a1c-046e05999641.png)

**Comment by rvdheij** [comment]
Brilliant! The default non-zero Y-min fooled me before. :facepalm:
