### ISSUE TITLE
status=502 - Unable to add dashboards HTTP Error Bad Gateway

### ISSUE THREAD

**Issue by leeora** [grafana/grafana#7434]
status=502 - Wrong remote_add  Unable to add dashboards 

Please include this information:
- What Grafana version are you using?

 Grafana v4.1.1 (commit: v4.1.1)

- What datasource are you using?
graphite

- What OS are you running grafana on?

Red Hat Enterprise Linux 7.2 (Source)

- What did you do?

Install Grafana latest ver.Grafana v4.1.1
Installation pass.
Tried to add graphite dashboard. (or any other one such as influxDB  or Prometheus)

- What was the expected result?
Dashboard was add with no error

- What happened instead?
When pressing add I get :
**HTTP Error
Bad Gateway**

Without using Proxy I get :Error unknow.

On /var/log/grafana/grafana.log I get:
t=2017-02-02T16:24:50+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/metrics/find **status=502** remote_addr=10.223.3.85 time_ms=1ns size=0

Please note that the remote_addr ip is something that I don;t know where it came from as I'm working on a local machine. (127.0.0.1:3000)

Any attempt to add any dashboard came with the same error results.

Please help.

**Comment by leeora** [comment]
![grafana](https://cloud.githubusercontent.com/assets/25510363/22558818/c051d9ca-e977-11e6-8a70-effbca2ffb65.PNG)

**Comment by leeora** [comment]
![grafana](https://cloud.githubusercontent.com/assets/25510363/22558856/eb90d474-e977-11e6-8b11-8df7ab21d196.PNG)

**Comment by torkelo** [comment]
Do you have a graphite install on port 8080 on the same server as grafana is running on?

**Comment by leeora** [comment]
Yes.
graphite install on port 8080 on the same server as grafana is running on.
The error is the same in db I'm trying to add. 

If you try not to use PROXY than the error is "unknown"

**Comment by torkelo** [comment]
your graphite server is returning 502 "Bad Gateway", make sure it's accessable via http://localhost:8080 from same server as grafana-server

**Comment by leeora** [comment]
it is not working.I was not install graphite server as I understand that on that version of grafana graphite is built in it.look at the above picture and see.I think I did all by the book. 

not sure what to do next. if you can send me a link to a step by step it could be great. 
thanks for your help
