### ISSUE TITLE
Task: Enable public dashboards by default on prem

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#74350]
Enable Public dashboards by default in the [registry](https://github.com/grafana/grafana/blob/main/pkg/services/featuremgmt/registry.go)

Evaluate if we should remove the FF completely or keep it to be able remove the feature on demand

Remove mention to public preview in the config modal

**Comment by juanicabanas** [comment]
We won't remove the FF so users can disable it setting it as false and we can also modify the cloud instances
