### ISSUE TITLE
i18n: Mark up `PlaylistPage` for translations

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#74365]
follow instructions [here](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-translation-phrase). can verify translation strings have been marked up correctly by using the development-only pseudo locale: 
![image](https://github.com/grafana/grafana/assets/20999846/30890cfd-89bc-4d8f-8c47-daa8a92f5727)

checklist:
- [ ] Empty state text
- [ ] search placeholder text
- [ ] `New playlist` button
- [ ] `Start playlist` button
- [ ] `Edit playlist` button
- [ ] `Delete playlist` button
- [ ] `Share playlist` button tooltip text

**Comment by charlin99** [comment]
I'm new at contributing to open source projects and I would like to try to solve this issue. Can I be assigned to it?

**Comment by ashharrison90** [comment]
hi @charlin99 👋 

that's great! 🙌 feel free to raise a PR and tag this issue in the description

i try to avoid assigning issues to external contributors since if they then decide they don't have time, the assigned name dissuades others from contributing. hope that makes sense! 🙏

**Comment by ashutosh887** [comment]
@ashharrison90 
Let me work on this 

/assign
