### ISSUE TITLE
[Bug] Grafana Slack Alerts Sent Twice

### ISSUE THREAD

**Issue by iceandroidph** [grafana/grafana#7437]
![scr_stackoverflow](https://cloud.githubusercontent.com/assets/1859652/22578926/4034f95c-e981-11e6-8efa-10d979cc62a1.png) 
-- erased non-relevant info.

Please include this information:
- What Grafana version are you using? Grafana v4.0.2 (commit: v4.0.2)
- What datasource are you using? InlfuxDB
- What OS are you running grafana on? (Centos)
- What did you do? Create alert and notify via slack
- What was the expected result? Sends 1 slack notification (same for alerting, OK, and No Data)
- What happened instead? Sends 2 of the same notification (same for alerting, OK, and No Data)

**Comment by torkelo** [comment]
could it be so that you have more than one Grafana server connected to the same database?

If that is the case you need to disable alert evaluation on one of them. 

http://docs.grafana.org/alerting/rules/#clustering

**Comment by iksaif** [comment]
Seems to be a dup of https://github.com/grafana/grafana/issues/6957
