### ISSUE TITLE
Anonymous users can create snapshots but cannot delete them

### ISSUE THREAD

**Issue by maratkalibek** [grafana/grafana#7440]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
Grafana v4.1.1 (commit: v4.1.1)

- What datasource are you using?
Doesn't matter

- What OS are you running grafana on?
Ubuntu Server 16.04

- What did you do?
I took local snapshot as anonymous user (role Viewer)

- What was the expected result?
It must be forbidded to anonymous user to create local snapshots

- What happened instead?
I could take local snapshot as anonymous user 

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by jessabe** [comment]
I can't seem to recreate this bug anymore in v7. If you're still facing this issue please let us know and we can reconsider opening. Thanks for letting us know!
