### ISSUE TITLE
[Feature request] FieldOverrides: Unit as templated variable

### ISSUE THREAD

**Issue by Mikesch-mp** [grafana/grafana#7441]
It would be nice if we could set the axes unit of a graph with a templated variable or just set it via url variable like var-unitx=kb or similiar. 

Thanksin advance,
Carsten

- What Grafana version are you using? : 4.1.1
- What datasource are you using? : InfluxDB 1.2
- What OS are you running grafana on? : Centos 7

**Comment by osimmasgard** [comment]
Agreeing!

**Comment by friesoft** [comment]
Setting it from a query would also be nice. Icinga2 supports writing units into InfluxDB in master already.
https://github.com/Icinga/icinga2/pull/5675

**Comment by BastiBr** [comment]
Any news?
