### ISSUE TITLE
grafana ruler api is not documented

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#74434]
### What happened?

no documentation on 
https://github.com/grafana/grafana/blob/13f438221443f2164994d19ceb277c32af874db4/pkg/services/ngalert/api/generated_base_api_ruler.go

### What did you expect to happen?

to find some documentation on the api described in the code 

### Did this work before?

no 

### How do we reproduce it?

1. open docs
2. search for ruler api in docs
3. don't see nothing

### Is the bug inside a dashboard panel?

no 

### Environment (with versions)?

Grafana: 10.x
OS: linux
Browser: chome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

grafana

**Comment by GrafanaWriter** [comment]
@brendamuir - can you please review and assess for improvement?

**Comment by brendamuir** [comment]
@alexweav can you help with this one? or point me to who can? thanks :)
