### ISSUE TITLE
[Feature request] Data source (failover)

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#7443]
Hello, 
I thought about the feature or issue with a datasources. If I have a problem with connecting to my first prometheus, it will be able connect to secondary prometheus. For example: I would like have connected graphs from one dashboard to two same datasources. Is there a way to create this situation? It would be fine have it in a Grafana. 

![datasource-grafana](https://cloud.githubusercontent.com/assets/8748774/22593182/ae7a55c8-ea1d-11e6-8ca5-f1d629ce7e86.png)

Please include this information:
- What Grafana version are you using?  **Grafana v4.1.1** 
- What datasource are you using? **Prometheus**
- What OS are you running grafana on? **Debian Jessie**

Thank you.

**Comment by jsedy7** [comment]
So, I tested the datasource as failover and haproxy is the solution. Integrated solutions in grafana could be perfect feature. :)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
