### ISSUE TITLE
[Bug] Grafana can not interpret data

### ISSUE THREAD

**Issue by Ernte** [grafana/grafana#7444]
Hello,

I connected Grafana with Elasticsearch successfully. But I have no idea why Grafana can not show my Data.

So the value is "104". I want that the "Single Stat Panel" shows my  value "104".

What for a data structure Grafana requiers ? Or did I set the metrics wrong ? 

![test1](https://cloud.githubusercontent.com/assets/25530918/22594976/c384f114-ea25-11e6-8eeb-1f17bf297455.PNG)

![test2](https://cloud.githubusercontent.com/assets/25530918/22594990/d44174aa-ea25-11e6-8a1e-0c43881b6906.PNG)

![test3](https://cloud.githubusercontent.com/assets/25530918/22594991/d7f0240c-ea25-11e6-99a9-51df0bc83083.PNG)

- What Grafana version are you using? **4.0.2**
- What datasource are you using? **Elasticsearch**
- What OS are you running grafana on? **Windows 7**

**Comment by torkelo** [comment]
you index name is ecommerce, you specified `[ecommerce]` , that could be one problem. 

Please include the query sent to Elasticsearch and the Elasticsearch resposne, you find these in chrome dev tools network tab.
