### ISSUE TITLE
[Bug] singlestat panel shows NaN instead of 0

### ISSUE THREAD

**Issue by mmlb** [grafana/grafana#7445]
Please include this information:
- What Grafana version are you using?
4.1.1 (docker image)
- What datasource are you using?
prometheus
- What OS are you running grafana on?
Arch Linux
- What did you do?
Single stat graph of an apc exporter stat
- What was the expected result?
`0s`
- What happened instead?
`NaN ns`

Maybe a regression of #1039?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query

![2017-02-03-104035_1718x1394_scrot](https://cloud.githubusercontent.com/assets/708570/22597348/3ca98844-e9fd-11e6-8c67-1803ded5cc0b.png)
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Not sure how to get the raw query from chrome dev tools except from seeing it in the tooltip in the above screenshot. Here is the raw response.

```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"apcupsd_battery_time_on_seconds","hostname":"manny","instance":"localhost:9162","job":"apcupsd","model":"Back-UPS ES 750","ups_name":"manny"},"values":[[1486136007,"0"],[1486136011,"0"],[1486136015,"0"],[1486136019,"0"],[1486136023,"0"],[1486136027,"0"],[1486136031,"0"],[1486136035,"0"],[1486136039,"0"],[1486136043,"0"],[1486136047,"0"],[1486136051,"0"],[1486136055,"0"],[1486136059,"0"],[1486136063,"0"],[1486136067,"0"],[1486136071,"0"],[1486136075,"0"],[1486136079,"0"],[1486136083,"0"],[1486136087,"0"],[1486136091,"0"],[1486136095,"0"],[1486136099,"0"],[1486136103,"0"],[1486136107,"0"],[1486136111,"0"],[1486136115,"0"],[1486136119,"0"],[1486136123,"0"],[1486136127,"0"],[1486136131,"0"],[1486136135,"0"],[1486136139,"0"],[1486136143,"0"],[1486136147,"0"],[1486136151,"0"],[1486136155,"0"],[1486136159,"0"],[1486136163,"0"],[1486136167,"0"],[1486136171,"0"],[1486136175,"0"],[1486136179,"0"],[1486136183,"0"],[1486136187,"0"],[1486136191,"0"],[1486136195,"0"],[1486136199,"0"],[1486136203,"0"],[1486136207,"0"],[1486136211,"0"],[1486136215,"0"],[1486136219,"0"],[1486136223,"0"],[1486136227,"0"],[1486136231,"0"],[1486136235,"0"],[1486136239,"0"],[1486136243,"0"],[1486136247,"0"],[1486136251,"0"],[1486136255,"0"],[1486136259,"0"],[1486136263,"0"],[1486136267,"0"],[1486136271,"0"],[1486136275,"0"],[1486136279,"0"],[1486136283,"0"],[1486136287,"0"],[1486136291,"0"],[1486136295,"0"],[1486136299,"0"],[1486136303,"0"],[1486136307,"0"]]}]}}
```

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
looks like prometheus is return strings instead of number values strange.

**Comment by torkelo** [comment]
hm.. looks like that is normal for Prometheus. What are your options in the Options tab?

**Comment by mmlb** [comment]
I've got other graphs that are fine with the string'ed numbers. Side note: I was able to hack around the NaN by changing query to `+ 0.00001`  which will then show `ms` or `ns` (can't remember) and the added a mapping to map the tiny value to `0`, but that's an obviously ugly hack. Nothing weird in options AFAICS
![2017-02-03-110220_1718x1394_scrot](https://cloud.githubusercontent.com/assets/708570/22598131/7240dcca-ea00-11e6-8957-efa67f9f2746.png)

**Comment by mmlb** [comment]
Also I'm using this dashboard fwiw: https://github.com/mdlayher/grafana/blob/master/servnerr2apcupsd.json

**Comment by int3l** [comment]
@mmlb I just mapped the value **0** to the string "**0 s**" via the **Value Mappings** tab.
Unfortunately this approach requires manual entering of the unit name, because Grafana doesn't append it for the duration unit...

**Comment by torkelo** [comment]
think this is fixed in v7
