### ISSUE TITLE
[Query?Bug?] Cannot add more then 6 items to a graph

### ISSUE THREAD

**Issue by rashtisouciance** [grafana/grafana#7446]
Hello,

I am running Grafana with InfluxDB as my data source. I am gathering docker metrics from a host and on that host there are more than 6 containers deployed. I want to graph out the memory usage. If I graph container separately then I get 12 individual graphs.

However if I want to combine them into a single graph Grafana limits it to 6 containers only. No matter what kind of graph I try to draw I hit a maximum of 6. Is this is Grafana limit or Telegraf/InfluxDB setting?

I am using grafana 4.1.1
I am using influxdb
I am running inside docker on AMI linux
I was hoping to draw all 12 containers on single graph. 

Otherwise awesome tool ;) Even more awesome with the new alerting feature.

**Comment by torkelo** [comment]
Must be a limit in your query or InfluxDB setting, never herd of anyone having this problem. 

There is no limit in Grafana

**Comment by rashtisouciance** [comment]
The query itself returns all containers which are in total 19. There are values for the rest as I can definitely draw them individually but when you combine them you can only see maximum six at once. See the screenshot where the query returns more than six containers but the graph only draws first six. 
![screenshot023](https://cloud.githubusercontent.com/assets/13943280/22608691/4116f55e-ea5e-11e6-81e6-3b60bf5df57b.png)

**Comment by torkelo** [comment]
I can send you metric query only returns 6 series, maybe there are tags for more but only data for 6 series for the time range. 

As I said you this is a  issue with your query.  If you don't believe me just check the raw response frok InfluxDB using chrome dev tools network tab, there you Can  find the raw query sent to influxdb and it's response

**Comment by rashtisouciance** [comment]
Thanks I will look into the query more. A strange one.
