### ISSUE TITLE
Unable to update plugins with previous invalid signature

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#74462]
When a plugin has an invalid signature it is blocked from loading and being installed/managed through the catalog. 

If the plugin is updated to include a valid signature then the user is still blocked from updating. 

![Image](https://github.com/grafana/grafana/assets/19860021/b98f41ba-d9ab-4ea2-aa1e-53ed4a5cb7be)

This _should_ be an relatively uncommon scenario, and more so once our plugin validator has its new check, so documentation / FAQ / Community post may suffice.

The remediation is to update the plugin via Grafana.com or potentially the CLI.

To reproduce:
- Navigate to https://grafana.com/grafana/plugins/operato-windrose-panel/?tab=installation
- Select `Version 1.1.0` 
<img width="262" alt="Screenshot 2024-01-12 at 15 04 13" src="https://github.com/grafana/grafana/assets/19860021/4e405be2-3733-4fe5-8904-34c41d927db7"> 

- install into your instance

Somewhat related issue - #45281

**Comment by sympatheticmoose** [comment]
@josmperez I think this might make more sense as a doc update or community post for now. https://grafana.com/docs/grafana/latest/administration/plugin-management/ or https://grafana.com/docs/grafana-cloud/introduction/find-and-use-plugins/ are our main install pages for plugins. I'm not totally convinced it makes sense to update either. Do you have any alternative suggestions or should I just raise a question on the forum and answer it myself?

**Comment by josmperez** [comment]
@sympatheticmoose  Hi, I don't recall seeing the notification for this mention of me in my inbox. In the future, feel free to assign me an issue if it's clearly related to plugin docs, and this will ensure it gets onto my GitHub dashboard.
