### ISSUE TITLE
Snapshot config option or URL parameter for "kiosk" mode [Feature request]

### ISSUE THREAD

**Issue by Codelica** [grafana/grafana#7447]
Please include this information:
- What Grafana version are you using?  4.1.1
- What datasource are you using?  InfluxDB
- What OS are you running grafana on?  Ubuntu 16.04

The addition of kiosk mode is great, but (correct me if I'm wrong), there isn't a way to trigger it other then keystrokes currently. (or embedding some JS which feels a little hackish)  I'd love to be able to have a snapshot option to load the dashboard in kiosk mode or a url param to do it.  Use case is for automated signage that isn't going to be supplying the keystrokes needed.

Thanks for listening...  :)

**Comment by xginn8** [comment]
Does the `kiosk=true` url param not accomplish this feature?

**Comment by Codelica** [comment]
Excellent!  Sorry I didn't see that option in my searches...
