### ISSUE TITLE
[Feature request] Embed mode: Add parameter to disable editing

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#7450]
- What Grafana version are you using?: 4.1
- What datasource are you using? Graphite, InfluxDB, Elasticsearch
- What OS are you running grafana on? RedHat 6.8
- What did you do? Embed a panel into Icingaweb2 per performance metric
- What was the expected result? Only graph viewing capabilities, not editing
- What happened instead? Clicking the head of the panel opens the edit bar and you can do the usual actions like view, edit, ...

```
<iframe src="https://ourdomain.com/grafana/dashboard-solo/db/icinga2-graphiteplugin-metric-link?from=1486185993015&to=1486207593015&var-METRIC=icinga2.our_host.services.Login.selenium_host_login.perfdata.loginTime.value&theme=light&panelId=1" width="450" height="200" frameborder="0"></iframe>
```

We would need another parameter in the url like "&editing=false" which prevents all manipulation of the panel/graph and only allow zooming/viewing.
It isn't possible for us to change privileges of the anonymous user as we have an external auth system (based on headers) needing it this way.

Using the builtin dashboard options "Editable" we get pretty close but it would also be great to disable the clickable header.

Currently it looks like this in icingaweb2:
![2017-02-04 14_04_40-icinga web](https://cloud.githubusercontent.com/assets/124109/22618672/094c2812-eae3-11e6-9618-ddf94a42f012.png)

**Comment by danmackin** [comment]
+1!

**Comment by noamha** [comment]
+1

**Comment by MartinMikita** [comment]
+1

**Comment by roy651** [comment]
+1

**Comment by dyachuk** [comment]
+1

**Comment by EdmondKong** [comment]
+1

**Comment by jmcarvalho** [comment]
+1

**Comment by Codyooo** [comment]
+1

**Comment by ahmednafies** [comment]
+1

**Comment by djvulee** [comment]
+1, any updates?

**Comment by MRakeshHarsha** [comment]
+1

**Comment by jangojam** [comment]
+1

**Comment by laundmo** [comment]
i solved this automatically logging in a "viewer" role user (cant edit, cant change anything, only able to change time range and color temporarily) https://github.com/grafana/grafana/issues/13706#issuecomment-540958284

**Comment by ajayit28** [comment]
Hi,

Is there any update on this?

Thanks in Advance!

**Comment by zerog981** [comment]
+1

**Comment by bersace** [comment]
Would be nice if we could embed a full grafana dashboard with date picker, refresh selector and NOT kiosk selector, dashboard name and search dialog, no way to escape kiosk, no variable edition. Does anyone have this requirements ?

Regards
