### ISSUE TITLE
[Feature request] Wildcard search on not_analyzed fields for Elasticsearch datasource

### ISSUE THREAD

**Issue by mbraeger** [grafana/grafana#7451]
Grafana version: 4.1.1 
Datasource: Elasticsearch - Native Plugin v. 3.0.0
OS: linux

# Problem
With the current Elasticseach datasource plugin it is not possible to use wildcards in the Lucene query for `not_analyzed` fields. This concerns at least Elasticsearch version 2.3.

The reason is that the current `query_string` created by the plugin is not specifying `lowercase_expanded_terms: false`

## Lucene query example
```
computer:cs-ccr-*
```

# Resolution
The problem can easily be fixed by adding to [query_buider.js](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/query_builder.js) the missing `query_string` option 

See also Elasticsearch documentation:
 https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html

**Comment by mbraeger** [comment]
I have a patch ready, if you are interested.

**Comment by lpic10** [comment]
I can see this option was removed on Elasticsearch 5.x, do you know what is the behavior in it?

**Comment by mbraeger** [comment]
No, I did not have the time to test the behaviour with Elasticsearch 5.x. We currently still use 2.3, but I will try to make a quick test within the next days.

**Comment by cherweg** [comment]
I´s only a deprecation:
[https://github.com/elastic/elasticsearch/blob/14d2b122a1b91ba14fc13fbb103e553cfddd5778/core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java#L95-L99](url)

I tried to write a feature to configure the query_term options ... take a look :
https://github.com/grafana/grafana/pull/7709

regards
Christian

**Comment by DvirM** [comment]
Hi Guys,

Any updates on this?

**Comment by cherweg** [comment]
Maybe someone could review my pull request?
It´s a working solution, but not the cleanest or best solution for sure. Perhaps we could make easier to merge.

(If this is the reason not to merge)

regards
christian

**Comment by torkelo** [comment]
since this option was removed in Elastic 5.x closing this seems appropriate
https://github.com/elastic/elasticsearch/issues/9978
