### ISSUE TITLE
SHA256 of 10.1.1 OSS standalone Linux binaries doesn't match

### ISSUE THREAD

**Issue by hasso** [grafana/grafana#74514]
### What happened?

I download 10.1.1 OSS edition standalone Linux binaries as stated in https://grafana.com/grafana/download/10.1.1?edition=oss, but SHA256 of tarball isn't the stated one 4b8d22ba6419a08d631ddbd543683a774f62b39e257fcda83cd1089063075ec1.

```
$ wget https://dl.grafana.com/oss/release/grafana-10.1.1.linux-amd64.tar.gz
--2023-09-07 11:43:55--  https://dl.grafana.com/oss/release/grafana-10.1.1.linux-amd64.tar.gz
Resolving dl.grafana.com (dl.grafana.com)... 151.101.246.217
Connecting to dl.grafana.com (dl.grafana.com)|151.101.246.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109275125 (104M) [application/x-tar]
Saving to: ‘grafana-10.1.1.linux-amd64.tar.gz’

grafana-10.1.1.linux-amd64.tar. 100%[=====================================================>] 104.21M  11.3MB/s    in 9.5s

2023-09-07 11:44:05 (10.9 MB/s) - ‘grafana-10.1.1.linux-amd64.tar.gz’ saved [109275125/109275125]

$ shasum -a 256 grafana-10.1.1.linux-amd64.tar.gz
9a3168007cc5cdd26c56d6121c4c163f9b6012435c87dacf3d3fa7914f9768f6  grafana-10.1.1.linux-amd64.tar.gz
$
```

### What did you expect to happen?

I'd expect SHA256 hash to match with stated one.

### Did this work before?

.

### How do we reproduce it?

.

### Grafana platform?

None

**Comment by dronenb** [comment]
Yep, I have noticed this for the past few versions as well.

**Comment by kminehart** [comment]
We were investigating this and I believe we've found the culprit. It's definitely not anything malicious.

Locally, they are created just fine, but I with the extra caching involved in our build process, the sha256 stuff is being cached. Testing out a solution now. I just thought I'd comment and say that nothing has been hijacked or anything and that this was an unfortunate logic error on our part.

**Comment by zerok** [comment]
Rechecked and I think we got the underlying issue 🙂
