### ISSUE TITLE
[Feature Request] Update moment/Add moment-timezone

### ISSUE THREAD

**Issue by bmagistro** [grafana/grafana#7453]
Currently using Grafana 4.2.0-pre1; datasource is not applicable; OS Ubuntu 16.10;

Would like to have moment updated and moment-timezone added.  I was unable to find a way to include moment-timezone in the plugin ([clock-panel](https://github.com/grafana/clock-panel)) directly while moment is being included in grafana.  If someone knows how to do that I'm open to trying to make the changes.

Dependency: https://github.com/moment/moment-timezone/pull/444
Supports: https://github.com/grafana/clock-panel/pull/19
May support: Support custom timezone selection #558

**Comment by daniellee** [comment]
We won't be using moment in the future so closing this feature request.
