### ISSUE TITLE
@grafana/data datetime tests fail in node >18.13.0

### ISSUE THREAD

**Issue by vinodk99** [grafana/grafana#74533]
### What happened?

Frontend tests are failing on ppc64le:

`yarn test --watchAll==false
jest-haste-map: duplicate manual mock found: store.navIndex.mock
  The following files share their name; please delete one of them:
    * <rootDir>/public/app/features/connections/__mocks__/store.navIndex.mock.ts
    * <rootDir>/public/app/features/datasources/__mocks__/store.navIndex.mock.ts

jest-haste-map: duplicate manual mock found: index
  The following files share their name; please delete one of them:
    * <rootDir>/public/app/features/datasources/__mocks__/index.ts
    * <rootDir>/public/app/features/plugins/admin/__mocks__/index.ts

 FAIL  packages/grafana-data/src/datetime/formats.test.ts
  ● Date Formats › localTimeFormat

    expect(received).toBe(expected) // Object.is equality

    Expected: "MM/DD/YYYY, hh:mm:ss A"
    Received: "MM/DD/YYYY, hh:mm:ss A"

      15 |     );
      16 |
    > 17 |     expect(format).toBe('MM/DD/YYYY, hh:mm:ss A');
         |                    ^
      18 |   });
      19 | });
      20 |

      at Object.<anonymous> (packages/grafana-data/src/datetime/formats.test.ts:17:20)

  ● systemDateFormats › contains correct browser-localized date formats

    expect(received).toBe(expected) // Object.is equality

    Expected: "MM/DD/YYYY, hh:mm:ss A"
    Received: "MM/DD/YYYY, hh:mm:ss A"

      53 |   it('contains correct browser-localized date formats', () => {
      54 |     systemDateFormats.useBrowserLocale();
    > 55 |     expect(systemDateFormats.fullDate).toBe('MM/DD/YYYY, hh:mm:ss A');
         |                                        ^
      56 |     expect(systemDateFormats.fullDateMS).toBe('MM/DD/YYYY, hh:mm:ss.SSS A');
      57 |     expect(systemDateFormats.interval.millisecond).toBe('HH:mm:ss.SSS');
      58 |     expect(systemDateFormats.interval.second).toBe('HH:mm:ss');

      at Object.<anonymous> (packages/grafana-data/src/datetime/formats.test.ts:55:40)

 FAIL  public/app/core/components/SharedPreferences/SharedPreferences.test.tsx (15.914 s)
  ● SharedPreferences › saves the users new preferences

    Timed out in waitFor.

       8 |   input: HTMLElement,
       9 |   optionOrOptions: string | RegExp | Array<string | RegExp>
    > 10 | ) => await waitFor(() => select(input, optionOrOptions, { container: document.body }));
         |                   ^
      11 |
      12 | // Finds the parent of the Select so you can assert if it has a value
      13 | export const getSelectParent = (input: HTMLElement) =>

      at waitForWrapper (.yarn/cache/@testing-library-dom-npm-9.3.1-ec81dc9367-8ee3136451.zip/node_modules/@testing-library/dom/dist/wait-for.js:160:27)
      at public/test/helpers/selectOptionInTest.ts:10:19
      at .yarn/cache/tslib-npm-2.6.0-4d336a6824-c01066038f.zip/node_modules/tslib/tslib.js:169:75
      at Object.__awaiter (.yarn/cache/tslib-npm-2.6.0-4d336a6824-c01066038f.zip/node_modules/tslib/tslib.js:165:16)
      at selectOptionInTest (public/test/helpers/selectOptionInTest.ts:10:5)
      at public/app/core/components/SharedPreferences/SharedPreferences.test.tsx:157:29
      at fulfilled (.yarn/cache/tslib-npm-2.6.0-4d336a6824-c01066038f.zip/node_modules/tslib/tslib.js:166:62)`

### What did you expect to happen?

All tests suites should have passed.

### How do we reproduce it?
run yarn test --watchAll==false

### Environment (with versions)?

Grafana version: v10.1.1
User OS: RHEL 8.7
Arch: ppc64le
Any pointers to resolve this issue? Thanks!

**Comment by joshhunt** [comment]
Looks like this is failing for developers, regardless of arch, running Node 18, which is the only version of node we support for development + building. Strange that it passes in CI though.

Thanks for reporting - will investigate 👍🏻

**Comment by joshhunt** [comment]
Node 18.13.0 changed the behaviour of Intl.DateTimeFormat slightly that causes the specified tests to fail. Our [supported node version](https://github.com/grafana/grafana/blob/main/.nvmrc) specifically is 18.12.0. We plan on updating to Node 20 LTS when that is released next month, so rather that bumping our build images twice in quick succession, we'll fix this when we do that upgrade
