### ISSUE TITLE
TypeError: Cannot assign to read only property 'scalyrUrl' of object '#<Object>'

### ISSUE THREAD

**Issue by driedener** [grafana/grafana#74538]
### What happened?

When trying to add or edit a dataset datasource in the actual Grafana Cloud version, it's throwing an error. Reproducible on multiple machines and stacks.

https://github.com/scalyr/scalyr-grafana-datasource-plugin/issues/124

### What did you expect to happen?

Regular creating and editing of a the datasource.

### Did this work before?

Yes

### How do we reproduce it?

1. Add plugin to instance
2. Add a dataset datasource
3. Type any key in the _Name_ field

### Environment (with versions)?

Grafana: 10.2.0-60139
OS: macOS, Windows 11
Browser: Edge Version 116.0.1938.69

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

sentinelone-dataset-datasource (v3.1.2)

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by driedener** [comment]
I'm unable to add a datasource on play.grafana.org because I don't have the rights to. Maybe connect to them? https://github.com/scalyr/scalyr-grafana-datasource-plugin/issues/124

**Comment by driedener** [comment]
The issue has been fixed with the new version sentinelone-dataset-datasource (v3.1.3).
