### ISSUE TITLE
Cloud Monitoring: MQL query lost when switching to Builder mode 

### ISSUE THREAD

**Issue by asimpson** [grafana/grafana#74543]
If you have a MQL query and switch to Builder mode and then back to MQL mode the query is lost. This does not happen if you switch between MQL and SLO mode.

This is a regression from the behavior in `9.x` where the query was preserved.

https://github.com/grafana/grafana/assets/1048831/ccb00ec6-a229-4241-b9a5-c85924a659fd

**Comment by akarsh-jain-790** [comment]
@bossinc can you assign this issue to me?

**Comment by asimpson** [comment]
@akarsh-jain-790 we're still not done figuring out how we want to address this particular issue. We'll update the card when we have a more concrete plan in place.

**Comment by alyssabull** [comment]
This is fixed by https://github.com/grafana/grafana/pull/76836.
