### ISSUE TITLE
Prometheus: White spaces tricks the autocomplete system.

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#74560]
This is something that we noticed when using the Lezer parser for TraceQL. When there are white spaces in front of the cursor, the Lezer parses often gets confused on which node of the abstract tree we are, thus making the autocompletion system potentially suggests wrong or no options.

Example:
![image](https://github.com/grafana/grafana/assets/135109076/4903cc68-7832-413b-b7e4-3fad1ff76be2)
![image](https://github.com/grafana/grafana/assets/135109076/5e697383-ff99-406a-bc13-5c40d00d4d39)

**Comment by itsmylife** [comment]
This is not happening with Prometheus anymore. 
Related PR https://github.com/grafana/grafana/pull/85942
