### ISSUE TITLE
Loki Autocomplete: White spaces tricks the autocomplete system.

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#74561]
This is something that we noticed when using the Lezer parser for TraceQL. When there are white spaces in front of the cursor, the Lezer parses often gets confused on which node of the abstract tree we are, thus making the autocompletion system potentially suggests wrong or no options.

Example: 
<img width="939" alt="image" src="https://github.com/grafana/grafana/assets/135109076/ac49db3e-ba62-49fe-8984-9c4ab3bda9ef">
<img width="960" alt="image" src="https://github.com/grafana/grafana/assets/135109076/99054ae9-0e37-4809-91d4-7ee1f9f2c94c">

**Comment by gtk-grafana** [comment]
Looks like we have the same problem in Prometheus: https://github.com/grafana/grafana/issues/74560.
I'll take a look at these both and see if we can find a solution.

**Comment by gtk-grafana** [comment]
Ok, I was confused in the meeting earlier today, we weren't trimming whitespace, but we did find a bug where the "cursor" position passed into lezer was always at the end of a text selection, as opposed to the front.
https://github.com/grafana/grafana/issues/70562

This appears still to be an issue in loki, so maybe I can pull in what we did for prom here as part of this fix.

**Comment by gtk-grafana** [comment]
Monaco is finicky as always: 
<img width="993" alt="image" src="https://github.com/grafana/grafana/assets/109082771/778dded7-fc92-418f-b767-c62174cb36f7">
<img width="510" alt="image" src="https://github.com/grafana/grafana/assets/109082771/f3adadf4-85a5-4a01-b4b5-40ca6a70faa4">
It's simple enough to strip out whitespace and update the cursor position, but Monaco seems to realize it's in a label value node without the preceding `=`, so while this solves the problem surfaced in this issue, it opens autocomplete to create invalid queries.

**Comment by gtk-grafana** [comment]
Taking a look at how this was solved with Tempo in https://github.com/grafana/grafana/pull/73707/files.

**Comment by gtk-grafana** [comment]
Moving back to backlog as this requires much more effort then originally estimated.
