### ISSUE TITLE
[Feature request] In playlists, render next dashboard before switching to it

### ISSUE THREAD

**Issue by nyerup** [grafana/grafana#7458]
When using playlists on a common screen, the experience gets visually "loud" whenever the playlist switches to a new dashboard. It would be great if the switch could wait until the browser is done rendering the new dashboard, so that playlists could get to be almost as smooth an experience as a single, auto-updating dashboard.

Thanks to @bergquist for a great talk on FOSDEM '17.

**Comment by torkelo** [comment]
what do you mean visually loud? It switches instantly. You mean load the dashboard and issue all metric queries and wait for them to finish before switching? That is going to be insanely complicated to do with almost no gain (dashboards load nearly instantly anyway)

**Comment by nyerup** [comment]
On our screen (powered by an RPI) the screen goes black, and takes a while (hundreds of milliseconds) to repopulate – especially if the graphs render data that takes a while to load from Grafana's data source. This causes the screen to unnecessarily attract attention when the playlist switches between dashboards. As a consequence, we've stopped using the playlist feature.

I realise this is probably a lot of work for a modest gain, and I don't think I have the skills to provide a patch. Are you interested in a screencast, or will this remain closed as a wontfix?

**Comment by torkelo** [comment]
I just don't see a way to implement it (that does not require massive changes and new complexity)

**Comment by nyerup** [comment]
All right.
