### ISSUE TITLE
Dashboards: Repeat a panel on DS variable display the same data in all repeated panels

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#74605]
### What happened?

Repeated panels are repeating the panel state for the first result rather than each selected variable value.
The customer has set up a dashboard variable returning each Loki datasource on their instance, by which the repeated panels are driven.
When selecting multiple values for this variable, the expected behaviour is a panel for each value showing that datasources logs. Instead the first result only displays and is repeated by n values selected. 

### What did you expect to happen?

Every repeated panel displays different data because they point to different data sources

### Did this work before?

Not sure

### How do we reproduce it?

1. Go to https://play.grafana.org/d/bb9123ce-ed4c-4ddc-aa57-cf361f3dec4e/repeat-on-loki-datasource-variable?orgId=1&editIndex=0&var-loki_ds=grafanacloud-alert-state-history&var-loki_ds=grafanacloud-logs&var-loki_ds=rfPVhrTVk 
2. Unticking all multi-value items on the dashboard variable
3. Resetting the initial panel back to any loki datasource from `loki_ds`
4. Unapplying and reapplying the repeated behaviour for the panel to loki_ds
5. Readding values to multi-value dropdown

You can see the same data in every panel

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Loki

**Comment by redbaron** [comment]
> Did this work before?
> Not sure

In your own words, it did work perfectly fine: https://github.com/grafana/grafana/pull/53521#pullrequestreview-1068215096

**Comment by polibb** [comment]
@redbaron Not sure what you mean. The linked comment is entirely not what this issue is about.

**Comment by polibb** [comment]
Neither I, nor @axelavargas can reproduce this 🤔. We did, however, reproduce a different important bug - the page freezing when you deselect all values. We will look into that for now.

**Comment by redbaron** [comment]
> @redbaron Not sure what you mean. The linked comment is entirely not what this issue is about.

It is the same bug, no? The title is incorrect. It is not that repeated panel displays same data, it is that it is impossible to select DS variable as datasource in a panel configured as repeat for that variable.

**Comment by redbaron** [comment]
>  Because I don't see a bug there?

There is a bug, but not on the screenshot.

1. Select multiple ds_var values
2. Try creating new panel repeated over that ds_var , you can't because in datasource selector there is no ds_var

As suggestes workaround , which took _days_ to find  , only single value has to be selected. When multiple values are selected neither creating new repeated panels nor editing datasource of existing   repeated panels is possibe: dropdown simply doesn't list ${ds_var}

**Comment by axelavargas** [comment]
Hello @redbaron 👋🏾, thank you for taking the time to provide the steps to reproduce the issue. You're correct that the title of this current GitHub issue doesn't match the problem you've described. The issue you're experiencing was previously mentioned in another [report](https://github.com/grafana/grafana/issues/16543#issuecomment-1181633895). To provide better clarity, we've created a new, separate GitHub issue for it: [Issue #74849](https://github.com/grafana/grafana/issues/74849).

As for the current issue about repeating panels displaying the same data, we're actively investigating it but haven't been able to reproduce the problem yet.

We will update both this current issue and the new one with our findings 😄.

Thank you 🙏🏾.

**Comment by polibb** [comment]
@redbaron I see now. Yes, this is a whole other bug 📝. Please open an issue for it reproducing the steps you do to encounter it, and we will look into it.

**Comment by dprokop** [comment]
@ivanortegaalba I've tried to reproduce this locally using a test data source variable, and I couldn't make this bug appear. Any chance you can provide a test dashboard that can be used locally for reproduction and debugging this?
