### ISSUE TITLE
Rendering: dashboard screenshots are overlapping due to resize animation

### ISSUE THREAD

**Issue by dnwe** [grafana/grafana#74603]
### What happened?

Since [v10.1.0](https://github.com/grafana/grafana/releases/tag/v10.1.0) (https://github.com/grafana/grafana/pull/67953) when taking screenshots of panels through the web browser, the animation is triggered causing the panels to overlap at the point the screenshot is taken:

![image](https://github.com/grafana/grafana/assets/8060970/c375aff8-2dfe-4645-9495-e74d6048bad0)

### What did you expect to happen?

Panels should remain spaced out when a screenshot is taken by the browser

### Did this work before?

Before 10.1.0 this wasn't an issue as there was no animated effect on page resize

### How do we reproduce it?

1. Open a grafana dashboard in (e.g.,) Google Chrome and allow it to complete loading
2. Use the 'Capture Full Page' / 'Capture Screenshot' / 'Capture Node' functionality
3. Note that the panels are overlapping

This is exactly the same problem that was described in https://github.com/grafana/grafana/pull/73190, but the fix there was a workaround for [grafana-image-renderer](https://github.com/grafana/grafana-image-renderer) which simply disables the animations if the user context indicates the browser was authenticated by a renderKey cookie. Ideally we need a more generic way of skipping the animation

### Environment (with versions)?

Grafana: [10.1.1](https://github.com/grafana/grafana/milestone/458)
OS: any
Browser: any

### Grafana platform?

None

**Comment by evictorero** [comment]
Hi Dominic, thanks for reporting this.
I was able to reproduce it with this [dashboard](https://github.com/grafana/grafana/files/12597755/dashboard.json.txt) and recorded a video. 

https://github.com/grafana/grafana/assets/20256983/d6616675-d97b-40dc-8372-b9fe4d3b48e6

**Comment by dnwe** [comment]
I added https://github.com/grafana/grafana/pull/75540 as one option to potentially provide a means to workaround this issue (for headless browser capture e.g., using `--force-prefers-reduced-motion`) and to provide better accessibility for users

**Comment by dnwe** [comment]
@dprokop any thoughts on the above proposal?

**Comment by ivanortegaalba** [comment]
Hi @dnwe, I see the PR you proposed is merged. Can we consider this bug resolved?

**Comment by dnwe** [comment]
Yep it is working well with the workaround PR merged and "prefer reduced motion" enabled in-browser

**Comment by juanicabanas** [comment]
Hi @dnwe . I wonder where you set `--force-prefers-reduced-motion` flag.
We're facing the same issue with Grafana Image Renderer Service and, as far as I know, the browser applies the CSS media query you added based on the OS device preference.
Thanks!
