### ISSUE TITLE
[Bug] InfluxDB Alerting doesn't support template variables in groubpy time interval

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#7461]
I am operating Grafana v4.1.1 with InfluxDB 1.0.2 on Debian testing, 64 bit. In my dashboards I have set up the "Group by time interval" field using a template variable, in my case called `$resolution`. When defining alerting on a graph that is set up this way, the `$resolution` variable is not replaced in the query that is sent to the database, therefore triggering a 400 bad request through a syntax error.

What is sent to the influxdb server is e.g.:

```
GET /query?db=diamond&epoch=s&q=SELECT+mean%28%22value%22%29+%2A+-1+%2B+100+FROM+%22diskspace%22+WHERE+%22counter%22+%3D+%27byte_percentfree%27+AND+time+%3E+now%28%29+-+5m+GROUP+BY+time%28%24resolution%29%2C+%22device%22+fill%28null%29
```

Where `%24resolution` is the non-replaced templating variable.

The original query I am using for the graph is:
```
SELECT mean("value") * -1 + 100 FROM "diskspace" WHERE "counter" = 'byte_percentfree' AND $timeFilter GROUP BY time($interval), "device" fill(null)
```
And the "group by time interval" field looks like this:
<img width="440" alt="screen shot 2017-02-05 at 17 11 04" src="https://cloud.githubusercontent.com/assets/1336287/22627597/1c8697d0-ebc6-11e6-905d-d61dc0c2cebf.png">

**Comment by languitar** [comment]
Hm, ok, but this only seems to happen the first time I press the test button for an alert. Subsequent calls (maybe after some time?) seem to work well later.

**Comment by torkelo** [comment]
alerting does not support template variables. https://github.com/grafana/grafana/issues/6557  

You can use the built in variables $__interval and $__interval_ms    and you can set lower limits in group by time option, like `>2m`

**Comment by languitar** [comment]
Does that mean that I have to recreate dashboards just for the purpose of alerting in case my usual queries use template variables?

**Comment by torkelo** [comment]
yes, we recommend dashboards that are specifically designed for alerting rules. Generally creates better and more maintainable alerts.

**Comment by languitar** [comment]
Ok, thanks for the hint

**Comment by jportoles** [comment]
It seems like there was some kind of regression because on 4.0 I can absolutely get template based resolutions to work with alerts as @languitar described, but not so on 4.1/4.2.

**Comment by jportoles** [comment]
Confirmed: just downgraded a server from 4.2 to 4.0.2 and alerts with template based resolutions are working again.

**Comment by torkelo** [comment]
No, alerting has never supported template variables

**Comment by jportoles** [comment]
@torkelo it must have supported some of it by accident then. Test it yourself on 4.0.2 when you have moment, you'll see what I mean, place a template variable on the resolution field and see what happens when you set up and alert with it on 4.0.2 vs 4.2. I'm not dreaming this, I guarantee you are going to be surprised.

**Comment by torkelo** [comment]
Must be due to your query somehow working even though no string interpolation is going on. Or that a rawQuery form of your query was saved after interpolation done by the frontend. 

I assure you the backend alerting engine has never supported templating, the backend tsdb engine has no such concept.
