### ISSUE TITLE
[Feature Request] Log of user actions on alerts

### ISSUE THREAD

**Issue by kirthiss** [grafana/grafana#7462]
- What Grafana version are you using - 4.1
- What datasource are you using? - InfluxDB
- What OS are you running grafana on? - Ubuntu 16.04

An important requirement of the alerts & notifications feature is that we need to record and track the user activity on alerts - everytime an alert is paused or un-paused or when alert configuration is modified or even alert is deleted, we need to record the timestamp, user and the activity related to those events. The log files do not provide details on user actions other than the api/function that was called. This is a critical feature enforced by regulatory requirements.

Is this feature possible?

**Comment by bergquist** [comment]
We agree that this is critical. But right now we think this should not only be applied to alerts. We should make it possible to turn on revisioning for all dashboards if requested.

**Comment by kirthiss** [comment]
Very true. The user activity log as a whole is very critical to the application.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1504
