### ISSUE TITLE
[Bug] Wrong percentiles diplay

### ISSUE THREAD

**Issue by stgleb** [grafana/grafana#7464]
Please include this information:
- What Grafana version are you using?
     4.1.1
- What datasource are you using?
    Graphite
- What OS are you running grafana on?
     linux ubuntu 14:04 
- What did you do?
    Display latencies percentiles
- What was the expected result?
    percentiles to be sorted
       upper > upper_99 > upper_95 > upper_90
- What happened instead?

     upper < upper_99 < upper_95 < upper_90

I send latencies from my app to graphite and feeds grafana with data from there,  I've obversed that grafana displays percentiles in wrong wrong way because I expect upper to be maximum. I've compared with graphs from graphite web. Graphite web follows that rules and display percentiles correctly. I've checked numerical representation - this is wrong for grafana either.

**Comment by stgleb** [comment]
I've checked out, it is okay only when I order percentiles like

upper_50
upper_75
upper_90
...
upper

So in that case grafana displays it correctly. Could you explain why order of percentiles affects displayed values?

**Comment by torkelo** [comment]
sorting series is done in graphite
