### ISSUE TITLE
Bug - Limit of tags displayed in chart when grouped by

### ISSUE THREAD

**Issue by biker73** [grafana/grafana#7465]
Please include this information:
Version - 4.0, 4.1
Datasource - Influx
OS - RHEL 7

Create a dashboard using the graph to display a field metric for a number of objects.
The chart should display a line per object representing the selected field metric for the time period specified.
I originally thought this was a limit of 6 lines, however it seems random as another chart restricts it to just 3 regardless of the number of objects selected.  i have not yet found any logical reason and although I am using templated fields I have removed all variables and replaced with explicit values to test / reproduce.

So the query I have (I have changed object names to A-G but these are tags, what the tag is makes no difference).

SELECT mean(metric_field) FROM "default"."cpu" WHERE "host" =~ /A|B|C|D|E|F|G/ AND "cpu" = 'Average_cpu' AND $timeFilter GROUP BY time($interval), "host", "cpu"

This only displays data for A-F. 
I remove A, I get displayed data for B-G (this proves there is data for all objects).

If I add back A, I get only displayed data for A-F.
If I remove B I get displayed data for A + C-G.

I have also replaced the =~ with WHERE host = 'A' OR host = 'B' or host = 'C' etc. and the result is the same.

I have experimented with different tags and selected fields and the results are the same, always truncated to 6 results.

If i select TWO fields I can get 12 displayed lines, two per group by tag so this does seem to be a restriction on the number of tags selected / grouped by.

It is possible a configurable value has been introduced but I have gone back and tested V4.0 and this also has the same limitation.  If this is the case I have not yet come across such a setting.

The same query in influx directly returns data for all requested tag values (ie more than 6).

**Comment by torkelo** [comment]
maybe an issue with influxdb, grafana does not limit anything

**Comment by biker73** [comment]
>> The same query in influx directly returns data for all requested tag values (ie more than 6).

**Comment by torkelo** [comment]
You can look at he raw InfluxDB response using chrome dev tools network tab

**Comment by biker73** [comment]
Yes I was going to get on to that, I've influx on debug and the full http request seems fine with all requested tags. I will verify the response next. I had wondered if it was purely a display issue and not with the actual data.

Many thanks.

**Comment by biker73** [comment]
Also a correction, I've checked with V3 and same issue so it's not specific to V4 (if grafana related at all).

**Comment by torkelo** [comment]
it might be due to influxdb chunking introduced in influxdb 1.2

**Comment by biker73** [comment]
So the HTTP Request includes all tag values that grafana sends, however only a subset of these is returned in the response. I do not know whether grafana needs to make further requests until all data is returned, or whether there is something I need to do on the influx side. Chunking of data is usually requested until an end of data sequence is returned.

This looks in part related to an older point >> 3242

However if i query just a few seconds where there are very few data points (total 12 returned which is not all requested)  the same issue exists for me, ie only a few of the selected tag values are returned in the response.

looking in the influx 1.2 docs I do not see chunked=true in the request either.

I'll change the default max-row-limit but as the points in my chart are only 12 I don't see how this will help.

**Comment by biker73** [comment]
got a workaround.

**Comment by Zero3** [comment]
@biker73 care to share your workaround? I'm running into the exact same issue right now :(.

Did you figure out whether the issue is with Grafana or with InfluxDB?

**Comment by altech6983** [comment]
Yea you gotta love it when you are having the exact same problem (I am) and you get to the end and just get "got a workaround".

**Comment by altech6983** [comment]
Also from looking at the request I can see all tags being sent. I suspect that it has something to do with the max number of points returned by influx because if I set group by time to like 10m I get all the tags back.
