### ISSUE TITLE
Dashboard: ad hoc filter variable breaks with datasource variable

### ISSUE THREAD

**Issue by ThomasFOC** [grafana/grafana#74657]
### What happened?

In a dashboard when using a variable of "variable type" `datasource` a variable of "variable type" `adhoc` breaks.

### What did you expect to happen?

In a dashboard with a `datasource` variable we can use "adhoc filters" on all panels using the datasource.

### Did this work before?

We upgraded from Grafana version `9.5.2` to version `10.1.1`. Under `9.5.2` the ad hoc filters worked. In the new version `10.1.1` the adhoc filters do not work anymore.

### How do we reproduce it?

For reproducibility we assume there is an existing data source of type `loki` with name "Loki".

1. Create a new dashboard.
2. Create a variable of type `datasource` (works as intended): 
![image](https://github.com/grafana/grafana/assets/38452519/b58e5aae-2ebc-40e4-be75-628ba4dd6cce)
3. Build a panel of type `table` with the variable `${data_source}` as "Data source".
4. Within the table panel build a query to populate the table to get the "Column filter" / "Filter for value" signs in the table:
![image](https://github.com/grafana/grafana/assets/38452519/329a6632-98c1-4df3-815d-1887c4087f70)
5. Close the panel editor and click the "Filter for value".

This generates a new variable of type `adhoc`:
![image](https://github.com/grafana/grafana/assets/38452519/dd8d8032-e235-46c5-98f9-285c1d9e2ba1)
but the filtering is not applied to any other panels of the dashboard.

![image](https://github.com/grafana/grafana/assets/38452519/71a1ff39-0239-434a-99ea-b107b13e7b24)

You may want to create a "Logs" panel next to the "table" panel to view the results, but the above steps reproduce the behavior as small as possible.

The variable `${data_source}` is not selectable when creating a custom "Ad Hoc Filter" variable.

### Is the bug inside a dashboard panel?

The bug is not exactly located inside a dashboard panel.

We assume its because of the missing support of variables of  type `datasource` within the "Ad Hoc options" within the "Data source" field.

Using a table panel seem to provide the only (simpliest) possibility to generate an "Ad Hoc Filter" variable.

### Environment (with versions)?

Grafana: Grafana Version 10.1.1 as Docker image (REPOSITORY: grafana/grafana, TAG 10.1.1, IMAGE ID: 854e0474bbc1)
OS: Docker image OS
Browser: Microsoft Edge for Business, Version 116.0.1938.76 (Official Build) (64-Bit)

### Grafana platform?

Docker

**Comment by jasuade** [comment]
Hey @ThomasFOC, the issue was identified, fixed, and backported to 10.1.x:  https://github.com/grafana/grafana/pull/74192. Please, check again on this version once available

**Comment by ThomasFOC** [comment]
Hey @jasuade the solution looks promising. I'm looking forward to the next release 🥳

**Comment by mellieA** [comment]
@jasuade I'll close this as fixed, please open a new issue and reference this one if the update doesn't resolve it for you!
