### ISSUE TITLE
[Bug] Custom Configuration settings not taking effect 

### ISSUE THREAD

**Issue by spohn-acc** [grafana/grafana#7467]
Grafana version:
msg="Starting Grafana" logger=main version=4.1.1 commit=v4.1.1 compiled=2017-01-12T08:48:03+0000

Installed with rpm on AWS instance, running as a service.
Linux **** 4.4.30-32.54.amzn1.x86_64 #1 SMP Thu Nov 10 15:52:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Issue**:  The values defined in the custom file /etc/grafana/grafana.ini  are not taken effect.  The only way I found to make changes to the configuration was to edit this file: /usr/share/grafana/conf/defaults.ini which I believe is not best practice.  Why is it not picking up the values from the custom config file?

**Command running**:
/usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins

**Logs showing it read the file**
t=2017-02-06T12:55:03+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-02-06T12:55:03+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-02-06T12:55:03+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-02-06T12:55:03+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-02-06T12:55:03+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-02-06T12:55:03+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-02-06T12:55:03+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-02-06T12:55:03+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-02-06T12:55:03+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-02-06T12:55:03+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3

**Comment by DanCech** [comment]
Are you sure the syntax of the /etc/grafana/grafana.ini file is valid?

**Comment by torkelo** [comment]
Can you show your grafana.ini config line that is not taking effect? It is very likley that you just missing removing the comment symbol `;` from the start of the line (all lines starting with `; `are ignored)

**Comment by spohn-acc** [comment]
Thank you @torkelo !  It was the `;` that got me, so mentally glued to using `#` for comments.  Sorry for the trouble.
