### ISSUE TITLE
Bug# Alerts from Grafana, promothesis datasource not working

### ISSUE THREAD

**Issue by voodemsanthosh** [grafana/grafana#7468]
Hey,

I am planning to setup alerts from Grafana on haproxys. I am using promothesis datasource and trying to setup the alerts on haproxy responses.

alerts setup getting the below template unsupport issue as follow,
![image](https://cloud.githubusercontent.com/assets/5786198/22655023/57a32606-ec54-11e6-8c67-472ee70029bc.png)

Please let us to the resolve the issue

Please include this information:
- What Grafana version are you using?  v4.0.2
- What datasource are you using? promethesis
- What OS are you running grafana on? Unix
- What did you do?
- What was the expected result?
- What happened instead? alerts not triggering if threshold reached

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
template variables are not supported  (there is feature request to support template variables in alerting queries but it is not on any roadmap)

**Comment by voodemsanthosh** [comment]
do you have any tentative dates for supporting template variable? and is there any way to keep the alarms?

**Comment by torkelo** [comment]
No plans to support template variables (so no ETA), not sure what you mean keep alarms?

**Comment by voodemsanthosh** [comment]
If the haproxy-servers-haproxy having multiple graphs to show the request/response metrics. I want to set the alerts for each metrics graph threshold. If threshold is crossed I need to get the notification.

**Comment by torkelo** [comment]
Yes?

**Comment by voodemsanthosh** [comment]
Yes, how do i setup the alerts and that alert should send the notifications?

**Comment by JeromeVi** [comment]
Can you link the issue for supporting variables ? I would like to use it too. I can explain why if you want
