### ISSUE TITLE
Global user list clipped to 1000 users

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#7469]
Please include this information:
- What Grafana version are you using?  3.1.1
- What OS are you running grafana on?  Linux
- What did you do?
I tried to find a user in the global user list but could not find him. The user was found as user of a specific organisation. We have more than 1000 users, however when I ran the "/api/user" interface only 1000 json items with user info where returned. The server settings for the maximum allowed number of global users is set to -1 (no limit). This is problematic, because  I also have scripts that use this user list to send out mails etc. It turned out not to be complete :-(
- What was the expected result? I expect the API to return all global users (>1000)
- What happened instead? It only returned 1000 users

**Comment by nopzor1200** [comment]
Hi Paul, 
Unfortunately the admin user-list screen/API has a hard-coded limit of 1000 users. It's something we need to add pagination to. It's come up a few times recently. We can commit to an imminent fix shortly.

**Comment by bergquist** [comment]
![image](https://cloud.githubusercontent.com/assets/618863/22822574/47da1f02-ef80-11e6-8987-29616d20d5f4.png)

The above screenshot is a preview of how paging for the user list in admin will look like. This first version will show 1000 users per page. 1000 users means a lot of scrolling but to show less users per page we need to add the ability to do a free text search on user name and user email.

A new endpoint with paging parameters will be added to the api:

`/api/users/search?perpage=1000&page=2`

It returns:

```json
{
    "users": [...],
    "totalCount": 123
}
```

The current endpoint `/api/users` will also have the new parameters, perpage and page but only returns a list of users and not the total count. This is so as not to introduce a breaking change.

We will merge and build this on Monday and and make a new release 4.1.2 that includes this change.

**Comment by PaulKuiper** [comment]
Thanks that really helps us (we cannot add new users at the moment due to
this). I will inform our team to be ready for upgrading. Thanks for the
very quick response!

Paul Kuiper
