### ISSUE TITLE
AzureAD user not member of one of the required groups

### ISSUE THREAD

**Issue by NCekicX** [grafana/grafana#74700]
### What happened?

Hello Community,

i have read some reports here regarding the same error which is receive but didnt found the solution for me. Hopefully anyone of you can help.

I have configured in Azure the App for my Grafana instance to use openID Connect. The configs of the Azure App are as follows:
Authentication => WEB (URI´s: https://<grafana-domain>/login/azuread and https://<grafana-domain>
Certificates and Secrets => Secret has been created
Token configuration => email (token type: ID), family_name (token type: ID), given_name (token type: ID), groups (token type: ID)
API Permissions => i have added over "own API" the group for my app "Grafana Org Admin" which is also configured as allowed_groups. And under API Permissions i also habe the Microsoft Graph: email, openid, profile, user.read
App Roles: Grafana Org Admin, Grafana Viewer, Grafana Editor (in all of those groups i have put my user inside) and the group IDs are the same like in the manifest file:
[manifest.txt](https://github.com/grafana/grafana/files/12583987/manifest.txt)
[](url)

And this is my grafana configuration:
name: Grafana OIDC Login
    enabled: true
    allow_sign_up: false
    client_id: "((GF_AUTH_AZUREAD_CLIENT_ID))"
    client_secret: "((GF_AUTH_AZUREAD_CLIENT_SECRET))"
    scopes: openid email profile
    auth_url: https://login.microsoftonline.com/ID/oauth2/v2.0/authorize
    token_url: https://login.microsoftonline.com/ID/oauth2/v2.0/token
    allowed_groups: 751f9983-973e-49c9-bab0-82296f261f46, 634287bc-ecec-4245-9085-47112c29ccef, 7659f705-8a18-450e-a792-187b3dd41b71
    allowed_domains: company_domain
    allow_assign_grafana_admin: false
    use_pkce: false
    auto_login: false
    force_use_graph_api: false
    role_attribute_strict: true

And this i get when i access grafana :
logger=context userId=0 orgId=0 uname= t=2023-09-12T07:57:08.236193222Z level=error msg="login.OAuthLogin(get info from azuread)" error="user not a member of one of the required groups"
logger=context userId=0 orgId=0 uname= t=2023-09-12T07:57:08.236831308Z level=error msg="Request Completed" method=GET path=/login/azuread status=500 remote_addr=11.237.100.254 time_ms=312 duration=312.365498ms size=1366 referer=https://login.microsoftonline.com/ handler=/login/:name
logger=cleanup t=2023-09-12T08:02:02.977677253Z level=info msg="Completed cleanup jobs" duration=20.807658ms

### What did you expect to happen?

Succesfull login via openID Connect

### Did this work before?

No, this is the first implementation.

### How do we reproduce it?

1. Have a running Grafana instance
2. Register new App in AzureAD with the mentioned configs

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

**Comment by mellieA** [comment]
@NCekicX I'd suggest checking out the troubleshooting section in our docs for AzureAD. This could be related to a misconfigured or missing role or group https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#map-roles 

You can get help from other community members in our forum at community.grafana.com.
