### ISSUE TITLE
Can I hide series that are under a threshold?

### ISSUE THREAD

**Issue by psyciknz** [grafana/grafana#7471]
I use influxdb as the db, and have a internet usage table with host, direction and value.

A lot of the hosts have very little traffic - but never 0,  so wondering if there's a way of hiding, or rolling up traffic under a certain threshold?

Or could this be done by altering the influx query?  Currently it just:
SELECT non_negative_derivative(mean("value"), 1m) FROM "wifi" WHERE $timeFilter GROUP BY time($ginterval), "host", "direction" fill(none)

Could I just as add a where value > 1mb?

**Comment by torkelo** [comment]
I think influxdb has introduced some way to filter series based on min / max, nor sure, this is something other databases solve in the query so it's not something grafana does

**Comment by sadhen** [comment]
I have the same question. Using InfluxDB datasource, we are only permitted to use tag in "where" filters.
