### ISSUE TITLE
Prometheus: Variables Query Editor  - label filter disappears after selecting value

### ISSUE THREAD

**Issue by damslo** [grafana/grafana#74714]
### I was trying to set new variable:
![image](https://github.com/grafana/grafana/assets/123402182/c930db17-710a-4cf9-9e0f-8573073fa62d)

### Once I select something from list, label disappears.

![image](https://github.com/grafana/grafana/assets/123402182/20a3c848-fc85-4e41-b062-ffd3972d4163)

I'm using grafana 10.1.1, but I was also able to reproduce it on grafana sandbox https://play.grafana.org/

### What did you expect to happen?

Label stays in place

### Did this work before?

Probably yes

### How do we reproduce it?

1. create dashboard
2. create variable
3. select Prometheus data source
4. query type - Label values
5. select label
6. select label filter = select value
7. label filter will disappear

### Environment (with versions)?

Grafana: 10.1.1 (also in official sandbox)
OS: Windows
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by mellieA** [comment]
I was able to reproduce this too, thank you so much for the detailed steps AND reproducing it on play!

One extra step, for me the label filter appeared normal until I clicked **run query**

**Comment by bohandley** [comment]
Thank you for the issue and for your patience! Fixed in https://github.com/grafana/grafana/pull/76472
