### ISSUE TITLE
Alerting: Ms Teams error 413

### ISSUE THREAD

**Issue by iculda** [grafana/grafana#74724]
### What happened?

Hello,
When i tried to send some alerts to teams (190+ instances) it seems that teams responded with error

<img width="1415" alt="Screenshot 2023-09-12 at 14 54 10" src="https://github.com/grafana/grafana/assets/13196005/4a257d61-2b5e-4fda-94ba-a4e05e599e07">

### What did you expect to happen?

Alert being sent

### Did this work before?

no

### How do we reproduce it?

1. Create an alert with multiple instances(dimensions)
2.Create teams contact point
3.Try to send it

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1
OS: Docker
Browser:

### Grafana platform?

Docker

### Datasource(s)?

Azure Monitor

**Comment by mellieA** [comment]
@iculda it looks like this is a problem with the alert message being too large.

https://powerusers.microsoft.com/t5/General-Power-Automate/Error-413-RequestEntityTooLarge-Post-message-in-Teams-Channel/td-p/1653515
