### ISSUE TITLE
Don't updated values of legends below graph [bug]

### ISSUE THREAD

**Issue by nynax** [grafana/grafana#7474]
Version grafana: 4.1.1.
Data sourse: InfluxDB
OS: FreeBSD 10.3

When i do zoom in or zoom out on graph, value of legend (min, max, avg) don't refreshed. This is very  don't comfortable. I want, see value of legend only selected line segment. This is bug or feature?  Thank you for help.

**Comment by torkelo** [comment]
don't know what your doing wrong, the legend values always update and represent the current time range in the graph. 

Have you inspected your metric query and it's response? Please include the raw query sent to inflxudb and it's response. You find this in chrome dev tools network tab.

**Comment by nynax** [comment]
Request: 
http://dvictor.ru:3000/api/datasources/proxy/4/query?db=db_mining&q=SELECT%20value%20FROM%20userworkers%20WHERE%20type%3D%27hashrate%27%20AND%20username%3D%27nynax.crypto1%27&epoch=ms

Answer: 
{"results":[{"series":[{"name":"userworkers","columns":["time","value"],"values":[[1486299389000,56.95],[1486299419000,113.9],[1486299449000,137.08],...[1486462165000,277.91]]}]}]}

Video:
https://youtu.be/4RMyldUi3Ts

**Comment by torkelo** [comment]
your query does not have a time filter so you always get all data points. so the legend values never change. You need a time range condition in your query. If you switch to raw mode query mode (text box), you need to know what you are doing. There is a `WHERE $timeFilter` part there for a reason :)

**Comment by nynax** [comment]
Thank you very much. I'm innatentive newbie. You big guru!
