### ISSUE TITLE
Logs: Feature tracking is called too often

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#74740]
When using logs in Explore, the feature tracking is called too often. Displaying one log-result will e.g. call multiple `grafana_explore_logs_result_displayed` events:

https://github.com/grafana/grafana/assets/8092184/d9e816d9-9ba0-4227-a445-afbae38dfae7

Also in some occasions the `grafana_loki_query_executed` seems to be sent multiple times.

**Comment by gtk-grafana** [comment]
Looks like @ifrost fixed this in https://github.com/grafana/grafana/commit/e4ea62b3af673e4db686fc8684d81194eb48ed20
https://github.com/grafana/grafana/pull/74798. Closing out
