### ISSUE TITLE
CloudWatch Logs - Add support for regex

### ISSUE THREAD

**Issue by katebrenner** [grafana/grafana#74760]
**What would you like to be added**:

Add support for Regex
More info [here]( https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-cloudwatch-logs-regular-expression-filter-pattern-syntax-support/)

**Comment by iwysiu** [comment]
Do we need to do this? It seems like the regex at that link are for [metric filters](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html)/[subscription filters](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html)/ [filter log event](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SearchDataFilterPattern.html) which I don't think we support.
We already support the `/regex/` format that is in the CloudWatch Logs Insights query syntax: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax-examples.html .
