### ISSUE TITLE
[Feature request] Ability to delete datasources by name

### ISSUE THREAD

**Issue by jmdacruz** [grafana/grafana#7476]
Please include this information:
- **What Grafana version are you using?** Grafana v4.1.0 (commit: 98b648d) 
- **What datasource are you using?** InfluxDB, Elasticsearch
- **What OS are you running grafana on?** Ubuntu 14.04
- **What did you do?** Trying to delete a datasource by name, e.g., `DELETE /api/datasources/:datasourceName`
- **What was the expected result?** The datasource is deleted
- **What happened instead?** An error is returned

This kind of functionality would be useful for automation, when datasources need to be created and removed depending on other dependencies.

**Comment by utkarshcmu** [comment]
👍

**Comment by utkarshcmu** [comment]
Currently, even wizzy uses delete org by ID (https://utkarshcmu.github.io/wizzy-site/remote-commands/org-commands/) , but it make more sense to operate on orgs with names. So, creating an issue to change all org commands to use Names instead of IDs - https://github.com/utkarshcmu/wizzy/issues/83
