### ISSUE TITLE
Data Source: ID is used instead of database name when using Data Source Variables

### ISSUE THREAD

**Issue by keck-in-space** [grafana/grafana#74777]
### What happened?

An existing, working dashboard stopped working with the below error message occurring for every panel:

```
Status: 500. Message: db query error: Error 1146 (42S02): Table 'nYwx1e2zk.table_name' doesn't exist
```

`nYwx1e2zk` is the ID of the database given by Grafana.

### What did you expect to happen?

The existing dashboard would work as expected as there were no changes made to the dashboard or database.

### Did this work before?

Yes, it worked in this same dashboard on this same version of Grafana.

### How do we reproduce it?

1. Create a datasource variable named Database
2. Attempt to use the Database variable
3. The ID is used instead

### Is the bug inside a dashboard panel?

Yes. I can't share this as it is internal.

### Environment (with versions)?

Grafana: v10.1.1 (0cfa76b22d)
OS: Windows 10 / RHEL 8 (server)
Browser: Firefox 102.15.0esr (32-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

MySQL

**Comment by mellieA** [comment]
@keck-in-space does the datasource work if you go to the Connections > test datasource page? That test query also uses the datasource uid in the query. 

I tested this with Grafana 10.2 and a mySQL datasource. The query returns as expected using the datasourceUID in the query. 

I'd suggest two things: 

- Test the datasource and verify that nothing has changed there
- Query the mySQL database table directly with the same credentials used in grafana to make sure nothing has changed at the source

Please open a new issue and reference this one if you find a bug. If you find another explanation, it would be so nice to update this thread for others in the community who might learn from it.

**Comment by keck-in-space** [comment]
Very interesting. Maybe I need to update to Grafana 10.2.

1. Testing the data source returned "Database Connection OK"
2. Directly connecting to the MariaDB source worked fine using DBeaver and the same credentials.

I'll see what else I can figure out. Thanks!
