### ISSUE TITLE
Why Grafana Alert Rules always to request "/api/ruler/<datasource uid>/api/v1/rules/test/test"

### ISSUE THREAD

**Issue by wkshare** [grafana/grafana#74784]
### What happened?

/api/v1/rules/test/test

I'm not **test** namespace.
I'm not **test** groupname.

Why always to request the namespace and groupname?

```
{"msec": "1694586735.923", "connection": "448147", "connection_requests": "5", "pid": "4009743", "request_id": "055dac7c98ce82a40e84913676ff6b39", "request_length": "717", "remote_addr": "172.29.52.81", "remote_user": "", "remote_port": "49318", "time_local": "13/Sep/2023:01:32:15 -0500", "time_iso8601": "2023-09-13T01:32:15-05:00", "request": "GET /api/ruler/sre-Log-Syslog-OS/api/v1/rules/test/test HTTP/1.1", "request_uri": "/api/ruler/sre-Log-Syslog-OS/api/v1/rules/test/test", "args": "", "status": "404", "body_bytes_sent": "102", "bytes_sent": "355", "http_referer": "https://10.157.135.235:3000/alerting/list", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36", "http_x_forwarded_for": "", "http_host": "10.157.135.235:3000", "server_name": "", "request_time": "2.484", "upstream": "10.157.135.235:3030", "upstream_connect_time": "0.000", "upstream_header_time": "2.484", "upstream_response_time": "2.484", "upstream_response_length": "102", "upstream_cache_status": "", "ssl_protocol": "TLSv1.2", "ssl_cipher": "ECDHE-RSA-AES128-GCM-SHA256", "scheme": "https", "request_method": "GET", "server_protocol": "HTTP/1.1", "pipe": ".", "gzip_ratio": "", "http_cf_ray": ""}

```

### What did you expect to happen?

always return 404

### Did this work before?

-

### How do we reproduce it?

1. Open Grafana Web Portal
2. Click Alerting
3. Click Alert Rules

### Environment (with versions)?

Grafana: v8.5.4 and v9.4.3
OS: Oracle Linux 7.9
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Grafana Loki

**Comment by makeittotop** [comment]
I think the async js function responsible for triggering this is here - https://github.com/grafana/grafana/blob/4b7b323061a803125db161219c5452d7e2f27e6f/public/app/features/alerting/unified/api/ruler.ts#L95

We have 1000's of datasources registered in Grafana, and each one of them have 10s of alert rules, so in the end the grafana alert panel ends up making many thousands of api calls leading to issues like page crash/unresponsiveness/slowness etc. 

Among other issues I stumbled upon the above js call which is periodically looping over every datasource there is to make an API call to the fake "test/test" endpoint in the grafana backend  which _ALWAYS_ results in a 404. This is certainly adding significant overhead to the webpage performance, as well as the backend server to some extent.

Would someone be able to tell why do we have this running periodically in Grafana? What purpose does it server? And, is there a way to disable this?

**Comment by gillesdemey** [comment]
Hi! This is part of [our heuristics](https://github.com/grafana/grafana/blob/96b55ea37ccb11cb14170a795a2ec454757ee21a/public/app/features/alerting/unified/api/buildInfo.ts#L46-L106) to figure out if we are communicating with a data source that has a ruler API – one that allows us to create / update and delete alert rules via an HTTP API. 

I suspect most of your data sources are either an older version of Cortex, Loki or an older version of Prometheus that might not have a `/buildinfo` endpoint that can tell us if the ruler API is available and enabled. Can you give us some more information about what DBs and versions are running for those data sources?

There is currently no way to disable this behaviour. As for the impact on the rendering of the front-end, how long does it take on average to receive `404` from your data sources? This is usually negligible but when thousands of data sources are configured it might start to add up.

**Comment by wkshare** [comment]
@gillesdemey Thanks you response.
My Loki version is 2.6.1
Alright, I close this issue.

**Comment by makeittotop** [comment]
@gillesdemey You're right. I'm fairly new to loki and didn't have this insight about the buildinfo api endpoint. Looks like that our layer 7 lb didn't expose that endpoint to grafana. I've since asked it to be added to the lb frontend. Let's see how that goes.

Also, I've one more question - am I write in my hypothesis that currently there is no way to selectively call datasources from the client side by applying filtering on the alert panel page? Looks like grafana client side js fetches all ds rules everytime, and _then_ applies filtering on top of it?

**Comment by gillesdemey** [comment]
That is correct, we fetch all rules for all data sources by default but are planning a UI update to this view – we'll take this feedback in to account because the ability to only fetch rules from a particular set of data sources by default has come up before. 

You can also omit the data source entirely by disabling "Manage alert rules in Alerting UI" https://grafana.com/docs/grafana/latest/datasources/loki/configure-loki-data-source/#alerting
