### ISSUE TITLE
Grafana smtp notification error

### ISSUE THREAD

**Issue by vincent927** [grafana/grafana#7478]
I have setting grafana config smtp like this
![](http://ww1.sinaimg.cn/large/6e9a4d0bgy1fchs5iwgz6j20h305kt8t)

and i restart the grafana-server
 
but when i Alert notification, log output error

![qq 20170207121554](https://cloud.githubusercontent.com/assets/10399425/22677644/3aff2d7a-ed2f-11e6-9e6d-1f89616ce88f.jpg)

```
t=2017-02-07T12:04:01+0800 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=2.188 alertId=1 name="load alert" firing=false
t=2017-02-07T12:04:02+0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-02-07T12:04:12+0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-02-07T12:04:21+0800 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-02-07T12:04:21+0800 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[vincentl@ziztour.com]
t=2017-02-07T12:04:21+0800 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="gomail: could not send email 1: 501 mail from address must be same as authorization user"
t=2017-02-07T12:04:21+0800 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="gomail: could not send email 1: 501 mail from address must be same as authorization user"
t=2017-02-07T12:04:21+0800 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=192.168.1.6 time_ms=130ns size=48
```

- grafana 4.1.1
- datasource influxdb1.2
- os centos6.5

**Comment by torkelo** [comment]
you smtp server is giving errors. maybe change the from address so it match the gmail account?

**Comment by vincent927** [comment]
@torkelo 
Thanks .
I has solved the problem。

```
from_address = grafana@ziztour.com
```
notification test successful!

**Comment by kedarss** [comment]
@vincent927 , @torkelo 

I am facing the same issue. I am unable to send email. We are having Office365 exchange Server. What should be my settings in the defaults.ini file? Please Assist.

**Comment by daniellee** [comment]
@kedarss can you ask the question on the [community site](https://community.grafana.com/) as it is probably not a bug in Grafana. And please include the error from your Grafana server log and your current configuration in the custom.ini (just like vincent927 did in this issue).
