### ISSUE TITLE
[Bug] current value binding issue along with multiple legend

### ISSUE THREAD

**Issue by jieqian** [grafana/grafana#7479]
version: 4.1.1
datasource: influxdb
OS: centos6

The current value seems not binding to the line to which it belongs as I click the refresh button several times.
![image](https://cloud.githubusercontent.com/assets/4167422/22680692/4c6725a8-ed44-11e6-93ea-956568fa2e52.png)

![image](https://cloud.githubusercontent.com/assets/4167422/22680710/64d4516a-ed44-11e6-9760-38baa2b785ea.png)

The following is my metric query
![image](https://cloud.githubusercontent.com/assets/4167422/22680793/e8c26bd8-ed44-11e6-9381-41a6d78f1e9f.png)

**Comment by jieqian** [comment]
Hi, @torkelo 
I am the new user of grafana, so I am not sure if it is a bug or it is my ignorant to grafana.
And that would be appreciate to check this issue for me

**Comment by torkelo** [comment]
Please provide more info. Your first two screenshots, (showing the tooltip), why did you paste those? not seeing anything wrong in them. 

The legend `Current` value is the last value returned from your query. You can open chrome dev tools network tab to review the raw response from InfluxDB. If you still think the current displayed is not the same as the last value returned from influxdb then please past the info there and I will try my best to help you :)

**Comment by jieqian** [comment]
The tooltip value could be switched at the same time spot(14:36:50) when I refresh several times by clicking the button on the top right of this graph. The value is not always switch each time I refresh. 
And what else info do you want to know?

**Comment by torkelo** [comment]
I am not following you,  looks correct

**Comment by torkelo** [comment]
Oh, regarding more info I mentioned that, you need to look at the data your query returns

**Comment by jieqian** [comment]
**The first query**
`{"results":[{"series":[{"name":"xyz_klink_random_frontend_Controller_metric_p95","tags":{"service":"frontend"},"columns":["time","mean"],"values":[[1.48645092e+12,0],[1.48645093e+12,3],[1.48645094e+12,3],[1.48645095e+12,3],[1.48645096e+12,3],[1.48645097e+12,3],[1.48645098e+12,3],[1.48645099e+12,3],[1.486451e+12,3],[1.48645101e+12,3],[1.48645102e+12,3],[1.48645103e+12,3],[1.48645104e+12,3],[1.48645105e+12,3],[1.48645106e+12,3],[1.48645107e+12,3],[1.48645108e+12,3],[1.48645109e+12,3],[1.4864511e+12,3],[1.48645111e+12,3],[1.48645112e+12,3],[1.48645113e+12,3],[1.48645114e+12,3],[1.48645115e+12,3],[1.48645116e+12,3],[1.48645117e+12,3],[1.48645118e+12,3],[1.48645119e+12,3],[1.4864512e+12,3],[1.48645121e+12,3],[1.48645122e+12,3],[1.48645123e+12,3],[1.48645124e+12,3],[1.48645125e+12,3],[1.48645126e+12,3],[1.48645127e+12,3],[1.48645128e+12,3],[1.48645129e+12,3],[1.4864513e+12,3],[1.48645131e+12,3],[1.48645132e+12,3],[1.48645133e+12,3],[1.48645134e+12,3],[1.48645135e+12,3],[1.48645136e+12,3],[1.48645137e+12,3],[1.48645138e+12,3],[1.48645139e+12,3],[1.4864514e+12,3],[1.48645141e+12,3],[1.48645142e+12,3],[1.48645143e+12,3],[1.48645144e+12,3],[1.48645145e+12,3],[1.48645146e+12,3],[1.48645147e+12,3],[1.48645148e+12,3],[1.48645149e+12,3],[1.4864515e+12,3],[1.48645151e+12,3],[1.48645152e+12,3],[1.48645153e+12,3],[1.48645154e+12,3],[1.48645155e+12,3],[1.48645156e+12,3],[1.48645157e+12,3],[1.48645158e+12,3],[1.48645159e+12,3],[1.4864516e+12,3],[1.48645161e+12,3],[1.48645162e+12,3],[1.48645163e+12,3],[1.48645164e+12,3],[1.48645165e+12,3],[1.48645166e+12,3],[1.48645167e+12,3],[1.48645168e+12,3],[1.48645169e+12,3],[1.4864517e+12,3],[1.48645171e+12,3],[1.48645172e+12,3],[1.48645173e+12,3],[1.48645174e+12,3],[1.48645175e+12,3],[1.48645176e+12,3],[1.48645177e+12,3],[1.48645178e+12,3],[1.48645179e+12,3],[1.4864518e+12,3],[1.48645181e+12,3],[1.48645182e+12,3],[1.48645183e+12,3],[1.48645184e+12,3],[1.48645185e+12,3],[1.48645186e+12,3],[1.48645187e+12,3],[1.48645188e+12,3],[1.48645189e+12,3],[1.4864519e+12,3],[1.48645191e+12,3],[1.48645192e+12,3],[1.48645193e+12,3],[1.48645194e+12,3],[1.48645195e+12,3],[1.48645196e+12,3],[1.48645197e+12,3],[1.48645198e+12,3],[1.48645199e+12,3],[1.486452e+12,3],[1.48645201e+12,3],[1.48645202e+12,3],[1.48645203e+12,3],[1.48645204e+12,3],[1.48645205e+12,3],[1.48645206e+12,3],[1.48645207e+12,3],[1.48645208e+12,3],[1.48645209e+12,3],[1.4864521e+12,3],[1.48645211e+12,3],[1.48645212e+12,3],[1.48645213e+12,3],[1.48645214e+12,3],[1.48645215e+12,3],[1.48645216e+12,3],[1.48645217e+12,3],[1.48645218e+12,3],[1.48645219e+12,3],[1.4864522e+12,3],[1.48645221e+12,3],[1.48645222e+12,3],[1.48645223e+12,3],[1.48645224e+12,3],[1.48645225e+12,3],[1.48645226e+12,3],[1.48645227e+12,3],[1.48645228e+12,3],[1.48645229e+12,3],[1.4864523e+12,3],[1.48645231e+12,3],[1.48645232e+12,3],[1.48645233e+12,3],[1.48645234e+12,3],[1.48645235e+12,3],[1.48645236e+12,3],[1.48645237e+12,3],[1.48645238e+12,3],[1.48645239e+12,3],[1.4864524e+12,3],[1.48645241e+12,3],[1.48645242e+12,3],[1.48645243e+12,3],[1.48645244e+12,3],[1.48645245e+12,3],[1.48645246e+12,3],[1.48645247e+12,3],[1.48645248e+12,3],[1.48645249e+12,3],[1.4864525e+12,3],[1.48645251e+12,3],[1.48645252e+12,3],[1.48645253e+12,3],[1.48645254e+12,3],[1.48645255e+12,3],[1.48645256e+12,3],[1.48645257e+12,3],[1.48645258e+12,3],[1.48645259e+12,3],[1.4864526e+12,3],[1.48645261e+12,3],[1.48645262e+12,3],[1.48645263e+12,3],[1.48645264e+12,3],[1.48645265e+12,3],[1.48645266e+12,3],[1.48645267e+12,3],[1.48645268e+12,3],[1.48645269e+12,3],[1.4864527e+12,3],[1.48645271e+12,3],[1.48645272e+12,3]]}]},{"series":[{"name":"xyz_klink_random_frontend_Controller_metric_count","tags":{"service":"frontend"},"columns":["time","non_negative_derivative"],"values":[[1.48645092e+12,31],[1.48645093e+12,0],[1.48645094e+12,0],[1.48645095e+12,0],[1.48645096e+12,0],[1.48645097e+12,0],[1.48645098e+12,0],[1.48645099e+12,0],[1.486451e+12,0],[1.48645101e+12,0],[1.48645102e+12,0],[1.48645103e+12,0],[1.48645104e+12,0],[1.48645105e+12,0],[1.48645106e+12,0],[1.48645107e+12,0],[1.48645108e+12,0],[1.48645109e+12,0],[1.4864511e+12,0],[1.48645111e+12,0],[1.48645112e+12,0],[1.48645113e+12,0],[1.48645114e+12,0],[1.48645115e+12,0],[1.48645116e+12,0],[1.48645117e+12,0],[1.48645118e+12,0],[1.48645119e+12,0],[1.4864512e+12,0],[1.48645121e+12,0],[1.48645122e+12,0],[1.48645123e+12,0],[1.48645124e+12,0],[1.48645125e+12,0],[1.48645126e+12,0],[1.48645127e+12,0],[1.48645128e+12,0],[1.48645129e+12,0],[1.4864513e+12,0],[1.48645131e+12,0],[1.48645132e+12,0],[1.48645133e+12,0],[1.48645134e+12,0],[1.48645135e+12,0],[1.48645136e+12,0],[1.48645137e+12,0],[1.48645138e+12,0],[1.48645139e+12,0],[1.4864514e+12,0],[1.48645141e+12,0],[1.48645142e+12,0],[1.48645143e+12,0],[1.48645144e+12,0],[1.48645145e+12,0],[1.48645146e+12,0],[1.48645147e+12,0],[1.48645148e+12,0],[1.48645149e+12,0],[1.4864515e+12,0],[1.48645151e+12,0],[1.48645152e+12,0],[1.48645153e+12,0],[1.48645154e+12,0],[1.48645155e+12,0],[1.48645156e+12,0],[1.48645157e+12,0],[1.48645158e+12,0],[1.48645159e+12,0],[1.4864516e+12,0],[1.48645161e+12,0],[1.48645162e+12,0],[1.48645163e+12,0],[1.48645164e+12,0],[1.48645165e+12,0],[1.48645166e+12,0],[1.48645167e+12,0],[1.48645168e+12,0],[1.48645169e+12,0],[1.4864517e+12,0],[1.48645171e+12,0],[1.48645172e+12,0],[1.48645173e+12,0],[1.48645174e+12,0],[1.48645175e+12,0],[1.48645176e+12,0],[1.48645177e+12,0],[1.48645178e+12,0],[1.48645179e+12,0],[1.4864518e+12,0],[1.48645181e+12,0],[1.48645182e+12,0],[1.48645183e+12,0],[1.48645184e+12,0],[1.48645185e+12,0],[1.48645186e+12,0],[1.48645187e+12,0],[1.48645188e+12,0],[1.48645189e+12,0],[1.4864519e+12,0],[1.48645191e+12,0],[1.48645192e+12,0],[1.48645193e+12,0],[1.48645194e+12,0],[1.48645195e+12,0],[1.48645196e+12,0],[1.48645197e+12,0],[1.48645198e+12,0],[1.48645199e+12,0],[1.486452e+12,0],[1.48645201e+12,0],[1.48645202e+12,0],[1.48645203e+12,0],[1.48645204e+12,0],[1.48645205e+12,0],[1.48645206e+12,0],[1.48645207e+12,0],[1.48645208e+12,0],[1.48645209e+12,0],[1.4864521e+12,0],[1.48645211e+12,0],[1.48645212e+12,0],[1.48645213e+12,0],[1.48645214e+12,0],[1.48645215e+12,0],[1.48645216e+12,0],[1.48645217e+12,0],[1.48645218e+12,0],[1.48645219e+12,0],[1.4864522e+12,0],[1.48645221e+12,0],[1.48645222e+12,0],[1.48645223e+12,0],[1.48645224e+12,0],[1.48645225e+12,0],[1.48645226e+12,0],[1.48645227e+12,0],[1.48645228e+12,0],[1.48645229e+12,0],[1.4864523e+12,0],[1.48645231e+12,0],[1.48645232e+12,0],[1.48645233e+12,0],[1.48645234e+12,0],[1.48645235e+12,0],[1.48645236e+12,0],[1.48645237e+12,0],[1.48645238e+12,0],[1.48645239e+12,0],[1.4864524e+12,0],[1.48645241e+12,0],[1.48645242e+12,0],[1.48645243e+12,0],[1.48645244e+12,0],[1.48645245e+12,0],[1.48645246e+12,0],[1.48645247e+12,0],[1.48645248e+12,0],[1.48645249e+12,0],[1.4864525e+12,0],[1.48645251e+12,0],[1.48645252e+12,0],[1.48645253e+12,0],[1.48645254e+12,0],[1.48645255e+12,0],[1.48645256e+12,0],[1.48645257e+12,0],[1.48645258e+12,0],[1.48645259e+12,0],[1.4864526e+12,0],[1.48645261e+12,0],[1.48645262e+12,0],[1.48645263e+12,0],[1.48645264e+12,0],[1.48645265e+12,0],[1.48645266e+12,0],[1.48645267e+12,0],[1.48645268e+12,0],[1.48645269e+12,0],[1.4864527e+12,0],[1.48645271e+12,0],[1.48645272e+12,0]]}]}]}`



**The second query**
`{"results":[{"series":[{"name":"xyz_klink_random_frontend_Controller_metric_count","tags":{"service":"frontend"},"columns":["time","non_negative_derivative"],"values":[[1.48645104e+12,31],[1.48645105e+12,0],[1.48645106e+12,0],[1.48645107e+12,0],[1.48645108e+12,0],[1.48645109e+12,0],[1.4864511e+12,0],[1.48645111e+12,0],[1.48645112e+12,0],[1.48645113e+12,0],[1.48645114e+12,0],[1.48645115e+12,0],[1.48645116e+12,0],[1.48645117e+12,0],[1.48645118e+12,0],[1.48645119e+12,0],[1.4864512e+12,0],[1.48645121e+12,0],[1.48645122e+12,0],[1.48645123e+12,0],[1.48645124e+12,0],[1.48645125e+12,0],[1.48645126e+12,0],[1.48645127e+12,0],[1.48645128e+12,0],[1.48645129e+12,0],[1.4864513e+12,0],[1.48645131e+12,0],[1.48645132e+12,0],[1.48645133e+12,0],[1.48645134e+12,0],[1.48645135e+12,0],[1.48645136e+12,0],[1.48645137e+12,0],[1.48645138e+12,0],[1.48645139e+12,0],[1.4864514e+12,0],[1.48645141e+12,0],[1.48645142e+12,0],[1.48645143e+12,0],[1.48645144e+12,0],[1.48645145e+12,0],[1.48645146e+12,0],[1.48645147e+12,0],[1.48645148e+12,0],[1.48645149e+12,0],[1.4864515e+12,0],[1.48645151e+12,0],[1.48645152e+12,0],[1.48645153e+12,0],[1.48645154e+12,0],[1.48645155e+12,0],[1.48645156e+12,0],[1.48645157e+12,0],[1.48645158e+12,0],[1.48645159e+12,0],[1.4864516e+12,0],[1.48645161e+12,0],[1.48645162e+12,0],[1.48645163e+12,0],[1.48645164e+12,0],[1.48645165e+12,0],[1.48645166e+12,0],[1.48645167e+12,0],[1.48645168e+12,0],[1.48645169e+12,0],[1.4864517e+12,0],[1.48645171e+12,0],[1.48645172e+12,0],[1.48645173e+12,0],[1.48645174e+12,0],[1.48645175e+12,0],[1.48645176e+12,0],[1.48645177e+12,0],[1.48645178e+12,0],[1.48645179e+12,0],[1.4864518e+12,0],[1.48645181e+12,0],[1.48645182e+12,0],[1.48645183e+12,0],[1.48645184e+12,0],[1.48645185e+12,0],[1.48645186e+12,0],[1.48645187e+12,0],[1.48645188e+12,0],[1.48645189e+12,0],[1.4864519e+12,0],[1.48645191e+12,0],[1.48645192e+12,0],[1.48645193e+12,0],[1.48645194e+12,0],[1.48645195e+12,0],[1.48645196e+12,0],[1.48645197e+12,0],[1.48645198e+12,0],[1.48645199e+12,0],[1.486452e+12,0],[1.48645201e+12,0],[1.48645202e+12,0],[1.48645203e+12,0],[1.48645204e+12,0],[1.48645205e+12,0],[1.48645206e+12,0],[1.48645207e+12,0],[1.48645208e+12,0],[1.48645209e+12,0],[1.4864521e+12,0],[1.48645211e+12,0],[1.48645212e+12,0],[1.48645213e+12,0],[1.48645214e+12,0],[1.48645215e+12,0],[1.48645216e+12,0],[1.48645217e+12,0],[1.48645218e+12,0],[1.48645219e+12,0],[1.4864522e+12,0],[1.48645221e+12,0],[1.48645222e+12,0],[1.48645223e+12,0],[1.48645224e+12,0],[1.48645225e+12,0],[1.48645226e+12,0],[1.48645227e+12,0],[1.48645228e+12,0],[1.48645229e+12,0],[1.4864523e+12,0],[1.48645231e+12,0],[1.48645232e+12,0],[1.48645233e+12,0],[1.48645234e+12,0],[1.48645235e+12,0],[1.48645236e+12,0],[1.48645237e+12,0],[1.48645238e+12,0],[1.48645239e+12,0],[1.4864524e+12,0],[1.48645241e+12,0],[1.48645242e+12,0],[1.48645243e+12,0],[1.48645244e+12,0],[1.48645245e+12,0],[1.48645246e+12,0],[1.48645247e+12,0],[1.48645248e+12,0],[1.48645249e+12,0],[1.4864525e+12,0],[1.48645251e+12,0],[1.48645252e+12,0],[1.48645253e+12,0],[1.48645254e+12,0],[1.48645255e+12,0],[1.48645256e+12,0],[1.48645257e+12,0],[1.48645258e+12,0],[1.48645259e+12,0],[1.4864526e+12,0],[1.48645261e+12,0],[1.48645262e+12,0],[1.48645263e+12,0],[1.48645264e+12,0],[1.48645265e+12,0],[1.48645266e+12,0],[1.48645267e+12,0],[1.48645268e+12,0],[1.48645269e+12,0],[1.4864527e+12,0],[1.48645271e+12,0],[1.48645272e+12,0],[1.48645273e+12,0],[1.48645274e+12,0],[1.48645275e+12,0],[1.48645276e+12,0],[1.48645277e+12,0],[1.48645278e+12,0],[1.48645279e+12,0],[1.4864528e+12,0],[1.48645281e+12,0],[1.48645282e+12,0],[1.48645283e+12,0],[1.48645284e+12,0]]}]},{"series":[{"name":"xyz_klink_random_frontend_Controller_metric_p95","tags":{"service":"frontend"},"columns":["time","mean"],"values":[[1.48645104e+12,0],[1.48645105e+12,3],[1.48645106e+12,3],[1.48645107e+12,3],[1.48645108e+12,3],[1.48645109e+12,3],[1.4864511e+12,3],[1.48645111e+12,3],[1.48645112e+12,3],[1.48645113e+12,3],[1.48645114e+12,3],[1.48645115e+12,3],[1.48645116e+12,3],[1.48645117e+12,3],[1.48645118e+12,3],[1.48645119e+12,3],[1.4864512e+12,3],[1.48645121e+12,3],[1.48645122e+12,3],[1.48645123e+12,3],[1.48645124e+12,3],[1.48645125e+12,3],[1.48645126e+12,3],[1.48645127e+12,3],[1.48645128e+12,3],[1.48645129e+12,3],[1.4864513e+12,3],[1.48645131e+12,3],[1.48645132e+12,3],[1.48645133e+12,3],[1.48645134e+12,3],[1.48645135e+12,3],[1.48645136e+12,3],[1.48645137e+12,3],[1.48645138e+12,3],[1.48645139e+12,3],[1.4864514e+12,3],[1.48645141e+12,3],[1.48645142e+12,3],[1.48645143e+12,3],[1.48645144e+12,3],[1.48645145e+12,3],[1.48645146e+12,3],[1.48645147e+12,3],[1.48645148e+12,3],[1.48645149e+12,3],[1.4864515e+12,3],[1.48645151e+12,3],[1.48645152e+12,3],[1.48645153e+12,3],[1.48645154e+12,3],[1.48645155e+12,3],[1.48645156e+12,3],[1.48645157e+12,3],[1.48645158e+12,3],[1.48645159e+12,3],[1.4864516e+12,3],[1.48645161e+12,3],[1.48645162e+12,3],[1.48645163e+12,3],[1.48645164e+12,3],[1.48645165e+12,3],[1.48645166e+12,3],[1.48645167e+12,3],[1.48645168e+12,3],[1.48645169e+12,3],[1.4864517e+12,3],[1.48645171e+12,3],[1.48645172e+12,3],[1.48645173e+12,3],[1.48645174e+12,3],[1.48645175e+12,3],[1.48645176e+12,3],[1.48645177e+12,3],[1.48645178e+12,3],[1.48645179e+12,3],[1.4864518e+12,3],[1.48645181e+12,3],[1.48645182e+12,3],[1.48645183e+12,3],[1.48645184e+12,3],[1.48645185e+12,3],[1.48645186e+12,3],[1.48645187e+12,3],[1.48645188e+12,3],[1.48645189e+12,3],[1.4864519e+12,3],[1.48645191e+12,3],[1.48645192e+12,3],[1.48645193e+12,3],[1.48645194e+12,3],[1.48645195e+12,3],[1.48645196e+12,3],[1.48645197e+12,3],[1.48645198e+12,3],[1.48645199e+12,3],[1.486452e+12,3],[1.48645201e+12,3],[1.48645202e+12,3],[1.48645203e+12,3],[1.48645204e+12,3],[1.48645205e+12,3],[1.48645206e+12,3],[1.48645207e+12,3],[1.48645208e+12,3],[1.48645209e+12,3],[1.4864521e+12,3],[1.48645211e+12,3],[1.48645212e+12,3],[1.48645213e+12,3],[1.48645214e+12,3],[1.48645215e+12,3],[1.48645216e+12,3],[1.48645217e+12,3],[1.48645218e+12,3],[1.48645219e+12,3],[1.4864522e+12,3],[1.48645221e+12,3],[1.48645222e+12,3],[1.48645223e+12,3],[1.48645224e+12,3],[1.48645225e+12,3],[1.48645226e+12,3],[1.48645227e+12,3],[1.48645228e+12,3],[1.48645229e+12,3],[1.4864523e+12,3],[1.48645231e+12,3],[1.48645232e+12,3],[1.48645233e+12,3],[1.48645234e+12,3],[1.48645235e+12,3],[1.48645236e+12,3],[1.48645237e+12,3],[1.48645238e+12,3],[1.48645239e+12,3],[1.4864524e+12,3],[1.48645241e+12,3],[1.48645242e+12,3],[1.48645243e+12,3],[1.48645244e+12,3],[1.48645245e+12,3],[1.48645246e+12,3],[1.48645247e+12,3],[1.48645248e+12,3],[1.48645249e+12,3],[1.4864525e+12,3],[1.48645251e+12,3],[1.48645252e+12,3],[1.48645253e+12,3],[1.48645254e+12,3],[1.48645255e+12,3],[1.48645256e+12,3],[1.48645257e+12,3],[1.48645258e+12,3],[1.48645259e+12,3],[1.4864526e+12,3],[1.48645261e+12,3],[1.48645262e+12,3],[1.48645263e+12,3],[1.48645264e+12,3],[1.48645265e+12,3],[1.48645266e+12,3],[1.48645267e+12,3],[1.48645268e+12,3],[1.48645269e+12,3],[1.4864527e+12,3],[1.48645271e+12,3],[1.48645272e+12,3],[1.48645273e+12,3],[1.48645274e+12,3],[1.48645275e+12,3],[1.48645276e+12,3],[1.48645277e+12,3],[1.48645278e+12,3],[1.48645279e+12,3],[1.4864528e+12,3],[1.48645281e+12,3],[1.48645282e+12,3],[1.48645283e+12,3],[1.48645284e+12,3]]}]}]}`

**Comment by jieqian** [comment]
the above 2 queries attempt return different current value

**Comment by jieqian** [comment]
The 2 queries above return the same current, but the order of 2 json object is different, so am I missing some setting in the display tab or metric tab?

**Comment by torkelo** [comment]
strange, influxdb should return results in same order. The order is the responsibility of the time series backend that process the query logic. 

Ask in mailing list (Grafana or InfluxDB)

**Comment by jieqian** [comment]
thanks a bunch
