### ISSUE TITLE
[Bug] Basic auth is not working with Direct connection

### ISSUE THREAD

**Issue by yarons** [grafana/grafana#7480]
I'm using Grafana 4.1.2
My datasource is Graphite
My OS is Debian Wheezy
I tried changing the data fetching method from Proxy to Direct and it didn't work, I'm getting a 401 error (Basic auth), exact same address, the only change was switching between Proxy and Direct.

All the errors appear in the console.

At a certain point I was experiencing a prefilght (CORS) error but I'll open another bug once we'll get to that.

Thank you!

**Comment by torkelo** [comment]
tested this, Grafana is sending the correct basic auth header. Sure it's accessible from your browser with that URL and you have CORS headers configured for you graphite server?

**Comment by yarons** [comment]
I was able to connect to it using the browser (the password was saved in advance, both Firefox and Chromium), In Proxy mode it was working, in Direct mode I got 401 Unauthorized and the name of the realm, Is it OK if I'll add screenshots?

**Comment by torkelo** [comment]
Yes, show screenzhots of chrome dev tools console, and one for network tab, showing raw request with headers

**Comment by yarons** [comment]
Well, I took some screenshots, the first one is showing the proxy mode, the image is pretty useless because the browser does not initiate the connection at all yet, there it is:
<img width="1440" alt="screen shot 2017-02-13 at 17 39 22" src="https://cloud.githubusercontent.com/assets/406826/22890621/987b49bc-f215-11e6-941b-3335ce002a63.png">

This is the error message appears when I switch to direct mode (notice the "realm" message):
<img width="1422" alt="screen shot 2017-02-13 at 17 44 25" src="https://cloud.githubusercontent.com/assets/406826/22890769/0551a7e8-f216-11e6-94ed-9349ab2f4897.png">

In addition: I copied the exact same address and pasted in another tab and this is the result:
<img width="846" alt="screen shot 2017-02-13 at 17 49 13" src="https://cloud.githubusercontent.com/assets/406826/22890817/217f6428-f216-11e6-9a9d-20e19cb35b1c.png">

I had to censor the address but you'll probably believe me when I tell you that they are the same. 😄

**Comment by yarons** [comment]
@torkelo Can you confirm this data is sufficient?

**Comment by torkelo** [comment]
For direct access your graphite server must support cross domain resources sharing, the OPTIONS http method needs to be excempt from basic auth for cors to work
