### ISSUE TITLE
Explore view fails if data source is a variable

### ISSUE THREAD

**Issue by RoryCrispin** [grafana/grafana#74822]
### What happened?

The error `One of the queries has a datasource that is no longer available and was removed.` is raised in the console when clicking '...' -> 'Explore' or pressing 'x' over a dashboard panel whose data source is a variable.
The Explore page which you are navigated to doesn't contain the query of the panel which you tried to 'Explore' to.

### What did you expect to happen?

I expect to be taken to the same query in the Explore view. This behaviour works when the data source is not a dashboard variable.

### Did this work before?

I recall it working before, and it works for panels with a constant data source.
The error occurs on 9.6.6, 10.1.1

### How do we reproduce it?

1. Launch Grafnana, you can use your own version or a clean download from grafana.com with the exampe data sources.
2. Create a new dashboard
3. Add a dashboard variable with type 'Data Source'
4. Add a panel, X, to the dashboard. Use the new data source variable as panel source.
5. Add another panel, Y, with a constant data source.
6. Try to explore to the Y panel. You should launch into explore with a pre populated query
7. Try to explore to the X panel. You should see a sparse explore page
8. Open the dev console and try exploring to the X panel again, see the error `One of the queries has a datasource that is no longer available and was removed.`

### Environment (with versions)?

Grafana: 10.1.1
OS: MacOS 
Browser: Firefox 117.0.1

### Grafana platform?

A downloaded binary

**Comment by RoryCrispin** [comment]
Tested on Grafana Cloud. I still see the blank explore panel, but there is no console log

**Comment by mellieA** [comment]
@RoryCrispin I'm not able to reproduce this on 10.2 (the version on Grafana Cloud). Can you spot anything I'm doing differently?

https://github.com/grafana/grafana/assets/18175287/210bcb16-751b-4887-9090-05f084b0f8cc

**Comment by RoryCrispin** [comment]
Hi @mellieA, 

I've tested and confirmed that:
This bug is no longer producable in Grafana Cloud,
I cannot repro the bug in 10.1.2
I can still produce the bug in old versions, just tried with 10.0.2 

For refernece, this dashboard exhibits the bug in 10.0.2:
```
{
  "__inputs": [],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.1.2"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "${query0}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "${query0}"
          },
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "-- Grafana --",
          "value": "grafana"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "query0",
        "options": [],
        "query": "grafana",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "uid": "d9834cdf-ec91-423a-8633-5acaa8e5063d",
  "version": 3,
  "weekStart": ""
}
```

We can close this as resolved 🍾
