### ISSUE TITLE
Permissions: grafanaBootData.user.permissions lists folders:write for Viewer with edit on one folder

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#74848]
Granting a viewer user "Edit" permission to just a single folder results in the `dashboards:create` permission being incorrectly listed in the frontend `grafanaBootData.user.permissions` user permissions data.

This causes the frontend to show "Create Dashboards" button when the user does not actually have permission to create dashboards (the API request to create the dashboard will fail)

Reproduction:

(While not strictly related, it's easier to see the impact of this with the `newBrowseDashboards` feature flag enabled)

1. **Admin**: Have a user "Viewer" with the basic Viewer role
2. **Viewer**: Log in as the Viewer user and navigate to `/dashboards`
    - 👍🏻 The blue New > Dashboard button won't be shown
    - 👍🏻 Logging `console.table(grafanaBootData.user.permissions)` in the JS console will not list `folders:write`
3. **Admin**: Grant the "Viewer" user edit permission to a single folder
4. **Viewer*: Reload `/dashboards`
   - 👎🏻  The blue New > Dashboards button _will_ be shown
   - 👎🏻 Logging `console.table(grafanaBootData.user.permissions)` in the JS console will incorrectly list `dashboards:create`,  `folders:write`, and `folders:delete`

https://github.com/grafana/grafana/assets/46142/22315def-d97a-4345-8b29-69c76d01b596

**Comment by aarongodin** [comment]
Verified that this is fixed as of 11.2. I believe this was tackled as part of the folder permissions fixes and updates that @IevaVasiljeva did.

https://github.com/user-attachments/assets/d537a95e-2173-49d3-aa16-542d64ae428b
