### ISSUE TITLE
Export with non-standard plugins to raintaink fails

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7485]
This is not strictly a Grafana bug, but here goes:

I exported https://dashboard.fosdem.org/dashboard/db/ulb-switching-overview to raintank.io and got `Unknown panel type: jdbranham-diagram-panel` once I had exported and visited the created link.

This makes sense for scalability, versioning, and security reasons, but is still very bad UX.

**Comment by torkelo** [comment]
Raintank snapshot server does not support custom plugins, how is this bad UX????

**Comment by torkelo** [comment]
We should probably install some popular plugins there, but not all

**Comment by torkelo** [comment]
We actually have some plugins installed there, not all, and the message is pretty clear why you the custom installed panel is not showing in the public grafana server so not sure walhar we can do more

**Comment by RichiH** [comment]
Arguably, non-supported exports should not even be allowed in Grafana UI.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by torkelo** [comment]
Why,?  It not like the snapshot is totally broken, maybe most panels are standard panels and only on is a custom plugin. Why prevent the snapshot from being made in that case?  Uses can also setup their own external snapshot servers and change what the external snapshot button push to
