### ISSUE TITLE
[Feature request] Thrid Y Axis

### ISSUE THREAD

**Issue by parkesy** [grafana/grafana#7486]
What Grafana version are you using: 4.1.1
What datasource are you using: InfluxDB
What OS are you running grafana on: Ubuntu 16.04
What did you do: I went into display->Series Overrides and tried to set the Y axis to 3 but only 1 and 2 exist.

- What was the expected result: I expected that the two see my three time series drawn on a graph each with their own independent Y axis. I was happy to see Axis one on the left, axis two on the right and axis three on either the left or the right.
- What happened instead? There is not option for a third axis.

**Comment by torkelo** [comment]
why create this issue again???
https://github.com/grafana/grafana/issues/7397

**Comment by parkesy** [comment]
Ah! gees. I totally forgot that I'd already created that ticket... my bad.
