### ISSUE TITLE
Discord Contact Point cannot send test message 

### ISSUE THREAD

**Issue by GaNiziolek** [grafana/grafana#74877]
### What happened?

I cannot send the test message to my discord webhook bot.
When I click on "Send test notification button" this error message appears:
```
Failed to send test alert.: Post "https://discordapp.com/api/webhooks/<KEY>/<KEY>": EOF
```

![2023-09-13-162208_1920x1053_scrot](https://github.com/grafana/grafana/assets/54728889/58450f22-2d34-42b4-9415-6438e8d2de08)

### What did you expect to happen?

Receive a test message on my discord channel

### Did this work before?

Is the first time i'm trying

### How do we reproduce it?

1. On Discord, get the webhook URL from a channel integration
2. Create a new Discord Contact Point on Grafana and set the URL 
3. Send test message

### Environment (with versions)?

Grafana: V10.1.1
OS: Linux
Browser: Firefox

### Grafana platform?

Docker

**Comment by GaNiziolek** [comment]
I've tried to change the webhook URL to https://webhook.site and the POST requisition is being send.

The result can be acessed [here](https://webhook.site/#!/5b31f4d4-a9bf-420d-961d-00e132ea35e0/9a732fee-cb02-4542-aefb-296bea0ccfb9/1)

**Comment by GaNiziolek** [comment]
I'm going to fork the repo and try to test and debug what could be causing this problem

**Comment by armandgrillet** [comment]
Can you tell us about your network setup? The raw content on webhook.site looks fine. This error could happen if your corporate network has Discord disabled, for example.

**Comment by GaNiziolek** [comment]
The Grafana server is running in a container.
The host machine (that runs all containers) is an server inside a corporate network as you said.

I did some tests with CURL:

### On Grafana container / Host machine
```sh
$ curl -v -H "Content-Type: application/json" -d '{"content": "hello world"}' https://discordapp.com/api/webhooks/<key>/<key>
*   Trying 162.159.129.233:443...
* TCP_NODELAY set
* Connected to discordapp.com (162.159.129.233) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to discordapp.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to discordapp.com:443
```

### On my machine (outside corporate network)
This works, the message is sent
```sh
$ curl \
    -w "status: %{http_code}" \
    -H "Content-Type: application/json" \
    -d '{"content": "hello world"}' \
    https://discordapp.com/api/webhooks/<id>/<id>
status: 204
```

**Comment by GaNiziolek** [comment]
I spoke to the company's IT and they add my server to firewall whitelist, this resolved the issue.

I will leave the suggestion here to give more verbose log about the problem, the current message is very generic.

**Comment by papagian** [comment]
@armandgrillet can you point us to the backend code that is called so that we can try to improve the error log, thanks!

**Comment by mildwonkey** [comment]
hi @armandgrillet can you answer @papagian 's question? This isn't something we are familiar with in the backend platform, so I'm not sure how we can help. Thanks!

**Comment by armandgrillet** [comment]
We've looked during our board maintenance and it is this file: https://github.com/grafana/grafana/blob/062d255124160420f48c2af9a09a8cf89681369e/pkg/services/notifications/webhook.go#L81-L84
