### ISSUE TITLE
Release "Direct Input" datasource as core plugin

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#74889]
**Why is this needed**:

I have a use-case for panels with constant values in a dashboard. Existing solutions to add constant values include using Text Panels, which have limited formatting options, or creating constant PromQL queries like "35" and then using a Stat panel.

I'd like to use a Stat panel and its formatting facilities to create constant panels. The Direct Input datasource was first [added to Grafana in 2019 as an alpha datasource](https://github.com/grafana/grafana/pull/16282). It supports storing CSV as either a shared value in the datasource, or as constant data in the dashboard panel's JSON. It's been alpha for 4 years.

**What would you like to be added**:

Update the status of the plugin to a "bundled datsource" l[ike the others listed here.](https://grafana.com/docs/grafana/latest/datasources/#built-in-core-data-sources)

**Who is this feature for?**

Any Grafana Dashboard Users who would like to create panels based on constant data, without loading files from disk like the CSV datasource requires.

**Comment by tolzhabayev** [comment]
@joeblubaugh is there anything you can't do with https://grafana.com/docs/grafana/latest/datasources/testdata/?

**Comment by joeblubaugh** [comment]
I think TestData probably *does* cover my needs, but I didn't realize how many different forms of data it supported at first. Thanks!

In that case I might recommend deprecating and removing this datasource, it might be redundant with other core plugins.

**Comment by sympatheticmoose** [comment]
fixed by #83163
