### ISSUE TITLE
Feature : 

### ISSUE THREAD

**Issue by pankajmehta** [grafana/grafana#7488]
I want to read login user in the template variables query, so that user based authorization(filer data based on userid) can be setup, 
Is there a global variable availabe to read the login user and how to use in the templating.

Please include this information:
- What Grafana version are you using : 4.2
- What datasource are you using :influxdb
- What OS are you running grafana on :Ubuntu
- What did you do
- What was the expected result?
- What happened instead?

**Comment by torkelo** [comment]
it would not be very secure as anyone can view the query the frontend generates and change their user Id using simple http tools. In order to securely separate user data you need to put them in separate InfluxDB databases, create two orgs in Grafana and create one data source for each org

**Comment by pankajmehta** [comment]
Understood, but my point is user A should be able to see only org 'A' data and user 'B' should be able to see Org 'A' and 'Org 'B' data together.. How to achieve this if userid is not exposed.
