### ISSUE TITLE
CloudWatch: Update metrics for AWS/MediaConnect

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#74883]
We need to update the [hardcoded metrics](https://github.com/grafana/grafana/blob/4b7b323061a803125db161219c5452d7e2f27e6f/pkg/tsdb/cloudwatch/constants/metrics.go#L360) for AWS/MediaConnect to include newer metrics ([aws docs](https://docs.aws.amazon.com/mediaconnect/latest/ug/monitor-with-cloudwatch-metrics-source-health.html))

**Comment by jovialdude** [comment]
Are the metrics for gateway health required?

**Comment by Deepali1211** [comment]
@iwysiu Can you please assign this issue to me? I would to work on this.

**Comment by fridgepoet** [comment]
Feel free to work on it and open a PR, even if you are not assigned @Deepali1211

**Comment by Deepali1211** [comment]
Please review.
I have added all the metrics to monitor flow health, source health, output health, media health and gateway health.
