### ISSUE TITLE
[Bug] Repeat panel does not work

### ISSUE THREAD

**Issue by mantzas** [grafana/grafana#7489]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
 Grafana v4.1.1
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
ubuntu 16.10
- What did you do?
Created a template server list from influxdb 
Created a graph and used the repeat  option
- What was the expected result?
I should have a dashboard with all servers
- What happened instead?
I had only the first server and the span 12.

The first dashboard where i used the repeat feature was fine and worked. All the subsequent attempts have failed.

**Comment by torkelo** [comment]
it should work. Here is an example dashboard I made for you that show how you do it:
http://play.grafana.org/dashboard/db/influxdb-templated-queries-copy?var-datacenter=America&var-host=10.1.100.1&var-host=server1&var-host=server2&var-summarize=$__auto_interval

Make sure you use the variable in the query. You also need to select more than one value in the variable (it only repeats for the selected values, so you need a variable with All or Multi value enabled)

**Comment by mantzas** [comment]
It does work on your PC(trademark). I have attached the setup:

- Template
- Panel
- Dashboard

![template](https://cloud.githubusercontent.com/assets/605434/22731315/db7582f4-edf2-11e6-94ee-c4f9556da496.PNG)
![dashboard](https://cloud.githubusercontent.com/assets/605434/22731316/db920302-edf2-11e6-9a3d-1e5d2e2c1291.PNG)
![panel](https://cloud.githubusercontent.com/assets/605434/22731317/dbaf8eae-edf2-11e6-99fa-6f28e1d607ab.PNG)

**Comment by torkelo** [comment]
And what is the value of your template variable?

**Comment by mantzas** [comment]
ip's (string) of our servers

**Comment by mantzas** [comment]
please reopen this bug, it is not resolved!

**Comment by torkelo** [comment]
We have  no other reports of problems with panel repeat and fail to replicate any issues, please provide more info, like dashboard json and exact values of templates,  any Javascript errors in Chrome console?

**Comment by mantzas** [comment]
I have the following data for you

- Dashboard: [PerServer.zip](https://github.com/grafana/grafana/files/782909/PerServer.zip)
- Template values of  "show tag values from searches with key = ip" return 30 ip's in the 10.x.x.x range
- Console did not show any errors.

hope this helps

**Comment by torkelo** [comment]
could not see any values for Hosts in that dashboard.

**Comment by mantzas** [comment]
the values from hosts are coming from the template query mentioned previously (ips from 30 machines in the 10.x.x.x range)

**Comment by mantzas** [comment]
Steps to reproduce:

- Create a new dashboard
- Create a new template with values from influx and hide variable
- Add a panel and repeat on that template
- Save, reload.

in order to work the template has to be visible!

**Comment by torkelo** [comment]
works fine when I test that scenario. 

In this dashboard the server variable is hidden
http://play.grafana.org/dashboard/db/graphite-panel-repeats-hidden?var-server=backend_01&var-server=backend_02&var-server=backend_03

**Comment by mantzas** [comment]
Yes but you have checked Multi-Value and Include All-Options which have to do with the select which is not used.
My steps did not have theses two included.

**Comment by torkelo** [comment]
but those are required for panel repeats. The panel is repeat for each selected value (all or multi selected state)

**Comment by mantzas** [comment]
Event if the select control is not visible? Ok, it was not obvious for me. 
I thought that the template would contains all values by default and the "all" and "multi-select" had only to do with the html select control.
When the above are not checked then the template variable contains only the first value of the list which is counter intuitive with the select * query.
Is there a reason for someone to NOT check "all" and "multi-select" and have the variable invisible?

**Comment by torkelo** [comment]
> Is there a reason for someone to NOT check "all" and "multi-select" and have the variable invisible?

yes, of course. Why would hiding it have anything to do with how many values it can have selected at once?

**Comment by mantzas** [comment]
Since it works as expected you can close the issue.
I have to remember to always check the boxes in order to have the templates behave the way i want it to.
Thanks very much for your help.
