### ISSUE TITLE
Alerting: No alerts are shown when editing notification template

### ISSUE THREAD

**Issue by Igorgro** [grafana/grafana#74923]
### What happened?

I wanted to setup custom notification message which will be sent to email/telegram/slack. I'm trying editing notification template, but when I click "Select alert instances", then the empty is opened:
![image](https://github.com/grafana/grafana/assets/22894169/ef05fc80-8f58-4781-92c5-46893b7d2182)
and nothing is showed even if I start seaching for something. I have an alert rule with multiple instances, but it is not showed in this dialog.
<details><summary>Alert rule with instances</summary>
<p>

![image](https://github.com/grafana/grafana/assets/22894169/a109f0e1-d5f9-4229-991e-b67addc5d1e7)

</p>
</details> 

### What did you expect to happen?

The list of alert rules and their instances are shown

### Did this work before?

Not sure, because I found this feature only today.

### How do we reproduce it?

1. Install the latest (10.1.1) version of Grafana
2. Add some datasource (for example Prometheus) and create a dashboard
3. Create new alert rule from Prometheus metrics and make sure that it has at least one instance
4. Go to 'Contact points' and create new notification template
5. While editing notification template, try to add an alert using 'select alert instances'

### Environment (with versions)?

Grafana: 10.1.1
OS: Arch Linux
Browser: Google Chrome 117.0.5938.62

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by mellieA** [comment]
Double-check that you've selected the same alertmanager from the drop-down in the top right corner that you used to create your alert, it's tricked me before! 

![Screenshot 2023-09-19 at 1 50 37 PM](https://github.com/grafana/grafana/assets/18175287/fa8cf42f-deee-4676-8b9a-368f94a816b5)

**Comment by Igorgro** [comment]
@mellieA yes I already checked: I have only one Alertmanager - the one which embedded in Grafna

**Comment by Igorgro** [comment]
But I now found solution: there shown only firing alerts. It's strange that it isn't documented enywhere, at least there is no some hint for such behaviour

**Comment by usmangt** [comment]
Based on your steps of reproduction, I was also able to reproduce it on my test machine.

The only happens for alerts if the state is other than firing.

I will forward this issue to our Engineers so that they can have a look and analyse it.

**Comment by mihalt** [comment]
@armandgrillet Do I understand correct, that it will not be integrated anytime? I would be glad at least to take values from history of firing alerts. 

Or if you really not plan in any forms, than rename `Use existing alert instances` to `Use existing firing alert instances`. This setting was really confused me.
