### ISSUE TITLE
Alerting: Images in Slack notification are added to thread

### ISSUE THREAD

**Issue by PovilasV1** [grafana/grafana#74921]
### What happened?

We are using Slack contact point with Slack API token configured. The messages are sent and images are attached, but they are added to the message thread instead of the original message.
![image](https://github.com/grafana/grafana/assets/48908420/e5e220ac-1e4d-4f4b-a533-e126ae13726b)
Also, alert names and labels are added to the thread, which we do not want. Not sure if this is expected behavior or if we didn't configure the alert/slack app correctly. The Slack app has these scopes: `chat:write`, `files:write` and `links:write`
The same behavior occurs when uploading images to local storage or private s3 bucket.

### What did you expect to happen?

The alert and image are posted as 1 message.

### Did this work before?

It worked with Grafana 8 and legacy alerting.

### How do we reproduce it?

Create a new alert with Slack contact point and Slack API token.

### Environment (with versions)?

Grafana: v10.1.1
OS: Linux
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by mellieA** [comment]
The image and alert should come through in a single message with the new alerting. The alert can be customized by updating the alert message template, the default template uses labels in it. 

I have sample alerts that fire regularly and look like this: 

![Screenshot 2023-09-19 at 11 49 22 AM](https://github.com/grafana/grafana/assets/18175287/406b2486-a2f8-4720-b8b6-808120267ba7)

I'd suggest opening a post in the community at community.grafana.com to find out if others have run into the issue of threading notifications and fixed it. I haven't seen that problem before.

**Comment by PovilasV1** [comment]
This happens when you use a Slack bot token. It adds the image and dumps alert names and labels into the thread. When Slack webhook is used, the image is attached to the original message. However, webhooks do not actually upload the image; they only link it from external storage, which does not work if you are using publicly inaccessible storage. 

It would be nice if both webhook and bot token produced the same format.
