### ISSUE TITLE
[Feature request] Start new row for repeated panels of varying heights.

### ISSUE THREAD

**Issue by Gebuz** [grafana/grafana#7494]
Hi, I am using the [status panel plugin](https://grafana.net/plugins/vonage-status-panel) and I have run into an issue with repeated panels of varying heights causing a lot of wasted space because it will try to fill in more panels after the highest panel in each row as shown in this picture:
![repeat panels wasted space](https://cloud.githubusercontent.com/assets/6773230/22734134/f39d4d6a-edf4-11e6-9c3e-1587d02f3031.png)

I do not believe that it is connected to the plugin, as it behaves the same way if you just make more panels than can fit in a row:
![wasted space](https://cloud.githubusercontent.com/assets/6773230/22733861/d3948246-edf3-11e6-9820-5f0038940533.PNG)

It would waste a lot less space if it never tried to fit in extra panels, or if it also tried to fit in panels before the highest panel in the row.

**Comment by torkelo** [comment]
panels no a row need to have the same height

**Comment by torkelo** [comment]
We want to improve layouts in the future, but not sure it will cover this case. Just set the height of the row to the height of the highest panel and they should all align

**Comment by Gebuz** [comment]
Sadly that does not work for repeated panels, as they are all in the same "row". I can understand that assuming repeated panels are all of the same height is reasonable, but it would still be nice if it worked with different heights. Anyway, thanks for taking your time to answer :)
