### ISSUE TITLE
Grafana Alerting: Notifications in new Teams are not rendering markdown correctly

### ISSUE THREAD

**Issue by jvmdc** [grafana/grafana#74959]
### What happened?

When using the new Microsoft Teams application, Markdown does not render properly in custom templates:
![image](https://github.com/grafana/grafana/assets/109624469/7291af52-8a6f-4571-9203-fd16a1a1b34a)

Bold font and lists do not work either.

For some reason, the default template renders just fine

### What did you expect to happen?

Markdown should render properly as in the old Microsoft Teams:
![image](https://github.com/grafana/grafana/assets/109624469/08953bae-cb9d-4289-93e0-4e38123e1307)

### Did this work before?

Yes, in the same version (Grafana v10.1.1 (0cfa76b22d))

### How do we reproduce it?

1. Create a custom template, the above was generated using this:
```
{{ define "mysystem_alert_template_title" }}
  {{ if gt (len .Alerts.Firing) 0 }}
    🔥{{ len .Alerts.Firing }} alert(s) firing
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    ✅{{ len .Alerts.Resolved }} alert(s) resolved
  {{ end }}
{{ end }}

{{ define "mysystem_alert_template_message" }}
  {{ if gt (len .Alerts.Firing) 0 -}}
    {{ range .Alerts.Firing -}}
    
**Summary: {{ .Annotations.summary }}**


Description: {{ .Annotations.description }}

    {{ if .Annotations.runbook_url -}}
      [Runbook]({{ .Annotations.runbook_url }})
    {{ end }}
    {{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    ✅{{ len .Alerts.Resolved }} alert(s) resolved
  {{ end }}
{{ end }}
```
2. Use the custom template in a Teams Webhook contact point
3. Test the contact point, setting Runbook URL to e.g. https://google.com
4. If using new Teams, notice that the Markdown URL is not properly converted to a clickable link.
5. Swap to old Teams by clicking the switch:
![image](https://github.com/grafana/grafana/assets/109624469/200e29f4-002d-4380-8a00-ae2d9dfeab26)
6. Notice that the Runbook is now a clickable link

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v10.1.1 (0cfa76b22d)
OS: Windows 11
Browser: N/A
Broken in Microsoft Teams: 23217.806.2340.1703, client version:  49/23082000931
Working in Microsoft Teams: 1.6.00.22378 (64-bit

### Grafana platform?

Kubernetes

**Comment by jvmdc** [comment]
I do realize that the problem is potentially on Microsoft Teams' end, but it might also be some API endpoint that's changed ¯\\\_(ツ)_/¯

**Comment by usmangt** [comment]
Hi @jvmdc ,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by jvmdc** [comment]
I've sent the feedback their way as well, just figured Grafana Labs might have another point of entry to Microsoft than I do - My fear is the issue will drown in all the feedback they probably get.

**Comment by cah-jad-baz** [comment]
This might be related to this MS forum post: https://learn.microsoft.com/en-us/answers/questions/1375884/markdown-formatting-issue-in-microsoft-teams-conne

**Comment by bhadreshpanchal88** [comment]
Hi Team,

I am also facing the similar issue on Teams channel. Any update from Microsoft Or any work around to fix this issue ?

**Comment by armandgrillet** [comment]
It doesn't look like the fix has been fixed on Team's side yet according to https://learn.microsoft.com/en-us/answers/questions/1375884/markdown-formatting-issue-in-microsoft-teams-conne

**Comment by DomsaNN** [comment]
Any workaround to fix this? Teams as usually can't deliver....

**Comment by engrtitus** [comment]
For us, what we discovered was causing it was the presence of line breaks like so in the message content 

```\n    \n   alertname\n   TestAlert\n \n instance\n Grafana nice\n \n \n \n```

To fix, we proxied the request to teams via a cloudflare worker and removed the extra spaces after the line breaks
