### ISSUE TITLE
Alert Provisioning: Not able to delete the provisioned alert

### ISSUE THREAD

**Issue by nitu-s-gupta** [grafana/grafana#74958]
### What happened?

we have tried to provision the alerts using file provisioning. The alerts are provisioned succesfully after grafana restart. But when I m trying to delete the provisioned alert:

a. I cant see any delete option on UI to delete provision  alert
b. I cant delete them even after deleting the file that I used to provision them
c. I cant delete them even after using the following api
/api/v1/provisioning/alert-rules/{UID}
I m getting the following error
{
    "message": "cannot delete with provided provenance 'api', needs 'file'",
    "traceID": ""
}

### What did you expect to happen?

There should be some way by which provisioned alerts can be deleted

### Did this work before?

This is first time trying alert provisioning 

### How do we reproduce it?

1.Provision alert using file provisioning mentioned in grafana documentation
2.Try deleting the same alert after provisioning
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Version 9
OS: Ubuntu/Linux
Browser: Chrome/Edge

### Grafana platform?

Kubernetes

@konrad147 @soniaAguilarPeiron can you please help me with this issue

Should it be separate file 
I have added the file as delete.yaml wit following value
# config file version
apiVersion: 1

# List of alert rule UIDs that should be deleted
deleteRules:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> unique identifier for the rule
    uid: "b3ee9a12-5f7d-4254-a8bd-2eft6f82cb245"

please let me know anything else is needed as this is not working

@soniaAguilarPeiron Editing this meesaqge as not able to add comment to it. Please let me know if any mistake i m doing

**Comment by soniaAguilarPeiron** [comment]
Hi @nitu-s-gupta ,
Yes, you can use the section `deleteRules` in the provisioned file.
You need to add the orgId and uid of the corresponding rule in that list.
[Here](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-alert-rules) you have documentation about provisioning.

**Comment by mellieA** [comment]
@nitu-s-gupta it looks like @soniaAguilarPeiron was able to share the answer. I'll close this for now, if you find there is a bug please open a new issue and reference this one.
