### ISSUE TITLE
[Bug] blurred graph pannel

### ISSUE THREAD

**Issue by beserg** [grafana/grafana#7496]
- What Grafana version are you using?
Grafana v4.1.1 (commit: v4.1.1)
- What datasource are you using?
graphite
- What OS are you running grafana on?
Ubuntu 14.04.5 LTS Firefox 51.0.1 (64-bit), 1920х1080.
- What did you do?
Opened a graph panel
```
{
  "aliasColors": {
    "__ffff_10_0_0_1": "#DEDAF7",
    "awaps-asXx_yandex_ru": "#9AC48A",
    "bsfrontXx_yabs_yandex_ru": "#F9934E",
    "bsyetiXx_yabs_yandex_ru": "#FFDF12",
    "bsyetiXx_yandex_ru": "#CCA300",
    "fdef__1": "#DEDAF7",
    "fresh_ipv4": "#999999",
    "fresh_ipv6": "#999999",
    "nanpu01e_yandex_net": "#DEC62C",
    "nanpu01ep_yandex_net": "#DEDAF7",
    "nanpuXx_yandex_net": "#967302",
    "stormXx_rtcrypta_yandex_net": "#7EB26D",
    "unresolved_ipv4": "#999999",
    "unresolved_ipv6": "#999999",
    "yabsbtX-X_yabs_yandex_ru": "#BA43A9",
    "yabsbtX-X_yandex_ru": "#E24D42",
    "yabsstX-Xx_yandex_ru": "#F4D598"
  },
  "annotate": {
    "enable": false
  },
  "bars": true,
  "datasource": "bs.mega-graphite",
  "decimals": null,
  "editable": true,
  "error": false,
  "fill": 0,
  "grid": {
    "threshold1": null,
    "threshold1Color": "rgba(216, 200, 27, 0.27)",
    "threshold2": null,
    "threshold2Color": "rgba(234, 112, 112, 0.22)"
  },
  "id": 513,
  "legend": {
    "alignAsTable": false,
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "rightSide": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": false,
  "linewidth": 1,
  "links": [],
  "minSpan": 2,
  "nullPointMode": "null as zero",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "repeat": null,
  "resolution": 100,
  "scale": 1,
  "scopedVars": {
    "dc": {
      "text": "g",
      "value": "g",
      "selected": false
    }
  },
  "seriesOverrides": [],
  "span": 2.4,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "hide": true,
      "refId": "F",
      "target": "aliasByNode(sortByTotal(summarize(maximumAbove(sumSeriesWithWildcards(transformNull(one_min.idserv??[[dc]]_rtcrypta_yandex_net.hip6src.*, 0), 1), 0), '$t', 'avg')), -1)",
      "textEditor": false
    },
    {
      "hide": false,
      "refId": "A",
      "target": "aliasByNode(sumSeriesWithWildcards(sortByTotal(maximumAbove(summarize(scaleToSeconds(transformNull(one_min.idserv??[[dc]]_rtcrypta_yandex_net.ident_server.proxy.ipv6.*, 0), 1), '$t', 'avg'), 0)), 1), -1)",
      "textEditor": true
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "[$dc] proxy traffic sources",
  "tooltip": {
    "msResolution": false,
    "query_as_alias": true,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "show": true
  },
  "yaxes": [
    {
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": 0,
      "show": true
    },
    {
      "format": "short",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "zerofill": true,
  "repeatIteration": 1486562522942,
  "repeatPanelId": 138
}
```
- What was the expected result?
Clear stacked bar chart
- What happened instead?
Browser rendered blurred chart

Screenshot below
http://imgur.com/a/FxIDZ

**Comment by torkelo** [comment]
cannot see any difference

**Comment by irandom** [comment]
Version 3.1.1 has clear 3-pixel bright bars and clear 2-pixel dark space between them (with little blending). Version 4.1.1 aggressive blending that removes "sharp edges" of the bars. It's like difference between digital rectangular signal and analogous sine-shaped counterpart. The visual difference is partly wiped out and some people see it from the first sight, while other recognize the difference some time later. Can we reopen the issue?

http://imgur.com/a/cV1Bi

**Comment by levanovd** [comment]
Also the difference probably is not so noticeable on high-DPI displays like Retina, but it is obvious on standard-DPI displays like 24" 1980x1080.

**Comment by torkelo** [comment]
can you consistantly get this difference between 3.1 vs 4.x? it just looks like pixel alignment, sometimes the canvas will align pixel perfect and sometimes not, so it should be pretty random if it's blurred or sharp (and no consistant difference between 3.1 and 4.x as there has been no change related to canvas rendering)

**Comment by kyluke** [comment]
I'm experiencing the same issue. I have a better example though: https://imgur.com/a/8zNDE

I'm running:

 - Firefox Dev (54)
 - MacBook Pro (Retina, 13-inch, Early 2015) on Sierra
 - Grafana v4.0.2 (commit: v4.0.2)

Although not as clear, the problem exists on the Grafana demo page as well: http://imgur.com/a/2EiWU

I just performed the same test on a Linux machine and the problem persists. Although this isn't as noticeable with the lower resolution of this netbook. http://imgur.com/a/BlA2H

 - Firefox Dev (54)
 - elementary OS 0.4 Loki
 - Grafana v4.0.3 (commit: 4.0.2)

It seems a higher resolution screen is really necessary to properly experience the issue.
