### ISSUE TITLE
Dashboards: Edit panel shows flickering at top right

### ISSUE THREAD

**Issue by kratsg** [grafana/grafana#74965]
### What happened?

![flicker](https://github.com/grafana/grafana/assets/761483/8ff1007a-f59c-4301-a85e-f86048dd0c26)

https://github.com/grafana/grafana/assets/761483/e4795c41-40aa-4ecc-a64f-47a3ad6b3912

### What did you expect to happen?

No flickering.

### Did this work before?

It used to be ok in Grafana v7 releases, and bumping to v9.4.7 shows this behavior.

### How do we reproduce it?

1. Go to dashboards, pick any plot, click to Edit, and the Edit Panel screen shows it happening.

Resizing does not fix behavior. Cannot check if reproducible in other browsers (get the "Grafana warning" page about unsupported browser on CentOS7 (Firefox, Brave, etc...) -- only Chrome seems to work.

### Is the bug inside a dashboard panel?

Happens to all of them, rather than a specific one.

### Environment (with versions)?

Grafana: v9.4.7
OS: 3.10.0-1127.el7.x86_64 (RedHat / CentOS7)
Browser: Chrome 87.0.4280.88 (64-bit)

### Grafana platform?

Docker

**Comment by kratsg** [comment]
@usmangt https://play.grafana.org/d/cf557618-e173-44fa-af5e-7c38439b071d/scipp-pixmod-test?orgId=1

Don't even need to create any panels. I'm already seeing that behavior directly on that empty dashboard (see attached video).

Uploading IMG_3729.MOV…

**Comment by natellium** [comment]
Hey @kratsg, I've noticed you're using Chrome 87.0.4280.88 (64-bit), would you be able to update to the latest version? I've seen this issue before in old Chrome versions but it seemed to go away with the upgrade.

**Comment by kratsg** [comment]
Yeah, so on SL7 - I can't seem to get Chrome to update any newer, I need to figure out why - but I'm not sure I can get a newer version of Chrome that easily.

**Comment by natellium** [comment]
I understand. Right now, we're only able to help with the latest version (see supported browsers [here](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers)), so I'm afraid I'll have to close this issue for the time being. But if you do manage to update to a newer version and still run into the same problem, please give us a shout. We'd be glad to dive deeper into it and see how we can assist.

**Comment by kratsg** [comment]
Understood, thanks anyway!
