### ISSUE TITLE
Pushover: Cannot send test notification at Emergency level without setting additional params

### ISSUE THREAD

**Issue by rixx** [grafana/grafana#74968]
### What happened?

Setting up Grafana, I wanted to configure Pushover notifications. I first set up notifications at warning level (policy, contact point, alert rules etc). I was able to use the "Test" button in the contact point, and received appropriate test notifications on my Pushover devices.

However, when I duplicated the contact point in order to test emergency level messages (which can bypass do-not-disturb, ring continuously, and so on), I got no test notification, and Grafana said "Failed to send test alert.: webhook response status 400 Bad Request".

The logs say:

```
logger=ngalert.notifier.pushover notifierUID=f4430140-3e58-46d5-9c54-5a82d41466fc t=2023-09-16T12:40:30.40806591Z level=error msg="Missing receiver"
logger=ngalert.notifier.pushover notifierUID=f4430140-3e58-46d5-9c54-5a82d41466fc t=2023-09-16T12:40:30.408743643Z level=error msg="Missing group labels"
logger=ngalert.notifier.pushover notifierUID=f4430140-3e58-46d5-9c54-5a82d41466fc t=2023-09-16T12:40:31.109030833Z level=error msg="failed to send pushover notification" error="webhook response status 400 Bad Request" webhook=test
```

After trying out a lot of things, I decided to fill in the "Retry (Only used for Emergency Priority)" and "Expire (Only used for Emergency Priority)" fields. After filling in these fields and saving, I was able to send emergency level test notifications.

### What did you expect to happen?

If those fields are required to send notifications at emergency levels, I'd expect them to be mandatory (or for Grafana to use sensible defaults). If they are not required for regular notifications and only have to be set for test notifications, I'd expect test notifications to work exactly the same as notifications in the field.

### Did this work before?

I have never set up Grafana before, however, the forum are full with people quoting this error message starting about a year ago.

### How do we reproduce it?

1. Set up a pushover alert
2. Test it with any level other than emergency, no other settings changed (success)
3. Test it with emergency level (fail)

### Is the bug inside a dashboard panel?

–

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

–

**Comment by danteali** [comment]
I'm getting the same errors - but I can't seem to get anything to send even with all fields filled in. And doesn't matter which priority I choose, same error for all priority levels.

**Comment by mellieA** [comment]
@danteali and @rixx can you share the versions of Grafana you're using?

**Comment by danteali** [comment]
Sorry, should have included that info. I was using the 10.0.3 docker image. 

But I just updated to the most recent image (10.1.2) and it's working now. Apologies for not thinking to upgrade before posting before! Thanks for the work on this.

**Comment by rixx** [comment]
I'm running 10.1.1. I just updated to 10.1.2 (which wasn't available on my platform when I reported), where the problem seems to be fixed. Thank you!

**Comment by maltekrupa** [comment]
> I'm getting the same errors - but I can't seem to get anything to send even with all fields filled in. And doesn't matter which priority I choose, same error for all priority levels.

I experience the same on Grafana Cloud.

Error message:

```
Failed to send test alert.: webhook response status 400 Bad Request
```

**Comment by baonq-me** [comment]
Same here with `v9.1.8 (3c0c14de5d)`

**Comment by rixx** [comment]
I just tried this again and it seems that emergency notifications are still malformed and trigger a HTTP 400. This is on Grafana v12.3.1.
