### ISSUE TITLE
Grafana / Cloudwatch Datasource - Monitoring AWS custom namespace metrics and replacing template variables in the query editor - Couldnt retrieve the template variable value

### ISSUE THREAD

**Issue by kamalvpm777** [grafana/grafana#7497]
[Bug]Grafana with Cloudwatch Datasource - Monitoring AWS custom namespace metrics and replacing template variables in the query editor for metric name  couldnt retrieve the template variable value, so wanted something like this on metrics field ({"httpjson_$appname_heap"} ---> "httpjson_engine_heap")

Please include this information:
- What Grafana version are you using? v 3.1.1
- What datasource are you using? CLOUDWATCH 
-Which Cloud watch metrics ? Custom name space metrics within Cloudwatch
- What OS are you running grafana on? Mac OS X EI Capitan -ver 10.11.1
- What did you do? Monitoring AWS custom namespace metrics in Grafana through Cloudwatch as a datasource, couldnt pull the template variable value for the metric value in the query editor
- What was the expected result?
 In Cloud watch our metric name looks like this "httpjson_engine_heap"
 Similar to engine we have many apps, so used the template custom variable "appname" to replace the app names . 
So we expected {"httpjson_$appname_heap"} ---> "httpjson_engine_heap"
- What happened instead?
Couldnt retrieve the value of appname variable value of "engine" for the metric name {"httpjson_$app name_heap"} 

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query

We are more focused on "select metric"  field to handle different metric for different application
![image](https://cloud.githubusercontent.com/assets/25632887/22744317/121b5f3e-edeb-11e6-84a4-5f228d653954.png)

**WORKS** - Using the metric name of "httpjson_engine_heap" without any template variable
![image](https://cloud.githubusercontent.com/assets/25632887/22744325/1a3db02c-edeb-11e6-82c1-7ac3f2f5a409.png)

**NOT WORKS** - When using metric name of {"httpjson_$appname_heap"} using the template variable of $appname to retrieve the appname, it never works

![image](https://cloud.githubusercontent.com/assets/25632887/22744537/9d819cbe-edeb-11e6-9751-cd478c9d1931.png)

**TEMPLATE VARIABLE** - Custom template variable called "appname" to handle different appname(engine)
![image](https://cloud.githubusercontent.com/assets/25632887/22744596/ca347ee8-edeb-11e6-8894-82de2d6dc192.png)

**Comment by torkelo** [comment]
use [[varnmae]] syntax if you want to use a variable in the middle of text

**Comment by kamalvpm777** [comment]
Great. Thanks torkelo, works like a charm !!
