### ISSUE TITLE
[Support Options] Usage of row name in a template

### ISSUE THREAD

**Issue by salvax86** [grafana/grafana#7499]
Please include this information:
- Grafana 4.1.1
- Mixed (Prometheus/InfluxDB)
- Linux

![unbenannt](https://cloud.githubusercontent.com/assets/10816934/22747295/fc065780-ee26-11e6-96cc-19d0d588bd2b.JPG)

Hello everyone

I was trying to make a dynamic dashboard in order to have one panel for different environment, Like on the image above, I have f.e. four strings in a custom variable (hostTemplate) and one query variable to ask about the different servers. I duplicate the row for the custom variable and duplicate the panel for the query variable. Here i expect f.e. in "kafka"-row only the panels for kafka-servers and not the panels for zookeepers too. 

Is it there a possibility to get the row.showTitle for the variable query?

Regards

**Comment by torkelo** [comment]
you cant combine row and panel repeats like this. Since the Host variable has All as value and you repeat a panel based on it, it is going to get repeated for each value.
