### ISSUE TITLE
[BUG] Table Legend not showing all entries

### ISSUE THREAD

**Issue by exbane** [grafana/grafana#7500]
Please include this information:
- What Grafana version are you using? grafana-4.2.0-1485181773pre1.x86_64
- What datasource are you using? InfluxDB 1.1
- What OS are you running grafana on? CentOS7
- What did you do? Upgraded to grafana-4.2.0-1485181773pre1.x86_64 
- What was the expected result? scroll bar for tabled values
- What happened instead? it only shows about 5 to 6 entries then cuts it off

We recently updated to grafana-4.2.0-1485181773pre1.x86_64 to fix the scrolling issue on the Table Legends and it seemed to work fine and then stopped. 

![capture](https://cloud.githubusercontent.com/assets/12447405/22747342/d128b206-edf4-11e6-83ca-5e0895d503ec.PNG)

As you can see in the screenshot it's only listing a few servers - where in the templated query i've selected over 20.. If i select each system individually they work fine and i can see them in the legend - just not when i select them all at the same time. thoughts? 

I've attempted to update to the latest nightly build to see if it will resolve the issue but get an error.. 
Preparing...                          ################################# [100%]
        package grafana-4.2.0-1485181773pre1.x86_64 (which is newer than grafana-4.2.0-6887pre1.x86_64) is already installed

**Comment by torkelo** [comment]
might be related to this InfluxDB breaking change https://github.com/grafana/grafana/issues/7380

try changing InfluxDB option max-row-limit to zero (infinite)
