### ISSUE TITLE
[Feature request] Global Display Overrides for Aliases

### ISSUE THREAD

**Issue by jspada200** [grafana/grafana#7501]
We have a System in which we have groups of data in different categories. If I have two graphs with the same categories I need to set the display overrides on each one. It would be nice to set a global display override that works on the top level and populates down into all dashboards and panels unless it is override on the panel level. This would reduce the amount of work needed to map alias to colors.

**Comment by DanCech** [comment]
See #6806

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
