### ISSUE TITLE
[Bug] Buttons and legend colors missing in several grafana versions on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ma-tri-x** [grafana/grafana#7502]
Hi! I cannot get rid of the following issue:
![screenshot from 2017-02-08 21-44-32](https://cloud.githubusercontent.com/assets/12648792/22756976/56b9b880-ee49-11e6-8e04-c87c761961d6.png)

I see no "save dashboard" and many other buttons though they seem to be active and there are no colors in the legend. I installed grafana from deb files. Tried first 4.x and then downgraded to 2.6.0. It worked but next login the grafana-server service broke down. Could resolve this via
dpkg --configure -a
but then the above issue appears again.

Using 
influxdb
16.04.1 LTS (Xenial Xerus)
same on firefox, chrome, light theme, dark theme

**Comment by torkelo** [comment]
cannot replicate this here with chrome on 16.04 . are you running official builds? 

maybe same as this issue: https://github.com/grafana/grafana/issues/4712 

Must be something special with your system/install as thousands run it without issue on ubuntu 14-16. Very strange. maybe ask in mailing list if you dont find the cause. 

you can look in chrome dev tools network tab, see if any font fail to load/ / not found, maybe some extension or http proxy blocking accessing the fonts

**Comment by ma-tri-x** [comment]
Hi ! Thanks for the quick reply. Unfortunately I'm a noob concerning webserver debugging. Yes, I run official builds.
The thing is that the buttons show up after reinstalling (apt-get purge and dpkg -i thedebfile) but on the next login the grafana-server service crashes. 
Since I'm a noob, I can't figure out what to do if I look into #4712 
Building from source led into some strange errors

# github.com/grafana/grafana/pkg/models
pkg/models/datasource_cache.go:59: unknown http.Transport field 'MaxIdleConns' in struct literal
pkg/models/datasource_cache.go:60: unknown http.Transport field 'IdleConnTimeout' in struct literal
exit status 2
exit status 1

So I'm doomed :-(

**Comment by torkelo** [comment]
the error looks like wrong Go version. 

Grafana server crash? strange, we have no reports of it crashing, did you check grafana server log for why it crashed?

**Comment by ma-tri-x** [comment]
Hi! Yes maybe, I tried the most recent go version, but maybe I better downgrade? Anyway the other issue produced log outputs like the following:
<
2017/02/06 13:27:26 [I] Completed 134.76.92.154 - "GET /public/css/grafana.dark.min.a95b3754.css HTTP/1.1" 404 Not Found 2134 bytes in 3410us
2017/02/06 13:27:27 [I] Completed 134.76.92.154 - "GET /public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 2134 bytes in 819us
2017/02/06 13:27:27 [I] Completed 134.76.92.154 - "GET /public/img/fav32.png HTTP/1.1" 404 Not Found 2134 bytes in 1162us
2017/02/06 13:30:51 [I] Completed 134.76.92.154 - "GET /public/css/grafana.dark.min.a95b3754.css HTTP/1.1" 404 Not Found 2134 bytes in 1173us
2017/02/06 13:30:51 [I] Completed 134.76.92.154 - "GET /public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 2134 bytes in 695us
2017/02/06 13:30:51 [I] Completed 134.76.92.154 - "GET /public/img/fav32.png HTTP/1.1" 404 Not Found 2134 bytes in 860us
2017/02/06 13:31:33 [I] Completed 134.76.92.154 - "GET / HTTP/1.1" 302 Found 29 bytes in 13775us
2017/02/06 13:31:33 [I] Completed 134.76.92.154 - "GET /public/css/grafana.dark.min.a95b3754.css HTTP/1.1" 404 Not Found 2134 bytes in 857us
2017/02/06 13:31:33 [I] Completed 134.76.92.154 - "GET /public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 2134 bytes in 871us
2017/02/06 13:31:33 [I] Completed 134.76.92.154 - "GET /public/img/fav32.png HTTP/1.1" 404 Not Found 2134 bytes in 834us
2017/02/06 13:31:40 [I] Received signal terminated. shutting down
>

**Comment by torkelo** [comment]
You need to restart grafana server after every upgrade (or downgrade)

**Comment by ma-tri-x** [comment]
Hi Torkelo,
I am only a noob concerning network debugging, webservers etc but restarting is even one step before noobiness ;-)
But fortunately -- until now -- the issue could be solved here using the very recent recent version 4.1.2 (I started trying with 4.1.1 or lesser I think when setting up this issue.). That one looks nicer anyway. I'm still curious what it was with the other versions before... I hope it'll stay working now but it looks good so far. Thank you for your quick replies!

**Comment by torkelo** [comment]
The only reason I can see is that your previous version was a bad unofficial build missing files

**Comment by ma-tri-x** [comment]
Yes maybe. But the above error appears if you install ubuntu 16.04 LTS and the type
sudo apt-get install grafana
so it's the "official" repository. Actually, a friend of mine encountered the exact same issue on a completely different machine with the same OS. So I wonder why I'm the only one reporting it.

**Comment by torkelo** [comment]
It is unfortunate that a broken unofficiall package is included in the standard Ubuntu repository

**Comment by ma-tri-x** [comment]
citing http://docs.grafana.org/installation/debian/ :

"
Add the following line to your /etc/apt/sources.list file.

deb https://packagecloud.io/grafana/stable/debian/ jessie main
"

It's not about Ubuntu. Or do you mean dependencies?

**Comment by torkelo** [comment]
sorry I misunderstood you, I thought you said you installed it via the default ubuntu repositories that are added in a base ubuntu install. 

So you installed it with on a Ubuntu 16 from the Grafana project official debian repository (on packagecloud)  ? 

you mention installing and downgrading? Did you restart grafana-server after each upgrade / downgrade? The missing files in the log tell me you upgraded/or downgraded without restarting grafana-server. 

Can you replicate the missing fonts issue?

**Comment by krtschmr** [comment]
i also have that issue. font awesome doesnt seem to be loaded at all

**Comment by xLorix** [comment]
> Hi! I cannot get rid of the following issue: ![screenshot from 2017-02-08 21-44-32](https://cloud.githubusercontent.com/assets/12648792/22756976/56b9b880-ee49-11e6-8e04-c87c761961d6.png)
> I see no "save dashboard" and many other buttons though they seem to be active and there are no colors in the legend...
> Using influxdb 16.04.1 LTS (Xenial Xerus) same on firefox, chrome, light theme, dark theme

I think the missing "icons" issue is in all Grafana 32 bit versions in Ubuntu repositories. 
Found the solution comparing it with the 64 bit, details here: https://github.com/grafana/grafana/issues/4712#issuecomment-934170840

I'm afraid it's a bit late though :-)
