### ISSUE TITLE
[Bug] 502 bad gateway when adding data source for PostgresQL

### ISSUE THREAD

**Issue by Kavinsp** [grafana/grafana#7505]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
Grafana 4.0.1
- What datasource are you using?
grafana-sqldb-datasource (grafana-sqldb_20160615.tar.gz)
- What OS are you running grafana on?
RHEL 6.4 (Linux)
- What did you do?
Trying to add the sqldb data source using the Grafana UI
- What was the expected result?
Data source should be added successfully
- What happened instead?
Saving and testing the datasource ended up with the following error
Unknown error
SqlDB Error: undefined

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by bergquist** [comment]
Where did you get `grafana-sqldb_20160615.tar.gz` ? that's not build by us. 

We currently does not support sql databases as datasources so I suggest you direct you question to who ever built that version.

**Comment by Kavinsp** [comment]
Okay . In order to use postgresQL database . do you have any data source plugin?

**Comment by bergquist** [comment]
@Kavinsp Not at the moment. But we might add it in the future all thou we done have any ETA right now.
