### ISSUE TITLE
[Bug] Error logging not working for Grafana 4.0.1

### ISSUE THREAD

**Issue by Kavinsp** [grafana/grafana#7506]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
Grafana 4.0.1
- What datasource are you using?
grafana-sqldb-datasource (grafana-sqldb_20160615.tar.gz)
- What OS are you running grafana on?
RHEL 6.4 (Linux)
- What did you do?
Trying to enable the log levels for grafana
- What was the expected result?
All log levels should be reported to the log file
- What happened instead?
Only info log is reported

COnfig file:
```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
mode = console, file

# Either "trace", "debug", "info", "warn", "error", "critical", default is "info"
level = info

# optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
;filters =


# For "console" mode only
[log.console]
;level = 

# log line format, valid options are text, console and json
;format =

# For "file" mode only
[log.file]
level = error

# log line format, valid options are text, console and json
format = text

# This enables automated log rotate(switch of following options), default is true
;log_rotate = true

# Max line number of single file, default is 1000000
;max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
;max_size_shift = 28

# Segment log daily, default is true
;daily_rotate = true

# Expired days of log file(delete after max days), default is 7
;max_days = 7

[log.syslog]
;level =

# log line format, valid options are text, console and json
;format = text

# Syslog network type and address. This can be udp, tcp, or unix. If left blank, the default unix endpoints will be used.
;network =
;address =

# Syslog facility. user, daemon and local0 through local7 are valid.
;facility =

# Syslog tag. By default, the process' argv[0] is used.
;tag =
```

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by bergquist** [comment]
grafana-sqldb_20160615.tar.gz is not from us so its really hard to debug this.

But its seems like you have a `, ` char as seperator instead of just a space
```
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
mode = console, file
```
