### ISSUE TITLE
Burp Scan Reports : Strict Transport Security not enforced

### ISSUE THREAD

**Issue by AshrithaSB** [grafana/grafana#75063]
### What happened?

Used ingress and enabled `strict_transport_security` feature in security section of `grafana.ini` to use Grafana in HTTPS mode. Confirmed with the response headers after installation that HSTS(`strict_transport_security`) is enabled. Performed the Burp Scan for Grafana and could still find the issue "Strict Transport Security not enforced" in the reports for few links that redirects to .js scripts as well as robots.txt in public/build folder .

### What did you expect to happen?

The issue related to Strict Transport Security not enforced shouldn't be raised in the Scan reports.

### Did this work before?

Had the same issue earlier too

### How do we reproduce it?

1. Install Grafana in HTTPS mode .
2. Enable strict_transport_security feature in .Values.grafana_ini.security section
3. Perform the Burp Scan

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @AshrithaSB,

Thanks for opening this issue.


Please review the submission template and include more details:

* What Grafana version and what operating system are you using?
* What is your datasource?
* Can you copy/paste the configuration(s) of grafana.ini file?
* Did you receive any errors in the Grafana UI or in related logs? If so, please tell us **exactly** what they were.
* Did you follow any online instructions? If so, what is the URL?

**Comment by AshrithaSB** [comment]
Grafana version: 10.0.3
Datasource: Prometheus

grafana_ini:
   security:
      strict_transport_security: true

No errors received in pods or logs
referred: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#strict_transport_security

**Comment by mildwonkey** [comment]
Hi, @AshrithaSB , thanks for reporting this.!
I'll label this accordingly, but so you know, we have a suite of security scanners and tools that we prioritize over issues reported by other tools that aren't part of our standard suite.
