### ISSUE TITLE
[Feature request] Support authorization callback URL with HTTPS

### ISSUE THREAD

**Issue by keimoon** [grafana/grafana#7507]
Grafana uses plain HTTP as authorization callback URL for auth.github and auth.google. This would be nice if a configuration is added to enable setting callback URL to use HTTPS, for example `https://<my_grafana_server_name_or_ip>:<grafana_server_port>/login/github`

**Comment by torkelo** [comment]
If you set grafana ini option root_url correctly the  your good to go :)
