### ISSUE TITLE
Add enable and disable time interval option to single stat

### ISSUE THREAD

**Issue by nimantha** [grafana/grafana#7508]
[Feature request] The single stat data panel breaks down metrics into time buckets upon every request. This results in the accuracy of the actual singlestat value changing with the time range and the group by time interval. In order to get accurate values, the group by time interval must be greater than the time range because the data needs to be split into exactly one bucket to show accurate values. 
- grafana-4.1.1
- elasticsearch
- SUSE Linux Enterprise Server 11 SP3
- I created a single stat that shows a max value of a linearly increasing metric.
- A continuously increasing value irrespective of the time range. 
- The value kept changing as the time range was changed and the only way to get the correct value was to increase the time interval to a value that is greater than the time range.

Metic query
https://cloud.githubusercontent.com/assets/13083944/22778919/b8a9d4cc-eede-11e6-8bd8-f6d32a26d1e8.PNG

Request : 
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"ssm_stats"}
{"size":0,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1486633416073","lte":"1486633716073","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"2":{"date_histogram":{"interval":"2s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1486633416073","max":"1486633716073"},"format":"epoch_millis"},"aggs":{"1":{"max":{"field":"new_customers.total"}}}}}}

Response : 
{"responses":[{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":7628,"max_score":0.0,"hits":[]},"aggregations":{"2":{"buckets":[{"key_as_string":"1486633416000","key":1486633416000,"doc_count":53,"1":{"value":1904566.0}},{"key_as_string":"1486633418000","key":1486633418000,"doc_count":53,"1":{"value":1905414.0}},{"key_as_string":"1486633420000","key":1486633420000,"doc_count":53,"1":{"value":1906266.0}},{"key_as_string":"1486633422000","key":1486633422000,"doc_count":26,"1":{"value":1906691.0}},{"key_as_string":"1486633424000","key":1486633424000,"doc_count":54,"1":{"value":1907542.0}},{"key_as_string":"1486633426000","key":1486633426000,"doc_count":53,"1":{"value":1908390.0}},{"key_as_string":"1486633428000","key":1486633428000,"doc_count":56,"1":{"value":1909244.0}},{"key_as_string":"1486633430000","key":1486633430000,"doc_count":53,"1":{"value":1910098.0}},{"key_as_string":"1486633432000","key":1486633432000,"doc_count":52,"1":{"value":1910944.0}},{"key_as_string":"1486633434000","key":1486633434000,"doc_count":52,"1":{"value":1911798.0}},{"key_as_string":"1486633436000","key":1486633436000,"doc_count":63,"1":{"value":1913075.0}},{"key_as_string":"1486633438000","key":1486633438000,"doc_count":53,"1":{"value":1913926.0}},{"key_as_string":"1486633440000","key":1486633440000,"doc_count":52,"1":{"value":1914774.0}},{"key_as_string":"1486633442000","key":1486633442000,"doc_count":55,"1":{"value":1915628.0}},{"key_as_string":"1486633444000","key":1486633444000,"doc_count":52,"1":{"value":1916476.0}},{"key_as_string":"1486633446000","key":1486633446000,"doc_count":53,"1":{"value":1917328.0}},{"key_as_string":"1486633448000","key":1486633448000,"doc_count":53,"1":{"value":1918182.0}},{"key_as_string":"1486633450000","key":1486633450000,"doc_count":52,"1":{"value":1919028.0}},{"key_as_string":"1486633452000","key":1486633452000,"doc_count":34,"1":{"value":1919458.0}},{"key_as_string":"1486633454000","key":1486633454000,"doc_count":47,"1":{"value":1920306.0}},{"key_as_string":"1486633456000","key":1486633456000,"doc_count":53,"1":{"value":1921160.0}},{"key_as_string":"1486633458000","key":1486633458000,"doc_count":56,"1":{"value":1922012.0}},{"key_as_string":"1486633460000","key":1486633460000,"doc_count":52,"1":{"value":1922860.0}},{"key_as_string":"1486633462000","key":1486633462000,"doc_count":53,"1":{"value":1923712.0}},{"key_as_string":"1486633464000","key":1486633464000,"doc_count":52,"1":{"value":1924566.0}},{"key_as_string":"1486633466000","key":1486633466000,"doc_count":63,"1":{"value":1925839.0}},{"key_as_string":"1486633468000","key":1486633468000,"doc_count":53,"1":{"value":1926690.0}},{"key_as_string":"1486633470000","key":1486633470000,"doc_count":52,"1":{"value":1927543.0}},{"key_as_string":"1486633472000","key":1486633472000,"doc_count":54,"1":{"value":1928386.0}},{"key_as_string":"1486633474000","key":1486633474000,"doc_count":53,"1":{"value":1929244.0}},{"key_as_string":"1486633476000","key":1486633476000,"doc_count":52,"1":{"value":1930098.0}},{"key_as_string":"1486633478000","key":1486633478000,"doc_count":53,"1":{"value":1930944.0}},{"key_as_string":"1486633480000","key":1486633480000,"doc_count":53,"1":{"value":1931798.0}},{"key_as_string":"1486633482000","key":1486633482000,"doc_count":53,"1":{"value":1932650.0}},{"key_as_string":"1486633484000","key":1486633484000,"doc_count":28,"1":{"value":1933075.0}},{"key_as_string":"1486633486000","key":1486633486000,"doc_count":52,"1":{"value":1933927.0}},{"key_as_string":"1486633488000","key":1486633488000,"doc_count":53,"1":{"value":1934774.0}},{"key_as_string":"1486633490000","key":1486633490000,"doc_count":56,"1":{"value":1935628.0}},{"key_as_string":"1486633492000","key":1486633492000,"doc_count":53,"1":{"value":1936477.0}},{"key_as_string":"1486633494000","key":1486633494000,"doc_count":52,"1":{"value":1937328.0}},{"key_as_string":"1486633496000","key":1486633496000,"doc_count":63,"1":{"value":1938606.0}},{"key_as_string":"1486633498000","key":1486633498000,"doc_count":52,"1":{"value":1939460.0}},{"key_as_string":"1486633500000","key":1486633500000,"doc_count":53,"1":{"value":1940306.0}},{"key_as_string":"1486633502000","key":1486633502000,"doc_count":52,"1":{"value":1941160.0}},{"key_as_string":"1486633504000","key":1486633504000,"doc_count":54,"1":{"value":1942013.0}},{"key_as_string":"1486633506000","key":1486633506000,"doc_count":53,"1":{"value":1942860.0}},{"key_as_string":"1486633508000","key":1486633508000,"doc_count":53,"1":{"value":1943712.0}},{"key_as_string":"1486633510000","key":1486633510000,"doc_count":53,"1":{"value":1944566.0}},{"key_as_string":"1486633512000","key":1486633512000,"doc_count":51,"1":{"value":1945414.0}},{"key_as_string":"1486633514000","key":1486633514000,"doc_count":28,"1":{"value":1945836.0}},{"key_as_string":"1486633516000","key":1486633516000,"doc_count":54,"1":{"value":1946691.0}},{"key_as_string":"1486633518000","key":1486633518000,"doc_count":53,"1":{"value":1947542.0}},{"key_as_string":"1486633520000","key":1486633520000,"doc_count":56,"1":{"value":1948390.0}},{"key_as_string":"1486633522000","key":1486633522000,"doc_count":53,"1":{"value":1949244.0}},{"key_as_string":"1486633524000","key":1486633524000,"doc_count":52,"1":{"value":1950098.0}},{"key_as_string":"1486633526000","key":1486633526000,"doc_count":63,"1":{"value":1951374.0}},{"key_as_string":"1486633528000","key":1486633528000,"doc_count":52,"1":{"value":1952221.0}},{"key_as_string":"1486633530000","key":1486633530000,"doc_count":53,"1":{"value":1953075.0}},{"key_as_string":"1486633532000","key":1486633532000,"doc_count":52,"1":{"value":1953927.0}},{"key_as_string":"1486633534000","key":1486633534000,"doc_count":55,"1":{"value":1954774.0}},{"key_as_string":"1486633536000","key":1486633536000,"doc_count":52,"1":{"value":1955628.0}},{"key_as_string":"1486633538000","key":1486633538000,"doc_count":53,"1":{"value":1956476.0}},{"key_as_string":"1486633540000","key":1486633540000,"doc_count":53,"1":{"value":1957328.0}},{"key_as_string":"1486633542000","key":1486633542000,"doc_count":52,"1":{"value":1958181.0}},{"key_as_string":"1486633544000","key":1486633544000,"doc_count":27,"1":{"value":1958605.0}},{"key_as_string":"1486633546000","key":1486633546000,"doc_count":54,"1":{"value":1959459.0}},{"key_as_string":"1486633548000","key":1486633548000,"doc_count":53,"1":{"value":1960306.0}},{"key_as_string":"1486633550000","key":1486633550000,"doc_count":56,"1":{"value":1961160.0}},{"key_as_string":"1486633552000","key":1486633552000,"doc_count":52,"1":{"value":1962012.0}},{"key_as_string":"1486633554000","key":1486633554000,"doc_count":53,"1":{"value":1962860.0}},{"key_as_string":"1486633556000","key":1486633556000,"doc_count":63,"1":{"value":1964138.0}},{"key_as_string":"1486633558000","key":1486633558000,"doc_count":52,"1":{"value":1964989.0}},{"key_as_string":"1486633560000","key":1486633560000,"doc_count":52,"1":{"value":1965838.0}},{"key_as_string":"1486633562000","key":1486633562000,"doc_count":53,"1":{"value":1966691.0}},{"key_as_string":"1486633564000","key":1486633564000,"doc_count":54,"1":{"value":1967542.0}},{"key_as_string":"1486633566000","key":1486633566000,"doc_count":53,"1":{"value":1968390.0}},{"key_as_string":"1486633568000","key":1486633568000,"doc_count":53,"1":{"value":1969244.0}},{"key_as_string":"1486633570000","key":1486633570000,"doc_count":52,"1":{"value":1970098.0}},{"key_as_string":"1486633572000","key":1486633572000,"doc_count":53,"1":{"value":1970944.0}},{"key_as_string":"1486633574000","key":1486633574000,"doc_count":26,"1":{"value":1971374.0}},{"key_as_string":"1486633576000","key":1486633576000,"doc_count":53,"1":{"value":1972220.0}},{"key_as_string":"1486633578000","key":1486633578000,"doc_count":54,"1":{"value":1973075.0}},{"key_as_string":"1486633580000","key":1486633580000,"doc_count":53,"1":{"value":1973926.0}},{"key_as_string":"1486633582000","key":1486633582000,"doc_count":56,"1":{"value":1974774.0}},{"key_as_string":"1486633584000","key":1486633584000,"doc_count":53,"1":{"value":1975628.0}},{"key_as_string":"1486633586000","key":1486633586000,"doc_count":52,"1":{"value":1976476.0}},{"key_as_string":"1486633588000","key":1486633588000,"doc_count":63,"1":{"value":1977753.0}},{"key_as_string":"1486633590000","key":1486633590000,"doc_count":52,"1":{"value":1978605.0}},{"key_as_string":"1486633592000","key":1486633592000,"doc_count":53,"1":{"value":1979459.0}},{"key_as_string":"1486633594000","key":1486633594000,"doc_count":52,"1":{"value":1980306.0}},{"key_as_string":"1486633596000","key":1486633596000,"doc_count":54,"1":{"value":1981160.0}},{"key_as_string":"1486633598000","key":1486633598000,"doc_count":53,"1":{"value":1982013.0}},{"key_as_string":"1486633600000","key":1486633600000,"doc_count":53,"1":{"value":1982860.0}},{"key_as_string":"1486633602000","key":1486633602000,"doc_count":53,"1":{"value":1983712.0}},{"key_as_string":"1486633604000","key":1486633604000,"doc_count":34,"1":{"value":1984138.0}},{"key_as_string":"1486633606000","key":1486633606000,"doc_count":45,"1":{"value":1984989.0}},{"key_as_string":"1486633608000","key":1486633608000,"doc_count":54,"1":{"value":1985839.0}},{"key_as_string":"1486633610000","key":1486633610000,"doc_count":53,"1":{"value":1986691.0}},{"key_as_string":"1486633612000","key":1486633612000,"doc_count":56,"1":{"value":1987542.0}},{"key_as_string":"1486633614000","key":1486633614000,"doc_count":52,"1":{"value":1988390.0}},{"key_as_string":"1486633616000","key":1486633616000,"doc_count":53,"1":{"value":1989244.0}},{"key_as_string":"1486633618000","key":1486633618000,"doc_count":63,"1":{"value":1990520.0}},{"key_as_string":"1486633620000","key":1486633620000,"doc_count":52,"1":{"value":1991374.0}},{"key_as_string":"1486633622000","key":1486633622000,"doc_count":52,"1":{"value":1992221.0}},{"key_as_string":"1486633624000","key":1486633624000,"doc_count":53,"1":{"value":1993075.0}},{"key_as_string":"1486633626000","key":1486633626000,"doc_count":54,"1":{"value":1993926.0}},{"key_as_string":"1486633628000","key":1486633628000,"doc_count":53,"1":{"value":1994774.0}},{"key_as_string":"1486633630000","key":1486633630000,"doc_count":52,"1":{"value":1995628.0}},{"key_as_string":"1486633632000","key":1486633632000,"doc_count":53,"1":{"value":1996476.0}},{"key_as_string":"1486633634000","key":1486633634000,"doc_count":53,"1":{"value":1997328.0}},{"key_as_string":"1486633636000","key":1486633636000,"doc_count":26,"1":{"value":1997754.0}},{"key_as_string":"1486633638000","key":1486633638000,"doc_count":53,"1":{"value":1998605.0}},{"key_as_string":"1486633640000","key":1486633640000,"doc_count":54,"1":{"value":1999458.0}},{"key_as_string":"1486633642000","key":1486633642000,"doc_count":53,"1":{"value":2000306.0}},{"key_as_string":"1486633644000","key":1486633644000,"doc_count":56,"1":{"value":2001160.0}},{"key_as_string":"1486633646000","key":1486633646000,"doc_count":52,"1":{"value":2002012.0}},{"key_as_string":"1486633648000","key":1486633648000,"doc_count":64,"1":{"value":2003290.0}},{"key_as_string":"1486633650000","key":1486633650000,"doc_count":52,"1":{"value":2004138.0}},{"key_as_string":"1486633652000","key":1486633652000,"doc_count":52,"1":{"value":2004989.0}},{"key_as_string":"1486633654000","key":1486633654000,"doc_count":53,"1":{"value":2005838.0}},{"key_as_string":"1486633656000","key":1486633656000,"doc_count":54,"1":{"value":2006691.0}},{"key_as_string":"1486633658000","key":1486633658000,"doc_count":52,"1":{"value":2007542.0}},{"key_as_string":"1486633660000","key":1486633660000,"doc_count":53,"1":{"value":2008390.0}},{"key_as_string":"1486633662000","key":1486633662000,"doc_count":53,"1":{"value":2009244.0}},{"key_as_string":"1486633664000","key":1486633664000,"doc_count":53,"1":{"value":2010098.0}},{"key_as_string":"1486633666000","key":1486633666000,"doc_count":26,"1":{"value":2010520.0}},{"key_as_string":"1486633668000","key":1486633668000,"doc_count":53,"1":{"value":2011374.0}},{"key_as_string":"1486633670000","key":1486633670000,"doc_count":54,"1":{"value":2012221.0}},{"key_as_string":"1486633672000","key":1486633672000,"doc_count":53,"1":{"value":2013076.0}},{"key_as_string":"1486633674000","key":1486633674000,"doc_count":56,"1":{"value":2013927.0}},{"key_as_string":"1486633676000","key":1486633676000,"doc_count":52,"1":{"value":2014774.0}},{"key_as_string":"1486633678000","key":1486633678000,"doc_count":53,"1":{"value":2015629.0}},{"key_as_string":"1486633680000","key":1486633680000,"doc_count":63,"1":{"value":2016904.0}},{"key_as_string":"1486633682000","key":1486633682000,"doc_count":52,"1":{"value":2017754.0}},{"key_as_string":"1486633684000","key":1486633684000,"doc_count":52,"1":{"value":2018605.0}},{"key_as_string":"1486633686000","key":1486633686000,"doc_count":53,"1":{"value":2019459.0}},{"key_as_string":"1486633688000","key":1486633688000,"doc_count":54,"1":{"value":2020306.0}},{"key_as_string":"1486633690000","key":1486633690000,"doc_count":53,"1":{"value":2021160.0}},{"key_as_string":"1486633692000","key":1486633692000,"doc_count":53,"1":{"value":2022012.0}},{"key_as_string":"1486633694000","key":1486633694000,"doc_count":52,"1":{"value":2022860.0}},{"key_as_string":"1486633696000","key":1486633696000,"doc_count":27,"1":{"value":2023290.0}},{"key_as_string":"1486633698000","key":1486633698000,"doc_count":52,"1":{"value":2024138.0}},{"key_as_string":"1486633700000","key":1486633700000,"doc_count":53,"1":{"value":2024990.0}},{"key_as_string":"1486633702000","key":1486633702000,"doc_count":54,"1":{"value":2025839.0}},{"key_as_string":"1486633704000","key":1486633704000,"doc_count":53,"1":{"value":2026691.0}},{"key_as_string":"1486633706000","key":1486633706000,"doc_count":56,"1":{"value":2027543.0}},{"key_as_string":"1486633708000","key":1486633708000,"doc_count":52,"1":{"value":2028390.0}},{"key_as_string":"1486633710000","key":1486633710000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1486633712000","key":1486633712000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1486633714000","key":1486633714000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1486633716000","key":1486633716000,"doc_count":0,"1":{"value":null}}]}},"status":200}]}

**Comment by torkelo** [comment]
you can disable it by increasing the date histogram interval. Then you wont be able to use the singlestat sparkline (trend line) option, but that is fine.

**Comment by nimantha** [comment]
In our scenario it would be ideal if we could use both the trend line and the stat value. Is it possible to do this?

**Comment by torkelo** [comment]
yes, then you need a date histogram interval so you get a time series. In the options tab specify which value of all values returned you want to show (in your case Max), make sure you have Max metric in your query as well
