### ISSUE TITLE
grafana 9.5.9 也没加载慢

### ISSUE THREAD

**Issue by Heyz6** [grafana/grafana#75081]
### What happened?

当我从7.5.4 版本 grafana 升级到 9.5.10 版本后 发现
页面加载慢,并且 当我选择 24小时展示的时候,发现 network 在下载 query 数据,并且 没有停止的意思,这和 7.5.4 版本是不同的,这导致 我的网络带宽被占用,以及 导致grafana oomkilled ,我改如何解决

### What did you expect to happen?

grafana 页面无法展示,一致 wait 等待中

### Did this work before?

grafana 7.5.4

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @Heyz6,

Thanks for opening this issue.

Grafana's current latest stable version is 10.1.x and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).

Also, if possible then please try to explain the issue back in English once it is reproducible on the latest stable version.

Incase if it is not possible then you can try to send a video screencast which can explain what problem you might be having
