### ISSUE TITLE
Alerting: unable to select panel in collapsed row

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#75093]
### What happened?

When creating/editing an alert rule it's not possible to select a panel (in "Dashboard and panel" section) that is inside a collapsed row.

### What did you expect to happen?

To be able to select a panel independently of it's "visibility" state in a dashboard.

### Did this work before?

Not via the current functionality.
It was always possible to select the panel in earlier grafana versions (up to 10.0.* I believe) because the panelID was manually set in a text field.

### How do we reproduce it?

1. Add a panel to a "row" in a dashboard
2. Collapse the row
3. Save the dashboard
4. The panel is not visible while trying to select the "Dashboard and panel" inside the alert

Workaround:
1. Expand the "row" where the panel you want to select is
2. Save the dashboard
3. Go to the alert rule and select the panel by browsing the "Dashboard and panel"
4. Save the alert rule
5. Collapse the "row" again and save the dashboard

Note:
After adding a pannel which is then added to a "collapsed row", when going back to the alert rule, the selected "Panel <ID>" is shown instead of the panel name (and corresponding hyper-link to it).

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.1.2
OS: linux
Browser: chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
thank you for reporting this bug @salavessa 

I have reproduced it in 10.1.0, but not in 9.5.6

**Comment by armandgrillet** [comment]
Thanks for the report. We were able to reproduce this bug and the dashboards API returned the panels in the collapsed rows. The issue is thus on the alerting side of things.
