### ISSUE TITLE
Data Source: Error 500 upon loading float with Databricks Connector

### ISSUE THREAD

**Issue by bartvdooren** [grafana/grafana#75096]
### What happened?

We are using the Databricks connector, version 1.0.1, within an Azure Managed Grafana instance.
When loading an unity catalog table using this connector, we get an 500 error, only when we load a table with a float.

The only way to resolve the issue to perform a CAST as follows:
CAST(`<catalog>`.`<schema>`.`<table>`.`<column>` AS NUMERIC(10,2)) AS XX

### What did you expect to happen?

When loading the data using the Databricks connector it would load smoothly with float values and no custom CAST having to be made. We also receive a simple 500 error, not explaining the issue, making a select * not possible.

![image](https://github.com/grafana/grafana/assets/15154392/8da4bb72-a68d-4d5e-8421-31689a77ac55)

### Did this work before?

This has never worked correctly.

### How do we reproduce it?

1. Create a table in unity catalog with a float
2. Load the table inside grafana using the databricks connector (e.g. select * table)
3. Receive 500 error

### Is the bug inside a dashboard panel?

Dashboard panel are unable to load due to this.

### Environment (with versions)?

Grafana: 9.5.8
OS: W10
Browser: Firefox

### Grafana platform?

Other

### Datasource(s)?

Databricks 1.0.1

**Comment by usmangt** [comment]
Hi @bartvdooren,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.
