### ISSUE TITLE
[Bug] Cannot select datasource variable as datasource option in template variables

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#7510]
*  Grafana v4.2.0-pre1 (commit: bccb650) 
* graphite

problem:
* open a graphite dashboard (in my case the dashboard i test with has some template variables already existing - it's https://grafana.net/dashboards/338)
* introduce a new template variable to select a graphite datasource, name it `datasource`
* go to the edit page for one of the pre-existing template variables, or create a new one

expected:
- in the datasource field, i can select `$datasource'

experienced:
- in the datasource field i can only select a datasource by name, not the variable.

What I also tried to no avail:
* move the datasource variable up so it's on top
* save dashboard and reload the page.

thanks,
Dieter

**Comment by bergquist** [comment]
Any chance you forgot to click `Add` after creating the datasource variable? That happens to me sometimes.

**Comment by Dieterbe** [comment]
No it's there. That's how I'm able to bring it to the top with the arrows (which doesn't help)
