### ISSUE TITLE
[Bug] Documentation links broken on some pages

### ISSUE THREAD

**Issue by ddhirajkumar** [grafana/grafana#7512]
All the links at the bottom of the following page are broken:-
http://docs.grafana.org/datasources/kairosdb/

<img width="1433" alt="image" src="https://cloud.githubusercontent.com/assets/6774758/22792595/2a086c92-eea2-11e6-8f9f-e4eca65a21f3.png">

**Comment by torkelo** [comment]
thanks, need to remove that link and page!

**Comment by bergquist** [comment]
Cant find this file in grafana/grafana. stuck in cdn?

**Comment by torkelo** [comment]
fixed, (by removing KairosDB docs)
