### ISSUE TITLE
Loki Query Builder: No UI option for `bool` operator in loki query builder for nested binary comparison operations

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#75122]
### What happened?

Taking the first example from the logsQL docs under "on and ignoring" keywords: https://grafana.com/docs/loki/latest/query/#keywords-on-and-ignoring
`max by(machine) (count_over_time({app="foo"}[1m])) > bool ignoring(machine) avg(count_over_time({app="foo"}[1m]))`

We'll see that the query builder doesn't work with this example and the "bool" operator is always stripped out when any change is made in the query builder.
The example query above becomes
`max by(machine) (count_over_time({app="foo"}[1m])) > ignoring(machine) avg(count_over_time({app="foo"}[1m]))`
And you'll see that there's no place for the "bool" operator to go.
<img width="925" alt="image" src="https://github.com/grafana/grafana/assets/109082771/4e8bf417-e86e-474f-82e1-8112b4375825">

This issue is being created to tackle the problem of not being any allowance in the UI for the bool operator when used with the binary operation with query. 

https://github.com/grafana/grafana/issues/75119 and https://github.com/grafana/grafana/pull/74950 deal with a related bug in which the boolean operator is causing the parser to strip out the input to the on or ignoring functions.

### What did you expect to happen?

Query builder shouldn't be removing parts of the query

### Did this work before?

No

### How do we reproduce it?

1. Add this query in logQL or promQL code editor `max by(machine) (count_over_time({app="foo"}[1m])) > bool ignoring(machine) avg(count_over_time({app="foo"}[1m]))`
2. Change the query builder
3. Change something
4. See that bool was stripped out.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Loki, Prometheus

**Comment by gtk-grafana** [comment]
@catherineymgui @niat22 TL;DR we need to add a checkbox to the nested binary operator for the `bool` modifier:
<img width="495" alt="image" src="https://github.com/grafana/grafana/assets/109082771/3f5d2333-8dde-484b-bd7f-7986dfa4ecf3">

...just like we already do for the non-nested operations:
<img width="168" alt="image" src="https://github.com/grafana/grafana/assets/109082771/2ac9cae4-24f8-411e-b923-6cdbcbb497a4">

This should be a pretty tiny change, but figured I'd ping you both and give us the opportunity to sync up any potential design changes.

**Comment by niat22** [comment]
Thank you Galen. Perhaps @catherineymgui has more insights, since the query builder hasn't been covered by me yet.

**Comment by catherineymgui** [comment]
Yeah I'm okay with adding the checkmark?

As a side note how do you use the builder to get this?

<img width="685" alt="Screenshot 2023-09-27 at 09 32 15" src="https://github.com/grafana/grafana/assets/5264102/4674d1e4-e339-4700-8c6b-7201adf60d8c">

**Comment by gtk-grafana** [comment]
@catherineymgui 
<img width="658" alt="image" src="https://github.com/grafana/grafana/assets/109082771/f5ed00f2-1497-449d-8453-59f0f0658f15">

It's the `binary operation with query` operation
