### ISSUE TITLE
Data Sources: Data Source ID used instead of Database Name

### ISSUE THREAD

**Issue by keck-in-space** [grafana/grafana#75130]
### What happened?

I have started from a fresh download of Grafana 10.1.2 on Windows 10. I am running MariaDB 10.11.5.

![image](https://github.com/grafana/grafana/assets/32853381/5765060f-e841-4a71-a5c7-9ccf5981810a)

I have added the Data Source for the local MariaDB instance and it validates successfully.

<img width="806" alt="data_source2" src="https://github.com/grafana/grafana/assets/32853381/68e53626-d9a8-4bb4-93c3-d6f5737f6462">

The issue appears when I attempt to use a Data Source Variable on a Dashboard. I am not able to use the `$Database.` variable to select the database. The variable appears to use the Data Source's ID instead of the name.

<img width="1004" alt="data_source" src="https://github.com/grafana/grafana/assets/32853381/fa6b2fd5-477f-4fbb-bb28-1c6e9b8bc023">

If I do not use the variable and instead manually specify the database name it works correctly.

<img width="1016" alt="data_source1" src="https://github.com/grafana/grafana/assets/32853381/27180998-3921-4f4c-a19a-16b3c2497de6">

Same behavior as #74777.

### What did you expect to happen?

When using the `$Database.` variable, the correct data source is used instead of the ID of the data source.

### Did this work before?

Yes, this worked before in 10.1.0.

### How do we reproduce it?

1. Add a MariaDB database via the MySQL plugin
2. Create a new dashboard and add a Data Source Variable named `Database`
3. Create a new panel and attempt to use the `$Database.` variable to select data.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | table @ 10.1.2 |
| Grafana | 10.1.2 (2b2d40ba32) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "type": "table",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "id": 2,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "executedQueryString": "select * from dd758a09-5f4f-427c-af59-9b905b60c35e.test_table "
                },
                "fields": []
              },
              "data": {
                "values": []
              }
            }
          ]
        }
      ],
      "options": {
        "showHeader": true,
        "cellHeight": "sm",
        "footer": {
          "show": false,
          "reducer": [
            "sum"
          ],
          "countRows": false,
          "fields": ""
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "pluginVersion": "10.1.2"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 10.1.2</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[mysql]</td>\n    </tr>\n    \n    <tr><th>Data</th><td>Error 1 frames, 0 fields, 0 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.1.2 (2b2d40ba32) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"type\": \"table\",\n  \"title\": \"Panel Title\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"datasource\": {\n    \"uid\": \"${Database}\",\n    \"type\": \"mysql\"\n  },\n  \"id\": 1,\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"mysql\",\n        \"uid\": \"${Database}\"\n      },\n      \"refId\": \"A\",\n      \"format\": \"table\",\n      \"rawSql\": \"select * from ${Database}.test_table \",\n      \"editorMode\": \"code\",\n      \"sql\": {\n        \"columns\": [\n          {\n            \"type\": \"function\",\n            \"parameters\": []\n          }\n        ],\n        \"groupBy\": [\n          {\n            \"type\": \"groupBy\",\n            \"property\": {\n              \"type\": \"string\"\n            }\n          }\n        ],\n        \"limit\": 50\n      },\n      \"dataset\": \"gpx2_flight\",\n      \"rawQuery\": true\n    }\n  ],\n  \"options\": {\n    \"showHeader\": true,\n    \"cellHeight\": \"sm\",\n    \"footer\": {\n      \"show\": false,\n      \"reducer\": [\n        \"sum\"\n      ],\n      \"countRows\": false,\n      \"fields\": \"\"\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"cellOptions\": {\n          \"type\": \"auto\"\n        },\n        \"inspect\": false\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"10.1.2\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2023-09-19 18:11:57",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2023-09-19T16:11:57.598Z",
    "to": "2023-09-19T22:11:57.598Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.1.2
OS: Windows 10
Browser: Firefox 102.15.1esr (32-bit) and Edge Version 117.0.2045.31 (Official build) (64-bit)
Data Source: MariaDB 10.11.5 via MySQL Plugin

### Grafana platform?

A downloaded binary

### Datasource(s)?

MariaDB 10.11.5 with the MySQL Data Source Plugin

**Comment by usmangt** [comment]
:Hi @keck-in-space,

Thanks for opening this issue.

This seems more of a syntax issue rather than an actual issue. Please look at the Grafana-MySQL documentation where it explains as how to use the query variable:

https://grafana.com/docs/grafana/latest/datasources/mysql/#using-variables-in-queries

Let us know if this helps.

**Comment by keck-in-space** [comment]
Hello!

Thanks for the response. I reviewed the documentation listed and tried the two listed syntaxes, but neither of them worked.

Here's what I tried:

Per the docs, use `$Database`:
![image](https://github.com/grafana/grafana/assets/32853381/527ef933-e21f-413a-8b01-deaaedce4378)

I get the same error as before:

![image](https://github.com/grafana/grafana/assets/32853381/b0b4e29d-ed71-4cec-8e22-ba9a531b780c)

Per the docs, use `[[Database]]`

![image](https://github.com/grafana/grafana/assets/32853381/54a2752a-e614-4b6f-a8d2-28b9487e0b03)

I get the same error as before:

![image](https://github.com/grafana/grafana/assets/32853381/eb87faa7-ec7e-43c6-b1b9-51b1af0070a6)

I re-ran the query each time.

Am I missing something from my reading of the docs?

Here's the page I used: https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#variable-syntax

I also tried using `${Database}`, but got the same error again. I'm really confused as to why this would stop working in an existing dashboard.

**Comment by AmrikSD** [comment]
I've noticed what I think is the same thing. 
Since `10.1.1` when we use a variable referencing a data source we're seeing uids rather than the string/name that we expected.

We had a very simple panel that just printed out the value of `${Databse}` in large text at the top of a dashboard, to make it very obvious where the data you're looking at. 

Since at least `10.1.1` instead of the name of the prometheus data source represented as text we see a uid instead.

- Minimal example here - https://play.grafana.org/d/fd497d4e-7c50-4d72-b5c5-f7cc38ef3014/amriksd?orgId=1&var-datasource=-DI2VkR4z
- https://gist.github.com/AmrikSD/3bd26fcc3184aed3f8bdb903c09e395f - JSON that you can import assuming the link above is ephermeral 
- Even more strangely, in that example "grafanacloud-prom" seems to show correctly, but not the rest of the datasources.

I'll try tomorrow to find exactly when this behaviour started, but let me know if I can help any other way. Thanks!

**Comment by keck-in-space** [comment]
Thanks @AmrikSD this is very interesting. I have found that changing the variable to `${Database:text}` is a viable workaround for me. I am just not sure why this would have changed from previously working variables without at least a note to say the syntax has changed. 

Thanks for the example and extra information! I will also let you know if I come across anything else helpful.

**Comment by usmangt** [comment]
Thanks all for your input as this always helps.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by gabor** [comment]
hi @keck-in-space , i think this is an intentional change, happened in grafana-10.1.0, you can find this in the [CHANGELOG](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) in the "breaking changes" section for 10.1.0 (search for `The data source template variable type has changed the way it represents its options.`).

the change happened in this PR: https://github.com/grafana/grafana/pull/69259 

(reassigning the issue to @grafana/dashboards-squad , as this is not related to the mysql datasource plugin)

**Comment by axelavargas** [comment]
Hello everyone 👋🏾 , 

Thank you @gabor for helping us investigate this issue 🏅 . Indeed, this was an intentional change, currently any dashboards that are relying on the data source name being returned by `${datasourceVariable}` will have to update all their usages to `${datasourceVariable:text}` in order to get the previous behavior.
Let me know if this solves the problem you are experiencing.

Thank you 🙏🏾

**Comment by john159753** [comment]
Glad I found this thread. This solves the problem I was having too, adding ":text" helped in my case where I was using the data source name in a panel link.

**Comment by keck-in-space** [comment]
This is a great find! I don't know how this slipped my research. I looked on the website, but missed this in the breaking changes section. Thanks!
