### ISSUE TITLE
BarChart: Add option for align 0

### ISSUE THREAD

**Issue by IntermittentNRG** [grafana/grafana#75132]
### What happened?

0 is not aligned between left/right Y-axis of bar-chart

![image](https://github.com/grafana/grafana/assets/66844/c46f8d38-f7ee-4ef1-a083-c1eba33cf47d)

For time series the issue was fixed in pull #52555 and reported in issue #54343. But it is not fixed for bar-chart.

### What did you expect to happen?

I expect 0 to be aligned between left/right Y-axes.

### Did this work before?

It may have worked in old style panels. I have not tried.

### How do we reproduce it?

Use different units or left/right axis in bar chart
One series contains negative values.

### Environment (with versions)?

Grafana: 10.1.1
OS: linux/docker
Browser: Firefox 117.0.1

### Grafana platform?

Kubernetes

**Comment by fatman00** [comment]
Has this feature not been added to the code yet? I have the same issue on 10.3.0.

**Comment by leeoniya** [comment]
the test dashboard attached in https://github.com/grafana/grafana/pull/75136#issue-1903966126 still works for me. please attach a broken one to a new issue.

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/
