### ISSUE TITLE
Alerting: graphLink unable to parse variables

### ISSUE THREAD

**Issue by erroltuparker** [grafana/grafana#75135]
### What happened?

When attempting to use graphLink in alerting with metric based variables, they are printed as text rather then their value query below

```
{{ graphLink "{\"expr\": \"{container=`azure-resourcemanager`}| json | resourceHealth_properties_availabilityState=`{{$labels.availabilityState}}` | resourceHealth_properties_reasonType!=`Customer Initiated` | resourceID=`{{$labels.resourceID}}`\", \"datasource\": \"Loki\"}" }}
```

This then exports the below

```
/explore?left={"datasource":"Loki","queries":[{"datasource":"Loki","expr":"%7Bcontainer%3D%60azure-resourcemanager%60%7D%7C+json+%7C+resourceHealth_properties_availabilityState%3D%60%7B%7B%24labels.availabilityState%7D%7D%60+%7C+resourceHealth_properties_reasonType%21%3D%60Customer+Initiated%60+%7C+resourceID%3D%60%7B%7B%24labels.resourceID%7D%7D%60","instant":false,"range":true,"refId":"A"}],"range":{"from":"now-1h","to":"now"}}
```

### What did you expect to happen?

Output to be as below

```
/explore?left={"datasource":"Loki","queries":[{"datasource":"Loki","expr":"%7Bcontainer%3D%60azure-resourcemanager%60%7D%7C+json+%7C+resourceHealth_properties_availabilityState%3D%60Unhealthy%60+%7C+resourceHealth_properties_reasonType%21%3D%60Customer+Initiated%60+%7C+resourceID%3D%60/subuscriptionid/stuff/resourceid/3245345235-234524234-2342342%60","instant":false,"range":true,"refId":"A"}],"range":{"from":"now-1h","to":"now"}}
```

### Did this work before?

No

### How do we reproduce it?

1. Create loki metric based alert
2. For Summary set below query
```
{{ graphLink "{\"expr\": \"{container=`azure-resourcemanager`}| json | resourceHealth_properties_availabilityState=`{{$labels.availabilityState}}` | resourceHealth_properties_reasonType!=`Customer Initiated` | resourceID=`{{$labels.resourceID}}`\", \"datasource\": \"Loki\"}" }}
```
3. Save alert

### Environment (with versions)?

Grafana: 9.4.7
OS: Ubuntu 22.04.2 LTS
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Prometheus. Loki

**Comment by usmangt** [comment]
Hi @erroltuparker,

Thanks for opening this issue.

Grafana's current latest stable version is 10.1.1 and the version you are using is slightly a bit older. As, there are numerous bug fixes and improvements have been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here and we can investigate further.

**Comment by erroltuparker** [comment]
Hi @usmangt,

I have just tested using the grafanacloud using synthetic monitoring for testing

The exact same issue occurs.

````
{ graphLink "{\"expr\": \"probe_icmp_duration_seconds{job="{{$labels.job }}"}\", \"datasource\": \"grafanacloud-prom\"}"}}
````

**Comment by armandgrillet** [comment]
This is expected behavior as this is how the Prometheus Alertmanager works: https://github.com/prometheus/prometheus/blob/b43358fd43cda5e19fc138a557b11bcf5bc7e408/util/strutil/strconv.go#L33-L38
However, the behavior you suggest might be useful.

**Comment by santihernandezc** [comment]
Hi @erroltuparker, the `graphLink` function takes a plain string, not a template. The Go template engine doesn't support this kind of nesting.

As a workaround, you can use the `printf` function:

```go
// Parse the expression and save it as a variable
{{ $expression := printf "probe_icmp_duration_seconds{job=%q}" $labels.job }}

// Build the JSON string and pass it to graphLink
// graphlink is receiving
//    `{"expr": "probe_icmp_duration_seconds{job="foo"}", "datasource": "grafanacloud-prom"}`
// as input and returning the parsed link
{{ printf "{%q: %q, %q: %q}" "expr" $expression "datasource" "grafanacloud-prom" | graphLink }}
```

There are some examples in the [docs](https://pkg.go.dev/text/template#hdr-Examples) for Go templates.

We're marking this as a feature request, we could achieve the same thing in a more concise way with a custom template function that takes a template string and executes it.

**Comment by erroltuparker** [comment]
Hi @santihernandezc 

Yeah, I was aware of the printf option, I just couldn't figure it out but thanks for the example. I've managed to get my query working as below now using your example

```
{{ $availabilitystate := title $labels.availabilityState }}{{ $expression := printf "{client=%#q, container=`azure-resourcemanager`} | json | resourceHealth_properties_availabilityState=%#q | resourceHealth_properties_reasonType!=`Customer Initiated` | resourceID=%#q" $labels.client $availabilitystate $labels.resourceID }}To view additional information regarding this event click the link below or copy paste it into a browser:

https://tenant.grafana.com{{ printf "{%q : %q, %q: %q}" "expr" $expression "datasource" "Loki" | graphLink }}
```

The url gets broken in the email though, it drops the last } from being hyperlinked, but copy pasting it works.

If this is being looked as a feature request, would love if {{externalurl}} didn't also include the / at the end so that I could then parse.

```
{{ externalurl }}{{ printf "{%q : %q, %q: %q}" "expr" $expression "datasource" "Loki" | graphLink }}
```
