### ISSUE TITLE
time format in field in templating

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#7514]
hello,

- What Grafana version are you using?
4.1
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
mac sierra
- What did you do?
create a templating with the query:
SELECT "computation_time"  FROM "t_m2" where "station"='montana' and "lead_time"='01:00'
 "computation_time" is a field with time values
- What was the expected result?
value in human time format 
- What happened instead?
the time is in  epoch unix timestamp
![templating](https://cloud.githubusercontent.com/assets/20662503/22792752/15e871ac-eeee-11e6-8f10-31bdb52ac5da.png).

 In influxdb the values have the right format.
 When I create a table with the query:
SELECT distinct("computation_time") FROM "t_m2" WHERE "station" = 'montana' AND $timeFilter GROUP BY time($interval) fill(null)

![table](https://cloud.githubusercontent.com/assets/20662503/22792829/5e9f8020-eeee-11e6-8e36-fbd963ec4704.png)

Thank you!

**Comment by torkelo** [comment]
template variable queries should be in the form SHOW TAG VALUES, SHOW FIELD, SHOW TAG KEYS etc, 

https://github.com/grafana/grafana/issues/5013

**Comment by gwuillou** [comment]
Thank you,

I saw that in the doc, but I thought it could be possible. I have to find a other way to do that.
I would like to tell you thank you for all your job. Grafana is a very nice tool!
