### ISSUE TITLE
[Bug] Graph sometimes ignore series 

### ISSUE THREAD

**Issue by temenoskrpavithra** [grafana/grafana#7515]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxdb
- What OS are you running grafana on? Redhat
- What did you do? Graph - for time period of 1-Jan-2016 to 1-Feb-2017
query is the following and Axes- Series, Value- Avg
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND $timeFilter GROUP BY time(1s) fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'A' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'B' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'C' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'D' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'E' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'F' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'G' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)
SELECT distinct("TIMESPENT") FROM "CODINGTIME" WHERE "TYPE" = 'Defect' AND "TEAM" = 'H' AND $timeFilter GROUP BY time(1s), "TEAM" fill(none)

- What was the expected result? Bar for every series.
- What happened instead? Bar for team H missing for 1 year date. If i change the date for last 30 days, i get all the series shown. 
Team H has data spread throughout the year. 

For the same 1 year range, if i hide any of the above queries, then i get Team H listed.
Is there any limitation on the number of series that can be listed ?

**Comment by torkelo** [comment]
No limitation, can you show InfluxDB response (open chrome dev tools  network tab), maybe influxdb is chunking response, new InfluxDB 1.2 has some breaking changes in how it  returns data

**Comment by utp-promote** [comment]
In Network tab, i see status 200 for all the queries including the one that is not displayed on the chart. I don't see any error.
Could you tell me what specifically i should be looking for ?

**Comment by temenoskrpavithra** [comment]
In Network tab, i see status 200 for all the queries including the one that is not displayed on the chart. I don't see any error.
 Could you tell me what specifically i should be looking for ?

**Comment by torkelo** [comment]
Look at the network tab / response to see the raw response from InfluxDB

**Comment by temenoskrpavithra** [comment]
Thank you.
I see that it returns the response and find the points list in preview as well.

When i hide any other query in the chart, then the missing one is shown. Again, its response and preview list is similar to what it was when it was hidden.

**Comment by temenoskrpavithra** [comment]
@torkelo Do you know why this fails in my case ? Is there any parameter that i should look for to prevent a series from getting hidden ?

**Comment by torkelo** [comment]
it might be related to this InfluxDB breaking change, https://github.com/grafana/grafana/issues/7380

**Comment by temenoskrpavithra** [comment]
Thank you @torkelo For some reasons I don't get Partial:true in Chrome. However, this is highlighted in my Firefox browser. I have set max_row_limit = 0 in InfluxDB, still makes no change. It is still ignoring data as it is being chunked. I have enquired in another releavant thread (https://github.com/influxdata/influxdb/issues/7879) on how chunk should be set to false and size modified.
