### ISSUE TITLE
[Feature] As a business team we like to change the default black background of entire grafana screen with custom images(jpeg) or background with other colours

### ISSUE THREAD

**Issue by kamalvpm777** [grafana/grafana#7517]
[Feature] For the business team we like to change and see the default black background of entire grafana screen with custom images(jpeg) or background with other colour. This will help grafana montoring to look better for supporting  different module of business operations 

Please include this information:
- What Grafana version are you using? v3.1.1
- What datasource are you using? CLOUDWATCH
- What OS are you running grafana on? Linux
- What did you do?  Trying the change the default black background with some custom image / other colour for entire grafana screen
- What was the expected result? Grafana screen with a different background colour / image 
- What happened instead? Currently don't see an option to replace/customize the default black colour for entire grafana screen background with other colours or images

Current Background - Full Black colour for entire grafana screen
Anticipating  Background - Option for background with different colour and customize with different images.
**IMPORTANT** 
If it relates to *metric data viz*:
![image](https://cloud.githubusercontent.com/assets/25632887/22800151/6539a8a6-eed6-11e6-8306-4bdc3ff88413.png)

I believe this feature makes sense as part of Grafana  UI correlating with different business operations, let me know if still not my clear and i will be happy to explain more on the same

**Comment by torkelo** [comment]
you can change the background color of singlestat panels, (you can create custom panels as well), you can change to white theme. Beyond that sorry :(
