### ISSUE TITLE
[Bug] Influxdb query fails to populate metric fields >=1 hour time ranges

### ISSUE THREAD

**Issue by jl98800** [grafana/grafana#7518]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?  3.1.0-1468321182
- What datasource are you using?   Influxdb v1.2.0-1
- What OS are you running grafana on?  Ubuntu 14.04.5 LTS
- What did you do? 
Created a dashboard with 8 queries to Influxdb to gather:
  1.  Number of jobs running
  2.  Number of jobs failed
  3.  Number of jobs succeeded
  4.  Number of jobs failed awaiting restart
  5.  Long running jobs
  6.  Total columns
  7.  Average jobs attempts
  8.  Average run time
The query runs every 60 seconds.  I can view data in all rows with zero to some number results for time ranges of 5m, 15m, 30m, 

Some query results fail to render any output (0-any number) to the dashboard for time ranges 1h, 3h, 6h, 12h, 24h.  That is the query shows data for all 8 queries until you zoom out to view stats greater than or equal to 1 hour time ranges.  Then results are very inconsistent. Sometimes you get 5 query results even if null is to report 0.  The further out you go - like 24h - you may only see 2 query fields populated (number of jobs running and failed). 

- What was the expected result?
The expected end result is report back data for all 8 queries even when results are null, 0, etc. 

- What happened instead?

See What did you do section above.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Raw Queries:
=<private>

SELECT last("value") FROM "<jobs.running>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<jobs.failed>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<jobs.succeeded>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<obs.failed_awaiting_restart>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<jobs.long_running>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<jobs.total>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<obs.avg_job_attempts>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

SELECT last("value") FROM "<jobs.avg_run_time>" WHERE "app" = '<app_name>' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

Response for Network Request:
Sorry - private data.  Can't share. But trust me the response if FULL of data when viewed from chrome dev tools network tab.

The dashboard has been solid for a long time.  Influxdb was recently updated to 1.2.

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
Please include this info (in the issue template)

> The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/7380
