### ISSUE TITLE
Alerting: notification policies don't match missing label

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#75196]
### What happened?

A notification policy that looks for a missing label in alerts doesn't not match any alerts.

Matcher: label: `test`, operator: `=`, value: `""`

Alternative Matcher: label: `test`, operator: `!~`, value: `.+`

Alternative Matcher: label: `test`, operator: `=~`, value: `^$`

An alert without label `test` is not matched by the policy.

### What did you expect to happen?

Since the alert does not have the label `test`, the policy should match but instead only the default notification policy matches.

### Did this work before?

N/A

### How do we reproduce it?

1. Create a notification policy that matches an empty label
2. Create an alert without the tested label
3. Click `Preview routing`
4. Notice it does not match the notification policy created in step 1

### Environment (with versions)?

Grafana: 10.1.0

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @gtirloni 

thank you for creating this issue

> 2. Create an alert without the tested label

When creating alert rules, in step # 5 Notifications,  you are reminded with this message :
`"Without custom labels, your alert will be routed through the root route."`

It does not look like you can work around this fact by using those labels in the notification policy. So far, this looks more like a feature request, IMHO.

What is your use case? Perhaps there are some users that could be interested.

**Comment by gtirloni** [comment]
My use case is a list of alerts that is managed by several teams manually through the UI.

They historically routed alerts based on a specific label (that encoded too much information), and we wanted to break it down into 2-3 labels.

So until we have these 2-3 labels properly defined in all alerts, the old generic label will still exist. And because of that we need to keep two big sets of routing rules in place.

So I initially wanted to build a routing policy that would match all the alerts that don't have the generic label... and from there start matching the 2-3 new labels.

I flipped that logic and put the generic label routing policy at the top and disabled continues. Now the generic label will take precedence, even if the alert has the new labels. People will have to remember to remove the generic label if they set the new label, which sounds okay.

Sorry for missing the reminder about the custom labels.

**Comment by tonypowa** [comment]
hi @gtirloni 

You were right after all ! 🙏  It seems there is actually a bug, that shows the incorrect policy.
@soniaAguilarPeiron  is already working on a fix 🚀
