### ISSUE TITLE
[Feature request] Extended datasource handling for multiple orgs

### ISSUE THREAD

**Issue by bluebob** [grafana/grafana#7521]
Please include this information:
- What Grafana version are you using?
_4.0.2_
- What datasource are you using?
_N/A_
- What OS are you running grafana on?
_Linux_
- What did you do?
_Added new Org_
- What was the expected result?
_N/A, see below_
- What happened instead?
_Nothing_

Our Grafana instances have multiple orgs, one per team. We also have a standard set of datasources that have to be duplicated manually (using a local script hooking into the REST API at present) when a new Org is created. It would be desirable for us to be able to do one or more of:
a. Be able to define a datasource as "Global" and therefore available to any existing, and all new orgs;
b. Have some Grafana-resident method to push a selection of datasources from one group to another, or pull from a "source" group to a "destination" one;
c. Be able to "clone" a datasource selection from an existing group when a new group is created.

I suspect that (a) would require some appreciable amount of engineering, whereas (b) & (c) would be a lot more straightforward. (b) especially is pretty much just a UI around some fairly straightforward database manipulation.

**Comment by torkelo** [comment]
organizations are for multi tenant setups where different companies / organizations can share the same grafana server, so organisations can have their own dashboards , users and data sources. 

We will later this year work on dashboard folders, and after that user groups and permissions, 
https://github.com/grafana/grafana/issues/1128
