### ISSUE TITLE
SQL Builder: Regression in builder options - cannot build time series queries.

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#75210]
### What happened?

The SQL query builder doesn't allow me to enter the $__timeFilter and $__timeGroup aliases in their respective fields

### What did you expect to happen?

I expected the query builder to allow building timeseries queries - grafanas main and original usecase

### Did this work before?

In grafana 8 query builder this worked flawlessly. We already skipped migrating to grafana 9, and will likely have to wait even more until this is fixed. Some of our grafana users rely on the query builder since they do now know SQL.

### How do we reproduce it?

1. go to grafana 10
2. build a query
3. try to make the query limited to the time range, and group by the interval.
4. fail.

### Environment (with versions)?

Grafana: v10.0.5 
OS: Windows
Browser: firefox

### Grafana platform?

Docker

### Datasource(s)?

MySQL, Postgres

**Comment by usmangt** [comment]
Hi @laundmo,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by gabor** [comment]
hi @laundmo thanks for the report! we are already tracking this problem in https://github.com/grafana/grafana/issues/68750, so i'll close this one.
