### ISSUE TITLE
[Question] How to put border around a row ?

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7522]
Hi, thank you to everybody who will read this.

Please include this information:
- What Grafana version are you using? latest
- What datasource are you using? Prometheus
- What OS are you running grafana on? MacOS Sierra
- What did you do? I created a dashboard with JavaScript 
- What was the expected result? the same as the one I have

So I made a Grafana's dashboard who is created by JavaScript and now I think I should add a border around each row to make reading easier.

That's the actual view: 
<img width="1426" alt="capture d ecran 2017-02-10 a 10 16 15" src="https://cloud.githubusercontent.com/assets/22610050/22824811/05eefde2-ef8a-11e6-9a3c-0d177360641e.png">

but as you can see we can't see easily which row is for which "name".

So what I want to do is something like this: 
![capture d ecran 2017-02-10 a 11 31 18](https://cloud.githubusercontent.com/assets/22610050/22824818/116beaa4-ef8a-11e6-9b37-b0ced15b9a6e.png)

And I can't find a field to put borders.

**Comment by torkelo** [comment]
you can create row headings (by go to row options check show title), there are no row borders

**Comment by JeromeVi** [comment]
@torkelo  Ok thank you for the nice and fast answer ! :)
