### ISSUE TITLE
[Feat Request] Add support for running Grafana inside electron

### ISSUE THREAD

**Issue by aptro** [grafana/grafana#7523]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? 
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

grafana version: 4.1.1
datasource: elasticsearch
os: aws ami
 
Note: Expect Dashboard Page other Pages are working
Error Page
![grafana](https://cloud.githubusercontent.com/assets/10391409/22825665/a896f4c6-efb4-11e6-814c-5bcd7882d336.png)

**Comment by MachineSaver** [comment]
This is a brilliant idea. Finally in September 2020 I see what you were trying to do back in February 2017. Grafana is an awesome UI tool for displaying data and being able to package node-red, its dependencies and grafana up together as an electron app would be incredibly powerful for people who want to build cross-platform projects with the logic handled by node-red.

**Comment by maheshrajrp** [comment]
Curious, now that Grafana is ported to React, I believe this should be possible ?

**Comment by gelicia** [comment]
I'd be interested to hear about if we've heard any sort of changing demand for this over the last few years given the other ways people can share dashboards and etc in Grafana. Set this up to be a cross team topic to investigate, so we can decide if we would consider moving forward investigating this or not.

**Comment by maheshrajrp** [comment]
> I'd be interested to hear about if we've heard any sort of changing demand for this over the last few years given the other ways people can share dashboards and etc in Grafana. Set this up to be a cross team topic to investigate, so we can decide if we would consider moving forward investigating this or not.

This should help incase of application developed within Electron. I had to drop a feature request as this feature wasn't supported. Not sure if this still doesn't work, but having this feature would really help.

**Comment by joshhunt** [comment]
I'm going to close out this issue as something that we can't support. 

Grafana is a website that targets somewhat modern web browsers, and not Electron. If Electron has an incompatibility with the web platform that prevents websites from working in it, the responsibiliy for the fix lies there. 

Small, non-invasive PRs to work around issues caused by Electron _may_ be accepted, but as Electron is not a supported platform, we don't have tests to catch regressions with it so it may break again in the future.
