### ISSUE TITLE
Adhoc Filters - Enter key doesn't work on custom text entry

### ISSUE THREAD

**Issue by trexx** [grafana/grafana#75231]
**Steps to reproduce**:
Have a dashboard with an adhoc filter and attempt to use the regex comparison operator "=~". When typing a custom value that isn't in the dropdown, press the enter key to submit your query.

**Actual Result**:
Enter key does nothing and I'm left focused on the text input field for the adhoc filter.
I have to click outside of the text field for my query to be submitted.

**Expected Result**:
Pressing enter submits my adhoc filter, and triggers a query to view my requested data.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
Maybe https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#keyboard-accessible

(Not sure if bug or accessibility issue)

**Environment**:
- Grafana version: 10.1.2
- Data source type & version: Elasticsearch
- User OS & Browser: Edge 117.0.2045.36 64Bit
- Others:

**Comment by usmangt** [comment]
Hi @trexx,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/dashboards/f/e04a2013-1aef-4c39-87e4-4d6c1698820a/sandbox and then share the dashboard link so that we can view it?


Thanks

**Comment by trexx** [comment]
Hi @usmangt 

Yes, I can reproduce it there too. https://play.grafana.org/goto/Y8PjRzWIR?orgId=1

In order to reproduce it. Clear the adhoc query, and readd it.

You'll find when you type "artifacts.*" and press enter, it won't do anything, and you'll have to click out for your change to register. It seems the enter key only works if there are results suggested and highlighted. Where as with a regex query, its unlikely a suggestion in the list will contain regex characters and its more likely "no options found" will be displayed instead.

**Comment by usmangt** [comment]
Thanks !!

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.
