### ISSUE TITLE
Remove unsupported DS map and update documentation

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#75243]
Remove [unsupported DS map ](https://github.com/grafana/grafana/blob/main/pkg/services/publicdashboards/commands/generate_datasources/generate.go#L16) once [this task](https://github.com/grafana/grafana/issues/74872) is done

**Comment by juanicabanas** [comment]
@sarahzinger can we confirm Cloudwatch works for public dashboards? I'm not able to test it locally

**Comment by sarahzinger** [comment]
@juanicabanas our team merged a fix to use super.query last week https://github.com/grafana/grafana/pull/77532

I can test this locally and it seems to work although it shows a warning regarding an unsupported datasource in the modal. I tried testing in prod and didn't see the changes, but I'm guessing it just hasn't been released/rolled out yet on my instance.
