### ISSUE TITLE
Alerting: Save Rule button exits for copied rule

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#75244]
### What happened?

If you create a new rule by copying an existing one (copy button), the new alert page has two buttons "Save rule" and "Save rule and exist". Both of them save the rule and go back to the alert list.

### What did you expect to happen?

"Save rule" would save the rule but stay on the samepage.

### Did this work before?

N/A

### How do we reproduce it?

1. Find an existing alert
2. Click the copy button
3. In the new page, change alert configuration and click on "Save rule"
4. Notice the page will close and the alert list page will show next

### Environment (with versions)?

Grafana: 10.1.0

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @gtirloni,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine. :+1: 

I will forward this issue to our Engineers so that they can have a look and analyse it.
