### ISSUE TITLE
Cloud Monitoring Query Editor: Unable to add custom label manually

### ISSUE THREAD

**Issue by ariefradityo** [grafana/grafana#75280]
### What happened?

Cloud Monitoring query editor: I cannot add custom group by value as per documentation.
![image](https://github.com/grafana/grafana/assets/9078925/2324dc03-55ae-4514-a03c-f46b5ea28016)

### What did you expect to happen?

Group by component should allow custom value to be manually input rather than depending on predefined labels.

### Did this work before?

I assume the older group by query builder can add custom value as per documentation
![image](https://github.com/grafana/grafana/assets/9078925/e29ff13d-0738-4870-b49c-c3c5faecccf8)

### How do we reproduce it?

1. Create a query for google monitoring with query builder
2. Try to group by metrics by using non listed metrics
3. UI won't provide option to add custom value

### Environment (with versions)?

Grafana: Grafana v10.1.2 (8e428858dd)
OS: Ubuntu
Browser: Google Chrome Windows 116.0.5845.188

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring

**Comment by aangelisc** [comment]
Hi @ariefradityo, thank you for reporting this! I can't see that this was ever supported and the documentation may actually be wrong here. We can look at adding support for this in the future.

**Comment by zsrv** [comment]
@aangelisc I just opened an issue about this same thing before seeing this one. In my report (#81750) I linked to a couple of issues that showed that custom metadata labels could be entered in earlier Grafana versions. Not being able to use custom metadata labels is a big limitation for us.

**Comment by aangelisc** [comment]
Hi @zsrv, apologies for the delay, I have a PR open that should fix this 😊
