### ISSUE TITLE
Explore Logs: Incorrect query range being sent when providing filter expression

### ISSUE THREAD

**Issue by al-lac** [grafana/grafana#75282]
### What happened?

We have two Loki Connections set up in Grafana. Both of them are setup identical and use the same Loki version. 

However, when we run a query like this in the Explore section on one of those connections we get an error. The other one is just working fine.

Query: `{namespace="test"} |= "ERROR"`
Error: `the query time range exceeds the limit (query length: 2160h29m35.444s, limit: 30d1h)`

In this case the time range was set to 6 hours. 
Of course if we integrate this query on a dashboard, that panel also fails.

If we remove the filter expression it works fine:
Query: `{namespace="test"}`

On our second Loki connection, both variants work just fine.

### What did you expect to happen?

Grafana should send the query time range that is set and show the logs, regardless of if a filter expression is set or not.

### Did this work before?

Yes, we are not sure though when it broke.

### How do we reproduce it?

1. Open Explore Tab
2. Run a query like this: `{namespace="test"} |= "ERROR"`
3. See if an error like this shows up: `the query time range exceeds the limit (query length: 2160h29m35.444s, limit: 30d1h)`

### Is the bug inside a dashboard panel?

Both Explore and Dashboard Panel

### Environment (with versions)?

Grafana: v10.1.2
OS: macOS 13.5.2
Browser: Chrome 117.0.5938.92

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Loki 2.9.1

**Comment by gtk-grafana** [comment]
This error appears to be coming from Loki, not Grafana. 

I found a related issue on the Loki github: https://github.com/grafana/loki/issues/4509, which led me to the `max_query_length` in the [limits config](https://grafana.com/docs/loki/latest/configure/#limits_config) in the loki docs.

While I'm still not able to reproduce the specific issue with the filter changing when this error is triggered:
<img width="656" alt="image" src="https://github.com/grafana/grafana/assets/109082771/649e3921-4945-4bf7-ac5f-0c4d9cba89dc">
I was able to receive this error when changing the `max_query_length` value in my Loki instance to 6h and rebooting.

I was able to set an indefinite max_query_length with a value of `0h` just like in the comment in that [loki issue I linked above](https://github.com/grafana/loki/issues/4509#issuecomment-988000715), which allowed me to query any duration.

If you are still having trouble with filters impacting the `max_query_length` configuration of your Loki instance, I suggest submitting a bug report on the [Loki board](https://github.com/grafana/loki/issues/new/choose), as this appears to be an issue related to Loki configuration, and not anything we can fix in the Grafana datasource (but please reopen if this is incorrect).

**Comment by al-lac** [comment]
Found the root cause for this issue. We misconfigured the following setting:
```yaml
querier:
  max_concurrent: 2048
  engine:
    max_look_back_period: 2160h
```

It seems like that once `max_look_back_period` reaches a certain amount of hours, the filtering breaks. With about `336h` it still worked. 

We now just set it back to the default level (30s).
