### ISSUE TITLE
Dashboards: empty links configs break dashboards after upgrade

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#75315]
### What happened?

We're seeing this on v10.1.1:

```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'replace')
    at S.getDataLinkUIModel (link_srv.ts:301:45)
    at linkSuppliers.ts:152:29
    at Array.map (<anonymous>)
    at Object.getLinks (linkSuppliers.ts:151:20)
    at o (getPanelChromeProps.tsx:56:53)
    at We (PanelLinks.tsx:27:23)
    at Bl (react-dom.production.min.js:167:137)
    at Nc (react-dom.production.min.js:290:337)
    at el (react-dom.production.min.js:280:389)
    at ws (react-dom.production.min.js:280:320)
```

### What did you expect to happen?

No errors.

### Did this work before?

Everything was working fine on v9.4.x.

### How do we reproduce it?

Have a dashboard with a panel that has the following:

```json
                "links": [
                    {}
                ],
```

### Environment (with versions)?

Grafana: v10.1.1
OS: macOS
Browser: Chrome

### Grafana platform?

None

**Comment by bobrik** [comment]
I fixed it locally by removing `{}` from `links` in the panal json via export -> edit -> import.

**Comment by tonypowa** [comment]
hi @bobrik 

thank you for the issue

I am trying to repro the same behaviour but I don't see the link element in the panels I create. 

- Could you please give more details? 
- Is the body of the JSON coming from panels from of versions of Grafana?

**Comment by bobrik** [comment]
Try importing this dashboard:

<details>
  <summary>dashboard.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 12,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green"
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "links": [
        {}
      ],
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "10.1.1",
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "grafana"
          },
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Broken links",
  "uid": "ee93c155-2dc5-4ade-8eb8-2868076acafe",
  "version": 6,
  "weekStart": ""
}
```

</details>

I made it from scratch and then added `{}` into `links` of the only panel.

I don't think it matters much how `{}` got there in the first place. Grafana should handle this gracefully and not break panels that it itself made in previous versions.

**Comment by bobrik** [comment]
> I notice that there are two "links" name/value pair in your JSON.

The first one is for the dashboard, the second is for the panel.

**Comment by natellium** [comment]
@bobrik how did you get a dashboard JSON with that format? I tried with a 9.4.0 dashboard but I didn't manage to get the empty link config.

**Comment by bobrik** [comment]
I have no idea how empty links appeared there. Humans are creative when pushing buttons out of expected order.

**Comment by natellium** [comment]
Given that we weren't able to replicate the dashboard config, we haven't gotten any other reports, and there's a workaround I will close this issue. If the problem reappears, feel free to reopen.

**Comment by bobrik** [comment]
Here, I replicated it for you: https://play.grafana.org/d/d676dc96-6446-49d7-abbb-77d1dc3bd80b/issue-75315?orgId=1

The diff that broke it is exactly as described in the issue description:

<img width="557" alt="image" src="https://github.com/grafana/grafana/assets/89186/2ac29b7c-821a-486c-abdd-1f1e11d64633">

**Comment by bobrik** [comment]
Here's another: https://play.grafana.org/d/ee93c155-2dc5-4ade-8eb8-2868076acafe/broken-links?orgId=1

I imported a dashboard from this comment verbatim:

* https://github.com/grafana/grafana/issues/75315#issuecomment-1735964766
