### ISSUE TITLE
Task: Validate dashboardUid on deletion

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#75316]
The deletion URL receives both values, `dashboardUid` and `publicDashboardUid` we should validate a `publicDashboardUid` belongs to the `dashboadUid` provided.
Similar to [PR](https://github.com/grafana/grafana/pull/70993/files), reuse the same code.

**Comment by aditipatelpro** [comment]
Hi @evictorero, I would like to contribute to this issue, could you please assign it to me?
