### ISSUE TITLE
Dashboards: Time Series visualization not working if using Format Time transformation 

### ISSUE THREAD

**Issue by shrx** [grafana/grafana#75330]
### What happened?

If I enable the [Format Time](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-1/#format-time-transformation) transformation on my Time Series data, the visualization stops working and displays the message:

> Data is missing a time field
> Switch to table / Open visualization settings

If I switch to table the data looks fine.

### What did you expect to happen?

Grafana should be able to visualize the data as a Time Series.

### Did this work before?

N/A, this is a new feature.

### How do we reproduce it?

1. Create a new Time Series dashboard panel.
2. Choose Grafana as a data source and Random Walk as a query type.
3. A random walk time series is displayed.
4. Go to Transform tab.
5. Select Format Time transformation, time field = `time`,  format = `D. M. YYYY hh:mm:ss`.
6. The visualization displays the "Data is missing a time field" message.

### Is the bug inside a dashboard panel?

[debug-Panel Title-23. 9. 2023 10 31 55.json.txt](https://github.com/grafana/grafana/files/12705947/debug-Panel.Title-23.9.2023.10.31.55.json.txt)

### Environment (with versions)?

Grafana: 10.1.2
OS of server: raspbian bullseye
OS of client: windows
Browser: Firefox

### Grafana platform?

None

**Comment by leeoniya** [comment]
i think this is expected behavior. this transform is mostly useful for the table panel.

you can achieve the same thing in other panels by setting the time field's unit to `time:D. M. YYYY hh:mm:ss`. though this is not very well known.

**Comment by shrx** [comment]
I actually solved this myself now: another transformation "Convert field type" is needed after the "Format Time" transformation, to convert the column from string back to time type. Now it displays as a time series.

**Comment by leeoniya** [comment]
what's the purpose of converting from time to string and then back to time?

**Comment by shrx** [comment]
The purpose is daily averages of the data. My real usecase is to use `D. M. YYYY 12:00:00` time format and then grouping the values by time and computing daily min, max, means.

The reason why I can't use the GroupBy directly in the query is that I'm displaying Expressions which combine data from multiple queries.
