### ISSUE TITLE
[FeatureRequest] Intervals: Auto time interval won't go below 10ms

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#7533]
- What Grafana version are you using?
4.1.1

- What datasource are you using?
InfluxDB 1.2.0

- What OS are you running grafana on?
Windows

- What did you do?
I have data that has been recorded at a 4ms interval and tried graphing it in grafana using the auto interval in the group by clause of the query.

- What was the expected result?
Data would be requested with an auto interval that would scale down to 1ms.

- What happened instead?
It seems that no matter what you do grafana will only generate auto interval ranges down to 10ms. I also tried making a custom interval variable with auto turned on and it's auto interval would not use anything below 10ms either even though it allows you to specify those intervals.

Grafana works fine if you manually request a group by of 1ms but that obviously doesn't work once you zoom out. Are there any technical issues that cause the cap to be at 10ms rather than 1ms? I have never worked on Grafana before but I was poking around the code and found the kbn javascript file that contains the calculateInterval function which contains a comment that suggests that the minimum it can go is 1ms. However it calls the round_interval function which seems to stop at a 10ms interval.

**Comment by willemdh** [comment]
I'm seeing similar problems lately. On some intervals results seem to be missing. When zooming out they suddenly appear. When using summarize template it seems indeed that when an interval is used lower then 10 seconds, results seem to be missing.

**Comment by multiple1** [comment]
I think you are right with the `round_interval` function in kbn.ts.
I added a range for 1ms and the `$__interval` gets changed down to 1ms.

```
kbn.round_interval = function(interval) {
  switch (true) {
    // 0.005s
    case interval < 5:
      return 1; // 0.001s
    // 0.015s
    case interval < 15:
      return 10; // 0.01s
```

**Comment by psmt** [comment]
Any news on this?  any plans to add this 1 ms time interval feature?

**Comment by garaemon** [comment]
I have the same issue too.

**Comment by gabor** [comment]
currently this happens at https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/datetime/rangeutil.ts#L331

this is not specific to influxdb, so what do you think about this @grafana/grafana-frontend-platform ?
