### ISSUE TITLE
Option to hide un-mapped values in time series panel using y-axis mapping

### ISSUE THREAD

**Issue by thoro** [grafana/grafana#75341]
**Why is this needed**:

Currently when using y-axis mapping with discreet values the y-axis will be cluttered with unattainable values.

<img width="402" alt="Screenshot 2023-09-24 at 14 00 26" src="https://github.com/grafana/grafana/assets/554474/740afcf9-7636-4fc3-a494-26b50a79b157">

This will clean up the view and only leave the y-axis mappings as setup.

**What would you like to be added**:

Add a toggle (that can be also overridden for the right and secondary axis) that controls wether intermediate (i.e. unmapped) values are shown in the axis.

**Who is this feature for?**

Users that utilize the y-axis mapping function to display concrete states for devices, i.e. Heatpump modes, Ventilator modes, Application states, e tc.

**Comment by leeoniya** [comment]
i'll add a bit more related info here...

we recently added support for rendering new `enum` type fields to TimeSeries: https://github.com/grafana/grafana/pull/64179. that would be useful here.

however, only the `testdata` datasource is currently capable of producing these `enum` fields. we are planning to add a transformation that can take an existing field and create an enum field out of it, with an interface likely very similar to the Value Mappings one: https://github.com/grafana/grafana/issues/72073.

once this is done it would support your discrete use case without needing to add the "hide unmapped values" option. the technical problem i see with adding the option you're asking for is that the values you see on the y axis are simply ticks (they don't come from data). so in timeseries this is simply a proxy for setting axis tick options. in other panels (like StateTimeline) this option would mean something else unrelated to the axis but to actually removing values from the data. we would have to go through every panel and figure out what this setting means in the context of each of many panel, which is much bigger task with more than a few unknowns.

**Comment by leeoniya** [comment]
so...you could set Decimals = 0 as a clever hack, which will hide the non-int ticks if your mapped values are ints, though it will still show unmapped ints :)

<details><summary>mappings-zero-decimals.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 766,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "stepAfter",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "decimals": 0,
          "mappings": [
            {
              "options": {
                "0": {
                  "index": 0,
                  "text": "Zero"
                },
                "1": {
                  "index": 1,
                  "text": "One"
                },
                "2": {
                  "index": 2,
                  "text": "Two"
                },
                "3": {
                  "index": 3,
                  "text": "Three"
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 15,
        "w": 14,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "0,1,2,1"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "mappings-zero-decimals",
  "uid": "efb62ca5-b0a1-4e11-8b60-0ad9aa74ba14",
  "version": 1,
  "weekStart": ""
}
```
</details>

![image](https://github.com/grafana/grafana/assets/43234/ec47e5ae-63ba-43d1-b7f7-b99f0640d7ed)

![image](https://github.com/grafana/grafana/assets/43234/12b9b47b-7db6-4530-bf61-dbca008ed5f9)

**Comment by thoro** [comment]
Thanks! That’s what I needed in the example case.

I do have a second panel that uses 2^x as values, there it doesn’t work, but already halfway there 👌
