### ISSUE TITLE
Option to change the global font

### ISSUE THREAD

**Issue by RedShift1** [grafana/grafana#75351]
**Why is this needed**:

The new default font since Grafana 9 (Inter) is quite fuzzy on 100% scaled displays. The previous font (Roboto) looks better at 100% scaling. An option to change the global font would alleviate this issue.

**What would you like to be added**:

A font option similar to UI Theme in preferences. Maybe offer two options: Roboto and Inter, or a custom option where the user can type the font name themselves (like a CSS style).

**Who is this feature for?**

Anyone who doesn't like or has problems with the default Inter font.

Comparison:

![image](https://github.com/grafana/grafana/assets/3098010/244fa0d7-6650-4980-8989-aec9fa29d4ed)

**Comment by dhruvchandak30** [comment]
@RedShift1  I would like to work on this issue!

**Comment by RedShift1** [comment]
For those that need a quick fix, you can use the [Stylus plugin](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) and use this stylesheet:

```
html, body, button, input, optgroup, select, textarea, h1, h2, h3, h4, h5, h6
{
	font-family: Arial !important;
}
```
Replace Arial with your choice of font.

**Comment by dhruvchandak30** [comment]
@RedShift1  Where should I place my dropdown menu for fonts?

**Comment by RedShift1** [comment]
Probably here, between "UI Theme" and "Home Dashboard"?

![image](https://github.com/grafana/grafana/assets/3098010/f0d6682a-6491-43fb-b9a5-a7a8ed93247e)

**Comment by dhruvchandak30** [comment]
@RedShift1 
I have set up the whole environment but got stuck at the last step.
![WhatsApp Image 2023-10-01 at 13 14 10_5087841e](https://github.com/grafana/grafana/assets/116879117/53c9ef8b-78d5-4bb3-b874-f6e06e213967)
It is asking me the directory of the original game files.
![WhatsApp Image 2023-10-01 at 13 14 48_5e10e518](https://github.com/grafana/grafana/assets/116879117/516a6e1e-1d69-4a89-93c9-680f274a2fe3)
But the game can be download only on windows
and It can only be compiled on Linux
![WhatsApp Image 2023-10-01 at 13 13 11_5f7a5bc8](https://github.com/grafana/grafana/assets/116879117/03b70839-71e5-453b-8b09-0e7d385d113d)
So how should I proceed further?

**Comment by RedShift1** [comment]
@dhruvchandak30 you're in the wrong repository. This is Grafana, not OpenLoco.

**Comment by dhruvchandak30** [comment]
![image](https://github.com/grafana/grafana/assets/116879117/205a1f3a-5923-4ae4-a3c3-18848265895b)
Can you please help me with this error !

**Comment by joshhunt** [comment]
I'm going to dupe this to custom themes https://github.com/grafana/grafana/issues/10495

But I'm doubtful we would add an option just for changing the font. If our font option looks bad, then we should just not use it and instead improve it for everyone.

**Comment by esthor** [comment]
I would love to have any `monospaced` font as an option. 🙏 

Without consistent spacing between characters, it makes it impossible to just glance at a column of numbers and know which ones are an order or two magnitude higher than others because some number characters take up more width than others.

**Comment by lubomirmatus** [comment]
> I would love to have any `monospaced` font as an option.
Same here. The monospaced font is perfect for displaying technical info like numbers, date-times or strings (e.g. hashes) that looks better when are alligned.
I try to use monospaced fonts in every technical tool that has option to change font (like code editors, terminals, database tools, ...). On Windows mostly the `Consolas` font.

**Comment by cschar** [comment]
> I'm going to dupe this to custom themes [#10495](https://github.com/grafana/grafana/issues/10495)
> 
> But I'm doubtful we would add an option just for changing the font. If our font option looks bad, then we should just not use it and instead improve it for everyone.

The linked issue was closed as "not planned"...?
Seeing how Grafana is a Data Visualization Tool, (lots of numbers, dates in dashboard titles) wouldn't a standard font being 'monospaced' be a good fit for product?

**Comment by RedShift1** [comment]
I solved this organization wide by having the reverse proxy inject a custom stylesheet, here's the Apache HTTPD config:

```
<VirtualHost *:443>
        ServerName grafana
        DocumentRoot /var/www/vhosts/grafana

        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://127.0.0.1:3000/$1" [P,L]

        ProxyPreserveHost On
        ProxyTimeout 180

        ProxyPassMatch "^/custom/.*" !

        ProxyPass / http://127.0.0.1:3000/
        ProxyPassreverse / http://127.0.0.1:3000/

        <LocationMatch ".*">
                AddOutputFilterByType SUBSTITUTE text/html
                Substitute "s|</head>|<link rel='stylesheet' href='/custom/mystyle.css'></head>|"
        </LocationMatch>
</VirtualHost>
```
Put your own stylesheet in `/var/www/vhosts/grafana/custom/mystyle.css`. Because it's the last stylesheet that will be loaded, you can use it to override anything.
