### ISSUE TITLE
Grafana 4.1.1 file handle leak

### ISSUE THREAD

**Issue by jleclanche** [grafana/grafana#7535]
Using Grafana 4.1.1 with InfluxDB, Influx Internal and Cloudwatch datasources. The influxdb and influx internal sources are sitting on the same machine as Grafana.

The machine dies every few days with "too many open files". A cursory look at `lsof` shows many, many open sockets such as these:

```
grafana-s   315 23040    grafana   35u     IPv4           38695754       0t0        TCP ip-172-**-**-**.ec2.internal:19459->ec2-52-**-**-**.compute-1.amazonaws.com:8086 (ESTABLISHED)
grafana-s   315 23040    grafana   36u     IPv4           38696609       0t0        TCP localhost:3000->localhost:12977 (ESTABLISHED)
```

I saved a full lsof dump though it has some sensitive information. Any idea what's causing it?

**Comment by mtanda** [comment]
The port 8086 is InfluxDB's port.
If CloudWatch api calls leak file handle, there are many https connection to following endpoints.
https://docs.aws.amazon.com/general/latest/gr/rande.html#cw_region

I'm not sure what cause it, but I think the CloudWatch datasource doesn't leak file handle.

**Comment by bergquist** [comment]
Any idea what `localhost:12977` might be?

**Comment by jleclanche** [comment]
I'll check but I don't think anything runs there. Was just a random port
among the many lines.

**Comment by torkelo** [comment]
@jleclanche have you continued to see this? Any more info for us to help troubleshoot this? We have had no other reports on connection leaks.

**Comment by jleclanche** [comment]
Yeah I still have to restart influx and grafana once or twice a week.

**Comment by daniellee** [comment]
@jleclanche any more info that you can give us? When you check the lsof output, is there any pattern? In your snippet above, you show two open sockets but you said you have many open sockets - can you give us some more examples? Or maybe count which ones are the most common.

**Comment by torkelo** [comment]
any more info for us? what is running on localhost:12977 ?

**Comment by jleclanche** [comment]
I haven't seen this happen anymore since I last reported. No idea what fixed it. Sorry, wish I could be of more help :/
