### ISSUE TITLE
Test user mapping for LDAP still not visible in Grafana 10.1.2. Menu Authentication is missing

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#75364]
### What happened?

Till Grafana 10.0.3 we have the option to test LDAP groups with "Test user mapping" under Adminitration/LDAP.

After updates these option is no longer visible.

### What did you expect to happen?

That I have this option "Test user mapping" for LDAP even in Grafana 10.1.2 or newer.

### Did this work before?

Until Grafana 10.0.3

![Test user mapping for LDAP not visible - Grafana](https://github.com/grafana/grafana/assets/56024424/023110df-869e-4eca-8509-4e8a5a70bdeb)

### How do we reproduce it?

1. Install Grafana with Docker Image: docker pull grafana/grafana:10.1.2
2. Look for this menu point: "LDAP" 
3. Look for "Test user mapping"

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1.2
OS:          Docker image
Browser:  Chrome 116.0.5845.97

### Grafana platform?

Docker

### Datasource(s)?

no

**Comment by essinghigh** [comment]
Confirming I'm seeing the same.
Testing via the API works (/api/admin/ldap/test/{user}), but can't see the test user mapping since updating to latest ver.

**Comment by BramSchutte** [comment]
same issue here, the LDAP button isn't there anymore in Grafana 10.1.2 Enterprise.

**Comment by mhollstein** [comment]
It is be resolved in Grafana 10.1.5

![2023-10-16 16_16_36-LDAP - Authentication - Administration - Grafana](https://github.com/grafana/grafana/assets/56024424/da77c959-8dbc-4793-93a1-0a9c15636405)

**Comment by Jguer** [comment]
Closing as fixed
