### ISSUE TITLE
[Feature Req] View Snapshot JSON 

### ISSUE THREAD

**Issue by ybizeul** [grafana/grafana#7539]
Classifying as a bug as I think it's an inconsistency. Exporting a dashboard using APIs gives you the datapoints, not through Grafana Web UI

> - What Grafana version are you using?
4.1.1

> - What did you do?
Display a dashboard, go in Share > Export

> - What was the expected result?
JSON should contain datapoints, the same way it is build when using APIs to get the snapshot

> - What happened instead?
Only the structure is exported, not the datapoints.

**Comment by bergquist** [comment]
Exporting dashboards is only for exporting the dashboard structure. 

Snapshots is a way to share the data without the recipient having access to the server. 

Totally different features. Perhaps the description in the menu could be improved. @daniellee  What do you think?

![image](https://cloud.githubusercontent.com/assets/618863/22921542/709c4b96-f29a-11e6-95be-3c8eb69546ae.png)

**Comment by daniellee** [comment]
@ybizeul Which method in the API do you mean? 

API call [Get Dashboard](http://docs.grafana.org/http_api/dashboard/#get-dashboard) exports the dashboard structure. It does not take a snapshot (or include any data points).

API call [Create Snapshot](http://docs.grafana.org/http_api/snapshot/#create-new-snapshot) exports a snapshot.

The naming for the methods in the API seems similar to the Web UI to me. Are you saying that the export option in the Web UI has a confusing description?

**Comment by ybizeul** [comment]
So what I'm using right now to solve this issue, is the snapshot API, i.e. `/api/snapshots/<key>` to get snapshot data once it has been saved locally in the UI.

With that call, I'm able to save a local json file that contains snapshot data.

I guess my problem is there is no way to export a snapshot from the UI. You can export to grafana, but not to a local file. Or maybe I'm missing something.

I guess that's why in that window I went to the "Export" tab, and tried to export the JSON

**Comment by ybizeul** [comment]
"View" would make less sense than "Download" I guess but yes that's the idea

**Comment by wrouesnel** [comment]
+1 - the precise thing I want to do is to save the snapshot *data* to a json file locally, so I can upload/share it with git or push it to a different grafana server for longer-term persistence.

**Comment by baiwfg2** [comment]
Is this issue being worked on ? I really need this feature, since many times I want to save the snapshot from one grafana server that I cannot own or access for a long time. So I can import the local snapshot file into my grafana server and see it.  So convenient.

**Comment by breeswish** [comment]
I have interests to implement this feature as described in https://github.com/grafana/grafana/issues/10401 . Considering that it involves with some UI changes, I would like to receive feedbacks or thoughts from Grafana developers about the proposal in #10401 before I start to follow it. @daniellee
