### ISSUE TITLE
dropped ticks cause flappy alerts with "Opsgenie" contact point

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#75409]
### What happened?

We're slowly migrating to the new alerting engine. 
As part of the migration, we've created an alert with a somewhat heavy query with a short evaluation interval (1m). This caused some of the ticks to be dropped constantly.

Now we had some metrics that we were in constant alert condition violation (in a constant state of alert) but for some reason, we kept getting OK->Alert->OK->Alert messages every couple of minutes. Upon investigation, we noticed that the Alert->OK->Alert coincides with the following message in the logs:

```
2023-09-22 06:52:10.350 | logger=ngalert.scheduler t=2023-09-22T06:52:10.350253075Z level=warn msg="Tick dropped because alert rule evaluation is too slow" rule_uid=cab26378-c998-449f-8b9e-577be6d5e353 org_id=1 time=2023-09-22T06:52:00Z
```
When increasing the evaluation interval, the amount of log warnings about missed ticks went down and so did the flapping alert messages, when increasing the interval even further, the flapping alert messages disappeared.

We're using Opsgenie as our main contact point. The alert is configured with following:
```
Alert state if no data or all values are null: No Data
Alert state if execution error or timeout: Error
All rules in the selected group are evaluated every 1m. 
Pending period: 0m
```

### What did you expect to happen?

the dropped ticks to not trigger flappy alerts. 

The actual expected behavior is similar to the old alert engine with "Keep Last State" 

### Did this work before?

No idea - we're new to this alerting engine and this configuration in general

### How do we reproduce it?

1. create an alert with long running query and short evaluation time with some series violating the alert condition
2. send the alert to Opsgenie
3. observe the flappiness

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1.1
OS: linux
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by armandgrillet** [comment]
We recommend you to increase the interval to 2 minutes. The behavior is by design: https://github.com/prometheus/prometheus/issues/5277. Implementing keep last state while using Prometheus Alertmanager as a backend is not easy which is why we haven't done it.
