### ISSUE TITLE
[Bug] installing grafana from repo get "is not signed"

### ISSUE THREAD

**Issue by jeffrey4l** [grafana/grafana#7540]
I am using following repo to installing grafana in centos 7

```
[grafana]
name=grafana
baseurl=https://packagecloud.io/grafana/stable/el/7/$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

```

but get following error message

```
Package grafana-4.1.2-1486989747.x86_64.rpm is not signed
```

Seems there are something wrong in the rpm package.

**Comment by LukasMa** [comment]
Same here.
I set `gpgcheck` to 0. But that shouldn't be more than a temporary solution.

**Comment by bergquist** [comment]
Seems like our build failed to sign the package. Will do it manually.

**Comment by hackruu** [comment]
+1 on this one, please provide signed packages.

**Comment by bergquist** [comment]
The package is now signed. Thanks for noticing! :)

**Comment by AntonOfTheWoods** [comment]
Is there any plan to resign the existing available versions with the new key? Thanks!
