### ISSUE TITLE
Backend compilation failed

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#75405]
### What happened?

In recent days, I suddenly discovered that Grafana plugin started reporting errors when compiling the backend using the 'image v' command. What is the reason? I am using grafana plugin sdk go v0.178.0, image v1.15.0, go1.21。

<img width="883" alt="image" src="https://github.com/grafana/grafana/assets/76942485/a5709da9-5276-414c-9310-f5bec8e97f31">
<img width="862" alt="image" src="https://github.com/grafana/grafana/assets/76942485/314b8c00-3c7b-48e5-9532-78cb99f20af4">

### Did this work before?

Previously, it was possible to compile through commands

### How do we reproduce it?

 go get -u github.com/grafana/grafana-plugin-sdk-go

 go mod tidy

mage -v

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Other

**Comment by marefr** [comment]
@CloudWise-Lukemiao please see the breaking changes and mitigation in https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.177.0

**Comment by marefr** [comment]
Please let us know if that doesn't work

**Comment by CloudWise-Lukemiao** [comment]
> Please let us know if that doesn't work
After adjusting the code locally, I executed go get - u github. com/grafana/grafana plugin sdk go and go mod tidy. Everything was normal, but when I executed the mage - v command, I encountered the problem shown in the following figure
![image](https://github.com/grafana/grafana/assets/76942485/f2c83c1b-7768-4a86-8c05-c20c435c2d7a)

**Comment by marefr** [comment]
@CloudWise-Lukemiao thanks. We have a similar issue opened at https://github.com/grafana/grafana-plugin-sdk-go/issues/760, feel free to continue the discussion there. We're going to look into it
