### ISSUE TITLE
[Bug]  Text on annotation hover does not fit in the box

### ISSUE THREAD

**Issue by capsno1** [grafana/grafana#7542]
Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? ElasticSearch
- What OS are you running grafana on? Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.65-1+deb7u1
- What did you do? created annotation then hovered over the annotation on the graph
- What was the expected result?  nice clean view of the alert
- What happened instead?  message text does not fit in the box

I realize that the syslog message is rather long but if it could somehow be wrapped that would be great.  Let me know if I am missing something.  I would not be surprised if I did something wrong.  Thanks!!

![image](https://cloud.githubusercontent.com/assets/20799351/22895695/7242e568-f1eb-11e6-9e0f-46903e839810.png)

![image](https://cloud.githubusercontent.com/assets/20799351/22895708/7a4383b2-f1eb-11e6-9955-57868db314e7.png)

**Comment by storagedevops** [comment]
Looks great!
![image](https://cloud.githubusercontent.com/assets/20799351/24253423/b2c22e12-0fb6-11e7-9fa0-40d9324c2865.png)
