### ISSUE TITLE
Dashboards: Scrolling Not Working in Twinmaker Plugin with New Panel Header

### ISSUE THREAD

**Issue by idastambuk** [grafana/grafana#75422]
### What happened?

We received a bug report for the Twinmaker plugin with their dashboard panels. Link to the original bug report is [here](https://github.com/grafana/grafana-iot-twinmaker-app/issues/224), but here's a quick overview: 
```we used to be able to have scroll bar with in our query editor panel when i test in Grafana 8.4.7 and 9.4.1 . Now when I test with our plugin in 10.1.1 I see scrolling only on the dashboard level and no scrolling within the panel.```
 There are videos reproducing the behavior in the original report.

If we disable the `newPanelChromeUI` feature toggle, panel scrolling works again, so the bug seems to be traceable to that feature. 

Twinmaker plugin credentials can be found in the [plugin provisioning repo](https://github.com/grafana/plugin-provisioning/blob/main/provisioning/datasources/aws-iot-twinmaker.yaml), and the behavior can be reproduced with the same query as in the original report (though no data will be returned)

### What did you expect to happen?

Scrolling to be enabled by default in panels

### Did this work before?

It worked in Grafana 8 and 9, as well as 10, but with the feature toggle disabled.

### How do we reproduce it?

1. Add a Twinmaker datasource, or use one from plugin provisioning
2. Add a panel in a new dashboard
3. Select Twinmaker Query Editor visualization
4. Enter SELECT e.entityName FROM EntityGraph MATCH (e) in the editor and run the query
5. Notice that the bottom part of the query editor panel is cut off, but it isn't scrollable
6. If you save and return to the dasboard, the panel isn't scrollable there either

### Environment (with versions)?

Grafana: 10
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Twinmaker

**Comment by kaydelaney** [comment]
I think typically panel plugins have wrapped their content with the [CustomScrollbar](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx) component when scrollable content is desired, but that doesn't seem to be the case with the twinmaker plugin.

Adding `overflow: auto;` to the panel content css also might work, but I'm not sure if that would break things elsewhere...

**Comment by idastambuk** [comment]
Hi @kaydelaney it looks like wrapping the panel in CustomScrollbar works, thanks for the suggestion! We can implement this in Twinmaker, unless your team wants to further investigate this?

**Comment by kaydelaney** [comment]
Closing since a solution seems to have been found
