### ISSUE TITLE
[BUG] Unauthorized when access http api - with configured ldap authentification

### ISSUE THREAD

**Issue by runningAgain** [grafana/grafana#7543]
- What Grafana version are you using?
   4.1.1
- What datasource are you using?
   InfluxDB
- What OS are you running grafana on?
   RHEL7
- What did you do?
   Access http api with Authorization Bearer and a simple request /api/org   or /api/dashboards/home
- What was the expected result?
   normally json data about the requested org or home dashboard
- What happened instead?
   the following error "Invoke-RestMethod : {"message":"Unauthorized"}"

Grafana is running with postgresql as datastore and session datastore. Ldap is successfully configured and working. Ldap is the only authentication method.

**Comment by torkelo** [comment]
How did you access Grafana HTTP API? using API Token? Using Basic Auth? Those are the only options

**Comment by runningAgain** [comment]
Yes, i use both, Basic and Token. But it doesnt work ....
When i use grafana without ldap authentication i can use http api successfully. With ldap authentication enabled ... http api with basic or token doesnt work.

The Question is, when we use grafana frontend with ldap authentication, can we also use token or basic authentication to access http api ? it seem's that this is not working.

**Comment by torkelo** [comment]
Yes, both work fine,  or at least api token should work fine, basic auth should also work, not sure

**Comment by torkelo** [comment]
You should be able to use api token (works here at least), and no reports of api tokens not working when ldap is enabled. 

Basic auth should also work but only for local grafana user/passwords, as the basic auth mechanism is not integrated with ldap auth

**Comment by wangycc** [comment]
same problem, 401 authentication failed via base authentication when ldap authentication configuration is enabled.

grafana running in kubernetes, I need to import some initialization data after deploying grafana, how should I access the http api.
