### ISSUE TITLE
Alerts based on stat panels in dashboards

### ISSUE THREAD

**Issue by AlexLamond** [grafana/grafana#75440]
**Why is this needed**:

This feature would reduce the complexity in creating alerts on Grafana, whilst allowing much more complicated alerts to be created from numerous data sources and queries

**What would you like to be added**:

I currently have a number of queries where data is coming from Zabbix, and then some transforms, texts and exclusions are being made in order to generate time series graphs or, more importantly for this feature request, stats. In my opinion, stats are a huge part of Grafana, but I find it very difficult to create alerts for them. I can't simply click 'Create Alert', I have to try and manually set it up. Some have specific timeframes, or text files they are filtering on, and Grafana Alerts do not seem to support these

It would be amazing to be able to have alerts created from evaluations of stats based on the dashboard they are in. So if I have a numerical limit, over a 30 day period from mid-month to mid-month, then I can create an alert on that specific panel and voila, should it exceed on that dashboard I get alerted

**Who is this feature for?**

This would be great for any user who is getting started with, or increasing their use of Grafana alerts

**Comment by Quazmoz** [comment]
+1
This would be useful for me as well
