### ISSUE TITLE
[Bug] Graph not drawing multiple hosts 

### ISSUE THREAD

**Issue by copenlc** [grafana/grafana#7544]
Hello, I have a graph using a template that should be showing 20+ checks,  What seems to be happening is that the graph is only showing 7 machines when the all option is selected.  Attached is a screen shot of what happening and what I am seeing.  When I select a indivual host that is not being graphed, instead of using the "ALL" option it seems to draw on the graph correctly. 

http://imgur.com/a/iSbkB

Please include this information:
- 4.1.1
- InfluxDB 1.2.0
- CentOS Linux release 7.3.1611 (Core)
- Graphing multiple hosts via a host name Template to graph all at the same time
- All the hosts to graph lines on a single graph
- Graphs are missing when the "ALL" option is select.  When I individually select hosts, graphs work as desired.

![1241 working](https://cloud.githubusercontent.com/assets/25438177/22898273/9a0f594c-f1f4-11e6-8b4e-a936de473370.PNG)
![missing](https://cloud.githubusercontent.com/assets/25438177/22898271/99edcf8e-f1f4-11e6-8e4b-de3cc1cc78bf.PNG)
![multi-request](https://cloud.githubusercontent.com/assets/25438177/22898270/99e15de4-f1f4-11e6-88b8-946d2238c7ad.PNG)
![breakout_of_query](https://cloud.githubusercontent.com/assets/25438177/22898272/9a012084-f1f4-11e6-9be3-61af6c3d0855.PNG)

![template](https://cloud.githubusercontent.com/assets/25438177/22898301/c05b5272-f1f4-11e6-9a6a-1139f413d8ef.PNG)

**Comment by copenlc** [comment]
To add to the weirdness, when I duplicate a graph to work from, multiple more hosts appear.  Then after a second or two the hosts are added and drawn back into the original graph. 

![duplicate](https://cloud.githubusercontent.com/assets/25438177/22902771/31195db0-f204-11e6-8cf2-a1d9c302f6e2.PNG)

![dup2](https://cloud.githubusercontent.com/assets/25438177/22902769/2dc625ee-f204-11e6-8298-5d3e354c89f5.PNG)

**Comment by phemmer** [comment]
This is very likely a dup of #7380

**Comment by jdmaloney** [comment]
I am seeing this too, as I turn off the visibility on the different queries different hosts will show up.  The graph will sometimes plot like it doesn't have recent data for that metric, but when I copy and paste the query into influx I get data that is in the time range that is not getting plotted.  

For example in the attached image, I limited the graph to only show 2 of the 6 hosts I'm plotting, one shows data all the way through, the other stops part of the way.  Influxdb has all the data and the same queries from grafana show all the data in influxdb for that time range.  All systems are in sync with ntp and the timestamps in influxdb show all are inserting data normally.  Grafana package installed: 4.1.2-1486989747 on CentOS 7.3.1611

![screen shot 2017-02-16 at 2 44 57 pm](https://cloud.githubusercontent.com/assets/16138910/23040754/1e4653cc-f458-11e6-963b-92018c80f77a.png)

**Comment by phemmer** [comment]
@jdmaloney see #7380

**Comment by jdmaloney** [comment]
@phemmer Thanks!

**Comment by copenlc** [comment]
Bug has been resolved with an update to InfluxDB 1.2.2.
