### ISSUE TITLE
Tempo Trace View “Find in page” missing (Removed Feature/Bug?)

### ISSUE THREAD

**Issue by ovidiubuligan** [grafana/grafana#75455]
After I upgraded to 10.0.1.1 , this feature is missing and replaced with a less usefull “Trace Filter”.
To search for something now I need to download trace …which is a pain.
Last search I did was actually searching for attribute name .
Can we bring back full text search ?

![image](https://github.com/grafana/grafana/assets/4757459/4f8956f9-4024-4df5-a12e-bf8ba95166bd)

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/grafana/pull/78628
