### ISSUE TITLE
[Bug] Query results for a specific point in time fail to render on page

### ISSUE THREAD

**Issue by jl98800** [grafana/grafana#7545]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?  3.1.0
- What datasource are you using?  Influxdb v1.2 (recently upgraded)
- What OS are you running grafana on?  Ubuntu 14.04
- What did you do?  See results in tables and graphs past 3 hours and up to 5 years - a snapshot of that point in time. 
- What was the expected result?  
We should see data for all time intervals from 5 minutes out to 5 years.  We aren't seeing data past the first 2 queries (below) after 3 hours.
- What happened instead?
Nothing is returned for most queries past 3 hours. If result is null still nothing is displayed on the page.  Like the query never ran. But results show data is returned. 

### Bug report

__System info:__ [Ubuntu 14.04, Influxdb version is 1.2 (recently upgraded).
 Grafana version is 3.1.0. ]

__Steps to reproduce:__

1. Every 60 seconds we run 8 queries to pull data from InfluxDB and present it in a Grafana dashboard. 

Queries:
 A
SELECT last("value") FROM "jobs.running" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
B 
SELECT last("value") FROM "jobs.failed" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
C
SELECT last("value") FROM "jobs.succeeded" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
D
SELECT last("value") FROM "jobs.failed_awaiting_restart" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
E
SELECT last("value") FROM "jobs.long_running" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
F
SELECT last("value") FROM "jobs.total" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)
G
SELECT last("value") FROM "jobs.avg_job_attempts" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

H SELECT last("value") FROM "jobs.avg_run_time" WHERE "app" = 'app_name' AND "envt" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)

2. View the time intervals in Grafana under quick ranges shows all data from 5 minutes to 3 hours.  Then many queries fail to render anything (including null values).  We need to see data in snapshots or chunks of time for all supported ranges in Grafana (up to 5 years).

__Expected behavior:__ [What you expected to happen]
Then many queries fail to render anything (including null values).  We need to see data in snapshots or chunks of time for all supported ranges in Grafana (up to 5 years).  We were expecting data in tables/graphs to show up for that point in time - even if null.

__Actual behavior:__ [What actually happened]
Rows fail to render in results for tables and graphs show not values (nothing) for points in time past 3 hours.

**Comment by jl98800** [comment]
More info:

I was taking a look in developer tools to see what the request was going to influx for time interval
If I choose 30days, then the interval is 30minutes
If I choose 1year, then the interval is 6hours
30days * 24 hours * 60 minutes * 8 metrics = 345,600 / 30 = 11,520
365 days * 24 hours * 60 minutes * 8 metrics = 4,204,800 / (6hrs*60)  = 11,680
so it seems that the max-row-limit needs to be about 12,000
for 8 metrics

This may work for us.

**Comment by torkelo** [comment]
Not sure if there is a Grafana bug here. Is grafana issuing the wrong query and not showing data InfluxDB returns? 

Is probably related to a breaking change in InfluxDB 1.2, https://github.com/grafana/grafana/issues/7380
