### ISSUE TITLE
[Bug] Blurred graphs since v4

### ISSUE THREAD

**Issue by jakubbartel** [grafana/grafana#7546]
Hi,
since grafana version 4 there is an issue with blurred middle of all graphs.

- What Grafana version are you using?
Issue tested on all v4 versions available on dockerhub. (We were using multiple v3 versions before.)
- What datasource are you using?
Influxdb (but not related, I guess).
- What OS are you running grafana on?
Currently Chrome on windows "User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
Tested also in Edge and many other computers in our company. (but if I remember not tested on Mac)
- What did you do?
Looked on the graphs :)
- What was the expected result?
Sharp graphs :)
- What happened instead?
Graphs (all of them) that are blurred in the middle.

It doesn't matter what type of graph it is, what window size I have, resolution, there is no antialiasing etc.

When I drag a window and try to resize it, and also when I switch browser panels, for a short while (like 0,1 sec.) I can see sharp version of the graph, then left and right halfs "go together" and graph starts to be blurred – the closer you watch to the (horizontal) middle of the graph, more blurred the graph is.

I have these two examples, but I can provide as many of them as you want.

![grafana_blurred_1](https://cloud.githubusercontent.com/assets/22750048/22904385/902034b8-f23c-11e6-98dc-4fbddb94f915.png)

![grafana_blurred_2](https://cloud.githubusercontent.com/assets/22750048/22904388/9574813a-f23c-11e6-83b1-d4cff373342b.png)

Also maybe related with this one #7496 ?

Thank you for your time!

Jakub

**Comment by torkelo** [comment]
there has been no change here. Must be a change in how browsers render canvas. It is a matter how the canvas aligns with the pixel grid. Sometimes it align sometimes now, this must be the same in v3, think the difference you saw must be a fluke (meaning v3 should be blurry at times as well)
