### ISSUE TITLE
Docs: state data source queried upon time range change

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#75475]
Add query variable documentation is misleading:
https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-a-query-variable

In explanation of "On Time Range Change" option, clarify that this option queries the data source every time the dashboard loads AND when the dashboard time range changes. (I.e., no matter which dashboard variable query option you choose, the query always runs at dashboard load.)

**Comment by chauchausoup** [comment]
@imatwawana is this a proper explanation ?

<img width="817" alt="Screenshot 2023-09-28 at 16 58 01" src="https://github.com/grafana/grafana/assets/34975245/ef35a8be-6e0b-4bed-b44b-ad35e9bca283">

Let me know.
