### ISSUE TITLE
Docs: enhance disabling presence indicator content

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#75476]
Presence indicator documentation isn't detailed enough:
https://grafana.com/docs/grafana/latest/dashboards/assess-dashboard-usage/#presence-indicator

Documentation does not mention that for disabling presence indicator on the dashboards you can configure 
 [analytics.views]
recent_users_age = 0

In order to hide this information

**Comment by chauchausoup** [comment]
@imatwawana will this work ?
<img width="796" alt="Screenshot 2023-09-28 at 18 11 13" src="https://github.com/grafana/grafana/assets/34975245/a84c317b-f772-443c-ab09-07f724bbeab6">
