### ISSUE TITLE
CloudWatch: Use the WithContext versions of functions for resource handlers

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#75498]
**What is the chore?**:
The resource handlers in CloudWatch currently use the non-context versions of the CloudWatch API calls (ex. [DescribeInstancesPages](https://github.com/grafana/grafana/blob/ebec452f9f9b21ee8d345a5ec30224d2e8b4eb8c/pkg/tsdb/cloudwatch/metric_find_query.go#L254) instead of [DescribeInstancesPagesWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeInstancesPagesWithContext) and [ListMetricsPages](https://github.com/grafana/grafana/blob/ebec452f9f9b21ee8d345a5ec30224d2e8b4eb8c/pkg/tsdb/cloudwatch/clients/metrics.go#L25) instead of [ListMetricsPagesWithContext](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.ListMetricsPagesWithContext)). It's important to use the `WithContext` versions, so that the requests are cancelable.

Checklist of necessary updates:
- [x] [DescribeInstancesPages](https://github.com/grafana/grafana/blob/ebec452f9f9b21ee8d345a5ec30224d2e8b4eb8c/pkg/tsdb/cloudwatch/metric_find_query.go#L254) https://github.com/grafana/grafana/pull/76855
- [x] [DescribeRegions](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/services/regions.go#L39) https://github.com/grafana/grafana/pull/76922
- [x] [ListMetricsPages](https://github.com/grafana/grafana/blob/ebec452f9f9b21ee8d345a5ec30224d2e8b4eb8c/pkg/tsdb/cloudwatch/clients/metrics.go#L25) https://github.com/grafana/grafana/pull/76938
- [x] [GetResourcesPages](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/metric_find_query.go#L277) https://github.com/grafana/grafana/pull/76921
- [x] [DescribeLogGroups](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/services/log_groups.go#L39) https://github.com/grafana/grafana/pull/77176
- [x] [GetLogGroupFields](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/services/log_groups.go#L73) https://github.com/grafana/grafana/pull/77174
- [ ] [ListMetricsPages](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/clients/metrics.go#L25)
- [x] [ListSinks](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/services/accounts.go#L27) and [ListAttachedLinks](https://github.com/grafana/grafana/blob/ecbc52f51529e1f35e26895db1a10f8a1c2f4244/pkg/tsdb/cloudwatch/services/accounts.go#L64) (In the same function) https://github.com/grafana/grafana/pull/77083

If you're doing this for hacktoberfest, feel free to take one function and not all of them, it's a lot of refactoring. (Though maybe claim it in the comments)

**Is there anything else we need to know?**:

**Comment by pucke-uninow** [comment]
I would like to work on this one

**Comment by iwysiu** [comment]
Hi @pucke-uninow ! Feel free to work on it! (you don't have to be assigned) If you have any questions, I'll be happy to answer them.

**Comment by shabeebk** [comment]
@iwysiu Created a PR in case this is still open. Looks like no work is done still.
