### ISSUE TITLE
Azure Monitor: Dashboards with logs crashing after upgrade to v10.1.2 

### ISSUE THREAD

**Issue by Gerthum** [grafana/grafana#75497]
### What happened?

After upgrading to Grafana 10.1.2 Dashboards that use Azure Monitor logs queries started timing out and crashing. 

The issue seemed to be caused by the following feature:
https://github.com/grafana/grafana/pull/71278

It defaults to Query which requires you to specify the time range in the  query instead of using the dashboard time range. 

Switching it to Intersection or specifying a time range solves the problem. 

I'm creating this bug purely for informational purposes. 

### What did you expect to happen?

Grafana dashboard to not crash. 

### Did this work before?

Yes 

### How do we reproduce it?

1. Upgrade to 10.1.2
2. Use Azure Monitor Visualization with no time range specified in query.  
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by aangelisc** [comment]
Hey @Gerthum, were you using the `Intersection` property? Could you share your dashboard JSON? This behaviour has been changed as of #74675 which will be released in 10.2

**Comment by Gerthum** [comment]
Hi @aangelisc - I posted this purely for informational purposes as I had the issue and it took a bit of investigation to resolve. So leaving it here for anyone else having the issue. 

The resolution is after upgrading to 10.1.2 if your Log Analytics Visualizations are slow and causing Grafana to crash. Make sure you switch to using the Intersection property if you have not specified a time range in your queries.
