### ISSUE TITLE
Grafana Snapshot creates graphs and stats with wrong data 

### ISSUE THREAD

**Issue by cpazjma** [grafana/grafana#75495]
### What happened?

When exporting as dashboard the graphs and stats shows innacurate data. The values in the snapshot doesn't match with the ones observed in Grafana. 

### What did you expect to happen?

snapshot generated with the same data and values as visible in Grafana. 

### Did this work before?

no, never, accross different Grafana instances

### How do we reproduce it?

1. Go to a dashboard
2. Click on Share > Snapshot > configure it as below:
![image](https://github.com/grafana/grafana/assets/146129363/bc7948ae-0ec3-425a-b43d-cca3559e14ff)
 (We tested with different timeouts.. 600, 1200, 1800 and always at least 1 graph fails. 
4. click on public to snapshots.raintank.io
5. issue: some graphs are corrupted for example grapsh below. 

![snapshot _ wrong data](https://github.com/grafana/grafana/assets/146129363/bdac6bab-2cbb-45df-a29f-71ea06222036)

6. Above data doesn't match with the real one observed in Grafana for exactly the same graph for same devices and date/time range are below. 

![screenshot from Grafana - values OK](https://github.com/grafana/grafana/assets/146129363/81ff8b6b-0f51-474d-a673-22d1ffef7bdb)

### Environment (with versions)?

Grafana: v8.5.2 
OS: 
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by cpazjma** [comment]
Hello, 

Any update related to this ticket? 
Please let me know. 

Thank You, 

Camilo Solarte
JMA Wireless

**Comment by cpazjma** [comment]
Please let us know if you have had any progress on this or required any additional information. 

We have several deployments and urgent need to create and export snapshots. 

Regards, 

Camilo Solarte
JMA Wireless

**Comment by cpazjma** [comment]
Helleo, 

Do you have any update for this case? 
Is this a known issue or identfied to be fixed in a future sw release ? 

Please let me know. 
Thank You, 

Camilo

**Comment by juanicabanas** [comment]
Hi @cpazjma. 
I'm investigating this issue. 
Have you considered updating Grafana to a newer version? 
On the other hand, it's also possible to share a dashboard via public dashboards feature, which was introduced since Grafana 9.1.
We're aware of some issues in snapshots and public dashboards could be a workaround, while I check the issue

**Comment by cpazjma** [comment]
Hi Juan,

Thank you for reaching out.

We are seeing the issue even on Grafana v10.1.1 (0cfa76b22d).

Below you will find a comparison between the real data seen in Grafana server and the one in the snapshot feature (link below) that is incorrect. As mentioned before, we have tested with different time outs or less complex dashboard, but it is not reliable since use to fail to display the same info we see in Grafana directly.

https://snapshots.raintank.io/dashboard/snapshot/ywRtq1rRVGcjZ0tb1HGsfnTcoLqkr62m?orgId=2

For example.
Real information from Grafana directly.
***@***.***

***@***.***


Same Information in the snapshot.
***@***.***

***@***.***

Regards,


***@***.***
Camilo Jose Solarte
Analyst NOC, Tier 1
***@***.******@***.***>
+1 3158982843
www.jmawireless.com<http://www.jmawireless.com/>

**Comment by juanicabanas** [comment]
@cpazjma have you tried public dashboards? I think that could fit your needs.
On the other hand, could you share with me the JSON model of one of those dashboards and a link to its snapshot?
Thanks!

**Comment by cpazjma** [comment]
Hello Juan,

Thank you for your feedback. Please find attached json file for one of the dashboards that we need to snapshot.

When you say public dashboard do you refer to below option ? or where is that feature ?

***@***.***

Regards,


***@***.***
Camilo Jose Solarte
Analyst NOC, Tier 1
***@***.******@***.***>
+1 3158982843
www.jmawireless.com<http://www.jmawireless.com/>

**Comment by juanicabanas** [comment]
@cpazjma I cannot see any attached json file (look at the format of your message, there might be something wrong because it's being replied by an email)
You can take a look at Public Dashboard feature [here](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/). It's in public preview but it will be in GA sooner. 
You can enable it via a feature flag, like [here](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/#enable-the-feature)

**Comment by cpazjma** [comment]
Hello Juan,

Please find attached the json file. 
I also tried enabling the public dashboard but I am getting following error when using the feature.  

![image](https://github.com/grafana/grafana/assets/146129363/f4ac5f5e-9aa5-411a-9d38-4911e5afa212)


Can you please advise. 

Regards, 

Camilo Solarte


[KPI Dashboard SU - 4G - Multi eNB - Summary-1695304495947.json](https://github.com/grafana/grafana/files/12894317/KPI.Dashboard.SU.-.4G.-.Multi.eNB.-.Summary-1695304495947.json)

**Comment by evictorero** [comment]
Hi @cpazjma that is not an error, just a warning that public dashboards do not support template variables.
The dashboard you shared has a lot of panels so my guess is the problem generating snapshot is about loading a lot of panels.
You could increase the timeout or split the dashboard and try generating a snapshot with fewer panels so at least you can confirm there is a timeout problem with loading panels.

**Comment by lucychen-grafana** [comment]
Hi @cpazjma ,

Just wanted to follow up and see if you were able to utilize the Public Dashboards feature for your need

**Comment by cpazjma** [comment]
Hello,

Thank you for reaching out.

We were not able to use it, we don’t longer need this feature.

Thank you for your support until this point.

Regards,


***@***.***
Camilo Jose Solarte
Analyst NOC, Tier 1
***@***.******@***.***>
+1 3158982843
www.jmawireless.com<http://www.jmawireless.com/>

**Comment by lucychen-grafana** [comment]
@cpazjma sounds good. I will go ahead and close this issue then
