### ISSUE TITLE
[Bug] Invalid Basic Auth Header

### ISSUE THREAD

**Issue by alqassak** [grafana/grafana#7550]
- What Grafana version are you using?
We are using Grafana 4.1.1

- What datasource are you using?
The data source that we are trying to connect to is OSIsoft-PI

- What OS are you running grafana on?
Windows 2012 R2 Server

- What did you do?
Creating OSIsoft-PI data source
![image](https://cloud.githubusercontent.com/assets/25760677/22915191/79215cf2-f286-11e6-81a7-901cb23205f4.png)

- What was the expected result?
To connect successfully
![image](https://cloud.githubusercontent.com/assets/25760677/22915072/b87e68e6-f285-11e6-9865-0ebc9c9a8e84.png)

- What happened instead?
We start getting Invalid Basic Auth Header and "GET http://GRAFANA_URL:8080/api/datasources/proxy/5/assetdatabases?path=\\AF_SERVER\Grafana 401 (Unauthorized)"

Also sometimes we receive Success: Data source is working but when we try to get the assets from AF it show us empty elements.

**Comment by torkelo** [comment]
I see you already opened a question for this datasource.  https://github.com/GridProtectionAlliance/osisoftpi-grafana/issues/2 

Since we have no other reports on problems with basic auth I think this is specific to this data source plugin.
