### ISSUE TITLE
Cannot update/uninstall clock (core) plugin

### ISSUE THREAD

**Issue by Derek-K** [grafana/grafana#75505]
### What happened?

Upgraded Grafana to v10.1.2 (2b2d40ba32)

One of the dashboard uses clock plugin and crashed. Attempt to update/uninstall clock plugin failed

![image](https://github.com/grafana/grafana/assets/16491026/c4d3f409-bbac-4c59-b58d-1de13285a523)

### What did you expect to happen?

Should be able to update plugin flawlessly. Core plugin should not have invalid signature, or able to allow exception.

### Did this work before?

N/A

### How do we reproduce it?

1. Under Grafana from 7.0.0 (with clock plugin 1.1.1 installed) create a dashboard contain clock panel (other additional panels are optional)
2. Upgrade Grafana from 7.0.0 to 10.1.2 (with clock plugin 1.1.1 installed)
3. Open the dashboard created in step 1.
4. Try to "Update" or "Uninstall" Clock plugin

### Is the bug inside a dashboard panel?

![image](https://github.com/grafana/grafana/assets/16491026/251fe519-9edd-4307-82c8-7eb8dff4a67c)

### Environment (with versions)?

Grafana: 10.1.2
OS: Windows 10
Browser: Chrome Version 117.0.5938.92

### Grafana platform?

A downloaded binary

### Datasource(s)?

NA

**Comment by academo** [comment]
Hi @Derek-K 

We've seen a [similar error before](https://community.grafana.com/t/update-to-grafana-9-got-a-error-plugins-grafana-clock-panel-module-js/67472) and this is most likely caused by the very old clock panel plugin version having no compatibility with this more modern version of grafana.

My advice is to update the plugin via [grafana cli](https://grafana.com/docs/grafana/latest/cli/).  Try running `grafana cli plugins install grafana-clock-panel` using the same binary you use to initialize grafana. Check again. a grafana restart might  be necessary.

**Comment by Derek-K** [comment]
> grafana cli plugins install grafana-clock-panel

![image](https://github.com/grafana/grafana/assets/16491026/c9dad74e-a3b3-4dc0-8036-cbb662a19ae9)

I tried, but keep getting this error, and I have stopped the Grafana service already.

I have tried to remove it first but the result is the same
![image](https://github.com/grafana/grafana/assets/16491026/ccd6078f-373b-42dc-a762-da65cc287bdc)
 
Notice the zip file in Temp is different every time, not sure what process is using it, and somehow cli thinks it's install ok. But upon restarting grafana, it still shows v 1.1.1

**Comment by academo** [comment]
@Derek-K  It seems there's something in your computer blocking that specific file from working. I suggest you make sure grafana is really stopped (check if you can access it locally) and if you keep getting this error, reboot your computer.

this specific error is not a grafana one, but something in your computer keeping hold on the file grafana is trying to use

**Comment by Derek-K** [comment]
> @Derek-K It seems there's something in your computer blocking that specific file from working. I suggest you make sure grafana is really stopped (check if you can access it locally) and if you keep getting this error, reboot your computer.
> 
> this specific error is not a grafana one, but something in your computer keeping hold on the file grafana is trying to use

I did make sure the service is stopped, and try to access it with web browser to confirm.
I tried regular command prompt and "run as administrator" cmd, same results.
*BUT* when I check ```..data\plugins\grafana-clock-panel\plugin.json``` it does show

```
    "updated": "2023-09-04",
    "version": "2.1.3"
```

I have even tried to reboot, grafana plug panel still showing version 1.1.1
weird...

**Comment by Derek-K** [comment]
> @Derek-K could you please share your `custom.ini` file? Or if you have edit your `default.ini`. Can you provide that one?

I don't seems to have a `custom.ini` and not sure what to edit in `default.ini` but I looked inside `default.ini` this seems to be correct

```
# Directory where grafana will automatically scan and look for plugins
plugins = data/plugins
```
Another thing I have tried.
1) Stopped grafana via windows services panel
2) ```grafana cli plugins remove grafana-clock-panel```
3) Check ```\Program Files\GrafanaLabs\grafana\data\plugins``` directory and no longer have the ```grafana-clock-panel``` directory
4) Start grafana via windows services panel
5) Go to ```Home > Administration > Plugins``` and dang! Clock panel v1.1.1 still there?!!

**Comment by Derek-K** [comment]
> Ok ok, do you have access to the Grafana service output? Also, can you check if you have set any environment variables starting with `GF_`? I just want to double check that you are running your instance with the `plugin path` pointed to `\Program Files\GrafanaLabs\grafana\data\plugins`.

Not sure how to get the Grafana service output.. but I searched my harddrives, and found this.
![image](https://github.com/grafana/grafana/assets/16491026/53c2040b-878a-4212-ac22-0408f5110e2a)

That must be where it is coming from! (from *previous* version of Grafana, see the date) 

Deleted that directory, restarted Grafana to make sure clock panel is gone. Stopped grafana, install clock panel via cli, restart grafana, tada!!

**Comment by mckn** [comment]
Nice, case closed I guess?
