### ISSUE TITLE
Tests: Investigate why query tests fail when padding changes

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#75519]
While working on https://github.com/grafana/grafana/pull/74536/ Haris found that if padding is removed from columnWrapper in public/app/features/explore/Explore.tsx:

```diff
    columnWrapper: css({
      display: 'flex',
      flexDirection: 'column',
-     padding: theme.spacing(0, 0.25),
      flex: '1 1 auto',
    }),
```

The test in explore/spec/query.test.tsx fails (queries are not executed, results are not rendered).

It'd be good to timebox some investigation to figure out why it's happning.

**Comment by luan-cestari** [comment]
Hi @ifrost =) I was wondering if I can take a look for https://hacktoberfest.com . Or do you have another issue you would recommend?

**Comment by ifrost** [comment]
Hi @luan-cestari! Feel free to give it a shot, though this one might be tricky. You can also have a look at list of issues we labeled as recommended for hacktoberfest: https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+ Happy hacking!
