### ISSUE TITLE
[Feature request] Allow setting graph defaults

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#7552]
It would be really nice if we were able to change the default settings on graphs.
In our use case, several of the defaults are rather unpleasant, and we change them on every graph we create.
For example "Display -> Null value -> connected", or "Display -> Fill -> 0", or "Metrics -> Group By -> Fill -> none", or "Axes -> Left Y -> Y-Min -> 0" (this one we sometimes leave, but rarely).

**Comment by bergquist** [comment]
I kinda like this idea.

This would also make it possible to create global series overrides and other default settings. @torkelo any thoughts?

**Comment by torkelo** [comment]
defaults sounds like a good idea

**Comment by phemmer** [comment]
closing as this is 6 years old now, and the last activity was >5 years ago.
