### ISSUE TITLE
i18n: Mark up `DashboardSettings` for translations

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#75531]
follow instructions [here](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-translation-phrase). can verify translation strings have been marked up correctly by running `yarn i18n:pseudo` and using the development-only pseudo locale: 
![image](https://github.com/grafana/grafana/assets/20999846/30890cfd-89bc-4d8f-8c47-daa8a92f5727)

section title checklists:
- [ ] Settings
- [ ] General
- [ ] Annotations
- [ ] Variables
- [ ] Links
- [ ] Versions
- [ ] Permissions
- [ ] JSON Model

**Comment by GalaxyGamingBoy** [comment]
Hi @ashharrison90!
I would like to give it a try, may I take it?

**Comment by ashharrison90** [comment]
hi @GalaxyGamingBoy 👋 

sure, feel free to raise a PR and mark that it fixes this issue. i tend to avoid assigning external contributors to issues in case they decide later that they don't have time anymore - having an assignee on an issue tends to dissuade other external contributors.

hope that makes sense! 😄
