### ISSUE TITLE
Plugins Catalog reports "Cannot install or change a Core plugin" in a non core plugin.

### ISSUE THREAD

**Issue by academo** [grafana/grafana#75537]
From [this report ](https://github.com/grafana/grafana/issues/75505) of a problem with a very old  version of clock panel migrating from grafana 7 to grafana 10 the user reports this screenshot

![image](https://github.com/grafana/grafana/assets/227916/8ac4f160-96b7-4f87-8056-96c884d3ec81)

We should investigate why the catalog refuses to uninstall/update this plugin when this big jump happens. 

note: this is a rather extreme edge case.

**Comment by sympatheticmoose** [comment]
Good to track this and record in case it comes up again, but probably not something we need to prioritise right now.
