### ISSUE TITLE
i18n: Mark up `GeneralSettings` for translations

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#75530]
follow instructions [here](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-translation-phrase). can verify translation strings have been marked up correctly by running `yarn i18n:pseudo` and using the development-only pseudo locale: 
![image](https://github.com/grafana/grafana/assets/20999846/30890cfd-89bc-4d8f-8c47-daa8a92f5727)

checklist:
- [ ] Form field labels
- [ ] Form field descriptions
- [ ] Form subheadings
- [ ] Delete dashboard button

**Comment by KathanrDave** [comment]
Hey @ashharrison90 i would like to give it a try. Can you please assign it to me?

**Comment by ashharrison90** [comment]
hi @KathanrDave 👋 

sure, feel free to raise a PR and mark that it fixes this issue. i tend to avoid assigning external contributors to issues in case they decide later that they don't have time anymore - having an assignee on an issue tends to dissuade other external contributors.

hope that makes sense! 😄

**Comment by KathanrDave** [comment]
Okay no problem.
I get back with a query or a PR 🫡
Thanks!👍

**Comment by otilor** [comment]
@KathanrDave you can use https://github.com/grafana/grafana/pull/75549 as a pointer.
