### ISSUE TITLE
Alerting: distribute alert rule evaluations over time

### ISSUE THREAD

**Issue by sjpalf** [grafana/grafana#75544]
**Why is this needed**:

We have thousands of alert rules which are all evaluated once every 2 minutes. These rule evaluations are all executed at exactly the same time, which causes unacceptable latency (in our case from ~25ms to ~5 seconds). If we change our alert rule groups to run at different evaluation intervals then we can maintain our latency of 25ms most of the time, but occassionaly we will still get all evaluations occuring simultaneously.

**What would you like to be added**:

The alerting rule evaluation scheduler should automatically spread it's load over time and not run all evaluations at exactly the same time.
An alternative solution might be to add an offset to the rule group so that we can define when evaluations occur relative to other rule groups.

**Who is this feature for?**

Anyone who uses grafana alerting

**Comment by ryan-grafana** [comment]
this feature was released in 10.4
