### ISSUE TITLE
Rudderstack: do not trigger manage_dashboards_query_submitted on page load

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#75545]
When opening the dashboards browse page (including any folder pages), the manage_dashboards_query_submitted event gets triggered.

This causes issues in our analysis, for example when looking at % of searches with a specific filter, as the number of total searches (as measured by manage_dashboards_query_submitted) is higher than the actual searches performed (as it includes each page view as well.)

Expected: only trigger the event when there is a search performed, not on page load.

**Comment by yaelleC** [comment]
[Ash] : we could filter by query length!= 0

[Josh] We could add a new event when the search is actually user-initiated
