### ISSUE TITLE
[Feature request] Send notification when threshold is reached

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#7555]
I'm aware of the new Alert functionality brought by version 4.x of Grafana as well as the feature requests pending (e.g. #6553).

From my understanding, currently the thresholds are only for a visual purpose. Wouldn't be a plus if it was also possible to link the available alerting channels with the thresholds' menu, in order to send a notification every time a threshold is reached? 

Also, in terms of usability, I believe it's quite simple for someone to set up a threshold, that triggers a notification, than to set up an alerting condition query.

Does this feature request make sense?

**Comment by torkelo** [comment]
yes, makes perfect sense, it is what we spent 6+ months implementing last year (and will continue working on this year), http://docs.grafana.org/alerting/rules/

**Comment by antjori** [comment]
Hey @torkelo!

First of all thank you for the Alerting mechanism and for the quick response :100: 

I'm aware of the work you guys had, no disrespect. The thing's that, IMHO, the complexity of setting up a threshold is way smaller than creating the condition for the alert.

Therefore, after defining the notification channel, it would be almost linear to link the channel to the threshold and, once the threshold is surpassed, it would trigger the notification. Do you see what I mean?

Cheers!

**Comment by torkelo** [comment]
but that is how it works. you create a notification channel. You have a graph, you drag a threshold, you pick the notification, every time the threshold is reached the rule will go into alerting state and notifications will be sent out. 

Not sure what your want done differently

**Comment by antjori** [comment]
You're referring explicitly to the alert condition, which only allows you to have a single alert.

Do you think, having the same behavior on the thresholds, enhancing them from only visual to _alertish_, would somehow be redundant and will it almost degenerate on #6553?

**Comment by torkelo** [comment]
@antjori what do you mean single alert? you can create any number of alerts, and a threshold condition can be applied to many series. Not understanding what is stopping you from using alert rules with thresholds.

**Comment by antjori** [comment]
@torkelo when I say _single alert_ I mean an alert per panel, I'm sorry for not being completely clear.

**Comment by torkelo** [comment]
Yes, but a single alert can  have multiple thresholds and target multiple queries and series, so why is not enough?

**Comment by antjori** [comment]
Then perhaps is me who's not seeing things properly... Could you please explain how we can set up multiple thresholds on a single alert?

Because the panels, on the Live Demo, only have a single threshold defined. I assume the one associated with the condition.

**Comment by torkelo** [comment]
yes, but you can add many query conditions that use different or same query, you can have OR or AND operator between conditions, each condition can have thresholds

**Comment by antjori** [comment]
@torkelo I see what you mean, thank you for the enlightenment. :wink: 

Nevertheless, even if I define different queries and different conditions, visually I'll only have a single threshold line, correct?

![image](https://cloud.githubusercontent.com/assets/8490141/23117695/dea4df7e-f748-11e6-9fcc-55d1620fd0a2.png)

Which I think can make the user confused. Perhaps what I'm trying to suggest is what's already been proposed as a solution by you on #6553.

**Comment by torkelo** [comment]
no, that issue is only about setting severity on the whole alert rule. 

Yes, we only visualize the first threshold condition in the alert rule. If you have `within` or `outside` threshold (which contains two thresholds, upper and lower) we visualize both thresholds. 

With multiple conditions and thresholds it becomes next to impossible to visualize the thresholds correctly so that is why we only visualize the first condition and the special thresholds types (above, below, within etc).

**Comment by antjori** [comment]
Thank you for your time and for the explanation, I perfectly understand it now.
