### ISSUE TITLE
Ability to only display data source in variable query editor

### ISSUE THREAD

**Issue by cameronwaterman** [grafana/grafana#75551]
**Why is this needed**:

I have a use-case for a data source that only makes sense to be displayed in the context of the dashboard query variable editor.

See https://github.com/grafana/grafana/pull/75323 for more information.

**What would you like to be added**:

See PR referenced above.

**Who is this feature for?**

Developers of custom data sources.

**Comment by sunker** [comment]
Currently, the annotation editor, variable query editor and meta data inspector editor are opt-in for a data source. The query editor (displayed in panel edit and explore) is the only view that is not optional - the plugin is always displayed in the data source picker when in the panel edit or explore context. If this FR is implemented, it would be possible to opt-out on the query editor view too. However, it would need to default to `true` (i.e being displayed by default) to not break existing functionality. 

If you as a contributor wish to see this feature in Grafana, please upvote this issue and/or provide your feedback here.
