### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by onepif** [grafana/grafana#75554]
Greetings developers!
In accordance with [these instructions](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-language), I added an additional language, however, to my great regret, only a couple of buttons and one or two menus were translated in the interface.
What could be the reason?

**Comment by otilor** [comment]
Hi @onepif based on https://github.com/grafana/grafana/issues/70957 the internalization process is ongoing. Several issues have been added there (places we need to add support for internalization) and some of them have been addressed.

I think the Grafana guys would have more to say about whether you can document the specific part(s) that are missing out and possibly create a PR using https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#internationalization

**Comment by ashharrison90** [comment]
hi @onepif 👋 

previous comment is pretty much spot on - we're currently working on marking up the strings within core grafana as part of https://github.com/grafana/grafana/issues/70957. as more of these strings get marked up, more of the UI will start to be translated. 

if you'd like to assist in any way, we'll be periodically creating more issues in the epic above ☝️ 

thanks!

**Comment by onepif** [comment]
there are 2 more questions:
- why when switching to different languages the degree of translation is different;
- how much work has already been done on internationalization.

**Comment by ashharrison90** [comment]
@onepif 

> why when switching to different languages the degree of translation is different;

i'm not sure what you mean by "the degree of translation is different" 😕 at a basic level, the process is that we periodically send [our extracted strings](https://github.com/grafana/grafana/blob/main/public/locales/en-US/grafana.json) to translators who then translate the content (see e.g. [spanish](https://github.com/grafana/grafana/blob/main/public/locales/es-ES/grafana.json)). any strings currently missing in the translated message files will be populated the next time we send these files to translators. the more strings we extract into these message files, the more we translate. this is what the epic above is tracking.

> how much work has already been done on internationalization.

this is extremely difficult to estimate. the hardest part is setting up the initial tooling. this is complete for core grafana, but we still have work to do in the future to make this work for plugins. then there is the task we're currently doing which is extracting strings to the message files. the initial focus was on the viewer persona, so _most_ things specifically around viewers and dashboards should be translated. an extremely rough estimate for progress around all of grafana is it's probably about 10-15% translated.
