### ISSUE TITLE
[Bug] Snapshots show "no datapoints" for some graph panels

### ISSUE THREAD

**Issue by anandpaul24** [grafana/grafana#7556]
Grafana version - Grafana v4.1.2
Datasource  - InfluxDB v0.9
OS  - Windows Server 2012 R2 Standard

What did you do?
1. Use a dashboard to monitor over a extended period of time (11 hours in my case)
2. Create a snapshot of this time period
3. Check the graphs in the snapshot

What was the expected result?
Expecting to see all graph panels populated with same data as in the dashboard

What happened instead?
Some panels showing "No datapoints returned from metric query"

Screenshots of both the dashboard and snapshot attached.

![original_dashboard](https://cloud.githubusercontent.com/assets/25349049/22927542/bee686a4-f2a9-11e6-9656-766a001010b3.png)

![snapshot](https://cloud.githubusercontent.com/assets/25349049/22927549/ca0af092-f2a9-11e6-95ff-e49c74007978.png)

**Comment by torkelo** [comment]
this is due to some queries not completing before the snapshot is taken, 
https://github.com/grafana/grafana/issues/2537
