### ISSUE TITLE
[Bug] Metrics alias problem with wildcard in tags

### ISSUE THREAD

**Issue by gkissand** [grafana/grafana#7558]
Grafana version: 4.1.2
Datasource opentsdb 2.3.0
OS Debian 8

I added two metrics (memory used and memory free)
I added as tags "host=ecmwww* " on both
I added in Alias "used $tag_host" and "free $tag_host"
I expected to see legends named "used hostname" and "free hostname"
Instead i got all "used hostname" for both metrics
This happens if in tags i have wildcard (asterisk)
It does not happen if i don't have wildcard in tags or use Filters

![capture](https://cloud.githubusercontent.com/assets/25226373/22928418/aa7956b2-f2b6-11e6-80dd-ccaea60af62f.PNG)

**Comment by torkelo** [comment]
This is a limitation in OpenTSDB that requires OpenTSDB 2.3+ I think,

#1876

**Comment by gkissand** [comment]
Hi Torkelo

2.3+ is 2.3.0 and above or earlier version than 2.3.0?
I have 2.3.0
Nevertheless i have to wait for a newer opentsdb probably

thank you
