### ISSUE TITLE
[Feature request] Additional unit Degree / Angle "°" 

### ISSUE THREAD

**Issue by lost-carrier** [grafana/grafana#7559]
I'm currently running Grafana inside in Docker backed by InfluxDB with some weather-related metrics.

While various useful units are already present (°C, °F, km/h, ...) I'm still missing the unit for degree of angles or rotation (or azimuth, altitude, wind-direction...) with symbol being just "°".

Can this be added? https://en.wikipedia.org/wiki/Degree_(angle)

**Comment by daniellee** [comment]
Yes, we accept PR's for new units. This PR was merged today that added some physics units (force, pressure and flow):

https://github.com/grafana/grafana/pull/7554

**Comment by Ismael** [comment]
But maybe there could be a way to add custom units from the UI?

**Comment by torkelo** [comment]
possible now via custom user-specified units: https://github.com/grafana/grafana/pull/20763
