### ISSUE TITLE
Alerting: The “Configure no data and error handling” settings do not work correctly

### ISSUE THREAD

**Issue by Pro100x3mal** [grafana/grafana#75594]
### What happened?

The “Configure no data and error handling” settings do not work correctly. The “state if no data or null” and “state if execution error or timeout” settings do not affect the sending of notifications. Both parameters are set to "OK", but I still receive fire notifications when the request contains the NaN value.
![IMG_0507](https://github.com/grafana/grafana/assets/87969152/1bd4287e-96cb-4a1f-8041-59f7ec44b326)
![IMG_0506](https://github.com/grafana/grafana/assets/87969152/3dffa67c-a5f9-4435-9fb6-9c9d84918566)
![IMG_3261](https://github.com/grafana/grafana/assets/87969152/e764878b-ffbd-4626-a7fb-f4f1f8524ba1)

### What did you expect to happen?

When I set the “state if no data or null” and “state if execution error or timeout” parameters to “OK”, I expect not to be notified when an alert is triggered if the request has the value “NaN”

### Did this work before?

Don’t know 

### How do we reproduce it?

1. Alert Rules - New Alert Rule
2. Set alert evaluation behavior - Configure no data and error handling
3. Select OK in Alert state if no data or all values are null
4. Select OK in Alert state if execution error or timeout
5. Add expression with NaN value
6. Grafana send Alert notification instead of enabling the Normal status

### Environment (with versions)?

Grafana: 10.1.2
OS: Ubuntu 22
Browser: Safari
DB: Prometheus

### Grafana platform?

A downloaded binary

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
thank you for creating the issue @Pro100x3mal 

I could not repro the same behaviour from my end
The issue is now added to the alerting team's board for review

**Comment by armandgrillet** [comment]
You should do a `replace non numeric value` via the reduce operation, the issue is the handling of NaN.
![image](https://github.com/grafana/grafana/assets/2117580/5024d80c-f102-4d8c-b069-56f500104e85)
