### ISSUE TITLE
[Bug] multiple instances of same metric (with different aliases) doesn't show alaises

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#7560]
Grafana 4.1
Datasource opentsdb 2.2
OS RHEL 7.2
![capture](https://cloud.githubusercontent.com/assets/10222648/22930507/9e09763c-f28e-11e6-922a-56cb021169ea.PNG)

I want to display the same metric on one graph twice.  In this case cpu.percent.idle.  The first metric is the raw data, but the second metric is a downsampled 5 minute average.

For the two metrics I define an alias, "% Idle" and "% 5M Avg Idle", however the display and hover over only shows the first alias which in this case is "% Idle"

See screen snapshot.

**Comment by torkelo** [comment]
This is a limitation in OpenTSDB that requires OpenTSDB 2.3+ I think, 

https://github.com/grafana/grafana/issues/1876

**Comment by torkelo** [comment]
Try setting OpenTSDB version in data source options, not sure if that makes a difference.
