### ISSUE TITLE
Grafana User Session: Session does not expire after password reset/change.

### ISSUE THREAD

**Issue by iUtsavB** [grafana/grafana#75601]
### What happened?

When I reset/change grafana user password, session continues, user does not get logged out of the UI.

### What did you expect to happen?

User to logged out automatically after password reset/change.

### Did this work before?

No

### How do we reproduce it?

1. by changing the password.
2. by resetting the password.

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: v9.3.2 (21c1d14e91)
OS: Mac OS
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @iUtsavB 
Could you increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors? 

thank you
