### ISSUE TITLE
[Feature request] In axes->Series mode, allow sorting the series

### ISSUE THREAD

**Issue by Ismael** [grafana/grafana#7561]
Please include this information:
- What Grafana version are you using?
4.1.1

- What datasource are you using?
Graphite

When I'm using Axes -> X-Axis -> Mode = Series; I'd like to be able to sort the bars by their name. In the screenshot, I'd like them to be sorted from least to most (57,85..... 549, 555)

In general, maybe allow specifying what to sort on? Like which node to use, sorting by value, sorting by tag (if using InfluxDB).

![image](https://cloud.githubusercontent.com/assets/120270/22931551/cf99b8aa-f2a3-11e6-9b8a-c8f76a3e4e22.png)

**Comment by torkelo** [comment]
sorting series is the responsibility of the metric query / time series backend.
