### ISSUE TITLE
[Feature request] Recent time range selection

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7562]
I want to quickly select a time range, recently select in another tab.
The time range is stored in browser side, and show it in date time picker.
This is quite useful when two dashboards are not connected with drill down link.

(Currently, we need to open date time picker twice, and copy from/to value from one tab to another tab)

**Comment by torkelo** [comment]
good idea! question is where/how to show it

**Comment by mtanda** [comment]
At first, I think like following.
1. Store time range automatically, at every time range change, and save recent 5 time range
2. Show recent 5 time range at dashboard time picker (http://docs.grafana.org/reference/timerange/)

But, automatical time range storing might be not intentional in some case.
Copy time range by keyboard shortcut, and Paste it to another dashboard is one of the idea.

Let me consider more, what is the best UI.

**Comment by ivanahuckova** [comment]
+cc @slim-bean you have mentioned this issue as well, so I am giving it an upvote. 🙂

**Comment by dprokop** [comment]
@ivanahuckova @mtanda this one is already solved and the last 5 time range selection(absolute time range) are already persisted:

http://localhost:3000/d/2GpnExoGz/reinitialisation?orgId=1&from=1606694400000&to=1607731199000

**Comment by ivanahuckova** [comment]
@dprokop Sorry, I was focusing mostly on *copy-paste*  time range part. Is there any plan for that? 

Also it seems like the recently-used time ranges are loaded from the local storage when we mount time-range picker button. Do you think it would make sense to change it to when we open a time picker drop down. As that way, we will have up to date ranges. When now, we see only time ranges that were stored when we opened the Explore/Dashbaord. Do you think it makes sense?
