### ISSUE TITLE
[Bug] Multi-value templates with graphite backend gives label which do not allow identification

### ISSUE THREAD

**Issue by dgoetz** [grafana/grafana#7564]
- What Grafana version are you using? v4.1.2
- What datasource are you using? Graphite (with Data from Icinga 2)
- What OS are you running grafana on? Debian 8.7
- What did you do? 
We created a template for the interfaces which allows for selecting of mutli-values and used this also in the alias of the metric.
![image](https://cloud.githubusercontent.com/assets/3658213/22940925/d3f417c0-f2e3-11e6-8e49-35074c01312f.png)
![image](https://cloud.githubusercontent.com/assets/3658213/22940940/e1a58e9e-f2e3-11e6-8b22-bdba437a2a4c.png)

- What was the expected result?
We wanted to have a nice readable label only showing the interface name matching the metric.

- What happened instead?
We got all selected values included in every label which does not allow to identify the interface at all.
![image](https://cloud.githubusercontent.com/assets/3658213/22940888/b72a312e-f2e3-11e6-8aed-cce1feb192e6.png)

**Comment by torkelo** [comment]
You need to use aliasByNode function if you want to alias by a metric segment/node,

**Comment by dgoetz** [comment]
Thanks, but this only gives me the node and I can not add a prefix/suffix so it also does not allow to identify the metric as I can not see if its traffic inbound or outgoing for the interface or in another example if the metric are discarded or error packages.

**Comment by torkelo** [comment]
you can alias by multiple nodes, aliasByNode(6,8) for example. 

Since $interface variable has multiple values it will be multiple values both in metric path and in aliasBy (variable values are interpolated, and aliasBy is function is handled by Graphite, not Grafana)
