### ISSUE TITLE
[Bug] Grafana 3.1.1 500 internal server error

### ISSUE THREAD

**Issue by vijay2710** [grafana/grafana#7566]
I am having trouble with grafana 3.1.1. It stopped visualising my metrics on the dashboard and it is showing  internal server error 500. `curl http://admin:admin@localhost:3000/api/datasources/proxy/1/api/query -v`
```
* About to connect() to localhost port 3000 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> GET /api/datasources/proxy/1/api/query HTTP/1.1
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.29.0
> Host: localhost:3000
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 14 Feb 2017 18:49:39 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
```
Please include this information:
- What Grafana version are you using?: grafana-3.1.1
- What datasource are you using?: sqlite3
- What OS are you running grafana on?: Linux 3.10.0-327.36.1.el7.x86_64 x86_64
- What did you do? Nothing
- What was the expected result? reply to curl request
- What happened instead? server timeout 500  (Grafana is not visualizing anything on the dashboard)

**Comment by torkelo** [comment]
Is your prometheus server working? Have you looked in the grafana server log?

**Comment by torkelo** [comment]
closing this as you already sent this question in the mailing list
