### ISSUE TITLE
elasticsearch 1.x support removed?

### ISSUE THREAD

**Issue by warroyo** [grafana/grafana#7567]
I just upgraded to version `4.1.2` from `4.0.1` and noticed the `1.x` is removed from the elastic search datasource. I did not see this mentioned in the changelog, was this by accident or will `1.x` no longer be supported?

**Comment by torkelo** [comment]
Yes, it was removed in order to support Elasticsearch 5, should be in the changelog, will add it if it is missing

**Comment by hbeigi** [comment]
We are missing ES 1.x Support. Is it possible to enable ES 1.x in Grafana?

**Comment by marefr** [comment]
@hbeigi #7131
