### ISSUE TITLE
Bug? Grafana graph isn't displaying.

### ISSUE THREAD

**Issue by ItsAlwaysDNS** [grafana/grafana#7570]
What Grafana version are you using? V4.1.1
What datasource are you using? InfluxDB
What OS are you running grafana on? CentOS

This is the only way I'll get a graph to be display completely.
![grafana-todaysofar](https://cloud.githubusercontent.com/assets/24477163/22949585/5e26acf8-f2c8-11e6-968c-c6286770e87b.PNG)

This is what my graph looks like if i select anything less than 12 hours
![grafana-last3hours](https://cloud.githubusercontent.com/assets/24477163/22949596/64c6c6e2-f2c8-11e6-930c-f77decc99133.PNG)

If I click and drag over the whole graph then data shows up.
![grafana-withlast3hourszoomedin](https://cloud.githubusercontent.com/assets/24477163/22949597/666c152e-f2c8-11e6-8254-cb2169abd010.PNG)

If manually change the graph the 9 hours, I get a little bit of data all the way to the right about about 1 hour.

I have this same setup done at work and it works no problem. What could be the issue. I'm not the best with this stuff by all means, just looking for instruction.

Also, this is being pulled from librenms.

**Comment by torkelo** [comment]
Have you checked InfluxDB responses? Open chrome dev tools network tab, look at raw response. 

Maybe you need to set a minimum group by time interval, like >1m
