### ISSUE TITLE
Alerting: Permission denied when edit existing alert - /api/v1/ngalert/alertmanager status=403

### ISSUE THREAD

**Issue by MarcoJ-CID** [grafana/grafana#75714]
### What happened?

![Untitled](https://github.com/grafana/grafana/assets/6771839/abb79aaa-a60a-4614-a3d4-4ed3267456c8)

All users in our Grafana OSS installation with the role Editor got a warning when open the edit page of an alert. This is cause by an API call in the background to the `/ngalert/alertmanager` which responses with a 403. As administrator we don't face this kind of issue. 

In the logs we could see that lot of API calls were generated when editing an alert and only this one results in a 403:
`level=info msg="Request Completed" method=GET path=/api/v1/ngalert/alertmanagers status=403 remote_addr=0.1.2.3 time_ms=0 duration=504.2µs size=32 referer=https://grafana.instance/alerting/alertUid/edit handler=/api/v1/ngalert/alertmanagers`

One of the most important information is that all users are able to edit, update and save the alert. The permission denied is only related to an api call in the background. But this behavior confuses my colleagues a lot. 

### What did you expect to happen?

No errors/warning when I'm able to work with Grafana as expected (view, edit and save). 

### Did this work before?

At least this worked with Version 10.0.3. We got this issue since updating to 10.1.1 and also in 10.1.2 this is occuring.

### How do we reproduce it?

Maybe with running Grafana OSS
1. Login as editor
2. Try to edit an alert

### Environment (with versions)?

Grafana: 10.1.2
OS: Windows
Browser: Chrome/Firefox

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
thank you for creating the issue @MarcoJ-CID 

I have reproduced it in v.10.1.0 as you described

Adding issue to the alerting squad's board for review

**Comment by armandgrillet** [comment]
This is caused by the preview feature that might require more permissions, this is something we should fix.
