### ISSUE TITLE
Navigation: Add 'Dock menu' button to `DockedMegaMenu` and implement docked menu functionality

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#75727]
designs here: https://www.figma.com/proto/FStledDq3ytXssh4PykKf5/Combined-megamenu?page-id=648%3A15218&type=design&node-id=648-15601&t=o2VbXdFceTbxkrhU-0&scaling=min-zoom&starting-point-node-id=648%3A15601

acceptance criteria:
- [ ] there is a "dock menu" button
- [ ] clicking the "dock menu" button displays the megamenu permanently
- [ ] once docked, clicking either the hamburger or "dock menu" button will close the menu

probably need to modify the state in `AppChromeService` to handle whether it's docked or not, either through some new state variable, or by extending `megaMenuOpen` to keep track of all 3 states (open, closed, docked)

we also need to think about responsiveness, but we can defer that to another task 👍

**Comment by eledobleefe** [comment]
I'd love to work on this task 🙂
