### ISSUE TITLE
[Bug] Template variable in metric name causing wrong label for OpenTSDB datasource

### ISSUE THREAD

**Issue by tesseract2048** [grafana/grafana#7572]
- What Grafana version are you using?
latest

- What datasource are you using?
OpenTSDB

- What OS are you running grafana on?
linux 3.16

- What did you do?
Using template variable in metric name for OpenTSDB data source with alias for a multiple time series graph.

- What was the expected result?
Label shows according to each series's alias.

- What happened instead?
All label shows as first alias.

**Comment by torkelo** [comment]
This has been reported many times already (for example, #2687, https://github.com/grafana/grafana/issues/7560)

Due to a limitation in the OpenTSDB query api,
#1876
