### ISSUE TITLE
Navigation: Ensure current page hierarchy is expanded and scrolled into view on page transition

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#75726]
designs here: https://www.figma.com/proto/FStledDq3ytXssh4PykKf5/Combined-megamenu?page-id=648%3A15218&type=design&node-id=648-15699&t=o2VbXdFceTbxkrhU-0&scaling=min-zoom&starting-point-node-id=648%3A15601

acceptance criteria:
- [ ] when the active page changes to a child or grandchild, all parents should be automatically expanded.
- [ ] when the active page changes, the active page should be scrolled into view if needed

**Comment by shaikahmadnawaz** [comment]
I'm not able to see figma file, please give view access @ashharrison90

**Comment by ashharrison90** [comment]
@shaikahmadnawaz this is an internal issue for Grafanistas to work on - if you'd like to contribute look for issues with the 'help wanted' label

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz this is an internal issue for Grafanistas to work on - if you'd like to contribute look for issues with the 'help wanted' label 

Thank you for the update. I'll make sure to check for issues with the 'help wanted' label and see if there's anything I can contribute to. If I have any questions or need guidance, I'll reach out. Thanks again! @ashharrison90
