### ISSUE TITLE
API dashboard export leaks scopedVars and current variable values

### ISSUE THREAD

**Issue by joe-pll** [grafana/grafana#7573]
Running Docker Grafana 4.0.0/4.1.1

Hi,
the dashboard export through the API has the same variable leaks explained in the #6520. The scopedVars and the current value of the vars are in the resulting json.

The problem has been fixed in the UI export.

**Comment by torkelo** [comment]
there is no export api, only export feature right now is accessed through the UI. 

Did you try using the UI export?

**Comment by joe-pll** [comment]
Hi, I get the dashboard via the API to add it, via the API, in another Grafana instance.

**Comment by torkelo** [comment]
you mean the load dashboard api that is used when you load up a dashboard? that is not meant for exports but loading a dashboard by the frontend. We do not have an "export & remove variables"  api yet

**Comment by joe-pll** [comment]
Thank you for your answer, I understand what you are saying.

I meant: download the json of a dashboard via the API from a Grafana instance running on the host A and upload it via the API in another Grafana instance using a different   database, not necessarily on the same host.
