### ISSUE TITLE
[Question/Issue] Error "dashboard not found" despite I have 3 dashboards

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7574]
Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? Prometheus
- What OS are you running grafana on? macOS Sierra
- What did you do? Open localhost:3000 who is my Grafana webpage
- What was the expected result? see my dashboard
- What happened instead? got error "dashboard not found"

I have a question about Grafana because when I go to the webpage it looks like this:
<img width="1340" alt="capture d ecran 2017-02-15 a 12 50 54" src="https://cloud.githubusercontent.com/assets/22610050/22973432/ef15c3c4-f37d-11e6-80e4-daf99a253146.png">
Despite I have 3 dashboards:
<img width="1121" alt="capture d ecran 2017-02-15 a 12 51 01" src="https://cloud.githubusercontent.com/assets/22610050/22973441/f5203dc6-f37d-11e6-8871-5b45473952d2.png">

Is there a settings somewhere to specify the default dashboard ? If it's the case I haven't founded it in `grafana.ini` and in settings. 

Thank you for the help

**Comment by torkelo** [comment]
you can set default dashboard in profile option (but you must star a dashboard for it to be selectable a home dashboard).

How did you start grafana? What is the output from grafana log?

**Comment by JeromeVi** [comment]
It's not the default dashboard that I can set in profile option it's the home dashboard. To start it I made a `docker build` from [Dockprom](https://github.com/stefanprodan/dockprom) and then Grafana is running in a container. 

The logs are full of `request completed`

**Comment by JeromeVi** [comment]
I have found the source of my problem. I was including Grafana via a `<iframe>` and I had a wrong path so now I do` <iframe width="100%" height="1000px" src="http://localhost:3000/"></iframe>` and I have set a home dashboard. Thank you for the help @torkelo
