### ISSUE TITLE
[Bug] Graph is not displayed in Grafana

### ISSUE THREAD

**Issue by ItsAlwaysDNS** [grafana/grafana#7575]
Some moron closed the thread without any chance for a response.

What Grafana version are you using? V4.1.1
What datasource are you using? InfluxDB
What OS are you running grafana on? CentOS

This is the only way I'll get a graph to be display completely.
![grafana-todaysofar](https://cloud.githubusercontent.com/assets/24477163/22975425/5ae9df7c-f34c-11e6-9e6f-ca0fe8cad075.PNG)

This is what my graph looks like if i select anything less than 12 hours
![grafana-last3hours](https://cloud.githubusercontent.com/assets/24477163/22975434/5e738d32-f34c-11e6-9e3a-42dff39fb153.PNG)

If I click and drag over the whole graph then data shows up.
![grafana-withlast3hourszoomedin](https://cloud.githubusercontent.com/assets/24477163/22975443/648dd326-f34c-11e6-87d0-7c8d33380173.PNG)

If manually change the graph the 9 hours, I get a little bit of data all the way to the right about about 1 hour.

I have this same setup done at work and it works no problem. What could be the issue. I'm not the best with this stuff by all means, just looking for instruction.

Also, this is being pulled from librenms.

**Comment by ItsAlwaysDNS** [comment]
Don't close the thread until I get a chance to respond Torkel, especially when its only a couple hours old...

**Comment by JeromeVi** [comment]
So what you said at then end of your post is that if you manually > -12hours from now you can have some data ? But if you use the timepicker >-12hours from now you have no data ?

**Comment by ItsAlwaysDNS** [comment]
If I manually set the graph to last 9 hours I'll get a small amount of data, if i increase it to last 10 i'll get a larger but still incomplete amount of data, and a little bit more while increasing the time upwards. 

If the graph is set anywhere manually or auto from last 1 minutes to last 8 hours I don't have any data displayed on graph.

Although, if i set it to any of those times and click and drag on the graph to zoom in, it shows a complete graph full of data.

**Comment by JeromeVi** [comment]
Can you post your request ? (the request to collect the data from the DB)

**Comment by ItsAlwaysDNS** [comment]
I can, but what concerns me is I have a near similar setup at work. all the same software in use and it works just fine, everything is on the same version.

**Comment by JeromeVi** [comment]
@ItsAlwaysDNS ok, so no sorry I can't find an idea about what the problem could comes from sorry

**Comment by ItsAlwaysDNS** [comment]
No problem, I'm just at a loss right now and have no idea where to look.

**Comment by torkelo** [comment]
@ItsAlwaysDNS why open a new issue ? I closed your last issue because it was missing crucial information that we request in the New Issue template, did you read it? 

From the new issue template:

```
**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
```

Grafana has issues queries to InfluxDB, in InfluxDB does not return data for specific time ranges then it is very likely some configuration option in InfluxDB. 

This is most likely related to a breaking change in InfluxDB 1.2 that is affecting many people, I suggest downgrading to a previous version of InfluxDB until we add support for this version. 

https://github.com/grafana/grafana/issues/7380

**Comment by torkelo** [comment]
sorry for closing your issue so quickly, it is just that we get so many issues every day and without important information (like queries sent and raw response from time series database) we cannot troubleshoot.

**Comment by shubhamod1** [comment]
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.

**Comment by daniellee** [comment]
@shubhamod1 ask this question on the [community site](https://community.grafana.com) instead and include more details, please.

**Comment by bobfaridsh** [comment]
i have installed grafana and data source is successfull added , but no graph comes with any kind of visulization
