### ISSUE TITLE
InfluxDB SQL: Automatically add time filter in queries

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#75754]
Automatically add time filter to the queries based on the selected time range.

i.e.
```sql
SELECT
  temp,
  hum,
  room
FROM home
WHERE
  time >= '2023-03-20T08:00:00Z'
  AND time <= '2023-03-20T20:00:00Z'
```

**Comment by UTKARSHMOHAN2003** [comment]
assign me sir  i can fix this 
DECLARE @StartTime DATETIME = '2023-03-20T08:00:00Z';
DECLARE @EndTime DATETIME = '2023-03-20T20:00:00Z';

SELECT
  temp,
  hum,
  room
FROM home
WHERE
  time >= @StartTime
  AND time <= @EndTime;
