### ISSUE TITLE
[Bug] Grafana not displaying all data

### ISSUE THREAD

**Issue by pzai577** [grafana/grafana#7576]
Please include this information:
- What Grafana version are you using? Grafana 4.1.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Windows
- What did you do? Load data into a graph
- What was the expected result? All of the data is displayed
- What happened instead? Not all of the data is displayed

<img width="1403" alt="screen shot 2017-02-15 at 10 24 31 am" src="https://cloud.githubusercontent.com/assets/20449109/22981837/5f1fd988-f36b-11e6-85ce-8bb8f7521aa2.png">

When I have a graph with 'too much' data, the graph does not display all of it. In this example, line 5 (the red line) does not continue to the end of the graph (if I view the last 24 hours, all 5 lines are visible and complete, so I know the data exists). In another example, I asked for 5 lines, but the 5th one is not displayed and does not even appear in the legend, while the 4th line is incomplete.

Regarding the network request: I am not too familiar with this, but I took a glance at the network request and response. It looked like it returned 5 sets of data, each set of size 720, and each datapoint is a [timestamp, value]. In particular, the 5th set also appears complete (in the network response, not in the graph obviously). I'm not sure if this is relevant.

There appears to be some sort of limit on how much data Grafana is willing to load. If that is the case, does anyone know where this limit comes from? Can I configure it to match my needs? Is there a good workaround that exists?

Thanks! Let me know if you would like any more information.

**Comment by pzai577** [comment]
One note: There is one datapoint per minute. Originally, I did not aggregate the data, so there were more datapoints, and Grafana only loaded 2 of the 5 lines (line 1 completely, and line 2 partially). I then told the graph to "Group by time(auto)" and aggregate as a mean, which brought it to the above state (4 lines load completely, the 5th one partially). I'm not sure how Grafana automatically picks a time for "time(auto)" though, and I would like to know more about that.

**Comment by phemmer** [comment]
Likely dup of #7380

**Comment by pzai577** [comment]
Correct, this is was a dupe of #7380 . Thanks for pointing it out to me! Sorry I didn't find it on my own. Should I close this issue now?

**Comment by torkelo** [comment]
Closing as this has been reported about 10 times already :) we have adding support for InfluxDB 1.2 as a top priority, hopefully this breaking change in InfluxDB can be worked around in the mean time
