### ISSUE TITLE
Cloudwatch Variables values queries don't update when other parameters are changed from the dropdown

### ISSUE THREAD

**Issue by alexmnyc** [grafana/grafana#7577]
First param "env" is declared as a list of "qa,prod"

Second param is declared via a variable values query:

Query: dimension_values(us-east-1, AWS/EC2, CPUUtilization, AutoScalingGroupName)
regex:$env-telemetry.+

When changing env dropdown values, the second param query does not update.

It works on load via query string parameters but not when updated in the UI:

/dashboard/db/sample-dashboard?var-env=prod
/dashboard/db/sample-dashboard?var-env=qa

**Comment by bergquist** [comment]
What version of grafana are you using?

**Comment by alexmnyc** [comment]
Checking this for you.

**Comment by alexmnyc** [comment]
3.1.0

**Comment by torkelo** [comment]
Can you try 4.1? lots of updates to templating engine between 3.1 and 4.1
