### ISSUE TITLE
404 - page not found error on opening grafana/developers /plugin-tools in CONTRIBUTING.md

### ISSUE THREAD

**Issue by harshPareek-git** [grafana/grafana#75788]
### What happened?

<img width="623" alt="Screenshot 2023-10-01 at 9 55 27 AM" src="https://github.com/grafana/grafana/assets/146609296/b8d828df-b633-4918-9acb-fe01c6815da7">
<img width="1428" alt="Screenshot 2023-10-01 at 9 54 15 AM" src="https://github.com/grafana/grafana/assets/146609296/4b9a8d66-9bba-4fa1-9e75-cb49b87dca15">

### What did you expect to happen?

Page should load plugin-tools

### Did this work before?

Yes

### How do we reproduce it?

1. Direct to this URL - https://github.com/grafana/grafana
2. Under the Contributing section, click on Contributing guide
3. Redirect to - **https://github.com/grafana/grafana/blob/HEAD/CONTRIBUTING.md**
4. Head to bottom of the page and under "Where do I go from here" section click on developing plugins.
5. Now, the redirected page shows 404 error.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by Navise** [comment]
@harshPareek-git  I would like to contribute to this issue here , can you assign it to me

**Comment by harshPareek-git** [comment]
@Navise I don't have the privilege to assign

**Comment by sujalcodes3** [comment]
Can we get the URL of the plugins so it can be fixed.
