### ISSUE TITLE
[Feature Request] Templating Select & Custom Variable Replacements

### ISSUE THREAD

**Issue by msfunty** [grafana/grafana#7580]
It would be very useful to have replacement patterns also in the SELECT field working.
Esp. it should be possible to use a template variable and concatenate with a prefix or suffix.

The same goes for variable definition of type "custom". Great value adding feature would be to have string replacement there as well

**Comment by torkelo** [comment]
Not sure I understand, you can use variables everywhere. 

Do you have an example?

**Comment by msfunty** [comment]
Idea is based on a "grouping" data model, where you have measurements for several machines/things in tables like this:
building_floor_thing_measurement
Templating would be based on building, floor and thing.

1. example: var1 is based on a select statement returning item1 and item2.
When templating based on var1 you can only select in tables item1 and item2. I'd like to see string replacement in the select clause not just as alias, e.g. "SELECT ... FROM $var1_crit..." or "SELECT ... from 01_$var1_crit".

2. example: You have a second variable (var2) which should be based on var1, which is used for templating. $var2 = "prefix_$var_suffix".
For 1st item $var2 = "prefix_item1_suffix", 2nd item $var2 = "prefix_item2_suffix". $var could than be used in the select statement giving more flexibility.

I hope now it's more clear :-)

**Comment by torkelo** [comment]
you should be able to do that right now using ``prefix_[[varname]]__[[suffix]]`` interpolation syntax
