### ISSUE TITLE
[Bug] isMsResolutionNeeded: Error on upgrading to Grafana 4.x.x

### ISSUE THREAD

**Issue by abhisant** [grafana/grafana#7581]
- Grafana Version: 4.1.2
- Datasource: Druid
- What did you do? 
Updaraded grafana to 4.1.2, the druid plugin broke and started giving the following errors, although I am getting the response from the Druid backend. 

1. 
TypeError: Cannot read property '1' of null at a.isMsResolutionNeeded
at a.timeSeriesHandler
at Array.map (native)

2. 
TypeError: Cannot read property 'toString' of undefined at a.isMsResolutionNeeded 
at new a
at a.timeSeriesHandler  

 Is there any change from 3.x.x to 4.x.x in the timeseriesHandler that broke the plugin. The release notes however, doesn't mention any change that might break the existing plugins. The plugin was working fine on 3.x.x

- What was the expected result? 
The graphs should plot since I am getting the response form Druid. 
- What happened instead?
Getting the type script errors in some of the cases.

**Comment by bergquist** [comment]
its still available in 4.1.2

https://github.com/grafana/grafana/blob/99f18f9d69993f7033ccd7a38bf14af6fa57b5b0/public/app/core/time_series2.ts

The only change that could affect this is that we upgrades lodash version in 4.0.

**Comment by torkelo** [comment]
You might need an update to the druid plugin

**Comment by torkelo** [comment]
Can you show what the druid plugin query method return ls that is causing the error? We have no other report on plugins with this error, so likely something on common in the return data from the druid datasource plugin

**Comment by abhisant** [comment]
Hi @torkelo 

When I see the traceback, it doesn't lead me in druid plugin source code. Following is the traceback:

Panel data error: TypeError: Cannot read property '1' of null
    at a.isMsResolutionNeeded (localhost:3000/public/app/boot.6d63bd8b.js:21:3558)
    at new a (localhost:3000/public/app/boot.6d63bd8b.js:21:934)
    at a.timeSeriesHandler (localhost:3000/public/app/boot.6d63bd8b.js:18:29092)
    at localhost:3000/public/app/boot.6d63bd8b.js:18:28273
    at Array.map (native)
    at a.getSeriesList (localhost:3000/public/app/boot.6d63bd8b.js:18:28246)
    at b.onDataReceived (localhost:3000/public/app/boot.6d63bd8b.js:19:3247)
    at f.emit (localhost:3000/public/app/boot.6d63bd8b.js:52:2928)
    at a.emit (localhost:3000/public/app/boot.6d63bd8b.js:52:5256)
    at b.handleQueryResult (localhost:3000/public/app/boot.6d63bd8b.js:46:4942


However, I don't see this error in timeseries Druid Query Type, I am seeing this in topN query. I can see the response coming in the network tab, as soon as it tries to process and render the response, it throws this error.

Following is the link the method that does the query type processing:

this._doQuery:
https://github.com/grafana-druid-plugin/druidplugin/blob/master/src/datasource.js#L113

convertTopNData:
https://github.com/grafana-druid-plugin/druidplugin/blob/master/src/datasource.js#L344

**Comment by torkelo** [comment]
so what does the query function return when you get the error? 

I mean the error is in the grafana code, that is a given, but it is due to returning some invalid time series data from the data source plugin. hard to see from the code what your returning. 

> Can you show what the druid plugin query method return ls that is causing the error? We have no other report on plugins with this error, so likely something on common in the return data from the druid datasource plugin

**Comment by abhisant** [comment]
I saw that this.datapoints[i][1] in time_series2.js?bust=1487366777883:215:66 is undefined for topN and groupby query response.

Following is the topN response:
topN response:

[ {
  "timestamp" : "2017-02-17T19:02:00.000Z",
  "result" : [ {
    "cnt" : 1916495,
    "dimensionValue" : null
  }, {
    "cnt" : 703292,
    "dimensionValue" : "200"
  }, {
    "cnt" : 57283,
    "dimensionValue" : "302"
  } ]
}, {
  "timestamp" : "2017-02-17T19:03:00.000Z",
  "result" : [ {
    "cnt" : 1877409,
    "dimensionValue" : null
  }, {
    "cnt" : 690786,
    "dimensionValue" : "200"
  }, {
    "cnt" : 55632,
    "dimensionValue" : "302"
  } ]
}, {
  "timestamp" : "2017-02-17T19:04:00.000Z",
  "result" : [ {
    "cnt" : 404227,
    "dimensionValue" : null
  }, {
    "cnt" : 39442,
    "dimensionValue" : "200"
  }, {
    "cnt" : 6462,
    "dimensionValue" : "304"
  } ]
} ]

==============================================
Following is the GroupBy response:

[ {
  "version" : "v1",
  "timestamp" : "2017-02-17T18:56:00.000Z",
  "event" : {
    "cnt" : 696792,
    "dimensionValue" : "200"
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-02-17T18:57:00.000Z",
  "event" : {
    "cnt" : 706571,
    "dimensionValue" : "200"
  }
} ]

**Comment by torkelo** [comment]
Does not look like a valid response from a datasource query method, should be an array of series with a datapoints array

**Comment by abhisant** [comment]
@torkelo : Nothing has changed in the Grafana datasource w.r.t topN and GroupBy output. It used to work very well since the day plugin was built. 

Just FYI.. Timeseries query type is working fine, it's just an issue with the topN and groupBy.

**Comment by torkelo** [comment]
Strange, maybe grafana 3.1 was more for giving, but can't see how, that response has never been a valid response form a datasource query method, can't imagine Grafana ever accepting / working if a datasource query method returned that.

**Comment by abhisant** [comment]
@torkelo: @knoguchi identified the issue. Please see the commits of pull below:

https://github.com/grafana-druid-plugin/druidplugin/pull/9/commits

I will close the issue once I merge and test it. I will be releasing a new Grafana version soon, once the fix works.
