### ISSUE TITLE
Panel search: scope frontend work

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#75834]
In order to scope the upcoming work to enable panel title search, we need to understand the changes in the API response with the `panelTitleSearchInV1` feature toggle.

Behavior: You can search either dashboards or panels but not at the same time.

Outcome: an epic with a list of tasks required to trigger a panel title search and display panel results. 

Will be implemented by engineering and reviewed by UX.

**Comment by zsofiakm** [comment]
@suntala has been working on the backend, so please approach her if you have questions about the API.

**Comment by L-M-K-B** [comment]
I moved the issue back to Future as the Backend tasks were postponed for now.

**Comment by zsofiakm** [comment]
Closing as this is 6+ months out.
