### ISSUE TITLE
[Issue] Dashboard not found when using API

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7584]
Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? Prometheus
- What OS are you running grafana on? macOS Sierra
- What did you do? I'm sending dashboard to my Grafana webpage via the API 
- What was the expected result? No errors
- What happened instead? Dashboard not found

# Issue

So I'll explain my problem here, I'm sending dashboard using the API. Sometimes I have this error :  
<img width="555" alt="capture d ecran 2017-02-16 a 14 33 07" src="https://cloud.githubusercontent.com/assets/22610050/23023243/dc2b7fa6-f454-11e6-8cc4-38af847aaf5f.png">

And sometimes not. So to see why my JSON was incorrect I copied the JSON when it works and when I have the error with a console.log before sending the data and.... they are 100% the same : 

<img width="1427" alt="capture d ecran 2017-02-16 a 14 34 16" src="https://cloud.githubusercontent.com/assets/22610050/23023277/075c365c-f455-11e6-9832-77154adf2196.png">

I post them here if you want to test or to do something : 
Working: 
```
{ annotations: { list: [] },
description: 'Containers metrics',
editable: true,
gnetId: null,
graphTooltip: 1,
hideControls: false,
id: null,
links: [],
refresh: '1s',
rows:
 [ { collapse: false,
     height: 250,
     title: 'Summary infos of Prometheus',
     panels: [Object],
     showTitle: true,
     titleSize: 'h6' } ],
schemaVersion: 14,
style: 'dark',
tags: [ 'docker' ],
time: { from: 'now-15m', to: 'now' },
timepicker:
{ refresh_intervals: [ '1s', '5s', '10s', '30s', '1m', '5m', '15m', '30m', '1h', '2h', '1d' ],
time_options: [ '5m', '15m', '1h', '6h', '12h', '24h', '2d', '7d', '30d' ] },
timezone: 'browser',
title: 'Docker Containers _custom_from_js',
version: 1 }
```

Error:
```
{ annotations: { list: [] },
description: 'Containers metrics',
editable: true,
gnetId: null,
graphTooltip: 1,
hideControls: false,
id: null,
links: [],
refresh: '1s',
rows:
 [ { collapse: false,
     height: 250,
     title: 'Summary infos of Prometheus',
     panels: [Object],
     showTitle: true,
     titleSize: 'h6' } ],
schemaVersion: 14,
style: 'dark',
tags: [ 'docker' ],
time: { from: 'now-15m', to: 'now' },
timepicker:
{ refresh_intervals: [ '1s', '5s', '10s', '30s', '1m', '5m', '15m', '30m', '1h', '2h', '1d' ],
time_options: [ '5m', '15m', '1h', '6h', '12h', '24h', '2d', '7d', '30d' ] },
timezone: 'browser',
title: 'Docker Containers _custom_from_js',
version: 1 }
```

**Comment by torkelo** [comment]
Can you show more how you call the api, the raw request? Have you looked at the request the UI makes when it saves a dashboard? It uses the same api

**Comment by JeromeVi** [comment]
@torkelo  that's the call: 
```
HTTP.call("POST", "http://localhost:3000/api/dashboards/db", {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json',
                        'Authorization': APIKEY,
                    },
                    data: {
                        dashboard: dataJSON,
                        overwrite: true
                    }
                },
                function(error, result) {
                    if (!error) {
                        console.error("result post " + dataJSON.title + " --------------------OK------------")
                        console.log(result);
                    } else {
                        console.log("error post " + dataJSON.title + "  --------------------KO------------")
                        console.error(error);
                    }
                });
```

**Comment by torkelo** [comment]
And you are sure there is no id property in the dashboard json? That is they only way to get that error

**Comment by JeromeVi** [comment]
@torkelo  no I have set `id:null` as in the doc to avoid errors

**Comment by JeromeVi** [comment]
And yes it's really random, sometimes it works and sometimes it make the error despite it's always the same code...

**Comment by JeromeVi** [comment]
@torkelo could it comes from the fact that I set `"id":null` and `"overwrite":true`  ????

**Comment by torkelo** [comment]
it shouldn't. Very strange. try omitting the id property all together.

**Comment by torkelo** [comment]
do you get this error randomly when you save new dashboads from the  UI?

**Comment by JeromeVi** [comment]
No I get them when I do a Post to the api using JavaScriot.

**Comment by torkelo** [comment]
failing to replicate this here, can you create a small node.js app that replicates the problem?

**Comment by JeromeVi** [comment]
Mhh I'm not sure that I'm able to do that... so I'll try and try some tricks and some debug then if I find the problem I'll come here and tell it

**Comment by torkelo** [comment]
version is the database version for the dashboard instance, how many times it's been updated. Used for write concurrency checks to two users do not overwrite each others changes without knowing about it

**Comment by JeromeVi** [comment]
@torkelo  great now I know what is this field ^^, to correct the error I just try to post my dashboard 3times and in all the case it works so it's perfect
