### ISSUE TITLE
Plugins: Datasource Proxy oauth2 unable to authenticate against api

### ISSUE THREAD

**Issue by oujonny** [grafana/grafana#75858]
### What happened?

We extended the JSON API Datasource plugin and would like to use now the oaut2 token functionality of the data source proxy to authenticate against our API. From the logs, it seems as the datasource-proxy gets a token from the configured oauth2 provider, but then still sends an empty token to the API "Authorization: Bearer  " (so the token var is empty)

logs:
```
2023-10-03 08:45:28 logger=data-proxy-log t=2023-10-03T08:45:28.671598167+02:00 level=info msg="Got new access token" ExpiresOn=2023-10-03T08:45:28.671567333+02:00.
2023-10-03 08:45:28 logger=data-proxy-log t=2023-10-03T08:45:28.671662833+02:00 level=info msg=header header=  --> custom log, clearly visible that the header is not properly set
2023-10-03 08:45:28 logger=data-proxy-log userId=-1 orgId=1 uname= path=/api/datasources/proxy/uid/de47046f-4c3e-4c76-ac5c-76bbaa4bcb97/starlink/v1/applications remote_addr=192.168.65.1 referer=http://localhost:3000/connections/datasources/edit/de47046f-4c3e-4c76-ac5c-76bbaa4bcb97 t=2023-10-03T08:45:28.8773165+02:00 level=info msg="Authentication to data source failed" body="{\"errors\":[{\"code\":9401,\"msg\":\"Unauthorized\"}]}\n" statusCode=401
```
I dived into the grafana code and figured out the problem is clearly in this file: https://github.com/grafana/grafana/blob/main/pkg/api/pluginproxy/token_provider_generic.go (around line 92-106)

#### Approach 1
All the auth parameters get encoded and then added to the HTTP request into the **body** and then the Conent-Type is set to _application/x-www-form-urlencoded_. 

In the [RFC 6748](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2) it says 
> The client MUST authenticate with the authorization server as
   described in [Section 3.2.1](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2.1).

And if I understand the code correctly the client_id and the client_secret are just part of the body, **instead of being sent as basic auth.**

So simply adding client_id & client_secret as basic auth to the request would fix it.

#### Apporach 2
At least our Oauth2 Provider would also support everything in the body but only if the content is valid and the Content-Type is set to _application/json_

### What did you expect to happen?

The authentication to the backend API should work with the configured oauth2.

### Did this work before?

no

### How do we reproduce it?

1. Configure the plugin.json file of the JSON API Datasource plugin like this
```JSON
{
  "type": "datasource",
  "name": JSON Datasource",
  ...
  "routes": [
    {
      "path": "exmple",
      "url": "https://example.com",
      "tokenAuth": {
        "url": "<token URL>",
        "params": {
          "grant_type": "client_credentials",
          "client_id": "<client id>",
          "client_secret": "<client secret>"
        }
      }
    }
  ]
  ...
}
```
3. build the plugin with `yarn build` and install the plugin.
4. Test the plugin against an oauth2 secured API.

### Is the bug inside a dashboard panel?

 no

### Environment (with versions)?

Grafana: 10.2.0-pre
OS: docker image (linux/amd64)

### Grafana platform?

Docker

### Datasource(s)?

JSON API

**Comment by oujonny** [comment]
I was able to fix the issue by adding this one one to the source code:

File: https://github.com/grafana/grafana/blob/main/pkg/api/pluginproxy/token_provider_generic.go
```
  97   │     getTokenReq, err := http.NewRequest("POST", tokenUrl, bytes.NewBufferString(params.Encode()))
  98   │     if err != nil {
  99   │         return "", err
 100   │     }
 101 + │ 
 102 + │     getTokenReq.SetBasicAuth(provider.authParams.Params["client_id"], provider.authParams.Params["client_secret"])
 103 + │ 
 104   │     getTokenReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
 105   │     getTokenReq.Header.Set("Content-Length", strconv.Itoa(len(params.Encode())))

```

**Comment by Stefan-Mihail** [comment]
[oujonny](https://github.com/oujonny) could you please share the plugin somewhere here 
both the frontend and the backend part please

**Comment by tolzhabayev** [comment]
Closing as stale
