### ISSUE TITLE
[Question] filter/search Tags attribute in ec2_instance_attribute

### ISSUE THREAD

**Issue by Eduard3000** [grafana/grafana#7585]
Hi Guys,

thanks for grafana, I would like to subquery the Tags attribute inside ec2_instance_attribute.

ec2_instance_attribute(eu-central-1, Tags, {"instance-id": ["$instanceid"]})

gives me keys & values for that instance, but I would like to subquery/filter the Tags 
(we add Tags with Key = Name with Value = Uniq Name to identify instances more easily)

Is there a way of subquery the Tags Attribute?

Regards,
Eduard

Please include this information:
- What Grafana version are you using? > grafana-4.1.2
- What datasource are you using? > CloudWatch
- What OS are you running grafana on? > 4.4.0-62-generic #83-Ubuntu
- What did you do? > Trying to show Value of Tag Key Name
- What was the expected result? Show Value of Specific Tag Key
- What happened instead? No Docs about Queriing Tags

**Comment by torkelo** [comment]
please use mailing list for questions
