### ISSUE TITLE
Alerting: POST /api/admin/provisioning/alerting/reload return 500

### ISSUE THREAD

**Issue by sasha-sup** [grafana/grafana#75877]
### What happened?

I use alert file provisioning. In my case, if I don't change the provisioning yaml files and make an API call `POST /api/admin/provisioning/alerting/reload ` server returns a 500 error. I am not sure if this is the correct response, as there is no error, maybe the response to this request should be reconsidered.

### What did you expect to happen?

I expected something like code 200, no changes.

### Did this work before?

I guess no?

### How do we reproduce it?

Without changing the provisioning files, make a api request
```
curl -u 'admin:admin' -X POST 'http://localhost:3000/api/admin/provisioning/alerting/reload'
{"message":"Internal Server Error","traceID":""}
```
The log will show an error message
```
logger=provisioning.alerting t=2023-10-03T10:59:56.825356355Z level=info msg="starting to provision alerting"
logger=context userId=1 orgId=1 uname=admin t=2023-10-03T10:59:56.832166768Z level=error msg= error="alert rules: failed to create new rule versions: UNIQUE constraint failed: alert_rule_version.rule_org_id, alert_rule_version.rule_uid, alert_rule_version.version" remote_addr=127.0.0.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-10-03T10:59:56.83220866Z level=error msg="Request Completed" method=POST path=/api/admin/provisioning/alerting/reload status=500 remote_addr=127.0.0.1 time_ms=28 duration=28.420983ms size=48 referer= handler=/api/admin/provisioning/alerting/reload
```

### Environment (with versions)?

Grafana: 10.0.3
OS: [Official Docker image](https://hub.docker.com/layers/grafana/grafana/10.0.3/images/sha256-da34adacd374f6a4d539669a8d5dbda781aa004d429b2058aba9434a9224a04b?context=explore)

### Grafana platform?

Docker

**Comment by nkol** [comment]
is it possible that this API is moved out of the **admin group** apis to somewhere else where we can use token bearer not basic auth in order to use this API?

Basic auth is disabled for us due to security reasons and then we are not able to use RELOAD api for alerts and this is needed one for implementing GitOps and persisting the alerts since without reload api we need to restart grafana everytime we edit alerts which is not a good use case for production use
