### ISSUE TITLE
Lower limit time interval not working with InfluxDB

### ISSUE THREAD

**Issue by coquebg** [grafana/grafana#7587]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
grafana-4.1.2-1486989747.x86_64
- What datasource are you using?
influxdb-1.2.0-1.x86_64
- What OS are you running grafana on?
CentOS Linux release 7.3.1611 (Core)
- What did you do?
Created a simple chart, showing cpu usage
`SELECT mean("usage_idle") FROM "cpu" WHERE "cpu" = 'cpu-total' AND $timeFilter GROUP BY time($interval), "host" fill(null)`
Set a low limit for time interval >10s
![grafana_timeinterval_limit](https://cloud.githubusercontent.com/assets/12639094/23028033/d50ee3e2-f46e-11e6-883b-647f972778cf.PNG)
- What was the expected result?
To show a corresponding graph
- What happened instead?
The request sent to InfluxDB is not correct
`SELECT 100 - mean("usage_idle") FROM "cpu" WHERE "cpu" = 'cpu-total' AND time > now() - 15m GROUP BY time(>10s), "host" fill(null)
`
It includes time(>10s), which is not appropriate for InfluxQL

InfluxDB responds with error
`
{
  "error": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 107",
  "message": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 107"
}
`

**Comment by torkelo** [comment]
Strange, can try to remove the query and readd it? Must be something old in the query model

**Comment by coquebg** [comment]
It is repetitive.
The problem appears after you save the dashboard and reload it. Doesn't matter whether you add new or edit existing chart.

**Comment by torkelo** [comment]
ah, sorry though this was fixed in 4.1 , but it was actually fixe in 4.2 (master), you could try a nightly build from master. 

https://github.com/grafana/grafana/issues/6765
