### ISSUE TITLE
Authorization: Loosing editor access if logging in incognito mode or doing logout and login again

### ISSUE THREAD

**Issue by jagyas** [grafana/grafana#75884]
### What happened?

We are using Okta as oauth provider and we are using generic_oauth for grafana authentication from Okta. We have upgraded our grafana from 9.3 to 10.1.0 and found that our authentication was broken. We fixed it by add below config values:
[auth]
oauth_allow_insecure_email_lookup = true

[auth.generic_oauth]
skip_org_role_sync = true

Now the problem is when we are assigning grafana editor access to anyone in the team, that person is loosing editor access if he or she is doing logout and login again or logging in incognito mode of chrome.

### What did you expect to happen?

Editor access should not be removed automatically if we are trying to login in incognito mode of chrome or doing logout and  login again.

### Did this work before?

Yes

### How do we reproduce it?

1. Enable generic_oauth and auhenticate grafana with Okta
2. Add properties suggested in #74154 to fix oauth breaking change
3. Assign editor access to anyone.
4. Try to login in incognito mode of chrome. You will find that editor access is lost.
5. In your main chrome window if you will try to logout and login again still you will loose editor access

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.0
OS: Docker image (Linux)
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch

**Comment by kalleep** [comment]
Hey, yes this was a known issue on 10.1.0 but have been patched in a later version. Can you upgrade to either latest 10.1.x version or latest 10.2.x?
