### ISSUE TITLE
Alerting: Math functions do not function with more than two conditionals

### ISSUE THREAD

**Issue by evan-chaney** [grafana/grafana#75889]
### What happened?

This is really a follow-up to the solution provided in #72609 which does not work. 
To replicate do something like this in an alert:

- Have 6 queries from different data sources with the same type (in my case it is 6 InfluxDB data sources), named A-F
- Create a reduce function for reach query, it doesn't matter which reduce method you use, named AR-FR
- Create a math function with `${AR} > 100 || ${BR} > 100 || ${CR} >100 || ${DR} > 100 || ${ER} > 100 || ${FR} > 100`

When you click the preview button it won't show the alert instances like it does with one or two term math functions. It never triggers an alert.

### What did you expect to happen?

I expected it to work as was described in #72609

### Did this work before?

The same functionality worked with classic functions in 6.X.

### How do we reproduce it?

(Copy-pasted from above)
1. Have 6 queries from different data sources with the same type (in my case it is 6 InfluxDB data sources), named A-F
2. Create a reduce function for reach query, it doesn't matter which reduce method you use, named AR-FR
3. Create a math function with `${AR} > 100 || ${BR} > 100 || ${CR} >100 || ${DR} > 100 || ${ER} > 100 || ${FR} > 100`

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Grafana: 9.5.1
OS: CentOS 7
Browser: Chrome 117.0.5938.92

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by shwethabm** [comment]
Can I pick this up?

**Comment by evan-chaney** [comment]
@shwethabm Please do!

**Comment by grobinson-grafana** [comment]
I'm going to keep both this and #72609 open, as I see these as different issues. #72609 is related to supporting multiple inputs for Threshold expressions, and this issue is about Math expressions not working with disjoint label sets.

**Comment by bmgante** [comment]
Got the same issue, In my case i have 2 loki queries A and B from different loki datasources. Then, i create a reduce last, strict for each previous query, named C and D.
At then end i do a math E with expression ${C}>0 || ${D}>0. However, when only one of C or D has values E returns but if both C and D have values, E returns no data.
