### ISSUE TITLE
[Bug] Bars with lower value are covered up by bars with higher value

### ISSUE THREAD

**Issue by jasonmclose** [grafana/grafana#7590]
When graphing values via a bar graph, the smaller values are overwritten by the larger values when graphing multiple queries.  What I would expect to happen in this situation is that the smaller value is always pushed to the front, so that its graph/value could always be seen.  At the moment, it depends on the order of the query.

Using:
 - Grafana v4.1.2
 - InfluxDB
 - Running on Ubuntu 16.04
 - Graphed using multiple queries and InfluxDB as the DataSource.
 - Expect to see all bars, with lesser values pushed to the front
 - Some bars are covered up.

See attached screenshots.  The top screenshot shows both queries, while the bottom shows just one.  You can see how the orange bars in the top graph are completely covering up some of the values in the bottom graph, because the value is greater.  In those cases, I would expect those bars to be pushed to the back, so that the green bar can sit in front (like in the graph where the green value exceeds the orange).
![screen shot 2017-02-16 at 10 36 23 am](https://cloud.githubusercontent.com/assets/427384/23031281/09d0a9aa-f436-11e6-8168-4735588aa8d9.png)
![screen shot 2017-02-16 at 10 36 34 am](https://cloud.githubusercontent.com/assets/427384/23031282/09d321b2-f436-11e6-9447-a44cef457cdf.png)

**Comment by torkelo** [comment]
You need to enable stacking if you want to make sure multiple series and all bars are visible, the order each series is draw is determined by the order they are returned by query (or overrides by z-index style override)
