### ISSUE TITLE
Different behavior when importing dashboards from UI vs API 

### ISSUE THREAD

**Issue by MathieuMailhos** [grafana/grafana#7592]
Hello,

I am having different behaviors when trying to import a dashboard into Grafana depending on the "entry door": API vs UI.

A template from Grafana Dashboards library can be imported from the UI but couldn't from the API.

**Reproducing the error**

One example of source: https://grafana.net/api/dashboards/718/revisions/1/download
Importing from the UI is perfectly fine.

<img width="741" alt="screen shot 2017-02-16 at 18 28 20" src="https://cloud.githubusercontent.com/assets/5645869/23032746/cdae0dba-f475-11e6-9ca4-3938a0f607af.png">

Importing using the HTTP API doesn't go as well

```
 curl -vvv http://<username>:<password>@127.0.0.1:9092/api/dashboards/db -X POST  -d @node_exporter_template.json  -H 'Content-Type: application/json'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9092 (#0)
* Server auth using Basic with user '<username>'
> POST /api/dashboards/db HTTP/1.1
> Authorization: Basic sometoken=
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:9092
> Accept: */*
> Content-Type: application/json
> Content-Length: 9225
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 422 Unprocessable Entity
< Content-Type: application/json; charset=utf-8
< Date: Thu, 16 Feb 2017 17:18:49 GMT
< Content-Length: 84
* HTTP error before end of send, stop sending
<
* Closing connection 0
[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]
```

It should not come from my curl command since importing a basic template such as this one is fine:

```
{
    "dashboard": {
        "id": null,
        "title": "New dashboard",
        "originalTitle": "New dashboard",
        "timezone": "browser",
        "rows": [
            {
                "collapse": false,
                "editable": true,
                "height": "250px",
                "panels": [],
                "title": "Row"
            }
        ],
        "schemaVersion": 6,
        "version": 0
    }
}
```

`{"slug":"new-dashboard","status":"success","version":0}`

I am using the latest version of Grafana: v4.1.2 .

Thanks a lot

**Comment by torkelo** [comment]
if you need to import a dashbord using api you should use the import api. 

Sadly this import api is missing from the API docs (will try to add shortly)
When using the UI import feature, open chrome dev tools network tab and look at the api request grafana makes when doing the final import step.

**Comment by MathieuMailhos** [comment]
Thanks a lot. However I suggest not closing the ticket yet.

The import is a POST request on: `grafana/api/dashboards/import`.
However here is the result:

```
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 17 Feb 2017 16:29:57 GMT
< Content-Length: 760
* HTTP error before end of send, stop sending
<
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>Grafana - Error</title>
		<link href='/grafana/public/css/fonts.min.css' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="/grafana/public/css/grafana.dark.min.b4255f90.css">
    <link rel="icon" type="image/png" href="/grafana/public/img/fav32.png">
		<base href="/grafana/" />
  </head>
	<body>
		<div class="page-container">
			<div class="page-header">
				<h1>
					Server side error :(
				</h1>
			</div>
			<h4>runtime error: invalid memory address or nil pointer dereference</h4>
			<pre></pre>
		</div>
	</body>
</html>
* Closing connection 0
```

I noticed that the Payload is modified on the UI.
A wrapper is added onto the body called `dashboard: {}`.

I think it would be nice to be able to import directly the templates from the community without having to modify them on the fly.

**Comment by torkelo** [comment]
Well you need to as the import requires you to pick datasource

**Comment by MathieuMailhos** [comment]
Got it! Thanks :)

**Comment by ttstarck** [comment]
Is the dashboard import api endpoint ever going to be documented?
