### ISSUE TITLE
[Feature request]: Add template variables to dashboard list

### ISSUE THREAD

**Issue by sia-s** [grafana/grafana#7595]
It would be nice if the dashboard list could send template variables to target dashboards. For example I have a "service" template variable. On the same dashboard I have a dashboard list with following items:
- Performance Metrics
- Response times
- Cache access

I want the value of the "service" variable to be sent to dashboards above when I click on them.

**Comment by torkelo** [comment]
Not sure i understand what you mean. You want the dashboard search to let you pick template variables before opening the dashboard?

**Comment by torkelo** [comment]
closing due to lack of updates

**Comment by scarabus** [comment]
I'm looking for a similar feature. 
Assume that I have a top-level dashboard that includes a dashboard list. 
In my top-level dashboard I can set a Time range. I also have a number of variables defined that I can select.

If I select one of the dashboards in the list then when it is opened I want to have the option to pass in the time range and the values of the variables that were set.
