### ISSUE TITLE
[Bug] Single Metric exact value difference visuals

### ISSUE THREAD

**Issue by uniquoo** [grafana/grafana#7596]
Using Grafana 4.1.1 i'm having the issue when i set the color-codes to 55-85 and a digit is exactly at the border to the next "color", the bar shows another color than the value.
![error](https://cloud.githubusercontent.com/assets/970999/23046234/b99429da-f4a8-11e6-906d-a62cce7b1578.PNG)

**Comment by uniquoo** [comment]
Here is a snapshot (7 days accessible):

https://snapshot.raintank.io/dashboard/snapshot/125NxmI3XpgUy8o0KJieigVHiLtP7YAC

**Comment by torkelo** [comment]
Thanks for reporting this issue and helping out making Grafana better.  

Will close however as this has already been reported:  https://github.com/grafana/grafana/issues/5515
