### ISSUE TITLE
Azure Monitor: Find a work around for core config

### ISSUE THREAD

**Issue by bossinc** [grafana/grafana#75966]
public/app/plugins/datasource/azuremonitor/components/ConfigEditor.tsx imports `app/core/config` for `config.secureSocksDSProxyEnabled`. We need a different solution when we externalize Azure Monitor.

@stephaniehingtgen said It is still disabled by default, and it actually will continue to be disabled by default on OSS. It'll only be enabled by default in cloud

**Comment by aangelisc** [comment]
This has been resolved as the property is now available in the `config` exported by `@grafana/runtime`
