### ISSUE TITLE
[Bug] Graphs with alerts stop working when group by time interval set

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#7597]
- What Grafana version are you using?
4.1.1

- What datasource are you using?
InfluxDB 1.2

- What OS are you running grafana on?
Windows

- What did you do?
Set up 3 graphs with an alert. For each graph I also set up a group by time interval set to ">=10s"

- What happened instead?
At a random time in the future I will log back into the dashboard and the graphs will have no data and will be alerting. They seem to be trying to group by >=10s which is not a valid query. What's weird is that this works for a few days before it breaks.

- Reproduction
I tried setting this up again with one of the graphs set with no time interval and the others set to the >=10s interval. The >=10s interval graphs broke once again whereas the one with no interval is still working.

Query:
SELECT mean("Free_Megabytes") FROM "win_disk" WHERE "instance" = 'E:' AND time > 1487235173142ms and time < 1487238773142ms GROUP BY time(>=10s) fill(none)

Error Message:
  "error": "error parsing query: found >=, expected identifier, string, number, bool at line 1, char 139",
  "message": "error parsing query: found >=, expected identifier, string, number, bool at line 1, char 139"

<img width="717" alt="screen shot 2017-02-16 at 5 53 43 pm" src="https://cloud.githubusercontent.com/assets/572187/23046721/eac45648-f470-11e6-858d-3e11e1330668.png">

<img width="672" alt="screen shot 2017-02-16 at 5 57 32 pm" src="https://cloud.githubusercontent.com/assets/572187/23046868/b31fb722-f471-11e6-992b-0376b68d2226.png">

**Comment by torkelo** [comment]
This is fixed in master and latest 4.2 builds (try nightly build)
#6765
