### ISSUE TITLE
[Bug] 4.0.2 to 4.1.2 request mistakenly cancelled 

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#7598]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
I try 4.0.2, 4.1.2, this bug exists
- What datasource are you using?
graphite
- What OS are you running grafana on?
debian wheezy
- What did you do?
Open a dashboard
- What was the expected result?
panel graph showing
- What happened instead?
all panel except one are now showing

I see a lot of request cancelled: 
![image](https://cloud.githubusercontent.com/assets/2576762/23051872/6d9fd95c-f507-11e6-80b2-0abd7a4ed206.png)

There are some points about the `Panel request cancelled` Object:
* target is not equal.
* requestId are all equal to `graphite.panelId.6`

The dashboard has one row and many panels. When open the dashboard, only one panel is showing, and the others are spinning, and all metric request except one succeeds, the other just cancelled, above is the cancelling object.

**Comment by torkelo** [comment]
how did you create this dashboard? multiple panels with same panelId should not be possible, unless maybe it is created through a script or via API.

**Comment by liyichao** [comment]
Mannually, may be created before 4.0.2

**Comment by torkelo** [comment]
and by manually you mean through json editor or through UI? should be impossible to get same panel id if you add panels from UI
