### ISSUE TITLE
Auth: Google SSO not working for new users

### ISSUE THREAD

**Issue by Danial968** [grafana/grafana#76003]
### What happened?

In 10.0 and 10.1. There seems to be a bug not allowing users that were invited to be able to use Google SSO. The users will get "Login failed, Sign up is disabled". This is after creating an account that was sent via email.

### What did you expect to happen?

The user should be able to login with Google SSO even after they have created an account with username/password as according to this: https://github.com/grafana/grafana/issues/16363 and past experience.

### Did this work before?

Worked before in version v9.5.2 and lower

### How do we reproduce it?

1. Upgrade to version 10.0 or 10.1.1
2. Send a user invite to a user.
3. Get user to sign up via email and create a password.
4. Once they have created an account, user should try to use google SSO to login.

### Environment (with versions)?

Grafana: 10.0 and above
OS: 
Browser: Google Chrome

### Grafana platform?

Kubernetes

**Comment by oldgiova** [comment]
Same issue here. Adding few logs:

```
logger=context userId=0 orgId=0 uname= t=2023-10-09T19:35:35.844508948Z level=info msg="Request Completed" method=GET path=/login/google status=302 remote_addr=**** time_ms=0 duration=222.121µs size=550 referer=https://**** handler=/login/:name
logger=user.sync t=2023-10-09T19:35:39.650415966Z level=warn msg="Failed to create user, signup is not allowed for module" auth_module=oauth_google auth_id=****
logger=authn.service t=2023-10-09T19:35:39.650667848Z level=warn msg="Failed to run post auth hook" client=auth.client.google id= error="[user.sync.signup-disabled] system administrator has disabled signup"
logger=context userId=0 orgId=0 uname= t=2023-10-09T19:35:39.660700489Z level=info msg="Request Completed" method=GET path=/login/google status=302 remote_addr=172.30.1.195 time_ms=113 duration=113.247812ms size=29 referer=https://accounts.google.com/ handler=/login/:name
```

**Comment by jirikralik** [comment]
I am using version 10.0.3, we are able to sign in to Grafana but unable to login (user already exist). Anybody encountered this issue?

**Comment by kalleep** [comment]
This is happening because grafana blocks linking an external provider to already existing users by default. Seems like you are creating a user with email / password and then after try to link that user using google sso.

You can read the reason for this braking change here https://github.com/grafana/grafana/issues/70203#issuecomment-1603895013.

You have two options:

1. Enable allow_signup for google sso and let that be the way to populate users

2. If you are using google as a social login and don't wan't to enable allow_signup you use:
```
[auth]
oauth_allow_insecure_email_lookup=true
```
to get back the previous behavior.

Let me know if this resolves you issue

**Comment by Danial968** [comment]
> This is happening because grafana blocks linking an external provider to already existing users by default. Seems like you are creating a user with email / password and then after try to link that user using google sso.
> 
> You can read the reason for this braking change here [#70203 (comment)](https://github.com/grafana/grafana/issues/70203#issuecomment-1603895013).
> 
> You have two options:
> 
> 1. Enable allow_signup for google sso and let that be the way to populate users
> 2. If you are using google as a social login and don't wan't to enable allow_signup you use:
> 
> ```
> [auth]
> oauth_allow_insecure_email_lookup=true
> ```
> 
> to get back the previous behavior.
> 
> Let me know if this resolves you issue
