### ISSUE TITLE
[Vendor] Consider upgrade Macaron

### ISSUE THREAD

**Issue by Unknwon** [grafana/grafana#7600]
Hi, thanks for the great project!

Not sure if you're desired or think it doesn't matter very much in practice:

Macaron recently made a change to [`(*macaron.Context).SetSuperSecureCookie`](https://github.com/go-macaron/macaron/blob/master/context.go#L421-L429) which replaces old MD5 and starting using PBKDF2.

For side effects, from 0.8 to latest tag (1.2.1) shouldn't have API break, but not certain about some behavior changes than you would expect currently.

And if you guys decided to upgrade Macaron (and its dependencies), the parameter pass into the method should not be MD5-encoded anymore as it increases collisions, see example [here](https://github.com/gogits/gogs/blob/master/routers/user/auth.go#L127) and it's a simple change.

**Comment by torkelo** [comment]
Hi, thanks for all your great go libs & projects! 

yea, we should really upgrade Macaron asap.

**Comment by Unknwon** [comment]
Good to know! Ping me if you have any questions or run into any problems.

**Comment by bergquist** [comment]
@Unknwon thank you for all great libs! :)

I think we should get this into master ASAP after we branch of master to 4.2.0

**Comment by torkelo** [comment]
upgraded! 

https://github.com/grafana/grafana/commit/4720216e5ea085b3291c02c83aa81037c69cac9f
