### ISSUE TITLE
Remove the video from the `Get started` subpage of `Alerting` page

### ISSUE THREAD

**Issue by dhalachliyski** [grafana/grafana#76020]
Remove the video from the `Get started` subpage of `Alerting page`.
`How it works panel` should occupy 3 columns, `Get started` panel should occupy 2 columns

<img width="1279" alt="image" src="https://github.com/grafana/grafana/assets/119334180/4e0bf65a-9763-466d-9ef6-21056e603c1d">

**Comment by kheuser** [comment]
Hey Team,

Could you assign this one to me please?

**Comment by tomratcliffe** [comment]
Hi, FYI I've assigned this to me, PR will be coming soon
