### ISSUE TITLE
[Question] How to get meaningful logs / "Datapoints outside time range"

### ISSUE THREAD

**Issue by Marek77** [grafana/grafana#7604]
Hello,

I'm trying to write a datasource (directly accessing rrdtool's cache daemon rrdcached) using simplejson as a starting point. I'm struggling with getting the metrics displayed in a graph, as I'm only getting "Datapoints outside time range" message in the graph and nothing at all in /var/log/grafana.log

I have a graph displayed OK when using Graphite datasource *pointing to the same target*.

Please include this information:
- What Grafana version are you using?
4.1.1

- What datasource are you using?
custom, written in Python, using simplejson

- What OS are you running grafana on?
RHEL 7.2 x86_64

- What did you do?
Two graphs with the same target, one via Graphite datasource, the other via simplejson datasource 

- What was the expected result?
Two graphs

- What happened instead?
"Datapoints outside time range" with simplejson datasource

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query

simplejson:
![snapshot78](https://cloud.githubusercontent.com/assets/5499488/23070529/a0704974-f52b-11e6-8b8a-080b7e50cb95.jpeg)

Graphite:
![snapshot79](https://cloud.githubusercontent.com/assets/5499488/23070545/b41cd5f0-f52b-11e6-842e-1e214889d802.jpeg)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

(captured using wireshark)

Graphite / request:
```
POST /render HTTP/1.1
Host: 192.168.122.7:80
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Content-Length: 151
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Content-Type: application/x-www-form-urlencoded
Dnt: 1
Referer: http://192.168.122.8:3000/dashboard/db/devel-dash?from=1487341740000&to=1487341800000&panelId=1&fullscreen&edit
X-Forwarded-For: 192.168.122.1

target=%2Fibms%2Fnode%2Frio0%2Fhca2%2Fchip1%2Fport1%2Fdata.rrd%2Fxmit_data&from=1487341740&until=1487341800&format=json&maxDataPoints=1639
```
Graphite / response:
```
HTTP/1.1 200 OK
Date: Fri, 17 Feb 2017 15:07:58 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/3.4 Python/2.7.5
Content-Length: 186
Content-Encoding: gzip
Expires: Fri, 17 Feb 2017 15:08:59 GMT
Vary: Accept-Encoding
Last-Modified: Fri, 17 Feb 2017 15:07:59 GMT
Cache-Control: max-age=60
Content-Type: application/json

[{"target": "192.168.122.1:42216.node.rio0.hca2.chip1.port1.data.xmit_data", "datapoints": [[485634.46153846156, 1487341740], [455115.32307692314, 1487341750], [488259.6923076922, 1487341760], [488259.6923076922, 1487341770], [467472.73846153845, 1487341780], [472774.15384615376, 1487341790]]}]
```

simplejson / request:
```
POST /query HTTP/1.1
Host: 192.168.122.1:8082
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Content-Length: 421
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Content-Type: application/json
Dnt: 1
Referer: http://192.168.122.8:3000/dashboard/db/devel-dash?from=1487341740000&to=1487341800000&panelId=1&fullscreen&edit
X-Forwarded-For: 192.168.122.1

{"panelId":1,"range":{"from":"2017-02-17T14:29:00.000Z","to":"2017-02-17T14:30:00.000Z","raw":{"from":"2017-02-17T14:29:00.000Z","to":"2017-02-17T14:30:00.000Z"}},"rangeRaw":{"from":"2017-02-17T14:29:00.000Z","to":"2017-02-17T14:30:00.000Z"},"interval":"50ms","intervalMs":50,"targets":[{"target":"/ibms/node/rio0/hca2/chip1/port1/data.rrd/xmit_data","refId":"A","type":"timeserie"}],"format":"json","maxDataPoints":1639}
```

simplejson / response:
```
HTTP/1.0 200 OK
Server: BaseHTTP/0.3 Python/2.7.13
Date: Fri, 17 Feb 2017 14:56:57 GMT
Content-length: 281
content-type: application/json

[{"target": "/ibms/node/rio0/hca2/chip1/port1/data.rrd/xmit_data", "datapoints": [[509822.0307692308, 1487341740], [477018.8307692308, 1487341750], [477018.8307692308, 1487341760], [473773.2923076922, 1487341770], [426683.0769230769, 1487341780], [485155.9384615385, 1487341790]]}]
```

The timestamps in both Graphite and simplejson are identical, so it's really not clear why "Datapoints outside time range" ??? There is absolutely nothing usefull in /var/log/grafana.log in spite of 

```
[log]
level = trace
```

How can I determine what is the problem?

**Comment by torkelo** [comment]
The json-datasource expects data to be returned in epoch milliseconds not seconds (so its a bit different from the Graphite response)
