### ISSUE TITLE
Multiple Series Error on Single stat with template

### ISSUE THREAD

**Issue by rpelissi** [grafana/grafana#7606]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.1.2
- What datasource are you using?
Zabbix (using grafana plugins)
- What OS are you running grafana on?
RHEL 7.2
- What did you do?
Trying to have multiple singlestat for all %free space on mount points
- What was the expected result?
Multiple Series Error error
- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

Hi,
I am playing with grafana and wanted to have some singlestat showing the % of free space on the different filesystem used on a host. So I created a varaible called "mounts" with:
Query: *.$host.Filesystems.*
RegExp: /Used disk space on (.*)/

I see in the preview the different value (ALL, /opt/, /boot/ home etc)
If I create a singlestat box with the /$mount/ value for item and stat=avg, I got a N/A value and the error Multiple Series Error.

Can you help?

Thanks!

**Comment by torkelo** [comment]
Hi! 

I hope to be able to help you. 

Singlestat panel only supports queries that return a single series. Your query seems return multiple. 

If you think something is wrong in Grafana please look at raw query grafana sends and the raw response

**Comment by siddharth-gitrepo** [comment]
If it is to display singlestat value from all the labels, sum() function could be used.
