### ISSUE TITLE
[Feature Request] Client side transformations

### ISSUE THREAD

**Issue by fzakaria** [grafana/grafana#7608]
I noticed there is a inverse (y * -1), it might be useful to put other transforms in the series override such as: add, subtract, multiply, divide (fixed values or potentially another series).

I think it would fit nicely in the series override next to the inverse already.

**Comment by torkelo** [comment]
that is only display transformation, the value in tooltips and legend are still the same. 

For actual data transformations Grafana relies on the capabilities of the query language of the time series database you use. For example Graphite can do mostly everything when it comes to chaining different transforms. Some TSDBs are however not as capable so Grafana will provide some query transforms via this proposed feature, https://github.com/grafana/grafana/issues/3677
