### ISSUE TITLE
Geomap: geojson styling

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#76083]
**Why is this needed**:

Styling of geojson boundaries

**What would you like to be added**:

ability to use css styles in geojson

**Who is this feature for?**

The World! ;)

I notice this specification for some mapping utilities, not sure if this feature is available in geomap?

https://wiki.openstreetmap.org/wiki/Geojson_CSS

```
{ 
    "type": "Feature",
    "geometry": {
    "type": "Polygon",
    "coordinates": [[
        [-180.0, 10.0], [20.0, 90.0], [180.0, -5.0], [-30.0, -90.0]
        ]]
    },
    "style": {
        "__comment": "all SVG styles allowed",
        "fill":"red",
        "stroke-width":"3",
        "fill-opacity":0.6
    },
    "className": {
        "baseVal":"A class name"
    }
}
```

**Comment by Alex9779** [comment]
I'd really love to see the option to change the the whole style of feature in a GeoJSON and not only the color and opacity.
https://geojson.io/ offers the ability to add "simplestyle" properties.
A configurable mapping of a propertiy to a style property like color, stroke width, ... would be awsome.
But also a much simpler implementation of doing this by fixed rules would be much appreciated...

**Comment by yosiasz** [comment]
This is beatiful!
![image](https://github.com/grafana/grafana/assets/900951/d5137f8c-798d-44bd-b7e7-b48f25dd7580)

But if I have 10K things I would rather not configure e a c h & e v e r y - o n e - o f - t h e m

manually, could be more scalable if it picked this up from the geojson styling settings itself.
