### ISSUE TITLE
Can't install grafana plugins (or find where the plugins folder is)

### ISSUE THREAD

**Issue by Madhu94** [grafana/grafana#7610]
I am using Grafana v4.1.2. OS is Red Hat Enterprise Linux Server (release 7.3) 

I used the tarball given in the [downloads ](http://grafana.org/download/)page to install 

I wanted to be able to install plugins like the pie chart. I ran this 
```
grafana-cli plugins install grafana-piechart-panel
```

I got this error
```
Error: \u2717 error: stat /var/lib/grafana/plugins: no such file or directory
```

I tried changing the settings in defaults.ini file 
```
plugins = ~/data/plugins // I created this folder in my home directory
```
That didn't work, neither did the ``--pluginsDir`` command line option.  

Do plugins need a different configuration, if Grafana was installed via tarball?

Thanks,
Madhu

**Comment by torkelo** [comment]
if you install via tarball you need to use --pluginsDir option. Can you show how you used it and what the result was? 

Test installing plugins using cli from tar ball, seems to work fine. 

```
❯ ./bin/grafana-cli --pluginsDir ~/Downloads plugins install grafana-piechart-panel
installing grafana-piechart-panel @ 1.1.4
from url: https://grafana.net/api/plugins/grafana-piechart-panel/versions/1.1.4/download
into: /Users/torkel/Downloads

✔ Installed grafana-piechart-panel successfully
```

**Comment by Madhu94** [comment]
Thanks ! I got it now. It was a permissions issue.
