### ISSUE TITLE
[Bug] Serverside rendering broken in ha environment

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#7611]
i am using such a scheme for my installation 
![image](https://cloud.githubusercontent.com/assets/289277/23094616/f09d3192-f615-11e6-8c3a-9a42717f483b.png)

There are trouble with that kind of installation. 
Serverside rendering is not working giving very useless error 404. 

First of all i have to patch grafana's render.js with 
```
  page.customHeaders = {
      "Authorization": "Basic XXXXXXXXX"
  };
```
my grafana config has 
```
[server]
root_url = https://XXXXX/ui/grafana/

[auth.proxy]
enabled = true
header_name = Remote-User
header_property = username
```
After some investigation i found that construct 
https://github.com/grafana/grafana/blob/c400b5cf635a88f6a86732c1c45ab6ff97c45d4d/pkg/components/renderer/renderer.go#L63

it seems it brokes all the things. because generates following 
```
/usr/share/grafana/vendor/phantomjs/render.js,url=http://localhost:3000/dashboard-solo/script/noc.js?dashboard=mo&id=175485&height=500,width=1000,height=500,png=/opt/noc/var/db/grafana/png/XSrzzxgI42uA5YZ1n3Q2.png,domain=localhost,renderKey=18gczSfHuVh77aG8czXuNKzevU0BbkMZ
```
so trouble is 
* http instead of https 
* localhost insted of host part of root_url or domain
* port 

probably there was some spelling error in 
https://github.com/grafana/grafana/commit/ab07667b6945b8d97cbc580737818a1a6accfbdf#diff-c1caa1da1a352a16b0e1f58ee28e92bcR40
cause there have to be `localDomain = setting.domain `

or 
maybe there have to be root_url 
https://github.com/grafana/grafana/blob/c400b5cf635a88f6a86732c1c45ab6ff97c45d4d/pkg/components/renderer/renderer.go#L68

**Comment by torkelo** [comment]
set protocol in grafana.ini http options to https and it should work.  The local phantomjs render call should use localhost

**Comment by freeseacher** [comment]
nope. 
```
фев 18 19:23:41 db04 grafana-server[9052]: t=2017-02-18T19:23:41+0300 lvl=info msg="Initializing CleanUpService" logger=cleanup
фев 18 19:23:41 db04 grafana-server[9052]: t=2017-02-18T19:23:41+0300 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=https subUrl=/ui/grafana
фев 18 19:23:41 db04 grafana-server[9052]: t=2017-02-18T19:23:41+0300 lvl=eror msg="Fail to start server" logger=server error="cert_file cannot be empty when using HTTPS"
```

Grafana is listening on http port. there no need for https in backend network

**Comment by freeseacher** [comment]
Ok let me explain more. it seems problem is much more complicated. I have a scripted dashboard
On a saved dashboard everything works as expected
```
фев 18 20:38:04 db04 grafana-server[30171]: t=2017-02-18T20:38:04+0300 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/fttb-2014-s2328-n1-3-s1-15-511702-copy"

фев 18 20:38:05 db04 grafana-server[30171]: Input: /usr/share/grafana/vendor/phantomjs/render.js,url=http://localhost:3000/dashboard-solo/db/fttb-2014-s2328-n1-3-s1-15-511702-copy,width=1000,height=500,png=/opt/noc/var/db/grafana/png/mujStp8Z9MvBDE6txqap.png,domain=localhost,renderKey=jUcVuRGFEh10eXBzpFSqAkyP9A0jX3Z1

фев 18 20:38:05 db04 grafana-server[30171]: Loading a web page: http://localhost:3000/dashboard-solo/db/fttb-2014-s2328-n1-3-s1-15-511702-copy status:
```

but i use scripted dashboard for most of the cases
```
фев 18 20:39:06 db04 grafana-server[30412]: t=2017-02-18T20:39:06+0300 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/script/noc.js?dashboard=mo&id=175485"
фев 18 20:39:06 db04 grafana-server[30412]: Input: /usr/share/grafana/vendor/phantomjs/render.js,url=http://localhost:3000/dashboard-solo/script/noc.js?dashboard=mo&id=175485,width=1000,height=500,png=/opt/noc/var/db/grafana/png/1XNALXvN5agridAQxyFH.png,domain=localhost,renderKey=mgvyM97FoIjohpIQQ4iCDHfDlnoIK3Ut
фев 18 20:39:06 db04 grafana-server[30412]: Loading a web page: http://localhost:3000/dashboard-solo/script/noc.js?dashboard=mo&id=175485 status:
фев 18 20:39:07 db04 grafana-server[30412]: t=2017-02-18T20:39:07+0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/pm/ddash/ status=404 remote_addr=[::1] time_ms=6ns size=10245
фев 18 20:39:17 db04 grafana-server[30412]: t=2017-02-18T20:39:17+0300 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=shirokih method=GET path=/render/dashboard-solo/script/noc.js status=404 remote_addr=10.2.67.126 time_ms=11.518µs size=19
```
so there will be no noc.js on  http://localhost:3000/dashboard-solo/script/noc.js

**Comment by bergquist** [comment]
@freeseacher is the scriptet dashboard available on both grafana servers?

**Comment by freeseacher** [comment]
yep. on both. but what about path ? 
by the way according to script (it rather simple), grafana have to get url 
```
....
    // Get dashboard configuration
    $.ajax({
        method: "GET",
        url: "/pm/ddash/?" + $.param(args)
    }).done(function(result) {
        callback(result);
    });
....
```
of cause that url will not be available here.

**Comment by torkelo** [comment]
> what about path

Not suree what you mean, what about it? 

> of cause that url will not be available there.

I am bit confused here, what URL?

**Comment by torkelo** [comment]
closing this due to lack updates
