### ISSUE TITLE
Support new PromQL native histogram functions

### ISSUE THREAD

**Issue by krajorama** [grafana/grafana#76111]
**Why is this needed**:

Users of [native histograms](https://prometheus.io/docs/prometheus/latest/feature_flags/#native-histograms) would expect auto completion, help text, syntax check, syntax highlighting  for the new histogram functions

- histogram_avg no documentation link yet, just merged: https://github.com/prometheus/prometheus/pull/13467
- [histogram_count](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_count-and-histogram_sum)
- [histogram_sum](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_count-and-histogram_sum)
- [histogram_fraction](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_fraction)
- [histogram_stddev](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_stddev-and-histogram_stdvar)
- [histogram_stdvar](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_stddev-and-histogram_stdvar)

Also [histogram_quantile](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile) can work on native histograms.

**What would you like to be added**:

See above.

**Who is this feature for?**

Operator, dashboard editor.

End-user of dashboards not affected so I'd say this is a nice to have feature.

**Comment by itsmylife** [comment]
This requires upgrading the lezer package which has no migration guidelines. That makes things hard to implement. Due to other commitments in Q4, we will be able to take this maybe at the end of Q4 or in Q1.

**Comment by krajorama** [comment]
I've added one more function that we just merged and in the mean time we added some documentation in Mimir as well: https://grafana.com/docs/mimir/latest/visualize/native-histograms/
