### ISSUE TITLE
TimeRange: Copy & paste time range

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#76122]
**Why is this needed**:

Customers often need to reuse the same time range in multiple places in Grafana. For example:

- after finishing troubleshooting in Explore, go to a dashboard and apply the same range as in Explore
- after narrowing down the data in a dashboard, go to other tab (e.g. with Explore or an App Plugin) and reuse the same range
- etc.

**What would you like to be added**:

It'd be great to have a way to "copy current time range to clipboard" and "paste time range from clipboard". For example there could be two small buttons to perform both actions: one to copy the range to clipboard and the other to paste it.

For example:

https://github.com/grafana/grafana/assets/745532/c599bb76-8ef8-4767-bd6d-dd51a839b2cd

**Who is this feature for?**

Any user who needs to look at the data within the same time range but using different features.

cc @gtk-grafana @the-it @grafana/explore-squad

**Comment by joshhunt** [comment]
@ifrost  In general we're supportive of this feature, though we probably won't prioritise this soon. Pull requests are welcome :) 

We discussed this as a team, and the main struggle we had was identifying a good UI pattern for implementing this, without adding too much clutter to an already quite busy interface.

**Comment by dmitry-cherkas** [comment]
I came here searching for this feature, as I miss if after Datadog. The UX they implemented is simple and convenient - when the user clicks on the time range picker - it converts to a simple input field, allowing to copy and paste the value.
<img width="595" alt="image" src="https://github.com/grafana/grafana/assets/3441528/16b420fc-dbf4-4da6-9207-e5a67617ea2b">

Hope to see something similar in Grafana one day.

**Comment by datamuc** [comment]
That's already too much clicking, but pressing `t` `c` switch dashboard and press `ctrl-v` would be awesome. If you do it, please also make sure that it works from/to the explorer.
