### ISSUE TITLE
synchronize queries between alert rule and dashboard panel

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#76139]
**Why is this needed**:

In the old grafana, when you defined an alert, it was part of the dashboard, and thus shared the same query as the panel. Now however alert queries are maintained completely independently from dashboards. This leads to them becoming desynchronized. A user may edit one and forget about the other, leading to confusion when the alerts don't match with what the panel shows.

**What would you like to be added**:

Alerts can already be linked to panels by creating the alert from the edit panel screen. This link should be used to maintain synchronization. Either the alert should directly reference the panel query. Or when either is edited, the query should be copied to the other.

**Who is this feature for?**

People who create alerts from panels.

**Comment by eugenenelou** [comment]
I agree that this would be useful. 
Especially in my case I have most of my dashboards with parametrized datasource for various environments (like preprod), but want my alerts to be on the production environment. I'd like to be able to share the query between the alert and the panel, but not necessarily the datasource.
