### ISSUE TITLE
Alerting: Losing data of contact points and notification templates due to overwriting everything

### ISSUE THREAD

**Issue by ignas-sedunovas** [grafana/grafana#76138]
### What happened?

I was editing different contact points and/or notification templates in separate browser tabs, but later noticed that many of my changes were gone.

Upon inspection I found out that, even though I was editing a _single_ contact point or a _single_ notification policy, the saving process was sending _all_ contact points _and all_ notification templates to the API. This behavior leads to overwriting any change in any other contact point or notification template done since I loaded the Contact Points page. Last browser tab so submit changes wins. And there's no warning.

Currently, the only way to not lose data is if only one person edits Contact Points page and uses only one browser tab for that.

Here is what gets `POST`ed to `/api/alertmanager/grafana/config/api/v1/alerts` when saving a _single_ contact point:
![grafana POST](https://github.com/grafana/grafana/assets/3921290/a9e82a05-6c9d-47d7-956d-48b7c76f0769)

### What did you expect to happen?

That only _that_ single contact point or notification template is saved when clicking the Save button

### Did this work before?

Don't know. 
But at least don't remember having this issue with the legacy alerting system.

### How do we reproduce it?

Scenario A:
1. Open Contact Points page (`alerting/notifications`) on two tabs and create a new contact point on each (in any sequence or with any delay)

Outcome -> only the last saved is persisted

Scenario B:
1. Open two different contact points on two tabs
2. Make any change and save (in any sequence or with any delay)

Outcome -> only the last saved is persisted

Scenario C:
1. Open two different notification templates on two tabs
2. Make any change and save (in any sequence or with any delay)

Outcome -> only the last saved is persisted

### Environment (with versions)?

Grafana: Grafana v10.1.2 (8e428858dd)
OS: Windows Server 2019 Core
Browser: any

### Grafana platform?

A downloaded binary

**Comment by KevalSenghani171** [comment]
Hi Ignas, I am also facing the issue. In the latest version it is overriding just like you described your scenario. But in Grafana 9.5.2 this was not happening. If someone has made changes and if you are making the changes this dialogue box use to come and it forcefully tell us to first refresh the page and make your changes.
![Grafana Alert save dialogue](https://github.com/grafana/grafana/assets/53435521/df8af9bd-4eeb-42ed-a243-718be9ecc08a)

**Comment by armandgrillet** [comment]
> In the latest version it is overriding just like you described your scenario. But in Grafana 9.5.2 this was not happening.

Interesting, the lack of the warning looks like a regression.  We did not remove it on purpose. Thank you for the report.
