### ISSUE TITLE
[Bug] Should not be possible to create self-referencing (recursive) template variable definitions 

### ISSUE THREAD

**Issue by Gelob** [grafana/grafana#7614]
Please include this information:
- What Grafana version are you using? 4.1.2-1486989747, 4.2.0-7034pre1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS
- What did you do? I created a templated query that included the variable in the query for the same templated variable I was making
- What was the expected result? The templating system would throw an error or the dashboard would load after saving
- What happened instead? The query was valid and displayed None and the dashboard appeared to work as expected with the failed templating variable after hitting Update. Everything works fine until saving and refreshing upon wish the dashboard failed to load properly.

Example:
Template variable name: device
Template variable type: query
Query: SHOW TAG VALUES FROM "network.interfaces" WITH KEY = "host"  WHERE blah = "$device"

This is a query with valid syntax, that returns no results. By just having $device in the query, when saving the dashboard and refreshing you are presented with a blank page.

![image](https://cloud.githubusercontent.com/assets/422752/23106515/55163634-f6b4-11e6-9606-6ad54bd15f26.png)

**Comment by torkelo** [comment]
thanks for reporting this. There should be some kind of validation so variables like this cannot be created
