### ISSUE TITLE
[Question/Request] Make Grafana responsive  

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7615]
Please include this information:
- What Grafana version are you using? latest
- What datasource are you using? Prometheus
- What OS are you running grafana on? macOS Sierra
- What did you do? Reduced the window
- What was the expected result? Elements being responsive
- What happened instead? 80% of the contents were responsive

I think Grafana is responsive and I'm doing something wrong but maybe it's not the case. I tested to reduce my window to see how my dashboard would fit on a Tab or on a Smartphone and I noticed that the graphics were responsive (they go one under one) but the top menu wasn't responsive. 

Here it's the maximum view where all is perfect:
<img width="1673" alt="capture d ecran 2017-02-20 a 10 15 12" src="https://cloud.githubusercontent.com/assets/22610050/23118744/805d49d0-f755-11e6-97f6-2c84ce044ef0.png">

Then it's the view when I reduce the window:
<img width="1303" alt="capture d ecran 2017-02-20 a 10 15 45" src="https://cloud.githubusercontent.com/assets/22610050/23118768/9743595a-f755-11e6-8980-c05086381a06.png">

What we can see is that the logo is hide under the grey top menu bar

And if I reduce a bit more to reproduce smartphone view :
<img width="405" alt="capture d ecran 2017-02-20 a 10 16 57" src="https://cloud.githubusercontent.com/assets/22610050/23118806/c11d003c-f755-11e6-80ac-8cf1d17880e9.png">

We can see the top menu is pretty ugly.

Does it come from the fact that I "Pin" my left side menu ? Or is it just not responsive ? 

Thank you for your answer

**Comment by torkelo** [comment]
it is responsive, but we do not support a pinned side menu in mobile views

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/23118946/7a64340c-f756-11e6-8789-6630599ce85f.png)

**Comment by JeromeVi** [comment]
Thank you for the really fast answer 👍
