### ISSUE TITLE
Canvas: Button secondary variant seems to be broken

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#76159]
Secondary button variant should have a grey background with black text but is currently showing up as transparent background with white text

Investigate this and implement a fix

Current canvas button with secondary variant (in dark mode this seems expected)
<img width="134" alt="Screenshot 2023-10-06 at 11 52 28 PM" src="https://github.com/grafana/grafana/assets/22381771/baed205c-f782-4a43-b369-f5ba188a0236">

For light mode this is very broken
<img width="191" alt="Screenshot 2023-10-06 at 11 55 04 PM" src="https://github.com/grafana/grafana/assets/22381771/83f7250e-63db-410c-b824-245a60281aa2">

[Expected](https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-button--basic&args=variant:secondary)
<img width="200" alt="Screenshot 2023-10-06 at 11 57 16 PM" src="https://github.com/grafana/grafana/assets/22381771/6ecea813-ef75-46c1-bbb0-7d2d0d7eafd6">

Might be related to: https://github.com/grafana/grafana/blob/91b20ce751b16d517c852daccbbc7c1343f4b2c8/public/app/features/canvas/element.ts#L94

**Comment by ibilalkayy** [comment]
@nmarrs In light mode, the Example Button is working. You can see it here.
![Screenshot from 2023-10-07 15-21-57](https://github.com/grafana/grafana/assets/64713734/d55ef5e9-22c3-4cbf-8f53-83b35862a043)

**Comment by aditya-sodhiya** [comment]
I can work on this. Please assign it to me.

**Comment by drew08t** [comment]
Hey @aditya-sodhiya, that would be awesome. Please feel free to work on it. We will support any PR you create.

**Comment by nmarrs** [comment]
I think this has been fixed in latest main, so closing this issue out

https://github.com/grafana/grafana/assets/22381771/2f361231-bbfb-4d3c-bc1c-9e04b39e54ab
