### ISSUE TITLE
Logging: empty values in logfmt logs are not formatted properly

### ISSUE THREAD

**Issue by tiny6996** [grafana/grafana#76175]
### What happened?

when shipping logs from Grafana to Loki via syslog -> Telegraf -> Loki I was unable to parse the logs due to certain logfmt keys being empty showing as `key=`  specifically the uname field. This doesn't occur when setting logs to json. JSON log messages set the uname field to `""`

```
logger=context userId=0 orgId=0 uname= t=2023-10-07T00:25:56.627991134Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=10.89.0.44 time_ms=0 duration=360.541µs size=29 referer= handler=/
```

### What did you expect to happen?

logfmt keys without a value would either appear as key="" or be removed from the log message

```
logger=context userId=0 orgId=0 uname="" t=2023-10-07T00:25:56.627991134Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=10.89.0.44 time_ms=0 duration=360.541µs size=29 referer= handler=/
```

### Did this work before?

unsure

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1
OS: Fedora 38 with podman
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

loki

**Comment by matyax** [comment]
@tiny6996 It looks to me that you might be looking for the `--keep-empty` flag for the `logfmt` parser. You can read more https://grafana.com/docs/loki/latest/query/log_queries/#parser-expression . It's a recent addition to Loki, so your version has to support this.

**Comment by tiny6996** [comment]
thanks my workaround for now has been to use json logging for grafana and loki but I will keep this mind if I run into it again
