### ISSUE TITLE
Dashboard: Improve widget split flow

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#76179]
In order to move the widget split feature forward, we need to address internal feedback

- Drop the modal of widget selection and follow the same UX as in "adding visualization"
- Introduce widget link when searching widget in visualization tab (@Ijin08 to check UX)
- Add a widget tab next to the visualizations tab (@Ijin08 design support)
- Add aux secondary text under options in the "Add +" CTA
- Library panels should show all panels (no filtering based on what is rendered)

_Originally posted by @thanos-karachalios in https://github.com/grafana/grafana/issues/67910#issuecomment-1746918301_

**Comment by shih-chris** [comment]
> Drop the modal of widget selection and follow the same UX as in "adding visualization"

I'm just a user of grafana (mostly for business intelligence & analytics), so I don't have the context around our broader UX design. 

**Fwiw, I really like the widget selection**. I've helped a few new Grafanistas get up to speed on using Grafana and it's typically been a little jarring that the add visualization flow drops you into a time series panel automatically (which in analytics world _usually_ starts a user off with an error that there is no time series column).

Is the proposal that the add widget defaults to adding a text panel?

If we haven't A/B tested the presence of the widget selection, I'd love to help us do so on a small % of users to see if there are differences in user behaviors!

**Comment by axelavargas** [comment]
After an internal discussion, we decided to put the Widget and Visualization Split efforts on hold.

https://github.com/grafana/grafana/issues/78114
