### ISSUE TITLE
Adhoc filter not filtering on Grafana 10.1.x

### ISSUE THREAD

**Issue by doctorwhoq** [grafana/grafana#76183]
### What happened?

The adhoc filter doesnt seems to be working in Grafana 10.x with Elasticsearch DS.
"must\":[{\"match_phrase\" part of the query doesnt seem to show up when querying to ES, as can be seen from the query inspector.

Tried the same dashboard/DS on grafana 9.3.16, seems to working just fine.

https://ibb.co/GP7G0bC

### What did you expect to happen?

The adhoc filters from table works properly.

### Did this work before?

Yes, Grafana version 9.3.16.

### How do we reproduce it?

1. Create a dashboard with ES and a table panel.
2. Adhoc filter from the table 
3. Check to see if the resulted is filtered 

### Is the bug inside a dashboard panel?

Seems to be the issue with the DS.

### Environment (with versions)?

Grafana: 10.1.4
OS: Pop Os
Browser: Brave

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch

**Comment by torkelo** [comment]
I did spin up Elasticsearch and tested adhoc filters and seems to work, it modifies the query string:

the level:"info" is from the adhoc filter I added 
![image](https://github.com/grafana/grafana/assets/10999/704c1f1b-f001-4391-abef-b3462ec83ed9)

**Comment by doctorwhoq** [comment]
Have you try filter it from a table panel ? 
`
'{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["kong-access-log-2023.10.09"]}\n{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1696846984256,"lte":1696850584256,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:(\\"xxx\\") AND http_status:(\\"200\\") AND request.uri.keyword:\\"/plugins/servlet/nfj/PushNotification\\""}}],"must":[{"match_phrase":{"request.uri.keyword":{"query":"/plugins/servlet/nfj/PushNotification"}}}]}},"aggs":{"2":{"date_histogram":{"field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1696846984256,"max":1696850584256},"format":"epoch_millis","fixed_interval":"1m"},"aggs":{"1":{"percentiles":{"field":"latencies.request","percents":["25","50","75","95","99"]}}}}}}\n' `

this is the same request from Grafana 9.x
`'{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["kong-access-log-2023.10.09"]}\n{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1696847177972,"lte":1696850777972,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"host:(\\"xxx\\") AND http_status:(\\"200\\")"}}]}},"aggs":{"2":{"terms":{"field":"host.keyword","size":10,"order":{"_count":"desc"},"min_doc_count":1},"aggs":{}}}}\n'`

This is from Grafana 10.x 

Notice the `"must":[{"match_phrase"` is missing from the second body.

**Comment by doctorwhoq** [comment]
I also notice that this button is not triggering a search to DS as i'm watching the networks tab 
https://ibb.co/H2VfBHx

**Comment by torkelo** [comment]
@doctorwhoq strange, it works for me. Have you changed the feature toggle enableElasticsearchBackendQuerying? 

where did you see that request?

**Comment by doctorwhoq** [comment]
No, i use the same ini file for both version actually, with most of it being default. 

Would you require a recording or something like that to further investigate ? it'd be much easier too see it in action.

**Comment by svennergr** [comment]
@doctorwhoq would be great if you could share the panel JSON by clicking on the Panel Menu -> Inspect -> Panel JSON.

**Comment by doctorwhoq** [comment]
```
{
  "id": 8,
  "gridPos": {
    "h": 9,
    "w": 14,
    "x": 0,
    "y": 29
  },
  "type": "table",
  "title": "Top Request URI by count",
  "transformations": [
    {
      "id": "merge",
      "options": {
        "reducers": []
      }
    }
  ],
  "datasource": {
    "type": "elasticsearch",
    "uid": "${datasource}"
  },
  "pluginVersion": "9.3.16",
  "links": [],
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto",
        "inspect": false
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "decimals": 2,
      "displayName": "",
      "unit": "short"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Time"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Time"
          },
          {
            "id": "unit",
            "value": "time: YYYY-MM-DD HH:mm:ss"
          },
          {
            "id": "custom.align"
          }
        ]
      }
    ]
  },
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": "",
      "countRows": false
    },
    "cellHeight": "sm"
  },
  "targets": [
    {
      "alias": "",
      "bucketAggs": [
        {
          "field": "request.uri.keyword",
          "id": "2",
          "settings": {
            "min_doc_count": "1",
            "order": "desc",
            "orderBy": "1",
            "size": "20"
          },
          "type": "terms"
        }
      ],
      "datasource": {
        "type": "elasticsearch",
        "uid": "${datasource}"
      },
      "hide": false,
      "metrics": [
        {
          "id": "1",
          "type": "count"
        }
      ],
      "query": "host:$host AND http_status:$http_status",
      "refId": "A",
      "timeField": "@timestamp"
    }
  ]
}
```

I just straight up pasted this into the grafana 9.3.16 and it works well with the adhoc filter without doing anything but select the DS.

**Comment by svennergr** [comment]
So that's the panel from 9.3.16. Could you provide the same directly from 10.1.4? Also if you could provide a recording of the issue it would be awesome.

With that panel JSON I don't see anything wrong and in my local installation everything was working fine.

**Comment by doctorwhoq** [comment]
It's the panel from 10.1.4, i pasted it into the 9.3.16 
Here a video on that,
a small notes, the grafana on the left is 10.x , the right one is 9.x .
You should watch it from 0:23, i messed up the first half, might cause you confusion.

https://gemoo.com/tools/upload-video/share/569985044997558272?codeId=v69RO95jpR2q9&card=569985040706785280

**Comment by doctorwhoq** [comment]
Already shared in the panel json above. I'll try 10.2 to see if it works

**Comment by matyax** [comment]
Totally missed it, thanks @doctorwhoq
