### ISSUE TITLE
[Bug]  dashboard rendering show collapse button 

### ISSUE THREAD

**Issue by shlomihorev** [grafana/grafana#7618]
Hi All,

Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? **zabbix 3.2.1** 
- What OS are you running grafana on? Centos 6.7
- What did you do? Render the dashboard - http://10.37.171.244:8080/render/dashboard/db/zabbix?width=1800
- What was the expected result? See the img without the collapse buttons (see attached)
- What happened instead? We see the img with collapse buttons.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

img  (attached)
![dash](https://cloud.githubusercontent.com/assets/24894890/23125592/2cc6f7e6-f77b-11e6-8e99-a8a3bafa4ccd.png)

**Comment by torkelo** [comment]
dashboard rendering is not an officially supported feature yet (only single panel rendering). So marking this as low prio "bug" for now.

**Comment by torkelo** [comment]
this should be fixed in later versions
