### ISSUE TITLE
Dashboard: Remove usage of bootstrap classes in `DashboardLinksDashboard` component 

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#76182]
The issue is coming from this [escalation](https://github.com/grafana/support-escalations/issues/7724)

`DashboardLinksDashboard` component relies on `bootstrap` classes (https://github.com/grafana/grafana/blob/07266aa983202078de9f21ebc09f93e6d704b36e/public/app/features/dashboard/components/SubMenu/DashboardLinksDashboard.tsx#L51C17-L51C17), however, the library is only [included](https://github.com/grafana/grafana/blob/07266aa983202078de9f21ebc09f93e6d704b36e/public/app/angular/loadAndInitAngularIfEnabled.ts#L21) when the `angularSupportEnabled` configuration is enabled. This leads to a problem when a Grafana instance does not have that configuration if a dashboard link is rendered as a Dropdown. 

![image](https://github.com/grafana/grafana/assets/239999/e8dd038e-bd54-4afb-ae56-9660c0341f0b)

A good approach will be to use the `Menu` component from `grafana-ui` and not rely on the old bootstrap CSS classes.

**Comment by torkelo** [comment]
@axelavargas i think the menu component would be the best match.

**Comment by axelavargas** [comment]
Oh yes! I forgot that one! Thank you 🙌🏾

**Comment by axelavargas** [comment]
Fixed by https://github.com/grafana/grafana/pull/77855 🥳
