### ISSUE TITLE
Loki: Metric kick start your query should be applied on top of your log query

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#76207]
When user selects **metric kick start your query** pattern with log query - e.g.`{job="grafana"} | logfmt | foo="bar"`, it should not remove pipe operations/ it should apply it on top of that query. 

https://github.com/grafana/grafana/assets/30407135/80445d48-39b7-4971-a30c-a6abb9f649cb

**Comment by ivanahuckova** [comment]
I marked it as bug, but maybe it is more of an UX issue.

**Comment by lucasoares** [comment]
This can be related: https://github.com/grafana/grafana/issues/70243
