### ISSUE TITLE
[Bug] Not receiving alerts even though metric value have crossed threshold

### ISSUE THREAD

**Issue by PNarode** [grafana/grafana#7621]
Grafana Version: v4.1.1.
Datasource: Influxdb

I am setting alert in one of my dashboard graph. Even though my metric value have crossed the threshold I have set in my alert rule, no alerts have been triggered or no notification have be sent. Also even though its in alerting state (as clicking on Test Rule button I see data in log I have attched a screenshot), the graph shows No Data state. Also one more issue I see is even its in No data state, a No Data notification is also not send.

<img width="679" alt="screen shot 2017-02-20 at 7 47 54 pm" src="https://cloud.githubusercontent.com/assets/5019916/23128609/8d8f418a-f7a5-11e6-9c9f-9f4ab438f139.png">
<img width="1410" alt="screen shot 2017-02-20 at 7 48 07 pm" src="https://cloud.githubusercontent.com/assets/5019916/23128610/8de60128-f7a5-11e6-9fe4-6d582e18f4e2.png">

**Comment by torkelo** [comment]
have you added any notifications under Notifications section in the alert rule? Any error in grafana.log?

**Comment by PNarode** [comment]
I have added slack notification.
<img width="647" alt="screen shot 2017-02-20 at 7 56 53 pm" src="https://cloud.githubusercontent.com/assets/5019916/23128941/c4492e2e-f7a6-11e6-880a-94aa2549ca4a.png">

**Comment by torkelo** [comment]
and does it work when you test it?

**Comment by torkelo** [comment]
in the notification channel edit page

**Comment by PNarode** [comment]
yes it works. It is able to send a test alert

**Comment by PNarode** [comment]
Here is this query right when data is being written to influx every 5m
<img width="631" alt="screen shot 2017-02-20 at 8 02 22 pm" src="https://cloud.githubusercontent.com/assets/5019916/23129153/97f3fa9c-f7a7-11e6-907b-87dfaf2d8fa4.png">

**Comment by PNarode** [comment]
Oh wait I started receving alerts. Not sure what was wrong with it. It took lot of time to change its state. Thanks for your response.
