### ISSUE TITLE
BUG-Issues visualizing imported metrics from an upstream system

### ISSUE THREAD

**Issue by bsurnida** [grafana/grafana#7622]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
3.1.0
- What datasource are you using?
graphite
- What OS are you running grafana on?
Centos 6.8
- What did you do?
Import custom metrics and tried to visualize data for last 30 days
- What was the expected result?
A graphite for the whole last 30 days.
- What happened instead?
Missing last 7 days portion in the last 30 days report

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
Attached
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Attached more files.

If it relates to *alerting*
- An image of the test execution data fully expanded.

More notes:

Hi, I'm having some issues while visualizing some of the metrics on grafana and wondering if this a bug.
I've imported the metrics from our upsteam metrics system (solarwinds) into grafana.

I'm able to see the graph for the 7 days metrics just fine.
When I try to view the data for the last 30 days, I'm missing the last 7 days portion of the graph.
When I try to view the data for the last 60 days, I'm missing the last 30 days portion of the graph.
Any report more than 60 days is missing the last 30 days portion.

In solarwinds the metrics are stored as follows.
1 data point per every day since last 2 yrs till the last 30 days.
1 data point per every hour since the last 30 days till the last 7 days.
1 data point per every 15 mins since the last 7 days till the current time.

The metric I'm trying to visualize is the size of a datavolume on a given server in a given cluster.

PFA a sample metrics file,a python program I used to upload the metrics to graphite, some screenshots and a json export of the dashboard.

let me know this might be due to nonexistence of an entry in the storage-schemas.conf file for my metrics.
The metrics are store in a single on the graphite server as below.
/data/graphite/whisper/mycluster/myserver/datavolumesize.wsp

I plan to push similar metrics once every day say 6:00 AM. At times I may have to load a couple of hours of data.

Any pointers are most appreciated.
![last-30-days](https://cloud.githubusercontent.com/assets/5676347/23140816/59ba2fcc-f779-11e6-95bb-499b59fe640c.png)
![last-60-days](https://cloud.githubusercontent.com/assets/5676347/23140818/59c0b8ec-f779-11e6-9082-8bdef5bb9ee4.png)
![last-7-days](https://cloud.githubusercontent.com/assets/5676347/23140817/59c04fd8-f779-11e6-9d9f-729625ecc023.png)
[metrics.txt](https://github.com/grafana/grafana/files/788466/metrics.txt)
[python-pgogram-for-sending-metrics-to-graphite.txt](https://github.com/grafana/grafana/files/788468/python-pgogram-for-sending-metrics-to-graphite.txt)
[mydashboard.json.txt](https://github.com/grafana/grafana/files/788470/mydashboard.json.txt)

**Comment by torkelo** [comment]
Review your graphite storage schema and import processes, maybe open questions in mailing list. 

This is not a problem in Grafana and we try to keep questions to mailing list and other channels. Hope you find help there.

**Comment by bsurnida** [comment]
Thanks for your response @torkelo , I'll review the storage schema.

**Comment by hector7869** [comment]
@bsurnida I would be interested into finding out how you are importing the data from solarwinds. Can you provide more details on that?

**Comment by bsurnida** [comment]
@hector7869 sorry for the late reply.

Solar winds has a rest api using which you can get the metrics and the history you may need.
https://thwack.solarwinds.com/thread/55527

You can install a sqleditor like client from below links and run the sql like SWQL commands to retrieve the data.
You might have to spend some time understanding the underlying Orion database schema first.
https://github.com/solarwinds/OrionSDK/releases
https://github.com/solarwinds/OrionSDK

Hope this helps for you though this is not much relevant grafana.

**Comment by douglasmauro** [comment]
@bsurnida did you figure this out?  We're trying to perform the same task.  Any code to share?

Thanks!
