### ISSUE TITLE
[Feature request] Document AWS regions and permissions for S3 external image upload

### ISSUE THREAD

**Issue by whereisaaron** [grafana/grafana#7624]
Please include this information:
- What Grafana version are you using? **4.20-pre-1**
- What datasource are you using? **N/A**
- What OS are you running grafana on? **Linux**
- What did you do? **Read documentation on docs.grafana.com**
- What was the expected result? **Gain enough information to configure S3 external image uploads**
- What happened instead? **No information on how to specify AWS region nor required S3 permissions**

I created PR #7623 to add the missing information.

Note that the 'external_image_storage.s3.bucket_url' might be better replaced with
- external_image_storage.s3.bucket_name
- external_image_storage.s3.region

I think using a URL is throwback to the old uploader code. The URL you configure is never actually used for anything except to regex out the bucket name and region. The regex works for '.amazonaws.com.cn' regions, but only by mistake, since it is a substring match.

https://github.com/grafana/grafana/blob/master/pkg/components/imguploader/imguploader.go#L34-L46
```
region := ""
rBucket := regexp.MustCompile(`https?:\/\/(.*)\.s3(-([^.]+))?\.amazonaws\.com\/?`)
matches := rBucket.FindStringSubmatch(bucket)
if len(matches) == 0 {
	return nil, fmt.Errorf("Could not find bucket setting for image.uploader.s3")
} else {
	bucket = matches[1]
	if matches[3] != "" {
		region = matches[3]
	} else {
		region = "us-east-1"
	}
}
```

**Comment by torkelo** [comment]
the problem is removing the bucket_url is a breaking change, trying to avoid breaking changes

**Comment by chaosong** [comment]
aws china s3 url format cannot pass `rBucket.FindStringSubmatch(bucket)` because of `s3.<region>` instead of `s3-<region>`. 
eg: "https://ops-monitor.s3.cn-north-1.amazonaws.com.cn/test.jpg"
