### ISSUE TITLE
Alert list panel started flashing after upgrade

### ISSUE THREAD

**Issue by dusatvoj** [grafana/grafana#76259]
### What happened?

Before upgrade to grafana v10.x we commonly used the feature of alertlist that can be refreshed every second and there are appearing and disappearing alerts over time.

After upgrade to grafan v10 (currently v10.1.4) there's a problem that it still works but every refresh does flash and rerender.

It's problematic because after the upgrade the re-rendering causes collapsing expanded info @ alert.

Now I can't keep the alert info expanded for longer time than the dashboard refresh time.

The workaround I'm using is to stop refreshing the dashboard.

### What did you expect to happen?

Do not flash and collapse the alert info when dashboard refresh happens.

### Did this work before?

Expanded alert details were still expanded after refresh and there's no re-render flash.

### How do we reproduce it?

1. Create dashboard with fast refresh
2. Add alertlist to dashboard
3. Try to keep alert details expanded for more than the refresh time of dashboard

### Is the bug inside a dashboard panel?

Maybe

### Environment (with versions)?

Grafana: 10.1.4
OS: Arch linux (client), official docker image (server)
Browser: FF 118.0

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
thank you for opening this issue @dusatvoj 

Reproduced as indicated in v10.2.0 - Firefox 118.0.2
![alertlist](https://github.com/grafana/grafana/assets/45235678/ce8083d1-f634-44fb-9b73-7b41b66624d7)



I am forwarding this issue to the alerting team for review

**Comment by dusatvoj** [comment]
It's not only alertlist. The same annoying stuff is happening to table and it's sort.

**Comment by dusatvoj** [comment]
@fayzal-g , not anymore - it's fixed. Closing issue. Thank you
