### ISSUE TITLE
Right-y, remove text from legend

### ISSUE THREAD

**Issue by bhaap** [grafana/grafana#7626]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? 
No idea where to find this
- What datasource are you using? 
InfluxDB
- What OS are you running grafana on? 
Ubuntu 12.04 LTS server
- What did you do? 
Use as normal
- What was the expected result? 
Just Y-axis on the right side
- What happened instead? 
Y-axis on the right side and added text to the legend.
I do not want the (right-y) after the legend text, any way to remove this?

<img width="1686" alt="skarmavbild 2017-02-21 kl 11 43 00" src="https://cloud.githubusercontent.com/assets/2168003/23161560/f1add6b0-f82a-11e6-925b-ef618d414084.png">

The text (right-y) I do not want there.

**Comment by torkelo** [comment]
well it is there to know which series is assign the right y-axis

**Comment by bhaap** [comment]
Yes i know what its for.
Could there be an option to show it or not somewhere? :)

**Comment by torkelo** [comment]
sorry, we have too many options already. An option for this is unlikely
