### ISSUE TITLE
Correlations: Explore Editor UX updates

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#76263]
- [x] Add more emphasis to correlation helper https://github.com/grafana/grafana/pull/75930#issuecomment-1754829790
- [ ] Using info box as form for helper - other options?
- [ ] Save button too far away from the correlation itself
- [ ] Related: Make admin editor consistent by adding confirmation when deleting transformations

@Elfo404 Proposal 
![Untitled-2023-10-10-1617](https://github.com/grafana/grafana/assets/1533128/112ca45a-3392-4e52-8a2b-16a34d481cc9)

**Comment by Elfo404** [comment]
@diegoadams we need to come up with a task list for the improvements mentioned here (if we we want to implement them)

**Comment by diegoadams** [comment]
@Elfo404 , I can add them to this [doc](https://docs.google.com/document/d/1quOleISf5zeflma7c4YIecf1MyL3vl_kHznBKeSTZ3k/edit). The idea behind this doc is that they are still subject to exploration or discussion.
