### ISSUE TITLE
[Feat Req] Support for log scale and negative numbers

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#7627]
latest grafana.
I have a chart that usually looks good, but as soon as negative number has to be shown, it breaks and shows nothing at all.
![not-like-this](https://cloud.githubusercontent.com/assets/20774/23161949/5cde98c4-f82c-11e6-98c0-caaeb70b0b6b.png)

turns out this is because i have log scale enabled.switching to linear scale or removing negative numbers, makes things look good again.

can this be handled in a more graceful way?
my suggestion is to use a similarly log-scaled negative y-axis, like so:
![like-this](https://cloud.githubusercontent.com/assets/20774/23161979/7fbfc138-f82c-11e6-9943-679896629a01.png)

crappy mockup but I hope this explains what I mean ( obviously the scale only needs to go as far as needed, based on what lowest y-value is, which grafana already does)

**Comment by torkelo** [comment]
you cant have a positive and negative pow scale at the same time, at least to my knowledge. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L520

**Comment by Dieterbe** [comment]
as discussed on slack, it should be straight forward.
if v<0, then transform with `-1 *  Math.log(-1 * n) ` and inverseTransform with `-1 * Math.pow(base, -1 *v)` . can we try that?

**Comment by bigbenhur** [comment]
@Dieterbe I don't think it's straight forward as the plot will very likely be misleading: If you connect a positive value and a negative value in your plot with a line, the slope of the line only depends on the axis ranges you choose for the positive and negative values, which is arbitrary (manual axis scale) or depending on the other data values (automatic axis scale). I.e. positive and negative points must not be connected. Also, the user would have to study the axis labels with the positive and negative ranges very hard in order to interpret the plot correctly.

Maybe another transform such as the inverse hyperbolic sine or the cube root is better suited to show large and small numbers (positive, negative and even zero) on the same plot?

**Comment by Dieterbe** [comment]
> If you connect a positive value and a negative value in your plot with a line, the slope of the line only depends on the axis ranges you choose for the positive and negative values, which is arbitrary (manual axis scale) or depending on the other data values (automatic axis scale).

isn't this the exact same problem with the slope between 2 positive points, if the x-axis covers an arbitrary (positive) range, that will also affect the slope. same for linear scales too. am i missing something?

**Comment by bigbenhur** [comment]
@Dieterbe I see your point, but it's not the same. Check out the following two plots showing the same data points on differently scaled axes:
![clipboard01](https://user-images.githubusercontent.com/19605469/29744727-83f8c9f4-8aab-11e7-9521-90c6dd52e99f.png)
![image](https://user-images.githubusercontent.com/19605469/29744732-9161a93a-8aab-11e7-8a4d-e5964778a905.png)
The slope between positive and negative values can be made more shallow or steeper than the other (constant) slope.

I do see positive aspects of this ploting style, but it could confuse people. (Also it would almost certainly never be used/allowed in a scientific publication.)

**Comment by bigbenhur** [comment]
@Dieterbe I just noticed something even worse: try to estimate the y-value of the third data point in the plots above. In the first plot it's between 0 and 0.1, so it's 0.05? Only the second plot shows the value more clearly: it's between 0.001 and 0.1, so it's actually 0.01!

**Comment by Dieterbe** [comment]
I think this is just a property of log axis and manifests itself with only positive axis as well.

**Comment by mueslo** [comment]
You should look into adding a symmetric logarithmic scaling function which is linear around 0, just like https://matplotlib.org/api/_as_gen/matplotlib.colors.SymLogNorm.html

**Comment by xBytez** [comment]
We run into the same issue. I'm currently drawing bits/sec network graphs and using download speed as negative value. When using logarithmic scaling, it completely disappears.

**Comment by bigbenhur** [comment]
@xBytez : What should the log-graph of the negative values look like in your opinion?
(to explain the "bug" you see: log of a neg. number is not a real number and thus cannot be plotted. In my opinion, that's correct.)

**Comment by mueslo** [comment]
@bigbenhur https://github.com/grafana/grafana/issues/7627#issuecomment-396959027

**Comment by bigbenhur** [comment]
@mueslo I agree, symmetric logarithmic scaling would be a useful transformation (not replacing the current logarithmic scaling, but adding a new transformation)

**Comment by mueslo** [comment]
@bigbenhur I concur, since it wouldn't be logarithmic below the linear threshold and requires additional parameters (e.g. what region needs the linear threshold). I think that would satisfy the needs of requesters in this thread (it would mine).

**Comment by jehrich** [comment]
> @xBytez : What should the log-graph of the negative values look like in your opinion?
> (to explain the "bug" you see: log of a neg. number is not a real number and thus cannot be plotted. In my opinion, that's correct.)

I think it's important to distinguish between graphing negative numbers on a log scale, and calculating log of a negative number. The first one simply compresses the graph visually and I think is what Dieterbe is trying to accomplish.

I'm trying to do the same, in order to graph in/out traffic on the same graph. Maybe the solution is to have some way of flipping the axis without making the metric negative.

**Comment by fabio-brbyte** [comment]
i don't know if is the same question, but i have a negative number coming from zabbix, and i want to show logarithmic y-axis and not linear...
my range is -30 to -90, when i try to set this on max end min, the data desapar end y-axis goes to positive numbers

**Comment by unixwitch** [comment]
> I'm trying to do the same, in order to graph in/out traffic on the same graph

i would like to see this too.  

i understand that if you're plotting a single time series which can have both positive and negative values, there are issues with allowing a log scale (as in @bigbenhur example) and i'm fine with not allowing that.

but for network traffic, we have two unrelated time series, "A" and "B", neither of which can ever be negative (unless your NIC is sucking the data back in), so there's no concern about having to plot negative values or calculate the log of a negative number.  

what we actually want is, conceptually, two separate graphs, where one is turned upside down and pasted below the other one.  the centre line of the graph is Y=0, above the centre we plot the positive values of "A" and below the centre we plot the positive values of "B" - both with a log scale.

**Comment by feuGeneA** [comment]
I want this too.  I'm trying to graph logarithmic returns of the price of an asset, and my series is generally in the range [-0.0015,0.0015].  I'd love to be able to make my graph logarithmic, to amplify the differences between my values -- and that sort of works, in that i can see the positive values in the graph just fine, but of course it doesn't really work at all because the Y axis minimum value is 0.  If I manually set the Y-min and Y-max, i can get a decent view of my series, but of course that isn't dynamic to the data in view.

(By the way, just leaving everything linear and Y axis min/max at auto left me wanting (see screenshot) and that's why I went digging into log scale in the first place.
![image](https://user-images.githubusercontent.com/7883777/106535634-adf7d500-64c4-11eb-864b-a6fbb2c5550a.png))

**Comment by dennypage** [comment]
When moving to Grafana, I quickly hit this as well. Same basic requirement described by @xBytez and @unixwitch. Graphing network in/out interfaces as opposing directions with a logarithmic scale.

**Comment by leeoniya** [comment]
> Maybe the solution is to have some way of flipping the axis without making the metric negative.

uPlot has recently gained support for scale direction inversion, which i think opens up a reasonable path to doing this using two charts (one above the other), the bottom one with an inverted y axis.

https://leeoniya.github.io/uPlot/demos/scales-dir-ori.html

i might work on a demo that implements this and we can later evaluate the feasibility of doing it in grafana's new timeseries panel.

**Comment by leeoniya** [comment]
that was...surprisingly easy: https://leeoniya.github.io/uPlot/demos/log-scales2.html

![image](https://user-images.githubusercontent.com/43234/107129753-51623480-688d-11eb-8263-6bca4a88f499.png)

**Comment by leeoniya** [comment]
@bigbenhur

> Maybe another transform such as the inverse hyperbolic sine or the cube root is better suited to show large and small numbers (positive, negative and even zero) on the same plot?

i'm not liking how cube root behaves here, but the inverse hyperbolic sine transform looks super promising and tracks log very well. as a bonus, it's natively supported in browsers via `Math.asinh()`. i'll give it a try in the next week or so and if it works out, that's a much easier path for grafana inclusion vs the two-chart route.

![image](https://user-images.githubusercontent.com/43234/107138031-5cda4d80-68d7-11eb-8282-dcd50afeb0ae.png)

**Comment by bigbenhur** [comment]
@leeoniya 
> i'm not liking how cube root behaves here, but the inverse hyperbolic sine transform looks super promising and tracks log very well. 

As you show that's correct for large numbers. For small numbers around zero asinh becomes almost linear and thus "looses the magnification". E.g. in the use case of @feuGeneA with values in the range of [-0.0015,0.0015] I think the graph would look almost exactly like a linear scale. Don't get me wrong: I still think the asinh transformation is useful, but don't expect it to solve all problems.
Also: the tick spacing and labeling on the y-axis could be a challenge :-)

**Comment by leeoniya** [comment]
i have a prototype that works well. the ticks are not tuned yet, but that won't be an issue as long as we know where the "linear" portion is. the default is about -1,1 but i'm hoping there is a way to compress or expand that region by tweaking the default Math.asinh formula (`ln(x + sqrt(x^2 + 1))`), similar to matplotlib's SymLogNorm: https://matplotlib.org/api/_as_gen/matplotlib.colors.SymLogNorm.html

i've asked the question here:
https://old.reddit.com/r/askmath/comments/lfp4i3/linearity_threshold_for_asinh_inverse_hyperbolic/

if the linearity range can be tuned, then this becomes universally useful, but even without it, i think there's a lot of cases that vanilla `Math.asinh()` would accommodate.

![image](https://user-images.githubusercontent.com/43234/107299391-e0fa1580-6a3c-11eb-8792-a3aa8437e2a1.png)

**Comment by bigbenhur** [comment]
@leeoniya, a tuned transformation formula could be f(x) = asinh(x/a) with a being the limit of the "linear" range.
Examples:
a=1 -> linear range [-1,+1]
a=0.01 -> linear range [-0.01,+0.01]

**Comment by leeoniya** [comment]
sure enough :)

top one is no skew (1), and bottom is 0.00001:

![image](https://user-images.githubusercontent.com/43234/107475947-8e9f1e80-6b3a-11eb-9e6f-948636c2a12a.png)

**Comment by leeoniya** [comment]
arcsinh scales will be natively supported in the next uPlot version:

https://leeoniya.github.io/uPlot/demos/arcsinh-scales.html

![asinh](https://user-images.githubusercontent.com/43234/107867050-e12f5200-6e3c-11eb-965a-fdb1394227d6.gif)

**Comment by shaynevanasperen** [comment]
I've run into this problem too. I'm rendering a bar chart of trading profits and losses. Profits are shown as positve bars and losses as negative bars. The chart is very intuitive to read and comprehend, but as soon as I try to enable log scale, it breaks and stops showing losses.

Is there any progress on this, or is it a dead-end feature request?

**Comment by shapirus** [comment]
I've run into this too. I am rendering a rate function that goes positive and negative and its value is low (around say 10-50) most of the time, but sometimes there are spikes on the order of thousands that make the rest of the graph unreadable. Log scale is an obvious choice, but unfortunately it does not work well with negative (and zero) values. The arcsinh scale would be a good solution.

**Comment by Ruakij** [comment]
I also have this problem.
I want to plot Signal-strenght in dBm which is between -90 to -20 in my case. I want to display it according to a more intuitive scaling which would be logarithmic.

**Comment by daenney** [comment]
* It looks like this feature got released in uPlot 1.6.5: https://github.com/leeoniya/uPlot/releases/tag/1.6.5
* Grafana currently uses 1.6.17: https://github.com/grafana/grafana/blob/8828d5e8d704ddc9e0b4e14e01ffbe1fe01069e9/package.json#L357

So feels like everything for it should already be in place, and what is missing is the option to select it in the graph panel. Right now I only see linear or logarithmic (with a selectable base).

**Comment by nareto** [comment]
> So feels like everything for it should already be in place, and what is missing is the option to select it in the graph panel. Right now I only see linear or logarithmic (with a selectable base).

any news on this?

**Comment by iustin** [comment]
Not being familiar with Grafana's release policies (I see backports labels being added then removed) - is it known already in which version this will land?

**Comment by leeoniya** [comment]
when there are no explicit backport tags like `backport-9.1.x`, the earliest version is gonna be the milestone.

![image](https://user-images.githubusercontent.com/43234/189208443-1fbb75b0-29c5-49e9-be18-1e113df179e4.png)
