### ISSUE TITLE
[Bug] Template error

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7628]
grafana-4.1.2-1486989747.x86_64 with Prometheus on CentOS.

I have a template in a dashboard with 1803 values. When clicking the template filter widget and typing, I get this error in the dev console, once per keypress:

````
boot.6d63bd8b.js:42 TypeError: Cannot read property 'toLowerCase' of undefined
    at boot.6d63bd8b.js:26
    at i (boot.6d63bd8b.js:52)
    at Function.Lg [as filter] (boot.6d63bd8b.js:53)
    at Object.c.queryChanged (boot.6d63bd8b.js:26)
    at fn (eval at compile (boot.6d63bd8b.js:44), <anonymous>:4:239)
    at o.$eval (boot.6d63bd8b.js:42)
    at boot.6d63bd8b.js:44
    at boot.6d63bd8b.js:45
    at d (boot.6d63bd8b.js:40)
    at Cg.$$writeModelToScope (boot.6d63bd8b.js:45)
````

And no filtering of the template list happens.

A similar dashboard with only a few hundred template values works just fine.

**Comment by RichiH** [comment]
PS: The same happened in grafana.x86_64 0:4.1.1-1484211277

**Comment by torkelo** [comment]
Can you show the list of values? Any null values in the template variable?

**Comment by RichiH** [comment]
@bastischubert

**Comment by RichiH** [comment]
@torkelo I will need to verify what, if any, data I can share.

**Comment by RichiH** [comment]
Template query: `label_values(node_boot_time, fqdn)`

From Prometheus: `node_boot_time{fqdn=""}` ->

````
node_boot_time{instance="foo",job="node"}	1484240058
node_boot_time{instance="bar",job="node"}	1485848169
````

So we actually have two empty values in there.

**Comment by bergquist** [comment]
This should be fixed by https://github.com/grafana/grafana/commit/a747d333730c2e79319b9234c6e4bb87458fe94a
