### ISSUE TITLE
[Bug] packagecloud images are not signed properly

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7629]
We are using CentOS and have this in our sources:

````
/etc/yum.repos.d/00-xmlconfig.repo:baseurl=https://packagecloud.io/grafana/stable/el/6/$basearch
/etc/yum.repos.d/00-xmlconfig.repo:gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
/etc/yum.repos.d/00-xmlconfig.repo:baseurl=https://packagecloud.io/grafana/testing/el/6/$basearch
/etc/yum.repos.d/00-xmlconfig.repo:gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
````

`$basearch` being amd64.

Updating the package complains that it's not signed properly:

`Package grafana-4.1.2-1486989747.x86_64.rpm is not signed`

@bergquist mentioned you had to sign by hand; that probably went wrong.

**Comment by RichiH** [comment]
@bastischubert

**Comment by bastischubert** [comment]
[root@prometheus10 yum]# rpm -qi grafana
Name        : grafana
Version     : 4.1.2
Release     : 1486989747
Architecture: x86_64
Install Date: Tue 21 Feb 2017 11:49:47 AM CET
Group       : default
Size        : 132093086
License     : "Apache 2.0"
**Signature   : (none)**
Source RPM  : grafana-4.1.2-1486989747.src.rpm
Build Date  : Mon 13 Feb 2017 01:45:03 PM CET
Build Host  : 5f23998951bc
Relocations : / 
Packager    : contact@grafana.org
Vendor      : Grafana
URL         : http://grafana.org
Summary     : Grafana
Description :
Grafana

**Comment by torkelo** [comment]
This has to be some caching issue. We accidentally published unsigned packages but later republished them (signed). So if you can, try running yum update or maybe some other yum command to flush cache or fetch new packages. 

I did spin up a new centos box and installed it from the yum repo:

```
root@743073422e16 /]# rpm -qi grafana
Name        : grafana
Version     : 4.1.2
Release     : 1486989747
Architecture: x86_64
Install Date: Tue Feb 21 11:21:12 2017
Group       : default
Size        : 132093086
License     : "Apache 2.0"
Signature   : RSA/SHA1, Tue Feb 14 09:44:03 2017, Key ID 8c8c34c524098cb6
Source RPM  : grafana-4.1.2-1486989747.src.rpm
Build Date  : Mon Feb 13 12:45:03 2017
Build Host  : 5f23998951bc
Relocations : /
Packager    : contact@grafana.org
Vendor      : Grafana
URL         : http://grafana.org
Summary     : Grafana
Description :
Grafana
```

Partial logs from the yum install grafana:

```
Total                                                                                                                                                                                                      14 MB/s |  45 MB  00:00:03
Retrieving key from https://packagecloud.io/gpg.key
Importing GPG key 0xD59097AB:
 Userid     : "packagecloud ops (production key) <ops@packagecloud.io>"
 Fingerprint: 418a 7f2f b0e1 e6e7 eabf 6fe8 c2e7 3424 d590 97ab
 From       : https://packagecloud.io/gpg.key
Is this ok [y/N]: y
Retrieving key from https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
Importing GPG key 0x24098CB6:
 Userid     : "Grafana <info@grafana.com>"
 Fingerprint: 4e40 ddf6 d76e 284a 4a67 80e4 8c8c 34c5 2409 8cb6
 From       : https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
Is this ok [y/N]: y
Running transaction check
Running transaction test
Transaction test succeeded
```

**Comment by RichiH** [comment]
If one is unsigned and in the wild, you should arguably bump the package version to get rid of all old versions.

**Comment by torkelo** [comment]
yes, that is definitely true. It was not in the wild very long, and did not know packagecloud would cache the old one.
