### ISSUE TITLE
Transformations: TimeseriesToTable Transformation Error with Multiple Timeseries

### ISSUE THREAD

**Issue by JohnJMartins** [grafana/grafana#76291]
### What happened?

The TimeSeriesToTable transformation does not work as expected with more than one series being returned. This has been tested with multiple other combinations of metrics, namespaces, etc. When a query is returning one time series, the transformation will work as expected and show a sparkline for the series when the cell type is auto or sparkline. When a query returns greater than one series, the transformation does not work correctly, and shows "no data" in the table format, or other broken displays.
No transformation applied, one series returned:
![image](https://github.com/grafana/grafana/assets/77704161/8880c377-1b48-483b-b598-16348154be30)
Transformation applied, one series returned:
![image](https://github.com/grafana/grafana/assets/77704161/4b161ab4-1663-4b62-bc21-35bf08f2537e)
No transformation applied, multiple series returned:
![image](https://github.com/grafana/grafana/assets/77704161/1e7a0073-d7ae-4a8e-a63c-63bfa4e4b9de)
Transformation applied, multiple series returned. No timeseries to table conversion occurs and no sparklines are shown, with corrupted data as well:
![image](https://github.com/grafana/grafana/assets/77704161/646d8ecd-6fd1-4298-b7f9-f099a618b08d)

### What did you expect to happen?

The expected behavior is to see sparkline data in a table format for all of the timeseries returned from a query, much like how the data for a singular returned series is currently displayed.

### Did this work before?

Unsure, this is our first time testing this ability

### How do we reproduce it?

1. Create any query that returns one series and apply the timeseries to table transformation, with a cell type of sparkline. Note the table shows as expected
2.  Alter the query so that multiple series are returned. Note that displays such as "no data" for series which clearly have data in a normal time series will appear, and no sparklines will be shown

### Environment (with versions)?

Grafana: v10.0.2
OS: Windows 11
Browser: Edge

### Grafana platform?

Docker

**Comment by codeincarnate** [comment]
I'll take a look at this and see how the transformation is implemented. Depending on the implementation it may be tricky with multiple series but I'm not sure off the top of my head.

**Comment by JohnJMartins** [comment]
> I'll take a look at this and see how the transformation is implemented. Depending on the implementation it may be tricky with multiple series but I'm not sure off the top of my head.

Thanks, Kyle. Looking forward to updates on this. One thing I would ask is what is the expected behavior here originally: was this always intended to only work for one series being returned or was the intent to be working for multiple series (as I assumed it would)? We were hoping to use this transformation and cell type combination as a basis for another panel we are building, so knowing that this multiseries behavior will be operational in the future would be extremely helpful!

Thanks again, John

**Comment by oscarkilhed** [comment]
https://github.com/grafana/grafana/blob/b6dff851276fee7659fa73ec8ec9da0273c09f24/packages/grafana-data/src/dataframe/utils.ts#L5C8-L10

```
export function isTimeSeriesFrame(frame: DataFrame) {
  if (frame.fields.length > 2) {
    return false;
  }
  return Boolean(frame.fields.find((field) => field.type === FieldType.time));
}
```


I think this is part of the issue here. Frames with multiple value fields are not identified as time series.

**Comment by JohnJMartins** [comment]
> https://github.com/grafana/grafana/blob/b6dff851276fee7659fa73ec8ec9da0273c09f24/packages/grafana-data/src/dataframe/utils.ts#L5-L10
> 
> I think this is part of the issue here. Frames with multiple value fields are not identified as time series.

I see that in the original PR for this feature that multiple sparkline rows in one table is achieved with multiple queries, but at least for our implementation we would need this to be possible with just multiple series returned from one query. Would it be possible to add this feature to the transformation/sparkline cell type in the near future? If not, we will need to look into other avenues of implementing the functionality we want.

**Comment by codeincarnate** [comment]
@JohnJMartins I've been looking more into this. There are a few situations in which we get multiple series returned, and it looks like we're simply missing the case in which a single query will return multiple series. It appears to work as expected in the case of multiple queries. I'm currently mulling over what would potentially be a good way to address this and will update when I have more 😄

**Comment by codeincarnate** [comment]
I've taken a look at this more, per the above we are indeed only handling a case with multiple queries. I'm currently exploring detecting multiple series within the same frame. It looks like right now that we should be able to map multiple series within a frame. I'll update once I have the details figured out.

**Comment by JohnJMartins** [comment]
@codeincarnate Thank you Kyle! Looking forward to updates on this. Please let me know if there is anything else I can do or anything I can clarify!

**Comment by codeincarnate** [comment]
@JohnJMartins I have a draft PR up which should resolve this issue. Time series are being broken out by label and field so that there is one resulting sparkline per combination of data and label. Still need to clean some things up and add an option to preserve some previous behavior. Currently looking like this:

<img width="1616" alt="sparklines" src="https://github.com/grafana/grafana/assets/199847/fb818118-d7c6-4068-8503-2b259e3cdf58">

Hoping to get this merged by the end of the week 😄

**Comment by JohnJMartins** [comment]
> @JohnJMartins I have a draft PR up which should resolve this issue. Time series are being broken out by label and field so that there is one resulting sparkline per combination of field and label. Still need to clean some things up and add an option to preserve some previous behavior. Currently looking like this:
> 
> <img alt="sparklines" width="1616" src="https://user-images.githubusercontent.com/199847/276597488-fb818118-d7c6-4068-8503-2b259e3cdf58.png">
> Hoping to get this merged by the end of the week 😄

Looks awesome! Thanks so much
