### ISSUE TITLE
[Bug] y-axis seconds(s) is displaying duplicate "mean" value instead of precise time

### ISSUE THREAD

**Issue by M-M-M-M** [grafana/grafana#7630]
- Grafana 4.1.2
- datasource : influxdb 1.3
- OS : Linux Centos 7

I have a graph whose y left axis is a time in seconds but some values are duplicated due to lack of precision: 1 min and 1 min instead of 1 min xx s an 1 min yy s

![image](https://cloud.githubusercontent.com/assets/8309818/23165984/02d95554-f83f-11e6-9fbb-0c0434870ce2.png)

![image](https://cloud.githubusercontent.com/assets/8309818/23165991/08e2f55e-f83f-11e6-9573-ff848e90d46d.png)

![image](https://cloud.githubusercontent.com/assets/8309818/23165997/0dbe62ac-f83f-11e6-86dc-0f7c3b12acd9.png)

JSON of the panel is: 

[download-panel.zip](https://github.com/grafana/grafana/files/790179/download-panel.zip)

**Comment by bergquist** [comment]
setting y-max to 120 reproduces this behavior.

**Comment by torkelo** [comment]
This should be fixed in later versions of Grafana
