### ISSUE TITLE
[Feature request] Allow Text to Value mappings in Singlestat panel

### ISSUE THREAD

**Issue by CliveJL** [grafana/grafana#7631]
Please include this information:
- What Grafana version are you using? - 4.1.1
- What datasource are you using? - InfluxDB
- What OS are you running grafana on? - CentOS 7

I'm hoping I'm not missing an existing way of doing this in Grafana... I'd like to be able to use the "Value Mappings" option in the Singlestat panel to do the opposite of what it currently does; i.e. to map a **string** value from a limited set of values in an InfluxDB query to a **numeric** value, and then use that numeric value to change the panel colour using Thresholds based on the "translated" numeric values.

My particular use-case for this is based on monitoring the cluster health status of an Elasticsearch cluster. The Elasticsearch API (GET _cluster/health) returns one of three string values for the cluster health; "green", "yellow" or "red". We use the Telegraf agent with the [[input.elasticsearch]] to feed this data into InfluxDB. If you could assign values such as:

"green" -> 1
"yellow" -> 5
"red" -> 10

Then setting a Threshold of "4,6" would allow the panel background colour to change to match the cluster health status. I appreciate that this may be a limited use, but I thought I'd throw it in here in case anyone else may find it useful. Thanks for a fantastic product by the way!!!

**Comment by lucasrodcosta** [comment]
+1. Would be really nice to have this feature.  
And this could be used in [table panels](http://docs.grafana.org/reference/table_panel/) too.

What do you think about this concept?

![grafana_text_to_value](https://user-images.githubusercontent.com/2574399/26901674-096fc044-4bad-11e7-86ff-dd96aaa5d24f.png)

A new section called "Text to value mapping", that maps string regexes to values.  
Thus, once the texts have been mapped to values, the same logic used to get the colors from the values could be used.

**Comment by torkelo** [comment]
looks interesting

**Comment by zarbis** [comment]
You pretty much designed this with my use case in mind, upvoting it!

**Comment by lucasrodcosta** [comment]
A question: in this approach, a string that doesn't have a mapping, should be mapped to which value?

In other words, in the image attached in [my first comment](https://github.com/grafana/grafana/issues/7631#issuecomment-306927900), the word "blue" (that doesn't matches any of the regexes) should be colored green, yellow or red?

**Comment by Cholsonic** [comment]
+1 lucasrodcosta's concept is essential in my case.   We have fields showing Up / Warning / Down.   I have tried converting these to numerics on the input, but can only colour the values cell (colorising the whole row looks untidy).

Does anyone know how likely this is to go into production?   Or if there is a work around that I can use?

To add my 2 cents:  if it doesn't match a regex it should stay uncoloured - then, if someone wants to change this behaviour - so that a default (no match) string can be 'blue' - they can have a catchall regex.

**Comment by westofariver** [comment]
+1 This would be big value add for my use cases / requirements.

**Comment by Ritesh-Sharma** [comment]
@lucasrodcosta, pretty nicer way of solving this issue ; Could you please tell me what changes i need to make to my current code base of Grafana to achieve this "Text to value mapping" segment.

**Comment by Ritesh-Sharma** [comment]
@lucasrodcosta : Nicer way of solving this issue ; could you please tell me how i can i achieve this for my grafana code base.

**Comment by lucasrodcosta** [comment]
Thanks for all feedbacks! 😃 

@Ritesh-Sharma this feature is not implemented yet.
I just made the HTML/CSS without any logic behind.

I'll try to implement this feature in the next weeks.

**Comment by lucasrodcosta** [comment]
Hi everyone!

I just finished an initial version of this feature for Table panels (see PR #9455).  
Reviews, tests and feedbacks are very welcome!

**Comment by Cholsonic** [comment]
@lucasrodcosta 

[apologies for the n00b question] I am wanting to test them but how can I implement these changes into my environment?   I have tried editing the relevant files manually, but nothing has changed.

Cheers

**Comment by lucasrodcosta** [comment]
@Cholsonic you must rebuild the frontend assets in order to apply the changes.  
You can find the instructions to do it in [README](https://github.com/grafana/grafana#building-frontend-assets).

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.

**Comment by panasaan** [comment]
+1 Text to Value
