### ISSUE TITLE
time-series panel not displaying all data except when zoomed

### ISSUE THREAD

**Issue by AliEbrahimpour** [grafana/grafana#76324]
### What happened?

when I filter the dashboard for 30 days
the dashboard doesn't show all the data but when I zoom the dashboard that I can see the data

### What did you expect to happen?

doesn't show the data

### Did this work before?

I don't know exactly

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.1.4
OS: Linux ubuntu 20.04.6
Browser: chrome
![1](https://github.com/grafana/grafana/assets/25286551/02a0ca34-83c4-4cc2-be8e-1da302bfdcb1)
![2](https://github.com/grafana/grafana/assets/25286551/f3a5b57b-747f-474e-8dd0-858f358209c7)

### Grafana platform?

Other

**Comment by tonypowa** [comment]
hi @AliEbrahimpour 
thank you for creating this issue

could you share more details about:

- your `interval` variable 
- what is the data source

**Comment by AliEbrahimpour** [comment]
Hi, I set the interval to 30 days, but it doesn't provide me with the correct data. However, when I set it to 1 hour, I get the correct data. I am using Prometheus as the data source.
