### ISSUE TITLE
Alerting detects different value than actual value is

### ISSUE THREAD

**Issue by Roberto6969** [grafana/grafana#76322]
### What happened?

Actual value is 160. Alerting firing based on value A0=256.

![image](https://github.com/grafana/grafana/assets/21200507/e75a0175-fdff-47a5-b475-4a98420dbd7f)
![image](https://github.com/grafana/grafana/assets/21200507/d344dea7-5dc6-427d-a609-94053e01b1a4)
![image](https://github.com/grafana/grafana/assets/21200507/649abc63-c3b7-43f2-a993-fdbf717dc72b)

### What did you expect to happen?

Alerting should read correct value 160 and not 256. alert should not be active if value is bellow Threshold

### Did this work before?

So far, this is not always the issue. Usually, alerter shows the same value as actual is.

### How do we reproduce it?

1. Set the threshold to 250
2. Get the actual value 160 in panel 
3. Alert is firing (in my case)

### Is the bug inside a dashboard panel?

Yes, Time series visualization

### Environment (with versions)?

Grafana: Grafana v10.2.0-139518 (28c0fb1cfd)
OS: Windows 10
Browser: Chrome 117.0.5938.150 (Official version) (64-bit)

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment]
hi @Roberto6969 

could you please share more details about your alert? (safely share the query and expressions)

thank you

**Comment by Roberto6969** [comment]
Hi Tony,
here is query: SELECT "AQI" FROM "autogen"."ra_mclimate_aqi" WHERE ("dev_id" = 'cryz355583dld') AND $timeFilter
and picture (threshold is 250):
![image](https://github.com/grafana/grafana/assets/21200507/3bd6e57e-4f0b-469a-9987-43010a5de26d)

Did you mean this?

**Comment by Roberto6969** [comment]
I hope this will help you:

![image](https://github.com/grafana/grafana/assets/21200507/3a371c43-f68e-4867-98b7-a1711aef1f8e)

**Comment by tonypowa** [comment]
could you try to use the `reduce` expression together with `threshold` expression, as your alert condition, instead of the `classic condition`?
![image](https://github.com/grafana/grafana/assets/45235678/60d7bee3-9b29-455c-8fef-e169f9d0368c)
