### ISSUE TITLE
[Bug] /api/search does not return all dashboards

### ISSUE THREAD

**Issue by wleese** [grafana/grafana#7633]
- What Grafana version are you using?
4.1.2

- What did you do?

curl -s "https://grafana/api/search"

- What was the expected result?

Show all dashboards

- What happened instead?

Missing some dashboards

---

So, the above mentioned curl does not return my dashboard. Others seem to be missing too. 

Just as an experiment I checked postgres:

```
grafana=# select count(*) from dashboard;
-[ RECORD 1 ]
count | 942
```

Compared with a curl:

```
 # jq parses json and pulls out all id's, wc -l counts them
curl -s "https://grafana/api/search" | jq .[].id | wc -l
```

This has me very confused. I have differing counts *and* I can find my dashboard in the DB, but the api doesn't return it.

When saving the dashboard with 'Save as', the new one *is* visible.
Here's a diff between the 2:

```
➜  ~/Downloads git:(master) ✗ diff -u broken.json saved_as.json
--- broken.json	2017-02-21 15:08:00.211113258 +0100
+++ saved_as.json	2017-02-21 15:08:06.515010929 +0100
@@ -2,12 +2,11 @@
   "annotations": {
     "list": []
   },
-  "editMode": false,
   "editable": true,
   "gnetId": null,
   "graphTooltip": 1,
   "hideControls": false,
-  "id": 1503,
+  "id": 1906,
   "links": [
     {
       "icon": "external link",
@@ -2276,6 +2275,6 @@
     "type": "timepicker"
   },
   "timezone": "browser",
-  "title": "William logsearch",
-  "version": 179
+  "title": "testing1234",
+  "version": 0
 }
\ No newline at end of file
```

**Comment by torkelo** [comment]
yes, its a search api, it has some limits to number of results it returns. 

https://github.com/grafana/grafana/issues/4468

**Comment by wleese** [comment]
Ouch. This makes the api pretty much useless for people with big deployments..

**Comment by torkelo** [comment]
yea, I know it sucks :( 

paging for the search api would be great, just not had time to implement it and not many who have requested it.
