### ISSUE TITLE
[Bug] Grafana confuses row titles and data when row order changes

### ISSUE THREAD

**Issue by drscre** [grafana/grafana#7634]
Grafana 4.1.1 with Prometheus data source on Ubuntu 16.04

I have a dashboard which has a repeated set of rows with graphs for different hostnames.
When i press "refresh" button or auto-refresh happens, Grafana starts mixing up row titles and corresponding graphs. 

In the video below i periodically press "refresh" button. Sometimes the rows are reordered correctly, sometimes only titles are reordered, sometimes only graphs are reordered:

![my](https://cloud.githubusercontent.com/assets/844519/23171776/8c96cb3a-f864-11e6-95ca-b99b14cb3d15.gif)

**Comment by drscre** [comment]
Version 4.5.2 still has this bug, which makes auto-refresh unusable on our dashboards

**Comment by torkelo** [comment]
the order of your template variable values change. Maybe you have variables that have refresh set to refresh on Time range change? if that is the case order needs to be consistent every time, looking from your screenshot the variable value changes after you refresh the time range.

**Comment by drscre** [comment]
@torkelo 
It's not that variable order changes. The problems is that the row labels stop corresponding to the graphs.

If you look at the screen cast you will see that 
first: the title of the second row changes from the ip-10-0-1-158 to ip-10-01-164 but the metrics graph still remains for ip-10-0-1-158
then: now metrics graph changes, but the row labels don't

It looks like grafana starts mixing up which row labels correspond to which graphs when order of variables changes
