### ISSUE TITLE
Loki: Rename index.ts in monaco-completion-provider directory

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#76374]
**What is the chore?**:
Rename index.ts file and reorganize tests

**Is there anything else we need to know?**:
From: https://github.com/grafana/grafana/pull/76080#discussion_r1352812657

**Comment by shabeebk** [comment]
@gtk-grafana Just wanted to see if this is something open for contribution. If, that is the case, what would you assume the name of this file to be? Would `completionUtils.ts` make sense?

**Comment by gtk-grafana** [comment]
Yes and yes and thank you!

**Comment by shabeebk** [comment]
Created the PR.
