### ISSUE TITLE
Enable configuration of Prometheus exemplars to Azure Monitor App Insights traces

### ISSUE THREAD

**Issue by kayodeprinceMS** [grafana/grafana#76388]
**Why is this needed**:

Allow users to drill down from Prometheus exemplars to App Insights traces, analogous to current support for Prometheus to other trace datasources e.g. Jaeger, Tempo, Zipkin.

**What would you like to be added**:
The Azure Monitor plugin now supports querying and viewing App Insights traces in Grafana native visualizations such as Explore and trace viewer.

This feature would allow users to configure the Prometheus plugin Exemplars to point to Azure Monitor datasource to link App Insights traces. This enables users to find and isolate relevant App Insights traces associated with Prometheus metrics.

**Who is this feature for?**

Full stack, cloud native and DevOps users that need to quickly identify representative traces associated with metric anomaly observed in Prometheus.

cc: @taleena for adding labels.

**Comment by yves-chan** [comment]
To support azure monitor traces as an internal datasource link
1. `"tracing":true` needs to be added as a field https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/azuremonitor/plugin.json
2. The [azure monitor's TracesQueryEditor](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/azuremonitor/components/TracesQueryEditor/TracesQueryEditor.tsx) needs to be able to read the App insights resourceId, and operationId that can be passed from prom exemplar

**Comment by kayodeprinceMS** [comment]
Discussed two options for accessing required App Insights resource ID to pass to trace query.

1. Retrieve AI resource ID from the returned time series label/dimension. In this case, Prometheus plugin would need to pass two values on click in Exemplar Modal, resource ID and trace ID.
2. Require admins to set a single App Insights resource to be used for Exemplar traces in Azure Monitor data source config. Less flexible implementation that's more likely to run into permissions and scale issues.

**Comment by kayodeprinceMS** [comment]
Update from Azure App Insights team on Indexer API call requirements. In near future, Indexer will not require the specific AI resource ID, but any Azure Resource ID would work to query trace details. The best option available in Grafana is to use the Default Subscription ID in the Azure Monitor plugin configuration as the resource for trace queries where only Operation Id is available.

This means no changes will be required in the Prometheus plugin to support drilling down from exemplars to App Insight traces. All changes will be in Azure Monitor plugin to use Default Sub ID when only the Operation ID is passed from the exemplar. There may be some additional UX changes required in the Azure Monitor trace query wizard to require Operation ID if no resource is selected before the query is issued, and default to Trace view in this case instead of Table view.

**Comment by bohandley** [comment]
Thank you @kayodeprinceMS, just returned from vacation, sorry for the delay in response. This is good to hear. So you are saying that Prometheus exemplars only need to have the trace id and the link to App insights?

**Comment by kayodeprinceMS** [comment]
Correct. With the planned changes to the Indexer API, only changes in the Azure Monitor plugin will be required.

**Comment by taleena** [comment]
Closing this as this was implemented in Azure Monitor: https://github.com/grafana/grafana/pull/87742
