### ISSUE TITLE
Explore Content outline follow-up: Traces scroll to top

### ISSUE THREAD

**Issue by harisrozajac** [grafana/grafana#76391]
With the implementation of [Content Outline in Explore](https://github.com/grafana/grafana/pull/74536), the need for scroll to the top button in Trace View with its current functionality becomes obsolete. 

If we consider keeping it, here are the issues that need to be fixed:

- the button is absolutely positioned to the right corner of the window and doesn't work in split mode because it will be displayed only in the right pane
- it scrolls all the way to the top of the screen when it should scroll to the top of the Trace View container. I think it should have a similar behavior as the Logs scroll button, which just scrolls to the top of logs. The point of the scroll to the top in trace view should be to scroll to the top of spans. I think this is the main reason why we would keep the button. 
- it's displayed even when all spans fit the screen

**Comment by harisrozajac** [comment]
@joey-grafana what are your thoughts on this?

**Comment by joey-grafana** [comment]
Honestly I've used the content outline and it works great. It does feel like the scroll to top is no longer needed and can be removed.. or has it already been removed?

**Comment by harisrozajac** [comment]
> Honestly I've used the content outline and it works great. It does feel like the scroll to top is no longer needed and can be removed.. or has it already been removed?

Great, I can work on removing it. It hasn't been removed because I first wanted to discuss it with your team.
