### ISSUE TITLE
alert is not sent when the requirement is meet.

### ISSUE THREAD

**Issue by whc9527** [grafana/grafana#7641]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
  grafana-4.1.2-1486989747
- What datasource are you using?
  influxdb-0.9.6.1-1
- What OS are you running grafana on?
   CentOS release 6.6
- What did you do?
  setting alert in graph using influxdb.
- What was the expected result?
  when the requirement is meet, fire the alert
- What happened instead?
   at my first time to add the alerting it works and send email, but when twenty minutes latter, there is no alert email any more. 
   
**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

Dear all. I met the  problem as this https://github.com/grafana/grafana/issues/6232

the picture is my Grafna screenshot.my script is twenty minutes to collect data, and then inserted into the influxdb.
![image](https://cloud.githubusercontent.com/assets/17898805/23214857/43aee1d6-f94b-11e6-97e4-dd94fa803b64.png)
![image](https://cloud.githubusercontent.com/assets/17898805/23215426/4b76c062-f94d-11e6-8f9f-57e806f14704.png)

![image](https://cloud.githubusercontent.com/assets/17898805/23215378/1735f548-f94d-11e6-951b-a5eedc40afcf.png)

coud anybody can help me.. thx...

**Comment by torkelo** [comment]
Grafana will only send notifications on state transitions, so it will send an alert when going from OK -> Alerting, and when going from Alerting -> OK. 

But it will not continue to send notifications every minute if it stays in Alerting

**Comment by whc9527** [comment]
@torkelo Thank you very much. According to what you said, I tested it, it works all right! thank you very much!

**Comment by srflaxu40** [comment]
Hey, commenting on this - I read what I see about transitions.  I have a Green OK state, and I see alerting in Grafana (I set alert on timeouts as well as no datas) but I don't see an alert in Slack?  It does alert green OK on recovery from the alert..?

**Comment by kirankrishnamurthy** [comment]
Hey, Even I have a similar issue. I am using Grafana 4.4.
I am getting alerts, but when the state comes to normal I am not getting OK. But the dashboard shows green,

![image](https://user-images.githubusercontent.com/31940195/36046689-a1e63c2e-0d8e-11e8-84a3-55406be242f8.png)

**Comment by bhagujava** [comment]
@torkelo 

I am not able to get notification here is my log

````
t=2019-08-28T10:03:21+0000 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/png/C5RK0VYPVEWadU8ntsQJ.png
t=2019-08-28T10:03:21+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email uid=WZmQaDFZk isDefault=true
t=2019-08-28T10:03:21+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[bhargav.patel@gmail.com]
t=2019-08-28T10:03:22+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=37.150 alertId=4 name="Test Notification alert" firing=true attemptID=1
t=2019-08-28T10:03:25+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=3
t=2019-08-28T10:03:31+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler na


````
