### ISSUE TITLE
ServiceAccounts: missing pagination

### ISSUE THREAD

**Issue by mhulscher** [grafana/grafana#76423]
### What happened?

Under Administration > Service Accounts. When the number of items no longer fit on one page, there are no page navigation elements at either the top or bottom of the page. Items that don't fit the first page can only be found by using the search bar.

### What did you expect to happen?

Navigation buttons should appear

### Did this work before?

Don't know

### How do we reproduce it?

Create >100 service accounts

### Environment (with versions)?

Grafana: 10.1.2
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @mhulscher,

Thanks for opening this issue.

Is this happening in the Grafana OSS version or the enterprise one?

**Comment by mhulscher** [comment]
@usmangt I am currently using the enterprise with an active (trial) license.
