### ISSUE TITLE
[Unified alerting] Executing migration failed" id="move dashboard alerts to unified alerting" error="pq: invalid byte sequence for encoding \"UTF8\": 0xd1 0x5f"

### ISSUE THREAD

**Issue by Kot-o-pes** [grafana/grafana#76421]
### What happened?

Hello, we have upgraded our grafana instance from 8.5 to 9.5 and turned on unified alerting, after that we rolled back to old alerting with 
`force_migration = true` flag 
as per https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/ 
now we decided to apply back unified alerting and it fails with error 
```
logger=migrator t=2023-10-12T09:54:12.831869958Z level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="pq: invalid byte sequence for encoding \"UTF8\": 0xd1 0x5f"
logger=migrator t=2023-10-12T09:54:12.831928894Z level=error msg="Exec failed" error="pq: invalid byte sequence for encoding \"UTF8\": 0xd1 0x5f" sql="code migration"
Error: ✗ migration failed (id = move dashboard alerts to unified alerting): pq: current transaction is aborted, commands ignored until end of transaction block
```

### What did you expect to happen?

migration works w/o error

### Did this work before?

- 

### How do we reproduce it?

1. upgrade to unified alerting
2. roll back with force flag 
3. try to apply unified alerting alerting back 

### Environment (with versions)?

Grafana: 9.5.8
OS: Debian

### Grafana platform?

Kubernetes

**Comment by IgorArg** [comment]
Hi! Have the same issie. Can't migrate alerts to u/a after it was rolled back. I migrated and rolled back u/a month ago and now can't migrate it again. Managed to reproduse it at stage env. I tried to solve it by uploading migrated and rolled back db dump  with different values such as: 1. initial instance w/o migration, 2. after migration and rolled back. Nothing is going to work. More than that, Alerting API does not work too, so I even can,t export alerts from broken db to new grafana instance

**Comment by Kot-o-pes** [comment]
> Do you see the same error with legacy alerting enabled?

nope, when legacy alerting is enabled migrations arent happening hence no such errors arise

**Comment by armandgrillet** [comment]
A workaround is to clean up the KV store and alerting tables in the Postgres database. This is probably a leftover from the previous attempt migrating. If there are no leftover, please let us know, but there should be keys with `namespace` `alertmanager` to delete.
