### ISSUE TITLE
Alerting: "Not found" error when trying to edit/view alert rule from Grafana

### ISSUE THREAD

**Issue by peterD4N** [grafana/grafana#76433]
### What happened?

 When I am trying to view/edit alert rule from Grafana:
![image](https://github.com/grafana/grafana/assets/39486971/5ca9a9e3-ddd2-496b-a5e4-9da582b47ee2)

I am getting  `not found` error.

![image](https://github.com/grafana/grafana/assets/39486971/f0cebe61-9348-4562-a789-e91414f8c8af)

From Grafana debug log:
`2023-10-10 09:13:33.814	
127.0.0.1 - USER [10/Oct/2023:07:13:33 +0000]  404 "GET /prometheus/config/v1/rules/agent/abc-builders/builders-api-builders/27188a03-ee35-4aa9-85cc-773cb12acd27/abc-builders.builders-api-builders?subtype=mimir HTTP/1.1" 19 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0" "-"`

When I tried manually supply `/` with `%2F` API request worked:
`2023-10-10 09:14:55.374	
127.0.0.1 - USER [10/Oct/2023:07:14:55 +0000]  200 "GET /prometheus/config/v1/rules/agent%2Fabc-builders%2Fbuilders-api-builders%2F27188a03-ee35-4aa9-85cc-773cb12acd27/abc-builders.builders-api-builders?subtype=mimir HTTP/1.1" 674 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0" "-"`

### What did you expect to happen?

View/Edit possibility from Grafana alerting page.

### Did this work before?

I think it worked when we didn't use multi tenancy.

### How do we reproduce it?

1. Use Mimir as datasource in Grafana.
2. Push alerts via Grafana to Mimir.
3. Use Azure as a storage for Mimir
4. In Grafana agent we use flow mode setup with default setup for mimir.rules.kubernetes. With [default configuration](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/#:~:text=%E2%80%9C-,agent,-%E2%80%9D) agent prefix is added in namespace

### Environment (with versions)?

Grafana: `10.1.1 `
Mimir: `5.1.0`
Grafana agent: `0.25.0`
OS: `AKS` 
Browser: `Chrome`

### Grafana platform?

Kubernetes

**Comment by VLZZZ** [comment]
We're experiencing the same issue with the single tenant installation.

```
Grafana: 10.1.2
Mimir: 5.1.2
Grafana agent: 0.37.4
```

**Comment by sigurdfalk** [comment]
@konrad147 @soniaAguilarPeiron any updates on progress on this one? 🙏🏻

**Comment by sigurdfalk** [comment]
@gotjosh Any news on this one? 🙏🏻

**Comment by peterD4N** [comment]
Bumping Grafana to the latest version `v10.4.1` seems helped.
