### ISSUE TITLE
Alerting: Copying alerts no longer works

### ISSUE THREAD

**Issue by evgenymarkov** [grafana/grafana#76435]
### What happened?

When I'm trying to copy an alert, the UI shows an error:

> Data source configuration is not available for "grafana" data source

https://github.com/grafana/grafana/assets/16443248/22b18282-4ee2-4e8d-8676-d70efbf2192d

### What did you expect to happen?

I expect the alert edit form to open

### Did this work before?

Yes, it worked in version 9.x

### How do we reproduce it?

1. Open alert page https://grafana.avride.ai/alerting/grafana/:uuid/view
2. Click "Copy"

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.4
OS: macOS Ventura 13.6
Browser: Chrome 117

### Grafana platform?

Kubernetes

**Comment by evgenymarkov** [comment]
I found that bug appears in [this function](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/unified/state/actions.ts#L77-L85).

The dataSources object in the Redux state is not always populated. In particular, if you access the alert page through a folder or directly, the dataSources object is always empty.

If you go to the alert page from the page https://grafana.avride.ai/alerting/list, then copying works because, probably, on this page there is a request for information about date sources.

**Comment by soniaAguilarPeiron** [comment]
Thank you so much @evgenymarkov for the catch!
Taking a look 👀

**Comment by soniaAguilarPeiron** [comment]
We fixed in this [commit](https://github.com/grafana/grafana/pull/76016/commits/fb67da381c5069c040d7f59383babec2359230d8) . So if you update your version to the latest you will see that the error is gone. Thanks anyway!

**Comment by soniaAguilarPeiron** [comment]
I'm going to close the issue. In case you find something more, please let us know.
