### ISSUE TITLE
[Feature Request]: Type-ahead templating query 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7644]
Template variable of type query currently fetches values on dashboard load or on time range change. There is no option to load it on demand as you type in the variable value select dropdown. 

Problems that need to be solved:
* metricFindQuery needs to be extended to take filter string
* What value does the variable have initially (on Dashboard Load), what is All value?

**Comment by shalstea** [comment]
+1

**Comment by euanmacinnes** [comment]
Perhaps have a second query to define the default value on dashboard load?
