### ISSUE TITLE
[Bug] External link with templating variables not working correctly

### ISSUE THREAD

**Issue by SNoof85** [grafana/grafana#7645]
Please include this information:
- What Grafana version are you using? => 4.1.2
- What datasource are you using? => graphite 0.10.0
- What OS are you running grafana on? => SLES 12 SP2
- What did you do? => Create dashboard with templating variable (only 1) and add an external link with $var for url
- What was the expected result? => A link to http://<variable_value>
- What happened instead? => A link to http://**%7B**<variable_value>**%7D**

As i'm getting metrics from several proxmox HV to graphite then to grafana, i was trying to add on my dashboard an external link to the proxmox web interface. My dashboard uses templating to switch between my HV, it could be very nice if the templating var could be re-used in the external link URL. It's kinda working except the variable value has "%7B" in the beginning and "%7D" in the end. So link if out of order.
Same on play.grafana.org.
Tested on latest stable Chrome browser.

**Comment by bergquist** [comment]
Seems to work fine for me. http://play.grafana.org/dashboard/db/link-using-template-variable?editview=templating&var-uri=http:%2F%2Fwww.dn.se&var-part=www.dn.se

**Comment by SNoof85** [comment]
I see, but i use graphite query to get values of my variable. Not custom vars as you tested, i just be able to reproduced on play.grafana.org on dashboard : http://play.grafana.org/dashboard/db/graphite-panel-repeats with adding a link with value : http://$server

**Comment by bergquist** [comment]
Yea. I recreated this bug and saved the dashboard.

**Comment by SNoof85** [comment]
Trying to understant what's happening, i can't reproduce the bug in my test env...and neither with another variable than $server on the dash http://play.grafana.org/dashboard/db/graphite-panel-repeats

**Comment by luongvo209** [comment]
@SNoof85  How do you fix the bug?

**Comment by jb4415** [comment]
I'm using Grafana 5.1.4 and am experiencing this issue.

I have a dashboard that has a repeating panel based on a multi value variable, and I want to be able to drill down on the node displayed by the individual panel, but the "{" and "}" characters are being added to the URL

How can I pass the value of the current panel to a drill-down URL
