### ISSUE TITLE
[bug] GPG key signiature is invalid for RPM packages for versions <4.1.2

### ISSUE THREAD

**Issue by tomhaynes** [grafana/grafana#7647]
Issue information:
- What Grafana version are you using?
<4.1.2
- What datasource are you using?
N/A
- What OS are you running grafana on?
Centos 7
- What did you do?
Attempted to downgrade to v3.0.5
- What was the expected result?
Successful installation
- What happened instead?
Install failed with:
`The GPG keys listed for the "grafana repo" repository are already installed but they are not correct for this package.`

I can see that the Signature is different for the latest RPM:
```
rpm -qi grafana-4.1.2-1486989747
Signature   : RSA/SHA1, Tue 14 Feb 2017 09:44:03 AM UTC, Key ID 8c8c34c524098cb6
```

```
rpm -qi grafana-3.0.4-1464167696
Signature   : RSA/SHA1, Wed 25 May 2016 09:19:27 AM UTC, Key ID 30a3d7723dd18bdd
```

Would it be possible to re-release the older versions with the new signature, please, as currently we cannot install them without relaxing the GPG-check.

**Comment by torkelo** [comment]
We switched PGP signing key for 4.1.2, it's unfortunate but we had to do it, you should be able to ignore that warning and still install the old version
