### ISSUE TITLE
Prometheus: Promqail UI Fixes

### ISSUE THREAD

**Issue by catherineymgui** [grafana/grafana#76493]
**What is this?**

Updating the PromQL + AI suggestor drawer to match the Figma designs and have a better user experience

**Fixes**

- [ ] Middle align the label and name of the metric

<img width="409" alt="Screenshot 2023-10-12 at 12 30 06" src="https://github.com/grafana/grafana/assets/5264102/37b24cc7-0636-46f1-b345-6bbb3e2304c0">

- [ ] Align the 'Choose new metric', 'Use', And 'Give Feedback' buttons to be 16px from the right

<img width="233" alt="Screenshot 2023-10-12 at 12 43 02" src="https://github.com/grafana/grafana/assets/5264102/2031af62-a25a-4f70-a5b4-eabd5ee1231d">

- [ ] Right now the drawer automatically scrolls down when someone expands the explanation. This should be an exception (no auto scroll) as it can be jarring, especially since the text is animated in. There also tends to be no auto scroll when the explanation has been expanded before. 

https://github.com/grafana/grafana/assets/5264102/40aa633e-7780-4e6d-a4b0-dd41e365cab2

- [ ] The explanation button has 12px padding under it for _historical queries_, but not for suggested queries. Add 12px to suggested queries

<img width="590" alt="Screenshot 2023-10-12 at 12 58 02" src="https://github.com/grafana/grafana/assets/5264102/901fdcb2-fa5d-4a72-ad86-4e876e574149">

- [ ] Should we add a dot after these numbering?

<img width="251" alt="Screenshot 2023-10-12 at 13 00 22" src="https://github.com/grafana/grafana/assets/5264102/2b924144-9e5a-4b12-91a7-e012099827e7">

**Comment by bohandley** [comment]
> #1 Middle align the label and name of the metric

The most up to date version of bohandley/prometheus-promqail-frontend has these as middle aligned.

https://github.com/grafana/grafana/assets/25674746/8b67430f-eb06-40c2-a626-d882839106a6

all other things are addressed in the[ PR here ](https://github.com/grafana/grafana/pull/76654)
