### ISSUE TITLE
Installing SSL certificate in Grafana

### ISSUE THREAD

**Issue by shunmugavel2609** [grafana/grafana#7650]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? grafana-3.1.1
- What datasource are you using? Influx
- What OS are you running grafana on? Linux
- What did you do?  
# Installing ssl certificate in Grafana
Edited --config=/etc/grafana/grafana.ini 

# Protocol (http or https)
#;protocol = http
;protocol = https

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
#;http_port = 3000
#;http_port = 80
;http_port = 443

# https certs & key file
;cert_file = /usr/share/grafana/conf/file.cert
;cert_key = /usr/share/grafana/conf/file.key

- What was the expected result? 
SSL certificate installed.

- What happened instead?
after editing the grafana.ini file. Despite restarting the server. Its still starting back on OLD default port 3000. and ssl certificate was not installed 

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
You need to uncomment the settings, that is remote the starting semi colon

**Comment by shunmugavel2609** [comment]
Can you elaborate ?. 

I did the ps -ef on the server.

[server ~]$ ps -ef|grep -i "grafana"
47740    11224 10828  0 09:45 pts/0    00:00:00 grep -i grafana
grafana  18873     1  0 Feb16 ?        00:00:55 /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins

But to what ever changes that i do to /etc/grafana/grafana.ini, grafana restart its not picking up the changes ?

Command that we use to Stop and start the server.

To stop the service:

ps -ef|grep -i “grafana"
Kill the process with grafana as process id.

Or execute:
 sudo service grafana-server stop

To start the service.
 sudo service grafana-server start

**Comment by shunmugavel2609** [comment]
https://github.com/grafana/grafana/issues/7650

Can you please elaborate ?.

I did the ps -ef on the server.

[server ~]$ ps -ef|grep -i "grafana"
47740 11224 10828 0 09:45 pts/0 00:00:00 grep -i grafana
grafana 18873 1 0 Feb16 ? 00:00:55 /usr/sbin/grafana-server
--pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini
cfg:default.paths.data=/var/lib/grafana
cfg:default.paths.logs=/var/log/grafana
cfg:default.paths.plugins=/var/lib/grafana/plugins

But to what ever changes that i do to /etc/grafana/grafana.ini, grafana
restart its not picking up the changes ?

Command that we use to Stop and start the server.

To stop the service:

ps -ef|grep -i “grafana"
Kill the process with grafana as process id.

Or execute:
sudo service grafana-server stop

To start the service.
sudo service grafana-server start


- Sam

**Comment by LaurentDumont** [comment]
I'm pretty sure he means removing the ";" before the config line. Not just the "#"

**Comment by srikanta50** [comment]
@torkelo , 

first i have created csr file using openssl command which created 2 file one is server_name.csr & server_name.key. Then i submitted server_name.csr file to CA authority to get those signed. And now i have ca signed certificated with me (Server, intermediate and Root).  while i am configuring this as below is not working. how to do this setup now?
cert_file = /etc/grafana/crt/Server.crt(CA signed certificate)
cert_key = /etc/grafana/server_name.key(this one is first file that i created using openssl command ). 
I really need your help here, please suggest.

**Comment by yashh08** [comment]
Hi 

If anyone can help me with this, Because I am getting the err "Cannot find the SSL cert_file at "given_path/cert_file.CRT".

After installing Grafana, I have C:\Program Files\GrafanaLabs\grafana
So where exactly I should keep the cert and key file?

**Comment by richad1** [comment]
> @torkelo ,
> 
> first i have created csr file using openssl command which created 2 file one is server_name.csr & server_name.key. Then i submitted server_name.csr file to CA authority to get those signed. And now i have ca signed certificated with me (Server, intermediate and Root). while i am configuring this as below is not working. how to do this setup now?
> cert_file = /etc/grafana/crt/Server.crt(CA signed certificate)
> cert_key = /etc/grafana/server_name.key(this one is first file that i created using openssl command ).
> I really need your help here, please suggest.

Hi, 

I have also followed the same steps. However, I am still able to see the certificate shows still not valid. When I check it using openssl command it shows as below:
verify error:num=20:unable to get local issuer certificate
verify return:1
verify error:num=21:unable to verify the first certificate
verify return:1

did you find any solution to your problem?
