### ISSUE TITLE
Bug: setting up development environment. 

### ISSUE THREAD

**Issue by kaushiksriram100** [grafana/grafana#7651]
When setting up the development environment on my MAC i get this error: 
What am I missing? 

L-SNVJ0NCFFT-M:grafana skaush1$ go run build.go setup
Version: 4.2.0-pre1, Linux Version: 4.2.0, Package Iteration: 1487798871pre1
go get -v github.com/kardianos/govendor
go install -v ./pkg/cmd/grafana-server
github.com/grafana/grafana/pkg/api
# github.com/grafana/grafana/pkg/api
../../grafana/grafana/pkg/api/http_server.go:55: undefined: http.ErrServerClosed
../../grafana/grafana/pkg/api/http_server.go:61: undefined: http.ErrServerClosed
../../grafana/grafana/pkg/api/http_server.go:74: hs.httpSrv.Shutdown undefined (type *http.Server has no field or method Shutdown)
exit status 2
exit status 1
L-SNVJ0NCFFT-M:

**Comment by utkarshcmu** [comment]
Is your golang version 1.8?

**Comment by kaushiksriram100** [comment]
its - 1.7.5
L-SNVJ0NCFFT-M:grafana$ go version
go version go1.7.5 darwin/amd64
L-SNVJ0NCFFT-M:grafana$

**Comment by kaushiksriram100** [comment]
worked after upgrade. closing this now.

**Comment by garceri** [comment]
Shouldn't the readme be updated with the Golang > 1.8 Requirement ?

**Comment by daniellee** [comment]
@garceri where in the docs are you seeing something else than Golang 1.8?

http://docs.grafana.org/project/building_from_source/#dependencies

**Comment by garceri** [comment]
@daniellee , i'm so embarrased, i had the same issue while compiling telegraf and i posted this to the wrong project issues page.

**Comment by daniellee** [comment]
@garceri don't worry about it. Just wondering if we had some documentation that was out of date.
