### ISSUE TITLE
[Bug] elastic search data source does not work in chrome

### ISSUE THREAD

**Issue by bmurphy1976** [grafana/grafana#7652]
We are trying out Grafana v4.1.2 (official Docker image) and noticed a weird problem.  We created an Elastic Search data source (with ssl + basic authentication) that works fine in Firefox but doesn't work in Chrome.  

The Elastic Search graphs show "Request Error" instead of any data and when I try to sniff the network traffic I see the http requests to _msearch returning a 403. 

Here's a failing request from Chrome:

```
Request:

Request URL:https://grafana.SNIP.com/api/datasources/proxy/2/_msearch
Request Method:POST
POST /api/datasources/proxy/2/_msearch HTTP/1.1
Host: grafana.SNIP.com
Connection: keep-alive
Content-Length: 469
Accept: application/json, text/plain, */*
Origin: https://grafana.SNIP.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: https://grafana.SNIP.com/dashboard/db/bryan-test-dashboard
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: _oauth2_proxy=Ym11cnBoeUBtZWRpYWZseS5jb20=|1487795561|iDZjnQUChVry9ojbFWGqUvWWUW4=; grafana_sess=b07ede01674c5846

Response:

HTTP/1.1 403 Forbidden
Content-Type: text/plain; charset=utf-8
Date: Thu, 23 Feb 2017 01:09:52 GMT
Server: nginx
Content-Length: 0
Connection: keep-alive

```
And here's a succeeding request from Firefox:

```
Request:

Request Url: https://grafana.SNIP.com/api/datasources/proxy/2/_msearch
Request Method: POST
Host: grafana.SNIP.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://grafana.SNIP.com/dashboard/db/bryan-test-dashboard
Content-Type: application/json;charset=utf-8
Content-Length: 509
Cookie: did=E1E111EB058832EE864678EBBF6BC08B0097048995C9C16803F540FBB7DE286EC0095775F55E4C5B84C35E3219A8A24AA50888CE15AF910D505A5430634A30B719984EAB74260C79F50A9A424B0D74010DE9498237F957E2C39EA31FB074A84FE926D093178260145556046330B8BACE03A95275C5BDD8C264DD31FBCDABBEDEDB24DA7376731BBE3F7E73E66B6CE7DADC66C4D4; _ga=GA1.2.552613247.1486655631; _oauth2_proxy=Ym11cnBoeUBtZWRpYWZseS5jb20=|1487795012|YG8s6QRZaRiTNzYFXRdGh58aUAI=; grafana_sess=d0912a990c8d01d0
DNT: 1
Connection: keep-alive

Response:

Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Thu, 23 Feb 2017 01:04:13 GMT
Server: nginx
Transfer-Encoding: chunked
```

**Comment by torkelo** [comment]
works here, strange. No idea what could cause this. Seems to be related to the auth setup you have around ES

**Comment by bmurphy1976** [comment]
Not that this helps much, but who knows.  Here are the nginx logs from our TLS wrapper:

```

**Comment by torkelo** [comment]
Any update on this? 

is withCredentials checked in your data source settings?

**Comment by bmurphy1976** [comment]
Yes, withCredentials is checked.  Still the same behavior, although I have not upgraded Grafana since I created this issue.  I'm leaving for vacation in 48 hours so I won't have time to check a newer version for a couple weeks.

**Comment by daniellee** [comment]
What version of ElasticSearch are you using?

Found this: https://discuss.elastic.co/t/got-403-forbidden-with-chrome-user-agent/52812
and this related issue: https://github.com/elastic/elasticsearch/issues/18878

If you do a curl with the chrome user agent as they do in the issue linked above, what result do you get then?

**Comment by bmurphy1976** [comment]
```
"version": {
    "number": "5.1.1",
    "build_hash": "5395e21",
    "build_date": "2016-12-06T12:36:15.409Z",
    "build_snapshot": false,
    "lucene_version": "6.3.0"
}
```
I ran the query against our elastic search end point, I had to remove the timeout and ignore_unavailable parameters as it did not like those (400 bad request).  I get what appears to be a valid response:

```
$ curl -u 'SNIP' -v 'https://elasticsearch.SNIP.com/_mget?preference=1465897339430' -H 'origin: https://elasticsearch.SNIP.com' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5)' -d '{"docs":[{"_index":".kibana","_type":"config","_id":"4.5.1"}]}' | jq .
* TCP_NODELAY set
* Connected to elasticsearch.SNIP.com (54.243.39.90) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.SNIP.com
* Server certificate: Go Daddy Secure Certificate Authority - G2
* Server certificate: Go Daddy Root Certificate Authority - G2
* Server auth using Basic with user 'SNIP'
> POST /_mget?preference=1465897339430 HTTP/1.1
> Host: elasticsearch.SNIP.com
> Authorization: Basic SNIP
> Accept: */*
> origin: https://elasticsearch.SNIP.com
> user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5)
> Content-Length: 62
> Content-Type: application/x-www-form-urlencoded
>
} [62 bytes data]
* upload completely sent off: 62 out of 62 bytes
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 24 Mar 2017 14:20:46 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 76
< Connection: keep-alive
< Access-Control-Allow-Origin: https://elasticsearch.SNIP.com
<
{ [76 bytes data]
* Curl_http_done: called premature == 0
100   138  100    76  100    62    260    212 --:--:-- --:--:-- --:--:--   260
* Connection #0 to host elasticsearch.SNIP.com left intact
{
  "docs": [
    {
      "_index": ".kibana",
      "_type": "config",
      "_id": "4.5.1",
      "found": false
    }
  ]
}
```

**Comment by daniellee** [comment]
When comparing the requests for Chrome and Firefox, I noticed that the cookie values are different. The Chrome cookie has an oauth key. Have you logged in with oauth on chrome and with a db user on Firefox?

**Comment by bmurphy1976** [comment]
Grafana is protected by an oauth2 proxy, but the elastic search api is protected by basic auth and is hosted at a different DNS name.

I just tried on firefox right now, it may have been a copy/paste error in my original comment because the firefox requests do include the oauth cookie.

**Comment by torkelo** [comment]
So is there anything Grafana can do differently here? Seems to be an issue with your auth setup and how cookies across domains work differently in chrome and firefox

**Comment by jeannos** [comment]
I had exactly the same issue.

After looking at it for quite bit, it seems that Chrome adds a 'Origin' header whereas Firefox does not.

This Origin header makes the call to _msearch return a 403

Since we have a haproxy in front, we nuked the header using:

 http-request del-header Origin

and it worked... The 403 no longer happens

I believe this is an issue on the grafana server end at the proxy level.

In the grafana configuration,
enforce_domain = false

**Comment by torkelo** [comment]
How is this an issue in Grafana?

**Comment by torkelo** [comment]
The enforce domain option is totally unrelated :)

**Comment by silviot** [comment]
This is a problem with the Elasticsearch configuration.

The URL you use to access grafana should be allowed in the `http.cors.allow-origin` setting in the `elasticsearch.yml` config.

Something like:

> http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?|https?:\/\/grafana\.example\.com(:[0-9]+)?/

OR (not recommended) you can disable CORS checks:

> http.cors.enabled: false
