### ISSUE TITLE
Bug - InfluxDB source graph unable to list all hosts with regex filter predicate 

### ISSUE THREAD

**Issue by wongster80** [grafana/grafana#7653]
- What Grafana version are you using?
4.1.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
CentOS 7.1

- What did you do?
Create a graph with the following query.
SELECT mean("err_in") FROM "3_month"."net" WHERE "host" =~ /^vert-prod-node*/ AND "interface" = 'bond1' AND $timeFilter GROUP BY time($interval), "host" fill(null)

- What was the expected result?
Complete graph with all hosts displayed for the metric.

- What happened instead?
Incomplete set of hosts are displayed on the graph

**Comment by steverweber** [comment]
I'm also hitting this bug. some things to note ... when setting the fill mode to none its seems to show more hosts...

**Comment by steverweber** [comment]
also I haven't yet confirmed if its an issue with influxdb or grafana.

influxdb seems to have a few closed bugs with regex in subject.
https://github.com/influxdata/influxdb/milestone/62?closed=1

perhaps the 1.2.1RC has a fix

**Comment by steverweber** [comment]
might be somewhat related.
https://github.com/influxdata/influxdb/issues/8050

**Comment by torkelo** [comment]
closing this as it's related to InfluxDB (regex filtering is done by InfluxDB)

**Comment by wongster80** [comment]
When I run the query in influxdb directly all the hosts displays but it isn't in Grafana.  Can someone look into it please?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/7380

you can fix this by increasing `max-row-limit`

**Comment by steverweber** [comment]
confirmed. bumping `max-row-limit` by * 10 /fixed/ the issue.

i don't understand why influxdb would only part of the result over an error.. this is going to generate issue reports.

**Comment by wongster80** [comment]
Thanks guys, I can also confirm increasing max-row-limit fixed the issue

**Comment by Brightside56** [comment]
For me - not
