### ISSUE TITLE
[Bug] select template variable cause duplicative query

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7654]
Please include this information:
- What Grafana version are you using?
  - 73830a44fe391ce62efd2a3cf33022fc56403a8b
- What datasource are you using?
  - Prometheus, CloudWatch
- What OS are you running grafana on?
  - MacOS
- What did you do?
  - Create template variable (multi select off)
  - Create graph with the template variable
  - change the selection, redraw graph
- What was the expected result?
  - Only once query
- What happened instead?
  - Duplicative query

**Comment by mtanda** [comment]
In Grafana 4.1.1, I can't reproduce this.

**Comment by bergquist** [comment]
We checked this before pushing.. 

And I cannot repro.
I just created a new dashboard with one panel and one query and I only get one datasource call.

**Comment by bergquist** [comment]
Im going back in git history to find it.
This issue was present in 2c68c071c00c37ab4ab42ba8a6d5cd318881389b

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/e73b306e0ccb7cbce1753f9f3015f38772e03429

**Comment by mtanda** [comment]
Thanks!
