### ISSUE TITLE
Alerting: Cannot find panels from certain dashboards

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#76557]
### What happened?

When editing an alert, Grafana 10 has the option to link it to a panel through the button `Link dashboard and panel`.

In the search page, some dashboard do not show any panels.

### What did you expect to happen?

To see panels from the dashboards

### Did this work before?

N/A

### How do we reproduce it?

1. Edit alert
2. Click on `Link dashboard and panel`
3. Click on a few dashboards (that surely have panels)
4. Notice for some dashboards, no panels are listed

### Environment (with versions)?

Grafana: 10.1.1
Browser: Chrome 117

### Grafana platform?

Kubernetes

Example dashboards: https://gist.github.com/gtirloni/5264eef6c1abd513f8be9e5d41f35f1c

**Comment by tonypowa** [comment]
hi @gtirloni 

thank you for opening this issue

i have trouble importing the dashboards. Can you please name the panels that are not listed? I am wondering if there is a chance that none of them are compatible for alerts

**Comment by gtirloni** [comment]
> Can you please name the panels that are not listed?

From the dashboard where panels are not listed, one panel that doesn't show: `CPU Throttling`

What makes a panel compatible for alerts?

Please let me know if you need any other info.

**Comment by tonypowa** [comment]
>CPU Throttling

what type of panel is it? (e.g.time-series, table panel etc)

here is one example of a panel that does not support alerts

https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/#annotation-and-alert-support

**Comment by gtirloni** [comment]
Time-series.

**Comment by tonypowa** [comment]
thank you @gtirloni 

Since I could not copy your dashboards from your repo, could you copy and paste this time-series panel named "CPU Throttling" using the panel --> more --> get help workflow in the panel's dropdown menu?
