### ISSUE TITLE
perSecond doesn't display

### ISSUE THREAD

**Issue by dolphinsboy** [grafana/grafana#7656]
Gafana Version：grafana-3.0.1
DataSource: Graphite-0.10
OS: Linux4.4.8-20. 46.amzn1.x86_64
Expected result: perSecond function for the total metric 

Question: use perSecond doesn't display any graph.

My Query is:
aliasByNode(sortByName(perSecond(mysql.ads.3500.m.*.*.com_select), 'true'), 6)

This feature is running ok before, but today wrong.

**Comment by dolphinsboy** [comment]
## perSecond run ok 
![image](http://pic.027cgb.cn/20170205/20172239692053794775.png)

## select lastest 30min, it doesn't display
![image](http://www.freep.cn/ads/outcalling.aspx?u=http://pic.027cgb.cn/20170205/20172236411290357780.png) 

## The problem is using perSecond

![image](http://pic.027cgb.cn/20170205/20172232661484720467.png)

**Comment by torkelo** [comment]
strange, must be an issue with graphite, as that function is executed by graphite. Not sure why it stopped working for you. Maybe ask in mailing list for Graphite or Grafana. Check graphite logs
