### ISSUE TITLE
Feature request: Explore from a panel in a new tab

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#76562]
The current "[Explore from a panel](https://grafana.com/docs/grafana/latest/explore/#start-exploring)" feature looks like this:

![Screenshot 2023-10-13 08-58-54 explore from panel](https://github.com/grafana/grafana/assets/3270755/864e3c08-5259-4c4c-9c61-89542947b3bb)

The Explore documentation for this feature says (emphasis added):

> Alternately to start with an existing query in a panel, choose the Explore option from the Panel menu. **This opens an Explore tab** with the query from the panel and allows you to tweak or iterate in the query outside of your dashboard.

There are two things that I would like to change in this feature:

* The keyboard shortcut was previously 'x'. This has changed to 'p x'. I prefer 'x' because it is one less keystroke, and 'p x' requires two hands to type on a QWERTY keyboard.
* I would like the ability to open Explore in a new tab. The Explore item in the panel menu is not a link, therefore it's not possible to right-click to open the link in a new tab. I would like the default behavior to open Explore in a new tab, even when I use the 'x' shortcut.

**Why is this needed**:

* I **always** want to go back to the dashboard when I am finished with my Explore session.
* [I love tabs](https://alexandre.deverteuil.net/post/organize-firefox-tabs/).
* When I am dashboarding, I have my right hand on the mouse button, and I use my left hand to open panel editors with the 'e' key. I also want to use my left hand to hit the 'x' key, instead of having to make multiple clicks or two-handed key strokes to open Explore.

**What would you like to be added**:

[Add a brief description of what the feature or enhancement should do.]

**Who is this feature for?**

Power users.

**Comment by Elfo404** [comment]
cmd+click (or ctrl+click) now works as expected, it was probably a regression in your specific version. 

as of the shortcuts, we had to align the explore shortcut with other panel related actions, we don't have any plans on changing it unfortunately.

Closing this issue as there are not actionable items left, feel free to comment if you want us to take a second look.

**Comment by GlacierWalrus** [comment]
I have a suggestion which you're welcome to ignore if you don't value it:

Situation:
When I'm debugging a misbehaving panel, I might be in the middle of modifying the query, and get back no results (say I added a label filter which was incorrect for some reason)

I know want to debug it, and the only thing I know to do atm is to open the explore mode.

Current ux:
1. Edit panel query, panel breaks
2. Click explore
3. Get prompted with "Do you want to save your changes?" "cancel/discard/save"
** frustration point **: I don't want to do any of these, I just want to access the explore view, but now I'm blocked by a modal which adds an extra step to my flow and resets me to the beginning

Suggested change:
If the panel is in a dirty state, the explore button changes to "open explore in new tab" or maybe a fictitious split or something else, such that I don't get to that modal.

Reason:
I think the change I'm suggesting is "natural behaviour". I've used grafana for close to decade and I still get caught by this super regularly.


I thing debugging panel queries in general is a bit use unfriendly, but I understand that those kinds of things aren't priority features. Let me know if you have suggestions to improve my workflow if I'm doing something wrong here.
