### ISSUE TITLE
Data Links: works for "Time series" but not for "State timeline" panels

### ISSUE THREAD

**Issue by lecriquet38** [grafana/grafana#76563]
### What happened?

Dear developper, 

I have manage to put a static data link to a "Time series" panel.
It works because one can do a left click on a value.

However, when I use a "State timeline" panels, one can not do a left click on a value.

 Am I doing it wrong ?

I have looked over the internet and I found other users having the same problem :
https://community.grafana.com/t/state-timeline-data-link-for-drill-down-to-details-for-the-event/54959

### What did you expect to happen?

I expect, when I do a left click on a "State timeline" panel, to have the same behavior than with the "Time series" panel, that is to say a window shows the possibility to click on the predefined static link, as you can find in the attachement.

![image](https://github.com/grafana/grafana/assets/87651448/01755e98-d74d-46d1-84b0-4b8bd846d27b)

### Did this work before?

Nope

### How do we reproduce it?

1. Open a "State timeline" panel
2. Edit panel
3. Go to the "Data Links" option
4. Click on the " + Add link" Button
5. In Title, put : static_link_giphy_is_life
6. In URL, put : https://giphy.com/
7. Click on th "Apply" button and save the dashboard
8. Try to left click in the "State timeline" panel => nothing appear.
![image](https://github.com/grafana/grafana/assets/87651448/911c8abd-4a8b-4b2f-b193-566565d87e54)

If you make the same steps with the "Time series" panel, a window appears with the link as you can see in the attachement

### Is the bug inside a dashboard panel?

Sorry, I could not find that ...

### Environment (with versions)?

Grafana: 8.5.20
OS:         my OS is windows 10
Browser: Chrome Version 117.0.5938.92 (Official Build) (64-bit)

I think Grafana is managed using a Paas.

### Grafana platform?

I don't know

### Datasource(s)?

Nope

**Comment by usmangt** [comment]
Hi @lecriquet38,

Thanks for opening this issue.

Grafana's current latest stable version is 10.1.x and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).
