### ISSUE TITLE
ACTIVE DIRECTORY INTEGRATION

### ISSUE THREAD

**Issue by troyygan** [grafana/grafana#7657]
I am using grafana 4.1 on centos 6.8. Can someone help me with the integration to active directory. I'm having a hard time finding on how to set up properly the configuration. Also is there a plug in for active directory? Thanks

**Comment by joelittlejohn** [comment]
@troyygan These two links should help:

http://docs.grafana.org/installation/ldap/
https://github.com/grafana/grafana/issues/2505

**Comment by troyygan** [comment]
Thanks @joelittlejohn. So I need to set up first an LDAP. I thought there's an easy way like plug-in for active directory on Grafana. :)

**Comment by torkelo** [comment]
Active Directory supports LDAP protocol so there is a "plug-in", but you have to configure it by specifying your active directory options in grafana config file ldap.toml

**Comment by troyygan** [comment]
@torkelo 

I'm a lil bit confuse. Do I still need to set up an LDAP for AD integration for Grafana? Thanks

**Comment by torkelo** [comment]
You need to configure the ldap auth yes

**Comment by troyygan** [comment]
Ok. So I don't need to set up another LDAP service on my linux box. I just need to enter the required directives on the ldap.toml (ldap config files). I.e, 

# Ldap server host (specify multiple hosts space separated)
host = < Active Directory IP >
# Default port is 389 or 636 if use_ssl = true
port = 389

Can you confirm? Thanks

**Comment by torkelo** [comment]
Correct

**Comment by troyygan** [comment]
Hi @torkelo 

I need your help. Below is the current settings on my grafana.ini

#################################### Auth LDAP ##########################
[auth.ldap]
;enabled = true
;config_file = /etc/grafana/ldap.toml
;allow_sign_up = true


After restarting the grafana seems that the ldap authentication is still disable.

![ldap](https://cloud.githubusercontent.com/assets/16662446/23527735/1254ea80-ffd2-11e6-9536-dbc79106e624.JPG)

**Comment by torkelo** [comment]
remove the `;` at the start of the line, those comment out lines

**Comment by troyygan** [comment]
@torkelo 

Thank your for this. I was able to  enable the ldap auth and I can see from logs that Grafana is connecting to AD, actually the information of AD user is now visible on grafana logs however there was an error. See below.

t=2017-03-03T16:13:07+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=2 orgId=1 uname= error="UNIQUE constraint failed: user.email"
