### ISSUE TITLE
[Bug] Cloudwatch source not showing graph when using multiple template variables

### ISSUE THREAD

**Issue by toote** [grafana/grafana#7658]
## What Grafana version are you using?
v4.0.2

## What datasource are you using?
Cloudwatch

## What OS are you running grafana on?
Ubuntu

## What did you do?

Create a dashboard with two template variables:
* `elb`: dimension_values(us-east-1,AWS/ELB,RequestCount,LoadBalancerName)	
* `az`: dimension_values(us-east-1,AWS/ELB,RequestCount,AvailabilityZone)

Create a graph panel with the following configuration:
![screen shot 2017-02-23 at 18 24 10](https://cloud.githubusercontent.com/assets/4922352/23279766/542d55ec-f9f5-11e6-9f51-aae9fc49256d.png)

## What was the expected result?

A multi-line graph with one series per ELB per AZ.

## What happened instead?

Nothing. No errors in the console, nothing. If one of the two template variables is removed from the configuration, the graph works just fine.

**Comment by torkelo** [comment]
Can you open chrome dev tools, network tab,  look at request sent to Cloudwatch and copy paste it here?

**Comment by k0nserv** [comment]
We also see this problem with a single variable combined with a string e.g `LoadBalancerName: CommonPrefix-$LoadBalancer`

**Comment by mtanda** [comment]
`CommonPrefix-$LoadBalancer` is not expanded correctly in 4.1.1.
And, `CommonPrefix-[[LoadBalancer]]` is not supported in 4.1.1.
Not sure, but https://github.com/grafana/grafana/pull/7649 support `[[variable]]`, it may solve some of issues.
Please try nightly build.

**Comment by toote** [comment]
@torkelo thanks for your quick reply. I am proxying requests through grafana itself (to make use of IAM roles) and the request shown in the network tab includes the following information:

```json
{  
   "region":"us-east-1",
   "action":"GetMetricStatistics",
   "parameters":{  
      "namespace":"AWS/ELB",
      "metricName":"RequestCount",
      "dimensions":[  
         {  
            "Name":"LoadBalancerName",
            "Value":"XXX"
         },
         {  
            "Name":"AvailabilityZone",
            "Value":"{us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e}"
         }
      ],
      "statistics":[  
         "Sum"
      ],
      "startTime":1487944089,
      "endTime":1487947689,
      "period":60
   }
}```

**Comment by seanclerkin** [comment]
I'm also seeing this issue on the latest nightly.

**Comment by torkelo** [comment]
Cloudwatch api does not appear to support multi valued values that the Grafana templating system requires.
