### ISSUE TITLE
Grafana plugins: If a plugin has the wrong target architecture, no error will be reported in the UI

### ISSUE THREAD

**Issue by DonCamillo72** [grafana/grafana#76597]
### What happened?

The Grafana UI shows no error on plugins installed with the wrong target architecture.
Only the console log shows an error:
`logger=plugin.loader t=2023-09-25T10:31:06.28955146+02:00 level=error msg="Could not start plugin" pluginId=grafana-mqtt-datasource err="fork/exec /var/lib/grafana/plugins/grafana-mqtt-datasource/gpx_mqtt_linux_arm64: no such file or directory"`

### What did you expect to happen?

The UI should report that the plugin is installed in the wrong target architecture.

### Did this work before?

I don't know. I tested this behavior only with version Grafana v10.1.2 

### How do we reproduce it?

1. Install Grafana v10.1.2 on linux amd64 and linux arm64 device
2. Install a Grafana plugin with specific target architecture e.g. [MQTT plugin ](https://grafana.com/api/plugins/grafana-mqtt-datasource/versions/1.0.0-beta.3/download?os=linux&arch=amd64) on the linux amd64 device 
3. Transfer the plugin folder to the linux arm64 device
4. Restart Grafana on linux arm64 device
6. In the Grafana console log the error is logged as: 
`logger=plugin.loader t=2023-09-25T10:31:06.28955146+02:00 level=error msg="Could not start plugin" pluginId=grafana-mqtt-datasource err="fork/exec /var/lib/grafana/plugins/grafana-mqtt-datasource/gpx_mqtt_linux_arm64: no such file or directory"`
7. In the UI the MQTT plugin is marked as installed but no error is reported

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana:  v10.1.2 
OS: Ubuntu Core 22
Browser: Google Chrome Version 117.0.5938.150

### Grafana platform?

A downloaded binary

**Comment by tolzhabayev** [comment]
@DonCamillo72 it is correct and currently a known behaviour, I will keep this in our project as feature request and something we can improve in the future.

**Comment by andresmgot** [comment]
This has been improved by this https://github.com/grafana/grafana/pull/85960

Now there ir an error message with more details about the error. For this specific case, it will show:

![image](https://github.com/grafana/grafana/assets/4025665/cf41ca9d-9286-4946-aef0-0f83af92e156)

This will be available in Grafana 11.1 and onwards.
