### ISSUE TITLE
[Bug] Snapshots of graphs with annotations fail to render (HTTP 401)

### ISSUE THREAD

**Issue by alexzorin** [grafana/grafana#7659]
> What Grafana version are you using?

 Grafana v4.1.2 (commit: v4.1.2) 

> What datasource are you using?

InfluxDB

> What OS are you running grafana on?

CentOS 6.x

> What did you do?

1. Create a local snapshot of a graph with annotations on it (e.g. from alerting)
2. Open in a browser with no Grafana session (e.g. incognito/private browsing)

> What was the expected result?

Snapshot should be rendered on screen

> What happened instead?

Blank graph, "Annotations Failed" alert window, "HTTP Error (401) Unauthorized"

![1](http://i.imgur.com/B8x2Dwk.png)

![2](http://i.imgur.com/tIkkH6U.png)

**Comment by torkelo** [comment]
thanks for reporting this, seems to be an issue with annotations and snapshots.

**Comment by bortek** [comment]
I am having the same issue here and the same error message. I am on ver4.1.1. Is this fixed in 4.2.2 ?
