### ISSUE TITLE
[Bug] - InfluxDB source graph unable to list all hosts with regex filter predicate

### ISSUE THREAD

**Issue by wongster80** [grafana/grafana#7660]
What Grafana version are you using?
4.1.2

What datasource are you using?
InfluxDB

What OS are you running grafana on?
CentOS 7.1

What did you do?
Create a graph with the following query.
SELECT mean("err_in") FROM "3_month"."net" WHERE "host" =~ /^vert-prod-node*/ AND "interface" = 'bond1' AND $timeFilter GROUP BY time($interval), "host" fill(null)

What was the expected result?
Complete graph with all hosts displayed for the metric.

What happened instead?
Incomplete set of hosts are displayed on the graph

When I run the query in Influxdb directly all the hosts displays but it isn't in Grafana.  Can someone look into it please? 
This looks like a Grafana issue.

Displaying the CPU stats for 5 hosts:
![screen shot 2017-02-23 at 4 43 12 pm](https://cloud.githubusercontent.com/assets/1155156/23285649/6c2eede4-f9e7-11e6-8418-699c8860ff5b.png)

Displaying the Mem stats for 5 hosts:
![screen shot 2017-02-23 at 4 43 49 pm](https://cloud.githubusercontent.com/assets/1155156/23285676/929dafc4-f9e7-11e6-851f-584f512324a4.png)

Displaying the CPU and Mem stats for 5 hosts, expecting 10 graph lines, only seeing 6:
![screen shot 2017-02-23 at 4 43 33 pm](https://cloud.githubusercontent.com/assets/1155156/23285698/ae7ab516-f9e7-11e6-9832-5e9788ffae29.png)

**Comment by torkelo** [comment]
This is due to a breaking change in InfluxDB 1.2, https://github.com/grafana/grafana/issues/7380

you can fix this in by increasing InfluxDB option  max-row-limit
