### ISSUE TITLE
[Bug] toggle edit mode did not escape / of templates

### ISSUE THREAD

**Issue by hzhaop** [grafana/grafana#7661]
- What Grafana version are you using?
4.0
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 6
- What did you do?
I toggle the edit mode and do some complex sql query with templates including '/' character.
- What was the expected result?
the '/' character should be escaped and query influxdb
- What happened instead?
It didn't escape '/' and raise syntax error from influxdb

**Comment by torkelo** [comment]
can your provide more info? 

* Template variable options and current value
* Your InfluxDB query

**Comment by hzhaop** [comment]
For example, I have a template variable option $t and its value is "/api/put"
My influxdb query is 
select mean(some_metric) from "some_measurement" where "some_tag" =~ /^$t$/ and time > 1487865600s and time < 1487952000s GROUP BY another_tag;

The acturla query is 
select mean(some_metric) from "some_measurement" where "some_tag" =~ '/^/api/put/' and time > 1487865600s and time < 1487952000s GROUP BY another_tag;
and raise syntax error because '/' was not escaped.

The expected query is 
select mean(some_metric) from "some_measurement" where "some_tag" =~ '/^\/api\/put/' and time > 1487865600s and time < 1487952000s GROUP BY another_tag;

If I disabled the toggle edit mode, everything worked normal as the query matched the expected query. But if I enabled the toggle edit mode, it didn't.

**Comment by torkelo** [comment]
Is multi value enabled for template variable? 

Try updating to latest Grafana

**Comment by ysfseu** [comment]
I am using grafana 5.3.0. There is still this problem? Is there any workaround?
