### ISSUE TITLE
Unknown state : 'no_data'

### ISSUE THREAD

**Issue by BoByUkn** [grafana/grafana#76619]
### What happened?

After the migration from grafana 9.5.13 to 10.1.5, we don't have alerts in the main dashboard  "Error Alert" wich is an alert list. We don't understand why we have not data in our dashboard.

Error: "  Unknown state : 'no_data'  "

Screenshot:
![Capture d'écran 2023-10-16 135909](https://github.com/grafana/grafana/assets/102911790/8aba1aab-7066-4976-bf2a-57c00ffdf15c)

In "grafana.log" file I have this kind of log but it's not very revelant.

logger=context userId=14 orgId=1 uname=xx@xx.xx t=2023-10-16T14:01:59.554900328+02:00 level=error msg="unknown state 'no_data'" error="unknown state 'no_data'" remote_addr=xx.xx.xx.xx traceID=

### What did you expect to happen?

Some help with this issue and i want to know how i can fix it.

### Did this work before?

9.5.13, just before the migration

### How do we reproduce it?

1.migration 9.5.13 to 10.1.5
2.actualize main dashboard (alert list)
3.get the error " Unknown state : 'no_data' "

### Is the bug inside a dashboard panel?

Yes and it's an alert list dashboard.

### Environment (with versions)?

Grafana: 10.1.5
OS: Ubuntu 22.04
Browser: Brave

### Grafana platform?

A downloaded binary

**Comment by keomabrun** [comment]
Hi @BoByUkn, how did you resolve this ? I am running Grafana version 10.2.2 and I'm still having a similar issue, just with a different text: "unknown state 'execution_error'".

**Comment by schoentoon** [comment]
We've had the same execution_error on grafana 10.2.2. Turns out the dashboard where we got this had a panel in it showing currently active alerts. A source type that no longer exists in this version of grafana. Removing this panel solved it. It's likely something similar that you're encountering.

**Comment by keomabrun** [comment]
Thanks ! It worked indeed ! :pray:
