### ISSUE TITLE
Grafana can now set permissions for a person so that he can only see some dashboard

### ISSUE THREAD

**Issue by whc9527** [grafana/grafana#7662]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
   grafana-4.1.2-1486989747
- What datasource are you using?
   influxdb-0.9.6.1-1
- What OS are you running grafana on?
   CentOS release 6.6
- What did you do?
   Grafana can now set permissions for a person so that he can only see some dashboard？

I used the way nginx + lua, combined with auth.proxy authentication method, made a third party certification. Now the boss wants to control permissions for some graphs.  Grafana can now set permissions for a person so that he can only see some dashboard？

**Comment by torkelo** [comment]
no, that is currently not implemented.

https://github.com/grafana/grafana/issues/2132

https://github.com/grafana/grafana/issues/1611

**Comment by whc9527** [comment]
@torkelo  谢了， thank you very much!
