### ISSUE TITLE
"Could not view rule" for alert rules provisioned via Grafana-Agent flow mode

### ISSUE THREAD

**Issue by trexx** [grafana/grafana#76628]
### What happened?

I have Grafana Agent configured like so to load in any PrometheusRules added via GitOps:
```
      mimir.rules.kubernetes "local" {
        address = "http://infra-mimir-ruler:8080"
        tenant_id = "infrastructure"

        rule_namespace_selector {
          match_labels = {
            "kubernetes.io/metadata.name" = "grafana-ops",
          }
        }
        rule_selector {
          match_labels = {
            "grafana_agent" = "true",
          }
        }
      }
```
I can see the rules are loaded, visible, and evaluated in Grafana. When I attempt to dig deeper in to a specific alert, I am hit with an error and 404.

I get these errors when attempting to click on the "View alert rule" in the "Alerts" panel in a dashboard, and also when I click on the view button (the eye) in the Alert rules screen.
```
grafana logger=context userId=2 orgId=1 uname=some-user t=2023-10-16T13:14:42.220235142Z level=error msg="404 page not found\n" error="404 page not found\n" remote_addr=some-ip traceID=

grafana logger=context userId=2 orgId=1 uname=some-user t=2023-10-16T13:14:42.2219728Z level=info msg="Request Completed" method=GET path=/api/ruler/GazPBQB4z/api/v1/rules/agent/grafana-ops/coredns-forward/6cfef514-5766-4de4-9a36-407de1f1916c/coredns_forward status=404 remote_addr=some-ip time_ms=5 duration=5.417232ms size=47 referer="https://some-domain/alerting/Mimir%20(Infrastructure)/cri%24Mimir%20(Infrastructure)%24agent%1Fgrafana-ops%1Fcoredns-forward%1F6cfef514-5766-4de4-9a36-407de1f1916c%24coredns_forward%24CoreDNSForwardLatencyHigh%241378505054/view?returnTo=%2Falerting%2Flist" handler=/api/ruler/:DatasourceUID/api/v1/rules/:Namespace/:Groupname
```

### What did you expect to happen?

That I can see the details of that particular alert rule such as queries, labels, etc.

### Did this work before?

First time setting this up.

### How do we reproduce it?

1. Deploy Grafana, Mimir, and Grafana Agent (Configure it to to load PrometheusRules in to Mimir) in a Kubernetes cluster.
2. Setup a data source to Mimir where managed alerts are enabled.
3. Deploy a PrometheusRule in the cluster to be discovered by Grafana-Agent
4. The rule should then be discoverable, but viewing the details of the alert rule will cause a 404.

### Is the bug inside a dashboard panel?

Unlikely

### Environment (with versions)?

Grafana: v10.1.5
OS: Windows
Browser: Edge Chromium

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by trexx** [comment]
> @trexx First question: do you have several Grafana agents from different clusters attacking a single tennant on Grafana Mimir's Ruler?

Nope. I only have one instance of the grafana agent running on a single cluster. None running elsewhere.

**Comment by achetronic** [comment]
If you attack from several grafana agents, uploading prometheusrules, don't forget to set the prefix in the agent component for PrometheusRules. If not, they will be overriden each time some of them upload their rules from the clusters

**Comment by trexx** [comment]
Thanks, I'll keep that in mind. But for my case where I only have 1 Grafana Agent doing this provisioning, any idea what it could be?

**Comment by achetronic** [comment]
> Thanks, I'll keep that in mind. But for my case where I only have 1 Grafana Agent doing this provisioning, any idea what it could be?

No, sorry, let's wait for others 🙏🏼

**Comment by rodrigoccaldas23** [comment]
Hello @trexx,
I am facing the same issue. If I click on the eye icon I get a 404 with this message, and I if I try to edit, it displays “ruler not supported”.
Any ideas?
![image](https://github.com/grafana/grafana/assets/48653110/83a4bd60-5efa-4864-ad8d-d83ca5dafb7e)

**Comment by trexx** [comment]
Hey @rodrigoccaldas23 

Thanks for chiming in. Unfortunately I still have the same issue.
As I am using Mimir, I do see a 404 when attempting to view the rule in Grafana on the Nginx Gateways.

`404 "GET /prometheus/config/v1/rules/agent/grafana-ops/metallb-metallb/e7eaf7b1-e4a9-43d8-b7ba-98c077f42d4c/bgp?subtype=mimir HTTP/1.1" 19 "-" "Grafana/10.2.2" "-"`

Might have something to do with it.

Are you also using Mimir?

**Comment by trexx** [comment]
My current hunch is that when viewing the rule, Grafana does not pass on the Tenant, resulting in a 404.

**Comment by trexx** [comment]
I got it.

Grafana needs to escape the slashes.

`curl -H "X-Scope-OrgID: tenant" localhost:8080/prometheus/config/v1/rules/agent%2Fgrafana-ops%2Fmetallb-metallb%2Fe7eaf7b1-e4a9-43d8-b7ba-98c077f42d4c/bgp?subtype=mimir`

**Comment by rodrigoccaldas23** [comment]
I am also using mimir. 

I have those 404 errors on Nginx:
![image](https://github.com/grafana/grafana/assets/48653110/59d8cc66-e639-4413-a208-1761ab245907)

Yes, nice catch! I sent a curl on my grafana pod `curl -H "X-Scope-OrgID: metamonitoring" http://mimir-ruler.mimir.svc:8080/prometheus/config/v1/rules/agent%2Fmimir%2Fmimir-alerts%2Fb2f3975c-09cc-4d18-a3ec-843eb8cfda4c/alertmanager_alerts?subtype=mimir` and it returned the rule.

One million dollar question, how to workaround/fix this? :)

**Comment by rodrigoccaldas23** [comment]
Updated for grafava v10.2.2 but still the same issue:
`10.244.29.41 - - [28/Nov/2023:14:22:14 +0000]  404 "GET /prometheus/config/v1/rules/agent/mimir/mimir-alerts/b2f3975c-09cc-4d18-a3ec-843eb8cfda4c/gossip_alerts?subtype=mimir HTTP/1.1" 19 "-" "Grafana/10.2.2" "-"`

**Comment by trexx** [comment]
Actually, you might be able to alter Mimir's Nginx configuration to escape the slashes at request time until a proper fix is in place. I'll likely take that approach.

**Comment by trexx** [comment]
No use I'm afraid. Nginx doesn't make it as easy as I thought.
It either normalises the url, or sends a redirect back to Grafana which will fail.

This is as far as I got.

```
        location ~ /prometheus/config/v1/rules/agent/ {
          set $ruler infra-mimir-ruler.grafana-mimir.svc.cluster.local;
          rewrite ^ $request_uri;
          rewrite ^/prometheus/config/v1/rules/(.+)/(.+)/(.+)/(.+)$ /prometheus/config/v1/rules/$1%2F$2%2F$3/$4$is_args$args break;
          return 400;
          proxy_pass      http://$ruler:8080/$uri;
        }
```

**Comment by rodrigoccaldas23** [comment]
We also tried a similar workaround with nginx, but no success.
Maybe we need here an input from someone from Grafana...

**Comment by eric-engberg** [comment]
Would be nice to get some traction on this.  Also have the same problem obviously.  This should be affecting everyone I'd think

**Comment by eric-engberg** [comment]
Though this brings up another question.  I'd like to link back from a slack message to the alert in grafana.  The URL seems to contain the filename of the alerts.  I'm assuming there's no way to generate a proper link back to the alert from alertmanager templates?

Should I open a ticket for a feature request of sorts?

**Comment by ObserveLite** [comment]
can anyone tell me how to connect the grafana-agent to mimir because i tried i couldn't do it by documentation and there is no videos about grafana mimir configuration and grafana agent ..  i have installed the agent in static mode and grafana mimir  in my aws ubuntu instance (in same machine)

agent.yaml

server:
  log_level: info

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 60s
    remote_write:
    - url: http://127.0.0.1:9009/api/v1/push
    
  
integrations:
  node_exporter:
      enabled: true
    

 please help me i have been trying to connect almost five days );
<img width="932" alt="git" src="https://github.com/grafana/grafana/assets/149372161/f376fc94-65c3-482c-83e6-2ab0ec6f51cb">

**Comment by emirisman** [comment]
I have also encountered this issue and would be really nice if #80504 makes it as soon as possible :)

**Comment by trexx** [comment]
Looks like as of Grafana 10.3.1, I can access alert details. @rodrigoccaldas23 how about you?
