### ISSUE TITLE
[Feature request] Make $interval available in Prometheus template "query" field

### ISSUE THREAD

**Issue by brian-brazil** [grafana/grafana#7664]
Due to the evaluation model of Prometheus, topk() and friends don't work as expected as they're per step rather than across the whole graph. If we could have an expression like "topk(rate(metric[$interval]), 5)" that'd allow us to select the relevant timeseries via templating, and then graph them.

This should probably only work with the On Time Range Change setting.

**Comment by mtanda** [comment]
I try to use this, and it seems to works.

The query string is `query_result(topk(5,rate(http_request_duration_microseconds_count[$interval])))`.

I can use `$interval` template variable in the templating query.

**Comment by brian-brazil** [comment]
That's not working for me, the $interval remains uninterpolated. Tried with 4.1.2.

**Comment by bspradling8** [comment]
Did you create a templating variable of type `Interval`? I created a variable of type `Interval` and called it `interval`. My issue is that I would like to get the current time range as an interval for my query, but it seems that in the template variable, the lowest step you can have is 2 which divides the current time range in half which I don't want. Is it possible to make this 1 or have another way to get the entire time range as a variable?

**Comment by mtanda** [comment]
@bspradling8 I want it too.

I added Feature request for supporting step=1.
https://github.com/grafana/grafana/issues/7685

**Comment by torkelo** [comment]
Both the built in variables $__interval and $__interval_ms  now work in the prometheus query editor

**Comment by torkelo** [comment]
sorry , reopening, this was for templating

**Comment by syepes** [comment]
Most necessary feature, currently its not really possible to have TOPN graphs :-(

**Comment by loicoudot** [comment]
👍 
`$_interval` is great for `query_range` request but for instant `query` only the start time is specified by Grafana. We need `$__range` variable to make instant `query` possible. For exemple, for the simplest query : 'number of request received in the selected interval time selectionned' we could write something like:
`sum(increase(http_request_count{job='gateway'}[$__range]))`

Personnaly, i've patch Grafana to add `$__range` variable by adding this line of code in the file `datasource\prometheus\datasource.ts`:

```typescript
    // Adjust the interval to take into account any specified minimum and interval factor plus Prometheus limits
    var adjustedInterval = this.adjustInterval(interval, minInterval, range, intervalFactor);
    var scopedVars = options.scopedVars;
    scopedVars["__range"]= {text: range+"s", value: range+"s"};  // <-- new line
    // If the interval was adjusted, make a shallow copy of scopedVars with updated interval vars
    if (interval !== adjustedInterval) {
      interval = adjustedInterval;
```

I know it's not enough for a pull request (need documentation and completion code) but it definitevely make Grafana usable with Prometheus.

**Comment by FUSAKLA** [comment]
It would be great to have also `$__range_ms` the same way the `$__interval_ms` is also available, if the `$__range` would be added.

**Comment by davkal** [comment]
Rough plan:

* the DS function that serves results to the variable service is `metricFindQuery()`
* it does not have access to any dashboard or panel options, hence any interval needs to be either set in the datasource options or be calculated from scratch (using time service range and a fixed resolution)
* cant really reuse interval logic in `createQuery()` since that is very panel/target dependent.
* extract interpolation logic into its own function for testing
* add interval and range, plus their _ms cousins to scoped vars
