### ISSUE TITLE
Font Size for Bar Charts

### ISSUE THREAD

**Issue by cellmechanic** [grafana/grafana#76653]
**Why is this needed**:

Trying to display bar charts on a playlist dashboard, on a tv, and you can't change the fonts of labels making it extremely hard to read the data on a screen.

**What would you like to be added**:

Make it possible to change the font size for the bar chart axis labels.

**Who is this feature for?**

Anyone that wants to be able to read the charts from a distance, like by putting them on a tv screen.

**Comment by leeoniya** [comment]
have you considered using horizontal bar gauges that have font scaling?

https://play.grafana.org/d/KIhkVD6Gk/4-gauges?orgId=1&refresh=10s

**Comment by cellmechanic** [comment]
I had not, but I'm playing around now and it looks like what I want thanks!

**Comment by adela-almasan** [comment]
@cellmechanic I'm closing this issue as it seems you made it work. Please feel free to reopen or create a new issue if you have more questions. Thank you!
