### ISSUE TITLE
Public dashbord dark mode

### ISSUE THREAD

**Issue by oscni** [grafana/grafana#76663]
**Why is this needed**:

My eyes are burning when looking on a 50" monitor ;)

**What would you like to be added**:

Option when publishing a public dashboard in either light or dark mode

**Who is this feature for?**

Everyone who not wears sunglasses

**Comment by evictorero** [comment]
We are tracking this Feature request in this [issue](https://github.com/grafana/grafana/issues/62387).
In the meantime, you can change your theme default preferences in `Administration -> Default preferences`.
The public dashboard will use the theme defined there or, if the option `System preference` is selected, the public dashboard will use your OS preference.

**Comment by evictorero** [comment]
[Duplicate](https://github.com/grafana/grafana/issues/62387)
