### ISSUE TITLE
Unable to View Azure Event Grid in Azure Monitor Datasource.

### ISSUE THREAD

**Issue by MayurCXone** [grafana/grafana#76665]
### What happened?

We are unable to get the azure event grid default topic in datasource (Azure Monitor), however when we create custom topic event grid option for custom topic is visible.

### What did you expect to happen?

Event Grid default topic should be visible like all other Azure resources.

### Did this work before?

It is working in Azure Managed grafana according to Azure support.

### How do we reproduce it?

We have followed all the steps mentioned in link https://grafana.com/docs/grafana/latest/datasources/azure-monitor/. 

### Environment (with versions)?

Grafana: Grafana v8.3.2,
OS: server deployed on linux distribution,
Browser: accessing on Microsoft Edge.

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
Hi @MayurCXone, would you be able to provide more detail on the query you're attempting to run? Screenshots and detaills of the resources will help us identify the issue. Thanks!

**Comment by MayurCXone** [comment]
Hello @aangelisc, 
Sure.

we have a Azure Storage account in which we have a resource group with resources like storage blob, event grid, etc.
we have created datasource with help of Azure Support Team : https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-self-managed-grafana-azure-active-directory

we successfully configured Azure using Azure Monitor as datasource in Grafana,
we are able to query every resources in all our subscription, however we are unable to query "Event Grid Default Topic",
as we were de-bugging with Azure Support for errors from their side it turned out we can monitor "Event Grid Custom Topic"
in that same Azure Monitor datasource but not default topic.

let me check with Team, if I can share screenshot for reference.

Thanks!

**Comment by alyssabull** [comment]
Hey @MayurCXone - is there any update on this issue?

**Comment by MayurCXone** [comment]
Hi @alyssabull, No and the issue still persists, I am attaching the query, what's missing is that in ResourceType, options should include "Event Grid Default Topic", The role assigned to datasource has Full Reader Permission.
![image](https://github.com/grafana/grafana/assets/98597954/b67cda51-cb70-44f9-8ddb-16a4438195ad)

Let me know if more specific information required!

**Comment by alyssabull** [comment]
Hi @MayurCXone - upon looking into this further this issue should have been fixed in [this PR](https://github.com/grafana/grafana/pull/77308/files) for v10.3.2. If you upgrade Grafana this issue should be fixed. Thanks!

**Comment by alyssabull** [comment]
Closing this issue as it is fixed with [this PR](https://github.com/grafana/grafana/pull/77308/files).
