### ISSUE TITLE
[Bug] grafana singlestat panel shows random value for different time interval

### ISSUE THREAD

**Issue by vcraescu** [grafana/grafana#7667]
I have singlestat panel that display a value of a gauge. The value is displayed correctly for Time Range: Today. 

![alt text](https://i.stack.imgur.com/jrBFG.png)

However, If I change the time range to yesterday the panel shows a very large value.

![alt text](https://i.stack.imgur.com/397B5.png)

 Have no idea how it computes such a value since all the values are around 1900 figure. I'm using graphite as a datasource and I'm pretty sure I send the correct values. Retention policy is configured like this:

> retentions = 10s:1d,5m:365d,1h:5y

I'm using Grafana 3.0.4 with Graphite datasource on Ubuntu 16.

Max data points is set to 100. I tried with different values but still getting very large values.

**Comment by torkelo** [comment]
It probably due your retention rules, when you look at past data, if it's a count metric it gets summed, so you have apply functions like scaleToSeconds to get the per second metric  independent of rollup period
