### ISSUE TITLE
[Screencast request] what's new in Grafana 4.0 screencast

### ISSUE THREAD

**Issue by msanitariusz** [grafana/grafana#7668]
Please record a screencast "what's new in Grafana 4.0" as you have done for [2.0](https://www.youtube.com/watch?v=FC13uhFRsVw&list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&index=3) and [3.0](https://www.youtube.com/watch?v=1kJyQKgk_oY&list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&index=8) releases.
[Those screencast](https://www.youtube.com/watch?v=mgcJPREl3CU&list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2) are great and really helpful, we've found few thing in the screencast that we had overlooked while reading the "what's new in Grafana" section in the documentation.

**Comment by torkelo** [comment]
yes, would love to do a couple more screencasts

**Comment by torkelo** [comment]
You can checkout the Videos from GrafanaCon:

GrafanaCon 2016: Torkel Odegaard, The Launch of Grafana 4.0 and Native Alerting 
https://www.youtube.com/watch?v=B16Za773OuE&index=3&list=PLDGkOdUX1Ujp_6OnJ8M-t59eGPs0rZF4Q

GrafanaCon 2016: Torkel Odegaard, Grafana 4 Features Demo Session 
https://www.youtube.com/watch?v=jfUb8pGERrg&index=22&list=PLDGkOdUX1Ujp_6OnJ8M-t59eGPs0rZF4Q&t=981s
