### ISSUE TITLE
[Feature request] Display counter increment in table plugin

### ISSUE THREAD

**Issue by Thibo-Abidbol** [grafana/grafana#7669]
I would like to add to the table plugin the ability to display the increase of a counter (taking into account counter resets). 
Let's say I want to display the total number of HTTP request to a webserver in a table panel, based on an `http_request` counter. The metric is a monotonic increasing counter that can be reset when the server reboot. In this case, the total number of resquest is simply the value of the counter at the end of the period minus the value of the counter at the beginning of the period. When the counter is reset, the drop should not be taken into account.

**Comment by torkelo** [comment]
calculating counter deltas is the responsibility of the query execution backend (TSDB query). Graphite, Elasticsearch, OpenTSDB, Prometheus, InfluxDB etc all have ways to calculated the rate (derivative) from an increasing counter.
