### ISSUE TITLE
[Feature Request] Add the possibility to add custom external links to the login page.

### ISSUE THREAD

**Issue by shad1w** [grafana/grafana#7671]
In some cases, external links need to be added to the login page of the application.

An example for this is linking to a privacy policy, which is required by the law in some (although few) countries.

**Comment by daniellee** [comment]
This is part of the white labeling feature in Grafana Enterprise: https://grafana.com/docs/grafana/latest/enterprise/white-labeling/

We won't be adding any more white-labeling features to open source Grafana (too much maintenance and is very much an enterprise feature).
