### ISSUE TITLE
Auto-generate: Improve custom feedback edge case handling

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#76729]
Given the capability to provide custom user input / feedback to the AI there are numerous edge cases we will probably want to handle - especially in the case / eventuality where customers are using keys provided / managed by Grafana for this functionality.

One example edge case is overriding the description (and I imagine title) character limit, resulting in a description essay / increased API usage
<img width="559" alt="really long description" src="https://github.com/grafana/grafana/assets/22381771/bbe196cf-51be-465f-be5c-26b355038aa9">

**Comment by ivanortegaalba** [comment]
We won't prioritize this for now until we see users misbehaving. There are plenty of ways to break OpenAI
