### ISSUE TITLE
Feature Request  -The Secrity Issues About Grafana

### ISSUE THREAD

**Issue by KingOfDragon** [grafana/grafana#7672]
A role of vistor can not update my data! But in the version of grafana 2.6.0,  a user who have not sign in my system can modify row of dashboards .
 
![image](https://cloud.githubusercontent.com/assets/25999939/23348041/c168f398-fce1-11e6-8354-4da5153870be.png)
![image](https://cloud.githubusercontent.com/assets/25999939/23348050/cb7d7340-fce1-11e6-9d0e-a9cfe34711b0.png)

If a man visit my grafana through Ip:port, he directly into the login screen would be great.
ps:English id not my mother tongue, Please excuse my grammatical mistake.

LOOKING　FORWARD TO YOUR REPLY.

**Comment by torkelo** [comment]
you must have enabled anonymous access http://docs.grafana.org/installation/configuration/#auth-anonymous

**Comment by KingOfDragon** [comment]
Thank you for solving my problem!
