### ISSUE TITLE
Auto-generate: Update panel + dashboard description character limits

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#76727]
While reviewing features it seems like the current 140 character limit for descriptions is a little too restrictive.

Update panel description character limit to 250, and consider removing dashboard description character limit altogether (if after testing that doesn't produce good results maybe consider 300-500 characters) 🤷‍♂️ 

The limit is provided as part of the prompt in the respective genAI button components

**Comment by natydej** [comment]
We could probably use 500 characters for the max length of the general text and 250 for the shorter one if we are going to use a shorter description as default - to avoid waiting time for users.
