### ISSUE TITLE
If we can have multiple grafana windows open at the same time to look at dashbord on different organization

### ISSUE THREAD

**Issue by grantzhanghao** [grafana/grafana#7673]
Hi guys,

We want to use one userid and password to have multiple grafana windows open at the same time,
then visit different dashbord on different organization. But after we opened the second windows and opened dashbord, then refreshed the first dashbord, it got error (message: "Dashboard not found").

Welcome your comment.

version: 3.1.1

**Comment by joakimberglund** [comment]
[4.2](https://github.com/grafana/grafana/blob/master/CHANGELOG.md) solves that issue .

_Orgs: Sharing dashboards using Grafana share feature will not redirect to correct org. #1613_

**Comment by torkelo** [comment]
Using Multiple Orgs at the same time is not supported and will likely never be.
