### ISSUE TITLE
Alerting: Remove patch for the history package

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#76744]
We added a fix + patch in history to fix a wrong encoding when url contains % characters.

**Context:**  
https://github.com/grafana/grafana/pull/76148/files#diff-d39aa8bb5f5c32177ba0cef60b1277b58288013d5d2ac2daaa68930771e4c350R251-R256,

We need to update to the latest versions as the versions we are using for history and react-router are not being maintained from long time ago and don't receive any security bug fixes. 

Once we update with the right versions of `react-router` and `history`, we should revert this patch and fix.

**Comment by Clarity-89** [comment]
@soniaAguilarPeiron you can now use the `useParams` and `useLocation` hooks from the `react-router-dom-v5-compat` package, which should allow you to remove the patch.

**Comment by soniaAguilarPeiron** [comment]
Thanks @Clarity-89 !
