### ISSUE TITLE
Make variable filter line stick when scrolling

### ISSUE THREAD

**Issue by deanmax** [grafana/grafana#76745]
**Why is this needed**:
When scrolling the window, for lots of time I want to change the variable filter for a certain panel that are down below in the dashboard. It's very inconvenient in this case that I have to scroll back to the top and change the variable dropdown, and then scroll back down again to the panel I want to see.  It would be nice if this variable filter bar thing can stick when I scroll the window.
<img width="1724" alt="Screenshot 2023-10-12 at 11 05 44" src="https://github.com/grafana/grafana/assets/3320547/d2946951-c28d-4861-a2ac-bb953c578c5d">

**What would you like to be added**:

The variable filter bar thing can stick when I scroll the window.

**Who is this feature for?**

Everyone can benefit.

**Comment by evictorero** [comment]
Duplicated https://github.com/grafana/grafana/issues/11166
