### ISSUE TITLE
"Label filters" in Variables Settings not working at all

### ISSUE THREAD

**Issue by Aracki** [grafana/grafana#76743]
### What happened?

Whatever I put in "Label filters" the "Preview of values" is showing the same list.

### What did you expect to happen?

I'd expect filter to be applied and to show only the part of the list.

### Did this work before?

Yes!

I'm cocmparing `Grafana v10.1.1 (0cfa76b22d)` and `v9.3.6 (978237e7cb)`

In version 9, we had old Query Options query field (no query builder like in v10), and filters were working all the time.

### How do we reproduce it?

Try to add any filter by any label and it won't work.

### Environment (with versions)?

Grafana v10.1.1 (0cfa76b22d)
OS: MacOS
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Thanos

**Comment by usmangt** [comment]
Hi @Aracki,

Thanks for opening this issue.

What is the Data source you are using? (is this problem related to a specific Data source?

**Comment by Aracki** [comment]
Only Thanos/Prometheus datasource.

**Comment by usmangt** [comment]
Can you please share a screenshot so that it is easier to understand. Thanks!!

**Comment by Aracki** [comment]
Thanos/Prometheus 
<img width="499" alt="image" src="https://github.com/grafana/grafana/assets/6129986/f131223f-5a63-4c52-a968-7ba40ba3efb8">

Here is the simple one. Whatever the $network is, the same variable comes up from the dropdown menu.

**Comment by natellium** [comment]
Thanks for your contribution :) As you mention this is isolated to the prometheus datasource - @grafana/observability-metrics would this be something you could look into? Thanks!

**Comment by gfarcas** [comment]
We have the same problem also, grafana 10.2.0, Thanos datasource

**Comment by gfarcas** [comment]
I have observed that the request sent looks like this 
```json
match[]: kube_pod_container_resource_requests{namespace="kyverno"}
start: 1699320457
end: 1699342057
```

**Comment by gfarcas** [comment]
https://github.com/thanos-io/thanos/issues/6338

**Comment by gfarcas** [comment]
seems to be fixed in https://github.com/thanos-io/thanos/pull/6816

**Comment by Aracki** [comment]
I've updated all Thanos components to latest `v0.32.5`, but still experiencing the issue unfortunately.

These two queries by Grafana returns the same result:
```
/api/datasources/uid/<ID>/resources/api/v1/label/cluster_name/values?match%5B%5D=eth_block_number%7Bjob%3D%22node-fantom%22%7D&start=1699430054&end=1699433654
```
```
/api/datasources/uid/<ID>/resources/api/v1/label/cluster_name/values?match%5B%5D=eth_block_number&start=1699430182&end=1699433782
```

although it should return less entries when `job=node-fantom`.

**Comment by gfarcas** [comment]
We have also tested with latest and it didn't work

**Comment by bohandley** [comment]
Are you both seeing that Grafana is sending the label filters in the request to Thanos but Thanos is not respecting that?

Is it the same when you curl directly to Thanos with that endpoint with label filters?

**Comment by bohandley** [comment]
I am closing this as it is not a Grafana Prometheus data source issue but an issue with Thanos and external labels being returned in the resource.
