### ISSUE TITLE
Can't integrate ElasticSearch as a service with Grafana via reverse proxy - receiving 403

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#7674]
[Bug]

Grafana version 4.1.1
Datasource - ElasticSearch
OS - Amazon Linux AMI release 2016.09
- What did you do?
- What was the expected result?
- What happened instead?

I tried to add an elastic search data source in Grafana and receive 403 error.
Checking the grafana log I can only see this exception which doesn't elaborate too much:
lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/accountindex/_stats status=403 remote_addr=X.X.X.X:X time_ms=9ns size=303

I'm using ElasticSearch as a service by AWS via reverse proxy (Using Nginx).
When I try to run CURL commands from the Grafana server I receive an answer from the designated elastic search service.

But when I'm trying to add elastic search data source I receive 403 error.
I don't have any white list IP's listed.

**Comment by torkelo** [comment]
it seems to return access denied, do you have any auth setup for your Elasticsearch service?  

Maybe ask this in mailing list?

**Comment by dudusakharovich** [comment]
Hey,

No, we don't have any auth setup in our ES service.
What did you mean by asking this in mailing list ?

**Comment by torkelo** [comment]
https://groups.io/g/grafana
