### ISSUE TITLE
Grafana triggers the alert, even when metric avg() condition is not met

### ISSUE THREAD

**Issue by tomekit** [grafana/grafana#7677]
Please include this information:
- What Grafana version are you using?
 Grafana v4.0.2 (commit: v4.0.2)

- What datasource are you using?
Graphite
- What OS are you running grafana on?
Docker: https://github.com/kamon-io/docker-grafana-graphite
- What did you do?
Set up Slack alert on a metric:
![image](https://cloud.githubusercontent.com/assets/7759113/23378088/6acdb2e8-fd32-11e6-8066-9dd7cae110a9.png)

- What was the expected result?
Alert should trigger only when certain criterium is met, values > 50, avg() from 10 minutes

- What happened instead?
Even though criterium is not met, the alert was raised. The metric was way below < 50, check the screenshot.

![image](https://cloud.githubusercontent.com/assets/7759113/23378003/2b49b982-fd32-11e6-8e8d-4325757dfbdf.png)

**Comment by torkelo** [comment]
As you can see the value was 100, the graph is not always the same your alert query. As the query time range for the alert is only 10m and the graph is 6h. 

So maybe it's something in the query that is causing a discrepancy depending on time range? 

You can hit Test Rule in the Alert tab, this will show you the raw data returned from your query.

**Comment by tomekit** [comment]
Good spot about the time range differences, I will play with it. Thanks.

**Comment by rs-sathya** [comment]
Seeing this happen as well. Was there a resolution?

**Comment by tomekit** [comment]
I think I've eventually updated to newest version and problem went away, don't remember the details though.
