### ISSUE TITLE
[Feature request] Prevent use of the prefix `__` for templates in web UI

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7678]
Not Grafana beta 4.2 yet ;)

Instead of asking users to reserve the `$__*` foo namespace, it would be better to simply prohibit the creation of new templates which follow that pattern via the web UI. Old dashboards would work, imports would work, and people could do this by hand if they really really wanted to shoot their own foot.

But the common user would be protected.

**Comment by bergquist** [comment]
Didn't find a style for custom error message so I made one up.
![image](https://cloud.githubusercontent.com/assets/618863/23413361/b59a1dba-fdd8-11e6-95bc-78c4720818e7.png)
I bet someone else want to give it some love later on :)
