### ISSUE TITLE
[BUG] New graphs not displaying information

### ISSUE THREAD

**Issue by dxm765** [grafana/grafana#7679]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.1.2 and 4.1.1
- What datasource are you using?
InfluxDB Server: v1.1.1
- What OS are you running grafana on?
Docker / Host is Ubuntu
- What did you do?
Created a new dashboard, added graph, added source as InfluxDB , selected metric.
- What was the expected result?
For the selected metric and data to be displayed, other graphs (pre existing) work perfectly with the same data.
- What happened instead?
No data was graphed , data shows when "bars" or "points" are selected.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

[Images are found here](https://imgur.com/a/gyZZt)

**Comment by torkelo** [comment]
Maybe group by time is too low? So your query returns null values between each data point? When you add the data source be sure to set a lower limit in the group by time interval (to the collection interval), for example `>10s` if you write to influxdb every 10s
