### ISSUE TITLE
Dashboard list: Changing template variable does not update dashboard links

### ISSUE THREAD

**Issue by pierreyves258** [grafana/grafana#76800]
### What happened?

On a visualisation "Dashbaord List" I use the feature 
"Include current template variable values" to send variables to the displayed dashboard in list 

When the initial dashboard is first loaded, the variables are correctly passed to the dashboard in list
but when I change the variable in the initial dashboard, the dashboards links in list are not update with the new var unless I reload the page

### What did you expect to happen?

When a variable is modified in the initial dashboard, all the links in "Dashboard list" are updated with the new vars

### Did this work before?

Don't know

### How do we reproduce it?

Create a Dashboard (called "initial" there)
Create another dashboard (called "second" there)
Mark the second dashboard as favorite (star icon)
Put a custom variable in both dashboards with multiple values [val1, val2]
On the initial dashboard create a visualisation "Dashboard list" to display the second one and check "Include current template variable values"
Go back the initial dashboard with var-variable=val1
Change the initial dashboard variable value in UI to "val2"

=> The link to the second dashboard in "Dashboard List" visualisation is still ending with &var-variable=val1

### Environment (with versions)?

Grafana:  v10.1.2

### Grafana platform?

Other

**Comment by tonypowa** [comment]
hi @pierreyves258 

thanks for reporting this bug

I am adding the issue to the fronted squad's board for review

**Comment by JoaoSilvaGrafana** [comment]
Hey @pierreyves258 ! 👋 Thanks for raising this and for the detailed steps. I managed to reproduce, it's like you said, the dashboard list panel does not pick up the variable change so it doesn't update itself. I will add this to our team's board so we can have a look at fixing it 👍

**Comment by Hackmeat** [comment]
Hello, i have the same issue with grafana 11.3.0 - was this fixed and is now broke again? 1:1 the same issue mentioned above
