### ISSUE TITLE
[Bug]Graph legend scrolls to top when an alias is toggled/clicked

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#7680]
- What Grafana version are you using? 4.1.x

- What datasource are you using? Elasticsearch

- What OS are you running grafana on? Windows 10

- What did you do? Scrolled down the list of aliases in the legend panel (displayed as a table on the "Graph" panel) and clicked an item to toggle all other items to be hidden.

- What was the expected result? I expected my current scroll location to be preserved after the click.

- What happened instead? The scroll position was reset to the top of the list.

When dealing with long lists of aliases, it is very detrimental to lose your scroll position every time you click. Especially if you are Ctrl-clicking to hide numerous elements. In Grafana 3.x, the scroll position was maintained as expected.

**Comment by ushuz** [comment]
@torkelo Sorry to bother, but this problem reappears in 5.1.3 and 5.2.0.
