### ISSUE TITLE
[Feature request] Allow commas in template variables

### ISSUE THREAD

**Issue by Codelica** [grafana/grafana#7681]
- What Grafana version are you using?
4.1.2
- What datasource are you using?
InfluxDB

Commas have a very important use case with InfluxDB as related to the `GROUP BY time()` operator.  

Basically all times in InfluxDB are stored as UTC, so if you want something like 1 day groupings via `GROUP BY time(1d)` you will get day boundaries according UTC +0.  However if the data is from UTC -7 and you want to respect those day boundaries, you currently need to use Influx's "advanced" form of `GROUP BY time(<time_interval>,<offset_interval>)` like `GROUP BY time(1d,7)`

Thus if you are trying to use an "interval" template variable, you'd like to be able to include something like "1d,7" or "7d,7", etc which currently isn't possible. (from what I've seen)

Something like a valid escape char for them would be great.  1d\,7  or 1d,,7 or anything usable :)

Thanks for listening...

**Comment by daniellee** [comment]
Closed by #7732
