### ISSUE TITLE
Prometheus data source: No data is returned for Prometheus 4XX errors instead of the actual error

### ISSUE THREAD

**Issue by VermaPriyanka** [grafana/grafana#76835]
### What happened?

When running a query that returns 414 with Prometheus data source, "No data" is retuned in the panel.

![image](https://github.com/grafana/grafana/assets/45492140/88867693-da0e-42f1-bb32-5a983bcce482)

### What did you expect to happen?

Expectation is to see the error code returned by Prometheus, instead of No data. In v10, the data source config page returns the error details, but not in the panel:

![image](https://github.com/grafana/grafana/assets/45492140/a64d58ac-c6b7-470f-951e-a556ffe1337d)

### Did this work before?

worked in v8.4. Does not work in v9.4 or v10.1

### How do we reproduce it?

1. Create a Node server that always returns 4XX errors
2. Add it as a Prometheus data source, and run any test queries
3. Compare the health check response on the data source settings page vs Explore or a dashboard panel.

### Environment (with versions)?

Grafana: v9.4.7, v10.1
Browser: Chrome

### Grafana platform?

Other

### Datasource(s)?

Prometheus

**Comment by taleena** [comment]
This appears to be for a hosted version of Prom, as it doesn't occur in a local setup + vanilla Prom. In any case, surfacing the error more clearly within Grafana would be an improvement over the current misleading one (No Data), and there are likely other areas this happens as well.

**Comment by v1jayr** [comment]
+1/ We are experiencing this issue after upgrading to Grafana v10. Incorrect promql statements produce similar "No Data" message instead of an error which is indistinguishable from valid Promql queries that returns no data. This is concerning especially when testing out alert rules as they are expected to return no data when everything is fine.
