### ISSUE TITLE
[Bug]The data in SingleStat is not updating

### ISSUE THREAD

**Issue by yhdai** [grafana/grafana#7684]
- What Grafana version are you using?
V4.1.2
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Windows
- What did you do?
I set the same metrics for both singlestat and graph, and it turns out the graph can display the correct data while the singlestat can't.
- What was the expected result?
They should display the same data.
- What happened instead?

The query is : *.timers.$App.cluster.histogram.total_server_num.mean
I checked the value from Graphite browser, the value on graph is correct.

**Comment by torkelo** [comment]
what are your singlestat options? You specify in Options tab which value to show (if your query returns more that one value). Maybe this option is not what you expect?Maybe change it from Average to Current

**Comment by yhdai** [comment]
Hi torkelo,
Yes I am using avg in singlestat option, but it doesn't even set to current.
