### ISSUE TITLE
Auto-generate: Address maximum update depth exceeded warnings

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#76848]
The gen AI functionality / buttons seem to be causing a lot of maximum update depth exceeded warnings.

This may be impacting actual functionality - such as in the case of https://github.com/grafana/grafana/issues/76651

As part of this fix we should test and verify that panel title / description generation is stable / up to date on every panel option update (especially panel type at the very least)

![error](https://github.com/grafana/grafana/assets/22381771/94d946aa-6015-463f-a3dc-12af45e56386)

https://github.com/grafana/grafana/assets/22381771/637428ae-f916-4ef1-a87c-46bff106a113

Grafana: 10.2.3

**Comment by ivanortegaalba** [comment]
Fixed by https://github.com/grafana/grafana/pull/83879
