### ISSUE TITLE
[Feature request] add full resolution for $interval variable

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7685]
Adding "1" as option in https://github.com/grafana/grafana/blob/v4.1.2/public/app/features/templating/partials/editor.html#L124.

Use case is Prometheus templating.
I want to use like `query_result(max_over_time(foobar[$interval]) > $threshold)`.
To query for all time range, full resolution is required.

**Comment by andrewhowdencom** [comment]
I was able to stub something like this by making the step invervals small and granular, and using the Grafan primitives (Avg, for example). But this would considerably improve the efficiency of the queries (only return one stat as opposed to calculating the avg in Grafana)

**Comment by bspradling8** [comment]
I would like this too for prometheus querying! Is there a reason that the `step` is a dropdown instead of text input? Though just adding 1 for now would be awesome.
