### ISSUE TITLE
[Bug] Unable to import Dashboard with Mixed Datasource

### ISSUE THREAD

**Issue by SerhiiD** [grafana/grafana#7687]
Please include this information:
- What Grafana version are you using?
Version 4.1.2
- What datasource are you using?
InfluxDB (Mixed)
- What OS are you running grafana on?
CentOS Linux release 7.3.1611 (Core)
- What did you do?
Created a dashboard using a Mixed datasource (using two different InfluxDB datasources). Exported to JSON, and tried to re-import the dashboard.
- What was the expected result?
The dashboard should be imported successfully using the mixed datasource.
- What happened instead?
![image](https://cloud.githubusercontent.com/assets/20995897/23408864/3fbdd7ae-fdd2-11e6-9784-f2bf7734c9dd.png)

**Comment by torkelo** [comment]
thanks for reporting this, happy to say that this has already been reported and fixed! 
https://github.com/grafana/grafana/issues/6032

fix is available in 4.2-beta

**Comment by SerhiiD** [comment]
I have Just updated my grafana to Version 4.2.0-beta1. Have the same problem.

in issue #6032 you said that problem was solved in 4.0.0-Beta1.
