### ISSUE TITLE
[Bug] Dashboards are played randomly

### ISSUE THREAD

**Issue by msalajka** [grafana/grafana#7688]
What Grafana version are you using?
Grafana v4.1.2 (commit: v4.1.2)
What datasource are you using?
InfluxDB (Mixed)
What OS are you running grafana on?
CentOS Linux 
What did you do?
Created a playlist.
What was the expected result?
Play dashboards in defined order.
What happened instead?
Dashboards are played "randomly" - not in defined order. The order defined in the setting is ignored.

**Comment by LuizMeier** [comment]
Hello!

Just installed 4.3.2 version right now and the issue persists.

The playlist assume another order to display the dashboards. It is not random, but is not the order I've defined.

**Comment by torkelo** [comment]
you have to update the playlist for the fix to take effect

**Comment by LuizMeier** [comment]
Torkelo,

Thank you for the answer. Update the playlist did the trick!

Luiz
