### ISSUE TITLE
Lock scaling y axis

### ISSUE THREAD

**Issue by Tendoncs** [grafana/grafana#769]
It would be nice to be able to create a connection across Graphs on a dashboard that will lock the adjustable scaling to each other. Like the X axis is locked to all graphs on a dashboard. I know it can be set up ahead of time by assigning each graph a scale but with how much the data fluctuates it is nice to have an auto adjust. This request is along the idea that all the graphs share a X axis but could be limited to a row or just selected graphs. 

Example I have two very busy graphs that are for shopping carts. Filled carts and stale carts. When they are next to each both center the data and it causes them to look equal. That is a red flag. However the filled carts are 2-3k and the empty are in 1k-2k range. so the range could auto scale them to 750-4,000 on the Y so they look like they are connected. I could sum them up and use a 3rd graph but there is a lot to show and so little space.

**Comment by torkelo** [comment]
you will have to set the y min/max on both panels if you want lock them in place
