### ISSUE TITLE
[Feature request] Hiding template variables in kiosk mode or view mode

### ISSUE THREAD

**Issue by Rickkwa** [grafana/grafana#7691]
Hi,

My request is that we can optionally make it so that when we put a dashboard into kiosk mode (and maybe view mode), it will hide the template variable dropdowns. 

For example, there are multiple 24/7 monitors that I want to have Grafana on. They use the same dashboard, just with different variable values chosen from the dropdowns. The dropdowns don't look very good when in kiosk mode, and for a 24/7 display there will not be user interaction so having a dropdown is not needed.

I know that we can set the variable values through the URL but having it in the GUI is more user friendly.

Currently using Grafana version 4.1.1.

**Comment by torkelo** [comment]
the problem with doing it in view mode is that those variables could for many dashboards be important context (visual info) to the rest of the dashboard. Same for kiosk mode. Hard to solve it for everyone without introducing a new hide option for the variables

**Comment by Rickkwa** [comment]
Yes, having it as an optional setting would be best.

**Comment by crypt0train** [comment]
+1

**Comment by Khord** [comment]
+1

**Comment by aniketbiswas2017** [comment]
It would be a good option to keep the submenu (variables) hide settings as optional in the Preferences or Settings Tab so as to tend to the requirements of the end users or projects. Thank you.
