### ISSUE TITLE
[Feature request] Possible to change link in "Go to the Alerts page"?

### ISSUE THREAD

**Issue by spawnmarvel** [grafana/grafana#7693]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by spawnmarvel** [comment]
![bilde](https://cloud.githubusercontent.com/assets/25563453/23455853/7a2dc9fe-fe71-11e6-96ba-e92b57c3aee2.png)

**Comment by spawnmarvel** [comment]
Hi, 
Granfana v4.1.1

I am wondering if it is possible to change the url in  "Go to th Alerting page" link recieved from alering mail.
The link goes to http://localhost.....

Is it a possibility to edit the link used there.

regards

![bilde](https://cloud.githubusercontent.com/assets/25563453/23456015/1735f6a4-fe72-11e6-9dd4-4ea0dd031211.png)

**Comment by daniellee** [comment]
The url used in emails can be set in the ini file: http://docs.grafana.org/installation/configuration/#root-url

```
# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://yourgrafanaserver.com
```

**Comment by spawnmarvel** [comment]
Hi, 

Great, thanks very much
