### ISSUE TITLE
Loki: fetchLabelValues API should accept optional query paramter

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#76943]
fetchLabelValues() could accept an [optional second ](https://grafana.com/docs/loki/latest/reference/api/#list-label-values-within-a-range-of-time)query[parameter](https://grafana.com/docs/loki/latest/reference/api/#list-label-values-within-a-range-of-time) so developers don't have to go through `fetchSeriesLabels` if they want label values. 

Related to https://raintank-corp.slack.com/archives/C03Q8A1GY92/p1696952289458019?thread_ts=1696854758.113109&cid=C03Q8A1GY92

**Comment by matyax** [comment]
This has been done.
