### ISSUE TITLE
[Feature Request] Support dm3 unit

### ISSUE THREAD

**Issue by sebastienfouss** [grafana/grafana#7695]
A natural gas consumption is typically provided in dm3.
Today, Grafana offers the following units:
- liters (but not appropriate for gas)
- m3 (not really appropriate for typical household natural gas consumption)

Any possibility to support dm3 (cube decimeter) as well ? 

Thanks

**Comment by daniellee** [comment]
Googling this, it seems [liters and dm3](https://en.wikipedia.org/wiki/Dm3) are exactly the same? But that does not really matter, we can add aliases for the same units.

**Comment by sebastienfouss** [comment]
Indeed, they are the same but are used in different context. For example, you purchase a bottle of 1 liter of water, not of 1dm3 of water.

I would really appreciate if you could indeed add an alias.

Thanks

**Comment by mitjaziv** [comment]
Added support for dm3 cubic decimetre

https://github.com/grafana/grafana/pull/7719

**Comment by mitjaziv** [comment]
added cubic decimetre (dm3) https://github.com/grafana/grafana/pull/7720

**Comment by daniellee** [comment]
Closed by #7720
