### ISSUE TITLE
Dashboards: Panel description tooltip goes past the edge of the screen

### ISSUE THREAD

**Issue by albert-smit** [grafana/grafana#76958]
### What happened?

Narrow panels near the edge of the screen can have their description go off screen when you hover over the i
![1698063202](https://github.com/grafana/grafana/assets/7870036/52d9b73a-690e-408f-a17d-4ad20990e49d)

### What did you expect to happen?

I would expect the tooltip to stay in the screen so the whole description is readable

### Did this work before?

not sure

### How do we reproduce it?

1. create a panel near the right edge of the dashboard
2. add a description to the panel
3. hover over the i so the description tool tip appears

### Environment (with versions)?

Grafana: 10.0.1, also tested on grafana play( version 10.2.0) 
OS: linux and windows
Browser: firefox and chrome

### Grafana platform?

None

**Comment by johan-vcc** [comment]
We also see this issue both in a local instance running Grafana v9.3.1 and in Grafana cloud v10.2.0.
In v9.3.1 we also see an issue where a big description for a panel at the top of the page will go outside the top of the window. Also in v9.3.1 on page reload descriptions will render nicely (down for panels at the top and left for panels at the right edge) the first time on hover over, second time onward it renders outside of window.

In v10.2.0 it consistently renders down and right, which is only a problem for panels at the right edge of the window. Hovering over then scrolling causes the description to pop back inside the window.

Tested in Linux on Firefox and Chromium.

**Comment by tonypowa** [comment]
Hi @albert-smit 

Thank you for reporting this bug

Adding issue to both front end platform and dashboard squads' boards

**Comment by ashharrison90** [comment]
hi @albert-smit 👋 

this has been fixed by https://github.com/grafana/grafana/pull/77676 which will be released in 10.3.0.

thanks again for reporting this! 🙌
