### ISSUE TITLE
Loki: Ad Hoc variable filtering is not applied when used with Loki datasource from variable

### ISSUE THREAD

**Issue by yafanasiev** [grafana/grafana#76952]
### What happened?

When using ad-hoc filters with Loki datasource loaded from variable, filters are not applied. 

### What did you expect to happen?

Ad-hoc filter should work as expected.

Searching the GitHub issues I found a few related ones:

1. https://github.com/grafana/grafana/issues/74657 - seems to be resolved, datasource variable is selectable in the ad-hoc variable UI
2. https://github.com/grafana/grafana/issues/75101 - might be related.

Please let me know if you need any additional information, I would be happy to help.

### Did this work before?

Not sure, first time setting this up

### How do we reproduce it?

1. Create a new dashboard, add a datasource variable

<img width="490" alt="Screenshot 2023-10-23 at 12 54 52" src="https://github.com/grafana/grafana/assets/66992401/3b426078-1089-40a8-be78-87fb07abae34">

2. Create a new table panel (reproducible on Logs panel as well):
<img width="1305" alt="Screenshot 2023-10-23 at 12 56 05" src="https://github.com/grafana/grafana/assets/66992401/578dad13-107a-4710-8ef5-2b0fc5e6bbe7">

3. Try to filter on label value:

<img width="1214" alt="Screenshot 2023-10-23 at 12 58 07" src="https://github.com/grafana/grafana/assets/66992401/9af8c1b7-674a-4ca5-84b1-a337904a1cbc">

Changing datasource from variable inside panel makes filtering work. However, if panel datasource is set to a variable, and ad-hoc filter variable datasource is manually changed to a specific one, filtering will work until new filter is added - then ad hoc filter variable datasource value automatically reverts to the datasource variable.

### Environment (with versions)?

Grafana: v10.1.5 (849c612fcb)
OS: macOS 14.0 (23A344)
Browser: Google Chrome 118.0.5993.88 (Official Build) (arm64)

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by usmangt** [comment]
Hi @yafanasiev 

Thanks for the update on this, I will close this one for now. But feel free to reopen it if it happens again.
