### ISSUE TITLE
Prometheus: Switch to heatmap data format & heatmap visualization when grouping by le

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#76962]
We want to see the data in heatmap visualization when grouping by le

`sum(rate(http_response_time_seconds_bucket[$__rate_interval])) by (le)`

`histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket[$__rate_interval])) by (le))`

**Comment by leeoniya** [comment]
btw, i'm currently modifying our Histogram panel to support the `heatmap-rows` and `heatmap-cells` format out of the box (https://github.com/grafana/grafana/issues/76131). it will ignore timestamps and sum all the histograms/buckets in the response together. so maybe we won't know if the user wants a Heatmap or Histogram viz at the end.

currently Histograms don't look right:

https://nativehistogram.grafana-dev.net/d/dc5080b6-5d30-40cf-8e97-c0b82100cecb/histogram-demo?orgId=1&from=now-6h&to=now

current wip for `heatmap-cells` support:

wrong (current):

![image](https://github.com/grafana/grafana/assets/43234/a1cebde3-b6ba-45aa-9581-282cf7366196)

less wrong (wip):

![image](https://github.com/grafana/grafana/assets/43234/9e7cdc64-9322-473e-9b7d-2c3dccd21a42)
