### ISSUE TITLE
Explore: Decouple plugin dependencies 

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#76963]
Goal is to make it easier to decouple plugins from Explore (this is an ongoing work for many squads). In long run (outside of the scope) we can think about decoupling Explore even further so it can be turned into a plugin on its own.

1. Remove dependencies Explore has on plugins to make it easier to decouple plugins
2. Put a limit in place so no new dependencies to plugins are introduced

- [ ] Decouple imports from `plugins/datasource` dependencies
- [x] #74176

**Comment by Elfo404** [comment]
This is something plugins squad are currently working on and we should not own.
