### ISSUE TITLE
Breadcrumbs: link does not reflect the path from root_url with serve_from_sub_path

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#76976]
### What happened?

We have Grafana instance with configured `root_url` and `serve_from_sub_path` behind a reverse proxy on a sub path and found out that links in breadcrumbs does not honor these settings and omit the sub path at all.

### What did you expect to happen?

Breadcrumb links to follow the honor the configuration from root_path

### Did this work before?

Not sure

### How do we reproduce it?

1. Configure grafana with the `root_url=http://foo.bar/sub/path/grafana` and `serve_from_sub_path=true`
2. Go to any dashoard and see where the links in breadcrumbs leads 

### Environment (with versions)?

Grafana: Grafana v10.1.4 (a676a96d91)
OS: Official docker image
Browser: Firefox

### Grafana platform?

Kubernetes

**Comment by torkelo** [comment]
@FUSAKLA can you show me which breadcrumbs does not include the sub path?

**Comment by FUSAKLA** [comment]
Hi, yes sorry should have included a screenshot

These :point_down:  (now I hope those are not from some 3rd party plugin :facepalm: )
![image](https://github.com/grafana/grafana/assets/6112562/a6aa4d60-92d1-49ca-abed-28590f4755d1)

**Comment by torkelo** [comment]
@FUSAKLA unable to replicate that on 10.2/10.3 (latest main).

**Comment by FUSAKLA** [comment]
Ok, will upgrade and report back. Thanks for taking a look!

**Comment by FUSAKLA** [comment]
Right, after upgrading to 10.2 the issue seems to be resolved.

Thanks once again!
