### ISSUE TITLE
[Feature request] Add auto multi-select with template variables

### ISSUE THREAD

**Issue by sebito91** [grafana/grafana#7698]
- What Grafana version are you using?
v4.0.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
RHEL7

- What did you do?
Create a multi-select template variable on a dashboard

- What was the expected result?
When you have a long list of values in the multi-select, would be nice if when typing the filter would auto-select those values that match. Horrible to admit, but filters in Excel do this now and having that kind of workflow would be amazing!

- What happened instead?
You have to click through and add each one, which can we cumbersome in long lists.

![multi-select](https://cloud.githubusercontent.com/assets/3159454/23472245/d152d454-fe71-11e6-8606-1002a2f886a1.png)
![multi-select_excel](https://cloud.githubusercontent.com/assets/3159454/23472247/d15920d4-fe71-11e6-8d23-a4f875fa8df1.png)

**Comment by wanderingnewfie** [comment]
+1

**Comment by Caez83** [comment]
+1
