### ISSUE TITLE
Elastic templating {"find": "terms", "field": "@hostname"} not working

### ISSUE THREAD

**Issue by m2b** [grafana/grafana#7700]
Grafana version 4.1.2
Running against elastic 5.2.1

Passing _msearch?search_type=count along with the template request returns bad request

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [count]"}],"type":"illegal_argument_exception","reason":"No search type for [count]"},"status":400}

**Comment by torkelo** [comment]
make sure you set your elasticsearch version in grafana data source options

**Comment by Venture200** [comment]
@torkelo's solution worked for me. Thanks
