### ISSUE TITLE
[Feature Request] Remember Dashboard Filters

### ISSUE THREAD

**Issue by andyl** [grafana/grafana#7701]
Using Grafana 4.1.2 with InfluxDB on Ubuntu 16.04.

You can filter dashboards by STAR and by TAG.  Your filter settings are reset each time you bring up the dashboard list.

Feature request: remember the STAR and TAG settings within and across sessions.

Use Case:  I have many dashboards in development, and star the ones that are finished.  In day-to-day use, I only care about the STAR dashboards.  Remembering the filter setting would eliminate a very repetitive step.

**Comment by bergquist** [comment]
Would https://github.com/grafana/grafana/issues/1611 solve your use case? if so that's the prefer solution.

**Comment by andyl** [comment]
The folders approach is more complicated than we need.  With folders, we would probably ask for the folder state to be remembered.  Then there will arise questions about folder per missioning etc.  For us the simplicity of stars and tags is better.

**Comment by andyl** [comment]
Oh!  Just discovered Grafana's keyboard shortcuts.  Very good!  The shortcut "ss" opens the search window with starred dashboards.  That is what I wanted!

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
