### ISSUE TITLE
[Bug] Elasticsearch getIndexList error.

### ISSUE THREAD

**Issue by zhuqunzhou** [grafana/grafana#7702]
My timestamp saved as '2017-03-01 02:00:00.109+08:00',

But,The function `getIndexList` in [index_pattern.js](https://github.com/grafana/grafana/blob/05d43999dc83c2adc5bda27eb8e41e0b762c35ea/public/app/plugins/datasource/elasticsearch/index_pattern.js) will use `utc` to calculate index name.

Here is the code,`var start = moment(from).utc().startOf(intervalInfo.startOf);`.

So,i can't get correct index name if i just want to get the data from zero o'clock to eight o'clock?

**Comment by torkelo** [comment]
yes, index names need to use UTC . Sorry if this is causing issues for you. 

Any change you can change how you create index names? UTC is the standard for most Elasticsearch time/date based index names
