### ISSUE TITLE
"http: proxy error: EOF" when adding datasource for PostgreSQL

### ISSUE THREAD

**Issue by Kavinsp** [grafana/grafana#7705]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.1.2
- What datasource are you using?
New Datasource for PostgreSQL Database
- What OS are you running grafana on?
RHEL 6
- What did you do?
Trying to add the data source
- What was the expected result?
When clicking "Save & Test" button the data source should be added successfully
- What happened instead?
When clicking "Save & Test" button , grafana shows the error log "http: proxy error: EOF"

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

Logs are pasted below

INFO[03-02|06:40:45] Proxying incoming request                logger=data-proxy-log userid=1 orgid=1 username=admin datasource=sqldb uri=/api/datasources/proxy/14/query method=POST body="{\"query\":\"SELECT 1 AS num\",\"epoch\":\"ms\"}"
**2017/03/02 06:40:49 http: proxy error: EOF**
INFO[03-02|06:40:50] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=POST path=/query status=502 remote_addr=xx.xx.xx.xx time_ms=4.709µs size=0

**Comment by daniellee** [comment]
Could you post a link to the postgres data source that you are using, please. As it is not published on Grafana.net, it is not a plugin that we know about.

**Comment by daniellee** [comment]
One follow up question, are you using direct or proxy access under the data source settings?

**Comment by Kavinsp** [comment]
Am using proxy for the data source settings. The plugin is not available anywhere in the link . I took a example data source plugin and developed one .

**Comment by daniellee** [comment]
Ok, so it is your own custom plugin. Can you explain more about it? It is very hard to give any advice without a better description. If I was to guess, then maybe you are returning an empty response? 

- Why are you doing a POST for a select query?
- What does the http request and response look like?
- What is your code doing when it receives the request (in the query function in your data source)?
- Have you tried debugging the javascript to see what happens?

**Comment by Kavinsp** [comment]
Hey . It's working now . I am able to add a postgreSQL data source. Thanks for your help.

**Comment by Aakansha-Talati** [comment]
@Kavinsp what did you do to resolve this? I am using the Graphite Datasource and using the proxy access.

**Comment by Kavinsp** [comment]
@Aakansha-Talati

I got a patch from Github which helped me to adopt the postgresSQL
Datasource.

**Comment by dudusakharovich** [comment]
@Kavinsp  - Hey,

Sorry to bother you, I also tried to add Postgressql data source (Actually Amazon RDS service) version 10.6, but for some reason always receiving error "unexpected EOF" - Do you know what is wrong with my configuration ?

![image](https://user-images.githubusercontent.com/24862189/54882495-45b92080-4e63-11e9-86ea-bb53cef32d60.png)
