### ISSUE TITLE
[Bug] Error when returning to page

### ISSUE THREAD

**Issue by XaroRSA** [grafana/grafana#7706]
- What Grafana version are you using?
Fairly recent, updated with latest version 2-3 weeks ago.

- What datasource are you using?
Influxdb 

- What OS are you running grafana on? 
Linux Ubuntu 14.04

- What did you do?
Viewed a dashboard in Grafana previous day, and left browser open on that page. +-8hours later, I refreshed the page.

- What was the expected result?
To see the same graph with the same time settings

- What happened instead?
A error occurred: Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
true

I don't think this is related to login/session, because if I press back, enter url for another dashboard, no login is prompted.

- An image or text representation of your metric query
http://mydomain.com/dashboard/db/new-dashboard-copy?from=1488322800000&to=1488455234278&refresh=false

Javascript
Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
    at Object.c.describe_interval (boot.js:25)
    at Object.c.interval_to_ms (boot.js:25)
    at a.setAutoRefresh (boot.js:12)
    at a.init (boot.js:12)
    at b.a.setupDashboardInternal (boot.js:11)
    at b.a.setupDashboard (boot.js:11)
    at b.a.onInitFailed (boot.js:11)
    at b.a.setupDashboard (boot.js:11)
    at a.init (boot.js:11)
    at b.a.initDashboard (boot.js:34) true

**Comment by bergquist** [comment]
This issue seems like a pain to repro. But should be tested a few times to verify.

**Comment by daniellee** [comment]
This was a bug in 4.1, we think it might be fixed already. Can you check what version you are running or are you on the master branch?

**Comment by torkelo** [comment]
yes, this should be fixed in latest beta / master builds. Please test and let us know if you still get this.

**Comment by ManivannanMurugavel** [comment]
Please check the datasource and remove the Default group by time text box value

**Comment by shuibinggun** [comment]
Version 4.2.0

ERROR

```
Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
```
Grafana Metrics

```
SELECT mean("request_time_us") FROM "test_metric" WHERE $timeFilter GROUP BY time($__interval) fill(null)
```
InfluxDB

```
> SHOW FIELD KEYS
name: test_metric
fieldKey                  fieldType
--------                  ---------
agent                     string
auth                      string
client_ip                 string
http_version              float
ident                     string
referrer                  string
request                   string
request_time_us           float
resp_bytes                integer
upstream_response_time_us float
```

```
SELECT * FROM /.*/ LIMIT 1
name: test_metric
time                agent                                                                                                                     auth client_ip     host            http_version ident referrer request                                                                      request_time_us resp_bytes resp_code upstream_response_time_us verb
----                -----                                                                                                                     ---- ---------     ----            ------------ ----- -------- -------                                                                      --------------- ---------- --------- ------------------------- ----
1496807434000000000 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 -    192.168.171.1 192.168.171.128 1.1          -     -        /user/get-info?web_token=65ScKwp2c%3D 5.123           92         401       5.038                     GET
```
