### ISSUE TITLE
grafana running behind a nginx reverse proxy with ssl encryption can not load apllication files

### ISSUE THREAD

**Issue by trupf** [grafana/grafana#77063]
### What happened?

I must admit this behavior is very strange to me. Some facts to understand the problem:
- grafana is running behind nginx reverse proxy in a subpath (/grafana)
- nginx does handle ssl encryption with letsencrypt cert
- i can access grafana and all is working with my firefox browser from my Debian client
- with chromium brower i get a black page showing "If you're seeing this Grafana has failed to load its application files"
Errors in Chromium:
Uncaught SyntaxError: Invalid or unexpected token
UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2:1  Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
- if I remove ssl encryption in nginx (hence open port 80 and enable the reverse proxy on this port) everything is working even in chromium 
- it is also working if I access grafana without proxy on port 3000
- with my windows machine firefox is showing the above mentioned black page and message, with chrome on the other hand I can login but later when loading the dashboards I get a popup "Failed to fetch"
- same setup on an other machine (odroid hc4) has no issues neither in firefox nor in chromium even with ssl encryption

So there must be some issue with SSL encryption but I don't get what is going on. SSL encryption for other hosted sites is working on the same machine. with the same certs.

Error message in Chromium is: Uncaught SyntaxError: Invalid or unexpected token (at app.5134ec4….js:2719:28260)

### What did you expect to happen?

Just normal load of the dashboards

### Did this work before?

not on this machine, but as described on an other one.

### How do we reproduce it?

I don't know

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.1.5
OS: Server: raspbian bookworm, linux 6.1.21, nginx 1.22.1,
        Client: Debian bookworm
Browser: Firefox 120.15.1esr, respective Chromium 108.0.5359.40 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

no, even the login page ist not shown correct

**Comment by daudcanugerah** [comment]
mee to

**Comment by trupf** [comment]
Now after several reloads and trials on different days the display suddenly started working. And it is still working after a restart. But the issue remains. If I switch to an other user (hence one with chromium which has not seen the site before), I still get the above error. It seems that chromium is chaching the resoource and can load it from cache. So I suspect this is a timing issue / race condition i chromium....

**Comment by mildwonkey** [comment]
Hi @trupf , I'm sorry you're running into this behavior. This sounds more like a proxy configuration question or issue than a Grafana bug that we can help with. We use Github issues for bugs and feature requests; I recommend using the [Grafana Community Forums](https://community.grafana.com/) for questions.

**Comment by nook24** [comment]
I have the same issue, since I updated Nginx to `nginx/1.22.1`. The configuration was working fine with `nginx/1.20.1` so probably not a Grafana issue.

That's my nginx config
```nginx
#Proxy for Grafana (external requests done by Web browsers)
location ^~ /grafana/ {
    # Send request to authentication server first
    auth_request     /auth_grafana;
    auth_request_set $auth_status $upstream_status;

    proxy_set_header X-WEBAUTH-USER viewer;
    proxy_set_header Authorization "";
    proxy_pass http://127.0.0.1:3033/;
    sub_filter 'http://localhost:3033/grafana/' 'https://$host/grafana/';
    sub_filter_once off;
}
```

**Comment by Azim-Azizov** [comment]
@trupf hi. Were you able to fix this issue? I checked everything. Do you use Cloudflare proxy. I guess the problem is in that part. Because I tried loading up without that proxy, and everything worked. Maybe Cloudflare somehow caches the requests and prevents the resource from loading?

**Comment by trupf** [comment]
Yes the issue is fixed but I think it was a total unrelated problem. My Internet router was misconfigured by the provider to send ipv6 router advertisements with preferred lifetime = 0 which led my machine create a new ipv6 address every second and chromium to continously use a newly created temp address. This way chromium didn't have enough time to fetch the files. Obviously firefox does use the old address somewhat longer. I was able to fix the issue by manually assigning a fixed ipv6 and meanwhile my provider has fixed the ra and everything is working again.
