### ISSUE TITLE
Canvas: Make extents grow with pan

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#77087]
Make canvas extents grow with pan. With [current approach for pan/zoom](https://github.com/grafana/grafana/pull/76705), panning to the canvas edges, causes pan to stop and "bounce" back. Elements are also cut off.

![Image](https://user-images.githubusercontent.com/60050885/277780802-3dea4b78-4fa7-47cb-95e0-370f8c04cde2.gif)

Some considerations:
1. How does this impact the layout constraint system?
2. Does this become an option, and if so, where does that live?

To implement, inside of [app/features/canvas/runtime/SceneTransformationWrapper.tsx](https://github.com/grafana/grafana/blob/b0130ecb829925a3343abc208395a3bfdc1b9187/public/app/features/canvas/runtime/SceneTransformWrapper.tsx#L65), inside of the `<TransformWrapper/>` add something similar to this:  

        onPanning={(r, e) => {

        const mouseEvent = e as MouseEvent;
        // Get deltaX and deltaY from pan event and add it to current canvas dimensions
        let deltaX = mouseEvent.movementX;
        let deltaY = mouseEvent.movementY;
        if (deltaX > 0) {
          deltaX = 0;
        }
        if (deltaY > 0) {
          deltaY = 0;
        }
        scene.updateSize(scene.width - deltaX, scene.height - deltaY);
        scene.panel.forceUpdate();

      }}
        limitToBounds={false}

**Comment by nmarrs** [comment]
See https://github.com/grafana/support-escalations/issues/8962#issuecomment-1891669837 for a great example debug panel to use for testing this feature

**Comment by drew08t** [comment]
We could recalculating all bottom / right constrained elements during pan.
