### ISSUE TITLE
[Bug] Graph Description tooltip - wrong position for some Rows 

### ISSUE THREAD

**Issue by rnovikovP** [grafana/grafana#7708]
Reproducible on http://play.grafana.org/dashboard/db/big-dashboard 

If you add description for graph in Row on second screen (not 1st, 2nd rows )
you  got 
![grafana-tooltip](https://cloud.githubusercontent.com/assets/25495422/23501555/f9d4fa08-ff3c-11e6-95fb-50212503fb13.png)

For Rows on first browser screen  - everything fine , tooltip - near the  '( i )'

**Comment by torkelo** [comment]
Hi, 

Strange, I am unable to replicate this. Can you describe in detail the steps you took? What browser are you using?

**Comment by rnovikovP** [comment]
@torkelo  Chrome  56/ win 10  , also Edge / win 10 
Steps  are  :
1) open http://play.grafana.org/dashboard/db/big-dashboard
2) scroll down 
3) "Edit" the last Graph
4) Description = "Lorem ipsum " [(http://prntscr.com/ef9adr)](http://prntscr.com/ef9b2e)
5) view Graph  [(http://prntscr.com/ef9b2e)](http://prntscr.com/ef9b2e)

**Comment by pschultz** [comment]
Can't reproduce with Chrome 56 on Fedora.
