### ISSUE TITLE
TimeSeries: Threshold opacity is ignored when used to color series

### ISSUE THREAD

**Issue by Honusnap** [grafana/grafana#77093]
### What happened?

![2023-10-24_224155](https://github.com/grafana/grafana/assets/507094/543365d1-57e1-40b5-b89a-7c18b8bebe37)
![2023-10-24_223953](https://github.com/grafana/grafana/assets/507094/6e6e5a8a-4edf-4f91-a49d-eff381d301bd)
![2023-10-24_223919](https://github.com/grafana/grafana/assets/507094/31edc54f-7cbe-44f1-9901-4efff887873a)

Hi,
I used a transform to add 3 fields together, then add a coloring by thresholds cause i do not want to display negative values.
I defined 3 thresholds 1000 (Orange), 0 (Orange) and -1000 (transparent).
Instead of being transparent when negative .. it is displayed in black (background color i suppose)

### What did you expect to happen?

I expected it to be transparent = not displayed.

### Did this work before?

Dunno .. first time i try this.

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 9.1.1
OS: Home Assistant OS
Browser: Brave

### Grafana platform?

Other

### Datasource(s)?

Home Assistant/InfluxDB

**Comment by leeoniya** [comment]
so, this is because we set the alpha (opacity) during fill() to match the setting in the panel options. the stroke is always done with 100% opacity. we ignore any existing opacity in the threshold colors when coloring the series.

this feels tricky because if we start honoring the opacity of the threshold colors, we will break existing panels that have relied on the series opacity setting and left the threshold opacity at 100%. maybe this is fine, i dont think a lot of people use this style of coloring, though it would be confusing why the opacity slider no longer works.

one idea that comes to mind is special-casing threshold colors with 0 alpha (obviously being used to "erase" part of the data). this would be tricky because we cannot use a global alpha setting anymore and have to set the series alpha to individual colors stops in the fill gradient, except those with 0 alpha in the thresholds.

> I used a transform to add 3 fields together, then add a coloring by thresholds cause i do not want to display negative values.

i guess i'll ask the obvious: why not use another transformation to filter out values < 0 instead of incurring the cost rendering them as transparent?

![image](https://github.com/grafana/grafana/assets/43234/762cc48b-0cb0-4ca0-90a8-23ecd1f449d2)

minimal repro:

<details><summary>thresholds-opacity.json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana-testdata-datasource",
        "uid": "9cY0WtPMz"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 22,
            "gradientMode": "scheme",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "transparent",
                "value": null
              },
              {
                "color": "red",
                "value": 40
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "grafana-testdata-datasource",
            "uid": "9cY0WtPMz"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90,30,5,0"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "thresholds-opacity",
  "version": 0,
  "weekStart": ""
}
```
</details>

![image](https://github.com/grafana/grafana/assets/43234/b2eb4fe4-9378-4e63-84d7-f0295c136b2c)

https://github.com/grafana/grafana/assets/43234/820cb89d-4418-4f14-96cd-da80fbf7a218

**Comment by leeoniya** [comment]
well, i just learned something. apparently `ctx.globalAlpha` has no effect on colors with an explicitly-set alpha [1], but this is not called out anywhere in the MDN docs [2] or the spec. this seems to work consistently at least in Chrome and Firefox, so we should be able to pass this through. we may still need to special-case alpha=0 for stroke.

relevant code is gonna be in https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/config/gradientFills.ts

[1] https://jsfiddle.net/v8r7omn1/1/
[2] https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalAlpha

**Comment by leeoniya** [comment]
turns out we don't use globalAlpha for this :sweat_smile:.

in https://github.com/grafana/grafana/pull/77104 i just special-cased fully transparent colors from inheriting series fill opacity or hard-coded 100% opacity for stroke.

**Comment by Honusnap** [comment]
Hello,

About "why not use another transformation to filter out values < 0 instead of incurring the cost rendering them as transparent?", cause the transformation remove all values that would be on this line (same time) and i want to keep my other datas. Or maybe i do something wrong ..?

![2023-10-25_102052](https://github.com/grafana/grafana/assets/507094/878e9e44-e82d-47bf-ac76-c054510fe2e4)
![2023-10-25_102018](https://github.com/grafana/grafana/assets/507094/4c94c658-1f80-4230-b665-0753cbda34cd)
