### ISSUE TITLE
[Bug] 4.2-Beta1 has stopped our Slack Alert from working

### ISSUE THREAD

**Issue by phateuk** [grafana/grafana#7710]
Please include this information:
- What Grafana version are you using? 4.2-Beta1
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 6.8 Final
- What did you do? Attempt to trigger a Slack alert as normal
- What was the expected result? No slack alert, error in log file
- What happened instead? No Slack alert, error in log file.

Here is the error from the grafana.log:

t=2017-03-02T05:19:13+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=20 notification=WebServices_alert_grafana
t=2017-03-02T05:19:42+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=WebServices_alert_grafana

Rolling back to 4.1 fixes the problem immediately with no changes to the grafana.db, grafana.ini or anything else.

Note: We are using the http/https proxy settings in the init file as we're sat behind a reverse-proxy but this has never posed an issue before.

**Comment by bergquist** [comment]
Thanks for reporting this! This will be fixed in next beta release and our night build.
