### ISSUE TITLE
Dashboards: Select Sum(mean) from subquery is incorrect

### ISSUE THREAD

**Issue by Honusnap** [grafana/grafana#77115]
### What happened?

Maybe i do something wrong or misunderstand how it should work... 

I use a subquery (A) to gather values from a table : 3 values, one is null cause this inverter is actually off.

SELECT mean("value") FROM "autogen"."W" WHERE ("entity_id" = 'lifepo4_soc_power' OR "entity_id" = 'power'  OR "entity_id" = 'power_2') AND $timeFilter GROUP BY time(5m), "entity_id" fill(linear)

Values that will be summed by this main query : 
Select sum(mean) from (A) GROUP BY time(5m) fill(linear)

But the sum is SOMETIMES.. incorrect, look at  08:00:00, those 2 TotalParams component are ok, but the "Pack Power" is not added to the sum ... weird ..

![2023-10-25_101145](https://github.com/grafana/grafana/assets/507094/7a027277-afaf-4b67-a9de-aa0fd538b2c2)

I noticed it cause the graphic is mostly good .. but with strange spikes... Purple ,is supposed to be Red + Blue and should give the inverters "efficiency".

![2023-10-25_104730](https://github.com/grafana/grafana/assets/507094/7bc75a93-1435-43d3-9977-e824386d7d8d)

### What did you expect to happen?

A correct sum

### Did this work before?

I dunno, first time i try it

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 9.1.1
OS: 
Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

Browser: Brave - 1.5.120

### Grafana platform?

None

**Comment by Honusnap** [comment]
Do you need some more datas to understand this one ?

**Comment by itsmylife** [comment]
@Honusnap What do you get when you run this on InfluxDB UI?
Do you mind sharing a .har file so I can check the values? I assume you are using influxdb datasource on frontend mode (either `influxdbBackendMigration` feature toggle is disabled or not even used). That means we show whatever data we receive from InfluxDB directly. We do not apply any calculation.
