### ISSUE TITLE
Live: Streaming panels temporarily go blank during dashboard refresh

### ISSUE THREAD

**Issue by ManIntelligent** [grafana/grafana#77142]
### What happened?

When utilizing streaming from Redis data sources, the related panels temporarily goes blank each time the dashboard refreshes. This is in contrast to panels without streaming enabled, which seamlessly update only with new data, maintaining data visualization during refreshes.

https://github.com/grafana/grafana/assets/148908345/8e20514a-48d0-4551-a8d3-0d2bdc6fc25f

### What did you expect to happen?

My expectation is that when a dashboard refresh occurs, either manually initiated via the 'Refresh Dashboard' button or automatically according to the set refresh interval, the streaming connections and associated panels remain unaffected. Rather than going blank or experiencing any disruption in streaming interval, they should continue to display and update data seamlessly. This continuity will ensure a user-friendly experience, minimizing disruptions in streaming data visibility regardless of dashboard refresh actions.

### Did this work before?

No

### How do we reproduce it?

1. Configure Redis as a data source.
2. Create new dashboard.
3. Add visualization of any type.
4. Select Redis as a data source.
5. Choose, e.g. Type: Command-line-interface (CLI), Command: EVAL "return redis.call('TIME')[1]" 0, Steaming: Enabled, "Run".
6. Apply.
7. Save dashboard.
8. Click "Refresh Dashboard".

### Environment (with versions)?

Grafana Enterprise: 
10.2.0, 
10.1.5

Browsers:
Chrome Version 118.0.5993.118 (Official Build) (32-bit), 
Edge for Business Version 118.0.2088.76 (Official build) (64-bit)
Firefox 119.0 (64-bit)

### Grafana platform?

Amazon ECS (Docker)
Windows 10 Enterprise 64-bit 22H2 19045.3570 (Local)

### Datasource(s)?

redis-datasource

**Comment by usmangt** [comment]
Hi @ManIntelligent,

Thanks for opening this issue.

Can you please test this against other browsers e.g. Chrome, Firefox, etc so that we can rule out the possibility of it.

**Comment by ManIntelligent** [comment]
Hi @usmangt,

Thank you for raising the need for more information.
(Unfortunately) I was able to reproduce in both Chrome, Edge, and Firefox as well as on an AWS ECS hosted and local installation of Grafana. The updated details have been added to the issue description above.

**Comment by marefr** [comment]
Tested this locally and to me it seems like an issue with the redis data source since it works as expected with the Grafana Live scenario of the built-in test datasource. So I would suggest to open an issue at https://github.com/RedisGrafana/grafana-redis-datasource.

Happened to notice this comment which might hint that you're asking for is not supported: https://github.com/RedisGrafana/grafana-redis-datasource/issues/86#issuecomment-716997082

@mikhail-vl fyi
