### ISSUE TITLE
Alerting: Modify export 404's with custom root url

### ISSUE THREAD

**Issue by schoentoon** [grafana/grafana#77149]
### What happened?

We run multiple grafana instances within our k8s cluster. To accomplish this we have an ingress setup to have grafana behind `/namespace/grafana`. Grafana is also configured to understand this by having the `GF_SERVER_ROOT_URL` env variable set to the same path. Additionally `GF_SERVER_SERVE_FROM_SUB_PATH` is set to true as well. The modify export button on alerts will however link to `/namespace/grafana/namespace/grafana/alerting/<uid>/modify-export`. Which naturally results in a 404.

### What did you expect to happen?

I expected to end up on `/namespace/grafana/alerting/<uid>/modify-export` and not be greeted with a 404.

### Did this work before?

This feature was only added with 10.2, so no.

### How do we reproduce it?

1. Setup grafana with a custom `GF_SERVER_ROOT_URL` and `GF_SERVER_SERVE_FROM_SUB_PATH` variable. I used the following podman command to reproduce this locally: `podman run -it --rm -p 3000:3000 -e GF_SERVER_ROOT_URL=/namespace -e GF_SERVER_SERVE_FROM_SUB_PATH=true docker.io/grafana/grafana:10.2.0`
2. Setup some alert. Remember grafana would now be on http://127.0.0.1:3000/namespace
3. Go back to the alerts list and press modify export

### Environment (with versions)?

Grafana: 10.2.0

### Grafana platform?

Docker

**Comment by schoentoon** [comment]
Issue persists with `GF_SERVER_SERVE_FROM_SUB_PATH=false` and a reverse proxy in front of it. Similar issue pops up seemingly randomly in other parts of this UI as well.

**Comment by usmangt** [comment]
Hi @schoentoon,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by rwwiv** [comment]
I was able to reproduce this on latest `main`, this looks to be coming from the sub-URL passed to `locationService.push()` on these buttons.

Ex:
https://github.com/grafana/grafana/blob/03a7c65eadcf80c08832279252fc5022524bf1b2/public/app/features/alerting/unified/components/rules/RuleActionsButtons.tsx#L152-L155

**Comment by schoentoon** [comment]
Am I correct in thinking this should be included in grafana 10.2.1 (I do see the commit in there at least)? As I can still reproduce it on this version that came out yesterday.

**Comment by gillesdemey** [comment]
It looks like the PR wasn't back-ported, I'll create the back-port and it should be scheduled for 10.2.2 if we do another patch release between now and 10.3.
