### ISSUE TITLE
[Feat Req]: Elasticsearch templating term query order by doc count

### ISSUE THREAD

**Issue by conet** [grafana/grafana#7715]
Sorting of terms in templating query [is hardcoded](https://github.com/grafana/grafana/blob/d2dac02a2844a68a8c46bccd928183601c796946/public/app/plugins/datasource/elasticsearch/query_builder.js#L275) to ascending order by term value, since grafana can already sort terms alphabetically or numerically shouldn't this ordering request be removed to allow the user to use the default ordering (by doc count)?

Another possibility would be to expose datasource sorting but that would complicate things.

The reason behind this is that it is more useful to have terms ordered by doc count instead of by value (since ordering by value is supported anyway).

**Comment by mustafaakin** [comment]
Yeah, default ordering by term causes too much confusion, it would be much better if it would default to doc_count

**Comment by uecasm** [comment]
In Grafana 4.4, selecting to order a grouping by "term value" appears to select descending order, with no apparent way to select ascending ordering; the only other option is "doc count".  Which perhaps does what the OP wants, but still isn't ideal for other cases.

**Comment by conet** [comment]
Come on man, sorting by terms [is still hardcoded](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/query_builder.ts#L316) in master. Do I need to create a PR just to remove that config which makes absolutely no sense if sorting is possible in the front end. The default elasticsearch ordering, by doc count, is much more relevant, that is why the made it the default, so it it's too much work to make it configurable please just remove it.

Please note that this only applies to the templating queries (the ones that fetch the values of variables).

**Comment by Rohlik** [comment]
This is what I looking for. I also need dynamic values in my variables, values which have highest occurence in my Elasticsearch datasource.

**Comment by gbourke** [comment]
+1 for this feature

**Comment by nfx** [comment]
any update on this?
