### ISSUE TITLE
[Feature request] add org_role = "Read Only Editor"  in ldap.toml

### ISSUE THREAD

**Issue by IzekChen** [grafana/grafana#7716]
When I try to integrate ldap auth, I just want to give the users Read only editor permission.
But It seems we only can add "Admin", "Editor" and "Viewer".

**Comment by torkelo** [comment]
Did you try with `Read Only Editor` ? it should work

**Comment by IzekChen** [comment]
I already try that, that's not work.

**Comment by torkelo** [comment]
can you show me the ldap.toml config you tried?

**Comment by IzekChen** [comment]
I retry it again.
Yes, that's my bad. It work now.
Because I check wrong users page.

![image](https://cloud.githubusercontent.com/assets/7790230/23638899/5f9355e8-031f-11e7-8b42-154b210e328d.png)
