### ISSUE TITLE
[Bug] Table 

### ISSUE THREAD

**Issue by jaspereira** [grafana/grafana#7717]
Please include this information:
- What Grafana version are you using?
4.1.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu 16.04
- What did you do?
Table with Time Series Aggregations
- What was the expected result?
Show all the existing Metrics (Current and Max) in a time range of 24h
- What happened instead?
Only some of the metrics are showed. It was working fine in previous Grafana version. Reducing the time range to less then 24h shows more metrics, i.e choosing 1h Time range shows all metrics, increasing this Time Range reduces de number of metrics showed.

Showing 24h time range
![image](https://cloud.githubusercontent.com/assets/10101937/23548636/5d58e918-0000-11e7-988a-4bc6f8d78029.png)

Showing 12h time range
![image](https://cloud.githubusercontent.com/assets/10101937/23548661/74d5bc4c-0000-11e7-8e0f-bb87cc1db491.png)

**Comment by torkelo** [comment]
Influxdb 1.2 introduced a breaking change when they set a low value to max-row-limit, so queries no longer return all the data. You need to increase this InfluxDB  option.
