### ISSUE TITLE
Add plural values for time units in dashboard panels

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#77182]
**Why is this needed**:

Grafana dashboard panels support various time units like seconds, milliseconds, etc. At display time, values with a time unit are converted into something like "1 day, 1 week".

**However**, these values are not pluralized, so we end up with "3 hour", "5 day", "4 week". These should be made plural for any values greater than 1.0: "1.5 weeks", "8 days", "3 weeks".

**What would you like to be added**:

Modify all functions [like this one](https://github.com/grafana/grafana/blob/fd5ad38f3819d032e980f5297b36b4f5937d3929/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts#L45) to return pluralized values when dealing with any value other than 1.0

**Who is this feature for?**

All dashboard users

**Comment by san70sh** [comment]
@joeblubaugh can I work on this issue as part of Hacktoberfest?

**Comment by 123MwanjeMike** [comment]
Does this also apply to values less than 1? For example, does [this one](https://github.com/grafana/grafana/blob/fd5ad38f3819d032e980f5297b36b4f5937d3929/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts#L160) change to mins?

**Comment by joeblubaugh** [comment]
I suppose it depends on the formatting. "0.75 **minutes**" is common in English, but it's "3/4 of a **minute**"

**Comment by utkarshdeepak** [comment]
@joeblubaugh I have considered just 1 as a singular and remaining as a plural, as per English convention.
Can you please review the PR #77337 ?
