### ISSUE TITLE
Grafana: go-difflib package EOL

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#77184]
go-difflib go package is no longer maintained, it has reached EOL.
https://github.com/pmezard/go-difflib

Still in grafana go-difflib package is used. Is there any plan to replace go-difflib package??

**Comment by venkatbvc** [comment]
this go-difflib is coming from github.com/stretchr/testity go module.  There is an alternative https://github.com/martinohmann/go-difflib  which is based on  github.com/pmezard/go-difflib. Can we change ?
