### ISSUE TITLE
[Bug] elastic search datasource doesnt use host from url

### ISSUE THREAD

**Issue by devsschmidt** [grafana/grafana#7718]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
`version=4.1.2 commit=v4.1.2 compiled=2017-02-13T13:13:31+0100`
- What datasource are you using?
Elastic Search
- What OS are you running grafana on?
Debian Jessie 
- What did you do?
Added an Elastic Search Datasource with a valid URL (works from Shell with curl) and clicked on Save & 
Test
my URL was like http://abc.local:32794 and works just fine
- What was the expected result?
to have Access to elastic search
- What happened instead?
When i click on Save & Test Grafana said 
ERROR
502

and Grafana log Output is
`t=2017-03-03T13:18:23+0100 lvl=info msg="Request Completed" logger=context userId=2 orgId=2 uname=XXXXXXXXXX method=GET path=/XXXXXXXXX/_stats status=502 remote_addr=127.0.0.1 time_ms=30.002µs size=0`
grafana doenst use the host i've put in as remote_addr

**Comment by torkelo** [comment]
Did you specify direct or proxy access mode? 

In proxy access mode the request will go through grafana server, so the url you specify needs to be accessable from the server runnning grafana-server

**Comment by devsschmidt** [comment]
i specified the datasource as Proxy and tested the exact URL from a Shell of the Server grafana is installed on and it worked all fine

**Comment by torkelo** [comment]
strange, Grafana get's a 502 Bad Gateway response when it tries to issue a request to that url.

**Comment by devsschmidt** [comment]
i think ist rather strange that Grafana issues a request to `remote_addr=127.0.0.1` even though the url i've configured looked like `http://abc.local:32794`

**Comment by torkelo** [comment]
that is the http logger, showing the client making the initial request, not the internal request sent to ES

**Comment by devsschmidt** [comment]
is there anyway to fix the Situation here ?

**Comment by torkelo** [comment]
you could run network trace to investigate the traffic between grafana server and http://abc.local:32794 , maybe then you can figure out why it's returning 502

**Comment by devsschmidt** [comment]
found the reason for the bad Gateway. some admin have configured a Proxy which blocks certain Kinds of traffic aparrently. bypassing the Proxy is enough to make grafan work.
