### ISSUE TITLE
Alerting: Summary-Annotations > Can't change to another option once "Add new"  option is selected

### ISSUE THREAD

**Issue by tonypowa** [grafana/grafana#77194]
### What happened?

When creating a new alert in the older UI (`Grafana v10.0.3 (eb8dd72637)`) , in the step 4  (Summary and annotations), you are asked to pick an option from the drop-down menu, or **+ Add new**. If you select + Add new , it does not let you pick another option.

![image](https://github.com/grafana/grafana/assets/45235678/cd7a94af-6856-4fcf-882f-027f886d52f6)

The workaround is to type something and delete it. Then you get the drop-down option back.

This is not reproducible in later versions because the UI has changed. For example: not reproducible in Grafana v10.1.0 onward. 

### What did you expect to happen?

be able to pick another option from the drop-down menu, if you changed your mind

### Did this work before?

not sure

### How do we reproduce it?

![annotation-menu](https://github.com/grafana/grafana/assets/45235678/7e631c79-9206-4226-9ae5-fa40edba0dad)

1. go to Alerting > Alert rules > add new
2. scroll down to step 4
3. select + Add new option
4. try to select another option 

### Environment (with versions)?

Grafana: v10.0.3 (eb8dd72637)`
OS: Raspberry PI OS
Browser: Firefox, Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by armandgrillet** [comment]
Closing this as later versions of Grafana 10 fixed the issue but thanks for the report. We would not fix this in older versions without strong reasons.
