### ISSUE TITLE
Azure Monitor: Microsoft.NetworkCloud/clusters resources not showing up in resource picker for metrics

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#77224]
### What happened?

When trying to query metrics from Microsoft.NetworkCloud/clusters, the resources of that type do not show up under the resource picker.

Note that queries succeed in the Azure Portal. Seems like the namespace has not been added here yet: https://github.com/grafana/grafana/blob/dc0ff5a0aabfe074c78f07fef1acfcb5644a0039/public/app/plugins/datasource/azuremonitor/azureMetadata/resourceTypes.ts#L191

Could you help take a look @aangelisc ? thanks :)

### What did you expect to happen?

For resources of type Microsoft.NetworkCloud/clusters to show up in the resource picker

### Did this work before?

No

### How do we reproduce it?

1. Having a Microsoft.NetworkCloud/clusters (Azure Nexus) go to Grafana and try to create a panel for Azure Monitor metrics 
2. Notice how the resource won't show in the resource picker.

### Environment (with versions)?

Grafana: 9.5.12
OS: Windows
Browser: Edge

### Grafana platform?

None

### Datasource(s)?

Azure Monitor

**Comment by kayodeprinceMS** [comment]
Note that this resource type is covered in Azure docs for [supported metrics](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/metrics-index#microsoftnetworkcloud).

**Comment by mukesh-dua** [comment]
Just to add there are more to the list for Azure Operator Nexus:
1. Microsoft.NetworkCloud/clusters
2. Microsoft.NetworkCloud/bareMetalMachines
3. Microsoft.NetworkCloud/storageAppliances
4. Microsoft.ManagedNetworkFabric/networkDevices

Please ensure the support is added for each of these.

**Comment by aangelisc** [comment]
#77308 should fix this. If you could please review @jcolladokuri @mukesh-dua @kayodeprinceMS
