### ISSUE TITLE
Canvas: Consider adding link property to elements outside of datalink system

### ISSUE THREAD

**Issue by xkilian** [grafana/grafana#77246]
**Why is this needed**:

There is no current way to simply add a link to an Element.
When creating navigation elements in a Panel, some Elements are NOT linked to a metric as such they cannot have a link associated with them.

**What would you like to be added**:

In the Element configuration section.
Ability to add a http hyperlink to an Element so that it becomes clickable. This would be a link for the whole Element. NOt a datalink tied to a field.
When the object is clicked, follow directly the link (to new page or replce current page). Do NOT show a tooltip with a link in it.
The http link should support dashboard variables.

**Who is this feature for?**

Graphically represent navigation links. Provide links for Elements not tied to metric.
This is a basic feature that is often requested.

**Comment by xkilian** [comment]
Relaed to #79698

**Comment by nmarrs** [comment]
Hey @xkilian - thanks for raising up this issue - I think these two PRs (expanding [data link support vastly](https://github.com/grafana/grafana/pull/84142) + [one click access mode](https://github.com/grafana/grafana/pull/85430)) get us a little closer to this reality (with a current work around now being adding a phantom data link to a "hidden" property such as background image that will make the element able to include a link)


https://github.com/grafana/grafana/assets/22381771/5a87859f-754c-4ede-909b-941074717dd6

**Comment by nmarrs** [comment]
Addressed by https://github.com/grafana/grafana/pull/89079 🎉
