### ISSUE TITLE
The warning threshold was not reached, and the email was sent anyway

### ISSUE THREAD

**Issue by yyhhhhhh** [grafana/grafana#77253]
### What happened?

The threshold set by the grafana alarm rule was not reached, but an alarm email was sent with a null value
![image](https://github.com/grafana/grafana/assets/92375979/6aa7db29-be58-43e5-aafe-4d53b1b44bc0)

### What did you expect to happen?

I think the correct alarm email should be sent

### Did this work before?

It's my first time using it

### How do we reproduce it?

not sure

### Environment (with versions)?

Grafana: 8.3.3

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
hi @yyhhhhhh 

could you add the following info and open a new post in our [community forum](https://community.grafana.com/) instead? it sounds that your case is more of a configuration question than a bug in the program

- your no data and error handling config 
-https://grafana.com/docs/grafana/v8.3/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/#no-data-and-error-handling
- the status history of your alert  (alert>view)
- the query and expressions of your alert (remove sensitive data)


thank you
