### ISSUE TITLE
Grafana Always loads config from Defaults.ini and not grafana.ini

### ISSUE THREAD

**Issue by varunsrinath** [grafana/grafana#7725]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.x
- What datasource are you using?
graphite
- What OS are you running grafana on?
cent-os
- What did you do?
modified grafana demons to load config from a different directory and packaged a new rpm.
- What was the expected result?
Config should have loaded from grafana.ini from a custom location
- What happened instead?
The inti.d scrip clearly states its loading config from  /usr/**/grafana.ini, how ever when i start the service the demon always loads config from defaults.ini and overrides changes from grafana.ini

Additional Information

when I go service grafana-server status , it prints the conf dir and file as my custom one (grafana.ini). when i logged in as admin , i still see config details from defaults.ini

**Comment by torkelo** [comment]
defaults are loaded from defaults.ini and overrides from /etc/grafana/grafana.ini

make sure you uncomment a config line for it to take effect, the `;` char at the start is the start of a comment line and needs to be removed

**Comment by varunsrinath** [comment]
grafana.ini did not have the ; prefixed, despite of that it still did not load the values from grafana.ini

**Comment by torkelo** [comment]
Strange, please provide your uncommented grafana.ini options and the logs from Grafana.log

**Comment by mikequentel** [comment]
> make sure you uncomment a config line for it to take effect, the ; char at the start is the start of a comment line and needs to be removed

This is not obvious in the installation and configuration instructions. I had installed Grafana on RHEL 6 from an RPM and spent a lot of time trying to understand why custom settings were not being set from `grafana.ini` -- now understood thanks to comment of @torkelo above--one must uncomment the `;` for the setting to be used.

**Comment by daniellee** [comment]
@mikequentel  Added section at top of the configuration docs page, pointing this out. We get this question/problem a lot. (Semicolons are the recommended way to comment in .ini files but it does not seem to be common knowledge)

http://docs.grafana.org/installation/configuration/#comments-in-ini-files

**Comment by mikequentel** [comment]
@daniellee many thanks. The config file has a mix of `#` and `;` so it was not obvious to me that the `;` were also comments, even though I have seen `;` used before for commenting in other systems. The line at the top of http://docs.grafana.org/installation/configuration/#comments-in-ini-files definitely makes the nature of `;` clearer.

**Comment by gyustorm** [comment]
> grafana.ini did not have the ; prefixed, despite of that it still did not load the values from grafana.ini

maybe you should bring the field quote like "[users]" in:
```
[users]
# Default UI theme ("dark" or "light")
default_theme = light

```
when wanna overriding on color theme

**Comment by fchiorascu** [comment]
Hi @torkelo @daniellee I have a strange aspect under investigation: https://community.grafana.com/t/smtp-not-configured-check-your-grafana-ini-config-files-smtp-section/29220

any news?
