### ISSUE TITLE
[Bug] Date format for field returns "Invalid date" in Table

### ISSUE THREAD

**Issue by dhaners** [grafana/grafana#7726]
I am using Grafana 4.1.2 with an elasticsearch datasource. I have created a mapping for a field with the format of epoch milliseconds and I am trying to visualize this time data in a table. I am able to create and visualize time series graphs with this data but when given in a table format the data returns "Invalid date." 

![image](https://cloud.githubusercontent.com/assets/26175216/23572284/3f00fcc8-002b-11e7-93c6-927050ef5b77.png)

We see this in Grafana 4.1.1 as well as Grafana 4.1.2 but in Grafana 3.0.4 we can see the proper data displayed in the table:

![image](https://cloud.githubusercontent.com/assets/26175216/23572467/771d7dba-002c-11e7-8c9c-114abaebb36a.png)

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab and refresh graph and spot the __msearch request to elasticsearch, what is the response from that request (click response tab and copy paste the response here, want to know exactly how the Start Time field is returned by elasticsearch)

**Comment by dhaners** [comment]
This is the response given by elasticsearch for the table:

{"responses":[{"took":12313,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":31359,"max_score":0.0,"hits":[]},"aggregations":{"3":{"buckets":{"queue:(root.dev OR dev)":{"doc_count":7317,"5":{"doc_count_error_upper_bound":0,"sum_other_doc_count":7307,"buckets":[{"key":1488807992649,"key_as_string":"1488807992649","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7808","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxxxx","doc_count":1,"1":{"value":285380.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"com.abcd.click.job.test","doc_count":1,"1":{"value":285380.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":285380.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":285380.0}}]}}]}}]}}]}}]}},{"key":1488806971978,"key_as_string":"1488806971978","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7795","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":32540.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx ","doc_count":1,"1":{"value":32540.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":32540.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":32540.0}}]}}]}}]}}]}}]}},{"key":1488806919953,"key_as_string":"1488806919953","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7794","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":42811.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":42811.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":42811.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":42811.0}}]}}]}}]}}]}}]}},{"key":1488806875069,"key_as_string":"1488806875069","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7793","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":36206.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":36206.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":36206.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":36206.0}}]}}]}}]}}]}}]}},{"key":1488806839242,"key_as_string":"1488806839242","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7789","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":27332.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx ","doc_count":1,"1":{"value":27332.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":27332.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":27332.0}}]}}]}}]}}]}}]}},{"key":1488806800651,"key_as_string":"1488806800651","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7787","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":27903.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":27903.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":27903.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":27903.0}}]}}]}}]}}]}}]}},{"key":1488806764392,"key_as_string":"1488806764392","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7781","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":28449.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx “,"doc_count":1,"1":{"value":28449.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":28449.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":28449.0}}]}}]}}]}}]}}]}},{"key":1488806728113,"key_as_string":"1488806728113","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7780","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":29264.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":29264.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":29264.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":29264.0}}]}}]}}]}}]}}]}},{"key":1488806690330,"key_as_string":"1488806690330","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7779","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":27213.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx ","doc_count":1,"1":{"value":27213.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":27213.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":27213.0}}]}}]}}]}}]}}]}},{"key":1488806650132,"key_as_string":"1488806650132","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_7774","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":28038.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":28038.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":28038.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":28038.0}}]}}]}}]}}]}}]}}]}}}}}}]}

**Comment by torkelo** [comment]
cant see any Start Time field in the response, so not sure that can be the right response

**Comment by dhaners** [comment]
Elasticsearch is providing the response in the form of key/value pairs. The keys that being with "14888" are the start time values in epoch milliseconds. When I change the options to display the start time as a string you can see these values:

![image](https://cloud.githubusercontent.com/assets/26175216/23669211/921d2434-0320-11e7-855b-a8c319a496e6.png)

The issue I am facing is that Grafana is unable to properly display information of type "Date" in the Column Styles section of the Options tab, even though it was able to convert this information properly in previous versions.

**Comment by torkelo** [comment]
If the field is an Elasticsearch date in epoch format it should not be returned as a string but as a number.

**Comment by dhaners** [comment]
Okay, well here is the result as a number:

![image](https://cloud.githubusercontent.com/assets/26175216/24005238/b3a5bcea-0a25-11e7-8873-2ec57827fda8.png)

I arbitrarily set the units to milliseconds but any unit I set gives the same result. Again what I need is to be able to use the type "Date" so that I can convert the epoch format to an actual date. As I mentioned before this had worked in previous versions but it is not working in Grafana 4.1.1 or 4.1.2.

**Comment by torkelo** [comment]
I mean number in elasticsearch, it does not appear to index as ES date or be in ms epoch format, as it should then be returned as number by Elasticsearch

**Comment by dhaners** [comment]
If you are referring to the "key_as_string" property it appears in the elasticsearch response in grafana 3.0.4 as well but in that case the time data is still converted properly. Here is the response from elasticsearch where the information is displayed properly in grafana 3.0.4:

{"responses":[{"took":55,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":31449,"max_score":0.0,"hits":[]},"aggregations":{"3":{"buckets":{"queue:(root.dev OR dev)":{"doc_count":7610,"5":{"doc_count_error_upper_bound":0,"sum_other_doc_count":7600,"buckets":[{"key":1489671745383,"key_as_string":"1489671745383","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20357","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":283804.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"com.abcd.click.job.test","doc_count":1,"1":{"value":283804.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":283804.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":283804.0}}]}}]}}]}}]}}]}},{"key":1489667993698,"key_as_string":"1489667993698","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20323","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":230369.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"com.abcd.click.job.test","doc_count":1,"1":{"value":230369.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":230369.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":230369.0}}]}}]}}]}}]}}]}},{"key":1489667220783,"key_as_string":"1489667220783","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20282","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":24872.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxxxx","doc_count":1,"1":{"value":24872.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":24872.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":24872.0}}]}}]}}]}}]}}]}},{"key":1489667188493,"key_as_string":"1489667188493","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20279","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":23743.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxxx","doc_count":1,"1":{"value":23743.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":23743.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":23743.0}}]}}]}}]}}]}}]}},{"key":1489667157100,"key_as_string":"1489667157100","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20274","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":23795.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":23795.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":23795.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":23795.0}}]}}]}}]}}]}}]}},{"key":1489667120260,"key_as_string":"1489667120260","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20273","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxx","doc_count":1,"1":{"value":27586.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxxx","doc_count":1,"1":{"value":27586.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":27586.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":27586.0}}]}}]}}]}}]}}]}},{"key":1489667086178,"key_as_string":"1489667086178","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20272","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxx","doc_count":1,"1":{"value":25925.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxxx","doc_count":1,"1":{"value":25925.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":25925.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":25925.0}}]}}]}}]}}]}}]}},{"key":1489667056935,"key_as_string":"1489667056935","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20271","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxx","doc_count":1,"1":{"value":22225.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":22225.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":22225.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":22225.0}}]}}]}}]}}]}}]}},{"key":1489667019344,"key_as_string":"1489667019344","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20270","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxx","doc_count":1,"1":{"value":29463.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":29463.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":29463.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":29463.0}}]}}]}}]}}]}}]}},{"key":1489666983654,"key_as_string":"1489666983654","doc_count":1,"6":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"application_1488190062017_20269","doc_count":1,"7":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxx","doc_count":1,"1":{"value":26980.0},"8":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"xxxxxxx","doc_count":1,"1":{"value":26980.0},"9":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"finished","doc_count":1,"1":{"value":26980.0},"4":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"succeeded","doc_count":1,"1":{"value":26980.0}}]}}]}}]}}]}}]}}]}}}}}}]}

**Comment by torkelo** [comment]
what does you query look like? Do you have a date histogram?

**Comment by dhaners** [comment]
Here is the query:

![image](https://cloud.githubusercontent.com/assets/26175216/24225733/4fbbabaa-0f1f-11e7-94e4-94ccfd32863f.png)

I am using "Terms" for startedTime because I want to preserve the actual time rather than have Date Histogram place the data points into buckets. This is the same query for both versions of Grafana. Another thing I found was that I am still able to sort the information in the table by Start Time and the reordered Elapsed Time in both versions match.

**Comment by torkelo** [comment]
I see, you need to use date histogram for the date formating to be preserved, other wise key as string is used which makes the dare format invalid

**Comment by dhaners** [comment]
Just to clarify, this exact same graph with the same settings works just fine in the older version of Grafana, version 3.0.4:

![image](https://cloud.githubusercontent.com/assets/26175216/24257403/08a206ae-0fa8-11e7-8a68-761053458d79.png)

If what you say is correct then setting Date Histogram should work but as you can see that does not work either. 

![image](https://cloud.githubusercontent.com/assets/26175216/24257702/c5bf2190-0fa8-11e7-9dfc-03c06c09f646.png)

This looks like a problem with newer versions of Grafana, especially since there is literally no difference between the graphs aside from the Grafana version.

**Comment by torkelo** [comment]
Yes, looks like it, to fix an issue with elastic IP display we now look at key as string for terms aggregations. Date histogram needs to be the last group by for graft to process it properly (at least for time series)

**Comment by dhaners** [comment]
Thank you for clarifying that. Adding the start time to the last group by seems to show the Date properly again (I am still using Terms and it seems to work fine).

**Comment by daniellee** [comment]
This issue seems to be resolved. Closing.
