### ISSUE TITLE
DashboardScene: Legacy panel migrations are not executed

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#77260]
We have an issue with running panel migration handlers. Those migration handlers assume the argument passed to them is the full `PanelModel`. But, in scenes' `VizPanel` only [a limited PanelModel](https://github.com/grafana/scenes/blob/main/packages/scenes/src/components/VizPanel/VizPanel.tsx#L133C31-L133C31) is passed to those migration handlers, skipping options that might have been attached to the root of the `PanelModel`. A good example is [dashlist panel migration](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/dashlist/migrations.ts#L39). In a dashboard using `DashboardScene` this  migration will have no effect.

**Comment by torkelo** [comment]
@dprokop been trying to solve this one, but soo tricky :(
