### ISSUE TITLE
[Feature request]Adding existing editable fields to the organisation web UI

### ISSUE THREAD

**Issue by royemmerich** [grafana/grafana#7729]
I'm running Grafana v4.1.1

# Background
When creating/administering an organisation, one can only enter the organisation name at the moment. Diving into the code I noticed the [org.go](https://github.com/grafana/grafana/blob/master/pkg/models/org.go#L14) model has a few additional variables which aren't yet exposed in the web interface.

```go
type Org struct {
	Id      int64
	Version int
	Name    string

	Address1 string
	Address2 string
	City     string
	ZipCode  string
	State    string
	Country  string

	Created time.Time
	Updated time.Time
}
```

# Feature Request

Expose these additional variables as editable fields in the web interface.

**Comment by torkelo** [comment]
all of those are exposed in the org preferences view.

**Comment by royemmerich** [comment]
I now see that. Apologies for the oversight.

Still, I think a bit of UI consolidation is required as the settings for organisations are split across three separate locations.

# Global Orgs
Editing one of my organisations via the `Admin -> Global Orgs` link I can change the organisation name and administer the users but not see or modify the address info, as seen in the image below:

![screen shot 2017-03-06 at 16 47 37](https://cloud.githubusercontent.com/assets/3904395/23617242/bbb03794-028c-11e7-972b-fd98b5d31a48.png)

# Preferences + User Admin Page 2
Then via the `Preferences` page one can edit the address info and a few other options, with a link to a different page to the one on the `Global Orgs` page, where one can manage users as well as pending invitations.

Wouldn't it make sense to combine all these into a single organisation admin page?

**Comment by torkelo** [comment]
You are talking about the grafana server administration pages. Organization admins have no access to that page
