### ISSUE TITLE
[Bug] Inconsistent help message: graphana-cli

### ISSUE THREAD

**Issue by JeffAbrahamson** [grafana/grafana#7730]
# Version, etc.

This is using grafana version 4.1.2-1486989747 as installed from grafana's deb thus:

    deb https://packagecloud.io/grafana/stable/debian/ jessie main

running on an ubuntu 16.04 host (that is a vagrant instance) that identifies its kernel (via uname) as `4.4.0-65-generic`.

# What I want to do, what I expect

The manual leads me to think I can change the admin password thus:

    ubuntu@loire1:/tmp$ grafana-cli admin reset-admin-password myadmin
    Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
    ubuntu@loire1:/tmp$ 

This is confusing (but not the bug reported here), though I suspect it just wants to make sure it's got the right config file.  So I try asking for help thus:

    ubuntu@loire1:/tmp$ grafana-cli -h
    NAME:
       Grafana cli - 

    USAGE:
       grafana-cli [global options] command [command options] [arguments...]

    VERSION:
       4.1.2

    AUTHOR(S):
       Grafana Project <https://github.com/grafana/grafana> 

    COMMANDS:
       plugins	Manage plugins for grafana
       admin	Grafana admin commands
       help, h	Shows a list of commands or help for one command

    GLOBAL OPTIONS:
       --pluginsDir "/var/lib/grafana/plugins"	path to the grafana plugin directory [$GF_PLUGIN_DIR]
       --repo "https://grafana.net/api/plugins"	url to the plugin repository [$GF_PLUGIN_REPO]
       --debug, -d					enable debug logging
       --help, -h					show help
       --version, -v				print the version

    ubuntu@loire1:/tmp$ 

It looks like I can get more information by specifying the debug flag.  Let's try that.

    ubuntu@loire1:/tmp$ grafana-cli --debug admin reset-admin-password myadmin
    flag provided but not defined: -debug
    Usage of grafana-cli:
      -config string
	    path to config file
      -homepath string
	    path to grafana install/home path, defaults to working directory
    ubuntu@loire1:/tmp$ 

Ah, so I should use -config to specify the config path.  Let's try that:

    ubuntu@loire1:/tmp$ grafana-cli --debug -config /etc/grafana/grafana.ini admin reset-admin-password myadmin
    Incorrect Usage.

    NAME:
       Grafana cli - 

    USAGE:
       grafana-cli [global options] command [command options] [arguments...]

    VERSION:
       4.1.2

    AUTHOR(S):
       Grafana Project <https://github.com/grafana/grafana> 

    COMMANDS:
       plugins	Manage plugins for grafana
       admin	Grafana admin commands
       help, h	Shows a list of commands or help for one command

    GLOBAL OPTIONS:
       --pluginsDir "/var/lib/grafana/plugins"	path to the grafana plugin directory [$GF_PLUGIN_DIR]
       --repo "https://grafana.net/api/plugins"	url to the plugin repository [$GF_PLUGIN_REPO]
       --debug, -d					enable debug logging
       --help, -h					show help
       --version, -v				print the version

    flag provided but not defined: -configubuntu@loire1:/tmp$ 
    ubuntu@loire1:/tmp$

That didn't work: the config flag was provided and not defined.  In addition, the help message failed to emit a newline at the end.

Maybe it wants an equal sign rather than a space, despite the help text.

    ubuntu@loire1:/tmp$ grafana-cli --debug -config=/etc/grafana/grafana.ini admin reset-admin-password myadmin
    Incorrect Usage.

    NAME:
       Grafana cli - 

    USAGE:
       grafana-cli [global options] command [command options] [arguments...]

    VERSION:
       4.1.2

    AUTHOR(S):
       Grafana Project <https://github.com/grafana/grafana> 

    COMMANDS:
       plugins	Manage plugins for grafana
       admin	Grafana admin commands
       help, h	Shows a list of commands or help for one command

    GLOBAL OPTIONS:
       --pluginsDir "/var/lib/grafana/plugins"	path to the grafana plugin directory [$GF_PLUGIN_DIR]
       --repo "https://grafana.net/api/plugins"	url to the plugin repository [$GF_PLUGIN_REPO]
       --debug, -d					enable debug logging
       --help, -h					show help
       --version, -v				print the version

    flag provided but not defined: -configubuntu@loire1:/tmp$ 
    ubuntu@loire1:/tmp$ 

Nope, same problem.  I try repeating this with homepath (set to `/etc/grafana/`, as a first guess).  Same error: flag provided but not defined.  I start to suspect it means "not defined in the code" rather than "you didn't provide a value", in which case "`unknown flag: config`" would have been a bit clearer.

I'm not yet clear if my travails about admin passwords represent a bug in my head or in the code, but I think the help text could use some help.  Since I'm not precisely sure what _should_ happen, I'll summarise thus:
* missing newline
* inconsistent information about what flags are available (config, homepath, or not)
* unclear error message: is it the flag that is not defined in the code or the flag's value on the commandline?
* if config and homepath are allowed, perhaps define what is meant by them.  Especially homepath, since config I can find by looking at how I invoke grafana.

**Comment by torkelo** [comment]
home path is explained, one one of your outputs:

```
Usage of grafana-cli:
  -config string
    path to config file
  -homepath string
    path to grafana install/home path, defaults to working directory
```

grafana is by default installed in `/usr/share/grafana` try specifing that as homepath

**Comment by JeffAbrahamson** [comment]
That may be the intended meaning of `-homepath`, but note that `grafana-cli` still complains about the flag on providing it:

    ubuntu@loire1:/tmp$ grafana-cli -homepath /usr/share/grafana admin reset-admin-password myadmin
    Incorrect Usage.

    NAME:
       Grafana cli - ubuntu@loire1:/tmp$ grafana-cli -homepath /usr/share/grafana.ini admin reset-admin-password myadmin
Incorrect Usage.

NAME:
   Grafana cli - 

USAGE:
   grafana-cli [global options] command [command options] [arguments...]
   
VERSION:
   4.1.2
   
AUTHOR(S):
   Grafana Project <https://github.com/grafana/grafana> 
   
COMMANDS:
   plugins	Manage plugins for grafana
   admin	Grafana admin commands
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --pluginsDir "/var/lib/grafana/plugins"	path to the grafana plugin directory [$GF_PLUGIN_DIR]
   --repo "https://grafana.net/api/plugins"	url to the plugin repository [$GF_PLUGIN_REPO]
   --debug, -d					enable debug logging
   --help, -h					show help
   --version, -v				print the version
   
flag provided but not defined: -homepathubuntu@loire1:/tmp$ 


    USAGE:
       grafana-cli [global options] command [command options] [arguments...]

    VERSION:
       4.1.2

    AUTHOR(S):
       Grafana Project <https://github.com/grafana/grafana> 

    COMMANDS:
       plugins	Manage plugins for grafana
       admin	Grafana admin commands
       help, h	Shows a list of commands or help for one command

    GLOBAL OPTIONS:
       --pluginsDir "/var/lib/grafana/plugins"	path to the grafana plugin directory [$GF_PLUGIN_DIR]
       --repo "https://grafana.net/api/plugins"	url to the plugin repository [$GF_PLUGIN_REPO]
       --debug, -d					enable debug logging
       --help, -h					show help
       --version, -v				print the version

    flag provided but not defined: -homepathubuntu@loire1:/tmp$

**Comment by mbuyukkarakas** [comment]
I have the same problem. The error messages are very confusing.

**Comment by zhxiaohe** [comment]
cd the '/usr/share/grafana'   directory,  then start server..

`[root@test share]# /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini   --pidfile= cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath
[root@test share]# cd /usr/share/grafana
[root@test grafana]# /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini   --pidfile= cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins 
INFO[11-07|22:51:32] Starting Grafana                         logger=main version=4.2.0 commit=349f3eb compiled=2017-03-22T18:06:41+0800
INFO[11-07|22:51:32] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO[11-07|22:51:32] Config loaded from                       logger=settings file=/etc/grafana/grafana.ini
INFO[11-07|22:51:32] Config overriden from command line       logger=settings arg="default.paths.data=/var/lib/grafana"`

**Comment by zhxiaohe** [comment]
cd /usr/share/grafana && /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini

**Comment by manashmndl** [comment]
@zhxiaohe Thanks so much :confetti_ball:

**Comment by f9n** [comment]
```bash
$ sudo systemctl status grafana
grafana.service - Grafana service
   Loaded: loaded (/usr/lib/systemd/system/grafana.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-01-03 01:28:19 +03; 18s ago
  Process: 20014 ExecStart=/usr/bin/grafana-server --config=/etc/grafana.ini (code=exited, status=1/FAILURE)
 Main PID: 20014 (code=exited, status=1/FAILURE)

Jan 03 01:28:19 effy grafana-server[20014]: t=2019-01-03T01:28:19+0300 lvl=info msg="Starting DB migration" logger=migrator
Jan 03 01:28:19 effy grafana-server[20014]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:28:19 effy grafana-server[20014]: t=2019-01-03T01:28:19+0300 lvl=info msg="Initializing SearchService" logger=server
Jan 03 01:28:19 effy grafana-server[20014]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:28:19 effy grafana-server[20014]: t=2019-01-03T01:28:19+0300 lvl=info msg="Initializing RenderingService" logger=server
Jan 03 01:28:19 effy grafana-server[20014]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:28:19 effy grafana-server[20014]: t=2019-01-03T01:28:19+0300 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: mkdir /usr/share/grafana/data/png: read-only file system"
Jan 03 01:28:19 effy grafana-server[20014]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:28:19 effy systemd[1]: grafana.service: Main process exited, code=exited, status=1/FAILURE
Jan 03 01:28:19 effy systemd[1]: grafana.service: Failed with result 'exit-code'.

$ # After running this command. It worked for me.
$ sudo grafana-server --config=/etc/grafana.ini --homepath=/usr/share/grafana
INFO[01-03|01:30:19] Starting Grafana                         logger=server version=5.4.2 commit=d812109ebf branch=makepkg compiled=2018-12-13T15:49:23+0300
INFO[01-03|01:30:19] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO[01-03|01:30:19] Config loaded from                       logger=settings file=/etc/grafana.ini
INFO[01-03|01:30:19] Path Home                                logger=settings path=/usr/share/grafana
INFO[01-03|01:30:19] Path Data                                logger=settings path=/usr/share/grafana/data
INFO[01-03|01:30:19] Path Logs                                logger=settings path=/usr/share/grafana/data/log
INFO[01-03|01:30:19] Path Plugins                             logger=settings path=/usr/share/grafana/data/plugins
INFO[01-03|01:30:19] Path Provisioning                        logger=settings path=/usr/share/grafana/conf/provisioning
INFO[01-03|01:30:19] App mode production                      logger=settings
INFO[01-03|01:30:19] Initializing HTTPServer                  logger=server
INFO[01-03|01:30:19] Initializing SqlStore                    logger=server
INFO[01-03|01:30:19] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[01-03|01:30:19] Starting DB migration                    logger=migrator
INFO[01-03|01:30:19] Initializing SearchService               logger=server
INFO[01-03|01:30:19] Initializing RenderingService            logger=server
INFO[01-03|01:30:19] Initializing AlertingService             logger=server
INFO[01-03|01:30:19] Initializing DatasourceCacheService      logger=server
INFO[01-03|01:30:19] Initializing HooksService                logger=server
INFO[01-03|01:30:19] Initializing InternalMetricsService      logger=server
INFO[01-03|01:30:19] Initializing CleanUpService              logger=server
INFO[01-03|01:30:19] Initializing NotificationService         logger=server
INFO[01-03|01:30:19] Initializing ProvisioningService         logger=server
EROR[01-03|01:30:19] cant read datasource provisioning files from directory logger=provisioning.datasources path=/usr/share/grafana/conf/provisioning/datasources
INFO[01-03|01:30:19] Initializing PluginManager               logger=server
INFO[01-03|01:30:19] Starting plugin search                   logger=plugins
INFO[01-03|01:30:19] Plugin dir created                       logger=plugins dir=/usr/share/grafana/data/plugins
INFO[01-03|01:30:19] Initializing TracingService              logger=server
EROR[01-03|01:30:19] cant read dashboard provisioning files from directory logger=provisioning.dashboard path=/usr/share/grafana/conf/provisioning/dashboards
INFO[01-03|01:30:19] Initializing Stream Manager 
INFO[01-03|01:30:19] HTTP Server Listen                       logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
INFO[01-03|01:30:24] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=[::1] time_ms=1 size=29 referer=
^CINFO[01-03|01:31:18] Shutdown started                         logger=server reason="System signal: interrupt"
INFO[01-03|01:31:18] Stopped ProvisioningService              logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped PluginManager                    logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped NotificationService              logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped TracingService                   logger=server reason=nil
INFO[01-03|01:31:18] Stopped InternalMetricsService           logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped Stream Manager 
INFO[01-03|01:31:18] Stopped CleanUpService                   logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped RenderingService                 logger=server reason=nil
INFO[01-03|01:31:18] Stopped AlertingService                  logger=server reason="context canceled"
INFO[01-03|01:31:18] Stopped HTTPServer                       logger=server reason=nil
EROR[01-03|01:31:18] Server shutdown                          logger=server reason="System signal: interrupt"
...
Control-C
$ # Then, the grafana service worked too
$ sudo systemctl start grafana
$ sudo systemctl status grafana
● grafana.service - Grafana service
   Loaded: loaded (/usr/lib/systemd/system/grafana.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-01-03 01:31:27 +03; 2min 13s ago
 Main PID: 20234 (grafana-server)
    Tasks: 14 (limit: 4915)
   Memory: 17.0M
   CGroup: /system.slice/grafana.service
           └─20234 /usr/bin/grafana-server --config=/etc/grafana.ini

Jan 03 01:31:27 effy grafana-server[20234]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:31:27 effy grafana-server[20234]: t=2019-01-03T01:31:27+0300 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/usr/share/grafana/conf/prov>
Jan 03 01:31:27 effy grafana-server[20234]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:31:27 effy grafana-server[20234]: t=2019-01-03T01:31:27+0300 lvl=eror msg="Problem reading image dir" logger=cleanup error="open /usr/share/grafana/data/png: permission denied"
Jan 03 01:31:27 effy grafana-server[20234]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:31:27 effy grafana-server[20234]: t=2019-01-03T01:31:27+0300 lvl=info msg="Initializing Stream Manager"
Jan 03 01:31:27 effy grafana-server[20234]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:31:27 effy grafana-server[20234]: t=2019-01-03T01:31:27+0300 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
Jan 03 01:31:27 effy grafana-server[20234]: FileLogWriter("/usr/share/grafana/data/log/grafana.log"): Rotate: rename /usr/share/grafana/data/log/grafana.log /usr/share/grafana/data/log/grafana.log.2019-01>
Jan 03 01:32:27 effy grafana-server[20234]: 2019/01/03 01:32:27 error garbage collecting session files: open /usr/share/grafana/data/sessions: permission denied
```
