### ISSUE TITLE
[Feature request] Introduce customisable branding options per (sub-)organisation

### ISSUE THREAD

**Issue by royemmerich** [grafana/grafana#7731]
I'm running Grafana v4.1.1

# Background
This feature request is related to feature request #4893

# Feature Request
As we all know, branding is extremely important in business. I would very much like to provide the option of (sub-)organisation specific branding to my customers for the dashboards, email communication and alert notification via the various supported platforms (e.g. email).

# Use case
As part of its complete solution, **company X** hosts a Grafana server for customers A, B & C. Each of these **company X** customers have their own customers. Company A wants their customers to log into the data visualisation portal and be faced with company A branding.

For an additional fee, **company X** should be able to rebrand organisation A's sub-portal with organisation A's logo (and possibly customer specific CSS styling).

**Comment by pkolyvas** [comment]
@royemmerich I'm going to close this feature as it duplicates functionality available in Grafana Enterprise. At the current time, we don't have any plans to implement something similar in the Open Source tool. 

My calendar is always open to discuss any needs related to use of Open Source Grafana, so please don't hesitate to connect; I'm here to listen (contact links on my GitHub profile page).
