### ISSUE TITLE
Connections/Datasources: 404 Page not found and cannot edit datasources, also Connections is missing

### ISSUE THREAD

**Issue by lenaxia** [grafana/grafana#77332]
### What happened?

When going to Administration, a new box pops up saying that datasources has moved to "Connections", when I click the link, it takes me to a page that shows my current datasources, but at the top it says "Page not found" and there is no way to edit the datasources. 

Also the Connections option is missing from the left navigation bar as described here: https://grafana.com/docs/grafana/latest/administration/data-source-management/

![image](https://github.com/grafana/grafana/assets/6321838/ecd8ebba-f86a-41c1-8f25-7eef1498e448)

![image](https://github.com/grafana/grafana/assets/6321838/dd8756ce-ef86-43a6-8018-ee03b0cbc047)

Logs when accessing datasources page:

```
logger=context userId=2 orgId=1 uname=<username> t=2023-10-29T01:34:07.300570077Z level=info msg="Access denied" userID=2 accessErrorID=ACE5143284481 permissions="any(datasources:explore all of datasources:read, any of datasources:create, datasources:delete, datasources:write)"
logger=context userId=2 orgId=1 uname=<username> t=2023-10-29T01:34:07.300640705Z level=info msg="Request Completed" method=GET path=/connections/datasources status=302 remote_addr=192.168.0.1 time_ms=11 duration=11.350352ms size=24 referer= handler=/connections/datasources
logger=context userId=2 orgId=1 uname=<username> t=2023-10-29T01:34:08.530079752Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.0.1 time_ms=13 duration=13.277433ms size=0 referer= handler=/api/live/ws
```

### What did you expect to happen?

Take me to a page where I can edit the datasources

### Did this work before?

Yes

### How do we reproduce it?

1. Install Grafana
2. Goto datasources
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.1.5 (849c612fcb
Grafana Helm Chart: 6.61.1
OS: Kubernetes
Browser: Edge and Firefox both show this behavior

Helm Release: https://github.com/lenaxia/home-ops-prod/blob/a2819d78039043dfafd99973fa0b4a34debc0a6e/cluster/apps/monitoring/grafana/app/helm-release.yaml

### Grafana platform?

Kubernetes

**Comment by lenaxia** [comment]
Due to oauth sync only assigning viewer to users

**Comment by cjetty** [comment]
@lenaxia  How did you fix this issue. I am facing the same issue after Grafana Upgrade
