### ISSUE TITLE
Retrieve intrinsic attributes from Tempo API

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#77368]
As originally pointed out [in this comment](https://github.com/grafana/grafana/pull/77146#issuecomment-1779511110), instead of hardcoding intrinsic attributes such as `status` or `duration` in Grafana, we could retrieve them from the Tempo API, more precisely the `search/tags` endpoint, which we already call. At the moment, there are mainly two problems to be addressed to apply this approach:
- Not all intrinsic attributes seem to be returned, as noted [in this Tempo issue](https://github.com/grafana/tempo/issues/3081)
- The Monaco editor, used as TraceQL query editor, requires the intrinsic attributes when mounted, so we should check how to handle a dynamic list and how the editor reacts to the changes

**Comment by joey-grafana** [comment]
Yes we retrieve the intrinsics from the API response and we have a fallback list also.
