### ISSUE TITLE
Missing 'alias' in email notification

### ISSUE THREAD

**Issue by MonicaMagoniCom** [grafana/grafana#77360]
### What happened?

Starting with Grafana 9, email template changed a lot and right now (also in Grafana 10) it is not possible to use 'alias' for Elasticsearch alerts inside email notification. 

### What did you expect to happen?

I would like to see the alias field as before or at least understand how to modify the 'ng_alert_notification.html' in order to see it

### Did this work before?

yes it worked before Grafana 9

### How do we reproduce it?

Create an alert based on elasticsearch data source where alias are populated

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch

**Comment by tonypowa** [comment]
Hi @MonicaMagoniCom 
Could you share the template that used to worked before v9 in the [community forum](https://community.grafana.com/)?
The community might be able to help you, and GitHub is mainly used for tracking bugs and feature requests.
Thank you
