### ISSUE TITLE
Create an extendable Filter component for list views

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#77364]
Create a component for filtering tabular/list data, based on the [designs](https://www.figma.com/file/Jk9PWNElaPZh2oSBWOxoWm/Joseph-Breitreiter-%7C-List-View---In-Progress?type=design&node-id=436-2&mode=design&t=uLdyYpbRbEBM5SiC-0).

The component is based on the behavior of the [AdHocFilter](https://github.com/grafana/grafana/blob/main/public/app/features/variables/adhoc/picker/AdHocFilter.tsx) component, but with updated UI to match the new form styles.

**Comment by torkelo** [comment]
The design seems like a small step back from scenes design, where inline label feels connected to the input (and more similar to other design systems that have similar inline labels). 

Variables: 
![Screenshot from 2023-12-12 09-23-59](https://github.com/grafana/grafana/assets/10999/f92b2e0a-5760-49d2-ab0c-3050b30de318)

Adhoc filters:
![image](https://github.com/grafana/grafana/assets/10999/8831e95e-137e-4981-83ea-b09ef885f2fc)

The remove action being attached to the filter as one block feel also pretty good as it makes the filter a single unit and more clear that the remove action is for this unit (we can switch to trash icon if that would help).

**Comment by Clarity-89** [comment]
> The design seems like a small step back from scenes design, where inline label feels connected to the input (and more similar to other design systems that have similar inline labels).
> 
> Variables: ![Screenshot from 2023-12-12 09-23-59](https://private-user-images.githubusercontent.com/10999/289794334-f92b2e0a-5760-49d2-ab0c-3050b30de318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzAzOTQsIm5iZiI6MTcwMjM3MDA5NCwicGF0aCI6Ii8xMDk5OS8yODk3OTQzMzQtZjkyYjJlMGEtNTc2MC00OWQyLWFiMGMtMzA1MGIzMGRlMzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4MzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NTkwNjY5YWM5MGZmZTcyYzUyYTk1MGNlZDg4MGIyYWQ0NmQzMzUyOGJkYzQ3ZGFmMWYzNzNkNGI2OGQ2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bXrC7_xLyqhgJuBA-VB-GD3mTiLSNI16Qo5o9N9_gTc)
> 
> Adhoc filters: ![image](https://private-user-images.githubusercontent.com/10999/289794682-8831e95e-137e-4981-83ea-b09ef885f2fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzAzOTQsIm5iZiI6MTcwMjM3MDA5NCwicGF0aCI6Ii8xMDk5OS8yODk3OTQ2ODItODgzMWU5NWUtMTM3ZS00OTgxLTgzZWEtYjA5ZWY4ODVmMmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA4MzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTgzYjQ4MThjMDI0NjQ4MDIwZTlmZDRmNjQxYmFkNmM3N2NkOTQ0MjM1NDNkMGNjYTdjMmEzZjc2OTU1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_arGBsbR5bXrcvvNLqCVgPEZrFuOtXFU79IzjiiTsc)
> 
> The remove action being attached to the filter as one block feel also pretty good as it makes the filter a single unit and more clear that the remove action is for this unit (we can switch to trash icon if that would help).

cc @breitreiter

**Comment by torkelo** [comment]
The other thing to consider is that the variable and filter controls needs to work on the canvas background (if we are to use the same component in dashboards and standard pages). And using secondary background in labels does not work well on canvas (too high contrast difference). 

Opted to use primary bg for the label. this makes them look a bit different in light and dark but sort of works. 

Light theme in dashboards 
![Screenshot from 2023-12-12 09-48-12](https://github.com/grafana/grafana/assets/10999/335c02a3-65ea-4a18-8ca1-2a212aec2725)

Dark theme in dashboards:
![Screenshot from 2023-12-12 09-48-47](https://github.com/grafana/grafana/assets/10999/b54520b5-b9df-483a-8629-2779398f0198)

Light theme page: 
![image](https://github.com/grafana/grafana/assets/10999/c7e71680-96a2-4993-83b5-939b806bc301)


dark theme page: 
![Screenshot from 2023-12-12 09-49-21](https://github.com/grafana/grafana/assets/10999/3d7f23a9-c110-4f8e-b492-a7fddf1b246e)
