### ISSUE TITLE
bug: serviceaccount token is not bound by `auth.api_key_max_seconds_to_live`

### ISSUE THREAD

**Issue by mhulscher** [grafana/grafana#77362]
### What happened?

I added the following to my `grafana.ini`:

```yaml
  auth:
    api_key_max_seconds_to_live: 15552000 # 180 days
```

with the intent that serviceaccount tokens should expire after no more than 180 days.

Serviceaccount tokens do not seem to be affected by this configuration. I do not see an equivalent configuration that specifically targets serviceaccount tokens.

### What did you expect to happen?

My tokens should have a limit expiration.

### Did this work before?

N/A

### How do we reproduce it?

1. Configure `auth.api_key_max_seconds_to_live`
2. Create a serviceaccount and generate a token without expiration
3. Observe that token has no expiration

### Environment (with versions)?

Grafana: 10.1.5
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by mgyongyosi** [comment]
Hey @mhulscher,

You can use the `service_accounts.token_expiration_day_limit` settings with service accounts! More info [here](https://grafana.com/docs/grafana/latest/administration/service-accounts/#service-account-token-expiration-dates).

**Comment by mhulscher** [comment]
Thank you @mgyongyosi . I wasn't able to find this setting because it does not appear here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
