### ISSUE TITLE
Dashboards: AWS/KafkaConnect namespace not present in cloudwatch metrics namespace list

### ISSUE THREAD

**Issue by Sharu95** [grafana/grafana#77381]
### What happened?

I try to set up MSK Connect metrics for a connector in our AWS/MSK environment. Using the cloudwatch data source and the code interface with metrics queries, the metrics are available and I get values in Grafana. See picture below:

![Screenshot 2023-10-30 at 15 14 34](https://github.com/grafana/grafana/assets/14542723/750ebe9f-c531-4ccc-beb4-bd63af158f72)

However, when trying to use the builder interface to find the namespace in the `Namespace` dropdown list, it does not seem to be there.

![image](https://github.com/grafana/grafana/assets/14542723/c58bee29-6256-471d-bf36-25b150cb3f00)

From what I see in the source code, it seems like it's not supported yet: 

https://github.com/grafana/grafana/blob/c5a7afce44070e5008bdfbfeb39f1c3841d77d87/pkg/tsdb/cloudwatch/metric_find_query.go#L90

https://github.com/grafana/grafana/blob/c5a7afce44070e5008bdfbfeb39f1c3841d77d87/pkg/tsdb/cloudwatch/metric_find_query.go#L183C2-L183C2 (edited) 

**What would you like to be added**:
Initially, it seemed like the metric namespace was not supported, but it is, through the metrics queries. It would be great to add the dropdown item as well

**Who is this feature for?**
Anyone using the MSK service in AWS, particularly the MSK Connect service.

### What did you expect to happen?

I expected to see the `AWS/KafkaConnect` namespace in the dropdown list

### Did this work before?

No

### How do we reproduce it?

1. Select cloudwatch as data source in grafana 
2. From the dropdown list, search for `AWS/KafkaConnect`

### Is the bug inside a dashboard panel?

NA

### Grafana platform?

Docker

### Datasource(s)?

cloudwatch

**Comment by kevinwcyu** [comment]
Hi @Sharu95, do you have a link to AWS documentation that shows a list of the metrics that should be available for this namespace? I can't seem to find any documentation on the namespace `AWS/KafkaConnect`, I'm not sure if I looked in the correct place for it.

**Comment by Sharu95** [comment]
Hi @kevinwcyu, sure thing. Here are the list of metrics; https://docs.aws.amazon.com/msk/latest/developerguide/mkc-monitoring-overview.html

**Comment by Sharu95** [comment]
Oddly enough, the namespace `AWS/KafkaConnect`is difficult to find, but if you have access to the AWS console and cloudwatch metrics, it is in there. The official doc under https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html, states that the namespace for MSK Connect is `ConnectorName`, but this is outdated I think. Someone from AWS has to verify that I suppose. 

<img width="1258" alt="image" src="https://github.com/grafana/grafana/assets/14542723/8586b93c-047b-4138-b3e3-940865cfdb4c">

**Comment by kevinwcyu** [comment]
Hi @Sharu95, for now you can workaround this if you type "AWS/KafkaConnect" in the namespace dropdown and hit enter to manually add it, you can do the same for the metric dropdown too.

**Comment by sarahzinger** [comment]
Moving this to "Next", it seems to me like an easy fix for us to add "AWS/KafkaConnect" to our list of hard coded metrics. Unfortunately aws does not really offer us an api, so everytime they update the list of namespaces, we have to manually update the list ourselves as well.

**Comment by kevinwcyu** [comment]
Closed by https://github.com/grafana/grafana/pull/79532
