### ISSUE TITLE
Need light theme with white background png graphs

### ISSUE THREAD

**Issue by maklaut** [grafana/grafana#774]
I'm using light theme with png graphs because it's more printer friendly (less toner and save colors in legend).
Why I choose png:
1. I can save png graphs with whole html page and use these graphs in email, wiki etc. But unfortunately png graphs lost titles (titles is in html).
2. While printed flot graphs lost all colors from legend (PNG is ok).

But png graphs missing such a "must have" feature as a hover hints :(
I need to stop using png graphs if you can fix legend colors (#775) and implement "Copy png-graph URL" (#776).

Now I using this script to patch png-graphs color:
```
E1='s/bgcolor=1f1f1f/bgcolor=ffffff/'
E2='s/fgcolor=BBBFC2/fgcolor=000000/'
sed -e "$E1" -e "$E2" -i app/app*.js

**Comment by bl4ckmesa** [comment]
For anyone who looking at this now, as I did, when looking for white-themed PNGs, and being new at Grafana, I want to point out that this is a frontend for (most likely) Graphite, and it's actually the Graphite Render API that we really care about here.  His idea of replacing the bgcolor and fgcolor directive work just fine for most situations, and you can add a title as simply as appending "&title=Your%20Title" to the end of the graph string.

Source: http://graphite.readthedocs.org/en/latest/render_api.html

**Comment by maklaut** [comment]
Hmm, it's some kind of injection vulnerability.
