### ISSUE TITLE
[Bug] grafana generates empty find query to graphite -> 422 Unprocessable Entity

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#7740]
Grafana v4.1.2 (commit: v4.1.2)
on a customer's installation, they have a query like `alias(scale(divideSeries(#A, #B), 100), 'foo')`
this generates a http request to `https://grafana.foo.com/api/datasources/proxy/1/metrics/find/?query=`
to which graphite returns `http 422 Unprocessable Entity` which causes an error box in graphite
(the viz however seems to work fine)

**Comment by torkelo** [comment]
> on a customer's installation, they have a query like alias(scale(divideSeries(#A, #B), 100), 'foo')
this generates a http request to https://grafana.foo.com/api/datasources/proxy/1/metrics/find/?query=

How does this query generate a metricFind request? I mean that is only used when doing a template variable query (finding values), and clicking on the metric segments in the query editor. So when is his query generated, when they try to change a metric path?

**Comment by Alexul** [comment]
Can reproduce, that query generated when going from any other tab or just from a dashboard view to a "Metrics" tab.

**Comment by Dieterbe** [comment]
yes. what Alex said. go to the metrics tab and it'll trigger find queries for all the queries that are defined, most work just fine because they are normal metrics patterns, but that particular one fails.

**Comment by torkelo** [comment]
ah, that helped me replicate it and fix it :)
