### ISSUE TITLE
Log: Inconsistent log mode

### ISSUE THREAD

**Issue by franzwong** [grafana/grafana#77413]
### What happened?

The default log mode is "console" in docker image.

https://github.com/grafana/grafana/blob/release-10.2.0/packaging/docker/run.sh#L85

### What did you expect to happen?

Log mode is "console file" which is specified by the [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#mode)

### Did this work before?

No

### How do we reproduce it?

1. Start grafana docker image
2. Check if /var/log/grafana/grafan.log exists inside docker image

### Environment (with versions)?

Grafana: 10.2.0
OS: MacOS
Browser: N/A

### Grafana platform?

Docker

**Comment by mildwonkey** [comment]
Hi @franzwong , 

I'm unable to reproduce the issue you are reporting on MacOS with the latest Grafana docker image, can you please help with the reproduction case? 

When I run it with `docker run -d --name=grafana -p 3000:3000 grafana/grafana`,  the expected logging output appears in `docker logs {container id}`, and I don't see a log file in the docker container (the directory, `/var/log/grafana` is created, but that's expected).

Is the any additional information you can provide? Are you using any env vars or configuration overrides?

**Comment by franzwong** [comment]
@mildwonkey Thanks for the response. 

> I don't see a log file in the docker container

That's the problem I have. The documentation said log should be written to BOTH stdout/stderr and file. However, the docker image ONLY outputs to the stdout/stderr.

I expect the file exists inside `/var/log/grafana`.

```
docker run -d --name=grafana -p 3000:3000 grafana/grafana
c02c55bab517c604b9774d615fb92d66859c5368e544a17f538df3231b602f12
➜  ~ docker exec -it grafana bash
c02c55bab517:/usr/share/grafana$ ls -l /var/log/grafana/
total 0
c02c55bab517:/usr/share/grafana$ exit
exit
➜  ~ docker logs grafana | wc -l
1081
```

**Comment by franzwong** [comment]
@mildwonkey Or the documentation should mention about the behaviour of docker container if the default behaviour is different.

**Comment by mildwonkey** [comment]
Indeed, we could add some notes to the [grafana container docker hub](https://hub.docker.com/r/grafana/grafana) page that explains any docker-specific modifications to the defaults.
