### ISSUE TITLE
[Supporting the Platform] 259081a: Horizontal scroll bar appears at bottom of menu at small widths

### ISSUE THREAD

**Issue by taleena** [grafana/grafana#77411]
### What happened?

**Steps to reproduce:**
Go to the home page. Resize screen to 320px. Click on the hamburger menu button. See horizontal scrollbar.

**Actual Result:**
Horizontal scrollbar appears at the bottom of the menu. This doesn't actually block any functionality.

![Screenshot 2023-10-30 at 3 56 13 PM](https://github.com/grafana/grafana/assets/27587456/4630e646-8f7b-4c8e-a9bf-23dfa4dfd26a)

### What did you expect to happen?

**Expected Result**
There did not appear to be any text pushing this to the side. Text should respond reasonably so as not to produce a scrollbar, so that users using smaller screens or screen magnifying software, etc. do not accidentally scroll horizontally uncessarily.

### Did this work before?

N/A

### How do we reproduce it?

1. Navigate to play.grafana.org in Chrome
2. Use dev tools to reduce the screen size
3. Click the hamburger menu, view the scrollbar

### Environment (with versions)?

Grafana: 10.2
OS: Mac
Browser: Chrome

### Grafana platform?

None

**Comment by eledobleefe** [comment]
Hi,
I checked, and with the latest changes to the menu, this issue seems to be fixed.

<img src="https://github.com/user-attachments/assets/db8c3934-bfa6-4a2b-84bc-58e6a61cc1a1" width="320px"/>

Closing this issue as done. Re-open if needed.
