### ISSUE TITLE
Task: Move the time picker down to the canvas

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#77431]
This is part of the way of toolbar improvements.

The behavior for this should be using a `position:sticky`

<img width="1440" alt="DashboardsTopBar" src="https://github.com/grafana/grafana/assets/51436795/b7577051-187c-4b68-b45d-bfd806f39b9e">

[Figma](https://www.figma.com/file/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?type=design&node-id=52-2229&mode=design)

**Comment by evictorero** [comment]
@natydej can we close this issue? This is the default design of Scenes, right? We won't change it old dashboards.

**Comment by natydej** [comment]
Yes @evictorero 
Closing it since the migration from Dashboards to scenes has already implemented this behavior.
