### ISSUE TITLE
[Bug] PhantomJS binary on win64 platform has incorrect extension

### ISSUE THREAD

**Issue by woutersmit** [grafana/grafana#7744]
- What Grafana version are you using?
4.0.1
- What OS are you running grafana on?
Win64
- What did you do?
Send alert via email notification
- What was the expected result?
Email with graph included
- What happened instead?
Error in logging about phantomjs and NO graph included in email

Quick fix for me was, rename vendor/phantomjs/phantomjs to vendor/phantomjs/phantomjs.exe

**Comment by torkelo** [comment]
this is fixed in 4.2-beta1
