### ISSUE TITLE
[Bug] LDAP group membership check uses wrong attribute in check

### ISSUE THREAD

**Issue by jblaine** [grafana/grafana#7746]
Grafana 4.1.1-1484211277

I don't believe this is a "question" vs. bug. My apologies if others think otherwise. All effort to get LDAP group membership working is failing. The membership check is checking for the value of username instead of the distinguishedName. I have tried both "generic" and also "AD with nested groups" methods as you can see below.

Our user objects **have** `memberOf` on them, and each `memberOf` points to a DN of a group.

## Configuration 1:
1. search_filter is set to `"(&(objectCategory=Person)(sAMAccountName=%s))"`
2. Commented out: group_search_filter
3. Commented out: group_search_filter_user_attribute
4. Web UI Username: m2000

In the log for this configuration below you can see the user is found, but according to what is logged, it is checking to see if `m2000` is a member of the group in question but it "should be" checking to see if the full DN for `m2000` is a member of the group.

Result:
```
t=2017-03-06T13:43:01-0500 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc4206a8460)({\n DN: (string) (len=81) \"CN=Charles Blaine (M2000),OU=Services,DC=OUR,DC=ORG\",\n FirstName: (string) (len=7) \"Charles\",\n LastName: (string) (len=6) \"Blaine\",\n Username: (string) (len=6) \"m2000\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=1 cap=1) {\n  (string) (len=77) \"CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG\"\n }\n})\n"
t=2017-03-06T13:43:01-0500 lvl=info msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=m2000 groups="[CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG]"
t=2017-03-06T13:43:01-0500 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
```

## Configuration 2:
I then tried using the "AD with nested groups" example from ldap.toml

1. group_search_filter set to `"(member:1.2.840.113556.1.4.1941:=%s)"`
2. group_search_filter_user_attribute set to `"distinguishedName"`
3. `[servers.attributes]` : member_of set to `"distinguishedName"`
4. Web UI Username: m2000

In the log for this configuration below you can see in the 2nd log line that the user is found and the group it is a member of is noted as well!, but according to what is logged, it is checking to see if "m2000" is a member of the group in question but it "should be" checking to see if the full DN for "m2000" is a member of the group.

```
t=2017-03-06T13:35:14-0500 lvl=info msg="Searching for user's groups" logger=ldap filter="(member:1.2.840.113556.1.4.1941:=CN=Charles Blaine \\28M2000\\29,OU=Services,DC=OUR,DC=ORG)"
t=2017-03-06T13:35:32-0500 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc42066a9a0)({\n DN: (string) (len=81) \"CN=Charles Blaine (M2000),OU=Services,DC=OUR,DC=ORG\",\n FirstName: (string) (len=7) \"Charles\",\n LastName: (string) (len=6) \"Blaine\",\n Username: (string) (len=6) \"m2000\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=1 cap=1) {\n  (string) (len=77) \"CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG\"\n }\n})\n"
t=2017-03-06T13:35:32-0500 lvl=info msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=m2000 groups="[CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG]"
```

**Comment by torkelo** [comment]
what is your group mapping config? 

>"Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=m2000 groups="[CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG]"

This does just mean that there was no role mapping defined for this group, `CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG`

If you add this group to group mapping the configuration 1 example should work. 

```
[[servers.group_mappings]]
group_dn = "CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG"
org_role = "Editor"
```

**Comment by jblaine** [comment]
The group `CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG` is already in a group mapping, and was for all attempts so far.
```
[[servers.group_mappings]]
group_dn = "CN=R701,OU=Groups,OU=IDM_MANAGED,OU=Services,DC=OUR,DC=ORG"
org_role = "Admin"
```

**Comment by torkelo** [comment]
strange, should work

**Comment by plrunner** [comment]
Why did this issue get closed? I confirm exactly what reported by @jblaine.

**Comment by jblaine** [comment]
@plrunner It's comforting to know someone else is hitting this!

**Comment by plrunner** [comment]
@jblaine try with `allow_sign_up = true` in the `[auth.ldap]` section of the ini file. It worked for me at the end.
