### ISSUE TITLE
[Bug] Grafana is not alerting on negative values

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#7747]
- What Grafana version are you using?
4.1.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS 6.6

- What did you do?
Set alert on positive and negative values. Positive values create alerts. **Negative do not.** 

![capture](https://cloud.githubusercontent.com/assets/5177657/23634766/a3026dde-0291-11e7-9b29-4db5ff4b0631.PNG)

My alert:

![capture2](https://cloud.githubusercontent.com/assets/5177657/23634804/d454dc6e-0291-11e7-9ca4-0f5021711ed3.PNG)

**Comment by torkelo** [comment]
what is the time range for your alert and how frequently is it run?

**Comment by torkelo** [comment]
So there is no problem with negative values. I think the problem your facing is the query time range and that there is large sections without data. 

![image](https://cloud.githubusercontent.com/assets/10999/23645701/b7e90218-030d-11e7-9e1c-4e5a019d1d60.png)
