### ISSUE TITLE
[Bug] IE11 fails to show chart data after a few minutes (reopen request for #6936)

### ISSUE THREAD

**Issue by HeikoOnnebrink** [grafana/grafana#7748]
Version: Grafana 4.1.2
Datasource: Influxdb 0.13
OS: Docker Container build from ubuntu:14.04
What was I doing? Just watching a chart over time (every 30s refresh)
What should happen? Data continues to appear
What happened instead? Data disappears

Just ran into issue as described in bug #6936 for clients using iExplorer 11 when using Grafana 3.1.
Edge and Firefox all work fine, just in iE11 data does not get rendered into the graphs during page refreshes while initial page load displays all graph data.

As mentioned in bug #6936 that issue is related to client side data caching and should be fixed in 4.0.1
I build new docker container based on Grafana 4.1.2 (as I assume that fix introduced in 4.0.1 made its way into 4.1.2). But still same problem

The workaround for iE11 to change cache settings from "Automatic" to "Every time I visit the page" fixes the problem, but no need to discuss that this is no real/permanent solution.

Funny to mention that I never could reproduce the problem with Edge browser while it was reported that problem also should occur there.

**Comment by louloizides** [comment]
I had the same issue and the workaround helped. Thanks!

**Comment by torkelo** [comment]
IE11 is not supported
