### ISSUE TITLE
Variables: data source not found

### ISSUE THREAD

**Issue by arvonh** [grafana/grafana#77494]
### What happened?

when I query a variables using aliyun-log-service-datasource datasource, it always responses 404 with msg:data source not found

### What did you expect to happen?

The variables query return an expected response

### Did this work before?

yes, it works at v9.2.x

### How do we reproduce it?

1. Create a Variables
2. Select one of "aliyun-log-service-datasource" datasoure
3. perform query, then it  responses 404 with msg:data source not found all the time

### Is the bug inside a dashboard panel?

it works normally inside  a dashboard panel.

### Environment (with versions)?

Grafana: v10.0.9
OS: macos, linux
Browser: chrome

### Grafana platform?

None

### Datasource(s)?

aliyun-log-service-datasource

**Comment by tonypowa** [comment]
hi @arvonh 

it seems like you are using a community-developed plugin or data source (i.e. it does not have support from Grafana).
please post your question in https://community.grafana.com/ instead, where there might be other users that can do help you troubleshoot the issue
thank you for your understanding
