### ISSUE TITLE
[bug] api  '/api/dashboards/db'  add  dashboard , panel.thresholds always equal []

### ISSUE THREAD

**Issue by janceChun** [grafana/grafana#7749]
**information:**
- grafana:4.1.2
- influxdb:1.1.1

**describe:**

add  dashboard  through api  '/api/dashboards/db'，
i try to  set panel.thresholds:[
      {
        "value": 20,
        "colorMode": "critical",
        "op": "gt",
        "fill": true,
        "line": true
      }
    ]
but   it  return panel.thresholds:[] always

**Comment by torkelo** [comment]
can you show the json your trying to save? I mean the same api is used by the UI so unable to replicate it. 

Here is a panel json with a threshold that saves/loads ok:

```
{
  "aliasColors": {},
  "bars": false,
  "datasource": null,
  "fill": 1,
  "id": 1,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 12,
  "stack": false,
  "steppedLine": false,
  "targets": [],
  "thresholds": [
    {
      "colorMode": "critical",
      "fill": true,
      "line": true,
      "op": "gt",
      "value": 0
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}
```

**Comment by janceChun** [comment]
{
  "aliasColors": {
    "Pages_persec": "rgb(254, 57, 18)",
    "pages/sec": "rgb(254, 57, 18)"
  },
  "bars": false,
  "datasource": "telegraf",
  "fill": 10,
  "grid": {},
  "id": 15,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "sideWidth": 250,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 0,
  "nimei": "fuck",
  "nullPointMode": "null as zero",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "span": 12,
  "stack": true,
  "targets": [
    {
      "alias": "$col",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "auto"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "measurement": "win_mem",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Pages_persec"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              "pages/sec"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/^$host$/"
        }
      ]
    }
  ],
  "thresholds": [
    {
      "value": 20,
      "colorMode": "critical",
      "op": "gt",
      "fill": true,
      "line": true
    }
  ],
  "title": "Memory  Pages/sec",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "show": true,
    "mode": "time",
    "name": null,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": 0,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": false
    }
  ],
  "steppedLine": false,
  "timeFrom": null,
  "timeShift": null,
  "seriesOverrides": []
}

**Comment by janceChun** [comment]
{
  "aliasColors": {
    "Pages_persec": "rgb(254, 57, 18)",
    "pages/sec": "rgb(254, 57, 18)"
  },
  "bars": false,
  "datasource": "telegraf",
  "fill": 10,
  "grid": {},
  "id": 15,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "sideWidth": 250,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 0,
  "nullPointMode": "null as zero",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "span": 12,
  "stack": true,
  "targets": [
    {
      "alias": "$col",
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "auto"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "measurement": "win_mem",
      "policy": "default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "Pages_persec"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          },
          {
            "params": [
              "pages/sec"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/^$host$/"
        }
      ]
    }
  ],
  "thresholds": [
    {
      "value": 20,
      "colorMode": "critical",
      "op": "gt",
      "fill": true,
      "line": true
    }
  ],
  "title": "Memory  Pages/sec",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "show": true,
    "mode": "time",
    "name": null,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": 0,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": false
    }
  ],
  "steppedLine": false,
  "timeFrom": null,
  "timeShift": null,
  "seriesOverrides": []
}

**Comment by janceChun** [comment]
@torkelo

**Comment by janceChun** [comment]
@torkelo 
![image](https://cloud.githubusercontent.com/assets/4457572/23651032/24454268-035f-11e7-998c-6fb7c9e02cb4.png)
the json is  export from this  panel.

it is work fine when  i  add thresholds from ui

**Comment by torkelo** [comment]
When I use the panel json you pasted it seems to work. 

```
{
"aliasColors": {
"Pages_persec": "rgb(254, 57, 18)",
"pages/sec": "rgb(254, 57, 18)"
},
"bars": false,
"datasource": "telegraf",
"fill": 10,
"grid": {},
"id": 15,
"legend": {
"alignAsTable": true,
"avg": false,
"current": false,
"max": true,
"min": true,
"rightSide": true,
"show": true,
"sideWidth": 250,
"total": false,
"values": true
},
"lines": true,
"linewidth": 0,
"nullPointMode": "null as zero",
"percentage": false,
"pointradius": 5,
"points": false,
"renderer": "flot",
"span": 12,
"stack": true,
"targets": [
{
"alias": "$col",
"dsType": "influxdb",
"groupBy": [
{
"params": [
"auto"
],
"type": "time"
},
{
"params": [
"none"
],
"type": "fill"
}
],
"measurement": "win_mem",
"policy": "default",
"refId": "A",
"resultFormat": "time_series",
"select": [
[
{
"params": [
"Pages_persec"
],
"type": "field"
},
{
"params": [],
"type": "mean"
},
{
"params": [
"pages/sec"
],
"type": "alias"
}
]
],
"tags": [
{
"key": "host",
"operator": "=~",
"value": "/^$host$/"
}
]
}
],
"thresholds": [
{
"value": 20,
"colorMode": "critical",
"op": "gt",
"fill": true,
"line": true
}
],
"title": "Memory Pages/sec",
"tooltip": {
"msResolution": false,
"shared": true,
"sort": 0,
"value_type": "individual"
},
"type": "graph",
"xaxis": {
"show": true,
"mode": "time",
"name": null,
"values": []
},
"yaxes": [
{
"format": "short",
"label": null,
"logBase": 1,
"max": null,
"min": 0,
"show": true
},
{
"format": "short",
"label": null,
"logBase": 1,
"max": null,
"min": null,
"show": false
}
],
"steppedLine": false,
"timeFrom": null,
"timeShift": null,
"seriesOverrides": []
}
```

**Comment by torkelo** [comment]
![screen shot 2017-03-07 at 13 29 42](https://cloud.githubusercontent.com/assets/10999/23656502/47e3327c-033a-11e7-8995-6d058bf71162.png)

**Comment by janceChun** [comment]
@torkelo  
I used  the second json that you gave me，but it  still  not  working(but the first json that you gave  works ),  maybe because I used the docker image  grafana/grafana:4.1.2?    
Or the version of grafana is different?(macos 10.12.2)
Although  I  tried the docker image  grafana/grafana:4.0.2, it  dosen't work,neither.

**Comment by torkelo** [comment]
in what way does it not work? When you open the dashboad & panel and go into display tab / thresholds, what do you see?

**Comment by janceChun** [comment]
in api way，'/api/dashboards/db'

**Comment by torkelo** [comment]
what?

**Comment by janceChun** [comment]
![image](https://cloud.githubusercontent.com/assets/4457572/23687181/49d49432-03e8-11e7-9656-e9f4bf6217d3.png)
I copy  the second json that you gave me , send the json to api '/api/dashboards/db', and then open the dashboad & panel and go into display tab / thresholds  .

**Comment by janceChun** [comment]
😊   i  know how to  dealwith this  problem,    just delete json  attribute grid  is ok . @torkelo
