### ISSUE TITLE
[Bug] Displaying Prometheus annotations is incredibly slow

### ISSUE THREAD

**Issue by bechtoldt** [grafana/grafana#7750]
- What Grafana version are you using?

v4.1.2

- What datasource are you using?

Prometheus v1.1.3

- What OS are you running grafana on?

Linux

- What did you do?

1. Configured annotations (see screenshot)
2. Enabled annotations while having a dashboard open

- What was the expected result?

* Show annotations

- What happened instead?

* Browser site/tab (Chrome 56) hangs, becomes unresponsive, dies.

**IMPORTANT** 

There *aren't a lot* alerts (~ 20-30) that should have been displayed for a timeframe, e.g. 7days. It's a dashboard with more than 15 Panels (histograms).

**Comment by mtanda** [comment]
The Prometheus query for long time range (e.g. 7days) could be slow query.
Please try to execute same annotation query (and same time range) in Prometheus expression browser.

And drawing too many annotation line might cause unresponsive.
I tried to fix it, but not approved.
https://github.com/grafana/grafana/pull/6168

**Comment by torkelo** [comment]
seems like step is hardcoded to 60s, should this not be changed depending on time range like normal metric queries?

**Comment by mtanda** [comment]
@torkelo I reopen past PR to fix step issue.
https://github.com/grafana/grafana/pull/7765

**Comment by mtanda** [comment]
Ah, I may misunderstand.
You means the step should be automatically adjusted by time range?

**Comment by abadyan-vonage** [comment]
This issue is also happenning in influxdb. When I use a large enoguh timeframe (30d) annotations query is very very slow (just running it in influxdb returns almost immediately). Also annotations become unreadable.
I think maybe their resolution can be changed like regular metrics do so that they are aggregated.
Maybe something like a meta-annotation that says it is hiding 5 other annotations and only when you zoom in you actually see them.
@torkelo

**Comment by abadyan-vonage** [comment]
The way I get around this right now is use a hard limit in the query itself so only 20 results return, this makes the result manageable.

**Comment by torkelo** [comment]
With influxdb you can add a limit keyword to limit the events returned. 

@mtanda yes, some reasonably auto steps, divide the time range in 100 steps for example so you can never get more than 100 events back. but a step parameter might be good as well

**Comment by abadyan-vonage** [comment]
@torkelo yes, that's exactly what I wrote that I did but it would be nice if instead there would be some aggregation into meta-annotations like I explained. What do you think?

**Comment by mtanda** [comment]
About meta-annotation, I like this idea.
https://github.com/grafana/grafana/issues/3031#issuecomment-275146476

**Comment by mtanda** [comment]
@torkelo I add step parameter in https://github.com/grafana/grafana/issues/7768 .
With interval type templating variable, we can limit the total events.

**Comment by torkelo** [comment]
Meta annotation?

**Comment by abadyan-vonage** [comment]
An annotation that represents a group of annotations in order to reduce the density of annotations on the graph.
