### ISSUE TITLE
Please can any one help me for setting up data source as SimpleJson by using Rest API 

### ISSUE THREAD

**Issue by RaghuKumarBA** [grafana/grafana#7752]
As I am using the Grafana 4.1.1 and trying to set up SimpleJson Data source on my Local Machine.
Also as in my Data Source i have created REST API for populating the Data. After adding the Rest API Url, In log it's getting updated as 404 Error.
Can any please Help me in this issue . as I am new to Grafana .

**Comment by torkelo** [comment]
please use mailing list for questions. 

And provide every relevant info you can think of. The options you specified, your network setup.

**Comment by RaghuKumarBA** [comment]
Hi Torkelo,

Please find the snapshot of the issue wat i am facing

![grafana](https://cloud.githubusercontent.com/assets/26250084/23693626/5d08ab2a-03fb-11e7-8655-c727fb8f8d28.png)


Please help me to resolve this issue

**Comment by torkelo** [comment]
if you specify that url in your browser does it work? are running the simplejson data source on your local machine?

**Comment by RaghuKumarBA** [comment]
Hi 
It's working in the browser 
![grafana1](https://cloud.githubusercontent.com/assets/26250084/23695398/003b762a-0405-11e7-8490-4b8db4fab3c3.png)

**Comment by RaghuKumarBA** [comment]
Ya i am using simpleJson data source ..

**Comment by daniellee** [comment]
Looks like it might be a CORS problem. Trying changing the Access mode from direct to proxy.

If that does not work then, open Chrome dev tools and see if there are any errors in the console. You can also look at the response to see what the error is:

![chromedevtoolsresponse](https://cloud.githubusercontent.com/assets/434655/23703207/17d8ba8c-03ff-11e7-99fc-66395bc26c48.png)
