### ISSUE TITLE
Canvas: Rectangle Element rounded corner option

### ISSUE THREAD

**Issue by xkilian** [grafana/grafana#77526]
**Why is this needed**:

Better display of rectangle elements

**What would you like to be added**:

Configuration of the _rounded_ parameter for rectangle elements in the Element configuration section.
Permit a number slider for the amount of rounding 0 to X.

**Who is this feature for?**

When creating status panels rounded rectangles and such are much easier to look at for hours on end.

**Comment by lukasztyrala** [comment]
The rounded corner option should be available for all elements and arrows/connectors.

Initially, all corners (connectors/lines) or edges (elements) should be uniformly charged for the given path or element, for example, by adding a radius option in the panel edit.

<img width="1692" alt="radius" src="https://github.com/grafana/grafana/assets/141744/ff448672-c2e4-4d62-adb0-7a35628cad20">

**Comment by drew08t** [comment]
> The rounded corner option should be available for all elements and arrows/connectors.
> 
> Initially, all corners (connectors/lines) or edges (elements) should be uniformly charged for the given path or element, for example, by adding a radius option in the panel edit.
> 
> <img alt="radius" width="1692" src="https://private-user-images.githubusercontent.com/141744/313705007-ff448672-c2e4-4d62-adb0-7a35628cad20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODAzMDIsIm5iZiI6MTcxMDc4MDAwMiwicGF0aCI6Ii8xNDE3NDQvMzEzNzA1MDA3LWZmNDQ4NjcyLWMyZTQtNGQ2Mi1hZGIwLTdhMzU2MjhjYWQyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNjQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTQwMjE5MzIzNmNmNzA4MGVjOWEzMGRmNThiZjE3ZDA3YTdjYzNhMDkzNmQ2NDk5NWRmMGM2NTFjNjhkMDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nsXAGLm4NyyRkoZc3efPRnjy4ttlShbbWFLzkdN0PeY">

A comprehensive list of element types we aim to support with this option:

1. Connections
2. Text
3. Rectangle
4. Button (maybe)
5. Triangle (new element)
6. Parallelogram (new element)

**Comment by lukasztyrala** [comment]
Button element should be bound with the grafana/ui, so I'd leave the button out of the equation for rounded edges/corners.

**Comment by drew08t** [comment]
> Button element should be bound with the grafana/ui, so I'd leave the button out of the equation for rounded edges/corners.

Agree!
