### ISSUE TITLE
System Resources: High CPU/Memory usage after 10.2.0 upgrade

### ISSUE THREAD

**Issue by a26nine** [grafana/grafana#77544]
### What happened?

I upgraded my cluster from `10.1.5` to `10.2.0` a few hours ago. Right after the upgrade, the CPU and Memory usage spiked and have been the same ever since.

![Snap-20231102-110632@2x](https://github.com/grafana/grafana/assets/103454930/250145f0-8be4-4a1f-9b99-a84a8583de6a)

### What did you expect to happen?

I expected it to remain stable as earlier.

### Did this work before?

Yes, earlier, it was working fine.

### How do we reproduce it?

1. Note CPU and Memory usage on `10.1.5`.
2. Upgrade to `10.2.0`.
3. Check CPU and Memory usage again.

### Environment (with versions)?

Grafana: 10.2.0
OS: MacOS
Browser: Chrome/Chromium

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
hi @a26nine 

could you please copy and paste all relevant data using the panel --> more --> get help workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:
https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/
![alt text](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by a26nine** [comment]
@tonypowa, I think we can close this for now.
