### ISSUE TITLE
Logs panel: Specify field selection (eye button)

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77552]
### Discussed in https://github.com/grafana/grafana/discussions/38290

<div type='discussions-op-text'>

<sup>Originally posted by **mieliespoor** June  1, 2021</sup>
**What would you like to be added**:
On the logs panel it should be possible to select which fields from the log item is being shown. Sometimes, the full log message is not needed as it doesn't make sense to show all that information on a dashboard.

**Why is this needed**:
We have a query showing Cloudwatch Log data and a query similar to:

```
fields @timestamp, Level, Properties.CorrelationId, MessageTemplate
| sort @timestamp desc
| limit 20
```

When running the same query in Grafana, it will only show the data from the Level field and nothing else. The expectation is that we see the data for all the fields listed in the query.</div>

**Comment by CumpsD** [comment]
Has there been any progress on this? I would love to select what is shown as the log line based on a field

**Comment by CumpsD** [comment]
Turns out with Cloudwatch you can do it like this:
```
fields @message
| sort @timestamp desc
| parse @message "* ip-* *[*]: * * *" as time, node, job, thread, date, hour, msg
| filter ispresent(msg)
| display @timestamp, msg, node, job, time
| limit 50
```
The first and second field in display is used for timestamp and the log line, everything else gets added as fields

**Comment by rolfwessels** [comment]
Hmm, I have a terrible workaround for this.

What I would like to do is run this 
```
fields @message
| sort @timestamp desc
| parse @message "*,*,*,*,*,*,*,*" as ip, useragent, datetime, method,url,protocal,status,rest
| display @timestamp, ip , method, url, status
| limit 100
```
This should then display the columns as expected unfortunately it only displays the timestamp. :-( 

My workaround is to put all the data into `@message`.

```
fields @message
| sort @timestamp desc
| parse @message "*,*,*,*,*,*,*,*" as ip, useragent, datetime, method,url,protocal,status,rest
| fields concat(ip, " ",method, " ", url, " ", status) as @message
| display @timestamp, @message
| limit 100
```

It's ugly but at least it works. 🤞 some updates in the future will resolve this

**Comment by vtrmdz** [comment]
A possible solution ( has worked for me with Influxdb  ):
- Apply the 'Organize fields by name' transformation
- Drag the desired field to the 2nd position, below your time field ( _time )

_Ive found the above to keep the fields in the desired order most of the time. On occasion, the transformation does not apply? thus you'll randomly have the log fields render at a random order._

**Comment by Eleskovic** [comment]
How about if i want to change the displayed field on the log line and want to colorize it at the same time? I want to select: timestamp, level and msg at the same time but I can only show either:
* timestamp + level
* timestamp + log msg
* type + level
* type + log msg
So in each case, I am missing either my timestamp to show dates or level to colorize or msg to understand whats going on.
