### ISSUE TITLE
[BUG] Hive is not showing any metrics in any "Hive" dashboards

### ISSUE THREAD

**Issue by pd47** [grafana/grafana#7755]
[BUG] Hive is not showing any metrics in any "Hive" dashboards

Ambari version:  2.4.1.0
HDP Stack: 2.4.3.0
Grafana version: 2.4.1.0-22
Datasource: Ambari Metrics
OS: RedHat Linux 6.7 (2.6.32-573.el6.x86_64)

After I installed Grafana, Hive metrics is not showing on any of the Hive dashboards. It's displaying "No datapoints".
All other dashboards are showing metrics data.

I do not see any metrics error either in hivemetastore or hiveserver2 logs

**Comment by torkelo** [comment]
please ask questions in mailing list.

**Comment by torkelo** [comment]
your metric query is not returning any data, so you will have to trouble shoot Ambari Metrics.
