### ISSUE TITLE
Loki: Use custom level field name for log volume

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77557]
### Discussed in https://github.com/grafana/grafana/discussions/43274

<div type='discussions-op-text'>

<sup>Originally posted by **sherifkayad** December 14, 2021</sup>

**What happened**:
The Volume Histogram can't interpret the levels of the logs and classified logs as `unknown` when the label `level` isn't used but another label e.g. `severity` is used.

The logs panel shows the **correct** coloring though.

**What you expected to happen**:
Both the Volume section and the Logs panel show the right coloring (e.g. Green for Info, Red for Error, .. etc.) .. Maybe Grafana needs to enable a list of fields that the user can define via the data source config for the severity / log level?!

**How to reproduce it (as minimally and precisely as possible)**:
- Use a different field for log level e.g. `severity` and send these logs to Loki
- Query the logs making sure you have the `fullRangeLogsVolume` supported

**Anything else we need to know?**:
Just attaching some screenshots ..
![image](https://user-images.githubusercontent.com/8362784/146007163-a230d021-b084-4203-aea4-4dadca557d3a.png)

![image](https://user-images.githubusercontent.com/8362784/146020617-c57a0cd5-a0a4-47c2-867f-9b05875c3e19.png)

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Loki v2.4.1
- OS Grafana is installed on: Kubernetes using the official Helm Chart
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
</div>

**Comment by matyax** [comment]
Reopening, as there seems to be [interest](https://github.com/grafana/grafana/discussions/61167) in adding support for this.

**Comment by matyax** [comment]
Wrong issue.
