### ISSUE TITLE
Feature request Cloudwatch GroupBy

### ISSUE THREAD

**Issue by Isaacpm** [grafana/grafana#7756]
Hi,

It would be really useful if we had a similar groupby option in Cloudwatch as there is in Elasticsearch.
If CloudWatch permits it.
- What Grafana version are you using?
4.1.2
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Create a panel in a dashboard, selected a dimension
- What was the expected result?
Group By button, like the available for Elasticsearch
- What happened instead?
There is no group by

Thanks,
Isaac

**Comment by torkelo** [comment]
Don't think Cloudwatch api has this
