### ISSUE TITLE
Trend: Shared tooltip and zoom

### ISSUE THREAD

**Issue by selvavm** [grafana/grafana#77564]
**Why is this needed**:

Trend chart is for x!=time. However, I have timeseries which is a simulation data and starts from 0 with steps of dt. It would be nice if I can have shared tooltip and zoom (same x), then I can enjoy all functionalities as timeseries chart. 

Also, one more reason why I can’t use timeseries chart is it sends a new query whenever a zoom happens which is slow in our case (XY chart zooming is really fast). 

**What would you like to be added**:

Please add shared tooltip and shared zooming in trend chart. Also while zooming it should not query for new data but zoom the current data similar to XY chart. 

**Who is this feature for?**

End users of trend chart

Note: I can support on developing this but I need to know if you are interested and also some pointers on what script should be looked upon.

**Comment by leeoniya** [comment]
hi, i dont understand what you're asking here.

cursor sharing is based on the x scale, not on the x cursor pixel position. since trend chart does not have a time scale on x, it cannot have shared cursor with other charts that have time x.

as you said, zooming in Trend does not requery (because you dont have a time scale), but TimeSeries has a time scale and does requery.

how are you proposing to sync these? or are you asking to synchronize only between multiple Trend trend panels?

**Comment by selvavm** [comment]
Thanks for response. 

Say I have two tables. 
Table 1 is the first panel (I.e) t is in x-axis and sen1 in y-axis of trend chart
```
t    sen1
- - - - - -
0.0 1.0
0.4 2.0
0.8 3.0
1.2 4.0
1.4 5.0
……
10  40.0

```

Table 2 is the second panel (I.e) t is in x-axis and sen2 in y-axis of trend chart

```
t    sen2
- - - - - -
0.0 1.1
0.4 2.1
0.8 3.1
1.2 4.1
1.4 5.1
……
10  40.1

```

Now if I hover on first panel at t=0.4, I would like to see in the tooltip below 

```
t = 0.4
sen1 = 2.0
sen2 = 2.1
```

Then if I zoom, I am able to zoom similar to XY chart without rerunning query

Note - I could use timeseries chart if it does not re-query while zooming and I can visualise time starting from 0 (I tried manipulating time format but it is universal and our Grafana is used by many users)

**Comment by leeoniya** [comment]
> I would like to see in the tooltip below

this doesnt currently exist even in the timeseries panels. shared tooltip simply means to display the tooltip while synchronizing the cursor. it does not show you values from other panels in the same tooltip. all panels are independent of each other.

what you can do is set tooltip mode to All, then query all the data in one trend panel, then use the Dashboard datasource for the other trend panels to share those query results and configure "Hide from: Viz".

![image](https://github.com/grafana/grafana/assets/43234/8a211763-cfa0-4dc2-9fc1-741922449332)

![image](https://github.com/grafana/grafana/assets/43234/e706c3ef-5035-4e94-91e7-c8b2d6a9301b)

**Comment by leeoniya** [comment]
> and configure "Hide from: Viz".

i guess this won't work due to https://github.com/grafana/grafana/issues/63691 :cry: 

you can set the color to transparent:

![image](https://github.com/grafana/grafana/assets/43234/1ddcbe40-0bec-4928-b9a0-6fce1bf1ea94)

**Comment by selvavm** [comment]
Hi thanks. Sorry, I might have concluded how tooltip looks based on my experience before checking. I am okay if the tooltip is shown in each panel separately. So, if I hover at 0.4s in one panel, I get a tooltip in this panel and also in other panel.

**Comment by selvavm** [comment]
Also, can you support how can I have shared zoom. So if I load the dashboard from 0 to 10 and if a user zooms from 3 to 7 in one panel, I expect all the panels to zoom.

**Comment by leeoniya** [comment]
we'll have to think about how only trend<->trend can work, since we don't currently have panel-specific isolation and pretty much all of it is based on time, including zoom, which is simply re-querying. it's not super simple, unfortunately.

**Comment by selvavm** [comment]
Ah Thanks. 😔. If you know there is a feature request to stop querying while zooming in timeseries panel, you can tag this as duplicate. Again thanks for speedy response.

**Comment by leeoniya** [comment]
> If you know there is a feature request to stop querying while zooming in timeseries panel

no, but we already do this for vertical zooming via shift+drag. i dont think it would be difficult to do the same for x zoom. whether this will work with sync is a different question :sweat_smile:

**Comment by selvavm** [comment]
Thanks @leeoniya. Any suggestion on how to modify code to enable shared zooming in trend or xy chart?

**Comment by selvavm** [comment]
@leeoniya, do you think below will work,

1. Add a panel with time overrride and load full dataset 
2. Hide this panel
3. Add a new panel with dashboard as datasource
4. Make this panel with repeating option, so I get Sen1 and sen2 as separate panels 
5. 

Now, if I zoom in this panel, it will query the dashboard panel, hence, avoiding performance bottleneck. Do you think it will work?

if yes, I have no idea how to hide a panel (step 2]

**Comment by nmarrs** [comment]
Hi @selvavm - thank you for submitting this issue. We discussed this internally as a team and at this point we have decided to not move forward with implementing this functionality at this time.

**Comment by leeoniya** [comment]
@selvavm

the sync functionality is going to be too tricky to get working well without a big project and design to cursor modify our sync options. however, i've broken out the Trend client-only zooming request into https://github.com/grafana/grafana/issues/82012.
