### ISSUE TITLE
Feature request -- Cloudwatch dimensions to allow EC2 Name 

### ISSUE THREAD

**Issue by Isaacpm** [grafana/grafana#7757]
Hi,

It would be very useful if we could select the EC2 Instance name as dimension.
Having the instance-id is not very useful if you are rebuilding images often, nor it's easy to use as they are random strings.

- What Grafana version are you using?
4.1.2
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Created a panel in a dashboard, selected AWS/EC2 namespace. Clicked on dimensions.
- What was the expected result?
I would like the name of the instance to be available
- What happened instead?
Name is not available, only autoscalinggroupname, imageid, instanceid and instancetype are available.

Thanks,
Isaac

**Comment by fredm1** [comment]
+1 We deploy and delete our test, stage and dev stacks frequently also and this feature would be nice to have.

**Comment by paco3346** [comment]
@fredm1 and @Isaacpm My PR #8307 will allow you to select / view EC2 tags.

**Comment by tsupertramp** [comment]
Started working on this. Allow to Use Tags.Key (e.g. Tags.Name) to filter Instances through Tags. - I love pacos PR but from user experience it is very confusing to use like a "sub select template variable" and this does not allow to show a static graph just by selecting the name - You always have to use template vars. Will try my best.

**Comment by tsupertramp** [comment]
Stopping my work on this. Do not find any way to put it in nicely. Idea was to use a regex on the input of dimensions and if it is e.g. "Tags.Name", the frontend first uses a get request to get the instance ids to then query the metrics - Maybe something like that. But this just feels very hacked into it. Maybe somebody wants to help or use this to start on an own version. Greetings, Thomas

```
+         query.dimensions = _.map(target.dimensions, function(value, key) {
+           if (/^Tag./.test(key)) {
+             value = value.replace('Tag.', '');
+
+             var filters = [{
+               Name: "tag:Name",
+               Values: [value]
+             }];
+
+             return self.performEC2DescribeInstances(query.region, filters, null).then(function(result) {
+               var instanceIds = [];
+
+               _.map(result.Reservations, function(reservation) {
+                 _.map(reservation.Instances, function(instance) {
+                   instanceIds.push(instance.InstanceId);
+                 });
+               });
+
+               console.log(instanceIds);
+
+               return [{
+                 Name: "InstanceId",
+                 Value: instanceIds}];
+             });
+           } else {
+             return self.convertDimensionFormat(target.dimensions, options.scopedVars);
+           }
+         });```

**Comment by sunker** [comment]
This is not supported by the cloudwatch GetMetricData api, so I don't think this should be implemented on our end. Closing the issue.

**Comment by tbarkai** [comment]
Hi all, here's a relatively simple patch which I'm using in my deployment:
https://github.com/grafana/grafana/compare/master...tbarkai:ec2names

If the time series contains an instance ID (e.g. i-12345678) - it replaces the time series name with the instance Name tag.
