### ISSUE TITLE
Dashboard: Page crashing when saving a new dashboard

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#77593]
The page is crashing when trying to create a new dashboard, in latest `main`.

https://github.com/grafana/grafana/assets/88068998/2c696db5-2523-4535-9125-f5b7522527a8

**Comment by timlevett** [comment]
Interesting, this seems to only happen if you try to save within the panel edit screen. If you "apply" then "save", it works fine. Just noting the workaround, we should still fix this :D
