### ISSUE TITLE
MySQL's deprecation warning

### ISSUE THREAD

**Issue by gbast0s** [grafana/grafana#77598]
### What happened?

I have upgraded my Grafana from 10.1.5 to 10.2.0, and I’m using embedded panels on my website, but now I’m getting a warning every time a panel it’s loaded, and since I’m new to Grafana, I’m not figuring out what’s the problem.

I'm using MySQL code option

![image](https://github.com/grafana/grafana/assets/82844195/25d0db71-e2d5-4abc-8f21-231d27c9c87e)

### What did you expect to happen?

That the warning did not appear

### Did this work before?

There was no warning

### How do we reproduce it?

1. Connect a database mysql
2. Create a panel and make a query with data
3. Load an iframe panel and the warning shows up

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

MySQL

**Comment by gabor** [comment]
i think this is coming from https://github.com/grafana/grafana/blob/0a5a86f20b014193ee6a663ebfdcbfcb24ed3084/public/app/features/query/state/PanelQueryRunner.ts#L306 , @grafana/dashboards-squad , could you take a look please?

**Comment by torkelo** [comment]
Fixed in https://github.com/grafana/grafana/pull/78339
