### ISSUE TITLE
[Feature request] Scientific notation for singlestats and legend values for charts

### ISSUE THREAD

**Issue by nagimov** [grafana/grafana#7763]
It's not always possible to conveniently display a number in decimal form (unit prefixes sometimes are not convenient, e.g. for vacuum systems the convention is to display `5e-9 torr`, not `5 nano-torr`).
Specification of the decimal format is possible right now, so shouldn't be hard to add the scientific notation (preferably, with a custom exponential threshold, e.g. allow to display `0.05` but replace `0.005` with `5e-3`).

**Example singlestat:**
![2017-03-08 00_58_28-grafana - isac cryoplants](https://cloud.githubusercontent.com/assets/3197765/23696872/604f347c-039a-11e7-848f-448bee6a6f45.png)

**Example chart:**
decimal legend values (as it is now):
![2017-03-08 01_01_55-grafana - isac cryoplants](https://cloud.githubusercontent.com/assets/3197765/23697026/f82cb968-039a-11e7-934b-b25ef366b76a.png)

exponential legend values (what's requested):
![2017-03-08 01_01_38-grafana - isac cryoplants](https://cloud.githubusercontent.com/assets/3197765/23697035/ff321316-039a-11e7-9dd9-88c5a73528e5.png)

**Comment by nagimov** [comment]
Any chances of getting #7781 into 4.3.0? Seems to be a simple patch (4 extra lines)

**Comment by daniellee** [comment]
@nagimov yes, maybe - we haven't forgotten about it. We are focusing on releasing 4.2.0 first (which will probably be tomorrow).
