### ISSUE TITLE
Improve public dashboard acknowledgment on creation

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#77655]
We received feedback about the acknowledgments we are displaying on public dashboard creation.
Since we see some risk in making data public we want to improve the warnings with more information.
More context in this [discussion](https://raintank-corp.slack.com/archives/C036J5B39/p1698266294608469)

We want to change the first one "your entire dashboard will be public" with something more explicit
![image](https://github.com/grafana/grafana/assets/20256983/63f77180-cce5-4db2-97f5-4d2f2c3dd84d)

We don't have the final text yet, I will update this issue accordingly.

Evaluate whether we want to continue saying `currently` when talking about template variables or not.
We removed this kind of wording from docs in this PR.

![image](https://github.com/grafana/grafana/assets/20256983/70eb230a-154b-42b4-80b8-2bd1778b0f4a)

**Comment by AgnesToulet** [comment]
@evictorero Who should we talk to to get the final text?

**Comment by evictorero** [comment]
> @evictorero Who should we talk to to get the final text?

@thanos-karachalios can you help us with this?

**Comment by lucychen-grafana** [comment]
@thanos-karachalios any chance you can help with this

**Comment by lucychen-grafana** [comment]
Since we are making changes to the acknowledgement section as part of the new sharing modal design, should this be discarded or should be worked on if urgent? @evictorero @natydej

**Comment by natydej** [comment]
I think we need to wait to address this until we have the documentation page ready from Isabel, to merge these 3 checkboxes into one. 
Another thing that we can do in the meantime, can be to improve the "Notification banner", which now shows 2 and we can show only one with the CTA to this [doc](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/#limitations) for limitations

**Before:**
<img width="742" alt="Screenshot 2024-01-08 at 18 57 13" src="https://github.com/grafana/grafana/assets/51436795/c7a1a6fb-e523-4387-b9d0-da29af0eb437">


**After:**
<img width="704" alt="alert_base" src="https://github.com/grafana/grafana/assets/51436795/cceb4e77-d99d-4607-9bdc-00e0686af040">

What do you think about the copy? @imatwawana

**Comment by imatwawana** [comment]
I think we should remove the word "currently". This kind of language can make people think a change is coming sooner than it is. Maybe:

> Template variables and frontend data sources aren't supported for public dashboards.

**Comment by lucychen-grafana** [comment]
How about the first checkbox? The original issue is with the first checkbox "Your entire dashboard will be public" not being explicit enough and needs to be updated.

**Comment by evictorero** [comment]
> Since we are making changes to the acknowledgement section as part of the new sharing modal design, should this be discarded or should be worked on if urgent? @evictorero @natydej

We can wait until we have the new design.

**Comment by natydej** [comment]
**Latest update of the redesign notification**

<img width="954" alt="Screenshot 2024-03-11 at 16 47 47" src="https://github.com/grafana/grafana/assets/51436795/0ed1c0d0-ae44-47dc-a39f-7deb26e7e6dc">

**Copy:**
When making your dashboard public, note that the entire content becomes accessible to anyone. Additionally, the publishing feature is presently limited to specific data sources.

**Checkbox:**
I confirm awareness that this entire dashboard will be public *

**Comment by imatwawana** [comment]
Some suggestions for the wording:

**Copy**:
Sharing this dashboard externally makes it entirely accessible to anyone with the link. Currently, this feature is limited to some data sources.

**Checkbox**:
I understand that this entire dashboard will be public.

**Comment by evictorero** [comment]
We are not going to make changes to the current modal since we are working on a Sharing redesign and the goal of this task will be accomplished in the new design.
