### ISSUE TITLE
url show variable to id =WEbXXzRVz not to datasource name

### ISSUE THREAD

**Issue by valdemarpavesi** [grafana/grafana#77665]
### What happened?

url show variable datasource with id ' =WEbXXzRVz' not with name.

### What did you expect to happen?

to show the datasource name on url

### Did this work before?

yes

### How do we reproduce it?

1. deploy Grafana 10.2.0
2. show any dashboard.
3.

### Environment (with versions)?

Grafana: 10.2.0
OS: Linux
Browser: any

### Grafana platform?

Kubernetes

### Datasource(s)?

any

**Comment by tonypowa** [comment]
hi @valdemarpavesi 

it seems that some repro steps are missing
could you please add it?
thank you

**Comment by valdemarpavesi** [comment]
Hello @tonypowa 
Grafana 10.3.1 I do not see this problem anymore.

**Comment by tonypowa** [comment]
@valdemarpavesi 
Thanks for letting us know about it!
Let's close the issue for now
If you, for some reason, couldn't upgrade to the working version, feel free to ask us to reopen
