### ISSUE TITLE
Loki: Support Azure auth for Loki data source

### ISSUE THREAD

**Issue by FTFX** [grafana/grafana#77671]
**Why is this needed**:
As a user, I want to deploy Loki on PaaS such as Azure App Service, and guard it from unauthenticated access with the App Service built-in Azure AD authentication, but this would make Loki inaccessible from Grafana as currently the Loki plugin only supports basic auth and OAuth forwarding.

**What would you like to be added**:
Add Azure auth option in Loki data source, just like what we have in Prometheus data source.
![image](https://github.com/grafana/grafana/assets/12870191/4d8b6781-8a90-44af-bff7-58e6b4ed3d11)

**Who is this feature for?**
Users who want to guard their Loki instances with Azure AD.

**Comment by odbaeu** [comment]
Hello, could someone please have a look at this request? It's quite important for companies who try to work password-less. Thanks!
