### ISSUE TITLE
Users: cannot manage permissions of new (10.2) root folder

### ISSUE THREAD

**Issue by ArthurMelin** [grafana/grafana#77688]
### What happened?

After upgrading to 10.2.0, our users with the role Viewer cannot list dashboards that were in the General folder and were moved to the new root folder introduced in 10.2.
They are missing the permission `folders:read` and I didn't find how to manage permissions for this new root folder.

### What did you expect to happen?

We should be able to manage users/roles permissions on the root folder.

### Did this work before?

The root folder was introduced in 10.2 so the problem appeared then.

### How do we reproduce it?

1. Run Grafana 10.2.0
2. Create a dashboard at the root folder level
3. Attempt to list dashboards as a Viewer role

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.0 OSS
OS: N/A
Browser: Chrome 119

### Grafana platform?

Kubernetes

**Comment by erikoffereins** [comment]
We are experiencing the same problem here. Is the temp fix maybe to create a folder and move the dashboards in it? (haven't tried yet)

**Comment by ArthurMelin** [comment]
> We are experiencing the same problem here. Is the temp fix maybe to create a folder and move the dashboards in it? (haven't tried yet)
> 
> UPDATE: It is 'fixed' by creating a(n empty) folder with view permissions for viewers.

My workaround was to create a temporary folder, move all the dashboards inside it and grant the Viewer role permissions to list.

**Comment by alxndr13** [comment]
+1

This is breaking our workflow of having dashboards provisioned via the filesystem, without having them in folders and assigning permissions to it.

**Comment by pprkut** [comment]
I think https://github.com/grafana/grafana/pull/77983 and https://github.com/grafana/grafana/pull/77988 fixed this for the next release(s)

**Comment by ArthurMelin** [comment]
Yep, the issue was resolved after upgrading to 10.2.1 (and after removing the temporary folder)
