### ISSUE TITLE
Input field (with lucene query) at dashboard

### ISSUE THREAD

**Issue by Kaszal** [grafana/grafana#7769]
Hi,

I would like to create input field (like Query) with lucene query for dashboard user.
e.g. input filed where can I write e.g. {"find": "terms", "field": "field_name"}

**Comment by daniellee** [comment]
I'm not sure I understand the question. Could you explain a bit more?

**Comment by Kaszal** [comment]
I want prepare dashboard for user where I will put panel (e.g. table), but I want give possibility to write own lucene query (like input filed Query below table panel (Metrics -> Query)

**Comment by daniellee** [comment]
I do not know of any way to do this right now but you I think you can get pretty close with Ad-hoc filter variables.

http://docs.grafana.org/guides/whats-new-in-v4/#ad-hoc-filter-variable

You can see it in action here: http://play.grafana.org/dashboard/db/elasticsearch-templated

**Comment by Kaszal** [comment]
@daniellee , thank you very much, this is what I was looking for :)

**Comment by daniellee** [comment]
Great!
