### ISSUE TITLE
Zoom In/Out Bug?

### ISSUE THREAD

**Issue by dipenshah90** [grafana/grafana#7771]
Seeing different maximum values (Y-axes ) for Zoom in/out.

- What Grafana version are you using?
**Grafana v4.1.2 (commit: v4.1.2**

- What datasource are you using?
**PRTG (https://github.com/neuralfraud/grafana-prtg)** 

- What OS are you running grafana on?
**Ubuntu** 

- What did you do?
**When I zoom in the Graphs show different Max values as compared to when I zoom out. Please look at Y-axes values.**

**Zoomed In**:    http://pasteboard.co/H01gF1AeA.png
**Zoomed Out**: http://pasteboard.co/H01xdkzKm.png

- What was the expected result?
**I expect the maximum values to be the same irrespective of the Zoom?**

- What happened instead?
**The maximum values changed, thus giving me a wrong idea about is actually happening on a bigger date range.**

**Please let me know if you need more information.

Note: Tried looking for answers on IRC and previous issues. No luck.

Thanks.**

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment]
It depends in you metric query, so if you show Max in the legend you must use a max aggregation in your query. I am not familiar with PRTG so you have to consult that datasource
