### ISSUE TITLE
Explore: Time ranges in split view should be synced by default

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77742]
This was feedback from user interview. When user uses the Explore's split view, they expect it to be synced by default. They always have to sync manually.

**Comment by ifrost** [comment]
Interesting! How many users requested it comparing to how many were interviewed?

@diegoadams / @thanos-karachalios What do you think about this one?

**Comment by ivanahuckova** [comment]
> Interesting! How many users requested it comparing to how many were interviewed?

When we do interviews, we usually don't ask about specific features. So this is the first time I've heard this feedback, but we also almost never talk about split pane/syncing times.

**Comment by diegoadams** [comment]
@ivanahuckova , in what scenario does this happen, when viewing logs and metrics or traces side by side I thought the time always synced.

**Comment by diegoadams** [comment]
Since we currently don’t have a lot of data on how often users sync their time ranges in split view. It might be helpful to look into this a bit more to really get a feel for what most of our users prefer. @Elfo404, @gelicia  I know you spoke about this in the slack chat but is there any way we could put tracking on the sync time click?

**Comment by ifrost** [comment]
> @ivanahuckova , in what scenario does this happen, when viewing logs and metrics or traces side by side I thought the time always synced.

Hmm... that reminds me of one more thing. Data links use "split open" function. We don't want to sync times when a data link is clicked (at least not by default). Tempo data links use different, more specific time range (with a shift) that is different than the source pane.

**Comment by ivanahuckova** [comment]
>@ivanahuckova , in what scenario does this happen, when viewing logs and metrics or traces side by side I thought the time always synced.

In this specific case it was metrics + logs
