### ISSUE TITLE
Explore: Add to dashboard and new dashboard are looking same, but different behavior

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77743]
Different behaviour between 2 "plus" buttons - add to dashboard and new dashboard and it is confusing why they have different behaviour.

During user interview, user clicked on + button in top navigation and then was surprised why was the new dashboard empty and why didn't they see their original query. After a while, they realized that there are 2 `+` buttons that do different things:
- the lower one creates dashboard from query results
- the top one just creates new dashboard 

<img width="598" alt="image" src="https://github.com/grafana/grafana/assets/30407135/ae9b26f7-7257-451b-ad3f-7254aabbbfb6">

**Comment by gelicia** [comment]
@diegoadams we can change icons/etc here, but maybe both menus should be looked at and not just the explore one

**Comment by ifrost** [comment]
> @diegoadams we can change icons/etc here, but maybe both menus should be looked at and not just the explore one

Maybe the top one shouldn't be "+"? It looks like a generic shortcut menu. Also - is it expected it shows up all the time in any page in the top nav?

**Comment by gelicia** [comment]
@diegoadams Thanks for letting us know what the team thinks. Do we have a specific direction you'd like to see?

**Comment by diegoadams** [comment]
Removing the icon would be a good direction, but it also breaks the "icon"Text" layout on the toolbar as seen here. So there is a case for a new icon as well. 

This is what it looks like with no icon.
<img width="706" alt="Screenshot 2023-11-09 at 09 47 30" src="https://github.com/grafana/grafana/assets/95694434/37d077d9-3cbf-4cc3-83ba-c8aec0562f34">
a4be6de">

I would pause this for now and let me first align with @natydej  to make sure we are aligned and using the same pattern.

**Comment by ifrost** [comment]
Another suggestion from Explore team: We could disable top nav shortcut "+" dropdown when in Explore

**Comment by diegoadams** [comment]
Circling back to this I got some feedback from our UX Share & Aware session.
<img width="964" alt="Screenshot 2023-11-27 at 18 57 00" src="https://github.com/grafana/grafana/assets/95694434/1c4d487b-d50e-4a9f-b335-5c4cf4f9518c">

The key takeaways are: 

- Do we have current stats on which of the two buttons gets clicked more? I assume the Explore +Add.
- Was this one incident or have we received similar feedback regarding the confusion? 
- Perhaps an alterative + icon in Explore could work like this:

<img width="1980" alt="Screenshot 2023-11-27 at 19 21 12" src="https://github.com/grafana/grafana/assets/95694434/d793975e-67e8-4b16-a915-81d6f0bcebd4">

**Comment by Elfo404** [comment]
> Do we have current stats on which of the two buttons gets clicked more? I assume the Explore +Add.

no, we don't have any tracking of that specific action.

> Was this one incident or have we received similar feedback regarding the confusion?

we know of only one person getting confused about this so far. the feedback is still valid tho imho and the question of whether we want to fix this or not still remains

> Perhaps an alternative + icon in Explore could work like this:

we definitely can, is this the proposed solution? which icon do you think would fit the best?

**Comment by diegoadams** [comment]
I'm in favour of the "no icon" option as we are starting to add items to the toolbar like Query Library.  

<img width="843" alt="Screenshot 2024-02-21 at 19 58 30" src="https://github.com/grafana/grafana/assets/95694434/98345119-6cd2-4a69-8bb5-7ae3d59bc3fb">
