### ISSUE TITLE
PromQAIL - Copy updates

### ISSUE THREAD

**Issue by catherineymgui** [grafana/grafana#77753]
Update the copy for PromQAIL to emphasize steps an user has to take before using the feature

See all designs: https://www.figma.com/file/yG0a79rfRhfza8iawDgJ8z/PromQail---LLM-%2B-PromQL?type=design&node-id=326%3A16565&mode=design&t=oToSbu3pVZR26Ssb-1

- [ ] Add inline banner asking users to install the LLM app
<img width="1382" alt="Query Advisor - Updated LLM app banner" src="https://github.com/grafana/grafana/assets/5264102/720c6dc8-e5ea-46cb-b517-ee4a5c0b0f17">

- [ ] Remove description around "historical queries" when providing query suggestions
<img width="1382" alt="Query Advisor - Updated query suggestion copy" src="https://github.com/grafana/grafana/assets/5264102/10314630-81fc-4c4e-ae90-bca1fcc21913">

- [ ] Add tooltip when feature is disabled
<img width="1382" alt="Disabled - Tooltip" src="https://github.com/grafana/grafana/assets/5264102/97cef602-b33b-4fc9-90c3-e3ede93df026">

**Comment by bohandley** [comment]
Closed as these fixes have been updated in this fix https://github.com/grafana/grafana/pull/77903
