### ISSUE TITLE
Using Grafana with elasticsearch be able to use the output of one query in another

### ISSUE THREAD

**Issue by Exocomp** [grafana/grafana#7776]
I'm using Elasticsearch with the max metric on a field1 then using the terms aggregator to group by field2.  Essentially ending up with a list of rows with a unique identifier per row.  With a second query I would like to use that unique identifier (per row) and retrieve results.

**Comment by torkelo** [comment]
This would be cool. But it would be tricky to do and not seeing how we can make the changes for this top be possible. 

What you can do is create a template variable query, and use that variable in your metric query.
