### ISSUE TITLE
After upgrading to 10.2.0 Time series Bars it not readable

### ISSUE THREAD

**Issue by SDpower** [grafana/grafana#77765]
### Background / Why we're doing this

The setting will same as before the upgrade.

<img width="1070" alt="截圖 2023-11-07 上午10 10 22副本" src="https://github.com/grafana/grafana/assets/745625/e9160194-ca85-4fcf-bf79-1f15a23919b9">

**Refresh 2sec**
On 10.1.5:
![Nov-07-2023 10-35-13](https://github.com/grafana/grafana/assets/745625/f5bb6400-5cb9-4984-b193-160961f34143)

On 10.2.0:
![Nov-07-2023 10-23-59](https://github.com/grafana/grafana/assets/745625/7a684db3-f925-4779-8f98-28bfe87083fc)

### Is there existing research for this?

No research yet

### Problems or tasks

- A problem we're trying to solve
- A task the user needs to accomplish
- …

### Deliverables

- Figma mockup
- Miro board
- …

**Comment by leeoniya** [comment]
pretty sure this is fixed in https://github.com/grafana/grafana/pull/77317

can you try a nightly build?

https://grafana.com/grafana/download/nightly?edition=oss

**Comment by SDpower** [comment]
Yes, it is Fixed. #77317
Thank's @leeoniya
