### ISSUE TITLE
[Bug] Graph does not continue last value to current time

### ISSUE THREAD

**Issue by oblogic7** [grafana/grafana#7778]
Please include this information:
- What Grafana version are you using? 
**4.0.1**
- What datasource are you using? 
**InfluxDB**
- What OS are you running grafana on? 
**Raspbian Jessie**
- What did you do? 
**Created a chart containing data from a sensor that reports a binary state.  I used stiarcase display option with line and fill to indicate the state of the data.**
- What was the expected result?
**I expect that this combination of options (staircase + line) will automatically continue the line representing the last reported value to current time.**
- What happened instead?
**The graph does not represent the current state of the sensor since the line does not continue past the last recorded value to current time.  This means that if the last recorded datapoint is outside of the current time window, then the visual representation of the data is incorrect.**

![image](https://cloud.githubusercontent.com/assets/453840/23727108/690cd3ee-041c-11e7-90a0-a7e50b15eda8.png)

`SELECT "value" FROM "binary_sensor.test_door" WHERE time > 1488940908s and time < 1488941178s`

`{
  "results": [
    {
      "statement_id": 0,
      "series": [
        {
          "name": "binary_sensor.test_door",
          "columns": [
            "time",
            "value"
          ],
          "values": [
            [
              1488941015270,
              0
            ],
            [
              1488941018852,
              1
            ],
            [
              1488941033473,
              0
            ],
            [
              1488941047516,
              1
            ]
          ]
        }
      ]
    }
  ]
}`

**Comment by torkelo** [comment]
Grafana does not invent values as would be required in this case, would be  tricky as could be not what the user wants in many cases. 

In graphite there is a function keepLast that will make the database query keep last value, should have worked in your case. Think InfluxDB has  fill(last) which works the same but not sure.

**Comment by oblogic7** [comment]
The problem with fill(previous) is that is is a group by and requires an aggregate on the select.  For a binary state, aggregation of the values via mean() results in improper display of the data at certain zoom levels.  It does allow the previous value to continue to current time on the graph, but it means trading one incorrect visual representation for another.

![image](https://cloud.githubusercontent.com/assets/453840/23754807/f13163d4-04a3-11e7-95e4-d03b76b07c4b.png)

I don't expect Grafana to "invent values", but expect it to be smart enough to display the current state of a measurement even if the latest result is not within the currently selected time range.

**Comment by torkelo** [comment]
> I don't expect Grafana to "invent values", but expect it to be smart enough to display the current state of a measurement even if the latest result is not within the currently selected time range.

That is the responsibility of the TSDB query language. Graphite can do this for example. Much better to put this logic in the query. No way for Grafana to know that this is desired behaviour other than a a specific option for this. But it's a feature that feels much better placed in the query & transformation layer (TSDB query engine). 

> requires an aggregate on the select. For a binary state, aggregation of the values via mean() results in improper display of the data at certain zoom levels. 

Would not max(value) or last(value) work for your case? I mean there are other aggregations functions than `mean`  :)

**Comment by oblogic7** [comment]
Maybe I'm missing something, but I'm not presented with max or last options for aggregations.

![image](https://cloud.githubusercontent.com/assets/453840/23766854/0f8df0a4-04cc-11e7-8104-d3023cd8ce03.png)

**Comment by torkelo** [comment]
They are under Selectors (don't blame grafana for the strange categorisation, I took it from InfluxDB docs)

**Comment by phemmer** [comment]
For reference, see also #2296, as this issue seems to be a duplicate of that one.
