### ISSUE TITLE
support for google auth proxy

### ISSUE THREAD

**Issue by bridgetkromhout** [grafana/grafana#778]
Hi, @torkelo! We'd very much like to use Grafana, but would prefer not to use basic auth.

We have https://github.com/bitly/google_auth_proxy in front of our Graphite installation, so Grafana hits the google auth screen and can't proceed to Graphite. I know that last spring only basic auth was supported (my colleague @jvaleo discussed this with you here: https://github.com/grafana/grafana/issues/259), but perhaps adding more forms of auth might be of interest to you now? (Definitely of interest to us!)

Thanks either way. :)

**Comment by timurb** [comment]
After Grafana 2.0 is out I simply protect the OpenTSDB (Graphite in your case) external access with google_oauth_proxy and configure grafana-server to access it directly without any authentication.

I need to keep 2 pairs of google apps credentials for this but that's ok once you set it up.

**Comment by torkelo** [comment]
yea, the need for this should have been solved in Grafana 2.0 with integrated login/signup using Google OAuth, as well as datasource proxies,  and if that is not the case, working on this issue now: https://github.com/grafana/grafana/issues/1921
