### ISSUE TITLE
Need a way to link feature toggles to corresponding docs

### ISSUE THREAD

**Issue by Eve832** [grafana/grafana#77815]
Support has a customer that is requesting more robust documentation for feature toggles. There is a list with brief descriptions here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/ but we don't link to documentation (when it exists) that relates to the toggles. 
Moving forward, we'll be able to filter on the What's new feature toggle field for every release note entered into the CMS (and actually those toggles that are are mentioned in the older what's new in grafana OSS, and these rel notes usually do link to corresponding feature documentation, but the page above doesn't direct user eyes...

**Comment by GrafanaWriter** [comment]
Iceboxing for now as this would be significant effort and the impact and value is not clear.
