### ISSUE TITLE
Public Dashboards: Panel menu and data inspection not working

### ISSUE THREAD

**Issue by adkinsjd** [grafana/grafana#77825]
### What happened?

When viewing a public dashboard, occasionally the panel menu is unavailable, and if it is available the inspect->data view does not load.

https://github.com/grafana/grafana/assets/6424912/18415318-40b5-4bbd-8bdf-1dfca0384450

### What did you expect to happen?

Both the panel menu should be available and inspect->data should work as expected.

### Did this work before?

I do not know if this has ever worked, it has only been tried on one Grafana version (10.1.2) and it did not work there.

### How do we reproduce it?

1. Create a public dashboard with a time series panel and attempt to view the panel menu and inspect the panel data.

### Is the bug inside a dashboard panel?

This has only been tried with the time series panel.

### Environment (with versions)?

Grafana: 10.1.2
OS: MacOS 12.5.1
Browser: Brave  1.57.47 Chromium: 116.0.5845.96

### Grafana platform?

Kubernetes

### Datasource(s)?

Postgres

**Comment by tonypowa** [comment]
hi @adkinsjd 
thank you for creating this issue

I am not sure that this feature is supposed to work in public dashboards
Neither I could not reproduce it by manually creating a time-series panel in v9.5.x and 10.1.x

Could you share your panel by clicking on  `panel --> more --> get help`, in the panel's dropdown menu? This will help up mock up your data and try to reproduce your issue

Thank you
