### ISSUE TITLE
[Bug] Not able to see legends

### ISSUE THREAD

**Issue by rohitrsh** [grafana/grafana#7782]
Hi Team,

We have integrated grafana with hubot to fetch graphs on slack, but with all graphs we have noticed strange behavior that we are not able see legends in reverend image.

Same has been reported to hubot-grafana repo, [Missing Legends 55] (https://github.com/stephenyeargin/hubot-grafana/issues/55). After some debugging we found that its related to Grafana not hubot scripts.

While sharing dashboard `Share -> Direct link rendered image` We are getting the same image (Missing Legends) which we are getting on slack using hubot.

Attaching snapshot below
![image](https://cloud.githubusercontent.com/assets/17526588/23738487/4dc68564-04bf-11e7-9f8c-aa2a22e058d3.png)

Please help us, to troubleshoot it further. Rquired Information given below:

- What Grafana version are you using?
`As of now we have tested it on 4.0.2. 4.1.1 and Latest 4.1.2`
- What datasource are you using?
`We have tested it on CloudWatch, ELasticsearch and InfluxDB Datasrouces`
- What OS are you running grafana on?
`Its RHEL-7 and Centos-7`

-Rohit 

cc @stephenyeargin

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/rpm/#server-side-image-rendering

> yum install fontconfig
yum install freetype*
yum install urw-fonts

**Comment by rohitrsh** [comment]
My bad, thanks for the prompt response.

Now i am able to see fonts in my legends.

-Rohit

**Comment by torkelo** [comment]
no problem, it's easy to miss :) 

Will add this to the new FAQ category on the discourse community site we are building
