### ISSUE TITLE
CloudWatch: Dimension picker should load dimension keys without current filter

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#77828]
If you are editing an already set dimension, it doesn't load the key options properly:
![Screenshot 2023-11-07 at 3 21 35 PM](https://github.com/grafana/grafana/assets/5421859/974ad07c-f6f8-4187-beae-f5854405fb57)
This is because when it queries the backend, it sends it with the dimension value for the dimension its editing set (eg. for the above query it has the `dimensionFilters` set to `{"ClusterIdentifier":["redshift-cluster-grafana"],"NodeID":["Shared"]}` for the `dimensionKeys` query). We should query the backend without the dimensionKey we're changing set instead.

Repro:
1. Set CloudWatch datasource using details here: https://github.com/grafana/plugin-provisioning/blob/main/provisioning/datasources/aws-cloudwatch.yaml.
2. Open Explore and selected the following in query builder
- Namespace="AWS/Redshift"
- MetricName="CPUUtilization"
- Statistic: Average
- Dimension: "ClusterIdentifier"="redshift-cluster-grafana"
3. Run query
4. Try to change the Dimension - no option shows anymore in the dropdown list until the Dimension fields are removed and added back.

Reported in https://github.com/grafana/support-escalations/issues/8244

**Comment by marinnedea** [comment]
hi team, any chance to have a fix  released for this?

**Comment by iwysiu** [comment]
Hi @marinnedea ! A fix was just merged and should be released in the next 10.2.x patch release
