### ISSUE TITLE
Get yaml for provisioning a correlation from a correlation created via UI

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#77843]
**Why is this needed**:

I like creating correlations via the Explore UI because it lets me see the data that I'm working with, and helps me verify that the correlation I'm defining is actually what I was intending to create. Compare this to the process of creating a YAML snippet you'd need to provision that correlation. This is significantly slower and more error prone; you're typing in a text editor and hoping you get the values (and indentation) right. 

I want to use the UI to set up and refine exactly the correlation I want. I then want to export that correlation as the YAML snippet I'd need to provision that finalized correlation in other Grafanas at my company. This lets me roll it out and manage it in an automated way. 

**What would you like to be added**:

I want a way to export a correlation that I set up in the UI as the [YAML snippet I'd need to provision it](https://grafana.com/docs/grafana/latest/administration/correlations/create-a-new-correlation/#create-a-correlation-with-provisioning). From there, I can copy that YAML into where I provision my datasources in my Grafana configurations (namely, in the `provisioning/datasources` directory). 

**Who is this feature for?**

This is helpful for centralized observability teams and folks trying to roll out observability at scale and in an as-code way.

**Comment by Stono** [comment]
<img width="1250" alt="Screenshot 2023-11-30 at 10 21 31" src="https://github.com/grafana/grafana/assets/1486729/25e19c0f-5fce-4e88-a126-6a703bf8d9d5">

I'd also like this, in the interim i edit in the UI; then use developer tools to see the `correlations` api response, convert that to yaml, and put in datasources!
