### ISSUE TITLE
[BUG] future of "To" in alerting

### ISSUE THREAD

**Issue by leoleovich** [grafana/grafana#7784]
Hello Grafana team.
We were trying to play around with alerting and we found strange behaviour:
Since we are not 100% sure, that all data has arrived to graphite, we want to set `From: 10m`, `To: 5m` as a condition for query:
![image](https://cloud.githubusercontent.com/assets/4749052/23744966/b107bb60-04b6-11e7-9c0a-842728b1bf7c.png)
And right now it returns 500.
Graphite, as a tsdb, gets the query:
```
from=-10min&maxDataPoints=500&target=someQuery&until=5min"
```
Of course `until=5min` is the invalid part.
I've spent some time to dive into the code and this is what I found:
https://github.com/grafana/grafana/blob/master/pkg/tsdb/graphite/graphite.go#L53-L54
```
	formData := url.Values{
		"from":          []string{"-" + formatTimeRange(context.TimeRange.From)},
		"until":         []string{formatTimeRange(context.TimeRange.To)},
		"format":        []string{"json"},
		"maxDataPoints": []string{"500"},
	}
```
The problem is in this dirty magic, that "-" is added to "from" and not to "until". I assume there are some deep thoughts why it is done like this, that is why before sending Pull Request I want to discuss things.

Also from point of view alerting there is no restriction to specify "To". But I have to use `-2m`, which is very strange, when we have "From" without minus.

As the options, I see:
1) Add extra "-" to graphite tsdb part and check, that we do not have such things as "-now".
2) While reading `params` of alerting condition from database add "-" to "To".

Please recommend me the better way.

**Comment by torkelo** [comment]
Try `now-5m` in the To field (until in graphite), the from is implicitly `-` now

**Comment by leoleovich** [comment]
@torkelo it is obviously working. But this is not how it should be and. It confuses and introduces dark magic. Let's at least discuss how to improve interface.

**Comment by leoleovich** [comment]
This
![image](https://cloud.githubusercontent.com/assets/4749052/23750210/2abec5c4-04cc-11e7-9330-e3d439517f73.png)
And this
![image](https://cloud.githubusercontent.com/assets/4749052/23750218/35d40f1e-04cc-11e7-9b43-781cbd88953a.png)
Is just wrong from interface point of view. It is inconsistent and not clear for users.
Conditions for OF query should be in the same time values. If you use `10m`, which means 10m ago, the second value should have the same dimension.
I could take care of the problem myself, this is not an issue. I was just expecting you to share the reason why it is like it is.

**Comment by torkelo** [comment]
why is dark magic? the time picker works the same. I am open to ideas to make it more intutive

**Comment by leoleovich** [comment]
Let's imagine somebody needs to check the query within 5 minutes interval:
If configuration of alert conditions says - `query(A, 5m, now)`. In my understanding it is a scale like this `-10m____(-5m____now)` where we check from now to 5 minutes ago. To achieve it you had to  generate the Graphite query  `from=-5min&until=now` which has `-` in front of 5min.

The moment we want to shift the query to 5 minutes earlier - query should look like this: `query(A, 10m, 5m)` or `query(A, -10m, -5m)` or `query(A, now-10m, now-5m)` if we play by these rules and scale look like `(-10m____-5m)____now`.
This means we need to be consistent. 
But right now this breaks, because it does not have magic with adding `-` in front for `until`. Graphite query will look like this `from=-10min&until=5m` which is invalid from graphite point of view.

Something like `query(A,10m,-5m)` will help with the issue, but it rather looks like 15 minutes interval because of different signs.
Also usage of `now-` in one field is not obvious and if we revert sign of the `From` people would expect this to be done for `until` as well.
