### ISSUE TITLE
Grafana Server auto restart

### ISSUE THREAD

**Issue by James601232** [grafana/grafana#77846]
### What happened?

Recently. our grafana server auto restart. There are no obvious error log in grafana.log file. but we found some errors about grafana server in messages log while granfa server restart. as following:
 
Nov  8 14:07:54 Test grafana-server: panic: runtime error: index out of range [5] with length 5
Nov  8 14:07:54 Test grafana-server: goroutine 400845 [running]:
Nov  8 14:07:54 Test grafana-server: github.com/go-sql-driver/mysql.readLengthEncodedInteger(0xc001c52004, 0x5, 0xffc, 0xffc, 0x0, 0x0)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/utils.go:438 +0x1d0
Nov  8 14:07:54 Test grafana-server: github.com/go-sql-driver/mysql.(*mysqlConn).readResultSetHeaderPacket(0xc001b28360, 0x3, 0xc001586b40, 0x132)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go:552 +0x8e
Nov  8 14:07:54 Test grafana-server: github.com/go-sql-driver/mysql.(*mysqlConn).query(0xc001b28360, 0xc001586b40, 0x132, 0x3f99198, 0x0, 0x0, 0x0, 0x0, 0xc0031f1698)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:390 +0x18b
Nov  8 14:07:54 Test grafana-server: github.com/go-sql-driver/mysql.(*mysqlConn).QueryContext(0xc001b28360, 0x2c5eae0, 0xc000132010, 0xc001586b40, 0x132, 0x3f99198, 0x0, 0x0, 0x7f0d1c51efff, 0x1000, ...)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:512 +0x10f
Nov  8 14:07:54 Test grafana-server: database/sql.ctxDriverQuery(0x2c5eae0, 0xc000132010, 0x7f0d2c4df858, 0xc001b28360, 0x0, 0x0, 0xc001586b40, 0x132, 0x3f99198, 0x0, ...)
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/ctxutil.go:48 +0x22e
Nov  8 14:07:54 Test grafana-server: database/sql.(*DB).queryDC.func1()
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/sql.go:1650 +0x1df
Nov  8 14:07:54 Test grafana-server: database/sql.withLock(0x2c41d50, 0xc008a902d0, 0xc001a1b960)
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/sql.go:3294 +0x69
Nov  8 14:07:54 Test grafana-server: database/sql.(*DB).queryDC(0xc0015369c0, 0x2c5eae0, 0xc000132010, 0x0, 0x0, 0xc008a902d0, 0xc0016b8eb0, 0xc001586b40, 0x132, 0x0, ...)
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/sql.go:1645 +0x5d4
Nov  8 14:07:54 Test grafana-server: database/sql.(*DB).query(0xc0015369c0, 0x2c5eae0, 0xc000132010, 0xc001586b40, 0x132, 0x0, 0x0, 0x0, 0x417901, 0xc0028417a0, ...)
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/sql.go:1628 +0x13e
Nov  8 14:07:54 Test grafana-server: database/sql.(*DB).QueryContext(0xc0015369c0, 0x2c5eae0, 0xc000132010, 0xc001586b40, 0x132, 0x0, 0x0, 0x0, 0xc0031f1b01, 0xc0028417a0, ...)
Nov  8 14:07:54 Test grafana-server: /usr/local/go/src/database/sql/sql.go:1605 +0xd4
Nov  8 14:07:54 Test grafana-server: xorm.io/core.(*DB).QueryContext(0xc00769e800, 0x2c5eae0, 0xc000132010, 0xc001586b40, 0x132, 0x0, 0x0, 0x0, 0x18, 0xc000b8a618, ...)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/xorm.io/core@v0.7.3/db.go:121 +0x90
Nov  8 14:07:54 Test grafana-server: xorm.io/core.(*DB).Query(...)
Nov  8 14:07:54 Test grafana-server: /root/go/pkg/mod/xorm.io/core@v0.7.3/db.go:133
Nov  8 14:07:54 Test grafana-server: github.com/grafana/grafana/pkg/tsdb/sqleng.(*sqlQueryEndpoint).Query.func1(0xc005795354, 0xc0001b4620, 0xc000a91340, 0xc001586b40, 0x132, 0xc000a91380, 0xc001bd4580)
Nov  8 14:07:54 Test grafana-server: /drone/src/pkg/tsdb/sqleng/sql_engine.go:171 +0x15b
Nov  8 14:07:54 Test grafana-server: created by github.com/grafana/grafana/pkg/tsdb/sqleng.(*sqlQueryEndpoint).Query
Nov  8 14:07:54 Test grafana-server: /drone/src/pkg/tsdb/sqleng/sql_engine.go:165 +0x45c
Nov  8 14:07:54 Test systemd: grafana-server.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov  8 14:07:54 Test systemd: Unit grafana-server.service entered failed state.
Nov  8 14:07:54 Test systemd: grafana-server.service failed.
Nov  8 14:07:55 Test systemd: grafana-server.service holdoff time over, scheduling restart.
Nov  8 14:07:55 Test systemd: Starting Grafana instance...

### What did you expect to happen?

Grafana server should be not restart

### Did this work before?

we use 7.5.11 version all the time.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 
 version=7.5.11
OS:
Linux
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
Hi @James601232  👋 

Thank you for opening this issue.

However, I'm afraid that the Grafana version that you are using is no longer supported. The last 2 major versions of Grafana will receive support. 

If you upgrade and you still experience this issue, please open a new issue. 

We appreciate your understanding.
