### ISSUE TITLE
How to rename a Snapshot in Grafana?

### ISSUE THREAD

**Issue by arunmadanan** [grafana/grafana#7785]
Hi,

I saved a bunch of snapshots by the default names. Can any one tell me how to rename a snapshot that is already saved?

Grafana version: Grafana v4.1.1 
Datasource: Elastic search

Thanks in advance.

**Comment by daniellee** [comment]
There is currently no way to do it via Grafana. If you saved the snapshots locally and have access to the sql db for Grafana server, then you could change the name in the dashboard_snapshot table in the database. The other option is to delete them and recreate them with the correct name.
