### ISSUE TITLE
UI: Make possible to disable animations and css filters

### ISSUE THREAD

**Issue by baryluk** [grafana/grafana#77859]
### What happened?

When using Grafana 10.0.1 and 10.2.0, together with VNC to VM, some operations are super slow and hog a lot of vnc server to vnc client bandwidth, especially at higher resolutions.

This problem was not present before in Grafana 9.x, but Grafana 10.x add some extra animations and animated css filter behind few menus, which cause massive amount of screen redraw every frame.

### What did you expect to happen?

Smooth operations.

### Did this work before?

Yes.

### How do we reproduce it?

1. Run Grafana 10.x
2. Run VM, i.e. Fedora, and run desktop under Xvncserver
3. Connect, with high resolution screen
4. Maximise browser (Firefox, Chrome)
5. After login, Click either hamburger menu on the left, or the main search bar at the top.
6. Observe animation and css blue/frost filter applied to the rest of the page behind.

Example:

[grafana10-over-vnc.webm](https://github.com/grafana/grafana/assets/110322/4191054c-14f9-41ee-b684-52105debdc89)

Please note that above video capture, was captured at 30 fps, and AT VM side. On VNC client side it is even worse. The full viewport of the webpage had size 2275 px height x 2685 px tall.

![grafana10-example-viewport](https://github.com/grafana/grafana/assets/110322/c2bed0e3-f7ec-4610-8eda-0238ac757b40)

Running very same web browser version, at same viewport size, and same grafana server, but on client side (without VNC), is smooth. So this is not a browser, grafana or machine issue, but rather inherent to VNC transfering A LOT of data during these animations.

### Environment (with versions)?

Grafana: 10.x
OS: Doesn't matter
Browser: Doesn't matter

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @baryluk,

Thanks for opening this issue.

I am not sure about how to capture the VNC traffic data (just like we normally do with Chrome browser via .HAR file). So if possible then please send it to us.

Also as you said that this was not an issue in version 9.x 

Can you please specific the exact version number for Grafana 9 (e.g. 9.5.1 or 9.5.3 etc).

**Comment by SergeyGhoru** [comment]
`+` disable login form fade-in animation

**Comment by baryluk** [comment]
There few more places where this blur filters pop up, and are super slow over VNC.

For example doing a panel edit discard, panel save (to save a new dashboard), or going to dashboard settings and clicking dashboard save, where it ask for confirmation, it blurs (with animation) out the stuff behind the dialog.

Same happens on "Row options", "Row delete".

Some of these animation and blurring, were in older versions, i.e. in 8.4.2.

But, the one in the original post at the top, (search bar, and the left side panel), were working without animation or bluring in 8.4.2. 

As of in which version of 9.x it was or not was, I cannot tell quickly at the moment, as we do not have any 9.x running anymore.

There are some other animations too that would be nice to be able to disable, like collapsing a row / section, clicking the panel menu when in dashboard (currently the panel menu unrolls from the top as an animation) 

I would prefer it does not do either animation or blur (or apply any other filter, like darkening, desaturation, or anything like this), so it performs well over VNC.

**Comment by usmangt** [comment]
We have now Grafana version 10.x so if you are looking to reproduce it then use the most latest version of Grafana 10.

Version 8 and 9 (very soon) will be out of support.

**Comment by baryluk** [comment]
The bug is about Grafana 10

**Comment by JoaoSilvaGrafana** [comment]
Thank you for raising this, we understand that there could sometimes be issues with animations being slow or undesirable, so we are planning on implementing something with the [prefers-reduce-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query so that you can disable some of these animations on your device.

**Comment by baryluk** [comment]
Thanks. Do you know if these is an easy way to enable this prefers-reduce-motion selectors on desktop Firefox and Chromium?

**Comment by baryluk** [comment]
Answering myself. In Firefox:

> In Firefox `about:config`: Add a number preference called `ui.prefersReducedMotion` and set its value to either 0 for full animation or to 1 to indicate a preference for reduced motion. Changes to this preference take effect immediately.

Sounds good to me.

**Comment by joshhunt** [comment]
@eledobleefe's merged in some work to reduce some animations across Grafana, and we'll continue to address more animations over time.

If there's an animation in particular you're finding troubling, please raise a new issue for that specifically and we'll take a look at it 👍

**Comment by baryluk** [comment]
Thank you. Once we update our grafana (or I find to run some stuff in docker) at work, will check it out! Hopefully next week.

The most problematic was the animated guassian blur of the background when focusing on the main search field at the top of the grafana page. If there is more, or something else, I will open a separate new issue.

**Comment by react-map-gl** [comment]
@usmangt https://stylesheets.space/questions/css-3-blur-filter-without-the-use-of-transition-timing
