### ISSUE TITLE
dataList.map is not a function

### ISSUE THREAD

**Issue by RaghuKumarBA** [grafana/grafana#7786]
.execute/f</a.prototype.getSeriesList@http://localhost:8080/public/app/boot.js:18:28235
.execute/i</b.prototype.onDataReceived@http://localhost:8080/public/app/boot.js:19:3232
f.prototype.emit@http://localhost:8080/public/app/boot.js:52:2923
.execute/e</a.prototype.emit@http://localhost:8080/public/app/boot.js:52:5243
.execute/j</b.prototype.handleQueryResult@http://localhost:8080/public/app/boot.js:46:4930
g@http://localhost:8080/public/app/boot.js:42:13902
h/<@http://localhost:8080/public/app/boot.js:42:14074
xc/this.$get</o.prototype.$eval@http://localhost:8080/public/app/boot.js:42:21711
xc/this.$get</o.prototype.$digest@http://localhost:8080/public/app/boot.js:42:20193
xc/this.$get</o.prototype.$apply@http://localhost:8080/public/app/boot.js:42:21996
x/i<@http://localhost:8080/public/app/boot.js:42:18162
f@http://localhost:8080/public/app/boot.js:40:31993
jb/k.defer/c<@http://localhost:8080/public/app/boot.js:41:1437

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by daniellee** [comment]
Can you explain what caused this? It is very hard to diagnose your problem with just a stack trace.

**Comment by daniellee** [comment]
Closing, I will reopen if you can provide more details.

**Comment by alex-chaliy** [comment]
@daniellee  Hi! I have the same problem. Could you help me, please
![console_datalist_map_is_not_a_function](https://cloud.githubusercontent.com/assets/7645254/24697792/11fdc52c-19f7-11e7-924b-a6d809a8e0bb.png)
?
![dataList_map_is_not_a_function](https://cloud.githubusercontent.com/assets/7645254/24697633/8e6930de-19f6-11e7-8c66-1655947f191a.png)

**Comment by torkelo** [comment]
is your query returning data in correct format? You seem to use a custom data source

**Comment by benkindt** [comment]
I made the same mistake. Return an array and it's working.

See  http://docs.grafana.org/plugins/developing/datasources/
> Time series response from datasource.query. An array of:
> ...
