### ISSUE TITLE
[Bug] Alerting engine cannot be disabled

### ISSUE THREAD

**Issue by mayurjpatel** [grafana/grafana#7787]
Please include this information:
- What Grafana version are you using? v4.1.2
- What datasource are you using? Does not matter
- What OS are you running grafana on? Linux 64-bit
- What did you do? I added "enabled = false" in [alerting] section of configuration
- What was the expected result? I should not see alerting in the home drop down and should not see alert widget when creating a graph panel
- What happened instead? I saw alerting in the drop down

**Comment by torkelo** [comment]
This option is new in v4.2 should add a comment about that in the config docs
