### ISSUE TITLE
[Epic] Prometheus: Add new language features for query editor with updated lezer

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#77879]
The Prometheus query editor in Grafana is dependent on the lezer promQL parser. Updating the lezer version is a breaking change for Grafana currently and will require a significant work effort. The benefits of this work include:

- supporting new language features like `offset`
- support ooo
- need research
  - support fixes for [other issues](https://github.com/grafana/grafana/issues/71846)
  - histograms => https://github.com/grafana/grafana/issues/76111

Challenges:

- maintaining support for template variables in the parser

Proposed steps for work:

1. Document the features supported in the current lezer version
2. Update the version
3. Use @gtk-grafana's lezer language visualizer to explore the diff https://github.com/grafana/lezer-promql-tree-viz
4. Write tests to prove that the breaking changes are handled safely
5. Write tests to show the updated language features.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/85941
- [x] Update monaco-promql package
```

**Comment by itsmylife** [comment]
We must find a better approach than it was introduced in this PR https://github.com/grafana/grafana/pull/60461
Each `expr` that has grafana variables are parsed twice. That is not ideal.

**Comment by itsmylife** [comment]
Closing this epic with this issue created https://github.com/grafana/grafana/issues/87687
