### ISSUE TITLE
[Bug] ad hoc filter does not handle regexp correctly for influxdb

### ISSUE THREAD

**Issue by jonaz** [grafana/grafana#7788]
Grafana version: v4.0.2 (commit: v4.0.2)

When i use the ad hoc filter on a influxdb data source the query gets generated like this:

```
SELECT mean("value") FROM "cpu/usage_rate" WHERE time > now() - 7d AND "pod_name" =~ feature GROUP BY time(10m), "pod_name" fill(null)
```

However thats wrong. The influxdb needs regexp to be surrounded by / like this:
```
SELECT mean("value") FROM "cpu/usage_rate" WHERE time > now() - 7d AND "pod_name" =~ /feature/ GROUP BY time(10m), "pod_name" fill(null)
```

Is it expected to have to write /feature/ when searching for pods containing the word feature?

**Comment by torkelo** [comment]
This looks fixed, when I add ad hoc filter with white space it gets added with quotes
