### ISSUE TITLE
Transformation: Prevent overriding field conversion in convert field type transform

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#77898]
Currently the user is able to override a field's type multiple times. This probably doesn't make a lot of sense to support and leads to things breaking when converting to an enum field type multiple times.

What we probably should do is filter the list of fields to convert based on if the field already has an existing conversion.

See https://github.com/grafana/grafana/pull/76410 for additional context.

![Screenshot 2023-11-08 at 2 07 29 PM](https://github.com/grafana/grafana/assets/22381771/25d07272-a283-4894-a4c2-b7fd75e4ef9b)

**Comment by oscarkilhed** [comment]
Makes sense that the same transformation instance should only convert a field one time. I would expect a following instance of the convert field type transformation, to be able to convert the field again.
