### ISSUE TITLE
[Bug] No org assigned when using proxy authn + ldap authz

### ISSUE THREAD

**Issue by ncabatoff** [grafana/grafana#7789]
- What Grafana version are you using?
4.1.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Fedora 25 is the host OS, but using the stock docker image, so really Grafana is running on Debian Jessie.
- What did you do?
Configured a reverse proxy to do authentication, put Grafana into auth.proxy mode, and also enabled auth.ldap.
- What was the expected result?
As per #6895, Grafana trusts the proxy for authentication, but still does LDAP lookups for role/org assignment.
- What happened instead?
It mostly works, but when a user first logs in they get "org missing" and they have to manually switch to the main org before they can do anything.  In the logs I always see orgId=-1 initially:

t=2017-03-09T13:32:26+0000 lvl=info msg="Request Completed" logger=context userId=5 orgId=-1 uname=XXXX method=GET path=/api/dashboards/home status=200 remote_addr=172.17.0.10 time_ms=1ns size=1405

This happens regardless of what I put for auto_assign_org or in org_id keys in [[servers.group_mappings]] sections,

**Comment by daniellee** [comment]
It occurs because of this line:

https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy.go#L41

which leads to:

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/user.go#L37-L39

I guess this is a bug. I think the logic is that the org should be synced from ldap rather than being auto assigned by Grafana.

**Comment by ncabatoff** [comment]
I agree this is a bug.  There's also a related bug in the LDAP sync.  Once the account is created, any future changes to the corresponding LDAP object don't get sync'd.  Thus if you kick someone out of the LDAP group that gave them the Admin role, you have to manually update Grafana to assign a new role.

**Comment by asifmohammedgithub** [comment]
Hi Guys
Any update on this bug.
I have the same issue.

**Comment by trent** [comment]
+1 with same issue here.  Any fix planned?

**Comment by rajo** [comment]
can confirm this with a twist: I'm not using auth.proxy, but auth.basic and auth.ldap.

**Comment by nyrkovms** [comment]
+1 this bug
i'm using auth.ldap

**Comment by jasonkeller** [comment]
@daniellee any traction on this?

**Comment by zdenekpizl** [comment]
Is anybody going to fix this annoying bug? Each user added into databases after LDAP authentication is enabled must be manually tweaked in grafana's database now.

Or is there any reasonable workaround? Thank you, .zp.

**Comment by tsn77130** [comment]
same bug for me, always appears on 1st log with user put on special organization, I have to switch to org I defined in mapping section manually

**Comment by sspieker** [comment]
Ran into this, too...

**Comment by sspieker** [comment]
I have to get back to this: this exakt problem still occurs with the 5.0.0-pre1 code I just checked out and ran in my test environment.
I just don't understand the logic in the code which @daniellee posted in [march](https://github.com/grafana/grafana/issues/7789#issuecomment-285610379): why has "orgSetup" to be skipped if auto signup is used with auth proxy?
[auth_proxy.go#L41](https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy.go#L41)
`		if setting.AuthProxyAutoSignUp {
			cmd := getCreateUserCommandForProxyAuth(proxyHeaderValue)
			if setting.LdapEnabled {
				cmd.SkipOrgSetup = true
			}`

**Comment by tsn77130** [comment]
Hi, any news about this ?

this is very annoying in v5, because we can't no more manually switch to correct org (switch is no more displayed), so we can't use grafana no more with new users

**Comment by fyang13** [comment]
This seems still a problem in v5.0.1-pre1. Although I can do the workaround by manually updating "OrgID=-1" at existing dashboard url, afterwards the users can see the dashboards. But other functions like assign admin permission to the user does not work.
The suggestion to create user from API does not really work well, since auth.proxy + auth.ldap being used, the user still get created upon first login with no org associated even with allow_sign_up disabled:
 "allow_sign_up = false"

**Comment by pawarrchetan** [comment]
+1
Any updates on the issue ?

**Comment by mommsen** [comment]
+1
It would be really nice to get this bug fixed soon. Thanks!

**Comment by sevagh** [comment]
I can't recreate this on Grafana 5.2.4 (happens on 4.6.3 though).
