### ISSUE TITLE
Plugins: Grafana v10.2.0 requires internet connection to open plugins page

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#77905]
### What happened?

When I run grafana v10.2.0 on a device without internet connection cannot open the plugins page.
I get error 502 due to lookup which cannot happen

```
logger=context userId=2 orgId=1 uname=admin@admin.com t=2023-11-09T06:11:12.429435491Z level=error msg="Proxy request failed" err="dial tcp: lookup grafana.com on 127.0.0.11:53: server misbehaving"
logger=context userId=2 orgId=1 uname=admin@admin.com t=2023-11-09T06:11:12.429572178Z level=error msg="Request Completed" method=GET path=/api/gnet/plugins status=502 remote_addr=10.255.0.64 time_ms=9 duration=9.521542ms size=0 referer="http://127.0.0.1:3000/plugins?chunkNotFound=" handler=/api/gnet/*
```

### What did you expect to happen?

I expect to be able to use grafana in offline mode w/o having internet

### Did this work before?

It work on v9.5.9, after upgrading to v10 it does not work

### How do we reproduce it?

1. Run grafana v10
2. Do not have internet connection
3. Try to open plugins page

### Environment (with versions)?

Grafana: v10.2.0
OS: ubuntu/docker
Browser: chrome

### Grafana platform?

Docker

**Comment by leventebalogh** [comment]
Hopefully [this PR](https://github.com/grafana/grafana/pull/77978) will fix the issue.

(I think the bug was introduced in `10.2.0`, so hopefully `10.1.5` should work in the meantime.)

**Comment by leventebalogh** [comment]
The [fix](https://github.com/grafana/grafana/pull/77978) is merged, I am afraid it won't be part of version 10.2.1, however will be in 10.3.0 for sure. 

Closing this issue, please reopen if you have objections.
