### ISSUE TITLE
[Bug] Alerting not working for file based Dashboards

### ISSUE THREAD

**Issue by deelthor** [grafana/grafana#7790]
We are running Grafana 4.1.2 in Docker with Prometheus as datasource. Because we dont want to create our dashboards manually we have them pre-configured as JSON files and copy them to the according folder within the container. This is working perfectly so far. Now we wanted to use the alerting feature. Our standard workflow for creating a dashboard is:

1. Create dashboard manually via UI
2. View/Copy the JSON of the created dashboard 
3. Add it to our project so it will be created on the next startup

We did the same to test alerting. The alert tab is also appearing in the ui in the dashboard and the config looks fine. But it wouldnt trigger an alert at any time and the dashboard status wont change.

When I create the same dashboard via the REST API it works fine.

Is there a known issue with file based dashboards?

Here is the JSON of the Dashboard:

`{
  "annotations": {
    "list": []
  },
  "editMode": false,
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "hideControls": false,
  "id": null,
  "links": [],
  "rows": [
    {
      "collapse": false,
      "height": 612,
      "panels": [
        {
          "alert": {
            "conditions": [
              {
                "evaluator": {
                  "params": [
                    499
                  ],
                  "type": "gt"
                },
                "operator": {
                  "type": "and"
                },
                "query": {
                  "datasourceId": 1,
                  "model": {
                    "expr": "avg(gauge_test_Amount{sp_container=\"test\", sp_stage=\"dev\"}) by (name)",
                    "intervalFactor": 2,
                    "legendFormat": "{{name}}",
                    "metric": null,
                    "refId": "A",
                    "step": 4
                  },
                  "params": [
                    "A",
                    "1m",
                    "now"
                  ]
                },
                "reducer": {
                  "params": [],
                  "type": "max"
                },
                "type": "query"
              }
            ],
            "executionErrorState": "alerting",
            "frequency": "60s",
            "handler": 1,
            "message": "Test Alert",
            "name": "Alert Testing",
            "noDataState": "no_data",
            "notifications": [
              {
                "id": 1
              }
            ]
          },
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {},
          "id": 1,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg(gauge_test_Amount{sp_container=\"test\", sp_stage=\"dev\"}) by (name)",
              "intervalFactor": 2,
              "legendFormat": "{{name}}",
              "metric": null,
              "refId": "A",
              "step": 4
            }
          ],
          "thresholds": [
            {
              "colorMode": "critical",
              "fill": true,
              "line": true,
              "op": "gt",
              "value": 499
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Amount Dev",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "sort": 0,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "Row",
      "titleSize": "h6"
    },
    {
      "collapse": false,
      "height": "250px",
      "panels": [],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "New row",
      "titleSize": "h6"
    },
    {
      "collapse": false,
      "height": "250px",
      "panels": [],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "New row",
      "titleSize": "h6"
    }
  ],
  "schemaVersion": 14,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": true,
          "tags": [],
          "text": "dev",
          "value": "dev"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "label": "Stage",
        "multi": false,
        "name": "job",
        "options": [
          {
            "selected": true,
            "text": "dev",
            "value": "dev"
          },
          {
            "selected": false,
            "text": "pp",
            "value": "pp"
          }
        ],
        "query": "dev,pp",
        "refresh": 0,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "Amound Dev",
  "version": 1
}`

**Comment by torkelo** [comment]
yes, we are not going to support alerting for file based dashboards. But hope to change how file based dashboards work (for example sync them continuously from file to db)

**Comment by deelthor** [comment]
Thanks for the quick answer!
