### ISSUE TITLE
[Feature request] Graphite's expand API to be used in Query of Template Variable

### ISSUE THREAD

**Issue by mcbsdEU** [grafana/grafana#7792]
Hi,

I believe following might be very handy. Imagine following situation.
Metrics:
production.server.server01.linuxRelatedMetric
production.server.server02.linuxRelatedMetric
production.server.server03.windowsRelatedMetric
production.server.server04.windowsRelatedMetric

It is not possible to distinguish whether server is Linux or Windows just by the "path".
However it is known only Windows servers have windowsRelatedMetric and similarly for Linux. 

Current behaviour:
Query field in Template Variable is taking result from /metrics/find API. Therefore it is not possible to return output with wildcard * used in the middle of query.
Etc.: query "production.server.*.windowsRelatedMetric" can't return output [server03, server 04].

Expected behaviour:
Etc.: query "production.server.*.windowsRelatedMetric" will return output [server03, server 04].
Then such output could be perfectly used when creating separate dashboards for Linux and Windows or even better to be used in same way for tags.

Possible solution:
/metrics/expand is able to consume query like "production.server.*.windowsRelatedMetric" and returns output as full path, for instance.:
production.server.server03.windowsRelatedMetric
production.server.server04.windowsRelatedMetric

-then it is easy to extract node name by regex

I really believe many people will find this useful.
Thanks!
.......................
- What Grafana version are you using? - 4.1.2
- What datasource are you using? - Graphite
- What OS are you running grafana on? - CentOS 7

**Comment by torkelo** [comment]
good feature request and description! 

Will close as we have a feature request already for this :)
https://github.com/grafana/grafana/issues/2343
