### ISSUE TITLE
[Feature request] Subqueries on InfluxDB with authentication

### ISSUE THREAD

**Issue by khenderick** [grafana/grafana#7793]
Since InfluxDB 1.2 subqueries are supported, these work fine if entered manually since the editor does not (yet) support them. However, as soon as InfluxDB is configured with authentication, the query fails.

Query example: `SELECT last("foo") / last("bar") FROM (SELECT last("aaa") as "foo" FROM ... WHERE ... GROUP BY ...), (SELECT last("bbb") as "bar" FROM .... WHERE .... GROUP BY ...) WHERE ... GROUP BY ...`

The returned error:
```
{ 
    "error": "error authorizing query: invalid measurement: (SELECT last("aaa") as "foo" FROM ... WHERE ... GROUP BY ...)",  
    "message": "error authorizing query: invalid measurement: (SELECT last("aaa") as "foo" FROM ... WHERE ... GROUP BY ...)"
}
```

Using:
* Grafana: 4.1.1
* InfluxDB: 1.2
* OS: Ubuntu 16.04

**Comment by torkelo** [comment]
Not sure what Grafana can do here. Since the auth is in the Header, and there is no difference for Grafana in how it sends the query to InfluxDB. 

Maybe an InfluxDB bug?
