### ISSUE TITLE
Elasticsearch: Support template variables as the Size of Group by Terms

### ISSUE THREAD

**Issue by alexandrul** [grafana/grafana#7794]
Currently the template variable is parsed as an int and I'm getting ```illegal_argument_exception```: ```[terms] size doesn't support values of type: VALUE_NULL```

![group_by__size](https://cloud.githubusercontent.com/assets/663809/23757650/197d552c-04f0-11e7-95b7-6f02907f4a9a.png)

Grafana v4.3.0-pre1 (commit: 2f5814d51)
ES 5.x
Windows 7 x64

**Comment by alexandrul** [comment]
This is the int parsing part:
```b.terms.size = 0 === parseInt(a.settings.size, 10) ? 500 : parseInt(a.settings.size, 10)```

This enhancement seems to be working with an extra step: if ```a.settings.size``` is not a number then ```b.terms.size = a.settings.size```

Of course, there should be some sanity checks (it makes no sense to use a multi-value template var here).

**Comment by alexandrul** [comment]
up

**Comment by apetzo** [comment]
I ran into the same issue just now with elastic and Grafana 7.0

**Comment by simianhacker** [comment]
@Elfo404 Should every setting be overridable by variables? The only variables that seem to show up in the `options.scopedVars` is `$_interval` and `$_intervalMS`. I setup a 'constant' variable which only seems to be available via the `templateSrv.getVariables()` on the data source.

**Comment by Elfo404** [comment]
@simianhacker ideally any user input should support variables when it makes sense. I started working on a draft some time ago in #29739 which seems to work quite okay-ish, but it needs a bit more investigation.
