### ISSUE TITLE
CloudWatch log derived field to Tempo trace

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77948]
### Discussed in https://github.com/grafana/grafana/discussions/42498

<div type='discussions-op-text'>

<sup>Originally posted by **berabulut** November 30, 2021</sup>
I am manually instrumenting my Lambda functions and sending traces to Tempo. With the query below I can access CloudWatch logs and can see traceID as a derivedField in Grafana.

`fields @timestamp, @message | filter @message like /traceID/ | sort @timestamp desc`

I want to go a Tempo trace directly with a button like Loki's. Is this possible?     </div>

**Comment by idastambuk** [comment]
Hi @berabulut thanks for you patience in us getting to this. 

Grafana@10 actually supports the [Correlations feature](https://grafana.com/docs/grafana/latest/administration/correlations/) that might provide what you need. Here's the docs for it: 

Keep in mind that the feature is currently only supported in explore, but explore queries can easily be opened from dashboards, from panel options. 

Also, you will have to target Cloudwatch's @message field when adding the correlation:



<img src="https://github.com/grafana/grafana/assets/16140639/18573be3-07e4-4a01-817f-0eac4ee193ce" width="400">


Let us know if that works for you!

**Comment by idastambuk** [comment]
Hi again @berabulut, since we haven't had activity on this for a while, I will close it. I hope the above suggestion was useful!
