### ISSUE TITLE
Enable/Disable Cloudwatch Metrics

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77950]
Users sometimes only wish to use Cloudwatch Metrics or Cloudwatch Logs and not necessarily both. 

Right now if you only use the datasource for Cloudwatch Logs, you always have to see a ui that is inoperable for you for Cloudwatch Metrics before you navigate away. 

Relates to https://github.com/grafana/grafana/issues/67850

### Discussed in https://github.com/grafana/grafana/discussions/44942

<div type='discussions-op-text'>

<sup>Originally posted by **ainapudi** February  3, 2022</sup>
We do not expose CW metrics to Grafana users. We want the ability to hide metrics from the dropdown when selecting the datasource in the UI.</div>

**Comment by katebrenner** [comment]
Closing - we wont get to it in the next 6 months
