### ISSUE TITLE
Cloudwatch: Feature Request for Tag Support (alias support for tags and filtering by tags)

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77953]
Users find it difficult to navigate Instance Ids and would rather be able to view by tag name

### Discussed in https://github.com/grafana/grafana/discussions/41816

<div type='discussions-op-text'>

<sup>Originally posted by **Alex-Richman** August 29, 2020</sup>
Add support for using resource tags in the CloudWatch query alias.

See attached PR for details.

Example:
![2](https://user-images.githubusercontent.com/1280519/91644580-416c3c00-ea35-11ea-867a-61fbcb02be7a.png)
</div>

See also: https://github.com/grafana/grafana/discussions/56612

**Comment by schndr** [comment]
Hey,

It would be great to filter AWS resources by tags with the Grafana Cloudwatch data source.

It's already possible by using the official Grafana AWS integration, which is based on Cloudwatch API polling and ingesting the metrics into the telemetry storage. However, this creates AWS costs (CW requests). Introducing the same feature for the Grafana Cloudwatch data source, Grafana would enable the users to decrease the AWS costs and switch to the Grafana Cloudwatch data source. Here’s an example: Show me the CPU utilization of all databases from team X.
