### ISSUE TITLE
[Feature request] Panel for Sankey Diagram

### ISSUE THREAD

**Issue by kumaravel29** [grafana/grafana#7795]
It would be great if there would be Sankey Diagram panel in Grafana

**Comment by mattttt** [comment]
This also came up in a conversation with a Grafana Commercial Support customer. Would love to see this as well.

@Kumaravel2904 Can you give a bit more detail on what data you'd like to use it with?

**Comment by daniellee** [comment]
If we added a panel plugin then we would probably use this:

https://github.com/d3/d3-sankey

Demo of the sankey plugin: https://bl.ocks.org/xaranke/9ada4c74a87b57ae7308

The hard part is figuring out how this would work in the Grafana context with time series data.
This is a little bit similar to the [diagram panel](https://grafana.net/plugins/jdbranham-diagram-panel) which configures the connections between nodes by using a special syntax for diagrams (Mermaid JS).

**Comment by royemmerich** [comment]
I'm looking for a way to depict energy flow from multiple (renewable) energy sources (e.g. wind, solar, diesel generator) and where this energy goes to (e.g. some into the battery, some straight to loads).

Being able to dynamically update this would be 👍

**Comment by mbucknel** [comment]
I have also been looking for Sankey in grafana,  I have found one for kibana, so that uses time series data.
https://github.com/chenryn/kbn_sankey_vis
I am sure this could be used as a basis for the grafana plugin, i have it working in kibana and it works nicely for netflow data.

**Comment by kumaravel29** [comment]
Out of curiosity, I have created a sankey diagram plugin/panel for grafana using the piechart panel as a baseline and google charts drawing sankey diagram. https://github.com/kumaravel29/sankey-panel

**Comment by zoltanbedi** [comment]
We most likely wont implement this ourselves so feel free to use @kumaravel29 solution.
