### ISSUE TITLE
Docs: Add link or info about WSL info in Grafana installation on Windows instructions

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#77968]
Instructions for installation on Windows make no reference to WSL procedures. I would like to see a link to https://grafana.com/blog/2021/03/03/how-to-set-up-a-grafana-development-environment-on-a-windows-pc-using-wsl/ (assuming this 2021 info is still up-to-date) or perhaps even a separate topic on WSL as a variety of Linux installation.

**Comment by Eve832** [comment]
Rather than linking out to the blog, should we vet the info and pull it into the tech docs?

**Comment by josmperez** [comment]
> should we vet the info and pull it into the tech docs

Yes, that's probably the best long-term solution. At a mimimum, a link.
