### ISSUE TITLE
Cloudwatch: Support Querying Alarms

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77962]
In the AWS Console there's a section for Alerts, Metrics, and Logs, but our Cloudwatch Datasource only supports querying for Metrics and Logs right now. What would it be like to query/visualize Alarms from Cloudwatch inside Grafana?
<img width="250" alt="Screenshot 2023-11-09 at 1 52 42 PM" src="https://github.com/grafana/grafana/assets/6620164/7ba6d478-62fd-4a2c-b3ad-e0972223e4a2">

### Discussed in https://github.com/grafana/grafana/discussions/41815

<div type='discussions-op-text'>

<sup>Originally posted by **jjshoe** April  5, 2021</sup>
In cloudwatch, you can have panels which display various drawings of data, a table of logs, and you can include relevant alarms.

Stated another way, given web app hello world, I can have three panels:
1) Requests per second as a line graph
2) Last 100 log messages
3) Alarms for cpu, disk space, and requests per second

In Grafana, I would love support for #3. The visualization for "Alert List" does not seem to support querying AWS cloudwatch in any way.

Supporting requests:
https://github.com/grafana/grafana/issues/19013
https://community.grafana.com/t/show-aws-cloudwatch-alarms-in-table/14879</div>

**Comment by katebrenner** [comment]
closing because this is not on our immediate roadmap
