### ISSUE TITLE
Dashboard annotations: "toLowerCase is not a function" error - hovering over PagerDuty annotations

### ISSUE THREAD

**Issue by catewascat** [grafana/grafana#77989]
### What happened?

What are you trying to achieve? Hovering over a PagerDuty annotation for more detail
How are you trying to achieve it? I’ve set up the PagerDuty datasource, have configured annotations for a service.
What happened? The annotations show on the graph, but when I hover over an annotation I get an error on the graph "toLowerCase is not a function"

### What did you expect to happen?

I would expect to see incident details when hovering over the annotation

### Did this work before?

No 

### How do we reproduce it?

1.  Set up a PagerDuty annotation on a dashboard - with or without any filtering parameters
2.  Load dashboard and see annotations
3.  Hover over an annotation

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana:  v10.2.0-62263
OS:  Windows 11 Pro
Browser:  Chrome 119.0.6045.107 

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

PagerDuty

**Comment by armandgrillet** [comment]
You seem to be talking about https://github.com/xginn8/grafana-pagerduty which is not owned by owners of this repository, this does not seem to have anything to do with Grafana Alerting. Feel free to reopen if that is not correct.
