### ISSUE TITLE
[Feature Request]: Allow visualization of non-time series datasource data in Bar Charts

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#7798]
Related to: https://github.com/grafana/grafana/pull/5917 . However, it seems that bar charts are only able to be used with Data that is in time series format from the datasource.

For datasources that support raw histogram or table storage, it would be good to be able to pass it raw data. In particular for histograms it allows you to have better and more accurate representations of latency. Bit it would also be helpful for categorical data where the transform happens in the datasource and not in grafana.

Edit:

Chatted with @Dieterbe @torkelo and @alexanderzobnin about this a little. The main feature is to support what are calling "pre-bucketed" data and doesn't process time series data client side. Example datastores than can do this are Elastic, Elastic via Bosun, and IronDB.

**Comment by kylebrandt** [comment]
Example Histogram object:

```
{
  "StartTime": 0,
  "EndTime": 0,
  "Buckets": [
    {
      "Low": 0,
      "Count": 1090
    },
    {
      "Low": 10,
      "Count": 640
    },
    {
      "Low": 20,
      "Count": 131
    },
    {
      "Low": 30,
      "Count": 34
    },
    {
      "Low": 40,
      "Count": 15
    },
    {
      "Low": 50,
      "Count": 9
    },
    {
      "Low": 60,
      "Count": 8
    },
    {
      "Low": 70,
      "Count": 4
    },
    {
      "Low": 80,
      "Count": 9
    },
    {
      "Low": 90,
      "Count": 6
    },
    {
      "Low": 100,
      "Count": 9
    },
    {
      "Low": 110,
      "Count": 4
    },
    {
      "Low": 120,
      "Count": 1
    },
    {
      "Low": 130,
      "Count": 4
    },
    {
      "Low": 140,
      "Count": 3
    },
    {
      "Low": 150,
      "Count": 5
    },
    {
      "Low": 160,
      "Count": 3
    },
    {
      "Low": 170,
      "Count": 3
    },
    {
      "Low": 180,
      "Count": 2
    },
    {
      "Low": 190,
      "Count": 1
    },
    {
      "Low": 200,
      "Count": 1
    },
    {
      "Low": 210,
      "Count": 1
    },
    {
      "Low": 220,
      "Count": 1
    },
    {
      "Low": 230,
      "Count": 1
    },
    {
      "Low": 240,
      "Count": 0
    },
    {
      "Low": 250,
      "Count": 1
    },
    {
      "Low": 260,
      "Count": 0
    },
    {
      "Low": 270,
      "Count": 2
    },
    {
      "Low": 280,
      "Count": 1
    },
    {
      "Low": 290,
      "Count": 1
    },
    {
      "Low": 300,
      "Count": 1
    },
    {
      "Low": 310,
      "Count": 3
    },
    {
      "Low": 320,
      "Count": 0
    },
    {
      "Low": 330,
      "Count": 0
    },
    {
      "Low": 340,
      "Count": 0
    },
    {
      "Low": 350,
      "Count": 0
    },
    {
      "Low": 360,
      "Count": 1
    },
    {
      "Low": 370,
      "Count": 0
    },
    {
      "Low": 380,
      "Count": 0
    },
    {
      "Low": 390,
      "Count": 0
    },
    {
      "Low": 400,
      "Count": 0
    },
    {
      "Low": 410,
      "Count": 0
    },
    {
      "Low": 420,
      "Count": 0
    },
    {
      "Low": 430,
      "Count": 0
    },
    {
      "Low": 440,
      "Count": 0
    },
    {
      "Low": 450,
      "Count": 0
    },
    {
      "Low": 460,
      "Count": 0
    },
    {
      "Low": 470,
      "Count": 0
    },
    {
      "Low": 480,
      "Count": 0
    },
    {
      "Low": 490,
      "Count": 0
    },
    {
      "Low": 500,
      "Count": 0
    },
    {
      "Low": 510,
      "Count": 0
    },
    {
      "Low": 520,
      "Count": 0
    },
    {
      "Low": 530,
      "Count": 0
    },
    {
      "Low": 540,
      "Count": 0
    },
    {
      "Low": 550,
      "Count": 0
    },
    {
      "Low": 560,
      "Count": 0
    },
    {
      "Low": 570,
      "Count": 0
    },
    {
      "Low": 580,
      "Count": 0
    },
    {
      "Low": 590,
      "Count": 0
    },
    {
      "Low": 600,
      "Count": 0
    },
    {
      "Low": 610,
      "Count": 0
    },
    {
      "Low": 620,
      "Count": 0
    },
    {
      "Low": 630,
      "Count": 0
    },
    {
      "Low": 640,
      "Count": 0
    },
    {
      "Low": 650,
      "Count": 0
    },
    {
      "Low": 660,
      "Count": 0
    },
    {
      "Low": 670,
      "Count": 0
    },
    {
      "Low": 680,
      "Count": 0
    },
    {
      "Low": 690,
      "Count": 0
    },
    {
      "Low": 700,
      "Count": 0
    },
    {
      "Low": 710,
      "Count": 0
    },
    {
      "Low": 720,
      "Count": 0
    },
    {
      "Low": 730,
      "Count": 0
    },
    {
      "Low": 740,
      "Count": 0
    },
    {
      "Low": 750,
      "Count": 0
    },
    {
      "Low": 760,
      "Count": 0
    },
    {
      "Low": 770,
      "Count": 0
    },
    {
      "Low": 780,
      "Count": 0
    },
    {
      "Low": 790,
      "Count": 0
    },
    {
      "Low": 800,
      "Count": 0
    },
    {
      "Low": 810,
      "Count": 0
    },
    {
      "Low": 820,
      "Count": 0
    },
    {
      "Low": 830,
      "Count": 0
    },
    {
      "Low": 840,
      "Count": 0
    },
    {
      "Low": 850,
      "Count": 0
    },
    {
      "Low": 860,
      "Count": 0
    },
    {
      "Low": 870,
      "Count": 0
    },
    {
      "Low": 880,
      "Count": 0
    },
    {
      "Low": 890,
      "Count": 0
    },
    {
      "Low": 900,
      "Count": 0
    },
    {
      "Low": 910,
      "Count": 0
    },
    {
      "Low": 920,
      "Count": 0
    },
    {
      "Low": 930,
      "Count": 0
    },
    {
      "Low": 940,
      "Count": 0
    },
    {
      "Low": 950,
      "Count": 0
    },
    {
      "Low": 960,
      "Count": 0
    },
    {
      "Low": 970,
      "Count": 0
    },
    {
      "Low": 980,
      "Count": 0
    },
    {
      "Low": 990,
      "Count": 0
    },
    {
      "Low": 1000,
      "Count": 0
    },
    {
      "Low": 1010,
      "Count": 0
    },
    {
      "Low": 1020,
      "Count": 0
    },
    {
      "Low": 1030,
      "Count": 0
    },
    {
      "Low": 1040,
      "Count": 0
    },
    {
      "Low": 1050,
      "Count": 0
    },
    {
      "Low": 1060,
      "Count": 0
    },
    {
      "Low": 1070,
      "Count": 0
    },
    {
      "Low": 1080,
      "Count": 0
    },
    {
      "Low": 1090,
      "Count": 0
    },
    {
      "Low": 1100,
      "Count": 0
    },
    {
      "Low": 1110,
      "Count": 0
    },
    {
      "Low": 1120,
      "Count": 0
    },
    {
      "Low": 1130,
      "Count": 0
    },
    {
      "Low": 1140,
      "Count": 0
    },
    {
      "Low": 1150,
      "Count": 0
    },
    {
      "Low": 1160,
      "Count": 0
    },
    {
      "Low": 1170,
      "Count": 0
    },
    {
      "Low": 1180,
      "Count": 0
    },
    {
      "Low": 1190,
      "Count": 0
    },
    {
      "Low": 1200,
      "Count": 0
    },
    {
      "Low": 1210,
      "Count": 0
    },
    {
      "Low": 1220,
      "Count": 0
    },
    {
      "Low": 1230,
      "Count": 0
    },
    {
      "Low": 1240,
      "Count": 0
    },
    {
      "Low": 1250,
      "Count": 0
    },
    {
      "Low": 1260,
      "Count": 0
    },
    {
      "Low": 1270,
      "Count": 0
    },
    {
      "Low": 1280,
      "Count": 0
    },
    {
      "Low": 1290,
      "Count": 0
    },
    {
      "Low": 1300,
      "Count": 0
    },
    {
      "Low": 1310,
      "Count": 0
    },
    {
      "Low": 1320,
      "Count": 0
    },
    {
      "Low": 1330,
      "Count": 0
    },
    {
      "Low": 1340,
      "Count": 0
    },
    {
      "Low": 1350,
      "Count": 0
    },
    {
      "Low": 1360,
      "Count": 0
    },
    {
      "Low": 1370,
      "Count": 0
    },
    {
      "Low": 1380,
      "Count": 0
    },
    {
      "Low": 1390,
      "Count": 0
    },
    {
      "Low": 1400,
      "Count": 0
    },
    {
      "Low": 1410,
      "Count": 0
    },
    {
      "Low": 1420,
      "Count": 0
    },
    {
      "Low": 1430,
      "Count": 0
    },
    {
      "Low": 1440,
      "Count": 0
    },
    {
      "Low": 1450,
      "Count": 0
    },
    {
      "Low": 1460,
      "Count": 0
    },
    {
      "Low": 1470,
      "Count": 1
    },
    {
      "Low": 1480,
      "Count": 0
    },
    {
      "Low": 1490,
      "Count": 0
    },
    {
      "Low": 1500,
      "Count": 0
    },
    {
      "Low": 1510,
      "Count": 1
    }
  ],
  "Interval": 10
}
```

**Comment by kylebrandt** [comment]
FWIW would like pre-bucketed data in heatmaps as well:

{
  "TimeBuckets": {
    "1489091100": [
      {
        "Low": 0,
        "Count": 14
      },
      {
        "Low": 10,
        "Count": 15
      },
      {
        "Low": 20,
        "Count": 1
      },
      {
        "Low": 30,
        "Count": 0
      },
      {
        "Low": 40,
        "Count": 0
      },
      {
        "Low": 50,
        "Count": 0
      },
      {
        "Low": 60,
        "Count": 0
      },
      {
        "Low": 70,
        "Count": 0
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 6
      }
    ],
    "1489091160": [
      {
        "Low": 0,
        "Count": 84
      },
      {
        "Low": 10,
        "Count": 77
      },
      {
        "Low": 20,
        "Count": 25
      },
      {
        "Low": 30,
        "Count": 7
      },
      {
        "Low": 40,
        "Count": 3
      },
      {
        "Low": 50,
        "Count": 3
      },
      {
        "Low": 60,
        "Count": 1
      },
      {
        "Low": 70,
        "Count": 0
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 20
      }
    ],
    "1489091220": [
      {
        "Low": 0,
        "Count": 160
      },
      {
        "Low": 10,
        "Count": 166
      },
      {
        "Low": 20,
        "Count": 44
      },
      {
        "Low": 30,
        "Count": 8
      },
      {
        "Low": 40,
        "Count": 9
      },
      {
        "Low": 50,
        "Count": 0
      },
      {
        "Low": 60,
        "Count": 3
      },
      {
        "Low": 70,
        "Count": 1
      },
      {
        "Low": 80,
        "Count": 2
      },
      {
        "Low": 90,
        "Count": 9
      }
    ],
    "1489091280": [
      {
        "Low": 0,
        "Count": 226
      },
      {
        "Low": 10,
        "Count": 161
      },
      {
        "Low": 20,
        "Count": 34
      },
      {
        "Low": 30,
        "Count": 4
      },
      {
        "Low": 40,
        "Count": 1
      },
      {
        "Low": 50,
        "Count": 2
      },
      {
        "Low": 60,
        "Count": 0
      },
      {
        "Low": 70,
        "Count": 1
      },
      {
        "Low": 80,
        "Count": 1
      },
      {
        "Low": 90,
        "Count": 10
      }
    ],
    "1489091340": [
      {
        "Low": 0,
        "Count": 274
      },
      {
        "Low": 10,
        "Count": 124
      },
      {
        "Low": 20,
        "Count": 40
      },
      {
        "Low": 30,
        "Count": 10
      },
      {
        "Low": 40,
        "Count": 3
      },
      {
        "Low": 50,
        "Count": 2
      },
      {
        "Low": 60,
        "Count": 1
      },
      {
        "Low": 70,
        "Count": 2
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 15
      }
    ],
    "1489091400": [
      {
        "Low": 0,
        "Count": 284
      },
      {
        "Low": 10,
        "Count": 190
      },
      {
        "Low": 20,
        "Count": 52
      },
      {
        "Low": 30,
        "Count": 8
      },
      {
        "Low": 40,
        "Count": 4
      },
      {
        "Low": 50,
        "Count": 6
      },
      {
        "Low": 60,
        "Count": 1
      },
      {
        "Low": 70,
        "Count": 2
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 9
      }
    ],
    "1489091460": [
      {
        "Low": 0,
        "Count": 254
      },
      {
        "Low": 10,
        "Count": 172
      },
      {
        "Low": 20,
        "Count": 57
      },
      {
        "Low": 30,
        "Count": 5
      },
      {
        "Low": 40,
        "Count": 5
      },
      {
        "Low": 50,
        "Count": 3
      },
      {
        "Low": 60,
        "Count": 3
      },
      {
        "Low": 70,
        "Count": 4
      },
      {
        "Low": 80,
        "Count": 2
      },
      {
        "Low": 90,
        "Count": 12
      }
    ],
    "1489091520": [
      {
        "Low": 0,
        "Count": 186
      },
      {
        "Low": 10,
        "Count": 118
      },
      {
        "Low": 20,
        "Count": 27
      },
      {
        "Low": 30,
        "Count": 4
      },
      {
        "Low": 40,
        "Count": 2
      },
      {
        "Low": 50,
        "Count": 1
      },
      {
        "Low": 60,
        "Count": 0
      },
      {
        "Low": 70,
        "Count": 2
      },
      {
        "Low": 80,
        "Count": 2
      },
      {
        "Low": 90,
        "Count": 7
      }
    ],
    "1489091580": [
      {
        "Low": 0,
        "Count": 215
      },
      {
        "Low": 10,
        "Count": 147
      },
      {
        "Low": 20,
        "Count": 22
      },
      {
        "Low": 30,
        "Count": 7
      },
      {
        "Low": 40,
        "Count": 7
      },
      {
        "Low": 50,
        "Count": 11
      },
      {
        "Low": 60,
        "Count": 2
      },
      {
        "Low": 70,
        "Count": 1
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 15
      }
    ],
    "1489091640": [
      {
        "Low": 0,
        "Count": 230
      },
      {
        "Low": 10,
        "Count": 152
      },
      {
        "Low": 20,
        "Count": 25
      },
      {
        "Low": 30,
        "Count": 13
      },
      {
        "Low": 40,
        "Count": 5
      },
      {
        "Low": 50,
        "Count": 1
      },
      {
        "Low": 60,
        "Count": 2
      },
      {
        "Low": 70,
        "Count": 5
      },
      {
        "Low": 80,
        "Count": 0
      },
      {
        "Low": 90,
        "Count": 9
      }
    ]
  },
  "Interval": 10,
  "Start": 0,
  "BucketCount": 10
}
```

**Comment by sesse** [comment]
Seemingly Grafana supports this if you have an Elasticsearch backend and choose “Time series bucket”. But for e.g. Prometheus, there's nothing, and no known workaround.

**Comment by torkelo** [comment]
Prometheus does not support histograms in the same way as elasticsearch

**Comment by sesse** [comment]
This is true; it just explodes them into time series with an le="" label.

**Comment by RichiH** [comment]
Arguably, Prometheus should be disabled as a datasource for histograms unless it's going to be fixed in the near future. https://github.com/mtanda/grafana-histogram-panel/issues/58 does not sound as if a fix is incoming, either.

**Comment by GedPL** [comment]
Any updates ? 
I'm interested to have this for Elaticsearch to visualize for example:
SystemCode (string) on X-axis and count of WARNING/SUCCESS/ERROR for each SystemCode as a stacked bar for Y-axis.
![image](https://user-images.githubusercontent.com/31762538/35394506-3792adc8-01e8-11e8-9f55-ef9be114d871.png)

**Comment by GedPL** [comment]
Any chance to get it alive ?

**Comment by AndreasRosenberger** [comment]
Hi,

a nontime based bar graph would be the top of the mountain :)

**Comment by NitanshuSaini** [comment]
> Any chance to get this one working ?
HI 

Did you resolve this issue as i also have the same requirement.

**Comment by jjose122** [comment]
Are there any plans to have non time series charts in Grafana?

**Comment by torkelo** [comment]
yes!

**Comment by Gisborn** [comment]
> yes!

Could you specify terms for this feature request, please?

**Comment by dzhydyk** [comment]
Is there a chance that this will be implemented?

**Comment by leeoniya** [comment]
i think we have mostly everything covered for this in the Histogram and BarChart panels. let's open new issues for anything that's still missing.

**Comment by yossarian123** [comment]
Is this doable in Histogram or bar charts? Any link to instructions on how to build this kind of panel would be super useful.

**Comment by Huangvivi** [comment]
any upadte?

**Comment by siljuovix** [comment]
@Huangvivi I was also struggling with producing a stacked bar chart for categorical data. I am using Grafana >9 and according to the [documentation](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-chart/), the output of the query should be only one dataframe. I believe this means that you will have to produce a cross table and one way I found to achieve that is to use the **Grouping to Matrix** transform. Once you have a compact table and the stacked option selected it should produce the right plot.

**Comment by qbmiller** [comment]
I use mysql as datasource. Can plot non time series chart .
just set the x Axis as the field u want. 

But I can't plot multi chart without time-series, use Partition by values
