### ISSUE TITLE
Alerting: Edit alert rule page rendering issues in Safari

### ISSUE THREAD

**Issue by NikolayTsvetkov** [grafana/grafana#77982]
### What happened?

Some page elements start disappearing/appearing when scrolling or moving the mouse around when using Safari v17.1.

### What did you expect to happen?

Just having all the elements rendered properly so that one can configure the alert :)

### Did this work before?

This is working in Chrome, Firefox and previous Safari versions (v16).

### How do we reproduce it?

1. Use Safari 17.1
2. Open Edit rule page using the Unified Alerting framework. 
3. Start moving the mouse or scrolling up/down.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: v10.1.5
OS: macOS Sonoma 14.1.1
Browser: Safari 17.1

### Grafana platform?

A downloaded binary

<img width="1336" alt="Screenshot 2023-11-10 at 11 25 10" src="https://github.com/grafana/grafana/assets/24571856/8de3e430-4fbb-4e4d-ba0f-fb72bd55f7f8">
<img width="717" alt="Screenshot 2023-11-10 at 11 24 12" src="https://github.com/grafana/grafana/assets/24571856/5248b1ce-bacb-4d67-93d2-d9b520dd9610">

**Comment by armandgrillet** [comment]
We were unable to reproduce this with that version of Safari on Grafana 10.3. Please upgrade to the latest Grafana 10.X minor and reopen this issue if that keeps on happening.
