### ISSUE TITLE
Introduce overview panels

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#78]
Today I came across Marvel (http://www.elasticsearch.org/guide/en/marvel/current/index.html) - an awesome elasticsearch dashboard based on (guess what) Kibana. I really like the overview panels:
![overview_thumb](https://f.cloud.github.com/assets/2163464/2120287/4beb7992-91aa-11e3-8ddd-28df4c8e940f.png)

**Comment by jtyr** [comment]
Cubism-kind of graphs would be great for more dense dashboards.

**Comment by bergquist** [comment]
Closing this since both single stat and table panel have been added.
