### ISSUE TITLE
Plugin Catalog: "Enable" button not visible after install an app plugin

### ISSUE THREAD

**Issue by academo** [grafana/grafana#78003]
### What happened?

After an app plugin is installed the "Enable" button is only visible after a hard refresh 
![image](https://github.com/grafana/grafana/assets/227916/1613661e-8b35-441e-9725-158993d7e933)

Upon installation only the "Uninstall" button is visible. 

### What did you expect to happen?

The "Enable" button should be visible after installing the plugin 

### Did this work before?

Yes

### How do we reproduce it?

1. Install any app plugin via the plugin's catalog
2. Observe there's no "Enable" button, only "uninstall"
3. Refresh the browser page
4. Observe now the "Enable" button is availablle. 

### Environment (with versions)?

Grafana v10.3.0-pre (7d2d5fbe89)

OS:
Browser:

### Grafana platform?

None

**Comment by sympatheticmoose** [comment]
@academo just checking - your screenshot implies that the app can't be managed by the catalog so the reproduction steps don't align or this is an additional error?

**Comment by academo** [comment]
@sympatheticmoose I just happened to take the screenshot in a local developed app plugin. It is exactly the same scenario for any app plugin.
