### ISSUE TITLE
Grafana produce too many info logs when querying loki

### ISSUE THREAD

**Issue by Nemric** [grafana/grafana#78017]
### What happened?

I have a dashboard in kiosk mode, with a refresh interval, that query loki with a filter like `(?i)error|warning`
since a newer version, I can see a lot of logs like : 
`logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=y4yykKPMk uname=nemric fromAlert=false t=2023-11-10T21:52:51.79041792Z level=info msg="Response received from loki" duration=226.626941ms stage=databaseRequest statusCode=200 contentLength= start=2023-11-10T20:52:50.097Z end=2023-11-10T21:52:50.097Z step=2s query="{job=\"systemd-journal\"} |~ `(?i)error|warning`" queryType=range direction=backward maxLines=1000 supportingQueryType=none lokiHost=loki:3100 lokiPath=/loki/api/v1/query_range status=ok`

these logs are generated for each query and are "auto flooding" themselves :D 

I thing that this log should be "downgraded" to debug 

### What did you expect to happen?

Nothing more than just querying loki and showing results, without logging to loki that a "Response received from loki"

### Did this work before?

Yes, this behaviour is not so old

### How do we reproduce it?

1. open grafana and go to "explore"
2. query a loki database with filter on grafana unit (depending your promtail config, here it's journald)
3. observe log flooding while running query again and again

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.0
OS: Fedora CoreOS
Browser: firefox nightly

### Grafana platform?

Docker

### Datasource(s)?

loki

**Comment by svennergr** [comment]
Hi @Nemric,

thanks for opening this issue. We will think about moving that log to a different level.

From what I understood you are trying to "observe" your own Grafana instance for `warning` and `error` logs, right? Do you think it would also be a viable way to change the query you are running to not use a line filter, but filter for the `level` label being `error` or `warning`?

**Comment by Nemric** [comment]
Hi,
Thanks for your answer and taking care about it :)
I'm not only observe grafana but all "systemd-journal" logs and not all service use level= or use correct logfmt
I'm used to have some false positive like "no error" :D
The best option be to use grafana's parser, the one that give some sugar (colors) on log lines in "Logs visualization" ;)

**Comment by svennergr** [comment]
Hi @Nemric,

we decided to leave the loglevels like this for now and thus will close this issue.

I think there are some ways you can use to tweak your query to make sure, logs of those kind are not shown, by e.g. a `!= "level=info"` filter to not show logs that have the `info` level set.

Thank you for your understanding!
