### ISSUE TITLE
Alerting: Unable to import Notification policies from json file.

### ISSUE THREAD

**Issue by rvillablanca** [grafana/grafana#78020]
### What happened?

If you export the default notification policy in json format and then try to provision it, it fails to do so with the error 

```
root route must specify a default receiver
```

However, the exported file contains the receiver

```json
{
    "apiVersion": 1,
    "policies": [
        {
            "orgId": 1,
            "Policy": {
                "receiver": "grafana-default-email",
                "group_by": [
                    "grafana_folder",
                    "alertname"
                ]
            }
        }
    ]
}
```

### What did you expect to happen?

The default notification policy is provisioned correctly.

### Did this work before?

I don't know

### How do we reproduce it?

1. Use a brand new instance of Grafana
2. Go to Alerting -> Notification Policies -> Default Policy -> Export
3. Select the JSON format and copy the content
4. Create a new file in the default provision folder for alerting (`./conf/provisioning/alerting/`)
5. Run grafana

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Latest version and main branch
OS: Linux
Browser: Google Chrome

### Grafana platform?

Other

**Comment by tonypowa** [comment]
Thank you  @rvillablanca for your creating this issue, and for contributing with a PR
I will add this issue into the squad's board for review
