### ISSUE TITLE
[Question/Issue] What is the error 500 when we want to add a Prometheus database 

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7802]
Please include this information:
- What Grafana version are you using? 4.1.2
- What datasource are you using? Prometheus
- What OS are you running grafana on? macOS Sierra
- What did you do? I added datasource (7ds) with the API and sometimes some of them aren't added and I have this error message:

```
{ [Error: failed [500] {"message":"Failed to add datasource"}]
  response:
   { statusCode: 500,
     content: '{"message":"Failed to add datasource"}',
     headers:
      { 'content-type': 'application/json; charset=UTF-8',
        date: 'Fri, 10 Mar 2017 10:12:41 GMT',
        'content-length': '38',
        connection: 'close' },
     data: { message: 'Failed to add datasource' } } }
```

the thing is that I can't find what is the error code `500` and what can make it happens.

thank you for your help

**Comment by torkelo** [comment]
must be some invalid data being posted. What does the grafana.log say?

**Comment by torkelo** [comment]
if you installed with homebrew the logs are in `#{HOMEBREW_PREFIX}/var/log/grafana`

**Comment by JeromeVi** [comment]
@torkelo  I use a Docker container so I don't have this file

**Comment by torkelo** [comment]
check the docker container logs int that case

**Comment by JeromeVi** [comment]
@torkelo  I have founded, sometimes the code wasn't finish when it was sended. Thank you for your help
