### ISSUE TITLE
The plugin page has been stuck on "Loading results," preventing me from enabling Zabbix. Can someone tell me what to do?

### ISSUE THREAD

**Issue by zasufe** [grafana/grafana#78039]
The plugin page has been stuck on "Loading results," preventing me from enabling Zabbix. Can someone tell me what to do?

My Grafana server is in an offline, non-networked environment, and I've already installed the plugins offline. However, I'm unable to enable them.
![image](https://github.com/grafana/grafana-zabbix/assets/49631859/a6675522-fab4-4df0-a0cb-46256afa7fe9)

**Comment by zoltanbedi** [comment]
I've transfered the issue from zabbix as it is more a question/feature request in grafana.

**Comment by gabor** [comment]
@grafana/plugins-platform-frontend , could you take a look please? thanks!

**Comment by mckn** [comment]
This should be fixed by the following PR https://github.com/grafana/grafana/pull/77978

**Comment by zoltanbedi** [comment]
Awesome! @mckn 🎉

**Comment by zoltanbedi** [comment]
We can close this as a duplicate of https://github.com/grafana/grafana/issues/77905
