### ISSUE TITLE
Task: remove publicDashboard FF disclaimer in dashboard insights documentation

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#78049]
There's a disclaimer in https://grafana.com/docs/grafana/latest/dashboards/assess-dashboard-usage/ about `publicDashboard` FF. 
Since we're already in GA, we should remove it and add public dashboard tab as part of the insight description as it is with the rest of the features.

**Comment by AgnesToulet** [comment]
@juanicabanas @natellium @thanos-karachalios I started to work on this and I think we should replace it with a configuration field to allow users to disable the feature. As this has security implications, I wonder if we should do this in a two-step process:
1. Add configuration field, keep the feature toggle but add deprecation warnings if this is used to disable the feature to tell users to use the configuration field instead.
2. Entirely remove the feature toggle. 

WDYT?

This is a bit more work and this won't impact a lot of customers. Currently, there are 68 instances with the feature disabled on Cloud VS 1515 enabled: https://ops.grafana-ops.net/d/afqrz7j7z/public-dashboards?orgId=1

**Comment by AgnesToulet** [comment]
This was updated in https://github.com/grafana/grafana/pull/78894
