### ISSUE TITLE
Prometheus: label_values returns to many results

### ISSUE THREAD

**Issue by Jakob3xD** [grafana/grafana#78043]
### What happened?

I have a variable containing different clusters and only one can be selected:
![image](https://github.com/grafana/grafana/assets/29206900/aba1b3a7-db57-4a0b-af58-a0b274937d2f)

I want to get the region of the selected cluster:
![image](https://github.com/grafana/grafana/assets/29206900/6437d8e1-efdc-4c3d-a606-a1422f00cdf8)

The request filters are correctly set in the request:
![image](https://github.com/grafana/grafana/assets/29206900/8e229317-2182-42fc-b880-87a9a4241853)

But the API returns the region of all clusters instead of only the selected one.
![image](https://github.com/grafana/grafana/assets/29206900/ca5f74ad-8dc9-4db0-b467-3efeea82999f)

### What did you expect to happen?

I expected to only get the region of the cluster that I selected.

### Did this work before?

Yes, it works with Grafana 9.2.3.

### How do we reproduce it?

See at "What happend?"

1. You need a metric that has two different labels with different values
2. Create a variable of type Label Values and query the first label
3. Select a var in the UI / Dashboard
4. Create a variable of type Label Values referencing the var created from step 2 in the label filters
5. You will get the label values from all metrics that are present in the variable created in step 2 and no the selected one.

### Environment (with versions)?

Grafana: 9.3 and above
OS: Ubuntu 22.04
Browser: Firefox

### Grafana platform?

Kubernetes

**Comment by kylebrandt** [comment]
1. Can you let us know the version and type (e.g. native prom, mimir, of thanos)?
2. Can you let us know the prometheus version setting in the data source settings?

**Comment by gtk-grafana** [comment]
Example for 2:
<img width="619" alt="image" src="https://github.com/grafana/grafana/assets/109082771/e2d973d5-dd8a-42bf-a077-5a3cc7eb96c6">

**Comment by Jakob3xD** [comment]
> Can you let us know the version and type (e.g. native prom, mimir, of thanos)?

Thanos: v0.32.5 Prometheus: v2.47.2


> Can you let us know the prometheus version setting in the data source settings?

Prometheus type is set to `Thanos` with version  `> 0.31.x`

**Comment by itsmylife** [comment]
Might be related: 
- https://github.com/thanos-io/thanos/pull/6816
- https://github.com/grafana/grafana/pull/68801#issuecomment-1768236536

**Comment by bohandley** [comment]
Because the request is being sent correctly, this looks more like a bug with Thanos. I would copy the request as curl in the browser and see what Thanos returns directly. This more like Thanos not respecting the label matchers.

**Comment by Jakob3xD** [comment]
> Because the request is being sent correctly, this looks more like a bug with Thanos. I would copy the request as curl in the browser and see what Thanos returns directly. This more like Thanos not respecting the label matchers.

Yes, there is an closed issue with thanos. I added a comment to reopen. If they don't react I'll create a new issue. Thanks for your help. Closing it for now as it seems to be a Thanos issue.
