### ISSUE TITLE
Explore: Tables are missing vertical spacing

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#78059]
In Explore, each visualization is displayed with some gap (8px wit the current theme) set by a common flex container. 
The table Viz however - being wrapped in another element - does not respect this when rendering multiple tables:

![image](https://github.com/grafana/grafana/assets/1170767/ce465a31-1553-4d5a-8fdf-f59c44a89ce9)

**How to reproduce:**
create 2 queries using `testdata`, `CSV Content` scenario and make sure that each table has different columns, ie:

Query A
```
A,B
A,B
```

Query V
```
C,D
C,D
```

**Comment by aditipatelpro** [comment]
@Elfo404, I would like to contribute to this, can you please assign this issue to me?

**Comment by Elfo404** [comment]
@aditipatelpro absolutely! thanks for the interest!

if you need some pointers you can start by looking at the render method of `public/app/features/explore/Table/TableContainer.tsx`

if you need any help please feel free to reach out and i'll do my best to assist you

happy hacking!

**Comment by saifion33** [comment]
@Elfo404 Hi, is this issue is still open.

**Comment by Elfo404** [comment]
@saifion33 we are reviewing @aditipatelpro 's solution in https://github.com/grafana/grafana/pull/78149
