### ISSUE TITLE
[Feature request] Dynamically read thresholds from datasource

### ISSUE THREAD

**Issue by bechtoldt** [grafana/grafana#7808]
The feature showing annotations that are fetched from a datasource is awesome. It will be much easier to see connections of peaks in the graph and alerts of corresponding backend services.

It would be great to have this for thresholds, too. Users with r/o access which haven't configured the alerting thresholds in the underlaying monitoring system (based on Prometheus, Graphite, ES or others) and users without technical background will be able to understand the graphs faster.

**Comment by torkelo** [comment]
There are a couple of related issues already so closing this:

https://github.com/grafana/grafana/issues/159
https://github.com/grafana/grafana/issues/922

**Comment by RashmiSaravanan16** [comment]
Does dynamic threshold can be implemented to simpleJson data source .

**Comment by jengstro2** [comment]
+1 for dynamic threshold setting with datasource 'syntax' (pretty much same as you define variables with datasource)
