### ISSUE TITLE
Chore: Remove random walk data from all gdev dashboards

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#78080]
we use gdev dashboards for visual regression testing. this is a time-consuming process that requires patience and someone who knows where and what to look for. even then, subtle changes can go unnoticed due to the dynamic nature of the data.

to have any hope of automating this (e.g. via screenshot testing), we need to remove random data from all panels in exchange for determinism.

**Comment by oscarkilhed** [comment]
Don't know if this is in scope, but would be nice for development as well, if these data sets would be part of the test data source.
