### ISSUE TITLE
Loki: query were not triaged  in the dashboard  after enabled lokiQuerySplitting for target with `"maxLines": 0`

### ISSUE THREAD

**Issue by liwanxue** [grafana/grafana#78096]
### What happened?

The dashboard is not loaded, and click on `Query` button, nothing happened.
The json for this panels as
`{
          "datasource": {
            "type": "loki",
            "uid": "cff9e619-5bd3-46f8-8863-56ed36c6bd10"
          },
          "editorMode": "code",
          "expr": "sum (quantile_over_time(0.50, {_namespace_=\"xxx\"}|logfmt|t_site_id=0|cmd_comm=\"a\"|dd_d_de=\"b\"|dd_bf_b=~\"Chrome.*|Safari|Firefox\"|unwrap jbyte[$__interval]))",
          "hide": false,
          "maxLines": 0,
          "queryType": "range",
          "refId": "A"
        },`
![image](https://github.com/grafana/grafana/assets/6746057/328d823a-6c01-47f2-957f-593b332f4488)

after removed `"maxLines": 0,` 
The dashboard could be loaded. 
![image](https://github.com/grafana/grafana/assets/6746057/31f6be47-fc12-441f-9ee8-2d8f9e2e771b)

### What did you expect to happen?

The dashboard could be loaded, and query can be executed when `"maxLines": 0` were set. 

### Did this work before?

Yes, disable lokiQuerySplitting, the query can be loaded. 

### How do we reproduce it?

1.  In Json Model, append `"maxLines": 0` for the queries. Save it. 
2. Check the dashboard, you can reproduce it. 

### Environment (with versions)?

Grafana: 10.1.5
OS: MacOS 13.5.1
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

Loki

**Comment by matyax** [comment]
@liwanxue I'm curious. Why were you using `maxLines: 0`?

**Comment by liwanxue** [comment]
> @liwanxue I'm curious. Why were you using `maxLines: 0`?

Maybe that's default behavior of some version grafana. It was created by someone else. We are facing this issue during enable lokisplit feature.

**Comment by matyax** [comment]
@liwanxue I see. `maxLines` is used for query splitting when querying logs, and it requires a value > 0 to properly work, so there's no workaround for that now.

In any case, I see that you're doing a metric query: `sum (quantile_over_time(0.50, {_namespace_=\"xxx\"}|logfmt|t_site_id=0|cmd_comm=\"a\"|dd_d_de=\"b\"|dd_bf_b=~\"Chrome.*|Safari|Firefox\"|unwrap jbyte[$__interval]))`. 

`maxLines` is a configuration that is only relevant for log queries. You can see that we hide the option when it's a metric query. My recommendation would be to make sure your panels have an empty or > 0 value for `maxLines`. Keep in mind that you will need to change the query from metric to logs to make the  input visible.

https://github.com/grafana/grafana/assets/1069378/b91726f2-8519-4873-a7e0-fb73ecc7fec6

I will keep this issue open, so we consider clearing out the value of `maxLines` when we hide the field.

**Comment by liwanxue** [comment]
Is grafana going to clear out value `maxLines` when user edit the query expr, do we need to clear up manually for existing dashboards? 
I am thinking, if the user already have this `maxLines` for metric, and when he open the dashboard, but he didn't edit the query expr, does `maxLines` will be removed?  If it's not, then the dashboard can not be loaded.

**Comment by matyax** [comment]
For now you would have to manually edit `maxLines` whenever it's set to 0. In the mean time, we will discuss how to best handle this configuration value when switching between different types of queries.
