### ISSUE TITLE
Explore: datasources in the URL out of sync

### ISSUE THREAD

**Issue by harisrozajac** [grafana/grafana#78115]
Reproduction steps. **You must follow these steps exactly by navigating initially with the link.** Navigating back and forth between loki and slow-prometheus does not consistently reproduce the issue. Navigating from the loki link to normal prometheus does not reproduce the issue.

1. Run devenv with normal loki and slow proxy prometheus. I used `make devenv sources=tempo,slow_proxy`
2. Go to this [link](http://localhost:3000/explore?panes=%7B%22yC0%22:%7B%22datasource%22:%22gdev-loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcompose_service%3D%5C%22db%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22gdev-loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1) 
3. Wait for the loki query to finish
4. Change the datasource to slow-prometheus
5. Slow prometheus' query editor will show with the loki options (IE with the label browser). The query header will also say "(gdev-loki)"

--- 

This occurs because the url sync logic fires multiple times in this scenario. The history after the above steps are taken looks like this 

1. Pane DS loki, query DS loki : `explore?panes={"lR_":{"datasource":"loki-ds","queries":[{"refId":"A","expr":"{app=\"aggregator\"} | logfmt","queryType":"range","datasource":{"type":"loki","uid":"loki-ds"},"editorMode":"code"}],"range":{"from":"now-6h","to":"now"}}}&schemaVersion=1&orgId=1`
2. Pane DS prom, query DS prom : `explore?panes={"lR_":{"datasource":"prom-ds","queries":[{"refId":"A","expr":"{app=\"aggregator\"}","range":true,"datasource":{"type":"prometheus","uid":"prom-ds"}}],"range":{"from":"now-6h","to":"now"}}}&schemaVersion=1&orgId=1`
3.  Pane DS prom, query DS loki : `explore?panes={"lR_":{"datasource":"prom-ds","queries":[{"refId":"A","expr":"{app=\"aggregator\"} | logfmt","queryType":"range","datasource":{"type":"loki","uid":"loki-ds"},"editorMode":"code"}],"range":{"from":"now-6h","to":"now"}}}&schemaVersion=1&orgId=1`

Under functional navigations, the previous params and current params are never mismatched, so the sync doesn't occur. With the above, the URL appears to be out of sync, so the sync logic fires and causes the issue.

**Comment by gelicia** [comment]
Bumping up the delay to 500ms seems to fix it but I would like to find another solution https://github.com/grafana/grafana/blob/main/public/app/features/explore/hooks/useStateSync/index.ts#L66

The action that causes the extra sync is for updating the range
