### ISSUE TITLE
Explore: (more views) - multi-panel validation and forming the problem

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#78113]
https://docs.google.com/document/d/1J4G6dX1P3zDs7eQFjl4Z9eLwRTs9S1C3E69IUdFNFyI/edit#heading=h.5sybau7waq2q

Explore is currently limited to a two-pane layout. 
Quite a few users have been expressing interest in seeing Explore lifting this limitation and allow multiple panes to be created in the same browser tab. This is especially useful when users have wider (or simply bigger) screen real estate.
Currently the accepted workaround is simply to open a new browser tab and have a different Explore instance running, but this comes with its own limitations.

Another notable feedback we received quite a few times is the ability to have a tabbed interface within Explore itself, which adds to the previous point. With a tabbed interface users would have much more flexibility in how they can organize the Explore view to better suit their needs.
Combined with the possibility of splitting each pane vertically this would result in complete flexibility. A common example brought up multiple times is a IDE-like interface, such a s vscode.

### Current features to keep
Syncing time between panes should still be possible and kept frictionless.
It is unclear if there is the need of only some panes/tabs to be synced in a view, the easiest solution would be to sync them all.

### Unknowns
- [ ] How would this work with the newly introduced correlations editor?
- [ ] How would this work with datalinks?
  - Currently opening a datalink opens or replace the "rightmost" pane in explore, options are:
    - Split the current pane/tab group
    - create a new tab in the current pane and switch to it

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
