### ISSUE TITLE
Alerting: [plugin.downstreamError] failed to query data

### ISSUE THREAD

**Issue by ivantr5** [grafana/grafana#78122]
### What happened?

After the upgrade to Grafana v10.0.3 we periodically get issues with alerting.
Mostly they are of following types:

```
[plugin.downstreamError] failed to query data: invalid character '<' 

[plugin.downstreamError] failed to query data: Post \"https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256\": EOF" 

[plugin.downstreamError] failed to query data: Post \"https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256\": context deadline exceeded" 

[plugin.downstreamError] failed to query data: Post \"https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" duration=30.001080015s
```

For example:

```
logger=ngalert.scheduler rule_uid=e54efe71-c316-48ef-a53a-6656eff26854 org_id=1 version=24 fingerprint=c7da47139ef661da attempt=0 now=2023-11-08T13:30:00+01:00 rule_uid=e54efe71-c316-48ef-a53a-6656eff26854 org_id=1 t=2023-11-08T13:30:27.215031223+01:00 level=**error msg="Failed to evaluate rule" error="[plugin.downstreamError] failed to query data: invalid character '<' looking for beginning of value**" duration=22.89593443s

logger=ngalert.scheduler rule_uid=d0a55f5e-f9e8-4e01-8978-4a94ad211621 org_id=1 version=24 fingerprint=ae3103f6f6d23e2c attempt=0 now=2023-11-08T12:53:00+01:00 rule_uid=d0a55f5e-f9e8-4e01-8978-4a94ad211621 org_id=1 t=2023-11-08T12:53:00.835045709+01:00 level=error msg="Failed to evaluate rule" **error="[plugin.downstreamError] failed to query data: Post \"https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256\": EOF"** duration=1.014832ms
```

Apparently the problem appeared after the migration , and there were no infrastructure changes, neither changes on ElasticSearch datasource side that could be causing these issues.

Here is an example of alert configuration:
![image](https://github.com/grafana/grafana/assets/85614462/58f01ac7-f42c-47fc-9b60-02d83ce11bec)

Please assist in finding the reason.

### What did you expect to happen?

Alerts to work as before the migration to Grafana v.10.0.3

### Did this work before?

Yes, with Grafana v.8/9

### How do we reproduce it?

Provided details in ticket description

### Environment (with versions)?

Grafana: v.10.0.3
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

ElasticSearch

**Comment by usmangt** [comment]
Hi @ivantr5,

Thanks for opening this issue.

Can you please tell if you created these alert rules in more earlier versions of Grafana i.e. in version 8 or 9 and then used the same rules also in version 10?

**Comment by ivantr5** [comment]
Yes, the same rules were used in v.8 and 9. At the moment we are trying to resolve some of them my increasing the timeout value on the datasource.

**Comment by ivantr5** [comment]
Maybe you can check the invalid character issue, for the rest we will see if the timeout change will resolve them completely

**Comment by ivantr5** [comment]
In addition, we are not sure why the call to Elasticsearh goes with max_concurrent_shard_requests=256, while this setting is by default 5, for example:   https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256

**Comment by KaplanSarah** [comment]
Please provide debug logs.  Can you also tell us how many alert rules and how often they are evaluated for this elasticsearch cluster?

**Comment by ivantr5** [comment]
[grafana_2023-11-13.txt](https://github.com/grafana/grafana/files/13559765/grafana_2023-11-13.txt)
I added logs. I do not have clear picture how many alert rules are active on this data source, most of them evaluate on 3 mins.

Kind regards,
Ivan

**Comment by ivantr5** [comment]
By increasing the timeout setting on the data source, we succeeded to get rid of the timeout errors.
At the moment we still experience following 2 errors (if you could pls focus on those ones):

logger=ngalert.scheduler rule_uid=f239947e-2018-4f96-9fd4-5affb404fe74 org_id=1 version=2 fingerprint=857a1fabf020c4e1 attempt=0 now=2023-11-13T02:15:00+01:00 rule_uid=f239947e-2018-4f96-9fd4-5affb404fe74 org_id=1 t=2023-11-13T02:15:29.127190854+01:00 level=error msg="Failed to evaluate rule" error=**"[plugin.downstreamError] failed to query data: invalid character '<' looking for beginning of value**" duration=22.959730567s

logger=ngalert.scheduler rule_uid=c280bd7b-624e-4b0e-8352-3836c60c5989 org_id=1 version=1 fingerprint=26eab52141559c9d attempt=0 now=2023-11-13T02:15:00+01:00 rule_uid=c280bd7b-624e-4b0e-8352-3836c60c5989 org_id=1 t=2023-11-13T02:15:19.929047087+01:00 level=error msg="**Failed to evaluate rule" error="[plugin.downstreamError] failed to query data:** Post \"https://kibana-nonprod.common-blue.apfr-acm-common.ec1.aws.az.cloud.a/_msearch?max_concurrent_shard_requests=256\": net/http: **TLS handshake timeout"**

**Comment by ivantr5** [comment]
It is also worthwile to mention that these issues are not happening all the time, but only from time to time.

**Comment by svennergr** [comment]
Hi @ivantr5,
with Grafana 10.2 we heavily improved debug logs within the Elasticsearch data source, which might help here. Is there a possibility to upgrade Grafana to the latest 10.2.x version and send us those debug logs containing the `logger=tsdb.elasticsearch` label?

**Comment by rajeshwar-nu** [comment]
I am observing the same problem, with Elasticsearch Datasource/Connection timeout set to 600. The error occurs within a few seconds of executing a query, so it seems that timeout was never breached before the error popped up

**Comment by ivantr5** [comment]
Hi @svennergr - We installed Grafana 10.2, but there was no much additional info in the debug logs:

logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=bbec1b07-7507-4b59-92cb-1adb50b66c9c org_id=1 fromAlert=true t=2023-12-26T14:33:00.787651633+01:00 level=info msg="Prepared request" queriesLength=1 duration=61.399µs stage=prepareRequest

logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=bbec1b07-7507-4b59-92cb-1adb50b66c9c org_id=1 fromAlert=true entity=client t=2023-12-26T14:33:00.788442938+01:00 level=error msg="Error received from Elasticsearch" error="Post \"[https://kibana-nonprod.common-blue.apfr-acm-common.ec1.aws.cloud/_msearch?max_concurrent_shard_requests=5\":](https://kibana-nonprod.common-blue.apfr-acm-common.ec1.aws.cloud/_msearch?max_concurrent_shard_requests=5\%22:) EOF" status=error duration=725.722µs stage=databaseRequest
logger=ngalert.sender.router rule_uid=bbec1b07-7507-4b59-92cb-1adb50b66c9c org_id=1 t=2023-12-26T14:33:00.789218019+01:00 level=info msg="Sending alerts to local notifier" count=1

**Comment by ivantr5** [comment]
Here are some more debug logs:
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true entity=client t=2024-01-02T14:44:04.699208739+01:00 level=debug msg="Creating new client" configuredFields="es.ConfiguredFields{TimeField:\"@timestamp\", LogMessageField:\"\", LogLevelField:\"\"}" indices=logs-*-azpdd-* interval= index=logs-*-azpdd-*
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true t=2024-01-02T14:44:04.699261825+01:00 level=debug msg="Parsing queries" queriesLength=1
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true t=2024-01-02T14:44:04.69936216+01:00 level=info msg="Prepared request" queriesLength=1 duration=98.293µs stage=prepareRequest
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true entity=client t=2024-01-02T14:44:04.699516604+01:00 level=debug msg="Completed encoding of batch requests to json" duration=117.026µs
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true entity=client t=2024-01-02T14:44:04.699542889+01:00 level=debug msg="Sending request to Elasticsearch" url=https://kibana-nonprod.common-blue.apfr-acm-common.ec1.aws.cloud
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true entity=client t=2024-01-02T14:44:04.761010201+01:00 level=info msg="Response received from Elasticsearch" status=ok statusCode=200 contentLength=-1 duration=61.607677ms stage=databaseRequest
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true entity=client t=2024-01-02T14:44:04.76116618+01:00 level=debug msg="Completed decoding of response from Elasticsearch" duration=95.352µs
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true t=2024-01-02T14:44:04.761205859+01:00 level=debug msg="Processed metric query response"
logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName="Elasticsearch AZPDD" dsUID=EAimtTs7k uname=grafana_scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 fromAlert=true t=2024-01-02T14:44:04.761246178+01:00 level=info msg="Finished processing of response" duration=43.513µs stage=parseResponse
logger=expr rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 datasourceType=elasticsearch queryRefId=A datasourceUid=EAimtTs7k datasourceVersion=3 t=2024-01-02T14:44:04.761289339+01:00 level=debug msg="Data source queried" responseType=no-data
logger=ngalert.scheduler rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 version=1 fingerprint=24586316479a7171 attempt=0 now=2024-01-02T14:44:00+01:00 rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.761354953+01:00 level=debug msg="Alert rule evaluated" results="[{Instance:datasource_uid=EAimtTs7k, ref_id=A State:NoData Error:<nil> Results:map[] Values:map[] EvaluatedAt:2024-01-02 14:44:00 +0100 CET EvaluationDuration:4.761350186s EvaluationString:}]" duration=62.523932ms
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.761416467+01:00 level=debug msg="State manager processing evaluation results" resultCount=1
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 instance="datasource_uid=EAimtTs7k, ref_id=A" t=2024-01-02T14:44:04.76146019+01:00 level=debug msg="Setting next state" handler=resultNoData
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 instance="datasource_uid=EAimtTs7k, ref_id=A" t=2024-01-02T14:44:04.761482328+01:00 level=debug msg="Execution no data state is Normal" handler=resultNormal previous_handler=resultNoData
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 instance="datasource_uid=EAimtTs7k, ref_id=A" t=2024-01-02T14:44:04.761512149+01:00 level=debug msg="Keeping state" state=Normal
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.761538552+01:00 level=info msg=**"Detected stale state entry"** cacheID="[[\"__alert_rule_namespace_uid__\",\"yijei6E4k\"],[\"__alert_rule_uid__\",\"a19a03e7-03a7-4287-bcbc-d837f094b669\"],[\"__contacts__\",\"azpdd-test\"],[\"alertname\",\"All errors with alert [azpdd-uat2]  in azpdd-allyz-s3-file-manager-provider\"],[\"grafana_folder\",\"AzPDD_DF\"]]" state=Alerting reason=Error
logger=ngalert.image rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 dashboard=iy5BjnzSk panel=19 t=2024-01-02T14:44:04.761565266+01:00 level=debug msg="Requesting screenshot"
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.761591596+01:00 level=debug msg="Deleting alert states" count=1
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.762013597+01:00 level=debug msg="Saving alert states" count=1 max_state_save_concurrency=1
logger=ngalert.state.manager rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.762538552+01:00 level=debug msg="Saving alert states done" count=1 max_state_save_concurrency=1 duration=524.083µs
logger=ngalert.state.historian backend=annotations rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.762579935+01:00 level=debug msg="Alert state changed creating annotation" newState="Normal (MissingSeries)" oldState="Alerting (Error)"
logger=ngalert.sender.router rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.762640913+01:00 level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.state.historian backend=annotations rule_uid=a19a03e7-03a7-4287-bcbc-d837f094b669 org_id=1 t=2024-01-02T14:44:04.765009332+01:00 level=debug msg="Done saving alert annotation batch"

**Comment by armandgrillet** [comment]
We think your datasource query is returning HTML because the error message states that the data starts with `<` which is HTML. Can you verify manually, for example using curl, that you are getting back what you are expecting? Is there a proxy/load balancer between Grafana and the datasource that could be returning these messages?

**Comment by svennergr** [comment]
I'll close the issue for now, but please don't hesitate to push back when you still think there's an issue in Grafana. Thanks!
