### ISSUE TITLE
[Feature request] draw trend line

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7812]
It would be nice if Grafana support drawing trend line.
https://www.datadoghq.com/blog/visualizing-trends-regression-lines/

I think such feature should be provided by visualization tool, not TSDB.
If Grafana provide the feature, all users can use it with all datasources.

**Comment by deepakgup** [comment]
I agree. I am working on Grafana for IT Operations use case and we have a need to add trend lines. While I think we can achieve this using formulas in source DB however it might be convenient in my opinion to allow the user to add trend lines on the fly from Grafana UI without bothering about source DB formulas.

**Comment by restistor3672** [comment]
I'd think a panel would be needed. After all, a trend (like least squares regression lines) is most interesting if you project it into the future. The data that creates the line gives you a formula (y = mx +b), that you can then use to draw a line through the points. 
Projecting that line out ahead of the data will give you a lot more visual information about the trend you are looking at, and what it might mean for you down the road. That will help with capacity planning, failure prediction, etc. I think that's the kind of thing a special panel could be used for.

**Comment by deepakgup** [comment]
I agree – we need to have this capability embedded into existing line chart panel or a new line chart panel.

The use cases for me is exactly what you stated – capacity and utilization trending.

 

It will be really nice if we could get this capability delivered for the MySQL Data source adapter.

**Comment by torkelo** [comment]
this is best handled by the time series database query language and processing/transformation layer. And if implemented in Grafana via the meta queries feature https://github.com/grafana/grafana/issues/3677

**Comment by deepakgup** [comment]
Thanks for taking up the feature request.

 

Cheers!

Deepak

**Comment by deepakgup** [comment]
Looks like I will need to upgrade MySQL to version 8.X. Let me upgrade and give it a shot.

**Comment by cinek810** [comment]
are there any updates on it? I'll be especially interested in trend line projection to the future.

**Comment by timdonovanuk** [comment]
A graph tool without trend lines?

**Comment by torkelo** [comment]
Most of the popular time series database that Grafana supports has that built into their query function library

**Comment by cprivite** [comment]
> Most of the popular time series database that Grafana supports has that built into their query function library

My database is graphite and I don't have a data scientist around to rearchitect the collection. I'm an IT guy using data collected by a vendor provided plugin.  So here's another vote for Graphana to do this natively. Hell it could be display level only and in the client javascript. I just need a line to exist long enough to get a screenshot to show to the boss.

**Comment by lihan** [comment]
@torkelo @cprivite Most prediction function from time series database is very limited, it only works if your metrics have clear trends. I am looking for ways to pull data out from Grafana and hook it to my own prediction server and push it back into a new data source. Both original data and prediction data should be able to display side by side. 

Happy to push this back to community if someone can help resolve below API issue.

https://github.com/grafana/grafana/issues/17834

**Comment by ganadara135** [comment]
In my case, I draw the trend line as the difference of time interval on the same raw data.
ex) X data time interval 1 minute, 1 hour.
<img width="717" alt="스크린샷 2020-04-23 15 40 44" src="https://user-images.githubusercontent.com/24896007/80067778-76ddb600-8579-11ea-9a6b-6542cb0fd66c.png">

**Comment by Neurozone** [comment]
what is the state of the feature implementation ?

**Comment by ganadara135** [comment]
That is same raw data as you see on the capture image

**Comment by R-Studio** [comment]
@torkelo is something like this feature request on the Grafana roadmap? This would be very useful!

**Comment by akovov** [comment]
any news from Grafana team?

**Comment by abctaylor** [comment]
Would also love to see this become a thing. There is no native way in prom to add a trend line or SMA/EMA line to a chart. It would be awesome if this could be a component of the time series panel itself for various moving averages/regressions.

**Comment by hoppedmalt** [comment]
I've been going through the solutions, and there seem to be only complicated and burdensome solutions for this. I would love to see implementation for this in Grafana.
