### ISSUE TITLE
[Feature request] Display of syslog and database text messages

### ISSUE THREAD

**Issue by trlafleur** [grafana/grafana#7813]
In displaying system status, its desirable to also have the ability of displaying time based text messages that may be in the database and to allow displaying of text message from syslog or other URL related messaging system.

this could be done in a re-sizeable scroll box with a time stamp that could be mixed in with the graphs.

    What Grafana version are you using? - 4.1.1
    What datasource are you using? - InfluxDB
    What OS are you running grafana on? - CentOS 7

thanks

**Comment by torkelo** [comment]
you can show text messages in singlestat and in table panel
