### ISSUE TITLE
[Bug] 2 open pages on Chrome with 2 different users

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#7814]
- What Grafana version are you using?
4.1.1
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
Ubuntu
- What did you do?
Open 2 grafana web page on Chrome in two different organizations and with a different user.
- What was the expected result?
It should work
- What happened instead?
There is a conflict when I switch from one page to the other and navigate in the page 

I think the reason is that it keeps the data for one session in the cache and then it bugs in the other...

When I go in the profile I get the user of the other page.
![grafana_profil](https://cloud.githubusercontent.com/assets/20662503/23847822/80c92efe-07d4-11e7-84b0-54d88e400280.png)

**Comment by torkelo** [comment]
Grafana does not support having multiple users logged in at the same time in the same browsers. You need to use incognito mode or use different browsers, otherwise the browser will share the session cookie between the two tabs
