### ISSUE TITLE
[NestedFolders]: Folders API (api/folders) is taking very long when nested folders are enabled

### ISSUE THREAD

**Issue by aishyandapalli** [grafana/grafana#78143]
### What happened?

[NestedFolders]: Folders API (api/folders) is taking very long when nested folders are enabled

It's taking around 1.7 min for the data to come back.

### What did you expect to happen?

It should come back in less than a minute

### Did this work before?

No

### How do we reproduce it?

1. Use Grafana 10.0.9 as base image
2. Enable NestedFolders
3. Go the dashboards tab on the left nav bar

### Environment (with versions)?

Grafana: 10.0.9
OS: linux
Browser: chrome

### Grafana platform?

None

**Comment by zserge** [comment]
Do you have an estimate on how many folders/dashboards/users do you have in your setup? It would be helpful to know how deeply they are nested (i.e. are they all "flat" on the topmost level? Do you have folders that are inside other root level folders now? What is the branching factor, i.e. each root folder has ~10 child folders or ~1K child folders?). Also there were some folder performance improvements in v10.1 and v10.2.

**Comment by papagian** [comment]
@aishyandapalli thank you for reporting this: does the request that takes too long returns any folders? asking because there used to be a bug [when the folder didn't have any subfolders](#78280)
in any case: could you share the request/response?
