### ISSUE TITLE
[Bug] Possible bug issue with label containing dots `.`

### ISSUE THREAD

**Issue by nemo83** [grafana/grafana#7815]
Please include this information:
- What Grafana version are you using?
Grafana v4.1.2 (commit: v4.1.2)

- What datasource are you using?
Prometheus 

- What OS are you running grafana on?
AWS (Centos?)
- What did you do?
I've defined a templating variable as follows:
`label_values(http_request_duration_seconds_sum{job="$job"}, path)`
and I've used this variable to generate repeated rows. 

The variable is used in 
`sum(rate(http_request_duration_seconds_count{job="$job",path="$Resource"}[1m]))`

- What was the expected result?
This has worked perfectly so far, but we've recently added a `.` (dot) in the name of a label and this prevented the metric above from being pulled correctly. If I hardcode the value in the `path` filed above, it works well, but the variable substitution doesn't seem to be working fine with the `=` sign.

*It does work if I use `=~` instead!!*

Is this the expected behavior?

Thanks!

**Comment by torkelo** [comment]
It depends. What are the variables options? If "All" or Multi Value is enabled on the variable it will be regex escaped so you must use =~ operator.

**Comment by nemo83** [comment]
Yeah I use both `All` and `Multi Value` so I guess this is working as expected.
