### ISSUE TITLE
Unexpected folder name change for standalone linux binary download

### ISSUE THREAD

**Issue by schu** [grafana/grafana#78151]
### What happened?

The name of the top folder for standalone linux binary downloads has changed from 10.2.0 to 10.2.1. Before it was `grafana-10.2.0`, now it's `grafana-v10.2.1` (leading `v` added). Not a problem per se, but an unexpected and potentially breaking change for automated deployments which expect the former naming scheme.

### What did you expect to happen?

Folder name is consistent with previous releases.

### Did this work before?

Folder name was consistent across releases before.

### How do we reproduce it?

```
cd /tmp/

curl -LO https://dl.grafana.com/oss/release/grafana-10.2.0.linux-amd64.tar.gz
curl -LO https://dl.grafana.com/oss/release/grafana-10.2.1.linux-amd64.tar.gz

tar tf grafana-10.2.0.linux-amd64.tar.gz | head
grafana-10.2.0/...

tar tf grafana-10.2.1.linux-amd64.tar.gz | head
grafana-v10.2.1/...
```

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

**Comment by usmangt** [comment]
Hi @schu,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.
