### ISSUE TITLE
Build: Grafana v10.2.1 Docker build fails

### ISSUE THREAD

**Issue by EpiJunkie** [grafana/grafana#78157]
### What happened?

`make build-docker-full` fails when attempting to build from the `v10.2.1` and `v10.2.2` tag.

```
$ git checkout v10.2.1
$ make build-docker-full
...
92.05 pkg/services/ngalert/models/testing.go:7:2: package slices is not in GOROOT (/usr/local/go/src/slices)
92.06 exit status 1
92.06 exit status 1
92.06 make: *** [Makefile:125: build-go] Error 1
------
Dockerfile:73
--------------------
  71 |     ENV BUILD_BRANCH=${BUILD_BRANCH}
  72 |
  73 | >>> RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}
  74 |
  75 |     FROM ${BASE_IMAGE} as tgz-builder
--------------------
ERROR: failed to solve: process "/bin/sh -c make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}" did not complete successfully: exit code: 2
make: *** [build-docker-full] Error 1
$
```

Looking into this issue, the 'slices' package is not included in the Go standard library until version Go 1.21rc1. It seems that 5d5f8dfc should have been included in the v10.2.x branch for the 10.2.1 release. The uses of 'slices' was introduced by 819a0c1c.

Resources:
* https://pkg.go.dev/slices@go1.21rc1?tab=versions
* https://github.com/grafana/grafana/compare/v10.2.0...v10.2.1

### What did you expect to happen?

A Docker image to be created and tagged.

### Did this work before?

This worked on version v10.2.0. Eg:
1. `git checkout v10.2.0`
2. `make build-docker-full`

### How do we reproduce it?
1. `git checkout v10.2.1`
2. `make build-docker-full`

or

1. `git checkout v10.2.2`
2. `make build-docker-full`

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.2.1
OS: OSX 14.1.1 (23B81)
Docker Desktop: 4.25.1
Browser: N/A

### Grafana platform?

Kubernetes

### Datasource(s)?

N/A

**Comment by nkukard** [comment]
Getting the same issue here

**Comment by nkukard** [comment]
> still not fixed in 10.2.2 ?

Doesn't look like it , just tried the build and it failed with the same message.

It looks like a newer version of Go is now required.

**Comment by usmangt** [comment]
Hi @EpiJunkie and others,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by abdulsathar-m** [comment]
Getting same issue in 10.2.2

**Comment by V-yw** [comment]
Getting same issue in 10.2.2

Step 52/77 : RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}
 ---> Running in 6033cb1c13cb
generate go files
/go/bin/wire-v0.5.0 gen -tags oss ./pkg/server
wire: github.com/grafana/grafana/pkg/server: wrote /tmp/grafana/pkg/server/wire_gen.go
build go files
go run build.go  -build-tags=oss build
Version: 10.2.2, Linux Version: 10.2.2, Package Iteration: 1701313515
building binaries build
building grafana ./pkg/cmd/grafana
rm -r ./bin/linux-amd64/grafana
rm -r ./bin/linux-amd64/grafana.md5
go build -ldflags -w -X main.version=10.2.2 -X main.commit=unknown-dev -X main.buildstamp=1701313515 -X main.buildBranch=main -tags oss -o ./bin/linux-amd64/grafana ./pkg/cmd/grafana
pkg/services/ngalert/models/testing.go:7:2: package slices is not in GOROOT (/usr/local/go/src/slices)
exit status 1
exit status 1
make: *** [Makefile:125: build-go] Error 1
The command '/bin/sh -c make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}' returned a non-zero code: 2

**Comment by alexandre1984rj** [comment]
Same issue here

**Comment by twei55** [comment]
The issue seems to be fixed in the [main branch](https://github.com/grafana/grafana/blob/main/Dockerfile#L6). Works fine for me 👍

**Comment by drTr0jan** [comment]
@twei55 `main` branch uses go121, but `v10.2.x` uses go120.

**Comment by V-yw** [comment]
@twei55 use main branch rebuild :
COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist

**Comment by drTr0jan** [comment]
Fixed at 10.2.3 after `v10.2.x` has used go121.

**Comment by aangelisc** [comment]
As @drTr0jan mentioned, this has been fixed in 10.2.3 as the Go version was upgraded to 1.21.3 (and then upgraded further to 1.21.5 in https://github.com/grafana/grafana/commit/70629d8865c29c69d8a56b3ba9868249377242dc. I'm going to close this issue but if there are further issues related to this please leave a comment or reopen 😊

**Comment by Drun1baby** [comment]
Same issue in V11.2.0

**Comment by ndoo** [comment]
Same error in HEAD if using docker [compose] build instead of using make build-docker-full.

> `ERROR [grafana go-builder 21/21] RUN make build-go GO_BUILD_TAGS=oss WIRE_TAGS=oss`

**Comment by tgirotto** [comment]
I did not have the "slices" problem, but that same line failed. The solution was simply to attempt a build on a much bigger machine.
