### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Shyam2534** [grafana/grafana#7816]
Hi,

I am sorry for the way I am framing the question. Please bear with me.
I am planning to embed grafana (whole software) as a part a webapp (own product) like the same way cloudify used in their monitoring process. In other words, I need it as a single process. I also need to create instance of a dashboard of a predefined dashboard in each deployment, make changes to each dashboard and save it separately. It will be very much helpful if I get some help here.

Grafana version - 4.0.1
Datasource - ElasticSearch 
OS - CentOs 7.1

**Comment by torkelo** [comment]
You can embedd Grafana using an iframe. 

Grafana-server (backend part) is a single process by itself, you cannot embed this part into another application. 

You can use the Grafana HTTP api to setup users & dashboards in an automated fashion.
