### ISSUE TITLE
Docs: Missing info in link to prometheus annotation querying

### ISSUE THREAD

**Issue by onefourfive** [grafana/grafana#78164]
### What happened?

In [docs/sources/datasources/prometheus/_index.md](https://github.com/grafana/grafana/blob/1a53a716e9473fc5ac91d3879bf389f6d3e62c41/docs/sources/datasources/prometheus/_index.md?plain=1#L31C288-L31C305), this reference to using Prometheus to annotate visualizations leads to a page that does not reference `annotations` at all: 

```markdown
...
use [Explore][explore], and [annotate visualizations]({{< relref "./query-editor#apply-annotations" >}}).
```

Refer to docsite: https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-data-source

### What did you expect to happen?

Expected link `annotate visualizations` to lead to page with information regarding annotating visualizations with Prometheus.

### Did this work before?

I was not able to find a major version where the linked page contained annotation information.

### How do we reproduce it?

1. Click link
2. Ctrl + F 'annotation'
4. Expect: hits
Actual result: no hits

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
closing since the fixed is merged 🚀
