### ISSUE TITLE
Auth/JWT: don't include `auth_token` in Share > Link > Copy for panel

### ISSUE THREAD

**Issue by ulken** [grafana/grafana#78189]
### What happened?

Sharing a permalink to a panel for a dashboard which uses [JWT authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#configure-jwt-authentication) includes `auth_token` in the copied URL.

As long as the token has not expired, anyone with the link can access the panel without having to provide any credentials of their own. Not only the panel, but the entire organization.

The `auth_token` is tied to a specific user, so it makes no sense to forward it to other users.

Even though there's responsibility to put on the end user here, being careful with who they share potentially sensitive data, I find it to be somewhat of a security issue since the UI enables/encourages spreading credentials into the wrong hands.

### What did you expect to happen?

I see no reason to include the `auth_token` query parameter in the copied URL. It should be removed from the text field all together.

### Did this work before?

I don't think this is a regression. I'm assuming it's been like this since the feature was introcuded.

### How do we reproduce it?

1. Enable [JWT authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#configure-jwt-authentication)
2. Load a dashboard using the `auth_token` query parameter
3. Click a panel title, select **Share** and click **Copy** under the _Link_ tab

### Is the bug inside a dashboard panel?

Yes, but I don't think there's any data to provide here?

### Environment (with versions)?

Grafana: 9.5.1
OS: macOS Ventura 13.6
Browser: Arc

### Grafana platform?

Docker

**Comment by ulken** [comment]
@usmangt care to help me address this? Could probably help out with a PR if approved.

**Comment by usmangt** [comment]
Hi @ulken,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by ulken** [comment]
@usmangt you rock 🤘

**Comment by Aurora178** [comment]
Hello, I would like to ask a question: Can I use auth_token as Headers when using auth_token to access grafana dashboards?
