### ISSUE TITLE
Query is being re-issued when moving to a different time range on the trail. We need to refine the logic in scene query runner that evaluates if time range is different

### ISSUE THREAD

**Issue by adrapereira** [grafana/grafana#78185]
https://github.com/grafana/scenes/blob/main/packages/scenes/src/querying/SceneQueryRunner.ts#L226

**Comment by darrenjaneczek** [comment]
The logic is resolved and merged into `scenes`.
- https://github.com/grafana/scenes/pull/468
I just have to figure out how and when to issue a new release and update Grafana to use it.
