### ISSUE TITLE
[Bug] Slack Alert notification under proxy

### ISSUE THREAD

**Issue by andrea-borraccetti** [grafana/grafana#7818]
Hi all
After update from Grafana v4.1.2 to v4.2 Beta, the notification to slack doesn't work if it must use a proxy server to reach the webhook. It seems that grafana try to send the call only without proxy. 

I define the proxy settings in the environment configuration of grafana with:
http_proxy=http://x.x.x.x:3128
https_proxy=http://x.x.x.x:3128
dns_proxy=http://x.x.x.x:3128

What Grafana version are you using? 4.2-Beta
What datasource are you using? N/A
What OS are you running grafana on? Ubuntu 16.04.2
What did you do? Send test from Alert Notification (Slack)
What was the expected result? a message in slack
What happened instead? error during connection to webhook

**Comment by torkelo** [comment]
Hi, 

This is fixed in master and will be fixed in 4.2 stable. will try to get a new nightly build out in the next 2-3 days. We hope to release 4.2 stable early next week.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/7710
