### ISSUE TITLE
Elasticsearch: Remove TimeInterval from backend as not used

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#78187]
We are not using `TimeInterval` at backend https://github.com/grafana/grafana/blob/c06debe20046a2e1062b632728eb8856f195bd96/pkg/tsdb/elasticsearch/client/client.go#L39, cause it is used in frontend to calculate correct `DataQuery.Interval`.  Therefore we can remove it.

**Comment by samucap** [comment]
Hi, I'd like to take this one.

**Comment by ivanahuckova** [comment]
@samucap thank you so much! 🧡  Yeah, you are right - just removing `TimeInterval` from `/pkg/tsdb/elasticsearch`. I will assign you the issue.
