### ISSUE TITLE
[BUG]? Data Limit reached from InfluxDB 1.2?

### ISSUE THREAD

**Issue by 999chris** [grafana/grafana#7820]
Hi,

Recently I've noticed (I think since upgrading Influx to 1.2). Grafana is unable to show all the data from InfluxDB that I require if I go back too far in time.

For example:

![image](https://cloud.githubusercontent.com/assets/26387530/23864432/6d68468e-080a-11e7-9986-d9032ce3de8f.png)

You can see Alert Annotations have been made (meaning that data exists), though the data only goes for a few hours in the UI.

Is this a data limit issue with Grafana or InfluxDB. Is there a workaround on Grafana or Influx you're aware of? I feel as though there should be a warning if not all the data can be shown.

I appreciate your help with this in advance.

**Comment by 999chris** [comment]
...  just to follow up. I have the Group By time paramater set to 30s. I realise this is why the data points are such high resolution and therefore possibly causing the issue.

I could set to "auto" but when I set a shorter timerange the graph is a mess:

![image](https://cloud.githubusercontent.com/assets/26387530/23864715/469d5462-080b-11e7-9764-a8de03e0a304.png)



Is there a way of setting an auto minimum perhaps? In this case 30seconds would be great.

**Comment by torkelo** [comment]
check out this thread: https://github.com/grafana/grafana/issues/7380

**Comment by 999chris** [comment]
Thanks torkelo. You're doing a great job.
