### ISSUE TITLE
Explore: `getExploreUrl` doesn't receive and use `AdHocFilter[]`

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#78200]
`getExploreUrl` uses [ds.interpolateVariablesInQueries](https://github.com/grafana/grafana/blob/main/public/app/core/utils/explore.ts#L75) to interpolate variables. And [interpolateVariablesInQueries method was updated to accept adHocFilters[]](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L336). But `getExploreUrl` currently doesn't have these passed in props and therefore ad-hoc filters are not added when jumping from dashboard to Explore. 

This causes an issue for data sources that migrated `TemplateSrv` from `app/features/templating/template_srv` to `@grafana/runtime` and rely on these passed adhoc variables. 

Data sources (e.g. Prom/Elastic) that were migrated and rely on adhoc param in interpolateVariablesInQueries don't include adhoc variables when jumping to Explore anymore:

https://github.com/grafana/grafana/assets/30407135/2432f901-f6cb-4c64-b641-a44940de81ec

Data sources (e.g. Prom/Elastic) that weren't migrated and don't rely on adhoc param in interpolateVariablesInQueries include adhoc variables when jumping to Explore:

https://github.com/grafana/grafana/assets/30407135/66e9c990-4552-492d-a80e-6a52e4e76c8c

Might be related to https://github.com/grafana/grafana/pull/75552

**Comment by harisrozajac** [comment]
@ivanahuckova I was able to reproduce this one, but I need a bit more time to work on it. I'll look at this in the morning.

**Comment by ifrost** [comment]
@ivanahuckova I think Explore never supported AdHoc filters explicitly. It is implemented by data sources by calling `templateSrv.getAdhocFilters(this.name);`.  If there's a need to support AdHoc filters with Explore URLs we can add it as a feature request and add it to the backlog but probably won't be prioritized this quarter.

I have no context on #75552 but it seems you still can use `getAdhocFilters` (it's deprecated, not removed).

What's the depreciation period? I don't see any deprecation notice in #75552 that would be added to the changelog. Can it be used by 3rd party plugins? cc @torkelo @dprokop

**Comment by harisrozajac** [comment]
After looking at this one these are my findings:
- This issue is definitely related to https://github.com/grafana/grafana/pull/75552 because this is where Prometheus's way of handling ad-hoc filters has changed
- This issue is not a bug in Explore because it was caused by a change in datasources. Of course, we can support this feature in the future, but we'll have to prioritize it
- With the deprecation of `template_srv.getAdHocFilters` should we still use `getFilteredVariables` from here: https://github.com/grafana/grafana/blob/027a1578985ddcdd30cd21b91f47a65450298164/public/app/features/variables/state/selectors.ts#L98

**Comment by torkelo** [comment]
@ivanahuckova @ifrost @harisrozajac 
https://github.com/grafana/grafana/pull/78339

**Comment by ivanahuckova** [comment]
Awesome! Thank you @torkelo

**Comment by ivanahuckova** [comment]
Fixed by https://github.com/grafana/grafana/pull/78339
