### ISSUE TITLE
[Bug] Span over 6 limits displayed items

### ISSUE THREAD

**Issue by Jason-field** [grafana/grafana#7821]
Version: 4.1.1 (Also tested against latest BETA and master docker images)
Data source: Influx 
OS: Ubuntu 16.04 docker host 

Problem:
When I use a template which returns more than 6 results I can only see the first 6 if I have the span set to between 7 and 12, if I set the span to 6 I can see all items

**Comment by torkelo** [comment]
probably related to this issue: https://github.com/grafana/grafana/issues/7380
