### ISSUE TITLE
[Bug] GET api/datasources with no id returns incorrect JSON for some fields

### ISSUE THREAD

**Issue by ncabatoff** [grafana/grafana#7822]
- What Grafana version are you using?
4.1.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Fedora 25 is the host OS, but using the stock docker image, so really Grafana is running on Debian Jessie.
- What did you do?
a) queried http://localhost:3000/api/datasources
b) queried http://localhost:3000/api/datasources/1
- What was the expected result?
The datasource with id 1 appears the same in the output of both commands.
- What happened instead?
a) api/datasources: typeLogoUrl="", withCredentials=false, secureJsonFields=null
b) api/datasources/1: typeLogoUrl="public/app/plugins/datasource/prometheus/img/prometheus_logo.svg", withCredentials=true, secureJsonFields={}

Comparing with what's shown in the datasource UI, I can see that the output of (a) is incorrect, at least with respect to withCredentials.

**Comment by torkelo** [comment]
yes, this is a bug. Might be an issue for this already not sure. These fields should not show up at all in the list api resource. These properties should only show when you fetch by id
