### ISSUE TITLE
[Bug]: now/d does not respect UTC timezone setting

### ISSUE THREAD

**Issue by Roguelazer** [grafana/grafana#7823]
If a dashboard is set to UTC mode, `now/d` still starts at the current day in the browser's local timezone, as opposed to the current day in UTC. 

I would prefer if `now/d` aligned with the dashboard-wide timezone setting (for UTC graphs, if it started at 0:00 UTC instead of 0:00 browser time). If that isn't possible for backwards-compatible reasons, I would also accept a new suffix like `now/d@utc` to force UTC alignment of the day boundary.

**Grafana version**: 4.1.1
**Datasource**: Graphite & ElasticSearch
**OS**: CentOS
**What did you do**: Set a dashboard's timezone to UTC when the Time Range was `now/d` to `now`.
**Expected Result**: Graph would range from 0:00 UTC to the current time
**Actual Result**: Graph ranges from 07:00 UTC to the current time

**Comment by maxiberta** [comment]
This affects Prometheus datasource too. Setting `from now-7d/d to now/d` (for improved cache hit rate), `start` and `end` request params from browsers on different timezones are offset by eg. 3 hours on UTC-3. 

Note that `start` and `end` _do match_ with `from now-7d/h to now/h` on different timezones.

**Grafana version**: tested on 3.0.0 and 4.1.2
