### ISSUE TITLE
Save dashboard flyout - not appearing or taking 15sec+ to appear since 10.2 -> 10.2.1 update

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#78234]
### What happened?

I use Grafana every day, and very frequently-   Since the 10.2.1 update (was coming from 10.2.0) ,  At times clicking the dashboard's save button will either freeze indefinitely, or will take 15 to 60 seconds for the window / fly-out to appear where you can then press apply (to actually save the dashboard changes).

This is pretty critical because as of 10.2.1 - I may spend a good amount of time making changes to a dashboard but I'm not sure if I'll actually be able to save/write my changes (or if the browser window will indefinitely lock up , with only way out to close the browser window and thus loose my new dashboard changes).

I can reproduce on both Firefox 119.1  and chrome 119.0.6045   (and have tested on a separate PC onsite, and the issue persists)

Even when the issue does not occur, There is a significant delay from the time you click the save button to when the flyout appears,  which was not the case on 10.2.0 and prior.

I know this was since the 10.2.1 update as I would have noticed it or others would have complained to me, when we were on 10.2.0 for the past three weeks or so.

I enabled trace logging in Grafana.ini ,  but nothing relevant shows up that i can see (see full log below, was 2.8mb in size - note i did find/replace on some specific names, and replaced with XX): 
https://paste.c-net.org/MultiplySector
 (log file was too large for pastbin)

Frequently if / when the lockup occurs (ie user waiting for the fly-out to appear), if I go to the debian Server and issue:
`service grafana-server restart; sleep 2; service apache2 restart`

after that, *usually* the flyout will then appear, and ill be able to successfully save.  (most of the time).

Please let me know if i can provide additional data.

here is the plugins dir on the server (i did delete a few that we dont use any longer-  note i did test removing all of these below, and restarting,  issue still persists):

![image](https://github.com/grafana/grafana/assets/60830628/a166c057-6795-424a-8875-e628b68fe2eb)

thanks

(LOVE GRAFANA!!)

### What did you expect to happen?

Save to function like it did on prior grafana versions

### Did this work before?

yes , was fine / fast on 10.2.0

### How do we reproduce it?

1. update from 10.2.0 to 10.2.1
2. modify an existing dashboard (maybe have to be a large dashboard)
3. click save icon (disk icon) and the flyout should take a while to appear (if at all)

### Environment (with versions)?

Grafana: 10.2.1
OS: ubuntu20
Browser: chrome / FF (versions in txt above)

### Grafana platform?

A downloaded binary

**Comment by Freezepop** [comment]
I can confirm. OS Ubunta 18.04, Oracle 8.6. The problem started after upgrading from 10.0.3 to 10.2.1.

It's horrible. In fact, users cannot modify dashboards normally.

**Comment by serrrios** [comment]
+1

**Comment by torkelo** [comment]
This sounds terrible! we will investigate as quickly as we can. We have no other reports, and I can't replicate it. I have experianced a ~1-5 seconds freeze a couple weeks ago on a really large dashboard so I feel there is something bad going on. 

@bob454522 @Freezepop can anyone subscribe a json file for a dashboard that shows his behavior? Is it always?

* How big is the dashboard? 
* If you save , then make another change is it slow again?

**Comment by Freezepop** [comment]
@torkelo 

Example json in attachment.

1) Json for almost 7k lines. In what units can we say how big the Dashboard is? :)

2) Saving freezes the page even when you just move the panel a little to the right/left.

[sample.json](https://github.com/grafana/grafana/files/13373504/sample.json)

**Comment by Freezepop** [comment]
@torkelo 
UPD: It seems the problem gets worse in proportion to how many rows were expanded when saving. The more of them, the slower the dashboard is saved, up to complete failure.

**Comment by ivanortegaalba** [comment]
Thanks, @Freezepop, I'm trying to get a reproducible env locally. Can you share with me the HAR file from the browser?

It helps if includes:
1. Time when clicking in "Save icon" 
2. Time when clicking on "Changes" tab

Thanks! 🙏

**Comment by ivanortegaalba** [comment]
@Freezepop I found a possible cause for this performance issue. Can you try to deactivate `dashgpt` feature flag in your instance? This can quickly fix your issue.

**Comment by Freezepop** [comment]
@ivanortegaalba 
1) [click_on_save_ico.txt](https://github.com/grafana/grafana/files/13377126/click_on_save_ico.txt)
2) [click_save_in_change_tab.txt](https://github.com/grafana/grafana/files/13377125/click_save_in_change_tab.txt)

I can confirm.
Adding "dashgpt = false" to the [feature toggles] section fixes the performance issue in my case.

**Comment by ivanortegaalba** [comment]
Great! I'll work on getting a PR to solve this issue asap. I'll also backport it to v10.2.x so you will get the fix as soon as the next patch is released.

Thanks for bringing this to us with a lot of information! 💯

**Comment by bob454522** [comment]
> Adding "dashgpt = false" to the [feature toggles] section fixes the performance issue in my case.

This fixed it for me also!
I added (wo quotes):
`dashgpt = false`
to my `/etc/grafana/grafana.ini` 
and restarted:
`service grafana-server restart; sleep 2; service apache2 restart`
re-tested (fixed! no delay at all,  and save is back to normal!)

For what its worth-  i did *not* have dashgpt feature flag enabled (I actually haven't modified anything in my grafana.ini , nor otherwise, for quite over a year)  but this still resolved it!    (im not sure if i should close this comment/ticket or not - so admin feel free to close it)
thanks
(LOVE GRAFANA!)
