### ISSUE TITLE
apps not appearing in main menu

### ISSUE THREAD

**Issue by Jaware** [grafana/grafana#7824]
apps not appearing in main menu after enabled

Grafana 4.1.2, mac 

 
<img width="598" alt="qq20170314-0" src="https://cloud.githubusercontent.com/assets/3970304/23892794/0563270c-08d7-11e7-8b4a-5f32a2478678.png">

**Comment by torkelo** [comment]
only some apps do this depending on how they are configured (by the plugin author)
https://github.com/raintank/worldping-app/blob/master/src/plugin.json#L103

**Comment by Jaware** [comment]
thanks,maybe it is a bug,which pages array property not work anymore

**Comment by torkelo** [comment]
do you have an enabled app that have `addToNav` properties defined in their plugin.json yet still not showing in the menu?

**Comment by Jaware** [comment]
it worked,thanks
