### ISSUE TITLE
Bug: Plugin source maps are broken

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#78259]
Plugin source maps in production environments appear to point to wrong code. The screenshot is from a breakpoint in loki data source query method

![Image](https://github.com/grafana/grafana/assets/73201/20734471-b4ab-46fb-8df4-777bc778fd0f)

Checking plugin sourcemaps using the visualizer proves the output isn't the problem:

![Image](https://github.com/grafana/grafana/assets/73201/fecd77f9-90b8-4eee-8daa-eb74f7f8ca9d)

The bug appears to be coming from the [iife wrapper](https://github.com/grafana/grafana/blob/main/public/app/features/plugins/loader/systemjsHooks.ts#L88-L94) introduced in the SystemJS bump work to circumvent a conflict with requirejs which is used to load monaco editor.

**Comment by mckn** [comment]
Fixed by [#78415](https://github.com/grafana/grafana/issues/78415)
