### ISSUE TITLE
Incorrect warning about regular expression invalidity.

### ISSUE THREAD

**Issue by Freezepop** [grafana/grafana#78254]
### What happened?

When I try to use a regular expression with a flag in variables, I get messages about its invalidity, but everything works and it is possible to save the variable.

![изображение](https://github.com/grafana/grafana/assets/28865504/8533ae00-a504-4e3d-ac3a-b95d031be0d9)

### What did you expect to happen?

Don't receive an error message.

### Did this work before?

As far as I remember, there was no such message before.

### How do we reproduce it?

1. Write a query with a regular expression with a flag in variables.
2. See a warning about invalidity.

### Is the bug inside a dashboard panel?

Nope

### Environment (with versions)?

Grafana: 10.2.1
OS: Ubuntu 18.04
Browser: FireFox 119.0.1

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

"Zabbix plugin for Grafana" - https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/

**Comment by tonypowa** [comment]
hi @Freezepop 

Is this issue specific to the zabbix plugin?

**Comment by Freezepop** [comment]
@tonypowa 

Yes, I checked with other plugins where possible. It looks like the problem is only with the zabbix plugin.
I think we can close this issue. I’ll leave a similar one in the plugin project.

**Comment by tonypowa** [comment]
thanks for checking
feel free to reopen if needed
