### ISSUE TITLE
move functions from `pkg/tsdb/intervalv2` to `grafana-plugin-sdk-go`

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#78268]
there are two functions in `pkg/tsdb/intervalv2` that are used in many core plugins:
- `FormatDuration` : converts a `time.Duration` into a `string`, for example a string like `"5m"`. it’s used in azuremonitor, influx, loki, sql. for example, when interpolating the `$__interval` variable into a string.
- `ParseIntervalStringToTimeDuration`: the opposite of `FormatDuration`, converts a string like `"5m"` to the corresponding `time.Duration`. it’s used in azuremonitor, loki, prometheus. for example, when loading in time-duration fields from a json, that stores them as strings.

as these datasource-plugins become decoupled from core grafana, they will need to be able to do this functionality. one possible solution is to move these functions into `grafana-plugin-sdk-go`.

(relates to https://github.com/grafana/grafana/issues/73115)

**Comment by gabor-grafana** [comment]
note: `FormatDuration` was moved already in https://github.com/grafana/grafana/pull/81764 .

**Comment by gabor** [comment]
note: `FormatDuration` was moved already in https://github.com/grafana/grafana/pull/81764 .

**Comment by itsmylife** [comment]
`GetIntervalFrom` and `ParseIntervalStringToTimeDuration` was moved. https://github.com/grafana/grafana-plugin-sdk-go/pull/886

I did not update the `grafana/grafana` yet but I will.

**Comment by itsmylife** [comment]
`roundInterval` moved to https://github.com/grafana/grafana-plugin-sdk-go/pull/887

**Comment by itsmylife** [comment]
Removing `intervalv2` https://github.com/grafana/grafana/pull/82074
