### ISSUE TITLE
[Bug] Long term graphing doesn't work

### ISSUE THREAD

**Issue by kbechler** [grafana/grafana#7827]
Hello,

I've got simple InfluxDB/Grafana stack and observed strange thing.

Graph with two metrics. When time range is smaller than 12-13 hours, everything looks fine:
![screenshot from 2017-03-14 14 51 05](https://cloud.githubusercontent.com/assets/22340389/23904261/7eeacbb2-08c7-11e7-97ed-811d2cf374e6.png)

But when I expand time range to something like 24 hours, one of graphs disappears:
![screenshot from 2017-03-14 14 50 24](https://cloud.githubusercontent.com/assets/22340389/23904278/8eb6c0b4-08c7-11e7-81fd-d4f498a84d64.png)

After deleting one metric (doesn't matter which one), whole graph looks fine.

Regards,
Konrad

- What Grafana version are you using? 4.1.2-1486989747
- What datasource are you using? InfluxDB 1.2.0-1
- What OS are you running grafana on? Ubuntu 16.04.2 LTS
- What did you do? Setup graph with two metrics
- What was the expected result? See both metrics
- What happened instead? One of the metrics is cut after few hours

**Comment by torkelo** [comment]
this is due to a breaking change in InfluxDB 1.2

read this thread:
https://github.com/grafana/grafana/issues/7380
