### ISSUE TITLE
[Bug] Alerts and now() returns NO DATA

### ISSUE THREAD

**Issue by tcgjensen** [grafana/grafana#7828]
Please include this information:
- What Grafana version are you using?
4.1.2
- What datasource are you using?
influx
- What OS are you running grafana on?
linux centos
- What did you do?
Created an alert, but because the data in influx is in UTC and my local timezone is utc+2 using condition(5m,now()) in the alert will always result in "NO DATA" since now() returns my local time and not now in UTC. My influx db has latest data from 2 hours ago and therefore now() does not work.
I have configured UTC timezone in grafana.
I can see from another post made on the 12th jan 2017 (closed by torkelo) that data is always to be written in UTC in a timeserie db. I get that, but the now() in the alert should return now in UTC time not local time.

- What was the expected result?
now() should return now in UTC time and not local time
- What happened instead?
now() returns local time

**Comment by torkelo** [comment]
The query is executed in InfluxDB so is relative to the influxdb server time.

Does your graph show data for last 5min? Please open questions in the community forum. This is likely not a but as there no other reports like this since alerting was released months ago, and everyone use UTC on server and local time zone in browser

**Comment by tcgjensen** [comment]
But it can not be a requirement to use UTC on the server.
Grafana should be able to use timezones to present the data correctly. So
for that reason it is a bug. What is the point of being able to select
timezone if it does not work. for each graph I should be able to specify
timezone and have the data presented accordingly.
We have customers in different timezones and are (will be) receiving data
from all over and need to see the data presented in right time format in
order to understand it and use it for analysing and discuss with the
customer etc. When insidents are reported and reported to have happend on a
specific time, we should be able to find data in grafana without having to
think about converting to utc.
All you need to do is actually use the timezone feature on dashboard level
and expand it to contain all timezones and then cast the timestamp to the
timezone when extrating it and using it in the graphs.

**Comment by torkelo** [comment]
This is not something that is in Grafana's control as the query and the evaluation of the now keyword is evaluated by InfluxDB. 

InfluxDB I think requires that you write and query in UTC, the you can show the data in local time zone depending where user is. This had thus far never been an issue with the many thousands of InfluxDB and grafana users. 

So so i think you are confused, mixing together how data is shown and how it is queried.

**Comment by tcgjensen** [comment]
Look, I am not confused. Influx seems to handle timezones but again grafana
does not support it and since grafana puts restrictions on how to query
data, it becomes grafanas problem.
You sound a bit like a spoiled brad that does not like people to point out
that the app has issues. You just keep closing the tickets when you dont
like them.

**Comment by torkelo** [comment]
Sorry you feel that way. It was not my intent to sound spoiled. 

InfluxDB docs has zero mentioned of timezone. And as I said Grafana + InfluxDB is use by many thousands around the world in companies that span timezone and this has never come up which should at least give you some pause. I could be wrong I admit that but I think there is something else going on here that revolves around how you write or query the data. 

If you provide some more info I might be able to help. 

>Created an alert, but because the data in influx is in UTC and my local timezone is utc+2 using condition(5m,now()) in the alert will always result in "NO DATA" since now() returns my local time and not now in UTC. My influx db has latest data from 2 hours ago and therefore now() does not work.

This makes no sense. The timezone option for a query like 5m to now() is the same no matter if you have UTC in grafana (or anywhere). as the time range is evaluated by InfluxDB server. The difference will be how Grafana shows the data (time axis in graph). 

So if you show the graph for the 5m -> now() query, and the result of the Test Rule button (shows you the raw response from InfluxDB). Maybe it's an issue with the InfluxDB group by time is different with the 5m range query that is causing no data, or maybe there is no data for the last 5m. 

I am here to help
The spoiled brat
