### ISSUE TITLE
Add support export for Grafana Provider in Crossplane

### ISSUE THREAD

**Issue by Hronom** [grafana/grafana#78282]
Since we follow Infrastructure as Code, we wanna our developers to have possibility to construct yaml that can be directly used in crossplane-provider-grafana: https://doc.crds.dev/github.com/grafana/crossplane-provider-grafana/alerting.grafana.crossplane.io/RuleGroup/v1alpha1@v0.6.0

**Comment by armandgrillet** [comment]
cc @julienduchesne

**Comment by julienduchesne** [comment]
This is now possible using the resources exporter plugin: https://grafana.com/grafana/plugins/grafana-resourcesexporter-app/

Issues with the plugin should be reported here: https://github.com/grafana/grafana-resources-exporter-plugin
