### ISSUE TITLE
[Bug] Stack Display with 'fill(none)' will not render correctly

### ISSUE THREAD

**Issue by notes-jj** [grafana/grafana#7829]
- What Grafana version are you using?

  dockerhub: grafana/grafana:4.1.2 --- 2017-02-19T12:42:59

- What datasource are you using?

  dockerhub: influxdb:1.2.0-alpine

- What OS are you running grafana on?

  debian:jessie

- What Browser:

  Windows Firefox 52.0 64-bit

- What did you do?

  I created a Graph with fill option null and display option stack.

  `SELECT sum("value") FROM "teststack" WHERE $timeFilter GROUP BY time($interval), "user" fill(none)`

- What was the expected result?

  The bars should stack like when setting `fill(0)`.

  Example 1:
![image](https://cloud.githubusercontent.com/assets/17141243/23903632/7252de64-08c5-11e7-96b3-770f03e67b08.png)

  Example 2: Real World Scenario. This is the users amount of bad passwords produced in two days. This graph is set to sum up, not to group by username and `fill(0)`. This graph give the outline look of the group by graph.
![image](https://cloud.githubusercontent.com/assets/17141243/23906487/661c05cc-08ce-11e7-96ee-15f4fc8999a4.png)

- What happened instead?

  Example 1: The bars are stacking in a strange way and are rendered to broad. Screenshot from sample data below:
![image](https://cloud.githubusercontent.com/assets/17141243/23903604/5d63176c-08c5-11e7-99ee-55ce7fb60851.png)

  Example 2: Grouped by user name and `fill(none)` Look at the black space at the bottom of the bars. But some bars are also too tall (maximum should be 102 and not almost 250). In this case the bars are not rendered too broad:
![image](https://cloud.githubusercontent.com/assets/17141243/23906526/8363cc6e-08ce-11e7-868e-0e1107767f17.png)

### Workaround, but fails with Large Amount of Tags

  As workaround set `fill(0)`. 

  This will not help for databases with a high amount of tags/series. There are 2968 unique user names as tag values in our real world database. If I set `fill(0)` there will be missing tags/series.

  Example 2 Error with large Amount of Tags: The maximum is approx. 30 and should be at 102
![image](https://cloud.githubusercontent.com/assets/17141243/23906551/9e7eadfc-08ce-11e7-8e25-4af6559dedf1.png)

### Steps to Reproduce Example 1:

  1. Create test database in influxdb
  2. Import 'InfluxDB Sample Data' into test database
  3. Create datasource in grafana to connect to test database
  4. Create new dashboard
  5. Create new graph panel
  5. Import 'Grafana Panel JSON' into graph

### InfluxDB Sample Data

InfluxDB Data to reproduce the error in exapmle 1. The data starts at 2017-03-14T12:00:00Z

    teststack,user=a value=1 1489492800000000000
    teststack,user=b value=1 1489492800000000000
    teststack,user=c value=1 1489492800000000000
    
    teststack,user=d value=1 1489493100000000000
    teststack,user=e value=1 1489493100000000000
    teststack,user=f value=1 1489493100000000000
    
    teststack,user=a value=1 1489493400000000000
    teststack,user=b value=1 1489493400000000000
    teststack,user=c value=1 1489493400000000000
    
    teststack,user=d value=1 1489493700000000000
    teststack,user=e value=1 1489493700000000000
    teststack,user=f value=1 1489493700000000000

### Grafana Panel JSON

Grafana Test Panel to reproduce the error. Bear in mind to change the data source to your data source.

    {
      "aliasColors": {},
      "bars": true,
      "datasource": "testjj",
      "fill": 1,
      "id": 1,
      "interval": ">5m",
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": false,
      "linewidth": 1,
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "span": 12,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "dsType": "influxdb",
          "groupBy": [
            {
              "params": [
                "$interval"
              ],
              "type": "time"
            },
            {
              "type": "tag",
              "params": [
                "user"
              ]
            },
            {
              "params": [
                "none"
              ],
              "type": "fill"
            }
          ],
          "measurement": "teststack",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "sum"
              }
            ]
          ],
          "tags": [],
          "alias": "$tag_user"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "links": []
    }

**Comment by torkelo** [comment]
It you want to good results when stacking fill(0) is always goods. Makes sure there are always values for every point and makes the bar width for each series the same.

**Comment by notes-jj** [comment]
If I set `fill(0)` then there are missing values in databases with large amount of tags. So it does not solve my problem.

**Comment by torkelo** [comment]
Missing values? You might  be running into the issue of the low max-row-limit option that is affecting a lot of InfluxDB users, you need to increase that InfluxDB sever setting

**Comment by notes-jj** [comment]
@torkelo max-row-limit=250000 solved the missing tag problem part.

But nevertheless, don't you think this report should be a feature request. Because the stack display is really messed up with `fill(none)`.  The `fill(none)` will save transfer time and transfer size. In my real world example:

- 30 Days with fill(0)
  - 982 ms
  - 51,7 KiBi JSON

- 30 Days with fill(none)
  - 432 ms
  - 32,7 KiBi JSON

**Comment by torkelo** [comment]
without regular bucketed data bars display becomes a mess, and doing date group by is the responsibility of the time series backend. 

the response size should not be that different if you have use auto interval, maybe if you a lot of missing data / empty series there might be a difference. But returning 0 or null for missing data is very crucial information that Grafana cannot know

**Comment by vikrant-eligible** [comment]
@torkelo , I am also facing a similar problem
Is it not possible for grafana to plot null/zero values at those time intervals which influxdb didnot return because of `fill(none)` was passed in query. This would make the graph realistic.

Current graph rendering with `fill(none)`:
![image](https://user-images.githubusercontent.com/42178801/50627598-35776080-0f5a-11e9-925b-cea2442333b3.png)


Graph gendering with `fill(0)` but with large time_interval in `GROUP BY  time_interval` so that there is no missing data:
![image](https://user-images.githubusercontent.com/42178801/50627603-3d370500-0f5a-11e9-9304-dee256f41bdf.png)

I know there is the workaround mentioned above 
```Workaround with Large Amount of Tags like pointed out by torkelo: Increase the number of maximum rows in influxdb.conf section [http] max-row-limit=250000 or with docker set environment on run -e INFLUXDB_HTTP_MAX_ROW_LIMIT=250000.```
But isn't it inefficient to pass large amounts of redundant values (zero or null values) from Influxdb when Grafana can itself place `zero or null values` in place of missing time_intervals with `fill(none)`
