### ISSUE TITLE
Table Panel, value mapping, mapping value from Another Sub Query rather than custom data set

### ISSUE THREAD

**Issue by getchu** [grafana/grafana#78301]
**Why is this needed**:

DataSource: MySQL-TradeCenter
select time, order_no, sku_code from orders limit 100;

DataSource: MySQL-GoodsCenter
select sku_code, sku_type from sku_type_mapping;

There are many sku_code and sku_type, 
I don't want to configuration the "Value-Mappings" for each panels , 
or  enter so many key-values one by one .....

I need a new feature : 
the value-mapping function,
add HashMap (key-value) from  Another Sub Query (mysql or sqlite3) , rather than custom data set

**Comment by getchu** [comment]
We could not "Join Table" between two mysql cluster;
And I don't want to use  the  "Transformations" -> "Join The Field";

**Comment by gelicia** [comment]
> And I don't want to use the "Transformations" -> "Join The Field";

@getchu Why not? If you can't do a SQL join, this is how you would do a join in Grafana.
