### ISSUE TITLE
Design: Align the usage of search bard and pagination for playlist and snapshots pages

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#78316]
**Background / Why we're doing this**

Currently we have different UI for the search bar on these pages, and also we are missing the pagination and search bar for snapshots list page. We want to make consistent the look & feel of these pages, to follow the pattern that we see in Playlist page.

**What we have**
-Playlist page
<img width="1773" alt="Screenshot 2023-11-17 at 11 20 57" src="https://github.com/grafana/grafana/assets/51436795/63d97ca0-2cc7-43dc-a1ed-511bb8dc6bbf">

-Snapshots page
<img width="1755" alt="Screenshot 2023-11-17 at 11 20 52" src="https://github.com/grafana/grafana/assets/51436795/1209ec23-5c30-4eba-a76f-84d9ccd8449f">

**What we want to achieve**
-Library panels page
<img width="1735" alt="Screenshot 2023-11-17 at 11 21 08" src="https://github.com/grafana/grafana/assets/51436795/f3abe7ea-cf86-407f-b9a4-df904b404c54">

**Tasks**

- [x] Add search bar
- [x] Add pagination
- [x] Update cards component from Saga Design System

**Comment by EduardZaydler** [comment]
Hello, are there any deadlines for this issue?

**Comment by natydej** [comment]
This issue will be addressed when we update these designs -https://github.com/grafana/grafana/issues/82303

**Public dashboard page**
<img width="1440" alt="PublicDashboardPage" src="https://github.com/grafana/grafana/assets/51436795/efc5315c-ddcd-48c6-96c3-38f6e41d6778">

**Snapshot page**
<img width="1440" alt="SnapshotsPage" src="https://github.com/grafana/grafana/assets/51436795/b2c1157a-f6b8-434d-b587-fbb4aa045e67">
