### ISSUE TITLE
[Feature Request] Include a Cassandra Dialect 

### ISSUE THREAD

**Issue by brandonraphael** [grafana/grafana#7831]
Please include this information:
- What Grafana version are you using: 4.1
- What datasource are you using: OpenTSDB
- What OS are you running grafana on: Linux
- What did you do: Wanted to use Cassandra as the DB for grafana
- What was the expected result: That a dialect for Cassandra existed already
- What happened instead: The Cassandra dialect was found not to exist.

I'm willing to make this change myself obviously, just need a little guidance on how you would like this done.

**Comment by torkelo** [comment]
Grafana has no built in plugin for Cassandra, but KairosDB can read from Cassandra, and there is an external plugin for KairosDB

**Comment by torkelo** [comment]
https://grafana.com/plugins

**Comment by brandonraphael** [comment]
To be clear, we do NOT need Cassandra as a datasource. We want to create a Cassandra dialect to use Cassandra and store user data. Will this plugin do that?

**Comment by torkelo** [comment]
Not sure what you mean, you want to store m Grafana  users and dashboards etc in Cassandra?

**Comment by brandonraphael** [comment]
yes, that is correct.

**Comment by torkelo** [comment]
ok, interesting. Why do you want to use Cassandra (or a DB that speaks Cassandra) for something like this?

**Comment by brandonraphael** [comment]
Our architecture is required to be highly available, and thus have no single point of failure. Currently, the databases which can used to store user data all have a single point of failure (for example, in the case that Postgres' master node were to fail). Cassandra would help us fulfill our criteria by being decentralized.

**Comment by torkelo** [comment]
Facebook seem to be doing pretty good with decentralised & highly available systems many depending on big MySQL clusters. 

Not sure of the HA / failover situation for Postgres but must have some auto failover / master election. 

Anyway, unless you fork Grafana and rewrite the data layer, Cassandra dialect is not going to happen :(

**Comment by brandonraphael** [comment]
Yeah, believe you me MySQL would make enough sense but these requirements weren't laid out by me (or facebook).

Mostly I was just looking for some guidance as to what exactly needs to be changed. Is adding the Cassandra dialect as simple as editing the pieces in the grafana/pkg/services/sqlstore/migrator folder? What do you mean by 're-writing the data layer' exactly?

**Comment by torkelo** [comment]
Last time I checked Cassandra is not using  SQL dialect, it  other even a relational database. Which is why you would have to rewrite the whole data access layer. 

Cassandra is a non-relational database, and so uses different concepts to store and retrieve data. Simplistically, a Cassandra keyspace is a SQL database, and a Cassandra column family is a SQL table (CQL allows you to interchange the words “TABLE” and “COLUMNFAMILY” for convenience). This difference necessitates a different syntax for creating and manipulating data:
