### ISSUE TITLE
[Feature request] - Can we use mysql db to store ldap credentials & config instead of text file ldap.tmol

### ISSUE THREAD

**Issue by vishksaj** [grafana/grafana#7833]
Can we use mysql db to store ldap credentials & config instead of text file ldap.tmol

Org restrictions and ldap credentials are now stored in text file   /etc/grafana/ldap.tmol which is causing an open vulnerability. If we can store it in a DB it well be helpful.

**Comment by torkelo** [comment]
The database is no less secure than a text file. We do want to add support to change most settings via UI (and persist in database) in the future. But there is no security advantage in this,

**Comment by vishksaj** [comment]
@torkelo Thank you for the update.
