### ISSUE TITLE
New User UX Improvements

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7836]
Quick things we can do to improve new user experience: 

- Guide user how to edit panels and get to metrics tab.
- Do not auto collapse queries for InfluxDB, Elasticsearch & Prometheus etc for new panels or if there is only 1-3 queries. 
- Validate Elasticsearch index exist & timefield exist in Elasticsearch Test Data source

**Comment by thuck** [comment]
@torkelo for the auto collapse should it have some "memory"? Meaning if the collapse was selected by the user or if it was automatic done by the system? So it should be possible to differentiate if even with less than 3 queries the user "forced" the collapse.

**Comment by torkelo** [comment]
Maybe if it comes up as a popular feature request, but for now I think we can "auto expand" when > 3 queries

**Comment by torkelo** [comment]
<img width="429" alt="screen shot 2017-03-29 at 16 11 25" src="https://cloud.githubusercontent.com/assets/10999/24458871/7793819a-149a-11e7-8c7b-9beeb4086ed7.png">

<img width="355" alt="screen shot 2017-03-29 at 16 12 21" src="https://cloud.githubusercontent.com/assets/10999/24458896/865790d6-149a-11e7-9177-6f34e74a2a44.png">
