### ISSUE TITLE
Loki Derived field is not displaying in Explore. 

### ISSUE THREAD

**Issue by naveenarintech** [grafana/grafana#78364]
### What happened?

I am trying to setup tempo where it can derive the field from loki log and setup an internal link to tempo to lookup the trace id.

this example works perfectly fine in 10.2 or below version(tried using docker containers of grafana). However its failing on Grafana cloud which runs on Grafana v10.3.0-63516 (5096806eab) or on docker container grafana/grafana-dev:10.3.0-147059

Log line
```
2023-11-18 05:26:42.617  INFO [boot-otel-tempo-api,4a3457699c23142ed64b9205de568598,5a5fc9cf379b6bab] 7 --- [nio-8080-exec-4] i.o.example.flight.FlightService         : Doing some work In New span 
2023-11-18 05:26:42.595  INFO [boot-otel-tempo-api,4a3457699c23142ed64b9205de568598,c481f08fa02b4a6a] 7 --- [nio-8080-exec-4] i.o.example.flight.FlightClient          : Getting Flights from http://boot-otel-tempo-provider1:8090/flights 
2023-11-18 05:26:42.595  INFO [boot-otel-tempo-api,4a3457699c23142ed64b9205de568598,0cd27ae7e7acbd16] 7 --- [nio-8080-exec-4] i.o.example.flight.FlightService         : Getting flights for India 
```

Logs and Traces does exists
![image](https://github.com/grafana/grafana/assets/147517211/21deeb9f-1e78-4e9f-b242-0693b1982d9d)

Derived field is parsing the traceid too.

![image](https://github.com/grafana/grafana/assets/147517211/e531e831-859c-448c-bba9-4e84deb2317e)

However when i query the loki logs, its now showing the Derived field.  Either i have some issue with my configuration pertains to latest version of grafana OR derived field is not working as expected. 

### What did you expect to happen?

I should be able to see the derived field in loki logs with internal link to look up the trace ID in tempo

### Did this work before?

It works fine in 10.2 or lower grafana version. Does not work in Grafana cloud which runs on v10.3.0-63516 (5096806eab)

### How do we reproduce it?

1. Setup Loki to record logs consists of Trace ID
2. Setup tempo to record the spans and traces
3. Configure the datasource in grafana v.10.3 using  container grafana/grafana-dev:10.3.0-147059 OR grafana cloud
4. Try to setup derived field between Loki and tempo

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.3.0-63516 (5096806eab)
OS: Windows 11
Browser: Version 119.0.6045.160 (Official Build) (64-bit)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Loki, tempo

**Comment by MatthieuBailleul** [comment]
Hello,
I have the same problem on grafana cloud. Debug mode confirms the correct discovery of the trace id but no derived field is displayed to me during a query on the configured data source.
Could we have some news and confirm that this is indeed a bug?
I also tried with an external link (google search on trace id) and it's the same
Sincerely,
Matthew

**Comment by usmangt** [comment]
Hi @naveenarintech,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by usmangt** [comment]
Also, can you please attach the configuration file that you used to reproduce this issue?

**Comment by gustysap** [comment]
Hello,

I have same issue, the debug log is correct but still not displaying in Explore.
My configuration is like this 
![image](https://github.com/grafana/grafana/assets/30117785/d548d5c1-4f66-4f3d-9b9a-03bcd2908574)

**Comment by matyax** [comment]
@svennergr could this be related to the recent contribution?

**Comment by svennergr** [comment]
Hi folks,

unfortunately this was a bug that should be fixed with https://github.com/grafana/grafana/pull/78849. 

Please let us know if you still experience this behaviour on a Grafana version containing this fix. The current release Grafana Cloud version `Grafana v10.3.0-64082 (0c9356a3c7)` should contain the fix.

**Comment by Filipcsupka** [comment]
I am using kube-prometheus stack on version 57.1.1 and i have this sisue also sitll in 2025...
When i set derived fields in helm chart it never appears in logs or direectly in Loki datasource but all logs from Grafana say its OK
