### ISSUE TITLE
First repeating library panel erroneously shows no data

### ISSUE THREAD

**Issue by mhoran** [grafana/grafana#78368]
### What happened?

When using repeating library panels and the panel is repeated (i.e. there is more than one value for the configured variable), the first panel will return "No data" until the dashboard is refreshed.

This looks to be a regression with the fix for #59805. Unlinking the library panel and saving the dashboard resolves; but re-linking the dashboard panel will introduce the bug again.

### What did you expect to happen?

Repeating library panels should work just like regularly repeating panels and show the correct data (not no data).

### Did this work before?

Yes.

### How do we reproduce it?

1. Create a dashboard with a variable and two values, and allow multi-value and include all option
2. Create a library panel that repeats based on that variable
3. Select the all option and save the dashboard, selecting the option to save current variable values as default
4. Navigate to a different dashboard
5. Navigate back
6. Notice that the repeating library panel shows "No data" until the refresh button is clicked

### Environment (with versions)?

Grafana: Grafana Cloud v10.3.0-63516 (5096806eab)
OS: Linux
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
hi @mhoran 
I could not repro the issue in current Grafana v10.3.0-63588 (13d67be0a9), is the issue still reproducible from your end?

**Comment by mhoran** [comment]
I was just able to reproduce with the latest Grafana Enterprise Docker image `v1.3.0-64033` (ab83bc7346). Perhaps the data source needs to be of type Prometheus. Here is a sample dashboard using the `up` metric. You will need to replace the instance variable with two meaningful instance values for your Prometheus data source. The single library panel is a time series with query `up{instance="${instance:raw}"}` and repeat by variable `instance`.

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "libraryPanel": {
        "name": "Panel Title",
        "uid": "a8d6df17-c578-49c8-b622-ff1918b3545c"
      },
      "title": "Panel Title"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": [
            "All"
          ],
          "value": [
            "$__all"
          ]
        },
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "instance",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "replaceme-instance-1",
            "value": "replaceme-instance-1"
          },
          {
            "selected": false,
            "text": "replaceme-instance-2",
            "value": "replaceme-instance-2"
          }
        ],
        "query": "replaceme-instance-1, replaceme-instance-2",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "uid": "a77c5aa2-9f8b-45b6-a460-77a885934a6e",
  "version": 9,
  "weekStart": ""
}
```

**Comment by tonypowa** [comment]
sorry for the delay in my answer

can't import the dashboard for some reason @mhoran . can you try to import it?
if it works for you and not for me , can you record your screen reproducing the issue?

many thanks

**Comment by mhoran** [comment]
You likely can't import because of the referenced library panel. Create a library panel as described above (time series with query `up{instance="${instance:raw}"}` and repeat by variable `instance`). Then replace the UID `a8d6df17-c578-49c8-b622-ff1918b3545c` in the exported dashboard with the UID of the created library panel.

https://github.com/grafana/grafana/assets/5330/6dbd5792-b298-4461-af24-f3777fb1df97

**Comment by mhoran** [comment]
I can't get GitHub to accept a screen capture, it says the file is corrupt. But the issue is simple. Opening the dashboard using a library panel as described shows "No data". After clicking the refresh button in the Grafana UI the graph loads.

![Screenshot_20231211_090902](https://github.com/grafana/grafana/assets/5330/b1a93412-0f11-4a3c-b1a5-077131d6ee6f)
![Screenshot_20231211_090909](https://github.com/grafana/grafana/assets/5330/9fc5a2ad-76ce-4c92-bcf8-38b6023f6e24)

**Comment by jerno** [comment]
Same problem here.
I can confirm, it is indeed always the **first repeating library panel**!
And it does work well after refresh, but it shows no data on initial dashboard load.

**Comment by jayceslesar** [comment]
+1 on this being an issue, exactly as others have described, although it shows incorrect data in my case and not no data.

**Comment by mdvictor** [comment]
I reckon this is fixed in the new architecture and does not reproduce in v11.3. I will close this issue for now, but please reopen if anything pops up.
