### ISSUE TITLE
Grafana API does not work, could you help me figure it out?

### ISSUE THREAD

**Issue by xixikaikai** [grafana/grafana#7838]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Dashboards
Create / Update dashboard
POST /api/dashboards/db

- What Grafana version are you using?
4.0.2
- What datasource are you using?
prometheus
- What OS are you running grafana on?
mac pro 10.12.3
- What did you do?
POST /api/dashboards/db
as in page http://docs.grafana.org/reference/http_api/#create-update-dashboard
- What was the expected result?
create OK
- What happened instead?
<Response [404]>
{u'message': u'Not found'}

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Hi, yes we can help! 

But please open questions on the community site https://community.grafana.com
