### ISSUE TITLE
Task: Add tracking for the usage of Export configuration

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#78383]
**Goal**

Need to track users' actions on the export option to measure usage and take some steps to improve our "share" dialog options.

**Background**

Under the event of "dashboards_sharing_actions_clicked" on the Export section, the only action that has been tracked is the **"Save to File"** button (`item:save_export`). We need to define the events missing there.

**Task list**

- [ ] Export for sharing externally
- [ ] View JSON
- [ ] Copy to Clipboard

**Definition for these tracking events**

```
reportInteraction(
Event: 'dashboards_sharing_export_view_json_clicked',
type: 'external|internal'
)

reportInteraction(
Event: 'dashboards_sharing_export_save_json_clicked',
type: 'external|internal'
)

reportInteraction(
Event: 'dashboards_sharing_export_externally_clicked'
)
```

**Comment by evictorero** [comment]
Will be fixed in https://github.com/grafana/grafana/issues/78609
