### ISSUE TITLE
[Bug] Grafana ignores Data Source 'Default group by time' on first Dashboard load

### ISSUE THREAD

**Issue by notes-jj** [grafana/grafana#7839]
- What Grafana version are you using?

  dockerhub: grafana/grafana:4.1.2 --- 2017-02-19T12:42:59

- What datasource are you using?

  dockerhub: influxdb:1.2.0-alpine

- What OS are you running grafana on?

  debian:jessie

- What Browser:

  Windows Firefox 52.0 64-bit

- What did you do?

  Added a `Default group by time >3h` to data source. Added no `Group by time interval` to graph. Saved the dash board and changed the dash board. This will only happen if you switch to the dashboard from another dash board or press <kbd>SHIFT</kbd>-<kbd>Browser Reload Button</kbd>

  ![image](https://cloud.githubusercontent.com/assets/17141243/23947123/a37e2738-097d-11e7-9607-fe7cdfc74f9c.png)

  ![image](https://cloud.githubusercontent.com/assets/17141243/23947158/cfc4ba1e-097d-11e7-8232-acaa067a358c.png)

- What was the expected result?

  The resulting graph should be grouped by 3h.

  ![image](https://cloud.githubusercontent.com/assets/17141243/23947249/3626d2c4-097e-11e7-855a-fc87e30912d3.png)

- What happened instead?

  The Result is grouped by 5m.

  ![image](https://cloud.githubusercontent.com/assets/17141243/23947233/2894459c-097e-11e7-9650-141155542b8c.png)

  Query from InfluxDB Log:

        [I] 2017-03-15T11:40:25Z SELECT count(transCount) FROM dominotrans.autogen.transglobal WHERE time > now() - 1w GROUP BY time(5m) service=query
        [I] 2017-03-15T11:40:25Z SELECT count(count) FROM dominotrans.autogen.transdetail WHERE time > now() - 1w GROUP BY time(5m) service=query

- Workaround:

  Press the Grafana Reload Button: ![image](https://cloud.githubusercontent.com/assets/17141243/23947377/d2744904-097e-11e7-83f2-2d986ad04f27.png)

  Query from InfluxDB Log:

        [I] 2017-03-15T11:40:39Z SELECT count(count) FROM dominotrans.autogen.transdetail WHERE time > now() - 1w GROUP BY time(3h) service=query
        [I] 2017-03-15T11:40:39Z SELECT count(transCount) FROM dominotrans.autogen.transglobal WHERE time > now() - 1w GROUP BY time(3h) service=query

**Comment by torkelo** [comment]
your right! thanks for reporting this! Will fix asap.
