### ISSUE TITLE
Rewrite Code Editor to Monaco Editor ESM Version

### ISSUE THREAD

**Issue by asimonok** [grafana/grafana#78415]
**Why is this needed**:

In https://github.com/VolkovLabs/volkovlabs-dynamictext-panel we load external scripts and sometimes they find `window.define` function and work unexpected. It happens when page contains [CodeEditor](https://github.com/grafana/grafana/blob/259ecb1793e26ece176ffced237ef8e452b6f7f8/packages/grafana-ui/src/components/Monaco/CodeEditor.tsx#L17) It happens because the code editor component uses AMD Version - https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-amd.md which sets window.define function.

Seems to be there is also workaround inside - https://github.com/grafana/grafana/blob/259ecb1793e26ece176ffced237ef8e452b6f7f8/packages/grafana-runtime/src/utils/plugin.ts#L72

**What would you like to be added**:

To make scripts working we have to keep window.define is undefined. As an option, use Monaco Editor ESM Version - https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md#option-2-using-plain-webpack

**Who is this feature for?**

For plugins developers

**Comment by jackw** [comment]
Hello,
Many thanks for opening this issue.

> we load external scripts and sometimes they find window.define function and work unexpected.

Could you give an example of an external script that doesn't work as expected if `window.define` exists please? 

If a plugin is attempting to load external scripts that include a module loader (e.g.`requirejs`) the likelihood is it will silently bail if `window.define` exists and then the library won't load. From the perspective of plugins loading various external libraries this is virtually impossible to manage. Once the module loader loads, it will create `window.define` and then later if a different plugin instance (say another panel) wants to load a different library with a different module loader that relies on `window.define` the same issue will occur. I could very well be wrong but I think the only solution here would be to seek out alternative libraries that don't rely on module loaders. 🤔 

> To make scripts working we have to keep window.define is undefined. 

Unfortunately we cannot keep `window.define` undefined. The workaround you've highlighted for loading plugins via Systemjs has created a bug which [breaks plugin sourcemaps](https://github.com/grafana/grafana/issues/78259). As such we need SystemJS to set `window.define` so it can load plugins as intended. Coincidentally we are currently looking to solve this conflict by loading Monaco via ESM.

As a side note I think it's also worth mentioning that relying on any global variables within Grafana plugins is prone to failure as we do not consider them public APIs and can change without notice. Additionally ongoing plugin sandbox work will potentially prevent access to global variables and prevent loading external libraries all together in the future.

**Comment by asimonok** [comment]
@jackw

here is an example of script - https://cdn.jsdelivr.net/npm/chart.js
I suppose the most scripts have this code which allows to use it with various of module systems
```
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):(t="undefined"!=typeof globalThis?globalThis:t||self).Chart=e()}
```

Now I see the current approach won't work properly so we will look into the solution to fetch scripts with the local context which allows to keep global context is clean and will work for us. 

Thanks for the clarifying

**Comment by Zhen-dot** [comment]
Hi @jackw , I'm currently running into this issue as well where window.define is stopping me from importing utility libraries for other uses. In my case, we used to add the dayjs cdn directly to grafana's index.html, where we can access dayjs in our panel editors such as echarts plugins. Unfortunately this seems no longer possible unless i set window.define to undefined everytime I load a script, but im unsure if doing so would create any side affects.

As far as I can tell systemjs supports loading amd modules via a plugin, but I cant find any instructions on this. Could you provide any pointers as to how I can load dayjs using the existing Systemjs during runtime? Alternative methods for achieving this would be much appreciated as well. Cheers!

**Comment by jackw** [comment]
> In my case, we used to add the dayjs cdn directly to grafana's index.html, where we can access dayjs in our panel editors such as echarts plugins. Unfortunately this seems no longer possible unless i set window.define to undefined everytime I load a script, but im unsure if doing so would create any side affects.

Hello @Zhen-dot,
How were you adding it directly to grafanas index.html and how were you using it in a plugin? If you set window.define to undefined you will need to store a reference to the original window.define and put it back after you're done loading, otherwise it will break the plugin loader. e.g.

```js
let originalDefine = window.define;
delete window.define;

// load dayjs from cdn

window.define = originalDefine;
```

> As far as I can tell systemjs supports loading amd modules via a plugin, but I cant find any instructions on this. Could you provide any pointers as to how I can load dayjs using the existing Systemjs during runtime? Alternative methods for achieving this would be much appreciated as well. Cheers!

Is there a reason not to bundle dayjs with the plugin? It is not listed as an external in our create-plugin webpack config nor is it shared with plugins via systemjs. I would suggest you bundle it with the plugin rather than attempt to load it via cdn or make changes to the grafana index.html file.

That said, if bundling doesn't work for you, you should be able to load it via SystemJS in a plugin like so:

```js
const dayJS = await System.import('https://cdn.jsdelivr.net/npm/dayjs-ext@2.2.0/dayjs.min.js');

console.log(dayJS); // should log out the module 
```

See this [plain js example](https://stackblitz.com/edit/stackblitz-starters-qqicytfg?file=script.js).


Note that none of this is officially supported and SystemJS can be updated at anytime and may break the plugin usage. I would recommend you bundle the dependency if your plugin needs it.
