### ISSUE TITLE
[Grafana 4.1] - Multiple Series Error from Single Stat 

### ISSUE THREAD

**Issue by troyygan** [grafana/grafana#7841]
Hi,

Can someone help me resolve the issue from my grafana single stat. I want to set up a single stat dashboard that is updating every 30 minutes, same labels with different values every 30 mins. I 'm using prometheus db as a data source and the metrics are being updated every 30 mins from PromDB. From Options > Stat Value = Current ( This settings will fetch the latest value from promDB right? provided that there is an old metric existing).......Or single stat dashboard is not designed to handle multiple values from once metric. 

Thanks,
Troy

**Comment by torkelo** [comment]
It can handle multiple values, but only a single series. So your query needs to only return a single series (metric name and set of label / label values).

**Comment by troyygan** [comment]
Oh. So this is not possible? Please refer to the attached image. I have two series with the same metric name and set of labels but different values. What I am trying to achieve is to create a single stat dashboard that updates every 30 mins. 

![Uploading image.png…]()

**Comment by torkelo** [comment]
since the testrun label is different the result is two different series. Not sure if prometheus has way to combine different series without doing any aggregation, but maybe.

**Comment by troyygan** [comment]
Thanks @torkelo. I found the solution, tweaking on the prometheus side. :)
