### ISSUE TITLE
Frontend Platform: Migrate from aria-label e2e selectors to data-testid

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#78412]
Hi @grafana/grafana-frontend-platform!

A while back to changed to prefer using `data-testid` for E2E selectors instead of `aria-label`. There's only a few of these old `aria-label`-based selectors left, so we've made this list of files that your team owns so we can tidy them up 🙌.

For some guidance on how exactly to fix these, check out [this comment](https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512).

There are 17 issues over 15 files:

- [x] 1 issue in `packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/DateTimePickers/TimeRangeInput.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/Drawer/Drawer.tsx` 
- [x] 2 issues in `packages/grafana-ui/src/components/Menu/SubMenu.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/PageLayout/PageToolbar.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/PanelChrome/LoadingIndicator.tsx` 
- [x] 1 issue in `packages/grafana-ui/src/components/QueryField/QueryField.tsx` 
- [x] 1 issue in `public/app/core/components/AppChrome/News/NewsContainer.tsx` 
- [ ] 1 issue in `public/app/core/components/AppChrome/SectionNav/SectionNavItem.tsx` 
- [x] 1 issue in `public/app/core/components/ForgottenPassword/ChangePassword.tsx` 
- [x] 2 issues in `public/app/core/components/Login/LoginForm.tsx` 
- [x] 1 issue in `public/app/core/components/PageHeader/PanelHeaderMenuItem.tsx` 
- [x] 1 issue in `public/app/core/components/PasswordField/PasswordField.tsx` 
- [x] 1 issue in `public/app/core/components/QueryOperationRow/QueryOperationAction.tsx` 
- [x] 1 issue in `public/app/core/components/Select/OldFolderPicker.tsx`

**Comment by OmAximani0** [comment]
Hi, I want to work on this issue.

**Comment by joshhunt** [comment]
@OmAximani0 You're welcome to take a stab at this. Try to limit PRs to one file or 'area' at a time, just to limit scope. One thing to look out for is making sure unit tests pass before pushing up for quicker feedback - an easy way to do that is with something like `DEBUG_PRINT_LIMIT=0 yarn jest --findRelatedTests packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimeRangeContent.tsx`.

Also be sure to check out the guide here https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512 and my PR (with some other unrelated changes) https://github.com/grafana/grafana/pull/78399

**Comment by 0xJamin** [comment]
Hi @joshhunt  Is this still available for grabs?
There seems to be no PR available for it yet.

**Comment by kimconn** [comment]
Hi @joshhunt I opened a PR for the `TimeRangeInput.tsx` file [here](https://github.com/grafana/grafana/pull/79610#issuecomment-1859004276)

**Comment by 0xJamin** [comment]
Hi @joshhunt  it looks like the `aria-label` for `public/app/core/components/AppChrome/SectionNav/SectionNavItem.tsx
` is being used accessibility do we still have to change this?
