### ISSUE TITLE
BI: Migrate from aria-label e2e selectors to data-testid

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#78411]
Hi @grafana/grafana-bi-squad!

A while back to changed to prefer using `data-testid` for E2E selectors instead of `aria-label`. There's only a few of these old `aria-label`-based selectors left, so we've made this list of files that your team owns so we can tidy them up 🙌.

For some guidance on how exactly to fix these, check out [this comment](https://github.com/grafana/grafana/issues/36523#issuecomment-1819160512).

There are 2 issues over 1 file:

- [ ] 2 issues in `public/app/features/transformers/editors/ReduceTransformerEditor.tsx`

**Comment by baldm0mma** [comment]
Thanks @joshhunt, we'll try to take a look this week!

**Comment by baldm0mma** [comment]
Opened a draft PR here -> https://github.com/grafana/grafana/pull/78426. All updated tests pass.

**Comment by baldm0mma** [comment]
@joshhunt does this cover the bases? -> https://github.com/grafana/grafana/pull/78426
