### ISSUE TITLE
Flux Datasource: Incorrect data is displayed when using join functions.

### ISSUE THREAD

**Issue by levinkerschberger** [grafana/grafana#78429]
## Context
I am currently trying to build a dashboard based on the data output from the /metrics endpoint.
Unfortunately, the storage_bucket_X meaurements do not show the name of the bucket, but its ID.
With a left-outer join with the output of the query buckets() it would be easy to add the name as desired.
This works wonderfully in Influx itself.

Okey, lets try this in Grafana

### Example
Unlike in Influx itself, with the following Query, I get this Error-Message:
`invalid: error in building plan while starting program: error in join function - some expressions are not yet supported in the `on` parameter: illegal expression type in join predicate: StringLiteral
`
```
import "join"
left = from(bucket: "scraper")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "storage_bucket_measurement_num")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> last()
  |> drop(columns: ["_time", "_start", "_stop"])


right = buckets()
|> drop(columns: ["organizationID", "retentionPolicy", "retentionPeriod"])

join.left(
left: left |> group(), 
right: right,
on:((l,r) => l.bucket == r.id), 
as: ((l, r) => ({l with name: r.name}))
)
```

Then I tried to create a new Column with the values of the column `bucket` and things started to get confusing.
While Influx still perfectly generates, what I expect, thats the output, which Grafana brings up
```
import "join"
left = from(bucket: "scraper")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "storage_bucket_measurement_num")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> last()
  |> drop(columns: ["_time", "_start", "_stop"])
  |> map(fn: (r) => ({r with bucketID: r.bucket}))


right = buckets()
|> drop(columns: ["organizationID", "retentionPolicy", "retentionPeriod"])

join.left(
left: left |> group(), 
right: right,
on:((l,r) => l.bucketID == r.id), 
as: ((l, r) => ({l with name: r.name}))
)
```
![image](https://github.com/grafana/grafana/assets/126667618/39130974-0c8f-48cf-a8b2-8cde0f4a319b)
Why does Grafana puts the name of one of the buckets into the BucketID-Field now?
Interestingly enough, that even without the join-operation, grafana knows one of the Bucket-Names now?
```
import "join"
left = from(bucket: "scraper")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "storage_bucket_measurement_num")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> last()
  |> drop(columns: ["_time", "_start", "_stop"])
  |> map(fn: (r) => ({r with bucketID: r.bucket}))
  |>yield(name: "yield")
```
![image](https://github.com/grafana/grafana/assets/126667618/2632ad1a-0525-40ea-b804-e3970425afe2)

Would be awesome, if someone could determine the causes of this behavior!
Until then, I´ll hardcode the Bucket-Names with a display overwrite. Unfortunaltly, that´s not the solution I need, cause we´re deploying our dashboards on multiple stages via provisioning...

#### Results of `buckets()`:

|table|name       |id              |organizationID  |retentionPolicy|retentionPeriod|
|-----|-----------|----------------|----------------|---------------|---------------|
|0    |_monitoring|b07aee8c9d4f688d|e32e6f553bbb513c|               |604800000000000|
|0    |_tasks     |ada429ad4077fd3f|e32e6f553bbb513c|               |259200000000000|
|0    |scraper    |6d18c249e8d1bd98|e32e6f553bbb513c|               |0              |
|0    |telegraf   |66cc7e18df4fb1a7|e32e6f553bbb513c|               |0              |

#### Results of storage_bucket_measurements
`
from(bucket: "scraper")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "storage_bucket_measurement_num")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
`
|table|_start     |_stop           |_time           |_value         |_field         |_measurement                  |bucket          |
|-----|-----------|----------------|----------------|---------------|---------------|------------------------------|----------------|
|0    |2023-11-20T09:11:58.944204292Z|2023-11-20T21:11:58.944204292Z|2023-11-20T20:22:00Z|8              |gauge          |storage_bucket_measurement_num|66cc7e18df4fb1a7|
|0    |2023-11-20T09:11:58.944204292Z|2023-11-20T21:11:58.944204292Z|2023-11-20T20:24:00Z|8              |gauge          |storage_bucket_measurement_num|66cc7e18df4fb1a7|
|0    |2023-11-20T09:11:58.944204292Z|2023-11-20T21:11:58.944204292Z|2023-11-20T20:26:00Z|8              |gauge          |storage_bucket_measurement_num|66cc7e18df4fb1a7|
|0    |2023-11-20T09:11:58.944204292Z|2023-11-20T21:11:58.944204292Z|2023-11-20T20:28:00Z|8              |gauge          |storage_bucket_measurement_num|66cc7e18df4fb1a7|
|0    |2023-11-20T09:11:58.944204292Z|2023-11-20T21:11:58.944204292Z|2023-11-20T20:30:00Z|8              |gauge          |storage_bucket_measurement_num|66cc7e18df4fb1a7|

#### Results of my Query with the Join-Operation:
```
import "join"
left = from(bucket: "scraper")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "storage_bucket_measurement_num")
  |> filter(fn: (r) => r["_field"] == "gauge")
  |> last()
  |> group(columns: ["bucket"])
  |> map(fn: (r) => ({r with bucketID: r.bucket}))


right = buckets()
|> drop(columns: ["organizationID", "retentionPolicy", "retentionPeriod"])

join.left(
left: left |> group(), 
right: right,
on:((l,r) => l.bucketID == r.id), 
as: (l, r) => ({l with name: r.name}),
)
```

|table|_field     |_measurement    |_start          |_stop          |_time          |_value                        |bucket          |bucketID        |name    |
|-----|-----------|----------------|----------------|---------------|---------------|------------------------------|----------------|----------------|--------|
|0    |gauge      |storage_bucket_measurement_num|2023-11-20T09:16:52.55027947Z|2023-11-20T21:16:52.55027947Z|2023-11-20T21:16:46.4390173Z|9                             |66cc7e18df4fb1a7|66cc7e18df4fb1a7|telegraf|
|0    |gauge      |storage_bucket_measurement_num|2023-11-20T09:16:52.55027947Z|2023-11-20T21:16:52.55027947Z|2023-11-20T21:16:46.4390173Z|121                           |6d18c249e8d1bd98|6d18c249e8d1bd98|scraper |

### Did this work before?

Never tried with another version...

### How do we reproduce it?

Just use my example queries...

### Environment (with versions)?

Grafana: Version 9.5.3 & Latest
OS: Docke-Image & Linux
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influx - Flux Datasource

**Comment by tonypowa** [comment]
thank you for creating such a detailed issue @levinkerschberger 

I am forwarding this issue for review

**Comment by itsmylife** [comment]
Hi @levinkerschberger. Thanks for the detailed report. Please help me understand the following:
- You are trying to query `on:((l,r) => l.bucket == r.id),` something that is not exist. The query result doesn't have a bucket field as you show in `Results of storage_bucket_measurements`. How would this work? 

- Could you please share what Influx gives you when you run the same query?
