### ISSUE TITLE
[FEATURE REQUEST] Shareable single graphs

### ISSUE THREAD

**Issue by fzakaria** [grafana/grafana#7845]
It would be great, to rather just limit graphs to dashboards, to be able to create one off graphs.
Sometimes, I'd like to share metrics / investigations that don't pertain to a dashboard.

Would be cool to just say "new graph" and have it generate some friendly name or UUID
(not searchable) but you can share the link.
 Similar to a pastebin.

**Comment by torkelo** [comment]
good idea, we have a very similar issue for that already: https://github.com/grafana/grafana/issues/1803

**Comment by fzakaria** [comment]
@torkelo great thanks -- i'll give my 2cents there.
I also just saw some of the new developer docs and they are much needed.

I wrote for my company a Grafana datasource plugin -- and a lot of it was trial and error from looking at other examples (especially the partials). The added documentation is helpful.
(I wonder if there is a way to export typescript type definition files for the main components so it makes development easier)
