### ISSUE TITLE
Onboarding panel clips poorly on narrow screens

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#78451]
The onboarding panel on the default OSS homepage dashboard gets clipped poorly on narrow screens. It's especially noticable with the new docked menu.

![image](https://github.com/grafana/grafana/assets/46142/17ba30c5-4249-44cc-8de3-530c24ea7c24)

**Comment by amy-super** [comment]
While we're here :) it would be great to be able to collect number of clicks on each of the 5 onboarding cards:
- Grafana fundamentals
- Add your first data source
- Create your first dashboard
- Create users and teams
- Find and install plugins

We'll be ideating on a new home page soon, so collecting this data will help us understand if these cards are useful.
