### ISSUE TITLE
[Feature request] Annotations for row/panel integrated with repeating rows/panels

### ISSUE THREAD

**Issue by Rickkwa** [grafana/grafana#7847]
Please include this information:
- What Grafana version are you using? Version 4.1.1
- What datasource are you using? Zabbix and Simple JSON

Right now annotations are on the dashboard level. I would propose an option to create annotation on the row/panel level. 

The big advantage for this would be that the annotation can use a template variable that is being repeated on. For example, I have a templating variable, $foo, with the multi-select option on and it has three possible values. Then I create a row that repeats on $foo; three rows are created when I select all. I can then create a row-level Simple JSON annotation that uses the $foo variable in the query. It will send a single value for $foo (instead of all 3) since we're repeating on this variable. That way, all 3 rows will display their own relevant annotations, instead of annotations for everything since the query is different per row.

**Comment by torkelo** [comment]
Thanks for the feedback! we do want to add something like this in the future (or when a PR comes in).

Will close this as we a similar issue already https://github.com/grafana/grafana/issues/717
