### ISSUE TITLE
Cloudwatch: Add missing metrics for AWS/IVSRealtime workspace

### ISSUE THREAD

**Issue by muhfarsh** [grafana/grafana#78483]
### What happened?

Hi, cloudwatch is missing metrics for the new AWS/IVSRealtime namespace.
List of missing metrics according to AWS IVS Documentation:
DroppedFrames, PacketLoss, PublishBitrate, PublishBitrate, Publishers, PublishResolution, SubscribeBitrate and Subscribers.

All of these metrics are under the dimension : Stages

These metrics can be found in this AWS IVS Documentation: https://docs.aws.amazon.com/ivs/latest/RealTimeUserGuide/stage-health.html

### What did you expect to happen?

Metrics DroppedFrames, PacketLoss, PublishBitrate, PublishBitrate, Publishers, PublishResolution, SubscribeBitrate and Subscribers should be present in Grafana Cloudwatch datasource.

### Did this work before?

AWS/IVSRealtime is a new namespace.

### How do we reproduce it?

How to reproduce it (as minimally and precisely as possible):

1. Open Grafana Explorer
2. Choose Cloudwatch datasource
3. AWS/IVSRealtime namespace is missing alongside its list of metrics

### Environment (with versions)?

Grafana: 9.4
OS: Mac
Browser: Chrome, Safari

### Grafana platform?

Other

### Datasource(s)?

Cloudwatch

**Comment by usmangt** [comment]
Hi @muhfarsh,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by muhfarsh** [comment]
thanks @usmangt ! happy to provide anything you guys need!

**Comment by muhfarsh** [comment]
hi there @idastambuk thank you so much for working on this and finishing this. It seems that this will only be merged for the grafana 10.x branch. Any way this can be ported to grafana 9.4, so our customers can use it without doing a upgrade?
