### ISSUE TITLE
[Bug] Quick ranges doesn't work fine for periods shorter than 6 hour

### ISSUE THREAD

**Issue by dragonxtek** [grafana/grafana#7850]
I'm using Grafana v4.2.0-beta1 (commit: ffe0ecf), Influxdb and Ubuntu 16.04
I'm plotting the info every 5 seconds, but if I try show it for periods shorter than 6 hours (3 hours, 1 hour, 30 min, 15 min or 1 min), grafana doesn't show the plot, but shows the information.

Data at 9:20 for last 6 hours
![selection_052](https://cloud.githubusercontent.com/assets/10552658/23997213/2dad8cb2-0a2f-11e7-95c6-984bb379fd2a.png)
Data at 9:20 for last 3 hours (doesn't show the plot)
![selection_053](https://cloud.githubusercontent.com/assets/10552658/23997212/2d917fae-0a2f-11e7-9921-42dbe0a8b2ff.png)

**Comment by dragonxtek** [comment]
I get the data (input or output bytes) from a switch and it respectives ports.
I write in influxdb every 10 seconds.
These are the sentences:
![selection_036](https://cloud.githubusercontent.com/assets/10552658/23999980/b92870f0-0a38-11e7-8b8b-3b46fae884f5.png)
I don't thinks that is a query or a data issue. 
Maybe is a refresh issue to plot the data...

**Comment by martinbalint** [comment]
I have same issue with influxdb-1.2.0-1.x86_64 and grafana-4.1.2-1486989747.x86_64
Tried Chrome and IE on Windows 10. Looks like some rendering issue.

Data from influxdb looks like this for "Last 3 hours".
Draw Mode: Lines = no lines shown, Bars and Points are shown.
![image](https://cloud.githubusercontent.com/assets/2743083/24000997/3336bd92-0a5d-11e7-800b-ebfbc59197d0.png)

**Comment by martinbalint** [comment]
Also noticed, when Null value option is other than null, line gets drawn.

**Comment by dragonxtek** [comment]
I forgot it. I tested on Chrome and Firefox for Ubuntu.
You're right, for values none, 0 or previous I don't have the issue. 
It's a fill(null) issue for periods shorter than 6 hours

**Comment by DeltaEvo** [comment]
I have same issue grafana v4.1.2 and v4.1.1

**Comment by dragonxtek** [comment]
It's solved on version 4.2.0 (released 3 hours ago)

**Comment by DeltaEvo** [comment]
@dragonxtek It's not solved for me

**Comment by dragonxtek** [comment]
I need to change, in my case, time($__interval) by time(10s)
![selection_049](https://cloud.githubusercontent.com/assets/10552658/24200014/6c504be8-0eea-11e7-8106-0365d2aa03af.png)

![selection_051](https://cloud.githubusercontent.com/assets/10552658/24200163/f3742c3e-0eea-11e7-89d5-7e276f7de4d6.png)

**Comment by daniellee** [comment]
There is a group by time interval that should match the frequency of how often you write the data to InfluxDB:

![image](https://cloud.githubusercontent.com/assets/434655/24206003/495029c8-0f1d-11e7-8339-295c7199aeb3.png)
