### ISSUE TITLE
Alerting: After upgrading from 10.1.4 to 10.2.1 not able to edit silences 

### ISSUE THREAD

**Issue by mvnarsing** [grafana/grafana#78509]
### What happened?

We upgraded from 10.1.4 to 10.2.1 and noticed that we are not able to edit the silences as option is no longer available.

![Screenshot 2023-11-21 at 5 33 24 PM](https://github.com/grafana/grafana/assets/38599861/789a0ea1-1e94-4d6a-9270-c81f3dd702f8)

### What did you expect to happen?

Below is the image from old version 10.1.4 where we can see edit option for silences
![Screenshot 2023-11-21 at 5 46 01 PM](https://github.com/grafana/grafana/assets/38599861/61cb8663-51c6-441a-aa28-8ed4939efdbc)

### Did this work before?

yes as mentioned in what you expect to happen section above

### How do we reproduce it?

1. create a new silence
2. upgrade to 10.2.1
3. Try to edit the silence created

### Environment (with versions)?

Grafana: 10.2
OS: grafana/grafana:10.2.0
Browser: chrome or safari

### Grafana platform?

Kubernetes

**Comment by Sinjo** [comment]
Hey 👋🏻 

We also ran into this one at PlanetScale and it looks like #72626 might be the culprit.

As of that PR, the ability to edit a silence has been [gated behind the presence of the configuration API](https://github.com/grafana/grafana/blob/71f32d4e19cdac029bd702f130961e64082a8101/public/app/features/alerting/unified/hooks/useAbilities.ts#L175-L178) which [only Mimir and Cortex](https://github.com/grafana/grafana/blob/71f32d4e19cdac029bd702f130961e64082a8101/public/app/features/alerting/unified/state/AlertmanagerContext.tsx#L102-L112) have.

I think this functionality should have a different feature gate or potentially not have a gate at all (if it's something that all Alertmanager implementations are expected to support).

**Comment by dragoangel** [comment]
> Hey 👋🏻
> 
> We also ran into this one at PlanetScale and it looks like #72626 might be the culprit.
> 
> As of that PR, the ability to edit a silence has been [gated behind the presence of the configuration API](https://github.com/grafana/grafana/blob/71f32d4e19cdac029bd702f130961e64082a8101/public/app/features/alerting/unified/hooks/useAbilities.ts#L175-L178) which [only Mimir and Cortex](https://github.com/grafana/grafana/blob/71f32d4e19cdac029bd702f130961e64082a8101/public/app/features/alerting/unified/state/AlertmanagerContext.tsx#L102-L112) have.
> 
> I think this functionality should have a different feature gate or potentially not have a gate at all (if it's something that all Alertmanager implementations are expected to support).

Yep, it should not be applied to Prometheus Alertmanager

**Comment by gillesdemey** [comment]
Oops, looks like this one snuck in during a refactor and we didn't catch it – we'll have a PR up soon :)
