### ISSUE TITLE
Speed up Grafana tips & tricks

### ISSUE THREAD

**Issue by Kaszal** [grafana/grafana#7851]
Hi,

I would like to speed up Grafana searching, filtering etc. my source is elastic and maybe someone knows (has some tricks) how to speed up Grafana? (sth like increase java memory etc)

**Comment by torkelo** [comment]
What is you find that is slow? If you want to speed up your Elasticsearch server then there should be plenty of tips and tricks for how to speed up Elasticsearch (index tuning, and ES settings etc). 

Please post questions on the community site: https://community.grafana.com/
