### ISSUE TITLE
Panel cannot click the copy button of the sharing link in ifream

### ISSUE THREAD

**Issue by ibarryyan** [grafana/grafana#78519]
### What happened?

Panel cannot click the copy button of the sharing link in ifream

### What did you expect to happen?

Panel cannot click the copy button of the sharing link in ifream

### Did this work before?

Place Grafana in ifream

### How do we reproduce it?

1.Place Grafana in ifream
2.Select Panel click share
3.Click Link Copy Button

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:v9.5.13
OS:Linux
Browser:Google Chrome v119.0.6045.124
 

### Grafana platform?

None

**Comment by biubiubiuboomboomboom** [comment]
Maybe you can check this configuration.

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_embedding

**Comment by tonypowa** [comment]
hi @ibarryyan 

did the advice from @biubiubiuboomboomboom  helped ? If not:

Are there any console errors in the browser when you attempt to click the copy button? To check this, please open the browser's developer tools (usually F12) and navigate to the 'Console' tab.

f possible, could you provide a screenshot or video demonstrating the issue?

thank you

**Comment by ibarryyan** [comment]
@tonypowa Thanks for your reply！
When clicking the copy button, there were no errors, but there was no prompt for success or successful copying, which felt like the JS function was invalid.

Operation steps：
(1)Embed Grafana into ifeam and create charts
(2)Select a share button for a chart
(3)After selecting the link option, click on copy

The version I am using is v9.5.2. If there are no issues with your operation, please let me know the version.

**Comment by evictorero** [comment]
This problem is not related to Grafana but to Browser security policies. You can add `allow="clipboard-read; clipboard-write"` to the iframe, and it will work. However, we don't recommend embedding Grafana in an iframe for security reasons.
