### ISSUE TITLE
[Feature request] additional options for elapsed time formatting in column styles

### ISSUE THREAD

**Issue by 3IWOH** [grafana/grafana#7852]
We track downtime in some of our tables. I currently store this value as seconds and use the column styles to format this. It works ok, however representing time with decimals is not intuitive to many users. It would be great to offer the ability to format elapsed time as HH:mm:ss , etc.

![image](https://cloud.githubusercontent.com/assets/7918433/24004547/d5b128ee-0a23-11e7-9ffd-2c3d441ed0b6.png)

**Comment by daniellee** [comment]
Sounds like a good feature request to me.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
