### ISSUE TITLE
[Bug] Grafana Internal Metric for Alerts returns strage results

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#7853]
- What Grafana version are you using?
Grafana v4.1.2 (commit: v4.1.2)
- What datasource are you using?
Both Graphite for the alerts and the monitoring metrics
- What OS are you running grafana on?
Docker, "latest"-Tag
- What did you do?
I'm using the Grafana features to send the Grafana internal metrics to Graphite. Afterwards I display them in a dashboard. See image below, the graph uses stacking.
- What was the expected result?
The number of alerts (we have 30+) should somehow sum up to a constant and usefull result.
- What happened instead?
The number of "OK" alerts isn't constant, is not the amount of alerts I really have and summing it up with other states doesn't helper either.

![image](https://cloud.githubusercontent.com/assets/648527/24008262/6fb1314e-0a71-11e7-8153-e67d10ed8e52.png)

I more or less wonder if this is intended behavior and if I should be able to get useful results. Maybe I'm doing the query the wrong way, using "summarize last" might not be the best chooice, but the result is far off from my expectations.

**Comment by daniellee** [comment]
Just looked at our internal alerting stats and they seem correct. 

Our stats:
- ~60 alerts
- Most of them are evaluated every 60 seconds (a few that have longer intervals)

Here is the graph for state_ok, summarized with 1 minute (which matches our 60 second interval):

![image](https://cloud.githubusercontent.com/assets/434655/24054036/266343cc-0b3b-11e7-952d-9eafee0c3f81.png)

Here is the same graph summarized every 5m:

![image](https://cloud.githubusercontent.com/assets/434655/24054191/a4f26da8-0b3b-11e7-9fc0-c32fc110aa0c.png)

And the math seems to be correct here too - ~60 alert evaluations per minute * 5 = ~300 alerts/5m

How often are your alerts typically evaluated?

**Comment by torkelo** [comment]
it's a counter for alerting evaluation results, so it will fluctuate slightly based on how often rules are evaluated and how often you send the internal metrics to graphite

**Comment by Fox32** [comment]
Thanks for clarifying that. 
But the amount of alerts in each state, independent from the evaluation would be a nice metric, too.
