### ISSUE TITLE
Azure Monitor: Azure / Insights /Storage Accounts dashboard not working

### ISSUE THREAD

**Issue by yves-chan** [grafana/grafana#78547]
### What happened?

1. Load the Azure /Insights /Storage Accounts dashboard from the Azure Monitor Dashboard folder.
2. Observe the broken panels:
![image](https://github.com/grafana/grafana/assets/7664931/06a79df8-4f28-4cb2-992c-7de5b75a4a44)
The error is: 
```
A
request failed, status: 400 Bad Request, error:
Status: 500
Object
code:"BadRequest"
message:"Microsoft.Storage/storageAccounts/aulrgdiag is not a supported platform metric namespace, supported ones are Microsoft.Cdn/profiles,Microsoft.Cdn/CdnWebApplicationFirewallPolicies..."
```

When clicking into one of the broken panels, (ie: Transactions by Storage Type)
![image](https://github.com/grafana/grafana/assets/7664931/7103a535-633e-4af2-a342-8371a50ee8b4)
it seems to set the namespace to `$ns/$resource` in realtime, but the metricNamespace in the dashboard JSON should be this:

```
...
            "metricName": "Transactions",
            "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
            "resourceGroup": "$rg",
            "resourceName": "$resource/default",
            "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
            ...
```
I had a look through the dashboard history and I don't think there was anything changed in the content itself so I'm assuming it's a regression on some conversion that happens during query time?

### What did you expect to happen?

Dashboard loads without issues

### Did this work before?

Yes, but I do not recall

### How do we reproduce it?

See description

### Is the bug inside a dashboard panel?

This is the template from Azure Monitor

### Environment (with versions)?

Grafana: 9.5.13
OS: Windows
Browser: Windows

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @yves-chan,

Thanks for opening this issue.

Grafana's current latest stable version is 10.2.0 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements have been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).
