### ISSUE TITLE
Canvas: Selected connection not appearing in inline editor

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#78564]
When selecting a connection in canvas while using the inline editor, the user is only able to delete the connection and does not see the "Selected connection" editor pane (where they can modify the size / color of the connection). This may be a regression.

https://github.com/grafana/grafana/assets/22381771/403f9561-d983-4f70-81d0-11ae2d37b1a0

**Comment by nmarrs** [comment]
It turns out this is not a regression but a known limitation based on original implementation -> https://github.com/grafana/grafana/pull/64360

**Comment by R1d3rBG** [comment]
Hello, is it possbile this to be enabled in Azure Grafana?
