### ISSUE TITLE
Logs Dashboard: Default display of the first 1000 characters when log lines are too long

### ISSUE THREAD

**Issue by honganan** [grafana/grafana#78572]
**Why is this needed**:

When log line is too long(like Java error log contains stack), showing all content by default will not be a good user experience.

**What would you like to be added**:

Display first of 1000 characters if log lines are too long, and give a toggle switch button to show full lines as if user want to watch the original full lines. The effect is as follows:

![image](https://github.com/grafana/grafana/assets/4892550/c29e8816-f767-4522-bc00-1fb08473005c)

**Who is this feature for?**

Logs panel users

**Comment by honganan** [comment]
I need help for confirming if this is needed and compatible. If it's ok, I will send a PR.

**Comment by matyax** [comment]
@honganan for multi-lines logs like stack traces, the "wrap lines" options now controls that. Thank you for reporting this issue.
