### ISSUE TITLE
grafana should handle "snapshot post -> 413 Request Entity Too Large" better

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#7857]
If you post a snapshot and the request results in "413 Request Entity Too Large", you get an ugly error in grafana.
It would be better if grafana would handle this more gracefully and present a warning dialog to the user. something along the lines of
"there's too much data in this dashboard, please select a narrower timerange, or adjust which data is shown"

**Comment by yarix** [comment]
is it related \ due to #3176 ? (using proxy?)
