### ISSUE TITLE
Y-axis values not easily readable when using logarithmic base 10 scale

### ISSUE THREAD

**Issue by tjb36** [grafana/grafana#78585]
### What happened?

Created a graph panel with logarithmic base 10 y-axis. The y-axis values are squashed together and unreadable:

![Clipboard03](https://github.com/grafana/grafana/assets/43373700/23c3f7c4-1d28-43f6-bd46-bac25354c7d0)

### What did you expect to happen?

I expected y-axis values to be clearly seperated and readable. 

### Did this work before?

This was the case with previous versions of Grafana (v5):

![Clipboard02](https://github.com/grafana/grafana/assets/43373700/3632b8a6-00de-4ab2-b9af-281aa75a5277)

### How do we reproduce it?

1. Create a graph with logarithmic base 10 yaxis on Grafana v10.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10
OS: RedHat
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB

**Comment by lukasztyrala** [comment]
Hi @tjb36, between v5 and v10 we deprecated Angular panels (Graph panel) in favor of new React panels (Time series panel).

Can you please confirm if the problem with overlapping y-axis labels is related to the Graph (old) or Time series (new) panel?

**Comment by tjb36** [comment]
Yes, my apologies. I was running 10.1 instead of 10.2. It is indeed fixed. 
Sorry for wasting your time!
