### ISSUE TITLE
Unable to install grafana

### ISSUE THREAD

**Issue by sLuvpreet33** [grafana/grafana#7858]
My system is 64 bit, still it isn't getting installed. I am following the official garfana page.

It says, 

`luvpreet@luvpreet-vm:~/django/gunitest$ sudo dpkg -i grafana_4.1.2-1486989747_amd64.deb`
`dpkg: error processing archive grafana_4.1.2-1486989747_amd64.deb (--install):`
 `package architecture (amd64) does not match system (i386)`
`Errors were encountered while processing:`
 `grafana_4.1.2-1486989747_amd64.deb`

But system is 64 bit.

`luvpreet@luvpreet-vm:~/django/gunitest$ uname -a`
`Linux luvpreet-vm 4.4.0-66-generic #87~14.04.1-Ubuntu SMP Fri Mar 3 17:33:10 UTC 2017 i686 i686 i686 GNU/Linux`

**Comment by daniellee** [comment]
It looks like you have 32-bit Ubuntu:

http://askubuntu.com/a/444401/498572

Closing but will reopen if that is not the case.

**Comment by sLuvpreet33** [comment]
I was trying to install it in my VM machine. I think that was creating the
problem.
It works in my main machine.
