### ISSUE TITLE
Loki: Forward search

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#78588]
### Discussed in https://github.com/grafana/grafana/discussions/56850

<div type='discussions-op-text'>

<sup>Originally posted by **cyriltovena** November 14, 2019</sup>

**What would you like to be added**:

I want an option to search forward within logs currently we can only do backward.

**Why is this needed**:

Backward is nice when you're looking at the last logs of an applications but forward is more useful when you're scanning past incidents. 

It would be also nice to be able to page from the last logs received so we can move within the same timeframe but show missing logs cut by the limit.

Loki API support both forward and backward search.</div>

**Comment by jasuade** [comment]
Hey team, @ivanahuckova we would like to extend this also to ES datasource, would that be possible? Should we create another issue?

**Comment by ivanahuckova** [comment]
@jasuade, yes please, could you create a new issue for elasticsearch (if there is not one yet). 🙂

**Comment by steveteuber** [comment]
@ivanahuckova I think this issue can be closed. Fixed by #91181.

**Comment by jlippmann** [comment]
[celebrate]     Jens Lippmann reacted to your message:
________________________________
