### ISSUE TITLE
[Bug] Limited amount of metrics to show on the graph

### ISSUE THREAD

**Issue by dragonxtek** [grafana/grafana#7860]
I'm using Grafana v4.2.0-beta1 (commit: ffe0ecf) with InfluxDB 1.2.1 on Ubuntu 16.04 64 bits.
When I try to show more than 5 metrics (I have 7 metrics), only appears the first 5 metrics that I have configurated on Grafana.

![selection_037](https://cloud.githubusercontent.com/assets/10552658/24019940/d9c3513c-0a78-11e7-8076-9549fb7a2c8e.png)

If I turn-off the first and second metrics, grafana shows the following 5 metrics.

![selection_039](https://cloud.githubusercontent.com/assets/10552658/24019946/e5ced0dc-0a78-11e7-828a-90b507b060cb.png)

Why I can't see all of them?
I don't remember well, but I think with influxdb 0.10.0 (default version in ubuntu) I hadn't this issue.

**Comment by lpic10** [comment]
This is due a to change in InfluxDB, see #7380 
Latest release of InfluxDB fixes this.

**Comment by dragonxtek** [comment]
Changing max-row-limit to 0 in /etc/influxdb/influxdb.conf solves the issue. Thanks

**Comment by nerocide** [comment]
Like lots of folks i had a problem because of influxdb's HTTP max-row-limit while graphing with grafana.

Can somebody explain me this, maybe is missed something on my setup, but I don't understand why grafana is not quering with a time parameter (WHERE TIME =/</>.... ) but ask for the whole entries, then grafana display the entries according to it's time frame filters.
Thanks

**Comment by torkelo** [comment]
@nerocide what do you mean? Of course Grafana builds InfluxDB queries with time filters, not having time filters in the query would be crazy slow and unusable. And even if you do not use the Grafana built in InfluxDB query builder UI and switch to raw query mode you have the `WHERE $timeFilter` part that Grafana will replace with the current active time range. 

InfluxDB changed max-row-limit to a very low value (think they reverted this change as it has had such bad impact). The low value can easily be hit as a large time range will require a lot of rows to be read from the influxdb database (max-row-limit is not the same as amount of data returned to Grafana as max-row-limit is number of rows read before InfluxDB group by aggregations are processed)

**Comment by nerocide** [comment]
@torkelo here is an example. 

**Json extract of the source query**
` "query": "SELECT \"value\",\"warning\",\"critical\" FROM \"metric_cpu_prct_used\" WHERE \"host_name\" =~ /$hostname$/",
`

**From influxdb logs**
`avril 03 14:15:26 fr-eme1-u044.group.wan influxd[26821]: [httpd] 10.50.4.254 - quser [03/Apr/2017:14:15:26  0200] "GET /query?db=shinken&epoch=ms&p=[REDACTED]&q=SELECT "value","warning","critical" FROM "metric_cpu_prct_used" WHERE "host_name" =~ /fr-eme1-u102$/&u=quser HTTP/1.1" 200 58620 "http://fr-eme1-u044.skg.clients:8080/dashboard/db/skg_maindashboard?var-hostname=fr-eme1-u102&var-Disk1=Swap_space&var-Disk2=Swap_space&var-Device=dm-0&var-Process=&from=now/d&to=now" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 `

Once again i might have missed something on the setup. I did use the raw query editor but didn't insert `WHERE $timeFilter ` (i'll try right now)
I can confirm it can get slow from time to time.

**Comment by nerocide** [comment]
@torkelo works a LOT better with the $timeFiler variable.
I don't know why and i how i forgot to check that before.
Anyway thanks i lot for correcting my "genuis" mistake
