### ISSUE TITLE
Google Cloud Monitoring Multivalue variables not working in PromQL Queries

### ISSUE THREAD

**Issue by f0o** [grafana/grafana#78619]
### What happened?

When I create a variable that allows multiple selections and attempt to include it in a PromQL query such as foo{label~="$values"} it becomes:

foo{label~="{bar,baz}"}

This is not valid PromQL and the query returns empty.

The correct way would be to use foo{label~="bar|baz"} but I have no idea how to instruct the plugin to construct this type of multivalue representation.

### What did you expect to happen?

Multivalue labels to work correctly

### Did this work before?

No

### How do we reproduce it?

1. Create Multivalue Variable based on GCP's Monitoring Label Values equivalent
2. Create Query using multivalue variable
3. Observe blank graph

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Google Cloud Monitoring 1.0.0

**Comment by bossinc** [comment]
This should help for now https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#pipe

But pipes should be default for PromQL queries. I'll add this to the backlog!

**Comment by aangelisc** [comment]
Hi @f0o, I have a PR open to fix this issue now 😊
