### ISSUE TITLE
[Feature Request] Add units and fix numeric precision for Alert data

### ISSUE THREAD

**Issue by dugeem** [grafana/grafana#7861]
Please include this information:
- What Grafana version are you using? v4.1.1
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 6.8
- What did you do? View Alert for % data
- What was the expected result? Alert data field -> 30.0 % (example)
- What happened instead? Alert data field -> 29.977942725422 (example)

Currently the data in Alerts has no unit suffix which makes the data harder to interpret when Alerts are viewed elsewhere (e.g. Slack, OpsGenie). Also, the numeric data has an unnecessary level of floating precision (e.g. 29.977942725422) when 2-4 significant digits would generally be sufficient (e.g. 30.0). Ideally the Alert data precision could be inherited from Decimals setting (under Graph tab Legend).

**Comment by daniellee** [comment]
Sounds like a good idea.

**Comment by krzysbaranski** [comment]
duplicate #6511
