### ISSUE TITLE
[Bug] Alert Notification type OpsGenie misspelling

### ISSUE THREAD

**Issue by dugeem** [grafana/grafana#7862]
Please include this information:
- What Grafana version are you using? v4.1.1
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 6.8
- What did you do? Crate new Alert Notification of type OpsGenie, then hover over OpsGenie setting Auto close incidents
- What was the expected result? text containing OpsGenie
- What happened instead? text containing OpseGenie

 Misspelling of OpsGenie

**Comment by daniellee** [comment]
Closed by #7867
