### ISSUE TITLE
Panel/Time series: The last value in plot does not match Table view 

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#78626]
### What happened?

I have a time series panel in Grafana with the Amazon Athena plugin, see below playground:
https://grafana.csselectronics.stellarhosted.com/d/canmod-input/canmod-input-test?from=1699869308000&to=1699869481000&orgId=1

The aim is to show a plot of the average value of a specific signal as per the panel. When setting up the query and looking at the Table View, everything looks as expected (values fluctuating around ~4700-5200 approximately throughout). Notice how in the table view, the last value is showing as 4781, which is as expected:
![image](https://github.com/grafana/grafana/assets/26184427/2be3f381-13d3-45c8-a5a4-288964b837b5)

However, when changing to the Time Series panel view, I get a strange result where the 'max' value of the last aggregation observation is shown, resulting in a strange plot as below:
![image](https://github.com/grafana/grafana/assets/26184427/7c5c999a-0782-4ae1-a2fb-141c5dd24817)

Notice in particular that the last observation is showing as the value 9860 and that the timestamp is 1 second after the Table View last timestamp:
![image](https://github.com/grafana/grafana/assets/26184427/d67122d8-9022-4ca4-9737-cdc34f4c8307)

### What did you expect to happen?

I would expect the Time Series view to produce a plot of the observation timestamps and values that appear in the Table View

### Did this work before?

I'm not sure if this is a new behavior, but I think my particular dataset makes this very visible (it's a sinus style curve where the plots show aggregations from across "long time periods", meaning that the average values at this level become 4700-5100 in range, while the max individual observations are up around 9000-1000.

### How do we reproduce it?

I have provided the panel as an export here:

[debug-message_ can2_analog1to8fd _ signal_ analog5fd           -2023-11-24 09_50_36.json.txt](https://github.com/grafana/grafana/files/13456943/debug-message_.can2_analog1to8fd._.signal_.analog5fd.-2023-11-24.09_50_36.json.txt)

### Is the bug inside a dashboard panel?

Yes, the Time Series panel

### Environment (with versions)?

Grafana: Cloud
OS: Windows 10
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
Hello @MatinF thank you for reporting this discrepancy between the table view and the time series panel view. It seems like this could be related to the Amazon Athena plugin you are using in conjunction with the Time Series panel. To get the right attention to this issue, I'm directing it towards the AWS Datasources project

**Comment by leeoniya** [comment]
that value is actually present in your data, but your data is not sorted by time, so it is not the last datapoint in the table.

the timeseries panel requires that the data is sorted so we sort it automatically. if you sort the table by the time column, you will see it as the last row in the table as well.

![image](https://github.com/grafana/grafana/assets/43234/3dac2e07-4eb1-49cf-bcbd-f0b6475632e5)

![image](https://github.com/grafana/grafana/assets/43234/62cf30a9-3989-4205-9170-180ca6bb0cb2)

**Comment by MatinF** [comment]
Thanks for clarifying on the value being present in the table, I missed that. 

However, I still struggle to understand the logic of why the plot looks so different related to whether I do a `order by time` in the Athena SQL query, vs. simply letting Grafana do the sorting in the time series plot. 

**Default view: No order by time in query**
![image](https://github.com/grafana/grafana/assets/26184427/7e3dc227-0849-4e0d-b194-c039c72193af)

**Alternative view: order by time in query**
![image](https://github.com/grafana/grafana/assets/26184427/85af8d73-877b-46d7-ad48-34be41a17e74)
