### ISSUE TITLE
 [Bug] Grafana graph span behaves unpredicably with "repeat for" stats

### ISSUE THREAD

**Issue by flypenguin** [grafana/grafana#7868]
**Grafana info**

*  Grafana v4.1.2 (commit: v4.1.2), running as Docker container
* Ubuntu 16.04 running Docker
* Firefox 53.0b2 (64-bit)
* Prometheus data source

**Initial situation**

* Two templating variables
* A singlestat number, which relies on one of those (with 7 values)

**What I want**

* one row, with singlestats, looking like this: `[1]  [1]  [1]  [1]  [1]  [1]  [1]  [   5 free   ]` [numbers in brackets are spans] 
* Repeat that n times for the other template variable

**Where I started**

![graf1](https://cloud.githubusercontent.com/assets/5030694/24037510/5db03d40-0afe-11e7-9994-7f508dd4cc92.png)

**The settings I chose**

![graf2](https://cloud.githubusercontent.com/assets/5030694/24037525/705f276c-0afe-11e7-80e4-8193f049b466.png)

**Expected result**

```
[1]  [1]  [1]  [1]  [1]  [1]  [1]  [   5 free   ]
[1]  [1]  [1]  [1]  [1]  [1]  [1]  [   5 free   ]
[1]  [1]  [1]  [1]  [1]  [1]  [1]  [   5 free   ]
```

**Actual result**

![graf3](https://cloud.githubusercontent.com/assets/5030694/24037597/b1e5173c-0afe-11e7-9293-22446e06579b.png)

**Remarks**

The span was always set to 4. Setting "min span" or "span" had no effect.

The singlestat fits beautifully in a span 1.

#4878 seems to be about the same thing, and it was closed without fix. But since grafana is a displaying tool, it *does* matter IMHO that the information is presented in a "beautiful" way. Also the behavior is completely unexpected, unpredictable and has no reflection in the grafana UI (you *can* still select the "span" option, although it then behaves fully erratically, without warning).

**Comment by torkelo** [comment]
set the Min span option below the repeat option in General tab to define the width of the repeated panel.

**Comment by torkelo** [comment]
I see you tested this, already. The min span option is the only way to control width of repeated panels. Grafana when repeating panels will always try to make the panels fit the whole row.

**Comment by torkelo** [comment]
This might not be ideal in some cases, maybe a max span option would also be good, think we have an issue or PR for that.

**Comment by flypenguin** [comment]
I would agree :) . it actually works now, but I DID TEST THIS before and it didnt (and not only once). 
sorry for the ticket, but at least it works now. thanks for the quick answer!

**Comment by flypenguin** [comment]
Okay I am now trying to do *exactly* the same in another dashboard for about one hour now. And it is absolutely not working. Setting min span like crazy, NOTHING repeats (in contrast to the other one), and there is *NO* indication of what's going wrong. 

I really consider the UI interaction for this completely broken. (The feature might work, but the UI helps shit if you do something wrong - which I apparently do, cause it's not working, and I *know* it does. I just can't get it to work by doing exactly the same steps as with the other dashboard ...)

**Comment by torkelo** [comment]
You need to change the variable value for a repeat cycle to trigger, so the variable you have specified in the repeat needs to change its current selected value state or you need to save and reload the dashboard for the repeat process to trigger. Just changing min span will not have an immediate effect. 

Yea, I agree the UX for panel respeat

**Comment by flypenguin** [comment]
oh I did. countless times, believe me. 

For about two hours I also experimented with ...

* re-creating the whole dashboard multiple times,
* using different template variable selectors (see image, with and without selector drill-down - in all cases grafana found the values for the variables),
* step-by-step iteration of the prometheus queries with change-save-reload cycles to "ease" into the desired state.

Nothing worked. And I have absolutely no idea why. And that is kinda frustrating :( . maybe I can try to make a video of the process. But then it will suddenly work - of course - and then I go crazy.

<img width="518" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5030694/24063934/240a9806-0b62-11e7-990c-fd34cc43128e.png">

**Comment by torkelo** [comment]
Very strange, we have no other reports of panel repeats not working consistently, and fail to replicate any problem here so if you manage to replicate it describe the steps.

**Comment by torkelo** [comment]
And also include the dashboard json

**Comment by flypenguin** [comment]
I have [the json on a gist](https://gist.github.com/flypenguin/a591b04af0cb2b3f80606bfeba4ad652) now, and I have made a video that shows me creating the dashboard: [grafana.zip](https://github.com/grafana/grafana/files/859018/grafana.zip)

thanks for any help! it's probably really stupid, but like I said - I have no clue what it is.

**Comment by torkelo** [comment]
in your dashboard json the stack variable only has one value (not multiple), you must have multiple values selected (or all) for there to be any repeats

**Comment by flypenguin** [comment]
true, there are a couple with only one value, but depending on which stack you select it's multiple. and still it does not repeat. I attached a screenshot of the "situation". (and yes I changed the selectors before). no repeat. :/

![auswahl_003](https://cloud.githubusercontent.com/assets/5030694/24193702/86748544-0ef3-11e7-98f6-db2e233bb7e4.png)

**Comment by torkelo** [comment]
you must enable Multi-Value or All value for a template variable to have multiple values "selected" (active), the repeat function only works on the current values selected (so you can select from a long list of values which services to see for example).
