### ISSUE TITLE
[Change]: Only allow lowercase dashboard tags?

### ISSUE THREAD

**Issue by opentokix** [grafana/grafana#7869]
I am using Grafana v4.1.1 (commit: v4.1.1)

When using tags, they should not be case sensitive. 

ie. clicking on USsystem should also show ussystem and UsSystems, dashboards.

**Comment by daniellee** [comment]
Definitely a bug. There are a couple of places in Grafana that have case sensitive ordering and that should be fixed.

**Comment by daniellee** [comment]
This is fixed.
