### ISSUE TITLE
DateTimePicker: Bug with full_date format

### ISSUE THREAD

**Issue by KnpA** [grafana/grafana#78697]
### What happened?

Hello,

We're using Grafana since a long time and we want to upgrade from Grafana 8 to Grafana 9.
In our grafana.ini we have set "full_date" to "DD/MM/YYYY HH:mm:ss" according to Grafana documentation.
It was working in Grafana 8.x but now we got "Invalid date" in "Recently used absolute ranges" :
![image](https://github.com/grafana/grafana/assets/6367927/b1ad23bd-3070-4638-8dca-a805b250f604)

The selected timerange is working, but appears as "Invalid date to Invalid date"

In the local storage the value seems correct :
![image](https://github.com/grafana/grafana/assets/6367927/145f99a1-abee-421b-8221-7f6c89cafe0c)

If I click on it, I get this error message :
![image](https://github.com/grafana/grafana/assets/6367927/610769b8-16c9-4048-8cd0-79cb964e2eea)

And I'm locked in this state until I manually clean my local storage.

If I change the full_date to "DD-MM-YYYY HH:mm:ss" I don't get JS error but dates are wrong.

### What did you expect to happen?

No error message with this time format

### Did this work before?

It was working in Grafana 8.x (ex: 8.2.7)
![image](https://github.com/grafana/grafana/assets/6367927/8dfce329-f4e7-4f47-ae20-8ee0b4b76c7d)

### How do we reproduce it?

1. Set full_date to "DD/MM/YYYY HH:mm:ss"
2. Restart Grafana service
3. Select a custom timerange with the timepicker and "Apply"
4. Re-open timerange and select previous custom timerange in "Recently used absolute ranges"

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 9.5.13
OS: Linux Red Hat 7.4
Browser: Firefox ESR 115.5.0

### Grafana platform?

A downloaded binary

### Datasource(s)?

N/A

**Comment by usmangt** [comment]
Hi @KnpA,

Thanks for opening this issue.

Grafana's current latest stable version is 10.2.2 and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).
