### ISSUE TITLE
Plugins: validation failed in windows

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#78700]
### What happened?

Installing a plugin like zabbix or grafana-iot-twinmaker-app in windows is failing with an error:
`logger=plugins.signature.validation t=2023-10-25T14:45:19.5298275-03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginId=alexanderzobnin-zabbix-datasource status=unsigned`

See more details in https://github.com/grafana/grafana-zabbix/issues/1726

### What did you expect to happen?

I expected it to work.

### Did this work before?

I think yes.

### How do we reproduce it?

1. Install `alexanderzobnin-zabbix-app` with the grafana-cli in windows
2. Observe the logs and that you can't add a data source

### Environment (with versions)?

Grafana: 10.2.0
OS: Windows 10
Browser:

### Grafana platform?

A downloaded binary

**Comment by marefr** [comment]
Reproduced it using OSS 10.2.0 and 10.2.2. Going to try latest nightly build.
