### ISSUE TITLE
Azure Monitor: Azure / Insights /Storage Accounts dashboard not working

### ISSUE THREAD

**Issue by yves-chan** [grafana/grafana#78706]
### What happened?

#78547 Original issue logged here. I can reproduce with Grafana version 10.2.0

### What happened?

1. Load the Azure /Insights /Storage Accounts dashboard from the Azure Monitor Dashboard folder.
2. Observe the broken panels:
![image](https://github.com/grafana/grafana/assets/7664931/06a79df8-4f28-4cb2-992c-7de5b75a4a44)
The error is: 
```
A
request failed, status: 400 Bad Request, error:
Status: 500
Object
code:"BadRequest"
message:"Microsoft.Storage/storageAccounts/aulrgdiag is not a supported platform metric namespace, supported ones are Microsoft.Cdn/profiles,Microsoft.Cdn/CdnWebApplicationFirewallPolicies..."
```

When clicking into one of the broken panels, (ie: Transactions by Storage Type)
![image](https://github.com/grafana/grafana/assets/7664931/7103a535-633e-4af2-a342-8371a50ee8b4)
it seems to set the namespace to `$ns/$resource` in realtime, but the metricNamespace in the dashboard JSON should be this:

```
...
            "metricName": "Transactions",
            "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
            "resourceGroup": "$rg",
            "resourceName": "$resource/default",
            "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
            ...
```
I had a look through the dashboard history and I don't think there was anything changed in the content itself so I'm assuming it's a regression on some conversion that happens during query time?

### What did you expect to happen?

Dashboard loads without issues

### Did this work before?

Yes, but I do not recall

Might be related to parsing resourceUri (parseNamespaceAndName in ResourcePicker/utils.ts): https://github.com/grafana/grafana/commit/a4f56446eee9f201cedb738ada1d2383a549ee04

### How do we reproduce it?

See description

### Is the bug inside a dashboard panel?

This is the template from Azure Monitor

### Environment (with versions)?

Grafana: 10.2.0
OS: Win 
Browser: Win

### Grafana platform?

Other

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
Azure mentioned they experienced this issue in 10.2.0 and 9.5.x

**Comment by yves-chan** [comment]
@asimpson Thank you for investigating this issue, upon closer inspection. I'm also able to load the dashboard correctly if I import it from the Azure Monitor Datasource and also if I copy and paste the json content from this storage.json. The error only occurs from Azure Managed Grafana Instances. There is probably another copy of storage.json that gets provisioned instead of the one in this repo. Closing this issue as it's not related to grafana/grafana
