### ISSUE TITLE
Dashboards: Adhoc filter does not work with backslash

### ISSUE THREAD

**Issue by pavel-mokrushin** [grafana/grafana#78716]
### What happened?

When I click on "filter for value" on a text value that contains backslash, it shows nothing. If I escape that backslash in ad hoc filter, then the data is displayed.
Almost the same thing was fixed earlier [here](https://github.com/grafana/grafana/issues/72008), only there were double quotes

https://github.com/grafana/grafana/assets/82204499/3ed14060-1f03-4658-847f-15a676c33043

### What did you expect to happen?

The data should be filtered, including the value with backslash

### Did this work before?

it definitely worked on version 9.2.20

### How do we reproduce it?

1. There must be a value with text data that contains backslash
2. On the table panel, click "filter for value" or "filter out value".

### Environment (with versions)?

Grafana: 10.2.1
OS: Linux Debian
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch 7.17.15

**Comment by pavel-mokrushin** [comment]
Will there be any questions or clarifications?

**Comment by pavel-mokrushin** [comment]
Hi, @svennergr 
has there been no release of version 10.3 yet?
the night build of docker image does not download from me grafana/grafana-oss-dev:10.3.0-150176

**Comment by leeoniya** [comment]
i have some related work in https://github.com/grafana/grafana/pull/79286, but did not want to touch adhoc filters in that PR. maybe @ivanahuckova or @matyax can help. not sure if non-alphanum symbols must be matched, or if it's okay to just ignore them :thinking:

**Comment by matyax** [comment]
@leeoniya AFAIK, it shouldn't matter if alpha or non-alpha; the problem here used to be only about scaping and properly handling backslashes.

**Comment by svennergr** [comment]
> Hi, @svennergr has there been no release of version 10.3 yet? the night build of docker image does not download from me grafana/grafana-oss-dev:10.3.0-150176

Hi @pavel-mokrushin,

yea, sorry, you are right that 10.3 is not released yet.
I also tested this on a current 10.2.2 release and it seems it is working for me.

**Comment by pavel-mokrushin** [comment]
I checked on version 10.2.2 (in docker), it also doesn't work for me

https://github.com/grafana/grafana/assets/82204499/cd5d4e3b-1772-442b-87f8-4ed83aff57ad

**Comment by pavel-mokrushin** [comment]
@svennergr snapshot: 
[debug- Error list-2023-12-12 11_30_15.json.txt](https://github.com/grafana/grafana/files/13645048/debug-.Error.list-2023-12-12.11_30_15.json.txt)

**Comment by svennergr** [comment]
> @svennergr snapshot: [debug- Error list-2023-12-12 11_30_15.json.txt](https://github.com/grafana/grafana/files/13645048/debug-.Error.list-2023-12-12.11_30_15.json.txt)

Thanks @pavel-mokrushin, that helped. I can reproduce the issue now. I will keep you updated.
