### ISSUE TITLE
Provisioning: Azure SQLMI Datasource can't be configured to use Azure Authentication

### ISSUE THREAD

**Issue by tidux** [grafana/grafana#78711]
### What happened?

I'm trying to provision a connection to an Azure SQL Managed Instance as a Grafana datasource from a YAML file to avoid having it tweakable in the UI by users.  I have confirmed that the provided URL, tenant, client, and secret work correctly from the datasource management page in the Grafana UI when logged in as admin.  Using the same tenant/client/secret/URI in the jsonData field of a datasource.yml file does not work.  The syntax for doing this in a provisioning file is undocumented so I've been looking at the Go source code in  grafana/pkg/tsdb/mssql/mssql.go and trying to guess at correct variable names/capitalization, since the variable names in Go source do not correspond exactly to expected JSON values.

### What did you expect to happen?

I expected to provision a SQLMI data source.

### Did this work before?

no

### How do we reproduce it?

```
$ cat <<EOF > /etc/grafana/provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
  - name: SQLMI
    type: mssql
    url: censored.whoops.nope.database.windows.net:1433
    jsonData:
      database: Foo
      authenticationType: "AzureAuthentication"
      azureAuthType: "clientsecret"
      tenantId: "asd;flkasjdf;laksfja;sdl"
      clientId: "asdfa;lsdfj;asdlkja;sdfkja;sfkl"
      encrypt: 'true'
    secureJsonData:
      clientSecret: "ads;fkj;sdlkfj;asldfja;sdfklj"
EOF
```

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.2
OS: Win10
Browser: MS Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

MSSQL

**Comment by tonypowa** [comment]
Hi @tidux 
Thank you for creating this issue

If I provision your config file, I get the following error when trying to test the data source:

```
logger=datasources t=2023-12-20T08:11:28.033038481Z level=debug msg="Querying for data source via SQL store" uid=P16C6A219BDD0D6CF orgId=1
logger=secrets.kvstore t=2023-12-20T08:11:28.033512152Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=SQLMI
logger=tsdb.mssql t=2023-12-20T08:11:28.033598974Z level=debug msg="Parsing MSSQL URL" url=http://localhost:1433
logger=tsdb.mssql t=2023-12-20T08:11:28.033628659Z level=debug msg="Couldn't recognize as valid MSSQL URL" url=http://localhost:1433
logger=context userId=1 orgId=1 uname=admin t=2023-12-20T08:11:28.033669315Z level=error msg="Internal server error" error="[plugin.healthCheck] client: failed to check health: unrecognized MSSQL URL format: \"http://localhost:1433\"" remote_addr=172.26.0.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-12-20T08:11:28.033702887Z level=error msg="Request Completed" method=GET path=/api/datasources/uid/P16C6A219BDD0D6CF/health status=500 remote_addr=172.26.0.1 time_ms=1 duration=1.520088ms size=103 referer=http://localhost:3000/grafana/g/connections/datasources/edit/P16C6A219BDD0D6CF handler=/api/datasources/uid/:uid/health

```

When you say the provisioning "does not work" with the YAML file, could you provide any error messages that occur when Grafana tries to parse or use the YAML file you've created?

**Comment by taleena** [comment]
We haven't heard back on this one, and given our error received above when we tried, it appeared to be an issue with the MSSQL URL. Closing for now, please reopen a new issue with the requested details if needed.
