### ISSUE TITLE
[Bug]: Restore support for s3 bucket urls like  https://s3.amazonaws.com/<bucket> 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7871]
As noted here, https://github.com/grafana/grafana/pull/7058#issuecomment-287188612, that PR breaks s3 urls without region in the url. Need to fix that before release.

**Comment by DanCech** [comment]
It's not the region bit that causes problems.

The regex expects urls like `https://<bucket>.s3(-<region>)?.amazonaws.com` but doesn't handle urls like `https://s3(-<region>)?.amazonaws.com/<bucket>`

**Comment by rsilva4** [comment]
For those currently struggling to use s3 here is what worked for me (eu-west-2):

Url must be as @DanCech described take special attention to the `-` after the `s3` part.

For best control of s3 permissions I created a specific user and IAM Policy as described in http://stackoverflow.com/questions/8203598/i-need-an-amazon-s3-user-with-full-access-to-a-single-bucket.
