### ISSUE TITLE
[Bug] Faulty rendering of alert threshold on graph with two different Y axis

### ISSUE THREAD

**Issue by rburchell** [grafana/grafana#7873]
> Please include this information:
> - What Grafana version are you using?

4.1.1.

> - What datasource are you using?

InfluxDB.

> - What OS are you running grafana on?

OS X.

> - What did you do?

I have a graph, configured with a few different metrics, measuring ping. A few of these metrics are in ms (min/max/avg), and one is in percentage (packet loss).

![Metrics configuration](https://cloud.githubusercontent.com/assets/125863/24061690/b662c70a-0b58-11e7-8707-8eb96040f402.png)

The graph is thus configured to split packet loss to a seperate axis:

![Series overrides to split axes](https://cloud.githubusercontent.com/assets/125863/24061709/cc43feb8-0b58-11e7-9ad0-10a4d342dce3.png)

Y axis 2 is configured to use a percentage-based unit. So far so good.

![Axes configuration](https://cloud.githubusercontent.com/assets/125863/24061723/dd1fe864-0b58-11e7-99f4-7cb2c3b97cb4.png)

I then went to configure an alert based on this:

![Alert configuration](https://cloud.githubusercontent.com/assets/125863/24061765/0b3ff612-0b59-11e7-8aef-bf400ffb696f.png)

> - What was the expected result?

I expect the red overlay to not even be visible, seeing as packet loss is nowhere near 50%.

> - What happened instead?

![Graph showing incorrect overlay for alert](https://qtl.me/0904316B395C86A46C0A12E40DE0CABE.png)

Packet loss alert overlay appears to be tying its value to Y axis 1 (50 ms) instead of the axis the percentage is shifted to. The alert triggers correctly, so the problem is purely visual.

I hope I've been descriptive enough here, but if I can be of more help, please ask.

**Comment by torkelo** [comment]
Alerting thresholds are currently only visualized on left Y axis, currently no way for grafana to know which Y axis would be correct, so not sure we will support alert thresholds on left Y axis

**Comment by rburchell** [comment]
Thanks for the snappy response. I assume you mean "not sure we will support thresholds on right axis"?

Is the expected use of alerts/thresholds that they are separate series from those that are displayed, then? As I had expected that it worked based off the series I queried and then set up display for.

**Comment by torkelo** [comment]
It expected to be used with queries rendered in the graph. But Grafana does not know what series the query will return, maybe one is mapped to right axis and one to left, the number of series could change etc. 

Maybe in the future when if we associate display and axis settings to query letters it would be possible

**Comment by torkelo** [comment]
closing as there is already a feature request for threshold on right Y: https://github.com/grafana/grafana/issues/7107

**Comment by maxreb** [comment]
I don't think this is a direct duplicate as #7107 mentions the thresholds (Display -> Thresholds) but this metion the threshold on the alert panel (Alert -> Alert Config). As you can not define a Display Threshold if you defined an alert, it would be nice if we could set the threshold for the Alert, too, like this:
![image](https://user-images.githubusercontent.com/39700092/50736918-64443f80-11c3-11e9-98b8-74c22797ca7e.png)

**Comment by xordspar0** [comment]
#7107 already has a fix that was merged, but this issue remains.

**Comment by RuralHunter** [comment]
+1

**Comment by passcod** [comment]
This is not fixed, please reopen
