### ISSUE TITLE
[Bug] Alerts seem to "corrupt" InfluxDB queries somehow

### ISSUE THREAD

**Issue by rburchell** [grafana/grafana#7874]
> Please include this information:
> - What Grafana version are you using?

4.1.1.

> - What datasource are you using?

InfluxDB.

> - What OS are you running grafana on?

OS X.

> - What did you do?

See #7873 for most of it. I then saved the dashboard, wandered around a bit, clicked some other things... I know this isn't too descriptive, but I don't have exact reproduction steps yet.

> - What was the expected result?

My ping graph kept working.

> - What happened instead?

Somehow, the alert query broke it.

It's getting:

> {
>  "error": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 115",
>  "message": "error parsing query: found >, expected identifier, string, number, bool at line 1, char 115"
> }

Off the following query:

> SELECT mean("AverageTime") FROM "ping_stat" WHERE time > 1489776406669ms and time < 1489778392679ms GROUP BY time(>40s), "host" fill(null);SELECT mean("MaxTime") FROM "ping_stat" WHERE time > 1489776406669ms and time < 1489778392679ms GROUP BY time(>40s), "host" fill(null);SELECT mean("MinTime") FROM "ping_stat" WHERE time > 1489776406669ms and time < 1489778392679ms GROUP BY time(>40s), "host" fill(null);SELECT "PacketLossPercent" FROM "ping_stat" WHERE time > 1489776406669ms and time < 1489778392679ms GROUP BY time(>40s), "host"

Of some interest is that the ">40s" value is what I had entered in `Group by time interval` previously, but the graph had no problems loading data or rendering at all until I reloaded some time later.

Furthermore, nothing I do seems to be able to fix this easily. I tried blanking the time interval box, I tried removing the alert, I tried tweaking the series query by hand... All didn't work. It still keeps complaining about the same ">40s" value which I can't find *anywhere* anymore.

If I disable view of the "PacketLossPercent" metric, the error in the top left goes away, but the graph does not show any data.

**Comment by rburchell** [comment]
> If I disable view of the "PacketLossPercent" metric, the error in the top left goes away, but the graph does not show any data.

This "graph not showing data after I disable PacketLossPercent" problem appears to be caused by fill(null). If I change that to fill(none), I see the graph I expect. Weird. I guess that's a second bug, but I wouldn't have a clue how to look into that...

**Comment by rburchell** [comment]
I think the key to the problem is having ">40s" in `Group by time interval` when creating a metric (which has an alert on it). I create the metric query, everything looks fine. I save the dashboard, reload it, and it's "corrupt" and will no longer load until I delete and replace the alerted metric. Then it will be fine until I save & reload again subsequently.

If I do the same process without any time interval grouping, there is no "corruption".

**Comment by torkelo** [comment]
this is fixed in 4.2-beta1 https://github.com/grafana/grafana/issues/6765

**Comment by rburchell** [comment]
thankyou! sorry for the dupe.
