### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#78759]
In Grafana, we have pages with similar functionality but the overall layout varies from product-area to product-area. We should create templates for the most commonly use page layout types.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/78575
```

**Comment by Clarity-89** [comment]
@staton-hyse11 we already have an epic for the template-related work: https://github.com/grafana/grafana/issues/77269.

**Comment by staton-hyse11** [comment]
Closing this as a duplicate of https://github.com/grafana/grafana/issues/77269.
