### ISSUE TITLE
[Bug] Disable Login Form setting not handled properly

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#7875]
If the login form is disabled by the setting `auth.disable_login_form = true` any users invited to Grafana won't be able to log in.  If this setting is enabled the UI should not offer the ability to invite new users to an org, and if a user attempts to invite a new user by email address they should receive an error message.

Additionally, the setting above isn't checked by the API `/login` route, meaning that it is still possible to log in to Grafana with a local account when logins are ostensibly disabled.  This can be achieved by loading Grafana and executing the following code from the javascript console (replace admin/pass with a valid user/pass):
```
var req=new XMLHttpRequest();req.open('POST','/login',false);req.setRequestHeader('Content-Type','application/json');req.send('{"user":"admin","password":"pass"}');window.location='/';
```

Please include this information:
- What Grafana version are you using? master
- What datasource are you using? n/a
- What OS are you running grafana on? linux
- What did you do? disabled local account login
- What was the expected result? ui shouldn't offer the ability to invite new local users, /login route should reject login attempts
- What happened instead? ui still offers the ability to invite new local users, /login route still allows login

**Comment by nopzor1200** [comment]
Rather than receiving an error message when inviting the user to the internal Org, I think it would be better if there was a message in the place of the Invite button that explained "This Grafana is configured to authenticate via X; manage your users there"
