### ISSUE TITLE
Saga website Icons page

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#78763]
Create an Iconography page that includes all icons used within Grafana with click-to-copy functionality and a search function that uses keywords

Edit:
We can expand this to the overall iconography handling of the system — Figma, Github, Storybook as there is an active effort to revisit how we are handling icons.

**Comment by Aires-Grafana** [comment]
Leaving here the link for the issue related to the new Figma "Saga Iconography" file.
https://github.com/grafana/grafana/issues/78814

**Comment by L-M-K-B** [comment]
Closing this issue for now
