### ISSUE TITLE
[Bug] OpenTSDB nested templating with metrics() query

### ISSUE THREAD

**Issue by trzejos** [grafana/grafana#7877]
Grafana Version: 4.1.1
Datasource: OpenTSDB 2.3
OS: CentOS 7

I created two template variables, $service_pfx and $service:
![grafana_templating_01](https://cloud.githubusercontent.com/assets/3720978/24063110/4c516488-0b2c-11e7-98c8-0596327f2bc3.png)
![grafana_templating_02](https://cloud.githubusercontent.com/assets/3720978/24063115/52de4352-0b2c-11e7-9986-3548047a7643.png)
![grafana_templating_03](https://cloud.githubusercontent.com/assets/3720978/24063119/5695f31e-0b2c-11e7-941a-a827a4016512.png)

The second template variable, $service, does not return any values because it improperly forms a query to opentsdb's /api/suggest endpoint

Error
`/api/suggest?max=1000&q=i,service_pfx%3Dc,service_pfx%3Di,service_pfx%3Dn,service_pfx%3Dg,service_pfx%3Da,service_pfx%3D.,service_pfx%3Dh,service_pfx%3Do,service_pfx%3Ds,service_pfx%3Dt&type=metrics`

Expected
`/api/suggest?max=1000&q=icinga.host&type=metrics`

**Comment by torkelo** [comment]
should be fixed in 4.2 beta1, https://github.com/grafana/grafana/issues/7385
