### ISSUE TITLE
[Bug] SearchPhaseExecutionException[Failed to execute phase [query] when creating queries for Elasticsearch

### ISSUE THREAD

**Issue by Electronickss** [grafana/grafana#7879]
This is likely a PEBKAC/isn't possible because of versioning but I wanted to ask. I am using a SIEM that relies on an old version of Elasticsearch [`1.5.2`] and wanted to add it as a data source to our Infosec dashboard

- What Grafana version are you using? `Grafana v4.1.2 (commit: v4.1.2)`
- What datasource are you using? `Elasticsearch 1.5.2` 
- What OS are you running grafana on? Ubuntu 14.04.3
- What did you do? Added it as a data source
- What was the expected result? To be able to query data
- What happened instead? Received this error:
```
"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[pFCfrEIbRrWyGecQmLliLA][logs-2017-03-19][0]: SearchParseException[[logs-2017-03-19][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{\"size\":0,\"query\":{\"bool\":{\"must\":[{\"range\":{\"normalDate\":{\"gte\":\"1489883784601\",\"lte\":\"1489905384601\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"filters\":{\"filters\":{\"*\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}}}},\"aggs\":{}}}}]]]; nested: IllegalArgumentException[Invalid format: [epoch_millis]: Illegal pattern component: p]; nested: IllegalArgumentException[Illegal pattern component: p]; }{[pFCfrEIbRrWyGecQmLliLA][logs-2017-03-19][1]: SearchParseException[[logs-2017-03-19][1]: from[-1],size[0]: Parse Failure [Failed to parse source [{\"size\":0,\"query\":{\"bool\":{\"must\":[{\"range\":{\"normalDate\":{\"gte\":\"1489883784601\",\"lte\":\"1489905384601\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"filters\":{\"filters\":{\"*\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}}}},\"aggs\":{}}}}]]]; nested: IllegalArgumentException[Invalid format: [epoch_millis]: Illegal pattern component: p]; nested: IllegalArgumentException[Illegal pattern component: p]; }]"
```
To my understanding it has to do with the fact that pre 2.0 elasticsearch used `dateOptionalTime` for the date. I'm seeing in the error that it references epoc_millis a few times.

Is there anything I can do to add this as a source or am I just SOL because the SIEM uses to old of a version?

**Comment by Electronickss** [comment]
Here is the time format that I am looking to use for the log
`"logDate": "2017-03-17T20:13:06.5899945"`

**Comment by torkelo** [comment]
Grafana 4.x+ only supports ES 2.x and 5.x
