### ISSUE TITLE
Product Area: UI/UX Elasticsearch 5.0.0 plugin

### ISSUE THREAD

**Issue by JsonBlack09** [grafana/grafana#78790]
### What happened?

Highlighting is not working in elasticsearch datasource in EXPLORE view
In the previous version of Grafana, with which we updated, the highlight worked correctly in any fields

![Untitled22](https://github.com/grafana/grafana/assets/48260560/50db6db9-f15f-4fbb-bb4b-5bad6f46b4b0)

Also, log information from the _source field has stopped being displayed. Although all the information in the datasource is filled out correctly. All these problems arose after updating Grafana. There weren't any before.

![Untitled3](https://github.com/grafana/grafana/assets/48260560/172bb45c-6c30-418d-84ec-ff8772b9aa8f)

### What did you expect to happen?

Working highliting

### Did this work before?

Upgrade grafana from 10.0.3 to v10.2.1

### How do we reproduce it?

1. Install grafana 10.0.3 from deb
2. Install elasticsearch datasource 5.0.0
3. Upgrade grafana to 10.2.1
4. => Bug in Explore (logs) with highlighting and display info

### Environment (with versions)?

Grafana: v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)
OS: Ubuntu 22.04.3 LTS
Browser: 119.0.6045.161 Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch 5.0.0

**Comment by matyax** [comment]
Thank you for reporting this @JsonBlack09! We'll be looking at it shortly, in particular the highlighting issue.

**Comment by JsonBlack09** [comment]
In additional - highlight worked with any field except _source. Looks like _source forced changed to _id field in datasource code source
![image](https://github.com/grafana/grafana/assets/48260560/6acedae3-7d99-4387-b6e6-5c99eddd2876)

**Comment by matyax** [comment]
@ivanahuckova FYI.

**Comment by ivanahuckova** [comment]
@JsonBlack09 thank you do much for reporting this! I have created https://github.com/grafana/grafana/pull/80804 to fix showing of correct `__source` field as log message in logs panel.

Regarding the highlighting, could you confirm that it is working with any other field? Because from your messages it seems that the highlighting works correctly, and the issue was not showing `__source` as log message. Could you confirm this?

**Comment by JsonBlack09** [comment]
@ivanahuckova Good afternoon, I can confirm that when _source is used as the “Message field name”, the _source field is not displayed on visualizations of the “Logs” type; instead of _source, _id is displayed (screen in the description of the problem in the 1st post). Accordingly, it is impossible to highlight information from _source, because it does not appear on the panel.
I checked about 20 fields from different documents as “Message field name” and for all fields the highlighting in the “Logs” visualization worked. So now I think the problem was not the highlight not working, but the fact that _source was not showing up in the Logs panel

**Comment by ivanahuckova** [comment]
Thank you for the confirmation. 🧡 I have merged the fix and it should be part of the next release. In the meantime, you can set `enableElasticsearchBackendQuerying` feature toggle to `false` and it should work as expected because the issue happens with querying through data source backend.
