### ISSUE TITLE
Dashboards: Deleting a dashboard from settings is not redirecting to home

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#78810]
### What happened?

When deleting a dashboard, I receive a confirmation alert but it doesn’t take me to another place.

### What did you expect to happen?

Redirect to home or the dashboard list.

### Did this work before?

Yes, it's a regression

### How do we reproduce it?

1. Create a dashboard
2. Go to settings
3. Delete it

https://github.com/grafana/grafana/assets/20256983/45d9e0d8-d63f-4636-b2b7-636c89e08960

### Environment (with versions)?

Grafana: main
OS: OSX
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

**Comment by ivanortegaalba** [comment]
It took me some time to realize what was going on 😓 

Here is the fix: https://github.com/grafana/grafana/pull/78918

Thanks @evictorero for reporting it!
