### ISSUE TITLE
[Feature request] Elasticsearch 5.2.2 data source support

### ISSUE THREAD

**Issue by SnirX** [grafana/grafana#7882]
Hi,
When will Elasticsearch 5.2.2 data source will be supported by Grafana?

Grafana version - grafana-4.1.2
Data source - Elasticsearch
OS - Centos 6.8

**Comment by torkelo** [comment]
I was not aware that it did not work? Is there something specifically we need to change to support 5.2.2 ?

**Comment by SnirX** [comment]
Even when trying to query how many documents are in the data source (simplest query) we recieve '400 Bad Request' error

**Comment by torkelo** [comment]
ok, have you specified version in Datasource edit page? need to be set to ES 5. 

Also please include query sent and response from ES. 
https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
