### ISSUE TITLE
InfluxQL: Allow to change the Database in the builder UI

### ISSUE THREAD

**Issue by william-carrier** [grafana/grafana#78823]
**Why is this needed**:

Allow to change the InfluxDB database (bucket) in the explorer UI. The InfluxDB query syntax already allows switching the database in the query. ex:

> SELECT * FROM "_internal".."database" LIMIT 10

With the arrival of InfluxDB 3.0, Flux will no longer be supported and we will need to change for InfluxQL. Creating a datasource for each database might not always be favorable.

**What would you like to be added**:

Adding a dropdown list button the same way we select measurements.

**Who is this feature for?**

All users that use InfluxQL with a lot of databases (buckets) in InfluxDB.

**Comment by Olivier-Stp** [comment]
That would be so easier when dealing with multiple DBs.

**Comment by itsmylife** [comment]
Hi @william-carrier. Thanks for the suggestion. It would be indeed useful. But in this way, it will require too much change in InfluxDB datasource. Data sources are not built for such a use case. Each should work against one database. 

The good thing is we have a way to cover this case. [This PR](https://github.com/grafana/grafana/pull/83356) will allow us to do the same thing without changing many lines of code in InfluxDB and provides the same functionality for other data sources too. 

Therefore, we won't be moving forward with integrating it into InfluxDB at this time. I am closing this issue. Please let us know if you have further questions or suggestions. I'll make sure that PR will land on `main` as quickly as possible.
