### ISSUE TITLE
[Feat]: Dashboard & Persistent urls (that works after name change)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7883]
Dasboards urls should still work after a dashboard name change. 

Propose new url structure: 

`/o/<orgId>/d/<dash-id>/<slug>`

1) Start with making new backend routes for dashboard & dashboard solo (png rendering / embedd single panel)
https://github.com/grafana/grafana/blob/master/pkg/api/api.go#L63

2) New frontend routes
The id is used for lookup, the dashboard name is just there for nice readable url. If it does not match the current slug of the dashboard it will redirect to the current url. 

Will need a new api to lookup dashboard id by slug to support the old url as well (so the old url can redirect to new). This logic needs to be in the frontend and backend so start with frontend. 

Change would have to be backward compatible with current url structure, at least for one major version. 

Ignore scripted dashboards for these new urls. We might drop support for them in v5 or after v5

**Comment by ryantxu** [comment]
Can we make sure that links from 4x redirect?  at least for a little while?  I'd like to avoid the "update your bookmarks" email :)

**Comment by bergquist** [comment]
Making dashboard titles none unique will make the fallback a little weird. 

I'm not sure what to return if we fall back to using slugs and have two dashboards with the same slug. 
* return lowest id first?
* return last edited dashboard?
* return `/dashboards` with the slug name pre-filled in the search box.

Right now we are leaning towards option 3.

**Comment by marefr** [comment]
@torkelo @bergquist 

Been thinking about this for a while and have a proposal which only (to start with) solves the problems introduced by folders (basically #10419).
 - Make dashboard slugs editable
 - When creating a new folder, make sure that the slug includes *`f-<slug of folder title>`*. This will make folder slugs kind of unique compared with dashboard slugs. Or don't include folders when searching/validating unique dashboard slugs.
 - When creating a new dashboard in the root folder the dashboard slug will be suggested as *`<slug of dashboard title>`*
 - When creating a new dashboard in a folder the dashboard slug will be suggested as *`<folder-slug>-<slug of dashboard title>`*
 - Settings form, save and save as dashboard dialogs includes new field for edit the slug together with existing field for title and folder selection.

Maybe we also should separate dashboard and folder concepts in the api, making it more explicit that folder and dashboard are two separate things. 

I think my proposal is a good slice to start solving the problems related to persistent urls. I don't see that starting with changing to a new url structure solves the problems introduced with folders, rather introducing new and more problems.

What are your thoughts about starting with solving #10419 and postpone new url structure?

**Comment by marefr** [comment]
New proposal:

Introduce a new column holding a unique identifier for a dashboard/folder. Change the url structure for dashboard:
`/d/<unique identifier>/<optional human-friendly part, usually slug of dashboard title>`

The old url structure should still be supported for fallback mechanism to support legacy slug-based urls, i.e. /dashboard/db/<slug of dashboard title>. The old url structure should redirect to new url structure using a 301 permanently moved.

### First step

- [ ] Add new column *uid* to the dashboard table

- [ ] Add migrations for generating unique identifiers for existing dashboards

- [ ] Add unique index for the *uid* column

- [ ] Add unique identifier to dashboard model

- [ ] Return unique identifier in response to creating/updating a dashboard

### Second step

- [ ] Add support for retrieving a dashboard by unique identifier (HTTP API)

- [ ] Add uri to dashboard and search api responses

- [ ] API/internal query for retrieving unique identifier by slug (fallback)

### Frontend step

- [ ] New route `/d/<unique identifier>/<slug of dashboard title`

- [ ] Implement loading dashboard by unique identifier. Fallback to slug, if possible, and redirect.

- [ ] Handle redirect if new dashboard created or existing title changed (different slug).

- [ ] Use new *uri* property returned from dashboard api when linking to dashboards

### Backend step

- [ ] Remove unique index of *org_id* and *slug*

- [ ] Remove uniqueness check on *slug* when saving dashboard

- [ ] Add uniqueness check on *title* and *folder_id* when saving dashboard. Should be possible to save dashboards with same title in different folders. A folder and dashboard with the same title should not be possible. Tracked in #10419 

### Cleanup step

- [ ] Remove return of slug in responses

- [ ] Backend route for rendering server response of new dashboard url structure

### Out of scope for this issue

- [ ] Handle linking to other dashboards using unique identifier

**Comment by marefr** [comment]
Realized that we need to do some changes related to alerting as well. This will be a problem otherwise when having at least two dashboards with the same title in different folders and at least an alert defined in each dashboard.

### Alerting step

- GetRuleUrl for EvalContext needs to return a url based on the new default dashboard url

- Need to change path to the renderToPng when uploading image (notificationService.uploadImage) 

- Return *dashboardUrl* property in alerts api and use that to render link to dashboard in the alert rules page. Make sure to set fullscreen=true to make going back to alert rules pages with one browser back button instead of two

**Comment by marefr** [comment]
There was some more things needed, but changes was too big why we create another step for tracking the rest of frontend work:

### Frontend step 2

- [ ] Remove return of slug in dashboard search responses

- [ ] Change the front end route for folders to `/dashboards/f/<uid>/<slug of folder title>. Tracked in #10579

- [ ] Restoring a dashboard version pre-5.0 which don't have a uid should get the current uid, if any

- [ ] If url doesn't equal the url returned from api when loading a dashboard we should change the url in browser
