### ISSUE TITLE
[Bug] "binding.node: ELF load command past end of file" error when building branch "alerting-elasticsearch"

### ISSUE THREAD

**Issue by eueuy** [grafana/grafana#7884]
hi,all

on linux core version 6.x 
node --version -> v6.10.0
npm --version  ->  3.10.10

i need the alerting feature of es , so i found this branch: https://github.com/grafana/grafana/tree/alerting-elasticsearch.

when i building frontend assets by command "npm run build"
error happend:

[root@sd-3-centos30 grafana]# npm run build

> grafana@4.2.0-pre1 build /root/go/src/github.com/grafana/grafana
> ./node_modules/grunt-cli/bin/grunt

Version 4.2.0-pre1
Loading "sass.js" tasks...ERROR
>> Error: /root/go/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-48/binding.node: ELF load command past end of file

Running "jscs:src" (jscs) task
>> 86 files without code style errors.

Running "jshint:source" (jshint) task

 No problems

Running "jshint:tests" (jshint) task

 No problems

Running "exec:tslint" (exec) task

Running "clean:gen" (clean) task
>> 1 path cleaned.

Running "copy:node_modules" (copy) task
Created 100 directories, copied 1596 files

Running "copy:public_to_gen" (copy) task
Created 324 directories, copied 2641 files

Running "phantomjs" task

Running "copy:phantom_bin" (copy) task
Copied 1 file
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.2.0-pre1 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the grafana@4.2.0-pre1 build script './node_modules/grunt-cli/bin/grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/go/src/github.com/grafana/grafana/npm-debug.log

i have searched this error on community,issues, github of nodejs  npm.. etc ... but useful information none.

thank you for help . @torkelo

**Comment by torkelo** [comment]
did you run `yarn install` before?

**Comment by eueuy** [comment]
@torkelo 
yes , i just follow the document step by step.

**Comment by daniellee** [comment]
We got an issue for this a week ago. We cannot recreate this locally. 

Maybe this helps:

https://github.com/grafana/grafana/issues/7805#issuecomment-287028402

Also, try removing your node modules directory:

`yarn cache clean && rm -rf node_modules`

 and then run: `yarn install --pure-lockfile`

There seem to be lots of people having problems with Yarn and node-sass: https://github.com/sass/node-sass/issues/1804

Maybe you can try either `npm rebuild node-sass` or if that fails then `yarn install --pure-lockfile --force`

**Comment by eueuy** [comment]
thanks  all.  
its sloved by @daniellee 's comment
