### ISSUE TITLE
Startup with empty config file panicks.

### ISSUE THREAD

**Issue by fabxc** [grafana/grafana#7885]
Grafana 4.1.1

Starting the server with an empty config file panicks.

Stack trace: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4278467]

goroutine 1 [running]:
panic(0x4a3ec60, 0xc42000c0e0)
       	/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/vendor/gopkg.in/ini%2ev1.(*Section).GetKey(0x0, 0x4b5eb14, 0x7, 0x3, 0x4, 0x4)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/vendor/gopkg.in/ini.v1/section.go:73 +0x37
github.com/grafana/grafana/vendor/gopkg.in/ini%2ev1.(*Section).Key(0x0, 0x4b5eb14, 0x7, 0x4)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/vendor/gopkg.in/ini.v1/section.go:132 +0x43
github.com/grafana/grafana/pkg/log.ReadLoggingConfig(0xc4201d4790, 0x1, 0x1, 0xc4201dec60, 0x18, 0xc4201e2ee0)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/log/log.go:188 +0x2e8
github.com/grafana/grafana/pkg/setting.initLogging()
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/setting/setting.go:621 +0x1f0
github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc420117de8)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/setting/setting.go:404 +0x31e
github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc420117de8, 0x4a9d4f8, 0xc420117df8)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/setting/setting.go:473 +0x54
main.initRuntime()
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:70 +0xd5
main.(*GrafanaServerImpl).Start(0xc4201e08d0)
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:52 +0x5f
main.main()
       	/private/tmp/grafana-20170112-81795-m2v726/grafana-4.1.1/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:62 +0x12c
```

**Comment by torkelo** [comment]
strange, works fine here. Maybe your modifying the defaults file? can you describe what file you modified and how you start grafana?

**Comment by fabxc** [comment]
I did `brew install grafana` and ran `grafana-server`. Startup was giving
me very obscure messages as to what kind of path (it probably meant
something related to the config file) was expected from me. I sort of
inferred via docs that it expected ./conf/defaults.ini and created that as
an empty file as it was not clear based on documentation what should be in
there as a minimum. After starting like that it crashed.

I don't think it really matters whether I modified a defaults file (if
there's a system-wide one, it was obviously not found by the application).
Crashing does not seem like a valid handling of the environment not
matching expectations.

**Comment by torkelo** [comment]
well it's a file that is part of the core package, so if you remove a file that is part of the core it will crash or if you start grafana-server without a proper homepath. 

You should start grafana-server has a homebrew service, think the command is printed after you install it with homebrew. 

If start it manually  you need to specify a few options:

Here are the homebrew options 
``
  plist_options :manual => "grafana-server --config=#{HOMEBREW_PREFIX}/etc/grafana/grafana.ini --homepath #{HOMEBREW_PREFIX}/share/grafana cfg:default.paths.logs=#{HOMEBREW_PREFIX}/var/log/grafana cfg:default.paths.data=#{HOMEBREW_PREFIX}/var/lib/grafana cfg:default.paths.plugins=#{HOMEBREW_PREFIX}/var/lib/grafana/plugins"
``

I know the mac install docs are very poor, we will try to update and improve those. The error you got should also be handled better, but we have handling for not finding the config files, etc, but did not expect a core file (that users never change) to be empty

**Comment by fabxc** [comment]
I did not remove any file. I created a new one because out of the box, Grafana was apparently missing something to start up.

I still believe that panicking based on unfulfilled environment expectations (which are additionally caused by a broken install process) should not result in a panic.

**Comment by torkelo** [comment]
but grafana installs to `#{HOMEBREW_PREFIX}/share/grafana` , there is a conf/defaults.ini there already.  but you say you created an empty on somewhere else? 

Grafana requires a few things at startup and it has validation for those environment variables, for example it looks for a conf directory and deafults.ini in the homepath or homepath is your working directory. If it find that it expects that file to be VALID file that came with the install not a user modified empty file. But I agree a crash is not what should happen in a case like this either. But looking checking for every file that should come with an install is not that usual, but a good error message is still to be expected. It's just since it finds the file and this is a core file that users never ever change it expects it to have the content's it should have, since there is no reason to expect differently.
