### ISSUE TITLE
Alerting - Flap detection 

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#7886]
It would be nice to have some kind of flap detection. I got ~60 Email+SMS alerts over a 4 hour period

not sure how this would work, or if its possible.
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html
 
![screen shot 2017-03-20 at 12 52 28](https://cloud.githubusercontent.com/assets/9446644/24098699/28b1f154-0d6c-11e7-8f94-7262782f9304.png)

**Comment by daniellee** [comment]
Related #6202

**Comment by marefr** [comment]
Of your suggestions I like `For` the most, at least from a UI perspective.

Some other suggestions
* Notify after  (depending on if state is changed to alerting directly when evaluated to TRUE)
* Alert after (depending on if state is changed to alerting  when evaluated to TRUE during for example 3m)

For example, Prometheus are using the `PENDING` state until the state of an alert that has been active for longer than the configured threshold duration and then transitions to `FIRING`. Are we thinking about doing something similar? Given that we create annotations on state change (OK -> ALERT) it might be easier code wise to only trigger ALERT after "duration".

**Comment by bergquist** [comment]
Right now we don't change the state before the alert have been firing longer than `FOR`

I'm currently reusing the pending state, which means all notifications etc works as expected. I'm thinking about introducing a new state but I'm hesitant since more states make it harder to know what's state an alert is in.

**Comment by haizaar** [comment]
Will this feature be useful for implementing logic like "trigger alert if last minute average of metric X is above Y **for 5 minutes**"?
I don't remember the details, but back in a while it took me a lot of fiddling doing something similar with P8s 2.x and Grafana 4.x.
