### ISSUE TITLE
[Bug] Cannot fire alerting when using preloaded dashboards

### ISSUE THREAD

**Issue by mkuculyma** [grafana/grafana#7888]
- What Grafana version are you using? 4.1.2
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Official Grafana Docker image
- What did you do?

I imported dashboards json files with alerting this way:
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards

and start Grafana.

Now. To fire alerting I should save dashboard first, right? So I click "save as" and dashboards are being duplicated. The saved duplicate json does not contain alerting section at all (when viewing it's json). So adding dashboards with alerting this way does not work. Preloaded dashboard contains alerting section, but the dashboard ID is not yet in database. So I cannot use alerting. And the saved duplicate got alerting section cut out somehow, so naturally it is not possible to use this to fire alerting.

- What was the expected result?
I expected to be able to fire alerting after saving the dashboard. I would like to be able to use alerting when using preloaded dashboards.

**Comment by torkelo** [comment]
we are depricating dashboard.json feature, replacing it with something that can sync dashboards from file to dashboards in database (and prevent changes in UI). The dashboard.json feature is a bit broken right now as these dashboard have no dashboard id and cannot be starred and set as home dashboard, so we are going to redesign this and deprecate it. 
https://github.com/grafana/grafana/issues/5269

In the mean time I recommend you use this tool to import / sync dashboard from file to Grafana db:
https://github.com/utkarshcmu/wizzy
