### ISSUE TITLE
Return org picker's searching functionality

### ISSUE THREAD

**Issue by ManiacMaxo** [grafana/grafana#78885]
**Why is this needed**:

Our use-case has hundreds of organizations in a self-hosted instance of Grafana. An administrator trying to add a user to an org is an incredibly tedious process since the org list is unsorted and extremely long. 

**What would you like to be added**:

We recently upgraded from v6 to v10 and v6 had this org picker with search enabled. I would like to resurrect this functionality. Seems like an easy fix since it will all be frontend-based.

**Who is this feature for?**

A grafana instance with multiple organizations that are managed by humans.

**Comment by usmangt** [comment]
Hi @ManiacMaxo,

Thanks for opening this issue.

Version 6 is extremely old and as v10 is not just the new version but also used a different backend and frontend as well.

Your request may be interesting to be a feature. Can you please share a small video screenscast as how you use to this operation in version 6?

**Comment by ManiacMaxo** [comment]
Hey! This is the use-case at a much smaller scale than needed:

https://github.com/grafana/grafana/assets/25492186/6532935d-92d5-4478-a02b-800e8f824ef7

**Comment by metalgrid** [comment]
Hello,
What is the status on this? I see there's a pull request that solves the issue, but I'd rather not run a grafana fork. What is required for this go be merged in GA?

Best regards!
