### ISSUE TITLE
[Bug] Incorrect png rendering related to phantomjs "Flex flow: row wrap" issue

### ISSUE THREAD

**Issue by Fiery-Fenix** [grafana/grafana#7889]
- What Grafana version are you using?
Grafana 4.2.0-beta1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu Xenial (16.04)
- What did you do?
Export dashboard to png via /render/dashboard/... URL
- What was the expected result?
Correct alignment and size of dashboard links and dashboard template variables dropdown, see image:
![after](https://cloud.githubusercontent.com/assets/2854059/24112588/b6844898-0da2-11e7-9b5c-aa692259e197.png)

- What happened instead?
Dashboard link button has 100% size and dashboard template variable dropdown has incorrect wrap, see image:
![before](https://cloud.githubusercontent.com/assets/2854059/24112602/bf56ce64-0da2-11e7-9f65-a18a29232023.png)

This issue totally related to PhantomJS issue [14365](https://github.com/ariya/phantomjs/issues/14365) and was fixed in 2.5.0 beta version. 
For current stable version proposed workaround is to add autoprefixer rule in postcss.js task:
```
diff --git a/tasks/options/postcss.js b/tasks/options/postcss.js
index 5d77096..396c632 100644
--- a/tasks/options/postcss.js
+++ b/tasks/options/postcss.js
@@ -11,7 +11,7 @@ module.exports = function(config) {
       },

       processors: [
-        require('autoprefixer')({browsers: 'last 3 versions'}), // add vendor prefixes
+        require('autoprefixer')({browsers: ['last 3 versions', 'safari >= 4']}), // add vendor prefixes
       ]
     },
     dist: {
```

**Comment by torkelo** [comment]
since dashboard png rendering is not officially supported yet, we think we can wait for phantomjs 2.5 to be released I feel.

**Comment by Fiery-Fenix** [comment]
PhantomJS 2.5.0 beta was released only in January this year and has no stable release date for now. Seems that new version has a lot of bugs and I don't believe that stable release of 2.5 version could appear in next half of year. So if dashboard png rendering is planned to be officially supported this year - I think this workaround would be very useful.

**Comment by torkelo** [comment]
Closing this as taking png snapshots of whole dashboards is not fully supported yet. And if we do it as a real feature I think dashboard links will likely be hidden anyway
