### ISSUE TITLE
Service Account Name is global (not scoped to organization)

### ISSUE THREAD

**Issue by noamApps** [grafana/grafana#78903]
### What happened?

I tried to create a service account with the same name in two different organizations, got service account name already exist after generating a service account with the same name in another one

### What did you expect to happen?

Service account should have been created successfully

### Did this work before?

Not sure

### How do we reproduce it?

1. create a service account with name "test" in Org A
2. try tocreate a service account with name "test" in Org B
3. Observe service account name already exists error

### Environment (with versions)?

Grafana: v10.2.1
OS: MacOs Sonoma
Browser: Chrome 119.0.6045.159

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @noamApps,

Thanks for opening this issue.

Which Grafana version you are using i.e. Grafana OSS, or Grafana Enterprise?

**Comment by noamApps** [comment]
Grafana OSS

**Comment by usmangt** [comment]
Thank you.

Service account are meant to be used for Grafana Enterprise. For Grafana OSS please use the normal API token method.

Here is also a link to an old GitHub issue on same question https://github.com/grafana/grafana/issues/73602

**Comment by noamApps** [comment]
Hi @usmangt
Its a bit confusing in my opinion as docs advocate to use service account token, as it seems API Keys are being phased out 
https://grafana.com/docs/grafana/latest/administration/service-accounts/
can you clarify the roadmap for best practice in Grafana OSS going forward?

**Comment by usmangt** [comment]
Yes, it is indeed confusing as I also initially thought to use the Service account but after asking with team, it is meant to encourage the Grafana Enterprise users to use it as its more secure that the normal API key.

About the API key in Grafana OSS, they are still there and probably will not get phased out.

**Comment by noamApps** [comment]
thank you for the fast response 🙏

**Comment by lianghuiyuan** [comment]
<img width="781" alt="image" src="https://github.com/grafana/grafana/assets/8090998/eb6c3c30-2c17-4d63-9ed5-16d6c99b78fb">

https://grafana.com/docs/grafana/latest/administration/api-keys/
