### ISSUE TITLE
[Bug] Odd summarize behavior with M3QL

### ISSUE THREAD

**Issue by klnusbaum** [grafana/grafana#7891]
Grafana Version: 2.6
Datasource: M3QL
OS: Mac OSX

Description of problem:
I'm experiencing some really odd Grafana behavior. In the gif below the following annoyances happen:

1. Why does summarize magically reorder itself after I'd put the field above ailasByTags
2. Why can't I use my resolution template variable
3. I can't hit the enter key once summarize has become autoselected. I have to switch to mouse and click.
![jbqaejxp3z](https://cloud.githubusercontent.com/assets/495570/24113968/c66541fa-0d5b-11e7-9513-a30b7845ecf5.gif)

**Comment by mattttt** [comment]
Talked to @klnusbaum on Twitter DM. Let him know that we dont have any way to help as we dont have the code for this plugin, nor have used it ourselves. 

@mmihic Do you or your team have any insight here? I did a quick search for m3 (and related) on the official @uber account but couldnt find anything.

**Comment by torkelo** [comment]
Since this is a third party plugin not developed by the core team it's hard for us to help.
