### ISSUE TITLE
Correlations: Move data links in logs visualization to somewhere more accessible

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#78924]
Data links are always associated with one field. In the logs visualization, the data link appears next to the field, meaning the user must expand the log context to see any data links in the fields for that log line. For some users with a lot of information in one log line, that can also mean scrolling through many lines as expanding the log line will fill the page. 

Investigate options for moving data links up the heirarchy of a log line so they are more easily visible.

Idea 1: surface all fields in the new Logs Table view
The new logs table view does render data links in the table, which surfaces them the way that was requested. The downside is the table currently only supports 2 fields, so the correlation has to be created on one of those two fields for it to be visible. The user would have to know that, and also know that the table view is where you'd see links in this way.

The performance impact is lessened by the table being virtualized and only rendering partial data at a time.

![Image](https://github.com/grafana/grafana/assets/1533128/64a523c3-7946-46bc-94ab-8d9d3d06d3d7)
![Image](https://github.com/grafana/grafana/assets/1533128/083b238d-fdac-479a-b48f-86477d6549d9)

Idea 2: Lazy load correlations after initial render

**Comment by Elfo404** [comment]
Closing this as there's nothing actionable we can do right now, we may pick this up again in the future.
