### ISSUE TITLE
Dashboards: Grafana shows datasource UID instead of name in legend

### ISSUE THREAD

**Issue by dmitriishaburov** [grafana/grafana#78949]
### What happened?

We're using datasource variable in dashboard, and putting it into legend in some panels.
Before it was rendering datasource name picked via dropdown.
After update to 10.1.0 and later it's rendering datasource UID instead.

### What did you expect to happen?

Panel legend that's using `${datasource}` should render datasource name instead of UID

### Did this work before?

Yes, last version is 10.0.9

### How do we reproduce it?

1. Create datasource kind variable in dashboard, i.e. named `datasource`
2. Put it into legent in panel, i.e. `${datasource} - usage`
3. Datasource will be shown as UID instead of name in dropdown.
![image](https://github.com/grafana/grafana/assets/75983712/bb8d1cc9-5539-4f6d-9615-c56b593a61a0)

### Environment (with versions)?

Grafana: 10.2.2
OS: Windows 11
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by dmitriishaburov** [comment]
@adela-almasan sorry, last working version was `10.0.9`, not `10.9.0` 😄

**Comment by baldm0mma** [comment]
Hey @dmitriishaburov , this was an intentional change, and can be reflected in the "breaking changes" category of our CHANGELOG for `10.1.0 (2023-08-22)`, and was created in this PR: #69259.

From the above CHANGELOG:
```
The data source template variable type has changed the way it represents its options. The text field still represents the data source name, but the value has been changed to the uid of the data source. This allows dashboards to declare the currently selected option by uid, however it changes how a datasource template variable value will be rendered by default. If the name of the data source is expected, the variable syntax will have to be changed to specify the [text format](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#text).
```

In other words, if you try `${datasourceVariable:text}` instead of `${datasourceVariable}`, I believe that should solve the issue.

**Comment by dmitriishaburov** [comment]
Oh, sorry, will pay more attention to that changelog instead of `what's new in Grafana X` 😢 
Thanks for explanation

**Comment by baldm0mma** [comment]
> Oh, sorry, will pay more attention to that changelog instead of `what's new in Grafana X` 😢 Thanks for explanation

No worries. There's a lot of new features and changes all the time; it's even hard for **_us_** to keep track! ☺️
