### ISSUE TITLE
[Bug]smtp failed

### ISSUE THREAD

**Issue by dlintw** [grafana/grafana#7894]
Please include this information:
- What Grafana version are you using? 4.3.0-pre1 (commit: b05fca4fd)
- What datasource are you using? prometheus
- What OS are you running grafana on? Arch Linux
- What did you do? create notification channels
- What was the expected result? send test mail successful
- What happened instead? got error message

grafana.ini
```
[smtp]                                                                                                                                                                                        
enabled = true                                                                                                                                                                                
host = localhost:25                                                                                                                                                                                  
user =                                                                                                                                                                                        
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""                                                                                                
password =                                                                                                                                                                                    
cert_file =                                                                                                                                                                                   
key_file =                                                                                                                                                                                    
skip_verify = true                                                                                                                                                                            
from_address = myid@mydomain.com
from_name = Grafana                                                                                                                                                                           
```                                                                                                                                                                                              

error log
```
t=2017-03-21T10:40:35+0800 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-03-21T10:40:35+0800 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[myid@mydomain.com]
t=2017-03-21T10:40:35+0800 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp [::1]:25: getsockopt: connection refused"
t=2017-03-21T10:40:35+0800 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="dial tcp [::1]:25: getsockopt: connection refused"
t=2017-03-21T10:40:35+0800 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=[::1] time_ms=2ns size=4
```

**Comment by torkelo** [comment]
and your sure there is a working smtp server on port 25 on the same server as grafana-server?

**Comment by dlintw** [comment]
I use Arch Linux, I can use mailx to send e-mail out, mailx is provided by s-nail package.  Because it can just send e-mail in intranet, I don't require to setup extra external smtp server. The following command workable.

eg. echo test | mailx -s 'test' myid@mydomain.com

Do you know what's command I should test for the base of grafana workable for debug purpose?  I've ever check old version Go has a bug related to sent IPv6  e-mail.  But I use Go 1.8 to compile, it should not have such issue.  I'm testing grafana in Virtualbox which is IPv6+IPv4.  Outside of the box, it is IPv4(eg. the mail server of myid@mydomail.com)

**Comment by torkelo** [comment]
ok, then it's probably related to this issue: 
https://github.com/grafana/grafana/issues/7189

**Comment by dlintw** [comment]
@torkelo In my case, I don't require TLS to send e-mail, I can just use mailx to send without setup TLS.

**Comment by torkelo** [comment]
yes, seems to be an issue with SMTP servers that do not use TLS

**Comment by Aananth1995** [comment]
Using Gmail's SMTP is working fine. The configuration is given below, hope this is useful.

#################################### SMTP / Emailing #####################
[smtp]
enabled = true
host = smtp.gmail.com:465
user = abcd@gamil.com
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password ="password123"
cert_file =
key_file =
skip_verify = true
from_address = abcd@gamil.com
from_name = Grafana

[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html
