### ISSUE TITLE
Add InfluxDB Datasource from Remote Server using OMD-Labs with Grafana 4.1.2

### ISSUE THREAD

**Issue by lukas-kd** [grafana/grafana#7896]
Hi there,

i have 2 OMD-Labs Server with InfluxDB + Nagflux (Monitoring Core: Naemon) and Grafana 4.1.2.

I want to add an Datasource from Server 1 to Server 2.

**My Datasource Settings are:**
**Type**: InfluxDB
**URL**: "remote-ip":8086
**Access**: proxy
**Database**: nagflux
**User**: "username"
**Password**: "password"

On Server 1 i use the exact same settings (only that i'm accessing the local InfluxDB).

**Grafana Version**: 4.1.2
**Datasource**: InfluxDB
**OS**: CentOS 7
**What did you do?**: Trying to add a remote datasource from server 1 to server 2.
**What was the expected result?**: To have the InfluxDB from server 1 at server 2.
**What happened instead?**: I get the following error:
"Unknown error
InfluxDB Error: undefined"

In the grafana.log file i have this entry:
t=2017-03-22T08:50:48+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=omdadmin method=GET path=/query status=502 remote_addr=" "ip-local-pc", "ip-local-pc" " time_ms=16ns size=0

Any Idea how to solve this?

**Comment by daniellee** [comment]
Usually if you get an HTTP Error 502, then the actual error is on the line above it in the logs. That would help to troubleshoot this.

Here is an example:

```
2017/03/21 13:49:29 http: proxy error: dial tcp 127.0.0.1:8001: getsockopt: connection refused
INFO[03-21|13:49:29] Request Completed                        logger=context userId=10 orgId=1 uname=danielt8 method=GET path=/api/v1/namespaces status=502 remote_addr=127.0.0.1 time_ms=5ns size=0
```

**Comment by lukas-kd** [comment]
This is the line above:
`2017/03/22 13:48:00 http: proxy error: dial tcp 192.9.200.9:8086: getsockopt: connection refused`

`t=2017-03-22T13:48:00+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=omdadmin method=GET path=/query status=502 remote_addr="192.168.1.243, 192.168.1.243" time_ms=17ns size=0`

**Comment by daniellee** [comment]
Looks like you do not have access to that IP address with that port. Can you ping `192.9.200.9` and curl (or access with the browser) `192.9.200.9:8086` from Server 2?

**Comment by lukas-kd** [comment]
I can ping 192.9.200.9 from Server 2. When i do `curl 192.9.200.9:8086` i get the following: `curl: (7) Failed connect to 192.9.200.9:8086; Verbindungsaufbau abgelehnt`.
I disabled firewalld on Server 1 (192.9.200.9), same error.

**Comment by lukas-kd** [comment]
`netstat -tulpn` shows this:
`[root@kiho-srv-omd ~]# netstat -tulpn
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      28031/influxd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4382/sshd
tcp        0      0 127.0.0.1:8088          0.0.0.0:*               LISTEN      28031/influxd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1582/master
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN      23339/nrpe
tcp        0      0 127.0.0.1:8003          0.0.0.0:*               LISTEN      28244/grafana
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      469/httpd
tcp6       0      0 :::80                   :::*                    LISTEN      4753/httpd
tcp6       0      0 :::22                   :::*                    LISTEN      4382/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1582/master
tcp6       0      0 :::443                  :::*                    LISTEN      4753/httpd
tcp6       0      0 :::6557                 :::*                    LISTEN      28409/xinetd
tcp6       0      0 :::5666                 :::*                    LISTEN      23339/nrpe
udp        0      0 0.0.0.0:41511           0.0.0.0:*                           11641/snmpget
udp        0      0 0.0.0.0:53934           0.0.0.0:*                           11272/snmpget
udp        0      0 0.0.0.0:38317           0.0.0.0:*                           12288/perl`

**Comment by daniellee** [comment]
Did you figure it out? If you cannot curl it then grafana will not be able to access it either.

**Comment by harshal-raina** [comment]
Installed edgex with grafana on an ubuntu 16.0.4 system, graphs and other data metrics are working perfectly on that system. But while accessing it via IP remotely, the grafana page loads and show all the graphs and meters with specified name on it but doesn't show any readings(even the graphs).
Using localhost 3000 for grafana. Influx_db is being used for datasource. Also checked data is being received on the system(ubuntu in which edgex is installed).  
Any idea what might be the problem? 
Tried upgrading and downgrading the container but that didn't help!
