### ISSUE TITLE
[Feature Request] Deleting Multiple Dashboards

### ISSUE THREAD

**Issue by InH4te** [grafana/grafana#7897]
Hi,

Tried looking for a similar request but couldn't find it.

Is there a functionality to delete multiple dashboards at once? I've got dashboards being created quite quickly and my dashboard home seems to filling up with unecessary dashboards. Going to each of them and hitting delete is cumbersome. Is there any easier way?

Much thanks!

**Comment by tiagoReichert** [comment]
+1

**Comment by torkelo** [comment]
this is possible in Grafana v5+
