### ISSUE TITLE
Alerting: Cannot unsilence and edit silences in 10.2.2

### ISSUE THREAD

**Issue by dmitriishaburov** [grafana/grafana#78999]
### What happened?

After update to 10.2.0 "Unsilence" and "Edit" buttons on silences page disappeared
![image](https://github.com/grafana/grafana/assets/75983712/692f8e10-b45a-4daf-bdaa-ec689b30242e)

### What did you expect to happen?

Being able to unsilence and edit silences as before 
![image](https://github.com/grafana/grafana/assets/75983712/875c935d-b087-46b1-ade0-2e7436b8273e)

### Did this work before?

Yes, last version is 10.1.5

### How do we reproduce it?

1. Update to Grafana 10.2.0 and higher
2. Go to Alerting - Silences page
3. There is no mentioned buttons

### Environment (with versions)?

Grafana: 10.2.2
OS: Windows 11
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by mvnarsing** [comment]
any ETA on when the 10.3 version will be released?

**Comment by gillesdemey** [comment]
Closing this one as it will be included in a future release and can you can obtain nightly builds if waiting for the 10.3 release is not an option.
