### ISSUE TITLE
10.2.0 rebuild error

### ISSUE THREAD

**Issue by V-yw** [grafana/grafana#79000]
### What happened?

i git clone version 10.2.0 ,use docker version 24.0.5 build grafana image ,

----------------------
Step 51/77 : ENV BUILD_BRANCH=${BUILD_BRANCH}
 ---> Running in d04b92d8b66f
Removing intermediate container d04b92d8b66f
 ---> b357e58ff603
Step 52/77 : RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}
 ---> Running in 9a19b38a4e65
generate go files
/go/bin/wire-v0.5.0 gen -tags oss ./pkg/server
wire: github.com/grafana/grafana/pkg/server: wrote /tmp/grafana/pkg/server/wire_gen.go
build go files
go run build.go  -build-tags=oss build
Version: 10.2.0, Linux Version: 10.2.0, Package Iteration: 1701679689
building binaries build
building grafana ./pkg/cmd/grafana
rm -r ./bin/linux-amd64/grafana
rm -r ./bin/linux-amd64/grafana.md5
go build -ldflags -w -X main.version=10.2.0 -X main.commit=unknown-dev -X main.buildstamp=1701679689 -X main.buildBranch=main -tags oss -o ./bin/linux-amd64/grafana ./pkg/cmd/grafana
go version
go version go1.20.10 linux/amd64
Targeting linux/amd64
building binaries build
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/linux-amd64/grafana-server
rm -r ./bin/linux-amd64/grafana-server.md5
go build -ldflags -w -X main.version=10.2.0 -X main.commit=unknown-dev -X main.buildstamp=1701679873 -X main.buildBranch=main -tags oss -o ./bin/linux-amd64/grafana-server ./pkg/cmd/grafana-server
go version
go version go1.20.10 linux/amd64
Targeting linux/amd64
building binaries build
building grafana-cli ./pkg/cmd/grafana-cli
rm -r ./bin/linux-amd64/grafana-cli
rm -r ./bin/linux-amd64/grafana-cli.md5
go build -ldflags -w -X main.version=10.2.0 -X main.commit=unknown-dev -X main.buildstamp=1701679873 -X main.buildBranch=main -tags oss -o ./bin/linux-amd64/grafana-cli ./pkg/cmd/grafana-cli
go version
go version go1.20.10 linux/amd64
Targeting linux/amd64
Removing intermediate container 9a19b38a4e65
 ---> c285cfd18f6b
Step 53/77 : FROM ${BASE_IMAGE} as tgz-builder
3.18.3: Pulling from library/alpine
7264a8db6415: Pull complete 
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:3.18.3
 ---> 7e01a0d0a1dc
Step 54/77 : WORKDIR /tmp/grafana
 ---> Running in 6cf2f7a0a8db
Removing intermediate container 6cf2f7a0a8db
 ---> 43bd29208de1
Step 55/77 : ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"
 ---> Running in 304e630e3f78
Removing intermediate container 304e630e3f78
 ---> 9d691cc1fdeb
Step 56/77 : COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz
COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist

### What did you expect to happen?

help me

### Did this work before?

10.2.2 version rebuild。The same thing happens when compiling and reporting an error.
https://github.com/grafana/grafana/issues/78157

### How do we reproduce it?

1. git clone
2. cd grafana-10.2.0 && docker build -t xxxx .
3. waiting

### Environment (with versions)?

Grafana: 10.2.0
OS: ubuntu 22.04
Browser:

### Grafana platform?

Docker

**Comment by aangelisc** [comment]
This should be fixed in the 10.2.3 release, if it isn't please reopen this issue 😊
