### ISSUE TITLE
Docs: Link from datasource to "Learn more about trace to logs"  incorrect

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#79003]
### What happened?

The link to **_Learn more about trace to logs"_** in picture below is not valid any more, since  https://github.com/grafana/grafana/pull/74291
![image](https://github.com/grafana/grafana/assets/89977373/d9d77d1f-4956-489d-8bd9-2102f5bf5876)

Link in grafana points to https://grafana.com/docs/grafana/next/datasources/tempo/#trace-to-logs
The information is now found on https://grafana.com/docs/grafana/next/datasources/tempo/configure-tempo-data-source/#trace-to-logs instead 

### What did you expect to happen?

Link from Grafana to documentation to be correct.

### Did this work before?

Yes, before 10.1

### How do we reproduce it?

Create new datasource, click link to documentation in **Trace to Logs** section

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2

### Grafana platform?

Docker

### Datasource(s)?

Tempo

**Comment by joey-grafana** [comment]
Hello, thanks for raising the issue however this should be updated since [this PR](https://github.com/grafana/grafana/pull/76678) in 10.2.3 :)
