### ISSUE TITLE
[Feature Request]: Users Confused about being Logged in with Anon Enabled

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#7902]
Ever since we enabled anonymous access, people are getting confused about their access levels or the validity of links because they do not realize that they are non logged in.

When we link to an existing dashboard, and they are not logged in they see:

![screen shot 2017-03-22 at 9 53 32 am](https://cloud.githubusercontent.com/assets/1692624/24201115/830e04b0-0ee5-11e7-92fe-5ae14273fe0b.png)

Perhaps when someone hits "dashboard not found" any there anonymous, the page could suggest that they may need to log in?

Or perhaps there should always be an "anonymous" indicator that is visible.

**Comment by torkelo** [comment]
not sure I understand, why is the dashboard not found for anonymous users? different org?

**Comment by kylebrandt** [comment]
That is correct. Anonymous has it's own org id:

![image](https://cloud.githubusercontent.com/assets/1692624/24201620/fefc6a66-0ee6-11e7-96b5-8ecffab496b8.png)

**Comment by torkelo** [comment]
think we can fix this quite easily after we change dashboards urls to include dashboard id:
https://github.com/grafana/grafana/issues/7883
