### ISSUE TITLE
[Feature request] Allow to customize a panel's "No datapoints" message

### ISSUE THREAD

**Issue by majewsky** [grafana/grafana#7904]
When the metric queries for a panel all turn up empty, it shows a message "No datapoints" in the panel area ([defined here](https://github.com/grafana/grafana/blob/3d4c3ff00d2cb1378138996e39cacfefe73b6a6b/public/app/plugins/panel/table/module.html#L26) in current master). I would like to be able to customize this message to read, e.g. "No errors", for a panel that only shows data when errors occur. I currently work around this by adding documentation to the title, which is pretty ugly:

<img width="717" alt="screen shot 2017-03-22 at 16 39 30" src="https://cloud.githubusercontent.com/assets/24696/24206318/2857df58-0f1e-11e7-8bba-85fce3962a9e.png">

**Comment by kylebrandt** [comment]
I also have this problem on some graph panels that are for showing annotations only.

I see the error message when I don't want it there, because in that case as well it is not an error, but intentional.
