### ISSUE TITLE
Bug High CPU with Influxdb datasource

### ISSUE THREAD

**Issue by Devon21** [grafana/grafana#7905]
Please include this information:
- What Grafana version are you using?
grafana-4.1.2-1486989747
- What datasource are you using?
Influxdb version 1.2.1
- What OS are you running grafana on?
Amazon Linux AMI release 2016.09

I'm having an issues with grafana-server Spiking CPU on the Influxdb server. Everytime grafana-server queries, it creates a spike in CPU on the influxdb server. This is causing dashboard to be very slow. 

We are using Telegraf 1.2.1 to gather data. 

Please let me know what I can do.

**Comment by torkelo** [comment]
Sounds like a problem with how you store data or query the data. Or maybe a CPU usage bug in InfluxDB? 

Please post questions to our community site
https://community.grafana.com/

Github is only for bug reports & feature requests and this seems like a problem in InfluxDB or a configuration problem. Maybe your just querying to much data?
