### ISSUE TITLE
[Feature request]Dashboard Graph show "No datapoints returned from metric query"

### ISSUE THREAD

**Issue by topdean2036** [grafana/grafana#7906]
Grafana 4.1.2
InfluxDB 1.2
CentOS release 6.5 (Final)

I'm a newcomer to Grafana and InfluxDB , when create a new Graph in dashboard, it show me a message "No datapoints returned from metric query", and no error message.
I have created data source for inluxdb, and test sucess.
Follow the troubleshoot I get the browser network Headers and Response(at the end of issue).
From request url, is seems not a correct query : SELECT mean("value") FROM "measurement", this query will return nothing from influxdb.

How can I create a Graph for influxdb, is there needs other config?

- Headers

General
Request URL:http://192.168.202.151:3000/api/datasources/proxy/1/query?db=telegraf&q=SELECT%20mean(%22value%22)%20FROM%20%22measurement%22%20WHERE%20time%20%3E%20now()%20-%206h%20GROUP%20BY%20time(15s)%20fill(null)&epoch=ms
Request Method:GET
Status Code:200 OK
Remote Address:192.168.202.151:3000
Referrer Policy:no-referrer-when-downgrade

Response Headers
view source
Content-Encoding:gzip
Content-Length:62
Content-Type:application/json
Date:Thu, 23 Mar 2017 02:15:15 GMT
Request-Id:8d839ce7-0f6e-11e7-9460-000000000000
X-Influxdb-Version:1.2.1

Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Cookie:grafana_sess=c64c9894c6eec915; grafana_user=admin; grafana_remember=eee0bd83e0e3f931f5ce18d734c2721117e7b521764a0ba9
Host:192.168.202.151:3000
Pragma:no-cache
Referer:http://192.168.202.151:3000/dashboard/new?gettingstarted
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3026.3 Safari/537.36

Query String Parameters
view source
view URL encoded
db:telegraf
q:SELECT mean("value") FROM "measurement" WHERE time > now() - 6h GROUP BY time(15s) fill(null)
epoch:ms

- Response

{"results":[{"statement_id":0}]}

**Comment by topdean2036** [comment]
It needs to Click on the Title, and show the edit menu. It cost 1 day, now I got is ,thanks gods.

**Comment by daniellee** [comment]
Sorry to hear that you got stuck because of the UX. The current UI is focused on hiding as much as possible to make it look good on a big screen but we are aware that this can be confusing for new users. We plan on improving that in the coming months. In the meantime, maybe screencast nr. 7 here would be a good introduction to building dashboards: http://docs.grafana.org/guides/screencasts/
