### ISSUE TITLE
Save Dashboard: An unexpected error happened.

### ISSUE THREAD

**Issue by Alex-Kidston** [grafana/grafana#79074]
### What happened?

The following workflow generated an error in the Grafana UI:
- Home - Connections - data source - dashboards tab - import dashboard
- Home - Dashboards - open imported dashboard
- save dashboard - save
```
An unexpected error happened
TypeError: can't define property "isHandled": Object is not extensible

V@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:1330:1537
je@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:1358:9
r
l@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:224:13290
v@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:37:13858
d@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:629:177392
d@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:823:19905
o@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:204:119128
g@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:204:119637
y@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:181:94088
zf@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:4954:122
```

### What did you expect to happen?

![Screenshot 2023-12-05 at 13 08 31](https://github.com/grafana/grafana/assets/113187177/34cdfebb-b672-491d-8e91-32fadf4de6d1)

### Did this work before?

Yes - this works in all grafana flavours except v10.2.0 - v10.2.2

### How do we reproduce it?

see above

### Environment (with versions)?

Grafana: 10.2.2 / 10.2.1 / 10.2.0
OS: RHel 9.2 / CentOS 9 / ubuntu 23.10
Browser: FireFox 120.0 / Chrome 118

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @Alex-Kidston,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine.

Can you please share a small screencast/gif file so that we can see how you are able to reproduce it with your steps.

Thanks

**Comment by Alex-Kidston** [comment]
@usmangt, thanks for investigating...since this issue was created using one of our new backend datasource plugins, the best next step is probably to share replication steps once the plugin is published...

**Comment by Alex-Kidston** [comment]
Issue replication requested during Grafana dev team data source plugin review pre publication.

**Comment by Alex-Kidston** [comment]
@usmangt following the publication of our data source plugin:

https://grafana.com/grafana/plugins/ibm-kql-datasource

I'm attempting to replicate the issue:

Grafana Cloud - not replicated
Grafana v10.1.5 - not replicated
Grafana v10.2.2 - replicated
Grafana v10.2.1 - replicated
Grafana v10.2.0 - replicated
Grafana v10.2.3 - not replicated

Workflow
Data Source - Dashboards - Import Sample Dashboard - Save Dashboard - Save As

Expected
Dashboard saved under new name

Actual
```
An unexpected error happened
TypeError: can't define property "isHandled": Object is not extensible

V@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:1330:1537
je@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:1358:9
r
l@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:224:13290
v@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:37:13858
d@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:629:177392
d@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:823:19905
o@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:204:119128
g@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:204:119637
y@http://localhost:3000/public/build/958.b63f864e3aa7eee86718.js:181:94088
zf@http://localhost:3000/public/build/4019.8e650672867c3e4c40ad.js:4954:122
```
Next Step
We will add this as a known issue to our plugin support wiki with the workaround being to upgrade to Grafana v10.2.3.

**Comment by Alex-Kidston** [comment]
Closing as fix version found.
