### ISSUE TITLE
about elasticsearch

### ISSUE THREAD

**Issue by oklink** [grafana/grafana#7908]
I want to know，does grafana support that  joining two elasticsearch Index data ?  like joining two table
in the mysql

**Comment by torkelo** [comment]
Not sure, I would consult the Elasticsearch docs. 

You can query multiple indexes at a time with a single ES query, and you can even in Grafana using -- Mixed -- datasource query different ES servers in same panel, but "join" , that is cross match on id is not something Grafana does and maybe ES does it within their query API, not sure
