### ISSUE TITLE
UX: Bring back grafana 5 editing panel layout

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#79099]
I love Grafana but the UX has really gone downhill for dashboard creators/editors since grafana 6.

The edit right column is a nightmare to work with, everything is hidden inside sub-sections. Even though I am a heavy user, I spend a lot of time browsing through it and I never get it right.

Also, don't let me start about the "flex" layout of the queries area ... I'm working on a 15" laptop and scrolling through queries on half a 15" screen is horrendous. I don't really care to see the panel when I'm editing queries, please give me back all my screen's real estate.

And how frustrating to have the scrolling stop when your mouse hovers over a query field ...

Back then we had 3 simple tabs and every options available after a quick look. Wasn't as fancy as today but so much easier to work with when you heavily customize your panels.

I hope you will consider this.

Thank you.

**Comment by gelicia** [comment]
>  everything is hidden inside sub-sections

Have you played around with this search field, which lets you filter what options display?
<img width="338" alt="Screenshot 2023-12-05 at 11 42 19 AM" src="https://github.com/grafana/grafana/assets/1533128/aea4b1d2-1161-4933-be57-7c6756519dce">

> [...I'm not a fan of] the "flex" layout of the queries area [...] scrolling through queries on half a 15" screen is horrendous. I don't really care to see the panel when I'm editing queries, please give me back all my screen's real estate.

Have you played around this panel being resizable? The handle is in the middle. You can also collapse the options panel on the side, if needed. 

<img width="803" alt="Screenshot 2023-12-05 at 11 44 59 AM" src="https://github.com/grafana/grafana/assets/1533128/2b476fde-4151-49ab-8e0e-d344663a9b36">
<img width="192" alt="Screenshot 2023-12-05 at 11 45 05 AM" src="https://github.com/grafana/grafana/assets/1533128/13d9a845-d806-4d49-871f-b3458f8294ce">
<img width="1081" alt="Screenshot 2023-12-05 at 11 45 17 AM" src="https://github.com/grafana/grafana/assets/1533128/b6a27925-3124-4f4d-ab59-4d503a90de7e">



> And how frustrating to have the scrolling stop when your mouse hovers over a query field ...

Can you provide replication steps editing a panel on play.grafana.org ? https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2
