### ISSUE TITLE
[Bug] branch "alerting-elasticsearch" has problem of alert : "tsdb.HandleRequest() error type assertion to string failed"

### ISSUE THREAD

**Issue by eueuy** [grafana/grafana#7909]
this bug is very like https://github.com/grafana/grafana/issues/6456
but on elasticsearch datasources.

After creating a new alert using a elasticsearch query the server returns "tsdb.HandleRequest() error type assertion to string failed" when I want to test the rule.

**Comment by torkelo** [comment]
Please include Elasticsearch version (and your data source settings), and your ES query.

**Comment by torkelo** [comment]
and please post details to the open issue: https://github.com/grafana/grafana/issues/5893
