### ISSUE TITLE
Is there a way to script the playlist?

### ISSUE THREAD

**Issue by sogwiz** [grafana/grafana#791]
Hi,

is there a way to script a playlist?  

I'd like to be able to give my boss a url and this url would simply be a grafana playlist.  We could then put the playlist url on various monitors in our company. Right now, it seems like a playlist must be both created and started manually

Any thoughts are welcome and appreciated :)

**Comment by javenfang** [comment]
+1 for the feature:

playlist has url, can be defined many and tagged with name.

**Comment by TheHodge** [comment]
Also adding a +1 for this, we've just installed a new monitor ready for dashboards and would love to be able to go to /playlist to get them to auto rotate (I don't have the budget for a monitor per dashboard yet)

**Comment by bbinet** [comment]
+1, it would be great to be able to share playlists as permalinks

**Comment by sknolin** [comment]
+1 for me too.

**Comment by activars** [comment]
+1, it would be great if URL parameter can replace template parameter value.

**Comment by dzebleckis** [comment]
Hi, posting our solution to this problem, maybe someone will find it of any use.
Background: http://docs.grafana.org/reference/scripting/
Script: https://gist.github.com/dzebleckis/d938b5d0652e29aaaae4

**Comment by bergquist** [comment]
closed by #1137 

In the next release of Grafana it will be possible to start a playlist from an url.
