### ISSUE TITLE
default data source 

### ISSUE THREAD

**Issue by nicoamaro** [grafana/grafana#7910]
Is there anyway to set a datasource as default just using the API? 

- What Grafana version are you using?
 4.2.0
- What datasource are you using?
 Influxdb
- What OS are you running grafana on? 
debian

**Comment by torkelo** [comment]
> Read before posting:
Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue.
Checkout FAQ: https://community.grafana.com/c/howto/faq
Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

please post questions to the community site:
https://community.grafana.com.
