### ISSUE TITLE
Variables do not work with Filter data by values Transformation

### ISSUE THREAD

**Issue by R2DToo** [grafana/grafana#79118]
### What happened?

I created a brand new dashboard, added some variables of query and custom type. Then created a panel with some data I'd like to filter. I added the Filter data by values transformation but it does not show the variable dropdown to select from, nor does it work if I type the variable in manually like $variableName.

### What did you expect to happen?

I expected to see a variable dropdown within the value field of the Filter data by values transformation as shown in the video here https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-2/#use-dashboard-variables-in-transformations. Typing $ or Ctrl + Space should show the dropdown but they do not.

### Did this work before?

No this is a new experimental feature added in Grafana 10.2

### How do we reproduce it?

1. Update to the latest version of Grafana (10.2.2 at the time of writing)
2. Create a new dashboard
3. Add one query or custom type variable (My variable options are numbers not strings)
4. Create a panel and query some data which can be filtered
5. Add the Filter data by values transformation 
6. Add a condition on a number type field
7. Set the match field to equal
8. Within the value field type $ or press Ctrl + Space and observe there is no menu shown
9. Type the variable manually ($variableName) into the value field and observe that this does not work

### Is the bug inside a dashboard panel?

The bug is affecting dashboard panel transformations

### Environment (with versions)?

Grafana: v10.2.2
OS: Zorin OS 16 (Based on Ubuntu)
Browser: Google Chrome v119 

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hi @R2DToo 

it seems that this is not yet supported in the filter data by values transformation

https://github.com/grafana/grafana/issues/25469#issuecomment-846311484

I will reach out internally to the maintainers to find more details about this topic

**Comment by lalitdhami007** [comment]
![image](https://github.com/grafana/grafana/assets/81741142/d6808d35-85dd-4f6e-ba69-1d2d64e1449e)
I also checked on 10.2 version but this feature is missing but in documentation they added this

**Comment by lalitdhami007** [comment]
Any update on this feature

**Comment by tonypowa** [comment]
I appreciate your waiting @R2DToo 

So, I have reached out to the code owners and they have told me that indeed they have added support for using variables in transformations, behind a  feature toggle. You can activate it by modifying the[ .ini file](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles) of your local Grafana instance. 

The feature toggle that allows using variables in transformations is called `transformationsVariableSupport` and it is listed [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#preview-feature-toggles) 

If you are on Docker, you can easily activate this feature toggle by adding the following environment variable:

`- GF_FEATURE_TOGGLES_ENABLE=transformationsVariableSupport`


Note: The feature toggle is in preview phase. But I have tested it and it worked for me!

![image](https://github.com/grafana/grafana/assets/45235678/4119c066-1f2d-41dd-9a20-affb8e66a497)

Let us know if this helped you!

**Comment by R2DToo** [comment]
Hi @tonypowa,

Thank you very much for looking into this and pointing out the exact configuration that is required!
Now that I have updated the feature toggles I can see the feature is working as expected!

Thanks,
Braden (R2DToo)

**Comment by guimaurer** [comment]
I solved it by adding it to grafana.ini

```
enable = transformationsVariableSupport
transformationsVariableSupport = true
```
