### ISSUE TITLE
Can not run command "bra run" when install Grafana from source

### ISSUE THREAD

**Issue by dejokuondi** [grafana/grafana#7911]
When I run command "bra run":

root@grafana-source:/home/ubuntu/grafana/src/github.com/grafana/grafana# bra run
No command 'bra' found, did you mean:
 Command 'bar' from package 'bar' (universe)
 Command 'br' from package 'bottlerocket' (universe)
 Command 'bwa' from package 'bwa' (universe)
 Command 'brag' from package 'brag' (universe)
 Command 'bro' from package 'bro' (universe)
 Command 'ra' from package 'argus-client' (universe)
 Command 'ara' from package 'ara' (universe)
bra: command not found

Please help me! Thanks ^^

**Comment by dejokuondi** [comment]
This is my history:

1  sudo apt-get update
2  mkdir grafana
3  cd grafana/
4  export GOPATH='/home/ubuntu/grafana'
5  go get github.com/grafana/grafana
6  sudo apt-get install golang-go
7  cd $GOPATH/src/github.com/grafana/grafana
8  go get github.com/grafana/grafana
9  cd $GOPATH/src/github.com/grafana/grafana
10  sudo go run build.go setup
11  sudo go run build.go build
12  sudo apt install npm
13  sudo npm install -g yarn
14  curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
15  sudo apt-get install -y nodejs
16  yarn install --pure-lockfile
17  sudo npm install -g grunt-cli
18  grunt
19  go get github.com/Unknwon/bra
20  bra run

**Comment by dejokuondi** [comment]
http://stackoverflow.com/questions/32688414/how-to-install-grafana-on-mac

**Comment by dejokuondi** [comment]
https://groups.io/g/grafana/topic/grafana_package/4414211?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,4414211

g1zm0 said that: "Ok, but as I said before, you must execute bra with its absolute or relative path
$GOPATH/bin/bra run"

But It cannot find package "context"...

[Bra] 03-23 07:35:44 [DEBUG] Running: go [build -o ./bin/grafana-server ./pkg/cmd/grafana-server]
pkg/cmd/grafana-server/server.go:4:2: cannot find package "context" in any of:
        /home/ubuntu/grafana/src/github.com/grafana/grafana/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/ubuntu/grafana/src/context (from $GOPATH)
[Bra] 03-23 07:35:45 [ WARN] Fail to execute command: go [build -o ./bin/grafana-server ./pkg/cmd/grafana-server] - exit status 1
^C

**Comment by torkelo** [comment]
you set gopath as env var for your user  but then you sudo go get. 

Not sure why you sudo so much.

**Comment by daniellee** [comment]
I would start again and follow the instructions here: https://github.com/grafana/grafana#get-code without using sudo for everything (except for sudo npm install -g grunt-cli).
