### ISSUE TITLE
Text Panel JQuery function to refresh when grapana event is clicked

### ISSUE THREAD

**Issue by venkatesanlalitha** [grafana/grafana#7913]
Hi All,

I had written a Text Panel JQuery function which gets a specific data from my database. I want to refresh when any grapana button event is clicked. I am not able to catch the same.

My text panel JQuery is working successfully when Grafana loads, but not on any Grafana button click. I am also able to take the Grafana time from Angular JS.

Please help

Thanks in advance.

**Comment by torkelo** [comment]
text panel & javascript embedded in this panel is not ment to interact with the rest of grafana frontend services. for that you need to develop a proper plugin: 
http://docs.grafana.org/plugins/developing/development/
