### ISSUE TITLE
Panel issues starting with iOS 17.2 (mobile devices)

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#79176]
### What happened?

Starting with iOS 17.2, dashboards are running into issues. Some panels are not displayed until the user start scrolling. 

### What did you expect to happen?

All panels are visible immediately after loading a dashboard on mobiles.

### Did this work before?

YES, issue is starting with iOS 17.2. Reproduced on Safari. Issue also reproducible on browsers which are using Apples WebKit.

### How do we reproduce it?

1. update iOS to 17.2 RC (public release next week)
2. open a dashboard
3. first panels are missing the most of the time

https://github.com/grafana/grafana/assets/14274103/388e8198-f050-45ae-a7d5-ef07cdbac306

### Environment (with versions)?

Grafana: 10.2.2
OS: Ubuntu Focal
Browser: Safari

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment]
hi @jostrasser 

Thank you for reporting this issue

Could you please confirm if the issue persists across all dashboards or if it's specific to a certain type of panel, and data source (influxDB)?

Also , can you confirm whether this issue occurs with browsers on desktop versions (using the same WebKit versions) or is it strictly on mobile iOS 17.2?

Thank you!

**Comment by jostrasser** [comment]
Hi @tonypowa 

I am able to reproduce it on multiple dashboards but can confirm that on all of these dashboards the "Stats panel" is on the first position on the mobile view. I think you should focus on the Stats panel ;)

Thanks!

**Comment by jostrasser** [comment]
@tonypowa I tested now the RC for iOS 17.3 which will be released next week to the public and I can confirm that the issue still persists.

**Comment by jostrasser** [comment]
@tonypowa any updates on this? Thank you!

**Comment by iculda** [comment]
I think is the same with [82975](https://github.com/grafana/grafana/issues/82975)
and i think is related to the length of the dashboard
when length is greater than the browser size (need to scroll) some of the panels disappears

**Comment by jostrasser** [comment]
I can't reproduce it with iOS 17.4 / Grafana 10.4 or newer.
