### ISSUE TITLE
[Bug] Empty/broken snapshot

### ISSUE THREAD

**Issue by rburchell** [grafana/grafana#7917]
> - What Grafana version are you using?

4.1.1.

> - What datasource are you using?

InfluxDB.

> - What OS are you running grafana on?

macos.

> - What did you do?

Created a snapshot of a working dashboard. See https://snapshot.raintank.io/dashboard/snapshot/ublE1rTR3q7B9l5d6iBDzMmPKJNcchsB

> - What was the expected result?

It appears as usual.

> - What happened instead?

It's broken, and reports flotchart errors in console (flotcharts error RangeError: Maximum call stack size exceeded)

**Comment by daniellee** [comment]
This looks like it is a large dashboard. The default timeout when taking snapshots is 4 seconds so it looks like it timed out before all the snapshot data was saved. In the recently released 4.2.0, there is now an option for increasing the timeout (#7449).

![image](https://cloud.githubusercontent.com/assets/434655/24283432/0095a06a-1066-11e7-9211-b21e34e03c1f.png)

**Comment by rburchell** [comment]
A smaller subset of the dashboard exhibits the same problem: https://snapshot.raintank.io/dashboard/snapshot/Yyn7zQkc3wjmj0mf6JNtc8G3ZfRIX3uA

Also strange is that while this is loading, I do see some content (at least, legends, and the text at the top of the dashboard). Everything flickers to blank at the end of the load though.

**Comment by daniellee** [comment]
Can you try shortening the time interval to 5 minutes and see if there is any difference?

Another question: is this a file based dashboard or a normal dashboard?

**Comment by rburchell** [comment]
There aren't many data samples involved here. We're talking quite low frequency data (maybe 16 data points per graph per day, each day), so I don't think shortening the interval would do all that much. Or is the amount of data not relevant here? I can try again on Monday if needed (I'm proxying this report for someone else with access to the system in question, so I can't do it myself)

> Another question: is this a file based dashboard or a normal dashboard?

Not familiar with what the difference is here, excuse my ignorance. The snapshots came from an actual Grafana instance - or can you explain what you mean / what to check?

**Comment by daniellee** [comment]
@rburchell never mind about the file based dashboards - it's a feature that we are phasing out. How did it go with the snapshot this time?

**Comment by svagner** [comment]
Guys, in my case reason of this behaviour is using annotation with elasticsearch data bag. Any timeouts don't help...

**Comment by rburchell** [comment]
I am indeed also using annotations, with Influx. I haven't yet been able to retry this on the problematic instance. It's in the midst of being transitioned elsewhere. Sorry for the lack of update.

**Comment by rburchell** [comment]
Just going to close this. I can't reproduce my original problem at the moment.
