### ISSUE TITLE
Excessive memory usage -> grafana crashes

### ISSUE THREAD

**Issue by jA103** [grafana/grafana#79203]
### What happened?

Grafana allocates too much memory when uses table panels. This leads to out of memory. 

### What did you expect to happen?

The table will use the new query instead of either letting the existing one run out or terminating the existing one. Or there is much worse memory management.

### Did this work before?

NO

### How do we reproduce it?

1. Create Table 
2. Use a large number of records
3. Click the refresh button as fast as the browser allows.

```
{
  "datasource": {
    "type": "elasticsearch",
    "uid": "vASHHiT7z"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "cellOptions": {
          "type": "auto"
        },
        "inspect": false,
        "filterable": true
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "attack_type"
        },
        "properties": [
          {
            "id": "custom.width",
            "value": 294
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "geoip.city_name"
        },
        "properties": [
          {
            "id": "custom.width",
            "value": 152
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 1
  },
  "id": 26,
  "options": {
    "showHeader": true,
    "cellHeight": "sm",
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "countRows": false,
      "fields": ""
    },
    "sortBy": []
  },
  "pluginVersion": "10.1.2",
  "targets": [
    {
      "alias": "",
      "bucketAggs": [],
      "datasource": {
        "type": "elasticsearch",
        "uid": "vASHHiT7z"
      },
      "metrics": [
        {
          "id": "1",
          "settings": {
            "limit": "5000"
          },
          "type": "logs"
        }
      ],
      "query": "host_header: $host_header",
      "refId": "A",
      "timeField": "@timestamp"
    }
  ],
  "title": " ",
  "transformations": [
    {
      "id": "filterFieldsByName",
      "options": {
        "include": {
          "names": [
            "@timestamp",
            "attack_type",
            "geoip.city_name",
            "geoip.country_name",
            "message",
            "policy_name",
            "request",
            "request_status",
            "response_code",
            "severity_label",
            "unit_hostname",
            "uri",
            "violations",
            "vs_name",
            "host_header"
          ]
        }
      }
    },
    {
      "id": "organize",
      "options": {
        "excludeByName": {},
        "indexByName": {
          "@timestamp": 0,
          "attack_type": 2,
          "geoip.city_name": 4,
          "geoip.country_name": 5,
          "host_header": 1,
          "message": 6,
          "policy_name": 7,
          "request": 8,
          "request_status": 3,
          "response_code": 9,
          "severity_label": 10,
          "unit_hostname": 11,
          "uri": 12,
          "violations": 13,
          "vs_name": 14
        },
        "renameByName": {}
      }
    }
  ],
  "type": "table"
}
```

### Environment (with versions)?

Grafana: 10.2.0 to latest (10.2.2).
OS: Windows 10 Enterprise
Browser: MS Edge

### Grafana platform?

I don't know

**Comment by jA103** [comment]
Hi, thank you for your questions, answers are below.


  *   How much memory is being allocated and what is the total available memory on the system where Grafana is running?
250MB is normal stable allocation
400MB - X GB when issue.. we have 400MB limit (higher limit is not solution)

  *   Is this behavior observed with a specific dashboard or with all dashboards that include table panels?
More dashboards, more ELK data sources - it depends at least on "Limit" attribute - higher value means more MEM.

***@***.***

  *   Have you tried monitoring the memory usage over time? It would be helpful to have a screenshot or graph showing memory usage that correlates with Grafana crashes.

Picture shows 2x restart (16:32, 16:45)
***@***.***

  *   Can you provide information about your Elasticsearch datasource, such as the version and resource allocation?
ELK v 8.7.0
ELK resource allocation - what do you mean? I dont know MEM allocation for the datasource. Disk is not important. Old grafana is stable (MEM is stable).

  *   Are there any error messages or logs you can share that occur when Grafana crashes due to excessive memory usage?
No - only more MEM needed.

jA

**Comment by undef1nd** [comment]
@grafana/plugins-platform folks, could you please take a look? It might be within your area of expertise. Thanks

**Comment by marefr** [comment]
This sounds more related to Elasticsearch without any further details. So @grafana/observability-logs can you please have a look?

**Comment by jA103** [comment]
As I said, it occurs on the new version of grafana. Not with the new Elastic.

**Comment by svennergr** [comment]
Hi @jA103 

thanks for the bug report. Could you please try disabling the `enableElasticsearchBackendQuerying` feature toggle? 
You can follow the following documentation: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles

Once disabled and Grafana is restarted, please try to reproduce the issue and report back.

Thank you!

**Comment by jA103** [comment]
Hi, YES, enableElasticsearchBackendQuerying: false helped. When is set to false, memory is stable. The issue can be closed for me. But in general, it would probably be good to optimize this new feature.

Thanks for identifying the cause and suggesting a solution (thumb up).

**Comment by jA103** [comment]
Thank you. Hope and believe you will mention it in the changelog in the future 🙂

jA
