### ISSUE TITLE
Improve reliability of costmanagementui navtree changes

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#79221]
During https://github.com/grafana/support-escalations/issues/8623 we identified an issue with the Cost Management App navtree tweaks where the Adapative Metrics/Logs app can disappear from the navtree completely if the `costManagementUi` feature toggle is enabled but the `grafana-costmanagement-app` app is not installed.

We should make the admin IA tweaks more resiliant and make sure the nodes are not removed completely.

**Comment by abannachGrafana** [comment]
Since we're live for cost management in all environments I plan on removing the feature flag and defaulting the placement of adaptive metrics and log volume explorer under cost management.

**Comment by ashharrison90** [comment]
thanks for confirming @abannachGrafana 

will close this 👍
