### ISSUE TITLE
Alert are marked as updated even if nothing changed

### ISSUE THREAD

**Issue by benoittgt** [grafana/grafana#79235]
Hello

I am syncing 400+ alerts using Grafana API every 30min via a crontask. 98% of the time nothing change, but since few days I am seeing frequently alert going “normal” with the information “updated”… but I changed nothing. It generates 100+ of Slack notification of “Resolved”, then after the next evaluation if some of those alerts were firing, X Slack alerts.

To avoid that, I sync during a mute interval, but I don’t understand why it was working before without changing alarm state and not now.

Shouldn't we keep previous state if nothing has been changed on the alarm?

![View_rule_-_Alert_rules_-_Alerting_-_Grafana](https://github.com/grafana/alerting/assets/8417720/da89746e-579b-4d4b-ac51-db03390d08cf)

**Comment by benoittgt** [comment]
I can confirm that it fix the issues. Thanks for the patch.

**Comment by yuri-tceretian** [comment]
Thanks for confirming!
