### ISSUE TITLE
[Feature Request] Sensu Notifier: Have Sensu event source not tied to alerting rule ID

### ISSUE THREAD

**Issue by fir4** [grafana/grafana#7924]
Version: 4.2.0

Right now, the Sensu Notifier posts results to the Sensu API as the "grafana_rule_XX" source and uses the alert name set in grafana. This doesn't make much sense, for two reasons:
 * Assuming you have a single Grafana instance, it will appear as N sources if you have N different alerts fire
 * Assuming you have several Grafana instances, IDs will overlap so sources are not tied to the actual grafana instances and meaningless

This is mostly unpractical by the fact that if you have a lot of Grafana alerts firing, they'll appear as different source hosts, and have to be deleted/resolved/silenced one by one...

I propose to instead use either the instance name or an user provided parameter as "source" when routing the notifications to sensu. This ensures notifications from Grafana do not appear as coming from different hosts/sources. To ensure the event names are unique, the ID could be prefixed to rule name instead of put into the source.

Tagging @jaxxstorm as the original implementer of the Sensu notifier

**Comment by jaxxstorm** [comment]
This shouldn't be too hard to implement, and also allows the flexibility. As long as you set some kind of default if the source doesn't exist.

I'm not currently using this any more as the grafana alerting doesn't work with templated dashboards, which made it untenable. Hopefully someone else will be able to pick it up.
