### ISSUE TITLE
failed to save and apply Alertmanager configuration: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by shlomimn** [grafana/grafana#79248]
### What happened?

I connected my Grafana(9.4.17) to RDS-postgres version-15 (15.3).
Then I tried to create a new contact point,

![image](https://github.com/grafana/grafana/assets/20398208/16b08225-157b-4049-bb34-3ef901c142f1)

And after pressing "Save contact point", I got an error.
 
![image](https://github.com/grafana/grafana/assets/20398208/f115819a-db06-4b33-a9c5-c39ae4b0f272)

**kubectl logs grafana-pod**

logger=ngalert.multiorg.alertmanager t=2023-12-07T20:04:12.529254712Z level=error msg="**unable to save and apply alertmanager configuration**" error="**pq: there is no unique or exclusion constraint matching the ON CONFLICT specification**"
logger=context userId=34 orgId=1 uname=my-user@controlup.com t=2023-12-07T20:04:12.529368398Z level=error msg="failed to save and apply Alertmanager configuration: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification" error="failed to save and apply Alertmanager configuration: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification" remote_addr=10.204.111.141 traceID=
logger=context userId=34 orgId=1 uname=my-user@controlup.com t=2023-12-07T20:04:12.529451502Z level=info msg="Request Completed" method=POST path=/api/alertmanager/grafana/config/api/v1/alerts status=400 remote_addr=10.204.111.141 time_ms=263 duration=263.067036ms size=165 referer="https://grafana-url/alerting/notifications/receivers/new?alertmanager=grafana" handler=/api/alertmanager/grafana/config/api/v1/alerts

### What did you expect to happen?

To add a new contact point without an error,
As it was before I migrated my Grafana's sqlite to RDS.

### Did this work before?

Only when connected to SQLite DB.

### How do we reproduce it?

1. Add database parameters in configmap
  database:
    type: postgres
    host: rds-endpoint
    user: postgres
    password: password

2. Activate connection to RDS by scaling grafana deployment to 0 and then to 1.
3. Accessing Grafana UI
4. Try to add a new contact point.

### Is the bug inside a dashboard panel?

No,
It is in Alerting -> Contact points
![image](https://github.com/grafana/grafana/assets/20398208/d14a3b86-ba6a-4679-b26c-89938c65066c)

### Environment (with versions)?

Grafana: 9.4.17
OS: 20.04 Ubuntu
Browser: Google Chrome

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @shlomimn 

thank you for reporting this issue

Can you confirm if the PostgreSQL RDS instance has any specific configurations or permissions that might differ from a standard setup, which could potentially affect the creation of contact points?

thank you

**Comment by armandgrillet** [comment]
We think that the move from SQLite to RDS is missing an index. You can fix the index yourself or start Grafana with new database so that it creates the schema and move that to the correct schema.

What specific RDS settings are you using? Are you using native Postgres or something with a Postgres compatibility layer?

**Comment by JacobsonMT** [comment]
Closing as stale
