### ISSUE TITLE
[Bug] api/alerts and api/alert/:id hold previous data for "message" and "Message" field when field value is changed from "some string" to empty string.

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#7927]
Bug has been reproduced on v4.2.0, v4.1.2, v4.1.1.

1) Create a new alert with empty message + save dashboard
2) Select view JSON for that new dashboard -> produced output contains "message": ""
3) GET http://grafana/api/alerts -> produced output for the alert contains "message": "" 
4) GET http://grafana/api/alerts/:id -> produced output for the alert contains "message": "" and "Message":""
5) Change message field from empty to "foobar" + save dashboard
6) Select view JSON -> produced output contains "message": "foobar"
7) GET http://gragana/api/alerts -> produced output for the alert contains "message": "foobar"
8) GET http://grafana/api/alerts/:id -> produced output for the alert contains "message": "foobar" and "Message":"foobar"
9) Change message field from "foobar" back to empty + save dashboard
10) Select view JSON for that new dashboard -> produced output contains "message": ""
11) GET http://grafana/api/alerts -> produced output for the alert contains "message": "foobar"  which is the bug as there is no more "foobar" value for the message field. 
12) GET http://grafana/api/alerts/:id -> produced output for the alert contains "message": "" and "Message":"foobar" which is also a bug

**Comment by torkelo** [comment]
thanks for reporting this!
