### ISSUE TITLE
Plug-in permission issues

### ISSUE THREAD

**Issue by huozhirui** [grafana/grafana#79287]
I wrote a plug-in with a backend app. I registered it in Grafana. Only users with Admin permissions can see this plug-in, but users with editor permissions cannot. How can I let editor users see this plug-in?
![image](https://github.com/grafana/grafana/assets/55824382/877eda0c-2aa9-4c2b-870a-3c8538ae54b6)

**Comment by usmangt** [comment]
Hi @huozhirui,

Thanks for opening this issue.

Can you please reference the link to the documentation where it says that the plugin is accessible for users with "editor permissions"?

**Comment by huozhirui** [comment]
The document introduction is visible by default, but now I can only see it with admin permissions

https://grafana.com/docs/grafana/latest/administration/plugin-management/#managing-app-plugins-access

**Comment by huozhirui** [comment]
> 你好@huozhirui,
> 
> 感谢您打开此问题。
> 
> 您能否引用文档的链接，其中说明具有“编辑器权限”的用户可以访问该插件？

The document introduction is visible by default, but now I can only see it with admin permissions

**Comment by usmangt** [comment]
Hi @huozhirui 

So, the document do state that it is only can get access by admin. Then I close this issue
