### ISSUE TITLE
[Feature request] use curly braces for reference variable

### ISSUE THREAD

**Issue by lucadistefano** [grafana/grafana#7928]
grafana 4.2.2, influxdb,centos 6,

expand variables referencing it with the name inside curly braces ${varname} in addition to actual referencing way $varname.
This is useful if you need to compose strings using variables and avoids restrictions in variable expansion.
Example:
with variable/template varname="CPU"
actual behaviour:
field($varname_1w)-field($varname) the expansion will be:  field(**$varname_1w**)-field(CPU)
future behaviour using curly braces:
field(${varname}_1w)-field($varname) expansion will be :  field(**CPU_1w**)-field(CPU)

thanks Luca

**Comment by torkelo** [comment]
we have  ``[[varname]]`` syntax for that

**Comment by lucadistefano** [comment]
sorry I missed this way for referencing variables. It works perfectly!
thanks
Luca
