### ISSUE TITLE
Alerting: label __name__ is empty in __value_string__ of template when graphite query contains 'or'

### ISSUE THREAD

**Issue by perederyaev** [grafana/grafana#79301]
### What happened?

Hello!
When using graphite query in alert rule like
removeEmptySeries(aliasByNode(mtp.activeNode.*.connect_to_service.**{clickhouse,clickhouse_devices**}.group_connect, 2))
we get empty labels dict in alert template: 
"__value_string__": "[ var='B0' metric='A' **labels={}** value=4 ]

If I use just removeEmptySeries(aliasByNode(mtp.activeNode.*.connect_to_service.**clickhouse**.group_connect, 2))
then we get it working well:
"__value_string__": "[ var='B0' metric='A' **labels={__name__=mtpro0}** value=4 ]

### What did you expect to happen?

Expecting to have __name __ label for each metric in alert template

### Did this work before?

not sure

### How do we reproduce it?

Create alert rule with graphite query containing 'or'

### Environment (with versions)?

Grafana: 10.0.9
OS:
Browser:

### Grafana platform?

Kubernetes

### Datasource(s)?

graphite

**Comment by usmangt** [comment]
Hi @perederyaev,

Thanks for opening this issue.

Could you please change the default log level to debug mode and send it to us? 

To do this go to the server where grafana is installed and edit the configuration file (`/etc/grafana/grafana.ini`)

There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again.
