### ISSUE TITLE
[Feature request] Table exclude null values

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#7930]
Hello,

Version: 4.1.0
Datasource: Graphite

currently it isn't possible to exclude null values from the table panel.
We have one Icinga2 service which only returns values once a day and we would like to visualize its values in a table and a graph. Using a graph it is possible to connect null values. The table shows hundreds of lines with no value.

Expected: checkbox to exclude null values, table should show only rows with values

Thanks,
Bernhard Friedreich

**Comment by desknotes** [comment]
Yes...very interested in this feature me too. You can read my need in [this post](https://github.com/grafana/grafana/issues/8325#issuecomment-543567999).

Looking Forward...

**Comment by daniellee** [comment]
If you are using Graphite then there is a function for this: 

https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeEmptySeries

Closing this issue - if we should re-open it (and make it more general than just for Graphite) then let us know.

**Comment by daniellee** [comment]
ref #25416
