### ISSUE TITLE
InfluxDB: Show a notification when fill(null) and reduce expression with strict mode

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#79315]
When `Reduce strict mode` is used, `fill(null)` (Influxql function) will result in `NaN`. 
See docs https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#sum

This is a confusion for the users who don't know the details in deep. We can display a notification when `Reduce with strict mode` is used and point to the documentation.

**Comment by kaushiktalukdar** [comment]
Is this available to pick up or it is already fixed?

**Comment by itsmylife** [comment]
@kaushiktalukdar It is available. Feel free to send PR. Thank you!

**Comment by shubhankarunhale** [comment]
Hi @itsmylife , 
I created  a PR for this issue. Can you please review [#97224](https://github.com/grafana/grafana/pull/97224)?
