### ISSUE TITLE
[Bug]  error by expanding variable in template if value starts with a dot

### ISSUE THREAD

**Issue by lucadistefano** [grafana/grafana#7931]
set a costant in templating
$measure=.NET_CLR_Memory
![image](https://cloud.githubusercontent.com/assets/1080723/24289250/bff43bb4-1080-11e7-95d5-9179acfb3cf7.png)

then set in templating a query
SHOW FIELD KEYS FROM "$measure"
![image](https://cloud.githubusercontent.com/assets/1080723/24289283/e33da830-1080-11e7-92cc-b7df03cd1a01.png)
you get an error because the value of $measure starts with a dot

but if you don't use the constant in query then works:
SHOW FIELD KEYS FROM ".NET_CLR_Memory"
![image](https://cloud.githubusercontent.com/assets/1080723/24289322/0a2b49fc-1081-11e7-98d0-8505dfe10c92.png)

I expected that the value of the variable will be expanded as is, or there is another way to do it?

grafana 4.1.2, influxdb, centos 6

**Comment by torkelo** [comment]
by default values in template variable queries are regex escaped so multiple values are supported. 

SO try`SHOW FIELD KEYS FROM /$measure/`
