### ISSUE TITLE
[Bug] Problem with template variable / search with Grafana 4.1.1/4.2.0 - ElasticSearch

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#7932]
Please include this information:
- What Grafana version are you using? Grafana 4.0.1/4.1.1/4.2.0 
- What datasource are you using? ElasticSearch 2.x/5.x
- What OS are you running grafana on? Docker (grafana/grafana)
- What did you do?  See below
- What was the expected result?  See below
- What happened instead?  See below

Good morning,

With Grafana 4.0.1 I use a lot of templates variables with regex. Also it works well with ElasticSearch 2.x. 
But I tried Grafana 4.1.1 and Grafana 4.2.0 with ElasticSearch 2.x (and 5.x) and it's complicated. Why ? Because I think with Grafana 4.1.1 there is a "limitation" of the amount of lines when Grafana search something on ElasticSearch. Before today I was thinking it is a "limitation" of the template variable but not now because of the "new" option size.

So let me explain this with examples : 

I use the same database but it's the same with separate database/datas.

Here I use Grafana 4.0.1 : 

I have a lot of items (Grafana display in fact 1000 items, but there is a lot more)  : 

![1](https://cloud.githubusercontent.com/assets/23166349/24289089/0da0fd30-1080-11e7-8b3d-092e2649f626.png)

If I want to search something outside these 1000 items I can (the word "network" is outside of these items so that's why I think Grafana asked the database) : 

![2](https://cloud.githubusercontent.com/assets/23166349/24289147/49daeac2-1080-11e7-9cdb-580197305f47.png)

Now, I use Grafana 4.1.1 (or Grafana 4.2.0) : 

I have also a lot of items (Grafana display also 1000 items but I don't think if there is a lot more. Also if you use size :  0 . I noticed that Grafana display 500 items) :   

![3](https://cloud.githubusercontent.com/assets/23166349/24289184/73d98310-1080-11e7-8493-d9abc74aae52.png)

If I want to search something outside these 1000 items I can't : 

![4](https://cloud.githubusercontent.com/assets/23166349/24289253/c28c9538-1080-11e7-9b3a-62acc9c1deb2.png)

And it's the same with regex. So that's why I think we can only search on these 1000 items.

I hope I was comprehensible, and sorry for my English.

Thank you for your help and have a good day.

**Comment by torkelo** [comment]
I think you want Grafana to live query Elasticsearch for values as you type? and send the text as a filter to Elasticsearch? 

Right now template variable options (values) are fetched (and ES has a size limit that you can change). And the auto complete search you get when you use the dropdown only filters down the values returned by the initial template variable query. 

So i think you wish there was something like this issue describes: 
https://github.com/grafana/grafana/issues/7644

**Comment by ChamMach** [comment]
Good morning @torkelo, 

It's not really what I said I think. In fact the examples shown above just indicate a problem I encounter with template variable / search on Grafana 4.1.1 and Grafana 4.2.0. With Grafana 4.0.1 and ElasticSearch 2.x it's working very well. 
If I try to use the same ElasticSearch (ElasticSearch 2.x or even with ElasticSearch 5.x) on Grafana 4.1.1 and Grafana 4.2.0 for example it's not "working". I explain that as much as I can on the first post, so tell me if you don't understand or if you have any questions about that.

Thank you again for your help.

**Comment by torkelo** [comment]
Did you set size option that we added in 4.2 to zero (no limit) then all entries should be returned and it should work as before. 

If you limit it to 1000 the only the 1000 items will be returned and the drop down type ahead filtering will only filter based on those 1000 items returned

**Comment by ChamMach** [comment]
Good morning @torkelo,

In fact and as I said on the first post, if I set size to 0 it's return only 500 items. If I set size option to someting < 1000 it's working. But, if I set size option to >1000 it's not working and there is a limitation (of 1000).

**Comment by torkelo** [comment]
strange, wonder why ES is not returning more than 1000 in your case.

**Comment by ChamMach** [comment]
Can you re-open the ticket please ? Maybe someone have the same issue or have a "solution" for this and also for the initial problem (which is the "function search" of Grafana doesn't really work). 
I think ES return more than 1000 items because I used the same ES with an other version of Grafana (4.0.1) and its work perfectly. I have this problem only with Grafana > 4.0.1.

**Comment by torkelo** [comment]
>  which is the "function search" of Grafana doesn't really work 

It doesn't? Can you describe more. I am not aware of any report of issues with search, or template variable filtering. 

> I think ES return more than 1000 items because I used the same ES with an other version of Grafana (4.0.1) and its work perfectly. I have this problem only with Grafana > 4.0.1.

Can you open chrome dev tools and inspect the query sent to ES and the response from ES? Is there a size limit sent by Grafana? With Grafana 4.2 (only fixed in latest release). you can set `size: 0` in the templating query, this will cause Grafana to not send any size limit so ES should return all values unless there is some built in size limit in ES.

**Comment by ChamMach** [comment]
> It doesn't? Can you describe more. I am not aware of any report of issues with search, or template variable filtering.

Good afternoon,

In fact, this report is an issue with search and template variable filtering @torkelo. I can't describe more, just I think I can only make search or create template variable with only the first 1000 items sends by ElasticSearch. With Grafana > 4.0.1 if I create a template variable with the same regex like a similar template variable on Grafana 4.0.1, I'll don't have a result. Except if I "search" (which mean I adapt my query/regex) on these 1000 items.

> Can you open chrome dev tools and inspect the query sent to ES and the response from ES?

Query sent to ES (it's an example and I replace all "compromising" data with xxx. But with Grafana 4.0.1, it works) : 

[query1.txt](https://github.com/grafana/grafana/files/879073/query1.txt)

Response from ES : 
[resp1.txt](https://github.com/grafana/grafana/files/879091/resp1.txt)


Query sent to ES (with Grafana 4.0.1, it works) : 
[resp1.txt](https://github.com/grafana/grafana/files/879074/resp1.txt)

Query sent to ES (with Grafana 4.2.0 and if I have more than 1000 items in ES) : 
[query2.txt](https://github.com/grafana/grafana/files/879089/query2.txt)

Response from ES : 
[resp2.txt](https://github.com/grafana/grafana/files/879093/resp2.txt)


> Is there a size limit sent by Grafana? With Grafana 4.2 (only fixed in latest release). you can set size: 0 in the templating query, this will cause Grafana to not send any size limit so ES should return all values unless there is some built in size limit in ES.

I think there is no limit sent by Grafana but there is a "problem" with the search function. If there is some built in size limit in ES I don't know why it's work perfectly with Grafana 4.0.1 and not with Grafana 4.1.1 or Grafana 4.2.0. Even if I have more than 1000, 10000 or 100000000 items in ES (not the same ES are used with different Grafana of course, one grafana, one ES).

Thank you again for your help.

**Comment by torkelo** [comment]
Your showing the metric queries, not the template variable queries. 

For some reason your ES is not returning more than 1000 items in Grafana 4.2 for you template variable query. But when I test this query is identical in Grafana 4.2 (if you specify size: 0) to what it was prior to the size limit of 500 that Grafana added (which I think always was there not sure)

**Comment by ChamMach** [comment]
Thank you for your response;

How can I get the template variable queries exactly  ?

And yes as I said, if you specify size: 0 Grafana return only 500 items but if you specify size: something < 1000 it's work well.

**Comment by torkelo** [comment]
If you have chrome dev tools open while you hit Update button in the template variable edit view you should see a new call to ES

**Comment by torkelo** [comment]
I do see the same limit as you do, but not sure why ES is limiting the results. 

if you set a size property that is sent in the query to ES (size: 0 does not do anything, I was wrong on this, size: 0 will cause grafana to send default limit of 500, terms aggregations require a size limit otherwise ES will return error, zero is not a valid limit). 

so if I specify 100000 in the size limit Grafana will query:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"logstash-*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1490195072207","lte":"1490796272208","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"ip","size":100000,"order":{"_term":"asc"}}}}}
```

But something is ES is limiting it to just 1000. must be some hard limit option in ES settings?

**Comment by ChamMach** [comment]
Query sent to ES (it's an example and I replace all "compromising" data with xxx. But with Grafana 4.0.1, it works) :

[query3.txt](https://github.com/grafana/grafana/files/879394/query3.txt)

Response from ES :

[resp3.txt](https://github.com/grafana/grafana/files/879395/resp3.txt)

Query sent to ES (with Grafana 4.2.0 and if I have more than 1000 items in ES) :

[query4.txt](https://github.com/grafana/grafana/files/879398/query4.txt)


Response from ES :

[resp4.txt](https://github.com/grafana/grafana/files/879399/resp4.txt)

Yeah I don't know why, if you specificy something > 1000 ES "send" only 1000 items. And why it's working on Grafana 4.0.1 and not for Grafana 4.1.1 and Grafana 4.2. It's delirious.

**Comment by ChamMach** [comment]
Any news @torkelo ? This is a bug ?

**Comment by torkelo** [comment]
Not sure, no idea why ES is limiting response to < 1000 terms even when you ask for more. Maybe an ES bug?

**Comment by ChamMach** [comment]
Good morning @torkelo,

I'm not sure. Why it's work perfectly with Grafana < 4.1.1 and not for Grafana 4.1.1 and Grafana 4.2.0 ?
It's the same with ES 2.x or even 5.x. I my personnal opinion it's a "bug" of Grafana or maybe a "bug" of ES which is doesn't totally understand the "query" of Grafana 4.1.1 or Grafana 4.2.0.

I don't know but it's very penalizing for my project.

**Comment by torkelo** [comment]
I cannot see any difference in the query sent to ES by Grafana.

In the queries you showed above, you state you specified a high value for size in the template variable query but the raw query you showed still show 

`{"search_type":"count","ignore_unavailable":true,"index":"esxtop"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1480621795172","lte":"1486009318234","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"@metric","size":500,"order":{"_term":"asc"}}}}}
` 

size:500  (query4.txt) 

This not what I get when I test with template variable with a size: 10000 in the template variable query, then I see that reflected in the size sent to ES

**Comment by ChamMach** [comment]
Hi @torkelo,

Sorry to answer so later, I'm a little busy here.

So, yes, I think it was a mistake. But, now I have the same as you : 
```
{"search_type":"count","ignore_unavailable":true,"index":"esxtop"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1459976804379","lte":"1491512804380","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"@metric","size":"100000","order":{"_term":"asc"}}}}}
```
In fact I tested on a different server and sometimes I can see the values I want on my templates query (it's still limited to 1000 items but I can search "like" before once in ten). But when it's working and when I create my query, nothing appears except "values" of template variables : 

![pic1](https://cloud.githubusercontent.com/assets/23166349/24776525/722a5322-1b21-11e7-9810-61f67a5bd1fd.png)

So, I'm not sure but maybe it's a bug or a limitation of ES in addition of a "bug" or something like that in Grafana ? Strange.

**Comment by aurimasplu** [comment]
Hi,
I have similar problem.
I am running Grafana 4.6.3-1 and Elasticsearch 6.1.1
My template query looks like this:
![image](https://user-images.githubusercontent.com/33485896/36593300-bdb0265e-18a1-11e8-9e04-c90944b0accd.png)
Also I have same problem when I try lo list all my devices in table, I get max 500 results and currently I should get something about ~1000.
 
From your conversation above I do not understand if you get to some kind of solution.

**Comment by aurimasplu** [comment]
never mind, I found solution in documentation :)
