### ISSUE TITLE
CloudWatch: Errors while loading queries/datasource on Safari

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#79347]
When using the CloudWatch plugin with Safari, CloudWatch errors and isn't able to successfully query. I tried both CloudWatch with Chrome and tried other datasource plugins with Safari and only had this issue with CloudWatch and Safari. Interestingly, the original reporter got the error `Type error: undefined is not an object (evaluating 'Qs')` while I got the error:
![Screenshot 2023-12-11 at 11 35 46 AM](https://github.com/grafana/grafana/assets/5421859/179f4c0a-41b2-4af7-ba90-651d1afc2460) 
and when I try to open an existing dashboard the console logs a warning: `[Log] failed to load data source – {message: "Datasource: <DatasourceID> was not found"}`

Originally reported in https://github.com/grafana/support-escalations/issues/8693

**Comment by dspitzer** [comment]
I'd like to add a "me too". It stopped working sometime last week.
