### ISSUE TITLE
Panels: Notification gets hidden on smaller panels with longer titles

### ISSUE THREAD

**Issue by anurag-patnaik** [grafana/grafana#79349]
### What happened?

We noticed that notifications gets hidden with a triangular error icon on smaller panels with longer title. Customer sees a notification triangle on top of panel title when panels are made very small.
<img width="519" alt="notification_bug" src="https://github.com/grafana/grafana/assets/949305/0d7a62fa-a247-4d5b-809d-f1787a1ba399">

### What did you expect to happen?

Notifications should be handled gracefully with small panels and long titles, instead of showing a traingular error icon.

### Did this work before?

Unsure if this worked before.

### How do we reproduce it?

1. Create a new Grafana panel with a long title
2. Note the traingular error icon overlapping with the text.

### Environment (with versions)?

Grafana: 9.4
OS: macOS
Browser: Chrome

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @anurag-patnaik,

Thanks for opening this issue.

Grafana's current latest stable version is 10.2.x and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here
