### ISSUE TITLE
[Bug] Session of datasource provided to webbrowser (proxy mode)

### ISSUE THREAD

**Issue by roan92** [grafana/grafana#7935]
I'm facing still the issue described in #3845.
When using Grafana with the OpenNMS datasource (proxy mode), my webbrowser is receiving the session of the datasource user, so I'm also logged in with the datasource user in OpenNMS.

Cookie passed to browser: JSESSIONID
Grafana version: 4.1.2-4.2
Datasource: OpenNMS
Grafana and OpenNMS running on same host behind nginx reverse proxy

**Comment by torkelo** [comment]
The Grafana datasource proxy mode acts like a reverse proxy. 

Cookies from the user are hidden to the data source, but there are currently no way to filter out headers returned from your data source.

**Comment by roan92** [comment]
But is this not the same issue (again) as #3845?
