### ISSUE TITLE
[bug] zoom out changes override time range

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#7937]
We have an "overview" dashboard that has a number of panels where we restrict the time to only the last 1 hour. This prevents users from selecting a different time range. I noticed that if you "zoom out" this has an effect on these panels. It seems this should not happen. 

I am using 4.2 but I believe this is an issue in earlier versions as well.

**Comment by torkelo** [comment]
Panel relative time override is only active when the dashboard time is relative. So when you zoom into any panel the dashboard time becomes absolute, all panel time overrides are disabled, set back dashboard time to relative (like now-2 hours to now)
