### ISSUE TITLE
Adding (new) dashboard using curl without bearer token

### ISSUE THREAD

**Issue by prasenforu** [grafana/grafana#7938]
Ver: 4.2.0

I am able to add datasource using curl command (below)

```
echo 'Import Prometheus datasource on Grafana' &&
curl --silent --fail --show-error \
--request POST http://admin:password@HOST:3000/api/datasources \
--header "Content-Type: application/json" \
--data-binary @prometheus-datasource.json ;

```

But not able to add dashboard ..

```
echo 'Import Prometheus dashboard on Grafana' &&
curl --silent --fail --show-error \
--request POST http://admin:password@HOST:3000/api/dashboards/db  \
--header "Content-Type: application/json" \
--data-binary @prometheus-dashboard.json ;

```

Can you please help. 

Note : without bearer token

**Comment by torkelo** [comment]
In the POST to create/update a dashboard you need to specify the dashboard model in a dashboard property, there is also an overwrite property to tell grafana what to do if there already is a dashboard if the same name (or same id)

**Comment by torkelo** [comment]
http://docs.grafana.org/http_api/dashboard/

**Comment by yanhongwang** [comment]
Hello @torkelo 

Thanks for your hint with 'http://docs.grafana.org/http_api/dashboard/'
My grafana version: 5.0.4

I can successfully create an **empty** dashboard by 'curl' command. 
----------------------------------------------------------------------------------------
generate_post_data() {
cat <<EOF
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Development",
    "tags": [ "" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
  },
  "folderId": 0,
  "overwrite": true
}
EOF
}
curl --silent --user admin:password --request POST --header 'Content-Type: application/json;charset=UTF-8' --data-binary "$(generate_post_data)" http://SERVER_IP/api/dashboards/db | jq
---------------------------------------------------------------------------------------------------------------
And the successful response is
{
  "id": 11,
  "slug": "development",
  "status": "success",
  "uid": "sGWzypFik",
  "url": "/d/sGWzypFik/development",
  "version": 1
}
-------------------------------------------------------------------

But, if I have a predefined grafana json file, how can I insert to grafana by curl?
Thanks.

Hong
