### ISSUE TITLE
Dashboards: Variable selection no longer preserved when moving back from "View panel" to dashboard

### ISSUE THREAD

**Issue by nemobis** [grafana/grafana#79396]
### What happened?

In Grafana 10.0.2, with the new dashboard navigation breadcrumbs, clicking on the dashboard title when in "View panel" doesn't preserve the variable selection.

I'm not able to discern a pattern in what variables get selected when returning to the dashboard. Sometimes they're the dashboard's defaults, sometimes not. Perhaps they're whichever values the variables happened to had when the dashboard was first loaded in the current window (which may not be the defaults if the dashboard has been opened with specific URL parameters).

### What did you expect to happen?

The variables I have currently selected in the panel should be preserved.

At very least, if the variables need to be thrown away, I should be given a warning about losing state, so that I could instead choose to navigate back with the "back" feature in my browser.

### Did this work before?

Yes, all URL parameters used to be preserved.

### How do we reproduce it?

1) Open a dashboard with default values.
2) Change one variable from the dropdown and wait for the panels to reload.
3) Open one panel.
4) Click on the dashboard title in the breadcrumbs at the top of the page to go back.

### Is the bug inside a dashboard panel?

No, it doesn't seem specific to any specific panel type.

### Environment (with versions)?

Grafana: 10.0.2
OS: Fedora Linux
Browser: Firefox 120.0.1

### Grafana platform?

Kubernetes

**Comment by nemobis** [comment]
> At very least, if the variables need to be thrown away, I should be given a warning about losing state, so that I could instead choose to navigate back with the "back" feature in my browser.

This might be related to https://github.com/grafana/grafana/issues/74695 / https://github.com/grafana/grafana/issues/69349, which is kind of the opposite issue.

**Comment by nemobis** [comment]
Workaround: I can exit the panel without data loss by pressing <kbd>ESC</kbd>. I didn't find any equivalent in the UI.

**Comment by usmangt** [comment]
Hi @nemobis,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by torkelo** [comment]
unable to replicate this

**Comment by nemobis** [comment]
I can't reproduce the bug in v10.2.3 either. Looks like it was fixed at some point after v10.0.2.
