### ISSUE TITLE
Ability to show elasticsearch array types

### ISSUE THREAD

**Issue by Exocomp** [grafana/grafana#7939]
I don't see a way to do this, if this ability exists please let me know how to accomplish this:

Elasticsearch Query:  _type:"api" AND tags:"stats"
Metric: Raw Document

The raw document has a field which is an array such as:

      "versions" : [
        {
          "version" : "1.8.0_121",
          "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
          "vm_version" : "25.121-b13",
          "vm_vendor" : "Oracle Corporation",
          "count" : 1
        }
      ],

I'm using the JSON Data table transformation but I don't see a way to display elements of the array in versions.  I can access versions but it just shows up as "[object Object]".

**Comment by torkelo** [comment]
you can't show an array of objects, but you can show an array of values in a single column. 

Not sure how to this would work, what if there are multiple objects? concatenate each value in each object?

**Comment by torkelo** [comment]
We do want to improve table panel so you can drill down into the raw json better, but as a primary column field an array of objects is going to be tricky.

**Comment by rlabrecque** [comment]
I think I'd even be happier with the raw json rather than just [object] in this case.

**Comment by davewat** [comment]
> I think I'd even be happier with the raw json rather than just [object] in this case.

@rlabrecque There is a PR that allows you to do this (we use it to lookup the raw object for Elasticsearch) see #13890 and #13907

**Comment by rlabrecque** [comment]
Exciting, thanks for the link!

I felt shitty about commenting on an old closed issue, nice to see that progress is being made though!
