### ISSUE TITLE
[Bug] Cloudwatch custom namespaces() query with regex only show 1 match

### ISSUE THREAD

**Issue by AnthonyWC** [grafana/grafana#7942]
- What Grafana version are you using?
Grafana v4.1.1

- What datasource are you using?
cloudwatch

- What OS are you running grafana on?
Ubuntu 16.04.1 LTS

- What did you do?
![image](https://cloud.githubusercontent.com/assets/6215805/24326583/b1a27e24-1187-11e7-9d83-eea8cb7707eb.png)

- What was the expected result?
I expected to see multiple namespaces that starts with DevBeta1 to show up (under preview)

- What happened instead?
I only see 1 name space matched

- If related to metric query / data viz:
namespace()

**Comment by torkelo** [comment]
Try specify this regex: 

`/DevBeta1.*/`

**Comment by AnthonyWC** [comment]
No difference; does it matter if my values are separated by underscores? (e.g. DevBeta1_type1)

**Comment by torkelo** [comment]
Can you show what your values look like without the regex ?

**Comment by AnthonyWC** [comment]
Note: I modified the title to mention that these are custom namespace

custom namespace doesn't show with no regex (due to 20 limits):

![image](https://cloud.githubusercontent.com/assets/6215805/24370728/750a70f0-12f6-11e7-8964-b9f2aca6a228.png)

In the dropbox it only shows one custom namespaces:
![image](https://cloud.githubusercontent.com/assets/6215805/24371199/180c4f2a-12f8-11e7-8fde-f3120325c746.png)


If I manually enter the namespaces/metrics I get data.

**Comment by torkelo** [comment]
If only one show in drop down only one is returned by the backend, so the list of custom metrics can't be working correctly

**Comment by AnthonyWC** [comment]
It does work if I manually enter the namespace, e.g.

![image](https://cloud.githubusercontent.com/assets/6215805/24378924/bf109f1e-1312-11e7-8475-388b09f2a7ec.png)

But the namespaces themselves are not returned by the query (except for one).

**Comment by torkelo** [comment]
yes, but it is not so strange that the regex does not result in more items as there is only one custom metrics entry returned. How do you specify the custom metrics to Grafana?

**Comment by AnthonyWC** [comment]
Should namespaces() not return all the custom metrics by default and why would it only show one custom namespace but not the others?

I specified the other custom metric by manually putting it in the namesapce field.

**Comment by torkelo** [comment]
In the custom namespace field on the data source edit view, did you seperate your custom metrics by a comma? It needs to be a comma seperated list

**Comment by AnthonyWC** [comment]
You are right, I forgot to add the other custom namespace specification in the data source (incidentally can it no longer reference a json file like in previous version?)
