### ISSUE TITLE
pass selected value from bar graph to another dashboard and filter data in the 2nd dashboard based on the data 

### ISSUE THREAD

**Issue by Neelam-zanvar** [grafana/grafana#79437]
**Why is this needed**:

I am building a log monitoring dashboard using loki as a data source. I've made stacked bar graph to display the sum of bytes consumed by every service. HEre are few snaps of the config
![image](https://github.com/grafana/grafana/assets/98389856/fc037c28-aa6f-4732-bb03-6dfac17dcbab)
![image](https://github.com/grafana/grafana/assets/98389856/d0ae3553-3e4e-408c-a638-7d644e1f1c79)
![image](https://github.com/grafana/grafana/assets/98389856/e1a20a74-4c9b-4137-982a-a222821b4703)
![image](https://github.com/grafana/grafana/assets/98389856/5caa100d-1c7a-4187-87d1-0e93cfdea0f9)
This is how th chart looks like
![image](https://github.com/grafana/grafana/assets/98389856/ae300d1e-a7fe-411f-9793-18a27ad1a5ba)

Now when i select a specific service(bar)on the graph i want to navigate to another dashboard or display another table which lists all the byte transactions of the SELECTED SERVICE AT SELECTED TIME in the table. How can i pass these values from one dashboard to another. PLease HElp. I'm new to grafana .

**What would you like to be added**:

[Add a brief description of what the feature or enhancement should do.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Comment by usmangt** [comment]
Hi @Neelam-zanvar,

This is more of a general question than reporting an issue (problem) and the best place to ask questions is our [Community Forums](https://community.grafana.com/) where you find the [Loki Category](https://community.grafana.com/c/grafana-loki/41) to create a post and the community members can help you out.

What actually you are looking for is the Grafana Data links. Here is the link to the [documentation](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/).
