### ISSUE TITLE
[Bug] checkbox_white.png missing one icon

### ISSUE THREAD

**Issue by shaymos02** [grafana/grafana#7943]
Compare to checkbox.png . 
The light theme missing the multi select checked icon.
So, in template with multi select option the icon disappear.

**Comment by torkelo** [comment]
what version are you using?

**Comment by daniellee** [comment]
In latest version, 4.2.0:

![image](https://cloud.githubusercontent.com/assets/434655/24344381/83d50882-12cb-11e7-9f85-70fd97e39126.png)
