### ISSUE TITLE
Document 'eventbus' in PanelProps

### ISSUE THREAD

**Issue by josmperez** [grafana/grafana#79431]
As part of the documentation for provide guidance on use of PanelProps, ensure useful documentation for 'eventbus'. (Chore leftover from https://github.com/grafana/grafana/issues/67026.)

**Comment by josmperez** [comment]
Esteban, please add this doc chore to your to-do list or suggest another developer resource for this. Thank you.

**Comment by academo** [comment]
@josmperez I found this previous guide from Marcus that covered this specific topic https://community.grafana.com/t/how-to-subscribe-to-grafana-application-events/59147

Do you think you can use this as the base for the documentation of the event bus?

Notice that in reality what is mentioned in that post is all you need to know about how to use the event bus, the powerful part that is hard to find full information, document and keep up to date are the available events.

**Comment by academo** [comment]
Stages 0 and 1 are finished. Currently working on deploying stage 2

**Comment by josmperez** [comment]
Yes, I agree that Marcus's post could be a good way to get started. I'll port this to the documentation next week.
