### ISSUE TITLE
Failing to display AWS cloudwatch dimensions while using template

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#7944]
- What Grafana version are you using? 
**4.1.1**
- What datasource are you using?
**cloudwatch**
- What OS are you running grafana on?
**Amazon Linux AMI**
- What did you do?
I've imported dashboard from Grafana org - "AWS Cloudwatch Browser".
For some reason there isn't any data displayed using the out of the box dimension template, but when I enter the dimensions manually the data is displayed properly. 

The screenshot which shows using the template:
![using_template](https://cloud.githubusercontent.com/assets/24862189/24330929/450aa98e-1232-11e7-8153-4a8e7c44ee23.PNG)

The screenshot which shows using the manual value:
![using_manual_value](https://cloud.githubusercontent.com/assets/24862189/24330937/5d120324-1232-11e7-9e9e-630a242243e7.PNG)

What could explain this behavior  ?

@torkelo

**Comment by daniellee** [comment]
An [identical question](https://community.grafana.com/t/failing-to-display-aws-cloudwatch-dimensions-while-using-template/268) is posted on the community site. Closing. Will reopen if it is a bug.
