### ISSUE TITLE
[bug] in graph, last series disappears,  when rescaling panel more then half a screen

### ISSUE THREAD

**Issue by PitPaul** [grafana/grafana#7946]
- What Grafana version are you using?
4.2.0
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu 16.04
- What did you do?
rescale panel 
- What was the expected result?
all series should be included in rescaled graph
- What happened instead?
 last 3 series are gone from graph - after downscaling and refresh,  lost series appear again.
![grafana-bug](https://cloud.githubusercontent.com/assets/26178409/24332492/c7e8b444-1247-11e7-9289-5745bfe78c61.png)

**Comment by torkelo** [comment]
probably related to breaking change in influxdb 1.2 (max-row-limit), 

https://github.com/grafana/grafana/issues/7380

**Comment by torkelo** [comment]
Sorry, forgot to mention that it can easily be fixed by increasing the max-row-limit InfluxDB setting or setting it to zero, which I think disables it which was the default prior to InfluxDB 1.2)
