### ISSUE TITLE
Navigation: Menu indicates `Dashboards` instead of `Starred` when located on this page

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#79473]
When clicking on the `Starred` menu item we get to that page but in the menu the item highlighted is `Dashboards`. 
We can investigate how to highlight the right menu item taking into account the menu docked makes this more noticeable.

<img width="761" alt="Captura de pantalla 2023-12-13 a las 17 10 45" src="https://github.com/grafana/grafana/assets/65417731/858ee741-a795-4a53-b861-18bafeaffdaa">

**Comment by joshhunt** [comment]
We agree this is mildly a problem, but it's pretty low impact and has never came up in any of the feedback we've gotten. Because it'll always be at the bottom of our priority list to work on, we've decided to close it for now.
