### ISSUE TITLE
Explore: Changing the time range freezes the browser

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#79476]
Found by internal conversation: https://raintank-corp.slack.com/archives/C02TXB92G6T/p1701350562527189
(Issue relates to internal environment and is intermittently reproducible since it depends on relative time)

Possible reproduction steps:

Open Explore with Test Data and pass following Raw Frames:

<details><summary>frames</summary>

```
[
  {
    "schema": {
      "refId": "A",
      "meta": {
        "type": "timeseries-multi",
        "typeVersion": [
          0,
          1
        ]
      },
      "fields": [
        {
          "name": "Time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time"
          },
          "config": {
            "interval": 1
          }
        },
        {
          "name": "Value",
          "type": "number",
          "typeInfo": {
            "frame": "float64"
          }
        }
      ]
    },
    "data": {
      "values": [
        [
          1701343547253
        ],
        [
          1
        ]
      ]
    }
  }
]

```

</details>

The error does not happen when `config.interval = 1` is not passed.

Full repro steps: 
1. Run devenv loki and have it running for a while for more data
2. Run an aggregation query and have the time range be 4 seconds long (example [link](http://localhost:3000/explore?schemaVersion=1&panes=%7B%22uuh%22:%7B%22datasource%22:%22gdev-loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%20by%28job%29%20%28count_over_time%28%7Bjob%3D%5C%22tns%2Fapp%5C%22%7D%20%7C%3D%20%60%60%20%7C%20logfmt%20%5B$__auto%5D%29%29%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22gdev-loki%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221702501200000%22,%22to%22:%221702501204000%22%7D%7D%7D&orgId=1))
3. Change the time range to 6 hours ago and watch your browser crash (Note: if you dont have a lot of data, it will complete successfully and the interval in the dataframe json will change to 10000 which is correct.)

The issue is we need to re-calculate the interval after the time range is changed and before the query runs so the visualization picks up the new interval. Currently, the time range is changed and the visualization uses the previous interval, and then the interval is changed after it finishes filling out null values. The null insert threshold is assuming the threshold will throttle the while loop to only be ran a reasonable number of times. 

--- 
Investigation: 

The problem seems to be with a function that will fill in null values between two other values. https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/transformations/transformers/nulls/nullInsertThreshold.ts#L155

With the above frame, it will want to run this while loop 1,074,636,887 times. This makes the browser extremely sad.

**Comment by leeoniya** [comment]
> The error does not happen when `config.interval = 1` is not passed.

this is the $1M question, why is the interval 1 (millisecond). usually you'll get something like 60000 if your maxDataPoints ends up calculating a "safe" interval of 60s on the backend. it would only be 1 if you zoomed down to 1ms resolution between datapoints, which i'm not sure is even possible.

**Comment by gelicia** [comment]
So it's worth noting in the original example, there is a link you visit that works fine, and then you change the time range to the last 6 hours which causes the problem.

In the first link, the time range is 4 seconds long - 11:25:43 to 11:25:47. This, with the max data points set at 2251 means that the time interval will be set to 1ms, the lowest it can go.
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/datetime/rangeutil.ts#L289 

When you attempt to pull back the time range to the last 6 hours, I'm guessing it doesn't recalculate the interval which causes the issue. 

If you just take the loki query and start from scratch at a 6 hours history, the interval is set to 10000.

Does this seem plausible @leeoniya  ?

**Comment by leeoniya** [comment]
i'm not aware of any caching of the interval, but memory might be failing. but yeah, that would def explode if that's what's happening :sweat_smile:
