### ISSUE TITLE
Stat: Percent Change color options

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#79486]
Allow user to control how percent change color logic is applied.

See [this comment](https://github.com/grafana/grafana/pull/78250#pullrequestreview-1777313597) for more information.

**Comment by drew08t** [comment]
I think for an initial version of this we can simply add three color options that can later be extended without the need for any migration:

['Standard', 'Inverted', 'Same as Value'], where 'Standard' is red = negative, green = positive and 'Inverted' is red = positive, green = negative. 'Same as Value' would match the color with the value color.

In the future we can extend more options to include things like "Adjacent threshold", "End of mapping spectrum", and even custom.

**Comment by drew08t** [comment]
See this reference to color explorations from @torkelo: https://github.com/grafana/grafana/blob/b011a5d53bffc78ee80935529ea26adad15ae1bf/packages/grafana-ui/src/components/BigValue/BigValueLayout.tsx#L143-L151

**Comment by Hipska** [comment]
Came here to request an inverted option, that would already be helpful.

Use case: memory, disk and cpu usage should be red when increasing and green when decreasing.

**Comment by robhamnett** [comment]
Agree that this would be helpful! +1 

Use case: difference % of alerts going down over time.. Should be green!

I know it's possible to use the calculation feature to do this, but we don't get the fancy up/down arrow without some funky value maps etc etc

**Comment by nunodsfernandes** [comment]
+1 on this.
I'm monitoring node loads, and it's clear that red decreasing is not "good".
I'm not going into that rabbit hole, but.. thresholds for the color change percentage would really help in identifying percentage dips/climbs in very crammed dashboards. :)

**Comment by sbourell** [comment]
+1000 
Just another example. I have an API Response Time panel and it appears green when it's longer than previous metric, which is, for an API response time, not the way we want it of course :D 
![image](https://github.com/grafana/grafana/assets/125288190/326f6f62-7c75-4c5d-a559-ae19d659fd00)

As @drew08t said, a simple ['Standard', 'Inverted', 'Same as Value'] option will be exellent for a start.

**Comment by mikemiller35** [comment]
Just ran into this myself, and would like to configure the color.

![Screenshot 2024-03-21 at 15 13 54](https://github.com/grafana/grafana/assets/39773669/3e5079a3-43ca-4b66-8439-080ae8bdb967)

**Comment by nikelprophet** [comment]
i have the same problem, pls fix it .
when it raises i need it red
