### ISSUE TITLE
BarChart: Support rendering some series as lines

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#7949]
Please include this information:
- What Grafana version are you using ? 4.x
- What datasource are you using ? ElasticSearch.
- What OS are you running grafana on ? Docker (grafana/grafana)
- What did you do ? Trying to stack result of request with X-Axis mode Series.
- What was the expected result? Something like that : 

![5](https://cloud.githubusercontent.com/assets/23166349/24347256/f9c15f58-12d7-11e7-9f6f-f45b48e03a47.png)

- What happened instead ? Something like that : 

![6](https://cloud.githubusercontent.com/assets/23166349/24347289/1777a638-12d8-11e7-9166-a75b713b44d6.png)

As you can see, points are not "stacking" on bars. For each new query (like query with points), Grafana create graph at the right (even if I use Group by : Date Histogram : "@timestamp" or something like that). 
So, I want the possibility to "stacking" result of query for graphs with x-axis mode series like x-axis mode date : 

![7](https://cloud.githubusercontent.com/assets/23166349/24347556/fd8bfb4c-12d8-11e7-94d2-c40f2ca8c0a8.png)

OR the possibility to change the "dimension" of bars.

Thank you and have a good day.

**Comment by luiscruz** [comment]
Any update on this?

**Comment by rentes** [comment]
Hi everyone, I'm not sure what to do to speed up this feature release, except saying that it would be of tremendous help to have it. I too want to stack X-axis by series, not by time. What can I do to have this on my grafana charts? Thank you.

**Comment by jeliasson** [comment]
One would expect that stacking of metrics would be a native feature by now. When thinking of it, it does not seem like a big challenge. However, would really love to see this feature in the future. Thanks and keep it up!

**Comment by Deltablox** [comment]
@jeliasson i agree... 2.5 years after opening that feature request and nothing happened until now.
Feelsbadman.
I would also really love to see this feature soon. It would be a nice improvement

**Comment by ChamMach** [comment]
Hi everyone ! 

Glad to see that I'm not the only interested for this feature. Even 2 years later.

@torkelo the team have any plan to add this feature in the future ?

Thank's.

**Comment by MattGill98** [comment]
+1

**Comment by trierra** [comment]
+1

**Comment by kvannorel** [comment]
+1

**Comment by mohdhallal** [comment]
+1

**Comment by Psyf** [comment]
+1

**Comment by ThomasMadland** [comment]
+1

**Comment by jceddy** [comment]
+1

**Comment by AgrPriyank** [comment]
+1

**Comment by cherya** [comment]
+1

**Comment by bitabitabita** [comment]
+10

**Comment by vivekdsr** [comment]
+10

**Comment by vivekdsr** [comment]
+1

**Comment by falaleevms** [comment]
Any chances this one to be done?

**Comment by tguerena** [comment]
+1

**Comment by c-thiel** [comment]
+1

**Comment by marian-aretu** [comment]
+1

**Comment by hblauth** [comment]
+1

**Comment by Tranceh2** [comment]
+1

**Comment by Arnovw** [comment]
+1

**Comment by ChamMach** [comment]
Hi @torkelo, any news ?

**Comment by vikasmn** [comment]
+1

**Comment by vkas-mn** [comment]
+1

**Comment by ArthurTimmermans** [comment]
+1

**Comment by lucaslefaucheur** [comment]
+1

**Comment by truj** [comment]
+1

**Comment by suchwerk** [comment]
+1

**Comment by kieran-cummins-lu** [comment]
+1

**Comment by rentes** [comment]
+1

**Comment by rentes** [comment]
In the meantime, I found out this plugin and going to try it to see if it solves my problem.

[Grouped Bar Chart Panel Plugin for Grafana](https://github.com/gipong/grafana-groupedbarchart-panel)

**Comment by truj** [comment]
@rentes We were using the plugin you mention with Grafana 6.
But unfortunately it doesn't work with Grafana 7.

**Comment by rishabh-khurana** [comment]
+1

**Comment by jay0129** [comment]
+1
@rentes Did you solve your problem?

**Comment by MichaelTendoSsemwanga** [comment]
+1

**Comment by sagiwei** [comment]
+1

**Comment by zalito12** [comment]
+1

**Comment by alexsanderp** [comment]
+1

**Comment by zalito12** [comment]
Hi! I achived this with the new bar chart beta version.
Using prometheus with 2 groups and with some transformations:
Label to fields (1st field) -> Group by (2nd field)

**Comment by jwjhdev** [comment]
+1

**Comment by morenod** [comment]
+1

**Comment by ptoutant** [comment]
+1, need stacked bar with dynamic series asap

**Comment by jayarjo** [comment]
+1

Absolutely required.

![image](https://user-images.githubusercontent.com/150075/181913960-a3df419a-57a5-4262-a2bd-e22d2d15cd70.png)

**Comment by ptoutant** [comment]
I found a solution that works for my situation.  I saw in one of the Grafana tutorials where a pivot table query was being used for a side-by-side bar chart.  I tried it as a stacked bar, on my data, and it works great!  Now I can now generate stacked bars with dynamic series using a pivot table and some dynamic sql.  Here's the query I'm using:

DECLARE 
  @columns NVARCHAR(MAX) = '', 
  @sql NVARCHAR(MAX) = '';

-- Select the source IPs to pivot to columns
SELECT 
  @columns+=QUOTENAME(sourceip) + ','
FROM (
	SELECT DISTINCT SourceIP
	FROM PacketsView
	) sips
ORDER BY 
 sourceip;

-- Remove the last comma
SET @columns = LEFT(@columns, LEN(@columns) - 1);

-- Construct dynamic SQL
SET @sql ='
SELECT * FROM 
(
  SELECT 
    sourceip, 
    destinationip
  FROM 
    packetsview p
) t 
PIVOT(
  COUNT(sourceip) 
  FOR sourceip IN ('+ @columns +')
) AS pivot_table;';

-- Execute the dynamic SQL
EXECUTE sp_executesql @sql;

Hope this helps some of you!

**Comment by Wepstern** [comment]
+1

**Comment by Huangvivi** [comment]
+1

**Comment by leeoniya** [comment]
we're gonna try to pick this up soon: https://github.com/grafana/grafana/pull/43512

**Comment by rentes** [comment]
> +1 @rentes Did you solve your problem?

@jay0129 Didn't try again, sorry. I'm going to update grafana to the latest version and work on some dashboards but I'm not sure I'm going to try this again. If I do try it, I'll let you know. Sorry for my late reply and thank you.
