### ISSUE TITLE
PostgreSQL plugin: `driver: bad connection` when connecting to EdgeDB

### ISSUE THREAD

**Issue by aljazerzen** [grafana/grafana#79505]
### What happened?

Grafana is reporting `driver: bad connection` when connecting to EdgeDB, which is (supposed to) be comapatible with PostgreSQL wire protocol and SQL interface.

See the initial issue here: https://github.com/edgedb/edgedb/issues/6437

![image](https://github.com/grafana/grafana/assets/11072061/8426fb02-b6ef-4bfc-9f8d-41f2c98d53ed)

### What did you expect to happen?

Successful connection or a more elaborate message explaining what went wrong.

### Did this work before?

No.

### How do we reproduce it?

1. Start an edgedb server.
   I have an example database here: https://github.com/aljazerzen/edgedb-sql-go-example/tree/main/edgedb
   There are more instructions on how to do that here: https://www.edgedb.com/docs/intro/quickstart
2. Start grafana and add PostgreSQL plugin. 
3. Use params as described here: https://www.edgedb.com/docs/reference/sql_support
4. Make sure to use `SSL mode: require`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: version=10.2.2 commit=161e3cac5075540918e3a39004f2364ad104d5bb branch=HEAD compiled=2023-11-20T13:18:33Z
OS: Linux
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

PostgreSQL

**Comment by gabor** [comment]
hi @aljazerzen , i checked, and the [db.Ping()](https://pkg.go.dev/database/sql#DB.Ping)  method fails with edgedb when using the https://github.com/lib/pq module.

here is a go program that reproduces the problem:
```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	str := "user=edgedb dbname=edgedb password=edgedb host=localhost port=5656 sslmode=require"
	db, err := sql.Open("postgres", str)
	if err != nil {
		log.Fatal(err)
	}

	defer db.Close()

	err = db.Ping()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("ping was ok")
}
```

this is why the healthcheck fails.

**Comment by aljazerzen** [comment]
Thank you, this really is a bug either in lib/pq or edgedb itself.
