### ISSUE TITLE
Lines not appearing between metrics

### ISSUE THREAD

**Issue by InH4te** [grafana/grafana#7950]
Firslty, I'm new to InfluxDB and have come from Graphite so please bear with me.

I am using Grafana v4.1.1 and using InfluxDB. I'm trying to pull multiple stats of different APIs onto Grafana. I've got the following DB structure.

| api  | bno | landscape     | MTT   | 
|------|-----|---------------|-------|
| api1 | 600 | testlandscape | 400.2 |  
| api1 | 600 | testlandscape | 402.5 |  
| api1 | 601 | testlandscape | 500.5 |  
| api1 | 602 | testlandscape | 400.2 |  
| api1 | 602 | testlandscape | 405.5 |  
| api1 | 603 | testlandscape | 600.5 |  
| api1 | 603 | testlandscape | 605.2 |  
| api1 | 604 | testlandscape | 100.5 |  

**My intention:** I want Grafana to show me all the MTTs of api1 as different (but connected) points on the graph and I want the x-axis (or legend) to show just the bno. I am using the following query.

select bno,MTT from Metrics where "api"='api1' AND "landscapename"='testlandscape' GROUP BY jenkins_bno fill(0)

However, this plots the graph correcltly but with two issues.
1. No lines appear to join the dots: I have already read [this](https://community.grafana.com/t/why-is-my-graph-empty-when-i-zoom-in/24) arcitle and tried to get rid of the null values by selecting "connected" in the "Display" tab as well as I've set fill to 0, but with no lines appearing. And ofcourse, in the "Display" tab, both "points" + "lines" are selected. Still no lines!
2. I'm unable to alias the second column: I read through aliasing but when I use $col, I get MTT as the x-axis. Is there something like $col_2 or someway to number the columns that are returned so I can show only them?

Attaching screenshot of the network log to show the data that's being retrieved.

![image](https://cloud.githubusercontent.com/assets/10860168/24351146/40eb20ba-1302-11e7-9772-da89fa1ad766.png)

Also, a picture of the graph that's currently forming

![image](https://cloud.githubusercontent.com/assets/10860168/24351166/52e5a560-1302-11e7-862b-b990b8fa2a30.png)

Is there something I'm doing wrong? Please advise.

Regards

**Comment by torkelo** [comment]
If you have X-axis mode to series, each x-axis tick will be a different "series" so there is not going to be a connecting line between them as they represent different series. Lines will only connect points on the same series.
