### ISSUE TITLE
Timeshift doesn't compensate for daylight savings

### ISSUE THREAD

**Issue by GriffReborn** [grafana/grafana#7951]
_- What Grafana version are you using?_ 
4.0

_- What datasource are you using?_ 
Graphite

_- What OS are you running grafana on?_ 
Centos 7

_- What did you do?_ 
Compared two instances of the same query, one with a 7 day timeshift.   There is an alert in place should the two deviate significantly

_- What was the expected result?_ 
No alerts, both graphs match each other unless there is an issue with the service producing the metrics

_- What happened instead?_ 
Due to BST/GMT daylight saving change, we received several alerts this morning as the metrics deviated due to the 1 hour change.   (see screenshots below)
 
_Workaround:_ timeshift has been set to 167hours

_Workaround limitation:_ 

- the 167hr comparison will alert again in one week, whereby we will set this back to 7 days again.  
- we also have week-on-week comparisons (14d, 21d etc) which will need updating every week to compensate.  

_Questions:_ 

- Is there a way for Grafana to compensate for this automatically?  
- Or is it more of a Graphite issue?   
- Failing the above, is there a more elegant workaround?

Screenshots to illustrate the issue
![chrome_2017-03-27_11-06-27](https://cloud.githubusercontent.com/assets/11091780/24351430/85718b68-12dd-11e7-9226-d40afed9c9be.png)

![chrome_2017-03-27_11-04-54](https://cloud.githubusercontent.com/assets/11091780/24351376/5de7ea1a-12dd-11e7-82fd-928062d446a0.png)

**Comment by torkelo** [comment]
timeshift is processed in graphite-web/graphite-api,  it should handle daylight time saving to my knowledge. Maybe upgrade to latest version of Graphite.
