### ISSUE TITLE
Alerting/Datasource: Viewers can see ALL Contact Points, Notification Policies, Silences and Groups of the entire Organization, including Datasource names.

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#79519]
### What happened?

A user with only "Viewer" permission can see the entire Alerting section, with only the Alert Rules themselves being empty. They can, on the Alert Rules page access the names of all data sources, by selecting a dropdown.

![image](https://github.com/grafana/grafana/assets/24855949/bd93cca5-9a78-4a5c-89e8-d5dd843d8620)
![image](https://github.com/grafana/grafana/assets/24855949/b7cd596d-3354-47eb-8e95-aae1f068786c)

### What did you expect to happen?

Viewer role users should not be able to view *anything* relating to Alerting.

The entire Alerting section should not show up for Viewers, just like the "Connections" section is also entirely inaccessible.

### Did this work before?

We noticed this while migrating from 8.5 to 10.

in 8.5 this was not an issue.

### How do we reproduce it?

1. create alert as admin
2. create viewer account
3. log in as viewer
4. click menu, then alerts, and see that viewer roles can see almost everthing

### Environment (with versions)?

Grafana: v10.0.5
OS: Ubuntu 21.10, Docker
Browser: Firefox 120

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
Thank you for reporting this issue @laundmo 

I am routing the issue to the Alerting squad for review

**Comment by tonypowa** [comment]
@laundmo 

I reached out internally and in OSS Grafana, [users roles](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/#basic-roles) such as the viewer role, are made of a number of [permissions](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/#basic-role-assignments). For example the permission that allows viewers to view contact point details is `fixed:alerting.notifications:reader`

You can use RBAC to modify the permissions associated with any basic role. However, this is only available in [Grafana Enterprise](https://grafana.com/docs/grafana/latest/introduction/grafana-enterprise/) and [Grafana Cloud](https://grafana.com/docs/grafana-cloud).

**Comment by tonypowa** [comment]
I'll mark this issue as solved,  but feel free to comment if you have any further questions
Thank you

**Comment by laundmo** [comment]
"Pay us so we wont leak important details to other users" is a really unsatisfying answer, please reconsider.

This permission is clearly falsely present for viewer role users, so even if OSS cant change it the default is wrong.

**Comment by guilhermebrgs** [comment]
We need a solution for this, it is a huge security flaw to release this type of information, even if only for viewing by certain users.

**Comment by guilhermebrgs** [comment]
Any answers on this? This is a considerable security flaw.

**Comment by laundmo** [comment]
@tonypowa please reconsider this issue. the default for OSS grafana should be that roles apply to all things equally. This is not a request for allowing enterprise features for OSS users. The default should be changed though, to be secure by default.

**Comment by Maxisokol** [comment]
@tonypowa Hi, I would like to also kindly bump this issue.
Quite surprised that this is a default setting. Still present in version 11. Please, could you raise a flag to change this default setting such that viwers wouldn't be able to see at least all the contact points? That just sounds like such a clear oversight to me.
Thanks!

**Comment by laundmo** [comment]
I have given up, clearly Grafana wants to push people towards paying for the basic decency of common-sense privacy.

This issue alone has caused us to entirely disable alerting in Grafana. The hassle of dealing with the potential that any users could see this is not worth the convenience of Alerting grants. A few scripts running in Cron work just as well.

**Comment by Talhazzers** [comment]
I received feedback from a client today indicating that all contact points are visible. All our sensitive contact point API connections have been leaked and could be viewed by viewers. The fact that this is visible to everyone by default is a major vulnerability and needs to be urgently resolved.
