### ISSUE TITLE
[Bug] Cannot select values from tables

### ISSUE THREAD

**Issue by dlsniper** [grafana/grafana#7956]
Please include this information:
- What Grafana version are you using?
4.1.2
- What datasource are you using?
AWS CloudWatch
- What OS are you running grafana on?
AWS Linux
- What did you do?
Created a Table panel and a Graph panel with a Legend as table enabled, populated with data, tried to select the data in the tables
- What was the expected result?
Be able to select the values so that I can copy-paste them
- What happened instead?
It's impossible to select any values from it.
From what I can see, it's not possible to select anything from anywhere.

Thank you.

**Comment by torkelo** [comment]
This is an old bug (https://github.com/grafana/grafana/issues/2083) that is still not fixed :( 

Work around is to enter view or edit mode

**Comment by dlsniper** [comment]
Oh, I've missed that, definitely blame Github issues on this. I'm sorry for opening a duplicate issues. Thank you.
