### ISSUE TITLE
Is it possible to upgrade the performance of grafana by changing the precission of the points?

### ISSUE THREAD

**Issue by Metamathematics** [grafana/grafana#7957]
My grafana is showing very low performance. Im using grafana-3.1.1 and influxdb-1.0.2 as backend.
OS: Windows 2008 R2 Enterprise

In the past the graphs were very fast, but with the rise of the ammount of data it slows down.
I had an bad decision accidentally: I have used microseconds (-ms) flag when i was importing data to influx, but the actuall precisiion is seconds.
So grafana is now working with microseconds too. I can probably change it, but it would cost a lot of time and Im not sure about the output of this work. Would it be reasonable for performance to change the precission? Could this solution improve the performance of grafana or should I search for some other solutions?

**Comment by torkelo** [comment]
If it slows down your query must be doing something wrong. Make sure you group by time($interval) , grafana will automatically set interval depending on the time range and how wide the panel is so there is never more data points returned than there are pixels in the graph.
