### ISSUE TITLE
[accessibility issue] Focus lost when opening keyboard shortcuts from help menu

### ISSUE THREAD

**Issue by ckbedwell** [grafana/grafana#79585]
**Steps to reproduce**:
Go to any Grafana instance (e.g. play.grafana.com), click the "Help" button and select "Keyboard shortcuts", the keyboard shortcuts modal appears. Focus goes to the body element and not automatically to the close button.

Note that if you open the modal with the keyboard shortcuts instead that focus is handled correctly.

UHG Audit Id: 2.43

**Comment by tskarhed** [comment]
Is an issue in other types of modals?

**Comment by tskarhed** [comment]
@ckbedwell Is this fixed? I can't reproduce. However, there is another issue, when using the keyboard. The focus isn't moved directly to the modal.

**Comment by ckbedwell** [comment]
@tskarhed This is actually fixed :D It has a very minor issue that the the close button receives `:focus` rather than `:focus-visible` but that is pretty small so I'm going to close this as complete 😄
