### ISSUE TITLE
[User permissions according to dashboards]

### ISSUE THREAD

**Issue by yash9amnex** [grafana/grafana#79638]
### What happened?

I have created multiple users in an organization I want to achieve particular user will see particular dashboard only.
But in my case all the users are able to see all the dashboards in that organization.
According to official document I have follow the steps.

### What did you expect to happen?

Not all the users will able to see all the dashboards in that organization only a particular user which i want will have that permission to see that dashboard.
Added the permissions in dashboard also but not working.

### Did this work before?

No, this is not working at all.

### How do we reproduce it?

- Sign in to Grafana as an organization administrator.

- In the left-side menu, click Dashboards.

-     Hover your mouse cursor over a folder and click Go to folder.

-     Click the Permissions tab, and then click Add a permission.

-     In the Add Permission For dropdown menu, select User, Service Account, Team, or Role.

-     Select the user, team, or role.

-     Select the permission and click Save.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
hi @yash9amnex 
please provide:

- version of Grafana 
-browser (and version)
- which option did you use `user, team or role`?  
- could you include screenshots of the permission settings for the dashboards in question?

thank you
