### ISSUE TITLE
[Feature request] Discord.gg integration

### ISSUE THREAD

**Issue by jereksel** [grafana/grafana#7964]
Discord.gg is slack-like platform for gamers. It seems to be popular also with dev teams, because of free voice chat, unlimited messages and unlimited number of uploaded files.

PR that implements integration: https://github.com/grafana/grafana/pull/7926

**Comment by phit** [comment]
How much interest is needed for this to be looked at again? Discord is becoming quite huge and "500 Bad Request" using the slack hook is becoming rather annoying.

**Comment by LucaDev** [comment]
Well... Looks like there is some interest now. 17 upvotes  is quite a bunch. It just has to be merged

**Comment by LucaDev** [comment]
@torkelo Any news on this?

**Comment by phit** [comment]
@daniellee sorry to bump this again, but with Discord quickly becoming one of the biggest messaging services this would be really nice to have, there is an existing PR at #7926 in which you mentioned if this gets enough support it will get merged

**Comment by carlbennett** [comment]
I'd like support for this as well.

**Comment by RedSpid3r** [comment]
+1 to this please

**Comment by FileInputStream** [comment]
+1 Would be useful to use for discord. Please add support for this.

**Comment by daniellee** [comment]
Reopened the PR as there seems to be some interest in it :smiley: 

We have just released 5.0 beta so it might be a few weeks before we get around to merging it though.

**Comment by Scrayos** [comment]
Sounds fantastic!

**Comment by RedSpid3r** [comment]
any update on this?? :D

**Comment by carlbennett** [comment]
Looking for an update on this. The current Slack-to-Discord hack no longer reports on alerting/no-data and only on OK.

**Comment by phit** [comment]
@carlbennett https://gist.github.com/phit/ee024bf11f1943e2dac97526109d7871

**Comment by Astraithious** [comment]
Also looking for this! Our dev team has a bunch of bots set up for influxdb to discord as well as mysql, even running queries from the chat. If I can get alerts to discord this would be absolutely perfect

**Comment by kot83** [comment]
bump

**Comment by RedSpid3r** [comment]
sorry to go off topic but @Astraithious you have a discord monitoring bot for influx/grafana? Are these OpenSource? I'm looking for a stats bot that'll work with grafana also!

**Comment by Manevolent** [comment]
bump

**Comment by phit** [comment]
@cleanunicorn read the damn PR or try it before being a smartass

>Discord has slack webhook integration, but I found it very unreliable (on our production server I got "Context timeout" and on newest master "500 Bad Request"), so I decided to implement native solution.

Discords slack endpoint has been broken for years, and drops messages randomly..
