### ISSUE TITLE
Canvas: Allow for canvas elements to directly open data links

### ISSUE THREAD

**Issue by zs-dima** [grafana/grafana#79698]
Could be nice to add an option to make Canvas panel clickable to be able turn them into beatiful buttons and tiles with extra information.
Curretly it is no option to assign URL to open on panel click.
Panel links and Data links displayed in tooltips only and can not be used in this case.

![image](https://github.com/grafana/grafana/assets/25195453/1aa124a8-082d-45b6-a7fe-b0428908e1c5)

![image](https://github.com/grafana/grafana/assets/25195453/0a745b61-cb42-45b1-a2ef-6d39dd6a9798)

**Comment by gelicia** [comment]
I chatted with @zs-dima about this - the request is the option where clicking the element would go directly to the link in question, skipping the tooltip. The example shown at https://play.grafana.org/d/canvas-examples/panel-tests-canvas-examples?orgId=1 is close but the current flow where it clicks to open the tool tip to select the link isn't as straightforward as they'd like.

**Comment by zs-dima** [comment]
@gelicia thanks a lot for the details.

In addition it would be nice to make not only metric-value elements clickable, but also the Panel itselt. 
(or at least to a Rectangle element without a linked field, to be able to put transparent one over the panel as a workarround).
![image](https://github.com/grafana/grafana/assets/25195453/57061342-8620-4b77-b183-0eeb672e2174)

Maybe Button can have option to open URL as well.

Currently looks a bit strange to press button to open tooltip to press item to open URL...

**Comment by GCIotron** [comment]
Hello! 
We're also interested in the requested feature, in particulary we like to make canvas's metric and text values elements clickable to open a link when there is only one DataLink defined for the canvas's element. 
I also think that would be useful to show a popup when there are more the one DataLink defined for a canvas's element in order to let the user to choose one of them.

**Comment by nmarrs** [comment]
Hey @zs-dima - thanks for raising up this issue - I think these two PRs (expanding [data link support vastly](https://github.com/grafana/grafana/pull/84142) + [one click access mode](https://github.com/grafana/grafana/pull/85430)) get us a little closer to this reality (with a current work around now being adding a phantom data link to a "hidden" property such as background image that will make the element able to include a link)

In this way for your original request you could simply add a transparent rectangle that has its background property tied to a dummy data value and be able to configure clicking on said element bounds to wherever you like achieving the affect you are after.

https://github.com/grafana/grafana/assets/22381771/5a87859f-754c-4ede-909b-941074717dd6

**Comment by nmarrs** [comment]
Addressed by https://github.com/grafana/grafana/pull/89079 🎉
