### ISSUE TITLE
Dashboards: on mobile, choosing the time range zooms in the window

### ISSUE THREAD

**Issue by freak12techno** [grafana/grafana#79702]
### What happened?

Better show once than describing in text.

1. Open a dashboard on mobile (I use Safari, also tested it on Chrome and got the same behaviour):
![telegram-cloud-photo-size-2-5190566761920057681-y](https://github.com/grafana/grafana/assets/83376337/7c670999-d03b-479e-80d7-0e7c349bbaef)
2. Click the three dots at the top (so far everything's good):
![telegram-cloud-photo-size-2-5190566761920057682-y](https://github.com/grafana/grafana/assets/83376337/f93d3065-82e1-47c1-b4fb-05e5dfd28d07)
3. Choose the time range (notice the page is zoomed in a bit):
![telegram-cloud-photo-size-2-5190566761920057683-y](https://github.com/grafana/grafana/assets/83376337/af06318c-35d4-4db1-9898-c120600bdf35)
4. The time range picker closes, and the page is stayed zoomed in as on step 3:
![telegram-cloud-photo-size-2-5190566761920057684-y](https://github.com/grafana/grafana/assets/83376337/db3d53c6-92ae-4d64-bcfd-57facb27138a)
 

### What did you expect to happen?

Page should not zoom in, as I have to zoom it out every time I need to change a time range and it's quite inconvenient.

### Did this work before?

Not sure to be honest.

### How do we reproduce it?

See steps above.

### Is the bug inside a dashboard panel?

It applies to all the dashboards I have

### Environment (with versions)?

Grafana: latest at the moment
OS: iOS
Browser: Safari (also reproducible on Chrome at least)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
hi @freak12techno  thanks for reporting the issue

Could you please provide the following additional details?

- **Exact version of Grafana**: you're using. 'Latest' can often mean different versions, depending on the source or time of download.
- **Device and OS version:** could be helpful
- Export the panel via --> more --> get help workflow in the panel's dropdown menu. This will help up mock up your data and reproduce your issue


Thank you

**Comment by freak12techno** [comment]
@tonypowa For Grafana version:
```
monitoring@monitoring-logging ~ ❯ grafana-server -v                                                                                                                                                14:39:49
Version 10.2.3 (commit: 1e84fede543acc892d2a2515187e545eb047f237, branch: HEAD)
```

For device and OS version: I use iOS 17.2 and could reproduce it on both Safari (not sure which version or how to check it) and on Chrome (120.0.6099.119).
For panels, it can be reproduced on any panel, I can reproduce it on any of mine at least. Creating a new panel with some data and trying to reproduce it there should work.

**Comment by ashharrison90** [comment]
hi @freak12techno 👋 

thanks for reporting this 🙌 

a quick explanation: this is specific to iOS, and is intended behaviour on their part. any input with font-size < 16px will be zoomed in on when focused. because our default font size is 14px and we autofocus the search input when opening the time picker, this causes the zooming behaviour. i've removed the autofocus in [this PR](https://github.com/grafana/grafana/pull/80961), but note that when manually focusing the input this will still happen.

hope that helps
