### ISSUE TITLE
Mentions in team

### ISSUE THREAD

**Issue by Thamizhvanan-R** [grafana/grafana#79721]
**Why is this needed**:

[Add a description of the problem the feature is trying to solve.]

**What would you like to be added**:

[Add a brief description of what the feature or enhancement should do.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Comment by tonypowa** [comment]
Hi @Thamizhvanan-R 

Could you please elaborate on the description of this feature request? 

Thank you!

**Comment by Thamizhvanan-R** [comment]
Hi @tonypowa 
This is a duplicate of the issue - https://github.com/grafana/grafana/issues/77545

**Comment by tonypowa** [comment]
thanks @Thamizhvanan-R 
ok then let's close it so we don't split the attention and upvotes :)
