### ISSUE TITLE
[Feature request] Rename 'allow_sign_up' variable

### ISSUE THREAD

**Issue by f-breidenstein** [grafana/grafana#7972]
The variable name "allow_sign_up" is misleading for external auth mechanism like e.g.  LDAP. It suggests that people can register new accounts, but instead it's responsible for the account creation in the internal user database  of Grafana. 
The comment in the `[user]` sections says `# disable user signup / registration` which strengthens the wrong interpretation of the variable.
Something like "auto_create_users" would be more descriptive in my opinion, or one could add a line of code explaining the "new"/different function of this variable.

Best regards,
Felix

**What Grafana version are you using?**
4.0.0.

**What did you do?**
Configure LDAP authentication

**What was the expected result?**
User shoudl be able to log in via LDAP but are not allowed to create acocunts.

**What happened instead?**
User can't log in

**Comment by torkelo** [comment]
I can see how it can be misleading, but you signup to services and sites using OAuth, but you use an existing account to do it so I think it's the most common term. 

allow sign up basically means that people can register new accounts if they pass the LDAP authentication. It's a bit late to change the config key as it would be a breaking change (we could leave the old key and add a new and have support for both). But maybe best thing is to update documentation and comment and make it more clear what the setting does.
