### ISSUE TITLE
Unified Alerting Migration: invalid character in string escape code

### ISSUE THREAD

**Issue by cpretzer** [grafana/grafana#79720]
### What happened?

We have migrated from Grafana 8.4.2 to 9.5.5 in multiple steps, and one of the steps is to migrate from legacy alerting on 9.5.5 to Unified Alerting.

After updating the grafana.ini config to disable alerting and enable unified alerting, we see an error during the `move dashboards to unified alerting` migration that describes an invalid character in the escape code.

Configuration via helm values.yaml file:
```
grafana:
...
    alerting:
      enabled: false
    unified_alerting:
      enabled: true
```

Log output:
```logger=migrator t=2023-12-19T17:51:58.844473524Z level=info msg="Starting DB migrations"
logger=migrator t=2023-12-19T17:51:58.89066255Z level=info msg="Executing migration" id="clear migration entry \"remove unified alerting data\""
logger=migrator t=2023-12-19T17:51:58.932305811Z level=info msg="Executing migration" id="move dashboard alerts to unified alerting"
logger=migrator t=2023-12-19T17:51:59.050119836Z level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="invalid character ':' in string escape code"
logger=migrator t=2023-12-19T17:51:59.050151123Z level=error msg="Exec failed" error="invalid character ':' in string escape code" sql="code migration"
Error: ✗ migration failed (id = move dashboard alerts to unified alerting): invalid character ':' in string escape code
```

This appears to be the same behavior as #65097 with a different character

### What did you expect to happen?

I expected the dashboards to be migrated to unified alerting from legacy alerting without any errors

### Did this work before?

This is the first time that we have attempted the migration.

### How do we reproduce it?

1. Run an instance of Grafana 8.4.2 using sqlitedb to store legacy alerts
2. Create some dashboards with ":" in the messaage
3. Upgrade the 8.4.2 instance to 9.5.5
4. Export the sqlite database file from the 8.4.2 instance
5. Use [grafana/database-migrator](https://github.com/grafana/database-migrator) to convert the sqlite database to a format that MySQL can consume
6. Configure a MySQL instance to store data for Grafana 9.5.5
7. Import the file created in step 5 to the MySQL instance
8. Configure Grafana 9.5.5 to use the MySQL instance with _legacy alerting_
9. Start Grafana 9.5.5 and ensure that all the migrations complete successfully
10. Stop Grafana 9.5.5 and update grafana.ini to disable `alerting` and enable `unified_alerting`
11. Start Grafana 9.5.5 and watch the logs for errors

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 8.4.2 upgraded to 9.5.5
OS: Linux
Browser: Arc

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @cpretzer 

thank you for reporting this issue. It is now added to the Alerting squad board for review

In the meantime, could you please provide the specific section or format of the dashboard JSON that includes the : character where you mentioned adding it in the message? 

Thank you

**Comment by armandgrillet** [comment]
Asking for the same as in https://github.com/grafana/grafana/issues/56338#issuecomment-1267466463, can you check the alert table for `\:`?

**Comment by cpretzer** [comment]
There are definitely `\:` characters in the alert_rules table. I see that the `data` field is a text field that stores JSON. 

From what I can tell, the JSON isn't validated upon insertion. However the migration fails when the JSON is unmarshaled, because it is invalid.

It's been a couple of weeks since I looked into this, so much of this has fallen out of my brain. 🧠

**Comment by KaplanSarah** [comment]
This is a problem with the database migrator.  For now the best solution is the one listed in https://github.com/grafana/grafana/issues/65097.
