### ISSUE TITLE
Grafana 10.2.3 is breaking CloudWatch plugin for Safari

### ISSUE THREAD

**Issue by joergheber** [grafana/grafana#79722]
### What happened?

After upgrading from Grafana 10.2.2 to Grafana 10.2.3, the CloudWatch data source brings up an error message. None of the CloudWach configurations load for dashboards. 

"CloudWatch plugin failed
TypeError: undefined is not an object (evaluating 'Qs')"

<img width="490" alt="Screenshot 2023-12-19 at 10 56 55 AM" src="https://github.com/grafana/grafana/assets/90109860/e3ff775b-2e06-40d9-b71c-38d950b07003">
<img width="727" alt="Screenshot 2023-12-19 at 10 57 32 AM" src="https://github.com/grafana/grafana/assets/90109860/a1a23a15-6461-4a38-8364-47ad670bedfb">

### What did you expect to happen?

The plugin to work as it did in the previous version.

### Did this work before?

Yes, it worked fine across all browsers prior to 10.2.3

### How do we reproduce it?

1. Use Docker grafana/grafana-enterprise
2. Install or update to 10.2.3
3. In Safari, go to "Connections", "Data Sources", "CloudWatch", "Explore"

### Is the bug inside a dashboard panel?

it is generic and also appears when exploring the data source itself.

### Environment (with versions)?

Grafana: 10.2.3
OS: MacOS Sonoma 14.2, iOS 17.2
Browser: Safari

### Grafana platform?

Docker

### Datasource(s)?

CloudWatch 5.0.0

**Comment by joergheber** [comment]
PS: I forgot to mention above that Grafana works as expected in Chrome and Firefox on MacOS. I also cleared out any browser and system caches.

**Comment by alex-tate** [comment]
I have got a very similar issue that has occured when we updated from 10.2.2 to 10.2.3 overnight. However, in our case it is our PostgreSQL plugins that have broken.

![image](https://github.com/grafana/grafana/assets/81570091/7992fd38-4e5f-4638-b32a-ab39597c9551)

I have taken a look at the installed plugins and there appears to be two Postgres plugins installed..

![image](https://github.com/grafana/grafana/assets/81570091/d1e0627a-0e5a-48b1-8df3-d0c8b6f4965f)

One of the Postgres plugin details looks fine, the other looks like this...

![image](https://github.com/grafana/grafana/assets/81570091/dc0449dc-64ac-40e9-8f28-8b19bd742f6d)
 
I'll do some further investigations but the upshot is that all of our dashboards are non-functioning - not ideal.

**Comment by alex-tate** [comment]
Apologies, I jumped the gun on this one. Restarting the Grafana service was enough to clear the issues we were seeing with our Postgres data sources. It is unclear why an earlier restart after the v10.2.3 patch left it in this state but all good now. Quite possibly nothing to do with the CloudWatch issue reported by @joergheber

**Comment by joergheber** [comment]
this appears to be the same issue as reported in  #79347, which is marked as closed and fixed. But at least for me it seems still an issue...
