### ISSUE TITLE
[Feature request] on dashboard modification, refresh all sessions currently viewing that dashboard

### ISSUE THREAD

**Issue by tomschlick** [grafana/grafana#7973]
As someone who uses grafana on status board type displays hung on the wall (powered by raspberry pi's), it would be great if when I modified & saved a dashboard on my laptop, those screens would auto refresh.

Currently I have to ssh/vnc into those boxes and refresh the screens manually.

What I am proposing is something like a checkbox on the dashboard's settings that says "On modification, auto-refresh all viewers".

When that is enabled, grafana would check the last modified date of the dashboard every X seconds. If it's newer than the previous date, it reloads.

**Comment by torkelo** [comment]
Some auto reload or notice (if local changes) would be nice, very similar to this request (https://github.com/grafana/grafana/issues/7369) so closing this one.
