### ISSUE TITLE
What's the meaning of red/green dotted line?

### ISSUE THREAD

**Issue by dlintw** [grafana/grafana#7974]
Is there document about the meaning of dotted line?
I've trying to zoom it to maximum and put cursor on the line, but found the numbers are the same as neighbors.

![grafana_dot_line](https://cloud.githubusercontent.com/assets/326179/24433619/955e38e8-145c-11e7-8589-ed3c7d604f1d.png)

**Comment by bashgeek** [comment]
Red meaning an alert triggered and green meaning an alert cleared. Check your alert settings for details.

**Comment by dlintw** [comment]
I have setup a alert evaluate every 60s.
WHEN max() OF query(A,1m,now) IS ABOVE 0.002
if no data or all values are null SET STATE TO No Data
if execution error or timeout SET STATE TO Alerting.

I've check the value of the stats all are below 0.002.

I've pressed the 'Test Rule' and get the following result.
result
firing false
state ok
conditionEvals false = false
timeMs 3.897ms
logs [ [object Object], [object Object], [object Object], [object Object], [object Object], [object Object] ]

**Comment by dlintw** [comment]
Well, I understood. The rule is base on 1 min, so, for example:
10:10:10 occurs 0.00278
10:11:01 alert show red dotted line because during 10:10:00~10:11:00 the max() value is 0.00278 which greater then 0.002.
10:12:01 alert show green dotted line because during 10:11:00~10:12:00 the max() value is below 0.002.

**Comment by zyxue** [comment]
Sometimes I see yellow dotted line, what does yellow mean?

**Comment by macetw** [comment]
Yellow line likely means "pending," as if an alert rule is violated, but only for an instant before a 5-minute window for the alert is required.
