### ISSUE TITLE
scheduler job offset

### ISSUE THREAD

**Issue by Jaware** [grafana/grafana#7975]
i read your   source code about alerts,but can not understand the function of job offset,can anyone tell me ?
```javascript
if job.OffsetWait && now%job.Offset == 0 {
			job.OffsetWait = false
			s.enque(job, execQueue)
			continue
		}

		if now%job.Rule.Frequency == 0 {
			if job.Offset > 0 {
				job.OffsetWait = true
			} else {
				s.enque(job, execQueue)
			}
		}
```

```javascript
func (s *SchedulerImpl) Update(rules []*Rule) {
	s.log.Debug("Scheduling update", "ruleCount", len(rules))

	jobs := make(map[int64]*Job, 0)

	for i, rule := range rules {
		var job *Job
		if s.jobs[rule.Id] != nil {
			job = s.jobs[rule.Id]
		} else {
			job = &Job{
				Running: false,
			}
		}

		job.Rule = rule

		offset := ((rule.Frequency * 1000) / int64(len(rules))) * int64(i)
		job.Offset = int64(math.Floor(float64(offset) / 1000))
		if job.Offset == 0 { //zero offset causes division with 0 panics.
			job.Offset = 1
		}
		jobs[rule.Id] = job
	}

	s.jobs = jobs
}
```

**Comment by torkelo** [comment]
The function is to distribute execution so not all alerts are executed the same second. For example if you have 100 rules that should be evaluated every 60 seconds, the job offset will try to distribute the tick when they are evaluated so they are not all evaluated the same second. 

```go
offset := ((rule.Frequency * 1000) / int64(len(rules))) * int64(i)
```

Say frequency is 60 seconds, and we have 100 rules, and this rule has index 10 in the array
offset = (60000 / 100) *10 = 6000
offset = (60000 / 100) *15 = 4000

so each rule gets an offset (later divided to whole seconds), so they are not scheduled for execution on the same second.

**Comment by Jaware** [comment]
thanks
