### ISSUE TITLE
Error when run command "yarn install --pure-lockfile" and command "bra run"

### ISSUE THREAD

**Issue by dejokuondi** [grafana/grafana#7976]
Hi,
When I run command "yarn install --pure-lockfile", It's error:

yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠂ iltorb: node@7.7.4 | linux | x64
[2/3] ⠂ node-sass
[3/3] ⠂ phantomjs-prebuilt
[-/3] ⠂ waiting...
warning Error running install script for optional dependency: "/home/ubuntu/grafana/src/github.com/grafana/grafana/node_modules/iltorb: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node-gyp rebuild\nDirectory: /home/ubuntu/grafana/src/github.com/grafana/grafana/node_modules/iltorb\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.0\ngyp info using node@7.7.4 | linux | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.\ngyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/yarn/node_modules/node-gyp/lib/configure.js:482:19)\ngyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/yarn/node_modules/node-gyp/lib/configure.js:396:16)\ngyp ERR! stack     at F (/usr/lib/node_modules/yarn/node_modules/which/which.js:68:16)\ngyp ERR! stack     at E (/usr/lib/node_modules/yarn/node_modules/which/which.js:80:29)\ngyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/which/which.js:89:16\ngyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/isexe/index.js:42:5\ngyp ERR! stack     at /usr/lib/node_modules/yarn/node_modules/isexe/mode.js:8:5\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)\ngyp ERR! System Linux 4.4.0-64-generic\ngyp ERR! command \"/usr/bin/nodejs\" \"/usr/lib/node_modules/yarn/node_modules/node-gyp/bin/node-Done in 43.69s.

And when I run command "bra run" to Recompile backend on source change:

ubuntu@ip-10-0-1-101:~/grafana/src/github.com/grafana/grafana$ bra run
No command 'bra' found, did you mean:
 Command 'brag' from package 'brag' (universe)
 Command 'bar' from package 'bar' (universe)
 Command 'bro' from package 'bro' (universe)
 Command 'br' from package 'bottlerocket' (universe)
 Command 'ra' from package 'argus-client' (universe)
 Command 'bwa' from package 'bwa' (universe)
 Command 'ara' from package 'ara' (universe)
bra: command not found

Please help me to build grafana from source

**Comment by torkelo** [comment]
Did you follow this guide?
http://docs.grafana.org/project/building_from_source/#recompile-backend-on-source-change 

You seem to have missed installing bra (which is a tool that recompiles the backend when you modify go files). 

Please open questions on the community site:
https://community.grafana.com 


For the yarn install part, try installing node LTS (v6.10.1), also OS and platform your using is helpful

**Comment by dejokuondi** [comment]
@torkelo
I run command "go get github.com/Unknwon/bra"
but when run command "bra run" error.

**Comment by daniellee** [comment]
Is your $GOPATH/bin directory in your $PATH?

See installation instructions for Golang:
https://golang.org/doc/install#tarball
