### ISSUE TITLE
Authentication: Grafana LDAP Logout broken in 10.2.3 (works in 10.2.2)

### ISSUE THREAD

**Issue by Terr4** [grafana/grafana#79778]
### What happened?

We just upgraded from 10.2.2 to 10.2.3 and in the new version the Logout does not work anymore with LDAP authentication.
When pressing the LOGOUT button on top right it redirects to "**https://servername/logout**" and displays an error page (ERR_EMPTY_RESPONSE).

Only way to logout of Grafana now is by deleting the cookies in the browser.

I saw that all auth types have received a new property in 10.2.3 called "signout_redirect_url" and the LDAP auth method is missing this property. Maybe this is related, however even after adding this property in the LDAP block it does not fix the issue.

### What did you expect to happen?

I am logged in with LDAP, I press the logout button and get logged out and get redirected to the Grafana loginpage

### Did this work before?

Yes, worked in 10.2.2

### How do we reproduce it?

1. Enable LDAP Auth
2. Login with an LDAP user
3. Press Logout in Top Right corner

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.3
OS: Windows Server 2022
Browser: Edge

### Grafana platform?

A downloaded binary

**Comment by kalleep** [comment]
Hey, thanks for the issue. 

This is something we have already fixed in https://github.com/grafana/grafana/pull/79271. We probably need to backport the fix so it is included in next 10.2.x release
