### ISSUE TITLE
[Feature request] Commit dashboards to git on change

### ISSUE THREAD

**Issue by Civil** [grafana/grafana#7977]
Sometimes people complain that they want to control who why and when changing their dashboards.

That's why we came up with a feature request:
Have an ability to commit dashboards to git on change. So we'll be able to create a dedicated server that will allow people to do the changes and a bunch of real-world production frontends that will be in read-only mode.

**Comment by ihard** [comment]
+1 Really need the functionality

**Comment by utkarshcmu** [comment]
@Civil @ihard u can use https://github.com/utkarshcmu/wizzy

**Comment by Civil** [comment]
@utkarshcmu That's not exactly what I want, sorry.
