### ISSUE TITLE
Explore: TimeRange defaulting to 6 hours since v10.1.0

### ISSUE THREAD

**Issue by andykingit** [grafana/grafana#79777]
https://github.com/grafana/grafana/assets/109355108/498e3d18-fbbb-4947-9220-83e1380dd4b1

### What happened?

Since v10.1.0 the default TimeRange when navigating to Explore in the UI is 6 hours. In versions >10.1.0 it was always 1 hour

### What did you expect to happen?

When opening explore the TimeRange is 1 hour. By default we realise that most users will ignore the value in the TimeRange, build the query and then run it before they consider the time range. I cant find any references to the change in the CHANGELOG so I believe this is a unexpected action.

### Did this work before?

Yes in versions less than 10.1.0

### How do we reproduce it?

1.  With docker running: `docker run -d -p 3000:3000 --name=grafana grafana/grafana:10.1.0`
2. Go to the [UI](http://localhost:3000/explore?) 
3. See that the TimeRange in the top right is 6 hours

To see how it worked before the release:

1.  With docker running: `docker run -d -p 3000:3000 --name=grafana grafana/grafana:10.0.10`
2. Go to the [UI](http://localhost:3000/explore?) 
3. See that the TimeRange in the top right is 1 hours

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: >10.1.0 (Checked many versions above this, same issue persists)
OS: OSX
Browser: Chrome (120.0.6099.129)

Our production environments are deployed using helm, but I have locally grabbed various versions of the docker file to test locally and the same issue exists, so this is not isolated to the helm deployments.

### Grafana platform?

Docker

### Datasource(s)?

Not limited to datasource

**Comment by gelicia** [comment]
@andykingit Just wondering how you're accessing explore - do you have bookmarked URLs that you're using? If so, can you share a URL with me - feel free to anonymize any query data, etc you don't want to share.

Why I'm asking: The default range for explore has been 6 hours for [a while](https://github.com/grafana/grafana/blame/main/public/app/features/explore/state/utils.ts#L34), but some sort of user flow must have overridden that and a change is now preventing that from happening. I just have to do a little more investigation to find out what you [and others](https://community.grafana.com/t/change-grafana-explore-ui-default-time-range/106801) are running into.

**Comment by andykingit** [comment]
@gelicia thanks for the response. I am not using the bookmark to get to explore, I go via grafana toggle menu and straight to explore directly each time. 

Just for clarity the link for me when I hit the explore page ends up being: 

https://monitoring.xxxx.cloud/explore?panes=%7B%22KxR%22:%7B%22datasource%22:%2xxxxxx%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xxxxxx%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
