### ISSUE TITLE
How to set [auth.anonymous] in the grafana.ini for 2 or more than 2 orgnizaitions accessed anonymously?

### ISSUE THREAD

**Issue by leee66** [grafana/grafana#7979]
Hi,
I configed many orgnizations in the Grafana. Now there are 2 orgnizations (named as CBS and TMC) , which need to be accessed anonymously. However, how to set [auth.anonymous] in the grafana.ini?

**Comment by torkelo** [comment]
only one can be accessed anonymously

**Comment by leee66** [comment]
Will this feature be added in future? Thanks.

**Comment by leee66** [comment]
@torkelo Will this feature be added in future? Thanks.

**Comment by torkelo** [comment]
not very likely

**Comment by leee66** [comment]
@torkelo  Why? Is this feature not good?

**Comment by torkelo** [comment]
so far it's never been requested, and it would involve some changes to url structure to know which org to use

**Comment by leee66** [comment]
@torkelo thanks for your reply
