### ISSUE TITLE
Tempo Service Graph bad_data error when span has regex in name

### ISSUE THREAD

**Issue by toporek3112** [grafana/grafana#79791]
### What happened?

When going to the Explore page, selecting Tempo as datasource and selecting query type 'Service Graph' I see the following error:
![image](https://github.com/grafana/grafana/assets/24610056/67388cf3-6450-49c7-902c-9042d9126a9d)

This only happens when fetching spans which opentelemetry collects from kafka. These spans have a regex in their name. Here some examples:

- http delete /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**
- http get /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**
- http post /esb/{service:[a-za-z]+[\w-]*}/{version:[\d\.]*}/{serviceinstance:[a-za-z]+[\w-]*}/{operation:[a-za-z]+[\w-]*}
- http put /esb/{service:[a-za-z]+[\w-]*}/{serviceinstance:[a-za-z]+[\w-]*}/{version:[\d\.]*}/**

I checked passed issues on this topic and found:

- https://github.com/grafana/grafana/issues/4234
- https://github.com/grafana/grafana/issues/54849

Also there has been a [PR](https://github.com/grafana/grafana/pull/66301) which was supposed to fix this issue but apparently there are still some edge cases.

Let me know if this is an issue in Grafana or if we have to fix something on our side. Thank you!

### What did you expect to happen?

Service Graph is displayed

### Did this work before?

It worked before we started collecting spans from kafka where we store esb traces. These contain some regex in their name (see above)

### How do we reproduce it?

1. I provided the span names with the regex (I hope thats enought)
2.
3.

### Environment (with versions)?

- Firefox 115.5.0esr (64-bit)
- Chrome 120.0.6099.110
- Grafana 10.2.2
- tempo 2.3.0
- opentelemetry-collector-contrib 0.86.0-krb5fix (collecting spans from kafka)
- opentelemetry-collector-contrib 0.82.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo, Prometheus

**Comment by toporek3112** [comment]
Please let me know if you need any additional information

**Comment by toporek3112** [comment]
Hmm I just noticed that the node graph works when I do a TraceQL querry for a single trace id. 
Idk if that helps

**Comment by iarlyy** [comment]
```
Error (bad_data: invalid parameter "query": 1:105: parse error: unknown escape sequence U+002D '-'). Please check the server logs for more details.
```

`service GET /path/to/{somethingID}/subpath/{subpathID}/api/{targetPath:[a-zA-Z0-9=\-\/]+}`

I think that the escaped character is the issue, i am experiencing the same with an escaped dash (`-`)

**Comment by ttshivers** [comment]
I am also experiencing the same issue with mine looking like:
```
Error (bad_data: invalid parameter "query": 1:78: parse error: unknown escape sequence U+0048 'H'). Please check the server logs for more details.
```

when it is trying to do a query:
```
topk(5, sum(rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR",span_name=~"GET /|GET|Psr\\\Http\\\Server\\\RequestHandlerInterface@anonymous/var/www/vendor/slim/slim/Slim/MiddlewareDispatcher\\.php:108\\$35::handle|Slim\\\MiddlewareDispatcher::handle|Psr\\\Http\\\Server\\\RequestHandlerInterface@anonymous/var/www/vendor/slim/slim/Slim/MiddlewareDispatcher\\.php:138\\$36::handle"}[$__range])) by (span_name))
```

In this case, it looks like it's not properly escaping the the `\`. It should be using 4 backslashes `\\\\` but it's only using 3.
