### ISSUE TITLE
[Feature request] Message notification for OK Status

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#7980]
[Feature request]. 

Please include this information:
- What Grafana version are you using? 4.2.0
- What datasource are you using? influxdb
- What OS are you running grafana on? windows 2012 R2
- What did you do? slack alerts and notifications
- What was the expected result? have a message for [OK] status as well;
- What happened instead? we have a message only the [Alerting] status
![grafana_issue_2](https://cloud.githubusercontent.com/assets/22320901/24461201/1696c56e-14a9-11e7-8175-81d65151c5ac.png)
![grafana_issue_1](https://cloud.githubusercontent.com/assets/22320901/24461200/167d1d62-14a9-11e7-8c82-b198acb7e7bf.png)
![grafana_issue_proposal](https://cloud.githubusercontent.com/assets/22320901/24461199/167c9842-14a9-11e7-8d73-5378b7f2bf67.png)

thank you.

**Comment by torkelo** [comment]
This should be easy to fix, but in the meantime I suggest setting up the image store so you can get images on you alerting and OK slack notifications

**Comment by Go-Pomegranate** [comment]
Is this feature completed?

**Comment by Valantir007** [comment]
It will be very helpfull to fix that issue

**Comment by nishant-ketu** [comment]
@torkelo Do we have any update for this feature request? It is one of most requested feature.

**Comment by tlallen608** [comment]
Our company would also like to have this feature added for our Alerting in Grafana. It is confusing to the developers who do not have access to grafana to understand what metric is now in an OK state, especially when there are multiple alerts posted in slack.

**Comment by grobinson-grafana** [comment]
Hi! 👋 This is now present in resolved notifications for Grafana Managed Alerts. I think we can close this? @armandgrillet

**Comment by gelicia** [comment]
This is said to be resolved. Closing. If this is a mistake, please feel free to leave a comment on what is missing and I can reopen and send to the right team.
