### ISSUE TITLE
CloudWatch: No static label for alarm metric

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#79833]
### What happened?

We just migrated from version 9 to 10, where the alias was completely removed in favour of the dynamic labels. Until now we used `cloudWatchDynamicLabels = false` to avoid issues with the metric names for cloudwatch alarms. But because the feature toggle is no longer available we are looking for a way to override the alarm name in the label field:

![Screenshot 2023-12-22 at 12 56 11](https://github.com/grafana/grafana/assets/127092832/3548c97e-7387-4785-9d09-9302ad7aba2b)

In the screenshot above we define the label as `CIS`, but the panel renders `CIS CIS-CompositeAlarm` instead.

I found this old and closed issue pointing to the same problem, which still seems to exist: https://github.com/grafana/grafana/issues/51714

### What did you expect to happen?

I would expect to be able to replace the label of a cloudwatch metric with any static (or other) value via the label field.

### Did this work before?

It worked fine it version 8 and was still usable in version 9 with dynamic labels being disabled via feature toggle.

### How do we reproduce it?

1. Grafana 10
2. CloudWatch Plugin
3. Try to define custom static label for metric

### Environment (with versions)?

Grafana: 10.2.2
OS: macOS (Grafana is running in a linux docker container in AWS (`public.ecr.aws/bitnami/grafana`))
Browser: Chrome/Firefox/Safari

### Grafana platform?

Docker

### Datasource(s)?

CloudWatch

**Comment by usmangt** [comment]
Hi @frederikmartin1337 ,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by frederikmartin1337** [comment]
Thanks @usmangt. Our current solution to deal with the labels is to use field overrides, if we have a query per line and otherwise transform the field name data after the query.

**Comment by sarahzinger** [comment]
Glad you found a workaround! It does sound like we may have prematurely closed that ticket and then we mistakenly went forward with dynamic labels, losing sight of this breaking change. Our apologies!

Will bring this to the team and see if we can take a look in a sprint or two to see if there's something we can do on our end to handle this to let users override labels that aws returns in this case. Or if that's not possible for some reason, we should at least document this breaking change/loss of functionality, with an alternative work around such as the one you're describing documented somewhere. 

thanks for your patience and understanding!
