### ISSUE TITLE
Alertmanager: Grafana unusable with HA-configured Prometheus Alertmanager

### ISSUE THREAD

**Issue by olvesh** [grafana/grafana#79834]
### What happened?

<tl;dr>
Grafana by default has no way of listing several Alertmanager instances in a HA configuration as a datasource. When reading alerts this is fine, but when sending alerts, these must be sent to all Alertmanager Instances as [Alertmanager does not propagate these by itself](https://prometheus.io/docs/alerting/latest/alertmanager/#high-availability) 
</tl;dr>

I have configured Grafana to use a Prometheus Alertmanager and forward all Grafana Alerts to those instances, using a Kubernetes headless SVC dns entry in the Grafana Datasources UI.

When Grafana sends alerts to the alertmanagers, they end up being load balanced, causing each Alertmanager instance to have a different set of active alerts than the rest.
The "endsAt" field that autoresolves an alert if no new updates is received is also sometimes triggered making the alert appear to be flopping, even though the Grafana configured alert is still firing.

```
alertmanager-0 alertmanager ts=2023-12-22T14:24:05.818Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert="Disk Space cpmgmt1[2223b1a][active]"
alertmanager-2 alertmanager ts=2023-12-22T14:24:09.800Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert="Disk Space cp-fw1-2[0e36b69][active]"
alertmanager-0 alertmanager ts=2023-12-22T14:24:09.872Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert="Disk Space cp-fw2-1[b41b20f][active]"
```

Above is a excerpt from the Prometheus Alertmanager logs across all (3) instances, filtered on the alert name "Disk Space.*". This shows that the alert which is configured in Grafana is not sent to all alertmanagers, as each unique alert is only seen by one alertmanager.
This causes the next update of the alert state to go to an another instance of the Alertmanagers, causing the original alert to resolve via `endsAt` field timing out - normally after few minutes.

### What did you expect to happen?

According to [Alertmanager Documentation](https://prometheus.io/docs/alerting/latest/alertmanager/#high-availability) Alertmanager does not sync alerts between instances, all alerts must be sent to all Alertmanagers.

This does not happen when Grafana alerts are sent to Alertmanager. Filtering logs on an alert sent from Prometheus clearly shows the alert sent to all instances at the same time:

```
alertmanager-0 alertmanager ts=2023-12-22T14:31:26.216Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=KubePodCrashLooping[f136c7c][active]
alertmanager-1 alertmanager ts=2023-12-22T14:31:26.216Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=KubePodCrashLooping[f136c7c][active]
alertmanager-2 alertmanager ts=2023-12-22T14:31:26.217Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=KubePodCrashLooping[f136c7c][active]
```

When using a Headless SVC in Kubernetes, translating to multiple A-records, I expect Grafana to multiplex and send to all Alertmanagers, as this is clearly how Alertmanager expects to be used.

And I would expect Grafana to discover or somehow communicate that this issue in the UI.

### Did this work before?

no

### How do we reproduce it?

1. Set up Prometheus Alertmanager in HA mode
2. Set up Prometheus Alertmanager as default destination of all alerts
3. Create more than one alert that is firing in Grafana
4. Retrieve status of alerts from the different Alertmanager instances and observe the differences

### Environment (with versions)?

Grafana: v10.2.2
OS: Linux/Kubernetes/GKE 
Browser: Safari

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus Alert manager

edit: improved language and explanation

**Comment by clarifai-fmarceau** [comment]
I'm having the same issue! @tonypowa have you had a chance to reproduce this ?

**Comment by armandgrillet** [comment]
Grafana does not multiplex, neither Prometheus. The solution is to create 3 datasources, one for each Prometheus Alertmanager, and enable "Receive Grafana alerts" on all of them. Then send the alerts to external Alertmanager in the admin page, but you're already doing that.

**Comment by olvesh** [comment]
Well, that is a bit simplistic solution I would say. Prometheus utilises its service discovery capabilities in order to expand the list of alertmanagers. 
It would be helpful to have some support for the same in Grafana. 

Multiplexing is perhaps the wrong wording, but some help in achieving HA setup in Grafana for external Alertmanagers would be nice.

As far as I remember, there is not a way to forward Grafana alerts to several Alertmanagers?

**Comment by olvesh** [comment]
@armandgrillet  - thanks for the clarification, it worked 👍 
Some documentation around this issue would be preferable though, it is easy to stumble upon this problem and hard to understand what is happening.

**Comment by clarifai-fmarceau** [comment]
It worked for me too but indeed some doc on that would be helpful..!
