### ISSUE TITLE
[Bug] Table fails to parse JSON

### ISSUE THREAD

**Issue by arohner** [grafana/grafana#7983]
Read before posting: 

I'm using the eventer binary from kubernetes/heapster to monitor my kube cluster. Eventer is writing to InfluxDB. When attempting to create a Table in Grafana, and parsing the JSON, the event data is not parsed into a JSON object and I get the following stacktrace in Chrome Dev Tools:

```
TypeError: Cannot read property 'length' of undefined
    at Object.transform (boot.5ee7468a.js:21)
    at f.c [as transformDataToTable] (boot.5ee7468a.js:21)
    at b.render (boot.5ee7468a.js:21)
    at boot.5ee7468a.js:46
    at o.$broadcast (boot.5ee7468a.js:42)
    at boot.5ee7468a.js:11
    at boot.5ee7468a.js:43
    at f (boot.5ee7468a.js:41)
    at boot.5ee7468a.js:41
```

Please include this information:
- What Grafana version are you using?
`Version 4.2.0 (commit: 349f3eb)`
- What datasource are you using?
Influx 1.2

- What OS are you running grafana on?
  Ubuntu 16.04.2

- What did you do?
create a grafana `Table`. In `Options`, select `Table Transform` -> JSON
- What was the expected result?
The table would show parsed JSON
- What happened instead?
The table showed the raw JSON string, and the above stacktrace

**Comment by torkelo** [comment]
What does you query look like?

InfluxDB data source does not support returning json, you can write a query that returns a table (switch format option to Table in InfluxDB query)

**Comment by arohner** [comment]
> InfluxDB data source does not support returning json

Why is that? 

My data is a JSON event from kubernetes, stored in an influxDB string field. It looks like

```
{
 "metadata": {
  "name": "foo-123",
   ...
 },
 "involvedObject": {
  "kind": "Pod",
  "namespace": "default",
  "name": "foo-123"
 },
 "reason": "Pulled",
 "message": "Container image \"us.gcr.io/foo/bar:72\" already present on machine",
 "source": {
  "component": "kubelet",
  "host": "gke-staging-1-default-pool-a5716439-8993"
 },
 "firstTimestamp": "2017-03-29T20:22:43Z",
 "lastTimestamp": "2017-03-29T21:38:40Z",
 "count": 342,
 "type": "Normal"
}
```

I would like to be able to write a query that extracts nested fields out of the JSON and displays them.

> you can write a query that returns a table 

I already have that selected, I'm not sure what it gets me though. 

While I'm sure there's User Error going on here, the docs and PRs indicate this should be possible, and I'm pretty sure grafana shouldn't be throwing uncaught exceptions in chrome dev tools with no user-visible error.

**Comment by torkelo** [comment]
Json embedded inside an InfluxDB string  field is not supported at this time.
