### ISSUE TITLE
Authentication though auth.generic_oauth first login attempt failed after installing Grafana 10.2.1

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#79836]
### What happened?

Installed grafana docker image 10.2.1 and auth.generic_oauth is enabled.
Logged in via generic oauth, **first login attempt** failed with below error.
![image](https://github.com/grafana/grafana/assets/38758323/ff96b94f-c906-49cb-bb6d-8db10726cac4)

**Grafana logs:**
2023/12/22 08:16:34 logger=oauth.generic_oauth t=2023-12-22T08:16:34.405359586Z level=debug msg="User info result" result="Id: 8484844b-6b72-4217-8b49-00752a7607ad, Name: xxxx, Email: xxxx@xxxx.com, Login: xxxx@xxxx.com, Role: , Groups: []"
2023/12/22 08:16:34 logger=user.sync t=2023-12-22T08:16:34.429161574Z level=error msg="Failed to create user" error="user not found" auth_module=oauth_generic_oauth auth_id=8484844b-6b72-4217-8b49-00752a7607ad
2023/12/22 08:16:34 logger=authn.service t=2023-12-22T08:16:34.429186929Z level=error msg="Failed to run post auth hook" client=auth.client.generic_oauth id= error="[user.sync.internal] unable to create user: user not found"

Once again tried loggen in via generic oauth and it was successful in **second attempt.**
After this issue was not observerd ever.

Attached grafana.ini for reference.
[grafana_ini.txt](https://github.com/grafana/grafana/files/13753934/grafana_ini.txt)

### What did you expect to happen?

login to grafana on first attempt

### Did this work before?

Yes, in 10.0.3

### How do we reproduce it?

1. 
2.
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.1
OS:
Browser:

### Grafana platform?

Docker

**Comment by chalapat** [comment]
@VeenaThimmegowda  After looking into your configuration, Issue is the following:
Maxscale mariadb is used as backend database. Port used for communication is that of ReadWrite Split. With this port grafana will not work. Masteronly port needs to be configured for grafana to work.  After changing the port to Master only then the reported issue is not seen.

This can be closed.

**Comment by VeenaThimmegowda** [comment]
Hi @chalapat ,
Thanks for the help, Issue is fixed.

**Comment by SilverFire** [comment]
In my case it was related to https://github.com/grafana/grafana/issues/70203 and to the disabled email lookup by default.

See https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#extended-authentication-settings
