### ISSUE TITLE
[Feature request]-Ldap group user as grafana Admin

### ISSUE THREAD

**Issue by vishksaj** [grafana/grafana#7985]
Hi Team,

Is it possible to use Ldap group user as a grafana Admin for basic Auth API calls so that we can use Ldap user for "server admin" requests ( create Org/List Org ). If we can use Ldap user as Grafana Admin we can track the user via Centralized AD also.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/2469
