### ISSUE TITLE
Grafana 2.6 RaspberryPi only one value displayed

### ISSUE THREAD

**Issue by mutiger** [grafana/grafana#7986]
Hi there,

I am currently running Grafana 2.6 on my raspberry pi. My data gets transferred to the RaspberryPi via MQTT and is saved in an InfluxDB the following format:  location / source / value. 

I am trying to show multiple metrics per graph but I can only show Metric A OR Metric B but not bot. If I select both metrics, only one is shown (no matter if I activate group by or other values).

I need to add an ";" at the end of the first query in order to make it work - but even then - only one value is displayed.

What do I need to change?

Best Regards,

![2017-03-30-143022_1920x1200_scrot](https://cloud.githubusercontent.com/assets/26058686/24505111/02044c7e-1559-11e7-9bf6-5b2e2db0d1e5.png)

**Comment by torkelo** [comment]
You seem to be using a very old version of Grafana, this looks like a very old issue where InfluxDB changed how multiple queries where sent, fixed more than a year ago.
