### ISSUE TITLE
Alerting: Alarm value unit configuration benchmarking graphic panel

### ISSUE THREAD

**Issue by GitHamburg** [grafana/grafana#79865]
**Why is this needed**:

The current alarm value unit configuration supports very few units, only Humanize, Humanize1024, HumanizeDuration, HumanizePercentage, and HumanizeTimestamp, and the configuration is cumbersome.

The existing panel comes with a powerful unit configuration, which can be classified and searched by unit, clear and rich, covering almost all units used. Unfortunately, Alerting's unit configuration was unable to reuse or associate this advantage.

**What would you like to be added**:

I hope that the unit configuration of Alerting can be more diverse and user-friendly, preferably consistent with the unit configuration in the panel.

Unit Configuration in Alerting:
Humanize, Humanize1024, HumanizeDuration, HumanizePercentage, and HumanizeTimestamp

Unit configuration in the panel:
![grafana-panel-unit](https://github.com/grafana/grafana/assets/16780183/115e3988-02a0-43a3-9513-a2fb5343faad)

It is obvious that the unit configuration in the panel is more diverse, clearly classified, and easy to use.

**Who is this feature for?**

Users with unit conversion needs.

**Comment by GitHamburg** [comment]
@KaplanSarah The current method of specifying units in alerts allows for flexibility by specifying them in the content. However, it can be cumbersome to use and lacks richness.
```
....xxxx... {{ humanize1024  (index $values "B").Value }}B/s ...xxx....
```

It would be beneficial to have a unit configuration option in interfaces such as query and reduce, similar to the DashBoard Panel, where units can be configured.Like this:
![image](https://github.com/grafana/grafana/assets/16780183/c1fccb49-aa76-4840-ab9f-59062bbf321e)

**Comment by KaplanSarah** [comment]
This is not a priority for the team at the moment.  If more customers come forward then we can re-open the request and prioritize it against our current backlog.
