### ISSUE TITLE
Alerting: Performance issues with Alert list controls

### ISSUE THREAD

**Issue by GitHamburg** [grafana/grafana#79867]
### What happened?

When I open the Alert list control and check the browser network, I find that I will access "/app/rules/grafana/app/v1/rules? Subtype=Cortex". This link will access all the alarm rule content, currently 18.51KB, but if you create many rules and load all the rules, there will be performance issues.

### What did you expect to happen?

Can the Alert list control avoid loading all alarm rules?

### Did this work before?

I'm not sure, I haven't used the Alert list control before.

### How do we reproduce it?

1. Create a dashboard and add an Alert list control;
2. Open the dashboard, browser - network, and view "/app/rules/grafana/app/v1/rules? Subtype=Cortex" resource.

### Environment (with versions)?

Grafana:10.3
OS:macos
Browser:safari

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
hi @GitHamburg 

thank you for creating this issue

I will forward your concern to the Alerting team

In the meantime:

- Do you have any metrics or profiling information that illustrate the performance bottleneck? For example, browser performance timelines, server resource usage at the time of issue, etc.

- Approximately how many rules are you currently managing within your system?

**Comment by GitHamburg** [comment]
Thank you for your attention and response. 

Currently, there are 244 rules, and the request time for all rules is 287.6 milliseconds. There are no significant performance issues at the moment. 
![grafana-2024-01-25_09-40-01](https://github.com/grafana/grafana/assets/16780183/bbda2cdd-6f38-4be1-941e-040355e913a9)

Would it be possible to load only the rules related to alerts? This would be more reasonable.

**Comment by armandgrillet** [comment]
The alert list panel does get all of the rules to then match them up to see the state of a particular rule and be able to go to its detail view. We have no control on making that payload smaller as we first have to find all the rules in a particular state and there is no filter for that in the API thus it has to be done in the frontend.
