### ISSUE TITLE
[Bug] Grafana alerting to slack not displaying pictures

### ISSUE THREAD

**Issue by mnuic** [grafana/grafana#7987]
I am running docker image Grafana v4.2.0 (commit: 349f3eb)

Set up s3 bucket for picture upload for Slack:

```
provider = s3
bucket_url = http://grafanaXYZ.s3-eu-central-1.amazonaws.com
access_key = XXXXXX
secret_key = YYYYYYY
``` 

From the log I can see that files are uploaded to s3 bucket:
```
t=2017-03-30T13:08:25+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=3 newState=alerting prev state=ok
t=2017-03-30T13:08:25+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=3 sent count=1
t=2017-03-30T13:08:25+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/test?&panelId=3"
t=2017-03-30T13:08:26+0000 lvl=info msg=uploaded logger=alerting.notifier url=https://grafana.s3.amazonaws.com/xxyyyzzz.png
t=2017-03-30T13:08:26+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=4 isDefault=false
t=2017-03-30T13:08:26+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=3 notification=#slack-test
```
And can confirm that files are in s3 bucket.

The problem is that pictures are not shown in slack notification message.

Files (pictures) are publicly accessible by HTTP or HTTPS, but when I copy HTTPS link in slack the picture is not shown, only HTTP is working.

I think that slack can not show https link for s3 bucket, but I can't confirm that. Or I didn't set someting right.

This is my bucket policy:
```
{
    "Version": "2017-04-30",
    "Id": "PolicyNameTest",
    "Statement": [
        {
            "Sid": "PublicAllow",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::BUCKET_NAME/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "public-read"
                }
            }
        }
    ]
}
```

Can someone help?

**Comment by torkelo** [comment]
strange, not sure why slack would not like the https s3 url. Not sure what Grafana can about it. We have no similar reports, maybe everyone use http but not sure.

**Comment by mnuic** [comment]
The url that grafana is sending picture is HTTPS:
```
t=2017-03-31T11:26:16+0000 lvl=info msg=uploaded logger=alerting.notifier url=**https**://xxxyyyzzz.s3.amazonaws.com/xxxxx.png
````

and the s3 bucket url defined in default.ini file is:
```
bucket_url = **http**://xxxyyyzzz.s3.amazonaws.com
````

how is possible that HTTP -> HTTPS?

**Comment by jondoe1337** [comment]
@mnuic did you contact slack or found a workaorund?

**Comment by mnuic** [comment]
@jondoe1337 don't use any bucket policy on s3 (leave it empty) and under the Access Control List -> Manage public permissions -> only check "group Everyone" -> Object and Access permissions to Read

And the bucket is located in US East.

**Comment by jondoe1337** [comment]
This helped. In addition to that, my fault was that I had additional dots in my bucket name which lead to an invalid https certificate, which is filtered in slack. 

Thanks @mnuic
