### ISSUE TITLE
Alerting: Silence is not matching alerts in the 'normal' state

### ISSUE THREAD

**Issue by SergeiCherevko** [grafana/grafana#79886]
### What happened?

Silence matcher in UI doesn't show alerts in normal (green) state

### What did you expect to happen?

I expect to see all alerts, for example i have 1120 targets matched with alert TargetUnreacheable, but only one of them in firing state when i trying to match by labels

### Did this work before?

I don't have a proof, but i remember earlier (in version 8-9) when i did silence i see all alerts and i can able to silence alerts in any states (firing, supressed, normal) for some instances

### How do we reproduce it?

1. Go to [Alerting] - [Silences] - Add silence
2. Add matcher (alertname = TargetUnreachable)
3. You will see only supressed and firing alerts

### Is the bug inside a dashboard panel?

-

### Environment (with versions)?

Grafana: v10.1.5 849c612fcb
OS: MacOS Sonoma 14.1.1
Browser: Google Chrome Version 120.0.6099.109 (Official Build) (arm64)

### Grafana platform?

Kubernetes

**Comment by SergeiCherevko** [comment]
<img width="1073" alt="image" src="https://github.com/grafana/grafana/assets/17637953/92b04b49-582f-4aaa-9a05-1b11d7338f3a">
<img width="353" alt="image" src="https://github.com/grafana/grafana/assets/17637953/e87bd810-0bb9-4fbd-b03d-cff32c6ca04a">

I suppose i should to see all 1118 alerts

**Comment by tonypowa** [comment]
Hi @SergeiCherevko 

Thank you for reporting the issue. 

I could not reproduce it, but perhaps it would be good to learn from the Alerting team if there are any known limits around how many matched alerts will display in the UI under a particular Silence.

In the meantime, 

You've left the 'Datasource(s)?' field with No response. Could you specify which datasource(s) you're using for your alerts? This will help us understand if the issue relates to a specific datasource or if it's more general.

**Comment by SergeiCherevko** [comment]
Hello! We use "Victoria metrics" datasource for all alerts. This is was your question, correct? Sorry im not sure understand what i shoud to show you, if you need more information, please ask me

I give to you another example
We have alert, which is firing when certificate on host expiring after 30 days (name of alert - CertificateExpireAfter30days)
For example i want to supress this alert before when its will be firing, just to prevent annoying my team

<img width="1631" alt="image" src="https://github.com/grafana/grafana/assets/17637953/ad5d6404-31f4-45d5-b9a2-71e01a0c2356">


So i go to silences and try to create silence (when this alert in normal green state)



<img width="797" alt="image" src="https://github.com/grafana/grafana/assets/17637953/90aae2fd-bc6c-46a7-9d1f-973e3debddd0">

So i see matching only when alert already firing. If i want to create silence on not yet firing alert, i see nothing. Very strange behaviour, I know this silence will be work when i create them and when alert will be firing - it will be silenced

But what if i make mistake in labels but i can't understand because in all cases i don't see matching (even when labels its correct)

**Comment by tonypowa** [comment]
>We use "Victoria metrics" datasource for all alerts. 

This is what I was asking about. Thank you!

>If i want to create silence on not yet firing alert, i see nothing. 

Good question. I am not sure that silences are supposed to match alerts, when the alerts are not firing yet. 
Either, way once the team responds to your questions, we will update [the docs](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-silence/)

**Comment by armandgrillet** [comment]
This is expected behavior, the preview only shows you the alerts it would silence right now.
