### ISSUE TITLE
Dashboard: Loki metrics are not displaying fully

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#79892]
### What happened?

If you try to use a Loki datasource with metrics queries and then select a large time frame. It does not display all the data. First raised [on slack](https://raintank-corp.slack.com/archives/C036J5B39/p1703170552954199).
<img width="1511" alt="Screenshot 2023-12-28 at 15 15 55" src="https://github.com/grafana/grafana/assets/100691367/1b770e09-9d0b-4f88-8d51-e56cd9d958ac">

If you try to edit one of these panels, the data displays correctly:
<img width="1512" alt="Screenshot 2023-12-28 at 15 19 03" src="https://github.com/grafana/grafana/assets/100691367/86a9648a-1145-461a-92f7-d2ae160e9c80">

This seems to be because the Loki metrics queries are split, so the panel does not update with every updated query, using only the one with the latest data.

<img width="1144" alt="Screenshot 2023-12-28 at 15 17 25" src="https://github.com/grafana/grafana/assets/100691367/640466c0-a1e4-4b91-93de-9884c26b2907">

### What did you expect to happen?

All of the chart to be displayed at once.

### Did this work before?

Not sure

### How do we reproduce it?

1. You can see it in this [dashboard](https://play.grafana.org/d/d47f296b-438b-4966-8f75-70acc57bc7e8/dashboard-log-queries-not-loading-all-data?orgId=1)

### Environment (with versions)?

Grafana: 10.3.0
OS: Mac
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

Loki

**Comment by axelavargas** [comment]
Hey @JoaoSilvaGrafana 👋🏾 , thanks for helping report this issue 🏅 , I was able to reproduce it and figure out it was related to streaming panels. The good news is this was fixed by this PR https://github.com/grafana/grafana/pull/79860
