### ISSUE TITLE
I can't  pan the Node Graph using Firefox

### ISSUE THREAD

**Issue by starsliao** [grafana/grafana#79904]
### What happened?

I can't  pan the Node Graph using Firefox, But chrome can

### What did you expect to happen?

I can pan the view by clicking outside any node or edge and dragging your mouse.

### Did this work before?

1

### How do we reproduce it?

1

### Environment (with versions)?

Grafana: 10.2.2
OS: win10
Browser: firefox 122.0b3

### Grafana platform?

None

**Comment by aocenas** [comment]
Should be fixed by https://github.com/grafana/grafana/pull/79508
