### ISSUE TITLE
[documentation]: Possibly incorrect example for specific API request

### ISSUE THREAD

**Issue by aureq** [grafana/grafana#79919]
### What happened?

Hi,

I was reading this [documentation](https://grafana.com/docs/grafana/latest/developers/http_api/dashboard_public/#get-public-dashboard-by-dashboard-uid) on how to *GET* a Public Dashboard. The URI shown is of `GET /api/dashboards/uid/:uid/public-dashboards/`, however the example proposed uses a different URI `GET /api/dashboards/uid/xCpsVuc4z`.

Here's the link to the [original source file](https://github.com/grafana/grafana/blob/v10.2.3/docs/sources/developers/http_api/dashboard_public.md?plain=1#L193-L212).

### What did you expect to happen?

In the *GET* request, I was expecting something like `GET /api/dashboards/uid/xCpsVuc4z/public-dashboards/`.

### Did this work before?

Likely not, the change was first introduced in a4c8f04565495073f3fb555b8c3419b2e8d81b69

### How do we reproduce it?

n/a

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: v10.2.3
OS: n/a
Browser: n/a

### Grafana platform?

Kubernetes

### Datasource(s)?

n/a

**Comment by usmangt** [comment]
Hi @aureq,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by lucychen-grafana** [comment]
Changes have been made and will be available with version 10.4
