### ISSUE TITLE
[Feature request] batch CloudWatch API call support in backend

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7991]
Replace current templating variable expanding feature, https://github.com/grafana/grafana/pull/5003 .

Expanding GetMetricStatistics API, and support multiple Dimension value in one Dimension entry. http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html

Current request payload which Grafana frontend send.

```
{
"region" : "us-east-1",
"action" : "GetMetricStatistics",
"parameters" : {
"namespace" : "AWS/EC2",
"metricName" : "CPUUtilization",
"dimensions" : [
{
"Name" : "InstanceId",
"Value" : "i-1234abce"
}
],
"statistics" : [
"Average"
],
"extendedStatistics" : [],
"startTime" : 1490871009,
"endTime" : 1490892609,
"period" : 300
}
}
```

Change this like following.
The backend call GetMetricStatistics multiple times.

```
{
"region" : "us-east-1",
"action" : "GetMetricStatistics",
"parameters" : {
"namespace" : "AWS/EC2",
"metricName" : "CPUUtilization",
"dimensions" : [
{
"Name" : "InstanceId",
"Value" : ["i-1234abce", "i-2345abce"]
}
],
"statistics" : [
"Average"
],
"extendedStatistics" : [],
"startTime" : 1490871009,
"endTime" : 1490892609,
"period" : 300
}
}
```

Or mark some dimension entry which include multi value, and support regex match support.

I'm not sure what is the best way.
Expanding API is hacky too, but if it is better than expanding template variable, it is worth to consider.
https://github.com/grafana/grafana/pull/7707#issuecomment-285000152

**Comment by torkelo** [comment]
So the Cloudwatch api support arrays for the dimension values?

**Comment by mtanda** [comment]
CloudWatch API doesn't support it.
The idea is, Grafana backend receive array of the dimension values, and call CloudWatch API for each dimension values, and merge response.

We need to change CloudWatch query editor too.

> Or mark some dimension entry which include multi value, and support regex match support.

If we take this idea, I'll change the query editor like following.
![cw_query_editor](https://cloud.githubusercontent.com/assets/224552/24598727/f1b056e2-1887-11e7-904e-4a9e249b175b.png)

To support Alert feature (https://github.com/grafana/grafana/issues/5858, https://github.com/grafana/grafana/issues/6557), we need to move tricky code from frontend to backend.
Otherwise, we need to maintain both tricky code...

**Comment by torkelo** [comment]
if cloudwatch api supports =~ then I am for it, if not then we have to wait for cloudwatch to improve their API

**Comment by sunker** [comment]
Implemented now using wildcards and search expressions. See #20058
