### ISSUE TITLE
Grafana dashboard not acessible. Wrong login/password

### ISSUE THREAD

**Issue by vedmed85** [grafana/grafana#79924]
### What happened?

After installation via helm in kubernatis and creating service I can't login with password admin/admin. No clear manual how to access 

### What did you expect to happen?

I expect to login 

### Did this work before?

with grafana inside kubernatis I didnt work

### How do we reproduce it?

1.install grafana in Lens via helm
2. create service 
3. via browser I cant login

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @vedmed85,

Thanks for opening this issue.

This is more of a general question related to Grafana installation via helm and the usage of the command line.

I will try to help you by writing the instructions but in future please use our Community forums where you can get help from our community members.

1- go to your Kubernetes server via SSH and run the command:
`helm get notes your-grafana-installation name`

incase if you have installed grafana other than the default namespace then add `-n your-name-space-name` at the end of the above command

2- the above command will give you text-based information on how to log in via admin and how to expose the service

```
Get your 'admin' user password by running:

   kubectl get secret -n your-name-space-name your-grafana-installation name -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
```
Again you can remove the -n your-name-space-name from the above command if have installed it directly in the default namespace

3- After running the above command you will get a decoded string which is actually the grafana admin password that you can use to login.
