### ISSUE TITLE
"Database table is locked" error

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#7992]
@woodsaj and I ran into this issue while testing some new worldPing updates. Specifically, the latest version of wP will automatically update your datasources to the latest settings for the app.

The requests were being sent concurrently and we saw:
```
EROR[03-30|13:50:29] Failed to update datasource              logger=context userId=1 orgId=1 uname=admin error="database table is locked"
EROR[03-30|13:50:29] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/1 status=500 remote_addr=[::1] time_ms=8ns size=41
```

Rather than making changes in the app itself, @woodsaj noted that this could happen any time concurrent requests needed to modify the same table - Ie saving 2 dashboards at the same time. 

Is this something that should be addressed in Grafana?

**Comment by torkelo** [comment]
any tips for how to replicate this?

**Comment by YouZhengChuan** [comment]
I also encountered this error, occurs when the alerting state changes.
I am trying to solve this problem by adding a retry in the source code.

> INFO[04-24|10:49:20] New state change                         logger=alerting.resultHandler alertId=3 newState=ok
> EROR[04-24|10:49:20] Failed to save annotation for new alert state logger=alerting.resultHandler error="database table is locked"
> INFO[04-24|10:55:20] New state change                         logger=alerting.resultHandler alertId=3 newState=ok
> EROR[04-24|10:55:20] Failed to save annotation for new alert state logger=alerting.resultHandler error="database table is locked"

**Comment by daniellee** [comment]
@youzhengchuan if you are experiencing this problem a lot, we would recommend switching the Grafana database from SQLite to MySQL or Postgres. SQLite is not built to handle multiple concurrent writes.

**Comment by daniellee** [comment]
This change got rolled back and is not included in the 4.3.0 release.

**Comment by shubhamod1** [comment]
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.

**Comment by daniellee** [comment]
@nageshvs can you open a new issue and add some more details - anything that can help us troubleshoot this issue. Could you post more from your Grafana logs so that we can see more of the context.

**Comment by llech** [comment]
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2019-03-04T08:03:58+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2019-03-04T08:13:35+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import

I'm the only user that works with Grafana. It works terribly unreliable. Sometimes I have to click 'save' 4 or 5 times, the last click wins , all previous are hanging forever...

Can it be the issue with persistent volume on NFS? 

I'm using image grafana/grafana:5.1.0 from Rancher helm charts, with default DB configuration.

**Comment by remram44** [comment]
Running into this on 9.2.4:

> `logger=datasources t=2022-11-11T18:50:08.133198168Z level=error msg="Failed getting data source" err="database is locked" uid=x297kRDVz id=0 name= orgId=1`
> `logger=ngalert rule_uid=rSly4WvVk org_id=1 version=20 attempt=0 now=2022-11-11T18:50:00Z t=2022-11-11T18:50:08.133278411Z level=error msg="failed to evaluate alert rule" results="[{Instance: State:Error Error:failed to execute conditions: failed to build query 'A': database is locked EvaluatedAt:2022-11-11 18:50:00 +0000 UTC EvaluationDuration:8.133271318s EvaluationString: Values:map[]}]" duration=5.006064637s`

Every once in a while Grafana will fire random alerts because of this internal error. At times it will also randomly log me out.

It looks like other parts of the code have a retry mechanism if the database is locked:

https://github.com/grafana/grafana/blob/8949e574e6288671343b80991479e2e2b9adfc88/pkg/services/sqlstore/session.go#L83

But getting data source doesn't use it:

https://github.com/grafana/grafana/blob/96cdf77995c6fcd47256e19dccece145ebad59aa/pkg/services/datasources/service/store.go#L59-L63
