### ISSUE TITLE
Home DashBoard does not display Tag

### ISSUE THREAD

**Issue by iliugh** [grafana/grafana#7995]
- What Grafana version are you using?
   Grafana 3.1.1
- What datasource are you using?
   Influxdb
- What OS are you running grafana on?
   CentOS
- What did you do?
   I edit the public/dashboards/home.json,and change the "tags": [] to "tags": ["Test"].However,when I refresh the browser,the tag content is not displayed on the home dashboard bar.
![tag](https://cloud.githubusercontent.com/assets/5077845/24533648/abb367da-15fb-11e7-87f5-22901f207fcf.png)
- What was the expected result?
   Let the tag contents display on the home dashboard bar.

**Comment by torkelo** [comment]
Home dashboard is a special link in the search to `/` it can go to what ever home dashboard you have configured (you can change home dashboard in org & profile preferences)
