### ISSUE TITLE
[BUG]login.OAuthLogin(state mismatch)

### ISSUE THREAD

**Issue by geekgonecrazy** [grafana/grafana#7996]
Please include this information:
- What Grafana version are you using? 4.2.0
- What datasource are you using? influxdb
- What OS are you running grafana on? Linux - Docker k8s

Added generic oauth.  I struggled with this error a good bit, then turned on `enforce_domain` that solved it. But then I enabled ssl and it started happening again.

`https://oauth-provider/oauth/authorize?access_type=online&client_id=<client id>&redirect_uri=https%3A%2F%2F<grafana address>%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=OHu36tbGrDJvwanu2Hs3z3%2FgzJpECE%2BYq9j8vlf9vCc%3D`

The URL it redirects back to:
`https://<grafana address>/login/generic_oauth?code=cc536d98d27750394a87ab9d057016e636a8ac31&state=OHu36tbGrDJvwanu2Hs3z3/gzJpECE+Yq9j8vlf9vCc=`

It seems to happen very randomly.  One time it happens and the next it doesn't.

The state definitely matches.

**Comment by torkelo** [comment]
How many grafana servers are you running and what session store are you using?

**Comment by geekgonecrazy** [comment]
@torkelo no other instances running.  Default session store.  Which I assume is sqlite3.  I don't have any volumes mounted to persist right now, so for sure nothing else touching any of its files

**Comment by torkelo** [comment]
is the url for grafana the exact same when you start oauth login process as when you come back from oauth service? The domain and protocol needs to match for the session cookie to be the same

**Comment by geekgonecrazy** [comment]
@torkelo I have `enforce_domain` set and domain matches.  I have protocol set to `https` and nothing listening at `http` so if it were to land there there would be nothing. 

Starts on page: https://monitor.mydomain.com/login
And ends on: https://monitor.mydomain.com/login/generic_oauth?code=cc536d98d27750394a87ab9d057016e636a8ac31&state=OHu36tbGrDJvwanu2Hs3z3/gzJpECE+Yq9j8vlf9vCc=

Is there specific cookie content I should look for? Or some way to verify the contents?

**Comment by torkelo** [comment]
yes, grafana_sess cookie, is it the same in the initial login request (to grafana) as when you come back?

**Comment by geekgonecrazy** [comment]
@torkelo I went to login page, checked the grafana_sess cookie the value was: `b7ea10faae53a563` I clicked the generic_oauth.  It came back with the state error and the cookie contains: `b7ea10faae53a563`

So it seems to cookie value has not changed.

**Comment by torkelo** [comment]
not sure what could be the issue, somehow the session store is not working. Try switching session store to mysql or postgres

**Comment by geekgonecrazy** [comment]
@torkelo i'll give that a shot. My guess is it'll work with those session stores.  But will report back as soon as I have a chance to confirm

**Comment by jostyee** [comment]
@torkelo We've met the same issue, even storing sessions in MySQL doesn't help.

**Comment by haizaar** [comment]
For it was an issue of typing grafana URL with the ending dot, e.g. `monitoring.example.com.` *<- trailing dot*.

Took some time to spot it.

**Comment by geekgonecrazy** [comment]
I wish that was mine.  But mine is random.  One login attempt it works, another we hit this :(  

I've got grafana deployed stateless on kubernetes with config and dashboards all loaded in, so trying to avoid having to deplyo mysql or something just for login :(

**Comment by haizaar** [comment]
I know you said before that you are running only a single instance of Grafana, but my guts tell me that your problem is that request lands in a wrong place from time to time... My 2c.

**Comment by geekgonecrazy** [comment]
@haizaar agreed that's what I suspected too.  But definitely only single instance running.

**Comment by neuquino** [comment]
I'm having exactly the same error, but I'm running a cluster with 2 instances and a DB for session store. Is there a way to make Generic OAuth work in an HA environment?

**Comment by ynoser** [comment]
I have same error.

I'm running 1 server.
Not always, but sometimes(around 2 error for 5 tries?).

I could see "... &state=eQKriqmsbOtnK6t%2Bg%2FnnxdgCF8F%2FT57jnnvCOqlZrFI%3D" from oauth2 login page but I could see "... &state=eQKriqmsbOtnK6t+g/nnxdgCF8F/T57jnnvCOqlZrFI=" when I redirected to error page of Grafana.

At the moment, I could signin to Grafana due to change "state=eQKriqmsbOtnK6t+g/nnxdgCF8F/T57jnnvCOqlZrFI=" to "state=eQKriqmsbOtnK6t%2Bg%2FnnxdgCF8F%2FT57jnnvCOqlZrFI%3D" from url bar of browser.(in my case, it was Chrome)

According to the phenomenon, it is clear that there is an issue related to URL encoding of state value.

**Comment by geekgonecrazy** [comment]
Yup this looks very consistent with what i'm seeing.

**Comment by buroa** [comment]
I'm also seeing this issue, even with the latest version v5.3.1 (commit: 08c7908). We run an active-active Grafana deployment, but I went as far as pointing all of our regions to the same MySQL database, and the session still fails with this error code. The URL is exactly the same across all of our instances too.

What is going on here?

**Comment by cauwulixuan** [comment]
Any progress on this? Also meet this issue. In my case, I ran a 2 grafana instances for HA according to the doc [grafana ha setup](https://grafana.com/docs/tutorials/ha_setup/) , and set a DB for session store. Is there a way to make Generic OAuth work in an HA environment?

**Comment by marefr** [comment]
@buroa I think you finally solved this by changing some replication settings, correct?

**Comment by andreicucu** [comment]
I am also having the same issue. 

- running one instance of grafana 6.2.0 on centOS droplet. 
- protocol: https with no reverse proxy in front
- main database is postgres
- remote cache settings is default

Relevant settings below:

```
enforce_domain = true
cookie_secure = true
cookie_samesite = none

[auth.generic_oauth]
enabled = true
name = GenericOauth
allow_sign_up = true
client_id = secret
client_secret = secret
scopes = openid email
auth_url = https://sso.provider.com/provider/oidc/endpoint/oidcidp/authorize
token_url = https://sso.provider..com/isam/provider/endpoint/oidcidp/token
api_url =
send_client_credentials_via_post = true
```

Log entry for login attempt:

```
t=2019-07-05T07:22:51+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.10.10.10 time_ms=0 size=29 referer=
t=2019-07-05T07:22:54+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.10.10.10 time_ms=0 size=336 referer=https://mywebsite.cf:3000/login
t=2019-07-05T07:22:57+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2019-07-05T07:23:07+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2019-07-05T07:23:13+0000 lvl=info msg="state check" logger=oauth queryState=7d4715445d76ac210d3ead75ec8b3ea2049047f51637f41553241230675e2470 cookieState=1856c8ee017fcef457d1b4bcd457d6f316ca94a21e69891a29d46cfcd271e7cf
t=2019-07-05T07:23:13+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=10.10.10.10 time_ms=0 size=1737 referer="https://sso.provider.com/provider/oidc/endpoint/oidcidp/authorize?access_type=online&client_id=ZjE3ZGQ5ZGMtYmE0ZS00&redirect_uri=https://mywebsite.cf:3000/login/generic_oauth&response_type=code&scope=openid%20email&state=1chnbcpOD4JUNefvUsSQxPIn9xRnMEXD680b0IjBXNs="
t=2019-07-05T07:23:14+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/public/img/fav32.png status=404 remote_addr=10.10.10.10 time_ms=249 size=22825 referer=
t=2019-07-05T07:23:14+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=404 remote_addr=10.10.10.10 time_ms=250 size=22825 referer=
```

In the log entry the cookieState and the queryState are different but i cannot figure out why that is.

The 

I've been wrapping my head around this for a week now with no luck.

**Comment by torkelo** [comment]
closing this as we have remade the ways  state is stored (no longer in session but in a cookie)

but we still have related issue in https://github.com/grafana/grafana/issues/17978
