### ISSUE TITLE
[Bug] Grafana not showing all series with different time frames (InfluxDB Datasource)

### ISSUE THREAD

**Issue by tardoe** [grafana/grafana#7997]
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Grafana Versions: 4.1.2 & 4.2.0
InfluxDB Versions: 1.2.1
Ubuntu Xenial 16.04 LTS

We're collecting interface statistics (one stack using Telegraf, another using snmpcollector) and we're noticing that when the time range changes, the number of series displayed by Grafana changes.

### Query:
![image](https://cloud.githubusercontent.com/assets/5331531/24535164/21ee70e4-161e-11e7-8c22-27c470a71e27.png)

We expect that all interfaces be graphed for the time period as shown. All interfaces have data in influx for the periods graphed below. Instead, we see less series shown on the Grafana graphs and in the legend. This appears to be intermittent as sometimes all interfaces will be displayed and sometimes they are not. Usually it's the last few interfaces that are removed, but not always. There are no errors in the Chrome Developer tools console and I can confirm that doing the same queries via the InfluxDB command line always show series for each interface.

### Graphs:
Last 1 Hour
![image](https://cloud.githubusercontent.com/assets/5331531/24535068/95a043e2-161d-11e7-9fb0-b0159855d679.png)

Last 3 Hours
![image](https://cloud.githubusercontent.com/assets/5331531/24535078/a3fa980c-161d-11e7-9b64-a7fe00632ba2.png)

Last 6 Hours
![image](https://cloud.githubusercontent.com/assets/5331531/24535081/a652bf12-161d-11e7-8ef2-455dac93c2fa.png)

Last 24 Hours
![image](https://cloud.githubusercontent.com/assets/5331531/24535083/a8748690-161d-11e7-9413-26a6a4a124c6.png)

**Comment by torkelo** [comment]
This is due to InfluxDB not returning all series due to an option named max-row-limit , this option was by mistake I think changed in InfluxDB 1.2 (they are fixing in next releases).

For further reading on this issue:
https://github.com/grafana/grafana/issues/7380
