### ISSUE TITLE
Alert/Notification support for custom datasource

### ISSUE THREAD

**Issue by vganjare** [grafana/grafana#7998]
Hi,

I have created a new datasource for MongoDB (still work in progress). I want to add support for the Alerts and Notification for this datasource. 

How can I achieve this? Is there any documentation or example which can be used to add this support?

Thanks,
Vishal

**Comment by torkelo** [comment]
currently there is no way for external plugins to support alerting (or add new alert notification channel types). 

But we hope to support this some the future (maybe this autumn) via backend plugins:
https://github.com/grafana/grafana/issues/6841
