### ISSUE TITLE
grafana alerting Groups: not possible to search by label.

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/grafana#79987]
### What happened?

I tried to filter alerts on grafana alerting under groups. like the info button states, I assume I'm able to search for alerts with a specific label.
![image](https://github.com/grafana/grafana/assets/109516706/421ba6a1-9c72-418d-ad53-d33827390b4d)
strangly enough this does not do anything. I'm using an alertmanager instance.

### What did you expect to happen?

I excpect to be able to search on a certain label.

### Did this work before?

never tested it before.

### How do we reproduce it?

1. go to grafana
2. add an alertmanager with alerts
3. try to search for alerts with a specific label.

### Environment (with versions)?

Grafana: 10.2.2
OS: windows server 2022
Browser: google chrome 118

### Grafana platform?

Kubernetes

### Datasource(s)?

alertmanager

**Comment by tonypowa** [comment]
thank you for reporting this problem

can you share an example of what you are entering in the "search by label" search bar?

example of a valid search of a label:
`label:yourAlertLabel=value`

**Comment by ToonTijtgat2** [comment]
Hi, I tried like everything.
label:omnitracker=xxxx
{severity="critical"}
{severity=critical}
severity=critical
severity="critical"
with : instead of =
it does not seem to affect when filling something in.

**Comment by tonypowa** [comment]
Team: Another user is reporting the same issue [here](https://github.com/grafana/grafana/issues/80233)

**Comment by karaktaka** [comment]
We've got the same problem. Currently using Grafana v10.3.1.

**Comment by armandgrillet** [comment]
This has been fixed in Grafana v10.4 which will be released in the next weeks: https://github.com/grafana/grafana/pull/80358
