### ISSUE TITLE
Review command palette UI and behavior

### ISSUE THREAD

**Issue by amy-super** [grafana/grafana#79988]

**Comment by amy-super** [comment]
In the future, we want to support "search for anything" in Grafana. The most logical place for this is in the command palette, but we need to make sure results are presented in a usable way - especially if a search term returns many **types** of results (dashboards, actions, extension points). 

This issue is a placeholder for me to dive in and imagine what a much larger scope of search may look like. @zsofiakm fyi.

**Comment by yaelleC** [comment]
Closing as command palette is part of our product discovery this Q
