### ISSUE TITLE
alert-rules: view in explore forward does not work for 

### ISSUE THREAD

**Issue by bunert** [grafana/grafana#79995]
### What happened?

Seems like the `View in Explorer` forwarding when checking an alert rule is broken for non-default data sources. If you check the forwarded explorer page, always the default data source is selected. The same behavior happens for the Loki data source. 

### What did you expect to happen?

I expect the right data source to be selected with the corresponding query.

### Did this work before?

Not sure.

### How do we reproduce it?

1. Configure non-default Google Cloud Monitoring data source.
2. Create an alert rule with a simple query on the newly added data source.
3. Check the `View in Explorer` forward button. 

### Environment (with versions)?

Grafana: v10.0.3
OS: Ubuntu 22.04
Browser: Google Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring, Loki

**Comment by tonypowa** [comment]
hi @bunert 

could you add a screenshot or a short video recording displaying the issue could be very helpful for us to pinpoint the UI elements in question.

Thank you

**Comment by bunert** [comment]
Hi @tonypowa 

We recently upgraded to Grafana v10.2.3 and the issue is resolved. I close the issue, thanks!
