### ISSUE TITLE
Show Timezone in graphs

### ISSUE THREAD

**Issue by axos88** [grafana/grafana#800]
Hello!

When working together and sharing graphs with remote offices, it's hard to guess what timezone the sent graphs are in. Are they in UTC? Are they in my timezone? Are they in their timezone?
Things get even harder when forwarding graphs received.

Please add a feature that would display UTC+/-X on the time axis.

**Comment by PaulKuiper** [comment]
+1, can the list with time zones be extened with all time zones (see http://momentjs.com/timezone/).  Some reports need to be made in the local time of the remote offices (so they match up with local logbooks)

**Comment by PaulKuiper** [comment]
Would be great if the timezone could be set per graph. I think this could be added to the "Time Range" tab. A drop down with available timezone names (from moment.js) to choose from. Even nicer would be to also list available template parameter in the drop down. In this way you can use a template parameter to change the timezone of multiple graphs. (our machines live in many different timezone, I now how to change my system clock to get a good local time graph for the local teams).

**Comment by nucleusv** [comment]
+1 set different time zone per each graph

**Comment by torkelo** [comment]
this was implemented (partly) for whole dashboard in 2.6 I think
![image](https://cloud.githubusercontent.com/assets/10999/17077256/9493392e-50c9-11e6-8e9d-c78cb9d81981.png)
