### ISSUE TITLE
Prometheus: feature request to have AlignTimeRange respect query range for larger min steps

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#80005]
**Feature request:** 

Respect the range provided in Grafana and do not round to a multiple of a step. For example, 1w min step/min interval will always round to Thursday, even if a customer wants the week to start on a different day. ([see this escalation for an example of not respecting the query range](https://github.com/grafana/support-escalations/issues/8853))

**Background/Context**
Prometheus rounds the interval range start and end with the function [AlignTimeRange](https://github.com/grafana/grafana/blob/dd77ff6bcde9f363927795ef70769989d7b22181/pkg/tsdb/prometheus/models/query.go#L287-L291). This function aligns query range to step. It rounds start and end down to a multiple of step.

How it behaves currently:

Min interval(min step): 1w
Relative Time(dashboard feature to change range): 1M/M
Time Shift(dashboard feature to shift range): 7d/d
No matter what the range is adjusted for with Relative Time and Time Shift, the query range begins with Thursday.
![Image](https://github.com/grafana/grafana/assets/25674746/50573e91-e41a-4bf4-8aa9-2eafb1b0d2df)

Hacky solution:
Min interval of 1day
Write a query that contains an interval of 1w but filter out all days/select only the starting day of the week.
```
sum by(<label_example>) (increase(<metric>{<label_one>="value"}[1w ])) and on() day_of_week() == <the day of the week you want, i.e. 0,1,...,6>
```

**Possible Long Term Solutions**

There are two proposed options for this that will need more discussion.

**1. We could add a ceiling to the AlignTimeRange rounding function of 1w.**

**Pros:** 
- Customers can select the beginning of the week of a specific day without writing a hacky PromQL query.

**Cons:** 
- There may be unintended consequences for providing a ceiling and not being explicitly about stopping rounding to the step. This will need to be researched. 
- Mimir and Cortex rely on start and end times being step-aligned to cache the results. Turning that off means query results will not be cached. [Mimir docs](https://grafana.com/docs/mimir/next/references/architecture/components/query-frontend/#caching).

**2. We could add an option to turn off rounding in the UI.**

**Pros:** 
- Being clear about how Grafana Prometheus data source calculates the range is good and being clear about allowing users to disable this function gives them more awareness and power over their queries. 

**Cons:** 
- Prometheus UI is very busy and overwhelming as it is. Adding more to the UI will have to add great value and should be requested by a significant amount of our customers.
- Mimir and Cortex rely on start and end times being step-aligned to cache the results. Turning that off means query results will not be cached. [Mimir docs](https://grafana.com/docs/mimir/next/references/architecture/components/query-frontend/#caching).

**3. Invest in tests and docs but do nothing**

PR here for test and docs => https://github.com/grafana/grafana/pull/80165#

**Comment by 56quarters** [comment]
> 2. We could add an option to turn off rounding in the UI.

Note that both Mimir and Cortex rely on start and end times being step-aligned to cache the results. Turning that off means query results will not be cached. [Mimir docs](https://grafana.com/docs/mimir/next/references/architecture/components/query-frontend/#caching).

**Comment by bohandley** [comment]
Thank you @56quarters, adding this to the cons of both suggestions. Adding a ceiling to stop aligning or turning it off entirely, both would mean query results would not be cached. Thank you for the link to the docs too! This would not be positive so we would at least have to provide a warning message if this was implemented.

**Comment by bohandley** [comment]
Closing this issue for the following reasons:

1. #3 ✅ We have updated the docs and the tests to give greater clarity on this Prometheus behavior that Grafana plugin supports.
2. #1 not implemented: Having this feature work with a ceiling would break Prometheus caching.
3. #2 not implemented: We are not adding a new option at this time because the UI is busy and complex currently.
