### ISSUE TITLE
[Bug] Possible Math() Calculation bug

### ISSUE THREAD

**Issue by zmcpherson** [grafana/grafana#8001]
**- What Grafana version are you using?**
Grafana v4.3.0-pre1 (commit: 6e304e6)
**- What datasource are you using?**
INfluxDB
**- What OS are you running grafana on?**
OSX
**- What did you do?**
I'm attempting to use the math feature to add/subtract queries, but even the basic addition subtraction function do not seem to be working 
**- What was the expected result?**
Expecting things like 24 - 2 to equal 22  
**- What happened instead?**
24-2 = -218

I am seeing some weird behavior when trying to use the math function with influx/grafana, I'm curious if it's by design (in which case, how do I do it correctly) or if it's a bug.

So I am trying to do some math functions in a single stat panel - I have 3 queries like so.

![snip20170330_1](https://cloud.githubusercontent.com/assets/14893745/24529165/ffca5966-155e-11e7-8ac9-b71546a45f6e.png)
![snip20170330_3](https://cloud.githubusercontent.com/assets/14893745/24529168/04ff346a-155f-11e7-951e-d5b6ca82144c.png)
![snip20170330_5](https://cloud.githubusercontent.com/assets/14893745/24529171/0710174c-155f-11e7-8c2e-e213818f027f.png)

From what I was reading in the documentation,

`SELECT "A" + "B" From "add"` should return 36 (24+12)
(I just realized I read this on an influx document and might not be true for grafana)

But even weirder is when I do this - 

![snip20170330_6](https://cloud.githubusercontent.com/assets/14893745/24529505/e6a27962-1560-11e7-9e1e-2dbd34957f43.png)

I would expect this to be 34 (24 + 10)

Here is another example -

![snip20170330_7](https://cloud.githubusercontent.com/assets/14893745/24529560/302381bc-1561-11e7-9a2d-9ea036f70d64.png)

The expected result should be 22 (24 - 2) 

A few more examples of the weird math instances -

Here is 24/10 (which works)

![snip20170330_9](https://cloud.githubusercontent.com/assets/14893745/24530072/6c443d78-1564-11e7-96b8-a7d5e119df4f.png)

Here is 24 - 10 (which is a completely different than the first calculation)

![snip20170330_11](https://cloud.githubusercontent.com/assets/14893745/24530085/811ad2c0-1564-11e7-8e55-720c612762c4.png)

Here is 24 - 100 

![snip20170330_12](https://cloud.githubusercontent.com/assets/14893745/24530097/8fed1d9e-1564-11e7-8482-4a579d221b22.png)

And here is 24 +100 

![snip20170330_13](https://cloud.githubusercontent.com/assets/14893745/24530105/98e52e64-1564-11e7-80e5-f33e01720d4d.png)

So is this expected behavior and or what am I doing wrong?

Thank you

**Comment by torkelo** [comment]
Not sure, the queries are executed by InfluxDB so maybe a bug in how it executes math between queries?

Did you look at the response from influxdb? (chrome dev tools network tab)
