### ISSUE TITLE
BUG - Custom metrics namespaces are not available in cloudwatch datasource

### ISSUE THREAD

**Issue by alexmnyc** [grafana/grafana#8002]
Looks like cloudwatch plugin is using a static map for "supported" namespaces in cloudwatch metrics. This is bad by design because Cloudwatch is used for custom metrics storage as well. Please correct https://github.com/grafana/grafana/blob/master/pkg/api/cloudwatch/metrics.go#L31 to either have "Custom" namespace which does a dynamic lookup or add custom namespaces to the root namespace selector. Thanks!

**Comment by torkelo** [comment]
Not aware of an api to look up metrics and metrics namespaces, which I know sux. Have Amazon added apis?

**Comment by alexmnyc** [comment]
Not sure, but perhaps letting user input drive the api call such as" I-KNOW-MY-NAMESPACE.MyMetric.count" would work?

**Comment by torkelo** [comment]
I think that already works. And you can specify your custom metrics in the data source settings

**Comment by torkelo** [comment]
closing this, if you know of cloudwatch api's to get custom metrics list  (and built in metrics) let me know
