### ISSUE TITLE
[Bug] Annotations fail to display

### ISSUE THREAD

**Issue by melanopsis** [grafana/grafana#8003]
- What Grafana version are you using?
4.2

- What datasource are you using?
Influxdb

- What OS are you running grafana on?
Linux

- What did you do?
Enabled annotations

- What was the expected result?
Annotations are displayed 

- What happened instead?
Error message:  "Annotations failed d[a].split is not a function"

Data is properly requested and returned but can't be displayed.

**Comment by torkelo** [comment]
please include your annotation query & settings and the response from InfluxDB (open chrome dev tools network tab)

**Comment by melanopsis** [comment]
These annotations work fine with  v. 4.1.2


GET /query?u=admin&p=admin&db=outage&q=select%20%22duration%22%2C%22workscope%22%2C%22outage_id%22%20from%20outage%20where%20unit_name%20%3D~%20%2F.*client.*%2F%20limit%202&epoch=ms HTTP/1.1
Host: localhost:8086
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Referer: http://localhost:3000/dashboard/db/test?orgId=1&editview=annotations
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,tr;q=0.6

HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Accept-Encoding, Authorization, Content-Length, Content-Type, X-CSRF-Token, X-HTTP-Method-Override
Access-Control-Allow-Methods: DELETE, GET, OPTIONS, POST, PUT
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: Date, X-InfluxDB-Version
Connection: close
Content-Encoding: gzip
Content-Type: application/json
Request-Id: ce6b0154-1659-11e7-8019-000000000000
X-Influxdb-Version: v1.2.2
Date: Fri, 31 Mar 2017 21:34:22 GMT
Transfer-Encoding: chunked

{"results":[{"statement_id":0,"series":[{"name":"outage","columns":["time","duration","workscope","outage_id"],"values":[[1236729600000,0,"workscope1","9752456"],[1247961600000,48,"workscope2","9771250"]]}]}]}

**Comment by torkelo** [comment]
and your annotation settings ? (column/field maps)

**Comment by melanopsis** [comment]
Title --> outage_id
Tags --> duration
Text --> workscope

It seems like switching title <--> tags is getting rid of the error.

**Comment by torkelo** [comment]
Tags needs to be a string or an array of strings
