### ISSUE TITLE
[Grafana 4.1]  Grafana LDAP Integration

### ISSUE THREAD

**Issue by troyygan** [grafana/grafana#8004]
Hi,

Can someone help me with this error that I encountered below. I was able to connect the grafana to AD as seen on the logs of Active directory and grafana logs. Below is the error log and configuration from grafana server.

Config 

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAaccountName"
member_of = "memberOf"
email =  "mail"

Error Log

t=2017-04-01T01:03:30+0000 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="UNIQUE constraint failed: user.login"
t=2017-04-01T01:03:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=10.10.214.193 time_ms=10ns size=53

**Comment by torkelo** [comment]
make sure the mail and username properties are correct. You can debug this by enabling more logging via: 

```
[log]
filters = ldap:debug
```

The error indicates that there is something wrong with the username and email properties (empty or the same as existing Grafana user)
