### ISSUE TITLE
[Bug] RequiredError for LoginOrEmail

### ISSUE THREAD

**Issue by Joannou1** [grafana/grafana#8005]
Exact symptoms / issue as #5209 - except I'm using PHP CURL to post data.
No errors in log, 'role' field gets submitted fine, complains if I remove it with the same message.
Other API methods seem to work just fine (creating users and orgs) with the same curl post method.

Using latest Grafana (4.2.0 349f3eb) on Ubuntu / Nginx / Influx

Method used:
http://docs.grafana.org/http_api/org/#add-user-in-organisation

```
function assignUserOrg($user, $role, $orgid){
	return post("/orgs/$orgid/users", array(
		"loginOrEmail" => $user,
		"role" => $role
	));
}

function post($path, $args){
	global $auth;
	global $url;
	$curl = curl_init();
	curl_setopt_array($curl, array(
		CURLOPT_RETURNTRANSFER => 1,
		CURLOPT_URL => $url . $path,
		CURLOPT_HTTPHEADER => array(
			$auth
		),
		CURLOPT_POST => 1,
		CURLOPT_POSTFIELDS => $args
	));

	$resp = curl_exec($curl);
	curl_close($curl);

	return $resp;
}
```

**Comment by torkelo** [comment]
Make sure you set Content-Type to  application/json 

If you still get error please include full raw data sent to HTTP API
