### ISSUE TITLE
[BUG] When swithching the organisation, getting redirected to loacalhost3000 

### ISSUE THREAD

**Issue by bb-vishalsingh** [grafana/grafana#80073]
### What happened?

When switching to another organisation from the current organisation it replaces the domain with localhost:3000, for the first time and if trying to swithch to same organisation in other tab for the second tab it is working fine. This is happening for each organisation swithch for the first time and for second time for the same organisation it is working fine

### What did you expect to happen?

Switching organisation should not redirect to localhost

### Did this work before?

No

### How do we reproduce it?

1.Try deploying grafana through a reverse proxy.
2. Create multiple Organisation.
3. Try Switching the organisation 

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10.1.5
OS: Linux
Browser: Chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
Hello @bb-vishalsingh , thank you for reporting this issue

Could you check whether there are any console errors in the browser's developer tools when the redirection to localhost:3000 occurs? If so, could you please provide the output here?

Can you confirm if you have any Grafana configuration settings (grafana.ini or environment variables) that might be related to the base URL or domain settings? If so, please provide details.

Thank you

**Comment by bb-vishalsingh** [comment]
Got resolved the issue through setting the subpath and domain explicitly
