### ISSUE TITLE
[bug]tag_values() and tag_names() is invalid --templating of OPENTSDB

### ISSUE THREAD

**Issue by congshenV** [grafana/grafana#8007]
Grafana version:4.2.0
datasource:OPENTSDB
OS:CentOS

- What did you do?
I want to get a metric tag and tag values.
From the documentation I learned that you can use tag_values (metric_names,tag_name) to get tag values.
the documentation is :http://docs.grafana.org/features/datasources/opentsdb/
I do not know the document is not updated or I use the method is not correct?
- What was the expected result?
Return a list of tag values.
- What happened instead?
Return nothing

**Comment by torkelo** [comment]
If you look at the docs under the template variable section it mentions that you need to enable OpenTSDB options for some of these to work

**Comment by congshenV** [comment]
I have turned on opentsdb related options, but still can not get tag_values variable through tag_values ().

In addition, I need to explain that I can get tag_values through suggest_tagv(), but can not obtained through tag_values ().
I would like to know if the function interface has been changed?And how can I get the tag_values by tag.
