### ISSUE TITLE
Prometheus: Implement OAuth / OIDC to support authentication with AWS Cognito

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#80086]
AWS Cognito requires OAuth / OIDC to work. Here is an [escalation](https://github.com/grafana/support-escalations/issues/8754) requesting that.

OAuth / OIDC is not supported in data sources.

There are a few options we can look at for this.

1. Implement it in the future vendor specific externalized Prometheus
2. Request that data sources squad that maintains the Auth component to bring this to all data sources.

This will need further research.

**Comment by bohandley** [comment]
Observability metrics does not currently have bandwidth to prioritize development on this issue. If members in the community want to take this issue we will help review any submitted PRs. Please upvote or comment to help us re-prioritize this issue in the future!

**Comment by ajaydevtron** [comment]
@bohandley Does we any workaround to authenticate Prometheus endpoint (Enabled OpenId with okta using AWS ALB) ?
Still this support not added in Grafana(Image -> grafana/grafana:11.5.1) ?

Note:- My Grafana is enabled with google auth enabled
