### ISSUE TITLE
Alert dragging broken on log scale

### ISSUE THREAD

**Issue by jleclanche** [grafana/grafana#8008]
Grafana 4.2.0. Dragging the alert scale is completely broken if the graph is using a log scale; it goes all over the place.

![image](https://cloud.githubusercontent.com/assets/235410/24579519/0b963ad8-1700-11e7-9b04-7776f06f1b21.png)

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by kaydelaney** [comment]
Closing this as it's been fixed
