### ISSUE TITLE
[Bug] - Constantly receiving [No Data] Alerts 

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#8010]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Amazon Linux AMI
- What did you do?
Configured CPU alert on CPU metric with Moving average.
- What was the expected result?
Receive alerts upon threshold violation
- What happened instead?
Constantly receiving No Data alerts and after a while it clears by itself.

Some screen shots:

The received alert:
![image](https://cloud.githubusercontent.com/assets/24862189/24602737/d6f36aa4-1866-11e7-939f-f1c9042d456d.png)

The metric configuration:
![image](https://cloud.githubusercontent.com/assets/24862189/24602763/f55a24ce-1866-11e7-88db-2bbea8dea504.png)

The alert configuration:
![image](https://cloud.githubusercontent.com/assets/24862189/24602787/0c4b4050-1867-11e7-9339-703e57597736.png)

**Comment by torkelo** [comment]
And if you hit Test Rule, what does your query return (if you expand the log output that show up after Test Rule you can  see the raw data returned by query)

**Comment by dudusakharovich** [comment]
This is the output when CPU is green and normal:

![image](https://cloud.githubusercontent.com/assets/24862189/24608668/3ab69926-1880-11e7-93d1-19f216f8ceaa.png)

I will try to catch the same output when No data alert is received.

**Comment by dudusakharovich** [comment]
Another thing @torkelo - Most of the times an alert is being generated it seems like the threshold actually not violated.
Maybe it's related to the fact that I'm trying to monitor moving average ?

**Comment by torkelo** [comment]
make sure you have specified a low limit on group by time (like `>1m`) so that the group by time is not lower than you expect

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/24614138/a355b57a-188a-11e7-833c-95954c2b136b.png)

Also if you really want to use filters bucket aggregation then I would recommend adding that before the terms aggregation.

**Comment by torkelo** [comment]
sorry, commented on wrong issue

**Comment by dudusakharovich** [comment]
Hey @torkelo
I've received another false alert, you can clearly see in the graph that the threshold violation has not reached, and in addition the alert doesn't provide the metric name & value.

![image](https://cloud.githubusercontent.com/assets/24862189/24617143/dae257c6-189b-11e7-91ce-c83411ce5aa4.png)

**Comment by torkelo** [comment]
if open the graph and hover over the alerting annotation, what does the tooltip say? You can also see info in the alert history view in the alert tab

**Comment by cmclaughlin** [comment]
I have this problem on Grafana 4.4.1 with a Graphite backend.

<img width="622" alt="screen shot 2017-07-30 at 3 04 46 pm" src="https://user-images.githubusercontent.com/1061109/28757459-a0e20568-7538-11e7-865e-289f87365150.png">

<img width="504" alt="screen shot 2017-07-30 at 3 05 30 pm" src="https://user-images.githubusercontent.com/1061109/28757465-c97673b0-7538-11e7-9247-7f2aa43ccd58.png">

I found a few other issues about this, but this one seems the most relevant.  Please let me know if there's anything I can do to help narrow it down.

**Comment by cmclaughlin** [comment]
btw, I'm running `whisper-resize.py` on my graphite server which is probably taking it offline intermittently... but I don't want Grafana to alert in this situation.

**Comment by torkelo** [comment]
if @cmclaughlin if your graphite server is intermittently returning no data then I guess you have to set "if no data or all values are null" to Keep Last State if you want Grafana to ignore that.
