### ISSUE TITLE
[Bug] Singlestat panel "Direct link rendered image" is missing title and stat

### ISSUE THREAD

**Issue by scharissis** [grafana/grafana#8011]
Grafana 4.12
I've got a dashboard with a repeated singlestat panel which is using a template variable as it's name/title.

When I select Share > Link > "Direct link rendered image", it renders the background and spark lines, but the title and stat are both missing.

Is the singlestat panel not supported, or is this a bug?

**Comment by torkelo** [comment]
strange, unable to replicate on this dashboard: 

http://play.grafana.org/dashboard/db/templating-repeated-panels?var-server=backend_01&var-server=backend_02&var-server=web_server_03&var-server=web_server_04

**Comment by scharissis** [comment]
Strange!

What version of Grafana is play.grafana.org running?
Would the datasource matter? I am using a custom one.

Here's what gets rendered for me: http://pasteboard.co/RdVcP44Gw.png

**Comment by torkelo** [comment]
play.grafana.org is using v4.1.1 

if you try to load the URL that "Direct link rendered image" generates but remove the `/render/` part you should see the singlestat panel in fullscreen in your browser. does it show the number?

**Comment by scharissis** [comment]
Interesting. Yes, when I remove the "/render/" part of the URL, I do indeed the the panel fullscreen and it appears correctly. That is, it does show both the title and number.
Also, when I load both (with/without /render/) I see no errors in my browser Network/Console.

Any other ideas to try? Or, can I provide any more detail/context?

**Comment by scharissis** [comment]
torkelo@, is there a reliance on  certain fonts? I suspect that's what I'm missing.

**Comment by torkelo** [comment]
That is probably it, try to install some basic font packages (check centos install doc page for example)

**Comment by scharissis** [comment]
I installed "urw-fonts" and this worked, but it looks really ugly.

I don't have any experience with handling fonts, but his reliance is ugly/annoying. Can we not bake it into Grafana, or have a fallback to some other font?

**Comment by torkelo** [comment]
you can install other fonts as well. It's the font rendering that requires a server side package for phantomjs to use. Grafana already includes links to a a custom web font (OpenSans). But for phantomjs not sure that is being used.

**Comment by torkelo** [comment]
But images I render on ubuntu usually look identical to what I see in the browser.
