### ISSUE TITLE
[Bug] Escaping needed when using template variable in regex (influxdb source)

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#8012]
- What Grafana version are you using?
`v4.2.0 (commit: 349f3eb)`
- What datasource are you using?
`InfluxDB`
- What OS are you running grafana on?
`RHEL 6`
- What did you do?
  - Add a template variable `intf` consisting of a query `SHOW TAG VALUES FROM "snmp_data" WITH KEY = "name" WHERE "device_name" =~ /^$device$/` (single selection only)
  - Add a table-panel
  - Add a query `SELECT * FROM "snmp_data" WHERE "device_name" =~ /^$device$/ AND "name" =~ /^$intf$/ ORDER BY time DESC LIMIT 1`
  - The template variable `$intf` can have values like 'GigabitEthernet1/1/1`
- What was the expected result?
  - The contents of the template variable `$intf` would be properly escaped in order that the query returns the data expected.
- What happened instead?
  - The forward slashes weree not escaped. InfluxDB interprets this as termination of the regex and fails.

Workaround
- As long as single selection is enough, using regexes is not mandatory and the query can be manually transformed to: `SELECT * FROM "snmp_data" WHERE "device_name" =~ /^$device$/ AND "name" = '$intf' ORDER BY time DESC LIMIT 1`

Proposal
I think, it's probably not the best to generally escape anything as users might want to use regexes as template variable values, but to provide an option at the template variable setup to specifically enable escaping.

This issue is similar to #5452, but related to InfluxDB and not Elasticsomething

**Comment by bbczeuz** [comment]
Solution could be related to #7966 (--> Checkbox to enable/disable escaping)

**Comment by torkelo** [comment]
Cannot replicate this, by default all interpolated values are regex escaped for InfluxDB queries. There is one exception, if the template variable as no "All" value and unchecked the "Multi Value" option. 

Example:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?var-datacenter=Asia&var-host=server%5C5&var-host=server%5Csecond%5Cslash&var-summarize=1m


Can you show the options for your $intf variable?

**Comment by bbczeuz** [comment]
Indeed, checking "All" or "Multi value" is kind of another workaround that helps, but being able to check multiple values does not make sense here.
I actually found that the issue (no escaping of fwd slashes) does only appear if using the text edit mode for the query. I need the text edit mode as Grafana currently does not support `ORDER BY time DESC` and `LIMIT 1`

**Comment by torkelo** [comment]
yea, I know it's now ideal.In raw mode it's trickier to know what context the variable is in (regex operator or just inside a string), 

https://github.com/grafana/grafana/issues/7306
