### ISSUE TITLE
 How to configure Grafana to send multiple messages to Altermanager？

### ISSUE THREAD

**Issue by huo2huo** [grafana/grafana#80134]
The Grafana version is V9.5.7 with a configuration check table data change. If the condition is not met, a message will be sent to the altermanager. The altermanager has configured that if no message is received within 1 hour, it will become resolved. However, it was found that Grafana only sent a message once. How can multiple messages be sent within 1 hour in Grafana?

**Comment by marefr** [comment]
Please ask your question on [community.grafana.com/](https://community.grafana.com/). To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!
