### ISSUE TITLE
[Bug] Heatmap plugin error

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#8013]
- What Grafana version are you using?
4.3.0-7413pre1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04 LTS
- What did you do?
Created dashboard with new "heatmap" graph
- What was the expected result?
Heatmap graph
- What happened instead?
```
Plugin Error
[$injector:unpr] Unknown provider: bProvider <- b http://errors.angularjs.org/1.6.1/$injector/unpr?p0=bProvider%20%3C-%20b
```

**Comment by torkelo** [comment]
@alexanderzobnin can you take a look at this? 

Probably an `/** @ngInject **/`  missing on a constructor for a heatmap angular controller. 

To test optimized build run  `grunt build`  (then restart grafana-server the main html template file is updated with revisioned css/js file)
