### ISSUE TITLE
Permissions: Explicitly assigned permission displayed as inherited

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#80156]
### What happened?

When folder or dashboard has both inherited and explicitly assigned permission, it is displayed as inherited.

![Screenshot from 2024-01-08 12-56-43](https://github.com/grafana/grafana/assets/4932851/d2afa66f-b9e3-41b4-bd31-2bc05cc574fe)
![Screenshot from 2024-01-08 12-58-12](https://github.com/grafana/grafana/assets/4932851/3e366d13-9147-46c4-adf0-57fbc0cf7da0)

### What did you expect to happen?

It should be displayed as regular permission.

### Did this work before?

No

### How do we reproduce it?

1. Create a folder.
2. Assign permission for user/team or role
3. Create another folder inside.
4. Assign the same permission.

### Environment (with versions)?

Grafana: latest main (10.3)
OS:
Browser:

### Grafana platform?

None

**Comment by IevaVasiljeva** [comment]
Sorry @alexanderzobnin, I didn't realise that you had already assigned this to yourself. Hope you didn't start working on it yet.
