### ISSUE TITLE
Remove core imports from `app/store/store` from CloudWatch

### ISSUE THREAD

**Issue by katebrenner** [grafana/grafana#80153]

**Comment by kevinwcyu** [comment]
Work for this was completed in https://github.com/grafana/grafana/pull/80837, https://github.com/grafana/grafana/pull/80843, https://github.com/grafana/grafana/pull/80926, and https://github.com/grafana/grafana/pull/81422

Effort tracked in https://github.com/grafana/grafana/issues/80148
