### ISSUE TITLE
Filter for table panel

### ISSUE THREAD

**Issue by izenk** [grafana/grafana#8015]
Hello

Grafana: 4.2.0
datasource elasticsearch 5.2
OS: Ubuntu 14.04 x64
I'm trying to configure dashboard with table panel:

My conditions is: choose memory metric, filter by role:db and group by role_host
My query config is:

<img width="1429" alt="screen shot 2017-04-03 at 16 02 45" src="https://cloud.githubusercontent.com/assets/6417697/24610448/3ec02382-1887-11e7-85b6-072fda7fe139.png">

Table transform is Timeseries to rows. As you can see, Metric column contains my filter as part of content (for example: postgresql-1 **role:db**). So filter was not applied.

**Comment by torkelo** [comment]
you specified `role:db` as group by filter (So it will create a group for documents matching that filter). Did you want to that or did you want to filter the whole query? 

The Filters bucket aggregation will give the series name the filter content so you know which series are due to which filter.

**Comment by torkelo** [comment]
which probably explains why the dredis-1 table row do not have any value in the table.

Sounds like you want to filter the whole query put the  `role:db` in the main query field.

**Comment by izenk** [comment]
Tried, but nothing changed
<img width="1391" alt="screen shot 2017-04-03 at 16 52 27" src="https://cloud.githubusercontent.com/assets/6417697/24612457/fd16eafe-188d-11e7-9a3d-036943df12be.png">


More over, my older panels start work incorrectly.
I recorded short screen-video to show the process.
In general: I have a query, which worked fine but after updating to grafana 4.2, filtering not work

Please find record: https://drive.google.com/file/d/0B896mc0LoDQ0M0FMcnRQcUFnTm8/view?usp=sharing

Look at Legend at the right part of screen. I just changed filter value and returned it back

**Comment by torkelo** [comment]
You can open chrome dev tools and look at the query sent to ES? Not sure why ES is not filtering the data. Maybe something wrong with the ES index mapping? 

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

When I try it it works fine:
http://play.grafana.org/dashboard/db/elasticsearch-metrics-filter?panelId=6&fullscreen&edit

**Comment by izenk** [comment]
```json
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["metricbeat-2017.04.02","metricbeat-2017.04.03"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1491166800000","lte":"1491253199999","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"4":{"filters":{"filters":{"role:db":{"query_string":{"query":"role:db","analyze_wildcard":true}}}},"aggs":{"5":{"terms":{"field":"role_host","size":10,"order":{"_term":"asc"},"min_doc_count":0},"aggs":{"2":{"date_histogram":{"interval":"1m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1491166800000","max":"1491253199999"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"system.load.1"}}}}}}}}}}
```

I have also Kibana installed and filtering works fine from Kibana or direct curl.

**Comment by torkelo** [comment]
@izenk the query you pasted is still using a filters bucket aggregate and I am not seeing the the response from ES. 

Would be interesting to see the query and response if you specify `role:db` in the query field.

**Comment by izenk** [comment]
request:
```json
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["metricbeat-2017.04.02","metricbeat-2017.04.03"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1491166800000","lte":"1491253199999","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"role:db"}}]}},"aggs":{"5":{"terms":{"field":"role_host","size":10,"order":{"_term":"asc"},"min_doc_count":0},"aggs":{"2":{"date_histogram":{"interval":"1m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1491166800000","max":"1491253199999"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"system.load.1"}}}}}}}}
```

responce (was cut because of too big number of lines):
lb1.lb.ap.prd host also has no role:db
```json
{"responses":[{"took":100,"timed_out":false,"_shards":{"total":18,"successful":18,"failed":0},"hits":{"total":994883,"max_score":0.0,"hits":[]},"aggregations":{"5":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"lb1.lb.ap.prd","doc_count":0,"2":{"buckets":[{"key_as_string":"1491166800000","key":1491166800000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1491166860000","key":1491166860000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1491166920000","key":1491166920000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1491166980000","key":1491166980000,"doc_count":0,"1":{"value":null}},"status":200}]}
```

<img width="1413" alt="screen shot 2017-04-03 at 17 34 22" src="https://cloud.githubusercontent.com/assets/6417697/24614447/e7fee4c2-1893-11e7-9a2f-612d43aa5a78.png">

**Comment by torkelo** [comment]
Strange. Somehow ES is ignoring the lucene query filter? 

The query contains 
`"query_string":{"analyze_wildcard":true,"query":"role:db"}` so not sure what else Grafana can do here. This is the way query filters have been issued since Grafana v2.5 and and so far no other reports of non effective filters. 

Any ideas?
