### ISSUE TITLE
[Bug] Graph Description Not Fully Displayed

### ISSUE THREAD

**Issue by jerenmb** [grafana/grafana#8016]
Hello,

I couldn't find this issue open anywhere else, but please correct me if this has already been raised. When I add a description for any graph, the tooltip that shows in the top left corner is centered over the info icon, so if the graph extends to the left side of the screen, much of the text is lost. I see this same behavior in Chrome, Safari, and Firefox. Please see the attached screenshot.

Edit: I am using Grafana v 4.2.0

![screen shot 2017-04-03 at 10 14 01 am](https://cloud.githubusercontent.com/assets/5981522/24613865/9ae4fa32-1857-11e7-8f4c-43f1c278ca10.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/24614202/d5625726-188a-11e7-91e2-e4b1aadc6a45.png)

Just searching for the word description and you find two duplicates of this issue :) It's fixed in master/nightly build :)
