### ISSUE TITLE
[Feature Request] Colorize table rows by hidden column value

### ISSUE THREAD

**Issue by wrouesnel** [grafana/grafana#8017]
It is currently possible to set a table column as "hidden".

But a hidden column cannot be used to set the color of a table row based on the value in the hidden column. This means adding tables showing something like a service or node's "health" doesn't work - i.e. where you'd like to display the name of service, and it's color based on a health metric value (i.e. 1 or 0) but not the redundant 1 or 0 value in a separate column.

**Comment by con5cience** [comment]
Yes please!

**Comment by previousdolphin** [comment]
would be great to be able to color the row, by a hidden columns value!

**Comment by rdelpret** [comment]
Yes trying to do this right now! :)

**Comment by avgdev** [comment]
Thanks a lot for working on this. any idea if we can test this now?

**Comment by jgoldring** [comment]
Is there a rough estimate when this might be available?

**Comment by codeincarnate** [comment]
We're looking into table enhancements at the moment and we'll track this one along with the other ones we're working on. That can be found here: #56220
