### ISSUE TITLE
Dashboards: Panels appear loading indefinately after getting response with No Data

### ISSUE THREAD

**Issue by itsjusth** [grafana/grafana#80171]
### What happened?

I have a panel using Azure Monitor Data Source to get logs.  The KQL query should yield no results for the date range selected.  In the Browser's Developer Tools, I can see that Grafana called Azure to perform the query and the response came back with no data.  The response body was

`{"results":{"A":{"status":200}}}`

Instead of the panel saying "No data", the user is experiencing the panel in a constant "loading" state.  The loading spinner for the panel continues perpetually and the panel displays nothing.

In testing, I was able to reproduce this issue MOST of the time, but not every time.  Multiple users on other Windows platforms and other browsers also observed this issue.

### What did you expect to happen?

Expected to see "No data" in the panel.

### Did this work before?

Yes.  Unsure what version.  Recently migrated from 9.5.6 to latest.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: v10.3.0-64399  (Enterprise license - Grafana Cloud hosted)
OS: Windows 11
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Azure Monitor 1.0.0

**Comment by usmangt** [comment]
Hi @itsjusth,

Thanks for opening this issue.

Could you please copy/paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu?

This will help us mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. 

Thank you!

Here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by itsjusth** [comment]
Hi, @usmangt
This issue affected my organization for about 48 hours, but has since stopped and we cannot reproduce.  The original issue affected any panel with a data source & selection that returned no data.  This is condition is simple to reproduce, however the continuous loading situation we are seeing is not happening anymore.  This can be closed for now.
