### ISSUE TITLE
Alerting: Resolved notifications do not resolve Go template code

### ISSUE THREAD

**Issue by jv4n5e** [grafana/grafana#80198]
### What happened?

The Go template code for .Annotations.description is correctly interpreted/translated for FIRING notifications, but not for RESOLVED ones in the content of email notifications. Please see the provided images. The template does have more data, which is working as expected and the code within the range .Alerts.Firing and range .Alerts.Resolved is identical. No useful data on logs.

This seems to work as expected though, when I use the same ng_alert_notification.html but using a different subject template.

### What did you expect to happen?

Go template code being interpreted/translated correctly for both FIRING and RESOLVED notifications.

### Did this work before?

Not sure, first time working on this.

### How do we reproduce it?

1. Use the provided ng_alert_notification.html.
2. Have alerts firing and later resolving.
3. See .Annotations.description displaying correctly for firing notifications, but not for resolving.
[ng_alert_notification.html.txt](https://github.com/grafana/grafana/files/13872359/ng_alert_notification.html.txt)

### Environment (with versions)?

Grafana: 10.2.2
OS: Kubernetes (helm chart)

### Grafana platform?

Kubernetes

**Comment by grobinson-grafana** [comment]
Hi! 👋 As mentioned in Slack, we do not support modifications to the `ng_alert_notification.html` file. If notifications are not working as expected following modifications to this file, although work with the original version of this file, I would think there is a mistake somewhere in the modifications made. I would recommend restoring `ng_alert_notification.html` to it's original version until Grafana offers official support for customizing HTML in emails.
