### ISSUE TITLE
[Bug] Black (and empty) graph on mail alerts 

### ISSUE THREAD

**Issue by antoiner77** [grafana/grafana#8020]
- What Grafana version are you using?
-> version 4.2.0
- What datasource are you using?
-> InfluxDb
- What OS are you running grafana on?
-> Amazon linux
- What did you do?
-> Setup an alert, it first work then no more, without any change (no error on log)
- What was the expected result?
-> Be able to see the graph on the mail
- What happened instead?
-> A black and empty graph on the mail

Thanks

**Comment by torkelo** [comment]
try installing font packages so that phantomjs works on your server

http://docs.grafana.org/installation/rpm/#server-side-image-rendering
