### ISSUE TITLE
Snapshots: values are connected despite `Connect null values` set to `never`

### ISSUE THREAD

**Issue by mkuratczyk** [grafana/grafana#80211]
### What happened?

I have a dashboard from performance tests, with each test separated by a quiet period. The dashboard sets `Connect null values` to `never` and that works as expected, for example here are the results of 6 different tests:
<img width="687" alt="Screenshot 2024-01-09 at 13 00 04" src="https://github.com/grafana/grafana/assets/9566114/90f67125-c6ec-4de8-9c39-d4af1eaff0c2">

However, when I export a snapshot of this dashboards, values are connected, making the dashboard much less readable:

<img width="433" alt="Screenshot 2024-01-09 at 13 02 36" src="https://github.com/grafana/grafana/assets/9566114/9839e4b4-ec06-4a2c-b1c1-922121e76d11">

### What did you expect to happen?

I'd like the snapshot to look just like the dashboard

### Did this work before?

Don't know.

### How do we reproduce it?

1. Create a dashboard with some "gaps" (null values)
2. Set `Connect null values` to `never`
3. Publish a snapshot

A sample snapshot with the issue:
https://snapshots.raintank.io/dashboard/snapshot/WVtYt4of7WCUm2Oy114StXUhieI8jLAZ?orgId=2

### Environment (with versions)?

Grafana: v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)
OS: Linux
Browser: Chrome/macOS

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
hi @mkuratczyk 

Thank you for creating this issue

I could not repro this behaviour Here is a capture of my snapshot (Grafana v 10.0.3, data source is also Prometheus, and panel type is time-series)

![image](https://github.com/grafana/grafana/assets/45235678/9a17fefd-c978-4b51-9db3-bb8a74650328)

Could you please provide the JSON model of the dashboard panel that is experiencing this issue? This could help us replicate the problem more accurately. You can export the JSON model by using the panel --> more --> get help workflow in the panel's drop-down menu

Also, are there any console errors in your browser's developer tools when viewing the snapshot?

Thank you

**Comment by mkuratczyk** [comment]
I just tried again (I'm on `Grafana v10.3.1 (00a22ff8b2)` now) and it runs out this only happens when I publish to https://snapshots.raintank.io/. A local snapshot is fine.

This is what a local snapshot looks like:
<img width="998" alt="Screenshot 2024-02-07 at 19 33 21" src="https://github.com/grafana/grafana/assets/9566114/b8d1c372-0b79-41df-ab43-d7452e61c300">

And this is another snapshot, but [published](https://snapshots.raintank.io/dashboard/snapshot/1TM5QOuVm5uEvuKCZXw4CJGbP6dAcdd1?orgId=2):
<img width="1002" alt="Screenshot 2024-02-07 at 19 34 22" src="https://github.com/grafana/grafana/assets/9566114/a2266268-8bb0-44ef-823c-e6243e89c625">

The panel:
[panel.json](https://github.com/grafana/grafana/files/14200157/panel.json)

**Comment by lucychen-grafana** [comment]
Hi @mkuratczyk, is there a reason why you are publishing it to https://snapshots.raintank.io/ and not just using local snapshots? We are planning on removing the publishing it to raintank functionality as there are better ways to share now including [Public Dashboards](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/)

**Comment by mkuratczyk** [comment]
We run some of the tests/benchmarks in ephemeral clusters that we deploy with all the tooling, including `kube-prometheus-stack` but then want to capture the snapshots before destroying the cluster. If this functionality is going away, feel free to close this issue - seems like the problem doesn't occur with local snapshots and I'm sure we can rearrange our tests to just collect data in a Grafana that'll be long-lived.

**Comment by lucychen-grafana** [comment]
Great! Please do utilize local snapshots and public dashboard for you needs. Thanks
