### ISSUE TITLE
Alerting: Templating plus Slack breaks when name for the notification template contain square brackets

### ISSUE THREAD

**Issue by martinreck** [grafana/grafana#80224]
### What happened?

I use Grafana Alerting with Slack as notification platform.

To increase readability, I create several notification templates. I would like to use the following naming pattern when I add a new template:

- [Slack] Message Title
- [Slack] Message Text
- [EMail] Subject
- [EMail] Body

When I try to test a Slack contact point with the existing templates, I get an error message:

```text
logger=ngalert.notifier.slack notifierUID=*** t=*** level=error msg="The request was unsuccessful" body="{\"ok\":false,\"error\":\"invalid_arguments\",\"warning\":\"missing_charset\",\"response_metadata\":{\"messages\":[\"[ERROR] missing required field: channel\"],\"warnings\":[\"missing_charset\"]}}" err=invalid_arguments
```

If I remove the square brackets from the template names and then test the Slack contact point again, the test message is sent without an error.

In the documentation I cannot find any hint that there are character restrictions for template names.

### What did you expect to happen?

I expect that all characters are allowed in the template names. If there are any character restrictions, I expect the documentation to contain appropriate information.

### Did this work before?

I don't know

### How do we reproduce it?

See "What happened"

### Environment (with versions)?

Grafana: 10.1.1
OS: MacOS Sonoma
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by martinreck** [comment]
I have one more hint:

If I use an opening square bracket (`[`) in the name of the template, then I get the error:

> Error saving template
> failed to save and apply Alertmanager configuration: syntax error in pattern

**Comment by tonypowa** [comment]
@martinreck  is this specific to Slack ?

**Comment by martinreck** [comment]
I have only tested this with Slack as I don't have an email setup yet.

**Comment by tonypowa** [comment]
@martinreck 
I'm afraid, I don't have a local SMTP setup with access to logs at the moment, but I will ask my team to check this for me.

In Cloud, I managed to sent myself a test notification using an email contact point that uses a notification template with title "[Email] Template name", like yo did. And obviously there was some error because I never got the email. 

I inspected the network, and I can see that the request was sent successfully at this point.  Here is the title in the request body (JSON):
``` 
message:	'{{template "[Email] Template name" .}}'
```

I will keep you posted once I test it or once I learn more details about char restrictions from the Alerting team

**Comment by tonypowa** [comment]
actually I just found out that when if you make reference to the notification template in the contact point settings like so:
`{{template "[Email] Template name" .}}`

 and you hit the save button, an error is logged in the broswer's inspector tool

```
JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: 
Source Map URL: react_devtools_backend_compact.js.ma
```

**Comment by tonypowa** [comment]
@martinreck 

My colleague suspects that there is an error is somewhere else in the template.
Could you please remove any sensitive data and share your whole notification template?

Here is btw an example of a working notification using the square brackets in the title 

``` go
{{define "[Email] Template name" }}
Hello, world
{{ end }}
```

![Screenshot 2024-02-15 at 9 59 10 AM](https://github.com/grafana/grafana/assets/45235678/a31d32fb-8ffa-41b7-a632-e6d30b7a1346)
![Screenshot 2024-02-15 at 9 58 52 AM](https://github.com/grafana/grafana/assets/45235678/7f198812-29f3-42b5-a8df-1bbb40bd2242)
![Screenshot 2024-02-15 at 9 58 58 AM](https://github.com/grafana/grafana/assets/45235678/43524a91-af1f-412b-be94-91c279698f66)
![Screenshot 2024-02-15 at 9 58 45 AM](https://github.com/grafana/grafana/assets/45235678/8922ea3c-7187-491a-b842-76359f24acaa)

**Comment by armandgrillet** [comment]
Waiting for feedback for 2 weeks, closing.

**Comment by martinreck** [comment]
There is a misunderstanding here. I am not talking about the name of the template, as shown in this comment:

https://github.com/grafana/grafana/issues/80224#issuecomment-1945746309

My error occurs when I use square brackets in the following place in the web interface:

![Grafana-NewTemplate](https://github.com/grafana/grafana/assets/2986819/76e01e33-7be2-4181-ad71-e57fe8471b74)

**Comment by santihernandezc** [comment]
Hi @martinreck, it looks like a bad Slack title template will cause no `channel` field to be sent in the request to Slack.
I just issued a [fix for this bug](https://github.com/grafana/alerting/pull/248).

In your case, you changed the name in the UI, but the template itself is still called `slack.message.text` (check the `define` statement in the template you shared). Calling `{{ template "[Slack] Dummy Notification" . }}` within the contact point will result in an error as the template is not defined. You can check for warnings in the logs to confirm this.
