### ISSUE TITLE
Update request for tutorial: How to create alerts with log data

### ISSUE THREAD

**Issue by Eve832** [grafana/grafana#80239]
A user has identified that the sample file text in this tutorial is incorrect. Note that this tutorial lives in this repo at: `docs/sources/tutorials/create-alerts-with-logs`

Per the user:

> Regarding:

> https://grafana.com/tutorials/create-alerts-with-logs/#optional-use-docker-compose-to-create-the-tutorial-environment

> The section with sample code in the section i reference in the link will NOT work as presented.  If you copy the file "web-server-logs-simulator.py" with the COPY provided it will not work because the indentation for the python file is incorrect.

> I have enclosed a screenshot of what the correct looking file should look like to be copied.
 
<img width="1213" alt="Screenshot 2024-01-08 at 8 58 49 PM" src="https://github.com/grafana/grafana/assets/81647476/c66b5639-a239-4b85-9499-f549cb8000c8">

**Comment by Eve832** [comment]
Since the original author is no longer available to work on this, I'm going to tag @moxious  just in case there's a dev advocate willing to update the PR while I put it in our (Docs) backlog.

**Comment by tonypowa** [comment]
looking into it 👀
