### ISSUE TITLE
[Bug] Annotation Table not working in Grafana 4.2 with JSON data source

### ISSUE THREAD

**Issue by msm93v2** [grafana/grafana#8023]
I just upgraded Grafana 3.2 to 4.2 and am experiencing an issue similar to what was described in https://github.com/grafana/grafana/issues/7268 however my table is not displaying column headers.

I currently am using Grafana 4.2 running on Ubuntu Server 16.04, I created an annotation table using the a simple JSON datasource, the annotations return as expected on a Graph panel, but the table is blank. I can tell that the table recognizes results (it paginates when there are many annotations returned) however there is nothing displayed in the panel.

Here's example JSON returned for the annotations:

`[
   {
      "annotation": {
         "name": "Outages",
         "datasource": "pingdom-exporter",
         "enable": true,
         "iconColor": "rgba(255, 96, 96, 1)",
         "query": "{service.example.com,biblio.example.com,ego.example.com,email.example.com,emerald.example.com,login.example.com,launchpad-service.example.com,mercury.example.com,prism.example.com,scholar.example.com,siren.example.com,tully.example.com}"
      },
      "time": 1477048736000,
      "title": "scholar.example.com",
      "tags": "Outages",
      "text": "scholar.example.com was down for 6660 seconds"
   },
   {
      "annotation": {
         "name": "Outages",
         "datasource": "pingdom-exporter",
         "enable": true,
         "iconColor": "rgba(255, 96, 96, 1)",
         "query": "{service.example.com,biblio.example.com,ego.example.com,email.example.com,emerald.example.com,login.example.com,launchpad-service.example.com,mercury.example.com,prism.example.com,scholar.example.com,siren.example.com,tully.example.com}"
      },
      "time": 1477066496000,
      "title": "scholar.example.com",
      "tags": "Outages",
      "text": "scholar.example.com was down for 2280 seconds"
   },
   {
      "annotation": {
         "name": "Outages",
         "datasource": "pingdom-exporter",
         "enable": true,
         "iconColor": "rgba(255, 96, 96, 1)",
         "query": "{service.example.com,biblio.example.com,ego.example.com,email.example.com,emerald.example.com,login.example.com,launchpad-service.example.com,mercury.example.com,prism.example.com,scholar.example.com,siren.example.com,tully.example.com}"
      },
      "time": 1485324776000,
      "title": "scholar.example.com",
      "tags": "Outages",
      "text": "scholar.example.com was down for 120 seconds"
   },
   {
      "annotation": {
         "name": "Outages",
         "datasource": "pingdom-exporter",
         "enable": true,
         "iconColor": "rgba(255, 96, 96, 1)",
         "query": "{service.example.com,biblio.example.com,ego.example.com,email.example.com,emerald.example.com,login.example.com,launchpad-service.example.com,mercury.example.com,prism.example.com,scholar.example.com,siren.example.com,tully.example.com}"
      },
      "time": 1485948956000,
      "title": "scholar.example.com",
      "tags": "Outages",
      "text": "scholar.example.com was down for 120 seconds"
   }
]`

**Comment by torkelo** [comment]
unable to replicate it here, 

can you show your dashboard json? (annotation config, and table config, data returned from your annotation query etc).

**Comment by msm93v2** [comment]
Panel JSON:
`{
  "columns": [],
  "datasource": "Prometheus",
  "editable": true,
  "error": false,
  "filterNull": false,
  "fontSize": "100%",
  "id": 2,
  "links": [],
  "pageSize": 200,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "span": 12,
  "styles": [
    {
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "pattern": "Time",
      "type": "date"
    },
    {
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 2,
      "pattern": "/.*/",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "expr": "",
      "intervalFactor": 2,
      "refId": "A",
      "target": "12-month"
    }
  ],
  "title": "Outages Overview",
  "transform": "annotations",
  "type": "table"
}`

**Comment by torkelo** [comment]
managed to replicate this now, was  bug introduced by https://github.com/grafana/grafana/pull/7487. 

Fix incoming.

**Comment by msm93v2** [comment]
Question - is there a quick/easy way for me to apply your changes on my end? I manually edited /usr/share/grafana/public/app/plugins/panel/table/module.html with the changes you made in the commit but see no difference. Maybe it's not that simple for the changes to take effect?

**Comment by torkelo** [comment]
You need to rebuild your the frontend, html and js files are concatenated and minified in releasses

**Comment by GainfulShrimp** [comment]
I'm getting the same symptoms in 4.2.0, with InfluxDB as my Annotations source.  They show up fine in graph panels (as dotted lines with callouts at the bottom), but the table I've set to list them is totally empty.

**Comment by k-tooriyama** [comment]
I'm suffering from the same symptoms in 4.2.0 with Prometheus as @GainfulShrimp described above.
* Graph panels shows annotations
* Table panel doesn't show annotations, but only page numbers are appeared on the table.

![annotation_problem](https://cloud.githubusercontent.com/assets/15643109/25937562/279abd18-3667-11e7-9fe9-e91708460817.PNG)

Will this problem be fixed by #7487 ? (Or the problem I've found might be generated by other cause.)

**Comment by daniellee** [comment]
We will be releasing v4.3.0-beta1 this week that includes this fix.

**Comment by k-tooriyama** [comment]
I got it. I'll try again with the new version.
Thanks a lot.
