### ISSUE TITLE
[Bug] the grant of "grafana admin" to user@gmail.com (Google Auth) doesn't works well

### ISSUE THREAD

**Issue by jpereira** [grafana/grafana#8025]
Please include this information:
- What Grafana version are you using: 4.2.0
- What datasource are you using: mysql + google auth
- What OS are you running grafana on: Linux
- What did you do:

I Logged with an username@mydomain using the Google Auth than I changed this user to be "grafana admin", after that this user can't see all Orgs.

- What was the expected result: 

if I granted 'grafana admin' to the user@gmail.com that should see all Orgs as a default user "admin"

- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by jpereira** [comment]
I noted that the problem is related to the relation between the table `user` & `org_user`. because after change de relationship directly into the database. My user@gmail.com with ID4 now can see all Orgs.

![image](https://cloud.githubusercontent.com/assets/254448/24636391/4ad6af46-18b0-11e7-9c23-6f649c7da263.png)

**Comment by jpereira** [comment]
Grafana Team,

My current hack is:

```
INSERT INTO org_user (user_id, org_id, role) SELECT u.id, o.id,"Admin" FROM user u JOIN org o WHERE u.is_admin = 1;
```

**Comment by DanCech** [comment]
The google oauth integration doesn't confer any special permissions on users it creates.  This is a known limitation of the integration, not a bug.

**Comment by torkelo** [comment]
Also just because your user has `grafana admin` permission does not automatically give you access to all orgs. You have to add yourself to the orgs you want to manage first (you can the permission to do this from the admin users/orgs pages)

**Comment by robsonpeixoto** [comment]
Are there plans to add support to configure all users created by google sign up as admin?
Thanks

**Comment by drzraf** [comment]
Changing the `admin_user` key in the `security` section of the configuration does not make it either. This is an unexpected (and annoying) behavior.
