### ISSUE TITLE
Grafana fails to start after restart: rule title under the same organisation and folder should be unique

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#80269]
### What happened?

We have two instances of grafana (two VM instances) running with the MySQL database as the backend, all of the servers are working as expected but if we restart them, we get this error:
```
Error: ✗ migration failed: executing migration: migrate org 4: insert alert rules: a conflicting alert rule is found: rule title under the same organisation and folder should be unique
```
The issue is fixed after restarting the unit for a few times (20~30 times)

I tried this query on MySQL but didn't get any output:
```
SELECT
    title,
    COUNT(title)
FROM
    alert_rule
WHERE org_id=4
GROUP BY title
HAVING COUNT(title) > 1;
```

### What did you expect to happen?

More descriptive log to describe the issue, and why the issue happens and fixes randomly?

### Did this work before?

yes, we saw this error after enabling grafana UA on version 10

### How do we reproduce it?

1. No specific steps, just restart the grafana systems unit

### Environment (with versions)?

Grafana: 10.2.3
OS: centos7
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @yasharne,

Thanks for opening this issue.

Are you running the Grafana instances as High Availability setup as described in the documentation?
https://grafana.com/docs/grafana/latest/setup-grafana/set-up-for-high-availability/

**Comment by yasharne** [comment]
Hi @usmangt 
Yes, all instances are configured properly to support HA, we also have these new errors:
```
Error: ✗ migration failed: executing migration: migrate org 1: migrate alert 'XXX': invalid alert query A: invalid relative time range: {From:1m0s To:1m0s}
migrate alert 'YYY': invalid alert query A: invalid relative time range: {From:1m0s To:1m0s}
migrate alert 'ZZZ': invalid alert query A: invalid relative time range: {From:1m0s To:1m0s}
```
The point is, the error was correct, but when we fixed the issue in another running instance of Grafana, we still get this error on the new grafana instances, it seems it is reading the information from a table that has older data
NOTE: We use MySQL group replication and all the grafana instances are connected to the same master database instance (and this is guaranteed)

**Comment by yuri-tceretian** [comment]
It looks like the instances migrate over and over whereas it should happen only once when the first instance that points to the database starts. Please make sure that you do not have setting `force_migration` enabled.

**Comment by JohnnyQQQQ** [comment]
Closing this for now, if you still face any issues feel free to reopen it.
