### ISSUE TITLE
Cloudwatch Variable Editor: Have to click the + button twice to add the first filter

### ISSUE THREAD

**Issue by idastambuk** [grafana/grafana#80275]
### What happened?

When selecting EC@ instance attributes, we have to click the + button twice to add the first filter

https://github.com/grafana/grafana/assets/16140639/df901547-8ff5-4a60-995e-5df505dcd8a2

### What did you expect to happen?

Filter is added on the first click

### Did this work before?

Not sure

### How do we reproduce it?

1. Add a new CW variable
2. Select EC@ Instance Attributes from the dropdown
3. Try to add a new filter

### Environment (with versions)?

Grafana: 10.2.0
OS:
Browser: Chrome

### Grafana platform?

None

**Comment by wilguo** [comment]
Hi, is anyone currently working on this? If not, I'll take it on.

**Comment by idastambuk** [comment]
Hi @wilguo we're not currently working on it, you're very welcome to take it up! 🙂

**Comment by katebrenner** [comment]
closed with https://github.com/grafana/grafana/pull/83082
