### ISSUE TITLE
[Bug] v4.2.0 causing dashboards to pause/freeze or otherwise stop refreshing automatically

### ISSUE THREAD

**Issue by phateuk** [grafana/grafana#8028]
- What Grafana version are you using? 4.2.0
- What datasource are you using? Graphite
- What OS are you running grafana on? Centos 6
- What did you do? Used dashboards as normal
- What was the expected result? Dashboard auto-refreshes as normal
- What happened instead? Dashboard would pause, intermittently

So, we upgraded our Production Grafana environment to v4.2.0 last week. Over the course of the week or so since, I've had a number of reports of dashboards freezing. It appears to affect all browsers, primarily Firefox and Chrome which most people use and seems unrelated to any specific browser version.

It's not obvious the dashboard has frozen, all appears normal except that it's stuck on a specific time period regardless of the auto-refresh interval set (which we mostly have set to 1 min). Sometimes clicking into the body of the page and waiting a moment would force it to suddenly catch up, but often required a complete reload of the page or clicking the refresh button was required. It would often then work for a period of time i.e. a few mins or upto an hour or so, and then freeze again.

I rolled back Grafana from 4.2.0 to v.4.1.2 yesterday and am no longer able to replicate the fault and noone else has seen it since.

**Comment by torkelo** [comment]
Wonder if it's related to a change that disables refreshes when Grafana browser tab is not visible. 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/time_srv.ts#L138 

The tab/window visibility is determined by: 

 ```
(document.visibilityState === undefined || document.visibilityState === 'visible')
```

So maybe somehow this becomes false after a while. 

Do you know now long it takes for the freeze to happen, and what browser & version & OS was used?

**Comment by phateuk** [comment]
Hi Torkelo,

Yes it does appear to be related to minimizing the browser and/or switching tabs. Also, the guys who have come across the issue are the on-call engineers who often have a browser with multiple grafana dashboards open and a browser extension to rotate the tabs. It's affected Chrome and Firefox, various versions around the latest version, and across Windows 7 and 10.

**Comment by torkelo** [comment]
so it's caused by the browser plugin maybe? How long does it stay on each tab (compared to refresh interval)

**Comment by phateuk** [comment]
Nah I don't think so, a couple of colleagues experienced it without using any such tab rotate plugins. I figured when you advised there is a change in v4.2.0 which disables refreshing when the tab is not visible that we may have come across this more due to frequent tab switching.
Can this new functionality be optional? I know it's likely to cut down calls/resources on the backend, but that's not a concern of ours with hundreds of simultaneous users we can handle the volume, I'd much prefer for the dashboards to reload always in all circumstances.

**Comment by torkelo** [comment]
No it's not optional currently, what refresh intervals are you using?

**Comment by phateuk** [comment]
1 min pretty much exclusively on all dashboards as we have 60s metric refresh from most systems, a few are at 10s interval but these are few and far between

**Comment by torkelo** [comment]
I setup a couple of dashboards with 1min interval over night, no freeze or pause. (Ubuntu 16 & Latest Chrome).

Not sure what could be going on, will with a tab switcher next that switches tab every 2min (so a dashboard refresh is not missed).

**Comment by phateuk** [comment]
Thanks Torkelo,

If you're not able to replicate it I'll upgrade one of our instances to v4.2.0 again and try and replicate the problem

**Comment by torkelo** [comment]
yes, any details on what is required to make it freeze would help

**Comment by torkelo** [comment]
And if you do see it freeze, please open chrome dev tools console and look for any js errors.

**Comment by ihard** [comment]
I have same problem - grafana 4.2.0. with 4.1.2 - no problem with freeze page.

**Comment by rmsys** [comment]
Yes, same problem after update to 4.2.0. In 4.1.2 this problem don't oncurred.

I tried disable the flag "discard tabs" in Chrome, but not successful and same problem in Firefox.

**Comment by ihard** [comment]
in firefox development  error:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla

{"message":"Unauthorized"}

**Comment by torkelo** [comment]
@ihard seems unrelated, seems like your getting actual auth error. 

@rmsys just so we are all talking about the same problem. By freeze we just mean that the dashboard time range auto refresh has stopped? You can still manually trigger a refresh or interact with the dashboard / change dashboard? 

After a freeze anything in javascript console?

**Comment by torkelo** [comment]
I hope https://github.com/grafana/grafana/pull/8076  will fix this problem. With that change Grafana will directly refresh dashboard you it becomes visible  (tab focus)

**Comment by rmsys** [comment]
Tks torkelo!

Upgrade to last nightly build?
