### ISSUE TITLE
[Feature][Question] Is it possible to calculate percentage of total with Elasticsearch?

### ISSUE THREAD

**Issue by michal-dudek** [grafana/grafana#8029]
Grafana version:
- grafana-3.0.4-1464167696

Datasource:
- Elasticsearch

OS grafana is working on
- Red Hat, kernel 2.6.32-573.8.1.el6.x86_64

---

Dear Developers / Support,
First of all I want to thank you for developing Grafana ... it is really very good and powerful tool.

I have a distributed system of machines connected to computers from which I am publishing the statistics data. The information I am receiving include the following:
- number of devices in error physical state
- number of devices in okay physical state
- total number of devices connected

What I wanted to achieve is the graph with percentage distribution of healthy and faulty devices in time. What I have noticed is that, the values per computer publishing statistics are stable ... but when I combine all statistics from all computers I get a plot which is changing all the time.

The situation is probably like that because for the "global" graph I use averaging and the publishing time of each computer is different -- every 2 minutes from the time it was turned on and the system was booted. Please have a look at the attached images. When I change the interval aggregation time to higher values like 5m or 10m the graph is smoother, but still not representing the real data.

I would be very grateful for any suggestions.

Best regards,
Michal Dudek

P.S I have read the article by @daniellee but it was based on Graphite.

https://danlimerick.wordpress.com/2017/01/29/graphite-and-grafana-how-to-calculate-percentage-of-totalpercent-distribution/

Images
![grafana 1](https://cloud.githubusercontent.com/assets/20183359/24658920/7f6d094e-194b-11e7-9689-26d003cdaf85.png)
![grafana 2](https://cloud.githubusercontent.com/assets/20183359/24658921/7f82bf46-194b-11e7-942d-7c04cf3883d7.png)

**Comment by torkelo** [comment]
Elasticsearch does not currently support doing operations on the result of whole sub queries (like Graphite).

We hope to allow for some kind of "post tsdb" transformation & processing where you can combine and divide series results from queries.

https://github.com/grafana/grafana/issues/3677

**Comment by michal-dudek** [comment]
@torkelo okay, understood, thank you very much for your help!
