### ISSUE TITLE
Explore: Failed to call resource when attempting to change label in Builder mode

### ISSUE THREAD

**Issue by nhippe-ds** [grafana/grafana#80308]
### What happened?

After searching logs with Loki and wanting to change a label value (ie: environment) to something else, an error is received "Failed to call resource". The label values are not returned (dropdown just spins). See screenshot as example.
<img width="1368" alt="Screenshot 2024-01-10 at 10 38 10 AM" src="https://github.com/grafana/grafana/assets/77296759/5e17e0b9-2b20-460c-8b38-25a701e6c730">

Logs return the following:

```
2024-01-10T16:32:03.123567981Z stdout F logger=context userId=137 orgId=1 uname=xxx t=2024-01-10T16:32:03.123447886Z level=error msg="Failed to call resource" error="parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~\".*\" does not meet this requirement, but app=~\".+\" will" traceID=
```

This results in a broken query that requires a refresh, or removing all other label filters.

### What did you expect to happen?

The error message doesn't provide any clear context as to what happened and why. The label filter dropdown should present the same values that the initial query offered (ie: environment > all values). 

### Did this work before?

Unknown

### How do we reproduce it?

1. In Explore > Builder > choose Loki datasource, add label filters (ie: environment="produs", namespace!~"loki")
2. Run Query
3. Attempt to change first/initial label filter (ie: produs) to something else
4. Note error "Failed to call resource"

### Environment (with versions)?

Grafana: 9.4.3
OS: macOS
Browser: Chrome

### Grafana platform?

Other

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
Thank you for reporting this issue @nhippe-ds . It seems like it's related to the dropdown component in the Loki query builder within Grafana. I'll tag this issue for the Explore project team.

note for reviewer:

reproducible in play.grafana (explore tab)

![image](https://github.com/grafana/grafana/assets/45235678/c07d69ee-4a68-4db8-8996-25e4148fbf89)

**Comment by ifrost** [comment]
cc @grafana/observability-logs
