### ISSUE TITLE
Correlations: Permissions issues around Explore Editor

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#80304]
A person without permissions to see correlations still can see the element on the dropdown and go through the process to create a correlation, only to find out at the end they don't have permission.

The option should be hidden for people without permissions to create correlations.

**Comment by Elfo404** [comment]
I tried to have a look at this, and as long as i don't give a user `datasources:write` permission i can't get the extension to show up. Am i missing something?

**Comment by gelicia** [comment]
@Elfo404 - it was built to check for datasources:write since the beginning https://github.com/grafana/grafana/blob/main/public/app/features/explore/ExploreActions.tsx#L21

And I don't see anything in the channel about any other granularity about permissions. I think I might have made a note without checking but we will need more details to figure out how someone was able to start creating correlations without the ability to save them. Looking at the API layer, that is the permission for saving https://github.com/grafana/grafana/blob/main/pkg/services/correlations/api.go#L24

I'm closing this because past Kristina did not give enough details and I am not seeing anything in slack.
