### ISSUE TITLE
[BUG]Grafana shows less data than actual.

### ISSUE THREAD

**Issue by Abhishek321singh** [grafana/grafana#8031]
I am monitoring Vsize for one of the process on a machine.
I found Grafana is showing ~40MB lesser data than actual. However, when i exported the graph
into CSV using "Export CSV(series as columns)" option, i found data was very accurate but graph shows lesser data.

Any pointers?

Please include this information:
- What Grafana version are you using? Grafana v4.2.0 (commit: 349f3eb)
- What datasource are you using?Kairosdb
- What OS are you running grafana on?MAC
- What did you do? Tried monitoring Vsize of one process
- What was the expected result? Expecting the proper data which i am pushing to db[same data is present in the CSV exported from graph] but grafana shows less data ~40MB diff
- What happened instead?grafana shows less data ~40MB diff
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Yes, first step is to read how this article in how to troubleshoot metric query issues, which included guides for how to see the raw data returned by KairosDB, if you still think it's a bug please include the raw response from KairosDB and your graph settings https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50?u=torkel

**Comment by Abhishek321singh** [comment]
I am very new to Grafana..

I feel Kairos db is returning proper output

{"queries":[{"sample_size":9,"results":[{"name":"smtcore_vsize.mts.mediastreaming","group_by":[{"name":"type","type":"number"}],"tags":{"component_name":["mts_test"],"component_version":["7.6.4"],"environment":["sqa1"],"hardware":["x6"],"host":["198.18.120.197"],"instance_name":["main"],"ip":["198.18.120.197"],"name":["smtcore_vsize.mts.mediastreaming"],"network":["mts"],"organization":["MCDN"],"provider":["mediastreaming"],"region":["9019"],"release":["mts_4444"],"role":["lead_xbc"],"run_id":["04/03/2017 | 09h 16m 10s | abhishek_test"],"software_system":["mts_test"],"team":["sqa"],"type":["smtcore_vsize"],"unit":["unknown"]},"values":[[1491210971000,8.6214656E8],[1491211001000,8.6214656E8],[1491211032000,8.63199232E8],[1491211062000,8.63199232E8],[1491211093000,8.63199232E8],[1491211123000,8.63199232E8],[1491211154000,8.83183616E8],[1491211184000,8.83183616E8],[1491211214000,8.83183616E8]]}]}]}

Panel JSON o/p

{
  "aliasColors": {
    "smtcore_vsize": "#58D68D"
  },
  "bars": false,
  "datasource": "Lighthouse",
  "decimals": 1,
  "fill": 1,
  "grid": {},
  "height": "",
  "id": 5,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "max": true,
    "min": true,
    "rightSide": false,
    "show": true,
    "steppedLine": false,
    "total": true,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 1,
  "points": true,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 6,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "smtcore_vsize",
      "metric": "smtcore_vsize.mts.mediastreaming",
      "refId": "A",
      "tags": {
        "role": [
          "lead_xbc"
        ],
        "run_id": [
          "$run_id"
        ]
      }
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "transparent": false,
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "bytes",
      "label": "smtcore vsize lead xbc",
      "max": null,
      "min": 0,
      "show": true
    },
    {
      "format": "bytes",
      "label": "",
      "max": null,
      "min": null,
      "show": true
    }
  ]
}

Let me know if anything else i can check

**Comment by Abhishek321singh** [comment]
<img width="760" alt="screen shot 2017-04-04 at 10 45 42 pm" src="https://cloud.githubusercontent.com/assets/18096287/24669685/f8d698d0-1988-11e7-8562-eff425204558.png">

Graph shows lesser value

**Comment by Abhishek321singh** [comment]
<img width="1074" alt="screen shot 2017-04-04 at 10 45 49 pm" src="https://cloud.githubusercontent.com/assets/18096287/24669704/0a39569e-1989-11e7-8dfa-f3543f5b20cc.png">

Graph shows lesser value

**Comment by torkelo** [comment]
Looks right to me:

862146560/1024
=841940  (KiB)
841940/1024
822.20703125 (MiB)

If you you want a decimal unit switch unit to `data (Metric) -> bytes `
