### ISSUE TITLE
[Bug] Lockup in nightly

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#8033]
Please include this information:
- What Grafana version are you using?
4.3.0-7421pre1
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Run grafana
- What was the expected result?
Grafana stops responding after some time running
- What happened instead?
Should be working

Nothing in logs. Simply starts to timeout.

```
root@heimdall:~# curl localhost:3000
<a href="/login">Found</a>.

root@heimdall:~# curl localhost:3000/login
```

**Comment by daniellee** [comment]
Can you check the console in the Chrome Dev Tools, any errors there?

Does the api still work - http://localhost:3000/api/search

Is your database ok? Are you using sqlite?

**Comment by rlex** [comment]
Yep, sqlite.
No errors in dev tools.
Api seems to work, at least it returns "unathorized"

**Comment by rlex** [comment]
After further testing, it seems like 4.3.0-7410pre1 is not affected. All builds after it are affected.

**Comment by torkelo** [comment]
just installed grafana_4.3.0-7421pre1_amd64.deb with no issues. 

Can you describe more what your setup looks like? Number of dashboards, users, alerts, data sources etc. In what way does it lock up?

**Comment by rlex** [comment]
There is 2 orgs with around 15 dashboards in each (very similar - one org is basically staging) with 5 users.
I have ES, InfluxDB and zabbix datasources. 
DB is SQLite. No alerting configured.

**Comment by torkelo** [comment]
can replicate this here, takes a while but seeing the same on local build

**Comment by jasonafernandez** [comment]
Experiencing the same issue, it does take a little bit to appear. I was able to see this viewing grafana-server service status. Not sure if it's related. 

`grafana-server[8795]: 2017/04/05 17:01:57 httputil: ReverseProxy read error during body copy: context canceled`

**Comment by cederigo** [comment]
I'm also experiencing the same issue on Docker builds. (InfluxDB, SQLite)

**Comment by torkelo** [comment]
This should be fixed in recent nightly builds

**Comment by jasonafernandez** [comment]
Working well for me, upgraded to grafana_4.3.0-7461pre1_amd64. Thank you!

**Comment by rlex** [comment]
Can confirm it works for me as well. 
Looks like sqlite issue, so migration to pgsql/mysql is the way to go?
