### ISSUE TITLE
Influxdb: group tag variables followed by minus sign in Influxdb query alias are no longer substituded in legend

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#80355]
### What happened?

When I use group tags in the alias field of an influxdb query that are followed by minus sign, they are not expanded anymore in the legend, such as in the alias L$tag_line-$tag_signal in the screenshot below. The legend label (metric name) still contains the variable name $tag_line, only the second group tag is expanded. Escaping as $ tag\_line, $ {tag\_line} or ${tag\\\_line} does not work either, and the minus sign can also not be escaped with a backslash. Apparently only escaping with [[tag_line]] seems to work (see [influx query editor](https://grafana.com/docs/grafana/latest/datasources/influxdb/query-editor/)), but this type of escaping is discouraged (see [variable syntax](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/))
![image](https://github.com/grafana/grafana/assets/6523124/2f1c57d4-d055-4709-8fc9-eab9e567dea5)

### What did you expect to happen?

I expected the tag variable $tag_line in the alias $tag_line-$tag_signal to be expanded properly in the legend, to L1-rms_median, L2-rms_median and L3-rms_median. Since the minus sign can normally not be part of a variable name.

### Did this work before?

Before grafana 10.2.3, I could use group tags like $tag_line in the alias field followed by a minus sign. See the following screenshot when downgraded to grafana 10.2.2 where the group tag is correctly expanded to L1-rms_median, L2-rms_median and L3-rms_median in the legend:
![image](https://github.com/grafana/grafana/assets/6523124/f4268dbc-a872-4324-983f-499094d6b894)

### How do we reproduce it?

1. create influx query
2. use group by for one or more tags, e.g. sometag
3. use $tag_sometag in the alias field followed by a minus sign

### Environment (with versions)?

Grafana: 10.2.3
OS: Ubuntu 22.04.3 LTS
Browser: 21.0.1+build1-0ubuntu0.22.04.1~mt1 amd64

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

influxdb

**Comment by user45876** [comment]
Could this be a related issue? https://github.com/unpoller/unpoller/issues/653
In the linkes issue, dashboards stopped working in relation to variables as well, also since Grafana 10.2.3.

**Comment by bijwaard** [comment]
> Could this be a related issue? [unpoller/unpoller#653](https://github.com/unpoller/unpoller/issues/653) In the linkes issue, dashboards stopped working in relation to variables as well, also since Grafana 10.2.3.

Don't think it is related, in my case the queries work, but not all group tag variables in the alias are substituted in legend and query result metric names

**Comment by cfz** [comment]
i have the same issue. the square bucket ("[[]]") alias patten is not affected. only "$" style patten has the problem

**Comment by bijwaard** [comment]
I noticed that [[tag_line]] would work in the alias, but this style is [deprecated](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/) and discouraged and will be removed some time in the future.
