### ISSUE TITLE
Failed to send alert notification email

### ISSUE THREAD

**Issue by justlooks** [grafana/grafana#8035]
i install grafana-4.1.2-1486989747.x86_64 rpm package on my docker container

here is my smtp config
[smtp]
enabled = true
host = smtp.tqmall.com:25
user = mid
password = mypass
;cert_file =
;key_file =
skip_verify = true
from_address = my@gmail.com

[alerting]
# Makes it possible to turn off alert rule execution.
execute_alerts = true

here is my log error info

t=2017-04-05T03:38:00-0500 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="400 ERR.PARAM"
t=2017-04-05T03:38:00-0500 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="400 ERR.PARAM"
t=2017-04-05T03:38:00-0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=192.168.20.239 time_ms=2.081µs size=48

**Comment by torkelo** [comment]
```
host = smtp.tqmall.com:25
```

is that correct ?

**Comment by torkelo** [comment]
probably related to this issue: https://github.com/grafana/grafana/issues/7189

**Comment by justlooks** [comment]
yeah, the problem located in my mail smtp server ,when i change another smtp server ,it's worked fine!

**Comment by Hitesh3202** [comment]
Hi @justlooks  Can you please share your config for SMTP. I want to look through the host settings
