### ISSUE TITLE
Dashboards: Provisioned dashboards not available with anonymous access

### ISSUE THREAD

**Issue by atimin** [grafana/grafana#80351]
### What happened?

I use Grafana in a stateless Docker container with a few provisioned dashboards. I have enabled anonymous access, but  users can't see the dashboards without authorization. The dashboards are available  in the "Dashboards" folders but if you click on it , you will have the 404 error. 

If a user login at least once, the dashboards can be available without permissions. However, it ruins the idea of  anonymous access. Another problem, I use stateless containers and user must repeat the login operation after each deployment.

This is another report about the problem: https://community.grafana.com/t/trying-to-view-a-provisioned-dashboard-for-the-first-time/87830

### What did you expect to happen?

The provisioned dashboards must be available with anonymous access 

### Did this work before?

No

### How do we reproduce it?

1. Provision a dashboard according to the documentation
2. Enable anonymous access with the following env variables
    "GF_AUTH_ANONYMOUS_ENABLED=true}",
    "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer",
3. Clean configuration database to imitate the stateless approach
4. Restart grafana and try to open the dashboard without logging in 

### Environment (with versions)?

Grafana: 10.2.1
OS: Ubuntu 22.04 amd64
Browser:  Version 120.0.6099.71 (Official Build) snap (64-bit)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hi @atimin 

thank you for reporting this issue

Can you share the log files from Grafana after enabling anonymous access and after attempting to access the dashboards? 

Are there any messages in the browser console when the 404 error occurs? This could help us identify client-side issues.

Thank you

**Comment by atimin** [comment]
Unfortunately or not, I can't repeat this behaviour anymore. We updated Grafana up to v10.3.1 for some reasons and it works well now.  I'll close the issue and re-open it with the requested information if I encounter the error again.
