### ISSUE TITLE
Dashboards: Folder defaults to root folder when more than 1000 dashboard folders

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#80377]
### What happened?

When you have more than 1000 dashboard folders and go to the dashboard's settings page, the value of the dropdown for folder gets set to be the root folder.

<img width="647" alt="Screenshot 2024-01-11 at 9 30 27 AM" src="https://github.com/grafana/grafana/assets/20195316/eb3bfd5c-e9ee-40ee-816d-d013f577fecd">

It looks like the culprit of this is [here](https://github.com/grafana/grafana/blob/eb6420930122eee2d43617bf41668688c2f90ea2/public/app/core/components/Select/OldFolderPicker.tsx#L150C13-L150C13). The query to get all possible folder options has a limit of 1000.

### What did you expect to happen?

The dropdown should have the name of the dashboard's folder.

### Did this work before?

Probably not.

### How do we reproduce it?

1. Create more than 1000 dashboard folders.
2. When you go to the dashboard settings page, there is an api call to get the first 1000 dashboard folders. Make sure your dashboard's folder is not included in that response. I think they're ordered by name?
3. When you go to the dashboard's setting page, it's folder will be shown as `General` instead it's actual folder.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 9.4.9
OS: Mac
Browser: Firefox

**Comment by owensmallwood** [comment]
@saadnabs

**Comment by ashharrison90** [comment]
as josh said, this has been fixed in the new browse dashboards UI and the new nested folder picker

we've also delivered a separate feature toggle [here](https://github.com/grafana/grafana/pull/80461) that will allow enabling the new folder picker without enabling nested folders
