### ISSUE TITLE
Grafana Scene Tabs don't wrap or are useable past ~20 tabs

### ISSUE THREAD

**Issue by paulJonesCalian** [grafana/grafana#80389]
### What happened?

![image](https://github.com/grafana/grafana/assets/151241545/2027b2b4-3538-41ae-8ec4-df7f9b207e72)

I was working on creating procedural generated tabs (ie. From a loop), with the end goal of a user being able to graph values against each other at will, each tab could hold different sets of graphs and could be pulled up as desired.

The tabs numbers should go on and on up to 100, but unless you zoom out, the other tabs are completely accessible. I understand this is a niche case, but if tabs are expanded in the future, this could be a valid concern.

This is one of my first issues I've raised, so feel free to move this to "chore" or "feature" or whatever works better.

### What did you expect to happen?

1. There's a little button overlay on each side that allows the user to view tabs on the edges. (preferred solution)
2. There's a hard tab limit (but this wouldn't work on all screens)
3. The tabs wrap downward (Unideal, but alternative solution)

### Did this work before?

No

### How do we reproduce it?

1. Create over 20 tabs in Grafana Scenes
2. Try to access the last few tabs
3. Zoom out
4. Successfully access the last few tabs
5. Wish there was a better way

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1
OS: Linux
Browser: Chrome

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @paulJonesCalian,

Thanks for opening this issue.

Grafana's current latest stable version is 10.3.x and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).

**Comment by paulJonesCalian** [comment]
Tested in Grafana 10.4.2. Issues remains
