### ISSUE TITLE
[Feature request] More intuitive links

### ISSUE THREAD

**Issue by pzai577** [grafana/grafana#8038]
The UI for panel links (links from a panel to another dashboard or a direct link) are not particularly intuitive.

I am currently using Grafana version 4.1.1. In this version, the icon for the link is faint, off to the side, and requires the user to hover over it (and furthermore, not accidentally bring the mouse over the panel options immediately to the left of the link icon). Thus, it is not easy to 1) see that a link exists, 2) understand how to access the link, and 3) actually use the mouse go to the link.

The link UI Grafana version 4.0.1 is a little better regarding points 1 and 3 since the icon is darker and near the title, and there is more room for error with the mouse.

One possibility would be to use something similar to the current link for singlestat panels. Perhaps, if you click anywhere on the graph, a small link menu appears (as in version 4.0.1 for example). Then hovering the mouse over the panel at any time indicates that it can be clicked and show a link menu, and it would be very easy to use.

If not, could we get link UI that is more similar to the UI in version 4.0.1?

Thanks!

**Comment by torkelo** [comment]
yes, the panel links can be improved. But very tricky to make them non intrusive and distracting
