### ISSUE TITLE
Plugin installation pages not reliably showing up (grafana.com with Chrome)

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#80409]
### What happened?

See attached video of the issue. In some cases, a single F5 refresh is enough, in other cases I've tried clearing cache and hitting Shift + F5 20+ times with no luck. There appears to be some bug that causes the installation/uninstallation buttons to not load properly.

https://github.com/grafana/grafana/assets/26184427/80225b83-2ed2-4c91-b931-44e0bafa29f0

### What did you expect to happen?

The plugin install/uninstall button should show up immediately.

### Did this work before?

This has not worked for over a year on Chrome I believe.

### How do we reproduce it?

1. Use Chrome on Windows 10
2. Uninstall/reinstall a plugin on Grafana Cloud (I tested with Amazon Athena)
3. Check if the button loads immediately or not

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Cloud
OS: Windows 10
Browser: Chrome latest

### Grafana platform?

I use Grafana Cloud

**Comment by tolzhabayev** [comment]
@oshirohugo please take a look
