### ISSUE TITLE
Nested Folders: Unable to create sub-folders with the same name across different parent folders

### ISSUE THREAD

**Issue by apantw** [grafana/grafana#80408]
### What happened?

Error: `a folder or dashboard in the general folder with the same name already exists`

### What did you expect to happen?

Grafana allows this action

### Did this work before?

Not sure which version of Grafana this worked in before

### How do we reproduce it?

From Grafana UI,

1. Create two folders `Folder 1`, `Folder 2`
2. Create a folder `Sample` under `Folder 1`.
3. Create a folder `Sample` under `Folder 2` (This action will lead to an error)

### Environment (with versions)?

Grafana: 10.2.3
OS: Mac
Browser: Chrome

### Grafana platform?

Docker

**Comment by jdmaloney** [comment]
I am able to reproduce this error as well on Grafana v10.2.3, browser is Safari, Grafana OSS on RHEL 8 (via RPM install).  I have the following features enabled via toggle:

```
[feature_toggles]
nestedFolders = true
nestedFolderPicker = true
```

I happened to sit down today to test out this feature (we're really excited to use it) but this puts the deployment of it on hold for us.

**Comment by JustNZ** [comment]
Even if you try to create the nested Folders with API/Terraform it doesn't work.
Seems like the Folder Name is the Unique Identifier and not the UID itself

**Comment by tonypowa** [comment]
hi @apantw  @jdmaloney  @JustNZ 

Thanks for reporting (and adding info to) the issue 

The issue is reproducible .
The browser inspector throws a 409 (conflict) error
`POST
http://localhost:3000/grafana/api/folders
[HTTP/1.1 409 Conflict 4ms]`

error in logs:

```
logger=context userId=1 orgId=1 uname=admin t=2024-02-08T09:07:34.072152879Z level=info msg="Request Completed" method=POST path=/api/folders status=409 remote_addr=192.xx time_ms=2 duration=2.590503ms size=91 referer=http://localhost:3000/grafana/g/dashboards/f/df4c9135-dbbb-4581-9319-19b1d9e15ffb/ handler=/api/folders/
```

**Comment by tonypowa** [comment]
cc @grafana/grafana-frontend-platform
