### ISSUE TITLE
Create variables using pyroscope data source. How to write regex

### ISSUE THREAD

**Issue by hexiang1219** [grafana/grafana#80413]
### What happened?

Want to create a variable for service_name using the metrics provided by the pyrscope data source. I don’t know how to write regex

![图片](https://github.com/grafana/grafana/assets/34543240/740dfe73-c4d4-4b6d-925a-5057b248b6e5)
![图片](https://github.com/grafana/grafana/assets/34543240/be91550f-0b39-4fc4-9f22-e2b3c8510dec)

### What did you expect to happen?

Is there a missing box to fill in the query statement? My understanding is that regex is a regular match for the results.

### Did this work before?

none

### How do we reproduce it?

none

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by aocenas** [comment]
Hey @hexiang1219, is it possible you are running older version of Grafana? We added support for template variables for Pyroscope in 10.2 https://grafana.com/blog/2023/10/24/grafana-10.2-release-grafana-panel-title-generator-interactive-visualizations-and-more/#:~:text=Use%20template%20variables%20with%20the%20Grafana%20Pyroscope%20data%20source&text=The%20Grafana%20Pyroscope%20data%20source%20now%20supports%20template%20variables.,and%20instantly%20preview%20their%20values.
