### ISSUE TITLE
Annotations: Library Panel: PanelId changes at every page reload so my annotations disappear

### ISSUE THREAD

**Issue by Maja0108** [grafana/grafana#80417]
### What happened?

When I reload Grafana Dashboard with library panels my annotations disappear or reappear. It is doesn't matter if I send annotations via HTTP API or I put on with my hands. After some research I realized that  by every reload of the page the panelId changes. 
Moreover I am not able to share a particular library panel because if I copy a valid link, in the next browser it says the "panel not found".

### What did you expect to happen?

As earlier in 9.3.x, panelId should change only if new panel is added to the dashboard, or new library panel. 
If I unlink library panels then the panelId does not change with page reload. But this couldn't be a solution as we use at least 10 library panels per dashboard. 

### Did this work before?

In 9.3.x it worked perfectly. Nothing changed in dashboard json only there was an upgrade from 9.3.x to 10.2.3. 

### How do we reproduce it?

1.Create a dashboard with at least 3-4 library panels (1 library panel with 3-4 child) 
2. Add an annotation to the 2nd, 3rd... panel (not to the mother panel)
3. Check the panelId
4.Reload the page completely
5. Annotation in most cases disapper
6. Check panelId again
7. They will differ.

### Is the bug inside a dashboard panel?

Panel works perfectly, only annotations are problematic in library panels.

### Environment (with versions)?

Grafana: 10.2.3
OS: Win 11
Browser: Edge (v. 120) and Chrome (v.120)

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @Maja0108 
thanks for reporting this issue

could you safely share the JSON of your dashboard so we can try to reproduce your scenario as accurately as possible?
Thank you!

**Comment by Maja0108** [comment]
@tonypowa How can I safely share the dashboard JSON?
