### ISSUE TITLE
[Feature request] Add an option to attach graph image link in Pushover notification

### ISSUE THREAD

**Issue by jpeg2600** [grafana/grafana#8043]
As asked by @devkid in [#8006](https://github.com/grafana/grafana/issues/8006), I open an issue to request a new feature. 

Would it be possible to add an option to attach the link to the rendered graph uploaded to S3 in a Pushover notificaiton? The [webhook](http://docs.grafana.org/alerting/notifications/)  outputs the info variable imageUrl, so I guess that the info is already somewhere accessible. 

`{
  "title": "My alert",
  "ruleId": 1,
  "ruleName": "Load peaking!",
  "ruleUrl": "http://url.to.grafana/db/dashboard/my_dashboard?panelId=2",
  "state": "Alerting",
  "imageUrl": "http://s3.image.url",
  "message": "Load is peaking. Make sure the traffic is real and spin up more webfronts",
  "evalMatches": [
    {
      "metric": "requests",
      "tags": {},
      "value": 122
    }
  ]
}`

I use Grafana to display the temperatures of a very sensitive environment . A quick peak on the graph when there's an alert would be useful on mobile and it loads quicker. The curve of a broken furnace and the one of a door left open is very different and tells at what speed we must rush to the site.

A simple link attached to the message would work fine.  Thanks!

**Comment by devkid** [comment]
Just as a preliminary comment: I hope you don't rely on Pushover notifications in Grafana for critical situations. Currently, the Pushover plugin only tries to execute the API call once and doesn't retry if it fails (e.g. when the API server is down or some other reason).

**Comment by jpeg2600** [comment]
@devkid I have an homemade gateway that sends the alert as a SMS but I would like to only use pushover instead for the simplicity of it... Do you have any other suggestion?

**Comment by devkid** [comment]
Nope, my comment was just to underline that Pushover notifications in Grafana are not reliable in terms of repeat-until-delivered, which should be considered for critical situations. It's totally up to you how to handle your alerts :)

**Comment by jpeg2600** [comment]
I understand. Thanks for bringing up the concern. Both your notification plugin and pushover are probably more reliable than my homemade tool anyway!

I wish I could help out and add the functionnality myself, but I lack the time to learn how to use Github, the language and how everything works together. 

Are you planning on adding the retry functionnality? I wonder if other notification plugins does that.

**Comment by devkid** [comment]
Looks like so:

![screenshot_20170409-202153](https://cloud.githubusercontent.com/assets/1257263/24839855/4dabc556-1d62-11e7-84d5-e6270abf97e4.png)

**Comment by jpeg2600** [comment]
Hey great work there @devkid ! I can't wait to try this out. Should I close the issue?
