### ISSUE TITLE
The navigation using breadcrumb doesn't work for variable edition

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#80434]
Testing the variables edit flow and I noticed some issues with navigation after editing the variable. Steps to repro:

1. Go to edit mode
2. Go to variable edit
3. Go back to list
4. Try navigating back to the dashboard using Breadcrumbs - nothing happens

**Comment by Sergej-Vlasov** [comment]
Issue was resolved by someone else while I was investigating the cause
