### ISSUE TITLE
S3 image upload lost the ability to upload to a directory

### ISSUE THREAD

**Issue by arodland** [grafana/grafana#8045]
Prior to 4.2.0, this config worked:

```
[external_image_storage.s3]
bucket_url = https://bucketname.s3.amazonaws.com/grafana_alerts
access_key = XXX
secret_key = YYY
```

and the images would be uploaded inside the `grafana_alerts` directory of `bucketname`.

After #7058, the path component of the URL is completely ignored, and grafana tries to update into the root of the bucket. In my case, the AWS credentials I was provided only have write access inside of the subdirectory, so all of the uploads now fail and all of my alerts have no graphs.

**Comment by aedahl** [comment]
Can confirm.

I have the same setup as @arodland, with the write access inside of a subdirectory - all of the uploads (I am using the Slack webhook integration) now fail with the error "Could not find bucket setting for image.uploader.s3".

I will not be available over the weekend, but if there is any way I can help once the next week rolls around, let me know.

**Comment by aedahl** [comment]
@torkelo Please forgive the double-post, but in light of the assumed scope of issue #8250, would the fix for this defect also be a part of 4.3.0?

**Comment by torkelo** [comment]
yes, everything in master will be in 4.3

**Comment by aedahl** [comment]
@torkelo Thanks for the reply - I didn't see this defect (8045) assigned to a milestone - that's why I was asking.

**Comment by torkelo** [comment]
closing this as it looks to not be relevant anymore
