### ISSUE TITLE
Explore: Screen is flickering when moving mouse on loki logs on firefox

### ISSUE THREAD

**Issue by Solvero** [grafana/grafana#80455]
### What happened?

When I move mouse on loki logs almost whole page flicker (The part with Run Query, Live buttons to the bottom).
I don't have this problem when I use chrome or Vivaldi browser.

### What did you expect to happen?

Page should not flicker/refresh? when I move mouse.

### Did this work before?

I think it worked well in older version of grafana but unfortunatelly i dont have numbers to tell.

### How do we reproduce it?

1. Open grafana loki logs explorer(use firefox)
2. Move mouse over the log records. It should flicker.

### Environment (with versions)?

Grafana: v10.2.2 
OS: Ubuntu 22.04.3 LTS
Browser: Firefox 121.0.1

### Grafana platform?

I don't know

**Comment by tonypowa** [comment]
hi @Solvero 

thanks for the report

Can you add a screen recording where we can see the flickering happening? Also please provide any console logs that are output in Firefox's developer tools when the flickering occurs.

Lastly, could you clarify if you are running Grafana locally or on cloud?

**Comment by Solvero** [comment]
Hey @tonypowa 

Seems that few days ago we have upgraded Grafana to 10.3.1. I don't see this problem anymore.
