### ISSUE TITLE
 [Feature request] Add Favorites to Org Selection

### ISSUE THREAD

**Issue by trumpetsherald** [grafana/grafana#8046]
It would be really nice if the Org selector would remember my most commonly used orgs or if I could mark orgs as a favorite and display those. The filter makes selecting orgs a pain because I now have to type the name of my org to get it to show up.

Please include this information:
- What Grafana version are you using? 4.2
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Ubuntu

**Comment by torkelo** [comment]
We are going to add user groups and permission ACLs to data sources, dashboards, and dashboard folders. The organization feature (that many use due to lack of user group support) is not something we currently plan to expand on.
