### ISSUE TITLE
error="remote error: tls: handshake failure"

### ISSUE THREAD

**Issue by ivishnu7** [grafana/grafana#8047]
- What Grafana version are you using?
4.2.0. We installed Percona Monitoring Management (PMM) version 1.1.2. It includes the Prometheus data source, grafana in docker. I installed that docker image. 
- What datasource are you using?
Prometheus. 
- What OS are you running grafana on?
CentOS release 6.8 (Final)
- What did you do?
I have configured SMTP mail alerts as followed and testing mail alerts. Got the followed error. Is there any mistakes Am I doing in grafana.ini?

#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = smtphost.qualcomm.com:25
user =
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password =
cert_file =
key_file =
skip_verify = true
from_address = admin@grafana.localhost
from_name = Grafana

t=2017-04-05T21:15:52+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[c_vvard@qualcomm.com]
t=2017-04-05T21:15:53+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="remote error: tls: handshake failure"
t=2017-04-05T21:15:53+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="remote error: tls: handshake failure"
t=2017-04-05T21:15:53+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 **remote_addr=127.0.0.1** time_ms=66ns size=48

- What was the expected result?
I have to receive test mail.
- What happened instead?
Getting TLS handshake failure error.

**Comment by torkelo** [comment]
may be related to this issue:

https://github.com/grafana/grafana/issues/7189

**Comment by ivishnu7** [comment]
Mailing notification is working if I am using localhost:25 without TLS, but not for smtphost.gmail.com:25 without TLS.  

Is it expected to not use TLS for localhost (localhost:25) and to use TLS for non-localhost (smtphost.gmail.com:25)?

**Comment by torkelo** [comment]
gmail is expecting TLS so is trying renegotiate to TLS. This is not something Grafana supports (as it's not recommended), try using gmails TLS port
