### ISSUE TITLE
OpenTSDB: Improve check for template variable usage (alerting)

### ISSUE THREAD

**Issue by dbcook** [grafana/grafana#8048]
Grafana 4.2.0, OpenTSDB data source

On the advice of [pdf](https://github.com/pdf) I am submitting this as a separate issue; I initially thought it fell under [6557](https://github.com/grafana/grafana/issues/6557).

We have a graph panel with a template var dropdown for selecting the metric downsample interval, i.e. the downsample field is "$interval". The regular plot works fine and the template dropdown has the intended effect.

Attempting to create any alert from this causes a query error 400 when you click the test condition button, regardless of what alert conditions you set.

Changing the downsampling to a normal literal value such as "1m" allows the alert to work.

Expected behavior would be that Grafana would tell you that template vars are disallowed in the metric downsample field straightaway when you try to create the alert.  More generally, it should check for template vars in any field that could make its way into the alert query since the same multiplicity issues discussed in 6557 are in play anywhere that template vars are used.

**Comment by torkelo** [comment]
Grafana does check for template variables, for Graphite and InfluxDB this is quite easy as the query is a single string. But with OpenTSDB its a lot harder as the query model is much more complicated.

**Comment by hugohaggmark** [comment]
Confirmed this on Grafana v7.3.1 (6668161a88). Adding it to @grafana/observability-squad board.

**Comment by gtk-grafana** [comment]
If this is still an issue, create a new issue, alerting has completely changed since Grafana 4.2
