### ISSUE TITLE
[improvement] When we search for "Grafana API" we don't have the right page

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#8049]
Hi,
I noticed (and some months ago you talked about that with me in an issue) that when we search in Google for "Grafana api" and we take the first link it's not the right documentation.

<img width="612" alt="capture d ecran 2017-04-06 a 07 32 40" src="https://cloud.githubusercontent.com/assets/22610050/24739224/41b94cce-1a9b-11e7-82e6-724185ef70f0.png">

The 2nd link is the new documentation but the first one is an old documentation.

Am I right ?

Thank you for your good work !

**Comment by torkelo** [comment]
pushing redirect rule now, thx for informing me!
