### ISSUE TITLE
Condition: Eval: false, Query Returned No Series (reduced to null/no value)

### ISSUE THREAD

**Issue by suyanL** [grafana/grafana#80517]
grafana version:7.5.17,In the alarm configuration, Condition configures query (now-10m, now). Click Test rule. The error message is Condition: Eval: false, Query Returned No Series (reduced to null/no value), but the query (10m, now) response is normal. What's the difference between these two configurations?
![image](https://github.com/grafana/grafana/assets/64967836/45d50a00-0392-436e-b483-3859dd93b6d7)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by tonypowa** [comment]
hi @suyanL 

Thanks for reaching out. It seems your reported issue is more of a question, better suited for our [community forums.](https://community.grafana.com/) Also, note that the version you're using is unsupported. For bug reports or feature requests on a supported version, please submit a new issue.
