### ISSUE TITLE
[Bug] Percentage calculated wrong

### ISSUE THREAD

**Issue by roelywoely** [grafana/grafana#8051]
Version: 4.2
Datasource: CloudWatch
OS: Docker container on Ubuntu

I added 2 metrics:
- ResultsPageLoaded (the number of times a results page has loaded or refreshed it's results)
- SearchFormSubmit (the number of times a search form has been submitted)

I want to display a line graph of these metrics in percentages (by checking both the Stacked and Percentage checkboxes in the Display tab). But the calculation is wrong. Example, for a certain on a certain moment in time I have this:
- ResultsPageLoaded: 25
- SearchFormSubmit: 5

I expect the line position to be at ((5 / 25) * 100 = ) 20% but the line is actually at ((5 / (25 + 5)) * 100 = ) 16.67%, probably because I have to enable the Stacked option before I can enable the percentage option. How can this be fixed?
When I Google for percentage I see all kinds of solutions for dashboards using Graphite, but I'm using CloudWatch as a datasource.
I also want to display this in a graph over time, so a singlestat panel is not an option here.

**Comment by sunker** [comment]
@roelywoely sorry for late reply. Do you still have this problem?

**Comment by daniellee** [comment]
Closing this as no reply and this bug is 3 years old.
