### ISSUE TITLE
[Feature request] Kibana 3 style filter narrowing on click for Elasticsearch

### ISSUE THREAD

**Issue by jonesn** [grafana/grafana#8052]
Kibana 3 offered a feature where you could click on a magnifying glass beside a term in a table to apply a filter that would further narrow the results returned from a query.

It would be great to have this in Grafana.

Example screenshot below.

![kibana_narrowing2](https://cloud.githubusercontent.com/assets/277481/24744954/ed930c76-1b07-11e7-8d52-cc8a0e45d7da.png)

**Comment by daniellee** [comment]
In Kibana 3, this was great for filtering logs to see how often an error occurred. In Grafana, where would you want to see this? In the table panel? Would this be for all data sources?

**Comment by jonesn** [comment]
The magnifying glass would be in the table panel and if possible the filter would be applied across all Elastic data sources in use on the dashboard. 

A visual indication of the filter being applied could be added to the header section of the dashboard where the template variables go now (ala Kibana 3).

**Comment by chrisjschultz** [comment]
This would be great. We are kinda stuck at the moment as this is one of the Kibana3 features we need. We want to move to Grafana and away from Kibana and having this would allow us to do so.

**Comment by torkelo** [comment]
this is now merged to master can be tested in latest nightly build! 

For a video demo of the feature: 
https://twitter.com/grafana/status/895000347630084096

**Comment by torkelo** [comment]
please test and give feedback on how it works!

**Comment by arienchen** [comment]
Is there an option to disable by column, 
not each column required to be filtered.

**Comment by IshaGirdhar** [comment]
Can we turn off ad-hoc filters in the table, we don't want to filter in our use case.

**Comment by marefr** [comment]
@IshaGirdhar currently you can't. Please open a feature request if that's something you want.
