### ISSUE TITLE
Grafana/ui: add supporting timezone to Date Pickers

### ISSUE THREAD

**Issue by asimonok** [grafana/grafana#80529]
**Why is this needed**:

We use DateTimePicker - https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-datetimepicker--basic to show and allow to enter date within the panel. There is needed to show dates in the selected dashboard timezone. By the current implementation we adopt dates to the browser timezone (add diff to dates between utc, browser and dashboard timezones) to show dates for user in the dashboard timezone.

**What would you like to be added**:

Add additional parameter `timezone` to date picker components (DateTimePicker, DatePicker, TimeOfDayPicker, TimeRangePicker,etc) which will show dates in defined timezone or browser timezone by default (current behavior).

Example of usage
```
<DateTimePicker timezone="utc" />

<DateTimePicker timezone="browser" />

<DateTimePicker timezone="any dashboard timezone " />
```

Output results for ISO String: `2024-01-15T08:35:11.000Z`
In browser timezone (+1h): `1/15/2024, 9:35:11 AM`
In utc timezone (0): `1/15/2024, 8:35:11 AM`

**Who is this feature for?**

Plugin Developers

**Comment by Clarity-89** [comment]
Hi, for `DatePicker` and `TimeOfDayPicker` you can provide timezone-aware date/time by using the utils from `@grafana/data`, e.g., 
```ts
<TimeOfDayPicker
    value={dateTimeForTimeZone(getTimeZone({ timeZone: 'America/New_York' }), date)}
/>
```
`TimeRangePicker` already supports custom timezones. 

For `DateTimePicker` you can set timezone resolver that would return a specific timezone:
```ts
import { setTimeZoneResolver } from '@grafana/data';

setTimeZoneResolver(() => 'America/New_York');
```
This might not be optimal a it'll set the timezone globally, so will need to be reset outside of dashboard. We'll need to check if it's easy to add a custom timezone support to the `DateTimePicker`.

Hope this helps!

**Comment by asimonok** [comment]
`setTimeZoneResolver` works fine.

timeZone for DateTimePicker doesn't work properly - the picker still shows date in browser timeZone.

```
<DateTimePicker date={dateTime('2024-07-12T06:36:46.580Z')} timeZone={timeZone} />
```

America/Adak
<img width="820" alt="Screenshot 2024-07-12 at 09 33 57" src="https://github.com/user-attachments/assets/caba0545-6373-4dcb-99f7-759e007971ff">

utc
<img width="824" alt="Screenshot 2024-07-12 at 09 33 30" src="https://github.com/user-attachments/assets/371fd316-4c14-43d4-b063-0751af6a7f96">

**Comment by Clarity-89** [comment]
This change will be released in grafana/ui 11.2.0, which is not out yet. You can test it locally on the latest main meanwhile.

**Comment by asimonok** [comment]
@Clarity-89 tested on `^11.2.0-186891`

**Comment by Clarity-89** [comment]
Are you sure the component gets the updated time zone when you change it in the dashboard's timerange picker? If you do
 ```tsx
  <DateTimePicker
              minDate={element.min ? new Date(element.min) : undefined}
              maxDate={element.max ? new Date(element.max) : undefined}
              date={dateTime()}
              timeZone={'America/Adak'}
/>
```
You can see that the correct date time is displayed in the picker.

**Comment by asimonok** [comment]
Yes, the component gets the updated timeZone. 
I realized I used not latest grafana version. On the main version timeZone works properly

Thanks!
