### ISSUE TITLE
Docs: Heatmap docs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8054]
We need docs for the new heatmap panel

**Comment by towolf** [comment]
Yeah, I'm enthusiastically playing with it and still quite puzzled.

* How does time binning in ES query interact with histogram X binning? The numbers never seem to add up
* What is the difference between "Timeseries" and "ES histogram" mode?
      * For the latter the "Histogram" Group-By seems to be required, but the resulting visual is hard to interpret
      * Do I need to put "Count" as the Metric in the "ES histogram" mode?

Docs with screenshots would be highly appreciated.

**Comment by torkelo** [comment]
> How does time binning in ES query interact with histogram X binning? The numbers never seem to add up 

Not sure I understand? Histogram X is the time axis, which is defined by ES date histogram. 

> What is the difference between "Timeseries" and "ES histogram" mode?

Time series mode will take all time series and all data points and divide them into y & x buckets of specified (or auto) size.
 
ES histogram (renamed this just now to Time series pre-bucketed). this mode has nothing specifically to do with ES but with time series that are prebucketed. So if you add a Histogram aggregation above the Date Histogram aggregation you will get one time series back per interval in the histogram aggregation. So the heatmap can just get the Y buckets from the series name value.  In this mode the series names must be a numeric value representing the max or min of bucket range. 

> Do I need to put "Count" as the Metric in the "ES histogram" mode?

You can use any ES metric aggregation or Doc Count

**Comment by towolf** [comment]
>>How does time binning in ES query interact with histogram X binning? The numbers never seem to add up
> Not sure I understand? Histogram X is the time axis, which is defined by ES date histogram.


Does not seem to be the case:

![image](https://cloud.githubusercontent.com/assets/345210/25341123/1c1aa0d2-2908-11e7-8c37-7c28829a1bca.png)

![image](https://cloud.githubusercontent.com/assets/345210/25341129/23010a3a-2908-11e7-88b8-3b493c14e93d.png)


And If I reset the bucket width to `auto` and set something longer in the date histogram, it looks like non-sense, with Count 1 in each bucket.

![image](https://cloud.githubusercontent.com/assets/345210/25341204/67e76216-2908-11e7-8339-9bbe3c4c80b6.png)

**Comment by torkelo** [comment]
not sure I understand, looks correct to me. what is that you find puzzeling ?

**Comment by torkelo** [comment]
For the second example of course the count is going to be 1 that is very easy to understand, you only get one 1 for each hour bucket. 

Your selecting the average of queueTimeMs1  grouped into hour buckets (so you get 1 value per hour, not very good for heatmap panel)

Try this: 
Average queeTimeMs1
Group by Histogram  (specify a interval for example 100 for 100ms y-axis buckets)-
Group by Date Histogram (specify interval 15min to 1h depending on how big the x-axis buckets you want)

Change format to ES histogram (meaning time series per bucket, only works if you have histogram followed by date histogram)

**Comment by torkelo** [comment]
Sorry this is better:

Metric: Doc Count
Group by Histogram `queeTimeMs1` (specify a interval for example 100 for 100ms y-axis buckets)-
Group by Date Histogram (specify interval 15min to 1h depending on how big the x-axis buckets you want)

Query in human langauge
Get the doc count for each histogram bucket based on the value of queeTimeMs1 and group by date buckets

**Comment by towolf** [comment]
Thanks for your tips,

my intuition was already that I want to use the pre-bucketed "ES histogram" mode, but I ran into strange issues that made it seem like it didn't work as expected.


In the regular "Timseries" (now "TS") histogram my issue is that I need the "Date Histogram" Group-By at all. Ideally, I want to feed raw data points into the heatmap bucketer, and not pre-bucketed.  So I set this to 1s now and that seems to work fairly well. But 1s is not the same as "raw".

**Comment by towolf** [comment]
So, this seems to kind of work:

![image](https://cloud.githubusercontent.com/assets/345210/25355332/8acf45c2-2936-11e7-8b12-778649071018.png)

But these settings here mostly seem to have no effect:

![image](https://cloud.githubusercontent.com/assets/345210/25355358/a3262e74-2936-11e7-9c2e-20a50362922b.png)

And the "log" options looks a bit strange when enabled.

**Comment by torkelo** [comment]
If you have pre bucketed data (by ES, which is 100x faster than returning millions of raw data points to Grafana). then most bucket options wont have an effect. We should hide those when that format is chosen.
