### ISSUE TITLE
Add custom command to Command Palete

### ISSUE THREAD

**Issue by houtaru** [grafana/grafana#80562]
**Why is this needed**:
Use Command Palette to jump into the dashboard with a specific template variable value.

**What would you like to be added**:

Ability to add custom commands to Command Palette. Therefore, we can jump into the selected dashboard with the input value of the template variable(s).
e.g.: A dashboard `K8S` with a variable called `node`. Use the command palette and type `k8s:node=20.11.3.44`, we will jump into the dashboard with the variable `node` has value equal to `20.11.3.44`.

**Who is this feature for?**
Grafana Command Palette

**Comment by eledobleefe** [comment]
Hi @houtaru
First of all, thanks for your suggestion. 
After discussing this with the team, we think it's a little too specific to appear as a global action in the Command Palette. 
Although we're proceeding to close this issue, we may reevaluate this idea in the future.
