### ISSUE TITLE
[Feature request] Configurable csv export datetime format

### ISSUE THREAD

**Issue by cederigo** [grafana/grafana#8058]
It would be nice if the format of the time column in the csv export was configurable. 
The current format (ISO86001, ex: “2017-04-06T14:13:19.683Z”) can’t be parsed by Excel. Importing csv data is a frequent use case of mine.

I’m willing to make a pull request. Here is my implementation idea:
  - Add config section “export” (Or “csv-export”?)
  - Add config key “date_format”. Default value: “YYYY-MM-DDTHH:mm:ssZ” (ISO86001)
  - Use config value in “file_export.ts” with moment().format(..)

Any chance you accept such a pull request?

Cheers, Cédric

**Comment by cederigo** [comment]
Any chance you accept a PR as described above?

**Comment by daniellee** [comment]
Yes, we would accept a PR for this.

After some discussion with Torkel, we think the design should be like this:

1. Combine the two CSV options in the context menu to one `Export CSV`option:
![image](https://cloud.githubusercontent.com/assets/434655/25428973/bb84b5de-2a77-11e7-84d2-60f2161c28f3.png)

2. When the user clicks on the new `Export CSV` option, show a modal with the following:
    - Radio button with the following options: `Export Series as Rows` or `Export Series as Columns` 
    - Field for `Date Format` where the default value is YYYY-MM-DDTHH:mm:ssZ

Look at the Share options or Save as option to see an example of how to make a modal.

There are several issues connected to this:
- #2401
- #1855

Looking forward to the PR. Thanks for taking this on!

**Comment by Flyweightt** [comment]
Unix epoch timestamps would be great.

**Comment by daniellee** [comment]
Fixed by #8282

**Comment by daniellee** [comment]
This could be enhanced further. The table panel does not format time columns when exported to CSV. This is a bit trickier as there might not be a time column in the table data or there might be multiple time columns.
