### ISSUE TITLE
datasource  /query function -  asynchronous promise

### ISSUE THREAD

**Issue by dk25094** [grafana/grafana#8061]
Dear Grafana Experts,
I am trying to implement a bigquery plugin and new to angularJS.
I am trying to implement /query function, I parse my req object, but my backend fetch to bigquery is slow, so I use a promise syncQuery below.

The issue is that the /query is expecting an immediate reply with the req object ( target and datapoints)

However I use a promise call to the bigquery backend and not clear on how to return the res object when the .then executes upon successfully retrieving the BiqQuery Data.
I used a debugger, set a breakpoin in the .then and verified data and format is correct. However I dont know why Grafana does not display when the res.json(bqResult) returns.

Any suggestions very much appreciated. Below is my code snippet.

app.all('/query', function(req, res){
  setCORSHeaders(res);
 
..
..
 ,,,
 pull out target from req()
..
   syncQuery(sqlQuery1).then(
       function(results) {
           var bqResult = getdata(results,slo_target[0]);
          printResult(bqResult.Datapoints); < - verified results are correct and formated as per grafana docs
           res.json(bqResult);
           res.end();    <-------------------------------  this is never displayed in the Grafana chart
       },
       function(error) {}
   );

  //res.json(bqResult);
  // res.json(bqResult);    < --- if I comment out this return, bqResult has not yet received data from BiqQuery
  //res.end();
});

**Comment by torkelo** [comment]
Grafana expects most functions return an async promise, (the is returned immediate but it can be fulfilled at any time in the future). 

return an angular $q promise that when fullfilled returns an object with a a data property that contains your series
