### ISSUE TITLE
[Bug] Links on panels low on the page do not display properly

### ISSUE THREAD

**Issue by pzai577** [grafana/grafana#8062]
Please include this information:
- What Grafana version are you using? 4.1.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Windows

I have a dashboard with several rows, and each row has a panel with links. The links for the first several rows work fine (though, as discussed in [another issue](https://github.com/grafana/grafana/issues/8038), the UX could use work). However, the later rows do not have working links.

<img width="1416" alt="screen shot 2017-04-06 at 3 05 39 pm" src="https://cloud.githubusercontent.com/assets/20449109/24771179/8efcd156-1ada-11e7-9cd8-4462cee7d1b7.png">

As we can see, the panel in row 2 has working link. Also note that the bottom of the screen is a little below -0.5 in row 3.

<img width="1394" alt="screen shot 2017-04-06 at 3 06 53 pm" src="https://cloud.githubusercontent.com/assets/20449109/24771210/b2823a30-1ada-11e7-93bc-decc306289ec.png">

As we can see, the link for the panel in row 4 (titled 'Panel Title') does not work properly. The link appears right above where the bottom of the screen would be (at -0.5 in row 3), if we were still scrolled up to the top as we were in the previous image. Subsequent rows also have their link appear here.

Thanks for looking into this! Let me know if I can provide any more information.

**Comment by torkelo** [comment]
fixed in 4.2

https://github.com/grafana/grafana/issues/7708

**Comment by pzai577** [comment]
Oh okay, my bad. Thanks!
