### ISSUE TITLE
[Feature request] add AWS Lambda notifier

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8066]
It is good tool to automate some of operational works.
If this feature is supported, Grafana can start Auto scaling by Grafana alert.

Grafana already support Webhook, so it is possible to call Lambda with API Gateway.
But, we need to protect access to Lambda, we need to use IAM role or other auth method.
Directly support Lambda call is one of the option to implement this feature.

https://aws.amazon.com/lambda/
https://aws.amazon.com/api-gateway/

**Comment by mtanda** [comment]
If Grafana support AWS SNS, it could be alternative for this feature.

**Comment by arash-bizcover** [comment]
How about a simple **API key** support for webhook instead of user pass _basic auth_ ?
