### ISSUE TITLE
[BUG] Stacked graph stacking not case sensitive

### ISSUE THREAD

**Issue by juhovan** [grafana/grafana#8067]
Hi,

I discovered that when stacking values that have names only differentiated by their case they will be incorrectly stacked.
Please see https://stats.24-7.fi/dashboard/db/factorio?panelId=4&fullscreen&from=1491033244900&to=1491163137901 for live demonstration, enable and disable "Juho" and "juho" and you will see that they often follow each other and stack incorrectly.
The legend is always correct and so is the graph when stacking is off.

Some images in case the link doesn't work:
(Correct) Only "Juho" selected, "Since Start" is excluded from stacking:
![selection_002](https://cloud.githubusercontent.com/assets/6834766/24791399/933cd998-1b82-11e7-8527-b27e34cd03c4.png)
(Correct) Only "juho" selected:
![selection_004](https://cloud.githubusercontent.com/assets/6834766/24791404/97877eea-1b82-11e7-8a74-8f00316a0476.png)
(Incorrect) Both selected, notice how the blue line correctly stays at 0 at the beginning but the red line follows the blue line while it should stay at 0:
![selection_003](https://cloud.githubusercontent.com/assets/6834766/24791402/96001884-1b82-11e7-8386-b05bd28ab825.png)
(Correct) Non-stacked graph, this is how the stacked graph _should_ look like in this case:
![selection_005](https://cloud.githubusercontent.com/assets/6834766/24791405/9918570c-1b82-11e7-884f-e750c8262707.png)

Please include this information:
- What Grafana version are you using?
Grafana v4.2.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS 7

**Comment by torkelo** [comment]
looks correct to me, as you have enabled stack on only one series is excluded from the stacking. So in the image where red and blue lines are drawn, the red line gets stacked on top of the blue.

**Comment by torkelo** [comment]
> (Correct) Non-stacked graph, this is how the stacked graph should look like in this case:

Why should the stacked graph look like the non stacked graph?

**Comment by juhovan** [comment]
If you take a close look at the third image you can see that the lines behave differently:
* At the first two times the the red line is drawn at 1, blue at 0 when real values are 1 & 0
* The rest of the times both lines are drawn to 1 when real values are 0 & 1

The stacking also normally leaves 0-values at 0 instead of stacking them like you mention, here's an example:
![selection_006](https://cloud.githubusercontent.com/assets/6834766/24796143/8302765c-1b94-11e7-83fa-d37c32552870.png)

**Comment by torkelo** [comment]
It depends on the order in which the series is drawn. If you stack a 0 value on top of a 1 value it will be drawn on the top of the 1 value.
