### ISSUE TITLE
log has one more button

### ISSUE THREAD

**Issue by zhaomingcheng01** [grafana/grafana#80692]
![image](https://github.com/grafana/grafana/assets/46734892/f055d310-e6a1-4921-abc2-cd01e5526ae7)
Only 1000 logs can be loaded at a time. A maximum of 2000 logs can be loaded. Can you add more buttons at the bottom to load the next 1000 logs

**Comment by zhaomingcheng01** [comment]
For example, there are 3700 logs in 6 hours, but currently only 1000 have been loaded. Without my understanding, I would assume that there is no more button at the bottom to load the remaining 1000 logs. Click to load the remaining 1000 logs, then click to load the remaining 700 logs, and do not load the number of logs that exceed the time range

**Comment by matyax** [comment]
There's the navigation component to load more logs, and soon there will be infinite scrolling in Explore.
