### ISSUE TITLE
[BUG] Error Sending Email Alerts with SMTP - "tls: first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by petershrom** [grafana/grafana#8071]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 
4.2.0

- What datasource are you using? 
InfluxDb

- What OS are you running grafana on?
Ubuntu Trusty

- What did you do?
tried to send an email alert

- What was the expected result?
an email alert

- What happened instead?
UI Says: "Problem! Failed to send alert notifications" 
Logs say: logger=alerting.notifier.email error="tls: first record does not look like a TLS handshake"
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by daniellee** [comment]
Related to this issue: #7189 

There is currently no support for sending alerts via SMTP servers that do not support TLS.

**Comment by petershrom** [comment]
Our Mailserver does support TLSv1 - so I'm not sure why we're getting this error.

**Comment by daniellee** [comment]
In the Grafana config, the default port is 25 (if you have not specified something else in your config). Does your mail server have support for TLS on that port?

Otherwise, could be something to do with STARTTLS vs TLS. I don't think we have renegotiation enabled in the TLS config. But I think it might be simpler to just support sending emails without TLS as specified in #7189 rather than adding that option.

**Comment by petershrom** [comment]
Thanks for following up, but I think it working on my end.  I changed the
port back to 25 with smtp true and it seems to be working now.

Pete

**Comment by daniellee** [comment]
Great!

**Comment by prakashray4pt** [comment]
Grafana docker running in ECS(AWS)  is failing  to send email alert using Simple Email Service (AWS)  SMTP server

Grafana - version : v5.4.3
SMTP server: email-smtp.us-east-1.amazonaws.com:25 

Grafana Run command:
docker run -d -p 3000:3000 \
-e "GF_SMTP_ENABLED=true" \
-e "GF_SMTP_HOST=email-smtp.us-east-1.amazonaws.com:25 \
-e "GF_SMTP_USER=xxx" \
-e "GF_SMTP_PASSWORD=xxx" \
grafana/grafana:5.4.3

Error: eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp 54.243.251.159:25: i/o timeout"

please help

**Comment by andrius-finnplay** [comment]
Grafana seems to lack these settings form email alerts:
Encryption method: SSL/TLS or STARTTLS
Authentication type: PLAIN or LOGIN.

We need these settings because Grafana cannot send any emails when using MS Exchange mailer.

**Comment by kgupta26** [comment]
> Grafana docker running in ECS(AWS) is failing to send email alert using Simple Email Service (AWS) SMTP server
> 
> Grafana - version : v5.4.3
> SMTP server: email-smtp.us-east-1.amazonaws.com:25
> 
> Grafana Run command:
> docker run -d -p 3000:3000
> -e "GF_SMTP_ENABLED=true"
> -e "GF_SMTP_HOST=email-smtp.us-east-1.amazonaws.com:25
> -e "GF_SMTP_USER=xxx"
> -e "GF_SMTP_PASSWORD=xxx"
> grafana/grafana:5.4.3
> 
> Error: eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="dial tcp 54.243.251.159:25: i/o timeout"
> 
> please help

@prakashray4pt i would check the connectivity on port 25.  Make sure its not blocked
