### ISSUE TITLE
alerting: creating a new alert returns an instant-vector even if time series and range are selected

### ISSUE THREAD

**Issue by iridos** [grafana/grafana#80724]
### What happened?

When I create a new alert (from a panel or from the alerting overview), the query directly returns a reduced value. The query shows  a table with values.  The reduce expression prints a "this function is not needed". 

Switching between type "Range" and "Instant" does not change this, neither does changing format to "time series".  

Only newly created alerts are affected. I still have previously created alerts that return a time series and even when I add a second query to them, I can switch between Instant and Range and the behavior is as expexted showing a time series when the type is "instant". 

### What did you expect to happen?

range giving me a time range

### Did this work before?

It worked definitely before the last major release. Not sure when afterwards it broke, as I am not daily adding new alerts. I noticed the new behavior maybe some weeks ago (and we have auto-updates on the grafana repo except for major versions). 

### How do we reproduce it?

1. create a new alert
2. check that it is "range"
3. press "run queries" or "preview"

### Is the bug inside a dashboard panel?

export via api/v1/provisioning/alert-rules/export:
        - uid: e985b71a-6df8-4373-8794-c1f58a236113
          title: bugtest
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cf6775f7-9e82-40fa-88df-04cc7b7caa67
              model:
                datasource:
                    type: prometheus
                    uid: cf6775f7-9e82-40fa-88df-04cc7b7caa67
                editorMode: code
                expr: system_load1{job="monitoring"}
                hide: false
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations: {}
          labels:
            service: k
          isPaused: false

### Environment (with versions)?

Grafana: 10.2.3
OS: Debian stable
Browser: Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
Hi @iridos  thank you for the detailed report!

Could you share some screenshots of the alert configuration that is returning an instant-vector instead of the expected time series? 

Would you be able to provide the Grafana server logs around the time when you create or edit an alert and experience this issue?

**Comment by tonypowa** [comment]
thanks for all the input @iridos  @togoes 
the issue was added to the team's board
they will take it from here
🚀

**Comment by armandgrillet** [comment]
This expected behavior is due to https://github.com/grafana/grafana/pull/69976, we make that more obvious in 10.4 and above with https://github.com/grafana/grafana/pull/78751 and also disable it by default with https://github.com/grafana/grafana/pull/78932.
