### ISSUE TITLE
sharing of dashboard between organization 

### ISSUE THREAD

**Issue by trlafleur** [grafana/grafana#8074]
It would be very useful to share live dashboard between organization...

ie: one dashboard, that can be part of one or more organization

Thanks

**Comment by torkelo** [comment]
This will likely not happen as we it makes little sense from a security perspective. Orgs are completely separate entities with their own dashboards. You can create a dashboard snapshot with a link you can share (But that is not live data). 

We are working on user groups (as replacement for Organisations) and dashboard & dashboard folder permissions ACLs (where you can use user groups). This will aid in sharing dashboards between user groups (but not between Orgs which should not be needed as much when user groups are introduced)

**Comment by torkelo** [comment]
it's getting close, hopefully beta release in mid December

**Comment by iekulyk** [comment]
thanks for the update

**Comment by acmeguy** [comment]
Any news on this? :) (Thnx for a great product!)
