### ISSUE TITLE
After update to 10.2 issues with dynamic variables

### ISSUE THREAD

**Issue by madd2008** [grafana/grafana#80758]
### What happened?

Hello,

We are doing this:

SELECT
  non_negative_derivative(mean("in_octets"), 1s)*8/1000/1000 / mean("/interfaces/interface/state/high_speed")
FROM
  "autogen"."gnmi_ifcounters"
WHERE
  "acro_reg"::tag =~ /^$Region$/
  AND "acro_dc"::tag =~ /^$DC$/
  AND "acro_cat"::tag =~ /^$Category$/
  AND "acro_provider"::tag =~ /^$Provider$/
  **AND "acro_ifcomplete"::tag =~ /^$Interface$/**
  AND $timeFilter
GROUP BY
  time($Resolution)
  ,"acro_ifcomplete"::tag

Variable  
interface = SHOW TAG VALUES FROM "gnmi_ifcounters" WITH KEY = "acro_ifcomplete" WHERE acro_reg =~ /$Region/ and acro_dc =~ /$DC/ and acro_cat =~ /$Category/ and acro_provider =~ /$Provider/

For the interface names with "/" we see that it's not processing it correctly anymore
For Example:
ams1-rt-01 et-0/1/0 (PF)
Appears as(please see screenshot, since this web page is replacing special characters &#x2 with the proper "/" symbols): 
ams1-rt-01 et-0&#x2F;1&#x2F;0 (PF)

And it throughs an error 
Status: 500. Message: InfluxDB returned error: error parsing query: found 1, expected ; at line 10, char 51

Thus no information is shown on the graphs
<img width="1496" alt="Screenshot 2024-01-17 at 10 30 45" src="https://github.com/grafana/grafana/assets/33316295/891671a9-eb8f-4507-8400-0f1c07f9d163">

### What did you expect to happen?

I would expect for the above query to continue to work

### Did this work before?

yes in version 10.1.6 it still works as expected(no special characters are added in the name)

### How do we reproduce it?

1. Have / in the name and use the query with the dynamic variable as per my example above

### Environment (with versions)?

Grafana: 10.2.3
OS: Rocky 9
Browser: All

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by Naumis1** [comment]
Hello, I have similar problem. 
Updated from grafana-10.2.1-1.x86_64 to grafana-10.2.3-1.x86_64

Had to roll back to old version :(

**Comment by paul5gray** [comment]
I ran into the same issue in 10.2.3 when trying to match filesystem names. 

For example, using "filesystem_name" =~ /^$FILESYSTEM$/ in the select will generate "Status: 500. Message: InfluxDB returned error:"

**Comment by tonypowa** [comment]
hi @madd2008 

thank you for reporting this issue

Could you confirm that the REGEX in the query is formatted correctly for the updated version? Sometimes updates change how special characters need to be escaped.

**Comment by tonypowa** [comment]
@grafana/dashboards-squad  @grafana/observability-metrics

**Comment by itsmylife** [comment]
This was resolved with this PR https://github.com/grafana/grafana/pull/80971
It will be available in `v10.4.0`.

**Comment by tonypowa** [comment]
thanks for sharing the fix @itsmylife  !
closing this issue
feel free to request reopening if needed
