### ISSUE TITLE
Node Graph improvement feature request

### ISSUE THREAD

**Issue by hkailantzis** [grafana/grafana#80750]
**Why is this needed**:

Hi there, 

This is more like a question, and also apologies, if its already mentioned...

In the Tracing context using Jaeger or Tempo as datasource, and the **Node Graph** in particular, it would be great to provide a way of an overview of the system where, if users desire, can then drill-down to more details on the Node Graph for a span/operation view to see a more detailed view...

**What would you like to be added**:

I've seen in most UI's or Monitoring from other providers (ie Elastic, Splunk to name a few), when Tracing is part of a system, that the Service Overview which is generated is a very nice way to have it as a high-level overview of just a service dependency graph. At the moment, Node Graph provided in Grafana, is directly on the span/operation level, which is a too overwhelming imho to see at first glance, and looks more confusing, increases cognitive load etc...

I understand the panel is still in beta, but was wondering, if its something to consider in the future, where for example an overview of the system is first displayed, showing the dependencies, and if the user desires can drill down, from that graph to see on operation/span level the relevant flow/view...

I have uploaded 2 screenshots, as an example, from the Otel demo (https://opentelemetry.io/docs/demo/), of the relevant Graph in Elastic/APM UI in Kibana, and Grafana's Node Graph, hoping to help out explaining on what I'm trying to explain here :-)... Notice the bold lines in the Elastic version, is happening on mouse over, ie the service map is interactive and nodes and flows are actually clickable allowing for drilling down to details...

<img width="777" alt="Screenshot 2024-01-17 at 17 52 06" src="https://github.com/grafana/grafana/assets/2778156/37b9e0b8-ee45-4216-9526-be48003501f2">
<img width="1064" alt="Screenshot 2024-01-17 at 17 52 29" src="https://github.com/grafana/grafana/assets/2778156/06db69d8-5790-43d5-983d-e272fc9328bb">

Thanks in advance

**Who is this feature for?**

Grafana Node Graph.

**Comment by pingping95** [comment]
+1

**Comment by 09jvilla** [comment]
Have you used the "Service Graph" view for Tempo? Is that sort of along the lines of what you're interested in? In this graph, the circles (i.e. the nodes) are services (rather than span names). 

I don't know if there is an equivalent for Jaeger. 

![Screenshot 2024-02-12 at 9 17 54 AM](https://github.com/grafana/grafana/assets/9610816/74e56fab-93e6-49f7-99c3-1fe76e05809b)

**Comment by pingping95** [comment]
in my usecase, before LGTM stack, i used datadog as APM tool

we changed from datadog to grafana stack.

there was clear view who is client and server and database when using datadog.

In LGTM stack, there wasn't clear view.

i used tempo metrics generator service graph.

i made service graph, spanmetrics dashboard for our developers.

when i talking with developers, service graph isn't clear and hard to zoom in and out.

of course this can be useful to view overall API call and latency but someway it is actually incomvinient to view.😢

so i added this comment as user
and apology for my poor English.

**Comment by hkailantzis** [comment]
hi @09jvilla, 
yes I'm aware, is one of the reasons, why I would love to use Tempo vs Jaeger, (apart from better Grafana stack integrations, and Storage options), however one of the reasons, is that Jaeger also offers this already via its UI/Jaeger query, is called  SPM, (attached screenshot), so was hoping to at least be able to access or reproduce the same on Grafana UI via Jaeger datasource and the NodeGraph. Besides, thats one of the powers of Grafana, being able to 
bring features from multiple datasources not only the LGTM stack ;-). 

Another reason, is that, to get the the ServiceGraph out of Tempo, (and correct me if I'm wrong), it requires Remote Write to Prometheus or Thanos, which is something, in some orgs is not an option, for different reasons, like security, internal org policy etc.

<img width="898" alt="Screenshot 2024-02-15 at 15 35 21" src="https://github.com/grafana/grafana/assets/2778156/566b8675-7bff-4d1f-8cf0-a30374c3790b">

**Comment by 09jvilla** [comment]
> Another reason, is that, to get the the ServiceGraph out of Tempo, (and correct me if I'm wrong), it requires Remote Write to Prometheus or Thanos, which is something, in some orgs is not an option, for different reasons, like security, internal org policy etc.

You are correct. The way that Tempo renders a service graph is by using its metrics-generator component to create metrics from incoming spans. Those metrics need to get written to a time series database. Once TraceQL metrics queries get more mature (they were only just released as [experimental](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/)) , I anticipate we'll be able to build this kinds of node/edge graphs on-the-fly from spans, rather than having to generate metrics, store them in a TSDB, and then read them out of there. 

> so was hoping to at least be able to access or reproduce the same on Grafana UI via Jaeger datasource and the NodeGraph. Besides, thats one of the powers of Grafana, being able to
bring features from multiple datasources not only the LGTM stack ;-).

Totally reasonable. :) Looks like there's a related ask for that here:
https://github.com/grafana/grafana/issues/79372

**Comment by hkailantzis** [comment]
@09jvilla thanks for the feedback. 
For the time being, for my needs, I was forced to jump to Tempo anyway, but without having to use the Prometheus Remote Write (for security internal reasons) for all the features of Tempo. I managed to use the OTEL collector and enable ServiceGraph and SpanMetrics Connectors for it. Metrics generated out of these components are then pulled by using the Prometheus Exporter component of OTEL collector and adding an 'extra' ServiceMonitor for those OTEL dedicated metrics. So, is working perfectly fine, so all features of Tempo without Prometheus Remote Write was what I was after, but it is quite the config and took a while to get my head around it. Was just hoping that we could get similar behaviour of Jaeger UI's SPM features also in Grafana/Jaeger realm without all that fuzz. :D. The issue can be closed, but can also be kept open in case there is more contribution/ideas about it... Thank you!.

**Comment by hkailantzis** [comment]
btw, https://github.com/grafana/grafana/pull/72200 for it has been merged.
