### ISSUE TITLE
Some href links conflict with Grafana hosted on sub-path

### ISSUE THREAD

**Issue by sterbeN27** [grafana/grafana#80777]
### What happened?

I'm running Grafana on sub-path `/dashboard` + Nginx by following steps from https://grafana.com/tutorials/run-grafana-behind-a-proxy/ 

Most of the pages work fine but when I tried to create a new dashboard using the drop down button at top right, it says page not found. 
![image](https://github.com/grafana/grafana/assets/57295193/6ba5eee3-71aa-44e7-bdc0-d398e506e9c5)
![image](https://github.com/grafana/grafana/assets/57295193/59d491d6-88d8-4205-b101-04ef3013054d)

When I tried to debug, it looks like something wrong with the href links of the `New dashboard` button which caused it to ignore the Grafana sub-path (`/dashboard`). I noticed it happened if I click import dashboard as well.
![image](https://github.com/grafana/grafana/assets/57295193/13382c6f-6b77-44f8-b558-bd1fd7a53fd3)

### What did you expect to happen?

I expect it to go to `/dashboard/dashboard/new` instead of overwrite the url to `/dashboard/new`.

### Did this work before?

It works if I changed the sub-path into the name that is not part of Grafana routing paths but it will be an additional work to make sure the sub-path name that we choose should not conflict with Grafana routing.

### How do we reproduce it?

1. Edit Grafana `defaults.ini` & `grafana.ini` file:
```
...
[server]
protocol = http
http_port = 3000
domain = localhost
root_url = %(protocol)s://%(domain)s:%(http_port)s/dashboard/
serve_from_sub_path = true
...
```
2. Edit Nginx `/etc/nginx/sites-available/default` file:
```
...
location /dashboard {
    proxy_set_header Host $http_host;
    proxy_pass http://localhost:3000;
}

location /dashboard/api/live {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $http_host;
    proxy_pass http://localhost:3000;
}
...
```
4. Restart Nginx and Grafana

### Environment (with versions)?

Grafana: **10.2.2**
OS: **Ubuntu 22.04.3 LTS**
Browser: **Mozilla Firefox**

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

```[tasklist]
### Tasks
```

**Comment by L-M-K-B** [comment]
We need to investigate how to prevent this in the future.

**Comment by sterbeN27** [comment]
> We need to investigate how to prevent this in the future.

Thanks!

**Comment by joshhunt** [comment]
For some additional context, previously we had this https://github.com/grafana/grafana/issues/74275 which was spot-fixed in this PR https://github.com/grafana/grafana/pull/84992 from a contributor with some additional context from me:

> - we've been talking about more automatic subprefixing for URLs, but turns out we already have then (when using react-router-dom Links with basename, which this does with)
> - BUT, it appears there's a bug or incomaptibility with react-router where it doesn't prefix the subpath if your subpath is the same as a route (such as your dashboards)
