### ISSUE TITLE
PostgreSQL: support connections to non-default schemas

### ISSUE THREAD

**Issue by thetoothpick** [grafana/grafana#80771]
**Why is this needed**:
PostgreSQL supports the notion of ["schemas"](https://www.postgresql.org/docs/current/ddl-schemas.html), which are subsets of a "database".  Currently, Grafana does not support setting the target schema for a data source.  This makes it difficult to discover tables and table structures, as the query builder and code editor can't see non-default schemas.

**What would you like to be added**:

Add a configuration option to set the schema for a PostgreSQL connection.  This can be accomplished by adding a `search_path` parameter to the connection string ([lib/pq](https://pkg.go.dev/github.com/lib/pq#hdr-Connection_String_Parameters)).

**Who is this feature for?**

Users who have PostgreSQL data in non-default schemas.

**Workarounds**

I've tried several workarounds, including setting `search_path` in the query window.  This does work temporarily, and tables / columns populate in the query builder, but only for the connection it was executed on, and it eventually reverts.

**Comment by memo26167** [comment]
This was discussed earlier (see #27435 #58712 #75968) and the issues are moved back and forth.

**Comment by thetoothpick** [comment]
@memo26167 the linked issues all relate to using Postgres as a datastore for Grafana itself (i.e. setting the schema in `grafana.ini`).  This issue is referring to using Postgres as a connection within the Grafana application, to be used in dashboards, etc.
