### ISSUE TITLE
[Bug] Influxdb SELECT UI broken

### ISSUE THREAD

**Issue by Artanicus** [grafana/grafana#8077]
Repeats on play.grafana.org:
1. Go to: http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit&orgId=1&tab=metrics
2. Expand query A
3. From the SELECT section add a new Transformations -> Derivative
Expected result: derivative block added to query
Actual result: click goes through menu item and instead selects the Display tab

- All other SELECT column blocks also fail to produce anything but since there's nothing behind most them to click, nothing happens. For example Aggregations -> Distinct also goes through.
- By switching edit mode and adding in the transformations myself everything works fine.
- Running Google Chrome Version 57.0.2987.110 (64-bit) on Ubuntu 16.04, also repeats in extensionless incognito window.

Video example: https://gfycat.com/AmbitiousNextIndochinesetiger

**Comment by torkelo** [comment]
Very strange, fail to replicate this on exactly the same browser and OS. 

No idea what could be causing it, good that you tested without extensions because that was going to be my followup suggestion. Do you have colleagues who can replicate it or replicated it on in other browsers or other OS?

**Comment by Artanicus** [comment]
Strange indeed. On OS X, Chrome version Version 57.0.2987.110 (64-bit) the issue does not repeat for me.

Also tried a Chrome reboot but the issue continues on the other machine. Any debug output I can pull? This also repeats on my own Grafana instance so can wiggle with flags there.

**Comment by torkelo** [comment]
Please open chrome dev tools console, maybe an error? 

Also test starting chrome without hardware acceleration (remember chrome on linux has some graphic issues, which maybe can cause some z-index click issues).

Maybe also show your settings for chrome://gpu/

**Comment by Artanicus** [comment]
No console errors unfortunately.

Did some triangulation on the Linux machine where this fails:
- Doesn't reproduce on google-chrome-unstable, Version 59.0.3047.0 (Official Build) dev (64-bit) 
- Reproduces with fresh user, fresh profile, google-chrome-stable 57.0.2987.110 (64-bit)
- Reproduces with fresh user chrome 57 even with turning off hardware acceleration.

So seems like it's some very obscure Chrome bug that's already been fixed in unstable. Lovely.

**Comment by Artanicus** [comment]
Managed to narrow down the Chrome bug even more, when launching chrome stable without a window manager the issue does not reproduce. When using Awesome as a WM the issue reproduces on stable but not on unstable. So as I guessed, obscure bug that gets tickled by a tiling WM. I guess it's my own shame then and we can close this :-)
