### ISSUE TITLE
Using ldap authorisation, configuration I am following the official recommended configuration, but currently I can't get normal administrator permissions (ldap group exists and users are included in it) .

### ISSUE THREAD

**Issue by MagicStarTrace** [grafana/grafana#80783]
### What happened?

level=debug msg="No permissions set for entity" namespace=user id=3 orgID=0 login=yifanhu

### What did you expect to happen?
```
[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "172.16.0.1"
port = 389
bind_dn = "cn=Manager, dc=test, dc=com"
bind_password = 'test123'

use_ssl = false
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false


search_filter = "(cn=%s)"
search_base_dns = ["dc=test,dc=com"]
group_search_filter = "(&(objectClass=groupOfUniqueNames)(uniqueMember=%s))"
group_search_base_dns = ["ou=groups,dc=test,dc=com"]
group_search_filter_user_attribute = "uid"



[[servers.group_mappings]]
group_dn = "cn=grafana-admin,ou=groups,dc=test,dc=com"
org_role = "Admin"


[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
```
With the above configuration enabled, the corresponding user should have administrator rights, but after testing, it only has view rights.

I made some changes to the configuration
```
group_dn = "*" [[servers.group_mappings]]
group_dn = "*"
org_role = "Admin" 
```
Log in again and the corresponding account has administrator privileges.

### Did this work before?

Using ldap authorisation, configuration I am following the official recommended configuration, but currently I can't get normal administrator permissions (ldap group exists and users are included in it) .

### How do we reproduce it?

Copying the configuration above (which requires ldap) to reproduce it, I'm not sure what's causing this problem

### Environment (with versions)?

Grafana:  Version 10.2.3
OS:  ubuntu 18.04.4 
Browser: chrom 120.0.6099.216
 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
hi @MagicStarTrace 
Thank you for reaching out with your issue regarding LDAP authorization in Grafana

Have you checked Grafana's logs for any additional error messages when a user is trying to authenticate or when the user's permissions are being evaluated? If possible, could you provide those log entries?

**Comment by MagicStarTrace** [comment]
> hi @MagicStarTrace Thank you for reaching out with your issue regarding LDAP authorization in Grafana
> 
> Have you checked Grafana's logs for any additional error messages when a user is trying to authenticate or when the user's permissions are being evaluated? If possible, could you provide those log entries?

I've fixed it. ldap configuration problem.
Now fixed
