### ISSUE TITLE
massive grafana rules  performance

### ISSUE THREAD

**Issue by halleystar** [grafana/grafana#80788]
### What happened?

The alert generator evaluates all alert rules on all instances. when there are massive number of alert rules, it will take a long time to evaluate all of them. resulting in a long delay in alerting. how can we improve the performance of alerting?

### What did you expect to happen?

A way to horizontally scale the alert generator?  or sharding by group?

### Did this work before?

no

### How do we reproduce it?

set massive number of alert rules

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
Hi @halleystar 

GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on[ https://community.grafana.com/](https://community.grafana.com/)

With your question please share the version of Grafana you're using

Thank you
