### ISSUE TITLE
Alerting: Graph Alert history & Percent of time in OK or Alerting

### ISSUE THREAD

**Issue by andreyradygin** [grafana/grafana#8079]
Hi guys!
It would be great to have uptime/downtime calculating feature.
As grafana have all needed data for such calculations, it would be nice to see such digits in percentages for chosen period of time.
For instance when we looking at alert history for some time period - grafana automatically calculate it and show to admin.
There is nice example - availability reports in Icinga.

PS
I was looking for such feature request or possibility in Issues or community info, but couldn't find it.

Anyway, thank you guys for such great tool!

**Comment by torkelo** [comment]
Can you describe what your data looks like? (the response from your metric query)? 

There is a duration unit that can show seconds as "3 days"

**Comment by andreioss** [comment]
It doesn't matter what data do we have.
I meant calculate uptime percent based on time ranges in State history of Alert.

For example we have such history:

OK
февр. 28, 2017 21:37:32
ALERTING
февр. 28, 2017 21:19:05
OK
февр. 28, 2017 21:12:16
ALERTING
февр. 28, 2017 19:39:28

So from this time periods we can calculate common percent of uptime/downtime for this service.

For instance, we have several periods of Alerting (meaning - downtime actually), with total duration - 10 hours, so if chosen period of time - 100 hours, we have 90% of uptime. Here is what calculations I talking about.

**Comment by pdf** [comment]
Related: #9192

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
