### ISSUE TITLE
Alert state hidden by Info corner

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8080]
When a panel gets too narrow, the alert state can be hidden by an info panel. 

<img width="534" alt="screenshot 2017-04-10 10 06 16" src="https://cloud.githubusercontent.com/assets/2886187/24865566/a51463fc-1dd5-11e7-8dca-d6fe9eaee42e.png">

The alert state certainly exceeds the info corner in information priority, so we'll need to devise a workaround to not hide the broken heart. The border of the panel still pulses red, but especially for our color-blind folk, it makes it even harder to notice something is awry.

**Comment by torkelo** [comment]
But then you can't interact with the panel info, that also may contain panel error messages and is a link to panel inspector. So it's not clear about what should take z-index preference. 

(not a solution just some instinctive feedback, the title seems overly verbose, especially the first word endpoint)

**Comment by mattttt** [comment]
Good point on the error message. 

As for title size in this case - seems irrelevant. You could have a shorter title encounter the same problem, or a longer title where it is not overly verbose.

Perhaps in either case,  we can put a left margin on the panel title so it leaves appropriate space for the corner info area?

**Comment by daniellee** [comment]
The alert state is now still visible even when the panel gets really narrow and has a link.
