### ISSUE TITLE
[Bug] Grafana cannot read multiline results properly

### ISSUE THREAD

**Issue by tammytankian** [grafana/grafana#8081]
Hello there o/

My problem is the following :/

I have this text

> ID:
> 
> Origem: 4
> 
> Mensagem: Parametro invalido: CHASSI_INVALIDO: chassi
> 
> Gateway: 2
> 
> Versao: v20170130
> 
> Layout: BASERNS2
> 
> Data: 2017-04-10 10:00:04.592

And grafana (**doesnt matter the panel**) reads like this

> ID: Origem: 4 Mensagem: Parametro invalido: CHASSI_INVALIDO: chassi Gateway: 2 Versao: v20170130 Layout: BASERNS2 Data: 2017-04-10 10:00:04.592

How can I get for Grafana to show the result properly, with the 'new line'?

Is that even possible?

Thanks

- What Grafana version are you using?  _Grafana v4.1.2 (commit: v4.1.2)_ 
- What datasource are you using? _ALEXANDERZOBNIN-ZABBIX-DATASOURCE_
- What OS are you running grafana on? _Debian 8.7_

**Comment by torkelo** [comment]
Not sure, please open questions on the community site, and include the panel configuration and the raw response from the datasource. 

Not sure any core grafana panel supports multi line text values

**Comment by tammytankian** [comment]
Thank you! I will


Peace
