### ISSUE TITLE
How to change title of website grafana

### ISSUE THREAD

**Issue by dejokuondi** [grafana/grafana#8083]
<img src="https://cdn-standard3.discourse.org/uploads/grafana/original/1X/07841959faa1b31b5c6ea442f8783ef1c8ceb8fb.PNG" width="690" height="372">

I have a project use grafana.
I want to change title of website (2 point) as image attached.
Please help me to change it.

Thanks.

**Comment by torkelo** [comment]
please don't create duplicate posts :cry: 
https://community.grafana.com/t/how-to-change-title-of-website-grafana/500
