### ISSUE TITLE
Dashboards: auto refresh not loaded correctly

### ISSUE THREAD

**Issue by morsik** [grafana/grafana#80842]
### What happened?

Opening dashboard with set `refresh=auto` fails to properly load this value and fallbacks into disabled refresh.

### What did you expect to happen?

Dashboard will open correctly with previously-saved value `refresh=auto`.

### Did this work before?

Tried on versions 10.2.2 and 10.2.3 (latest) - both not working properly

### How do we reproduce it?

1. Create dashboard
2. Set "Refresh Interval" in top-right corner to "Auto". Grafana automatically assigns refresh interval nicely.
3. Get happy because you don't need to deal with this anymore and try to save your greatest dashboard :)

   You see this so you are even more happy, because it gets saved:
   
   <img width="377" alt="Screenshot 2024-01-18 at 21 29 40" src="https://github.com/grafana/grafana/assets/783794/e71ccce4-c2e0-4b6e-a4e0-255f83b871e9">
   
4. Go to other page in Grafana and try to load your dashboard again. Be sad, because your saved refresh config is not there anymore, refresh is disabled and you have to set it to auto everytime you enter your dashboard :(

### Environment (with versions)?

Grafana: 10.2.2, 10.2.3
OS: macOS Sonoma 14.2.1
Browser: Firefox 121.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus (from Mimir), Loki

**Comment by nagisa** [comment]
Came to report the same issue, but for me it seems to pick specifically the 5s option rather than auto on a fresh load of the dashboard.

**Comment by morsik** [comment]
@nagisa yeah, I discovered that slightly after making this issue.

For me it's even weirder because I changes possible intervals and I don't even have 5s on my list. And because of that, it looks like auto refresh is disabled in menu (since 5s is not an option for me), but it indeed redirects dashboard to URL with `refresh=5s`.


<img width="714" alt="Screenshot 2024-01-22 at 13 35 53" src="https://github.com/grafana/grafana/assets/783794/c6f865c7-9498-430c-905b-d9620acfd4e7">

**Comment by bobemoe** [comment]
Same issue here.

I figured maybe its not getting accepted as valid config value for some reason. I thought maybe I would add Auto to my available intervals like this: 

![image](https://github.com/grafana/grafana/assets/2304970/b15da0be-8cc7-4bcb-ba6f-00ed373d0b94)

But it wouldn't save with a validation error. Funnily enough it will save with a lower case "a" like so:

![image](https://github.com/grafana/grafana/assets/2304970/15c5ee92-f224-464f-92fb-c81755be344a)

Then you get 2 autos in the dropdown:

![image](https://github.com/grafana/grafana/assets/2304970/bed6cb9f-5a26-46fb-a247-cb860d78fa3d)

But even selecting either of those it still wont save to the dashboard.

I have also tried setting "auto" in the json and also pushing the json up via the API. It just wont accept it :/

**Comment by toxyl** [comment]
I'm having problems with the auto refresh as well. When restarting my browser the auto setting is ignored and everything defaults to 5s, overloading my local prometheus VM. So far I couldn't find a way to force my dashboard(s) to use Auto by default.

**Comment by tonypowa** [comment]
hi @morsik 

thank you for reporting this issue

when you saved the dashboard:
did you also tick this checkbox? This will actually show when selecting a new time range (not refresh interval, but still I would like to know if it shows when you hit Save).

![image](https://github.com/grafana/grafana/assets/45235678/e38df0b7-605a-4267-ab9e-3f8008964f23)

In addition, could you please provide us with the browser's console logs when you save the dashboard and when you load it again? 
And,  what was the last version in which this worked correctly? 
Thank you!

**Comment by bobemoe** [comment]
Hi thanks for looking at this, but that box is not available:
![image](https://github.com/grafana/grafana/assets/2304970/6d1b572b-7baf-4bfe-b18d-f37d46c6b84d) ![image](https://github.com/grafana/grafana/assets/2304970/2ada7ec1-5e70-4522-bb27-db4f8a974031) 

I don't think that is the issue though, because as you can see in the screenshot the option should be saved in the json. Also as mentioned above I've also tried pushing it up through the API, and as others mentioned its also replaced from `refresh=auto` to `refresh=5s` when passed in the URL too, even though when selecting auto in the picker the url gets updated to read `refresh=auto`, it just doesn't persist across a reload.

**Comment by tonypowa** [comment]
thanks for the quick reply @bobemoe 
I will leave from here to the maintainers

**Comment by bobemoe** [comment]
I don't think it was ever working... It was introduced in 10.1 https://github.com/grafana/grafana/pull/70479 and I just tested a local 10.1 docker image and still seeing the same unexpected behaviour there too.

Nothing in FF browser console other than the usual:
```
unreachable code after return statement redux-toolkit.esm.js:321:4
unreachable code after return statement redux-toolkit.esm.js:426:4
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. grafana.ecomotus.co.uk:489:10
Error in parsing value for '-webkit-box-align'.  Declaration dropped. grafana.ecomotus.co.uk:532:22
Error in parsing value for '-webkit-transition'.  Declaration dropped. grafana.ecomotus.co.uk:575:26
Error in parsing value for 'transition'.  Declaration dropped. grafana.ecomotus.co.uk:576:18
Error in parsing value for 'min-height'.  Declaration dropped. 2 grafana.ecomotus.co.uk
```

**Comment by FeepingCreature** [comment]
I'm not sure this was actually fixed by that commit. `refresh=auto` in the *URL* still has no effect. That is, you set refresh to auto, reload the dashboard, it falls back to no refresh.
