### ISSUE TITLE
[question] is it possible to automatically create panel per tag?

### ISSUE THREAD

**Issue by skygragon** [grafana/grafana#8085]
I have a metric "server.uptime" in openTSDB and every server will update this metric with own tag like: host=serverXXX. For each server I want create a SingleStat panel to display the uptime.
I have tried scripted dashboard, but it require me to script some to query all tags first then create panels one by one. Just wondering if there has other easier way to achieve this? 

BTW, can I load a JSON in the script? otherwise I have to write a lot of code to render panel config...

**Comment by torkelo** [comment]
yes, if you create a template variable holding all your tag values. Then use that variable in your query. 

Then in panel general tab specify the variable under the repeat option.

**Comment by skygragon** [comment]
Thanks @torkelo The repeat panel is working! But how can I specify the width of each panel? Currently all the panels are auto-sized evenly within the row...

**Comment by torkelo** [comment]
yes, there is no control. Grafana tries to fill the row with as many as fits (depending on min span option)
