### ISSUE TITLE
Query input: no space around "Loading..." placeholder

### ISSUE THREAD

**Issue by colega** [grafana/grafana#80861]
### What happened?

I often see this for a few milliseconds and it annoys me but then I forget and get back to work.

<img width="550" alt="image" src="https://github.com/grafana/grafana/assets/1511481/92653c0a-8eeb-4ca9-b967-44ced5dfdc6c">

However, today I'm working on a very bad internet connection and I had to stare at that "Loading..." placeholder for a while.

### What did you expect to happen?

I would expect the "Loading..." placeholder to be styled consistently with the rest of the interface.

### Did this work before?

I don't think so.

### How do we reproduce it?

1. Open "Explore" on a slow connection (simulate from Chrome)
2. Try not to cry while staring at the "Loading..." without proper padding.

### Environment (with versions)?

Grafana: Grafana v10.2.3 (1e84fede54)
OS: Mac
Browser: Chrome, Arc.

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by ifrost** [comment]
It seems to be related to Monaco Editor. @grafana/observability-logs, @grafana/observability-metrics, @grafana/grafana-frontend-platform who's the owner of Monaco nowadays?

**Comment by joshhunt** [comment]
Monaco editor doesn't really have strong ownership - it recieves drive-by contributions by those who need them. We're going to leave this one with Observability Metrics, as the main consumer in this use case.
