### ISSUE TITLE
Not able to set Alert in Grafana

### ISSUE THREAD

**Issue by Nicky050** [grafana/grafana#8088]
Hi,
I am working on to create a Grafana dashboard with InfluxDB and Telegraf as metric collection tool to monitor the Hyper-V servers.

I have created the time series graph and now in Alert setting part and I am not able to make it success.

1) I added individual hosts one by one from rows A to I to create the RAM utilization graph.
![image](https://cloud.githubusercontent.com/assets/27270591/24901974/566f2588-1ec6-11e7-8919-1bec13ec33d5.png)

2) Do I need to make any more setting changes to trigger the email?
3) How to create a single condition to include all the hosts (from A to I) so that the alert can be set as common?

![image](https://cloud.githubusercontent.com/assets/27270591/24901708/82de505e-1ec5-11e7-8a69-69ff548b1709.png)

Test rule out put

result
    firing true
    conditionEvals [true OR true] = true
    timeMs 31.318ms
    matches
        0 { metric: denad568, value: 379906230000, $$hashKey: object:3673 }
        1 { metric: denad568, value: 379896878000, $$hashKey: object:3674 }
    logs
        0 { message: Condition[0]: Query Result, data: [object Object], $$hashKey: object:3685 }
        1 { message: Condition[0]: Eval: true, Metric: den8, Value: 379906230000.000, data: null, $$hashKey: object:3686 }
        2 { message: Condition[1]: Query Result, data: [object Object], $$hashKey: object:3687 }
        3 { message: Condition[1]: Eval: true, Metric: den8, Value: 379896878000.00

Can someone please provide some more info for this.

**Comment by torkelo** [comment]
We appreciate if questions are posted on the community site. 

Maybe you missed this text from the new issue template? 

Read before posting: 
- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request].
