### ISSUE TITLE
[Bug] Redirect after switching Org does not obey sub path in root_url (using reverse proxy)

### ISSUE THREAD

**Issue by skladd** [grafana/grafana#8089]
Grafana version: 4.2.0
OS: Linux
Setup: Apache as reverse proxy,  root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

When switching the Organization via orgId GET parameter the redirect omits the "/grafana" in the new URL and I get a 404. Trying again it works - I suspect because the organization is not changed.

**Comment by torkelo** [comment]
it will just redirect to the same url that was originally requested. Maybe something that is strange with your reverse proxy?

**Comment by skladd** [comment]
The proxy works just fine as long as I do not change the orgId. So it works if the new orgId is the same as the old one.

If a do a GET request to `https://myserver/grafana/dashboard/db/my-dashboard?orgId=1&var-host=host123` I get a 302 response with Location `/dashboard/db/my-dashboard?orgId=1&var-host=host123`.

I do also use auth proxy for authentication in case that it matters, here is the relevant section of the vhost config file:
```
SSLProxyEngine On
ProxyRequests Off
ProxyPass /grafana http://localhost:3333
ProxyPassReverse /grafana http://localhost:3333

<Location /grafana>
    RequestHeader set       X-Forwarded-Proto "https"
    RewriteEngine           On
    RewriteRule             .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
    RequestHeader set       X-WEBAUTH-USER "%{PROXY_USER}e"
    RequestHeader unset     Authorization

    AuthType                basic
    AuthName                "restricted"
    AuthBasicProvider       file
    AuthUserFile            ***
    Require                 ***
</Location>
```

**Comment by torkelo** [comment]
found the problem! fixed, please try next nightly build!

**Comment by skladd** [comment]
Tested with grafana_4.3.0-7526pre1, it works. Thank you!

**Comment by mshillinger** [comment]
This appears to still be broken in 4.3.0-beta1

My config is:
```
[server]
# Protocol (http or https)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = localhost

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url (THE TRAILING SLASH IS REQUIRED!!!)
# root_url = %(protocol)s://%(domain)s:%(http_port)s/
root_url = http://localhost:3000/graph/
```
Visiting http://localhost:3000/graph/ in the browser will show the index.html, but nothing else will load.

Grafana log is showing;
```
msg="Request Completed" orgId=1 uname= method=GET path=/graph status=404 remote_addr=127.0.0.1 time_ms=20 size=9330
msg="Request Completed" orgId=1 uname= method=GET path=/graph/public/css/fonts.min.css status=404 remote_addr=127.0.0.1 time_ms=15 size=9330
msg="Request Completed" orgId=1 uname= method=GET path=/graph/public/css/grafana.dark.min.4524dd51.css status=404 remote_addr=127.0.0.1 time_ms=57 size=9330
msg="Request Completed" orgId=1 uname= method=GET path=/graph/public/app/boot.8f0650f6.js status=404 remote_addr=127.0.0.1 time_ms=66 size=9330
```

**Comment by torkelo** [comment]
No that is unrelated, if you use subpath in roomlt url you need to access grafana through reverse proxy that adds the subpath

**Comment by daniellee** [comment]
@mshillinger you cannot access grafana directly at localhost:3000/graph if you have set up a reverse proxy (like Torkel said above).

This error: `/graph/public/css/fonts.min.css status=404` shows that the base url is still localhost:3000. Have you set up a proxy or where you just testing?

**Comment by TheHolm** [comment]
Problem seems to be back with  Grafana v5.0.2 (commit: f14ad74).  Symptoms are same. 
Grafana is siting behind "pound" reverse proxy. which is redirecting everything behind "/grafana" to Grafana. Please note that reverse proxy also terminates SSL, but talks to Grafana over HTTP.  

 If I configure it as 
1) root_url = https://metaview.nexon.com.au/grafana
I getting 404 on loading static content.  

t=2018-03-15T04:59:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/grafana status=404 remote_addr=192.168.88.125 time_ms=2 size=10202 referer=
t=2018-03-15T04:59:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/grafana/public/build/grafana.dark.css status=404 remote_addr=192.168.88.125 time_ms=1 size=10202 referer=https://metaview.nexon.com.au/grafana

2) if it configured as (which is obviously wrong) 
root_url = https://metaview.nexon.com.au/
Then static content is loading just fine. But I'm getting blank black page. 

t=2018-03-15T05:29:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/grafana status=404 remote_addr=192.168.88.125 time_ms=2 size=10146 referer=

**Comment by krunalvora** [comment]
I am facing the same problem. Could you resolve this @TheHolm ?

**Comment by snowgrains** [comment]
Hi,
I'm facing the original problem with Grafana 5.3.1 (08c7908). I have clean grafana setup (no any specific proxy configurations) and by changing the org in browser will redirect to localhost first time. If I enter the address again with new org after first redirection it will function as it should. 

This is causing problems when trying to open simultaneously multiple organisations into different browser tabs.

Thanks for checking this!

**Comment by skladd** [comment]
Just checked it, the original problem is back for me, too.

**Comment by marefr** [comment]
@skladd what Grafana version?

**Comment by skladd** [comment]
Grafana v5.4.2

**Comment by marefr** [comment]
Yes that's what I thought. We had a bug which was fixed in 5.4.3. Thanks for confirming

**Comment by star-series-testing** [comment]
Was this fixed? I am having the same issues with 6.0.1

**Comment by marefr** [comment]
@star-series-testing It was fixed, but maybe a new regression? Could you please include some more information of what's going on and what reverse proxy+config + grafana config you're using? Thanks

**Comment by iondulgheru** [comment]
Also happening to me on grafana 6.0.1

**Comment by covrig** [comment]
Still happening on Grafana 6.3.3.

**Comment by bb-himeshsharma** [comment]
Any new issue was opened for this thread ? 
With grafana 10.1.5 I am facing the same issue
