### ISSUE TITLE
using value of  Singlestat for another  Singlestat 

### ISSUE THREAD

**Issue by jsaada** [grafana/grafana#8090]
hello,
my config ( grafana + influxdb,debian 8 ) everything up to date

i've got 2 singleStat which are working great:
SELECT sum("value") FROM "prod.video.ok" WHERE $timeFilter
SELECT sum("value") FROM "prod.video.ko" WHERE $timeFilter

i would like to create a third "singleStat" as a percentage of the 2: prod.video.ko *100 / prod.video.ok
how can i do that ?

**Comment by torkelo** [comment]
no that is not possible. You will have to write an InfluxDB query that does the percentage calculation. Not sure if that is possible given InfluxDBs limited query language.

We appreciate if questions are posted on the community site.

Maybe you missed this text from the new issue template?

Read before posting:

Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue.
Checkout FAQ: https://community.grafana.com/c/howto/faq
Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
Please prefix your title with [Bug] or [Feature request].
