### ISSUE TITLE
Grafana + Oauth proxy: error 403 - requires log in

### ISSUE THREAD

**Issue by TiferetJackson** [grafana/grafana#80954]
### What happened?

After adding ouath proxy as container to Grafana deployment, grafana operator can't reach grafana api and receives error 403 - <title>Log In</title>

When I tried to add the following flag: -skip-auth-regex=.\*api.\* to the ouath proxy container, the operator managed to reach the deployment and load the data sources and dashboards, but when trying to edit them or add a new ds I get a "Missing rights" notice: "You are not allowed to modify this datasource. Please contact your server admin to update this datasource.". 

### What did you expect to happen?

Grafana operator to be able to access grafana deployment on http port instead of trying to access https port
OR Grafana Operator to be logged in automatically

### Did this work before?

It worked with the previous api version, as following:
Kind: Grafana
apiVersion: integreatly.org/v1alpha1
Now I upgraded operator and deployment to work with api version, as following:
apiVersion: grafana.integreatly.org/v1beta1

### How do we reproduce it?

1. Deploy Grafana Operator with basic configuration v5.6.0
2. Deploy Grafana deployment v9.2.6 containing ouath proxy container + Grafna datasource connecting to grafana instance
3. Watch Operator logs

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafna Operator: v5.6.0
Grafana: v9.2.6
OS: linux
Deployed on Openshift

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @TiferetJackson,

Welcome to the :grafana: community support forums !!

We are excited that you joined our OSS community. Please read about some of the [FAQs](https://community.grafana.com/faq) in the community :slight_smile: 

Grafana's current latest stable version is 10.1.x and the version you are using is a bit older now. Also, there are numerous bug fixes and improvements had been made along the releases (see [Changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md))

The recommendation would be to test this in the recent stable version and if that does not work then feel free to report it here. (for now, I will close this issue).
