### ISSUE TITLE
InteractiveTable: Add doc examples for usage of CellProps

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#80978]
Some [added documentation](https://developers.grafana.com/ui/latest/index.html?path=/docs/experimental-interactivetable--basic) for how to use and type custom cell usage would be nice. What exactly is exposed and how should it be used? Using the example provides something similar to this
```
        {
          row: {
            original: { teamName, orgName },
          },
        }: CellProps<LdapTeam, void>
``` 

What else exists on the object and how can it be used? Is it possible to infer types directly in InteractiveTable so that `CellProps` is not needed? To get the current cell value, is this the best approach?

**Comment by JoaoSilvaGrafana** [comment]
I guess we could add an example on that, but I think part of the point of our InteractiveTable is that it is just a wrapper on [react-table](https://tanstack.com/table/latest/), we mention that at the start and point to their documentation to read more about it, which is where `CellProps` come from. So I don't know how much we add examples here or just expect people to read docs of react-table 🤷

**Comment by tskarhed** [comment]
Good point, I think some examples would be good/sufficient.
