### ISSUE TITLE
Product Area: x509 errors on all datasources

### ISSUE THREAD

**Issue by antoine-dhersin** [grafana/grafana#80994]
### What happened?

We installed a grafana container running on azure connected to a Managed Mysql instance on Azure. Since the MySQL integration, all the datasources are displaying a x509 errors. We set a skip verify to connect to Azure Elasticsearch but we have the same error using the Azure Monitor integration:

unexpected error Get "https://management.azure.com/subscriptions?api-version=2019-03-01": x509: certificate signed by unknown authority

### What did you expect to happen?

Connecting to the datasource whithout cert error

### Did this work before?

Yes if we don't use mysql as system database

### How do we reproduce it?

1. Deploy grafana as a container on Azure
2. Integrate MySQL managed by Azure with SSL/TLS support
3. Try to add any datasource using certificate

### Environment (with versions)?

Grafana: 8.4.0
OS: Windows
Browser: Brave

### Grafana platform?

Docker

### Datasource(s)?

All

**Comment by antoine-dhersin** [comment]
Hi, do you have some news about this issue? Thanks :-)

**Comment by yosiasz** [comment]
https://community.grafana.com/t/x509-everywhere-when-using-azure-mysql/112824/6

**Comment by usmangt** [comment]
Hi @antoine-dhersin

I see that you already found the answer on the community forum so closing this issue
