### ISSUE TITLE
Alerting: Alerts resolved while silenced do not send new notifications until repeat_interval

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#80996]
### What happened?

When a firing alert resolves while silenced and the silence is then removed. If the alert then quickly re-triggers (before `repeat_interval` passes) then a firing notification will not be sent for this alert. 

If the alert remains firing, it will send a firing notification when repeat_interval is hit. 
If the alert resolves again, it will send a resolved notification.

Specifically: 
1. An alert is triggered.
2. A silence is created to suppress the alert.
3. The alert resolves while the silence is still in effect.
4. This leads to a scenario where the alert, if re-entering the firing state quickly, may not generate a notification.

### What did you expect to happen?

After the following sequence:

1. An alert is triggered.
2. A silence is created to suppress the alert.
3. The alert resolves while the silence is still in effect.

If then alert re-triggers quickly (before next repeat_interval), a firing notification is sent.

Alternatively, we could send a resolve notification after the silence is removed.

### Did this work before?

No.

### How do we reproduce it?

1. Create an alert that will regularly flap and connect it to a route with a repeat_interval that is longer than the flap period. Ex. Alert runs every 30s, flaps every 1m, repeat interval > 1m.
2. While the alert is firing, silence it.
3. Wait until the flapping alert resolves.
4. Remove the silence.
5. Wait until the alert fires again and note that no alert notification will be sent.

### Cause

The root cause of this behavior lies in the fact that the upstream Alertmanager embedded in Grafana-managed alerting uses an internal notification log (nflog) to deduplicate notifications for the same alert group. This ensures that notifications are not sent more frequently than the configured repeat_interval.

In the described situation, the resolving alert is silenced, preventing it from writing to the nflog. Subsequently, when the silence is lifted, if the alert starts firing again the Alertmanager checks the nflog. Since the resolve write was prevented, the nflog indicates that the previous state was firing instead of resolved. If this prior firing notification was recent enough, not enough time will have passed to surpass the `repeat_interval`, resulting in the skipping of the notification.

While this behavior may align with the technical specifications of the Alertmanager, it is not the desired outcome from the perspective of Grafana-managed alerting.

At this point, it remains unclear whether the fix should be implemented upstream, in Grafana, or both.

- A mitigation could be to continue to send resolved notifications to the internal AM for 15m, similar to the Prometheus ruler. This is not a full fix depening on `repeat_interval`/`group_interval`/`silence` length.
- Another mitigation could be to always send states (even normal) to internal AM.
- Alernatively, solutions on the AM side such as https://github.com/prometheus/alertmanager/issues/226 or updating the nflog for silenced resolved alerts.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by 1tft** [comment]
Following bug exists:
-     An alert is triggered.
-     A silence is created to suppress the alert or a normal daily silence starts after alert has been triggered.
-     The alert resolves while the silence is still in effect.
-     No resolved message is sent. Also no resolve message after repeat interval.
