### ISSUE TITLE
time shift issue

### ISSUE THREAD

**Issue by sylviapari** [grafana/grafana#8100]
hi 

I'm trying to use the time shift feature to compare graphs.Both are scripted dashbords the first graph time range is 2mins. when i am exceeding the time range shift it is directly showing 10days shift.example if the graph range is 124s if i give the time shift as 125s then the time is jumping to 10 days shift in the graph have shared the screen shots please refer.
![dashboard1](https://cloud.githubusercontent.com/assets/27336205/24951180/2762c120-1f91-11e7-958d-a074348bd662.PNG)
![dashboard2](https://cloud.githubusercontent.com/assets/27336205/24951181/27d7310e-1f91-11e7-87eb-db101db02258.PNG)
![afterissue](https://cloud.githubusercontent.com/assets/27336205/24951183/29bf5db6-1f91-11e7-8e3b-dc3775b6008d.png)
![beforeissue](https://cloud.githubusercontent.com/assets/27336205/24951185/2b4c611a-1f91-11e7-89e4-f43a00c74027.png)

**Comment by torkelo** [comment]
I am unable to replicate this, when I specified 123s in timeshift it works as expected. Sure the dashboard time range was not changed between tests?

**Comment by sylviapari** [comment]
There is no change in the dashboard time range between the test.
![afterissue](https://cloud.githubusercontent.com/assets/27336205/24992669/405a6c96-2040-11e7-87b6-a5265226af45.png)
![beforeissue](https://cloud.githubusercontent.com/assets/27336205/24992670/405c2da6-2040-11e7-8428-514f23b8d8c2.png)

**Comment by sylviapari** [comment]
hi 

any update?

Thanks 
sylvia

**Comment by torkelo** [comment]
Still unable to replicate

**Comment by torkelo** [comment]
closing this, till unable to replicate and  no other similar report
