### ISSUE TITLE
Postgres Plugin generates msg="Failed connecting to Postgres" err="invalid option: \"Files\\\\\\\\GrafanaLabs\\\\\

### ISSUE THREAD

**Issue by craftzneko** [grafana/grafana#81008]
### What happened?

Connecting to postgres DB in azure fails with
msg="Failed connecting to Postgres" err="invalid option: \"Files\\\\\\\\GrafanaLabs\\\\\\\\grafana\\\\\\\\data\\\\\\\\tls\\\\\\\\f44631f5-68c8-4cdb-99ba-83321f7ef406generatedTLSCerts\\\\\\\\root.crt'\""

I am not providing a root CA as its set to require and didnt think i needed one but even if i provide one it doesnt work.

The problem seems to be that grafana is installed in the standard installation lcoation in windows C:\program files which has a space in. When i configure certificate content it creates a file here tlsRootCert="C:\Program Files\GrafanaLabs\grafana\data\tls\f44631f5-68c8-4cdb-99ba-XXXXXXXXgeneratedTLSCerts\root.crt" but clearly when using that as the connection string it fails on the space between program files. No idea how to sovle this seems like this is a bug that can only be solved in correcting the code to deal with spaces in paths when using certificate content

Confirmed - when i create a folder and use file path without a space it works. So the issue is that using certificate content creates a cert in a location with a space and doesnt handle quoting it.

### What did you expect to happen?

Connect

### Did this work before?

No

### How do we reproduce it?

1. Create db in azure
2. connect
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

**Comment by craftzneko** [comment]
The problem seems to be that grafana is installed in the standard installation lcoation in windows C:\program files which has a space in. When i configure certificate content it creates a file here tlsRootCert="C:\\Program Files\\GrafanaLabs\\grafana\\data\\tls\\f44631f5-68c8-4cdb-99ba-XXXXXXXXgeneratedTLSCerts\\root.crt" but clearly when using that as the connection string it fails on the space between program files. No idea how to sovle this seems like this is a bug that can only be solved in correcting the code to deal with spaces in paths when using certificate content

**Comment by craftzneko** [comment]
Hi, I am not sure how much more I can provide. I perhaps didn't explain it very well the first time.

I configured the certificate to be loaded from this location C:\Program Files\GrafanaLabs\grafana\data\tls

When trying to use this. the grafana log contains this error

msg="Failed connecting to Postgres" err="invalid option: "Files\\\\GrafanaLabs\\\\grafana\\\\data\\\\tls\\\\f44631f5-68c8-4cdb-99ba-83321f7ef406generatedTLSCerts\\\\root.crt'""

It's clear here that after the space in c:\program its thinking the next bit is an option (as options probably separated by spaces hence why its referring to just the last part of the path after the space Files\\\\GrafanaLabs\\\\grafana\\\\data\\\\tls\\\\f44631f5-68c8-4cdb-99ba-83321f7ef406generatedTLSCerts\\\\root.crt'""

I fixed it for myself by just storing the cert in a path without a space, further confirmation this is the problem as I am using the same Postgres database with the same certificate just changed the location it was stored in. I was using grafana version 10.2.3. Hope that helps

**Comment by gabor** [comment]
hi @craftzneko , with the pull request https://github.com/grafana/grafana/pull/81353 merged, we changed how these certificates are handled, and those `generatedTLSCerts/*` files will not happen anymore, so that should fix your problem, when it is released.

if it does not, reply back and we can reopen the issue.
