### ISSUE TITLE
Unable to delete provisioned contact point

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#81014]
### What happened?

Recently we removed some contact points and notification policies that were no longer used.  We provision these via yaml files.  I removed both the notification policy and the contact point from our yaml files.   The notification policy was removed when we restarted grafana however the contact point is still there.  It is marked as "Unused" and the Delete button is greyed out so it seems I have no way through the UI to clean this up.

### What did you expect to happen?

I expected it to either be removed when it was removed from the provisioned yaml file OR to have the ability to manually remove it from the UI.

### Did this work before?

unsure, I don't think we've done this previously

### How do we reproduce it?

1.  provision contact point from yaml
2. restart grafana
3. remove contact point from yaml
4. restart grafana

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.3
OS: mac
Browser: chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

n/a

**Comment by whoissteven** [comment]
+1, I am also dealing with this.

**Comment by rmawhinnie** [comment]
This is impacting us as well, would love to see this looked into :D

**Comment by pdmckenzie** [comment]
we're dealing with this too.  Please prioritize higher if possible :D

**Comment by AnEddieAllen** [comment]
This is also impacting us

**Comment by bnayahu0** [comment]
also us dealing with it. even deleting from the api not works...

**Comment by KaplanSarah** [comment]
Please refer to https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#import-contact-points

There is a field in the yaml file: deleteContactPoints specific for deleting receivers/contact points.

**Comment by danfinn** [comment]
That's a less than ideal workflow.  For those of us using gitops workflow I now how to make another (one time) commit to remove the contact point.  Could we get the button fixed that is greyed out now allowing deletion?

**Comment by twaslowski** [comment]
Just ran into this as well using terraform provider 3.25.4 with Grafana 9.2. The suggested workflow is highly inconvenient.
