### ISSUE TITLE
grafana does not attempt to connect to influxdb

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8103]
Similar to #5283, when I try to configure grafana to connect to influxdb, I also get "undefined error"

To try and debug this...
Set "logging" to trace - nothing.
Last mesage is "Looking for App Dashboard updates" then nothing.

If I do "strace -e connect -fp $(cat /var/run/grafana-server.pid)", nothing. Not a single connect attempt is made. If I run tcpdump on the other end, it sees nothing. Neither lsof or netstat show any sign of a socket to the influxdb server.

If I use strace to see what my browser sends grafana, I see something like this:

[pid 27703] read(8, "PUT /api/datasources/1 HTTP/1.1\r\nHost: 127.0.0.1:3001\r\nConnection: keep-alive\r\nContent-Length: 294\r\nAccept: application/json, text/plain, */*\r\nOrigin: http://127.0.0.1:3001\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36\r\nContent-Type: application/json;charset=UTF-8\r\nReferer: http://127.0.0.1:3001/datasources/edit/1\r\nAccept-Encoding: gzip, deflate, sdch, br\r\nAccept-Language: en-US,en;q=0.8\r\nCookie: grafana_sess=5746574657465746; grafana_user=admin; grafana_remember=f8baf8baf8baf8baf8baf8baf8baf8baf8baf8baf8baf8ba\r\n\r\n{\"id\":1,\"orgId\":1,\"name\":\"staging\",\"type\":\"influxdb\",\"typeLogoUrl\":\"\",\"access\":\"direct\",\"url\":\"http://10.10.100.100:8086\",\"password\":\"XXXXX\",\"user\":\"XXXXX\",\"database\":\"XXXXXXX\",\"basicAuth\":false,\"basicAuthUser\":\"\",\"basicAuthPassword\":\"\",\"withCredentials\":false,\"isDefault\":false,\"jsonData\":{}}", 4096) = 891

So grafana is getting told correctly how to connect, it just isn't doing it.

The greater mystery is that there are no clues about why it isn't or how to fix.

**Comment by eighteen14k** [comment]
Also similar to https://github.com/grafana/grafana/issues/6357
Same version, Centos 6.7.

I can connect to "10.10.100.100:8086" from the grafana server (but not from the browser.)

**Comment by eighteen14k** [comment]
Oh this is just silly.

"Access: direct" - browser attempts to verify "data source"
"Access: proxy" - grafana verifies "data source".

That's the inverse of what I would expect.

**Comment by analbeard** [comment]
WTF. I've just wasted two hours on this - that's so misleading. Thanks for providing the solution though!
