### ISSUE TITLE
Azure monitor datasource in grafana cannot select multiple netapp volumes

### ISSUE THREAD

**Issue by WABAM2406** [grafana/grafana#81051]
### What happened?

When I try to create a new alert I cannot select multiple netapp volumes in the resource selector.
However I am able to select multiple resources of another type eg, vm's or key vaults.
PS the volumes are in the same RG and region.
![image](https://github.com/grafana/grafana/assets/156316681/18cd859e-04a6-4f30-8b9d-54583696d4dc)

When I go to the advanced selector I am however able to specify additional volumes as seen below:
![image](https://github.com/grafana/grafana/assets/156316681/71377406-6822-41d7-be9e-256c398c9ad5)

Why is it not possible to do this in the selector above? Now I need to specify each of my volumes one per one which takes a long time.

### What did you expect to happen?

I expect to be able to select multiple netapp volumes in the scope selector.

### Did this work before?

This is my first time working with the azure monitor datasource so I have no idea.

### How do we reproduce it?

1. Create a new alert rule in grafana with the azure monitor datasource.
2. Try to select multiple netapp volume resources in the scope selector. (Not the advanced selector)

### Grafana platform?

Kubernetes

### Datasource(s)?

azure monitor

**Comment by aangelisc** [comment]
Thank you for reporting this @tonypowa. If you specify multiple NetApp volumes using the advanced resource picker does the query succeed? If so then we can look at adding support for this namespace to our multi-resource picker.

**Comment by aangelisc** [comment]
I have verified this myself and created a PR to support this namespace (#84779) 😊

**Comment by aangelisc** [comment]
Closed by #84779
