### ISSUE TITLE
Prometheus: Default to calling the `/label/<name>/values` endpoint instead of `/series`

### ISSUE THREAD

**Issue by colega** [grafana/grafana#81059]
**Why is this needed**:

It's been a while since Prometheus implemented the support for the `match[]` param in the `/label/<name>/values`: 3 years. Downstream projects also implemented this a couple of years ago.

However, the default behavior is still to call the expensive `/series` endpoint. The justification for that is that the old implementation of the endpoint doesn't fail, but returns more values than needed when it doesn't recognize the matcher param.

Customers who provision their datasource through code often forget or misconfigure the "Prometheus Type" as it's not mandatory, which makes their Grafana call the expensive `/series` endpoint, which can't be fulfilled (see: Prometheus, Mimir, Cortex and more importantly: GEM) because it tries to bring millions of entire series in one shot when the query builder is opened. Best outcome is to see some kind of limit error or a 4xx status code when using query builder, worse is to OOMKill an ingester, or querier, or query-frontend, or any combination of those.

We've received multiple support escalations and answered multiple ad-hoc queries regarding this.

**What would you like to be added**:

I would like to make the default behavior to assume that the Prometheus backend supports this, and have a specific opt-out at this point.

**Who is this feature for?**

For anyone who runs a non-years-old Prometheus-compatible backend. Especially important for GEM customers.

**What are the risks?**

If an old implementation is called with the matcher param, it will silently ignore it and return more label values than expected: this will cause the query builder or a template variable in Grafana have more items than expected. This is a minor drawback at this point IMO.

**Comment by bohandley** [comment]
Hi @colega! Yes, this is a good feature request and the @grafana/observability-metrics squad has this in mind. To do this we have a few things we have to work on first and a few things we need to refactor before we can safely remove the series endpoint.

1. The metrics browser is dependent on the series endpoint. We need to refactor this code. https://github.com/grafana/grafana/issues/70777
2. We still have customers that use older versions of Prometheus that don't support the `match[]` param in the `/label/<name>/values` endpoint. We need to refactor our type and version support to handle these cases and still support the series endpoint if users need it.
3. We are currently refactoring the Grafana Prometheus code and [building a frontend library](https://github.com/grafana/grafana/pull/77762). This will take a least another month for the library. We will then begin using it in core grafana prometheus. Once this library work is done, we can begin looking at the changes for removing the series endpoint.

In the meantime, we recently merged a small change that touches upon this request here. #80774 

So for the time being, the full feature request is blocked by current work but it is something we are looking to allocate resources to in the future.
