### ISSUE TITLE
[Bug] Alert state is not  re-evaluated

### ISSUE THREAD

**Issue by jozic** [grafana/grafana#8108]
- What Grafana version are you using? 4.2
- What datasource are you using? graphite
- What OS are you running grafana on? ubuntu 14.04
- What did you do? setup an alert
- What was the expected result? alert to change state once condition is met/not met
- What happened instead? alert state doesn't change 

Once the alert was setup it went to Ok state, then at some point (legitimately) changed  to ALerting state and never got back to Ok, though the alert condition evaluates to False

![image](https://cloud.githubusercontent.com/assets/124249/24986922/ff4d153e-1fca-11e7-96da-8435c46fce9f.png)

When I press "Test Rule" it evaluates value correctly

![image](https://cloud.githubusercontent.com/assets/124249/24987285/162ea0a4-1fcd-11e7-92c1-33ed7ef94eff.png)

Metric B is a hidden metric, defined as

![image](https://cloud.githubusercontent.com/assets/124249/24987319/57042a40-1fcd-11e7-911b-7169d787695c.png)

**Comment by haron** [comment]
I am experiencing the same bug, using exactly same setup (Grafana 4.2.0, Ubuntu 14.04). While testing the rule I see that condition expression includes `true`, although all clauses are actually `false`:

    conditionEvals: [[true OR false] OR false] = true
    logs:
        1: message Condition[0]: Eval: false, Metric: XX, Value: 0.000
        3: message Condition[0]: Eval: false, Metric: YY, Value: 0.000
        5: message Condition[0]: Eval: false, Metric: ZZ, Value: 0.000

**Comment by torkelo** [comment]
This might have fixed it, #7992,  if you use sqlite3 database the state history event never get's written sometimes due to concurrent write table locked error, (just the history event, the alert rule changes state)
