### ISSUE TITLE
Request-URI Too Large

### ISSUE THREAD

**Issue by wangxiangyu** [grafana/grafana#8109]
hi， 
    I am using templating to filter the data and the query is failed. I found "Request-URI Too Large" error when grafana do the query to backend db(influxdb).
    I am using nginx as proxy in front of grafana and obviously it was nginx that blocked this query. I find that when I choose All on one of the variables in templating, all the values under this variable are passed in the url to backend db which causes "Request-URI Too Large".
    Is there any way to solve this problem? Or  is this one of defects of grafana in design?

**Comment by torkelo** [comment]
In many cases you can specify a custom All value, like `.*`  (regex wildcard) in the template variable options. This way Grafana will not use all values but a the regex string you specified

**Comment by Nodraak** [comment]
Hi!

After searching for a while the origin of the "Network Error: undefined(undefined)" error on my dashboard, I found this to be the root cause.

The error message I got was really not helpful, would it be feasible to include the http status code in the error message ? (at least when the error is undefined)

**Comment by kbolino** [comment]
This doesn't work for when the URI is too large because multiple values have been selected. Maybe Grafana should use a POST request when the query exceeds a certain size, then this issue would never come up and it would be fixed automatically without the user having to Google for the problem.

**Comment by erez-rabih** [comment]
@torkelo I'm having the exact same issue with a prometheus data source
Is there a reason not to use the POST verb to get data from prometheus as well?

**Comment by torkelo** [comment]
reopened https://github.com/grafana/grafana/issues/17342#issuecomment-496817673 and made a comment looks like not all Prometheus api's support POST but could be the docs are wrong
