### ISSUE TITLE
Alert email(smtp) with Env doesnnt work

### ISSUE THREAD

**Issue by orientzc** [grafana/grafana#8112]
- What Grafana version are you using? 
Grafana image of latest, it means 4.2.0
- What did you do?
docker run -p 3000:3000 -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=smtp.aaa.com:25" -e "GF_SMTP_FROM_ADDRESS=xxx" -e "GF_SMTP_USER=xxx" -e "GF_SMTP_PASSWORD="yyy" -e "GF_SMTP_SKIP_VERIFY=true"
- What was the expected result?
alert notifications test success: send email
- What happened instead?
wrong: docker logs is
t=2017-04-13T09:16:45+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="x509: certificate signed by unknown authority"
t=2017-04-13T09:16:45+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="x509: certificate signed by unknown authority"
t=2017-04-13T09:16:45+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=10.251.0.201 time_ms=28ns size=48

so i edit the run.sh, Like it
#!/bin/sh

: "${GF_PATHS_DATA:=/var/lib/grafana}"
: "${GF_PATHS_LOGS:=/var/log/grafana}"
: "${GF_SMTP_ENABLED:=true}"
: "${GF_SMTP_HOST:=smtp.163.com:25}"
: "${GF_SMTP_USER:=chenjian@163.com}"
: "${GF_SMTP_PASSWORD:=dfdfdfdwer}"
: "${GF_SMTP_SKIP_VERIFY:=true}"
: "${GF_SMTP_FROM_ADDRESS:=chenjian@163.com}"

# Allow access to dashboards without having to log in
# Export these variables so grafana picks them up
export GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
export GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
export GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL:-http}

echo "Starting a utility program that will configure Grafana"
setup_grafana >/dev/stdout 2>/dev/stderr &

echo "Starting Grafana in foreground mode"
exec /usr/sbin/grafana-server \
  --homepath=/usr/share/grafana \
  --config=/etc/grafana/grafana.ini \
  cfg:default.paths.data="$GF_PATHS_DATA"  \
  cfg:default.paths.logs="$GF_PATHS_LOGS"   \
  cfg:default.smtp.enabled="$GF_SMTP_ENABLED"    \
  cfg:default.smtp.host="$GF_SMTP_HOST"     \
  cfg:default.smtp.user="$GF_SMTP_USER"     \
  cfg:default.smtp.password="$GF_SMTP_PASSWORD"    \
  cfg:default.smtp.skip_verify="$GF_SMTP_SKIP_VERIFY" \
  cfg:default.smtp.from_address="$GF_SMTP_FROM_ADDRESS"
and everything is ok. but where is wrong with my ways with envs. what i missed? could anyone help me? Thanks.

**Comment by torkelo** [comment]
```
-e "GF_SMTP_SKIP_VERITY=true"
 ```

looks like you misspelled verify

**Comment by orientzc** [comment]
Thanks. but there is  -e "GF_SMTP_SKIP_VERIFY=true" in my command. and the issue #8112 is edited by me from -e "GF_SMTP_SKIP_VERITY=true" to  -e "GF_SMTP_SKIP_VERIFY=true". i make a mistake, but in fact, i used -e "GF_SMTP_SKIP_VERIFY=true".

**Comment by torkelo** [comment]
strange, not sure what cold be the case, just tested `export GF_SMTP_SKIP_VERIFY=true` and it picked up the setting just fine.

**Comment by orientzc** [comment]
sorry. why is the issue closed? i tried
 -e "GF_SMTP_SKIP_VERIFY=true"
but it doesnt work. and the logs is #8112. could anyone help me ?

**Comment by torkelo** [comment]
during startup grafana prints config options overriden by env variables.

You should see this during startup:

 ```
NFO[04-14|07:49:55] Config overriden from Environment variable logger=settings var="GF_SMTP_SKIP_VERIFY=true"
```

**Comment by orientzc** [comment]
@torkelo 
the logs:
t=2017-04-14T08:39:04+0000 lvl=info msg="Starting Grafana" logger=main version=4.1.2 commit=v4.1.2 compiled=2017-02-13T12:13:31+0000
t=2017-04-14T08:39:04+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-04-14T08:39:04+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_ENABLED=true"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_HOST=hq.smtp.test.cn:25"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_USER=orientzc@test.cn"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_PASSWORD=*********"
t=2017-04-14T08:42:19+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_SKIP_VERIFY=true"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_FROM_ADDRESS=orientzc@test.cn"
t=2017-04-14T08:39:04+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_ALERTING_EXECUTE_ALERTS=true"
t=2017-04-14T08:39:04+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-04-14T08:39:04+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-04-14T08:39:04+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-04-14T08:39:04+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-04-14T08:39:04+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-04-14T08:39:04+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-04-14T08:39:04+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-04-14T08:39:04+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-04-14T08:39:04+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-04-14T08:39:04+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-04-14T08:39:04+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-04-14T08:39:04+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-04-14T08:39:04+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-04-14T08:39:04+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=

everthing is ok. but email test doesnnt work. the logs:
t=2017-04-14T08:44:33+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="gomail: could not send email 1: 550 5.7.1 Client does not have permissions to send as this sender"
t=2017-04-14T08:44:33+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="gomail: could not send email 1: 550 5.7.1 Client does not have permissions to send as this sender"
t=2017-04-14T08:44:33+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=10.251.0.201 time_ms=90ns size=48

but if i  edit run.sh, it works very well.

**Comment by torkelo** [comment]
looks like your getting another error now, you are not getting `x509: certificate signed by unknown authority` any more but `gomail: could not send email 1: 550 5.7.1 Client does not have permissions to send as this sender´ try changing your from_address to something your smtp server accepts

**Comment by orientzc** [comment]
@torkelo thanks. but i use the same parameter in run.sh(the run.sh is like above), and it works. but  i use the same parameter in Envs, and it doesnnt work. so i think the from_address is right. and what do i miss?

**Comment by torkelo** [comment]
{GF_SMTP_FROM_ADDRESS:=chenjian@163.com}"

r="GF_SMTP_FROM_ADDRESS=orientzc@test.cn"r="GF_SMTP_FROM_ADDRESS=orientzc@test.cn

Look different, I dont know what could be wrong.

**Comment by orientzc** [comment]
Thanks. because the security, so the value of GF_SMTP_FROM_ADDRESS in run.sh is false.(chenjian@163.com and orientzc@test.cn) but in fact, the value of GF_SMTP_FROM_ADDRESS in run.sh is same as the Envs. do i only meet the problem? my password contains #, so i try """#password#"""" and #pssword#, but they donnt work.

**Comment by orientzc** [comment]
i am ok. Thanks everybody.
