### ISSUE TITLE
Alerting: Text in the email is not bolded when should be

### ISSUE THREAD

**Issue by pavelklecansky** [grafana/grafana#81131]
### What happened?

When I used \*\*bold** to make text bold, text in email is not bold. 
![image](https://github.com/grafana/grafana/assets/28779692/0f703326-b7f6-403e-a176-5026d8d75a33)
![image](https://github.com/grafana/grafana/assets/28779692/1cba3ee0-2b57-4f07-ac77-32ae80becd0c)

### What did you expect to happen?

In documentation, it is specified that in notification template we can [format text in bold and italic, and add or remove line breaks.](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/). So I would expect that when I use \*\*bold** to make text bold that text in email will be bold.

### Did this work before?

Didn't use it before.

### How do we reproduce it?

1. Create notification template with \*\*bold** text
2. Send testing email on contact point that has specified this template.

### Environment (with versions)?

Grafana: 10.2.2
OS: 
Browser: 

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hi @pavelklecansky 

At the moment, email clients can't render Markdown. Some other integrations understand markdown (like Slack). 

Grafana doesn't render Markdown into HTML for email notifications. This is indicated in the docs that you made reference to:

> You cannot use notification templates to:
> Add HTML and CSS to email notifications to change their visual appearance.
