### ISSUE TITLE
Grafana: When Running Multiple Grafana Pods It's Getting - failure: contact points: could not find object using provided id and hash

### ISSUE THREAD

**Issue by ilangrs** [grafana/grafana#81139]
### What happened?

When running multiple Grafana pods I keep getting the following error:
 "failure: contact points: could not find object using provided id and hash"
 It causes the pod to restart multiple times.

### What did you expect to happen?

I expected Grafana to spin up without any issues

### Did this work before?

No

### How do we reproduce it?

1. Use contact points and run Grafana in HA mode inside K8S

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.2
OS: amazon-eks-node-1.27-v20240117
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
hello @ilangrs 

thank you for reporting this issue

Can you share the configuration file for Grafana (without any sensitive data), specifically highlighting how the HA (High Availability) mode is set up?
Are there any specific steps you follow when you 'use contact points', as mentioned in your reproduction steps? Please elaborate on this process.

**Comment by bengoldenberg09** [comment]
hey @tonypowa,
this is our deployment:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitor
  labels:
    app: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        karpenter.sh/do-not-evict: 'true'
    spec:
      volumes:
        - name: config
          configMap:
            name: grafana
            defaultMode: 420
            optional: false
        - name: dashboards-config
          configMap:
            name: dashboards-config
            defaultMode: 420
            optional: false
        - name: alerts-log-based
          configMap:
            name: grafana-alerts-log-based
            defaultMode: 420
            optional: false
        - name: alerts-metric-based
          configMap:
            name: grafana-alerts-metric-based
            defaultMode: 420
            optional: false
        - name: alerts-message-template
          configMap:
            name: grafana-alerts-message-template
            defaultMode: 420
            optional: false
        - name: alerts-contact-points
          configMap:
            name: grafana-alerts-contact-points
            defaultMode: 420
            optional: false
        - name: alerts-notification-policy
          configMap:
            name: grafana-alerts-notification-policy
            defaultMode: 420
            optional: false
        - name: dashboard-main
          configMap:
            name: grafana-dashboard-main
            defaultMode: 420
            optional: false
        - name: dashboard-overview
          configMap:
            name: grafana-dashboard-overview
            defaultMode: 420
            optional: false
      containers:
        - name: grafana
          image: >-
            grafana/grafana:10.1.2
          ports:
            - name: service
              containerPort: 3000
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
            - name: grafana-alert
              containerPort: 9094
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: <name>
                  key: <key>
                  optional: false
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <name>
                  key: <key>
                  optional: false
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_LOG_MODE
              value: console file
            - name: GF_LOG_LEVEL
              value: info
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: '3'
              memory: 6Gi
            requests:
              cpu: '3'
              memory: 6Gi
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              mountPropagation: None
            - name: config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
              mountPropagation: None
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              mountPropagation: None
            - name: alerts-log-based
              mountPath: /etc/grafana/provisioning/alerting/alert_rule_log_based.yaml
              subPath: alert_rule_log_based.yaml
              mountPropagation: None
            - name: alerts-metric-based
              mountPath: /etc/grafana/provisioning/alerting/alert_rule_metric_based.yaml
              subPath: alert_rule_metric_based.yaml
              mountPropagation: None
            - name: alerts-contact-points
              mountPath: /etc/grafana/provisioning/alerting/contact_point.yaml
              subPath: contact_point.yaml
              mountPropagation: None
            - name: alerts-message-template
              mountPath: /etc/grafana/provisioning/alerting/message_template.yaml
              subPath: message_template.yaml
              mountPropagation: None
            - name: alerts-notification-policy
              mountPath: /etc/grafana/provisioning/alerting/notification_policy.yaml
              subPath: notification_policy.yaml
              mountPropagation: None
            - name: dashboard-main
              mountPath: /etc/dashboards/Arango/main.json
              subPath: main
              mountPropagation: None
            - name: dashboard-overview
              mountPath: /etc/dashboards/Cloud/overview.json
              subPath: overview
              mountPropagation: None
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: grafana
      serviceAccount: grafana
      automountServiceAccountToken: true
      shareProcessNamespace: false
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        runAsNonRoot: false
        fsGroup: 472
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: grafana
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      enableServiceLinks: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
`

this is our grafana.ini file:

`[analytics]
check_for_updates = false

[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

# Metrics available at HTTP URL /metrics and /metrics/plugins/:pluginId
[metrics]
# Disable / Enable internal metrics
enabled = true
# Disable total stats (stat_totals_*) metrics to be generated
disable_total_stats = false

[live]
allowed_origins = "<orgin>"

[server]
protocol = "http"
enable_gzip = true
router_logging = true
root_url = "<url>"

[dashboards]
default_home_dashboard_path = "/etc/dashboards/test.json"

[unified_alerting]
enabled = true
admin_config_poll_interval = "30m"
alertmanager_config_poll_interval = "17m"
ha_listen_address = "${POD_IP}:9094"
ha_peers = "grafana-alerting.monitor:9094"
ha_advertise_address = "${POD_IP}:9094"

[alerting]
enabled = false
evaluation_timeout_seconds = 60
max_annotation_age = 2d
max_annotations_to_keep = 300000

[annotations]
cleanupjob_batchsize = 300

[annotations.api]
max_age = 2d
max_annotations_to_keep = 300000

[auth.google]
enabled = true
client_id = ""
client_secret = ""
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
allow_sign_up = true
allowed_domains = ""
[caching]
enabled = true
backend = memory

[caching.memory]
max_size_mb = 350

[auth]
disable_login_form = true


[users]
auto_assign_org_role = Editor

[database]
type = postgres
host = grafana-psql.monitor.svc.cluster.local
name = grafana
user = "user"
password = ""
max_open_conn = 1000
ssl_mode = disable

[remote_cache]
type = memcached
connstr = grafana-memcached.monitor.svc.cluster.local:11211
`
this is our dashboard config:
`apiVersion: 1
providers:
- name: dashboards
  type: file
  updateIntervalSeconds: 30
  options:
    path: /etc/dashboards
    foldersFromFilesStructure: true
`
this is our contact point config file:
`apiVersion: 1
contactPoints:
  - orgId: 1
    name: default-cp
    receivers:
      - uid: default-cp
        type: slack
        disableResolveMessage: true
        settings:
          recipient: "#alerts-grafana"
          token: "<token>"
          title: |
            {{ template "title-log-based" . }}
          text: |
            {{ template "text-log-based" . }}
  - orgId: 1
    name: Test
    receivers:
      - uid: Test
        type: slack
        disableResolveMessage: true
        settings:
          recipient: "test"
          token: "<token>"
          title: "test"
          text: "text"`
this is our policies file:
`apiVersion: 1
policies:
  - orgId: 1
    receiver: default-cp
    group_by:
      - alertname
    group_wait: 30s
    group_internval: 5m
    repeat_interval: 12h
    routes:
      - receiver: test
        group_by:
        - alertname
        group_wait: 1d
        group_internval: 5m
        repeat_interval: 12h
        matchers:
          - name = test`
         
if you have any other data you need plz ping me

**Comment by JohnnyQQQQ** [comment]
The problem here is that somehow the hash of the configuration has changed between the time you loaded the config and the time you updated the config. The configuration is guarded by optimistic locking, which does check that in between a read and an update the config hasn't changed. For this we use the hash of the config.

This might have happened if you kept the config open for a while and someone else changed it in the meantime or your HA setup is not working correctly and you send the request with a loadbalancer to multiple instances, creating a race condition.

Closing this for now, if you still face the problem let us know.
