### ISSUE TITLE
[Feature request] Introduce settings for refreshing tabs in background

### ISSUE THREAD

**Issue by irandom** [grafana/grafana#8113]
In #7218, a feature was implemented that disables refreshing tabs that are in background. That is not what one can expect by default, yet the feature is useful with no doubt.

I propose to introduce settings in dashboard that can disable refreshing in background, so user can disable refreshing for heavy tabs. The general idea is shown in screenshot, a toggle is underlined in red:

![refresh-in-background](https://cloud.githubusercontent.com/assets/1736815/25000593/1f798fe4-206c-11e7-8c26-0494ba2eefb4.png)

**Comment by torkelo** [comment]
I do no think this is going to be required anymore, given this change:

If earlier dashboard refresh was supressed, force a new one on page becoming visible
https://github.com/grafana/grafana/pull/8076

**Comment by levanovd** [comment]
#8076 doesn't solve the problem in case of dashboard with lots of complicated graphs. Requesting data from Graphite may take up to minute (or even fail time to time) if backends are under heavy load.

Getting more or less relevant data in a minute is absolutely different experience than seeing data immediately after tab switch (even if data is _a bit_ outdated).

Taking look on graphs time to time to see if there's no critical artefacts is the main use case of Grafana in our team. Breaking this feature in #7218 critically hit the usability of Grafana.

So I suggest not to close the issue so fast without deep investigation.

**Comment by torkelo** [comment]
Will reopen to se if others have the same requirement. But we are trying hard to not add options for every use case under the soon. Grafana is toggle fest already.

**Comment by bashgeek** [comment]
Same here. I've three dashboards opened in three browser tabs. Every now and then I switch through them to check the data. Unfortunately now I have to switch to the tab and manually hit the refresh button in all of them, wait for the update (takes a few seconds) and go over to the next one. If I accumulate this during a day, I spent at least 10-20 minutes more time on just refreshing graphs manually and wait for the results.

I have no doubt that the initial change in #7218 might be useful to a lot of people, although in our use-case (and apparently for others, too) it's causing more problems than solving. I see your point in not wanting to add yet another option, but I think this was a critical change to the workflow of Grafana. So it's either going back to the old behaviour or adding an option to the dashboards, this way every can chose it by themselves what behaviour they prefer.

**Comment by torkelo** [comment]
We have made a change so it will automatically refresh when you give a tab focus

**Comment by SimenB** [comment]
When refresh-on-focus is released, my think would be that I'd press ctrl+tab through the tabs, then open the first. Then I'd get mostly updated data when viewing them. For us, this is an acceptable workaround, but I can see argument that it would be nice to turn it off.

For instance you might have really big screen with 4 separate dashboards open at the same time. You can't focus on more than one at a single time, so without manually switching focus (or running some app that can do it for you), they can never get updated.

**Comment by torkelo** [comment]
>For instance you might have really big screen with 4 separate dashboards open at the same time. You can't focus on more than one at a single time, so without manually switching focus (or running some app that can do it for you), they can never get updated.

Grafana checks for document visibiility, I think that would still be true in that case. But I agree there can still be an argument to add an option.

**Comment by SimenB** [comment]
Ah, you are correct, just tested it 😄

**Comment by dprime** [comment]
I'm in favour of having the option to enable background refreshing. It takes some time to update my status pages and I have several open in my browser and this change has materially impacted the usefulness of those dashboards. Perfectly happy for it to be disabled by default as it does certainly save on browser cpu, network, and storage queries.

**Comment by peterw-cf** [comment]
Also in favour of this. I have a dashboard on a second screen and i always have to click on it once to get it to refresh even when it is the top most window. This feature would be great to have.

**Comment by Culmert** [comment]
I would like this to; being able to make sure that dashboards update regardless of ...anything I guess. 
I won't be able to control whether the browser windows stay on top, but I might want to link actions to events occuring in a dashboard; e.g. trigger a certain Javascript when some background color changes.

On a side note, and also to further show the use of a "refresh in Background"-feature: In my experience, it is not enough that the browser window is visible for the auto update to work; I often keep a Grafana dashboard open in a web browser on my second screen. Despite being visible, it sits all day without updating.

**Comment by spydmobile** [comment]
Yes please, it will make multi desktop, multi monitor etc far easier

**Comment by Jelmergu** [comment]
I think the option should not be turn autorefresh on, but rather turn autorefresh off. It seems to me that that seems to be more intuitive. There is no one who wants to stare at data that could be 20 minutes old. I use Graftana on a second screen while the main screen does something else, which is rather impossible to do with #7218. 

I think that there are fewer people that use #7218, than that there are people who find it a nuisance

**Comment by torkelo** [comment]
Not sure what you mean? We don’t modify auto refresh. And you can have Grafana on multiple monitors and auto refresh.

**Comment by dprime** [comment]
Auto refresh only works when the browser window has focus. This means that if you have a separate browser window or tab, it only refreshes when you click to that window/tab.

**Comment by Jelmergu** [comment]
With #7218 autorefresh when Graftana is out of focus was turned off. The OP suggests having a toggle to turn autorefresh on when Graftana is out of focus. I suggest that Graftana should autorefresh even when out of focus by default, and that the toggle is to make Graftana NOT autorefresh when out of focus. 

Like Culmert said before me, make Graftana refresh regardless of the circumstances and let the user choose if he/she wants to limit Graftana's refresh abilities.

**Comment by torkelo** [comment]
No https://github.com/grafana/grafana/issues/7218 is about not autofreshing when tab is not visible.  

I can have 5 visible chrome tabs/windows and all auto refresh

**Comment by forever765** [comment]
I also hope that we can give the option to us. Is there any progress in this issue?

**Comment by mjunek** [comment]
I too would like to see this as an option to enable refreshing then the browser is in the background. 

I have a page open that I reference every half an hour or so, on a separate tab. The configuration in my environment is that the Grafana server is externalised via a reverse proxy, which forces authentication prior to sending requests to the Grafana server. This authentication times out if there are no requests for 10 minutes (auth cookie expired).

My problem is not that I am forced to just press refresh to get new data - when I switch back to the inactive Grafana tab, I get red errors that the page couldn't refresh, from which I then have to manually refresh the page, re-authenticate / enter credentials for the reverse proxy, sign back into Grafana, and select the dashboard.

As a workaround, I am using the following plugin to Chrome - https://chrome.google.com/webstore/detail/always-active-window-alwa/ehllkhjndgnlokhomdlhgbineffifcbj?hl=en --- this prevents Grafana detecting it's in the background.
Not my preferred choice as I prefer to use different a different browser where this plugin is not available.

**Comment by ssavva05** [comment]
I want this feature too. It is very useful when we have alerts running. Are there any plans to implement it in the future?

**Comment by atavakoliyext** [comment]
I would also like to see this as a configurable option. Refreshing only when the tab is in focus has consequences on deployments using an [external proxy for authentication](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/) and when the session token gets refreshed.

Ideally, users can avoid having to experience the authentication refresh whenever they switch to their tab after an idle period, if it can be done in the background.

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!
