### ISSUE TITLE
[Feature request] Clock-like formatting of time duration

### ISSUE THREAD

**Issue by leonsery** [grafana/grafana#8114]
Currently **duration** is formatted as strings, for example: 
**3 days, 10 hours, 0 minutes, 24 seconds**. 
It's very long string and it will be better to have clock-like formatting option, for example:
**03:10:00:24** or **3d 10:00:24**

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
