### ISSUE TITLE
Data trails: UI improvements

### ISSUE THREAD

**Issue by catherineymgui** [grafana/grafana#81169]
Overview section
- Currently the description seems to fill the width of the screen. Cap description column at 360px
![Image](https://github.com/grafana/grafana/assets/5264102/63564dd0-3dc6-4cbb-ab3a-0614ffd071e2)

Breakdown
- [Switch from radiobuttongroup component to a select dropdown when there’s more than 6 items
](https://raintank-corp.slack.com/archives/C0630AYC4SY/p1701803233429689?thread_ts=1701706912.267339&cid=C0630AYC4SY)
![Image](https://github.com/grafana/grafana/assets/5264102/b1f53808-8b2a-4418-971e-53272167cb77)

Padding on action button row
- Tighten padding from 16px —> 8px between items in this line
![Image](https://github.com/grafana/grafana/assets/5264102/20251921-b24b-4262-bb18-47b33d9d4db7)

Add to dashboard button
- This is the only button in the row without any icon - can we add the “+” icon?
![Image](https://github.com/grafana/grafana/assets/5264102/57d02222-3396-49af-950d-4b5dfa76187b)

**Comment by darrenjaneczek** [comment]
The "add to dashboard" button is currently missing.
![image](https://github.com/grafana/grafana/assets/38694490/3147d5c2-78f3-43c8-92c3-0f3c44580342)

I will reduce the spacing on this action panel, similar to what was requested for the top panel.
