### ISSUE TITLE
[Bug] Table transfrom field always returns to "Time series to raws" value

### ISSUE THREAD

**Issue by django-kz** [grafana/grafana#8116]
Hello ! 
I have an issue with "Table" panel. 
- What Grafana version are you using? Version 4.2.0 (commit: 349f3eb)
- What datasource are you using? Zabbix
- What OS are you running grafana on? Centos 7.3
I am trying to change the "Table transform" field to anything else then "Time series to raws". It changes, but after 3-5 seconds it returns to its default value, which is "Time series to raws".

**Comment by torkelo** [comment]
What does your query return? The table panel switches to time series to rows if the data returned is not of type table of docs. Which is correct. Maybe a bug in the zabbix data source. 

Does your query return time series?

**Comment by django-kz** [comment]
I am using Zabbix datasource.

**Comment by torkelo** [comment]
ok, then there might be an issue with that data source. 

The table panel always switch to "Time series to rows" if the data format returns from the query is not in table or docs format
