### ISSUE TITLE
Dashboards Grafana - infinite fetching of dashboard data

### ISSUE THREAD

**Issue by edgarkz** [grafana/grafana#81180]
### What happened?

After upgrading Grafana as part of OMD package we are facing infinite dashboard loading issues along with data consumption from datasources. 
Please see attached - query tasks just loads tons of data and never stop.

![image](https://github.com/grafana/grafana/assets/68842306/1c37d7a6-ae75-42f1-a10f-d08497480b3c)

### What did you expect to happen?

Dashboard panel should be loaded and fetching stopped once graph is populated

### Did this work before?

Yes, on our main instance of grafana 7.5.13 everything seem to work fine
![image](https://github.com/grafana/grafana/assets/68842306/19cf32d1-5c30-41cc-85ba-ca4e0df347d9)

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 9.5.6
OS: centos 7 
Browser: Chrome  Version 120.0.6099.234 (Official Build) (arm64)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus 2.28.1

**Comment by edgarkz** [comment]
Can someone please assist?

**Comment by tonypowa** [comment]
Hello @edgarkz  thank you for reaching out 

Could you elaborate on the repro steps. and share the specific query or queries that are running when you experience the infinite loading?

Also, could you be able to share any relevant Grafana server logs from around that time?

**Comment by edgarkz** [comment]
Hii @tonypowa,
We already removed old instance and started from fresh instead of upgraded version due to above issues.
