### ISSUE TITLE
[bug] Repeating a fixed span single stat panel changes size to 12

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8118]
Please include this information:
- What Grafana version are you using? 4.2.0
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 6
- What did you do? Created repeating single stat panel, selected a second data source
- What was the expected result? A new single stat panel of the same size on the same row
- What happened instead? SingleStat panel was enlarged to fill half the row and the next one appeared on the row below of the same size.

![Uploading before.png…]()
![Uploading after.png…]()

**Comment by eighteen14k** [comment]
Before .. things are laid out nicely ...
![before](https://cloud.githubusercontent.com/assets/6872041/25013207/19788b32-20b6-11e7-8b99-a6b94ddbecd8.png)

**Comment by eighteen14k** [comment]
And after, when it has all gone horribly wrong...

![after](https://cloud.githubusercontent.com/assets/6872041/25013233/33622120-20b6-11e7-9cff-de3ed86a02b4.png)

**Comment by torkelo** [comment]
you can only have one repeating panel on each row. Grafana will automatically try to fill the whole row with as many values you have selected. The min span option controls how small the panels are allowed to be.

**Comment by torkelo** [comment]
btw, I know this is not ideal. But trying to simplify the dynamic dashboard use case a bit. So if you want to use repeating panels you need to dedicate a single row for that panel you want to repeat.

**Comment by eighteen14k** [comment]
What I'd like to happen is for
- the rows to repeat (per host)
- the Graph to show multiple instances (GROUP BY)
- the SingleStat to repeat to the right for each volume

This would be very useful in many other use cases that I can think about.

If I had 100 volumes, and just did a display of volumes, Grafana packs out a grid, maybe 10 rows, with 10 volumes per row (for example), so why does it behave like this here? :(

**Comment by eighteen14k** [comment]
If there is a "Min Span", why not "Max Span"? Would that help layout?
