### ISSUE TITLE
Tempo Explore: Under certain circumstances the "disable" button is toggled on query edit

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#81192]
The disable query button will somtimes toggle on/off simply by editing a query:

![image](https://github.com/grafana/grafana/assets/2272392/dd8179cc-8620-4448-aa0f-311ab9e41bf9)

Then by simply adding a space to the query the query is re-enabled. I have gotten this to toggle the other way as well. Going from enabled -> disabled on edit.

![image](https://github.com/grafana/grafana/assets/2272392/44879602-2d71-4170-ac86-fd1771c9e2e2)

This may not be directly related to "Copy Query From Search" but I can reliably repro the issue with that feature.

Steps to repro:

1. Load Explore/Tempo Datasource
2. Go to the "Search" tab
3. Select a service name from the drop down
4. Go to the "TraceQL" tab
5. Click "Copy query from search"
6. Click the disable query/eyeball button. (The query is now disabled)
7. Edit the query in any way. (The query is toggled back to enabled).

**Comment by joey-grafana** [comment]
Looks like this is a more general issue that we've had for a while! 👎 Fix in https://github.com/grafana/grafana/pull/81343
