### ISSUE TITLE
The Time columns using $__timeGroup are grouped according to UTC time boundaries. 1 hour late compared to Europe/Berlin localtime.

### ISSUE THREAD

**Issue by bohuang-work** [grafana/grafana#81207]
### What happened?

- Grafana connected to MySQL DB.
- The time column of all data are saved in UTC in database.
- Grafana server and MySQL server all running in cloud server of ubuntu with default timezone Europe/Berlin +1.0:00. 

The plot is shifted 1 hour before local time (Europe/Berlin) after applied `$__timeGroup`:
<img width="1693" alt="Screenshot 2024-01-24 at 20 27 49" src="https://github.com/grafana/grafana/assets/66997911/6cbeb9ce-3d39-46c1-9cb4-d725ebfc4978">

If directly query the date from database, it shows right time which matches local time.
Table A: with `$__timeGroup` 1min interval.
Table B: directly query datetime from DB.
<img width="212" alt="Screenshot 2024-01-24 at 20 25 30" src="https://github.com/grafana/grafana/assets/66997911/6e492464-3e5c-49fa-9a00-372d294ff49f">

Table A query:

`SELECT
  $__timeGroup(date, 1m) as time_sec,
  COUNT(event) as "event_count",
  event as metric
FROM event_db.event_table
WHERE $__timeFilter(date) and event = "some_event_name"
GROUP BY 1, event
ORDER BY 1
`

Table B query:
`
SELECT date as time_sec FROM event_db.event_table ORDER BY date DESC
`

### What did you expect to happen?

the plot is not shifted and matches the browser time.
temporary solution: add +3600 after `date` 

### Did this work before?

no

### How do we reproduce it?

1. connect a Grafana with Mysql
2. group a datetime column and show the counts of another column
3. see plots

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: V10.2.3
OS: mac os
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

MySQL 10.5.21

**Comment by bohuang-work** [comment]
seems same issue here: https://github.com/grafana/grafana/issues/51525

**Comment by gabor** [comment]
hi @bohuang-work , yes, it seems to be the same issue as https://github.com/grafana/grafana/issues/51525 , so i'll closet this one as duplicate. and i recommend following https://github.com/grafana/grafana/issues/51525 for updates. thanks!
