### ISSUE TITLE
[Feature Request] Support for selecting all values for invisible variables

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8121]
Please include this information:
- What Grafana version are you using? 4.2.0

What I would like to do is have a variable that is something like this:

SHOW TAG VALUES FROM df_value WHERE host =~ /$host$/

... make that a hidden variable (so that users can't see it) BUT ...
... have all of the values auto-select so that a "Repeat" in a panel can refer to "volume" and display multiple panels (one for each volume) without a user need to select 'All'

**Comment by torkelo** [comment]
Have you tested to select all then hide it then save dashboard?

**Comment by eighteen14k** [comment]
It's not enough to "Save" them all selected, for example, when the list is loaded in time the panel is loaded, the contents of the variable chance. This is most common where (for example) different volumes are present on different hosts.

But I see what you're saying:
- don't set the list to reload
- construct the query to return the fullest list possible
- select them all from the UI
- make the variable invisible
- use the variable and let grafana worry about what variable elements are/aren't present

I'm not sure that this is a very obvious way to achieve the outcome?

**Comment by torkelo** [comment]
Not sure what is not working here. 

This dashboard as a server variable with All, selected, and Refresh on Dashboard Load:
http://play.grafana.org/dashboard/db/graphite-templated-nested-copy?orgId=1

Seems to work, have not tested to add a server though, but the variable is doing a query to update its values.

**Comment by eighteen14k** [comment]
Ok... here's what I'm finding.

I have two variables, host and disk volume names. Not all hosts have the same set of volume names.

The variable I want to display is hosts.
The variable I want to hide is volume names.

If host X has volumes A,B and host Y has volumes C,D then I *must* save the dashboard with both of those hosts visible for the template variable to have A,B,C,D iin it.

If I save the panel with both host X & Y visible then I can come back at any time and see both hosts with both of their volumes associated with them. All good.

If I deselect host Y, everything is updated, looks good.
If I then re-select host Y, volumes C & D do not reappear.
It does not matter if the volumes variable is "Reload: Never" or not.

I've attached the JSON for the page to this.

It almost appears like the "Reload: Never" is ignored and that the values in $volume are reloaded anyway.


I think the "Reload" in the "Template variables" needs to be a bit more complex. That needs to be reloaded. This problem is very easy to demonstrate.

**Comment by torkelo** [comment]
Strange, that scenario (I think) works here:
http://play.grafana.org/dashboard/db/graphite-templated-nested-copy

If I change the app variable the hidden server variable updates to the contain the servers for that app, and the panels repeated by that variable are updated accordingly .
