### ISSUE TITLE
grafana 10.2.2 use mariadb , start err `signing_key` (`key_id`) key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by bluebiubluebiu** [grafana/grafana#81225]
### What happened?

install grafana and use mariadb , will show start err  `signing_key` (`key_id`) key was too long; max key length is 767 bytes

### What did you expect to happen?

no err

### Did this work before?

no

### How do we reproduce it?

1. linux version : centos 7.9       3.10.0-1160.el7.x86_64
2.grafana 10.2.2
3.databases: mariadb：mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1

### Environment (with versions)?

Grafana:10.2.2
OS:centos 7.9 
Browser: google

### Grafana platform?

None

**Comment by bluebiubluebiu** [comment]
logger=settings t=2024-01-25T06:07:57.0696709Z level=info msg="Starting Grafana" version=10.2.2 commit=161e3cac5075540918e3a39004f2364ad104d5bb branch=HEAD compiled=2023-11-20T13:18:33Z
logger=settings t=2024-01-25T06:07:57.069946818Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2024-01-25T06:07:57.069962905Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2024-01-25T06:07:57.069971911Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2024-01-25T06:07:57.069980366Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2024-01-25T06:07:57.069988408Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2024-01-25T06:07:57.069996567Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2024-01-25T06:07:57.070004424Z level=info msg=Target target=[all]
logger=settings t=2024-01-25T06:07:57.070027438Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2024-01-25T06:07:57.070036344Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2024-01-25T06:07:57.070044101Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2024-01-25T06:07:57.070052026Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2024-01-25T06:07:57.07006031Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2024-01-25T06:07:57.070067982Z level=info msg="App mode production"
logger=sqlstore t=2024-01-25T06:07:57.07016269Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2024-01-25T06:07:57.072072634Z level=info msg="Starting DB migrations"
logger=migrator t=2024-01-25T06:07:57.080470332Z level=info msg="Executing migration" id="add unique index signing_key.key_id"
logger=migrator t=2024-01-25T06:07:57.080962724Z level=error msg="Executing migration failed" id="add unique index signing_key.key_id" error="Error 1071 (42000): Specified key was too long; max key length is 767 bytes" duration=490.452µs
logger=migrator t=2024-01-25T06:07:57.081024727Z level=error msg="Exec failed" error="Error 1071 (42000): Specified key was too long; max key length is 767 bytes" sql="CREATE UNIQUE INDEX `UQE_signing_key_key_id` ON `signing_key` (`key_id`);"

**Comment by tolzhabayev** [comment]
@andresmgot could you take a look please?

**Comment by andresmgot** [comment]
Hi,

This seems to be caused by an old version of MariaDB/MySQL: https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes

Note that one of the requirements of Grafana is MySQL 5.7+: https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases

This migration [was introduced in 10.2](https://github.com/grafana/grafana/pull/75487) so in order to avoid it, you would need to install Grafana 10.1.

Hope that helps!

Please, reopen the issue if the problem persist with a recent version of the database.
