### ISSUE TITLE
[Bug]Number of measurements incorrect

### ISSUE THREAD

**Issue by sLuvpreet33** [grafana/grafana#8123]
Please prefix your title with [Bug] or [Feature request]. 

Please include this information:

- What Grafana version are you using?
	Grafana v4.2.0 (commit: 349f3eb) 

- What datasource are you using?
Influxdb

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
See nginx log results using logparser

- What was the expected result?
I got different measurements

- What happened instead?
Measurements should have been same

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

I think this is a bug, not sure.

But have a look.

![screenshot from 2017-04-14 01-06-21](https://cloud.githubusercontent.com/assets/23127804/25021308/5d5947d0-20af-11e7-8e63-8a87ad96d6e4.png)

In this picture, as you can see, I have chosen a log file, from the influxdb datasource. I am writing to influxdb by telegraf.

It shows me 8 different fields, you can see those in picture.

Now look at this picture,

![screenshot from 2017-04-14 01-06-38](https://cloud.githubusercontent.com/assets/23127804/25021429/bbcce13c-20af-11e7-8842-de17b6310984.png)

I chose all fields, by putting * in the field option. Now, in the graph, you will see that I have 11 different fields.

This is what I think is different and I cannot get it. Why * shows 11 fields and otherwise I can see only 8 fields.

Also, when I want to create an alert on query "SELECT * FROM "netdata_access.log" WHERE $timeFilter", I cannot chose a single field as all are included in only one query.

What is the possible solution of this problem ?

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab, then trigger the field selection drop down, you should see a query sent to influxdb to fetch fields, can you show the response from InfluxDB? Click on the query in the network tab that appeared when you tried to select the field, then click on response to the right in Chrome dev tools. 

For the second question, alerting conditions acts on queries, if a query returns multiple series then the threshold is evaluated per series. If you only want to set alert on one series you need to create a specific query that returns only that series

**Comment by sLuvpreet33** [comment]
http://127.0.0.1:8999/api/datasources/proxy/3/query?db=telegraf&q=SHOW FIELD KEYS FROM "netdata_access.log"&epoch=ms

this is when I select * .

127.0.0.1:8999/api/datasources/proxy/3/query?db=telegraf&q=SELECT "agent" FROM "netdata_access.log" WHERE time > 1492102512211ms and time < 1492113092721ms&epoch=ms

this is when I select a single field namely "agent".


First query is `"select * from netdata_access.log limit 2"` 
and second is `"select agent from netdata_access.log limit 2"`
and third query is `"SHOW FIELD KEYS FROM "netdata_access.log""`

Here are the corresponding results,

![screenshot from 2017-04-14 02-02-39](https://cloud.githubusercontent.com/assets/23127804/25023172/760fdbca-20b6-11e7-9195-86229a045561.png)

**Comment by torkelo** [comment]
Please look at chrome dev tools network and response from the show field keys query, want to see what response grafana geta
