### ISSUE TITLE
Docker container: behind nginx reverse proxy lead to gatway timeouts 504

### ISSUE THREAD

**Issue by carcinoma** [grafana/grafana#81258]
### What happened?

Using the latest docker image (which currently corresponds to v10.3.1) behind a nginx reverse proxy lead  to many gateway timeouts and sporadic reachability.

### What did you expect to happen?

The grafana container should be reachable flawlessly.

### Did this work before?

After fiddling around a downgrade to 10.2.3 made it work.  

### How do we reproduce it?

1. Run grafana 10.3.1 in a docker container
2. Configure it to use in reverse proxy mode by specifing:
- GF_SERVER_DOMAIN=mydomain.com
- GF_SERVER_ROOT_URL=https://mydomain.com/grafana/
- GF_SERVER_SERVE_FROM_SUB_PATH=true
3. Configure nginx reverse proxy in a docker container and configure grafana endpoint:
```

upstream grafana {
  server grafana:3000;
}

location /grafana/ {
    proxy_set_header Host $http_host;
    proxy_pass http://grafana;
}

# Proxy Grafana Live WebSocket connections.
location /grafana/api/live/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $http_host;
    proxy_pass http://grafana;
}
```
4. Access the grafana instance via the web browser lead to the gateway timeout
5. Accessing via the host the containers are running on with `curl <grafana-container-ip>:3000/grafana/ -v -H "Host: mydomain.com"` lead to the gateway timeout
6. Accessing via the inside of the **nginx** container with `curl <grafana-container-ip>:3000/grafana/ -v -H "Host: mydomain.com"` lead to the gateway timeout
7. Accessing via the inside of the **grafana** container with `curl 127.0.0.1:3000/grafana/ -v -H "Host: mydomain.com"` **works**

Additional observations:
- Configuring without the sub path made it work
- In debug log mode it is visible that in this rare cases where the request is successful the timing are reasonable from the grafanas perspective (80ms) where as the timing for the caller is around 20s. 
- After rebooting the entire node grafana seems to be accessible for a while (2min).

Note:
- I am running my domain with a Let's encrypt SSL certificate behind an dynamic IP address.

### Is the bug inside a dashboard panel?

No, basically everywhere

### Environment (with versions)?

Grafana: 10.3.1
OS: Debian 12
Browser: Firefox 122

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by dkatheininger** [comment]
Maybe this is connected to https://github.com/moby/moby/issues/47211 ?

**Comment by carcinoma** [comment]
> Maybe this is connected to [moby/moby#47211](https://github.com/moby/moby/issues/47211) ?

Hm, the symptoms are different here. They talk about "no route to host" where as in this case the route is not an issue. Also a reboot solved the issue in their case but not here.

Nevertheless i switched back to the 10.3.1 image for inspection … guess what … its gone. Even after a reboot it now works with 10.3.1 …

I will close the issue.
