### ISSUE TITLE
[Feature request] Enhance histogram feature

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8126]
Some of these feature is requested by my panel plugin user.
https://github.com/mtanda/grafana-histogram-panel

1. Set min and max value for x-axis (filter out anomaly value from graph)
2. Normalize by percent value (show `count` / `total count`)
3. Support bucket size (specify value range for each bucket)
4. Support unit for x-axis
5. Support to show individual histogram showing for multiple time series, and stack show

**Comment by torkelo** [comment]
3) is already supported (setting bucket size)

**Comment by mtanda** [comment]
> Set min and max value for x-axis (filter out anomaly value from graph)
We can utilize PromQL to support this in datasource.
By using `>`, `<`, `clamp_min()`, or `clamp_max()`, we can set min/max value.

I'm not sure Graphite or other datasource has such feature.
If meta query support such transformation, it could be alternative.

**Comment by mtanda** [comment]
> Support bucket size (specify value range for each bucket)

If the value range is 1-100, and the option value is 10, it makes 10 buckets.
If the option value is 5, it makes 20 buckets. The first buckets contains 1-5.

It is supported in original PR.
https://github.com/grafana/grafana/pull/949/files#diff-c47e5ca0d4f2e6bec248268700b673b7R103

**Comment by torkelo** [comment]
> If the value range is 1-100, and the option value is 10, it makes 10 buckets.
> If the option value is 5, it makes 20 buckets. The first buckets contains 1-5.

option value? I am not sure I understand what you want here, what is the algorithm and what purpose would it be? 

Closing this as it's better to have each feature request in a separately issue clearly detailed with use cases and descriptions for why the feature is useful :)

**Comment by mtanda** [comment]
> option value? I am not sure I understand what you want here, what is the algorithm and what purpose would it be?
I don't know the purpose, because it is already support in original PR...

I open several feature request for histogram.
Now, Grafana itself support histogram/heatmap, so I'll stop to develop my panel plugins.
