### ISSUE TITLE
Elasticsearch: Broken SigV4 authentication

### ISSUE THREAD

**Issue by youribonnaffe** [grafana/grafana#81294]
### What happened?

After an upgrade from Grafana 10.2.2 to 10.3.1 we noticed the Elasticsearch datasource stopped working.
Calls made to Elasticsearch are failing with 403 errors.
We are using AWS SigV4 authentication for this datasource (Access & Secret key).

We found this change https://github.com/grafana/grafana/pull/77386 that could be related, where the HTTP client for the datasource has been changed.

### What did you expect to happen?

Elasticsearch datasource to work with Grafana 10.2.3+

### Did this work before?

10.2.2

### How do we reproduce it?

Troubleshooting by running a local proxy showed the version 10.2.3 or 10.3.1 is not longer sending the Authorization header.

Below are the details of the request in both situation:

(not working)
```
GET / HTTP/1.1
Host: host.docker.internal:12344
User-Agent: Go-http-client/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.5
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Datasource-Uid: ffe25624-dc07-452d-9263-92325137920f
X-Forwarded-For: 192.168.65.1
X-Grafana-Device-Id: 2bc1725ca744db81d32143ef9145988c
X-Grafana-Nocache: true
X-Grafana-Org-Id: 1
X-Grafana-Referer: http://localhost:3001/connections/datasources/edit/ffe25624-dc07-452d-9263-92325137920f
X-Plugin-Id: elasticsearch
```

(working)
```
GET / HTTP/1.1
Host: host.docker.internal:12344
User-Agent: Grafana/10.2.2
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.5
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/eu-west-3/es/aws4_request, SignedHeaders=host;x-amz-date, Signature=REDACTED
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Amz-Date: 20240125T171555Z
X-Datasource-Uid: edae5189-b01e-4b3a-9004-1e70c2cc4c84
X-Forwarded-For: 192.168.65.1
X-Grafana-Nocache: true
X-Grafana-Org-Id: 1
X-Grafana-Referer: http://localhost:3001/connections/datasources/edit/edae5189-b01e-4b3a-9004-1e70c2cc4c84
X-Plugin-Id: elasticsearch
```

### Environment (with versions)?

Grafana: 10.2.3
OS: Mac
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch

**Comment by tolzhabayev** [comment]
@grafana/observability-logs please take a look

**Comment by matyax** [comment]
Thanks @tolzhabayev

**Comment by ivanahuckova** [comment]
Thank you @youribonnaffe for troubleshooting and reporting. @matyax I can work on this one. Will investigate if the new httpProvider from sdk is the source of the issue and if so, we will need to implement `status_source` within Elasticsearch the same way as we have done with Loki. @svennergr fyi

**Comment by svennergr** [comment]
Hi @youribonnaffe,

thank you for reporting this issue. I did a fix in https://github.com/grafana/grafana/pull/81814 that will be available in the next 10.3.x and 10.4.x release.

Best,
@svennergr

**Comment by nightswimmings** [comment]
This is preventing us from using 10.3.X, please release 10.3.4 :,)

**Comment by svennergr** [comment]
@nightswimmings You should expect a 10.3.4 release in March.

**Comment by svennergr** [comment]
10.4.0 and 10.3.4 should be released on the same date early March - so, unfortunately not sooner.
