### ISSUE TITLE
[bug] multi-page table panel refreshing to first page when refresh = off

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#8129]
- What Grafana version are you using?
4.2
- What datasource are you using?
influx
- What OS are you running grafana on?
centos
chrome browser on client

- What did you do?

Created panel with that contains paged results. 

- What was the expected result?

That the panel would stay on the currently selected page until clicking on another.

- What happened instead?
 
When viewing "deeper" pages the panel refreshes to the first page after about 5 seconds even if the dashboard refresh setting is off.

**Comment by torkelo** [comment]
That sounds very strange. unable to replicate it here. 

Are you getting the same on all table, are you getting it here:
http://play.grafana.org/dashboard/db/table-panel-showcase?orgId=1

**Comment by 3IMOH** [comment]
I did not see the behavior on that table. I seem to have fixed this by changing and saving a new time filter. It is odd as refresh has been off on this table since I created it. It was for sure refreshing though, as I saw the spinning icon in the upper right. I can't seem to be able to replicate this now.

**Comment by torkelo** [comment]
ok, closing this. please reopen if you are able to replicate it
