### ISSUE TITLE
[Bug] Received "NoData" Alerts even if it was set to Keep Last State

### ISSUE THREAD

**Issue by ofdeath** [grafana/grafana#8130]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
carbon
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
I added a new alert with conditions - WHEN avg() OF query(A, 10m, now) HAS NO VALUE
![image](https://cloud.githubusercontent.com/assets/20808100/25046074/538db810-216a-11e7-92f6-3a957fb049df.png)

- What was the expected result?
Receiving alerts only when one or some points has no value
![image](https://cloud.githubusercontent.com/assets/20808100/25046078/5ea06676-216a-11e7-9aa1-d85e09871cdc.png)

- What happened instead?
Received alerts even if no data or all values are null
![image](https://cloud.githubusercontent.com/assets/20808100/25046083/67e446da-216a-11e7-9ba1-907e3d67875f.png)
I expected that it'll be ignored when the grafana server was failed to get data from the datasource if I set the state of "If no data or all values are null" to "Keep Last State", but it sent alerts.
And it was same even when I changed the state of "If no data or all values are null" to Alerting, No Data, Keep Last State or OK.

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
anything interesting in grafana.log ?

**Comment by ofdeath** [comment]
Today I got 2 alerts, but I didn't find anything interesting in grafana log :(

**Comment by torkelo** [comment]
Did you enable debug logging? Could be a good idea for a day or two.

**Comment by ofdeath** [comment]
My server has too many logs, so it is not good to enable debug logging. Maybe I can make a new test server to test debug logging.

**Comment by ofdeath** [comment]
This is a debug log. 
There are two alerts - TA06 Site3 StreamScanner warning and TA06 Site4 StreamScanner warning.
But I got an alert of site4 only at 2017-04-18T21:43.
```
t=2017-04-18T21:42:12+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="TA06 Site3 StreamScanner warning" id=2
t=2017-04-18T21:42:12+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=34.844 alertId=2 name="TA06 Site3 StreamScanner warning" firing=false
t=2017-04-18T21:42:18+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:42:24+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="TA06 Site4 StreamScanner warning" id=3
t=2017-04-18T21:42:24+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=28.658 alertId=3 name="TA06 Site4 StreamScanner warning" firing=false
t=2017-04-18T21:42:28+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:42:38+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:42:47+0000 lvl=dbug msg="Checking for updates"
t=2017-04-18T21:42:48+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:42:58+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:43:08+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2017-04-18T21:43:12+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="TA06 Site3 StreamScanner warning" id=2
t=2017-04-18T21:43:12+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="TA06 Site4 StreamScanner warning" id=3
t=2017-04-18T21:43:12+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=10.818 alertId=2 name="TA06 Site3 StreamScanner warning" firing=false
t=2017-04-18T21:43:12+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=3 newState=alerting prev state=ok
t=2017-04-18T21:43:12+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=3 sent count=1
t=2017-04-18T21:43:12+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/ima-warning-admon?&panelId=4"
t=2017-04-18T21:43:15+0000 lvl=dbug msg="Image rendered" logger=png-renderer path=/vol/grafana/png/EMYSNQNmBFrkmAMlEIy0.png
t=2017-04-18T21:43:15+0000 lvl=info msg=uploaded logger=alerting.notifier url=
t=2017-04-18T21:43:15+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=1 isDefault=false
t=2017-04-18T21:43:15+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=3 notification=kr-ima-warning-jmoon
t=2017-04-18T21:43:15+0000 lvl=dbug msg="Sending webhook" logger=notifications.webhook url=<My Slack URL> http method=
t=2017-04-18T21:43:15+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=28.907 alertId=3 name="TA06 Site4 StreamScanner warning" firing=true
```

**Comment by daniellee** [comment]
There is only one alert firing in that debug log: TA06 Site4 StreamScanner. Was it triggered due to NoData or an error?

**Comment by ofdeath** [comment]
It was failed to get data points from data source but actually there are data points.
Sometimes it was failed because our data source is too busy.

**Comment by torkelo** [comment]
@ofdeath and your option for execution errors and no date is still `Keep last State and yet receive notifications on TSDB query errors/timeouts?

**Comment by ofdeath** [comment]
I got a slack notification
```
[Alerting] TA06 Site4 StreamScanner warning
jmoon test from ac02 StreamScanner has no value for 10 minutes.
NoData
Grafana v4.2.0Today at 6:43 AM
```

But I don't know when the value is "NoData".I think it is one of two cases - "If no data or all values ara null" or "If execution error or timeout", but I set them to "Keep Last State"

**Comment by torkelo** [comment]
But your alert rule is for HAS NO VALUE so that is what your alert rule is designed to test, just notificed this :) 

The no data state rule is no applicable if your alert condition specificially checks for no_data. 

Check your query and the query time range. Somehow it returns only nulls some times. Which is what your alert rule seems to check.

**Comment by ofdeath** [comment]
I have a question. 
If the condition has "HAS NO VALUE" and there are no datapoint by some reason like query error/timeouts, should I keep receiving the notifications even I set state to "Keep Last State"?

I think some people want to ignore that kind of errors - query errors/timeout.
I set the rule "If no data or all values are null" to "Keep Last State" because I want to ignore any cases of "all values are null".
Or could you add some other method to do it?

**Comment by daniellee** [comment]
@ofdeath for you, what's the difference between "HAS NO VALUE" and "all values are null"?  Maybe the wording is unclear and should be changed.

**Comment by torkelo** [comment]
> " because I want to ignore any cases of "all values are null".

hm.. this is strange, because. 

>ps. I'm sorry I didn't understand exact meaning of the option "HAS NO VALUE".

HAS NO VALUE means your query returns all nulls or no data points at all.

**Comment by ofdeath** [comment]
@daniellee Oh I'm sorry, I'm talking about two phrases in the page "Alert Config" of Alert - "HAS NO VALUE" in Conditions and "If no data or all values are null".

My requirement is that I want to receive a notification when one or some data points are null except the case that all data points are null. 
I just want to ignore the case that there are no data points by some errors - grafana was failed to get the data points occasionally.
Could I do that?

**Comment by ofdeath** [comment]
@torkelo I think "HAS NO VALUE" means there are some data points which is null.

**Comment by torkelo** [comment]
Yes, that is what the rule checks for, it is evaluated for every series, so if one series is all null the the rule will trigger and go into alerting state

**Comment by ofdeath** [comment]
@torkelo Yes, I understood. But I don't want to get a notification when all series are all null - I'm checking many series at once, because it is happened when grafana was failed to get data from data source.

**Comment by torkelo** [comment]
>  because it is happened when the grafana was failed to get the data from data source.

that would not generate a NoData alert I think. NoData means the query is returning nulls or no data.

you can enable logging of graphite query and response in alerting calls:

```
; this is at the to of the ini file in global scope
app_mode = development 

[log.console]
filters = tsdb.graphite:debug
```

Then we can see the raw response from graphite when the alert happens

**Comment by ofdeath** [comment]
Thank you! I'll try it today

**Comment by zzugg** [comment]
Hello, I am a friend of @ofdeath investigating this issue together.
I think we need to distinguish between 'no data' and 'no value'.
In other words, if all the data points' values are null, it can be fired by a 'Has no value' condition, but if the response is no data, I think it needs to follow the `If no data or all values are null` firing rule.
In our case, if the graphite's response has nothing(no time series info), we hope it follows the `If no data or all values are null`, i.e. `KeepLastState` with no firing.
How do you think about it?

**Comment by ofdeath** [comment]
I tried it and I finally understood that there are 3 cases which is firing alerts with condition "HAS NO VALUE"

1. some series have no value
2. all values are null (all series's values are null)
3. no data (no datapoints)

And I hope that the condition "HAS NO VALUE" don't trigger alert if it is case 3.
Because the name of rule is "HAS NO VALUE" and case 1&2 are related to values but case 3 is related to data points. :)

**Comment by ofdeath** [comment]
@torkelo 
Could you read my comment and reply about whether the idea is good or not acceptable?
Thank you!

**Comment by torkelo** [comment]
all null and no data points are seen as the same. (NO VALUE == NO DATA). 

I guess we need a new condition for your case if it's a common scenario / wish we might add new conditions to test against "no datapoints" or "all nulls"

**Comment by ofdeath** [comment]
Thank you, I hope that you add new good conditions for my case :)

**Comment by zyf0330** [comment]
Is there news?

**Comment by jgournet** [comment]
@torkelo :
Would it be possible to re-open this ticket and add that new condition ?
I'm having the same issue here.

**Comment by jgournet** [comment]
> I think we can wait, in v8 Grafana will have have a completely new alerting system

Thanks for the heads up ;)
