### ISSUE TITLE
Table Datalinks: support column alignment

### ISSUE THREAD

**Issue by skeagy** [grafana/grafana#81300]
### What happened?

Right-aligned column changed to left-aligned when adding a datalink via an override. I tried to add the datalink override first and the column alignment override second, but the order doesn't matter. Column alignment rule is ignored when a datalink is present, and when the datalink is removed, the column goes back to the correct setting.

### What did you expect to happen?

I expected column alignment to be independent of datalink setting, so that I can have a right aligned column with a hyperlink.

### Did this work before?

I don't know. First time I tried it was in my current version grafana-10.2.3-r0 x86_64 (Alpine Linux) on server, and Firefox client browser. I didn't check older versions.

### How do we reproduce it?

1.Create a table
2.Add override on column A, create a datalink.
3.Add override on column A, column alignment right (which will be ignored)
4. Remove the datalink override on column A, and the column alignment override should now be visible.

### Environment (with versions)?

Grafana: grafana-10.2.3-r0 x86_64
OS: 6.6.7-0-virt #1-Alpine SMP PREEMPT_DYNAMIC
Browser: Firefox 121.0.1 (64-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by radeonsk** [comment]
I have the same issue. Column alignment is not respected when there is data link.

I'm using Grafana 10.3.1, it was working in version 10.2.2.

**Comment by spbnick** [comment]
Same issue here with v11.1. As soon as I added a data link to a table, the column alignment jumped to the left, from the configured right.

**Comment by drew08t** [comment]
Thanks for sharing. Just to summarize, you are only experiencing this behavior during overflow? If not, please share a panel JSON.

This is what I'm seeing:

<img width="867" alt="image" src="https://github.com/grafana/grafana/assets/60050885/0b58e59e-3fd4-45c9-9706-847874a7c919">

**Comment by spbnick** [comment]
Yes, that particular behavior (left alignment when right is specified) is only seen on overflow.

There are other problems related to data links being used, like overflowing cell expansion on mouse-over not working sporadically (no expansion happening), and ellipsis appearing (which I like, but it's inconsistent with non-linked cells). I don't have time to report those separately right now, but tell me if you need more details, or would like me to go to other issues for that.

**Comment by drew08t** [comment]
I appreciate the detail @spbnick. Please create a new issue to capture that behavior when you have a chance, thanks!
