### ISSUE TITLE
Email alert not showing which server/monitor problem in aggregate graph 

### ISSUE THREAD

**Issue by kotarusv** [grafana/grafana#8131]
Setting up alert on groupby/aggregate graph not showing enough information on email from which server the alert got triggered. It is too tedious or not flexible to setup a graph for each server or monitor and hard code information in alert text/body. The Grafana should be able to indicate which server or monitor in the aggregated graph has issues in email body.

**Comment by torkelo** [comment]
The email should include the series name that triggered the threshold violation. 

How does the email look for you?

**Comment by kotarusv** [comment]
![7tfzbcxeuf8enk6j4qyn](https://cloud.githubusercontent.com/assets/7401609/25166102/8521f0e0-248e-11e7-9b8e-7ff361adaa31.png)
attached a recent alert. I created a group by graph which has multiple servers. I also setup a alert but alert doesn't have info about which server having issue.

**Comment by kotarusv** [comment]
I can't create separate graph per each setup the alert with name as servername for easy identification. It overkill

**Comment by torkelo** [comment]
what data source are you using? Can you show ouput from "Test Rule" button (expand all response rows)

**Comment by kotarusv** [comment]
Sure, am using influxDB as a data source. 

SELECT count("packets_received") FROM "ping" WHERE "datacenter" = 'ALLN' AND $timeFilter GROUP BY time(30s), "url" fill(0)

![test](https://cloud.githubusercontent.com/assets/7401609/25206047/9af43bf8-251a-11e7-86b6-d98d5ad2fdef.jpg)

**Comment by jregovic** [comment]
I see a similar issue with OpenTSDB datasources. The tags are not carried forward into the notification, so the JSON only contains the metric name:
`{"evalMatches":[{"value":21.9658756256104,"metric":"metrix.mem_used_percent","tags":null},{"value":9.81780624389648,"metric":"metrix.mem_used_percent","tags":null}],"ruleId":3,"ruleName":"Memory % Used alert","ruleUrl":"http://localhost:3000/dashboard/db/control-center-stats?fullscreen&edit&tab=alert&panelId=3&orgId=1","state":"alerting","title":";[Alerting] Memory % Used alert"}`

**Comment by torkelo** [comment]
This is related to backend OpenTSDB response handling (used in alerting) does not currently support alias patterns & series naming https://github.com/grafana/grafana/issues/7309
