### ISSUE TITLE
Grafana maxed out postgres connections causing mass alerts to trigger

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#81319]
### What happened?

We got a flood of alerts from grafana that had this error:

```
pq: sorry, too many clients already
```

We are using HA, we have 2 grafana pods with a postgres backend.  The default connection limit in postgres is 100 which seems more than adequate.  This postgres instance is only used by grafana.  Under "normal" operation, it looks like grafana only has around ~5 connections open to postgres.

Looking through the logs from grafana, this is the first sign of any error, I didn't see anything prior to this:
```
logger=ngalert.state.manager rule_uid=gkQRdCEVkz org_id=1 t=2024-01-25T21:55:06.354038281Z level=error msg="Failed to save alert state" labels="Prod-Teams=True, __alert_rule_namespace_uid__=fa44f676-3b57-474f-86c8-08803be24a34, __alert_rule_uid__=gkQRdCEVkz, alertname=Prod - EastUS - Failed Pods, datasource_uid=5ebb38d4-0b60-45dd-be01-3c641161dbd1, grafana_folder=FolderName, ref_id=Failed Pod Count" state="unsupported value type" error="pq: sorry, too many clients already"
```

the logs from both pods look about the same, no warning or mention of any issue and then all of a sudden everything failing because it's hitting the pgsql connection limit.

After this it was the flood of alerts.  After about 20 minutes we got recovery alerts for everything.  Strangely enough, none of these alerts were ever showing as firing in the grafana UI.

What would cause grafana to exhaust the default connection limit of 100?  I don't think bumping that limit is the right answer here but I'd also like to avoid this happening in the future.

I did find this older issue that didn't go anywhere but seems related
https://github.com/grafana/grafana/issues/27647

If grafana is still allowing an unlimited number of connections this seems like an issue

### What did you expect to happen?

grafana to not use over 100 connections to the postgres backend

### Did this work before?

Yes, this is the first time we've seen this

### How do we reproduce it?

1. not totally sure honestly
2.
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.3
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by danfinn** [comment]
just had this happen again however it appears to have recovered on it's own and quickly this time but we did get some alerts triggering with
```
pq: sorry, too many clients already
```
from postgres and grafana is all that is using this postgres instance

**Comment by danfinn** [comment]
I've still been actively working on this as it's causing production issues for us.  I've tried a few things but am still having problems.

I've set the following in my helm values under the database section:
```
grafana.ini:
  database:
    max_open_conn: 50
    ssl_mode: require
    url: postgres://user:$password$@grafanapgsql-primary.grafana.svc:5432/db
```

and we are still having issues.  At 1 second intervals I've been running the following command on the postgres server to get the connection count:

```
select count(*) from pg_stat_activity;
```

And I just caught it going up to 106.  I took at look at the connections and probably 95% of those or more were coming from grafana.

According to the docs here:
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#max_open_conn

this is the correct way to limit the database connections but grafana does not seem to be respecting that.

**Comment by danfinn** [comment]
I've lowered max_open_conn to 25 and we haven't had any issues in the past day.  I've been keeping an eye on the number of connections and I haven't seen it go over 40 ish.  I think what is happening is that because we are using HA as well as using HA for alerting that we are doubling the number of our connections from grafana, one from each pod.  It seems like this is overkill and could be improved but I don't know how HA works in alert manager.

I suspect it's alert manager because of the frequency of the increase in pgsql connections.  It's seems to be on a very regular pattern and I suspect it's timed with our alert rules kicking off. We don't have a lot of regular user traffic for looking at dashboards or explore or things like that.

I'm a bit concerned at what having to set this limit so low will mean for us in the future.  What happens as we add alerts?  What happens as user traffic increases and we have more users using dashboards and explore and whatnot?

**Comment by KaplanSarah** [comment]
The original issue appears to be solved.  Please open a new issue if there is a specific feature request.

**Comment by AbhiTaker** [comment]
Can someone from Grafana team provide an update on this issue? we are also facing the similar issue.

**Comment by jcalfee** [comment]
What does `show idle_in_transaction_session_timeout;` say?  I found my local loki exceeding connections on the server after network outages.  When I bounced the local loki-grafana stack the idle connections on the server did not go away.
