### ISSUE TITLE
Plugins: Calls to external APIs failing CORS pre-flight when Access-Control-Allow-Headers is in use

### ISSUE THREAD

**Issue by laurie71** [grafana/grafana#81312]
### What happened?

Our datasource plugin, which works well with Grafana 9, breaks with Grafana 10 as the API we're calling out to uses an `Access-Control-Allow-Headers` header as part of its CORS configuration. Grafana is adding an 'x-grafana-device-id` header which, of course, is not allowed by the API (see [https://github.com/grafana/grafana/blob/5e88d29814184d2a7cee70c581c373ecab6ee972/public/app/core/services/backend_srv.ts#L161](https://github.com/grafana/grafana/blob/5e88d29814184d2a7cee70c581c373ecab6ee972/public/app/core/services/backend_srv.ts#L161))

### What did you expect to happen?

The API call should complete successfully. I would suggest supporting an option in `BackendSrvRequest` to allow disabling this additional request header on a per-request basis (so by default the header will be set, but in a situation like mine I have a way of preventing that).

### Did this work before?

Using Grafana 9 this header is not set, and our plugin works as intended.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10
OS: macOS for my testing (but probably any)
Browser: Chrome for my testing (but probably any)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

custom datasource plugin we built for our customers to use

**Comment by tolzhabayev** [comment]
This header was introduced by https://github.com/grafana/grafana/pull/78685, please take a look @grafana/identity-access-team
