### ISSUE TITLE
[bug] hide series results in mismatch between graph and legend

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8132]
Please include this information:
- What Grafana version are you using? 4.2.0
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 6
- What did you do? Selected "Hide series with only zeros"

The query for the series is:
SELECT "value" FROM "pps" WHERE "host" =~ /^$host$/ AND "instance" =~ /^$channel$/ AND $timeFilter GROUP BY "instance"
... which results in 4 lines on the graph corresponding to the 4 channels. The display is stacked and each channel has its own color on the legend but as one channel is all zeros, it is not visible (at all) on the graph. It is the 4th series which is not visible and on the graph, it is the organge colour that overwrites the blue of the 3rd. This is all as expected.

The goal is to make the 3rd series visible and the 4th series invisible by using "Hide series" and then selecting "With all zeros".

- What was the expected result?

The expected result was to see all of the serieses on the graph with non-zero data with a matching legend.

- What happened instead?

The series with only zeros for data was removed from the graph and legend BUT the legend and the graph do not match. The top line of the graph is still orange (and not blue) which is incorrect. The legend however is correct and has green, yellow and blue. The hover display is correct - it lists the three values for green, yellow and blue.

The graph is not correct.

**Comment by torkelo** [comment]
you will have to assign color manually, hidden series are still there so take a color slot, but you can override colors. 

Soon you will abe able to use a transform to remove series will all nulls
