### ISSUE TITLE
Why Worldmap panel cannot be added to dashboard like other panels after installation?

### ISSUE THREAD

**Issue by alirezastack** [grafana/grafana#8133]
- What Grafana version are you using? **V4.1.1**
- What datasource are you using? **InfluxDB**
- What OS are you running grafana on? **MAC OS X**
- What browser version are you using? **Chrome 57.0**

I installed world map panel plugin by using the command below:
`grafana-cli plugins install grafana-worldmap-panel`

I could find the plugin inside of **/usr/local/var/lib/grafana/plugins** and I can see that it is installed on my grafana:

![screen shot 2017-04-15 at 5 39 38 pm](https://cloud.githubusercontent.com/assets/6417083/25063777/8aee6244-2202-11e7-8a76-9e8440e96be4.png)

But the problem is when I open a dashboard and trying to add a new panel the world map plugin is not included in the list. When I open the plugin in the plugin it just shows a readme file.

![screen shot 2017-04-15 at 5 40 22 pm](https://cloud.githubusercontent.com/assets/6417083/25063808/131da436-2203-11e7-90d4-7a7eff98b1c2.png)

Is this a bug? Why map is not in the panel list? Did I miss something?

**Comment by alirezastack** [comment]
I restarted grafana server but didn't do anything. I signed out from my panel and then logged back in. It now works!

**Comment by henry-driver** [comment]
enchanted a similar issue, @alirezastack did you resolved this issue?

**Comment by marefr** [comment]
@henry-driver please refresh page in browser

**Comment by alirezastack** [comment]
@henry-driver I just signed out and logged back in again. That solved the issue for me. Maybe doing a hard refresh would help to solve this problem too.
