### ISSUE TITLE
don't request for login 

### ISSUE THREAD

**Issue by hamedtorky** [grafana/grafana#8135]
Hi, I want to show all dashboards for everyone before I want to disable login page, it is passable? 

thank you so much :) 

Please include this information:
- What Grafana version are you using? 4.2.0
- What data source are you using? influx DB
- What OS are you running grafana on? Linux
- What did you do? monitoring
- What was the expected result?
- What happened instead? I want to everyone see dashboards 
- If related to metric query/data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Yes, you can enable anonymous access :)

http://docs.grafana.org/installation/configuration/#enabled
