### ISSUE TITLE
Escaping regex characters in templating 

### ISSUE THREAD

**Issue by cemo** [grafana/grafana#8136]
I am using grafana 4.2.0 with prometheus 1.5.1 version. 

I have some servers with labels:

- a-xxx-app
- a-yyy-app
- b-zzz-app

I would like to select these servers in a multiple way by template variables: `a-.*` and `b-.*`. These templated variables are already regex and grafana converts them a regex compatible string which are already regex compatible. When the Include All option or Multi-Value option is disabled, everything is working fine but when I enable them it is escaped again. 

Grafana documentation states:

```
When the Include All option or Multi-Value option is enabled, Grafana converts the labels from plain text to a regex compatible string. Which means you have to use =~ instead of = in your Prometheus queries. For example ALERTS{instance=~$instance} instead of ALERTS{instance=$instance}.
```

How can I stop escaping it? Or Is there any other workaround?

**Comment by torkelo** [comment]
If you select Multi or Include All, grafana will generate the final regex, so needs to escape in order to create a valid regex value. 

There is no way to disable this currently (other than disabling Multi or All value).

There already is a feature request for an option to disable escaping:
https://github.com/grafana/grafana/issues/7955

**Comment by cemo** [comment]
For those who will hit this issue: It is better to add a label to your servers and using it to select for grouping. :) I could not do at my case because the labels are already set and could not find a way to add. This disabling regex was only related to mitigate issue but our pain actually was in somewhere else.
