### ISSUE TITLE
UX improvement of panels

### ISSUE THREAD

**Issue by cemo** [grafana/grafana#8137]
From a newbie perspective it is not clear what to do after adding a panel. There is no indication of what should be done after it. İt is not clear how should I edit it.

**Comment by torkelo** [comment]
Yes, we are aware that this is a big problem, been a problem for a while. Its mainly been in conflict with keeping the dashboard clean, so there is no distractions from the data. But we have in 4.0 added view mode that dashboard switches to automatically after some inactivity so we can add some affordances. 

We have already started working on this:
https://github.com/grafana/grafana/tree/panel-title-menu-ux

here is a video, (work in progress, experiment)
https://s3-us-west-2.amazonaws.com/docs.grafana.com/assets/videos/panel_menu_v3_work_in_progress.mp4

**Comment by cemo** [comment]
Honestly a title does not indicate for me editing a panel. I expect editing a title only changing it. If it will be continued to be stay as in this video, it would be better to open it initially to indicate there is a menu and it is related to whole panel. 

PS: Thank your so much for your awesome work so far you have done with your team. Words are really not enough to say how you are good and solving what a big problem.

**Comment by cemo** [comment]
@torkelo I will provide some more information on this issue. Please make me correct in case a problem.

The current way of leaving of editing panels are also not clear. A button at the top and bottom of the page might be best because of repeating panels can not fit window.

**Comment by torkelo** [comment]
> The current way of leaving of editing panels are also not clear. A button at the top and bottom of the page might be best because of repeating panels can not fit window.

Not sure I understand this sentence. You can leave edit mode with a big link "Back to dashboard" in the menu, as well as a close icon to the right the edit tabs. 

Not sure how this relates to repeating panels.

**Comment by cemo** [comment]
I have not noticed `Back to dashboard` honestly. I intuitively searched a exit or save button at the end page like other pages such as `adding data source`: 

![image](https://cloud.githubusercontent.com/assets/44156/25091754/65ca1bc4-2393-11e7-94ea-30129813f4fb.png)

This can easily be distinguished and more intuitive. It can be arguable but this seems easier for me.
