### ISSUE TITLE
repeating rows: Variables occasionally pass list rather than individual value

### ISSUE THREAD

**Issue by afcjason** [grafana/grafana#81381]
### What happened?

Using variable with multiple value option ticked.
When expanding a consolidated row that is set to repeat with a variable, the variable used in the panels under the row does not use the value of the variable, but rather gets the list of variables. Any queries using the variable value errors out in this situation.
Dashboard must be freshly opened with variable default having 2 or more values selected.
correct values are shown/used when changing variable value.

screen recording:
https://github.com/grafana/grafana/assets/157816405/427d4b1d-e42f-44b3-b66f-7e8890969db3

### What did you expect to happen?

variable values to be consistent and values to be used when variable is reference rather than the list

### Did this work before?

no. 
currently using v10.0.2
recreated bug on v10.4.0-65039

### How do we reproduce it?

1. refresh dashboard with previous save having all the repeated rows consolidated
2. expand the second row
3. expand first row

### Is the bug inside a dashboard panel?

[Template Variable Formatting Options-1706280513805.json](https://github.com/grafana/grafana/files/14066458/Template.Variable.Formatting.Options-1706280513805.json)

### Environment (with versions)?

Grafana: v10.0.2
OS: Linux
Browser: Brave (on Windows)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hello @afcjason 

Could you confirm if this issue occurs consistently with all browsers, or have you noticed it specifically with Brave? 

I can't reproduce it in Firefox 122.0.1 (64-bit)

**Comment by afcjason** [comment]
Hi @tonypowa ,

I can confirm I can recreate the bug on Microsoft edge and on google chrome using the grafana version above v10.0.2.
I believe it is an issue with how the list is obtained on the grafana side rather than the browser being used as I could recreate the issue on the example dashboards provided on your website with minor changes.
https://play.grafana.org/d/cJtIfcWiz/template-variable-formatting-options?orgId=1&var-servers=test2&var-servers=test3&var-servers=test.1
steps taken:
- save dashboard
- add row
- under the row option, choose repeat for 'servers'
- save dashboard
(VERY IMPORTANT)
- refresh page
- expand the any column other than the first one
- then expand the first column, entire list selected rather than first variable

hope this helps,
Jason

**Comment by tonypowa** [comment]
thank you for the info

i am afraid I still could not reproduce it. can you note down the version of the browsers that your are using?

**Comment by afcjason** [comment]
Hi Tony, apologies for the delayed reply.
Seems as if the bug can no longer be recreated in the later version of Grafana. I can still recreate the issue with the active version I am using (v10.0.2) but not on the latest active version v11.0.0. The issue may have been accidently fixed in the time between the first post and now. I will just have to update to the latest version for the fix. Thanks for your assistance!
