### ISSUE TITLE
Prometheus: Using result of query in the legend

### ISSUE THREAD

**Issue by cemo** [grafana/grafana#8138]
I would like to use labels of query result in prometheus datasource in legend. This is an instant vector of my query:

```
element                                               value
{image="sm/td-cron-app:38b0c4b",namespace="prod"}	1
{image="sm/td-cron-app:38b0c4b",namespace="stage"}	1
{image="sm/td-rest-app:38b0c4b",namespace="prod"}	3
{image="sm/td-bo-app:38b0c4b",namespace="prod"}	        1
{image="sm/td-web-app:38b0c4b",namespace="stage"}	1
{image="sm/co-rest-app:e3c623d",namespace="stage"}	1
```

What I want to use is like this: 

```
label_values($result, image) in label_values($result, namespace)
```
and expecting such results in legend:

```
sanalmarket/tazedirekt-cron-app:38b0c4b in prod
```

Is there a way to access result in legend and use other functions?

**Comment by torkelo** [comment]
In the Legend format input field in the query editor you can use expressions like `{{image}} in {{namespace}}`

**Comment by cemo** [comment]
@torkelo thanks. It worked. One more question. Is this information available in documentation or should I open another issue for improving it?
