### ISSUE TITLE
Sparkline does not show on the single stat panel

### ISSUE THREAD

**Issue by alirezastack** [grafana/grafana#8139]
I have read documentation to add sparkline, and I read the below similar issue:
[https://github.com/grafana/grafana/issues/3996](https://github.com/grafana/grafana/issues/3996)

In influxDB I have 2 fields time and value. In single stat panel I have enabled the sparkline. It just displays `N/A`.

![screen shot 2017-04-16 at 5 08 48 pm](https://cloud.githubusercontent.com/assets/6417083/25071395/063047a6-22cb-11e7-95b1-176eba89ea41.png)
![screen shot 2017-04-16 at 5 10 57 pm](https://cloud.githubusercontent.com/assets/6417083/25071396/063baa60-22cb-11e7-91b2-a2e579f80741.png)

I have used the below query:
`SELECT mean("value") FROM "total_users" WHERE $timeFilter GROUP BY time(1h) fill(null)`

![screen shot 2017-04-16 at 5 13 16 pm](https://cloud.githubusercontent.com/assets/6417083/25071397/0645d544-22cb-11e7-8afd-69f8c457929a.png)

Any reason why it is not displaying the sparkline?

**Comment by torkelo** [comment]
Please checkout the troubleshooting query guide on the community site 
https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
