### ISSUE TITLE
Why Grafanat Alerting message doesn't has Metric's Tags

### ISSUE THREAD

**Issue by whc9527** [grafana/grafana#8141]
Please prefix your title with [Bug] or [Feature request]
For question please check Support Options. Do not open a github issue

Please include this information:

What Grafana version are you using?
grafana-4.1.2-1486989747
What datasource are you using?
influxdb-0.9.6.1-1
What OS are you running grafana on?
CentOS release 6.6
What did you do?

Here is my metrics configuration.
![image](https://cloud.githubusercontent.com/assets/17898805/25086692/fd464362-239b-11e7-8865-79151ec75bcd.png)

Here is my alerting configuration.
![image](https://cloud.githubusercontent.com/assets/17898805/25086734/745c8254-239c-11e7-941e-edfd95a0e71e.png)

Here's what I print out the grafana message from my interface
![image](https://cloud.githubusercontent.com/assets/17898805/25086754/a542833c-239c-11e7-89ab-4d0ff6a558b7.png)

So. I can't understand why my metric has tag information, but why didn't grafana send it?  
Coud somebody can help me, Thx！

**Comment by torkelo** [comment]
Looks like your using OpenTSDB and not InfluxDB, there is an open bug/feature to add support for series alias patterns in alertinghttps://github.com/grafana/grafana/issues/7309

**Comment by whc9527** [comment]
@torkelo thanks  for you help. 谢谢了！
