### ISSUE TITLE
Using the alias in the world map

### ISSUE THREAD

**Issue by sLuvpreet33** [grafana/grafana#8142]
Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
4.2
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
used alias to display multiple metrics in the pop over
- What was the expected result?
It should display multiple values
- What happened instead?
It displayed null
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
  Here is the query,

`http://127.0.0.1:8999/api/datasources/proxy/2/query?db=vehicleinfo&q=SELECT "speed" AS "metric", "latitude", "longitude", "vehicleno", "geohash" FROM "vehicleinfo" WHERE "vehicleno" = 'KA-03-AD-6910' AND time > 1492367400000ms and time < 1492453799999ms&epoch=ms`

I made use of templating and declared a variable for all the tags.

then I run this query,

![screenshot from 2017-04-17 19-18-06](https://cloud.githubusercontent.com/assets/23127804/25090728/a2065f62-23a2-11e7-9254-b1637c24997e.png)

You can see in the pop-over that it is showing `null` after the `vehicleno`.

before this query, I was using a single field as a metric, and it displayed that perfectly. But now, I wanted to see multiple fields, therefore, I made this query.

What is the problem ? Why it is not showing ?

**Comment by torkelo** [comment]
I do not think the worldmap panel supports this type of query, please open issues in the worldmap panel repository
