### ISSUE TITLE
Prometheus classic histogram heatmap de-accumulation produces values < 0

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#81437]
you can see the baseline here is -5, not 0. this is because of imperfect float precision, and we end up with near-zero values that should actually be zero.

we should modify the de-accumulation function [1] to treat any values < 1e-9 as zero. we already hide such values by default in Heatmap panel, since they add a bunch of noise and are almost universally float precision errors.

![image](https://github.com/grafana/grafana/assets/43234/3cb2c117-ee1a-493f-a40f-08672480b817)

![image](https://github.com/grafana/grafana/assets/43234/1ba03273-9fd7-436d-8fed-7e9edd2e4c45)

[1] https://github.com/grafana/grafana/blob/1a1531ca5e92554d107bb1eb9df2f9fdc604d824/public/app/plugins/datasource/prometheus/result_transformer.ts#L362-L384

**Comment by bohandley** [comment]
Hi @leeoniya! Both of these code examples are the same. Do you have a second example of how you suggest implementing this?

**Comment by leeoniya** [comment]
sorry, just linked it twice
