### ISSUE TITLE
Window.fetch: HEAD or GET Request cannot have a body

### ISSUE THREAD

**Issue by chengzi-xs** [grafana/grafana#81456]
### What happened?

Alertmanager version: 0.26.0

Prometheus version: 2.27.0

Grafana version: 7.5.17

Setting grafana alertmanager dashboard show next info
Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
![image](https://github.com/grafana/grafana/assets/59002007/2517ca35-87b5-4fb2-b325-21542aa9d406)

### What did you expect to happen?

use alertmanager normal 

### Did this work before?

normal on grafana version 5.4.2

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

### Datasource(s)?

alertmanager

**Comment by chengzi-xs** [comment]
Use google browser debug module, we can see console ouput 
![image](https://github.com/grafana/grafana/assets/59002007/05674e20-c7f5-4117-9446-cb5f85ba77f0)

**Comment by tonypowa** [comment]
Hello @chengzi-xs 

We wanted to bring to your attention that the version you're currently using is not supported. If you encounter any issues or have feature requests, we encourage you to submit them as a new issue on a supported version.

Thank you for your understanding
