### ISSUE TITLE
[Bug] Log2-10 vertical axes value layout exceeds graph panel

### ISSUE THREAD

**Issue by dmitrios** [grafana/grafana#8146]
Please include this information:
- What Grafana version are you using?
[Latest, build from source]
- What datasource are you using?
InfluxDb
- What OS are you running grafana on?
OSX
- What did you do?
Created simple InfluxDb query with log2 vertical axe.
- What was the expected result?
vertical axe starts with 0 within graph panel
- What happened instead?
vertical axe starts with 1 with 0.1 measurement far below graph panel
- If related to metric query / data viz:
 None.

**Comment by daniellee** [comment]
@dmitrios can you add a screenshot of this please.

**Comment by dmitrios** [comment]
![logaxe](https://cloud.githubusercontent.com/assets/20961950/25109463/8ec82e32-2391-11e7-9e3f-574f1c8f724d.png)
Please see attached. I did report same behavior in Safari on OS X and Chrome.

**Comment by dmitrios** [comment]
Please see 2nd screenshot attached. 
![logaxe2](https://cloud.githubusercontent.com/assets/20961950/25109501/df020274-2391-11e7-9409-95929ce8918e.png)

**Comment by torkelo** [comment]
Please attach your graph panel options (json) and the raw data response from your query

**Comment by dmitrios** [comment]
Please see attached. I can reproduce by simply changing type of vertical axes.
[panel.json.txt](https://github.com/grafana/grafana/files/930420/panel.json.txt)
[Response.json.txt](https://github.com/grafana/grafana/files/930421/Response.json.txt)
<img width="1280" alt="linear" src="https://cloud.githubusercontent.com/assets/20961950/25141960/23ea2384-241a-11e7-9580-4c61fdd41601.png">
<img width="1280" alt="logbase2" src="https://cloud.githubusercontent.com/assets/20961950/25141963/2668172e-241a-11e7-81f8-1422f8769fd5.png">

**Comment by torkelo** [comment]
should be fixed in latest & v4.4.3
