### ISSUE TITLE
Filter-by-values: Exclude-null doesn't get initialised properly

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#81465]
The "Exclude by values" filter doesn't initialise properly when "Exclude null values" is chosen.

I've reproduced the issue on this dashboard:
https://play.grafana.org/d/issue-81465/50742fe3-c7c7-5c29-8c43-9de6e1d118e3?orgId=1

This panel is the problem panel:
https://play.grafana.org/d/issue-81465/50742fe3-c7c7-5c29-8c43-9de6e1d118e3?orgId=1&editPanel=61

You can see the panel JSON shows:
```
  "transformations": [
    {
      "id": "filterByValue",
      "options": {
        "filters": [
          {
            "fieldName": "city",
            "config": {
              "id": "greater",
              "options": {
                "value": 0
              }
            }
          }
        ],
        "type": "exclude",
        "match": "any"
      }
    }
  ]
```

Also see this video:

https://github.com/grafana/grafana/assets/2903904/144e37ba-00dc-4688-88c7-aba20fee02ee

**Comment by samjewell** [comment]
This increases the impact of #81475, because both make it almost impossible to remove null values. There's no obvious workaround.

**Comment by baldm0mma** [comment]
I was able to reproduce this. Moving this to `ToDo`.

**Comment by Eduardo-Pedrosa** [comment]
Can you assign me to this issue? I've started to work on this bug already.
