### ISSUE TITLE
Native Panel Options in Custom React Panels

### ISSUE THREAD

**Issue by IhsenBen** [grafana/grafana#81462]
**Why is this needed**:

I am working on a custom plugin panel with React and my team needs to use Threshold in our custom panels.
Is there a way to reuse the threshold option in custom plugins without recoding the whole thing with PanelOptionsEditor etc? 
It doesn't seem to be mentioned anywhere in the documentation.

**What would you like to be added**:

Ideally, access panel options as reusable elements.

**Who is this feature for?**

This feature would allow users to reuse existing options in the visualisation panel into custom plugin panels.

**Comment by jackw** [comment]
@IhsenBen thanks for opening this issue. Could I please get a little more information on what it is you're looking to do?
 
> Is there a way to reuse the threshold option in custom plugins without recoding the whole thing with PanelOptionsEditor etc?

Are you asking to be able to reuse the react components that are used to build the threshold config in the panel editor? Or are you looking to use threshold values within your panel plugin?

**Comment by IhsenBen** [comment]
Hi @jackw,
I was asking to be able to reuse the react components that are used to build the threshold config in the panel editor.
I just copied the threshold component from the source code, but this could be a useful feature to develop custom plugins.

**Comment by jackw** [comment]
@IhsenBen sorry for the follow up question but how / where are you using the thresholds component? In the panel itself? Can you better explain the use case please? 

Currently you can enable the thresholds editor in the panel editor by using the `.useFieldConfig()` method in `PanelPlugin` to add the threshold editor to your panel plugin. This can be further customised to remove other fields with `disableStandardOptions`, change speecific settings/options with `standardOptions` or introduce custom config with `useCustomConfig`. [Piechart example here](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/piechart/module.tsx#L13-L30).

Hopefully this helps you to use the thresholds in your panel. I'll make sure to add an issue to document this in the future.

**Comment by tolzhabayev** [comment]
@IhsenBen could you please take a look at questions above?

**Comment by mckn** [comment]
Closing this one due to inactivity, please ping us if we should re-open the issue.
