### ISSUE TITLE
Configuration: inline `#` in `grafana.ini` is treated as comment 

### ISSUE THREAD

**Issue by oliviermichaelis** [grafana/grafana#81473]
### What happened?

I would like to be able to use the `#` character in `grafana.ini` configuration values.
Grafana currently treats `#` as a comment and breaks the configuration value.

I think this is down to how the `ini` package parses the configuration file (https://github.com/go-ini/ini). It is apparently possible to escape the `#` with `Cfg, err := ini.LoadSources(ini.LoadOptions{SpaceBeforeInlineComment: true}, source)` as shown in  https://github.com/go-ini/ini/issues/277.

Is there a possible workaround?

### What did you expect to happen?

Inline comments with `#` are not parsed as a comment. This would allow me to use `#` in my configuration.

### Did this work before?

I don't think so.

### How do we reproduce it?

I had this problem with the following `grafana.ini`:
```ini
[auth.okta]
...
role_attribute_path = contains(groups[*], 'example#admin') && 'Admin'
```
and this user information:
```json
{
  "sub": "test",
  "name": "Alice",
  "locale": "en_US",
  "email": "test@example.com",
  ...
  "groups": [
    "example#admin",
    "test-group"
  ]
}

```
With the above `role_attribute_path`,  no role was found for the user. I validated the JMESpath expression with multiple tools and it seems to be correct.

The following `role_attribute_path`  worked as expected:
```ini
[auth.okta]
...
role_attribute_path = contains(groups[*], 'test-group') && 'Admin'
```

### Environment (with versions)?

Grafana: `10.2.3`
OS: `linux`

### Grafana platform?

Kubernetes

**Comment by oliviermichaelis** [comment]
Took me way too long to figure this out, but I was successfully able to override the `role_attribute_path` with the `GF_AUTH_OKTA_ROLE_ATTRIBUTE_PATH` environment variable :)

**Comment by tonypowa** [comment]
hi @oliviermichaelis 

thank for sharing your solution to this issue

I'm closing the issue but if you still have comments/concerns or need help please feel free to let us know!
