### ISSUE TITLE
Grafana issue with new version of influxdb 

### ISSUE THREAD

**Issue by adeel26** [grafana/grafana#8147]
I had grafana - v1.9.0-rc1 - 2014-11-17 embedded within my app querying and displaying data from influxdb verion 0.8.0. 
with app.fea68443.js file. 
my config file setting as follows

// == Configuration
define(['settings'], function(Settings) {

  return new Settings({

      

      datasources: {
        influxdb: {
          type: 'influxdb',
          url: "http://localhost:8086",
          username: 'test',
          password: 'test',
        },
        

      /* Global configuration options
      * ========================================================
      */

      // specify the limit for dashboard search results
      search: {
        max_results: 100
      },

      // default home dashboard
      default_route: '/dashboard/file/default.json',

      // set to false to disable unsaved changes warning
      unsaved_changes_warning: true,

      // set the default timespan for the playlist feature
      // Example: "1m", "1h"
      playlist_timespan: "1m",

      
      admin: {
        password: 'admin'
      },

      // Change window title prefix from 'Grafana - <dashboard title>'
      window_title_prefix: 'Grafana',

      // Add your own custom panels
      plugins: {
        // list of plugin panels
        panels: [],
        // requirejs modules in plugins folder that should be loaded
        // for example custom datasources
        dependencies: [],
      }

    });
});

Now i upgraded my influx version to influx 0.9 and I understand api is different and hence i used latest boot.6d63bd8b.js file. But for some reason its always giving me error like Error: (SystemJS) undefined is not an object (evaluating 'c.bootData=b')

**Comment by daniellee** [comment]
Are you still running version 1.9.0 of Grafana? Or did you upgrade to 4.2.0?

**Comment by adeel26** [comment]
I have upgraded to the verson 4.2.0 of grafana, basically versioning of grafana shouldn't matter here. I am embedded the grafana app inside my project, as in putting entire directory inside my application folder.

**Comment by daniellee** [comment]
So it is not in an iframe? This is an unusual use case for Grafana. I think you will have to debug and investigate some more yourself. This does not look like a bug in Grafana to me.
