### ISSUE TITLE
Saga website: Add props to each component

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#81487]
We need to figure out a way to add the props of each component to the Saga website, but we want to do this automatically, without having to remember to update it every time a prop is added/removed/changed.

Suggestions to look into from Josh:
https://github.com/atomicpages/docusaurus-plugin-react-docgen-typescript
https://github.com/styleguidist/react-docgen-typescript
https://github.com/seek-oss/braid-design-system/blob/master/packages/generate-component-docs/src/generate.ts

**Comment by staton-hyse11** [comment]
transferred to Grafana repo to keep work in the same location
