### ISSUE TITLE
Stop removing `+00:00` from `UTC +00:00` in the UTC relative-time badge of the time-range picker

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#81506]
**Stop removing `+00:00` from `UTC +00:00` in the UTC relative-time badge of the time-range picker**

It's not always clear to users, particularly in the UK and Ireland, whether a Grafana Dashboard is being rendered in UTC or in their local time (eg. GMT).

![image](https://github.com/grafana/grafana/assets/2903904/d233ae72-999a-4f26-91ef-d5b9d7d200eb)

For users in other time-zones this is much clearer, because we preserve the relative time-difference in the UI. eg: `UTC +03:00` in the image below:

![image](https://github.com/grafana/grafana/assets/2903904/b6469bae-65e4-4cdb-84b3-3aca66516922)

SO - for this ticket, please bring back the `+00:00` even for people who have zero offset with UTC. This will reduce confusion, and increase consistency.

**Comment by JoaoSilvaGrafana** [comment]
Thanks for raising the issue @samjewell ! After reviewing this a bit more, I now understand that the little grey square in the right is meant to be the offset that that timezone has with UTC _right now_, so it doesn't really have the abbreviation of the timezone and it is correct to say "UTC". You can see that if I change my system's date to be before the time change, it changes that timezone offset to say "UTC+01:00":

<img width="698" alt="Screenshot 2023-09-29 at 16 16 06" src="https://github.com/grafana/grafana/assets/100691367/9d4de769-7417-4319-b947-e2d85396901c">

Given this example what each of these mean are:
**Timezone title**: "Europe/London" (this is the "official" timezone [name](https://momentjs.com/timezone/docs/#/zone-object/name/) according to IANA guidelines)
**Timezone country**: "United Kingdom" (information that comes from moment timezone [`.countries`](https://momentjs.com/timezone/docs/#/using-timezones/getting-country-zones/) function)
**Timezone abbreviation**: "BST" (information that comes from moment timezone [`.abbr`](https://momentjs.com/timezone/docs/#/zone-object/abbr/) function depending on the current timestamp of that tz)
**Timezone offset to UTC**: "UTC+01:00"

What you actually select is on that dropdown is "Europe/London" (or in your example "Browser Time", which deep down is the same for you), the rest is just extra information; to always follow "GMT" you should select "Coordinated Universal Time".

After investigating I no longer think this is a bug, just timezones being confusing 🙁

**Comment by samjewell** [comment]
hm, ok. Thanks @JoaoSilvaGrafana for the investigation and explanation.

I'm not leaping to close this right away, as you and I both thought it was a bug from the UI. Maybe this is a UI/UX papercut (even if it's not a bug) and could do with some improvement? @natydej Just thought I'd try you - any ideas?

I'm wondering whether something like `UTC +00:00` might make it a little clearer what the purpose of this is in the UI 🤔

**Comment by JoaoSilvaGrafana** [comment]
Yeah there is a piece of code that removes the `+00:00` [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/DateTimePickers/TimeZonePicker/TimeZoneOffset.tsx#L36). If we think that would make it more clear we can remove that block, but then yeah it becomes a UX decision probably.

**Comment by natydej** [comment]
Hey @samjewell tbh I don't have the answer for this currently, I would recommend you bring this topic in the next UX feedback session to get a broader discussion :) happy to see you there!

**Comment by samjewell** [comment]
> Yeah there is a piece of code that removes the +00:00 [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/DateTimePickers/TimeZonePicker/TimeZoneOffset.tsx#L36). If we think that would make it more clear we can remove that block, but then yeah it becomes a UX decision probably.

I brought this to the UX feedback session today, and we agreed that bringing back the `+00:00` is a good resolution. It reduces confusion and increases consistency.

Is that what you need @JoaoSilvaGrafana ?

**Comment by JoaoSilvaGrafana** [comment]
@samjewell Yes perfect! Thanks for bring it up to UX feedback session! We also just had a discussion within the team and agree that that is a good solution, so we will move this to our board and specify that the task is to add the `+00:00` into that box.

Do you mind editing your post at the top + the title to make it clear what the task is? 🙏
