### ISSUE TITLE
[Feature request] histogram support unit for x-axis

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8150]
If the time series value is big, hard to interpret the distribution.

![histogram2](https://cloud.githubusercontent.com/assets/224552/25113615/9e1af5f2-2433-11e7-8c8f-895e7a0e5916.png)
In this graph, x-axis is bytes, but should draw as kbytes.

**Comment by darasion** [comment]
+1
This is useful to me.

**Comment by erichuang1994** [comment]
Any updates?

**Comment by chenzhuoyu** [comment]
+1
This is super useful to me.

**Comment by MaDOS** [comment]
+1
Would be very useful for me too. Any Updates?

**Comment by anthonyeleven** [comment]
+1
I'm currently working up a histogram panel where the values will only be integers, yet intervals are chosen like 191.0 191.2 191.4 etc.  Decreasing the number of buckets doesn't help.

**Comment by brentwritescode** [comment]
+1
I have a use case where the X-axis is time-based (e.g. how long did this thing take to finish) and trying to interpret "50 million milliseconds" as an actual human readable time is tough.

**Comment by zsiciarz** [comment]
+1, same use case as previous comment. For the time being I'm dividing the seconds value by 3600 and added unit information to chart title.

**Comment by Shapedsundew9** [comment]
+1 same issue
