### ISSUE TITLE
InfluxDB: Wrong query generated when using templateVariable with equal operator on influxql visual query builder

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#81517]
When you are using a single value regex variable with a non regex operator (e.g. =), and you convert the query from builder to code-editor, it leaves the regex wrapper around the variable in the expression, and wraps that in a single quote, which leads to a broken query expression:

![Image](https://github.com/grafana/grafana/assets/820946/1c79d4ca-cbbd-4b14-a4c0-79500130843f)

![Image](https://github.com/grafana/grafana/assets/820946/badce6b5-5c3d-4db5-96dd-3fea4ba428d1)

**Comment by wasim-nihal** [comment]
@itsmylife , I would like to contribute here. Can you please assign it to me?

**Comment by itsmylife** [comment]
Hi @wasim-nihal , thanks for taking a look at this!

We tend not to assign issues to external contributors just in case they decide that they don't have time anymore to take it on. Once you have raised a PR if you link to this issue in the description it will be clear to others you've put in the work for it 😄

Hope that makes sense.
