### ISSUE TITLE
[Feature request] histogram support multiple legend and stack

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8151]
To see several type of time series in one graph, need to support this.

The graph looks like following.
![histogram3](https://cloud.githubusercontent.com/assets/224552/25113688/2bfa2e2e-2434-11e7-9a3f-da4558ee7a8b.png)

I found some of graph tools support it.
https://www.ibm.com/support/knowledgecenter/en/SSLVMB_20.0.0/com.ibm.spss.statistics.help/gpl_examples_barcharts_histogram_stack.htm

**Comment by wmaiouiru** [comment]
@mtanda I would like to utilize this feature in my graph. Are there any documentation to make this happen? I am using one postgres instance with the following template query:

SELECT
    value,   -- the value that I want histogram of where y-axis is the occurrence and x-axis is the bins
    metric,  -- the series
    time
FROM
    db
