### ISSUE TITLE
[Feat Req] Support boolean type format in Table Panel

### ISSUE THREAD

**Issue by sunnos9** [grafana/grafana#8152]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 4.2
- What datasource are you using? InfluxDB (1.1)
- What OS are you running grafana on? (CentOS 7)
- What did you do? Created a new Table panel, influxDB data source, Table has boolean column (e.g. isValid), unable to apply column style to color entire cell/ row - did not work. 
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by daniellee** [comment]
This is not currently supported. The only types supported are number, date and string. Labeling this as a feature request.

**Comment by agwaltz** [comment]
+1  

Adding "Value Mapping" and "Series Override" to the Table Graph > Column Styles would enhance the Table panel immensely.

**Comment by danger89** [comment]
Yes, please,I still can **NOT** use Boolean type from Influx in Grafana. Also not with the built-in Singlestat plugin.

How is it ever possible? S.M.A.R.T. (Self-Monitoring, Analysis, and Reporting Technology) reports health status of your disks as a boolean type (true -> OK. false -> NOK). Its not possible to show this!

**Comment by Apollon77** [comment]
I had success with 0/1 mappings in the Singestat panel

**Comment by CaffeinatedAndroid** [comment]
I would add that you don't always need to support Boolean types from InfluxDB (perhaps a separate feature request), but also support value mapping in the front-end (Table panel). So when choosing a data type for a column:
`1` is shown as `True`
`0` is shown as `False`

An additional value mapping whilst we're at it:
`Yes`/`No`
`On`/`Off`
Or allow user defined values.

Some sensors report bools as `1`/`0`, so supporting this would require less transofmration configuraiton lower down a stack.

**Comment by adamkdean** [comment]
This is still a requirement, years later

**Comment by danger89** [comment]
I agree.. its still missing, I though it was easy to implement by some Grafana developers with the right known-how.

**Comment by DobroAlex** [comment]
Voting + for this. It would be nice to able to set custom label and color for True and False

**Comment by TyVik** [comment]
It's affecting me too :'(

**Comment by hixfield** [comment]
Why is this taking so long to implement? Encoding values as boolean (true/false) is a native json and database type. We really should get this implemented.

**Comment by danger89** [comment]
> Why is this taking so long to implement? Encoding values as boolean (true/false) is a native json and database type. We really should get this implemented.

False, I mean True!

**Comment by hixfield** [comment]
I kindof found a solutionby using distinct() but it only works for one trace in a graph...

**Comment by gabor** [comment]
this works in grafana now (tested with 8.0.0-beta3):
- the boolean data from the influxdb data source will arrive in grafana
- if you add for example a "Stat" visualization, you can use the "Value mappings" option to set custom text and color for `true` and for `false`
