### ISSUE TITLE
Azure Monitor: Cannot backfill empty metrics timeseries

### ISSUE THREAD

**Issue by joebeernink** [grafana/grafana#81523]
### What happened?

I am trying to build a visualization for API availability. 
The math expression is simple:  100 * (TotalRequests-$FailedRequests)/$TotalRequests

where TotalRequests is a metrics query on Azure.ApplicationInsights http.server.request.duration (count)
and FailedRequests is a metrics query on Azure.ApplicationInsights http.server.request.duration (count) where the status code starts with 5

The problem is that when there are no failed requests in the time frame for the visualization, instead of showing 100% availability, the count of the TotalRequests shows instead because the result of the Failed request query is an empty array of unknown type. 

I tried to add a resample expression to the Failed requests, but since there is nothing to sample, there is nothing to re-sample.

### What did you expect to happen?

There has to be a way to generate the correct visualization for this type of availability graph...

### Did this work before?

Unknown.

### How do we reproduce it?

1. Create a dashboard
2. Add a time series visulaization
3. Add two time series queries, where the second one returns no data
4. Try to apply an expression which merges the two results to calculate a value

### Environment (with versions)?

Grafana: Azure Managed Grafana
OS: 
Browser: Edge

### Grafana platform?

Other

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
Hi @joebeernink, I am unable to replicate this. If I query an App Insights resource (`Microsoft.Insights/Components` namespace) with two separate queries for the `TotalRequests` and `FailedRequests` I do not retrieve an empty response. I do retrieve an empty response if I query the underlying logs data directly.

Could you provide a sample of your query so that I can attempt to replicate this? Thanks!

**Comment by bossinc** [comment]
Closing for now. Please reopen if this is still an issue. 🙂
