### ISSUE TITLE
[Bug] Description popup text cannot be seen

### ISSUE THREAD

**Issue by Frenjon** [grafana/grafana#8153]
Grafana: 4.2.0
Datasource: Prometheus
Browser OS: Mac Os 10.12.3
Chrome browser v56

When hovering the small "i" on a graph to show that graphs description the text box shown is always centered over the "i".

When the graph is on the left hand side of the dashboard and the browser window is on the edge of monitor the popup cannot be seen in its entirety. 

It's evident here: http://play.grafana.org/dashboard/db/grafana-play-home?panelId=5&fullscreen&orgId=1
If you try and hover the "i" you can only read half of it.

Expected behaviour: Being able to read the entire description :)

**Comment by torkelo** [comment]
this was fixed 6 days ago :)
https://github.com/grafana/grafana/commit/dd3e594dd76f8a2736c1f2b74c398a3bab968609#diff-1352eb8acf59f116006679184d5f51d3
