### ISSUE TITLE
[Bug] Minio as external image storage

### ISSUE THREAD

**Issue by lukasmalkmus** [grafana/grafana#8156]
I suggests labeling this as `state: needs more details` and `comp: imagestore`.

I tried to use [minio](https://github.com/minio/minio) as an external image storage and expected it to work just fine, since it's S3 API compatible.
But the upload fails with the following message (extracted from log): `Could not find bucket setting for image.uploader.s3`.
I think this could be a possible duplicate of #8045. The bucket is reachable at `https://minio.example.com/minio/grafana` and not the typical AWS-like URI (`https://bucketname.s3.amazonaws.com/grafana`).

**Comment by torkelo** [comment]
we are using the aws sdk to upload, it requires region and s3 credentials. So not sure it supports alternative http enpdoints

**Comment by lukasmalkmus** [comment]
How are the chances that a PR, introducing Minio as external storage, will be accepted?

**Comment by torkelo** [comment]
Sadly low, if there are not a feature request with a lot of user interest in

**Comment by nimeops** [comment]
well... i hope it will be implemented !

**Comment by GPConnect** [comment]
triednto use minio in grafana but didn't worked ! please add custom url in bucket setting THANKS !!!

**Comment by jenciso** [comment]
I would like to use minio as storage for images, please implement this feature

**Comment by Wander1024** [comment]
+1

**Comment by dominic-miglar** [comment]
:+1:

**Comment by Nepoxx** [comment]
@torkelo 
> we are using the aws sdk to upload, it requires region and s3 credentials. So not sure it supports alternative http enpdoints
I know this is an old request, but you can definitely use the aws sdk with other S3 compatible storage (minio, Digital Ocean, etc.).

**Comment by marefr** [comment]
@Nepoxx this [change](https://github.com/grafana/grafana/pull/20354) is included in v6.6.0, but we forgot to add it to the changelog. So I think this issue is solved now?

**Comment by Nepoxx** [comment]
@marefr Yeah probably!

That being said, I am not able to get it to work, I guess that would be another issue.
