### ISSUE TITLE
[Feature Request] Allow to use S3 compatible services

### ISSUE THREAD

**Issue by rsilva4** [grafana/grafana#8157]
It would be nice to be able to use S3 compatible services like [Minio](https://minio.io/). Right now it appears to be [hardcoded](https://github.com/grafana/grafana/blob/b387a8759e0c88367b8c7a75115f26b6267ffbc3/pkg/components/imguploader/s3uploader.go#L81) to AWS urls.

Here is how to use [AWS Go SDK to connect to a Minio server](https://docs.minio.io/docs/how-to-use-aws-sdk-for-go-with-minio-server).

**Comment by herver** [comment]
I'd be happy to provide a fix as we run some S3 compatible storage but can't use it because of the hard-coded AWS urls as mentioned by @rsilva4 , they're also [here](https://github.com/grafana/grafana/blob/master/pkg/components/imguploader/imguploader.go#L65-L92)

The only thing is that I don't really see a nice and clean solution to this (without weakening current checks)

**Comment by torkelo** [comment]
@herver it's not the hard coded AWS urls is the main problem (I think), its we use the official AWS SDK libs to support IAM / EC2 roles auth for s3 upload. 

But if the official AWS Go s3 lib can work with s3 compatible endpoints then I am all for changes to make that happen :)

**Comment by Fusl** [comment]
I'm trying to configure Grafana with Ceph radosgw (S3 compatible API), the error message I get in the Grafana logs
```
t=2017-09-20T19:29:06+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Could not find bucket setting for image.uploader.s3"
```
suggests that it's aborting here: [`return nil, fmt.Errorf("Could not find bucket setting for image.uploader.s3")`](https://github.com/grafana/grafana/blob/87308fd97fc63bbcc2b5fe64a9f56f5016f19e77/pkg/components/imguploader/imguploader.go#L102)
This happens right after trying to match for [`https?:\/\/(.*)\.s3(-([^.]+))?\.amazonaws\.com\/?`](https://github.com/grafana/grafana/blob/87308fd97fc63bbcc2b5fe64a9f56f5016f19e77/pkg/components/imguploader/imguploader.go#L78) and [`https?:\/\/s3(-([^.]+))?\.amazonaws\.com\/(.*)?`](https://github.com/grafana/grafana/blob/87308fd97fc63bbcc2b5fe64a9f56f5016f19e77/pkg/components/imguploader/imguploader.go#L90)

This was implemented by [a PR](https://github.com/grafana/grafana/pull/7058) trying to implement IAM support.

The broken configuration for the S3 compatible radosgw API is:
```
[external_image_storage.s3]
bucket_url = http://share.grafana.fvz.io/
access_key = xx
secret_key = xx
```

**Comment by laughland** [comment]
I created the following PR that would add in Minio support - https://github.com/grafana/grafana/pull/9961

**Comment by azhiltsov** [comment]
Any chances to get #9961 merged to the master?
