### ISSUE TITLE
Templating: Datasource as variable

### ISSUE THREAD

**Issue by falkenbt** [grafana/grafana#816]
I really like the 1.8 templating feature. I'm wondering we could have a special variable $datasource to quickly switch the datasource for all graphs?

**Comment by idebruijn** [comment]
+1

**Comment by Sybsw** [comment]
This feature would be hugely beneficial for us. At the moment my team works with test and production versions of the dashboards looking at the respective graphite instances. The ability to overwrite the prod one with the test one and then quickly switch all the data sources would be excellent.

**Comment by williamjoy** [comment]
+1

**Comment by sckevmit** [comment]
+1

**Comment by ibam** [comment]
We also have pro and test dashboards, and this feature will help us a lot in simplifying the maintenance of the dashboard since we will only need to maintain a single dashboard with switchable datasource instead of having multiple copies of the dashboard pointing to different datasources. Will this feature be part of the Grafana 2.0 release, @torkelo?

**Comment by cemo** [comment]
+1

**Comment by kerush** [comment]
:+1:

**Comment by jwestboston** [comment]
+1

**Comment by phrend** [comment]
My company could use this as well. I would like to be able to create a single dashboard, and select which environment's (dev/qa/prod) data to view. For my use-case, having a specific datasource variable would work, but it seems like being able to use a standard template variable would be more flexible.

**Comment by agilgur5** [comment]
+1

**Comment by lancehunt** [comment]
+1

**Comment by jozic** [comment]
+1

**Comment by thebyrd** [comment]
+1

**Comment by monestri** [comment]
+2

**Comment by mwitkow** [comment]
It would be fantastic if we could have this. Our data sources (Prometheus) are doing per-cluster monitoring. Having to keep a copy of each dashboard separately for each cluster is really painful.

If we could have template parameter expansion on the Datasource for each graph/template variable dropdown, it would be insanely good :) For Example: being able to set: 
```js
  "panels": [
   {
          "datasource": "$cluster monitoring",
   }
 ]
```

**Comment by mtanda** [comment]
+1

**Comment by ankitdimania-eligible** [comment]
+1

**Comment by alaphoid** [comment]
+1

**Comment by codeb2cc** [comment]
+1

**Comment by nick4eva** [comment]
+1

**Comment by bobo** [comment]
+1

**Comment by eddiemoser** [comment]
+1

**Comment by utkarshcmu** [comment]
@torkelo How about this as an option in settings instead of having datasource as a template variable?

<img width="859" alt="screen shot 2016-02-03 at 3 05 55 am" src="https://cloud.githubusercontent.com/assets/1019609/12780495/36fad84e-ca23-11e5-8004-40108ee41b4f.png">

**Comment by eddiemoser** [comment]
@utkarshcmu that would work for my needs if we could put that on the dashboard at the top.

**Comment by tehlers320** [comment]
+1

**Comment by mburger** [comment]
+1

**Comment by mwitkow** [comment]
Would that be override-able from a template variable so you can deep-link?

**Comment by throck** [comment]
+1 :metoo:

**Comment by bpang** [comment]
+1

**Comment by grobie** [comment]
+1

**Comment by PaulKuiper** [comment]
+1

**Comment by jacobrichard** [comment]
+1

**Comment by ntent-ashton** [comment]
+1

**Comment by evanbreznyik** [comment]
+1

**Comment by rvrignaud** [comment]
+1

**Comment by torkelo** [comment]
New template variable is now available (Data source)
![image](https://cloud.githubusercontent.com/assets/10999/14895241/f756942e-0d77-11e6-910a-091c0c470caf.png)

You pick the data source type and the variable will be automatically populated with all your data sources of that type. You can also provide a regex filter. When you add a new data source it will be automatically available in the variable values dropdown (if it passes the regex filter that is)

You can pick the variable in the panel data source selection:
![image](https://cloud.githubusercontent.com/assets/10999/14895284/279246ce-0d78-11e6-8cb5-acd25b54a9cc.png)

You can also have other query template variables use the template variable: 
![image](https://cloud.githubusercontent.com/assets/10999/14895305/4e1450c6-0d78-11e6-9d31-8d0fcf702d58.png)

**Comment by grobie** [comment]
YES! Thanks @torkelo

**Comment by eddiemoser** [comment]
Much needed thank you

**Comment by torkelo** [comment]
@toni-moreno I hope you still need this, sorry for it taking so long :)

**Comment by PaulKuiper** [comment]
Great additions. Perfect timing for me. Thanks!

**Comment by surendarchandra** [comment]
Its awesome. I have one issue, for Annotations, it lets me select Datasource but has no elements in it? How do I choose annotations from a certain datasource? Thanks

**Comment by toni-moreno** [comment]
Hi @torkelo , Is perfect !! Better late than never!.  Thanks !

**Comment by akaHuman** [comment]
@torkelo Is there a way to multiselect Datasource template and then do a repeat row on that?

**Comment by torkelo** [comment]
Not sure

**Comment by reinhard-brandstaedter** [comment]
I was just looking for this @akaHuman ! Templating the datasource makes switching dashboards to different sources easy, but a multi-select and repeat on rows/panels would be really useful.
e.g. we have multiple customers with a separate database each. Now I want to ahve an overview dashboard that shows metrics of all databases in one.

**Comment by AniGunner** [comment]
@torkelo Hi,
I am using Grafana v5.3.4 (69630b9),there is no option for datasource templating.can you please tell me in which version it is available??

**Comment by torkelo** [comment]
You go into dashboard setting and create a new variable of type datasource, then you can select this datasource in the datasource selector in the panel settings

**Comment by gaetanquentin** [comment]
Is 'Datasource' variable name a recognized built-in variable ?

**Comment by gongruitao** [comment]
> Is 'Datasource' variable name a recognized built-in variable ?

I have the same question, how to get name of the data source current in use? $env.name??

**Comment by czm41k** [comment]
I have issues trying to save my graph with created alert when using parametrised datasource ($datasource):
```
Alert validation error: Data source used by alert rule not found, alertName=<NAME>, datasource=$datasource
```
Grafana v 6.5.2

**Comment by tinyweasel** [comment]
I also need to do a parameterized data source based alert, should this work?

**Comment by czm41k** [comment]
Unfortunately, Its still not implemented
