### ISSUE TITLE
v10.3.1 - newVizTooltips max width too small

### ISSUE THREAD

**Issue by gburiola** [grafana/grafana#81622]
### What happened?

We just upgraded from version  v9.5.1 to v10.3.1. In the latest version, we enabled feature toogle `newVizTooltips`.

If you have have labels with very long values, they are truncated and there's no way to control it. This is specially bad with kubernetes pod names where the most important thing is the end of it.

### v9.5.1
![image](https://github.com/grafana/grafana/assets/6121373/5c85ba7a-b855-49f2-b437-3c102a879a74)

### v10.3.1 with newVizTooltips ENABLED
![image](https://github.com/grafana/grafana/assets/6121373/f8de7ab3-6f63-489e-9ee5-55ec93b80fd2)

### v10.3.1 with newVizTooltips DISABLED
![image](https://github.com/grafana/grafana/assets/6121373/66d63707-1544-4ec0-a95b-6df46e5946cb)

I believe this was introduced on https://github.com/grafana/grafana/pull/75841
@adela-almasan FYI

### What did you expect to happen?

tooltip adjust to width of the value

### Did this work before?

yes. worked on v9.5.1

### How do we reproduce it?

Enable `newVizTooltips ` feature toggle in  v10.3.1

### Grafana platform?

Kubernetes

**Comment by leeoniya** [comment]
now that we have explicit control over maxWidth and maxHeight, perhaps we should remove the defaults for these.
