### ISSUE TITLE
[bug] Grafana/openTSDB 2.3 getting error "c is undefined" on the graph panel

### ISSUE THREAD

**Issue by Helene** [grafana/grafana#8164]
- What Grafana version are you using?
4.2.0
- What datasource are you using?
openTSDB
- What OS are you running grafana on?
Windows 7
- What did you do?

Hello,
I wanted just test the graph panel with a simple query using openTSDB **2.3** API. ( The same query works fine with openTSDB 2.2).
Here is the query: 
![query](https://cloud.githubusercontent.com/assets/22845495/25170668/afd1fbac-24eb-11e7-8bc9-c4ff126ff15e.JPG)
Here is the error:
![error](https://cloud.githubusercontent.com/assets/22845495/25170692/c035938c-24eb-11e7-80ed-f79a3f095db0.JPG)

I don't think this is network issue since the data source connection was established sucessfully and using Developer Tools Network I can see dps values in returned results:

![network](https://cloud.githubusercontent.com/assets/22845495/25170869/4c90caea-24ec-11e7-8f33-f5c76f4b6b9e.JPG)

**Comment by torkelo** [comment]
Has OpenTSDB 2.3 changed anything in how they return data? 
@utkarshcmu any ideas?

**Comment by tinder-ubhatnagar** [comment]
No, OpenTSDB 2.3 has the same way of returning data as 2.2. Grafana has been supporting 2.3 since a long time now!

**Comment by Helene** [comment]
found issue cause
