### ISSUE TITLE
Table footer -> Count formats integer-counts as the units of the fields above (dollars etc)

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#81670]
This illustrates well the issue:

<img width="578" alt="image" src="https://github.com/grafana/grafana/assets/2903904/bae6ecb7-3e5c-482c-a75a-e93b6929b80c">

When configured with this:
<img width="448" alt="image" src="https://github.com/grafana/grafana/assets/2903904/3fac8e89-e5e9-4dd9-8d48-3d0bec4e987d">

The correct formatting in the footer would just say `4`, `4`, `2`, but instead it says `4 GiB` and `$4` for the first two value columns.

**Comment by samjewell** [comment]
Arguably the "Count rows" toggle (which appears when you choose "Count") is the workaround for the bug that I reported. I just don't like it when we "fix" a bug by shipping a workaround to that bug
![image](https://github.com/grafana/grafana/assets/2903904/dfbc314f-3ab8-4b90-bca5-42e5603e0b3a)

**Comment by samjewell** [comment]
Some feature requests I have around the Table panel:

- Can we make Table Footer enabled by default? Like we recently did with Shared Crosshair?
- It's currently impossible to have `count` in the footer for one column (such as an identifier column), and `sum` beneath the other "value" columns. Could we support this? Maybe be flipping the user-interaction around this feature, so you pick each field first, and pick the reducer-function you want for each column you want reduced?

Let me know if I should open another ticket for these - if that can help get them prioritised

**Comment by codeincarnate** [comment]
The issue is here: https://github.com/grafana/grafana/blob/17358bd7c9d31a29c59e509ac5b8f2b91bdd81f8/packages/grafana-ui/src/components/Table/utils.ts#L388

`getDisplayProcessor` will apply units here regardless of the reducer being used. Currently exploring ways to solve this.
