### ISSUE TITLE
Monaco editor does not reflect changes to the query in the onChange callback

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#81687]
**Why is this needed**:

The Monaco Editor uses the first version of props.onChange in handleOnMount i.e. always has the initial value of query because underlying Monaco editor is passed `query` below in the onChange callback. handleOnMount is called only once when the editor is mounted and does not get updates to query. So we need useRef to get the latest version of query in the onChange callback. 

This request is a result of observations in [fixes](https://github.com/grafana/grafana/pull/81343) we have made :) 

**What would you like to be added**:

It would be better if updates to the query were reflected in the onChange callback.

**Who is this feature for?**

Users of the Monaco CodeEditor.

**Comment by ivant** [comment]
@joey-grafana @joshhunt Why was this fix reverted in #83677? It is a really non-obvious behavior of `CodeEditor` that makes it hard to use it when writing a plugin. Is there a good rationale for the current behavior that is described somewhere?

**Comment by palecoyote** [comment]
Agreed with @ivant, this is very confusing behavior.  Can we at least reopen the issue?
