### ISSUE TITLE
[Feature request] Alert List - filter to display alerts only from specified dashboards

### ISSUE THREAD

**Issue by MarvAmBass** [grafana/grafana#8168]
I'd like to request a useful feature.

You can already filter/query the 'Dashboard List' Plugin to only display Dashboards with a matching name.

If we could also add this functionality to the 'Alert List' Plugin, so only alerts from specified dashboards are displayed would be a great feature!

Thanks

**Comment by generelspaz** [comment]
yes please, this feature specially will be great for making a specific micro service dashboard and then an application dashboard and tag each subsequent service with the application and filter all services used by that application and see what services are not working as expected.

**Comment by hfuhuang** [comment]
I would also like to have an alerting list for given dashboards, instead of only from current dashboard or all.
