### ISSUE TITLE
Alert notification function failed！

### ISSUE THREAD

**Issue by aliasmee** [grafana/grafana#8169]
http://docs.grafana.org/installation/configuration/#smtp
**## Official guidance**
All options in the configuration file (listed below) can be overridden using environment variables using the syntax.
Then you can override them using:
```
export GF_DEFAULT_INSTANCE_NAME=my-instance
export GF_SECURITY_ADMIN_USER=true
export GF_AUTH_GOOGLE_CLIENT_SECRET=newS3cretKey

```

Please include this information:

What Grafana version are you using?
v4.1.1
What datasource are you using? 
influxDB
What OS are you running grafana on?
Docker platform

# **Questions：Alert notification send email failed**

**1.Runing container command for configured SMTP：**
`docker run -d -p 80:3000 -e INFLUXDB_HOST=localhost -e INFLUXDB_PORT=8086 -e INFLUXDB_NAME=cadvisor -e INFLUXDB_USER=root -e INFLUXDB_PASS=root -e GF_SMTP_ENABLED＝true -e GF_SMTP_HOST=smtp.163.com:25 -e GF_SMTP_USER=mymailaddress@163.com -e GF_SMTP_PASSWORD=secretkey -e GF_SMTP_FROM_ADDRESS=mymailaddress@163.com --link influxsrv:influxsrv --name grafana-alerting grafana/grafana`

**2. View environment variables**
```
＃export 
declare -x GF_SMTP_ENABLED="true"
declare -x GF_SMTP_FROM_ADDRESS="mymailaddress@163.com"
declare -x GF_SMTP_HOST="smtp.163.com:35"
declare -x GF_SMTP_PASSWORD="secretkey"
declare -x GF_SMTP_USER="mymailaddress@163.com"
```

**3. Then I login on to the web interface and add test Alert notification**
```
Problem!
Failed to send alert notifications
```

**4. This is Grafana Log**
`t=2017-04-19T12:18:49+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-04-19T12:18:49+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[tester@163.com]
t=2017-04-19T12:18:49+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="Grafana mailing/smtp options not configured, contact your Grafana admin"
t=2017-04-19T12:18:49+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Grafana mailing/smtp options not configured, contact your Grafana admin"
t=2017-04-19T12:18:49+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=111.198.237.95 time_ms=1ns size=48`

**Excuse me, is this a bug, or is my configuration error? Please help point out, thank you！**

**Comment by daniellee** [comment]
1. You can check in the Grafana UI if they are set:

![image](https://cloud.githubusercontent.com/assets/434655/25185984/19911b4e-251f-11e7-9b7f-4918daa6c481.png)

2. In the log, when Grafana starts it should log which variables got overridden:

`INFO[04-14|07:49:55] Config overriden from Environment variable logger=settings var="GF_SMTP_SKIP_VERIFY=true"`

3. As a sanity check, you could check if the env variables were set in the container:

- `docker exec -i -t <your docker container id> /bin/bash`
- `echo $GF_SMTP_HOST`

**Comment by aliasmee** [comment]
Hi, @daniellee  I'm glad you answered my question in time. … ^_^ 

**1. The following screenshot is set  on Grafana UI**
<img width="436" alt="grafana-alert" src="https://cloud.githubusercontent.com/assets/22883562/25190287/593cba66-255e-11e7-9372-1507c329bb3e.png">

**2. I checked the variables according to your tips. The GF_SMTP_ENABLED variable is found to be empty (no variables in the system) But I did add the environment variable when running the container. (-e GF_SMTP_ENABLED=true)**
```
root@dfc9430a339a:/# export | grep "GF"
declare -x GF_SMTP_FROM_ADDRESS="mymailaddress@163.com"
declare -x GF_SMTP_HOST="smtp.163.com:25"
declare -x GF_SMTP_PASSWORD="secretkey"
declare -x GF_SMTP_SKIP_VERIFY="true"
declare -x GF_SMTP_USER="mymailaddress@163.com"
```

```
root@dfc9430a339a:/# echo $GF_SMTP_ENABLED


```
**3.The following is a log prompt to start Grafana**

```
root@10ef54888aa9:/# tail -100f /var/log/grafana/grafana.log 
......
t=2017-04-19T15:53:21+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-04-19T15:53:21+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_HOST=smtp.163.com:25"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_USER=mymailaddress@163.com"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_PASSWORD=*********"
t=2017-04-19T15:53:21+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SMTP_FROM_ADDRESS=mymailaddress@163.com"
t=2017-04-19T15:53:21+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
```

Look forward to your reply。Thank you ！……^_^

**Comment by torkelo** [comment]
You seem to be missing the GF_SMTP_ENABLED environment variables, it is not reported by export command and grafana is not seeing it at startup, double check how start your container

**Comment by aliasmee** [comment]
**The following is my command to run when the docker container：**

`docker run -d -p 80:3000 -e INFLUXDB_HOST=localhost -e INFLUXDB_PORT=8086 -e INFLUXDB_NAME=cadvisor -e INFLUXDB_USER=root -e INFLUXDB_PASS=root -e GF_SMTP_ENABLED＝true -e GF_SMTP_HOST=smtp.163.com:25 -e GF_SMTP_USER=mymailaddress@163.com -e GF_SMTP_PASSWORD=secretkey -e GF_SMTP_FROM_ADDRESS=mymailaddress@163.com --link influxsrv:influxsrv --name grafana-alerting grafana/grafana`

`-e GF_SMTP_ENABLED＝true`

Excuse me, what's wrong with the above operation?？Thanks

**Comment by daniellee** [comment]
@aliasmee The equal to sign looks strange. GF_SMTP_ENABLED＝true vs GF_SMTP_ENABLED=true

This sign: ＝ is not the same as =

**Comment by orientzc** [comment]
@aliasmee @daniellee 
yeah. i also think the problem is this character =. it shouldnnt be the chinese =, and it should be the english =.
like this:
docker run -d -p 80:3000 -e INFLUXDB_HOST=localhost -e INFLUXDB_PORT=8086 -e INFLUXDB_NAME=cadvisor -e INFLUXDB_USER=root -e INFLUXDB_PASS=root -e GF_SMTP_ENABLED=true -e GF_SMTP_HOST=smtp.163.com:25 -e GF_SMTP_USER=mymailaddress@163.com -e GF_SMTP_PASSWORD=secretkey -e GF_SMTP_FROM_ADDRESS=mymailaddress@163.com --link influxsrv:influxsrv --name grafana-alerting grafana/grafana
good luck.

**Comment by aliasmee** [comment]
@daniellee @torkelo  
 Very embarrassing, my mistakes！Did not expect is the "=" character problem。
**Thanks again for your help. The problem has been solved**

Best Regards
