### ISSUE TITLE
At small timescale, graph-hover event is inconsistent

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#8172]
(in grafana 4.3.0-pre1)

When you zoom to a small scale (less then .5s?) the graph-hover events don't have x or y info
```
appEvents.on('graph-hover', (event) => { ...
```
```
pos : Object
  ctrlKey : false
  metaKey : false
  pageX : 442
  pageY : 438
  panelRelY : 0.45974381764729816
```

Normal results look like:
```
pos : Object
  ctrlKey : false
  metaKey : false
  pageX : 564
  pageY : 426
  panelRelY : 0.39724381764729816
  x : 1492579565696.5745
  x1 : 1492579565696.5745
  y : 0.15911483764648438
  y1 : 0.15911483764648438
```

This is not a big deal, but figured it is worth a report.  I would either expect there to be values or no event

**Comment by torkelo** [comment]
unable to replicate this:
![image](https://cloud.githubusercontent.com/assets/10999/25197999/4b025bbc-2546-11e7-8a6e-784d3b93a5d6.png)

I get positions even when I go below a 100ms time range. 

There needs to be data points for the x/y to have values I think, could be it

**Comment by ryantxu** [comment]
> There needs to be data points for the x/y to have values I think, could be it

ahh -- yes, that is it.  When zoomed far enough the data goes away.
