### ISSUE TITLE
Why old data not visible 

### ISSUE THREAD

**Issue by prasenforu** [grafana/grafana#8173]
I am using grafana and prometheus as a data source in kubernetes  platform.

Both grafana & prometheus data in persistent storage.

If I shutdown entier environment then check in next day to plot yesterday there is no data.

In display its showing "no data points"

Please help.

Grafana 4.2
Prometheus 1.5

All are in container.

**Comment by torkelo** [comment]
Prometheus needs to be running to collect data, which I think you understand (sounds like your surprised there is not data while it was shut down) 

Make sure you prometheus container have persisted volumes defined for its db

**Comment by prasenforu** [comment]
As I mentioned "Both grafana & prometheus data in persistent storage".

If I query in Prometheus previous day data I am able to fetch.

**Comment by torkelo** [comment]
you can check the query grafana sends to prometheus and prometheus response:

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by prasenforu** [comment]
When query, does grafana fetch data from prometheus and store in its own DB (sqlite) ?

**Comment by torkelo** [comment]
> When query, does grafana fetch data from prometheus and store in its own DB (sqlite) ?

no, it queries Prometheus and graphs it directly, the sqlite database is only for dashboards and users
