### ISSUE TITLE
Display issue when Grafana is behind Apache SSL Reverse proxy

### ISSUE THREAD

**Issue by uvsq21306949** [grafana/grafana#8176]
What Grafana version are you using? -> Grafana v3.1
What datasource are you using? Graphite
What OS are you running grafana on? Debian Jessie
What did you do? -> Put Grafana behind Apache reverse proxy

Hello,

Since 1 year, in our organisation, we are using Grafana (3.1) in direct access without reverse proxy and it works very well. 
We decided to put Grafana behind a secure SSL Apache reverse proxy, this is our conf files : 

- grafana.ini : 

app_mode = production

[database]
host = 127.0.0.1:3306
name = grafana
password = grafana
type = mysql
user = grafana

[server]
protocol = http
http_port = 8080
http_addr = 127.0.0.1

[users]
allow_sign_up = false
allow_org_create = false

[auth.anonymous]
enabled = false

[auth.basic]
enabled = true

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true

- metrologie.conf (Apache reverse proxy) : 

<virtualhost *:443>
        ServerName metrics
        ProxyPass / http://127.0.0.1:8080/
        ProxyPassReverse / http://127.0.0.1:8080/
        ProxyRequests Off
        ProxyPreserveHost On
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/metrologie.cert.pem  
        SSLCertificateKeyFile /etc/apache2/ssl/metrologie.key.pem  
</virtualhost>

after applying this configuration, we are no longer able to view our dashboards, we got the following error message : 

![grafana](https://cloud.githubusercontent.com/assets/15668255/25221678/48eb05c0-25b6-11e7-9b72-198345b2c6d3.JPG)

Could you help please ?

**Comment by daniellee** [comment]
What error are you getting in the Grafana server logs?

**Comment by uvsq21306949** [comment]
Thank you for your answer,
We don't have errors in the logs, the error message in the screenshot above is related to mixed content (http/https) in the browser.
After investigation, we discovered that we are using graphite (non secure) Data source in direct mode, so the browser don't appreciate to show mixed secure Data from Grafana and unsecure data from Graphite.

We plan to secure Graphite with SSL to prevent this situation.

What do you think about that solution ?

**Comment by daniellee** [comment]
@uvsq21306949 you can't use proxy mode for the Graphite data source? Does the the grafana server not have access to the Graphite server?

**Comment by uvsq21306949** [comment]
In Proxy mode it works fine ! the issue is resolved. Thank you
