### ISSUE TITLE
[Bug] Sporadic Unable to load datasource meta data

### ISSUE THREAD

**Issue by marcherren** [grafana/grafana#8177]
Please include this information:
- What Grafana version are you using? -> Grafana v4.2.0
- What datasource are you using? Zabbix
- What OS are you running grafana on? CentOS 7
- What did you do? -> Nothing, was running fine over the last month..

 
Since yesterday I suddenly see a lot of the following errors:

t=2017-04-19T11:32:59+0200 lvl=eror msg="Unable to load datasource meta data" logger=context userId=1 orgId=8 uname=admin error="Data source not found"
t=2017-04-19T11:32:59+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=8 uname=admin method=POST path=/api/datasources/proxy/5 status=500 remote_addr=194.88.197.50 time_ms=1ns size=49

There was no change on the Zabbix nor on the Grafana site in the last 2 weeks

[root@bgsgrafana grafana]# ls -al
total 4652
drwxr-xr-x 2 grafana grafana 161 Apr 19 11:37 .
drwxr-xr-x. 10 root root 4096 Apr 16 03:25 ..
-rw-r--r-- 1 grafana grafana 4499753 Apr 19 11:37 grafana.log
-rw-r--r-- 1 grafana grafana 8912 Apr 12 23:59 grafana.log.2017-04-13.001
-rw-r--r-- 1 grafana grafana 14023 Apr 13 14:11 grafana.log.2017-04-14.001
-rw-r--r-- 1 grafana grafana 174 Apr 14 19:13 grafana.log.2017-04-18.001
-rw-r--r-- 1 grafana grafana 4649 Apr 18 12:02 grafana.log.2017-04-19.001
[root@bgsgrafana grafana]# grep "Data source not found" grafana.log | wc -l
12711
[root@bgsgrafana grafana]# grep "Data source not found" grafana.log.2017-04-13.001 | wc -l
15
[root@bgsgrafana grafana]# grep "Data source not found" grafana.log.2017-04-14.001 | wc -l
0
[root@bgsgrafana grafana]# grep "Data source not found" grafana.log.2017-04-18.001 | wc -l
0
[root@bgsgrafana grafana]# grep "Data source not found" grafana.log.2017-04-19.001 | wc -l
0

The dashboards are loading most of the time correctly, but let's say 1 out of 10 times it reports this error instead:

Zabbix API Error
{"message":"Unable to load datasource meta data"}
On the Zabbix server I did not see any errors in the log.

A reboot of the Grafana-server solved the issue for some time, therefore it might be related to grafana.

**Comment by torkelo** [comment]
Are you switching orgs sometimes? Do you use multiple orgs?

**Comment by marcherren** [comment]
Yes we do!
I have external customers as well as internal departments wich are all using different orgs.

**Comment by marcherren** [comment]
Ok, I can confirm that this happens once you login with the same user on two websessions and select a different org for each of it. Once you select the org on the second session, the first starts to display this error.
Is this per design? We didn't notice it in the last few month...

**Comment by torkelo** [comment]
yes, sadly you can only use one org at any time with a user (so you cannot use multiple orgs in different tabs at the same time)
