### ISSUE TITLE
[Feature request] Table Panel Swap Axis

### ISSUE THREAD

**Issue by derng** [grafana/grafana#8178]
Can you please add the ability to swap the axis in the Table Panel, where metrics is on the y-axis and time is on the x-axis?

I wish to achieve something similar to these standard examples:
http://servicestatus.sco.cisco.com/status
http://www.google.co.uk/appsstatus#hl=en&v=status

Related:
https://community.grafana.com/t/table-panel-swap-axis/618

- What Grafana version are you using?
4.2.0
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 6.8

**Comment by Brian-Rojas** [comment]
I really need this feature, I need to create one chart with many metrics and simply using the x-axis will squish my labels after 10 metrics. I need minimum 100 metrics on the y-axis. Is this doable?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
