### ISSUE TITLE
[alertmanager] exposing smtp secret in plain text for multitenant alertmanager

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/grafana#81805]
### What happened?

I pushed the alertmanager configuration via the mimir tool and was checking the config in grafana for the multitenant alertmanager.
I noticed that the password for the smtp user is there in plain text.
![image](https://github.com/grafana/mimir/assets/109516706/a0e5185e-5f67-45dc-8388-974485b07921)
Howerver when I go the the multitenant alertmanager url I see that there the secret is blurred.
-- auth_password: <secret> --

If I check in grafana with a singletenant alertmanager (https://github.com/grafana/prometheus-alertmanager)
I see that the secret is also hidden for this alertmanager.
![image](https://github.com/grafana/mimir/assets/109516706/36006155-5163-4bd1-beb1-b7d200e3c1aa)

If I change the alertmanager implementation to prometheus instead of mimir, the secret is also hidden.
![image](https://github.com/grafana/mimir/assets/109516706/86991626-407c-4fc5-86f3-6154f909ac8d)

### What did you expect to happen?

I expect that sensitive data is hidden and not displayed in plain text.

### Did this work before?

Don't know

### How do we reproduce it?

1. install the multitenant alertmanager via mimir distributed helm chart.
2. push some alertmanager config with mimirtool that contain smtp settings
3. add the alertmanager as a datasource in grafana with implementation Mimir
4. Go to alerts -- contanct points and open the smtp configuration and check for the password.

### Environment (with versions)?

Grafana: 10.2.2
OS:
Browser:

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager from mimir

**Comment by ToonTijtgat2** [comment]
This is a duplicate of https://github.com/grafana/mimir/issues/7276 since I don't know if it's for the grafana or the mimir team.

**Comment by tonypowa** [comment]
closing in favor of https://github.com/grafana/mimir/issues/7276
please monitor progress from there
thank you
