### ISSUE TITLE
XYChart: 'Single' vs. 'All' tooltip mode

### ISSUE THREAD

**Issue by aballinEH2** [grafana/grafana#81836]
### What happened?

When I have Tooltip mode set to 'Single' and hover over a data point, it shows information from all of the traces that have a data point near the x-coordinate I'm hovering over. This seems like the same behavior as if I had selected 'All' for the tooltip mode. Interestingly, selecting 'Hidden' does work at hiding the tooltip.

### What did you expect to happen?

I expected to only see information from the selected trace when the Tooltip mode is set to 'Single'.

### Did this work before?

I think this worked in Grafana v9.4.3

### How do we reproduce it?

1. Make an XY Chart with two traces that have at least one pair of points from each trace with similar x-coordinates.
2. Set Tooltip mode to 'Single'.
3. Hover over one of the data points in the pair.

### Environment (with versions)?

Grafana: 10.2.3

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by leeoniya** [comment]
Single mode works correctly now in the new XY panel (behind `autoMigrateXYChartPanel` feature flag)

![image](https://github.com/grafana/grafana/assets/43234/27ee7876-07aa-43b4-aff3-655de4038064)
