### ISSUE TITLE
Annotations: Annotations sometimes do not render

### ISSUE THREAD

**Issue by nickmoeck** [grafana/grafana#81846]
### What happened?

Annotations sometimes do not render. If set to render on all panels, some panels get annotations, some do not. Which panels get annotations and which do not seems to be random. Sometimes (rarely) only the arrows at the bottom of the annotation line render, and the dotted line does not.

Reducing the number of panels on the dashboard seems to improve the success rate of the annotations rendering, but it still fails over 50% of the time with a single panel.

The HTTP request which fetches the annotations always succeeds, and has the correct data.

### What did you expect to happen?

Annotations should be shown on the graphs every time the dashboard is loaded.

### Did this work before?

Works normally in Grafana 10.2.3, with the exact same data and dashboard definitions.

### How do we reproduce it?

1. Create a dashboard with a time series panel
2. Add an annotation to the graph, or add an annotation query to the dashboard.
3. Refresh the dashboard and observe that the annotations don't show up at least half of the time.

### Environment (with versions)?

Grafana: 10.3.1
OS: Windows 11
Browser: Chrome Version 121.0.6167.140 (Official Build) (64-bit)

### Grafana platform?

A downloaded binary

**Comment by leeoniya** [comment]
can you try toggling the `newVizTooltips` feature flag in a nightly build and see if it helps?

https://grafana.com/grafana/download/nightly?edition=oss
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#feature-toggles
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#configuration-file-location

e.g. this is my local `custom.ini` file:

![image](https://github.com/grafana/grafana/assets/43234/3da61d74-3044-4533-aa98-31e13e70cd82)

**Comment by nickmoeck** [comment]
Just tested in 10.4.0-66879 (fe6d1460b0) and annotations appear to be rendering all the time now. However, I did experience new abnormal behavior. On graphs that are below the fold, the triangles are sometimes rendered at the top of the graph and offset horizontally from where they should be, as in the attached image.

![Screenshot 2024-02-12 152226](https://github.com/grafana/grafana/assets/1075974/068c337b-0347-4cf2-947b-d62866cf7915)

**Comment by leeoniya** [comment]
yep, we're aware of the lazy-loaded panels issue and will look into a fix soon.

**Comment by nickmoeck** [comment]
Thanks for the prompt help!

**Comment by bobemoe** [comment]
I'm still experiencing this on 10.4.0:
[vokoscreenNG-2024-03-20_19-35-50.webm](https://github.com/grafana/grafana/assets/2304970/5ee28a6f-795d-47a5-a4ba-f6153f1a5732)

Its quite a complex dashboard and I haven't found a easy way to reproduce yet. Its a MySQL annotation query on Graphite panels. If I can reproduce easy I will open new issue.

What was the cause/fix for this issue? Maybe that give me clue to help.

I have not enabled newVizTooltips.

**Comment by leeoniya** [comment]
> I have not enabled newVizTooltips.

you should. the anno rendering was completely rewritten, with many bugs fixed.

there have been many additional fixes to `newVizTooltips` since 10.4, so you should try a nightly build of 11.0 and enable with them enabled.

there is still an issue with initial rendering for panels that are lazy-loaded (scrolled to / off screen / in a collapsed row). we will fix this soon: https://github.com/grafana/grafana/issues/84712

**Comment by bobemoe** [comment]
I cant enable newVizTooltips as there are some bugs (fixed in 11.0) holding us back.

This is another reason to perhaps use 11.0, but what is the target release date on it? I'm a bit reluctant because as soon as soon as I "fix" it in dev we'll want to deploy it to prod!

**Comment by leeoniya** [comment]
tomorrow is feature code freeze for us. then about a month of qa/bug fixes/beta testing. i think official 11.0 is early May.

**Comment by bobemoe** [comment]
OK, now could be a good time to jump on board then :)
