### ISSUE TITLE
How to show the latest 24-hour metrics data and the latest 10-hour metrics data in the same panel without the help of the time picker located in the top right corner?

### ISSUE THREAD

**Issue by leee66** [grafana/grafana#8185]
Hi,
I need to show the latest 24-hour metrics data and the latest 10-hour metrics data in the same panel. My SQL is as follows.
![1](https://cloud.githubusercontent.com/assets/12559285/25272755/ad61b5a2-26bb-11e7-82a0-7d88ee0a3971.jpg)

 However, the data I saw is showed according to the time range selector located in the top right corner. 【”time” > now() – 24h】 and 【”time” > now() – 10h】do not work. For example, please see the following pic. I chose 【Last 3 hours】in the top right corner, and then the data in the panel named as【latest 24hours & 10hours】changed according to 【Last 3 hours】.
![2](https://cloud.githubusercontent.com/assets/12559285/25272730/939e13d6-26bb-11e7-8122-f419e50ef922.jpg)

How to show the latest 24-hour metrics data and the latest 10-hour metrics data in the same panel without the help of the time picker located in the top right corner?

Look forward to your soon reply.
Thank you.

**Comment by torkelo** [comment]
Hi, please read the "new issue template" before posting new issues do not just delete the template without reading it first, this is pretty rude :) 

```
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

```

 Questions should be posted to https://community.grafana.com.
