### ISSUE TITLE
[Bug] deselect panel repeated value cause extra query

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8186]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Mac
- What did you do?
1. Create dashboard with panel repeat
2. select several value of panel repeat variable
3. deselect some value
- What was the expected result?
Only visible panel cause query.
- What happened instead?
There are extra query.
For example, if each panel has 1 query, and repeat 5 panel.
And then, deselect 1 value, it cause 10 query.
The query count should be 4 query.

Maybe, it is concurrency order problem.
The refresh event is reached to panel, before panel is removed.
https://github.com/grafana/grafana/blob/v4.2.0/public/app/core/directives/value_select_dropdown.js#L254
 
EDIT (2017/04/21 21:15 +0900):
10 query is not correct, 5 query.

**Comment by torkelo** [comment]
if you change a template variable the whole dashboard is refreshed (all panels), this is not a bug

**Comment by torkelo** [comment]
Or am I missing something?

**Comment by mtanda** [comment]
http://play.grafana.org/dashboard/db/prometheus-repeat

There are 3 panels, and if I deselect `alertmanager` from `job` variable.
The panel count becomes 2, so I expect only 2 query, but I see 3 query in devtools network tabs.

**Comment by mtanda** [comment]
And more,
edit query like `go_memstats_alloc_bytes{job="$job"}` and do same thing,
There are 2 query for `node` job.

![image](https://cloud.githubusercontent.com/assets/224552/25277202/a8082614-26d8-11e7-9774-9ffc587b45b9.png)

**Comment by torkelo** [comment]
ah, now I understand! sorry :)

**Comment by mtanda** [comment]
Just a memo for debugging.

first variableSrv.variableUpdated() call.
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/dashboard/submenu/submenu.ts#L20
fist updateOptions() call.
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/variable_srv.ts#L126
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/query_variable.ts#L85
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/variable_srv.ts#L184
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/query_variable.ts#L66
second variableSrv.variableUpdated() call.
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/variable_srv.ts#L242
second updateOptions() call.
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/variable_srv.ts#L126

from somewhere, dashboard refresh trigger updateOptions() call.
https://github.com/grafana/grafana/blob/v5.2.0/public/app/features/templating/variable_srv.ts#L45
