### ISSUE TITLE
Searching panel options throws a runtime error

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#81883]
See the attached video. The same thing happens when switching to the **Overrides** tab.

https://github.com/grafana/grafana/assets/2376619/d0e91055-39ef-46a8-8a53-81094ff23e04

**Comment by axelavargas** [comment]
Re-opening this issue, we had to revert the [PR](https://github.com/grafana/grafana/pull/82439)

**Comment by dprokop** [comment]
Closed by https://github.com/grafana/grafana/pull/82449

**Comment by kaydelaney** [comment]
Seems like this issue has come back :(
