### ISSUE TITLE
Problem in alerts list 

### ISSUE THREAD

**Issue by sLuvpreet33** [grafana/grafana#8188]
Using Grafana 4.2 on ubuntu 16.04 

Everything was working good, but it is happening from yesterday, and I don't have a clue,

![screenshot from 2017-04-21 17-20-27](https://cloud.githubusercontent.com/assets/23127804/25278071/e11738c4-26be-11e7-86cb-bba0f31bdfe1.png)

The alerts are showing this text, what is the problem, how can they be fixed ?

**Comment by torkelo** [comment]
what is the problem? the alert list seems to be working

**Comment by sLuvpreet33** [comment]
yes it is working, but why it is showing that query below it ?

**Comment by torkelo** [comment]
because it is showing the reason why the alert rule is triggering, it's showing that the query failed with connection refused, somehow grafana cannot reach influxdb

**Comment by sLuvpreet33** [comment]
It was not showing this query before.
Can I get rid of this query text from the alert list ?

**Comment by torkelo** [comment]
yes, by fixing the connection error so Grafana can reach influxdb again

**Comment by sLuvpreet33** [comment]
haha,  okay. I thought it was some error in grafana. Sorry for creating an issue for this.

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-04-22 03-36-31](https://cloud.githubusercontent.com/assets/23127804/25298529/42d7d06a-2713-11e7-9cfb-8b0fc46c3692.png)


How is this type of graph is possible ?

It is showing the value of the middle line only, but when I go in the extreme left, it shows me the value of the bottom axis ?
