### ISSUE TITLE
How to find backend to grafana and connecting to database mysql

### ISSUE THREAD

**Issue by jhagaurav026** [grafana/grafana#8191]
Hii,

how to connect with grafana backend mysql and how to see & i got error when add datasource graphite bad gateway error thanks in advance

**Comment by torkelo** [comment]
please open questions on the community site and be much more descriptive with your question. Your question right now is impossible to answer and understand :)

**Comment by jhagaurav026** [comment]
Hi torkelo

Actually i install Grafana 4.2.0 with NSM  successfully and run on http://localhost:3000 but when i add datasources graphite show the http error bad gateway. actually i have a database in mysql how to connect with grafana i mean how to connect grafana with mysql & where i to see database in grafana

**Comment by torkelo** [comment]
>  actually i have a database in mysql how to connect with grafana i mean how to connect grafana with mysql & where i to see database in grafana

Sorry, I do not understand you :( 

You have a graphite database in MySQL? Your graphite server is returning bad gateway? Does the Graphite API URL you enter work?

**Comment by jhagaurav026** [comment]
yes i have a graphite database in mysql and graphite server is running but its show http error bad gateway how to resolve.

**Comment by jhagaurav026** [comment]
![grafana](https://cloud.githubusercontent.com/assets/27891800/25313812/2c1c6498-2854-11e7-8e0b-ef750d29d3e1.png)
hi please see this u got my point perfectly i attached the screen shot

**Comment by torkelo** [comment]
Your graphite api is not working, it's returning error, have you tried accessing it on port 8080 on the same server as your running grafana on? 

Did you check graphite api logs?

**Comment by jhagaurav026** [comment]
torkelo i am running grafana on local host url is http://localhost:3000 its running successfully shown in screen shot actually i have database of otrs (OTRS is one of the most flexible web-based ticketing systems used for Customer Service, Help Desk, IT Service Management.) i want to connect with grafana to show statics graphs so what should i do in that case and one more question grafana supports mysql ?

**Comment by jhagaurav026** [comment]
one more thing please its important work please help me out asap hardly thank full to you

**Comment by jhagaurav026** [comment]
i have also few questions 
Grafana supports mysql ?
how to connect database (mysql) with grafana and where i to see the backend

**Comment by jhagaurav026** [comment]
if i have a api of some **demo_otrs** database so how its cofigure please ellaborate how to connect

**Comment by torkelo** [comment]
No grafana does not support MySQL yet. 

Your graphite time series database does not seem to work,  I can't help you any more, can hardly understand a single sentence you write :( sorry

**Comment by jhagaurav026** [comment]
https://www.percona.com/blog/2016/02/29/graphing-mysql-performance-with-prometheus-and-grafana/

please see this link this is a correct process or not its correct so how to connect grafana with mysql

**Comment by torkelo** [comment]
Yes, but that article never mentions connecting Grafana with MySQL. 

You need prometheus and prometheus node exporter to collect MySQL performance metrics, the you connect Grafana to Prometheus

**Comment by jhagaurav026** [comment]
i want to know if i have a graphite source of data than how to connect with grafana in case of mysql

**Comment by jhagaurav026** [comment]
1: Actually i have a database name otrs_Demo already preapred/developed in mysql 
2: i install grafana on local and its run perfectly 
3: my question is that  how to connect otrs_demo database with grafana

**Comment by daniellee** [comment]
@jhagaurav026 so Graphite is working? If you go to http://localhost:8080 in your browser, does that work?

**Comment by jhagaurav026** [comment]
@daniellee  graphite is not working its shows error http error bad gateway  i am running on local host

**Comment by daniellee** [comment]
@jhagaurav026 So the problem is Graphite is not working? How did you install it?

**Comment by daniellee** [comment]
@jhagaurav026 just checking but do you know that Grafana and Graphite are two separate products? Grafana is a time series visualization front end and Graphite is a time series database.

**Comment by jhagaurav026** [comment]
yes graphite is not working 
https://www.youtube.com/watch?v=QJxk0V5i6qM please see this link on youtube i follow these steps
if i go to link graphite url localhost:8080 its shows error

**Comment by torkelo** [comment]
@jhagaurav026  
That video is for Grafana, and installing it on Windows. Not Graphite. Graphite is a separate thing you install. It is the time series database.

But if you want to monitor MySQL I recommend Prometheus and Prometheus node exporter (metric collector to fetch mysql metrics). 

If you really want to use Graphite (But I doubt you understand what it is ) you need a linux system as it does not work on Windows. 

Again Graphite != Grafana.  They are two VERY different projects/systems

**Comment by jhagaurav026** [comment]
@daniellee  yes i know both are different  please give me your skype if have no problem i have few more queries on grafana actually i am confused grafana supports mysql  or not coz i searching many of websites shows its supports but what is process behind i want to know about the process coz i have a database in mysql i want to connect with grafana what should i do

**Comment by daniellee** [comment]
@jhagaurav026 It seems you still think Grafana and Graphite are the same program?

How to install Graphite:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server

Collectd with Graphite: https://www.digitalocean.com/community/tutorials/how-to-configure-collectd-to-gather-system-metrics-for-graphite-on-ubuntu-14-04

An Introduction to Tracking Statistics with Graphite, Statsd and CollectD:
https://www.digitalocean.com/community/tutorials/an-introduction-to-tracking-statistics-with-graphite-statsd-and-collectd

**Comment by daniellee** [comment]
@jhagaurav026 Grafana does not have any official support for MySQL yet (it is coming in the next version 4.3.0). As Torkel said above "No grafana does not support MySQL yet." 

Grafana is mainly a frontend for time series databases and MySQL is not a time series database.

**Comment by jhagaurav026** [comment]
@torkelo  i want use mysql than i will go Prometheus and Prometheus node exporter (metric collector to fetch mysql metrics). right ??

**Comment by jhagaurav026** [comment]
Thanks @torkelo  its connect with prometheus ..

**Comment by jhagaurav026** [comment]
@torkelo  @daniellee grafana successfully running on localhost:3000
and prometheus successfully running on localhost:9090
how to download prometheous exporter and configure please help

**Comment by jhagaurav026** [comment]
https://www.percona.com/blog/2016/02/29/graphing-mysql-performance-with-prometheus-and-grafana/

 see that link

**Comment by jhagaurav026** [comment]
hii @torkelo  please help me how to install node_exporter and mysqld_exporter on centos @daniellee  @matschaffer @damm @ctrochalakis

**Comment by torkelo** [comment]
@jhagaurav026 sorry we do not have time to help you anymore :(
