### ISSUE TITLE
Table Panel: Column selection UI

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#81913]
**Why is this needed**:
Users of tabular data often want to hide/show fields inline in the visualization without needing to change contexts and modify the current query. In addition, consumers of dashboards that were not involved with the query writing will struggle to make correlations in tabular data due to the lack of customization options available to them.

This feature void is creating snowflake implementations for point-and-click column selection, like in the new table view for logs in explore.
<img width="1709" alt="image" src="https://github.com/grafana/grafana/assets/109082771/289a4232-fbd2-4694-a75a-14ce70331062">

**What would you like to be added**:
The table visualization should expose UI allowing users to hide/show/reorder columns. 

**Who is this feature for?**
Users of logs panels (particularly in dashboards), upstream developers.

**Comment by leeoniya** [comment]
i think this should go into a wrapper component that does the column filtering. probably too much UX changes / design discussion needed to put this into core right now.
