### ISSUE TITLE
[Bug] Description is cut when shown on the browser edge

### ISSUE THREAD

**Issue by Runamook** [grafana/grafana#8192]
Grafana v4.2.0 (commit: 349f3eb) 
DS Graphite 1.0.0
OS Oracle Linux Server release 7.3

I've assigned a Description to a graph. A graph is placed at the left side of the row. 
When I reach the "i" icon with the mouse pointer I expect the full Description textbox to appear on the screen.
Instead the description box is cut at the left border of the browser, as depicted on the screenshot attached.

![screenshot from 2017-04-22 23-31-10](https://cloud.githubusercontent.com/assets/23465060/25308010/59f726dc-27b4-11e7-9178-06e74e848015.png)

 Egor

**Comment by torkelo** [comment]
already fixed in master, please search before posting a new issue :) 
Searching for description would have yielded about 5 duplicate issues of the same bug.

https://github.com/grafana/grafana/issues/7970

**Comment by Runamook** [comment]
My bad, looks like I've only searched for the open issues.

Thank you, Torkelo
