### ISSUE TITLE
Use api to import json file error

### ISSUE THREAD

**Issue by wspwork** [grafana/grafana#8193]
curl request:
`curl 'http://admin:admin@192.168.80.42:30/api/dashboards/import' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary @/home/bc1/unichain_business.json`
error:
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Grafana - Error</title>

		<link href='/public/css/fonts.min.css' rel='stylesheet' type='text/css'>

		<link rel="stylesheet" href="/public/css/grafana.dark.min.c7b017c5.css">

    <link rel="icon" type="image/png" href="/public/img/fav32.png">

		<base href="/" />

  </head>

	<body>

		<div class="page-container">
			<div class="page-header">
				<h1>
					Server side error :(
				</h1>
			</div>

			<h4>runtime error: invalid memory address or nil pointer dereference</h4>

			<pre></pre>

		</div>
	</body>

</html>`

My grafana run in docker container,   when I import json file with UI,it work well

**Comment by torkelo** [comment]
please use the normal dashboard save/update HTTP api that is documented here:
http://docs.grafana.org/http_api/dashboard/

The import API is much trickier to use as you need to specify data source mappings and other stuff (used in import UI when importing a dashboard from another instance where data source names do not always match)

**Comment by wspwork** [comment]
when I use the request:
`curl 'http://admin:admin@192.168.80.42:30/api/dashboards/db' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary @/home/bc1/unichain_business.json`

the new error:
`[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]`

**Comment by daniellee** [comment]
The error is saying that the `dashboard` field is required for this API call.

There is an [example in the docs that Torkel linked to](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard) that show how to structure the body of the request.

With curl, it should look something like this (you will need to paste the json from unichain_business.json file into the dashboard field):
```
curl -X POST -H 'Content-Type: application/json;charset=UTF-8' -d
'{
  "dashboard": {
    "id": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "rows": [
      {
      }
    ],
    "schemaVersion": 6,
    "version": 0
  },
  "overwrite": false
}' http://admin:admin@192.168.80.42:30/api/dashboards/db
```

**Comment by mojili** [comment]
I solved the problem like this:
1- first create your datasource like this (In my case I used the combination of collectd, prometheus and grafana)

curl --user admin:admin 'http://IPADDR:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"test","type":"prometheus","url":"http://localhost:9090","access":"proxy","basicAuth":false}'

2-For adding the customized json dashboard, edit grafana.ini file and enable Dashboard json file section like below:
;#################################### Dashboard JSON files ##########################
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards

3- then copy dashboard json file to /var/lib/grafana/dashboards (you need to restart the service)

**Comment by mojili** [comment]
mentioned solution let u add your dashboard in a path but if it is necessary to put in on db here is the solution. 
curl --user admin:admin 'http://IPADDR:3000/api/dashboards/db' -X  POST -H 'Content-Type:application/json;charset=UTF-8'  --data-binary @./dashboard.json

pay attention to the format of json you are going to post. It must have "dashboard" section and also the version for the beginning must be 1 .  something like below example:

"dashboard":{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
.
.
.
  "timezone": "browser",
  "title": "NAME",
  "version": 1
