### ISSUE TITLE
[Tempo] Allow opting out of variable suggestions in Tempo query editor

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#81942]
**Why is this needed**:

Tempo "search" query editor currently suggests variables as tag options. This is undersirable for app o11y plugin, where variables are internal and not meant to be exposed to users.

![Image](https://github.com/grafana/grafana/assets/847684/4edf78d3-e3dd-4280-a1e6-e7feefe07b4e)

**What would you like to be added**:

An option to Tempo query editor to not show variables with tag options in the "search" query editor. 

**Who is this feature for?**

App o11y plugin, maybe others

**Comment by aocenas** [comment]
is this only problem with tempo DS? I thought we do this as standard think with all query editors so wonder if you don't have the same issue with others.

**Comment by fabrizio-grafana** [comment]
> wonder if you don't have the same issue with others.

@domasx2 To slightly elaborate on this: We were wondering if instead of fixing this issue just for the Tempo plugin, it could make sense to fix this for all data source plugins.

**Comment by domasx2** [comment]
> is this only problem with tempo DS? I thought we do this as standard think with all query editors so wonder if you don't have the same issue with others.

> @domasx2 To slightly elaborate on this: We were wondering if instead of fixing this issue just for the Tempo plugin, it could make sense to fix this for all data source plugins.

App o11y only includes Tempo and Loki query editors. I see that these variables also pop up in Loki query editor builder mode. It would be nice to be able to disable this for Loki query editor too. But haven't yet seen customers actually use builder mode yet :)

**Comment by domasx2** [comment]
fixed with https://github.com/grafana/grafana/pull/87126
