### ISSUE TITLE
Nested folder picker does not filter for permissions

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#81941]
Seeing a bug in NestedFolderPicker it is showing folders that I do not have permission to save dashboards to. This user only has permissions to save in one folder, but seeing all here when I am trying to create (or copy) a dashboard to a folder I have permission to.

additional slack thread for reference: https://raintank-corp.slack.com/archives/C036J5B39/p1708132717509169

![image](https://github.com/grafana/grafana/assets/46142/b9f1e465-a1d6-42a6-8281-b08b2948b374)

![image](https://github.com/grafana/grafana/assets/46142/da05196c-9ea1-49f3-b306-4842af8c3123)

**Comment by nickfuzer** [comment]
+ slack thread: additional slack thread for reference: https://raintank-corp.slack.com/archives/C036J5B39/p1708132717509169

**Comment by eledobleefe** [comment]
Blocked until this PR is merged: https://github.com/grafana/grafana/pull/83527
