### ISSUE TITLE
Saga - VKO presentation

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#81984]
Create a presentation to present an unconference at the upcoming VKO.

**Presentation for VKO uncofference structure:**
- 2023 (FY24) recap
    - Wins
    - Went public
    - atomic setup
    - Launch of templates and large patterns
- Plans for 2024 (FY25)
    - Metric improvements
    - Reconfigurablility
    - larger components/patterns
    - Figma experience improvements
    - DesignTokens
    -Help teams leverage bundling grafana/ui
        - less delay in component usage for teams outside of core grafana

shoot for around 20 mins

Signed up [here](https://docs.google.com/document/d/1oKNb7aYleGrtjCHbI8Cct0PaKVnOofBMVxYzRPsvZEU/edit#heading=h.tmsamszcgsnm)

[Slide template](https://docs.google.com/presentation/d/1q93ioA7U9K2sGD16W-_wCHinn2OxV0I0LQQXzVE404c/edit?usp=sharing)

**Comment by staton-hyse11** [comment]
Need to account for the release of primitive components!

**Comment by staton-hyse11** [comment]
[VKO deck](https://docs.google.com/presentation/d/1zWHMg5bl2WgSzG2XdeHlrm45sXSXpe6L2Gzay2nn-Cs/edit#slide=id.g2b85af0dbc4_0_24)

**Comment by JoaoSilvaGrafana** [comment]
Biggest Wins:
- New components (`Text`, `TextLink`, `Box`, `Stack`, `Grid`)
- Added invalid state to components that were missing it (`RadioButtonGroup`, `Checkbox`, `Switch`)
- Alignment of `IconButton` component between code and figma
- Standardised border-radius tokens and created tasks on each team to use them
- Hosting Saga publicly
  - Write documentation for base components in Saga
  - Created 5 different templates in Saga
  - Added a component status page
  - Added live preview snippets to Saga

**Comment by staton-hyse11** [comment]
Crushed it.
