### ISSUE TITLE
[Feature request] JWT Authentication

### ISSUE THREAD

**Issue by lobeck** [grafana/grafana#8198]
By now it would be great to get JWT Authentication support.

One use case for this would be Google IAP (https://cloud.google.com/iap/). In this case Google would do the authentication and passes a JWT Header containing the user information. I guess Google is just the starter for such use cases and other implementations might evolve soon.

There is still the option for OAuth, but this would be redundant for such cases, as OAuth takes already place at the auth proxy and we merely need to parse the passed header. There's also no issue from the security perspective, as the `X-Goog-Authenticated-User-JWT` header is signed. 

Here are the details about their respective headers:
- https://cloud.google.com/iap/docs/identity-howto#getting_the_users_identity_in_compute_name_short_container_name_short_and_gae_name_short_flexible_environment
- https://cloud.google.com/iap/docs/signed-headers-howto

This is in response to #1247

**Comment by ahume** [comment]
If we were able to work on this and contribute, would you accept a PR? Anything we should consider/design upfront?

**Comment by joar** [comment]
@ahume Pinging @torkelo from the old issue, he seems to have seen this issue, but I'm not sure he's seen your comment.

I'm also a user of IAP+Grafana, currently I've set it up with IAP+Google OAuth2, it works, but it means you'll have to sign in twice. It would be super neat if Grafana could just accept the JWT from IAP.

**Comment by jirwin** [comment]
@lobeck @ahume I implemented support for this in #9166. Would love any feedback!

**Comment by joar** [comment]
I can't try it out since i'm not able to build my own docker image of grafana easily.

**Comment by dekimsey** [comment]
FWIW, this is also something that would be helpful in AWS. We use the oidc configuration in our AWS ALB's to authenticate against Azure. The JWT information is encoded in the headers passed back to the application.

> x-amzn-oidc-accesstoken
> The access token from the token endpoint, in plain text.
>
> x-amzn-oidc-identity
> The subject field (sub) from the user info endpoint, in plain text.
> 
> x-amzn-oidc-data
> The user claims, in JSON web tokens (JWT) format.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html#user-claims-encoding

**Comment by felipebn** [comment]
Hey Grafana team, is this a feature you are willing to move forward? 

The linked PR has some interactions and I’m able to move further with making it mergeable but I would like to see some feedback from grafana team before investing time on it.

Could some of you give some feedback here or in the PR?

**Comment by rjmoseley** [comment]
I've been digging around as an interested party and I believe this has been implemented in https://github.com/grafana/grafana/pull/29995.  The docs for this are live on the docs site against 7.5.x (https://grafana.com/docs/grafana/latest/auth/jwt/) however I don't see the relevant work in the 7.5.x releases so I'm working on the assumption (and hoping) that this will instead be in the next release.  :crossed_fingers:

**Comment by rjmoseley** [comment]
Had a play with a build from master and this seems to work with Google's IAP.  I have however hit a problem in that I don't seem to be able to find a way of automatically creating a user when a new one connects via an IAP (in the same way as one can be when using oauth `allow_sign_up = true`, ldap `allow_sign_up = true` or auth proxy `auto_sign_up = true` authentication.)  Therefore all users need to be pre-populated in the db before JWT authentication is enabled, a bit of a show stopper for our usecase.  I've attempted to get a grafana developer environment up and running locally to have a poke around but that's proving harder than I hoped.

Interested to hear if anyone else is seeing the same or if I've missed anything?  Would be great if we could get this figured out in time to be included in the initial jwt auth release.  For reference the config I've used is below.

```
[auth.jwt]
enabled = true
header_name = x-goog-iap-jwt-assertion
jwk_set_url = https://www.gstatic.com/iap/verify/public_key-jwk
email_claim = email
```

**Comment by jkreileder** [comment]
@rjmoseley Yea, I've seen the same problem on a short test with the commit cherry-picked into v7.5.x.
Also, "logout" is kind of useless unless you set GF_AUTH_SIGNOUT_REDIRECT_URL (which you probably should in most cases in order to enable single-sign-out). 

My config with traefik, oauth2-proxy, and keycloak:
```
      GF_AUTH_JWT_ENABLED: "true"
      GF_AUTH_JWT_HEADER_NAME: "X-Auth-Request-Access-Token"
      GF_AUTH_JWT_USERNAME_CLAIM: "preferred_username"
      GF_AUTH_JWT_EMAIL_CLAIM: "email"
      GF_AUTH_JWT_JWK_SET_URL: "https://keycloak.foo/auth/realms/bar/protocol/openid-connect/certs"
      GF_AUTH_JWT_CACHE_TTL: "60m"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://oauth.foo/oauth2/sign_out?rd=https://keycloak.foo/auth/realms/bar/protocol/openid-connect/logout?redirect_uri=https://some.site/"
```

**Comment by bgardner-noggin** [comment]
For those waiting for this for AWS ALB support, prepare to be disappointed.

The JWT generated by the ALB

1. Is not valid JWT as the encoding includes trailing = as well as possibly - and _ - these are invalid JWT according to the spec and Grafana cannot parse them
2. The key URL is dynamic based on the JWT payload. It contains a 'kid' parameter in the header, and the key needs to be retrieved from https://public-keys.auth.elb.region.amazonaws.com/key-id

If anyone finds workarounds for these problems, please update this issue.

**Comment by gillg** [comment]
> For those waiting for this for AWS ALB support, prepare to be disappointed.
> 
> The JWT generated by the ALB
> 
> 1. Is not valid JWT as the encoding includes trailing = as well as possibly - and _ - these are invalid JWT according to the spec and Grafana cannot parse them
> 2. The key URL is dynamic based on the JWT payload. It contains a 'kid' parameter in the header, and the key needs to be retrieved from https://public-keys.auth.elb.**_region_**.amazonaws.com/**_kid_**
> 
> If anyone finds workarounds for these problems, please update this issue.

I'm trying to setup grafana behind a load balancer and I face (probably ?) the same issues.
The JWT token is sent to Grafana, but Grafana seems not use it... My biggest problem will be for now the lack of `allow_sign_up ` as @rjmoseley said.

But ! To discuss your last point about signature keys it seems not a problem. The well known endpoint https://xxxxxx.us-west-2.amazonaws.com/xxxxxxxxx/.well-known/openid-configuration (`[iss]/.well-known/openid-configuration`) give the jwks_uri
https://xxxxxx.us-west-2.amazonaws.com/xxxxxxxxx/.well-known/jwks.json and this endpoint give the keys indexed by kid. So Grafana should be able to validate the JWT signature.

**Comment by bgardner-noggin** [comment]
I tried the jwks.json approach but my keys didn't match. Regardless, Grafana wouldn't understand the non standard JWT anyway.

However, I've successfully gotten it to work using Cognito's OAuth2 functionality.

These are my grafana.ini environment override values

                  - Name: GF_AUTH_GENERIC_OAUTH_ENABLED
                    Value: 'true'
                  - Name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
                    Value: 'true'
                  - Name: GF_AUTH_GENERIC_OAUTH_NAME
                    Value: <Label to present to end user on the Grafana login screen>'
                  - Name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                    Value: !Ref UserPoolClient
                  - Name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                    Value: !GetAtt UserPoolInfo.ClientSecret
                  - Name: GF_AUTH_GENERIC_OAUTH_SCOPES
                    Value: 'openid profile email'
                  - Name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
                    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize'
                  - Name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
                    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/oauth2/token'
                  - Name: GF_AUTH_GENERIC_OAUTH_API_URL
                    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/oauth2/userInfo'

And the callback URL in the cognito user pool client is set to https://<grafana public domain>/login/generic_oauth. Note that in this cloudformation snippet above, I had to build a custom resource to extract the ClientSecret from the AWS::Cognito::UserPoolClient resource as CloudFormation does not provide a way to get to this natively.

This is all working for me now, and I'm investigating the https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping section now.

**Comment by TBOU** [comment]
When using OAuth authentication, it is possible to forward the OAuth access token to backend proxied datasources.
This is activated by setting the "oauthPassThru" key to true in the JSON data of the datasource configuration.

Would it be possible to have a similar functionality with this new JWT authentication ?
For the request sent through the Grafana data source proxy, it would set the "Authorization" header with the JWT token (bearer type).


Currently, in ds_proxy.go :

	if oauthtoken.IsOAuthPassThruEnabled(proxy.ds) {
		if token := oauthtoken.@(proxy.ctx.Req.Context(), proxy.ctx.SignedInUser); token != nil {
			req.Header.Set("Authorization", fmt.Sprintf("%s %s", token.Type(), token.AccessToken))
		}
	}

**Comment by gillg** [comment]
> However, I've successfully gotten it to work using Cognito's OAuth2 functionality.

I did the same, but it's not really satisfying. On this case you expose grafana on internet and you don't fully delegate the authentication to cognito with your load balancer.

**Comment by sakjur** [comment]
:eyes: I'll close this feature request, because the feature requested here is implemented. To my eyes it seems like there might be a few additional surrounding features and possible bugs you're discussing right now, it'd be nice if we could get all of these issues reported separately so that we can discuss and work on them in isolation.

To answer a question of when this will appear in Grafana: This feature will make its way into 8.0, we accidentally released the docs a little early and without a clear version indicator. Whoops 🙈

The discussion here is really interesting, and I'd suggest opening separate issues for at least the following four things I've found browsing:

- Cleaning up JWTs that doesn't strictly follow the standard but are used by a popular provider (stripping =s).
- Signing up users auotmatically when authenticated with valid JWTs.
- Validation URLs dynamic to the payload (I'm not a massive fan of this one, I see the utility, but I'm also not overeager to allow dynamic content from something unverified be part of a validation chain 😅 ).
- Passthrough credentials to backend data sources (before opening that issue, try out forwarding the JWT header using #17846, and then if that's not sufficient, let us know why that is)

Feel free to ping me when opening issues, I'll be away until next Monday so don't expect any response from me until then, but I'm interested in these features and often read things posted about them even if I'm not always joining the conversation.

(cc @ryantxu)

**Comment by towolf** [comment]
> Had a play with a build from master and this seems to work with Google's IAP. I have however hit a problem in that I don't seem to be able to find a way of automatically creating a user when a new one connects via an IAP 

>Therefore all users need to be pre-populated in the db before JWT authentication is enabled, a bit of a show stopper for our usecase

> Interested to hear if anyone else is seeing the same or if I've missed anything? Would be great if we could get this figured out in time to be included in the initial jwt auth release. For reference the config I've used is below.


I figured it out, I needed both `auth.jwt` and `auth.proxy` blocks to make the transparent account creation work:

```ini
[auth.jwt]
enabled = true
header_name = x-goog-iap-jwt-assertion
jwk_set_url = https://www.gstatic.com/iap/verify/public_key-jwk
email_claim = email

[auth.proxy]
enabled = true
header_name = X-Goog-Authenticated-User-Email
header_property = email
auto_sign_up = true
```

**Comment by jkreileder** [comment]
@towolf I've rewritten larges parts of the JWT code for https://github.com/empolis/grafana
The main user-visible changes are enhanced account creation/updating.  A typical configuration might look like:

```
    [auth]
    disable_login_form = true
    signout_redirect_url = ...
    
    [auth.jwt]
    enabled = true
    header_name = X-Auth-Request-Access-Token
    username_claim = preferred_username
    email_claim = email
    name_claim = name
    role_attribute_path = resource_access."oauth2-proxy".roles && (contains(resource_access."oauth2-proxy".roles[*], 'grafana-admin') && 'Admin' || contains(resource_access."oauth2-proxy".roles[*], 'grafana-editor') && 'Editor') || 'Viewer'
    groups_attribute_path = groups.*.name
    jwk_set_url = ...
    cache_ttl = 60m
```

`role_attribute_path` gives users a Grafana role. `groups_attribute_path` maps users to Grafana organizations.
Would be great if anybody could try this before I open a PR.

**Comment by LukeHandle** [comment]
> I figured it out, I needed both `auth.jwt` and `auth.proxy` blocks to make the transparent account creation work:
> 
> ```ini
> [auth.jwt]
> enabled = true
> header_name = x-goog-iap-jwt-assertion
> jwk_set_url = https://www.gstatic.com/iap/verify/public_key-jwk
> email_claim = email
> 
> [auth.proxy]
> enabled = true
> header_name = X-Goog-Authenticated-User-Email
> header_property = email
> auto_sign_up = true
> ```

@jkreileder, this doesn't seem to verify the JWT is present(/valid). Instead, I'd guess these 2 auth configs are _maybe_ interpreted as an OR.

eg. If the request contains a `X-Goog-Authenticated-User-Email` header, they are logged in, regardless of the the JWT settings.

**Comment by towolf** [comment]
@LukeHandle that's probably true, however my main concern was not authentication, but rather the transparent user creation. In my case the IAP proxy is already doing auth for me.

So I look forward to a possible PR from @jkreileder .

**Comment by csms** [comment]
I don't understand how the current implementation matches it's use case (provide a more secure alternative to auth.proxy where the received credentials are validated). 
How could jwt.auth satisfy the use case without auto_sign_up functionality? 

To me it seems implausible and unrealistic to pre-populate with accounts provided by an external identity provider (where most likely authorization is provided by some sort of group membership/roles etc).

Or am I missing something obvious? Really looking forward to the pull request :-).

**Comment by abh** [comment]
@jkreileder The groups_attribute_path functionality you suggested would be great.

**Comment by qassandrach** [comment]
> @jkreileder The groups_attribute_path functionality you suggested would be great.
is this configuration already working in auth jwt configuration? I tried to use this to mapping teams from jwt payload but it's not working
