### ISSUE TITLE
Tempo: Streaming search does not pass `X-Scope-OrgID` header

### ISSUE THREAD

**Issue by thomaspurchas** [grafana/grafana#81998]
### What happened?

Trying to perform trace searches using Grafana with a Tempo datasource, with both multi-tenancy and streaming searches turned on. Result is a query error say `no org id`.

<img width="465" alt="image" src="https://github.com/grafana/grafana/assets/782311/8653b87a-8d29-4f53-b9ba-ac161983578c">

### What did you expect to happen?

Streaming searches to work.

### Did this work before?

Streaming searches worked before turning on Multi tenancy in Tempo. Disabling streaming searches or Multi tenancy fixes search errors.

### How do we reproduce it?

1. Install Grafana 10.3 and latest Tempo
2. Turn on `traceQLStreaming` feature toggle
3. Turn on Multitenancy in Tempo
4. Connect Grafana to Temp, and add `x-scope-orgid` header in Tempo datasource
5. Try to perform a trace _Search_ (not a traceID lookup)
6. Notice that `no org id` error is returned.

### Environment (with versions)?

Grafana: 10.3
OS: Mac OS
Browser: Chrome and Safari

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by williamfeng323** [comment]
I also encounter this issue. The custom header does not work at all. Grafana version 9.5.2

**Comment by joey-grafana** [comment]
Hello, this should be fixed 10.4. If you run into any issues in 10.4 please let us know.

**Comment by thomaspurchas** [comment]
For those wondering, this appears the PR that fixes this issue [#81693](https://github.com/grafana/grafana/pull/81693)
