### ISSUE TITLE
[Feature request] Way to link to a row/panel from another dashboard

### ISSUE THREAD

**Issue by mathieulongtin** [grafana/grafana#8200]
It would be nice if I could, from a dashboard, add a panel or row from another dashboard.

For example: 
- I make a dashboard to monitor some job
- In that dashboard, it would be interesting to have the CPU panel for the server involved
- I already have that CPU panel elsewhere
- Instead of copying the JSON, I click "add panel from another dashboard", then it allows me to select the panel.

In the future, somebody else fixes something in the CPU panel in the source dashboard. That modification is reflected in my dashboard as well.

Bonus: if I ever want to modify the CPU panel in my dashboard, I have an option to "copy it" and break the link.

**Comment by daniellee** [comment]
dupe #1803
