### ISSUE TITLE
[Bug] Unable to save dynamically created templating variables

### ISSUE THREAD

**Issue by Lillfilly** [grafana/grafana#8201]
- What Grafana version are you using?
2.4.0
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Linux mint 18.1
- What did you do?
1. Dynamically added a custom templating variable through addVariable(model) which is defined here:  grafana/public/app/features/templating/variable_srv.ts
2. Tried to save dashboard by clicking the icon in the top bar of the UI.

- What was the expected result?
Dashboard is saved with the template variable set

- What happened instead?
Browser console complaining about cyclic data structure error.

I believe the addVariable function contains a bug.
```
addVariable(model) {
    var variable = this.createVariableFromModel(model);
    this.variables.push(this.createVariableFromModel(variable));
    return variable;
}
```

Maybe it should do `this.variables.push(variable)` instead of `this.variables.push(this.createVariableFromModel(variable));`

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/d085aaad417cf1df722773596a4ef175255b5f9f
