### ISSUE TITLE
[Bug] Metrics missing when using longer timeframe - InfluxDB source

### ISSUE THREAD

**Issue by DanHoerst** [grafana/grafana#8202]
**- What Grafana version are you using?**
Grafana v4.2.0 (commit: 349f3eb)

**- What datasource are you using?**
Influxdb Enterprise v1.2.1

**- What OS are you running grafana on?**
Ubuntu 14.04

**- What did you do?**
I have a graph with a query like so:

`SELECT sum("value") FROM "table" WHERE "region" = 'us-west-2' AND $timeFilter GROUP BY time($interval), "exchange"`

When I set `$timeFilter` to `Last 1 hour`, `Group by time interval` to `60s` and run the query - I get back 9 results:

![image](https://cloud.githubusercontent.com/assets/1361529/25342853/4d3f72b4-28db-11e7-93fc-e0350c67e766.png)

When I set `$timeFilter` to `Last 24 hours`, `Group by time interval` to `60s` and run the query - I get back 7 results:

![image](https://cloud.githubusercontent.com/assets/1361529/25342868/5c6f9dae-28db-11e7-90b5-926b5a94f092.png)

If I run the same `Last 24 hours` query but change `Group by time interval` to `1h` I get back 9 results as expected:

![image](https://cloud.githubusercontent.com/assets/1361529/25342896/6bcf1a72-28db-11e7-9dfc-897efe0a31df.png)

**- What was the expected result?**
I expect to get 9 results for all three of the queries above. I get the expected result when querying the data from InfluxDB directly.

**- What happened instead?**
The results vary when the `$timeFilter` is > 3 hours.

**- Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.**
 `query?db=proddb&q=SELECT%20sum(%value%22)%20FROM%20%22table%22%20WHERE%20%22region%22%20%3D%20%27us-west-2%27%20AND%20time%20%3E%20now()%20-%2024h%20GROUP%20BY%20time(60s)%2C%20%22exchange%22&epoch=ms`

**Comment by torkelo** [comment]
this is due to change in default value of max-row-limit In InfluxDB 1.2, think it was reverted back in InfluxDB 1.2.2 so try upgrading, or change your InfluxDB server config optikon max-row-limit (increase or set to zero for no limit). 

Please search for an issue before posting a new one, there are about 10 duplicates with this problem :)
