### ISSUE TITLE
Alerts: Graph does not display

### ISSUE THREAD

**Issue by jvenskus** [grafana/grafana#82027]
### What happened?

User created a new dashboard, Attempted to create a new alert for the dashboard. When the query was executed data was returned but the UI only shows a table view with the first data point value from the JSON data section. 

### What did you expect to happen?

User should have seen a graph of the resulting data. 

### Did this work before?

Yes prior to Grafana version 10.3.1

### How do we reproduce it?

See what happened section

### Environment (with versions)?

Grafana: 10.3.1
OS: Linux Centos 7
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?
TSDB

**Comment by tonypowa** [comment]
Hello @jvenskus 
Thank you for reporting this issue

To help us better understand and replicate the problem we’ll need a little more information.

1. What datasource are you using exactly? 

1. Can you share the JSON of the panel via the panel --> more --> get help workflow in the panel's dropdown menu?

1. Could you attach a screenshot of the UI, showing both the table view and any error messages or console outputs in the browser's developer tools?

**Comment by jvenskus** [comment]
Good Evening,

We are using OpenTSDB data source.

We can see the JSON response using developer tools. However, in the UI all we get as a response is a blank panel outline in gray and the words No Data.

As a side note we have noticed that since version 9.2 Grafana has had many UI issues when it comes to creating alerts and viewing query results when the data source being used is openTSDB.




Jonathan Venskus

Scientist



M: 240-888-3850 | ***@***.******@***.***>



ProSync Technology Group | An Employee-Owned Company

6021 University Blvd., Suite 300 | Ellicott City, MD. 21043


________________________________

**Comment by tonypowa** [comment]
Hi @jvenskus 

Thank you for your answers
However, we still would appreciate if you could copy and paste all relevant data using the panel --> more --> get help workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:
https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/
![alt text](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by jvenskus** [comment]
Good Evening,

I have attached two files, the first is a screenshot of the results we receive. We were expecting a graph of the data. The second is the JSON response we receive from Grafana.



Jonathan Venskus

Scientist



M: 240-888-3850 | ***@***.******@***.***>



ProSync Technology Group | An Employee-Owned Company

6021 University Blvd., Suite 300 | Ellicott City, MD. 21043


________________________________

**Comment by tonypowa** [comment]
@jvenskus 

I can't see any attachments 🤷

**Comment by jvenskus** [comment]
@tonypowa, 

Hmm I attached them to the email thread. Trying again by going to GitHub
![screen_shot1](https://github.com/grafana/grafana/assets/139516748/8be61a75-5995-412e-b40c-83ae6469d77f)
[10.3.1_openTSDB_alert_query.json](https://github.com/grafana/grafana/files/14564998/10.3.1_openTSDB_alert_query.json)

**Comment by jvenskus** [comment]
Uploaded files via GitHub hopefully that works


Jonathan Venskus

Scientist



M: 240-888-3850 | ***@***.******@***.***>



ProSync Technology Group | An Employee-Owned Company

6021 University Blvd., Suite 300 | Ellicott City, MD. 21043


________________________________

**Comment by tonypowa** [comment]
thank you for uploading the files

> User created a new dashboard, Attempted to create a new alert for the dashboard. When the query was executed data was returned but the UI only shows a table view with the first data point value from the JSON data section.

one last question, when creating the alert through the panel, what visualization were you using (e.g time series, etc) ?

**Comment by jvenskus** [comment]
It was a time series we tried 10 mins, last 24 hours, 1 week it did not change the result.


Jonathan Venskus

Scientist



M: 240-888-3850 | ***@***.******@***.***>



ProSync Technology Group | An Employee-Owned Company

6021 University Blvd., Suite 300 | Ellicott City, MD. 21043


________________________________

**Comment by aangelisc** [comment]
Hi @jvenskus,

Apologies for the lack of response here. I can confirm I've replicated the issue and tracked it down to #77841. We'll prioritise and investigate a fix.
