### ISSUE TITLE
Dataproxy: The timeout option default value - implementation mismatch documentation

### ISSUE THREAD

**Issue by kwarunek** [grafana/grafana#82029]
### What happened?

Documentation states (https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#timeout)

> How long the data proxy should wait before timing out. Default is 30 seconds.

But from my observations/tests and from simple look up into the code - the actual timeout is 10s.

https://github.com/grafana/grafana/blob/main/pkg/setting/setting_data_proxy.go#L15

### What did you expect to happen?

Documentation should be consistent with the implementation.

### Did this work before?

No

### How do we reproduce it?

N/A

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.3.1
OS: Linux
Browser: N/A

### Grafana platform?

Kubernetes

### Datasource(s)?

All dataproxy plugins

**Comment by GrafanaWriter** [comment]
Will be fixed when https://github.com/grafana/grafana/pull/83617 is merged.
