### ISSUE TITLE
Unable to see the change on local instance after source code 

### ISSUE THREAD

**Issue by MahekPavagadhi** [grafana/grafana#8203]
I made a change in this file 

`./public/app/plugins/panel/singlestat/editor.html`

**restarted the server** but could not see corresponding change on the grafana dashboard instance that is running on my localhost.

Not sure what file needs to be altered in order to add an attribute in 'Options' under singlestat panel

**Comment by daniellee** [comment]
You need to run grunt to build the frontend assets. Read more about building Grafana from source here: http://docs.grafana.org/project/building_from_source/

**Comment by MahekPavagadhi** [comment]
I did run grunt for building purpose then I restarted the server. Still no luck

**Comment by daniellee** [comment]
Have you followed all the steps from the Building From Source instructions? Especially this part:

```
npm install -g yarn
yarn install --pure-lockfile
npm install -g grunt-cli
grunt
```
You do not need to restart the server for frontend changes.

**Comment by MahekPavagadhi** [comment]
I followed all the steps. 

Got this at the end :

>   **Done, without errors.**

 Still the changes did not reflect on the dashboard.

Also I had a doubt, As singlestat plugin is **included** in grafana, do I need to keep it under 

 `/usr/local/var/lib/grafana/plugins` like other custom plugins? or it is okay to manipulate from the place where it is.

**Comment by MahekPavagadhi** [comment]
I made few front end changes and when I tried to build the source I am getting this error while `npm install -g grunt-cli`

I upgraded node and npm (it that matters)

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! path /usr/local/lib/node_modules/grunt-cli/README.md
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/grunt-cli/README.md'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/grunt-cli/README.md']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/grunt-cli/README.md' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/grunt-cli/CHANGELOG.md'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/grunt-cli/CHANGELOG.md']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/grunt-cli/CHANGELOG.md' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/####/Grafana/src/github.com/grafana/grafana/npm-debug.log
```

**Comment by MahekPavagadhi** [comment]
While doing:

**$ yarn install --pure-lockfile**

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/yarn/node_modules/escape-string-regexp/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/chalk/index.js:2:26)
    at Module._compile (module.js:409:26)
```

**Comment by torkelo** [comment]
try sudo it,

**Comment by MahekPavagadhi** [comment]
I manipulated grafana.dark.min.css file on local. Everytime I build the source, the changes that I made are reverting back to the original one. 

@torkelo

**Comment by bulletfactory** [comment]
Perhaps the issue is the css files are the compiled styles. You need to change the **scss** files.

**Comment by MahekPavagadhi** [comment]
@bulletfactory Not working. Even scss file is reverting back. Can you point me out the path of scss file that I can modify? instead of grafana.dark.min.css?

**Comment by bulletfactory** [comment]
Sure - should be in your public/sass directory.
