### ISSUE TITLE
Alert Rule: Search by Label results in an error in browser webconsole

### ISSUE THREAD

**Issue by psteinmetzcid** [grafana/grafana#82044]
### What happened?

After Update Grafana to 10.3 we regconized, that filter alert rules by labels don't work.
As soon as a filter typed in the field, we get an error in the web console.

![screen_record_alertrule_filter_issue](https://github.com/grafana/grafana/assets/132431614/e069c340-963f-46b4-bddc-731e56afc1d3)

### What did you expect to happen?

That the Rules will filtered.

### Did this work before?

According to our colleagues, it worked in the previous version 10.2.

### How do we reproduce it?

1. Alert Rules
2. View a single Alert Rule
3. open web console in browser
4. type in a filter

### Environment (with versions)?

Grafana: 10.3.1
OS:  Microsoft Windows Server 2019 Datacenter - 10.0.17763 N/A Build 17763
Browser: Google Chrome Version 121.0.6167.140 (Official Build) (64-bit) / Firefox 121.0.1

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
Hi  @psteinmetzcid 

Thank you for reporting this issue

I'm forwarding this issue to the Alerting team for review

**Comment by konrad147** [comment]
I confirm this is a bug. Thanks for reporting!
