### ISSUE TITLE
[Feat Req] Provide official 32bit builds/packages

### ISSUE THREAD

**Issue by Techwolfy** [grafana/grafana#8205]
I'd like to use Grafana, but my environment has a mix of 32-bit and 64-bit servers. Unfortunately, I can't upgrade at this time, and I can't use software that isn't compatible with every node.

I tried to build Grafana from source, but was unable to on Debian Stable, and packages failed to generate on Ubuntu (I don't use Go or NodeJS so my build environment may be odd, but it didn't throw any errors). The provided package works great, but only for 64-bit hosts.

A cross-platform package for a previous version of Grafana is already in the [Debian unstable repository](https://packages.debian.org/sid/grafana). Would it be possible to update it? A version in backports would be great, but an i386 package in the current repository is all I really need to start using it.

I'm willing to help with package publication if necessary, but I'm not a Debian package maintainer so it would take a while (and official approval) to get access.

**Comment by bobemoe** [comment]
I'm also looking for this.  Unfortunately the link above is now 404.  The bulding from source link over at https://github.com/grafana/grafana/issues/1968 is also broken, and I cant even find the source when following link on https://grafana.com/docs/grafana/latest/installation/debian/ for Install from binary .tar.gz file https://grafana.com/grafana/download?platform=linux

**Comment by bobemoe** [comment]
OK, I finally found the latest build guide: https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md

Problem is nodejs no longer supports i386 :( https://github.com/nodejs/help/issues/1384

I've given up trying to get this to work.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
