### ISSUE TITLE
[Feature request] (cloudwatch) new templating function which use GetResources()

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8207]
I think this is useful for RDS/ElastiCacher user.

The GetResources() API can filter resource by tags.
http://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html
By using this API, we can get ARN of resource which has `Enviroment=production` tag.

The templating function might becomes like following.
```
arn_filter_by_tag(region, resource_type, tags)
```

**Comment by chrisferry** [comment]
👍 Would love to be able to use tags to build the graphs.  When we relaunch an ALB we have to rebuild the graphs with the new TargetGroup IDs.  We should be able to query based on Tag

**Comment by tyvich** [comment]
#13643 Similar request to support filtering dimension values based upon tags

**Comment by tyvich** [comment]
Would this be more reasonable to accomplish with the release of more robust tagging search API by amazon (No longer have to go to each service to get ARNs)?

**GetResources API**: https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html

**YACE** Also, noticed that a cloudwatch prometheus exporting project has implemented discovery for a variety of the core aws services (ec2, alb, rds,etc...)
https://github.com/ivx/yet-another-cloudwatch-exporter

Would be a major win for our team to not have to update our dashboards on each deploy

**Comment by jeroenvollenbrock** [comment]
Ran into the same problem and gave it a shot (#14803).
