### ISSUE TITLE
Global Grafana using multiple Grafana's

### ISSUE THREAD

**Issue by bsikander** [grafana/grafana#8209]
I have multiple Grafana's configured for different environment. Each Grafana is using basic authentication. On the backend I am using InfluxDB and it does not have public IP. Only Grafana's have public IP.

Now, I would like to see a global view without accessing InfluxDB. A global Grafana which shows the status of each environment. In other words, I would like to embed a few panels from each individual Grafana into my global Grafana.

Is this usecase supported ? Or somehow can I do it?

My OS: ubuntu
Grafana: 3.x.x

P.S. I tried the community page but somehow it is not working.

**Comment by torkelo** [comment]
In your public Grafana add multiple data sources for each of your InfluxDB servers

**Comment by bsikander** [comment]
As mentioned, my InfluxDB datasources are not accessible outside and I don't want to expose them. 
I want to embed the panels from child grafana's into the parent grafana.

I was doing some experimentation and found out that in the child grafana, I can generate the iframe embed code and I can use this code inside a Text Panel in parent grafana. This works without basic authentication. 

With basic authentication it shows me the login page. Here is my html inside the Text Panel

```
<html>
<body>
<iframe src="http://user:pass@ip:3000/dashboard-solo/db/dashboard?panelId=1" width="600" height="400" frameborder="0"></iframe>
</body>
</html> 
```

How can I avoid the login page ?
