### ISSUE TITLE
Add the possibility to apply different timeshifts on the same visualization

### ISSUE THREAD

**Issue by Animarc** [grafana/grafana#82093]
**Why is this needed**:

Currently, there is no way to compare data values on different dates within the same visualization, as the timeshift is configured once and applies to all queries in the visualization.

**What would you like to be added**:

To be able to specify query options for each query in the visualization for all datasources or atleast when you select "Mixed"

**Who is this feature for?**

All types of users, as this will enhance data insights into how your data is modeling compared to other weeks.

**Comment by Inbloo** [comment]
+1

**Comment by Monicafgz** [comment]
+1

**Comment by gabor** [comment]
(i assigned this to the dashboard-squad, but not sure if that's the right home for the issue.  feel free to reassign it. thanks!)

**Comment by leoswing** [comment]
Hi, anyone who wants to use the timeShifts ability, could use the [compareQueries-datasource-rc](https://github.com/leoswing/autohome-compareQueries-datasource-rc) plugin,  tag 1.1.0 has the ability to make timeShifts.

@Animarc  Hi, you can use the release tags as below:

[Release Tag detaisl](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.1.0)
