### ISSUE TITLE
[Feature request] Documentation update for the function: "dashboard from JSON file"

### ISSUE THREAD

**Issue by it-praktyk** [grafana/grafana#8210]
On the [documentation page](http://docs.grafana.org/http_api/dashboard/#dashboard-from-json-file) is mentioned that it's possible (?) to import Grafana dashboard from a file.

Could you update documentation and include an example in it?

The functionality is implemented 
1. [/pkg/api/api.go](https://github.com/grafana/grafana/blob/456b07b766b8e1e31a39f25c58855ba742e1bfc7/pkg/api/api.go#L227)
2. [/pkg/api/dashboard.go](https://github.com/grafana/grafana/blob/22bf6420f13176ab2a5caea40c6efbc7fefc04e9/pkg/api/dashboard.go#L242-L267)

Thank you.

**Comment by torkelo** [comment]
Here is the api docs for saving / updating dashboards
http://docs.grafana.org/http_api/dashboard/#dashboard-api

**Comment by it-praktyk** [comment]
@torkelo, did you check the section about update what I requested?

![grafana_http_api](https://cloud.githubusercontent.com/assets/4910261/25389916/ca77899e-29c9-11e7-8714-4d910bb0b3b4.jpg)

Does it look like documented?

**Comment by torkelo** [comment]
sorry that should not be in the docs, (and is not related to importing dashboard from file). 

Use the normal json api that I linked to to import a dashboard. or use wizzy https://github.com/utkarshcmu/wizzy

**Comment by it-praktyk** [comment]
OK, thx for an explanation. Please reopen the issue to remember about removing it from the webpage.

It's look that [source of webpage](https://github.com/grafana/grafana/blob/master/docs/sources/http_api/dashboard.md) is updated now.
