### ISSUE TITLE
InfluxDB data source 405 error with SQL Query Language

### ISSUE THREAD

**Issue by twillhorn** [grafana/grafana#82120]
### What happened?

When attempting "Save & Test" I get this error:

ERROR: flightsql: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); transport: received unexpected content-type "text/html"

I am following the instructions here:
https://docs.influxdata.com/influxdb/cloud-serverless/process-data/visualize/grafana/

and here:
https://www.influxdata.com/blog/official-influxdb-v3-data-source-grafana-released/

### What did you expect to happen?

A successful connection

### Did this work before?

No

### How do we reproduce it?

1. Create an InfluxDB using the tutorial e.g. <influx home>/new-user-setup/python
2. Follow the instructions https://www.influxdata.com/blog/official-influxdb-v3-data-source-grafana-released/

### Environment (with versions)?

Grafana: v10.4.0-65875 (b758b91e84)
OS: Mac
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by danielvoelk** [comment]
I have the same issue

**Comment by keynode** [comment]
Same issue,
Following doc instructions:

ERROR: flightsql: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); transport: received unexpected content-type "text/html"

**Comment by danielvoelk** [comment]
I fixed it by changing the HTTP from USA to Europe. It showed up as Europe for me, but it was actually the USA url.

**Comment by yosiasz** [comment]
Are you installing locally or on the cloud?

**Comment by tonypowa** [comment]
hello @twillhorn 

thank you for reaching out 

is the issue still occurring? 
is it on prem or cloud?
could you provide the settings in the configuration of the InfluxDB datasource within Grafana?

**Comment by twillhorn** [comment]
My Grafana trial expired so I cannot try to reproduce

**Comment by tonypowa** [comment]
thank you for the reply @twillhorn 
In that case let's close the issue
If you encounter the same problem again, please add a comment and we will reopen

**Comment by skilledboy** [comment]
Hi, I have the same issue
ERROR: flightsql: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); transport: received unexpected content-type "text/html"
<img width="1187" alt="image" src="https://github.com/grafana/grafana/assets/20128372/a07ffbee-d8f9-4cc2-a84b-4ae4159db8e1">

**Comment by aangelisc** [comment]
Hi all,

I'm going to close this issue as we've been unable to reproduce it. If it reoccurs then please re-open!

**Comment by bortolin** [comment]
I have the same error when try connect to InfluxDb Cloud (https://westeurope-1.azure.cloud2.influxdata.com/)

<img width="1441" height="221" alt="Image" src="https://github.com/user-attachments/assets/29174125-1da6-40df-9cab-2b7f67f722cb" />
