### ISSUE TITLE
[Bug] Coloring thresholds 

### ISSUE THREAD

**Issue by diegokamiha** [grafana/grafana#8213]
- What Grafana version are you using?
4.1.2-1486989747
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Amazon Linux 
- What did you do?
I created a repeated panel with singlestats (with the same threshold configuration). However, panels have different colors, even when they have the same value.

![screen shot 2017-04-25 at 4 01 55 pm](https://cloud.githubusercontent.com/assets/6676458/25403825/10dd13c2-29d4-11e7-8226-a88464361c8c.png)
![screen shot 2017-04-25 at 4 02 13 pm](https://cloud.githubusercontent.com/assets/6676458/25403826/10e384b4-29d4-11e7-85d1-f9131d3c1145.png)
![screen shot 2017-04-25 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/6676458/25403827/10e4336e-29d4-11e7-9a3b-08487b6b16bc.png)

- What was the expected result?
Both panels with the same color (in this case, red)

- What happened instead?
Value's color is different between panels.

**Comment by torkelo** [comment]
can you change decimals to 2? Maybe the value looks the same but the unrounded value is different?

**Comment by torkelo** [comment]
think we fixed so that the threshold is evaluated before rounding 
https://github.com/grafana/grafana/pull/8334
