### ISSUE TITLE
Elasticseach No timestamp field

### ISSUE THREAD

**Issue by SnchitGrover** [grafana/grafana#8215]
I have a index in elastic seach. 
```
{
 "settings" : {
  "number_of_shards" : 1,
  "number_of_replicas" : 0
 },
 "mappings" : {
  "_default_" : {
   "properties" : {
    "reporting_date" : {"type": "string", "index" : "not_analyzed" },
    "user_type" : {"type": "string", "index" : "not_analyzed" },
    "paid_free" : {"type": "string", "index" : "not_analyzed" },
    "published" : {"type": "string", "index" : "not_analyzed" },
    "count" : {"type": "integer", "index" : "not_analyzed" }
   }
  }
 }
}
```

My reporting_date field has data like '2016-10-11' (date data but in yyyy-mm-dd format)

In Grafana I added a new data source for elasticseach.

<img width="709" alt="screen shot 2017-04-26 at 11 00 18 am" src="https://cloud.githubusercontent.com/assets/22751886/25419352/b19153aa-2a6f-11e7-925f-6b993fab89a1.png">

In Grafana when I try to add a graph with this index. I get the following error:

```
{
    "root_cause": [
        {
            "type": "illegal_argument_exception",
            "reason": "Field [reporting_date] of type [keyword] does not support custom formats"
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query_fetch",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "musemau",
            "node": "3RpG77jhSnKgTFBlmiC4jg",
            "reason": {
                "type": "illegal_argument_exception",
                "reason": "Field [reporting_date] of type [keyword] does not support custom formats"
            }
        }
    ],
    "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Field [reporting_date] of type [keyword] does not support custom formats"
    }
}
```

In the graph my configuration looks like below
<img width="1428" alt="screen shot 2017-04-26 at 11 11 19 am" src="https://cloud.githubusercontent.com/assets/22751886/25419609/480a7220-2a71-11e7-9c4d-91275a01f236.png">
<img width="1426" alt="screen shot 2017-04-26 at 11 11 32 am" src="https://cloud.githubusercontent.com/assets/22751886/25419636/7bc91daa-2a71-11e7-8096-eec0a96e7b37.png">

I can't see the graph showing any data. What am I doing wrong?

**Comment by torkelo** [comment]
you need to update your index mapping so "reporting_date" is mapped as date type 

"reporting_date" : {"type": "string", "index" : "not_analyzed" },
