### ISSUE TITLE
Dashboards: Query template variable breaks when there's no results in the last 7-8 hours

### ISSUE THREAD

**Issue by tbalzer** [grafana/grafana#82154]
### What happened?

We have dashboards using a Loki datasource that filters for namespace, pod, etc via template variables (using label_values queries).

After updating to 10.2.3 (from 10.1.5) we have the issue that dashboards don't load anymore if a namespace is selected that did not have logs within the last 7-8 hours.

The error is `runRequest.ts:159 runRequest.catchError TypeError: Cannot read properties of undefined (reading 'map')` (in the console logs) and e.g. `Templating [pod] Error updating options: Cannot read properties of undefined (reading 'map')` in the UI.

It happens both when displaying the dashboard with such a namespace selected and also when editing variables. The variables are set to update when the timeframe changes, however they don't work even when the timeframe selected includes data (e.g. in our case 'last 2 days' contains data). It works once we select timeframes like 'last 14 days' which then shows data in the dashboard, but still doesn't allow editing the variables where the error still shows.

### What did you expect to happen?

* Even when there currently is no data to evaluate variable values it should just be an empty list and not lead to errors
* Variable values should be properly evaluated based on the selected timeframe if so configured

### Did this work before?

It worked in version 10.1.5

### How do we reproduce it?

Minimal reproduction for the variable editing case (that should at least not lead to errors imo):
1. Create dashboard with Loki datasource
2. Add variable with Loki datasource, query "Label values", label "namespace"
3. Observe this works fine
4. Edit variable to add a stream selector like e.g. `{namespace="nonexisting"}` which leads to no data
5. Observe the templating error message

### Environment (with versions)?

Grafana: 10.2.3
OS: Linux
Browser: Chrome Version 121.0.6167.85

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
Hello @tbalzer 
Thank you for providing detailed information about the issue

Could you provide the exact query you are using for the Loki datasource in the variable configuration?

Are there any specific logs related to the error from the Grafana server logs that might give more insight into the issue?

Does the error occur with all namespaces that lack data in the specified timeframe, or is it limited to specific ones?

Thank you

**Comment by tbalzer** [comment]
Hi @tonypowa ,

This is an example of how our variables are defined:

![image](https://github.com/grafana/grafana/assets/7325777/d0458878-1358-44ee-a36d-fab0ae77d7cd)

Our namespace variable in this case is just a fixed list of namespaces. The issue occurs if the other labels return an empty list because for a specified namespace no data is available.

No logs in the grafana server that relate to this, just the normal background noise of the update-checker and unrelated messages (they refer to specific user queries that timeout, not in the timeframe we observe this error).

In the browser console we see this stacktrace:
```
runRequest.ts:159 runRequest.catchError TypeError: Cannot read properties of undefined (reading 'map')
    at Pr.processMetricFindQuery (datasource.ts:688:34)
    at async Pr.metricFindQuery (datasource.ts:664:14)
TypeError: Cannot read properties of undefined (reading 'map')
    at Pr.processMetricFindQuery (datasource.ts:688:34)
    at async Pr.metricFindQuery (datasource.ts:664:14)
reportUnhandledError.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Pr.processMetricFindQuery (datasource.ts:688:34)
    at async Pr.metricFindQuery (datasource.ts:664:14) 
```

We only have this one specific namespace that actually doesn't consistently produce data, but selecting a nonexisting namespace (or replacing in the screenshot above the stream selector with `{namespace="nonexisting"}` will lead to the same result.

**Comment by tonypowa** [comment]
thanks for the details @tbalzer 
a member from the team will get back to you

**Comment by svennergr** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/81077/
