### ISSUE TITLE
division of two values in Grafana to get percentage

### ISSUE THREAD

**Issue by alirezastack** [grafana/grafana#8216]
I have configured icinga2 to fetch memory current value and memory max value based on hosts. For now I have both in a table panel. I have used influxDB to store metrics.

![screen shot 2017-04-26 at 11 23 46 am](https://cloud.githubusercontent.com/assets/6417083/25421605/ef0b0804-2a72-11e7-8425-c6b95c8c06b5.png)

The question is that is there a way to get percentage of memory used based on hosts?

(mem_value/mem_max) * 100

I want to implement this function in grafana. Is there any query like that in grafana? It is missing in grafana?

**Comment by torkelo** [comment]
this is up to Icinga to support. All metric transformations are the  responsibility of the time series database. For example graphite as divideSeries and asPercent, subtract functions that operate on series. 

at some point we want to support native time series transforms in Grafana via this feature: https://github.com/grafana/grafana/issues/3677 but it is in the future :)

**Comment by JessieZhao777** [comment]
Has this feature been added yet?
