### ISSUE TITLE
[Feature request] Import json files to grafana 

### ISSUE THREAD

**Issue by bgadmin** [grafana/grafana#8217]
Hello is it possible to import exported json files into grafan by putting them into some folder or does it still need to be done through API?

If not possible it would be really good feature to just copy *.json files and then grafana process it and stores into its database.

Grafana version: Version 4.2.0 (commit: 349f3eb93)

**Comment by torkelo** [comment]
it still needs to be done through the api. 

We hope to improve & have built in support to sync file based dashboards to & from the Grafana db.  But  until then we recommend: https://github.com/utkarshcmu/wizzy
