### ISSUE TITLE
UX: Heatmap panel icon

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8220]
A custom panel icon for the new heatmap panel would be nice: 

Inspiration:
![heatmap](https://cloud.githubusercontent.com/assets/10999/25435231/a536f6c6-2a8f-11e7-9422-0847da2b6c15.png)

**Comment by bulletfactory** [comment]
here's a preview of the new icon:
![heatmap_test](https://cloud.githubusercontent.com/assets/1950595/25634246/e687dc14-2f47-11e7-9dbf-2ea63b91c602.png)
