### ISSUE TITLE
Tempo: Streaming does not work when visiting a direct link

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#82206]
If you share a link to a Tempo explore page with streaming enabled the progress bar and intermediate results are not displayed.

Steps to repro:
1) Visit a Tempo explore page with streaming enabled.
2) Execute a query and see the glorious progress bar.
3) Copy the url and open a new window with it. Note that the progress bar/results are not displayed.

**Comment by ifrost** [comment]
Fixed by https://github.com/grafana/grafana/pull/93033
