### ISSUE TITLE
Tooltip: Sorting is broken

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#82210]
It was reported that the next generation tooltips have a bug where the sorting feature is broken (both for asc + desc)

**Comment by zyxep** [comment]
Hi,

I see it on time series panel, i am currently trying to get debug panel but i can't randomize the data.

**Comment by zyxep** [comment]
![Screenshot 2024-02-09 at 7 47 49 AM](https://github.com/grafana/grafana/assets/1403731/c61dd032-db84-4569-ab18-96de57c63a26)
this is a panel where the new tooltip is disabled, clearly sorted :)

**Comment by zyxep** [comment]
So, this is so weird.
![Screenshot 2024-02-09 at 7 55 30 AM](https://github.com/grafana/grafana/assets/1403731/45ee3294-b10c-4407-9877-eaa6dc572ef5)
This panel is set to Desc tool tip and it's clear not desc as the previous picture shows. (same panel).
But! there is the kicker.

The above picture (the one working) there is the `Panel options` in the dashboard set to `Shared crosshair` where when I set it to `Default` then it's not sorting.

+ in the mode `Default` the font is also different.

Here are the settings ![Screenshot 2024-02-09 at 7 58 10 AM](https://github.com/grafana/grafana/assets/1403731/65be6b9c-d174-484d-97a2-77dbc7b85252)

**Comment by leeoniya** [comment]
newVizToolstips still has unresolved issues with z-index and positioning when using Shared tooltips, so we currently dont enable them in that case, thats why they're different :)

im working to get that fixed in https://github.com/grafana/grafana/pull/81986
