### ISSUE TITLE
Public Dashboard permissions for non-administrator users

### ISSUE THREAD

**Issue by l-hah** [grafana/grafana#82235]
**Why is this needed**:

For Editors to be able to set dashboards public.  

**What would you like to be added**:

The ability to give certain users, or users with the role of Editor the ability to set a dashboard public.  

**Who is this feature for?**

Editors and Administrators. At the moment it is difficult to handle, as the administrator constantly needs to be contacted in order to set a single dashboard to public. It would be great if either editors had the permission to create public dashboards, or users could be assigned with the permission to publicise dashboards.

**Comment by evictorero** [comment]
We already have a specific [permission](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/custom-role-actions-scopes/), `dashboards.public:write,` to give users the ability to create and update a public dashboard.
