### ISSUE TITLE
Prometheus: Timeseries step changes in different views

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82276]
### What happened?

Refreshing the edit window of a prometheus pane may change the step of the query, making the time series chart look different.

### What did you expect to happen?

The interval that is valid for the dashboard is kept in the edit window, and persists on a refresh. 

### Did this work before?

Not sure.

### How do we reproduce it?

1. Go to [this play dashboard](https://play.grafana.org/d/4XuMd2Iiz/kubernetes-eks-cluster-prometheus?orgId=1&var-datasource=&var-node=All&var-account=&var-namespace=usman-sandbox&var-namespace=kube-system&var-namespace=play-backends&from=now-6h&to=now)
1. Note the "Cluster Pod Capacity" panel. From the network tab, see query is ran on the dashboard with step being `1m0s`
2. Open the kebob menu, and click Edit. The query is not not re-ran in the edit window. See the interval is `1m` on the query editor
4. Hit refresh. The interval is set to 20s, and the query is ran with a `20s` step

### Environment (with versions)?

Grafana: Grafana v10.4.0-65039 and Grafana v10.4.0-66819
OS: OSX
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

Prometheus

**Comment by itsmylife** [comment]
Interval is calculated as `Time range / Max data points`. And `Max data points` are tied to the width of the panel. 
When the panel width is changed it changes. So the change is normal. But I think it should have happened when we entered the edit view. @grafana/dashboards-squad owns the `Query options` panel. I am assigning this to them.

**Comment by Sergej-Vlasov** [comment]
From my investigation it seems like a default correct behaviour that has been there for a while now. As @itsmylife mentioned `Max data points` is calculated based on width of the panel and going into edit mode will likely change that.  You can preserve the interval by either entering `Max Data Points` value (placeholder will show the value you had in the panel) or copying value from `Interval` field into `Min interval`. Hope these workarounds are sufficient! Closing the issue in the mean time.
