### ISSUE TITLE
Azure Monitor "View in Azure Portal" data link can become ambiguous

### ISSUE THREAD

**Issue by kyledevans-cmp** [grafana/grafana#82286]
### What happened?

I created a data link to take the user to a resource's page on the Azure portal:

![image](https://github.com/grafana/grafana/assets/133250409/9ca967c0-e183-4dba-8ab6-30b83f756dca)

The problem is that no matter what I name my new data link it's still ambiguous and confusing with the default link "View in Azure Portal" that is generated by the Azure Monitor data source.

### What did you expect to happen?

My users need to be able to glance at the list of data links and immediately know which link is the correct one.  The current default generated data link text really collides with any kind of link that we may make that points to the Azure portal.

There's a few ways this could be resolved that I can think of:
1. An option in the panel to remove or rename the data source generate link.
2. Change the default auto generated link to something more specific.  Like "View Query in Azure Portal".
3. UI changes to provide a more clear distinction between default data links and configured ones.
    * Clever use of spacing, padding, separators, etc can make a more clear distinction between default and custom data links.
    * Admittedly this solution probably would require the most involvement from the Grafana team members.

### Did this work before?

I haven't tested on older versions.  There is a short [community discussion here](https://community.grafana.com/t/disable-view-in-azure-portal-on-point-click/107355) from November 2023 that was never resolved.  This seems like intended behavior but is resulting in unintended consequences.

### How do we reproduce it?

1. Create a Table panel with a single query from an Azure Monitor datasource.
2. The query needs to be configured to use the Azure Resource Graph service.
3. Create a simple panel that returns some Azure resources along with a generated link to the resource in the Azure Portal.  For example:
```
resources
| where tags.platformMap =~ 'true' and tags.environment =~ 'prod'
| project ResourceName=name, PortalLink=strcat('https://portal.azure.com/#@example.com/resource', id)
```
4. Create a data link with the following settings:
![image](https://github.com/grafana/grafana/assets/133250409/ba754711-5050-4e3f-9822-7faea77ebd2e)
5. Save and then go back to viewing the dashboard.
6. Click on the text of one of the rows in the table, then try and figure out which link takes you to the resource's management page and which one takes you to the Azure Resource Graph Explorer query editor.

### Is the bug inside a dashboard panel?

I need to scrub my data before I can provide the requested information.  I am happy to come back and do this if the information I provided was insufficient.

This really became an issue for me on a Table panel.  Other panel types like Stat also automatically create the "View in Azure Portal" link.

### Environment (with versions)?

Grafana: v10.4.0-65875 (b758b91e84)
OS: Windows 11 Business 23H2
Browser: Chrome 121

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
Thank you for creating this issue @kyledevans-cmp and I apologise for the delay in response. I agree this can be ambiguous and I've created a PR to clarify this link is for viewing the _query_ in the portal.

**Comment by kyledevans-cmp** [comment]
Perfect!  Thank you!
