### ISSUE TITLE
XYChart: Overlapping x-axis tick labels

### ISSUE THREAD

**Issue by allomorphy** [grafana/grafana#82284]
### What happened?

The X-axis of time on an XY Chart _Beta_ has overlapping tick text.

![image](https://github.com/grafana/grafana/assets/50141922/7b3840b5-2dde-4d65-8ec1-1f1a78210b51)

### What did you expect to happen?

That you can adjust the frequency of the ticks so that they do not overlap or some such config that is available in for example Time Series Chart

### Did this work before?

NAFAICS. And not sure if this is due to Beta status of this fine Chart type or my dumb oversight. (The Overrides system is rather freaky to navigate in click and poke).

### How do we reproduce it?

1. Make an XY chart
2. Use any Time Format
3. Change zoom level if you do not already see overlap of the tick text

### Is the bug inside a dashboard panel?

XY Chart

### Environment (with versions)?

Grafana: 10.3.1
OS: Mac
Browser: Safari, Chrome ... did not test more

### Grafana platform?

Docker

### Datasource(s)?

Influxdb

**Comment by leeoniya** [comment]
thanks, we'll take a look.

something additional worth considering is making much shorter labels to reduce impact of this.

8 days ago -> -8d
1 month ago -> -1mo
in 2 months -> +2mo

**Comment by allomorphy** [comment]
> thanks, we'll take a look.
> 
> something additional worth considering is making much shorter labels to reduce impact of this.
> 
> 8 days ago -> -8d 1 month ago -> -1mo in 2 months -> +2mo

Thank youi @leeoniya 
These strings are a cute way of representing time and I discovered them in the standard Time format options provided by Grafana. So these are not custom strings and I had no idea that you could make custom time strings.

XY Chart is a massively powerful step (out of the domain of time series), let's make it rock 😊

**Comment by allomorphy** [comment]
> thanks, we'll take a look.
> 
> something additional worth considering is making much shorter labels to reduce impact of this.
> 
> 8 days ago -> -8d 1 month ago -> -1mo in 2 months -> +2mo

Hey @leeoniya 

I am wondering if we made any progress on the overlapping time axis labels.
Would be great if you would let us know.

Also would be great if you shared how to reformat the time strings as you recommend, where and how do we do this. (Saves searching and iteration effort on our part ;-) )

Thank you!
E

**Comment by allomorphy** [comment]
Sorry, still a bitch this 🤷‍♂️
Not sure how hard a fix could be.
The moment.js time formatting is not deterministic in my hands either.

XY is a super powerful panel. Massive scope.

Thanks
E

**Comment by leeoniya** [comment]
sorry, we (the dataviz team) have a ton of stuff on our plate and we have to prioritize work that is highest impact.

if you'd like to make a PR that attempts this, that would help push this forward. roughly, i think this would involve:

1. adding a new unit, like `From Now (short)`
   <img width="473" alt="image" src="https://github.com/user-attachments/assets/6760e983-0fae-4ddc-9743-3255a9e095e4">
  https://github.com/grafana/grafana/blob/82236976ae7a1aeb4ed58d97085308b156da7bbd/packages/grafana-data/src/valueFormats/categories.ts#L215-L216
2. adding something to the formatter options (that maybe handles adaptive precision based on full time range or tick increment).  maybe using [Moment's short formatter](https://momentjs.com/docs/#/plugins/shortformat/) and then replacing `ago / in` with `- / +`
   https://github.com/grafana/grafana/blob/f1c3c559836f78e4b13e12f57d7018ba13fc09ad/packages/grafana-data/src/datetime/formatter.ts#L50-L61

**Comment by gojanpaolo** [comment]
We're also encountering this issue. I think the ability to specify a fixed number/count of x-axis labels would work on our end (e.g. 5 labels including the min/max would work in our use case).

![Image](https://github.com/user-attachments/assets/3d4cc280-4d0b-458b-ae70-1ac34d4bb6fe)

**Comment by leeoniya** [comment]
this was significantly improved by https://github.com/grafana/grafana/pull/93195, which will be in the upcoming 11.3 release, (already rolled out to our cloud users).

for self-hosted, you can try it in a nightly build: https://grafana.com/grafana/download/nightly?edition=oss

**Comment by gojanpaolo** [comment]
Just now tried 11.3.0-77331 and it worked like a charm! 🤩 

![Image](https://github.com/user-attachments/assets/ee41caab-5284-440d-8351-9f6e7bef4189)
