### ISSUE TITLE
logarithmic scale for small values

### ISSUE THREAD

**Issue by lgerster** [grafana/grafana#8231]
Logarithmic scale seems to only work for large numbers. For values smaller than one the scale is broken. It goes from 1 to the next tick at 0, which is wrong, as zero never shows up on a log scale.
As our values range from 10^-10 to 1, the log scale is unusable for our purposes. Furthermore it would be useful to have intermediate tick marks at .25, .5 and ,75 of each decade

**Comment by torkelo** [comment]
this should be fixed in 4.3 (master/nightly builds):
https://github.com/grafana/grafana/issues/3620
