### ISSUE TITLE
Configuration: Grafana no longer parses __file references in environment variables

### ISSUE THREAD

**Issue by GauntletWizard** [grafana/grafana#82328]
### What happened?

I attempted to login to my grafana instance with uses Google oauth as it's only auth mechanism, and was greeted by an error 401:
![image](https://github.com/grafana/grafana/assets/194325/0c61e9f6-f90c-4c3a-9028-c92ce068b633)

After a few minutes of debugging, I noticed something odd in the URL I was being redirected to:
https://accounts.google.com/signin/oauth/error/v2?authError=Cg5pbnZhbGlkX2NsaWVudBIfVGhlIE9BdXRoIGNsaWVudCB3YXMgbm90IGZvdW5kLiCRAw%3D%3D&client_id=%24__file%7B%2Fvar%2Frun%2Fsecrets%2Fgrafana%2Foauth%2Fclient_id%7D
Looking at the URL parameters, I see our client ID is set directly to our value of `GF_AUTH_GOOGLE_CLIENT_ID`, i.e. `$__file{/var/run/secrets/grafana/oauth/client_id}`

### What did you expect to happen?

I expected the __file directive to be interpreted, and for the secret value to be read out of our mounted secret volume.

### Did this work before?

In versions prior to 10.2, $__file() references in environment variables were interpreted by the configuration engine.

The "correct" method is documented at https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#configure-grafana-with-docker-secrets

### How do we reproduce it?

1. Start a grafana instance running 10.1 or earlier
2. Configure OAUTH using the environment variable configuration overrides and set them to a file path, i.e. `GF_AUTH_GOOGLE_CLIENT_ID='$__file{/var/run/secrets/grafana/oauth/client_id}'`
3. Upgrade to Grafana 10.3
4. Attempt to login via Oauth, and look at the redirected URL. The file name rather than oauth client id will be in the redirected client id parameter

### Environment (with versions)?

Grafana: 10.3.1 (sha256:7567a7c70a3c1d75aeeedc968d1304174a16651e55a60d1fb132a05e1e63a054)
OS: Linux
Browser: N/A

### Grafana platform?

Kubernetes

**Comment by kevinslin** [comment]
We also ran into this issue. Worked around by configuring grafana via `grafana.ini` which is able to correctly resolve the `$__file` reference
