### ISSUE TITLE
How to show many cpus with multi-set in a gragh?

### ISSUE THREAD

**Issue by itfanr** [grafana/grafana#8232]
Please include this information:
- What Grafana version are you using?     grafana-4.2.0-1.x86_64.rpm
- What datasource are you using?   influxdb 
- What OS are you running grafana on?   linux 
 
Hello everyone, 
I want to show many cpus with multi-set in a gragh, but I can only get a cpu as flows: 

![1](https://cloud.githubusercontent.com/assets/4652694/25475124/501cee96-2b68-11e7-9016-ddcd5d6a64c2.png)
![3](https://cloud.githubusercontent.com/assets/4652694/25475121/50196500-2b68-11e7-8e9c-c3152d7adf3f.png)
![4](https://cloud.githubusercontent.com/assets/4652694/25475123/501b6e04-2b68-11e7-86a3-3a7434ef33b8.png)
![5](https://cloud.githubusercontent.com/assets/4652694/25475122/5019cb62-2b68-11e7-8b9a-c4db695ce839.jpg)

Can you help me?

Thank you .

**Comment by itfanr** [comment]
I made it !

````
GROUP BY : tag(cpu)
```

**Comment by torkelo** [comment]
please in the future read the "new issue template" which instructs you to open questions on the community site (https://community.grafana.com)

**Comment by itfanr** [comment]
@torkelo   ok
