### ISSUE TITLE
Singlestat panel is not showing units

### ISSUE THREAD

**Issue by giles-dev** [grafana/grafana#8233]
Hi

I'm using Grafana v4.2.0 (commit: 349f3eb) on Debian Jessie. InfluxDB 1.2 datasource running on the same Debian VM as Grafana. Firefox browser on Windows to configure.

The SingleStat panel seems not to display the units, see the screenshot attached. I have selected degrees C but the panel isn't showing it. No other units work either, but the postfix text does (so I could put the unit there I suppose, but not as neat).

Thanks
Giles.

 
![grafana_singlestat_units](https://cloud.githubusercontent.com/assets/28095115/25481287/6250a090-2b44-11e7-9b69-cc0a732c7776.jpg)

**Comment by torkelo** [comment]
try reloading the dashboard (hit recycle icon in upper right). Bug with the unit selector is not causing a re-render in 4.2 (will fix)

The unit is working
http://play.grafana.org/dashboard/db/celcius?orgId=1

**Comment by giles-dev** [comment]
Thanks - I agree the unit is working on the play site but this trick didn't fix it for me. Instead I manually added the unit as the Postfix value.

**Comment by torkelo** [comment]
it didnt? even after reload? Can you check your chrome dev tools console for any js errors? that is super strange.

**Comment by giles-dev** [comment]
Hi, no, not after a browser restart even. 

Could it be related to another issue with SingleStat I have, in that the threshold colouring doesn't seem to be applied? See this screenshot, the value of the stat is 1.something, the thresholds are 1.000,2.000 yet the panel is coloured green. I'd expect it to be orange.

![grafana_singlestat_threshold](https://cloud.githubusercontent.com/assets/28095115/25520917/a769667e-2bf5-11e7-8bae-df1bf6028187.jpg)

Also, if I switch on the gauge mode the value bar is not drawn:

![grafana_singlestat_gauge](https://cloud.githubusercontent.com/assets/28095115/25521038/148e8c0c-2bf6-11e7-829d-32489c21c907.jpg)

The query to return this value from InfluxDB is:

`SELECT "value" FROM "autogen"."power_consumption" WHERE "sensor-id" = 'leb' AND $timeFilter`


I am not a web developer so aren't familiar with the dev console, but I opened it and the only thing that appears in the log (set to verbose) is the following error whenever I switch to the Options tab:

> boot.5ee7468a.js:39 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
> boot.5ee7468a.js:41 [Violation] 'setTimeout' handler took 60ms

Thanks
Giles

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab and inspect the raw response for your InfluxDB query? I suspect that it is returning a string instead of an actual number type.

**Comment by giles-dev** [comment]
Hi

Oh!! I must say I hadn't really considered the data type stored in InfluxDB. I'm more used to MySQL where you explicitly define it in every table. I suspect I'm storing all my values as strings. I'll check/change and report back.

Cheers
Giles.

**Comment by giles-dev** [comment]
Hi

Just to confirm, yes, that was the problem. I am now using numeric data and the Singlestat panel is working with the gauge, colouring and and unit display.

Thanks for your help, it's very much appreciated. Grafana is simply excellent : )

Cheers
Giles
