### ISSUE TITLE
TraceView: Add span filters to panelState to be preserved in URL

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#82351]
Right now filtering trace view and sharing the URL does not preserve the filtered state. Adding the filter state as panelState would add this to URL state and make it shareable.

**Comment by macabu** [comment]
Hi @aocenas , I wasn't able to reproduce this, I tried copying both short and regular URLs for sharing, and the filters are always preserved. Do you mind sharing your steps to reproduce it?

**Comment by aocenas** [comment]
Considering how old is this issue I think we can just close it if it is not reproducible anymore. Is highly likely something changed which wasn't linked to this issue as this was a feature request not a bug report.

**Comment by eugeniyk** [comment]
I'd like to reopen this feature request as it's quite handy

The use-case is straight-forward - in the traces with 1k+ spans it's very useful to see only client/server spans (filter `kind~="(client|server)"`). It will be convenient to be able to provide span filters that will be applied for the single trace.

Right now shareable URL contains TraceQL which is trace-level; Only once the trace is loaded, span filters become available.
