### ISSUE TITLE
[Bug] Constant/Custom templating variables as regex in query templating variable broken

### ISSUE THREAD

**Issue by FFalcon** [grafana/grafana#8236]
@torkelo Something between 4.2-beta and 4.2 has broken the use of constant or custom templating variables as regex in query templating variables. I couldn't seem to find what did though.

**Comment by torkelo** [comment]
Strange, cant understand why it has ever worked. If variable is used in a regex operator space like `=~ /$custom/`  grafana is going to regex escape the variable value. This has always been the case (at least if you use query editor). If you use raw query editor mode all variables that have muli or all enabled will be regex escaped. 

There is a feature request to have an option to disable this:
https://github.com/grafana/grafana/issues/7955
