### ISSUE TITLE
Saga - Add tabular Inter font to text component

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#82371]
Hello! Is there any plan to add tabular numbers to Saga? They would make our tables, chart popovers and lists of numbers in general easier to scan. Especially with right-aligned paragraphs and using a consistent number of decimals.
Inter (https://rsms.me/inter/) supports them through the tnum OpenType feature.

**Comment by joshhunt** [comment]
Lets add a prop to `<Text />` that sets `font-feature-settings: "tnum";` property
