### ISSUE TITLE
[Feat Req] LDAP: Change order of user bind to precede group membership lookup

### ISSUE THREAD

**Issue by dmoagx** [grafana/grafana#8237]
I want to use LDAP authentication against Red Hat IPA with an anonymous initial bind, but the 
 actual user is rejected for missing group membership  (same setup works with Apache):

```
DBUG[04-27|16:18:04] Ldap User found                          logger=ldap info="(*login.LdapUserInfo)(0xc4201bc310)({\n DN: (string) (len=53) \"uid=foobar,cn=users,cn=accounts,dc=ipa,dc=example,dc=com\",\",\n LastName: (string) (len=8) \"Bar\",\n Username: (string) (len=8) \"foobar\",\n Email: (string) (len=26) \"foo.bar@example.com\",\n MemberOf: ([]string) {\n }\n})\n"
INFO[04-27|16:18:04] Ldap Auth: user does not belong in any of the specified ldap groups logger=ldap username=foobar groups=[]
```

From what I understand Grafana does LDAP login like this:
```
initial bind (anonymous)
  - find user DN
  - lookup Last Name, First Name, E-Mail
  - lookup Group Membership

second bind (user DN + password)
  - verify user/password by login
```

But it should be doing it like this:
```
first bind (anonymous)
  - find user DN

second bind (user DN + password)
  - verify user/password by login
  - lookup Last Name, First Name, E-Mail
  - lookup Group Membership
```

This is because Red Hat IPA does not return the `memberOf` attribute to anonymous bind users for security reasons:

> memberOf can contain some privileged information that you don't want to expose to anonymous users, like sudo and HBAC rule membership.

https://www.redhat.com/archives/freeipa-users/2013-October/msg00043.html

Note that this limitation can be potentially the case for any LDAP server (and any attribute). The anonymous bind should only be used to lookup the DN for the actual user.

- What Grafana version are you using?
4.2.0
- What OS are you running grafana on?
Red Hat 6.8

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
