### ISSUE TITLE
Navigation: Remove nav overrides in hosted grafana

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#82370]
- there are some [nav overrides in hosted grafana](https://github.com/grafana/hosted-grafana/blame/main/pkg/hgapi/instance/config_ini.go#L226)
- we should remove these so that all nav placements are located together [here](https://github.com/grafana/grafana/blob/main/pkg/services/navtree/navtreeimpl/applinks.go#L293) in core
- we should also update the test to ensure no future nav overrides are placed here
- need to wait for https://github.com/grafana/grafana/pull/82174 to make it through all the rolling release channels before proceeding

**Comment by joeblubaugh** [comment]
Why do we want these nav overrides to be in core? That will mean that any nav changes may take up to a month to propagate from merge to the slow channel.

**Comment by ashharrison90** [comment]
see previous discussion: https://raintank-corp.slack.com/archives/C01LENC4MD5/p1707407786759419 
it mainly boils down to "we want them in a single place". last time we tried to move asserts it took way longer than it should have because there was a competing override here. 

> That will mean that any nav changes may take up to a month to propagate from merge to the slow channel. 

is that a problem? 🤔 that's the point of the slow channel, it's slow 😄

**Comment by jarben** [comment]
@ashharrison90, I just found this discussion. Wouldn't it be better to keep cloud plugins in HG only? We often use HG feature flags, etc. The Collector plugin is an example of how navigation, including order, [can be defined](https://github.com/grafana/hosted-grafana/blame/ba0a4e7a4da5239c7b9512246129469edb1f6cfa/pkg/hgapi/instance/config_ini.go#L225C3-L225C97) without a definition in core. This would also make the OSS Grafana free of cloud-only code.

**Comment by ashharrison90** [comment]
@jarben ...maybe? 😅 

imo the advantage of having a single source of truth for this config outweighs the negative. i'm actually unsure what the negative is... the ~1 week delay before it makes it to steady? 🤔 

it's not a hill i'm willing to die on though. if we wanted to split it, all i'd say is we'd need to move all the cloud apps to the core config and i guess add a comment in core to say "if you want to position a cloud app, add the override in cloud instead"
