### ISSUE TITLE
Dashboards: Cannot change folder and save

### ISSUE THREAD

**Issue by 6nv** [grafana/grafana#82398]
### What happened?

https://github.com/grafana/grafana/assets/91281131/d78f7f1f-fc02-4bc4-a126-2f0100961b02

### What did you expect to happen?

The ability to save the dashboard after changing the folder.

### Did this work before?

I don't know.

### How do we reproduce it?

1. Create a dashboard
2. Save it
3. Change the folder
4. Try to save again

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Grafana: v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)
OS: macOS 14.2.1 (23C71)
Browser: Brave v1.62.162

### Grafana platform?

I don't know

### Datasource(s)?

N/A

**Comment by Clarity-89** [comment]
Hi this issue seems to be fixed in the latest version, so try upgrading your Grafana.

**Comment by 6nv** [comment]
I tried a local installation of Grafana 10.3.3, and I'm getting the same behavior. I can **Save As** but I cannot **Save** the dashboard after only changing the folder.
