### ISSUE TITLE
Docs: Prometheus Datasource needs improvement

### ISSUE THREAD

**Issue by jayeye** [grafana/grafana#8240]
This is not documentation. There is no explanation of anything, no examples, just screenshots of empty fields.

**Comment by torkelo** [comment]
This is not a an issue, no detail at all what you would like to see or feel missing, just an empty complaint. 

So the  horrible tone aside could you provide some detail? Do you want us to replicate the prometheus docs? We are we aware that the docs can be improved, sadly the prometheus community is not that involved in doing this. We do (core Grafana team) hope to spend time improving docs shortly.

**Comment by torkelo** [comment]
sorry, hit the close by accident

**Comment by torkelo** [comment]
Prometheus docs got a big update in may so closing this
