### ISSUE TITLE
Alerts - Aggregated Graphs

### ISSUE THREAD

**Issue by kotarusv** [grafana/grafana#8241]
want to make sure my understanding is correct or any issue with grafana in terms of bugs or limitations. We started using Grafana on big large scale setup. Alerts are not properly working on aggregated graphs.  

Example: 

1. I have a load balanced web serves and have a health probe. If I create an aggregated graph with all the matching web servers and want to alert if any web server went down . it is only alerting first web server went down and going into alert state but not triggering another alert if another web server also goes down subsequent? if i setup individual graphs on each web server, everything is alright and able to get an alert whenever  any web server went down in the firm.

2. my hosting team want to setup alerts for basic needs, like high load, root fs full, etc. Alert behaviour is same like above, only able to get 1st alert but no further alerts unless 1st alert went to OK state. We can't predict or guaranted that other nodes won't satisfy condition unless 1st node comes back to OK state. 

is it expected behaviour ? or something we are doing wrong in terms of setting up alerts?

We also tried creating separate queries for each node in graph panel and trying to accommodate or mimicking  aggregate condition by specifying separate query for each node. Although it is again time  waste process similar to setting up an alert for individual graph, but at least we have a single graph with multiple queries. This setup also not working or no guarateed all the time

only working scenario is setting up individual graph for every query. This is not practical when we have hundre of nodes and want to get an alert if one or more nodes failed to match condition.

i think this is very basic feature, am sure we are doing something wrong unless this feature not available.

**Comment by kotarusv** [comment]
Even aggregate graph send an alert although it is not reliable, it doesn't have information about which host or which tag in where condition is failing. It is causing confusion to ops guys which host/component is  having issue.

Due to these 2 issues, unable to use aggregated graphs in alerts except for other use cases. 

These are very important in my opinion not only us, but anyone who use Grafana in OPS world. I am wondering how these basic features are missing unless we are doing terribly wrong


Srinivas Kotaru

**Comment by torkelo** [comment]
Looks like topic 1) and 2) are the same? That you have a query that returns many series and want to alert on all of them but currently Grafana only notifies if the any series cause the alert to fire, and it has to go to OK for another alert to fire:

This is related to this feature request issue: https://github.com/grafana/grafana/issues/6041
No ETA on that but we hope to get to it within a couple of months. 

>These are very important in my opinion not only us, but anyone who use Grafana in OPS world. I am wondering how these basic features are missing unless we are doing terribly wrong

Alerting in Grafana is still very new (only introduced in 4.0) there are a lot of features and detail missing which we hope to address in the coming months/years.

**Comment by kotarusv** [comment]
Thanks you . Grafana is excellent tool and want to see its excellency in alerts tool. At this point we are not taking advantage of full alerts capabilities due to missing features. I hope you guys understand the importance of alerts and give more flexibility in that areas.  While I am paying around Grafana since few months for a large company, everything is excellent excellent alerts. Decent improvements required on this area.

Just want to check my understanding is correct on template variables graphs. Still it is not possible to setup alerts on template graphs right? template variables are great but unable to setup alerts on these graphs is again a really required missing feature

**Comment by torkelo** [comment]
So far no one has come up with a good reason to support template variables in alerting, nor how it would work, how it can be made understandable etc, so no plan to support that, but beside that we hope to improve alerting a lot the coming year
