### ISSUE TITLE
Authentication LDAP not showing when auth.ldap enabled true is capitalized

### ISSUE THREAD

**Issue by maikel-09** [grafana/grafana#82427]
### What happened?

Grafana does not show ldap debug view. With the following configuration.

```
[auth.ldap]
enabled=True
```
<img width="1088" alt="image" src="https://github.com/grafana/grafana/assets/58327038/c88dc145-69d4-41cd-9e73-d9fe82f0c608">

It does however with 
```
[auth.ldap]
enabled=true
```

<img width="1092" alt="image" src="https://github.com/grafana/grafana/assets/58327038/1b578748-7c44-4271-b887-fbd6a928efe3">

### What did you expect to happen?

I would expect one of the following things to happen:
- Error message in Grafana logging that auth.ldap setting is invalid or at least not used
- LDAP debug view is available in Authentication tab

### Did this work before?

Don't know because of https://github.com/grafana/grafana/issues/73884

### How do we reproduce it?

1. Set auth.ldap enabled to `True`
```
[auth.ldap]
enabled=True
```
2. Restart grafana

### Environment (with versions)?

Grafana: 10.1.7
OS: RedHat Enterprise Linux 8
Browser: Multiple

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by wessp01** [comment]
We are facing the same issue. I don't think it's difficult to change

**Comment by usmangt** [comment]
Hi @maikel-09,

Thanks for opening this issue.

I checked the Grafana Configuration docs, and it always mentions setting it to either `true` or `false` so that is the right value it only accepts by design.

**Comment by morganchristiansson** [comment]
Why not just accept True?
