### ISSUE TITLE
 smtp configuration issue

### ISSUE THREAD

**Issue by samyak335** [grafana/grafana#82433]
### What happened?

When i have installed grafana on a Linux server (yum package) , created 2FA for Gmail account and got app password generated for the smtp configuration which i have provided below works fine and i get email notification alerts .
```
[smtp]
enabled = true
host = smtp.gmail.com:587
user = abcd@gmail.com
password = xxxxxxx
from_address = abcd@gmail.com
startTLS_policy = MandatoryStartTLS
```

But when i use the same smtp config as shown below  in grafana helm chart values aks , when i test the alert notification email in grafana ui , i am getting an error as shown below.

**helm chart values under grafana.ini section in my values.yaml**

```
smtp:
  enabled :  true
  from_address :  abcd@gmail.com 
  host :  smtp.gmail.com:587
  passwordKey:  xxxxxxx
  startTLS_policy :  MandatoryStartTLS
  user:  abcd@gmail.com
```

**error in the grafana ui notification**
i get   error="Failed to send notification to email addresses: abc-test@gmail.com: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ge4sm941467pjb.49 - gsmtp"

If it is a firewall/network issue, it wont go till submitting credentials and getting the error.Not sure where its facing the issue.

### What did you expect to happen?

To get notification email using helm chart grafana, as i got it working using yum package grafana.

### Did this work before?

yes , it worked in yum package grafana installation .

### How do we reproduce it?

1. Create 2FA for gmail account, once 2FA is enabled , get app password generated .
2. Configure smtp in helm grafana chart values.yaml under grafana.ini section as shown below
```
smtp:
  enabled :  true
  from_address :  abcd@gmail.com 
  host :  smtp.gmail.com:587
  passwordKey:  xxxxxxx
  startTLS_policy :  MandatoryStartTLS
  user:  abcd@gmail.com
```

      
3. helm install  -f grafana-values.yaml grafana grafana/grafana
4. try to send test alert notification email from grafana ui

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.3
cluster:  AKS
Browser: chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

No

**Comment by usmangt** [comment]
Hi @samyak335 

Thanks for opening this issue:

Just like in the local install you used:

`password = xxxxxxx
`
use the same in the helm as I don't think `passwordKey` parameter exists (just replace it with password).

**Comment by samyak335** [comment]
The below configuration worked .I have configured a secret for my smtp username and password as smtp-config-sec and configured smtp as below in my values.yaml

smtp:
     enabled: true
     existingSecret: "smtp-config-sec"
     host:  abc.xyz.com:154
     startTLS_policy: "MandatoryStartTLS"
