### ISSUE TITLE
Log scale going down too far

### ISSUE THREAD

**Issue by volter** [grafana/grafana#8244]
The lower part of the scale goes below where it should be. Giving the graph more vertical room doesn't solve the issue, see screenshot.

The problem was introduced somewhere between the 4.2.0 release and 4.3.0-7380pre1. That was the oldest nightly build I could get.

Datasource is ES, happens in Firefox and Chromium.

![screenshot_20170428_131540](https://cloud.githubusercontent.com/assets/1042313/25527120/7ecbe346-2c17-11e7-821b-ceb37564b774.png)

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by bakerkj** [comment]
I am seeing this problem as well in 4.3.1.

In an attempt to fix the issue I have applied 634ee0f to /usr/share/grafana/public/app/plugins/panel/graph/graph.ts as installed by the ubuntu package (version 4.3.1).  I then restarted grafana-server.  Unfortunately I am still seeing the problem.  Below is an image of the problem as I am seeing it.

Thanks!

![p](https://cloud.githubusercontent.com/assets/5491232/26475599/9aa120e8-4186-11e7-911f-5946dff7242b.png)

**Comment by bakerkj** [comment]
@daniellee I am not familiar with the build process and I didn't rebuild the javascript.  Having rebuilt the debian packages and installing those it looks to be fixed.

Thanks!

**Comment by bobrik** [comment]
It still looks quite weird in 4.3.2:

![image](https://cloud.githubusercontent.com/assets/89186/26647209/66c7fdd4-45f3-11e7-876b-e9f738d68151.png)

Compare to 4.1.3:

![image](https://cloud.githubusercontent.com/assets/89186/26647223/730facea-45f3-11e7-9444-567b27095a54.png)
