### ISSUE TITLE
BUG - Annotation variable regex

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#8245]
grafana version: 4.2.0-beta1

I have a dashboard where I use regex in template variables
example: `foo.*` `bar.*` which matches hosts `foo01.local` `bar01.localhost.localdomain` etc 

I use annotation with logstash datasource. 

When I configure my annotation query to use the regex variable, it becomes broken
this: `tags:/$host/` 
becomes(using tcpflow -c -i eth0 port 9200 to see the query): 
`{"query_string":{"query":"tags:/foo.\\*/`

It works when I bypass the variable, and use the regex directly into the annotaiton query,
this: `tags:/foo.*/`
becomes: 
`{"query_string":{"query":"tags:/foo.*/`

The extra `\\` is breaking the query

**Comment by torkelo** [comment]
By default variables used in Elasticsearch queries are lucene escaped. Otherwise values containing a value with lucene control words/chars would not work. 

https://github.com/grafana/grafana/issues/7955
