### ISSUE TITLE
[Bug] Telegram notification doesn't include the image on the notification

### ISSUE THREAD

**Issue by DavidVentura** [grafana/grafana#8246]
- What Grafana version are you using?
v4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Debian Jessie
- What did you do?
Got an alert
- What was the expected result?
I get an alert **with** an image
- What happened instead?
I got an alert **without** an image
 
Related notification log
```
t=2017-04-28T15:37:51+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=ok prev state=alerting
t=2017-04-28T15:37:52+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=1 sent count=1
t=2017-04-28T15:37:52+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/main?&panelId=4"
t=2017-04-28T15:37:53+0000 lvl=info msg=uploaded logger=alerting.notifier url=
t=2017-04-28T15:37:53+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=telegram id=2 isDefault=true
t=2017-04-28T15:37:53+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.telegram bot_token=yaddayaddayadda
t=2017-04-28T15:37:53+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.telegram chat_id=1719831
```

Notification:
![2017-04-28-124113_444x110_scrot](https://cloud.githubusercontent.com/assets/3650670/25536297/af211e6e-2c10-11e7-8553-056442d134d0.png)

**Comment by daniellee** [comment]
What settings do have for your Telegram Notification channel? Have you checked the `Include Image` checkbox?

**Comment by DavidVentura** [comment]
Yes, it is checked

On April 29, 2017 5:14:32 PM GMT-03:00, Daniel Lee <notifications@github.com> wrote:
>What settings do have for your Telegram Notification channel? Have you
>checked the `Include Image` checkbox?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/grafana/grafana/issues/8246#issuecomment-298191847

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniellee** [comment]
And what settings do you have for external images?

http://docs.grafana.org/alerting/notifications/#external-image-store

**Comment by DavidVentura** [comment]
None, but the images are sent to my email anyway, so I expected this to work on the telegram alert, as it's a trivial http request(and Grafana already has the required data):

```bash
curl -s -X POST "https://api.telegram.org/bot<token>/sendPhoto" \
-F chat_id=<chatid> -F photo="@/path/to/your/photo.jpg"
```

**Comment by daniellee** [comment]
The problem is that Grafana does not have the required data. It does not store the image file automatically. For emails, the image is embedded if there is no external storage configured. But for all the other notification channels if you want an image then you have to configure external storage.

**Comment by DavidVentura** [comment]
You embed a base64 representation of the image you have in memory in a mail.
You can POST the same image you have in memory to telegram. You don't need to store it anywhere.

You would just do something like
```
curl -s -X POST "https://api.telegram.org/bot<token>/sendPhoto" \
-F chat_id=<chatid> -F photo="binary-data"
```

**Comment by DavidVentura** [comment]
You embed a base64 representation of the image you have in memory in a mail.
You can POST the same image you have in memory to telegram. You don't need to store it anywhere.

You would just do something like
```
curl -s -X POST "https://api.telegram.org/bot<token>/sendPhoto" \
-F chat_id=<chatid> -F photo="binary-data"
```

**Comment by daniellee** [comment]
Sounds like a feature request rather than a bug. None of the core team use Telegram so this part of the code base is dependent on PR's.

Here is the relevant section if you want to add that yourself:

https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/telegram.go#L96-L98

and this is email code for comparison: 

https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/email.go#L93-L101

As an alternative, instead of submitting a PR, you can open a new feature request issue for posting images to telegram.
