### ISSUE TITLE
Query editor - New Line and Run query keystrokes

### ISSUE THREAD

**Issue by krisztianfekete** [grafana/grafana#82469]
**Why is this needed**:

Reopening https://github.com/grafana/grafana/discussions/52616 as a feature request.
> "A user on twitter brought up an inconsistency between the Explore UI and the PrometheusIO's UI, where explore creates a new line by hitting enter, and shift enter runs the query, and the opposite happens in PrometheusIO..."

**What would you like to be added**:

> "... It seems that [both] editors used to be consistent but that is no longer the case. We would like to not switch this on people who may be used to how it is now, but still give the option for people who may be switching between applications so they can match."

**Who is this feature for?**

Users of both Prometheus and Grafana

**Comment by NWRichmond** [comment]
Closing in favor of https://github.com/grafana/grafana/issues/83022
