### ISSUE TITLE
Update alert query when the query in a panel is changed

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82492]
### Discussed in https://github.com/grafana/grafana/discussions/72610

<div type='discussions-op-text'>

<sup>Originally posted by **ThommyH** July 31, 2023</sup>
When you create an alert from an panel the query is suggested for the new alert. However, when you update a panel you must recreate/update the alert to follow suit or else the panel and the alert are out of sync and you may not notice that the alert is not really anymore what you expect.

Do I overlooked something or is it really that cumbersome? Or is there a different, better way?</div>

**Comment by gelicia** [comment]
Related: https://github.com/grafana/grafana/issues/82555

**Comment by armandgrillet** [comment]
Alert rules and panels are not tightly coupled anymore, this is a core concept of Grafana Alerting. This is expected behavior. We could have a new panel, "alert rule visualization", showing the data of the alert rule precisely and avoiding this kind of drifts.
