### ISSUE TITLE
[Feature request] Update template variables from a pane

### ISSUE THREAD

**Issue by maoe** [grafana/grafana#8249]
It would be great if template variables could be set/updated from a pane. 

For example, when there are well-known set of template variables it'd be great if we could list links in a markdown pane so we can click to set those variables. Also if those set of variables are updated dynamically, it'd be great if we could set up links in a table pane.

Currently Grafana supports setting template variables through URL query parameters. Unfortunately this doesn't work if it doesn't change the URL path. Suppose we have a markdown pane that contains a link like this:

```markdown
[Set my-template-var to foo](/dashboard/db/my-dashboard?var-my-template-var=foo)
```
Clicking the link does update the URL query parameter in the browser, but it doesn't update the template variable. So no effects.

More concrete example is available on the [Grafana Labs Community](https://community.grafana.com/t/update-a-template-variable-from-a-panel/683).

**Comment by papagian** [comment]
Fixed by #21480
