### ISSUE TITLE
[Feature request] Prometheus auto complete support in text-edit mode

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8252]
I think this is useful.
Prometheus users are familiar with editing query in text-mode.

This is a PR.
https://github.com/grafana/grafana/pull/4708

related to https://github.com/grafana/grafana/issues/5117 .

**Comment by torkelo** [comment]
This first step is to add a proper text editor component like Ace or Monaco that has intellisense hooks / support

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/30027143-ead79472-917f-11e7-8dc8-28f2420ae277.png)

[video](https://twitter.com/grafana/status/898143069886980096?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fgrafana.com%2Fblog%2F2017%2F08%2F18%2Ftimeshiftgrafanabuzz-1w-issue-9%2F)
