### ISSUE TITLE
[Feature request] Prometheus adhoc filter support

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8253]
Supporting https://github.com/grafana/grafana/issues/6038 in Prometheus.

This is a PR.
https://github.com/grafana/grafana/pull/6138

**Comment by bergquist** [comment]
Depends on https://github.com/prometheus/prometheus/issues/2038

**Comment by mtanda** [comment]
We can gather possible label key list from query expression.
By using Ace editor, we can get metric name list in query expression, so we only need to take care about label keys of these metrics.

**Comment by daniellee** [comment]
Closed by #15290
