### ISSUE TITLE
[Feature Request] upgrade legacy to alert rules and export

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82541]
### Discussed in https://github.com/grafana/grafana/discussions/72178

<div type='discussions-op-text'>

<sup>Originally posted by **jgournet** July 23, 2023</sup>
This is a bit far fetched, but that's something that would GREATLY help adoption of alerting rule.

Flow would be something like:
- enable LEGACY ALERTING in grafana 9.
- have a new endpoint in grafana 9 that could be called something like /export-upgrade/ALERT_ID   <= this would output a JSON for the converted legacy alert to alert rule.

I'm asking this because:
- the "export" functionality already exists in grafana 9 and 10.
- the "upgrade" functionality already exists when upgrading from grafana 8 to 9 (as far as I know?)
So hopefully, this could be easy enough to implement.

This would help all the people like me who use alert/alert rules provisioning and ephemeral grafana pod/docker, as we cannot just "upgrade" those.</div>

**Comment by armandgrillet** [comment]
This is https://github.com/grafana/grafana/pull/80497
