### ISSUE TITLE
[Feature request] Notebook dashboard

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8254]
This is useful to make an alert investigation note.
(If Grafana alert feature work with this feature, it is really great.)

1. Edit query expression and draw modes without opening query editor.
2. Edit text panel contents without opening query editor.

To add this feature, we may need to add dashboard option to enable this.

References for similar UI.
- https://www.slideshare.net/weaveworks/grafana-is-not-enough-diy-user-interfaces-for-prometheus/16
- https://www.datadoghq.com/blog/data-driven-notebooks/
- http://jupyter.org/

**Comment by torkelo** [comment]
Not sure I understand, can you describe how it would work? Where are options located, what panels do they modify, how do we show them, how will this affect layouts. 

I love the idea of notebook dashboards. But the features requires weeks of design work :) so for this feature request you just want to have one panel per row and edit mode open for all panels? So you can  scroll down and edit multiple panels at the same time?

**Comment by mtanda** [comment]
@torkelo 
> so for this feature request you just want to have one panel per row and edit mode open for all panels?

yes.

> So you can scroll down and edit multiple panels at the same time?

yes. I want to edit each panels query without switching query edit view.

It is better to watch the following video to imagin how it should works.

https://vimeo.com/198697459 (please play from 00:18)

In this video, the options is located on top of graph panel. They modify graph panel and text panel.
But, I think we don't need to implement same UI.

Datadog Notebooks is seems to be inspired by Jupyter Notebook.
I think such notebook interface (like Jupyter Notebook) is originally implemented by Wolfram Mathematica.
https://www.wolfram.com/mathematica/

When user want to add a panel, current Grafana UX require view transition from dashboard view => panel edit view => dashboard view.
Opening panel editor is not fluent UX if you want to create Notebook quickly.

Most of case, user only enter query, sometimes they want to change display style line to bar or dot.

In urgent situation like on-call engineer get alert, they want to investigate quickly.
If they don't have good dashboard, they need to create dashboard.
This feature could help such situation.

Another references:
1. Presentation video of "Grafana is Not Enough".
https://www.youtube.com/watch?v=bfSMDERvkZY (from 20:30 - )

2. Jupyter Notebook demo site.
https://try.jupyter.org/

**Comment by aocenas** [comment]
So with the [Explore](https://grafana.com/docs/grafana/latest/explore/) feature I think this request is obsolete. If needed specific requests targeting Explore can be opened.
