### ISSUE TITLE
Ability to lock panel query to alert query

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82555]
### Discussed in https://github.com/grafana/grafana/discussions/73235

<div type='discussions-op-text'>

<sup>Originally posted by **gtirloni** August 14, 2023</sup>
When a alert is created through the `Create alert rule from this panel` buttom, the alert query is populated with the panel's query initially.

Afterwards, any change to the alert's or panel's query don't affect each other.

This might create confusion for users migrated from Legacy to Unified Alerting and expecting some sort of dependency between them.

Grafana could offer the option to keep the queries synchronized (maybe by adding metadata to the query to link it to the panel's query somehow) and them grey out the alert's query text so users can't change (or inform users that changes in the alert's query would change the panel's query since they are synchronized).</div>

**Comment by gelicia** [comment]
Related: https://github.com/grafana/grafana/issues/82492

**Comment by armandgrillet** [comment]
Alert rules and panels are not tightly coupled anymore, this is a core concept of Grafana Alerting. This is expected behavior. We could have a new panel, "alert rule visualization", showing the data of the alert rule precisely and avoiding this kind of drifts.
