### ISSUE TITLE
Ability to define how legend should be sorted

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82569]
### Discussed in https://github.com/grafana/grafana/discussions/73327

<div type='discussions-op-text'>

<sup>Originally posted by **gtirloni** August 16, 2023</sup>
In Grafana 10, the time series panel does not allow one to define how the legend should be sorted:

![image](https://github.com/grafana/grafana/assets/5902830/b1c2ab61-fdbb-487b-8892-7000c6a9d848)

It's possible to sort the legend after it's rendered, by clicking on the arrow for the specific column. This is not ideal.

Something like the sorting for the Tooltip should be implemented for the Legend.

![image](https://github.com/grafana/grafana/assets/5902830/337cc9f1-cf81-45b2-9860-c20fcde42cc2)
</div>

**Comment by frittentheke** [comment]
Thanks for raising this issue. This has been requested (and implemented) before?
 https://github.com/grafana/grafana/pull/40226

**Comment by gelicia** [comment]
Duplicate of #73442
