### ISSUE TITLE
[Feature Request] Set the default Y-Axis per metric

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8256]
At present a display override allows setting the Y-Axis based on matching the alias of the metric. This is useful when you know what all the labels will be for displayed metrics but when using (say) "[[tag_host]]" in the metric alias, it is possible that not all series aliases will be known.

With some graphs with multiple series, it may be desirable to have the default (or a known set) of serieses graph to the Y-Axis 1 (on the left) and for others to appear on Y-Axis 2 (on the right.)

If I do something like:
- set series X to be on Y-Axis 1
- set serieses matching .* to be on Y-Axis 2
then all serieses will use Y-Axis 2.

**Comment by torkelo** [comment]
This works today does it not? You can define regex rules for series overrides.
