### ISSUE TITLE
Alerting: Reduce does not support Median like Classic Conditions do

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82572]
### Discussed in https://github.com/grafana/grafana/discussions/73472

<div type='discussions-op-text'>

<sup>Originally posted by **evan-chaney** August  9, 2023</sup>
### What happened?

There is no option for median in the reduce expression.

### What did you expect to happen?

I expected it to have all the options that classic condition does since that is what replaces it.

### Did this work before?

Yes, in Grafana 6

### How do we reproduce it?

1. Try to get the median of a timeseries in an alert

### Environment (with versions)?

Grafana: 9.5.1
OS: CentOS 7
Browser: Google Chrome 114.0.5735.198

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

_No response_</div>

**Comment by AryaMoghaddam** [comment]
I can take this up as first issue
