### ISSUE TITLE
Feature Request: Cloudwatch templating variables embedded in strings

### ISSUE THREAD

**Issue by CyBeRoni** [grafana/grafana#8257]
- What Grafana version are you using? 
4.2.0
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on? 
Linux
- What did you do? 
Tried to put a template variable in a string for a dimension (In this case, S3 BucketName), like 'foo-$var-prod', 'foo-$var-test', etc.
- What was the expected result? 
That the metric requested from CW would, for $var='blah', be 'foo-blah-prod'. Ideally, multi-selects would repeat the dimension with the appropriate variable substituted.
- What happened instead? 
No data. I can only enter '$var' by itself.

**Comment by petegallagher** [comment]
You should use `[[ var ]]` instead of `$var` for string interpolation e.g. `'foo-[[ var ]]-prod`

http://docs.grafana.org/reference/templating/#interpolation

**Comment by CyBeRoni** [comment]
Genius. Albeit unintuitive.
