### ISSUE TITLE
Azure Resource Graph  query requires a subscription

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82577]
### Discussed in https://github.com/grafana/grafana/discussions/66948

<div type='discussions-op-text'>

<sup>Originally posted by **msbannert** April 20, 2023</sup>
When creating any diagram using Azure Monitor data source with an azure resource graph query the UI forces to specify at least one  Subscription to be used. If one leaves the field empty, the application will pick a subscription and fill it in by itself.
However, the query seems to work properly without the subscription field filled.
This aligns with the behaviour in the azure Resource Graph explorer in the azure portal, where you also execute queries always against all available subscriptions (e.g. to all subscriptions to which the current user has access to).
Proposal: get rid of the enforcement of filling in a subscription. If no subscription specified, then the query should run against all accessible subscriptions.
</div>

**Comment by aangelisc** [comment]
I believe this has been fixed by the inclusion of an all option (we've chosen to be explicit in the selection of subscriptions) in #79582. If this issue is still present please open a new issue!
