### ISSUE TITLE
Grafana reserved labels in notification policies

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82589]
### Discussed in https://github.com/grafana/grafana/discussions/70787

<div type='discussions-op-text'>

<sup>Originally posted by **DaspawnW** June 28, 2023</sup>
Is it possible to define within notification policies the `grafana_state_reason` as a label matcher?

The reason we are very unsure about this is that `rule_uid` is also not mentioned as label but it seems to work and is used by Grafana itself.
Based on the source code it looks like there is such a label https://github.com/grafana/grafana/blob/fd870702c70adf3bfb3196559077fe1929d163c5/pkg/services/ngalert/models/alert_rule.go#L114 that could be utilised on the other side checking the documentation of [reserved labels](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/how-to-use-labels/#grafana-reserved-labels) it only mentions `grafana_folder`.

An advice would be highly appreciated.</div>

**Comment by armandgrillet** [comment]
Both `grafana_state_reason` and `rule_uid` are available to users but we do not have comments on their support, we use them internally and are not planning on deprecating them at the moment.
