### ISSUE TITLE
[Bug] X axis label outside of exported PNG graph

### ISSUE THREAD

**Issue by mageo** [grafana/grafana#8258]
Hello,

When the label of the X axis is too wide, it is wrapped to a second line, but this line is cropped on the generated image as you can see below:

![unnamed](https://cloud.githubusercontent.com/assets/12015577/25579387/c8e39660-2e77-11e7-85ca-2f7eb476f653.png)

Here is the required information:

- What Grafana version are you using?

 Grafana v4.2.0 (commit: 349f3eb)

- What datasource are you using?

Graphite

- What OS are you running grafana on?

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

- What did you do?

I used the link "Direct link rendered image" in the Share Panel of a graph.

- What was the expected result?

X axis label should be complete.

- What happened instead?

X axis label is cropped.

Thank you by advance for your help!

**Comment by torkelo** [comment]
looks like a timing thing with the phantomjs rendering. When the legend is to the right two render passes are needs to get the dimensions correct. Looks like phantomjs captures the image during the first phase or something like it as the x-axis tick generation includes as many ticks it would have if the legend was not to the right.

**Comment by marefr** [comment]
Closing this since PhantomJS is now removed in master/will be removed in Grafana v7.0, ref #13802. Please use https://grafana.com/grafana/plugins/grafana-image-renderer.
