### ISSUE TITLE
Allow CloudWatch Metrics Search Partial Match

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82599]
### Discussed in https://github.com/grafana/grafana/discussions/71091

<div type='discussions-op-text'>

<sup>Originally posted by **jfharden** July  5, 2023</sup>
Using the CloudWatch data source, doing a query using a CloudWatch Metrics Search, if I use the builder it's not possible to perform a [partial match search](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html#search-expression-partial-match)

If I manually build the search expression I can do it. Take this example:

```
REMOVE_EMPTY(SEARCH('Namespace="AWS/Kinesis" MetricName="IncomingRecords"  StreamName=__nginx_fargate', 'Sum', $__period_auto))
```

Notice the value of the StreamName is not double quoted, this makes it a partial match meaning I can find streams with names such as `test__nginx_fargate` and also `staging__nginx_fargate`.

This example using the builder returns no results:
![Screenshot 2023-07-05 at 16 29 23](https://github.com/grafana/grafana/assets/2170030/9b57e1c4-b6b3-4b2d-b590-534c858964a0)

</div>

**Comment by idastambuk** [comment]
Hi @jfharden, partial match on dimension values seems like something we'd want to support. I added it to our backlog to discuss, but glad that search expressions provide a workaround in the meantime! 

More info about the investigation: 
We're wrapping dimension values in quotes " here
https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/metric_data_query_builder.go#L126

When I remove line 126, I get back all the possible matches (though also empty values? unlike with escaped \" 🤔). Needs more investigation into why this happens

The question is if we want to do this by default, as it might make it impossible to look for exact matches that are also incidentally parts of other dimension values. Maybe we could 
1. add a switch similar to "match exact", or 
2. not wrap in quotes if the selected value is custom (i.e. not one of the fetched)

**Comment by katebrenner** [comment]
won't get to this in the next 6 months.  The workaround is building the query in the code editor instead of the query builder
