### ISSUE TITLE
Elasticsearch date histogram field stuck with timeField from datasource

### ISSUE THREAD

**Issue by Kotove** [grafana/grafana#8260]
Continuing https://github.com/grafana/grafana/issues/4004
> the JSON for the dashboard doesn't change. I tested this by changing other features like the alias and closing and opening the JSON panel; the alias was different but the field and timeField values were unchanged. Regardless of what I provide for the Date Histogram field, I get

reproduced on 4.2.0.
the value selected in the Date Histogram field doesn't appear in corresponding Target.
From my point of view - it is hardcoded here:
grafana/public/app/plugins/datasource/elasticsearch/query_builder.js:

```
ElasticQueryBuilder.prototype.getDateHistogramAgg = function(aggDef) {
...
esAgg.field = this.timeField;
...
```

To get field from what is configured in query (but not cloned from main datasource timeField)

```
ElasticQueryBuilder.prototype.getDateHistogramAgg = function(aggDef) {
...
esAgg.field = aggDef.field;
...
```

**Comment by Jazzepi** [comment]
Using ES version 2.4.3 and Grafana version 3.0.4

I've found that grafana is deciding **whether or not to display annotations** based on the @timestamp of the record the annotation data is found on, instead of the "time" field mapping. The time field mapping is still used to **position** the annotation elements, but if you zoom in on them to the point where the @timestamp of the record they live on, the annotations will disappear.

**Comment by Jonathan-Rosenberg** [comment]
With Grafana 4.3.2 and ES 5.4.1 I am still unable to change the date histogram field, and was unable to get @Kotove 's solution to work.

**Comment by jonesn** [comment]
+1

**Comment by StephenOTT** [comment]
Still an issue for sure.  Its suck on the default Time Field Name used in the ElasticSearch Data Source.

Example:

1. Create Datasource and set `Time field name` to `@timestamp`
1. Create a Graph and try and change to another date field.  it wont change.  It will also **not** change using the JSON panel
1. Save your Graph.
1. Go back to Datasource and change the `Time field name` to another date field.  Press Save and Test.
1. Return to graph and edit. The Date field will be updated to the new field you selected in the datasource.

Kinda a big issue, no?

**Comment by torkelo** [comment]
the timefield is needed from data source  any way as it used in the time range filter that is always applied.

**Comment by StephenOTT** [comment]
@torkelo so this is expected behaviour?  Meaning you cannot use two different time metrics for a single data source?

**Comment by davalente** [comment]
+1
Must use on the same graph, different querys using different "group by" "date histogram" fields.

**Comment by matschaffer** [comment]
I stumbled across this before realizing that time field was a data-source level setting.

Seems like you might be able to work around this by specifying to data sources to the same cluster/index-pattern with two different timefield settings.

**Comment by parisnps** [comment]
+1

**Comment by cyberluisda** [comment]
+1

**Comment by danielmotaleite** [comment]
yep, +1
i can make this with no problem in kibana and timelion, but using grafana i'm stuck in the wrong timefield

**Comment by hegoak64** [comment]
+1

**Comment by FranklinSamboni** [comment]
+1

**Comment by cosmos78** [comment]
I have the same issue.
I have created 2 datasources one with the datefield as @timestamp and another one with another date field ( uptime converted to epoch time ).

But when I use the datasource with the epoch data field I get an empty graph. I looks like the datapicker is hardcoded to use @timestamp. Is this a correct assumption ?

**Comment by Zyian** [comment]
+1

**Comment by M0rdecay** [comment]
+1
Our case is  - we send logs to the ES once a day, so each record has two fields with time, this is event time and processing time
we planned to use the second field to evaluate the performance of the Logstash stack

**Comment by Chivolta** [comment]
+1

**Comment by Drewster727** [comment]
+1

**Comment by grial1** [comment]
+1

**Comment by xavier-isecurity** [comment]
+1

**Comment by arenard** [comment]
It seems to be still true on current Grafana 8 releases. 😢 
Even if a custom timefield is set in a date_histogram aggregation, it is siltently ignored in favor of datasource defined timefield.

@Elfo404 Do you know if there is a plan to fix this long running issue ?

**Comment by Elfo404** [comment]
@arenard nothing really planned for this issue, but I'll try to have a look soon.
