### ISSUE TITLE
Datasource Variables to allow true multi-value selection

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82605]
### Discussed in https://github.com/grafana/grafana/discussions/71494

<div type='discussions-op-text'>

<sup>Originally posted by **JohnyChevyEG** July 12, 2023</sup>
I was curious if there was a future feature add to allow multiple data sources to be selected from a data source variable.  I have multiple Prometheus data sources that have the same metrics and I would like to include them all in the same panel without having to add a query for each data source.  If I set up a variable to search only for my Prometheus data sources but it only queries the first data source checked.  From what I have seen, this multi-value option will work when repeating to multiple panels but I want all nodes on the same panel.  Thank you.</div>

**Comment by mcbrineellis** [comment]
I would like this. +1
Commented on an old closed issue (https://github.com/grafana/grafana/issues/7492#issuecomment-2004940951) before I had the chance to check if there was any currently open issue for this.

**Comment by CoolZeroNL** [comment]
+1 facing the same challange to get the results from multi datasources (same type in my case) into one table through multi select datasource variable. instead of "for each" table.
