### ISSUE TITLE
Export alert status metric

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82626]
### Discussed in https://github.com/grafana/grafana/discussions/72174

<div type='discussions-op-text'>

<sup>Originally posted by **tomershafir** July 23, 2023</sup>
I think it may be useful that grafana will optionally export alert status metric to be scraped by prometheus, like
`grafana_alert_status` with contextual labels and numeric state representation.
Then, one can have a consolidated view on alerts for a specific use case, for example, SLO alerts for a specific app, using prometheus' flexible QL and grafana's amazing visualization.

It should be configurable with filters.

The assumption I guess is the new alert manager.

(if you think its useful, I can help contributing)
</div>

**Comment by armandgrillet** [comment]
This is possible when using the alert state history powered by Loki and not Prometheus: https://grafana.com/blog/2023/07/10/how-we-improved-grafanas-alert-state-history-to-provide-better-insights-into-your-alerting-data/#unlimited-possibilities-with-the-loki-storage-backend
