### ISSUE TITLE
Cloudwatch: Cross Region Cross Account support

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82638]
### Discussed in https://github.com/grafana/grafana/discussions/69440

<div type='discussions-op-text'>

<sup>Originally posted by **Alan01252** June  2, 2023</sup>
When using cloudwatch monitoring account I want to be able to select the region to be able to select the metrics from as I can within the cloudwatch console.

![image](https://github.com/grafana/grafana/assets/112859/da3d2702-63c0-4261-a7d6-3069efe5e1b2)

In grafana currently I only get a list of accounts when choosing the region the monitoring account is in

![image](https://github.com/grafana/grafana/assets/112859/153a37ad-7a1d-4342-a7e1-f6cc451d02fb)

If I choose a different region the account list vanishes and I can't select metrics from that account.</div>

**Comment by sarahzinger** [comment]
Hi @Alan01252 My understanding is that this is a limitation of AWS's api and I suspect you'll find when you go to the AWS Console you are also limited in cross acounts per region. You can however configure your monitoring account in AWS to have monitoring enabled in each region you're interested in and that will that be reflected in grafana. Let us know how that works out for you!
