### ISSUE TITLE
[Bug] Axis labels still show when the Show option is unchecked on Y axis

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#8264]
- What Grafana version are you using?
4.1.2
- What datasource are you using?
Elasticsearch 2.4
- What OS are you running grafana on?
Windows 2012 R2
- What did you do?
Uncheck the Show option on either Left Y or Right Y axis
- What was the expected result?
The axis should be turned off including its custom label
- What happened instead?
Axis scale is off, but the label still show up

I think this is just a minor UI bug. Removing the custom label solves the issue, but it should be the default behavior.

**Comment by torkelo** [comment]
Unable to replicate this in Grafana 4.2, maybe fixed already in 4.2? 

![image](https://cloud.githubusercontent.com/assets/10999/25617318/fc5a9d0c-2f41-11e7-9587-c47a7c834408.png)

**Comment by anhlqn** [comment]
I guess so, I'll upgrade to 4.2 and and see if it is fixed. Thanks a lot for prompt reply.

**Comment by daniellee** [comment]
I could replicate it in 4.2:

![image](https://cloud.githubusercontent.com/assets/434655/25627139/f1f3f820-2f61-11e7-8736-a19f98f8e53f.png)

**Comment by Jonnymcc** [comment]
This appears to be working as expected (when unchecked the axis label disappears) at commit 1de00ded1e44b6f0851a954efd4128ceb7774b09

**Comment by torkelo** [comment]
We will fix this in the upcoming new graph panel
