### ISSUE TITLE
AlertManager recording rules should allow a range for the graph

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82648]
### Discussed in https://github.com/grafana/grafana/discussions/70001

<div type='discussions-op-text'>

<sup>Originally posted by **MaxDiOrio** June 13, 2023</sup>
I often create Loki recording rules since we process thousands of log lines and metrics graphs are slow or impossible to load.

When creating a recording rule, I ran into one query where I was getting the following error, even though the query was working as expected in Explore for the same time period.

Failed to evaluate queries and expressions: failed to execute query A: maximum of series (5000) reached for a single query

Looking into it, I determined that when creating an AlertManager rule, the sample graph it generates uses a default, unchangeable 10 minute range, even when you specify the range directly in the query.

This becomes a problem when the query you're running will only work within a shorter time frame.  It would be good to be able to set the graph range as you can in Grafana Managed.  

When creating Grafana Managed, you can specify the graph range.

Managed Rule, range set to now-1m
![image](https://github.com/grafana/grafana/assets/25855524/78a9fe74-7bfe-439a-aebe-efef95fc52de)

AlertManager Rule, range fixed to 10 minutes.
![image](https://github.com/grafana/grafana/assets/25855524/eff1a26f-cfe5-4ea6-aa53-7d25d3e2c772)

</div>

**Comment by grobinson-grafana** [comment]
Hi! 👋 Can you update to a newer version of Grafana (10 or later) and try this again? We have made changes such that Loki recording rules should be instant vectors by default and the UI allows changing the time range.
