### ISSUE TITLE
Dashboards: Cannot change folder and save [10.3.3]

### ISSUE THREAD

**Issue by 6nv** [grafana/grafana#82649]
### What happened?

https://github.com/grafana/grafana/assets/91281131/d78f7f1f-fc02-4bc4-a126-2f0100961b02

### What did you expect to happen?

The ability to save the dashboard after **only** changing the folder. I can "Save As" just fine, but I just want to move a dashboard from folder A to folder B.

### Did this work before?

I don't know.

### How do we reproduce it?

1. Create a dashboard
2. Save it
3. Change the folder
4. Try to save again

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Grafana: v10.3.3
OS: macOS 14.2.1 (23C71)
Browser: Brave v1.62.162

### Grafana platform?

I don't know

### Datasource(s)?

N/A

**Comment by natellium** [comment]
Hey there, this seems to be the same issue as reported in https://github.com/grafana/grafana/issues/59293 I will close this as a duplicate
