### ISSUE TITLE
[BUG] Grafana (v4.2.0) Build fails in Windows Environment because of unix style path in package.json (scripts attribute)

### ISSUE THREAD

**Issue by vganjare** [grafana/grafana#8266]
Hi,

package.json is having unix style path in scripts sections:
` "scripts": {
    "build": "./node_modules/grunt-cli/bin/grunt",
    "test": "./node_modules/grunt-cli/bin/grunt test"
  }`

Because of this **npm run build** command is failing in windows environment with following error:

`grafana\grafana>npm run build
(node:10732) fs: re-evaluating native module sources is not supported. If you ar
e using the graceful-fs module, please update it to a more recent version.

> grafana@4.2.0 build D:\VishalGanjare\DevOpsPlatform\CodeRepo\GIT\GrafanaDev_20
170502\src\github.com\grafana\grafana
> ./node_modules/grunt-cli/bin/grunt

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\146414\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.2.0 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grafana@4.2.0 build script './node_modules/grunt-cli/bin/
grunt'.
npm ERR! This is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:`

If the package.json script section is changed to previous version (no absolute path), **npm run build** goes through.
`"scripts": {
    "build": "grunt",
    "test": "grunt test"
  }`

Thanks,
Vishal

**Comment by torkelo** [comment]
building from source guide does not mention "npm run build", think that is only used on the CI server where grunt is not installed in global scope.

http://docs.grafana.org/project/building_from_source/

**Comment by Ultraseamus** [comment]
I'm seeing this same error, except the build instructions you linked to now *do* mention "npm run build".

> ./node_modules/grunt-cli/bin/grunt

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.5.2 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 1
