### ISSUE TITLE
Button to toggle alert rules status

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82669]
### Discussed in https://github.com/grafana/grafana/discussions/67721

<div type='discussions-op-text'>

<sup>Originally posted by **jufy111** May  3, 2023</sup>
Hi,

I'd love the ability to quickly enable/disable the alert rules in the Web-UI without having to create a silence each time. 
It would make sense to have a toggle button under the actions (see image below).

![image](https://user-images.githubusercontent.com/40817638/235910417-334c9614-73f6-465f-8613-3432f6a95b45.png)
</div>

**Comment by armandgrillet** [comment]
We have both pause and silence buttons available from the alert rules list in Grafana 11.1 and more recent versions:

![Image](https://github.com/grafana/grafana/assets/2117580/3b2e536b-a768-4b41-a448-e6e4d3814c67)

![Image](https://github.com/grafana/grafana/assets/2117580/f29806a8-406c-4b7d-abf3-7000a2742352)
