### ISSUE TITLE
[FeatureRequest] Variables - Add new time range template variable type

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [grafana/grafana#8267]
# Request new Template Variable Type - "Time"

Following the thread on community.grafana:
`https://community.grafana.com/t/feature-request-time-template-variable-type/691`
I'm requesting a new Template Variable Type to allow us to specify times.

This is to allow us to query data outside the Dashboard's main time filter, like compare to last year's Black Friday, to an arbitrary time like a previous Performance Test, or...

# Proposal
Template Variable Type of "Time",
Then somewhere a DDL to choose from sub-type:

1. Literal
2. TimeShift
3. UserChosen

**# 1** the templated variable specifies exactly what time we're comparing against.
Ex: BlackFridayStart = '2016-11-26 18:00:00' | BlackFridayEnd = '2016-11-26 24:00:00'

**# 2** the variable specifies a shift against the currently selected time period in the Dashboard main time selector.
_(kind of made redundant by the "Time range" tab on the Panels, but I feel this actually makes more sense)_
Ex: LastWeekStart = $MainTimeFilterEnd -7d -2h & LastWeekEnd = $LastWeekStart + 2h

**# 3** in the variable selection area, a time-selector appears for the user to choose a time.
Ex: select start&stop time of a performance test conducted 2 days ago to compare to today's performance test.

**# ???** possibly, also make the variable _(ex: "$TimeFrom")_ expand into:
- $TimeFrom_InfluxDB
- $TimeFrom_ElasticSearch
- $TimeFrom_ISO123
- ...
To allow us to use those dates in the likes of links to ElasticSearch, etc, thus potentially also solving this request:
`https://github.com/grafana/grafana/issues/1909`

**Comment by hoerup** [comment]
I'd like this one as well

We are using grafana to render data from different test cases, where the user select a testcase ID from normal variable. But then the user has to find out manually the timeperiod where this particular testcase has data - it would be nice if the default timeperiod was a variable that could be defined by a query as well

**Comment by ssharma555** [comment]
I am also looking for this and would be a super useful feature to have.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
