### ISSUE TITLE
[Bug] Empty report when generation takes a bit longer than expected

### ISSUE THREAD

**Issue by dlsniper** [grafana/grafana#8268]
- What Grafana version are you using?
 Grafana v4.2.0 (commit: 349f3eb)

- What datasource are you using?
ElasticSearch 5.1

- What OS are you running grafana on?
Amazon Linux latest

- What did you do?
I've created an API token and queried a dashboard API in order to produce a graph.

- What was the expected result?
I've expected to see the actual graph

- What happened instead?
![empty-report](https://cloud.githubusercontent.com/assets/607868/25613115/fe5e9f6c-2f24-11e7-9093-a617edf97ac5.jpg)

Unfortunately I can't give you more information on this but I can tell you that I can reproduce this constantly.

What I expect is that whenever I query the API to produce an image for a graph I'll get back that image, not an empty image with a loading circle on it. The graph loads when I check the dashboard in the UI, even if it takes about 25 seconds to get it. I've tried adding a ` &timeout=30 ` parameter to force the timeout to be a bit longer but nothing changed (I guess it's not supported?). Per #2419 it seems that there was a decision to have this capped at 10 seconds but the data that I'm aggregating over to produce that report is on the large side so it will definitely take me a lot more than 10 seconds to get it back.

Is there something that I'm missing on how I'm doing the query?

Thank you.

Edit:

Here's what I get in the logs when I call the URL: http://dashboard-host/render/dashboard-solo/db/dashboard-name?orgId=1&panelId=2&from=1493642166872&to=1493728566872&width=1800&height=700&tz=UTC%2B01%3A00

```
t=2017-05-02T12:36:35+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/dashboard-name?orgId=1&panelId=2&from=1493642166872&to=1493728566872&width=1800&height=700&tz=UTC%2B01%3A00"
t=2017-05-02T12:36:46+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/_msearch status=502 remote_addr=127.0.0.1 time_ms=10.222µs size=0
```

If it helps, the ElasticSearch query but I've seen this happening for all requests that take more than 10 seconds to be processed:

```
Query: *, Metrics: Percentiles(request_time, 95, 99), Group by: Date Histogram(time), Interval: 5m
```

I'm using a proxied access to ES configuration, in case it's relevant.

Unfortunately I can't provide a lot more information as to exactly what happens.

**Comment by daniellee** [comment]
What's the exact API call you are using? And can you include the error from the Grafana logs as well please.

**Comment by dlsniper** [comment]
Hi @daniellee, I've updated the issue at the end of it with the required details. Hope it helps.

**Comment by torkelo** [comment]
PNG rendering has timeout (hardcoded) set to 10 seconds, after that the panel image is rendered.

There is an open feature request to have a timeout option:
https://github.com/grafana/grafana/issues/5728

**Comment by torkelo** [comment]
The phantomjs script that captures the image:
https://github.com/grafana/grafana/blob/master/vendor/phantomjs/render.js#L62

The go code that launches phantomjs:
https://github.com/grafana/grafana/blob/master/pkg/components/renderer/renderer.go#L78

**Comment by dlsniper** [comment]
Thank you!
