### ISSUE TITLE
Telegram topics support

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82692]
### Discussed in https://github.com/grafana/grafana/discussions/68527

<div type='discussions-op-text'>

<sup>Originally posted by **hoboroten** May 16, 2023</sup>
Hi.
Recently Telegram added support for Topics in Groups in Bot API. Will it be added to Telegram Alert Channel configuration? As far as i can see - there must be an opportunity to set message_thread_id parameter.</div>

**Comment by thomasvnl** [comment]
This feature seems to be already implemented in Grafana 11 but is also broken.

**Comment by grobinson-grafana** [comment]
@thomasvnl can you open an issue for this with more information so we can take a look? Here is a bug we fixed last month https://github.com/grafana/grafana/issues/84296. Is this the issue you are referring to?

**Comment by KaplanSarah** [comment]
Closing this issue as stale.
