### ISSUE TITLE
Customize body of webhook contact point in alerting

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82696]
### Discussed in https://github.com/grafana/grafana/discussions/68158

<div type='discussions-op-text'>

<sup>Originally posted by **Helloworld-can** May  9, 2023</sup>
Hello,

Was hoping if there's  way we can achieve this use case within Grafana.

Idea is to trigger Webhook(with Body) event whenever a panel goes in Alerting state.

Was hoping if anyone has been able to achieve this?

Type: Grafana On-Prem
version: 9.2.1
Alerting Type: Unified Alerting
Alert Manager: Grafana</div>

**Comment by armandgrillet** [comment]
Dupe of https://github.com/grafana/grafana/issues/6956
