### ISSUE TITLE
Grafana - Elasticsearch compatibility

### ISSUE THREAD

**Issue by adamantio87** [grafana/grafana#8269]
I'm using grafana 4.1 running on Linux and Elastic Search 1.5 and I'm getting this error: "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[7QY_l2tOQA2D-SNx3DhotQ][logstash-syslog-2015.10.18][0]: SearchParseException[[logstash-syslog-2015.10.18][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{\"size\":0,\"query\":{\"bool\":{\"must\":[{\"range\":{\"@timestamp\":{\"gte\":\"1493113525180\",\"lte\":\"1493718325180\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"

Is there any compatibility problem between Grafana 4.1 and this ES release?

**Comment by torkelo** [comment]
Grafana 4.x only supports Elasticsearch 2.x and 5.x, for 1.4-1.7 you need use Grafana 3.x
