### ISSUE TITLE
[Feature Request] Download data from Table panels

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [grafana/grafana#8271]
# Feature Request - Download data from Table panels

Requesting feature to download the data being observed in Table Panels (maybe also from graphics?). Like the similar-functionality option in Kibana.

Often I want to download the data I'm seeing in a table as CSV so we can go do all kinds of gimmicks with it in a spreadsheet program.

**Comment by torkelo** [comment]
you can export table data to CSV already:
![image](https://cloud.githubusercontent.com/assets/10999/25616280/05c5b012-2f3c-11e7-97c2-269d259cc3cb.png)

**Comment by PauloAugusto-Asos** [comment]
@torkelo 
Thanks. I was thinking it was quite strange for such a useful feature to not exist but I couldn't find it anywhere and searching (googling) for that just ran into unrelated stuff.
