### ISSUE TITLE
[Bug] Apostrophe in Influx Tag - 400 Bad Request

### ISSUE THREAD

**Issue by dynek** [grafana/grafana#8272]
Please include this information:
- What Grafana version are you using?
4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Docker Container on a Linux host

- What did you do?
Used an apostrophe in a tag value (Cage d'Escaliers) and as Grafana surrounds the value with apostrophe it breaks with a 400 (Bad Request), apostrophe should be escaped.

- What was the expected result?
Return value targeted by query

- What happened instead?
400 (Bad Request)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
``` 
GET /api/datasources/proxy/3/query?db=fibaro&q=SHOW%20TAG%20KEYS%20FROM%20%22fibaro%22%20WHERE%20%22section%22%20%3D%20%27Pi%C3%A8ces%20communes%27%20AND%20%22room%22%20%3D%20%27Cages%20d%27escaliers%27&epoch=ms HTTP/1.1
Host: grafana:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Referer: http://grafana:3000/dashboard/db/5-home-automation?refresh=1m&orgId=1&panelId=35&fullscreen&edit
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=2a7cbda41a0d388f; grafana_user=admin; grafana_remember=3ea2069ff46000a55e54b850ccac29b4844d95364dad519d
```
```
HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Length: 98
Content-Type: application/json
Date: Tue, 02 May 2017 10:48:59 GMT
Request-Id: f2a4a8a7-2f24-11e7-bf08-000000000000
X-Influxdb-Version: 1.2.2

{"error":"error parsing query: found escaliers, expected ; at line 1, char 87"}
```

**Comment by dynek** [comment]
Didn't have time yet to check it and submit a PR. Regular committers will most likely do it much quicker than I would :-)

**Comment by dynek** [comment]
this fixes SHOW TAG KEYS/VALUES:
https://github.com/dynek/grafana/commit/17f562f56e5377724445ae3788228ba0a2e2ad27

looking for the GET /api/datasources/ query now

**Comment by dynek** [comment]
Ping - should be really simple to fix. Would anyone be able to point me to the right file?
I'm unable to find where to escape quotes for queries.

**Comment by dynek** [comment]
OK too bad - wanted to help but couldn't get help almost a year later. Let's leave it like that!

**Comment by torkelo** [comment]
sorry that we did not give you more feedback to so you could fix and submit PR for this. We will try to improve issue correspondence in future and be more responsible.

**Comment by dynek** [comment]
Still not fixed in 5.2.3 - more than willing to submit a PR if someone points me into the right direction.

**Comment by dynek** [comment]
Still not fixed in 5.4.0 - more than willing to submit a PR if someone points me towards the right direction.

**Comment by bergquist** [comment]
It needs to be fixed in https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/query.go#L66 and in the frontend as shown earlier in this issue.

**Comment by dynek** [comment]
@bergquist doesn't work for me. Is a `bra run` sufficient to rebuild the backend and have the modification applied?

**Comment by bergquist** [comment]
That should be enough. Sometimes changes are picked up by the filewatchers so you can try running `bra run`
