### ISSUE TITLE
Alert export limited to organization admins

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82735]
### Discussed in https://github.com/grafana/grafana/discussions/66394

<div type='discussions-op-text'>

<sup>Originally posted by **mahradk** April 12, 2023</sup>
Hey,

I was wondering if it is possible to allow export of alerts with Editor/Viewer role as this is an standard feature of the dashboards.

As the [provisioning API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-get-alert-rule-exportspan-export-an-alert-rule-in-provisioning-file-format-_routegetalertruleexport_) is the only way one could get to unified alert rule JSONs.
If an `Editor` that has created an alert wants to export their alerts for provisioning, they have to contact an `Org. Admin`.

Would it be possible to update `alertingReaderRole` and `alertingWriterRole` of [ngalert/accesscontrol](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/accesscontrol.go#L135-L174) to allow `ActionAlertingProvisioningRead` and `ActionAlertingProvisioningWrite` respectively?</div>

**Comment by yuri-tceretian** [comment]
PR https://github.com/grafana/grafana/pull/76082 resolved this problem, and now users with regular permissions can access export endpoints.
