### ISSUE TITLE
Add intrinsic fields to TraceToMetrics

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82734]
### Discussed in https://github.com/grafana/grafana/discussions/65336

<div type='discussions-op-text'>

<sup>Originally posted by **faustodavid** March 27, 2023</sup>
Grafana allows us to link traces to metrics by mapping span tags to a predefined metric query.
https://grafana.com/docs/grafana/latest/datasources/tempo/#provision-the-data-source

The feature works great but misses the intrinsic fields, which are default dimensions when using the Tempo Metrics Generator.

I suggest adding an extra check to the expression to look for `$__name`, `$__status`, and `$__kind`. 

https://github.com/grafana/grafana/blob/a423c7f22ebbc491325ab15c3434e3b95dc165d0/public/app/features/explore/TraceView/createSpanLink.tsx#L372</div>

**Comment by joey-grafana** [comment]
Hey @faustodavid, thanks for your query.

We provide several query variables that can be mapped in the query. 

You can get for example, the span/trace name, the span/trace id, or the span tags (which contain status, kind etc). More details in our [docs](https://grafana.com/docs/grafana/next/datasources/tempo/configure-tempo-data-source/#custom-query-variables).
