### ISSUE TITLE
[Feature request] Series specific override: float legend to right (as in display on second y-axis)

### ISSUE THREAD

**Issue by Finkregh** [grafana/grafana#8273]
- What Grafana version are you using?
v4.2.0 (commit: 349f3eb)
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
OpenSuse
- What did you do?
try to float legend of some metrics to the right (as when choosing the secondary y-axis)
- What was the expected result?
this is only possible when i set the second y-axis
- What happened instead?
no possible to do that w/o the second y-axis

screenshot single y-axis:
![one-y-axis](https://cloud.githubusercontent.com/assets/518090/25616279/0549ee32-2f3c-11e7-9e9f-bc087d7ff5e7.png)

screenshot two y-axis:
![secondary-y-axis](https://cloud.githubusercontent.com/assets/518090/25616294/13ab2f0e-2f3c-11e7-9821-b534eff11d8d.png)

i'd like to have the "legend floats to the right" aspect of the "use secondary y-axis" as a separate feature.

**Comment by torkelo** [comment]
I think this option only makes sense when paired with the second-y axis. 

So far no one has requested this. Trying to keep feature creep low and not add a feature for every possible use case so closing this as it will very likely not be implemented (really sorry, but if we add every feature requested Grafana is going to become a bloated unmaintainable mess)
