### ISSUE TITLE
Support multiple datasources for same alert rule

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82758]
### Discussed in https://github.com/grafana/grafana/discussions/66125

<div type='discussions-op-text'>

<sup>Originally posted by **kthommandra** April  6, 2023</sup>
Dashboards support datasource as a variable so that the same panel can be targeted to different clusters.

Alert rule creation does not seem to offer using a set of datasources. Thus an alert needs to be duplicated for each cluster.</div>

**Comment by armandgrillet** [comment]
We won't do that for alerts, multi-dimension alerting is meant to not need that as you have one alert rule per serie. You can do this using Terraform provisioning.
