### ISSUE TITLE
Feature Request: Ability to use the alert summary as title for the Microsoft Teams notification

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82759]
### Discussed in https://github.com/grafana/grafana/discussions/66098

<div type='discussions-op-text'>

<sup>Originally posted by **sdaus** April  6, 2023</sup>
Currently, configuring the summary of an alert as the title for the Microsoft Teams notification in Grafana Alerts requires users to write a custom title with Go, which can be a complex and time-consuming process. To simplify this, it would be great to be able to retrieve specific information from the alert (such as the summary) using something like an environment variable or some other user-friendly method.</div>

**Comment by JelenaLahtina** [comment]
Does anyone successfully uses optional microsoft teams setting - templated title of the teams message? 

Whatever I do and put inside the template, add it to contact point and test it I receive empty teams alerts

**Comment by armandgrillet** [comment]
We do support this in Grafana: [here](https://github.com/grafana/alerting/blob/f1abba3e2067157bd0ff0258ff7f9d5e9bbbe158/receivers/teams/teams.go#L46) and [there](https://github.com/grafana/alerting/blob/f1abba3e2067157bd0ff0258ff7f9d5e9bbbe158/receivers/teams/teams.go#L292). We are [improving the templating editor](https://github.com/grafana/grafana/pull/84798) and [have some docs with examples](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/create-notification-templates/#template-the-subject-of-an-email).

The capacity to have variables coming from old alert notifications would be great, please reopen this issue if our improvements are not enough.
