### ISSUE TITLE
shall we add permission control for contact point and notification policy

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82769]
### Discussed in https://github.com/grafana/grafana/discussions/65879

<div type='discussions-op-text'>

<sup>Originally posted by **bossjie** April  3, 2023</sup>
as we have permission setting for alert rules to defend wild changing by unallowed users.
how about contact point and nofitication policy?  normal editors now are allowed to change/delete them
aka  protect partial cannot cover the protection.</div>

**Comment by armandgrillet** [comment]
RBAC for all alerting objects is in the work.
