### ISSUE TITLE
Google Cloud Monitoring (Stackdriver) open source plugin - Add PromQL support as a querying language

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82763]
### Discussed in https://github.com/grafana/grafana/discussions/64349

<div type='discussions-op-text'>

<sup>Originally posted by **dsaintilma-flinks** March  7, 2023</sup>
Hi,

Since Google Cloud Monitoring plugin/datasoure now supports PromQL, it would great to have this querying language added as an option for those of use who prefers using that language.

Thanks!</div>

**Comment by asimpson** [comment]
This was closed via #73503
