### ISSUE TITLE
Do simple mathematical operation on the data received from OpenTSDB database and visualize it in graph

### ISSUE THREAD

**Issue by NitinRanjan** [grafana/grafana#8276]
- What Grafana version are you using? 4.2
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? Ubuntu

**Comment by torkelo** [comment]
With OpenTSDB 2.3 I think they added Graphite like transformation functions so the need to do this in Grafana should not be as high. 

If you want to do time series transformations in Grafana you will have to wait for this feature (no ETA):
https://github.com/grafana/grafana/issues/3677
