### ISSUE TITLE
Feature Request: Hide silenced alerts in alert list visualization

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82772]
### Discussed in https://github.com/grafana/grafana/discussions/65449

<div type='discussions-op-text'>

<sup>Originally posted by **sdaus** March 28, 2023</sup>
I would like to request a feature that allows me to hide silenced alerts in the alert list visualization. Currently, there is no option to hide silenced alerts, which makes it difficult to quickly identify active alerts.</div>

**Comment by hpwjnijs** [comment]
We also like to have this feature. Solution is already made here:  https://github.com/grafana/grafana/issues/43855
Please implement.

**Comment by gelicia** [comment]
Closed as a duplicate of https://github.com/grafana/grafana/issues/43855
