### ISSUE TITLE
Feature Request: XY Chart Time Series Units and Axis Scaling

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82786]
### Discussed in https://github.com/grafana/grafana/discussions/66073

<div type='discussions-op-text'>

<sup>Originally posted by **blakeroberts-wk** April  5, 2023</sup>
The XY Chart should support displaying custom units and axis scaling for both the x and y axis.

A relatively common use case for both of these features is in tail latency graphs.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/28708077/230225217-08c62b67-29e4-4147-b86f-7fc4fcc679c4.png">

In this example, the x axis units should be displayed as a percentage and scale non-linearly to "zoom" into the "tail" latency (90% - 99.99...%) and the y axis units should display in milliseconds. Scaling the y axis non-linearly may have similar benefits.

Epic related to the XY Chart feature release: https://github.com/grafana/grafana/issues/61734</div>

**Comment by leeoniya** [comment]
this now works with `autoMigrateXYChartPanel` by using a field override
