### ISSUE TITLE
Logs: Better separation of timestamp and log line

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82795]
### Discussed in https://github.com/grafana/grafana/discussions/64390

<div type='discussions-op-text'>

<sup>Originally posted by **svennergr** March  8, 2023</sup>
![image](https://user-images.githubusercontent.com/8092184/223697110-c74bc05c-b499-44fc-b527-c01c6739e8a6.png)

Log lines and timestamps are currently displayed in the same way, with just a little space in between them. That might make it hard to read and focus on one of the two if there are many loglines.

Let's use this issue to discuss possible scenarios how to solve this and create a better separation of timestamp and logline. </div>

**Comment by matyax** [comment]
Sorry @svennergr . Maybe try table view?
