### ISSUE TITLE
[Feature request] Custom/One-off annotation data

### ISSUE THREAD

**Issue by tehdirector** [grafana/grafana#8279]
I find myself frequently wanting to annotate when something happens (or happened) on a. graph outside of the datapoint I'm collecting. This is usually for something that is not easily collectible as a data point.

I would love to have the ability to create custom one-off annotations. This could be as simple as adding an annotation "data source" as custom and giving a way to input Data and Date information for the custom point.

Examples:

Starting Maintenance, 2017-05-03 00:00:00
Maintenance Completed, 2017-05-03 00:10:00
Power Outage, 2017-01-01 01:23:45
Power Restored, 2017-01-01 01:45:45
Earthquake, 2017-02-02 15:00:00
Etc.

It would be nice to be able to add one new "Annotation" but to be able to add multiple data points to this custom annotation.

**Comment by daniellee** [comment]
You're in luck. This should be coming soon, probably in the 4.4.0 release in a month or so: #1286
