### ISSUE TITLE
[Feature Request] enhance alerting to lookback, trend, and possibly future predictions

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82802]
### Discussed in https://github.com/grafana/grafana/discussions/63830

<div type='discussions-op-text'>

<sup>Originally posted by **Sam-H101** February 28, 2023</sup>
From using other alerting tools, a few examples that standout would be:

numerical alerting:
- look back n number of values and if its a steady increase / decrease alert. (the last n number of values are all increasing or decreasing)
- if the trend of the last time interval is going down at a fast rate, alert
- in the next hour is this value going to be over x. 

non numerical alerting:
- if the last value is "string" alert or if that "string" has appeared n number of times over a time frame

This would be beneficial as we would not need to configure multiple alerting tools to achieve the desired results. It would be time saving if we could have all of the alerts in a single system. </div>

**Comment by armandgrillet** [comment]
Closing in favor of https://github.com/grafana/grafana/issues/53443.
