### ISSUE TITLE
Trying to get database query in grafana but unable to find it.

### ISSUE THREAD

**Issue by rajatporwal1** [grafana/grafana#8280]
Hello i am trying to get matrics on grafana dashboard through mysql but unable to find it. 

I install grafana with prometheus along with node_exporter and mysql_exporter. Everything is working correctly with proper port allocation. 
grafana Port: 3000
prometheus port:9090
node Exporter port: 9100
mysql Exporter port: 9104 

also add prometheus datasource in grafana. But i do not know how to pull data through mysql database. 

Please figure this out i am in middle of this. 

Thanks in advance.

**Comment by torkelo** [comment]
please open questions on the community site.

**Comment by rajatporwal1** [comment]
i already checked but did not ind how to write query to get graph in
grafana.

Please provide such link.

**Comment by torkelo** [comment]
https://community.grafana.com

**Comment by rajatporwal1** [comment]
Hello Torkel,

Now i am facing error of "*datasource of prometheus was not found" *
I am attaching image please check and give the solution. Prometheus
datasource is working correctlly.
