### ISSUE TITLE
[Feature request] Delay notifications

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82806]
### Discussed in https://github.com/grafana/grafana/discussions/63939

<div type='discussions-op-text'>

<sup>Originally posted by **haeiven** March  1, 2023</sup>
Hello,

Actually, in your notification policies you have an option "Repeat interval" to prevent being spammed every minute for an alert.

Something cool we could have, is an auto delay for this. after waiting for the Repeat interval once, you can add +X minutes delay to your notification, reducing the spam :)

Exemple Scenario:
00:00 - Alert sent
00:30 - Alert sent
01:10 - Alert sent (+10m delay)
01:50 - Alert sent (+10m delay)
etc...

Best regards,
</div>

**Comment by armandgrillet** [comment]
We're not planning on adding this.
