### ISSUE TITLE
Allow viewers to silence alarms

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82819]
### Discussed in https://github.com/grafana/grafana/discussions/60867

<div type='discussions-op-text'>

<sup>Originally posted by **terrpan** January  2, 2023</sup>
We want to use Grafana as a central GUI to manage alerts with Prometheus alert manager. But right now it does not look like viewers can silence alerts. The editor role is a bit to broad for us to assign to users.</div>

**Comment by armandgrillet** [comment]
We do not believe that viewers should be able to silence things as it would impact others. Grafana Cloud has role-based access control allowing you to create custom roles.
