### ISSUE TITLE
[Feature request] Auto generated units depending on service name

### ISSUE THREAD

**Issue by MarcusCaepio** [grafana/grafana#8281]
Please include this information:
- grafana 4.2.0-beta1
- influxdb 1.2.0-1    
- Ubuntu 16.04.2 LTS

Hi all,
so I am using the following dashboard, which auto generates the graphs for every service in my Icinga2 Environment: https://grafana.com/dashboards/1572
Because the dashboard is generated dynamically, depending on the Host and its Services, I have the problem that metrics for example of a disk check are given in a linear unit like 943289696. Is it possible to let grafana automatically format the output depending on the servicename? When I manually set the graph axis of Server 1, which has e.g. disk as first check (= first graph) to Bytes and then change the server, which has e.g. Cluster as first check = first graph, also the unit is Byte instead of linear or sth. else. It seems not assigned to the service name, but to graph's position. 

Kind Regards,
Marcus

**Comment by torkelo** [comment]
There is no way to do this for repeated panels as the panel template contains the defined unit. 

You will have to modify the dashboard and save it (remove the panel / row repeat), then you can define a unit on every panel as you would like.

**Comment by torkelo** [comment]
Might be possible if the inciga data source returned units for the series.

**Comment by Mikesch-mp** [comment]
Icinga can send the unit as variable :)

**Comment by dnsmichi** [comment]
Just some thoughts:

It is more a backend matter here. The icinga datasource in Grafana actually is InfluxDB, Graphite or PNP where Icinga 2 just dumps the data into.

AFAIK Graphite doesn't allow to store any kind of tags or units, InfluxDB does. PNP has some additional XML templates which are partially exposed through a new API adapter (didn't test it with Grafana though).

Depending on the backend defined in Grafana, you might use additional details to render your dashboards and templates in Grafana. I've never looked into the details though.

Dumping the tags for Graphite into Grafana is currently discussed in icinga/icinga2#5214. InfluxDB allows to enhance the tags already, i.e. by using a custom attribute. We might consider adding the UOM somewhere but please discuss that in an icinga2 feature request.

**Comment by ohrly** [comment]
TLTR: How to get the unit (which is now in the InfluxDB) into the Unit field of the Y-Axis?

The feature of units per metric in the InfluxDB (written thru the InfluxDBWriter) got implemented in 2017 and was included from @dnsmichi in Icinga2 version 2.9 https://github.com/Icinga/icinga2/issues/5627.
I get in InfluxDB the following:
```
influx
use icinga2
select time, service, value, unit, warn, crit from "ping4" where metric =~ /pl/ or metric =~ /rta/ limit 4;
```
time | service | value | unit | warn | crit
---- | ------- | ----- | ---- | ---- | ----
1554277930000000000 | Ping | 0 | **percent** | 5 | 15
1554277930000000000 | Ping | 0.000285 | **seconds** | 0.1 | 0.2
1554277938000000000 | Ping | 0 | **percent** | 5 | 15
1554277938000000000 | Ping | 0.000289 | **seconds** | 0.1 | 0.2

@torkelo How to get this DB information into the Units of Y-Axis?
This would be greatly appreciated by whomever uses Icinga2 + Icinga Web 2+ InfluxDB + Grafana + icingaweb2-module-grafana! Which is a great Combo - looks good and works smooth, except for this problem.
Did I oversee something here? Maybe @Mikesch-mp has some ideas?

The workaround is, adding a graph for every possible unit and mapping the service with https://github.com/Mikesch-mp/icingaweb2-module-grafana to the fitting graph. This is a lot to do with many different service checks. Also I like to use repeating panels for metrics and in the example you see the Ping service has different units for the different metrics. This is a problem for the repeating panel. IMHO: This all could be done by selecting the unit from the unit field. I am totally unfamiliar with the data feeding process of Grafana, but can you make a query for the units (variable?) of some sort? Or grab the unit from the IQL? Just a stupid example:
```
SELECT mean("value"), last("unit") AS "Left-Y-Unit"
  FROM /^$command$/
  WHERE (
    "hostname" =~ /^$hostname$/ AND
    "metric" =~ /^$metric$/ AND
    "service" =~ /^$service$/
  ) AND $timeFilter
  GROUP BY time($__interval), "metric", "service", "hostname" fill(none)
++ Format as "Time series"
++ Alias by "$tag_hostname $tag_service $tag_metric"
```
![example](https://www.dropbox.com/s/lgy15rvl2btn6lx/IQL-select-unit-for-Y-Axis.png?raw=1)
Thanks in advance!

**Comment by MarcusCaepio** [comment]
You have to create different panels for each service. In the panel you can set a metric. These panels have to be linked to the icingaweb2 grafana module. There is no way to auto apply metrics. I also use icinga2+web+influx+grafana. My way to solve this was to use the tag by metric option and create panels for unique services. As I am OOF right now (TGIF) I cannot give you an example.

**Comment by ohrly** [comment]
Yeah, I don't want to create a panel per service, that's why I ask for this feature. :wink:

**Comment by ohrly** [comment]
@torkelo Can you share your opinion about taking the unit from the database?
