### ISSUE TITLE
Explore: Hard to compare 2+ values in graph in Explore

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82813]
### Discussed in https://github.com/grafana/grafana/discussions/61621

<div type='discussions-op-text'>

<sup>Originally posted by **ivanahuckova** January 17, 2023</sup>
Blocked by https://github.com/grafana/grafana/issues/61615

Currently Explore's graph tooltip is showing only 1 value in tooltip (the hovered-over one) which makes it hard/impossible to compare multiple values in time. 

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/30407135/212899383-cc6e1230-8ef7-45ff-b066-b82004d06fd8.png">

The possible solution could be using `multi` tooltip that shows multiple values, but in current implementation, tooltip blocks large part of graph and is in the way. 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/30407135/212900576-39b1caa9-ad78-4f4f-8e17-29189e34d9b8.png">

**Environment**:
- Grafana version: 9.3.0</div>

**Comment by gelicia** [comment]
We had a lot of discussion here https://github.com/grafana/grafana/pull/61432

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
