### ISSUE TITLE
Users actions in Grafana via approval request

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82846]
### Discussed in https://github.com/grafana/grafana/discussions/64651

<div type='discussions-op-text'>

<sup>Originally posted by **laa88rf** March 11, 2023</sup>
Hi.

In my work, a frequent problem is the lack of control of remove alerts, the lack of control over changes in requests in charts, and the change in response time to an alert.
Is it possible to create some kind of Merge Request? As far as I know, this is not the case in the current version.
Thank you.</div>

**Comment by armandgrillet** [comment]
A solution would be to use provisioning, an as-code configuration allows you to have PRs editing/deleting alerts.
