### ISSUE TITLE
Request: Add rate() functions to the alerting toolkit so alerts can be fired based on the slope of a line

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82844]
### Discussed in https://github.com/grafana/grafana/discussions/64175

<div type='discussions-op-text'>

<sup>Originally posted by **pritster5** March  3, 2023</sup>
Shouldn't be too difficult to add. It would be extremely useful to fire an alert based on the rate of change of data overtime, as threshold based alerting doesnt apply in many cases. 

E.g.:

![image](https://user-images.githubusercontent.com/7132319/222810987-928a58bd-0b79-4757-9ed9-ceef8bd13105.png)

In the image above, I have an SQS queue displaying it's "Approximate Number of Messages Visible" metric. I would like to be alerted if the slope of the line is not negative over an extended period of time (say for 1hr). </div>

**Comment by armandgrillet** [comment]
Rate has a lot of edge cases, the best is to use the `rate()` function in a Prometheus datasource.
