### ISSUE TITLE
[Bug] metric-segment not able work without mouse

### ISSUE THREAD

**Issue by Gordiychuk** [grafana/grafana#8284]
On last revision https://github.com/grafana/grafana/commit/44f76fdabc2cb997070a9abf2c24f16202b69cae I faced with problem that <metric-segment> not allow fill multiple key-value pair without use mouse. In my plugin after change key i change focus via segment.focus to next value, after change value to next key etc. But if press enter not so fast, focus from metric-segment and control start work very strange. I think we should change subscribe from keydown to keyup. 

Current behaviour:
![current](https://cloud.githubusercontent.com/assets/10699594/25678124/549c2e12-3051-11e7-9f7b-364c39e23a18.gif)

Expected fixed version:
![after_fix](https://cloud.githubusercontent.com/assets/10699594/25678137/61fc0c8a-3051-11e7-96b3-49b64c1d062d.gif)

**Comment by torkelo** [comment]
unable to replicate this with Graphite query editor. 
Test here:
http://play.grafana.org/dashboard/db/graphite-carbon-metrics?panelId=2&fullscreen&edit&orgId=1

Can you replicate the same behavior there?

**Comment by Gordiychuk** [comment]
Yes, I can. I press enter fast enough everything work well, but it not always available. 

![graphite](https://cloud.githubusercontent.com/assets/10699594/25694810/127c19b2-30b9-11e7-8df6-c1c1e5d36699.gif)

**Comment by Gordiychuk** [comment]
@torkelo why keydown more preferable than keyup? I see only one reason, it's down arrow, that allow not press it twice. But in that case we can use different behaviour for enter and down arrow.

**Comment by Gordiychuk** [comment]
Every key/value press enter twice looks also not so cool. Why not listening any char key?, It's allow reduce count press buttons on keyboard and as a result speed up creating graph.

**Comment by torkelo** [comment]
keyup seems slower as you have to wait for release of key. 

Can still now replicate the behavior you show. even if I press down arrow or enter the quickest I can. 

> Every key/value press enter twice looks also not so cool. Why not listening any char key?, It's allow reduce count press buttons on keyboard and as a result speed up creating graph.

twice?  what?

**Comment by Gordiychuk** [comment]
It reproduces only with enter button, not arrow down. 

>>Every key/value press enter twice looks also not so cool. Why not listening any char key?, It's allow reduce count press buttons on keyboard and as a result speed up creating graph.
>
>twice? what?

When focus on button I press first time enter to start typing value after complete I press enter again to change focus to another control, etc.

**Comment by torkelo** [comment]
Sorry, unable to replicate it. when I press enter to select a value I can press enter again right after to trigger the dropdown on the second segment.

**Comment by Gordiychuk** [comment]
If I record screen with press buttons, is it help? I also try different browsers, result the same.

**Comment by torkelo** [comment]
can you describe what's happening and what your doing in more detail? I click on select metric, then type some filter and/or down arrow to focus the item I want, then enter to select the value, then a new segment appears and is given focus, if I press enter again the dropdown opens and I can start typing or press arrow down to select another item.

**Comment by torkelo** [comment]
closing for lack of update / details on how to replicate (and no other reports on this), please update if this is still a big problem for you and if you move details on how to replicate
