### ISSUE TITLE
Alerting: Allow matching of alert status in Notification policies

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82845]
### Discussed in https://github.com/grafana/grafana/discussions/64551

<div type='discussions-op-text'>

<sup>Originally posted by **bentasker** March  9, 2023</sup>
Currently, Notification Policies can only match on labels.

So, for example, I can easily say: Send alerts with `host=foo` to contact `bar`.

However, this will result in all statuses going to `bar` which may not be desirable - `bar` may want to receive `Firing` and `Resolved` but not `DataSourceError`.

As a real-world example, I have the following setup:

* Root notification policy: Send via email
* Notification Policy: match `severity=critical` and send to PagerDuty (to generate a page)

However, if my datasource is unavailable (for example, down for a full filesystem backup) the alert will go to status `DataSourceError` and generate a page.

This might be quite unwelcome at 2am. Mute timings can't be used for this, because you **do** want to receive a page if the thing being monitored is genuinely on fire.

It is possible to override this behaviour on the alert:

![override_state](https://user-images.githubusercontent.com/2900301/224118902-80f0a28c-5928-474c-8124-1854aec59830.png)

But that's not necessarily desirable:

* It means editing every alert *and* remembering to set this on any future alerts
* It'll change the alert reference/key for anything downstream that relies on a consistent label set
* You may still want an email notification to note that the interruption happened

It might be possible to hack something similar together by using a string template to set a label value (using `{{ .Status }}`) but it'd be nice to have a way that's less involved and doesn't require customising every current and future alert.</div>

**Comment by armandgrillet** [comment]
The solution you have described is unlikely to solve your problem and will create new ones regarding how alerts work in the Alertmanager. You should create a notification policy that matches the datasource Error alerts, and then you can either use a mute timing to suppress notifications outside working hours or you can override the timings in the notification policy so that the notification is not sent unless the alert has been firing for a certain period of time.
