### ISSUE TITLE
config.ini should let users choose the navigation title for plugins.

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82866]
### Discussed in https://github.com/grafana/grafana/discussions/62546

<div type='discussions-op-text'>

<sup>Originally posted by **joeblubaugh** January 31, 2023</sup>
The new navigation experience has a configurable set of "sections" on the side. The config setup allows users to choose the section they'd like a plugin's UI to appear in. This is used in the Grafana codebase to put the Oncall plugin inside the "Alerting and Incidents" section:
```go
https://github.com/grafana/grafana/blob/e3b4da2279100ce0f2592175b588b443fb1faa82/pkg/services/navtree/navtreeimpl/applinks.go#L260
```

In that code, plugins can also be configured with a custom title for the nav section. This custom title cannot be configured in config.ini. 

I'd like for users to be able to set a custom title in the config file just as happens in the code. For example, you might have a plugin with a name like "Google Cloud Stackdriver" that provides some UI, but in the nav some users might like to just call it "Stackdriver" to save space.</div>

**Comment by ashharrison90** [comment]
added it to the configurable nav epic
