### ISSUE TITLE
Logs: Download `raw` format

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82864]
### Discussed in https://github.com/grafana/grafana/discussions/61155

<div type='discussions-op-text'>

<sup>Originally posted by **svennergr** January  9, 2023</sup>
Currently logs are downloaded containing stats, labels and timestamps. 
However having a `raw` format, just downloading the plain loglines/entries would be good.</div>

**Comment by matyax** [comment]
Not a priority unless specifically requested.
