### ISSUE TITLE
Provisioning Library-Elements via Filesystem

### ISSUE THREAD

**Issue by saeltz** [grafana/grafana#82881]
Grafana allows to [provision resources](https://grafana.com/docs/grafana/latest/administration/provisioning/) like Dashboards, Plugins, ... via the Filesystem and also allows it to let Grafana reload such resources during runtime via an HTTP endpoint.
Would it be also possible to add the capabilities for [library-elements](https://grafana.com/docs/grafana/latest/http_api/library_element/#create-library-element)?

We're making use of this mechanism already for Dashboards and it would be great to use the same pattern for Library-Elements instead of the HTTP endpoints for creating/updating/deleting the Library-Elements.

_Originally posted by @guusvw in https://github.com/grafana/grafana/discussions/44388_

**Comment by suntala** [comment]
Thank you for your suggestion! We recognize the value of library elements provisioning. However, this part of the code is challenging to maintain, and we’re planning a rework starting with the next major release, which might address similar needs. We appreciate your insights—it’s a valuable addition to the conversation!
