### ISSUE TITLE
Problem export dashboard via api

### ISSUE THREAD

**Issue by contactmat85** [grafana/grafana#8288]
Hi, sorry I am pretty new in grafana, curl and php.
I am trying to export a dashboard via api with php using curl and import.

I tried something like:

`$curl = curl_init(); 	

curl_setopt($curl, CURLOPT_URL,            "https://admin:admin@local.com" );
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$result=curl_exec ($curl);
curl_close($curl);`

but I have:

{{alert.title}}
Docs
Support Plans
Community
Grafana v4.1.2 (commit: v4.1.2)
New version available!

What is that?

Thanks

**Comment by torkelo** [comment]
Must have the wrong api url:
http://docs.grafana.org/http_api/dashboard/#get-dashboard

please use community site for questions

**Comment by contactmat85** [comment]
Thanks but the url is correct:
I am using:
 https://admin:admin@futureboy-********.influxcloud.net/api/dashboard/db/gestoos-ds-dashboard

**Comment by contactmat85** [comment]
Oh my god... sorry... thanks
