### ISSUE TITLE
Hide empty folders from viewers

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82898]
### Discussed in https://github.com/grafana/grafana/discussions/61131

<div type='discussions-op-text'>

<sup>Originally posted by **krzd7** January  9, 2023</sup>
It would be great having an option to hide empty folders from viewers. I'm not sure if there is a way, but I could not find one.</div>

**Comment by joshhunt** [comment]
Thanks for the feedback. We're not going to work on this now, but will keep the feedback in mind for future work...............
