### ISSUE TITLE
Canvas: Button API Editor support PUT requests

### ISSUE THREAD

**Issue by flixr** [grafana/grafana#82891]
**Why is this needed**:

Some APIs use PUT a lot instead of POST.

**What would you like to be added**:

Also add support for PUT additionally to GET and POST.

**Who is this feature for?**

Everyone having APIs using PUT

**Comment by nmarrs** [comment]
Hi @flixr - on closer review the canvas button element api editor already supports `PUT` requests as of v10.3+ :) See [this PR](https://github.com/grafana/grafana/pull/76844)
