### ISSUE TITLE
[Feature request] Shortcut to focus panel

### ISSUE THREAD

**Issue by majkinetor** [grafana/grafana#8289]
Currently there is no obvious way to focus the panel, one must hover with the mouse and then shortcuts like `e` or `v` work. The `<tab>` also doesn't work for me which would be a poor way to focus anyway.

I have few suggestions of how this could work:

1. `<row><number>`  
For example 13 would focus row 1 panel 3.
1. `<alt>+<generated_char>`  
For example, holding alt would draw chars on top of panels: `[  j  ] [  k  ] [  l  ]`. Then pressing k in this case would  focus second panel in a row. This method could allow for panel to have customizable shortcut key in for example General settings.
1. Vim like `j/k` for up and `h/l` for left right. This would be the slowest method, but functional enough since dashboards usually do not have bunch of panels and its intuitive as many other tools support this.

Option 1 would probably be the fastest. Option 2 would provide visual ques which is not bad. If option 2 doesn't use numbers but chars only, even all 3 can coexist.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
