### ISSUE TITLE
Azure Monitor: add Basics Logs API

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82913]
### Discussed in https://github.com/grafana/grafana/discussions/61019

<div type='discussions-op-text'>

<sup>Originally posted by **tkubica12** January  5, 2023</sup>
Azure Monitor data source supports classic API (today called Analytics Logs), but Azure introduced much cheaper option when user need just filtering with no advanced analytics - Basic Logs with limited set of KQL capabilities. Unfortunately, this API endpoint is different. https://learn.microsoft.com/en-us/azure/azure-monitor/logs/basic-logs-query?tabs=api-1

</div>

**Comment by aangelisc** [comment]
Completed in #88025

**Comment by taleena** [comment]
Epic here: https://github.com/grafana/grafana/issues/84944
