### ISSUE TITLE
Show Horizontal scroll bar in graph legend

### ISSUE THREAD

**Issue by jait-23** [grafana/grafana#8291]
Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 
4.2.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Linux
- What did you do?
Trying to display graphs in mobile.
- What was the expected result?
Expected result was, we should get horizontal scrollbar in legend table below the graph panel as it gets hidden due to css issue.
- What happened instead?
Responsiveness of some legends gets hidden when viewed in mobile.
![graphana-legends](https://cloud.githubusercontent.com/assets/23431915/25701572/9f3d1974-30ea-11e7-85a7-6097688dc82d.PNG)

Thanks,
Jait

**Comment by torkelo** [comment]
do you have a screenshot of the problem? The screenshot you provided has no scrollbar but looks like there is no need for one as all rows are visible.

**Comment by jait-23** [comment]
<img width="1029" alt="web-view" src="https://cloud.githubusercontent.com/assets/23431915/25733462/e12e0ef6-3176-11e7-8e26-8b1bd9d5d115.png">
<img width="393" alt="mobileview" src="https://cloud.githubusercontent.com/assets/23431915/25733466/e878a32e-3176-11e7-9b02-c4def868809c.png">

Note: In mobile view, the legends gets hidden and we need a horizontal scrollbar.

**Comment by aocenas** [comment]
This seems to have been fixed in most recent version (6.2.4 and probably even sooner)
![Kapture 2019-06-20 at 16 36 40](https://user-images.githubusercontent.com/1014802/59857654-a3cda500-9379-11e9-8278-760e64ae6fed.gif)
