### ISSUE TITLE
[Bug] Rendered Panel Images includes sidebar after upgrade from 2.6 to 4.2

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#8293]
We have a external process gathering images to feed a external portal. After upgrade from 2.6 to 4.2 images includes sidebar with the same size (height=200px) .Fontsize seems to be the origin of the problem.

¿There is any way to change font size for the rendered objects?

* Before upgrade

![image](https://cloud.githubusercontent.com/assets/5883405/25710782/9389ae8c-30ed-11e7-9750-af68df6f03ea.png)

* After upgrade

![image](https://cloud.githubusercontent.com/assets/5883405/25710869/d93c9868-30ed-11e7-939a-ae27ddd4e86c.png)

Please include this information:

- What Grafana version are you using? 4.2
- What datasource are you using? graphite
- What OS are you running grafana on? redhat 6.2
- What did you do? render 
- What was the expected result? image without sidebar
- What happened instead? a sidebar appeared

**Comment by torkelo** [comment]
yes, looks like a very minor font change that has caused this minor breaking change. 

Sadly there is no option for this and this is the first time someone noticed so adding an option feels unwarranted
