### ISSUE TITLE
grafana-server.service needs to list the database service in the After list

### ISSUE THREAD

**Issue by wyllys66** [grafana/grafana#8294]
Grafana 4.2.0 
Ubuntu 16.04.1

The systemd script for grafana-server currently has a line specifying "After=network-online.target", however we have seen cases where grafana will fail to start if the database service (postgres, mysql, etc) is not running yet.  It would be better if the systemd script waited for the database service before starting.  Adding "postgres" to the list of "After" services would work.

However, because grafana can use a variety of database services, it may be challenging to specify the correct one since the systemd script is static and not dependent on the local configuration.

**Comment by torkelo** [comment]
already fixed, will be included in next release:
https://github.com/grafana/grafana/blob/master/packaging/deb/systemd/grafana-server.service#L6

https://github.com/grafana/grafana/pull/7903

**Comment by wyllys66** [comment]
excellent, thanks.
