### ISSUE TITLE
Support separate failing and succeeding conditions for alerts

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82954]
### Discussed in https://github.com/grafana/grafana/discussions/47181

<div type='discussions-op-text'>

<sup>Originally posted by **leo60228** January  7, 2021</sup>
**What would you like to be added**: Support for specifying separate failing and succeeding conditions for alerts. For example, an alert could trigger when a value goes above 100, and then go back to normal once it goes below 90. This is similar to #6202, but that was ambiguous between this and debouncing.

**Why is this needed**: This would allow further control over some types of flapping alerts. Debouncing is able to prevent an alert for going above 100 from repeatedly triggering for this example:
![image](https://user-images.githubusercontent.com/8355305/103925522-ab80a600-50e5-11eb-8937-50846486482a.png)

However, this allows preventing this from repeatedly triggering:
![image](https://user-images.githubusercontent.com/8355305/103925566-be937600-50e5-11eb-8380-8c0738ca3dd3.png)

While in many cases one solution will work for both, a combination of the two is necessary to cover all cases.</div>

**Comment by armandgrillet** [comment]
This has been done: https://github.com/grafana/grafana/pull/70998
