### ISSUE TITLE
Docs feedback: reference/dashboard.md

### ISSUE THREAD

**Issue by UncleBarney** [grafana/grafana#8296]
Dear Grafana team,

I have been working on a tool to dynamically generate grafana dashboard using terraform based on user inputs. And i have been referencing the [JSON Model](http://docs.grafana.org/reference/dashboard/) official documentation.

Although i was able to get it working in the end, the lack of details in the JSON models definitely caused many confusions during the implementation.

Please kindly add better documentation since it will hugely benefit the developers and community.

**Comment by daniellee** [comment]
@UncleBarney anything that you learned that could add to the docs for JSON Model in a Pull Request?  We are currently trying to update docs ([see the recent commit history](https://github.com/grafana/grafana/commits/master/docs) but any help would be much appreciated!

Here is the markdown document: 

https://github.com/grafana/grafana/blob/master/docs/sources/reference/dashboard.md

**Comment by oddlittlebird** [comment]
@UncleBarney, can you please add details? What would have helped you?

**Comment by oddlittlebird** [comment]
No response in over six months. Please reopen if this topic is still insufficient: https://grafana.com/docs/grafana/latest/reference/dashboard/
