### ISSUE TITLE
how to build query in Grafana?? 

### ISSUE THREAD

**Issue by jhagaurav026** [grafana/grafana#8297]
I am using grafana on localhost:3000 and datasource - promotheus running on localhost:9090 and node_exporter running on localhost:9100 , mysqld_exporter running on localhost:9104  all things are running succesfully actually i would like to know that how to execute query in grafana i have a table of agent i want to fetch total no agent how to build query in grafana please ellaborate @torkelo  @daniellee

**Comment by torkelo** [comment]
read the Prometheus query docs :) 

https://prometheus.io/docs/querying/basics/

**Comment by jhagaurav026** [comment]
I read all the docs but i can't understand the docs. So please tell me what is the query formation in grafana. 
in doc it's all about installation but i need to know graphical data of my sql database in grafana. 

Thanks in advace
