### ISSUE TITLE
[Feature Request] Plugin version dropdown.

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82974]
### Discussed in https://github.com/grafana/grafana/discussions/67294

<div type='discussions-op-text'>

<sup>Originally posted by **TheFern2** April 26, 2023</sup>
I am wondering if this has been suggested or talked about before.  We are running into an issue where a plugin is updated too often and sometimes installing the latest introduces breaking changes. Is there a possibility of providing a drop down to select a version of a plugin.</div>

**Comment by sympatheticmoose** [comment]
Looking at adding this as part of plugin installation improvements, but will create a new issue to cover it.

**Comment by dreddy-work** [comment]
Hi @sympatheticmoose , can you point me the issue/pr where this was implemented?

**Comment by sympatheticmoose** [comment]
@dreddy-work sure - https://github.com/grafana/grafana/pull/93922 was the initial PR i believe. You can install a specific version via the version history tab in the plugin details page i.e. `/plugins/<plugin-id>?page=version-history`
