### ISSUE TITLE
[Feature Request] Pause alerts from graph panel

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82983]
### Discussed in https://github.com/grafana/grafana/discussions/36997

<div type='discussions-op-text'>

<sup>Originally posted by **d-shi** June 26, 2018</sup>
Right now it seems you can only pause alerts from the alerting page, which does not show you the dashboard name or the data source for the alert rules in the list. We have essentially duplicate dashboards/alerts for multiple kubernetes clusters, which means the alert rules in the alerting page have identical names, and there's no way to tell which one belongs to which cluster without clicking through to graph panel.

It would be really nice to be able to click the heart icon on the graph panel itself to configure the alert rule status.
</div>

**Comment by armandgrillet** [comment]
We don't think we should do this. We have better interactions between panels and alert rules now.
