### ISSUE TITLE
[Feature request] InfluxDB group by time and $__interval math

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#8299]
Please include this information:
Grafana 4.2.0
InfluxDB 1.2.2

Scenario:
Im trying to create a graph with two merics.
* a mean metrics with  group by time of auto ($__interval)
* same mean metrics but with group by time of 4 times the interval (based on auto)

I can't figure out any way to do this without hardcoding the interval to a fixed value, but then it won't work when the timescale changes.

What I would love to see is the ability to do .....group by time(4 * $__interval)
This def need to be "pre-processed/calculated" before sending the query to Influx.

**Comment by torkelo** [comment]
this is not easy to do and would break some conventions (the templating is just string interpolation, the math left for InfluxDB to evaluate). 

So you will have to request this from influxdb. 

You could create 2 `Interval` variables with an auto option that defined 4 times as few steps and use those two different variables as a parameter to group by time. But 100% sure you can have 2 interval variables with auto mode have have them behave as you expect so might not work.

**Comment by joakimberglund** [comment]
Thanks for the quick answer (as usual)

Tried it, and sadly it doesn't work. And as you said it works fine with 2 interval variables but not with 2 on auto. It looks like the auto calculation shares some vars internaly since if I change one it affects the other also..
(would have been good enough for me)
