### ISSUE TITLE
Log Analytics throttling handling mechanism

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82994]
### Discussed in https://github.com/grafana/grafana/discussions/49267

<div type='discussions-op-text'>

<sup>Originally posted by **johnnyfeldman** May 19, 2022</sup>
Hi All,
When using Log Analytics data source, it actually uses a specific SPN to run the query. All users of the dashboard are sharing this SPN.
Azure has throttling policies causing the SPN to get throttled and thus causing all the users to experience timeouts and not working dashboards. Even with most efficient queries, there is no way to avoid throttling since number of concurrent queries are part of the policy, meaning that multiple users working with the same dashboard will eventually get throttled. 
I want to suggest a feature where a dashboard developer can provide multiple accounts and the data source will pick a different one each time it runs a query and also will detect response codes that indicates throttling had occurred to the account and switch automatically to another account.

Thank you,
Johnny.
</div>

**Comment by aangelisc** [comment]
Closing this as user-based authentication and the changes made in #86320 should alleviate this problem
