### ISSUE TITLE
Allow alert evaluation based on future data

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#83004]
### Discussed in https://github.com/grafana/grafana/discussions/37012

<div type='discussions-op-text'>

<sup>Originally posted by **glindsay78** May  9, 2019</sup>
**What would you like to be added**:
It would be nice if the alert engine was able evaluate rules using future data (e.g forecasts). Currently the query option only allows a time range from the past to now e.g query(A, 15m, now). Ideally it would allow 'now+X' queries e.g query(A, 15m, now+48h) or query(A, 15m, 48h).

**Why is this needed**:
To accommodate other (non sys-admin) data use cases for Grafana where forecast data is being displayed (e.g meterological) and alerts are requested based on this data, to allow warnings ahead of time rather than afterwards. 
An example use case in shipping would be a wind forecast alert for a container crane so that if the wind forecasts are over a certain threshold, an alert is generated and operational impacts can be assessed.

Thanks for an awesome product!</div>

**Comment by armandgrillet** [comment]
We have forecasts now: https://grafana.com/docs/grafana-cloud/alerting-and-irm/machine-learning/set-up/tutorial/
