### ISSUE TITLE
[Bug] Frequent gaps on all graphs

### ISSUE THREAD

**Issue by dugajean** [grafana/grafana#8300]
- What Grafana version are you using?: **4.2.0**
- What datasource are you using?: **Graphite**
- What OS are you running grafana on?: **Ubuntu 14.04**
- What did you do?: **Added graphs to my dashboard on my live server.**
- What was the expected result?: **No gaps in the graphs. There are no visible gaps in the Graphite app.**
- What happened instead?: **Got a lot of gaps in all of my graphs.**
- If related to metric query / data viz: **Not sure.**

<img width="1638" alt="screen shot 2017-05-05 at 14 14 31" src="https://cloud.githubusercontent.com/assets/2448254/25745016/3a27eb1e-319d-11e7-818d-ef574d84c499.png">

There are a lot more graphs on my dashboard, but they're all gapped like that.

**Comment by torkelo** [comment]
what's your null value option (in graph display tab).  Looks like you have periods of null values (no data)
