### ISSUE TITLE
[BUG] regex not working correctly.

### ISSUE THREAD

**Issue by ricard0ff** [grafana/grafana#8301]
- What Grafana version are you using?
4.2.0 0
- What datasource are you using?
graphite
- What OS are you running grafana on?
Ubuntu 12.04.5 LTS
- What did you do?
used the regex "/Z(\d+)/gi" on a dataset[proxy1-z1, proxy1-z2, proxy1-z3, proxy1-z4, proxy1-z5]
- What was the expected result? 
1 2 3 4 5
- What happened instead?
1 2 3
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2017-05-05T12:22:13.724Z",
        "time": 97.3389999999199,
        "request": {
          "method": "GET",
          "url": "http://graphite.<sanitized>.com/metrics/find/?query=stats.servers.proxy*",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Origin",
              "value": "http://10.9.40.90:8080"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Host",
              "value": "graphite.<sanitized>.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-GB,en-US;q=0.8,en;q=0.6"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Referer",
              "value": "http://10.9.40.90:8080/grafana/dashboard/db/regions-status-codes?orgId=1&editview=templating"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [
            {
              "name": "query",
              "value": "stats.servers.proxy*"
            }
          ],
          "cookies": [],
          "headersSize": 517,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Date",
              "value": "Fri, 05 May 2017 12:22:13 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Server",
              "value": "nginx/1.4.6 (Ubuntu)"
            },
            {
              "name": "Vary",
              "value": "Cookie, Accept-Encoding"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, OPTIONS, PUT, DELETE"
            },
            {
              "name": "Content-Type",
              "value": "application/json;charset=utf-8"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "145"
            }
          ],
          "cookies": [],
          "content": {
            "size": 595,
            "mimeType": "application/json",
            "compression": 450,
            "text": "[{\"leaf\": 0, \"context\": {}, \"text\": \"proxy1-z1\", \"expandable\": 1, \"id\": \"stats.servers.proxy1-z1\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"proxy1-z2\", \"expandable\": 1, \"id\": \"stats.servers.proxy1-z2\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"proxy1-z3\", \"expandable\": 1, \"id\": \"stats.servers.proxy1-z3\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"proxy1-z4\", \"expandable\": 1, \"id\": \"stats.servers.proxy1-z4\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"proxy1-z5\", \"expandable\": 1, \"id\": \"stats.servers.proxy1-z5\", \"allowChildren\": 1}]"
          },
          "redirectURL": "",
          "headersSize": 370,
          "bodySize": 145,
          "_transferSize": 515
        },
        "cache": {},
        "timings": {
          "blocked": 1.89799999861862,
          "dns": -1,
          "connect": -1,
          "send": 0.09700000009614995,
          "wait": 94.78900000067372,
          "receive": 0.5550000005314075,
          "ssl": -1
        },
        "serverIPAddress": "10.69.196.9",
        "connection": "1822"
      },

{...}

      REGEX

      {
        "startedDateTime": "2017-05-05T12:22:23.657Z",
        "time": 310.3789999986475,
        "request": {
          "method": "GET",
          "url": "http://graphite.<sanitized>.com/metrics/find/?query=stats.servers.proxy*%7B1%2C3%2C5%7D.*",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Origin",
              "value": "http://10.9.40.90:8080"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Host",
              "value": "graphite.<sanitized>.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-GB,en-US;q=0.8,en;q=0.6"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Referer",
              "value": "http://10.9.40.90:8080/grafana/dashboard/db/regions-status-codes?orgId=1&editview=templating"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [
            {
              "name": "query",
              "value": "stats.servers.proxy*%7B1%2C3%2C5%7D.*"
            }
          ],
          "cookies": [],
          "headersSize": 534,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Date",
              "value": "Fri, 05 May 2017 12:22:23 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Server",
              "value": "nginx/1.1.19"
            },
            {
              "name": "Vary",
              "value": "Cookie, Accept-Encoding"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, OPTIONS, PUT, DELETE"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "196"
            }
          ],
          "cookies": [],
          "content": {
            "size": 1000,
            "mimeType": "application/json",
            "compression": 804,
            "text": "[{\"leaf\": 0, \"context\": {}, \"text\": \"RCDN\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.RCDN\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"SOS\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.SOS\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"acct\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.acct\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"cont\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.cont\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"healthcheck\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.healthcheck\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"invalid\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.invalid\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"obj\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.obj\", \"allowChildren\": 1}, {\"leaf\": 0, \"context\": {}, \"text\": \"tfer\", \"expandable\": 1, \"id\": \"stats.servers.proxy*{1,3,5}.tfer\", \"allowChildren\": 1}]"
          },
          "redirectURL": "",
          "headersSize": 348,
          "bodySize": 196,
          "_transferSize": 544
        },
        "cache": {},
        "timings": {
          "blocked": 2.5949999999284,
          "dns": -1,
          "connect": -1,
          "send": 0.2309999999852197,
          "wait": 307.0589999988444,
          "receive": 0.49399999988946774,
          "ssl": -1
        },
        "serverIPAddress": "10.68.232.5",
        "connection": "1836"
      },
      {
        "startedDateTime": "2017-05-05T12:22:23.657Z",
        "time": 355.7199999995646,
        "request": {
          "method": "GET",
          "url": "http://graphite.<sanitized>.com/metrics/find/?query=stats.servers.proxy*%7B1%2C3%2C5%7D.obj.%7BBAD_METHOD%2CCOPY%2CGET%2CDELETE%2COPTIONS%2CHEAD%2CPOST%2CPUT%7D.*",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Origin",
              "value": "http://10.9.40.90:8080"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Host",
              "value": "graphite.<sanitized>.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-GB,en-US;q=0.8,en;q=0.6"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Referer",
              "value": "http://10.9.40.90:8080/grafana/dashboard/db/regions-status-codes?orgId=1&editview=templating"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [
            {
              "name": "query",
              "value": "stats.servers.proxy*%7B1%2C3%2C5%7D.obj.%7BBAD_METHOD%2CCOPY%2CGET%2CDELETE%2COPTIONS%2CHEAD%2CPOST%2CPUT%7D.*"
            }
          ],
          "cookies": [],
          "headersSize": 607,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Date",
              "value": "Fri, 05 May 2017 12:22:23 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Server",
              "value": "nginx/1.1.19"
            },
            {
              "name": "Vary",
              "value": "Cookie, Accept-Encoding"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, OPTIONS, PUT, DELETE"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "326"
            }
          ],
          "cookies": [],
          "content": {
            "size": 4048,
            "mimeType": "application/json",
            "compression": 3722,
            "text": "[{\"leaf\": 1, \"context\": {}, \"text\": \"200\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.200\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"201\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.201\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"202\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.202\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"204\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.204\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"206\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.206\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"303\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.303\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"304\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.304\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"400\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.400\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"401\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.401\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"403\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.403\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"404\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.404\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"405\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.405\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"408\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.408\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"409\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.409\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"411\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.411\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"412\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.412\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"413\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.413\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"416\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.416\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"422\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.422\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"497\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.497\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"499\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.499\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"500\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.500\", \"allowChildren\": 0}, {\"leaf\": 1, \"context\": {}, \"text\": \"503\", \"expandable\": 0, \"id\": \"stats.servers.proxy*{1,3,5}.obj.{BAD_METHOD,COPY,GET,DELETE,OPTIONS,HEAD,POST,PUT}.503\", \"allowChildren\": 0}]"
          },
          "redirectURL": "",
          "headersSize": 348,
          "bodySize": 326,
          "_transferSize": 674
        },
        "cache": {},
        "timings": {
          "blocked": 3.19900000067719,
          "dns": -1,
          "connect": -1,
          "send": 0.17799999841371994,
          "wait": 351.8630000016861,
          "receive": 0.4799999987876049,
          "ssl": -1
        },
        "serverIPAddress": "10.68.232.5",
        "connection": "1831"
      }
    ]
  }
}

**Comment by daniellee** [comment]
Do you mean regex in the serie name?

I don't think Graphite supports that. See docs for [Paths and Wildcards](https://graphite.readthedocs.io/en/latest/render_api.html#paths-and-wildcards).

For example, a range would work:

stats.servers.proxy1-z[1-5]

![image](https://cloud.githubusercontent.com/assets/434655/25748923/24c84dda-31ad-11e7-9e62-0260c1c3f546.png)

**Comment by ricard0ff** [comment]
Hey @daniellee thanks for getting in touch,

So to give more context I'm trying to build the following:
![screen shot 2017-05-05 at 15 17 04](https://cloud.githubusercontent.com/assets/17491850/25749308/f9bccaaa-31a5-11e7-8fd3-de97f29e7d49.png)

"Do you mean regex in the serie name?"

I was talking about the templating part and not in the series name, normally for that I use '*' or the '[]'
![screen shot 2017-05-05 at 15 23 59](https://cloud.githubusercontent.com/assets/17491850/25749598/f9e56b12-31a6-11e7-8878-f3ac7424324b.png)

I find it strange that it only returns the odd number with the following regex: "/Z(\d+)/gi"
removing the regex:

![screen shot 2017-05-05 at 15 26 22](https://cloud.githubusercontent.com/assets/17491850/25749668/3dde69d6-31a7-11e7-8cd6-5572aa82836a.png)

**Comment by torkelo** [comment]
Javascript regex docs:
https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by ricard0ff** [comment]
@torkelo https://regex101.com/r/PHOPLD/1

**Comment by daniellee** [comment]
Just leave off the g, I think.

![image](https://cloud.githubusercontent.com/assets/434655/25750363/c11d07da-31b1-11e7-9467-ee573d3afc16.png)

**Comment by daniellee** [comment]
http://stackoverflow.com/questions/18462784/why-is-javascript-regex-matching-every-second-time

**Comment by ricard0ff** [comment]
@daniellee you are correct :package: 
thanks!
