### ISSUE TITLE
[Bug] Possible html escaping error on telegram notifications

### ISSUE THREAD

**Issue by aleosd** [grafana/grafana#8302]
- What Grafana version are you using?
Grafana version=4.2.0 commit=349f3eb compiled=2017-03-22T15:06:41+0500
- What datasource are you using?
graphite
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Configured telegram alerts, set notification message contained string `rps < 50`, made alert settings to fail
- What was the expected result?
Message from telegram bot in group chat
- What happened instead?
Telegram api returned 400 error:
`lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook=my-telegram-bot`

Details on https://community.grafana.com/t/telegram-alerts-test-message-succeeded-but-400-bad-request-on-real-alerts/806
 
Replaced symbol `<` in notification message with `less then`, and got expected result. I can't be sure, but looks like html markup of telegram message lacks escaping.

**Comment by aaabramov** [comment]
Regarding escaping html symbols for Telegram messages:
![image](https://user-images.githubusercontent.com/11317222/64264923-c0ba5300-cf3a-11e9-9195-4fba7fd1adc9.png)

Source: https://core.telegram.org/bots/api#html-style

**Comment by mator** [comment]
is it possible to create a parser (escaper) for description area (field) , since i'm getting same issue on grafana version grafana-6.5.2-1.x86_64

**Comment by torkelo** [comment]
Closing this due to lack of updates / upvotes, if this is still an issue comment here or open a new bug

**Comment by thomas725** [comment]
This seems to be still an issue. Trying to send alerts via telegram bot, which makes the sending of the alert fail if variables like "{{ $values.C }}" resolve to "\<no value\>"
> logger=alertmanager org=1 t=2023-01-06T00:40:03.524485584+01:00 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Telegram Bot/telegram[0]: notify retry canceled due to unrecoverable error after 1 attempts: failed to send telegram message: webhook response status 400 Bad Request"
