### ISSUE TITLE
[Bug] "Auto refresh" not working

### ISSUE THREAD

**Issue by tammytankian** [grafana/grafana#8303]
Read before posting: 

Please include this information:
- What Grafana version are you using? 4.2.0
- What datasource are you using? Zabbix 
- What OS are you running grafana on? Debian 8.7

The configuration "Refresh every" is not really working, as showed in the images below. The data showing on grafana just updates with F5 (Tested on Firefox and Google Chrome, same result)

**Before F5**
![before f5](https://cloud.githubusercontent.com/assets/27218076/25745732/bfde3f50-3176-11e7-914b-cafa8ac03f76.jpg)

**After F5**
![after f5](https://cloud.githubusercontent.com/assets/27218076/25745667/722c24b6-3176-11e7-9d85-8a519a45efe9.jpg)

**Network Request&Response 1**
![network1](https://cloud.githubusercontent.com/assets/27218076/25745682/7df0554c-3176-11e7-8c86-c34fce1d4b4d.PNG)

**Network Request&Response 2**
![network2](https://cloud.githubusercontent.com/assets/27218076/25745689/84419a50-3176-11e7-8949-16e7619d79fe.PNG)

  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
cannot replicate with other data sources, maybe an issue Zabbix? or caching? 

You can check the network request and the time range filter. Grafana does send request every refresh

**Comment by tammytankian** [comment]
Thanks for the fast response!

With issue Zabbix, you mean the datasource Zabbix or the Zabbix per si?
The problem happens with different dashboards with different panes :/

**Comment by torkelo** [comment]
maybe zabbix caches the call or issue with zabbix data source plugin. You can inspect the network request (the parameters grafana sends to zabbix every refresh), why is Zabbix returning the same data?
