### ISSUE TITLE
Prometheus datasource: `$__interval` is interpolated incorrectly if "Min step" is used

### ISSUE THREAD

**Issue by artli** [grafana/grafana#83058]
### What happened?

When "Min step" is used for a Prometheus query (either in a dashboard panel or in the Explore UI) and the query uses the `$__interval` variable, the variable is filled in with the wrong value: instead of using the "Min step", which is the actual `step` parameter Grafana uses for the query, Grafana instead interpolates `$__interval` with the default value if would have had based on the heuristics Grafana would have applied without the "Min step" setting.

This means that with sufficiently large "Min step" values, the query starts consistently not taking some of the data into account.

Screenshots:

In a query without "Min step" `$__interval` gets correctly interpolated with 15s (the default scrape interval): ![Query without "Min step"](https://github.com/grafana/grafana/assets/4920393/16dfcae5-6400-4b52-b134-0fcc10f7f718)

In a query with an explicit "Min step" it still gets interpolated with the same 15s value: ![Query with a larger "Min step"](https://github.com/grafana/grafana/assets/4920393/068e4c68-2871-40dd-b82c-58d319311033)

Compare to `$__rate_interval`: in a query without "Min step" it's correctly interpolated with 1m: ![query without "Min step"](https://github.com/grafana/grafana/assets/4920393/562eff18-1ae7-4556-abfa-72353ca1396d)

In a query with "Min step" the value of `$__rate_interval` becomes appropriately larger: ![query with "Min step"](https://github.com/grafana/grafana/assets/4920393/7b84407d-1466-44d8-b060-c2ab4f6a63eb)

### What did you expect to happen?

`$__interval` is expected to be interpolated with the actual `step` parameter of the Prometheus query.

### Did this work before?

Same test in 9.5.1 shows `$__interval` being correctly interpolated with the value of "Min step".

### How do we reproduce it?

1. Compose any query that uses `$__interval`.
2. Set "Min step" to a value larger than the default step that would have been used by Grafana at this zoom level.
3. Observe `$__interval` being interpolated incorrectly in the Query inspector.
4. Observe the query returning incorrect results because they are based on incomplete data.

### Environment (with versions)?

Grafana: 10.3.3
Browser: Chrome 121

### Grafana platform?

A downloaded binary

### Datasource(s)?

Prometheus

**Comment by itsmylife** [comment]
Hi, thanks for reporting this. That was a known issue and indeed a bug. 
[This PR](https://github.com/grafana/grafana/pull/80904) has fixed the issue. 
Could you please upgrade to v10.4.0 and try again?

**Comment by artli** [comment]
Thank you! Will try the new release sometime soon and reopen if it's still an issue
