### ISSUE TITLE
[Bug] Variable auto-escaping is braking InfluxDB query

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [grafana/grafana#8305]
# [Bug] Variable auto-escaping is braking InfluxDB query

I have a variable _(queried from InfluxDB)_ which has this as one of its values:
- Average_Wait_Time_(ms)

The problem is that when that variable is used in an InfluxQL query, it is being automatically escaped and ends up as:
- Average_Wait_Time_\\(ms\\)

Which breaks the query.

The query I'm trying to execute is:
`SELECT mean("$variable") FROM "InfluxTable" WHERE blabla`
`SELECT mean("Average_Wait_Time_(ms)") FROM "InfluxTable" WHERE blabla`

**Comment by PauloAugusto-Asos** [comment]
It's also happening with variables named like:
* Contention_Rate_/_sec
Get's transformed to:
* Contention_Rate_\\/_sec

**Comment by torkelo** [comment]
What's you variable options? Is multi-value and all value disabled? If they are enabled the value get regex escapes, try disable those options

**Comment by PauloAugusto-Asos** [comment]
The multi-value and all-value options were enabled yes. But it was being used in a "repeat", so it would only ever have one value when used.
