### ISSUE TITLE
[BUG] Template variable with interpolated query including another template variable does not update on that template variable being updated via dropdown selection

### ISSUE THREAD

**Issue by alexmnyc** [grafana/grafana#8306]
Template variable with interpolated query including another template variable does not update on that template variable being updated

when changing $app_name dropdown selection to another value, $app_asg does not get updated through binding. It does update, however, once you click into it. Can you guys take a look at this buggy behaviour please?

CC @ajr2493

```
{
        "allValue": null,
        "current": {
          "text": "playlist-service",
          "value": "playlist-service"
        },
        "datasource": "graphite",
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "app_name",
        "options": [],
        "query": "$env.$namespace.skynet.*",
        "refresh": 2,
        "regex": "(media-service|playlist-service|key-service)",
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
```

```{
        "allValue": null,
        "current": {
          "text": "skynet-prod-playlist-service-AutoscalingGroup-GLA2EB7XR76I",
          "value": "skynet-prod-playlist-service-AutoscalingGroup-GLA2EB7XR76I"
        },
        "datasource": "$cw_datasource",
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "app_asg",
        "options": [],
        "query": "dimension_values($region, AWS/EC2, CPUUtilization, AutoScalingGroupName)",
        "refresh": 1,
        "regex": "skynet-$env-$app_name.+",
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
```

**Comment by ajr2493** [comment]
👍 I've seen similar issues. Any assistance here would be met with much gratitude.

**Comment by torkelo** [comment]
Not sure I understand, it does not update on binding? What do you mean by binding? It updates when you click, so then it is working. 

The app_asg variabel does not use the app_name it ins query define only in the regex. Nested variables are only connected (cause updates) when used in the query field.

**Comment by alexmnyc** [comment]
It is using $app_name in its regex - skynet-$env-$app_name.+

It does not automatically update app_asg value when app_name is changed in the dropdown

**Comment by torkelo** [comment]
Not buggy, maybe missing a feature. 

As I said only the query field is considered, not regex. Regex is mostly used to find a substring, filtering should be done in the query
