### ISSUE TITLE
Layer toggle option for geomap 

### ISSUE THREAD

**Issue by fredotdev** [grafana/grafana#83074]
**Why is this needed**: 
Vastly improves the UI of a dashboard using geomap. Now I would have to create multiple maps to show different things whilst they could be included in a single map.

**What would you like to be added**:
![image](https://github.com/grafana/grafana/assets/35976402/ffa4770c-41ba-4a10-9591-8a8e879b57a7)

Toggle menu for geomap layers. See example above.

**Who is this feature for?**
Anyone who has multiple layers on a geomap.

**Comment by nick-george** [comment]
Hi @freref, could you please describe how to use this feature?
