### ISSUE TITLE
Data Sources with a slash in the UID can be created through the API but cannot be interacted with in the UI

### ISSUE THREAD

**Issue by JamesBelchamber** [grafana/grafana#83088]
### What happened?

I created a Data Source with a hard-coded UID that included a slash(`/`), which I could then not interact with via the API without encoding the slash (`%2F`) and couldn't interact with in the UI at all ("Page not found" when clicking on the Data Source).

### What did you expect to happen?

Either:
a) Grafana properly escapes slashes when added as UIDs.
b) Grafana refuses to create a UID with a slash from the API

### Did this work before?

I don't know. I experienced this in the version of Grafana deployed by AWS (`v9.4.7`) and I tested it in Grafana Cloud (version unknown, but I tested it today).

### How do we reproduce it?

1. Send a POST request that includes a slash in the `uid` field to your API endpoint, e.g.: `https://<account>.grafana.net/api/datasources`
```
{
  "name":"test_datasource",
  "type":"graphite",
  "url":"http://mydatasource.com",
  "access":"proxy",
  "basicAuth":false,
  "uid":"test/thing"
}
```
2. Ensure the request returns successfully, e.g. with the following response:
```
{
    "datasource": {
        "id": 13,
        "uid": "test/thing",
        "orgId": 1,
        "name": "test_datasource",
        "type": "graphite",
        "typeLogoUrl": "public/app/plugins/datasource/graphite/img/graphite_logo.png",
        "access": "proxy",
        "url": "http://mydatasource.com",
        "user": "",
        "database": "",
        "basicAuth": false,
        "basicAuthUser": "",
        "withCredentials": false,
        "isDefault": false,
        "jsonData": {},
        "secureJsonFields": {},
        "version": 1,
        "readOnly": false
    },
    "id": 13,
    "message": "Datasource added",
    "name": "test_datasource"
}
```
3. Check the Data Sources panel in Grafana (e.g. `https://<account>.grafana.net/connections/datasources`) to see the data source, which includes the slash in the link, e.g. `https://<account>.grafana.net/connections/datasources/edit/test/thing`.
4. Click this to see a redirect to a "Page not Found" (e.g. `https://<account>.grafana.net/notfound`)

### Environment (with versions)?

Grafana: v9.4.7, Cloud
OS: macOS 14.3.1
Browser: Chrome 121.0.6167.184

### Grafana platform?

AWS Managed Grafana, Grafana Cloud

### Datasource(s)?

N/A

**Comment by gelicia** [comment]
We need to either reject the API call or fix the frontend. I'm guessing fix the frontend to encode the special character and not break the UI.

If it's not meant to be allowed, we should fail the API call and add to the documentation.

**Comment by JamesBelchamber** [comment]
I should add that, as a user, I'm not _expecting_ to be able to use a `/` in my uids. I was expecting it to have errored out when I tried to create it :) in fact, it left me in a weird spot because the character didn't need to be encoded when I created it (since it was in the POST body), but did need to be encoded for me to interact with the object by uid (as that was in the URI), and realising that wasn't intuitive (the API was also simply returning "not found", which is not the API's fault of course).

I would expect that uids could only be alphanumeric, and maybe also hyphens and underscores, and I'll be rewriting my code to do that when creating data sources. Obviously I don't mind how Grafana fixes this, which I suspect will be by supporting the character since people might already have uids with that character (as it was "accidentally" supported up until now).

**Comment by joshhunt** [comment]
FYI for other devs testing/debugging this, paste and run in your JS console to create a TestData datasource with a specified UID

```js
await fetch("http://localhost:3000/api/datasources", {
  body: JSON.stringify({
    type: "grafana-testdata-datasource",
    access: "proxy",
    name: "DS with slash UID",
    uid: "custom/uid",
  }),
  headers: {
    "content-type": "application/json",
  },
  method: "POST"
});
```

Can confirm that the data source is addressable through the API if the UID is percent-encoded.

**Comment by tolzhabayev** [comment]
Related: https://github.com/grafana/grafana/issues/73892

**Comment by leonorfmartins** [comment]
it happened to a customer: https://github.com/grafana/support-escalations/issues/10041
I'd like to propose we:
- add a validation on the FE side or
- modify the datasources api to take the datasource name as a query string instead of a path, e.g. /api/datasources?name=dev/metrics

wdyt?

**Comment by andresmgot** [comment]
@leonorfmartins the escalation is related to the datasource name, not the UID so it's a different issue
