### ISSUE TITLE
[Question] Plugin for view HAR files in Grafana

### ISSUE THREAD

**Issue by abhagupta** [grafana/grafana#8308]
Hi There,
I am wondering if there a Grafana plugin to view HAR file in the dashboard. If not, is it worth taking a stab on making a plugin for viewing HAR file?  The datasource of HAR file is not really a time series database, its a simple JSON file.  Considering this and my brief reading on developer guide for grafana plugins which are mostly either creating a datasource, or using a datasource,  just wondering if this is even possible?

**Comment by torkelo** [comment]
Please open questions on the community site :) 

Not aware of any HAR plugin, :(

**Comment by daniellee** [comment]
Definitely possible to make a data source plugin for this. Check out the [Simple JSON Data Source](https://github.com/grafana/simple-json-datasource).
