### ISSUE TITLE
[Feature Request] Option to only show non-zero points in graph

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8309]
When plotting graphs, it is possible to choose to hide serieses (in the legend) that are all zeroes.

This is great...

And I'd like to take this one step further - to not show zeros.

So that when you've got (say) 10 serieses being shown on the one graph that are zero most of the time, rather than have a stack of 10 points all on top of each other on the bottom of the graph, be able to not show them at all.

Of course this does not work for all graph types - it's a bit silly for "line graphs". The bar graph already behaves like this (kind of)

**Comment by RichiH** [comment]
FYI, this works with Prometheus by simply attaching `> 0` to your queries.

**Comment by ojle** [comment]
> FYI, this works with Prometheus by simply attaching `> 0` to your queries.

If you do this, and have alert rule on that graph, you'll have bad calculations, eg. avg()
So option just to hide 0 values in graph would be nice

**Comment by RichiH** [comment]
Agreed, but if you're using Prometheus, you should not be using Grafana
alerting at all.

Sent by mobile; please excuse my brevity.
