### ISSUE TITLE
[Feature Request] Select Time Range from batch start/end time query

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#8310]
Allow 'batch' query say when was batch= #1234 to get start/end time
then use these time points/events to select that as a time range in grafana

Various uses from home brew, show me fermentation of batch number #7777 
or in IOT when sous-vide was making chicken123

is there any partial work done that could pave the way to handle batch time ranges ?

**Comment by daniellee** [comment]
Don't understand this part:

> Various uses from home brew, show me fermentation of batch number #7777
or in IOT when sous-vide was making chicken123

Could explain more about what you mean by a batch query?

**Comment by roscoe57** [comment]
when you make things like beer, chemicals, pharmaceuticals usually it is done a batch at a time.  Each batch processed has a unique batch id, which has a start & end time.
so for instance a table can display a list of say the last 20 batches with columns display the start/end time
now I would like somehow to have grafana use the particular start/end times by say clicking of the table to select the exact start/end times are the time range and therefore so the associated dashboard temperature, weight, pH, annotations for that batch.
Otherwise, you have to somehow zoom in, easy if the batch was this week, less easy for last month if there are many batches

**Comment by roscoe57** [comment]
? closed by mistake .. whoops

**Comment by antiquechrono** [comment]
This is definitely something I would be interested in. We collect tons of events for various electrical data. It would be really neat to be able to just click on an event (for example when the power went out) in a table or something and have the rest of the graphs on a dashboard update to show you what happened during that event.

**Comment by hixxy89** [comment]
+1 Many industries are batch driven, usually an incremental number.  Already send the batch number as a graphite metric but it would be great to select a dashboards time range to be when batch metric was equal to 500 or batch metric was between 500 and 510. i.e. time range is selected by events

**Comment by fnoop** [comment]
+1 This is fairly fundamental to making grafana useable for sensor/batch/event data.  One possible/easier alternative would be to auto select the time range based on available data, so for example you could use templating to select batch=xx, then when the batch is chosen to automatically select the time range based on the start and end timestamps of the available data.
