### ISSUE TITLE
Dashboard: Template Variable break when Multi-Value or ALL is selected

### ISSUE THREAD

**Issue by gregoryb** [grafana/grafana#83130]
### What happened?

Got an error on InfluxQL Query (InfluxDB 1.8)
`Status: 500. Message: InfluxDB returned error: error parsing query: found $, expected ; at line 1, char 109`

Request seems valid:
`SELECT last("http_response_code") FROM "http_response" WHERE ("server"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)`

host variable is something like https://xxx.xxx.xxx

### What did you expect to happen?

A valid response.

### Did this work before?

Yes. Graph was ok on 9.x

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.2.4
OS: OSX
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

InfluxDb 1.8

**Comment by gregoryb** [comment]
Fixed using` "server" = '${host:raw}' `

**Comment by tonypowa** [comment]
thanks for sharing the solution! @gregoryb
