### ISSUE TITLE
Grafana with htpasswd 

### ISSUE THREAD

**Issue by prasenforu** [grafana/grafana#8314]
I want to use in linux host htpasswd file  for grafana authentication 

Can anyone suggest how? Or any blog.

**Comment by torkelo** [comment]
use nginx as proxy:
http://docs.grafana.org/installation/behind_proxy/#nginx-configuration

And configure nginx with htpasswd, then configure grafana with auth proxy settings (nginx sends user via header):
http://docs.grafana.org/installation/configuration/#enabled-3

**Comment by prasenforu** [comment]
Thanks ...

but some issue facing ..

grafana.ini

```
[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Editor

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```
my nginx conf file (default.conf)

```
server {
  listen 80;
  root /usr/share/nginx/www;
  index index.html index.htm;

  location / {
   proxy_pass http://grafana:3000/;
   auth_basic "Restricted";
   auth_basic_user_file /etc/nginx/users.htpasswd;
   proxy_set_header X-WEBAUTH-USER;
  }
}
```

but in browser and logs also getting following error.

**{"message":"Invalid username or password"}**

Tried with  below conf file also but same.

nginx conf file (default.conf)

```
server {
  listen 80;
  root /usr/share/nginx/www;
  index index.html index.htm;

  location / {
   proxy_pass http://grafana:3000/;
   auth_basic "Restricted";
   auth_basic_user_file /etc/nginx/users.htpasswd;
   proxy_set_header X-WEBAUTH-USER $remote_user;
  }
}
```

**Comment by sabrehagen** [comment]
Nginx forwards the `Authorization` header supplied by the client to Grafana. Because Graphana expects it's auth header, you get the invalid username or password error.

        location / {
            auth_basic "Restricted";
            auth_basic_user_file /var/nginx/.htpasswd;
            proxy_pass http://grafana:3000;
            proxy_set_header Authorization ""; # stop nginx forwarding the basic auth header for nginx .htpasswd to grafana
        }

**Comment by KevinGimbel** [comment]
The above also applies to Grafana behind Traefik proxy with basic auth, I had to set the following Docker label on my Grafana container. 

```
traefik.http.middlewares.grafana_header.headers.customrequestheaders.Authorization: ""
```
