### ISSUE TITLE
After the Grafana upgrade from 10.1.6 to 10.3.1 we are getting unthorized issue in elasticsearch panels

### ISSUE THREAD

**Issue by SricharanSundar** [grafana/grafana#83156]
**Steps to reproduce**:

**Actual Result**:
   The panels are showing unauthorized 401 in elasticsearch panels.
   Status: 500. Message: Post "https://sri.io/_msearch?max_concurrent_shard_requests=256": 401 Unauthorized

**Expected Result**
   All the panels need to work after the upgrade

**Environment**:
- Grafana version: 10.3.1
- Data source type & version: elasticsearch 
- User OS & Browser: windows and explore, chrome
- Others:

**Comment by usmangt** [comment]
Hi @SricharanSundar,

Thanks for opening this issue.

What happens if you setup a new ElasticSearch Data source (while keeping the same config settings as in the old one) and then does the error still occur?

**Comment by SricharanSundar** [comment]
> Hi @SricharanSundar,
> 
> Thanks for opening this issue.
> 
> What happens if you setup a new ElasticSearch Data source (while keeping the same config settings as in the old one) and then does the error still occur?

the datasource is getting 401 unauthorized after the upgrade in grafana panels

**Comment by ivanahuckova** [comment]
SigV4 was unfortunately broken in 10.3.1 https://github.com/grafana/grafana/pull/81814. I recommend checking the 10.3.4 or 10.4 releases where SigV4 should work. Closing the issue, but feel free to reopen if you encounter the issue on any of these recommended versions.
