### ISSUE TITLE
401 unauthorized after the upgrade 10.3.1

### ISSUE THREAD

**Issue by SricharanSundar** [grafana/grafana#83151]
### What happened?

I have upgraded the grafana version from 10.1.6 to 10.3.1. After the upgrade my panels are showing 401 unauthorized for all the panels.

### What did you expect to happen?

All the data source related panels need to work properly after the upgrade

### Did this work before?

yes perfectly worked before the upgrade

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

Yes, Its popping up an error occur within the plugin. Its popping the alert symbol with 401 unauthorized

### Environment (with versions)?

Grafana: 10.3.1
OS: windows
Browser: explorer

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch, Opensearch

**Comment by sheirys** [comment]
Same

**Comment by johanjino** [comment]
Same issue for me as well

**Comment by SricharanSundar** [comment]
@johanjino 
SigV4 is broken in Elasticsearch datasource of Grafana version 10.3.1.
Please upgrade to 10.4.1.
Before upgrading make the opensearch datasource version to be 2.14.7 or else few dashboard will get error.
