### ISSUE TITLE
ValidateRuleGroupInterval fires on exported/imported rule group that seemed valid

### ISSUE THREAD

**Issue by zlugo** [grafana/grafana#83154]
### What happened?

I wanted to test provisioning alerting resources and created a simple, seemingly valid test alert through the web UI.
I exported the rule group it's in using the [Export all alert rules in provisioning file format endpoint of the Alerting Provisioning HTTP API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-get-alert-rule-group-exportspan-export-an-alert-rule-group-in-provisioning-file-format-_routegetalertrulegroupexport_).
When trying to import this rule group again using the [Update the interval or alert rules of a rule group](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/http-api-provisioning/#span-idroute-put-alert-rule-groupspan-update-the-interval-or-alert-rules-of-a-rule-group-_routeputalertrulegroup_), it fails with
`{"message":"invalid alert rule: interval (0s) should be non-zero and divided exactly by scheduler interval: 10","traceID":""}`
In my exported rule group JSON, I can only see an `"interval":"5m"` (on group level) and some `"intervalMs":1000` in the rules section, so I'm not sure where this is coming from.

### What did you expect to happen?

I would expect that I can export an alert rule group/alert rule that I just created without validation errors in the web UI, and import it without getting different validation errors. Maybe [the validation rule](https://github.com/grafana/grafana/blame/00a22ff8b28550d593ec369ba3da1b25780f0a4a/pkg/services/ngalert/models/alert_rule.go#L631) is being applied to eagerly?

Of course it would not be a problem if something actually was invalid and this was also shown on the UI.
But I'm worried that I can create seemingly valid rules and export them in JSON format for provisioning, and then new validation errors turn up.

### Did this work before?

I have not tested this with any previous version yet, but the relevant validation logic seems to be ~2 years old.

### How do we reproduce it?

1. Create a new Grafana alert rule in its own evaluation group and export the group through the endpoint listed above. Here is my example command + output with some redactions:
`curl -H "Authorization: Bearer <redacted>" <grafana_url>/api/v1/provisioning/folder/fbba05f6-b1ab-4215-acf3-299812cf5852/rule-groups/<group_name>/export/?format=json`

> `{"apiVersion":1,"groups":[{"orgId":1,"name":"<group_name>","folder":"<dashboard folder>","interval":"5m","rules":[{"uid":"e1b88847-5bc7-4bea-a5dc-166933d803f9","title":"test_2","condition":"C","data":[{"refId":"A","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"PC96415006F908B67","model":{"disableTextWrap":false,"editorMode":"builder","expr":"component_up{monitored_instance=\"<instance to be monitored>\"}","fullMetaSearch":false,"includeNullMetadata":true,"instant":true,"intervalMs":1000,"legendFormat":"__auto","maxDataPoints":43200,"range":false,"refId":"A","useBackend":false}},{"refId":"B","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"A","intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"B","type":"reduce"}},{"refId":"C","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[1],"type":"lt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"B","intervalMs":1000,"maxDataPoints":43200,"refId":"C","type":"threshold"}}],"noDataState":"NoData","execErrState":"Error","for":"5m","annotations":{},"labels":{},"isPaused":false}]}]}`
2. Try importing this rule group through the endpoint listed above. Below is my example command (with some redactions) and the response:
`curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer <redacted>" -d '{"apiVersion":1,"groups":[{"orgId":1,"name":"<group_name>","folder":"<dashboard folder>","interval":"5m","rules":[{"uid":"e1b88847-5bc7-4bea-a5dc-166933d803f9","title":"test_2","condition":"C","data":[{"refId":"A","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"PC96415006F908B67","model":{"disableTextWrap":false,"editorMode":"builder","expr":"component_up{monitored_instance=\"<instance to be monitored>\"}","fullMetaSearch":false,"includeNullMetadata":true,"instant":true,"intervalMs":1000,"legendFormat":"__auto","maxDataPoints":43200,"range":false,"refId":"A","useBackend":false}},{"refId":"B","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"A","intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"B","type":"reduce"}},{"refId":"C","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[1],"type":"lt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"B","intervalMs":1000,"maxDataPoints":43200,"refId":"C","type":"threshold"}}],"noDataState":"NoData","execErrState":"Error","for":"5m","annotations":{},"labels":{},"isPaused":false}]}]}' <grafana_url>/api/v1/provisioning/folder/fbba05f6-b1ab-4215-acf3-299812cf5852/rule-groups/<group_name>`
> `{"message":"invalid alert rule: interval (0s) should be non-zero and divided exactly by scheduler interval: 10","traceID":""}`

### Environment (with versions)?

Grafana: 10.3.1 (docker.io/grafana/grafana:10.3.1)

### Grafana platform?

Kubernetes

**Comment by zlugo** [comment]
The same issue seems to exist in Grafana 9.5.5 as well (same error message).

**Comment by KaplanSarah** [comment]
The export functionality is to export the group in file provisioning format.  If you want the correct payload for the provisioning API, you need to use the GET API.   We realize this is not obvious and hope to fix it in the future.
https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#route-get-alert-rule-group-export

**Comment by YouShallNotCrash** [comment]
Hi, 
according to me the issue persist (v. 11.3) :(
Exporting the "proper way", with /api/v1/provisioning/folder/:folderUid/rule-groups/:group/export and importing it's output results in the same error as mentioned in the original issue
