### ISSUE TITLE
Alerting: Grafana Managed Alerts should use time_intervals instead of mute_time_intervals

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#83168]
Grafana Managed Alerts should use the new `time_intervals` field instead of `mute_time_intervals`, which is deprecated.

### Backend

In the backend, this requires changes to `grafana/alerting` and `grafana/grafana`. The `Configuration` interface in `grafana/alerting` will need `TimeIntervals()`:

```go
type Configuration interface {
	DispatcherLimits() DispatcherLimits
	InhibitRules() []InhibitRule
	TimeIntervals() []TimeInterval
	MuteTimeIntervals() []MuteTimeInterval
	...
}
```

and the initialization of mute timings will need to use both `TimeIntervals()` and `MuteTimeIntervals()` method:

```go
am.timeIntervals = am.buildTimeIntervals(cfg.TimeIntervals(), cfg.MuteTimeIntervals())
```

In `grafana/grafana`, the Grafana API will need to be updated for both the UI and Provisioning to use `time_intervals` instead. We should also write a migration to move `mute_time_intervals` to `time_intervals`.

### Frontend

The frontend will need to be updated to show `time_intervals` in the UI, and use them whenever creating or editing an existing time interval. Mute timings should also be renamed to Time intervals.

**Comment by soniaAguilarPeiron** [comment]
we need to update  `/time-intervals` api before merging FE PR.  Otherwise we won't see any intervals for simplified routing.

**Comment by grobinson-grafana** [comment]
I've re-assigned this issue to Will and Yuri who are working on the new time intervals API.
