### ISSUE TITLE
Metric find query old target

### ISSUE THREAD

**Issue by devans** [grafana/grafana#8316]
- Grafana 4.2.0
- Developing a data source plugin
- Ubuntu 16, Chrome and Firefox

I'm directing the simple json data source to my web service. In the graph builder, when I create a timeserie target for the graph, it sends a REST request to /search whenever I add text to the field.

However, the text is always whatever was last put into the text box before the latest editing of the box began. For instance, it will send 'select metric' over and over as I type. It's not explicitly documented but I am assuming this is meant to send a prefix of what is being typed so that matches can be autocompleted.

I verified that it is not a problem with the simple json data source code by inserting console.log() statements using the chrome dev tools into metricFindQuery(options) to verify the old text is what is being passed from the controller.

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/simple-json-datasource/commit/b46d6bd9168f1046fe22ece4b459564556f76d1f

For the fix to work you need to use last master (nighly build)
