### ISSUE TITLE
token_mgr_error with elasticsearch query when field have "/" in it

### ISSUE THREAD

**Issue by toporek3112** [grafana/grafana#83173]
### What happened?

While building and testing a new dashboard which is intended for logs analysis I stumbled upon a bug(?) where when a field in a query has a '/', I get a **token_mgr_error**.

Error:
....
 \"reason\": \"Failed to parse query [
 level:(\\\"DEBUG\\\" OR \\\"ERROR\\\" OR \\\"FINE\\\" OR \\\"INFO\\\" OR \\\"NONE\\\" OR \\\"WARN\\\") 
AND 
kubernetes.container_name:(... OR ... OR ...) 
AND 
kubernetes.labels.app_kubernetes_io/part-of.keyword:\\\"some-team\\\"]\"
....

I also have been trying some other custom field which we have in our elastic index but every time the field I want to filter for has a '/' in it I get this error. And since the [Kubernetes label conventions](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) recommend this style of labels I think this is a important thing to fix. I am suprised that nobody reported this since now (or at least I couldn't find any issues related to this).

### What did you expect to happen?

I expected the query to return me the correct logs. 

### Did this work before?

Nope

### How do we reproduce it?

1. Try sending a query to elastic where a field has a '/' in it. Examples: [Kubernetes label conventions](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) 

### Is the bug inside a dashboard panel?

In my case this bug effects a whole dashbaord and all the panels in it. But I also tested the query in Kibana and it worked with no issues. But when I tried the same query again in the Grafana explore window I get the same error described above

### Environment (with versions)?

Grafana: v10.1.4

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch 7.17.3

**Comment by ivanahuckova** [comment]
@toporek3112 you need to escape your `/` with `\`. 

See bellow how escaped query produces correct results `app.kubernetes.io\/name:"abc"`

<img width="1496" alt="image" src="https://github.com/grafana/grafana/assets/30407135/82e5a5c0-0cda-4704-b323-a7d12de9d3ef">

Versus no results, if `/` isn't escapted `app.kubernetes.io/name:"abc"`:

<img width="941" alt="image" src="https://github.com/grafana/grafana/assets/30407135/9562723b-0066-4297-b29e-e10c249f73b6">

Closing the issue, but feel free to comment on/reopen if I misunderstood the issue.

**Comment by toporek3112** [comment]
I see, that makes sense. The issue was with the adhc filters but in version 10.3.3 this issue seems to be fixed. 
Sorry for the late response and thank you for the support. BR
