### ISSUE TITLE
Reflect Response from DB on Panel (Developing a Datasource)

### ISSUE THREAD

**Issue by aakarshit-batchu** [grafana/grafana#8318]
Hi Team Grafana,
 I am Trying to develop a OrientDB DataSource Plugin for Grafana. I am able to query the DB and get the response and return the response as it is from the query function. But I don't see data getting reflected on Panel.

My question is "In which Format the data is to be parsed before returning from the query function". To Reflect the data on Panel. I know that returning the raw response as it is to panel will not work. So can you tell me how to parse the data and format of the data.

Grafana-Version: 4.1.2
OS: Ubuntu: 14.04
DataSource: OrientDB

Error image:
![nodatapoints](https://cloud.githubusercontent.com/assets/27916328/25798918/a19d2376-3400-11e7-945d-535327d4d345.PNG)

Request Images:
Making a SQL Query to a Database in OrientDB to list all the Vertex Classes.
![request1](https://cloud.githubusercontent.com/assets/27916328/25799112/6cd53466-3401-11e7-80a4-4f7ff0183c36.PNG)

![request2](https://cloud.githubusercontent.com/assets/27916328/25799125/7567596a-3401-11e7-9fc4-be5b878b3b7d.PNG)

Response Image:

![response](https://cloud.githubusercontent.com/assets/27916328/25799142/839d6cf4-3401-11e7-9326-f4e8e63980dd.PNG)

**Comment by torkelo** [comment]
example data source response is included in the data source plugin docs:
http://docs.grafana.org/plugins/developing/datasources/

**Comment by daniellee** [comment]
@aakarshit-batchu if you have more questions, then you can ask them on in our [Development category on the Grafana community site](https://community.grafana.com/c/development)

**Comment by jspizziri** [comment]
@aakarshit-batchu, did you ever complete your plugin? Is it open source?

**Comment by jspizziri** [comment]
FWIW, I whipped up [a basic datasource plugin](https://gitlab.com/5stones/5stones-orientdb-datasource) that allows for a connection to orientdb. Currently it only allows you to enter a raw query, but it's enough to get the job done.
