### ISSUE TITLE
Grafana Data Source Plug-In for SAP ALM: No Connection tab when setting up ALM API data source connection

### ISSUE THREAD

**Issue by CloudALM** [grafana/grafana#83183]
### What happened?

Following 3rd step of Setup procedure in https://github.com/SAP/alm-plug-in-for-grafana/tree/master/sap-alm-dp-api-datasource, we cannot see the Connections tab under the Settings of our ALM plugin data source.

![Grafana Setup Connections Issue](https://github.com/grafana/grafana/assets/160761776/6e56305b-dbce-41e1-b1ed-7e033e951886)

### What did you expect to happen?

As shown in the screenshot of the Setup procedure, there should be a Connection tab under Settings.

### Did this work before?

No, this is our first try to set up the plugin in Grafana.

### How do we reproduce it?

1. Log in to Grafana and go to Data Sources.
2. Click SAP ALM API to view the Settings

### Environment (with versions)?

Grafana: 10.2.1
OS: Windows
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

SAP Cloud ALM

**Comment by ayalandz** [comment]
I am facing same issue I just installed grafana 10.3.3 for windows installed alm datasource fololowing this guide https://github.com/SAP/alm-plug-in-for-grafana/tree/master/sap-alm-dp-api-datasource and I can not see settings for connection of data source :
![image](https://github.com/grafana/grafana/assets/161588123/94dfcb72-8abf-4e27-87d0-7a2c1181c4f3)

**Comment by sympatheticmoose** [comment]
Hi, as this is an unsigned external plugin I'd suggest raising an issue on the plugin itself https://github.com/SAP/alm-plug-in-for-grafana
