### ISSUE TITLE
Upper and lower thresholds

### ISSUE THREAD

**Issue by feangulo** [grafana/grafana#832]
Currently I can specify two grid threshold levels that will result in either an upper-bound or a lower-bound for the metric that I am graphing.

I've found that for some of my metrics (i.e. request rates) I need both an upper-bound AND a lower-bound. Maybe instead of Level1 and Level2, we could have:
- Upper Bound Warning Level (yellow by default)
- Upper Bound Critical Level (red by default)
- Lower Bound Warning Level (yellow by default)
- Lower Bound Critical Level (red by default)

**Comment by mlang38** [comment]
:+1:

**Comment by pasancario** [comment]
+1

**Comment by ghostwords** [comment]
Related: Can we set a threshold series override?

For example, a disk space percentages chart with multiple series (free, reserved, used). I could set an upper threshold, but I only want it to apply to the "used" series.

**Comment by swissdave** [comment]
+1

**Comment by arthurlogilab** [comment]
This would be a killer feature when watching bandwidth graphs that are represented as upload and download.

**Comment by bergquist** [comment]
Fixed some time ago. I don't remember when exactly :)

http://play.grafana.org/dashboard/db/threshold-example?orgId=1
