### ISSUE TITLE
[FEATURE REQUEST] horizontal charts align based on time index

### ISSUE THREAD

**Issue by PitPaul** [grafana/grafana#8320]
![grafana-time sync](https://cloud.githubusercontent.com/assets/26178409/25810840/a70eec8e-3411-11e7-84ab-a6993b750270.png)
When two, or more charts have different Y units, time base goes to be shifted.One "time align" should set time base to the same value

**Comment by torkelo** [comment]
If you have similar panels with same settings they will align, your first graph has no right Y axis, so no trivial way to solve this. Think there already is an issue for this
