### ISSUE TITLE
Don't default "Min Doc Count" to 0 for Elasticsearch terms aggregation

### ISSUE THREAD

**Issue by volter** [grafana/grafana#8321]
min_doc_count defaults to 0 and this is usually not what you want. If you set up the following query, the results may surprise you:

`host:myhost`

Now add a terms aggregation for host. The result will look a bit like this:

`
myhost: 2, unrelated: 0, also_unrelated:0, ...
`

ES' default for min_doc_count is actually 1, to avoid this effect, since terms aggregations don't work like group-bys in SQL. I therefore recommend to default it to 1 and possibly don't allow 0 at all.

I also suggest to default to a "Top" query instead of a "Bottom" query, like I did before. :)

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/8d072de556a0fa7db279b32b778074d2f9c3ce3a
