### ISSUE TITLE
[Bug] MySQL Data Source: Database type LONG not supported

### ISSUE THREAD

**Issue by johnsusek** [grafana/grafana#8322]
- What Grafana version are you using?
grafana_4.3.0-7715pre1_amd64

- What datasource are you using?
mysql (amazon SDS replica)

- What OS are you running grafana on?
ubuntu 14.04

- What did you do?
Set up mysql data source 
Added new panel "Table"
Clicked Metrics tab, selected mysql as data source.
Format as: Table
Entered a very simple sql query: `select id from customers`. `id` is an int
Clicked preview button

- What was the expected result?
Show sql results in table panel

- What happened instead?
Received error when trying to preview panel: `Database type LONG not supported`

- If related to metric query / data viz:
Request:
```
{"from":"1494240196830","to":"1494261796832","queries":[{"refId":"A","intervalMs":10000,"maxDataPoints":1871,"datasourceId":1,"rawSql":"select\nid \nfrom customers\n","format":"table"}]}
```
Response:
```
{
    "timings": [
        null
    ],
    "results": {
        "A": {
            "error": "Database type LONG not supported",
            "refId": "A",
            "meta": {
                "sql": "select\nid \nfrom customers\n"
            },
            "series": null,
            "tables": null
        }
    },
    "message": "Database type LONG not supported"
}
```

**Comment by daniellee** [comment]
Thanks for pointing this out. The mysql data source is still under construction. We have more types than this we need to add support for as well. We should get those added this week hopefully.

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/e8b798914d9a15a1a5c792e94754abfec9dd621d
