### ISSUE TITLE
[Bug] Time range. From: date, can be set later then To: date

### ISSUE THREAD

**Issue by PitPaul** [grafana/grafana#8323]
![time range](https://cloud.githubusercontent.com/assets/26178409/25817240/089cf120-3427-11e7-988b-bdfd86133dbf.png)

**Comment by torkelo** [comment]
Not really a bug, that is the definition of from, the start time range, grafana requires that time move from past to futut

**Comment by torkelo** [comment]
Sorry read that as can't :)
