### ISSUE TITLE
[Feature request] Support dividing two series lists without aggregation

### ISSUE THREAD

**Issue by bfosberry** [grafana/grafana#8324]
- What Grafana version are you using? 4.2.0-beta1
- What datasource are you using? Graphite
- What OS are you running grafana on? Unsure
- What did you do? Attempt to divide two sets of series
- What was the expected result? Those sets of series as a percentage
- What happened instead? ValueError returned
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

```
target=divideSeries(snap.*.*.intel.docker.collabcache.*.collabcache.stats.filesystem.*.available%2C%20snap.*.*.intel.docker.collabcache.*.collabcache.stats.filesystem.*.capacity)&from=-6h&until=now&format=json&maxDataPoints=178
```

<img width="701" alt="screen shot 2017-05-08 at 3 55 21 pm" src="https://cloud.githubusercontent.com/assets/1553039/25828773/f2d138ee-3406-11e7-9e49-44474b03473b.png">

I have two sets of series, one for filesystem capacity, one for available space. I want to divide those two sets of series, such that my resulting set of series will be [A1/C1, A2/C2,....AN/CN], however it seems that divideSeries requires a single divisor series. 

Would a divideSeriesWithWildcard be useful here?

**Comment by torkelo** [comment]
yes, that or maybe reduceSeries function. 

Closing this as it feels more like a Graphite question? http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.reduceSeries

**Comment by bfosberry** [comment]
Ohhh you're right, thanks for the tip, I'll give that a shot and try reach out there, thanks!
