### ISSUE TITLE
[Feature request] Hide null/zero values series from Table panel

### ISSUE THREAD

**Issue by erez-rabih** [grafana/grafana#8325]
- What Grafana version are you using?
3.1.1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Linux
- What did you do?
Add a Table panel
- What was the expected result?
I am able to hide null values series from the table rows, like I can do with Graph panels on the Legend tab
- What happened instead?
There is no such option

**Comment by daniellee** [comment]
This actually got added (in version 4.2.0) and then removed again (in latest master) due to performance problems.

As you are using Graphite, you can use the [removeEmptySeries](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.removeEmptySeries) function.

**Comment by erez-rabih** [comment]
@daniellee Unfortunately I am using Graphite 0.9.15 which, AFAIK, does not support the removeEmptySeries function.

**Comment by daniellee** [comment]
@erez-rabih there are a couple of other filter functions - I've used [removeBelowValue](https://graphite.readthedocs.io/en/0.9.10/functions.html#graphite.render.functions.removeBelowValue) and [averageAbove](https://graphite.readthedocs.io/en/0.9.10/functions.html#graphite.render.functions.averageAbove). They are not exactly equivalent but might work for you.

```
averageAbove(seriesname, 0)
```

Other options are to upgrade Grafana to 4.2.0 that has this function (but not 4.3.0) or to upgrade your Graphite (maybe not so easy).

At the moment, we are not going to add this function back to the table panel. This sort of filtering function belongs in the query languages of the time series databases.

**Comment by lgieron** [comment]
I don't think any of the three suggestions (`removeEmptySeries`, `removeBelowValue`, `averageAbove`) are helpful. Currently I don't see a viable way to filter out the nulls. I'm using [go-carbon](https://github.com/lomik/go-carbon) as my backend.
As a Grafana user, I'd prefer to have an option to filter the nulls. Even if it can be a performance drag (maybe the feature could be accompanied with a big warning sign), it's better than not having  it at all.

**Comment by desknotes** [comment]
Still no news about this topic? Every function metric that makes the job done in a simple graph panel ( so without null points) fails in table panel.

I'm using Graphite and sincerly do not understand why there is such a big problem adding an option to filter out this events. Even if with other data sources is a problem you can warn the user which is going to activate the feature.

In an industrial automation IOT solution where we want to show specific events (think of machine alarms) this is a must feature.

Please consider back this issue.
![nLlj7lCknX](https://user-images.githubusercontent.com/61511/67074613-c043e780-f189-11e9-9dcf-d8a6676c7380.png)

**Comment by JuniorTour** [comment]
Really need this feature to connect the discrete points to a line.

**Comment by rvsingh011** [comment]
For anyone landing here : use `transformNull` function in graphite. This can hide the null values with whatever specified.
