### ISSUE TITLE
Explore: Move query history panel to function over both panes in split mode

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#83259]
In preparation for work needed for the query library (#83095), change query history so the drawer extends over both panes. 

When clicking "Run query" in split mode, display a modal asking what pane the query should be ran in.

If the pane is open, queries ran in either pane that are relevant to the filter selected should show.

This will not be behind a feature flag and will be applied to all Grafana users.

**Comment by ifrost** [comment]
> This will not be behind a feature flag and will be applied to all Grafana users.

Does it need to be behind a toggle? Might be hard to maintain both and seems like a nice new feature that we could add directly.
