### ISSUE TITLE
[Bug] Custom header_name in the auth.proxy config is not read by grafana

### ISSUE THREAD

**Issue by banjoh** [grafana/grafana#8326]
According to the [documentation](http://docs.grafana.org/installation/configuration/#auth-proxy), when using an external ```auth proxy``` I can specify a ```header_name``` to use for the username. If not specified, it defaults to ```X-WEBAUTH-USER```. This is not the case apparently.

Grafana version: 4.2.0
OS: Ubuntu 16.04
Proxy auth module: [Apache OpenIDC](https://github.com/pingidentity/mod_auth_openidc) (not so relevant to reproduce the issue)
Reverse proxy: Apache 2.4.18 (I guess this should be reproducible with nginx as well)

**Apache configuration**
```xml
<VirtualHost *:80>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    LogLevel debug

    #OpenIDC specific configurations. Stripped out to focus on the issue at hand
    <Location "/">
        # OpenIDC authenication section
        # AuthType openid-connect
        # Require claim family_name:Doe
        # Similate authentication by adding the header of the username
        RequestHeader setifempty X-MY-AUTH-USER-HEADER johndoe

        ProxyPreserveHost On
        ProxyPass http://localhost:3000/
        ProxyPassReverse http://localhost:3000/

        # Works only if I set X-WEBAUTH-USER header explicitly
        # https://grafana.com/blog/2015/12/07/grafana-authproxy-have-it-your-way/
        RequestHeader setifempty X-WEBAUTH-USER %{X-MY-AUTH-USER-HEADER}e
    </Location>
</VirtualHost>
```

**Grafana configuration**
```ini
[auth.proxy]
enabled = true 
;header_name = X-MY-AUTH-USER-HEADER
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
disable_login_form = true
disable_signout_menu = true

[users]
# disable user signup / registration
allow_sign_up = false
```

**Possible bug**
If I remove ```RequestHeader setifempty X-WEBAUTH-USER %{X-MY-AUTH-USER-HEADER}e``` line from the *apache* config, and use ```header_name = X-MY-AUTH-USER-HEADER``` in my *grafana* config, I would assume this will work. It does not. I simulated authentication by adding a request header which is sent to grafana.

**Comment by torkelo** [comment]
Are you sure you setting (custom header name) is set? Did you restart grafana server after change? Go into admin server settings, should list the option, you can see what Grafana options have been set to. 

The auth proxy code is using the option https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy.go#L21

**Comment by banjoh** [comment]
I restart the grafana server.

Yes, I'm sure I set the custom header. Here is a test app hosted on the same reverse proxy with the same exact settings. I just changed the port to ```5000``` in apache's ```Proxy``` config section.

**flask app**
```python
from flask import Flask, request
app = Flask(__name__)

@app.route('/')
def hello_world():
    headers = ''
    for key in request.headers.keys():
        if key.startswith('X-'):
            headers += '{}: {}<br>\n'.format(key, request.headers[key])
    return headers

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)
```

**...and the response**
```bash
13:37 $ curl -v localhost
* Rebuilt URL to: localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 09 May 2017 10:37:19 GMT
< Server: Werkzeug/0.10.4 Python/3.5.2
< Content-Type: text/html; charset=utf-8
< Content-Length: 126
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization, accept
< 
X-Forwarded-For: 192.168.0.1<br>
X-Forwarded-Host: localhost<br>
X-Forwarded-Server: 192.168.0.2<br>
X-My-Custom-Header: johndoe<br>
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by banjoh** [comment]
After looking at the admin settings and seeing the correct setting, it just popped in my mind that this could be a case sensitivity issue. A quick test and viola! It works. Basically the setting in Grafana is **case sensitive** to the http header key. According to the [spec](https://tools.ietf.org/html/rfc2616#section-4.2), header keys are case-insensitive.

My library is setting ```OIDC_CLAIM_preferred_username``` as the header key. The environment variable (which was what I have been working with) is full CAPS while the doc has camel-cased values.

Problem solved!

I would however prefer to follow the http standard and handle header keys as case-insensitive.

**Comment by daniellee** [comment]
@banjoh are you sure? Seems to work for me when changing the case fo the header (tested sending the header with curl and postman).

```
curl  -H "X-WEBAUTH-User: username" http://localhost:3000/api/search
```

I'll investigate some more.

**Comment by daniellee** [comment]
Not able to recreate this. @banjoh can you recreate this using curl or postman to call the Grafana API?

**Comment by banjoh** [comment]
@daniellee I cannot repro using curl and now my setup seems to work. I had a docker setup and now I'm using a VM. It doesn't explain the anomaly but I guess I may have had some config errors from the beginning. I'll try to do some more testing. Issue can be closed.
