### ISSUE TITLE
Canvas: Arrow head options

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#83268]
Add options for arrow heads:

1. Forward
2. Reverse
3. Bi-directional
4. None (line)

Source / target style independent.

**Comment by lukasztyrala** [comment]
For arrow head styling, here is the proposal for two possible options we might have:
![Arrow heads](https://github.com/grafana/grafana/assets/141744/7831d887-c7ad-4f50-b172-1f930f7d7bac)

SVG: ![Arrow heads](https://github.com/grafana/grafana/assets/141744/58152e17-64ef-49a3-83b3-38b6d58c9b19)

Note that the size of the arrowhead ending changes linearly, but not one-to-one. Here is an example of the relationship between the line width and length of the arm of the arrow head ending with chevron:
<img width="602" alt="Zrzut ekranu 2024-03-19 o 17 00 19" src="https://github.com/grafana/grafana/assets/141744/ab907955-cb14-4f64-b3c0-5ac52a5db6dc">
📐😅
