### ISSUE TITLE
Alerting: reordering "grouped" alert rules removes alerts filtered via search

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#83263]
### What happened?

When reordering rules inside a "filtered" evaluation group, all alerts that were not present in filtered list get removed.

### What did you expect to happen?

Alert rules not to be deleted when sorting a filtered evaluation group.
I would even expect that the sort list content would NOT be affected by rule filters via search dialog.

### Did this work before?

n/a

### How do we reproduce it?

1. create 3 alert rules using the same evaluation group, e.g. create alert rules "a1", "b1" and "b2" under evaluation group "mygroup"
2. filter alerts, e.g. search for "b"
3. reorder rules for the "mygroup" evaluation group, e.g., move "b2" to top position
4. clear all filters
5. the alert rule "a1" is gone

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.3
OS: linux
Browser: chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
hi @salavessa 

>filter alerts, e.g. search for "b"

mind you this is not a valid way of searching

instead try:

`group:B_group`

searching like this respected the new ordering

here is the documentation about[ filtering alert rules with labels](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/view-alert-rules/#filter-alert-rules)

**Comment by salavessa** [comment]
hi @tonypowa
The issue is not about the "filtering" functionality and the example is not meant to be applied to "group" names, the search is directed to alert rule names.
The "How to reproduce it?" section describes the simplest way I found for you to reproduce the issue, which happens when you **reorder rules** in a group where some of the group rules have been "filtered" via search dialog.

**Comment by tonypowa** [comment]
HI @salavessa 

Thank you for your reply and apologies for the delayed answer

I have finally managed to reproduce the issue.

I even saw how the alert rule was been deleted after I applied the new order . My rules were named  a1, a2, and b1, and I first filtered for 'a' in the search bar at /alerting/list. Next, I rearranged the alert rule a2 to be at the top). Finally, I cleared the filter, and I witnessed how alert rule "b1" was being deleted.

![image](https://github.com/grafana/grafana/assets/45235678/5d16ab3a-d89f-4478-934d-6a3decb702ca)

Moving issue to alerting squad's board for review

**Comment by tomratcliffe** [comment]
Thanks for reporting this @salavessa! Agreed/confirming what @tonypowa said - this is a bug. 

What I'm planning to do to fix this is to always show the full list of rules/group in the reordering modal. This makes the most sense as you would most likely always want the full (unfiltered) list of rules available to you when reordering them, so you have the context of where everything will end up.

**Comment by tomratcliffe** [comment]
PR to fix this has been opened here: https://github.com/grafana/grafana/pull/88221
