### ISSUE TITLE
Alerting: Sporadic EOF errors from Elasticsearch

### ISSUE THREAD

**Issue by johnp789** [grafana/grafana#83279]
### What happened?

We have just upgraded from Grafana 9.2.5 to 10.3.3.  Several orgs have Elasticsearch 7.x data sources.  Elasticsearch is reached through an AWS Application Load Balancer in the same VPC as our Grafana server.  Since the upgrade ~26 hours ago, we have alerts sporadically triggered by errors evaluating their rule.  It has happened only 24 times, so rules are getting evaluated successfully most of the time.

The log messages look like

`logger=tsdb.elasticsearch endpoint=queryData pluginId=elasticsearch dsName=MY_DATASOURCE dsUID=CjO9xxxxx uname=grafana_scheduler rule_uid=_IVCmxxxx org_id=445 fromAlert=true entity=client t=2024-02-22T05:54:00.058382968Z level=error msg="Error received from Elasticsearch" error="Post \"https://elasticsearch.alb.dns.name.com:443/_msearch?max_concurrent_shard_requests=256\": EOF" status=error duration=9.9109ms stage=databaseRequest`

Unlike #78122 we don't also see any logs about `invalid character`.  The duration shown in these error log lines is also very short like above, not 30s.

The `max_concurrent_shard_requests` setting seems to have come in as a default during a Grafana upgrade or something; we will experiment with setting it to 5 for some data sources.  [Edit: After changing one Elasticsearch data source to have 5 `max_concurrent_shard_requests`, we saw the same EOF error occur a few hours later.]

Our ALB has HTTP/2 enabled and timeout is set to 60s.  Some kind of stale connection and keep-alive issue may be happening.

### What did you expect to happen?

No new ES search errors after upgrading from Grafana 9.2.5 to 10.3.3.

### Did this work before?

Yes, the same data sources and alert rules were running for a long time with Grafana 9.2.5.

### How do we reproduce it?

It seem ongoing for us, but we have only one environment with this combination of Grafana 10.3.3 and Elasticsearch.  Having Elasticsearch behind an ALB may be essential for reproducing the issue.

### Is the bug inside a dashboard panel?

No, it's showing up in alerts.

### Environment (with versions)?

Grafana: 10.3.3
OS: Container in AWS Fargate
Browser: Chrome (but this is an alerting issue manifested in the Grafana server logs)

### Grafana platform?

Docker

### Datasource(s)?

Elasticsearch 7.17.8

**Comment by ivantr5** [comment]
Regarding [https://github.com/grafana/grafana/issues/78122], we reported the same issue which is still occuring for us, and we are not sure why the call to Elasticsearh goes with max_concurrent_shard_requests=256, while this setting is by default 5, for example: https://kibana-nonprod.common/_msearch?max_concurrent_shard_requests=256

**Comment by ivanahuckova** [comment]
Hello @johnp789! Thank you for reporting the issue. First of all, I have created a fix for the default `maxConcurrentShardsRequests` https://github.com/grafana/grafana/pull/87703. Secondly, I wasn't able to reproduce the issue. Having ES ALB/anything else between Grafana and ES can be a source of issues which we have no way to reproduce or fix. If possible, could you confirm whether this issue occurs when you query ES directly from Grafana? Thank you!

**Comment by ivanahuckova** [comment]
> To try to reproduce the issue, I created a new data source which connects to ES directly, and then created several duplicates of an alert using that data source and evaluating every 1 minute.

👍 Thank you! Let me know if you were able to reproduce it with this set up.

**Comment by johnp789** [comment]
After running 10+ separate alerts running once per minute having a direct URL to Elasticsearch instead of via an AWS Application Load Balancer (ALB), we have logged zero EOF errors from these "direct" data sources.  We continue to see occasional EOF errors for other alerts which access Elasticsearch via the ALB.  We will investigate if there are any settings on the ALB which has an effect on these, and if we find something, it will be shared here.

**Comment by johnp789** [comment]
We disabled HTTP/2 on our ALB overnight, and we still observed several of the EOF errors, so unfortunately, that does not seem to be a workaround.

**Comment by johnp789** [comment]
Changing the AWS Application Load Balancer idle timeout from the default 60s to 75s has eliminated this error in our environment.

**Comment by ivanahuckova** [comment]
Thank you @johnp789 for sharing the solution! Might help someone in the future. 🧡
