### ISSUE TITLE
[Bug] Auto-refresh at random intervals or not at all - browser-specific?

### ISSUE THREAD

**Issue by numo68** [grafana/grafana#8328]
- What Grafana version are you using?

4.2.0

- What datasource are you using?

InfluxDB 1.2.2

- What OS are you running grafana on?

Debian 8 armhf (Raspberry)

- What did you do?

Parametrized a trivial graph showing the last week of data and refreshing every 5 min.

- What was the expected result?

A graph pulling new data every 5 minutes.

- What happened instead?

Chrome 58: The graph updates erratically or not at all. Looking into the network console the queries came at 1.7, 2.2, 6.2 and 21.2 min, then nothing for at least 40 minutes. Manual refresh works.

Microsoft Edge: For the one hour or so I did let it run it seems to work. The queries are spaced exactly 5 minutes apart.

The query URL was the same for every request:
`http://xxx:3000/api/datasources/proxy/1/query?db=openhab&q=SELECT%20mean(%22value%22)%20FROM%20%22autogen%22.%22Weather_1_Temp%22%20WHERE%20time%20%3E%20now()%20-%207d%20GROUP%20BY%20time(5m)%20fill(linear)%3BSELECT%20mean(%22value%22)%20FROM%20%22autogen%22.%22Weather_1_Hum%22%20WHERE%20time%20%3E%20now()%20-%207d%20GROUP%20BY%20time(5m)%20fill(linear)&epoch=ms`
and the response had the correct data.

There are no messages in the js console except for the warning `[Violation] 'setTimeout' handler took 67ms` that should be harmless.

**Comment by torkelo** [comment]
Very strange, have no other reports on strange auto refresh behavior, this is one of the most used features so it's puzzling

**Comment by numo68** [comment]
Okay, I tried to debug this, unfortunately I have no real experience with javascript, DOM etc. It looks like that due to the `b.contextSrv.isGrafanaVisible() && b.refreshDashboard()` the refresh is only in fact executed if `isGrafanaVisible()` returns true. I of course tried this in a browser I am using for everything else, doing other work between the updates. If being in another browser tab means that the function returns false, this could well be the reason. I don't know why there were the first "faster" refreshes, but the last one is spaced exactly 15 minutes, so that might be one where the tab was visible.

Trying with a separate browser window on another display that is always visible indeed works correctly.

Now the question is, is this the right thing to do? One basically has to see the window at the precise time of the sheduled refresh, otherwise nothing is updated. This is not a problem for the always visible dashboards or short refresh times, which is probably that it does not get reported, but is really inconvenient otherwise. Maybe this behaviour should be parametrizable?

**Comment by daniellee** [comment]
https://github.com/grafana/grafana/issues/7218 and https://github.com/grafana/grafana/pull/7219 is the change that turns off refresh if the page is not visible.

**Comment by numo68** [comment]
okay, so if I read this correctly, it was handled in #8076 and should appear in 4.3.0. Thanks

**Comment by daniellee** [comment]
Nice find. I'd forgotten about that fix. Closing this issue.
