### ISSUE TITLE
Grafana Metrics Dropdown - Not Even Opening

### ISSUE THREAD

**Issue by sangeethnandakumar** [grafana/grafana#83294]
### What happened?

The Metrics dropdown for Grafana connected to Prometheus when clicked logs errors on the console. It never completes loading
Prometheus is collecting data and I can see that. The issue is Grafana goes into a bug before I select a metrics

### VIDEO DEMO: 
https://youtu.be/cC8Ua9lFUk4

<hr/>

### SCREENSHOTS 
Check the screenshot.
![image](https://github.com/grafana/grafana/assets/24974154/2615dc69-4165-4c72-9517-f58c7a504c4c)

### What did you expect to happen?

The Metrics dropdown need to open to select the metric

### Did this work before?

Using Grafana for first time

### How do we reproduce it?

Connect to Prometheus running on Docker and deploy an API that generates telemetry. Then try selecting the metrics dropdown

### Is the bug inside a dashboard panel?

Yes, Can't create any dashboards since metric dropdown is not openable

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)
OS: Ubuntu Server
Browser: Chrome Version 121.0.6167.185 (Official Build) (64-bit)

### Grafana platform?

Docker

### Datasource(s)?

Promethieus

**Comment by sangeethnandakumar** [comment]
Instead of opening the dropdown, If we type in we can see the metrics, upon clicking it crashes completely

![image](https://github.com/grafana/grafana/assets/24974154/36d845aa-c1d8-47ee-b545-68c0568b7c89)

**Comment by bLd75** [comment]
Same error here on `v10.3.3 (252761264e)`

**Comment by vbezhenar** [comment]
This bug manifested after upgrade to prometheus 2.50. I rolled back to 2.49.1 and it works.

**Comment by itsmylife** [comment]
Duplicate: https://github.com/grafana/grafana/issues/80185
Reason: https://github.com/grafana/grafana/issues/80185#issuecomment-1961325729
Solution: https://github.com/grafana/grafana/issues/80185#issuecomment-1961565317

**Comment by sangeethnandakumar** [comment]
Good catch @itsmylife ..! Wonder how this breaking change gone into Prometheus without a mention it in release notes. Thanks anyway I just downgraded Prometheus. I just saw your PR and will re-upgrade to newer version in the next release cycle
