### ISSUE TITLE
[Feature request] Text Box to allow for background colour

### ISSUE THREAD

**Issue by trevorndodds** [grafana/grafana#8330]
The ability to set the background colour of a text box.

**Comment by daniellee** [comment]
Do you mean generally for every text box (HTML input) in Grafana?

**Comment by torkelo** [comment]
@trevorndodds please provide more detail

**Comment by trevorndodds** [comment]
Hi,

When using the Text Panel
![image](https://cloud.githubusercontent.com/assets/10899305/25898933/fd755888-355b-11e7-813b-39e73f578a02.png)

I would like to set the background colour. I've tried HTML code for background but that is not being applied.

![image](https://cloud.githubusercontent.com/assets/10899305/25898930/f98770a8-355b-11e7-8e78-c018e6ba0ca8.png)

I can do it with a single stat, but I need to enter my own text. 

![image](https://cloud.githubusercontent.com/assets/10899305/25898995/27bd030c-355c-11e7-8a3c-7a994d9fe9a5.png)

**Comment by michaelkaasjp** [comment]
If you put all your content inside a div, you will be able to choose the background color.

See this example where the background color becomes white:

<style>
.background{
background-color:white;
}
</style>
<div class="background">
//Your content here
</div>

**Comment by cbrahms** [comment]
> If you put all your content inside a div, you will be able to choose the background color.
> 
> See this example where the background color becomes white:
> 
> <style> .background{ background-color:white; } </style>
> //Your content here

Something must have changed, as this option doesn't seem to work for me on Grafana 6.2.5.

**Comment by rbrayner** [comment]
> > If you put all your content inside a div, you will be able to choose the background color.
> > See this example where the background color becomes white:
> > <style> .background{ background-color:white; } </style>
> > //Your content here
> 
> Something must have changed, as this option doesn't seem to work for me on Grafana 6.2.5.

I've tested on Grafana 6.6.1 and this does't seem to be working. I still can't figure out a way to put a background on a Text Panel.

**Comment by BrunaDaniel** [comment]
For Grafana 7.0 here's the code:

<h2 style="color: #FFFFFF; background-color: #728BA1; font-size: 17px;">
Your text here
</h2>

**Comment by BrunaDaniel** [comment]
For Grafana 7.0 and latest here is the code:

```html
<h2 style="color: #FFFFFF; background-color: #1A2838; font-size: 17px;">
Your text here
</h2>
```
