### ISSUE TITLE
Alerting: Silences page display wrong operator in matching labels

### ISSUE THREAD

**Issue by bcruvelier** [grafana/grafana#83312]
### What happened?

Silences coming from AlertManager datasource are shown with wrong operators in matching labels

### What did you expect to happen?

Operator should always be the one filled in the first place. 

### Did this work before?

No

### How do we reproduce it?

1. Create a silence from Grafana WebUi with a matcher containing a = operator :
![image](https://github.com/grafana/grafana/assets/37801065/55055df7-d202-4c61-a86e-b4e9f8d787ba)

2. It appears correctly in the AlertManager webui : 
![image](https://github.com/grafana/grafana/assets/37801065/babe8a01-2fe0-46fc-b341-019d3653f8dd)

3. In Grafana UI, it shows != operator instead of =: 
![image](https://github.com/grafana/grafana/assets/37801065/2475d42a-d11f-4b1e-8741-a05fbb89ca0e)

4. Editing the silence from Grafana changes the operator that was originally set:
![image](https://github.com/grafana/grafana/assets/37801065/c9e19799-5d46-43a3-aeb2-1a9dcf48741a)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.3.1
OS: Windows
Browser: Chrome, Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager

**Comment by bcruvelier** [comment]
Hi!
We are using the vanilla AlertManager in a quite old 0.21 version that might be responsible for that bug.

**Comment by gillesdemey** [comment]
Can you try upgrading to a newer version of Alertmanager and report back to us? Sadly the version you're running is somewhat out of bounds for our supported version(s) – usually the last two minor releases.

**Comment by bcruvelier** [comment]
No problem, I'll test it and come back to you here.

**Comment by grobinson-grafana** [comment]
I'm closing this issue as we haven't heard back. However, please feel free to re-open once you have tested this and can confirm it's reproducible!
