### ISSUE TITLE
[BUG] Alerting does not work

### ISSUE THREAD

**Issue by svenkirsten** [grafana/grafana#8333]
- What Grafana version are you using?
**4.2.0**
- What datasource are you using?
**InfluxDB**
- What OS are you running grafana on?
**CentOS and Redhat 7.2**
- What did you do?
**Want to use the Alerting Function**
- What was the expected result?
**When the value cross the threshold, I expect that the alert will be fired.** 
- What happened instead?
**Nothing, the value crosses several times the threshold, but nothing happened.** 

I have created a Metric B : 

<img width="1081" alt="alert_chart_metric_b" src="https://cloud.githubusercontent.com/assets/25989309/25887839/fcd291d6-3563-11e7-8391-128c4b330c57.png">

Then I have created an Alert that uses that Metric B: 

<img width="1139" alt="alert_config_result_metric_b_0" src="https://cloud.githubusercontent.com/assets/25989309/25888204/7f5a0e12-3565-11e7-9019-253e1b0d3a66.png">
<img width="880" alt="alert_config_result_metric_b" src="https://cloud.githubusercontent.com/assets/25989309/25888207/82dc8146-3565-11e7-8885-c2ec2d11c071.png">

When I press the TEST Alert button, I see 5 datapoints. But all points has NULL values. 
The result from the TEST Alert button does not correspond to the chart you can see on the first picture. And both queries are based on the same Metric B. 

So that sounds like a bug.

**Comment by daniellee** [comment]
I understand that this can be a bit tricky. If you change the Null Value to be null on the Display tab then I think you will see that the alert and the graph show the same result. The latest value is probably null.

![image](https://cloud.githubusercontent.com/assets/434655/25889497/38461052-356a-11e7-96ff-e7631aa30b55.png)

Try shifting the alert check one minute later (it looks like you write your data once every 1 minute) like this: `query(B, 6m, now-1m)`.

**Comment by svenkirsten** [comment]
I changed the Display option to "Null value" = "connected". 
What means connected ? 

And I have changed the query to query(B, 6m, now-1m) but without success. The datapoints contain still NULL values. 
Then I have changed the aggregate function from last() to max(), but the datapoint don't want to go above NULL.

**Comment by torkelo** [comment]
please use community site for questions.

**Comment by daniellee** [comment]
@svenkirsten I meant change to null not to connected. Connected means if there is a null value that the trend line continues on rather than show the gap.
