### ISSUE TITLE
Canvas: Datalink not formatting dashboard time range correctly

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#83345]
When using data links in canvas and providing the dashboard time range, the resulting data link is not formatted correctly (missing a `?` in the url)

This hopefully will be a straightforward one liner fix 😬 

https://github.com/grafana/grafana/assets/22381771/7ebd8497-a5ce-4653-b045-a4c4c1f261fb

[debug-Data links in Canvas-2024-02-23 16_09_32.json.txt](https://github.com/grafana/grafana/files/14389773/debug-Data.links.in.Canvas-2024-02-23.16_09_32.json.txt)

**Comment by nmarrs** [comment]
On closer review it seems like this is not actually broken and just requires the user to set up the data link url correctly by adding a `?` to pass the time range as query parameter

I am worried giving this is how things are currently working that auto including a `?` may break existing setups (and logic to determine this case might be a little messy / have edge cases with regression of functionality / break existing data links.

Canvas example 

TBD

Timeseries works exactly the same way

TBD

cc @lukasztyrala I think I am comfortable closing this issue out given the above findings. Any objections?

**Comment by lukasztyrala** [comment]
No objections, the documentation for [Data links](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/) could benefit from making it clear that the `?` will not be returned by, for example, ${__url_time_range}.

<img width="785" alt="docs_data-links" src="https://github.com/grafana/grafana/assets/141744/6ed5120f-34c3-4ee7-b33d-a8bd89e69632">

**Comment by imatwawana** [comment]
@nmarrs @lukasztyrala - It makes sense to me to just take out the `?` in the docs to avoid confusion. Do you think we need to say anything explicit about adding the `?` when writing your variables?

**Comment by nmarrs** [comment]
@imatwawana - I think we need to keep the `?` in the docs as that is required for the variable to be included as a query parameter in the URL

I think what @lukasztyrala is getting at is that when a user is creating a data link and including a time range variables in the url (via `${__url_time_range}`) they might assume that will return `?time=x` while in reality it just returns `time=x` and as it is missing the `?` breaks / doesn't work. 

So I think all we need to do is add a line in the docs saying that you must form query parameter syntax yourself (i.e. `?${__url_time_range}&${__value.time}`) <- note the explicit `?` + subsequent `&` which chains multiple url params together

**Comment by imatwawana** [comment]
I understood what @lukasztyrala was getting at, but I see your point too. I'll prep a PR today.

**Comment by imatwawana** [comment]
@nmarrs & @lukasztyrala - Please take a look when you have time:
https://github.com/grafana/grafana/pull/84074
