### ISSUE TITLE
CloudWatch: Call AWSDatasourceSettings.Load in LoadCloudWatchSettings

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#83341]
**What is the chore?**:
A lot of the [LoadCloudWatchSettings](https://github.com/grafana/grafana/blob/2146f6ce1f622f0b03bc88720010d3ce1f58293d/pkg/tsdb/cloudwatch/models/settings.go#L26) function is duplicated in [awsds.AWSDatasourceSettings.Load](https://github.com/grafana/grafana-aws-sdk/blob/825cd34af7ab64a0510f2b44f44e6e7f084c9a59/pkg/awsds/settings.go#L114). Since `CloudWatchSettings` wraps `awsds.AWSDatasourceSettings`, it should call `Load` on the wrapped settings first and then set the remaining settings. Note while doing this that CloudWatchSettings has additional fields that we still have to set after calling load.

**Is there anything else we need to know?**:

**Comment by foehammer127** [comment]
@iwysiu Pull request ready for review.
