### ISSUE TITLE
Canvas: Consider supporting datalink functionality for any data driven element

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#83346]
We have received some general feedback that the limitation of only being able to have data links for metric value / text elements is a little limiting. Instead we should consider enabling data links for any element that can be driven by data.

**Comment by lukasztyrala** [comment]
In the meantime we could make [the docs](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/canvas/) a bit more clear about no current support for datalinks with other elements than metric-value:
<img width="813" alt="Screenshot 2024-02-28 at 09 02 06" src="https://github.com/grafana/grafana/assets/141744/e405f967-4112-4ff3-8fbf-12da87ed69ad">

The instructions above suggest that once a data link is created, all other elements using certain fields will display data links as well (this is true, actually, but it does not work as expected).

Maybe @imatwawana could chip in? :-)

**Comment by nmarrs** [comment]
@imatwawana Metric value + text elements currently support data links. With [this new PR](83870), that list extends to also include rectangle + ellipse elements 😬
