### ISSUE TITLE
Canvas: Datalink tooltip positioning glitch

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#83344]
When using data links in canvas there is a potential edge case where the placement of the tooltip is off and based on the previous element's positioning. This may be a regression caused / not addressed by this fix for another data link issue: https://github.com/grafana/grafana/pull/82213

https://github.com/grafana/grafana/assets/22381771/c5a40af2-0909-4544-8db4-92cf4aa2f842

[debug-Data links in Canvas-2024-02-23 16_09_32.json.txt](https://github.com/grafana/grafana/files/14389773/debug-Data.links.in.Canvas-2024-02-23.16_09_32.json.txt)

**Comment by lukasztyrala** [comment]
BTW, the datalink for the text element works differently than the rectangle.

[debug-Panel Title-2024-02-27 19_11_16.json.txt](https://github.com/grafana/grafana/files/14424122/debug-Panel.Title-2024-02-27.19_11_16.json.txt)

https://github.com/grafana/grafana/assets/141744/c662f199-3f02-4962-b91f-eecc4ecd8f85
