### ISSUE TITLE
Metric Selection does not work

### ISSUE THREAD

**Issue by awptechnologies** [grafana/grafana#83369]
### What happened?

When adding virtualization to dashboard i can no longer select a metric. It just spins and never shows any thing.

### What did you expect to happen?

Normally i can select from all of my metrics from Prometheus such as home assistant entity node explorer, etc. 

### Did this work before?

I don't know for sure the version. I use shepherd to update my docker swarm services every night and the last time i used this while it was working was 3 or 4 days ago. 

### How do we reproduce it?

1. Go to dashboard
2. Click add virtualization.
3. Under select metric option it spins but never loads anything. 

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: Latest
OS: Debian
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

If it helps when using the build section this happens. If i switch to code instead it seems to show my metrics.

**Comment by awptechnologies** [comment]
I know this I probably dumb question. But when I look at the image tags on prom/prometheus.  They all start with a v. Do I need to put a v infront of the image you recommended.

**Comment by itsmylife** [comment]
Hi @awptechnologies Thanks for reporting the issue. The issue might be related to https://github.com/prometheus/prometheus/pull/13633
If you are using Prometheus v2.50.0, could you please upgrade it to v2.50.1 and clear the browser cache and try again?

Related issue: https://github.com/grafana/grafana/issues/80185

**Comment by itsmylife** [comment]
I am closing this and please feel free to open a new issue or reopen this one if you face the same issue. But upgrading and clearing the cache will solve the issue for sure.
