### ISSUE TITLE
Alert manager: Authorization header is missing

### ISSUE THREAD

**Issue by UpBlueio** [grafana/grafana#83365]
### What happened?

We use the Prometheus Datasource. We use a custom auth wrapper on top of Prometheus that only accepts oauth2 tokens. When creating an alert in the alert manager. Everything works fine. The token is used for all the dashboards and alert rule preview. When saving the Alert Rule, all rules get the same status: No data. In the backend i see that all requests from alert manager get a 403 with the message: "authorization header is missing"

### What did you expect to happen?

That the alert manager backend sends the request with a forwarded OAuth Identity

### Did this work before?

I don't know. This is the first time we implement the Alert Manager

### How do we reproduce it?

1. Create a Prometheus datasource
2. Enable "Forward OAuth Identity"
3. Create a Alert Rule
4. Wait a while
5. Get a NoData label

### Environment (with versions)?

Grafana: 10.3.1
OS: Kubernetes
Browser: Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Latest embedded Prometheus datasource

**Comment by KaplanSarah** [comment]
Can you clarify whose OAuth identity is being used to run the alert manager query?  Alerts are run by the system - not a logged in user.

**Comment by UpBlueio** [comment]
When the alertmanager runs in the background, no OAuth identity is used. I checked this by using webhook.site as datasource url. For now i implemented an username/password in the datasource so we can use the alert manager.

**Comment by KaplanSarah** [comment]
Alerts are run by the system and not a user.  There are no plans to implement Oauth for the system user.  It looks like you found a work-around so we will close the issue.
