### ISSUE TITLE
Dashboards: Sharing modal is retained in the url generated to share the dashboard

### ISSUE THREAD

**Issue by narendratl** [grafana/grafana#83378]
### What happened?

I created a link to share the dashboard. When I opened the link in other tab, sharing modal is retained in the dashboard

![Share_link3](https://github.com/grafana/grafana/assets/161302864/869d0ff6-ad87-4c78-9aba-c0ce7774c3da)

### What did you expect to happen?

Sharing modal should not be retained when a dashboard is shared

### Did this work before?

This is observed with version 10.3.3 This is not observed with version 7

### How do we reproduce it?

1. Generate the link to shared the dashboard
2. Open the link in other tab
3. Sharing modal will be displayed along with the dashboard in the new tab

### Environment (with versions)?

Grafana: 10.3.3 
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by evictorero** [comment]
Hi @narendratl thanks for reporting this. A was [merged](https://github.com/grafana/grafana/pull/81976) a few days ago and will be released on the next Grafana version.
