### ISSUE TITLE
Refreshing the edit view causes the panel to not render properly

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#83375]
I think ["table view"](https://github.com/grafana/grafana/pull/83077) in the edit view caused an issue with navigating directly to the edit view. If you're in the edit view and refresh the browser, the panel will not render properly.

I've tried to figure out why, but I'm a bit stuck.

https://github.com/grafana/grafana/blob/d5adcf350a3801bdb93a931ab3983699af98fe55/public/app/features/dashboard-scene/panel-edit/VizPanelManager.tsx#L74
If the `{ $data: undefined }` is removed here, it works as expected for the normal view, but not for table view. But setting this as undefined seems critical for the solution for table view in this PR.

**Comment by harisrozajac** [comment]
This was fixed by updating scenes to `3.8.0`
