### ISSUE TITLE
No alert service for Splunk Datasource

### ISSUE THREAD

**Issue by ShuPr001** [grafana/grafana#8338]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Currently only Graphite, Prometheus, InfluxDB and OpenTSDB can be used in alerting rules. 

Sadly support for more data sources is going to take some time. In order to add support for more requires new backend plugin capability (https://github.com/grafana/grafana/issues/6841) which is still some time off, then the data source plugin needs to be re-implemented in Go.

**Comment by vikram-yerneni** [comment]
> Currently only Graphite, Prometheus, InfluxDB and OpenTSDB can be used in alerting rules.
> 
> Sadly support for more data sources is going to take some time. In order to add support for more requires new backend plugin capability (#6841) which is still some time off, then the data source plugin needs to be re-implemented in Go.

Was this ever implemented @torkelo ? The alerting mechanism for Splunk datasource is something I am trying to implement in our organization, I want to see if its feasible.

**Comment by torkelo** [comment]
It’s coming soon

**Comment by vikram-yerneni** [comment]
Thanks @torkelo
