### ISSUE TITLE
chart offset by 1 hour

### ISSUE THREAD

**Issue by zkrvova** [grafana/grafana#83395]
### What happened?

![Unbenannt](https://github.com/grafana/grafana/assets/161316231/fa1a8408-c64e-4093-9fc8-103a85bb864a)
The chart starts plotting from 12 o'clock, even though the data appears from 11 o'clock."
![Unbenannt1](https://github.com/grafana/grafana/assets/161316231/c4f0d5d0-e769-4472-b2a5-4d82476eb213)

### What did you expect to happen?

The chart muss starts plotting from 11 o'clock.

### Did this work before?

I don´t know.

### How do we reproduce it?

Every chart does this

### Environment (with versions)?

Grafana:"commit": "81fef5b4b4",
  "database": "ok",
  "version": "8.0.4"
OS: Windows 10
Browser: Chrome Version 122.0.6261.70

### Grafana platform?

I don't know

### Datasource(s)?

MySQL

**Comment by gabor** [comment]
hi @zkrvova , i see that the data-points are not in a sequential order, could you adjust your sql query to have the timestamps ordered? (with some form of `ORDER BY`).

does that fix the problem?

if not, please adjust the sql query to only return a very small amount of data points (let's say `LIMIT 3`), then show us the same screenshot you did above. thanks!

**Comment by zkrvova** [comment]
![image](https://github.com/grafana/grafana/assets/161316231/a8e03bfd-10cf-4c21-bf27-2fd8d0ced415)
Here are 5 values, but now -27

**Comment by gabor** [comment]
as we have no feedback, we'll close the issue for now, when we get more info, we can of course reopen it. thanks!
