### ISSUE TITLE
ElasticSearch: Permit "field" to be parsed to a variable

### ISSUE THREAD

**Issue by alisson276** [grafana/grafana#8339]
Grafana version: 4.3.0-pre1
Datasource: Elasticsearch
OS: CentOS 7
If is tried to use "field": "$variable" in query of Variables, the variable is not resolved and the query for the elasticsearch.

Tryied:
Create a variable named $test, type Custom with value "AAA,BBB"
Select $test ='AAA' in a dashboard.
Set another variable named named $test1 with query = {"find": "terms", "field": "$test"}

Result: 
{"find": "terms", "field": "$test"}

Espected result:
{"find": "terms", "field": "AAA"}

**Comment by davkal** [comment]
Will be addressed soon in an effort to interpolate all kinds of fields for template variables.
