### ISSUE TITLE
[Bug] Receiving no data alerts for data that doesn't exist

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#8340]
- What Grafana version are you using?
4.2.0 also occurred in 4.1.1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Windows Server 2008

I have some alerts set up to monitor a few metrics on hard drive space, memory etc... However I keep getting no data alerts on these alarms I have set up. The issue is when it emails me the graph for the alert the data is completely wrong. For example this alert was sent today.
![cvlix9qnemyyzanlfjlc](https://cloud.githubusercontent.com/assets/572187/25916664/14cc4bfc-358b-11e7-97c1-11aba92e740b.png)

As you can see it's claiming we had around 22 GB of disk today, however we haven't had that much on that disk in about a month. Here is a graph of today's data, you can see it doesn't match up at all.
<img width="1294" alt="screen shot 2017-05-10 at 2 16 15 pm" src="https://cloud.githubusercontent.com/assets/572187/25916745/62ff57ec-358b-11e7-963f-d3b5a3c84a15.png">

<img width="593" alt="screen shot 2017-05-10 at 2 18 26 pm" src="https://cloud.githubusercontent.com/assets/572187/25916825/a5d05738-358b-11e7-9af8-ed369b27c835.png">
<img width="565" alt="screen shot 2017-05-10 at 2 18 49 pm" src="https://cloud.githubusercontent.com/assets/572187/25916829/a9b6a82a-358b-11e7-9675-40da74b826a5.png">

**Comment by torkelo** [comment]
what does your InfluxDB query look like?

**Comment by antiquechrono** [comment]
Here you go.

<img width="844" alt="screen shot 2017-05-10 at 2 23 29 pm" src="https://cloud.githubusercontent.com/assets/572187/25917009/4d0f21dc-358c-11e7-91e2-d9a50e8e548c.png">

**Comment by antiquechrono** [comment]
I also forgot to mention that these alerts do not show up in the alert history.

<img width="775" alt="screen shot 2017-05-10 at 2 29 03 pm" src="https://cloud.githubusercontent.com/assets/572187/25917291/264ae364-358d-11e7-882b-ed5773b45d5f.png">

**Comment by torkelo** [comment]
try setting a lower limit on your group by time interval, like`>10s` if you write data every 10 seconds. 

The missing history data we have an issue for that already.

**Comment by antiquechrono** [comment]
Why would the min time interval cause completely wrong alert data to be generated? I can't even figure out what day that data it emailed me came from.

**Comment by torkelo** [comment]
well the alert was for no data (in your screenshot), which looked correct as there was no data to the right of the graph. 

As for the values being different in the screenshot that is strange. It could be depending on your query and query aggregation method that the values returned by your query change depending on how big the graph is as the auto group by time interval is dynamic and depends on time range and how many pixels the graph has so it's important to have correct aggregation function in your query

**Comment by antiquechrono** [comment]
Thanks for replying. I guess this is really two issues for me. What is causing all of these no data situations to happen, and why the graphs are so off.

Is there anything I can do to stop these spurious no data alerts? I have noticed that sometimes Grafana loads half the data or none of the data on the dashboards. Maybe this has something to do with querying influx. The data is always being written, maybe sometimes the alert engine does a query and something goes wrong with that process which is why it's so random? Maybe having alerts retry with a max retry and time between retires would solve this issue.

On the other hand there's the graphs being wildly off. Here's another one that happened today. The RAM here was sitting at around 4.5 GB when this alert issued. I do not see how taking the mean could cause the numbers to be off so much.

![mgrymxfcnmb9ftg2i02z](https://cloud.githubusercontent.com/assets/572187/25965539/e6be9044-364d-11e7-8fef-86abc1fcf6f0.png)

Here's what the actual data looked like. We clearly never hit 2GB nor did we hit 14 GB.

<img width="676" alt="screen shot 2017-05-11 at 1 38 19 pm" src="https://cloud.githubusercontent.com/assets/572187/25965982/3085d6f0-364f-11e7-8da4-5ce03e3e4b81.png">

Well speak of the devil it just happened again while I was typing this and it's even weirder this time.

Here is what the graph currently looks like
<img width="684" alt="screen shot 2017-05-11 at 1 48 20 pm" src="https://cloud.githubusercontent.com/assets/572187/25966450/a718c4a2-3650-11e7-8885-77fb8f0c1090.png">

Here are the two alerts that were issued.

![2p81fubcfb5cv2v2oapd](https://cloud.githubusercontent.com/assets/572187/25966507/d572c942-3650-11e7-8be3-564b619279b4.png)

![okzzknkwnnms9t1wiyz0](https://cloud.githubusercontent.com/assets/572187/25966552/f4d99a0e-3650-11e7-9add-0e9e6e506000.png)

These alerts look absolutely nothing like the real data in the DB. This issue also seems to have gotten worse after I upgraded from 4.1.1 to 4.2.0 as it was occurring every week or so, now it's occurring daily. I think this should be reopened as a bug.

**Comment by daniellee** [comment]
@antiquechrono when you tried setting the minimum interval, what value did you set it to? Did it match the interval in which you are writing data to InfluxDB? This really sounds like an aggregation issue.

![image](https://cloud.githubusercontent.com/assets/434655/26056723/d2e4eb82-3976-11e7-84df-223c49f498ac.png)

**Comment by antiquechrono** [comment]
@daniellee As per torkelo's advice the data is being written at 10s so I tried >10s as the group by time interval. When that did not work I also tried >=10s and that did not work either. I'm really not sure why people keep suggesting that it's an aggregation issue because as you can see from the pictures the data in the alert emails looks nothing like the actual data in the database.

Also as an update I created an identical copy by hand of the dashboard and deleted the old one. Since then I have not received any more of these spurious alerts.

**Comment by daniellee** [comment]
@antiquechrono 

> Also as an update I created an identical copy by hand of the dashboard and deleted the old one. Since then I have not received any more of these spurious alerts.

Does this mean you don't have this error anymore on any of your dashboards?

**Comment by antiquechrono** [comment]
@daniellee 

Yes that is correct, after I deleted and remade an identical copy of the dashboard everything is now working. I have yet to receive any more of those weird alerts. Also the issue never occurred on any other dashboards. Maybe there was an issue in Grafana 4.1.1 with creating the alerts, but it seems to be working so far in 4.2.0.

**Comment by antiquechrono** [comment]
Okay I take that back. I have all my alerts paused and I just got an alert. Something is really screwed up here.

<img width="978" alt="screen shot 2017-05-16 at 3 39 49 pm" src="https://cloud.githubusercontent.com/assets/572187/26127186/1d8152fc-3a4e-11e7-80d3-9bb37995afef.png">

Alert Emails:
![vv9pb7i0vvly3wcacqbe](https://cloud.githubusercontent.com/assets/572187/26127202/258f39d2-3a4e-11e7-97b7-f6f027a37e22.png)

![ixudr5dua39acveda4k3](https://cloud.githubusercontent.com/assets/572187/26127207/2afd7dc0-3a4e-11e7-8c2f-0329e04f00e1.png)

Actual Data:
<img width="1113" alt="screen shot 2017-05-16 at 3 42 23 pm" src="https://cloud.githubusercontent.com/assets/572187/26127234/4c83dcd2-3a4e-11e7-8cc7-1c1a87062de3.png">

**Comment by torkelo** [comment]
Your metric queries seem to return very differently when executed from grafana server, I'd you use the panel share, option, then image link, check that, it will render panel as PNG on server, same process used in alerting, does the image look different then what you get in  your browser?

**Comment by antiquechrono** [comment]
So here's what I believe is happening. I deleted the old dashboard and recreated it from scratch. When I did that I decided I wanted to rename some things and change some graph colors. In particular I changed the color of the memory panel to from orange to red.

Currently here is what that memory panel looks like.

Screen grab:
<img width="1162" alt="screen shot 2017-05-17 at 12 24 01 am" src="https://cloud.githubusercontent.com/assets/572187/26139563/422b2120-3a97-11e7-8837-f53e23201a82.png">

Share link pic that you suggested:
![server](https://cloud.githubusercontent.com/assets/572187/26139577/59675f7a-3a97-11e7-9e35-84757218a061.png)

As you can see both of these are consistent. However if you look at my previous post the alert emails were sending a graph with the old text and orange line from the dashboard I deleted. So for some reason today it randomly emailed me an alert off a dashboard I deleted a few days ago. You can also see in those alert emails I received that it was pulling bad data somehow.

**Comment by torkelo** [comment]
Do you see the alert rule twice in the alert list page (using side menu), can you click on the alert rule an open it? 

We fixed an issue a couple of days ago that could cause issues with sqlite3 and concurrrent writes, which very rarely could cause issues where the dashboard was deleted but the alert rule deletion failed due to sqlite db locked.  (this problem is now fixed)

**Comment by antiquechrono** [comment]
The alert list does not contain any duplicates. Nor does it contain the deleted alert that triggered.

**Comment by torkelo** [comment]
And if you click on this memory alert where does it take you? How does the graph look compared to alert notification?

**Comment by antiquechrono** [comment]
It takes me to the appropriate dashboard and everything looks fine.

**Comment by torkelo** [comment]
and if you change the threshold temporarily (and save) to generate an alert, does the notification image still look strange?

**Comment by antiquechrono** [comment]
That alert looks fine. I also opened up the grafana.db file and the only alerts in the alerts table are what I expect to be there.

**Comment by antiquechrono** [comment]
Only thing I can find in grafana.db is an old snapshot of that dashboard which has the alert configuration in it and user and org id are set to -1. I'm not sure why that table row was never deleted as I deleted that snapshot a long time ago. In fact it has several snapshots in it that were supposed to be deleted.
