### ISSUE TITLE
app-plugins that contain a datasource plugin fail to load on Windows

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#83416]
i tested with the [zabbix](https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/) plugin and with the [IOT-twinmaker](https://github.com/grafana/grafana-iot-twinmaker-app) plugin, same behavior.

- you install the plugin
- when you try to create a data source configuration, and press [save&test] you get the error "Plugin unavailable"

i tried a datasource-plugin that is not an app-plugin  ( [csv](https://grafana.com/grafana/plugins/marcusolsson-csv-datasource/)), and that works correctly on windows.

i checked the logs, and here is the relevant output for all 3 plugins:

csv-plugin (this works on windows):
```log
DEBUG[02-26|16:19:11] starting plugin
    logger=plugin.marcusolsson-csv-datasource
    path=D:\\test\\grafana-v10.3.3\\data\\plugins\\marcusolsson-csv-datasource/gpx_csv-datasource_windows_amd64.exe
    args=[D:\\test\\grafana-v10.3.3\\data\\plugins\\marcusolsson-csv-datasource/gpx_csv-datasource_windows_amd64.exe]
DEBUG[02-26|16:19:11] plugin started                          
    logger=plugin.marcusolsson-csv-datasource
    path=D:\\test\\grafana-v10.3.3\\data\\plugins\\marcusolsson-csv-datasource/gpx_csv-datasource_windows_amd64.exe
    pid=12345
```

zabbix-plugin (does not work on windows)
```log
DEBUG[02-26|16:19:11] starting plugin
    logger=plugin.alexanderzobnin-zabbix-datasource
    path=gpx_zabbix-plugin_windows_amd64.exe
    args=[gpx_zabbix-plugin_windows_amd64.exe]
ERROR[02-26|16:19:11] Could not start plugin                   
    logger=plugins.backend.start
    pluginId=alexanderzobnin-zabbix-datasource
    error="exec: \"gpx_zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"
ERROR[02-26|16:19:11] Could not initialize plugin
    logger=plugins.initialization
    pluginId=alexanderzobnin-zabbix-datasource
    error="exec: \"gpx_zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"
```

iot-twinmaker plugin (does not work on windows)
```log
DEBUG[02-26|16:37:06] starting plugin
    logger=plugin.grafana-iot-twinmaker-datasource
    path=gpx_twinmaker_app_windows_amd64.exe
    args=[gpx_twinmaker_app_windows_amd64.exe]
ERROR[02-26|16:37:06] Could not start plugin
    logger=plugins.backend.start
    pluginId=grafana-iot-twinmaker-datasource
    error="exec: \"gpx_twinmaker_app_windows_amd64.exe\": executable file not found in %PATH%"
ERROR[02-26|16:37:06] Could not initialize plugin              
    logger=plugins.initialization
    pluginId=grafana-iot-twinmaker-datasource
    error="exec: \"gpx_twinmaker_app_windows_amd64.exe\": executable file not found in %PATH%"
```

it seems the `path` is not populated correctly in the failing cases.

**Comment by gabor** [comment]
issue originally reported for the zabbix plugin at https://github.com/grafana/grafana-zabbix/issues/1785

**Comment by academo** [comment]
Hi @gabor thanks for the report. We'll take a look.

**Comment by tolzhabayev** [comment]
Adding a bit more info from what I can see:

zabbix is an app with id: `alexanderzobnin-zabbix-app` that has a nested plugin / datasource with id `alexanderzobnin-zabbix-datasource`

This datasources has executable defined in plugin.json that is using a relative path:
https://github.com/grafana/grafana-zabbix/blob/e18caea127d84ee73981907eedb0a6571d27aef0/src/datasource/plugin.json#L9

So my assumption is this does not play well on windows.

**Comment by tolzhabayev** [comment]
This was resolved in https://github.com/grafana/grafana-plugin-sdk-go/pull/1007, please confirm @gabor

**Comment by gabor** [comment]
yes, i can confirm this fixes the windows problem, closing the issue. thanks for the fix!
