### ISSUE TITLE
Alerts worked fine for few days and stopped working now

### ISSUE THREAD

**Issue by Rajeshwnco** [grafana/grafana#8343]
![image](https://cloud.githubusercontent.com/assets/17207626/25940413/aee08832-35fb-11e7-8742-9d3073eed53e.png)

![image](https://cloud.githubusercontent.com/assets/17207626/25940455/cf831564-35fb-11e7-9db6-62b6e2629952.png)

If you see the first Image it has files processing and as per the alert rule in second image i got alert two days back that we are not receiving data from past 2hrs and then after few hours we got the data but grafana didnt alert the OK email which used to do before and also it still blinks with red marks.

please help with this if some one knew the solution.

Thanks in Advance....

**Comment by torkelo** [comment]
What does the state history say? Do you have grafana.log output from the timerange when the data started getting received again (when it should have moved to OK) ?

Your no data and execution rules say Keep Last State. And looks like data points are sparse. What does your query look like?

**Comment by Rajeshwnco** [comment]
Hi,

Thanks for the quick response and from below picture

1.       When we met the alert rule that we didn’t get data for 2 hrs we got one red bar alert and got email to me but after that

2.       If you see the green bar it means we got data at that time but I didn’t get the email since then and we keep on getting data but even then red graph is blinking don’t know why ?

3.       And for your question Your no data and execution rules say Keep Last State I use the same kind of rule for all the other applications I am working on and all of them work fine and below is the only application I got issue.
And as per me Iam thinking  no data and execution rules say Keep Last State is when grafana is not able to connect to graphite we get null data, so I said keep last state which will not give me wrong alaram.
[cid:image001.png@01D2CA0D.47C51690]

Thanks

**Comment by Rajeshwnco** [comment]
please find the query i am using 
![image](https://cloud.githubusercontent.com/assets/17207626/25968725/27e14224-3658-11e7-9129-675b6bebabba.png)

Thanks,
Rajesh

**Comment by Rajeshwnco** [comment]
Hi,

please let me know if you need any more information.

Thanks,
Rajesh

**Comment by Rajeshwnco** [comment]
Below id the picture i explained on the above red bar as error

![image](https://cloud.githubusercontent.com/assets/17207626/26006929/f8fbd990-3703-11e7-804e-2222513cef4e.png)

**Comment by torkelo** [comment]
This might have fixed it, https://github.com/grafana/grafana/issues/7992

And we are also going to fix this in next couple of days, will give you more info on why the alert happened:

**Comment by torkelo** [comment]
If you want to troubleshoot more you can enable debug logging for graphite , http://docs.grafana.org/alerting/rules/#troubleshooting 

will give you more info on the query and response from graphite might explain why the alert triggered if this happens again

**Comment by Rajeshwnco** [comment]
Hi,

The alert happend for good as my alert rule is fire an alert if we dont get feed for 2hrs from now, there by we got red bar and alert till here its good and worked as expected

# but the problem is graph didn't recover and send and alert by saying OK when we got the feed back to normal, i am posting the same graph above one to make it more clear.

![image](https://cloud.githubusercontent.com/assets/17207626/26123085/4a54d894-3a3f-11e7-9978-338f3172fea2.png)

And the below is the graph at present today which is still alerting like as if we didnt get feed from long back

![image](https://cloud.githubusercontent.com/assets/17207626/26123136/71b100ac-3a3f-11e7-9d2d-22caff378006.png)


please let me know if you need any info from my side.

Thanks in Advance...

**Comment by torkelo** [comment]
This should be fixed in master and latest nightly build, will be included also in 4.3 stable
