### ISSUE TITLE
[Bug] Missing documentation in [auth.proxy] for ldap_sync_ttl and whitelist

### ISSUE THREAD

**Issue by haidaraM** [grafana/grafana#8345]
Grafana 4.2
Centos 7

In the `grafana.ini` there are two options that are not documentated in the lastest documentation http://docs.grafana.org/installation/configuration/#auth-proxy :
```
;ldap_sync_ttl = 60
;whitelist = 192.168.1.1, 192.168.2.1
```
These two options were added by this PR https://github.com/grafana/grafana/pull/6895

**Comment by marefr** [comment]
Fixed by #9796
