### ISSUE TITLE
[Feature request] Dashboard: organization/user specific variables

### ISSUE THREAD

**Issue by danmx** [grafana/grafana#8350]
Grafana Version: 4.2.0
Data source: AWS ElasticSearch (more on the way)

Having organization and/or user specific global variables (e.g. their names) available in templating would allow creation of more personalised dashboards.

This feature plus some query magic could solve [#1313](https://github.com/grafana/grafana/issues/1313)

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/1959

**Comment by torkelo** [comment]
kind of (very similar to #1959) so closing
