### ISSUE TITLE
Security: Let user configure if autocomplete should be turned on/off 

### ISSUE THREAD

**Issue by khushijain21** [grafana/grafana#83501]
**Why is this needed**:

Users should be able to configure if autocomplete on Input field should be turned on/off as sensitive data can be breached from the browser. This may configured in grafana.ini

**What would you like to be added**:

Users should be able toggle autocomplete on/off. 

**Who is this feature for?**
Everyone

**Comment by eledobleefe** [comment]
First of all, thanks for raising this. 
Are you able to explain what you believe the security issue with autocomplete is? I'm not sure there is an issue here, as this is native browser behaviour. [Browsers also typically don't obey ](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields) `autocomplete=off`, so there's only so much we could do in Grafana. If users/admins wish to limit autocomplete on websites, it should be disabled in the web browser instead.
I'm going to close this issue for now, but if there's a change we need to make we can reopen it.

**Comment by chalapat** [comment]
@eledobleefe  During the Burp scan of grafana, following vulnerability is shown.  If there is a provision for user to configure then atleast, it is taken care in supported browsers. Also not disabling autocomplete may cause problems in obtaining PCI compliance.
Please share your views
![image](https://github.com/grafana/grafana/assets/25923985/636b62be-a99a-4c97-bde5-6f955dee0a7f)

**Comment by eledobleefe** [comment]
Hi @chalapat,
We still think this is a native browser behaviour and there's only so much we could do.
Regarding PCI compliance, it is part of our compliance certifications, as you can see here: [trust.grafana.com](https://trust.grafana.com/)
Thanks again, we appreciate your concern for Grafana's security.

**Comment by chalapat** [comment]
@eledobleefe  Thanks for the link. In the link i see, grafana is compliant with PCI DSS.  and in the scan report that i shared, it is mentioned for PCI compliance it is required it to be off. Can you let us which tool is used to get the compliance?

**Comment by eledobleefe** [comment]
As I have found recently, I have mixed up the information as the PCI compliance refers to the parts of Grafana Cloud that accept payments, and not the Grafana dashboarding product (this repo). As a developer, I don't have the context, but you could ask for more information on [trust.grafana.com](http://trust.grafana.com/)
