### ISSUE TITLE
[Bug] Receiving state change notification although nothing should trigger state change

### ISSUE THREAD

**Issue by samlinbris** [grafana/grafana#8351]
Please include this information:
- What Grafana version are you using?
4.2.0-beta1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
docker repo `grafana/grafana:4.2.0-beta1`  on top of ubuntu16.04
- What did you do?
set alert to fire notification when CPU usage > 80%
- What was the expected result?
nothing should fire as cpu usage is < 2%
- What happened instead?
alert state was always at `OK`, somehow fires another `OK` status notification with no pre-existing warning state

here's what's in my log
```
CPU usage
t=2017-05-11T04:53:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=4 newState=ok prev state=alerting
t=2017-05-11T04:53:30+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=4 sent count=1
t=2017-05-11T04:53:30+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/graphite-machine-metrics?&panelId=1"
t=2017-05-11T04:53:31+0000 lvl=info msg=uploaded logger=alerting.notifier url=https://phoenix-metrics-grafana.s3.amazonaws.com/tfRl0AxnenuqvWlwwKt5.png
t=2017-05-11T04:53:31+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=2 isDefault=false
t=2017-05-11T04:53:31+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=4 notification=phoenix-alerts
```

 
<img width="1574" alt="screen shot 2017-05-12 at 12 40 27 pm" src="https://cloud.githubusercontent.com/assets/5134976/25980172/3aa841ec-3710-11e7-93af-74e9d05e4821.png">
I have received 2 confusing OK notification throughout the past 30 days. Although there wasn't a pre-existing ALERT notification to trigger an OK notification - an OK notification was still sent. My alert rule was set to fire notifications when cpu usage > 80%, as the graph suggested at no point was the CPU usage > 80%. However, I still received a redundant OK alert.

Thanks in advance for taking a look into this.

**Comment by torkelo** [comment]
The graph shows an alert state change, so the rule did go to alerting state. If you zoom in is there also an OK state change? 

If you go to alert rule tab and the state history you can see more detail on the state changes. The rule might have triggered due to query error (your time series db responding with error code). Or maybe it's time sensitive, sometimes derivatives can cause temporary spikes depending on time range. What does your query look like? What does your alert rule look like? 

To investigate further you can also enable debug logging for the relevant time series database you use:
http://docs.grafana.org/alerting/rules/#troubleshooting

**Comment by samlinbris** [comment]
Hi @torkelo 

Thanks for getting back to me, here are my queries and alert rule. I have also updated grafana to 4.2.0 (stable). On the graph it appears to fire an alerting message however the query has never gone pass the threshold.

<img width="181" alt="screen shot 2017-05-15 at 9 28 28 am" src="https://cloud.githubusercontent.com/assets/5134976/26038693/5f854eb8-3951-11e7-87f5-15f326a3494a.png">

<img width="1567" alt="screen shot 2017-05-15 at 9 32 40 am" src="https://cloud.githubusercontent.com/assets/5134976/26038701/7d233cb4-3951-11e7-9183-999104490917.png">

<img width="1074" alt="screen shot 2017-05-15 at 9 28 49 am" src="https://cloud.githubusercontent.com/assets/5134976/26038696/6ba5c7ae-3951-11e7-987e-286bff399fe5.png">

<img width="955" alt="screen shot 2017-05-15 at 9 30 26 am" src="https://cloud.githubusercontent.com/assets/5134976/26038704/89dd51e2-3951-11e7-95a3-78890970914c.png">

**Comment by torkelo** [comment]
could have been a request error (execution error), currently you dont see why the alert triggered in the history or in the annotation. We are going to add that soon .

**Comment by torkelo** [comment]
#7257
