### ISSUE TITLE
Reduce expression: raw data to series when datasource is elasticsearch on latest Grafana 10.3.3

### ISSUE THREAD

**Issue by yordanmanov** [grafana/grafana#83528]
### What happened?

Hello,
I was in the process of upgrading our Grafana instance from 9.5.2 (open source) to the latest 10.3.3 and I noticed when my datasource is Elasticsearch and I've selected several fields to group by the reduce expression no longer presents the information as label value rather than only "Series", based on those labels we are able to properly route events in Elasticsearch to team owners and present them with brief information about the issue in the description of the alert(description is send to Slack).
More about the issue you can find in the below two screenshots.

<img width="1305" alt="Screenshot 2024-02-27 at 15 49 08" src="https://github.com/grafana/grafana/assets/65708360/b0eb8081-7c83-410a-aa66-c6712e00fafe">

The first ^ screenshots shows how it was working until now with the label values in the reduce expression which are the fields that I've used to group the data from elasticsearch.

The description of the alert looks like this and it works perfectly on 9.5.2
<img width="670" alt="Screenshot 2024-02-27 at 16 10 29" src="https://github.com/grafana/grafana/assets/65708360/5ec3cecb-d839-450c-a66b-a6a3a295c670">

And we route based on the label_owner value:
<img width="482" alt="Screenshot 2024-02-27 at 16 10 42" src="https://github.com/grafana/grafana/assets/65708360/c9931571-6995-4672-a7db-4cb7a858cc8c">

--------------------------
<img width="912" alt="Screenshot 2024-02-27 at 15 57 06" src="https://github.com/grafana/grafana/assets/65708360/2ccd2cb8-322e-4b69-83e3-ea1b59555871">

In the second screenshot ^ you can see now the labels (HOSTNAME & message) are transformed into "Series" and we do not have full control of the message displayed in slack as we cannot refer the same way as in 9.5.2 in the alert description.

Not sure if its something on our end that we can modify in the alert definition, but I've tried almost everything and the labels are not presented.

PS. I've tried it on Ubuntu based env and CentOs, also from Ghrome & Safari browser issue still persisted.

### What did you expect to happen?

I truly believe that it was not intended the Elasticsearch - alert configuration link to work like this in v10, so it should be fixed to be as in version 9.5.2 as its really useful when you have control over the labels.

### Did this work before?

Yes, it worked perfectly with Grafana v 9.5.2, I've waited for v10.3.3 as there Grafana resolved an issue that we cannot bypass to upgrade. (silence was not working when the source label had dot in the name eg. test.test)

### How do we reproduce it?

1. Install Grafana 10.3.3
2. Configure Elasticsearch as datasource
3. Create an alert that uses fields as an option to group by results
4. Create reduce expression of the query 
5. Labels are no longer available in the reduce expression they appear as "Series"

### Is the bug inside a dashboard panel?

No, its a bug in the alert configuration wizard.

### Environment (with versions)?

Grafana: 10.3.3
OS:  Linux 5.4.0-155-generic #172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux AND Linux 5.10.198-187.748.amzn2.x86_64 #1 SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Browser: Safari (16.6), Chrome (121.0.6167.85)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by GitHamburg** [comment]
The same issue **+1**. After upgrading Grafana to Grafana v11.0.0-pre, when selecting the Elasticsearch data source in the alert rules and using the "Group By Terms" option, only "Series 1, Series 2, ... Series N" are displayed.

![grafana-es-series1](https://github.com/grafana/grafana/assets/16780183/5a2598f2-3321-4c98-bc9d-3c952fcf0863)

![grafana-es-series1-1](https://github.com/grafana/grafana/assets/16780183/27de2efe-852a-4df4-a97a-a01a7380fded)

**Comment by SagenKoder** [comment]
Same issue here as described by the original poster.
