### ISSUE TITLE
[Bug] tsdb.HandleRequest() error time: invalid duration $interval

### ISSUE THREAD

**Issue by rootingbill** [grafana/grafana#8353]
Hi guys,

i tried to integrate Alarms in into my existing dashboard, but it's not working. Everytime i add a new Alert i receive the following error: 

`result
firing true
state alerting
conditionEvals = true
timeMs 4.633ms
error tsdb.HandleRequest() error time: invalid duration $interval`

![image](https://cloud.githubusercontent.com/assets/1809834/25991726/961ad744-3704-11e7-99fa-07de9a8ac3df.png)

This is how the Query A looks like:

![image](https://cloud.githubusercontent.com/assets/1809834/25991773/ca66aac8-3704-11e7-9f9d-0712de19ec3d.png)

Interval is set to "auto". Even if i remove the variable $interval from the query it's still not working and giving me the same error. The value "1" in my Alert here is just an example. 

Just for the clearification my graph:
![image](https://cloud.githubusercontent.com/assets/1809834/25991949/66eef706-3705-11e7-8b5d-2f0396827b1c.png)

System:
- Grafana 4.2.0
- InfluxDB 1.2.2
- Ubuntu 16.04 LTS

**Comment by torkelo** [comment]
Do you have a group by time set blow your queries? If you specify a fixed interval, like 1m or 10s what happens then? 

Very strange, no other reports with issues relating to $interval in group by time with InfluxDB

**Comment by torkelo** [comment]
Also check any relevant logs from grafana.log

**Comment by rootingbill** [comment]
I had a group by time set (by $Interval). I removed it for testing purposes, but still no notification and also receiving an error:

![image](https://cloud.githubusercontent.com/assets/1809834/25996466/ba8bc7ba-3717-11e7-8431-ae45f6c291bc.png)

I tried with Group by time interval: 10s, but receiving the same error:

![image](https://cloud.githubusercontent.com/assets/1809834/25996621/7fbd0e72-3718-11e7-949c-be397e155c71.png)


Grafana.log is not showing any error.

**Comment by torkelo** [comment]
do you have manually created variable named  `variable` ?

**Comment by rootingbill** [comment]
Hi torkelo,

sorry for the late answer, but i was on vacation. Can you explain me which variable do you mean? i don't have a variable called `variable`.

**Comment by torkelo** [comment]
Are you still getting this error? 

```
result firing true state alerting conditionEvals = true timeMs 4.633ms error tsdb.HandleRequest() error time: invalid duration $interval
```

Try upgrading to 4.3 and resave edit the alert query (just make a minor change then change back, or if that does not work remove the query and re add it ) then save dashboard.

**Comment by winmasta** [comment]
Have same error

Error: tsdb.HandleRequest() error time: invalid duration $inter

when i create alert it becomes active because of this error

**Comment by daniellee** [comment]
@winmasta what does your query look like? Does it contain `$inter` or `$interval`? `$inter` is not an inbuilt variable.

**Comment by cxwcfea** [comment]
I got the same error.
Yes, my query contains $inter, it is a template variable defined by me, its type is interval, and in my query, it appears in "Group by time interval $inter". 
I have the problem in V4.4.1, but in v4.1.2 there is no error for the same configuration.

Any idea about how to fix it  ?

**Comment by torkelo** [comment]
No fix, alert rule queries do not support user defined template variables

**Comment by cxwcfea** [comment]
I mean how to fix the problem in my side.
The same query works in v4.1.2, so if you decide to make it not a valid usage in newer version (like v4.4.1), then what is the recommended way to achieve the same purpose in these version ?

**Comment by torkelo** [comment]
Template variables has never worked in alerting there has been no change here. 

You can  use the built in __interval variable

**Comment by dariusz-m** [comment]
I had the same or similar problem:
![image](https://user-images.githubusercontent.com/17393515/42223166-66bd5794-7ed7-11e8-95e5-73848f399b1b.png)

To solve this, you have to look at options on metrics tab and change "Min time interval" to e.g. 5s

![image](https://user-images.githubusercontent.com/17393515/42223126-4d073b30-7ed7-11e8-839b-a300700f5055.png)
