### ISSUE TITLE
Shows more results in legend than the search criteria matches

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#8354]
Using Grafana 4.2 and here's an incorrect graph:

![image](https://cloud.githubusercontent.com/assets/1611494/25992621/1517d1b0-36ff-11e7-8217-a16f08f36d99.png)

You can see the search criteria clearly specifies one Component, but on the graph it is showing multiple components. 

When the same search criteria is put on Kibana, it produces correct result, and it shows only one component. 

![image](https://cloud.githubusercontent.com/assets/1611494/25992825/bc6d7d8e-36ff-11e7-8185-133fc788271d.png)

**Comment by torkelo** [comment]
very strange. Unable to replicate (and no other reports on problems with the lucene query string). 

Can you investigate the query sent to ES? https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50 

Check the json sent to ES (the full query) and paste it here. Is it including your specified lucene query string filter?

**Comment by oazabir** [comment]
Here's the request:

```
{"search_type":"count","ignore_unavailable":true,"index":["ovlog-2017.05.11","ovlog-2017.05.12"]}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1494543600000","lte":"1494584241167","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"group:ovlog AND server:cbs137a092 AND  component:WfProcMgrPSTNGenAsset"}}]}},"aggs":{"3":{"terms":{"field":"server","size":10,"order":{"1":"desc"},"min_doc_count":0},"aggs":{"1":{"max":{"field":"duration"}},"4":{"terms":{"field":"component","size":10,"order":{"_term":"desc"},"min_doc_count":0},"aggs":{"2":{"date_histogram":{"interval":"2m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1494543600000","max":"1494584241167"},"format":"epoch_millis"},"aggs":{"1":{"max":{"field":"duration"}}}}}}}}}}
```

Kibana Visualize produces this query:
```
{"index":["ovlog-2017.05.12"],"search_type":"count","ignore_unavailable":true}
{"size":0,"query":{"filtered":{"query":{"query_string":{"query":"group:ovlog AND server:cbs137a092 AND component:WfProcMgrPSTNGenAsset","analyze_wildcard":true}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":1494569932581,"lte":1494584332581,"format":"epoch_millis"}}}],"must_not":[]}}}},"aggs":{"3":{"date_histogram":{"field":"@timestamp","interval":"5m","time_zone":"Europe/London","min_doc_count":1,"extended_bounds":{"min":1494569932581,"max":1494584332581}},"aggs":{"4":{"terms":{"field":"server","size":5,"order":{"2":"desc"}},"aggs":{"2":{"avg":{"field":"duration"}},"5":{"terms":{"field":"component","size":5,"order":{"2":"desc"}},"aggs":{"2":{"avg":{"field":"duration"}}}}}}}}}}
```

**Comment by torkelo** [comment]
The query looks identical, only difference I can see is a whitespace more in the query sent by grafana, can a double white space effect the lucene query? Have you tried with only the component filter condition? Try removing the extra white space

**Comment by oazabir** [comment]
I have removed the whitespace, did not make any difference. The problem is still there.

I see Grafana generates a bool query with a filter & query inside it. Where kibana generates a filtered query with a filter & query inside it. The type of search query is different.

**Comment by torkelo** [comment]
Lucene query string should still work the same, try changing min doc count to 1, on the terms aggregation, think that will solve it
