### ISSUE TITLE
[Bug] Auto interval not working correctly when panel overrides relative time

### ISSUE THREAD

**Issue by pprkut** [grafana/grafana#8355]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS 7
- What did you do?
I have a dashboard with an interval variable set to "auto" and step count 30. The dashboard shows data of the last 1 hour.
If I set one panel to override the relative time to "Last 24h", the interval won't adjust. Rather than 30 steps, it shows 30 steps/h
- What was the expected result?
Showing 30 steps for the overridden timeframe
- What happened instead?
Showing 30 steps/h for the overridden timeframe

Could reproduce on [http://play.grafana.org](http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&orgId=1&edit&tab=time%20range&var-datacenter=Asia&var-host=server%5C5&var-host=server%5Csecond%5Cslash&var-summarize=$__auto_interval)

**Comment by torkelo** [comment]
Manually created interval variables are global for the whole dashboard, and not panel specific
