### ISSUE TITLE
Math expression broken in v10.3.3

### ISSUE THREAD

**Issue by iXingo** [grafana/grafana#83562]
### What happened?

Grafana Math expression has broken since v10.3.3, and make charts mess up.
before: 
![image](https://github.com/grafana/grafana/assets/3634305/8319e9b9-345a-4b7d-9413-d2e9762d70a5)

after:
![image](https://github.com/grafana/grafana/assets/3634305/a7d225d3-9a37-45bf-af5f-7da622f23aeb)

### What did you expect to happen?

Grafana Math expression works like 10.2.4

### Did this work before?

Yes, it works fine in v10.2.4

### How do we reproduce it?

1. upgrade the version from 10.2.4 to 10.3.3
2. use multi-frame data, and make 2 queries and one Math expression, let $A -$B
3. $C should be the result of  $A -$B, but now it's messed up.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: v10.3.3
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elastcisearch

**Comment by iXingo** [comment]
is there anyone look at this?

**Comment by iXingo** [comment]
even works in 10.3.1 , but does not works on 10.3.3, just want to know what happened to expression 10 10.3.3

**Comment by iXingo** [comment]
@yuri-tceretian @kylebrandt @bohandley

**Comment by tonypowa** [comment]
hi @iXingo 

thank you for creating this issue

The reproduction steps are helpful, but could you provide a bit more detail on the queries that you are using to produce $A and $B?

**Comment by kylebrandt** [comment]
This should be fixed via https://github.com/grafana/grafana/pull/84485 in the 10.4.1 and 10.3.5 releases.

**Comment by iXingo** [comment]
verified, it is fixed now. thanks
