### ISSUE TITLE
[Feature Request] `/api/health` with Prometheus-compatible value

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#8357]
Beta 4.3 has an `/api/health` endpoint.

Can you make the page display

`grafana_database_up 1`

or

`grafana_database_reachable 1`

or something along those lines while everything is OK on top of the HTTP 200? Alternatively, this data could be the start of a proper `/metrics` endpoint which always returns said text and only switches between 1 and 0 for the value.

**Comment by torkelo** [comment]
yes, I guess a numeric database up status could be added along side the string status code

**Comment by RichiH** [comment]
The only potential problem I realized is this:

If others rely on the endpoint to throw 5xx, you can never use the same endpoint to display 0 in case of an error; that metric simply goes away as far as Prometheus is concerned.

**Comment by torkelo** [comment]
Well this is not really a metrics endpoint

**Comment by torkelo** [comment]
More of licenses probe

**Comment by torkelo** [comment]
That should be liveness probe

**Comment by RichiH** [comment]
Agreed.

Having the initial string in there for now should be a good first start.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9187
