### ISSUE TITLE
Traceql streaming option is not available after traceQLStreaming feature toggle  enabled 

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/grafana#83581]
### What happened?

hi team,

Traceql streaming option is not available in UI after traceQLStreaming feature toggle. 
http_over_streaming_enabled option is also set in tempo.

below are the feature toggles are set 
[feature_toggles]
  enable = tempoSearch tempoBackendSearch tempoServiceGraph tempoApmTable traceQLStreaming correlations

below option is not available, which show complete/in progress streaming result in UI.
![image](https://github.com/grafana/grafana/assets/128572542/76c34511-e6c8-4484-8add-4a051c8a0ceb)

### What did you expect to happen?

if i enable  traceQLStreaming feature toggle , the steaming progress option in UI should show.

### Did this work before?

no

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.2
OS: windows  11
Browser: edge 
 

### Grafana platform?

Kubernetes

**Comment by joey-grafana** [comment]
Hello, can you perhaps post a short clip of what you are doing in the UI? Also, can you update to a more recent version of Grafana?

If `traceQLStreaming` is enabled and the [live](https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-live/) feature is also enabled in your environment, then as soon as you click the run query button in your Tempo datasource, the streaming query should be run.

Note: if your configuration has something like
[live]
max_connections = 0

this will effectively disable Grafana live functionality which is needed to run the streaming query over websockets.

**Comment by fabrizio-grafana** [comment]
Closing as stale, but feel free to reopen it if there are updates.

**Comment by g3david405** [comment]
btw: I use latest version of grafana(11.1.3)

**Comment by joey-grafana** [comment]
Hey yeah that's a bug. The [init](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L251) function sets the Tempo version, which in turn is used to see if streaming can be enabled with the version of Tempo. 

This seems to only run in explore and not dashboards.

@adrapereira for vis. This might help with your investigation but at the very least something to be aware of.
