### ISSUE TITLE
[Feature request] UNIX socket permissions

### ISSUE THREAD

**Issue by 5lava** [grafana/grafana#8358]
Version 4.3 beta 1.
Please add an option to explicitly set UNIX socket permissions.
Thank you.

**Comment by torkelo** [comment]
which unix socket?

**Comment by 5lava** [comment]
The one Grafana is listening on. #4030

**Comment by torkelo** [comment]
Just specify socket path to a directory with the permissions you want

**Comment by daniellee** [comment]
http://stackoverflow.com/questions/5977556/how-can-i-change-the-permissions-of-a-linux-socket-file

Also read the section `Pathname socket ownership and permissions` in the [man pages](http://man7.org/linux/man-pages/man7/unix.7.html). You might have to stop Grafana while changing permissions and then start it again.

**Comment by 5lava** [comment]
@torkelo, @daniellee — thank you very much for your responses, I appreciate it.
But please look at the problem from a different perspective.

Default path for sockets is usually ```/run```, which is tmpfs, and my distro's Grafana init.d script doesn't care about creating a special directory ```/run/grafana```. Okay, I can fix it and make it create directory with corresponding permissions. I'll just have to remember doing that each time I upgrade Grafana (or install somewhere else). Alternatively I can use ```/tmp/grafana``` (as ```/tmp``` is persistent). Somewhat dirty, but that'd do it.

Oh, I have a really bad habit of having things tidy, strict and secure, so I'd like to make ```/run/grafana``` permissions no higher than 750 (ideally 710). But that would make socket file not group writable, which defeats the purpose. So... okay, I'll make directory permissions 770. I can live with that.

Hmm, but my socket file turns out to be 750 anyways — not group writable. Because default system umask is 022. Okay, just one more fix to init.d script... 

_"Hey, ideal permissions for sockets are 660!"_ — inner perfectionist keeps repeating annoyingly.
_"Shut up"_.

So.. long story short, an option in grafana.ini to set socket file permissions explicitly would make life so much easier!

**Comment by torkelo** [comment]
I wonder if there settings umask will change the socket permissions as well, because Grafana does not create the socket this is done by the standard Golang http library, with not permission settings that I can find in the Golang lib

Regarding umask in the init.d script, had a PR open to set that I initd script and asked for feedback from community on what is best practices regarding setting umask in init.d script, but got no response and could not find other similar open source projects having umask set in their init.d script

**Comment by 5lava** [comment]
https://github.com/golang/go/issues/11822#issuecomment-123850227 could be helpful maybe?
But I know some people prefer umask being quite open (e.g. 0002, so things like logs can be world readable), but instead tightening per-file permissions (e.g. 660 for a socket). Since we can't guess everyone's need, I suggest leaving it to user.

I usually do it this way (pseudo-code):
```javascript
// temporarily set restrictive umask but remember original value
original_umask = umask(0777);

// create socket file
// since file permissions will be 000, prefer some temporary location
// so no 3rd-party script would be confused with existence of
// our (not yet usable) socket file
// also note that moving socket file across filesystems is generally
// bad idea, so we create temporary file right in the target directory
tmp_socket_filename = dirname(socket_filename) + "/some.tmp.filename";
bind(socket, tmp_socket_filename);

// restore umask
umask(original_umask);

// set desired socket permissions (they could be more open than umask,
// that's up to user's config!)
chmod(..., desired_permissions);
// alternatively we may want to make permissions not more open than umask
// but I'm not a big fan of this approach
// chmod(..., desired_permissions & (~original_umask))

// finally, move our ready-for-use socket to where it's expected to live
rename(tmp_socket_filename, socket_filename);
```


Regarding umask in init.d script — I can suggest standard Gentoo (flexible) way:

> /etc/conf.d/grafana
```javascript
GRAFANA_UMASK=xxx
```

>/etc/init.d/grafana
```javascript
start-stop-daemon ... \
	${GRAFANA_UMASK:+--umask ${GRAFANA_UMASK}} \
```

**Comment by skynet** [comment]
This is still a problem. My system is refusing to set permissions to 660 even if the parent /var/run/grafana has 771. I had to add `chmod 660 /var/run/grafana/grafana.sock` in /etc/init.d/grafana

**Comment by frankli0324** [comment]
the original issue author asked for:

> an option (in grafana.ini) to explicitly set socket file permissions

while grafana "fixes" this issue by implicitly setting socket file permissions.

https://github.com/grafana/grafana/blob/e402a8f27d9faabac8181c847b06014ae29af0d5/pkg/api/http_server.go#L473

well done...
