### ISSUE TITLE
/render/dashboard/ improvements

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#8363]
I am trying to use the /render/ endpoint to take a screenshot of the whole dashboard rather than just a single panel.  The request generally works great, but each panel shows a 'collapse' menu:

![image](https://cloud.githubusercontent.com/assets/705951/26007270/991c46d6-36f4-11e7-87cf-d4aab046ff07.png)

The 'height' parameter also behaves strangely.  The output image is the full height of the dashboard (great!) but it only loads data up to the height specified.  The workaround is to put in a very large height and it will load the whole page.  Weird, but OK.

**Comment by torkelo** [comment]
rendering whole dashboards is not supported right now, only individual panels

**Comment by IzakMarais** [comment]
@ryantxu: take a look at https://github.com/IzakMarais/reporter which generates pdf reports from grafana dashbaords
