### ISSUE TITLE
[Bug] Lazy loading of panels is too lazy

### ISSUE THREAD

**Issue by 5lava** [grafana/grafana#8365]
Version 4.3 beta 1.
Related to #5216.
Lazy loading behavior should apply only when the panel is offscreen **entirely**.
Currently a panel stop refreshing as soon as it gets scrolled just a tiny bit above the visible browser window (and it's especially annoying when editing graphs — gotta scroll up each time to see any change on the graph).
The problem doesn't appear if a panel gets scrolled to the bottom (and this is correct behavior).

Please look at the following screencast below. I set auto-refresh to 1 second. Notice when the spinning loading icon stops reappearing:

![screencast 2017-05-12 14-54-40](https://cloud.githubusercontent.com/assets/63829/26012617/1bbb393e-3723-11e7-9217-d87f0d5daa8f.gif)

Thank you.

**Comment by torkelo** [comment]
reverted lazy loading  due to internal Chrome deadlock bug, https://github.com/grafana/grafana/issues/8500
