### ISSUE TITLE
[Bug] Invalid data sources for static JSON dashboard definitions.

### ISSUE THREAD

**Issue by kujenga** [grafana/grafana#8366]
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Docker Container
- What did you do?
I created a dashboard in a Grafana instance running in Kubernetes that is talking to a Prometheus installation. I exported the working dashboard and saved it as a JSON file. I then tore down the running graphing instance and restarted it with modified settings such that in the `dashboards.json` section, `enabled` was set to `true` and `path` was set to the proper directory. I then manually setup the data source for the Prometheus instance we have in the same cluster using the same name that I had initially created it with (is there a way to do this automatically via static files?).
- What was the expected result?
I would expect that the dashboards appeared in static form with the same content that I had dynamically created.
- What happened instead?
The dashboards appear with a error message saying `Datasource named ${DS_MY_PROMETHEUS} was not found`. I can manually set the datasource to the proper value, but that fix disappears on page reload, leaving me with the same error message. Additionally, each JSON file has two dashboards showing in the UI, both with identical paths to them.

I also tried on a build from source on master, and the same issue occurs.

Additionally, importing the raw JSON file manually works, as I am able to select the correct data source in the import UI.

**Comment by torkelo** [comment]
Exported dashboards requires that you use the import process or import api, if you just want to save a json file of you currently dashboard use view json  in the dashboard setting menu

**Comment by torkelo** [comment]
Sorry for the bad English, on move and auto correct is messing it up

**Comment by kujenga** [comment]
Got it, thank you for the prompt response!

**Comment by dgellow** [comment]
> Exported dashboards requires that you use the import process or import api

@torkelo What do you mean by that? I exported a dashboard via the web interface, when I'm trying to load it using `GF_DASHBOARDS_JSON=enabled` or using the API via `curl -s -H "Content-Type: application/json" -XPOST http://admin:admin@localhost:3000/api/dashboards/db --data-binary "@/dashboards/my_dashboard.json"` I get the same error message than @kujenga.

## Error message
<img width="595" alt="screen shot 2017-06-08 at 14 43 17" src="https://user-images.githubusercontent.com/2451004/26929495-33f9c62c-4c5a-11e7-8227-e835073cfa68.png">

## Data sources
```
$ curl http://admin:admin@localhost:3000/api/datasources
[
  {
    "id":1,"orgId":1,"name":"Prometheus Production",
    "type":"prometheus",
    "typeLogoUrl":"public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access":"proxy",
    "url":"http://localhost: 9090",
    "password":"",
    "user":"",
    "database":"",
    "basicAuth":false,
    "isDefault":false,
    "jsonData":{}
  }
]
```
