### ISSUE TITLE
[Feature request] Positive Only option in Aggregation of Derivative

### ISSUE THREAD

**Issue by trevorndodds** [grafana/grafana#8367]
Grafana 4.2.0 using Elasticsearch 5.4.0

When displaying derivative stats eg (network) the counter keeps increasing and at some point the value resets making the next value a negative. This makes it impossible to use SUM with a valid result.
Would it be possible to have a selection on the derivative function to only use positive numbers?

For graphing I select a Y Axis as 0 but that doesn't help with a single stat SUM.
![image](https://cloud.githubusercontent.com/assets/10899305/26016096/9cc1e484-3731-11e7-833a-1ce657789c8d.png)

Elasticsearch has this option:
![image](https://cloud.githubusercontent.com/assets/10899305/26018343/3e29f172-373c-11e7-9e83-933a521fa4e6.png)

Thanks

**Comment by torkelo** [comment]
The derivative is down by elasticsearch so this logic needs to be implemented by elasticsearch

**Comment by trevorndodds** [comment]
Maybe the logic is there as it works in kibana, unless that positive bit is handled by the browser.

**Comment by torkelo** [comment]
Maybe there is an option that is not exposed by Grafana, can you check the derivative aggregation docs?
