### ISSUE TITLE
[Bug] Login page loads after DOMContentLoaded Event

### ISSUE THREAD

**Issue by yuribit** [grafana/grafana#8368]
When I open grafana on Safari or Chrome it takes several seconds to load the login page.
During that interval of time I see a white page in Safari and a black page in Chrome. I also noticed that the progress bar on Safari reaches 100% before the page is actually loaded. 
Here are the network timelines of two instances of grafana running in two geographically different places: 

![screen shot 2017-05-12 at 5 07 22 pm](https://cloud.githubusercontent.com/assets/1260900/26021019/4b436aba-373b-11e7-9fa8-91122ee5e379.png)

![screen shot 2017-05-12 at 5 20 50 pm](https://cloud.githubusercontent.com/assets/1260900/26021014/47a809e2-373b-11e7-97be-ff8e15a390b1.png)

As you can notice, in the first screenshot the load event was sent after 234ms while the login page loaded after 1.5s. In the second screenshot (same codebase, different server location) there are 7s between the load event and the login page.

I am trying to figure out why it's taking so long to load the login page from a different location but the load event should not be sent until the app is loaded.

- What Grafana version are you using?
4.2.0

**Comment by torkelo** [comment]
the load event does not relate to app loading, but html & images. The javascript & app are loaded async. 

With a slow connection I can load play.grafana.org (with cache disabled)
![image](https://cloud.githubusercontent.com/assets/10999/26048421/555a491a-3957-11e7-8010-a75b84818664.png)

With cache enabled it takes about 1s. 

Are you running an optimized official build? says 1/192 requests in your network footer, maybe your running a dev build?

**Comment by yuribit** [comment]
@torkelo, thank you, running an optimized build fixed the issue.
