### ISSUE TITLE
Dashboards: Refresh button is hidden when time picker is hidden

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana#83691]
### What happened?

When hiding time picker from dashboard the refresh button also gets hidden

### What did you expect to happen?

Hiding both time range picker and refresh button with hide time picker is bit miss leading.
That refresh button sometimes is required, when dashboard does not need a time picker we hide it, but then the refresh button will disappear and to reload a new set of data we need to refresh the whole dashboard page... Also the auto refresh dropdown will go away and we will not be able to set the refresh interval in that case.

### Did this work before?

I was since my first use of grafana ~ v4.x

### How do we reproduce it?

1. Create dashboard
2. Hide time picker from dashboard general settings
3. Go back to dashboard

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: <= 11.x
OS: Any
Browser: Any

### Grafana platform?

Kubernetes

**Comment by dprokop** [comment]
Duplicate https://github.com/grafana/grafana/issues/11782
