### ISSUE TITLE
[Bug] Singlestat produces nonsense values when using derivative function

### ISSUE THREAD

**Issue by zstephen** [grafana/grafana#8369]
Versions

* InfluxDB 1.2.2
* Grafana 4.2
* Ubuntu 16.04.2

Singlestat sometimes produces random and seemingly nonsense values when using derivative function

>SELECT derivative("value", 24h) FROM "smartmeter-meterage" WHERE $timeFilter

* Using a data value from "smartmeter-meterage" incrementally increases (each 15 mins) to show kWh of electricity used, it only goes up, like an odometer
* It's currently returning 47.914 and 27 from two separate Singlestat displays which both have the above command in use

**Comment by torkelo** [comment]
Singlestat shows what your query returns, so if your query returns seemly random values then that is what it shows. 

Please include the query response form InfluxDB, (check via open chrome dev tools network tab), and include your singlestat options. 

InfluxDB derivative function can be really tricky, many have issues with unexpected values with it

**Comment by zstephen** [comment]
Thanks @torkelo I've followed [these](https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50) instructions to provide your requested info.

Query String Parameters:
>db:electricity
q:SELECT derivative("value", 24h) FROM "smartmeter-meterage" WHERE time > now() - 24h
epoch:ms

Response:
>{"results":[{"statement_id":0,"series":[{"name":"smartmeter-meterage","columns":["time","derivative"],"values":[[1494635400849,9.502752745201812],[1494636300793,9.504592981100936],[1494637200692,9.793095317012805],[1494638100630,9.600659866184463],[1494639000723,9.503021853759902],[1494639900704,9.792206086831923],[1494640800604,9.505059770736763],[1494641700726,9.598699578120092],[1494642600642,19.009774656477862],[1494643500806,9.790209844821833],[1494644401010,9.597831942382232],[1494645300880,9.505372726344424],[1494646200738,19.2990306539035],[1494647100835,9.59897207911013],[1494648000730,9.505109612132731],[1494648900794,9.503317785599007],[1494649800775,9.792206860149655],[1494650700787,9.599869101522327],[1494651600888,9.502939161252373],[1494652500840,19.297026848490866],[1494653400791,9.600519728081336],[1494654300796,19.007899503123163],[1494655200753,38.68983516530002],[1494656100939,47.894126325891435],[1494657000667,28.904744414658776],[1494657900722,47.90107290908828],[1494658801559,28.869155395214854],[1494659701371,57.51600942584507],[1494660600853,57.441050154712464],[1494661501153,38.67511678546181],[1494662401202,67.00433527710376],[1494663301012,47.91413137584379],[1494664200921,38.69189799293971],[1494665101026,19.101762501494978],[1494666001026,28.80001639677424],[1494666900882,19.107047380468167],[1494667800867,28.896483300439638],[1494668700963,28.796938901864404],[1494669600930,28.897058890226173],[1494670501046,19.10154000469761],[1494671400943,28.803287202768118],[1494672301014,19.102496494021864],[1494673200935,19.297689035296738],[1494674100931,38.40017696709925],[1494675000996,19.10262254406866],[1494675901243,28.888079642971952],[1494676800958,9.507005587337616],[1494677701037,9.503169973028406],[1494678600962,19.393618003220453]]}]}]}


Have I missed anything else you needed?

**Comment by torkelo** [comment]
Singlestat options as well, did you look at the response? Does it conflict with what singlestat shows (depends if the singlestat stat option (avg, current etc)? 
.
How can can see if there is anything wrong in Grafana without knowing what data your query returns, your panel options, and what it currently shows

**Comment by zstephen** [comment]
Hi @torkelo I'm sorry if my posting is poorly structured. I'm trying to better understand what I need to look into and possibly provide so I can resolve or correctly report this issue.

I'll attempt to provide this info you've asked for, and I'm happy to provide more if I'm still missing key info.

When you mention the response, I noticed this when I try to query values without use of derivative then compared to a query with use of them.

I've included this picture to help visualise it, but have also included some details which hopefully will help drill down further.

![grafana 2017-05-16 16-14-55](https://cloud.githubusercontent.com/assets/10385295/26092327/bef332cc-3a53-11e7-9278-7eabdae5e6b3.png)


**No Derivative**

Query from GUI:

````
SELECT "value" FROM "smartmeter-meterage" WHERE $timeFilter
````


Query from Chrome:

````
db:electricity
q:SELECT "value" FROM "smartmeter-meterage" WHERE time > 1494828000000ms and time < 1494914400000ms
epoch:ms
````

Reponse from Chrome:

>{"results":[{"statement_id":0,"series":[{"name":"smartmeter-meterage","columns":["time","value"],"values":[[1494828001034,33319.1],[1494828901060,33319.2],[1494829801200,33319.5],[1494830701054,33319.699],[1494831601300,33319.9],[1494832501296,33320.198],[1494833401258,33320.3],[1494835201082,33320.8],[1494836101324,33321.299],[1494837001055,33321.6],[1494837901163,33321.9],[1494838801053,33322.201],[1494839701109,33322.598],[1494840601117,33323.1],[1494841501031,33323.299],[1494842401056,33323.5],[1494843301103,33323.801],[1494844201109,33324],[1494845101137,33324.198],[1494846001200,33324.499],[1494846901047,33324.8],[1494847801014,33324.899],[1494848701116,33324.998],[1494849601105,33325.1],[1494850501106,33325.299],[1494851401062,33325.401],[1494852301099,33325.5],[1494853201116,33325.6],[1494854101127,33325.9],[1494855001133,33326.3],[1494855901192,33326.899],[1494856801166,33327.2],[1494857701163,33327.6],[1494858601211,33328.099],[1494859501165,33328.499],[1494860401136,33328.998],[1494861302174,33329.401],[1494862201171,33329.798],[1494863101216,33330.3],[1494864001354,33330.7],[1494864901241,33331.2],[1494865801358,33331.6],[1494866701152,33332.099],[1494867601136,33332.601],[1494868501206,33332.998],[1494869401113,33333.1],[1494870301099,33333.299],[1494871201201,33333.401],[1494872101247,33333.6],[1494873001267,33333.699],[1494873901239,33333.9],[1494874801200,33334],[1494875701112,33334.3],[1494876601180,33334.598],[1494877501114,33335.001],[1494878401222,33335.398],[1494879301208,33335.699],[1494880201192,33336.099],[1494881101205,33336.4],[1494882001153,33336.899],[1494882901135,33337.1],[1494883801240,33337.299],[1494884701151,33337.401],[1494885601162,33337.5],[1494886501278,33337.6],[1494887401219,33337.699],[1494888301274,33337.798],[1494889201210,33337.9],[1494890101269,33338],[1494891001401,33338.201],[1494892801219,33338.4],[1494893701221,33338.499],[1494894601256,33338.598],[1494895501398,33338.7],[1494896401392,33338.8],[1494897301370,33338.899],[1494898201300,33339.001],[1494899101309,33339.1],[1494900001358,33339.2],[1494900901291,33339.299],[1494901801337,33339.398],[1494902701336,33339.5],[1494903601321,33339.699],[1494904501357,33340],[1494905401314,33340.198],[1494906301200,33340.4],[1494907201273,33340.499],[1494908101314,33340.8],[1494909001343,33340.899],[1494909901314,33341.1],[1494910801361,33341.2],[1494911701311,33341.401],[1494912601273,33341.6],[1494913501249,33341.699]]}]}]}


**24h Derivative**

Query from GUI:

````
SELECT derivative("value", 24h) FROM "smartmeter-meterage" WHERE $timeFilter
````

Query from Chrome:

````
db:electricity
q:SELECT derivative("value", 24h) FROM "smartmeter-meterage" WHERE time > 1494828000000ms and time < 1494914400000ms
epoch:ms
````

Response from Chrome:

>{"results":[{"statement_id":0,"series":[{"name":"smartmeter-meterage","columns":["time","derivative"],"values":[[1494828901060,9.599719656217935],[1494829801200,28.795511524076815],[1494830701054,19.10711689386239],[1494831601300,19.290723502607037],[1494832501296,28.608119773887946],[1494833401258,9.792408079021362],[1494835201082,24.002350739439777],[1494836101324,47.891142815642645],[1494837001055,28.904617447369255],[1494837901163,28.79655558372927],[1494838801053,28.89952454547183],[1494839701109,38.1096491194746],[1494840601117,48.1915526227561],[1494841501031,19.105834400801367],[1494842401056,19.295464523120543],[1494843301103,28.89449749513357],[1494844201109,19.103858193299608],[1494845101137,19.007404676468173],[1494846001200,28.893997845805547],[1494846901047,28.90092122569528],[1494847801014,9.504346659183478],[1494848701116,9.502918485939956],[1494849601105,9.792122748227237],[1494850501106,19.103985814916292],[1494851401062,9.792475775451841],[1494852301099,9.503604202403102],[1494853201116,9.599822842692266],[1494854101127,28.799642169877373],[1494855001133,38.3997313623177],[1494855901192,57.500267846984215],[1494856801166,28.8968330535857],[1494857701163,38.40012758298492],[1494858601211,47.901455277298794],[1494859501165,38.40196557978662],[1494860401136,47.90549867615667],[1494861302174,38.64344127657326],[1494862201171,38.15455185013677],[1494863101216,48.18955830494112],[1494864001354,38.39412643876144],[1494864901241,48.00602263770863],[1494865801358,38.39500145357561],[1494866701152,47.914974396180575],[1494867601136,48.19283920101107],[1494868501206,38.10903754843288],[1494869401113,9.79301489767084],[1494870301099,19.104300604585827],[1494871201201,9.79088425188926],[1494872101247,19.103029246146395],[1494873001267,9.50379409986779],[1494873901239,19.296588217173287],[1494874801200,9.600415710586455],[1494875701112,28.802837125532772],[1494876601180,28.60583744886299],[1494877501114,38.690833126518086],[1494878401222,38.10740645879585],[1494879301208,28.89644080542573],[1494880201192,38.4006930539279],[1494881101205,28.895580040739667],[1494882001153,47.90677474661062],[1494882901135,19.296393600700647],[1494883801240,19.10177483633713],[1494884701151,9.792968468780751],[1494885601162,9.503884720866692],[1494886501278,9.598756678602985],[1494887401219,9.504622900172706],[1494888301274,9.503419915218615],[1494889201210,9.792697161573983],[1494890101269,9.599368504208664],[1494891001401,19.293166985125442],[1494892801219,9.552969078762688],[1494893701221,9.503974683291029],[1494894601256,9.50362945781523],[1494895501398,9.790454914427139],[1494896401392,9.600063799318782],[1494897301370,9.504231108197937],[1494898201300,9.792766700238628],[1494899101309,9.503909290560722],[1494900001358,9.599473430675383],[1494900901291,9.504709999355063],[1494901801337,9.503514428531892],[1494902701336,9.792005023654955],[1494903601321,19.104319389691668],[1494904501357,28.894852367623425],[1494905401314,19.00891498387736],[1494906301200,19.39445442103022],[1494907201273,9.503220554001738],[1494908101314,28.89471463686907],[1494909001343,9.50368497010663],[1494909901314,19.296639238678228],[1494910801361,9.599491390989215],[1494911701311,19.29708637718793],[1494912601273,19.104802668019612],[1494913501249,9.504254316494869]]}]}]}

**Comment by torkelo** [comment]
ok, but your questions was regarding singlestat? 

>It's currently returning 47.914 and 27 from two separate Singlestat displays which both have the above command in use

Did you check what your query returns and compared that to the singlestat value showwn? (Options tab, stat option). 

It's impossible for me to see any issue where as your just showing numbers. You need to show your query response, panel options, and what panel shows for THAT EXACT QUERY execution. Then we can see if we can understand why the value was shown.

**Comment by zstephen** [comment]
I think I'm slowly getting an understanding of exactly what you're after, thanks for your ongoing help..

Here's some more info you requested..

Chrome Query String Parameters:

````
db:electricity
q:SELECT derivative("value", 24h) FROM "smartmeter-meterage" WHERE time > now() - 24h
epoch:ms
````

Chrome Response:

>{"results":[{"statement_id":0,"series":[{"name":"smartmeter-meterage","columns":["time","derivative"],"values":[[1494836101324,47.891142815642645],[1494837001055,28.904617447369255],[1494837901163,28.79655558372927],[1494838801053,28.89952454547183],[1494839701109,38.1096491194746],[1494840601117,48.1915526227561],[1494841501031,19.105834400801367],[1494842401056,19.295464523120543],[1494843301103,28.89449749513357],[1494844201109,19.103858193299608],[1494845101137,19.007404676468173],[1494846001200,28.893997845805547],[1494846901047,28.90092122569528],[1494847801014,9.504346659183478],[1494848701116,9.502918485939956],[1494849601105,9.792122748227237],[1494850501106,19.103985814916292],[1494851401062,9.792475775451841],[1494852301099,9.503604202403102],[1494853201116,9.599822842692266],[1494854101127,28.799642169877373],[1494855001133,38.3997313623177],[1494855901192,57.500267846984215],[1494856801166,28.8968330535857],[1494857701163,38.40012758298492],[1494858601211,47.901455277298794],[1494859501165,38.40196557978662],[1494860401136,47.90549867615667],[1494861302174,38.64344127657326],[1494862201171,38.15455185013677],[1494863101216,48.18955830494112],[1494864001354,38.39412643876144],[1494864901241,48.00602263770863],[1494865801358,38.39500145357561],[1494866701152,47.914974396180575],[1494867601136,48.19283920101107],[1494868501206,38.10903754843288],[1494869401113,9.79301489767084],[1494870301099,19.104300604585827],[1494871201201,9.79088425188926],[1494872101247,19.103029246146395],[1494873001267,9.50379409986779],[1494873901239,19.296588217173287],[1494874801200,9.600415710586455],[1494875701112,28.802837125532772],[1494876601180,28.60583744886299],[1494877501114,38.690833126518086],[1494878401222,38.10740645879585],[1494879301208,28.89644080542573],[1494880201192,38.4006930539279],[1494881101205,28.895580040739667],[1494882001153,47.90677474661062],[1494882901135,19.296393600700647],[1494883801240,19.10177483633713],[1494884701151,9.792968468780751],[1494885601162,9.503884720866692],[1494886501278,9.598756678602985],[1494887401219,9.504622900172706],[1494888301274,9.503419915218615],[1494889201210,9.792697161573983],[1494890101269,9.599368504208664],[1494891001401,19.293166985125442],[1494892801219,9.552969078762688],[1494893701221,9.503974683291029],[1494894601256,9.50362945781523],[1494895501398,9.790454914427139],[1494896401392,9.600063799318782],[1494897301370,9.504231108197937],[1494898201300,9.792766700238628],[1494899101309,9.503909290560722],[1494900001358,9.599473430675383],[1494900901291,9.504709999355063],[1494901801337,9.503514428531892],[1494902701336,9.792005023654955],[1494903601321,19.104319389691668],[1494904501357,28.894852367623425],[1494905401314,19.00891498387736],[1494906301200,19.39445442103022],[1494907201273,9.503220554001738],[1494908101314,28.89471463686907],[1494909001343,9.50368497010663],[1494909901314,19.296639238678228],[1494910801361,9.599491390989215],[1494911701311,19.29708637718793],[1494912601273,19.104802668019612],[1494913501249,9.504254316494869],[1494914401232,19.29636441703424],[1494915301374,19.10098392841353],[1494916201394,19.295571292715827],[1494917101299,9.601015312542165],[1494918001380,19.006275563551792],[1494918901520,28.891511537730846],[1494919801451,19.297473926739148]]}]}]}

Panel Options & Value:
![grafana panel options 2017-05-16 17-47-53](https://cloud.githubusercontent.com/assets/10385295/26095139/f45c16ac-3a5f-11e7-81a1-8862092d3fd6.png)

**another thing I noticed**
I noticed with the above graph from my previous post before this one, is that spikes in derivative output tend to happen when usage increases (i.e. the incremental readings from smartmeter-meterage increase noticably) if this is unrelated, I can file it separately. I assume that a momentary spike in the value that the 24h derivative is based on should not cause a significant increase in the derivative output itself?

**Comment by torkelo** [comment]
So looks like Grafana is showing the correct value. 

You will have to seek help in the InfluxDB docs & support site if you think there is something wrong with the InfluxDB derivative function, many are having trouble with that function as it's tricky to use and sometimes can give confusing results.

**Comment by zstephen** [comment]
Thanks, just to be clear and help highlight the issue for when I raise it with InfluxDB, does this graph and other data in the post help show that the issue is not Grafana and is likely to be InfluxDB?

https://github.com/grafana/grafana/issues/8369#issuecomment-301686844

If so, then I'll follow up with them.

And thanks again for your help in nailing this issue down. I've learned a lot through this process.
