### ISSUE TITLE
InfluxDB query fails after updating Grafana

### ISSUE THREAD

**Issue by langeschro** [grafana/grafana#83708]
### What happened?

After updating Grafana from 10.1.1 to 10.3.3 one of our queries is failing.
In Grafana we see the error:
`InfluxDB returned error: error parsing query: found $, expected ; at line 1, char 131`

The query is:
` SELECT mean(total) AS "total", mean(used) as "used" FROM "disk" WHERE "host" =~ /$server$/ AND "path" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), "host", "path"`

With Grafana 10.1.1 we can see in explore:
`SELECT mean(total) AS "total", mean(used) as "used" FROM "disk" WHERE "host" =~ /service\.virtual-cluster\.lan$/ AND "path" =~ /^\/$/AND $timeFilter GROUP BY time($interval), "host", "path"`

After updating to Grafana 10.3.1 (and also with 10.3.3) we are seeing:
`SELECT mean(total) AS "total", mean(used) as "used" FROM "disk" WHERE "host" =~ /service\.virtual-cluster\.lan$/ AND "path" =~ /^/$/AND $timeFilter GROUP BY time($interval), "host", "path"`

As it can be seen the escaping of the path is wrong now. Instead of  "path" =~ /^\/$/ we now have "path" =~ /^/$/

### What did you expect to happen?

The query should continue to work

### Did this work before?

Yes, it works with 10.1.1 but fails with both 10.3.1 and 10.3.3.

### How do we reproduce it?

1. Create a similar query
2. Verify that the query sent to InfluxDB has now a wrong syntax with Grafana 10.3

### Environment (with versions)?

Grafana:  10.3.3
OS: Rocky Linux 8
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by langeschro** [comment]
This might be a duplicate of https://github.com/grafana/grafana/issues/83530 I am not completely sure.

**Comment by nishiki** [comment]
Hello, i have the same problem

**Comment by nishiki** [comment]
It's fixed for me with Grafana 10.4.0

**Comment by langeschro** [comment]
> It's fixed for me with Grafana 10.4.0

Also fixed for me with 1.4.0
With 1.3.4 it was broken as well.
