### ISSUE TITLE
[Feature request] Supporting Google Cloud Storage for external images

### ISSUE THREAD

**Issue by theckman** [grafana/grafana#8370]
Hi there,

Thank you for your hard work on Grafana. So far it's been simple to deploy and use, and it looks ***awesome***.

We're currently running the latest build of Grafana with a Prometheus backend. I was researching how to share images of graphs to my team via Slack, and found that you can configure Grafana to generate an image and push it to S3. Awesome! That should be simple enough to get going.

When seeing only S3 was supported, I could see that maybe becoming a slight hindrance in the future for me. Companies are starting to migrate things to GCP, mine included, so I can see there being interest in wanting to use Google Cloud Storage (their S3-equivalent product) for hosting all of their objects. I think this would include images generated from Grafana.

Has adding this support been considered for Grafana yet? I did some research and didn't find any tickets that seemed related.

**Comment by yesoreyeram** [comment]
We are interested in Azure storage  as well.

**Comment by syepes** [comment]
+1 for gcs

**Comment by saada** [comment]
@yesoreyeram https://github.com/grafana/grafana/pull/8956

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/8990

**Comment by PaulMazzuca** [comment]
Is there an example of what a gcs configuration should look like or if any special permissions need to be applied on the Google Cloud, because under the current configuration I receive a 404 in the logs?

I have a bucket called "test-bucket", and I have stored my service key in "/path/to/service/key.json". The bucket exists and the service key has permissions to write to gcs.

My config
```
[external_image_storage]
provider = gcs

[external_image_storage.gcs]
key_file = /path/to/service/key.json
bucket_name = test-bucket
```

however, the Grafana logs are returning

```
lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/DL2HETwpZu0rIqR9CvL6.png
lvl=dbug msg="Sending POST request to GCS" logger=gcsuploader
lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="GCS response status code 404"
```

**Comment by PaulMazzuca** [comment]
Just FYI, the configuration should be "bucket" not "bucket name" or maybe "bucket_name" as the configuration documentation suggests.
