### ISSUE TITLE
[Bug] Mysql datasource: Date not being properly displayed

### ISSUE THREAD

**Issue by geekangel** [grafana/grafana#8371]
Hi. I'm using 4.3.0-beta1. I added the mysql datasource and it works. But when I'm displaying the graphics there is an error in the date. It shows the date like 1969 (with no format). Using the FROM_UNIXTIME shows:
"MySQL response parsing error sql: Scan error on column index 0: unsupported Scan, storing driver.Value type time.Time into type *sql.RawBytes"

I checked and the unixtime information in the database is correct.

Please include this information:

- What OS are you running grafana on? Ubuntu 16
- What did you do? Tried to setup a graphic dashboard
- What was the expected result? A graphic depicting the values ordered by the date

- If related to metric query / data viz:

metrics_panel_ctrl.ts:121 Panel data error: Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error", headers: function}
angular.js?bust=1494733467831:12410 POST http://localhost:3000/api/tsdb/query 500 (Internal Server Error)
(anonymous) @ angular.js?bust=1494733467831:12410
sendReq @ angular.js?bust=1494733467831:12155
serverRequest @ angular.js?bust=1494733467831:11908
processQueue @ angular.js?bust=1494733467831:16648
(anonymous) @ angular.js?bust=1494733467831:16692
$eval @ angular.js?bust=1494733467831:17972
$digest @ angular.js?bust=1494733467831:17786
$apply @ angular.js?bust=1494733467831:18080
(anonymous) @ angular.js?bust=1494733467831:19924
completeOutstandingRequest @ angular.js?bust=1494733467831:6111
(anonymous) @ angular.js?bust=1494733467831:6390
metrics_panel_ctrl.ts:121 Panel data error: Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error", headers: function}
 

{from: "1494651600000", to: "1494737999999",…}
from
:
"1494651600000"
queries
:
[{refId: "A", intervalMs: 60000, maxDataPoints: 1143, datasourceId: 1,…}]
0
:
{refId: "A", intervalMs: 60000, maxDataPoints: 1143, datasourceId: 1,…}
datasourceId
:
1
format
:
"time_series"
intervalMs
:
60000
maxDataPoints
:
1143
rawSql
:
"SELECT↵  UNIX_TIMESTAMP(<time_column>) as time_sec,↵  <value column> as value,↵  <series name column> as metric↵FROM <table name>↵WHERE $__timeFilter(time_column)↵ORDER BY <time_column> ASC↵"
refId
:
"A"
to
:
"1494737999999"

The server response is:

{"timings":[null],"results":{"A":{"error":"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\u003ctime_column\u003e) as time_sec,\n  \u003cvalue column\u003e as value,\n  \u003cseries name column\u003e as' at line 2","refId":"A","meta":{"sql":"SELECT\n  UNIX_TIMESTAMP(\u003ctime_column\u003e) as time_sec,\n  \u003cvalue column\u003e as value,\n  \u003cseries name column\u003e as metric\nFROM \u003ctable name\u003e\nWHERE time_column \u003e FROM_UNIXTIME(1494651600) AND time_column \u003c FROM_UNIXTIME(1494737999)\nORDER BY \u003ctime_column\u003e ASC\n"},"series":null,"tables":null}},"message":"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\u003ctime_column\u003e) as time_sec,\n  \u003cvalue column\u003e as value,\n  \u003cseries name column\u003e as' at line 2"}

![screenshot from 2017-05-14 01-03-12](https://cloud.githubusercontent.com/assets/24721831/26031725/4c50cc96-3843-11e7-8f7b-5c568b761b67.png)

**Comment by torkelo** [comment]
What is your query? The response you pasted looks like an example query with syntax error

**Comment by geekangel** [comment]
The query that I was using was SELECT  (UNIX_TIMESTAMP(`Unixtimestamp`)) AS 'time_sec',`my_data` AS 'value',`unique_id` AS 'metric' FROM `mytable` 


The Unixtimestamp is the field wihtin my database that holds that information.

**Comment by torkelo** [comment]
An the response? No time filter in the query? What panel are you using? What are the panel options?

**Comment by shubhamod1** [comment]
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.

**Comment by nischalsamji** [comment]
Facing the same issue. Understand this is a mysql-go-driver bug. @torkelo Why is this bug closed? Is this fixed already in grafana?

**Comment by marefr** [comment]
@nischalsamji please upgrade to latest Grafana version.

**Comment by nischalsamji** [comment]
@marefr Currently on Grafana v5.0.1 (commit: a747ec3). Is there a later version than this?

**Comment by marefr** [comment]
@nischalsamji no. Please include the query you're using thanks

**Comment by iliesh** [comment]
@marefr i hahe the same issue: please see below the query:

```
SELECT
  UNIX_TIMESTAMP(test_time) as time_sec,
  avg(ping_time) as value,
  test_time AS metric
FROM devices_ping
WHERE $__timeFilter(test_time)
GROUP BY test_time
ORDER BY test_time ASC

```
this is Generated SQL:
```
SELECT
  UNIX_TIMESTAMP(test_time) AS time_sec,
  AVG(ping_time) AS VALUE,
  test_time AS metric
FROM devices_ping
WHERE test_time >= FROM_UNIXTIME(1521661508) AND test_time <= FROM_UNIXTIME(1521663308)
GROUP BY test_time
ORDER BY test_time ASC;
```


[root@username]# grafana-server -v
Version 5.0.3 (commit: 91162f3)
Thank You.

**Comment by marefr** [comment]
@iliesh the test_time AS metric looks weird. Please remove that or replace it with `'ping time' as metric.

If not that solves your problem, please include more information. 
* What exactly is your problem? A lot of comments above so want to make sure. 
* What panel type are you using, I guess graph panel? 
* What is your time range?
* Can you include the result of a `select top 10 test_time, ping_time from devices_ping` against the time range you're trying to visualize?

**Comment by iliesh** [comment]
@marefr,
The issue was:

> MySQL response parsing error sql: Scan error on column index 2: unsupported Scan, storing driver.Value type time.Time into type *sql.RawBytes

Removing 'test_time AS metric' solved the issue.
Thank You.
