### ISSUE TITLE
[Feature Request] Mysql datasource: macro for time range

### ISSUE THREAD

**Issue by Chris7** [grafana/grafana#8372]
Using the built-in grafana mysql data source, plotting bar graphs can result in very skinny bars that are nearly invisible. To fix this, I would like to limit the number of datapoints by adjusting my group by to be sensitive to the time range window selected, which would require access to the panel range limits. 

Instead of a macro, it would be nice if this was simple a variable I could reference such as `$__timeFrom()` $__timeTo()`.

**Comment by torkelo** [comment]
We plan to make more variables, like interval, and from and two, right now we only have the timeFilter

**Comment by Chris7** [comment]
Great! I just started using the mysql datasource and saw to put requests/feedback here. I really like that the format is raw SQL so I can easily do joins to assign metric names to FKs, etc.

**Comment by daniellee** [comment]
Fixed by #8578
