### ISSUE TITLE
Data lost on the Panel on Refresh or on changing the Window(eg: from 1 hour to 6 months)

### ISSUE THREAD

**Issue by aakarshit-batchu** [grafana/grafana#8374]
Please include this information:
- What Grafana version are you using? v 4.1.2
- What datasource are you using? orientdb
- What OS are you running grafana on? ubuntu 14.04
- What did you do? developed a datasource plugin for orientdb.On refresh the data is not retained.It is lost.Also on panel refresh the data is not reflecting on panel.

**Comment by torkelo** [comment]
Data lost? You mean empty graph? 

Did you check metric query troubleshooting guide on community site (linked to in new github issue template) 

Please include your query and the OpenTSDB response (find how you get this in the community site)
