### ISSUE TITLE
grafana alert rule only sends email once

### ISSUE THREAD

**Issue by bodycombathuang** [grafana/grafana#83749]
### What happened?

grafana alert rule only sends email once
![image](https://github.com/grafana/grafana/assets/20555274/e8901be3-a8e8-4455-8674-e290e036f600)

### What did you expect to happen?

grafana alert rule sends email after each evaluation

### Did this work before?

no

### How do we reproduce it?

1. create an alert rule with an alert condition
2. set evaluation period is 10 seconds
3 save the rule

I can see the state for the rule is always firing, but it just sends email to mailbox set in contact point once

### Environment (with versions)?

Grafana: 10.3.0
OS: windows
Browser: chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

influxdb

**Comment by tonypowa** [comment]
hi @bodycombathuang 

double check the `repeat interval` option in your notification policy > Timing options

pro tip: you can see what notification policy is routing your alert by clicking `Preview routing` within the alert rule editor.
