### ISSUE TITLE
Visualize each tag instance in a different graph with template

### ISSUE THREAD

**Issue by contactmat85** [grafana/grafana#8375]
Hi,
I create a grafana dashboard with different template to select different combination of tag from a influxdb dataset.  When I visualize in graph I can just see one graph at time, also enabling multiple selection I combine the information coming from the selected tag in one graph. 
Instead I would like to have one graph for each selected tag.
Is that possible?

Thanks

**Comment by maxtar** [comment]
I think you can use Repeat row feature http://docs.grafana.org/reference/templating/#templating at the end of the page.

**Comment by contactmat85** [comment]
Thanks! I tried and this replicate the selected graph in different windows. What if I would like to have them in the same window?

**Comment by maxtar** [comment]
@contactmat85 Sorry, I don't understand. What do you mean "in different windows"? This setting allow to duplicate rows or panels according template variables.

**Comment by contactmat85** [comment]
If I select the repeat option and I select three different value for a tag I end up with three graph in the same row, in three different panels. I would like to have them all in the same, one on top of the other

**Comment by maxtar** [comment]
:) Understand. If you want duplicate panels in the one row you need to use [repeating panels](http://docs.grafana.org/reference/templating/#repeating-panels) feature. :)

**Comment by contactmat85** [comment]
:( same problem... I want to force grafana to draw the graphs on the very same panel... to have a visual comparison. If I select repeat row I end up with multiple rows and repeat panels with multiple panels... I need all the graph in the same panel and same row

**Comment by maxtar** [comment]
You need to use variable in you request and do "group by" this vales.

**Comment by contactmat85** [comment]
![grafana](https://cloud.githubusercontent.com/assets/27950755/26052708/ac3b96bc-3966-11e7-983b-c824919b6d41.png)
 
I am doing like this... what is wrong?

**Comment by maxtar** [comment]
Try to set "group by" $content on the first place and time after that.

**Comment by contactmat85** [comment]
ok thats worked out!! Thanks a lot! :) 👍

**Comment by maxtar** [comment]
Glad to help. :)
