### ISSUE TITLE
Task: Improve Snapshot current modal option

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#83781]
**Why**
Issue related
https://github.com/grafana/grafana/pull/83550

**Task**
Improve the UI for this feature

Now with Scenes
![Image](https://github.com/grafana/grafana/assets/51436795/d5541d3c-9ad4-46e3-9710-b090abe6c4e4)

After generating the Snapshot

![Image](https://github.com/grafana/grafana/assets/51436795/3acbab56-e071-4b89-b6ed-d1bbce0de224)

Proposal
![Image](https://github.com/grafana/grafana/assets/51436795/57253f99-382d-4133-9ef4-985b64e46b96)

After generating the Snapshot

![Image](https://github.com/grafana/grafana/assets/51436795/8adb9cf5-c906-4e4e-8547-aa9d44c64476)
![Image](https://github.com/grafana/grafana/assets/51436795/0bc240cf-8b3e-45c3-b6e8-4a515a763b74)

**Comment by natydej** [comment]
**Main changes**

- Change the message and have inside a notification banner "informational" type
- Snapshot name field, should be with an * that means to be required
- Change the label of "expire" to be "expiration date"
- Make "1 hour" by default, since is the most used option and it will be the most updated option
- Change the order to be the options like "1 hour/1day/1week/Never"
- Change 7 Days to be 1 Week
- Change the "Local Snapshot" label on the button to be "Publish Snapshot"

**Comment by natydej** [comment]
Changing the copy, from a suggestion that @imatwawana made :) if we think we are missing things here, we can add that to the documentation and have a link, on the CTA of "Learn more"

**Design attached**
![Image](https://github.com/grafana/grafana/assets/51436795/0f449c3f-f115-478e-a763-e2fafc5da666)

**Message**
"Snapshots instantly share interactive dashboards publicly, but don't include queries and panel links. Anyone with the link can access the dashboard."

**Comment by kardoka** [comment]
Regarding snapshot creation, would it be possible to let the user assign the snapshot key in the UI? That would allow users to recreate snapshots while keeping the same URL as before.

**Comment by natydej** [comment]
This task is being tracked on this [issue](https://github.com/grafana/grafana/issues/88506)
