### ISSUE TITLE
[WANTED] Part-time writer for Documentation and Tutorials

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8379]
As the Grafana product and community continues to grow, we're realizing that we need to up our game when it comes to documentation and tutorials. 

Before posting a public ad, we wanted to first reach out to our core users and see if anyone is looking to pick up some extra work. This is a PAID position, fairly autonomous and expect that you both have an existing understanding of Grafana and can create visual assets to accompany your wonderful writing. Long-term, we hope it turns into a full-time role that encapsulates community engagement in addition to writing alone. 

Please email us at hello@grafana.com, tell us a little bit about yourself, include some links to writing examples and we'll go from there.

**Comment by oddlittlebird** [comment]
@marcusolsson , should we close this?

**Comment by marcusolsson** [comment]
I think it's probably safe to close this now :)
