### ISSUE TITLE
[Bug] middleware render hasn't been registered after upgrade to 4.3.0-beta1

### ISSUE THREAD

**Issue by szibis** [grafana/grafana#8380]
Upgrade from Grafana 4.2 to 4.3-beta1 on Ubuntu Trusty.

t=2017-05-15T19:28:15+0000 lvl=eror msg="Request error" error="middleware render hasn't been registered" stack="/usr/local/go/src/runtime/panic.go:489 (0x430e7f)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/render.go:654 (0x7a81b4)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/render.go:658 (0x7a81e0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/gzip/gzip.go:90 (0xb34a09)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aebaf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae174)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x780fdf)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7809aa)\n/go/src/github.com/grafana/grafana/pkg/middleware/util.go:24 (0xb3e38d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x79ea21)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x780cb2)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x780aab)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ec82)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79eba6)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb3df01)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x79ea21)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x780cb2)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x780aab)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ec82)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79eba6)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb3bbb2)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aebaf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae174)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x780fdf)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7809aa)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ec82)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:267 (0x7b0ee9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:301 (0x7aae0a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7a375c)\n/usr/local/go/src/net/http/server.go:2568 (0x68ddf2)\n/usr/local/go/src/net/http/server.go:1825 (0x68a1c2)\n/usr/local/go/src/runtime/asm_amd64.s:2197 (0x4603f1)\n"

Nginx gets "upstream prematurely closed connection while reading response header from upstream" and return 502 code on any action in Grafana from browser.

**Comment by szibis** [comment]
Same on latest nightly - grafana_4.3.0-7814beta1

**Comment by torkelo** [comment]
Strange, no other reports, could be something unique to your config? Can you share parts of your grafana.ini config? Specially [server] config.

**Comment by szibis** [comment]
```
[server]
# Protocol (http or https)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 127.0.0.1

# The http port  to use
http_port = 3003

# The public facing domain name used to access grafana from a browser
domain = grafana.example.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true

# The full public facing url
#root_url = %(protocol)s://%(domain)s:%(http_port)s/
root_url = https://%(domain)s/

# Log web requests
router_logging = true

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = true

# https certs & key file
cert_file =
cert_key =
```

**Comment by torkelo** [comment]
try to disable, gzip, and restart. Any change? 

Try to disable router_logging, restart, any change?

**Comment by rednasem** [comment]
I got the same error on Debian 8.7 when `enable_gzip = true`

Everything works fine with `enable_gzip = false`.

Changing router_logging did not seem to make any difference.

**Comment by szibis** [comment]
Yes, problem with ```enable_gzip = true```

**Comment by hairyhenderson** [comment]
Just FYI - I experienced the same thing. I'll try downgrading to 4.2.0.

**Comment by snezhkov** [comment]
same bug for me, oracle linux 6.9, grafana-4.3.0-beta1
`enable_gzip = false` resolve the problem

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/7c50563f0f7761e87d26d45b9a4e8c5d2e6ef1cf
