### ISSUE TITLE
Template support in -Mixed- datasource panel queries

### ISSUE THREAD

**Issue by bcg365** [grafana/grafana#8381]
Related to issue #4906.

Request that template definitions built of values from datasources allow values retrieved from all datasources included in a dashboard with -mixed- datasource panels.

Use case:  Have 4 general locations where it is not practical to push metrics to a single datasource (Graphite in this case).  Each location has the same Graphite data structure, different names in the tree but same leaf node and branch design.  I use dashboards and queries with -mixed- datasources to populate similar data from all 4 regions for high level summary dashboards.

I'd like to add templates to allow which regions or which elements from a region to include in the high-level dashboards.  Users would like the control that a single datasource panel with templates provide.  Custom value templates can do the job but require significant manual maintenance due to dynamic nature of the value list.  Datasource based template would work if I could select the template value elements from the multiple data sources that appear on the panels/dashboard.

Limitation of such a feature would be that the user is responsible to confirm that the datasource types are the same (making the template value list lookup convenient) and that the datasource structure is similarly equivalent between those datasources queried.

Example:
Datasource tree "application.location.server.cpu"
"application" in all sources has "web", "db", "app".
Datasource for New York state has locations "Albany", "Buffalo", "New York"
Datasource for California state has locations "Los Angeles", "San Francisco".

Would like to build a template variable for "$location" having all 5 locations available on a dashboard where a "mixed" panel pulls from both datasources.  Such would allow display of "Buffalo" versus "San Francisco" for instance.

I have built a mechanism to build a "fake" datasource based on periodic extracts from the primaries, server that small datasource as the default for templates only, and then use mixed datasource query definitions for every panel.  While functional, the mechanism is cumbersome and non-intuitive for users creating their own dashboards.

Thank you for your consideration.

**Comment by torkelo** [comment]
I don't understand your request. I understand that you have multiple Graphite servers. 

You can create a `Datasource` variable that you can use in other variables query definitions. But don't think that helps you, or well, not sure what would as I fail to understand what you want Grafana to do :)

**Comment by bcg365** [comment]
It's harder to say in words, so a couple of picture.  You're correct in that the Datasource template variable is helpful it doesn't do what I want in this case.

Here is an example panel definition:
![panel](https://cloud.githubusercontent.com/assets/28716173/26111032/98291ba0-3a19-11e7-844f-a5cb80244d99.PNG)

It's a panel with -- Mixed -- data source type.  The Graphite data sources have the same structure, but as the tree builds out obviously different data.

What I'd like, if possible, is a query template that can pull selectable values from the same data tree element across multiple data sources, in this case for instance the 1st wildcard element of the query where the values are unique to each data source.  The current query style templates are restricted to a single data source.  So if I create a basic query template today (4.2), I can only pull selectable values from the a single specified datasource:
![template](https://cloud.githubusercontent.com/assets/28716173/26111234/357aea14-3a1a-11e7-9d5d-ff2fe72ce3da.PNG)
which do not cover the range of wildcard values I'm able to display based on the panel data queries.

The most direct way of describing the feature, I guess, is that I'd like the data source selection in the Query Template definition to be multi-value selectable.

I understood by this request that the result is to put additional data aggregation functionality into Grafana.  Such functionality is more often than not better handled in the data source layers of the stack rather than the front end.  Unfortunately I have edge cases where doing so is neither easy nor practical which is why I make this feature request.

I hope this helps explain it more fully and thank you for consideration.

**Comment by torkelo** [comment]
querying multiple data sources in a template variable will not be supported so closing this.

**Comment by aronica** [comment]
So awesome feature it could be, sad to hear it would not be supported.
