### ISSUE TITLE
UX: Alert history list

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8383]
Would like some help redesigning the alert state history list 

Current look alert state history tab:
![image](https://cloud.githubusercontent.com/assets/10999/26096438/8112f67c-3a21-11e7-877e-9dd1ecc48273.png)

Current look alert-list panel:
![image](https://cloud.githubusercontent.com/assets/10999/26096501/b0848038-3a21-11e7-9ca4-07c5ba04e53c.png)

Want to solve two problems. First try to align both these lists so they use same component and look more similar. There is one big difference in that the alert-list panel items needs to contain the Alert Rule name as it will contain a mixed list of state changes for different alert rules while the alert state history tab is for one alert rule and hence does not contain the alert rule name. Not sure if this is a big enough difference to warrant very different design (or code component). I hope we can align the two even with this difference. 

Would like to add more info to this list and make it more useful. 

WIP work on new design:
![image](https://cloud.githubusercontent.com/assets/10999/26096682/48b457fc-3a22-11e7-8231-74207b5930d6.png)

So we have more info to show (Image link, reason, execution error) and would like to make it a little bit more structured.  Also a link to move time range to alert (maybe an icon after time stamp or make time stamp a link). 

Feel a bit stuck getting this design to look good and work in both context (alert list panel with Alert rule title included somewhere, and in state history tab). And would like some help. 

Info we have to show for each item:

- Alert rule name (only show in alert-list panel state history mode)
- Alert history item state 
- Alert history item timestamp
- Alert history item reason (NoData, Conditions true, Error, Conditions false)
- Alert history item metrics (values that triggered conditions true)
- Alert history item error message (if reason error)
- Alert history item image link (not always available) 

Also just throwing this idea out to use background colors instead to add color & make it stand out more. Not sure it's a good idea, just could be worth testing :) 

![background](https://cloud.githubusercontent.com/assets/10999/26096826/c5de2a3c-3a22-11e7-94a0-000297205d25.png)

**Comment by torkelo** [comment]
Would be great with some short help on this, @mattttt or @bulletfactory ,  just do a mockup, I can do the markup & implementation, want to refactor this into a reusable component and decouple this alert list item from the standard card markup/css that it currently uses.

**Comment by Gobiviswa** [comment]
HI Team,

I have created a Alert List panel for a Dashboard, But how to create Alert list for specific panels rather for whole Dashboard? Any options available? Thanks.

**Comment by marefr** [comment]
@Gobiviswa there's no support for filtering based on specific panels from dashboard. The only option when looking at current state is to filter by alert name.

**Comment by Gobiviswa** [comment]
![grafana-alert-list-options](https://user-images.githubusercontent.com/20736363/48190706-60ce3c80-e369-11e8-85f2-7ade7ef31c11.png)

Hi @marefr ,
Thanks for the reply. I am able to filter specific to the current dashboard, But how to filter by filter-name ?

**Comment by marefr** [comment]
@Gobiviswa there's new functionality in recent Grafana versions. However, `Recent state changes` as you've selected in screenshot haven't got any new filters, only `Current state`. Grafana v5.2 included fix for #11500 and looks like this:

![image](https://user-images.githubusercontent.com/1668778/48191423-5601b080-e345-11e8-8166-42a4a0dc79e6.png)

**Comment by Gobiviswa** [comment]
@marefr Currently I am with 4.6.2 release and running at least 20 dashboards. Can I update to current version, Hope it willn't affect the existing dashboards?

**Comment by marefr** [comment]
Yes you can. It always recommend to backup the database before upgrading in case of any unexpected things happening. Read upgrade notice for details http://docs.grafana.org/installation/upgrading/#upgrading-to-v5-0.
