### ISSUE TITLE
Data source: Changing Loki server URL does not change TLS serverName

### ISSUE THREAD

**Issue by remram44** [grafana/grafana#83844]
### What happened?

I created a data source with URL `https://loki:3100`, enabled TLS validation with a custom CA certificate. It worked.

Later, I change the URL to `https://loki2:3100`. However every panel fails with a TLS error:

> `Get "https://loki2:3100/loki/api/v1/query_range?direction=backward&end=1709566583228000000&limit=1000&query=%7B%7D&start=1709562983228000000&step=2000ms": tls: failed to verify certificate: x509: certificate is valid for loki2, loki2.logging.svc, not loki`

Looking into the Grafana database, I can see that `url` correctly changed to `https://loki2:3100`, however `json_data` contains `"serverName":"loki"`. It has not been updated, expected the new location to use the old server name, and validation fails every time.

### What did you expect to happen?

Updating the URL of a Loki data source is possible.

### Did this work before?

I haven't tried another Grafana version. It worked before I updated the data source obviously.

### How do we reproduce it?

1. Create a Loki data source
2. Update the URL

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.3

### Grafana platform?

Docker

### Datasource(s)?

Loki

**Comment by svennergr** [comment]
If you change the URL of your data source, you also need to update the CA certificate along because the domain name is likely part of your certifiate.
