### ISSUE TITLE
Failed to find LDAP server

### ISSUE THREAD

**Issue by miketice22** [grafana/grafana#83864]
### What happened?

I've encountered this issue in grafana 10.2.4 and 10.3.3. I configured `grafana.ini` with a `[auth.ldap]` section enabling LDAP authentication, however grafana cannot find the ldap server I have configured in `ldap.toml`
[grafana.ini.txt](https://github.com/grafana/grafana/files/14486324/grafana.ini.txt)
[ldap.toml.txt](https://github.com/grafana/grafana/files/14486325/ldap.toml.txt)

Also, when trying out a username under the "Test user mapping" section, it fails and the following error is in the logs:
```
logger=context userId=1 orgId=1 uname=admin t=2024-03-04T14:00:23.739632441-05:00 level=error msg="Request Completed" method=GET path=/api/admin/ldap/status status=500 remote_addr=10.135.0.20 time_ms=0 duration=450.702µs size=44 referer=https://aplhpc-01-mon000.jhuapl.edu:3000/admin/authentication/ldap handler=/api/admin/ldap/status
logger=context userId=1 orgId=1 uname=admin t=2024-03-04T14:00:36.719127415-05:00 level=error msg="Request error" error="runtime error: invalid memory address or nil pointer dereference" stack="runtime/panic.go:261 (0x501d1f7)\nruntime/signal_unix.go:861 (0x501d1c5)\ngithub.com/grafana/grafana/pkg/services/ldap/api/service.go:263 (0x8f94b3b)\ngithub.com/grafana/grafana/pkg/api/routing/routing.go:17 (0x8f937fb)\ngithub.com/grafana/grafana/pkg/api/response/web_hack.go:40 (0x613a98f)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:131 (0x612d40e)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/services/contexthandler/contexthandler.go:145 (0x87b787b)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/render.go:44 (0x612df9d)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/macaron.go:137 (0x612d4b2)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/csrf/csrf.go:66 (0x7e0461a)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/recovery.go:179 (0x8790c75)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/loggermw/logger.go:72 (0x7e05636)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/request_metrics.go:83 (0x6711ef5)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/request_tracing.go:88 (0x87918d5)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/middleware/requestmeta/request_metadata.go:66 (0x87b6915)\nnet/http/server.go:2136 (0x5375c88)\ngithub.com/grafana/grafana/pkg/web/context.go:52 (0x612bef6)\ngithub.com/grafana/grafana/pkg/web/router.go:155 (0x612f66d)\ngithub.com/grafana/grafana/pkg/web/router.go:221 (0x61301b4)\ngithub.com/grafana/grafana/pkg/web/macaron.go:163 (0x612d8dc)\nnet/http/server.go:2938 (0x537896d)\nnet/http/server.go:2009 (0x5374853)\nruntime/asm_amd64.s:1650 (0x503c6e0)\n"
logger=context userId=1 orgId=1 uname=admin t=2024-03-04T14:00:36.719255674-05:00 level=error msg="Request Completed" method=GET path=/api/admin/ldap/ticemp1 status=500 remote_addr=10.135.0.20 time_ms=1 duration=1.190136ms size=107 referer=https://aplhpc-01-mon000.jhuapl.edu:3000/admin/authentication/ldap handler=/api/admin/ldap/:username
```

### What did you expect to happen?

LDAP server should be reachable by/from grafana

### Did this work before?

I have another grafana instance at version 9.3 that works with a similar configuration.

### How do we reproduce it?

1. install grafana 10.2.4 or 10.3.3 with the attached configs
2. restart grafana-server
3. Administration -> Authentication -> LDAP should show "Failed to find the LDAP server"

### Environment (with versions)?

Grafana: 10.2.4 / 10.3.3
OS: RHEL 9
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by misilot** [comment]
I am also running into the same issue with 10.3.3 from `grafana/grafana-oss`

**Comment by jm-esquivel** [comment]
I have encountered this error and I was able to resolve it by commenting "[[servers.group_mappings]]". LDAP config produce error when there's an empty config of server group_mappings.
![image](https://github.com/grafana/grafana/assets/104746696/6a38cf36-6b54-4439-a0e0-8306d9e03038)
<img width="365" alt="image" src="https://github.com/grafana/grafana/assets/104746696/6d990064-40ad-42b2-96cd-c8279c0ffad2">

**Comment by miketice22** [comment]
> I have encountered this error and I was able to resolve it by commenting "[[servers.group_mappings]]". LDAP config (ldap-toml) produces error when there's an empty config of servers.group_mappings. ![image](https://private-user-images.githubusercontent.com/104746696/312298737-6a38cf36-6b54-4439-a0e0-8306d9e03038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzA5ODIsIm5iZiI6MTcxMDMzMDY4MiwicGF0aCI6Ii8xMDQ3NDY2OTYvMzEyMjk4NzM3LTZhMzhjZjM2LTZiNTQtNDQzOS1hMGUwLTgzMDZkOWUwMzAzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMTUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTI3M2ZkMGJkZGMwYjk2ZWM2OTE5Y2IyNzhkODE3YTExZjkyZmE5Mzc3YTllZjg1ODg1MTMzMjg0Y2E5MmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Et6qHK_pMZ8L-6_Ol5tIgJtGYiA9rAfYk7mhSV59iSQ) <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/104746696/312298809-6d990064-40ad-42b2-96cd-c8279c0ffad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzA5ODIsIm5iZiI6MTcxMDMzMDY4MiwicGF0aCI6Ii8xMDQ3NDY2OTYvMzEyMjk4ODA5LTZkOTkwMDY0LTQwYWQtNDJiMi05NmNkLWM4Mjc5YzBmZmFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMTUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjU4ZGYyNmRmZTA0YTFjNjUzN2RiN2E4NDY3MzgxMDk5OWJmZGEzMTMyMWMwMzM5NzcxM2EzZGViYmZiODNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BbAjvUpq1q4D_KKHfvQjIErjcx5EvLw_2e4A90xKTUw">

Unfortunately this didn't work for me. Also my group mappings was not empty.

**Comment by kalleep** [comment]
Hey when you start grafana there should be an error log happening if something is wrong with your config. That log should have a message `Failed to get LDAP config` and log error that occurred. Can you please check for that?

**Comment by miketice22** [comment]
> Hey when you start grafana there should be an error log happening if something is wrong with your config. That log should have a message `Failed to get LDAP config` and log error that occurred. Can you please check for that?

Thank you. I did not notice this line in the log. I searched for this specifically and found the error(s) in my ldap config.

I had to triple quote the ldap bind password, and double escape an ldap group that begins with a '+'

**Comment by Realboyblue** [comment]
I was getting "Failed to find LDAP server" in the Frontend GUI LDAP testing page and LDAP was not functioning to log into the server frontend. However manual tests from the terminal were working just fine.

I was able to resolve this issue by carefully reading the Official documentation, specifically this line "Commenting out a group mapping requires also commenting out the header of said group or it will fail validation as an empty mapping.". Look through your ldap.toml file and check for any variable groupers with no values defined that are not commented out and restart the Grafana service. The moment I changed this I was able to make LDAP connections again. 

Example Problem Config:
[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
# group_dn = "*"
# org_role = "Viewer"

Example Fixed Config:
# [[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
# group_dn = "*"
# org_role = "Viewer"


https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/
