### ISSUE TITLE
[Bug] alert rule out of sync with panel query when using references

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#8387]
Grafana Version: 4.2.0
Datasource: graphite

Changes to the queries are not propagating to the alert rule.  When testing the Rule, the logs showed the data the alert rule was fetching did not match the current query being used.

steps to replicate:
create query #A:  constantLine(10)
create query #B: constantLine(5)
create query #C: divideSeries(#A,#B)

create an alert rule, avg() of query(C, 5m, now) is above 1
Save dashboard
test rule.  Logs will show the alert fires with the value evaluated to 2.

modify query #A to be: constantLine(5)
modify query #b  to be: constantLine(10)
save dashboard.
test rule.  Logs will show that the alert is still firing with a value evaluated to 2, even though the result should be 0.5

even after deleting and recreating the alert rule, the problem still persists.

**Comment by torkelo** [comment]
I think this was fixed in https://github.com/grafana/grafana/pull/8143

**Comment by torkelo** [comment]
verified that https://github.com/grafana/grafana/pull/8143 does indeed fix this

**Comment by levin81** [comment]
Running Grafana v4.3.0-beta1 (commit: 3a89272) and still suffering from this problem. Using diffSeries with references to other metrics in the graph. Clicking "Test Rule" still returns the result for the old diffSeries metric that was duplicated, instead of the new one.

**Comment by torkelo** [comment]
You need to update one query, or remove readd it for the fix to take effect

**Comment by levin81** [comment]
Thanks, that worked!
