### ISSUE TITLE
User with no role required to have alert rules reader permissions to open a dashboard

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#83872]
### What happened?

When giving a user dashboards reader permission, dashboard shows error that alert rules reader is also required. Even when dashboard doesn't have any alert rules.
![image](https://github.com/grafana/grafana/assets/1131253/e846ab60-ba5c-476c-99a5-0c94b15b54d2)

There was a similar problem with annotations permissions, it was fixed with the feature flag **annotationPermissionUpdate**.
But the feature flag doesn't cover alert rules.

See https://github.com/grafana/grafana/pull/78899

### What did you expect to happen?

Assigning dashboards reader permission should be enough.

### Did this work before?

Everything seems to work fine in 10.3.3 but main branch has the problem with alert rules permission.

### How do we reproduce it?

1. Have a user with no predefined role in the org
2. Give this user dashboard reader permission to a particular dashboard
3. When user tries to open the dashboard, user see the Alert Rules reader error message.

### Is the bug inside a dashboard panel?

No, dashboard permissions logic.

### Environment (with versions)?

Grafana: main
OS: N/A
Browse: N/A

### Grafana platform?

None

**Comment by timlevett** [comment]
@konrad147 is this an issue in 10.4.x? If so, could you backport it? If not, please let us know.

**Comment by konrad147** [comment]
Yes, this is an issue in 10.4.x 
I'll backport
