### ISSUE TITLE
Alerting: Emergency! During the upgrade from Grafana 10.3.3 to version 11.0.0-pre, there is an anomaly in the Elasticsearch query result series("Series 1, Series 2, ... Series N" ).

### ISSUE THREAD

**Issue by GitHamburg** [grafana/grafana#83882]
### What happened?

After upgrading Grafana to Grafana v11.0.0-pre, when selecting the Elasticsearch data source in the alert rules and using the "Group By Terms" option, only "Series 1, Series 2, ... Series N" are displayed.

![image](https://github.com/grafana/grafana/assets/16780183/89bc0262-8e42-4ce0-b326-1013ed237a2e)

![image](https://github.com/grafana/grafana/assets/16780183/1a0eceb5-a506-4a33-add7-64a3b8bf3e8a)

Same issue: [Reduce expression: raw data to series when datasource is elasticsearch on latest Grafana 10.3.3](https://github.com/grafana/grafana/issues/83528)

### What did you expect to happen?

The Elasticsearch query results display metric, label, and other information instead of "Series 1, Series 2, ... Series N".

### Did this work before?

The current version of my production environment is Grafana v10.3.0-pre (ee4bbfe2b2), and it is currently functioning properly.

![image](https://github.com/grafana/grafana/assets/16780183/17b5dfeb-2c20-4605-b576-399e0aa1d148)

### How do we reproduce it?

1.Add Elasticsearch Datasource
2.In the alert rule configuration interface, write a query statement, for example: level:ERROR
3.Group By Terms with any field
4.Execute Elasticsearch query preview

### Environment (with versions)?

Grafana:11.0.0-pre
OS:13.6.1 (22G313)
Browser:Google Chrome 122.0.6261.94

### Grafana platform?

None

### Datasource(s)?

Elasticsearch 7.16.3

**Comment by ivanahuckova** [comment]
Hello, thank you for reporting the issue. In [10.3.5 patch release](https://github.com/grafana/grafana/releases/tag/v10.3.5) and [10.4.1 patch release](https://github.com/grafana/grafana/releases/tag/v10.4.1) we fixed the issue. I recommend using one of these versions. Sorry for inconvenience. 

I am closing the issue as resolved, but feel free to reopen if fix didn't help.
