### ISSUE TITLE
GitHub 404 error 

### ISSUE THREAD

**Issue by olalonde** [grafana/grafana#8388]
The Github button redirects me to https://github.com/login/oauth/authorize?access_type=online&client_id=MYCLIENTID&redirect_uri=http%3A%2F%2Fmonitoring.mydomain.com%2Flogin%2Fgithub&response_type=code&scope=user%3Aemail%2Cread%3Aorg&state=somestatevariable%3D which is a 404. Any idea how to troubleshoot this?

**Comment by torkelo** [comment]
It's the correct url. Maybe your client id or redirect uri is wrong?

Github OAuth seems to work here:

**Comment by torkelo** [comment]
http://play.grafana.org/login

**Comment by olalonde** [comment]
Oh thanks, turns out I was mixing up client id / secret.

**Comment by olalonde** [comment]
Btw, when Github returns a "redirect_uri_mismatch" error, Grafana silently ignores the error and just redirects to the login page.
