### ISSUE TITLE
Height of Collapsed Rows

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8390]
![image](https://cloud.githubusercontent.com/assets/2886187/26109353/558762ee-3a1d-11e7-9b65-e60cae271f84.png)

With v4.0, we've included default spacing between collapsed rows, which has increased the height. This is an issue to think about ways to tighten up that spacing when you have a block of rows together.

**Comment by torkelo** [comment]
Think the spacing feels appropriate as it's using the same panel margins as other items on the dashboard. So the row margin feels much more consistent and looks good to me. 

![image](https://cloud.githubusercontent.com/assets/10999/26110080/876f9f40-3a51-11e7-8a7c-37fc2ab18442.png)
