### ISSUE TITLE
Exclude Row Status (open/closed) from Change Tracker

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8391]
Similar to time range changes, rows opens and closes should be excluded from the change tracker. 

Also just as the timepicker, when the dashboard is saved, it will save the current state of the rows (open & closed), but a user should not be prompted that the dashboard has changed if they've only opened and closed rows.

**Comment by torkelo** [comment]
row collapse state is already ignored, added to ignore list 2 years ago,  in v2.0 :)
