### ISSUE TITLE
Prometheus data source: label values requests aren't cancelled

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/grafana#83926]
### What happened?

This is in the context of setting up a dashboard variable with Label values from a Prometheus datasource:

If the user changes the prompt for the filtered values, the requests to the grafana backend aren’t cancelled. If the requests are expensive and come at a high frequency they can overwhelm the prometheus backend.

https://github.com/grafana/grafana/assets/21020035/d32cd599-5181-4338-a3d2-9fb44c9ba537

### What did you expect to happen?

Previous requests (especially the ones after 0:43 in the recording) should be cancelled before they return since their response will not be visualized anyways.

### Did this work before?

when the form included a basic text field without autocompletion, this wasn't a problem

### How do we reproduce it?

See recording

### Environment (with versions)?

Grafana: Grafana v11.0.0-67812 (3f2820a552)
OS: MacOS
Browser: Google Chrome 122.0.6261.94 (Official Build) (arm64)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by NWRichmond** [comment]
Thanks for this issue, @dimitarvdimitrov! I just opened #86403 to address this.
