### ISSUE TITLE
Elastic Datasource: query groups are no longer converted to labels

### ISSUE THREAD

**Issue by MarcoJ-CID** [grafana/grafana#83968]
### What happened?

After the last Grafana update, Elasticsearch query groups are no longer converted to labels.

The absence of “*service” label causes Slack alerts to come ungrouped and without identification which services have issues. Also this partially breaks templated Slack alert messages.
![image](https://github.com/grafana/grafana/assets/6771839/30aa2497-cec2-4b70-87a1-caa89a9af515)

### What did you expect to happen?

That the labels shown up correctly

### Did this work before?

Yes it was working before. See attached image

### How do we reproduce it?

We could reproduce it with following steps  
1. new alert
2. select elastic as datasource
3. add query
4. add reduce and threshold
5. click on preview

### Environment (with versions)?

Grafana: 10.3.3
OS: Windows Server 2022 
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Elastic (should be the native one)

**Comment by MarcoJ-CID** [comment]
We tested today the update 10.3.4 and 10.4.0 just to be safe but these release didn't fixed the issue. 
With 10.4.0 we get now also an error when the alert rule is loaded.
![image](https://github.com/grafana/grafana/assets/6771839/98d5c53d-0da4-43e2-b196-bc402c93f5c0)

**Comment by slhck** [comment]
Yes, the original PR causing this is this one: https://github.com/grafana/grafana/pull/81708

**Comment by ivanahuckova** [comment]
Yes, https://github.com/grafana/grafana/pull/81708 unfortunately broke alerting. We'll have a look and provide a fix. In the meantime, I recommend to stay on v10.3.1.

**Comment by ivanahuckova** [comment]
I have created the fix https://github.com/grafana/grafana/pull/84485. In the meantime, I recommend to stay on `v10.3.1` or latest `10.2.x` until patch release.
