### ISSUE TITLE
external-image-storage defaults to non existent S3 AWS URL

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#8397]
as documented in here 
http://docs.grafana.org/installation/configuration/#external-image-storage
Bucket URL for S3. AWS region can be specified within URL or defaults to ‘us-east-1’, e.g. - http://grafana.s3.amazonaws.com/ - https://grafana.s3-ap-southeast-2.amazonaws.com/ - https://grafana.s3-cn-north-1.amazonaws.com.cn

this means when pulling the images from the default bucket will be accessed like this:
bucketname.s3-us-east-1.amazonaws.com/dWP3sw7N7WpoGyxZW5lD.png

this type of URL is not accessible anymore accordingly with AWS documentation:
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

available URLs for us-east-1 are:
bucketname.s3.amazonaws.com
bucketname.s3-external-1.amazonaws.com
bucketname.s3.dualstack.us-east-1.amazonaws.com**

so in the actual config if we do not specify any region the upload will actually work but the way grafana is trying to pull the image will not work anymore

extract from grafana 4.3.0-beta logs:
t=2017-05-17T09:01:59+0000 lvl=info msg=uploaded logger=alerting.notifier url=https://bucketname.s3-us-east-1.amazonaws.com/dWP3sw7N7WpoGyxZW5lD.png

 I suppose you should either change/update the code so that grafana will pull from a valid endpoint or do not default to any region since s3 is global and leave it like bucketname.s3.amazonaws.com the same way this is being used for upload.

thank you.

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/pull/8251
