### ISSUE TITLE
capitalization issue in InfluxQL 

### ISSUE THREAD

**Issue by Adrian181200** [grafana/grafana#83982]
### What happened?

While I was creating dashboard from the influx 3.0 data its issue that cannot comprehed with capital letters in 'Select Table'. 
I want to get data from "device_frmpayload_data_tempC_DS" and here is error code - "Status: 500. Message: flightsql: rpc error: code = InvalidArgument desc = Error while planning query: Error during planning: table 'public.iox.device_frmpayload_data_tempc_ds' not found".

### What did you expect to happen?

I am expecting to get my data from influx in the same way as i get it in the case while I am using only lowercase.

### Did this work before?

Influx db 3.0 connection work from the grafana 10.0 update so It cannot work beforeXD

### How do we reproduce it?

1. Get connection to the influx DB and choose SQL query language
2. Try to make a time series from a data which name consist capital letters
3. Enjoy

### Environment (with versions)?

Grafana: 10.3
OS: Debian
Browser: Opera

### Grafana platform?

Other

### Datasource(s)?

I've installed grafana locally on my Debian

**Comment by tonypowa** [comment]
hi @Adrian181200 

can you share the entire query please? The error seems to point to the `order by` clause. 
Please redact any sensitive info
thanks!

**Comment by itsmylife** [comment]
@Adrian181200 Thanks for sharing the bug with us. It was a known issue and fixed with this PR https://github.com/grafana/grafana/pull/83765
The fix will be in `v11.0.0`. It is already in the latest `v10.4.x` release. Therefore I am closing this issue as it was resolved. 
Please let us know if you will experience any other inconsistencies.
