### ISSUE TITLE
[Feature request] Change graph background when all metrics null

### ISSUE THREAD

**Issue by mageo** [grafana/grafana#8398]
Hello,

We were able, using rrdtool, to generate graph where the background color of the graph changes when there's no data to graph:

![rrd_gray](https://cloud.githubusercontent.com/assets/12015577/26151942/36b66e44-3b05-11e7-8407-16f7dea90a9e.png)

This is implemented using a special CDEF as explained there: http://rpm.pbone.net/index.php3/stat/45/idpl/34615278/numer/1/nazwa/cdeftutorial#lbAY

I was able to mimik this behaviour using the transformNull() function but the result is not perfect and the metric is quite complicated.

It would be great, as for thresholds, to be able to modify the background of the graph according to certain conditions, the one needed here would be "If all metrics are null".

Do you think this would be possible ?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
