### ISSUE TITLE
Annotations has not been working correctly since 10.2.3.

### ISSUE THREAD

**Issue by larshove** [grafana/grafana#84003]
### What happened?

Enabling and disabling annotations will make them half-appear (arrow will show in bottom, and line will not show, or line will show and arrow will not show).
When enabling annotations, the line will not show.
When disabling annotations, the line will show.

See attached video.

https://github.com/grafana/grafana/assets/15522085/c9278eaf-ac29-4747-9e76-8c66da2d26aa

### What did you expect to happen?

Enabling annotations should show the line and arrow.
Disabling annotations should hide the line and arrow.

### Did this work before?

It worked fine in 10.2.3 and older.

### How do we reproduce it?

1. Create an annotation.
2. Enable it, and disable it to see the error.

### Is the bug inside a dashboard panel?

The bug is present on dashboard graphs.

### Environment (with versions)?

Grafana: 10.3.3, 10.4.0
OS: Windows
Browser: Chrome, Edge

### Grafana platform?

A downloaded binary

**Comment by gelicia** [comment]
One easy replication to see: https://play.grafana.org/d/cdfr0pbkjt1j4f/annotation-testing-2?orgId=1

Toggling the annotation off and on can show how the annotation doesnt always appear correctly.

**Comment by leeoniya** [comment]
should be fixed with the `newVizTooltips` flag. please try enabling this on a nightly build: https://grafana.com/grafana/download/nightly?edition=oss

**Comment by larshove** [comment]
Confirmed working with the newVizTooltips enabled.
