### ISSUE TITLE
[Feature request] Option to Disable Getting Started Panel

### ISSUE THREAD

**Issue by roobert** [grafana/grafana#8402]
Hi,

We're deploying Grafana as part of an application stack. Part of our deployment procedure is to load dashboards into Grafana. Our deployments are ephemeral (changes are lost when the stack is rebuilt) but we configure our instances with no-auth and with the default role as Admin so that our users can adjust/tune graphs before exporting them and rolling them back into config-management.

The "Getting Started" panel adds confusion for our users since it implies some action is required, when it isn't. Would it be possible to make the panel configurable through the config file?

Thank you kindly,

Grafana version: v4.3.0-beta1 (commit: 3a89272)
Data source: prometheus
OS: Linux

**Comment by rabbbit** [comment]
+1, exactly same situation.

**Comment by vmdude** [comment]
Before it's integrated, you could achieve that with sqlite3 client:

`sqlite3 /var/lib/grafana/grafana.db "update user set help_flags1 = 0 where login = 'admin';"`

**Comment by roobert** [comment]
This work around doesn't work if you are using grafana as an anonymous user, so unfortunately this doesn't help in my situation since it looks like grafana reverts to the default built-in value of `help_flags1 = 1`.

**Comment by siggy** [comment]
Bumping this feature request. We distribute https://github.com/linkerd/linkerd-viz with Grafana in an anonymous / admin configuration for ease of use. We are stuck on Grafana 3.1.1 because of this issue.

**Comment by torkelo** [comment]
can't you change the home dashboard to a custom home dashboard?

**Comment by roobert** [comment]
@torkelo: Would that work? Is it also possible to remove the Home dashboard? This seems like a bit of an odd work around and feels like the Getting Started panel ought to be configurable.. I can try and look into patching this at some point, if it's likely to get accepted from a feature perspective?

**Comment by torkelo** [comment]
You can change home dashboard on the organisation level. Why is this odd?

**Comment by roobert** [comment]
Seems odd to me because the configuration option already exists for normal users so people must see the value in hiding the panel and since an anonymous user is just another type of user, why not allow it to hide the panel also? Functionally, apart from the panel, there is nothing wrong with the Home dashboard. It'd also be nice for users to have a consistent experience between anonymous and non-anonymous deployments.

I was hoping this would get picked up as part of the projects drive to make grafana more deployment/ops friendly.

Hope this makes sense and thank you for all your hard work on Grafana.

**Comment by torkelo** [comment]
Well having anonymous admins is not something we want to incurage. 

Why would home dashboard be different for anonymous users?? If you create a custom version of the home dashboard (you can do save as on the default one) it will used by both anonymous and logged in users

**Comment by roobert** [comment]
The reason we have anonymous admins is because we want our users to be able to adjust graphs and then roll them back into our config management system. Is there some other way we should be doing this?

I don't want dashboards to be different for anonymous users..?

I think I understand what you're proposing, but my question remains: if there is a switch already, why not make the switch work in the anonymous user context? Otherwise we're just looking at a load more stuff to manage / update whenever the Grafana project updates the default dashboard. If my options are to write a custom dashboard and do everything necessary to manage it, or write a useful patch for Grafana, I'd rather do the latter, if it'll be accepted as a feature?

**Comment by siggy** [comment]
@torkelo To answer your earlier question, we do change the home dashboard:
https://github.com/linkerd/linkerd-viz/blob/4d701b2dbf825e9f2549c37ce5464e922262ca07/Dockerfile#L41
...but the "Getting Started" panel still appears. 

We tried modifying the sqlite db during Docker build:
https://github.com/linkerd/linkerd-viz/blob/4d701b2dbf825e9f2549c37ce5464e922262ca07/Dockerfile#L14
...but as noted in an [earlier comment](https://github.com/grafana/grafana/issues/8402#issuecomment-314729626), this does not make the "Getting Started" panel go away.

I realize there's some subtlety here, as the existing help flag check requires a user with the flag, not anonymous, I'd defer to you on the best approach around this. Linking here for my own memory:
https://github.com/grafana/grafana/blob/46412c8475e559849382121874c3c5031b67cb80/pkg/api/dashboard.go#L223

I definitely understand not wanting to encourage anonymous admin usage. In our use case, we redistribute Grafana as part of a monitoring kit to other developers, so we're reluctant to make assumptions about their administrative/authentication models.

**Comment by torkelo** [comment]
That is not what I mean by changing home dashboard, you change home dashboard on  the organisation preferences page (or using the preferences api).

Do you need to give the anonymous users admin role? Do they need to add new datasources? Editor role can also create dashboards.

**Comment by siggy** [comment]
@torkelo `GF_AUTH_ANONYMOUS_ORG_ROLE=Editor` works for us, thanks!

**Comment by mattpr** [comment]
We also fall in the provisioning boat where we want to deploy a pre-configured grafana with a set of default dashboards, data sources, etc.  Yes users can build their own and that is part of the point of grafana...so we have to accommodate backingup/restoring dashboards as part of any rebuilt install.  As a side note, looking forward to user/group provisioning someday. 

Since home dashboard isn't part of config file based provisioning at this point, we overwrite the default dashboard `<grafana-install-base>/public/dashboards/home.json` after unpacking the tarball.

The "getting started" widget seems to be injected by angular and isn't part of the template.  
Having to make a sqlite or API call as part of the provisioning process feels clunky.
So first users of new grafana deployment/redeployment have to dismiss this.
