### ISSUE TITLE
[BUG] Elasticsearch datasource index pattern fails to fetch data with Arabic browser language

### ISSUE THREAD

**Issue by achennuru** [grafana/grafana#8403]
If my system language is set to Arabic all the date formats are in Arabic but when querying elasticsearch index pattern it sends the request in Arabic but the index exists only in english.

logstash-2017-05-17 index is in elasticsearch but the browser sends the request for 
logstash-٢.١٧-.‎٥-١٧‎
which does not exist.

**Comment by aocenas** [comment]
Seems like the issue could be localized formatting when creating the pattern which would be a bug.
