### ISSUE TITLE
[Feature request] Singlestat null value color

### ISSUE THREAD

**Issue by joelraburton** [grafana/grafana#8404]
Hello, I'm new to grafana (running 4.1.1) and I am trying to figure out how to get the singlestat panel to display a specific colour / color when there is null data. (I have posted this to the community site with no joy so now posting here)

The panel displays an averaged time for the last 15 minutes of data but the data is intermittent so I might have 10 updates in the space of five minutes (which is then averaged) or I might not have any updates for 30 minutes (at which point the average is null). (Data feed is journey time for a vehicle to travelling between two fixed cameras)

What I want is when an average can be calculated is the panel to be green and showing the averaged value and when there is no data to average I want the panel to be red. While I can just set the value mappings of null to either blank / #N/A / **NO DATA** I have quite a few panels so I want an easy colour / color coded system that allows for quick visual inspection.

I cannot use changed() as I want to see the averaged values in the panel and I cannot use transformNull() either as this skews the average. I could potentially use transformNull() if I could create a query that has only a single averaged value but I have not been able to figure out how to get this to work.

**Comment by Samuel1989** [comment]
@joelraburton,

Could you set the value mapping of null to 0 and then set the colour threshold to display red on 0? I just tried this on V4.2.0 and it seemed to work.

Sam

**Comment by joelraburton** [comment]
I have tried setting the value to zero in grafana 4.1.1 but it appears to treat the mapping as a string rather than a value. I also have the issue that if null becomes a value e.g. 0 it may change the average which would cause the calculated value to be incorrect.

**Comment by vvk** [comment]
It's not the way to consider `null` as `zero`. It must have separate color mapping.

**Comment by rgosdal** [comment]
Considering _null_ as zero doesn't solve the problem. I would like to display RED both on _null_ and above a configured threshold.

**Comment by vvk** [comment]
The issue should be reopened since #9438 has been reverted right after it has been merged.

**Comment by botzill** [comment]
Hi,

Currently I have the same issue. I map null -> 0 in value mapping but when try to use it in thresholds, like `0,1` there is no coloring for zero(which is null). I'm testing latest version: `Version 4.7.0-pre1 (commit: 799aaf7)`

Thx!

**Comment by jbrekle** [comment]
i have the same issue. We found a workaround in [a related issue](https://github.com/grafana/grafana/issues/2393#issuecomment-192522042)
add "OR vector(0)" in the query
but i would rather see this fixed in the threshold evaluation

**Comment by 3IMOH** [comment]
I just ran into this bug after upgrading to 4.6.3. I was on version 4.2 and my Null->0 mapping allowed the "0" to be colored. It no longer works after the upgrade. I am using influxdb as my datasource.

**Comment by talbz** [comment]
@jbrekle, does this trick work also with metrictank?

**Comment by stephanstapel** [comment]
+1

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.

**Comment by bjerngaard** [comment]
Workaround: Use the transformNull function. Value mapping can still be used.

**Comment by elieyal** [comment]
Have the same issue.
@bjerngaard, Can you elaborate on your workaround?

**Comment by bjerngaard** [comment]
@elieyal Use the transformNull function to transform null values into another value (I'm using Graphite). Let's say we transform null to 0. Now use 'Value mappings' to map 0 into a text string, and 'Coloring' under 'Options' to color according to your 0 value.

![screen shot 2018-11-27 at 16 15 40](https://user-images.githubusercontent.com/10154675/49091305-cd997000-f25f-11e8-98fe-45a75f81050f.png)
![screen shot 2018-11-27 at 16 16 01](https://user-images.githubusercontent.com/10154675/49091307-ce320680-f25f-11e8-96b5-f421928a175b.png)
![screen shot 2018-11-27 at 16 16 12](https://user-images.githubusercontent.com/10154675/49091308-ce320680-f25f-11e8-9a16-8181c1411fc0.png)

**Comment by elieyal** [comment]
@joelraburton I understand :-)
I'm using InfluxDB so I need another solution.
Thanks!

**Comment by rdxmb** [comment]
seems like this is fixed with Grafana 7.1.5 within the **Stat** Panel:

![Screenshot_20200918_145207](https://user-images.githubusercontent.com/30314040/93599690-d2905c00-f9be-11ea-85a2-3c0b46b631ea.png)
