### ISSUE TITLE
Dashboards: Elasticsearch legends not shown with 10.4.0

### ISSUE THREAD

**Issue by slhck** [grafana/grafana#84054]
### What happened?

I have a visualization that used to show the ratio between two sets of data. The queries are set up like this:

<img width="781" alt="image" src="https://github.com/grafana/grafana/assets/582444/b6d4dbb8-221e-4dfd-8c6e-251e1efd895f">

The visualization is a heatmap with no custom settings.

The heatmap shows some seemingly random numbers as y-axis labels:

<img width="800" alt="image" src="https://github.com/grafana/grafana/assets/582444/d6d4981b-6bea-4436-b745-9e9b9e289c81">

Note that I only want to display the last query (the calculated ratio). When I only keep the first query for debugging purposes, I get the correct labels:

<img width="788" alt="image" src="https://github.com/grafana/grafana/assets/582444/a9571dd4-b0ae-4d2f-9c19-175d36bdbfde">

### What did you expect to happen?

I am expecting the heatmap to show the actual distinct values of `study.subject.keyword` in the y axis as labels, because I only want to show the calculated ratio grouped by those values.

### Did this work before?

Yes! This used to be the case with Grafana < 10.4. It now no longer works after updating. Something broke here.

### How do we reproduce it?

See the screenshots for the queries.

### Is the bug inside a dashboard panel?

Too long for this field. See https://gist.github.com/slhck/929757d91275c85186dfd1d5614f6c99

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker/Linux
Browser: Chrome 122

### Grafana platform?

None

### Datasource(s)?

Elasticsearch 8

**Comment by slhck** [comment]
I also noticed the existing alerts are breaking:

<img width="1307" alt="SCR-20240307-nxpm" src="https://github.com/grafana/grafana/assets/582444/b1b8316e-0e09-47b5-8aab-3da2cfca06b0">

This shows proper labels and raw values:

<img width="1237" alt="image" src="https://github.com/grafana/grafana/assets/582444/99593a97-d258-402c-9f73-5635c843512d">

Yet upon creating the alert expression, the actual series have no name:

<img width="838" alt="image" src="https://github.com/grafana/grafana/assets/582444/aa889e77-7838-4f38-916b-f3d91a4f352d">

**Comment by ivanahuckova** [comment]
Thank you for reporting this issue and providing data to investigate. To quickly resolve the issue for you, you can set `enableElasticsearchBackendQuerying` feature toggle to false. I will investigate why this is happening with the feature flag on.

**Comment by slhck** [comment]
Thank you for the response. Setting the feature toggle to false does **not** solve the issue.

I have set it like this (screenshot from Grafana backend after modifying the config file, and restarting Grafana):

<img width="538" alt="SCR-20240314-icop" src="https://github.com/grafana/grafana/assets/582444/fe2450b7-dcc1-43a6-8177-80ba9023b4f9">

Yet, the panel from my issue description still looks the same.

**Comment by ivanahuckova** [comment]
I have created the fix https://github.com/grafana/grafana/pull/84485. In the meantime, I recommend to stay on `v10.2.x` until patch for 10.4 is released.

**Comment by slhck** [comment]
Thanks, I see this was merged. I suppose this will only be released some time in April?
I unfortunately cannot roll back the affected instance, but I will just wait for the release then.

**Comment by slhck** [comment]
I can confirm this is working again with 10.4.1. Thanks for the quick fix!
