### ISSUE TITLE
Single stat Panel change

### ISSUE THREAD

**Issue by MahekPavagadhi** [grafana/grafana#8406]
Hi, In single stat panel under '**Options**' I want to break down the '**Values**' into two different parts. One that displays **current** stat on the center of the panel and **Avg** stat should be displayed on the top-right corner of the panel. The data source remains same and also the '**tag**'. The metrics will be common for both.

Can you guide how should I proceed. Apart from html and css, I couldn't figure out the flow as I am new to grafana.
![18518876_1948173901875375_82572839_n](https://cloud.githubusercontent.com/assets/6774570/26169927/4c7cc4b4-3af4-11e7-9d7a-c7cbd13096ab.jpg)

**Comment by torkelo** [comment]
this would need to be a different panel. Singlestat is built to show a single and a trend line :)

**Comment by MahekPavagadhi** [comment]
Can you consider it as feature request?

**Comment by torkelo** [comment]
Not in this case I think, as we want to keep singlestat focused on showing a single stat
