### ISSUE TITLE
[Bug] Math scaling doesn't work with variable as field

### ISSUE THREAD

**Issue by nedds9** [grafana/grafana#8407]
Using grafana v4.2.0:

I'm using a template variable as the field in a query, like:

SELECT mean(/^$field$/) ...

When I try to apply a scaling factor to this, such as:

SELECT mean(/^$field$/) * 1000000

My graph tells me there are no data points. However, if I replace the field variable with my selected value for it ("avg" in this case), the scaling works properly.

If this is intended behavior, is there a way to apply scaling in the case of a variable as my field?

**Comment by torkelo** [comment]
You will have to open a question with the  InfluxDB project, not sure how regex field name works with math expression
