### ISSUE TITLE
dashboard list for remote instances

### ISSUE THREAD

**Issue by cbnorman** [grafana/grafana#8410]
hi 

we have multiple versions of grafana across our firm and its starting to become a bit difficult to know what dashboard is on what instance. is there a way to create a dashboard list that can display dashboards on another instance. my plan would be to have this same dashboard list on all instances so we could jump between them all?

thanks

chris

**Comment by torkelo** [comment]
you could develop a custom panel that lists dashboards from multiple instances. 

But Grafana Dashboard search will not do this. It can suppport many thousands of dashboards already.
