### ISSUE TITLE
Dashboards: Share button should not be so prominent in toolbar

### ISSUE THREAD

**Issue by drewhammond** [grafana/grafana#84110]
### What happened?

The new blue "Share" button added in https://github.com/grafana/grafana/issues/77298 / https://github.com/grafana/grafana/issues/72741 is distracting. The prominent placement and color suggests it is the primary action in the toolbar, which I'd imagine is not aligned with real-world user expectations in nearly all cases.

For non-public use, sharing a dashboard or panel has always been as simple as copy/pasting the URL. If I wanted to do something fancy like preserving the data in a snapshot, I was happy to spend a couple extra seconds to find and open the sharing modal.

I realize this may conflict with your goal to increase adoption, but the addition of the button feels like a step in the wrong direction and negatively affects user experience.

Based on the screenshots in the PR and design spec (and also perhaps the only real use case), it seems like maybe this was intended to be used only on public dashboards, so I am filing this as a bug.

### What did you expect to happen?

The share button would not be displayed so prominently.

### Did this work before?

In previous versions it was a transparent icon that did not distract from the primary purpose of Grafana.

### How do we reproduce it?

1. Upgrade Grafana to 10.4.0
2. View any dashboard
3. Get distracted by the blue share button

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by ebabeshko** [comment]
+1. Before 10.4.0 the tiny 'Share' icon was as its place. Starting from 10.4.0 this bright blue button is definetly distracting and looks like alien

**Comment by danutchereches** [comment]
I feel the same way.

**Comment by natellium** [comment]
👋 Thank you for your feedback. This was done intentionally as  part of a bigger project to increase the adoption of sharing features but also to improve the dashboard toolbar. In v11.0.0 we'll be releasing a new dashboards toolbar and in that new design the sharing button won't be a primary action anymore. I attach a screenshot with the new design. 

<img width="200" alt="Screenshot 2024-03-25 at 10 45 31" src="https://github.com/grafana/grafana/assets/74534993/0fb52bc0-ba0f-4854-8b0a-eea089104c73">

**Comment by drewhammond** [comment]
@natellium will there be a way to disable the button in v11?

Also, you don't owe us an answer, but I'm curious why Grafana Labs thinks sharing needs any improvement. Anecdotally, Grafana is the most widely "shared" tool at my company with hundreds of dashboard and panel links being shared in various slack channels per day. I can't recall a single time where someone has said "I wish I could share this link, internally, but also change the theme to break the viewers' preferences"

I looked at the Figma diagrams and I understand there may be advanced multi-org use cases where ad hoc permissions need to be generated to facilitate sharing, but that seems like something that should be configurable then (i.e. please give us a way to disable this new "sharing" entirely, similar to how we can currently disable external snapshot sharing)

Re: your screenshot; it looks like an improvement over the current design (I assume it will be next to the user avatar), but any button that isn't gray will still look like a primary action, even if the fill color is no longer blue.
