### ISSUE TITLE
[Feature request] Allow parentheses in macro expansion for MySQL data source

### ISSUE THREAD

**Issue by ikirker** [grafana/grafana#8411]
With 4.3 beta 1, because (as far as I can tell from a quick inspection of [the regex](https://github.com/grafana/grafana/blob/ae5e004b6980e4cacf7cc9b50b4beef5eea99340/pkg/tsdb/mysql/macros.go#L12)) the macro expansion parameter terminates at the first closing parenthesis, using expressions including MySQL functions as the parameter for a macro gives unexpected results that can give confusing syntax errors.

Allowing functions here to work as naively expected would make individual macros significantly more flexible (IMO).

**Comment by ikirker** [comment]
Thinking about this a bit, it would be easy to let this run away a bit into some rather gnarly depths of actual SQL parsing.

Do people have any thoughts on replacing the macro parameter characters from `()` to something like `{{}}`, for a simpler implementation that only slightly modifies the current code? It'd make it more obvious to the end-user that they're doing text replacement, rather than merging into the SQL, too.

**Comment by bascarsija** [comment]
this appears to affect postgres as well, so i created issue #10380 for that, as this issue is currently specific to MySQL.

feel free to merge these two issues if that is appropriate, of course

**Comment by ikirker** [comment]
Some very quick regexp testing in the Go Playground suggests that this *might* be possible to handle with a `\b()` pattern. (This is mostly a note to remind *me*, I'm happy to give it a try if no one else does it in the meanwhile.)

**Comment by zoltanbedi** [comment]
We tried to fix this but it broke everything and turned out that it would need some more considerations. We will revisit this later.
