### ISSUE TITLE
Grafana 10.4.0 - Test user mapping in menu Authentication shows only two group memberships

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#84123]
### What happened?

With Grafana 10.4.0 Test user mapping in menu Authentication shows only two group memberships. One match and one "No match".

### What did you expect to happen?

Linke until Grafana 10.3.4 I expect to see all LDAP groups with "No match"

### Did this work before?

Until Grafana 10.3.4

### How do we reproduce it?

1. Use menu Authentication
2. Test user mapping
3. Enter your LDAP Username

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:  10.4.0
OS:          Docker
Browser:  Chrome Version 122.0.6261.95 (Offizieller Build) (64-Bit)

### Grafana platform?

Docker

### Datasource(s)?

No

**Comment by gfarcas** [comment]
I have the same problem on the same version.
Every refresh shows only one group, changing every time I refresh

**Comment by gfarcas** [comment]
It seems the roles are returned in json by the api, the problem is they are not displayed correctly in the ui

**Comment by gfarcas** [comment]
they are returned incorrectly though all of them have this:
```
            "orgId": 0,
            "orgName": "",
            "orgRole": "",
```
Shoudn't those fields be populated like before?

**Comment by gfarcas** [comment]
same issue on 10.4.1
However, on both of them it seems that the matched groups are displayed correctly
