### ISSUE TITLE
InfluxDB: Have maxDataPoints input for flux variable queries

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#84120]
We calculate the maxDataPoints based on the panel size. For the variables there is no panel size so we cannot calculate the maxDataPoints. We use a default value https://github.com/grafana/grafana/blob/main/pkg/services/query/query.go#L324

For flux we have an enforcer https://github.com/grafana/grafana/blob/main/pkg/tsdb/influxdb/flux/executor.go#L32-L33
So it ends up as 1000.

For some cases users might need more than 1000 points. So we will give that option to users by adding maxDataPoints input in VariableEditor. In order to support maxDataPoints we need `CustomVariableSupport`. Loki might be a good example how we can add that support https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/components/VariableQueryEditor.tsx

**Comment by itsmylife** [comment]
This requires `CustomVariableSupport`. 
Examples: 
1. [Prometheus](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/variables.ts)
2. [Loki](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/LokiVariableSupport.ts)

**Comment by gefaila** [comment]
As the originator of this issue can I check in for an ETA.  Just need to communicate with my team because currently we have great IIoT dashboards showing all machines and all parameters but engineers can only choose from the first 1000 parameters in the variable list.  This is affecting our original purpose of using Grafana for visualising troubleshooting data for machines.

**Comment by itsmylife** [comment]
@gefaila This requires some prerequisite work. I started dealing with those prerequisites. I'll link this issue to those PRs. You can track the progress. Unfortunately, I cannot give an ETA. But this is on my list and try to deliver it as soon as possible.

**Comment by gefaila** [comment]
Ok, thanks for the update.
No rush. Just cool that someone has it in sight.
:-)
