### ISSUE TITLE
In editor, occassionally some characters are missed or the cursor moves to the end during typing

### ISSUE THREAD

**Issue by kennethso168** [grafana/grafana#84125]
### What happened?

https://github.com/grafana/grafana/assets/5262487/16fd0b4c-767a-4237-8903-e1a96c17fdef

Example of missed characters or jumps:
00:38 - `Mem`: the "`em`" disappears shortly after typing
00:45 - Attempt to type `$` within the double quotes move the cursor to the end
01:08 - `arc_c`: the underscore `_` shortly disappears before I notice, therefore `arcc` is typed instead
01:27 - Extreme difficulty in typing `or`

Might be related to #54942 , but that had different symptoms as the cursor always jumped to the end on every key press. Mine only happened occassionally. It seems that it may be related to autocomplete as the autocomplete popup disappears every time when missed characters/jumps happen.

### What did you expect to happen?

All characters are successfully typed without being missed and without the cursor suddenly moving to the end

### Did this work before?

Don't know, only started using Grafana for a short time

### How do we reproduce it?

N/A

### Environment (with versions)?

Grafana: v10.4.0 (03f502a94d)
OS: Reproduced with both Windows 10 (personal machine) and Linux Mint (fresh install)
Browser: Reproduced with both Firefox (Win 10 and Linux Mint) and Chrome (Win 10 only)

Not reproducible on Grafana Play (Grafana v11.0.0-67348 (778d80f922), but this version is not released?)

### Grafana platform?

Docker

### Datasource(s)?

Tested with both Prometheus 2.42.0 and VictoriaMetrics

**Comment by JDuskey** [comment]
Can confirm this is happening for me as well.

**Comment by itsmylife** [comment]
This is not happening anymore in the `main` and `v11.0.0`
The related PR is here https://github.com/grafana/grafana/pull/85942
Could you please check this when v11.0.0 will be released?

**Comment by robhamnett** [comment]
This has happened a bunch to me lately with v11

**Comment by DutchEllie** [comment]
It's still constantly happening to me, running v11.4.0
