### ISSUE TITLE
Tool tip scroll does not work in 10.4.0

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#84136]
### What happened?

I've tested Grafana 10.4.0 with ```GF_FEATURE_TOGGLES_ENABLE=newVizTooltips``` but the tool tip scroll does not show
![Screenshot_20240310_103106](https://github.com/grafana/grafana/assets/2118079/3d92c4e0-5052-4576-a52f-6f24da1d179c)

Relates to #82177

### What did you expect to happen?

A scroll bar should be pressent

### Did this work before?

no

### How do we reproduce it?

1. run grafana 10.4.0 
2. Add a time series panel with metrics with many series
3.

### Is the bug inside a dashboard panel?

Body is too long to add it here

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker
Browser: chrome

### Grafana platform?

None

**Comment by leeoniya** [comment]
it should become scrollable once you anchor it by clicking. otherwise, how do you expect to scroll it when you cannot hover into it?

**Comment by gespi1** [comment]
doesnt work. Even on 10.4.3

**Comment by leeoniya** [comment]
we added tooltip `maxHeight` control, which makes it scrollable beyond that height.

see https://github.com/grafana/grafana/issues/89834

> doesnt work. Even on 10.4.3

try 11.1: https://grafana.com/grafana/download
