### ISSUE TITLE
Explore Loki: Failed to load log volume for this query

### ISSUE THREAD

**Issue by david-peters-aitch2o** [grafana/grafana#84144]
### What happened?

When browsing to Explore for Loki the Log Volume displays 

```
Failed to load log volume for this query
parse error at line 1, col 77: syntax error: unexpected IDENTIFIER
```

### What did you expect to happen?

a bar of logs volume 

### Did this work before?

yes

### How do we reproduce it?

1. log into Grafana
2. go to explore, select Loki
3. select any logs and watch the Log Volume

### Environment (with versions)?

Grafana: v10.4.0
OS: Amazon Linux Version 2
Browser: Safari and Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Loki

**Comment by theophileds** [comment]
I'm facing the same problem since I upgraded Grafana to version 10.3.X.

The problem doesn't occur anymore when I downgrade to version [10.2.5](https://github.com/grafana/grafana/releases/tag/v10.2.5).

I suspect this [change](https://github.com/grafana/grafana/pull/79681) is responsible.

Grafana: 10.3.4
Loki: 2.6.1

**Comment by emaildanwilson** [comment]
We've had the same problem on Grafana Cloud for a few months now but have not had the chance to open a ticket. Note that the error changes to a different column number depending on the length of the query.

**Comment by frankh** [comment]
Had the same problem, confirmed rolling back to 10.2.5 worked

Grafana: 10.3.3
Loki: 2.7.5

**Comment by martonivan** [comment]
Make sure that your Loki server supports `| drop __error__` label filtering, since it's appended to the Gafana histogram query. It is for sure in 2.9.1.

**Comment by emaildanwilson** [comment]
It looks like that feature was aded in Loki version 2.8.10: https://github.com/grafana/loki/pull/7975

**Comment by gulpo** [comment]
Can confirm that upgrading Loki fixed the problem in my case also.
Grafana 10.3.3
Loki 2.6.1 upgrade to 2.9.4

So Grafana 10.3.x should with loki 2.8.10+ I guess. For the logs volume feature at least

**Comment by victor-sudakov** [comment]
Had the same problem in Grafana 10.4.0 , upgraded Loki to 2.8.11 which solved the problem.

**Comment by davordbetter** [comment]
I have Grafana 10.4.0 and Loki v2.9.3 but still having this issue

**Comment by lyz-code** [comment]
@davordbetter we run into the same issue, even though helm is saying that we're at Loki v2.9.3 the statefulset was using version 2.6.1. Describe the pod to make sure that you're using the same version as you expected.

We haven't found in our code where is the version set, so we've added a `tag: latest` to our values.yaml. That solved the issue

**Comment by weeezes** [comment]
Updating to a fresh Loki worked for us too.

**Comment by davordbetter** [comment]
I can confirm. Added tag latest like @lyz-code suggested and it works now. Before, it was 2.6.1 image tag (this must be a bug in helm chart, because yaml says app version is 2.6.3)

**Comment by ivanahuckova** [comment]
Thanks to everyone who provided help and guidance here. Log volume works with Loki version 2.8 and higher. We have updated the documentation to clarify which version of Loki is needed to support full functionality in Grafana: https://grafana.com/docs/grafana/next/datasources/loki/#supported-loki-versions

**Comment by zouchengli** [comment]
> [@davordbetter](https://github.com/davordbetter) we run into the same issue, even though helm is saying that we're at Loki v2.9.3 the statefulset was using version 2.6.1. Describe the pod to make sure that you're using the same version as you expected.
> 
> We haven't found in our code where is the version set, so we've added a `tag: latest` (which is the chart default in theory) to our values.yaml. That solved the issue

Upgrade to same loki-promtail image tag work for me

**Comment by zakkg3** [comment]
Same here. Loki-stack says app version is 2.9.3 but its 2.6.1

```
helm search repo grafana/loki                                                                         ✔
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
...
grafana/loki-stack          	2.10.2       	v2.9.3     	Loki: like Prometheus, but for logs.
```

that  rendered:

```
image: 'grafana/loki:2.6.1'
```

**Comment by theophileds** [comment]
@zakkg3 grafana/loki stack is not maintained much anymore, I would advise you to use grafana/loki instead.

**Comment by Uday599** [comment]
Facing similar issue with below versions - 

grafana 11.0.0                            
loki 3.2.0

**Comment by joerx** [comment]
> [@zakkg3](https://github.com/zakkg3) grafana/loki stack is not maintained much anymore, I would advise you to use grafana/loki instead.

**Comment by joerx** [comment]
> [@zakkg3](https://github.com/zakkg3) grafana/loki stack is not maintained much anymore, I would advise you to use grafana/loki instead.

X is not used much anymore, please use X instead?

**Comment by theophileds** [comment]
@joerx I think what he meant was moving from the [loki-stack](https://artifacthub.io/packages/helm/grafana/loki-stack) to [loki](https://artifacthub.io/packages/helm/grafana/loki), which is indeed true, I had to move as well because Loki was no longer upgraded on the former chart.
