### ISSUE TITLE
template issue (adding '%7B and %7D) aka { } (grafana 4.2)

### ISSUE THREAD

**Issue by DanoOM** [grafana/grafana#8416]
Hi all, we are preparing to move to grafana 4 (from 2.5), and have encountered an odd issue where some graphs are not rendering properly (getting 500 back from the server).

Investigation has shown:
The following graphite expression is being process incorrectly Grafana 4:
aliasByNode(sumSeries(bap.$datacenter-prd-bap-*.url.xyz.2xx-responses.m1_rate), 4)

IN 2.5, this is sent via http
target=aliasByNode(sumSeries(bap.adc-prd-bap-*.url.xyz.2xx-responses.m1_rate)%2C%204)

but in 4.2 this is sent.
target=aliasByNode(sumSeries(bap.%7Badc%7D-prd-bap-*.url.xyz.2xx-responses.m1_rate)%2C%204)

This ends up in a Status: 500 coming
If we change the expresison above to: (i.e. drop the aliasByNode)
sumSeries(bap.$datacenter-prd-bap-*.url.xyz.2xx-responses.m1_rate)
its works as expected..

NOTE:
The following works just fine on 4.2 as well.
aliasByNode(bap.$datacenter-prd-bap-*.jvm.SystemCpuLoad,1)
aliasByNode(bap.$datacenter-prd-bap-*.jvm.SystemCpuLoad,2)

**Comment by DanoOM** [comment]
Closing this out..as I do not believe the '{' '}' are an issue, still investigating the root cause of the 500

**Comment by torkelo** [comment]
You can upgrade graphite, old versions don't support single value in glob expression
