### ISSUE TITLE
How to use snmp octet string data in single stat panel?

### ISSUE THREAD

**Issue by AL7DS** [grafana/grafana#8417]
I see that string data is now able to be used in a single stat panel, but no where is there any instruction or example on how to go about it.

My monitored equipment only returns string data from queries.  I need to grab that string and based upon what text is returned, issue an OK or Error indication on a singlestat panel in a similar fashion to the value to text capability.  Data source is influx via icinga2.
I also have number values that are being returned as strings.  I need to display that value as a number in the panel.  ie: a temperature value is returned as "40.00C".  I want it to display as 40.0 and have a sparkle line reflect the changes over time.

**Comment by toni-moreno** [comment]
Hi @AL7DS If you sue influxdb as a data backend, I suggest gather and transform data from 40.00C to 40 in the same agent  and send only values. 

You can do it with snmpcollector  by defining a STRINGPARSER  SnmpMetric DataSrcType  (https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics). 

I hope this could help you

**Comment by torkelo** [comment]
The singlestat panel can show the text returned by your query if you change query format option to `Table`,  then it will show value the column you specify in options, of the first row. 

You cannot replace / map it to something else, you will have to do that in the query (if you data source query language support it)
