### ISSUE TITLE
Heatmap: Metric labels are not rendered in Data Links when a unit is selected   

### ISSUE THREAD

**Issue by lorinescu** [grafana/grafana#84182]
### What happened?

I am  building drill down Data Links for Heatmaps that use the bucket name label. Field labels are not rendered in Data Links attached to a Heatmap *when* a unit is selected. When the unit is *number* (default) all is well.. Field labels do render in Time Series and other visualizations no matter of the unit selected. 
I have tried to use `newVizTooltips` feature flag but the same problem occurs. 

![grafana-datalinks-heatmap](https://github.com/grafana/grafana/assets/47192237/63c30939-b001-43cf-b9e8-31449dbfe7dd)

### What did you expect to happen?

The Data Link contains the raw value, without unit, of the bucket name.

### Did this work before?

No

### How do we reproduce it?

1. Create a histogram metric with the bucket names called `le`
2. Create a Heatmap visualization  
3. Add a Data Link with `moo.com/${__field.labels.le}` link and/or title
4. Set the unit to Time -> Seconds - the data link shown in the pop-up or in the link will be `moo.com/`
5. Set the unit to Misc -> Number - the data link will be `moo.com/<bucket name>`

### Environment (with versions)?

Grafana: 10.0-10.4.0
OS: Linux
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by leeoniya** [comment]
> I have tried to use `newVizTooltips` feature flag but the same problem occurs. 

there have been some big improvements to Heatmap data links (https://github.com/grafana/grafana/pull/83876) in recent builds, i recommend you try the nightly build: https://grafana.com/grafana/download/nightly?edition=oss

> Add a Data Link with `moo.com/${__field.labels.le}` link and/or title

now works on `main` :)

<img width="530" alt="image" src="https://github.com/grafana/grafana/assets/43234/e6115210-eddc-4d66-8d8b-7761a272bb19">
