### ISSUE TITLE
Oncall scheduler always leave an hour gap when recurrence period is set to 7 days

### ISSUE THREAD

**Issue by kevinyang372** [grafana/grafana#84192]
### What happened?

When creating the oncall schedule, I set the recurrence time to 7 days. However, after saving, the scheduler automatically adds a 6 days, 23 hours shift length limit. This creates an hour gap between two shifts that we cannot close.
<img width="402" alt="image" src="https://github.com/grafana/grafana/assets/30107576/e72cdcd0-1a42-41ef-8d15-80704f8ea616">

If I try to turn off the limit, the scheduler shrinks the oncall length to 1 day which is also not what I expect.
<img width="1126" alt="image" src="https://github.com/grafana/grafana/assets/30107576/d227c0e4-a236-4b93-841d-100c5db90a08">

### What did you expect to happen?

The oncall scheduler should not add the hour long gap automatically. Users should be able to create shifts without gaps in them

### Did this work before?

Using Grafana Oncall for the first time

### How do we reproduce it?

1. Create new oncall
2. Add rotation and set recurrence period to 7 days
3. Save the changes -- see scheduler automatically adds the 6 days, 23 hours limit to the final schedule

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
Hi @kevinyang372 
Thanks you for creating this issue
For oncall related issues please resubmit here 
https://github.com/grafana/oncall/issues

Thank you!
