### ISSUE TITLE
Dashboard can be saved with add-library-panel panel

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#84199]
One can save dashboard with add libtary panel widget:

<img width="2088" alt="image" src="https://github.com/grafana/grafana/assets/2376619/ab901472-cf54-4c17-aeb0-45491187de84">

**Comment by mdvictor** [comment]
Is this not desired? Same happens in old arch.

**Comment by dprokop** [comment]
@mdvictor - you are right, I'll close it for now
