### ISSUE TITLE
Grafana smtp not working

### ISSUE THREAD

**Issue by SecretSun** [grafana/grafana#8422]
I am trying to configure grafana with smtp to alerting problem emails. But smtp not working.

I have configured grafana.ini smtp values appropriately i.e.
[smtp]
enabled = true
host = smtp.xxx.com:994
user = xxx@xxx.com
password = xxx
;cert_file =
;key_file =
skip_verify = false
from_address = xxx@xxx.com

From logs, I get:
t=2017-05-19T15:39:18+0800 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF
t=2017-05-19T15:39:18+0800 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error=EOF

Grafana v4.2.0 (commit: 349f3eb)

**Comment by torkelo** [comment]
do you have another port to test with? This seems like a common error (when googling smtp issues). Seems like the TLS upgrade/start is not working

**Comment by SecretSun** [comment]
Do you know graylog, We used the same smtp configuration in graylog inside, The graylog is working, but graylog used transport_email_use_tls = true ,transport_email_use_ssl = true?
I try skip_verify = true, it's always this error ...
