### ISSUE TITLE
[Feature Request] Series names in alerts on graphs using templates? 

### ISSUE THREAD

**Issue by Samuel1989** [grafana/grafana#8425]
- What Grafana version are you using?
V4.2.0

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu 14.04

- What did you do?
Create a graph to display memory across multiple servers, and used the Grafana Template function to be able to filter servers. Then create an alert across these servers to notify me if one of them crosses a threshold.

- What was the expected result?
The ability to provide the servers name in the alert, rather than a static piece of text, e.g. "$Server has exceeded x threshold."

- What happened instead?
I was only able to provide a static description/name "Something has gone wrong, it could be anyone of the servers involved".

I am not sure if this is already possible (I apologise if it is, I did have a search and whilst there were lots of more complex requests, there didn't seem to be an exact match).

Is it possible to be able to provide the series name in the alert name/description that is sent? I appreciate multiple series can alert at the same time and being able to alert per series is likely the ultimate solution, however, in the interim, just having the current/first offending series in the title of the alert would probably be enough to make it super useful.

At the moment the only way I think I could distinguish between which server has crossed the threshold would be to have a separate graph for each? With an alert configured statically detailing the servers name etc? Although this would mean undoing all my nice templating work :( which I really like.

Any help/info on this would be really appreciated.

Sam

**Comment by torkelo** [comment]
the series name that caused the alert to fire should be included in the email/notification message. 

Not sure I understand what you want beyond that.

**Comment by Samuel1989** [comment]
Hey @torkelo,

Thanks for the quick reply.

I now realise I should have added some more detail, apologies.

The Metric Name/Value is very useful, however, these only appear to be embedded in the email body, in terms of a quick glance at what has gone wrong and where it would be super useful to be able to include it in the emails subject using the same patterns as the alias overrides.

e.g. in my alert name/subject: "$measurement has exceeded its threshold"

Also I am using the Hipchat plugin, which doesn't appear to include the metric name and/or value, just the alerts title.

Sam
