### ISSUE TITLE
Installing a plugin through an API request

### ISSUE THREAD

**Issue by LeamonaDor** [grafana/grafana#84273]
**Why is this needed**:

I run `grafana` through `docker` and want the plugins to be installed at runtime and not at build time.

**What would you like to be added**:

I want an `API` request to install plugins in `grafana`.

**Who is this feature for?**

For anyone who has been missing this until now...

**Comment by usmangt** [comment]
Hi @LeamonaDor,

Thanks for opening this issue

You can follow this [example](https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#example-1) to install at runtime via docker
