### ISSUE TITLE
Prometheus: Respect dashboard queries when querying ad hoc filter labels

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#84276]
Currently, when presenting the ad hoc filters, prometheus data source shows all available labels in the labels selector. 

With https://github.com/grafana/grafana/pull/81071 merged it's now possible for the ad hoc filters to access the queries that exist in the Grafana dashboard. This allows data source to narrow down the list of presented ad hoc filter labels to a list that' meaningful in the context of a given dashboard.

However, no data source currently does that, and Prometheus seems like an obvious candidate to introduce this feature. 

Please have a look at  https://github.com/grafana/grafana/pull/81071  to see the API changes that enable this feature.

**Comment by bergquist** [comment]
👍 @dprokop do we know the order of the queries? Can we expect them to come in the same order as the panels?

**Comment by dprokop** [comment]
@bergquist yes, they should come in the order of the panels.

**Comment by bergquist** [comment]
If there is a limitation in the prometheus API for how many timeseries that can be used when fetching labels, we should just use the first X. 

Would be frontend be clever enough to extract the timeserie name themself or are we better of delegating that to the backend? 

ping @kylebrandt @itsmylife

**Comment by kylebrandt** [comment]
@bergquist Probably the BE I think, since we can use the parser to parse out all the metric selectors from the queries.

**Comment by itsmylife** [comment]
@dprokop Currently we don't receive any query information when `getTagKeys` or `getTagValues` called. Do I need to enable a feature flag or do something special to make it work?

**Comment by dprokop** [comment]
@itsmylife  - are you using Scenes based dashboard?

**Comment by kylebrandt** [comment]
@dprokop For that it is `scenes` and `dashboardScene` toggles, and then put `&scenes=true` (`scene`) ?

**Comment by itsmylife** [comment]
@dprokop Nope. Just a normal dashboard. I'll try with `dashboardScene` feature toggle. That's the only feature toggle I should enable right?

**Comment by dprokop** [comment]
> @dprokop Nope. Just a normal dashboard. I'll try with dashboardScene feature toggle. That's the only feature toggle I should enable, right?

Yes. Then all dashboards will be rendered with Scenes architecture by default. 

If you don't want to enable the toggle, you can simply add `&scenes`  query param to the URL.

**Comment by dprokop** [comment]
> @dprokop For that it is scenes and dashboardScene toggles, and then put &scenes=true (or scene=true) in dashboard url ?

@kylebrandt - it's **either** the toggle (`dashboardScene`) or query param in the URL :)

**Comment by itsmylife** [comment]
I have the PR ready https://github.com/grafana/grafana/pull/85674
Please advise if I should backport this to v11 and `add to change log`

**Comment by itsmylife** [comment]
Backend changes that allows backend to apply ad-hoc filters to the query https://github.com/grafana/grafana/pull/85969
