### ISSUE TITLE
Telegram "Message Thread ID" is required by UI

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#84296]
### What happened?

When a user creates a new one or edits an existing contact point with Telegram integration, UI does not let it save unless the field "Message Thread ID" is specified. 

![311868726-4b5cc39e-cccb-4b03-a747-32cce56e0fa9](https://github.com/grafana/grafana/assets/25988953/fee28aea-3b30-4d80-b9c0-5761e1a343d6)

### What did you expect to happen?

The field is marked as not required in the code https://github.com/grafana/grafana/blob/cf601fab0906f1d811f1aa2fe18a67bc5421e3db/pkg/services/ngalert/notifier/channels_config/available_channels.go#L818-L826

but UI seems to 

### Did this work before?

The field is new in 10.4 and before it worked.

### Environment (with versions)?

Grafana: 10.4.0

**Comment by byawitz** [comment]
![image](https://github.com/grafana/grafana/assets/316103/11c30cdb-6b66-4a27-8e50-d41626ff55a8)
Putting `0` solved the issue

**Comment by FulvioSpelta** [comment]
> Putting `0` solved the issue
Thanks for the workaround.
