### ISSUE TITLE
Override default series color palette 

### ISSUE THREAD

**Issue by fschaer** [grafana/grafana#843]
Hi,

I just started "playing" with grafana and graphite a short while ago, so it's perfectly possible I overlooked what I will ask :  is it possible to specify a series colors, or a theme color scheme ?

I've seen the "color picker" appear when you click on a specific series color, but all these colors do not allow for correctly viewing my ~25 stacked series on the same graph. Not enough contrast, I fear. What I'd like is to specify a (list of) series color by value, e.g : RGB=00FF00 ?

Can I give grafana my list of prefered colours instead of the pre-defined ones, which I find are not optimum for what I whant to graph (and how many can I feed grafana with ? Can I have 30 prefered colors ?) ?

Also, even if possible for one series at a time, I'm wondering how this could be done when selecting series with a star in the metric query, for instance : 
monitoring.infosys.batch.queues.node74.*.GlueCEStateRunningJobs

?

Thanks

**Comment by misterstrogg** [comment]
:+1: Would be really nice to have a color palette per-query. 

 So, for example, a stacked CPU graph can have reds for system, yellows for user, blue-blacks for iowait, light greens for idle.

The colors for each type are close enough you can get a good representation of how the pool is doing on cpu overall, but they are different enough that you can also tell if one host or cpu is struggling disproportionately. 

![Uploading querypalettes.png . . .]()

**Comment by torkelo** [comment]
@misterstrogg you can change color easily for each series, not sure what you mean "palette per-query"

**Comment by misterstrogg** [comment]
For a static graph choosing each series' color manually is fine. But once I change a template variable, new series are generated with new colors from the wildcards in my queries. 

I'm trying to get to something like the template-generated image here:

![querypalettes](https://cloud.githubusercontent.com/assets/7613580/7220420/042ae814-e67b-11e4-99fb-42b7e989a78f.png)

Where the template variable is the hostname, the wildcard is the cpu number, and each type of counter (system, iowait, etc) is handled by its own query, which has a limited color palette, that it cycles through as series are generated by the query. 

Palettes are the grail in this case though, I'd be giddy if I could force all series from a query to a single color. If I could limit a query to generating series of only one color, I could achieve a similar banded-group effect with transparency of line fill + non-zero line width.

**Comment by faxm0dem** [comment]
:+1: for custom palettes: the one available is too narrow

**Comment by matschaffer** [comment]
I could also get behind at least choosing the start color for a graph's.

The use case for me would be to differentiate success metrics (via the usual blue/yellow/green/orange), and error metrics (starting with red, then blue/pink/purple).

**Comment by faxm0dem** [comment]
as a workaround you could invert y axis for errors

**Comment by fschaer** [comment]
For the record : it seems that with grafana 2.6+ you can override series color using this kind of thing in the dashboards json : 

"aliasColors": {
    "alice": "#FF0000",
    "apc": "#554400",
    "atlas": "#0000FF",
    "atlasMC8": "#0000FF",
    "atlasana": "#0080FF",
    "biomed": "#8000FF",
    "cms": "#00FF00",
    "hess": "#FF0088",
    "ops": "#C0C0C0"
  },

(these are series titles)

At least we can override things, even if that's not perfect

**Comment by torkelo** [comment]
@fschaer you can pick colors by clicking on the series legend (the color line icon), or specify override rules using regex in the styles tab

**Comment by aschor** [comment]
as a matter of fact, I found a "hack" : 
- edit the file grafana/public/app/boot.xxxx.js 
- search the string    i.colors=[
- edit / add / remove colors as hex RGB values
- enjoy your new colors

**Comment by steviecoaster** [comment]
You can edit the JSON of the dashboard and change the colors to the hex code of your liking. I just accomplished this in needing black to show Printer Toners on a panel. Worked a treat!

**Comment by samlinbris** [comment]
FYI - Not sure about older versions. I'm on 4.1.1 and I can change my series colour by going into 

> Edit Graph > Display > Series overrides > Color

![screen shot 2017-03-15 at 11 00 00 am](https://cloud.githubusercontent.com/assets/5134976/23928990/bc58e2ca-096e-11e7-9289-db31e4353f3a.png)

**Comment by maxboyer** [comment]
For the next person, you can change the color by clicking on the line in the legend. *Mind blown* finding it.
![grafana_colorchange](https://cloud.githubusercontent.com/assets/26586097/24220374/69ff0916-0f20-11e7-9ece-9443a9df3147.PNG)

**Comment by austinbutler** [comment]
@maxboyer this issue is I believe about adding to/modifying those colors in the popup.

**Comment by maxboyer** [comment]
@austinbutler Reading the first post again, you're right. I'm new to grafana and found out today how to change the graph colors.

**Comment by johann8384** [comment]
Any update on being able to update the default pallet? Is this something that is likely to get attention in upcoming versions?

**Comment by kasperkarlsson** [comment]
I would also (really) like to see this feature. Is there any chance that it might get implemented?

**Comment by swe** [comment]
Any updates or not?

**Comment by jeanduporte** [comment]
No updates for now (I'm on Grafana 4.0). Maybe try in the Grafana 5.0 Beta to see if a update is available or not.

**Comment by torkelo** [comment]
actually starting from v4.5 (I think) we introduced a new color picker that allowes you to specify a custom color

**Comment by jjustinwhite** [comment]
The color picker is great, but it would be nice to be able to set default colors. Having to change every metric on every panel by hand is tedious.

**Comment by barry-dutton-ck** [comment]
@torkelo I don't think this addresses the question. My understanding is that people want to alter the set of colors that Grafana chooses from when determining which colors to assign to each series in a graph. This is more for when you don't know specifically what your series are but know that things are related and want them colored similarly. This would also be helpful for doing things like preventing Grafana from assigning something a very dark color when the background is black!

I too would love to be able to change the set of colors that Grafana chooses from (possibly even specifying RGB ranges, but at least being able to give a list of actual colors?)

**Comment by jjustinwhite** [comment]
Yep, for us we like to have the first metric start as blue, the second metric is green, the third metric is yellow... and so on. Right now, Grafana defaults to green, then yellow, then teal (maybe?). We can switch these by hand of course using the color picker, but it isn't ideal to do this each time. Allowing an override, or for us to change the default coloring order would be great.

**Comment by CME64** [comment]
The feature is there and just needs voting, here is the request:
https://github.com/grafana/grafana/issues/17092

And here is the PR:
https://github.com/grafana/grafana/pull/17076
