### ISSUE TITLE
BUG: InfluxDb multiple queries configured as proxy

### ISSUE THREAD

**Issue by byrner75** [grafana/grafana#8430]
version: Grafana 4.2.0
datasource: InfluxDB
platform: docker

I created a graph with multiple queries. The second query doesn't render. If I hide the first query (pressing the eye button) the diagnostics panel complains about a missing q parameter.

However if I re-configure the datasource to be direct it works !

**Comment by torkelo** [comment]
unable to replicate in v4.3 
http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit&orgId=1
