### ISSUE TITLE
newVizTooltips loses labels after refresh on panels using math expression

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#84333]
### What happened?

Trying out newVizTooltips. Noticed some of my panels tooltips were missing the correct labels. It only occurs on panels where I have used math expressions AND only after a refresh. 

See towards end of video (1:13), labels `test1` and `test2` become `A` and `B` after the auto refresh happens.

### What did you expect to happen?

Consistent labels matching legend don't change after refresh

### Did this work before?

Never tried newVisTooltips pre 10.4, but it does work fine using old style tooltips on 10.4 and all previous

### How do we reproduce it?

[vokoscreenNG-2024-03-12_21-46-51.webm](https://github.com/grafana/grafana/assets/2304970/dac977bd-0691-4c45-8751-9041b98bce5e)

### Is the bug inside a dashboard panel?

Couldn't paste get help content here "There was an error creating your Issue: body is too long (maximum is 65536 characters)."

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker
Browser: Firefox

### Datasource(s)?

Graphite

**Comment by bobemoe** [comment]
This seems to be working ok on main branch (11.0.0-dev) so I guess its fixed? Cant find a 10.x-dev on docker hub to test if its fixed there too?

**Comment by leeoniya** [comment]
try https://grafana.com/grafana/download/nightly?edition=oss

**Comment by leeoniya** [comment]
these days we only backport critical & security bug fixes to production features. so unfortunately this wasnt possible like previously.
