### ISSUE TITLE
[Bug] GRAFANA_GROUP is ignored in .deb package

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#8433]
Please include this information:
- What Grafana version are you using?

4.2.0

- What OS are you running grafana on?

Ubuntu 16.04

- What did you do?

Installed Grafana from the apt repo

Edited /etc/default/grafana-server

Changed the value of GRAFANA_GROUP to some other group which already exists on the system (and it is used by other processes).

Restarted grafana-server

- What was the expected result?

grafana-server should run as the new group

- What happened instead?

Still runs as the old grafana group:

```
# ps axo pid,euser,egroup,args | grep grafana
 1776 grafana  grafana  /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile= cfg:default.paths.logs=/var/log/grafana
```

**Comment by torkelo** [comment]
looks like the systemd spec file does not use env variables for user and group
https://github.com/grafana/grafana/blob/master/packaging/deb/systemd/grafana-server.service#L11

**Comment by torkelo** [comment]
closing due to this seems to impact no one else
