### ISSUE TITLE
Feature request: Variable usage in HTTP api

### ISSUE THREAD

**Issue by p0nt** [grafana/grafana#8434]
I would love to be able to use variables in HTTP requests:

http://icinga:3000/api/dashboards/db/icinga2-filesystems?var-host=nfs02&var-filesystem=All

This will allow a little less static configuration when I parse graphs for different hosts, because some hosts have only 1 filesystem and some have multiple which will mean that hardcoding panel id's will not work and will give errors when the panels don't exist for certain hosts.

more info: https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/42

**Comment by torkelo** [comment]
you can set variables via url:
http://play.grafana.org/dashboard/db/templating?orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-interval=1h

**Comment by p0nt** [comment]
ok but not via api, how can you get json out of this?

**Comment by torkelo** [comment]
The templating queries & variables and evaluation of repeated panels & rows is all done in the browser, so the api cannot return the info you want.

**Comment by p0nt** [comment]
ok thx!
