### ISSUE TITLE
Dashboards: The share dialog for a dashboard is broken and always leads to the 'share dashboard' dialog

### ISSUE THREAD

**Issue by ThomasMinor** [grafana/grafana#84340]
### What happened?

If you want to share a dashboard the URL always contains the parameter to open the share dialog: `&shareView=link`

### What did you expect to happen?

The generated URL links to the dashboard, not the dialog

### Did this work before?

It didn't stand out to me in the past but I can't tell for 100%

### How do we reproduce it?

1. Open a dashboard
2. Click on share
3. Inspect the generated URL and test it in another window

### Is the bug inside a dashboard panel?

All dashboards.

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)
OS: MacOS 14.4
Browser: Firefox 123.0.1 (64 bit)

### Grafana platform?

Kubernetes

**Comment by klieber** [comment]
I'm seeing this same behavior after a recent upgrade to v10.3.3 from v9.3.14.  I can also confirm it used to work fine before the upgrade.  The link just always includes `&shareView=link` now which results in the link going to the share link dialog rather than the graph you want.  So, making short links is impossible right now.

**Comment by tonypowa** [comment]
Hi @ThomasMinor  I can't reproduce this issue

When I click share,  the URL looks like this:
`http://localhost:3000/d/ebfd3459-f73c-4781-ac93-3ed487c3d631/akojmdfsas?orgId=1&from=1707260052748&to=1707261852748` 

|Grafana v10.2.2| Firefox 124.0.2

Can you try upgrading Firefox and other browsers?

**Comment by vfiset** [comment]
Hi @tonypowa ! Not OP but also getting the same behaviour with `Grafana v10.3.3 (252761264e)` and the latest Chrome and Firefox.

**Comment by juanicabanas** [comment]
Hi, the fix was included since Grafana v10.3.4. Please, upgrade to that version at least. Thanks!
