### ISSUE TITLE
[Feature request]Migrate dashboards from influxdb to pormetheux. 

### ISSUE THREAD

**Issue by tenfyzhong** [grafana/grafana#8435]
Please include this information:
- What Grafana version are you using?
docker image: grafana/grafana:3.0.3
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu-16.04
- What did you do?
I have 100+ dashbroads, and the datasource is influxdb. Now, I want to use prometheux instead influxdb. Is there any scripts help me to migrate the dashbroads? 
- What was the expected result?
After I migrate influxdb to prometheux, the dashbroads can be work.

**Comment by torkelo** [comment]
no script exists, they are radically different data sources, next to impossible to migrate automatically
