### ISSUE TITLE
XY Chart: Missing x dimension: Edit panel not working

### ISSUE THREAD

**Issue by PhilippDehner** [grafana/grafana#84360]
### What happened?

An unexpected error happened:
![grafik](https://github.com/grafana/grafana/assets/49042626/862f3698-52e0-4087-bcdc-c55e4b11e73b)
![grafik](https://github.com/grafana/grafana/assets/49042626/d5ac634b-6a1a-4a7a-adcf-14186b5af1cb)

### What did you expect to happen?

Normal panel edit window

### Did this work before?

No

### How do we reproduce it?

1. Create a query with no data
2. Insert it into the XY Chart panel
3. The error occurs, or save the dashboard, load it, and try to open the panel edit window

### Is the bug inside a dashboard panel?

[debug-Panel Title-2024-03-13 12 41 25.json](https://github.com/grafana/grafana/files/14587001/debug-Panel.Title-2024-03-13.12.41.25.json)

### Environment (with versions)?

Grafana: 10.3.0
OS: docker/Windows
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

PostgreSQL

**Comment by leeoniya** [comment]
the crash is fixed with `autoMigrateXYChartPanel` feature toggle enabled, which uses the new xychart2 code. we are currently rolling this out to production instances.

we still have a bit of work remaining to improve the shown error message tho.
