### ISSUE TITLE
template in home dashboard can't be saved  after refresh 

### ISSUE THREAD

**Issue by genkimaru** [grafana/grafana#8436]
`bug`
- grafana 4.2.0
- opentsdb
- win10
 
when I set template in home dashboard, I find it can't be saved after I refresh the page .  in fact , I can't find anywhere I can take the saving action. is there any bug or just it is design?
@torkelo 
 
![image](https://cloud.githubusercontent.com/assets/5584476/26299626/0d68188c-3f0e-11e7-9493-c3f39897397f.png)

**Comment by torkelo** [comment]
default home dashboard is a built in dashboard that cannot be modified. 

You can use "Save As" to save it to a new name, then star the dashboard. Then go organization Preferences or Profile preferences and change your home dashboard.

**Comment by genkimaru** [comment]
thank you very much   can I ask you a question , that if I need to set a template can be used  in every dashboard ,how can I  do ?

**Comment by torkelo** [comment]
Template variable definitions cannot currently be reused or shared between dashboard
