### ISSUE TITLE
Grafana v4.3.0-beta1 is missing an upper time bound in $timeFilter for GROUP BY to work in influx 1.2.4 while using, say, "Last 3 hours".

### ISSUE THREAD

**Issue by AndreCAndersen** [grafana/grafana#8437]
**What Grafana version are you using?**

Grafana v4.3.0-beta1 (commit: 3a89272), with ...

`InfluxDB v1.2.4 (git: master 77909d7c7826afe597b12d957996d6e16cd1afaa)`

**What datasource are you using?**

Influx's own '_internal'

**What OS are you running grafana on?**

Ubuntu 14.04.5

**What did you do? What was the expected result? What happened instead?**

Using the query builder, the following works when setting the window to "Last 3 hours":

```
FROM default runtime WHERE hostname = myhost
SELECT field(HeapInUse)
GROUP BY ____
ORDER BY time ASC
```

or using the free text version: `SELECT "HeapInUse" FROM "runtime" WHERE "hostname" = 'myhost' AND $timeFilter`

However, when I introduce a group by using:

```
FROM default runtime WHERE hostname = myhost
SELECT field(HeapInUse) mean()
GROUP BY time(1m)
ORDER BY time ASC
```

or using the free text version: `SELECT mean("HeapInUse") FROM "runtime" WHERE "hostname" = 'myhost' AND $timeFilter GROUP BY time(1m)`

This fails to produce any output. The log shows that the following was run: `SELECT mean("HeapInUse") FROM "runtime" WHERE "hostname" = 'myhost' AND time > now() - 3h GROUP BY time(1m)`

Running this manually gives the error "Server returned error: max-select-buckets limit exceeded: (128798969/1000000)".

From what I gather this is because there is no upper bound on the WHERE clause. Modifying it to `SELECT mean("HeapInUse") FROM "runtime" WHERE "hostname" = 'myhost' AND time > now() - 3h AND time < now() GROUP BY time(1m)` makes it work. The change was to set `now()` as an upper bound.

Grafana should add an upper bound to `$timeFilter`. I suppose the current window's upper bound should work.

The workaround is to explicitly set the upper bound. It also works when panning to historic windows. It only is an issue when using "Last 3 hours", etc.

**Comment by torkelo** [comment]
strange, this has never been an issue with inflxudb before, has there been a recent change requiring a upper bound?

**Comment by torkelo** [comment]
strange, unable to replicate this

**Comment by AndreCAndersen** [comment]
Have you set the `max-select-buckets` setting? It might be defaulted to 0, i.e., inf, i think.

**Comment by torkelo** [comment]
But how would an not having an upper bound change select buckets unless you have future data?

**Comment by AndreCAndersen** [comment]
This is a global issue. All measures are affected on my end ,including those in the `_internal` database, i.e., the influxdb monitoring database. I doubt they all have future data by mistake. This is also a pretty new release, only 14 days old, but was the one suggested as the current version over at: https://portal.influxdata.com/downloads

I've investigated the code changes and it does seem like the implied upper `now()` bound was removed: https://github.com/influxdata/influxdb/commit/d7c8c7ca4fbb86ac95d1828aaed82545a3d70883#diff-084cb29c383c1c0fffae2fac08113ad5L521

My previous version was [v1.1.0](https://github.com/influxdata/influxdb/releases/tag/v1.1.0). [Here](https://github.com/influxdata/influxdb/blob/800da5732b91c816b0a097acf8887fa2af1efa1a/coordinator/statement_executor.go) is the status of the above file at that time. The version I'm on now is [v1.2.4](https://github.com/influxdata/influxdb/releases/tag/v1.2.4). [Here](https://github.com/influxdata/influxdb/blob/77909d7c7826afe597b12d957996d6e16cd1afaa/coordinator/statement_executor.go) is the status of the above file now.

**Comment by torkelo** [comment]
But still pretty strange, that that having an upper bound reduces select-buckets (unless there is future data). 

I can try to set max-select-buckets to some thing and see if I can replace it, what did you set yours to?

**Comment by AndreCAndersen** [comment]
From my error message it seems I've set it to `1000000`.

**Comment by daniellee** [comment]
Closing this bug as it has been inactive for a long time and I couldn't replicate it easily. Let me know if this is still an issue and I can re-open it.
