### ISSUE TITLE
[Feature request] predictable panel id generation

### ISSUE THREAD

**Issue by freeseacher** [grafana/grafana#8438]
Please include this information:
- What Grafana version are you using?

 4.1.2
- What datasource are you using?

 influxdb 1.2
- What OS are you running grafana on?

 debian 8
- What did you do?

 i have created templated dashboard. add several static vars with such values
![image](https://cloud.githubusercontent.com/assets/289277/26304711/18fe972a-3ef5-11e7-9eab-94096f718f95.png)
than i've added panels with graph and repeat panels. 
![image](https://cloud.githubusercontent.com/assets/289277/26304753/3f40a32e-3ef5-11e7-935f-9f34d9dadcf1.png)
of cause i have rows for all templated vars. 
than i've selected several graphs from combobox
![image](https://cloud.githubusercontent.com/assets/289277/26304942/eec477ee-3ef5-11e7-88d3-8a863f6d8da2.png)

- What was the expected result?

 as far as i can see i got some panel id. 
it will be inserted in (png generation | embed graph | share link) links. 
i expect that panel id will be always the same.

- What happened instead?

panel id always generated and depend on order that panel was shown. that leads to unpredictable panel id generation.

with @alexanderzobnin we found that https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/model.ts#L135 is the problem. it returns id that depends on already generated panels not on graph content. 
in my opinion it have to return same panel id always. 
May be it will be better if there were a possibility to link graph not by panel id, but by title too. 
Or generate id with base64 of all vars used in panel. 
the best option is generate  panel id that way it can be predicted by external system.

**Comment by torkelo** [comment]
it should be predictable if your data source returns variable options in the same order (you can also have grafana sort the response)
