### ISSUE TITLE
Okta auth: Access denied on /connections/datasources to Admin role

### ISSUE THREAD

**Issue by ulidtko** [grafana/grafana#84411]
### What happened?

Updated `grafana-server` to 10.4.0 from 10.3.3.

Now, can't access the Datasources page when logged in via Okta, despite getting `Admin/editor` role:

![image](https://github.com/grafana/grafana/assets/365338/4cc08fc5-c19c-4f20-85f3-0807874adab9)

Server log says:

> Mar 13 19:10:33 i-038e9a3f34a5ebf9f grafana[342]: logger=context userId=9 orgId=1 uname=myuser.name@acmecorp.com t=2024-03-13T19:10:33.269842885Z level=info msg="Access denied" namespace=user userID=9 accessErrorID=ACE6960765070 permissions="any(datasources:explore datasources:create all of datasources:read, any of datasources:delete, datasources:write)"
> Mar 13 19:10:33 i-038e9a3f34a5ebf9f grafana[342]: logger=context userId=9 orgId=1 uname=myuser.name@acmecorp.com t=2024-03-13T19:10:33.269984737Z level=info msg="Request Completed" method=GET path=/connections/datasources status=302 remote_addr=172.30.1.178 time_ms=7 duration=7.210584ms size=24 referer= handler=/connections/datasources status_source=server

I do have access when logged in with username-password as `admin@localhost`.

### What did you expect to happen?

Admin/editor role for builtin auth === Admin/editor role from Okta

### Did this work before?

Yes... unfortunately I don't remember when, and the logs were rotated away, washed out by an error spam from a recent incident. Pretty sure it worked last year.

I do try to keep Grafana up to date, so this must've been a reasonably recent version.

### How do we reproduce it?

1. Create a free dev-account on okta.com
2. Create an Authorization Server
3. Add an OAuth2 "application" (client_id + client_secret pair), configure its users & groups
4. Configure `[auth.okta]` section in grafana.ini
5. In grafana's `ldap.toml`, 
```
[[servers.group_mappings]]                                                                   
group_dn = "cn=admins,ou=groups,dc=grafana,dc=org"                                           
org_role = "Admin"
```
6. Log in to grafana using this Authorization Server
7. /admin/users shows:
   ![image](https://github.com/grafana/grafana/assets/365338/837a921b-8840-4c1c-914a-97b4d5a66c24)
8. /connections/datasources

### Environment (with versions)?

Grafana: 10.4.0
OS: Ubuntu Jammy 22.04.4 LTS

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by Jguer** [comment]
Hey @ulidtko can you share censored versions of your `auth.okta` and also a screenshot of the org users page?

**Comment by Jguer** [comment]
What's happening is that okta oidc default maps to Viewer and as such your LDAP mappings are overridden every time the user logs in

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/#configure-role-mapping

Configuring `role_attribute_path` instead of relying on LDAP would be the recommended setup

**Comment by Jguer** [comment]
Closing as mapping the same users from different sources is not supported, if there's any extra info, I'll take a look at it

**Comment by ulidtko** [comment]
Hi again @Jguer, I think there's been misunderstanding of the issue. I don't have any LDAP connection here.

In fact, the issue reproduces after `rm /etc/grafana/ldap.toml` (and server restart, of course).

Also I'd just retested on Grafana v11.1.3 (beac3bdbcb) — same outcome.

To rehash the OP:
 1. There's `admin@localhost` which can access /connections/datasources just fine.
 2. There's an Okta OAuth method configured, that assigns admin role as expected :warning: 
 3. Yet, Okta users **with Admin role** get "Access denied" to /connections/datasources.

Server log:

> Aug 01 09:46:20 i-038e9a3f34a5ebf9f grafana[12474]: logger=context userId=9 orgId=1 uname=myuser.name@acmecorp.com t=2024-08-01T09:46:20.191121206Z level=info msg="Access denied" namespace=user userID=9 accessErrorID=ACE0082013765 permissions="any(datasources:explore datasources:create all of datasources:read, any of datasources:delete, datasources:write)"

<details><summary>
<i>(click expand)</i> <tt>GET /api/user</tt> for the Okta "admin" that gets the above access denied
</summary><pre>{
    "authLabels": [
        "Okta"
    ],
    "avatarUrl": "/avatar/2fde12550a3082ea501bc8f49f709f70",
    "createdAt": "2022-09-22T08:06:51Z",
    "email": "myuser.name@acmecorp.com",
    "id": 9,
    "isDisabled": false,
    "isExternal": true,
    "isExternallySynced": true,
    "isGrafanaAdmin": true,
    "isGrafanaAdminExternallySynced": false,
    "login": "myuser.name@acmecorp.com",
    "name": "Max Ulidtko",
    "orgId": 1,
    "theme": "",
    "uid": "u000000009",
    "updatedAt": "2024-08-01T09:46:01Z"
}</pre>
</details>

Notice `isGrafanaAdmin: true` :eyes: :point_up:


<details><summary>
<i>(click expand)</i> <tt>GET /api/user</tt> for admin@localhost
</summary><pre>{
    "authLabels": [],
    "avatarUrl": "/avatar/46d229b033af06a191ff2267bca9ae56",
    "createdAt": "2022-06-20T11:17:30Z",
    "email": "admin@localhost",
    "id": 1,
    "isDisabled": false,
    "isExternal": false,
    "isExternallySynced": false,
    "isGrafanaAdmin": true,
    "isGrafanaAdminExternallySynced": false,
    "login": "admin",
    "name": "",
    "orgId": 1,
    "theme": "",
    "uid": "u000000001",
    "updatedAt": "2024-01-05T12:11:48Z"
}</pre>
</details>

------------------------

Can you please take another look? cc @tonypowa

**Comment by ulidtko** [comment]
I'd also kindly ask to reopen; after checking the advice & the docs, my issue is not resolved.
