### ISSUE TITLE
Variable in "field from calculation"

### ISSUE THREAD

**Issue by KacThe** [grafana/grafana#84422]
### What happened?

Hey, I have a problem with performing binary operations with two variables. The operation executes successfully, but after refreshing the dashboard, it disappears because a new variable is created. Is there any way to bypass this?
![image](https://github.com/grafana/grafana/assets/154582387/01dc2b54-c5aa-45ac-8ab1-f520eeea62b4)
![Screenshot from 2024-03-14 08-05-06](https://github.com/grafana/grafana/assets/154582387/69bf0ff4-a2b3-4136-bc36-1fb250be9aa3)

my query A:

from(bucket: "search_jmeter_new_api")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "avg" or r["_field"] == "count" or r["_field"] == "error" or r["_field"] == "max" or r["_field"] == "min")
  |> filter(fn: (r) => r["symbol"] == "TOTAL")

        |> filter(fn: (r) =>  r["number"] == "2.171.0_B_466_2024-03-06")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  |> pivot(rowKey:["number","_measurement"], columnKey: ["_field"], valueColumn: "_value")

my query B:

from(bucket: "search_jmeter_new_api")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "avg" or r["_field"] == "count" or r["_field"] == "error" or r["_field"] == "max" or r["_field"] == "min")
  |> filter(fn: (r) => r["symbol"] == "TOTAL")

        |> filter(fn: (r) =>  r["number"] == "2.171.0_B_466_2024-03-06")
  |> group()
  |> sort(columns: ["_time"], desc: true)
  |> pivot(rowKey:["number","_measurement"], columnKey: ["_field"], valueColumn: "_value")
  |> rename(columns:  {count: "count_2", min: "min_2", max: "max_2", avg: "avg_2", error: "error_2"})

![image](https://github.com/grafana/grafana/assets/154582387/93f68f6f-b484-4ca9-8f0d-d28b1ea02397)

### What did you expect to happen?

Make it not disappear because I can't display variables.

### Did this work before?

It was working on grafana 7.4 

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 9.4.7
OS: Ubuntu 22
Browser: Chorme

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by KacThe** [comment]
resolved

**Comment by tonypowa** [comment]
hi @KacThe 

we are glad to hear you managed to resolve it by yourself

do you mind to share how you did it? It can potentially help other users that encounter the same issue

thank you!

**Comment by KacThe** [comment]
i needed change from |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
to
|> range(start: 2021-03-29T22:00:00Z, stop: 2030-03-29T22:00:00Z)
and grafana again can work with that

**Comment by tonypowa** [comment]
@KacThe , thanks for sharing your Grafana solution. Your contribution turned your issue into a community asset – thank you!
closing issue
