### ISSUE TITLE
[Bug] CloudWatch Datasource doesn't work via HTTP proxy

### ISSUE THREAD

**Issue by visit1985** [grafana/grafana#8443]
- What Grafana version are you using?
v4.2.0

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Ubuntu 16.04.2 LTS

- What did you do?
  - added http_proxy / https_proxy to `/etc/default/grafana-server`
  - restarted Grafana
  - created CloudWatch datasource with "Access & secret key" auth provider
  - Save and test says "Success: Data source is working"
    - Request Payload: `{"region":"eu-central-1","action":"ListMetrics","parameters":{"namespace":"AWS/Billing","metricName":"EstimatedCharges","dimensions":[]}}`
    - Response: `{"Metrics":null,"NextToken":null}`
  - tried to create a Graph using the Datasource

- What was the expected result?
  - to pick dimensions from a drop-down and get a graph displayed

- What happened instead?
  - the drop-down does not show any dimensions
  - there are no log entries for cloudwatch datasource, even with loglevel = trace
  - Request Payload: `{"region":"eu-central-1","action":"ListMetrics","parameters":{"namespace":"AWS/ELB","metricName":"Latency","dimensions":[]}}`
  - Response: `{"Metrics":null,"NextToken":null}`

**Comment by visit1985** [comment]
Same behavior in v4.3.0

**Comment by visit1985** [comment]
[This](https://gist.github.com/jakexks/2f876697dfca1fe15b92f7bb6032780d) might help fixing the issue. Looks like we need to define the `HTTPClient` property in `func getAwsConfig` when a proxy is present in the environment.

**Comment by torkelo** [comment]
we moved cloudwatch to backend in v4.5 so this issue should be resoved

**Comment by torkelo** [comment]
sorry misread this issue

**Comment by sunker** [comment]
@visit1985 are you still having the same issue?
