### ISSUE TITLE
Influx datasource for user with viewer permission error

### ISSUE THREAD

**Issue by psachs** [grafana/grafana#84459]
### What happened?

Since around 16h our influx 2.x datasource shows up a lot of errors.
Users with only viewer permission are not able to load data resulting in a data source error, while users with editor or admin permission everything still works fine.

We didn't change anything on our system

### What did you expect to happen?

Dashboards with InfluxDB datasource also works for users with Viewer permission

### Did this work before?

Yes before everything worked as expected

### How do we reproduce it?

1. Access a Dashboard with a user with viewer permission
2. See error message: "InfluxDB returned error:"
3.

### Is the bug inside a dashboard panel?
yes

### Environment (with versions)?

Grafana: Grafana v11.0.0-67977 (0e7c0d25fe)
OS: Ubuntu 22.04
Browser: Firefox and Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB 2.7

**Comment by tonypowa** [comment]
hello @psachs 

have you tried with other data sources? is this issue only occurring when using influxDB?

Is the issue occurring on a specific panel within the dashboard, or is it widespread across all panels that use the InfluxDB datasource? If it's a specific panel, sharing the query that the panel is using might give us some insights.

Can you check the logs for both InfluxDB and Grafana around the time the issue started? Look specifically for errors related to permissions or datasource access.

thank you!

**Comment by bohandley** [comment]
Hello @grafana/dashboards-squad! I believe this is related to [this escalation](https://github.com/grafana/support-escalations/issues/9722).

**Comment by oscarkilhed** [comment]
This issue was fixed in: https://github.com/grafana/grafana/pull/84975

I'll close this for now, let us know if the issue returns.
