### ISSUE TITLE
[Bug] "Unresponsive script" warning when graph scale set as log (base X)

### ISSUE THREAD

**Issue by christophe-r** [grafana/grafana#8446]
Hello,

- What Grafana version are you using?
4.3.0 (commit: d9c6f7a)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
I graphed an InfluxDB field into Grafana.
On this graph, I set the base as "log (base 2)":
Axes > Scale > log (base2).

- What was the expected result?
Manage points which are equals to 0.

- What happened instead?
Most of time, everything work because my points are > 0.
But if a point is equal to 0, my browser (Firefox, same on Chrome) shows "Unresponsive script".

This must be because :
Math.log2(0);
-Infinity

The problem is the same with other logarithmic bases (2, 10, 32, 1024).

Thank you for fixing.

**Comment by torkelo** [comment]
did you get this in grafana 4.2 or is this new for 4.3.0 ?

**Comment by christophe-r** [comment]
I have not tested on 4.2.
I noticed this after the 4.3 update.

**Comment by torkelo** [comment]
unable to replicate, can you replicate this on play.grafana.org?

**Comment by christophe-r** [comment]
1)
![image](https://cloud.githubusercontent.com/assets/6024172/26401124/9d1eaa46-4084-11e7-86dc-f9d2ae8ffbe9.png)
I added math(*0) to the query in order to simulate points which are equals to 0.


2)
After selecting "log (base2)", the browser starts lagging, and then the warning prompt appears:

![image](https://cloud.githubusercontent.com/assets/6024172/26401174/e150a20a-4084-11e7-89d8-07f2a54706f7.png)

**Comment by azhiltsov** [comment]
It did not happen on 4.2 for me, but on 4.3 it causing chrome to crash if the line contains only "0" values and the scale is log (base 10).  
Mozilla become very unresponsive.
Data source is carbonapi (https://github.com/go-graphite/carbonapi) if this matter.
This behavior is completely gone after changing to the linear scale, or roll back to the 4.2

**Comment by daniellee** [comment]
I can replicate it on play.grafana.org and locally. It crashes the Chrome tab and gets the unresponsive script error in Firefox. Guess it must be related to the log scale PR for showing very small values.
