### ISSUE TITLE
Importing graphite dashboards into grafana

### ISSUE THREAD

**Issue by m-messiah** [grafana/grafana#8447]
Same question as was in #976 but now seems latest Grafana missed that feature.

Is it possible at all? 

I have a lot of Graphite dashboards and don't even guess, how can I migrate them to Grafana.

Any ways?

**Comment by torkelo** [comment]
Install Grafana 3.0 and use the Grafana dashboard import feature (imports from graphite-web). The dashboard migration was very basic, only a few options from graphite-web was migrated and the layout was not the same.
