### ISSUE TITLE
[Feature request] timezone selection by using query string

### ISSUE THREAD

**Issue by pga23** [grafana/grafana#8448]
It would be nice to have possibility of choosing dashboard's timezone by using query string in the following (or similar) way:

**Local browser time (default):**
http://play.grafana.org/dashboard/db/big-dashboard
http://play.grafana.org/dashboard/db/big-dashboard?tz=local

**UTC timezone:**
http://play.grafana.org/dashboard/db/big-dashboard?tz=UTC

**Custom timezone (when it will be implemented):**
http://play.grafana.org/dashboard/db/big-dashboard?tz=Europe%2FWarsaw
http://play.grafana.org/dashboard/db/big-dashboard?tz=CET
http://play.grafana.org/dashboard/db/big-dashboard?tz=+02:00

I develop an web application with build-in Grafana dashboards and lack of timezone selector (at least between local and UTC) by using query string is very problematic to me.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
