### ISSUE TITLE
[Feature request] RPM package should include dependency on urw-fonts

### ISSUE THREAD

**Issue by austinbutler** [grafana/grafana#8451]
- What Grafana version are you using?
```
[vagrant@monitoring ~]$ grafana-server -v
Version 4.3.1 (commit: befc15c)
```
- What OS are you running grafana on?
```
[vagrant@monitoring ~]$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
```
- What did you do?
Tried to render a dashboard.
- What was the expected result?
Dashboard rendered, including text.
- What happened instead?
Dashboard rendered without text.
 
I see this pops up a lot on the issues here and the community site, and I was able to fix it very easily by installing the `urw-fonts` package. It seems it would be worthwhile to have that package as a dependency. At https://github.com/grafana/grafana/issues/6035#issuecomment-246903423 it seems to imply everything necessary should already be installed as dependencies of the RPM.

This isn't a huge deal for me, I've already worked around it, but it seems like a useful small change.

```
[vagrant@monitoring ~]$ sudo yum deplist grafana
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.scalabledns.com
 * extras: centos-distro.cavecreek.net
 * updates: mirrors.gigenet.com
package: grafana.x86_64 4.3.1-1
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-21.el7_3
  dependency: /sbin/service
   provider: initscripts.x86_64 9.49.37-1.el7_3.1
  dependency: fontconfig
   provider: fontconfig.x86_64 2.10.95-10.el7
   provider: fontconfig.i686 2.10.95-10.el7
```

**Comment by torkelo** [comment]
fixed yesterday, https://github.com/grafana/grafana/pull/8442
