### ISSUE TITLE
Can't find the "Trace to metrics" segment on the page of datasource tempo in Grafana

### ISSUE THREAD

**Issue by maxiaoyu123-coder** [grafana/grafana#84510]
**I can't find the "Trace to metrics" segment on the page of datasource tempo**

![grafana-tempo](https://github.com/grafana/tempo/assets/58209070/537d0917-4de2-4596-be43-4e4daa833715)

**Comment by joe-elliott** [comment]
Thanks for filing the issue, but this is a Grafana issue and not a Tempo one.

**Comment by joe-elliott** [comment]
Be patient :)

**Comment by fabrizio-grafana** [comment]
👋 @maxiaoyu123-coder Did you enable the `traceToMetrics` [feature toggle](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#experimental-feature-toggles)? It is required for Grafana `10.3.x`. That might explain why you don't see the mentioned section.

**Comment by maxiaoyu123-coder** [comment]
@fabrizio-grafana  Thanks for you reply. yes, I did but it seems not to work for me.
My grafana version is grafana:10.3.1 and I've enabled the feature toggle  `traceToMetrics` by adding an environment variable in grafana container:
![image](https://github.com/grafana/grafana/assets/58209070/6d2c1fd1-af43-4113-ac3f-0866fdfd8e24)

**Comment by maxiaoyu123-coder** [comment]
@fabrizio-grafana thank you very much, you save me！！
