### ISSUE TITLE
MySQL driver dependency is incorrect

### ISSUE THREAD

**Issue by TamalSaha** [grafana/grafana#8453]
In 4.3.0 release, vendor.json says 
```
		{
			"checksumSHA1": "42vkdsxNaLyPu+FktCzZ/8zsNSE=",
			"path": "github.com/go-sql-driver/mysql",
			"revision": "9dee4ca50b83acdf57a35fb9e6fb4be640afa2f3",
			"revisionTime": "2017-03-27T11:30:21Z"
		},
```

But that version of mysql drive has no constants like `mysql.FieldTypeNameTiny`. So, grafana will not build.
```
# github.com/grafana/grafana/pkg/tsdb/mysql
pkg/tsdb/mysql/mysql.go:187: undefined: mysql.FieldTypeNameTiny
pkg/tsdb/mysql/mysql.go:189: undefined: mysql.FieldTypeNameInt24
pkg/tsdb/mysql/mysql.go:191: undefined: mysql.FieldTypeNameShort
pkg/tsdb/mysql/mysql.go:193: undefined: mysql.FieldTypeNameVarString
pkg/tsdb/mysql/mysql.go:195: undefined: mysql.FieldTypeNameVarChar
pkg/tsdb/mysql/mysql.go:197: undefined: mysql.FieldTypeNameLong
pkg/tsdb/mysql/mysql.go:199: undefined: mysql.FieldTypeNameLongLong
pkg/tsdb/mysql/mysql.go:201: undefined: mysql.FieldTypeNameDouble
pkg/tsdb/mysql/mysql.go:203: undefined: mysql.FieldTypeNameDecimal
pkg/tsdb/mysql/mysql.go:205: undefined: mysql.FieldTypeNameNewDecimal
pkg/tsdb/mysql/mysql.go:205: too many errors
```

**Comment by torkelo** [comment]
strange, what version of Go are you building with? not getting any compile error locally nor on build server.

**Comment by torkelo** [comment]
those types are added by Us patching the vendored version (adding a file), https://github.com/grafana/grafana/blob/master/vendor/github.com/go-sql-driver/mysql/row_columntypes.go

This was required to get MySQL data source to work (so we can know what types are returned my mysql queries, something the official driver has yet to merge support for)

**Comment by TamalSaha** [comment]
Can you create a fork from the official driver and add that file and then add your forked version as dependency?

My issue is that we are trying to add some more dependencies for our setup of Grafana. And this is failing my build.

**Comment by torkelo** [comment]
I would prefer not to, as the official go mysql driver will soon merge support for column types.

Not sure why this is causing you issues, not failing on any other build system. Are you running govendor and refetching all vendorered files? 

This file https://github.com/grafana/grafana/blob/master/vendor/github.com/go-sql-driver/mysql/row_columntypes.go  is checked in, did you remove it?

**Comment by lprofession** [comment]
It issue happened to me when build up the source code, how to fix it?@tamalsaha

**Comment by tamalsaha** [comment]
I just used by fork https://github.com/appscode/mysql/pull/1

**Comment by lprofession** [comment]
yes, it fixed when used  appscode/mysql, but another issue as below ,have you met it before when built source? I wonder the dependences package of migrator are not correct.
github.com/grafana/grafana/pkg/services/sqlstore/migrator
# github.com/grafana/grafana/pkg/services/sqlstore/migrator
pkg/services/sqlstore/migrator/migrator.go:124:29: too many arguments in call to sess.Query
	have (string, []interface {}...)
	want (...interface {})
exit status 2
exit status 1
