### ISSUE TITLE
Select: When virtualised is true the items get's wrong top position 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#84542]
* Create a Select with a few options
* Select an option 3 options down
* Open the menu again, notice the empty space above and the top 2 options are not visible 

![Screenshot 2024-03-15 at 09 44 24](https://github.com/grafana/grafana/assets/10999/fd40fec8-ce4a-40f8-8f14-6db61aad6b2b)

https://github.com/grafana/grafana/assets/10999/953d749a-7b59-4aeb-9ea1-486e9d29ba13

Looks like it's caused by initialScrollOffset here:
https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Select/SelectMenu.tsx#L71

It is fixed If I remove that line, maybe bug in react-window?

**Comment by eledobleefe** [comment]
Hi @torkelo, correct me if I'm wrong, but didn't your [PR](https://github.com/grafana/grafana/pull/84544) fix this issue? Should we close it as done? 🤔

**Comment by torkelo** [comment]
@eledobleefe yes, we can close this
