### ISSUE TITLE
Removing a panel from a row duplicates row actions

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#84567]
To repro:

- Create a new panel
- Create a new row
- Remove the panel
- Row glitches out

After this, trying to save the dashboard crashes with the error in image
<img width="530" alt="Screenshot 2024-03-15 at 13 06 58" src="https://github.com/grafana/grafana/assets/74534993/12d110c7-d632-447d-bd5d-17485f9fe7f7">

**Comment by mdvictor** [comment]
I think this is related to https://github.com/grafana/grafana/issues/84194 which was fixed. I tested the repro steps, no row glitching out anymore and saving the dashboard doesn't crash it, so I think this can be closed.
