### ISSUE TITLE
[Bug] Incorrect e-mail graph captions

### ISSUE THREAD

**Issue by PSmetrics** [grafana/grafana#8456]
What Grafana version are you using?
grafana-4.2.0-1.x86_64
What datasource are you using?
InfluxDB
What OS are you running grafana on?
RHEL6.8
What did you do?
Create alert and receive email with graph screenschot.
What was the expected result?
I received a letter with a graph
What happened instead?
Graph has incorrect displaying of captions:
![screen](https://cloud.githubusercontent.com/assets/27350828/26396996/87c12d06-407d-11e7-88fc-609ceb374327.png)

**Comment by torkelo** [comment]
try:

```
yum install fontconfig
yum install freetype*
yum install urw-fonts
```

This will be done automatically starting from > 4.4

**Comment by PSmetrics** [comment]
Thank you!
