### ISSUE TITLE
Bug: Public dashboard tag is missing in the nav bar when a dashboard has been shared as a public dashboard

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#84566]
We are missing the "public" tag 

![image](https://github.com/grafana/grafana/assets/239999/7dbd9f0f-bfa4-4643-8815-8efa1e1b90db)

**Comment by torkelo** [comment]
I think this a very good chance, the public dashboard tag is there as a warning so editors know it's public dashboard, we should have this warning in the save dialog instead

**Comment by axelavargas** [comment]
@torkelo After discussing with the sharing squad, we agreed we will keep the badge, as it is intended to let all users know that the dashboard is being “public” (the tag implies it can be viewed by anyone with the URL)

**Comment by torkelo** [comment]
@axelavargas but why is this useful information for other viewers? It's only relevant when editing / making changes.

**Comment by axelavargas** [comment]
@torkelo, I get where you're coming from. At first glance, it may seem like the "public" badge is more relevant for editors, but after giving it some thought, I realized that it has other benefits regarding data security awareness. For example, if viewers use dashboards for meetings or discussions inside or outside the organization, marking a dashboard as "public" indicates that the information shown is not sensitive and can be shared widely. Moreover, if a public dashboard displays sensitive data, anyone from the organization can raise their hand and fix the problem.

Also, removing the badge could create inconsistency in user experience. If only editors or admins are aware of the public status, it means that all roles will perceive and use the dashboard information differently.

That's my take on it 😄 . But, the best team to answer why the badge exists is probably @grafana/sharing-squad 😄. For now, I will implement the current behavior, as we aim to complete M2 bugs before next week.

**Comment by natydej** [comment]
As @axelavargas said, the **"public"** badge is useful for other viewers because it clarifies the dashboard's accessibility level, informing them whether the data they're viewing is publicly accessible or not _(since anyone with the link can view that dashboard)_. Also, for new users, the `badge` helps as a visual cue about the dashboard's accessibility and promotes transparency in data sharing practices.
