### ISSUE TITLE
Dashboard data source: Sometimes the selected panel data is not loaded

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#84575]
See attached dashboard for repro:

- Add new panel to https://dev.grafana-dev.net/d/cdfjv9izbwj5sb/victor-s-dashboard-copy
- Select Dashboard data source
- Pick source panel 
- Panel will be in a loading state infinitely.

**Comment by mdvictor** [comment]
I managed to repro this consistently when the source panel is not saved, e.g.:
- Create a new dashboard
- Create a new source panel
- Create another panel and set DS to be Dashboard with that panel as source
- Reproduces consistently
