### ISSUE TITLE
Dashboard Scene: Slow template variable query doesn't show loading indicators in Panels

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#84574]
On a slowly loading dashboard (due to slow template variable query), panels do not get loading indicators until variables are loaded. This creates a sense of a broken dashboard.

#### Note: This behavior is also present in the current architecture, therefore it's an improvement and not part of the bug bash

**Comment by Sergej-Vlasov** [comment]
After quick investigation even with slow 3G the gap before loading bar is shown is barely noticeable. Probably worth to deprioritise until we can replicate again.
Example dashboards: 

- Panel tests - Slow Queries & Annotations (local gdev)
- https://dev.grafana-dev.net/d/edeceqvqy1vk0c/billing-usage?var-org_slug=raintank&var-org_id=1&var-metrics_id=$__all&var-logs_id=$__all&var-traces_id=$__all&var-grafana_id=$__all&var-profiles_id=$__all

**Comment by axelavargas** [comment]
I managed to reproduce the issue, indeed we are only showing the loading indicator in the panel after the variable is resolved, this behavior is also present in the current architecture, and it's related to the `PanelChrome` component, we are only showing the loading indicator when data is being fetched, not when we have dependencies with variables.

https://github.com/grafana/grafana/assets/239999/12098840-c126-46ff-b83d-11bd19b2bb05
