### ISSUE TITLE
[Bug] : Error tooltip is partially hidden

### ISSUE THREAD

**Issue by anton-arsentyev** [grafana/grafana#8457]
Please include this information:
- What Grafana version are you using?
v4.2.0

Error tooltip is partially hidden: 

![screen shot 2017-05-24 at 11 17 47 2](https://cloud.githubusercontent.com/assets/22887126/26399899/f3e0f4a2-407e-11e7-8226-66c2d5bd0d33.png)

**Comment by torkelo** [comment]
fixed in v4.3 :)
