### ISSUE TITLE
Prometheus: Improve Code Mode performance by truncating autocomplete results

### ISSUE THREAD

**Issue by NWRichmond** [grafana/grafana#84600]
**Why is this needed**:

When a Prometheus instance has an enormous number of unique metric names (on the order of many hundreds of thousands, or millions), it takes a long time (single to double-digit seconds) to load metric names to power the autocomplete experience in [Code Mode](https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#code-mode). Rendering such a large volume of label names in the Monaco editor can freeze the UI.

**What would you like to be added**:

- Determine the approximate number of unique metric names that can be loaded in, say, <300ms
- When the number of unique metric names exceeds that number:
  - Truncate the list of unique metric names that are used to power the Code Mode autocomplete feature
  - Display a warning in the UI that there are too many results to support autocomplete

**Who is this feature for?**

Prometheus data source users, especially those with hundreds of thousands to millions of unique metric names.

**Comment by danstadler-pdx** [comment]
for "Display a warning in the UI that there are too many results to support autocomplete" - anything we can add to the messaging that helps the user (or their admin) go figure out their naming issues would be very helpful.

For example, we could suggest queries they could run, like 
group ({cluster="my_cluster"}) by (__name__)

**Comment by NWRichmond** [comment]
This will likely be closed next week in favor of https://github.com/grafana/grafana/issues/84612.
