### ISSUE TITLE
Canvas: Connections without a target behave unexpectedly during resize

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#84604]
During resize of panel, since connections without targets are positioned by relative percent, instead of absolutely, unexpected positioning can occur, especially when navigating from panel edit to panel view.

https://github.com/grafana/grafana/assets/60050885/88a104a3-80fe-496b-80f6-8f500110fa4d

**Comment by nmarrs** [comment]
This behavior is actually expected as the connections are anchored relative to the panel dimensions on a relative coordinate system (-1,-1, bottom left corner, to 1, 1 top right corner). When panel is resized the relative coordinates result in different positioning of the ends of the connection lines 😬

**Comment by nmarrs** [comment]
Given this is expected behavior based on the current layout system I am closing this issue.
