### ISSUE TITLE
Submit worldping API key from command line

### ISSUE THREAD

**Issue by hgibson1** [grafana/grafana#8461]
I'm building a grafana docker image which needs to include installing and enabling the worldping app. According to the documentation it's possible to install worldping through the grafana CLI, but it has to be enabled through the GUI. Is there a way to enable world ping through the CLI with a given API key? 

Alternatively, is there a way to enable the worldping app using cURL? I've tried curl --data "API_KEY" -u admin:PASSWORD" http://localhost:3000/plugins/raintank-worldping-app/edit and keep getting 404 errors (curl get requests return status 200).

**Comment by torkelo** [comment]
when you enable it via the UI, have chrome dev tools > network tab open (and preserve option checked), then you can see what api calls are made when you enable the plugin
