### ISSUE TITLE
[Bug] Display issue with staircase mode on

### ISSUE THREAD

**Issue by nicolargo** [grafana/grafana#8462]
Hi all, first of all thanks for this awesome software.

when i use Grafana to display my sensors data, the staircase option did not work as expected.

Here is my graph without the staircase option:

![2017-05-24 17_02_56-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26410654/378ee2b6-40a4-11e7-851b-253b730278df.png)

and with (note that the Null value is set to null):

![2017-05-24 17_03_11-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26410777/817659c2-40a4-11e7-93fd-94b0c31c61b4.png)

As you can see, when there is an hole in the data source, the staircase option draws an unexpected line with a 0 value.

![2017-05-24 17_16_29-d__users_hennionn_pictures_captures_2017-05-24 17_03_11-grafana - agyr png - gre](https://cloud.githubusercontent.com/assets/776747/26410962/f989d1a0-40a4-11e7-9f68-350cc101636d.png)

I think that the straircase option should draw a horizontal line between the current point and the n-1 point only if this one exist (!= Null). 

Additional information:
- What Grafana version are you using? 4.2.0 (also tested with 4.2.3 beta1)
- What datasource are you using? InfluxDB 1.2.2
- What OS are you running grafana on? CentOS 7.3

**Comment by torkelo** [comment]
what's your fill() option in your influxdb query? What's the response from influxdb?

**Comment by nicolargo** [comment]
Hi @torkelo,

The fill option of the influx request is set to none. 
No 0 value in the InfluxDB response...

**Comment by torkelo** [comment]
try setting fill to fill(null)

**Comment by nicolargo** [comment]
Much better:

![2017-05-29 18_12_33-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26556453/dc7c47c4-449a-11e7-98ea-b0e964de7436.png)

but... the hole are filled with previous value, not null...

![2017-05-29 18_13_07-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26556491/12404ea0-449b-11e7-93be-2389da9f2163.png)

**Comment by torkelo** [comment]
What is your display option null value set to (display tab)?

**Comment by nicolargo** [comment]
"Null value" is set to "null" in the display panel.

**Comment by torkelo** [comment]
Can you show the response (raw response) from your influxdb query?

**Comment by nicolargo** [comment]
For the following graph:

![2017-05-30 15_33_53-grafana - agyr - chromium portable](https://cloud.githubusercontent.com/assets/776747/26585866/baaa7aae-454d-11e7-82fe-72e2a6537b19.png)

Here is the RAW response from the InfluxDB database:

[raw.txt](https://github.com/grafana/grafana/files/1038476/raw.txt)

**Comment by torkelo** [comment]
I cannot see any null values in the response. Sure you have fill(null) in your InfluxDB query?

**Comment by nicolargo** [comment]
Sorry, miss understand, the request of the previous graph use the fill(none) option. If if set it to fill(null), i have the following (with the stair starting at 0):

![2017-06-01 09_54_44-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26670053/7124d1e0-46b0-11e7-9088-909a8086cabf.png)

**Comment by torkelo** [comment]
ok, looks ok. So no bug in Grafana then? Or did you forget to include the raw response from InfluxDB that resulted int the above graph?

What I am do to with the above graph? why did you post it without describing what data you have and what you think is wrong?

**Comment by nicolargo** [comment]
@torkelo let's return to my first post.

I have the following graph:

![2017-06-01 09_54_44-grafana - agyr](https://cloud.githubusercontent.com/assets/776747/26678940/3f402d0a-46d3-11e7-8acb-e557eb0aef33.png)

with the relative RAW response from InfluxDB: 

[raw.txt](https://github.com/grafana/grafana/files/1044648/raw.txt)

The metric request is (fill(null)):

    SELECT mode("eng") FROM /^$tm$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)

and the display option is display null option value is set to null.

As you can see, when there is an hole in the data source, the staircase option draws an unexpected line with a 0 value.

**Comment by torkelo** [comment]
Did you look at the raw data? 

It includes the zeros you see in the graph. 

```
[1464689520000,  0]
```

**Comment by nicolargo** [comment]
@torkelo sure i have a look on it... There is 3 zeros because the curve crosses the Y axe 3 times...

![2017-06-02 09_30_16-grafana - agyr - chromium portable](https://cloud.githubusercontent.com/assets/776747/26715483/30dec098-4776-11e7-8a71-806b6f619a0b.png)

but there is no zeros here...

![2017-06-02 09_31_40-grafana - agyr - chromium portable](https://cloud.githubusercontent.com/assets/776747/26715545/6288f3de-4776-11e7-967f-cfc83b879820.png)

So why Grafana draws thoses lines ?

**Comment by nicolargo** [comment]
@torkelo Do you need anothers informations ?

**Comment by nicolargo** [comment]
update ?

**Comment by torkelo** [comment]
manged to replace the issue. Seem after null value, a line is drawn from zero.

**Comment by torkelo** [comment]
closing this as it's an edge case that seems to not affect that many
