### ISSUE TITLE
[Feature request] Turn off "OK" notifications

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#8463]
Please add the ability to turn off "OK" notifications. Sometimes too much notifications distracting in slack.

[Feature request]. 

- What Grafana version are you using? 4.2.0
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubunty
- What did you do? Slack alerts and notifications
- What was the expected result? 
**Please add the ability to turn off "OK" notifications. Sometimes too much notifications distracting in slack.** 
- What happened instead? N/A
- If related to metric query / data viz: N/A

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/6696

**Comment by TomasJavurek** [comment]
Same problem.
