### ISSUE TITLE
Alert features

### ISSUE THREAD

**Issue by kotarusv** [grafana/grafana#8465]
Just saw the release notes of Grafana 4.3.  Overall it is a great release but little disappointed in terms of missing long waited alerting features.

I would like to have support of 

 - Support setting up alerts on aggregated graph. I can setup alerts currently on aggregated graphs but subject line doesn't show up from which host alert got triggered or having issue. Due to this limitation, i had to setup thousand of alerts on graph by graph basic where alert name clearely indicate which host.  if tag_hostname supported in alias name in alert config, it helps us from which alert got triggered in aggregated graph situation and greatly help time/effort/frustration to build single graphs host by host basis

- It would nice to disable alerts by graph by graph or global channel level for time being rather removing and adding email alias whenever we don't' want to send notifications, particularly situations like patching, planned maintenance, or  some issue with data collection layer or data base level ( InfluxDB) where Grafana thinks data not coming up thus start triggering emails. 

- Some kind of analysis report to shows whether inbuild sqlite database is reaching its scale limits or not? How many queries or data sqlite can support ? What is the current size in terms of schema information? We're  happy with build in database in terms of performance and stability but never know when we reaching limits due to sqlite limits. 

- When we duplicate a graph, it is not copying alert panel. Since am setting up multiple alert graphs due to limitation of aggregated graph notification, I merely want to change hostname in the query. Now i had to again create the alert panel although i duplicated the graph and setup alert config from scratch. Due to this limitation of alert tab not duplicating, i  had to export panel to json and modify as per needs and paste into duplicated panen json source panel.

- Can we also duplicate entire row ? i had multiple use cases where 2nd row is pretty much same as 1st row except i had to change few tags or values in query columns. it would greatly help to build the 2nd row from scratch just for few changes. 
- Can we export individual rows? I experienced this need multiple times while building my dashboards. i want to export individual rows from dashboard A and import into Dashboard B with minor changes. Due to this limitation, I had to export panel by panel and import after minor modifications. 

- Can we have table support with multiple fields as multiple columns? I am sure it would be possible and I failed literally to build. Take an example, i want to have a table with load 1/5/15 minutes and group by hostname. I tried table panel with rows and columns options  but nothing working as expected. i want first column is hostname, and 2 column is 1 min load, 3 columns is 5 mins load and last colukn is 15 m load. Think about a simple excel sheet by

hostname     1m    5m 15m 
host1              value value value
host2              value value value 

I felt these are very important missing features while i had been working with Grafana last weeks. I am pretty much happy and satisfied with Grafana/Telegraf/InfluxDB combination. I'm eagerly waiting some improvements on alert side as I don't want to use/investor another tool for just alerting as Grafana is perfectly matching my needs of Visualization and Alerting

**Comment by torkelo** [comment]
Thanks for the feedback, we hope to improve alerting going forward

Please search for existing feature requests and add a reaction to it to vote for the feature, for general comment feedback please use community site
