### ISSUE TITLE
[Bug] Unable to change datasource when using -- Mixed -- Data Source

### ISSUE THREAD

**Issue by checketts** [grafana/grafana#8466]
Using  Grafana v4.3.1 (commit: befc15c) 
Running via Docker in Kubernetes with Prometheus datasources.

# What did you do?
After upgrading to Grafana 4.3.1, I am unable to change the DataSource when using `-- Mixed --` datasources.

![image](https://cloud.githubusercontent.com/assets/416063/26455944/dc4b0e2c-4128-11e7-90cc-ea87c20ef4e5.png)

# What was the expected result?
Before if I needed to change the datasource I could click the datasource name as listed on the left (dev1 harbor2 in the screenshot above). It would give me a drop down and I could switch the datasource.

# What happened instead?
 After the upgrade clicking merely toggle edit mode.

**Comment by torkelo** [comment]
This has always been the case, in mixed mode you decide what datasource each query target when you add the query, you must be remembering wrongly :)

**Comment by checketts** [comment]
You are correct. My apologies. This brain of mine, it has a mind of its own sometimes.
