### ISSUE TITLE
[Bug] Table panel broken with Elasticsearch 2.x datasource

### ISSUE THREAD

**Issue by goldeelox** [grafana/grafana#8467]
- What Grafana version are you using?
  - 4.3.1
- What datasource are you using?
  - Elasticsearch 2.x
- What OS are you running grafana on?
  - Linux
- What did you do?
  - After upgrading to Grafana 4.3.x, the table panel no longer works with an Elasticsearch 2.x datasource. Appears that pull request #8317 is the cause.
<img width="1077" alt="screen shot 2017-05-25 at 11 24 24 am" src="https://cloud.githubusercontent.com/assets/1199770/26457439/18fb9214-413e-11e7-9123-42d3b62b3ac8.png">

**Comment by louzadod** [comment]
This bug sill happens on version 4.3.2. ElasticSearch 2.3.3

**Comment by goldeelox** [comment]
@louzadod Can you share a screenshot of the error? I tested on ES 2.3.3.

**Comment by louzadod** [comment]
The problem was on my side. My index templates were wrong. Field "@timestamp" was with "doc_value" set to "false". I changed it and now it is working. Thanks.
