### ISSUE TITLE
Alerting: Dry-run upgrade runs even when alerting is not enabled

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#84695]
### What happened?

Starting Grafana with alerting disabled causes a dry-run upgrade to occur every time the server starts.

In my use-case (a multitenant server with lots of organizations), this adds 20 seconds to every startup:

```json
{"level":"info","logger":"ngalert.migration","msg":"Starting","t":"2024-03-18T20:09:43.292096948Z"}
{"cleanOnUpgrade":false,"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Dry-running upgrade. To deactivate on-start dry-run, disable the feature flag 'alertingUpgradeDryrunOnStart'","t":"2024-03-18T20:09:43.292358965Z"}
{"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Migrating alerts for organisation","orgID":1,"t":"2024-03-18T20:09:43.618541522Z"}
{"alerts":0,"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Alerts found to migrate","orgID":1,"t":"2024-03-18T20:09:43.619070926Z"}
{"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Migrating alerts for organisation","orgID":4,"t":"2024-03-18T20:09:43.619848163Z"}
{"alerts":0,"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Alerts found to migrate","orgID":4,"t":"2024-03-18T20:09:43.62000972Z"}

{"dryrun":"true","level":"info","logger":"ngalert.migration","msg":"Dry-run upgrade succeeded. No changes were made. Current legacy alerting setup is ready to upgrade.","t":"2024-03-18T20:10:03.190148144Z"}
```

This behavior can be disabled by setting the `alertingUpgradeDryrunOnStart` feature flag to false. I think it should be automatically disabled when both legacy and unified alerting are disabled.

### What did you expect to happen?

With both legacy and unified alerting disabled in config, I would expect no alerting dry-run upgrade to run (or any alerting components for that matter such as 'MultiOrg Alertmanager', but that's less important as it significantly impact server startup).

### Did this work before?

Yes, before the automatic dry-run upgrade was added (in 10.4.0 with #82835, I believe).

### How do we reproduce it?

1. Set the following config in `grafana.ini` to disable alerting:
   ```ini
   [alerting]
   enabled = false

   [unified_alerting]
   enabled = false

   ```
2. Start Grafana, see dry-run upgrade and other alert-related messages in logs.

### Environment (with versions)?

Grafana: [v10.4.x](https://github.com/grafana/grafana/commits/v10.4.x/) branch (commit de5b7712)
OS: ubuntu
Browser: Chrome

### Grafana platform?

Other

**Comment by KaplanSarah** [comment]
As you mention, there is a feature flag to disable this functionality.  The reason the migration still runs is that this is the last version with legacy alerting.  While this is not optimal, it is expected behavior.  Once you upgrade to Grafana 11 this will go away.
