### ISSUE TITLE
[BUG] Dashed lines with a width > 1 turn into solid lines

### ISSUE THREAD

**Issue by checketts** [grafana/grafana#8469]
# What Grafana version are you using?
Grafana 3.4.1, running via Docker on Kubernetes with Prometheus Datasources

# What did you do?
I set a line to `dashed: true` and increased its width

# What was the expected result?
I expected the line to be thicker, but remain dashed

Width still at 1:
![image](https://cloud.githubusercontent.com/assets/416063/26462253/404863c0-413d-11e7-8801-d0865ac63d50.png)

# What happened instead?
The line turned solid when line width is set to greater than 1:
![image](https://cloud.githubusercontent.com/assets/416063/26462322/81eca886-413d-11e7-8b59-7d13878320e6.png)

**Comment by daniellee** [comment]
Committed a fix to master. Will be included in the 4.4.0 release.
