### ISSUE TITLE
[Feature request] Tool tip for alert heart types in panel titles

### ISSUE THREAD

**Issue by jsha** [grafana/grafana#8471]
When a panel has an alert present, it gets a a little heart icon: grey, green, or red. The meaning of each of these colors is not immediately clear. It would be nice to have a tool tip when hovering on the heart that explains what it's for, and what it indicates. E.g. "Alert status: ok", "Alert status: alerting"

**Comment by wenjie711** [comment]
hi, could you tell me what does grey heart mean?

**Comment by tonidas** [comment]
Thats a cool feature request!

Red means Alerting State.
Green means OK State.
Orange means Pending State.
Grey means that the Alert is not being verified for some reason. If there is no data, for instance.
