### ISSUE TITLE
[Feature request] "real" auto elasticsearch date_histogram interval 

### ISSUE THREAD

**Issue by tianzk** [grafana/grafana#8476]
- What Grafana version are you using?
4.3-beta
- What datasource are you using?
Elasticsearch
- What OS are you running grafana on?
OSX
- What did you do?
1、Set query group by date historgram with **"auto"** interval
![image](https://cloud.githubusercontent.com/assets/6689676/26488611/ae3ae408-4236-11e7-8c0b-c9957500ea75.png)

2、Change date range of a dashboard（select a short duration）
![image](https://cloud.githubusercontent.com/assets/6689676/26488659/deaad670-4236-11e7-9d6b-513486e564b2.png)

- What was the expected result?
Graph's date_histogram interval change to fit the date reange.(eg:auto decrease interval)
- What happened instead?
The interval just stay in the same with "Default Group by time interval" or global "Group by time interval" setting.

I think the behaviour of grafana  is not worth the meaning of **"auto"**.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
? auto means the it changes depending on time range and panel width. 

You can control the auto behavior by setting a lower limit (or a fixed limit) ion the Panel group by time or data source group by time option. 

To set a lower limit of auto specify `>10s' in your group by time option. ( for example),. If you set a fixed value you override the auto behavior.
