### ISSUE TITLE
Aggregation: When using a Stacked Bar Chart data does not aggregate daily.

### ISSUE THREAD

**Issue by LifHkr** [grafana/grafana#84780]
### What happened?

A Stacked Bar Chart will not aggregate to 1 hour intervals even when the Min Interval and Min Step are both set a 1 Day. No interval overrides are included in the query.

### What did you expect to happen?

When Aggregating at a daily level I should get one bar per day. I am still getting a bar for every 5 minute interval.

### Did this work before?

It works as expected with smaller data sets but fails on larger production levels.

### How do we reproduce it?

1.Created a stacked bar chart
2.Set the Min Interval 1d
3.Set the Min Step to 1d
4. Verify that we get 1 single stacked bar per hour

### Environment (with versions)?

Grafana: 9.5.6
OS:Windows
Browser:FireFox

### Grafana platform?

I don't know

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
Hi @LifHkr 
Thank you for creating this issue

**Comment by LifHkr** [comment]
When we upgraded from 9.5.14 to 9.5.16 the problem went away. I do not know if it was related to the Grafana update or if something changed in the data source but the issue has been resolved.
