### ISSUE TITLE
fail to get render panel image with valid admin role service account token

### ISSUE THREAD

**Issue by bossjie** [grafana/grafana#84797]
### What happened?

I have admin role service account token,I have a script run as webhook service to receive alert from grafana.
as webhook way could send alert with image, with help of image render. it was working before 9.4.7, using apikey.
after grafana 10.x, it forces to migrate to service account and token to integrate with grafana. 
my cmd run  like below, 
curl -H 'Authorization: Bearer glsa_abcd_15de8a1b' 'https://abc.com/render/d-solo/NtNdgVOSk?panelId=4' > test34.png
result:
![image](https://github.com/grafana/grafana/assets/8426828/d032839d-e774-4188-af61-58a3c2ed8854)

while using same token, I could create dashboard via below post. 
tips:  the image render works when I click the rendered image link
![image](https://github.com/grafana/grafana/assets/8426828/fc09ff3e-92b5-4ac9-96e8-3fcd2cb8789d)

curl -X POST --insecure -H "Authorization: Bearer glsa_aaaaa_37aa44a6" -H "Content-Type: application/json" -d '{
  "dashboard": {
    "id": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "rows": [
      {
      }
    ],
    "schemaVersion": 6,
    "version": 0
  },
  "overwrite": false
}' https://abc.com/api/dashboards/db

### What did you expect to happen?

download the rendered image with panel content, not the error.

### Did this work before?

yes, on 9.4.7, now we are on 10.3 & 10.4

### How do we reproduce it?

1. install image render(https://github.com/grafana/grafana-image-renderer)
draw a panel with a time series chart  and click share to check rendered image on browser like above pic 2 ==> to validate the image render works.
2. run below cmd with an admin service account token(create by admin, goto service account tab), replace below token and grafana url, 
NtNdgVOSk and panelId could be found on step1
curl -H 'Authorization: Bearer glsa_abcd_15de8a1b' 'https://abc.com/render/d-solo/NtNdgVOSk?panelId=4' > test34.png

3. check the png file, whether it's an error or normal panel content

### Is the bug inside a dashboard panel?

no, looks like grafana block an entry

### Environment (with versions)?

Grafana: 10.4
OS: ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

any

**Comment by bossjie** [comment]
update per deep testing.
multiple versions succeed with docker deploy mode.
but in kubernates, it failes with pic shows, token invalid while the token is ok to operate rest APIs like create dashboard.
we turn off the istio, checking the debug logs and still no clue on it.   
Hope we could learn some guides from community side   cc @AgnesToulet

**Comment by evictorero** [comment]
I can't reproduce it following the provided steps, it works as expected.
If this is something related to a more complex configuration can you provide the simplest way to reproduce it?

**Comment by bossjie** [comment]
@evictorero  thanks for checking this issue.
as I said, it works with docker images & in centos
but not in kubernates env.   do you mean you made it in kubernates?

**Comment by evictorero** [comment]
I'm trying to reproduce it directly. If it only happens in a specific platform or configuration, then it could be related to it. Can you isolate where the problem is? If the token is invalid ONLY through Kubernetes, I assume the Authentication header is not being delivered correctly.

**Comment by bossjie** [comment]
@evictorero  it is resolved.  RC: caused by our customized code which leads a force logout in 10.2(worked in 9.4.7)
we remove that part then it works.  thanks.   everything is green now.
