### ISSUE TITLE
Can't find the "Trace to Profiles" segment on the page of datasource tempo in Grafana

### ISSUE THREAD

**Issue by maxiaoyu123-coder** [grafana/grafana#84791]
I configured  according to this document 
https://grafana.com/docs/pyroscope/latest/configure-client/trace-span-profiles/java-span-profiles/

**Expected Result**
there should be a section on tempo datasource like this 
![image](https://github.com/grafana/grafana/assets/58209070/4f5137ec-5d67-42c1-8f72-90779c76b28e)

**Actual Result**:
unable to find the "Trace to Profiles" segment on the page of datasource tempo in Grafana.
![image](https://github.com/grafana/grafana/assets/58209070/0fbecda7-4ea7-4438-a5a9-932d36465278)

**Environment**:
grafana version is 10.3.1
tempo version is latest
pyroscope version 1.4.0

**Comment by fabrizio-grafana** [comment]
Hey @maxiaoyu123-coder!

I see you are using version `10.3` of Grafana. This version should still have the `traceToProfiles` feature flag, removed in version `10.4`, which controls whether the "Trace to Profiles" section in the settings is visible or not. [More info here](https://grafana.com/docs/grafana/v10.3/setup-grafana/configure-grafana/feature-toggles/#experimental-feature-toggles). 
Did you set that feature flag? If not, that could explain why you don't see the "Trace to Profiles" section.

**Comment by fabrizio-grafana** [comment]
Closing as stale.
