### ISSUE TITLE
Dashboard Variables: Unable to get tags for linked accounts

### ISSUE THREAD

**Issue by langarano** [grafana/grafana#84805]
### What happened?

I would like to create a variable with the tags for the EC2 in the linked accounts. However, after selecting as Query type "EC2 Instance Attributes", I can select the Region, but not the Account, as for the query type "Dimension Values", for example.
![e2c9edf6-6c6f-45ab-ad4a-acbf2220f1b9](https://github.com/grafana/grafana/assets/164167610/f87d6d49-a414-4b7c-9a48-694b60ee4690)

### What did you expect to happen?

I would expect the possibility to select the Account right after the Region.
![54954dff-1447-4e9c-9143-6e433a81553c](https://github.com/grafana/grafana/assets/164167610/7e739739-c831-4fc8-ac2a-8a28eaaaad67)

### Did this work before?

I am using Grafana v9.4.7, I do not know if it worked with previous versions.

### How do we reproduce it?

1. Create a New Variable for a Dashboard
2. Select EC2 Instance Attributes as Query type
3. After choosing the Region, we should be able to select the account, as it happens for Dimension Values.

### Environment (with versions)?

Grafana: Grafana v9.4.7
OS: AWS Grafana Managed

### Grafana platform?

Other

### Datasource(s)?

CloudWatch

**Comment by sarahzinger** [comment]
Hi @langarano great question! I believe this is currently possible, although it is not very obvious. 

We use the aws-sdk to fetch this data and specifically do so using [this describeInstancesPages](EC2.DescribeInstancesPagesWithContext) function, which can take a number of filters that you can add in the field below.

In [reading the expected input](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#DescribeInstancesInput) and shape of those filters, I see this `owner-id - The Amazon Web Services account ID of the instance owner.` it looks to me like it is possible therefore to pass in a filter of `owner-id` and the value of the account ids you want and it should filter out the tags you are looking for. 

Let me know if that works for you!
