### ISSUE TITLE
[Bug] Dashboard.json as configuration group name unusable from ENV

### ISSUE THREAD

**Issue by salanki** [grafana/grafana#8482]
The configuration for generated dashboards is under config section `[dashboard.json]`. When setting Grafana config via environment variables, as is popular in a Docker deployment it is impossible to set the dashboard path as environment variables can't contain `.`.

Suggestion: Remove the `.` from the config section name, maintain an alias for backwards compatibility.

**Comment by torkelo** [comment]
Use underscore in place of dots when setting option via ENV vars

**Comment by salanki** [comment]
Ok, thank you. Did I just miss this in the documentation or should it be documented?

**Comment by torkelo** [comment]
It is mentioned in the docs in the section on how to set config options using  environment variables
