### ISSUE TITLE
Error while using multiple variable in Grafana

### ISSUE THREAD

**Issue by DemPago** [grafana/grafana#84838]
### What happened?

"When using Grafana, I am making a JQL query on Azure Monitor as a data source, and when I select 'multi-value,' the query does not return any values."
This is the query:
| where Nome_ente contains  ("$Name") or "$Name" contains_cs  "All" 

Here the date about **Name**
$Name is a query variable.
<img width="374" alt="image" src="https://github.com/grafana/grafana/assets/125261604/2c41a395-ab4e-4a8b-ad92-0fcebf37cb92">

It's something wrong?

### What did you expect to happen?

"I would like to visualize a multi-value query."

### Did this work before?

Never

### How do we reproduce it?

1. Use Azure Monitor as Data Source
2.| use a query like this  where Nome_ente contains  ("$Name") or "$Name" contains_cs  "All" 

3. Set multi value on the variable

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: ver 10
OS: Mac OS Sonoma
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Azure Monitor

**Comment by aangelisc** [comment]
Hi @DemPago, thank you for opening this issue. To confirm:
- Do you see data when selecting a single value for the multi-value template variable?
- Do you see data when you select the `All` option?

**Comment by DemPago** [comment]
I see data with one value or all but not with multiple value

Il mer 17 apr 2024, 21:38 Andreas Christou ***@***.***> ha
scritto:

**Comment by bossinc** [comment]
@DemPago The `contains` operator does not work with a list of values. https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/contains-operator

I think you are looking for the `in` operator. https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/in-cs-operator

**Comment by DemPago** [comment]
Thanks but doesent work the in operator.

Il mar 7 mag 2024, 00:37 Andrew Hackmann ***@***.***> ha
scritto:

**Comment by bossinc** [comment]
@DemPago What do you expect the query to look like after executing the template variables?

`| where Nome_ente contains ("name1", "name2") ` is not valid KQL. `contains` expects only 1 value.

**Comment by bossinc** [comment]
I am closing this issue for now. Let me know if you have more questions or if this wasn't resolved.

**Comment by DemPago** [comment]
Hi Andrew the problem is up & running.
From a kusto query is impossibile to use the multi selection on a variable.

Il mer 29 mag 2024, 03:20 Andrew Hackmann ***@***.***> ha
scritto:
