### ISSUE TITLE
Canvas: New SVG elements don't support background image position

### ISSUE THREAD

**Issue by Develer** [grafana/grafana#84843]
New SVG elements don't react to `Image size` changes.

<img width="575" alt="Screenshot 2024-03-20 at 17 17 32" src="https://github.com/grafana/grafana/assets/1418924/4f2a92cf-abff-478d-866c-8bee5035a682">

**Comment by nmarrs** [comment]
This is caused by the logic skipping applying data css that is causing https://github.com/grafana/grafana/issues/84869

**Comment by nmarrs** [comment]
Given this is a bit more involved fix and not the most impactful I think a good interim solution here is to just disable background image settings for svg based elements (so we don't have dead UI options on release) and look back into this if / when we receive interest in this functionality for these specific elements

An alternative to the method above is to apply the svg itself as a background src to a html element where background size / repeat properties actually apply.
