### ISSUE TITLE
Canvas: The border of the SVG element clipped outside the wrapper

### ISSUE THREAD

**Issue by Develer** [grafana/grafana#84848]
Right now border of the new canvas shapes cut if the goes outside of the wrapper.
<img width="607" alt="Screenshot 2024-03-18 at 18 09 19" src="https://github.com/grafana/grafana/assets/1418924/b369506e-9839-4c35-a52b-1f68756b797a">

**Comment by nmarrs** [comment]
Additional context on this issue, it seems that ellipse and cloud is also impacted by this. Also for the cloud element it seems that default range is not behaving at the same scale as our other SVGs

![general strangeness with borders; uneven for triangle : parallelogram, maxed out for cloud seems over the top](https://github.com/grafana/grafana/assets/22381771/d8552c6e-02be-4d57-ad04-0965be2e7a6b)

**Comment by nmarrs** [comment]
Additional context [from original PR](https://github.com/grafana/grafana/pull/84205#pullrequestreview-1946765573)
