### ISSUE TITLE
[Feat Req】Elasticsearch support pipleline aggregations in Terms Order By +

### ISSUE THREAD

**Issue by chenspnjupt** [grafana/grafana#8485]
Grafana version : 4.3.1
Datasource: ElasticSearch 5.x
OS: SUSE Linux Enterprise Server 11

![image](https://cloud.githubusercontent.com/assets/8540045/26518776/ff036f00-42e9-11e7-963d-1d9b5677320e.png)

But elasticsearch return wrong result.
Requst JSON：
{
 "search_type": "query_then_fetch",
 "ignore_unavailable": true,
 "index": [
 "metricbeat-2017.05.27"
 ]
}{
 "size": 0,
 "query": {
 "bool": {
 "filter": [
 {
 "range": {
 "@timestamp": {
 "gte": "1495863416979",
 "lte": "1495867016979",
 "format": "epoch_millis"
 }
 }
 },
 {
 "query_string": {
 "analyze_wildcard": true,
 "query": "system.network.name:bond0"
 }
 }
 ]
 }
 },
 "aggs": {
 "5": {
 "terms": {
 "field": "beat.name",
 "size": 10,
 "order": {
 "6": "desc"
 },
 "min_doc_count": 1
 },
 "aggs": {
 "4": {
 "date_histogram": {
 "interval": "1m",
 "field": "@timestamp",
 "min_doc_count": 0,
 "extended_bounds": {
 "min": "1495863416979",
 "max": "1495867016979"
 },
 "format": "epoch_millis"
 },
 "aggs": {
 "1": {
 "max": {
 "field": "system.network.in.bytes"
 }
 },
 "6": {
 "derivative": {
 "buckets_path": "1",
 "unit": "second"
 }
 }
 }
 },
 "6": {
 "derivative": {
 "field": "1"
 }
 }
 }
 }
 }
}

Result ：
"Unknown key for a VALUE_STRING in [6]: [field]."

**Comment by marefr** [comment]
According to Elasticsearch documentation pipeline aggregations cannot be used for sorting using terms aggregation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order

Closing this for now. Would Elasticsearch add support for this we can reopen this issue.
