### ISSUE TITLE
[FAQ]what it means is Alert Conditions query the first parameter ?

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#8486]
In Grafana Alert configuration, the Condtion query first parameter most of the time is "A", but sometimes it will be "G", "F" or "M", what the first parameter means, I did't find the relevant explanation in the document("http://docs.grafana.org/alerting/rules/") .

![image](https://cloud.githubusercontent.com/assets/3882312/26521222/c7b4ffd8-4315-11e7-8f25-aed0238e94fd.png)

thanks for you explain.

**Comment by torkelo** [comment]
The letters refers to queries you define in the Metrics tab.  I have updated the docs in response to this question to make the docs more clear on this.
