### ISSUE TITLE
Dashboards: Custom Variables labels don't display when variable mentioned on the url

### ISSUE THREAD

**Issue by rckforme** [grafana/grafana#84870]
### What happened?

when creating a dashboard using custom variables the labels do not display correctly (and then disappear) 
if reloading the url

Here is the initial view of the dashboard:
<img width="472" alt="Screenshot 2024-03-20 at 5 00 12 PM" src="https://github.com/grafana/grafana/assets/71188769/abf8de21-581d-4bd6-92c8-2c8957c7ebcd">

now select "yes" from the drop down:
<img width="472" alt="Screenshot 2024-03-20 at 5 00 58 PM" src="https://github.com/grafana/grafana/assets/71188769/03d040ed-58f2-4485-9483-743023502b7b">

"yes" (the label) is now displayed in the drop down:
<img width="472" alt="Screenshot 2024-03-20 at 5 00 21 PM" src="https://github.com/grafana/grafana/assets/71188769/957244d0-f36c-4d5b-ae8a-39bbac960bc2">

reload the dashboard url

now "oui" (the value) is displayed in the drop down.
<img width="472" alt="Screenshot 2024-03-20 at 5 00 30 PM" src="https://github.com/grafana/grafana/assets/71188769/f09356a4-91e1-4094-a8a5-fa89a95ccd21">

if you select the drop down only the "All" option is available:
<img width="472" alt="Screenshot 2024-03-20 at 5 00 42 PM" src="https://github.com/grafana/grafana/assets/71188769/63db023a-3a4e-4b95-a9e9-1dfd18d9d14a">

### What did you expect to happen?

The drop down at the end of the sequence should contain the expected lables:
<img width="472" alt="Screenshot 2024-03-20 at 5 00 58 PM" src="https://github.com/grafana/grafana/assets/71188769/03d040ed-58f2-4485-9483-743023502b7b">

### Did this work before?

yes, it used to work back in grafana 8

### How do we reproduce it?

1. create a dashboard with this json:

```
{
  "__inputs": [],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.4.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": ".*",
        "current": {
          "selected": false,
          "text": "All",
          "value": "$__all"
        },
        "description": "",
        "hide": 0,
        "includeAll": true,
        "multi": false,
        "name": "custom",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "yes",
            "value": "oui"
          },
          {
            "selected": false,
            "text": "no",
            "value": "non"
          }
        ],
        "query": "yes : oui, no : non",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "custom-var-test",
  "uid": "fdga0pvf4pzi8e",
  "version": 2,
  "weekStart": ""
}
```

2. select `yes` from the custom variable drop down

3. hit reload on the web page

4. notice how the drop down now shows `oui` (the value not the label)

5. also notice how the only option available for selection is `All`

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.4.0 (03f502a94d)
OS: browser running on Mac Ventura 13.6.4 (22G513)
Browser: Chrome Version 121.0.6167.184 (Official Build) (arm64)

### Grafana platform?

Kubernetes

### Datasource(s)?

none

**Comment by tonypowa** [comment]
hi @rckforme 
thank you for the detailed report!

Could you please confirm if there are any console errors in your browser's developer tools when the issue occurs?

It would be great if you can share a more complete JSON model of the dashboard (if possible), specifically including any panel configuration that may be relevant to the custom variable.

Is this behavior consistent across different browsers or browser versions? Additionally, has this been tested in an incognito window or with browser extensions disabled to rule out any interference from them?

**Comment by tonypowa** [comment]
I cant repro this issue
Tested in Grafana v11.1.0 & FIrefox 124.0.2  |  Grafana v10.2.2 & Chrome 124.0.6367.61
Moving issue to dashboard squad for further review

**Comment by axelavargas** [comment]
Hey, @rckforme 👋🏾 , thank you for reporting this issue, it seems that it was already fixed, and I can't reproduce it 😢 . 
You can take a look at this dashboard https://play.grafana.org/d/fdga0pvf4pzi8e/eb5c9b98-0033-56f6-a179-1c3c34c828ba?orgId=1&var-custom=oui

**Comment by rckforme** [comment]
thanks @axelavargas, it seems like we need to update to 11.1.0 (at a minimum).
