### ISSUE TITLE
Syncronous vertical cursor line for all open panels

### ISSUE THREAD

**Issue by JaakkoRautanen** [grafana/grafana#84874]
**Why is this needed**:

This makes it easier to users to easily visually match moments in graphs between various panels.

**What would you like to be added**:

All open time-series graph panels in a dashboard show vertical cursor line syncronously at the same time. When users points cursor to one panel, let's say Traffic Rate OUT - in this case, vertical cursor line is shown automatically in all other open panels (Traffic Rate IN in this case) at the same time. In other words cursor lines in other panels mirror user cursor movements in the panel users is pointing to.

![Screenshot from 2024-03-21 08-17-06](https://github.com/grafana/grafana/assets/93380573/be290bc2-c0e0-4bf6-9dba-47059ee3e1c5)

I think this would be usefull in any case but especially when panels are not aligned in dashboard or have different widths. 

Ps. It should be concidered if horizontal cursor line should follow the same logic in case of same unit between panels.

**Who is this feature for?**

This feature is for all users and should be enabled by default.

**Comment by leeoniya** [comment]
this exists in the each dashboard's config, called shared crosshair.

it is more complicated for the y axis because even if units are the same, the range is often very different and without overlap. additionally, we support multiple y axes per panel and dashboards have many different units at the same time.

**Comment by JaakkoRautanen** [comment]
Oh, I didn't know that, thanks for information. Works like a charm!
