### ISSUE TITLE
[Feat Req] Support really small numbers in Graph Panel

### ISSUE THREAD

**Issue by JohannesAtGit** [grafana/grafana#8488]
- What Grafana version are you using?
v3.1.0
- What datasource are you using?
InfluxDB / Telegraf

- What OS are you running grafana on?
Ubuntu

- What did you do?
I have extremely small values in the InfluxDB. 
1495548240000000000 2.75390375499386e-25
1495548270000000000 1.6703270613015249e-25
etc.

- What was the expected result?
Grafana should show the graph and the line should just be 0.

- What happened instead?
Grafana does not show anything and display naN, infinity if you go with the mouse over the graph.

**Comment by daniellee** [comment]
This feature has already been implemented, so we’re going to go ahead and close this.
