### ISSUE TITLE
when rendering dashboard with annotations the dashboard is very very slow

### ISSUE THREAD

**Issue by davidkarlsen** [grafana/grafana#8490]
When annotating with alerts from prometheus (and there has been continous alerts for some time) the dashboard will render dead-slow

Please include this information:
-  grafana v4.3.1
- prometheus datasource 
- RHEL 7.3
- Annotate my dashboard with ALERTS{alertstate="pending"} and ALERTS{alertstate="firing"}
- the dashboard would render about as fast as normally
- the page "hangs" in chrome, warning about this and wanting to close the page, it will eventually render - but very slow
- see above

**Comment by torkelo** [comment]
How many annotation events is your query returning? Annotations are expensive to render, try to limit the number your query returns

**Comment by davidkarlsen** [comment]
How can this be done (other than changing the time interval for the entire dashboard)?

**Comment by davidkarlsen** [comment]
#7750 seems related so linking here

**Comment by davidkarlsen** [comment]
Oh - sorry for my ignorance - I see there is a step option in the templating now!
What happens if I set it to 10 minutes? Can it miss anything in inside a 10-minute span - or will it simply make the result "unique" over a 10 minute range - and give me all unique alerts?

**Comment by torkelo** [comment]
@davidkarlsen Not sure how the step option works in Prometheus for alert queries.
