### ISSUE TITLE
Tempo Search: Filtering not narrowing down results

### ISSUE THREAD

**Issue by msvechla** [grafana/grafana#84914]
### What happened?

When selecting a value for filter on the Tempo search, the following filters are not scoped to the results from previous filters.
In large environments, this makes it very hard to drill down using the Tempo search, as all values suggested in following filters can be completely unrelated to the already applied filters.

![image](https://github.com/grafana/grafana/assets/8947879/ea7b30a8-0c0c-47b1-894d-6f17a5a49d82)

In this example, when filtering based on `Service Name = "internal-api"`, the filter for `Span Name` shows values unrelated to the "internal-api" service.

### What did you expect to happen?

Applied filters to narrow down the possible values for the filter selectors in the Tempo search

### Did this work before?

Not sure, probably not

### How do we reproduce it?

1. Filter for a Service Name
2. Open the Filter for Span Name
3. See unrelated values

### Environment (with versions)?

Grafana: v10.4.0 (03f502a94d)
OS: MacOS
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by joey-grafana** [comment]
We send the current query with the request for span name values, can you please check if this is the case in your instance?

![Screenshot 2024-04-29 at 14 33 59](https://github.com/grafana/grafana/assets/90795735/abdaa7b9-c036-45ab-8c34-e477e04a83a8)

**Comment by joey-grafana** [comment]
We send the current query with the request for span name values, can you please check if this is the case in your instance?

Is this the issue or is it something else?

![Screenshot 2024-04-29 at 14 33 59](https://github.com/grafana/grafana/assets/90795735/678c42c6-6f1e-4ae1-8be4-c74de3f6c486)

**Comment by msvechla** [comment]
Thanks, I can confirm its working now on our end as well. In the meanwhile we update to Grafana `v10.4.1`, maybe the issue was fixed there.

Thanks a lot!
