### ISSUE TITLE
Tooltip looses its values

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#84937]
### What happened?

This probably relates to the latest changes around tooltip 10.4.0, the tooltip looses the metric description and instead just show Value:
![Screenshot_20240321_184606](https://github.com/grafana/grafana/assets/2118079/9daeafad-6fdc-4199-b15e-2aceb04188d8)

Once editing the panel without changing anything the values are back in all the panels in the dashboard not just the edit one, but it goes a way after a refresh.
![Screenshot_20240321_184839-1](https://github.com/grafana/grafana/assets/2118079/ca895198-4e44-4156-a0e0-95a9c9a75e9a)

### What did you expect to happen?

The graph tooltip should contain the metrics labels like this:
![Screenshot_20240321_184839-1](https://github.com/grafana/grafana/assets/2118079/ca895198-4e44-4156-a0e0-95a9c9a75e9a)

### Did this work before?

yes

### How do we reproduce it?

1. Create a dashboard with multiple panels
2. After a refresh, the tooltip loses its labels
3.
,

### Is the bug inside a dashboard panel?

[panel.txt](https://github.com/grafana/grafana/files/14704659/panel.txt)

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

Prometheus

**Comment by leeoniya** [comment]
this has been fixed since 10.4. please try on a v11 nightly build: https://grafana.com/grafana/download/nightly?edition=oss

**Comment by amnonh** [comment]
Unfortunately, I cannot use unofficial releases. Is there a chance it will be part of a patch release?

**Comment by leeoniya** [comment]
note: fix for this was https://github.com/grafana/grafana/pull/82985
