### ISSUE TITLE
[Feature request] Send unique incident_key to Pagerduty per alert and serie

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#8493]
PagerDuty de-duplicates incidents based on the incident_key parameter. Today the incident_key are sent as 	`alertId-<alert id in grafana>`, e.g. alertId-123.

When #6041 is closed it would be great if the incident_key are sent to Pagerduty as some value that uniquely identifies an alert for a certain serie, e.g. alert name + serie.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
