### ISSUE TITLE
Error / Warning Reporting

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#84948]
Basic logs come with a new set of limitations (8 - day query retention, limited Kusto Query Language support, no support in alerts, among others)

For all limitations that are not met, the plugin will fail / warn gracefully and notify:
- of 8-day data retention when a time range greater than 8-days is selected
- of no support on alerting queries for basic logs table
- Any syntax errors that the API for basic logs queries reports back should be properly parsed and shown to the user

**Comment by aangelisc** [comment]
Fixed by #87653
