### ISSUE TITLE
Cost and usage notification

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#84949]
In order to ensure users are aware of the cost per query associated with Basic logs, a Modal containing an acknowledgement of the cost per query model should show as follows:

1. When users first switch from Analytics to Basic
     a. Once they have clicked I acknowledge, succeeding queries should not require further acknowledgement

2. IF users switch from Basic back to Analytics and then again back to Basic, this acknowledgement should show again

Once users have written their queries, and accepted the acknowledgement, they should be notified of the approximate GiB of data scanned below the query editor so they are always aware of the data usage. If for some reason, users do not have access to the table used to calculate the query usage, a generic warning will be displayed.

Both of the above will contain links to docs on  [Basic logs information](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/basic-logs-configure?tabs=portal-1 )

**Comment by aangelisc** [comment]
Closed by #86737 #88009
