### ISSUE TITLE
Basic / Analytics toggle in Log analytics query experience

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#84946]
In order to support Basic logs, there needs to be a toggle that lets users switch between basic and analytics in order to properly route the query against the right API endpoint.

This toggle should:
- Only show if the resource they have selected is a Log analytics workspace and Basic Logs has been enabled on the datasource level
- Not show when users are writing alert queries using Azure Monitor Logs Service regardless of the resource type they have selected
- Clear the query in the Query text editor whenever users change from Basic to Analytics and viceversa

**Comment by aangelisc** [comment]
Fixed by #85905
