### ISSUE TITLE
[Feature request] JS interface API to interact with template variables in Text Panels

### ISSUE THREAD

**Issue by christophe-r** [grafana/grafana#8495]
Hello,

I manage thousands of hosts into InfluxDB/Grafana. These hosts are identified by their IP address.
I created a template variable on the IP address.
To make the navigation between hosts easier, I created a custom navigation form in a Text Panel (html+js), with a little bit of ajax.

Thanks to the #1816 case (@jezhalford post), I can listen to the change of the template variable, in order to autofill my form. (e.g. if I select a host directly by its IP address).

Now, if I want to select a host by its criterion (thanks to the ajax query via the Text Panel), I have to change the content of the template variable programmatically. The only way I found to do this is (which is in fact a workaround):
`window.location = "https://grafanaserver/dashboard/db/mydashboard?orgId=1&var-host=X.X.X.X";`
with "X.X.X.X" which is the new IP address obtained via the custom form with an ajax query.

Obviously with this solution the whole page reloads...

The idea is to provide an easy way to:
- listen a dashboard refresh,
- listen a change of template variables,
- change programmatically a template variable from the Text Panel without having to reload the whole page.

By the way, is there a better workaround than `window.location`?

**Comment by torkelo** [comment]
you can write a custom panel, then you can use the template variableSrv

**Comment by christophe-r** [comment]
I am trying to update my template variable like this from the text panel, but that does not refresh the dashboard:

```
var t = angular.element('grafana-app').injector().get('templateSrv');
var varValue = { text: "X.X.X.X", value: "X.X.X.X" };
var tVar = t._index['host'];
tVar.setValue(varValue);
t.updateTemplateData();
```

**Comment by joehoeller** [comment]
How do you write an AJAX call from a custom Grafana page that will allow you to select something that updates the data with new objects?

**Comment by daniellee** [comment]
@joehoeller that question is very broad. You'll have to be more specific than "select something that updates the data with new objects". 

There are lots of plugins to Grafana - do any of them do something similar to what you are trying to achieve? If so, then try and copy that.

**Comment by joehoeller** [comment]
Ok, so I have a custom javascript grafana page and I made a drop down select box that loads a new .js file and generates charts. I'd like to do it dynamically w one file.

**Comment by joehoeller** [comment]
Does that help? 

Also what I'm trying to do is sort of complex. I'm not sure texting is proper medium to describe everything.

**Comment by daniellee** [comment]
@joehoeller Is this a totally separate page that does not use any data from Grafana or from a Grafana data source? If you need access to Grafana functions, then you will have to build a custom plugin.
