### ISSUE TITLE
Canvas: When changing element type with a rotated element moveable control box glitches

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#84958]
This is relatively minor, but when changing the element type of a rotated element, the moveable control box "glitches" and does not update to the new default non rotated element's shape

https://github.com/grafana/grafana/assets/22381771/095e55af-becf-4030-be00-48143089b7f2

**Comment by adela-almasan** [comment]
Fixed by https://github.com/grafana/grafana/pull/85690
