### ISSUE TITLE
New service for Azure Monitor Basic Logs

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#84950]
Instead of Basic logs being nested under the same Azure Monitor Log Analytics datasource, a new service should be created for basic logs.

**Comment by aangelisc** [comment]
I think we can discuss the technical details of how to implement this before proceeding to ensure minimal duplication of code whilst also ensuring there's a distinct enough separation between the two to not cause issues 😊

**Comment by aangelisc** [comment]
Fixed by #87653
