### ISSUE TITLE
[Bug] Logarithmic Scale Is Not Displayed Very Well

### ISSUE THREAD

**Issue by pnovotnak** [grafana/grafana#8497]
Please include this information:
- What Grafana version are you using?
Version 4.3.1 (commit: befc15c)
- What datasource are you using?
InfluxDB / N/A
- What OS are you running grafana on?
Linux
- What did you do?
Set up a chart with a logarithmic scale
- What was the expected result?
That the Y-axis scale would be chosen appropriately and that the Y-min could be set as desired.
- What happened instead?
![screen shot 2017-05-30 at 2 43 31 pm](https://cloud.githubusercontent.com/assets/5713245/26606374/8d99f6e0-4546-11e7-99f6-f8cf3860bfeb.png)
![screen shot 2017-05-30 at 2 44 04 pm](https://cloud.githubusercontent.com/assets/5713245/26606380/8fca89e8-4546-11e7-98fe-f7c2526056b4.png)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I can provide a network request via email to a maintainer if they are careful with it's contents.

**Comment by torkelo** [comment]
This is fixed I master and in 4.3.x branch, patch release soon

**Comment by daniellee** [comment]
Made some more improvements that will be included in v4.4.0 -> 1b79e179707f2f6d220e295a1474fef3b9e8b36a
