### ISSUE TITLE
Updating alert rule group with a duplicate value returns 5xx error, should be 4xx

### ISSUE THREAD

**Issue by JohnnyQQQQ** [grafana/grafana#84985]
This is a follow-up of https://github.com/grafana/grafana/pull/76396, which should also target `/api/ruler/grafana/api/v1/rules/<Alert folder>`

![image](https://github.com/grafana/grafana/assets/3528218/a6230d28-222d-4ebc-96d1-f19d92f71a11)

**Comment by wasim-nihal** [comment]
@JohnnyQQQQ , is this issue open for contribution? I am willing to create a PR for the same.

**Comment by JohnnyQQQQ** [comment]
Yes, sure

**Comment by wasim-nihal** [comment]
Hi @JohnnyQQQQ , the issues seems to have been fixed in the commit https://github.com/grafana/grafana/commit/dd0ca1263bb0f635a84bbc2311d197ab643c129f#diff-56cde79e40d95960ccad2c25a4dd229c04b601d38967a2afb14503f97ffd50ac .

**Comment by JohnnyQQQQ** [comment]
Great catch! Thanks for taking a look, I'll close the issue.
