### ISSUE TITLE
Google Cloud Monitoring DataSource: UI locks up when using Query builder

### ISSUE THREAD

**Issue by mcove11** [grafana/grafana#84996]
### What happened?

When building a Query with Google Cloud Monitoring Datasource using the query builder, the UI locks up after selecting every part of the query, sometimes crashing the browser. 

By the time you work through selecting project-->service--> and adding filters it looks like its re-querying all data in the background each time a button is clicked. If you wait long enough - could eventually select everything but would take minutes.

### What did you expect to happen?

Selecting variables in the query builder to not be as intensive. 

### Did this work before?

Not sure if worked differently in previous versions. 

### How do we reproduce it?

1. In Grafana Cloud - configure and add a Google Cloud Monitoring Datasource 
2. In explore view select Query Builder 
3. Begin building out a query (one that has a result set). 

### Environment (with versions)?

Grafana: Cloud
OS: OSX Sonoma 14.3
Browser:Firefox and Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Google Cloud Monitoring

**Comment by aangelisc** [comment]
Can confirm I've replicated this issue and have a fix open.
