### ISSUE TITLE
[Bug] baseurl of YUM repository is broken

### ISSUE THREAD

**Issue by cr0ssmind** [grafana/grafana#8499]
The baseurl is **broken** in the official YUM repository:

https://packagecloud.io/grafana/stable/el/6/$basearch

```
[grafana]
name=grafana
baseurl=https://packagecloud.io/grafana/stable/el/6/$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

Could you re-create or restore the mentioned yum repo please?

Many Thanks!

**Comment by torkelo** [comment]
why do you say it's broken? Works fine? 

Do you get an error when you run:

```
sudo yum install grafana
```

**Comment by cr0ssmind** [comment]
Update: You have right, It works fine. It had a misconfiguration in my infrastructure.

**Comment by cr0ssmind** [comment]
Thank you for the review!
