### ISSUE TITLE
PDF and Reporting tab not added in ShareModal

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#85023]
Enterprise tabs are not added in Scenes ShareModal.
Those tabs are added in the old arch via `addDashboardShareTab` method
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/85081
- [ ] https://github.com/grafana/grafana/issues/85124
```

**Comment by dprokop** [comment]
@juanicabanas  - thank you so much for landing this work 🥇
