### ISSUE TITLE
[Bug] Prometheus Metric switching between OK / NO DATA every 1 minute

### ISSUE THREAD

**Issue by garceri** [grafana/grafana#8505]
- What Grafana version are you using?
4.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Amazon Linux 2017.03
- What did you do?
Trying to setup an alert for JVM Heap memory usage, i have the graph showing up fine with no gaps in data.
Created alarm and set threshold artificially low to test notifications
Grafana alternates between OK/No Data states every 1 minute

- What was the expected result?
There is no reason for the NO DATA status

- What happened instead?
NO DATA status means that the alert logic is ruined by the constant status changes (ie, even if the alert triggers the status changing prevents the alerts from being sent)

**Screenshots:** 
![image](https://cloud.githubusercontent.com/assets/10517648/26652562/b2a912f0-4626-11e7-98a4-1248b8c99cc2.png)
![image](https://cloud.githubusercontent.com/assets/10517648/26652614/d842a80a-4626-11e7-8af2-dfc4bfe47ae6.png)
**Alert Config:**
![image](https://cloud.githubusercontent.com/assets/10517648/26652710/31899d7e-4627-11e7-9b6c-942708f537e4.png)
**Metrics Config**
![image](https://cloud.githubusercontent.com/assets/10517648/26653147/9d19fa06-4628-11e7-80f0-a9751f76bfbb.png)

**Comment by torkelo** [comment]
looks to be something wrong with your prometheus server, look to be returning no data points sometimes. 

Try changing your alert query time range from 5m to now, to 7m, now-2m.
