### ISSUE TITLE
Variables: Enable non-query reference of variables with regex modification

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#85056]
**Why is this needed**:

In many use cases, it is relevant to have a set of query-based Variables that allow for customizing the dashboard view. This is doable today by creating each Variable as an independent query, or alternatively using the results of other variables as part of a new Variable query.

However, this can result in a lot of queries that need to finish before the rest of the dashboard can load, slowing down performance. 

**What would you like to be added**:

In e.g. an SQL context, it may be preferable to do a single hidden Variable query, for example as below:

```
SELECT
    CONCAT(cluster, '|', deviceid, '|', message, '|', signal, '|', aggregation) AS combined_variable
FROM
    tbl_aggregations_tripsummary
WHERE 
    date_created BETWEEN $__rawTimeFrom('yyyy/MM/dd') AND $__rawTimeTo('yyyy/MM/dd')
GROUP BY
    deviceid, cluster, message, signal, aggregation;

```

The result of this would be outputs like below:

```
cluster1|2F6913DB|CAN2_GnssImu|AccelerationY|avg
cluster1|2A896980|CAN2_GnssSpeed|Speed|avg
cluster1|2A896980|CAN2_GnssPosition|Longitude|first
cluster1|2A896980|CAN2_GnssOdo|DistanceTrip|delta_sum
cluster1|2F6913DB|CAN2_GnssSpeed|Speed|avg
cluster1|2F6913DB|CAN2_GnssPosition|Latitude|first
cluster1|2F6913DB|CAN2_GnssPosition|Longitude|first
cluster1|2A896980|CAN2_GnssAltitude|Altitude|max
cluster1|2A896980|CAN2_GnssImu|AccelerationZ|avg
cluster1|2A896980|CAN2_GnssPosition|Latitude|first
cluster1|18D508A1|CAN2_GnssImu|AccelerationZ|avg
``` 

Ideally, I would then be able to create separate non-query based Variables that simply take the values of my `combined_variable` result and splits it into sub parts via regex. This way I can get the data I need for 5 Variable drop downs at the cost of 1 query. 

This seems like it should be straight forward, but apparently the only way to reference the results of `combined_variable` is through other queries - making it difficult to use this in an efficient manner, unless I am overlooking something

**Who is this feature for?**

This would be useful to practically all dashboards that deploy multiple query based Variables.

**Comment by MatinF** [comment]
Nevermind, I found this out via a creative SQL query as below:

```
SELECT * FROM (VALUES ${combined_variable:csv})
```

**Comment by tonypowa** [comment]
Thank you for sharing your SQL solution @MatinF ! Your creativity is valuable to the community.
