### ISSUE TITLE
[Feature request] Proxy requests from Datasource plugins to Redis

### ISSUE THREAD

**Issue by vassilevsky** [grafana/grafana#8506]
Hello 👋

We are using in-house metrics backend. It stores metrics in Redis.

I want to write a Datasource plugin for it. But it has to query Redis.

Is it a good idea to add a proxy for Redis to Grafana backend? It already uses Go Redis client.

For example, POST from plugin to backend. In POST body, Redis commands (plain text). Backend sends them in MULTI command to Redis, returns result as array.

Should this be done?

**Comment by nextkitt** [comment]
Try using the python script to read redis, and then write to graphite

**Comment by vassilevsky** [comment]
But we don't even have a Graphite server...

**Comment by torkelo** [comment]
there seems to be http wrapper around the redis api already:
http://webd.is/
