### ISSUE TITLE
Annotations are shown out of Time series space if to use Time shift option

### ISSUE THREAD

**Issue by vladchel** [grafana/grafana#85075]
### What happened?

Annotations aren't taking into account Time shift value of Time series. Annotations can be shown out of Time series place (on the right of the bottom Time series):
![Time Shift with Annotations](https://github.com/grafana/grafana/assets/21196770/3454ab5e-eed7-45e3-b795-cb73c2946d4c)

### What did you expect to happen?

Annotations on Time series according to given Time shift.

### Did this work before?

The same issue for Grafana 10.2. No information about previous versions.

### How do we reproduce it?

1. Create Time series
2. Define Time shift via Query options
![5d time shift](https://github.com/grafana/grafana/assets/21196770/dbafb201-0706-4002-afb6-8c564510b311)
3. Add and enable annotations
4. Check annotations positions

### Environment (with versions)?

Grafana: v10.4.1 (d94d597d84)
OS: Windows 11
Browser: Chrome 122.0.6261.129

### Grafana platform?

Docker

### Datasource(s)?

Loki and Prometheus

**Comment by torkelo** [comment]
sadly annotations do no support time shift (and never have) as the query is executed on the dashboard level

**Comment by axelavargas** [comment]
Hey @vladchel 👋🏾, thank you for raising this issue. Unfortunately, as Torkel mentioned, we don't support this use case and there are no short-term plans to include it. I am closing this issue as we are aiming to reduce the number of triaged GitHub issues.
