### ISSUE TITLE
AdHocFilters: Allow providing a free text value

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#85070]
In the current implementation of the ad hoc filters, the allowed values for a given dimension are only the ones returned by `getTagValues` calls. This is a limiting factor for scenarios where user would like to provide a regular expression or an arbitrary, free text value.

**Comment by leeoniya** [comment]
feels similar to https://github.com/grafana/grafana/pull/84790

**Comment by dprokop** [comment]
@leeoniya yes, but missing in scenes
