### ISSUE TITLE
Constant variables shows in the dashboard after creation

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#85080]
When returning to the dashboard after creating a constant variable, this one is visible in the UI. After saving and refreshing the variable is no longer visible. See the video.

Note: there's an issue related to constant variables showing in the URL that I couldn't reproduce in the scenes architecture. Would be great to verify we don't reintroduce it. https://github.com/grafana/grafana/issues/82682

https://github.com/grafana/grafana/assets/74534993/8df867e3-708c-4aad-8ccc-4f7f1195d04c

**Comment by dprokop** [comment]
> Note: there's an issue related to constant variables showing in the URL that I couldn't reproduce in the scenes architecture. Would be great to verify we don't reintroduce it. https://github.com/grafana/grafana/issues/82682

@natellium  - in the new arch constant variable is never synced to the URL, ref https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/variants/ConstantVariable.ts#L18
