### ISSUE TITLE
[Bug]  Invalid interval string, expecting a number followed by one of "Mwdhmsy" with elasticsearch

### ISSUE THREAD

**Issue by misslzyan** [grafana/grafana#8510]
Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? elasticsearch 5.4.0
- What OS are you running grafana on? 	Debian GNU/Linux 7.8 (wheezy)
- What did you do? query data with elasticsearch datasource 
- What was the expected result?  correct data
- What happened instead?  error 
- If related to metric query / data viz:

the elasticsearch datasource :
 
![qq 20170601155651](https://cloud.githubusercontent.com/assets/17558850/26670109/f801a67a-46e2-11e7-8d70-a555ae5b738e.png)

query metric like 

![2](https://cloud.githubusercontent.com/assets/17558850/26670183/46b9c50e-46e3-11e7-9417-acd1195567c9.png)

the network _mapping:
Request URL:http://10.171.160.242:3000/api/datasources/proxy/1/druid-test-2017-06-01/_mapping
Request Method:GET
Status Code:200 OK
Remote Address:10.171.160.242:3000

but no query data . error like this :+1: 

Error: Invalid interval string, expecting a number followed by one of "Mwdhmsy"
    at Object.c.describe_interval (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:33:15362)
    at Object.c.interval_to_ms (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:33:15486)
    at Object.c.calculateInterval (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:33:14990)
    at b.calculateInterval (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:55:19124)
    at b.updateTimeRange (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:55:18878)
    at i (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:51:24759)
    at http://10.171.160.242:3000/public/app/boot.d709d8d5.js:51:25181
    at o.$eval (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:52:293)
    at o.$digest (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:51:30809)
    at o.$apply (http://10.171.160.242:3000/public/app/boot.d709d8d5.js:52:576)

how to solve this error ?

**Comment by torkelo** [comment]
The group by time interval in data source options, please change this to `>60s` to set a lower limit of 60s as  the group by time interval (set this to the lowest time distance between two documents in your elasticsearch index)

Added docs issue to document this option:
https://github.com/grafana/grafana/issues/8511

**Comment by misslzyan** [comment]
@torkelo thanks for your replication.
and I did like that you said , but can't solve it . The exception showed below:
![3](https://cloud.githubusercontent.com/assets/17558850/26674509/536d2682-46f3-11e7-845e-3d4b74fab543.png)
![4](https://cloud.githubusercontent.com/assets/17558850/26674625/a1cf2938-46f3-11e7-85e0-b35575a77d8d.png)
![5](https://cloud.githubusercontent.com/assets/17558850/26674632/a8084db6-46f3-11e7-8f7b-7bd32791a848.png)

**Comment by torkelo** [comment]
you have not changed group by time interval, it is still wrong. It needs to be a timespan, like `10s`,  `1m`, or  `1h`. Or a lower limit time span like `>60s`

**Comment by misslzyan** [comment]
@torkelo   thanks a lot ~
is this right?
![10](https://cloud.githubusercontent.com/assets/17558850/26678080/6097703e-4701-11e7-9945-793fd73055ae.png)

the exception also existed.

**Comment by torkelo** [comment]
no, please read what I wrote :) hint `Group by time interval`  (option in metrics tab below queries, and in data source edit page)

**Comment by misslzyan** [comment]
yeah~ it is correct ! Thank you very much ~

**Comment by sword2ya** [comment]
可以帮忙翻一下吗？我也碰到这个问题了，但看不懂

**Comment by Tang-RoseChild** [comment]
@sword2ya es的话，我的是influxdb，在source edit page 最下端有个min time interval，时间格式为 "<数值><单位>"，例如 "60s"，你看到天interval的地方边上会有一个感叹号的图标，会有提示

**Comment by Quanjiang** [comment]
@sword2ya  https://github.com/grafana/grafana/issues/10950
