### ISSUE TITLE
Auth.Proxy + Auth.LDAP with signout_redirect_url throws runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by devsecadm** [grafana/grafana#85128]
### What happened?

Configured signout_redirect_url in the general [auth] section in conjunction with auth.ldap and auth.proxy.  Grafana appears to logout, but then logs right back in due to not properly redirecting to the provided URL.

`runtime/panic.go:261 (0x56ae357)
runtime/signal_unix.go:861 (0x56ae325)
github.com/grafana/grafana/pkg/api/login.go:266 (0x931a0b2)
github.com/grafana/grafana/pkg/api/response/web_hack.go:40 (0x6c2250f)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:131 (0x6c14dce)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/services/contexthandler/contexthandler.go:137 (0x933c021)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/render.go:44 (0x6c1595d)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/macaron.go:137 (0x6c14e72)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/csrf/csrf.go:66 (0x892c7ba)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/recovery.go:180 (0x931411d)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/loggermw/logger.go:72 (0x892d7d6)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/request_metrics.go:75 (0x70ba615)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/request_tracing.go:88 (0x9314df5)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/middleware/requestmeta/request_metadata.go:66 (0x933b175)
net/http/server.go:2136 (0x5a09868)
github.com/grafana/grafana/pkg/web/context.go:52 (0x6c138b6)
github.com/grafana/grafana/pkg/web/router.go:155 (0x6c1702d)
github.com/grafana/grafana/pkg/web/router.go:211 (0x6c17b94)
github.com/grafana/grafana/pkg/web/macaron.go:163 (0x6c1529c)
net/http/server.go:2938 (0x5a0c54d)
net/http/server.go:2009 (0x5a08433)
runtime/asm_amd64.s:1650 (0x56cd860)`

### What did you expect to happen?

I expected Grafana to logout killing the grafana_session cookie.
Then proceed to the url defined in signout_redirect_url which would invalidate the session with our SSO provider which would prevent the user from getting past the web agent and back to Grafana.

### Did this work before?

This is our initial setup.

### How do we reproduce it?

1. Define signout_redirect_url under [auth] with [auth.ldap] and [auth.proxy] defined.
2.  Attempt to logout.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.4.1 (d3ce857c0e)
OS: Red Hat Enterprise Linux release 9.3
Browser: Edge/Chrome/Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

None

**Comment by steverweber** [comment]
10.2.6 WORKS (signout_redirect_url works with auth.proxy)
10.4.2 FAILS
11.0.0-preview FAILS
perhaps related 
- https://github.com/grafana/grafana/issues/79839
- https://github.com/grafana/grafana/issues/84108

**Comment by klesh** [comment]
Having the same problem, is this fixed backported to v10?
