### ISSUE TITLE
[Bug] InfluxDB templating issues

### ISSUE THREAD

**Issue by bolausson** [grafana/grafana#8512]
Hej all,

I am not sure if this is a bug, limitation or just my inexperience with GRAFANA/InfluxDB.
While trying to use templating with InfluxDB I am struggling to show multiple series in a single graph.

My InfluxDB series looks like:
`{
    "measurement": "VirtualDisk",
        "tags": {
            "metric": "rate",
            "controller": "0",
            "idx": key
            },
        "fields": {
            "KiB/sec": "%(f).0f" % {"f": CA_RATES[key][1]},
            },
        "time": current_time,
}`

e.g.:
VirtualDisk,controller=0,idx=0,metric=rate "KiB/sec"=60000
VirtualDisk,controller=0,idx=1,metric=rate "KiB/sec"=34000
VirtualDisk,controller=0,idx=2,metric=rate "KiB/sec"=32
VirtualDisk,controller=0,idx=3,metric=rate "KiB/sec"=0

I am using the templateing variable $VDID to get the values of tag "idx":
`SHOW TAG VALUES FROM "VirtualDisk" WITH KEY = "idx" WHERE controller = '0'`
The output is
`0 1 2 3`
which is fine.

In the graph I am using the query
`SELECT "KiB/sec" FROM "sfa14k"."VirtualDisk" WHERE "controller" = '0' AND "metric" = 'rate' AND "idx" =~ /^$VDID$/ AND $timeFilter`
to show the series values from the field "KiB/sec".
This is working as expected as long as I do only select a single value for VDID (2):
![single_value_selected](https://cloud.githubusercontent.com/assets/10600678/26671874/58d370d6-46b7-11e7-82a9-85a7e0c5599e.png)

As soon I select a second value for VDID (2,3), the plot contains the values of both keys but in a single plot instead of two independent plots:
![two_values_selected](https://cloud.githubusercontent.com/assets/10600678/26671882/5ea14682-46b7-11e7-992f-786881315c43.png)

The plot is expected to looks like this (using a second query do demonstrate it):
![expected](https://cloud.githubusercontent.com/assets/10600678/26671889/641e9a9c-46b7-11e7-950b-55650b4ec7d4.png)

Any ideas?

I have read and tried the suggestions here: https://github.com/grafana/grafana/issues/2555 but it didn't work for me.

- What Grafana version are you using?
v4.3.2 (commit: ed4d170)
- What datasource are you using?
InfluxDB 1.2.4
- What OS are you running grafana on?
CentOS Linux release 7.3.1611 (Core)

Greetings and thanks in advance,
Bjoern

**Comment by torkelo** [comment]
please read InfluxDB query documentation :) 

need to group by tag to get multiple series back for each tag value. Please use community site for questions in the future

**Comment by bolausson** [comment]
Thanks for the quick reply.

I gave it a read and came up with the following:

**Comment by bolausson** [comment]
SELECT "KiB/sec" FROM "sfa14k"."VirtualDisk" WHERE "controller" = '0' AND "metric" = 'rate' AND "idx" =~ /^$C0IDX$/ AND $timeFilter GROUP BY "idx"

did the trick... sorry for the noise.

Cheers,
Bjoern
