### ISSUE TITLE
Oauth: Certificate Reload for Oauth provider

### ISSUE THREAD

**Issue by khushijain21** [grafana/grafana#85132]
**Why is this needed**:

This feature is to support reloading the certificates of oauth providers when the certificates are renewed, instead of restarting the grafana.

**What would you like to be added**:
Certificate Reload functionality for Oauth providers

**Who is this feature for?**

For everyone who needs certificates to be reloaded up on renewal automatically.

**Comment by wasim-nihal** [comment]
@mgyongyosi, I'd like to work on this feature.

**Comment by wasim-nihal** [comment]
@mgyongyosi , after looking at the codebase, it seemed to me that this feature to reload tls cert and key is already supported by the Reload function below. It seems to update the OAuth info. Please correct me if I am wrong here with the understanding. 
https://github.com/grafana/grafana/blob/272cfa83b188e61226fd068927577fa79665fd46/pkg/login/social/connectors/generic_oauth.go#L116

In case of MySQL database client connection, the TLS config uses GetClientCertificate() is used to read certificates for each request.
https://github.com/grafana/grafana/blob/272cfa83b188e61226fd068927577fa79665fd46/pkg/services/sqlstore/tls_mysql.go#L28

Please let me know if similar change needs to be done for OAuth Client Certificates as well? I shall work on it.

**Comment by mgyongyosi** [comment]
Hey @wasim-nihal, Thanks for pinging me, you're correct! With the latest improvements in Grafana 11 the Reload function takes care of reloading the settings periodically.

Closing this ticket.
