### ISSUE TITLE
[Bug] Grafana not retrieving values when single value is selected in template

### ISSUE THREAD

**Issue by ricard0ff** [grafana/grafana#8514]
- What Grafana version are you using? 4.3.1
- What datasource are you using? graphite
- What OS are you running grafana on? Ubuntu
- What did you do? Selected one field from the template
- What was the expected result? show data for the selected field
- What happened instead? get a message about no datapoints

Basically I have a template where I select the fields, if i try it with multiple values I get  the following result:
<img width="1244" alt="multiselect" src="https://cloud.githubusercontent.com/assets/17491850/26688262/14cd0f90-46ea-11e7-880c-b84c184d61d5.png">

If I just select one I will get "no datapoints" from it:
<img width="1245" alt="single" src="https://cloud.githubusercontent.com/assets/17491850/26688316/3398df8a-46ea-11e7-90d5-927af04aa92a.png">
Even if i try to use the refresh  button from grafana.
But if i refresh the whole page via the browser I can get the single value to show.
Worth mentioning this was not happening on 3.X, only started happening after the upgrade.

Regards,
Ricardo

**Comment by torkelo** [comment]
This is a bug in an older version of Graphite that does not handle glob expressions with a single entry, like {myvalue} . 

You can fix this by upgrading Graphite.
