### ISSUE TITLE
[Feature request] Programmatically enable plugins 

### ISSUE THREAD

**Issue by mikef-nl** [grafana/grafana#8515]
There does not seem to currently be a method to enable a plugin via the API or through the use of grafana-cli. Is this something that is likely to be implemented?

**Comment by torkelo** [comment]
You mean apps? Apps currently need to be enabled via gui or http api.

**Comment by mikef-nl** [comment]
Sorry yes I meant apps. Is there documentation on enabling an app via the http api?

**Comment by torkelo** [comment]
no, you will have to reverse engineer that (open chrome dev tools and look at the api call the UI makes when enabling an app)

**Comment by mikef-nl** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/398 solved here
