### ISSUE TITLE
[Bug] Grafana 4.3.2 Y-scale is shifted on a logarithmic scale

### ISSUE THREAD

**Issue by alxrem** [grafana/grafana#8516]
Reproducible with docker images grafana/grafana:4.3.2

![log-scale-0 1](https://cloud.githubusercontent.com/assets/123157/26717180/1a2ceb22-4785-11e7-9cc8-7d1acece0da2.png)
![log-scale-1](https://cloud.githubusercontent.com/assets/123157/26717181/1a30b932-4785-11e7-893b-b627508af33c.png)
![log-scale-10](https://cloud.githubusercontent.com/assets/123157/26717182/1a320148-4785-11e7-86da-88e2e6533718.png)

**Comment by torkelo** [comment]
Shifted? Can you describe more what you think is wrong?

**Comment by alxrem** [comment]
Sorry, I forgot to say that panels has property `Y-Min: 0`. I think, in this case Y-scale should start from 0.

**Comment by torkelo** [comment]
0 is not a valid y-min value for a log scale. either 1 or something close to zero, like  0.00001
