### ISSUE TITLE
[Feature request] Graph Panel Tooltip, use series tags as columns 

### ISSUE THREAD

**Issue by kiranprabhu** [grafana/grafana#8517]
- What Grafana version are you using?
v4.1.0-beta1
- What datasource are you using?
influxdb 1.1.1
- What OS are you running grafana on?
Grafana Server : RHEL 5 x64   Client: Chrome on Windows 10

For a query such as like this (select sum(BPS) as BPS, sum(retran) as RETRAN, min(windowsize) as WINDOW from mymeasure group by time(1s), remote)  
Results in to a graph output that show's tooltip something like this

![image](https://cloud.githubusercontent.com/assets/9692754/26718998/72a08140-47a0-11e7-92da-3f7c064f493f.png)

Well this is fine as long as the columns or group are less in numbers other wise it doesnt fit in the tooltip window, it could be very useful if the tooltip is displayed something like this

![image](https://cloud.githubusercontent.com/assets/9692754/26719055/b462a5c2-47a0-11e7-8335-f6a083ea8844.png)

This will make lot of sense since the fields are grouped together and save UI space.

Thanks
Kiran Prabhu

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
