### ISSUE TITLE
[BUG] Panel Table: CSV export has charecter escaped 

### ISSUE THREAD

**Issue by mk-dhia** [grafana/grafana#8518]
- What Grafana version are you using? 4.3 / 4.2
- What datasource are you using? elasticsearch
- What OS are you running grafana on? Linux
- What did you do? export a table with text containing HTML character escaped (& < > ... for example )
unescaped
- What happened instead? the csv is with escaped character  `"&amp;"` instead of `"&"` which add to the csv a new column (the ";" is the separator)

This change was introduced with 3.1.0 commit 65683ab2419d4c8204a47b2d9595c7b41663ec90 file public/app/plugins/panel/table/renderer.ts (Table plugin, now in line 68 to 76). It comes from the case where we do not sanitze HTML (the else) we return _.escape(v) instead of v 
The extract from the commit
public/app/plugins/panel/table/renderer.
```javascript
-    return v;
+    if (style && style.sanitize) {
+      return this.sanitize(v);
+    } else {
+      return _.escape(v);
+    }
```

I do not see why the escape is needed.  i was modifying the code by removng the escape and all works properly for both the render in web page and the export . But i m not javascript expert , so may be i m missing something.
```javascript
   if (style && style.sanitize) {
      return this.sanitize(v);
    } else {
      return v;
}
```

An other possible solution is to update (I have not tested yet) public/app/core/utils/file_export.ts and add unescape on all text in function exportTableDataToCsv(table) , However we need to ake sure that all data that reach this function are escaped before so we do not modify text that contain text that looks like an escaped character 
```javascript
export function exportTableDataToCsv(table) {
    var text = '';
    // add header
    _.each(table.columns, function(column) {
-        text += (column.title || column.text) + ';';
+       text += _.unescape(column.title || column.text) + ';'
    });
    text += '\n';
    // process data
    _.each(table.rows, function(row) {
        _.each(row, function(value) {
 -           text += value + ';';
+           text += _.unescape(value) + ';';
        });
        text += '\n';
    });
    saveSaveBlob(text, 'grafana_data_export.csv');
}
```

I do not master javascript, but if you find one acceptable i can propose a pull request or you can do the modification 

Regards
Dhia

**Comment by torkelo** [comment]
We need to the escape or sanitizing, otherwise it's a big security hole

**Comment by mk-dhia** [comment]
Even if we do the unescape while saving csv to the blob
