### ISSUE TITLE
[Bug] Templating hosts selection brackets issue 

### ISSUE THREAD

**Issue by jhon287** [grafana/grafana#8519]
**Version:** Grafana v4.3.2 (commit: ed4d170)
**Datasource:** Graphite
**OS:** CentOS 7

I'm using templating to automate graphs generation.

I created a variable that get all my servers: `icinga2.*`
And then I use that variable to get all application services: `icinga2.$server.services.*`

This is working quite well but...

When I select first only 1 host, I'm getting all the metrics.
After I select 2 hosts, all is working well again.
If I reselect only 1 host again this is not working.
Moreover, if I save the dashboard with only 1 host selected and refresh the page is working again...

Do you have an idea why? It seem to be a bug...

```
/var/log/graphite-web/info.log
Fri Jun 02 11:54:12 2017 :: find_view query=icinga2.* local_only=0 matches=394
Fri Jun 02 11:54:12 2017 :: find_view query=icinga2.fx-a_tunz_com.services.* local_only=0 matches=7
Fri Jun 02 11:54:30 2017 :: find_view query=icinga2.{fx-a_tunz_com,fx-b_tunz_com}.services.* local_only=0 matches=14
Fri Jun 02 11:54:46 2017 :: find_view query=icinga2.{fx-a_tunz_com}.services.* local_only=0 matches=0
Fri Jun 02 11:57:30 2017 :: find_view query=icinga2.* local_only=0 matches=394
Fri Jun 02 11:57:30 2017 :: find_view query=icinga2.fx-a_tunz_com.services.* local_only=0 matches=7
```

**Comment by torkelo** [comment]
What version of Graphite are you running? Can be the bug that older version of Graphiite is not handling glob expressions with a single value. try upgrading Graphite

**Comment by jhon287** [comment]
```
[root@graphite graphite-web]# rpm -qa | grep graphite
graphite-web-0.9.16-1.el7.noarch
```

**Comment by torkelo** [comment]
try upgrading to Graphite 1.x

**Comment by torkelo** [comment]
upgrading Graphite should fix this so closing
