### ISSUE TITLE
Hardware specification guide for grafana.

### ISSUE THREAD

**Issue by munnancs** [grafana/grafana#8520]
Hi everyone I am new to grafana. I got a project to implement grafana using influxdb as time series database and telegraf as collector. The production enviornment which I am going to implement this is a moderate load enviornment. So as per the influxdb hardware sizing guide th specs which for my Virtual machine is 8 cpu and 32 GB RAM . I am planning to install grafana , influxdb and my collector on single virtual machine (redhat). My concern is how it will affect the performance. Do I have to install grafana on another virtual machine with other hardware specification? Is there any hardware specification guide for grafana ? I need the grafana experts opinion for this.

**Comment by torkelo** [comment]
You can run grafana on the same machine, Grafana does not use a lot of resources, very light use of ram and cpu (minimum 255 mb ram, 1 cpu)
