### ISSUE TITLE
Explore/logsInfiniteScrolling:  UI slowdown/freeze when using show/hide fields actions

### ISSUE THREAD

**Issue by ddelemeny** [grafana/grafana#85202]
### What happened?

Users of our plugin reported slowdown/freezes of the UI when using or hovering the field action buttons. Original information is scarce : quickwit-oss/quickwit-datasource#105

I managed to reproduce a similar situation (not sure if the same) using the showField action, with the `infiniteScrolling` feature turned on.

Reproduced on :  Grafana v10.4.0 (03f502a94d) | Grafana v10.4.2 (7cc6c7b5c4)
On Explore, with our datasource plugin https://github.com/quickwit-oss/quickwit-datasource

```
[feature_toggles]
logsInfiniteScrolling=true
```

![grafana-explore-freeze](https://github.com/grafana/grafana/assets/1690574/2d37f56d-cfdd-4abe-a0ee-9ffce9d41dcd)

Firefox profiling shows React getting stuck : 
[Firefox 2024-03-26 11.01 profile.json.gz](https://github.com/grafana/grafana/files/14761773/Firefox.2024-03-26.11.01.profile.json.gz)
The frontend build traces are obfuscated here. Tried using `app_mode=development` without success

AFAICT, the problem arises even if our QueryEditor component is commented out. I don't see anything triggered on our datasource when it starts malfunctioning.

I couldn't reproduce it with the infiniteScrolling toggle turned off, but I'm not sure if this is a hard condition or not.

Initial reporter's config unknown. I'll add to this issue if I get new relevant info.

### What did you expect to happen?

UI should not freeze.

### Did this work before?

-

### How do we reproduce it?

1. Use  `quickwit-datasource` and infinite scrolling feature
2. On explore, fiddle with the show/hide field feature. Maybe load more results.
3. Sometimes there's a noticeable pause in the reflow, sometimes the UI just hangs and will not recover.

### Environment (with versions)?

Grafana: Grafana v10.4.0 (03f502a94d) | Grafana v10.4.2 (7cc6c7b5c4)
OS: Ubuntu 23.10
Browser: Firefox 123.0.1

### Grafana platform?

Docker

### Datasource(s)?

quickwit-datasource v0.4.x

**Comment by gelicia** [comment]
Tried this with Loki on Explore in Grafana 11 with logsInfiniteScrolling and wasn't able to replicate it. Successfully filtered out/displayed only certain labels and scrolled around the infinite logs and didn't notice any slow down or freezing in either Chrome or FF.

**Comment by gelicia** [comment]
I chatted with the logs team about this, they pointed to https://github.com/grafana/grafana/pull/84407 as a possible fix for this issue. It seems to be an issue for larger/more complicated logs as some of the operations end up automatically processing each line. I'm passing this over to them, but it might be the case that updating to Grafana 11 when available will help.

**Comment by ddelemeny** [comment]
I tested with Grafana 11, can't reproduce the issue. Linked PR case seems consistent with what I've seen. I'll leave the issue on our side open until 11 is out.
 
 Thank you @gelicia !
