### ISSUE TITLE
Delete dashboard is missing from settings dropdown on new dashboard search Nav 

### ISSUE THREAD

**Issue by bulletfactory** [grafana/grafana#8521]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
   Master
- What datasource are you using?
   N/A
- What OS are you running grafana on?
   N/A
- What did you do?
   Tried to delete dashboard
- What was the expected result?
   Delete option to be available
- What happened instead?
   Delete seems to be missing
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

Current Version on play.grafana.org
<img width="629" alt="screenshot 2017-06-02 10 03 14" src="https://cloud.githubusercontent.com/assets/1950595/26729203/d7ff3660-477a-11e7-955f-36ecd3053b88.png">

Version in Master which seems to be missing the Delete Dashboard option
<img width="592" alt="screenshot 2017-06-02 10 03 47" src="https://cloud.githubusercontent.com/assets/1950595/26729213/e1de5e18-477a-11e7-9389-2eb6d121c1e3.png">

**Comment by MartynKeigher** [comment]
Very odd. I'm running the new 4.3 version, with worldPing and I DO have that functionality on all of the worldPing dashboards...

![image](https://cloud.githubusercontent.com/assets/3298134/26757175/bf7f706e-4879-11e7-9732-75d7ca17166c.png)

**Comment by torkelo** [comment]
missed adding the delete option to the new navbar's dashboard dropdown menu
