### ISSUE TITLE
Security: Grafana is generating traffic that matches OWASP CRS 3.2

### ISSUE THREAD

**Issue by areriklq** [grafana/grafana#85217]
### What happened?

I am using Grafana with a reverse proxy (Caddy) behind Azure Application Gateway. The AAG*s WAF is blocking traffic to Grafana (from Dashboards) due to the traffic matching CRS 3.2 patterns.

Are you aware of this?

Example logs (some data has been edited to remove ID):

Matched
```
"3/26/2024, 3:09:57.000 PM",ApplicationGatewayFirewall,"appgw_0",,,"/grafana/api/datasources/proxy/uid/dc2dda68-d3c0-4883-bdb7-ajdksadksad/_msearch?max_concurrent_shard_requests=5","OWASP CRS","3.2",920420,"Request content type is not allowed by policy",Matched,,"Pattern match ^[^;\s]+; Pattern match ^ Tx:allowed_request_content_type $ at TX:0.","{application/x-ndjson found within [REQUEST_HEADERS:content-type:application/x-ndjson]}","REQUEST-920-PROTOCOL-ENFORCEMENT.conf"
```
Matched
```
"3/26/2024, 3:28:08.000 PM",ApplicationGatewayFirewall,"appgw_0",,,"/grafana/api/dashboards/db/","OWASP CRS","3.2",942440,"SQL Comment Sequence Detected.",Matched,,"Pattern match (?:/\*!?|\*/|[';]--|--[\s\r\n\v\f]|--[^-]*?-|[^&-]#.*?[\s\r\n\v\f]|;?\x00) at ARGS.","{--  found within [ARGS:dashboard.annotations.list.datasource.uid:-- Grafana --]}","REQUEST-942-APPLICATION-ATTACK-SQLI.conf"
```
Blocked
```
"3/26/2024, 3:07:52.000 PM",ApplicationGatewayFirewall,"appgw_0",,,"/grafana/api/datasources/proxy/uid/dc2dda68-d3c0-4883-bdb7-hasudhkuadhusakd/_msearch?max_concurrent_shard_requests=5","OWASP CRS","3.2",949110,"Inbound Anomaly Score Exceeded (Total Score: 5)",Blocked,,"Greater and Equal to Tx:inbound_anomaly_score_threshold at TX:anomaly_score.",,"REQUEST-949-BLOCKING-EVALUATION.conf"
```

### What did you expect to happen?

The traffic should preferably not match , but definitely not be blocked by the WAF.

### Did this work before?

N/A

### How do we reproduce it?

1. Spin up Grafana behind an Azure Application Gateway
2. Enable the AAG's WAF in prevention mode.
3. Note how, legimate, Grafana traffic is blocked.

### Environment (with versions)?

Grafana: 9.5.1
OS: Linux
Browser: Chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
Hi @areriklq 
Thank you for reporting this issue

Regarding the two concerns  the CRS WAF configuration:

 According to [this comment](https://github.com/coreruleset/coreruleset/blob/b7ff42b1e6b5b74abbaa5340f45235e1446a5de2/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L892)  , the `allowed_request_content_type` parameter needs an update to include `application/x-ndjson`. There isn't any inherent vulnerability associated with this format; rather, it's a matter of the configuration not permitting it.

[This](https://github.com/coreruleset/coreruleset/blob/b7ff42b1e6b5b74abbaa5340f45235e1446a5de2/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1259) seems to be less specific, and may only be resolved by adjusting the level of caution.

It's important to note that neither of these issues constitutes "attacks," nor do they signify vulnerabilities on their own. It falls on the user to adjust their WAF settings, if feasible, to align with Grafana's intended behavior. The fact that certain requests were blocked doesn't necessarily indicate vulnerability; it's more likely indicative of generating excessive false positives.

The [following article](https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/) might be a good place for you to start (although it is from the context of ModSecurity, its talking about the same underlying rules), and [this page](https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/create-waf-policy-ag) from Microsoft explains how the Azure Application Gateway WAF can be tuned to reduce false positives

Hope it helps!
Closing this issue. Feel free to request reopening it if necessary.

**Comment by areriklq** [comment]
Thanks for taking the time commenting on this.

I am aware of the mitigations needed (thanks anyway, it helps future readers), my intention here was to raise to you that your software is out-of-the-box generating false positives on a major WAF product. I did not expect that, therefore I raised the issue here. I don't expect any further action. Thanks!
