### ISSUE TITLE
[Feature request] Rounded "group by" time intervals

### ISSUE THREAD

**Issue by zkhaled** [grafana/grafana#8522]
I'm using Grafana (v4.2.0) +InfluxDB and one feature which would be nice is to be able to round off the time interval when using a group by or to exclude "incomplete groups". Best explained with an example :)

For example, if I'm viewing data between 12:00 and 12:10 and grouping by 10s then instead of Grafana making a request between something like 12:00:03 and 12:10:03, I want it to make a request between 12:00:00 and 12:09:59. That way, any queries which are displaying count information as in the attachment, are accurate for the time period being shown rather than the user seeing a sudden drop because of an incomplete group being shown. From the example the incomplete group would be from 12:10:00 to 12:10:03 as there's still 7 seconds of data to be added to this group.

![grafana1](https://cloud.githubusercontent.com/assets/4985302/26734322/78f8f918-47b5-11e7-9a8d-ed2b93906901.png)

Or maybe instead it would be easier to just skip incomplete groups? So instead of displaying data for 12:00:03 to 12:10:03, it would display data between 12:00:10 and 12:09:59 to only show complete groups.

Time shifting doesn't help in this case because the shift will include the offset, e.g. if I time shifted by 10s in my example then the period being queried would be 11:59:53 and 12:09:53 so the problem would still exist.

**Comment by torkelo** [comment]
I think this group by rounding needs to be implemented in InfluxDB's group by time feature.  (Graphite has a feature to align group by time intervals)

**Comment by divishkumar** [comment]
Hey @torkelo,

Does this really fall under influxdb's domain ? Technically, influxdb is correctly returning the (grouped by) data for the requested time frame. Now what we really want is to not request the groups that don't have complete data, which means the time frame needs to be adjusted. That seems to fit more within grafana than influxdb?

**Comment by k-bx** [comment]
I wonder if anyone knows if this is possible with AWS CloudWatch Custom Metrics?
