### ISSUE TITLE
Authentication: auth.generic_oauth login problem after upgrade to Grafana > 10 - issue with auth_id user update

### ISSUE THREAD

**Issue by steefenh** [grafana/grafana#85232]
### What happened?

Follow up of https://github.com/grafana/grafana/issues/74154

related to CVE https://github.com/grafana/grafana/issues/70203#issuecomment-1603895013

Upgraded Grafana from 9 to > 10 - try to sign in using before perfectly working and not changed Generic OAuth Login
Users are created via API and just login (no signup) is done using Generic OAuth

I think the issue is that the fallback email lookup is not implemented in user sync hook

```
logger=user.sync t=2024-03-27T08:55:32.588458957+01:00 level=debug msg="Syncing user info" id= update="&{ ***email*** ***login***  123}"
logger=user.sync t=2024-03-27T08:55:32.588745336+01:00 level=error msg="Failed to update user" error="UNIQUE constraint failed: user.email" auth_module=oauth_generic_oauth auth_id=https://***issuer***
logger=authn.service t=2024-03-27T08:55:32.588775621+01:00 level=error msg="Failed to run post auth hook" client=auth.client.generic_oauth id= error="[user.sync.internal] unable to update user"
```

tried to find some related code and found the following involved:

https://github.com/grafana/grafana/blob/ace1cd63013cbb1fc2c451d61b974a30c8ab8758/pkg/services/authn/authnimpl/sync/user_sync.go

	func (s *UserSync) SyncUserHook(ctx context.Context, id *authn.Identity, _ *authn.Request) error {
	if !id.ClientParams.SyncUser {
		return nil
	}

	// Does user exist in the database?
	usr, userAuth, errUserInDB := s.getUser(ctx, id)
	if errUserInDB != nil && !errors.Is(errUserInDB, user.ErrUserNotFound) {
		s.log.FromContext(ctx).Error("Failed to fetch user", "error", errUserInDB, "auth_module", id.AuthenticatedBy, "auth_id", id.AuthID)
		return errSyncUserInternal.Errorf("unable to retrieve user")
	}

	if errors.Is(errUserInDB, user.ErrUserNotFound) {
		if !id.ClientParams.AllowSignUp {
			s.log.FromContext(ctx).Warn("Failed to create user, signup is not allowed for module", "auth_module", id.AuthenticatedBy, "auth_id", id.AuthID)
			return errUserSignupDisabled.Errorf("%w", errSignupNotAllowed)
		}

		// create user
		var errCreate error
		usr, errCreate = s.createUser(ctx, id)
		if errCreate != nil {
			s.log.FromContext(ctx).Error("Failed to create user", "error", errCreate, "auth_module", id.AuthenticatedBy, "auth_id", id.AuthID)
			return errSyncUserInternal.Errorf("unable to create user: %w", errCreate)
		}
	} else {
		// update user
		if errUpdate := s.updateUserAttributes(ctx, usr, id, userAuth); errUpdate != nil {
			s.log.FromContext(ctx).Error("Failed to update user", "error", errUpdate, "auth_module", id.AuthenticatedBy, "auth_id", id.AuthID)
			return errSyncUserInternal.Errorf("unable to update user")
		}
	}

	syncUserToIdentity(usr, id)
	return nil
	
	
	
	
https://github.com/grafana/grafana/blob/main/pkg/services/authn/authnimpl/sync/user_sync.go
	
	
	var userAuth *login.UserAuth
	// Special case for generic oauth: generic oauth does not store authID,
	// so we need to find the user first then check for the userAuth connection by module and userID
	if identity.AuthenticatedBy == login.GenericOAuthModule {
		query := &login.GetAuthInfoQuery{AuthModule: identity.AuthenticatedBy, UserId: usr.ID}
		userAuth, err = s.authInfoService.GetAuthInfo(ctx, query)
		if err != nil && !errors.Is(err, user.ErrUserNotFound) {
			return nil, nil, err
		}
	}

### What did you expect to happen?

working user login based on email lookup instead of auth_id

### Did this work before?

yes using version 9.x.x

### How do we reproduce it?

User Login only working for one user since auth_id (table user_auth) is always the same from IdP (example user_id 461)
If first user login (id 461) happened and entry in table user_auth is created
next user login (different user_id, example id = 123) is failing because the following happens during user login (debugging done)

2nd User successfully authenticates using OAuth 
UserSyncHook in Grafana is triggered, which tries to find user_auth_id in table user_auth - since the same comibination of user_auth and module is returned by OAuth IdP, entry is found with first users user_id (461)
Then the sync hook tries to update first users user entry (user_id 461) with information (mail and user login) from user id 123, which fails because of UNIQUE constraint issue in DB (this is expected)

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by duj4** [comment]
Any update on this issue?

**Comment by kalleep** [comment]
Since grafana grafana 10 we don't perform lookups by email. This will block logins if you user is not correctly mapped with an unique `auth_id`. For a long time generic oauth did not set this id but was changes a while ago and will be mandatory in a future release. But there is still and escape hatch, you can set `oauth_allow_insecure_email_lookup = true`.

**Comment by steefenh** [comment]
> @steefenh Which identity provider do you use? The `auth_id` should be a unique id (`sub` claim in the JWT token).

Using F5 oauth provider.
Now reconfigured it to provide a unique auth_id.
Everything working fine again.

**Comment by steefenh** [comment]
> Since grafana grafana 10 we don't perform lookups by email. This will block logins if you user is not correctly mapped with an unique `auth_id`. For a long time generic oauth did not set this id but was changes a while ago and will be mandatory in a future release. But there is still and escape hatch, you can set `oauth_allow_insecure_email_lookup = true`.

Right... what I am saying is: the parameter `oauth_allow_insecure_email_lookup = true ' is not working. Still the auth_id is required to be unique.

However...I fixed my issue now and reconfigured the F5 oauth provider.

Thanks for the analysis.
