### ISSUE TITLE
Share internally option (old link feature)

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#85241]
**Before**
<img width="737" alt="Screenshot 2024-03-27 at 12 23 32" src="https://github.com/grafana/grafana/assets/51436795/0eb5d158-2cc8-4d9d-b1ff-96f8f8d99236">

**Now**
<img width="285" alt="Screenshot 2024-03-27 at 12 24 01" src="https://github.com/grafana/grafana/assets/51436795/0d02e451-dfec-4b63-b45b-e1bb0d714c43">
<img width="477" alt="Screenshot 2024-03-27 at 12 24 32" src="https://github.com/grafana/grafana/assets/51436795/df0b7388-2053-4c3a-8cb9-709e882984b9">

**We are changing with this task:**

- Change the design of the `button` component to be a `Inside ButtonGroup` 
- Leave the `time range` locked by default
- Remove the `theme` config
- `Shorten URL` active by default

**Resources**
[Figma](https://www.figma.com/file/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?type=design&node-id=3118-42711&mode=design)
```[tasklist]
### Tasks
- [x] Create Design
- [ ] Add tests
```

**Comment by natydej** [comment]
Dependency in order to use the shorten link by default
https://github.com/grafana/grafana/issues/77829

**Comment by juanicabanas** [comment]
We're moving forward to another approach https://github.com/grafana/grafana/issues/89143
