### ISSUE TITLE
[BUG] Alert Emails are not going through, Error: getsockopt: connection refused" changing state

### ISSUE THREAD

**Issue by mananpreetsingh** [grafana/grafana#8525]
- What Grafana version are you using?
Grafana v4.3.1 (commit: befc15c)

- What datasource are you using?
Graphite (hopsoft/graphite-statsd image)

- What OS are you running grafana on?
using docker image grafana/grafana

- What did you do?
Dashboard is working fine, I have setup gmail smtp settings as below:

#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = smtp.gmail.com:465    # Also tried with 587 and 25
user = my-email@gmail.com
### If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password = my email-password
;cert_file =
;key_file =
;skip_verify = false
;from_address = admin@grafana-test.com
;from_name = Grafana

[emails]
;welcome_email_on_sign_up = false
###############################################

 
- What was the expected result?

If I send test notification its going through fine. I can receive email. but Once I setup alert I see below mentioned error and not getting emails. Is there any setting that needs to be done in order to make it work ?

- What happened instead?

Error that I am getting:

t=2017-06-02T17:58:12+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalHandler ruleId=1 name="Alert Test Panel alert" error="tsdb.HandleRequest() error Post http://localhost:80/render: dial tcp [::1]:80: getsockopt: connection refused" changing state to=alerting

Here is the screenshot:

<img width="968" alt="screen shot 2017-06-02 at 2 52 56 pm" src="https://cloud.githubusercontent.com/assets/27379172/26740394/5f0f0d7e-47a3-11e7-8665-b326c99f2066.png">

**Comment by torkelo** [comment]
your graphite server does not seem to be accessible from grafana-server with the url `t http://localhost:80/render`  

Also it looks like your alert query is using template variables which is not supported.

**Comment by mananpreetsingh** [comment]
@Torkelo Is Not that's just warning message  regarding template variable? 

I am using template for Dashboard to check the disk and ram for multiple servers. I didn't mention any template variable in alert query,  So does this mean templating Dashboard does not have alert functionality?

**Comment by mananpreetsingh** [comment]
Also I can access graphite render url  via browser, how do I know grafana is Not able to access it?

Grafana can access data's our experience though.

**Comment by torkelo** [comment]
You can use templating and alerts on same dashboard, just not in alerting query. 

Have you tried using the localhost URL for your graphite from the same server grafana is running on?

**Comment by mananpreetsingh** [comment]
Any other way to getting alerts if I am using templating dashboard ?

Thats the whole purpose of templating dashboard so that it will generate alerts whenever it will cross the servers threshold. So I am using templating dashboard for server names how I am suppose to create alerts so that I don't have to specify individual server every-time new server is created ?

**Comment by WaverlyAW** [comment]
I am in the same boat, able to set up server SMTP settings fine but "Test Rule" fails. I haven't found any useful info about building a dashboard without templating so I am unsure what to change/setup.

**Comment by torkelo** [comment]
>  useful info about building a dashboard without templating.

Just remove the template variable from the query and replace it with a wildcard or a specific tag/metic that you want to alert on.

**Comment by WaverlyAW** [comment]
Okay, I believe I have that set up (Thanks for the quick response) A new error has responded that connection timeout occurred. 

tsdb.HandleRequest() error Post http://34.212.81.194/render: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Grafana is running inside a docker container on ec2 AWS instance. Are other changes required other then SMTP settings on grafana.ini? Until now I haven't run into any connection issues and my notification channel has sent test emails fine.

**Comment by torkelo** [comment]
looks like grafana-server cannot access your graphite server at http://34.212.81.194/render

**Comment by WaverlyAW** [comment]
Thank you for the help. This may seem like a dumb question but how can access be failing if all the data is coming through into dashboards? Also I do not believe I set the Public IP anywhere in grafana. The IP is correct and it does take me to a graphite web interface. All features of grafana seem to be working and receiving data as expected except for the alert Test Rule. Thanks for any suggestions on how to get this working!

**Comment by torkelo** [comment]
@WaverlyAW 

just remove the template variable from your query and the Test rule will work

**Comment by WaverlyAW** [comment]
Removing the template variables is not an issue at this point as I am just running a test dashboard with basic packets received. I have been looking through other grafana config files and my only assumption is that it is a docker or graphite config issue. I will continue to debug, thanks in advance for any other ideas. 
![packetstest](https://user-images.githubusercontent.com/30242415/28328368-fc01bb82-6bab-11e7-9a9e-6256c16aaf86.PNG)

![alerttestrule](https://user-images.githubusercontent.com/30242415/28328377-02f082f2-6bac-11e7-8a15-75f41dfa842c.PNG)

**Comment by torkelo** [comment]
looks like a networking issue, graphite render request times out

**Comment by CoderXingZhang** [comment]
@mananpreetsingh   the problem is docker !! I guess your grafana and your influxDb is at different host,   As you use docker , it lookfor 'localhost:80' in grafana ; I chang this to my 'Docker host ip' , everything goes right.....

**Comment by WaverlyAW** [comment]
It was docker, configured the data source differently and that made the fix. The overall tool has been working great since!

**Comment by SimingLiu** [comment]
yeah, I got the same error. 
```code
firing:true
state:"pending"
conditionEvals:" = true"
timeMs:"0.899ms"
error:"tsdb.HandleRequest() error Get http://www.mydome.com:9090/api/v1/query_range?end=2019-07-10T16%3A58%3A49.158695518%2B08%3A00&query=avg+%281+-+irate%28node_cpu_seconds_total%7Bmode%3D%27idle%27%2Cinstance%3D%22172.16.0.110%3A9100%22%7D%5B1m%5D%29%29+%2A+100&start=2019-07-10T16%3A53%3A49.158695518%2B08%3A00&step=30.000: dial tcp 172.16.0.140:9090: i/o timeout"
```
my environments as following:
 1. I have two LAN hosts, they are `172.16.0.140` and `172.16.0.110`
 2. My `Grafana`  and `Prometheus` located at `172.16.0.110`
 3. My `node_exporter`  located at both `172.16.0.110` and `172.16.0.140`
 4. Ping `www.mydome.com` on host `172.16.0.110` get ip `172.16.0.140`
 5. Browser visit `http://www.mydome.com` reroutes to `172.16.0.140`
     Browser visit `http://www.mydome.com:9090` reroutes to `172.16.0.110`

So, when I click `test rule`, ` "dial tcp 172.16.0.140:9090: i/o timeout"`returned . Actually, it should access ` 172.16.0.110:9090`

**Comment by saurabhsingh121** [comment]
I had the same issue. For me I ran Grafana and Prometheus for Nodejs Application monitoring. I used docker-compose approach to run all the applications. I guess this was the issue related to docker networking.
