### ISSUE TITLE
[Bug] Grouping by terms containing data with hyphen not working

### ISSUE THREAD

**Issue by jkrech17** [grafana/grafana#8526]
Please include this information:
- What Grafana version are you using? **Grafana v4.1.2 (commit: v4.1.2)**
- What datasource are you using? **Elasticsearch**
- What OS are you running grafana on? **Centos 6**

We are currently trying to create a graph with Elasticsearch datasource using a query similar to this:
Query: ServiceName:blah, Metrics: (Percentiles(Duration), Group by: Terms (Id)

Id has hyphens in the name abc-123, dcf-567. In the graph, it is separating each as:
abc
123
dcf
567

The field is not analyzed in Elasticsearch

```
Id: {
type: "string",
norms: {
enabled: false
},
fields: {
raw: {
type: "string",
index: "not_analyzed",
ignore_above: 256
}
}
},

```

I guess this is a bug or am I missing something here?

**Comment by pruthviraj1991** [comment]
Hi,

Am opening an old ticket but may I know what was the resolution for this?
