### ISSUE TITLE
[Feature request] show series names in heatmap tooltips

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#8529]
It would be really useful to show series names when you hover over a rectangle of a heatmap panel. Would it be possible to add an option to do this?

- What Grafana version are you using? 
4.3

- What datasource are you using? 
graphite

- What OS are you running grafana on? 
RHEL6.4

- What did you do? 
Plot some data on the heatmap panel.

- What was the expected result?
Hovering over a rectangle should show the series in the bucket.

- What happened instead? 
Only the bucket count and range are displayed.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
