### ISSUE TITLE
[Feature Request] Single Stat Gauge to show result of a formula from 2 elastic search fields

### ISSUE THREAD

**Issue by kbsivacse** [grafana/grafana#8530]
Please include this information:
- What Grafana version are you using? 4.3
- What datasource are you using? Elastic Search
- What OS are you running grafana on? Ubuntu 14.1
- What did you do? Tried applying Query to pull 2 series data from elastic search and show aggregated value in percentage
- What was the expected result? Percentage number ((series-1/series-2)*100)
- What happened instead? Could not apply desired formula
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Sadly Elasticsearch does not support sub queries or operations on query results.
