### ISSUE TITLE
Cmd + H doesn’t hide the browser window on macos

### ISSUE THREAD

**Issue by sergeysolovev** [grafana/grafana#85321]
### What happened?

I use `Cmd + H` keyboard shortcut to hide windows on macos. Grafana intercepts it and shows me the shortcuts popup. Would love to have this disabled!

### What did you expect to happen?

I expected the operating system native shortcut to keep working as it should

### Did this work before?

Yes, I don’t remember the exact version, but it was introduced recently

### How do we reproduce it?

Open any dashboard, press `Cmd + H`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d3ce857c0e)
OS: Macos Sonoma 14.2.1 (23C71)
Browser: Google Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by eledobleefe** [comment]
This might be related to the following changes: [Keybindings: Change 'h' to 'mod+h' to open help modal](https://github.com/grafana/grafana/pull/82253).
