### ISSUE TITLE
Mysql source BUG? sql: int64: invalid syntax label:"datasource: MySQL" 

### ISSUE THREAD

**Issue by roysbike** [grafana/grafana#8534]
Read before posting: 
- 4.3.1-1
- mysql
- centos 7
- use plugin table list

SELECT  substring_index(`clid`,"<",+1) as clid,COUNT(`calldate`) AS total_calls, SEC_TO_TIME(SUM(TIME_TO_SEC(duration))) AS duration  FROM  `cdr` WHERE clid LIKE '"Park%' AND (`calldate` >='2017-05-01 00:00:00' AND `calldate` <='2017-05-31 23:59:59') and duration >=14;

+------------------+-------------+----------+
| clid             | total_calls | duration |
+------------------+-------------+----------+
| "Par"  |        1484 | 23:27:05 |
+------------------+-------------+----------+

sql: Scan error on column index 2: converting driver.Value type []uint8 ("23:27:05") to a int64: invalid syntax

label:"datasource: MySQL" 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Fixed in 4.3.2 :)

**Comment by roysbike** [comment]
I upgrade to  Grafana v4.3.2 (commit: ed4d170.

Query sql 
SELECT  substring_index(`clid`,"<",+1) as clid,COUNT(`calldate`) AS total_calls, SEC_TO_TIME(SUM(TIME_TO_SEC(duration))) AS duration  FROM  `cdr` WHERE clid LIKE '"Tula_parkovk%' AND (`calldate` >='2017-05-01 00:00:00' AND `calldate` <='2017-05-31 23:59:59') and duration >=14;


The problem continues . 
sql: Scan error on column index 2: converting driver.Value type []uint8 ("23:27:05") to a int64: invalid syntax
<img width="1672" alt="2017-06-04 13 07 53" src="https://cloud.githubusercontent.com/assets/2388223/26760637/d975de24-4926-11e7-9ba8-d9136fbe8c20.png">
