### ISSUE TITLE
Connection timeout if I reboot the client

### ISSUE THREAD

**Issue by hiscal2015** [grafana/grafana#8535]
Hi, all

I'm running grafana with Kubernetes, several days before I raised an issue here:
https://github.com/rancher/rancher/issues/8885

Issue description:
Grafana was running as Kubernetes pod, and use port 30000 as nodeport, after grafana container running, I can curl port 30000 successfully from client1, but if I rebooted the client1, then connection from client1 to the host hosting grafana will be time out.

I thought it was a Kubernetes issue, but after some testing, other applications do not have such issue, so I guess is it possible the session of grafana is the cause? (maybe not, because I just curl without login)

Current setting:
Grafana version: 4.2.0
Session use memory and keeps others default. The thing I can't understand is, why clients will be failed to connect to grafana after rebooted?

Thanks for the help.

**Comment by torkelo** [comment]
not sure either, we are running our hosted grafana service on Kubernetes with no timeout issues. And many run grafana in docker or in kubernetes without issue. 

Maybe a network issue with your kubernetes deployment setup? Please post questions to the mailing list. GitHub is for bug reports or feature requests, production support issues are handled on the community site.
