### ISSUE TITLE
PostgreSQL data source: "ERROR: cannot insert multiple commands into a prepared statement (SQLSTATE 42601)"

### ISSUE THREAD

**Issue by KholdStare** [grafana/grafana#85388]
### What happened?

Recently when our Grafana cloud instance upgraded, we started seeing an error on some of our dashboards that used the PostgreSQL data source:

```
db query error: ERROR: cannot insert multiple commands into a prepared statement (SQLSTATE 42601)
(Trace ID: 3eeeb71810951dfa4de1818ea2b3496e)
```

After some tinkering, it comes down to having multiple statements in the query. e.g.

```
set search_path = my_schema;
set join_collapse_limit = 30;
select *
-- ... etc ...
```

Not sure why a prepared statement is required in this case.

### What did you expect to happen?

All of our existing queries to keep working.

### Did this work before?

Unsure which Grafana version that worked, but it was working as recently as 2 weeks ago.

### How do we reproduce it?

1. Create a SQL query with several statements, using the PostgreSQL data source
2. Run the query!

### Environment (with versions)?

Grafana: v11.0.0-68643 (c33bc819bc)
OS: Windows
Browser: Any (browser doesn't affect this issue)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

PostgreSQL

**Comment by gabor** [comment]
hi @KholdStare , thank you for reporting this, i can confirm this is indeed happening, we are looking into this ( we adjusted something related to postgres, to fix an unrelated bug, and it's now having this effect). 

are you running multiple `SELECT` statements too? or is it multiple `set` commands, and a single `SELECT` at the end?

**Comment by KholdStare** [comment]
Thank you for looking into this. We don't use multiple selects, just set statements.

**Comment by gabor** [comment]
hi @KholdStare , we fixed this in https://github.com/grafana/grafana/pull/85509 .

(we had to revert the improvement we did)
