### ISSUE TITLE
can not query resource in azure resource graph

### ISSUE THREAD

**Issue by bestvit999** [grafana/grafana#85399]
### What happened?

can not query resource in azure resource graph, return "The name 'resources' does not refer to any known table, tabular variable or function.(KS204)"
![Xnip2024-03-29_17-27-33](https://github.com/grafana/grafana/assets/35884539/0cacac9e-253a-4307-8d2f-f7eac75e2252)

### What did you expect to happen?

In Azure portal it works
![Xnip2024-03-29_17-15-36](https://github.com/grafana/grafana/assets/35884539/ef639f3c-a8f6-4796-97fb-f5dbfb6c558c)

### Did this work before?

NA

### How do we reproduce it?

1. add data resources "Azure Monitor", Azure Cloud set to "Azure"
2. explore data resources by "Azure Resource Graph"
3. search expression
```
resources
| where type == 'microsoft.network/trafficmanagerprofiles'
| count
```

### Environment (with versions)?

Grafana: Docker grafana/grafana:latest (sha256:753bbb971071480d6630d3aa0d55345188c02f39456664f67c1ea443593638d0)
OS: Ubuntu 18.04.4 LTS
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Azure Monitor

**Comment by BP-vismaNmbrs** [comment]
Stumble on this one but no answer.
