### ISSUE TITLE
[Feature request] Value range restriction and display in heatmap panel

### ISSUE THREAD

**Issue by anttirt** [grafana/grafana#8539]
- What Grafana version are you using?
4.3.2
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Linux
- What did you do?
Create heatmap panel
- What was the expected result?
Ability to view / control value range
- What happened instead?
No view / control available

The new heatmap panel is awesome but one thing that would significantly improve its value is the ability to view and restrict the value range based on which the heatmap cell colors are chosen.

The two panels in the attached picture have identical source data, but in the left one outliers have been "clamped" to a max via a filthy hack (using [this function](http://www.wolframalpha.com/input/?i=1%2F%28%281%2Fx%29+%2B+x%2F100000%29+%2B+x*x%2F10000+-+x*x*x%2F28000000+between+0+and+1800) in the query as InfluxDB doesn't support a clamp function). As you can see the left one reveals patterns that are obscured in the right one due to a few huge outliers. (Note that this is using the "Time series buckets" view with pre-bucketed data.)

![image](https://cloud.githubusercontent.com/assets/281067/26787490/de687b8e-4a12-11e7-9ddc-9667546f3fbf.png)

It would be ideal if we could set, from grafana, a min and max value for the *coloring* of a heatmap cell; all values below min / above max would be counted as the "coldest" / "hottest" color, respectively. However, individual cell tooltips would still show the actual underlying value even if it is a significant outlier. One step further would be if such outlier cells could be highlighted somehow (such as with a simple border highlight).

This would also allow normalizing and visually comparing several panels that happen to have a different range of values at a given time.

To ease quick understanding of the heatmap data, it would also be desirable to see a legend of what numeric values different colors on the spectrum represent, say a three-point (cold, middle, hot) legend below the actual heatmap.

**Comment by jan11011977** [comment]
+1. I would like to have this feature too. Without it, the heatmap colours don't have consistent meaning (e.g. red = bad, green = good).

**Comment by alexanderzobnin** [comment]
@bobrik there's Color scale option which works with _Spectrum_ mode (seems, you use _Opacity_). Set Min value to negative in order to expand color scale and make low values more visible.

![screenshot from 2018-05-01 10-43-44](https://user-images.githubusercontent.com/4932851/39465621-fdc9de0a-4d2c-11e8-8713-1d93de1d2a71.png)

**Comment by alexanderzobnin** [comment]
@torkelo since this was merged, should we close this issue? Seems, Color scale doesn't work in Opacity mode, I can open another issue for this bug.

**Comment by alexanderzobnin** [comment]
Reminder: if Min value is negative, color legend should have 0 as a minimum anyway.

**Comment by bobrik** [comment]
Opacity:

![image](https://user-images.githubusercontent.com/89186/39479991-c0e03d4c-4d1b-11e8-8a09-91a4dc55ab8e.png)

Spectrum:

![image](https://user-images.githubusercontent.com/89186/39480025-d50e8e4a-4d1b-11e8-9153-88a302970040.png)

@alexanderzobnin, how do I remove background with zero values?

**Comment by alexanderzobnin** [comment]
You can't. Please, open an issue for this feature request.
