### ISSUE TITLE
I want to use template variables to affect display styles, display styles overrides and/or metric visibility

### ISSUE THREAD

**Issue by caguro** [grafana/grafana#854]
We do have some graphs with stacked series.
Earlier we had separate graphs with the same series summarized and time shifted for "Yesterday" and "Last week".

But now when you can use display style overrides for series, I was able to merge the two graphs by disable stacking for the time shifted, summarized series and to just show lines without fill for "Yesterday" and "Last week".

Saves a lot of space.

I want to be able to use true/false/value template variables to be able to affect style overrides.

I also want to be able to control a series visibility by switching the series show/hide with variables in a similar way.

**Comment by biancalana** [comment]
+1
