### ISSUE TITLE
Search does not handle LIMIT properly or TAG filtering for filesystem dashboards - for filesystem dashboards

### ISSUE THREAD

**Issue by ncabatoff** [grafana/grafana#8541]
This bug describes the same problem as #3623 but is specific to the JsonDashIndex, i.e. the filesystem-backed dashboards that aren't stored in a relational database.  Ultimately it's the same problem in both cases (limit enforced prior to doing tag filtering) but there are different code paths involved.

The problem manifests in my case when I have >100 dashboards, and I click on a dashboard link pulldown with tags.  Because JsonDashIndex first limits to 100, then checks for which tags match, I sometimes get fewer items in my pulldown than there are dashboards with matching tags.

**Comment by torkelo** [comment]
PR?

**Comment by torkelo** [comment]
this is not relevant anymore
