### ISSUE TITLE
When connected to proxy networks, Grafana does not display the dashboards.

### ISSUE THREAD

**Issue by vandanajp333** [grafana/grafana#8543]
While choosing the data source for ElasticSearch,I see a direct connect option or connect it via proxy whereas it is not present for Cloudwatch. When connected to proxy networks, Grafana does not display the dashboards. Tried setting proxy for windows in custom.ini file but it doesnt help. Request for a solution.

Please include this information:
- What Grafana version are you using?
Grafana 4.3.1
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
Windows7
- What did you do?
Tried setting proxy in custom.ini file
- What was the expected result?
Grafana should bypass proxy and show the dashboard for various CloudWatch metrics
- What happened instead?
A black screen was displayed
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Cloudwatch is always accessed from the same server as you run grafana on. There is no direct or proxy option as it can only be accessed via grafana-server, not directly from your browser as the aws credentials and auth is done by grafana-server

http://docs.grafana.org/features/datasources/cloudwatch/#adding-the-data-source-to-grafana

**Comment by vandanajp333** [comment]
Agree. When connected to proxy networks, Grafana does not display the dashboards. Tried setting Env variables also in Windows. Request you to help on how to view dashboards when connected to a corporate proxy network.
