### ISSUE TITLE
[Bug] error when ldap with tls are used

### ISSUE THREAD

**Issue by pytker** [grafana/grafana#8545]
- What Grafana version are you using?
Grafana v4.2.0 (commit: 349f3eb)

- What datasource are you using?
elasticsearch and prometheus

- What OS are you running grafana on?
Centos 6.8  x64

- What did you do?
Trying to setup auth via ldap with tls

- What was the expected result?
login to grafana with ad account

- What happened instead?
error:

lvl=eror msg="Request error" logger=context userId=0 orgId=0 uname= error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:489 (0x42f00f)\n/usr/local/go/src/runtime/panic.go:63 (0x42debe)\n/usr/local/go/src/runtime/signal_unix.go:290 (0x4441ef)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-ldap/ldap/conn.go:182 (0xa0fe58)\n/go/src/github.com/grafana/grafana/pkg/login/ldap.go:74 (0xa33d46)\n/go/src/github.com/grafana/grafana/pkg/login/ldap.go:93 (0xa342e8)\n/go/src/github.com/grafana/grafana/pkg/login/auth.go:37 (0xa33594)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/pkg/bus/bus.go:73 (0x86fd3e)\n/go/src/github.com/grafana/grafana/pkg/bus/bus.go:154 (0x870b19)\n/go/src/github.com/grafana/grafana/pkg/api/login.go:106 (0xc7cbb4)\n/usr/local/go/src/runtime/asm_amd64.s:515 (0x4594b8)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0xc9b08c)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:113 (0x776692)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:104 (0x7765b6)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:14 (0xa92a77)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:113 (0x776692)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:104 (0x7765b6)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:79 (0xa92cbb)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:113 (0x776692)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:104 (0x7765b6)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xa929e1)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:113 (0x776692)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:104 (0x7765b6)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xa90882)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x459438)\n/usr/local/go/src/reflect/value.go:434 (0x4aa01f)\n/usr/local/go/src/reflect/value.go:302 (0x4a95e4)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:117 (0x759104)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:113 (0x776692)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:184 (0x786829)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:286 (0x780dbd)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:175 (0x77a58c)\n/usr/local/go/src/net/http/server.go:2568 (0x6f0df2)\n/usr/local/go/src/net/http/server.go:3088 (0x6f27f3)\n<autogenerated>:312 (0x717714)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:307 (0x70ec9d)\n/usr/local/go/src/net/http/h2_bundle.go:4599 (0x6c78b9)\n/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45bbd1)\n"

ldap.toml

```
host = "xxx"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if ldap server supports TLS
use_ssl = true
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = true
# set to true if you want to skip ssl cert validation
ssl_skip_verify = true
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = /path/to/certificate.crt

```

**Comment by torkelo** [comment]
strange, no other reports on failing ldap & tls

**Comment by torkelo** [comment]
what ldap are you using? Config? self sign cert?

**Comment by pytker** [comment]
active directory, other information I will try to find out. Ldap config without tls work fine.

**Comment by torkelo** [comment]
try changing start_tls to false

**Comment by pytker** [comment]
Its work. I thought that I already did this. Thank you.

**Comment by sagiru** [comment]
Hi, we have the same problem. We switched from ldap to ldaps and got exactly the same error. After debugging and try & error with the params start_tls=false it's (re)working.
