### ISSUE TITLE
Docs: Describe org roles & what they mean (Editor, Read Only Editor, Admin, Viewer)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8546]

**Comment by tpoindessous** [comment]
Hi

Until this task is completed, can you please describe what does each role ? Thanks !

In organisation : 
- Admin : can add datasources, manages users in organization, modifies organization details and options
- Editor : can (create?)/modify dashboard. ??? 
- Read Only Editor : ??? 
- Viewer : can only view dashboard

Thanks !

**Comment by daniellee** [comment]
Readonly editor was created for the demo site. It is the viewer role with the added ability to open the edit mode of a panel. This allows the user to look at the query behind a panel and play around with queries but not to save anything.

**Comment by torkelo** [comment]
this has been done :)
