### ISSUE TITLE
Tempo: Always use time range even if timeShiftEnabled is false

### ISSUE THREAD

**Issue by ogxd** [grafana/grafana#85476]
# Context

Grafana Tempo [does not use the dashboard time range](https://github.com/grafana/grafana/blob/618cf8e5a103b0cf14c1ed9202b0c36b69d3564a/public/app/plugins/datasource/tempo/datasource.ts#L660) when querying by trace ID if `timeShiftEnabled` is `false` (default datasource parameter value). Whether this is by design or not, this behavior leads to the following problems:  

### Performance
When querying a trace without specifying start/end times, Tempo will look into all Parquet blocks (see [discussion](https://github.com/grafana/tempo/discussions/3517)). Not only is it slow (our Tempo querier pods often go OOM because of such queries), but it also led in our experience to extreme egress costs (using Grafana open-source). 
> `end` = (unix epoch seconds) Optional. Along with `start` define a time range from which traces should be returned. **Providing both start and end will include blocks for the specified time range only**.  

<img width="400" alt="image" src="https://github.com/grafana/grafana/assets/12692438/c042bdfc-234b-4d16-b564-06dabdebae71">. 
*Max memory usage for a querier pod receiving no more than ~10 "trace by id" queries per hour. Db has 2 weeks retention and ingests only about 10 spans/s*

### Coherence
I am guessing it was done this way because a trace ID is unique and should not be affected by time ranges. However, this is not the case when querying by trace ID in Grafana Tempo. Querying using TraceQL does use the time ranges, thus it feels odd that time ranges are ignored when querying by trace ID, especially when there is an actual time range shown in the UI. Myself and other users had to learn about this behavior by inspecting the browser console while investigating performance issues. Plus, when opening a trace from a list of traces queries from trace QL, those traces are already filtered by the time range, so opening any of these traces will work as the time range is the same.  
On top of this, the [documentation](https://grafana.com/docs/tempo/latest/using-tempo/api/#query-trace) does not mention this behavior, and we only found out by looking at the code that setting `timeShiftEnabled` to `true` along with a `spanStartTimeShift` of `0` would end up having the time range applied to the query. The name of that setting does not convey its purpose, or rather it currently has two purposes.

# Solutions

There are two solutions that I can think of to address this issue:
- **Option 1**: Always set the time range. This way there is no performance issue possible and `timeShiftEnabled` just does what it says: enable time shifting.
- **Option 2**: Rename `timeShiftEnabled` to `useTimeRangeForTraceIdQueries` or something similar, and keep `spanStartTimeShift` as a separate setting (usable even when `useTimeRangeForTraceIdQueries` is `false`).

Here I am proposing [a pull request](https://github.com/grafana/grafana/pull/85477) for Option 1, which I think is the most straightforward solution and because I could not find a good reason for not using time ranges.

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/grafana/pull/85477
