### ISSUE TITLE
InfluxDB: Flux datasource only loads first 1000 values of the template variable

### ISSUE THREAD

**Issue by cemselman** [grafana/grafana#85499]
### What happened?

Hello,

I am using Grafana 10 and influxdb v2.7.4.

I am using below flux code to create grafana variable for my dashboard.
When i test this on influxdb script editor, i can get 3500 Client_Name variable values.
But when i apply this as a variable and open the variable filter on dashboard the values are truncated. In alphabetic order i can only get until variable names starting with f… Nearly %70 of the variable value Client Names are missing in the filter. 

If i open variable configuring page. If i create variable from influx v2.7.4, i can only see 1000 client names at variable creation page by preview of values section at bottom of page.

I also have same data on influxdb 1.8 version. If i create variable from influx 1.8 with influxql, i can see 3500 client names at variable creation page by preview of values section at bottom of page.

Below shows that 3500 clients are coming in the filter with variable from influxdb 1.8 version with influxql.
![image](https://github.com/grafana/grafana/assets/52052330/15c89b33-64f9-40ea-9ab2-13b547723cfb)

But if i create variable from v2.7.4 influxdb with flux only 1000 clients are shown or searched.
Below shows v2.7.4 same data.
![image](https://github.com/grafana/grafana/assets/52052330/c412c8bd-4273-4777-b7d3-95d51a92f8f0)

Note : Tests are done with same 3500 Client_Name data in influxdb 1.8 and influxdb 2.7.4.

1) If i create variable from influx 2.7.4 with flux with below query only 1000 client names are shown at preview area at variable creation page (Also in dashboard filter):

import "influxdata/influxdb/schema"
schema.tagValues(
    bucket: "VFBckStrg",
    tag: "Client_Name"
)

2) If i create variable from influx 1.8 with influxql with below query all 3500 client names are shown at preview area at variable creation page (Also in dashboard filter):

SHOW TAG VALUES FROM “SELECTBOX_VALUES” WITH KEY = “Client_Name”

### What did you expect to happen?

When I create a Grafana variable with influxql in InfluxDB version 1.8, I can search and find all 3500 clients in the dashboard filter using this variable. However, in InfluxDB version 2.7.4, when I create a variable with flux, I can only list and search for the first 1000 clients in the filter. If I can find each of the 3500 clients in the dashboard filter with InfluxDB 1.8, I want to be able to find each of the 3500 clients in the Grafana variable filter created with the newer version, InfluxDB v2.7.4, using the flux language. I suspect there is an issue with variable integration in Grafana using InfluxDB v2.7 and the flux language.

### Did this work before?

When I create a Grafana 10 variable with influxql in InfluxDB version 1.8, I can search and find all 3500 clients in the dashboard filter using this variable. However, in InfluxDB version 2.7.4, when I create a variable with flux, I can only list and search for the first 1000 clients in the filter.

### How do we reproduce it?

1. Create data with **Client_Name** tag with **3500 sample tag values** on **influxdb 1.8** version.
2. Create data with **Client_Name** tag with **3500 sample tag values** on **influxdb 2.7.4** version.
3. Create grafana variable named XVAR with influxdb 1.8 with Client_Name tag with below influxql query : 

    SHOW TAG VALUES FROM “SELECTBOX_VALUES” WITH KEY = “Client_Name”
    Preview values on variable page and see 3500 values are shown.

4. Create grafana variable named ZVAR with influxdb 2.7.4 with Client_Name tag with below FLUX query :
import "influxdata/influxdb/schema"

schema.tagValues(
    bucket: "VFBckStrg",
    tag: "Client_Name"
)

Preview values on variable page and see only 1000 values are shown.

5. Open dashboard and check XVAR filter. You will be able to search and get all 3500 tag values in the filter.
6. Open dashboard and check ZVAR filter. You will be able to search and get only 1000 tag values in the filter.
7. At the end you will see that you can search and get all 3500 Client_Name values in XVAR filter which is created with influxdb 1.8. You will see that you can search only 1000 Client_Name values in ZVAR filter which is created with influxdb 2.7.4.
8. This means there is a problem with filters created with variables created with influxdb 2.7.4 flux language.  

### Is the bug inside a dashboard panel?

The bug starts in variable creation page. You can see that variables created with flux cannot show preview values more than 1000 values. But variables created with influxql in influxdb 1.8 show preview values more than 1000, even 3500. So when the variable goes to dashboard as a filter, the filter also behaieves like variable. 

### Environment (with versions)?

Grafana: 10.0.0
OS: RedHat Linux
Browser: Chrome Latest

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influxdb 2.7.4 with FLUX

**Comment by cemselman** [comment]
Any update?

**Comment by NWRichmond** [comment]
We expect this will be addressed by the work towards https://github.com/grafana/grafana/issues/84120, which will involve a few PRs

**Comment by itsmylife** [comment]
@gefaila This depends on the release channel of your instance. Do you know which channel your instance is in?

**Comment by gefaila** [comment]
I'm afraid I don't. 
@melgl ... Can you help me test this fix in our lbbc.grafana.net area?

**Comment by itsmylife** [comment]
@gefaila I think the change landed in your instance. Please check it again. But please be aware there is a potential bug with the calculation so I had to revert the calculation logic https://github.com/grafana/grafana/pull/88809 (and another issue https://github.com/grafana/grafana/pull/88642)

The changes I shared will take effect next Tuesday. I am sorry for the inconvenience. I'll be out till the 17th of June because of sickness but I'll try to provide support as much as possible.

**Comment by gefaila** [comment]
awesome.  I'll test next week.  This will greatly neaten our dashboards because we've had to work around the bug in a very ugly way until your work!
