### ISSUE TITLE
[Docs] Improve Panel Section

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8549]
We need to improve the panels section in our docs. 

1. Create an overview page that describes which panels are shipped with Grafana and introduce the idea of adding panels from Grafana.com: To be located at http://docs.grafana.org/features/panels/overview
2. Audit the existing individual panel sections to check screenshots and content for latest versions
3. Add a "Adding New Panels" page that describes and links to the panels section on Grafana.com.

This is a deceptively small ticket - the individual panel pages are going to be a good amount of work themselves. When this is being worked on, feel free to break this issue up into individual issues for ease of tracking.

**Comment by oddlittlebird** [comment]
Fixed when I rewrote the panel section for Grafana 7.0.
