### ISSUE TITLE
[Guide] Getting Started with Grafana & Prometheus

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8550]
We'd like to create a guide that can help a new user to Grafana & Prometheus get started. We can assume that a pre-requisite is that they have a running Prometheus server(s) and just need to start graphing in Grafana. 

This is a good base example: https://www.digitalocean.com/community/tutorials/how-to-add-a-prometheus-dashboard-to-grafana

The goal of the tutorial will be for the user to end with making a dashboard of their data so awesome that they want to share it on twitter and tell everyone. 💯

**Comment by mattttt** [comment]
In-progress by a new writer! Very excited.

**Comment by daniellee** [comment]
This recently got added: https://grafana.com/docs/grafana/latest/getting-started/getting-started-prometheus/
