### ISSUE TITLE
[Guide] Getting Started with Grafana & Graphite

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8551]
We'd like to create a guide that can help a new user to Grafana & Graphite get started. We can  assume that a pre-requisite is that they have a running Graphite server and just need to start graphing in Grafana. 

Should be full of screenshots and video/animated gifs, and be logically separately into easy to read sections. 

We should make an official dashboard on Grafana.com that helps them get started with Influx, and be sure to link to the filtered list for further exploration: https://grafana.com/dashboards?dataSource=graphite

The goal of the tutorial will be for the user to end with making a dashboard of their data so awesome that they want to share it on twitter and tell everyone. 💯

**Comment by zoltanbedi** [comment]
I would say this is done.
