### ISSUE TITLE
[Guide] Getting Started with Grafana & InfluxDB

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8552]
We'd like to create a guide that can help a new user to Grafana & InfluxDB get started. We can assume that a pre-requisite is that they have a running Influx server(s) and just need to start graphing in Grafana. 

Should be full of screenshots and video/animated gifs, and be logically separately into easy to read sections. 

We should make an official dashboard on Grafana.com that helps them get started with Influx, and be sure to link to the filtered list for further exploration: https://grafana.com/dashboards?dataSource=influxdb

The goal of the tutorial will be for the user to end with making a dashboard of their data so awesome that they want to share it on twitter and tell everyone. 💯

**Comment by mattttt** [comment]
Claimed and being worked on!

**Comment by musca001** [comment]
Hi Matt,

I've been trying to use Grafana+InfluxDB but noticed some odd behavior. When Grafana sends the SELECT query to Influx, it appends "ms" to the time stamp. Problem is Influx doesn't store time stamps with the "ms", so it never returns anything to Grafana.

Surely I can't be the first one to notice this but I haven't been able to find anything in the forums about this problem. I'm running influx 1.4.2 and Grafana server Version 4.6.2 (commit: 8db5f08).

Do you know what I need to do to either open a bug or request an enhancement to allow users to include or omit the "ms" in the SELECT time stamp?

Thank you ,
Dan

**Comment by torkelo** [comment]
It's not a bug it's how you specify the unit in the influxdb query language

**Comment by musca001** [comment]
Hi Torkel,

Thanks for the reply. I tried writing to influx using "ms" but it fails:

[admin@httstools tmp]$ curl -i -XPOST 'http://localhost:8086/write?db=bulkstats' --data-binary @/tmp/foo1
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: b707cf65-d9fc-11e7-82e3-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'P2P,Nodename=ALPRGAGQPND,p2p-duration-name=0,p2p-protocol=lync-file-transfer p2p-duration-value=10 0000000010000ms': bad timestamp
X-Influxdb-Version: 1.4.2
X-Request-Id: b707cf65-d9fc-11e7-82e3-000000000000
Date: Tue, 05 Dec 2017 20:41:48 GMT
Content-Length: 160

{"error":"unable to parse 'P2P,Nodename=ALPRGAGQPND,p2p-duration-name=0,p2p-protocol=lync-file-transfer p2p-duration-value=10 0000000010000ms': bad timestamp"}
[admin@httstools tmp]$ more foo1
P2P,Nodename=ALPRGAGQPND,p2p-duration-name=0,p2p-protocol=lync-file-transfer p2p-duration-value=10 0000000010000ms
[admin@httstools tmp]$

Forgive me if I'm missing something obvious, but I've been trying to get this to work for a while now and keep hitting the same issue (ie "ms" appended to the SELECT statement generated by Grafana).

Could you elaborate a bit when you say it's how you specify the unit in influx? Maybe with an example line like in my foo1 example above?

Thank you,
Dan Musca
Cisco High Touch Technical Support
Phone: 469-255-3768
Cell: 972-768-0937
Email/Jabber: dmusca@cisco.com<mailto:dmusca@cisco.com>
HTTS Hotline: 800-495-9121
To update your case: https://mycase.cloudapps.cisco.com/case
Cisco Worldwide Contact: http://www.cisco.com/c/en/us/support/web/tsd-cisco-worldwide-contacts.html
-------------------------------------------
Direct Manager: Mansoor Omer
Phone: 408-525-4745
Email: mmohamed@cisco.com<mailto:mmohamed@cisco.com>

On Dec 5, 2017, at 12:29 PM, Torkel Ödegaard <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a bug it's how you specify the unit in the influxdb query language

**Comment by torkelo** [comment]
It's not part of the write api, but the query language and how you specify date range filters. What you write data you use a different api

**Comment by musca001** [comment]
Hi Torkel,

Thank you for your response. Marcus Efraimsson (Grafana community) finally figured out what was going on. I was writing my time stamps to influx in milliseconds but wasn't specifying the "&precision=ms" qualifier in the HTTP POST. So influx was storing everything using 1970. I attached his reply in case it helps. I hope I'm not violating any forum rules by doing so :)

Thank you,
Dan Musca
Cisco High Touch Technical Support
Phone: 469-255-3768
Cell: 972-768-0937
Email/Jabber: dmusca@cisco.com<mailto:dmusca@cisco.com>
HTTS Hotline: 800-495-9121
To update your case: https://mycase.cloudapps.cisco.com/case
Cisco Worldwide Contact: http://www.cisco.com/c/en/us/support/web/tsd-cisco-worldwide-contacts.html
-------------------------------------------
Direct Manager: Mansoor Omer
Phone: 408-525-4745
Email: mmohamed@cisco.com<mailto:mmohamed@cisco.com>

On Dec 6, 2017, at 12:11 AM, Torkel Ödegaard <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not part of the write api, but the query language and how you specify date range filters. What you write data you use a different api
