### ISSUE TITLE
newVizTooltips: barchart tooltip regression

### ISSUE THREAD

**Issue by jfo** [grafana/grafana#85521]
### What happened?

We're in `beta` for `newVizTooltips`, and values are not rendered into tooltip that were previously present.

![Screenshot 2024-04-03 at 11 39 46](https://github.com/grafana/grafana/assets/4204764/f3f64fe2-515f-40c2-9f57-4ca5143b91dd)

Related to https://github.com/grafana/grafana/issues/85021

a/b split is here:

https://github.com/grafana/grafana/blob/22fe7b067cdfbc52543a536de9bf8303fdc26286/public/app/plugins/panel/barchart/BarChartPanel.tsx#L332-L390

Filtering happening here in new version:
https://github.com/grafana/grafana/blob/22fe7b067cdfbc52543a536de9bf8303fdc26286/packages/grafana-ui/src/components/VizTooltip/utils.ts#L77

vs here in old:

https://github.com/grafana/grafana/blob/22fe7b067cdfbc52543a536de9bf8303fdc26286/public/app/features/visualization/data-hover/DataHoverView.tsx#L37

### What did you expect to happen?

The same fields to be present before and after.

### Did this work before?

with `newVizTooltips` disabled:

![Screenshot 2024-04-03 at 11 40 27](https://github.com/grafana/grafana/assets/4204764/56a9862b-3190-4197-9fd2-0a6413048f4a)

### How do we reproduce it?

1. `enable = newVizTooltips` [here](https://github.com/grafana/grafana/blob/22fe7b067cdfbc52543a536de9bf8303fdc26286/conf/defaults.ini#L1702) (locally) or `Home > Administration > General >
Feature Toggles`
2. Create a `Bar Chart` from grafana-postgresql-datasource
3. change `Tooltip mode` to `all`
4. Use this query:
```sql
SELECT
	'title' AS a,
	'entity' AS b,
	sum(123) AS x,
	sum(456)::text AS y
GROUP BY
	a,
	b
ORDER BY
	x;
```

This is a simplified version of an analytics aggregation that we use on a dashboard. 

### Is the bug inside a dashboard panel?

Prod query includes PII

### Environment (with versions)?

Grafana: v11.1.0-68838 (22fe7b067c)
OS: Sonoma 14.2.1
Browser: Chrome / Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

grafana-postgresql-datasource but likely not uniquely

**Comment by leeoniya** [comment]
yep, thanks.

we're aware and working on a fix in https://github.com/grafana/grafana/tree/leeoniya/barchart-refactor -- turns out that the tentacles for the fix go pretty deep, especially now that the old tooltip code has been removed (https://github.com/grafana/grafana/pull/84420).

expecting to have a PR in the next few days or early next week.

**Comment by jfo** [comment]
Thanks 

> turns out that the tentacles for the fix go pretty deep

I found that out the hard way as I was trying to find a quick patch! 😄
