### ISSUE TITLE
[Guide] Getting Started with Grafana & ElasticSearch

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8553]
We'd like to create a guide that can help a new user to Grafana & ElasticSearch get started. We can  assume that a pre-requisite is that they have a running ES server and just need to start graphing in Grafana. 

Should be full of screenshots and video/animated gifs, and be logically separately into easy to read sections. Should include the 2 commonly used panels for ES, graph & table panels.

We should make an official dashboard on Grafana.com that helps them get started with ES, and be sure to link to the filtered list for further exploration: https://grafana.com/dashboards?dataSource=elasticsearch

The goal of the tutorial will be for the user to end with making a dashboard of their data so awesome that they want to share it on twitter and tell everyone. 💯

**Comment by softwareklinic** [comment]
We are using extensively -- Grafana with Elastic... If you need help let us know.

**Comment by mattttt** [comment]
hey @softwareklinic! If you wanted to take a stab at submitting a PR to get a guide started, we could help polish it up for publication. It would be immensely helpful to the Grafana/ES community. :)

Even starting with a Gist that we can help you flesh out would be very cool.

**Comment by softwareklinic** [comment]
What will be ideal place to put some examples....

**Comment by nickmcknight** [comment]
Any moves made on this? I've got elasticsearch bringing in parsed logs from winlogbeat. I am able to create a table with logins by user in Kibana, but I just cant figure out Grafana.

**Comment by a34477** [comment]
@mattttt @softwareklinic Could anyone let me know where perfect document is there for getting started with elasticsearch and grafana

**Comment by oddlittlebird** [comment]
@Elfo404 and @achatterjee-grafana, can we declare this done?

**Comment by achatterjee-grafana** [comment]
Closing the issue. We also. have a duplicate in https://github.com/grafana/grafana/issues/25483.
