### ISSUE TITLE
[Docs] What is time series data?

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8554]
We've received variations on the question, What is Time Series Data?, so it'll be valuable to create a docs page we can easily link to. 

Here are a couple examples from the community site:
https://community.grafana.com/t/any-one-can-explain-about-what-exactly-time-series/1091/2
https://community.grafana.com/t/how-to-build-query-in-grafana/839/6

It will be valuable to highlight what time series data is, and also what it is not. 

This does not have to be a long, comprehensive article on the pros/cons of time series databases. 

Think of it as a primer for a new Grafana user that wants to learn, and we can link them to other resources to educate themselves further.

**Comment by mattttt** [comment]
In-progress by a new writer! Very excited.

**Comment by oddlittlebird** [comment]
@mattttt , what is the status on this?

**Comment by oddlittlebird** [comment]
Closed with [Intro to timeseries](https://grafana.com/docs/grafana/latest/getting-started/timeseries/).
