### ISSUE TITLE
[Feature request] Add 'custom' option to 'Unit/none' selection which allows use of 'printf' format codes

### ISSUE THREAD

**Issue by MarkTurbo** [grafana/grafana#8556]
Currently, there's no option when specifying the 'Unit' of a Value, to display large numbers using traditional 'thousands' separators, e.g. displaying numbers like 1234567 as 1,234,567. Although it might be possible to add a a new option specifically for this format, I'd like to suggest an alternative approach, which would add much more flexibility.

Could a new option be added under 'Unit/none' called something like 'custom', which when selected, would open an additional edit box and allow a 'printf' format code to be specified? The format code can then be applied to the displayed Value.

Using my example above, the format code "%'d" would display 1234567 as 1,234,567.

**Comment by torkelo** [comment]
dupliicate (or similar to), https://github.com/grafana/grafana/issues/2968
