### ISSUE TITLE
Dashboard: share externally breaks dashboards with datasource variables

### ISSUE THREAD

**Issue by antonincms** [grafana/grafana#85606]
### What happened?

When a dashboard which uses a datasource variable is exported using the "share externally" option, grafana replaces 
```json 
{
"panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${datasource}"
      }
    }
}
```
with 
```json 
{
"panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
      },
    }
}
```

Here is the complete diff I see using [dyff](https://github.com/homeport/dyff) : 
```
➜  dyff between v10.4.0-1.json v10.4.0-2.json
     _        __  __
   _| |_   _ / _|/ _|  between v10.4.0-1.json
 / _' | | | | |_| |_       and v10.4.0-2.json
| (_| | |_| |  _|  _|
 \__,_|\__, |_| |_|   returned four differences
        |___/

(root level)
- three map entries removed:
  __elements: {}
  __inputs:
  - name: DS_PROMETHEUS
  │ type: datasource
  │ description:
  │ label: Prometheus
  │ pluginId: prometheus
  │ pluginName: Prometheus
  __requires:
  - name: Grafana
  │ version: 10.4.0
  │ id: grafana
  │ type: grafana
  - name: Prometheus
  │ version: 1.0.0
  │ id: prometheus
  │ type: datasource
  - name: "Time series"
  │ version:
  │ id: timeseries
  │ type: panel

id
  ± type change from <nil> to int
    - <nil>
    + 81

panels.1.datasource.uid
  ± value change
    - ${DS_PROMETHEUS}
    + ${datasource}

panels.1.targets.0.datasource.uid
  ± value change
    - ${DS_PROMETHEUS}
    + ${datasource}
```

### What did you expect to happen?

As the datasource is not hardcoded, it should correctly keep the datasource variable as is, as does the export without the "share externally" option.

### Did this work before?

I don't think so.

### How do we reproduce it?

1. Create a dashboard
2. Add a variable of type data source
3. Add a pannel using this variable as data source
4. Export using "share externally" , export without 
5. Compare the two exported dashboard, in the one using "share externally" the panels should not use the variable anymore

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: v10.4.0, also tested on cloud (v11.1.0-68838)
OS: linux
Browser: chrome

### Grafana platform?

None

**Comment by evictorero** [comment]
Probably [duplicated](https://github.com/grafana/grafana/issues/77961) and fixed [here](https://github.com/grafana/grafana/pull/86273).

**Comment by antonincms** [comment]
Thanks !
