### ISSUE TITLE
Templating grafana + CloudWatch custom metrics

### ISSUE THREAD

**Issue by ivan-balandzin** [grafana/grafana#8561]
Grafana version 4.3.2 (commit: ed4d170)
CloudWatch datasource
Server OS RHEL/Centos7
Cloud: AWS eu-west-1
**Issue about templating variables and their automatical update.**

I'm pushing custom metrics to CloudWatch from Jenkins jobs with the next combination: 
- Metric name: jenkins build number
- Metric value: job state (0 - Aborted, 1 - Failed, 2 - OK, 3 - Running) 

How it looks in CloudWatch:
![screenshot from 2017-06-06 23-15-06](https://user-images.githubusercontent.com/17778068/26849777-119be9cc-4b0e-11e7-8e5d-454055536749.png)
It's a mess, but grafana dashboard worth it.

Templating query example: dimension_values(eu-west-1, NightlyCI, SANITY, BUILD)
Numeric descending output example: 12, 11, 10 etc.

**The main problem is in refreshing of these variables.** New job with new build number has already pushed new metric with name as number of build but it has not been refreshed in automatic way even after any of next actions - refreshing each 5 seconds (dash setup), refreshing of browser page, incognito window, other browser and even other device. Also re-creating dashboard from json leads to the same result - new variable values (build numbers) appear but they can't be chosen automatically. Only manually and page reload returns default value back to the previous.

Only after several hours latest value (as per numeric descending sorting) becomes default value.

So refreshing using any of proposed ways (Dashboard load or Time range change) doesn't working at all for me now.
 
![screenshot from 2017-06-06 23-09-19](https://user-images.githubusercontent.com/17778068/26849525-34fe6058-4b0d-11e7-8ea8-7155c3f126a2.png)

As you see, default value is not the latest and it will not be latest for a couple of hours.
And it is a real pain because this dashboard will be placed on big screen TV in front of 150+ developers and there will be no possibility to refresh it manually.

And as a workaround could you please tell how to force variable update process or where to reset cached values?

**Comment by ivan-balandzin** [comment]
Seems that currently used variables are able to be saved along with dashboard. It's not good but not bad.

**Comment by ivan-balandzin** [comment]
The only way I've found to keep values up-to-date is:
1) exporting JSON of dashboard.
2) removing section _"current": {"text": "XXX", "value": "XXX"  }_ for each variable
3) importing JSON without these sections (importing is ok)
In this case grafana automatically sets latest (according to numeric descending sorting) values of variables as default and JSON of new dashboard has this values again.

**Comment by torkelo** [comment]
What did you set the Refresh option to for the variable?

**Comment by ivan-balandzin** [comment]
@torkelo As I told - I've tried both refreshing possibilities:
- On Dashboard Load
- On Time Range Change
Both options refresh variable itself but not the current value which is stored in dashboard configuration.
So I can see new values of variable but they can't be set as default without manually setting them and saving dashboard.
