### ISSUE TITLE
[Feature Request] OpenTSDB to support filtering on annotation custom fields

### ISSUE THREAD

**Issue by hijklmno** [grafana/grafana#8562]
Hi Grafana Team,

Thanks for the continuous effort! It has brought a lot of success in our production.

This is not part of the specs of OpenTSDB, but I have a use case where I am creating annotations on an OpenTSDB time series metric with custom values, which is a key value map described [here](http://opentsdb.net/docs/build/html/api_http/annotation/index.html). Right now after adding an annotation from datasource OpenTSDB, the global annotations returned in the query is 
`{..., "globalAnnotations":  
  [{  
    "tsuid":"",  
    "description":"Video Issue",  
    "notes":"These would be details about the event, the description is just a summary",  
    "custom": {  
      "serviceId":"100",  
      "userId":"124",  
      "agentId":"123",  
      "env":"dev"  
    },  
  "startTime":1496776195,  
  "endTime":0  
  }, ...],  
...}`  

Is there a way we can optionally allow filtering of the annotations, if there is template created on the dashboard that matches a key in the annotation? Again, this is not part of the specs. Wanted to post this up and get the thoughts of other fellow OpenTSDB users, as this would be a great tool to use with Grafana. I have filed this issue with OpenTSDB repo as well, [here](https://github.com/OpenTSDB/opentsdb/issues/992).

- What Grafana version are you using? 
v4.1.1
- What datasource are you using? 
OpenTSDB
- What OS are you running grafana on? 
AWS EC2 AMI
- What did you do? 
Added annotation from datasource OpenTSDB with a query and global annotations enabled.
- What was the expected result? 
Expected an option to filter through using the custom tag fields from globalAnnotations and localAnnotations.
- What happened instead? 
No option to filter through.

**Comment by torkelo** [comment]
The filtering would have to be done by your data source (OpenTSDB)
