### ISSUE TITLE
[Docs]: Document singlestat feature $__name that can be used in prefix or postfix

### ISSUE THREAD

**Issue by hijklmno** [grafana/grafana#8563]
Hi Grafana Team,

Thanks for the continuous effort! It has brought a lot of success in our production.

I encountered an issue using the single stat panel, and I don't think this is an intended consequence. I have an OpenTSDB time series metric with a tag `requestSource`, and the value of the tag shows up perfectly in the alias under Metrics tab. However, when using the same tag, in the prefix or postfix boxes, the translated tag value isn't properly shown; instead it shows the untranslated tag (see screenshot below).

Any chance we can fix that, or did I do something wrong? 

![screenshot 2017-06-06 15 10 45](https://user-images.githubusercontent.com/2644907/26854288-5b0f8cf6-4aca-11e7-9fa1-9080a6135b1e.png)

Thank you!

What Grafana version are you using?
v4.3.2
What datasource are you using?
OpenTSDB
What OS are you running grafana on?
AWS EC2 AMI
What did you do?
Add `$tag_requestSource` to postfix in single stat panel.
What was the expected result?
Expected `$tag_requestSource` to be replaced with the tag value.
What happened instead?
The raw string `$tag_requestSource` is displayed instead.

**Comment by torkelo** [comment]
you can already do this, use `$__name` in the prefix or suffix fields, will be replaced with the series name
