### ISSUE TITLE
[Feature Request] Add BitCoin currency unit

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8564]
This is a feature request to add BitCoin (B͈̎) to the list of supported currencies.
In addition to supporting the whole BitCoin unit, it would be nice to also have the units milli-bitcoin (mBTC) and micro-bitcoin (μBTC).

**Comment by tehdirector** [comment]
I see this is still open although Bitcoin is a listed currency unit. I would like to request a change away from using the "short" function on this unit. 1.05K BTC is also 1,050.12345678 BTC which can be easy to mis-interpret seeing the 1.05 and missing the K. If this could be switched to the same function s "locale" this would help to avoid and mis-interpretation of the data.

An alternative and better solution (IMO) would be to allow the "locale" format #,###,###.####### to be applied to any unit. This would allow for the user to decide how the number is displayed. This can be very beneficial for datasets that include numbers that range from millions/billions to a number of decimals without having to force one format on a specific unit.

**Comment by marefr** [comment]
@tehdirector  Since BitCoin currency have been added I will close this issue. Thanks for the pointer. I would suggest you open a new bug report or feature request issue to handle your additional comments.

**Comment by marefr** [comment]
Fixed by #13125
