### ISSUE TITLE
[Bug] Heatmap rounds units too much

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8566]
Please include this information:
- What Grafana version are you using?
4.3.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
FreeBSD

- What did you do?
Created a heatmap panel with data in a narrow range of y-axis values

- What was the expected result?
Appropriate precision in y-axis units, enough to show difference in values.

- What happened instead?
Y-axis units all have the same value.
![image](https://user-images.githubusercontent.com/1826947/26879135-f34423a4-4b5d-11e7-8bbb-d1e8674fe37e.png)

- If related to metric query / data viz:
http://dpaste.com/1TYX2X1.txt

**Comment by daniellee** [comment]
Closed by #8717
