### ISSUE TITLE
Connections: Explore button on data sources page is visible even if explore function is disabled

### ISSUE THREAD

**Issue by mgd722** [grafana/grafana#85697]
### What happened?

If the explore feature is disabled the Explore button is still visible next to the data source on the `/connections/datasources` page:

<img width="677" alt="image" src="https://github.com/grafana/grafana/assets/12187845/87ebe6a7-7682-4a86-9600-c5ee41958a64">

Clicking it yields a message telling the user that explore is disabled:

![image](https://github.com/grafana/grafana/assets/12187845/31c5fe6c-1cea-4809-aa9a-bc19744adbff)

### What did you expect to happen?

The explore button should be hidden if it will not function.

### Did this work before?

I am new to Grafana so I don't know, but a [similar issue](https://github.com/grafana/grafana/issues/56989) was raised in the past about the explore button on panels.

### How do we reproduce it?

1. Start Grafana with explore disabled.
2. Add a data source.
3. Navigate to `/connections/datasources` and click the explore button next to the data source.

### Environment (with versions)?

Grafana: 10.4.1
OS: MacOS 14.2.1
Browser: Chrome (latest)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
note for reviewer: not sure the issue belongs to your squad. please reroute if needed . thank you!

**Comment by ifrost** [comment]
I think Grafana Connections is owned by @grafana/frontend-plugins 🤔 The button can be hidden/disabled by checking [config.exploreEnabled property](https://github.com/grafana/grafana/blob/00d6e1d7f8da008527b94bcc711776a712b3c924/public/app/routes/routes.tsx#L163).

In long run it might be worth creating a simple `OpenExploreButton` component that would handle it internally.

**Comment by tolzhabayev** [comment]
Added it to our (plugins platform) squad - we will take this on.
