### ISSUE TITLE
Support for "no basic role" in `plugin.json`'s `includes` array.

### ISSUE THREAD

**Issue by mgd722** [grafana/grafana#85698]
**Why is this needed**:

I have an app plugin that exports a compliance report in PDF.

- This app plugin should be available to everyone within the organization, regardless of role.
- Some users within the organization have a login for the sole purpose of accessing this plugin, but should not have the ability to view anything else (thus even the "Viewer" role is too much access)

**What would you like to be added**:

In an app plugin’s `plugin.json`, allow setting the [includes role](https://grafana.com/developers/plugin-tools/reference-plugin-json#includes) to “[no basic role](https://grafana.com/blog/2023/11/22/new-in-grafana-roles-manage-user-permissions-better-with-no-basic-role/)”.

**Who is this feature for?**

This would allow plugin developers to provide plugin access to everyone at the organization, regardless of role.

**Comment by mgd722** [comment]
Looking at the [`RoleType`](https://github.com/grafana/grafana/blob/main/pkg/models/roletype/role_type.go#L12) enum and how it's parsed in [`ReadPluginJSON`](https://github.com/grafana/grafana/blob/main/pkg/plugins/plugins.go#L176-L180), you might think you could just set this to the string `"None"`.

This must get overwritten somewhere else though, because it seems to still default to viewer. Intellisense also takes issue with it, so it must be defined elsewhere.
![image](https://github.com/grafana/grafana/assets/12187845/7f2b3e87-b791-4e74-b2b4-3913e3ed20a7)

**Comment by mgd722** [comment]
Actually when the user is assigned "No basic role" and you pass `"role": "None"` in `plugin.json`, if the user tries to access the plugin they get a 403 and:
```
message: "You'll need additional permissions to perform this action. Permissions needed: plugins.app:access"`.
```

I'm running OSS so I can't set RBAC, but I'll bet if I could add that specific scope this would work.

**Comment by mgd722** [comment]
Indeed-- I faked RBAC by manually editing the database, adding:
- a new record to the `role` table (in my case, role ID 7)
- a new record to the `permission` table:
    - role_id: 7
    - action: plugins.app:access
    - scope: plugins:id:<my_app_id>
    - kind: plugins
    - attribute: id
    - identifier: <my_app_id>
- a new record to the `user_role` table to give the user this permission

Doing this, the user with "no basic role" was able to access a plugin with `"role": "None"`. As a result, the main tasks for this ticket would be:

- [ ] 1. Update `plugin.json` [docs](https://grafana.com/developers/plugin-tools/reference-plugin-json#includes) to reflect that `"None"` is a viable includes role if you have RBAC
- [ ] 2. Update the code intellisense with the same (this is probably auto-generated...?)
- [ ] 3. Find some way to support this in Grafana OSS?

Knowing now that this does work with RBAC, I imagine there's little hope of item 3 actually getting implemented 😔. The way it currently works seems ideal for RBAC, and I can't think of a clean way for OSS to handle these permissions in a way that wouldn't mess with RBAC.

In case you are an OSS user stumbling on this in the future: I'll report back if I find a less hacky way of getting this to work. For my use case for the time being, creating a role/permission manually and assigning it to a team is good enough. I only have a handful of users that need to access my plugin and ONLY my plugin, so giving them "no basic role" and assigning them to a team is okay.

**Comment by mckn** [comment]
I will close this feature request for the time being since RBAC is an enterprise/cloud feature and isn't available in OSS. If/when we include it in the OSS version we can revisit this issue. 

Please let me know if you want me to re-open the request.
