### ISSUE TITLE
inappropriate status code for alerting: invalid relative time range: {From:0s To:0s}

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#85709]
### What happened?

When adding an alert, 500 status code is returned when the time range is set as now to now
![image](https://github.com/grafana/grafana/assets/36128312/eb123098-0e15-46ac-bb7a-d7bc3e49f1ea)
![image](https://github.com/grafana/grafana/assets/36128312/eb43e708-9aaf-420f-aa0c-a34e55bcd1c5)

### What did you expect to happen?

This is caused by user error, returning 500 is inappropriate, 400 should be returned instead.

### Did this work before?

not sure

### How do we reproduce it?

1.create an alert rule
2.set the time range for the query as now to now
3.click save

### Environment (with versions)?

Grafana: 9.5.17, 10.3.4

### Grafana platform?

None

**Comment by tonypowa** [comment]
hi @MingjieZhuEmily 
Thanks for submitting this issue

I don't see any errors in Grafana v10.2.2

What is the data source that you are using?

**Comment by tonypowa** [comment]
perhaps also please share the json of the panel that contains the linked alert

**Comment by MingjieZhuEmily** [comment]
As mentioned in summary, this problem happened in both 9.5.17 and 10.3.4, I just tried at a 10.4.1 instance and this issue still exists. The data source is azure data explorer. 

Here is one example alert:
{"apiVersion":1,"groups":[{"orgId":1,"name":"5 Minutes Evaluation Interval","folder":"AMG Data Plane","interval":"1m","rules":[{"uid":"uhWULM8Vk","title":"Authentication Error (Auth Service) FF","condition":"AlertTriggered","data":[{"refId":"ErrorCount","queryType":"KQL","relativeTimeRange":{"from":0,"to":0},"datasourceUid":"PA389D0E01354CD76","model":{"database":"dpfairfax","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"PA389D0E01354CD76"},"expression":{"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.4.1","query":"let SubcriptionIds =\ndatabase('rpfairfax').WorkspaceSubscriptionMap\n| project Workspace=trim(@\"-[a-zA-Z0-9]+$\", Subdomain), HostRegion, subId;\nlet NginxAuthErrors =\ndatabase('dpfairfax').nginxProxyContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where log contains \"auth request unexpected status: 502\"\n| where Tenant !in (\"eastus2euap\", \"centraluseuap\")\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m);\nNginxAuthErrors\n| join kind=leftsemi SubcriptionIds on $left.Workspace == $right.Workspace\n| order by timestamp asc","querySource":"raw","queryType":"KQL","rawMode":true,"refId":"ErrorCount","resultFormat":"time_series"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":0,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":0,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"description":"","message":"[sev3] Auth service authentication failed over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace\nThis can happen during creation or patching phase due to a known issue https://msazure.visualstudio.com/AzureGrafanaService/_workitems/edit/16441756, so if this error no longer occur in the last 10 minutes, you can resolve it","runbook_url":"","summary":""},"labels":{"":"","domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"NB_AXMUVk","title":"Fail To Retrieve Access Token FF","condition":"AlertTriggered","data":[{"refId":"ErrorCount","queryType":"KQL","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"PA389D0E01354CD76","model":{"database":"dpfairfax","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"PA389D0E01354CD76"},"expression":{"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.4.1","query":"grafanaContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where msg contains \"Data proxy error\"\n| where error contains \"http: proxy error: failed to retrieve Azure access token: context canceled\"\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m)\n| order by timestamp asc","querySource":"raw","queryType":"KQL","rawMode":true,"refId":"ErrorCount","resultFormat":"time_series"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"Grafana workspace instance fail to retrieve access token from Token Service over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace"},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"E632yGBVz","title":"Fail To Retrieve Access Token","condition":"AlertTriggered","data":[{"refId":"ErrorCount","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"P61DCD2C6F70AF09D","model":{"database":"dpprod","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"P61DCD2C6F70AF09D"},"expression":{"columns":{"columns":["TIMESTAMP","lineNumber"],"type":"property"},"from":{"property":{"name":"grafanaContainer","type":"string"},"type":"property"},"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.2.0","query":"grafanaContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where msg contains \"Data proxy error\"\n| where error contains \"http: proxy error: failed to retrieve Azure access token: context canceled\"\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m)\n| order by timestamp asc","querySource":"raw","rawMode":true,"refId":"ErrorCount","resultFormat":"time_series"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":0,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"Grafana workspace instance fail to retrieve access token from Token Service over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace"},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"6RF8sGfVk","title":"Authentication Error (Auth Service)","condition":"AlertTriggered","data":[{"refId":"ErrorCount","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"P61DCD2C6F70AF09D","model":{"database":"dpprod","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"P61DCD2C6F70AF09D"},"expression":{"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.2.0","query":"let SubcriptionIds =\ndatabase('rpprod').WorkspaceSubscriptionMap\n| project Workspace=trim(@\"-[a-zA-Z0-9]+$\", Subdomain), HostRegion, subId;\nlet NginxAuthErrors =\ndatabase('dpprod').nginxProxyContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where log contains \"auth request unexpected status: 502\"\n| where Tenant !in (\"eastus2euap\", \"centraluseuap\")\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m);\nNginxAuthErrors\n| join kind=leftsemi SubcriptionIds on $left.Workspace == $right.Workspace\n| order by timestamp asc","querySource":"raw","rawMode":true,"refId":"ErrorCount","resultFormat":"time_series"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[0,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":0,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4,0],"type":"gt"},"operator":{"type":"and"},"query":{"params":[]},"reducer":{"params":[],"type":"avg"},"type":"query"}],"datasource":{"name":"Expression","type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"[sev3] Auth service authentication failed over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace\nThis can happen during creation or patching phase due to a known issue https://msazure.visualstudio.com/AzureGrafanaService/_workitems/edit/16441756, so if this error no longer occur in the last 10 minutes, you can resolve it"},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"qGftuwlVz","title":"MS Graph Service Unavailable","condition":"GraphCallFailureAbove5InLast15Minutes","data":[{"refId":"GraphCallFailureCount","relativeTimeRange":{"from":900,"to":0},"datasourceUid":"P80AE5638EE611A2D","model":{"editorMode":"code","expr":"sum (rate(dp_gateway_graph_service_request_duration_seconds_count{succeeded=\"false\", environment_name=~\"Production\"}[15m])) by (region)","hide":false,"intervalMs":1000,"legendFormat":"__auto","maxDataPoints":43200,"range":true,"refId":"GraphCallFailureCount"}},{"refId":"GraphCallFailureInLast15Minutes","relativeTimeRange":{"from":900,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"GraphCallFailureCount","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"GraphCallFailureInLast15Minutes","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"GraphCallFailureAbove5InLast15Minutes","relativeTimeRange":{"from":900,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[5],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"GraphCallFailureInLast15Minutes","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"GraphCallFailureAbove5InLast15Minutes","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"[sev3] Gateway reports more than 5 failed attempts to call MS Graph within the last 30 minutes."},"labels":{"domain":"DP","environment":"Prod","notifier":"ICM"},"isPaused":false},{"uid":"-4Y8iOkIk","title":"Authentication Error (Auth Service) MC","condition":"AlertTriggered","data":[{"refId":"ErrorCount","queryType":"KQL","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"P7A774134E4968E0C","model":{"OpenAI":false,"database":"dpmooncake","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"P7A774134E4968E0C"},"expression":{"from":{"property":{"name":"grafanaContainer","type":"string"},"type":"property"},"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.6.2","query":"let SubcriptionIds =\ndatabase('rpmooncake').WorkspaceSubscriptionMap\n| project Workspace=trim(@\"-[a-zA-Z0-9]+$\", Subdomain), HostRegion, subId;\nlet NginxAuthErrors =\ndatabase('dpmooncake').nginxProxyContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where log contains \"auth request unexpected status: 502\"\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m);\nNginxAuthErrors\n| join kind=leftsemi SubcriptionIds on $left.Workspace == $right.Workspace\n| order by timestamp asc","querySource":"raw","queryType":"KQL","rawMode":true,"refId":"ErrorCount","resultFormat":"table"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"[Sev4] Mooncake: Auth service authentication failed over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace\nThis can happen during creation or patching phase due to a known issue https://msazure.visualstudio.com/AzureGrafanaService/_workitems/edit/16441756, so if this error no longer occur in the last 10 minutes, you can resolve it"},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"--E2WOkSk","title":"Fail To Retrieve Access Token MC","condition":"AlertTriggered","data":[{"refId":"ErrorCount","queryType":"KQL","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"P7A774134E4968E0C","model":{"OpenAI":false,"database":"dpmooncake","datasource":{"type":"grafana-azure-data-explorer-datasource","uid":"P7A774134E4968E0C"},"expression":{"groupBy":{"expressions":[],"type":"and"},"reduce":{"expressions":[],"type":"and"},"where":{"expressions":[],"type":"and"}},"hide":false,"intervalMs":1000,"maxDataPoints":43200,"pluginVersion":"4.6.2","query":"grafanaContainer\n| where $__timeFilter(FluentdIngestTimestamp)\n| where msg contains \"Data proxy error\"\n| where error contains \"http: proxy error: failed to retrieve Azure access token: context canceled\"\n| summarize ErrorCount=count() by Region=Tenant, Workspace=Role, RoleInstance, timestamp = bin(FluentdIngestTimestamp, 5m)\n| order by timestamp asc","querySource":"raw","queryType":"KQL","rawMode":true,"refId":"ErrorCount","resultFormat":"table"}},{"refId":"ErrorCountSum","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"ErrorCount","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"sum","refId":"ErrorCountSum","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":1800,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[4],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"ErrorCountSum","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"0s","annotations":{"message":"[Sev4] Mooncake: Grafana workspace instance fail to retrieve access token from Token Service over 4 times in 30 mins. If the issue is not automitigated, please try restart the affected VM. Restart guilde can be found at: https://msazure.visualstudio.com/AzureGrafanaService/_wiki/wikis/AzureGrafanaService.wiki/450423/Restart-VM-for-a-specific-workspace"},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAndICM"},"isPaused":false},{"uid":"a1Y-2dkIk","title":"sudden increase of nginx active connection","condition":"AlertTriggered","data":[{"refId":"NginxConnectionChange","relativeTimeRange":{"from":300,"to":0},"datasourceUid":"P80AE5638EE611A2D","model":{"editorMode":"code","expr":"changes(nginx_ingress_controller_nginx_process_connections{state=~\"active\"}[30s])","hide":false,"intervalMs":3000,"legendFormat":"__auto","maxDataPoints":43200,"range":true,"refId":"NginxConnectionChange"}},{"refId":"MaxChange","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"NginxConnectionChange","hide":false,"intervalMs":3000,"maxDataPoints":43200,"reducer":"max","refId":"MaxChange","settings":{"mode":"dropNN"},"type":"reduce"}},{"refId":"AlertTriggered","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"__expr__","model":{"conditions":[{"evaluator":{"params":[2],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"__expr__"},"expression":"MaxChange","hide":false,"intervalMs":3000,"maxDataPoints":43200,"refId":"AlertTriggered","type":"threshold"}}],"noDataState":"OK","execErrState":"OK","for":"5m","annotations":{"description":"Nginx connection of ${aks_name} increased by 3 times in 30s."},"labels":{"domain":"DP","environment":"Prod","notifier":"teamsAlarmChannel"},"isPaused":false}]}]}

**Comment by MingjieZhuEmily** [comment]
I cannot save due to 500 so this is from edit and export function, but you can see relativeTimeRange":{"from":0,"to":0},

**Comment by tonypowa** [comment]
>  How do we reproduce it?
 
>1.create an alert rule
> 2.set the time range for the query as now to now
> 3.click save

Before you hit save, where did you create the alert rule. I'd like to know where in the UI you get the error.

in Alerting > Alert Rules > save ? (And then you linked the alert to a existing panel)
or
in the Dashboard > edit panel > Alert > save Dashboard ?

**Comment by MingjieZhuEmily** [comment]
I'm getting this error in Alerting > Alert Rules > save, I did not link the alert to any panel

**Comment by tonypowa** [comment]
thank you @MingjieZhuEmily 

I'm adding this issue to the team's board for review
note: issue seems to be related to azure's query options within the alert rule configuration

**Comment by adamyeats** [comment]
@MingjieZhuEmily Which version of the ADX datasource were you using? I am running Grafana v10.3.4 locally with v5.0.1 of the ADX datasource and I'm not able to reproduce the behaviour you're describing.

**Comment by MingjieZhuEmily** [comment]
![image](https://github.com/grafana/grafana/assets/36128312/1de6ae43-451a-46e1-8b49-c3c1060e1517)
![image](https://github.com/grafana/grafana/assets/36128312/7b2c0886-ed02-40f1-abb7-c000c67e68c9)
I don't think it relates to data source because I can reproduce it with prometheus data source too

**Comment by adamyeats** [comment]
Thanks @MingjieZhuEmily , @grafana/alerting-squad I think this one might be for you then, let me know if not.

**Comment by santihernandezc** [comment]
Hi @MingjieZhuEmily, this issue is indeed database-agnostic as you say.
We're not planning on modifying this status code in the near future, but you can open a PR and we'll review it.
