### ISSUE TITLE
[Feature request] MySQL SSL CA in datasource connector

### ISSUE THREAD

**Issue by JZacharie** [grafana/grafana#8570]
It is possible to allow using SSL CA in MySQL in datasource connector ?

E.G. I use this commande line to connect to MySQL instance :

mysql -u user -p -h myserverhost --ssl-ca=~/.ssh/certs/ca.pem

thanks in advance.

I'm using : 
Grafana v4.3.1 (befc15c), MySQL 5.7, RedHat 7.3

**Comment by torkelo** [comment]
yes, just have to be implemented :)

**Comment by rluisr** [comment]
this issue doesn't solve yet?

**Comment by rnkhouse** [comment]
This feature has not been addressed in newer version as well. Please add it. Cannot connect to the database without SSL.

**Comment by dmitriy18** [comment]
This is a critical feature. Please cosider adding it soon
Thanks!

**Comment by madmaze** [comment]
Seems like some of this is already there for the main database: https://github.com/grafana/grafana/pull/3584

Perhaps it just needs to be exposed properly?

**Comment by daniellee** [comment]
Postgres has had this feature for ages - a PR would be welcome.

**Comment by Ajaysrndpt** [comment]
Any idea when the issue will be fixed?

**Comment by eladeyal-intel** [comment]
What is missing is: that when adding a mysql datasource (in the GUI), we need a checkbox saying "use SSL". "Falcon SQL" and "metabase" have this.

**Comment by rshejnberg** [comment]
Any updates on this?

**Comment by manikSMahajan** [comment]
There is a workaround i found, change cnnstr with following ccnstr
path: grafana/pkg/tsdb/mysql
replace 

cnnstr := fmt.Sprintf("%s:%s@%s(%s)/%s?collation=utf8mb4_unicode_ci&parseTime=true&loc=UTC&allowNativePasswords=true",
		datasource.User,
		datasource.Password,
		"tcp",
		datasource.Url,
		datasource.Database,
)

with

  cnnstr := fmt.Sprintf("%s:%s@%s(%s)/%s?collation=utf8mb4_unicode_ci&parseTime=true&loc=UTC&allowNativePasswords=true&tls=skip-verify",
                datasource.User,
                datasource.Password,
                "tcp",
                datasource.Url,
                datasource.Database,
        )

**Comment by FabianSchuessler** [comment]
Is there any update on this feature request?

**Comment by sherif84** [comment]
+1

**Comment by xibix-fp** [comment]
+1

**Comment by Cylindric** [comment]
I can't connect to my datasources without TLS.  I didn't think this would be a problem because I _can_ do this for Grafana's own database.

**Comment by mermino** [comment]
+1 on this.  Any progress on getting this implemented?

**Comment by mikimh** [comment]
+1

**Comment by Gelbotron** [comment]
+1

**Comment by bugficks** [comment]
Hi, 
I gave this a quick shot.
Implementation is basically copy&paste from _pkg/models/datasource_cache.go_ and _public/app/features/plugins/partials/ds_http_settings.html_

![clipboard](https://user-images.githubusercontent.com/2992895/51133100-4f575400-1834-11e9-873a-a0bc61edeb29.png)

[mysql-ssl.patch.zip](https://github.com/grafana/grafana/files/2756583/mysql-ssl.patch.zip)

**Comment by marefr** [comment]
@bugficks any reason not opening a pull request?

**Comment by bugficks** [comment]
@marefr just laziness :)
