### ISSUE TITLE
Grafana With prometheus

### ISSUE THREAD

**Issue by honeygidwani** [grafana/grafana#8572]
I am Using Prometheus in grafana. I am executing  this query "haproxy_backend_connection_errors_total" and it is generating graphs properly. I want to know whether I am able to get the details of the result of above mentioned query. 

For example here I have configured backend for localhost:9000 and I have not started this server and executing the frontend. It will generate the backend error as the server is not started. So I want to know the details or reasons behind the failure when I am running this query in grafana.

If yes, then please guide me the way.

**Comment by torkelo** [comment]
please open questions on the community site
