### ISSUE TITLE
Dashboard: Variables query hides fields with google sheets

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#85730]
### What happened?

When selecting "google sheets" as a datasource for a query variable, all query fields disappear.

### What did you expect to happen?

If google sheets is not allowed as a variable datasource, it should at least still show the datasource dropdown so something can be changed.

### Did this work before?

Slightly. The community member who ran into the issue was running 10.2.1. In their screenshot, the datasource dropdown exists, but every other field specific to the google sheets query editor is not.

### How do we reproduce it?

1. Edit the variables of any dashboard, for example https://play.grafana.org/d/c9ea65f5-ed5a-45cf-8fb7-f82af7c3afdf/button-demo?orgId=1&refresh=5s&editview=templating&editIndex=1
2. Create a new variable. Leave it as the default 'query' type, then select a google sheets datasource
3. All fields, including the datasource dropdown, disappear. You need to refresh the page to be able to change datasources.

### Environment (with versions)?

Grafana: 11
OS: OSX
Browser: Chrome 123.0.6312.107

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Google sheets

**Comment by gelicia** [comment]
Not sure if this is with the variable editor or the datasource. Apologies in advance if it was misassigned!

**Comment by gelicia** [comment]
This same bug was reported for Infinity datasource here https://community.grafana.com/t/variable-data-source-option-not-available-while-creating-dashboard/120899

**Comment by clementduveau** [comment]
Seems to be fixed now
