### ISSUE TITLE
Chore: Feature Flag Cleanup

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#85733]
Following feature toggles can be removed from the code in `main`:
- [enablePluginsTracingByDefault](https://github.com/grafana/grafana/blob/5aa56c93807f28c8cb93ae46687bb70024fed726/pkg/services/featuremgmt/registry.go#L1039)
- [pluginsDynamicAngularDetectionPatterns](https://github.com/grafana/grafana/blob/5aa56c93807f28c8cb93ae46687bb70024fed726/pkg/services/featuremgmt/registry.go#L512)

**Comment by sympatheticmoose** [comment]
I'm not sure we want to remove the deprecationUI one given users may wish to disable still

**Comment by tolzhabayev** [comment]
> I'm not sure we want to remove the deprecationUI one given users may wish to disable still

ok let's keep it for now, but if we want to keep this around for longer it should become a config option instead of a feature flag.

**Comment by xnyo** [comment]
> I'm not sure we want to remove the deprecationUI one given users may wish to disable still

@sympatheticmoose it's possible to mark a plugin to be ignored from all the angular UI features with this config ini change:

```ini
[plugins]
hide_angular_deprecation = grafana-polystat-panel,another-plugin-slug
```

This can still be used as a fail-safe for the angular UI features if we remove the feature toggle and make it the default.

I think this approach it is sufficient, WDYT?
