### ISSUE TITLE
grafana table graph and templating max 500 element return of elasticsearch datasource

### ISSUE THREAD

**Issue by xiaoxuan220** [grafana/grafana#8573]
Grafana version:4.1.1
Datasource:elasticsearch

table graph and template max 500 element result,how to custom this limit?TKS

**Comment by torkelo** [comment]
for templating variables you can override the default limit and set a custom size.
http://docs.grafana.org/features/datasources/elasticsearch/#query-variable

If you need more than 500 documents in the table panel then this feature request/PR migth interest you:
https://github.com/grafana/grafana/pull/8527
