### ISSUE TITLE
[Bug] Admin create user API doesn't work with LDAP backend

### ISSUE THREAD

**Issue by richleigh** [grafana/grafana#8574]
- What Grafana version are you using? 4.1.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Linux
- What did you do? 

My grafana instance is set up to authenticate against LDAP, which works correctly for interactive (web form) login with first time users.

I am trying to use the API to configure appropriate dashboards for users. In order to do this programatically, it is necessary to have the user in the global users database before their organisation specific configuration can be done. To achieve this I POST the appropriate data to /api/admin/users, before PATCHing /api/orgs/:orgId/users/:userId and other API calls.

- What was the expected result?

The user account is created in the system in the same manner regardless of whether they log in through the web interface for the first time, or are created via the API.

- What happened instead?

The account created is local to grafana, and does not sync with LDAP for things like groups, passwords etc. Additionally, there is no way to avoid specifying even a dummy password as the field is mandatory in the POST to /api/admin/users, when for LDAP users none should be specified. 

If the user has already logged in through the web interface however, then their account is synchronised properly regardless of further manipulation via the API (such as PATCHing into an organisation).

**Comment by torkelo** [comment]
Sorry to say that Grafana does not ever write to LDAP (not will it), LDAP is just the authentication & membership source.

If you need to create users programmatically you need to talk to LDAP directly

**Comment by richleigh** [comment]
The users already exist in LDAP, but not yet in Grafana. When trying to manipulate a user's settings, if they are not yet in Grafana, they need to be added to Grafana. The Grafana API call to perform this step does not work with the LDAP backend.

**Comment by torkelo** [comment]
The create user api are totally unaffected by ldap. 

You said you wanted to sync password, groups. What did you mean, what did not work?

**Comment by richleigh** [comment]
Imagine a user in LDAP:

dn:CN=Doe, John,DC=example,DC=com
cn: Doe, John
sAMAccountName: doejohn
sn: Doe
givenName: John
mail: John.Doe@example.com

and so on. The user logs in to Grafana with their username, doejohn, and password. 

If the first time John encounters Grafana is by logging in through the web front end, the entry in the user table has blanks for the password, salt and rands fields, and the login is set to 'Doe, John', email is 'John.Doe@example.com' and name is 'John Doe'. 

However, creating an account through the admin API by posting to /api/admin/users with a body of
{
     "name": "John Doe",
     "email': "John.Doe@example.com",
     "login": "doejohn",
     "password": "1234"
}

ends up with password, salt and rands all populated, and login set to 'doejohn'. It seems that users created via the the web interface uses the LDAP cn and not the real login. As a result, when the user logs in as doejohn for an account created via LDAP, Grafana finds the entry in the database, and will only accept the password 1234, rather than John's LDAP credentials. Similarly, since Grafana believes this user to be a local user rather than an LDAP user, it doesn't seem to check groups against the LDAP backend either.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/8588
