### ISSUE TITLE
Geomap: How to customize label text of edges on network layer of geomap panel

### ISSUE THREAD

**Issue by visamanx** [grafana/grafana#85752]
Good afternoon, how can I edit the direction of the label text on the edges in the Network layer, so that the text follows the direction of the line and also create bidirectional links without the text of first one being on top of the text of the second one? Would it be possible?

**Comment by tonypowa** [comment]
Thank you for your question @visamanx 

However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on[ https://community.grafana.com/](https://community.grafana.com/)

Thank you for your understanding
