### ISSUE TITLE
[Bug] edit data source shows [object Object] instead of actual error

### ISSUE THREAD

**Issue by hc000** [grafana/grafana#8577]
Please include this information:
- What Grafana version are you using? 4.3.2 (docker hub)
- What datasource are you using? InfluxDB
- What OS are you running grafana on? dockerized version on ubuntu
- What did you do? trying to connect to an influxdb instance, pressed save & Test
- What was the expected result? to produce the actual error message
- What happened instead? InfluxDB Error [object Object]

**Comment by torkelo** [comment]
can you open chrome dev tools & console ? anything interesting there? and in the network tab what is the response from the influxdb network request?

**Comment by torkelo** [comment]
Fixed, now looks better! Thanks for reporting this! 
![image](https://user-images.githubusercontent.com/10999/26947509-3fa0d4be-4c93-11e7-87a9-faa31312834d.png)
