### ISSUE TITLE
Variables not working for InfluxQL in editor mode

### ISSUE THREAD

**Issue by dkneisz** [grafana/grafana#85800]
### What happened?

I have an InfluxQL query that uses a dashboard variable. When the value is set to all or more than one value is selected the query returns no data. 
![image](https://github.com/grafana/grafana/assets/43378003/68910202-29ae-4584-97b7-f1582d86ae34)

If I switch to query mod everything is working fine.
![image](https://github.com/grafana/grafana/assets/43378003/91bb57e2-511c-4ba6-beb7-de9b33e00165)

In editor mode it also returns a result if only one value is selected. I'm using InfluxQL to query an InfluxDB 1.x.

### What did you expect to happen?

I expect the query to behave the same in editor and query mode

### Did this work before?

It worked fine in 10.3.x (don't remember the exact version I had)

### How do we reproduce it?

1. create a dashboard variable returning multiple values
2. use the variable in a query
3. select all or multiple values
4. switch between query and editor mode

### Environment (with versions)?

Grafana: 10.4.1
OS: "latest" Docker container (ARCH)
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB1

**Comment by dkneisz** [comment]
Any update on this topic? I updated to 10.4.2 and the issue is still there. I compared the queries with the query inspector. I found only one difference and that is the "rawQuery" value. For the one that is working (in query mode) it it set to "true", for the not working one to "false" (I guess that's because it's not in "raw query mode"). If I only change this to "true" in query explorer I get results. Since the rest is unchanged it seems that queries that are not in raw query mode are treated differently and therefore return no results.

Since there is a workaround this is an inconvenience, but if you use that a lot in different places you first have to find them all to fix this. If there is anything I can do to help with fixing this issue please tell me.

**Comment by tonypowa** [comment]
hi @dkneisz 
thank you for reporting this issue

Is this issue only present when using InfluxDB ?

**Comment by dkneisz** [comment]
> hi @dkneisz thank you for reporting this issue
> 
> Is this issue only present when using InfluxDB ?

Since I only use InfluxDB I can't tell you if this happens for other DBs too.

**Comment by dkneisz** [comment]
One additional Information:

When I use "raw query mode" I get the following in influxdb.log:
`"GET /query?db=openhab_db&epoch=ms&q=SELECT+distinct%28%22value%22%29+FROM+%2F%5E%28EliasBathroomCurrentTemp%7CEliasBedroomCurrentTemp%7CEliasGuestroomCurrentTemp%7CEliasHallwayCurrentTemp%7CEliasKitchenCurrentTemp%7CEliasLivingCurrentTemp%7CEliasPCRoomCurrentTemp%7CEliasToiletCurrentTemp%29%24%2F+WHERE+time+%3E%3D+1715535578108ms+and+time+%3C%3D+1715621978108ms+GROUP+BY+time%281m%29+fill%28none%29 HTTP/1.1" 200 2283 "-" "Grafana/10.4.2" c4184fc0-114f-11ef-af74-0242ac110004 10430`

When in "editor mode" I get:
`"GET /query?db=openhab_db&epoch=ms&q=SELECT+distinct%28%22value%22%29+FROM+%2F%5E%7BEliasBathroomCurrentTemp%2CEliasBedroomCurrentTemp%2CEliasGuestroomCurrentTemp%2CEliasHallwayCurrentTemp%2CEliasKitchenCurrentTemp%2CEliasLivingCurrentTemp%2CEliasPCRoomCurrentTemp%2CEliasToiletCurrentTemp%7D%24%2F+WHERE+time+%3E%3D+1715535519302ms+and+time+%3C%3D+1715621919302ms+GROUP+BY+time%281m%29+fill%28none%29+ORDER+BY+time+ASC HTTP/1.1" 200 57 "-" "Grafana/10.4.2" a10bbb4e-114f-11ef-aec5-0242ac110004 5571`

So it looks like an additional "ORDER BY time ASC" is added. In my opinion this should not make any difference to the query itself, but maybe internally it causes issues.

**Comment by itsmylife** [comment]
Could you please try this with the latest version of Grafana (`v11.1.0`)? 
The problem was fixed with this PR https://github.com/grafana/grafana/pull/85423

**Comment by dkneisz** [comment]
Sorry for the late reply. I can confirm, that it is working in v11.1.0. Thank you for fixing it.
