### ISSUE TITLE
Legend: Percentile value options displaying all percentile options

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#85828]
### What happened?

The Legend now displays ALL percentile options when clicked for a value. This is probably not the best user experience.

https://github.com/grafana/grafana/assets/46619047/b1ea94f4-bb6f-4019-9093-a963fb884c27

### What did you expect to happen?

Maybe design a new way to see percentile options.

### Did this work before?

Yes. This was a feature introduced [here](https://github.com/grafana/grafana/pull/85554). The feature's great, but the UX needs to be rethought.

### How do we reproduce it?

1. create a panel that shows a legend
2. in legend options, click the `values` dropdown
3. ...
4. profit

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by baldm0mma** [comment]
This may also be true in other areas that use reducers.

**Comment by baldm0mma** [comment]
It looks like the `Registry` returns the full list of reducers to the options builder in an "ordered" manner that gets sorted by the `this.sort()` method (packages/grafana-data/src/utils/Registry.ts:185)... which was TODO-ed 5 years ago, and never built. 😂

**Comment by leeoniya** [comment]
maybe for now rename them to have same prefix like Percentile: 1st.

or perhaps just make this percentile number an option of a single transform called Percentile. and just default to 0.5?
