### ISSUE TITLE
Circular variable dependencies cause infinite loop deadlock

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8583]
* Version: v4.3.1 (commit: befc15c)
* Datasource: InfluxDB
* OS: Debian Jessie 64bit

##### Test case 1 (no dependency):
Variable $a, query `SHOW TAG VALUES FROM measurement WITH KEY = "a"`
Variable $b, query `SHOW TAG VALUES FROM measurement WITH KEY = "b"`
###### Result:
Changing the query for variable `$a` causes a refresh for values of variable `$a`, there is no refresh for values of variable `$b` because no dependency exists between them.

##### Test case 2 (simple dependency):
Variable $a, query `SHOW TAG VALUES FROM measurement WITH KEY = "a"`
Variable $b, query `SHOW TAG VALUES FROM measurement WITH KEY = "b" WHERE a =~ /$a/`
###### Result:
Changing the query for variable `$a` causes a refresh for values of variable `$a`, this causes a refresh for values of variable `$b` because (I suspect) the JavaScript code believes the query could have changed from `SHOW TAG VALUES FROM measurement WITH KEY = "b" WHERE a =~ /^1|2$/` to `SHOW TAG VALUES FROM measurement WITH KEY = "b" WHERE a =~ /^1|2$/`, but even if the query for `$b` hasn't changed, the refresh is still being done.

##### Test case 3 (circular dependency):
Variable $a, query `SHOW TAG VALUES FROM measurement WITH KEY = "a" WHERE b =~ /$b/`
Variable $b, query `SHOW TAG VALUES FROM measurement WITH KEY = "b" WHERE a =~ /$a/`
###### Result:
Changing the query for variable `$a` causes a refresh for values of variable `$a`, this causes a refresh for values of variable `$b` because (as described above) the query *could* have changed, this causes a refresh for values of variable `$a` because the query *could* have changed, this causes a refresh of `$b`, this causes a refresh of `$a`, this causes an infinite loop deadlock.

A possible solution to this would be to check if the query has actually changed if the refresh has been triggered by another refresh:

##### Test case 4 (circular dependency):
Variable $a, query `SHOW TAG VALUES FROM measurement WITH KEY = "a" WHERE b =~ /$b/`
Variable $b, query `SHOW TAG VALUES FROM measurement WITH KEY = "b" WHERE a =~ /$a/`
###### Expected result:
Changing the query for variable `$a` causes a refresh for values of variable `$a`, this causes a refresh for values of variable `$b` to be triggered but the function checks if the query for variable `$b` has actually changed and if it hasn't, ignores the trigger and does not refresh the variable.

Note: I reported this on Slack as well: https://grafana.slack.com/archives/C0Y4TLW74/p1497153038664846

**Comment by torkelo** [comment]
Yes, circular dependencies are not supported. Should be not cause infinite loop though :)

**Comment by Fusl** [comment]
If this is not officially supported, we should consider as a feature request then as well :)

**Comment by But4ler** [comment]
+1

**Comment by AlKult** [comment]
Hi,

Would the Grafana team have any updates on the case, please?

Best regards,
Albert.

**Comment by adamf663** [comment]
If you're not going to fix it, then you need to document it and call it a feature like "automatic prevention of display of unexpected data.  Please delete this application."

**Comment by LukasJerabek** [comment]
Still desired

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!

**Comment by milinpatel13298** [comment]
Would be nice to be able to use variables with circular dependency.
If not working, it should at least be documented as such, as @adamf663 suggested.

**Comment by adamf663** [comment]
Grafana is showing all the signs of being a dead product.
