### ISSUE TITLE
time picker Crazy transition between states visible and hidden

### ISSUE THREAD

**Issue by taoyantu** [grafana/grafana#85848]
### What happened?

I deployed grafana version 9.5.17 in an offline environment, and the time picker flickering problem also occurred. My browser is chrome 90.0.4430.72, and the phenomenon is style="order: 3 visibility:visible" and style="order : 3 visibility:hidden" Crazy transition between states. Currently we want to use grafana, but this problem prevents us from using it normally. Please help and tell me what should I do? Thanks

### What did you expect to happen?

![199185712-5df8f006-784c-49f1-86d5-7eb6b2e70e78](https://github.com/grafana/grafana/assets/13854732/c89d84bb-ad2d-4ea3-b523-1fcbd9255a74)

### Did this work before?

I deployed grafana version 9.5.17 in an offline environment

### How do we reproduce it?

1.grafana version 9.5.17
2.centos offline environment
3.chrome 90.0.4430.72

### Is the bug inside a dashboard panel?

In the upper right corner of the large screen panel, the time picker

### Environment (with versions)?

Grafana: 9.5.17
OS:centos 7.2
Browser:chrome 90.0.4430.72

### Grafana platform?

A downloaded binary

**Comment by taoyantu** [comment]
@ivanortegaalba @torkelo @bergquist @marefr @ryantxu
 Please help and tell me what should I do? Thanks

**Comment by taoyantu** [comment]
This phenomenon is related to the browser version. If you use a higher version of the browser, you will not have this problem. Currently using chrome 90_0_4430_72 version, this phenomenon will occur

**Comment by tonypowa** [comment]
thank you @taoyantu for sharing the solution
Indeed for a better experience, Grafana should be run in the latest version of the browser available
