### ISSUE TITLE
[Bug][4.3.2] Limitation of values in template variable with custom size - ElasticSearch

### ISSUE THREAD

**Issue by ChamMach** [grafana/grafana#8585]
Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? ElasticSearch 2x/5x 
- What OS are you running grafana on? Docker (grafana/grafana)
- What did you do? See below.
- What was the expected result? See below.
- What happened instead? See below.

Hi,
I tried Grafana 4.3.2 and I've still a problem with template variable. 
In fact, I have a query like this : 
{"find": "terms","field":"metric","size":1000}
with regex.
So it means to Grafana "Search all the terms on the first 1000 documents and filter the result with this regex" and it's working perfectly. But, if I have more than 2147483647 of documents in my ElasticSearch and if I want to search in all the documents I have a message like this : 

![1](https://user-images.githubusercontent.com/23166349/27012546-c1a023b2-4ed1-11e7-91f1-d9102af85e86.png)

So that's why I say there is a limitation (and if I set "size": 0 it doesn't work).

Thank you.

**Comment by torkelo** [comment]
Returning all those will values hang your browser if it worked. 

If you want to search, you need to create a separate variable with the search term, then use that in the other variable definition

**Comment by ChamMach** [comment]
Good morning @torkelo,

Are you sure if it's work if I have more than 2147483647 documents on my ElasticSearch ? Because I think the "size:xxxx" option tell to Grafana to querying on only the first xxxx documents on ElasticSearch, not on all the "database". I'll try your solution tonight but I'm not sure if it will work.

**Comment by torkelo** [comment]
Well the search is done server side by elasticsearch. 

Example: 

```json
{"find": "terms”, "field": "@hostname", "query":  "@hostname:$search", "size": 1000}
```

Then you create a custom $search variable to act as your search filter. The size limit is only the number of items returned to Grafana. But if you send the search query the search is going to be done by Elasticsearch. Not ideal. The best way would be if the variable to could continuously call the query as you type in the dropdown. 

Right now variable queries are issued and options returned, and the filtering in the typeahead dropdown is done in the browser (so if your variable query returns more than a couple of thousands options its' going to hang your browser). 

There is a feature request to support a "query" part that can refetch options based on what you currently type in the variable dropdown
https://github.com/grafana/grafana/issues/7644

**Comment by ChamMach** [comment]
Okay @torkelo,
The search is done server side by Elasticsearch but the query is making and sending by Grafana.

So, this is my original query on Grafana 4.3.2 where it works on Grafana < 4.1.1 : 
![1](https://user-images.githubusercontent.com/23166349/27044082-a8fcca24-4f9c-11e7-9dec-b8be03b0850c.png)

As you can see, I have nothing returned by Elasticsearch because the default number for size is 500 and the value I wanted for this template variable is placed much further.

So, I set the size value to 1 billion (**here** I have 30 million documents in my Elasticsearch and a lot of time I have more than 3 billion) and it's working : 
![2](https://user-images.githubusercontent.com/23166349/27044354-9058ef7e-4f9d-11e7-9818-9196fe3a04ed.png)

_But_ if the values as I want is positioned after 2147483647 documents that I could have in my Elasticsearch, Grafana send this message : 
 
![3](https://user-images.githubusercontent.com/23166349/27044526-1f769bfc-4f9e-11e7-9a79-7d453c68b7e2.png)

And I can't make search on theses values as I want because Grafana has a limitation.

Because in fact, Grafana doesn't search on _all_ the database, only on the "first" value that's we set on the option "size". I think "size" is not used to determine how many value we want on the template variable but how far can we go into the database.

I tried your solution but the problem is still present, the $search doesn't work if the value I want is positioned after 500 documents by default. And also for information all of my templates variables are hidden.

I hope you understand my problem because it worked well before with high amount of document in Elasticsearch.

Thank you again for your time and your work.

**Comment by torkelo** [comment]
Sure it, does, size only limits the returned documents, not the scope of the search.

**Comment by ChamMach** [comment]
Very strange,

Because for me and with Grafana 4.1.1 and higher I can't make a search on all my Elasticsearch. 
With Grafana 4.3.2 if I don't write on my query something like "size:100000000" nothing appears. 
By default size option is "limited" to 500, right. But for this picture : 
![2](https://user-images.githubusercontent.com/23166349/27146196-bf5f0b54-5138-11e7-921f-d90400e7e615.png)

I'm sure I have more than 500 "documents" which match the query as I want. 
So maybe there is a bug with size or when you have more "target document" (for example 1000) than the value set for size (for example 500) nothing appears and the "limit" doesn't work.

Thank you for your response @torkelo and have a good day.

**Comment by torkelo** [comment]
You need to add a query field to your elasticsearch template variable query

{"find": "terms”, "field": "@hostname", "query":  "@hostname:myhost ", "size": 1000}

**Comment by ChamMach** [comment]
Yes @torkelo, but "myhost" is variable so as you already said I create a template variable like this : 

Search : 
{"find": "terms”, "field": "@metric"}
regex : xxxx 

And then I create an other template variable like this : 
{"find": "terms”, "field": "@metric", "query": "@metric:$search ", "size": 1000}

But is also doesn't work because I have no value returned by $search.

**Comment by torkelo** [comment]
?? Your search variable is empty? Then it won't work. 

Not sure where you confusing is, size just controls the number of items returned. The query field is sent to elasticsearch as a query, elasticsearch will query all documents and filter them by the query, and the  limit  by size.

**Comment by ChamMach** [comment]
Yes my search variable is empty only if I don't specify a "big" (to englobe all of my Elasticsearch documents or at least a big part) size. But when I set size to 1 billion for example it's works. I don't know what to do now because as I already said before Grafana 4.1.1 it's working good.

**Comment by torkelo** [comment]
sorry, don't understand. Can you show me the query sent to elasticsearch and the response? Is something not correct?

**Comment by ChamMach** [comment]
Sorry for my bad english @torkelo, 

Query sent to Elasticsearch : 

```
{"find": "terms", "field": "@metric"} 
regex
```

Response : 
`{"responses":[{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [@metric:()]","index_uuid":"m3ethUvNRoKxrsbyqYQWjw","index":"xxx"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"xx","node":"T_P6ZVBfRvuAq3YttWENFw","reason":{"type":"query_shard_exception","reason":"Failed to parse query [@metric:()]","index_uuid":"m3ethUvNRoKxrsbyqYQWjw","index":"xxx","caused_by":{"type":"parse_exception","reason":"Cannot parse '@metric:()': Encountered \" \")\" \") \"\" at line 1, column 9.\nWas expecting one of:\n    <NOT> ...\n    \"+\" ...\n    \"-\" ...\n    <BAREOPER> ...\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \")\" \") \"\" at line 1, column 9.\nWas expecting one of:\n    <NOT> ...\n    \"+\" ...\n    \"-\" ...\n    <BAREOPER> ...\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    "}}}}]},"status":400}]}`

If a specify size : 

Query : 
```
{"find": "terms", "field": "@metric", "size": 100000000} 
regex 
```

Response : 
```
{"responses":[{"took":15002,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":6000,"max_score":0.0,"hits":[]},"aggregations":{"3":{"doc_count_error_upper_bound":0,"sum_other_doc_count":3500,"buckets":[{"key":"xxx","doc_count":500,"1":{"value":64.63999938964844},"2":{"buckets":[{"key_as_string":"1456483856000","key":1456483856000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483857000","key":1456483857000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483858000","key":1456483858000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483859000","key":1456483859000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483860000","key":1456483860000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483861000","key":1456483861000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483862000","key":1456483862000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483863000","key":1456483863000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483864000","key":1456483864000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483865000","key":1456483865000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483866000","key":1456483866000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483867000","key":1456483867000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483868000","key":1456483868000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483869000","key":1456483869000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483870000","key":1456483870000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483871000","key":1456483871000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483872000","key":1456483872000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483873000","key":1456483873000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483874000","key":1456483874000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483875000","key":1456483875000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483876000","key":1456483876000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483877000","key":1456483877000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483878000","key":1456483878000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483879000","key":1456483879000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483880000","key":1456483880000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483881000","key":1456483881000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483882000","key":1456483882000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483883000","key":1456483883000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483884000","key":1456483884000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483885000","key":1456483885000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483886000","key":1456483886000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483887000","key":1456483887000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483888000","key":1456483888000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483889000","key":1456483889000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483890000","key":1456483890000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483891000","key":1456483891000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483892000","key":1456483892000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483893000","key":1456483893000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483894000","key":1456483894000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483895000","key":1456483895000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483896000","key":1456483896000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483897000","key":1456483897000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483898000","key":1456483898000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483899000","key":1456483899000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483900000","key":1456483900000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483901000","key":1456483901000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483902000","key":1456483902000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483903000","key":1456483903000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483904000","key":1456483904000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483905000","key":1456483905000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483906000","key":1456483906000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483907000","key":1456483907000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483908000","key":1456483908000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483909000","key":1456483909000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483910000","key":1456483910000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483911000","key":1456483911000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483912000","key":1456483912000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483913000","key":1456483913000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483914000","key":1456483914000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483915000","key":1456483915000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483916000","key":1456483916000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483917000","key":1456483917000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483918000","key":1456483918000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483919000","key":1456483919000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483920000","key":1456483920000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483921000","key":1456483921000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483922000","key":1456483922000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483923000","key":1456483923000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483924000","key":1456483924000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483925000","key":1456483925000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483926000","key":1456483926000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483927000","key":1456483927000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483928000","key":1456483928000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483929000","key":1456483929000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483930000","key":1456483930000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483931000","key":1456483931000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483932000","key":1456483932000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483933000","key":1456483933000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483934000","key":1456483934000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483935000","key":1456483935000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483936000","key":1456483936000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483937000","key":1456483937000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483938000","key":1456483938000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483939000","key":1456483939000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483940000","key":1456483940000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483941000","key":1456483941000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483942000","key":1456483942000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483943000","key":1456483943000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483944000","key":1456483944000,"doc_count":0,"1":{"value":null}},{"key_as_string":"1456483945000","key":1456483945000,"doc_count":0,"1":{"value":null}}
[..........]
{"value":null}},{"key_as_string":"1456485127000","key":1456485127000,"doc_count":0,"1":{"value":null}}]}}]}},"status":200}]}
```

**Comment by ChamMach** [comment]
Any news @torkelo ?

**Comment by torkelo** [comment]
news of what? 

The error from elasticsearch does not match what you specified

`@metric:()'`  

in the query you specified
```
{"find": "terms", "field": "@metric"} 
```

only "@metric",  not "@metric:()" , you must have show the metric query not the template variable query response.

**Comment by ChamMach** [comment]
Ok @torkelo, I think we're going round in circles.. 
The fact is, for some of my template variable if I don't specify a "high" size limit in my query I can't see the values that I want.
If the size limit worked I could at least see 500 values returned by my template variable, but I don't see anything except If I specify a big limit for size option.
That's all and I really think there is a bug with Grafana with a lot of documents since Grafana 4.1.1.

Thank again for your time and your work.

**Comment by torkelo** [comment]
> Ok @torkelo, I think we're going round in circles.

Yes, I think we are. You will have to show that somehow. I cannot replicate any issue. Size has no bearing on what you can search on, only document count returned. 

You must be doing something strange. I suggest you investigate more the query sent to elasticsearch, see if you see anything that could be the cause for the no hits.

**Comment by torkelo** [comment]
you still have not shown the response for this template variable query: 

```
{"find": "terms", "field": "@metric"} 
```

What does ES return for this query? 500 values?

**Comment by ChamMach** [comment]
You're right @torkelo,
```
For this template variable query : 
{"find": "terms", "field": "@metric"} 
with regex.
```

Sometime ES return 500 values but in most of the case it return nothing and I see response like this : 
`{"responses":[{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [@metric:()]","index_uuid":"m3ethUvNRoKxrsbyqYQWjw","index":"xxx"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"xx","node":"T_P6ZVBfRvuAq3YttWENFw","reason":{"type":"query_shard_exception","reason":"Failed to parse query [@metric:()]","index_uuid":"m3ethUvNRoKxrsbyqYQWjw","index":"xxx","caused_by":{"type":"parse_exception","reason":"Cannot parse '@metric:()': Encountered \" \")\" \") \"\" at line 1, column 9.\nWas expecting one of:\n <NOT> ...\n \"+\" ...\n \"-\" ...\n <BAREOPER> ...\n \"(\" ...\n \"*\" ...\n <QUOTED> ...\n <TERM> ...\n <PREFIXTERM> ...\n <WILDTERM> ...\n <REGEXPTERM> ...\n \"[\" ...\n \"{\" ...\n <NUMBER> ...\n <TERM> ...\n ","caused_by":{"type":"parse_exception","reason":"Encountered \" \")\" \") \"\" at line 1, column 9.\nWas expecting one of:\n <NOT> ...\n \"+\" ...\n \"-\" ...\n <BAREOPER> ...\n \"(\" ...\n \"*\" ...\n <QUOTED> ...\n <TERM> ...\n <PREFIXTERM> ...\n <WILDTERM> ...\n <REGEXPTERM> ...\n \"[\" ...\n \"{\" ...\n <NUMBER> ...\n <TERM> ...\n "}}}}]},"status":400}]}`

All of my regex is something like this : 
`/.*Group Cpu.(?!.*ft.|.*vmotion.|.*idle.|.*vmkapimod.|.*drivers.|.*helper.|.*system.|.*\..).*Ready*/ `

Maybe the problem of all of this is my regex or even my mapping file for Elasticsearch (5.4) : 
```
{	
	"mappings": {
		"xxx":{
					"_all":{"enabled":false},
					"date_detection":false,
					"numeric_detection":true,
					"properties":{
					"@hostname":{"type":"keyword"},
					"@metric":{"type":"keyword"},
					"@timestamp":{"type":"date","format":"MM/dd/yyyy HH:mm:ss"},
					"@value":{"type":"float"}
					}
				}
	}
}
```

Or maybe it is the number of requests that are sent simultaneously to Elasticsearch when the dashboard is loading.. Or maybe my server is not powerful enough.

I will investigate more when I have more time but if you have an idea, do not hesitate to ask it here.

Thank a lot.
