### ISSUE TITLE
[Bug] Installing Grafana on Ubuntu 16.04.2. LTS installs version with "wrong" version info

### ISSUE THREAD

**Issue by CodingSpiderFox** [grafana/grafana#8587]
- What Grafana version are you using?
`grafana -v` -> "Version master (commit: NA)"
- What OS are you running grafana on?´
Ubuntu 16.04.2 LTS
- What did you do?
sudo apt-get install grafana && grafana -v
- What was the expected result?
The major.minor.bugfix version number should be displayed (e.g. "4.3.2 (commit: < ID >))
- What happened instead?
"Version master (commit: NA)" was displayed

Best regards

**Comment by torkelo** [comment]
Please use our official apt repo, the  you will get corret version. 

Follow the Debian install guide on docs site for more info on the official grafana apt repo. I suspect you installed from the main Debian apt repo that has an old broken and unofficiall package

**Comment by CodingSpiderFox** [comment]
I find it annoying adding a repo for each program I use.
Will the package in the Ubuntu repository be fixed?

**Comment by torkelo** [comment]
don't think so, not added by us, will ask some at canonical

**Comment by CodingSpiderFox** [comment]
Thanks a lot already
