### ISSUE TITLE
[Feature request] Allow creation of users without password when LDAP is enabled

### ISSUE THREAD

**Issue by haidaraM** [grafana/grafana#8588]
Hi,
Is it possible to allow creation of users without a password ? I know this seems strange but here is our use case : we have LDAP authentification enabled so no password is stored in Grafana. We want to create dynamically some organizations and dashboards and assign specific users to them. These users already exist in our LDAP server but not in Grafana when the organizations are created. 

Right now, when we want to create a new user with the REST API, we have to specify a password. Then this password can also be used to login. So we will end up with two passwords for one user: the one stored in the LDAP Server and the one in Grafana DB and both can be used to login.

One workaround for this, is to directly connect to the Grafana DB and then create the user through a SQL statement without specifying a password, a salt and rands.

- What Grafana version are you using? 
4.3.2
- What OS are you running grafana on?
Centos 7

**Comment by natalysheinin** [comment]
@haidaraM have you found a workaround that works for you?

**Comment by haidaraM** [comment]
Hmm I just create each user with a different strong random password. User can still connect with their LDAP password. @natalysheinin

**Comment by bkez322** [comment]
I'm also doing as @haidaraM is doing. It certainly works, but it would be nice if we didn't have to provide a garbage password through the API.
