### ISSUE TITLE
Auth: Fix login with generic OAuth when api_url is not configured

### ISSUE THREAD

**Issue by dmihai** [grafana/grafana#85891]
### What happened?

When trying to login with SSO using generic OAuth, the login failed with the following details in logs:
```
logger=oauth.generic_oauth t=2024-04-10T00:38:55.384768223Z level=error msg="Error getting email address" url=/emails error="Get \"/emails\": unsupported protocol scheme \"\""
logger=authn.service traceID=9ff48e209dba8c61b663087ad052a758 t=2024-04-10T00:38:55.384824283Z level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.userinfo.error] failed to get user info: Error getting email address: Get \"/emails\": unsupported protocol scheme \"\"
```
The `api_url` is not required for this SSO integration and it's left empty. 

Looking at [the implementation](https://github.com/grafana/grafana/blob/e3314f04e4813ae6a86e14a09c475e49a018840d/pkg/login/social/connectors/generic_oauth.go#L478) it seems that the authentication flow tried to retrieve the email by calling the `api_url` suffixed with the string `/emails`.

### What did you expect to happen?

The authentication flow for generic OAuth should not have attempted to call the `api_url + "/emails"` endpoint to retrieve the email because in this case the api_url is empty.

### Did this work before?

Did not try to reproduce this error in previous versions.

### How do we reproduce it?

1. Configure SSO for generic OAuth with no api_url endpoint configured.
2. Try to login with SSO using generic OAuth.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by ADTmux** [comment]
Hey, could I work on this?

**Comment by PyAgni** [comment]
@dmihai I took the liberty to raise a PR since no one has picked this. Let me know what you think. Thanks!
