### ISSUE TITLE
Change Grafana title on the login page

### ISSUE THREAD

**Issue by lohithbula** [grafana/grafana#8589]
Read before posting: 

hi 
I'm trying to change the grafana title name below the logo in the login page to some other name. can anyone help me out.
i'm using  Grafana 4.2.0
thank you 
![grafana1](https://user-images.githubusercontent.com/28143698/27029811-7d3b1388-4f87-11e7-84cf-6a71f365391d.JPG)

**Comment by torkelo** [comment]
this is currently not possible without modifying the code and rebuilding

**Comment by lohithbula** [comment]
can u please tell me where should i modify the code to change the grafana title

**Comment by moiramathew** [comment]
public/css/grafana.dark.min.af13213c.css. 

grafana_wordmark:before {
    content: "*";

Change content. Replace the * with what you want

**Comment by moiramathew** [comment]
I'm still working on the title. Can anyone help?

**Comment by svzain** [comment]
@moiramathew just grep "window_title_prefix" and change "Grafana - " to anything you want.

**Comment by Varulv1997** [comment]
> this is currently not possible without modifying the code and rebuilding

It is actually possible by a simple trick, the title you want to change is not a text it's actually an image (just spec it by dev tools in your browser), track the path and change it to your own logo image or if you only want to keep the above logo simply replace it with a transparent png image.

**Comment by mohit0231** [comment]
IMPORTANT POINT:

— — — — — — — — — — — — — — — — — — — — — — — — — — — — — — Location /usr/share/grafana/public/img contains all the images including our {Favicon , grafana logo , background image,grafana-logo-wordmark} by the names {fav32.png , grafana_icon.svg , heatmap_bg_test.svg,grafana_typelogo.svg } respectively. You can directly drop your own images here and make the login page look yours. But I got a no. of complaints from the users that the changes took place properly in their localhost /server but when a remote user tried to access the same Grafana page, they can’t see these changes happening. So to avoid these bugs follow me in this blog . — — — — — — — — — — — — — — — — — — — — —
HERE WE GO STEP BY STEP :

    First save all your images (Favicon , grafana logo , background image, Logo wordmark ) at a remote location in the cloud , in my case I am saving it on AWS S3 and being public ally accessible .
    Once I saved it on AWS S3 , all my images will generate a unique url to access it anywhere on the internet , please keep all those urls handy .
    Changing Favicon and Title :

Go to /usr/share/grafana/public/views/index.html and search for and for favicon

Change title by replacing [[.AppTitle]] and Paste your Favicon public url , in my case its aws s3 public url which I pasted here in place of [[.Favicon]] and after the change it looks like

Replaced Title by our company name and replcaed favicon by our favicon public url, In our case its aws s3 public url

So by now our Favicon and Title is successfully changed.

    Changing Grafana-Logo and Background image :

Go to /usr/share/grafana/public/build/ and search for the file app.****.js

ls|grep app.****.js

and then search for the keyword “heatmap_bg_test.svg” and “grafana_icon.svg” in this file, whatever places you find this keyword in the file replace the complete “src” & “url” with your own “public url” of your background image and the grafana_icon. The file looks quite messy if you open it with vim editor !

grafana_icon.svg might be at several places in this file , dont forget to replace your url at every place

    Changing Grafana-Logo-Wordmark :

Go to /usr/share/grafana/public/build/ and search for the file grafana.dark.****.css

ls|grep grafana.dark.****.css

and then search for the keyword “grafana_typelogo.svg” and replace the complete url by your own aws s3 logo word mark url ! Then restart your docker /server and kaboom ! The customized results looks awesome!

Grafana login screen looks like ours ! Favicon , title , logos , background everything changes and customized just like the way we want !

BONUS CUSTOMIZATION :

If you want to change the title in every screen , after you login to Grafana as well. Then go to /usr/share/grafana/public/build/DashboardPage.****.js and search for the keyword “document.title” and then change it like this document.title=r.title+” — ”.

Hope you liked this blog ! Follow me on this Grafana series to explore more about the service and if you are unaware about my last two blogs in this series then here are the links ! FYI , the next blog in the series will be on “AuthProxy” so stay tuned for that and many more awesome blogs !
