### ISSUE TITLE
Auth: Add support to filter for parent teams in GitHub connector's team membership filter

### ISSUE THREAD

**Issue by mgyongyosi** [grafana/grafana#85916]
Currently the GitHub connector's team membership filter only filters for teams that the currently authenticated user directly assigned to and doesn't consider the parent teams, so for example when someone specifies the parent team id in the `team_ids` then users won't be able to login if they are not directly assigned to the particular team on GitHub (they are assigned to one of the nested/sub teams).

Extend the GitHub connector team membership filter implementation to filter among the parent teams as well.

Relevant part:
https://github.com/grafana/grafana/blob/8461310e36395fad37cea4bb12c8fcb446b06806/pkg/login/social/connectors/github_oauth.go#L135-L154

More info about teams:
- [About teams](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams)
- [REST API endpoint docs](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-teams-for-the-authenticated-user)

**Comment by wasim-nihal** [comment]
Hi @mgyongyosi , is this open for contribution? I'd like to work on this.
Also, the link above for [REST API endpoint docs](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams) seems to incorrectly point towards GitHub teams. Can you please point me to the correct REST API docs here?

**Comment by mgyongyosi** [comment]
Hi @wasim-nihal, yes, great! Let me know if you have any questions!

> Also, the link above for [REST API endpoint docs](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams) seems to incorrectly point towards GitHub teams. Can you please point me to the correct REST API docs here?

Thanks, it has been updated!
