### ISSUE TITLE
Alering: Document how to verify that Alertmanger HA gossip is working

### ISSUE THREAD

**Issue by stevesg** [grafana/grafana#85913]
Docs here:
https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/

We should add a few lines about how to verify that HA is working, something along the lines of:

`alertmanager_cluster_members` should be the number of replicas
`alertmanager_peer_position` should be different depending on the replica: for two replicas, one should have a `alertmanager_peer_position==0` and the other `alertmanager_peer_position==1`

**Comment by brendamuir** [comment]
@grobinson-grafana can i grab you to help with this one before you head off?? thanks!

**Comment by brendamuir** [comment]
@stevesg would you be willing to add some rough draft docs on this that I can review? I am not sure of the technicalities of HA, so that would help greatly. Thanks!
