### ISSUE TITLE
panel/dashboard-list: Search by tag in all folders

### ISSUE THREAD

**Issue by LarsStegman** [grafana/grafana#85919]
### What happened?

It's not possible to search in all folders for dashboards. I cannot deselect the folder to search in. 
![image](https://github.com/grafana/grafana/assets/9332816/82abbf26-e1dc-499d-8ee2-e93bc1fa89b9)

### What did you expect to happen?

I can search in all folders

### Did this work before?

Not that I know

### How do we reproduce it?

1. Create multiple dashboard folders
2. Create a Dashboard List panel
3. Search for tag
4. It will only search for dashboards with the tag that are in the unnested folder.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10.4.1
OS: Linux
Browser: Edge

### Grafana platform?

Kubernetes

**Comment by ashharrison90** [comment]
hi! thanks for raising this 🙌

we have a new folder picker in grafana 11 that fixes the problem completely 🥳 

![image](https://github.com/grafana/grafana/assets/20999846/43aff40c-7cc1-4c56-b5ca-392361b958eb)
