### ISSUE TITLE
[Feat Req]: Different series color palette for each color theme

### ISSUE THREAD

**Issue by jsha** [grafana/grafana#8592]
The automatic assignment of colors to graph lines can sometimes pick a dark purple that is pretty close to indistinguishable on a black background, especially if there is any amount of glare.
See this example: ![screenshot from 2017-06-12 11-59-45](https://user-images.githubusercontent.com/220205/27050239-a52c9004-4f66-11e7-89f7-e71e7cf02311.png)

Color assignments should be background-aware (if they aren't already) and should be skewed towards more visible colors, even if that comes at a cost of having colors that are less distinct from others on the same graph.

**Comment by torkelo** [comment]
Yea, looks bad. 

it is at the end of the color spectrum so you would have to have 45+ series for that color to be chosen automatically.

**Comment by torkelo** [comment]
this was implemented in v6
