### ISSUE TITLE
[Feature request] Not all measurements are displayed in drop down

### ISSUE THREAD

**Issue by mgresser** [grafana/grafana#8593]
It looks like in https://github.com/grafana/grafana/pull/8092 a hard limit was placed on the number of items displayed in the measurement list. In our environment we have just over 100 measurements in one of our databases resulting in a few not being visible to users. Would it be possible to change this from a hard coded value to a configurable option that defaults to 100? Setting this to a static value seems more rigid than is necessary.

Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? Influxdb
- What OS are you running grafana on? CentOS 7
- What did you do? Selected the list of measurements from the dropdown
- What was the expected result? All measurements in the database should be displayed
- What happened instead? Only the least recently created 100 measurements were displayed.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
