### ISSUE TITLE
Operations on Metrics Series - for ES data source

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#8594]
Wanted to check if there is any way I can apply any operation(add/subtract/multiply/divide) --- on metrics e.g. A-B

Grafana does it nicely for Graphite DS... is it possible for Elasticsearch... its hard to find conversion % ... if I have Series A - which gives me total Visits and Series B - which gives me total orders... i want to do TotalOrders / TotalVisits

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
Elasticsearch does not support operations on results sadly. 

We hope to support this sometime for all data sources via meta queries: https://github.com/grafana/grafana/issues/8594

**Comment by gbrian** [comment]
Got the same issue and created: https://github.com/gbrian/grafana-timelion-datasource
Use at your own risk 😄 but at least for me is working fine

![image](https://user-images.githubusercontent.com/767180/41027350-1177e6c0-6977-11e8-9e2c-a6b68567ab4f.png)
