### ISSUE TITLE
[Feature request] Provide support for Oracle as backend database for grafana.

### ISSUE THREAD

**Issue by niranjanpai** [grafana/grafana#8595]
Grafana currently supports mysql, sqllite and postgres as backend databases. Can we add support for Oracle also as a backend database? We should be able to store user details, dashboards and sessions in Oracle.

- What Grafana version are you using?
   4.2

**Comment by Necrontyr** [comment]
This feature would be much appreciated in a production setting where Oracle is already heavily used and distributed, so all of our perf metrics live there already , I just want the power of grafana to render them

**Comment by MarkRx** [comment]
+1. Oracle is a common Enterprise database

**Comment by JekRock** [comment]
That would be great!

**Comment by bedrin** [comment]
Looks like Oracle is now supported by xorm. Will it unblock the development?

**Comment by squaptor** [comment]
+1 Oracle would be great for existing enterprise solutions

**Comment by zoltanbedi** [comment]
Oracle is one of our enterprise plugin https://grafana.com/grafana/plugins/grafana-oracle-datasource

**Comment by zoltanbedi** [comment]
@zackman0010 Sorry I misunderstood this feature request. I'm going to convert it to discussion as we use GitHub discussions for feature requests.
