### ISSUE TITLE
[Bug] Unable to change unit when selected kilovolt-ampere reactive (kvar) in Axes

### ISSUE THREAD

**Issue by layjump** [grafana/grafana#8596]
-  Grafana version are you using?
3.2.0
- What datasource are you using?
graphite
- What OS are you running grafana on?
macOs Sierra 10.12
- What Web Browser and version?
chrome 58.0.3029

- What did you do?
1. select y-axis unit kilovolt-ampere reactive (kvar) 
2. select another unit example: none > short
- What was the expected result?
unit will be changed to Short
- What happened instead?
y-axis unit still to be kilovolt-ampere reactive (kvar) 

Hi, this can be reproduce in http://play.grafana.org/, Thanks.
It seem the length of value of unit "kilovolt-ampere reactive (kvar)" is greater than the unit's max width，it has a class max-width-15。
In order to display the whole value "kilovolt-ampere reactive (kvar)", input turn to two line.
When click the options of units, the input will be cleanup which make it turn to one line.
This cause the unit options move up and make cursor lost focus on option。

**Comment by torkelo** [comment]
thanks for reporting this!
