### ISSUE TITLE
XY Graph: Unable to use time for point colour

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#85978]
### What happened?

I attempted to use the "time" field to apply colour to an XY plot. This is a common use case so that we can see how relationships change over time.

Instead of applying the colour gradient from the lowest time range to the highest one as expected, all values are simply the same colour. This occurs regardless of whether the feild is an actual time field or its converted to a "number". 

The workaround is to apply a series of transforms to the time field to make the numbers much much smaller. Once this is done, the colour gradient works as expected. I suspect that the issue is caused by the internal variables being used to calculate the colour are too small (e.g. 32 bit, but should be 64bit?). This workaround is cumbersome and not ideal for a production environment.
![Kapture 2024-04-11 at 08 58 26](https://github.com/grafana/grafana/assets/99200643/c6ecdfe6-fc3d-4d2a-947d-59ef76f872ae)

### What did you expect to happen?

I expect that selecting the "time" field correctly applies a colour range

### Did this work before?

No, however I used to do this exact thing when using the [natel plotly panel](https://github.com/NatelEnergy/grafana-plotly-panel). This is an Angular plugin however and we are attempting to migrate away from these in light of the upcoming deprecation of Angular plugins.

### How do we reproduce it?

1. Make an XY panel and load in time series data.
2. Set "Color Scheme" to red-yellow-green or any other gradiant.
3. Set "Point Color" to "Time" --> Does not work
4. Apply transforms to the time to make it smaller and change "Point Color" to that new field --> Now works as expected.

### Is the bug inside a dashboard panel?

[debug-server requests-2024-04-11 16_19_35.json.txt](https://github.com/grafana/grafana/files/14948714/debug-server.requests-2024-04-11.16_19_35.json.txt)

### Environment (with versions)?

Grafana: Grafana v11.1.0-69051 (https://github.com/grafana/grafana/commit/9d44c8e8cf3e934e68e3ff8e78e752e2773f83ca) // Enterprise
OS: Mac OS 14
Browser: Chrome 123

Also tested as being present in Grafana 10.2. 

### Grafana platform?

None

**Comment by leeoniya** [comment]
this works correctly in the new xychart panel (fully rolled out now in hosted Grafana, or behind the `autoMigrateXYChartPanel` feature toggle in grafana v11.1)
