### ISSUE TITLE
[Bug]Modified the height of the panel to an extra small value will lead the display of the panel in a wrong way.  

### ISSUE THREAD

**Issue by mafeil** [grafana/grafana#8597]
-  Grafana version: 3.2.0
- CentOS 6.6
- Repro steps:
1. Create a dashboard and add a Graph panel
2. Set height to 1 in General tab
3. Save the dashboard
4. Back to dashboard
Expected result:
The modified panel will be displayed as the height set.
Actual result:
The panel displayed an error in the top-left corner and the border of the panel is changed to smaller but the stat displayed not small.

![stats_is_smaller_than_border](https://user-images.githubusercontent.com/29397280/27076090-c0f3b044-505e-11e7-8613-4ce04ff725d0.png)
![error1](https://user-images.githubusercontent.com/29397280/27076091-c12fd222-505e-11e7-8d80-c5406507c2e6.png)

.

**Comment by torkelo** [comment]
Graph panel as some size requirements. Needs to be bigger than 1px :)

**Comment by mafeil** [comment]
ok, i set the height to 59, it displayed normally, but set to 58, it pops error. That's to say 58 is the boundary value of the graph height. So i think it's better to add some information of the height text box to tell users of the fact result if set the value smaller than 59. Or set a minimum size of the graph panel in advance so that if users set a value below the bar, it will not make effect on the panel, better than popping errors and displayed it in a wrong way :)
