### ISSUE TITLE
[Bug] yarn install --pure-lockfile hangs on stage 3/4 Linking dependencies...

### ISSUE THREAD

**Issue by NathanJAdams** [grafana/grafana#8598]
- Grafana version - 4.4.0
- OS - Fedora 24 x86_64
- Steps taken - Tried installing following this http://docs.grafana.org/project/building_from_source/
- Expected result - Grafana installed
- Actual result - Hangs on command yarn install --pure-lockfile - 3/4 Linking dependencies...

I've gone through the steps outline in the web page mentioned above. However when getting to the "yarn install --pure-lockfile" command it hangs on step 3/4 Linking dependencies... I've tried it a few times but had to Ctrl-C it as it just hung for several minutes without any indication it was doing anything.
The "top" command shows that the node process is at 60-80% while the progress bar is progressing, then disappears when the progress bar disappears.

Two things that may be of interest:
1. The yarn install command couldn't be run as written...it came back with a "bash: yarn: command not found" error. I had to run it as "node_modules/yarn/bin/yarn install --pure-lockfile" instead.
2. I'm behind a proxy so had to add a "https_proxy=<my_proxy> before the actual install command.

After Ctrl-C-ing it, an error message came back as follows:
`Error: Cannot find module '../errors.js'`
`    at Function.Module._resolveFilename (module.js:325:15)`
`    at Function.Module._load (module.js:276:25)`
`    at Module.require (module.js:353:17)`
`    at require (internal/module.js:12:17)`
`    at _load_errors (/<my_username>/work/golang/src/github.com/grafana/grafana/node_modules/yarn/lib-legacy/cli/index.js:48:20)`
`    at /<my_username>/work/golang/src/github.com/grafana/grafana/node_modules/yarn/lib-legacy/cli/index.js:388:34`
`    at run (/<my_username>/work/golang/src/github.com/grafana/grafana/node_modules/yarn/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)`
`    at /<my_username>/work/golang/src/github.com/grafana/grafana/node_modules/yarn/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28`
`    at flush (/<my_username>/work/golang/src/github.com/grafana/grafana/node_modules/yarn/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)`
`    at nextTickCallbackWith0Args (node.js:436:9)`

That's all I've got and am stumped. Hope it can be of some use.

**Comment by torkelo** [comment]
Make sure yarn is installed
npm install -g yarn

yarn install --pure-lockfile

it will take time as it needs to download packages, usually around 30 seconds if your on good internet.

**Comment by NathanJAdams** [comment]
That looks like it's working now thank you!
For future reference, what was missing was the "-g" option.
Is there any way of not requiring that option?
