### ISSUE TITLE
Generic oauth not able to parse oauth2.0 profile api's response

### ISSUE THREAD

**Issue by abdheshkumar** [grafana/grafana#8600]
I am trying to authenticate user with CAS server using oauth2.0. It is authenticating successfully and returning below authenticated user's profile json by calling api `oauth2.0/profile?access_token=AT-1-L9ufjAgzTKdsf1trCJby952TitYfdUkBSGn`. but below json is not parsing into grafana UserInfo struct.
Grafan's Error:
```
t=2017-06-13T12:51:24+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=178.78.120.2 time_ms=69 size=709

t=2017-06-13T12:59:43+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="json: cannot unmarshal string into Go struct field .attributes of type []string"

```
oauth2.0/profile?access_token api response:
```
{
  "attributes":
  {
    "display_name": "Hugo Williams",
    "email": "hwilliams@gmail.com",
    "LdapAuthenticationHandler.hwilliams": "uid=hwilliams,ou=users,dc=callhandling,dc=com",
    "login": "LoginName",
    "name": "Williams",
    "username": "hwilliams"
  },
  "id": "hwilliams"
}
```

**Comment by DanCech** [comment]
This doesn't look like any sort of openid connect style response.

**Comment by abdheshkumar** [comment]
If you want to know more about, please see the below link code.
CAS's  Oauth2.0 always return authenticated's user profile as `attributes` array object.
```
{
  "attributes":  {  },
  "id": "hwilliams"
}
```
https://github.com/apereo/cas/blob/3e3940fbfbc35731a477f4f891df32b19d9d4063/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileControllerController.java#L141 But Grafana's user need profile api response in below format
```
var data struct {
		Name        string              `json:"name"`
		DisplayName string              `json:"display_name"`
		Login       string              `json:"login"`
		Username    string              `json:"username"`
		Email       string              `json:"email"`
		Attributes  map[string][]string `json:"attributes"`

``` 
which would never unmarshal anyway.

https://github.com/grafana/grafana/blob/8422697199ffa21cda664644d7af459ad4efc3cc/pkg/social/generic_oauth.go#L169

**Comment by abdheshkumar** [comment]
@torkelo https://github.com/grafana/grafana/pull/6226 would solve this issue?

**Comment by torkelo** [comment]
No, think the response is not valid for this OAuth provider

**Comment by abdheshkumar** [comment]
@torkelo Thanks! you can see their code https://github.com/apereo/cas/blob/3e3940fbfbc35731a477f4f891df32b19d9d4063/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileControllerController.java#L141 they always returning below profile's API response.
```
{
  "attributes":
  {
    "display_name": "Hugo Williams",
    "email": "hwilliams@gmail.com",
    "LdapAuthenticationHandler.hwilliams": "uid=hwilliams,ou=users,dc=callhandling,dc=com",
    "login": "LoginName",
    "name": "Williams",
    "username": "hwilliams"
  },
  "id": "hwilliams"
}
```
I just wanted to know this is an issue in CAS server or grafana?

**Comment by torkelo** [comment]
user profile needs to return "name" and "email" fields directly, not nested inside attributes object

**Comment by idanielblake** [comment]
CAS 5.2 added a cas.authn.oauth.userProfileViewType=FLAT|NESTED option. I used it but was unsucessful. Did you try that? I get this error from cas:
`<Could not identify and extract access token request>
org.apereo.cas.services.UnauthorizedServiceException: Unable to locate OAuth service in registry for client null`

And garafana:
`error="oauth2: cannot fetch token: 400 \nResponse: error=invalid_grant"`

**Comment by Turing-Chu** [comment]
#### did someone saw this error?
```
t=2017-12-28T16:41:35+0800 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"message\":\"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.\",\"hint\":\"Authorization code has been revoked\"}"
```

**Comment by sparse91** [comment]
Finally, I could make this work with CAS 5.3:

grafana.ini:
```
[auth.generic_oauth]
enabled = true
name = CAS OAuth
allow_sign_up = true
client_id = myid
client_secret = mysecret
;scopes = user:email,read:org
scopes =
auth_url = https://casserver/cas/oauth2.0/authorize
token_url = https://casserver/cas/oauth2.0/accessToken
api_url = https://casserver/cas/oauth2.0/profile
;team_ids =
;allowed_organizations =
```

CAS properties:
```
cas.authn.oauth.userProfileViewType=FLAT
```

Service:

```
{
  "@class" : "org.apereo.cas.support.oauth.services.OAuthRegisteredService",
  "clientId": "myid",
  "clientSecret": "mysecret",
  "bypassApprovalPrompt": true,
  "serviceId" : "^https://grafanaserver.*",
  "name" : "grafana",
  "id" : 100,
  "jsonFormat" : "false"
  "supportedGrantTypes": [ "java.util.HashSet", [ "authorization_code", "password", "client_credentials", "refresh_token" ] ],
  "supportedResponseTypes": [ "java.util.HashSet", [ "code", "token" ] ],
  "attributeReleasePolicy":
  {
    "@class" : "org.apereo.cas.services.GroovyScriptAttributeReleasePolicy",
    "authorizedToReleaseCredentialPassword": "false",
    "authorizedToReleaseProxyGrantingTicket": "false",
    "excludeDefaultAttributes": "true",
    "groovyScript" : "file:/etc/cas/script/oauth.groovy"
  }
```

oauth.groovy:
```
import java.util.*

def Map<String, List<Object>> run(final Object... args) {
    def attrs = args[0]
    def logger = args[1]
    def principal = args[2]
    def service = args[3]

    return [ email:[attrs['email']], username:[principal.id], name:[attrs['name']]]
}
```
