### ISSUE TITLE
[Bug] Blank screen when passing authentication in authentication header with Auth-Proxy

### ISSUE THREAD

**Issue by patvallerand** [grafana/grafana#8602]
Hi, 
I open this bug because I have a weird issue with our grafana setup. Our grafana server listen on loopback interface and we are using Apache as a reverse proxy and auth-proxy.
We are using Grafana v4.3.2. on Centos 7 and we have an issue when using auth-proxy feature. Here are the scenario:

When we access to grafana URL, the browser ask for credential. If we entered it manually it work. However when we try to put authentication information in authentication header by using https://username:password@grafana.url we get authenticated and after get a blank screen. I said authenticated because when we click manually in the url bar and resend a request by doing enter and we got the graph (Refreshing does not give this behaviour). I have done the same test by using Firefox and Chrome (IE does not support authentication in URL) and got the same result.

Here is my Apache conf for name based vhost for grafana
```
 ServerName grafana.url
 Header set Access-Control-Allow-Origin    "*"
 Header set Access-Control-Allow-Methods   "GET, OPTIONS"
 Header set Access-Control-Allow-Headers   "origin, authorization, accept"
 Header set Access-Control-Allow-Credentials true
 <Proxy *>
  AuthLDAPBindDN [BIND DN COMMON NAME PATH]
  AuthLDAPBindPassword [PASSWORD]
  AuthLDAPURL "ldap://XXX/\
               OU=XXX,\
               OU=XXX,\
               DC=XXX,\
               DC=XXX,\
               DC=XXX\
               ?sAMAccountName?sub?(objectClass=*)"
  AuthType Basic
  AuthName "USE YOUR ADPROD WINDOWS ACCOUNT"
  AuthBasicProvider ldap
  AuthUserFile /dev/null
  Require valid-user
  RewriteEngine On
  RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
  RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"
 </Proxy>

 RequestHeader unset Authorization

 SSLEngine On
 SSLCertificateFile [SSLCertificateFilePath] 
 SSLCertificateKeyFile [SSLCertificateKeyFilePath]
 ProxyRequests Off
 ProxyPreserveHost On

 ProxyPass / http://127.0.0.1:3000/
 ProxyPassReverse / http://127.0.0.1:3000/
```

Also here is sample of my grafana.ini
```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

[auth.basic]
enabled = true

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
```

Best Regards

**Comment by torkelo** [comment]
not sure what it could be, unable to replicate it with nginx reverse proxy. I know many use this setup ad never heard of a problem like this. 

What does the apache logs and grafana log say? what is returned with the blank screen? (open chrome dev tools network tab)

**Comment by torkelo** [comment]
closing for lack of update / details
