### ISSUE TITLE
[Feat Req]: MySQL control sort order of returned series 

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8604]
Grafana Version: 4.3.2
Datasource: MySQL
OS: Windows 2008 Server

Dashboards legends order are random and are changing after every refresh. I can order by value (click in legend  column (min, max, avg...) ), but is not possible to sort by name of the legend/metric.

For MySQL datasource i don't find any option to sort legends by name.

This is one MySQL SQL query that i use:

SELECT
UNIX_TIMESTAMP(REFMONTH)  as time_sec,
SUM(PARQUE) as value,
SERVICO as metric
FROM ADSL_STATS
WHERE $__timeFilter(REFMONTH) AND TIPO='ADSL'
GROUP BY SERVICO, UNIX_TIMESTAMP(REFMONTH)
ORDER BY time_sec ASC

Adding metric field to ORDER BY has no impact.

Thanks

**Comment by kalyanbitra** [comment]
Hi,

Is this issue is fixed in any of the builds ?

**Comment by torkelo** [comment]
> Is this issue is fixed in any of the builds ?

Sorry no :( 
Next time, check if the issue still open it means it is unresolved / implemented / fixed.

**Comment by carnival18** [comment]
is there a plan to fix this issue? and when?  thanks.

**Comment by carnival18** [comment]
why fmcmarques closed this issue?

**Comment by torkelo** [comment]
dunno, reopened it :)

**Comment by carnival18** [comment]
I am trying modifying the source code to resolve this issue, but it seems to be a hard work.

**Comment by torkelo** [comment]
The easiest way is to solve it in the query, just order by metric first then timestamp asc.

**Comment by carnival18** [comment]
@torkelo I have tried as you said, but still not work.

**Comment by fmcmarques** [comment]
Sorry by the mistake closing the issue.

Ordering by metric first and then timestamp has no efect.

SELECT
UNIX_TIMESTAMP(REFMONTH)  as time_sec,
ROUND(SUM(TRAFEGO_MB/1024)) as value,
SERVICO as metric
FROM NET_STATS
WHERE $__timeFilter(REFMONTH) AND TIPO='ADSL'
GROUP BY SERVICO, UNIX_TIMESTAMP(REFMONTH)
ORDER BY SERVICO, time_sec ASC

Same behaviour!!

**Comment by torkelo** [comment]
> Ordering by metric first and then timestamp has no efect.

strange works when we test it here. Maybe it's the group by that is causing MySQL to not sort properly. When you execute the query directly against MySQL is the order random? Grafana does no sorting so it should be whatever MySQL returns

**Comment by robinsonjj** [comment]
I also get a random ordering, my query doesn't have a group by and I get the same order each time I run the generated query against mysql outside of grafana

if there are any logs that might be useful I can send them over / try and investigate on my side

**Comment by robinsonjj** [comment]
fwiw I've checked the network in tab in chrome, if I click the grafana refresh icon, post requests are sent to api/tsdb/query with identical payloads however the order of the series in the response from each request is different

**Comment by carnival18** [comment]
waiting for a solution.

**Comment by fmcmarques** [comment]
Without group by, same behaviour.

SELECT
UNIX_TIMESTAMP(REFDATE) as time_sec,
INCONSISTENCIAS_NE as value,
EXCHANGE as metric
FROM INCONSISTENCIAS_ASSINANTES
WHERE $__timeFilter(REFDATE) 
ORDER BY EXCHANGE, time_sec ASC

**Comment by torkelo** [comment]
so your mysql query is returning data in random order even after you ordered by EXCHANGE? very strange.

**Comment by carnival18** [comment]
i have downloaded the source code, which file is the main file to execute the mysql query?

**Comment by daniellee** [comment]
@carnival18 https://github.com/grafana/grafana/blob/master/pkg/tsdb/mysql/mysql.go

**Comment by fmcmarques** [comment]
"so your mysql query is returning data in random order even after you ordered by EXCHANGE". Yes, correct.

**Comment by pdoan017** [comment]
@robinsonjj 
I came up with a similar idea to that, but this would only sort the keys by increasing value. Wouldn't be able to sort by descreasing.

**Comment by robinsonjj** [comment]
yeah, I just wanted to make sure the series were in the same order every time so that the line colors stop changing every time I refresh or zoom in - feel free to edit or replace that pull request with a better one :)
