### ISSUE TITLE
[ISSUE] Grafana Basic Auth is not working with Graphite server

### ISSUE THREAD

**Issue by mananpreetsingh** [grafana/grafana#8605]
- What Grafana version are you using?
   Latest Image from docker hub

- What datasource are you using?
Graphite

- What OS are you running grafana on?

Docker for Mac latest 

- What did you do?
Trying to pull the metrics from graphite using basic auth

- What was the expected result?
Datasource should work

- What happened instead?
Giving an error as explained below and attachment

I am using sitespeedio graphite image for docker and latest for grafana.

So graphite is basic Auth protected "guest/guest" as per sitespeedio container. When I try to create datasource in grafana using basic auth it does not work gives Unknown error in Grafana but seems some issue with 'Access-Control-Allow-Origin' in graphite config. So when I checked on grafana and graphite side you can see what's happening in the attachment.

Left side Grafana config and on the right the Error that I am getting when I click on save and test    button for grafana datasource.

On top right, that is the nginx config in Graphite container, where specified the password file.

On bottom right that the error t hat I can see on nginx logs.

Not sure which side is the error Grafana or Graphite container, So I opened similar issue with sitespeedio as well to get more information.

<img width="1410" alt="screen shot 2017-06-13 at 12 22 52 pm" src="https://user-images.githubusercontent.com/27379172/27093293-2043ada4-5034-11e7-9c97-33d73f70498d.png">

thanks,
Manan

**Comment by mananpreetsingh** [comment]
I think I found the issue, If I use service name of the container from compose file it works fine but If I use localhost then it does not.

like in http url: http://graphite:80 works but http://localhost:80 does not , even though http://localhsot:80 it is accessible via browser and http://graphite:80 is not .

**Comment by torkelo** [comment]
you need to configure CORS with your Graphite server, or use "proxy" access in Grafana data source settings

**Comment by mananpreetsingh** [comment]
@torkelo I did configure CORS,  as I showed the config file in my first screenshot. but it still did not work.

**Comment by daniellee** [comment]
@mananpreetsingh any reason for not using Proxy mode? Using direct mode is only for special cases.

**Comment by mananpreetsingh** [comment]
I tried with proxy as well, exact same results. But If I use container name in url then it works but if I use localhost in url then it does not.

**Comment by torkelo** [comment]
your CORS setup seems incorrect, you need to except OPTIONS call from the basic auth and always allow it. Browsers do not send basic auth credentials in this call (OPTIONS call is done automatically by browsers)

**Comment by mananpreetsingh** [comment]
you mean I gotta remove  'OPTIONS' from CORS 'Access-Control-Allow-Methods' ?

**Comment by torkelo** [comment]
no, I mean you have to exempt the OPTIONS operation from the basic auth, so that it is always allowed, even with no authorization header
