### ISSUE TITLE
[Bug] Grafana Error to save a copy of existing dashboard or import a saved json file as new dashboard

### ISSUE THREAD

**Issue by ygprakash** [grafana/grafana#8606]
Hello Grafana Team,

We’re facing issues with Grafana.

Version used- Grafana v4.2.0.

• Error 1- Error while trying to create a dashboard from a saved json file

• Error 2- Even we’re unable to “save as” (a copy) of existing dashboard

Please include this information:
- What Grafana version are you using?
   V 4.2.0
- What datasource are you using?
   InfluxDB, Dashboard will be saved to mysql DB
- What OS are you running grafana on?
 RHEL 6.
- What did you do?
   Trying to create a dashboard from a saved json file
   Trying to save as” (a copy) of existing dashboard
- What was the expected result?
   Successful dashboard creation/save 
- What happened instead?
   Getting Dahsboard not found/ 404 errors (Refer to the Grafana error log in the below comment)

  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

t=2017-06-13T16:33:31+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"
t=2017-06-13T16:33:31+0200 lvl=eror msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/import status=500 remote_addr=172.31.26.185 time_ms=10ns size=40
t=2017-06-13T16:33:31+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"
t=2017-06-13T16:33:31+0200 lvl=eror msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/import status=500 remote_addr=172.31.26.190 time_ms=10ns size=40
t=2017-06-13T16:33:31+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"
t=2017-06-13T16:33:31+0200 lvl=eror msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/import status=500 remote_addr=172.31.26.190 time_ms=9ns size=40
t=2017-06-13T16:33:32+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"
t=2017-06-13T16:33:32+0200 lvl=eror msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/import status=500 remote_addr=172.31.26.190 time_ms=8ns size=40
t=2017-06-13T16:33:32+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"
t=2017-06-13T16:33:32+0200 lvl=eror msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/import status=500 remote_addr=172.31.26.185 time_ms=6ns size=40
t=2017-06-13T16:33:32+0200 lvl=eror msg="Failed to import dashboard" logger=context userId=1683 orgId=265 uname=gyenugon error="Dashboard not found"

t=2017-06-13T16:38:34+0200 lvl=info msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/db/ status=404 remote_addr=172.31.26.185 time_ms=17ns size=54
t=2017-06-13T16:38:35+0200 lvl=info msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/db/ status=404 remote_addr=172.31.26.185 time_ms=15ns size=54
t=2017-06-13T16:38:35+0200 lvl=info msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/db/ status=404 remote_addr=172.31.26.185 time_ms=14ns size=54
t=2017-06-13T16:38:35+0200 lvl=info msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/db/ status=404 remote_addr=172.31.26.185 time_ms=15ns size=54
t=2017-06-13T16:38:35+0200 lvl=info msg="Request Completed" logger=context userId=1683 orgId=265 uname=gyenugon method=POST path=/api/dashboards/db/ status=404 remote_addr=172.31.26.185

**Comment by torkelo** [comment]
Strange, no other reports on failing imports or save as. 

Can you provide the json your trying to import and the json for the dashboard your tried to "Save As" (View JSON)

**Comment by ygprakash** [comment]
Hello Torkelo,

There is an issue with our DB, we're working on it. Might be that is the one hard stooping to save dashboards and we're receiving the above listed errors. 

Will get back to you if the issue is not solved. 

Thanks alot for your quick response.
You can close the ticket.

Thanks,
Gowtham
