### ISSUE TITLE
[Bug] singlestat can't use tag/filter like tagname=*

### ISSUE THREAD

**Issue by skygragon** [grafana/grafana#8608]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
OpenTSDB
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Configure singlestat to query single metric, but use tag like "tagname=*", then error occurs like:
```
boot.5ee7468a.js:46 Panel data error: Error: Multiple Series Error
    at b.setValues (boot.5ee7468a.js:20)
    at b.onDataReceived (boot.5ee7468a.js:20)
    at f.emit (boot.5ee7468a.js:52)
    at a.emit (boot.5ee7468a.js:52)
    at b.handleQueryResult (boot.5ee7468a.js:46)
    at i (boot.5ee7468a.js:42)
    at boot.5ee7468a.js:42
    at o.$eval (boot.5ee7468a.js:42)
    at o.$digest (boot.5ee7468a.js:42)
    at o.$apply (boot.5ee7468a.js:42)
```

- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by skygragon** [comment]
The same error will also occur if choose "none" aggregator w/o specifying tags.

**Comment by torkelo** [comment]
You query must only return a single series

**Comment by skygragon** [comment]
Nope, there is always one metric returned, but if you use "none" as the aggregator, the JSON response will contain an array like:
```
[{"metric":"active.request.number_value","tags":{"dc":"dc1","host":"host01"},"aggregateTags":[],"query":{"aggregator":"none","metric":"active.request.number_value","tsuids":null,"downsample":null,"rate":false,"filters":[{"tagk":"dc","filter":"dc1","group_by":true,"type":"literal_or"}],"index":0,"rateOptions":null,"filterTagKs":["AAAB"],"explicitTags":false,"tags":{"dc":"literal_or(dc1)"}},"dps":{}},{"metric":"active.request.number_value","tags":{"dc":"dc1","host":"host02"},"aggregateTags":[],"query":{"aggregator":"none","metric":"active.request.number_value","tsuids":null,"downsample":null,"rate":false,"filters":[{"tagk":"dc","filter":"dc1","group_by":true,"type":"literal_or"}],"index":0,"rateOptions":null,"filterTagKs":["AAAB"],"explicitTags":false,"tags":{"dc":"literal_or(dc1)"}},"dps":{}}]
```
You see every item in the array is for metric "active.request.number_value", but it send the raw data without any aggregation thus each item represent one single data.

As singlestat panel, it could/should understand this array format and merge those data into one thus we can continue displaying total/first/last/max value against it.
