### ISSUE TITLE
Loki. Error when using "or" statements in line filter

### ISSUE THREAD

**Issue by norcalspearo** [grafana/grafana#86086]
### What happened?

{env="sandbox"} |= "error" or "fatal"
parse error at line 1, col 31: syntax error: unexpected STRING

### What did you expect to happen?

No error. Search returns statements with  "error" or "fatal"

### Did this work before?

This is a new feature I was hoping to use:
https://github.com/grafana/grafana/pull/78705

### How do we reproduce it?

{env="sandbox"} |= "error" or "fatal"

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.3.3 (252761264e)
OS: Windows 11 Pro
Browser: Chrome 123.0.6312.106 (Official Build) (64-bit)

### Grafana platform?

None

**Comment by matyax** [comment]
@norcalspearo Thanks for reporting this. What is your Loki version?

**Comment by norcalspearo** [comment]
Loki version is 2.9.3-510

**Comment by norcalspearo** [comment]
![LokiError](https://github.com/grafana/grafana/assets/166888869/f7ee5667-33d3-4ba6-ab6b-b19b0e669e0b)

**Comment by matyax** [comment]
@norcalspearo Grafana frontend has support for the feature, but Loki needs to be 3+. Apologies for the confusion!
