### ISSUE TITLE
[Bug]/[Feature request] Elastic Search Raw Document not sorted by date 

### ISSUE THREAD

**Issue by reecesmith** [grafana/grafana#8611]
Hi Grafana,

When using Elastic Search as a data source and viewing JSON as a raw document, the dashboard doesn't show the latest document and seems to show random ones

![image](https://user-images.githubusercontent.com/29427730/27127785-3a72c0a0-50f4-11e7-950d-bed6c00370c6.png)

![image](https://user-images.githubusercontent.com/29427730/27127974-c8839306-50f4-11e7-958d-df2176843bf8.png)

I'm not sure if this is a bug or a feature request, but we really need a way of getting the last document. 

Thanks in advance. Please let me know if you need further information
Reece Smith
Snr Analyst @ BGC

**Comment by torkelo** [comment]
In the picture of your table panel you can see that the table is configured to sort on the first column. You can sort by any column (click the column header)

**Comment by reecesmith** [comment]
That worked, I still think it might be worth adding information on default sort when setting up the query so that people are not confused. 

Thanks for coming back so quickly
