### ISSUE TITLE
Unable to use ExploreMetrics feature

### ISSUE THREAD

**Issue by wouter2397** [grafana/grafana#86121]
### What happened?

In the new Grafana 11 preview release, we should be able to use the new ExploreMetrics feature.
Unfortunately when deploying the new version as a docker container I'm not able to use this feature.

Please help me to determine if I'm facing a configuration issue or a bug
 

### What did you expect to happen?

According to the [docs](https://grafana.com/docs/grafana/latest/explore/explore-metrics/) this feature should be available in the Explore view as a submenu "Metrics".

As you can see in screenshot below this sub menu is not visible for me.

![Screenshot 2024-04-15 131208](https://github.com/grafana/grafana/assets/23476743/79833b75-944d-4498-8f59-1d3356fa945d)

Also found [this code](https://github.com/grafana/grafana/blob/41e4b95b51a00f44facbde969efe9a6229107a54/pkg/services/featuremgmt/registry.go#L975C19-L975C33) which shows the feature should be enabled by default

To make sure I explicitly enabled the feature in my docker image I configured the following grafana.ini:
```
[feature_toggles]
# there are currently two ways to enable feature toggles in the `grafana.ini`.
# you can either pass an array of feature you want to enable to the `enable` field or
# configure each toggle by setting the name of the toggle to true/false. Toggles set to true/false
# will take presidence over toggles in the `enable` list.

;enable = feature1,feature2

;feature1 = true
;feature2 = false
exploreMetrics = true
```

### Did this work before?

No

### How do we reproduce it?

1. Run the grafana/grafana:11.0.0-preview image.
2. Configure Prometheus datasource

### Environment (with versions)?

I've tested with the following docker images:
```
grafana/grafana:11.0.0-preview
grafana/grafana-oss:11.0.0-preview
grafana/grafana-enterprise:11.0.0-preview
```

### Grafana platform?

Docker

**Comment by mary-sitzenstatter** [comment]
@wouter2397 when you end up using the feature, we would love to hear any feedback that you have :)

**Comment by wouter2397** [comment]
@adrapereira Thanks for your reply. I enabled the `datatrails` feature flag and now Explore Metrics is available to me.

@mary-sitzenstatter I can now start playing with it. If I have feedback I will definitely share this.
