### ISSUE TITLE
Grafana + InfluxDB: add field-key on x-axis while keeping time

### ISSUE THREAD

**Issue by tcloaa** [grafana/grafana#8612]
Hi,

Is it possible to do something like: 

<img width="1280" alt="getstarting-dashboard_1" src="https://user-images.githubusercontent.com/8750937/27128758-7c2f9a20-5132-11e7-848e-1483249873ca.png">

while we can add some field-key name under each histogram in Grafana?
( The data in InfluxDB shall be like timestamp, field-key = id, so under each histogram, we can add `id1`, `id2`, ...., which is associated with corresponding timestamp (time).

Thanks,

**Comment by torkelo** [comment]
No it's not possible. You will have to decide what you on X-Axis, either time or series name, combining them is not possible

**Comment by tcloaa** [comment]
Is it not possible for all panels? (graph, singlestat, etc)
