### ISSUE TITLE
[Support Request] Grafana 4.3.2 and InfluxDB v1.2 - No graph

### ISSUE THREAD

**Issue by ktrev** [grafana/grafana#8614]
Please find the Dashboard I created below. 
I am not able to see the metrics query editor 
I have successfully added the Datasource and tested the connection. It is working.
I am using telegraf as a collector and influx db has data collected from telegraf.

OS - ubuntu 14

![image](https://user-images.githubusercontent.com/9925644/27140880-48b84c8e-5144-11e7-8033-12d04fabb6f7.png)

**Comment by daniellee** [comment]
Click on the title (where it says Panel Title) and this menu will pop up:

![image](https://user-images.githubusercontent.com/434655/27147412-0081fa20-513d-11e7-94e8-82d3243c92e4.png)

Then click on edit.

Here is a guide to getting started with dashboards: https://www.youtube.com/watch?v=sKNZMtoSHN4&index=7&list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2

**Comment by daniellee** [comment]
We know that these first steps can be hard for new users and we hope to address that in the near future. If you have any more questions then ask on our community site and we will help you there: https://community.grafana.com/

**Comment by ktrev** [comment]
Thank You for the help.
