### ISSUE TITLE
"Metric lookup" field. Grafana+Prometheus

### ISSUE THREAD

**Issue by django-kz** [grafana/grafana#8615]
Hello ! 
I am using Grafana v. 4.3.1
Datasource is Prometheus
OS is CentOs
I have an issue with "Metric lookup" field in any inserting elements( like graphs, tables etc). Seems that Grafana just dont want to  show more then some fixed number of metrics in that field. But in a raw response (through chome dev tools) I can see that all metric names were coming in Reponse to "http://MyIP/:MyPort/api/datasources/proxy/2/api/v1/label/__name__/values" request

I attached reponse file, but it's very long : ). It just shows that I have many metrics there, and I cant find them in Grafana. If I type metric name in "Metric lookup" filed, I can get the output, but if I dont know metric's name in advance it will be hard to find it.

**Comment by torkelo** [comment]
You just have to know part of it, the drop down has a limit of 500 or 1000 items, but if you specify part of the name you can filter it down
