### ISSUE TITLE
[BUG] Arrow keys not working to shift time range

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#8617]
- What Grafana version are you using?

  v4.3.2

- What datasource are you using?

  Prometheus

- What OS are you running grafana on?

  Server: Linux Debian
  Client: Chromium Linux Arch

- What did you do?

  * opened dashboard. default time range: last 1h.
  * pressend left arrow key to shift to go back in time

- What was the expected result?

  * Change time range setting to show previous time range

- What happened instead?

  * Nothing
  * No errors in js console

**Comment by torkelo** [comment]
The shortcut needs to be prefixed with  `t`
<img width="777" alt="screen shot 2017-06-15 at 10 59 05" src="https://user-images.githubusercontent.com/10999/27187645-bcfe1086-51b9-11e7-8776-ccd46045e226.png">

**Comment by grobie** [comment]
Oh, thanks! Is this new? The help text of the carrot signs next to the
selected time range need to get updated then. They only mention arrow keys.
