### ISSUE TITLE
[Feature request] add custom external link on navbar

### ISSUE THREAD

**Issue by darasion** [grafana/grafana#8619]
Hi,

i want to add custom external link on global navbar for returning to the main site, like this:
![a](https://user-images.githubusercontent.com/234933/27161033-24d7e13c-51ab-11e7-9385-8f293b106263.png)

Thanks.

**Comment by torkelo** [comment]
Go into dashboard settings, then links tab, there you can create external links shown below the nav. Grafana needs to own the nav, so we can guarantee a good experience and so we can make changes to the top nav without breaking dashboards

**Comment by darasion** [comment]
All right, I see. Thanks for reply.
