### ISSUE TITLE
[FEATURE] template "custom" type should offer a "ALL" choice

### ISSUE THREAD

**Issue by prune998** [grafana/grafana#862]
When creating a template variable of type "custom", you have to split every value by commas. 
Then you can chose one of the value in the dropdown menu but you can't chose "ALL" values, as you can do with a "query" type. 

This is on grafana 1.9 with influxdb backend.

**Comment by sknolin** [comment]
I also would like this option. Sometimes 'custom' just makes sense - for example, you have a set of arbitrary network ports that you want to monitor, not keyed by a metric. 

You have to manually select all of those each time you reload the page.

**Comment by mtanda** [comment]
May be fixed by https://github.com/grafana/grafana/pull/3113

**Comment by utkarshcmu** [comment]
This issue can be closed now as #3113 is merged.
