### ISSUE TITLE
[Bug] Font Awesome spinner is meant to be pulsing (`fa-spinner fa-spin` vs `fa-spinner fa-pulse`)

### ISSUE THREAD

**Issue by lwbt** [grafana/grafana#8620]
Read before posting: done.

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue.
  - Searched for results on "spinner" in all issues reported, found no related result
- Checkout FAQ:
  - Found no guidelines how to report, uh let's say design issues
- Checkout How to troubleshoot metric query issues:
  - This is not a metrics issue

Please prefix your title with [Bug] or <s>[Feature request]</s>. 

Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? not applicable to this bug
- What OS are you running grafana on? Ubuntu 16.04 with packages from packagecloud.io repository (http://docs.grafana.org/installation/debian/)
- What did you do? Wait for a panel to refresh itself.
- What was the expected result? A loading indicator should be shown. Font Awesome provides a few options but `fa-spinner` should be used with `fa-pulse` instead of `fa-spin` (See http://fontawesome.io/examples/ → Animated Icons)
- What happened instead? `fa-spinner fa-spin` was shown. While there is no clear statement on the FA project page, this doesn't look like a recommended pattern. The pulsing spinner is identifiable as an active element even at small display sizes. It also "moves" or "rotates" a bit faster.
- <s>If related to metric query / data viz:</s>

One just needs to replace every instance of `fa-spinner fa-spin` with `fa-spinner fa-pulse` found in this repo (5 files apparently) or select another icon to use as a spinner, but `fa-spinner fa-pulse` looks like the FA authors intended to have their spinner to look like.

---

For curious readers: I modified the files below on my Ubuntu installation. Some of these files appear to be generated from other files in this repository. 

```
/usr/share/grafana/public/app/app_bundle.js
/usr/share/grafana/public/app/boot.d709d8d5.js
/usr/share/grafana/public/app/core/partials.js
/usr/share/grafana/public/app/features/alerting/partials/alert_tab.html
/usr/share/grafana/public/app/features/dashboard/partials/shareModal.html
/usr/share/grafana/public/app/features/panel/panel_directive.js
/usr/share/grafana/public/app/features/panel/panel_directive.ts
```

**Comment by torkelo** [comment]
what do you mean? there is spin & pulse,  more a taste thing of which one you prefer :)

**Comment by lwbt** [comment]
What I mean: There are 8 *differently* shaped dots. One animation makes the biggest move clockwise in steps, the other animation ignores the desired effect of a pulsing spinner (which had been done before elsewhere as GIF animations) and just applies a 360° spin.

You can make the point that implementing design wrong can be a matter of taste. Consider that consumers don't enjoy feeling sick watching some stereoscopic or VR content. That's a more exaggerated comparison what this is about. :)

**Comment by torkelo** [comment]
> You can make the point that implementing design wrong can be a matter of taste. 

What? there is nothing here about what is right or wrong. 
http://fontawesome.io/examples/ 

The pulse has very nauseating effect where it bobs up and down a bit. But maybe it's just me.

**Comment by torkelo** [comment]
but can test it out and see what others think.

**Comment by lwbt** [comment]
Thanks for your consideration. If it's not too much too ask an option to set the preferred string would also be ok.
