### ISSUE TITLE
Influxdb: Repeater not working in Editor Mode

### ISSUE THREAD

**Issue by DanBlaisRithmik** [grafana/grafana#86208]
### What happened?

When using a repeated panel there's no data returned if using Editor Mode with the $Variable in the SELECT query. However it works in Raw Query Mode. 

### What did you expect to happen?

There should be data returned for either Raw Query Mode or Editor Mode.

### Did this work before?

Worked in 10.2.2

### How do we reproduce it?

1.  Create a dashboard with a variable to InfluxDB data. For example create a variables `Sensors` which returns all fields in a measurement (`SHOW FIELD KEYS FROM x` where x is the measurement)
2. Create a panel querying Influx data with `Repeat by variable` on `Sensors`
3. In the Panel SELECT field use `$Sensors`
4. No data will be returned
5. Switch to Raw Query Mode, data is returned.

### Environment (with versions)?

Grafana Cloud: 11.1.0
Grafana OpenSource: 10.4.2, 10.4.1 (docker image grafana/grafana)
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by itsmylife** [comment]
@DanBlaisRithmik Is this your use case? 
![image](https://github.com/grafana/grafana/assets/820946/e7073190-c555-4d54-9bda-dad2747aaabe)

**Comment by DanBlaisRithmik** [comment]
Yes assuming `cpu_field_keys` is a variable

**Comment by itsmylife** [comment]
Yes, it is a variable. Then, I have a reproduction. I'll fix it soon. Thanks for reporting it.
