### ISSUE TITLE
[Bug] Slack doesn't show attached graph

### ISSUE THREAD

**Issue by euqen** [grafana/grafana#8623]
I have faced with the problem that slack doesn't show attached image, if image dimensions are more than 400x500px. Slack documentation says that this image will be resized, but I assume that it's not correct. I have found similar issue here:  https://github.com/slackhq/slack-api-docs/issues/53
So it seems that the guys from slack are not going to fix this issue, unfortunately.
So currently grafana makes png with 800x400px, therefore is it possible to make png smaller, at least 400x500 px?

**Comment by torkelo** [comment]
strange, we are not having any issues with slack images. The image is not attached, only linked to. 

Do you have any more info on what is failing? Is the image rendered correctly? did it used to work?

**Comment by euqen** [comment]
@torkelo Yes, image is rendered correctly, grafana successfully uploads it into my webdav server. Also I debugged webhooks which grafana sends and image_url is absolutely correct.

Also slack has message builder which shows how message will be displayed using specific JSON. And [here is my slack notification](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22color%22%3A%22%2336a64f%22%2C%22fallback%22%3A%22%5BOK%5D%20Ping%20Response%20Time%20alert%22%2C%22fields%22%3A%5B%5D%2C%22footer%22%3A%22Grafana%20v4.3.2%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fgrafana.com%2Fassets%2Fimg%2Ffav32.png%22%2C%22image_url%22%3A%22http%3A%2F%2Fm03.mohito.net%3A8888%2Fwebdav%2FB2j1lDg3XaczVEVxx3et.png%22%2C%22text%22%3A%22%40euqen%22%2C%22title%22%3A%22%5BOK%5D%20Ping%20Response%20Time%20alert%22%2C%22title_link%22%3A%22%22%2C%22ts%22%3A1497455952%7D%5D%7D) with my graph image and [here is test notification](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22color%22%3A%22%2336a64f%22%2C%22fallback%22%3A%22%5BOK%5D%20Ping%20Response%20Time%20alert%22%2C%22fields%22%3A%5B%5D%2C%22footer%22%3A%22Grafana%20v4.3.2%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fgrafana.com%2Fassets%2Fimg%2Ffav32.png%22%2C%22image_url%22%3A%22https%3A%2F%2Fgrafana.com%2Fassets%2Fimg%2Fblog%2Fmixed_styles.png%22%2C%22text%22%3A%22%40euqen%22%2C%22title%22%3A%22%5BOK%5D%20Ping%20Response%20Time%20alert%22%2C%22title_link%22%3A%22%22%2C%22ts%22%3A1497455952%7D%5D%7D) with test image. (if slack will infinite load the preview, click on Compact then back to Clean) So as you can see first link doesn't display an image, but the second one is displaying. I've just picked random picture from google which is more than 400x500px, and slack also didn't show it.

**Comment by euqen** [comment]
@torkelo Hi, have you got any news according to this issue?

**Comment by torkelo** [comment]
I do not think it has to do with size as any size image works for me in slack (unless it is a limitation on slack free tier). No one else has complained about this and the image size has always been what it is.

Are you sure that http://m03.mohito.net:8888/webdav/B2j1lDg3XaczVEVxx3et.png is accessible from the internet (slack needs to be able to access it)
