### ISSUE TITLE
API for creating, modifying and removing alerts

### ISSUE THREAD

**Issue by AlekSi** [grafana/grafana#8624]
From http://docs.grafana.org/http_api/alerting/

> You can use the Alerting API to get information about alerts and their states but this API cannot be used to modify the alert. To create new alerts or modify them you need to update the dashboard json that contains the alerts.

It would be nice to have API for creating, modifying and removing alerts.

**Comment by torkelo** [comment]
since alerts are tied currently to dashboards & dashboard panels, it needs to be done through the dashboard api.

**Comment by AlekSi** [comment]
Is there an open issue for that?

**Comment by AlekSi** [comment]
There is none because that's already possible: http://docs.grafana.org/http_api/dashboard/ accepts full dashboard model definition, including alerts.
