### ISSUE TITLE
[Bug] Mails sent from GrafanaCloud marked as spam at Microsoft mail services

### ISSUE THREAD

**Issue by Zero3** [grafana/grafana#8627]
(Moved from https://github.com/grafana/grafana/issues/8069)

Mails sent from GrafanaCloud is going straigh to my spam folder in my Office365 mail account. The relevant headers explain why:

> X-Forefront-Antispam-Report: CIP:104.130.122.5;IPV:NLI;CTRY:;EFV:NLI;SFV:SPM;SFS:(8196002)(31640200002)(2980300002)(438002)(286005)(359002)(199003)(349900001)(189002)(349012);DIR:INB;SFP:;SCL:9;SRVR:VI1PR0602MB2991;H:mail5.static.mailgun.info;FPR:;SPF:Pass;MLV:ovrnspm;A:1;MX:1;PTR:mail5.static.mailgun.info;CAT:HSPM;LANG:en;

From https://technet.microsoft.com/en-us/library/dn205071.aspx: "The message was marked as spam by the content filter."

From https://technet.microsoft.com/en-us/library/jj200686.aspx: "High confidence spam" + "Deliver the message to the recipients’ Junk Email folder."

I'm not sure what will solve this besides people marking the mails as non-spam. Perhaps changing the generic test notification to include personalized information (User name, organization name, randomized values/graph) and removing stuff like remote images will make the mails more spam filter friendly.

> X-Microsoft-Antispam: UriScan:;BCL:8;PCL:0;RULEID:(23075)(22001)(8251501002)(3001016)(71702078);SRVR:VI1PR0602MB2991;
From https://technet.microsoft.com/en-us/library/dn759623(v=exchg.150).aspx: "The message is from a bulk sender that generates a high number of complaints"

As I read this, it means that the server you send mails from at Mailgun sends too many mails that people mark as spam, so Microsoft is blocking it.

**Comment by torkelo** [comment]
> As I read this, it means that the server you send mails from at Mailgun sends too many mails that people mark as spam, so Microsoft is blocking it.

Not sure there is easy way to solve this. Maybe we need to change mail sender service. Does it continue to be marked as spam after you flagged it as non spam? 

Please open GrafanaCloud related issues here: 
https://community.grafana.com/c/grafanacloud

**Comment by Zero3** [comment]
> Not sure there is easy way to solve this. Maybe we need to change mail sender service.

Either that, or a dedicated IP with them (which may or may not help).

> Does it continue to be marked as spam after you flagged it as non spam?

Yes. I just tested.

> Please open GrafanaCloud related issues here:

Sorry, I did not know that this issue was off-topic for this repository. I don't plan on creating a separate account on that community site just to submit this issue though.
