### ISSUE TITLE
[Bug] histogram in graph panel

### ISSUE THREAD

**Issue by sergesvr** [grafana/grafana#8628]
Please include this information:
- What Grafana version are you using?
4.3.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Ubuntu
- What did you do?
Using the graph panel, wrote a query (that works) and then change the x axis to "Histogram"
- What was the expected result?
To get an histogram with the x axis corresponding to the buckets corresponding the y axis time series.
To get y axis in the histogram view that can be show percentage of counts.
- What happened instead?
x axis values and number of buckets is erratic.
Defining 20 buckets only show 10 buckets
Values are not at all related to the time series y-values ([-20,+20]) while the x axis in the histogram view goes from 0 to 20. Then if i change the number of buckets from auto to 10 i got a x axis range that goes from 0 to 2.0 more or less
- If related to metric query / data viz:

**Comment by torkelo** [comment]
Can you include your data? (check response from your query), and your graph settings, also some screenshots to highlight what you think is wrong.

**Comment by sergesvr** [comment]
Before clicking on histogram
![image](https://user-images.githubusercontent.com/24296679/27197021-078a3bd6-520d-11e7-95f2-766b5c2f05ca.png)

After clicking on histogram
![image](https://user-images.githubusercontent.com/24296679/27197054-268c0b7c-520d-11e7-8309-39fdf51227ca.png)

After changing the number of buckets
![image](https://user-images.githubusercontent.com/24296679/27197082-44ba9334-520d-11e7-9249-a8deb01d5cd3.png)

**Comment by torkelo** [comment]
yea, looks a bit strange, @alexanderzobnin maybe you can investigate when you have time

**Comment by alexanderzobnin** [comment]
I'm stupid. For some reason, I added code which (WTF?) cuts values below 0. Fixing this.

**Comment by larrymeng** [comment]
How to write Query in prometheus data_source?

**Comment by torkelo** [comment]
https://prometheus.io/docs/querying/basics/

**Comment by larrymeng** [comment]
thanks.
I means, how to write Query in order to create Histogram-Graph in grafana?

**Comment by torkelo** [comment]
normal time seriers queries are the only one supported for prometheus.

**Comment by larrymeng** [comment]
Really?

**Comment by alexanderzobnin** [comment]
Histogram mode is Grafana-side processing. It converts regular time series into the histogram.

**Comment by celine-m-s** [comment]
Hello!
I have the same issue as mentioned above, whereas we are using the latest version (5.2.2). Maybe I'm missing something?
When I select "time", negative values appear on the abscissa axis but when I turn "Histogram' on, they disappear. Do you know where this can come from?
Thanks!
