### ISSUE TITLE
[Feature request] Pause/Resume Refreshing button

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#8629]
Please include this information:
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Elasticsearch 2.4
- What OS are you running grafana on?
Windows Server 2012 R2

It would be very helpful to have a Pause/Resume button on the dashboard, maybe right next to the time picker. This button allows us to switch from monitoring mode (with certain Refreshing interval to Analysis mode (no refreshing need) with a single click instead of having to go through 3 steps

1. Click on Time picker
2. Change Refreshing every to Off
3. Hit Apply

Then we'll have to remember the existing refreshing interval and repeat same steps to get back to monitoring mode.

**Comment by mattttt** [comment]
This might be a good opportunity for a keyboard shortcut.

**Comment by anhlqn** [comment]
Any chance that this will be implemented as a button or a shortcut?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
