### ISSUE TITLE
Table date error displaying

### ISSUE THREAD

**Issue by temamagic** [grafana/grafana#8630]
Mysql, `date` in base are (int)
When I try set type in table on `Date` there is a wrong time. 
What's whong?

![image](https://user-images.githubusercontent.com/15264697/27200662-54c09ce0-5223-11e7-852f-9512e8ab86bc.png) - string
![image](https://user-images.githubusercontent.com/15264697/27200668-5b837264-5223-11e7-978f-beadaaa38bf3.png) - date

**Comment by torkelo** [comment]
try multiplying by 1000, the date needs to be unix epoch in milliseconds
