### ISSUE TITLE
[Feature request] Advanced query editor

### ISSUE THREAD

**Issue by miton18** [grafana/grafana#8631]
- What Grafana version are you using? **4.3.x**
- What datasource are you using? **Warp10**
- What OS are you running grafana on? **Linux**

Hi everyone,

I work on the Warp10 Grafana datasource, queries are performed with WarpScripts, like Prometheus and PromQL. My problem is about the **QueryCtrl** of the datasource.

I want to make a V2 of the Warp10 Grafana Datasource, on the V1 I made something terrible, I call SystemJS on my QueryCtrl to load the Ace editor, like that:
https://github.com/miton18/grafana-warp10/blob/master/src/query_ctrl.js

So now, I switched to Typescript and I ask for you, what is the best way to make a query editor with Syntax Highlighing and autocompletion ?

**Comment by torkelo** [comment]
> So now, I switched to Typescript and I ask for you, what is the best way to make a query editor with Syntax Highlighing and autocompletion ?

Not sure. We plan to add Ace editor to prometheus and MySQL query editors sometime later this year

**Comment by daniellee** [comment]
@miton18 do you mean that you have it working with the Ace editor in JavaScript but that it does not work with TypeScript?

**Comment by miton18** [comment]
Yes actually, it works on the V1, because, I call SystemJs to load Ace / my language / my theme. and then I put a random ID on the query editor template.

here : https://github.com/miton18/grafana-warp10/blob/master/src/editor.js

I don't want to do this again.

An angular directive exist to do that :
https://github.com/angular-ui/ui-ace

but at the datasource plugin level, I cannot register a new module in Angular.

**Comment by miton18** [comment]
I found a workaround, 
In the middle of the query template, I can import a webComponent :
https://github.com/miton18/grafana-warp10/blob/feat/v2/src/template/query.pug

inside this webComponent, I can make a gateway between the textarea which is in the webcomponent directive, and bind him with my Ace editor in the shadow dom : 
https://github.com/miton18/grafana-warp10/blob/feat/v2/src/template/ace-editor.pug

Oh no ! your browser doesn't support webcomponents ? it's OK, the browser interpret the webcomponent as a 'div' and show the textarea which is inside

I can publish the component is someone want to reuse it :-)

**Comment by daniellee** [comment]
@miton18 interesting, I'll have a look. Are you going to be submitting your changes as a PR to the Warp10 plugin in the [grafana-plugin-repository](https://github.com/grafana/grafana-plugin-repository)?

**Comment by miton18** [comment]
We will wait for a stable v2 version and yes I will make a PR to include the plugin as an official one

**Comment by alexanderzobnin** [comment]
@miton18 We working on integrating Ace into grafana, new component will be reusable and you will have ability to include it in your data source without any terrible hacks. I think it will be something like this:
```html
<code-editor content="ctrl.target.rawSql" on-change="ctrl.panelCtrl.refresh()"
  data-mode="sql" data-theme="monokai">
</code-editor>

**Comment by miton18** [comment]
Seems good, do you do something generic and ready for the next components we want to include? 

Actually, a native webcomponenet + Babel works very well

**Comment by alexanderzobnin** [comment]
Not sure I understand what are you talking about.

**Comment by miton18** [comment]
I mean WebComponents are the next step of the web, bring ace-editor in the build is a good thing.
But make it possible for developers to register their own components is a higher and better step for me.

**Comment by miton18** [comment]
Another questions : 
data-mode="sql"
How can I load my custom mode ?

**Comment by alexanderzobnin** [comment]
@miton18 take a look at prometheus data source. It implements its own custom language mode which can be loaded from plugin's directory.
