### ISSUE TITLE
At grafana-server, error to initialize orm engine，Error 1115: Unknown character set: 'utf8mb4'\n" [Bug][Feature request]

### ISSUE THREAD

**Issue by yc576192** [grafana/grafana#8633]
The problem：
grafana-server -config="/usr/share/grafana/conf/custom.ini" -homepath="/usr/share/grafana"
INFO[06-16|09:31:34] Starting Grafana                         logger=main version=4.3.2 commit=ed4d170 compiled=2017-05-31T16:48:16+0800
INFO[06-16|09:31:34] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO[06-16|09:31:34] Config loaded from                       logger=settings file=/usr/share/grafana/conf/custom.ini
INFO[06-16|09:31:34] Path Home                                logger=settings path=/usr/share/grafana
INFO[06-16|09:31:34] Path Data                                logger=settings path=/usr/share/grafana/data
INFO[06-16|09:31:34] Path Logs                                logger=settings path=/usr/share/grafana/data/log
INFO[06-16|09:31:34] Path Plugins                             logger=settings path=/usr/share/grafana/data/plugins
INFO[06-16|09:31:34] Initializing DB                          logger=sqlstore dbtype=mysql
INFO[06-16|09:31:34] Starting DB migration                    logger=migrator
EROR[06-16|09:31:34] Fail to initialize orm engine            logger=sqlstore error="Sqlstore::Migration failed err: Error 1115: Unknown character set: 'utf8mb4'\n"
——————————————————————————————————————————————
information:
grafana-4.3.2-1.x86_64.rpm
Server version: 5.1.73 Source distribution
Red Hat Enterprise Linux Server release 6.6
——————————————————————————————————————————————
I have modified the [database] and [session] ，On mysql to create a session table。

[database]
; Either "mysql", "postgres" or "sqlite3", it's your choice
type = mysql
host = 192.168.99.100:3306
name = grafana
user = root
password = root

[session]
provider = mysql
provider_config = root:root@tcp(192.168.99.100:3306)/grafana
cookie_name = grafana_session
cookie_secure = false
session_life_time = 86400

——————————————————————————————————————————————
mysql -uroot -proot
CREATE DATABASE IF NOT EXISTS grafana default charset utf8 COLLATE utf8_general_ci;

CREATE TABLE `session` (
    `key`       CHAR(16) NOT NULL,
    `data`      BLOB,
    `expiry`    INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE session CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

flush privileges;
___________________________________________________________________________________________________________
I think a file attribute requirement is utf8mb4, can you help me solve this problem? Thank you very much.

**Comment by torkelo** [comment]
I think you need to update your mysql version.

**Comment by yc576192** [comment]
Do you want to update the mysql version at least 5.5?

**Comment by agrawalreetika** [comment]
I am not able to create session table.Look like it's not taking key as column for session table.
I am using mysql version 5.5.52

CREATE TABLE session (
key CHAR(16) NOT NULL,
data BLOB,
expiry INT(11) UNSIGNED NOT NULL,
PRIMARY KEY (key)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
