### ISSUE TITLE
Displaying data on text panel fetching from Elastic Search

### ISSUE THREAD

**Issue by sylviapari** [grafana/grafana#8634]
hi,
i have developed a scripted dashboard of analysis of data. The database is elastic search. now im having a requirement to display the description on the page,the description(is a paragraph to detail about the current analysis) is in database and it varies dynamically depending on the lucene query. The text panel is not having any data source connectivity .can any one please help me to satisfy the requirement

**Comment by torkelo** [comment]
You will have to use the table panel if you want to show text data.

**Comment by torkelo** [comment]
you can also try this external ajax panel plugin https://grafana.com/plugins/ryantxu-ajax-panel

**Comment by daniellee** [comment]
See this answer on how to use the Ajax Panel with Elasticsearch: https://community.grafana.com/t/grafana-datasource/987/2
