### ISSUE TITLE
[Bug] Quick Ranges Time Filter issue

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8635]
Version: 4.3.2
DataSource: MySQL
OS: Windows 2008 R2

Dashboard Quick Ranges filters are not considering 00:00:00 time of first day.

Example:

Last Month:
is considering date > '2017-05-01 00:00:00'  and ....
and should consider:
date >= '2017-05-01 00:00:00' and ....
This also happens for all other quick ranges filters.

I need to filter manually date > '2017-04-30 23:59:59'  and date <= '2017-05-31 23:59:59'  to get month all data. Should use operators >= and <= instead of > and <

Thanks

**Comment by torkelo** [comment]
I guess the built in __timeFilter macro should be use inclusive range filters `>=`

**Comment by fmcmarques** [comment]
Yes, apparently $__timeFilter macro is using > operator and should use >=.
Not sure for <, but also should use <= is if not using already.
