### ISSUE TITLE
[Bug] Time Zone issue exporting to CSV

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8636]
Grafana version: 4.3.2
Datasource: MySQL
OS: Windows 2008 R2

My Server and clients Time Zone is GMT+2. Dashboards are using default time zone (Local Browser Time) and work fine. The problem is when i export to CSV, the data is in UTC (with less two hours). Should use Dashboard TimeZone settings when exporting to Excel.

Thanks

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/8282
