### ISSUE TITLE
[Feature request] Reorganize Table Panel Columns

### ISSUE THREAD

**Issue by reecesmith** [grafana/grafana#8637]
Datasource: ElasticSearch
Grafana Version: 4.3.1

Hi Grafana Team,

Putting together some fantastic dashboards for our new system, but one of the really frustrating issues im finding is reorganizing the column order on the table panel when using the raw document:

![image](https://user-images.githubusercontent.com/29427730/27221039-14df43a4-527f-11e7-862a-3f149750bcf8.png)

To reorganise the columns I have to delete all the ones previous to where I want to put it and then re-add. It's even more frustrating when the business ask me to put another column in at the front as I have to delete every column. 
Would it be possible to drag the columns around here with the mouse:
![image](https://user-images.githubusercontent.com/29427730/27221003-f4d059a4-527e-11e7-9d5e-6b091eeb569f.png)

Apologies if this has already been raised / or I'm doing something wrong.

Reece

**Comment by kfdm** [comment]
@reecesmith as a workaround, you can click on the 'hamburger' menu for a panel and view the JSON and reorder things around that way.

**Comment by amytleonard** [comment]
See also #5082

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
