### ISSUE TITLE
Cloudwatch: Unable to authenticate to ap-south-2

### ISSUE THREAD

**Issue by vdmkenny** [grafana/grafana#86374]
### What happened?

I have an IAM keypair that I can use in the AWS CLI to assume a role and view cloudwatch metrics for services in region `ap-south-2`.
I am unable to configure the region `ap-south-2` in a way that will allow me to query this region.

This works completely fine without any special settings in the aws cli.

Without specifying an endpoint, I get 
`UnrecognizedClientException: The security token included in the request is invalid`

With specifying the local STS endpoint  `sts.ap-south-2.amazonaws.com` I get 
`SignatureDoesNotMatch: Credential should be scoped to a valid region.`

I tried every different permutation of combining `ap-south-1` (A region where I can view cloudwatch metrics using grafana, the account's default region) and `ap-south-2` in the region and endpoint configuration, but no luck.

If I configure `ap-south-1` as the region, and select region `ap-south-2` in the query editor, I get the same security token error.

This works perfectly fine in the cli by specifying `--region` and I can view the metrics there without issue using the same credentials and assumed role arn. I am assuming it's a bug of how the authentication is happening here.

It should be noted that `ap-south-2` is not populated in the dropdown selection of regions. I have to type it manually.
It's an optional region, but it's enabled for the account I'm authentication with. 

I use the same keypair with aws cli and terraform just fine.
I don't have console access, only programmatic.

### What did you expect to happen?

I expected to authenticate and be able to view cloudwatch metrics in region ap-south-2, in the same way I can do this using the aws cli.

### Did this work before?

It hasn't worked before in grafana. It works using the CLI, I can view metrics in json output for the resources I want to view in this region.

### How do we reproduce it?

1. Have an ap-south-1 default account
2. Enable ap-south-2 and create resources in it
3. Attempt to query cloudwatch in grafana for this region

### Environment (with versions)?

Grafana: 9.4.7
OS: MacOS (Docker)
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

Cloudwatch (Using grafana:latest container)

**Comment by idastambuk** [comment]
Hi @vdmkenny thanks for reporting this! It seems like your issue has the same cause as [this one](https://github.com/grafana/grafana/issues/81987). I see you're using grafana 9.4.7, and that one was fixed in Grafana v11. Are you able to update your Grafana version to 11? 
An alternative would be to define an environment variable AWS_STS_REGIONAL_ENDPOINTS=regional when running Grafana. 

Keep in mind that ap-south-2 (unlike ap-south-1) is an[ opt-in region](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html) so it needs to also be manually enabled in your AWS account.

Let us know if any of these suggestions works!

**Comment by vdmkenny** [comment]
Hi @idastambuk , thanks for the info!
I was able to work around it by not using the assumed role, but adding the permissions to the root account I was using to authenticate instead.
I will try to confirm if v11 and/or the extra env var solves it.

**Comment by idastambuk** [comment]
Closing this as we've found a workaround, and it's likely fixed in 11 or the env var
