### ISSUE TITLE
[Feature request] Support for multi dimensional table in grafana.

### ISSUE THREAD

**Issue by ruchitalodha** [grafana/grafana#8638]
DataSource : OpenTSDB

Metric A | Tag A|Tag B
Metric B | Tag A|Tag B
Metric C |Tag A |Tag B
Metric D |Tag A |Tag B 

or
Metric A| TagA=x|TAgB=y
Metric A| TagA=p|TAgB=q
Metric A| TagA=l|TAgB=m
Metric A| TagA=u|TAgB=v

For different metrics with same tag keys(as columns) or for same metrics with same tag keys, different tag values . Currently i can only do time series aggregation for one value

**Comment by bbczeuz** [comment]
As I understand it:
- TagA goes to column header
- TagB goes to row header
- Values go to cells

Yes?
I would like to have such a feature very much! (with InfluxDB source)

**Comment by ruchitalodha** [comment]
@bbczeuz yes exactly that

**Comment by CyBeRoni** [comment]
+1 except with Graphite, possibly then using more than one query somehow.

Right now I'm running into the problem that if I have counter data fetched every 10 seconds, I can either get a correct total (by using only derivative()) or a correct per second current value (using scaletoSecond(derivative())), but not both at the same time. Never mind if I also want to convert a bytes value to bits for one but not the other.

**Comment by torkelo** [comment]
> but not both at the same time.

Why not have two queries?

**Comment by CyBeRoni** [comment]
> Why not have two queries?

If you can tell me how to make two queries show up on the same row, then that would be fine. So far as I can tell though, separate queries means separate rows.
