### ISSUE TITLE
Show function hints when selecting a native histogram

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#86388]
The query editor will provide hints for classic histogram metrics by showing the function `histogram_quantile`. But, when a user selects a native histogram, none of the native histogram functions are shown as hints.

Classic histogram

![Image](https://github.com/grafana/grafana/assets/25674746/140b530f-b861-41ed-8b3e-3803691b1570)

Native histogram

![Image](https://github.com/grafana/grafana/assets/25674746/4a5e11d7-c8a7-42d3-9704-990ba913ca75)

Native histogram function hints should include
histogram_avg no documentation link yet, just merged: https://github.com/prometheus/prometheus/pull/13467
[histogram_count](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_count-and-histogram_sum)
[histogram_sum](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_count-and-histogram_sum)
[histogram_fraction](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_fraction)
[histogram_stddev](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_stddev-and-histogram_stdvar)
[histogram_stdvar](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_stddev-and-histogram_stdvar)

How to differentiate classic and native?

If we know a metric is of a certain type, we can show a hint. 

Currently there is no metadata available for native histograms so we have little to differentiate them from classic. (See https://github.com/grafana/alloy/issues/547).

We know classic histograms always end in `_bucket`, `_sum`, or `_count` like 
`cortex_request_duration_seconds_bucket`

And a native histogram metric would have everything but the suffix. 
`cortex_request_duration_seconds`

~~One suggestion is that if we know there is a classic histogram available, we can identify it, remove the suffix and create a collection of native histogram metric names. We could then compare any selected metric to that collection to identify it as a native histogram. This is not as nice as simply checking the metadata for the type, but it is one idea.~~

*update: The above idea will not work because classic histograms will be removed and there will be nothing to compare native histograms to.

~~What we are left with is a metric name with no clear frontend way to identify it's type. Another solution is to create a resource-like call that queries a chosen metric and parses the response to identify the metric as a native histogram, then return this information to the frontend to provide the hint. This would not be scalable to apply to all metrics but it could provide us the hint.~~

**Additional update: use metadata and test with vanilla Prometheus see slack for more context https://raintank-corp.slack.com/archives/C02UC0KCSF4/p1713424061722829?thread_ts=1708519355.394509&cid=C02UC0KCSF4

> We discussed this with Beorn yesterday and the best information and API currently is the [metadata](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata) endpoint. If it has the type==histogram and the series doesn't end in _bucket, _count or _sum, you can be reasonably sure that it is a native histogram.

**Comment by bohandley** [comment]
PR enables these hints



![Image](https://github.com/grafana/grafana/assets/25674746/7b996398-7664-42df-a55b-4859235da735)




![Image](https://github.com/grafana/grafana/assets/25674746/5b58236e-b39f-409d-b111-70d506ef9860)

**Comment by zhehao-grafana** [comment]
It seems that the current solution might still have outliers. For example, cortext_request_duration_seconds is still not tagged as the native histogram

![Screenshot by Dropbox Capture](https://github.com/grafana/grafana/assets/143556099/c2f1b7a3-81ee-4311-bc70-e6d386a68c5a)

**Comment by zhehao-grafana** [comment]
This is another exception: cortex_ingest_storage_reader_receive_delay_seconds
