### ISSUE TITLE
[BUG] Escape variables when using regex.

### ISSUE THREAD

**Issue by dannywillems** [grafana/grafana#8639]
Please include this information:
- What Grafana version are you using?
Tried on 4.3.1, 4.3.2 and last nightly build Version 4.4.0-pre1 (commit: e9c8881)

- What datasource are you using?
InfluxDB 1.2.4

- What OS are you running grafana on?
Ubuntu

- What did you do?
I have a database with a measurement called `load`. There are the tags `hello` and `tagg`. Some possible values for `tagg` contain a dash `-` like `top-bottom` and for `hello` we have the value `test`. I have the variables `hello` and `tagg`. The query is

```
SELECT sum("activity") FROM "autogen"."load" WHERE  "hello" =~ /^$hello$/ AND "tagg" =~ /^$tagg$/ AND $timeFilter GROUP BY time($__interval)
```

There are lots of data for this query and it works on an older Grafana version (2.5.0).
But Grafana shows N/A.

Using network for the value `top-bottom` (selected with the value selector), I see:
```
https://hostname.com/api/datasources/proxy/1/query?db=hello&q=SELECT sum("activity") FROM "autogen"."load" WHERE  "hello" =~ /^test$/ AND "tagg" =~ /^top\\-bottom$/ AND $timeFilter GROUP BY time($__interval)&epoch=ms
```
If I remove the variable and use directly the value `top-bottom`, the query is
```
https://hostname.com/api/datasources/proxy/1/query?db=hello&q=SELECT sum("activity") FROM "autogen"."load" WHERE  "hello" =~ /^test$/ AND "tagg" =~ 'top-bottom' AND $timeFilter GROUP BY time($__interval)&epoch=ms
```
and it works.

If I use the all values for `hello`, the query is:
```
https://hostname.com/api/datasources/proxy/1/query?db=hello&q=SELECT sum("activity") FROM "autogen"."load" WHERE  "hello" =~ /^\.\*$/ AND "tagg" =~ 'top-bottom' AND $timeFilter GROUP BY time($__interval)&epoch=ms
```
and it doesn't work, even if there is data...

**Comment by torkelo** [comment]
in the manual example that you say works you have ` "tagg" =~ 'top-bottom'`  and in the example with the template variable you have ` "tagg" =~ /$tagg/'    is there a reason you changed the regex syntax? 

<img width="807" alt="screen shot 2017-06-16 at 10 29 49" src="https://user-images.githubusercontent.com/10999/27230884-ce3374fc-527e-11e7-8bfe-a44ba4920b4a.png">

**Comment by torkelo** [comment]
was not able to reproduce the issue (see above)

**Comment by dannywillems** [comment]
@torkelo I fixed the manual example. It's `tagg = 'top-bottom'` (like if I fixed the value manually). It's not a regex but a plain string.
