### ISSUE TITLE
[Feature request] Add refId to each series returned by Elasticsearch query 

### ISSUE THREAD

**Issue by Chris7** [grafana/grafana#8642]
Please include this information:
- What Grafana version are you using?
  4.3.0

I am making a general data series visualization panel (ie plot the value of some elasticsearch tag vs another) and one feature I built in was to have the axes be from different query sources (A stupid example would be query A returning the average, query B returning the stdev). This works fine until groupings come into play, in which case the array index that is sent with data-receive no longer corresponds to the query issued. So in short, there is no way to extract what query generated a given source of data from js. Having an extra field for the query source (in the same object that has `datapoints`, `target`, etc.) would allow me to extract information based on the query type for visuals that can integrate across different datasources (ie pluck out a metric from a raw document from a ES data source and combine it with metrics in prometheus)

**Comment by torkelo** [comment]
If I understand you correctly you want a refId on each series returned by the query so you can know which series came from which query?

**Comment by Chris7** [comment]
Exactly!

**Comment by aocenas** [comment]
Needs to be checked because I think we already do this right now, ie returning the same refId  in the response that was in the query.

**Comment by torkelo** [comment]
Can't see that we do this currently.

**Comment by torkelo** [comment]
Should be easy to add the refId here https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/elastic_response.ts
