### ISSUE TITLE
Grafana Explore: Always shows as DEBUG color when the level is set to INFO

### ISSUE THREAD

**Issue by kjq** [grafana/grafana#86447]
### What happened?

We recently upgraded Grafana, Loki, and Prometheus to the latest versions from the Helm charts.  Both the explorer and log view (custom dashboard) are showing records which have a level of `INFO` as `DEBUG`. 

In the custom dashboard, using the log view component, the level has been set to `debug` (all lowercase).

This seems to only be happening when the level is `INFO`.  Other records (`WARN`, `ERROR`, etc.) show up correctly.

![Screenshot 2024-04-17 101928](https://github.com/grafana/grafana/assets/533810/8b487b66-9984-4883-90e1-2a415a4c8ac1)

### What did you expect to happen?

When the log `level` is `INFO` it shows as a green bar not blue (`debug`) and my level is not changed anywher. 

### Did this work before?

Yes, before this levels were shown correctly.

Taken from the log view dashboard (but same in explore):
![Screenshot 2024-04-17 102305](https://github.com/grafana/grafana/assets/533810/cd4027eb-5c59-4e3c-a365-7126efad491b)

The JSON log record also has the correct level:

```json
{"timestamp":"2024-04-17T14:27:33.74Z","sequence":2668,"logger":"org.apache.kafka.streams.processor.internals.StreamThread","level":"INFO","message":"stream-thread [fusion-events-services-18d85b2f-031c-42b7-9c35-1d6f4ff5127e-StreamThread-1] Processed 0 total records, ran 0 punctuators, and committed 0 total tasks since the last update","threadName":"fusion-events-services-18d85b2f-031c-42b7-9c35-1d6f4ff5127e-StreamThread-1","hostName":"e2ab94786a13"}
```

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

I dont believe so because the regular "explore" view shows it as `debug`.

### Environment (with versions)?

Grafana: 10.4.1
OS: Linux
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by shantanualsi** [comment]
this was a Loki issue, was fixed in https://github.com/grafana/loki/pull/12635

**Comment by hairyhenderson** [comment]
Given this was a Loki issue, can this issue be closed? Was/is there any Grafana issue here?
