### ISSUE TITLE
Product Area: Short description of bug

### ISSUE THREAD

**Issue by nagy1991** [grafana/grafana#86458]
### What happened?

Under Docker swarm, if you want to use secret in a stack, it doesn't work

`
version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
       GF_SECURITY_ADMIN_USER: /run/secrets/grafana-root-username             
       GF_SECURITY_ADMIN_PASSWORD: /run/secrets/grafana-root-password
    secrets:
      - grafana-root-username
      - grafana-root-password

secrets:
    grafana-root-username:
      external: true
    grafana-root-password:
      external: true
`

**Comment by timo** [comment]
you need to set the environment variables like this:

> Environment variable: GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password

see this page https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#configure-grafana-with-docker-secrets

**Comment by nagy1991** [comment]
thanks
