### ISSUE TITLE
Limit of 14 tags/graphs

### ISSUE THREAD

**Issue by chensMMG** [grafana/grafana#8646]
Hi,
I'm using Grafana 4.3.1 with InfluxDB (installed on CentOS 7.3).
I have a simple dashboard that shows host resources and I have 100 server and there is one graphs per resource (cpu memory etc.). I want to include only 35 server that are in a certain domain so I'm using templating to query these out:
SHOW TAG VALUES FROM "uptime_value" WITH KEY = "host" where host =~ /.*domain.*/
This works fine and I get all 35 server, I can see them in the drop-down list and can select each one and see their graphs.
my Metric query is like this:
SELECT mean("value") FROM "load_shortterm" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), "host" fill(null)
Alias by $tag_host

The problem is that when i select "All" or i select many of them manually - I get ONLY 14 of these.
Is there a clear limit of 14 tags per graph? 
Can it be modified to more? Where?

**Comment by torkelo** [comment]
No limit in Grafana, but could be a limit in InfluxDB via the option max-row-limit
