### ISSUE TITLE
Grafana alert cant work with influxdb 

### ISSUE THREAD

**Issue by ridhoyp** [grafana/grafana#8647]
![image](https://user-images.githubusercontent.com/28750276/27260077-51050452-544d-11e7-980f-d198375bc67e.png)

Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? influxdb
- What OS are you running grafana on? ubuntu 14.0.4
- What did you do? wanna make an alert 
- What was the expected result? can alert if value above expected value
- What happened instead? eror tsdb.handlerequest() error influxdb returned statuscode invalid 400 bad request

dashboard json : 
[json.txt](https://github.com/grafana/grafana/files/1083033/json.txt)

**Comment by torkelo** [comment]
What is your InfluxDB query? And what are your InfluxDB datasource settings

**Comment by ridhoyp** [comment]
here is the query =

![image](https://user-images.githubusercontent.com/28750276/27261135-d842f8ac-5466-11e7-8122-b652eae2b47c.png)

here is the datasource setting =

![image](https://user-images.githubusercontent.com/28750276/27261139-e7d8046a-5466-11e7-9e7c-8876a9b03f1e.png)

**Comment by torkelo** [comment]
and then you click on Test Rule what does grafana.log say? (might include more details on the error from InfluxDB)

**Comment by ridhoyp** [comment]
here is : 


t=2017-06-20T05:25:42+0700 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalHandler ruleId=13 name="Core SW 1 Temperature alert" error="tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request" changing state to=alerting

![image](https://user-images.githubusercontent.com/28750276/27308498-0595ea2c-5579-11e7-8b33-03136cb0d774.png)

**Comment by torkelo** [comment]
if you remove the tag regex filter or the hostname filter does it work then?

**Comment by ridhoyp** [comment]
still same with this :

![image](https://user-images.githubusercontent.com/28750276/27310058-cd376206-5581-11e7-8e0c-508bb060754d.png)

**Comment by Fusl** [comment]
How do you build your query that the result is `Switch\ 1\ -\ Temp\ \ 0`? I have a few queries here that have spaces in the where part of the query but never have an escaping backslash, they work fine with alerts:
![f69bd46b409d](https://user-images.githubusercontent.com/2349496/27370341-6a0175d8-565c-11e7-841e-fd5bd022ba59.png)

**Comment by ridhoyp** [comment]
Hi,

I just choose it, its from influxdb + librenms 

![image](https://user-images.githubusercontent.com/28750276/27370491-0050661e-5687-11e7-8577-72c98b7d8b54.png)


Regards,
RidhoYP

**Comment by torkelo** [comment]
are you still having issues with alert queries there tag filters have white space? Fail to replicate and no other reports on this.

**Comment by ridhoyp** [comment]
Hi,

is there any new update to fix?

Yea , maybe because i use librenms to view on grafana, the whitespace happen only with cisco product from librenms, and maybe others not use metrics like i was.

Regards,
RidhoYP

**Comment by torkelo** [comment]
closing this as I am not able to replicate it and no other reports similar to this has been reported
