### ISSUE TITLE
[Feature request] Provide Debian 9 'stretch' packages

### ISSUE THREAD

**Issue by mcktr** [grafana/grafana#8648]
Hello,

please provide packages for Debian 9 'stretch' in the [official repository](https://packagecloud.io/grafana/stable). I know that the Debian 9 release happened this weekend and that it is still hot, so no stress. :)

Wanted to put this here as a reminder.

**Comment by torkelo** [comment]
is there a reason why it needs to be specifically added for stretch? its the 100% exact same package? 

adding deb https://packagecloud.io/grafana/stable/debian/ jessie main
to sources list will still work.

But will update our publish script to push to stretch as well but feels stupid to duplicate the same package so many times (problem with linux apt repos I guess)

**Comment by mcktr** [comment]
Thanks. 

I don't know much about packaging, but when the package is 100% exactly the same as stretch is it not possible to make a symlink to the jessie package?

**Comment by mpartel** [comment]
Some reasons for separate repos for separate distro versions:
- users know which distros are "supported" (presumably tested against)
- you have the freedom to diverge the packages in the future should there be a need to e.g. add backwards compatibility hacks for legacy distros

**Comment by mryellow** [comment]
Unclear reading here what the state is.

For anyone passing by, it appears `stretch` is in-fact deployed.

`Get:1 https://packagecloud.io/grafana/stable/debian stretch/main amd64 grafana amd64 4.6.2 [47.3 MB]`
