### ISSUE TITLE
Product Area: Short description of bug

### ISSUE THREAD

**Issue by satya951** [grafana/grafana#86494]
### What happened?

How to set `allow_embedding` in aws garfana.

### What did you expect to happen?

when i cannot see the any allow embedding opstion  an di can see the opstion lik embed and can i copy  the url but i cannot access it because the embedding  is not in ture. 

### Did this work before?

 frist  iam using embed via aws garfana 

### How do we reproduce it?

1.why i cannot see more opsition comapre to aws garfana and grafna cloud .
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by satya951** [comment]
![aws grafana](https://github.com/grafana/grafana/assets/126106613/869f5831-b347-4c39-a66d-834446003721)

**Comment by tonypowa** [comment]
Hi @satya951 
Thanks for reaching out. It seems your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/). GitHub is mainly used for tracking bugs and feature requests

We appreciate your understanding.
