### ISSUE TITLE
[Feature Request] singlestat should understand raw JSON data

### ISSUE THREAD

**Issue by skygragon** [grafana/grafana#8653]
When choosing "none" aggregator, the respond JSON will treat each date point as separate item as following:
```
[
{"metric":"active.request.number_value","tags":{"dc":"dc1","host":"host01"},"aggregateTags":[],"query":{"aggregator":"none","metric":"active.request.number_value","tsuids":null,"downsample":null,"rate":false,"filters":[{"tagk":"dc","filter":"dc1","group_by":true,"type":"literal_or"}],"index":0,"rateOptions":null,"filterTagKs":["AAAB"],"explicitTags":false,"tags":{"dc":"literal_or(dc1)"}},"dps":{}},
{"metric":"active.request.number_value","tags":{"dc":"dc1","host":"host02"},"aggregateTags":[],"query":{"aggregator":"none","metric":"active.request.number_value","tsuids":null,"downsample":null,"rate":false,"filters":[{"tagk":"dc","filter":"dc1","group_by":true,"type":"literal_or"}],"index":0,"rateOptions":null,"filterTagKs":["AAAB"],"explicitTags":false,"tags":{"dc":"literal_or(dc1)"}},"dps":{}}
]
```
You see all items in the array are about metric "active.request.number_value", but grouped by individual tags. However singlestat doesn't recognize this format and claims "Multiple Series Error".
Actually singlestat could merge those values and still treat them as single serie, since all the needed data is returned and ready to use.

see #8608

**Comment by torkelo** [comment]
most time series databases support a way to aggregate many series together to one series, so no need to implement that again in the singlestat panel. 

For TSDBs that do not support it Grafana can handle it via this future feature (no ETA), https://github.com/grafana/grafana/issues/3677
