### ISSUE TITLE
span size changes when duplicate the panel

### ISSUE THREAD

**Issue by yosefy** [grafana/grafana#8654]
Please include this information:
- What Grafana version are you using?

 Grafana v4.3.2 (commit: ed4d170)
ubuntu16
duplicate pannel
keeps same span size
- What happened instead?

span changed to fit 12
so if i had one panel of 12  and i duplicate it i get two of span 6 on same line
even if i set min span to 12 too

thanks

**Comment by torkelo** [comment]
yes, the current layout engine tries to make it fit. terrible when that is not what you want. 

We will introduce a new grid & layout system after summer that will fix this.
