### ISSUE TITLE
Time series panel: Dash overlapping/matching lines

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#86546]
**Why is this needed**:

Readability

**What would you like to be added**:

When multiple series are following the same line in the plot, dash them.

E.g.:
![image](https://github.com/grafana/grafana/assets/7028403/1155602e-4ac4-4c97-8417-8681b4b77943)
In this image, the are actually six series. Two are hidden by the series in red. One is hidden by the series in blue. Because in each case, the values are the same. It is quite hard to know quickly where the green series, for instance, is. It would help a lot of the lines were dashed in  a way that allowed each series to show through. Even if we select "Dash" as the line style, they become dashed in such a way that each series' dashes start and end the same, still obscured.

**Who is this feature for?**

Users of the time series panel

**Comment by nabelekt** [comment]
For what it's worth, here is one forum post requesting the same thing: https://stackoverflow.com/questions/73986909/grafana-its-possible-to-see-two-overlapping-lines-at-the-same-time-in-grafana

**Comment by leeoniya** [comment]
> It would help a lot of the lines were dashed in a way that allowed each series to show through

this would be nice but it's not realistic for more than a few series and a small number of data points. it's not computationally feasible to analyze every series to see if it approximately matches any number of other series at some arbitrary % of datapoints and then configure each in such a way that the dashes are guaranteed to render in some non-occluding way. i'm not aware of any charting lib that can do this, either.

**Comment by nabelekt** [comment]
Instead of dashing, you could make the line drawn first thicker and the one drawn list thinner.

I guess I can do this manually using overrides if I know two or more series will often match. Something like this
![image](https://github.com/grafana/grafana/assets/7028403/9d86f08a-7376-43f1-b1d3-34eb9f74da60)

**Comment by leeoniya** [comment]
for sure, there are some solutions. the problem is that they don't scale with number of series and number of datapoints.
