### ISSUE TITLE
Cloudwatch: Label is missing when writing a search expression in code mode

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#86544]
To reproduce: 

-  In a Cloudwatch datasource, write a search expression while in code mode like so:`REMOVE_EMPTY(SEARCH('{"AWS/RDS","DBInstanceIdentifier"} MetricName="CPUUtilization" "DBInstanceIdentifier"=~"database*"', 'Maximum'))` (internally our test instance in us-east-2 is a good one)
- Notice the label is present as CPUUtilization:
<img width="736" alt="Screenshot 2024-04-18 at 12 22 33 PM" src="https://github.com/grafana/grafana/assets/6620164/444a9383-ed5f-4a6d-8007-fa8e240b1ba8">
- Try to make an alert from this panel and click preview. Notice that the previewed labels just say series 1, etc
<img width="898" alt="Screenshot 2024-04-18 at 12 23 54 PM" src="https://github.com/grafana/grafana/assets/6620164/95f1aa72-69e0-4387-94e3-271b71690a85">

There is a weird workaround this that seems less than idea: 
- Switch to the builder mode and add a similar query to fix the labels. 
<img width="737" alt="Screenshot 2024-04-18 at 12 38 20 PM" src="https://github.com/grafana/grafana/assets/6620164/75916b8a-6702-402e-8dbd-aab85bff3d11">
- then switch back to the code mode, and create an alert, notice that the labels appear again
<img width="889" alt="Screenshot 2024-04-18 at 12 39 17 PM" src="https://github.com/grafana/grafana/assets/6620164/828a4d99-8db0-4b9a-ba47-32c3a2699753">

However the above workaround only works when the feature flag `cloudWatchNewLabelParsing` is set to false. If it's set to true, it will instead return No Data, as it is hitting a go error in the [parse labels function](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/response_parser.go#L92)

In an ideal world:
- We are able to parse labels in alerting as we can in the query editor
- the code editor and the build editor do not influence one another, or at the very least it handles the error properly and demonstrates to the user in someway

Related: https://github.com/grafana/grafana/pull/84835

**Comment by katebrenner** [comment]
might be related to https://github.com/grafana/grafana/issues/87568

**Comment by iwysiu** [comment]
done in https://github.com/grafana/grafana/pull/88943
