### ISSUE TITLE
[Bug] Null value considered as previous value

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8655]
Grafana version: 4.3.2
Datasource: MySQL
OS: Windows 2008 R2

When value is null, Grafana consider value of previous time instead of zero.

Example:

REFDATE         VALUE
2017-01-01         100
2017-01-02         200
2017-01-03         null
2017-01-04         300

For 2017-01-03 Grafana Dashboard consider value 200 instead of 0.

Thanks

**Comment by torkelo** [comment]
What do you mean consider? Can you show graph with the raw data as well? What is you Graph display option for null value?

**Comment by fmcmarques** [comment]
![grafana_null_value_1](https://user-images.githubusercontent.com/29407741/27286712-6d936208-5501-11e7-999e-28308f4c8384.png)
![grafana_null_value_2](https://user-images.githubusercontent.com/29407741/27286715-6da6c172-5501-11e7-8ba0-91ae65ba4817.png)
![grafana_null_value_3](https://user-images.githubusercontent.com/29407741/27286713-6d98d7ba-5501-11e7-8562-dd418b4cee42.png)
![grafana_raw_data](https://user-images.githubusercontent.com/29407741/27286714-6d9e571c-5501-11e7-8925-a9e3c2cdd472.png)
![grafana_export_null_as_zero_option](https://user-images.githubusercontent.com/29407741/27286716-6e900800-5501-11e7-8335-ca748143055c.png)

The 3 options for null value have no impact for MySQL datasource. In the 3 cases Dashboard shows previous value when finds a null value. Please see attachs.

**Comment by daniellee** [comment]
@fmcmarques confirmed as a bug and fixed. The fix will be in the next Grafana release.

**Comment by Runnerblade84** [comment]
Hi,

grafana version 4.4.3

same happens if metric is missing
<img width="827" alt="schermata 2017-09-07 alle 15 46 54" src="https://user-images.githubusercontent.com/31735006/30166686-51c4e304-93e4-11e7-815a-4d46d262bf28.png">


<img width="241" alt="schermata 2017-09-07 alle 15 46 21" src="https://user-images.githubusercontent.com/31735006/30166589-0aa19382-93e4-11e7-8fb5-4c9d85f764a9.png">

**Comment by torkelo** [comment]
you query needs to group by time and return null/0 for missing data points

**Comment by Runnerblade84** [comment]
ok, I did, better but there is something that is not working
<img width="1040" alt="schermata 2017-09-07 alle 16 44 50" src="https://user-images.githubusercontent.com/31735006/30169239-16894e4e-93ec-11e7-82c8-c25112058500.png">

<img width="234" alt="schermata 2017-09-07 alle 16 47 03" src="https://user-images.githubusercontent.com/31735006/30169273-3382928a-93ec-11e7-8f4f-bc973a58523d.png">

Why "TIMG" has 1 that should be 0?
