### ISSUE TITLE
[Bug] 'Date/time field out of range' error when creating a new user within an organisation

### ISSUE THREAD

**Issue by poggs** [grafana/grafana#8656]
On v4.3.2 installed on Ubuntu 16.04 with PostgreSQL back-end, when I add or invite a new user within an organiation, it fails.  The log shows:

t=2017-06-19T18:48:08+0100 lvl=eror msg="Failed to save invite to database" logger=context userId=2 orgId=6 uname=***REDACTED*** error="pq: date/time field value out of range: \"0000-12-31 23:58:45\""
t=2017-06-19T18:48:08+0100 lvl=eror msg="Request Completed" logger=context userId=2 orgId=6 uname=***REDACTED*** method=POST path=/api/org/invites status=500 remote_addr=[::1] time_ms=24 size=47

I can create global users successfully.

**Comment by daniellee** [comment]
This `0000-12-31 23:58:45` is not a valid zero date for the email_sent_on field. Guess this is due to time zones. It should not be a zero date anyway. Will fix.
