### ISSUE TITLE
Alert annotation

### ISSUE THREAD

**Issue by rlugovyy** [grafana/grafana#86577]
Hello! I'm having a problem retrieving parameters from a log and passing them to an annotation. Every time an error occurs in the Kubernetes logs, an alert is generated. Unfortunately, however, this alert does not contain information about which pod the problem is associated with. I'm considering extracting the pod name, its namespace and environment variables (env) to pass them through an annotation. An error notification will be sent to Microsoft Teams. Also, all logs are stored in Loki.

````
{
    "body": {
        "object": {
             ...
            },
            "eventTime": null,
            "kind": "Event",
            "metadata":
                ... 
                "name": "name",
                "namespace": "namespace",
            },
            ...
            },
            ...
        },
        "type": "DELETED"
    },
    "attributes": {
        "env": "dev",
        "event.domain": "k8s",
        "event.name": "event.name",
        "k8s.resource.name": "events"
    }
}
````

**Steps to reproduce**:
2. Define query and alert condition
sum by (namespace, name, env) (count_over_time({exporter="OTLP"} |= `Error` [5m]))

4. Add annotations
Pod {{ $labels.name }} in Namespace {{ $labels.namespace }} in enviroment {{ $labels.env}} is in error

**Actual Result**:
![image](https://github.com/grafana/grafana/assets/137896719/0e9754db-7a1f-408f-a672-406ff3bfef3f)

**Expected Result**

**Environment**:
- Grafana version: 0.95.0
- Data source type & version: Loki

```[tasklist]
### Tasks
```

**Comment by tonypowa** [comment]
Hi @rlugovyy 

Thanks for reaching out.

It seems your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) 

I can't advise on interpolating labels from Loki, but I found a similar question in the forum.
https://community.grafana.com/t/is-it-possible-to-have-labels-in-loki-managed-alerts-summary-description/74674/6
Hope it points you to the right direction. If you get stuck , you are welcome to ask in our [Community Slack](https://slack.grafana.com/)
