### ISSUE TITLE
Grafana cannot save dashboard with too many panels

### ISSUE THREAD

**Issue by withpitt** [grafana/grafana#8659]
Hello, 

I made a dashboard with about 70 single stat panels. And when I'm trying to save the dashboard, orange color box occurs that says 'problem!' Then I deleted several panels and the dashboard was saved. 
So my question is, is there any limit for number of panels that one dashboard could contain?
Please include this information:
- What Grafana version are you using? the lastet
- What datasource are you using? influxdb
- What OS are you running grafana on? Ubuntu

thanks.

**Comment by daniellee** [comment]
I don't think there is a limit. I just saved a dashboard with more than 100 panels. What does the error say? Can you check the console and network tab in Chrome Developer Tools to see if there any errors there.

**Comment by torkelo** [comment]
could be a limit if you have a nginx proxy or apache proxy in front of Grafana with request size limits

**Comment by withpitt** [comment]
Thann you. As you said, the proxy server in the front was limiting the data size.
