### ISSUE TITLE
[Bug] Alerts `Clear history` button causes a 404 error in Grafana 4.3.2 (w/ InfluxDB source on Debian Jessie)

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8660]
Clicking the `Clear history` button here:
![ff737d2767aa](https://user-images.githubusercontent.com/2349496/27339667-ab487f5c-55d8-11e7-9cbc-ddabfbb67a76.png)
causes Grafana to throw an error
```
Problem!
Not found
```
with this in the logs:
```
t=2017-06-20T14:51:28+0000
lvl=info
msg="Request Completed"
logger=context
userId=1
orgId=1
uname=fusl
method=POST
path=/api/annotations/mass-delete
status=404
remote_addr=185.140.55.4
time_ms=0
size=23
```
Is this a case of `RTFM` or is this a bug in Grafana?

**Comment by daniellee** [comment]
Confirmed as a bug. Will fix for the next release.
