### ISSUE TITLE
Doc/Tempo/Data source provisioning: bad "traces to logs" configuration

### ISSUE THREAD

**Issue by cboudereau** [grafana/grafana#86604]
### What happened?

The actual documentation mentioned an example of a tempo datasource provioning using tracestologs which is quite good but the given "custom query" does not work: https://github.com/grafana/grafana/blob/ec1af89a024f283469d498e08707893264ca97c7/docs/sources/datasources/tempo/configure-tempo-data-source.md?plain=1#L241

![image](https://github.com/grafana/grafana/assets/2091863/9ed6f714-a9b6-45db-a146-e2a94b9119e8)

The dollar sign should be escaped like: `method="$${__span.tags.method}"`

### What did you expect to happen?

After fixing the configuration, the variable is well integrated:

![image](https://github.com/grafana/grafana/assets/2091863/38ae3d58-cbb1-4698-a9c5-bbad083b8715)

### Did this work before?

Yes

### How do we reproduce it?

1. Create a tempo datasource by copy pasting the one from the doc (https://github.com/grafana/grafana/blob/ec1af89a024f283469d498e08707893264ca97c7/docs/sources/datasources/tempo/configure-tempo-data-source.md?plain=1#L241
)
2. Edit the configuration and check that the variable is available
3.

### Environment (with versions)?

Grafana: 10.4.1

### Grafana platform?

None

### Datasource(s)?

tempo

**Comment by wusunny2022** [comment]
Hello, it would be handy if also update in the document for escaping $ with $$, thanks🙏
