### ISSUE TITLE
[Feature request] Show actual InfluxDB query

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8661]
The panel metrics select builder for InfluxDB looks basically like this (in Grafana 4.3.2)
![f41887c974b1](https://user-images.githubusercontent.com/2349496/27339986-939a2594-55d9-11e7-8da2-2c3ab4ebb2f5.png)
Clicking `Toggle Edit Mode` results in a select query similar to this:
```
SELECT median("value") FROM "xxxxxxxxxxxxxxx" WHERE $timeFilter GROUP BY time($__interval) fill(linear)
```
while the actual executed select query is (simplified)
```
SELECT median("value") FROM "xxxxxxxxxxxxxxx" WHERE time > now() - 7d GROUP BY time(5m) fill(linear) ;second select ;third select ;...
```
It would be cool if Grafana would display the actual InfluxDB select query on the panel > metrics query editor or have a button that, when clicked, displays the actual, parsed select query. This would help a lot in debugging syntax errors or other mistakes in the select query by being able to simply copy and paste the parsed select query into an InfluxDB CLI.

**Comment by torkelo** [comment]
We have actually started on a query troubleshooter that will allow you to do this (https://github.com/grafana/grafana/issues/8665) 

<img width="1255" alt="screen shot 2017-06-20 at 12 40 47" src="https://user-images.githubusercontent.com/10999/27344934-0fae18c6-55b6-11e7-8514-52384ee2035d.png">

Just need to figure out some UX issues
