### ISSUE TITLE
Templating with ES datasource should allow value of field value in term query to be substituted

### ISSUE THREAD

**Issue by ajrnz** [grafana/grafana#8662]
You should be able to select which field is used to perform a filter. Sort of like a reduced adhoc filter. For example:

    $filterField     ip,hostname,field
    $filterValue     {"find": "terms", "field": "$filterValue"}

The idea would be to be able to get results either by ip, hostname or serial and have the `filterValue` dropdown auto-populated. Then in the query you could write `$filterField:$filterValue`

Currently only the `query` field is interpolated, if it exists

**Comment by torkelo** [comment]
fixed in latest nightly build

**Comment by torkelo** [comment]
I mean merged
