### ISSUE TITLE
[Feature request] Align colors in picker grid by hue and brightness

### ISSUE THREAD

**Issue by danw1979** [grafana/grafana#8664]
All I can say, before writing this, is *sorry*.  I just have to get this off my chest.

- What Grafana version are you using?
4.1

- What datasource are you using?
N/A

- What OS are you running grafana on?
Served by Debian Jessie.  Viewing on Chrome / Mac OS.

- What did you do?
Opened the color picker.

- What was the expected result?
Colors would be arranged by hue & brightness in an easy-to-find way.  

- What happened instead?
Colors are ordered by hue in repeated sequences of differing brightness, but in non-aligned rows:
![screen shot 2017-06-20 at 16 50 07](https://user-images.githubusercontent.com/12696246/27342954-7839563a-55d9-11e7-975d-bfd8ea4d8356.png)

 
If the default shades in the color picker grid were arranged by the same hue vertically, and the same brightness/saturation horizontally, finding the color you want would be far easier.

**Comment by torkelo** [comment]
this was implemented in v4.6
