### ISSUE TITLE
`XYChart`: Allow tooltip configuration

### ISSUE THREAD

**Issue by jayceslesar** [grafana/grafana#86642]
**Why is this needed**:
In the docs as well as in practice, overrides do not work on `XYChart` tooltips.

**What would you like to be added**:
So that people can configure what is shown on the tooltip for an `XYChart`.

**Who is this feature for?**
Anyone who uses `XYChart`

**Comment by leeoniya** [comment]
configuring field Overrides > Hide from > Tooltip should work for this?

**Comment by jayceslesar** [comment]
@leeoniya I only see Series > Hide in area, which when selected (cross over the eye) does not hide the trace in the tooltip

**Comment by leeoniya** [comment]
we have an XYChart rewrite mostly done and will make sure this works

**Comment by jayceslesar** [comment]
Im not entirely sure its a bug, but im essentially trying to only show tooltips for Y-axis data on my XYChart...probably not a super common use case

**Comment by leeoniya** [comment]
any chance you can attach a debug snapshot we can play with? [1]

so you want just the y field displayed in the tooltip? the Hide in area override _should_ allow you to do this.

[1] https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

**Comment by jayceslesar** [comment]
Too big to send as json raw but here is the panel as json in a file
[panel.json](https://github.com/grafana/grafana/files/15049218/panel.json)

**Comment by jayceslesar** [comment]
FWIW when I hide stuff with a regex of /.*/ everything is hidden, but nothing gets hidden when I do anything more specific than that

**Comment by leeoniya** [comment]
it's hard to reproduce without data, mayve you can reduce the time range and/or zip the snapshot before attaching

**Comment by jayceslesar** [comment]
[debug-Bay 1, Fwd Spar-2024-04-20 17_49_43.json.txt](https://github.com/grafana/grafana/files/15049246/debug-Bay.1.Fwd.Spar-2024-04-20.17_49_43.json.txt)

Should include data -- my bad

**Comment by jayceslesar** [comment]
[debug-Bay 1, Fwd Spar-2024-04-22 13_46_17.json.txt](https://github.com/grafana/grafana/files/15063840/debug-Bay.1.Fwd.Spar-2024-04-22.13_46_17.json.txt)

**Comment by jayceslesar** [comment]
you can also see it https://play.grafana.org/d/_bjH2iOVz/xy-chart-axis-label-overrides?orgId=1 if you just try to hide y from the tooltip and legend with the same override of "Hide in area"

**Comment by jayceslesar** [comment]
The main issue is when we have long-format data, and wish to have one trace per "type". Redshift allows us to visualize our long-format data using the Format:timeseries setting. This will give us one trace per type.
The legend should just be the type, not an entry for both the X and Y side of the type.
Here is a reproducible example forked from [replicating issues](https://play.grafana.org/d/_bjH2iOVz/xy-chart-axis-label-overrides?orgId=1&shareView=link) but we haven't been able to figure out the Format:timeseries setting for this datasource.

![Screenshot 2024-04-22 at 1 39 26 PM](https://github.com/grafana/grafana/assets/47452474/050b5c47-7ca3-4160-8f1e-a651beaeadac)
[XY chart axis label overrides-1713807441648.json](https://github.com/grafana/grafana/files/15066897/XY.chart.axis.label.overrides-1713807441648.json)

**Comment by leeoniya** [comment]
i have some questions about the dataset in https://github.com/grafana/grafana/issues/86642#issuecomment-2069506409

- you're using redshift/postgres for this query?
- `Time` field is unused? can/should it be excluded from the query?
- `amvlju` fields are the strain values in mirostrain units, `µε` or `µS` on y axis?
- `hzcn` fields are load %? this should be x axis? i see some duplication of these values for a single sensor. is this combined data from multiple trials? if the load is only in increasing order and not duplicated we can better use the Trend panel instead of XYChart.

  also, all these `hzcn` fields have identical data, so presumably they can be JOINed on to avoid duplication?

  ```
        [
          25.2872518794959, <-- dupe 1
          25.2870896208556,
          25.2871977932825, <-- dupe 2
          25.2874141381362,
          25.2872518794959, <-- dupe 1
          25.2867651035751,
          25.2873059657093,
          25.2867110173617,
          25.2856833793066,
          25.2863865000811,
          25.2871977932825, <-- dupe 2
  ```

**Comment by leeoniya** [comment]
> The main issue is when we have long-format data, and wish to have one trace per "type". Redshift allows us to visualize our long-format data using the Format:timeseries setting. This will give us one trace per type

what is a "type" in the provided dataset? is it the sensor_id? `57FS001A_A1`

```
        {
          "config": {},
          "labels": {
            "strain_sensor_id": "57FS001A_A1"
          },
          "name": "hzcn",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          }
        },
        {
          "config": {},
          "labels": {
            "strain_sensor_id": "57FS001A_A1"
          },
          "name": "amvlju",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          }
        }
```

**Comment by jayceslesar** [comment]
I spent a good amount of time debugging this today with my team and we believe it comes down to us abusing tall format data in XYChart. The data for the plot we are trying to make comes from 2 tables essentially but we thought it would be better to join to data into one table in the database, and just feed grafana that. It turns out we get better performance, and all the overrides properly work when we set up a panel with multiple data sources (one for each table) and transform that into something an XYChart likes with an INNER join transformation

**Comment by leeoniya** [comment]
> I spent a good amount of time debugging this today with my team and we believe it comes down to us abusing tall format data in XYChart

maybe; maybe not :sweat_smile: . the XYChart panel has some fundamental issues that we think are fixed by the rewrite in v11.1+. it would be great for us to verify that we have in fact made all the correct improvements for use cases like this one.

> It turns out we get better performance, and all the overrides properly work when we set up a panel with multiple data sources (one for each table) and transform that into something an XYChart likes with an INNER join transformation.

if you have it working / looking as you need, i would love to see a sanitized version of this version in a debug dashboard similar to https://github.com/grafana/grafana/issues/86642#issuecomment-2069506409. it will help us improve XY and/or allow me to give you better advice. you should not need two datasources, that sounds like a huge hack :D

**Comment by leeoniya** [comment]
for SQL datasets, XYChart works well with tall dataframes, actually. you simply need to use the `Partition by values` transformations to split the single table into multiple series by one or more "discriminator" columns. in your case that column would be `type` (sensor ID)

https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#partition-by-values

**Comment by jayceslesar** [comment]
hmmm I can't seem to get an XYChart to work that way, it fails with 
```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'label')
```
when I run the query haha. I think this is because I am attempting to give the XYChart 3 values to plot and it is crashing before I can filter them down which is frustrating. Should be able to be solved by changing the query to return data in the format of

timestamp,strain_id,value_type,value
1,some_strain_id,strain,some_strain_value
1,some_strain_id,load,some_load_value
...

**Comment by leeoniya** [comment]
if you can just do a Table panel with the tall/long data and attach that snapshot here i can do the XYChart-fu
