### ISSUE TITLE
Authentication: SAML login button cannot be displayed

### ISSUE THREAD

**Issue by tkf0618** [grafana/grafana#86647]
### What happened?

When I set the "enable" for auth.saml to true, I cannot see the SAML login button on the login page. The configuration file is defaults.ini, which is located at /usr/share/grafana/conf within the Grafana container. In contrast, when I set the "enable" for auth.generic_oauth to true, I am able to see the corresponding login button.

### What did you expect to happen?

I can see SAML login button when I set auth.saml.enabled is true.

### Did this work before?

I have not noticed. This is my first time to use Grafana.

### How do we reproduce it?

1.  Deploy the Grafana container using grafana/grafana-enterprise:latest.
2.  Enter the container and modify /usr/share/grafana/defaults.ini to set the enabled value of auth.saml to true.
3.  Restart the container.
4.  Enter the URL of the Grafana login page in the browser and check the page.

### Environment (with versions)?

Grafana:  v10.4.0 (03f502a94d17f7dc4e6c34acdf8428aedd986e4c)
OS:  Grafana Docker Image (grafana/grafana-enterprise:latest)
Browser: Chrome

### Grafana platform?

Docker

**Comment by kalleep** [comment]
Hey sorry for late response but saml is a enterprise feature that requires a valid license, so even if you are running the enterprise docker image saml won't work unless you have a valid enterprise license.
