### ISSUE TITLE
Telegram alerting. More info about returned error.

### ISSUE THREAD

**Issue by vilkoivshchi** [grafana/grafana#86669]
I've try to set up notifications over Telegram, but get error:

```Failed to send test alert.: failed to send telegram message: webhook response status 400 Bad Request```

According TG bot [documentation](https://core.telegram.org/method/messages.sendMessage) status 400 have about 40 values. 
Please add more info to this message, i.e.:

```Failed to send test alert.: failed to send telegram message: webhook response status 400 Bad Request.  <What exacly happened>  ```

**Comment by mike2194** [comment]
same

```
Grafana v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)
```

**Comment by mike2194** [comment]
actually, mitigated the issue.

changed `Parse Mode` to anything except `MarkdownV2` is successful delivering alert
