### ISSUE TITLE
[Bug] mysql time_sec doesn't support DECIMAL timestamps

### ISSUE THREAD

**Issue by seanhoughton** [grafana/grafana#8666]
Grafana: 4.3.2 docker container
Mysql datasource
mysql: 5.7.10
tables: InnoDB

The mysql datasource seems to expect an INTEGER typed timestamp. However, the UNIX_TIMESTAMP macro can return DECIMAL typed columns. This results in a moderately confusing error about rows with no time values.

Example query:

```
SELECT
 FLOOR(UNIX_TIMESTAMP(time)) as time_sec,
 avg_delay AS value,
 task_name AS metric
FROM
(
SELECT 
    DATE_FORMAT(TIMESTAMP(created), "%Y-%m-%d %H:00:00") AS time,
    name AS task_name,
    AVG(delay) as avg_delay,
    AVG(delay) as total_delay
    FROM Tasks
AS items
GROUP BY time, task_name
)
AS items
WHERE $__timeFilter(time)
ORDER BY time_sec ASC;
```

The code that's raising the error:

```
if !rowData.time.Valid {
    return fmt.Errorf("Found row with no time value")
}
```

The workaround is to use the FLOOR function, e.g.

```
FLOOR(UNIX_TIMESTAMP(time)) as time_sec,
```

**Comment by torkelo** [comment]
is there a reason for   DATE_FORMAT(TIMESTAMP(created),, why not use UNIX_TIMESTAMP(created) ? 

what is the type of created?

**Comment by vls29** [comment]
@seanhoughton so glad I found this issue!  I've just spent 2 hours trying to work out what "Found row with no time value" meant with my query.

My query was
`SELECT
UNIX_TIMESTAMP(DT) as time_sec, windspeed as value,
  'windspeed' as metric FROM HOMEDATA WHERE $__timeFilter(DT)
ORDER BY DT ASC`

I had finally managed to narrow it down to the time_sec column having inserted a fixed unix timestamp, then tried your floor suggestion above and it's fixed :)

For reference, before the floor function is added around `UNIX_TIMESTAMP(DT)`, this is a snippet of the data that comes back from the above query:

time_sec | value | metric
1454241600.00 | 4.28 | windspeed
1454241660.00 | 3.92 | windspeed

**Comment by vesajaaskelainen** [comment]
Hi, With latest publicly available Grafana this is still happening.

Problem comes if one uses new sub-second precision for timestamps.

When you define your timestamp field with type DATETIME(6) (instead of traditional second precision DATETIME).

As a workaround one can use FLOOR operator to get something out but you lose the precision then. Currently it does not work out-of-box with MariaDB/MySQL when using higher precision timestamps.

Was there particular reason why this ticket was closed?

**Comment by maxtdaddy** [comment]
I'd like to reinforce the "Found row with no time value" problem.  The "floor" solution above solved it for me.  I'm using MariaDB and OpenHAB, which creates the tables automatically.  The time column that it creates converts with UNIX_TIMESTAMP to 3 decimals, which Grafana does not like. Using Floor in the Grafana SQL Query eliminates the decimals and takes care of the problem.

**Comment by daniellee** [comment]
This is now possible to implement after updating the MySql driver to a version that implements the ColumnType interface:

https://github.com/grafana/grafana/commit/7bc7af6c393f0a744d02bf86c7e2c98b3705f5a2

The plan is to change the implementation to be as similar as possible as the Postgres implementation. Currently, the time column has to have a `time_sec` alias (as time must be in seconds). Postgres uses a `time` alias OR checks the type and it supports subsecond precision.
