### ISSUE TITLE
Grafana can't talk to Prometheus that works with `curl`

### ISSUE THREAD

**Issue by cubranic** [grafana/grafana#8668]
Grafana version: 4.3.2
Datasource: Prometheus (in the proxy mode, no auth, plain HTTP)
OS: Linux

Testing the data source fails with the message "Bad gateway", even though it is reachable through `curl` from the Grafana host.

Grafana log (journalctl) shows:
```
http: proxy error: read tcp {grafana-host}:41874->{prometheus-host}:9090: read: connection reset by peer
```

**Comment by torkelo** [comment]
please use community site for questions. 

We have no other reports on Grafana not being able to reach prometheus  so this is very likely a network issue and not a Grafana bug.

**Comment by torkelo** [comment]
i wish I could help more, but not sure what the connection issue could be.

**Comment by cubranic** [comment]
OK, thank you. Will follow up there.
