### ISSUE TITLE
The suggested configuration file is recommended in yaml format

### ISSUE THREAD

**Issue by penhauer-xiao** [grafana/grafana#8669]
Sorry, registered account, has not received confirmation mail,  from https://community.grafana.com. 
so here my proposal, why the configuration file is not used yaml format, but the ancient ini format, yaml format clear and easy to understand, the relevant topics can be organized into a tree shape.

**Comment by torkelo** [comment]
yaml has some bad sides as well (fickly white space & indentation issues), but I agree, would prefer to have yaml. 

But to late now, do now want to introduce a new ini format (nor break old installs)

**Comment by penhauer-xiao** [comment]
@torkelo 
Can also support two formats (ini & yaml) configuration, is fully able to do for the user to choose according to their own habits and preferences;
