### ISSUE TITLE
Elastic alerting - error

### ISSUE THREAD

**Issue by softwareklinic** [grafana/grafana#8670]
What could be causing this error....

![image](https://user-images.githubusercontent.com/7537289/27367881-ef6cd5f2-5614-11e7-8a09-a391858c937b.png)

Also shows

**error tsdb.HandleRequest() error Could not find executor for data source type: elasticsearch**

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
elasticsearch is not supported data source in alerting 

https://github.com/grafana/grafana/issues/5893

**Comment by caneraydinbey** [comment]
Still? @torkelo

**Comment by hsafe** [comment]
@torkelo
Can you please clarify when and why? any time table for this feature?In fact with the introduction of the filebeats and hugely popular elasticsearch, and on the other hand the tons of costs on Watcher and X-pack seems to me a great "must have"...

**Comment by hsafe** [comment]
@torkelo I will eagerly wait for that and forgot to express my gratitude in earlier message...Great Job

**Comment by trautw** [comment]
@torkelo Do you need some beta-tester?
I am running v5.0.0-beta2

**Comment by tuncerinan** [comment]
sory what pluging supported alerting .

**Comment by marefr** [comment]
@tuncerinan see http://docs.grafana.org/alerting/rules/#execution
