### ISSUE TITLE
Multiple Commands While Holding a Meta

### ISSUE THREAD

**Issue by niabassey** [grafana/grafana#86710]
**Steps to reproduce**:
Hold a pseudo meta key and type a command key, then _without releasing the meta_ type another command;  

For instance: Hold **t** and press **left arrow** twice, where **t** is the meta and **left arrow** is the **Move time range back** command.

**Actual Result**:
Only the first command press is honored.  _The meta key must be released and reengaged_ before a second command press is honored.

**Expected Result**
As long as the meta key is held, subsequent presses of command keys should all be honored.  In the case above holding **t** and pressing **left arrow** twice should Move time range back two times.

In another example holding **g** while pressing **h** then **d** then **e** then **p** should go to each of Home Dashboard, Dashboards, Explore and finally Profile.  All without releasing **g**.

In the same way holding **d** while pressing **r** repeatedly should refresh the charts for every **r** press without ever releasing **d**. 

**_This behavior mimics the OS behavior of the ctrl/command keys, reducing the number and complexity of keystrokes._**

**Environment**:
- Grafana version: v10.4.2
- Data source type & version: Any (Tested with InfluxDB)
- User OS & Browser: Windows 11 & Chrome 123
- Others:

**Comment by tskarhed** [comment]
It is behaving as implemented, but I agree with you that your suggestion is a better user experience.
