### ISSUE TITLE
[Help] why the Alert can't get the data?

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [grafana/grafana#8673]
- Grafana version  
   4.3.2
- datasource  
  influxdb with heapster
-  OS 
  centos 6

I want to use the grafana to alert,but it cat't get the data,why? the detail:

the data is not null

![1](https://user-images.githubusercontent.com/18111540/27372711-1b9f29ee-5698-11e7-9bee-5d17b287129b.png)

the alert config

![2](https://user-images.githubusercontent.com/18111540/27372727-282a54fe-5698-11e7-905d-20e24d808128.jpg)

**Comment by torkelo** [comment]
Try increasing time range on the alert query condition. 

Please use community site for questions and support
