### ISSUE TITLE
Alertlist Panel Plugins: When execute_alerts=false is set, no list is displayed in the Alertlist panel.

### ISSUE THREAD

**Issue by jooyg62** [grafana/grafana#86752]
### What happened?

We are using integrated alarms and employing them in a cluster.

Among a total of three Grafana instances, two that are used for web purposes have the execute_alerts=false setting, and one instance used for alarms is set to execute_alerts=true.

During the migration from version 8 to version 10, we discovered that the Alertlist panel does not display any list.

Upon investigation, it appears that no list is displayed when execute_alerts=false.

Please check this issue. Thank you.

### What did you expect to happen?

I would like the list to be displayed in the Alertlist panel even when execute_alerts=false is set.

### Did this work before?

It worked properly in Grafana version 8.

### How do we reproduce it?

1.Trigger an alarm and confirm that it appears in the Alertlist.
2.Set execute_alerts=false and restart Grafana.
3.Confirm that the alarm no longer appears in the list.

### Environment (with versions)?

Grafana: 10.3.3
OS: CentOS Linux release 7.9.2009 (Core)
Browser: Google Chrome

### Grafana platform?

None

**Comment by soniaAguilarPeiron** [comment]
This is working as expected. As the alert panel show alert rules with more than one instance. 
Using `execute_alerts=false` leads to not having any alert instance.
