### ISSUE TITLE
[Bug] CloudWatch ECS Dashboard fails to display data

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#8676]
- What Grafana version are you using?
4.3.1
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
Linux AMI
- What did you do?
Added AWS ECS Dashboard in order to display AWS ECS metrics via Grafana

- What happened instead?
I received the following error on the UI : Unalbe to call AWS API
When I checked the grafana.log file I can see the following error:
Unable to call AWS API" logger=context userId=3 orgId=1 uname=dome9 error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"

- If related to metric query / data viz:
When checking via chrome developer tools I've received the following error:
500 (Internal Server Error)
 
![image](https://user-images.githubusercontent.com/24862189/27382019-b5e6d8d6-568d-11e7-9afe-3d38182bdff5.png)

**Comment by torkelo** [comment]
You need at least one dimension

**Comment by dudusakharovich** [comment]
@torkelo 

What do you mean ? What is missing ?

**Comment by dudusakharovich** [comment]
@torkelo 

The only two available dimensions are cluster name & service name and there are no values for both of them.

**Comment by torkelo** [comment]
if you have no values for them then I guess there is no data there. You need a dimension and dimension value filter to get data with cloudwatch
