### ISSUE TITLE
Query Library: User tracking

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#86761]
Define what user tracking is needed. What are the success criteria.

Update: The doc that outlines user tracking events is here: https://docs.google.com/document/d/1B4WT-axUsMyQwbD-HEu9zS_qtZoTJUIDP4ciz60UoDU/edit

**Comment by harisrozajac** [comment]
This is what we can track:

Query Library

1. Query Library opened/closed

Query

1. Filtered
2. Sorted
3. Starred
4. Duplicated
5. Added from query row
6. Added from query history 
7. Deleted
8. Added tag 
9. Pagination toggled 
10. Query run
    1. Same datasource
    2. Switched datasource
