### ISSUE TITLE
[Feature request] Specifying AWS credentials via environment variables

### ISSUE THREAD

**Issue by swaranga** [grafana/grafana#8677]
Team,

I want to use the Cloudwatch datasource but don't want to keep a ~/.aws/credentials file with my access in plain text lying around. This is a security risk best avoided. Even if the credentials are for Cloudwatch read-only it can still be problematic if exposed.

Please add support for being able to specify the credentials via env variables like:

```
GF_DATASOURCE_CLOUDWATCH_PROFILE_AWS_ACCESS_KEY_ID
GF_DATASOURCE_CLOUDWATCH_PROFILE_AWS_SECRET_ACCESS_KEY
GF_DATASOURCE_CLOUDWATCH_PROFILE_AWS_REGION
```

Here ```GF_DATASOURCE_CLOUDWATCH_``` is a static prefix, ```PROFILE``` is placeholder for the datasource profile and the remaining are the actual keys.

Other than that, thank you for an amazing product!

**Comment by torkelo** [comment]
if you do  not want to use awsconfig file you can specify the secret & client id from the UI, grafana will store them encrypted in it's database. 

We hope to provide a way to define data sources via config files sometime in the future  (think there is an issue for it). Might provide a mirrored way to specify those files via env vars

**Comment by swaranga** [comment]
Here is what I can specify when trying to add a Cloudwatch datasource:
```
Credentials profile name
Default Region
Custom Metrics namespace
Assume Role ARN
```

How do I specify the access and secret keys? I am using Grafana v4.0.2 (commit: v4.0.2) - is this available in a newer build?

**Comment by torkelo** [comment]
yes, try upgrading to 4.3
