### ISSUE TITLE
Define Threshold values relative to current unit 

### ISSUE THREAD

**Issue by scjoiner** [grafana/grafana#8679]
Grafana 4.1, Single Stat panel.
Data source InfluxDB

We are measuring disk usage in kB and displaying in GB or TB using the "Unit" feature in the Single Stat panel. The stat itself will adjust according to the unit selected, but the Thresholds do not. 

Expected behavior would be for threshold labels to scale by the same factor as the stat itself, in this case dividing by 1,000,000.

![image](https://user-images.githubusercontent.com/4303855/27392167-edcaeb76-5673-11e7-9a4f-f093c0317207.png)

**Comment by wood-jp** [comment]
2 years later, any updates on this?

**Comment by xafer337** [comment]
Any updates? I'm interested in showing the threshold values with their units.

**Comment by MaxDiOrio** [comment]
Any update?  This is preventing the From Now from having thresholds.
