### ISSUE TITLE
Add Amazon Kendra in the Namespace pull-down for CloudWatch metrics

### ISSUE THREAD

**Issue by scottschreckengaust** [grafana/grafana#86808]
**Why is this needed**:
Amazon Kendra is missing in the Grafana namespace pull down.

**What would you like to be added**:
Within Grafana, the Amazon Kendra metrics should be made available.

**Who is this feature for?**
Users choosing Kendra metrics for Grafana with the user interface.

**Comment by zspeaks** [comment]
Code ref here: https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/constants/metrics.go
