### ISSUE TITLE
Bar Chart is Giving Cannot Read Properties of undefined 

### ISSUE THREAD

**Issue by adityamauryaMog** [grafana/grafana#86823]
### What happened?

![Screenshot from 2024-04-24 12-12-44](https://github.com/grafana/grafana/assets/93261315/85cf5142-3944-4add-b5b0-daaadba33b5f)

### What did you expect to happen?

It Just Not show alert like this make a default graph

### Did this work before?

Grafana 8.4.5

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

Yes This bug is inside Panel When the Query return 0 Rows Than these things happened

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

MySQL

**Comment by tonypowa** [comment]
Hello @adityamauryaMog 
We wanted to bring to your attention that the version you're currently using is not supported. If you encounter any issues or have feature requests, we encourage you to submit them as a new issue on a supported version.
Thank you for your understanding.
