### ISSUE TITLE
[Bug] Query string  params escaping . in templated variable when 'Include All option' activated

### ISSUE THREAD

**Issue by JLSNZ** [grafana/grafana#8683]
- What Grafana version are you using?
grafana 4.3.1
- What datasource are you using?
Prometheus 1.5.0 with snmp_exporter
- What OS are you running grafana on?
Ubuntu 14:04 LTS
- What did you do?
Imported  dashboard https://grafana.com/dashboards/1124 and viewed
- What was the expected result?
Network interfaces/subinterfaces have query data returned and graphed
- What happened instead?
Network subinterfaces that have a . in the name have no data returned or graphed
- metric query from dashboard defined as
`
irate(ifHCOutOctets{job='snmp',instance='$Device',ifDescr='$Interface'}[5m]) * 8 or irate(ifOutOctets{job='snmp',instance='$Device',ifDescr='$Interface'}[5m]) * 8
`
Chrome network query headers
Without "Include All option" Enabled
`query:irate(ifHCOutOctets{job='snmp',instance='DEVICE',ifDescr='ae0.150'}[5m]) * 8 or irate(ifOutOctets{job='snmp',instance='DEVICE',ifDescr='ae0.150'}[5m]) * 8
start:1498081994
end:1498103594
step:120`
With "Include All option" Enabled, note `\\`
`
query:irate(ifHCInOctets{job='snmp',instance='DEVICE',ifDescr='ae0\\.150'}[5m]) * 8 or irate(ifInOctets{job='snmp',instance='DEVICE',ifDescr='ae0\\.150'}[5m]) * 8
start:1498082310
end:1498103910
step:120
`

**Comment by torkelo** [comment]
If you use include all (or multi value) you need to use the variable in with a regex operator in your prometheus query, otherwise you cannot filter on multiple values

**Comment by JLSNZ** [comment]
You are correct, a regex operator is being used.
The above dashboard uses `/.*ifDescr="(.*?)",.*/`, I have also tried multiple different capture group options. eg `/.*ifDescr="([xg]e[-\/\d]*|st0\.*\d*|reth\d\.*\d*|ae\d\.*\d*|vlan\.\d*|fab\d|vme\d*)",.*/`

The "Preview of values" shows the correct list with either regex, otherwise you are correct, none would match.
An  example of the values in the "Preview of values" when editing the template var

`ae0` `ae0.150` `ae0.151` `ae0.154` `ae0.1791` `ge-0/0/0` `ge-0/0/0.0` .....

When `All` is enabled, the dashboard shows one graph for every interface (tiled down the page), which corresponds to 2 HTTP GET from the dashboard for each graph (in and out octets) to the grafana backend. Any interface that has a `.` in the name the query gets sent to the backend with `\\` before the dot, as per the original ticket example, causing no match in the prometheus backend as no interface called `ae0\\.150` exists.

If I replace the templated `$Interface` with the literal string `ae0.150` in the graph edit interface, this queries the backend fine without the escaping, however I only get one graph, the same is true if I still use `$Interface` in the graph query and remove `All` as per the original ticket, I have to unhide the the `$Interface` variable so I can pick the individual graph, but each graph works fine, as soon as `All` is enabled it somehow triggers an escape encoding for the `.` causing problems

**Comment by torkelo** [comment]
yes, if it did not escape you could not use it in a regex filter in the prometheus metric query and not match on multiple values. 

You need to use a regex label filter in your **METRIC QUERY**

**Comment by JLSNZ** [comment]
@torkelo Thanks for clarifying and your patients, very new to using both grafana and prometheus
