### ISSUE TITLE
Graphite Datasource: Autocomplete for tag values doesn't include the time range

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#86842]
### What happened?

When using the query builder for graphite with tags, the time range is issued only for tag key autocomplete and not tag values. 

Autocomplete for tag key:
`https://grafana.example.com/api/datasources/proxy/uid/001/tags/autoComplete/tags?expr=namespace%3Dos&expr=name%3Dcpu.percent.idle.g&expr=cluster%3Dtkapps&limit=5000&from=1713934740&until=1713956388`

Autocomplete for tag value:
`https://grafana.example.com/api/datasources/proxy/uid/001/tags/autoComplete/values?expr=namespace%3Dos&expr=name%3Dcpu.percent.idle.g&expr=cluster%3Dtkapps&tag=host&limit=5000`

### What did you expect to happen?

I expect the time range for autocomplete to specified for both so that the result set only matches the values available in the currently selected time range.

### Did this work before?

As far as I know, this has always been the behavior. I only notice it know as we move to Grafana Mimir backend and the autocomplete is slow because no time range is given.

### How do we reproduce it?

1. Create a graphite datasource with tags
2. Use the graphite autocomplete

### Environment (with versions)?

Grafana: 10.0.1
OS: Windows
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

Graphite

**Comment by bossinc** [comment]
We did not set the time range here. https://github.com/grafana/grafana/blob/b97fb3bb78633135caaacc220861672e70ef01d4/public/app/plugins/datasource/graphite/state/providers.ts#L201 

I believe if we add the time range, the issue will be fixed. More testing is needed. @alyssabull
