### ISSUE TITLE
[Bug] Hover tooltip shows last value when no value available

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8686]
Grafana version: 4.3.2
Datasource: MySQL
OS: Windows 2008 R2

The hover tooltip shows last available value for series when no value available for selected date.
Should not show any value of series without values for specific dates.
Please see attach sample.
 
![grafana-series-without-values](https://user-images.githubusercontent.com/29407741/27437689-5447e7b0-5763-11e7-84c8-15e7d2c4db9b.png)

**Comment by torkelo** [comment]
if your query returns no values it will show the last, change your query to return null values for missing values

**Comment by fmcmarques** [comment]
I understand, but is harder to generate fake data that is not there.
I think that doesn't make sense for 22/Jun to show the value of 19/Jun, this is a presentation Bug and i think that is better to Grafana be deal with it and protect against this situation.
Thks

Sometimes

**Comment by torkelo** [comment]
most time series databases has away to group data into intervals, so if there is no data for an interval there is a null value. Grafana usually provides an interval variable to data source queries (the interval is dynamic and dependant on time range and how wide the graph is), looks like we have not added that to MySQL yet. 

But for your case, just add a group by time,

**Comment by fmcmarques** [comment]
I have a group by time, but if there is no records for that specified time, the group by will not produce any record/value for that time (missing value).

**Comment by torkelo** [comment]
oh, so used to time series databases being able to create null values for missing group by ranges.

**Comment by ipmb** [comment]
> if your query returns no values it will show the last, change your query to return null values for missing values

Is this an option with the Cloudwatch datasource? I'm seeing the same thing and not sure how to resolve it.

![2018-01-11 at 10 28 am](https://user-images.githubusercontent.com/319156/34838135-3e3f5efc-f6ba-11e7-830f-de0c637317cb.png)

**Comment by amithsharma** [comment]
is there a way to hide the text when hover?
