### ISSUE TITLE
[Bug] Template variables in case of time-change should be updated before executing the data selection query, not in parallel

### ISSUE THREAD

**Issue by lucamag** [grafana/grafana#8687]
This bug can be reproduced having a parent/child relation on template variables with parent of type 'Interval' with auto enabled. When the time selection changes, we observed Grafana executes in parallel both HTTP requests, one for the  "SHOW TAG VALUE WITH KEY=... "for the child as well as the one to select the data. The expected behaviour should be to first update all templates, and after execute the data query. 

This is related with this: https://community.grafana.com/t/parent-child-template-variables-using-interval-type-with-auto/1000/2

Easy way to reproduce:
*  go to the Grafana dashboard example here http://play.grafana.org/dashboard/db/influxdb-templated-queries?orgId=1
* exploring (with Developer tools) what happens when  'datacenter' changes shows that:
  * first the SHOW TAG VALUES WITH KEY = "hostname" WHERE "datacenter" =... is executed
  * then the actual SELECT to get the data
* now, create a new template variable of type Interval named 'foo' with auto option enabled
* change the 'host' variable to: SHOW TAG VALUES WITH KEY = "hostname" WHERE "datacenter" =~ /^$foo$/ 
* check with Developer tool what happens on changing the time interval now shows that now both the SHOW TAG query and the SELECT ones are executed in parallel

Please include this information:
- What Grafana version are you using?
Grafana 4.2
- What datasource are you using?
InfluxDB 1.2
- What OS are you running grafana on?
CentOS 7.3

**Comment by torkelo** [comment]
Cannot replicate, the metric query is executed after the template variable is updated

**Comment by torkelo** [comment]
http://play.grafana.org/dashboard/db/influxdb-templated-queries?orgId=1

has a interval variable already, I can change variable or time interval variable or time range and the metric query has the correct values.

**Comment by lucamag** [comment]
Hi Torkelo, 
thanks for the answer. Let me explain better, on http://play.grafana.org/dashboard/db/influxdb-templated-queries?orgId=1 
* add a dependency on the time variable changing the 'host' template  to: SHOW TAG VALUES WITH KEY = "hostname" WHERE "datacenter" =~ /^$summarize$/
* move $summarize up in the order of templates to fulfil dependency
* try to change the time range

As far as I can see, the the "show tag" and the "select" query are executed in parallel, hence breaking the dependency. 
That explains the problem we're facing as described in https://community.grafana.com/t/parent-child-template-variables-using-interval-type-with-auto/1000/2

Cheers, 
Luca

**Comment by torkelo** [comment]
Sorry, that use case is not supported. Time range changes will always cause panel refresh and not wait for interval variable updates.

**Comment by lucamag** [comment]
I see. Can this become then a feature request? 
As by the use case in [1], this would be a major improvement when working on InfluxDB backend and using multiple retention policies to store data with different resolution, relying on the interval variable, including 'auto' option, to build the correct metric query.

Cheers, 
Luca

[1] https://community.grafana.com/t/parent-child-template-variables-using-interval-type-with-auto/1000/2
