### ISSUE TITLE
[Feature Request] Add a metric to the ElasticSearch data source that show the last value

### ISSUE THREAD

**Issue by lfdominguez** [grafana/grafana#8688]
Hello, I'm using Grafana into my network (I'm a system administrator) with ElasticSearch as backend (data source), then I have installed the plugin to draw diagrams. In another virtual server, I have installed a program (HeartBeat from Elastic) to save the ICMP and TCP alive of my services and servers. That save into my server the time of the ping and TCP as if the service is UP as a boolean.
The principal problem in Grafana is that wen I add a metric to the panel I want to show if the service is UP, but I can't see any metric for the last value, all are Max, Min, Average, etc. and any of then resolve my problem, for example for Max: (0 is DOWN, 1 is UP):
If I can show the last 30 min, then the Metric catch the Max of that 30 mins, then if I have the service down, then I can see if in that window of time already have another with 1, because 1 > 0.

**Comment by torkelo** [comment]
I do not see a Last aggregation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics.html

**Comment by lfdominguez** [comment]
Well, but I see the top hits...
Without that aggregation, how I can do that? get if the service if UP with the last value?

**Comment by torkelo** [comment]
top hits does not provide last.

What grafana panel are you using? You can choose what legend value to show (Current(last), Total, Min, Avg) in the Graph Legend tab. 

The Singlestat also has a Stat option where you can select Current, Total, Min, Avg. 

In both cases using Current will show the last value of the Elasticsearch metric (so if you have Avg ES aggregation it will show last Avg).

**Comment by lfdominguez** [comment]
That's the problem, the average of 0,1 is 0,4 0,5 etc. so I need take the last value 0 or 1. I'm using the Diagram plugin.
Thanks for responding...

**Comment by torkelo** [comment]
but the average is only applied if you have more than 1 value for each date histogram interval bucket.

**Comment by lfdominguez** [comment]
Yeap I get the data every 5 secs and I have in Graphana last 30 mins. soo thinking, if in the group by the option of the metric I set Date histogram with an interval of 5 secs, then is a simulation of the last value??
