### ISSUE TITLE
Snapshot: Snapshot still exists after dashboard is deleted

### ISSUE THREAD

**Issue by lucychen-grafana** [grafana/grafana#86887]
### What happened?

After a dashboard is deleted, it's snapshot still exists and still shows up in the snapshot section. 

### What did you expect to happen?

When a dashboard is deleted, it's snapshot should also be deleted

### Did this work before?

No

### How do we reproduce it?

1. Create a dashboard
2. Create a snapshot
3. Delete dashboard
4. Go to snapshot list and notice snapshot still there

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by evictorero** [comment]
This is intended, the Snapshot is independent from a Dashboard.
