### ISSUE TITLE
Generic OAuth supports a "groups_url" configuration option

### ISSUE THREAD

**Issue by dtrejod** [grafana/grafana#86894]
**Why is this needed**:
I would like to restrict access to Grafana to users in a specific set of groups from my oauth provider. My oauth provider doesn't return the set of user groups in the `api_url` and instead requires you to hit another API endpoint to get a user's groups. In the `generic_ouath` Grafana integration today there are 2 [configuration options](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configuration-options) revolving around team/groups. 

From my understanding:
- Groups: Only used for the oauth workflow for validating a user can access Grafana.
- Teams: A Grafana internal concept for mapping users into logical "teams" that can be used for RBAC in Grafana. 

**What would you like to be added**:
In my oauth provider, the group memberships for a user are retrieved from another API endpoint. Therefore I would like if "groups" supported a similar concept to "teams" by having a corresponding `groups_url` that can be used to retrieve a user's groups. A combination of `allowed_groups` and a new `groups_url` configuration option would enable me to restrict Grafana access to a set of users in specific groups from my oauth provider. 

Alternatively, I could see the above workflow being supported if Grafana had a `allowed_teams` configuration to restrict access to grafana to a subset of teams. This new teams configuration optional ideally would would work similarly to `allowed_groups`. I think the 1st approach of `groups_url` makes more sense however given my understanding of the differences between "groups" and "teams" in the Grafana generic oauth integration. 

**Who is this feature for?**
Operators the utilize the `genric_oauth` Grafana auth integration and want to restrict access to only users in certain groups.

**Comment by kalleep** [comment]
Hey I would really like to avoid having to add new options to generic oauth that kinda overlaps.

Looking through the code a bit maybe the combination of `teams_url` and `team_ids` would work for you. It seems like `teams_ids` is just a list of strings that functions exactly like `allowed_groups` but is applied when using `teams_url`.

You would also `team_ids_attribute_path` to specify where in the response to extract the ids from

**Comment by dtrejod** [comment]
`team_ids` looks like it is what I was asking for with my `allowed_teams` comment! I'll try using that for now

**Comment by kalleep** [comment]
I will close this for now, feel free to re-open if it don't work out

**Comment by dtrejod** [comment]
Circling back -- 

I can confirm that using `team_ids` works! To use a group with spaces from my oauth provided I needed to have the below change in place, included in Grafana >=11.x. Then in `team_ids` you can pass in a via `team_ids: ["<GROUP_NAME>"]`

https://github.com/grafana/grafana/pull/85735
