### ISSUE TITLE
grafana.ini login_hint and password_hint not working

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#86899]
### What happened?

set grafana.ini  config
```
[user]
login_hint = xxx
password_hint = xxx
```

### What did you expect to happen?

`/login` to show hints.

### Did this work before?

i assume yes but not sure. I have the issue on:
    image: grafana/grafana:10.2.6-ubuntu
    image: grafana/grafana:10.4.2
    image: grafana/grafana:11.0.0-preview

### Grafana platform?

Docker

**Comment by steverweber** [comment]
as a workaround here is a hacky way to tweak things.

```bash
find_regex='performance.mark.*frontend_boot_js_done_time_seconds'
<<'EOF' sed -i "/$find_regex/r /dev/stdin" /usr/share/grafana/public/views/index.html
//START_CUSTOM_JS
if (window.location.pathname == '/login') {
    document.head.insertAdjacentHTML("beforeend", `<style>
        img[src="public/img/grafana_icon.svg"] {display:none !important}
        a[href="/user/password/send-reset-email"] {display:none !important}
        .footer {display:none !important}
    </style>`)
    setTimeout(() => {
        cb = document.querySelector('.login-content-box')
        html = cb.innerHTML.replaceAll('Welcome to Grafana', 'Grafana')
        html = html.replaceAll('Email or username', 'NEXUS username');
        html = html.replaceAll('email or username', 'NEXUS username');
        cb.innerHTML = html
    }, 1000)
}
//END_CUSTOM_JS
EOF
```

**Comment by tonypowa** [comment]
It seems that after stopping and running the docker container for the 2nd time, the changes have finally kicked-in  @steverweber 

can you try again ?
bellow are the relevant docker-compose.yml details:

        image: grafana/grafana:10.4.0 
        environment:
          - GF_USERS_LOGIN_HINT=paco
          - GF_USERS_PASSWORD_HINT=paco

![image](https://github.com/grafana/grafana/assets/45235678/181f1c75-fe98-496d-b5a3-e5127e118a97)

**Comment by steverweber** [comment]
`the docs say [users] not sure if this was a change but that seems to be working on 11.4.0`
```
[user]  --> [users]
login_hint = xxx
password_hint = xxx
```
