### ISSUE TITLE
Grafana Cloud v 11.1.0

### ISSUE THREAD

**Issue by dmitriklein** [grafana/grafana#86896]
### What happened?

No plugins work! "An error occurred within the plugin".

### What did you expect to happen?

Plugins connections OK.

### Did this work before?

In MaaS configuration.

### How do we reproduce it?

n/a

### Environment (with versions)?

Grafana: v.11.1.0
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
Hello :wave:

If you require help, please provide more info.

Thank you!
