### ISSUE TITLE
[Bug] Typing error in error message

### ISSUE THREAD

**Issue by coute** [grafana/grafana#8690]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
Version 4.3.2 (commit: ed4d170)
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Debian 9.0
- What did you do?
Installing grafana with mysql database configured, but i forgot to create the database.
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I got this error message : 
t=2017-06-22T17:38:23+0200 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: Error 1049: Unknown database 'grafana'\n"

There's a typing error here : "lvl=eror"
It could be annoying for a log parser or a grep command.

**Comment by daniellee** [comment]
This is not a bug or typing error. We use the [log15](https://github.com/inconshreveable/log15) package for logging and it returns log levels as 4-character words e.g. eror, crit and warn to keep the column width consistent.
