### ISSUE TITLE
[Bug] Redis configuration documentation

### ISSUE THREAD

**Issue by coute** [grafana/grafana#8691]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
Version 4.3.2 (commit: ed4d170)
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Debian 9.0
- What did you do?
I tried to configure Redis as session provider.
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I'm confuse. I tried to configure redis, but the documentation is not clear.

In the configuration file your example is :
`# redis: config like redis server e.g. addr=127.0.0.1:6379,pool_size=100,db=grafana`

On your [webiste](http://docs.grafana.org/installation/configuration/) i found this example :
`redis: ex: addr=127.0.0.1:6379,pool_size=100,prefix=grafana`

And in a precedent [issue](https://github.com/grafana/grafana/issues/8183) I saw this configuration :
`provider_config = addr=1.2.3.4:5000,pool_size=100,password=SECRETS`

So, what is the good syntax ?

Thanks.

**Comment by oddlittlebird** [comment]
Please let me know what change needs to be made to the documentation.

**Comment by zoltanbedi** [comment]
I think this is changed sometime ago and now the comment in the config file and the docs in our site is the same.
