### ISSUE TITLE
Dashboards module, create a new dashboards inside the json file

### ISSUE THREAD

**Issue by jiadong696** [grafana/grafana#86911]
Dashboards module, create a new dashboards inside the json file, stored in the server directory? How do I use the code to directly import the json file or create the json file where to view, thank you for telling me, thank you!

![image](https://github.com/grafana/grafana/assets/149371204/adeee302-5c8f-4591-8b8d-91c40b4ed787)

As shown in the figure, the json file for this is in the Linux server directory, or the default directory is in that directory

**Comment by tonypowa** [comment]
Thank you for your question @jiadong696  However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on[ https://community.grafana.com/](https://community.grafana.com/)
