### ISSUE TITLE
[Bug] nightly Influx query does not show 'Pane Data Source' choice

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#8692]
Using: Grafana v4.4.0-pre1 (commit: bc6a57ce3)  Downloaded from:
https://ci.appveyor.com/project/Torkeldegaard/grafana/build/4625/artifacts
Running on windows 10

I have two influx datasources configured, when I go to the query editor, there is no option to change the panel datasource!

![image](https://user-images.githubusercontent.com/705951/27448549-0424c2ae-573a-11e7-8eba-64000ed42155.png)

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
