### ISSUE TITLE
Reload/Refresh on Alert Page

### ISSUE THREAD

**Issue by phateuk** [grafana/grafana#8696]
- What Grafana version are you using? v4.3.2
- What datasource are you using? Graphite
- What OS are you running grafana on? Centos 6 x64

Minor feature request. Would it be possible to include a refresh function on this page:
https://yourgrafanadomain/alerting/list

i.e. https://yourgrafanadomain/alerting/list?state=alerting

Would be very useful for many I think so you can simply have this page open and it'll show you what alerts are currently open.

Thanks in advance :)

**Comment by DanCech** [comment]
This would be a good application for a socket connection to keep it up to date.

**Comment by regevbr** [comment]
This indeed will be an awesome feature!

**Comment by regevbr** [comment]
@DanCech should I go ahead and try to implement it myself?

**Comment by regevbr** [comment]
I think it will be even better to also add push notifications to the browser in case of changes to the alerts, that way the user doesn't event need to look at the tab to be notified about it

**Comment by orojina** [comment]
@phateuk  @DanCech  @regevbr  In case you find this useful, and as a temporary solution, I created a script to list alerts with their statuses and the dashboard they belong to. Listing several alerts can be done with:

grafana-cli alerts | grep -i <your_filter_cliteria>

![image](https://user-images.githubusercontent.com/11845190/107563867-32beaf00-6ba7-11eb-8d2f-92f53889c51c.png)

Adding the watch command into the mix will give you and your team an auto-refreshed view of your alerts

https://github.com/orojina/grafana-cli
