### ISSUE TITLE
[Feature-Request] Documentation on table panel date format

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8699]
Please include this information:
- What Grafana version are you using?
Version 4.3.2 (commit: ed4d170)

- What datasource are you using?
InfluxDB 1.2.4

- What OS are you running grafana on?
Linux

- What did you do?
Created a table panel with points having sub-second time resolution.

- What was the expected result?
Be able to figure out how to display sub-second resolution.

- What happened instead?
All times truncated to the second. [No documentation](http://docs.grafana.org/features/panels/table_panel/#column-styles) on how to use a different format.
![image](https://user-images.githubusercontent.com/1826947/27511556-07b15a4c-58f5-11e7-9521-b133bd670bb1.png)

I ended up digging through the source code and found that I could manually enter `YYYY-MM-DD HH:mm:ss.SSS`.

**Comment by walterdolce** [comment]
For those like me landing here whilst trying to find out what's the meaning of the various date format symbols, this is where they are defined: https://github.com/grafana/grafana/blob/13fa3a83785a6022715e7a8f6b663c485eeebd97/pkg/tsdb/elasticsearch/client/index_pattern.go#L200-L247

**Comment by stefaanv** [comment]
Is it possible to have text constants in date formatting ?  For instance "week 50 of 2018".  Can the "week" and " of " be escaped ?

**Comment by stefaanv** [comment]
Found the solution : \w\e\e\k, etc ...

**Comment by walterdolce** [comment]
It would be great if we didn't have to apply that horrible formatting ;)

**Comment by oddlittlebird** [comment]
@jessover9000 , before I update the documentation, is the UX team looking into the time formatting?

**Comment by jessover9000** [comment]
> @jessover9000 , before I update the documentation, is the UX team looking into the time formatting?

I hope I understood correctly what kind of formatting you mean, but a quick research indicated that [ISO formatting](https://en.wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD hh:mm:ss) is best on a global scale.

**Comment by oddlittlebird** [comment]
Is that what we are doing?

**Comment by jessover9000** [comment]
> Is that what we are doing?

I think it is, that's why I am a bit confused about what @walterdolce means by ugly? I guess it's more about generally being able to choose flexibly between options of what to show or not instead of the one-size-fits-all ISO formatting we're doing now? Because that's probably a bigger task that could use its own issue, and in that case that's not something we're currently working on. But if that's what you're aiming at @oddlittlebird I can put it in our backlog :)

**Comment by walterdolce** [comment]
@jessover9000 
> I think it is, that's why I am a bit confused about what @walterdolce means by ugly?

I was referring to @stefaanv's solution mentioned in https://github.com/grafana/grafana/issues/8699#issuecomment-450498365

**Comment by oddlittlebird** [comment]
@dprokop, is this issue still valid?

**Comment by dprokop** [comment]
Nope, this is already covered by https://grafana.com/docs/grafana/latest/panels/field-options/standard-field-options/#custom-units
