### ISSUE TITLE
Filter for aggregation function

### ISSUE THREAD

**Issue by nikicat** [grafana/grafana#87]
Filters are great to select different sets of metrics to display on dashboard, but it would be useful to have filters for functions too.
For example, for overview of thousands-server cluster it is convenient to show several percentiles (for example, 99, 95, 90, 75) on each panel for different system metrics (cpu,memory,disk,network,etc.), but if these percentiles changed rapidly for some reason, I want to know which server (or group of servers) caused this change.
It could be implemented using a filter, which provides a way to select global aggregation function like:
  - percentiles (using percentileOfSeries) - overview mode
  - percentile by groups - to compare server groups
  - top 10 series (using sortByMaxima) - to find misbehaving server or group
  - without aggregation - for raw data, it nothing above has helped

What do you think about it?

**Comment by torkelo** [comment]
already implemented
