### ISSUE TITLE
Support for multiple series & bars (side by side) for same time point 

### ISSUE THREAD

**Issue by marshell08** [grafana/grafana#870]
I have multiple data source on one single graph. For example I have 6 metrics on one single graph.Under chart options when i select bars they all show up on single bar line I want to show them as different bars ? How do i do that ? I have attached a sample image file. 

The problem with having all of them on one single line is the last data source that i add takes up all the space on the bar.

![git2](https://cloud.githubusercontent.com/assets/2876968/4408116/a3c3e922-44d0-11e4-8a33-7482b07307c7.PNG)

![git](https://cloud.githubusercontent.com/assets/2876968/4408071/28210e4e-44d0-11e4-8a4a-30bcb95fe020.PNG)

![images](https://cloud.githubusercontent.com/assets/2876968/4408059/06c121c6-44d0-11e4-8368-1a033dbe44cd.jpg)

**Comment by tomerikko** [comment]
i agree, i miss that as well.      awaiting for the feature request ...

**Comment by catacgc** [comment]
+1

**Comment by sobolews** [comment]
+1

**Comment by tanmaydeuskar** [comment]
+1

It would be great if we are able to draw something like the picture below ...
![image](https://cloud.githubusercontent.com/assets/11692662/8305387/1de0c9f2-19cc-11e5-9b7b-acca901d93d7.png)

**Comment by jgr** [comment]
:+1:

**Comment by hotsnow77** [comment]
+1

**Comment by KunalSaini** [comment]
+1

**Comment by msabramo** [comment]
+1

**Comment by victorhooi** [comment]
I would also love the ability to stack series side by side.

This is our use-case:

![screenshot 2015-08-28 14 23 30](https://cloud.githubusercontent.com/assets/243499/9539121/6429432e-4d90-11e5-899b-b2cdb389541e.png)

We're plotting the connection count over time, as well as the number of connections opened/closed for each bucket.

In the above graph, they're stacked on top of each other - however, it would be better if we could have the opens/closed side-by-side with each other, so you can better compare them.

(If you remove the stacking attribute, it seems to simply overlay the bar graphs on top of each other, which seems a bit...odd. I can't really see the use-case where you'd want that behaviour).

**Comment by mipapo** [comment]
+1

**Comment by kcnummija** [comment]
+1

**Comment by edast** [comment]
+1

**Comment by mortkane** [comment]
+1

**Comment by nichdiekuh** [comment]
+1

**Comment by evanbreznyik** [comment]
+1

**Comment by girgen** [comment]
+1

**Comment by ricardoekm** [comment]
+1!

**Comment by nvgoldin** [comment]
+1

**Comment by lucas-matt** [comment]
+1

**Comment by prawnsalad** [comment]
Are there any plans to have this implemented or is it a low priority thing for now?

**Comment by ryanb93** [comment]
+1

**Comment by Nevett** [comment]
+1

**Comment by russellsilva** [comment]
:+1:

**Comment by digrich** [comment]
+1

**Comment by bdortch** [comment]
+1

**Comment by anuragkyalsc** [comment]
Is there any plan to do this anytime soon?

**Comment by anuragkyal** [comment]
+1

Any timeline you guys have for this feature?

**Comment by timgl** [comment]
+1

**Comment by dbiazus** [comment]
+1

**Comment by sivad77** [comment]
+1

**Comment by gunererd** [comment]
+1

**Comment by seeallsea** [comment]
+1

**Comment by jifwin** [comment]
+1

**Comment by KorkyPlunger** [comment]
+1

**Comment by petrslavotinek** [comment]
+1

**Comment by sergeygalkin** [comment]
+1

**Comment by gwuillou** [comment]
Hello, 
As I am seeing with all these requests, it becomes a high priority feature.  Please help us!

**Comment by kavimaluskam** [comment]
+1

**Comment by absolutejam** [comment]
+1

**Comment by dburm** [comment]
+1

**Comment by ivanovmi** [comment]
+1

**Comment by yamert** [comment]
+1

**Comment by boris-42** [comment]
+1

**Comment by ehorohorin** [comment]
+1

**Comment by misterku** [comment]
+1

**Comment by mmalchuk** [comment]
+1

**Comment by aserrr** [comment]
i++

**Comment by petrslavotinek** [comment]
I've been briefly looking at this and it should be quite easy with jquery.flot.orderBars plugin.
The only a bit more complicated thing would be calculating the bars width.

![image](https://cloud.githubusercontent.com/assets/2470728/20639776/d014d1ea-b3cc-11e6-9f6a-19310b356922.png)

**Comment by rkhozinov** [comment]
+1

**Comment by jifwin** [comment]
Looks neat!

**Comment by geri4** [comment]
+1

**Comment by mbaran0v** [comment]
+1

**Comment by posox** [comment]
+1

**Comment by kuntashov** [comment]
+1

**Comment by CyrilMazur** [comment]
+1

**Comment by danielzheng** [comment]
+1

**Comment by stefanverhoeff** [comment]
+1

**Comment by ldktta** [comment]
+1

**Comment by source-ram** [comment]
+1

**Comment by neckhair** [comment]
Please stop this "+1" noise and use the reactions. Thank you!

**Comment by GianniGiglio** [comment]
+1

**Comment by cincodenada** [comment]
@petrslavotinek Would you mind pushing your changes up to a fork, or otherwise share what you have so far there? It would be nice to be able to patch it in ourselves, and perhaps submit as a PR.

**Comment by petrslavotinek** [comment]
I've created a fork with a new branch: https://github.com/petrslavotinek/grafana/tree/bars_side-by-side.
It works, but it's very basic.
Especially computation of width and spacing of the bars needs some improvement.
I will work on it but no sooner than the next week (after Easter holiday).

**Comment by haidaraM** [comment]
Is there a plan to include this functionality in the main repo?

**Comment by previousdolphin** [comment]
While this functionality is desired by many (myself included), I feel that it would not be in the best interest of properly representing time series data; if your x axis is time, non-stacked elements would indicate different timestamps for the data.

**Comment by JonasGutermuth** [comment]
@previousdolphin: It depends on the way the x axis is shown. Normaly in Grafana the Grid is aligned with the time. In this layout one time is exactly on this line, as you wrote and non-stacked elements would indicate different timestamps:
![image](https://user-images.githubusercontent.com/19645608/30844889-4d117cda-a291-11e7-9764-d8234550a1a1.png)
But it is also possible to layout the grid in a different way. As you can see on the graph below the time is not written on a grid line. This symbolized, that the grouped graphs belong to the same timesatamp: 
![image](https://user-images.githubusercontent.com/19645608/30845168-7010730c-a292-11e7-89eb-d05a08201fe3.png)

**Comment by previousdolphin** [comment]
It the second example is a time locked referential chart with buckets on the x-axis representing entire years.
  

  
I do not know how you would do / show this, within Grafana, which is designed to show the x-axis as a continuous representation of regular time intervals.
  

  
Perhaps they could overlay, and then have some clever animation to spread on a mouse over, and collapse back when your cursor is away?
  

  
  

  
  
>

**Comment by leandro-ss** [comment]
+1

**Comment by vascomedici** [comment]
+1

**Comment by olivierdemin** [comment]
+2 !!!

**Comment by cobab** [comment]
+1

**Comment by kccheung** [comment]
+1

**Comment by Meghna-singh** [comment]
@victorhooi can u explain how you got this connection count over time graph. actually mine use case is also similar to this. i have two queries which i want to be stacked. and multiple series side by side(like many buckets ). i want exactly the same kind of graph like what you posted here.

**Comment by devcode2** [comment]
Google has code that can be used to create charts:  http://gwt-charts.appspot.com/

**Comment by Meghna-singh** [comment]
@devcode2  grafana doesnot supports it . how to implementit in grafana.

**Comment by jonyrock** [comment]
Hey. Our team working on implementing this here:

https://github.com/CorpGlory/grafana-multibar-graph-panel (it is hackable!) 

Please support idea to extract graph panel so it would be easier to maintain the fork https://community.grafana.com/t/repo-for-graph-panel/5895/3

**Comment by nthienan** [comment]
+1

**Comment by jonyrock** [comment]
@CamilleGR @nthienan you can see link above with implementation. There are already people involved and they work on supporting this feature

**Comment by nthienan** [comment]
I really need this feature since https://github.com/CorpGlory/grafana-multibar-graph-panel does not work well, there are many issues. When does Grafana plan for this feature?

**Comment by GarinSmith** [comment]
I agree - it would be great to have support for this feature if possible.

**Comment by kccheung** [comment]
I need this feature as well, as https://github.com/CorpGlory/grafana-multibar-graph-panel does not work on grafana 5.

**Comment by GarinSmith** [comment]
I agree that this feature would be very useful indeed.  The current alternatives do not seem very good.

**Comment by jbalooka** [comment]
+1

**Comment by aramhakobyan** [comment]
+1

**Comment by tammytankian** [comment]
+1 
Any plans for the near future?

**Comment by shahrzadpeyman** [comment]
+1

**Comment by saadsarfrazz** [comment]
+1

**Comment by rozetko** [comment]
Hey, @nthienan @kccheung
We've fixed a few bugs
Now [multibar-panel](https://github.com/CorpGlory/grafana-multibar-graph-panel) is working in Grafana 5+

**Comment by cby016** [comment]
+1 for this feature

**Comment by bmfmsd** [comment]
+1

**Comment by zuzya** [comment]
+1

**Comment by maxdraki** [comment]
+1

**Comment by Paul-Reed** [comment]
+1

**Comment by alexslo** [comment]
+

**Comment by alexslo** [comment]
+1

**Comment by mboogert** [comment]
+1

**Comment by arriflex** [comment]
Just piling on to support the concept of a multi-bar chart with side by side bars.

**Comment by AbyssCoreInc** [comment]
This would be essential feature. So +1 for this request

**Comment by CWempe** [comment]
This is how you `+1` for this feature request:

![image](https://user-images.githubusercontent.com/1270359/53647557-19ccc580-3c3e-11e9-8815-dfefa0596bca.png)

Just click the 👍 on the **first post**

**Comment by bingobook02** [comment]
+1

**Comment by bingobook02** [comment]
Would be a handy feature, the idea could be as simple as grouping by alias, for my use case grouping dots under the same alias.
![Screen Shot 2019-03-21 at 12 27 17](https://user-images.githubusercontent.com/22493427/54775920-e5c63e00-4c06-11e9-91f9-6540cfc0d576.png)

**Comment by ceinmart** [comment]
+1
For grafana 6

**Comment by Paul-Reed** [comment]
> +1
> For grafana 6

@ceinmart  Please add a thumbs up to the first post in the thread, and that will make 100 users requesting this enhancement.

**Comment by elkekou** [comment]
+1 for the feature
Sorry about my question, but i does not know how to install plugin " https://github.com/CorpGlory/grafana-multibar-graph-panel "

Is not available with "grafana-cli plugins" command, so i assume i must install it manually but how?

Thanks for help

**Comment by elkekou** [comment]
Hi, 
someone could help me to install the plugin  https://github.com/CorpGlory/grafana-multibar-graph-panel.
I searched with command "grafana-cli plugins" but without succes i guess it must be installed manually but does not know how to achieveit.

**Comment by RedSpid3r** [comment]
+1 please

**Comment by JensLederer** [comment]
@elkekou 
> Hi,
> someone could help me to install the plugin https://github.com/CorpGlory/grafana-multibar-graph-panel.
> I searched with command "grafana-cli plugins" but without succes i guess it must be installed manually but does not know how to achieveit.


Just download the archive from github (relaeses) and unpack it to Grafana's plugin folder. After a restart of Grafana the plugin is available.

**Comment by bahmanfarid** [comment]
Hi , I have problem with bar charts beside each other , all of my items gather in one bars as in thew picture , also i applied stack but no difference.
![bars beside](https://user-images.githubusercontent.com/51912313/59600658-1cc2c780-9102-11e9-9012-068253974a12.PNG)

**Comment by Optimusbumble** [comment]
+1

**Comment by LOADCRCHS** [comment]
+1111111

**Comment by lester289** [comment]
+1

**Comment by wqtty** [comment]
so many +1s....
+1

**Comment by Robosoc11** [comment]
Can anyone say A) **if** and B) **when**  the ### `Multibar Graph Panel` may be promotoed to become an official plugin or even better a native plugin that comes with an new release of grafana automatically?

**Comment by JensLederer** [comment]
> Can anyone say A) **if** and B) **when** the `Multibar Graph Panel` may be promotoed to become an official plugin or even better a native plugin that comes with an new release of grafana automatically?

I had a talk with a Grafana sales guy earlier this year. Asked him why they don't add this functionality to the native graph panel plugin. He told me that there are other things that have much higher priority, than adding this feature to the graph panel. 

I don't know if this statement has deprecated in between.

**Comment by Robosoc11** [comment]
> I had a talk with a Grafana sales guy earlier this year. Asked him why they don't add this functionality to the native graph panel plugin. He told me that there are other things that have much higher priority, than adding this feature to the graph panel.
> 
> I don't know if this statement has deprecated in between.

Thank's Jens

**Comment by hassanfarid** [comment]
I found a plugin to achieve the same results,
https://github.com/gipong/grafana-groupedbarchart-panel

source: https://community.grafana.com/t/monthly-grouped-bar-chart/27198

**Comment by truj** [comment]
+1

**Comment by denisRay** [comment]
+1

**Comment by adrianovieira** [comment]
> When having multiple series you must enable stacking when bars are enabled. There is no support for bars that are side by side (yet)

Hi!
Please, give us some great news!

We would like to create a panel similarly bellow ones:

- this:

![image](https://user-images.githubusercontent.com/5561794/109554626-39a85580-7ab3-11eb-9ac0-30a1b1e01ceb.png)

- and this:

![image](https://user-images.githubusercontent.com/5561794/109555288-1b8f2500-7ab4-11eb-8f87-15a46f981977.png)

**Comment by leeoniya** [comment]
> Please, give us some great news!

yessir! https://github.com/grafana/grafana/pull/30323

**Comment by adrianovieira** [comment]
> > Please, give us some great news!
> 
> yessir! #30323

Wow!
It looks amazing.

Looking forward to see it working by myself.

What is the "visualization name"? 
Can you point me a documentation that explain how to use it?

**Comment by leeoniya** [comment]
it's still alpha and called "Bar chart". you can try it by enabling alpha plugins: https://grafana.com/docs/grafana/latest/administration/configuration/#enable_alpha

there's still quite a bit of work to do: https://github.com/grafana/grafana/issues/30741

the plan is to finish and release it with v8 in May.

**Comment by maxdd** [comment]
I have built a table as such

![image](https://user-images.githubusercontent.com/6155973/111471165-e2e48200-8728-11eb-8ea6-a4ec971c9808.png)

but i keep getting "Bar charts requires a string field".
What am i missing?

**Comment by erichiller** [comment]
Multistat plugin can do grouped bar charts now it seems.
https://grafana.com/grafana/plugins/michaeldmoore-multistat-panel/

But I'm probably just going to wait until v8

**Comment by castillo92** [comment]
> Multistat plugin can do grouped bar charts now it seems.
> https://grafana.com/grafana/plugins/michaeldmoore-multistat-panel/
> 
> But I'm probably just going to wait until v8

That's would be included in 8 version of Grafana?
