### ISSUE TITLE
Login using phantomjs

### ISSUE THREAD

**Issue by withpitt** [grafana/grafana#8703]
Hello, 

I'm trying to login Grafana dashboard using phantomjs to snapshot and save the image on the server.
But I'm having trouble to submit the login data.. because there's no available submit tag id..

part of js script that I worte is like this :

document.getElementByName("username").value="user";
document.getElementByName("password").value="password";
document.getElementByName("**loginclickbutton**").click(); 

It seems that i have to getElementByName the loginclickbutton.. but it doesn't show the name nor the id of the button on its html source..  
So how could I write a js script that submits the login data?

Please include this information:
- What Grafana version are you using? the latest
- What datasource are you using? influxdb
- What OS are you running grafana on? Ubuntu

Thanks

**Comment by torkelo** [comment]
please use community site for questions.
