### ISSUE TITLE
Upgrade to 11-preview

### ISSUE THREAD

**Issue by waqarsky** [grafana/grafana#87059]
### What happened?

I am using helm to deploy into K8s. I upgraded the "image" parameter to the following: 
```
image:
  tag: "11.0.0-preview"
```

After the deployment I log into grafana and can see version 11 via the api/health path. 

However, i cannot see the new features. Such as edit mode in dashboards and metrics explorer. Screenshot below: 
I tried clearing cache of browser etc as well as changing to new browser
![image](https://github.com/grafana/grafana/assets/112862127/00da20e3-a3c4-4883-ae89-930b7de4b6b2)

### What did you expect to happen?

See metrics explore as described in the release notes

### Did this work before?

N/A

### How do we reproduce it?

As above

### Environment (with versions)?

Grafana: 11-preview
OS: Docker - alpine image
Browser: Chrome

### Grafana platform?

None

**Comment by tonypowa** [comment]
hi @waqarsky 
Thank you for creating this issue

This feature is currently in public preview.
https://grafana.com/docs/release-life-cycle/#public-preview

I guess this is the reason why you can't see it in the navigation bar. Have you requested access ?
