### ISSUE TITLE
[Bug] Heatmap x-axis time displayed incorrectly in local timezone

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#8706]
- What Grafana version are you using?
  4.3.2

- What datasource are you using?
  Prometheus

- What OS are you running grafana on?
  Linux

- What did you do?
  Use a heatmap panel. Configured dashboard in UTC (org setting). Opened dashboard

- What was the expected result?
  See all times in UTC.

- What happened instead?
  Values are shown in UTC, but the x-axis legend is in local timezone. (-2:00 Berlin)

![screenshot from 2017-06-26 11-48-59](https://user-images.githubusercontent.com/3432/27533983-c2065aac-5a65-11e7-9a3b-7dbf8a1990c5.png)

@mtanda

**Comment by torkelo** [comment]
are you using the built in heatmap panel? or the external histogram panel?

**Comment by grobie** [comment]
@torkelo The official heatmap plugin it seems. I updated the title, excuse the ambiguity.
