### ISSUE TITLE
[Bug] Log(10) scale minimum default

### ISSUE THREAD

**Issue by DorianPIERRE** [grafana/grafana#8707]
After upgrade Grafana version 4.3.2 on debian 8 witch influxdb datasource, I have a non 0 Y-min on a log(base 10) scale graph.

![image](https://user-images.githubusercontent.com/19405304/27534059-fb983614-5a65-11e7-8dd5-0c1bf5b64191.png)

My past version was ok with this Y-min and if I set set Y-min to 0, the graph no change ...
Is there something in the config file (I don't upgrade it) ?

Thanks a lot.
Dody

**Comment by torkelo** [comment]
0 is not a valid value on a logarithmic scale. You can specify 0.1 in y-min if you want ~0 included on y-axis, but that will be done automatically if you have values between 0 and 1,

**Comment by DorianPIERRE** [comment]
Ok but in my past version (before my this morning upgrade) it was 0 value ... sniff

**Comment by daniellee** [comment]
This is fixed in master and will be release in v4.4.0 next week. See https://github.com/grafana/grafana/commit/1b79e179707f2f6d220e295a1474fef3b9e8b36a

**Comment by DorianPIERRE** [comment]
Thanks a lot ;)

**Comment by DorianPIERRE** [comment]
After my update it is ok for zero min value but I lost point ;)
Is there a raison ?

![image](https://user-images.githubusercontent.com/19405304/28067342-30be75b0-6641-11e7-8ac9-a4e6dc67fa43.png)

**Comment by daniellee** [comment]
Looks like you have negative values which are not valid on the log scale. There is a feature request to allow negative values even though they are not valid but we haven't taken a decision on that yet.

**Comment by DorianPIERRE** [comment]
Thanks a lot for your quick answer but according to right side, values are not negative but 0 ;)

**Comment by daniellee** [comment]
The legend shows zeroes you mean? They show "current" values which seem to be 0 or null. But you can see that the values dip below zero further back in time.

 You can check the raw values returned from you data source by checking the network tab in the Chrome Dev Tools.

**Comment by DorianPIERRE** [comment]
thanks. I just check and I
found many null values but the search of ",0]" return 642 occurrences.
So ... but or not ?
