### ISSUE TITLE
UX: Ace text editor with syntax highlighting & auto complete 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8709]
Adding support for Ace editor with IntelliSense (in text editor autocomplete / dropdowns).

1) For use in MySQL query editor
2) For use in Prometheus query editor
3) For use in InfluxDB raw query editor mode.

**Comment by daniellee** [comment]
As a reference, there is a [data source plugin for Warp10](https://github.com/cityzendata/grafana-warp10) that uses Ace:

![image](https://user-images.githubusercontent.com/434655/28927154-1e545364-786a-11e7-9f77-0f4f250ba3bc.png)

**Comment by daniellee** [comment]
ref #8631

**Comment by alexanderzobnin** [comment]
@daniellee thanks, will take a look!
