### ISSUE TITLE
Legend: Show scrollable-ness of lists/tables somehow

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#87095]
There currently is no way (at least in Chromium-based browsers) to know if a Legend is scrollable with extra rows (vertically), or extra data (horizontally).

**Comment by staton-hyse11** [comment]
Discussed today with the squad that we can approach this by:
1. placing the legend in a container
2. implement the shadow gradient like left nav

**Comment by staton-hyse11** [comment]
Recommended solution has been provided to @Develer. Closing this issue as complete.
