### ISSUE TITLE
Grafana k8s deployment reliability consulting

### ISSUE THREAD

**Issue by frank-lam** [grafana/grafana#87101]
grafana uses docker to deploy to k8s and uses mysql to store meta information. Is there any side effect of multi-instance deployment, such as duplicate alarms?

**Environment**:
- Grafana version:7.5.17
- Data source type: mysql

**Comment by tonypowa** [comment]
Thank you for your question @frank-lam  However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on[ https://community.grafana.com/](https://community.grafana.com/)
