### ISSUE TITLE
Increase timeout when generating image

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#8710]
Grafana v4.3.2 (commit: ed4d170) with Prometheus 1.6.

Prometheus redid memory handling; since then, some queries take longer. This is good for stability etc, but this means that while interactive dashboards will happily wait for data to arrive, the static image rendering runs into timeouts.

Could you increase this timeout, or simply make this a knob we can turn?

**Comment by RichiH** [comment]
@daniellee @bergquist  is there an ETA for 5.0? This is hurting us badly.

**Comment by rpm91** [comment]
When I try to request a static image, I'll receive a 404 error, propably caused by a timeout.
I can reproduce this error, when I try to request data from a longer timeperiod, for example last month.
After a while, the dashboard  will generate the graph.
When I try to load the image via the „direct link rendered image“, from the share dialog of the graph, I get sometimes the 404 error instead of the rendered image.
A larger timeperiod will raise the chance to get a 404 error.

**Comment by bergquist** [comment]
You could add a `timeout` query parameter to configure the timeout. 

ex http://play.grafana.org/render/dashboard-solo/db/grafana-play-home?orgId=1&panelId=4&from=1498759990264&to=1498767190264&width=1000&height=500&tz=UTC%2B02%3A00&timeout=30000

https://github.com/grafana/grafana/blob/master/pkg/api/render.go#L21

**Comment by RichiH** [comment]
Seems it's good enough, but we still seem to be running into issues. I am on the road, but @rpm91 will do some more testing/debugging, and add info or open a new issue.

**Comment by daniellee** [comment]
Docs updated with rendering options for Direct Link Rendered Images (might take a few minutes before the changes are visible): http://docs.grafana.org/reference/sharing/#direct-link-rendered-image

**Comment by rpm91** [comment]
I used the timeout query parameter, but this didn´t fix the problem. 
If I set the timeout query Parameter = 1, I get an error page from Grafana:
  Server side error :(
  Failed to render to png

and if the timeout query Parameter = 12 or more seconds I get my previous error from Grafana.
A blank site with only this text:
  404 page not found

I noticed that this error occures after ~11 seconds from Grafana and ignores the timeout query parameter even if I set it to 12 or more seconds seconds.

**Comment by daniellee** [comment]
@rpm91 wondering if this has something to with this [code](https://github.com/grafana/grafana/blob/master/pkg/components/renderer/renderer.go#L120-L123). Will test some more tomorrow.

**Comment by RichiH** [comment]
@daniellee Any update on this? Can @rpm91 do any more debugging?

**Comment by daniellee** [comment]
Oops, wrong button. Didn't make time for this yet but it's on my todo list.

**Comment by RichiH** [comment]
@daniellee Reminder-poke :)

**Comment by RichiH** [comment]
One place where we found a hardcoded timeout: https://github.com/grafana/grafana/blob/master/pkg/components/renderer/renderer.go#L120-L123

**Comment by torkelo** [comment]
there is also this, https://github.com/grafana/grafana/blob/master/vendor/phantomjs/render.js#L62 

10 second timeout. What kind of query times are you working with? Out of curiosity what are you using the png rendering api for?

**Comment by RichiH** [comment]
I would say that we sometimes go up to 30s, maybe more. This depends on complexity and amount of data. If we took 600s for some, we would still take it as it's batch.

We dump Grafana exports into PDFs for customer SLA & service reports from Jenkins on a monthly basis. If you would come to PromCon, I could show you; as it stands, only @bergquist will see :p

**Comment by RichiH** [comment]
I went through the whole repo and couldn't find anything else that looks likely to affect this; I don't speak Go, though.

**Comment by giner** [comment]
The issue still exists in Grafana 4.5.1. If rendering takes more than about 3 seconds then Grafana returns 404. Adding `timeout` to the query doesn't help.
```
$ time curl -sw %{http_code} 'https://grafana.rpaas.net/render/dashboard-solo/db/shiny-showcase?orgId=2&theme=light&panelId=2&width=300&height=150&from=now-10d&to=now&timeout=100000' -o /dev/null
200
real	0m1.755s
user	0m0.012s
sys	0m0.000s

$ time curl -sw %{http_code} 'https://grafana.rpaas.net/render/dashboard-solo/db/shiny-showcase?orgId=2&theme=light&panelId=2&width=300&height=150&from=now-30d&to=now&timeout=100000' -o /dev/null
404
real	0m2.932s
user	0m0.004s
sys	0m0.008s
```
