### ISSUE TITLE
HTTP Alerting Provisioning API - forbidden for the editor

### ISSUE THREAD

**Issue by kwarunek** [grafana/grafana#87110]
### What happened?

I have a user with a role Editor in the org. User is able to manage alert rules/contact points folders without a problem through the frontend (Grafana UI). But if I would like to use that user credentials with Terraform provider (generally with the HTTP API) I get erros.

### What did you expect to happen?

I would expect that users could interact with Grafana via API as with frontend. The workaound is to set `Admin` role, or service tokens with `admin` role which I can't do since I don't want the team to manipulate datasourceusers etc.

### Did this work before?

no

### How do we reproduce it?

1.Create user with Editor role
2. Try to get ds via API - curl -u 'user:123456' http://localhost:3000/api/.... -H 'x-grafana-org-id: 2'
or manage alerts/folders

### Environment (with versions)?

Grafana: 10
OS: Linux
Browser: irrelevant

### Grafana platform?

Kubernetes

**Comment by kwarunek** [comment]
Related 86303

**Comment by tonypowa** [comment]
Hi @kwarunek 

I confirm this limitation exists and it is not mentioned in our docs .
https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-post-alert-rulespan-create-a-new-alert-rule-_routepostalertrule_

TEST: 
Tried to create an alert rule via `api/v1/provisioning/alert-rules`, and a 403 response was received 
However, in the UI logged as a editor I can manually create resources such as alert rules

**Comment by yuri-tceretian** [comment]
This is the expected behavior in Grafana 10. Since Grafana 11 the requirements are relaxed and now Editor can access the provisioning API. https://github.com/grafana/grafana/pull/77007 and https://github.com/grafana/grafana/pull/85022
