### ISSUE TITLE
Issues with wildcard metric and timeshift function

### ISSUE THREAD

**Issue by joelraburton** [grafana/grafana#8711]
I am trying to display a series of metrics with a timeshift applied. While I am able to display several metrics at once using a wildcard if I try to then apply the timeshift function it only displays the first metric in series.

![image](https://user-images.githubusercontent.com/28592411/27542022-e36d8f5e-5a7d-11e7-8b85-4e5de6867941.png)

**Comment by daniellee** [comment]
Just move your timeshift function one step to the left before the removeAboveValue function (you can do that by clicking on timeshift and using the left arrow that appears in the menu above it).
