### ISSUE TITLE
GrafanaUI: Add three icons "enter", "paragraph" and "document-layout-left"

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#87118]
**What is this feature?**:
Add three icons to our Grafana UI library from IconScout: `enter`, `paragraph` and `document-layout-left`
for more see [slack thread](https://raintank-corp.slack.com/archives/C05L39NC4AV/p1714128889954989)

**Where is/could it be used?**:
For Grafana LLM feature for title and description generation is being used:
<img width="551" alt="Screenshot 2024-04-30 at 11 56 58" src="https://github.com/grafana/grafana/assets/51436795/f4b3b1ff-9904-4b46-95bb-a75667ad558a">

**Special notes for your reviewer:**

Please check that:
- [ ]  It works as expected from a user's perspective.
- [ ]  If this is a pre-GA feature, it is behind a feature toggle.
- [ ]  The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

**Comment by jtheory** [comment]
It looks like this is already working (before my attempted fix); but [our latest storybook](https://developers.grafana.com/ui/latest/index.html) must not actually be showing latest code.

**Comment by natydej** [comment]
And do you know where is the latest version of our Storybook? Thanks for taking a look at this.

**Comment by jtheory** [comment]
The one I linked in my comment ^ is the one bookmarked in the saga-design-system Slack channel -- worth double-checking with them if 1) the bookmark is still right or 2) if they don't yet have a process to keep it updated

**Comment by natydej** [comment]
As Rob said above ^ This is already in our code but is not updated in our storybook.

**Comment by natydej** [comment]
cc @JoaoSilvaGrafana @Clarity-89 to double-check with you about this [storybook link](https://developers.grafana.com/ui/latest/index.html), is there a reason why this is not updated with the icons that we are talking about here?

**Comment by Clarity-89** [comment]
@natydej the `latest` storybook is updated only when a new Grafana version is released. To get a more up-to-date version of Storybook, you can use the [canary version](https://developers.grafana.com/ui/canary/index.html?path=/story/docs-overview-icon--icons-overview).

**Comment by natydej** [comment]
Ohh got it! thanks so much for the clarification :)
