### ISSUE TITLE
Add button to convert relative time range to absolute

### ISSUE THREAD

**Issue by jackwickham** [grafana/grafana#87129]
**Why is this needed**:

Often I will be using a relative range to explore some metrics or logs, but I then want to freeze that into an absolute time range to share a link (eg for discussion, to post in a ticket or pull request, etc) so that everyone gets a consistent view. Currently, that means I need to manually convert it to an absolute time range, or hope that there's a time series chart visible that I can drag to select the range on.

**What would you like to be added**:

A button in the time selector panel when using a relative time, to convert the current relative time into an absolute range.

**Who is this feature for?**

I think this would be useful for most people who are exploring metrics/logs and might need to share their results with others.

**Comment by gelicia** [comment]
@jackwickham Are you talking explore, dashboards, or both? For Explore, we recently added a better list of ways to create links that might help. 
![Screenshot 2024-07-10 at 8 51 27 AM](https://github.com/grafana/grafana/assets/1533128/5e291cad-6027-48f5-a580-9dcf78ee844a)

**Comment by jackwickham** [comment]
I'm interested in both explore and dashboards, but for explore that does look good.

**Comment by gelicia** [comment]
> I'm interested in both explore and dashboards, but for explore that does look good.

It's also worth noting that by typing `t` and then `a`, you will convert the relative time range to absolute in either place. We could add a button to do this as well, though :)

**Comment by jackwickham** [comment]
Ah that's great to know! A button would also be good to have to make that discoverable, but I will definitely be using that.

**Comment by evictorero** [comment]
Both Dashboards and Explore have an option to share a link, converting a relative range to an absolute time range. Can we close this feature request, or am I missing something?

**Comment by gelicia** [comment]
Sounds good to me - please feel free to re-open or create a new issue if there is a scenario not covered. Thank you!
