### ISSUE TITLE
Selecting XY Chart when adding visualisation breaks the app

### ISSUE THREAD

**Issue by Sergej-Vlasov** [grafana/grafana#87134]
to reproduce create new dashboard and add XY Chart

https://github.com/grafana/grafana/assets/37613182/99b2c8c5-f0f5-4b51-b807-56f27161521d

error in localhost
<img width="912" alt="Screenshot 2024-04-30 at 16 40 52" src="https://github.com/grafana/grafana/assets/37613182/fef58474-16d1-4a45-b5fa-043ef1e6783a">

**Comment by leeoniya** [comment]
out of curiosity, does it break when using `autoMigrateXYChartPanel` feature flag as well?

**Comment by Sergej-Vlasov** [comment]
> out of curiosity, does it break when using `autoMigrateXYChartPanel` feature flag as well?

@leeoniya with this FF it has a silent error

<img width="1512" alt="Screenshot 2024-04-30 at 17 10 57" src="https://github.com/grafana/grafana/assets/37613182/12701562-3b7f-4995-8f18-827367d4f10a">

**Comment by leeoniya** [comment]
progress :)

that FF is a pretty big rewrite of XY. we dont have precise error messages in there yet. most likely it's missing some expected fields in the frame. hopefully by end of this week :crossed_fingers:

**Comment by Sergej-Vlasov** [comment]
@leeoniya just double checking if you know whether this relates more to dashboards squad or dataviz squad or both?

**Comment by leeoniya** [comment]
i think it's a difference with scenes.

XYChart (without FF) uses a custom editor, which previously only received `series` DataFrames, but now receives `annotations` type frames. you can see the difference by putting breakpoints into AutoEditor and load a new dashboard on https://testymctestface.grafana-dev.net/ with and without `&scenes=false`. 

with `&scenes=false`:

<img width="563" alt="image" src="https://github.com/grafana/grafana/assets/43234/24999360-5462-4659-8ce8-6f9da332c4ff">

---

normal load (with scenes enabled):

<img width="656" alt="image" src="https://github.com/grafana/grafana/assets/43234/a00afc78-50c4-476f-beff-f34824553b49">
