### ISSUE TITLE
how can i use grafana with mysql5.1

### ISSUE THREAD

**Issue by toryzen** [grafana/grafana#8714]
mysql5.1 dose not support utf8mb4 , how can i use grafana with mysql5.1 ?

**Comment by daniellee** [comment]
The simple (but maybe not possible) answer is to upgrade MySQL to at least v5.5. MySQL v5.1 was released in 2008.

Also, make sure you have upgraded to 4.3.2 to get this fix: #8483

Otherwise, have a look at this issue for some workarounds: #8450
