### ISSUE TITLE
Show series on Legend but no on Graph

### ISSUE THREAD

**Issue by scotia70** [grafana/grafana#8715]
Hi,
is there a way to have the result of a query display ONLY on the legend?  I have a "max - min" query which tells me the area under the graph (total data for the displayed time range) but I don't want it plotted as a line.
If I use a series override and turn off the line, the line does disappear, but the scaling of the y-axis doesn't change.  I have values on both y-axes already so can't push it to y-axis 2.
Maybe having a y-axis 0 (not plotted) would solve that (so that I could override the y-axis to that).
Thanks,
Scott

Grafana 4.3.2.1 on FreeBSD

**Comment by daniellee** [comment]
Sorry, you seem to have tried most options. I don't have any better solutions.
