### ISSUE TITLE
Can't reset admin password

### ISSUE THREAD

**Issue by jtweaver** [grafana/grafana#87158]
### What happened?

Tried to reset admin password with this:

```
grafana cli admin reset-admin-password <password>
```

### What did you expect to happen?

The password to be reset

### Did this work before?

Not sure

### How do we reproduce it?

1. grafana cli admin reset-admin-password Test123!
2. Try to log in with `admin` and `Test123!`
3. Cry

### Environment (with versions)?

Grafana: 10.4.2
OS: docker
Browser: All

### Grafana platform?

Docker

**Comment by Wolf2789** [comment]
The same happened to me and my team.
It worked some time ago in one of previous builds.

The solution for now is to downgrade. We switched to `grafana/grafana:10.4.2`

**Comment by kalleep** [comment]
Hey, thanks for the report. I found that when using the cli to reset password we hash it twice. Will make a pr to fix this and backport the fix
