### ISSUE TITLE
Dashboard Scene: Read-Only dashboards don't work as expected

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#87169]
Dashboard "Read Only" is not working as expected since it allows users to change Permissions and General Tab. 

https://github.com/grafana/grafana/assets/239999/89a2e678-140d-4302-8c30-a954d782456b

In the old architecture, when a dashboard was read-only, a screen was shown to inform the user about the dashboard situation and it offered the option to make the dashboard editable. 

![image](https://github.com/grafana/grafana/assets/239999/0a1ab492-7ced-44fc-b06f-88e4b3adf900)

**Comment by meanmina** [comment]
Can we also add an e2e test to validate this workflow in the future?
