### ISSUE TITLE
How to change Y axis value to non-decimal?

### ISSUE THREAD

**Issue by roshanbade221** [grafana/grafana#8718]
![y-axis](https://user-images.githubusercontent.com/23521061/27582974-96201b60-5b52-11e7-9808-467519d9e3b8.png)

**Comment by daniellee** [comment]
The only way to control this in Grafana is to set a larger Y-Max (on the Axes tab). The scale is calculated automatically and by increasing Y-Max to maybe 15 or 20, then it would be non-decimal.

Ref #2759

**Comment by IvanBoyko** [comment]
When Unit is set to short, I would expect it to be clever enough not to show 2.5 or 7.5 ...

**Comment by torkelo** [comment]
@IvanBoyko how?

**Comment by IvanBoyko** [comment]
@torkelo , I have absolutely no idea.
I was leaving this feedback just from user perspective.
We are only starting to use Grafana, so I'm not aware of "how" it works inside.
Counting is always integer, and seeing values like 2.5 really confuses us.

**Comment by nemenemsrouge** [comment]
I think we could add an option for Y axis : "no decimal values"

if you have to few variations (for example all values are between 20 and 21) we could simply extrapolate a minimum count of points under and upper 20 (5 for example) for displaying an Y axes with only these values from 15 to 25 

What do you thing of it?
I don't know if I am really clear

**Comment by sshiddibhavi** [comment]
Keep Decimals column inside Axes tab as zero.

**Comment by mwmahlberg** [comment]
@sshiddibhavi Which does not help with the mouseover values.

**Comment by TASSDevon** [comment]
> 
> 
> @sshiddibhavi Which does not help with the mouseover values.

Little late, if you type -1 instead of 0 in the decimals field, it looks OK

**Comment by shravan-Quovantis** [comment]
In the field of Decimals, you can specify the value like -2, -1, 0, 1, 2

**Comment by mrvindu** [comment]
![image](https://user-images.githubusercontent.com/50344084/134498355-1a600f8e-fd46-483c-b748-a055c9515908.png)

**Comment by mrvindu** [comment]
![image](https://user-images.githubusercontent.com/50344084/134498479-88dc69af-7e40-4602-aefe-509bfff65d98.png)

**Comment by afgtid** [comment]
You can try with unit "locale format", that will works too

**Comment by ekragan** [comment]
Even after giving decimal as 0 , x-axis is still ploted repetedly

**Comment by genefever** [comment]
I also see that the y-axis values are still plotted repeatedly, despite giving decimal as 0. How can I remove the repeated y-axis integer values?

**Comment by leeoniya** [comment]
this was fixed 3 days ago in https://github.com/grafana/grafana/pull/54679 and should be part of 9.1.4 (released 10hrs ago)

**Comment by M4TY** [comment]
Sorry for bumping, but the way I was able to do it is to set a Value map with an empty unicode space character. 
![image](https://github.com/user-attachments/assets/d25d95a6-bcd3-4d46-a318-944b6e62945e)
