### ISSUE TITLE
Rendering with selected tags

### ISSUE THREAD

**Issue by pavlov-tony** [grafana/grafana#8720]
Hello,

I want to render graph with selected tags, for example to render graph with only tv-habbl-8r2-11 host(see pic.)
![server](https://user-images.githubusercontent.com/15091368/27587237-412aa220-5b4c-11e7-9fe6-ecfa34395306.png)
How to do so?
Thanks.

**Comment by torkelo** [comment]
Please use community site for questions, this we ask of you in the new issue template, ease read it the next time you create a github issue :)
