### ISSUE TITLE
[Bug] Table with time series aggregations does not work with Prometheus

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#8721]
What Grafana version are you using? master
What datasource are you using? prometheus (current prom/prometheus:latest Docker hub image)
What OS are you running grafana on? Docker Hub image grafana/grafana:master on Ubuntu Server 16.04
What did you do?

I am monitoring various web endpoints using Prometheus blackbox exporter. It generates metrics named `probe_success` with a value of 0 or 1 and `probe_duration_seconds` with values in seconds.

* I create a new dashboard and a new Table in it.
* I select the data source and enter the query `probe_duration_seconds`
* Under "Options" I select Table Transform: time series aggregations
* Under Columns I remove the default Avg and add Current.

What was the expected result?

I get a table with my web endpoints matched up with their current (latest) probe duration.

What happened instead?

"Time series aggregations" on the Options tab of the panel does not seem to have any effect. Indeed, when I close the panel details and re-open, it goes back to "Table". No aggregated values are ever displayed, even temporarily (not even the default Avg).

In browser console, I see:

```
boot.67c19987.js:52 TypeError: Cannot read property 'length' of undefined
    at a.isMsResolutionNeeded (boot.67c19987.js:29)
    at new a (boot.67c19987.js:29)
    at Object.transform (boot.67c19987.js:29)
    at f.c [as transformDataToTable] (boot.67c19987.js:29)
    at b.render (boot.67c19987.js:30)
    at a.removeColumn (boot.67c19987.js:29)
    at fn (eval at compile (boot.67c19987.js:1), <anonymous>:4:253)
    at e (boot.67c19987.js:54)
    at b.$eval (boot.67c19987.js:52)
    at b.$apply (boot.67c19987.js:52)
```

When I click the Refresh button in the corner, I see the following request:

```
GET http://omar:9090/api/v1/query_range?query=probe_duration_seconds&start=1498547124&end=1498568724&step=20 HTTP/1.1
Host: omar:9090
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: http://omar:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Referer: http://omar:3000/dashboard/new?orgId=1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,et;q=0.8


HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date
Content-Type: application/json
Date: Tue, 27 Jun 2017 13:05:23 GMT
Content-Length: 207603


```

Body omitted for brevity. Nothing surprising in the response to my eye (just standard blackbox probe_duration_seconds data points).

When I click Save Dashboard, I see the following submission (note the `timeseries_to_columns` even though I specified aggregation):

```
POST http://omar:3000/api/dashboards/db/ HTTP/1.1
Host: omar:3000
Connection: keep-alive
Content-Length: 1341
Pragma: no-cache
Cache-Control: no-cache
Origin: http://omar:3000
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Content-Type: application/json;charset=UTF-8
Accept: application/json, text/plain, */*
Referer: http://omar:3000/dashboard/new?panelId=1&fullscreen&edit&orgId=1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,et;q=0.8
Cookie: ASP.NET_SessionId=xxx; grafana_sess=xxx; grafana_user=admin; grafana_remember=xxx

{"dashboard":{"annotations":{"list":[]},"editMode":false,"editable":true,"gnetId":null,"graphTooltip":0,"hideControls":false,"id":null,"links":[],"rows":[{"collapse":false,"height":"250px","panels":[{"columns":[],"datasource":"Prometheus (medium-term)","fontSize":"100%","id":1,"pageSize":null,"scroll":true,"showHeader":true,"sort":{"col":0,"desc":true},"span":12,"styles":[{"alias":"Time","dateFormat":"YYYY-MM-DD HH:mm:ss","pattern":"Time","type":"date"},{"alias":"","colorMode":null,"colors":["rgba(245, 54, 54, 0.9)","rgba(237, 129, 40, 0.89)","rgba(50, 172, 45, 0.97)"],"decimals":2,"pattern":"/.*/","thresholds":[],"type":"number","unit":"short"}],"targets":[{"expr":"probe_duration_seconds","format":"table","intervalFactor":2,"metric":"probe_duration_seconds","refId":"A","step":20}],"title":"Panel Title","transform":"timeseries_to_columns","type":"table"}],"repeat":null,"repeatIteration":null,"repeatRowId":null,"showTitle":false,"title":"Dashboard Row","titleSize":"h6"}],"schemaVersion":14,"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"now-6h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"timezone":"browser","title":"New dashboard Copy","version":0},"overwrite":false,"message":""}
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 27 Jun 2017 13:08:27 GMT
Content-Length: 60

{"slug":"new-dashboard-copy","status":"success","version":1}
```

**Comment by daniellee** [comment]
Have you tried the Format as Table option? See here for an example: http://play.grafana.org/dashboard/db/1-promcon-dashboard?panelId=2&fullscreen&edit&orgId=1&tab=metrics

**Comment by torkelo** [comment]
If you use time series aggregation table transform option your metric query format needs to be set as time series

**Comment by sandersaares** [comment]
Aha, that solves it! However, I would not consider the issue closed - this is a usability issue that remains as there is no real indication of what is wrong or why I should touch that particular dropdown in such a scenario. Not to mention the JavaScript error and failure to actually have the selected option stick.

**Comment by alamaison** [comment]
This is definitely a bug.  I had a working Time series aggregations panel with Grafana 4.4.3 and it continued to work when I upgraded to Grafana 4.5.1 ... until I clicked Edit.  That trashed the panel and I could recover it.  Every time I selected 'Time series aggregations' it was reset to 'Table'

**Comment by torkelo** [comment]
Strange, we have no other reports like that, can't replicate it (unless query format option is set to table, then the o ly singlestat option that works is table, but that is no breaking change)

Can you show me you query?

**Comment by alamaison** [comment]
@torkelo It's been a few weeks so I can be sure, but I think it was just this: `up{kubernetes_name="kafka",kubernetes_namespace=~"$kubernetes_namespace"}`

**Comment by floyd871** [comment]
This bug still existst, even in your playground and in our used version v4.6.1
http://play.grafana.org/dashboard/db/1-promcon-dashboard?panelId=2&fullscreen&edit&orgId=1&tab=metrics

**Comment by torkelo** [comment]
Works fine for me

**Comment by torkelo** [comment]
You need to set Format As to Time Series if you want to use "Time series aggregation" table transform:
![image](https://user-images.githubusercontent.com/10999/33009795-3a90d8ea-cdd8-11e7-8484-43d2c6317ae9.png)

**Comment by mayt** [comment]
@floyd871 Did you go through similar steps as #9927 to produce the bug?

**Comment by redesyservicios** [comment]
same issue
