### ISSUE TITLE
[Bug] Bad schema for postgresql database 

### ISSUE THREAD

**Issue by QuentinDeSoete** [grafana/grafana#8723]
I'm using grafana version 4.3.2 with a graphite datasource and a postgresql backend.
I'm running my grafana on a Debian Jessie.

I wanted to transfer my backend from mysql to postgresql.
To do so I just used MySQL-to-PostgreSQL on windows, I exported only my data and not the schema.
I used grafana to create the schema by letting grafana connecting to a postgres with an empty database. Then I exported the schema and imported it in my production Postgres. Finally I imported my data.
But I got some issue I couldn't change my datasources and my alerts.
The error was that grafana tried to put boolean into integers.

So you need to change your schema on two tables like this I think:

CREATE TABLE alert (
    id integer NOT NULL,
    version integer NOT NULL,
    dashboard_id integer NOT NULL,
    panel_id integer NOT NULL,
    org_id integer NOT NULL,
    name text NOT NULL,
    message text NOT NULL,
    state character varying(765) NOT NULL,
    settings text NOT NULL,
    frequency integer NOT NULL,
    handler integer NOT NULL,
    severity text NOT NULL,
    silenced boolean,
    execution_error text NOT NULL,
    eval_data text,
    eval_date timestamp without time zone,
    new_state_date timestamp without time zone,
    state_changes boolean,
    created timestamp without time zone,
    updated timestamp without time zone
);

CREATE TABLE data_source (
    id integer NOT NULL,
    org_id integer NOT NULL,
    version integer NOT NULL,
    type text NOT NULL,
    name character varying(765) NOT NULL,
    access text NOT NULL,
    url text NOT NULL,
    password text,
    "user" text,
    database text,
    basic_auth boolean,
    basic_auth_user text,
    basic_auth_password text,
    is_default boolean,
    json_data text,
    created timestamp without time zone,
    updated timestamp without time zone,
    with_credentials boolean,
    secure_json_data text
);

**Comment by daniellee** [comment]
What changes did you make to the tables in your two create table statements?

Not sure the problem is with the Grafana schema. MySQL uses tinyint(1) for booleans (although sometimes BIT is used instead) and postgres has a boolean type. This means it is hard to convert because you don't know if tinyint(1) is a number or a boolean.

**Comment by QuentinDeSoete** [comment]
ok i checked again and I my schema wasn't the right one but when I used the right schema and imported my data I can't restart grafana.
I got this statement in grafana log : 

> msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: pq: Could not complete operation in a failed transaction\n"

**Comment by daniellee** [comment]
@QuentinDeSoete is this before you have imported the data from MySQL? Can you show more of the server log before the error statement, does it say which table migration failed?

**Comment by QuentinDeSoete** [comment]
Of course this the log in question :
> t=2017-06-27T19:16:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
> t=2017-06-27T19:16:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
> t=2017-06-27T19:16:37+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
> t=2017-06-27T19:16:37+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
> t=2017-06-27T19:16:37+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
> t=2017-06-27T19:16:37+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
> t=2017-06-27T19:16:37+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=postgres
> t=2017-06-27T19:16:37+0000 lvl=info msg="Starting DB migration" logger=migrator
> t=2017-06-27T19:16:38+0000 lvl=info msg="Executing migration" logger=migrator id="Update user table charset"
> t=2017-06-27T19:16:38+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: pq: Could not complete operation in a failed transaction\n"

**Comment by daniellee** [comment]
@QuentinDeSoete is this the first time you create the postgres db before you import the data from mysql?

**Comment by QuentinDeSoete** [comment]
This time was not the first time I created the db but since the first time I have this issue.

**Comment by daniellee** [comment]
@QuentinDeSoete can you describe the steps you took? (Trying to figure out if this is a bug in Grafana or not)

**Comment by QuentinDeSoete** [comment]
- I used MySQL-to-PostgreSQL on windows to convert my mysql db to a postgresql db
- I dumped my Postgres database data
- I created a grafana db on a postgresql 
- I restarted grafana to use postgresql instead of mysql
- I imported my data to this postgresql database
but I had some issues like duplicate keys 

- I deleted the db
- I created a grafana db on a postgresql 
- I imported grafana database schema to this postgresql databse
- I imported my data to this postgresql database
and it worked fine
but when I tried to restart my grafana I had the issue and grafana just didn't want to restart

**Comment by daniellee** [comment]
Did you happen to wipe the migration_log table? That would really mess up the migrations. On startup, Grafana will try to run all the migrations once to create the database. If you have deleted all the rows in the migration_log table then it will try to rerun all the migrations and create the tables again. This will result in an error obviously.

**Comment by QuentinDeSoete** [comment]
No I didn't tried to whip this table

**Comment by daniellee** [comment]
If you look in the migration_log table, does it contain anything? It should have around 130 rows.

**Comment by QuentinDeSoete** [comment]
I have 50 lines in my migration_log table.

**Comment by daniellee** [comment]
@QuentinDeSoete sounds wrong (unless you have multiple pages and that is only the first 50?) - on a clean database I had 132 rows. Row 14 is "Update user table charset" which is where it failed for you. Do you have that migration in your table?

**Comment by QuentinDeSoete** [comment]
ok I checked my table and it seems that I have a lot of data that are missing.
And you are right I don't have this line so this is where the problem come from.
Do you have an idea of how I can correct this bug ?

**Comment by daniellee** [comment]
1. Create a new database in postgres
2. Configure Grafana to run against the new database so that it runs all the migrations
3. Copy all the rows from the migration_log table into your existing database
4. Configure Grafana to run against your existing database.

**Comment by QuentinDeSoete** [comment]
Ok thanks a lot for all your answers
