### ISSUE TITLE
Tree view option for dash board

### ISSUE THREAD

**Issue by dpkkumar01** [grafana/grafana#8725]
I am using grafana for my KPI dashboards. I would like to view my dash board on tree view structure and i am taking the metrics from InfluxDB.

Kindly let me know the feasible options to achieve the below.
 
Example:

>KPI
       > Network KPI>Product>Location
       > Service KPI>Product>Location
       > Server KPI >Product>Location
           
               

Thanks in Advance.

**Comment by daniellee** [comment]
Can you explain more? Is this a feature request for a tree view panel?

**Comment by dpkkumar01** [comment]
Thanks for your response.
 
Currently i am displaying my dashboards titles using "Row Option" where i can define my dash boards under one Row title. I would like to define sub dash boards(Network KPI, Service KPI, Server KPI) under one main dash board(KPI) 


Refer the below current link which i am using  for your quick reference.

![image](https://user-images.githubusercontent.com/25525188/27635489-d64ffb06-5c24-11e7-9d3f-0f76a59ce317.png)



I am expecting the dash board list some like below,

If i expand the KPI dash board. I should see the sub KPI list (Network KPI, Service KPI, Server KPI)

![image](https://user-images.githubusercontent.com/25525188/27635338-2edcb080-5c24-11e7-828f-b1db833cc045.png)

Hope this will help you to understand my requirement.

**Comment by daniellee** [comment]
We are currently working on switching out the grid layout system (should be released in v5.0.0 after the summer). This will allow much more flexible layouts and the row system will be a legacy concept then. It will still be supported but the idea is that it won't be needed by most users.

Unfortunately, I don't think it will support a tree structure like this with collapsible rows initially so marking this as a feature request.

**Comment by lemon1112** [comment]
Please help to create this feature. Would be very useful.

**Comment by SharvariBhosale** [comment]
Hi,
Is this tree view feature supported in Grafana v6.5.1 ?

**Comment by gvnirmal** [comment]
We are also looking for a tree view plugin since a long time. We are looking for alternative tools that can provide this capability.

**Comment by cdalexndr** [comment]
Another use case:

Select url, count from http resource url, grouped by status code, grouped by http method.
Using a table is cumbersome because it shows all rows expanded resulting to a large table.
A tree view could allow to view only urls, then manually expand to view details (status codes, http methods).
