### ISSUE TITLE
[Bug] Weird "pause alert" behaviour

### ISSUE THREAD

**Issue by Deriul** [grafana/grafana#8726]
[Bug] Weird "pause alert" behaviour 

Hi there! We normally use Grafana 4.3.2 + InfluxDB + graphite to monitor storages. As far as we have most backups going at night, we don't want to receive a bunch of alerts caused by backup process. Thus I have added to crontab two simple strings to suspend alerts during nights: 
  
curl --http1.1 -X POST http://admin:***@localhost/api/admin/pause-all-alerts -H "Content-type: application/json" -d '{"paused": true}' at 18 o'clock 

curl --http1.1 -X POST http://admin:***@localhost/api/admin/pause-all-alerts -H "Content-type: application/json" -d '{"paused": false}' at 8 o'clock 

Now I get something unexpected at morning:
![1](https://user-images.githubusercontent.com/29748300/27626499-f676cd44-5bf0-11e7-8e10-33891074cff7.PNG)

Any ideas? Thanks in advance.

**Comment by daniellee** [comment]
Unfortunately, the alert pause all function is not proper silencing/muting and is not meant to be used this way. We will hopefully have proper silencing in the near future. See #5856

What is happening here is that when the alerting is turned back on then all the alerts send an ok notification.
