### ISSUE TITLE
Alerting: When updating Evaluation Group on Alert rule page, got error message: Failed to update namespace / group: Access denied

### ISSUE THREAD

**Issue by jianwu** [grafana/grafana#87282]
### What happened?

When I try to edit exiting Evaluation Group on alert rule edit page. When I click save, it's blocked with error message: `Failed to update namespace / group: Access denied`. 

![Screenshot 2024-05-02 at 6 00 38 PM](https://github.com/grafana/grafana/assets/31761/556bc995-c6f4-4a07-afb4-10bbe1b985a2)

### What did you expect to happen?

The Evaluation Group should be saved. 

### Did this work before?

Not tried before

### How do we reproduce it?

1. Open an alert to edit
2. Click edit icon near blow evaluation group dropdown.
3. Change the value in the evaluation group edit dialog
4. Click save

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:10.4.1
OS: Mac
Browser: Chrome

### Grafana platform?

Docker

**Comment by VitaliySynytskyi** [comment]
Hi, I have exactly the same issue. I found a solution for myself - creating a new Evaluation Group with the same name and setting a new evaluation interval.

**Comment by vigneshs-12** [comment]
@jianwu It is possible to edit the evaluation interval from 'Alert rules' page.

**Comment by tonypowa** [comment]
hi @jianwu 
thank you for creating this issue

Is the user you are logged in with an administrator?

**Comment by jianwu** [comment]
Yes, I tried login both as admin or not, the issue aways happens

**Comment by NEODjazz** [comment]
Same issue form Grafana v10.4.0 (03f502a94d)

**Comment by KaplanSarah** [comment]
This issue has been fixed and will be available in 10.4.4.

**Comment by StefanJakic** [comment]
Is there any other way to do it(Currently we are on 10.4.0)? through API or something like this? 
I'm asking since I have 100 alerts in one evulation group
