### ISSUE TITLE
Feature request : Grafana configuration option to block searches during panel edits

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#8729]
Please include this information:
- What Grafana version are you using? 4.2
- What datasource are you using? opentsdb
- What OS are you running grafana on? linux redhat

One of the things we have noticed that is problematic when having a huge collection of timeseries > 1 million is when we are editing a graph or any other panel it tries to do searches.   I know we can disable the search by click on the little show icon but this is not intuitive for our many users.  

To give some more context lets assume we want to graph cpu.idle for a small subset of machines but we have 20,000 machines. To do this we need to add a filter.  The problem is that as soon as I type in the metric, a search is made to try and graph 20,000 machine data.  If I want to edit the filter it can also kick off a search.

It would be preferable to have an option for grafana that says when editing a panel don't search until told to do so in edit more, or kick off the search once it is saved.

I realize that this is a change in workflow but it is problematic.

**Comment by torkelo** [comment]
Can you describe more? When is grafana searching OpenTSDB? I mean it looks for metric names and tag names using suggest api, but these api should be relatively quick,if not it's a problem in OpenTSDB

**Comment by torkelo** [comment]
Do you want to disable metric name and tag value completion?

**Comment by shalstea** [comment]
No we don't want to disable the auto-completion.  We are seeing queries actually run to get the timeseries from opentsdb.  Maybe this is a bug / issue with the opentsdb plugin?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
