### ISSUE TITLE
Export Dashboard with Data

### ISSUE THREAD

**Issue by kadaan** [grafana/grafana#873]
It would be really useful if whole dashboards (and single panels) would be exported in such a way that the Dashboard JSON, all data for the current time range, and all annotations could be exported to a single file so that it can be added to bugs in a bud tracking system, design docs, etc.  Without this, putting the link to the dashboard in a bug tracking system could result in different data when the dashboard is viewed again (due to the retention settings).

**Comment by torkelo** [comment]
implemented via snapshots :)

**Comment by torkelo** [comment]
introduced in Grafana 2.0
