### ISSUE TITLE
[Bug] Navigating from dashboard to Alert List doesn't change page title

### ISSUE THREAD

**Issue by drichelson** [grafana/grafana#8730]
Please include this information:
- What Grafana version are you using? 
Grafana v4.3.2 (commit: ed4d170)
- What datasource are you using?
Graphite 1.0.1
- What OS are you running grafana on?
ubuntu 16.04
- What did you do?
I was viewing a dashboard ("New Dasboard 1"), then navigated to the Alert List Page:
![image](https://user-images.githubusercontent.com/602409/27642746-b68eda76-5bed-11e7-8b74-94fe567188e7.png)

- What was the expected result?
The tab's title should indicate I'm on the Alerts List Page
- What happened instead?
The tab's title is still indicating the previous page ("New Dashboard 1")
![image](https://user-images.githubusercontent.com/602409/27642847-fb610a84-5bed-11e7-92af-f66ff05789bf.png)
I don't imagine a network dump is needed to address this, nor do I suspect it is browser-specific, but I'm on Chrome Mac `Version 58.0.3029.110 (64-bit)` on Mac OS 10.11.6
Thanks!

**Comment by kasperkarlsson** [comment]
I get the same result for all of the the following menu alternatives:
- Profile
- Playlists
- Snapshots
- Alert list
- Notification channels

Mozilla Firefox 53.0 on Windows 7.

**Comment by torkelo** [comment]
Thanks for reporting this, will close this issue as there already is an issue for this https://github.com/grafana/grafana/issues/3211
