### ISSUE TITLE
[Feature request] Checkbox to strictly enforce template value choices (i.e. disallow freeform values)

### ISSUE THREAD

**Issue by jcmcken** [grafana/grafana#8731]
- What Grafana version are you using? 4.3.2
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 7.3
- What did you do? 

Limit a Template variable using the Regex field when using Type "Query"

- What was the expected result?

Only the Regex-captured values would be allowed for selection in the dashboard drop-down menu.

- What happened instead?

Only the Regex-captured values are shown in the menu, but any value can be supplied via GET query args or typed into the textbox. In other words, what's shown in the drop-down menu for the template variable are not the only values available to the user.

The result of this is that certain values can't be templatized, and need to be hard-coded into the graph query to prevent a user with the Viewer role from inspecting metrics to which they should not have access.

A possible solution would be to provide another combo box to optionally strictly enforce the selected choices. Ideally, at least in my opinion, strict enforcement should be a default, but I don't know if that was the intention or not (it was my assumption before actually testing it, since the UI seems to indicate that only certain choices are allowed).

**Comment by daniellee** [comment]
> "to prevent a user with the Viewer role from inspecting metrics to which they should not have access."'

You know that you cannot really stop a Viewer from inspecting metrics using curl, postman or a Chrome plugin. They would just have to open the network tab in Chrome Dev Tools, copy the query and change the parameter to whatever they want.

That level of security has to be done on the database level (like how security is implemented in mysql). As you are using InfluxDB, you have some options: 

https://docs.influxdata.com/influxdb/v1.2/query_language/authentication_and_authorization/#authorization

**Comment by jcmcken** [comment]
OK, I see what you mean. And that is briefly mentioned [here](http://docs.grafana.org/guides/whats-new-in-v2/#user-organization-permissions), but no where else that I can see.

Perhaps then the documentation could use some expansion or clarification in this regard? Someone who's setting up Grafana may not look in the "What's New" section for a 2 year old version of Grafana. There should be a more prominent explanation of what roles do and do not afford you, and maybe examples/recipes.

If I submit a PR for that type of change, would you have a suggestion for where it should go? Or any comments on the suggestion in general?

**Comment by daniellee** [comment]
There is already an issue for the roles docs: #8546 and docs PR's are the best PR's :-)

You are totally correct about the security currently not being well documented.

Generally, we have no plans to add an extra security layer to Grafana for the data sources. That would be a huge amount of work and feels like it should be done at the database layer (like relational databases already do).
