### ISSUE TITLE
Datasource name 'default' from previous configs causes silent failure on data source

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#8732]
Previous versions of grafana were happy with a data source named 'default', even though the default status was slight confusing with this.
In Grafana 4.3, trying to use a data source of type graphite with name 'default' causes a silent failure, and the testing status never updates on the data source panel.

**Comment by daniellee** [comment]
Need more information. Works for me:

![image](https://user-images.githubusercontent.com/434655/27680655-c213ba7c-5cbc-11e7-8118-829973ca8eb2.png)

**Comment by torkelo** [comment]
closing for lack of update / details
