### ISSUE TITLE
[Bug] Template variables with Multi-value option 

### ISSUE THREAD

**Issue by fnord7** [grafana/grafana#8733]
- What Grafana version are you using?
   - grafana: 4.3.2
   - carbon/whisper/graphite-web: 0.9.16-1.el7

- What datasource are you using?
   - graphite 

- What OS are you running grafana on?
   - centos 7

- What did you do?
  I create some Templating variables:
![image](https://user-images.githubusercontent.com/29758283/27653199-a442d8bc-5c3e-11e7-8f96-29d6994af766.png)

 And at the server value i select the "Multi-value" option.

- What was the expected result?
![image](https://user-images.githubusercontent.com/29758283/27653599-db40d9c6-5c3f-11e7-8ea8-8b6354b5024b.png)

- What happened instead?
![image](https://user-images.githubusercontent.com/29758283/27653699-31d131d2-5c40-11e7-8348-ab0ad79756bb.png)

- If related to metric query / data viz:
   - api/datasources/proxy/7/metrics/find/?query=collectd.ENV.%7Besgrayclu101%7D.cpu*
    query:collectd.ENV.{esgrayclu101}.cpu*
   result:
    [ ]
 
   - When i add a "," to the query after esgrayclu101 than all works fine 
  api/datasources/proxy/7/metrics/find/?query=collectd.ENV.%7Besgrayclu101,%7D.cpu**
  result:
 [{"leaf": 0, "context": {}, "text": "cpu-0", "expandable": 1, "id": "collectd.ENV.{esgrayclu101,}.cpu-0", "allowChildren": 1}, {"leaf": 0, "context": {}, "text": "cpu-1", "expandable": 1, "id": "collectd.ENV.{esgrayclu101,}.cpu-1", "allowChildren": 1}]

This problem is only when i use the "multi-value" option and select only one server.
When i select more than one server or not use the "multi-value" option, than all works fine.

**Comment by torkelo** [comment]
Try upgrading Graphite, older versions can't handle glob expressions with a single item
