### ISSUE TITLE
[Bug] UnboundLocalError: local variable 'archive' referenced before assignment

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#8735]
Please include this information:
- What Grafana version are you using?

Grafana v 4.3.2-1

- What datasource are you using?

Graphite

- What OS are you running grafana on?

CentOS 7

- What did you do / expected result / actual result?

Hi,
since few days we have a problem with one of our charts on one of our grafana dashboards. The problem appear only in one particular chart, similar charts with other parameters are not impacted.

Here some print screen about the issue.

![headers](https://user-images.githubusercontent.com/2543381/27678307-0fc8be64-5cb5-11e7-880c-2af648f2eca9.png)

![preview](https://user-images.githubusercontent.com/2543381/27678188-97644402-5cb4-11e7-8bc8-468f8e764bc1.png)

![response](https://user-images.githubusercontent.com/2543381/27678328-2429c484-5cb5-11e7-9445-899c1888ce14.png)

The server have been rebooted (by our hoster) few days ago. I don't know if it's related but maybe it's a useful information. I search for corrupted whisper files, in case of, but didn't find them.

Have you an idea of where I can search to fix the problem?

Thanks.

**Comment by daniellee** [comment]
Love these Graphite error messages :stuck_out_tongue_winking_eye: 

I have no idea what the problem is. You didn't change the storage retention schema or any similar changes? Do other queries against this whisper file work?

You could try opening an issue in the [Graphite-web](https://github.com/graphite-project/graphite-web) repo or the [Whisper repo](https://github.com/graphite-project/whisper) repo.

**Comment by scraly** [comment]
Thx, I will open issue in graphite repo ;-).

**Comment by scraly** [comment]
Do you know how to know the graphite version installed with Grafana?
I've got a /opt/graphite/webapp/graphite_web-0.9.13-py2.7.egg-info directory but don't know if it's really the version used by grafana.
Thx.

**Comment by daniellee** [comment]
Grafana does not know what version of Graphite it is querying (a problem for us now that graphite 1.0 has been released). You can find the graphite-web version by going to graphite-web -> http://localhost:8080/version/ (substitute localhost for your graphite-web domain)
