### ISSUE TITLE
[Feature Request] Allow additional mapping for template variables and use them in queries

### ISSUE THREAD

**Issue by swaranga** [grafana/grafana#8736]
Currently most of my graphs are templatized on a $region parameter. However some of the graphs work at  "datacenter" parameter. Data centres are local to a region as such there is a single data center for a region. Hence I don't want to force my users to select both region as well as data center.

I would like to request the ability to specify additional mappings for template variables which I can use in my metrics queries. Currently I need this feature only for template variables of "Custom" type. For example:

Consider a variable region with values "US", "CA", "MX" etc. I would like to set up additional mapping like:

```
{
  "US": {
    "dataCentre": "America",
    "timezone": "PST",
    "internalStruct": {
      "internalKey": "internalValue"
    }
  },
  "CA": {
    "dataCentre": "Canada",
    "timezone": "EDT",
    "internalStruct": {
      "internalKey": "internalValue"
    }
  },
  ...
}
```

Finally when I am writing my queries, I could use ```$(templateMapping($region, "dataCentre"))``` or ```$(templateMapping($region, "timezone"))``` or even ```$(templateMapping($region, "internalStruct.internalKey"))``` which is a Json path expression.

**Comment by daniellee** [comment]
Does chaining template variables not work for you in this case? (Passing in the value of a template variable into the query for another template variable). Example - [dependent template variable in a Graphite dashboard](http://play.grafana.org/dashboard/db/templating-showcase?orgId=1&var-custom=server2&var-server=backend_01&var-server=backend_02&var-server=backend_03&var-server=backend_04&var-dependent=All&var-db=graphite&editview=templating).

**Comment by swaranga** [comment]
Probably not. Because the "datacentre" and "timezone" etc properties are effectively arbitrary and not something I can query from some source. They are static for each region but not queryable from some source.

**Comment by daniellee** [comment]
Related issues: #1032, #3478, #1988

**Comment by torkelo** [comment]
not sure this is going to be feasible without a significant increase in complexity. Think problems like this are better severed with a stronger and more powerful support for scripted dashboards.
