### ISSUE TITLE
Public dashboards + Prometheus datasource: Panel error when legacy datasource property is used in the panel

### ISSUE THREAD

**Issue by zsrv** [grafana/grafana#87369]
### What happened?

Some panels in a dashboard that I enabled as a public dashboard stopped returning data when viewed using the public dashboard link at some point (the dashboard is in Grafana Cloud, so maybe it was after a Grafana upgrade; I'm not sure). The dashboard data was returned as expected when viewed normally through Grafana.

The panels use the Prometheus datasource.

Here's the error that I can see in my web browser's development console for request `POST
	https://zsrv.grafana.net/api/public/dashboards/cec686be8fe24eef90bb508f2ddea64a/panels/1/query`:

```
{"results":{"A":{"error":"json: cannot unmarshal string into Go struct field QueryModel.datasource of type v0alpha1.DataSourceRef","errorSource":"","status":500}}}
```

### What did you expect to happen?

When the dashboard is viewed using the public dashboard link, I expect panel data to be returned as it is when I view the same dashboard in the normal way (from Grafana).

### Did this work before?

Yes, it worked up until maybe a few months ago. I had not changed anything in the dashboard, so I assume that something (Grafana instance, etc.) in my Grafana Cloud stack had been upgraded.

### How do we reproduce it?

I submitted Grafana Cloud ticket 136564, which was resolved after it was figured out that exporting the dashboard JSON with the "for sharing externally" option enabled and importing that JSON back into Grafana fixed the issue. After looking at the diffs between the original dashboard and the reimported dashboard, I saw that the only difference was that the way the datasources were being referred to changed. If you have access to that ticket, you can see the dashboard I originally had this issue with.

I searched for more information around this and came across https://github.com/grafana/grafana/pull/87224, which appears to be related.

I've attached two dashboard JSON exports: one that uses legacy datasource refs, and one that uses the new ones.

[Dashboard with legacy datasource properties-1714915438922.json](https://github.com/grafana/grafana/files/15213113/Dashboard.with.legacy.datasource.properties-1714915438922.json)
[Dashboard with new datasource properties-1714915457206.json](https://github.com/grafana/grafana/files/15213115/Dashboard.with.new.datasource.properties-1714915457206.json)

Reproduction steps:
1. Import the dashboard with **new** dashboard properties
1. Update the panel datasources to use valid Prometheus datasources and metrics
1. Enable the public dashboard feature
1. View the dashboard in Grafana and observe that data is being returned for both panels
1. View the dashboard using the public dashboard link and observe that data is being returned for both panels
1. Import the dashboard with **legacy** dashboard properties
1. Update the panel datasources to use valid Prometheus datasources and metrics
1. Enable the public dashboard feature
1. View the dashboard in Grafana and observe that data is being returned for both panels
1. View the dashboard using the public dashboard link and observe that errors are being returned for both panels

### Environment (with versions)?

Grafana: Grafana Cloud
OS: Linux (client)
Browser: Firefox 125.0.1

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus 5.0.0

**Comment by evictorero** [comment]
Hi @zsrv, thanks for reporting this. I couldn't reproduce it following your detailed steps and files shared. 
Can you confirm this is still an existent issue and update the steps to reproduce it in Cloud?

**Comment by zsrv** [comment]
Hi @evictorero, I just checked again in my Grafana Cloud instance and it appears this has since been fixed. I'll close this now, thank you
