### ISSUE TITLE
Alerting: Invalid syntax when creating Notification Policy on onprem Mimir Alertmanager

### ISSUE THREAD

**Issue by AndreZiviani** [grafana/grafana#87387]
### What happened?

Whenever I try to create a Notification Policy I get following error: `"error validating Alertmanager config: bad matcher format: \"label_x\"=\"value_x\"\n"`

This happens with any combination of label/value

### What did you expect to happen?

A Notification Policy should be created

### Did this work before?

Yes, I believe it was the [UTF-8 support](https://github.com/grafana/grafana/pull/81512) that broke it, but I'm not sure

### How do we reproduce it?

1. Install Mimir with Alertmanager API enabled (tested 2.11 and 2.12)
2. Add the Alertmanager as Datasource
3. Create a Notification Policy with any label/value

### Environment (with versions)?

Grafana: Tested on both `Grafana Cloud v11.1.0-69372 (51da96d94e)` and OSS image id `c8b91775d855`
OS: Grafana Cloud and Docker
Browser: Chrome 123

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Alertmanager

**Comment by AndreZiviani** [comment]
Updating Mimir to version 2.12 and enabling `utf8_strict_mode: true` (default is `false`) fixed the issue.

Would be nice to have this documented somewhere (maybe [here](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-notification-policy/)?)

**Comment by grobinson-grafana** [comment]
> Updating Mimir to version 2.12 and enabling `utf8_strict_mode: true` (default is `false`) fixed the issue.

Please just make sure to read the [documentation](https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#alertmanager) for `utf8-strict-mode` before enabling it. It will become the default in future versions of Mimir and the flag will be removed. The docs in the Mimir 2.12 release were out of date and contained incorrect information. The docs for Mimir 2.12 on [grafana.com](https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#alertmanager) have been fixed, and Mimir 2.13 should contain the correct docs.
