### ISSUE TITLE
Can we use grafana with external database source via JDBC i.e i am using a GPU based database MapD but  to visualize the data in time series .i tried it with kibana but we can only visualize it in tabular form for external data source .So is it possible in grafana ? 

### ISSUE THREAD

**Issue by anubhavj880** [grafana/grafana#8739]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by daniellee** [comment]
There is no direct support for JDBC or ODBC currently. You could get this data in time series form and into Grafana if you are prepared to do some programming.

The [simple json data source](https://github.com/grafana/simple-json-datasource) is a generic backend that could make JDBC/ODBC calls to MapD and then transform the data into rthe ight form for Grafana.

**Comment by ramarov** [comment]
I was in the impression that Grafana is matured visualization tool and very disappointed to know when it does not even have basic feature like connect to JDBC/ODBC as datasource.
If I am prepare to do some programming, do you have any reference where write some coding to feed in time series data to Grafana?

**Comment by marefr** [comment]
@ramarov please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by archenroot** [comment]
@ramarov - JDBC is standard spec, so I also expected to put my JDBC driver for either MapD or Apache Phoenix and it will work out of the box - sure some of JDBC standard functions are not implemented in both of them, but I would expect just limit of options at specific use case... this design of data source is crazy :-) or at least I would expect some Generic JDBC Data source

**Comment by archenroot** [comment]
@anubhavj880 - have you finished your data source for mapd(omni sci) gpu engine? If so, can you share?

**Comment by scottlepp** [comment]
@archenroot this is ODBC based
https://grafana.com/grafana/plugins/grafana-odbc-datasource/
