### ISSUE TITLE
[Change] allow_sign_up enabled by default

### ISSUE THREAD

**Issue by themainframe** [grafana/grafana#8743]
Should `allow_sign_up` be enabled by default? It seems like this goes against [_secure by default_](https://en.wikipedia.org/wiki/Secure_by_default) principles by risking giving the public access to potentially-sensitive dashboards.

**Comment by daniellee** [comment]
Yes, agree. This was not a big deal a year or two but the situation has changed with lots of grafana instances now outside of company firewalls. See https://github.com/grafana/grafana-docker/issues/85

**Comment by themainframe** [comment]
Glad you agree @daniellee - I've done a little research and a rather alarming number of publicly-accessible Grafana instances do indeed have sign-up enabled.
