### ISSUE TITLE
[BUG] Error Msg "No Group Mappings Defined"

### ISSUE THREAD

**Issue by ascott58** [grafana/grafana#8744]
Please include this information:
- What Grafana version are you using? **4.2**
- What datasource are you using? **Zabbix**
- What OS are you running grafana on? **Amazon Linux**

I am trying to get LDAP working with Grafana and I cannot figure out why  it keeps on generating an error **No groups defined**, as shown below. The logs I'm looking at are /var/log/grafana/grafana.log
![image](https://user-images.githubusercontent.com/26335953/27719232-5076854c-5d94-11e7-860f-71f40bac212c.png)

And clearly I have defined a group mapping, as shown below:
![image](https://user-images.githubusercontent.com/26335953/27719256-79f7505e-5d94-11e7-8d29-703a68036f60.png)

When I log in with this particular user I'm expecting it to log into the Organization ID'd with 7, but it keeps logging the user into Organization ID 1.

I'm not the most experienced at Active Directory, but all I'm trying to figure out at this stage is why it thinks there are no mappings defined when I HAVE defined one. Please note that users defined in our Active Directory CAN successfully log in. So the LDAP integration is working, but group mappings are not...

Any help would be appreciated, thanks.

**Comment by daniellee** [comment]
You are missing an s. `server.group_mappings` should be `servers.group_mappings`. Easy to miss!

Improving the LDAP integration is on our roadmap and we will be start work on that during the autumn so hopefully this sort of simple mistake will not be possible in the future.

**Comment by ascott58** [comment]
Thank you so much Daniellee, just silly mistakes on my end haha.
