### ISSUE TITLE
Grafana Cloudwatch - Possible to gran hostnames instead of InstanceID?

### ISSUE THREAD

**Issue by onedomjohn** [grafana/grafana#8746]
Any help appreciated here. I'd like to display hostnames from my AWS instances as well as / instead of the InstanceID's that are currently supplied with the 'Monitor Artist' dashboard. 

![image](https://user-images.githubusercontent.com/28752964/27726445-73f314a8-5d72-11e7-8e44-9e6b94f9a015.png)

Currently I can't see a way of doing this. I thought you'd be able to add it into the templating but can't seem to make it work. Can anyone help? Is it even possible?

Thanks

**Comment by torkelo** [comment]
Need to open the feature request with cloudwatch query api support :)

**Comment by onedomjohn** [comment]
Thanks @torkelo will do
