### ISSUE TITLE
[Feature Request]  Nothing fetched through the template expression, but None is  present.

### ISSUE THREAD

**Issue by genkimaru** [grafana/grafana#8747]
Please include this information:
- What Grafana version are you using?    **4.3.1**
- What datasource are you using?              **opentsdb**
- What OS are you running grafana on?           **windows 10**

when I config a expression in templating , the  request get  nothing  but the returned value show "None",
so the "None"  is present in the dropdown list. this  make nonsense.  
 **It will be better if the  returned data is none the dropdown list  show nothing rather than  the  "None"** 

 
![grafana_bug](https://user-images.githubusercontent.com/5584476/27727505-5752ebfe-5db1-11e7-9b61-cf235e8bc85f.PNG)

**Comment by daniellee** [comment]
This is not a popular request. It has been open for a few years with no comments and no thumbs up so closing the issue.
