### ISSUE TITLE
Alerting: condition precedence order is not expected

### ISSUE THREAD

**Issue by evan361425** [grafana/grafana#87483]
**Why is this needed**:

When computing multiple alert rules in Grafana, the current logic evaluates all rules before determining whether to fire an alert based on their "and/or" relationships. For example, given four rules with the relationship:

- rule1: result `true`, operator `N/A`(first rule don't need an operator)
- rule2: result `true`, operator `and`
- rule3: result `false`, operator `or`
- rule4: result `false`, operator `and`

the algorithm computes as follow (excerpt from [pkg/expr/classic/classic.go](https://github.com/grafana/grafana/blob/v11.0.0-preview/pkg/expr/classic/classic.go)):

```go
func (cmd *ConditionsCmd) exec() {
	for i, cond := range cmd.Conditions {
		isCondFiring, isCondNoData, condMatches, err := cmd.executeCond(ctx, t, cond, vars)
		if err != nil { return }

		if i == 0 { // first rule have no operator
			isFiring = isCondFiring
			isNoData = isCondNoData
		} else {
			isFiring = compareWithOperator(isFiring, isCondFiring, cond.Operator)
			isNoData = compareWithOperator(isNoData, isCondNoData, cond.Operator)
		}

		matches = append(matches, condMatches...)
	}
}

func compareWithOperator(b1, b2 bool, operator ConditionOperatorType) bool {
	if operator == "or" {
		return b1 || b2
	} else {
		return b1 && b2
	}
}
```

This computation yields a result of `false` because:

- `true AND true` equals to `true`
- `true OR false` equals to `true`
- `true AND false` equals to `false`

I expected the computation is same as the logical order: `true && true || false && false`, resulting in `true`.

```go
func True() bool {
	print("True, ")
	return true
}
func False() bool {
	print("False, ")
	return false
}

func main()  {
	print(True() && True() || False() && False()) // True, True, true
}
```

**What would you like to be added**:

To enhance the logic flow, we can implement a check to return `true` if we encounter `true` before an `or` operation:

```go
for i, cond := range cmd.Conditions {
	if cond.Operator == "or" && isFiring {
		break
	}
	// ...
}
```

Introducing a new operator, perhaps named `lowerPrecedenceOr`, could facilitate this enhancement without causing breaking changes.

**Who is this feature for?**

This feature is essential for users implementing Google's *The Site Reliability Workbook* [Multiple Burn Rate Alerts](https://sre.google/workbook/alerting-on-slos/#5-multiple-burn-rate-alerts).
In production, missing alerts due to the following scenario has highlighted the necessity for improvement:

- Alert structure:  `{short_term} OR {mid_term} OR {long_term}`
- Example scenario:
  - The `{short_term}` rule was triggered as `{5_minutes} AND {1_hour}`, resulting in `true AND true`.
  - However, the `{mid_term}` rule failed to trigger because of `{30_minutes} AND {6_hours}`, which evaluates to `true AND false`.
  - Similarly, the `{long_term}` rule also failed to trigger because of `{6_hours} AND {72_hours}`, resulting in `false AND false`.
  - Getting the `false` result and the alert didn't fired.
- After the improvement, the alert should be fired.

Improving this functionality is crucial for ensuring timely and accurate alerting in complex operational environments.

**Comment by tonypowa** [comment]
Hi @evan361425 

Thanks for creating this issue.
I see you have included code.  Why don't you open a [Pull request? ](https://github.com/grafana/grafana/pulls) .

**Comment by evan361425** [comment]
Hi @tonypowa 

Thanks for your response.
I would love to open a PR, but I want to confirm if this feature will be accepted or if there are any considerations that haven’t been taken into account.

**Comment by tonypowa** [comment]
I will move the issue to the team's board so you can get some feedback, and hopefully unblock a potential PR.

**Comment by yuri-tceretian** [comment]
@kylebrandt, this looks like a bug.

**Comment by kylebrandt** [comment]
@yuri-tceretian I think a feature request. This is because classic condition is for backwards compatibility, so don't want to change the behavior.

So the feature request I think is an operation added that does aggregation in SSE. That combined with math for the lotic would achieve the result.

**Comment by evan361425** [comment]
I have opened a PR to initiate the discussion, but there are still some pending tasks listed in the PR's TODO section.

**Comment by evan361425** [comment]
@yuri-tceretian it seems you have self-assign yourself. Please let me know if you need me to close mine. Thank you.

**Comment by yuri-tceretian** [comment]
Hi @evan361425! sorry, it slipped through. I was about to work on that but then priorities changed. Thanks for opening PR! I can review it!
