### ISSUE TITLE
DashboardScene: Panel menu crop with `hoverHeader` in panel view/edit/duplicate/add scenarios

### ISSUE THREAD

**Issue by Sergej-Vlasov** [grafana/grafana#87495]
in #85780 we did not account for several other scenarios where panel menu can be cropped when `hoverHeader` is true. These are scenarios that can crop panel menu:
- panel view
- panel edit
- add panel
- duplicate panel
- library panels

some of the hover panel menu crop examples (in the video panels with transparent background are library panels):

https://github.com/grafana/grafana/assets/37613182/e140ff9f-3fb7-4696-b803-69807d131a34

**Comment by torkelo** [comment]
@Sergej-Vlasov unable to see any cropping in these scenarios

**Comment by Sergej-Vlasov** [comment]
@torkelo added a video with examples in the description. Here is a [PR](https://github.com/grafana/grafana/pull/87543) that fixes all the cases when hover panel menu is cropped.
