### ISSUE TITLE
[Bug] Grafana assumes wrong role for authorization with AWS when running inside ECS task

### ISSUE THREAD

**Issue by zgolus** [grafana/grafana#8750]
- What Grafana version are you using?
4.3.2

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Docker in ECS

- What did you do?
Tried to authorize with the ECS task role by setting data source to CloudWatch, Auth Provider to ARN and Assume Role ARN to the ECS task role (`arn:aws:iam::***:role/***`)

- What was the expected result?
Correct authorization 

- What happened instead?
Wrong role was assumed - Grafana tries to use the EC2 instance role instead of the ECS task role:
```AccessDenied: User: arn:aws:sts::***:assumed-role/***/*** is not authorized to perform: cloudwatch:GetMetricStatistics```

**Comment by torkelo** [comment]
@mtanda any idea what could be wrong?

**Comment by mtanda** [comment]
Sorry, I don't use ECS. I don't have any idea.
This feature is added by https://github.com/grafana/grafana/pull/7892 .

@gomlgs Hi, do you have any idea about this?

**Comment by gomlgs** [comment]
Looks like I missed a case, will send a PR.
