### ISSUE TITLE
$interval in seconds from template

### ISSUE THREAD

**Issue by dnhodgson** [grafana/grafana#8751]
Same issue as [#3773](https://github.com/grafana/grafana/issues/3773), however the $__interval_ms variable is not as I was expecting. The $__interval_ms variable is related to the timerange, where what I was expecting was the template $interval*1000.

Below is the value for $__interval_ms for a 5min and 15min time range with a template interval of 1 minute set.

<img width="1351" alt="screen shot 2017-06-30 at 10 44 25 am" src="https://user-images.githubusercontent.com/3902065/27740872-531cd7c8-5d81-11e7-9b51-a80cc4870f90.png">

<img width="1038" alt="screen shot 2017-06-30 at 10 46 31 am" src="https://user-images.githubusercontent.com/3902065/27740893-6b0c8b08-5d81-11e7-8e9b-73691d213bcf.png">

**Comment by torkelo** [comment]
yes, the built $__interval_ms is related to panel interval which is by default related to how wide the panel is and the time range. 

Use your custom time interval in the Group by time interval option below your metric queries, this option sets the panel interval to use your custom interval variable. This way the $__interval_ms built in variable will match your custom variable value.

**Comment by efvhi** [comment]
> yes, the built $__interval_ms is related to panel interval which is by default related to how wide the panel is and the time range.
> 
> Use your custom time interval in the Group by time interval option below your metric queries, this option sets the panel interval to use your custom interval variable. This way the $__interval_ms built in variable will match your custom variable value.

the $__interval_ms is not matching the custom "interval" variable, it is still matching the built-in $__interval, how to solve this ? sir? thanks !
