### ISSUE TITLE
[Feature request] Preview dashboard version from history

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#8752]
The new dashboard history is really nice-- thanks!

It would be great to be able to see a previous dashboard without needing to 'restore' it first.  Right now i find myself polluting the history just to figure out which one looks right.

This would likely require adding version to the dashboard API
GET /api/dashboards/db/:slug?version=XXX

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
