### ISSUE TITLE
[Feature request] Generic JSON datasource

### ISSUE THREAD

**Issue by jifwin** [grafana/grafana#8753]
Currently, Grafana supports multiple data sources, including various time series databases. That means each data source needs a data source plugin, that is compliant with the API. How about creating a generic JSON data source? That would be useful to monitor applications that already expose some metrics in their format. There is already simple JSON data source, but it requires to follow defined JSON format. In order to use that plugin with any type of application, a JSON to Grafana-readable data transformation would be provided by the user in the UI in data source configuration. Such transformation is not very hard to implement. It would simply contain a reference to data. 

For example for this JSON

```
{
"some":"not",
"very":{
"important":{
"data":[
1,
2,
3,
4
]
}
}
}
```

The transformation would be

```
very->important->data
```

Both time series and single value could be supported. Please share your feedback on that idea.

**Comment by daniellee** [comment]
Sounds like a good idea to me! Would make integrations much easier.

**Comment by mtanda** [comment]
JMESPath support such transformation.
http://jmespath.org/

There are js library which support JMESPath.

**Comment by jifwin** [comment]
Looks promising!

**Comment by jsedy7** [comment]
+1 :+1:

**Comment by jifwin** [comment]
I've started to work on that plugin here: https://github.com/jifwin/grafana-generic-json-datasource . Contributions are welcomed :)

**Comment by wbrowne** [comment]
Closing as this plugin seems to cover what's needed https://grafana.com/grafana/plugins/marcusolsson-json-datasource/
