### ISSUE TITLE
[Feature request] Allow for defining a user for hipchat notifications

### ISSUE THREAD

**Issue by alexcreek** [grafana/grafana#8754]
version:  Grafana v4.3.2

I'm trying to setup hipchat notifications and there's no option to set a user for authenticating to hipchat.  The alert tests result in a 401.  My api key is valid and works in other use cases but for those I have to specify a user (jid).  FWIW I'm using an on-prem instance of hipchat.  Not sure what version but it supports the v2 api. 

```
Jun 30 20:11:52 xxx docker-compose[4763]: grafana_1  | t=2017-06-30T20:11:52+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=hipchat id=0 isDefault=false
Jun 30 20:11:52 xxx docker-compose[4763]: grafana_1  | t=2017-06-30T20:11:52+0000 lvl=info msg="Executing hipchat notification" logger=alerting.notifier.hipchat ruleId=0 notification=asdf
Jun 30 20:11:52 xxx docker-compose[4763]: grafana_1  | t=2017-06-30T20:11:52+0000 lvl=eror msg="Failed to send hipchat notification" logger=alerting.notifier.hipchat error="Webhook response status 401 Unauthorized" webhook=asdf
Jun 30 20:11:52 xxx docker-compose[4763]: grafana_1  | t=2017-06-30T20:11:52+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Webhook response status 401 Unauthorized"
Jun 30 20:11:52 xxx docker-compose[4763]: grafana_1  | t=2017-06-30T20:11:52+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=xxx time_ms=27 size=48
```

**Comment by daniellee** [comment]
There seem to be a lot of different token types in HipChat but reading through the docs, it does not mention needing a username to use any of them. Are you sure your API key/token is actually working?

What type of token did you generate? And does it work if you test it using the "Testing a token" step described [here](https://developer.atlassian.com/hipchat/guide/hipchat-rest-api).

**Comment by alexcreek** [comment]
I use the token with hubot's hipchat module which requires the jid to work.  The account and token was created by an admin so I don't know what kind of token it is.  In testing using the link you provided it doesn't work :(

I'm thinking the hubot module tries to interact with hipchat in a different way than simply sending notifications/messages. I'm gonna close this as it's not definitive that the problem is the lack of a username.

Thanks for the help.

**Comment by jordandev** [comment]
I'm getting the same 401 error with an api key I have.

Did you ever figure this out?

**Comment by alexcreek** [comment]
No I ditched it

**Comment by u-nik** [comment]
I solved it by creating a new custom integration for the room the notifications should be sent to. 

As a result you get an url like `https://example.hipchat.com/v2/room/THE-ROOM-ID/notification?auth_token=THE-API-KEY` where you can take the room id and api key from.

This credentials will work with grafana.
