### ISSUE TITLE
[Security] Grafana v10.4.2 (22809dea50) x Postgresql: Why does Grafana query the pg_authid system catalog?

### ISSUE THREAD

**Issue by 3BK** [grafana/grafana#87551]
### What happened?

Why does Grafana query the pg_authid system catalog?

This catalog is not publicly readable by design because it contains passwords.

Grafana sent this to PostgreSQL: 

`SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnlimit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_authid') as rolcomment, rolname = current_user AS is_current_user FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 2`

By design, Grafana should have sent this to PostgreSQL:

`SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnlimit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_roles') as rolcomment, rolname = current_user AS is_current_user FROM pg_roles WHERE rolname !~ '^pg_' ORDER BY 2`

### What did you expect to happen?

I expected Graphana to query [pg_roles](https://www.postgresql.org/docs/current/view-pg-roles.html) instead of [pg_authid](https://www.postgresql.org/docs/current/catalog-pg-authid.html) .

### Did this work before?

Don't know.

### How do we reproduce it?

1.  Spin up grafana latest + postgresql latest 
2.  Connect Grafana to postgresql
3.  Boom

### Is the bug inside a dashboard panel?

The bug is in tsdb.postgresql

### Environment (with versions)?

Grafana: Grafana v10.4.2 (22809dea50) 
OS:         *NIX
Browser:  Chrome (latest)
Postgresql: 16.2

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

tsdb.postgresql
```[tasklist]
### Tasks
```

**Comment by 3BK** [comment]
What's even more interesting is that the Grafana repository doesn't appear to contain any obvious references to pg_authid .

**Comment by 3BK** [comment]
@tonypowa Is this within in your purview?

**Comment by 3BK** [comment]
Adding @yesoreyeram and @gabor as a second set of eyes.

**Comment by gabor** [comment]
hi @3BK , i cannot reproduce this with the postgres datasource. i tried with the commit you mentioned, and no such query was sent to the database by the datasource plugin.

are you using the postgres datasource, or are you using postgres as the database that grafana uses to run( i mean the https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#database setting)?

**Comment by 3BK** [comment]
Background
I set up postgresql as a datasource on a system at work but was unable get grafana to connect.

Investigation
I read all applicable internet solutions and related issue notes.
I read all the subject matter applicable git code.
I spun up a test bed and executed all high probability mutations, perms,  and combs on the seqeunce of events and configuration for connecting grafana to postgresql.   Same barriers and errors.

Testbed activities
After several debugging sessions, I found evidence that grafana connection attempt (using the read only account) triggered attempts to query the privileged catalog.  Hence the case / issue.

Last night
Suddenly the same high probability of success sequences and configurations which formerly failed or triggered the security issue worked -without any findings.  Nothing else had changed aside from one maybe two OS patches.  As an aside, I have been using a paswword manager, etc.  (It almost seemed like some underlying component had drifted/shifted on the test bed.  )

Next steps
I will retest the same sequences and config at work and advise if i can correlate / reproduce / narrow down or eliminate the security warning / finding.

________________________________

**Comment by 3BK** [comment]
Hi Gabor.
The issue can be cancelled.  The pg_authid is no longer being queried when the credentials are valid.

**Comment by 3BK** [comment]
Thanks!

**Comment by 3BK** [comment]
Please advise if you need any further info to close the case.

**Comment by 3BK** [comment]
Np.  Thanks Gabor.
All the best.
________________________________
