### ISSUE TITLE
[Feat Req] Mysql Datasource & Support for multiple statements

### ISSUE THREAD

**Issue by rambo45** [grafana/grafana#8755]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 
 Grafana v4.3.2 (commit: ed4d170)

- What datasource are you using?
MySQL
- What OS are you running grafana on?
RHEL 6
- What did you do?
Query:
SET @id= (select c.objid from xxxx.yyy c where c.name = $Cluster);
SET @q=( concat(
'SELECT round(f.time/1000) as \'time_sec\', \'UserReads\' as \'metric\',f.userReads as \'Value\' FROM ', 
concat('aaa.ppp_',@id,' f ') 
));
prepare stmt from @q;
execute stmt;

- What was the expected result?
Returns a table from MySQL

- What happened instead?
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @q=( concat(
'SELECT round(f.time/1000) as \'time_sec\', \'UserReads\' as \'' at line 2

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
It works fine from MySQL client but Grafana seems to have issue, tried removing '\' but didnt help. Any help is greatly appreciated

**Comment by daniellee** [comment]
I don't see this as a bug. The MySQL data source supports single queries. Is it possible to do this in a MySQL view instead and then just execute a SELECT from Grafana? Or rework it to be a simple query instead?

Marking this as a feature request to support prepared statements.

Also as a sidenote, are you sure about the syntax? Your query above does not work for me in MySQL Workbench. This part looks wrong:

```sql
'SELECT round(f.time/1000) as 'time_sec', 'UserReads' as 'metric',f.userReads as 'Value' FROM '
```

Think you either need to do some escaping or remove the single quotes:

```sql
'SELECT round(f.time/1000) as time_sec, UserReads as metric,f.userReads as Value FROM '
```

**Comment by Caffe1neAdd1ct** [comment]
We use a call to a stored procedure to generate a calendar table on the fly, this allows further queries to join onto the calendar giving a value (even if it's zero) for the entire time span.

https://github.com/gabfl/mysql_generate_series

```
CALL generate_series_date_day_base(DATE_FORMAT($__timeFrom(), '%Y-%m-%d'), DATE_FORMAT($__timeTo(), '%Y-%m-%d'), 1);
```

If you are using a **direct** connection to MySQL you can put this call to the stored procedure in Query Box A and the next queries are all run inside the same connection, meaning the tmp tables created will be available (and i presume set variables etc).

However the cavity for this is alerts run one query in one connection, meaning I had to use a separate really messy query to generate a time series to join onto which required a table with >= the number of rows in the needed time series (for alerts only).

Messy query example:
```
SELECT DATE(DATE_ADD(X, 
INTERVAL @i:=@i+1 DAY) ) AS datesSeries
FROM yourtable, (SELECT @i:=0) r
where @i < DATEDIFF(now(), date Y) 
;
```

This could be solved by being able to submit two statements inside one connection!

While developing locally I started with a local direct connection, hence the finding above. However when we pointed the local copy of Grafana to the live data through https://github.com/sysown/proxysql/ I discovered something interesting.

proxysql allowed multiple statements to be submitted in the same query box without the syntax erroring of the direct connection :grinning: This allowed the alerting queries to generate time series tmp tables and give full series back for correct alerting data, also letting us use the same query box for alerts and the chart data.

Hope this helps :+1:

**Comment by hiranchaudhuri1** [comment]
This is a messy combination of issues. First I want Grafana to take care of my quite basic problem but it does not (https://github.com/grafana/grafana/issues/8259#issuecomment-722990863), then I try to pass the string manipulation to MariaDB (https://stackoverflow.com/a/64714297/4222206) which also does not work.
It seems Grafana is not as veratile as I hoped it to be.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
