### ISSUE TITLE
[Feature request] - Cursor option for tooltip to show same time yesterday or the day before

### ISSUE THREAD

**Issue by nmat** [grafana/grafana#8757]
It would be nice if the cursor tooltip could show the result of the same time yesterday and so on.

For example if you are checking a metric of how many users where in on a specific time. Having the cursor show the information of the same time yesterday and so on could help to see what the diff is between the 2 times.

Does that make sense?

**Comment by daniellee** [comment]
This sounds very similar to the time shifting functionality that is already built into Grafana or is available at the query level for some time series databases (like the timeshift function in Graphite). Wouldn't a trend line showing yesterday's data be a better option? 

See the new dashed lines series override option to make a pretty trend line:

- see example of dashed lines in this [blog post](https://grafana.com/blog/2017/05/23/grafana-4.3-release/) (Dashed Lines in Graph Panel section)
- [docs](http://docs.grafana.org/features/panels/graph/#series-specific-overrides)

**Comment by nmat** [comment]
That would work if the graph is big enough and you only want to show the trend from yesterday.

The big problem with having the tooltip itself is how it would calculate what you want compare to. 

For example if you show 30 days graphs and you want same day last month at the same time. How would the tooltip calculate that? 

Or in a way be able to Enable a compare in a graph in a view where you would say: "Compare _this_ time on _this date_ with _that time_ on _another date_" I am going to look at those dashes to see if I can get some sort of workable diff.....but not sure it really fills the idea. :/

**Comment by torkelo** [comment]
closing for lack of interest and how unlikely this is to be implemented, this can easily be done already with time series databases like graphite that supports time shift:
example: http://play.grafana.org/dashboard/db/grafana-play-home?panelId=3&fullscreen&orgId=1
