### ISSUE TITLE
[Revert]: Graph panel histogram breaking change

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8761]
Revert value option from histogram feature. 

This fix to histogram added a new feature (and a breaking change) that needs a feature request and a description for why it is needed etc :) 
https://github.com/grafana/grafana/pull/8727

**Comment by alexanderzobnin** [comment]
The new value is needed because histogram is a probability density function for given series of points. And I think people expect that it will use percents (0-1 usually) as values for Y axis. And if we use percents, people can normalize values by setting Y max to 1. With only count option, they can't do that. What do you think?

**Comment by alexanderzobnin** [comment]
Actually, when we use a histogram, we don't want to see how many points are in the particular value interval. We want to see which part of the set of values are in the interval.

**Comment by alexanderzobnin** [comment]
See #8628 : 
> What was the expected result?
To get an histogram with the x axis corresponding to the buckets corresponding the y axis time series.
**To get y axis in the histogram view that can be show percentage of counts.**

**Comment by torkelo** [comment]
> we don't want to see how many points are in the particular value interval.  

That is exactly what we want, and is the definition of a histogram. 

Percentage of count is something else, anyway please let 8628 be a feature request for that and let's see how big the demand is :)

**Comment by torkelo** [comment]
I cloud be wrong and people prefer normalized view, but I think having counts a lot easier to understand, normalized view is tricky as we also need to know sample size to grasp how significant the distribution is, the percentage by themselves can be very misleading

**Comment by alexanderzobnin** [comment]
Ok, seems, it's a topic for discuss. I can revert changes, leave only fix, open issue and PR for new feature.

**Comment by daniellee** [comment]
Reverted and cherry picked two commits.
