### ISSUE TITLE
[Bug] Numerical sorting of template values breaks on null/empty value

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#8762]
Grafana v4.3.2 (commit: ed4d170) with Prometheus

Sorting template values returned from Prometheus labels which are empty leads to the error:

````
Templating
Template variables could not be initialized: Cannot read property 'match' of undefined
````

Sorting Alphabetically works.

This can break existing dashboards in opaque and hard-to-debug ways.

If this is touched, maybe https://github.com/grafana/grafana/issues/7307 can be revisited as well.

**Comment by RichiH** [comment]
PS: I thought I had reported this in the past, but could not find the issue.

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/issues/7382

**Comment by RichiH** [comment]
So I did report this.

````
richih@Mac-rih (git)-[master] ~git/grafana % git tag --contains a747d333730c2e79319b9234c6e4bb87458fe94a
v4.2.0
v4.2.0-beta1
v4.3.0
v4.3.0-beta1
v4.3.1
v4.3.2
richih@Mac-rih (git)-[master] ~git/grafana % 
````

The goggles, they do nothing :(

**Comment by torkelo** [comment]
What does empty mean in this case? Can you show the response from prometheus?

**Comment by hugohaggmark** [comment]
This is partially still in Grafana. I can repro this error for both Numercial sorting in Grafana 7.3.1 but none of the other sorting options:

![image](https://user-images.githubusercontent.com/562238/98644843-62081a80-2331-11eb-9ca9-a4ed697dc101.png)
![image](https://user-images.githubusercontent.com/562238/98644874-6d5b4600-2331-11eb-9787-249ff15c726d.png)
