### ISSUE TITLE
[Feature Request] - cloudwatch query api support

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#8763]
I'd like to be able to pull the machine names of AWS ec2 instances back to Grafana instead of just instanceid's. Is this possible please?

**Comment by nmat** [comment]
I think the only way is to get information based on tags. AFAIK that is what the query for aws supports at the moment. I can be wrong though.

**Comment by mtanda** [comment]
Not sure what "machine names" is, but you can get arbitrary attribute by using `ec2_instance_attribute()`.
https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/cloudwatch.md

**Comment by sunker** [comment]
As @mtanda pointed out, this is possible to do using the ec2_instance_attribute() template
