### ISSUE TITLE
Can't assign LDAP user to organization -> local  [Bug]

### ISSUE THREAD

**Issue by bastianvs** [grafana/grafana#8764]
I am using graffana 4.3.2 . I know Orgs are mapped to ldap groups. I only need ldap for login purpose. Is there a way to map orgs locally for ldap users ? Can we make it work somehow ?

This the Followup to https://github.com/grafana/grafana/issues/5656.

**Comment by daniellee** [comment]
The sync between ldap groups and an organization is not enabled per default. You would have to enable sync, see [LDAP to Grafana Org Role Sync](http://docs.grafana.org/installation/ldap/#ldap-to-grafana-org-role-sync).

The default is to create a user in a organization and then not sync it with LDAP. 

Is that what you want? Or am I not understanding your question?

**Comment by bastianvs** [comment]
It worked, thanks

**Comment by bastianvs** [comment]
commeneted
#[[servers.group_mappings]]
