### ISSUE TITLE
Do Grafana has a support for Elasticsearch 6.0.0 alpha-2

### ISSUE THREAD

**Issue by honeygidwani** [grafana/grafana#8765]
I am trying new elasticsearch version 6.0.0 alpha-2. Do grafana provides the support for this version of elasticsearch. Do we able to query in grafana using elasticsearch as data source?

**Comment by daniellee** [comment]
We have not tested yet but I think it should work. From the [release blog post](https://www.elastic.co/blog/elasticsearch-6-0-0-alpha1-released):

> Elasticsearch 6.0.0-alpha1 is a departure from our previous major version upgrades. Elasticsearch 1, 2, and 5 were huge releases containing many new features and changes, and it required significant effort to upgrade between major versions. In Elasticsearch 6, we are trying to make this process much, much easier.

> Throughout the 5.x series, we have added new features and breaking changes to the master (6.0) branch, then we have added backwards compatibility and backported these changes to 5.x minor versions. This means that we have been able to get more improvements into the hands of our users earlier, and that the differences between 6.0 and 5.x are smaller than in previous major versions.

If you find anything that breaks, please let us know.

**Comment by beckjim** [comment]
Hello,
currently running Grafana 4.5.0 against ES 6.0.0-rc1. No issues so far that I'm aware of.
my 2cts ...

**Comment by maozi07** [comment]
Hello,
I'm using Grafana 4.6.2 with Elasticsearch6.0. When I want to get a server list using `Templating > Variables > query` , I wrote like this：
`{"find": "terms", "field":"beat.name"}`
but there is an error `Template variables could not be initialized: Elasticsearch error: No search type for [count]`, and using Elasticsearch5.x it's OK

**Comment by daniellee** [comment]
@maozi07 

> Don't select the ES version in datasorce the problem happend, Select 5.x it's correct, but 2.x the whole dashboard fail

Do you mean it works if you select 5.x and have Elasticsearch 6.0?

**Comment by maozi07** [comment]
Yes, select `empty` it doesn't work ,select 2.x the whole dashboard failed

**Comment by daniellee** [comment]
@maozi07 so then it works and I can close this issue?

**Comment by maozi07** [comment]
@daniellee Thanks,I think you can

**Comment by wolfohyeah** [comment]
@maozi07 @daniellee Hi, I have the same problem with Elasticsearch 6.2.4 and Grafana 5.1.3.  When I fill the query for variables as` {"find":"terms","field":"cluster"}` ,  no error returns but the` Preview of values` is `None`.  I try to select different version in the datasource setup but nothing changed. Btw, I can see the series without templating but I really want the templating fuction.
I use Grafana4.0.2 for more than one year but today when add ES as datasource , the templating return `Template variables could not be initialized:undefined`. Then I install Grafana5.1.3 and no error returns but the variables value is None.

**Comment by marefr** [comment]
@wolfohyeah please include your mapping of your index and the details of the http request/response to elastic when the {"find":"terms","field":"cluster"} query is executed (use chrome dev tools network tab for this). The url in question should end with /_mapping

**Comment by daniellee** [comment]
@wolfohyeah can you open a new issue describing your issue. I tested on ES 6 and template variables seemed to work for me.
