### ISSUE TITLE
Error importing dashboard with template with regex

### ISSUE THREAD

**Issue by gianluca-sabena** [grafana/grafana#8767]
Grafana version: 4.3.1.1

Export a dashboard with a template and a regex:

```
      "templating":{  
         "list":[  
            {  
               "allValue":null,
               "current":{  
                  "text":"test",
                  "value":"test"
               },
               "datasource":"Prometheus",
               "hide":0,
               "includeAll":false,
               "label":"ENV",
               "multi":false,
               "name":"ENV",
               "options":[  

               ],
               "query":"label_values(up,app)",
               "refresh":2,
               "regex":"\\/tag1\\/([^\\/]+)\\/tag2",
               "sort":0,
               "tagValuesQuery":"",
               "tags":[  

               ],
               "tagsQuery":"",
               "type":"query",
               "useTags":false
            }
         ]
      },
```

If I post this json to `/api/dashboards/db` I get a dashboard with wrong template regex.

The regex imported is `/tag1/([^/]+)/tag2` but this is wrong because one back slash has been removed. I expected a regex with this value `\/tag1\/([^\/]+)\/tag2`

The same dashboard json works fine if imported as a file dashboard.

**Comment by gianluca-sabena** [comment]
Api import works correctly if I use a full form regex  `/tag1/([^/]+)/tag2/` (note slashes at beginning and end)

A strange behavior is that if I use a regex in this form `\\/tag1\\/([^\\/]+)\\/tag2` (no slash at the end) it works if imported from file system but not form API.

This issue can probably be closed.

**Comment by torkelo** [comment]
Did you properly json escape the string?
