### ISSUE TITLE
External Auth Improvements (Hosted Grafana + more)

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8768]
We discussed this in NYC with the team during our most recent summit, and want to start making incremental improvements to how we handle users that are managed by external auth.

With that, I'd suggest we focus on optimizing the Grafana.com users for Hosted Grafana as the first set of improvements.

### Summary
Users of Hosted Grafana are lost when adding new users to their instance. Core Grafana needs improvements to know that auth is being handled by an external provider, restrict actions like "Add User" and help guide the admin to the correct path. 

### Current: Most common experience
Most commonly, HG see the Users menu from within the main menu and add users there. It's the most intuitive path, and the error handling leaves them completely confused and without any idea why it's not working. This is an extremely bad experience for users at a time when they need to be adding team members and sharing Grafana internally. Very high priority to fix. 

![existing - wrong](https://user-images.githubusercontent.com/2886187/27803384-24620854-5ff7-11e7-973e-72ab74a0a5dc.png)

### Current: _Correct_ Flow
The correct flow currently isn't much better, even when an admin knows they need to add a user via Grafana.com. This flow is reliant on active communication between the admin and the new user, and is prone to delays and errors.

![existing - right](https://user-images.githubusercontent.com/2886187/27803591-37a5ba5e-5ff8-11e7-8367-5c5fb2f87605.png)

### Solution 
Will post additional thoughts on what the minimum incremental improvements could be, but in short, the handoff between HG and G.com needs to be seamless, with users understanding where auth is being handled and automate the process of adding new users to the correct org. This will involve improvements to G.com as well, but let's focus on the core Grafana improvements to facilitate this while laying groundwork for other auth providers.

**Comment by mattttt** [comment]
@torkelo This is really becoming a higher priority as days pass. Nearly every single new HG user is confused and needs help, even though in the welcome email we tell them how they need to add/manage users. 

Thanks!

**Comment by torkelo** [comment]
Not sure what the best way forward is (both in terms of quick low hanging fruit improvement and long term vision). 

See a few options 

A: Quick solution 
New option named something like "add user link" which will make the Add user button open a new tab with grafana.com org members page.

B: More integrated solution
Make the invite feature be able to communicate with Grafana.com so it sends a grafana.com user invite

C: Rethink grafana.com user management and the enforcement of only login via grafana.com user. 

Maybe start with A? 

@DanCech thoughts?

**Comment by DanCech** [comment]
A seems like a reasonable place to start

**Comment by mattttt** [comment]
@torkelo I think A is a great start. Are you thinking that the "Add User Link" would be a config item that would replace the default Add User button?

**Comment by torkelo** [comment]
> @torkelo I think A is a great start. Are you thinking that the "Add User Link" would be a config item that would replace the default Add User button?

yes exactly! 

ok. Will try to get this into 4.4.2 patch release

**Comment by torkelo** [comment]
```ini
[users]
...
...
# External user management
external_manage_link_url =
external_manage_link_name =
external_manage_info =
```

The external_manage_info can contain markdown (so it can contain links). 

![image](https://user-images.githubusercontent.com/10999/28779046-0be4f112-7602-11e7-9c34-1191dc325583.png)
