### ISSUE TITLE
[Bug] Grafana-InfluxDB tag querying when using template variable

### ISSUE THREAD

**Issue by tcloaa** [grafana/grafana#8770]
In InfluxDB, tag string value is stored at 'value' with the quotation. So when doing the query, we should do something like `select * from measurement where tag1 = 'value1'`.

However in Grafana, if we use template variable `template`, and we select `value1`, then in the panel, the query becomes `select * from measurement where tag1 = [[template]]`, which gives us nothing because of the missing quotations. (in the javascript response:  `select * from measurement where tag1 = value1`

Moreover, if you choose `ALL` option or `multiple selected` option, it will become a tuple in the query, giving us nothing as well.

Thanks,

**Comment by torkelo** [comment]
Grafana can not magically fix your  metric query if you use the raw query editor mode. If you use the UI query editor then it tries to do the right thing, even change to regex operator so multi value template variables will worm
