### ISSUE TITLE
[Bug] Templates check self referencing

### ISSUE THREAD

**Issue by kazeborja** [grafana/grafana#8773]
Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Centos7

- What did you do?
I had two templates one called "hostgroup" and one called "host", in my case "host" references "hostgroup".

```
$hostgroup	SHOW TAG VALUES WITH KEY = "submitter_hostgroup"
$host	SHOW TAG VALUES WITH KEY = "host" WHERE "submitter_hostgroup" =~ /$hostgroup/
```

- What was the expected result?
To load the "host" template with the results of querying InfluxDB by "hostgroup"

- What happened instead?
Couldn't update the template, the error was I can't reference a template variable by itself. Changing the name of the "host" template to "hostname" worked, so I believe the referencing check isn't matching the exact String and since "hostgroup" contains "host" it was giving a false match.
 
Related issue: https://github.com/grafana/grafana/issues/7614

**Comment by daniellee** [comment]
Confirmed: https://github.com/grafana/grafana/blob/master/public/app/features/templating/editor_ctrl.ts#L80-L83

**Comment by thuck** [comment]
@daniellee I think it's just a matter of improving the regex, from:
```RegExp('\\$' + $scope.current.name)```
to:
```RegExp('\\$' + $scope.current.name + '$')```

But I think I made it very restrictive for some reason that I do not recall right now, I think this breaks something after if we allow the regex to include "sub" matches.
Do you want me to take a look on this?

**Comment by daniellee** [comment]
@thuck that would be great if you have time. Thanks!

**Comment by thuck** [comment]
@daniellee no problem, I'll take a look this weekend.
