### ISSUE TITLE
Can singlestat sync with time range zoom in?

### ISSUE THREAD

**Issue by tcloaa** [grafana/grafana#8774]
Let's say my singlestat panel does the following:
```
 SELECT max(*) FROM (select a - b from message)
```

So basically, it searches for global maximum.

May I ask that, is it possible in Grafana that when I zoom in to look at the data in Graph panel (which will select a fixed time range on upper right corner), the singlestat will also "zoom in" to this range to look for a local maximum in this case?

Thanks,

**Comment by torkelo** [comment]
Yes of course, you just need to include the current time range i your query, this is available through macro

**Comment by tcloaa** [comment]
But this is not synchronized with the zoom-in time range with my graph, or dashboard time range. Is it?

**Comment by daniellee** [comment]
It is synchronized with the time range if you are in query editor mode then Grafana automatically adds the [$timeFilter variable/macro](http://docs.grafana.org/reference/templating/#the-timefilter-or-timefilter-variable) to the where clause.

If you are in Text Editor Mode (raw) then you have to [add it yourself](http://docs.grafana.org/features/datasources/influxdb/#text-editor-mode-raw).
