### ISSUE TITLE
[Bug] Quote character in metric name breaks InfluxDB Query Editor

### ISSUE THREAD

**Issue by vasekch** [grafana/grafana#8775]
I have a quote character (") in my InfluxDB metric name (silly I know, originally was not intention).

InfluxDB works ok with it if you escape it with backslash.
```
SELECT * from "Metric for \"silly\" thing." LIMIT 10
```
Using RAW query works ok, Query Editor suggests metric nicely, but after selecting it generates query without quotes escaped (seen in raw mode), thus causing error.

From Inspector:

REQUEST
```
SELECT mean("value") FROM "Metric for "silly" thing."." WHERE time > 1498812547512ms and time < 1499168419256ms GROUP BY time(1s) fill(null)
```

RESPONSE
```
{
  "error": "error parsing query: found silly, expected ; at line 1, char 39",
  "message": "error parsing query: found silly, expected ; at line 1, char 39"
}
```

I'm using Grafana 4.3.2 and InfluxDB 1.2.4 on CentOS 7

**Comment by daniellee** [comment]
I'm missing something here. Or do you mean that it does not automatically escape quotes? This works for me in both query editor mode and raw mode:

![image](https://user-images.githubusercontent.com/434655/27876576-ee3487c6-61b7-11e7-8c4d-5dc67365557a.png)

**Comment by torkelo** [comment]
closing due to lack of updates/details
