### ISSUE TITLE
Grafana Image Renderer does not send messages to the specified telegram topic

### ISSUE THREAD

**Issue by Gizex** [grafana/grafana#87785]
**What happened**:
Grafana Image Renderer does not send messages to the specified telegram topic
**What you expected to happen**:
After grafana update, it is now possible to select topics (message_thread_id) when sending messages via telegram
![изображение](https://github.com/grafana/grafana-image-renderer/assets/49234898/39318c5d-ced0-47a6-9b8b-78cc7a2ec01c)
![изображение](https://github.com/grafana/grafana-image-renderer/assets/49234898/05fea88a-cc56-4732-8b5d-14d69e0ad894)

In case of specifying a certain topic, the image from the alert will be sent to the master topic in any case. 
**How to reproduce it (as minimally and precisely as possible)**:
go to 
Alerting>> contact points >> add new contact point>> select "Telegram" >> add message_thread_id
![изображение](https://github.com/grafana/grafana-image-renderer/assets/49234898/fac3a377-e8f8-4145-b389-609c05920ae3)

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest(3.10.4)
- Grafana version: [11.0.0-preview (2024-04-08)](https://github.com/grafana/grafana/releases/tag/v11.0.0-preview) or [10.4.0 (2024-03-06)](https://github.com/grafana/grafana/releases/tag/v10.4.0)
- Installed plugin or remote renderer service: Installed plugin
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:

**Comment by AgnesToulet** [comment]
Hello! Thank you for opening this issue, I transferred it to the Grafana repository as this is an alerting issue and not an image renderer one.

**Comment by cfilomena** [comment]
Hello!
Same problem on the 11.0.0

Thanks

**Comment by kamenskiyyyy** [comment]
Hello!
Same problem on the Grafana v10.4.1 (d94d597d84)

<img width="300" alt="Screenshot 2024-06-14 at 18 09 27" src="https://github.com/grafana/grafana/assets/72261703/705acc4c-9fdf-4b9f-a3e4-87c367cb46d7">
<img width="300" alt="Screenshot 2024-06-14 at 18 09 27" src="https://github.com/grafana/grafana/assets/72261703/6f520602-0088-4de4-8b2c-cd32d15ed3cc">
