### ISSUE TITLE
[Bug] Using variable in "now delay"

### ISSUE THREAD

**Issue by lmjeremias** [grafana/grafana#8780]
I'm trying to use a template variable in the "Now delay now-" setting. I create a template variable (e.g. "delay" and give it "20m"). Then I refer the variable in the "Now delay now-" setting ($delay). As soon as I change the range to view in the top row I get the error "Cannot read property 'valueOf' of undefined" or "Cannot read property 'subtract' of undefined"

Using Grafana v4.3.0-beta1 (commit: 3a89272) with InfluxDB

**Comment by torkelo** [comment]
This field does not support variables, not sure we will add support for it, think the now delay needs some rethinking
