### ISSUE TITLE
[Question] Plugin Heatmap/Histogram

### ISSUE THREAD

**Issue by tcloaa** [grafana/grafana#8782]
I am using InfluxDB as my database.

Now I have a tag column named `instrument` with possible values `a`. `b`, `c`, and in InfluxDB, I think there is no way to count the number of options of tag values automatically. But I want to show the frequencies of these instrument options in either heapmap like [this](https://grafana.com/plugins/savantly-heatmap-panel), or just a histogram to reflect the frequencies.

Is it possible to do this for 1 tag column?

**Comment by torkelo** [comment]
Not possible with InfluxDB, 

Please use community site gör questions
