### ISSUE TITLE
[Bug] DB migration while upgrading 4.3.2 to 4.4.0 failed

### ISSUE THREAD

**Issue by abravorus** [grafana/grafana#8784]
After Grafana upgrade from 4.3.2 to 4.4.0 (via grafana_4.4.0_amd64.deb for Linux Debian 8.8 Jessie) grafana doesn't start. The log file includes the following DB migration error info:

t=2017-07-05T07:33:15+0300 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-07-05T07:33:15+0300 lvl=info msg="Starting DB migration" logger=migrator
t=2017-07-05T07:33:15+0300 lvl=info msg="Executing migration" logger=migrator id="save existing dashboard data in dashboard_version table v1"
t=2017-07-05T07:33:15+0300 lvl=eror msg="Executing migration failed" logger=migrator id="save 
existing dashboard data in dashboard_version table v1" error="NOT NULL constraint failed: dashboard_version.created_by"
t=2017-07-05T07:33:15+0300 lvl=eror msg="Exec failed" logger=migrator error="NOT NULL constraint failed: dashboard_version.created_by" sql="INSERT INTO dashboard_version\n(\n\tdashboard_id
,\n\tversion,\n\tparent_version,\n\trestored_from,\n\tcreated,\n\tcreated_by,\n\tmessage,\n\tdata\n)\nSELECT\n\tdashboard.id,\n\tdashboard.version,\n\tdashboard.version,\n\tdashboard.version,\n\tdashboard.updated,\n\tdashboard.updated_by,\n\t'',\n\tdashboard.data\nFROM dashboard;"
t=2017-07-05T07:33:15+0300 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error=
"Sqlstore::Migration failed err: NOT NULL constraint failed: dashboard_version.created_by\n"

Version 4.3.2 installed back works fine.
Datasourses: Graphite, ElasticSearch

**Comment by KKeXX** [comment]
I'm facing exactly the same problem under RedHat 6.9 x64. Installed via yum from grafana repo. A downgrade to 4.3.2 worked without Problems.
Datasources as well: Graphite and Elastic

**Comment by daniellee** [comment]
#8783 was reported just before this so closing as a duplicate. Thanks for reporting this!
