### ISSUE TITLE
[BUG] Wrong URL parameter for InfluxDB credentials introduced in Grafana 4.4

### ISSUE THREAD

**Issue by elisiariocouto** [grafana/grafana#8789]
Hello guys.

Using Grafana 4.3 querying an InfluxDB 1.2.2 instance, the URL parameters for authentication were `u=` and `p=`. In Grafana 4.4, apparently, they were changed to `username=` and `password=`. InfluxDB fails to parse the authentication credentials, I needed to downgrade to 4.3 again. Keep in mind that in the datasource settings I have the "HTTP auth" disabled and the "InfluxDB details" filled in with the credentials.

**Comment by torkelo** [comment]
what do use direct or proxy access (in data source settings) ?

**Comment by torkelo** [comment]
original commit was lost in history rewrite fix, new commit is cherrry picked into in v4.4.x 
https://github.com/grafana/grafana/commit/cff1c37064a2f0cf3e0d2ad8fa99f89e4b933c5a

**Comment by rkx-bloodshed** [comment]
This error is in the last build 4.4.1
