### ISSUE TITLE
"Not found" pop up message on every page after upgrading to v11 version

### ISSUE THREAD

**Issue by YevhenLodovyi** [grafana/grafana#87891]
### What happened?

I am testing the new grafana version(v11) and I can see the pop up message on every page). As far as I can see it is due to disabled alerting.
![Screenshot 2024-05-15 at 10 56 37](https://github.com/grafana/grafana/assets/118185595/20b5f9cf-e5d0-4785-b306-d1a106b80ade)

![Screenshot 2024-05-15 at 10 49 23](https://github.com/grafana/grafana/assets/118185595/3e9e8b2d-a21d-4e2c-a0c4-9fe21124ac21)

### What did you expect to happen?

no pop up message since it is very annoying

### Did this work before?

yes

### How do we reproduce it?

- disable alerting:
```
[unified_alerting]
enabled = false
``` 

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.0.0
OS:
Browser: Chrome 124.0.6367.203

### Grafana platform?

Docker

**Comment by alex2grad** [comment]
I had the same issue.
As workaround I deleted all permission associated with alert rules and no "Not found" pop up message anymore.

stop grafana
sqlite3 /var/lib/grafana/grafana.db
sqlite> delete from permission where action in ('alert.rules:read','alert.rules:create','alert.rules:delete','alert.rules:write');
start grafana

**Comment by dastrobu** [comment]
I can report the same issue after upgrading to Grafana 11. The request that is failing is 

```
https://***/grafana/api/prometheus/grafana/api/v1/rules?dashboard_uid=container-restarts
```

The response is `{"message":"Not found"}`. 

Grafana logs on debug level are also not very helpful: 

```
logger=context traceID=999b0f5636618b8fc073488bb36873c5 userId=201 orgId=156 uname=*** t=2024-05-27T07:38:28.078979597Z level=info msg="Request Completed" method=GET path=/api/prometheus/grafana/api/v1/rules status=404 remote_addr=10.131.85.208 time_ms=9 duration=9.066818ms size=24 referer="https://***/grafana/d/container-restarts/container-restarts?orgId=156" handler=notfound status_source=server
```

It should also be noted that grafana runs with 

```
[unified_alerting]
  enabled = false
```

So I am wondering what the calls to `prometheus/grafana/api/v1/rules?` are for.

**Comment by dastrobu** [comment]
Some local testing shows the following API behavior: 

```
[unified_alerting]
  enabled = true

```
gives
```
curl -X GET --location "http://localhost:3000/grafana/api/prometheus/grafana/api/v1/rules"     -H "Accept: application/json"     -H "Content-Type: application/json"     -H "Authorization: basic ***"     -H "X-Grafana-Org-Id: 1"
{"status":"success","data":{"groups":[]}}
```

whereas 

```
[unified_alerting]
  enabled = false

```
gives
```
curl -X GET --location "http://localhost:3000/grafana/api/prometheus/grafana/api/v1/rules"     -H "Accept: application/json"     -H "Content-Type: application/json"     -H "Authorization: basic ***"     -H "X-Grafana-Org-Id: 1"
{"message":"Not found"}
```

So it looks like a UI bug, where the UI is not aware of disabled alerting and tries to fetch rules, even if the API is disabled.

**Comment by matthewdarwin** [comment]
I am also getting the "not found" dialog box

**Comment by dastrobu** [comment]
Is this fixed in v11.1.0 or v11.0.1? I did see it on the release notes.

**Comment by gillesdemey** [comment]
It will be in the next minor release (v11.2.0) and I've back-ported to v11.1.x and 11.0.x so it should also land in those minors some time in the future.

I couldn't find it mentioned in the CHANGELOG nor the release notes so I'm assuming you meant you _didn't_ see it in the release notes?

As a general rule of thumb; if a fix isn't mentioned in the release notes and has the "add to changelog" label added to it it's simply not in that release and will be available in the next minor release :)

**Comment by dastrobu** [comment]
> I'm assuming you meant you didn't see it in the release notes?

Yes. Sorry for the typo. 

Thanks for the long explanation. I am looking forward to the next release.
