### ISSUE TITLE
Support for nested query for prometheus to reference other query rows

### ISSUE THREAD

**Issue by renannprado** [grafana/grafana#8791]
Please include this information:

* What Grafana version are you using?
docker image **grafana/grafana:4.3.2**
* What datasource are you using?
prometheus
* What OS are you running grafana on?
debian:jessie
* What did you do?
Tried to use nested query in prometheus like: sum(#B)
* What was the expected result?
Query prometheus by using sum(myquery)
* What happened instead?
Error: 

```json
{
"status": "error",
"errorType": "bad_data",
"error": "parse error at char 8: unclosed left parenthesis",
"message": "parse error at char 8: unclosed left parenthesis"
}
```

Call generated: `http://prometheus.intranet/api/v1/query_range?query=sum(%23B)&start=1499271350&end=1499271650&step=2`

For the graphite datasource, we have a very nice feature which is:
http://docs.grafana.org/features/datasources/graphite/#nested-queries

I'm not sure if this is supported by graphite or if it is implemented by the datasource plugin. However it would be nice that it was supported for the prometheus datasource too. Meaning: the replacement of `#B` by the said query would be done on the grafana side and doesn't necessarily needs to be supported by the datasource.

**Comment by torkelo** [comment]
would the final interpolated query be valid prometheus query? Does prometheus support nested sub queries?

**Comment by renannprado** [comment]
@torkelo not sure if ALL queries would be valid, however I'm pretty sure there are valid scenarios.
Example:
query A = rate(redis_net_input_bytes_total{kubernetes_namespace="yyyy"}[5m])
query B = sum(#B)

That works for sure.

**Comment by bergquist** [comment]
Closed by #9983

**Comment by renannprado** [comment]
@bergquist I believe this can be closed, right?

**Comment by tonglil** [comment]
Why did this get closed, did the feature get implemented? #10098 mentions further discussion between alerts + nested queries.

**Comment by raags** [comment]
This would be useful to break down long promql statements and also support [subquery](https://prometheus.io/blog/2019/01/28/subquery-support/)

**Comment by aocenas** [comment]
@dprokop I am adding this to platform backlog as this seems like a more generic feature request ie referencing other query like this:

```
query A = rate(redis_net_input_bytes_total{kubernetes_namespace="yyyy"}[5m])
query B = sum(#A)
```
Which should be relevant to all datasources and also dasahboards

**Comment by mtanda** [comment]
Another solution is supporting macros.

Cloud Monitoring MQL support macros.
https://cloud.google.com/monitoring/mql/query-language#ql-macros

It seems to useful for break down long complex query.

There is a feature request in Prometheus, but it was closed because they think it should be handled by Grafana.
https://github.com/prometheus/prometheus/issues/6822

**Comment by zoltanbedi** [comment]
@grafana/grafana-frontend-platform is the new expressions feature going to support this? Would this  features clash? We are thinking doing this for Prometheus.

**Comment by renannprado** [comment]
@zoltanbedi @davkal I see now it is `prio/high`, so is there any expectation when this should happen?

**Comment by itsmylife** [comment]
Because of other high priorities, we commit ourselves to follow up in Q4.

**Comment by mckn** [comment]
> Because of other high priorities, we commit ourselves to follow up in Q4.

I don't have much knowledge about nested queries in Prometheus but the example provided earlier in this thread is possible to achieve with query expressions.
