### ISSUE TITLE
[Bug] Graph lines disappear when zooming in (to <~ 500 data points)

### ISSUE THREAD

**Issue by rwarren** [grafana/grafana#8792]
**Grafana version**: 4.4.0
**Data source**: influxdb
**OS**: Linux (Debian 8.8 - Jessie)
**Browser**: Chrome 59.0.3071.115 (Official Build) (64-bit)

**Expected Result**:

Lines should be plotted, no matter how many data points are in the chart frame.

**What happens instead**:

When you zoom any of the basic charts to a span of less than 1.5 hrs (or so), all chart lines disappear.  Or they do on my system, with data points every 10 seconds (ie: <~ 500 data points). In order to see data, you need to change the chart to render the data points.

For example, below is the same chart, at slightly different zoom levels...

The limit of visibility (without point rendering):
![image](https://user-images.githubusercontent.com/2751728/27880005-8471845e-6191-11e7-93b6-179daf91ce24.png)

When zoomed in a bit more (the lines disappear):
![image](https://user-images.githubusercontent.com/2751728/27880021-8c77622c-6191-11e7-8f1e-07a75835d421.png)

Now _only_ enabling data point display so you can actually see the data:
![image](https://user-images.githubusercontent.com/2751728/27880044-9b370650-6191-11e7-9ddf-5561c84816d2.png)

FWIW, enabling bars also makes the data visible. Lines are the only things that disappear.

**Comment by torkelo** [comment]
https://community.grafana.com/t/why-is-my-graph-empty-when-i-zoom-in/24

**Comment by rwarren** [comment]
Thanks for that link... it does clearly explain the groupby oddity.

However, it seems like there should really be a better solution. The answer (setting the groupby for the data source to be `>$yourSamplePeriod`) is pretty non-intuitive and obscure. It does make sense, and did work for me, though, so thanks for that.

I think the ideal solution would be to *always* plot stranded (ie: nulls on either side) data points as a point, whether or not points should be drawn. Having a handy tooltip explaining why this was done might also be nice, but it should be reasonably clear in the chart for "real" missing data (vs "fake" missing data driven by groupby behaviour like `fill(null)`). Certainly more clear than displaying an empty chart on a reasonable zoom-in, anyway!!  If this feature *were* done, it does mean that the "point radius" would need to be available in the "Display" tab, even when points are not selected (this location would be a nice spot for a tooltip explaining that points are plotted when they are stranded).

Are there any related issues or features suggestions related to this, or with further info?
