### ISSUE TITLE
[Bug] A space in "Default group by time" value causes confusing errors

### ISSUE THREAD

**Issue by rwarren** [grafana/grafana#8793]
**Grafana version**: 4.4.0
**Data source**: influxdb
**OS**: Linux (Debian 8.8 - Jessie)
**Browser**: Chrome 59.0.3071.115 (Official Build) (64-bit)

**Expected Result**:

Entering "> 10s" (with a space) into the "Default group by time" for a data source should either A) work like ">10s" (no space), or B) not do weird things.

** What actually happens**:

I set the value to "> 10s" (with a space) and it seem to accept it.  However, various alarms started firing with this message:

`tsdb.HandleRequest() error time: invalid duration 10s`

After some failed experimentation with ">= 10s", "> 9.999s", and others (thinking it might be a fencepost issue), I noticed the space and tried removing it.  Without the space ("`>10s`") it works perfectly.

The space should be stripped, or an obvious error should occur.

**Addendum:**
I *think* that saving the bad (with space) setting was accepted without error, but I'm actually not sure. This is because my `grafana` user in `influxdb` does not have admin privileges, and any testing operations always throw an error due to not being able to run a `SHOW DATABASES` query.

**Comment by torkelo** [comment]
This syntax is no longer supported, default group by interval is always a minimum
