### ISSUE TITLE
[Bug] Grafana should not require Superuser access to InfluxDB

### ISSUE THREAD

**Issue by Stickiler** [grafana/grafana#8796]
The latest version of Grafana available on Ubuntu repos is 4.4.1, and it requires SuperUser access to any InfluxDB data source, which is an insane security risk, and writes off any chance of using the newer versions.

This is caused by commit 89a7c2c686854790f5306ab6de7f7aa48a55643b, which was developed to fix #7864, but the fix in place opens a serious security hole when using Grafana.

**Comment by daniellee** [comment]
Dupe #8481. This is incorrect. It only requires a superuser for testing the data source and that is just a warning. You can ignore it and use a user with lower permissions.
