### ISSUE TITLE
[Bug] Random Ordering of metric in mysql query

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#8798]
using grafana v4.4.1 and mysql as a datasource

If I have a query that returns more than one distinct value in the metric column I get multiple lines as expected but the order that the names appear in the legend (and hence the colors of the lines) appears to be random. Clicking on the refresh button makes the line colors change and causes the legend to randomly reorder.

I've tried `order by metric, datetime asc` and `order by datetime asc, metric` but neither seems to fix the issue.

I'm enjoying trying out the mysql datasource, thanks for all the work.

**Comment by daniellee** [comment]
Dupe: #8604

**Comment by kalyanbitra** [comment]
Hi,
has this issue getting any priority..  I recently started using grafana and I love it.. this feature will add huge kudos..
