### ISSUE TITLE
[Bug] Maintain scroll position after Exporting CSV

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#8800]
- What Grafana version are you using? (4.4.1)
- What datasource are you using? (graphite)
- What OS are you running grafana on? (RHEL 6.4)

- What did you do?
Export a CSV after scrolling to a panel

- What was the expected result? 
Scroll position should be maintained

- What happened instead? 
Scroll position reset to top of the page

**Comment by ryantxu** [comment]
This happens anytime you open a modal window.  It would be great if modal windows in general kept their original position rather than requiring scrolling to the top first.
