### ISSUE TITLE
InfluxDB: Query builder produces invalid SQL query when using wildcard column name

### ISSUE THREAD

**Issue by NWRichmond** [grafana/grafana#88008]
## Problem

When using the InfluxDB data source in SQL mode, the query builder can't run queries with a wildcard column name (`SELECT *`). Choosing `*` in the **Column** select leads to an error:

> flightsql: rpc error: code = InvalidArgument desc = Error while planning query: Schema error: No field named "*".

<details>
  <summary>Example query on main</summary>
  <img src="https://github.com/grafana/grafana/assets/5732000/8813f773-443c-4ea1-9219-4b8338cd9f0c" alt="demo influxdb sql error when using wildcard column" />
</details>

This happens because we are wrapping all column names in double-quotes and not considering `*` as a special case: https://github.com/grafana/grafana/blob/7726631fe8f5220fe09f8854616993fc1465bd0e/public/app/plugins/datasource/influxdb/fsql/sqlUtil.ts#L28-L29

## Proposed solution

When the column name is `*`, do not wrap the column name in double-quotes.

I made this change locally, and everything worked as expected: 

```ts
function formatTableName(parameter: string | undefined): string {
  if (parameter === '*') {
    return parameter;
  }

  return `"${parameter}"`;
}


export function toRawSql({ sql, table }: SQLQuery): string {
  // ...
  const sc = sql.columns.map((c) => ({
    ...c,
    parameters: c.parameters?.map((p) => ({ ...p, name: formatColumnName(p.name) })),
  }));
  // ...
}
```

<details>
  <summary>Example query with code change</summary>
  <img src="https://github.com/grafana/grafana/assets/5732000/033d4400-3eb0-4465-a713-b0987a932d96" alt="demo solution to influxdb sql error when using wildcard column" />
</details>

**Comment by wasim-nihal** [comment]
Is this open for contribution?

**Comment by itsmylife** [comment]
@wasim-nihal Yes it is. Feel free to contribute and add us as reviewers to your PR. Thank you very much for your contribution.

**Comment by yogesh1801** [comment]
@itsmylife can i contribute?

**Comment by wasim-nihal** [comment]
@yogesh1801, Thanks for expressing your interest here 🚀. This is currently WIP in branch https://github.com/nokia/grafana/tree/influxdb-88008

**Comment by yogesh1801** [comment]
@wasim-nihal can i contribute at the PR given by you

**Comment by wasim-nihal** [comment]
> @wasim-nihal can i contribute at the PR given by you

yogesh1801 , this branch belongs to my org and I am afraid I do not have access to provide permissions.
