### ISSUE TITLE
[Bug] Escaping chars for multi-value tags

### ISSUE THREAD

**Issue by jsiembida** [grafana/grafana#8801]
- What Grafana version are you using?

Grafana 4.3.2

- What datasource are you using?

Prometheus 1.7.0

- What OS are you running grafana on?

Debian 8.8

- What did you do?

Set up a CPU usage panel with a query like so `irate(cpu{host="[[host]]"}[1m])`
Where `[[host]]` is a Prometheus query type template variable pulled via `label_values(host)`.
Also, I set "repeat panel by host" to see CPU graphs for all selected hosts in one row, and make sure multi-value in template var config is enabled.

- What was the expected result?

Multiple panels in one row populated with CPU graphs for hosts selected from the dropdown.

- What happened instead?

For hosts that contain dots in the names, graphs are empty (as in "No data points") 

- Observations

Grafana escapes dots to work around regexps when template var has multi-value selected. At the same time, Grafana issues multiple queries to Prometheus, for each selected host, without actually using regexp operator. I.e. if I select from the dropdown two hosts: `a-b-c` and `d.e.f`, tcpdump shows two queries at the Prometheus backend:

`GET /api/v1/query_range?query=irate(cpu%7Bhost%3D%22a-b-c%22%7D%5B1m%5D)&start=1499317870&end=1499339470&step=40`
`GET /api/v1/query_range?query=irate(cpu%7Bhost%3D%22d%5C%5C.e%5C%5C.f%22%7D%5B1m%5D)&start=1499317763&end=1499339363&step=40`

Hex unescaped, they are (time ranges dropped):

`/api/v1/query_range?query=irate(cpu{host="a-b-c"}[1m])`
`/api/v1/query_range?query=irate(cpu{host="d\\.e\\.f"}[1m])`

The latter one makes Prometheus return empy result (it is `host=` not `host=~`, so the escaped dots don't seem right here).

When the multi-value option is disabled, Grafana doesn't escape the dots and graphs show up as expected.

**Comment by torkelo** [comment]
Use regex operator in your label filter, when multi value is selected each value is regex escaped so it works in a regex

**Comment by jsiembida** [comment]
If multi value implies regex, why the query sent to Prometheus doesn't use regex operator `host=~...`? It is `host=...`, which returns empty vector.

**Comment by torkelo** [comment]
Yes, you need to change that so it uses regex, only way to match multiple label values

**Comment by jsiembida** [comment]
I see, thanks, that will do.
