### ISSUE TITLE
Grafana Relational Database Datasource Timeline

### ISSUE THREAD

**Issue by amohnacs15** [grafana/grafana#8802]
Recently upgrading to Grafana 4.3 MySQL is now supported as a data source.  Postgres currently works with Grafana but with the aid of an external plugin and the correct version of Grafana which contains the appropriate patch.  Integrating Postgres doesn't seem to far off.  _Are there plans to introduce other relational databases at some point in the (near) future such as PostgreSQL?_

**Comment by daniellee** [comment]
Yes, see our [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md#short-term-1-4-months). Postgres is the next one after MySQL but we are planning to support other relational databases as well.
