### ISSUE TITLE
Data cleared for MQTT source when dashboard updates

### ISSUE THREAD

**Issue by gpabdo** [grafana/grafana#88038]
### What happened?

When you have both a panel with a live MQTT data source and a DB query, every time the dashboard refreshes, it deletes any data from the live panel as well. This means the live panel will reset to empty every time the dashboard updates. (every 5, 10, 30 seconds or whatever)

### What did you expect to happen?

Not lose data from live panels when the dashboard gets now data from other panels.

### Did this work before?

Never seen it work 

### How do we reproduce it?

1. Add a live panel to a dashboard
2. Set "Set auto refresh interval" to some valie
3. Wait for the interval

### Is the bug inside a dashboard panel?

No, dashboard itself. 

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d94d597d84)
OS: MacOS 13.2.1
Browser: Safari 16.3 / Chrome / FireFox

### Grafana platform?

Kubernetes

### Datasource(s)?

MQTT 1.0.0-beta.4

**Comment by tonypowa** [comment]
Hi @gpabdo 
Thank you for creating this issue

To help us investigate the problem with the MQTT data source on the dashboard effectively, could you please provide a bit more information?Thank you

- a screen recording where we can see the behaviour

- the configuration settings for the MQTT data source and the panel you're experiencing this issue with

- Any logs from Grafana or the MQTT broker that indicate an error or unexpected behavior during the auto-refresh interval
