### ISSUE TITLE
Explore: Show the edit form to define query template properties (when adding from query history)

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#88043]
Show a drawer to fill-in properties for a query template.

**Comment by ifrost** [comment]
Looks slightly different than on designs when using default components from grafana-ui:

<img width="795" alt="Screenshot 2024-05-22 at 15 00 19" src="https://github.com/grafana/grafana/assets/745532/9e9c6189-1577-4fd8-951f-d9631d0d0286">

@diegoadams should we go with grafana-ui (should be more consistent with the rest of IU) or tweak it as per deisgns?

**Comment by diegoadams** [comment]
Hey @ifrost , is there anyway I could see an Ephemeral of it? if not please could you do a video. I just want to see it in full context.

**Comment by ifrost** [comment]
> Hey @ifrost , is there anyway I could see an Ephemeral of it? if not please could you do a video. I just want to see it in full context.

Sure-io! I'll create one 👍

**Comment by diegoadams** [comment]
thanks @ifrost , The Grafana UI version looks good! The only suggestion I have is to change the auto-star toggle look. 

If possible, could we take it out of the current field and leave it as per the design.


<img width="1966" alt="Screenshot 2024-05-23 at 22 34 51" src="https://github.com/grafana/grafana/assets/95694434/d55b2307-444d-494c-ac6f-b2bd870d68ca">

**Comment by diegoadams** [comment]
> If yes - we can make adjustments to the shared component so it can happen in other places too.

Ok, leave it as is for now (as grafana UI default) and I will bring it up with UX team in the meantime.
