### ISSUE TITLE
Alerts are sent to telegram topics - but the image-renderer breaks it

### ISSUE THREAD

**Issue by zhyzha** [grafana/grafana#88044]
### What happened?

Hello!
Grafana 10.4.2 - thanks for the opportunity to send telegram alerts to individual topics.
In our team we use image-renderer. And when distributing alerts across topics, everything breaks down - pictures are sent as messages to the General or Main channel. Can anything be done about this?
After all, the meaning of the whole idea with topics in this case is lost

### What did you expect to happen?

The ability to receive alerts on topics with images

### Did this work before?

no

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:10.4.2
OS:Linux 6.1 amd64
Browser:

### Grafana platform?

Docker

### Datasource(s)?

VictoriaMetrics

**Comment by kamenskiyyyy** [comment]
duplication #87785

**Comment by AgnesToulet** [comment]
Closing as a duplicate.
