### ISSUE TITLE
[Feature request] Prevent time range modifications when saving an updated dashboard

### ISSUE THREAD

**Issue by mivok** [grafana/grafana#8805]
When viewing dashboards, very often we will zoom out to a different time range, make a small edit, and save the dashboard without remembering to set the time range back to what the dashboard was originally set at. For example, a dashboard has a time range of 1 hour, but you zoom to 24 hours and add an automatic refresh while viewing the dashboard (because that's the time range you're interested in looking at). Then you modify the dashboard to add a new graph, and save it without resetting the time range to 1 hour. The next person to view the dashboard gets a time range of 24 hours, and it has to be fixed separately.

Currently we have to have the discipline to not modify the dashboard after we've modified the time range (or deal with getting random time ranges on our dashboards each time we view them). It would be nice however to have something that prevents this issue from happening. Some ideas:

* Warn before saving a dashboard if you changed the time range from the one the dashboard was previously saved with, and give the user an option to save with the original time range instead.
* Have a time picker setting on the dashboard to preserve the original time range settings on dashboard save, which you have to explicitly untick if you want to save the dashboard with a new time range. If the box is ticked preventing changes, then any dashboard save would not alter the saved time range.

**Comment by daniellee** [comment]
We had hoped to include this in the 4.4.0 release but ran out of time. It should be in the next release of Grafana.

**Comment by grobie** [comment]
Thanks! This is great request and would help us a lot. At the moment we make a lot of our dashboards uneditable to prevent accidental time range and template variable defaults changes.

From @torkelo in #8935 

> In the save dialog (new in 4.4) where you can specify an optional save message, there will be two checkboxes for "save current time range" , "save current template variable values".

Does this mean changes to only the time range or template variables will still prompt the `Unsaved changes` dialog?

**Comment by torkelo** [comment]
This would be pretty easy to implement, just need some ux design for how to add two checkboxes to save menu. 

One checkbox for "Save current time range", and one for "save current template variable values".  Of course the second should only be visible if there are template variables.
