### ISSUE TITLE
Cannot read property 'alias' of undefined

### ISSUE THREAD

**Issue by Amaradana** [grafana/grafana#8806]
Hi,

Am completely new on Grafana(4.4.1) and influxDB(v1.2.2). Am sending my jmeter test logs to influx DB and am trying to build a query. i was able to pull 2 off the values but the i was not able to get the table from grafana, not sure if its really possible, below is my table structure

time,errorCount,nodeName,requestName,responseTime,testName,threadName
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest1"."ThroudGroup 1-1"
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest2"."ThroudGroup 1-1"

Now my testname is smoketest1 and smoketest2, they are 2 different tests, what i will need to to is form a table on the below format

 **requestName AVG1 AVG2**

I will need to compare avg response times based on the 2 tests, From influxDB i have written a query 

Select requestName, Avg1 from (select mean(responseTime)/1000 as Avg1 from requestsRaw where testName='SmokeTest1' group by requestName);Select requestName, Avg2 from (select mean(responseTime)/1000 as Avg2 from requestsRaw where testName='SmokeTest2' group by requestName)

I was able to get the values as expected from InfluxDb, but giving a semicolon this breaks in grafana and i get an error
**Cannot read property 'alias' of undefined**

below is the stacktrace
Stack trace:
TypeError: Cannot read property 'alias' of undefined
    at http://localhost:3000/public/app/boot.js:16:27482
    at i (http://localhost:3000/public/app/boot.js:52:15288)
    at http://localhost:3000/public/app/boot.js:52:15710
    at o.$eval (http://localhost:3000/public/app/boot.js:52:22865)
    at o.$digest (http://localhost:3000/public/app/boot.js:52:21338)
    at o.$apply (http://localhost:3000/public/app/boot.js:52:23148)
    at http://localhost:3000/public/app/boot.js:52:19198
    at f (http://localhost:3000/public/app/boot.js:51:1421)
    at http://localhost:3000/public/app/boot.js:51:2882

Please include this information:
- What Grafana version are you using? :5.4.3
- What datasource are you using? :influxdb
- What OS are you running grafana on? Windows

**Comment by Amaradana** [comment]
Note: Time can be varied, but Time is not considered here

**Comment by daniellee** [comment]
The way to add multiple queries in Grafana is not to separate them with semicolon. Click on the new query button:

![image](https://user-images.githubusercontent.com/434655/27954874-3cb4c130-6312-11e7-9978-07c16b36226e.png)

Or duplicate the first query and then edit it:

![image](https://user-images.githubusercontent.com/434655/27954852-2d565d48-6312-11e7-8ad9-caba8855c2b5.png)

**Comment by Amaradana** [comment]
hey Danielle, Thank you For your Response, I have also tried the way you as you said, i was able to see in the response but it does not show in the Grafana UI / web / table for instance, 

my settings look like this : 

Query A: Select requestName, Avg1 from (select mean(responseTime)/1000 as Avg1 from requestsRaw where testName='SmokeTest1' group by requestName)

Query B : Select Avg2 from (select mean(responseTime)/1000 as Avg2 from requestsRaw where testName='SmokeTest2' group by requestName)

For both off them I selected Table, And the Output is 

requestName AVG1 
Transaction1  425
Transaction2  800

Query B output is never showed. there are no failures or exceptions that i could find out but i did see the reponse and i was able to find the output in the response, from UI it does not show up. So I changed Format from **"Table"** to **"Time Series"** And from the option i did change to **"Time Series to Column"** and i get only one row in the format, the other record never showed up, i gave my table also for reference 

requestName AVG1 AVG2
Transaction2 425 800

time,errorCount,nodeName,requestName,responseTime,testName,threadName
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest1"."ThroudGroup 1-1"
2017-06-14T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest2"."ThroudGroup 1-1"
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction2".800."SmokeTest1"."ThroudGroup 1-1"
2017-06-14T11:07:00.637817217Z.0."Test-Node"."Transaction2".800."SmokeTest2"."ThroudGroup 1-1"

i tried almost all the possible ways and am i wanted to try nested query /sub query but i always fail to get response from influxDB so am still working on it, if you think this can be solved from nested \ subquery Any help would be highly appreciated

Select requestName, Avg1, AVG2 from ((Select requestName, Avg1 from (select mean(responseTime)/1000 as Avg1 from requestsRaw where testName='SmokeTest1' group by requestName))(Select Avg2 from (select mean(responseTime)/1000 as Avg2 from requestsRaw where testName='SmokeTest2' group by requestName)))

**Comment by torkelo** [comment]
In table mode i think only one query is allowed, otherwise grafana would need to merge results which is cannot do right now, if you have time series query any number of queries can be usrd

**Comment by Amaradana** [comment]
By the way in my previous comment i also mentioned i had selected time series but it only shows only one row/ record. It doesnt show all the records, Anyways If thats the case, i dont think my frame work will not be considered any more and i have to look for other solution to build comparision report. In performance testing with out comparison between 2 runs 90% of the clients would not love to have, thougrespective with respective to different runs its still a manual task. Thank you sp much for support

- [ ]

**Comment by daniellee** [comment]
It should work if you have multiple queries with timeseries data.

Here is a simple example: http://play.grafana.org/dashboard/db/influxdb-table?panelId=6&fullscreen&edit&orgId=1&tab=metrics
