### ISSUE TITLE
adding SSL to grafana error: http: TLS handshake error from 127.0.0.1:49374: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by savagexiv** [grafana/grafana#8809]
Trying to secure Grafana using SSL and self signed certificates using this link: https://www.akadia.com/services/ssh_test_certificate.html

I have added the following to /etc/grafana/grafana.ini

`protocol = https`
`cert_file = /usr/sbin/certificate.crt`
`cert_key = /usr/sbin/certificate.key`

and have restarted grafana and when going to `https://myinternalgrafana.com` and it refuses to connect. However when i do a `systemctl status grafana` i get the following message: `http: TLS handshake error from 127.0.0.1:49374: tls: first record does not look like a TLS handshake`

Both port 80 and 443 are opened

**Comment by daniellee** [comment]
Please don't double post: https://community.grafana.com/t/ssl-for-grafana-error-tls-first-record-does-not-look-like-a-tls-handshake/1690
