### ISSUE TITLE
Percent Change reversal

### ISSUE THREAD

**Issue by AS-Labs** [grafana/grafana#88109]
**Why is this needed**:

Given the newly added Percent Change in the stat panel, it is showing Green values for increases and Red values for any decreases. The option to change this where Green values are for any metric that is decreasing, indicating a healthy change.

**What would you like to be added**:

The ability to reverse the Percent Change coloring, for more control over this new visualization option in the stat panel.

**Who is this feature for?**

Operations and NOC teams to track changes correctly; as in stats are healthy or becoming healthy.

**Comment by nmarrs** [comment]
Hi @AS-Labs - this feature has been implemented by https://github.com/grafana/grafana/pull/88205 :)

**Comment by AS-Labs** [comment]
> Hi [@AS-Labs](https://github.com/AS-Labs) - this feature has been implemented by [#88205](https://github.com/grafana/grafana/pull/88205) :) Available in [v11.1](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v11-1/#stat-visualization-percent-change-color-mode-options)

Thank you!
