### ISSUE TITLE
[Bug] Description box half out of Chrome window on the far left

### ISSUE THREAD

**Issue by LiquidSame** [grafana/grafana#8810]
- Using Grafana-4.2.0 for linux 64bits
- Graphite
- Server side is on RHEL6.8 / Web interface is Chrome on Windows8.1
- Create a grafana dashboard (link to dashboard : https://grafana.com/dashboards/2276)
- To see the full description box for the far left panels
- Half the panel is outside the Chrome window and cannot be seen
![untitled](https://user-images.githubusercontent.com/10808451/27961173-2daf9fc2-632e-11e7-9e4e-dea6314b101a.png)

**Comment by torkelo** [comment]
Fixed in 4.3±
