### ISSUE TITLE
[Bug] querying influx returns null for all data

### ISSUE THREAD

**Issue by ssirobertreilly** [grafana/grafana#8811]
- What Grafana version are you using?
      grafana-4.4.1-1.x86_64
- What datasource are you using?
      influxdb-1.2.4-1.x86_64
- What OS are you running grafana on?
    centos 7.1
- What did you do?
    installed influxdb and grafana. I have used this setup (sensu -> influx -> grafana) many times before this is the first time i have seen this issue.
- What was the expected result?
   see metrics in grafana
- What happened instead?
   all nulls 
![all nullst](https://ibin.co/3SZtixf1141U.png)
 
same query in influxdb
```
SELECT mean(value) FROM statsd.autogen.load_avg_one WHERE host =~ /^xx\.xx\.xx\.xx\.priv$/ AND time > now() - 60m GROUP BY time(60s)
name: load_avg_one
time			mean
----			----
1499448240000000000
1499448300000000000	0.05
1499448360000000000	0.02
1499448420000000000	0.01
1499448480000000000	0
1499448540000000000	0
1499448600000000000	0
1499448660000000000	0
1499448720000000000	0
1499448780000000000	0.08
1499448840000000000	0.03
1499448900000000000	0.02
1499448960000000000	0.01
1499449020000000000	0.03
1499449080000000000	0.01
```

I am not seeing any errors in either grafana or influxdb log

**Comment by torkelo** [comment]
Please use community site for questions
