### ISSUE TITLE
[Bug] TLS skip verify defaults to true on data source, cannot be changed without enabling client auth

### ISSUE THREAD

**Issue by azenk** [grafana/grafana#8812]
When attempting to configure an InfluxDB data source that uses an internally signed certificate, there appears to be no way for me to tell grafana about the CA cert without enabling TLS client authentication (the box in the UI is hidden until TLS Auth is checked, then complains when a client cert isn't provided).

More distressing is the fact that the data source connection test succeeds whether I have provided a CA cert or not, indicating that any https InfluxDB data source will ignore validation errors unless client auth is enabled.

Based on my quick skim of the code, it looks like the validation would only be performed if I enabled TLS Auth.  However, I cannot do this without providing a client certificate as outlined above.  In this case it looks like any data source connection that uses GetHttpClient() would be affected.

https://github.com/grafana/grafana/blob/2c7adccf12c8620d37dd4e9cef7d31b2d0de175d/pkg/models/datasource_cache.go#L50

This seems related to #5334.

**Comment by marcv81** [comment]
I just discovered the same issue. This is quite critical: it means that Grafana + InfluxDB is vulnerable to MITM attacks even when a CA-issued TLS certificate is used.

**Comment by mattbostock** [comment]
Working on a PR to fix.

**Comment by bergquist** [comment]
Fixed by https://github.com/grafana/grafana/pull/9377
