### ISSUE TITLE
Hide _Send alerts to_ options when `alertingDisableSendAlertsExternal` is enabled

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#88139]
Follow-up to https://github.com/grafana/grafana/pull/87982, the component that allows users to configure how their alerts will be routed should be hidden if `alertingDisableSendAlertsExternal` is active.

![image](https://github.com/grafana/grafana/assets/41638679/eaf4a9a4-9213-48e3-b3e2-146416ad53be)

**Comment by stevesg** [comment]
- Enable/Disable buttons next to individual Alertmanagers are hidden

- Change the text under the header to not imply configuration is possible of alerts are being sent
> Manage Alertmanager configurations and configure where alert instances generated from 
Grafana managed alert rules are sent

- Decide what to do status text, i.e. does it say "receiving alerts" or not.
