### ISSUE TITLE
[Bug] Data column in dashboard_version doesn't match dashboard table

### ISSUE THREAD

**Issue by culdev** [grafana/grafana#8813]
Grafana version 4.4.1 (commit: 6a9f8ca) with datasource InfluxDB.
The grafana database is stored in a MySQL server.

When saving a dashboard that is larger than 64 kB it will not fit into the dashboard_version table.

Error from syslog when saving a dashboard that is 65 kB:
```grafana-server[8468]: t=2017-07-08T12:36:05+0200 lvl=eror msg="Failed to save dashboard" logger=context userId=1 orgId=1 uname=admin error="Error 1406: Data too long for column 'data' at row 1"```

The `dashboard`-table is using mediumtext for its data, `dashboard_version` is using text.

Edit:
I also noticed that because the columns are mismatching, any dashboards that did not fit into `dashboard_version` contains an invalid json string.

**Comment by daniellee** [comment]
The dashboard table was recently updated (see [migration](https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/dashboard_mig.go#L133) here) in #7959 but the dashboard version table did not get its data field upgraded to mediumtext.

**Comment by JimHagan** [comment]
@danielee I was deploying 4.4.1 at my company today and within 30 minutes we ran into this issue saving any sizable dashboards.  We had to rollback to our previous version.   We are definitely anxious to get this fix.  I see you've added this to 4.4.2 milestone.  What sort of ETA would there be in having this available in a patch RPM?

**Comment by torkelo** [comment]
yes, patch releases means new rpm packages are pushed to YUM repo (and available for download)

**Comment by shalstea** [comment]
+1 seeing this issue as well.

**Comment by jermorse** [comment]
1+ seeing this and need a fix or workaround too.

**Comment by torkelo** [comment]
we are going to release 4.4.2 with this fix soon, 

Or you can try nightly build:
https://grafana.com/grafana/download/5.0.0-8432pre1
