### ISSUE TITLE
4.4.1 release tag has been moved

### ISSUE THREAD

**Issue by iMichka** [grafana/grafana#8815]
Hi. I am one of the homebrew package manager maintainers.

We pushed the 4.4.1 release to our users a few days ago. Meanwhile the sha256 of the tar file has changed, meaning that the tag has been moved. This is pretty bad practice. We rely on the sha256 for security reasons, allowing to check if upstream is delivering something fishy. In general you may want to tag a new release instead of moving the tag, if you realise that your release had some major flaw.

Could you please confirm that the change was made on purpose? Also, how big is the difference between the two tags? Should we distribute this with a different version to our users to notify them that there was some change between 4.4.1 and 4.4.1.new ?

See  https://github.com/Homebrew/homebrew-core/pull/15423 for reference.

**Comment by daniellee** [comment]
Sorry about that. I committed two large files in the packaging subfolder by accident that bloated the size of the repo so we decided to rewrite git history and remove them. Totally forgot that this would affect the homebrew build.

For end users, there is no difference in functionality. The commit that was changed was for updating the version number in a build script. You do not need to distribute a new version of Grafana. 

Do we need to do anything to fix this?

**Comment by iMichka** [comment]
It's okay, we changed the sha256 of the tar.gz and that should be fine for our users. Especially if there is no change of functionality.

Even if the files were large, I would have just removed them in a commit, and tagged a new release. As soon as you push stuff online, it is a bad idea to rewrite the git history. The git repo would have to carry the large files in the history, but that is often not so much a problem.

Thanks for the fast answer 👍

**Comment by daniellee** [comment]
@iMichka it doubled the size of the repo and as it only affected the latest few commits we decided to rewrite and thought that it probably wouldn't affect anyone. Hopefully we won't ever be doing that again. I apologize about causing problems for homebrew.
