### ISSUE TITLE
Explore: Jaeger Query Timestamps are not sent correctly

### ISSUE THREAD

**Issue by robenie-cwt** [grafana/grafana#88156]
### What happened?

What happened: The timestams sent to the Jaeger API is wrong
Expected: `2024-05-12 07:00:00 to 2024-05-12 12:00:00 UTC`

![image](https://github.com/grafana/grafana/assets/98741914/aef290b2-b2e5-4dec-b40a-94ad99314e0b)

### What did you expect to happen?

Actual: `2024-05-21 21:11:41 to 2024-05-22 05:11:41 UTC`

### Did this work before?

I'm not sure. I only noticed after upgrading to Grafana 11

### How do we reproduce it?

1. Install a Jaeger Data source
2. Open Explore
3. Query a date that ends earlier than 6 hours ago

### Is the bug inside a dashboard panel?

This can also be reproduced in a dashboard, it is the same issue as Explore

### Environment (with versions)?

Grafana: 11.0.0
OS: Windows 10
Browser: Edge 124.0.2478.51 

### Grafana platform?

Docker

### Datasource(s)?

Jaeger
```[tasklist]
### Tasks
```

**Comment by orloffv** [comment]
Guys, who can help? It seems to be a critical bug.
