### ISSUE TITLE
[Feature request] Add group/role header in auth.proxy

### ISSUE THREAD

**Issue by staticmukesh** [grafana/grafana#8816]
Please include this information:
- What Grafana version are you using?
   **v4.4.0-pre1**
- What OS are you running grafana on?
   **Ubuntu 16.04**
- What do you want?
   Currently `auth.proxy` does the authentication and sends the username/email in `X-WEBAUTH-USER` header, and through `auto_assign_org_role`, we can assign only specific role to all users. There should be a functionality of providing user's role while creating the user. I checked ldap and auth.proxy integration to do groups/role based authorization, but it requires ldap server connectivity from grafana. 
Many authentication proxy systems authenticates the user (sometimes ldap) and sends the user details like username and groups information to upstream components. We can have groups role mapping (like ldap one) and groups information in header to map user role accordingly.

Thanks.

**Comment by jgreen210** [comment]
https://github.com/grafana/grafana/pull/6895

**Comment by jgreen210** [comment]
No - it just provides the auth.proxy and auth.ldap integration you mention.

**Comment by chrim5** [comment]
+1 for this feature request.

**Comment by berglh** [comment]
Definitely need to be able to map a comma separated list of Security Groups in a Proxy Auth header to Groups in Grafana to control access to specific data sources/team dashboards etc. This would allow use to do SAML auth at our reverse proxy and pass-through group membership information without having to map users to groups manually. (Just groups to groups).

**Comment by cantino** [comment]
Seconded.

**Comment by sandeepbangera** [comment]
+1

**Comment by kumaravel29** [comment]
+1

**Comment by lfdominguez** [comment]
Please any advance on this??? i need pass the role from my keycloak user to role of grafana user and i can use the generic oauth because that allow users without role login on grafana.

**Comment by hectorjjb** [comment]
+1 Any updates on this?

**Comment by voiprodrigo** [comment]
+1

**Comment by kopaygorodsky** [comment]
+1

**Comment by jvanmalder** [comment]
+1

**Comment by amandeepchugh** [comment]
+1

**Comment by KadenLNelson** [comment]
May we please stop commenting `+1` on this issue? Many of us are subscribed to this issue and don't want to get pinged on unnecessary notifications.

**Comment by diegonc** [comment]
In the [auth proxy](https://grafana.com/docs/grafana/latest/auth/auth-proxy/) documentation there's a setting named `headers` that is not explained later:
```
# Optionally define more headers to sync other user attributes
# Example `headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS`
headers =
```
There's a Groups as example and I'm not sure it solves this issue or is a totally unrelated thing. What's Groups user attribute?

**Comment by sandeepbangera** [comment]
https://grafana.com/docs/grafana/latest/auth/auth-proxy/#team-sync-enterprise-only - This `Groups:X-WEBAUTH-GROUPS`  is only available in the enterprise edition, Also the groups attribute maps to the team the user belongs to.

Ideally we want some proxy header which could map to the Grafana supported roles Admin/Viewer/Editor.

For e.g. `X-WEBAUTH-ROLE=Admin`, Should map the logged in user to the Admin role.

**Comment by hugree** [comment]
Grafana plays nicely with Istio. Always has ;) For that reason the Groups mapping functionality is much needed especially now after Istio's latest External Authorization plugins:
https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

There's no need to use direct OAUTH plugins. Just an authorization proxy which can now be configured directly on Istio. Works like a charm!

But it's getting difficult to explain to my colleagues why all users in our Grafana are now Admins 🙃

**Comment by UXabre** [comment]
Hi,
I'm currently working on a patch for something like this:
https://github.com/grafana/grafana/pull/33162

It has the ability to set a role for an organization (in which the org with 1 is the main one). Perhaps this could fit your needs as well?

**Comment by hugree** [comment]
@UXabre it seems like that would work just fine ;-). Thanks!

**Comment by skaravad** [comment]
@UXabre I build grafana from your repo and tested it, it works like a charm, it took me couple of attempts to understand the header setting (may be it is just me) just to add some details:
`X-WEBAUTH-ORGS "1:Admin"` 
Here `1` is the `OrgId` , it must exist in grafana , `Admin` the Role (quite straight forward) 

Thank you for the feature, really helps us.

**Comment by UXabre** [comment]
Hi @skaravad , thanks for checking it out! I will adjust the documentation to explain this better.

**Comment by UXabre** [comment]
So, as some of you might have seen, this PR has been closed due the assumption that orgs are not needed.
However, it seems that this assumption is based on the fact that most devs thought that, setting a role for an organization was already implemented.
If some of you could chime in on the PR discussion, to voice the importance of such a feature, that would be great, otherwise I fear this might "_die a silent death_" if we can't stress the relevance enough...

**Comment by bputt-e** [comment]
We plan on managing the users assigned to orgs via grafana's api to get around this. Essentially we're limiting everyone in an org to be an editor and are building our own user management feature outside of grafana since it's just username/email. Since our "user management" is essentially listing which groups users are in (managed via a 3rd party), we have to maintain the list of users in grafana because there's always a possibility where they can get out of sync (ex: 24hr cronjob to keep everything up to date).

Understand that grafana is considering changes to orgs and/or wanting to limit this feature to its enterprise-only customers. Just giving my 2c :)

**Comment by sandeepbangera** [comment]
I believe this issue should be closed now.
https://github.com/grafana/grafana/pull/36729/files


Starting Grafana 8.1.x 
```
# Optionally define more headers to sync other user attributes
# Example `headers = Name:X-WEBAUTH-NAME Role:X-WEBAUTH-ROLE Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS`
headers =
```

So you could use the `X-WEBAUTH-ROLE` header to pass the desired role to auth.proxy

**Comment by mac2000** [comment]
Wondering if it will be possible to support comma-separated roles list, e.g.:

```bash
curl -s -H "X-AAD-USERNAME: admin1"  -H "X-WEBAUTH-ROLE: Editor, Admin"    http://localhost:3000/api/user
curl -s -H "X-AAD-USERNAME: admin2"  -H "X-WEBAUTH-ROLE: Admin,Editor"     http://localhost:3000/api/user
curl -s -H "X-AAD-USERNAME: editor1" -H "X-WEBAUTH-ROLE: Foo,Editor, Bar"  http://localhost:3000/api/user
curl -s -H "X-AAD-USERNAME: editor2" -H "X-WEBAUTH-ROLE: Editor"           http://localhost:3000/api/user
```

So admin users in both cases will receive admin roles and editors their editor role

**Comment by TrayserCassa** [comment]
Since group sync is only supported by Enterprise we came up with a solution to use our ingress-nginx in the kubernetes cluster. We used the oauth-proxy with cognito and then added a annotation `configuration-snippet` in the grafana ingress with this configuration:
```        
        auth_request_set $groups $upstream_http_x_auth_request_groups;
        auth_request_set $user $upstream_http_x_auth_request_email;

        access_by_lua_block {
          local role = ""
          if string.find(ngx.var.groups, "grafana%-viewer") then
            role = "Viewer"
          elseif string.find(ngx.var.groups, "grafana%-editor") then
            role = "Editor"
          elseif string.find(ngx.var.groups, "grafana%-admin") then
            role = "Admin"
          else
            ngx.log(ngx.STDERR, "The User " .. ngx.var.user .. " has no permissions for Grafana")
            ngx.redirect("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
          end

          ngx.log(ngx.STDERR, "User: " .. ngx.var.user .. " has grafana role: " .. role)
          ngx.req.set_header("X-Auth-Request-Role", role)
```

The groups are from cognito and you need to configure the oauth proxy properly. To see issues with the header I can advise you to use echoserver, so you can check if grafana gets the correct headers.
