### ISSUE TITLE
[Feature request] Alert notification repeating

### ISSUE THREAD

**Issue by andreioss** [grafana/grafana#8817]
Hello guys!
Sometimes it would be very convenient to do repeated notification of triggered alert.
For instance, I have a lot of emails, chat messages etc, and one simple notification isn't enough to be acknowledge about what happened on the monitored system.
So it should be adjustable option - for which alerts it should repeat notification and how often it should do.
How realistic is this?
Thanks!

**Comment by daniellee** [comment]
This is totally realistic. A feature request exists for this already: #7330
