### ISSUE TITLE
Alerting: Include a list of ref_Id and datasource UID to alerts when state reason is NoData

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#88184]
In Grafana Alerting a rule evaluation can have basically 3 outcomes:
- normal evaluations with results
- no-data 
- error

For the last two outcomes, which are considered as exceptional, Grafana offers options to gracefully handle the result. Such options are: 
- Assume "normal" state for all known states from previous evaluations, e.g. if there are 3 dimensions with current state Alerting and 3 with Normal, all 6 states will be transitioned to Normal, and active alerts are resolved.
- Assume "alerting" state, e.g. the same situation, all normal states will be transitioned to "Alerting" respecting pending interval.
- assume the same state as the current state (aka "Keep Last State"), e.g. all states will be maintained, if pending interval is exceeded alert instance in "Pending" state gets promoted to "Alerting".

The fourth option is "do nothing". In that case, a new alert instance is created in the state "Alerting", which creates special kind of alerts with names DatasourceNoData and DatasourceError. The alerts contain information about data source UID and comma-separated refIDs of queries that returned no data (or error). 

The proposal is to add that information to the first 3 options. The only place that makes sense is to add them to annotations, which will keep the same alert and will be sent to the recipient after a "repeat interval".

**Comment by wasim-nihal** [comment]
Is this open for contribution?
