### ISSUE TITLE
LOcation json dashboard grafana

### ISSUE THREAD

**Issue by Guduowai** [grafana/grafana#8819]
Hello! i'm using grafana in centos 7 , my database is coming from elasticsearch , i need to locate json dashboard on my centos 7 because i need to migrate my grafana to another serevr so i ask if i can do it without repating settings thank's for help

**Comment by daniellee** [comment]
Do you need to move one dashboard or move everything?

**Comment by torkelo** [comment]
Please use community site for questions

**Comment by Guduowai** [comment]
everything i had found file name grafana.db in var/lib/grafana i think i
should move that ?
