### ISSUE TITLE
grafana_session_expiry cookie should be in HttpOnly

### ISSUE THREAD

**Issue by devisyam** [grafana/grafana#88206]
![Screenshot 2024-05-09 164613](https://github.com/grafana/grafana/assets/108857220/23cacbc9-6cd2-41a3-8826-97686379dc6e)

**Why is this needed**:

to enable cookies in httpOnly

**What would you like to be added**:

as shown in the above image i need to enable grafana_session_expiry should get HttpOnly flag   for the above i have used latest grafana opensource image hosted it on linux server i'm wishing to know what configuration should i add to get cookie flag in HttpOnly

**Who is this feature for?**

just learning purpose

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/83810
- [ ] https://github.com/grafana/grafana/issues/83810
```

**Comment by jkroepke** [comment]
If you put the HttpOnly on that cookie, it would break the Frontend of Grafana. Currently, the javascript needs access to that cookie.

https://github.com/grafana/grafana/blob/0ffc4c441b46756fb887ac8f08a6601cc9ebc4d8/public/app/core/utils/auth.ts#L2

**Comment by devisyam** [comment]
hi  @jkroepke thanks and i'm glad  for your response, i have zero knowledge on that can you please tell me how can i enable HttpOnly for the grafana_session_expiry without break of the frontend grafana ,

**Comment by jkroepke** [comment]
Hi @devisyam , this is impossible.

**Comment by devisyam** [comment]
@jkroepke ok atleast tell me what configuration that i need to add for passing the cookies in secure method add those configuration here

**Comment by jkroepke** [comment]
There no config for it

**Comment by devisyam** [comment]
@jkroepke thanks you so much for your response

**Comment by jkroepke** [comment]
Seems like multiple users ask for that feature: https://community.grafana.com/t/limit-user-login-sessions/19788 which is able to achieve yet.

**Comment by devisyam** [comment]
Hi @jkroepke can we get that feature in grafana enterprise ?

**Comment by jkroepke** [comment]
Create a support ticket for that

**Comment by kalleep** [comment]
Hey, as mentioned earlier here by @jkroepke it is not possible to make `grafana_session_expiry` cookie as  HttpOnly. I guess. I guess the the other things you are discussing here is related to https://github.com/grafana/grafana/issues/88321 and is not relevant to this issue

**Comment by vaibhhavv** [comment]
Hi @jkroepke, @kalleep, @Jguer, Do you know any future plans for "`grafana_session_expiry` cookie as HttpOnly"?
Is grafana going to bring this as a feature? If yes, is there any ETA for the same? If not, any specific reason for this, and Is that somewhere documented that I am missing?

**Comment by jkroepke** [comment]
> any specific reason for this

httpOnly means that the browser's JavaScript engine cannot access the cookie. However, by design, Grafana's JavaScript needs access to this cookie, which requires that the httpOnly flag must not be set.

**Comment by vaibhhavv** [comment]
Many thanks @jkroepke for the clarification.
