### ISSUE TITLE
[Feature request] Add option to prevent viewers to share dashboards

### ISSUE THREAD

**Issue by yurihbsis** [grafana/grafana#8821]
Hi!

In our company some Grafana users are doing snapshots and sharing our dashboards without our permission. We already configured their user profiles as "viewers", but as we knew it doesn't sufficient, so they still doing it. 

So will be nice if we have an way to prevent it. It may usefull to others too. 

- Grafana: 4.2.0 (Commit: 349f3eb) 
- Datasource: Zabbix 3.4.0
- OS: CentOS 7

**Comment by Androider03** [comment]
Hi,

I'm experiencing the same issue. It would be useful to disable the "share dashboard" button for specific roles (e.g.: for viewers).

**Comment by liberomic** [comment]
Hi,

I have the same problem, why the user in "read only" export/ create snapshot .... ?

Regards

**Comment by taivorokib** [comment]
Hi,

Totally agree.  With sharing feature they also modify data periods with link. They can see data what is not meant for them.

**Comment by pcsegal** [comment]
I agree - this is an important feature to have.

I see that you can disable _external_ snapshots, according to the following section in the docs: https://grafana.com/docs/installation/configuration/#external-enabled

However, it looks like you can't disable local snapshots, or to disable the option to view/share the dashboard's JSON.

**Comment by tailtNinjavanVN** [comment]
Many people voted.

Why doesn’t the development team make this feature from 2017 to present ?

I will consider purchasing license in the future!

**Comment by robinbraemer** [comment]
It can be disabled for all users (https://github.com/grafana/grafana/pull/2949/files)

**Comment by evictorero** [comment]
We will take care of this effort on this [issue](https://github.com/grafana/grafana/issues/83529)

**Comment by evictorero** [comment]
Only users with edit permissions on a Dashboard will be able to create Snapshots for it.
This change will be released on Grafana 11.

**Comment by aes256ctr** [comment]
Many people voted.
Why doesn’t the development team make this feature from 2017 to present ?
（love from 3 body problem world）
