### ISSUE TITLE
use the OB database as Grafana's database

### ISSUE THREAD

**Issue by yanyanguo** [grafana/grafana#88217]
Attempting to use the OB database as Grafana's database. Currently, the OB version used is the commercial version 4. x
Encountered: ERROR 1235 (0A000): table redefinition and alter options in single state not supported
I would like to ask which file is the SQL statement executed by Grafana when initializing the database? I would like to modify it to a single execution

**Comment by tonypowa** [comment]
Thank you for your question @yanyanguo 

However, GitHub is mainly used for tracking bugs and feature requests. You are welcome to post your question on[ https://community.grafana.com/](https://community.grafana.com/)
