### ISSUE TITLE
[Feature Request] Do not plot query but show in legend

### ISSUE THREAD

**Issue by scotia70** [grafana/grafana#8822]
Hi,

I have data that I wish to show below a graph in the legend (specifically the value of the area under the graph - calculated as max - min of the displayed range, which is useful to see the total data of a data/second derivative graph) - but I do not want it shown graphically as it's orders of magnitude greater than the plotted derivative.
If I choose a line width of 0 and no fill that removes it from the graph however the scale of the graph still caters for it.
Can you please add a feature to show a query on the legend but NOT on the graph?  Maybe create an override where the data is plotted on y-axis #0 (which is not plotted).
Thanks
Scott

**Comment by daniellee** [comment]
This feature has already been implemented, so we’re going to go ahead and close this.

The Hidden Series override does this:

![image](https://user-images.githubusercontent.com/434655/98576898-7c071600-22bb-11eb-8b60-489eceb4a5e8.png)
