### ISSUE TITLE
Bug. Dashboard doesn't work.

### ISSUE THREAD

**Issue by MaksimBalticom** [grafana/grafana#8823]
- What Grafana version are you using?
Version 4.3.2 (commit: ed4d170)
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
CentOS7
- What did you do?
Downloaded Revision number 3 from here: https://grafana.com/dashboards/1124/revisions to test dashboard. Then I imported the dashboard and changed job="snmp" to job="$model" where $model is my variable. 
- What was the expected result?
To see a list of IP addresses. 
- What happened instead?
But suddenly a drop-down list of IP addresses disappeared. Now I have two dashboards with completely the same config but the result vary. In the first one I do have a list of IP addresses, but in the second one - don't. I exported my dashboards, deleted them and imported again - same result. Please see my attachments. Hope someone can explain this. Thank you.
[dashboards.zip](https://github.com/grafana/grafana/files/1138142/dashboards.zip)

**Comment by torkelo** [comment]
Please use community site for questions, there is also a how to section with tips for how to troubleshoot metric query issues. 

You can investigate the query sent to Prometheus and its response for example. 

Also check the model variable options, is the query set to refresh on dashboard load? If multi or all is enabled you should use regex operator in query label value filter condition
