### ISSUE TITLE
Query type selection for Google Cloud Monitoring not working

### ISSUE THREAD

**Issue by GedPL** [grafana/grafana#88233]
### What happened?

![image](https://github.com/grafana/grafana/assets/31762538/dcc31fd1-7156-4386-9255-eee4bc4a71a0)

When selecting query type (for example: MQL, PromQL) nothing happens

### What did you expect to happen?

Grafana should switch to query editor (in this case when switching from Builder to PromQL)

### Did this work before?

yes, 10.4.2

### How do we reproduce it?

1. Add Google Cloud Monitoring data source
2. Create new visualization
3. Try to change Query type

### Is the bug inside a dashboard panel?

yes, in edit mode

### Environment (with versions)?

Grafana: 11.0.0
OS: Red Hat 8
Browser: Chrome Version 125.0.6422.76 (Official Build) (64-bit)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Google Cloud Monitoring

**Comment by bfoder** [comment]
The same issue occurs in grafana cloud (ver. Grafana v11.1.0-70903 (778d9eb69d))

**Comment by GedPL** [comment]
> The same issue occurs in grafana cloud (ver. Grafana v11.1.0-70903 ([778d9eb](https://github.com/grafana/grafana/commit/778d9eb69d033dd33e5215d6c53687875082a132))).
> 
> Additionally `Filters` section in query editor is not responsive too.

Confirming, clicking  + button - no effect.
![image](https://github.com/grafana/grafana/assets/31762538/abd57ff0-1ec4-4c65-944d-13278e300cd9)

**Comment by MiticoBerna** [comment]
Me too, it seems every dropdown or button of CloudMonitoring panel is not working with Grafana 11.

**Comment by venu-shapley** [comment]
Same here. I cannot change the Query Type directly. Have to navigate to an alternate tab like the Transformations tab and then come back to the Query tab and then I can see the query type changing. When I finally change to the PromQL query type, I cannot type into the query text box (unless i navigate to the Transformations tab and back)

With the Filters, I am unable to see any values for the labels either.

**Comment by eraac** [comment]
The whole query builder for GCP is bugged, we have rollback to 10.4.4 the bug is still present, 10.4.1 seems good ...

**Comment by odam06** [comment]
Same here, problem exist on v11.0.0 and v10.4.3 (10.4.2 works well)

**Comment by venu-shapley** [comment]
If I am using Grafana Cloud, is it possible to rollback to an earlier version?

**Comment by venu-shapley** [comment]
Hi, just checking to see if there is a workaround for this issue if I am on grafana cloud?

**Comment by andaag** [comment]
Has anyone successfully rolled back? Any database changes we should worry about in 11?

GCP metrics is functionally completely broken for us.

**Comment by odam06** [comment]
We did it on our staging deployment which seems to work well. 
But we'll not rollback it on prod because it's currently not impacting our alerting and dashboard.
We're waiting for a fix

**Comment by griseau** [comment]
Facing the same issue on our side with Grafana 11.0

**Comment by GedPL** [comment]
Additionally I've found one more problem with adding labels for grouping/filtering to existing query.
For example I have 4 labels:
metric.label.queue
metric.label.status
metric.label.dc
metric.label.result
First I've created query using two of above in group by (metric.label.dc and metric.label.status) and I've saved my dashboard.
Then I've tried to edit above wanted to add metric.label.queue and metric.label.dc but they are not shown in Filter/Group by dropdowns. Seems like occurs even with Grafana 10.4.2.

Anyone can confirm ?

**Comment by kyleabenson** [comment]
Hi folks, just wanted to drop a note here, specifically on the dropdown picker issue originally scoped to this issue. I'm from the Google Cloud Monitoring team and we've reached to our contacts at Grafana to see if we can track down the issue here.

**Comment by NEKOYASAN** [comment]
Same issue on v11.0.0 OSS. We've downgraded to v10.4.2 (works well)

Default project settings (datasource setting) and all drop down menus are unavailable as well.

Also, even after I managed to select MQL in the query type selection drop-down menu, I cannot enter MQL. (The input screen appears, but the query cannot be entered)

**Comment by venu-shapley** [comment]
Things seem to be working on Grafana v11.1.0-71799 (3a8b59f5e8).

**Comment by BossaGroove** [comment]
Confirmed not working in v11.1.0-71921
<img width="1422" alt="image" src="https://github.com/grafana/grafana/assets/614068/3fce806c-dfa5-470c-8197-c0dbe21f00c2">

**Comment by kyleabenson** [comment]
Hey folks, our contact at Grafana told us this should be fixed [here](https://github.com/grafana/grafana/pull/87990), a big thanks to the Grafana team but if you're still experiencing an issue post that fix be sure to follow up!

**Comment by GedPL** [comment]
Thanks @kyleabenson !
So closing this thread to avoid duplicates.
Anyone interested in issue resolution please check [https://github.com/grafana/grafana/pull/87990].
Many thanks for all messages !
