### ISSUE TITLE
Plot Data Over A Fixed Data Set

### ISSUE THREAD

**Issue by andrew-arc-boats** [grafana/grafana#88239]
**Why is this needed**:

In many cases it is helpful to be able to plot data over an expected data set. For example, comparing the result of a calibration process against the expected result.

**What would you like to be added**:

I would like the ability to plot data from a database against a known dataset. It would also be acceptable to plot the data over a background image of that dataset.

**Who is this feature for?**

Test engineers and technicians, hardware development engineers, and service technicians.

**Comment by leeoniya** [comment]
are you talking about non-timeseries data?

do both the expected and actual datasets have the same number of points? if not, how are they to be aligned?

can you attach an example of an expected and actual dataset and what panel you'd like to use?

**Comment by andrew-arc-boats** [comment]
The use case I was thinking of would be for timeseries data. The actual and expected data sets could have a different number of points.

Here is an example use case: I have some timeseries data that contains current and torque measurements from a test that was run on an electric motor. The specs for the motor say that the torque produced should be 0.75 times the current and I want to validate that my test results match this. To do this I want plot the current and torque measured during the test (`torque_actual` vs `current_actual`) against an expected dataset (`torque_ref` vs `current_ref`).

The test data (`torque_actual` and `current_actual`) is pulled from a database using a SQL query. It is about an hour in length and contains 60k data points per channel. The expected relationship between current and torque is known and I use that to define a "reference" dataset shown below.
`current_ref = [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];`
`torque_ref = [-7.5, -6.75, -6, -5.25, -4.5, -3.75, -3, -2.25, -1.5, -0.75, 0, 0.75, 1.5, 2.25, 3, 3.75, 4.5,  5.25, 6, 6.75, 7.5];`

I create a scatter plot panel that plots `torque_actual` vs `current_actual` and `torque_ref' vs `current_ref' on the same plot. Producing something like what I have below.
![image](https://github.com/grafana/grafana/assets/122923385/471652bb-f532-4b8b-8c2d-85b8f17bbad8)

**Comment by leeoniya** [comment]
ok, thanks.

so, this isn't really a timeseries use case. even if your measurement have timestamps they're irrelevant here.

we have an XYChart panel for the above scatter use case. your reference dataset here looks pretty linear and likely representable with 2 points. so you can actually embed it in the panel itself using the `testdata` datasource and the "CSV content" scenario, which would give you the red line. you can then do a regular query to your SQL source to get the actual points and plot them as a second series.

i would recommend trying the [nightly build](https://grafana.com/grafana/download/nightly?edition=oss) of grafana, enabling the `autoMigrateXYChartPanel` [feature flag](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles), and trying out XYChart.

**Comment by andrew-arc-boats** [comment]
I have other use cases that have more of a sigmoid shape that require more data points to plot. I am aware of the XY chart panel but I am not aware of a feature that will allow me to plot a fixed dataset on it.

**Comment by leeoniya** [comment]
> I am aware of the XY chart panel but I am not aware of a feature that will allow me to plot a fixed dataset on it.

as mentioned above, the TestData data source allows you to embed a dataset into the panel json:

> [TestData data source](https://grafana.com/docs/grafana/latest/datasources/testdata/) and the "CSV content" scenario
