### ISSUE TITLE
[Feature request] Add shuffle play mode to playlist

### ISSUE THREAD

**Issue by jehutywong** [grafana/grafana#8824]
when I have a long play list, those latter dashboards will have less chance to be played, due to various unexpected interruptions. Shuffle play should help in this case.

Thanks,

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
