### ISSUE TITLE
[Bug] embedding via iframe: vertical scroll bars show up if using y axis labels

### ISSUE THREAD

**Issue by skladd** [grafana/grafana#8827]
Grafana version: 4.4.1
For graph panels, the y axis labels get rotated and translated via [CSS](https://github.com/grafana/grafana/blob/f8d22385ce7a233e0dc7e7e599aec8094a45faad/public/sass/components/_panel_graph.scss#L322) so that the height of the page becomes at least about 150% of its width. Thus empty space is added to the embedded page and vertical scroll bars appear.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
