### ISSUE TITLE
[Bug] IP displayed as integer in Templating variable

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#8829]
- What Grafana version are you using?
4.2
- What datasource are you using?
Elasticsearch 2.4
- What OS are you running grafana on?
Win 2012 R2
- What did you do?
Create a variable to retrieve an IP field from Elasticsearch. The IP field is mapped as IP type
- What was the expected result?
Values should be in IP format
- What happened instead?
Values are in integer format. Graph and table panels display the IPs correctly.

Variable query: {"find": "terms", "field": "src_ip"}

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/e4950c2dc1012cb1a36cca947666244417e56194
