### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by MahekPavagadhi** [grafana/grafana#8831]
I have my panel ready but there is some issue while deploying. I think some build script issue. Can you guide me through it? 

There is not much thing I found in here related to that : http://docs.grafana.org/plugins/developing/development/

**Comment by MahekPavagadhi** [comment]
Do I need to duplicate all the files and keep in **dist** folder? @daniellee

**Comment by daniellee** [comment]
I'm not sure - depends on how you have set up your code. How it works with the dist folder is described [here](http://docs.grafana.org/plugins/developing/development/#start-developing-your-plugin). If a dist folder exists then Grafana will load the files there. If it does not exist then Grafana will load the files from the root. The reason for having a dist folder is if you have a build step and want to keep your source files separate from your production files (which might be compiled from ES6 or typescript).

This sounds like a question for the community site: https://community.grafana.com so closing this issue.
