### ISSUE TITLE
Cloudwatch logs: "show context" doesn't handle region as a variable correctly

### ISSUE THREAD

**Issue by njvrzm** [grafana/grafana#88310]
### What happened?

If you create a logs dashboard using a template variable for `region`, then click "show context" on a log line, the query that is sent includes the uninterpolated variable instead of the chosen region. No log lines are returned, of course.

### What did you expect to happen?

The region variable should be interpreted in the "show context" query, so that context can be shown.

### Did this work before?

Unknown

### How do we reproduce it?

1. Set up a dashboard with the Logs visualization and Cloudwatch Logs as the data source.
2. Create a dashboard variable for the AWS region
3. Use the dashboard variable for the region setting in the viz query
4. Click on the Show context icon on a line

### Environment (with versions)?

n/a

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

cloudwatch

**Comment by idastambuk** [comment]
@ErnestineMoreno we just moved it to Next, to be picked up in the next few weeks :)
