### ISSUE TITLE
Reordering alerts when a filter is applied deletes all other alerts

### ISSUE THREAD

**Issue by ncFoCo** [grafana/grafana#88314]
### What happened?

Reordering alerts when a filter is applied causes all other alerts to get dropped.  

https://github.com/grafana/grafana/assets/3170382/3c0ac578-88e6-412c-adc0-4e5f413053f9  

### What did you expect to happen?

I expected the filtered alerts to be reordered while not affecting any other alerts on the system.  

### Did this work before?

I am not sure, this is our first install of Grafana and we are starting at `Version 11.0.0 (commit: 277ef258d4b9a5acdf2932347c6a4ca72d739b28, branch: HEAD)`.  

### How do we reproduce it?

1. Select the Alert Rules tab.
2. Filter alerts to a specific dashboard.
3. Select the reorder rules icon.
4. Reorder any rule.
5. Clear the current filter.
6. All alerts that were not associated with the filtered dashboard will be gone.  

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Version 11.0.0 (commit: 277ef258d4b9a5acdf2932347c6a4ca72d739b28, branch: HEAD)
OS:  Red Hat Enterprise Linux release 8.9 (Ootpa)
Browser: Chrome Version 125.0.6422.112

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

influxdb2@2.7.6-1

**Comment by CrustyPistachio** [comment]
Fixed in #88221 and available in v11.1.

**Comment by tonypowa** [comment]
Thanks to @ncFoCo  for creating this issue and to @CrustyPistachio  for sharing the link to the fix
Closing issue. Feel free to comment if the issue persist after upgrading to v11.1
