### ISSUE TITLE
Snapshots broken for users with "Viewer" permission in Grafana 11

### ISSUE THREAD

**Issue by NielsH** [grafana/grafana#88326]
### What happened?

After updating  to Grafana 11, users with the "Viewer" permission can no longer create snapshots.
This appears to be caused by this: https://github.com/grafana/grafana/pull/84952

Our usecase is that we have a few people that create dashboards (Editors / Admins) and we have other users that are only allowed to view these dashboards, but we do not want them to edit the dashboards or create their own.  
They are however permitted to create snapshots of our dashboards/panels that they can share with 3rd parties that do not have an account in our Grafana instance.

Since Grafana 11 this no longer works. It appears to be an intended change, but in order to fix it I now have to give way more permissions (Editor) to our users just to get them to be able to make snapshots again.

### What did you expect to happen?

I expected the snapshots to still work for viewers, or be configurable to allow this if the default is to now to disallow the snapshots.

### Did this work before?

Yes, before Grafana 11

### How do we reproduce it?

1. Be a user with Viewer permissions
2. Try to share the dashboard/panel
3. the Snapshot button is missing

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11
OS: N/A
Browser: N/A

### Grafana platform?

A downloaded binary

### Datasource(s)?

N/A

**Comment by vtorosyan** [comment]
@grafana/sharing-squad could you please triage this?

**Comment by evictorero** [comment]
This was an intended change to [remove the ability of viewers to share a dashboard using snapshots publicly](https://github.com/grafana/grafana/issues/8821). 
We should add a specific RBAC permission to create snapshots to support this use case so the admin can grant it to a viewer user.

**Comment by kevinnoel-be** [comment]
We have the same issue, as we're using Grafana OSS we (AFAIK) don't have many RBAC controls and clearly cannot promote all of our users to editors or admins.

**Comment by consideRatio** [comment]
Having documentation about how to opt-in to providing snapshot permissions to a role, like the Viewer role, would be great. This is a goal for me currently and I'm not sure how to do it (grafana deployed via the grafana helm chart).

**Comment by evictorero** [comment]
This change was made to fulfill an old feature request from the [community](https://github.com/grafana/grafana/issues/8821).
It makes sense to remove this ability for Viewer users since we don't want to allow viewers to create resources in the Grafana Instance and potentially share sensitive data. 
It isn't easy to fulfill every use case with only 3 roles (Viewer, Editor, and Admin), which is why we have RBAC to have more control over permissions.
I'm sorry to hear this broke your particular use case, but Viewers shouldn't be able to create resources, and the main goal of this change was to improve the security of Grafana.

**Comment by Novichuk94** [comment]
Is the snapshot feature tied to organization role-based permissions?
We have a user who is a Viewer but is part of a team with Editor permissions. However, he can't create a snapshot (the option is missing) for a dashboard that he built. I can, as an admin.
