### ISSUE TITLE
[Bug] Amounts of redirection，error=Failed to start session

### ISSUE THREAD

**Issue by An0nymous0** [grafana/grafana#8833]
os:
centos + docker + grafana 4.4.1

error message:
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=61.50.103.90 time_ms=0 size=29 referer=
t=2017-07-12T02:04:50+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/7/4/744704da14503647: operation not permitted"
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=61.50.103.90 time_ms=6 size=24 referer=
t=2017-07-12T02:04:50+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/7/4/744704da14503647: operation not permitted"
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=61.50.103.90 time_ms=0 size=29 referer=
t=2017-07-12T02:04:50+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/7/4/744704da14503647: operation not permitted"
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=61.50.103.90 time_ms=8 size=24 referer=
t=2017-07-12T02:04:50+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/7/4/744704da14503647: operation not permitted"
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=61.50.103.90 time_ms=0 size=29 referer=
t=2017-07-12T02:04:50+0000 lvl=eror msg="Failed to start session" logger=context error="chtimes /var/lib/grafana/sessions/7/4/744704da14503647: operation not permitted"
t=2017-07-12T02:04:50+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=61.50.103.90 time_ms=8 size=24 referer=

chmod 777 /var/lib/grafana/      Not solved

**Comment by torkelo** [comment]
Looks like grafana cannot write to data volume, how did you start container?

**Comment by An0nymous0** [comment]
`docker run --name study-grafana -v /home/data/dockerwork/study-grafana:/var/lib/grafana -p 3000:3000 -d grafana/grafana:latest`

`docker exec -it study-grafana chmod 777  /var/lib/grafana`

**Comment by torkelo** [comment]
you need make sure the grafana user has access to /var/lib/grafana

**Comment by An0nymous0** [comment]
To establish grafana users on the host machine？

**Comment by torkelo** [comment]
The OS (Linux) user that is running grafana server, the Deb install package creates a grafana user, and the container start script starts grafana under this user
