### ISSUE TITLE
The image is rendered with the sidebar of Grafana, how to remove it?

### ISSUE THREAD

**Issue by giuliomagnifico** [grafana/grafana#88344]
**What happened**:

The image include the sidebar of Grafana and I want to remove it, see the image below:

![casetta-mimir](https://github.com/grafana/grafana-image-renderer/assets/1975176/6ea99776-516a-43b2-abc9-7bc027c000cd)

**What you expected to happen**:

Image without sidebar

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: 3.9.0
- Grafana version: latest
- Installed plugin or remote renderer service: 
- OS Grafana Image Renderer is installed on: Raspberry PI 4B
- User OS & Browser: DietPI
- Others:

**Comment by lucychen-grafana** [comment]
Closing as there is no further action.
