### ISSUE TITLE
Alerting API: documentation mismatch implementation

### ISSUE THREAD

**Issue by kwarunek** [grafana/grafana#88358]
### What happened?

From the documentation https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idtime-rangespan-timerange I assume that to create a mute timing I need to invoke:

```
curl -v -H 'Authorization: __REDACTED__' -H'Content-Type: application/json' http://grafana:3000/api/v1/provisioning/mute-timings -XPOST -d \
'{"name": "ignore-failed", "time_intervals": [{"days_of_month": [], "months": [], "times": [{"EndMinute": 1400, "StartMinute": 1000}], "weekdays": [], "years": []}]}' 
```
but it returns bad request.
The valid (that creates  a timing) request actually looks like
```
curl -v -H 'Authorization: __REDACTED__' -H'Content-Type: application/json' http://grafana:3000/api/v1/provisioning/mute-timings -XPOST -d \
'{"name": "ignore", "time_intervals": [{"days_of_month": [], "months": [], "times": [{"end_time": "24:00", "start_time": "18:00"}], "weekdays": [], "years": []}]}' 
```

### What did you expect to happen?

I expect that documentation should describe required object (field names, types) by the API (openapi would be great)

### Did this work before?

idk

### How do we reproduce it?

simple curl

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.1
OS: Linux

### Grafana platform?

Kubernetes

**Comment by kwarunek** [comment]
Probably another issue is that I'm unable to set location (as string Europe/Warsaw) even with Grafana UI
```
{
	"mute_time_intervals": [
		{
			"name": "off-business-hours",
			"time_intervals": [
				{
					"location": "Europe/Warsaw",
					"times": [],
					"weekdays": [
						"saturday",
						"sunday"
					]
				},
				{
					"location": "Europe/Warsaw",
					"times": [
						{
							"end_time": "24:00",
							"start_time": "17:00"
						},
						{
							"end_time": "07:59",
							"start_time": "00:00"
						}
					]
				}
			]
		}
	]
}
``
it returns with every tz
```
{"message":"bad request data","traceID":""}
```

**Comment by tonypowa** [comment]
hi @kwarunek 

Thank you for reporting this bug

I have reproduced it from my end.
I will add this issue to the team's board while we will update the docs

**Comment by kwarunek** [comment]
@tonypowa Yep the second example - my bad copy&paste from the internal logging system, of course it should be w/o that wrapper.  But to the point - I have managed to have working tz select - in our setup tzdata package was missing in the system.

Still doc vs examples do not match, thanks for taking your time.
