### ISSUE TITLE
Inappropriate status code when trying to delete an alert contact point

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#88356]
### What happened?

![image](https://github.com/grafana/grafana/assets/36128312/f2463ca3-384d-4989-9643-6ffe80d75c8d)
When trying to delete contact points using Grafana API 'DELETE /api/v1/provisioning/contact-points/', 500 is returned when contact points is used by a notification policy. This is due to user error so 500 is inappropriate to be returned.

### What did you expect to happen?

User error status code returned.

### Did this work before?

na

### How do we reproduce it?

1. Use 'DELETE /api/v1/provisioning/contact-points/' to delete a contact point that is used by a notification policy
2.
3.

### Environment (with versions)?

Grafana: 9.5.17
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
hello @MingjieZhuEmily 
Thank you for reporting this bug

I have reproduced it when attempting to delete a contact point that was in use and received this other message with status 500, which is also incorrect to return.

![image](https://github.com/grafana/grafana/assets/45235678/8672d105-f92c-45c8-9b18-0b91e16e305c)
