### ISSUE TITLE
[HOW TO] Use Data from other Dashboard ?

### ISSUE THREAD

**Issue by SlodeSoft** [grafana/grafana#8836]
Hello, 

I created a dashboard with some diffrent Single Stat. (With MySQL datasource.) Each single in this dashboard is a "Select COUNT(*) FROM ...," so i get differents numbers.
I want to get a sum of this differents "SELECT COUNT(*)", in a new dashboard ?

How can i do ? 

Thanks in advance.

**Comment by torkelo** [comment]
please use community site for questions. This is in the new issue template, please read this next time :) 

To answer your question, you have to combine all the queries into one, there is no way to reuse or refer to queries in other panels or dashboards

**Comment by SlodeSoft** [comment]
The problem is that my SELECT COUNT(*) comes from diffrent database. 
I don't understand how i can use multiple datasources in one Frame.
