### ISSUE TITLE
How to calculate between 2 metrics from 2 different type of data sources

### ISSUE THREAD

**Issue by kantsuw** [grafana/grafana#8837]
Grafana version 4.2.0

I have 2 metrics let call it metric A and metric B

Metric A is the value that come from ElasticSearch
Metric B is the value that come from Graphite

Is there anyway to calculate between them like A+B or A/B on the Grafana ?

**Comment by torkelo** [comment]
please use community site for questions :) 

There is a feature request that we hope to do some day that will solve your use case
https://github.com/grafana/grafana/issues/3677
