### ISSUE TITLE
Stat: Chart disappear on browser tab change

### ISSUE THREAD

**Issue by Develer** [grafana/grafana#88388]
The chart on Stat panel disappeared on browser tab change and back.

https://github.com/grafana/grafana/assets/1418924/1120f267-5496-4e3c-be9c-19b322388707

**Comment by leeoniya** [comment]
i think it's this: https://issues.chromium.org/issues/328755781

https://github.com/grafana/grafana/issues/4378#issuecomment-2122970763

which is fixed now. (there's an incident channel on slack discussing it)
