### ISSUE TITLE
[Feature Request] Allow selection of multiple time intervals

### ISSUE THREAD

**Issue by swaranga** [grafana/grafana#8838]
Sometimes I have a need to plot how a metric has changed day-over-day or week-over-week or even month-over-month. Currently this is not possible since I can only select one time range for a dashboard. 

Allowing multiple-time ranges will allow me to plot say JVM heap memory usage week over week and if and when I push a change that increase my heap memory usage of my application it will be easy for me to find exactly what change introduced the regression.

Additionally a lot of business metrics are reviewed not in isolation but like week/month/quarter/year over week/month/quarter/year respectively.

**Comment by daniellee** [comment]
There are several options for time shifting. Per panel support is in Grafana and depending on the tsdb that you are using there is support for time shifting at the query level too ([Graphite has a timeshift function](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.timeShift)).

http://docs.grafana.org/reference/timerange/#panel-time-overrides-timeshift
