### ISSUE TITLE
Docker - missing arm64 and v7 image

### ISSUE THREAD

**Issue by corasaniti** [grafana/grafana#88393]
### What happened?

The following architectures are missing in the latest tag

linux/arm/v7
linux/arm64

I can only extract the linux/amd64 but on my Raspberry I get the following error

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### What did you expect to happen?

Get correct image for architecture

### Did this work before?

11.0

### How do we reproduce it?

1. pull latast tag docker images from Raspberry
2. start docker images
3. get error
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### Environment (with versions)?

Grafana: 11
OS: Raspian
Browser:

### Grafana platform?

None

**Comment by No13** [comment]
This was also the only tag not pushed by the 'usual' user (grafanaci)

**Comment by corasaniti** [comment]
@No13 
You have a good eye. It was pushed by **kminehartgrafana**
Most likely it was a mistake and I think it will be removed
Thanks

**Comment by S474N** [comment]
Same problem here: https://github.com/grafana/grafana/issues/88390
