### ISSUE TITLE
Docker - missing arm64 image

### ISSUE THREAD

**Issue by S474N** [grafana/grafana#88390]
### What happened?

![image](https://github.com/grafana/grafana/assets/16512337/4267c670-0f88-47e0-9e1e-732d3538c2e0)

![image](https://github.com/grafana/grafana/assets/16512337/2f6081e7-35d2-4fda-ae23-8611b970348b)

### What did you expect to happen?

Download and run arm64 based image.

### Did this work before?

No

### How do we reproduce it?

1. `grafana:latest`
2. PULL
3. UP

### Environment (with versions)?

Grafana: latest docker image
OS: Raspbian newest

### Grafana platform?

Docker

**Comment by corasaniti** [comment]
Same error here

**Comment by tonypowa** [comment]
hi @S474N 

Thank you for reporting this issue

I am closing this one, and forwarding #88393 to the team for review
