### ISSUE TITLE
[Bug] Auth proxy in combination with multiple ldap servers always fails

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#8839]
* What Grafana version are you using?
4.4.1
* What datasource are you using?
N/A
* What OS are you running grafana on?
Centos
* What did you do?
Add one more ldap server to our existing Grafana installation, which also uses auth-proxy to login wall-mounted tv-screens around the office
* What was the expected result?
Everything should continue working for the screens
* What happened instead?
This text is on all our screens:
>Server side error :(
>Unable to authenticate user
In the server logs, this appears:

```
t=2017-07-12T09:17:10+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/dashboard/db/REMOVED status=500 remote_addr=REMOVED time_ms=1597 size=401 referer="REMOVED"
t=2017-07-12T09:17:29+0000 lvl=info msg="Searching for user's groups" logger=ldap filter="(member:1.2.840.113556.1.4.1941:=REMOVED)"
t=2017-07-12T09:15:50+0000 lvl=eror msg="Failed searching for user in ldap" logger=ldap error="Invalid Username or Password"
t=2017-07-12T09:15:50+0000 lvl=eror msg="Unable to authenticate user" logger=context error="Invalid Username or Password"
```

Looking though the code, the issue appears to be [here](https://github.com/grafana/grafana/blob/v4.4.1/pkg/middleware/auth_proxy.go#L109):

```
for _, server := range ldapCfg.Servers {
        auther := login.NewLdapAuthenticator(server)
        if err := auther.SyncSignedInUser(query.Result); err != nil {
return err
        }
}
```

Since we have multiple servers in our `ldapCfg`, this will search all of them, and unless the user is present in all of them, it will fail. 

I tried working on a PR for this, but it is not as simple as to just see if any of the servers succeed, since there could be many types of errors. Additionally, `SyncSignedInUser` mutates the database, so what should happen if the same username is present in multiple ldap sources? 

Another thing which threw my investigation off track for a while was that this was logged as "Invalid Username or Password", which is chosen as the error [here](https://github.com/grafana/grafana/blob/v4.4.1/pkg/login/ldap.go#L391) when there are no matches for the search.

I'd be happy to help fix these issues, but there probably needs to be some discussion first about what a proper fix is.

**Comment by oeyeguokan** [comment]
I am having the same issue, wondering if any progress has been made on this issue

**Comment by jessabe** [comment]
Hej alla. We've fundamentally have changed the way this works in Grafana, so hopefully this bug should be squashed now. But let us know if you're still having problems and we'll reconsider opening this :) Thank you for submitting this!
