### ISSUE TITLE
[BUG] text display error in Alertlist plugin

### ISSUE THREAD

**Issue by wait-io** [grafana/grafana#8840]
- What Grafana version are you using?
Version 4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB 1.2.4

- What OS are you running grafana on?
Red Hat Enterprise Linux Server release 6.8

- What did you do?
created Alertlist with 3 Alerts.

- What was the expected result?
Display of configured alerts with times since last state change
example: "OK for 5 hours"

- What happened instead?
On Windows Systems with DE locale browsers (tested with IE 11, Firefox and Chrome) it displays the alerts with time since last state change but part of the text is in german.
example: "OK for vor 5 Stunden"
note the repetition "for" in englisch followed by the german translation "vor"
For some alerts, it displays "OK for in 5 Stunden" which is also wrong.
Everything else in my dashboards is englisch as expected.

**Comment by daniellee** [comment]
The problem seems to be that MomentJS returns the date in its "fromNow" format in German text [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/alertlist/module.ts#L128). Definitely a bug.
