### ISSUE TITLE
"Server side error :( login.OAuthLogin(NewTransportWithCode)" in Google OAuth login from Grafana 

### ISSUE THREAD

**Issue by shashanks93** [grafana/grafana#8842]
I'm Using Grafana 4.3.2 and using Google Outh for login.
I've made the following changes in defaults.ini file : 

`
#################################### Server ##############################
[server]
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr =

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = ${DOMAIN}

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url
#root_url = %(protocol)s://%(domain)s:%(http_port)s/
root_url = %(protocol)s://%(domain)s/

# Log web requests
router_logging = false

# the path relative working path
static_root_path = public

#################################### Google Auth #########################
[auth.google]
enabled = true
allow_sign_up = true
client_id = ***********
client_secret = ******
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
api_url = https://www.googleapis.com/oauth2/v1/userinfo
allowed_domains = mistsys.com mist.com
hosted_domain =
`
I'm not able to figure out what's wrong am i doing ?

**Comment by torkelo** [comment]
what does grafana.log say?

**Comment by torkelo** [comment]
closing due to lack of update/details

**Comment by matevarga** [comment]
I experienced the same problem with Google SSO. Grafana log:
````t=2017-10-16T07:04:56+0000 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\n  \"error\" : \"invalid_client\"\n}"```

I guess

**Comment by Turing-Chu** [comment]
#### did someone saw this error?
```
t=2017-12-28T16:41:35+0800 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"message\":\"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.\",\"hint\":\"Authorization code has been revoked\"}"
```
