### ISSUE TITLE
Elasticsearch: Support moving average on doc count

### ISSUE THREAD

**Issue by linebp** [grafana/grafana#8843]
As far as I can tell there is no support for a moving average on the count metric in the Grafana interface.
Elasticsearch describes how to use it [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-pipeline.html#_special_paths). Instead of pathing to a metric in the `buckets_path`, there is a special path `_count`, that will use the document count as input for the moving average.

**Comment by markvincze** [comment]
I was surprised by this, and discovered only by accident that the Moving Average works if you use Unique Count instead of simple Count.
