### ISSUE TITLE
the default prometheus dashboards does not work when prometheus is monitoring another prometheus

### ISSUE THREAD

**Issue by agaengel** [grafana/grafana#8844]
as said in the title a prometheus instance monitoring another prometheus will not work as expected with the default dashboard

**Comment by torkelo** [comment]
why? Can you describe what is wrong?

**Comment by agaengel** [comment]
The three singlestat panels in the first row have a "multiple series error" and the other panels mix the data from several prometheus instances which is not making that much sens.

It happens when you start a prometheus instance that collects /metrics from more than one instance.

To solve this issue I opened the pull request 8845 where I added templating where you can select the node to show.
