### ISSUE TITLE
Explore/Logs: Visually indicate split views originating from the logs panel

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#88460]
### Problem to solve: 
If a user clicks on a data link inside the log details, and a new split view would open, users lose context which of the log lines on the left was clicked on.

### Solution:
Visually indicate which line was used to open a split view. A possible way to do so is by indicating it with a certain background color, that is easily identifiable and stays attached to the logline in order to help the user identify the origin. Another possible way is to use the WIP log line pinning feature (WIP PR: https://github.com/grafana/grafana/pull/88316) and see if that can help not losing context.

**Comment by gtk-grafana** [comment]
After quick discussion with the squad, we suggested that this feature should:
* Clicking on a derived field will automatically pin the log line
* Pinned log lines are given a UI treatment, similar to how log lines are pinned in the logs panel after closing the log context menu
<img width="919" alt="image" src="https://github.com/grafana/grafana/assets/109082771/f9986f1a-46b6-45cd-ad95-0715226a847a">
