### ISSUE TITLE
Users: Add config option to control how often last_seen is updated

### ISSUE THREAD

**Issue by kalleep** [grafana/grafana#88471]
We should introduce a config option to control of often `last_seen_at` field is updated for a user. Right now this is a [hard coded value ](https://github.com/grafana/grafana/blob/main/pkg/services/user/userimpl/user.go#L312)

Something like:
```
[users]
last_seen_update_interval = 15m
```

In https://github.com/grafana/grafana/pull/88461 we change this to 15 minutes so this should be the default value.

**Comment by parambath92** [comment]
Is this open for contribution ?

**Comment by kalleep** [comment]
@parambath92 Yes it is. I can assign you to this issue. Feel free to reach out if you have any questions :)

**Comment by yogesh1801** [comment]
Can i contribute?

**Comment by kalleep** [comment]
@yogesh1801 I have already assigned this issue, thanks anyway
