### ISSUE TITLE
[Bug] [Alerting] legend text disappeared from graph screenshot

### ISSUE THREAD

**Issue by delgod** [grafana/grafana#8847]
## Description:
text information (graph title, legend, axes labels) was fine in v4.1.1.
![screenshot 2017-07-12 19 04 33](https://user-images.githubusercontent.com/303592/28127400-1cd89900-6735-11e7-9457-1e6da791c585.png)

but become broken in v4.2.0 and still broken in v4.4.1
![screenshot 2017-07-12 19 05 06](https://user-images.githubusercontent.com/303592/28127408-21edada4-6735-11e7-9f85-91bc63cb3d77.png)
as you can see - graph don't have graph title, legend and axes labels anymore.

## STR:

1. configure SMTP settings in grafana.ini
2. configure email notification channel
3. create new dashboard
4. add one graph
5. set `node_load1{instance=~"NODE_NAME"}` as Query
6. save
7. add alert with the following condition
 `WHEN avg () OF query (A, 5m, now) IS ABOVE 1`
8. add notification channel for this alert
9. save
10. wait for 5 minutes
11. run
  `fulload() { dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null & }; fulload; read; killall dd`
12. wait for 5 minutes
13. check email

## Expected result:
graph screenshot with rightly rendered text

## Current result:
nothing printed where text should be

## Information:
- What Grafana version are you using?
labels are shown  fine on 4.1.1
and don't work on >=4.2.0
   
- What datasource are you using?
Prometheus

- What OS are you running grafana on?
CentOS 7

- dashboard JSON
`{
  "annotations": {
    "list": []
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "hideControls": false,
  "id": 30,
  "links": [],
  "rows": [
    {
      "collapse": false,
      "height": "250px",
      "panels": [
        {
          "alert": {
            "conditions": [
              {
                "evaluator": {
                  "params": [
                    1
                  ],
                  "type": "gt"
                },
                "operator": {
                  "type": "and"
                },
                "query": {
                  "params": [
                    "A",
                    "5m",
                    "now"
                  ]
                },
                "reducer": {
                  "params": [],
                  "type": "avg"
                },
                "type": "query"
              }
            ],
            "executionErrorState": "alerting",
            "frequency": "60s",
            "handler": 1,
            "name": "Panel Title alert",
            "noDataState": "no_data",
            "notifications": [
              {
                "id": 1
              }
            ]
          },
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "fill": 1,
          "id": 1,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "node_load1{instance=~\"pmm-server\"}",
              "interval": "3s",
              "intervalFactor": 2,
              "legendFormat": "pmm-server",
              "refId": "A",
              "step": 6
            }
          ],
          "thresholds": [
            {
              "colorMode": "critical",
              "fill": true,
              "line": true,
              "op": "gt",
              "value": 1
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Panel Title",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "Dashboard Row",
      "titleSize": "h6"
    }
  ],
  "schemaVersion": 14,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-30m",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "Idle",
  "version": 6
}`

**Comment by torkelo** [comment]
Strange, you are the only one who has reported this. Maybe there are missing font packages on your centos box? The rpm should depend on them and install them automatically when you install the rpm.

**Comment by delgod** [comment]
@torkelo,
I installed `fontconfig freetype urw-fonts` packages and alerting working fine now.
Thank you!
