### ISSUE TITLE
build-docker-full: error during step yarn install --immutable

### ISSUE THREAD

**Issue by pikachuabc** [grafana/grafana#88481]
### What happened?

fail to build docker image  on `release-10.4.2`

windows wsl2 with command `make build-docker-full`

![image](https://github.com/grafana/grafana/assets/41946353/bc2831f3-4cb5-43cd-b106-35314e98cf36)

![image](https://github.com/grafana/grafana/assets/41946353/ddb6de87-bf5b-4e27-bba7-040aefa58ead)

### What did you expect to happen?

build image

### Did this work before?

Yes,  used to be working.

### How do we reproduce it?

1.  run `make build-docker-full` in the project dir

### Environment (with versions)?

Grafana: 10.4.2
OS: windows wsl2
Browser: N/A

### Grafana platform?

None

**Comment by visago** [comment]
Having same issue with Grafana 10.4.3 docker build

It seems some files are missing
`/tmp/xfs-4b13ca2e # cat build.log
# This file contains the result of Yarn building a package (@esfx/equatable@npm:1.0.2)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.13.1 | linux | x64
node-pre-gyp info check checked for "/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64/hashCodeNative.node" (not found)
node-pre-gyp http GET https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @esfx/equatable@1.0.2 and node@20.13.1 (node-v115 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
`

**Comment by trend-john-s-tsai** [comment]
> Having same issue with Grafana 10.4.3 docker build.
> 
> Grafana: 10.4.3 OS: Debian 12 x64
> 
> It seems some files are missing for @esfx/equatable
> 
> ```
> /tmp/xfs-4b13ca2e # cat build.log
> # This file contains the result of Yarn building a package (@esfx/equatable@npm:1.0.2)
> # Script name: install
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@1.0.11
> node-pre-gyp info using node@20.13.1 | linux | x64
> node-pre-gyp info check checked for "/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64/hashCodeNative.node" (not found)
> node-pre-gyp http GET https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not installable for @esfx/equatable@1.0.2 and node@20.13.1 (node-v115 ABI, musl) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz
> ```

seems that esfx/esfx v1.0.2 release doesn't support node v115; tried replacing JS_IMAGE in dockerfile with node:18-alpine and then the build succeeds.

**Comment by Drun1baby** [comment]
Meet the same issue but solved by [trend-john-s-tsai](https://github.com/trend-john-s-tsai)
