### ISSUE TITLE
[Feature request] Data source --All-- 

### ISSUE THREAD

**Issue by ryanash999** [grafana/grafana#8850]
Version = 4.3.1
Datasource = Prometheus
OS=RHEL

Our topology will have multiple Prometheus collector servers per data center.  We are looking at a single Grafana server which services users and provides views across the Prometheus collectors which are per data center, sometimes multiples per data center.   Today it appears we have two options.  We can use the -- Mixed -- option where users must define the query for each applicable data source.  Another option is templating where they would toggle between the data sources and view the data one at a time.  

Am I missing an option?

Would it be possible to have a query assigned to -- All -- data sources or even all data sources matching a regex?

**Comment by torkelo** [comment]
No, dont think so, templating is a interpolation feature, so where would all value go? 

You need a prometheus query bridge that can send the  same query to multiple prometheus servers and then combine the results

**Comment by ryanash999** [comment]
I had envisioned the data source selector having an option for '-- All --' similar to the option for '-- Mixed--'.   I have not heard of anyone using a query bridge like you reference but that would also address the underlying use case.   For situations where we have a single Grafana instance servicing multiple data centers, each with an associated data source, the 'All' option would be very handy.
