### ISSUE TITLE
[Feature request] apply decimals to y-axis

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#8851]
Please include this information:
- What Grafana version are you using?
4.4.1
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu

Apply `decimals` to y-axis to save space for graph.
<img width="324" alt="screen shot 2017-07-12 at 4 26 07 pm" src="https://user-images.githubusercontent.com/2936715/28144248-4d3d75c2-671f-11e7-9e92-37efa7c77042.png">

**Comment by torkelo** [comment]
Dexomals to time axis? Can you describe more what you mean, and why, and your reasons, maybe include a grafana  snapshot that highlights your problem

**Comment by wei-hai** [comment]
my bad, should be y-axis only

**Comment by torkelo** [comment]
Closing this as there already is a feature request for this
