### ISSUE TITLE
Make the API fully stateless (orgId)

### ISSUE THREAD

**Issue by iksaif** [grafana/grafana#8853]
If I understand fully https://github.com/grafana/grafana/blob/4ce0bf4d16b9526bbca34b918929bc4d7a136d77/pkg/api/datasources.go#L126, this means that when using the API one has to first select its current organization.

This work well with API keys, but in some cases you actually want to use the admin user (to manage organizations, etc.. using chef for example). And in this case, it's pretty easy to run into race condition.

Could the orgId not be overriden when it is specified when creating / updating objects ?

**Comment by marefr** [comment]
You should be able to use the HTTP header X-Grafana-Org-Id
