### ISSUE TITLE
11.1-preview docker image

### ISSUE THREAD

**Issue by EvertonSA** [grafana/grafana#88545]
Hi colleagues,

I'm a passionate user of Grafana and I love test new features. I was using 11.0-preview in production for quite a while and now I would like to use 11.1-preview in production. Can we build a docker image?

**Comment by cbos** [comment]
Normally there are no preview build available as far as I know.
But that are grafana-dev images for each release.

https://hub.docker.com/r/grafana/grafana-dev/tags
There are 11.1 build available.
But these are dev builds, so things can be broken, but that you can report these as well to prevent it to reach the final version.

**Comment by EvertonSA** [comment]
thanks!
