### ISSUE TITLE
[Feature request] Template variable query with mysql

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#8855]
Grafana version 4.4.1

I couldn't find this as an existing request - it would be amazing to be able to create template variables from a mysql query. Thanks!

**Comment by towolf** [comment]
Me too. I'm hoping to augment our thousands of _non-descript_ Graphite top-level hostnames with variables from our server DB. 

Hoping binding to a Mysql with hostname to group mappings will allow that ...

**Comment by tardoe** [comment]
Similar use case here, our OSS is MySQL backed and it would be great to just pull information from there rather than create scripted dashboards that go via the (slower) API first.

**Comment by drix1994** [comment]
Did something change with it? 
I need add variable to dashboard using mysql query..

**Comment by towolf** [comment]
Woot! Trying this now ...

**Comment by towolf** [comment]
Great success, thanks @daniellee!

![image](https://user-images.githubusercontent.com/345210/29137876-176c1c8a-7d42-11e7-9b46-6e8dff121c95.png)

**Comment by robinsonjj** [comment]
Brilliant, thanks a lot!

**Comment by daniellee** [comment]
Added support for key/value template variables.

> The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value. An example query with hostname as the text and id as the value:

```sql
SELECT hostname AS __text, id AS __value FROM my_host
```

ref b716a2595ad9c9cffcf6dcfb5c9d960b091bdb02

Also, published docs for templating in the MySQL data source: http://docs.grafana.org/features/datasources/mysql/#templating
