### ISSUE TITLE
Prometheus: Refactor code editor hints to offer multiple hints

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#88564]
The Prometheus data source code editor only offers a single hint. This issue is to refactor the hints in the code editor similar to the query builder which offers multiple hints.

Code editor: single hint

![Image](https://github.com/grafana/grafana/assets/25674746/74c579d5-09bc-4a2c-b921-4b361cec276f)

Query builder: multiple hints

![Image](https://github.com/grafana/grafana/assets/25674746/73ece547-000d-4cea-a105-78d95a19526b)

**Comment by alex-kattathra-johnson** [comment]
I'd like to give this a shot for a first issue.

**Comment by itsmylife** [comment]
@alex-kattathra-johnson That would be nice. Please feel free to send a PR. Thank you in advance.

**Comment by ArtistBanda** [comment]
Hi @alex-kattathra-johnson it looks like you might be working on something else. Can I pick this up?
