### ISSUE TITLE
[BUG] Alerting - return no data

### ISSUE THREAD

**Issue by Yakha** [grafana/grafana#8857]
Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
Grafana v4.4.1
- What datasource are you using?
influxdb (version : 1.2.4 (git: master 77909d7c7826afe597b12d957996d6e16cd1afaa) )
- What OS are you running grafana on?
RHEL7
- What did you do?
Create alert with last() metrics

- What was the expected result?
If last () metrics is above 3, pop an alert.

- What happened instead?
Actually the alert check return always "no data" : 
![image](https://user-images.githubusercontent.com/9256016/28180237-d6c6c8bc-6804-11e7-8c41-87c711b14353.png)

When i'm checking on influx database I haven't null data value : 
> SELECT "value" FROM "database_size" WHERE "BDD" = 'XXXXXXX' AND "host" = 'srv514'
![image](https://user-images.githubusercontent.com/9256016/28180326-147107f4-6805-11e7-84b5-845c6f0efadb.png)

![image](https://user-images.githubusercontent.com/9256016/28180620-e7346956-6805-11e7-9c3f-fb0464030595.png)

Any idea about this error ? :+1: 

Best ,
Yakha

**Comment by daniellee** [comment]
Do you have template variables in your query?

**Comment by Yakha** [comment]
@daniellee No, i dont have on this one. But i have on an other Dashboard for the same metrics (there is a potential link ?)

**Comment by torkelo** [comment]
When you tested manually against InfluxDB Did you execute the exact same query and time range you have in your Grafana alert rule?  

Maybe there is no data for the last 5min and you fill(null) in your query. This seems the most likely as no one else has reported problems and it must be influxdb returning the null values.

**Comment by Yakha** [comment]
Hi @torkelo 

I've just tested now and all looks good, i mean no return of value 'null' : 
`SELECT last("value") FROM "database_size" WHERE "BDD" = 'XXXXXX' AND "host" = 'srv514' AND time > now() - 15m GROUP BY time(30s)
`
`name: database_size
time                last
----                ----
1500015240000000000 3.24142838
1500015270000000000 3.24142838
1500015300000000000 3.24142838
1500015330000000000 3.24142838
1500015360000000000 3.24142838
1500015390000000000 3.24142838
1500015420000000000 3.24142838
1500015450000000000 3.24142838
1500015480000000000 3.24142838
1500015510000000000 3.24142838
1500015540000000000 3.24142838
1500015570000000000 3.24142838
1500015600000000000 3.24142838
1500015630000000000 3.24142838
1500015660000000000 3.24142838
1500015690000000000 3.24142838
1500015720000000000 3.24142838
1500015750000000000 3.24142838
1500015780000000000 3.24142838
1500015810000000000 3.24142838
1500015840000000000 3.24142838
1500015870000000000 3.24142838
1500015900000000000 3.24142838
1500015930000000000 3.24142838
1500015960000000000 3.24142838
1500015990000000000 3.24142838
1500016020000000000 3.24142838
1500016050000000000 3.24142838
1500016080000000000 3.24142838
1500016110000000000 3.24142838
1500016140000000000 3.24142838`

**Comment by torkelo** [comment]
since your alert rule has 5m time range and using default group by time interval the group by time interval will be much lower than 30s, (200ms or so).

In the data source options or in group by time option below your queries specify `>30s' to set that as a lower group by time limit.

**Comment by Yakha** [comment]
@torkelo , first thanks for your feedback,
I set on my query parameters a default interval at '>30s' but this change nothing on the alerts status : 

![image](https://user-images.githubusercontent.com/9256016/28239604-38115940-6970-11e7-8983-bcde3170ccc2.png)

Result of check alert rules : 
![image](https://user-images.githubusercontent.com/9256016/28239612-5c398766-6970-11e7-80a7-5743689db908.png)

I'm missing something ? :/

**Comment by torkelo** [comment]
Strange, maybe an influxdb bug?

**Comment by torkelo** [comment]
Or more likely that there is no data for last 5min
