### ISSUE TITLE
New recording rule: when click [Configure a new data source], got wrong url。

### ISSUE THREAD

**Issue by lvjunsetup** [grafana/grafana#88580]
### What happened?

![image](https://github.com/grafana/grafana/assets/23273933/139ab45b-4a06-486f-b516-896986c1db27)
got it:
![image](https://github.com/grafana/grafana/assets/23273933/95ae9704-0e8c-43d3-a1c2-50c2ac6877e2)
it should be: grafana/connections/datasources/new
others not meet such problem:
![image](https://github.com/grafana/grafana/assets/23273933/dd7f142c-abb2-4abd-b7ec-80b092f8558d)

### What did you expect to happen?

in recording rule, when click [Configure a new data source], get right url。(head attach grafana/ , since my root_url  is [%(protocol)s://%(domain)s/grafana/])

### Did this work before?

i use this function first

### How do we reproduce it?

1. in recording rule, when click [Configure a new data source], get right url, base on root_url

### Environment (with versions)?

Grafana: Grafana v11.0.0 (277ef258d4)
OS: Windows 11 
Browser: Google Chrome 125.0.6422.76

### Grafana platform?

Kubernetes

**Comment by tomratcliffe** [comment]
This looks to be within the alerting UI, but I think the component used is within datasources, specifically here?:
https://github.com/grafana/grafana/blob/68e30e2b4b41f43044cf3385aaa4072671f5d4dc/public/app/features/datasources/components/picker/AddNewDataSourceButton.tsx#L14

I think the URL needs to take into account any subdirectory of the hosted environment

**Comment by tomratcliffe** [comment]
(I opened a PR to fix it, I believe this is the problem you were encountering @lvjunsetup - please let me know if this wasn't the bug)

**Comment by gillesdemey** [comment]
Fixed in https://github.com/grafana/grafana/pull/90536
