### ISSUE TITLE
[Bug] Some column styles do not work for table with Raw Document metric

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#8858]
- What Grafana version are you using?
4.4.1
- What datasource are you using?
Elasticsearch 2.4
- What OS are you running grafana on?
Win 2012 R2
- What did you do?
Change field unit to Bytes and set threshold
![2017-07-13 12_18_53-grafana - failed column styles](https://user-images.githubusercontent.com/3209539/28184032-9caa26f8-67c6-11e7-92d6-8cbb52072f7b.png)
 
- What was the expected result?
The settings should work as designed
- What happened instead?
Settings do not work

**Comment by torkelo** [comment]
Can you show the response from elasticsearch? Is the sent bytes field truly numeric?

**Comment by anhlqn** [comment]
Yes, received_bytes and sent_bytes field are mapped as long type. I'll post the response from ES later.

**Comment by anhlqn** [comment]
This is the mapping for sent_bytes field retrieved from the index
```
"sent_bytes": {
        "type": "long"
      }
```
Response from ES
```
"sent_bytes": "113656",
"received_bytes": "668637",
```
Looks like that number fields' values are also in double quotes. Wonder if this is why column styles do not treat the fields as number. Graphing the fields as an average or other metrics work just fine.

**Comment by torkelo** [comment]
But they are not, ES is returning them as strings

**Comment by anhlqn** [comment]
Yes, ES is return them as strings, but if I apply the unit in a Graph panel, it works fine. It just doesn't work when I use Table panel and Raw Document metric. Since ES responses are the same for both panels (numbers return in double quotes), should we expect the column styles to work in both panels as well?

**Comment by torkelo** [comment]
Graph panel does not support raw document queries not does it support string values , so it's strange you say that this query works there :)

**Comment by anhlqn** [comment]
![2017-07-13 12_18_53-grafana - failed column styles 2](https://user-images.githubusercontent.com/3209539/28234440-6efe34ee-68b4-11e7-8c61-1dd76b2f601d.png)

The screenshot above should illustrate my point more clearly. Same data set which ES returns numbers as string.

- First panel is a graph with Max metric. Unit is set to Bytes on the Axes tab
- Second panel is a table with Raw Document. Unit is set to Bytes on Colum Styles tab

Should the Table panel display proper unit as the Graph panel in this case?

**Comment by torkelo** [comment]
Well query is totally different so of course the result is different, in the graph query you use a ES metric aggregation, which returns numbers.

In the second case your query returns your raw data which are strings

**Comment by anhlqn** [comment]
> In the second case your query returns your raw data which are strings
It appears that ES returns number fields in double quotes. I've checked fields mapped as integer, long, float, and double. They are all returned in double quotes. Is it possible to have Grafana handle Raw document from ES data source differently?

**Comment by torkelo** [comment]
Raw document returns the data as you wrote it, the index does not change the type of the raw data you save. You seem to save strings

**Comment by rdubya16** [comment]
@anhlqn Did you ever find a solution for this? I am seeing the same behavior

**Comment by anhlqn** [comment]
@rdubya16 I have to use convert filter in Logstash to convert these fields before sending to ES.

**Comment by mikich** [comment]
This seems like a bug in Grafana: the _source:Object, which holds a json in the response object return ALWAYS with quotes, no matter how field defined in elasticsearch... 
Here is the example (response for garfana table view):

```javascript
{
    "responses": [
        {
            "took": 0,
            "timed_out": false,
            "_shards": {
                "total": 5,
                "successful": 5,
                "failed": 0
            },
            "hits": {
                "total": 42,
                "max_score": null,
                "hits": [
                    {
                        "_index": "index_name",
                        "_type": "logs",
                        "_id": "h9384h75d983475hd938475hd",
                        "_score": null,
                        "_source": {
                            "FIELD_1_INT": "6",
                            "FIELD_2_KEYWORD": "Build",
                            "FIELD_3_INT": "65031.39",
                            "FIELD_4_SHORT": "5",
                            "message": "Build,6,5,65031.39",
                            "path": "/in/some_file.csv",
                            "@timestamp": "2018-04-02T15:00:00.000Z",
                            "@version": "1",
                            "host": "mac.local"
                        },
                        "fields": {
                            "@timestamp": [
                                1522681200000
                            ]
                        },
                        "sort": [
                            1522681200000
                        ]
                    }
                ]
            },
            "status": 200
        }
    ]
}
```
