### ISSUE TITLE
[Bug]grafana and nginx reverse proxy with docker

### ISSUE THREAD

**Issue by elysiumHL** [grafana/grafana#8859]
I use docker to deploy grafana4.4.1 and nginx1.13.1 on different server. the nginx server is 10.88.142.19, and the grafana server is 10.88.142.20

My nginx conf like that:
upstream grafana {
    server 10.88.142.20:3000;
}
server {
    listen      80;
    server_name nginx;
    location /grafana/  {
        proxy_pass http://grafana/;
    }
}
 
My grafana conf in compose.yaml like that:
grafana:
    image: grafana/grafana:4.4.1
    ports:
        - "3000:3000"
    environment:
        GF_SECURITY_ADMIN_PASSWORD: 'devops'
        GF_SERVER_DOMAIN: 'nginx'
        GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s:/grafana'

When I access the url 'http://10.88.142.19/grafana/' in browser on my laptop, only the black sreen in browser window, no login page and so on. And the grafana log does not output anything. The last output is 't=2017-07-14T06:18:20+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/grafana socket='

**Comment by torkelo** [comment]
try setting 

GF_SERVER_ROOT_URL: 'http://10.88.142.19/grafana'

since that is what you use in your browser. 

Please use community site for questions.
