### ISSUE TITLE
[Bug] Making a query with division involving null values causes Internal server error

### ISSUE THREAD

**Issue by tirkarthi** [grafana/grafana#8860]
- What Grafana version are you using?  Grafana v4.4.1
- What datasource are you using? Prometheus v1.5.2
- What OS are you running grafana on? Mac OS X Yosemite
- What did you do? Created a query to calculate the average of the series with data point that can be null and alerts when the data point is null.
- What was the expected result? Alerts should be raised
- What happened instead?  Since average involves division and when the data points are null alerts are throwing an error
- If related to metric query / data viz:  Query : `rate(foo_sum[5m]) / rate(foo_count[5m])` . When there is no change in the value of foo then the value is plotted as null in the graph but alerts throw Internal server error while making a test alert call/
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

While making a POST request to `/api/alerts/test` when the datapoint is null it throws 500 error with the grafana logs showing the below : 

`t=2017-07-14T12:37:10+0530 lvl=eror msg="body json marshal" logger=context userId=1 orgId=1 uname=admin error="json: error calling MarshalJSON for type null.Float: invalid character 'N' looking for beginning of value"`

The same request when made with the datapoints in place is successful and raises appropriate alerts.

Query : `rate(foo_sum[5m]) / rate(foo_count[5m])` . When foo is not changed and is idle then the average rate of change is null and alerts need to be raised when there is null value.

Query :

![fireshot capture 023 - grafana - hf-mail metri_ - http___localhost_3000_dashboard_db_hf-mail-metrics](https://user-images.githubusercontent.com/3972343/28203724-89858356-6898-11e7-992a-9577bcc25f9f.png)

Error : 

![fireshot capture 022 - grafana - hf-mail metri_ - http___localhost_3000_dashboard_db_hf-mail-metrics](https://user-images.githubusercontent.com/3972343/28203626-23efd690-6898-11e7-9755-1dd3a21b2fc1.png)

**Comment by torkelo** [comment]
> `t=2017-07-14T12:37:10+0530 lvl=eror msg="body json marshal" logger=context userId=1 orgId=1 uname=admin error="json: error calling MarshalJSON for type null.Float: invalid character 'N' looking for beginning of value"`


looks like a prometheus bug or issue as the query seems to return non valid JSON.

**Comment by torkelo** [comment]
also you graph seems to use a unit type "duration" this is not designed for use in graph panel, it is more for singlestat. Try "time" units instead

**Comment by tirkarthi** [comment]
@torkelo Thanks. It seems prometheus returns NaN while calculating average with no data points as reported in https://github.com/prometheus/prometheus/issues/860 and https://github.com/knyar/nginx-lua-prometheus/issues/5 . I have used ` rate(foo_sum[5m]) / rate(foo_count[5m]) > 0` as a workaround.
