### ISSUE TITLE
[Bug] Some UI glitches on Grafana v4.4.1

### ISSUE THREAD

**Issue by anhlqn** [grafana/grafana#8863]
- What Grafana version are you using?
4.4.1
- What datasource are you using?
Elasticsearch 2.4
- What OS are you running grafana on?
Win 2012 R2
- What did you do?
After upgrading Grafana to 4.4.1, I start seeing some UI glitches on both latest Chrome and Firefox as seen on the screenshots. This issue occurs on multiple computers, with or without firewall between.

![2017-07-14 11_13_59-grafana ui glitch 1](https://user-images.githubusercontent.com/3209539/28225054-1d7aa824-6886-11e7-850a-c9ab93440eaa.png)
![2017-07-14 11_13_59-grafana ui glitch 2](https://user-images.githubusercontent.com/3209539/28225061-21022616-6886-11e7-85e0-381550190ca3.png)

Below is the error I see from Chrome DevTools
```
GET https://grafana/avatar/caf3902d5255ec0640605625efe99fac net::ERR_CONTENT_LENGTH_MISMATCH
```

**Comment by torkelo** [comment]
First red circle seems to be related to gravatar img, could be caused by gzip, so you have gzip enabled in Grafana? 

The second red circle will need more info on that not seeing the glitch

**Comment by anhlqn** [comment]
Disabling gzip fix the first issue. For the second, I guess it's a UI change. Those buttons used to be at the bottom on older versions. 

Thanks for your quick response.
