### ISSUE TITLE
feature: allow Grafana Viewers (or Editors) to view dashboard folder permissions

### ISSUE THREAD

**Issue by tonychoe** [grafana/grafana#88641]
**Why is this needed**:

Currently, OSS Grafana allows only Grafana Admins to view dashboard folder permissions and it seems there is no way to change this default setting

So when a Viewer or Editor wants to be able to manage dashboards within a folder, they can't see who might be the owners of folders. Instead, they must reach out to Grafana Admins to ask help with access. 

By allowing a Viewer or Editor to view permissions, this can be avoided.

**What would you like to be added**:

Allow a Viewer (or Editor) role to view dashboard folder permissions as default or make this configurable.

**Who is this feature for?**

Non Admin users of OSS Grafana

**Comment by vtorosyan** [comment]
Thank you for the issue. The described feature is available through the [Grafana RBAC](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/) which is available in Grafana Enterprise and Grafana Cloud (all plans, including free). So unfortunately we can't accept this feature request.

I'll close the issue for now.
