### ISSUE TITLE
[Bug] - Unable to upload rendered images to s3 bucket

### ISSUE THREAD

**Issue by egarbi** [grafana/grafana#8864]
- What Grafana version are you using?
4.4.1
- What datasource are you using?
Not relevant but InfluxDB
- What OS are you running grafana on?
The official docker image
- What did you do?
I configured s3 external storage to upload rendered images to a bucket.
This is the relevant config, got by docker inspect
```"GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL=http://grafana-images-testing.s3-website-eu-west-1.amazonaws.com/"``` 
- What was the expected result?
Show rendered images in a slack channel together with info about what is failing when an alert is triggered
- What happened instead?
No image shown with the alert and an upload error in logs:
```t=2017-07-14T18:00:02+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/uptime-per-container?&panelId=1"```
```t=2017-07-14T18:00:03+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="RequestError: send request failed\ncaused by: Put https://grafana-images-testing.s3.website-eu-west-1.amazonaws.com/Xvva32YlCO29mnUibenj.png: dial tcp: lookup grafana-images-testing.s3.website-eu-west-1.amazonaws.com on 10.23.0.2:53: no such host"```

> Note that the bucket configured and the one shown by log are similiar but not the same. The one in conf use "http" and ".s3-" prefix and the logs shows "https" and ".s3." prefix

**Comment by torkelo** [comment]
Don't use the website url use the raw bucket url
