### ISSUE TITLE
[Bug] Alert symbol enlarges panel when no title is set

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8865]
v4.4.1 - InfluxDB - Debian Jessie

Enabling alerts on a panel without a title assigned causes the alert icon on the panel to push it down a few pixels as can be seen on the screenshots here:

No title / Alert disabled:
![alert0_title0](https://user-images.githubusercontent.com/2349496/28243586-9fe3c96c-69d0-11e7-9bb4-38799fe918f4.png)

No title / Alert enabled (note the different spacing in the lower right corner):
![alert1_title0](https://user-images.githubusercontent.com/2349496/28243587-9fe5e300-69d0-11e7-81a0-4d02c10652c7.png)

Title assigned / Alert enabled:
![alert1_title1](https://user-images.githubusercontent.com/2349496/28243588-9fea6916-69d0-11e7-9e04-3cb282c34102.png)

**Comment by torkelo** [comment]
Yes, this is required to make space for the icon, similarly when having a title the panel header needs more space as is the case when enable alert rule

**Comment by torkelo** [comment]
Wait, think it's a bug though, the total height is not taking into consideration the alert icon

**Comment by Fusl** [comment]
Yes, sorry if my bug report wasn't clear enough, was pretty late already.

Basically what happens here is that the code checks

```
if the title is enabled:
    make the graph smaller
else:
    make the graph bigger
```

This should instead be:

```
if the title is enable or the graph is enabled:
    make the graph smaller
else:
    make the graph bigger
````

**Comment by Fusl** [comment]
Fixed my if-condition example in my previous comment. It said `or a graph is enabled` while it should say `or an alert is enabled`.

**Comment by torkelo** [comment]
This should be fixed in v7
