### ISSUE TITLE
Reduce cyclomatic complexity of PrepareRuleGroupStatuses

### ISSUE THREAD

**Issue by fayzal-g** [grafana/grafana#88670]
CI is failing for the function `PrepareRuleGroupStatuses` found at https://github.com/grafana/grafana/blob/783aa1c0b4b386cd02af3c0ff561afac0248c204/pkg/services/ngalert/api/api_prometheus.go#L238 due to 
```
pkg/services/ngalert/api/api_prometheus.go:238:1: cyclomatic complexity 36 of func `PrepareRuleGroupStatuses` is high (> 30) (gocyclo)
```
It has currently been excluded from lint with `//nolint:gocyclo` but the function should ideally be refactored.

**Comment by wasim-nihal** [comment]
@fayzal-g , is this open for contribution? I'd like to work on this.

**Comment by shivanshsharma13** [comment]
Hi @wasim-nihal, As I can see you have referenced this issue number in your branch and not created the pull request. If you are waiting for the approval or review before promoting, please tag the maintainers or reviewers. That will just speed up the process. Thanks

**Comment by wasim-nihal** [comment]
Hey @shivanshsharma13. This is still WIP and I am working on a few changes for it locally. Will issue a PR once done. Thanks!!
