### ISSUE TITLE
[Bug] Closing dashboard options with escape key causes it to no longer open

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8869]
v4.4.1 - InfluxDB - Debian Jessie

When closing the dashboard options (Settings/Templating/Annotations/Version history) with the escape key instead of the "X" button, Grafana no longer allows opening the same dashboard option, instead it requires another dashboard options to be opened which then allows the other dashboard options to be opened.

Demonstration: http://xor.meo.ws/oyMOQrouaZP-SArDfonOX_F3AOlBS255/out.webm

**Comment by torkelo** [comment]
thanks for reporting this
