### ISSUE TITLE
How do I install the grafana with the embedded-kiosk-mode

### ISSUE THREAD

**Issue by MaximBozek** [grafana/grafana#88704]
How do i install your grafana with the embedded kiosk mode?

**Comment by tsmjay** [comment]
@MaximBozek Do you have a link to the documentation for that?

**Comment by MaximBozek** [comment]
This is the guys post, can't comment in the thread anymore because it's closed

![image](https://github.com/grafana/grafana/assets/135378606/69fce472-5c6b-449f-85de-13fcd917561b)

https://github.com/pmint93/grafana/tree/embedded-kiosk-mode

v9.0.4 https://github.com/pmint93/grafana/commits/v9.0.4-embedded-kiosk-mode

v8.2.7 https://github.com/pmint93/grafana/tree/v8.2.7-embedded-kiosk-mode

**Comment by tsmjay** [comment]
Grafana has an in-built [kiosk mode](https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/) (item 12).

Not sure if that's what you're looking for?

**Comment by MaximBozek** [comment]
yes but it is exitable by pressing escape, which totally defeats the point for my purposes

**Comment by tonypowa** [comment]
Hi @MaximBozek 
Thanks for reaching out. GitHub is mainly used for tracking bugs and feature requests. Your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) If you get stuck , you are also welcome to ask in our [Community Slack](https://slack.grafana.com/)
We appreciate your understanding.
