### ISSUE TITLE
[Bug] Rendering API randomly displays datetime instead of time only when from=now-24h&to=now

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8871]
v4.4.1 - InfluxDB - Debian Jessie

Using `from=now-24h&to=now` in the graph render API causes it to sometimes display dates along with times although the timeframe is 24 hours only.

![ec1a1ce4f5a6](https://user-images.githubusercontent.com/2349496/28250544-8301e806-6a6b-11e7-86d5-363726ad775d.png)

Replacing from/to with `from=${from}&to=${to}` generated by

```
to=$(date +%s000)
from=$((${to}-86400000))
```

corrently hides the dates:

![a862ff2dd395](https://user-images.githubusercontent.com/2349496/28250549-9bae417e-6a6b-11e7-8703-323a50ba8e5b.png)

**Comment by torkelo** [comment]
Its due to the axis labels having different widths causing the graph width to be slightly different, and it appears that it's just at the point where the tick formating goes from just time to date and time

**Comment by Fusl** [comment]
That's not the case, see the 2nd and 3rd graphs on the first screenshot in the right column in my bug report.

This is caused by the code checking whether the selected timeframe is within 24 hours or not:

https://github.com/grafana/grafana/blob/32f9a42d5e931be549ff9f169468b404af9a6b21/public/app/plugins/panel/graph/graph.ts#L643
https://github.com/grafana/grafana/blob/97a7081b5735af8bb746ffd0e797f946f990ab34/public/app/plugins/panel/heatmap/rendering.ts#L814

This is a timing bug that causes the `oneDay` condition to be off just by a few milliseconds hence it jumps to the next conditional if-then-return.

**Comment by Fusl** [comment]
@torkelo Mind reopening this as it is an actual bug?

**Comment by torkelo** [comment]
This should be fixed
