### ISSUE TITLE
Timepicker: Overflow of "recently used" time ranges

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#88723]
### What happened?

Timepicker intermittently does not overflow recently used time range data properly. Data flows outside of window.

![Screenshot 2024-06-04 at 1 17 52 PM](https://github.com/grafana/grafana/assets/1533128/727c9c66-b30c-4e0e-8c6f-ed5b7b46876e)
![Screenshot 2024-06-04 at 1 15 51 PM](https://github.com/grafana/grafana/assets/1533128/71ad1e2f-602d-4d81-b130-da069303ec16)

### What did you expect to happen?

For the data to be contained to the time picker pane of modal.

### Did this work before?

Not sure. Reported internally to the Explore team.

### How do we reproduce it?

1. Select a couple absolute time ranges to populate the "recently used" section
2. Reduce the window width

I have noticed that at one point I was unable to replicate the problem. I opened Grafana in an incognito window and was able to replicate it again.

### Environment (with versions)?

Grafana: main
OS: OSX
Browser: Chrome current

### Grafana platform?

Other

**Comment by tskarhed** [comment]
It might be related to the changes in this PR #88327
