### ISSUE TITLE
Angular plugin detection too strict, it blocks my (scenes) plugin while it does not use Angular at all

### ISSUE THREAD

**Issue by cbos** [grafana/grafana#88739]
### What happened?

I am busy developing a plugin with Grafana Scenes.
My plugin was working fine for months.
Now I am making some changes to use Apache Echarts as well.

Now I get an error while loading setup with Grafana 11

```
ing-observabilityapp-scenesapp  | logger=plugins.validator.angular t=2024-06-05T06:17:43.624875464Z level=error msg="Refusing to initialize plugin because it's using Angular, which has been disabled" pluginId=ing-observability-app
ing-observabilityapp-scenesapp  | logger=plugins.validation t=2024-06-05T06:17:43.624907839Z level=error msg="Plugin validation failed" pluginId=ing-observability-app error="angular plugins are not supported"
```

Based on the code I could find which checks are done:
https://github.com/grafana/grafana/blob/e735573852ad5b28d9d834f6269b013c731defcb/pkg/plugins/manager/loader/angular/angularinspector/angularinspector.go#L72

If I grep on the mentioned code in the dist folder of the plugin it can find `editor.html` in a comment line of code in the code of Apache Echarts:

<img width="2380" alt="image" src="https://github.com/grafana/grafana/assets/255404/295bcc56-3366-4951-916d-e0f42805f5d2">

This blocks the loading of the plugin in Grafana 11.

### What did you expect to happen?

The plugin to be loaded correctly as it did before

### Did this work before?

Yes, untill I make some changes which loaded Apache Echarts

### How do we reproduce it?

In a Grafana scenes app just add a line of comment like this:

```javascript
    queries: [
        {
            //for example https://echarts.apache.org/examples/en/editor.html
            refId: 'servicesRate',
```

This ends up in the distribution and the plugin will fail to load

### Environment (with versions)?

Grafana: 11.0.0

### Grafana platform?

Docker

**Comment by cbos** [comment]
@tolzhabayev 
I saw that you disabled the support of Angular with this PR: https://github.com/grafana/grafana/pull/84738
I don't know if you worked on the feature in more general, but it looks like that the checks being done are too strict.

`editor.html` in a comment line in Apache Echarts.
https://github.com/apache/echarts/blob/a4db0d4f7f87e73ac20a322ee586f9ac5e8618ba/src/chart/custom/CustomSeries.ts#L395

When I use that library in a Grafana Scenes plugin app, that app is not loaded anymore.
That is not the intention of disabling Angular support I think.

Can someone have a look at this?

For now I can prevent this by re-enabling Angular support to prevent the blocking of the plugin. 
But I wonder how that will look like in Grafana 12.

**Comment by cbos** [comment]
NOTE:
The documentation of Grafana 11 is incorrect
https://grafana.com/docs/grafana/v11.0/setup-grafana/configure-grafana/#angular_support_enabled

> This currently defaults to `true` but will default to `false` in a future release. 

That is done in Grafana 11, but the documentation is not updated.

**Comment by tolzhabayev** [comment]
@cbos thanks for reporting this behaviour - it will be fixed in the next version of Grafana https://github.com/grafana/grafana/pull/88845

**Comment by cbos** [comment]
@tolzhabayev
Thanks for the quick reply and fixes!
I will check (next week) with a new dev build as well.

**Comment by cbos** [comment]
@tolzhabayev 
I have tested the latest grafana-dev build. 
The plugin is now loaded properly again, I don't have to enable angular support anymore. 
Thanks for the fix!
