### ISSUE TITLE
[Feature request] Allow mapping of github teams to roles in grafana

### ISSUE THREAD

**Issue by tobilarscheid** [grafana/grafana#8875]
Hi everyone,

I think it would be very helpful if github teams could be mapped to roles in grafana. We do this with a lot of other tools already and it has proven to be a good SSO-Solution. Specifically, we create an `administrators` team in our github org and try to make these guys administrators of grafana as well.

I would be willing to provide a PR if someone could give me a quick heads up where to start digging to grasp the grafana authz concept.

While searching I found issue #6809 which argues against what I propose here, I would however assume that it was ok for `[auth.github]` to support some github specific stuff.

Regards,

Tobi

**Comment by hairyhenderson** [comment]
I'd love to see this happen. It's very easy for an admin to "forget" to upgrade a user's role after they've logged in, and I'd much rather control this via GitHub Teams.

**Comment by frittentheke** [comment]
There exists (a closed) PR for roles to be taken from OAuth - https://github.com/grafana/grafana/pull/9767

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by inductor** [comment]
Hi, I created a discussion thread regarding this. Please upvote it if you're interested!
https://github.com/grafana/grafana/discussions/50369
