### ISSUE TITLE
Grafana Alerts Rules don't work with non root users

### ISSUE THREAD

**Issue by chim678** [grafana/grafana#88769]
### What happened?

I am trying to create an alert rule with my custom datasource plugin and get an error that the plugin is unavailable.
This error:

> [sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable

Some details:
I am running grafana as a podman container:

> grafana:
>     image: grafana/grafana:11.0.0-preview
>     container_name: grafana
>     ports:
>       - 172.17.0.1:3000:3000
>     volumes:
>       - /var/don/grafana/:/var/lib/grafana:z
>       - /var/don/grafana/plugins/:/plugins:z
>       - /var/don/grafana/grafana.ini:/etc/grafana/grafana.ini:z
>     user: 1000:357
>     environment:
>       - GF_LOG_LEVEL=error
>       - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/proxy/grafana/?(.*)
>       - GF_SECURITY_ALLOW_EMBEDDING=true

The issue is very similar to this one:
https://github.com/grafana/opensearch-datasource/issues/251

The error is the same. The only difference is the content of the /tmp directory. With non-root user, it looks like this:
![image](https://github.com/grafana/grafana/assets/89776717/a49da745-5f75-4b5f-baa0-4fefa8f3a9ec)

With the root user like this (with have several custom datasources with alerting feature):
![image](https://github.com/grafana/grafana/assets/89776717/635446b5-33d9-4298-ad6e-d2c4879d51d6)
The question is why the custom plugins are not shown in the /tmp directory. I assumed that permission and ownership of /tmp or /plugins directories would be the problem. But giving full permission to all users doesn't solve the problem. 

When I try to start the binaries manually, I have this:
![image](https://github.com/grafana/grafana/assets/89776717/cdb7b86f-47af-444a-a828-308932193305)

In Grafana logs, I see the following:

> logger=plugins.initialization t=2024-06-05T11:58:17.554137733Z level=error msg="Could not initialize plugin" pluginId=optimax-streaming-datasource error="Unrecognized remote plugin message: \nFailed to read any lines from plugin's stdout\nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is missing dynamic-link libraries necessary to run,\n  the plugin is not executable by this process due to file permissions, or\n  the plugin failed to negotiate the initial go-plugin protocol handshake\n\nAdditional notes about plugin:\n  Path: /var/lib/grafana/plugins/optimax-streaming-datasource/dist/gpx_backend_datasource_linux_amd64\n  Mode: -rwxr-xr-x\n  Owner: 1000 [optimax] (current: 1000 [optimax])\n  Group: 357 [357] (current: 357 [357])\n  ELF architecture: EM_X86_64 (current architecture: amd64)\n"

The binaries are compiled with the latest grafana-plugin-sdk-go, the GO version: 1.21.7. 

### What did you expect to happen?

alert rules created without any errors.

### Did this work before?

It works flawlessly with the root user.

### How do we reproduce it?

1. Take any plugin with enabled and working alerting feature
2. Create a new alert rule
3. Click "Preview".

### Environment (with versions)?

Grafana: v11.0.0-preview (tested in other versions - same error)
Podman: v4.6.1
Browser: Chrome
Linux: RHEL 9.3

### Grafana platform?

Docker

### Datasource(s)?

Custom, not published Datasource

**Comment by marefr** [comment]
> The error is the same. The only difference is the content of the /tmp directory

I'm not following how the /tmp directory is related to your problem, can you please expand?

How have you setup the volumes (persistent storage), have you followed the instructions in https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#save-your-grafana-data? 
Does all files in your volumes have user=1000 and group=357?

**Comment by chim678** [comment]
1. I am not sure how it is connected with /tmp directory, but when the alerts are working (with user=0 and group=357), I see the next content in /tmp:
![image](https://github.com/grafana/grafana/assets/89776717/57cae1bf-5454-4ced-9bbc-008629714d7b)

When the user=1000 and group=357 the /tmp is empty. 
We upgraded to grafana11.1.0 and now it is even worse: the backend plugin is not starting and the process of plugin initialization is exited (but the errors are the same):
`logger=plugins.backend.start t=2024-07-03T10:09:11.79667786Z level=error msg="Could not start plugin backend" pluginId=optimax-historian-datasource error="Unrecognized remote plugin message: \nFailed to read any lines from plugin's stdout\nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is missing dynamic-link libraries necessary to run,\n  the plugin is not executable by this process due to file permissions, or\n  the plugin failed to negotiate the initial go-plugin protocol handshake\n\nAdditional notes about plugin:\n  Path: /var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64\n  Mode: -rwxr-xr-x\n  Owner: 1000 [optimax] (current: 1000 [optimax])\n  Group: 357 [357] (current: 357 [357])\n  ELF architecture: EM_X86_64 (current architecture: amd64)\n"
`

2. About the docker setup. Yes, I followed the instructions. We store the plugins on the RHEL host and mount it with Grafana:
```
grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 172.17.0.1:3000:3000
    volumes:
      - /var/don/grafana/:/var/lib/grafana:z
      - /var/don/grafana/plugins/:/plugins:z
      - /var/don/grafana/grafana.ini:/etc/grafana/grafana.ini:z
    user: 1000:357
```
User 1000 has all the needed permissions for operating in /var/lib/grafana.

**Comment by marefr** [comment]
Hmm the content in /tmp would normally indicate plugins have been installed using grafana-cli and .zip files extracted to /tmp before moved into grafana plugins directory. Looking at your docker setup doesn't look like your installing any plugins, rather they're already mounted in the volume as you describe. 

Out of curiosity noticed the `:z` volume option which I've never seen before. Reading https://stackoverflow.com/a/60099730, not sure why you use that option and/or what it provides for you. Maybe the problem?

Regarding the logs, would be interesting to see more details and what happens earlier when grafana loads the plugins. Can you [enable debug logs](https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs) and see if it includes any additional clues and/or include it here (make sure to redact any sensitive information)

**Comment by chim678** [comment]
Yes, exactly the plugin lay on the local host and then mounted to the grafana container.
Z means a labeling for SELinux, which allows multiple containers to read and write to the volume. But sure, I am trying without it and see the next logs:
```

logger=local.finder t=2024-07-04T07:13:28.351126241Z level=debug msg="Loading plugin" path=/var/lib/grafana/plugins/optimax-historian-datasource/dist/plugin.json
logger=plugins.signature t=2024-07-04T07:13:28.418431809Z level=debug msg="Plugin signature valid" id=optimax-historian-datasource
logger=plugin.signature.validator t=2024-07-04T07:13:28.418469191Z level=debug msg="Plugin has valid signature" id=optimax-historian-datasource
logger=plugin.optimax-historian-datasource t=2024-07-04T07:13:28.418993603Z level=debug msg="starting plugin" path=/var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64 args=[/var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64]
logger=plugin.optimax-historian-datasource t=2024-07-04T07:13:28.419259653Z level=debug msg="plugin started" path=/var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64 pid=16
logger=plugin.optimax-historian-datasource t=2024-07-04T07:13:28.419288662Z level=debug msg="waiting for RPC address" plugin=/var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64
logger=plugin.optimax-historian-datasource t=2024-07-04T07:13:28.42317381Z level=debug msg="2024/07/04 07:13:28 open myLOG.txt: permission denied"
logger=plugin.optimax-historian-datasource t=2024-07-04T07:13:28.42369077Z level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64 id=16 error="exit status 1"
logger=plugins.backend.start t=2024-07-04T07:13:28.423740299Z level=error msg="Could not start plugin backend" pluginId=optimax-historian-datasource error="Unrecognized remote plugin message: \nFailed to read any lines from plugin's stdout\nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is missing dynamic-link libraries necessary to run,\n  the plugin is not executable by this process due to file permissions, or\n  the plugin failed to negotiate the initial go-plugin protocol handshake\n\nAdditional notes about plugin:\n  Path: /var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64\n  Mode: -rwxrwxrwx\n  Owner: 1000 [optimax] (current: 1000 [optimax])\n  Group: 357 [357] (current: 357 [357])\n  ELF architecture: EM_X86_64 (current architecture: amd64)\n"
logger=plugins.initialization t=2024-07-04T07:13:28.423752713Z level=error msg="Could not initialize plugin" pluginId=optimax-historian-datasource error="Unrecognized remote plugin message: \nFailed to read any lines from plugin's stdout\nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is missing dynamic-link libraries necessary to run,\n  the plugin is not executable by this process due to file permissions, or\n  the plugin failed to negotiate the initial go-plugin protocol handshake\n\nAdditional notes about plugin:\n  Path: /var/lib/grafana/plugins/optimax-historian-datasource/dist/gpx_backend_datasource_linux_amd64\n  Mode: -rwxrwxrwx\n  Owner: 1000 [optimax] (current: 1000 [optimax])\n  Group: 357 [357] (current: 357 [357])\n  ELF architecture: EM_X86_64 (current architecture: amd64)\n"
logger=context userId=1 orgId=1 uname=optimax t=2024-07-04T07:13:42.412618073Z level=error msg="Could not find plugin definition for data source" datasource_type=optimax-historian-datasource

```

what is myLOG.txt? I could assume it is still an SELinux problem but it is disabled now.

**Comment by marefr** [comment]
Thanks. 

> what is myLOG.txt? 

No idea. Something in your plugin? Definitely a permission problem, but not sure we can help further since it seems to be specific to your setup. Maybe try running with root user and inspect the logs and compare and/or see if you can find the myLOG.txt on disk

**Comment by chim678** [comment]
thank you! the problem is solved. This myLog.txt in datasource.go was the root cause of the issue.
