### ISSUE TITLE
Design: Internal link customization

### ISSUE THREAD

**Issue by evictorero** [grafana/grafana#88789]
**Goal**
We want to offer a quick action for "copy link" and share it internally.

**Before**
<img width="662" alt="Screenshot 2024-06-05 at 20 03 47" src="https://github.com/grafana/grafana/assets/51436795/2595e2c9-e7df-42b9-8d92-5a0789c9f4a9">

**After**

Open the dropdown options, where the internal link it will have "share internally" option as first
<img width="1440" alt="Dropdown" src="https://github.com/grafana/grafana/assets/51436795/bc37bc10-d3c4-4df5-ad90-cfd2747d4b79">

Then, it will open this drawer for the link settings.
<img width="1448" alt="InternalLink" src="https://github.com/grafana/grafana/assets/51436795/93a22b77-f3a1-4408-9e3e-7ed6cbbcc1b5">

https://github.com/grafana/grafana/assets/51436795/dc850056-c8b4-4230-882d-41b1aaf05330

**Comment by imatwawana** [comment]
I've made comments on the Figma file with suggested edits to the copy
