### ISSUE TITLE
Export options (PDF)

### ISSUE THREAD

**Issue by lucychen-grafana** [grafana/grafana#88807]
**Before**

**PDF**
<img width="741" alt="Screenshot 2024-04-05 at 14 30 38" src="https://github.com/grafana/grafana/assets/51436795/8ab2908d-8bd9-4602-ae97-db67f60777be">

**Now**

**PDF**
<video src="https://github.com/grafana/grafana/assets/51436795/f2d46a2c-7953-488e-931d-a69b3e02e768" />

**We are changing with this task:**

- Having both actions PDF and JSON under an "`Export`" button action - new to our toolbar
- Keeping exporting behavior the same as sharing actions, inside a drawer

**PDF improvements**

- Keeping format PDF `Orientation` and `Layout`
- Removing the `Zoom` feature, since other options like **Zoom in** and **Zoom out** are not being used, we will keep the "standard" option by default
- Button changes to **"Download PDF"** with the lead icon for **"download"**

**Resources**
[Figma](https://www.figma.com/file/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?type=design&node-id=3118-42711&mode=design)

**Comment by natydej** [comment]
PDF formats in SVG @lucychen-grafana 

[PDF-Format.zip](https://github.com/user-attachments/files/16052425/PDF-Format.zip)

**Comment by natydej** [comment]
**Update:** Due some technical constrains and feasibility, we @grafana/sharing-squad decided to keep the current behavior. So, the pdf generation will be open in a new tab as it is, the only change will be the UI style and the CTA will be **"Generate PDF"** with the `external-link` icon
<img width="687" alt="Screenshot 2024-07-17 at 18 46 50" src="https://github.com/user-attachments/assets/070c8251-4c97-435f-a294-5bc7bc70adb8">
