### ISSUE TITLE
How to create no data alert rule for one of the multiple hosts?

### ISSUE THREAD

**Issue by perrfect** [grafana/grafana#88808]
Hello. 
How to correctly create Grafana alerts when no data logs from one of the hosts? I'm using the Loki datastore in Grafana.
And the problem is when there are no logs from a host I don't see the line from this host in the alert rule, so I can't create a trigger when data is zero.
my query A looks like:
`count_over_time({hostname=~"test-.*"} | keep hostname [10m])`

and I'm getting the results

```
{hostname="test-01"} 5
{hostname="test-02"} 34
{hostname="test-03"} 7
```

My alert condition is - when A is below 1
But when I stop Promtail client and don't get logs (for example test-01) the line {hostname="test-01"} does not equal zero, but simply disappears from results, so the alert rule doesn't work.

I'm trying create another alert request, but in this case I have the same result:
`count_over_time({hostname=~"test-.*"} | keep hostname [20m]) - count_over_time({hostname=~"test-.*"} | keep hostname [10m]) == count_over_time({hostname=~"test-.*"} | keep hostname [10m])`

- **Grafana version:** 11.0.0
- **Loki datasource**: 3.0.0
- **Promtail version:** 2.9.7

**Comment by tonypowa** [comment]
Hi @perrfect 

Thanks for reaching out. GitHub is mainly used for tracking bugs and feature requests. Your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) You are also welcome to ask in our [Community Slack](https://slack.grafana.com/)

We appreciate your understanding.
