### ISSUE TITLE
Search v2: Add support for soft deleted dashboards

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#88825]
Following up #83131 that introduces: a new `deleted` column in the `dashboard` table for marking soft deleted dashboards (when the feature `dashboardRestore` is enabled)
We need to add support to search v2 so that it takes into account the `deleted` column when listing dashboards same as it happens for the [search](https://github.com/grafana/grafana/pull/83131/files#diff-c304ec803eafc0532ffa40ee09e5c3606c84781803ec2c0f9160a34b95f35891) endpoint

We need this otherwise it's not possible to have both the `dashboardRestore` and the `panelTitleSearch` features enabled.

**Comment by inf0rmer** [comment]
For reference, this is the PR that implemented support in Search V1: https://github.com/grafana/grafana/pull/89283/files
