### ISSUE TITLE
Bytes on Y-Axis have different order of magnitude than in the tooltip

### ISSUE THREAD

**Issue by paulbruzz** [grafana/grafana#88820]
### What happened?

![image](https://github.com/grafana/grafana/assets/83400339/fb651b6e-c16a-471c-9fd7-e73c7af90921)

When building a time series graph with a Prometheus data source (PromQL query: ` process_memory_usage_bytes{job="$job_name"}` and "Bytes(SI)" set as the unit, for some reason the tooltip shows a value in MB but the same value is represented as 10 times bigger in the graph, with GB being used for the Y axis.
What could be the possible reason for this? How can this be fixed?
Thank you in advance.

### What did you expect to happen?

Megabytes being used for the Y axis with the tooltip value being correctly reflected

### Did this work before?

I hadn't tried this on another version of Grafana

### How do we reproduce it?

1. Create a dashboard with a Prometheus data source
2. Run a query with `process_memory_usage_bytes`
3. Select "Bytes(SI)" as unit and "Time Series" as visualization type

### Environment (with versions)?

Grafana: Cloud
OS: Windows
Browser: Edge

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by UnrealCraig** [comment]
It looks like you are stacking your data in the graph.
If you have 11 data points stacked then the total will be 11 times the average.

**Comment by tonypowa** [comment]
Hi @paulbruzz 

Thanks for reaching out. Hope the answer provided by @UnrealCraig pointed you in the right direction.

Your reported issue is better suited for our[ community forums.](https://community.grafana.com/) You are also welcome to ask in our [Community Slack](https://slack.grafana.com/) 

We appreciate your understanding.

**Comment by paulbruzz** [comment]
Hello @tonypowa 

I haven't had the chance to verify @UnrealCraig 's assumption because I later scrapped the dashboard I was working on and moved to another task.

However, I thank you both for your consideration.

Best regards.
