### ISSUE TITLE
Azure Monitor datasource: Saving default subscription does not work

### ISSUE THREAD

**Issue by vainikkaj** [grafana/grafana#88828]
### What happened?

After setting up required configuration (tested with both Workload Identity and Current User) for Azure Monitor datasource, the list of available subscriptions is populated correctly. Single item can be selected for being default subscription and there are no errors when Save and Test is pressed.

![image](https://github.com/grafana/grafana/assets/661992/975ca211-fdee-4294-9628-6cfcef6af588)

However, the default is gone when page is re-visited later.

![image](https://github.com/grafana/grafana/assets/661992/1c9ce7e4-a385-4424-b78f-1dc89077a761)

### What did you expect to happen?

I expect default subscription selection to be saved.

### Did this work before?

N/A

### How do we reproduce it?

1. Setting up Azure Monitor datasource (we tested this with Workload Identy & Current User)
2. Repeating the steps in screenshots

### Environment (with versions)?

Grafana: v11.0.0 (83b9528bce)
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Azure Monitor

**Comment by UnrealCraig** [comment]
We see exactly the same behaviour.
Every time we use that datasource we have to select the subscription; it would be much better if the default worked!

**Comment by aangelisc** [comment]
Fix has been merged and released, closing this now but please re-open if the issue reoccurs!
