### ISSUE TITLE
Getting details of current logged in user

### ISSUE THREAD

**Issue by sanchita1305** [grafana/grafana#8882]
I am new to grafana,
I want to use different value for a variable for different users to be used in a query.
is there a way i can get current user in a variable and use that variable in a query?
i know there is an API to get that user but not sure how to do it from frontend.

**Comment by torkelo** [comment]
contextSrv.user

**Comment by daniellee** [comment]
ref #4922

**Comment by stullii** [comment]
I'm quite a noob with Grafana, just started using it last week... Now I have the same problem as sanchita1305... how am I supposed to use "contextSrv.user" in a query? I tried it as it is, with a leading $, with curly braces....nothing worked...

**Comment by daniellee** [comment]
@stullii `contextSrv.user` would work if you were building a custom plugin and getting the user details via javascript. It is not currently possible in Grafana but see https://github.com/grafana/grafana/issues/4922#issuecomment-218302378 for a possible solution.
