### ISSUE TITLE
[Bug] Range Singlestat randomly changes to unexpected values

### ISSUE THREAD

**Issue by jgrvs** [grafana/grafana#8883]
Running v4.1.1 with graphite data source. I have a continuous cumulative multi-day count metric, and I want just the count from current day. I have a single state using range option and time selection of "Today so Far" refreshing every 30s to get what I need. However, the value will sometimes be correct but will flicker to other seemingly random values sometimes. (i.e. it will be 0 the next time it refreshes 46). Also tried the Delta option with similar results.

**Comment by torkelo** [comment]
Check how to troubleshoot metric query guide on the community site, there you can  check the graphite responses. 

Very likely a graphite issue or query issue and not a grafana bug. Make sure the stat option in the singleatat options tab is set to current.
