### ISSUE TITLE
[Bug] Heatmap render error when using log scale and value == 0

### ISSUE THREAD

**Issue by geekdave** [grafana/grafana#8884]
> What Grafana version are you using?

Grafana v4.4.1 (commit: 6a9f8ca)

> What datasource are you using?

InfluxDB

> What OS are you running grafana on?

Ubuntu 14.04

> What did you do?

1. Set up a heatmap panel using the query `SELECT "value" FROM $Measurement WHERE $timeFilter`
2. Tried both `linear` scale (worked), and `base 2` (got error)

> What was the expected result?

Expected heatmap to render, which it does when scale is set to `linear`

![grafana_-_k6_load_testing_results](https://user-images.githubusercontent.com/1438478/28338026-c5b12716-6bc4-11e7-9fdd-dbdad5d0602c.gif)

> What happened instead?

When scale set to `base 2` I get this error:

![grafana_-_k6_load_testing_results](https://user-images.githubusercontent.com/1438478/28338089-07372924-6bc5-11e7-98b7-f2c09e501dbf.gif)

This seems to be a client-side rendering error, since the data appears to come back just fine.

> Include raw network request 

```
Request URL:https://xxxxxxxxxxxx/api/datasources/proxy/3/query?db=k6&q=SELECT%20%22value%22%20FROM%20http_req_duration%20WHERE%20time%20%3E%201500408854675ms%20and%20time%20%3C%201500408988700ms&epoch=ms
```

> & response

```
{"results":[{"statement_id":0,"series":[{"name":"http_req_duration","columns":["time","value"],"values":[[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],[1500408863767,0],
[...snip...]
[1500408981758,4.751515],[1500408982178,5.140055],[1500408982178,4.79091],[1500408982179,4.73336],[1500408982612,5.343223],[1500408982762,4.283681],[1500408983182,4.55624]]}]}]}
```

# NOTE

If I change the query to exclude zero values, then the heatmap renders just fine.  

`SELECT "value" FROM $Measurement WHERE $timeFilter and value > 0`

![grafana_-_k6_load_testing_results](https://user-images.githubusercontent.com/1438478/28338394-0f3a1a2c-6bc6-11e7-8411-27f10bf72cbb.gif)

**Comment by torkelo** [comment]
thanks for reporting this. Looks like a bug.
