### ISSUE TITLE
[Bug] Text box "text" mode does not show text

### ISSUE THREAD

**Issue by Andy--Rose** [grafana/grafana#8885]
When importing dashboards from 3.1.1 into 4.4.1, I noticed that text boxes didn't show text. When I click the "View" option for the object and go back, the text displays. Curious if this was a change to the JSON attributes, I created the object from scratch on a new dashboard. The behavior was replicated with my text not shown.

Please include this information:
- What Grafana version are you using?
4.4.1
- What datasource are you using?
MySQL
- What OS are you running grafana on?
CentOS 7
- What did you do?
Created a Text object with the mode "text" selected (instead of "html" or "markdown")
- What was the expected result?
Text would appear when the page was loaded. 
- What happened instead?
Text is not visible unless the object is viewed individually or you enter edit mode for the object. 
Also, in edit mode, even though I selected "text" as the mode, it shows "markdown" when the page is reloaded.
For additional debugging, I tried converting away from windows line endings and inserting the text back in and that did not help. 

Initial load of the page:
![image](https://user-images.githubusercontent.com/4985657/28341340-8135e58e-6bd0-11e7-8f8b-71e410e26f77.png)

After clicking on "Edit" for the object.
![image](https://user-images.githubusercontent.com/4985657/28341358-95475648-6bd0-11e7-9c85-79e34c7a71e3.png)

**Comment by Jonnymcc** [comment]
Looks like text mode was removed, is this still an issue?

**Comment by torkelo** [comment]
no, you right, we can close this
