### ISSUE TITLE
[Bug]: Graph Histogram mode changes series name of first series to count

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8886]
<img width="915" alt="screen shot 2017-07-19 at 10 21 37" src="https://user-images.githubusercontent.com/10999/28357553-21e16fc6-6c6c-11e7-8ba1-303899b54e6d.png">

**Comment by torkelo** [comment]
@alexanderzobnin looks like a minor bug so not super high prio, but likely a quick fix :)

**Comment by alexanderzobnin** [comment]
In this case, what do we expect? 1 series _count_, or original series, or something else?

**Comment by torkelo** [comment]
good question, had not thought about it. Maybe original series names is best as then you can show the legend & legend values, and see combined histogram

**Comment by alexanderzobnin** [comment]
I don't remember right now, seems, seems I just use first existing series as a container for aggregated histogram data (but why another series are shown in the legend?..). I'll check it.

**Comment by torkelo** [comment]
this is still a problem as it makes it impossible to change color of the histogram series. Since the first series changes name, first it's name is what the TSDB returns so gets color based on that, then gets changed to count.  so if you try to change color based on count name it resets on next refresh.
