### ISSUE TITLE
Explore: Inconsistency in log colour and "level" label value

### ISSUE THREAD

**Issue by micobg** [grafana/grafana#88874]
### What happened?

![Screenshot from 2024-06-06 22-10-47](https://github.com/grafana/grafana/assets/1549276/ef060279-bdd4-49ed-880f-15a966a2ce96)
`level` label doesn't correspond to the severity of the log and therefore the colouring is wrong.

### What did you expect to happen?

Critical and debug logs should not be green. Their `level` should not be `info`.

### Did this work before?

No.

### How do we reproduce it?

```python
import json
import logging

import logging_loki


class CustomLokiFormatter(logging.Formatter):
    def format(self, record):
        return json.dumps({
            "level": record.levelname.lower(),
            "message": record.getMessage(),
        })

handler = logging_loki.LokiHandler(
    url="http://localhost:3100/loki/api/v1/push",
    tags={'application': 'test-log-color'},
    version="1",
)
handler.setFormatter(CustomLokiFormatter())

logger = logging.getLogger('test-logger')
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

logger.debug('Debug log')
logger.info('Info log')
logger.warning('Warning')
logger.error('Error log')
logger.exception('Exception log', exc_info=Exception('Test exception'))
logger.critical('Critical log')

```

### Environment (with versions)?

Grafana: 11.0.0-preview
OS: Ubuntu 20.04
Browser: Brave

### Grafana platform?

Docker

### Datasource(s)?

Loki (main-e9b6ce9)

**Comment by matyax** [comment]
@micobg Thanks for reporting this issue! The level is based on the `level` label (or `detected_level` when available). Severity is not used.
