### ISSUE TITLE
Limited Prometheus Data

### ISSUE THREAD

**Issue by LordGorgul** [grafana/grafana#8889]
Hi,

I'm gathering data about our SAN switches with Prometheus and the snmp_exporter. As long as I have up to 9 different metrics (from Brocade MIBs), the data display in a Grafana graph works just fine. But when I have more than 9 metrics, I can't see any data in Grafana anymore.
![grafana](https://user-images.githubusercontent.com/30114728/28364806-6372a33c-6c86-11e7-8133-a37ccf27977f.PNG)

In Prometheus I can still see everything (including the new metrics).
It's not just that I have too much information to be displayed at once in a single graph but I also don't get any data when creating a new graph.

Does anyone have an idea why this happens?

**Comment by torkelo** [comment]
It's likely a prometheus / prometheus query issue, please investigate the raw query response from Prometheus.

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by torkelo** [comment]
Sorry for got to add, that I have never heard of an issue like this with prometheus, so it's likely something that is amiss

**Comment by LordGorgul** [comment]
![graph2](https://user-images.githubusercontent.com/30114728/28407756-8ea0e942-6d35-11e7-8549-13b6b84e69a0.PNG)

just a down time where I changed the config
