### ISSUE TITLE
Docs feedback: http_api/dashboard_versions.md

### ISSUE THREAD

**Issue by ddhirajkumar** [grafana/grafana#8890]
I was looking at the HTTP API documentation on these two pages:-
* http://docs.grafana.org/http_api/dashboard/
* http://docs.grafana.org/http_api/dashboard_versions/

The dashboard API refers to a dashboard by it's url-friendly slug whereas the dashboard_versions API refers it using the internal ID. 
Why is there an inconsistency in the way to refer to a dashboard?

**Comment by torkelo** [comment]
because we are going to migrate to id only as the id is better (slug can change)
