### ISSUE TITLE
Error when provisioning Tempo logs/metrics configuration.

### ISSUE THREAD

**Issue by JMora77** [grafana/grafana#88919]
### What happened?

When trying to implement tracesToLogs and tracesToMetrics, the changes did not appear in grafana. I can set them up manually but not provisiong them with gitops.

I even used the default tempo configuration provided by the documentation:

```apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: EbPG8fYoz
    url: http://localhost:3200
    access: proxy
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: 'loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: 'method="${__span.tags.method}"'
      tracesToMetrics:
        datasourceUid: 'prom'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      tracesToProfiles:
        datasourceUid: 'grafana-pyroscope-datasource'
        tags: ['job', 'instance', 'pod', 'namespace']
        profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
        customQuery: true
        query: 'method="${__span.tags.method}"'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: 'Tag'
        tag: 'http.path' 

```

I made sure that the Datasourceuids matched the ones from the mimir and loki, but still did not work.

All 3 databases are working as expected, and when the tracetometrics and tracetologs parameters are given manually it also works as expected.

### What did you expect to happen?

I expected the configurations to appear in the connections section.

### Did this work before?

Nope, implementing this for the first time.

### How do we reproduce it?

1. Try to provision the datasource with trace to metrics and trace to logs.

### Environment (with versions)?

Grafana: 11.0.0
Helm chart: 11.3.3
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by qodirovshohijahon** [comment]
@JMora77 
It worked when I did it like this

tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '3h'
        spanEndTimeShift: '-3h'
        # tags: ['job', 'instance', 'pod', 'namespace'] I have removed this line due to it will get automatically from span
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{"$${__span.tags}"} |="$${__trace.traceId}"'

**Comment by JMora77** [comment]
@qodirovshohijahon 
Thanks for your answer.

Could you elaborate a little? Do you think removing the tags made the difference or did it work from the start?
Also, what Grafana version are you using?

**Comment by JMora77** [comment]
I forgot to add apiVersion: 1 at the top of the file.

It is working as expected now.
