### ISSUE TITLE
[Bug] Grafana logs an IAM credentials error when running in an ECS task

### ISSUE THREAD

**Issue by bwhaley** [grafana/grafana#8891]
- What Grafana version are you using?
```
# /usr/sbin/grafana-server  -v
Version 5.0.0-pre1 (commit: af56cc4)
```

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Docker in ECS (official grafana/grafana docker image)

- What did you do?
Tried to authorize with the container instance's ECS task role.

- What was the expected result?
Successful/correct authentication as the ECS task role.

- What happened instead?
The following error:

```
t=2017-07-19T21:27:06+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I updated to master because I had the same problem as noted #8750. Maybe that isn't fully fixed yet?

**Comment by techgnosis** [comment]
I'm having a similar but  different error when running in an ECS task. When I look at the grafana logs it looks like it is using the IAM role for the ECS container instance and not the ECS task role. Which means that the SDK version is too low. Per the AWS ECS documentation.

The following AWS SDK versions and above support IAM roles for tasks:
    AWS CLI: 1.10.47
    C++: 0.12.19
    CoreCLR: 3.2.6-beta
    Go: 1.2.5
    Java: 1.11.16
    .NET: 3.1.6
    Node.js: 2.4.7
    PHP: 3.18.28
    Ruby: 2.3.22
    Python (botocore): 1.4.37
    Python (Boto3): 1.4.0
    Note
    The botocore module provides the low-level core functionality for Boto3, and each version of Boto3 supports a range of botocore module versions. For Boto3 support of IAM roles for tasks, you must ensure that your underlying botocore module is at least the minimum version shown above.

**Comment by bwhaley** [comment]
In your container do you see the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI env
var set? The ECS agent should populate that var automatically if it’s >=
v1.11.0 and the task definition is configured to use an IAM role. (As per
the AWS docs
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
)

On Tue, Sep 5, 2017 at 11:37 AM, James Musselwhite <notifications@github.com

**Comment by techgnosis** [comment]
Yep, I jumped into the container and ran

curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

and the credentials were there. Grafana was still trying to use the instance role.

**Comment by techgnosis** [comment]
Woops, my reported bug is already fixed in https://github.com/grafana/grafana/issues/8750 for version 5.0

Sorry for the thread hijack!
