### ISSUE TITLE
[Bug] (Prometheus Datasource) Value Groups/Tags experimental feature missing both Regex field preventing use of query_result and missing unique pass on label_values calls

### ISSUE THREAD

**Issue by r4j4h** [grafana/grafana#8892]
Please include this information:
- What Grafana version are you using?
4.4.1

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Debian Jessie

- What did you do?
Tried to add Template Variables to a dashboard along with Experimental Groups/Tags feature.

- What was the expected result?
Expected to be able to use query_result call passing a `sum by()` prometheus query to reduce set to unique cardinality, or expected to have label_values automatically do this (as it appears to for Query).

- What happened instead?

label_values works but shows for each entry, resulting in the same tag shown *n* times where *n* is the number of time series. Notice how many redundant tags there are:
![screen shot 2017-07-19 at 2 49 03 pm](https://user-images.githubusercontent.com/703007/28391129-9a280d76-6c91-11e7-881d-759cc2a44182.png)
For reference here are the settings that created it:
![screen shot 2017-07-19 at 2 49 10 pm](https://user-images.githubusercontent.com/703007/28391130-9a2d2dec-6c91-11e7-84c6-c74ed67e2d4a.png)
It should be noted that the tags **do** function in this setup.

There seems to be no way to unique them, but I would expect for there to be because when I put the same query into Query it does:
![screen shot 2017-07-19 at 2 51 38 pm](https://user-images.githubusercontent.com/703007/28391188-cdb980ca-6c91-11e7-83d4-cf036ab32ee3.png)

Notice how default and cob-e2e-testing only appear once each in the preview list at the bottom.

----------

Using query_result returns raw Prometheus data in string format but I am unable to parse or transform it into something usable. For the above Query there is a "Regex" field provided to parse these strings, but none is provided for these additional tag/grouping queries. The summing technique in the query does seem to remove the duplicate entries though functionality is broken with the tags as there is no easy way to tie them back together in the "tag values query".

![screen shot 2017-07-19 at 2 50 03 pm](https://user-images.githubusercontent.com/703007/28391131-9a3eba08-6c91-11e7-8711-b082d77b6af5.png)
![screen shot 2017-07-19 at 2 49 54 pm](https://user-images.githubusercontent.com/703007/28391128-9a274134-6c91-11e7-9bec-27e69cf0f90c.png)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I can provide this if you'd like but the above is pretty reproducible and seems it's functionality lacking and not a syntax bug. The closest related aspect was my attempts to parse the query were only added to the URL and not run against the result, which made those requests invalid.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/8040

**Comment by Keleir** [comment]
+1

> Version: `4.3.0`
> DataSource: prometheus

**Comment by r4j4h** [comment]
Works great, thanks so much :)
