### ISSUE TITLE
$timeFilter for Prometheus

### ISSUE THREAD

**Issue by sia-s** [grafana/grafana#8893]
It would be helpful if a variable like $timeFilter was available for Prometheus queries. For example I want the following query when dashboard time range is last 3 hours:

sum(api_request_status_count[3h])

and the following when last 30 minutes is selected:

sum(api_request_status_count[30m])

**Comment by torkelo** [comment]
What about absolute ranges? You have $__interval and $__interval_ms built in variables you can use today. 

Not sure timeFilter makes any sense, maybe $__range

**Comment by sia-s** [comment]
I'm showing the result in a table. Basically number of each status during last hour or whatever the range of the dashboard is. I think $__interval is more useful for graphs for example to calculate an average for each point. You're right; what I'm looking for is not time filter but the range of the dashboard. is $__range available? I don't see it in 4.2

**Comment by torkelo** [comment]
no, there is no $__range

**Comment by miaoyahong** [comment]
I am a Chinese programmer, my MySQL table useful two fields stored timestamp, one is a Date, the other one is Time.
How do I use $_timeFilter?As if $_timeFilter does not support multiple (),
e.g. $__timeFilter(UNIX_TIMESTAMP(LDate)+time_to_sec(LTime))
 --- replaced ---->
 UNIX_TIMESTAMP(LDate >= FROM_UNIXTIME(1500729562) AND UNIX_TIMESTAMP(LDate <= FROM_UNIXTIME(1500902362)+time_to_sec(LTime)) .
in addition,when the MySQL can use the variables?

**Comment by daniellee** [comment]
@miaoyahong you can ask questions on https://community.grafana.com/

This sounds similar to this [question](https://community.grafana.com/t/using-sql-timefilter/1686/2?u=daniellee).

**Comment by SirEdvin** [comment]
@torkelo What about this issue? Without range variable, I can't create single stat with, for example, visitors to site.

**Comment by torkelo** [comment]
sure you can, there are functions in prometheus that allows you to aggregate using sum, and pick the total value in singlestat options

**Comment by SirEdvin** [comment]
I mean something for example "Visits on sate at <grafana interval>". I can't make `delta` without timeRange variable.

**Comment by torkelo** [comment]
not sure I understand, you can get visits at site during dashboard time range, is that not what you want?

**Comment by SirEdvin** [comment]
I am totally sorry for this, I make a stupid mistake(

I just should select right option for Single Stat panel (delta).

Sorry for this, have a nice day!

**Comment by srikanta50** [comment]
@torkelo, i really need your help here.

While i am using default time range(last 30m, 24h or 2d), below query is working fine and showing the appropriate count. 
Query:
sum by (app)(increase(orders_success_seconds_count{app="$app", exception="none"}[$__range]))
Pic:
![image](https://user-images.githubusercontent.com/51711089/82344202-5e927700-9a11-11ea-9400-5ee86614eb2e.png)

But while i am giving custom time range the graph it changing which should not be proper one as its a counter metric. Which should be 199K as per the above snapshot.

![image](https://user-images.githubusercontent.com/51711089/82344726-0a3bc700-9a12-11ea-99e4-d1dce3d30dec.png)
 I haven't found any error in the query inspector. (for $__range getting this value: &start=1589863500&end=1589868045&step=15")

Given Time Range is :
![image](https://user-images.githubusercontent.com/51711089/82345004-5e46ab80-9a12-11ea-9193-b6497249a42d.png)

My current requirement is: Want to see the order count number for a particular time range.

Thanks,
Srikanta
