### ISSUE TITLE
Dashboards: Strange DNS traffic for releases after 10.2.3

### ISSUE THREAD

**Issue by dfsnow** [grafana/grafana#88951]
### What happened?

I'm running Grafana at home and recently noticed some suspicious looking traffic being blocked by my local DNS server (see below for a screenshot). After some investigating, it seems that these requests are coming from desktop Safari clients that load any local Grafana page from Docker image 10.2.3 or above. Some details:

- The requests can be triggered by a page refresh. Clicking through the UI does not trigger them.
- All Safari extensions are disabled.
- Safari version 17.4.1, macOS version 14.4.1.
- Chromium and Firefox do not produce the requests.
- Safari iOS clients do not produce the requests.
- tcpdump confirms this is client-side.
- Docker image 10.2.2 and below does not produce the requests.

<img width="1186" alt="Screenshot" src="https://github.com/grafana/grafana/assets/31494343/f1a6b941-6380-4a6a-95d4-35906b68419c">

It's entirely possible that this is a problem with the client/my MacBook (malware, etc.). However, I think that's unlikely as it's a relatively new machine, only Grafana produces these requests, and the requests are specific to an existing image.

I don't see anything glaringly wrong with the [10.2.3](https://github.com/grafana/grafana/releases/tag/v10.2.3) tag, but I'm also unfamiliar with Grafana's stack.

### What did you expect to happen?

I expected DNS requests only to expected URLs (grafana.com, etc.).

### Did this work before?

Yes, 10.2.2 has clean traffic when accessing the UI. All versions 10.2.3 and after yield the strange traffic.

### How do we reproduce it?

This seems specific to macOS and Safari, so it may be hard to reproduce. However, see the details listed above for my setup.

### Is the bug inside a dashboard panel?

No, it happens on all Grafana pages.

### Environment (with versions)?

Grafana: 10.2.3+
OS: macOS 14.4.1
Browser: Safari desktop 17.4.1

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by paidhima** [comment]
Confirmed I am seeing these requests as well. MacOS 14.5, Safari 17.5. The DNS requests are not made when running Firefox. Changing the user agent in Safari has no effect. The traffic appears reliably after logging into the web interface.

**Comment by KristianGrafana** [comment]
Hey @dfsnow and @paidhima 

Thanks for bringing this to our attention. We have been investigating this internally, and came to the conclusion that Safari does something called "DNS prefetching". This method pre-resolves hostnames through DNS and cache them for later use. The browser will resolve any hostname found in a response to save time. This seems to stem from the "News" (Latest from the blog) panel.

According to our investigations, we found that the DNS lookups did not happen when DNS prefetching was turned off in Safari. 

To turn off DNS prefetching, you can set the `x-dns-prefetch-control: off` header in Grafana. To set a header, please see the [[server.custom_response_headers]](https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L91) configuration option.

**Comment by dannyc-grafana** [comment]
To explain the behavior we think is responsible a bit further:

The Grafana splash page you hit after logging in has several links to external sites-- namely, our blog, our community discourse, and our community slack. Some of these sites (community discourse specifically) have at least some advertising scripts. It appears that Safari sees these links and is doing some form of speculative loading on the pages they point to (https://developer.mozilla.org/en-US/docs/Web/Performance/Speculative_loading), which further triggers speculative DNS requests to the domains mentioned. 

You can replicate the no-prefetch behavior for local testing by injecting a `<meta http-equiv="x-dns-prefetch-control" content="off">` tag into your index.html. 

We're looking into what changed to cause the speculative loading behavior to be different as of 10.3, but there isn't great documentation on this feature in Safari unfortunately, so that search may take a while.

**Comment by paidhima** [comment]
This is all great info, thank you. It should have occurred to me that Safari DNS prefetch/speculative loading was involved. It would be interesting to know what changed to cause this behavior now, but I'm glad that my hunch was correct and there's nothing malicious/untoward going on.

**Comment by dfsnow** [comment]
Agreed! Thanks for looking into this. I made some posts elsewhere that I'll edit to point to this answer. Good to know nothing fishy is happening. I'm also super curious to know what changed between 10.2.2 and 10.2.3.

**Comment by tonypowa** [comment]
Thank you for reporting and sharing this @dfsnow !
Since this is not longer a concern, I'm closing the issue.
