### ISSUE TITLE
[Feature request] Possibility to change the opacity of the bars in a bar chart 

### ISSUE THREAD

**Issue by coolchip** [grafana/grafana#8896]
- What Grafana version are you using?
v4.4.1 (commit: 6a9f8ca)
- What datasource are you using? 
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04

I made a graph with lines and bars. Because the bars ars solid color, they are very present. Would it be possible to set the opacity of the bars like the opacity of the line fill? Perhaps with the same "fill" parameter? This would be very helpful.

![haus](https://user-images.githubusercontent.com/7850591/28404991-c5fa4136-6d2b-11e7-9c8d-1659ecb7aa26.png)

**Comment by torkelo** [comment]
You can use lines with step mode and fill to achieve something very close to transparent bars

**Comment by coolchip** [comment]
That looks nice. Thanks
