### ISSUE TITLE
Grafana does not restart after upgrade.

### ISSUE THREAD

**Issue by pierreaubert** [grafana/grafana#88962]
### What happened?

After an upgrade from Grafana 10 to 11 (on Ubuntu 20.04.4), grafana server does not start.

`sudo -u grafana /usr/share/grafana/bin/grafana server --config /etc/grafana/grafana.ini`

is working but

`sudo systemctl restart grafana-server.service `

does not complete.

```
sudo systemctl status grafana-server.service 
○ grafana-server.service - Grafana instance
     Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: http://docs.grafana.org
```

I added debug logs in the ini file but nothing is showing up. I do not use SSH in this configuration, it is proxied by nginx.
It works well if started via the sudo line above.

Ideas?

### What did you expect to happen?

I expect Grafana to start :)

### Did this work before?

Yes

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11
OS: ubuntu 20.04.4
Browser: all

### Grafana platform?

APT

**Comment by tonypowa** [comment]
hi @pierreaubert 

Can you share the output of the `journalctl -u grafana-server.service` command after attempting to restart the service with systemctl? This may contain logs that are not captured in the Grafana debug logs.

Note; you might need to increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v11.0/troubleshooting/#troubleshoot-with-logs

**Comment by pierreaubert** [comment]
Hi, I have found the issue: /var filesystem was corrupted and a fsck fixed it. After that, grafana restarted nicely.
