### ISSUE TITLE
Query: missing apostrophe in query builder for InfluxDB SQL data source

### ISSUE THREAD

**Issue by bartvenmans** [grafana/grafana#88972]
### What happened?

I built an InfluxDB SQL query using the query builder in Grafana. Everything worked well until I added a second filter which resulted in the following error:

flightsql: rpc error: code = InvalidArgument desc = Error while planning query: SQL error: TokenizerError("Unterminated string literal at Line: 1, Column 248")
(Trace ID: 754b9b5526885735db488b180d8bcd7d)

The problem is that for the second filter, an apostrophe is missing at the end, which you can see in the Preview box.
![Screenshot 2024-06-10 at 11 21 36](https://github.com/grafana/grafana/assets/122388895/4abc87f3-6e74-408f-8c79-9399f94fabda)

### What did you expect to happen?

I would expect that for each additional filter, the correct syntax is used to build the query. Adding a apostrophe manually to the code solves the problem.

### Did this work before?

I don't know

### How do we reproduce it?

1. Add an InfluxDB SQL datasource
2. Create a query with the query builder
3. Add a second filter to the query

### Environment (with versions)?

Grafana: Grafana Cloud
OS: macOS
Browser: Google Chrme

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB SQL

**Comment by bossinc** [comment]
This should be fixed now in Grafana Cloud. Reopen if you are still experiencing this issue
