### ISSUE TITLE
Alert urls: Grafana alert urls not working under subpath and reverse proxy

### ISSUE THREAD

**Issue by dimitriskourlos085** [grafana/grafana#88974]
### What happened?

Specific Grafana urls not working when serving Grafana under subpath.
Seems that the subpath is not populated in the links. This results to the links not working when using Reverse proxy.

### What did you expect to happen?

Expected for the subpath to be populated in the links.

**example:**
the alert rule annotation links ( dashboard , panel ) links are as follows:

- https://{{domain}}/d/a18ef1af1afad0e84dae9155710ec07c_acc

But they should also have the subpath populated

- https://{{domain}}/grafana/d/a18ef1af1afad0e84dae9155710ec07c_acc

![Screenshot from 2024-06-10 12-14-08](https://github.com/grafana/grafana/assets/170091073/f286edb9-d39c-447f-80d6-50896a4e6bb1)

### Did this work before?

Didn't work before.
Only works when using no reverse proxy.

### How do we reproduce it?

1. Setup grafana with subpath / reverse proxy
2. Create an alert , and link with panel ( Dashboard/panel annotation links )
3. Open the alerts ( https://intragate.ec.europa.eu/cc-grafana-prod/alerting/list)
4. Navigate to the created alert and expand
5. Try to click in one of the links ( Dashboard UID , Panel ID )

### Environment (with versions)?

Grafana: oss - 10.3.3
OS: Podman  - Rhel 8
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
Hello @dimitriskourlos085 

Thank you for reporting this issue

Could you confirm if you've set the root_url in your Grafana configuration to include the subpath, as per the [Grafana documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#root_url)?

It would be helpful to see your reverse proxy configuration (please mask any sensitive information).

Have you seen any error messages in the Grafana server logs or the browser console when the issue occurs? If so, could you provide them?

**Comment by dimitriskourlos085** [comment]
Hi @tonypowa  ,

thanks for your reponse.

The issue was fixed by upgrading to Grafana 11.2.0

Now by clicking the alert rule urls navigate to the dashboards including the grafana subpath.
