### ISSUE TITLE
[Bug] REST API for downloading dashboards is no longer compatible with dashboard JSON

### ISSUE THREAD

**Issue by mattheworiordan** [grafana/grafana#8897]
This is a new issue as of either 4.4 or 4.3, this is not a problem with 4.2.

### Problem

Previously the REST API to download a dashboard provided a JSON output that could then be uploaded back into Grafana.  The endpoint used is `/api/dashboards/db/[ID]`.

However, now the format of the JSON from the Grafana REST endpoint is quite different to the format of the JSON exported from the Grafana UI itself and most importantly incompatible when trying to upload again.  The result of uploading a JSON dashboard exported from the  REST endpoint results in an empty dashboard.

### Recreate

1. Download the dasboard

`$ curl --user [CREDS] https://[GRAFANA-URL]/api/dashboards/db/[DASHBOARD-ID] > dashboard.json`

2. Log into https://[GRAFANA-URL], go to Dashboards, Import, select the `dashboard.json` file you just downloaded, and immediately you see the error "A Dashboard should have a name".

The workaround is of course to manually export JSON from the Grafana UI itself, but this means we can no longer automate download and upload of dashboards which worked before.

### Comparison

Extract of JSON for a dashboard from the REST API endpoint:

```json
{  
   "meta":{  
      "type":"db",
      "canSave":true,
      "canEdit":true,
      "canStar":true,
      "slug":"frontend-bandwidth-by-instance",
      "expires":"0001-01-01T00:00:00Z",
      "created":"2017-04-07T15:36:25Z",
      "updated":"2017-04-12T16:15:10Z",
      "updatedBy":"ably",
      "createdBy":"ably",
      "version":4
   },
   "dashboard":{  
      "annotations":{  
         "list":[  

         ]
      },
      "editable":true,
      "gnetId":null,
      "graphTooltip":0,
      "hideControls":false,
 ....
```

Extract of JSON generated from the Grafana dashboard itself:

```json
{
  "__inputs": [
    {
      "name": "DS_ABLY_STATS",
      "label": "ably_stats",
      "description": "",
      "type": "datasource",
      "pluginId": "influxdb",
      "pluginName": "InfluxDB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "4.4.1"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "influxdb",
      "name": "InfluxDB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": []
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "hideControls": false,
  "id": null,
  "links": [],
  "refresh": false,
  "rows": [
...
```

### Environment

Grafana 4.4.1 connected to InfluxData 1.2.4 on Ubuntu 14 Trusty

**Comment by torkelo** [comment]
The api to read a dashboard is different from api to write (write does not have meta fields and it does have a overwrite flag). This has always  been the case. 

The UI export feature exports dashboard so they can be imported to another instance, this export feature adds info on used panels and datasources. The exported dashboard can be imported using the import api, which can handle datasource mapping. The exported dashboard is not to be used directly with the regular save dashboard, as the exported dashboard is templated (to enable datasource remapping). 

There has been no change in this since 3.1 when the UI export features was added and the import api added, it's when we added the dashboard repository on grafana.com as well. 

I can understand that this is a bit confusing. But the api is not simple crud, read and write are different and you can not simply take the output of a read and expect that to work in a write operation.

**Comment by mattheworiordan** [comment]
> I can understand that this is a bit confusing. But the api is not simple crud, read and write are different and you can not simply take the output of a read and expect that to work in a write operation.

Ok @torkelo thanks for the explanation, but I am honestly a bit confused as to what now needs doing. If we want to ensure that we can programatically export dashboards so that they can later be imported, how do we go about doing this?    The import process could be programmatic or not, I am less worried about that as that is a secondary problem and it's rare we need to upload dashboards from our exports.

**Comment by torkelo** [comment]
Just use the normal read / save api, should be documented on docs site

**Comment by mattheworiordan** [comment]
Thanks @torkelo, will try.

**Comment by hcguersoy** [comment]
@torkelo Can you please point us to the _read / save api_ which you have mentioned?
I don't find anything else then the dashboard API which @mattheworiordan has used (and I tried to use, too, running into this issue).

**Comment by marefr** [comment]
@hcguersoy [retrieve a dashboard](http://docs.grafana.org/http_api/dashboard/#get-dashboard), the dashboard property in response is what you use as payload to [create/save a dashboard](http://docs.grafana.org/http_api/dashboard/#create-update-dashboard) together with some additional properties (overwrite).
