### ISSUE TITLE
[Feature request] Allow Script filed with timestamp

### ISSUE THREAD

**Issue by michaeleino** [grafana/grafana#8899]
Information:
- Grafana Version: 4.4.1
- Datasource : Elasticsearch
- OS: Ubuntu 16.04.2 LTS
- Mathematical operation on timestamps
- no result, timestamp field not allowed to be selected on aggregations.
Ex. for Kibana we do a script field like:
doc['End_Time'].value - doc['timestamp'].value
then we could perform any type of aggregations...

I think we could be able to select timestamps on aggs, or to create a "scripted field" like we did in kibana.
Ref:
https://community.grafana.com/t/basic-elastic-search-query/1543/11

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/5968
