### ISSUE TITLE
[BUG] Templating reference to itself

### ISSUE THREAD

**Issue by Oxydros** [grafana/grafana#8901]
- What Grafana version are you using? Grafana v4.4.0-pre1 (commit: a9b87cee5) 
- What datasource are you using? InfluxDB

It seems that the regex that checks if the template possess a reference to itself bug.
Here is a screenshot.

'eventCountry' contains 'event', and the error is triggered. But 'eventCountry' != 'event'.

![07_20_1715_57_32](https://user-images.githubusercontent.com/1645673/28421142-8ffcfde2-6d64-11e7-8631-8c81efd7c1ab.png)

**Comment by torkelo** [comment]
fixed in 4.4.1, https://github.com/grafana/grafana/issues/7354
