### ISSUE TITLE
[ Feature request ] for table with multiple columns

### ISSUE THREAD

**Issue by tuxjockey** [grafana/grafana#8902]
Please include this information:
- What Grafana version are you using? 4.4.1
- What datasource are you using? Graphite
- What OS are you running grafana on? RHEL
- What did you do? Created tables in Grafana
- What was the expected result? I need multiple columns
- What happened instead? No option available

Hello there,

I have different tables which shows different stats like number of CPU cores, Total memory etc in the following format.

![grafana](https://user-images.githubusercontent.com/19564248/28425027-c37f73f2-6d8c-11e7-86c4-782156790d61.png)

likewise I have many tables for different stats for all my servers in different tables.

I would like to know if there is a way around to merge these tables so that I can get it in the below format:

![grafana1](https://user-images.githubusercontent.com/19564248/28424771-1a802dfa-6d8c-11e7-96df-b1588a6fb04d.png)

(created using excel for demo purpose)

The different stats for the same server need to be shown as different columns in single same table. This will really help me to import the data as a single csv file and create excel reports easily.

**Cheers**
 Tuxworm

**Comment by torkelo** [comment]
don't think this is going to be possible with Graphite

**Comment by tuxjockey** [comment]
Thanks for checking. Do you think using a different data source instead of Graphite will make this possible?

**Comment by torkelo** [comment]
Yes, MySQL

**Comment by tuxjockey** [comment]
Any KB/guidelines you could suggest on how this can be achieved? Sorry for asking.

**Comment by torkelo** [comment]
must be millions of SQL query howtos, but it depends on the table layout and query analytics you want to do. 

But the most simple would be 

```sql
SELECT server, disk_usage, memory_usage, cpu_cores FROM metrics 
```

**Comment by yesoreyeram** [comment]
@tuxinaut @torkelo I managed to create a plugin with the above requirement. 

If anyone interested try this [Boom Table Panel](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel)

**Comment by yesoreyeram** [comment]
@torkelo  - Could you reopen this issue?  I have created a prototype to achieve this and succeeded with that. Also i think that there will be lots of possibilities with the latest tagging support in graphite.

**Comment by yesoreyeram** [comment]
@tuxjockey  @torkelo  I have published a plugin to overcome this issue.  https://github.com/yesoreyeram/yesoreyeram-boomtable-panel . Please check and let me know if this helps

![Image](https://raw.githubusercontent.com/yesoreyeram/yesoreyeram-boomtable-panel/master/src/img/panel.png)
