### ISSUE TITLE
[Bug] Saving configured span when templating variable is set fails

### ISSUE THREAD

**Issue by dansat** [grafana/grafana#8903]
- What Grafana version are you using?
 Grafana v4.3.1 (commit: befc15c)
- What datasource are you using?
graphite . Configured mysql in grafana.ini
- What OS are you running grafana on?
Debian Jessie
- What did you do?
Set a templating variable, and created two different panels in one row.
Each panel is set with dimension span of 6, and min span of 6. For each panel, set the templating variable to the preconfigured variable. the panels are correctly displayed in the dashboard, and save this.  Switch to other dashboard and went back to original dashboard with 2 panels.
 
- What was the expected result?
The dashboard still showed 2x6 span panels, regardless whether the templating variable is set or not. 

- What happened instead?
Dashboard showed 2x12 span panels instead .Previous dimension span that was saved is not taken into account. 

If the step above is repeated , but "templating variable" is not selected (or disabled) then the saved dashboard correctly showed 2x6 span.

**Comment by torkelo** [comment]
Are you using the panel repeat feature? What is the current select value state of the repeated variable? If you repeat a panel based on a variable with only one selected value the  the panel will take up full width, there is only a minSpan option, no maxSpan
