### ISSUE TITLE
[Bug] phantomjs image rendering does not work over a unix socket

### ISSUE THREAD

**Issue by propertone** [grafana/grafana#8904]
When grafana is configured to listen on a unix socket, the call to phantomjs ignores the socket path and constructs the url as socket://localhost:3000/dashboard-solo/...

If it's not possible for phantomjs to connect over a Unix socket, grafana should at least use the root_url variable to fetch the page instead.

**Comment by marefr** [comment]
Closing this since PhantomJS is now removed in master/will be removed in Grafana v7.0, ref #13802
