### ISSUE TITLE
[Feature request] Offer selected value count as a variable on templates

### ISSUE THREAD

**Issue by DavidVentura** [grafana/grafana#8905]
I have a multi-value variable on a template and I'm trying to match ALL of the values selected instead of some of them. As noted [here](http://docs.grafana.org/reference/templating/#formating-multiple-values), the selected values form an OR group.

Selecting "value1", "value2", "value3" would match either of those 3 values.

What I propose is adding a counter for the checked values (in my example, 3), so I can use that variable for another query.

**Current query:**

`SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /$Service/`

**Interpolated:**
`SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /(value1|value2|value3)/`

**Desired query:**
`SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /$Service{$__len_Service}/`

**Interpolated:**
`SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /(value1|value2|value3){3}/`

- What Grafana version are you using?
 v4.4.1 (commit: 6a9f8ca)
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
debian

- What did you do?
try and filter a template using an AND criteria
- What was the expected result?
the template being filtered using an OR criteria
- What happened instead?
the template was filtered using an OR criteria

**Comment by DavidVentura** [comment]
Essentially what I'm saying is that:

When assigning a template variable, create a variable named __len_[variable] whose value is the length of the currently selected keys.
This would be useful to match all elements in a group (assuming non-repeating elements on the input)

**Comment by torkelo** [comment]
not sure I see the utility of this, what does the length give you?

```
SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /(value1|value2|value3){3}/
```

why do need the `{3}`

**Comment by DavidVentura** [comment]
I want to get the hosts that match that regex:

Example:
(server1)
"Service" = "mysql, influxdb, bind"
(server2)
"Service" = "mysql, bind"

checking "mysql" and "influxdb" currently generates 
`SHOW TAG VALUES WITH KEY = "host" WHERE "Service" =~ /(mysql|influxdb)/`
which match any hosts that meet either requirement.

I want to match the hosts that meet *both* requirements:

**Comment by torkelo** [comment]
Are you tag values for service a csv string?

**Comment by DavidVentura** [comment]
I have in each node the following global tags (telegraf):
```
Service="mysql influxdb bind"
S_1="mysql"
S_2="influxdb"
S_3="bind"
```

Then in grafana the Service variable:
`SHOW TAG VALUES WITH KEY =~ /S_/`

Now I can check either service but end up with an OR operation between everything I have checked

**Comment by torkelo** [comment]
So the tag keys are numbered, that won't work, will be very fragile, and require OR statement, not the regex you had above
