### ISSUE TITLE
Snapshots: Clarify publishing paths

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#89064]
### What happened?

The documentation here about publishing a snapshot is here https://grafana.com/docs/grafana/latest/dashboards/share-dashboards-panels/#publish-a-snapshot

It talks about two paths to publish, either to your local instance or to snapshots.raintank.io . The latter will allow you to publish a snapshot that can be accessed by anyone with the link.

Users commonly use custom panels to display data, and if a snapshot containing a custom panel is published to snapshot.raintank.io, if the plugin is not available, the snapshot receives an error. There have been instances historically where someone would upload the custom plugin to the snapshot server. This is not a path we want to support, and we should clarify this to people who come across this scenario.

### What did you expect to happen?

For an explanation, in either or both the documentation or in the app, describing the limitations on publishing to snapshots.raintank.io and that we do not allow uploading custom panels to that server.

### Did this work before?

A [forum post](https://community.grafana.com/t/snapshot-created-using-raintank-does-not-show-custom-panel-plugin/35772) indicates that it was possible to request upload of custom panels to that server historically.

**Comment by imatwawana** [comment]
We'll address this as part of the overall doc updates with the redesign of the sharing feature.
