### ISSUE TITLE
[BUG] Plain Queries visable and manipulable in Firefox DevTools

### ISSUE THREAD

**Issue by n3k232** [grafana/grafana#8906]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
        Version 4.2.0
- What datasource are you using?
       Influxdb
- What OS are you running grafana on?
       SLES12SP1
- What did you do?
       checked the performance on the Firefox DevTools and saw, that every one can manipulate the  Queries that Grafana is sending to the DB
Like this: MyHost:3000/api/datasource/proxy/1/query?db=myDB&q=show%20measurements&epoch=ms

should it be like this?

**Comment by torkelo** [comment]
yes, all queries are sent by the browser to the data source (either directly if access mode is direct, or via grafana's built in http proxy for data sources). 

If you use influxdb the user/password will not be exposed to the frontend. But any user can issue any query if they know http. This has always been the case.
