### ISSUE TITLE
[Bug] Cannot read property 'originalUrl' of undefined

### ISSUE THREAD

**Issue by CptSpade** [grafana/grafana#8908]
Hello,

I have an issue with the snapshot navbar. I create the snapshot with the HTTP API and use the url from the response into an iframe.

Here's a screenshot from the code where the error message comes from :
![capture d ecran 2017-07-21 a 17 09 13](https://user-images.githubusercontent.com/18116816/28469691-5d4a79be-6e37-11e7-9d25-e0f3ec04f9de.png)
https://github.com/grafana/grafana/blob/e7e675e4715ba80b4d72d8022a3fc72bf4b94631/public/app/core/nav_model_srv.ts

It works fine in local : showing what I putted into the json to generate the snapshot (dashboard - title).
{{ctrl.dashboard.title}} is what is get (cf screenshot)

GRAFANA VERSION : 4.3.2

![capture d ecran 2017-07-21 a 16 50 25](https://user-images.githubusercontent.com/18116816/28468913-c62458a4-6e34-11e7-9cfe-a615b5aef7d7.png)
![capture d ecran 2017-07-21 a 16 50 39](https://user-images.githubusercontent.com/18116816/28468912-c62413ee-6e34-11e7-8301-c822d4dda46a.png)

**Comment by torkelo** [comment]
use community site for development questions.

**Comment by torkelo** [comment]
oh, and when you open a topic in the development category be sure to include the json you push. Must be missing something in the json you push but without including it it's hard to say what.

**Comment by CptSpade** [comment]
The JSON is missing a snapshot object.

Add this property to the dashboard object :

`
"snapshot": {
  "timestamp": "when this snapshot was made",
  "originalUrl": "url to original dashboard this snapshot was made from"
}
`
