### ISSUE TITLE
[Feature Request] Additional Anonymous Mode Configs

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8909]
Finally opening the issue after some internal discussion w/ a client. 

Current Situation: 
Anonymous mode successfully strips the menu of actions that a non-logged in user wouldnt be able to do (data source, alerting, etc), however apps and the login link appears. 

In anonymous mode, a large percentage of users will see that login and reach a dead end when getting to the login screen. Especially without further instruction, it's not clear to the user whether it's a web service they need to sign up for, or if they need an account. It introduces a UX issue that needs to be addressed.

The admins would still be able to login by going directly to https://<URL>/login, which is suboptimal from a user perspective, but at least it lets them keep their users from hitting the brick wall.

For apps, I believe we'll need some additional permission checking for anonymous users piggybacking off of the `reqRole` field. I propose that we check to see if any functionality has ` "reqRole": "Anon",` and if no functionality is available to anonymous users, the app does not even appear in the side menu. 

Thoughts?

**Comment by torkelo** [comment]
> In anonymous mode, a large percentage of users will see that login and reach a dead end when getting to the login screen. Especially without further instruction, it's not clear to the user whether it's a web service they need to sign up for, or if they need an account. It introduces a UX issue that needs to be addressed.

but is this not pretty universal? to have sign in link for users with accounts? maybe a configurable login message grafana-server admins can configure that is shown somewhere on the login page and a back link can improve the the dead end experience. 

> For apps, I believe we'll need some additional permission checking for anonymous users piggybacking off of the reqRole field. I propose that we check to see if any functionality has "reqRole": "Anon", and if no functionality is available to anonymous users, the app does not even appear in the side menu.

Do we have any examples where showing the app in the sidemenu for anonymous users is not desired? anonymous users are at minimum assigned the Viewer role, so any dashboards / app links with Viewer role will be shown. Bit worried that introducing Anon role will cause some inconsistencies. (Is Anon role? but in anonymous config anonymous users are assigned a role, like Viewer or Editor)

**Comment by mattttt** [comment]
> but is this not pretty universal? to have sign in link for users with accounts? And some there is a signup tab when its enabled. maybe a configurable login message grafana-server admins can configure that is shown somewhere on the login page and a back link can improve the the dead end experience.

I think that's absolutely acceptable. As long as we're giving folks a way to set expectation for confused users, I'm cool with that. 

In the case of https://cloudflareperformance.com it would say something like, "This site is administered by Cloudflare. If you are an employee and need an account, please contact us. Public users do not need accounts."

> Do we have any examples where showing the app in the sidemenu for anonymous users is not desired? anonymous users are at minimum assigned the Viewer role, so any dashboards / app links with Viewer role will be shown. Bit worried that introducing Anon role will cause some inconsistencies. (Is Anon role? but in anonymous config anonymous users are assigned a role, like Viewer or Editor)

See same link above. Anonymous users have no need to view their endpoints or probes. worldPing is completely behind the scenes for them.

**Comment by torkelo** [comment]
> See same link above. Anonymous users have no need to view their endpoints or probes. worldPing is completely behind the scenes for them.

But should they not move worldping to a org that does not have public access in that case? Or should endpoint and probe pages require editor role instead of viewer?

**Comment by mattttt** [comment]
If they were hosting it themselves, it sounds like that solution would work. 

In this case, they are running Hosted Grafana though, which does not support multiple orgs. 

Hmm.
