### ISSUE TITLE
[Bug] Error 1115: Unknown character set: 'utf8mb4'

### ISSUE THREAD

**Issue by mboogert** [grafana/grafana#8910]
- What Grafana version are you using? grafana-4.4.1-1.x86_64
- What datasource are you using? mysql-server-5.1.73-5.el6_6.x86_64 
- What OS are you running grafana on? CentOS 7
- What did you do? try to connect to mysql datasource
- What was the expected result? succesfull connection
- What happened instead? Error 1115: Unknown character set: 'utf8mb4'
 
I'm trying to add a MySQL 5.1.73 datasource on a CentOS 6 server. The Grafana instance is connecting using the utf8mb4 charset, which is not available at MySQL 5.1.73.

The error thrown during "Save & Test" is : Error 1115: Unknown character set: 'utf8mb4'

It would be nice to be able to configure the character set from the UI in Grafana to enable an utf8 charset instead of the supplementary utb8mb4.

**Comment by daniellee** [comment]
duplicate: #8714. Is it possible to upgrade your mysql? Version 5.1 is nearly 10 years old.
