### ISSUE TITLE
[Bug] Weird difference of escaping in "Query" templating (InfluxDB)

### ISSUE THREAD

**Issue by djpable** [grafana/grafana#8912]
- Grafana 4.4.1
- InfluxDB

I'm using a template query as a filter in a panel. I have to disable "All"-value and "Multi"-value.
But doing this this piece of code exclude regex-escaping!
But i need regex escaping because my template is of string type and contains "\\" (backslashes).

Results i don't see any data. Please help me fixing this or doing a rapid workaround.

```
  interpolateQueryStr(value, variable, defaultFormatFn) {
    // if no multi or include all do not regexEscape
    if (!variable.multi && !variable.includeAll) {
      return value;
    }

    if (typeof value === 'string') {
      return kbn.regexEscape(value);
    }

    var escapedValues = _.map(value, kbn.regexEscape);
    return '(' + escapedValues.join('|') + ')';
  }
```

**Comment by torkelo** [comment]
If you dont use multi or all there is no need to use regex operator as your match will be an exact value, so you can use equality operator and enlose variable in quotes, this is done automatically by the UI query editor

**Comment by djpable** [comment]
Do you mean;
WHERE "event" = '$event' ?

In my case "event" is a tag
and $event is a template InfluxDB

In my query i put ...WHERE "event" = '$event' ...

but i obtain this response using "Inspector":

```
{
  "error": "error parsing query: found \\0, expected identifier, string, number, bool at line 1, char 56",
  "message": "error parsing query: found \\0, expected identifier, string, number, bool at line 1, char 56"
}
```

The issue is still Open for me...

**Comment by torkelo** [comment]
Does the variable have multi value or all value enabled? The  you need to use regex tag filter operator, read grafana InfluxDB templating docs

**Comment by djpable** [comment]
For security reasons I must disable All values and Multi values... so i solved forking core code for now:

```
  interpolateQueryStr(value, variable, defaultFormatFn) {
    // if no multi or include all do not regexEscape
    if (!variable.multi && !variable.includeAll) {
      // NB. I should do string escaping for InfluxDB LineProtocol (PM)
      // return value;
      return value
        .replace("\"", "\\\"")
        .replace("\\", "\\\\");
    }

    if (typeof value === 'string') {
      return kbn.regexEscape(value);
    }

    var escapedValues = _.map(value, kbn.regexEscape);
    return '(' + escapedValues.join('|') + ')';
  }
```

**Comment by torkelo** [comment]
You don't need to do that, just use equality operator instead of regex operator in your InfluxDB query,

**Comment by djpable** [comment]
Infact im using this WHERE condition:

... WHERE "event" = '$event' AND $timeFilter GROUP BY ...

But when there is a single backslash query goes on error...

**Comment by torkelo** [comment]
Can you show your variable settings?

**Comment by djpable** [comment]
I post a screenshot of the template and the panel's 
![template_event](https://user-images.githubusercontent.com/1133451/28566048-4c675c80-712e-11e7-96dd-47b226838b99.png)

query:
SELECT * FROM "General" WHERE "hostname" =~ /^$hostname$/ AND UserName =~ /^$user$/ **AND event = '$event'** AND car =~ /^$car$/ AND driver =~ /^$driver$/ AND GroupName =~ /^$groupname$/ AND $timeFilter GROUP BY "ChannelName" ORDER BY time DESC LIMIT 1

error in panel:
```
{
  "error": "error parsing query: found \\0, expected identifier, string, number, bool at line 1, char 56",
  "message": "error parsing query: found \\0, expected identifier, string, number, bool at line 1, char 56"
}
```

Solved escaping double quotes and backslashes in case of non-regex filters.
