### ISSUE TITLE
Relative Time: Issue When Browser and Computer Time Settings Differ

### ISSUE THREAD

**Issue by torresgallegos** [grafana/grafana#89137]
### What happened?

**Working Configuration:**

Data Timestamp: UTC
Browser Time Settings: UTC+2
Computer Time Settings: UTC+2
Selected Timezone in Grafana: Any timezone
Behavior: Filtering by "Last 30 Minutes" correctly displays the real last 30 minutes.

**Non-Working Configuration:**

Data Timestamp: UTC
Browser Time Settings: UTC+2
Computer Time Settings: UTC+5 (UTC+5 is an example. This could be any time different to browser Time)
Selected Timezone in Grafana: Any timezone
Issue: When filtering by Time Range "Last 30 Minutes", no data is displayed. It appears to filter by what is considered "future" last 30 minutes.

**Possible Bug:** 

The time range filter seems to malfunction under differing browser and computer time settings, leading to incorrect data filtering that assumes a future time range.

### What did you expect to happen?

We expect to see the real last 30 minutes of data, regardless of the browser or computer time settings.

### Did this work before?

No

### How do we reproduce it?

1. First, check the computer Time is the same as the browser.
2. If it is the same, create a dashboard including a Time Series Panel showing data for the last 30 minutes. Capture this image.
3. Change the computer Time to be different from the Browser.
4. Go to the previous dashboard and capture the image.
5. Both images will probably show different Time ranges when they should always show the last real 30 minutes.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:  10.0.3
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
Hello @torresgallegos  

Thank you for taking the time to report this issue

To help us understand and replicate the issue further, could you please provide the following details:

- Could you specify the operating system you're using along with its version? 

- Which browser(s) have you encountered this issue with? Please include version numbers if possible.

- Lastly ,could you attach screenshots or a screen recording showing the issue in action?

**Comment by tonypowa** [comment]
I’ll be closing this issue, but please feel free to request a reopening if you have any additional questions or concerns
