### ISSUE TITLE
[BUG] Example in documentation doesn't work...

### ISSUE THREAD

**Issue by djpable** [grafana/grafana#8913]
Following documentation for InfluxDB templating queries:
http://docs.grafana.org/features/datasources/influxdb/#templating

leads to this example

http://play.grafana.org/dashboard/db/influxdb-templated-queries

It's not working, if you select the host "server\second\slash" ONLY you obatin same data as "server\5".

It's related to bug #8912 not closed properly.

**Comment by torkelo** [comment]
Works fine when I test it, when I select any of the series I get only the selected host. 

Closing, please provide more detail if you think you have spotted a bug

**Comment by djpable** [comment]
I attatch some screenshots:
![host_all](https://user-images.githubusercontent.com/1133451/28511828-46fa27c6-704f-11e7-8945-606f5600dbb9.png)
This is the default page.

Then i select first host:
![host_server_5](https://user-images.githubusercontent.com/1133451/28511837-5a608332-704f-11e7-8994-532e9db1f499.png)

Finally i select the other host (i see same data):
![host_server_second_slash](https://user-images.githubusercontent.com/1133451/28511851-6b412c06-704f-11e7-91f1-2af48b8c86d6.png)

**Comment by torkelo** [comment]
you can see the legend (series name) is different, the graph is the same as the fake data source generates the same data for these series

**Comment by djpable** [comment]
Yes but when you see all together they don't look the same. For example the first value is < 5 (green) > 10 (yellow)

**Comment by torkelo** [comment]
Probably because they are stacked :)

**Comment by djpable** [comment]
I have solved, patching Grafana Core 4

![image](https://user-images.githubusercontent.com/1133451/43968948-ede5643c-9cc8-11e8-91da-d2d672a2f967.png)

Bug, still persist in Grafana 5 i'll try to patch it again.
