### ISSUE TITLE
[Bug] Region names in Cloudwatch templates call to invalid endpoint URLs

### ISSUE THREAD

**Issue by reliam** [grafana/grafana#8917]
- What Grafana version are you using? Grafana v4.4.1 (commit: 6a9f8ca)
- What datasource are you using? Cloudwatch (role/ARN based)
- What OS are you running grafana on? Amazon Linux (ami-a4c7edb2)
- What did you do? Attempt to use region names as template variables.
- What was the expected result? Switch region and see metrics for resources in selected region.
- What happened instead? Graphs error out and error messages spit out in logs.

It looks like whatever component is parsing the regions is passing the string, but wrapped in braces.

![image](https://s3.amazonaws.com/uploads.hipchat.com/121542/3274008/QNhR1XT7z9cpRrk/upload.png)

## The template setup for this item:
![image](https://user-images.githubusercontent.com/11980918/28534417-7c1ad288-7055-11e7-939e-5f1f551d3008.png)

## How it's being passed:
![image](https://user-images.githubusercontent.com/11980918/28534548-ea20f1cc-7055-11e7-90c2-674356142d3d.png)

## The error seen in `/var/log/grafana/grafana.log`:
```
2017-07-24T09:42:16-0700 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse https://monitoring.{us-east-1}.amazonaws.com/: invalid character \"{\" in host name"
```

---

If I uncheck `Multi-Value` in the template it works again as expected. I'm guessing the current implementation only supports one region at a time. If this is a "won't fix" then I'm good with the workaround, just wanting to call it out in case someone else comes across this.

**Comment by torkelo** [comment]
Disable the multi value option, if cannot be used in in your scenario
