### ISSUE TITLE
[Feature request] Group by multiple of time interval

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8919]
This is a request to be able to specify a minimum group by time interval, and grafana would use a multiple of that value, scaling depending on the time range.
For example if I specify `15s`, grafana should group by `15s` or `30s` or `45s`, etc.

- What Grafana version are you using?
4.1.1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux

- What did you do?
Have a data source which reports at 15s intervals, used a query which computes a derivative of the value.

- What was the expected result?
See stable values.

- What happened instead?
Very erratic values, constantly spiking up and down.

- Additional information
This is happening because Grafana is choosing to group by a 20s interval. At this interval, the group interval boundaries are not consistent with the measurement intervals, and so the derivative math gets screwed up (sometimes the measurement is 5s into the group, and other times it's 10s into the group). We don't want to just specify a hard-set `15s` as the group interval, as then if you're viewing a span of days, the interval is too small.
The solution is to make sure that the group by interval is a multiple of the measurement interval. `15s`,`30s`,`45s`, ...

**Comment by mattiasholmlund** [comment]
I am having the same problem. I report data to influxdb every 10 seconds (exactly) and the have graphs that summarize over the data points and divide by the time interval to get a rate:

```
field(avg) -> sum() -> math(/($_interval_ms/10000))
```

This works fine as long as the $__interval is a multiple of 10 seconds, but for some window sizes we end up with $__interval 15 seconds and then the graph alternates between one datapoint per interval and two datapoints per interval which makes the graph have a very ugly sawtooth pattern.

For me, it would be preferable to have $__interval ALWAYS be a multiple of the Min time interval. That might be perceived as a breaking change to some, but I think it would be a sane default.

**Comment by mattiasholmlund** [comment]
Time interval 15 seconds:

![screen shot 2017-11-16 at 10 47 15](https://user-images.githubusercontent.com/33054233/32884744-a9512e6c-cabb-11e7-9550-91f8add2e3c4.png)

Resized window slightly to get 20 second time interval:

![screen shot 2017-11-16 at 10 49 34](https://user-images.githubusercontent.com/33054233/32884835-ee410966-cabb-11e7-9fe4-8cbe2f35f9e5.png)

**Comment by stevenh** [comment]
we have this issue as well, in addition time periods which don't align also cause issues, by that I mean imagine you have a value which is being reported from multiple sources, hostname tagged and you graph is displaying the cumulative total.

Then if the start / end periods don't align with those periods you get up tick at the beginning and a downtick at the end.

You can see something like this on the graph above, the small vertical yellow line at beginning of Outgoing streams. This is a relatively minor example it can be very much more pronounced.

For single stat panels which are showing current value this can cause the value to drop to zero on some refreshes, making them not very useful.

**Comment by stevenh** [comment]
Oh forgot to mention, this also causes havoc with graph Y Axis auto ranging, when you get the leading or trailing value drop to zero.

This is most noticeable when you have auto refresh as the graph values jump up and down like a yo-yo.

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
