### ISSUE TITLE
"New" menu showing up for stack viewers under dashboard browser

### ISSUE THREAD

**Issue by d0ugal** [grafana/grafana#89205]
### What happened?

I am a stack viewer and I was looking at the dashboard view `/dashboards`. I noticed that the "New" menu was visible despite only having Viewer permissions.
![Screenshot 2024-06-14 at 10 05 55](https://github.com/grafana/grafana/assets/48211/a2150b4d-a996-4be3-91e2-5f9e091ddd3d)

Somewhat interesting to note that "New folder" doesn't show up.
![Screenshot 2024-06-14 at 10 27 55](https://github.com/grafana/grafana/assets/48211/873afac4-9f57-4ff4-9e58-1aecb8e19571)

It is only when I try to save the dashoard that it fails
![Screenshot 2024-06-14 at 10 28 37](https://github.com/grafana/grafana/assets/48211/d65a1f33-1615-4f9e-a6f1-ad860238cde2)

### What did you expect to happen?

I don't expect to see the New menu

### Did this work before?

I believe so, but I am unsure.

### How do we reproduce it?

1. Be a stack viewer
2. Try to create a dashboard
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

```
                        "version": "11.1.0-71996",
                        "versionString": "Grafana v11.1.0-71996 (82aa000e9d)",
                        "commit": "82aa000e9d7091d0fae0c07f54f134dc25f2adcd",
                        "commitShort": "82aa000e9d",
                        "buildstamp": 1718352494,
```

### Grafana platform?

I use Grafana Cloud

**Comment by tskarhed** [comment]
I tried to reproduce it. My viewer only has dashboards:read permission, which means I can't see it. @ashharrison90 managed to reproduce it for one of his orgs, where his viewer had dashboards:write and dashboards:create permission. The button will show for either create (you can't save) or write.

**Comment by IevaVasiljeva** [comment]
This button will show if the user has access to create a dashboard anywhere (eg, they're an admin of one of the folders). We have two options 1) hide this button altogether 2) show this button, but make it clear that the user can't create a dashboard under the root level.

**1)  hide this button altogether**

I've done something similar for folder creation button here: https://github.com/grafana/identity-access-team/issues/803. This would be simple to do, but would make dashboard creation flow less discoverable for users who are editors/admins of a specific folder (they'd need to navigate to a folder that they can edit/admin to be able to create a dashboard).

**2) show this button, but make it clear that the user can't create a dashboard under the root level**

This is pretty much tracked by https://github.com/grafana/grafana-enterprise/issues/3287 - last I checked, it wasn't trivial to implement a fix.

@tskarhed and @ashharrison90 do you have any preference for approach 1) or 2)? Asking you, as you probably have a better intuition for UI improvements than I do :)

**Comment by IevaVasiljeva** [comment]
I've raised a PR that removes the root level "New" button for users who can't create dashboards on the root level: https://github.com/grafana/grafana/pull/92942 (the approach 1 from above).

Let me know if you have any objections.
