### ISSUE TITLE
API Keys no longer existent in v11 but still in docs

### ISSUE THREAD

**Issue by senpro-ingwersenk** [grafana/grafana#89213]
**What is the chore?**:
Right now, there are still API Key documentation in the Grafana documentation of version 11 although the feature seems to be completely gone.

I was trying to follow this guide: https://docs.opennms.com/horizon/33/operation/deep-dive/database-reports/templates/grafana.html
...and thus came to the conclusion that API Keys must be disabled on my instance. They are not, and there is also no toggle to "enable" them.
I tried to use a service account and that did not work - but that is a separate issue.

**Is there anything else we need to know?**:
No, just wanted to let you know.
As far as I know, API Keys worked a little different than SA tokens, so all I can do is ask OpenNMS to update their plugin, I suppose.

**Comment by Jguer** [comment]
Hi @senpro-ingwersenk 

https://grafana.com/blog/2024/06/12/grafana-update-service-account-tokens-are-replacing-api-keys/ 

API keys are going away in Grafana but until their final removal existing API keys will keep working. 

Feel free to open a new issue if your facing problems configuring Service Accounts
