### ISSUE TITLE
Grafana LDAP integration with Apache Directory Server

### ISSUE THREAD

**Issue by arnold-deak** [grafana/grafana#8921]
Hi, 
I have a problem integrating grafana with Apacheds (Apache Directory Server). I have tried all examples, issue fixes, everything, problem is, there is not much help with Apacheds. Most issues are with either OpenLDAP or Active Directory. I need some help, if someone knows what's the problem. 

My Apacheds has : 2-3 groups named graylog.... (graylogAdmins, graylogUsers, etc) so i used graylog* for group filter. The  groups which are **groupOfNames** objects, contain "**member**" attributes, that's how apacheds knows who's member and who's not member. Attribute member : uid=user@company.com,cn=section1,cn=people,dc=company,dc=com

**Configuration :**

# Search user bind dn
bind_dn = "$Search_User with view permissions"
# Search user bind password
bind_password = '$Password'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(uid=%s)"

# An array of base dns to search through
search_base_dns = ["ou=section1,ou=people,dc=company,dc=com"]

# GROUP SEARCH ( I think here is the issue..)
group_search_filter = "(&(objectClass=groupOfNames)(cn=graylog*))"

group_search_base_dns = ["ou=group,dc=company,dc=com"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
member_of = "distinguishedName"
name = "givenName"
surname = "sn"
username = "uid"
email =  "mail"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=graylogAdmins,ou=group,dc=company,dc=com"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
group_dn = "cn=graylogUsers,ou=group,dc=company,dc=com"
org_role = "Editor"

#[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
#group_dn = "*"
#org_role = "Viewer"

**Logs:**

msg="Searching for user's groups" logger=ldap filter="(&(objectClass=groupOfNames)(cn=graylog*))"

msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=user@company.com groups="[ ]"

msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"

**Comment by torkelo** [comment]
please use community site for questions.
