### ISSUE TITLE
[Feature request] Dynamically extended columns of data table and column header from query

### ISSUE THREAD

**Issue by lotysh** [grafana/grafana#8922]
Grafana version -  4.3.2
datasource   - postqre sql database

It would be useful to be able to use dynamically changed number of column in the  table
Now I have metrics with tags (CPU usage, Memory Usage, Bandwidth Peak etc.) and want to display only this column which are selected in the tag list. 

And also I have trouble to change column header in the table in accordance with selected  tags or template variable. Now in Column style, i can just "Apply to columns" name using hard coding or regex   but it would be great to be able to use the query (sql).

**Comment by torkelo** [comment]
If you configure your query to use format as set to Table, then the table panel will show what your query returns
