### ISSUE TITLE
[Bug] Using __input of "type" : "constant" does not work in queries

### ISSUE THREAD

**Issue by tobilarscheid** [grafana/grafana#8923]
> - What Grafana version are you using?

*4.4.1*

> - What datasource are you using?

*prometheus*

> - What OS are you running grafana on?

*Docker*

> - What did you do?

I created a template with `__inputs` like so:

```json
"__inputs": [
        {
            "name": "SERVICENAME",
            "label": "servicename",
            "type": "constant"
        },
      ]
```

I am then trying to use this input within a graph panel`s metric query:

```json
"targets": [
                        {
                            "expr": "2xx_responses_total{app=\"${SERVICENAME}\"}",
                            "legendFormat": "2xx responses"
                        },
```

I also tried `[[SERVICENAME]]` or `$SERVICENAME`

> - What was the expected result?

I expect the placeholder to be replaced by the value I supply during import of the json template.

> - What happened instead?

The placeholder is not replaced.

## Why am I even doing this?

I know that as a workaround I can insert my input values into a constant template variable and then reference these from the query. This is problematic for at least two reasons:

1. (_minor_) These values are not actually exchangeable in the template
2. (**major**) I can not define templated alerts which are created by importing the template.

**Comment by torkelo** [comment]
the constant template referred to in the "__inputs" section of an exported dashboard is for metric prefixes / hidden variables, so you can export the dashboard and someone else can import it and specify their own prefix. For example statsd prefix. 

Are you trying to build a dashboard that others can import? The '"__inputs" section is only looked at when you use the import API, is that what your doing?

**Comment by tobilarscheid** [comment]
Hi @torkelo,

I am in fact trying to build a template others can import - and yes, I am using the import API - when trying to import the dashboard I am queried for the defined inputs like so:

![image](https://user-images.githubusercontent.com/5900890/28609367-ad0c1fc4-71e4-11e7-9597-d394b1497849.png)

Note that I am aware that there is a difference between the `__inputs` section and the `templating` section - what ever get's defined in the templating section can be resued in queries. Stuff defined in the `__input` section can not be referenced from within queries - that is the bug I am reporting.

**Comment by torkelo** [comment]
template variable constants works fine in import. you use the variable with the $name or [[name]] syntax. That syntax is the normal template variable syntax that is replaced at runtime by Grafana. 

The templating that is done during import is using ${varname} syntax and allows you to set the value of the constant during import: 

![image](https://user-images.githubusercontent.com/10999/29820974-982940e4-8cc6-11e7-9629-a61f0962cba2.png)

**Comment by tobilarscheid** [comment]
I understand that I can replace a constant defined in `__inputs` with name `VAR_PREFIX` as `${VAR_PREFIX}` in the templating section during import - and then during runtime reference it like `$prefix` or `[[prefix]]` (to stay precisely with the example from your screenshot).

The point I am trying to make is that this replacement of stuff defined in `__inputs` **only** works in the templating section - I would however like to replace `${VAR_PREFIX}` **globally** in my whole template, most importantly in queries used in `targets` - for the reasons described in my initial post.

**Comment by tobilarscheid** [comment]
@torkelo would you mind reopening?

**Comment by italux** [comment]
I'm having the same issue so I've opened #29802

**Comment by DifferentialOrange** [comment]
It's also worth noting that InfluxDB tagged queries support dashboard input variables in queries. I use them in my dashboard template https://grafana.com/grafana/dashboards/12567 :
```
"targets": [
  {
     "alias": "$tag_label_pairs_alias",
     "groupBy": [ ... ],
     "measurement": "${INFLUXDB_MEASUREMENT}",
     "policy": "${INFLUXDB_POLICY}",
     "refId": "A",
     "resultFormat": "time_series",
     "select": [...],
     "tags": [...]
  },
  ...
```
