### ISSUE TITLE
[Feat Req]: Templating custom values for Table Panel Raw Document Size

### ISSUE THREAD

**Issue by storagedevops** [grafana/grafana#8924]
- What Grafana version are you using? 4.4.1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? Linux
- What did you do? Build Elasticsearch Table panel

I love the option to set the return size on the table panel but it would be nice if I could template the return size.  Currently it only accepts a number.

![image](https://user-images.githubusercontent.com/20799351/28578802-c50c03b2-7128-11e7-9fa3-355867105f35.png)

**Comment by aocenas** [comment]
Probably makes sense to have templating allowed in all the inputs in query editor in general.

**Comment by aocenas** [comment]
This should be already be implemented, not sure thought exactly when (probably Grafana 8) as we did rewrite quite a bit of the elastic search plugin since 2017.
