### ISSUE TITLE
[Bug] Adding Image when sending alerts to OpsGenie

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#8925]
- What Grafana version are you using?
4.4.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Amazon Linux AMI
- What did you do?
I've created an alerting channel in Grafana which sends alerts to OpsGenie.
I wanted to know how to configure to send the alert image to OpsGenie as well - Currently the alert is received without the image.

**Comment by torkelo** [comment]
have you configured an external image store?

http://docs.grafana.org/alerting/notifications/#external-image-store
