### ISSUE TITLE
[Bug] CloudWatch datasource unable to get some data from AWS.

### ISSUE THREAD

**Issue by makhnmik** [grafana/grafana#8926]
Hi, 

Please include this information:
- What Grafana version are you using?
grafana/grafana:4.4.1 docker image
- What datasource are you using?
CloudWatch
- What OS are you running grafana on?
Ubuntu Linux
- What did you do?
Trying to call ec2_instance_attribute(us-east-1, InstanceId, { "tag:env": [ "prod" ] }) 
- What was the expected result?
List of instance ID's
- What happened instead?
EROR[07-25|17:50:58] Unable to call AWS API                   logger=context userId=1 orgId=1 uname=admin error="UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403,

I'm using AWS instance with IAM role attached to It. Role has Full read permissions to EC2 and CloudWatch. I can call aws ec2 describe-instances from console as well as get some metrics from cloudwatch  in grafana, i.e. dimension_values(eu-west-1,AWS/EC2,CPUUtilization,InstanceId) works fine.

**Comment by torkelo** [comment]
can you try latest nightly build? 
https://grafana.com/grafana/download/5.0.0-8432pre1

might be fixed by 
https://github.com/grafana/grafana/pull/8766
