### ISSUE TITLE
where is the server.coreService.Initialize in the main branch

### ISSUE THREAD

**Issue by bbz525** [grafana/grafana#89271]
### What happened?

read the source code ,i can't find method   server.coreService.Initialize in the main branch ?where to find 

### What did you expect to happen?

when i  read source code

### Did this work before?

maybe work

### How do we reproduce it?

1. only read the souce code 
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
Hi @bbz525 
Thanks for reaching out. GitHub is mainly used for tracking bugs and feature requests. Your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) You are also welcome to ask in our [Community Slack](https://slack.grafana.com/)
We appreciate your understanding.
