### ISSUE TITLE
"make build-docker-full" does not work (v10.4.4)

### ISSUE THREAD

**Issue by azilly-de** [grafana/grafana#89289]
### What happened?

"make build-docker-full" exists with error at yarn install due to error when trying to build 'equatable'

```
<snip>
126.3 ➤ YN0009: │ @esfx/equatable@npm:1.0.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-f0bd6cd6/build.log)
127.0 ➤ YN0007: │ nx@npm:16.10.0 [aedfc] must be built because it never has been before or the last one failed
127.4 ➤ YN0000: └ Completed in 1m 21s
127.9 ➤ YN0000: · Failed with errors in 2m 7s
------
Dockerfile:25
--------------------
  23 |     RUN apk add --no-cache make build-base python3
  24 |     
  25 | >>> RUN yarn install --immutable
  26 |     
  27 |     COPY tsconfig.json .eslintrc .editorconfig .browserslistrc .prettierrc.js ./
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --immutable" did not complete successfully: exit code: 1
```

### What did you expect to happen?

Command runs successfully and image is created.

### Did this work before?

At least three weeks ago  I built v10.4.3 with "make build-docker-full" successfully - now 10.4.3 tag also shows above error due to yarn dependency.

### How do we reproduce it?

1. checkout grafana and change to tag v10.4.4
2. run command 'make build-docker-full'
3. error occurs

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.4.4
OS:  Docker  26.1.4 on Ubuntu 22.04.4 LTS linux/amd64
Browser: n/a

### Grafana platform?

Docker

**Comment by azilly-de** [comment]
After some investigation this seems to be related to the fact that 'node:20-alpine' in Dockerfile points to the image with tag  'node:20.14-alpine3.20'.  When changing JS_IMAGE explicitly to use 'node:20.14-alpine3.19' this error does not occur.

**Comment by azilly-de** [comment]
Current 'node:20-alpine' referenced in Dockerfile is working again. Latest image with mentioned tag was pushed  Jun 26, 2024.

**Comment by karankumark1998** [comment]
i'm using mac os but failing to build docker image

**Comment by azilly-de** [comment]
@karankumark1998 

This ticket was closed with merged [PR 89714 ](https://github.com/grafana/grafana/pull/89714)

Commenting a closed ticket may not be that helpful. If you have trouble building a docker image perhaps its much mor ehelpful to create a new ticket...
