### ISSUE TITLE
Incorrect escaping for space in template variable tags - Elasticsearch

### ISSUE THREAD

**Issue by snc29590** [grafana/grafana#8930]
Please include this information:
- What Grafana version are you using?
 Grafana v4.3.2 (commit: ed4d170) 

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
Uvuntu 14.04

- What did you do? What was the expected result? What happened instead?
I am trying to use tagging feature (experimental) while using Templating. I am using a elasticsearch datasource. Below are my template variables ($continent and $city)

![image](https://user-images.githubusercontent.com/16399189/28587559-3a4ca584-7195-11e7-8e29-33a738cd7269.png)

Here, I am trying to use the tagging feature for "$city" variable where the tags are country names. 

*"$city" variable configuration*
![image](https://user-images.githubusercontent.com/16399189/28590097-7d431810-719e-11e7-8d33-26a1aa40362c.png)

The tag gets listed correctly, but selecting the tag does not select the correct variables if the tag has a "space" character.

*Image 1*: Template variables with tag selection - without space in tag:
![image](https://user-images.githubusercontent.com/16399189/28587758-e52a3a48-7195-11e7-899b-6d9e8d1bcc69.png)

I have selected France and Germany, and the correct "$city" variables are selected.

Corresponding tag query request payload:

    {"search_type":"count","ignore_unavailable":true,"index":["geo-metrics-2017-07-25"]}
    {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":
    {"gte":"1500989512521","lte":"1501011112521","format":"epoch_millis"}}},{"query_string":
    {"analyze_wildcard":true,"query":"continent_name:(\"Asia\" OR \"Europe\" OR \"North\\ America\") 
    AND country_name:France"}}]}},"aggs":{"1":{"terms":{"field":"city_name","size":500,"order":
    {"_term":"asc"}}}}}

*Image 2*: Template variables with tag selection - with space character in tag:
![image](https://user-images.githubusercontent.com/16399189/28587800-0848fece-7196-11e7-9950-fc3c96b29bd3.png)

Notice I have selected "United Kingdom" but "London" does not get selected because of the space in the tag (United Kingdom)

Corresponding tag query request payload:
    {"search_type":"count","ignore_unavailable":true,"index":["geo-metrics-2017-07-25"]}
    {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":
    {"gte":"1500989607159","lte":"1501011207159","format":"epoch_millis"}}},{"query_string":
    {"analyze_wildcard":true,"query":"continent_name:(\"Asia\" OR \"Europe\" OR \"North\\ America\") 
    AND country_name:United Kingdom"}}]}},"aggs":{"1":{"terms":
    {"field":"city_name","size":500,"order":{"_term":"asc"}}}}}

Notice that **"country_name: United Kingdom"** is not escaped in the tag query. Hence, the query does not return any results, and subsequently the correct cities does not get selected. 

I believe the solution is to escape the "$tag" variable correctly depending on the datasource.

**Comment by snc29590** [comment]
Update:
I figured out a work-around for this. Specifying the "Tag Values Query" as follows solves the issue:

    {"find" : "terms","field": "city_name","query":"continent_name:$continent AND country_name:\"$tag\""}

Notice that I have added the quotes around "$tag" explicitly.

I guess this is still a bug and needs to be fixed. The above thing can be used as a temp work-around until the fix is out.

**Comment by torkelo** [comment]
you need to enclose it in tags if your values contain spaces and you want to match the whole expression.-

**Comment by dagwieers** [comment]
This is still an issue you cannot get right the way it is design in Elasticsearch 7.10.0 using Grafana 

Imagine that you have a list of values of which include spaces. Let's call this `$purpose`
- Customer Production
- Customer Non-Production
- Prospect
- Trial

And imagine we have this query that needs to work:
```lucene
event.dataset:catchpoint.testdata AND monitor.status:down AND fields.instancepurpose:<purpose value>
```

1. If you use quotes in the query, the query will look like this for any given `"$purpose"`
```lucene
event.dataset:catchpoint.testdata AND monitor.status:down AND fields.instancepurpose:"Customer Production"
```

However, if you select the *All* option, you will get a non-working query:
```lucene
event.dataset:catchpoint.testdata AND monitor.status:down AND fields.instancepurpose:"(\"Customer Production\" OR \"Prospect\" OR \"Trial\")"
```

2. If you do not use quotes, the *All* option works fine, but a query for a selection does not work:
```lucene
event.dataset:catchpoint.testdata AND monitor.status:down AND fields.instancepurpose:Customer Production
```
This contains systems that are also _Customer Non-Production_.

3. Even if we try to set the All value explicitly to an asterisk `*`, this gets quoted and we end up with:
```lucene
event.dataset:catchpoint.testdata AND monitor.status:down AND fields.instancepurpose:"*"
```

So there is no workaround if you want to have it working with both individual selections and *All*.
