### ISSUE TITLE
400 invalid object specification: type should not be an empty string

### ISSUE THREAD

**Issue by waski94** [grafana/grafana#89312]
### What happened?

I'm trying do add contact point using POST via API: /api/v1/provisioning/contact-points
Body:
i would like to have that:
```json
{
    "apiVersion": 1,
    "contactPoints": [
        {
            "name": "alertmanager",
            "receivers": [
                {
                    "type": "prometheus-alertmanager",
                    "settings": {
                        "url": "<some_url>"
                    },
                    "disableResolveMessage": false
                }
            ]
        }
    ]
}
```

also tried that a lot of another json...
eg:
```json
{
    "apiVersion": 1,
    "contactPoints": [
        {
            "orgId": 24,
            "name": "alertmanager",
            "receivers": [
                {
                    "uid": "<some_uid>",
                    "type": "prometheus-alertmanager",
                    "settings": {
                        "basicAuthPassword": <some_pass>",
                        "url": "<some_url>"
                    },
                    "disableResolveMessage": false
                }
            ]
        },
        {
            "orgId": 24,
            "name": "email receiver",
            "receivers": [
                {
                    "uid":" <some_uid>",
                    "type": "email",
                    "settings": {
                        "addresses": "<some@email.com>"
                    },
                    "disableResolveMessage": false
                }
            ]
        }
    ]
}
```

And every time i got:
400 invalid object specification: type should not be an empty string

DOC:
https://grafana.com/docs/grafana/v10.3/developers/http_api/alerting_provisioning/#contact-points

### What did you expect to happen?

i expect that contact point will be added.

### Did this work before?

No

### How do we reproduce it?

1.POST on grafana API. Body is exported from grafana GUI contactact points
2.
3.

### Environment (with versions)?

Grafana: 10.3
OS: Ubuntu 22.04.3
Browser: chomium

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
Hello @waski94 

Thanks for reporting this issue

I can reproduce it.

The field 'type' is not empty, but the API endpoint returns 


```
{
    "message": "invalid object specification: type should not be an empty string",
    "traceID": ""
}
```

body sent to `api/v1/provisioning/contact-points`

``` json
{
    "apiVersion": 1,
    "contactPoints": [
        {
            "orgId": 1,
            "name": "slack-critical-2",
            "receivers": [
                {
                    "uid": "",
                    "type": "slack",
                    "settings": {
                        "url": "https://hooks.slack.com/services/TxxE/Bxxx/gxxx"
                    },
                    "disableResolveMessage": false
                }
            ]
        }
    ]
}
```

**Comment by yuri-tceretian** [comment]
This is not correct format of the request for the API ` /api/v1/provisioning/contact-points`. I think you got it from export page, which provides data in _file_ provisioning format, which is different from API provisioning.

Please refer to the documentation that declares that API accepts [EmbeddedContactPoint](https://grafana.com/docs/grafana/v10.3/developers/http_api/alerting_provisioning/#span-idembedded-contact-pointspan-embeddedcontactpoint).
To get all your contact points in that format, you can use GET API

The correct format in your example would be 
```json
{
  "name": "alertmanager",
  "type": "prometheus-alertmanager",
  "settings": {
    "url": "<some_url>"
  },
  "disableResolveMessage": false
}
```
Provisioning API operates on the integration level, which is grouped by name into receivers. This is a bit confusing, and we're working on changing that in the future.
