### ISSUE TITLE
Heatmap Panel: "Calculate from data" X Bucket Count 

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#89319]
### What happened?

The X axis bucket count looks at the max and min timestamps returned within the query. If your data set is only for a subset of the full time range, the buckets will be much smaller than expected.

Example when we only see data on a small time range. Buckets are narrow:
![image](https://github.com/grafana/grafana/assets/99200643/fbe1101a-8dfd-4e4c-862f-f63820c5f7ea)

Example when we see data across the entire time range. Buckets are wide:
![image](https://github.com/grafana/grafana/assets/99200643/a374a8f0-30dc-411a-8e5a-3549881dc0b6)

### What did you expect to happen?

I expect that if I select Count=10 in the X axis, then it will divide the timespan from the time picker into 10 buckets, NOT the returned time range.

### Did this work before?

Unknown. Likely not

### How do we reproduce it?

1. Make a heatmap and "Calculate from data". Set "X Bucket" = "Count" and set to a number
2. Look at heatmap over various time ranges where data covers the entire time range, and then again when it only covers part of the time range.
3.
[debug-Memory _ CPU-2024-06-17 21_42_10.json.txt](https://github.com/user-attachments/files/15877603/debug-Memory._.CPU-2024-06-17.21_42_10.json.txt)

### Is the bug inside a dashboard panel?

Heatmap

### Environment (with versions)?

Grafana: v11.1.0-71799 (https://github.com/grafana/grafana/commit/3a8b59f5e8eafb8a63de6af38d182653065b4446)
OS: MacOS
Browser: Chromeos

### Grafana platform?

I use Grafana Cloud

**Comment by justinsmalley** [comment]
workaround _would be_ to set fill=null in the query so that we have data over the entire time range, however then we encounter https://github.com/grafana/grafana/issues/89318

**Comment by leeoniya** [comment]
hmm, yeah that would make sense.

one problem is that `calculateHeatmapFromData()` is a Transformation [1] which currently has no knowledge of the dashboard time range. i think pretty much all of our Transformations are currently unaware dashboard timeRange -- they only use what is passed to them as parameters from their config, plus only what's needed to interpolate template variables:

https://github.com/grafana/grafana/blob/3bbc821131f1b10ace139dbb4a6880fb77686646/packages/grafana-data/src/types/transformations.ts#L13-L18

we could extend this context with dashboard's `from` and `to`, and/or possibly add this as an internal option, like we do for our internal-only transformation for inserting "disconnect" gaps:

https://github.com/grafana/grafana/blob/3bbc821131f1b10ace139dbb4a6880fb77686646/packages/grafana-ui/src/graveyard/GraphNG/nullInsertThreshold.test.ts#L114-L115

and then use this inside of Heatmap panel, but then we would have a difference in behavior between the heatmap Transformation [1] and the Heatmap panel.

from a transformation perspective, i think it makes sense to divide the data range into the specified buckets, at least by default. for the panel, the opposite is probably true. so the question becomes whether we're okay having inverted defaults. maybe :thinking:?

[1] https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#create-heatmap

**Comment by leeoniya** [comment]
heh: https://github.com/grafana/grafana/blob/7c69f3657b5db4f6168af3d2b6e6796b7bb568d7/public/app/features/transformers/calculateHeatmap/heatmap.ts#L503

**Comment by justinsmalley** [comment]
Thanks for the quick turnaround!
