### ISSUE TITLE
I have a question in _mixins.scss

### ISSUE THREAD

**Issue by bigdaizi** [grafana/grafana#8932]
l have a question in mixins.scss line 15
@mixin tab-focus() {
  // Default
  outline: thin dotted;
  // WebKit
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

Will the outline display 5px auto in all browser ？
thanks for answer...

**Comment by torkelo** [comment]
Please use community site for questions. 

Is there a reason for your question? Seeing something strange on a particular browser?

**Comment by bigdaizi** [comment]
sorry . I write error code and make a wrong issue
