### ISSUE TITLE
Public Dashboard feature in Grafana encounters "Invalid panel id"

### ISSUE THREAD

**Issue by Nowalski** [grafana/grafana#89323]
### What happened?

Upon enabling **Public** Dashboard access in Grafana, I encountered an "**Invalid panel id**" error consistently when attempting to access the dashboard publicly. The specific error message in the browser console indicates a failed POST request to `/api/public/dashboards/{dashboard_id}/panels/undefined/query,` resulting in a 400 (Bad Request) response

### What did you expect to happen?

I expected the dashboard to render correctly and display data when accessed via its public URL.

### Did this work before?

N/A

### How do we reproduce it?

1. Enable Public Dashboard access for any dashboard in Grafana.
2. Access the dashboard via its public URL.
3. Check the browser console for error messages showing "Invalid panel id".

### Is the bug inside a dashboard panel?

No it's on the Whole Core,

### Environment (with versions)?

Self-hosted Grafana
OS: Ubuntu 22.04.4 LTS
Browser: Chromium,

### Grafana platform?

Docker

**Comment by Nowalski** [comment]
Same on the Cloud Version: Invalid panel id
Trace ID: 4e5f17f7c39cf5fcdad598c121804c1e but here i get a Trace ID

**Comment by andrei-near** [comment]
Try removing your dashboard variables. Public dashboards don't seem to work when variables are used

**Comment by tonypowa** [comment]
Hi @Nowalski 

What is your Grafana version? 

Also, could you share a sample dashboard. You'd copy the JSON of the dashboard and share it here.

Thank you

**Comment by Nowalski** [comment]
[](https://pastebin.com/1PADLZnJ)

For some Reason i can't Upload the JSON file here, 

So i tried the Dashboard on the Cloud Version and on My Self Hosted one, Grafana v11.0.0 (277ef258d4)
Linux,

**Comment by Nowalski** [comment]
> Try removing your dashboard variables. Public dashboards don't seem to work when variables are used

Yea i tried that and to make the Variable Default, sadly that don't work either, it all works fine but when u make it public it don't work.. there must be an easy fix for this, it's just useless like this sadly for me

**Comment by tonypowa** [comment]
@Nowalski 

>Yea i tried that and to make the Variable Default

What do you mean? 

I have imported your dashboard and seen that there are various variables in place. This would explain why your dashboard does not work.  Variables aren't supported in Public dashboards.

![image](https://github.com/user-attachments/assets/f0fa628b-76bf-4afa-8547-1037f919ec94)

**Comment by Nowalski** [comment]
I tried removing them, and made static variables same thing, i opened the connection ports and everything else but it does not give me specific errors, so only thing i can do is remove all variables,

**Comment by tonypowa** [comment]
Yes, removing the variables is the right move @Nowalski 

Let us know if the issue can be closed or if you have further questions

Thank you

**Comment by tonypowa** [comment]
I’ll be closing this issue, but please feel free to request a reopening if you have any additional questions or concerns
