### ISSUE TITLE
[Feature request] Allow dashboards to become editable without saving

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#8935]
We typically make dashboards with many template variables uneditable as it's so easy to save a different time range or template variable default value. In order to lookup a configuration of a panel (without using the pretty hard to read/copy JSON representation), it's currently required to save the dashboard twice for that: make editable + save, view configuraiton, make uneditable + save.

What Grafana version are you using? v4.4.1

**Comment by torkelo** [comment]
think we will solve your case differently. We plane to make time range changes & template variables value changes NOT save by default. In the save dialog (new in 4.4) where you can specify an optional save message, there will be two checkboxes for "save current time range" , "save current template variable values".

https://github.com/grafana/grafana/issues/8805

**Comment by grobie** [comment]
Oh lovely, that's what I wanted to report next! Will comment on the other
issue with some thoughts.
