### ISSUE TITLE
AWS Cloudwatch Alarms

### ISSUE THREAD

**Issue by petegallagher** [grafana/grafana#8936]
It would be useful to be able to display the current count of Cloudwatch Alarms in a particular state (e.g. `OK | ALARM | INSUFFICIENT_DATA`) as a SingleStat panel. I notice the [ability to call this API already exists](https://github.com/grafana/grafana/blob/v4.4.1/pkg/api/cloudwatch/cloudwatch.go#L317) but this does not appear to be used anywhere.

Is it possible to expose this as a metric that can be used?

**Comment by mtanda** [comment]
It is possible without add feature.
There are two way you can take.

1. Use API Gateway and Lambda, return the count.
This is a example which use API Gateway with Grafana.
https://www.linkedin.com/pulse/using-aws-lambda-api-gateway-server-less-grafana-adapters-jonas-birm%C3%A9

2. Create Lambda function which output the count as Custom Metrics.

**Comment by ad-it** [comment]
Thanks @mtanda .
This [link](https://medium.com/@anatoliydadashev/aws-cloudwatch-alarms-count-in-grafana-53932f5bc901) may be useful to get needed.
