### ISSUE TITLE
/api/frontend-metrics should not throw a toast when the API fails

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#89378]
We currently send some web vitals information to to `/api/frontend-metrics` when Grafana boots up. Recently uBlock has started blocking this call, and an annoying error toast is shown on the screen.

![image](https://github.com/grafana/grafana/assets/46142/2ba4aa7e-8232-49cb-8fb3-7dc01b239f1d)

While it's not really up to us to make sure things work when users install extensions that interfere with the website, this call is non-critical and should never throw a toast when it fails. We should just suppress this one.

**Comment by EvilJordan** [comment]
This is still happening in Grafana v11.1.0 (5b85c4c2fc)

**Comment by hoshinolina** [comment]
~~Still happening with 12.0.0. Perhaps reopen?~~

Nevermind, I was confused. This was indeed fixed.
