### ISSUE TITLE
[Bug] "Cannot read property '<field>.<aggregation>' of null" after important previously working dashboard

### ISSUE THREAD

**Issue by jhedev** [grafana/grafana#8938]
**What Grafana version are you using?**
I tested this with the following versions (docker tags):

* `master`
* 4.4.1
* 4.4.0
* 4.3.0

**What datasource are you using?**

InfluxDB

**What OS are you running grafana on?**

Linux (via Docker; official grafana image)

**What did you do?**

1. Put together a dashboard a working dashboard
2. Exported the Dashboard using the "View JSON" menu point
3. Changed the 
4. Tried two things:
    a. Deleted the dashboard and imported via UI button
    b. Restarted grafana and imported via curl
5. After reimporting dashboard doesn't work anymore (see error posted below) 

I tried various variations of the dashboard:

* different fields in the query
* different aggregations
* with and without templating options (the template query works just fine for the same datasource)

In addition, I can't get the dashboard working again by just editing the panels. If I recreate the panel with the exact same query it works fine.

**What was the expected result?**

Dashboard working in the same way it did when I created it manually via the UI

**What happened instead?**

Got the following error after I imported a previously working dashboard:

*Message*:
```
Cannot read property 'energy_inverter.count' of null
```
*Stacktrace*:
```
TypeError: Cannot read property 'energy_inverter.count' of null
    at a.timeSeriesHandler (https://oculus.gridx.de/public/app/boot.8f0650f6.js:19:12729)
    at https://oculus.gridx.de/public/app/boot.8f0650f6.js:19:11723
    at Array.map (native)
    at a.getSeriesList (https://oculus.gridx.de/public/app/boot.8f0650f6.js:19:11696)
    at b.onDataReceived (https://oculus.gridx.de/public/app/boot.8f0650f6.js:19:19175)
    at f.emit (https://oculus.gridx.de/public/app/boot.8f0650f6.js:60:26533)
    at a.emit (https://oculus.gridx.de/public/app/boot.8f0650f6.js:60:28851)
    at b.handleQueryResult (https://oculus.gridx.de/public/app/boot.8f0650f6.js:54:28561)
    at i (https://oculus.gridx.de/public/app/boot.8f0650f6.js:51:232)
    at https://oculus.gridx.de/public/app/boot.8f0650f6.js:51:654
```

**If related to metric query / data viz**:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

I checked both the requests sent as well as the response I get via the Dev Tools and they are totally fine. See screenshots below:

![screenshot 2017-07-26 16 56 57](https://user-images.githubusercontent.com/4572986/28627926-754788a0-7223-11e7-873a-c4765e693116.png)
![screenshot 2017-07-26 16 56 33](https://user-images.githubusercontent.com/4572986/28627927-754d04ce-7223-11e7-9ec0-1e07651cce5a.png)

**Comment by torkelo** [comment]
Please include the dashboard json

**Comment by jhedev** [comment]
You can find the dashboard json here: https://gist.github.com/jhedev/d968de6cacf31734fdf48ad4de695df5

**Comment by jhedev** [comment]
I now see the same behaviour with cloudwatch as datasource.

To clarify: 

I saved the dashboard json by clicking `View JSON` and storing the content in a file. Did two modifications to the file:

1. Add a key the dashboard key, i.e. `{ "dashboard": <actual_saved_dashboard> }`
2. Set dashboard `"id"` to `null`

Afterwards I try to import it via:

```
curl -H "Content-Type: application/json" --data '@./dashboards/monitoring.json' $GRAFANA_URL'/api/dashboards/db'
```

This works fine for some dashboards while it fails for some other dashboards. So far I couldn't figure what is different.

**Comment by jhedev** [comment]
If I use the export/import functionality it works fine, btw.

**Comment by jhedev** [comment]
Did also try to export via API, i.e.:

```
curl $GRAFANA_URL'/api/dashboards/db/monitoring' > monitoring.json
```

and import again via API:

```
curl -H "Content-Type: application/json" --data '@./dashboards/aws_elb.json' $GRAFANA_URL'/api/dashboards/db'
```

which leds to the same problem.

**Comment by jhedev** [comment]
I think I found the problem: The dashboards that don't work were pretty printed in a way that changed the order of the JSON keys. If I don't do that or just pretty print while leaving the order of the keys it works fine. 

I verified this with previously working dashboards as well as the other way around. Very weird bug ...

**Comment by torkelo** [comment]
Can you do a diff to identify the act difference?

**Comment by jhedev** [comment]
I did a semantic diff and there is no actual difference semantically. The only difference is the order of the keys.

I try to put together an example to reproduce if I have some time.

**Comment by torkelo** [comment]
Closing this as it looks like an old issue that is not impacting users anymore
