### ISSUE TITLE
Multiple Template Variables not working for CloudWatch datasource

### ISSUE THREAD

**Issue by qdoan** [grafana/grafana#8939]
Hello,

The current Cloudwatch does not handle receiving multiple template variables gracefully.

If I have multiple templating variables, and the cloudwatch query takes in multiple variables as values in the dimensions field, then it will have some discrepancies.

Example:
```
"dimensions": {
     "val1": "$val1",
     "val2": "$val2",
     "val3": "val3"
}
```
If I swapped the order of the dimensions, then it starts to work properly.

Addtionally, when I have multiple multi-value templating variables, then it will not work at all.

I have identified this block in [plugins/datasource/cloudwatch/datasource.js](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.js#L414)

It looks like it is only doing multi-value cloudwatch queries based on the first encounter templated variable in the dimension. Which could explain why swapping the order of dimensions made my queries work.

More Info:
- Grafana: 4.3.2
- Datasource: CloudWatch
- OS: MacOS X

Related Issue:
- [268](https://community.grafana.com/t/failing-to-display-aws-cloudwatch-dimensions-while-using-template/268)

Any Ideas regarding this?

**Comment by torkelo** [comment]
Cloudwatch and multi-value variables is not recommended, the Cloudwatch  api does not support way the templating system was intended to be used (string interpolation). 

Think there is an issue for this,

**Comment by joedj** [comment]
This still appears to be an issue, on Grafana v6.2.1 (9e40b07).

My graph has two dimensions, both variable - `ClusterName=$Cluster` and `ServiceName=$Service`.

Changing the order of the dimensions doesn't work for me.

Has anyone found a workaround?  Does Grafana intend to address this?

**Comment by max-lobur** [comment]
Having same issue with AWS/Kafka metrics on Grafana v5.4.2 (d812109)
