### ISSUE TITLE
Dashboards: new dashboards using browser time by default instead of 

### ISSUE THREAD

**Issue by carzil** [grafana/grafana#89398]
### What happened?

When I create new dashboard, it sets Browser time as Timezone in Dashboard settings.

### What did you expect to happen?

Dashboard will use default time zone for user.

This one:
<img width="642" alt="Screenshot 2024-06-19 at 14 25 38" src="https://github.com/grafana/grafana/assets/300045/f8fc9638-6f1a-47f6-aaf8-74d2d2815c31">

### Did this work before?

I don't know

### How do we reproduce it?

1. Click "New dashboard"
2. Open settings of the dashboard 
3. Time zone is Browser time

<img width="633" alt="Screenshot 2024-06-19 at 14 23 36" src="https://github.com/grafana/grafana/assets/300045/54d109ec-6b78-43e7-abc9-704ae96a9e9e">

### Environment (with versions)?

Grafana: v10.4.2 (701c851be7)
OS: macOS Ventura 13.0
Browser: Arc Version 1.43.0 (50018), Chromium Engine Version 125.0.6422.60

### Grafana platform?

Kubernetes

**Comment by Clarity-89** [comment]
Fixed in https://github.com/grafana/grafana/pull/89833.
