### ISSUE TITLE
org_mapping error message: Skipping org mapping due to invalid format

### ISSUE THREAD

**Issue by pbwur** [grafana/grafana#89399]
Recently Grafana has a new feature that makes it possible to map roles to organizations in the oauth configuration. Two properties can be used: org_attribute_path and org_mapping. This feature was very welcome and seems to work well. Except in the situation where the role names contain multiple colons.
In that case I get the message: "Skipping org mapping due to invalid format."

In the code I see that a split is made on the contents of the property org_mapping and the ':' character. That will probably be the cause.

Is there any way I could resolve this? I have checked whether it is possible to use a JMESPath query for 'org_attribute_path' that replaces all ':' with a '_', but I have not yet succeeded. Another option could be to make the split character configurable.

Is there any way I could fix this now?

**Comment by mgyongyosi** [comment]
@pbwur We added support for escaping the `:` character, so if you have a colon in the name of the external attribute then you should add a `\` before the colon and the parser doesn't treat it as a separator.

Would you be able to test it by using one of the [Nightly builds](https://grafana.com/grafana/download/11.2.0-72901)?
