### ISSUE TITLE
[Bug]Text Panel link is wrong in Grafana Docs

### ISSUE THREAD

**Issue by kavyakul** [grafana/grafana#8940]
When I click on Grafana docs @ http://docs.grafana.org/reference/text/ and then click "Text Panel" it takes me to the same page again i.e. http://docs.grafana.org/reference/text/

**Comment by daniellee** [comment]
The problem is that the Text Panel page is empty. Needsd to be added. Thanks for bringing our attention to this.

**Comment by marefr** [comment]
Seems to be fixed
