### ISSUE TITLE
Tabs: Screen reader only announces 1 of 1

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#89402]
**Steps to reproduce**:

Go to dashboard settings. Use a screen read with the tabs. 

probably related to https://github.com/grafana/grafana/issues/89403

**Actual Result**:

It announces `1 of 1` instead of the actual number in the list. This issue also appears in other places.

**Expected Result**
For it to say 2 of 5 or something of the sort.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by L-M-K-B** [comment]
This issue will be handled in the following issue summarising all a11y related issues: https://github.com/grafana/grafana/issues/92004
