### ISSUE TITLE
[Feature request] Use a field as weight/frequency in heatmap

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8941]
Basically right now heatmap uses the count of records that fall within a bucket as the weight of that bucket (to control the color scale of the points on the graph). The request is to instead sum up the value of another field and use that as the bucket weight. For example:

==============================
‣ 
‣ key 
‣ weight 
------------------------------
 row1 
 1 
 3 
------------------------------
 row2 
 2 
 1 
------------------------------
 row3 
 3 
 6 
------------------------------
 row4 
 5 
 3 
==============================

With a bucket size of 2 (keys 1-2, 3-4, 5-6), the resulting heat map column would be:

==============================
‣ bucket 
‣ weight 
------------------------------
 1-2 
 4 
------------------------------
 3-4 
 6 
------------------------------
 5-6 
 3 
==============================

The use case is pretty much exactly what is described above. I'm using InfluxDB, and I have data which is broken into multiple series. I have one field which is used as my "key", and another field which is used as the "weight". Both are fields, not tags, so they are numbers and can be used in arithmetic.

This might be a bit of an esoteric use case, but I wanted to propose it anyway and see what the feelings on it were.

**Comment by JamesGalt** [comment]
It is exactly what I need, would be great to have this feature.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
