### ISSUE TITLE
Cannot disable frontend-metrics, shows error in UI

### ISSUE THREAD

**Issue by drewmmiranda** [grafana/grafana#89437]
### What happened?

It appears a recent ublock origin update has added `/frontend-metrics^` to its block list which i've tracked down to the `easyprivacy` list. I understand this is in no way related to grafana, however, i cannot find any documentation nor information about what `/api/frontend-metrics` is, what its used for, why it exists and why i should allow it.

Grafana is showing an error pop up on every page despite grafana working perfectly without any issues. This error is misleading and ideally i would like to disable it.

![image](https://github.com/grafana/grafana/assets/12700525/f5a1475e-c3ca-41fd-9fea-214828664885)

### What did you expect to happen?

For grafana to not display errors when there is nothing wrong with grafana's functionality

### Did this work before?

N/A

### How do we reproduce it?

1. Use a chromium browser (e.g. Google Chrome, Edge) or firefox
2. Install uBlock origin
3. Navigate to any page and observe that grafana places a fetch to `/api/frontend-metrics` and displays the error (which is the problem) in the UI

![image](https://github.com/grafana/grafana/assets/12700525/f5a1475e-c3ca-41fd-9fea-214828664885)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.0.0 (83b9528bce) (docker image)
OS: Ubuntu Server 22.04 LTS (aarch64 for rpi)
Browser: Google Chrome, Microsoft Edge, Firefox

### Grafana platform?

Docker

### Datasource(s)?

Prometheus, OpenSearch

**Comment by drewmmiranda** [comment]
For reference https://github.com/easylist/easylist/issues/19380

IMO these are 2 separate issues (this URL being added to the list, and the existence of this URL and users not having documentation or control over it)

**Comment by drewmmiranda** [comment]
Disabling "analytics" has no effect whatsoever:

![image](https://github.com/grafana/grafana/assets/12700525/7cc43a50-0c24-4810-82d9-74af67fa673c)

**Comment by drewmmiranda** [comment]
Related:

* https://github.com/grafana/grafana/pull/89388
* https://github.com/grafana/grafana/pull/89379

**Comment by drewmmiranda** [comment]
Since this appears to be "fixed" i'll mark this as closed.

**Comment by indeyets** [comment]
@drewmmiranda the error is suppressed, but is it possible to disable analytics completely?

**Comment by joshhunt** [comment]
Just for some context - this endpoint reports some web vitals ([PerformanceBackend](https://github.com/grafana/grafana/blob/b43411631b616c962d86174134c60961bd0a98ee/public/app/core/services/echo/backends/PerformanceBackend.ts) and [app.ts](https://github.com/grafana/grafana/blob/27e800768ed82e83b621b36e0eed0f2345ea541e/public/app/app.ts#L287-L301)) to the backend and logs them as [prometheus metrics](https://github.com/grafana/grafana/blob/27e800768ed82e83b621b36e0eed0f2345ea541e/pkg/infra/metrics/frontendmetrics.go#L22-L37). These never leave your server or infrastructure (unless you chose to scrape them with Prometheus). See [Set up Grafana monitoring](https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-monitoring/) for more information about these metrics.

The [analytics config options](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#analytics) are used to control the 'phone home' analytics, but as these frontend metrics aren't reported back to Grafana, they're not controlled via this.

We're cutting some releases now - I'm looking into which versions exactly we'll release this in. In the mean time, you're free to allow this request through in your adblocker config, knowing that its not used as a part of telemetry that comes back to us.

**Comment by hasland** [comment]
FIY: Grafana 11.1.0 still shows "Failed to fetch". In 11.0.1 it's fixed.

**Comment by kolesaev** [comment]
Try disabling ad-blockers (eg. adBlock, uBlock, in-box browser's ad-blockers, etc) for Grafana page. Works for me

**Comment by sulo1337** [comment]
> @drewmmiranda the error is suppressed, but is it possible to disable analytics completely?

You can set environment variable GF_ANALYTICS_ENABLED to false to disable analytics completely.

**Comment by marc-cenon** [comment]
Hi, I updated to the latest kube-prometheus-stack helm chart with Grafana v11.1.0 but still have the problem.

**Comment by JumpWill** [comment]
this issue still exists , why close?

**Comment by ffrediani** [comment]
The issue still exists same way
Adding the env GF_ANALYTICS_ENABLED to false also doesn't work here
Brave with shields disabled for this URL
Grafana version 12.4.2
