### ISSUE TITLE
tsdb.HandleRequest() error bad_response: bad response code 400

### ISSUE THREAD

**Issue by rnkhouse** [grafana/grafana#8944]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
Version 4.4.1 (commit: 6a9f8ca)
- What datasource are you using?
prometheus
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
From summary dashboard trying to alert on CPU usage exceeds a certain percentage.
- What was the expected result?
Trigger alert successfully
- What happened instead?
result
firing true
state alerting
conditionEvals = true
timeMs 2.328ms
error tsdb.HandleRequest() error bad_response: bad response code 400
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
What does your query look like?

**Comment by rnkhouse** [comment]
@torkelo : sum(rate(node_cpu{instance="$host", mode!="idle"}[$interval])) by (mode) * 100 / count_scalar(node_cpu{mode="user", instance="$host"}) or sum(irate(node_cpu{instance="$host", mode!="idle"}[5m])) by (mode) * 100 / count_scalar(node_cpu{mode="user", instance="$host"})

**Comment by torkelo** [comment]
And if you use Chrome dev tools and look at the query grafana a sends to Prometheus (the interpolated query)

**Comment by rnkhouse** [comment]
That response is ok (200). But error is : Template variables are not supported in alert queries

**Comment by rnkhouse** [comment]
![grafana1](https://user-images.githubusercontent.com/3238963/28722464-d6149be6-7381-11e7-8c71-6146ff44be2a.png)
![grafana2](https://user-images.githubusercontent.com/3238963/28722468-d867bbbc-7381-11e7-9094-55770288b39c.png)

**Comment by torkelo** [comment]
> Template variables are not supported in alert queries

Read that, take a look at the query you use in your alert rule, does it use template variables? Yes.
