### ISSUE TITLE
Grafana crash after alert migration fail

### ISSUE THREAD

**Issue by MingjieZhuEmily** [grafana/grafana#89448]
### What happened?

When we change both grafana version from 9 to 10, and alerting from legacy to unified in grafana.ini, Grafana crash after failing to migrate two alert rules.
![image](https://github.com/grafana/grafana/assets/36128312/c490abad-4cf5-4aae-bf72-a2f716b32ff8)

### What did you expect to happen?

Grafana version upgraded, alert migrated, or miss some error alert, but Grafana does not crash

### Did this work before?

na

### How do we reproduce it?

Has some legacy alerts that could cause migration failure, upgrade version and alerting at the same time

### Environment (with versions)?

Grafana: 9.5 to 10.4
OS:
Browser:

### Grafana platform?

None

**Comment by jinghzhu-msft** [comment]
Hi Grafana Lab, looks like there is some bad alert in user workspace. Is it possible to detect those before encountering it during runtime?

**Comment by santihernandezc** [comment]
We suggest using the [migration preview tool](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-4/#grafana-alerting-upgrade-with-rule-preview) introduced in v10.4 to detect this kind of issues before migrating.
