### ISSUE TITLE
[Feature request] Ability to hide dashboard menu

### ISSUE THREAD

**Issue by kpachhai** [grafana/grafana#8946]
Hi,
I am not sure if other people have thought about this feature but I, for one, think would be a very neat feature in Grafana. There comes a time where there are lots of applications to manage and you don't wanna put every single graph in ONE dashboard. So, because of this, you create 5 different dashboards(for the same application) but serve different purposes(maybe one dashboard for managers, maybe one dashboard for more details about the application, maybe one dashboard for application health, another to aggregate results gotten from application, etc). 

At the moment, anytime we click on the dashboard menu to expand the list, we see every single dashboards in there so if we have 5 dashboards just for one application, the dashboard menu will be occupied by the dashboards for the same application. I know grafana has a bunch of options like dashboard list or linking to other dashboards but i think it would also be better if we have an option to disable dashboard menu for non-admins.

So, what i had in mind was the following use case scenario:
- Create 5 dashboards for application1, 3 dashboards for application2
- Create 1 dashboard(per application) that only contains the links to other dashboards with different description, annotations, text, etc whatever the case may be
- Disable certain dashboards so non-admins can only see the dashboards we want them to see so it reduces the clutter in the menu. So, in my case, i would probably wanna disable those 8 dashboards and only enable 2 dashboards
- The user then goes to one of  those two dashboards and then they can navigate to other dashboards from there(instead of having to go there directly via the menu)
- This would solve the problem of lack of hierarchy in dashboard menu that we currently have in grafana

Let me know your thoughts.

**Comment by torkelo** [comment]
We are going to introduce dashboard folders soon which will solve this organization problem nicely

**Comment by torkelo** [comment]
Thanks for the detailed feature request description! Closing this as I think grafana will have enough features to support this case with dashboard links, and dashboard folder

**Comment by Anthamma** [comment]
Hi i'm also facing same issue, i have multiple dashboard for drill down but i need to hide it in dashboard list and show only when drill down is done. is it possible??

**Comment by wamarobert** [comment]
Hi, Is there an option to hide the installed apps/ panels from other users with "viewer" Roles?

**Comment by wamarobert** [comment]
Hi, I got away around it, the only way was to create a new dashboard hence making it default.
