### ISSUE TITLE
Error 1406: Data too long for column 'data' at row 1

### ISSUE THREAD

**Issue by kengrary** [grafana/grafana#8947]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?   
4.4.1
- What datasource are you using? 
MySQL 5.6
- What OS are you running grafana on? 
CentOS 7
- What did you do? 
Save the dashboard
- What was the expected result? 
Save the dashboard successful.
- What happened instead? 
Error 1406: Data too long for column 'data' at row 1
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
This problem was relative to the data table dashboard_version, the type of column data is text, my dashboard data was bigger then the length of text (65535), so I change the column from text to longtext to bypass this problem.

**Comment by torkelo** [comment]
This has already been  reported and fixed in master and 4.4.x branch, will be included in 4.4.2 patch release next week
