### ISSUE TITLE
InfluxDB: `array_agg` returns no data

### ISSUE THREAD

**Issue by appletreeisyellow** [grafana/grafana#89499]
### What happened?

Data source: InfluxDB

`SELECT array_agg([1])` returns no data in Grafana

https://github.com/grafana/grafana/assets/14298407/936bb89b-7582-42f5-88d6-4e35efc6fdc9

### What did you expect to happen?

```sql
SELECT array_agg([1]);
+---------------------------------+
| ARRAY_AGG(make_array(Int64(1))) |
+---------------------------------+
| [[1]]                           |
+---------------------------------+

SELECT array_agg([1]), arrow_typeof(array_agg([1]));
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ARRAY_AGG(make_array(Int64(1))) | arrow_typeof(ARRAY_AGG(make_array(Int64(1))))                                                                                                                                                                               |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [[1]]                           | List(Field { name: "item", data_type: List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) |
+---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Did this work before?

I don't think so

### How do we reproduce it?

1. Connect to an InfluxDB data source
2. Explore data
3. Run query `SELECT array_agg([1])`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d94d597d84)
OS:
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by aangelisc** [comment]
Hi @appletreeisyellow,

I can confirm I've replicated this behaviour. However, I can also see the same behaviour when querying via the data explorer as shown in the image below. Can you provide details on how you're executing the query and retrieving results?

![Image](https://github.com/user-attachments/assets/1025b87d-e7a7-433b-b4fc-95d005ca8016)

**Comment by appletreeisyellow** [comment]
@aangelisc Thanks for looking into this! Yes, InfluxDB data explorer also has this bug. 

Here is another way to execute the query and retrieve the result -- using InfluxDB Python Flight SQL library ([doc](https://docs.influxdata.com/influxdb/cloud-serverless/reference/client-libraries/flight/python-flightsql-dbapi/)). 

Here are steps to reproduce:

1. Install

```
pip install flightsql-dbapi
```

2. Create a python file, let's call it `python-client-flightsql.py`, with the following code:
```py
# python-client-flightsql.py

from flightsql import FlightSQLClient

# Instantiate a FlightSQLClient configured for a database
client = FlightSQLClient(host='us-east-1-1.aws.cloud2.influxdata.com',
    token='API_TOKEN',
    metadata={'database': 'sample_data'}, # i.e. bucket (any bucket)
    features={'metadata-reflection': 'true'})

# Execute the query to retrieve FlightInfo
info = client.execute("SELECT array_agg([1])")

# Extract the token for retrieving data
ticket = info.endpoints[0].ticket

# Use the ticket to request the Arrow data stream.
# Return a FlightStreamReader for streaming the results.
reader = client.do_get(ticket)

# Read all data to a pyarrow.Table
table = reader.read_all()

print(table)
```

* Instructions of how to create an API token: https://docs.influxdata.com/influxdb/cloud-serverless/admin/tokens/create-token/#Copyright
* Instructions of how to create a bucket (i.e. database): https://docs.influxdata.com/influxdb/cloud-serverless/admin/buckets/create-bucket/#create-a-bucket

3. Run the python code

```
$ python3 python-client-flightsql.py
pyarrow.Table
array_agg(make_array(Int64(1))): list<item: list<item: int64>>
  child 0, item: list<item: int64>
      child 0, item: int64
----
array_agg(make_array(Int64(1))): [[[[1]]]]
```

**Comment by appletreeisyellow** [comment]
As you can see from the above python code, `SELECT array_agg([1])` returns `List`, which is not supported in the grafana code:

https://github.com/grafana/grafana/blob/78ce9b8f39dd815bc7b116f565aaed5b088b2a5a/pkg/tsdb/influxdb/fsql/arrow.go#L124-L157

We (InfluxData) documented a workaround [here](https://docs.influxdata.com/influxdb/cloud-serverless/query-data/troubleshoot-and-optimize/troubleshoot/#why-doesnt-my-query-return-data) FYI. Basically, use `array_to_string()` to convert the list into a string. For example:

```
SELECT array_to_string(array_agg([1, 2, 3]), ', ')
```

this will return the result correctly

```
1, 2, 3
```

**Comment by aangelisc** [comment]
Hey @appletreeisyellow,

Thank you for the steps above that was extremely helpful. Is this the response you'd expect to see?

![Image](https://github.com/user-attachments/assets/aacc37e5-4361-4938-8904-553cd3da348e)

**Comment by appletreeisyellow** [comment]
> Is this the response you'd expect to see?

@aangelisc Yes! 💯
