### ISSUE TITLE
[Bug]Alert can be trigger but not send email

### ISSUE THREAD

**Issue by lwhile** [grafana/grafana#8950]
### Grafana version
v4.4.0

### Dataource
Influxdb

### OS
Centos 7

### What did I do
I added a email notification  and webhhok to channel , and it could pass the email test (my box received a email sent by grafana ), and my server could received a webhook event.

Then I configed a alert about memory usage

### Expected result and happened instead
I hope I can received a webhook event and a email notificaton when the alert was be trigger.But I just only received a webhook event, no a email.

I had checked the log file, but no found something useful about email.

**Comment by torkelo** [comment]
What does your alert config / notification side tab look like? Are both notifications added? Can you show the grafana.log output for the time the alert fired?

**Comment by lwhile** [comment]
@torkelo  thanks for you reply.

![image](https://user-images.githubusercontent.com/13641863/28706950-ff631e2e-73a8-11e7-9f12-f678424d65eb.png)

![image](https://user-images.githubusercontent.com/13641863/28706978-1bf8d920-73a9-11e7-9ec7-b53794c889f0.png)

Both config could work well when I touch SEND TEST button.

and my memory alert config like this:

![image](https://user-images.githubusercontent.com/13641863/28707046-6130476c-73a9-11e7-94da-54ea189f8f02.png)

![image](https://user-images.githubusercontent.com/13641863/28707164-d92daae8-73a9-11e7-8953-e9885e653937.png)

Webhook notification could work well, but I couldn't receive email sent by grafana.  

and that is  log when I touch SEND TEST button:
```
t=2017-07-28T14:08:39+0800 lvl=info msg="Sending notification" logger=alerting.notifier type=webhook id=0 isDefault=false
t=2017-07-28T14:08:39+0800 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
t=2017-07-28T14:20:18+0800 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-07-28T14:20:18+0800 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xxx@xxx]
```

I not found useful log when the my memory alert was be trigger.

**Comment by torkelo** [comment]
Looks like it is sending the email

**Comment by lwhile** [comment]
I checked my box again, but could not find any email except that sent by test :(

**Comment by lwhile** [comment]
@torkelo Hello, it seems that alert run well now, but I don't know why it didn't work well 3h before
