### ISSUE TITLE
Plugin: Query function not working in version 11

### ISSUE THREAD

**Issue by farahzahid001** [grafana/grafana#89516]
### What happened?

I have created grafana frontend datasource plugin using following command

npx @grafana/create-plugin@latest

It created the plugin successfully with docker-compose file which is using grafana 10.3.3 version for development.
But I need to use the version 11 for development. When I change the grafana version in docker-compose file from 10.3.3 to 11.0.0 

`grafana_version: ${GRAFANA_VERSION:-10.3.3}` to `grafana_version: ${GRAFANA_VERSION:-11.0.0}`

then query function of datasource stop working. Like it is not running when I call `onRunQuery()` function and when I click on Run Query in explorer view. 

below is query function which is created by default when we create plugin 

`async query(options: DataQueryRequest<MyQuery>): Promise<DataQueryResponse> {
    debugger
    const { range } = options;
    const from = range!.from.valueOf();
    const to = range!.to.valueOf();

    const data = options.targets.map((target) => {
      return new MutableDataFrame({
        refId: target.refId,
        fields: [
          { name: 'Time', values: [from, to], type: FieldType.time },
          { name: 'Value', values: [target.constant, target.constant], type: FieldType.number },
        ],
      });
    });

    return { data };
  }`

### What did you expect to happen?

query function should work on grafana version 11

### Did this work before?

No

### How do we reproduce it?

1.  Create plugin using this command `npx @grafana/create-plugin@latest` without backend 
2. Change grafana version from 10.3.3 to 11.0.0
3. Run the code and you will see query function is not working

### Environment (with versions)?

Grafana: 11
OS: Ubunut
Browser: Chrome 

### Grafana platform?

Docker

**Comment by farahzahid001** [comment]
I have also deployed the plugin after building it. But it still not calling the query function

**Comment by simPod** [comment]
Same here for https://github.com/simPod/GrafanaJsonDatasource

It does not work on Grafana 11, query function is not called. The plugin complies with the DataSourceApi interface.

**Comment by academo** [comment]
Hi @farahzahid001 thanks for your report, I did some tests and I can see everything is working as expected (the `query` method running) but I also have an idea of what might happening to your code.

Here's a screenshot of a fresh-created plugin running in Grafana 11 (via docker as you did). The only modification was the `console.log` to see the trace in the browser console.

![image](https://github.com/grafana/grafana/assets/227916/7ef1ea48-aa1e-458d-98ec-a200a4b151bc)


What I think is happening?

The datasource generated by create-plugin (with backend=false selected) has the following method in the datasource file:

```typescript
export class DataSource extends DataSourceApi<MyQuery, MyDataSourceOptions> {
  // ... 
  filterQuery(query: MyQuery): boolean {
    // if no query has been provided, prevent the query from being executed
    return !!query.queryText;
  }
  //..
}
```

This method tells Grafana to skip the query if it returns a falsy value. In the case of the generated code, it won't run the query if you don't type something in the "query text" field of the query editor. Grafana 11 respects this method while Grafana 10 doesn't.

Additionally the generated datasource doesn't auto-trigger onQuery by itself. you have to press the refresh button in the dashboard to run the query again.

Could you please check perhaps that you don't have a `filterQuery` method in your datasource that is perhaps telling Grafana to skip the query?

If you can share the source code of your plugin would be ideal for us to take a look.
