### ISSUE TITLE
Explore: Previous query is sometimes passed to query editor which causes flash of new-old-new query in editor

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#89530]
Explore sometimes after passing new query, passes to the query editor previous query and then the new query again, causing a flash of old-new-old query in the editor.

See the issue here: 

https://github.com/grafana/grafana/assets/30407135/951c09a3-2c2f-4018-97cc-dd3e43fb2ed2

Noticed while working on: https://github.com/grafana/grafana-infinity-datasource/pull/884

**Comment by ifrost** [comment]
I could be related to query imports 🤔 Does it happen in other data sources which don't support imports as well?

**Comment by ivanahuckova** [comment]
I've noticed it also in Infinity data source that does not support query imports https://github.com/grafana/grafana-infinity-datasource/blob/main/src/datasource.ts

**Comment by ivanahuckova** [comment]
Thank you for fixing this @ifrost! 🫶
