### ISSUE TITLE
[Bug] Axis labels/grid are wrong with IEC units

### ISSUE THREAD

**Issue by marcan** [grafana/grafana#8957]
Grafana version:  v4.2.0 (commit: 349f3eb) 
Datasource: prometheus

With the left Y axis set to data (IEC)>bytes I see this scale:

![spectacle nn4796](https://user-images.githubusercontent.com/98387/28755918-80e8726c-759f-11e7-8b2d-7ce67e6b18c5.png)

This is obviously wrong; the scale isn't linear. Also, I have "decimals" set to 2, but Grafana is only displaying one significant digit. Changing the scale to metric does not change the graph or the gridlines, but the labels are now 2GB/4GB/6GB/8GB. So it seems that the GiB labels are wrong entirely, as the gridlines are aligned on metric divisions, not IEC, and furthermore the labels are being strangely rounded.

If I vertically expand the graph, then I get this:

![spectacle zb4796](https://user-images.githubusercontent.com/98387/28755934-e23df0a0-759f-11e7-9ccf-d8084fec0cc4.png)

That's at least correct modulo rounding, but those grid divisions aren't useful. The grid should be aligned on integer IEC multiples, not integer metric multiples.

**Comment by keithf4** [comment]
Not sure if this is related, but figured I'd respond here first before making a new issue.

It seems to be calculating the size wrong when summarizing to larger unit scales. Using prometheus as the data source, and I checked that it is returning the correct values.
```
Filesystem          1K-blocks    Used Available Use% Mounted on
/dev/mapper/cl-root  13092864 6194464   6898400  48% /
devtmpfs               926000       0    926000   0% /dev
tmpfs                  941712    8932    932780   1% /dev/shm
tmpfs                  941712    9004    932708   1% /run
tmpfs                  941712       0    941712   0% /sys/fs/cgroup
/dev/sda1             1038336  233088    805248  23% /boot
tmpfs                  188344       4    188340   1% /run/user/42
tmpfs                  188344      32    188312   1% /run/user/1000
```
```
node_filesystem_avail{device="rootfs",fstype="rootfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/"}	7063990272
node_filesystem_avail{device="sunrpc",fstype="rpc_pipefs",instance="127.0.0.1:9100",job="Prod",mountpoint="/var/lib/nfs/rpc_pipefs"}	0
node_filesystem_avail{device="/dev/sda1",fstype="xfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/boot"}	824573952
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run/user/42"}	192860160
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run/user/1000"}	192831488
node_filesystem_avail{device="tmpfs",fstype="tmpfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/run"}	955092992
node_filesystem_avail{device="/dev/mapper/cl-root",fstype="xfs",instance="127.0.0.1:9100",job="Prod",mountpoint="/"}	7063990272
```
`df` returns values in kilobytes and I checked the conversion values to bytes in prometheus and they match

If I just leave the units as "none" in grafana, it shows the matching value from prometheus in grafana. However, setting the unit type to "bytes"(either IEC or Metric) in grafana, the values it calculates when summarizing to GB are off. The above values convert to roughly 6.6GB and 787MB for availability of the xfs partitions, but grafana is reporting it as about 7.06GB and 825MB respectively.

**Comment by torkelo** [comment]
Can you show the exact response from prometheus that grafana gets and your panel settings? When I test I get 100% match (IE correct values shown) so must be something strange going on. 

Is the graph yaxis ticks or the legend value or the graph tooltip values that look wrong to you?

**Comment by marcan** [comment]
7063990272 bytes is 6.6GiB or 7.06GB. 824573952 bytes is 786MiB or 825MB. @keithf4 I think you're mixing up your units. I'm not seeing any wrong values in my setup - it always uses whatever style I selected (IEC or metric style) for the tooltip and the legend. This bug is about the graph axis scale being wacky, not the data being wrong.

**Comment by keithf4** [comment]
I could've sworn I tried changing that back and for between IEC and Metric before. I did say that originally. Now this morning it's behaving on my own system after restarting the VM. Will try again on the client system again where we were struggling with this last week. Wonder if it's something about the loading/creation of the graph that it's not switching units sometimes.

**Comment by kogaba** [comment]
I think my issue is related to this. I am on Grafana 6.6.2, so maybe it is already solved.
Y axis set to IEC bytes, and the scale is fine while adding an another series value. (there is no stacking or anything)
![output](https://user-images.githubusercontent.com/22454806/75614407-bdde9a80-5b38-11ea-896a-142ae6e23aa0.gif)

**Comment by Steve-dG** [comment]
Hopefully this graph will make it a bit more clear what is wrong with the y axis grid when using IEC units.
They all show the same data, but in different (artificial) source units. It clearly shows that the labels are rounded to the nearest base 10 units, instead of the nearest base 2 units. The '1 TiB' unit shows different GiB values instead of the 'real' 1 GiB.
When 'converting' to base 10 units, the labels are shown correctly.

![image](https://user-images.githubusercontent.com/18736062/92008904-06754b80-ed48-11ea-874b-babbff00c66b.png)

**Comment by marcan** [comment]
Yes, the problem is that the scale divisions are on base-10 units, but then show rounded base-2 labels. The grid needs to change to base-2 multiples to fix this and do what is expected. Until then, base-2 modes are basically not useful on graphs, because it makes the grid very misleading.

**Comment by Berbe** [comment]
From what I understood from the code, it seems to me the maths in the `setupTickGeneration` procedure of the `public/vendor/flot/jquery.flot.js` file might be responsible for computing axis size/segmentation.
I see a lot of base 10 computation in there, although it eludes me.

**Comment by rovo89** [comment]
Just checked with the new *Time series* panel, the ticks are similarly "unusual":

![image](https://user-images.githubusercontent.com/1573299/105355197-063ff480-5bf2-11eb-9e5b-6ca37eef2ce6.png)

**Comment by bboreham** [comment]
Today was my day to get irritated by this.  The axis should show numbers that look nice in the scale selected.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/8125524/206167802-c2dae560-5855-4f15-b7ac-fcd321bba14e.png">

^^ 186GiB is 200 billion; for this chart 160GiB or 180GiB seem reasonable to me, but even 200GiB would be better.
