### ISSUE TITLE
Percent stacking and legend values

### ISSUE THREAD

**Issue by majj** [grafana/grafana#896]
Display Styles > Multiple Series > Stack & Percent selected,  the Left Y Axis keep the original format, it should be present (%).  if change the format manually, the format of legend value is wrong.

![f1](https://cloud.githubusercontent.com/assets/543810/4518560/d93e5da2-4c92-11e4-9fbc-38fa77b1ecbf.png)

![f2](https://cloud.githubusercontent.com/assets/543810/4518561/e7227674-4c92-11e4-866c-3a4504ad725c.png)

**Comment by nemenemsrouge** [comment]
hello,

any news? I 've got the same issue => frustrating ^^

**Comment by torkelo** [comment]
@nemenemsrouge it requires a lot of work to fix this. The percent stacking code need to be moved out of the flot charts plugin. I would welcome a PR :) 

I am not sure when I have time too rewrite the stack percent feature. For graphite users there is always the percent function that you can use which will work a lot better (legend values and hover will be percent then)

**Comment by mnietz** [comment]
Are there any plans, in which release the bugfix / pr will be included ? Are there any known workarounds ? I need to have a table sorted by the percentage-values.

**Comment by torkelo** [comment]
@mnietz if you use graphite you can use the asPercent function

**Comment by mnietz** [comment]
No, sorry forget to mention, i use Influx 0.9.2 with Grafana 2.1.0pre1

**Comment by torkelo** [comment]
ok, sorry to hear that. well if more people request this it could be added to a future milestone

**Comment by mtanda** [comment]
Not sure, is https://github.com/grafana/grafana/pull/2379 fixed this?

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/2379
