### ISSUE TITLE
Loki Data Source Config: show maximum line limit in field

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#89608]
We have spotted the issue. Their datasource was configured to max lines 10k, when the max allowed in the backend is 5k. However, there is no mention of this max in the tooltip. Is this something we can include to avoid such situations? 

![image](https://github.com/grafana/support-escalations/assets/25328174/5d0dad06-5b0e-45c1-b58d-8ce8997531ab)

**Comment by svennergr** [comment]
maximum line limit is configurable in Loki. I don't think this it is easily possible to include that value in the tooltip.
https://grafana.com/docs/loki/latest/configure/#:~:text=max_entries_limit_per_query

**Comment by matyax** [comment]
Good point. I think we could do a better job letting them know how it works from the tooltop and docs. https://grafana.com/docs/grafana/next/datasources/loki/configure-loki-data-source/#queries

**Comment by matyax** [comment]
Not a lot of value out of this issue. We can come back to this if we have a good reason to.
