### ISSUE TITLE
[Bug] Each request to the login page uses 3-4 inodes

### ISSUE THREAD

**Issue by marcv81** [grafana/grafana#8961]
I am using Grafana v4.4.1 (commit: 6a9f8ca) on Debian Stretch 9.0. I use the default grafana.ini.

I hit http://localhost:3000/login repeatedly, with a script.

Grafana appears to create 3-4 inodes for each request to the /login page. The server disk filled up in 10 minutes (there is still space, but no inode to allocate). I believe the files are created in /var/lib/grafana/sessions. I otherwise use `df -i` to see how many inodes are available. During a separate test where I didn't let the disk fill up I observed that the allocated inodes do not get reclaimed even if I give Grafana 10+ minutes.

**Comment by torkelo** [comment]
The session lifetime is longer than  10 minutes, you can switch to mysql or redis session, or lower session timeout, or include the session cookie in subsequent requests in your script
