### ISSUE TITLE
Explore/Tempo: Reloading the query shifts the date by 30 minutes

### ISSUE THREAD

**Issue by thoro** [grafana/grafana#89637]
### What happened?

When activating the "Use time range in query" option for tempo and reloading a trace in the Trace Explore View the selected time range moves with each consecutive click (by 30 minutes). It does not change if the option is NOT activated.

### What did you expect to happen?

Reloading has no effect on the time range.

### Did this work before?

Not to my knowledge.

### How do we reproduce it?

1. Activate option "Use time range in query" in Datasource configuration
2. Navigate to a trace and select a time range.
3. Click refresh / reload ->  Time span changes with each click

### Environment (with versions)?

Grafana: 11.0.0
OS: macOS
Browser: Chrome 125

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by ifrost** [comment]
I was able to reproduce it in 11.0.0 but not in 11.1.0. It seems like it was fixed by https://github.com/grafana/grafana/pull/87980. I'll close the issue but feel free to re-open and provide more details if it's not working as expected.
