### ISSUE TITLE
[Bug] template metric not showing up from metrics($namespace, $region)

### ISSUE THREAD

**Issue by AnthonyWC** [grafana/grafana#8965]
- What Grafana version are you using?
Grafana v4.4.1 (commit: 6a9f8ca)

- What datasource are you using?
Cloudwatch

- What OS are you running grafana on?
host: Ubuntu 16.04.1 LTS
container: Debian GNU/Linux 8 (jessie)

- What did you do?
I try to get metrics dynamically based on namespace selection: metrics($namespace, us-east-1) for template (which didn't work): 

![image](https://user-images.githubusercontent.com/6215805/28794409-40d44826-7604-11e7-86b8-89843be03146.png)

For example, the namespaces are queried dynamically:
![image](https://user-images.githubusercontent.com/6215805/28794529-9ea6463e-7604-11e7-9b51-5b1be83c9c3b.png)

- What was the expected result?

I expected to use the custom metrics to show up, which does if I manually specify it, e.g.:
![image](https://user-images.githubusercontent.com/6215805/28794465-7a0f1b52-7604-11e7-8385-3019ac4b4154.png)

- What happened instead?
It doesn't show up.

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap
