### ISSUE TITLE
[Bug] Holes in the Graph panel

### ISSUE THREAD

**Issue by Dunkhase** [grafana/grafana#8974]
Hello, 
sorry I'm new here but i have a problem and search now a week for a Solution.
My feeling is that this is a small bug in the Graph. Please have a short look, and give me a 
idea what can be wrong.

Best regards Holger

- I use Grafana 4.3.1  and 4.4.1 same result
- What datasource are you using? MYSQL
- What OS are you running grafana on? Windows 7
- What did you do? Every thing is nice but some times i have a hole under the Bar's
- If related to metric query / data viz: The Data i checked there is all OK, i cant see any problem there.

![image](https://user-images.githubusercontent.com/30649822/28869501-31319d2c-777d-11e7-8be9-4c45a66439fa.png)

![image](https://user-images.githubusercontent.com/30649822/28869530-58db5aac-777d-11e7-933f-27ec2d22a371.png)

**Comment by torkelo** [comment]
what does your query look like and what does it return?

**Comment by Dunkhase** [comment]
The Query is very simple, and when check the Data it's ever thing OK.

SELECT 
UNIX_TIMESTAMP(Timestamp) as time_sec,
winding_Heads as value,
`tbl_machines`.`Machine_Text`  as metric
from tbl_winding_Heads_Stat
where  $__timeFilter(Timestamp) and winding_Heads >0
order by Timestamp

When you Zoom into the Graph then the Hole comes not again.
In this Query i have a result of 1200 Rows.

Holger

**Comment by torkelo** [comment]
you need a group by time so all the data is normalized into equal buckets, with zeros included for missing data. Not sure that is possible to do in SQL
