### ISSUE TITLE
Conflicting Alert Rule Response Has Wrong 'rule_uid'

### ISSUE THREAD

**Issue by bmoe24x** [grafana/grafana#89755]
### What happened?

We are using the [Alert Rule HTTP API](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/) and I noticed what appears to be a potential bug. We have a use case that will sometimes try to create an alert that may already exist (side note, it would be really handy make the POST just update if it exists, perhaps configurable via header). When we attempt to get the below error as expected according with the documentation:

```json
{
  "message": "[alerting.alert-rule.conflict] conflicting alert rule found [rule_uid: 'adpx066eftmv4b', title: '<MY_LAG_ALERT_NAME>', namespace_uid: '<MY_LAG_ALERT_FOLDER_UID>']: rule title under the same organisation and folder should be unique",
  "traceID": ""
}
```

Fine right? Well the `rule_uid` value is not correct. When I do a GET on that alert rule UID I get a 404 Not Found. This is further observed by resending the POST more times, I can watch the `rule_uid` change each time despite the title/body being _exactly_ the same each time. 

This is fairly inconvenient as we were hoping to use and store that `rule_uid` for another use case 

Looks like some of the code in[ question might be here ](https://github.com/grafana/grafana/blob/4651506319fa1e1d96487f4b7818ac86a77e553e/pkg/services/ngalert/models/errors.go#L15)

### What did you expect to happen?

I expect the `rule_uid` returned by the POST alert rule API on a conlicting alert to represent the conflicting alert in question

### Did this work before?

Not sure, greenfield project. 

### How do we reproduce it?

1. Create an alert with the HTTP Alert Rule API via POST request
2. Send that same exact POST request again, take note of the `rule_uid` in the response `message` value
3. Do a GET on the `rule_uid` retrieved from the previous step, in my testing I get a 404 Not Found 
4. Repeat, I can see the `rule_uid` changing each iteration of the POST despite the original alert rule still being available from the UI with the original alert rule UID (and no duplicate alerts being present)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.4.1 (enterprise on-prem)
OS: N/A (using HTTP API)
Browser: N/A (using HTTP API)

### Grafana platform?

Other

### Datasource(s)?

N/A - this is for Alert Rule API (utilizing a Prometheus/Thanos source)

**Comment by JacobsonMT** [comment]
Hi @bmoe24x, the `rule_uid` returned is the uid of the rule from your posted group that is conflicting with an existing rule in the folder. It is not the `rule_uid` of the existing rule. The error message could be a bit clearer for create requests since the rule uids are newly generated and have no use being returned.

**Comment by wasim-nihal** [comment]
Is this issue open for contribution? I would like to work on this.
