### ISSUE TITLE
[Bug] Viewer can delete dashboards through API

### ISSUE THREAD

**Issue by derbeneviv** [grafana/grafana#8976]
Hello!  
Today we accidentally tried to delete a dashboard via Viewer user and succeeded!
Grafana version used: both 4.2 and 4.4.1, CentOS7

steps to reproduce:

1. create dashboard
2. create user in organization with Grafana Admin=false and role = Viewer
3. run `curl -k -X DELETE -u test:test https://host/grafana/api/dashboards/db/new-dashboard-copy`
4. cry like a baby on your deleted dashboard

permissions list (upper - global permissions, lower - org permissions):
![alt text](http://i.imgur.com/8RithtE.png)

curl:
`curl -k -X DELETE -u test:test https://host/grafana/api/dashboards/db/new-dashboard-copy`
curl response:
`{"title":"New dashboard Copy"}`
actual result:
no such dashboard exists

**Comment by derbeneviv** [comment]
i'm not anything close to being a go coder, but it seems like we need r.Delete somewhere here:  
https://github.com/grafana/grafana/blob/master/pkg/api/api.go#L233

**Comment by torkelo** [comment]
well that's embarrassing, thanks for reporting this. fixing asap
