### ISSUE TITLE
Dashboard not loading on iPad with iOS 15.8.2

### ISSUE THREAD

**Issue by otto802** [grafana/grafana#89792]
### What happened?

I've used my old "iPad Air 2" as a wall mounted dashboard successfully over the years. Seems that Grafana V11 breaks the support for older Safaris? I'm using the latest docker install of Grafana (updated regularly).

It shows just the orange "If you're seeing this Grafana has failed to load its application files" message.

### What did you expect to happen?

I would like to use Grafana still on old iOS devices... 

### Did this work before?

I'm not exactly sure, but as I update the docker image regularly I guess its since V11?

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: v11.0.1 (302831c125)
OS: iOS 15.8.2
Browser: Safari

### Grafana platform?

Docker

**Comment by SokoFromNZ** [comment]
I have the exact same issue!

I'm on an "iPad mini 4" with iOS 15.8.2 (latest version).

www.whatismybrowser.com says:
Safari 15.6 on iOS 15.8
JavaScript enabled
Cookies enabled
3rd party cookies disabled

I've also tried:
**Firefox** 127.1 (42781): **same issue**
**DuckDuckGo** 7.126.0.1: **same issue**
**Opera** 4.7.0 (2): **same issue**
**Aloha** 5.11.0: **same issue**

I was not able to install Chrome, Brave, Edge as they require iOS 16.

Any help would be highly appreciated here :(

**Comment by alexadamski** [comment]
Same issue

**Comment by tskarhed** [comment]
This seems to be an iOS-specific issue. If you can provide some browser logs, it would be very helpful.

**Comment by SokoFromNZ** [comment]
@tskarhed
I'm happy to help here... but on iOS/Mac/Apple I'm just a user :) So you have to guide me a little how to provide logs from Safari on my iPad.

**Comment by otto802** [comment]
on iOS (at least below iOS 17.4) all browsers have to use the built in WebKit rendering engine. So there it possibly does not matter if it's a Firefox on iOS or a plain Safari - its all the same in the end.

I heard there is a JS console for Safari on iOS when the device is connected to a Mac. Maybe that gives some hints.

**Comment by tskarhed** [comment]
> on iOS (at least below iOS 17.4) all browsers have to use the built in WebKit rendering engine. So there it possibly does not matter if it's a Firefox on iOS or a plain Safari - its all the same in the end.
> 
> I heard there is a JS console for Safari on iOS when the device is connected to a Mac. Maybe that gives some hints.

So this could be a matter of an outdated WebKit version, rather than any browser version?

**Comment by tskarhed** [comment]
> @tskarhed I'm happy to help here... but on iOS/Mac/Apple I'm just a user :) So you have to guide me a little how to provide logs from Safari on my iPad.

This seems like a good guide https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by SokoFromNZ** [comment]
I'm on vacation currently and cant do anything till next week. If nobody else have done it until then I'll give it a try.

**Comment by JannikArndt** [comment]
For me, downgrading to 10.x worked:

```
sudo apt install grafana=10.4.6
```

**Comment by xtvdata** [comment]
Just tested with:
- old iPhone8 on 15.8.2: same behavior
- iPad Pro on 16.7.8: working 
- iPhone 15 with latest iOS: working (just for confirmation)

P.S.: unfortunately downgrade is not an option here...

**Comment by SokoFromNZ** [comment]
> > @tskarhed I'm happy to help here... but on iOS/Mac/Apple I'm just a user :) So you have to guide me a little how to provide logs from Safari on my iPad.
> 
> This seems like a good guide https://www.lifewire.com/activate-the-debug-console-in-safari-445798

@tskarhed I've had a detailed look now. I cannot provide you with debug data here as I dont have a mac which is needed to debug Safari on iPad/iPhone, sorry.

Maybe someone else could have a look here please?

**Comment by tskarhed** [comment]
@SokoFromNZ Thanks for trying at least!

I am closing this for using an outdated WebKit version at the moment.

If someone comes across this issue with the means to debug, feel free to either open a new issue referring to this one, providing browser errors, or post a comment in this issue mentioning `@grafana/grafana-frontend-platform`

**Comment by xtvdata** [comment]
> > > @tskarhed I'm happy to help here... but on iOS/Mac/Apple I'm just a user :) So you have to guide me a little how to provide logs from Safari on my iPad.
> > 
> > 
> > This seems like a good guide https://www.lifewire.com/activate-the-debug-console-in-safari-445798
> 
> @tskarhed I've had a detailed look now. I cannot provide you with debug data here as I dont have a mac which is needed to debug Safari on iPad/iPhone, sorry.
> 
> Maybe someone else could have a look here please?

The console actually reports some errors:
<img width="718" alt="Screenshot 2024-08-12 alle 14 22 11" src="https://github.com/user-attachments/assets/d5403f67-a7f3-452c-b095-ddfd00a2c80c">

Extracting some code (skipping 1st one that for some reasons I can't seem to be able to open...)

```js
"use strict";
```

```js
                        Pt(e + `
Arguments: `
                        + Array.prototype.slice.call(i).join("") + `
`
                        + new Error().stack),
                        _ = !1
```

```js
(self.webpackChunkgrafana = self.webpackChunkgrafana || []).push([[9778], {
```

Besides last case, which seems to be an unsupported feature of JS, previous errors do not match exactly with error message.
It seems like there is some character that is not shown, particularly in the last one:
```js
                        Pt(e + `
Arguments: `
                        + Array.prototype.slice.call(i).join("") + `
`
                        + new Error().stack),
                        _ = !1
```
Where the error is in the 4th line (the one with a single "`", after ".join("") + `", and the error is "_Unexpected token '?'_"

**Comment by SokoFromNZ** [comment]
@xtvdata thanks heaps.
@grafana/grafana-frontend-platform (@tskarhed this mention does not seem to do anything... does it?)

**Comment by tskarhed** [comment]
@xtvdata Thank you. Do you have the possibility to run it in development mode so it is possible to see the unminified version of the errors? Alternatively create an instance on Grafana Cloud, and maybe I can identify the errors through some of our troubleshooting tools.

**Comment by xtvdata** [comment]
> @xtvdata Thank you. Do you have the possibility to run it in development mode so it is possible to see the unminified version of the errors? Alternatively create an instance on Grafana Cloud, and maybe I can identify the errors through some of our troubleshooting tools.

You’re welcome.

I should be able to give it a shot at the beginning of September… (now I’m on holiday, far far away from any real keyboard 😁)

I’ll try first to run a vm in dev mode, or eventually opens Grafana Cloud account and test it with some sample data (I doubt that data is actually relevant for this issue).

**Comment by tskarhed** [comment]
I managed to get ahold of an older device. The error is because nullish coalescing operators `??` are used in the bundled Javascript. As this is the way forward, there is no reason to transpile/polyfill an alternative solution. Hence, this issue will not be fixed.

**Comment by otto802** [comment]
A bit sad but understandable! Thanks for looking into it! 

Let's blame Apple for not open their systems to up-to-date browser engines. However I've bought a recent iPad to keep Grafana running on my wall...

**Comment by lhns** [comment]
I've managed to transform the current version of grafana using babel to be comatible with iOS 15.
You can try it out here: https://github.com/lhns/docker-grafana-babel

**Comment by adammabrouk** [comment]
@lhns you're a lifesaver !
