### ISSUE TITLE
Dashboard: InfluxDB V2 Flux variable queries are broken in Grafana 11.1.0

### ISSUE THREAD

**Issue by strenker** [grafana/grafana#89798]
### What happened?

After migration from Grafana 10.4.2 to Grafana 11.1.0 all dynamic Flux variable queries which make use of the dynamic dashboard time range in dashboards are broken. 

After setting Grafana log level to "debug" i could verify in my syslog that "v.timeRangeStart" and "v.timeRangeStop" show both the values "1970-01-01T00:00:00Z". (The same broken values are shown in the InfluxDB log.) For me this looks as if the built-in "v" variable is not initialized/referenced correctly for dynamic Flux dashboard variable queries.

When i replace "v.timeRangeStart" and "v.timeRangeStop" with "time(v: some reasonable timestamp)" the query works as expected.

### What did you expect to happen?

Flux dashboard variable queries work the same way as in Grafana 10.x

### Did this work before?

In Grafana 10.x it works

### How do we reproduce it?

see above

### Is the bug inside a dashboard panel?

see above

### Environment (with versions)?

Grafana: 11.1.0, built from Git-Source
OS: Gentoo Linux
Browser: Firefox 115

### Grafana platform?

Other

### Datasource(s)?

InfluxDB V2 and Flux

**Comment by cholyoak** [comment]
Same problem here going from 11.0.0 to 11.1.0 on Debian Bookworm. Queries run fine in the datasource explorer but fail in a dashboard variable.

**Comment by Akenjeru** [comment]
The same thing, I use telegraph to transfer data to InfluxDB 2.7.6 and everything is clearly visible there and everything was fine in Grafana in 11.0.0, but after updating to 11.1.0, the data in influxdb is still shown, but not in Grafana

**Comment by hrolofs** [comment]
the same: grafana/grafana-enterprise:latest (11.1.0)

every flux query where i use v.timeRangeStart, v.timeRangeStop for the time range i got this error: cannot query an empty range (start: 1970-01-01T00:00:00Z, stop: 1970-01-01T00:00:00Z)

downgrade to 11.0.1 and it works fine.

**Comment by ilbarone87** [comment]
I think this is fixed in here https://github.com/grafana/grafana/pull/89347. Will be available with next release

**Comment by xbb** [comment]
In the meanwhile, I think you can use `${__from:date}` and `${__to:date}` like this

```
range(start: ${__from:date}, stop: ${__to:date})
```

**Comment by tommetje** [comment]
> In the meanwhile, I think you can use `${__from:date}` and `${__to:date}` like this
> 
> ```
> range(start: ${__from:date}, stop: ${__to:date})
> ```

This works! Awesome, many thanks!

**Comment by tonypowa** [comment]
>I think this is fixed in here https://github.com/grafana/grafana/pull/89347. Will be available with next release

I'm closing the issue as per this comment
