### ISSUE TITLE
Azure Monitor support for basic log query

### ISSUE THREAD

**Issue by lombardialess** [grafana/grafana#89818]
I'm trying to query the table ContainerLogV2 that is set as a basic log table and I have this message:

request failed, status: 400 Bad Request, body: {"error":{"message":"The request had some invalid properties","code":"BadArgumentError","correlationId":"52d141a8-e45b-4d81-b4c0-ea050af6bdec","innererror":{"code":"UnsupportedApiQueryValidationError","message":"Query of Basic Logs table is not supported with the API 'https://api.loganalytics.io/v1/workspaces/{workspaceId}/query'.\nYou can use 'https://api.loganalytics.io/v1/workspaces/{workspaceId}/search' instead.\nTo learn more on queries on Basic Logs table, read here: https://aka.ms/basicLogsQueryAPI."}}}

I think this is because Grafana is not supporting basic log tables but this is very useful because basic log tables permit to have cost optimized data on Log Analytics

**Comment by kayodeprinceMS** [comment]
Azure Monitor Basic Logs support for version 11.1+
https://github.com/grafana/grafana/pull/88025

Recommend starting with Explore for evaluating feature

**Comment by aangelisc** [comment]
Hi @lombardialess, as @kayodeprinceMS mentioned this is available in Grafana 11.1.0+. I'm going to close out this issue but if you have any more problems please let us know 😊

**Comment by SwordreamLj** [comment]
@aangelisc I find the issue still exist when Data Source is Azure China. Can you help check if the issue is fixed for Azure China?
I use Grafana version 12.3.1

**Comment by aangelisc** [comment]
Hi @SwordreamLj, can you check if you experience the same issue on Grafana 12.4.1? If you do, please share the Grafana server logs related to any error you see. Unfortunately, I cannot directly test this functionality against Azure China.

**Comment by mkozikowsk** [comment]
I also cannot use the basic logs table for alerts. Using Grafana v12.3.3. 

<img width="997" height="140" alt="Image" src="https://github.com/user-attachments/assets/d7032d62-026c-4801-bf19-e389c8c2415d" />
