### ISSUE TITLE
[Bug] in search string

### ISSUE THREAD

**Issue by ihard** [grafana/grafana#8981]
OS Mac 10.12.5
Browser Chrome, Safari
Grafana 4.4.2
![2017-08-02_19-39-48](https://user-images.githubusercontent.com/3078342/28920725-b39c422e-785b-11e7-8814-7b17e9b0a6a4.png)
on click starred or tag - search string closed (in prevous version select starred or tag dashboard)

**Comment by torkelo** [comment]
thanks for reporting this!
