### ISSUE TITLE
[Bug]: Color picker stops working if open when the dashboard auto refreshes.

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#8982]
For a dashboard with auto refresh turned on, if the color picker that is used for the legend in the Graph panel is open when the dashboard refreshes then it stops receiving clicks.

![](https://cdn-standard3.discourse.org/uploads/grafana/original/2X/a/af6a07a8f95d318f8441b679474ab4d742c97463.gif)

Grafana 4.4.2. Probably affects all browsers and OSes. 

No JavaScript errors in the console.

ref: https://community.grafana.com/t/the-color-does-not-change-after-updating-the-data/2114

**Comment by torkelo** [comment]
this seeems to be fixed
