### ISSUE TITLE
Auth: LDAP failing TLS handshake

### ISSUE THREAD

**Issue by davidhemp** [grafana/grafana#89828]
### What happened?

Upgraded to grafana-enterprise-11.1.0-1.x86_64 without any other changes and now LDAP auth fails to complete TLS handshake. In logs I see,

```
Jun 27 11:02:59 grafana.local grafana[298528]: logger=context userId=0 orgId=0 uname= t=2024-06-27T11:02:59.812750168+01:00 level=info msg=Unauthorized error="[password-auth.failed] failed to authenticate identity: LDAP Result Code 200 \"Network Error\": TLS handshake failed (remote error: tls: handshake failure)\n[password-auth.invalid] invalid password" remote_addr=192.168.0.2 traceID=
Jun 27 11:02:59 grafana.local grafana[298528]: logger=context userId=0 orgId=0 uname= t=2024-06-27T11:02:59.812794381+01:00 level=info msg="Request Completed" method=POST path=/login status=401 remote_addr=192.168.0.2 time_ms=17 duration=17.567769ms size=107 referer=https://grafana.local:8080/login handler=/login status_source=server
```

This prevents users from logging in although already authenticated users are unaffected. 

### What did you expect to happen?

Grafana should use LDAP to authenticate usernames and passwords

### Did this work before?

This worked in grafana-enterprise-11.0.0-1.x86_64 and just rolling back the update resolved this issue. 

### How do we reproduce it?

Using 11.1 with ldap auth with use_ssl and start_tls.

### Environment (with versions)?

Grafana: grafana-enterprise-11.1.0-1.x86_64 
OS: RHEL 8.10
Browser: Google Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by qbazak** [comment]
+1 from me on latest (11.1.0) docker version. Same story on 11.0.1. Downgrading to 11.0.0 helped.

**Comment by Cynnexis** [comment]
+1 I have a Grafana Docker container, and it works fine in `grafana/grafana:11.0.0` but not in `grafana/grafana:11.1.0`.

**Comment by vaz-ar** [comment]
Same issue using the RPMs, it works on 11.0.0 but not after

**Comment by bas-jpro** [comment]
I have Grafana (community) with the RPM and hit this issue, but I have it working with use_ssl = false and use_tls = true

Which makes some sense as use_ssl suggests it uses LDAPS. Previously I had both true and that worked up to 11.1. 

I haven't confirmed I'm actually getting a TLS connection with 11.1

**Comment by vaz-ar** [comment]
This is linked to the change of go version used to build grafana (1.22):

~~~md
[crypto/tls](https://tip.golang.org/pkg/crypto/tls/)

    [ConnectionState.ExportKeyingMaterial](https://tip.golang.org/pkg/crypto/tls#ConnectionState.ExportKeyingMaterial) will now return an error unless TLS 1.3 is in use, or the extended_master_secret extension is supported by both the server and client. crypto/tls has supported this extension since Go 1.20. This can be disabled with the tlsunsafeekm=1 GODEBUG setting.

    By default, the minimum version offered by crypto/tls servers is now TLS 1.2 if not specified with [config.MinimumVersion](https://tip.golang.org/pkg/crypto/tls#Config.MinimumVersion), matching the behavior of crypto/tls clients. This change can be reverted with the tls10server=1 GODEBUG setting.

    By default, cipher suites without ECDHE support are no longer offered by either clients or servers during pre-TLS 1.3 handshakes. This change can be reverted with the tlsrsakex=1 GODEBUG setting.
~~~
From https://tip.golang.org/doc/go1.22#minor_library_changes

Setting `GODEBUG="tlsrsakex=1"` in the environment used by grafana will make it work again (tested only with grafana installed via RPMs).

**Comment by bas-jpro** [comment]
Thanks, that fix works for me - I was not getting a TLS connection but my LDAP allows plain text login so it appeared to work.

**Comment by davidhemp** [comment]
I added ```GODEBUG="tlsrsakex=1"``` to the end of /etc/sysconfig/grafana-server and upgraded to v11.1.0-1. Everything seems to be working now. I guess the TLS issues needs an update to Grafana but we have a work around that is reported working so I'm going to close this.

**Comment by nathanlcarlson** [comment]
A more permanent fix is in the works? I'm using a docker container and adding this to environment didn't seem to help. Any tips for having this workaround work in a docker container?

**Comment by mgyongyosi** [comment]
It seems that [RSA only (non-ECDHE) key exchanges have been removed for security reasons](https://github.com/golang/go/issues/63413). As the changelog says, `By default, cipher suites without ECDHE support are no longer offered by either clients or servers during pre-TLS 1.3 handshakes.`, the emphasize is on the _no longer offered_ during the handshake, so (IIUC) there are two options:
1. Try to update the supported cipher suites and/or min TLS version on your LDAP server.
2. Specify the used cipher suite(s) used by the LDAP server explicitly in the `ldap.toml` using the `tls_ciphers` configuration.
