### ISSUE TITLE
Grafana displays "Failed to fetch" popup error message, caused by a failed `api/frontend-metrics` call

### ISSUE THREAD

**Issue by kamilkloch** [grafana/grafana#89820]
### What happened?

Browsing through dashboards results in a popup error message "Failed to fetch". See attached screenshot.
![Screenshot from 2024-06-27 11-30-17](https://github.com/grafana/grafana/assets/807154/8e24238d-1444-457e-92a8-511c5f217209)

The source of the error is the following HTTP call:
```
curl 'http://ls15:3000/api/frontend-metrics' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'Referer: http://ls15:3000/d/logs/logs?orgId=1&refresh=5s' \
  -H 'x-grafana-org-id: 1' \
  -H 'x-grafana-device-id: 01eee8bdb5da92f62d94450677b8e21a' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  --data-raw '{"events":[{"name":"frontend_plugins_preload_ms","value":0},{"name":"frontend_app_init_ms","value":15.800000011920929},{"name":"frontend_boot_load_time_seconds","value":0.568},{"name":"frontend_boot_js_done_time_seconds","value":0.508},{"name":"frontend_boot_css_time_seconds","value":0.109},{"name":"initDashboard_ms","value":31.400000005960464},{"name":"initDashboard_ms","value":99.90000000596046},{"name":"initDashboard_ms","value":58.20000001788139},{"name":"initDashboard_ms","value":56.599999994039536},{"name":"initDashboard_ms","value":66.40000000596046},{"name":"initDashboard_ms","value":23.69999998807907}]}'
```

Call stack:
![Screenshot from 2024-06-27 11-39-47](https://github.com/grafana/grafana/assets/807154/c7387bd7-f615-4274-a48c-049357a3b7d4)

### What did you expect to happen?

No error.

### Did this work before?

We did not encounter the error with Grafana 10.

### How do we reproduce it?

Launch Grafana with dasboards, browse through the dashboards. 

### Environment (with versions)?

Grafana:
```json
{
  "commit": "83b9528bce85cf9371320f6d6e450916156da3f6",
  "database": "ok",
  "version": "11.0.0"
}
```
OS: Ubuntu 24
Browser: Chrome

### Grafana platform?

None

**Comment by Clarity-89** [comment]
This was fixed in https://github.com/grafana/grafana/pull/89379, so you'd update your Grafana to v 11.0.1.
