### ISSUE TITLE
Grafana 11.1: when adding new datasource, long loading time 

### ISSUE THREAD

**Issue by farmboy-dev** [grafana/grafana#89866]
### What happened?

Hello Grafana team and community

I've upgraded Grafana 10.1 to 11.1, everything is working well so far except Add new data source.
My Grafana is in the private network, so can't connect to 34.120.177.193 (grafana.com), and I keep getting Proxy request timed out messages in logs. 
I have never had this issue with Grafana 10.1,

Thank you!

### What did you expect to happen?

-

### Did this work before?

I have never had this issue with Grafana 10.1,

### How do we reproduce it?

1. Click 'Add new data source' in the private network
2.
3.

### Environment (with versions)?

Grafana: 11.1 (docker image)
OS:
Browser:

### Grafana platform?

Docker

### Datasource(s)?

All

**Comment by tonypowa** [comment]
Hello @farmboy-dev 

Could you provide a snippet of the Grafana log showing the exact error message (including any stack traces or related errors) when you try to add a new data source?

Are there any proxy settings that you've configured within Grafana, or environment variables related to networking that could be relevant to this issue?

**Comment by HolgerHees** [comment]
Jul 28 12:40:56 marvin grafana[4816]: logger=plugin.signature.key_retriever t=2024-07-28T12:40:56.440534439+02:00 level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.com/api/plugins/ci/keys\": dial tcp 34.120.177.193:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"
Jul 28 12:40:56 marvin grafana[4816]: logger=plugin.angulardetectorsprovider.dynamic t=2024-07-28T12:40:56.441619194+02:00 level=error msg="Error while updating detectors" error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": dial tcp 34.120.177.193:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"

**Comment by tolzhabayev** [comment]
@HolgerHees 

```
Jul 28 12:40:56 marvin grafana[4816]: logger=plugin.signature.key_retriever t=2024-07-28T12:40:56.440534439+02:00 level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.com/api/plugins/ci/keys\": dial tcp 34.120.177.193:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"
Jul 28 12:40:56 marvin grafana[4816]: logger=plugin.angulardetectorsprovider.dynamic t=2024-07-28T12:40:56.441619194+02:00 level=error msg="Error while updating detectors" error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": dial tcp 34.120.177.193:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"
```

The first one is related to us checking for new keys, but if your env. is airgapped you can set `[plugins]. public_key_retrieval_disabled` to `true` ([Link](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#public_key_retrieval_disabled))

The second one will start respecting `check_for_plugin_updates = false` in 11.2 ([PR](https://github.com/grafana/grafana/pull/91194))

But regardless of them both it should not impact your experience of adding new datasources - can you provide more info there (maybe XHR file (cleaned up)) or a screen recording (without any sensitive info) or a network tab screenshot in dev tools that shows what is being slower when adding a new datasource?

**Comment by HolgerHees** [comment]
@tolzhabayev sorry, was my mistake. It has nothing to do with adding new data source.

I just saw the comment about network traffic in an isolated environment.

but anyway, your comment helps me to understand the root cause.

so I added the missing key "public_key_retrieval_disabled" and wait for the release of 11.2
