### ISSUE TITLE
grafana/grafana-oss:latest points to 11.0.1 instead of 11.1.0

### ISSUE THREAD

**Issue by mbs-c** [grafana/grafana#89873]
I just pulled the docker image grafana/grafana-oss:latest, expecting to get the latest release (11.1.0). However, the tag incorrectly points to 11.0.1 at the moment.

**What is the chore?**: Fix the latest and latest-ubuntu tags

**Comment by tolzhabayev** [comment]
@grafana/grafana-release-guild please take a look

**Comment by kminehart** [comment]
@mbs-c You should use the `grafana/grafana` repo and not `grafana/grafana-oss`.

**Comment by baldm0mma** [comment]
Looks like `grafana/grafana` is pointing to `11.0.0` instead of `11.1.0` as well. I'm working on a fix.

**Comment by mbs-c** [comment]
@kminehart OK, I see that the docker images are identical, so I'll use the other name in the future.

Either way, the release automation seems to be broken. Currently, the situation for `grafana/grafana:latest` is even more inconsistent, since `latest` points to `11.1.0` (published two days later - maybe a manual fix?), while `latest-ubuntu` still points to `11.0.1-ubuntu`.

**Comment by kminehart** [comment]
Thanks for pointing that out. We're working on improving that automation in the near future. Currently every release is marked as latest so if they're not done in the correct order then whatever was released last becomes `latest`.

**Comment by baldm0mma** [comment]
The builds for `amd64`, `arm64`, and `armv7` based on the `latest` tag are now pointing to the correct images/versions.
```
$ docker manifest inspect --verbose grafana/grafana:latest | grep '"Ref":'
		"Ref": "docker.io/grafana/grafana-image-tags:11.1.0-amd64",
		"Ref": "docker.io/grafana/grafana-image-tags:11.1.0-arm64",
		"Ref": "docker.io/grafana/grafana-image-tags:11.1.0-armv7",
```
In the mean time, we are working on automating this in a way where this won't be an issue in the future.

**Comment by NGPixel** [comment]
> @mbs-c You should use the `grafana/grafana` repo and not `grafana/grafana-oss`.

Your [own documentation](https://grafana.com/grafana/download?platform=docker&edition=oss) states that `grafana/grafana-oss` should be used...

`grafana/grafana-oss:latest` is still pointing to 11.0.1. Can this be fixed as well? You can't expect people to use `grafana/grafana` when the docs says otherwise.
