### ISSUE TITLE
Grafana 11 Dashboard: NOT FOUND error

### ISSUE THREAD

**Issue by thanissi** [grafana/grafana#89871]
### What happened?

When tried to open any dashboard with the following conditions
1) GF_UNIFIED_ALERTING_ENABLED = false; and
2) At least one folder has been created

**Not found** error would appear on the top right-hand corner

![Screenshot 2024-06-28 at 2 20 12 PM](https://github.com/grafana/grafana/assets/22128473/462975d7-d9d4-4708-96bf-cbc69a112987)

![Screenshot 2024-06-28 at 2 23 46 PM](https://github.com/grafana/grafana/assets/22128473/e1a40022-5fc0-4456-a894-7f144ed0a72f)

### What did you expect to happen?

Given unified alerting has been disabled, when loading a dashboard, it should not try to make this call:

api/prometheus/grafana/api/v1/rules?dashboard_uid=xxxxxxxx and getting 404 error.

### Did this work before?

Yes in version 10.x.x

### How do we reproduce it?

1. Run Grafana docker version 10.x.x
2. Set GF_UNIFIED_ALERTING_ENABLED = false
3. Create a dummy folder
4. Launch any dashboard

### Is the bug inside a dashboard panel?

It appears in the dashboard - not panel-specific

### Environment (with versions)?

Grafana: 11.0.1 and 11.1.0
OS: Docker
Browser: Chrome 126.0.6478.126

### Grafana platform?

Docker

### Datasource(s)?

default Grafana Random Walk

**Comment by thanissi** [comment]
Seems similar to https://github.com/grafana/grafana/issues/89884

**Comment by ecktom** [comment]
See https://github.com/grafana/grafana/issues/87891

**Comment by Clarity-89** [comment]
Fixed in https://github.com/grafana/grafana/pull/89361.
