### ISSUE TITLE
[Feature request] Dismiss Shortcuts modal using keyboard

### ISSUE THREAD

**Issue by j-white** [grafana/grafana#8988]
The "Shortcuts" modal window can be opened by pressing "Shift+?", however there doesn't appear to be any way to close the modal without using the mouse.

Personally, I would expect the "Esc" key to dismiss the modal, but instead it does nothing. (Unless there is already some settings window open behind the modal, in which case that is closed.)

Tested using Chrome 60.0 with Grafana 4.4.2.

**Comment by j-white** [comment]
As a temporary workaround, `Ctrl+S, Tab, Tab, Enter` seems to do the trick :)

**Comment by torkelo** [comment]
this used to work, but seems broken. Thanks for reporting this!
