### ISSUE TITLE
Grafana 11.1: Create folder with HTTP API will incur a "NOT FOUND" notice on GUI everywhere

### ISSUE THREAD

**Issue by Vonng** [grafana/grafana#89884]
### What happened?

My workflow involves the use of Python scripts to load Grafana dashboards via the HTTP API. This process has been reliable and efficient until the recent upgrade to Grafana version 11.1.

The GUI prompts a "NOT FOUND" error everywhere:

<img width="448" alt="image" src="https://github.com/grafana/grafana/assets/8587410/0e68a750-4371-4ce9-89f9-30548f604a2a">

The failed HTTP request is:

<img width="902" alt="image" src="https://github.com/grafana/grafana/assets/8587410/1dad46cb-9209-4b8e-af7a-609db407767b">

### What did you expect to happen?

If you create the folder with GUI, it works as usual.

But when you create the folder with API, the simplest form

```
post('/api/folders', {"title": "abc"})
```

The error occurs.

Starting from a fresh new Grafana instance (even without any datasource) will incur this issue.

### Did this work before?

Yes

### How do we reproduce it?

1. Launch a fresh Grafana instance
2. Invoke the `PUT /api/folders` to create a Folder through HTTP API

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.1
OS: RockyLinux 8.9
Browser: Chrome & Safari

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Not specific to a datasource

**Comment by ecktom** [comment]
See https://github.com/grafana/grafana/issues/87891

**Comment by Clarity-89** [comment]
Fixed in https://github.com/grafana/grafana/pull/89361.
