### ISSUE TITLE
fav16.png is 32x32 pixels in size...

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#8989]
https://raw.githubusercontent.com/grafana/grafana/master/public/img/fav16.png is
`fav16.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced`

**Comment by torkelo** [comment]
ok, need to rename the file to fav32 :)

**Comment by cron2** [comment]
hi,

On Sun, Aug 06, 2017 at 06:03:50AM +0000, Torkel Ödegaard wrote:
> ok, need to rename the file to fav32 :) 

I'm actually looking for a 16x16 icon...

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de
