### ISSUE TITLE
Build from source sqlite3 error

### ISSUE THREAD

**Issue by wmpedersen** [grafana/grafana#8992]
I'm trying to build from source to ARM using the setup instructions and the "go build.go setup" fails at creating the database with "pkg/services/sqlstore/shared.go:45: undefined: sqlite3.ErrLocked" 

I've been looking around and haven't found any information regarding this but obviously I don't have write access to the database. I've installed sqlite3 using the package manager, but have not set up a database because I thought the setup would take care of that. 

Is there some database configuration or configuration in the source that I'm missing before installing?

**Comment by torkelo** [comment]
what version of Go did you use?

**Comment by wmpedersen** [comment]
I used go 1.8.3

**Comment by torkelo** [comment]
strange, it's a compile error. Did not get that when I last tried an ARM build, and we are not seeing it on any of our build servers.  

There is no platform flags for that error constant so not sure why it's says undefined for you.

**Comment by daniellee** [comment]
@wmpedersen Have you seen this: https://github.com/fg2it/grafana-on-raspberry

**Comment by lynnsir-102** [comment]
in my go_env
“CGO_ENABLED=1”
But I have the same problem
