### ISSUE TITLE
CSS Style changes made in v 11.1.0?

### ISSUE THREAD

**Issue by github-ps1304** [grafana/grafana#89938]
### What happened?

I manipulated the row in a dashboard with an external plugin called "Boom Theme" with the the following code:

![image](https://github.com/grafana/grafana/assets/79707394/adb0e968-a564-4179-807d-f11e387937c6)

this isn't working anymore since updating to version 11.1.0

### What did you expect to happen?

row should be transparent

### Did this work before?

up to version 11.0

### How do we reproduce it?

1. install Boom Theme plugin
2. add background picture
3. add code from screenshot above

### Environment (with versions)?

Grafana: 11.1.0
OS: Debian 12
Browser: Safari

### Grafana platform?

Other

**Comment by github-ps1304** [comment]
I managed to fix it with the Grafana Text Visualization and the below code:
`<style type="text/css">
   .dashboard-row--collapsed{
    background-color: rgba(0,0,0,0);
}
    /* You can also use more advanced CSS for background patterns etc. */
  }
</style>`

**Comment by Clarity-89** [comment]
Hi, we have moved the legacy SCSS styles to Emotion (CSS-in-JS), so customising styles via CSS classes is not possible anymore and this was never a supported feature. The only way to achieve that now is to modify the source code for the `DashboardRow` component.

**Comment by github-ps1304** [comment]
@Clarity-89 Tx for the clarification - any chance to made the row transparent in collapsed mode? like it is when the row is expanded. I guess it would much nicer for many dashboards using rows and background to have the row transparent (collapsed+expanded)

kind regards Peter

**Comment by Clarity-89** [comment]
Looking at the [code](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/DashboardRow/DashboardRow.tsx#L202) of the `DashboardRow` component, it seems like the only way to achieve that is to modify the `theme.components.panel.background` variable as there's no prop for setting background to transparent, however that'll also mean modifying the source code.
