### ISSUE TITLE
Bug: alerting "pending since xxxx / ok since xxx" times not correct for newly created alert

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#8996]
observed on GrafanaLabs monitoring instance. Grafana v4.4.1 (commit: 6a9f8ca)

just added a new alert (seconds ago) and in the alert list it shows up like pending for many hours:
![pending-huh](https://user-images.githubusercontent.com/20774/29018462-6bf37a8e-7b5b-11e7-9b7a-b45acb433e66.png)

then it runs and shows up like this:

![conn2](https://user-images.githubusercontent.com/20774/29018513-ab80a19a-7b5b-11e7-8519-d59f4e6bf59f.png)

**Comment by daniellee** [comment]
Grafana Monitor server clock is set to EDT which is four hours after UTC. Think that Grafana should be able to handle this though.

**Comment by daniellee** [comment]
The bug is due to this line: 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/sqlstore.go#L149

which configures sqlite to save datetimes as local rather than UTC. But I'm unsure of the consequences of changing this. More research required.

**Comment by torkelo** [comment]
Is there an option to save in UTC, I tried every option to get sqlite to save in UTC but failed last time, maybe missed an option, or it had side effects, can't remember

**Comment by daniellee** [comment]
When I removed the Local parameter from the SQLite connection string then dates were saved in UTC (on my machine with timezone UTC+2). Also wondering about the side effects.
