### ISSUE TITLE
new dashboard -> create new charts -> alerts -> "save as" -> alerts not saved.

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#8997]
Grafana v4.4.1 (commit: 6a9f8ca)

create new dashboard
add charts
add alerting config to charts
hit "save as" -> save it

when navigating away and then coming back, the alerting rules are no longer there

however, when creating the dashboard with charts, then saving, then creating alerting rule and saving again, then it is properly saved.

**Comment by torkelo** [comment]
yea, save as always removes alert rules so you do not get alert rule duplicates. 

Is an issue with new dashboards though. Think we can fix this by not removing alert rules if the dashboard is unsaved.
