### ISSUE TITLE
[v11.1.0 + Firefox] Tooltips display scrollbar when there's not enough content to scroll

### ISSUE THREAD

**Issue by Max-E-Million** [grafana/grafana#89975]
### What happened?

After upgrading from 11.0 to 11.1 all of my tooltips suddenly show a scroll bar, even if there is not enough content.
This **only happens with the Firefox browser**, browsers like Edge or Chrome do not seem to have this problem.

There even are instances like this where there's scroolbars **for every** line which looks really ugly:

![grafik](https://github.com/grafana/grafana/assets/55145127/4a299d2d-1568-4486-9b13-917d32d55dfb)

Dude in [this issue](https://github.com/grafana/grafana/issues/89834) basically had the same problem but I don't understand the response - this has nothing to do with tooltip height, at least for me playing around with that value didn't change anything.

### What did you expect to happen?

Viewing tooltips in Firefox behaves the same as in other browsers -> no useless scrollbars in tooltips.

### Did this work before?

Yes, 11.0 didn't have this issue.

### How do we reproduce it?

1. Open Grafana in Firefox
2. Create any panel with one type of data in it
3. Hover over data
4. Observe tooltip and the scroll bar beside it

### Is the bug inside a dashboard panel?

Yes, in every single one.

### Environment (with versions)?

Grafana v11.1.0 (5b85c4c2fc)
OS: Windows 10 22H2
Browser: Firefox 127.0.2

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Prometheus

**Comment by salavessa** [comment]
Just to add that this also happens in the latest version of Chrome (_126.0.6478.127 (Official Build) (64-bit)_) for windows (didn't check other OS's).
![grafana-11 1 0-tooltip-scroll-visible-chrome](https://github.com/grafana/grafana/assets/15344273/e0221758-ce18-485c-ba39-29e46cdc236a)

**Comment by daFlo** [comment]
+1

**Comment by jtfrandsen** [comment]
+1

**Comment by abanichev** [comment]
Same on Vivaldi browser (version 6.8.3381.46, both macOS and Windows 11)

**Comment by macruch** [comment]
same on Opera and Edge
I cannot reach the scrollbar when "max hight" is set. Is the nature of mouse over tooltip. 
I did a rollback to 11.0

**Comment by nicholas-a-guerra** [comment]
Same issue mentioned as everyone above on latest Chrome and Safari on MacOS. Weird scroll bars and sizing is way bigger. Scrollbar wasn't needed before because size was reasonable. Now scrollbar is needed because text is much larger but there's no way to use it. The mouse can't ever enter the tooltip because it moves with the mouse. Seems unusable for now. Also having to revert back to 11.0.1 until this is looked into.

**Comment by adela-almasan** [comment]
Fixed by https://github.com/grafana/grafana/pull/91547
