### ISSUE TITLE
Cloudwatch: Preconfigured dashboard query returns error when mode is Metric Search Code

### ISSUE THREAD

**Issue by idastambuk** [grafana/grafana#90000]
We received a bug report  [here](https://github.com/grafana/support-escalations/issues/11270) regarding two panels in one of our preconfigured dashboards erroring out. The dasboard in question is Amazon Cloudwatch Logs, that can be imported form the Dashboards tab when configuring the datasource. 

After investigating, this is what happens for the first two panels `Incoming log events [count/sec]` and `Incoming bytes [bytes/sec]`:

- They don't have defined `queryMode`, `metricQueryType` and `metricEditorMode`. This defaults to Search -> Code. This means that they default to sending the Expression field, e.g. `REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period`
- This query, wherever, for some reason returns a `runtime.boundsError` from AWS
- This doesn't happen when you switch manually to Builder mode, that contains seemingly the same query. 

Expected behavior here is that the preconfigured dashboard panel can have both Builder and Code mode queries filled out, but both should work the same, and not have one error out.

**Comment by DirkRusche-Otto** [comment]
I'm not quiet sure, if I see the same error.
Just get back to me if not and I'll go ahead and open a new issue.

We're using this query:
![Screenshot 2024-07-04 at 07 30 45](https://github.com/grafana/grafana/assets/146933630/ba9aba69-9d8a-43cb-8102-43811e6bb05b)

But with version `11.1.0` we're seeing this error:
![Screenshot 2024-07-04 at 07 30 51](https://github.com/grafana/grafana/assets/146933630/4496df78-64a1-4c22-b9de-b060d39d5536)

In the logs I can also see this: `logger=tsdb.cloudwatch endpoint=queryData pluginId=cloudwatch dsName=cloudwatch-live dsUID=<REDACTED> uname= t=2024-07-04T05:30:25.515805061Z level=error msg="Execute Get Metric Data Query Panic" error="runtime error: index out of range [1] with length 1" stack=[]`

When I change from code to builder it works perfectly fine:
![Screenshot 2024-07-04 at 07 31 09](https://github.com/grafana/grafana/assets/146933630/ad7f69cb-1d27-404f-8f4d-81bf8fa4a881)

---

Rolling back to `11.0.1` fixed this error for us.

**Comment by idastambuk** [comment]
Hi @DirkRusche-Otto, it does look like the same problem, thanks for the additional info. We will try to get to this soon
