### ISSUE TITLE
Switching home dashboard in a tenant org makes it visible to all tenants

### ISSUE THREAD

**Issue by phakudi** [grafana/grafana#9001]
1) Assume a Grafana deployment with multiple orgs (Org1, Org2 say) and users mapped to admin and other roles on both these orgs.
2) As an admin of  Org1 navigate to Org Preferences and switch your Home dashboard to one of your existing dashboards.
3) Login as a non-admin user of Org2 and click on Dashboards drop down. You will see the new home dashboard chosen by the Org1 admin under your org.

This is a data security issue.

**Comment by torkelo** [comment]
what OS & Browser are you using? You mention it appears in dashboard search, can you open the dashboard as well?

**Comment by torkelo** [comment]
could not replicate this in chrome on windows/linux/mac. 

Sounds like a IE cache issue, we fixed an issue that could cause dashboard search results to be cached in the browser.  Fixed in nightly build:
https://grafana.com/grafana/download/5.0.0-8579pre1
