### ISSUE TITLE
Funnel plugin shows drop numbers as the wrong percentage

### ISSUE THREAD

**Issue by emrys90** [grafana/grafana#90019]
### What happened?

The actual drop is the inverse, so 13.37% is the drop. This is because the drop is from 187 to 162, which is a 13.37% decrease.
![funnel drop](https://github.com/grafana/grafana/assets/20632855/c2237500-8f46-4261-a61d-f9cf0682b5b4)

### What did you expect to happen?

For the percentage drop display to match how many actually dropped, or for dropped text to be renamed to reflect what is actually being displayed, which is the percentage that advanced to the next step. 

### Did this work before?

Unknown, I'm new to Grafana

### How do we reproduce it?

1. Create a funnel
2. Look at the drop numbers and percentage

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by marefr** [comment]
Please open an issue at https://github.com/mckn/mckn-funnel-panel/issues. Thanks
