### ISSUE TITLE
[Bug] View JSON is not working in Chromium 60+

### ISSUE THREAD

**Issue by Bonko** [grafana/grafana#9002]
Please include this information:
- What Grafana version are you using?
4.4.3
- What datasource are you using?
prometheus
- What OS are you running grafana on?
Debian Jessie (I am using the official Docker image)
- What did you do?
I clicked on `Settings` -> `View JSON` in several dashboards
- What was the expected result?
See the JSON
- What happened instead?
an emtpy site (about:blank) opened.
When inspected with Chrome Developer Tools, this error popped up in console:
```
Not allowed to navigate top frame to data URL: data:application/json;charset=utf-8...
```
 
While searching for this issue, it seems this is a change introduced in Chromium 60 to not support data urls in top-frame navigations anymore:

https://stackoverflow.com/questions/45493234/jspdf-not-allowed-to-navigate-top-frame-to-data-url
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

**Comment by Bonko** [comment]
I forgot to mention: it works in Firefox 54.0.1

**Comment by daniellee** [comment]
Confirmed. Guess there will have to be a 4.4.4 release :roll_eyes: (I just released 4.3.0 today)

**Comment by Bonko** [comment]
Thanks for the quick fix. Do you have an idea when the next version will be released?

**Comment by torkelo** [comment]
no, maybe next week

**Comment by pdoan017** [comment]
The same error is appearing when clicked on `Share dashboard` -> `Export` -> `View JSON`

**Comment by daniellee** [comment]
@pdoan017 Confirmed. Thanks for reporting this.

**Comment by rehevkor5** [comment]
Does anyone know a workaround for this issue?

**Comment by torkelo** [comment]
upgrade grafana
