### ISSUE TITLE
Delay in keyboard shortcuts ( v11.0 or newer only)

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#90020]
### What happened?

Grafana version:  11.1.0  (release)

I frequently use "e" keyboard shortcut to edit panels,  I noticed I frequently was editing the wrong panel and discovered that there seems to be a decent delay between the mouse over and what panel you edit (via pressing E on keyboard).  This was not the case until I upgraded to version Grafana v11.

I can reproduce this on Chrome (v125.0.6422.176)  and on firefox (v127.0)  (on windows 11 , in my case).
see video screen cap below, please.  
(In this video my mouse will be over the panel "m4500 RX BW" , so that is what should come up to be edited when i press "e" )

Please let me know how i can further help to debug this.  

thanks
![mouseOverKeyboard](https://github.com/grafana/grafana/assets/60830628/60342d5f-307f-4ff5-a18a-ad9a7882b06b)

### What did you expect to happen?

when you press a keyboard shortcut ( "e" in this case) , it should apply to the panel that your mouse is over currently.

### Did this work before?

yes, this issue did not occur on 10.4.3.  (although i have not rolled back to confirm- but i edit panels all-day, everyday, so i would have noticed).

### How do we reproduce it?

1. briskly move mouse across a few panels , then press "e" on keyboard,  and see which panel you end up editing.

### Environment (with versions)?

Grafana: 11.1.0  (release)
OS: Debian 9 for grafana,  win11 for browser
Browser:  Chrome (v125.0.6422.176)  and on firefox (v127.0)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Graphite

**Comment by tonypowa** [comment]
Hello @bob454522 

Thank you for creating this issue

**Comment by bob454522** [comment]
> Hello @bob454522
> 
> Thank you for creating this issue
> 
> I can't reproduce the issue in Grafana v11.2.0-73451 // win10 // Firefox 128.0.2
> 
>     * Have you been able to replicate this issue on another machine or browser session?
> 
>     * Are there any errors that show up in the browser's developer console when you press 'e' to edit a panel?

thanks for the reply,  yes i have been able to re-produce this on:
1- 2x browsers on my main PC (This occurs both with Firefox and chrome - i did mention this, with versions, in my original post).

2- an entirely separate PC (my laptop - win11 22H2 - firefox and chrome ).

note- still is occurring on 11.1.3.  (occurs even on a test dashboard, with very few panel dashboard).
i know this was not occurring on earlier versions of grafana (cant say exactly when it started but i THINK it was around v10.latest -> v11 update)

thanks, and please let me know what additional information I can provide to help.

screen cap of 2nd PC below ( im pressing E  on the keyboard to edit the panel,  but in the last example of the video i mouse over the green line panel,  and wait 2 seconds before pressing E and it edits the correct panel) -  This may not seem like a big deal but on larger dashboards with many panels it becomes a larger issue especially when I start to edit a dashboard only to realize it's not the one I pressed E on):

i didnt make a full video capture,  But on my second PC , i was also able to reproduce the issue when in a private browsing session thus the two Firefox extensions I run were disabled (i only run uBlock origin, always disabled on my grafana domain,  and 1password).

The grafana server is local to my network here.

![mouseOverKeyboardgrafana](https://github.com/user-attachments/assets/6b4eb400-ddf3-49c7-9056-3fdc6e9bae62)

![image](https://github.com/user-attachments/assets/62ff35ad-7a41-4f27-92ba-e06def861863)

**Comment by tonypowa** [comment]
moving issue to frontend squad. please reroute if the issue does not belong to your squad. thank you!

**Comment by tskarhed** [comment]
This is a known issue, we are working on how to resolve it properly. https://github.com/grafana/scenes/pull/867
