### ISSUE TITLE
Display Event Name as Event Name and not as "message"

### ISSUE THREAD

**Issue by ie-pham** [grafana/grafana#90027]
When doing a trace by id search, the Tempo response schema for events look like this:

```
 "events": [
                                {
                                    "timeUnixNano": "1719510778325485504",
                                    "name": "jennie-test",
                                    "attributes": [
                                        {
                                            "key": "k6.jaYhGVXoamLC1cT",
                                            "value": {
                                                "stringValue": "zHXI9PNGzQ1fhBSujY7QO4WUH7Sdz5"
                                            }
                                        }
                                    ]
                                },
],

```

But the result transformer code in Grafana transform it into something like this. (And events are called logs...?)
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/resultTransformer.ts
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/trace.ts 
```
     {
                                        "timestamp": 1719510778325.4856,
                                        "fields": [
                                            {
                                                "value": "jennie-test",
                                                "key": "message"
                                            },
                                            {
                                                "value": "zHXI9PNGzQ1fhBSujY7QO4WUH7Sdz5",
                                                "key": "k6.jaYhGVXoamLC1cT"
                                            },
                                        ]
                                    },
```

Event name should labeled as event name. And if there is another attribute with key "name", it should be displayed differently from event name. 

Not exactly the same response info as the above but the screenshot shows "message" when it is labeled name in the Tempo response
![Screenshot 2024-06-21 at 10 37 21 AM](https://github.com/grafana/grafana/assets/94262131/6731957f-bb89-44af-b72f-4cd63f202895)

**Comment by 09jvilla** [comment]
Related feature request to improve how the single trace view displays an event's attributes
https://github.com/grafana/grafana/issues/90578

**Comment by ifrost** [comment]
@ie-pham / @nadinevehling: would it make sense to display the event name like this or should it be more prominent? 

| Before | After |
|--------|--------|
| **XXms:** message=eventName, attributeA=value A, attributeB=valueB | **eventName (XXms):** attributeA=value A, attributeB=valueB |
| ![Screenshot 2024-08-01 at 12 37 03](https://github.com/user-attachments/assets/1ba64fda-a916-425e-aeff-a716cc87ef2b) | ![Screenshot 2024-08-01 at 12 34 06](https://github.com/user-attachments/assets/1a9df603-db65-48db-9350-e45e3b2b6c70) |

This is based on the PR: https://github.com/grafana/grafana/pull/91382

> But the result transformer code in Grafana transform it into something like this. (And events are called logs...?)
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/resultTransformer.ts
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/trace.ts

Note: this is a frontend transformation that seems to be applied for imported/uploaded traces. The actual transformation Tempo Response to Data Frames happens [in backend](https://github.com/grafana/grafana/blob/v11.1.1/pkg/tsdb/tempo/trace_transform.go#L254). I'll also have a look if that frontend transformations needs updating.

**Comment by ifrost** [comment]
@ie-pham / @nadinevehling - here's an alternative that was suggested by @nadinevehling (adding `duration=...`). Below is the comparison of all three:

| current main | option 1 | option 2 |
|--------|--------|--------|
| ![Screenshot 2024-08-13 at 22 43 37](https://github.com/user-attachments/assets/7479ebb9-c99e-499b-b58d-1dbb04f6845f) | ![Screenshot 2024-08-13 at 22 37 16](https://github.com/user-attachments/assets/5723d4f9-56e8-4967-a637-3e592e5b0b29) |  ![Screenshot 2024-08-13 at 22 38 53](https://github.com/user-attachments/assets/1cd57dd6-1d68-4c2b-b646-71d07fd3c912) | 

Let me know which one you prefer (or if you'd like to try something else :))

**Comment by nadinevehling** [comment]
Thanks @ifrost for providing all options side-by-side! 🎉
I think option 2 is the most clear option. Curious what @ie-pham thinks too.

**Comment by 09jvilla** [comment]
Sorry dumb question but is it "duration"? I actually think its not duration but rather a discrete point in time. So "`LookupEvent` happened at 18.46ms into the start of this span" rather than "`LookupEvent` took 18.46ms". If that's the case, I think duration might be the wrong word and something more like Timestamp would be more appropriate.

**Comment by ie-pham** [comment]
> Sorry dumb question but is it "duration"? I actually think its not duration but rather a discrete point in time. So "`LookupEvent` happened at 18.46ms into the start of this span" rather than "`LookupEvent` took 18.46ms". If that's the case, I think duration might be the wrong word and something more like Timestamp would be more appropriate.

This is correct. They are timestamps not duration. I believe in the transformer code, this timestamp gets translated to "time since start of trace" that is why it shows up as a time duration.

**Comment by ie-pham** [comment]
> [@ie-pham](https://github.com/ie-pham) / [@nadinevehling](https://github.com/nadinevehling) - here's an alternative that was suggested by [@nadinevehling](https://github.com/nadinevehling) (adding `duration=...`). Below is the comparison of all three:
> 
> current main	option 1	option 2
> ![Screenshot 2024-08-13 at 22 43 37](https://github.com/user-attachments/assets/7479ebb9-c99e-499b-b58d-1dbb04f6845f)	![Screenshot 2024-08-13 at 22 38 53](https://github.com/user-attachments/assets/1cd57dd6-1d68-4c2b-b646-71d07fd3c912)	![Screenshot 2024-08-13 at 22 37 16](https://github.com/user-attachments/assets/5723d4f9-56e8-4967-a637-3e592e5b0b29)
> Let me know which one you prefer (or if you'd like to try something else :))

Sorry for checking into this ticket so late. As events are basically logs for tracing, I think it makes sense to have the time displayed first then the name.

**Comment by 09jvilla** [comment]
Ok so it sounds like Jenny recommends an approach that is a mix of the above options. Put the timestamp first as in the current main (rationale is that events are like structured logs on a span, and the convention for logs is to start with the timestamp), and then follow that timestamp by the event name (using the greyed out and bracketing structure [here](https://github.com/grafana/grafana/issues/90027#issuecomment-2315541155)). 

Do folks agree? I think we probably need another picture heh.

**Comment by ifrost** [comment]
> Do folks agree? I think we probably need another picture heh.

T-O-T-A-L-L-Y!

![Image](https://github.com/user-attachments/assets/545a11e5-74d1-4001-85c9-93b7fd9b97b5)

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcm52OWp1eHpkZG96aXA3b2k0N3RtajFvcTIxOWV6ZDNzM2QzbGZ6biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6yRVg0HWzgS88/giphy.gif)

**Comment by ie-pham** [comment]
Thank you for updating! This looks great. I prefer the darker color but it's not a strong preference. Will leave it to the UI experts to decide the styling on this.

**Comment by 09jvilla** [comment]
I really like what you shared @ifrost ! Honestly I can barely see the difference between the lighter and darker versions so either is fine with me. 

Re: the statement at the bottom, I think it should read "Event timestamps are relative to the start time of the full trace". Yes, events are a form of "structured logging", but more people will just know them / think of them as "events".

**Comment by ifrost** [comment]
I've update the label at the bottom. Here's the latest version:

![Image](https://github.com/user-attachments/assets/84f006b1-1e1f-494d-a668-c33f831ca3fa)
