### ISSUE TITLE
[Feature Request] support queries to return only non-zero numbers

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9003]
- What Grafana version are you using? 4.4.2
- What datasource are you using? Influxdb 1.3.2
- What OS are you running grafana on? CentOS 6.6

Sometimes zeroes in returned data is useful, sometimes it is not. Amongst other things, zeros can cause problems between indexes and graphs, not to mention force vertical axis to start at 0.

This can be manually worked around by changing the edit mode of a query to allow raw queries to be sent and adding the simple "AND value > 0" into the expression used with influxdb. Since this is not compatible with the query builder, once non-zero values are forced, the query builder can no longer be used.

Of course where do you start/end the comparisons for value here? Tricky! Do you allow "value > 100" (for example) in the query builder or limit it to "value > 0"? Can of worms there.

At present, I'd be happy if there was a checkbox like this:

[X] Allow zero in returned results

or

[ ] Only return non-zero results

or similar. This is a fairly simple query that should be supported by many backends.

**Comment by torkelo** [comment]
> Of course where do you start/end the comparisons for value here? Tricky! Do you allow "value > 100" (for example) in the query builder or limit it to "value > 0"? Can of worms there.

Not sure I understand what you mean, if you want to filter by a value you use that, where is the can of worms? 

Think it makes no sense to filter values in Grafana, it should be done in the query, the query builder needs an update to support numeric values in where conditions, there is already an issue for that.

**Comment by yellowpattern** [comment]
What's the other issue number? Link?

**Comment by torkelo** [comment]
Search for numeric where InfluxDB and you should find it, on mobile now :(
