### ISSUE TITLE
Dashbaord Variables that use the InfluxDB variable "v.timeRangeStop" are suddenly broken

### ISSUE THREAD

**Issue by gefaila** [grafana/grafana#90077]
### What happened?

If users are using InfluxDB and using flux to create dashboard variables then their query will contain a range function and uses the built-in variables `v.timeRangeStart` and `v.timeRangeStop`
e.g.
`from(bucket: "PLC_Router_Data")`
`    |> range(start: time(v: int(v: v.timeRangeStart)), stop: v.timeRangeStop)`
`    |> filter(fn: (r) => r["host"] =~ /^$host$/)`
`    |> keep(columns: ["_field"])`  
`    |> distinct(column: "_field")`
`    |> keep(columns: ["_value"])` 
`    |> sort()`

Howeever, the use of  `v.timeRangeStop` in variables now breaks the query and nothing is returned.
You have to currently use `stop:now()` or something else.

This has only broken in the last week or so.

### What did you expect to happen?

built-in variables like `v.timeRangeStart` and `v.timeRangeStop` should work

### Did this work before?

Yes

### How do we reproduce it?

1. Create a variable in a dashboard that uses  `v.timeRangeStop`

### Is the bug inside a dashboard panel?

No, It's in a variable for a dashboard

### Environment (with versions)?

Grafana: Cloud 
Grafana v11.2.0-72125 (b9812a0784)
Browser: Chrome, Version 126.0.6478.115 (Official Build) (64-bit)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by SokoFromNZ** [comment]
see https://github.com/grafana/grafana/issues/89948
