### ISSUE TITLE
Influx Db plugin issue

### ISSUE THREAD

**Issue by manbi786** [grafana/grafana#90082]
### What happened?

My both Grafana and Influx db containers are working fine under one network . But when I am trying to plugin in grafana, it starts giving me error:
InfluxDB returned error: error reading influxDB

### What did you expect to happen?

Supposed to connect and test successful

### Did this work before?

supposed to

### How do we reproduce it?

help me

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Docker

**Comment by jeremow** [comment]
Hi @manbi786, this is not an issue with Grafana and InfluxDB but more a problem of configuration on your side (restricted network, availability of your services, protected port). This problem has been discussed a lot on [Grafana Forum](https://community.grafana.com/) . I advised you to search here for explanation and examples!
