### ISSUE TITLE
[Feat Req]: Make ad-hoc-filters lookup use predefined fixed filters 

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#9009]
The ad-hoc query is great, thank you!
What I'm missing is the ability to append a fixed query to it.

##### Example

Given:

* a datasource containing the following key/values:
  * host
  * datacenter
  * service
* a dashboard with the following template variables:
  * datacenter
  * query (ad-hoc)

It would make sense that the ad-hoc query only returns results that match the selected datacenter. For instance, when `datacenter=A`, adding the key `host` to the ad-hoc query should only return hosts that are in datacenter A

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
