### ISSUE TITLE
[Bug] Column export issue with missing values

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#9010]
Version: 4.4.0
Datasource: MySQL
SO: Windows 2008 R2

When exporting with column format, the non existing values are showed at the end, out of the correct order.
Please see screenshots:

![graph](https://user-images.githubusercontent.com/29407741/29113547-9a5d8f08-7cf1-11e7-9223-1b7852e164d6.png)

![row-export-ok](https://user-images.githubusercontent.com/29407741/29113474-5fe7a6b0-7cf1-11e7-92cc-d0cf62b81247.png)

 
![row-column-error](https://user-images.githubusercontent.com/29407741/29113557-a4b3de3a-7cf1-11e7-9757-987832b085d1.png)

Best Regards,
Fernando Marques

**Comment by torkelo** [comment]
do you have an order by time asc in your query?

**Comment by fmcmarques** [comment]
Yes or course.
Is an issue exporting to excel in column format
You can see in attach that value 227 for "TDM BANDALARGA 8192 170GB" is for 2017-01-01 date and not for 2016-09-01. Previous  2017-01-01 there is not data for this serie.

Row export is correct (same data as graph), but column export ignore months without data and consider first value in the first month.

Please verify attach. This is not closed.

Regards
Fernando Marques

**Comment by fmcmarques** [comment]
Any plans to correct this issue in next releases?
Exporting in "series as column" format is not useful. Currently i am exporting as "series as row" and then creating a pivot table in excel to convert to "series as column" format.

**Comment by jblevens** [comment]
I frequently use this function and would also request that this bug is corrected. It causes mass confusion among our users who need to pull data from the visualizations. Thanks

**Comment by torkelo** [comment]
think this is fixed in new csv export feature
