### ISSUE TITLE
[Bug] sorting legend alphabeticly in dashboard view

### ISSUE THREAD

**Issue by pukseli** [grafana/grafana#9011]
You can sort data by clicking amount in the legend (total in the 1st image). But to sort alphabeticly i click empty space above (red pen in the 2nd image). Should there be some kind of text to click in order to sort the legend? 
image1
![image](https://user-images.githubusercontent.com/23657509/29116439-7190067a-7d03-11e7-9605-e32bb4277efd.png)
image 2
![image](https://user-images.githubusercontent.com/23657509/29116556-d27baa0c-7d03-11e7-86ab-ca0b03390c78.png)

I use grafana 4.2.0 and data source is influxdb. Grafana runs on ubuntu 16

**Comment by torkelo** [comment]
sorting the series should be done by the metric query

**Comment by pukseli** [comment]
I'm talking about sorting the legend. Clicking empty space sorts the legend so should there be a button for that?

**Comment by torkelo** [comment]
>  Clicking empty space sorts the legend so should there be a button for that?

It does? Very strange, nothing happens when I click the empty space.

**Comment by pukseli** [comment]
Found that clicking anywhere from that element resets the sorting from active sorting to default. I was wrong with the alphabetical one, it is the default returned from query.  
![image](https://user-images.githubusercontent.com/23657509/29122159-f2052658-7d19-11e7-9476-d3246b033a8a.png)

**Comment by MichaelSchoenfelder-SiV** [comment]
I have the same request to sort legend independently of the series.  In the example above I would want to see the legend as "fail cases", "pass cases" since that is the order that the data is displayed in.
This feature was also asked for in "Sort order of legends #2640 (https://github.com/grafana/grafana/issues/2640)"
I can't tell if this feature has been added to a more recent release.

**Comment by sgtechedge** [comment]
Same here. I would like to have a custom order of the labels. Or at least an alpabetical one.
