### ISSUE TITLE
[Bug]  NaN handling

### ISSUE THREAD

**Issue by urba** [grafana/grafana#9012]
NaN result should not be treated as number.
In graph legend, we got "NaN.00" (because of decimals).
In singlestat, coloring handle NaN as 0 (Grafana 3.x does not apply any color on NaN)

- What Grafana version are you using?
4.4.3
- What datasource are you using?
Elasticsearch
- What OS are you running grafana on?
RHEL7

**Comment by torkelo** [comment]
What does your metric query return?

**Comment by urba** [comment]
It's a query that sometime return nothing. The problem is not with the query here, but with the way NaN is displayed.
In graph legend we should have 'NaN' instead of 'NaN.00'.
In singlestat, we should have no coloring shema applied.

**Comment by torkelo** [comment]
I am unable to replicate this when my query returna nothing, get nothing in legend or or empty value in legend and get N/A in singlestat with no coloring

**Comment by urba** [comment]
![grafana-bug-nan-01](https://user-images.githubusercontent.com/2108348/29140862-51d225fe-7d4c-11e7-91b7-f3891f3c0a72.png)
![grafana-bug-nan-02](https://user-images.githubusercontent.com/2108348/29140863-51db4328-7d4c-11e7-935f-48f714a2cb9b.png)
See screenshots.
Color definition :
`  "colors": [
    "rgba(40, 180, 40, 0.9)",
    "rgba(130, 180, 20, 0.9)",
    "rgba(210, 190, 00, 0.9)",
    "rgba(230, 100, 40, 0.9)",
    "rgba(255, 30, 20, 0.9)"
  ],
  "thresholds": "1,5,25,50",
`
