### ISSUE TITLE
Dashboards: Chinese characters cannot be filtered when they are re-filtered within the template value

### ISSUE THREAD

**Issue by 291723286** [grafana/grafana#90123]
### What happened?

 I can no  use chinese character filtering in template values when upgrade v10.0.1 to v11.1.0. 
This issue will also occur with the new grafana v11.1.0 instances as well

issus
![1](https://github.com/grafana/grafana/assets/35591735/b92dd615-d0fc-44cd-806b-9e7ba35f2db0)

filter by 中国，but is no values 
![2](https://github.com/grafana/grafana/assets/35591735/5afc6716-32ab-4605-a16f-a383295ad315)

### What did you expect to happen?

filter sucess

### Did this work before?

v10.0.1 is ok

### How do we reproduce it?

Template Variables  container chinese character

### Environment (with versions)?

Grafana:  v11.1.0
OS: docker
Browser: google

### Grafana platform?

Docker

**Comment by kapmix** [comment]
Any solution? 
Expect sharing.

**Comment by ashharrison90** [comment]
dupe of https://github.com/grafana/grafana/issues/90123

**Comment by kapmix** [comment]
Grafana: v11.2.0

This issue still exists.
