### ISSUE TITLE
DashboardScenes: Panel paste button in toolbar has weird behaviour

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#90141]
There is a weird behaviour happening when trying pasting a panel in a dashboard in scenes. Sometimes, when you copy a panel from a dashboard and go to another one and try to paste, the button is disabled even though there is a copied panel stored.

https://github.com/grafana/grafana/assets/36818606/d75756e9-93af-4e95-9d78-c92d6950eab7

This happens because the paste button depends on a property in the dashboard scene instance state. We need to depend on the store key itself instead.

**Comment by shih-chris** [comment]
👍🏽  - seeing this too, and was about to create a video/issue. Thanks so much for creating the issue and working on it!
