### ISSUE TITLE
I need Grafana 4.4.1 bits for Mac 64 bit

### ISSUE THREAD

**Issue by ehamilto** [grafana/grafana#9015]
Hi,

I need the bits for Mac for this specific version (they are available for Linux and Windows but not for Mac from the Grafana website). 

I am following the instructions to build from source laid out here http://docs.grafana.org/project/building_from_source/ and while the build of the backend goes seamlessly, I am finding difficulty with building the front end assets. Even after installing the following,

npm install -g yarn
yarn install --pure-lockfile
npm install -g grunt-cli

When I do npm install on the root repo (as indicated here https://gruntjs.com/getting-started ), I get the errors below (I have removed the full path of my home directory for privacy reasons). These show up even if I do 

npm upgrade minimatch@3.0.2
npm upgrade graceful-fs@v3.0.0

I essentially need the bits in the immediate. If there is a quick fix I could try, that'll be great, but if you could make the bits available via a brew command that would also be OK.

Thank you in advance,

Ethan.

bash-3.2$ npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/55/f0/afb97337e9f85d44928d2f6938afbc4c302b12ab13dd2bbae8d93a9837638be5a975bb9850be427695d561f5cd94a62eb7a731031d5a2828904ecad03bab'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/d4/1f/70f7b69325b67106b78c5b699b484fa223ee5b2528061ad7b21fa50aa92dcf3e1e4fc674419978cdcb415300bdcaf3a9e67d68386b436ad06a5b0eb50aa9'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/bf/20/fb5a72c2789b035d5883ff1bba693bb8545fe69e587628f85e1bbdb1306e79f7ded9074622f7151a614230f7de456248689525a12631b5b556e2e2176437'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/a5/0b/4ae85bb1f4e832b7f90a4b4c0ceab2170835c129f9e932213f3934b401e382f76a4aba894704900b3ca686e9a5672e21f2c9236b6279c7fb753e4a17163f'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/23/a8/2daf8ac6dade2cbfb4d0be82d9a285d05ee279c33a2658734ff93f6d8347c318ecfc1d0e5f8d6933996b6b6a9de3d95390be2d9fb7db27bbbc19c8a86505'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/22/7f/9dcea8e2d1c78fa6c2722749e54757a3b5d963640317da85116ff735ae2982f49866ccce61a28bdfb4d1ffd961aa0ab77c9fdea42d9669e8396b2274fd76'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/5c/9a/c8e6252433dd06122b720a1e27f715b9d70db4ea06b9ac1777dd4de6f11de31ef1f4f2f01d58c71bd845bb9467cc8c0b3a64e6dabc9562322991921f957c'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/54/a6/03dc098a0a8cbafac978a783fcb0cb3c67d574760b1818c19095a2f171627610aa7ae2b95a9e27bb493872532b8957ee9112e22eae4ac0925ae83eae0891'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/d6/3a/5b9dee3d0482fbbcf909553b604238523fcb58559082404991f7f907b8381092d41ca8aa1f721a2a9b3a7b4640c39db89cf0c106adca625baf281ca83d20'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/9d/8a/1e6203819522ba94768425e794a84f89ddd7cfc734c63b569f14ec9f399a826f1d8017c7f32a327417dc93d32543b87d821493d56f7aeca16a1e73516dde'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home2/corp/ehamilto/.npm/_logs/2017-08-09T18_25_09_468Z-debug.log
bash-3.2$ npm upgrade minimatch@3.0.2
bash-3.2$ npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/64/dd/f9114bd0222f8b0dd68fff12cfeae1a5eb2654e2399b4c460e21aec52696db0e7d58753185cc7f59ea4d581e9f76e8ae990f0e156903ba16c7c57b7eb663'

Unhandled rejection Error: ENOENT: no such file or directory, chmod 'MYHOME/.npm/_cacache/content-v2/sha512/a7/5c/238ca9cbbe2d829a1c14b6b98a09bb629c89235b33d1c3373f7aa119c53368b1d8c8e2e15b7d5711d8b7f3dd15c813b45d94d9f556905f8625ce9a0971e2'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     MYHOME/.npm/_logs/2017-08-09T18_25_34_394Z-debug.log

**Comment by ixolt** [comment]
Hi, you could try to install by this way
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/bb610303f56e81799caa75c5a7b11335c3fd42d4/Formula/grafana.rb

**Comment by ehamilto** [comment]
thanks @ixolt . 

We have decided to go with the latest version instead of 4.4.1 since there wasn't much risk involved. We were able to fix this issue on a different Mac but then other issues popped up while building from source.  I am closing the issue now.
