### ISSUE TITLE
Auth: Enabling a user silently fails in 11.1.0

### ISSUE THREAD

**Issue by mgd722** [grafana/grafana#90152]
### What happened?

Clicking "Enable user" reports that the user is successfully enabled, but the user remains disabled.

https://github.com/grafana/grafana/assets/12187845/b86ee1f8-255f-485c-88d8-fa678e98ddf5

### What did you expect to happen?

The user should be enabled again.

### Did this work before?

Testing in 11.0.1 it seems to work.

### How do we reproduce it?

1. Start fresh using the 11.1.0 image: `docker run -d -p 3000:3000 --name=grafana grafana/grafana-oss:11.1.0`
2. Log in and create a test user via the ["New user" form](http://localhost:3000/admin/users/create).
3. Disable the user, then attempt to enable the user via the "Enable user" button on the user's page or via the `/api/admin/users/:userId/enable` endpoint.

### Environment (with versions)?

Grafana: grafana/grafana-oss:11.1.0
OS: MacOS 14.5 (running on Silicon)
Browser: Chrome 126.0.6478.127 (Official Build) (arm64)

### Grafana platform?

Docker

**Comment by aarongodin** [comment]
Thanks for bringing this to our attention @mgd722 - tracking down the issue now and will resolve this ASAP.

**Comment by IevaVasiljeva** [comment]
As fix has been merged in https://github.com/grafana/grafana/pull/88117 and will be released with the next 11.1.x patch release as well as 11.2.0. I'll go ahead and close this issue, but feel free to reopen it if the problem remains.
