### ISSUE TITLE
[Bug] When selecting auto refresh = off, it is not updated in the query parameter

### ISSUE THREAD

**Issue by aaron7** [grafana/grafana#9016]
Please include this information:
- What Grafana version are you using? 4.2.0
- What did you do? Set auto refresh to off.
- What was the expected result? The refresh query parameter in the url to be set to a value representing off so when sharing the link to the dashboard (or refreshing the page), the auto refresh is kept to off.
- What happened instead? The refresh query parameter stays the same. e.g. `?request=10s`.

**Comment by torkelo** [comment]
fixed in 4.4.3 
https://github.com/grafana/grafana/commit/2d2800e7109bc301c92165ac43b8ade97fa06dcb

**Comment by aaron7** [comment]
Thanks @torkelo! Sorry I missed this - we will update :)

**Comment by Codyooo** [comment]
My Grafana version is 4.6.4. When I add &refresh=off in the url  it gives me back an error says **Invalid interval string, expecting a number followed by one of "Mwdhmsy".** Is there a way that I can disable auto refresh in the url?
