### ISSUE TITLE
[Bug] ldap mapping and "Main Org"

### ISSUE THREAD

**Issue by smolar** [grafana/grafana#9018]
- What Grafana version are you using?
4.4.2
- What OS are you running grafana on?
RHEL 7.3

Hello,
I have Grafana and ldap (freeipa). Mapping works, groups filters too, but I have one question.
If I enable option auto_assign_org in grafana.ini, user login in "Main Org" and then I need choose "Switch to My Org" where My Org is define in ldap.toml (org_id=2). 
When I disable auto_assign_org, user is not authenticated and I see in ldap debug log information: "error="Cannot remove last organization admin""

Is any option to login to my organization without switch button, and without "Main Org" or anything else in my Organizations? 
I want to prepare grafana.db with my organizations and when I deployed all my tools everything working with freeipa.

Thanks!

**Comment by torkelo** [comment]
try removing Main Org (and all users),since you had auto_assign_org you got added to it, but you cannot be removed since your admin of it.

**Comment by pmdz** [comment]
Why when `auto_assign_org` param is enabled, Grafana is creating new organization instead of assigning user to existing one which is properly matched in LDAP group matching?
