### ISSUE TITLE
Dashboards: "All" variable is multi-select variable splits into individual values when passed via dashboard link 

### ISSUE THREAD

**Issue by pathakhimanshucs** [grafana/grafana#90180]
### What happened?

With the changes to dashboards in Grafana 11. I have noticed that when a dashboard contains a link to another one with the option "Include current template variable values" and the "All" option is selected on a template variable. When the linked dashboard opens the variable is displayed as if all the items in the multi-select are selected individually instead of all.

This is causing issues in layout for some existing dashboards which I have that had 100s of options for a single template variable.

### What did you expect to happen?

I expect the selected status to remain as displaying `All` instead of `X, Y, Z +(100)` 

### Did this work before?

Yes this has been working previously in Grafana 10.X

### How do we reproduce it?

1. Create two dashboards with matching template variables that are multi-value variables with All option included
2. Create link from one dashboard to the other with the option "Include current template variable values"
3. Select all option on the first dashboard, Navigate to the second dashboard using the link
4. Notice the All option has reduced to all the values in the multi-value variable individually.

### Environment (with versions)?

Grafana: 11.1.0 running in Docker image
OS: Official Grafana Docker Image, Windows 10
Browser: Google Chrome

### Grafana platform?

Docker

### Datasource(s)?

Postgres

**Comment by itsjusth** [comment]
This impacts my dashboards also.  We have Rows that have the selected Team/Domain names in the titles.  When you have All selected, then click from one dashboard to another using the link, the Row titles make the Dashboard unuseable:
![image](https://github.com/user-attachments/assets/477ff6b6-da5f-4885-b305-d2be44c443c3)

Normal (expected):
![image](https://github.com/user-attachments/assets/16ea9408-b4f3-44f9-8ffe-f08d5a8cb2b2)

**Comment by pathakhimanshucs** [comment]
This still causes issues sometimes when there are many template variables and when navigating to a different dashboard the url becomes so large that I get `414 URI too long` from some intermediate proxies

**Comment by mdvictor** [comment]
Don't have a fix yet for this, but I think setting the `Custom all value` will work as a workaround until we address this
![Image](https://github.com/user-attachments/assets/de576931-2032-4876-ac03-135f9d7ff38e)
