### ISSUE TITLE
[Bug] Searching measurements in Influx query is not case insensitive 

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#9019]
Grafana 4.4.0 with, InfluxDB datasource, Chrome & IE

When creating a graph and go to the Metric tab and add a new query to the measurement dropdown box it shows all available measurements. When you start typing it filters the dropdown box. 

This is very nice behavior, however the search is NOT case insensitive which is very confusing.
The field dropdown box below it has propper behavior and works case insensitive.

Note: It might be connected to the fix for issue #5399.

**Comment by torkelo** [comment]
the filtering is done my InfluxDB so not sure Grafana can do anything about this.
