### ISSUE TITLE
Authentication/Login: Login Url Request with JWT Token does not set grafana_session cookies

### ISSUE THREAD

**Issue by scorpionofwar** [grafana/grafana#90200]
### What happened?

After updating to Grafana 10.2.8+ from version 10.1.10 the grafana login response no longer contains the “Set-Cookie” headers for “grafana_session” and “grafana_session_expiry”, so the users stays signed out. Even though the login request itself was successful. New users do also get created by logging in per URL and jwt token, so grafana accepts it. The only difference I saw between version 10.2.8 and 10.1.10 are the missing Set-Cookie headers.

Configuration ini:
```
[paths]
provisioning = /etc/grafana/provisioning

[server]
enable_gzip = true
serve_from_sub_path = true
protocol = http
http_port = 9000
domain = mydomain
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

[rendering]
callback_url = http://grafana:9000/

[security]
allow_embedding = true

[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Editor
default_theme = light

[log]
filters = rendering:debug

[auth]
disable_login_form = false

[auth.anonymous]
enabled = false
org_role = Viewer
org_name = Main Org.

[auth.proxy]
enabled = true
enable_login_token = true

[auth.jwt]
enabled = true
header_name = X-JWT-Assertion
username_claim = sub
role_attribute_path = role
key_file = /key_set/rsa_pub.pem
auto_sign_up = true
```

Response Headers on Version 10.2.8:
```
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
cache-control: no-store
content-encoding: gzip
content-type: text/html; charset=utf-8
location: /grafana/
vary: Accept-Encoding
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
date: Mon, 08 Jul 2024 15:47:16 GMT
content-length: 56
connection: close
```

Angular Proxy Config, for prod environment I use nginx:
```
{
  "/api": {
    "target": "http://localhost:3000",
    "secure": false,
    "logLevel": "debug"
  },
  "/grafana": {
    "target": "http://localhost:9000",
    "secure": false,
    "logLevel": "debug"
  }
}
```

Grafana docker container log:
`2024-07-08 17:48:42 logger=context userId=1 orgId=1 uname=admin t=2024-07-08T15:48:42.722665051Z level=info msg="Request Completed" method=GET path=/login/ status=302 remote_addr=192.168.89.1 time_ms=26 duration=26.609821ms size=32 referer=http://localhost/login handler=/login`

### What did you expect to happen?

Grafana login route sets the grafana_session cookies after the succesful login with the jwt token.

1. User logs into my web application
2. Backend gives user a JWT
3. Frontend automatically signs into Grafana with the JWT per URL request({grafana_url}/login/). An header is set(“X-JWT-Assertion”).
4. User is now also logged into grafana with set grafana session cookies, charts are viewable

Response Headers on Version 10.1.10:
```
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
cache-control: no-store
content-encoding: gzip
content-type: text/html; charset=utf-8
location: /grafana/
set-cookie: grafana_session=e33f0cb0408215ef6c10c14cf0c7eb8c; Path=/grafana; Max-Age=2592000; HttpOnly; SameSite=Lax
set-cookie: grafana_session_expiry=1720454397; Path=/grafana; Max-Age=2592000; SameSite=Lax
vary: Accept-Encoding
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
date: Mon, 08 Jul 2024 15:50:02 GMT
content-length: 56
connection: close
```

Docker container log on Version 10.1.10:
```
2024-07-08 17:51:49 logger=http.server t=2024-07-08T15:51:49.522640404Z level=info msg="Successful Login" User=admin@localhost
2024-07-08 17:51:49 logger=context userId=1 orgId=1 uname=admin t=2024-07-08T15:51:49.523319181Z level=info msg="Request Completed" method=GET path=/login/ status=302 remote_addr=192.168.89.1 time_ms=41 duration=41.550136ms size=32 referer=http://localhost/login handler=/login
```

### Did this work before?

This is working perfectly in Grafana Version 10.1.10

### How do we reproduce it?

1. Grafana Version 10.2.8
2. Use JWT for authentication
3. Request grafana login url with the jwt as header.

### Environment (with versions)?

Grafana: 10.2.8+
OS: Docker Container/Windows 11/Linux
Browser: Edge/Chrome/Firefox

### Grafana platform?

Docker

**Comment by ms-jm** [comment]
I am facing the same problem. Using Grafana Version 11.0.0.

**Comment by scorpionofwar** [comment]
Now I can not even get it to work in v10.1.10 (7b442dc0f87c9f0cfcc952420bde91ebf5334511)... Any updates?

**Comment by kalleep** [comment]
Hey thanks for reporting this issue, this flow has never been an indented way to sign in into grafana. 

In https://github.com/grafana/grafana/pull/78602 we changed so that grafana_session cookie was only created in case `AuthProxy` was used to authenticate.  The config you provided for auth proxy had the side effect of always creating a new session token regardless of authentication method used.
