### ISSUE TITLE
[Bug] Database validation check fails due to case-sensitivity

### ISSUE THREAD

**Issue by jerbrownie** [grafana/grafana#9020]
Version: Grafana v4.4.3  
Datasource: InfluxDB  
OS: Ubuntu 14.04.5 LTS, Trusty Tahr  

Created and saved datasource.  When user-entry-case does not match database-entry-case, "DB Not found" error results.  Expected result would be 'Success'.

To reproduce:  
InfluxDB: CREATE DATABASE "EXAMPLE01"  
Create datasource w/ database "EXAMPLE01" - Data source is working  
Change database to "example01" - DB Not found. Could not find the specified database name.  

This was introduced in commit: 89a7c2c686854790f5306ab6de7f7aa48a55643b
Root cause: grafana/public/app/plugins/datasource/influxdb/datasource.ts

```  testDatasource() {  
    return this.metricFindQuery('SHOW DATABASES').then(res => {
      let found = _.find(res, {text: this.database});
...
```
I believe the following may remove the case-sensitivity... but my typescript is not very good
```  testDatasource() {
    return this.metricFindQuery('SHOW DATABASES').then(res => {
       let found = _.find(res.map(db => db.text.toLowerCase()), {text: this.database.toLowerCase()});
...
```

**Comment by torkelo** [comment]
well InfluxDB does not seem to be case sensitive too so if the case is wrong the queries return nothing, so think case sensitive check is appropriate
