### ISSUE TITLE
[Bug] GitHub Authentication not working beside reverse proxy (Nginx+SSL)

### ISSUE THREAD

**Issue by xmudrii** [grafana/grafana#9021]
Please include this information:
- What Grafana version are you using? **Version 4.4.3 (commit: 54c79c5)**
- What OS are you running grafana on? **Ubuntu 16.04.3**
- What did you do? **Setup GitHub Authentication**
- What was the expected result? **Supposed it will work.**
- What happened instead? **Login failed - Login provider denied login request**

What did I exactly:
I have setup Grafana and configured Nginx to proxy pass requests to Grafana server. It also uses SSL certs issued by Let'sEncrypt.
This is Nginx configuration:
```
server {
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;
        listen 80;
        listen [::]:80;
        server_name grafana.example.com;

        ssl_certificate /etc/letsencrypt/live/grafana.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/grafana.example.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;

        if ($scheme != "https") {
                return 301 https://$host$request_uri;
        }

        location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
}
```
Grafana configuration, GitHub part:
```
#################################### Github Auth ##########################
[auth.github]
enabled = true
allow_sign_up = true
client_id = rrr.redacted
client_secret = redactedstuff
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
;team_ids =
allowed_organizations = SomeRandomOrg
```
I also allowed sign ups under `[auth]`.
After I restarted Grafana Server, GitHub button appeared on Login page. When I click it, I get error:
```
Login Failed
Login provider denied login request
```
I gave permissions to app to read members. App owner is organization.
Callback url is `https://grafana.example.com/login/github`.
Not sure about Webhook url, but I set it to `https://grafana.example.com/`. Also tried `https://grafana.example.com/login/github`.

Is this feature supported and/or what can I do to get it working?

Edit: I noticed that I created GitHub App. I created OAuth App now as well, but it's not working, same error as above.

Edit2: logs
```
t=2017-08-10T20:11:32+0000 lvl=info msg="Initializing Stream Manager"
t=2017-08-10T20:11:32+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2017-08-10T20:11:32+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-08-10T20:11:32+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-08-10T20:11:38+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=127.0.0.1 time_ms=0 size=297 refe
rer=https://grafana.example.com/login
t=2017-08-10T20:11:39+0000 lvl=info msg="Login provider denied login request" logger=context userId=0 orgId=0 uname= error=redirect_uri_mismatch errorDesc="The redirect_uri MUST match t
he registered callback URL for this application."
t=2017-08-10T20:11:39+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=302 remote_addr=127.0.0.1 time_ms=0 size=29 refer
er=https://grafana.example.com/login
```

**Comment by torkelo** [comment]
working here when I test it so must be a config issue with your GitHub OAuth keys.

The error is pretty clear
"The redirect_uri MUST match t
he registered callback URL for this application."

An issue with the redirect url. 

Make sure the grafana [server] root_url option is the full public root url for your grafana server,

**Comment by xmudrii** [comment]
@torkelo Thank you very much for your fast answer and support!
Setting the `root_url` fixed the problem and now I'm able to login. Thanks once again.
