### ISSUE TITLE
“not found” pop-up message on every page in Grafana 10

### ISSUE THREAD

**Issue by billynorris** [grafana/grafana#90239]
### What happened?

This issue is identical to #87891.

This request is to backport the fix for #87891 to grafana 10.4

### What did you expect to happen?

No pop-up message

### Did this work before?

This issue is identical to #87891

### How do we reproduce it?

This issue is identical to #87891

### Environment (with versions)?

Grafana: 10.4.0
OS:
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by JacobsonMT** [comment]
Hi @billynorris, there is an open PR to backport this to 10.4: https://github.com/grafana/grafana/pull/90331

**Comment by gillesdemey** [comment]
Fixed with https://github.com/grafana/grafana/pull/90331
