### ISSUE TITLE
[Bug] TimeShift issue with graph panel over 1 year shifted. 1 year view works 24hour view does not

### ISSUE THREAD

**Issue by jermorse** [grafana/grafana#9023]
I've noticed that when I place a metric into a graph with timeshift() function of over 300days (ie 1 year old data) and try to plot it along side today's data I can only view it with Last 1 year selected. I want to view last 24hour view and show today's data as 1 metric and another that is timeshifted 357d.

I've got this successfully working for other metrics (aggregates though) but it seems that Grafana will only show both on the graph panel at the same time when I view 1 year view not 24hour view.

I'm convinced this is a bug of some kind in Grafana but am open to other suggestions to work around the problem. I've so far tried movingAverage() to attempt to show the data.

I can't provide screenshots or metric names due to privacy issues.

Grafana v4.4.2
Carbon/Graphite Datasource
Linux CentOS

**Comment by torkelo** [comment]
Timeshift is calculated / handled  by graphite. One reason for your issue could be retention schema issues with such a long time shift

**Comment by jermorse** [comment]
I suppose that's possible but there is certainly a graphing issue occurring. I found the work around was to actually shift the entire graph panel 357days then timeshift current metric +357d and it works. So the data stored from 1 year ago is functioning properly.
