### ISSUE TITLE
[Bug] Alias By [[tag_hostname]] or $tag_hostname not working with InfluxDb Grouped query

### ISSUE THREAD

**Issue by ivandal77** [grafana/grafana#9024]
Dear,
I am trying to obtain exactly what explained here 
[http://docs.grafana.org/datasources/influxdb/#alias-patterns](http://docs.grafana.org/datasources/influxdb/#alias-patterns)

using InfluxDB with OpenTSDB data.
The query is
 `SELECT "value" FROM "netdata.system.load.load1" WHERE "host" =~ /^$hostname$/ AND $timeFilter GROUP BY "host"`
there $hostname is a Template variable and host is a TAG.
But the result in the alias is always $host or [[host]] not the correct TAG value
![dashboard](https://user-images.githubusercontent.com/30720659/29203592-4dbd21f4-7e72-11e7-9ae8-dd7f23e6cd09.jpeg)

How can I solve?
I suspect a bug.
Some background info:

OS:
`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial`
Kernel:
`Linux fbk-vm-monitoring 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux `
Grafana Version:
` Grafana v4.4.3 (commit: 54c79c5) `
InfluxDB:
`version 1.3.2`

**Comment by daniellee** [comment]
What do you mean by "But the result in the alias is always $host or [[host]] not the correct TAG value"? Can you not just change it to `$tag_host`? Or do you mean that Grafana is changing the value of the ALIAS  BY field?

**Comment by ivandal77** [comment]
Thanks it works.
I am using $host instead of $tag_host. 
But the documentation is not so clear. 
You can close thanks again
Ivan

**Comment by daniellee** [comment]
Added this sentence: 

> The syntax is `$tag_yourTagName` (must start with `$tag_`).
