### ISSUE TITLE
[Bug] Click on Toggle Edit Mode button don't do anything (Prometheus datasource)

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#9025]
- What Grafana version are you using?

4.4.2

- What datasource are you using?

Prometheus

- What OS are you running grafana on?

CentOS

- What did you do?

We import an existing "Kubernetes cluster monitoring (via prometheus)" dashboard. The dashboard show metrics, it's working, but then I click on Edit in a Graph and click on "Toggle edit mode" button in order to see the Metrics in edit mode instead on inline edition but nothing is happening. 

- What was the expected result?

The expected result is to display the editionmode to ee metrics with dropdown list ... and to have the possibility to edit the metrics easily.

- What happened instead?

Click on "toggle edit mode" button do nothing.

 - Query metric:

`sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~"^$Node$"}[1m]))
`

Thanks

**Comment by Trubochkin** [comment]
When you switch the mode, does something write in the console?

**Comment by scraly** [comment]
Yes, here the error message in the console:

boot.8fcdddf2.js:52 TypeError: this.queryCtrl.toggleEditorMode is not a function
    at a.toggleEditorMode (boot.8fcdddf2.js:14)
    at fn (eval at compile (boot.8fcdddf2.js:54), <anonymous>:4:178)
    at e (boot.8fcdddf2.js:54)
    at b.$eval (boot.8fcdddf2.js:52)
    at b.$apply (boot.8fcdddf2.js:52)
    at HTMLAnchorElement.<anonymous> (boot.8fcdddf2.js:54)
    at HTMLAnchorElement.dispatch (boot.8fcdddf2.js:49)
    at HTMLAnchorElement.q.handle (boot.8fcdddf2.js:49)
