### ISSUE TITLE
[BUG] [REST API POST] UNABLE TO ADD NEW USER 

### ISSUE THREAD

**Issue by natalysheinin** [grafana/grafana#9026]
- What Grafana version are you using?  4.3.1

REST API get requests are working using CURL, but when I try to create a new user I get an error: 
`{"message":"Unauthorized"}`

`curl -k --u admin -X POST -d @data.json https://ip_here/grafana/api/admin/users`

Looking at documentation, I tried adding a user to the organization as well:
`
curl -k -u admin -X POST --data "role=Viewer&loginOrEmail=88888" https://ip_here/grafana/api/orgs/1/users`

and I get the following once again:
`
{"message":"Unauthorized"}`

Why is the API not working? Using Basic Authentication instead of API key as documented.

**Comment by daniellee** [comment]
The HTTP API docs are wrong in a few places (it's on my todo list to fix) but some actions require basic authentication and will not work with an API key. This is the case for all the admin actions.

**Comment by natalysheinin** [comment]
I am using basic authentication

**Comment by daniellee** [comment]
And the user is a "Grafana Admin"?

**Comment by natalysheinin** [comment]
yes

**Comment by torkelo** [comment]
this works for me:
```
 curl -v -XPOST -H 'Content-Type: application/json' --user admin:admin http://localhost:3000/api/admin/users --data '{"email": "asd@asd.com", "login": "mynewuser", "password": "newpass"}'
```

Maybe you disabled basic auth in grafana.ini?
