### ISSUE TITLE
[Feature Request] Support multiple value columns in table view

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9028]
- What Grafana version are you using? 4.4
- What datasource are you using? Influxdb
- What OS are you running grafana on?

When building a table view as output, only 1 value column is presented, even if there are multiple queries for metrics.

When the row type is a table (and not a graph), how are multiple series presented?

What I want to see is these two queries presented as different "value" columns:

SELECT "value" AS "Load Avg" FROM "load_shortterm" WHERE "type" = 'load' AND $timeFilter GROUP BY "host"
SELECT "value" FROM "aggregation_value" WHERE "instance" = 'cpu-average' AND "type" = 'percent' AND "type_instance" = 'user' AND $timeFilter GROUP BY "host"

hmmm. what's got lost here was use of "last()"... e.g.

FROM default load_shortterm WHERE type = load +
SELECT field(value) last() alias(Load Avg) +
GROUP BY tag(host)
ALIAS BY [[tag_host]]      FORMAT AS Table

... goal is to get a single table with both short term load average and CPU% next to the hostname

**Comment by torkelo** [comment]
There is a transform for that called time series to columns

**Comment by yellowpattern** [comment]
Tried that. It does not work. The end result is a mess and unreadable.

**Comment by yellowpattern** [comment]
I think you have not tried what I want to do and do not understand the problem :(

**Comment by torkelo** [comment]
Strange, can you u show? It will give you a value column per series.

**Comment by yellowpattern** [comment]
<img width="1257" alt="post1" src="https://user-images.githubusercontent.com/24280758/29241791-00a11bfc-7fc4-11e7-96f1-075a2d6110a2.png">

The hostnames are FQDNs (about 40 characters long) so first up, there are "size" issues

But as you can see... no data...
<img width="1256" alt="screen shot 2017-08-13 at 1 12 17 am" src="https://user-images.githubusercontent.com/24280758/29241808-9293695c-7fc4-11e7-83d2-36ad0e03c22d.png">
this second image shows the configuration of the table.

When data does appear...
<img width="1240" alt="screen shot 2017-08-13 at 1 12 45 am" src="https://user-images.githubusercontent.com/24280758/29241810-a97430de-7fc4-11e7-939c-3c4ae56e5c1a.png">

it is way out by itself.

One of the problems that I need to overcome here is that collectd will report different timestamps for the two metrics - CPU and load - so by default, they won't align on the same row using raw time stamps.

**Comment by yellowpattern** [comment]
When I choose a single host, it looks a bit better but not by much but the genesis of the problem can now be seen...

<img width="1249" alt="screen shot 2017-08-13 at 1 17 19 am" src="https://user-images.githubusercontent.com/24280758/29241842-3b552e86-7fc5-11e7-98db-b0a8834120fb.png">

**Comment by yellowpattern** [comment]
Now I can use "Repeat" and "Host" to get that little 3x2 table to show up 30 times but that's not really optimal (it's rather awful to look at). What I want is 30 rows, one for each host at a given time, with 3 columns (hostname, load and CPU)
