### ISSUE TITLE
Dashboard: Variables broken when label_values prometheus query filters for label "cluster"

### ISSUE THREAD

**Issue by SipSeb** [grafana/grafana#90318]
### What happened?

We updated Grafana from version 9.3.6 to version 11.1.0. After that, many dashboards were broken.

Most of our dashboards are based on a prometheus source. Every metric has the labels "cluster" and "dc". All dashboards have one variable where we can select the cluster. The dashboards the got broken with the update all contained another variable which used "cluster" as a label filter.

When playing around, we found out, that it only happens with the cluster filter. When using a different label for filtering, it works as expected. See the two screenshots for better understanding.
![variable_filter_job](https://github.com/grafana/grafana/assets/9820790/e4d93178-ed98-4f1b-885a-70386247754f) ![variable_filter_cluster](https://github.com/grafana/grafana/assets/9820790/6602840a-19d7-4a34-b100-3fdc7a570551)

### Workaround

Rewriting the query and then doing a regex match for the filter value helps.
![variable_filter_promql_query](https://github.com/grafana/grafana/assets/9820790/0e16f742-f28c-408b-bdb0-67d812a0730a)

### What did you expect to happen?

The old label_values queries we used before, should have just continued working. The frontend is new, but the functionality should have been as before.

### Did this work before?

Yes.

### How do we reproduce it?

1. Have prometheus metrics with a label named "cluster".
2. Try to create a variable with a label values query, use cluster as a label filter.
3. See the results at the bottom of the page.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.1.0
OS: Alpine
Browser: Safari/Firefox/Chrome

### Grafana platform?

Docker

### Datasource(s)?

prometheus 2.52.0

**Comment by SipSeb** [comment]
Might be related to #90226.

**Comment by broferek** [comment]
It doesn't seem to be related only to a Prometheus data source.

I have the same problem when extracting label values with Loki as a data source.

The first variable of the dashboard works properly but then, when I select a value in this dropdown, the second dropdown based on the selected value of the first one is not filtered down correctly.

It used to work until version 11.0.

**Comment by broferek** [comment]
Rolling back to Grafana 11.0 resolved the issue for me.

All dashboard filters work fine now.

**Comment by craph** [comment]
Same issue for me here https://github.com/grafana/grafana/issues/91034

**Comment by dalander** [comment]
> Same issue for me here #91034

Thanks, didnt see that, and the others!

**Comment by SipSeb** [comment]
For us (as the reporter of this ticket) it looks like, it's not a Grafana bug. We don't query prometheus servers directly but go through `promxy` instead. And the label_values variables work as long as they are already inside the original prometheus metrics. But as soon as we want to filter for a label that was added by `promxy`, it stops working, because apparently the `/api/v1/label/$name/values` request is passed to the downstream prometheus servers, and they don't know the filter criteria.
