### ISSUE TITLE
grafana does not support groupByNodes that a funciton in graphite ???

### ISSUE THREAD

**Issue by wolfzhaoshuai** [grafana/grafana#9032]
I use grafana V4.4 on MacOs Sierra10.12.6, when I use groupByNode, I can get charts what I wanted, but when I use groupByNodes, for example, groupByNodes(a.*.b.*, 'sum', 1, 3), I get no
datapoints. So, what the reason?

**Comment by torkelo** [comment]
Your probably using Graphite 0.9.15 , that function is only available in Graphite 1.x
