### ISSUE TITLE
How to create alert dashboard?

### ISSUE THREAD

**Issue by dejnekas** [grafana/grafana#9033]
Hello,

I need to create a dashboard which will be green on red depending on statuses nested below other dashboards. I've imagined it as an ALERT lamp and in case we have a problem operator can drill down to find out what's wrong - disk perf. issue, chiller status, UPS issue etc. So many different elements/dashboards would be nested below that general one: "ALERT". 

Is there any way how to pull out statuses from all other dashboards to display it on that main one? I was thinking about sort of TAGs which can be checked by main dashboard on those below it but I couldn't find any way to do that. Those TAGs should be also automatically assigned to the dashboard which receives alert from monitored data.

It would be useful also to have alerts silencing if those were acknowledged already. 
I think similar issue was mentioned here #5856 

Any help or advice appreciated.

**Comment by torkelo** [comment]
please use community site for questions
