### ISSUE TITLE
Unable to save the grafana dashboard with  error="database is locked"

### ISSUE THREAD

**Issue by sree86** [grafana/grafana#9034]
Hello team,

I am running the grafana in a container in AWS ECS, please find the dockerfile given below:

FROM grafana/grafana
MAINTAINER  Sreejith.Pilakkat
EXPOSE 3000
VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"]
ENV GF_SECURITY_ADMIN_USER admin
ENV GF_SECURITY_ADMIN_PASSWORD changeme
ENV GF_USERS_ALLOW_SIGN_UP false
COPY ./grafana.ini /etc/grafana/grafana.ini
ENTRYPOINT ["/usr/sbin/grafana-server"]
CMD ["--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini", "cfg:default.log.mode=console", "cfg:default.paths.data=/var/lib/grafana", "cfg:default.paths.logs=/var/log/grafana", "cfg:default.paths.plugins=/var/lib/grafana/plugins"]

I am not able to save the grafana dashboard to new name, please find the info of grafana given below: 

Information:
- What Grafana version are you using?
root@6e96371803f2:/# grafana-server -v
Version 4.4.1 (commit: 6a9f8ca)

- What datasource are you using?
Prometheus
- What OS are you running grafana on?
root@6e96371803f2:/# cat /etc/issue
Debian GNU/Linux 8 \n \l

- What did you do?
I was trying to save the dashboard to different name
- What was the expected result?
The dashboard was suppose to save with new name
- What happened instead?
It error out with the log

t=2017-08-14T14:54:50+0000 lvl=eror msg="Failed to save annotation for new alert state" logger=alerting.resultHandler error="database is locked"
t=2017-08-14T14:54:51+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=3 sent count=0
t=2017-08-14T14:55:03+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalHandler ruleId=1 name="Panel Title alert" changing state to=keep_state
t=2017-08-14T14:55:20+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=3 newState=alerting prev state=ok
t=2017-08-14T14:55:25+0000 lvl=eror msg="Failed to save state" logger=alerting.resultHandler error="database is locked"
t=2017-08-14T14:55:31+0000 lvl=eror msg="Failed to save annotation for new alert state" logger=alerting.resultHandler error="database is locked"
t=2017-08-14T14:55:31+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=3 sent count=0
t=2017-08-14T14:56:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalHandler ruleId=1 name="Panel Title alert" changing state to=keep_state
t=2017-08-14T14:56:40+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=3 newState=alerting prev state=ok
t=2017-08-14T14:56:45+0000 lvl=eror msg="Failed to save state" logger=alerting.resultHandler error="database is locked"

 Let me know if you need any info from my side

**Comment by sree86** [comment]
Can anyone please check on this ?

**Comment by daniellee** [comment]
It is an SQLite error that can occur on concurrent writes. See #7992 and #7013. Not sure exactly why you are getting this error.

**Comment by torkelo** [comment]
are you sure you are using v4.4.1 ?

**Comment by sree86** [comment]
Hello all,

Yes i am using v4.4.1. Now i had to wipe off the data and restarted grafana which is working fine, not sure why was the database got locked in first stage. Now i am just tracking log for exception. 

I will close this ticket for now, will reopen this if it appears again.

Thanks
Sreejith

**Comment by sree86** [comment]
Hello team,

The issue has come up again, can anyone suggest me a stable version of grafana to work with.

Thanks
Sreejith

**Comment by sree86** [comment]
Can someone please check this on priority

**Comment by sree86** [comment]
The have garfana data getting written to EFS volume, not sure if the EFS is the culprit :-/ ....awaiting someone to check on this from the grafana team

**Comment by torkelo** [comment]
Seems like running a SQlite database on EFS is problematic, I suggest you use MySQL or postgres for grafana's main db.

https://stackoverflow.com/questions/42070214/why-does-sqlite3-not-work-on-amazon-elastic-file-system
