### ISSUE TITLE
Grafan update on windows from 11.0.0 to 11.1.0.0 all MySQL (MariaDB) datasources broken

### ISSUE THREAD

**Issue by JoMonitor** [grafana/grafana#90356]
### What happened?

After update on windows from 11.0.0. to 11.1.0.0 all my MySQL (MariaDB) datatasource aren't working anymore. 
If you got to the settings-menu, then menu is empty:

![image](https://github.com/user-attachments/assets/8647b1a0-4e62-4cc5-83d8-56ca4e74c1be)

### What did you expect to happen?

That the datasources are working after the update as before.
Menu should look like this:

![image](https://github.com/user-attachments/assets/af2cfa6f-601f-4fba-906d-6ca8dcb1ec06)

### Did this work before?

yes

### How do we reproduce it?

1. execute update
2. start grafana 11.1.0
3. load dashboards
4. all panels show sql-errors.

### Environment (with versions)?

Grafana: 11.0.0. --> 11.1.0.0
OS: Windows
Browser: Chrome/Edge

### Grafana platform?

A downloaded binary

### Datasource(s)?

MariaDB, CSV, Loki, Infinity

**Comment by Beshelmek** [comment]
Same issue on Linux

**Comment by JoMonitor** [comment]
It's still the same with 11.1.3. on windows ...

**Comment by JoMonitor** [comment]
After updating to 11.1.03 also creating of a new MySQL-datasource doesn't work:
![image](https://github.com/user-attachments/assets/a4859804-e0be-4e93-a926-be1ae6872702)

Leads to this:

![image](https://github.com/user-attachments/assets/7f649545-70d0-44a0-8073-0e76de7d8fe6)

**Comment by JoMonitor** [comment]
Found the solution: Layer 8

From former times and due to the behavior of the MSI, I safed before and copied after the update the folders
config
data
public

Because the database , the custom-plugins and the config were afte rthe update missing.
Now, with version 11.1.x.x this leads to the mentioned error.
Only the folder conf nedds the be saved and copied after the update. The fiel defaults.ini is over wrtitten by the MSI.
And perjhpas some other, wiht I'v not checked.

I gues, you could close this issue. Sorry for the circumstances.

**Comment by ivanahuckova** [comment]
Thank you for sharing how you resolved the issue and providing guidance for others!
