### ISSUE TITLE
[Bug] Notification test fails with PagerDuty integration

### ISSUE THREAD

**Issue by bfgoodrich** [grafana/grafana#9036]
I simply added the API key (I have verified the key several times). I tried both the V2 and V1 PagerDuty API keys without success. There is not much to configure with this, so I assume it is some kind of integration error between Grafana and PagerDuty.

I tried naming the Channel "PagerDuty" and entered in the "Integration Key" with various attempts API Keys from PagerDuty (V1,V2, multiple times.) I have also tried checking or not checking boxes "send on all alerts", "include image", "auto-resolve incidents" with the same error 400 in the logs when I click on "Send Test". Regardless of what combination of things I have tried.

Please include this information:
- Grafana version
-- Grafana 4.4.3
- Datasource
-- InfluxDB
- OS Version
-- Ubuntu 16.04.1 LTS
- What I tested
-- PagerDuty integration (Alerting Channel) test button "send test"
- What I expected to happen
-- successful test
- What did happen (in the logs)
-- lvl=eror msg="Failed to send notification to Pagerduty" logger=alerting.notifier.pagerduty error="Webhook response status 400 Bad Request"

**Comment by torkelo** [comment]
does your grafana-server have network access? maybe some proxy in the way that responds with 400?

**Comment by bfgoodrich** [comment]
Yes, I believe so - the is a curl request from the host I am running grafana on

```
curl -XPOST -v https://events.pagerduty.com/generic/2010-04-15/create_event.json
*   Trying 54.245.112.46...
* Connected to events.pagerduty.com (54.245.112.46) port 443 (#0)
```

**Comment by bfgoodrich** [comment]
Well, apparently there are two points of integration with PagerDuty - I was looking at the API key, which is actually incorrect. Under Services in PagerDuty there is an "Integration Key" (hint: same as what is stated in the integration in Grafana). If you use the integration key everything works fine. I am closing this request and hopefully this helps comment helps someone else.

**Comment by gelldur** [comment]
That would be nice to add (i) icon next to field from where we should get this :)
Thanks.
