### ISSUE TITLE
[Bug] Unable to enable LDAP debug logging

### ISSUE THREAD

**Issue by Ultimation** [grafana/grafana#9037]
Version: grafana-4.4.1-1.x86_64 
OS: Centos 7.2

I uncomment these two lines from /etc/grafana/ldap.toml
```
[log]
filters = ldap:debug
```
Followed by a:
`systemctl restart grafana-server`
And in /var/log/grafana/grafana.log:
> t=2017-08-15T10:26:50+0100 lvl=info msg="Ldap enabled, reading config file" logger=ldap file=/etc/grafana/ldap.toml
> t=2017-08-15T10:26:50+0100 lvl=crit msg="Failed to load ldap config file" logger=ldap error="Near line 3 (last key parsed 'log.filters'): Expected value but found 'l' instead."

**Comment by torkelo** [comment]
logging is defined in grafana.ini not ldap.toml  sorry if the docs are unclear about that.
