### ISSUE TITLE
[Feature request]Use grafana-cli to import a dashboard json file 

### ISSUE THREAD

**Issue by lwhile** [grafana/grafana#9038]
I think it is necessary that grafana could import a dashboard json file(or other file as yaml to as template) by grafana-cli. If so I could deploy a grafana instance which draw many dashboard by ansible,and I don't need to config dashboard by browser

**Comment by torkelo** [comment]
You can use the api to import dashboards, or use a tool like wizzy (that uses the api):
https://github.com/utkarshcmu/wizzy

We will improve automation scenarios in the future, so data sources, dashboards, users etc can be configured via yaml config files.
