### ISSUE TITLE
Feature Request : add auto-downsample to opentsdb datasource

### ISSUE THREAD

**Issue by FrankyGT** [grafana/grafana#904]
Create an option that, when selected and set to a numeric value x, will divide the timespan of the graph by that number and downsample to that result. 
So if the graph shows 24 hours, and I select "24" as autodownsample value, it should downsample to 60 minutes

This way I can finally zoom out of a graph without crashing the browser

Thanks a lot for a great tool!

**Comment by amuraru** [comment]
I use to create an 'interval' template param and set it to 'auto'. Then in your metrics just use '$interval'.

**Comment by torkelo** [comment]
A interval variable should be fine for this no?
