### ISSUE TITLE
[Bug] 422 Unprocessable Entity while adding Notification Channel 

### ISSUE THREAD

**Issue by rahul8590** [grafana/grafana#9040]
- What Grafana version are you using?
4.4.3

- What datasource are you using?
OpenTsdb 2.1

- What OS are you running grafana on?
CentOS release 6.5 (Final)

- What did you do?
Trying to login via default admin credential
Trying to add a new Notification Channel. 

- What was the expected result?
Should be able to login using admin/admin
Should be able to add Notification Channel. 

- What happened instead?
In both the cases, in the web ui I get `validation error` as notification.  Also, in the I get the following json response when checked via chrome tool.

While Add a new notification channel 

HTTP Request from Chrome tool:

Request URL:https://blah.com/tunnel/grafana/login
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:x.x.x.x:443      (ip address of haproxy serving the domain. )    
Referrer Policy:no-referrer-when-downgrade 

```[{"fieldNames":["Name"],"classification":"RequiredError","message":"Required"}, {"fieldNames":["Type"],"classification":"RequiredError","message":"Required"}]```

While Trying to login using admin/admin credential.

```[{"fieldNames":["User"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Password"],"classification":"RequiredError","message":"Required"}]```

**Comment by torkelo** [comment]
What browser version are you using? Any extensions? 

Do you get this on other browsers? Looks very strange, lie your browse is unable to communicate properly with Grafana, or something in between like a proxy removing headers
