### ISSUE TITLE
Grafana Cloudwatch doesn't support filter by AWS "Resource Group Tagging"

### ISSUE THREAD

**Issue by maestropandy** [grafana/grafana#90419]
### What happened?

In my AWS + Cloudwatch datasource, Am trying to create grafana dashboard to display metrics (for billing) group by "Resource Group Tagging".

Unfortunately Grafana + Cloudwatch datasource supports only Instance ID,  ImageID, Instance Type.

### What did you expect to happen?

Am looking forward to collect billing of my running resources based on its tags (key and values). 

### Did this work before?

No, it wasn't working before. 

### How do we reproduce it?

-  Install Grafana 8.x version, and create IAM policies as referred in https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/
-  Create a new panel.
-  Select CloudWatch as the data source.

Configure the query:

Namespace: AWS/EC2
Metric Name: CPUUtilization
Dimension: InstanceId
Group By Tags:

In the Dimensions section, add the InstanceId dimension.
If you have custom tags like Environment or Application, you can filter by these in the query editor- This is not listing my tags or filter with manual.

### Environment (with versions)?

Grafana: 8.x
OS: Centos
Browser: Chrome
Cloud: AWS
Datasource: Cloudwatch

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

cloudwatch

**Comment by maestropandy** [comment]
IAM policies as below https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#metrics-and-logs-permissions

**Comment by sarahzinger** [comment]
Hi @maestropandy getting support for tags for the Cloudwatch Datasource has been a long requested feature: https://github.com/grafana/grafana/issues/77953 and unfortunately due to the AWS API we are somewhat limited in what we can do. 

However you may wish to look at the grafana cloud AWS O11y App which offers tag support: https://grafana.com/blog/2023/08/29/centralize-aws-observability-with-grafana-cloud/

**Comment by idastambuk** [comment]
Closing as this is tracked by https://github.com/grafana/grafana/issues/77953
