### ISSUE TITLE
Grafana-login&log-out user logs

### ISSUE THREAD

**Issue by devisyam** [grafana/grafana#90412]
Hi Team,
I am using grafana open source version 10.2.2 so now my requirement is to have a 150 days of log in and log out logs of grafana users is it possible to have to 150 days of logs in open source ?
will it work if i change the number of days in the grafana.ini file just like below?

# Expired days of log file(delete after max days), default is 7
max_days = 150
if not, what configuration that i need to do to have a 150 days of logs of grafana user in open source grafana

**Comment by tonypowa** [comment]
Hi @devisyam 

Thanks for reaching out. GitHub is mainly used for tracking bugs and feature requests. Your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) You are also welcome to ask in our [Community Slack](https://slack.grafana.com/)

We appreciate your understanding.
