### ISSUE TITLE
dashboard will be override by new dashboard with same prefix name but different uid

### ISSUE THREAD

**Issue by cruvie** [grafana/grafana#90415]
### What happened?

I try to import a new dashboard, but it override an exist dashboard with same prefix name but different uid

### What did you expect to happen?

import a new dashboard

### Did this work before?

yes

### How do we reproduce it?

1.import a dashboard with
```json
  "title": "MongoDB Dashboard",
  "uid": "1jEruounz",
```
2.import a dashboard with
```json
  "title": "MongoDB+ Dashboard",
  "uid": "mongodbx-dashboard",
```
3.view dashboard list

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: v5.0.0 (NA)
OS:centos7
Browser:edge

### Grafana platform?

None

**Comment by cruvie** [comment]
![20240715-115014](https://github.com/user-attachments/assets/5fbf21e2-b20a-4a8a-9069-da8ea8819e9d)
I test some name of the new dashboard
```json
MongoDB+ Dashboard //override
MongoDB++ Dashboard //override
MongoDB3 Dashboard //import new dashboard
M2ongoDB Dashboard //import new dashboard

**Comment by tonypowa** [comment]
Hello @cruvie 

Thank you for creating this issue

What's the version of your Grafana instance, and how are you running it (docker, via binary file, cloud, etc.?

**Comment by cruvie** [comment]
@tonypowa  Grafana: v5.0.0 (NA) in docker(centos7 image)

**Comment by tonypowa** [comment]
you are using a unsupported version @cruvie 
can you reproduce the same issue in a supported version of Grafana (v10+) ?

**Comment by cruvie** [comment]
works fine in latest release, but I can't upgrade, anyway thank you!
