### ISSUE TITLE
Grafana/Explore: After clicking on the trace, spans overlap

### ISSUE THREAD

**Issue by mareklevv** [grafana/grafana#90430]
### What happened?

Hi. There is a UI issue with Grafana showing Tempo data.
The spans overlap whenever I try to open a given trace to see its spans.
![image](https://github.com/user-attachments/assets/2891a442-32c0-4549-9fd1-7f8884a7c4a3)

![image](https://github.com/user-attachments/assets/69159036-0542-40ee-a133-1407ac34f5f1)

### What did you expect to happen?

Spans don't overlap.

### Did this work before?

Yes, before Grafana v11 this worked fine.

### How do we reproduce it?

1. Go to explore tab
2. Choose tempo datasource
3. Pick trace and try to open a spans

### Environment (with versions)?

Grafana: 11.1.0
OS: Macos Sonoma 14.3
Browser: Chrome 126.0.6478.127

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by DrFaust92** [comment]
Seeing this as well

**Comment by awangc** [comment]
Seeing this as well, the latest version of grafana in which this was working was v11.0.2

**Comment by miki1029** [comment]
It's still happening in version 11.1.3.

**Comment by bruksnys** [comment]
https://github.com/grafana/grafana/pull/89082 looks like it should fix the issue

**Comment by mareklevv** [comment]
I can confirm the issue is fixed!
