### ISSUE TITLE
Grafana Cloud: timevariables break in timestream-datasource

### ISSUE THREAD

**Issue by SundayPowerEndre** [grafana/grafana#90434]
### What happened?

Today our dashboards using time variables to interface with timestream broke. We see that all of our other dashboards work, and we see that time variables works for our other data sources. 

Also the shitty quality of the video comes from the 10MB limit, we did not easily find a compressing software that took the screenrecodring to below 10 MB without making it pixalted. .

https://github.com/user-attachments/assets/ac706bb6-a518-4c6a-b88e-cc7cae08b3b7

### What did you expect to happen?

I expect time variables to work as stated in the documentation when using them with timestream datasource. They are both maintained by Grafana.

### Did this work before?

Yes.

### How do we reproduce it?

Use any timevariables with a timestream datasource. 

Example:
```select $__from as foo, $__to as bar, ${__from:date:iso} as baz```

### Is the bug inside a dashboard panel?

No, it is the datasource. It is shown in the dashboard... 

### Environment (with versions)?

Grafana: v11.2.0-72847 (aaf23c64c3)
OS: All
Browser: All

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Timestream

**Comment by kevinwcyu** [comment]
Hi @SundayPowerEndre, if you add `scenes=false` as a query parameter to the URL of your dashboard, does it work?

**Comment by SundayPowerEndre** [comment]
Hi @kevinwcyu 👋🏽

Yes, that resolves the issue.

But i would still prefer if the newer versions of grafana supports time variables 😅

**Comment by kevinwcyu** [comment]
Hi @SundayPowerEndre, thanks, that confirms that a certain feature was causing the issue. We've disabled the feature for now so it _should_ work without the query parameter now.

**Comment by SundayPowerEndre** [comment]
Ok, great, thank you 🙏

**Comment by kevinwcyu** [comment]
@SundayPowerEndre, I'm going to close this issue for now since it should be resolved. Let me know if there are still issues with this.

**Comment by connorhsm** [comment]
@kevinwcyu I'm also experiencing this issue, as described and demonstrated, in Grafana Cloud. Adding `scenes=false` to the URL also allows me to work around the issue. I have opened support ticket 154678.
