### ISSUE TITLE
Adding Data Source UI for InfluxDB doesn't show organization, token, default bucket

### ISSUE THREAD

**Issue by MinhTraHong** [grafana/grafana#90450]
### What happened?

I'm trouble with UI influxData in grafana, UI doesn't show some fields in InfuxData Details
Organization, Token and Bucket. I installed the latest version Grafana in my Windows, Ubuntu, Docker.  I'm very suprised when all of them are missing the fields. It looks like they did not switch to the Specific UI for influxData.

Could you please tell me how do i fill my organization, token, bucket when i connect influxData.

My UI:
![image](https://github.com/user-attachments/assets/c6741c95-fb0a-461c-b0f6-83027c4d5034)

Their UI: https://www.influxdata.com/blog/getting-started-influxdb-grafana/
![image](https://github.com/user-attachments/assets/b35a6e5a-4ad9-47a9-96a5-e2fdd0bb435b)

### What did you expect to happen?

Please support me to resolve it

### Did this work before?

i have no idea, the InfluxData UI is very different with the guideline in document

### How do we reproduce it?

1. Install the latest garafana in official document: https://grafana.com/grafana/download
2. Adding InfluxDB data source
3. Check InfuxDB dtails
4. Find no fields for organization, token and bucket

### Environment (with versions)?

Grafana: 11.1.0
OS: Windows and Linux
Browser: Chrome and Firefox

### Grafana platform?

None

**Comment by alyssabull** [comment]
Hi @MinhTraHong - depending on the query language you choose (Flux, SQL, or InfluxQL), different connection details are required in Grafana. If you are providing an organization, token, and bucket, you are connecting to InfluxDB using the Flux query language.

To change the query language, select the appropriate option from the dropdown at the top of the configuration page in Grafana.

![Image](https://github.com/user-attachments/assets/6115ce06-7c4a-49f0-b5de-e14e98bfc0f6)

**Comment by alyssabull** [comment]
Closing this issue because the explanation above should fix it. Please reopen if that doesn't solve your issue.
