### ISSUE TITLE
Cannot view snapshots without logging in?

### ISSUE THREAD

**Issue by spacertechie** [grafana/grafana#9045]
The description in the share feature says that a snapshot is "publicly accessible to anyone with the URL" but this is false.

I've tried making the dashboard a snapshot then sharing a snapshot of a graph inside, but a login is still required.

We do not want to enable anonymous access, but we need to have publicly shareable graphs.

**Comment by torkelo** [comment]
Strange, cannot replicate. I can view snapshots without logging in (and anonymous disabled), can also view shared links to panels in a dashboard snapshot. 

Do you have any more info on your setup and auth? maybe an auth proxy in between?
