### ISSUE TITLE
Edit data source default for mysql

### ISSUE THREAD

**Issue by hernaneche** [grafana/grafana#9046]
Default data source for mysql is wrong, **http://localhost:8080**

"Save & test" gives this Error

> "dial tcp: address http://localhost:8080: too many colons in address"

Can be solved by writing something like this **localhost:3306**

That is avoiding protocol and with correct port.

**Comment by torkelo** [comment]
thanks for the info, will fix!

**Comment by jhlweb** [comment]
With MariaDB 10 and higher it turns out the standard port is 3307 instead of 3306. 
3306 is the standard port for all lower versions of MariaDB
