### ISSUE TITLE
Ensure all Explore Metrics pages have canonical URLs

### ISSUE THREAD

**Issue by jdbaldry** [grafana/grafana#90477]
The documentation content is reused in multiple locations, in both Grafana OSS and Grafana Cloud documentation.

Search engines don't like indexing pages with duplicate content, so we should canonical URLs to indicate which page is the canonical source for indexing.

To set canonical URLs, use the [`canonical` front matter](https://grafana.com/docs/writers-toolkit/write/front-matter/#canonical) in each page.

The canonical should be set to the URL of the Grafana documentation.
For example, the page https://grafana.com/docs/grafana-cloud/visualizations/simplified-exploration/ should have the canonical URL set to https://grafana.com/docs/grafana/latest/explore/simplified-exploration/.

**Comment by derek-cadzow** [comment]
@knylander-grafana @JStickler @tacole02  @lwandz13   Does this impact the Explore pages you are working on (or have worked on?).  If so, could you self-assign?

**Comment by JStickler** [comment]
@derek-cadzow  already addressed this in https://github.com/grafana/explore-logs/pull/610

**Comment by knylander-grafana** [comment]
I completed this in this PR: https://github.com/grafana/grafana/pull/91501
