### ISSUE TITLE
[Bug] Trendline disappears when window set to 1 hour

### ISSUE THREAD

**Issue by mcandre** [grafana/grafana#9047]
Please include this information:
- What Grafana version are you using? Grafana 5, viewed with Safari 10.1.1, FWIW.
- What datasource are you using? Telegraf
- What OS are you running grafana on? Debian Jessie
- What did you do? Changed the window from 3 hours to 1 hour.
- What was the expected result? See the series stretch out to become more visible.
- What happened instead? The series entirely disappeared.

**Comment by torkelo** [comment]
Here is a guide for how to troubleshoot metric queries:
https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
