### ISSUE TITLE
[Bug] Sending the API a dashboard with a null ID creates a dashboard with a null ID

### ISSUE THREAD

**Issue by adriangarza** [grafana/grafana#9048]
According to the documentation, a null ID tells Grafana to create a new dashboard. It does so, but only problem is the ID of the created dashboard is also null (where I'm assuming it should be an automatically generated unique integer), making future attempts to find it impossible.

The rest of the dashboard JSON is valid; I tested it by importing via the UI.

Running grafana:latest (4.4.3) in a Docker container on MacOS Sierra 10.12.6, streaming data from CloudWatch.

**Comment by torkelo** [comment]
If that was the case no one could update a dashboard after first save. 

Unable to replicate:
![image](https://user-images.githubusercontent.com/10999/29398638-0a6c6f46-8326-11e7-94a2-c6d041b30049.png)

So the first
```
POST /api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "dashboard": {
    "id": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "rows": [
      {
      }
    ],
    "schemaVersion": 6,
    "version": 0
  },
  "overwrite": false
}
```  

Then we try to read the dashboard: 
```
GET /api/dashboards/db/:slug
```
where slug is the slug returned from the first operation

and as you can see in the screenshot the dashboard now has an id

**Comment by adriangarza** [comment]
update: Sending a GET request afterwards returns a dashboard with the correct ID, it was just being set to null when exporting a JSON file.
