### ISSUE TITLE
Alerting: unnecessary default groupBy labels for simplified routing

### ISSUE THREAD

**Issue by janw4ld** [grafana/grafana#90488]
### What happened?

When I create an alert rule with a "Contact point" notification and set the `group_by` field to `["container"]` the simplified routing's auto-generated policy is created with `group_by` labels `["grafana_folder", "alertname", "container"]`; My intention with grouping these alerts is to receive one notification for all alerts emitted from a specific *container* in case multiple are Firing at the same time, but auto-inserting `alertname` into the grouping labels makes this behaviour impossible. On the other hand, manually creating a notification policy that only groups by `["container"]` works as expected and all alerts from the same container are grouped together.

![image](https://github.com/user-attachments/assets/cc79e471-032c-4619-9da6-8e4d92008349)

### What did you expect to happen?

The auto-generated policies to only group alerts by `["container"]`.

I'm not sure why grouping by `grafana_folder` and `alertname` is required for simplified routing, but grouping by `alertname` reduces the benefit of grouping by a lot IMO.

### Did this work before?

No

### How do we reproduce it?

1. Create an alert rule through the provisioning HTTP API
2. Set the alert rule's `"notification_settings"."group_by"` to `["container"]`
3. Observe the notification policy auto-generated by simplified routing is grouped by `["grafana_folder", "alertname", "container"]`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.1.0
OS: Amazon Linux 2 x86-64 1.29.3-20240625 (kubernetes 1.29.3)
Browser: Firefox 128.0 (64-bit)

### Grafana platform?

Kubernetes

### Datasource(s)?

Thanos 0.27.0 (Prometehus 2.27.0)

**Comment by janw4ld** [comment]
I'm currently working around this by manually setting the `alertname` label to one value shared between all alerts, not sure if this is "acceptable" use of the label or might break API-side at any time.

**Comment by JacobsonMT** [comment]
Simplified routing does not support this use-case, at least for now it is meant to simplify routing an alert to a contact point. it looks like you've found the way to accomplish this, which is to create a manual route.
