### ISSUE TITLE
[BUG] signout option is missing in side menu or in profile menu

### ISSUE THREAD

**Issue by sudhe** [grafana/grafana#9049]
Grafana version :  Grafana v4.4.3 (commit: 54c79c5)
datasource        :  graphite and mysql
OS                     :  Linux version 3.10.0-229.14.1.el7.x86_64 (mockbuild@x86-017.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)
 
Conf change    : I made "disable_signout_menu" to "false" in grafana.ini file. 
Expected          : "signout" option should be listed in side menu(or under profile menu)
Actual               : NO SIGN_OUT option. For switch user we need to clear history.

**Comment by sudhe** [comment]
reference --> https://community.grafana.com/t/signout-option-is-not-listing-in-side-menu/2139/2

**Comment by torkelo** [comment]
Not sure what it's going on for you, are you sure your looking in the place I described?

![image](https://user-images.githubusercontent.com/10999/29399120-3da978f2-8328-11e7-9f61-36a23d9ad7c9.png)

**Comment by sudhe** [comment]
Hi,

I am getting only "user profile" under this menu. Should i do any extra configuration in grafana.ini ?

**Comment by torkelo** [comment]
Can you do a screenshot while hover over the user sidemenu item?

**Comment by sudhe** [comment]
[image: Inline image 1]

On click "admin" (first entry in side menu) i will get below page

[image: Inline image 2]

########## my configuration detail##########

# Set to true to disable (hide) the login form, useful if you use OAuth
*disable_login_form = false*

# Set to true to disable the signout link in the side menu. useful if you
use auth.proxy
*disable_signout_menu = false*

#################################### Anonymous Auth ######################
[auth.anonymous]
*# enable anonymous access*
*enabled = true*

# specify organization name that should be used for unauthenticated users
*org_name = Main Org.*

# specify role for unauthenticated users
*org_role = Viewer*










*[users]# disable user signup / registrationallow_sign_up = false# Allow
non admin users to create organizationsallow_org_create = false# Set to
true to automatically assign new users to the default organization (id
1)auto_assign_org = false# Default role new users will be automatically
assigned (if auto_assign_org above is set to true)auto_assign_org_role =
Viewer# Require email validation before sign up
completesverify_email_enabled = false# Background text for the user field
on the login pagelogin_hint = email or username# Default UI theme ("dark"
or "light")default_theme = light[auth]# Set to true to disable (hide) the
login form, useful if you use OAuthdisable_login_form = false# Set to true
to disable the signout link in the side menu. useful if you use
auth.proxydisable_signout_menu = false*
All other Auth.$OPTION are disabled (I am referring auth.github,auth.google
etc)

Thanks for your timely reply :)

**Comment by sudhe** [comment]
hi Torkelo,

Issue is solved, issue is because of old chrome browser. I updated to new version. It will be better if we mention compatible browser versions somewhere in document.

![image](https://user-images.githubusercontent.com/8737888/29405358-4c042b08-835b-11e7-86fb-1c58672545a6.png)

Thanks for useful suggestions.
