### ISSUE TITLE
[Feature Request] Reducing the number of data points returned when interval is auto in Elasticsearch

### ISSUE THREAD

**Issue by mustafaakin** [grafana/grafana#9050]
Please include this information:
- What Grafana version are you using? 4.4
- What datasource are you using? ES
- What OS are you running grafana on? Linux / OSx
- What did you do? Did a query in a day scale
- What was the expected result? A nice graph
- What happened instead? Too many points on a graph

Is it possible to limit the number of data points returned especially in ES queries? Right now, it causes both load on the server and it does not actually look good in the chart. More than 100 points in a line chart makes it unreadable. 

I made a simple code for my purposes currently, but it is far from perfect. If auto is selected as an interval, It finds the right interval so that it does not exceed maxBuckets (100)

`plugins/datasource/elasticsearch/datasource.js`:

```js
      var from = options.range.from.valueOf();
      var to = options.range.to.valueOf();
      var duration = (to - from);
      var actualIntervalMs = options.intervalMs;
      var actualBuckets =  duration / actualIntervalMs;
      var maxBuckets = 100;
      if (actualBuckets > maxBuckets){
        var intervalMs = duration / maxBuckets;
        var intervalSec = String(parseInt(intervalMs / 1000)) + "s";

        options.scopedVars.__interval_ms.text = intervalMs;
        options.scopedVars.__interval_ms.value = intervalMs;

        options.scopedVars.__interval.text = intervalSec;
        options.scopedVars.__interval.value = intervalSec;
      }

      payload = payload.replace(/\$timeFrom/g, options.range.from.valueOf());
      payload = payload.replace(/\$timeTo/g, options.range.to.valueOf());
      payload = templateSrv.replace(payload, options.scopedVars);
```

**Comment by torkelo** [comment]
Just set a minimum group by time interval in datasource settings or below your queries, for example specify `>5m`  that way the auto interval will never go below 5m

**Comment by mustafaakin** [comment]
Yes, but if a large interval is chosen like a week, it still produces 7d*24h*60m/5m = 2016 buckets which is still way too much for ES to handle when there are 10 simultaneous queries running. Kibana auto mode produces always 30 buckets, which makes more sense since it displays bar chart as a distribution, although you can make it higher resolution if you want.
