### ISSUE TITLE
Default flag of datasource lost after datasource update via API

### ISSUE THREAD

**Issue by monrealis** [grafana/grafana#9051]
1. Create default datasource by POSTing to http://localhost:3000/api/datasources. Datasource has the default flag true.
2. Update that datasource by  PUTing to http://localhost:3000/api/datasources/graphite. The datasource is no longer default, even though  isDefault was set to true in JSON content. I think that this is not the expected behaviour.

Request:
```
{
  "access": "proxy",
  "basicAuth": false,
  "basicAuthPassword": "",
  "basicAuthUser": "",
  "database": "",
  "isDefault": true,
  "name": "graphite",
  "orgId": 1,
  "password": "",
  "secureJsonFields": {},
  "type": "graphite",
  "typeLogoUrl": "",
  "url": "...",
  "user": "",
  "withCredentials": false
}
```

**Comment by monrealis** [comment]
Version 4.3.2.

**Comment by torkelo** [comment]
Unable to replicate this, the UI uses the same api as well and no other reports toggling default or loosing default status

**Comment by monrealis** [comment]
Which version did you check?

**Comment by torkelo** [comment]
4.4.1 and 4.4.3 and master

**Comment by monrealis** [comment]
I reproduced it. The problem is when ID part of the URL does not match data source ID.

0. Install `docker`, `jq`, start `docker` service
1. `docker run --name=grafana -p 3000:3000 grafana/grafana`
2. Create `ds.json`:
`{"id":1,"orgId":1,"name":"Test","type":"graphite","typeLogoUrl":"","access":"proxy","url":"http://localhost:8080","password":"","user":"","database":"","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"jsonData":{},"secureJsonFields":{}}`
3. Create `update.sh`:
```bash
INSERT_RESPONSE=$(curl -s -X POST http://localhost:3000/api/datasources -d @ds.json -u admin:admin -H "Content-Type: application/json" -w "\n")
ID=$(echo $INSERT_RESPONSE | jq .id)
curl -s http://localhost:3000/api/datasources/$ID -u admin:admin | jq .isDefault
UPDATE_RESPONSE=$(curl -s -X PUT http://localhost:3000/api/datasources/$ID -d @ds.json -u admin:admin -H "Content-Type: application/json" -w "\n")
curl -s http://localhost:3000/api/datasources/$ID -u admin:admin | jq .isDefault
UPDATE_RESPONSE2=$(curl -s -X PUT http://localhost:3000/api/datasources/graphite -d @ds.json -u admin:admin -H "Content-Type: application/json" -w "\n")
curl -s http://localhost:3000/api/datasources/$ID -u admin:admin | jq .isDefault
DELETE_RESPONSE=$(curl -s -X DELETE http://localhost:3000/api/datasources/$ID -u admin:admin -w "\n")
```
4. `bash update.sh`:
```
true
true
false
```
