### ISSUE TITLE
Cloud: Create token api not creating token

### ISSUE THREAD

**Issue by henningWoehr** [grafana/grafana#90519]
### What happened?

When trying to create a token via the cloud api (`POST http://www.grafana.com/api/v1/tokens`), I get a list of tokens, which is the same as using `GET http://www.grafana.com/api/v1/tokens`.

### What did you expect to happen?

Create the token and return the created token

### Did this work before?

Yes. A coworker reported, that the error first occured someday last week. Before that, it worked as expected

### How do we reproduce it?

Simply try to create a token through the cloud api

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana Cloud (Free)

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
hello @henningWoehr 

can you please share the link to the Grafana documentation with the details of the API?

thank you

**Comment by henningWoehr** [comment]
I used these docs: https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#create-a-token

**Comment by tonypowa** [comment]
@henningWoehr 

Since it's a Grafana-cloud specific issue, please create a Support ticket for this https://grafana.com/profile/org/tickets/new

Feel free to reach out again if needed

Thank you
