### ISSUE TITLE
Button bar not displayed 

### ISSUE THREAD

**Issue by R00T88** [grafana/grafana#9052]
Please include this information:
- What Grafana version are you using? master 

![image](https://user-images.githubusercontent.com/9050487/29415355-126dca7c-8363-11e7-96c3-9db6d9141ceb.png)

- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 16.04 x86
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
i install grafana from apt on my ubuntu 16:04 x86.

![image](https://user-images.githubusercontent.com/9050487/29415609-db08e980-8363-11e7-9e84-d5599e83d315.png)

The issue is with button bar "save dashboard" and "manage dashboard" that are not displayed correctly

![image](https://user-images.githubusercontent.com/9050487/29415286-dbbb806e-8362-11e7-96d3-24d3afee6fe8.png)

Thanks

**Comment by R00T88** [comment]
other button are not displayed too

![image](https://user-images.githubusercontent.com/9050487/29415443-5dc75c90-8363-11e7-874d-c71c37ffdab9.png)

**Comment by torkelo** [comment]
Please use official apt repo or download official Deb package, you must be using a very old on official package /repo
