### ISSUE TITLE
Scenes: RefreshEvent is not called after click on refresh button/variable change in dashboard

### ISSUE THREAD

**Issue by mikhail-vl** [grafana/grafana#90538]
### What happened?

We use a subscribe on `RefreshEvent` to update panel. It stopped working with `GF_FEATURE_TOGGLES_ENABLE=dashboardScene` in Grafana OSS and using the latest grafana version in Grafana Cloud.

### What did you expect to happen?

`RefreshEvent` triggered

### Did this work before?

Yes, before Scenes dashboards.

### How do we reproduce it?

1. Subscribe to `RefreshEvent` using EventBus.
2. Click on Refresh button or do variable change.

### Environment (with versions)?

Grafana: Cloud or OSS with feature enabled
OS: any
Browser: any

### Grafana platform?

I use Grafana Cloud

**Comment by tommiz1989** [comment]
I can confirm this is replicated in my environment as well.
Started after upgrading to V11.1 (was previously 10.1.5).
This is only happening when dashboardScene feature is turned on.

**Comment by ivanortegaalba** [comment]
@asimonok @mikhail-vl I'm reopening this ticket to track the pending work in Dashboards.

Scenes event bus is different from DashboardModel one. Also, the bus received by the panel is the PanelModel bus. DashboardModel forwards to PanelModel bus the events that are interesting for the panel. In this case, Refresh.

For Scenes, we use a compatibility wrapper to keep those working, but this specific event is missing to be forwarded to the panel bus from Scenes bus.

**Comment by ivanortegaalba** [comment]
Hi! 👋 

The PR was merged in Scenes https://github.com/grafana/scenes/pull/852
This was also included in Grafana through https://github.com/grafana/grafana/pull/91241

This will be included in v11.2.0.

Thanks for your patience and collaboration @mikhail-vl @asimonok! Cheers!
