### ISSUE TITLE
Error building grafana 

### ISSUE THREAD

**Issue by R00T88** [grafana/grafana#9055]
Hello,
i'm not able to build package for grafana because i got this error on command go run build.go build package.

![image](https://user-images.githubusercontent.com/9050487/29435141-200b4eaa-83a6-11e7-9e2d-3d38333465e3.png)

My linux version is ubuntu 16.04

Thanks

**Comment by torkelo** [comment]
strange, what version of node are you running? None of the core devs are seeing this, I am running node v6.10.1

**Comment by R00T88** [comment]
i am running node v6.11.2 
maybe it's because i'm on ubuntu x86?

**Comment by R00T88** [comment]
adding --force switch to grunt it's step over that errors but i don't think it's a really fix.
After that i get this other error on creating package

![image](https://user-images.githubusercontent.com/9050487/29449992-365b7fca-83fd-11e7-83d5-9229a19a15d4.png)

**Comment by R00T88** [comment]
i got it working changing build.go

runPrint("cp", "-p", filepath.Join(workingDir, "tmp/bin/"+binary), filepath.Join(packageRoot, "/usr/sbin/"+binary))

to

runPrint("cp", "-p", filepath.Join(workingDir, "bin/"+binary), filepath.Join(packageRoot, "/usr/sbin/"+binary))

	runPrint("cp", "-a", filepath.Join(workingDir, "tmp")+"/.", filepath.Join(packageRoot, options.homeDir))

to

	runPrint("cp", "-a", filepath.Join(workingDir, "")+"/.", filepath.Join(packageRoot, options.homeDir))

remove "-p", "./dist", because it failed on build rpm package after build deb package

Hope this help someone to get it builded

Thanks

**Comment by daniellee** [comment]
@R00T88 what command are you running? 

The tmp directory should get created by the build process. It does on my machine if I run `go run build.go package` or `go run build.go pkg-deb` (if you just want the debian package). The grunt task `copy:public_gen_to_temp` creates the tmp directory.

**Comment by R00T88** [comment]
go run build.go build package

I followed the command in documentation.
Running this combo it not create tmp folder and failed on create rom package after deb creation

**Comment by daniellee** [comment]
I just ran that command and it did create the tmp directory. Are you sure you did not miss anything in the frontend step here: http://docs.grafana.org/project/building_from_source/#build-the-front-end-assets

Or do you get an error when `copy:public_gen_to_temp` task runs?

**Comment by R00T88** [comment]
The difference is that i add --force on grunt to be able to build due to error in first post.
So i think with that it skip something in the build process.
I presume copy:public_gen_to_temp never been called with --force to overdide that errors.

Is it possbile?

**Comment by daniellee** [comment]
Yes, that explains it. We should fix the tests to only approximately equal numbers that are floats. This hasn't been a problem for us previously as we only publish x64 packages.

**Comment by fg2it** [comment]
On your x86, the x87 floating point unit is probably used by code responsible for this computation, as it is usual on x86 linux. This is done differently on x64 and this is likely to result in the difference ([short story](https://gcc.gnu.org/wiki/x87note), [longer story](https://hal.archives-ouvertes.fr/hal-00128124v5/document)).
I also build for a 32-bit platform and I don't have your problem. So my vote is that the fpu is the culprit here.
On modern cpu, gcc and go allow to avoid the x87 fpu on x86, using sse instead. But, it is probably a lot easier to just change the test.

**Comment by R00T88** [comment]
Thanks for explaination.
If you commit the change and want me to try again on build package let me know.

Regards
