### ISSUE TITLE
Page display issue of one tutorial

### ISSUE THREAD

**Issue by northtree** [grafana/grafana#9056]
This tutorial is not well display due to the long line of CURL command.
http://docs.grafana.org/tutorials/api_org_token_howto/

Please divide the CURL command to multiple lines for better readability and responsive display. 
https://github.com/grafana/grafana/blob/master/docs/sources/tutorials/api_org_token_howto.md

Many thanks.

**Comment by torkelo** [comment]
ok, thanks for the feedback!
