### ISSUE TITLE
[PR Proposal] Simple Annotation Query Control

### ISSUE THREAD

**Issue by fzakaria** [grafana/grafana#9057]
Hello,

I've opened an _issue_ to see if there is interest in submitting a subsequent PullRequest.
Me and my colleagues have developed a DataSource Plugin and have recently added Annotation functionality.

We've done something quite simple -- we store the date of the annotation in the dashboard json!
This make the Annotation query control easy to use across any datasource plugin -- and I think it would be a great candidate to be included as **the default** annotation plugin.

Here is a screenshot (the HTML polishing is still ongoing) of what I mean by this:

<img width="1184" alt="screenshot 2017-08-17 22 43 45" src="https://user-images.githubusercontent.com/605070/29446361-af208c14-83a0-11e7-8404-3921b2214ddf.png">
* We are thinking of allow multiple date selections per annotation (i.e. multiple date pickers)

The annotation code then becomes extremely simple

```typescript
    public annotationQuery(options) {
      const { annotation } = options;
      const date = (annotation.date)
      const ret = {
        annotation,
        titile: annotation.name,
        time: date.valueOf(),
        text: annotation.text,
      }
      return [ret];
    }
```

This might be a great easy way to provide annotation support out of the box for every plugin.
The downside is only that it bloats the dashboard json.

Let me know what you think and I would be happy to open up a PR

**Comment by torkelo** [comment]
we are working on a built in annotation data store (That uses grafanas internal database). 

https://github.com/grafana/grafana/issues/1286#issuecomment-294281268

**Comment by fzakaria** [comment]
@torkelo thanks -- I will look forward to the release.
We might perhaps investigate open sourcing our efforts anyways for people on 4.4 (and lower) as an easy way for others to incorporate it. 

Cheers
