### ISSUE TITLE
Alerting: Can't use `$values` in labels

### ISSUE THREAD

**Issue by daniel-resdiary** [grafana/grafana#90589]
### What happened?

I'm trying to set a "severity" label based on the value of an alert.

The configmap that creates the alert has the following line to set this label:

`severity: '{{if gt (index $values "B").Value 10.0 }}Critical{{else if gt (index $values "B").Value 7.0}}High{{else}}Low{{end}}'`

But when the alert is created, this label has the value `{{if gt (index "B").Value 10.0 }}Critical{{else if gt (index "B").Value 7.0}}High{{else}}Low{{end}}`

I see the following entry in the Grafana log:

```
logger=ngalert.state.manager rule_uid=adjpb8awmrpj4f org_id=1 t=2024-07-18T10:13:10.229348662Z level=error msg="Error in expanding template" error="failed to expand template '{{- $labels := .Labels -}}{{- $values := .Values -}}{{- $value := .Value -}}{{if gt (index  \"B\").Value 10.0 }}Critical{{else if gt (index  \"B\").Value 7.0}}High{{else}}Low{{end}}': error executing template __alert_SentSlowHTTPResponses: template: __alert_SentSlowHTTPResponses:1:92: executing \"__alert_SentSlowHTTPResponses\" at <\"B\">: can't evaluate field Value in type string"
```

As you can see, the `$value` has been stripped out of the label.

### What did you expect to happen?

A label to be created with the templated value `'{{if gt (index $values "B").Value 10.0 }}Critical{{else if gt (index $values "B").Value 7.0}}High{{else}}Low{{end}}'`, so that when an alert fires, the label is set based on the value of the alert.

### Did this work before?

No.  I've seen the same problem with `$labels` in labels.

`$value` is parsed correctly in the "description" annotation.

### How do we reproduce it?

1. Provision an alert with a yaml provisioning file
2. Include the following label: `severity: '{{if gt (index $values "B").Value 10.0 }}Critical{{else if gt (index $values "B").Value 7.0}}High{{else}}Low{{end}}'`
3.  See that the label that's created actually has the value  `{{if gt (index "B").Value 10.0 }}Critical{{else if gt (index "B").Value 7.0}}High{{else}}Low{{end}}`

### Environment (with versions)?

Grafana: Grafana v11.1.0 (5b85c4c2fc)
OS: Windows 11
Browser:  Chrome Version 126.0.6478.128 (Official Build) (64-bit)

### Grafana platform?

Kubernetes

**Comment by daniel-resdiary** [comment]
There is a workaround for this: rather than use `$values`, I can use `.Values`, like this:
`severity: '{{if gt (index .Values "B").Value 10.0 }}Critical{{else if gt (index .Values "B").Value 7.0}}High{{else}}Low{{end}}'`

**Comment by JacobsonMT** [comment]
Please use the following syntax for setting dynamic labels based on values:

```
{{ if (gt $values.A.Value 80.0) -}}
high
{{ else if (gt $values.A.Value 50.0) -}}
medium
{{ else -}}
low
{{- end }}
```

More information: https://grafana.com/docs/grafana/latest/alerting/alerting-rules/templating-labels-annotations/#set-a-severity-from-the-value-of-a-query

**Comment by daniel-resdiary** [comment]
Apologies for the long delay in responding to this, but the above syntax doesn't work for me any more than the syntax I tried.

In both cases, `$values` is stripped away.

I tried:
`severity: '{{if gt $values.B.Value 10.0 }}Critical{{else if gt $values.B.Value 7.0}}High{{else}}Low{{end}}'`

But the alert now has a `severity` label with the value `{{if gt .B.Value 10.0 }}Critical{{else if gt .B.Value 7.0}}High{{else}}Low{{end}}` (i.e. without `$values`).

Each instance of the alert has that same severity label, rather than a label that depends on the value.
