### ISSUE TITLE
[Feature request] Hide series with only nulls from CSV export

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#9058]
- What Grafana version are you using?
from 3.1.1 to 4.4.3
- What datasource are you using?
prometheus, influxdb, elasticsearch
- What OS are you running grafana on?
debian 8,9

We have dashboards for customers allowing to see results either for all countries or one chosen country.
We use template variables to show in graphs either summarized values for all or for only one. But this leads to the fact that some series have only NULLs based on variables. We can hide them in graphs which is great but they are visible in CSV export with all NULLs. Which is rather confusing for customers and some of them have a hard time to accept it.

Would it be possible to add new check box "hide series with only NULLs from CSV export" directly into graph so users will see in export only non- NULL series? Thanks.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
