### ISSUE TITLE
Alerting: Unable to create notification policy for Mimir alert manager

### ISSUE THREAD

**Issue by jimgus** [grafana/grafana#90584]
### What happened?

This is a continuation of #90582. Same setup with an alert manager datasource pointing to a Mimir alert manager and a Opsgenie contact point (without the responder set obviously). I'm trying to create a notification policy but no matcher labels are accepted. I get the following error: `Error: error validating Alertmanager config: bad matcher format: "team"="team1"`. When doing the same without any matcher, the policy gets saved and propagated to the Mimir alert manager (verified by `mimirtool`). Also tried doing the same for a slack contact point bu the result is the same.

![image](https://github.com/user-attachments/assets/c9854864-d59c-474f-a5f1-3ea3fb19e0b6)
![image](https://github.com/user-attachments/assets/c66fd162-087f-4f26-b335-6c4db793b7d4)

After pressing Save policy:
![image](https://github.com/user-attachments/assets/0442bd1b-1083-4326-aeaa-62a54195887e)

 

### What did you expect to happen?

The policy saved and propagated to the Mimir alert manager

### Did this work before?

No

### How do we reproduce it?

1. Configure an alert manager datasource pointing to a Mimir alert manager
2. Configure an Opsgenie contact point 
3. Configure a notification policy with match labels

### Environment (with versions)?

Grafana: Grafana v11.0.0 (83b9528bce)
OS: Linux
Browser: Firefox

### Grafana platform?

Kubernetes

**Comment by Elaugaste** [comment]
I have the same problem. The error may be related to a problem in the documentation.

https://github.com/prometheus/alertmanager/issues/3400

**Comment by HamzaKhait** [comment]
Hello, 

Same problem here. 
@jimgus  did you found a solution ?

**Comment by mousimin** [comment]
used cortex AL, but got the same error

**Comment by Elaugaste** [comment]
for fix set utf8_strict_mode: true to mimir alertmanager config

**Comment by JacobsonMT** [comment]
@Elaugaste is likely correct, setting `utf8_strict_mode` to true should fix the issue. See related issue and explanation here: https://github.com/grafana/grafana/issues/87387#issuecomment-2201137880
