### ISSUE TITLE
Grafana does not use gmail SMTP to send notification

### ISSUE THREAD

**Issue by khanga6tm** [grafana/grafana#9060]
I installed Grafana on EC2 Instance (Centos 7) but Grafana does not use Gmail to send Email notification.

Anyone could help me to solve it. 

Here is my config for smtp and error log

> [smtp]
> enabled = true
> host = smtp.gmail.com:587
> user = "xxxx@gmail.com"
> password = "Abc@123321"
> ;cert_file =
> ;key_file =
> skip_verify = true
> from_address = "xxxx@gmail.com"
> from_name = Grafana
> 
> t=2017-08-19T04:37:49-0400 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
> t=2017-08-19T04:37:49-0400 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[someone@gmail.com]
> t=2017-08-19T04:37:50-0400 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu8\n5.7.14 Uged4pkbZZmwY8Im81boMJ04ce8Mczn2XWutzD45TqeKFOUTGAQ_c177_smXdiypuhe_Z2\n5.7.14 18B0fC1yLSDLKwW7M17BIS1VNajtI--43AMsodK3Y13t17SlgnmqT5lby4TdFaI261dk7t\n5.7.14 LMbvEmxDM1ScOAVNWAqoUbe5y-YZCOVZ7X6M_niZFV1Kah1Ox-jas7g1VDc96jjJH62Eac\n5.7.14 wflJ0wZQvVNAWU8ljI689riw8toMU> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 f26sm4976357wrc.67 - gsmtp"
> t=2017-08-19T04:37:50-0400 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu8\n5.7.14 Uged4pkbZZmwY8Im81boMJ04ce8Mczn2XWutzD45TqeKFOUTGAQ_c177_smXdiypuhe_Z2\n5.7.14 18B0fC1yLSDLKwW7M17BIS1VNajtI--43AMsodK3Y13t17SlgnmqT5lby4TdFaI261dk7t\n5.7.14 LMbvEmxDM1ScOAVNWAqoUbe5y-YZCOVZ7X6M_niZFV1Kah1Ox-jas7g1VDc96jjJH62Eac\n5.7.14 wflJ0wZQvVNAWU8ljI689riw8toMU> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 f26sm4976357wrc.67 - gsmtp"
> t=2017-08-19T04:37:50-0400 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=58.187.204.93 time_ms=1144 size=48 referer=http://xxxx.compute.amazonaws.com:3000/alerting/notification/new

**Comment by torkelo** [comment]
Gmail SMTP works here, maybe wrong port? Or if you have two factor auth you need to create a device password

**Comment by khanga6tm** [comment]
Thank for your reply but 
1. Port is not wrong because I am using this port to send notification from Nagios (now I want to move to Grafana)
2. What is device password to pass two factor authentication? Could you please detail it for me?

**Comment by torkelo** [comment]
go to your gmail account & two factor auth views, there you can create device passwords that you can use that sidestep two factor auth

**Comment by derit** [comment]
same issue with gmail smtp

**Comment by Bujupah** [comment]
[smtp]
enabled = true
host = smtp.gmail.com:465
user = xxxx@gmail.com
password = """Abc@123321"""
;cert_file =
;key_file =
skip_verify = true
from_address = xxxx@gmail.com
from_name = Grafana

**Comment by jmstechhome7** [comment]
same issue still 

[smtp]
enabled = true
host = smtp.gmail.com:465
user = xxxx@gmail.com
password = """PASSWORD"""
;cert_file =
;key_file =
skip_verify = true
from_address = xxxx@gmail.com
from_name = Grafana

enable less secure app and enable IMAP also still i am getting same issue

**Comment by OverWorldD** [comment]
Got the same problem here. Except in my case the error says username and password are not accepted. I have confirmed they are correct, I do not have 2fa activated and I tried with "allow less secure apps" in my google account settings but the problem persists.

**Comment by joshua-jerred** [comment]
One thing worth noting for people who find this discussion is the comment above the password line in the config. 
`
# If the password contains # or ; you have to wrap it with triple quotes
password = """EXAMPLE;PASSWORD"""
`
This was my problem.
