### ISSUE TITLE
Stretch

### ISSUE THREAD

**Issue by scargill** [grafana/grafana#9061]
Grafana on the new Raspberry Pi Stretch..

I installed and got nothing but a black screen - then noticed this "fix"  in a discussion area (see below).

Well, it works and I have Grafana running - but missing out that commented angular drag-drop line is producing some strange effects - as you might expect.

Does anyone have a proper fix for this....  (Raspberry Pi 2 or 3 - on Raspbian Stretch - latest release - new installation).

[ Quoting <owner@bugs.debian.org> in "Bug#843263: Info received (also on ..." ]
>If you wish to submit further information on this problem, please
>send it to 843263@bugs.debian.org.

--- /tmp/app.js	2016-11-07 11:54:51.850417179 +0000
+++ app/app.js	2016-11-07 11:53:45.760318994 +0000
@@ -51,7 +51,7 @@
    'ngRoute',
    'ngSanitize',
    '$strap.directives',
-    'ang-drag-drop',
+//    'ang-drag-drop',
    'grafana',
    'pasvaz.bindonce',
    'ui.bootstrap',

Just dropping the bad dep fixes the loading for me, i.e grafana now works.
Haven't drag 'n dropped anything so no idea of adverse effects there.

Miek Gieben

**Comment by torkelo** [comment]
You are probably trying to install a very old unofficiall grafana package. 

Try this for raspberry 
https://github.com/fg2it/grafana-on-raspberry

**Comment by fg2it** [comment]
@scargill I try my [4.4.3 build](https://github.com/fg2it/grafana-on-raspberry/releases/tag/v4.4.3) in a docker container based on stretch (precisely [resin/armv7hf-debian:stretch](https://hub.docker.com/r/resin/armv7hf-debian/)). I didn't perform extensive testing, but everything seems to work fine.

@torkelo it is a recent build but it is still an *unofficial* one 😉

**Comment by scargill** [comment]
Thanks but I don't want to use Docker... I have in the meantime however managed to get Stretch to install the latest Grafana - and it works just fine - that kluge above stopped some of the visual interface working and so was no good...   When we get a foolproof install working I'll publish it at https://tech.scargill.net  - marvellous.

**Comment by fg2it** [comment]
@scargill sorry, I was probably unclear. I didn't suggest to use docker. I only use docker to have an easy way to check if my last build was fine in a stretch environment since I am still using jessie. So what this test shows is that it should be working fine with the last version of grafana.
