### ISSUE TITLE
Loki datasource provisioning : Backend version support to optimize UI  using /series endpoint when is not needed

### ISSUE THREAD

**Issue by nachopv** [grafana/grafana#90613]
**Why is this needed**:

- To enhance end user response time
- To alliviate expensive requests to the backend ( Loki )
- To Alliviate browsers  both memory allocation and cpu computation

When querying a Loki datasource  with “Loki Query Builder” we have detected a non optimal pattern when inspecting labels

When finding the first label to pick up everything goes fine and /labels endpoint is used so everything is fast and response is ligthweigth

 
![image](https://github.com/user-attachments/assets/4ee1dc7f-f372-4f78-a695-fbc9e5f97368)

However on the subsequent filters we do see that /labels is not used anymore and /series is used instead which returns the whole series combinations for the selected timeframe and former filters. In this case the payload is heavy ( in some cases up to 100MB , slow and can even freeze the browser as long as it forces it to use way more memory on that parsing

 
![image](https://github.com/user-attachments/assets/b2e66d69-9b82-4ba4-aaf0-7300ca195ac8)

Response times are significantly different on the example shared 
-	/labels : 200ms
-	/series : 5000ms

Checking the [loki api labels endpoint](https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-labels) it does support both timeframes and matching filters so it does not make much sense already

We think is a similar use case  of what [happened on Propmetheus in the past with label_values()](https://github.com/grafana/grafana/pull/57553) due to api  not supporting filtering on older prometheus versions. 
That’s why now  Promql datasources provisioning let us define  prometheus versions

![image](https://github.com/user-attachments/assets/1e111af8-a7ea-480f-ba9d-65db5d1fcd2b)

**What would you like to be added**:

Loki provisioning feature indicating Loki version to keep using labels() function whenever possible instead of /series

We think is a similar use case  of what [happened on Propmetheus in the past with label_values()](https://github.com/grafana/grafana/pull/57553) due to api  not supporting filtering on older prometheus versions. 
That’s why now  Promql datasources provisioning let us define 

**Who is this feature for?**

[Add information on what kind of user the feature is for.]
Mainly intended to dashboard editors and anyone using explore data capability

**Comment by svennergr** [comment]
Hi @nachopv,

This is a good request - thank you! And as you said, the tricky part is really to solve backwards compatibility. We are usually a bit opposed to add more configuration options, e.g. a version selection, to the datasource configuration itself. Another solution could be to autodetect the Loki version running.

Just to be sure, are you itself running "older" Loki versions where you would see the need to configure some on the newer version, and some on an older version?

Either way, I will take this to the team and let you know where it lands.

**Comment by nachopv** [comment]
Hi @svennergr 
I think autodetect feature sounds nice too
I think that was not possible as long as Prometheus did not have and endpoint to do so neither on older versions.
We are running a mix of backends both on Loki Enterprise  ( 3.x ) on Grafana Cloud  and Loki oss ( 3.0 ) on premise

**Comment by nachopv** [comment]
Hi @svennergr 
Did you check internally?
We assume based on the Loki version api that it should quite similar to the approach used on Prometheus

**Comment by svennergr** [comment]
Hi @nachopv,

please excuse the big delay with this issue. We decided to go with a different approach and "just" default to the more performant `/labels` API. The reason is, that the degraded UX with "old" Loki databases wouldn't justify working on a version detection.

I hope you agree with that, but please let me know if you don't.
