### ISSUE TITLE
Side Navigation Bar - Sort Alhabetical

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#90639]
**Why is this needed**:

Option to sort the side bar in alphabetical order. Is much more easier to find things when they are sorted alphabetically.

<img width="335" alt="Screenshot 2024-07-19 at 10 17 13 AM" src="https://github.com/user-attachments/assets/a0a4056e-5e36-4ae1-8e43-3aff0d0d13a4">

**What would you like to be added**:

alphabetical order

**Who is this feature for?**

Every user using the ui

**Comment by eledobleefe** [comment]
Hello,
We consider this a product decision and don't contemplate this change as possible.
