### ISSUE TITLE
[Bug] Missing "ADD ROW" and Row Context Menu Icons

### ISSUE THREAD

**Issue by davidbru** [grafana/grafana#9063]
- What Grafana version are you using?
4.4.3

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
macOS Sierra 10.12.6

- What did you do?
Trying to add new rows and trying to move rows up and down in a dashboard

- What happened instead? 
The "add row" button and the row context menu icons (the three little dots next to each row) are missing.

I have two dashboards and in one of them ("Inet RPi") those links are visible and in the other one ("Temperature") they are missing. So it's likely not an installation issue but a dashboard issue.

![dashboard](https://user-images.githubusercontent.com/2734298/29496166-68fdf508-85cd-11e7-85ab-d2bc9a794a5c.png)

Unlike #7017 it has nothing to do with pinned or unpinned side menu.

**Comment by torkelo** [comment]
there is a toggle under dashboard settings, hide controls (shortcut CTRL+h (CMD+h on mac))

**Comment by davidbru** [comment]
My bad. Thanks for the quick feedback.
