### ISSUE TITLE
[New Data Source]: [Grafana 11 datasource] How to use Alibaba Cloud SLS (Log Service) as datasource? 如何连接阿里云 sls 日志服务数据源?

### ISSUE THREAD

**Issue by wujingcheng7** [grafana/grafana#90641]
### Background

I am using Alibaba Cloud SLS (Log Service), and after upgrading my Grafana to Grafana 11, I am unable to set Alibaba Cloud Log Service as a data source. Does anyone know how to resolve this issue?

The [official documentation](https://help.aliyun.com/zh/grafana/user-guide/add-and-use-the-sls-data-source-in-log-service?spm=a2c4g.11186623.0.0.7ec561e9kuwmn0#1132facc0fzne) only explains how to set up data sources for Grafana 9 and Grafana 10, without providing information for Grafana 11. Could it be that Grafana 11 does not support Alibaba Cloud SLS Log Service?

我在使用阿里云SLS日志服务，我的 Grafana 升级到 Grafana 11 之后，无法将阿里云日志服务设置为数据源了。请问有人知道这个如何解决吗？

[官方文档](https://help.aliyun.com/zh/grafana/user-guide/add-and-use-the-sls-data-source-in-log-service?spm=a2c4g.11186623.0.0.7ec561e9kuwmn0#1132facc0fzne)只说明了 Grafana9 和 Grafana10 如何设置数据源，并未提供 Grafana11 的相关信息。是否是因为 Grafana11 不支持阿里云SLS日志服务？

### Use case

My team is using Alibaba Cloud SLS Log Service and Grafana simultaneously, and we recently updated Grafana to Grafana 11.

我的团队在使用阿里云SLS日志服务，也同时在使用Grafana，最近将 Grafana 更新到了 Grafana 11。

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi @wujingcheng7 - this form is to request new plugins. I'd suggest raising the issue with the plugin developer as this is an unsigned plugin not published to the catalog. We can't really offer any support on it. If I were to hazard a guess, I'd suspect the plugin has some dependency on Angular (support for which was turned off by default in Grafana 11). If you have the plugin locally you could confirm using the validator: https://github.com/grafana/plugin-validator/

I'll close this ticket, but please feel free to re-open and edit if you would instead like to turn this into a plugin build request. 

David
