### ISSUE TITLE
Issues in exporting graph data into CSV format

### ISSUE THREAD

**Issue by chandrabvv** [grafana/grafana#9064]
I am currently using docker image of Grafana with latest tag available on the docker repository. I am using cAdvisor to collect the data and InfluxDB as database.
I  was monitoring the resource usage (memory) by the containers. When i was exporting the the data into CSV format then value in the CSV file doesn't match with the value in the graph when i was using bytes as data(IEC) field (unit in Axes: left Y). But when i was using bytes as data(Metric) field (unit in Axes: left Y) then values in CSV file matches with the values in the graph. That is Y-axis values are different in both unit, data (IEC) and data (Metric).

The major problem is data in the graph generated by cAdvisor matches with bytes of data (IEC) not with bytes of data(Metric). From verification point of view, I think data shown by data(IEC) field is correct. But I am not able to export correct value in CSV format shown by data (IEC) and there is no point in storing wrong values shown in the case of data(Metric).

My questions are:
1. What is the difference between data (IEC) and data(Metric)?
2. Which one is correct value?
3. Why both are showing two different values?
4. How can I export values shown by data(IEC) in CSV format?

**Comment by torkelo** [comment]
Please use community site for questions
