### ISSUE TITLE
can't use Assume Role ARN to setup cloudwatch integrtion

### ISSUE THREAD

**Issue by manojtr** [grafana/grafana#9065]
Hi,

I am trying to integrate cloudwatch to grafana using Assume Role ARN. I get the following error

```
t=2017-08-21T12:18:48+1000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
t=2017-08-21T12:18:48+1000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1 status=500 remote_addr=10.38.3.135 time_ms=3 size=36 referer=http://10.11.68.117:3000/datasources/edit/1?gettingstarted
```
Grafana version - 4.4.3 on AWS RHEL7

Anyone integrated cloudwatch using IAM role or instance profile? 

![image](https://user-images.githubusercontent.com/7928180/29501492-24a4b30c-866c-11e7-889b-174b5ce2a1ff.png)

**Comment by tuukkamustonen** [comment]
@manojtr Just bumped onto the same error, care to share your solution?

**Comment by kshcherban** [comment]
After upgrade instace/ecs task iam role stopped working as well.

**Comment by tuukkamustonen** [comment]
For me, it was actually running behind proxy, and setting `HTTP_PROXY`/`HTTPS_PROXY` in `/etc/default/grafana`, but forgetting to specify `NO_PROXY=169.254.169.254` also. After adding `NO_PROXY`, things began working.

**Comment by kshcherban** [comment]
I'm running grafana in AWS ECS container task and role assigned to ECS task worked before upgrade fine, as there was no configuration for that plugin, even instance has role with cloudwatch access.

**Comment by akhandeshi** [comment]
I am seeing the same issues on Grafana v4.6.3.  I am trying to define a cloudwatch datasource.  I attain my temporary credentials and configure the datasource to point to the credentials.

I get =2018-04-24T20:35:52-0400 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=[::1] time_ms=120575 size=34 referer=http://localhost:3000/datasources/edit/1
I defined HTTP_PROXY, HTTPS_PROXY and NO_PROXY in  /usr/local/etc/grafana/grafana.ini.  I have installed this on a mac.  Any thoughts

**Comment by edasque** [comment]
Any success with this? I am on 5.3.1
