### ISSUE TITLE
Value mappings not working for color setting

### ISSUE THREAD

**Issue by magdalenakusz** [grafana/grafana#90656]
### What happened?

I am using the value mappings to adjust the text and color of certain values for the pie chart. 
The mapping seems to work only for the text, but has no impact on the colours, on the screenshot the issue is well visible: 
<img width="1561" alt="ValuesMappingColorIssue" src="https://github.com/user-attachments/assets/fb46909e-13f2-4acc-8828-99600229c804">

The matching seems to work correct, as the text was modified as specified in the values mapping. But the color's new value is not being used. That might be a bug, or maybe I am missing some configuration? Could you please have a look on this issue?

### What did you expect to happen?

Both: Text and Color shall be used for mapping

### Did this work before?

Unknown, not tested with previous versions

### How do we reproduce it?

1. Use data source and query that generates simple table, with two columns: [name, count]
2. Define values mapping (for the [name] column) and specify new values for text and color
3. Observe results -> only the text is modified, color stays the same

### Environment (with versions)?

Grafana: Grafana v10.4.3 (0bfd547800)
OS: Mac OS
Browser: Safari

### Grafana platform?

None

### Datasource(s)?

PostgreSQL

**Comment by AsocPro** [comment]
I am also seeing this when trying to create a Pie chart of a count of how many true and falses were returned in a postgres query. The colors will change color if you set thresholds based on the numbers but nothing I can find will change them based on the fields besides the count.

**Comment by AsocPro** [comment]
This situation can also be reproduced easily for testing with the grafana test plugin with the following csv data. In the screenshot below there is no way that I can find to change the colors based on the Errors or Success. Only based on how high the count is.
![Screenshot_20240810_021006](https://github.com/user-attachments/assets/576c27a1-88e1-46b9-8f41-1aaa20efb7ef)

**Comment by AsocPro** [comment]
OK I played with it some more and it looks like the key here is to apply a Rows to Fields Tranform. Once you do that transform, you can go into the overrides menu and use Fields with name overrides to use the field names to set the colors for each field name.
![Screenshot 2024-08-12 at 1 38 15 PM](https://github.com/user-attachments/assets/157faeff-d1ab-40ff-8473-6d92a68d5a19)

**Comment by magdalenakusz** [comment]
@AsocPro thank you for the solution, it worked for me as well! 
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/b7618aa1-f051-4843-8b26-b137e06bc919">

**Comment by magdalenakusz** [comment]
I think the issue can be closed, since the solution provided by @AsocPro is fixing the described problem.
