### ISSUE TITLE
[Feature request] Webhook for event_plublisher

### ISSUE THREAD

**Issue by kfdm** [grafana/grafana#9066]
There are a set of events defined [1] that calls out AMQP as a way to pass events to external systems. Some of that is defined here [2]. Are there any plans to add support for a web hook as an alternative destination?

The use case I have, is that I manage a single Grafana instance for many teams, and it would simply some of that management, if I was able to trigger things, when Dashboards were updated for example.

If there are no plans to offer this type of functionality in the near future, could I have a few pointers about how you would prefer it to be implemented and I can give it a shot myself :)

I imagine a simple implementation would add a single config to grafana.ini something like

```
[event_publisher]
;enabled = false
;rabbitmq_url = amqp://localhost/
;exchange = grafana_events
webhook_url = http://sample.example.com/
```

CC @bergquist since I mentioned this idea to him at PromCon :)

[1] https://github.com/grafana/grafana/blob/master/pkg/events/events.go
[2] https://github.com/grafana/grafana/blob/master/pkg/services/eventpublisher/eventpublisher.go

**Comment by torkelo** [comment]
the current AMPQ events feature is not used at all (by anyone we know at least), only a very few events related to user creation are sent

**Comment by kfdm** [comment]
Would adding extra events (for dashboard creation and such) and the webhook settings be something that you would accept as a PR?
Would you want to remove the AMPQ events or leave it as is?
Any other guidelines that you know of for a feature like this?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
