### ISSUE TITLE
[Bug] Alert mail with ugly js-error

### ISSUE THREAD

**Issue by Luke1887** [grafana/grafana#9067]
- What Grafana version are you using?
v5.0.0-pre1 (commit: 3dd3731

- What datasource are you using?
Graphite, Elasticsearch 5.x

- What OS are you running grafana on?
RHEL 7

- What did you do?
Created a Dashboard with different source (Graphite, ELK 5) and annotations (source: ELK 5)
Dashboard looks very fine viewing it. Created an alert on a panel with graphite source.
When alert is sent by mail, I get an ugly js-error, probably (my guess) because of no data on annotation in watched time range.

- What was the expected result?
Correct alert, but with an error in the screenshot.

Hi there, has someone expected a similar problem? Viewing the dashboard with browser, looks totaly normal, getting no errors. In the alert mail it comes...
Deactivating the notification make the mails nice again.

![image](https://user-images.githubusercontent.com/23240809/29506115-50413f48-864a-11e7-94ee-6a6f703300cf.png)

**Comment by torkelo** [comment]
looks like you have an Elasticsearch annotation query that is failing when executed from the grafana-server.

Anything in grafana.log? maybe you have Elasticsearch configured for direct access (ie from user browser directly) and cannot be accessed from the server running Grafana?
