### ISSUE TITLE
[Question] Supported MySQL field types?

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#9068]
- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 

I did ask but got no answer.

- What Grafana version are you using?

Latest stable

- What datasource are you using?

MySQL

- What OS are you running grafana on?

Linux Mint

- What did you do?

I am trying to fill a simple Table panel with a very simple query:

```
SELECT
  url AS metric,
  COUNT(*) AS value
FROM downloads
WHERE
  $__timeFilter(timestamp)
GROUP BY metric
ORDER BY value DESC
LIMIT 10
```

- What was the expected result?

I was expecting to get a sorted table of results.

- What happened instead?

I get the error "Database type BLOB not supported".

The problem is _not_ with the database, since much more complex queries from other tables of the same database work just fine. So, the problem must be in this particular table I'm querying with this query. The structure of this table is the following:

```
CREATE TABLE IF NOT EXISTS `downloads` (
  `id` int(11) NOT NULL auto_increment,
  `session` CHAR(32) NOT NULL,
  `timestamp` datetime NOT NULL,
  `url` text NOT NULL,
  `outfile` text NOT NULL,
  `shasum` varchar(64) default NULL,
  PRIMARY KEY (`id`),
  KEY `session` (`session`,`timestamp`)
);
```

After searching for this error in the source of Grafana, it seems that it comes from the file `grafana/pkg/tsdb/mysql/mysql.go`. Apparently, the field types are examined for a list of recognized values and this error is issued if the type is not recognized. Unfortunately, I don't know Go and don't understand what exactly are the recognized field types, so I can't figure out which field in the table is causing the problem. Is it the `id INT(11)` field? Should I change it to `id INT(16)` or something? A list of the "permitted" field types would be also very helpful, so that I could check the field types of the other tables in the database.

**Comment by daniellee** [comment]
Fixed in master already #8918. Will be released in the next version of Grafana or is available in the nightly builds - https://grafana.com/grafana/download/5.0.0-8667pre1
