### ISSUE TITLE
Public Dashboard: Relative time on panel doesn't work when time picker is disabled

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana#90681]
### What happened?

When having a relative time range set in a dashboard, this relative time range is not respected in the associated public dashboard when the time range picker is disabled. 

This is because, in the codebase, if the time picker is disabled, we set the time range from the dashboard time range: https://github.com/grafana/grafana/blob/main/pkg/services/publicdashboards/service/query.go#L398-L422

### What did you expect to happen?

The relative time range should be respected in the public dashboard.

### Did this work before?

Not that I'm aware.

### How do we reproduce it?

1. Create a dashboard with a panel with a relative time range set (should be greater than the dashboard time range).
2. Set this dashboard as public.
3. Access the public dashboard, part of the panel will be empty. 

### Environment (with versions)?

Grafana: Latest
OS: Windows
Browser: Chrome

### Grafana platform?

None

**Comment by evictorero** [comment]
Probably [duplicated](https://github.com/grafana/grafana/issues/79070)
The problem with these `relative` time ranges (like today so far) is that they depend on the timezone. Since the API does not expose any time-related data as input, it uses the dashboard or the server timezone to do the math. If that timezone is different from the consumer (the browser in this case) it is not possible to honor the selected time range.
When enabling the timepicker the API uses the data from the payload to calculate the correct times and that is the reason why it works in those cases.
One solution could be to send the timezone as a parameter but this will allow the consumer to manipulate it and see data different from the one set in the dashboard (like one day before).

**Comment by AgnesToulet** [comment]
This is not a time zone issue; the relative time range is something that you can set in a panel, and that's just ignored by the public dashboard. We should have access to this time range in the dashboard JSON and be able to use it.
![image](https://github.com/user-attachments/assets/5619884f-7e0d-4701-9ad2-3e03c31b3b0b)

 The time zone issue is another issue that, I agree, will be trickier to solve.

**Comment by grvsoni** [comment]
@AgnesToulet 
Do we have any updates or ETA for this issue?

**Comment by AgnesToulet** [comment]
Not for now, we have prioritized other things for this quarter and we'll discuss this again for Q4. Note that this issue can be worked around by enabling the time range picker.
![Image](https://github.com/user-attachments/assets/e5e0813f-eb72-41e2-8d0a-9ad7e46b69d3)

If the workaround can't be used by some customers, please reply to this issue with their reasons and we'll bump the priority of this issue.

**Comment by AleksandraGrafana** [comment]
This escalation: https://github.com/grafana/support-escalations/issues/11597 cannot be workaround with this, as the customer has already the time picker enabled and it does not help.

**Comment by AgnesToulet** [comment]
@AleksandraGrafana We never heard back from the customer for this escalation: https://github.com/grafana/support-escalations/issues/11597 but I think it should work. 

Did you mean this escalation: https://github.com/grafana/support-escalations/issues/11969? In this case, it's a different issue that we may not want to tackle. I'll catch up with the comments and give an update shortly.

**Comment by AleksandraGrafana** [comment]
Hi @AgnesToulet thank you for correcting me, I got mixed up. 
yes, I meant this escalation: https://github.com/grafana/support-escalations/issues/11969. Thank you very much!

**Comment by grvsoni** [comment]
@AgnesToulet 
Just checking, Do we have ETA for this? very roughly on timeline?
