### ISSUE TITLE
[Bug] keyboard shortcuts "Collapse/Expand all rows" not working

### ISSUE THREAD

**Issue by woidi** [grafana/grafana#9069]
On my grafana 4.4.3 (with mousetrap 1.6.0) shortcuts 'd E' and 'd C' were not working on the dashboards.

I changed them to 'd shift+e' and 'd shift+c' in public/app/core/services/keybindingSrv.ts and different browsers startet to recognise the shortcuts.

**Comment by daniellee** [comment]
Thanks for reporting this. Confirmed both the bug and your suggested fix.
