### ISSUE TITLE
Feature Request: Displaying current value within plot area

### ISSUE THREAD

**Issue by mkhaitman** [grafana/grafana#907]
It would be extremely helpful if we can select a series within a graph and have its current value displayed in a large font across the graph. Presently, the current value can only be seen in a small legend below or to the side of the graph, however, it would be a cool display feature to support a larger display of it over the plot area!

**Comment by torkelo** [comment]
solved via singlestat panel
![image](https://cloud.githubusercontent.com/assets/10999/12446607/46bcad92-bf6b-11e5-8b1e-68926f843bfa.png)
