### ISSUE TITLE
Public Dashboard no longer refreshing as expected

### ISSUE THREAD

**Issue by Gerdofal** [grafana/grafana#90706]
### What happened?

Public dashboard which has always refreshed as expected has stopped doing so with the most recent update (on grafana cloud). Tried re-saving and checking box to update the refresh to see if that fixed the issue, but did not fix it.

It doesn't seem to even try to refresh... the tickmarks that show on every panel when it's refreshing never even show on the public version.

### What did you expect to happen?

Public dashboard should honor the 60 second refresh like it used to.

### Did this work before?

Yes. I'm not sure which update on grafana cloud caused it. It seems potentially related to the update that changed the refresh/edit/save bar.

### How do we reproduce it?

1. Open public dashboard
2. Note that dashboard, which refreshes as expected when logged in, does not refresh when public link loaded

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: grafana.net
OS: Windows
Browser: Chrome and Edge both show same behavior

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
Hello @Gerdofal 

Thank you for reporting this issue. Could I ask you a few additional questions and for some clarifications?

- Could you please tell us the exact version of Grafana you are using?

- Have you checked the Grafana server logs for any errors that occur when you try to access the public dashboad

- Lastly, could you provide a screenshot or screen recording of the issue as it happens?

Thank you!

**Comment by tipani86** [comment]
I can report the same issue. Using Grafana cloud SaaS so not sure about the exact version (assuming it's always the latest?), but I've seen some UI elements on the non-public side updating itself slightly so I guess the cloud service is always a living and evolving product.

As to your other questions, not sure how to check the logs of Grafana cloud SaaS? We probably don't even have the permissions for that? I am actually using Grafana to visualize the logs of my own server, but that's not where Grafana is running on.

Lastly, not sure how to screenshot or even screen record something that doesn't exist? It will be just a long video of nothing happening :)

**Comment by tonypowa** [comment]
Apologies, I didn't notice you were using Grafana Cloud.

The issue has been added to the team's board for review.

**Comment by tipani86** [comment]
@Gerdofal you might already figured this out but FYI, we were able to work around this with a really dumb but effective way: Most browsers have tab auto-refresh extensions. Just download one and set it up to refresh the dashboard tab every x minutes or so.

It might not be as nice-looking as the in-page refresh with the jarring full-page reload but still better than no refresh.

**Comment by Gerdofal** [comment]
I played around with the settings some more and think I found the issue. The refresh seems tied to the date picker after the updates of the date picker, so if it is disabled, the refresh doesn't work either:

![Image](https://github.com/user-attachments/assets/176b5302-571c-4dec-9a04-56d95fe3712a)

**Comment by tipani86** [comment]
> I played around with the settings some more and think I found the issue. The refresh seems tied to the time picker after the Grafana updates, so if it is disabled, the refresh doesn't work either:
> 
> ![Image](https://github.com/user-attachments/assets/176b5302-571c-4dec-9a04-56d95fe3712a)

Looks like curiosity was worth it. I enabled this and now the public dashboard refreshes again. Gone with the tab auto-refreshers!

You're my hero of the month :D

**Comment by juanicabanas** [comment]
Hey @Gerdofal . Thanks for reporting the issue!
[This](https://github.com/grafana/grafana/pull/95206) is the fix that will be available in Cloud in the following hours for instances in `instant` RRC

**Comment by dokugo** [comment]
Hi @juanicabanas, I see that there was a PR for fixing this issue, but I still have the same exact issue. I am using the [grafana/grafana](https://hub.docker.com/r/grafana/grafana) image with Docker Compose. If I turn on the "Time range picker enabled" option, auto-updating starts working. Docker logs show no errors.
