### ISSUE TITLE
Select Specific Metrics from JSON data

### ISSUE THREAD

**Issue by p2ya** [grafana/grafana#9071]
How can I select specific metrics from the response through Simple JSON Plugin to be used for graphing ?
At the moment when metric is selected based on target value it shows all the underling data on JSON file.

For example I have the following response:
[{'target': 'A', 'datapoints': [[539.0, 1498831200000.0], [357.0, 1501509600000.0]]}, {'target': 'B', 'datapoints': [[744.0, 1498831200000.0], [494.0, 1501509600000.0]]}]

And in Graph, Metrics , timeseries I type in A, however it graphs both A and B

**Comment by torkelo** [comment]
Use community site for questions :)
