### ISSUE TITLE
[Bug] got error on dashboard after switch orgnization

### ISSUE THREAD

**Issue by IzekChen** [grafana/grafana#9072]
Please include this information:
- What Grafana version are you using?
   * 4.4.3
- What datasource are you using?
   * influxdb
- What OS are you running grafana on?
   * redhat7.2
- What did you do?
   * for example, I open a dashboard in Main Org. Then duplicate the page on another tab.
     Now I got two page A and B. Then switch org on B page. A will get template init failed , 502 bad gateway. If you refresh A page. It will get a wired page.

   Could we open two org and work fine at the same time? 
   If not, do you think is it possible to request as a feature?

**Comment by torkelo** [comment]
Sadly using two orgs at the same time from the same account is not supported
