### ISSUE TITLE
[Bug] [MySql] Unknown macro

### ISSUE THREAD

**Issue by temamagic** [grafana/grafana#9074]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?

> latest 4.4.3

- What datasource are you using?

> mysql

- What OS are you running grafana on?

> Ubuntu 16.04

- What did you do?

> Update grafana to latest, 
In the sources I found these lines:
![image](https://user-images.githubusercontent.com/15264697/29561150-17e52f26-873d-11e7-9655-3ec071c94ba8.png)

- What was the expected result?

> I want to use $__timeFrom (and __unixEpochFilter) macro, but..
Also, $__time filter works correctly

- What happened instead?

> Unknown macro __timeFrom
and unknown macro __unixEpochFilter

- If related to metric query / data viz:
- Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by temamagic** [comment]
Oh, I correctly understood that they were added to the code just recently, but not compiled in the new version?

**Comment by daniellee** [comment]
They are in the master branch and will be included in the next major release of Grafana. They are available now as a nightly build of Grafana: https://grafana.com/grafana/download/5.0.0-8695pre1
