### ISSUE TITLE
Explore: Prometheus string labels are being converted to numeric and truncated in table view

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#90770]
Some label values are parsed as a number instead of float or string in the explore table mode.

![image](https://github.com/user-attachments/assets/30cea54d-a2d3-40ee-8c96-0c8344929a67)

For example, having any histogram metric, if the value of le=5.0 (or x.0) the table parses as int 5, thus when selecting Filter out or Filter for this value, the value included in the query is the "5" and not "5.0".

It appears that the underlying issue is that Grafana number field types truncate the values from the query, so `5.0` -> `5` inside the data frame. Thus when using the explore prometheus table to filter out data, the incorrect label is appended to the query. The [data frames being passed](https://github.com/grafana/grafana/blob/f446096eb1734d729185fda683989fb6395eb3a7/public/app/features/explore/RawPrometheus/RawPrometheusContainer.tsx#L112-L113) to the `RawPrometheusContainer` have the values cut off. Also our field types do not distinguish between [int and float numbers](https://github.com/grafana/grafana/blob/f446096eb1734d729185fda683989fb6395eb3a7/packages/grafana-data/src/types/dataFrame.ts#L14) 

Update: 
- Data that is being returned from prometheus is a string label, so the main issue here is that the prometheus results table in explore is converting the string label into a number for some reason.

<img width="531" alt="Screenshot 2024-07-18 at 5 06 17 PM" src="https://github.com/user-attachments/assets/c241be0a-e16f-4cdf-b626-3b655bcb714b">

[Replicating number precision issue in data frames-1721343548543.json](https://github.com/user-attachments/files/16289907/Replicating.number.precision.issue.in.data.frames-1721343548543.json)

Related to https://github.com/grafana/support-escalations/issues/11162

**Comment by nberkley-gp** [comment]
So the issue isn't just the filter button, it's also that it displays the wrong label so even manually iterating on the query is extremely cumbersome. The only way to figure out the actual label value so I can add it to my query is to go into dev tools and inspect the response from the datasource.

> The [data frames being passed](https://github.com/grafana/grafana/blob/f446096eb1734d729185fda683989fb6395eb3a7/public/app/features/explore/RawPrometheus/RawPrometheusContainer.tsx#L112-L113) to the RawPrometheusContainer have the values cut off. Also our field types do not distinguish between [int and float numbers](https://github.com/grafana/grafana/blob/f446096eb1734d729185fda683989fb6395eb3a7/packages/grafana-data/src/types/dataFrame.ts#L14)

This feels like it misses the point a bit: Label values are strings, not numerics of any kind. As soon as you've converted to a numeric type, you've lost all ability to reconstruct the actual label value ("0x2", "2", "2e1", etc. are all going to map to the same number). I get why you'd want the ability to force a numeric interpretation for table formatting, but doing so by default seems wrong, especially for the raw view.

**Comment by jasuade** [comment]
Potential fix and investigation: https://github.com/grafana/grafana/pull/91662
