### ISSUE TITLE
[New Data Source] Amazon Managed Prometheus

### ISSUE THREAD

**Issue by josiahg** [grafana/grafana#90777]
This is officially [released](https://grafana.com/grafana/plugins/grafana-amazonprometheus-datasource) as 1.0!

**Comment by jangaraj** [comment]
Why AMP needs a dedicated datasource? I already use it with standard Prometheus datasource with AWS Signature Version 4 (SigV4) (assumed IAM role) authentication.

**Comment by josiahg** [comment]
Great question @jangaraj !

The Prometheus data source was originally designed to support Prometheus, which only existed in one "flavor" when we created it.

As the Prometheus has grown in popularity, there are many Prometheus flavors/hosting options - each of which may have it's own unique features/functions and authentication schemes.

This led to a lot of different features and functions being added to the Prometheus data source, which weren't actually core to Prometheus itself.

So, Grafana Labs has decided to pull these services out into their own data sources.

This also helps make it clear to users whether a service is fully supported in Grafana - if there is a standalone data source for the service, Grafana stands behind and ensures compatibility when connecting to that service.

**Comment by josiahg** [comment]
This has been [released](https://grafana.com/grafana/plugins/grafana-amazonprometheus-datasource/)
