### ISSUE TITLE
[Bug] Singlestat: Do not show decimal places, when displaying 100%.

### ISSUE THREAD

**Issue by JohannesAtGit** [grafana/grafana#9079]
Please include this information:
- What Grafana version are you using? 4.4.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubuntu
- What did you do?
Create a Singlestat panel
Query: SELECT * FROM "bla.status.value" WHERE $timeFilter fill(null)
Options:
Value: Stat avg
Unit: percent(0.0-1.0)
Decimals: 2

- What was the expected result?
100%

- What happened instead?
100.00%

The problem is, if I change  the decimals option to auto.
It shows 100.0%, but the actual output should be e.g. 99.97%

If I change the decimal option to 0.
It shows 100%, but the actual output should be 99.97%

**Comment by torkelo** [comment]
please include the raw data returned from your metric query: without that it's hard to say its a bug or not. 

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by torkelo** [comment]
closing for lack of updates / data to replicate

**Comment by samirmajen** [comment]
Hi guys, this is an actual issue. To recreate:

- Create a singlestat dashboard panel
- Under Options set 'Decimals' to 2
- Set 'Unit' to 'Percent 0-100'
- Return a value of anything other than 100 and you get the desired effect e.g. value is returned as 99.99%, 98.06% and so on, however if value is 100 you get 100.00% when it should just be 100%

**Comment by darkl0rd** [comment]
I ran into the same issue. When selecting the "Percent" unit, it should either by default take decimals into account (e.g. 99.97 should not be rounded to 100) - or as @samirmajen points out, when explicitly specifying the amount of decimals, all zero's should not be shown, e.g. 100, not 100.00.
