### ISSUE TITLE
DashboardScene: Some options in Gauge panel do not rerender panel

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#90805]
When in panel edit on a gauge panel, options like `Show threshold markers` and `Show threshold labels` do not rerender the panel when changed. Clicking refresh is a workaround for this, but ideally we want to just switch the toggle and visualize the changes, similar to other options (e.g.: orientation)

**Comment by ivanortegaalba** [comment]
This already works in latest Scenes version
