### ISSUE TITLE
[Bug] Incorrect names of the rows on the snapshot using variables

### ISSUE THREAD

**Issue by Schumbria** [grafana/grafana#9080]
_Grafana 4.3.3
InfluxDB
Grafana is running on Win2008 R2 64bit_

**What did I do:**
1. Create variable "srvrs", Type = Query
as:
$srvrs: SHOW TAG VALUES WITH KEY = "srvrs" , with options: Multi-value, Include All option
2. Create Row with Title = $srvrs 
and Repeat for = srvrs
3. Select two or more values (or "All") for "srvrs" 
4. Make a Snapshot
5. Look on the Row title on Snapshot

**What was the expected result:**
Title of every Row matches with value for every Raw (one srvrs for one Row Title)

 **What happened instead:**
On the snapshot all Row have the same name: "All" or list of values srvrs.

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630). We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
