### ISSUE TITLE
[Feature request]  Snapshot api via name/timestamp

### ISSUE THREAD

**Issue by Geekaylee** [grafana/grafana#9081]
Currently to create a snapshot via a POST to /api/snapshots it is required that the user passes the full dashboard data model to store.

It should be possible for the API to take a dashboard name and a set of from/to values and create the data model itself.  Alternatively the GET /api/dashboards/db/:slug request should be extended to return the full data model to insert into the /api/snapshots POST request

For more complex dashboards the overhead required to maintain the ability to use /api/snapshots programmatically far out ways the benefits provided, however I would love the ability to insert iframe snapshots into auto-generated reports rather than being stuck using the /render endpoint!

**Comment by torkelo** [comment]
This is currently not possible as the data a snapshot contains is collected in the frontend where all the panels and visualizations live. So to do this in the api we would need to load the dashboard in a headless browser (like we do for the panel render api). 

Maybe this can be done some time in the future but unlikely , maybe when we expand grafanas reporting features.

**Comment by tatumsu** [comment]
so if this is not possible from server side, can we update the document to reflect the limitation there?

**Comment by tatumsu** [comment]
so if this is not possible from server side, can we update the document to reflect this? current the API document is not very clear about how to create a snapshot with metric data, if we can provide more information there, it will he helpful.

**Comment by tatumsu** [comment]
so if this is not possible from server side, can we update the document to reflect this? current the API document is not very clear about how to create a snapshot with metric data, if we can provide more information there, it will he helpful for the people who read the document for the first time(without searching the issue list:)).

**Comment by Geekaylee** [comment]
@tatumsu 
We've moved away from using snapshots now, but at the time I looked into it my solution was to selenium in a headless browser to automate the snapshot process. I believe I used puppteer.
https://github.com/GoogleChrome/puppeteer
