### ISSUE TITLE
[Bug] CSV separator fix not present anymore in Grafana 4.4.2

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#9083]
In the past we had problems reading exported CSV files in Excel due to the ";" separators, see: https://github.com/grafana/grafana/issues/2401

This was solved with pull request: https://github.com/grafana/grafana/pull/5325

However in Grafana 4.4.2 this fix is gone and the CSV files are now not loading properly anymore in Excel

**Comment by PaulKuiper** [comment]
See: https://github.com/grafana/grafana/blob/c17d02e4963e2921a9d41881dcdb205d184b2481/public/app/core/utils/file_export.ts

The "sep=;/n" code is not present anymore

**Comment by daniellee** [comment]
Hmm, tricky. I removed it on purpose (https://github.com/grafana/grafana/commit/c17d02e4963e2921a9d41881dcdb205d184b2481) as it messed up the export for other spreadsheet programs that were not Excel (Google Sheets and LibreOffice).

In LibreOffice:

![image](https://user-images.githubusercontent.com/434655/29615589-bf679a5a-880e-11e7-8a03-158bfcb97d9b.png)

In Google Docs:

![image](https://user-images.githubusercontent.com/434655/29615686-20b19e3c-880f-11e7-86cc-f1cee2f0940c.png)

Think the solution (unfortunately), is to add an "Export to Excel checkbox".

**Comment by daniellee** [comment]
The fix will look like this for the graph panel:

![image](https://user-images.githubusercontent.com/434655/29617333-d96a6e7c-8814-11e7-8c9f-64735b13bbb8.png)

and this for the table panel:

![image](https://user-images.githubusercontent.com/434655/29617366-f25fdd40-8814-11e7-91fb-c7375c8a4845.png)

**Comment by PaulKuiper** [comment]
Hi Daniel,

Fast work, nice :-)
I would perhaps rephrase the label to "Excel dialect"

You might even consider an "Dialect" dropdown box with "RFC4180", "MS-DOS", "Excel" in case you want to support more CSV dialects in the future (see http://specs.frictionlessdata.io/csv-dialect/)

**Comment by meyerder** [comment]
So I spent a hour or so trying to hack up some of the files listed in the various threads to no joy... this works for graphs but does not work for tables... any suggestions how to fix it for tables?

**Comment by daniellee** [comment]
@meyerder can you explain what you are trying to do?

BTW, renamed the label to "Excel CSV Dialect" which will be included in the upcoming 4.6 release.
