### ISSUE TITLE
[Feature request] Allow queries for Threshold lines

### ISSUE THREAD

**Issue by SuperQ** [grafana/grafana#9084]
Please include this information:
- What Grafana version are you using?
4.4.3

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Linux

Prometheus provides some analytics queries, like `quantile_over_time()`. The can be used as "instant" queries that give you one value that could be used to set a Thresholds line. 

A common use case for this would be to display the "95th Percentile" on network graphs.

**Comment by miton18** [comment]
+1

**Comment by davkal** [comment]
@SuperQ could you elaborate?

To draw static lines you can simply use `123` as a PromQL query. For dynamic lines, does something like [quantile_over_time(0.5, scrape_duration_seconds[5m])](http://demo.robustperception.io:9090/graph?g0.range_input=3600s&g0.end_input=2018-05-14%2011%3A01&g0.step_input=undefined&g0.stacked=0&g0.expr=quantile_over_time(0.5%2C%20scrape_duration_seconds%5B5m%5D)&g0.tab=0) do the trick?

**Comment by SuperQ** [comment]
One thing to note, this could be partly solved with an instant query in the Metrics, but currently in the Graph panel, instant queries show up in the Legend, but don't draw anything on the graph.

**Comment by SuperQ** [comment]
This is now easy to get the data using `$__range`, but even with null point "connected", no line is shown.

**Comment by vishnubraj** [comment]
+1

**Comment by limberger** [comment]
+1

**Comment by odiraneyya** [comment]
+1

**Comment by Suraxius** [comment]
+1. Please bring it back! Migration to new Time series makes no sense without this.

**Comment by genefever** [comment]
+1, this is important!
