### ISSUE TITLE
this user requires mysql native password authentication

### ISSUE THREAD

**Issue by rnkhouse** [grafana/grafana#9086]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
v4.4.3
- What datasource are you using?
MySQL
- What OS are you running grafana on?
Linux
- What did you do?
Trying to connect Azure MySQL database with provided hostname and username and password. Username contains `@` by default which is Azure default username policy.
- What was the expected result?
Successfully connect to database.
- What happened instead?
Error: this user requires mysql native password authentication.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/8618

**Comment by Tian-MC** [comment]
> fixed by #8618

how
