### ISSUE TITLE
[Bug] Browsers on Mac shown "Nan.nfinity" instead of 0.

### ISSUE THREAD

**Issue by selina2017** [grafana/grafana#9087]
- What Grafana version are you using? 
Grafana version 4.4.3

- What datasource are you using?
InfluxDB

- What OS are you running grafana on? 
ubuntu

- What did you do?
We use Grafana to show value and percentage under a pie chart. 
When the collected data's summation is all 0, then the values shown "Nan.nfinity" instead of 0 on Mac even though the percentage column shown 0%.

<img width="194" alt="screen shot 2017-08-23 at 5 20 09 pm" src="https://user-images.githubusercontent.com/31295632/29644003-baca5ab4-8827-11e7-8102-5dbfaf2dbd3f.png">

If there is at least one non-zero number (e.g. '1'), it will show value.
In Windows PC, it shown 0 correctly.

- What was the expected result?
Mac should show 0 when the summation of data is 0.

- What happened instead?
Mac show "Nan.nfinity" instead of 0.

I saw that there is a related issue filed before which has been fixed. However, the fix may apply to Windows PC only.
https://github.com/grafana/grafana/issues/1039

- If related to metric query / data viz:

SELECT sum("StrNum") / 1000 FROM "ABC" WHERE "site" =~ /^$site_name$/ AND $timeFilter
StrNum is string type in influxDB, but data are all numbers.
When all StrNum = "0" it will show NaN.infinity on Mac but Windows PC is ok
If there is at least one nonzero (e.g., "1"), it will show value

  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
please use numeric values in InfluxDB not string values with numbers in them :)
