### ISSUE TITLE
Network: Grafana 11.1.0 attempts to connect to grafana.com every day

### ISSUE THREAD

**Issue by mroach** [grafana/grafana#90878]
### What happened?

Grafana is trying to connect to `grafana.com` for an HTTPS request about once a day.

We strictly control network egress from our environment and only allow egress to hostnames and ports that are necessary for business operations. As such, our Grafana is configured with the following to disable the default egress behaviour:

```
GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
GF_ANALYTICS_CHECK_FOR_UPDATES=false
GF_ANALYTICS_FEEDBACK_LINKS_ENABLED=false
GF_ANALYTICS_REPORTING_ENABLED=false
GF_SECURITY_DISABLE_GRAVATAR=true
```

Since upgrading from 10.4.2 to 11.1.0, I'm now seeing network egress violation logs for Grafana trying to connect to `grafana.com` on port 443. 

The cadence of it appears to be a timer of roughtly 26 hours and 20 minutes

```
2024-07-12 16:57
2024-07-13 19:18
2024-07-14 21:39
2024-07-15 23:59
2024-07-17 02:20
2024-07-18 04:41
2024-07-19 07:02
2024-07-20 09:22
2024-07-21 11:43
2024-07-22 14:04
2024-07-23 16:25
```

I found an error log from Grafana that lines-up with these times (above timestamps are UTC+2, below are UTC, so they line-up)

```
logger=plugin.angulardetectorsprovider.dynamic
t=2024-07-23T14:25:12.729228861Z
level=error
msg="Error while updating detectors"
error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

I have a feeling this is caused by https://github.com/grafana/grafana/pull/84723

### What did you expect to happen?

Grafana not to attempt any external network connections.

### Did this work before?

Yes, 10.4.2 did not exhibit this behaviour.

### How do we reproduce it?

1. Run Grafana 11.1.0 with the ENV config noted above
2. Monitor outgoing traffic for 2 days

### Environment (with versions)?

Grafana: 11.1.0
OS: Base `grafana/grafana-oss` Docker image
Browser: Sever-side issue

Plugins:
* grafana-clock-panel
* grafana-polystat-panel
* savantly-heatmap-panel
* marcusolsson-treemap-panel

**Edit (2024-07-24):** I realised we're not using `savantly-heatmap-panel`, so I removed it. If things change, I'll update the issue.

### Grafana platform?

Kubernetes

**Comment by tolzhabayev** [comment]
Hey @mroach, 
thanks for flagging this behaviour - we already have a change incoming (in 11.2) https://github.com/grafana/grafana/pull/91194 that will make this call respect the ```[analytics].check_for_plugin_updates``` setting.

**Comment by tolzhabayev** [comment]
Closing as 11.2 is out

**Comment by mroach** [comment]
@tolzhabayev Thanks for the fix and updating me about this. Nice! :)
