### ISSUE TITLE
RBAC: role picker goes offscreen on the Service Account page

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#90879]
### What happened?

The detailed role picker appeared offscreen on the Service Accounts page with the hamburger menu open at 1459x860px resolution.

https://github.com/user-attachments/assets/08feacaa-4db6-46fb-b479-1cf07a6fa8a8

<img width="1507" alt="Screenshot_2024-07-24_at_11_21_08 AM" src="https://github.com/user-attachments/assets/ea6436da-3c1e-4345-9101-e5a077118830">

### What did you expect to happen?

See the full role picker

### Did this work before?

It works on other pages - looks like just a FE rendering issue.

### How do we reproduce it?

1. Create a new service account /org/serviceaccounts/create
2. Open the main side nav hamburger
3. Click on the Role field to open the role picker
4. Hover over a role to open its permissions

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v11.2.0-72125 (b9812a0784)
OS: Mac OS Sonoma
Browser: Chrome

My resolution is about 1459x860px

### Grafana platform?

I use Grafana Cloud

**Comment by mjseaman** [comment]
@Clarity-89 @Jguer FYI, not urgent

**Comment by aarongodin** [comment]
relevant frontend platform issue: https://github.com/grafana/grafana/issues/90927

**Comment by mvv-dvb** [comment]
Same here. Only way to fix this is by zooming out to a very small size, or use a very large screen with a huge resolution.
