### ISSUE TITLE
Bug : QueryField suggestions is missing style (background) in v11.1

### ISSUE THREAD

**Issue by cyrsep** [grafana/grafana#90872]
### What happened?

I am working on a datasource plugin, using QueryField with suggestions mecanism (onTypeahead).
On upgrading from grafana v10.4 to v11.1, the background of the QueryField suggestions div turned to transparent.
![image](https://github.com/user-attachments/assets/bb6f1412-f58f-44c0-af78-f58f92fbd24a)

It is related to the recent SASS updates on Typeahead classes.

### What did you expect to happen?

Here is the expected result
![image](https://github.com/user-attachments/assets/70ccfb23-f0e9-42c0-8b23-67fec8c398a7)

### Did this work before?

Working as expected on Grafana up to v11.0.0

### How do we reproduce it?

This seems to apply to any usage of QueryField with 'onTypeahead' callback

### Environment (with versions)?

Grafana: v11.1 OSS
OS: Docker, Windows, Debian 12
Browser: Firefox 128, Chrome 116

### Grafana platform?

None

**Comment by mckn** [comment]
This sounds like a side effect from the scss migration done in this [PR](https://github.com/grafana/grafana/pull/88484)

**Comment by cyrsep** [comment]
Issue is fixed on v11.1.5 - docker - windows
Issue is fixed on v11.2 - docker

Issue is not fixed on v11.2 - windows

**Comment by mckn** [comment]
> Issue is fixed on v11.1.5 - docker - windows Issue is fixed on v11.2 - docker
> 
> Issue is not fixed on v11.2 - windows OSS - Grafana v11.2.0 ([c57667e](https://github.com/grafana/grafana/commit/c57667e4481563f5e6cf945b03bc0626caa4dbeb))

@ashharrison90 do you know about the `v11.2` version?

**Comment by ashharrison90** [comment]
@mckn my guess is it missed the cut off for 11.2.0, i don't see it mentioned in the changelog either: https://github.com/grafana/grafana/releases/tag/v11.2.0

so it will go out in 11.2.1 i suppose 🤔

**Comment by mckn** [comment]
Thanks for helping out here @ashharrison90 🙏🏻
