### ISSUE TITLE
iphone 12  Safari Browser not work at v10.3.5 v11.0.1

### ISSUE THREAD

**Issue by will007** [grafana/grafana#90894]
### What happened?

iphone 12  Safari Browser not work at v10.3.5 v11.0.1
![grafana-bug](https://github.com/user-attachments/assets/67d4bae7-3e11-4ee8-a9db-ae9c2df1cf33)

### What did you expect to happen?

iphone 12  Safari Browser not work at v10.3.5 v11.0.1

### Did this work before?

iphone 12  Safari Browser not work at v10.3.5 v11.0.1

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 11.0.1
OS: 15
Browser:

### Grafana platform?

A downloaded binary

**Comment by will007** [comment]
check grafana v9.5.19 is support

**Comment by tonypowa** [comment]
Hi @will007 

Thank you for opening this issue.

To assist you better, could you please provide some additional details that would help us reproduce the problem on our end? This will allow us to investigate and resolve the issue more efficiently.

Any specifics you can share would be greatly appreciated.

**Comment by ashharrison90** [comment]
please see comment [here](https://github.com/grafana/grafana/issues/90157#issuecomment-2291181000)

iphone 12 will work on iOS 16
