### ISSUE TITLE
RolePicker positioned incorrectly with `bodyScrolling`

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#90927]
> Regarding the bodyScrolling change, we are observing that the role picker behavior is broken, and it seems related to document layout. If you open the role picker (e.g. on the users list page), the frame for selecting roles is positioned after the main content. I'm doing what I can to triage the issue but am not sure whether a change to the role picker or to the other layout components is appropriate

Enterprise only

![image](https://github.com/user-attachments/assets/c5b24a34-5977-45cc-97e2-6a8cbd436d2d)

![image](https://github.com/user-attachments/assets/b59ae696-b74e-4552-b120-4a8d6a7bec9e)

Looking at the RolePicker, it looks like it does a bunch of custom positioning, which probably is not longer correct when the bodyScrolling toggle is enabled.

We should refactor this to use Floating UI for this popover.

**Comment by aarongodin** [comment]
Relevant issue for frontend platform: https://github.com/grafana/grafana/issues/90927
