### ISSUE TITLE
Does Grafana support to connect pub/sub data sources?

### ISSUE THREAD

**Issue by northtree** [grafana/grafana#9092]
I would like to connect Grafana with pub/sub data stream for creating realtime dashboard, instead of setting refresh rate on seconds to pull the data.

Does Grafana support this feature or provide data/api entries for developing plugin?

Thanks.

**Comment by torkelo** [comment]
yes, the datasource query method can return a promise to a RxJS subject, this subject can be used by the data source to stream data to the panel. 

There is however no documentation for how to do this and no good example beside this:
https://github.com/raintank/snap-app/blob/master/src/datasource/datasource.js#L108
