### ISSUE TITLE
BrowseDashboards empty page with `bodyScrolling` in Safari

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#90930]
Reported https://raintank-corp.slack.com/archives/C036J5B39/p1721867944029689

In macOS Safari, BrowseDashboards displays an empty page with the bodyScrolling feature toggle enabled. I have not verified this myself.

Suspect AutoSizer fails to get full height to display anything.

**Comment by tskarhed** [comment]
The request to `/folders?page=1&limit=50` is never made with the feature flag.
