### ISSUE TITLE
Grafana Dashboards: No title being displayed on the grafana dashboard list, shows "Missing Title" as the title 

### ISSUE THREAD

**Issue by PratyushK-22** [grafana/grafana#90933]
### What happened?

 Upgraded my Amazon Managed Grafana from version 9.4.7 to 10.4.1 and observed that one of my dashboard had no title. When tried to click on it within the folder view, it did not open. When I tried using the list view , I observed that the same dashboard had the "Missing Title" as the title and it was accessible. 
 
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/363de25d-0a35-4f69-87a7-a17e948c9762">

### What did you expect to happen?

I expected that the dashboard would display the original title instead of the " Missing Title" .
Also if there is already a value against the dashboard title it should display the same.
![image](https://github.com/user-attachments/assets/ab7784fe-5117-4ef0-a073-9758870a6873)

### Did this work before?

This worked fine within the Grafana Version 9.4.7 in Amazon Managed Grafana

### How do we reproduce it?

1.  I am unaware if this is reproducible using certain conditions but I have an entire json that lets me reproduce the same
2.
3.

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 10.4.1
OS: Windows 11, Version 23 H2
Browser: Chrome Version 127.0.6533.72 (Official Build) (64-bit)

### Grafana platform?

Other

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
closing in favor of https://github.com/grafana/support-escalations/issues/11774

**Comment by skpgituser** [comment]
@tonypowa .. I'm having similar issue and unable to open the support-escalation link. Can you help?
