### ISSUE TITLE
[Feature Request] Dashboard-level alerting

### ISSUE THREAD

**Issue by song860918** [grafana/grafana#9097]
I searched online and it seems this feature doesn't exist. Right now you can add an alert channel to a single graph or make alert channel default so that it applies to all channels. But there is no way to add an alert channel at the dashboard level. It seems to be very useful if there is a way to configure dashboard-level alert.

Please include this information:
- What Grafana version are you using? -- 4.4.2
- What datasource are you using? -- Graphite/InfluxDB
- What OS are you running grafana on? -- Ubuntu

**Comment by torkelo** [comment]
Not sure dashboard level channels (alert notifications) make any sense as these are slack/email/pagerduty integrations that you define once and reuse across dashboards & alerts
