### ISSUE TITLE
[Feature Request] Alert should support multiple conditions to different channels.

### ISSUE THREAD

**Issue by duke-cliff** [grafana/grafana#9098]
Please include this information:
- What Grafana version are you using? //4.4.3
- What datasource are you using? //Cloudwatch/NewRelic/Influxdb
- What OS are you running grafana on? //Docker
- What did you do? //Coding
- What was the expected result? //

I am hoping in panel alert setting. It should allow user to set multiple conditions and each condition might go to different notification channels.
E.g. If CPU > 80 and < 90 go to slack channel.
       If CPU >= 90 go to pageDuty channel.

- What happened instead? //
Feature not supported. Ugly workaround, we have to clone the same panel for multiple alert conditions.

**Comment by torkelo** [comment]
Similar / related to this issue: https://github.com/grafana/grafana/issues/6696

**Comment by bergquist** [comment]
I think notifications on warning is bad practice when it comes to alerting. In almost all companies Ive worked/talked to, a warning is just noise that people don't care about. I don't want Grafana to encourage that behavior. 

We might add support for notifications for warnings/pending in the future but this is not how we will solve it. So I'm closing this.
