### ISSUE TITLE
[Bug] can't get EC2 tags using cloudwatch integration

### ISSUE THREAD

**Issue by adeck** [grafana/grafana#9100]
[This documentation][docs] on using the CloudWatch datasource is inaccurate.
It states:

```
Tags can be selected by prepending the tag name with Tags.

Example ec2_instance_attribute() query

ec2_instance_attribute(us-east-1, Tags.Name, { "tag:Team": [ "sysops" ] })
```

...However when I actually try `ec2_instance_attribute($region, Tags, { "tag:Name": [ "*" ] })` I get `[{"Key":"Description","Value":"Managed by terraform"},{"Key":"Name","Value":"gw-infra"}]`, and when I try with `Tags.Name`, I understandably get nothing because the tags aren't arranged as a dict, they're arranged as a list of dicts.

Using `grafana` version 4.4.3 on debian stretch.

[docs]: http://docs.grafana.org/features/datasources/cloudwatch/

**Comment by torkelo** [comment]
try Grafana v5 nightly 
https://github.com/grafana/grafana/pull/8307
