### ISSUE TITLE
[Bug] API inputs not validated on datasource create

### ISSUE THREAD

**Issue by adeck** [grafana/grafana#9101]
My grafana version is `4.4.3`.

This...
```
POST /api/datasources HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.12.4
Content-type: application/json
Content-Length: 373
Authorization: Basic XXXXXXX

{"name": "local_cloudwatch", "basicAuthPassword": null, "database": null, "url": "", "basicAuth": null, "jsonData": "{authType: \"arn\", timeField: \"@timestamp\", defaultRegion: \"us-west-1\"}", "access": "proxy", "typeLogoUrl": null, "user": null, "tlsAuth": null, "basicAuthUser": null, "password": null, "type": "cloudwatch", "isDefault": true, "withCredentials": null}

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Sat, 26 Aug 2017 04:32:05 GMT
Content-Length: 63

{"id":2,"message":"Datasource added","name":"local_cloudwatch"}
```
...should not have succeeded.
Really, there are two bugs, here.

The first bug is that clearly no validation happens of the JSON received from the API call; it just gets put somewhere verbatim. That's bad. From a usability perspective, that's bad, because it doesn't let you know when something's malformed.

The second bug is that, after making this call, if you try to look at the datasource list in the UI, nothing loads and you get an unhappy orange box telling you a problem occurred. Which takes this from being a concerning possible security flaw to a DoS vulnerability that's easy to trigger.

Incidentally, this pathological edge case wasn't manually crafted- I was using the `grafana4_datasource` salt state. That module has a bug where it sends all those nulls. I'll be opening a PR for that soon, but in that's a different bug in a different project.

OTBS, the datasource still works for creating dashboards.

**Comment by adeck** [comment]
https://github.com/saltstack/salt/issues/43200 <-- linking to create relationship between tickets.

**Comment by torkelo** [comment]
thanks for reporting this! will fix!

**Comment by torkelo** [comment]
strange, tried to replicate this without any success. The data source list loads fine. 

```
curl -X POST -u admin:admin -v -d '{"name": "local_cloudwatch", "basicAuthPassword": null, "database": null, "url": "", "basicAuth": null, "jsonData": "{authType: \"arn\", timeField: \"@timestamp\", defaultRegion: \"us-west-1\"}", "access": "proxy", "typeLogoUrl": null, "user": null, "tlsAuth": null, "basicAuthUser": null, "password": null, "type": "cloudwatch", "isDefault": true, "withCredentials": null}'  -H 'Content-type: application/json; charset=utf-8' http://localhost:3000/api/datasources
```

the only required fields are name, type and access. jsonData a generic options store for plugins and is up the data source plugin and can be anything so there can be no validation of the properties inside it (as the data source plugin is frontend only).

What error did you get in the data source list?
