### ISSUE TITLE
[New Data Source]: <name-of-service>

### ISSUE THREAD

**Issue by SandeepRa1** [grafana/grafana#91025]
### Background

Dashboard visualization of csv

### Use case

Dashboard visualization of csv

### Contribution

- [ ] Are you looking to create the plugin?
- [X] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi @SandeepRa1 - there are two plugins which already support CSV files https://grafana.com/grafana/plugins/all-plugins/?search=csv as such it's unlikely that we'd accept another into the catalog without there being significant differentiation. I'll close this issue but please feel free to reopen if there is more to add
