### ISSUE TITLE
REQ: Add ability to create drilldown dashboards through facets

### ISSUE THREAD

**Issue by nicholashagen** [grafana/grafana#9102]
One of the ways I'd love to be able to view dashboards is by automatically drilling down without needing to setup a ton of custom dashboards.  In other words, I want to start from a very generic dashboard where all I see is an aggregation of metrics rolled up to the datacenter level.  I then want to be able to select a specific datacenter and see a rollup of a list of regions, then a list of az's, all the way down to the list of hosts.  So, for example, I might have a dashboard such as:
```
[CPU Graph]    [Req/Sec Graph]    [Error Rate]
```
When initially viewed, I'd want 2 series on each of those graphs resembling the AWS regions.  So I'd see CPU for `us-east-1` and `us-west-1` which would be the averages of all metrics tagged with that region.  Essentially, it would automatically add a tag for `region.name = *`

From there I'd be able to see that one region had a particularly high error rate and want to drill down to specifically where it was occurring.  So I would then be able to select the specific region and see all availability zones within that region.  By selecting `us-east-1` for example, all graphs would immediately update to now showing a series for each AZ.  So the CPU graph would switch from 2 series for each region to 3 series for `us-east-1a`, `us-east-1b`, and `us-east-1c`.  

Once again, I'd be able to see that `us-east-1b` was the main culprit for the error rate.  So I'd then select it and get a series for each host within that region.  This could continue as far as the customer wanted to have their drilldown defined.

Essentially what is happening is grafana is automatically adding and applying tags to each graph as the facets are selected.  The facets would be managed by one or more select boxes.  This could either be something such as:

`Facet:  [All Regions |v]`
`Facet:  [us-east-1 |v]   [All AZs |v]`
`Facet:  [us-east-1 |v]   [us-east-1b|v]  [All Hosts |v]`

where initially the `All` is selected and each time a specific selection is made it adds the next level of the drill down.  It could also just be a multi-level menu such as:

```
Facet:  [ All Regions
               us-east-1      >     All AZs
                                             us-east-1a     >     All Hosts
                                                                            ip-10-11-12-13
```

For the setup and definition of the Facets, I'd imagine something like this:

```
Facet Setup

Name:    [ Region           ]
Tag:        [ region ]
Type:     [ dynamic     | v]
Expr :      [ select value from tags where name = 'region' ]

[Add Facet]
```

If `Type` is `dynamic` then it would allow a custom query `Expr` to define the list.  If it was `Static` then it would be a comma-separated list of values.

Once the facet is setup, it would then allow the next level of facet to be defined for each of the values in the initial facet.  If the facets are `dynamic`, then you would just keep building dynamic facets such as:

```
Name:   [ AZ          ]
Tag:      [az ]
Type:    [dynamic |v]
Expr:     [select value from tags where name = 'az' and region=$tag_region]
```

The `tag_region` variable could become available, since that tag would have been applied already.

The `tag` itself is what is dynamically added to each Graph.  When `All` is selected it sets the value to `*`.  When a specific value is selected it sets the tag accordingly and the next tag is dynamically added as `*`.

Once setup, each graph would have to be setup to use facets.  Graphs should be allowed to be facetable or not.  A simple checkbox could support this:

```
Facet:  [  ]
Tags:  app.name = $app
```

If selected, Grafana would dynamically apply the tags as the facets change.  The graph names/aliases for the series could use the variable `$facet` to be the current dynamic tag name.  For example, initially `All Regions` would be selected so `$facet` would be equivalent to `$tag_region` or `us-east-1`/`us-west-1`.  Once a specific region was selected the `$facility` would change to become equivalent to `$tag_az` for example.

When being viewed on the dashboard, the actual series themselves within the legend could contain an icon that when clicked would automatically select that facet.  For example:

```
us-east-1 [^]
us-west-1 [^]
```

If the icon next to `us-east-1` is clicked it would select it as the facet and `All AZ` would be selected making the series become `us-east-1a`, `us-east-1b`, etc.

Lots of this is already available within Grafana and the various datasources.  It's just the ability to dynamically update the graphs and change the tags without have to update each graph or create multiple dashboards.

**Comment by torkelo** [comment]
Interesting, good scenario description. Grafana does support add hoc filters (for some data sources, like Elasticsearch & InfluxDB). 

And your definition looks very much like normal template variables. They can also be nested like you describe. 

you could do much of what you describe right now with template variables and drilldown links and series of dashboards.

**Comment by nicholashagen** [comment]
It looks like https://github.com/grafana/grafana/issues/1232 would also solve the issue.  Basically just need a way to make the legend items be clickable and pass through their value.  I'd still prefer the dashboard to update in place but having the legend item link to the next dashboard would be good as well.

**Comment by torkelo** [comment]
ok, closing this in favor of https://github.com/grafana/grafana/issues/1232 as that is definitively something we want to implement, while this seems very unlikely
