### ISSUE TITLE
Pressing e to edit panel frequently enters the wrong panel

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#91078]
### What happened?

Mousing over a panel and pressing "e" is supposed to go into the edit page for it. It now frequently enters the wrong page.

Video example of issue.
https://github.com/user-attachments/assets/f6e7005a-7b5e-428e-a474-cc6a3cab4336
Examples of entering the wrong panel are at: **12 seconds, 19 seconds, 31 seconds.** 

In the video I use this dashboard
https://play.grafana.org/d/dea43745-7fac-4bf4-85d0-d06b168de92b/5ada39be-866c-51c5-ae0c-f514df881f41?orgId=1

### What did you expect to happen?

Goes to the right page.

### Did this work before?

Yes. Last version I used was 10.2 and did not see this behaviour. 

### How do we reproduce it?

1. go to any dashboard with multiple panels 
2. mouse over a panel and press "e" to edit it. Frequently it will edit the wrong panel.
3. press e to exit editing the panel
4. repeat

### Environment (with versions)?

Grafana: 11.1, 11.2 (play.grafana.org)
OS: MacOS, Windows
Browser: Firefox, chrome

### Grafana platform?

Kubernetes

**Comment by bob454522** [comment]
this is the same issue i described in this issue post:
https://github.com/grafana/grafana/issues/90020

i THINK its going to be fixed in v11.3.0 (im not sure, but basing that on this merge):
https://github.com/grafana/scenes/pull/867
