### ISSUE TITLE
Relative time range in widgets

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#9107]
Hello

It would be nice to be able to convert any displayed date in relative dates for some widgets.

For example: 
- the singlestat widget can only display a number but it would be nice if it could display the last time an event occured in a relative way (ex: Last successfull payment: 3 min ago)

- we could apply the same principle with data tables. For example we could display a datatable like this

| supplier | Last succeeded call |
| --------- | --------- |
| supplier1 | 3 min ago |
| supplier2 | 12 min ago |

It could be applied to different widgets.

Displaying the last time an event occurred could be very useful in a lot of dashboards.

What do you think?

Regards
Jeremy

**Comment by torkelo** [comment]
Sounds like a very useful feature!

https://github.com/grafana/grafana/issues/2764

https://github.com/grafana/grafana/issues/6710

**Comment by nemenemsrouge** [comment]
I come back to this issue again: the 2 other Feature Request you linked are really promising.

But don't forget the "table" widgets

![image](https://user-images.githubusercontent.com/6534850/30152010-01501e8e-93b2-11e7-8bfd-701d714256be.png)

![image](https://user-images.githubusercontent.com/6534850/30152032-1326c572-93b2-11e7-8483-d198ceed8b82.png)


In this example, the "Last" column would be so much better with a relative time format.
It would be nice if we could choose "relative" in the "Date format" selector.

We could use something like http://momentjs.com/  to do the job easily
