### ISSUE TITLE
[Bug] Alert:  "Query Returned No Series" for influxdb moving_average query.

### ISSUE THREAD

**Issue by CptanPanic** [grafana/grafana#9108]
I have created a metric query that uses influxdb moving_average().  The data shows up fine in graph, but I cannot trigger an alert with it, and get "Condition: Eval: false, Query Returned No Series (reduced to null/no value)" Here is metric query: "SELECT moving_average("profitability", 360) FROM "mining" WHERE "miner" = 'nicehash' AND $timeFilter "

Please include this information:
- What Grafana version are you using?   Grafana v4.4.1 (commit: 6a9f8ca) 
- What datasource are you using? Influxdb
- What OS are you running grafana on? Ubuntu 16.04

**Comment by torkelo** [comment]
And if you hit Test Rule and click to expand the output log that shows what influxdb is returning what does that show? 

maybe the time range for the alert query is to low?

**Comment by CptanPanic** [comment]
Test Alert: result

    firing true
    state alerting
    conditionEvals true = true
    timeMs 2.734ms
    logs
        0
            message Condition[0]: Query Result
            data
        1
            message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
            data null

Query conditions:
last() of query(F,1s,now) is below .5

**Comment by daniellee** [comment]
That looks like you are alerting on the latest second? Seems like that could be null quite often. What interval do you write the data to InfluxDB and what "group by time interval" have you set in your query?

**Comment by CptanPanic** [comment]
I am updating the data at 1m intervals, so I tried longer query of 10m and still the Query result is empty.  Also tried using avg() instead of last.

**Comment by pdu** [comment]
@CptanPanic I have the same confusion at first, but later I found that it's because we can't use the template variables in the alerting rules.

You can find it in the doc:

> The query used in an alert rule cannot contain any template variables. Currently we only support AND and OR operators between conditions and they are executed serially. For example, we have 3 conditions in the following order: condition:A(evaluates to: TRUE) OR condition:B(evaluates to: FALSE) AND condition:C(evaluates to: TRUE) so the result will be calculated as ((TRUE OR FALSE) AND TRUE) = TRUE.
