### ISSUE TITLE
Docker Hub: Missing tags for many of the latest releases

### ISSUE THREAD

**Issue by mbentley** [grafana/grafana#91118]
### What happened?

There were a number of releases that occurred recently but there were no Docker tags created on Docker Hub.  This includes: v9.5.21 v10.2.9 v10.3.8 v10.4.6 v11.0.2 v11.1.2 v11.1.3

### What did you expect to happen?

Docker Hub should have those image tags.

### Did this work before?

Previous versions exist on Docker Hub.

### How do we reproduce it?

```bash
for TAG in v9.5.21 v10.2.9 v10.3.8 v10.4.6 v11.0.2 v11.1.2 v11.1.3
do
  TRIMMED_TAG="$(echo "${TAG}" | awk -F 'v' '{print $2}')"
  docker buildx imagetools inspect --raw "grafana/grafana:${TRIMMED_TAG}"
done
```

```
ERROR: docker.io/grafana/grafana:9.5.21: not found
ERROR: docker.io/grafana/grafana:10.2.9: not found
ERROR: docker.io/grafana/grafana:10.3.8: not found
ERROR: docker.io/grafana/grafana:10.4.6: not found
ERROR: docker.io/grafana/grafana:11.0.2: not found
ERROR: docker.io/grafana/grafana:11.1.2: not found
ERROR: docker.io/grafana/grafana:11.1.3: not found
```

Doing the same for previous versions (v9.5.20 v10.2.8 v10.3.7 v10.4.5 v11.0.1 v11.1.1) works as expected.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: n/a
OS: n/a
Browser: n/a

### Grafana platform?

Docker

**Comment by remram44** [comment]
Just ran into this.

It is also confusing that there's:

- [grafana/grafana](https://hub.docker.com/r/grafana/grafana) (referenced in [your dockerfiles](https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile))
- [grafana/grafana-oss](https://hub.docker.com/r/grafana/grafana-oss)
- [grafana/grafana-enterprise](https://hub.docker.com/r/grafana/grafana-enterprise) ("works without a license", linked from [your download page](https://grafana.com/grafana/download/11.1.3?platform=docker))

It certainly confuses me, and now it looks it confuses you too. Maybe revisit this?

**Comment by kminehart** [comment]
Taking a look at this now. Sorry about that; we made a ton of improvements to our release process, including a dry run option. This stem seems to have the dry_run condition flipped. I'll get these images deployed to docker hub today.

**Comment by kminehart** [comment]
11.1.3 should be published now. I'll get all of the others published today!
