### ISSUE TITLE
[Feature request] Row edit icon

### ISSUE THREAD

**Issue by dac88** [grafana/grafana#9115]
Hi, 

A minor detail, but I am finding that the edit icon for a row (three dots) is detracting from the dashboard experience, perhaps unnecessarily. 

Would this be best placed away from the farthest point on the left hand side of the screen? Maybe the dots could be aligned horizontally and before the row title to make it an easier target.

Thanks,
Dean.

**Comment by torkelo** [comment]
If you go to dashboard settings and click hide controls (or shortcut: CMD (or CTRL) + H). Then the row controls will be hidden. 

In upcoming Grafana 5.0 we introduce a new grid layout engine that reduces the need for rows (beside being able to collapse dashboard sections or repeat dashboard sections). So with the new layout engine most dashboards will have their rows merged to on row (without row title). You can still have rows, but only with visible row title. So the row concept is going to change quite a bit.

**Comment by dac88** [comment]
Thanks @torkelo. 

It was more a question of making the icon more visible rather than hiding. 

I will await the 5.0 release.

**Comment by torkelo** [comment]
> It was more a question of making the icon more visible rather than hiding.

more visible? Thought you found them detracting and unnecessarily :)

**Comment by dac88** [comment]
@torkelo i think the first post was misread.

I am guessing it will be very different in 5.0 :)

Thanks.
