### ISSUE TITLE
[Feature Request] LDAP Group Mapping for Global Admin

### ISSUE THREAD

**Issue by felixkretschmer** [grafana/grafana#9116]
I'd love to assign global Admins via LDAP or AD group.

Is it possible to add the feature for ldap configuration.
Something like:

[[servers.group_mappings]]
group_dn = "CN=GrafanaAdmins,OU=Groups,DC=example,DC=com"
org_role = "GlobalAdmin"

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/2469
