### ISSUE TITLE
[Question] Grafana Singlestat, Toner left value from Zabbix

### ISSUE THREAD

**Issue by DeimantasLT** [grafana/grafana#9120]
Hi, i have issue with showing toner left value from zabbix API in Singlestat metric. In zabbix i can see toner left values, but in grafana i get null.    

JSON

> {
  "id": 22,
  "title": "Panel Title",
  "span": 12,
  "type": "singlestat",
  "targets": [
    {
      "refId": "A",
      "mode": 0,
      "group": {
        "filter": "Printers"
      },
      "host": {
        "filter": "printername"
      },
      "application": {
        "filter": ""
      },
      "item": {
        "filter": "Toner left 6D 61 67 65 6E 74 61 00"
      },
      "functions": [],
      "options": {
        "showDisabledItems": false
      }
    }
  ],
  "links": [],
  "datasource": "work",
  "maxDataPoints": 100,
  "interval": null,
  "cacheTimeout": null,
  "format": "percent",
  "prefix": "",
  "postfix": "",
  "nullText": null,
  "valueMaps": [
    {
      "value": "null",
      "op": "=",
      "text": "N/A"
    }
  ],
  "mappingTypes": [
    {
      "name": "value to text",
      "value": 1
    },
    {
      "name": "range to text",
      "value": 2
    }
  ],
  "rangeMaps": [
    {
      "from": "null",
      "to": "null",
      "text": "N/A"
    }
  ],
  "mappingType": 1,
  "nullPointMode": "connected",
  "valueName": "avg",
  "prefixFontSize": "50%",
  "valueFontSize": "80%",
  "postfixFontSize": "50%",
  "thresholds": "",
  "colorBackground": false,
  "colorValue": false,
  "colors": [
    "rgba(245, 54, 54, 0.9)",
    "rgba(237, 129, 40, 0.89)",
    "rgba(50, 172, 45, 0.97)"
  ],
  "sparkline": {
    "show": false,
    "full": false,
    "lineColor": "rgb(31, 120, 193)",
    "fillColor": "rgba(31, 118, 189, 0.18)"
  },
  "gauge": {
    "show": false,
    "minValue": 0,
    "maxValue": 100,
    "thresholdMarkers": true,
    "thresholdLabels": false
  },
  "tableColumn": 

>

**Comment by torkelo** [comment]
Please use community site for questions
