### ISSUE TITLE
Security considerations for permission system

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#9121]
There does not seem to be an "issue from marked line" feature for non-PRs.

https://github.com/grafana/grafana/blob/master/ROADMAP.md contains "Dashboard permissions (on folders as well), permissions on groups or users"

are those, or can those even be, more than "don't show the JSON" given how Grafana works? Afaik, I can even inject somewhat arbitrary queries through Grafana in proxy mode. That, in turn, implies that the permission system is cosmetic at best and misleading at worst.

I could be wrong, but if I am right, this should at least be pointed out in the docs.

**Comment by torkelo** [comment]
> "don't show the JSON" 

What? we have no such option. 

> Afaik, I can even inject somewhat arbitrary queries through Grafana in proxy mode.

Yes, the proxy access is just a reverse proxy, anyone who has view access to the org with a data source can issue any queries against the data source. 

> That, in turn, implies that the permission system is cosmetic at best and misleading at worst.

What is cosmetic or misleading?

The view role restrictions of not being able to edit panels is a bit misleading, I was against it for a long time but relented after strong community demand to be able to stop some users from being able to edit panels in the UI even though that did not in any way stop them from manually issuing any query if they know some http. 

Doing query validation in the backend proxy would be extremely complicated and expensive and in many cases impossible given how queries can contain wildcards or regular expressions and change dynamically so we cannot compare the query issued against what is in the dashboard json. 

But maybe we should have a clearer explanation in data source edit view for what proxy access means. Maybe some users think there is some security filter going on that only limits queries to what is actually in the dashboard that user has access to, but that is never stated and can not see how that can work. 

For some level of query security we need features in the time series database apis. For example 
 if Prometheus, Graphite or InfluxDB had some good way to send in the query a list of regex patterns of valid measurements so they can validate that the query being sent targets allowed measurements. 

Then you could when you setup grafana specify in Prometheus settings what metrics & tag values are allowed for this data source instance. We can include that in the query to prometheus so it can do the actual validation (a validation that Grafana cannot make as the query can include wildcards, and summarize many series without Grafana being able to detect it)

**Comment by torkelo** [comment]
> Dashboard permissions (on folders as well), permissions on groups or users

So the permissions will be mainly there to control who can view & edit what dashboards, to make large grafana installs that are using by many teams more manageable. We will extend permissions to data sources as well but that will require a separate data source for you to be able to isolate some data from some users.

**Comment by daniellee** [comment]
InfluxDB has a [permissions system](https://docs.influxdata.com/influxdb/v1.3/query_language/authentication_and_authorization/#user-management-commands) now. I don't see how it would ever be possible that we could build something like this for Graphite, Prometheus (and all the other data sources) into Grafana.

As Torkel says, dashboard folders + permissions is for dashboards - which Grafana has full control over.

**Comment by nemanjan00** [comment]
How about signing request on backend, with binding fields that can be changed and sending date that should be injected into query separatly... 

For people who can edit, signature verification can be skiped? 

For example, you can do something like this: 

Let's say query looks like this

SELECT * FROM users WHERE id=$id

What you can do is, when viewer opens dashboard, send this pair, instead of just query: 

hmac(query, key) and query

And when user wants to get response, he can send something like this: 

query, signature, {id: 123}

On proxy, you can do verification

hmac(query, key) == signature || isEditor || isAdmin

If that is true, you can inject id into query, and forward query to database.
