### ISSUE TITLE
[Feature request] Plugin for bokeh visualizations

### ISSUE THREAD

**Issue by rtmaster** [grafana/grafana#9122]
As Grafana evolves more and more from a "trend tool" to an full-blend analytics platform, a great jump in capabilities would be the integration with the bokeh (see https://bokeh.pydata.org).
Bokeh is a visualization library with great interactivity for people who need to explore data and find hidden patterns in it.
Having a Panel plugin for bokeh would really help all those who use Grafana for data analysis and would be a further differentiator.
Thanks @torkelo for considering this
Al

**Comment by linar-jether** [comment]
Currently we're using the [python datasource ](https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850) to serve bokeh plots, works pretty well with the [HTML panel plugin](https://github.com/jether-energy/grafana-html-panel) (which should soon be merged back into the Ajax panel plugin).

The top rows are regular graph panels (also served by the python datasource), and the bottom are bokeh figures:
![screenshot 110](https://user-images.githubusercontent.com/11908736/29870699-dddc7094-8d56-11e7-9ac7-a0e74d9344db.png)

**Comment by rtmaster** [comment]
Hi @linar-jether thanks for sharing your experience.
My DataFrame is already fetched by a query using [Influxdb datasource](https://grafana.com/plugins/influxdb).
Is there a way to use the panel plugin that you mention to generate the bokeh plot using that data?

Also nice to hear you are merging the HTML and AJAX panels.
Thx

**Comment by linar-jether** [comment]
Yep, you can use the python datasource just for the bokeh plot, you can read the data in python from what ever source you like and then generate the bokeh plot

**Comment by torkelo** [comment]
closing this as this can be an external plugin

**Comment by msalvaris** [comment]
@linar-jether Really like the dashboard! In your example [here](https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850) you don't seem to be serving any bokeh plots. Is that right? If so do you have a short example how to do this?

**Comment by linar-jether** [comment]
@msalvaris Just use the `add_panel_reader(name, lambda query_str, ts_range: <html_content>)` to register a function that returns an HTML string for a given query string and time range. then to query use the ajax panel to query.

![image](https://user-images.githubusercontent.com/11908736/34761218-77e6b2a8-f5a8-11e7-8d8c-7857f4ad7efd.png)

**Comment by davidohana** [comment]
@linar-jether Thanks!  works great!

**Comment by jjose122** [comment]
Thanks a lot!!
It works perfect.
