### ISSUE TITLE
[Bug]Graph Panel displays bars with duplicate data

### ISSUE THREAD

**Issue by iliugh** [grafana/grafana#9123]
What Grafana version are you using?
v4.4.1

What datasource are you using?
InfluxDB

What OS are you running grafana on?
CentOS 7

What did you do?
Use Graph, works with bars

What was the expected result?
See a bar

What happened instead?
Get duplicate bar

If related to metric query / data viz:
 time			Num

Data which are duplicated in InfluxDB： 

1504018800000000000	3
1504019400000000000	3
1504020000000000000	6
1504020600000000000	9
1504021200000000000	12
1504021800000000000	2
**1504022400000000000	10
1504022400000000000	10
1504023000000000000	11
1504023000000000000	11
1504023600000000000	6
1504023600000000000	6
1504024200000000000	4
1504024200000000000	4
1504024800000000000	4
1504024800000000000	4
1504025400000000000	3
1504025400000000000	3
1504026000000000000	7
1504026000000000000	7
1504026600000000000	5
1504026600000000000	5
1504027200000000000	9
1504027200000000000	9
1504027800000000000	6
1504027800000000000	6
1504028400000000000	8
1504028400000000000	8
1504029000000000000	5
1504029000000000000	5
1504029600000000000	7
1504029600000000000	7
1504030200000000000	2
1504030200000000000	2
1504030800000000000	2
1504030800000000000	2
1504031400000000000	7
1504031400000000000	7
1504032000000000000	4
1504032000000000000	4
1504032600000000000	5
1504032600000000000	5
1504033200000000000	4
1504033200000000000	4
1504033800000000000	2
1504033800000000000	2
1504034400000000000	1
1504034400000000000	1
1504035000000000000	3
1504035000000000000	3
1504035600000000000	4
1504035600000000000	4
1504036200000000000	1
1504036200000000000	1
1504036800000000000	2
1504036800000000000	2
1504038000000000000	2
1504038000000000000	2
1504038600000000000	8
1504038600000000000	8
1504039200000000000	2
1504039200000000000	2
1504039800000000000	229
1504039800000000000	229
1504040400000000000	25
1504040400000000000	25
1504041000000000000	84
1504041000000000000	84
1504041600000000000	144
1504041600000000000	144
1504042200000000000	151
1504042200000000000	151
1504042800000000000	4
1504042800000000000	4
1504044000000000000	2
1504044000000000000	2
1504044600000000000	3
1504044600000000000	3
1504045200000000000	8
1504045200000000000	8**
1504045800000000000	6
1504046400000000000	3
1504047000000000000	3
1504047600000000000	3
1504048200000000000	7
1504049400000000000	2
1504050000000000000	10
1504050600000000000	8
1504051200000000000	18
1504051800000000000	9
1504052400000000000	79
1504053000000000000	161
1504053600000000000	49
1504054200000000000	5
1504054800000000000	53
1504055400000000000	44
1504056000000000000	61
1504056600000000000	61
1504057200000000000	37
1504057800000000000	64
1504058400000000000	32
1504059000000000000	29
1504059600000000000	64
1504060200000000000	96
1504060800000000000	11
1504061400000000000	7

![image](https://user-images.githubusercontent.com/5077845/29853327-e0ed59f4-8d71-11e7-81e9-6eb49a4cfe07.png)

**Comment by iliugh** [comment]
Howerver,if I change the Display with Lines,Grafana works fine!

![grafana](https://user-images.githubusercontent.com/5077845/29853610-7fbe1b9e-8d73-11e7-94ea-d40c1f20a660.png)

**Comment by torkelo** [comment]
data you posted does not match the data in the graph (lines or bars), the graph shows values of 600 in some places but your data had no such value. 

Please include the raw influxdb response (open chrome dev tools network tab).

**Comment by iliugh** [comment]
1.data is changing,the latest is:
{
    "results": [
        {
            "series": [
                {
                    "name": "CancleBillReport",
                    "columns": [
                        "time",
                        "Num"
                    ],
                    "values": [
                        [
                            1503993000000,
                            18
                        ],
                        [
                            1503993600000,
                            18
                        ],
                        [
                            1503994200000,
                            18
                        ],
                        [
                            1503994800000,
                            16
                        ],
                        [
                            1503995400000,
                            8
                        ],
                        [
                            1503996000000,
                            11
                        ],
                        [
                            1503996600000,
                            36
                        ],
                        [
                            1503997200000,
                            69
                        ],
                        [
                            1503997800000,
                            22
                        ],
                        [
                            1503998400000,
                            28
                        ],
                        [
                            1503999000000,
                            6
                        ],
                        [
                            1503999600000,
                            14
                        ],
                        [
                            1504000200000,
                            8
                        ],
                        [
                            1504000800000,
                            16
                        ],
                        [
                            1504001400000,
                            20
                        ],
                        [
                            1504002000000,
                            16
                        ],
                        [
                            1504002600000,
                            20
                        ],
                        [
                            1504003200000,
                            70
                        ],
                        [
                            1504003800000,
                            79
                        ],
                        [
                            1504004400000,
                            568
                        ],
                        [
                            1504005000000,
                            641
                        ],
                        [
                            1504005600000,
                            175
                        ],
                        [
                            1504006200000,
                            7
                        ],
                        [
                            1504006800000,
                            7
                        ],
                        [
                            1504007400000,
                            6
                        ],
                        [
                            1504008000000,
                            13
                        ],
                        [
                            1504008600000,
                            9
                        ],
                        [
                            1504009200000,
                            42
                        ],
                        [
                            1504009800000,
                            15
                        ],
                        [
                            1504010400000,
                            17
                        ],
                        [
                            1504011000000,
                            16
                        ],
                        [
                            1504011600000,
                            19
                        ],
                        [
                            1504012200000,
                            23
                        ],
                        [
                            1504012800000,
                            13
                        ],
                        [
                            1504013400000,
                            15
                        ],
                        [
                            1504014000000,
                            7
                        ],
                        [
                            1504014600000,
                            15
                        ],
                        [
                            1504015200000,
                            11
                        ],
                        [
                            1504015800000,
                            9
                        ],
                        [
                            1504016400000,
                            7
                        ],
                        [
                            1504017000000,
                            18
                        ],
                        [
                            1504017600000,
                            18
                        ],
                        [
                            1504018200000,
                            15
                        ],
                        [
                            1504018800000,
                            3
                        ],
                        [
                            1504019400000,
                            3
                        ],
                        [
                            1504020000000,
                            6
                        ],
                        [
                            1504020600000,
                            9
                        ],
                        [
                            1504021200000,
                            12
                        ],
                        [
                            1504021800000,
                            2
                        ],
                        [
                            1504022400000,
                            10
                        ],
                        [
                            1504022400000,
                            10
                        ],
                        [
                            1504023000000,
                            11
                        ],
                        [
                            1504023000000,
                            11
                        ],
                        [
                            1504023600000,
                            6
                        ],
                        [
                            1504023600000,
                            6
                        ],
                        [
                            1504024200000,
                            4
                        ],
                        [
                            1504024200000,
                            4
                        ],
                        [
                            1504024800000,
                            4
                        ],
                        [
                            1504024800000,
                            4
                        ],
                        [
                            1504025400000,
                            3
                        ],
                        [
                            1504025400000,
                            3
                        ],
                        [
                            1504026000000,
                            7
                        ],
                        [
                            1504026000000,
                            7
                        ],
                        [
                            1504026600000,
                            5
                        ],
                        [
                            1504026600000,
                            5
                        ],
                        [
                            1504027200000,
                            9
                        ],
                        [
                            1504027200000,
                            9
                        ],
                        [
                            1504027800000,
                            6
                        ],
                        [
                            1504027800000,
                            6
                        ],
                        [
                            1504028400000,
                            8
                        ],
                        [
                            1504028400000,
                            8
                        ],
                        [
                            1504029000000,
                            5
                        ],
                        [
                            1504029000000,
                            5
                        ],
                        [
                            1504029600000,
                            7
                        ],
                        [
                            1504029600000,
                            7
                        ],
                        [
                            1504030200000,
                            2
                        ],
                        [
                            1504030200000,
                            2
                        ],
                        [
                            1504030800000,
                            2
                        ],
                        [
                            1504030800000,
                            2
                        ],
                        [
                            1504031400000,
                            7
                        ],
                        [
                            1504031400000,
                            7
                        ],
                        [
                            1504032000000,
                            4
                        ],
                        [
                            1504032000000,
                            4
                        ],
                        [
                            1504032600000,
                            5
                        ],
                        [
                            1504032600000,
                            5
                        ],
                        [
                            1504033200000,
                            4
                        ],
                        [
                            1504033200000,
                            4
                        ],
                        [
                            1504033800000,
                            2
                        ],
                        [
                            1504033800000,
                            2
                        ],
                        [
                            1504034400000,
                            1
                        ],
                        [
                            1504034400000,
                            1
                        ],
                        [
                            1504035000000,
                            3
                        ],
                        [
                            1504035000000,
                            3
                        ],
                        [
                            1504035600000,
                            4
                        ],
                        [
                            1504035600000,
                            4
                        ],
                        [
                            1504036200000,
                            1
                        ],
                        [
                            1504036200000,
                            1
                        ],
                        [
                            1504036800000,
                            2
                        ],
                        [
                            1504036800000,
                            2
                        ],
                        [
                            1504038000000,
                            2
                        ],
                        [
                            1504038000000,
                            2
                        ],
                        [
                            1504038600000,
                            8
                        ],
                        [
                            1504038600000,
                            8
                        ],
                        [
                            1504039200000,
                            2
                        ],
                        [
                            1504039200000,
                            2
                        ],
                        [
                            1504039800000,
                            229
                        ],
                        [
                            1504039800000,
                            229
                        ],
                        [
                            1504040400000,
                            25
                        ],
                        [
                            1504040400000,
                            25
                        ],
                        [
                            1504041000000,
                            84
                        ],
                        [
                            1504041000000,
                            84
                        ],
                        [
                            1504041600000,
                            144
                        ],
                        [
                            1504041600000,
                            144
                        ],
                        [
                            1504042200000,
                            151
                        ],
                        [
                            1504042200000,
                            151
                        ],
                        [
                            1504042800000,
                            4
                        ],
                        [
                            1504042800000,
                            4
                        ],
                        [
                            1504044000000,
                            2
                        ],
                        [
                            1504044000000,
                            2
                        ],
                        [
                            1504044600000,
                            3
                        ],
                        [
                            1504044600000,
                            3
                        ],
                        [
                            1504045200000,
                            8
                        ],
                        [
                            1504045200000,
                            8
                        ],
                        [
                            1504045800000,
                            6
                        ],
                        [
                            1504046400000,
                            3
                        ],
                        [
                            1504047000000,
                            3
                        ],
                        [
                            1504047600000,
                            3
                        ],
                        [
                            1504048200000,
                            7
                        ],
                        [
                            1504049400000,
                            2
                        ],
                        [
                            1504050000000,
                            10
                        ],
                        [
                            1504050600000,
                            8
                        ],
                        [
                            1504051200000,
                            18
                        ],
                        [
                            1504051800000,
                            9
                        ],
                        [
                            1504052400000,
                            79
                        ],
                        [
                            1504053000000,
                            161
                        ],
                        [
                            1504053600000,
                            49
                        ],
                        [
                            1504054200000,
                            5
                        ],
                        [
                            1504054800000,
                            53
                        ],
                        [
                            1504055400000,
                            44
                        ],
                        [
                            1504056000000,
                            61
                        ],
                        [
                            1504056600000,
                            61
                        ],
                        [
                            1504057200000,
                            37
                        ],
                        [
                            1504057800000,
                            64
                        ],
                        [
                            1504058400000,
                            32
                        ],
                        [
                            1504059000000,
                            29
                        ],
                        [
                            1504059600000,
                            64
                        ],
                        [
                            1504060200000,
                            96
                        ],
                        [
                            1504060800000,
                            11
                        ],
                        [
                            1504061400000,
                            42
                        ],
                        [
                            1504062000000,
                            23
                        ],
                        [
                            1504062600000,
                            36
                        ],
                        [
                            1504063200000,
                            11
                        ],
                        [
                            1504063800000,
                            15
                        ],
                        [
                            1504064400000,
                            12
                        ],
                        [
                            1504065000000,
                            14
                        ],
                        [
                            1504065600000,
                            16
                        ],
                        [
                            1504066200000,
                            19
                        ],
                        [
                            1504066800000,
                            12
                        ],
                        [
                            1504067400000,
                            8
                        ],
                        [
                            1504068000000,
                            7
                        ],
                        [
                            1504068600000,
                            14
                        ],
                        [
                            1504069200000,
                            12
                        ],
                        [
                            1504069800000,
                            21
                        ],
                        [
                            1504070400000,
                            20
                        ],
                        [
                            1504071000000,
                            12
                        ],
                        [
                            1504071600000,
                            13
                        ],
                        [
                            1504072200000,
                            15
                        ],
                        [
                            1504072800000,
                            9
                        ],
                        [
                            1504073400000,
                            17
                        ],
                        [
                            1504074000000,
                            20
                        ],
                        [
                            1504074600000,
                            14
                        ],
                        [
                            1504075200000,
                            18
                        ],
                        [
                            1504075800000,
                            20
                        ],
                        [
                            1504076400000,
                            19
                        ],
                        [
                            1504077000000,
                            26
                        ],
                        [
                            1504077600000,
                            18
                        ],
                        [
                            1504078200000,
                            16
                        ]
                    ]
                }
            ]
        }
    ]
}
2. and the graph is:
![image](https://user-images.githubusercontent.com/5077845/29860995-5f1eb1c4-8d9a-11e7-9a08-483b76811ea0.png)

**Comment by torkelo** [comment]
you need to filter out the duplicate data. This causes distance between data points to be zero which is affecting the width of the bars.

**Comment by iliugh** [comment]
I think the graph should have the ability to filter out the duplicate data with the same time.

**Comment by Akabell95** [comment]
I agree with @iliugh. I have the same problem.
And why @torkelo closed the issue? It's a problem and it still exists in 5.2.1

**Comment by torkelo** [comment]
Data filtering is not Grafanas job , that is exactly what TSDB query languages are for
