### ISSUE TITLE
Grafana not showing values in past

### ISSUE THREAD

**Issue by digambarGitHub** [grafana/grafana#9125]
Please prefix your title with [Bug] or [Feature request]. 

Title : Bug
Please include this information:
- What Grafana version are you using? -->   **Grafana v4.4.1 (commit: 6a9f8ca)**
- What datasource are you using? --> **Graphite (default)**
- What OS are you running grafana on? --> **Win-8.1**
- What did you do? -- > **Sent data to grafana using Java app ,since 1st January to 27 August**
- What was the expected result? --> **All sent data should shown on panel**
- What happened instead? --> **Can see data only after 1st August instead of 1st January.**

- Below one is the network response , which looks good.
![image](https://user-images.githubusercontent.com/8347565/29860633-50de8be0-8d84-11e7-9850-6a5a68153ae3.png)

I can see the values from 1st August to 27th August only, see screenshot:
![image](https://user-images.githubusercontent.com/8347565/29860847-052de8e8-8d85-11e7-850e-b1e6b2d0e202.png)

 But when I change Time range >30 days I can not see data before that.
![image](https://user-images.githubusercontent.com/8347565/29860965-4fe8842e-8d85-11e7-89ef-114867488e42.png)

One observation: Yesterday I was able to see data for 31st July but can not see it today. It is visible 1st August onwards. Can't we see data before 30 days in this grafana version?

**Comment by torkelo** [comment]
Take a look at your graphite storage schema (storage-schema.conf) it includes rules for how long the data is stored.

**Comment by digambarGitHub** [comment]
Where I can check that file?

**Comment by daniellee** [comment]
@digambarGitHub http://graphite.readthedocs.io/en/latest/config-carbon.html
