### ISSUE TITLE
[Bug] Hosts disappear when changing timeperiod

### ISSUE THREAD

**Issue by Xat59** [grafana/grafana#9127]
Hi guys,

- What Grafana version are you using?
Grafana v4.4.3 (commit: 54c79c5)

- What datasource are you using?
influxdb-1.2.1

- What OS are you running grafana on?
CentOS Linux release 7.3.1611 (Core)

- What did you do?
I created a dashboard with this time period : "Last 5 minutes". It displays something like this :
![image](https://user-images.githubusercontent.com/1276192/29867512-1d36c1fc-8d7c-11e7-87c5-17962a1c98fd.png)

Then, I changed the time period, for instance to "Last 7 days". So, it displays something like this :
![image](https://user-images.githubusercontent.com/1276192/29867557-40ee2ef0-8d7c-11e7-9476-ef3ca79f55ce.png)

- What was the expected result?
The displayed graph shows us same hosts with a different time period.

- What happened instead?
As you can see, some hosts disappear when changing the timeperiod. 

Thank a lot team.
Regards,
Jérémy Descamps.

**Comment by torkelo** [comment]
Upgrade InfluxDB or change InfluxDB option max-row-limit

**Comment by Xat59** [comment]
Thank a lot @torkelo 
I can confirm the InfluxDB upgrade solved the problem.
