### ISSUE TITLE
[Bug] Axis Label causes Grafana Panel to become scrollable

### ISSUE THREAD

**Issue by iplonjochen** [grafana/grafana#9129]
Grafana 4.4.3
I have some grafana panels. Some of them use "Axes->Label", others don't.
The ones that do use those labels allow me to scroll to an empty area. The ones without labels seem to know their size.
I'd expect the scrollbars to work correctly regardless of the presence of an axes label.

Panel without axes labels has correct size
![noname](https://user-images.githubusercontent.com/25382841/29873849-2617f11a-8d95-11e7-9453-e77e7a584562.jpg)

Panel with axes labels allows scrolling into an empty area
![withname](https://user-images.githubusercontent.com/25382841/29873854-2a2f7354-8d95-11e7-863d-f99e43895305.jpg)

The funny thing is, if I try to use the F12 chrome developer tools to find out what is being drawn under my graph to mess up the size, the size will become correct.

**Comment by iplonjochen** [comment]
I just realized it will only happen if it is an embedded panel. 
"/grafana/dashboard-solo/"

**Comment by torkelo** [comment]
This looks fixed in later versions
