### ISSUE TITLE
Checksum for downloads

### ISSUE THREAD

**Issue by kronn** [grafana/grafana#913]
Can you provide a url where a digest (e.g. md5sum) for the download can be found?

I see that currently, such digest is no generated on releasing or distribution. I don't know enough about grunt to provide a proper pull-request. With some pointers, I can try to extend the grunt-tasks to create the file.

**Comment by mihu** [comment]
With the new v2.0 it would be nice to have checksums for deb and rpm packages too.

**Comment by kronn** [comment]
I just took another look at this and saw that the generated deb- and rpm-packages get a md5-file generated, at least the `build.go` says so. I couldn't get it to work locally.

As there seems to be a md5-sum generated, can you also put that to S3, next to the deb-file? This would solve my issue.

**Comment by brandongalbraith** [comment]
If its difficult to generate an md5sum during the build process, you could upload the object to S3, and then perform a HEAD request on the object to get the checksum from the Etag header (which should be an md5 checksum in S3 as long as the object is under 5GB and not uploaded as a multi-part file).

**Comment by theznx** [comment]
Hello,
Im raising this thread.
A checksum (md5 ,sha256, etc) would be great (you can publish it on an other location that the build)
But,
Grafana is now enough important, you should consider signing your stable realease with PGP/Gnupg

**Comment by torkelo** [comment]
new download page and nightly builds page have checksums 

http://grafana.org/download/  (you need to click on the .deb link and the checksums will show) all download packages have sha1 files as well (just add `.sha1` to the package filename)

**Comment by widgetpl** [comment]
@torkelo I'm not able to get checksum of latest grafana release.
https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.2.1-1.x86_64.rpm.sha1
https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.2.1-1.x86_64.sha1
or
https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.2.1_amd64.deb.sha1
https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.2.1_amd64.sha1
doesn't work for me. Are they correct links or I do sth wrong?

**Comment by torkelo** [comment]
The sha files end in sha256 https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.2.1_amd64.deb.sha256

**Comment by theznx** [comment]
Grafana is now enough important, you should consider signing your stable realease with PGP/Gnupg

**Comment by torkelo** [comment]
Agree, we do sign rpm packages, but we should sign deb as well. Is there a standard way to sign tar balls?

**Comment by theznx** [comment]
I don't know if someone try to standardize the process.
For the tarball, as far a I know, it's better to put a detach sign or just a `--clear-sign` of the checksums.

Use an offline master key with a signing key (online, without masterkey), publish the master fingerprint & signing key fingerprint.
After that, you should sign this key with your own keys, if you plan to push grafana in Debian or others.
For now, it's what I except from well known projects

QubesOS have a very clean process & doc about that, maybe not what you want for grafana: [https://www.qubes-os.org/security/verifying-signatures/](https://www.qubes-os.org/security/verifying-signatures/)
I hope it can help a little :)

**Comment by widgetpl** [comment]
@torkelo thanks for update

**Comment by folksgl** [comment]
Please please please document this. This issue is the only reason I was able to find hashes of Grafana files outside of the html in the downloads page.
