### ISSUE TITLE
[Bug] Grafana is requesting millisecond-precision data from graphite.

### ISSUE THREAD

**Issue by mikesnare** [grafana/grafana#9130]
- What Grafana version are you using?

4.4.3

- What datasource are you using?

Graphite

- What OS are you running grafana on?

Linux via docker

- What did you do?

I used the `$__interval` template variable in a `summarize` function.

- What was the expected result?

That grafana would display a graph using the summarized data.

- What happened instead?

Got a 500 error from graphite because grafana is sending an interval value of '200ms' which is invalid for graphite

Here's the query that is sent:

```
sumSeries(summarize(consolidateBy(blah.blah.*.blah.blah.count, 'sum'), '200ms', 'sum', false))
```
 
This happens when I set the time to 5 minutes in the UI.  I have to set it to 30 minutes or higher to get past this.

**Comment by aocenas** [comment]
@mikesnare what do you think would be correct interval value here? I assume this means you asked for a small time range where the computed interval is 200ms. Is there some minimal interval that can be used with graphite or is the problem just the formatting of the interval value?

**Comment by mikesnare** [comment]
I don't have a clue.  I entered this... like... two jobs ago.

**Comment by torkelo** [comment]
you can change min interval in query options
