### ISSUE TITLE
[Bug] Inconsistent labels breaks table columns

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#9134]
- What Grafana version are you using?
4.4.1

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Centos 7.3

- What did you do?
Create a table panel, with a query that returns different labels

- What was the expected result?
Either only common labels get a column, or (preferable) rows where a given column has no value are empty (a customizable default value would be nice)

- What happened instead?
The columns are taken from the labels of the first result. Time series with other labels get their labels mapped to columns in (I guess) returned order.

As an example, using this query: `ALERTS{alertstate="firing"}`, I will get back a number of time series with a wide variety of labels. Here's a few from my installation:

```
ALERTS{alertname="DiskFullWithinThreeDays",alertstate="firing",device="/dev/mapper/vg_data-lv_cassandra",environment="prod",fstype="xfs",instance="some-node",job="node_exporter",mountpoint="/var/lib/cassandra",severity="info"}
ALERTS{alertname="MachineDown",alertstate="firing",environment="stage",instance="some-node",job="wmi_exporter",severity="critical"}
ALERTS{alertname="DestinationUnreachable",alertstate="firing",environment="prod",instance="some-node",job="node_exporter",severity="critical"}
ALERTS{alertname="Cassandra_CompactionPendingTasks",alertstate="firing",environment="prod",instance="some-node",job="cassandra_exporter",severity="warning"}
ALERTS{alertname="BlackboxProbeFail",alertstate="firing",instance="http://some-url",job="blackbox",severity="error",url="http://some-url"}
```

This will render a table with the columns from the first returned series, `alertname,alertstate,device,environment,fstype,instance,job,mountpoint,severity`, and the first row in the table will look fine. The second row, though, does not have these labels, and even the labels that are shared are not in the same order. Here things get weird, the severity label is mapped to the device column, instance to environment, etc.

So we end up with something like this:

alertname|alertstate|device|environment|fstype|instance|job|mountpoint|severity
-|-|-|-|-|-|-|-|-
DiskFullWithinThreeDays|firing|/dev/mapper/vg_data-lv_cassandra|prod|xfs|some-node|node_exporter|/var/lib/cassandra|info
MachineDown|firing|stage|some-node|wmi_exporter|critical
DestinationUnreachable|firing|prod|some-node|node_exporter|critical
Cassandra_CompactionPendingTasks|firing|prod|some-node|cassandra_exporter|warning
BlackboxProbeFail|firing|http://some-url|blackbox|error|http://some-url

Which is quite confusing.

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/pull/10050 fix this issue.
Please check.

**Comment by carlpett** [comment]
I'm no longer with the company where this was causing issues, but the PR looks like it should solve it, so I'll just close this. Thanks!
