### ISSUE TITLE
Alerting: Contact point >Getting Telegram chat ID

### ISSUE THREAD

**Issue by CodeExplorerX** [grafana/grafana#91346]
My problem concerns the Grafana documentation. Namely, Telegram connections for notifications. The documentation states that in order to get chat_Id, we must extract it from the address of the telegram web version: https://web.telegram.org/a/#-4266674385
Where -4266674385 will be the chat id. But this is not the chat id.

To get ChatID, I would recommend using Telegram api, namely getUpdates:
https://api.telegram.org/bot{Token}/getUpdates
If this is a forum or just a group, then you need to write **/start@mybot** in it to receive the update.

Documentation page: https://grafana.com/docs/grafana/latest/alerting/configure-notifications/manage-contact-points/integrations/configure-telegram/

**Comment by tonypowa** [comment]
Hello @CodeExplorerX 

Thank you for creating this issue

>  But this is not the chat id.

 It's not working on your side? Are you getting any errors when using this ID to setup your Grafana contact point ?

>To get ChatID, I would recommend using Telegram api, namely getUpdates:
[https://api.telegram.org/bot{Token}/getUpdates](https://api.telegram.org/bot%7BToken%7D/getUpdates)

The method you suggest was included in an earlier version of the telegram documentation that you made reference to. It was changed later for the simpler grabbing-it-from-the-browser-URL approach. I tested calling `https://api.telegram.org/bot{{token}}/getUpdates`, and the chat ID I see in the request response body is the same I see in the browser URL of the group chat.

![Image](https://github.com/user-attachments/assets/2e344323-f428-4b14-b512-0c365e2c6ec8)

![Image](https://github.com/user-attachments/assets/f7d58d5d-108d-494f-bf41-5aa3afeab1d8)

**Comment by tonypowa** [comment]
I’ll be closing this issue, but please feel free to request a reopening if you have any additional questions or concerns
