### ISSUE TITLE
Missing pre 5.0

### ISSUE THREAD

**Issue by temamagic** [grafana/grafana#9135]
On my 1st server I installed pre version 5.0.0 by url https://grafana.com/grafana/download/5.0.0-8695pre1

Now I want install same version on my 2nd server, but page is gone.

Only avaiable 4.5

Where can I see the difference between them?

upd: 
I found url to download deb: wget https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana_5.0.0-8695pre1_amd64.deb

**Comment by torkelo** [comment]
We decided to do an interim v4.5 release, so the latest build of master is no v4.5

**Comment by torkelo** [comment]
it contains everything the 5.0.0 pre release had
