### ISSUE TITLE
Grafana traces table view overlaps traceid link with span id link

### ISSUE THREAD

**Issue by awangc** [grafana/grafana#91359]
### What happened?

when seeing traces in table view and expanding the trace id to view span ids and moving the mouse around, we see the traceid link overlapping with span id link 
![Screenshot 2024-07-31 at 12 19 25 PM](https://github.com/user-attachments/assets/24785a79-c780-46ef-b3a4-68a1ad8126cb)

### What did you expect to happen?

trace id link should remain on the top of the row, like what we see here
 
![Screenshot 2024-07-31 at 12 19 42 PM](https://github.com/user-attachments/assets/82c1484a-cb43-4386-a0e1-cbc68e3faee1)

### Did this work before?

Yes, worked in Grafana 11.0.2

### How do we reproduce it?

Pull down grafana and tempo containers, use services with otel collector or push traces, open home -> explore -> search tab -> see trace table -> expand trace id -> hover mouse

### Is the bug inside a dashboard panel?

Cannot find get help feature

### Environment (with versions)?

Grafana: Grafana v11.1.3 (da5a557b6e)
OS: Mac OS, running docker
Browser: Version 126.0.6478.127 (Official Build) (arm64)

### Grafana platform?

Docker

### Datasource(s)?

tempo latest

**Comment by bruksnys** [comment]
Seems like a duplicate of https://github.com/grafana/grafana/issues/90430

**Comment by awangc** [comment]
Yes, seems to be a duplicate, closing in favor of #90430
