### ISSUE TITLE
[Bug] Template for Fields Value

### ISSUE THREAD

**Issue by yakhatape** [grafana/grafana#9138]
Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? Version 4.4.3
- What datasource are you using? Influxdb 1.3.2
- What OS are you running grafana on? RHEL 7.2
- What did you do? Template for Fields values
- What was the expected result? Choose manually the fields value on the template and graph the metrics choosed.
- What happened instead? 
Graph return "No data Point", but when I put the variable on the Title of the Graph the metric name is correctly displayed : 
![image](https://user-images.githubusercontent.com/9256016/29926579-26dbf054-8e64-11e7-8b0f-df2488a4a420.png)

As you can see on the name of the graph "actives_writes" is correctly displayed. But when I used the same variable in my query no data is returned in the graph.

The Request URL is correctly formed : 
![image](https://user-images.githubusercontent.com/9256016/29926863-e449c4ea-8e64-11e7-97bc-f58f7b8a4c52.png)
when I copy / paste it directly in my browser I have the correct value, but when I'm checking the request parameters : 
![image](https://user-images.githubusercontent.com/9256016/29926915-0b7f12b8-8e65-11e7-8c66-438c76bee66f.png)

And try to use it directly on Influxdb side no data is returned : 
![image](https://user-images.githubusercontent.com/9256016/29927054-793e49e0-8e65-11e7-99a9-9ef459dc5371.png)

In my debug I was identified this format of variable automaticly set by grafana : "/^Mongo_Metrics$/" , by curiosity I have manually edit this variable to "$Mongo_Metrics" and all metrics was returned in my graph : 
![image](https://user-images.githubusercontent.com/9256016/29927189-de0f76c8-8e65-11e7-87de-dc2d8b78d9ea.png)

And query parameters correctly set : 
![image](https://user-images.githubusercontent.com/9256016/29927208-edd5f1c2-8e65-11e7-95ea-9152baca4676.png)

There is a bug or we have the obligation to edit this automatic variable set by grafana ?

Best regards,
Yakha

**Comment by torkelo** [comment]
thanks for reporting this, looks like the suggestion for fields is using a regex pattern, should probably just return the variable name

**Comment by torkelo** [comment]
Closing this as with new the Flux language we won't add that much effort on InfluxQL
