### ISSUE TITLE
[Bug] Dashboard can continue to refresh, even when auto-refresh is disabled

### ISSUE THREAD

**Issue by j-white** [grafana/grafana#9139]
To reproduce using v4.4.3:
* Manually refresh dashboard
* Set auto-refresh to 10 seconds
* Disable auto-refresh immediately (before the 10 seconds are elapsed)
* Wait up-to 10 seconds

Expected behavior: the dashboard should not refresh
Actual behavior: the dashboard refreshes and continues to refresh every 10 seconds, even though auto-refresh is disabled

**Comment by phemmer** [comment]
I've noticed a similar behavior where if you save a dashboard with auto-refreash "off", when you load the dashboard the refresh interval dropdown is blank, which results in it being turned on. These might be the same issue. I haven't reported it as I'm running on an older version and wanted to upgrade before I reported it.

**Comment by j-white** [comment]
The fix for this was committed in the v4.4.x branch. Can we also get this merged to master so it can be part of 4.5.0?

**Comment by torkelo** [comment]
@j-white good catch!  merged it to master now!
