### ISSUE TITLE
feature request: add consolidateBy() selected by user if maxDataPoints used.

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#914]
I found that grafana uses maxDataPoints ( a great workarround to speed up plotting with time series with  thousands of datapoints) .

But dashboard designer should be able to select how to consolidate each metric if finally consolidations is done. ( by default averaged consolidations done) 

I suggest to add  a combo selector for each metric ( the default should be 'average')

![image](https://cloud.githubusercontent.com/assets/5883405/4576348/4c9529b2-4fb2-11e4-8a9d-ce4d506bfd07.png)

if selected other than default grafana could add consolidateby("metric","selected_by_user") function by itself.

what do you think about?

**Comment by torkelo** [comment]
closing this for lack of interest
