### ISSUE TITLE
Multiply metric by the number

### ISSUE THREAD

**Issue by cryptonoise** [grafana/grafana#9141]
Hello!

Grafana 4.4.3

I need to execute a simple formula:

`(Metric A / Metric B) * 1000`

How can I do this? 

There is a simple function for division: `divideSeries(My Metric #A, #B)`
But how can I multiply the result by the number?

**Comment by daniellee** [comment]
Questions should be asked on the [community site](https://community.grafana.com/). I think you are looking for the scale function.
