### ISSUE TITLE
Alerting: `prev_state` and `new_state` annotation field lengths cannot hold some combinations of alert state strings

### ISSUE THREAD

**Issue by drewhammond** [grafana/grafana#91421]
### What happened?

As described in closed PR https://github.com/grafana/grafana/pull/88348, there are some alert state strings that are longer than 25 characters and therefore can't be used outside of sqlite.

>While migrating from sqlite to postgresql, it was found that some permutations of alert states stored in sqlite's annotations table exceeded the migrator schema's prev_state and new_state nvarchar(25) constraint.
>
>Non-conforming alert state permutations are:
>```
>Alerting (NoData, KeepLast)
>Pending (NoData, KeepLast)
>```

It seems like this bug was introduced in https://github.com/grafana/grafana/pull/83940

### What did you expect to happen?

Alert states would be stored in a way that doesn't need fields of type `character varying(25)`, or the schema would be modified to support longer strings.

### Did this work before?

I have not confirmed if this works in a fresh grafana install using Postgresql. This works in sqlite installations because sqlite does not enforce the character limit.

### How do we reproduce it?

1. Configure grafana to use postgresql instead of sqlite
2. Create an alert rule with a data source that makes it possible to have states like `Normal (NoData, KeepLast)` and `Alerting (NoData, KeepLast)`
3. Observe Postgres error: `ERROR:  value too long for type character varying(25)` 

```
postgres-1  | 2024-08-01 17:58:02.998 UTC [38] ERROR:  value too long for type character varying(25)
postgres-1  | 2024-08-01 17:58:02.998 UTC [38] STATEMENT:  INSERT INTO "annotation" VALUES(619611,1,511,0,913,1,NULL,'','','<REDACTED>',NULL,'Pending (NoData, KeepLast)','Alerting (NoData, KeepLast)','{"values":{}}',1719577850000,0,'[]',1719577850946,1719577850946,1719577850000)
```

### Environment (with versions)?

Grafana: 10.4.6
OS: Ubuntu 22.04 amd64

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by pharaonby** [comment]
Same problem, docker image grafana/grafana:11.1.3
