### ISSUE TITLE
[Bug] Bug in size SingleStat ?

### ISSUE THREAD

**Issue by Diegonarducci88** [grafana/grafana#9142]
Please include this information:
- What Grafana version are you using?
4.4.3
- What datasource are you using?
zabbix
- What OS are you running grafana on?
Centos 7
- What did you do?
migrate in 4.1 to 4.4.3, changed size singlestat, but creating new singlestat, continues wit size diferent between versions
- What was the expected result?
same size of single stat of the version 4.1 why ocuped more area of 
![graf](https://user-images.githubusercontent.com/11810798/29940650-444c2a8a-8e66-11e7-85fe-99b4620b67ba.png)

**Comment by torkelo** [comment]
strange, unable to replicate this:
<img width="430" alt="screen shot 2017-08-31 at 21 43 25" src="https://user-images.githubusercontent.com/10999/29942249-79159d12-8e95-11e7-9c18-c982ba402224.png">

What is the stat font size (in options tab) set to?

**Comment by torkelo** [comment]
closing for lack of update
