### ISSUE TITLE
[Bug] No data points when accessing directly to template URL with vars?

### ISSUE THREAD

**Issue by jcasals** [grafana/grafana#9145]
Hello community,

I am using Grafana v4.4.3 (commit: 54c79c5) (just updated it to see it this could fix my issue, but it didn't) connected to a Graphite instance. Running both on Centos7.

Everything looks good, in fact, very good, as we are using it to replace our old Ganglia instance. For the moment we are just sending gmetric values to Graphite and reading it from Grafana as an intermediate step.

I created several Dashboards, but just one with templating variables. Then here is the issue. When I load it, and changed the select values, plots load and change correctly, and URL is modified with the new vars specified in the select options, but when I copy that URL and paste it in a new tab/window, the select options get the value from the variables in the URL, but plots appear with "No data points". 

Looking at the apache logs I can see that when I change the select the search is correct:
```
192.168.10.109 - - [01/Sep/2017:11:27:28 +0200] "GET /api/datasources/proxy/1/metrics/find/?query=ganglia.HTCondor.* HTTP/1.1" 200 192 "http://example.com/dashboard/db/cluster-host?orgId=1&var-cluster=Batch_System&var-host=All" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
```
And when I copy the resultant URL (http://example.com/dashboard/db/cluster-host?orgId=1&var-cluster=HTCondor&var-host=All) the search query it's not correct (regarding select values):
```
192.168.10.109 - - [01/Sep/2017:11:23:18 +0200] "GET /api/datasources/proxy/1/metrics/find/?query=ganglia.* HTTP/1.1" 200 371 "http://example.com/dashboard/db/cluster-host?orgId=1&var-cluster=HTCondor&var-host=All" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
```
(Please, note the api query search that is being fired)

I don't know if this could be an error in the setup of the template, but I just looked over everything and nothing seems to me as a solution.

Thank you for your time, hope this helps!

Jordi

**Comment by torkelo** [comment]
strange, unable to replicate, can set template values via url and graph loads. Not sure what could be wrong

http://play.grafana.org/dashboard/db/graphite-templated-nested?orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-server=backend_03&var-interval=1h

**Comment by torkelo** [comment]
make sure the variable has "Refresh On Dashbard Load" set in refresh option. could be a potential fix.

**Comment by jcasals** [comment]
@torkelo Thank you! I had it just on the first variable but not in the second one. That definitely fixed my problem :)
Excuse for the late answer, by the way
