### ISSUE TITLE
[Bug] Cloudwatch long retention metrics support

### ISSUE THREAD

**Issue by jeyglk** [grafana/grafana#9146]
- Grafana version are you using?
**4.4.3**

- What datasource are you using?
**Cloudwatch**

- What OS are you running grafana on?
**Docker Grafana image (grafana/grafana:4.4.3)**

- What did you do?
**Go to a dashboard with Cloudwatch panels, select last 6 months time range (or more). The panels have the period either set to auto or 3600.**

- What was the expected result?
**Grafana should show the metrics for the 6 months time range (or more) since cloudwatch keep 1 hour datapoints for 455 days.**

- What happened instead?
**The cloudwatch panels display only 2 months of metrics, either with the period set to `auto` or `3600`.**

![screen1](https://user-images.githubusercontent.com/1737199/29965802-120955ce-8f07-11e7-9435-49d3f2ef60ff.png)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

<img width="629" alt="screen-ntw-req" src="https://user-images.githubusercontent.com/1737199/29965732-b636cab0-8f06-11e7-992b-38bb238b6642.png">

![screen-ntw-resp](https://user-images.githubusercontent.com/1737199/29965937-97a57780-8f07-11e7-93b3-4bdcd264f9c6.png)

**Comment by mtanda** [comment]
Sorry, it might be bug.

This change may fix the issue, please try nightly build, and confirm the bug is fixed...
https://github.com/grafana/grafana/pull/8958

**Comment by jeyglk** [comment]
Yes, just tested with the latest build and it works! Amazing, thanks.

**Comment by mtanda** [comment]
Thanks for test!!
