### ISSUE TITLE
Provisioning: data sources by name broken in 11.1

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#91470]
### What happened?

Since upgrading to Grafana 11.1.0, referencing data sources using strings in JSON dashboards no longer works. This feature was essential for managing multiple Grafana servers efficiently.

Previously, we could reference data sources like this:

```json
{
  "datasource": "thanos"
}
```

### What did you expect to happen?

Data source to work and dashboard to work as well

### Did this work before?

Yes

### How do we reproduce it?

Référence a data source as string instead of an object in a provisioned Json.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by roidelapluie** [comment]
I continue my investigation. This only happens with mixed datasource.

**Comment by roidelapluie** [comment]
My hint is that this is a regression from #83356

**Comment by gillesdemey** [comment]
@grafana/dashboards-squad this seems to be in your wheelhouse?

**Comment by scottlepp** [comment]
@roidelapluie  The dashboard json schema changed awhile back.  `datasource` is no longer a string. It is now:
```
{
  "datasource": {
     name: "thanos",
     uid: "uid"
  }
}
```
There was some backward compatibility over older Grafana versions as that was deprecated, but as Grafana 11, that json format is no longer supported.
