### ISSUE TITLE
InfluxDB tags with special characters don't get interpreted during alert notifications

### ISSUE THREAD

**Issue by atzoum** [grafana/grafana#9148]
Please include this information:
- What Grafana version are you using? 
Grafana v4.4.1

- What datasource are you using? 
InfluxDB

- What OS are you running grafana on? 
Linux

- What did you do? 
Tried to setup an alert on a metric where I used a query alias containing a tag with special characters (eg. a dot):
![alias](https://user-images.githubusercontent.com/2481587/29977227-561080c4-8f45-11e7-97d1-c78638067e72.png)

- What was the expected result?
The tag value should be interpreted correctly in the alert notification:
**[Alerting] CPU usage alert**
**trg0008li (cloud-net)**

- What happened instead?
The tag name was not interpreted: 
![alert](https://user-images.githubusercontent.com/2481587/29977235-5a9a5f34-8f45-11e7-937e-3fc55f9b9b59.png)

**Comment by floyd-may** [comment]
This has been sitting around for two years? This use case is pretty important when using kubernetes, where tag names look like `tag_io.kubernetes.container.name`.

**Comment by floyd-may** [comment]
Is there a workaround?

**Comment by floyd-may** [comment]
And for posterity, this is still occuring on version 6.0.2.

**Comment by floyd-may** [comment]
Even some guidance on what area(s) of the code to look into would help; I may try to make a PR.

**Comment by marefr** [comment]
@floyd-may Cool that you would like to try and fix this.

If I'm not incorrect the code in question should be this function:
https://github.com/grafana/grafana/blob/0e2d279e3a5c72a9a1af1f282d3b6885ab5b7d53/pkg/tsdb/influxdb/response_parser.go#L61-L100

With related tests:
https://github.com/grafana/grafana/blob/0e2d279e3a5c72a9a1af1f282d3b6885ab5b7d53/pkg/tsdb/influxdb/response_parser_test.go#L133-L162

So should be rather easy to add a new test with your alias that doesn't work.

**Comment by floyd-may** [comment]
@marefr Thanks for pointing me in the right direction!

**Comment by floyd-may** [comment]
@marefr LOL should have known it was a regex somewhere! 😅
