### ISSUE TITLE
[bug] c.datapoints is undefined error on graphs

### ISSUE THREAD

**Issue by nlobarinas** [grafana/grafana#9149]
Hi! A little help. I'm having an strange behaviour when I use a FQDN to enter grafana web. When I use the IP address of the server works fine. 
I made a fresh new install on a dedicated server and has the same behaviour.

Thanks in advance!

- What Grafana version are you using? Version 4.4.3 (commit: 54c79c5)
- What datasource are you using? Graphite
- What OS are you running grafana on? Debian 8.9
- What did you do?  DNS A record pointing to the Grafana IP  http://monitoreo-telefonia.xxx.xxx => 10.64.12.42
- What was the expected result? Use a FQDN instead of IP address on the web browser
- What happened instead? Each graph shows this error.
Message: `c.datapoints is undefined`
Stack trace: `c/this.convertDataPointsToMs@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:15:17337
i@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:15288
l/<@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:15710
$eval@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:22861
$digest@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:21330
$apply@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:23146
x/i<@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:52:19196
f@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:51:1419
pb/k.defer/c<@http://monitoreo-telefonia.xxx.xxx/public/app/boot.07485e0c.js:51:2882`

/etc/grafana/grafana.ini
```#################################### Server ####################################
[server]
protocol = http
;http_addr =
http_port = 3000
domain = xxx.xxx
;enforce_domain = true
root_url = http://monitoreo-telefonia.xxx.xxx/
router_logging = true
static_root_path = public
;enable_gzip = false
;cert_file =
;cert_key =
;socket =```

/var/log/syslog
`Sep  1 12:30:38 smon0408lx grafana-server[1981]: t=2017-09-01T12:30:38-0300 lvl=info msg="Request Completed" logger=context userId=3 orgId=2 uname=nlobarinas method=POST path=/render status=200 remote_addr="10.64.7.69, 10.1.1.91" time_ms=81 size=822 referer="http://monitoreo-telefonia.xxx.xxx/dashboard/db/recursos-del-sistema?refresh=10s&orgId=2"`
`Sep  1 12:31:23 smon0408lx grafana-server[1981]: t=2017-09-01T12:31:23-0300 lvl=info msg="Request Completed" logger=context userId=3 orgId=2 uname=nlobarinas method=POST path=/render status=200 remote_addr=10.64.7.69 time_ms=45 size=1763 referer="http://10.64.12.42/dashboard/db/recursos-del-sistema?refresh=10s&orgId=2"`

**Comment by torkelo** [comment]
How did you configure your graphite data source? Access method (direct or proxy?). Looks like Grafana cannot access your Graphite server when you switch to use the FQDN to access Grafana. Maybe a CORS issue with your Graphite server (if you use direct access mode)
