### ISSUE TITLE
how to remove grafana from page title 

### ISSUE THREAD

**Issue by ersanjay1995** [grafana/grafana#9150]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? ->4.4.0 
- What datasource are you using? -> influxdb 
- What OS are you running grafana on? -> windows
- What did you do? - > learning  
- What was the expected result? - 
- What happened instead?
- If related to metric query / data viz:  how to modify grafana
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by daniellee** [comment]
As it says in the issue template:

> Questions should be posted to https://community.grafana.com

Please include more detail in your question when you post it on the community site.
