### ISSUE TITLE
How it possible to add X-Grafana-Org-Id wich specific org id via helm/grafana for JWT?

### ISSUE THREAD

**Issue by Nazargora** [grafana/grafana#91516]

**Comment by tonypowa** [comment]
Hi @Nazargora 
Thanks for reaching out. GitHub is mainly used for tracking bugs and feature requests. Your reported issue is more of a question, better suited for our[ community forums.](https://community.grafana.com/) You are also welcome to ask in our [Community Slack](https://sla
