### ISSUE TITLE
Alerting: changing execution error from alerting to keep last state does not get it back to OK

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#9153]
Grafana v4.4.1 (commit: 6a9f8ca) (grafanalabs grafana-monitor)

we have an alert set to execution error -> alerting
execution error happened, got the alert
changed exec error to "keep last state", note that at this point the data was ok, below the alert threshold

-> alert not going back to ok?
the only way i got it to back to ok was first changing the threshlold so that it becomes erroring, than change it back to what it was

**Comment by torkelo** [comment]
How frequently is the alert rule evaluated? When you say the Data was OK, and you changed alert rule so exec was set to keep last state, did you wait for it to evaluate, what Was the result of that eval? Exec error again? Then if keep Last state was set it would keep alerting state as that was the previous state after previous eval.

Not sure this is a bug, but we can double check

**Comment by Dieterbe** [comment]
> How frequently is the alert rule evaluated?

every 120s.

> When you say the Data was OK, and you changed alert rule so exec was set to keep last state, did you wait for it to evaluate

i'm pretty sure i waited yes, i think i had temporarily increased the interval to 10s also. but it was a rough on call night, don't remember exactly.

> what Was the result of that eval?
IIRC i waited like 5~10 minutes, during which it should definitely have not hit the exec error anymore, but i didn't confirm the result of individual eval outcomes (how should i have done that, by tailing the log and grepping for the specific alert?)

when i flipped the condition it switched to erroring straight away, and then flipping it back it went to ok straight away.

**Comment by Dieterbe** [comment]
i just had this same problem again. alert was every 60s, it had 50 minutes time to go back to ok but refused.
when i manually tested the alert, it said firing false.
only way i got it to go back to ok, was change threshold to something too high, to cause it to fire, then switch threshold back to what it was. i also temporarily changed interval to 10s to speed this process up.

on our internal grafana, go to `/dashboard/db/worldping-alerts?panelId=4&fullscreen&edit&tab=alert&orgId=1&from=now-30m&to=now`
you can see the state history there, and how it got stuck on exec error.

**Comment by Dieterbe** [comment]
another example is `/dashboard/db/taskserver-alerts?fullscreen&edit&tab=alert&panelId=1&orgId=1&refresh=1m&from=now-5m&to=now`

exact same phenomenon.

**Comment by torkelo** [comment]
>when i manually tested the alert, it said firing false.
only way i got it to go back to ok, was change threshold to something too high, to cause it to fire, then switch threshold back to what it was. i also temporarily changed interval to 10s to speed this process up.

Are you referring to state or history / annotation event? 

Are you using sqlite or mysql for grafana db? 

Any errors in Grafana.log?

**Comment by Dieterbe** [comment]
we only keep about 6h of logs so i can't tell for those previous cases. but i have another example:
`/dashboard/db/kubernetes-hm-us-east-alerts?fullscreen&edit&tab=alert&panelId=2&orgId=1&from=now-6h&to=now` (on our internal grafanalabs monitoring, so it uses sqlite)
today, sunday oct 1st at 11:32 (stockholm time, CEST) this happened:
`Error: Alert execution exceeded the timeout` causin it to alert. this is reflected in the history, annotation event (but not alert state, which seems to be in ok since the previous incident, where it went from critical to ok about 20 hours ago) : 
![grafana-issue9153](https://user-images.githubusercontent.com/20774/31053786-544f384e-a6a5-11e7-8228-527342316312.png)
![grafana-issue-9153b](https://user-images.githubusercontent.com/20774/31053785-544ee84e-a6a5-11e7-828f-8352f843fbd0.png)


this is log output. (it looks like it may be related to the sqlite errors, though they seem to have been retried successfully):
```
root@ziggurat:/var/log/upstart# zgrep -i -E 'er.*hm-us-east Node Out of Disk|sqlstore' /var/log/upstart/grafana-server*
/var/log/upstart/grafana-server.log.1:INFO[10-01|05:31:33] Database table locked, sleeping then retrying logger=sqlstore retry=0
/var/log/upstart/grafana-server.log.1:INFO[10-01|05:31:33] Database table locked, sleeping then retrying logger=sqlstore retry=0
/var/log/upstart/grafana-server.log.1:EROR[10-01|05:32:00] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=112 name="Kubernetes hm-us-east Node Out of Disk alert" error="Alert execution exceeded the timeout" changing state to=alerting
/var/log/upstart/grafana-server.log.1:INFO[10-01|05:32:00] Database table locked, sleeping then retrying logger=sqlstore retry=0
root@ziggurat:/var/log/upstart# 
```
note that the server is in EDT so 5:32 is 11:32 CEST

currently, testing the alert in UI says firing:false , and there are no more exec errors in the logs
but the state history & annotations are not creating a new OK entry . state is still ok, which also doesn't make sense to me, that it's different from state history and annotations, because the sqlite query should have been retried, and with success because the only errors in the log were errors with retry=0.
when I look at the code for `inTransactionWithRetry` in `pkg/services/sqlstore/shared.go`, given that there was no further error messages, it should have just committed.

**Comment by bergquist** [comment]
Grafana only changes state/create new annotation on state change. 

Not going back to OK from alerting when changing how to handle errors is a bug. But expected due to the current logic. 

I'm not sure why the annotation aren't created in the last example. My guess is that the operation when it was suppose to be inserted failed and we don't create a new one since the alert itself isen't changing state again. 

I think some of this would be addressed when we start working on updating state based on series updates. At the same time we should improve the annotation service to not only act on state change but also act if last annotation failed.

**Comment by Dieterbe** [comment]
is there any ETA on a fix?

**Comment by torkelo** [comment]
Have yet to replicate it. Looking at the log it seems to be related to the sqlite3 database and slow access to disk on the server. It is retrying but the db is still locked. Been talking to Carl about how to handle failed notification handling (saving the alert state history annotation), but no solid plan for how to fix this. 

Upgrading to MySQL should solve it db access issues but it does not address the underlying problem of how to handle repeated failures to write the annotation history event.

**Comment by Dieterbe** [comment]
did you notice in the logs i posted above all the errors had retry=0 ? since there's no messages with retry=1 doesn't that mean they successfully retried?

**Comment by zuchka** [comment]
hey all, thinking we can close this issue now that legacy alerting is deprecated
