### ISSUE TITLE
[Bug] alert state history & annotations not in sync with /alert/list

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#9154]
Grafana v4.4.1 (commit: 6a9f8ca) (grafanalabs grafana-monitor)

on /dashboard/db/elasticsearch-overview?panelId=10&fullscreen&edit&tab=alert&orgId=1 today at 3:43 I noticed the following:

* alert state history and annotations displayed on the chart agree, last state was  alerting due to tsdb exec error
* however /alerting/list it said "ok for a day" for that alert.

**Comment by torkelo** [comment]
think was related to a timezone problem with alert timestamps & sqlite

**Comment by torkelo** [comment]
report again if you see this still happening
