### ISSUE TITLE
Stat Panel: Percent Change value off by a multiple of 100

### ISSUE THREAD

**Issue by lanzafame** [grafana/grafana#91553]
### What happened?

Initial value is 2671, Last* value is shown 2391, percent change is shown as -1050%.

![Screenshot 2024-08-05 at 13 34 45](https://github.com/user-attachments/assets/b33db766-2939-4996-8de8-dd95885dbabc)

### What did you expect to happen?

Expect percent change value is -10%

### Did this work before?

v11.0 worked.

### How do we reproduce it?

1. Create a Stat Panel
2. Add any datasource
3. Turn on Percent change

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by leeoniya** [comment]
think the fix is here: https://github.com/grafana/grafana/pull/91528

**Comment by Develer** [comment]
We have reverted the PR causing the regression, so everything should work as expected.
<img width="1233" alt="Screenshot 2024-08-13 at 14 12 56" src="https://github.com/user-attachments/assets/b8dc5575-f618-4a4f-87d0-ead97184f78e">
