### ISSUE TITLE
[Bug] localhost DB error

### ISSUE THREAD

**Issue by mr-varga** [grafana/grafana#9155]
Dear all,

i have a raspberry pi 3, with influxdb ver. 1.3.4 and grafana ver. 4.4.3.
In my router i have port forwarding from:
external port 3000 to 192.168.8.200 port 3000
external port 8086 to 192.168.8.200 port 8086.
I use duckdns to have a fix exemple.duckdns.org address.

When I try to add in grafana db with url: http://localhost:8086 it doesn't work and give me the error: 
Test Failed
Network Error: undefined(undefined).

When I add a db with url: http://192.168.8.200:8086 (my local fix ip of raspberry) it works, but when I acces to grafana from external network (exemple.duckdns.org:3000) the grafana software it's unable to collect data from database.

When I add a db with url: http://exemple.duckdns.org:8086 it works only if I do this from external network, and when I acces to grafana from internal network (192.168.8.200:3000) the grafana software it's unable to collect data from database.

Can someone explain why and give me a solution for this problem?

**Comment by torkelo** [comment]
Depends on what you set access option to, if you set to this direct then url you specify for InfluxDB must  accessable from your browser, if you specify proxy as the access option then the url must be accessable from the same server grafana is running from

**Comment by mr-varga** [comment]
I don't use proxy. And if I try to open http://localhost:8086 in the browser localy it give me the 404 error an this mean the InfluxDB is accessibile. Right?
Which setting i have to setup for be able to view grafana from everywhere?

**Comment by torkelo** [comment]
404 error sound like and error to me, 404 means a http server is returning a error status code of not found.

>Which setting i have to setup for be able to view grafana from everywhere?

Dont understand this question, grafana is accessible by default from anywhere that access the server you run grafana on, so depends on your server network and firewall setup
