### ISSUE TITLE
[Bug] templating - variables inconsistency

### ISSUE THREAD

**Issue by eran-totango** [grafana/grafana#9157]
Hi,

I'm using grafana & influxdb as our data source to monitor our Elasticsearch clusters (any a lot of other stuff).

I'm using templating in my Elasticsearch to choose the environment & cluster i want to see.
![screen shot 2017-09-03 at 7 31 00 pm](https://user-images.githubusercontent.com/17027773/30004814-93084ea4-90de-11e7-96b8-7229e9575d71.png)

I'm using this query for the "host" variable:
![screen shot 2017-09-03 at 7 36 09 pm](https://user-images.githubusercontent.com/17027773/30004863-262be13c-90df-11e7-9dc7-d4530c4dc76c.png)

When i load the graph, it looks like the templating works as excepted,
the first query i see when i inspect my browser is this query (to this the list of hosts):
```
curl 'http://10.0.138.45:8086/query?u=test&p=test&db=telegraf&q=SHOW%20TAG%20VALUES%20from%20elasticsearch_os%20WITH%20KEY%20%3D%20%22node_name%22%20where%20%22cluster_name%22%20%3D~%20%2Frt%2F%20and%20%22cluster_name%22%20%3D~%20%2Fprod%24%2F&epoch=ms'
```
I verified and the response returns all results that exist in influxDB. so far so good.

This is the query i use in each graph to query the relevant hosts:
![screen shot 2017-09-03 at 7 45 43 pm](https://user-images.githubusercontent.com/17027773/30004944-77fdf29c-90e0-11e7-8ec5-0d50818a2683.png)
(That's just an example for one graph we have, we have other graphs but they all use they same syntax to query data only from the relevant hosts).

**What Issues I See:**
1. When i change the timerange, i encounter inconsistency in the hosts grafana shows. hosts in the graph change. 
- If i query "1 last hour" i get the full list of hosts in all graphs.
- if i query "3 last hours" i have 2 nodes disappeared from the graph (even though their data exists in InfluxDB) 
- If i query "12 last hours" i only see 14 nodes (instead of 33)
- if i refresh the graph, it can suddenly return different results.
- sometimes i also see inconsistency in different graphs on the same dashboard even though they use they query syntax to query the relevant hosts, as i mentioned before.

**What Infra Components I Use**
- Grafana : Version 4.4.3 (commit: 54c79c5)
- InfluxDB: Version: 1.3.5
- OS: Ubuntu 14.04

Anyways, thanks for your amazing product. It helps us A LOT

**Comment by torkelo** [comment]
This has (most likely) nothing to do with templates variables, it sound like you InfluxDB max-row-limit is a too low, this can cause InfluxDB to only return some of the series
