### ISSUE TITLE
[feature request] AWS Athena as sql datasource

### ISSUE THREAD

**Issue by markfink** [grafana/grafana#9158]
I like to be able to use athena as a datasource for sql queries.

athena user guide http://docs.aws.amazon.com/athena/latest/ug/what-is.html

**Comment by JimmyDahlqvist** [comment]
+1
That would be really nice!

**Comment by zhouhaijia** [comment]
+1

**Comment by gdxhsw** [comment]
+1

**Comment by shogomuranushi** [comment]
+1

**Comment by rafi-sysaid** [comment]
+1

**Comment by matthew-churcher** [comment]
+1

**Comment by zhang1980s** [comment]
+1

**Comment by orest-p** [comment]
++

**Comment by wlay** [comment]
+1

**Comment by orest-p** [comment]
+1

**Comment by nidcode** [comment]
+1

**Comment by GiPPe** [comment]
+1

**Comment by myco** [comment]
+1

**Comment by yarax** [comment]
+1

**Comment by jeongchanggu** [comment]
+1

**Comment by hex2a** [comment]
> Please, stop posting +1 comments which are only spamming all people subscribed to this thread. Instead, click on the big yellow "thumbs up" button at the top of this issue to upvote it.

**Comment by junjihashimoto** [comment]
+1

**Comment by mtanda** [comment]
I make Athena datasource for personal use.
I can't help to somebody use, but it might be useful for somebody.

Contribution for documentation or any other is really welcome.

https://github.com/mtanda/grafana-aws-cloudwatch-logs-datasource

**Comment by shawnallen85** [comment]
+1

**Comment by odannyc** [comment]
Will this ever be implemented?

We use Grafana cloud and this would be extremely useful. I am current running data pipeline to copy data from s3 to postgres.

**Comment by CloudViking86** [comment]
I agree with @odannyc (and others who liked the initial post); support for this would be very useful

**Comment by praja-one** [comment]
+1

**Comment by VinQbator** [comment]
+1

**Comment by sooba** [comment]
+1

**Comment by tsoe77** [comment]
+1

**Comment by dthauvin** [comment]
+1

**Comment by mtanda** [comment]
I try to add my plugin to `grafana.com` .
https://github.com/grafana/grafana-plugin-repository/pull/660

**Comment by SlightThought** [comment]
+1
