### ISSUE TITLE
grafana dashboard: ad-hoc filter not properly escaping forward slash

### ISSUE THREAD

**Issue by ethanmdavidson** [grafana/grafana#91582]
### What happened?

When using an ad-hoc filter with an elasticsearch datasource, the `/` character is not properly escaped. This causes strange results to appear, because `/` is used as the delimiter in lucene regex queries. 

For example, using the ad-hoc filter `httpRequest.url.standardizedPath =~ /api/integrations.*` results in the query `httpRequest.url.standardizedPath://api/integrations.*/`. I believe lucene is parsing the query as `httpRequest.url.standardizedPath:// OR api OR /integrations.*/`. That is:
- an empty regex on the httpRequest.url.standardizedPath field
- `api` in any field 
- the regex `integrations.*` in any field

This causes all sorts of undesired results to be returned.

### What did you expect to happen?

the ad-hoc filter `httpRequest.url.standardizedPath =~ /api/integrations.*` should result in a query like `httpRequest.url.standardizedPath:/\/api\/integrations.*/`, which lucene should parse into a single regex `\/api\/integrations.*` matching against the httpRequest.url.standardizedPath field.

### Did this work before?

I just started using the elasticsearch datasource yesterday, and had never used the ad-hoc filter before today, so I have no idea what behavior they had in the past.

### How do we reproduce it?

1. Create a dashboard with [an ad-hoc filter](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-ad-hoc-filters)
2. Add a panel that uses an elasticsearch data source
3. In the ad-hoc filter, attempt to enter a regex that uses the `/` character
4. Open the query inspector on your panel and confirm that the `/` character in your regex has not been escaped.

### Is the bug inside a dashboard panel?

This isn't really a problem with the dashboard panel, I think it's in the datasource. I'll add this field if requested.

### Environment (with versions)?

Grafana: v11.2.0-73830 (8d98c9eba7)
OS: macos 14.6
Browser: Chrome Version 127.0.6533.89 (Official Build) (arm64)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

elasticsearch 1.0.0

**Comment by iwysiu** [comment]
Hi @ethanmdavidson ! I just merged a commit that should let users escape characters properly in their regexes, it should land in fast tomorrow and in steady next Tuesday. It should allow you to escape forward slashes yourself. Note that based on a conversation with Elasticsearch, you will have to use the `<field>.keyword` syntax to get the results. An example for using this below:
![Image](https://github.com/user-attachments/assets/396ae425-d8c5-4bf3-af40-f933ad89d316)

**Comment by ethanmdavidson** [comment]
Cool, thanks for the fix! Just to be clear, I will have to escape the characters myself? I would prefer if grafana could do that automatically

**Comment by iwysiu** [comment]
Hi @ethanmdavidson ! Yeah, you'll have to escape any [reserved character](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters) in Elasticsearch (including `/`) if you would like to use them as non-special characters in the regex. We've talked about this a bit internally, but we decided it was preferable to leave it to users to give them the most control over their regexes.
