### ISSUE TITLE
[Docs] Complete list of files to be backed up

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#9159]
The documentation is missing instructions on which files should be backed up.

The [upgrade guide](http://docs.grafana.org/installation/upgrading/) describes how to back up the database. But we need to add:

- scripted dashboards
- plugins
- config

See this [community question](https://community.grafana.com/t/complete-list-of-files-to-be-backed-up/2245) for more details.

**Comment by oddlittlebird** [comment]
@daniellee , please specify exactly what needs to be added to the documentation and where.
