### ISSUE TITLE
[Feature request] graph time range as URL parameter

### ISSUE THREAD

**Issue by simondel** [grafana/grafana#9160]
What I'd like is to be able to select a time range so I can choose if I want the data from the last hour, day, week or month. How can I do that?

I have a grafana graph that's available at https://mygrafanabaseurl/db/mydashboard?var-Environment=MyEnv&var-Servicedesc=MyService&panelId=1&fullscreen&theme=light
It shows the graph like this right now:
![image](https://user-images.githubusercontent.com/4221997/30020610-b2df7d2a-9164-11e7-97b2-b1ac6bed0210.png)

It defaults to the last hour, which is fine in most cases, but sometimes I want more history. The graph is embedded using an iframe on a website.

**Comment by torkelo** [comment]
change time range to whatever you want and the url will update to include time range, in from and to url params

**Comment by simondel** [comment]
The URL didn't show anything but `&from=now-7d` works, thanks!
