### ISSUE TITLE
Docker: Inconsistencies in releases

### ISSUE THREAD

**Issue by leventyalcin** [grafana/grafana#91616]
### What happened?

There is a confusing inconsistency with Docker image releases:
* There is a Docker image version with no corresponding release, and the build is broken on the git tag created for the release.
* Some releases are verified, while others are not.

### What did you expect to happen?

The Docker image 11.1.2 shouldn't exist as there is no corresponding release on GitHub, and the image build is broken on the git tag 11.1.2.

```shell
 => [go-builder 11/25] COPY pkg/promlib/go.sum pkg/promlib/                                                                                                                                                                                         0.1s
 => ERROR [go-builder 12/25] RUN go mod download                                                                                                                                                                                                    0.3s
------
 > [go-builder 12/25] RUN go mod download:
0.209 go: cannot load module pkg/build listed in go.work file: open pkg/build/go.mod: no such file or directory
------
Dockerfile:64
--------------------
  62 |     COPY pkg/promlib/go.sum pkg/promlib/
  63 |     
  64 | >>> RUN go mod download
  65 |     RUN if [[ "$BINGO" = "true" ]]; then \
  66 |       go install github.com/bwplotka/bingo@latest && \
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```

This makes sense because `COPY pkg/build/go.* pkg/build/` is missing, although it has been added in a later version.

In my understanding, a release should be created only if everything builds and test passes successfully, and the artifacts should be generated from that release. However, it doesn't seem to be the case here.

Additionally, I don't understand why some of the releases/tags are pushed by the delivery bot while others are pushed by individuals. While this could be acceptable, it creates uncertainty as some tags are created without being signed.

Given these points, I believe the process of tagging/releases and releasing artifacts to external destinations (e.g., Docker Hub) should be refined. It would also be beneficial to have images signed with DCT, ensuring we can trust the images we consume.

### Did this work before?

```shell
❯ curl -sSfL https://api.github.com/repos/grafana/grafana/commits/v11.1.1 -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
>     | jq .commit.verification.verified
false

❯ curl -sSfL https://api.github.com/repos/grafana/grafana/commits/v11.1.2 -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
>     | jq .commit.verification.verified
true

❯ curl -sSfL https://api.github.com/repos/grafana/grafana/commits/v11.1.3 -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
>     | jq .commit.verification.verified
false
```

### How do we reproduce it?

N/A

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Docker

**Comment by leventyalcin** [comment]
I've just noticed it. The tag `11.1.2` actually is building `11.1.1` 

```shell
❯ git br
* (HEAD detached at v11.1.2) - [v11.1.x] Alerting docs: updates icon on landing page (#90884) (2 weeks ago) [grafana-delivery-bot[bot]]

❯ git diff 
diff --git a/Dockerfile b/Dockerfile
index 37d5609de7a..7040f19d836 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -58,6 +58,7 @@ COPY pkg/util/xorm/go.* pkg/util/xorm/
 COPY pkg/apiserver/go.* pkg/apiserver/
 COPY pkg/apimachinery/go.* pkg/apimachinery/
 COPY pkg/build/wire/go.* pkg/build/wire/
+COPY pkg/build/go.* pkg/build/
 COPY pkg/promlib/go.* pkg/promlib/
 
 RUN go mod download

❯ make build-docker-full

❯ docker run -it --rm  --entrypoint=/bin/sh grafana/grafana-oss:dev -c '/usr/share/grafana/bin/grafana --version'
grafana version 11.1.1

**Comment by bob-rohan** [comment]
> Some releases are verified, while others are not.

@kminehart in addition to closing, please elaborate on maintainers view with regards to verified commits please. `11.4.0` showing as unverified, latest at time of writing. Could verified releases be added as a requested feature to the release pipeline please? If reasons for no please help us understand why. Thanks

**Comment by kminehart** [comment]
We manually create the tags. Sometimes we sign the tag sometimes we don't. Honestly we didn't think anyone cared. In the future we will make sure all tags are signed.

**Comment by bob-rohan** [comment]
Awesome, thanks
