### ISSUE TITLE
[Feature request] Time range in the embedded inside the charts

### ISSUE THREAD

**Issue by JavierDelgadoFernandez** [grafana/grafana#9163]
Use case: When sharing a chart, the user may need to know the time range specified.

With the current version of Grafana, the charts configuration doesn't allow you to show the time range, so, once you have embedded a chart as an ``iframe`` or ``image``, the user doesn't know the exact time range.

For us, it is really necessary since a lot of users want to create their own dashboard layout with the sharing feature of Grafana.

**Comment by b0g3r** [comment]
+1

**Comment by wonx** [comment]
+1

**Comment by YakovlevMikhail** [comment]
+1

**Comment by fedeneira** [comment]
Any change to have #9163 done in the next couple of months?
