### ISSUE TITLE
[Bug] Elasticsearch adhoc filtering is only applying the latest filter.

### ISSUE THREAD

**Issue by jonesn** [grafana/grafana#9165]
- What Grafana version are you using? 4.5.0 8742pre1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? RHEL7
- What did you do? Clicked on the adhoc filtering magnifying glass on 2 different fields to apply 2 filters combinded with an AND.
- What was the expected result? That the query sent to elastic would apply both filters. 
- What happened instead? Only the latest was applied.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

## Screenshot of applied filters:

![grafana_missing_filter_in_underlying_query](https://user-images.githubusercontent.com/277481/30038128-aed4d908-9215-11e7-837d-19e697edb3bc.PNG)

## Underlying query send to Elastic

In this case only the latest `TargetUserName` filter is applied the `keywords` filter with a value of 'Audit Success' is not.

```json
{  
   "search_type":"query_then_fetch",
   "ignore_unavailable":true,
   "index":"win*"
}{  
   "size":2000,
   "query":{  
      "bool":{  
         "filter":[  
            {  
               "range":{  
                  "@timestamp":{  
                     "gte":"1504039272121",
                     "lte":"1504060872121",
                     "format":"epoch_millis"
                  }
               }
            },
            {  
               "query_string":{  
                  "analyze_wildcard":true,
                  "query":"beat.hostname.keyword: (\"NCCINF\\-PRDADS01\" OR \"NCCINF\\-PRDADS02\" OR \"NCCINF\\-PRDADS04\" OR \"NDCINF\\-PRDADS01\" OR \"NDCINF\\-PRDADS02\" OR \"NDCINF\\-PRDADS03\" OR \"NDCINF\\-PRDADS04\" OR \"NDCINF\\-PRDADS05\" OR \"NDCINF\\-PRDADS06\" OR \"NDCINF\\-PRDADS07\" OR \"NDCINF\\-PRDADS08\" OR \"SDCINF\\-PRDADS01\" OR \"SDCINF\\-PRDADS02\" OR \"SDCINF\\-PRDADS03\" OR \"SDCINF\\-PRDADS04\" OR \"SDCINF\\-PRDADS05\" OR \"SDCINF\\-PRDADS06\" OR \"SDCINF\\-PRDADS07\" OR \"SDCINF\\-PRDADS08\" OR \"TPBINF\\-PRDADS01\") AND (event_data.LogonProcessName: Kerberos OR keywords: \"Audit Failure\")"
               }
            }
         ],
         "must":{  
            "match_phrase":{  
               "event_data.TargetUserName.keyword":{  
                  "query":"*********_Admin"
               }
            }
         }
      }
   },
   "sort":{  
      "@timestamp":{  
         "order":"desc",
         "unmapped_type":"boolean"
      }
   },
   "script_fields":{  

   },
   "docvalue_fields":[  
      "@timestamp"
   ]
}
```

**Comment by torkelo** [comment]
thanks for reporting this!
