### ISSUE TITLE
Grafana 10.1.5 not working with Go 1.22.3

### ISSUE THREAD

**Issue by LuckyTyagi** [grafana/grafana#91663]
### What happened?

I'm trying to create a docker image of Grafana where we're using v10.1.5 and upgrading our Go version from 1.20.6 to 1.22.3
With earlier version it was working perfectly fine but after upgrading Go version it fails with following error.

```
Step 41/72 : RUN make build-go GO_BUILD_TAGS=${GO_BUILD_TAGS} WIRE_TAGS=${WIRE_TAGS}
 ---> Running in 0c954cffd4a6
(re)installing /root/go/bin/wire-v0.5.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/google/subcommands v1.0.1
go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b
generate go files
/root/go/bin/wire-v0.5.0 gen -tags oss ./pkg/server
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57fd2f]

goroutine 875 [running]:
go/types.(*Checker).handleBailout(0xc000d09800, 0xc00636fca8)
        /usr/local/go/src/go/types/check.go:367 +0x88
```

### What did you expect to happen?

Docker image should have been built successfully. So that a pod can be created.

### Did this work before?

Yes. Same Grafana version with Go version 1.20.3

### How do we reproduce it?

Dockerfile of Grafana to be used which is widely available, with said versions.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

### Datasource(s)?

Go 1.22.3

**Comment by hairyhenderson** [comment]
Grafana 10.1.x is no longer supported (as of May 2024). Please upgrade to the latest.
