### ISSUE TITLE
Environment variable: "GF_SECURITY_ALLOW_EMBEDDING=true" is not updating setting in "grafana.ini"

### ISSUE THREAD

**Issue by marcelherrmann** [grafana/grafana#91670]
### What happened?

For embedding purposes via iframe, the Grafana setting "allow_embedding" is required to be set to the non-default value "true". I run Grafana through docker and start it up via a YML file with environment variables. Grafana starts up fine, however, the "allow_embedding" setting is always set to the default value "false" when inspecting the running container. I am on Windows 11 and run the Docker Desktop app in Linux context.

Example of our yml file (for some reason github is removing indentation):
grafana:
    image: 'grafana/grafana-enterprise'
    container_name: 'grafana'
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ${FILESTORAGE_DRIVE_LINUX}/grafana:/var/lib/grafana

In the Grafana log file I can see the following:
2024-08-08 10:56:13 logger=settings t=2024-08-08T08:56:13.116433004Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ALLOW_EMBEDDING=true"

But for some reason the actual grafana.ini file is still kept with default "false" value.

### What did you expect to happen?

"allow_embedding" setting to be "true" in grafana.ini

### Did this work before?

No, haven't tried it before

### How do we reproduce it?

1. Install Docker Desktop on Windows 11 with WSL / Linux
2. Create a linux.yml file with content
services:
  grafana:
    image: 'grafana/grafana-enterprise'
    container_name: 'grafana'
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true

3. Run via
`docker-compose -f /mnt/c/Users/PathToYourFile/linux.yml up`
4. Inspect in Grafana in Docker Desktop, grafana.ini shows:
;allow_embedding = false

### Environment (with versions)?

Grafana: 11.1.2
OS: Windows 11 Enterprise 23H2
Browser: Firefox 128.0.3 (64-bit)

### Grafana platform?

Docker

**Comment by marcelherrmann** [comment]
In https://www.reddit.com/r/grafana/comments/g49b1q/how_to_set_allow_embeddingtrue/ someone mentioned a very similar behaviour.

**Comment by marcelherrmann** [comment]
Bump

**Comment by abogdanov37** [comment]
I have same problem in kubernetes

**Comment by hairyhenderson** [comment]
Environment variables override the settings in the config file (as you are observing). These settings do not alter the config file, however. This behaviour is expected.
