### ISSUE TITLE
[Feature request] Swap "< zoom >" and date range

### ISSUE THREAD

**Issue by rca** [grafana/grafana#9168]
Please include this information:
- What Grafana version are you using?

Grafana v4.4.3 (commit: 54c79c5)

- What datasource are you using?

InfluxDB

- What OS are you running grafana on? 

Linux

- What did you do?  

Clicked on the `Zoom Out` link in the nav bar and then clicked again without moving the mouse

- What was the expected result?

I expected the `Zoom Out` link to continue being in the same position so that clicking multiple times without chasing it down would continue zooming out

- What happened instead?

The date range expanded and moved the `Zoom Out` link to the left.

I think it would be great to have the zoom and arrow keys stay in the same place regardless of how much space the date range takes.   Would it be possible to simply swap the zoom and date range elements such that the zoom and navigation arrows are to the right, and not affected by the size of the date range.

Thank you.

<img width="520" alt="screen shot 2017-09-05 at 8 22 39 am" src="https://user-images.githubusercontent.com/53537/30061154-446b3fae-9214-11e7-976d-6038deb4c764.png">

<img width="545" alt="screen shot 2017-09-05 at 8 22 53 am" src="https://user-images.githubusercontent.com/53537/30061158-481c3cfc-9214-11e7-9b76-ffe940558349.png">

**Comment by torkelo** [comment]
agree, been frustrated by this as well. 

Inclined to move some zoom & <> stuff to a on hover dropdown as well.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/13025
