### ISSUE TITLE
Annotations: annotations from a Loki datasource are not displayed on a dashboard

### ISSUE THREAD

**Issue by yskopets** [grafana/grafana#91702]
### What happened?

Annotations from a Loki datasource are not displayed on a dashboard.

Instead, a red triangle appears on the dashboard:

<img width="143" alt="Screenshot 2024-08-08 at 18 21 26" src="https://github.com/user-attachments/assets/d6a72ce7-e3b1-4f34-b04b-cf7bca3eda2b">

with the following tooltip (notice **"Invalid date"** text in the title):

<img width="1240" alt="Screenshot 2024-08-08 at 18 22 43" src="https://github.com/user-attachments/assets/38d9ee18-fdfe-421f-aa30-82a11d53fcf0">

### What did you expect to happen?

I expect to see annotations from log lines, which  [Grafana docs](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/#fetch-annotations-through-dashboard-settings) and [video](https://www.youtube.com/watch?v=2istdJpPj2Y) claim to be supported.

### Did this work before?

Supposedly.

There is a [video](https://www.youtube.com/watch?v=2istdJpPj2Y) included in the [Grafana docs](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/#fetch-annotations-through-dashboard-settings) that showcases quering annotations from log lines.

### How do we reproduce it?

Just follow the steps from the  [Grafana docs](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/#fetch-annotations-through-dashboard-settings) or the [video](https://www.youtube.com/watch?v=2istdJpPj2Y).

E.g., here is my annotation definition:

<img width="624" alt="Screenshot 2024-08-08 at 18 36 26" src="https://github.com/user-attachments/assets/23545630-8780-4daa-93d2-dcb4113ea17d">

### Is the bug inside a dashboard panel?

No idea.

### Environment (with versions)?

Grafana: 11.1.3
OS: MacOS
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by matyax** [comment]
This should have been fixed by https://github.com/grafana/grafana/pull/96226 . Please let us know if the issue persist.
