### ISSUE TITLE
[Bug/Regression 4.5.0-beta.1]: AWS Cloudwatch no longer working with IAM role credentials

### ISSUE THREAD

**Issue by ankon** [grafana/grafana#9171]
Read before posting: 

Please include this information:
- What Grafana version are you using?
4.5.0-beta.1

- What datasource are you using?
AWS CloudWatch

- What OS are you running grafana on?
grafana-docker, inside kubernetes.

- What did you do?
In 4.4.3 I configured a cloudwatch data source, using 'secrets' as source of credentials in region eu-west-1. I did not specify any access key/secret access token; Grafana is supposed to pick these up from the IAM role credentials.

Due to unrelated issues[*] I ended up with a new grafana container, running 4.5.0-beta.1. 

- What was the expected result?
Same as in 4.4.3: metrics are shown.

- What happened instead?
In 4.5.0-beta.1 all my AWS CloudWatch metrics failed to work, and the log was filled with errors related to invalid signatures.
~~~~
t=2017-09-05T15:14:16+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\ncontent-length:274\ncontent-type:application/x-www-form-urlencoded; charset=utf-8\nhost:monitoring.eu-west-1.amazonaws.com\nx-amz-date:20170905T151416Z\n\ncontent-length;content-type;host;x-amz-date\nd86274ee718b8cc1dedd35f8eb4a5927f7ae59c25708f93624c2e89bf0348b24'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170905T151416Z\n20170905/eu-west-1/monitoring/aws4_request\nf28fad08f9fe847a2e0feead40fc02fc44301d7fd3e3d2a16283a7304fb74124'\n\n\tstatus code: 403, request id: e20dbbb7-924c-11e7-8e0e-6db1d0d5dc83"
~~~~
~~~~
t=2017-09-05T15:14:16+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: e234a4e9-924c-11e7-8e0e-6db1d0d5dc83"
~~~~
~~~~
t=2017-09-05T15:14:17+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="RequestError: send request failed\ncaused by: Post https://monitoring.eu-west-1.amazonaws.com/: net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=\\b\\xbc\\x1fZ\\xd4<\\xf1\\x9fy\\a\\x90\\x1cG\\xfc\\xa6\\x9b\\x86\\xfax\\x16/20170905/eu-west-1/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=01eb0a680a18c43052b9bf6b60bc0e601bd18fba45f6ee1de51de7f044ff1fcc\" for key Authorization"
~~~~

Usually these would appear in close succession, seemingly for each of my diagrams using CloudWatch.

Going back to 4.4.3 without any configuration change makes these errors disappear, and things start working again.

**Comment by ankon** [comment]
[*]: The kubernetes deployment was configured to use the 'latest' grafana docker image, and the host node got decommissioned so that kubernetes pulled a new version, which happened to be the 4.5.0-beta.1.

**Comment by daniellee** [comment]
This is fixed in the master branch and will be included in the 4.5.0 release. There was a bug when decrypting the secret that meant every 2nd request got an incorrect Authorization header.

Fixed by b1506a2b09caf27562cf1d49d40d3204263fba13

Thanks for reporting this.

**Comment by daniellee** [comment]
Closed this a bit too fast. This bug might still exist for Cloudwatch.

**Comment by torkelo** [comment]
this was indeed fixed by https://github.com/grafana/grafana/commit/b1506a2b09caf27562cf1d49d40d3204263fba13

**Comment by ubershmekel** [comment]
Just my luck - my first ever install and test drive of grafana was with this. Thanks for the quick fix!
