### ISSUE TITLE
Login: Github apears broken

### ISSUE THREAD

**Issue by splitice** [grafana/grafana#91723]
### What happened?

Today when attempting to login via github to grafana on two seperate deployments both are reporting

"Login failed"
"cannot remove last organization admin"

### What did you expect to happen?

Login as usual

### Did this work before?

Yes, as recently as last week.

### How do we reproduce it?

I can't un reproduce it. Nothing was changed and two totally independent installations begun showing the exact same issue.

I tested an upgrade to [Grafana v11.1.3 (da5a557b6e)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) however this did not resolve the issue.

### Environment (with versions)?

Grafana: [Grafana v11.0.0 (83b9528bce)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
OS: Kubernetes
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by splitice** [comment]
I've also tested a different browser. Whatever is broken, appears to be tied to the github api response.

**Comment by splitice** [comment]
I do not know why this has suddenly changed but I now need to add `auto_assign_org_role = Admin`

I'm guessing github started sending some OAuth role information and its being incorrectly interpreted. I'm an org admin, so yeah. not sure what grafana is doing here.

**Comment by Jguer** [comment]
This is related with default oauth role assignments being changed to the default org role unless configured explicitly. 

This ensures that all user roles are configured via the idP instead of having a mismatch of manually assigned and synced roles.

You will also notice you won't be able to configure roles for these users manually anymore
