### ISSUE TITLE
[BUG] Right y axes label wrong positioned

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#9172]
Grafana version: 4.5.0 beta 1
Datasource: MySQL
OS: Windows 2008 R2

The right y axes label is wrong positioned at the left side, instead of right side.

![right-y-axis-label](https://user-images.githubusercontent.com/29407741/30069327-bf1fc03e-9260-11e7-996f-ba56399b63c1.png)

**Comment by fmcmarques** [comment]
In previous version was fine.

**Comment by torkelo** [comment]
chrome version?

**Comment by torkelo** [comment]
can replicate in firefox and chrome, thanks for reporting this, will fix!
