### ISSUE TITLE
DashboardScene: variable label is empty when label is not populated (does not fallback to variable name)

### ISSUE THREAD

**Issue by Sergej-Vlasov** [grafana/grafana#91727]
### What happened?

when creating variable in scenes and leaving label empty, in the dashboard UI variable label is empty and does not fallback to name

![Image](https://github.com/user-attachments/assets/a7c5f848-72e1-4a4b-a005-956ecc5a40f1)

![Image](https://github.com/user-attachments/assets/a66e2025-3f1e-4256-b122-fc858062de41)

### What did you expect to happen?

variable should have label

### Did this work before?

yes, works in old arch

**Comment by ivanortegaalba** [comment]
To reproduce, it needs to have the label first, and then remove the value
