### ISSUE TITLE
Grafana session interference causes automatic login to fail

### ISSUE THREAD

**Issue by xiaoyuan2019** [grafana/grafana#91772]
### What happened?

Our operation and maintenance platform supports password-free redirection to the Grafana dashboard page. It's not an anonymous login, but rather the backend Django framework interface automatically logs into Grafana and obtains the returned session, which is then inserted into the response. The frontend, upon receiving the backend response, automatically inserts this session into the browser, thus achieving password-free login to Grafana. However, there is now a problem: when clicking to redirect, the Django backend actively returns a session to the browser, and when the frontend opens the Grafana link, Grafana itself also generates a session. This results in two Grafana sessions existing simultaneously in the browser, with different scopes, causing the password-free login to fail. The solution is to clear the browser cookies. As shown in the figure below: the one with a path of "/" is generated by the backend, and the one with a path of "/grafana" is generated by Grafana itself. Is there a way to completely solve this cookie interference problem?
![image](https://github.com/user-attachments/assets/087de2cb-1865-40d8-b732-f28bce74c107)
![image](https://github.com/user-attachments/assets/e009086c-4d8d-4a95-85a0-b72e1841026d)
![image](https://github.com/user-attachments/assets/6e2ca225-ef81-4eaf-89be-097fc41503ed)
![image](https://github.com/user-attachments/assets/271e899f-0060-4d5b-85e3-c0d0108c6e93)

### What did you expect to happen?

The browser session is normal, and the Grafana page can automatically log in to the dashboard page.

### Did this work before?

no

### How do we reproduce it?

1、Modify the default cookie name in Grafana.
2、The backend automatically logs into Grafana and returns the session to the browser.
3、Open the Grafana link on the frontend to see if it can automatically log into Grafana.

### Environment (with versions)?

Grafana:v11.1.3
OS:Linux 3.10.0-1127.el7.x86_64 x86_64
Browser:Google Chrome 126.0.6478.128

### Grafana platform?

Docker

### Datasource(s)?

prometheus

**Comment by Jguer** [comment]
Hi @xiaoyuan2019 we do not provide any support for custom solutions based on internal auth features. 

For your use case we recommend setting up auth proxy https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/ with enable_login_token.
