### ISSUE TITLE
GrafanaAdmin role can't add users to org v11.1.3-boringcrypto enterprise

### ISSUE THREAD

**Issue by Cimbel** [grafana/grafana#91787]
### What happened?

I cannot assign user to organization that I'm not belong to with GrafanaAdmin role assigned
I even tried to turn off RBAC feature and assign custom role to GrafanaAdmin with all required permissions and I defined custom role as global. But it didn't help at all

### What did you expect to happen?

I want that GrafanaAdmin user can add users to orgs and at the same time not belong to the org that it adds user to

### Did this work before?

Yep, it worked before on v10.4.5-boringcrypto version on k8s platform

### How do we reproduce it?

1. Login into Grafana UI under admin@localhost user
2. Create an organization named testorg for example
3. Create a new user called test1
4. Add test1 user with Admin role to testorg organization
5. Remove admin@localhost from testorg organization
6. Create new user in Main Org. test2
7. And try to add user test2 to org testorg

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v11.1.3-boringcrypto Enterprise edition
OS: alpine linux v3.19.1
Browser: Google Chrome Version 127.0.6533.100 (Official Build) (x86_64)

### Grafana platform?

Kubernetes

**Comment by IevaVasiljeva** [comment]
Hi! Thanks for reporting the issue!

I've got a PR raised to fix this issue (it will allow server admins to add/remove users to orgs that server admin doesn't belong to). The fix will be released together with Grafana 11.3.0. Is adding the server admin to all the orgs a reasonable workaround until you have the fix?

Also a heads up that in the long term we're planning to change server admin org memberships by assuming that all server admins are members of all organizations.

**Comment by IevaVasiljeva** [comment]
I've merged the fix and backported it to 11.1.x. So this issue should hopefully be fixed in 11.2.0 as well as the next patch of 11.1.x (should be 11.1.5). I'll close this issue for now, but please shout if it still doesn't work, in which case we'll reopen the issue and keep investigating.
