### ISSUE TITLE
Reusable metrics

### ISSUE THREAD

**Issue by gukoff** [grafana/grafana#9180]
I have a metric `A` to display on the dashboard. 

`A` is a complex graphite query. Say, `A = asPercent(cluster.service.my_service.front.log_search.ok_rps.rps, sumSeries(cluster.service.my_service.front.log_search.*.rps))`

There is no way to edit this metric nicely. Only manually in a 'raw' mode, which is really painful:
<img width="1247" alt="2017-09-06 13 07 59" src="https://user-images.githubusercontent.com/5655837/30106675-e2f94eb8-9304-11e7-97ab-a556371b7852.png">

But we could make use of autocompletion like this:
<img width="1243" alt="2017-09-06 13 16 01" src="https://user-images.githubusercontent.com/5655837/30106872-949f8cb8-9305-11e7-9088-858508ba2583.png">

And reuse queries like this:
<img width="1247" alt="2017-09-06 13 19 34" src="https://user-images.githubusercontent.com/5655837/30106999-110f1a3e-9306-11e7-9e62-4365eaa045ff.png">

Note that I made the auxiliary rows hidden.

Also we could go further and reuse the paths:
<img width="1242" alt="2017-09-06 13 21 55" src="https://user-images.githubusercontent.com/5655837/30107099-6f1accea-9306-11e7-9187-41f725b9f677.png">

The minimum viable version of this wouldn't even require a back-end support. The queries could be expanded as if they were macros.

**Comment by torkelo** [comment]
all this works today and have for a very long time :)

![image](https://user-images.githubusercontent.com/10999/30111903-c7eb1f7e-930f-11e7-84b0-428ba2eb1852.png)

**Comment by gukoff** [comment]
Wow! Thanks
