### ISSUE TITLE
How Summarize the metric based on time range?

### ISSUE THREAD

**Issue by cryptonoise** [grafana/grafana#9181]
Hello!

Please help me set up Grafana. I dont find answer in grafana community.

I need summarize the metric based on current time range. For example:

I set time range “today” - and I want to see on singlestat my metric wich summarize statistic from 00:00 to current moment

or

I set time range “yesterday” - and I want to see on singlestat my metric wich summarize statistic from 00:00 yesterday to current moment

summarize(metric, '24h', 'sum', false)&from=00:00&until=now
not working

How I can do this? Write functions example please

**Comment by torkelo** [comment]
https://community.grafana.com/

**Comment by torkelo** [comment]
please open question on the community site :)
