### ISSUE TITLE
[Feature request] Grafana elasticsearch - How to do arithmetic operation on two elastic queries result

### ISSUE THREAD

**Issue by suyogdilipkale** [grafana/grafana#9183]
I am drawing timeline link chart to get avg post counts per active users. 
I have following query result: 
- A: total active users [unique] count per hour 
- B. total posts added by all users per hour 

I want to draw line chart for avg posts per active users for that hour [B/A].

How I can divide result of B by A for each hour.
![2017-09-06_1722](https://user-images.githubusercontent.com/16184220/30111252-9a7788aa-932a-11e7-9dc0-d0891148549d.png)

- What Grafana version:4.4.2
- What datasource: ElasticSearch 5.x
- What OS are you running grafana on: Linux/Windows

**Comment by torkelo** [comment]
this is currently not supported by Elasticsearch (it does not support nested queries nor operations on nested queries).

Grafana hopes to do this some time via this feature:
https://github.com/grafana/grafana/issues/3677

**Comment by suyogdilipkale** [comment]
I am able to get those avg directly from elasticsearch, **it means it is supported by elasticsearch.**
Below is sample query:

> GET post-analytics/_search
{
   "size": 0,
   "aggs": {
      "hour": {
         "date_histogram": {
            "field": "ts",
            "interval": "hour"
         },
         "aggs": {
            "posts": {
               "filter": {
                  "terms": {
                     "act": [
                        "addpost",
                        "resharepost"
                     ]
                  }
               },
               "aggs": {
                  "activities": {
                     "value_count": {
                        "field": "act"
                     }
                  }
               }
            },
            "users": {
               "cardinality": {
                  "field": "uid"
               }
            },
                "percentage": {
                    "bucket_script": {
                        "buckets_path": {
                          "totalPosts": "posts>activities",
                          "activeUsers": "users"
                        },
                        "script": "params.totalPosts / params.activeUsers"
                    }
                }
         }
      }
   }
}

I am not sure, How **I can achieve the same in Grafana.**

**Comment by liujin1993** [comment]
@torkelo this feature is supported by elasticsearch's bucket-script. https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-aggregations-pipeline-bucket-script-aggregation.html
