### ISSUE TITLE
[Feature request] Add "No data points" description for pie chart with 0 value.

### ISSUE THREAD

**Issue by selina2017** [grafana/grafana#9188]
- What Grafana version are you using?
Grafana version 4.4.3
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
ubuntu
- What did you do?
Our pie chart is to show abnormal behavior for a site. If there is no error (value = 0), the pie chart is showing blank. However, it is misleading to users who are not sure whether there is error that prevent the data from showing or there is no data.

<img width="186" alt="screen shot 2017-09-06 at 5 43 10 pm" src="https://user-images.githubusercontent.com/31295632/30140649-f5d15ef6-932a-11e7-91fc-75662ea9d7c7.png">

When there is data, the pie chart is looking fine.
<img width="264" alt="screen shot 2017-09-06 at 5 14 53 pm" src="https://user-images.githubusercontent.com/31295632/30140600-9641d826-932a-11e7-8579-530c9d7a7b22.png">

- What was the expected result?
The pie chart should show "No data points" just like what is shown in bar graph.
<img width="546" alt="screen shot 2017-09-06 at 5 13 24 pm" src="https://user-images.githubusercontent.com/31295632/30140457-a497d8fe-9329-11e7-87b0-94a84143b929.png">

- What happened instead?
The pie chart is showing blank.
<img width="186" alt="screen shot 2017-09-06 at 5 43 10 pm" src="https://user-images.githubusercontent.com/31295632/30140651-fae05a96-932a-11e7-8029-e687bca1ebd0.png">

**Comment by torkelo** [comment]
pie chart is an external plugin:
https://github.com/grafana/piechart-panel

**Comment by oligu** [comment]
Hello @torkelo This plugin is now part of Grafana Core and the issues still persists. Can you do something about it?

**Comment by oligu** [comment]
@torkelo Yes, when there is no data, everything is ok. But when all data points are 0, then there is a blank panel.

**Comment by torkelo** [comment]
@oligu can you open the inspect / data tab and show what your data looks like ? (also the raw dataframe in the JSON tab) would help

**Comment by torkelo** [comment]
All the values are zero, so 🤷  

A google sheet pie chart with only zeros is also blank 
![Screenshot 2024-03-15 at 09 10 28](https://github.com/grafana/grafana/assets/10999/3ad2218a-6f81-4468-a4e9-ef5538f5785e)

**Comment by oligu** [comment]
As the OP states, if the pie is blank, it's not obvious for users what is going on. Is there an error, data not loaded,  data=0, ??? 
One could argue that the pie should be halve/halve, as both values are equal. But this again could be confusing and lead users to think that there are values > 0.
A solution could be to just show the outline of an empty pie. See this discussion on highchaft: https://github.com/highcharts/highcharts/issues/5526
The default color of the outline could be "Transparent" in order to not break exisiting dashboards, but configurable to any color.
