### ISSUE TITLE
Logs: Forward direction search does not return oldest results for > 1d query range

### ISSUE THREAD

**Issue by stevendungan** [grafana/grafana#91907]
### What happened?

For Loki forward direction logs searches: Logs appear to return from the beginning of the query split interval (which is an internal grafana mechanism not exposed to most end users), as opposed to the beginning of the query interval specified by the user.

_For a query executed on August 14 with a 7 day lookback period:_
![image](https://github.com/user-attachments/assets/6bd506fe-de07-4c08-8bb6-1d2d1a3e855f)

### What did you expect to happen?

Return the logs beginning from the query range start period

### Did this work before?

No

### How do we reproduce it?

1. Set Loki logs query range greater than 1d (or whatever is being used for split interval)
2. Set Direction to Forward

### Environment (with versions)?

Grafana v11.2.0-74515 (b4126d3bce)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Loki

**Comment by matyax** [comment]
I'll assign this to me, but if you want to give this a try @svennergr , go for it!
