### ISSUE TITLE
Grafana alerts as a datasource

### ISSUE THREAD

**Issue by kjetilmjos** [grafana/grafana#9192]
Hi, 

I need to display a world map showing Grafana alerts. Currently we are doing this by making a custom webhook that puts every alarm in a alert database in influxDB. I would love a way to use the Grafana alerts directly as a datasource without the webhook. If Grafana alerts would also implement alert history it could be possible to display alerts as time series data to plot status over time.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
