### ISSUE TITLE
Docs: Broken links (404 Errors) to style guides on Grafana documentation site

### ISSUE THREAD

**Issue by lucasrod16** [grafana/grafana#91940]
### What happened?

While reading through the [developer contributing guide](https://github.com/grafana/grafana/blob/main/docs/sources/developers/contribute.md#best-practices-and-style), I received a 404 error when I clicked the [backend style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/backend.md) and the [documentation style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/backend.md).

### What did you expect to happen?

To be navigated to the selected style guide without receiving a 404 error.

### Did this work before?

I assume this used to work, but documentation has been updated and move to new locations.

### How do we reproduce it?

Navigate to this [developer contributing guide](https://github.com/grafana/grafana/blob/main/docs/sources/developers/contribute.md#best-practices-and-style) and click the [backend style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/backend.md) and [documentation style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/backend.md) links.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

N/A

### Grafana platform?

None

**Comment by lucasrod16** [comment]
I am preparing a PR to fix the broken links

**Comment by tonypowa** [comment]
fixed by https://github.com/grafana/grafana/pull/93049
