### ISSUE TITLE
[Feature request] Singlestat sparklines, selectable behaviour for null

### ISSUE THREAD

**Issue by candlerb** [grafana/grafana#9195]
At the moment, a singlestat panel with sparklines and missing data behaves like a regular graph with "null value: connected"

![image](https://user-images.githubusercontent.com/44789/30168085-4c40c5d2-93e0-11e7-886b-e63d457d2574.png)

I would like to be able to choose "null value: null" or "null value: null as zero" which a regular graph panel has.

- What Grafana version are you using? **v4.4.3 (commit: 54c79c5)**
- What datasource are you using? **prometheus**
- What OS are you running grafana on? **Ubuntu 16.04**

**Comment by zoltanbedi** [comment]
Singlestat has been deprecated and replaced by stat panel where this works.
