### ISSUE TITLE
Upgrade 10.4.6 -> 10.4.7 with yum: fails with error because file/folder already exists

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#91980]
### What happened?

I'm unable to update my Grafana installation from 10.4.6 to 10.4.7 using yum package manager.
This is the error message I get:
`failed to open dir data of /usr/share/grafana/plugins-bundled/internal/input-datasource/node_modules/@grafana/data/: File exists`

I'm working on a RHEL 9 machine.

### What did you expect to happen?

I expect to be able to upgrade my yum package as usual.

### Did this work before?

Yes, always.

### How do we reproduce it?

1. Install Grafana 10.4.6 on a RHEL (or CentOS) machine: `yum install grafana-10.4.6-1`
2. Upgrade to 10.4.7: `yum install grafana-10.4.7-1 -y`

### Environment (with versions)?

Grafana: 10.4.7
OS: RHEL 9
Browser: not relevant

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by sspieker** [comment]
Just found a grafana.com community question describing the exact same problem: https://community.grafana.com/t/error-update-10-4-7/128826
I tried to analyze the diff ([10.4.6 -> 10.4.7](https://github.com/grafana/grafana/compare/v10.4.6...v10.4.7)) but did not find the problem...

**Comment by Sypher45** [comment]
You can try with a new instance  10.4.6 on a new server without any installed plugins and you will reproduce  the same issue.

It will failed when you upgrade on 10.4.7

**Comment by sspieker** [comment]
I was able to update to 10.4.8 which was released today, so I'm closing this issue.
