### ISSUE TITLE
[Bug] Alerting: no alert when only one group in a GROUP BY query has no data

### ISSUE THREAD

**Issue by fransflippo** [grafana/grafana#9198]
I've got JVM memory metrics of two servers in a single InfluxDB value that is tagged with the server name:

SELECT mean("Used") FROM "JVM.Memory.Heap" WHERE "cluster" = 'REW_ZAI_Cluster' AND $timeFilter GROUP BY time($__interval), "node", "environment", "cluster" fill(null)

Because of the GROUP BY, this query results in two series in the graph widget. I've created an alert with a threshold and when either of the series goes over the threshold, I get an alert.
However, when either of the series (but not both) doesn't have data, I don't get an alert.

- What Grafana version are you using? 4.3.2
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Linux
- What did you do? Create an alert on a single query with a GROUP BY resulting in two series
- What was the expected result? Get an alert when either of the series went no data
- What happened instead? No alert when just one of the series goes no data
 
I didn't find anything about this in the documentation (http://docs.grafana.org/alerting/rules/), so perhaps this is how it's supposed to work, but it's not what I was expecting.

**Comment by torkelo** [comment]
This is a limitation or a problem in how influxdb returns time series. If there is no data point for a time series in the time range it returns no time series at all for that series, so there is no way for grafana's alerting engine to see that there is a series with "null" values / missing data as there is only a single series returned. Most other time series databases would in this case return the time series even when there is no data there. 

![image](https://user-images.githubusercontent.com/10999/30202904-5ea50954-9480-11e7-954a-81c7a0ca5e00.png)

Maybe this feature request can solve this problem, not sure:
https://github.com/grafana/grafana/issues/6041
