### ISSUE TITLE
[Bug] Severe memory leakage

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9199]
Please include this information:
- What Grafana version are you using?
4.4.1
- What datasource are you using?
influxdb, cloudwatch
- What OS are you running grafana on?
centos 6

We have many dashboards and alerts in Grafana and we observe severe memory leakage in Grafana and Grafana gets killed by the kernel due to OOM. Is there an easy way to get debugging information on where the memory leakage could happen?

**Comment by torkelo** [comment]
strange, it's not something we have seen and this is the frist reported case. Can you share details about your setup / config, dashboard count, alert rule count, active screens etc

**Comment by wei-hai** [comment]
it has been running for several months without any issue before we upgraded to 4.4.1, previously we were running 4.0.2. We use influxdb, cloudwatch as datasources and we enable LDAP auth in setup / config, nothing else. I think the memory leak might be related to alert error as some alerts report "couldn't find datasource".

<img width="967" alt="screen shot 2017-09-08 at 10 54 13 am" src="https://user-images.githubusercontent.com/2936715/30224698-9823b136-9484-11e7-837f-5d57b1e87b59.png">
