### ISSUE TITLE
RestoreDashboards: Add documentation

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#92003]
- evaluate where to add documentation 
- explain how it works: only available for admins, 30 days until permanent deletion

**Comment by L-M-K-B** [comment]
There's a draft PR with doc changes which are ready to be merged. As soon as RestoreDashboards is GA we can merge the mentioned PR. Until then it's blocked.

**Comment by L-M-K-B** [comment]
The project is currently on hold and will probably be rebuild next year. Additionally the related docs PR got closed automatically.

**Comment by marybaldwin** [comment]
Restore dashboards is in private preview! Here's a link to the epic: https://github.com/grafana/grafana/issues/83620
