### ISSUE TITLE
[bug] prometheus metrics list too small - 4.5.0-beta

### ISSUE THREAD

**Issue by prune998** [grafana/grafana#9203]
Version : Grafana v4.5.0-beta1 (commit: bc69023)
Datasource : prometheus
OS : K8s 1.7 / CoreOs

Issue : 
When using Prometheus Datasource, the "metrics search" field was replaces by an automatic search in the query field. Many metrics names are too wide and are not fully displayed, making it unusable

Expected result : 
the result of the search display full metrics name

Current result : 
search window (overlay) is too small to display the full metrics name
https://www.evernote.com/l/Akyi2-jFPlFJcak2aNRwl0F4Wp94OuAVJGY

**Comment by bergquist** [comment]
This should be fixed before 4.5 stable.
