### ISSUE TITLE
Data Sets: Performance Issue with Large Data Sets

### ISSUE THREAD

**Issue by yzengin** [grafana/grafana#92044]
### What happened?

When using Grafana with large data sets, I've noticed that dashboards become slow, and graphs take a long time to load. This is especially noticeable when querying Prometheus as a data source. The response times for queries significantly increase, negatively impacting the user experience. Additionally, memory usage spikes when handling large volumes of data. Could there be optimizations to improve performance in such scenarios?

### What did you expect to happen?

I expected the dashboards to load quickly and the graphs to be responsive even with large data sets. The performance should be consistent, regardless of the data size.

### Did this work before?

Yes, previous versions of Grafana worked more smoothly with similar data sets, but I’ve noticed the slowdown with the latest version.

### How do we reproduce it?

Steps to Reproduce:

1. Create a dashboard with a large data set.
2. Query Prometheus as the data source.
3. Observe the query response times and memory usage.

### Is the bug inside a dashboard panel?

Yes, the issue occurs within the dashboard panels where large data sets are visualized.

### Environment (with versions)?

Grafana: 11.1.4
OS: Ubuntu 20.04
Browser: Google Chrome 127.0.6533.120 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Prometheus 2.40.0

**Comment by tonypowa** [comment]
hello @yzengin 

Could you share a minimal Git repository where the issue can be reproduced? Also please provide any error messages or logs you're seeing.

Thank you

**Comment by NWRichmond** [comment]
@yzengin a video would help us understand your experience. Is this something you can provide?

**Comment by robhamnett** [comment]
We were running 11.2.2, updated to 11.3 
os - container-optimized os v113 
agent - victoria metrics v0.49.0

**Comment by NWRichmond** [comment]
@robhamnett thank you for the quick reply. One significant change in Grafana 11.3 is that [Scenes-powered Dashboards are generally available](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v11-3/#scenes-powered-dashboards-are-generally-available). As a troubleshooting step, could you try adding `&scenes=false` to the dashboard's URL? If that results in a performance change, that would be helpful info for us :)

**Comment by robhamnett** [comment]
That indeed seemed to have helped.

**Comment by NWRichmond** [comment]
Great to know, thanks for confirming @robhamnett. I think we should create a new issue to capture your experience, as it's a different situation than the one described by the author of this issue.

**Comment by melroy89** [comment]
> This is happening on our instance as well running 11.3 ever since the last update, it struggles to load, complaints from end users etc.

Grafana graphs/data/InfluxDB queries are also causing huge issues since Grafana v11.3 (I'm now running v11.3.1). I notice that the data is loading very slowly. And after several graphs loaded, Grafana fails to load more queries. And basically slowly becomes to a halt. The network tab also showed `NS_BINDING_ABORTED` on the `api/ds/query` (in my case influxdb) API end-point.

Downgrading back to Grafana v11.2 solved all the performance issues and the queries are very fast again. All graph the load all the data again without any issues after downgrading to v11.2.

**Comment by yzengin** [comment]
@NWRichmond 

Thank you for the clear explanation and the suggested steps. I’ve implemented the Use series endpoint toggle and adjusted the Prometheus data source configuration as you described. The performance issue has been resolved, and everything is functioning as expected now.

Your guidance was precise and effective in addressing the problem. I'll ensure these adjustments are considered for similar scenarios in the future.

Best regards,
@yzengin
