### ISSUE TITLE
[Bug] Text Panels revert to 'markdown' mode when put on 'text' mode

### ISSUE THREAD

**Issue by erictoner** [grafana/grafana#9204]
Version: 4.4.3
Datasource: Graphite, Diamond, Dashing
OS: Ubuntu 14.04

After updating to version 4.4 from 4.3, Text Panels in dashboard revert to markdown mode instead of text mode (and never show as text mode.) Other changes to the text box save, even using the HTML mode works, but the 'text' option never changes from markdown.

I tried updating from version 4.4.1 to 4.4.3, restarted the grafana-server service and restarted nginx. This is happening on two separate servers (they're both identical.)

![image-2017-08-15-23-25-31-444](https://user-images.githubusercontent.com/8885487/30219203-55da4aec-9489-11e7-8138-42be316a06f6.png)

![image-2017-08-15-23-24-16-190](https://user-images.githubusercontent.com/8885487/30219209-5aa95540-9489-11e7-89c7-7002e11199b4.png)

**Comment by torkelo** [comment]
thanks for informing us! The text mode was deprecated & removed some versions ago but we forgot to remove it from the settings dropdown.
