### ISSUE TITLE
group by for count only works with numbers with influxDB

### ISSUE THREAD

**Issue by radkin** [grafana/grafana#9205]
Given the following example:
```bash
create database example
use example
INSERT toys,type=marble,size=small,color=blue diameter=1
INSERT toys,type=marble,size=small,color=green diameter=1
INSERT toys,type=marble,size=medium,color=yellow diameter=2
INSERT toys,type=box,size=small,color=yellow diameter=1
INSERT toys,type=box,size=large,color=green diameter=3
```
We end up with the following series:
```bash
> select * from toys
name: toys
----------
time                            color   diameter        size    type
2017-09-08T16:32:26.882533253Z  blue    1               small   marble
2017-09-08T16:32:33.345800845Z  green   1               small   marble
2017-09-08T16:32:39.506119619Z  yellow  2               medium  marble
2017-09-08T16:32:45.715605615Z  yellow  1               small   box
2017-09-08T16:32:52.014982076Z  green   3               large   box
```
When you create a datasource for this (mine was called "example"), you can add templating for type with the following: 
```bash
SHOW TAG VALUES FROM toys WITH KEY = type
```
With this and the following statement in a graph 
```bash
SELECT count("diameter") FROM "toys" WHERE "type" =~ /^$type$/ AND $timeFilter GROUP BY time($__interval), "type" fill(null)
```
 we get attachment "itworks". Here we see that there are a total of 2 box type toys and 3 marble type toys.
However, with this statement in the graph 
```bash
SELECT count("color") FROM "toys" WHERE "type" =~ /^$type$/ AND $timeFilter GROUP BY time($__interval), "type" fill(null)
```
we get "No data points". Why can't we get a count of the number of color green toys, color blue toys, etc. ? More importantly, how do we get this graph?
<img width="1428" alt="itworks" src="https://user-images.githubusercontent.com/467568/30222590-188f3998-947c-11e7-9b8c-ce1369ff3384.png">

**Comment by torkelo** [comment]
For the query where you get the "no data points", please investigate the query Grafana sends and the response from InfluxDB. Do you see anything wrong the query Grafana sends?

https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by torkelo** [comment]
Here is an example that works and match your scenario:

http://play.grafana.org/dashboard/db/influxdb-group-by-count?panelId=1&fullscreen&edit&orgId=1

**Comment by radkin** [comment]
Thanks for the swift reply!
