### ISSUE TITLE
Plugins Platform: Update to react-router v6

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#92066]
Update the plugin-related components to be compatible with react-router v6 according to this checklist:

- [ ] Stop using route props and rely on `useParams()` instead
- [ ] Use `useNavigate()` instead of `props.history` and stop using the `history` package.
- [ ] Use relative links in `<Link>` and `<NavLink>`
- [ ] Replace `Redirect` with `Navigate`
- [ ] Replace `Prompt` with [useBlocker](https://reactrouter.com/en/main/hooks/use-blocker) (requires data-based router so can be done later). 
- [ ] Remove unnecessary Router usage in test files / check if `CompatRouter` can be used instead. 
- [ ] Replace all imports from `react-router-dom` with the alternatives from `react-router-dom-v5-compat` (except within `sharedDependencies.ts` and `grafana-plugin-configs/webpack.config.ts` which should not be touched until the time comes to remove support for react router 5 from plugins).

List of files:

- [x] `/public/app/features/connections/Connections.tsx`
- [x] `/public/app/features/connections/hooks/useDataSourceSettingsNav.ts`
- [x] `/public/app/features/connections/pages/DataSourceDashboardsPage.tsx`
- [x] `/public/app/features/connections/pages/DataSourceDetailsPage.tsx`
- [x] `/public/app/features/connections/pages/EditDataSourcePage.tsx`
- [x] `/public/app/features/datasources/components/DataSourcesList.test.tsx`
- [x] `/public/app/features/plugins/admin/pages/PluginDetails.test.tsx`
- [x] `/public/app/features/plugins/admin/pages/PluginDetails.tsx`
- [ ] `/public/app/features/plugins/components/AppRootPage.test.tsx`
- [ ] `/public/app/features/plugins/components/AppRootPage.tsx`

**Comment by jackw** [comment]
@Clarity-89 I've made some minor edits to the issue description to prevent whoever picks up this task from breaking support for loading plugins that continue to rely on react-router v5.
