### ISSUE TITLE
Any way to increase templating variable value character max over 20?

### ISSUE THREAD

**Issue by taichatha** [grafana/grafana#9206]
I am grabbing the time as one of my templating variable, but because of the precision, the value gets cut off at the 20 character mark.

**Comment by torkelo** [comment]
you mean it gets cut of in the display of the value in the dropdown? 

it does not get cut off for me 
![image](https://user-images.githubusercontent.com/10999/30265655-11ae9aca-96dd-11e7-8898-13d1eb0355b8.png)
