### ISSUE TITLE
Crate-Alerting: The datasource does not support alerting queries

### ISSUE THREAD

**Issue by fwb7014** [grafana/grafana#9207]
I`am submmting a bug:
  Use CrateDB, when setting the alert.
            The datasource does not support alerting queries

grafana-version:4.4.3
centos:6.8
datasource:cratedb

EROR[09-09|21:33:21] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="延迟 alert" error="tsdb.HandleRequest() error Could not find executor for data source type: crate-datasource" changing state to=keep_state

**Comment by bergquist** [comment]
Alerting is not available for plugin at the moment. 
We need to add support for backend plugins first. https://github.com/grafana/grafana/issues/6841

**Comment by addysunn** [comment]
Hi Carl, I am facing the same issue with simple-json-datasource and datasource is SAP HANA DB.

**Comment by markteehan** [comment]
@addysunn did you succeed in getting this to work; or did you find a workaround?

**Comment by andrius-finnplay** [comment]
Can you tell if this error is related? "Execution Error: tsdb.HandleRequest() error Could not find executor for data source type: alexanderzobnin-zabbix-datasource"
