### ISSUE TITLE
Azure Monitor Basic Logs: Existing Basic Log queries still run after Basic Logs option is disabled in datasource

### ISSUE THREAD

**Issue by kayodeprinceMS** [grafana/grafana#92104]
### What happened?

After enabling Basic Logs in the Azure Monitor datasource settings, dashboards and panel queries work as expected when panels are set to Basic option. However, after disabling the Basic Logs option in the datasource, dashboards and panels continue to work when the feature has been disabled. This is not the expected behavior. I would expect the datasource setting to be enforced and prevent any basic logs queries from being run.

When the panel is open for editing, the query does not run and this is more in line with the expected behavior.

![image](https://github.com/user-attachments/assets/5f0e4ef1-29c3-4417-bb79-9a7bfb48d62b)

![image](https://github.com/user-attachments/assets/d44ffc57-7450-405d-8da9-fb214bf68cdd)

### What did you expect to happen?

I expect all existing panels configured with basic logs to not run, or for the queries to fail if datasource setting disables the feature.

### Did this work before?

No.

### How do we reproduce it?

1. Enable Basic Logs in Azure Monitor plugin datasource config
2. Create and save dashboards using Basic Logs queries
3. Set Basic Logs to disabled in Azure Monitor plugin config.
4. Open existing dashboards to see successful queries.

### Environment (with versions)?

Grafana: 11.1
OS: Windows
Browser: Chrome and Edge

### Grafana platform?

Other

### Datasource(s)?

Azure Monitor

**Comment by kayodeprinceMS** [comment]
cc: @taleena for tagging

**Comment by taleena** [comment]
Thanks for the report - after turning Basic Logs off, if you go to the dashboard, make any change (anything small), and save the entire thing, (alternatively, force a refresh) do those queries then stop working as expected? I'm wondering if perhaps caching is a culprit given your detail about the panel edit.

**Comment by kayodeprinceMS** [comment]
Editing the panel and resaving produces the expected behavior. The basic logs panel-level toggle is not visible in the edit experience so any edits will be run using Analytics queries.
