### ISSUE TITLE
[Feature request] show template variable candidate in Prometheus code editor

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#9210]
May be, we need to add completer for Grafana template variable.

**Comment by torkelo** [comment]
good idea!

**Comment by alexanderzobnin** [comment]
@bergquist @torkelo which milestone should we apply? Guess `5.1`?

**Comment by torkelo** [comment]
@alexanderzobnin always move issue and PR to the next release milestone (when merged to master)

**Comment by marefr** [comment]
Closed by #9988
