### ISSUE TITLE
 Pie Chart & Data Table not identifying fields correctly - ElasticSearch

### ISSUE THREAD

**Issue by luvpreetsingh** [grafana/grafana#9211]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 

I did. https://community.grafana.com/t/pie-chart-data-table-not-identifying-fields-correctly/2672

- Checkout FAQ: https://community.grafana.com/c/howto/faq

- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?  - 	Grafana v4.2.0 (commit: 349f3eb) 
- What datasource are you using?  - Elasticsearch 5.2
- What OS are you running grafana on?  - ubuntu 16.04
- What did you do? - Added a query to get the simple text fields 
- What was the expected result? - The text fields should be fetched simply. 
- What happened instead? - The fields were not fetched as they were stored.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 

There is some misbehaviour in grafana Pie chart and Data Table.

I have a field called **Sites** in elasticsearch. 

Here is the problem, 

The field names are like this, 

* ABC University
* XYZ college
* MNO school

Now, when I use the group by query on these sites, these are taken as 6 sites,

* ABC
* University
* XYZ
* College
* MNO
* College

![screenshot from 2017-09-08 17-51-34](https://user-images.githubusercontent.com/23127804/30261323-b019df60-96e9-11e7-95fb-ba5611deabc2.png)

These are 3 sites, taken as 6 sites.
 
The same thing happens in Data Table.

**Comment by torkelo** [comment]
you need to use keyword or raw fields. Elasticsearch analyses strings and index each word separately by default
