### ISSUE TITLE
Alerting: Typo in provisioning API

### ISSUE THREAD

**Issue by not7cd** [grafana/grafana#92157]
There is a typo, dasboardUid
https://github.com/grafana/grafana/blob/cab5818bc74840818803f9779ae7e6887b56ca42/pkg/services/provisioning/alerting/rules_types.go#L69

This PR meant to solve it was shelved https://github.com/grafana/grafana/pull/65143

**Comment by JacobsonMT** [comment]
Fixed by https://github.com/grafana/grafana/pull/65143
