### ISSUE TITLE
Explore: Grafana(v11.0) doesn't use time range with Tempo data source

### ISSUE THREAD

**Issue by pyo-counting** [grafana/grafana#92173]
### What happened?

This is happened when i use the `query by traceid` in the Explore tab. When Grafana call the [`GET /api/traces/<traceid>?start=<start>&end=<end>` endpoint](https://grafana.com/docs/tempo/latest/api_docs/#query) of Tempo, it doesn't use start, end querystring parameters. As a result, trace that do not belong to the time range picker are found.

Grafana explore tab(timezone: Asia/Seoul, UTC+0900)
<img width="1311" alt="Grafana explore tab" src="https://github.com/user-attachments/assets/1ac49709-978a-41f1-8e63-da37571ddf1c">

Tempo query-frontend log(UTC)
```
level=info ts=2024-08-21T03:08:45.117030894Z caller=traceid_handlers.go:63 msg="trace id request" tenant=kurlypay path=/api/traces/e2f5205076f7bd0101c817ea27abc6db
level=info ts=2024-08-21T03:08:45.828177797Z caller=tracqueid_handlers.go:77 msg="trace id response" tenant=kurlypay path=/api/traces/e2f5205076f7bd0101c817ea27abc6db duration_seconds=0.711122266 err=null
level=info ts=2024-08-21T03:08:45.828331688Z caller=handler.go:133 tenant=kurlypay method=GET traceID=4c1ee47dbf765af7 url=/api/traces/e2f5205076f7bd0101c817ea27abc6db duration=711.188004ms response_size=14767 status=200
```

### What did you expect to happen?

We thought Grafana would call the trace by id query endpoint of Tempo using the time range picker value of the Grafana explore tab. But that was not the case, and as a result, we could see the traces that do not belong to the time range picker.

### Did this work before?

This is our first time using Tempo, so we are experiencing it for the first time.

### How do we reproduce it?

1. deploy Tempo with helm(chart version: 1.16.2)
2. deploy Grafana with helm(chart version: 8.3.5)

### Environment (with versions)?

Grafana: 11.1.0
OS: EKS(v1.25) on EC2
Browser: Naver Whale(3.27.254.15(arm64 build))

### Grafana platform?

Kubernetes

### Datasource(s)?

tempo 1.16.2

**Comment by cancub** [comment]
To add to the troubles with this issue: if you've got a ton of blocks in the backend, you're going to be seeing a lot of timeouts, which is very confusing for users who've selected something like a 5-minute time range.

We've been running into this at Morgan Stanley and we're considering a rollback to Grafana 10 resolve the issue for now, because the Tempo datasource has become unusable for some users. I imagine big institutional users of grafana's cloud services will be running into this soon.

**Comment by cancub** [comment]
In my case it was actually a bad configuration. We had disabled `traceQuery` in the tempo datasource in grafana 10.0.3 due to the time shift error in the datasource. This was resolved, but we forgot to re-add `traceQuery`.

**Comment by pyo-counting** [comment]
@cancub 
Thank you so much. I aslo checkd that i deactivated that setting. After activating it, I can see that `query by traceId` use start, end querystring parameter.
