### ISSUE TITLE
cannot run grafana on windows

### ISSUE THREAD

**Issue by sophir** [grafana/grafana#9219]
Hi
Just extracted the files, can not run grafana client. 
The server is running.
I commented out the port, changed it to 8080
When I run the client, I get a splash of a window for a second, then it collapses.
Standard Windows 7, 64-bit operating system.
PLS help
Thanks,
Shai

**Comment by bergquist** [comment]
Could you please explain what you mean with the "grafana-client". Are you refering to grafana-cli.exe?
If you comment out port and then change it to 8080 it wont take affect. It will still use the default port (3000)

**Comment by sophir** [comment]
Hi.
Yes, i meant the grafana-cli.exe
Maybe i should not run it at all? I thought this is the GUI
As for the port, i removed the ";" and changed 3000 to 8080. Is this what i should do?
Thanks a lot
Shai


נשלח ממכשיר הסמסונג שלי


-------- הודעה מקורית --------
מאת: Carl Bergquist <notifications@github.com>
תאריך: 11/09/2017 19:05 (GMT+02:00)
אל: grafana/grafana <grafana@noreply.github.com>
עותק: Shai Ophir <Shai.Ophir@Starhomemach.com>, Author <author@noreply.github.com>
נושא: Re: [grafana/grafana] cannot run grafana on windows (#9219)


Could you please explain what you mean with the "grafana-client". Are you refering to grafana-cli.exe?
If you comment out port and then change it to 8080 it wont take affect. It will still use the default port (3000)

**Comment by torkelo** [comment]
please use community site for questions. https://community.grafana.com

For running Grafana on windows: From the docs: http://docs.grafana.org/installation/windows/

> Start Grafana by executing grafana-server.exe, preferably from the command line. If you want to run Grafana as windows service, download NSSM. It is very easy add Grafana as a Windows service using that tool.

**Comment by sophir** [comment]
Hi.
Yes, i meant the grafana-cli.exe
Maybe i should not run it at all? I thought this is the GUI 
As for the port, i removed the ";" and changed 3000 to 8080. Is this what i should do?
The server is running , I just double clicked  the grafana-server.exe But I have no GUI, no application. 
Thanks a lot
Shai
