### ISSUE TITLE
[Bug] Alerting: Error: tsdb.HandleRequest() error context deadline exceeded - grafana:4.3.2

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#9220]
- What Grafana version are you using? -- grafana:4.3.2
- What data source are you using? -- InfluxDB
- What OS are you running grafana on? -- CentOS Linux release 7.3.1611 (Core) 
- What did you do?  
I enabled alerting + notification. I see an alert triggered [ON state] with "tsdb.HandleRequest() error context deadline exceeded" . After a while, this alert went away [OFF state] and its being in ON/OFF state steadily. Right now this alert is OFF.
- What was the expected result?
What is the meaning of this error?
Can I disable notification for this type of error?

**Comment by deepujain** [comment]
I read https://github.com/grafana/grafana/issues/8006 and could not figure out what was the solution to it, if any ?

**Comment by bergquist** [comment]
@deepujain it means the alert rule execution took to long time. The default total alert execution timeout is 30 seconds. Is such slow queries expected? 

You can set "If execution error or timeout" to "Keep last" if you want to avoid these errors.

**Comment by deepujain** [comment]
@bergquist +1

**Comment by bergquist** [comment]
```json
{
  "alert": {
    "executionErrorState": "keep_state"
  }
}
```

**Comment by bergquist** [comment]
Re opening this issue since the error message could be improved.

**Comment by deepujain** [comment]
I monitor disk usage alert for every machine. I have 100+ machines, is there a way to automatically generate 100 widgets?

**Comment by deepujain** [comment]
I see a second config "If no data or all values are null" then set state to alerting or so on.

Does this mean the agent collecting metrics (telegraf in my case), did not collect metric and store into TSDB ( influx in my case ) , something went wrong with telegraf ?
