### ISSUE TITLE
Can not run grafana-server on windows

### ISSUE THREAD

**Issue by sophir** [grafana/grafana#9222]
I unziped the files
I uncommented the port line, chanegd to 8080
I run the server, from the command line or by double clicking, the window is opening, it executes few things, then it is waiting.
Where is the GUI? 
Why I need to configure things on Windows?..
PLS HELP

**Comment by torkelo** [comment]
please use community site for questions

**Comment by torkelo** [comment]
grafana has a web ui, try open page in a web browser. (http://localhost:8080 if that is what you successfully changed port to)
