### ISSUE TITLE
Prometheus server failed to restart with error dial tcp 127.0.0.1:9090: connect: connection refused"

### ISSUE THREAD

**Issue by prasanthcavli** [grafana/grafana#92268]
### What did you expect to happen?

The prometheus server is expected to running without any crashes

### Did this work before?

Yes

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by NWRichmond** [comment]
Hi @prasanthcavli! I'm not clear about the relationship of this issue to Grafana. Were you using helm charts from https://github.com/prometheus-community/helm-charts? If so, I believe that's the right place to create an issue related to Prometheus helm charts.
