### ISSUE TITLE
[Bug] Empty screen and a console error when trying to create a new Dashboard

### ISSUE THREAD

**Issue by marcantoine-bibeau** [grafana/grafana#9227]
I'm getting an empty screen and a console error when trying to create a new Dashboard

See screencast: https://screencast.com/t/sIoZULv1L
traces: 
![image](https://user-images.githubusercontent.com/6455702/30337773-5b20e75a-97b7-11e7-9b7c-623d39ec192c.png)

Please include this information:
- What Grafana version are you using? 4.4.3 (Working fin in version 4.1.2)
- What datasource are you using? InfluxDb
- What OS are you running grafana on? MacOS
- What did you do? Creating a new Dashboard
- What was the expected result? View an empty dashboard
- What happened instead? Blank screen and console error (See screencast + attached screenshot)
- If related to metric query / data viz: Not related

**Comment by torkelo** [comment]
what browser and version are you running? Any custom plugins?

**Comment by marcantoine-bibeau** [comment]
I tried with later Chrome and latest Firefox :(

**Comment by marcantoine-bibeau** [comment]
@torkelo Do you have everything you need?

**Comment by torkelo** [comment]
been unable to replicate and no other reports

**Comment by marcantoine-bibeau** [comment]
I'm able to reproduce on my end every time :( Is there something I could do to help investigating?

**Comment by torkelo** [comment]
Try removing any installed plugins, try running in incognito mode

What chrome version are you using?

**Comment by marcantoine-bibeau** [comment]
I have cleaned everything and re-imported my dashboards... Seems to work now... Impossible to say what really the problem was but let's not waste time for this. 

Thanks a lot for your help!

P.S. Good job with grafana!
