### ISSUE TITLE
[Bug] Alert condition doesn't work when ending time is not now

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9228]
Please include this information:
- What Grafana version are you using?
4.4.1
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos
- What did you do?
1. set starting and ending times to 10m and 3m
2. test alert condition
- What was the expected result?
suppose the data points are [1,2,3,4,5,6,7,8,9,10]
the alert should run on [1,2,3,4,5,6,7,8]
- What happened instead?
however, it runs on [1,2,3,4,5,6,7,10]

<img width="619" alt="screen shot 2017-09-12 at 1 14 34 pm" src="https://user-images.githubusercontent.com/2936715/30346066-5dd898e4-97bc-11e7-82ae-d8a9c6a79c27.png">

<img width="466" alt="screen shot 2017-09-12 at 1 14 19 pm" src="https://user-images.githubusercontent.com/2936715/30346071-61d3f33a-97bc-11e7-8c77-88df10def07d.png">

<img width="361" alt="screen shot 2017-09-12 at 1 14 27 pm" src="https://user-images.githubusercontent.com/2936715/30346075-670fe4d0-97bc-11e7-8bef-5a276622230b.png">

**Comment by torkelo** [comment]
tried to replicate and InfluxDB is returning the expected data for me. More importantly it is generating the correct query. 

`time > now() - 10m and time < now() - 3m`  So the last data point being incorrect must be somehow due to InfluxDB. `
