### ISSUE TITLE
[Bug] Graph display is not proper when we switch between X-axis "mode" (time,series,histogram)

### ISSUE THREAD

**Issue by sudhe** [grafana/grafana#9229]
Please include this information:
Grafana version :  Grafana v4.4.3 (commit: 54c79c5)
Datasource : Graphite
OS : linux
Prerequisite : 
1) Under AXES --> X-axis --> mode = Time
2) Under Display --> draw modes --> line and points
![image](https://user-images.githubusercontent.com/8737888/30361264-9f378496-9873-11e7-968a-a4296533cf2c.png)

scenario : 
1) Now change AXES --> X-axis --> mode = "series" and then again revert it to "Time" 

Expected : We should get old "line and points" graph
Actual     : we are getting "BAR" graph (draw mode changed to bar and not reverted)
![image](https://user-images.githubusercontent.com/8737888/30361377-49de20bc-9874-11e7-9fe9-6465b7a6232b.png)

If above is valid/expected behavior, I will move forward and change 
1) "DISPLAY" -->  draw modes --> line and points
2) Change AXES --> X-axis --> mode = "series" 
I am getting below graph (In this case it will not change to BAR graph)
![image](https://user-images.githubusercontent.com/8737888/30361542-32ecd578-9875-11e7-9d4d-c089c9289753.png)

**Comment by torkelo** [comment]
do you have series overrides enabled? the series names looks a bit too long and the series are too many to be shown properly

**Comment by sudhe** [comment]
I did alias metrics name but still i am getting above graph (If I give small alias name I can overcome this problem). But issue is different "Why we are switching/changing  draw-modes from line,points to BAR when switching from time to series/histogram" ?

**Comment by torkelo** [comment]
because lines / points make little sense for histogram / series mode. bars make more sense so grafana switches automatically

**Comment by sudhe** [comment]
As I mentioned in issue, If I continue the same procedure 
After automatic switch : 
"DISPLAY" --> draw modes --> line and points
Change AXES --> X-axis --> mode = "series"
In this case it will not change to BAR graph. Please refer my initial post

**Comment by torkelo** [comment]
as I what you mean, it's when you switch back and forth, seems like the defaults are only applied once. 
thanks for reporting this. fixed in last commit .-
