### ISSUE TITLE
[Graphite]: Update query editor to support new tagging features

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9230]
Graphite (master branch) now has support for tagging. 

https://github.com/graphite-project/graphite-web/pull/2002

Example queries:
seriesByTag("name=my.metric.name.count", "tagKey=~tagValueRegex")

The query editor already supports starting with a function (for example try asPercent, sumSeries), this will remove the metric select before. 

To get started on this issue 
1) Get graphite master running
2) Get carbon master running and update fake data gen (https://github.com/grafana/fake-data-gen) so it can send data to graphite with tags
3) add seriesByTag function 
4) Make seriesByTag easier to use (add / remove arguments, tag key lookup & tag value lookup), not sure how to do this yet

**Comment by torkelo** [comment]
So the idea is to be able to do something like this:
![image](https://user-images.githubusercontent.com/10999/31161909-9145d05a-a8da-11e7-9fb9-15acce027d48.png)

Don't know how this can be done though. will have to parse seriesByTag arguments and make UI segments out of them.

**Comment by torkelo** [comment]
Initial work on this is merged and implemented:

![image](https://user-images.githubusercontent.com/10999/32947217-19775542-cb9b-11e7-8ee3-f1dadfd63878.png)

Created new issue for remaining work that will have to wait a few weeks until after we have merged develop branch and released v5 alpha.

https://github.com/grafana/grafana/issues/9911

**Comment by admin-pro** [comment]
Hello,

I'm currently running with the graphite version 0.9.13 (i'm not sure).

How i can upgrade from my actual version to the latest(v1.1.1) please ?

I need to reinstall from scratch and migrate my data or i can perform an upgrade inplace.

Thank you very much guys.

Have a nice day and happy new year
