### ISSUE TITLE
Values from one label showing up in another

### ISSUE THREAD

**Issue by zhehao-grafana** [grafana/grafana#92307]
See:
https://raintank-corp.slack.com/archives/C0630AYC4SY/p1708936490386859?thread_ts=1708729435.077859&cid=C0630AYC4SY

There is a bug where some job and namespace values are showing under the route label
![Image](https://github.com/grafana/grafana/assets/5264102/d1e58703-bf1c-423a-b186-64a0b581340a)

To replicate:
Data source: dev-cortex
Metric: job_route_cluster:pyroscope_request_duration_seconds_bucket:sum_rate

If you go under breakdown --> look at the aggregated route graph you can see job values like dev-us-east-0 or namespace values. However they do not show when you select the route label, and view each value.

- Different aggregations (irate, increase) - I believe there's another issue for this

**Comment by NWRichmond** [comment]
I believe that this is likely a duplicate of https://github.com/grafana/grafana/issues/91510.

**Comment by zhehao-grafana** [comment]
> I believe that this is likely a duplicate of [#91510](https://github.com/grafana/grafana/issues/91510).

Yup, you are right, and I will close down this one
