### ISSUE TITLE
[Bug]How to recover crashed 'traceur' in grafana?

### ISSUE THREAD

**Issue by gnh1201** [grafana/grafana#9231]
Please include this information:
- What Grafana version are you using? 4.4.3.
- What datasource are you using? Nothing.
- What OS are you running grafana on? ubuntu 14.04
- What did you do? Grafana plugin development.
- What was the expected result? Well done all.
- What happened instead?

I'm having trouble from crashed 'traceur' error (404 not found) during plugin delvelopment.
I am always afraid because I have to reinstall grafana whenever this error occurs.

`(SystemJS) XHR error (404 Not Found) loading http://localhost:3000/public/traceur?bust=1505290982387 Error loading http://localhost:3000/public/traceur Unable to load transpiler to transpile http://localhost:3000/public/plugins/custom-control-panel/module.js Error loading http://localhost:3000/public/plugins/custom-control-panel/module.js`

How to prevent crash traceur? and how to recover traceur?
If this is problem of my plugins, how to create and view logs about this errors?

- If related to metric query / data viz: data viz

**Comment by torkelo** [comment]
seems like an issue with traceur (which we dont use, so not sure how to help)

> I'm having trouble from crashed 'traceur' error (404 not found) during plugin delvelopment.
I am always afraid because I have to reinstall grafana whenever this error occurs.

reinstall? That sounds very strange. would recommend using webpack or systemjs builder and not do live transpiling

**Comment by finnci** [comment]
@gnh1201 did you ever resolve this issue? I ran into it just now when customising some plugins for grafana4.0.

**Comment by gnh1201** [comment]
@finnci Hello. I saw this issue when customizing my plugin, too.
I did not found how to solve. but it is not only traceur but also grafana.
Becuase, I wasn't manipulate anything related to traceur.

If you saw this issue, you will not recover. it is so hard.

I was solve this issue with this steps:
- purge(completely uninstall) grafana, and reinstall it.
- refactoring my plugin
