### ISSUE TITLE
[Bug] rounding of Y-axis units leads to wrong labels

### ISSUE THREAD

**Issue by mstud** [grafana/grafana#9232]
When selecting a unit like "short" or "kilowatt (kW)" for the y-axis, the labels in the kilo range are always rounded to one digit after the decimal point, which leads to plainly wrong labels in some cases.
E.g., when choosing a range from 0 to 1500, there will be a tick 1.3 K which actually should be 1.25 K. 

![grafana_scale_bug](https://user-images.githubusercontent.com/681715/30368891-e52612f2-9872-11e7-929a-81f5eb6d0a93.png)
As you can see here, the points appear to go above the 1.3 MW line, even though they are definitely under 1300 kW in absolute value. That's because the tick line actually represents 1250 kW but is labelled falsely due to the rounding. I'd prefer to have slightly wider labels rather than a wrong chart.

(This happens with Grafana version 4.4.3.)

**Comment by torkelo** [comment]
Agree this looks wrong. Thanks for reporting this. 

Not sure what the best solution is, add more decimals to auto decimal logic when scaling units or round down for y-axis ticks.

**Comment by torkelo** [comment]
This was fixed sometime during 6.x
