### ISSUE TITLE
[BUG] LDAP user group mapping does not work as expected

### ISSUE THREAD

**Issue by mengine23** [grafana/grafana#9233]
Hey there!

I'm trying to get a useful LDAP integration to work. The integration of LDAP is not the real deal, this seems to be really easy to implement and works like a charme. If you want to go further and map groups to different roles over in grafana, it seems that those "group_dn" mappings don't work properly.

Wildcards for example (*) work. But if i try to map a LDAP specific group to a grafana role, this is what im getting as result in the logs **groups=[]**. Seems that the array of groups is emtpy. Any suggestions?

**Feel free to get some system informations:**
- What Grafana version are you using?
Grafana v4.4.3 (commit: 54c79c5)
- What datasource are you using?
To stick to my problem, Windows Active Directoy
- What OS are you running grafana on?
Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
- What did you do?
Trying to map AD groups to grafa roles (especially "Admin" & "Editor")
- What was the expected result?
Working mapping due to [Grafana Docs](http://docs.grafana.org/installation/ldap/)
- What happened instead?
msg="Ldap Auth: user does not belong in any of the specified ldap groups" logger=ldap username=Foo.Bar groups=[]
 

Thanks in advance,
Chris

**Comment by torkelo** [comment]
If the groups is empty it means grafana as not been able to get user groups from ldap, this can be fetched either by configuring the member of attribute (a ldap feature only some ldao severs support), the other way is to set group search options and have grafana query for groups, this requires you to set the search base and search queries correctly

**Comment by mengine23** [comment]
@torkelo 

> this can be fetched either by configuring the member of attribute (a ldap feature only some ldao severs support)

The member_of attribute was correctly set to the memberOf attribute in LDAP. I have checked this twice. So this is exactly what i am doing...

The other way you decribe is not documented, so i would be great to get more informations on this...

Anyway it seems just like a workaround, the correct fetching of group is still bugged in my eyes.

**Comment by torkelo** [comment]
> Anyway it seems just like a workaround, the correct fetching of group is still bugged in my eyes. 

Strange, memberOf is working for me (and others, as no other reports on this not working). As I mentioned only some ldap servers have this feature (as this property is a "pseudo propery" that ldap servers calculate when you fetch an entity).

Are you sure your ldap server has the memberOf module enabled. Here is a guide for OpenLDAP: https://adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/

In ldap.toml file there is a commented out section that describes how you can use the alternative method.
```ini
# In POSIX LDAP schemas, without memberOf attribute a secondary query must be made for groups.
# This is done by enabling group_search_filter below. You must also set member_of= "cn"
# in [servers.attributes] below.

## Group search filter, to retrieve the groups of which the user is a member (only set if memberOf attribute is not available)
# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
## An array of the base DNs to search through for groups. Typically uses ou=groups
# group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]
```ini

**Comment by mengine23** [comment]
> Strange, memberOf is working for me (and others, as no other reports on this not working). As I mentioned only some ldap servers have this feature (as this property is a "pseudo propery" that ldap servers calculate when you fetch an entity).

I am pretty sure our LDAP got this, as i said we use a Windows Actice Directory server. All the other tools got no problem with fetching users from groups. So this looks really weird for me.
