### ISSUE TITLE
[Bug] Alert not triggering and threshold not shown on graph panel after dashboard is created using API

### ISSUE THREAD

**Issue by EdgarsM** [grafana/grafana#9234]
- What Grafana version are you using?
  4.0.2
- What datasource are you using?
  Graphite
- What OS are you running grafana on?
  CentOS
- What did you do?
  1. Create/update alert notification.
  2. Create a dashboard containing graph panel with alert referencing alert notification created in step 1.
  3. Run some tests that send data to Graphite that should trigger alert.
- What was the expected result?
  Alert is triggered.
- What happened instead?
  Alert is not triggered. Only after going to Edit view of specified dashboard and opening alerts tab alert condition threshold is shown on graph and after saving Dashboard without doing any changes alert is triggered. Compared dashboard definition JSON before and after opening and saving dashboard - no changes are made after dashboard is saved using UI.

**Comment by torkelo** [comment]
How did you save dashboard using api? The UI uses the same api so it's strange :)

**Comment by EdgarsM** [comment]
By POSTing data to /api/dashboards/db

**Comment by torkelo** [comment]
Strange, that is the same api the UI use.

**Comment by EdgarsM** [comment]
@torkelo, tried to do the same using Grafana UI - create dashboard and alert without saving dashboard. After both dashboard metrics and alert tab is filled I saved the dashboard. When I return back to edit view after dashboard is saved I do not see any data in alerts tab. 
Isn't the problem I described previously  in issue description related to fact, that when dashboard with alert is saved for first time, alerts JSON is saved together with dashboard definition but actual alerts are not set up because at that moment dashboard and panel ids are not assigned yet? Please see following code:
[DashAlertExtractor:150](../blob/b4fd6f2d45386a280f6023c2031a1d5d99964e03/pkg/services/alerting/extractor.go#L150)
[Alert:86](../blob/b4fd6f2d45386a280f6023c2031a1d5d99964e03/pkg/models/alert.go#L86)

**Comment by EdgarsM** [comment]
I managed to create a dashboard and alert that triggers as expected (with single API call). If "id" is provided for panel that contains alert then after dashboard creation alert is properly saved and it's state is changed without a need to save a dashboard once again. Note that I do not need to provide dashboard id for new dashboard.

**Comment by EdgarsM** [comment]
So I am not sure this implementation specifics should be considered a bug, rather it should be stated somewhere that panel definition should contain panel id in case dashboard with alert is created by API call.

**Comment by torkelo** [comment]
panel ids are always required for any dashboard not just panels with alerts.

**Comment by EdgarsM** [comment]
Probably, but if one does not provide it Grafana still will save a dashboard without returning validation errors.

**Comment by EdgarsM** [comment]
So as a quick recap: dashboard id is generated by Grafana on server side when dashboard is created and it is globally unique. Panel id is filled on UI and should be unique inside singe dashboard therefore if somebody is creating dashboard not from UI he should assign panel id manually.

**Comment by EdgarsM** [comment]
Thanks guys for your time and help
