### ISSUE TITLE
Alerting: user can select a query itself as alert condition

### ISSUE THREAD

**Issue by sae-artem** [grafana/grafana#92349]
### What happened?

When a user defines an alerting query and a threshold and accidentally clicks "Set as alert condition" on the query instead of threshold, the alert won't be firing, because there is no condition.
![image](https://github.com/user-attachments/assets/d2403f8b-692c-48d1-861b-39cd24d69889)

### What did you expect to happen?

I would expect that the user has **no** ability to set query as alert condition, because it doesn't make sense to me why would anyone do that.

There is already an error pop-up implemented if you're trying to use timeseries as alert condition, but why it's possible to use scalars as alert conditions?
![image](https://github.com/user-attachments/assets/3673a204-6634-458d-884a-1dc4e3a3c97d)

### Did this work before?

Not sure

### How do we reproduce it?

1. Create an alert.
2. Specify a query.
3. Click on "Set as alert condition"

### Environment (with versions)?

Grafana: Grafana v10.3.1 (00a22ff8b2)
OS: MacOS
Browser: Firefox

### Grafana platform?

I don't know

### Datasource(s)?

Prometheus

**Comment by nagisa** [comment]
> I would expect that the user has no ability to set query as alert condition, because it doesn't make sense to me why would anyone do that.

FWIW I do it frequently. That said I'm using data sources other than prometheus where it is more straightforward to set up queries that return non-zero values only if an alert should be fired. This allows for fancier logic than whatever alertmanager can… manage.

**Comment by santihernandezc** [comment]
> I would expect that the user has no ability to set query as alert condition, because it doesn't make sense to me why would anyone do that.

This is the expected behavior. For example, it's how [Prometheus alerts](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) work, non-zero metrics can be used to make an alert fire.

We're working on simplifying the alert creation flow, [query and expression simplification](https://github.com/grafana/grafana/pull/93022) will be shipped in v11.3 and it won't allow selecting a query as an alert condition.
