### ISSUE TITLE
Dashboard: Undo for Dashboard Deletes

### ISSUE THREAD

**Issue by smachiz** [grafana/grafana#9235]
Simply, deleting a dashboard is quite permanent - and I'd love to be able to restore an inadvertently deleted dashboard.

**Comment by bergquist** [comment]
When deleting dashboards we remove them from dashboard_versions as well. Keeping deleted dashboards in dashboard_version would allow this to be added. But I'm not sure we would like to introduce such behavior.

**Comment by Diegonarducci88** [comment]
+1

**Comment by prankousky** [comment]
Please add this feature! I meant to delete a single test dashboard while working on it and deleted ALL my dashboards o.O

**Comment by poldim** [comment]
+1

**Comment by drichelson** [comment]
Hi, I'm interested in implementing the backend (ie api-only) implementation of this feature. What is the next step?

**Comment by gisfinder** [comment]
+1
When I want to delete annotation, I did not found any button to delete it. Then in the left bar I found one and press it. Oh my god, it delete the dashboard.

**Comment by slick666** [comment]
+1

**Comment by trajakovic** [comment]
+1 same as @gisfinder, maybe UX is not so clear for some things, so undo delete dashboard would be great

**Comment by mdhms** [comment]
+1 thought i delete an annotation and instead deleted a dashboard...

**Comment by Kamapcuc** [comment]
+1

**Comment by sbach89** [comment]
+1

**Comment by komarov134** [comment]
+1

**Comment by ThorsteinnMarCcp** [comment]
+1

**Comment by jab1982** [comment]
+1

**Comment by alefhsousa** [comment]
+1

**Comment by un000** [comment]
The same, i've deleted my dashboard deleting an annotation

**Comment by dustinblack** [comment]
Another deleted dashboard when trying to delete an annotation, here. Please implement this and/or fix the UI.

**Comment by overcookedpanda** [comment]
Just deleted a dashboard when trying to delete a variable.. i support this request.

**Comment by ushuz** [comment]
> Just deleted a dashboard when trying to delete a variable.. i support this request.

same here. I think grafana can just keep dashboard_version after deletion.

**Comment by maracuja-juice** [comment]
Is there not a different way for a user to 'restore' a deleted dashboard other than to recreate it manually?

**Comment by mgresser** [comment]
I've got a script I run via cron to backup all my dashboards as json objects which is my safety net in case someone deletes a dashboard.

**Comment by maracuja-juice** [comment]
@mgresser
Could you share that script?

**Comment by mgresser** [comment]
Sure, I just cleaned out anything sensitive and published it to git.

https://github.com/mgresser/backup_grafana/blob/master/backup_grafana.sh

You'll need jq on the host it runs from and you'll need to edit the variables at the start of the script. Feel free to use as you see fit. No warranty or promise that I'll keep it updated but feel free to use it as a starting point.

**Comment by BonMatts** [comment]
+1 brand new to grafana, just deleted a dashboard accidentally, thought i was deleting a panel.

**Comment by llirikk** [comment]
+1 accidentally deleted the dashboard while clicking on versions panel.
Fortunately restored everything from another browser tab opened - the app keeps all the frontend in browser memory, even the panel with json of the dashboard

**Comment by torkelo** [comment]
There is a pretty big confirm modal, did you not get that?

If the dashboard contains an alert there is even more, you have to write DELETE in confirm model.

But I still think having a undo here would be really great.

**Comment by bergquist** [comment]
@Ijin08 perhaps you could look into this flow and see if there are any improves we could try before implementing restoring deleted dashboards?

**Comment by devils-ey3** [comment]
> +1 thought i delete an annotation and instead deleted a dashboard...

Same here :(

**Comment by Megaten-NZ** [comment]
+1 just deleted extensive dashboard after hours of setting it up when clicked through the modal thinking I was removing a panel. Yes - my trigger happy mistake. Could really use those hours back or an undo option...

**Comment by daytonpa** [comment]
Just deleted a dashboard version, and my entire Dashboard deleted as well.  Is this supposed to happen?

**Comment by Ijin08** [comment]
You can't delete a Dashboard version, at least not in the ui as I can see. So I guess you simply deleted the dashboard. Sorry about that.
Guess we have to move that delete button or make it clearer.

**Comment by amihazbani** [comment]
+1 dashboard deleted mistakenly while trying to delete variable

**Comment by wushbin** [comment]
+1 dashboard deleted mistakenly while trying to delete variable

**Comment by andnor** [comment]
+1. I accidentally deleted a dashboard when trying to delete a panel. Since the version history is available I think it's pretty common to assume that there's an undo for hard deletes.

**Comment by thavlik** [comment]
Piling on here for all the same reasons. +1

**Comment by pit3k** [comment]
+1

**Comment by dhiren051** [comment]
+1 accidentally deleted the dashboard while clicking on versions panel.

**Comment by csnook** [comment]
Since there are legitimate concerns about keeping full history around forever, even after a delete makes it look like it's gone, perhaps a good compromise would be an archive feature that unpublishes the dashboard and removes it from normal search results. That button could take the place of the delete button that people hit too easily, and actual deletion could be offered as an option after archiving.

**Comment by agopu** [comment]
Admittedly, I clicked YES on the confirmation modal but I thought I was deleting a new Variable was trying to add to an existing established dashboard. **Having the ability to restore a dashboard would be incredibly helpful**. I am going to look into implementing the dashboard backup idea mgresser mentioned above. 

**At least add a double confirmation or make the user type the name of the dashboard to delete (like github does when you try to delete a repo?)**

**Comment by DanCech** [comment]
Had to do a partial restore from backups today to recover dashboards accidentally nuked when a folder was deleted.

**Comment by jericvizmanos** [comment]
+1 Been encountering this more and more lately. This would be a great feature to have.

**Comment by Tomica-G** [comment]
+1 on this as well, it would make many lives easier.

**Comment by trallnag** [comment]
Just deleted a folder with a dashboard in it :/

Please add a warning or something like that if the folder still contains stuff

**Comment by mrsndmn** [comment]
There are tools for backup and restore dashboards in [grafana-tools/sdk](https://github.com/grafana-tools/sdk#examples-)

**Comment by webknows** [comment]
+1

**Comment by rotrials** [comment]
+1

**Comment by yaroze** [comment]
+1

**Comment by thomasbromkapsdata** [comment]
Keep them in history could be cool... lost a lot of dashboard by moving them and want to delete the empty folder...

**Comment by anavss** [comment]
Hi everyone 👋🏼 one of our product designers is investigating design improvements to dashboard folder management and navigation in Grafana. I spotted your feature request and wondered if any of you would be interested in speaking to her? 

You can [book 20-30min with her here](https://ethn.io/38442) and see some early design ideas 👀. If none of these time slots work for you, you can [send me an email](mailto:ana.vanschalkwyk@grafana.com) and I'll get in touch.

**Comment by ethirolle** [comment]
@anavss I am curious if there is still momentum on this feature request idea? I know several customers who would be happy to see this feature implemented... Thanks!

**Comment by MarcoJ-CID** [comment]
The topic was started right now nearly 6 years ago. At this time Grafana was in version 4.4.3 available and a beta of 4.5.0 was available as well. Now we got Grafana in version 10.0.3 and still missing the feature for backup/restore single dashboards. Would be really great when this topic will get now finally on the agenda of the dev's and getting implemented.

**Comment by shaharb-hs** [comment]
+1

**Comment by SpyridonSt** [comment]
I think this would be a great feature to include.
Perhaps a deleted folder can be created, so in case a dashboard, or folder is deleted my mistake it can go there.

Another idea could also work that I have previously read, which is you would need to type in the full name of the dashboard to delete it

**Comment by SpyridonSt** [comment]
Is it possible to request this somehow has a feature for a future update?
I mean to have some way of further protection from permanently deleting a dashboard
