### ISSUE TITLE
Documentation feedback: /docs/sources/setup-grafana/installation/_index.md

### ISSUE THREAD

**Issue by callmehyde** [grafana/grafana#92365]
We need to update the **Supported databases** section of this doc.

* https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases

Per @hairyhenderson in the Grafana Labs slack ([here](https://raintank-corp.slack.com/archives/C036J5B39/p1724371358068989)):

> MySQL 8.0 is the minimum supported version now (not 5.7)

To clarify, we should...

* Review if the existing supported databases list is still accurate
* Add new databases if they're supported (e.g. MariaDB)

**Comment by irenerl24** [comment]
there's a PR for this already: https://github.com/grafana/grafana/pull/92356
