### ISSUE TITLE
Grafana Loki Explore: Query always reports unexpected IDENTIFIER

### ISSUE THREAD

**Issue by imcom** [grafana/grafana#92371]
### What happened?

<img width="1791" alt="image" src="https://github.com/user-attachments/assets/6c1af606-a110-47d8-b204-227986398e05">

Failed to load log volume for this query
parse error at line 1, col 91: syntax error: unexpected IDENTIFIER

### What did you expect to happen?

The query is very simple, it should show me the log volume

### Did this work before?

grafana 9.4

### How do we reproduce it?

1. grafana community docker 11.4
2. configure Loki 2.7.5 docker
3. query Loki in grafana explorer

### Environment (with versions)?

Grafana: 11.4
OS: Mac OS
Browser: Brave & Safari both latest version

### Grafana platform?

Docker

### Datasource(s)?

Loki 2.7.5

**Comment by matyax** [comment]
@imcom Did you check if you have any invisible character anywhere in the query? I can reproduce it by replacing a space with a `cmd + space` character.

![Image](https://github.com/user-attachments/assets/083130d1-1f2e-41c4-bce4-c34b98b3559a)

**Comment by matyax** [comment]
Please reopen if this still occurs.

**Comment by matyax** [comment]
Hey @Alvaro948 ! This really shouldn't be an issue, and I'm starting to suspect that it's either the Loki version not supporting the "DROP" operation (although it should be in 2.9.3), or again an invisible character causing an issue.

Could you please try something again? Copy and paste this exact query and try to run it: `sum by (level, detected_level) (count_over_time({app="api"} |= `` | drop __error__[$__auto]))`

If you have the chance to update Loki to a most recent version, please do that. Keeping both Grafana and Loki up to date will allow you to use new features, so it's always a good idea. Keep us posted.

**Comment by matyax** [comment]
No worries! I'm glad the problem went away. Feel free to reach out again if you experience any issue.
