### ISSUE TITLE
New Select: Write test suite

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#92396]
Take inspiration from the current Select test cases. May be done as the same time as implementing the e2e selectors. https://github.com/grafana/grafana/issues/90645

Some cases:

- Select value by clicking #92485
  - That's directly visible #92485
  - That needs scrolling 
- Select value by searching and pressing enter #92485
- Select value by using keyboard only #92485
- Clear selected value #92485

To be implemented use cases:
- Create custom value
- Render select with custom value that is not available in the options

**Comment by KawtharAlakri** [comment]
Hi @tskarhed 
I would like to contribute to this. Can you just help me find where the existing select test cases are located?

**Comment by tskarhed** [comment]
> Hi @tskarhed I would like to contribute to this. Can you just help me find where the existing select test cases are located?

Of course. There are still some features missing for this component, such as adding a custom value. This component doesn't support multiple values either, so those test cases can be ignored.

- [Here is the Combobox component that needs to be tested](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Combobox/Combobox.tsx).
- [Here are the E2E test selectors used for the old Select](https://github.com/grafana/grafana/blob/fa95eb8c028968bd5d36c01a8fee39664c916ef4/packages/grafana-e2e-selectors/src/selectors/components.ts#L423)
- [Here are the test cases for the old select](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Select/SelectBase.test.tsx)

We also have some [guidelines related to testing](https://github.com/grafana/grafana/blob/main/contribute/style-guides/testing.md).

If you feel unsure about any test case, feel free to skip it. Any contribution is appreciated!

**Comment by KawtharAlakri** [comment]
Hi @tskarhed, I wrote the test cases but apparently it keeps failing, after some investigations I can see that the issue is with the virtualization not rendering the options (same issue found in [virtual repo](https://github.com/TanStack/virtual/issues/641)), after mocking that as suggested there it keeps failing with the following: 
![image](https://github.com/user-attachments/assets/42f6e49f-f5b8-4e7d-a3cd-7c5bf5ed8373)

My proposed testing code is [here ](https://github.com/KawtharAlakri/grafana/blob/new-select-testing/packages/grafana-ui/src/components/Combobox/Combobox.test.tsx)

**Comment by KawtharAlakri** [comment]
Thanks for replying. Here is a [draft PR ](https://github.com/grafana/grafana/pull/92485)

**Comment by KawtharAlakri** [comment]
From the requested test cases provided, [this PR](https://github.com/grafana/grafana/pull/92485) introduces: 

- [x] Component rendered without errors
- [x] Select value by searching and pressing enter
- [x] Select value by using keyboard only
- [x] Clear selected value
