### ISSUE TITLE
InfluxDB: percentile aggregation function

### ISSUE THREAD

**Issue by fsauer65** [grafana/grafana#924]
Please support the percentile aggregation function in the InfluxDB  query builder. I can see this is probably not straightforward since it has a second parameter unlike all the other currently supported functions.

**Comment by victorhooi** [comment]
I would also love to see `percentile` support as well! =).

@torkelo Is this related to #2802, or would it be possible to add this support prior to, or outside of that body of work?

**Comment by TheBox193** [comment]
Any updates on this? Is there a way to accomplish percentile aggregation for InfluxDB?
cc: @MelissaAcker

**Comment by tttMelody** [comment]
![image](https://user-images.githubusercontent.com/15643702/34301661-649796fc-e768-11e7-87f5-f8a47eb0b9f0.png)

![image](https://user-images.githubusercontent.com/15643702/34301697-9334208e-e768-11e7-8b7c-3629a413a3c6.png)

+1 it seems doesn't work.

@torkelo

**Comment by torkelo** [comment]
closing this, as this added a long time ago
