### ISSUE TITLE
New Select: Add empty state

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#92404]
Add empty state, such as "No options found".

- Use i18n
- Ignore if create custom value is available

**Comment by akshaywakhare** [comment]
hi, can you please assign this to me

**Comment by tskarhed** [comment]
@akshaywakhare Feel free to pick this up and open a PR that links to this issue so that we know that someone is working on it!

**Comment by akshaywakhare** [comment]
@tskarhed could you please provide more details such as
- where exactly do I need to add the empty state
- is ` "No options found"` , the exact name of empty state
- what do you mean by `Ignore if create custom value is available`

**Comment by tskarhed** [comment]
> * where exactly do I need to add the empty state
> * is ` "No options found"` , the exact name of empty state
> * what do you mean by `Ignore if create custom value is available`

This is the file. https://github.com/grafana/grafana/blob/3f6a64cc57b0a38b2c925f3d4f422c1ff42af5b4/packages/grafana-ui/src/components/Combobox/Combobox.tsx#L218

This is the custom value prop https://github.com/grafana/grafana/blob/3f6a64cc57b0a38b2c925f3d4f422c1ff42af5b4/packages/grafana-ui/src/components/Combobox/Combobox.tsx#L55

You can see the changes when running `yarn storybook`, [such as the one currently in main](https://developers.grafana.com/ui/canary/index.html?path=/story/forms-combobox--basic).
