### ISSUE TITLE
[Feat Req] Mixed data sources & have access to min interval & max data points options 

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#9240]
When editing a mixed panel i cant find the group by time config part:
![image](https://user-images.githubusercontent.com/12600004/30429836-3e3408cc-9959-11e7-97ed-913492b94ab7.png)

I was expecting to find this one at the bottom:
![image](https://user-images.githubusercontent.com/12600004/30429845-4a9555ee-9959-11e7-81c9-1b236d79cb96.png)

..for non-mixed it is there as usual

**Comment by torkelo** [comment]
yea, this has always been a limitation when using mixed data sources. Your the first to notice/open issue for it :)

**Comment by discoduck2x** [comment]
aha - do you know what happens right now then - i mean doest it reset to default (non set group by time value) ? @torkelo

**Comment by torkelo** [comment]
no the option is still there set to the value you last set it to, only not visible

**Comment by discoduck2x** [comment]
excellent so if i start with one datasource non-mixed and set a timeres template variable in the group by time then that will be applied to all datasources added after swapping to mixed? just i cant change that until/if feat gets implemented? @torkelo 
(im abit slow so i ask even though thats how i interpret ur prev answere)

**Comment by torkelo** [comment]
that is correct

**Comment by hugohaggmark** [comment]
I believe this is already been implemented, as I now can use Query Options for Mixed Datasources in Grafana v7.4.0-pre (db637a3630). Closing this issue.

Thank You to you for taking the time to create this issue!
