### ISSUE TITLE
[Feature request] Timebased Alerting / Acknowledgement of alerts

### ISSUE THREAD

**Issue by fl0wx** [grafana/grafana#9241]
Hey ,

i would love to see two more things on the alerting feature (like in nagios / icinga):

- Timesbased alerts (alert only active in a given interval, e.g. 8am to 7pm or sth like that)
- Acknowledge Alert with an comment (e.g. in case of an incident i dont want to get a bunch of alarms, i want to supress the alarm with an given comment)

Greetings Flowx

**Comment by torkelo** [comment]
thanks for the feedback! 

We already have  issues for these, https://github.com/grafana/grafana/issues/6592

**Comment by fl0wx** [comment]
@torkelo : Thanks for you fast feedback. Whats the status on this feature request? And i dont see the Request for alert acknowledgements?

Greetings Flowx
