### ISSUE TITLE
[Bug] Mixing panels with and without legend disrupt alignment 

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#9245]
Hi,

Grafana Version: HEAD

I've a row with several panels, some with legends and some without and it messes up the alignment of the panels :

![example](https://cdn.pbrd.co/images/GKlnb1W.png)

With firebug I tweaked the HTML a bit and reducing the heights of the 2 first panels div that have the class "histogram-chart" realigned everything :

```
<div class="histogram-chart" grafana-graph="" ng-dblclick="ctrl.zoomOut()" style="height: 174px;">
```

to
 
```
<div class="histogram-chart" grafana-graph="" ng-dblclick="ctrl.zoomOut()" style="height: 170px;">
```

I believe there must be a problem with the maths that calculates the height of panels' charts.

Regards.

**Comment by torkelo** [comment]
are you using firefox? do you get the same issue in chrome?

**Comment by sylr** [comment]
I've reproduced on Firefox, Chrome and Edge.

**Comment by torkelo** [comment]
unable to replicate on chrome v60 and OSX 

This dashboard
http://play.grafana.org/dashboard/db/mixing-panels-without-legend?orgId=1

**Comment by sylr** [comment]
Duplicate the last graph of the first row 2 more times and you will reproduce.

**Comment by torkelo** [comment]
not for me 
![image](https://user-images.githubusercontent.com/10999/30449886-a5c80d4e-9990-11e7-811b-40eba96e31a7.png)

**Comment by sylr** [comment]
![graph](https://cdn.pbrd.co/images/GKmUQUv.png)

**Comment by torkelo** [comment]
what version of the browser? tested on chrome v60 on windows now and cant replicate there either

**Comment by sylr** [comment]
- Firefox 55.0.3 on MacOS 10.12.6 (also tried in safe mode without addons).
- Chrome 60.0.3112.113 on MacOS 10.12.6

**Comment by sylr** [comment]
Are you sure you duplicated the "Traffic In/Out" panel and let the panels with legends first ?

**Comment by torkelo** [comment]
should be fixed in master https://www.youtube.com/watch?v=BC_YRNpqj5k&t=16s
