### ISSUE TITLE
[Bug] Cloudwatch undesired time aggregation

### ISSUE THREAD

**Issue by igorleao** [grafana/grafana#9246]
- What Grafana version are you using?
grafana 4.5.0

- What datasource are you using?
CloudWatch

- What OS are you running grafana on?
Centos 7

- What did you do?
I explored **RequestCount** metric over different ranges of time, always setting **Period** to _60s_

- What was the expected result?
Return **RequestCount** aggregated by _60s_

- What happened instead?
Aggregation occurs in intervals of `60` x `number of days selected via time picker`

## Range = **Today:**
![today](https://user-images.githubusercontent.com/780434/30442491-f9dd07c4-9952-11e7-969a-945bd04da303.png)
_Query Inspector_
```
Data Source
AWS CloudWatch
Query Inspector
 Expand All  Copy to Clipboard
request:Object
method:"POST"
url:"api/datasources/proxy/6"
data:Object
region:"us-east-1"
action:"GetMetricStatistics"
parameters:Object
namespace:"AWS/ELB"
metricName:"RequestCount"
dimensions:Array[1]
statistics:Array[1]
extendedStatistics:Array[0]
startTime:1505397051
endTime:1505407851
period:60
```
**period:60**
**value: 77.99**

## Range = **2  days ago:**
![2days](https://user-images.githubusercontent.com/780434/30442494-fd3a36ee-9952-11e7-9f3a-861e78c7a728.png)
_Query Inspector_
```
request:Object
method:"POST"
url:"api/datasources/proxy/6"
data:Object
region:"us-east-1"
action:"GetMetricStatistics"
parameters:Object
namespace:"AWS/ELB"
metricName:"RequestCount"
dimensions:Array[1]
statistics:Array[1]
extendedStatistics:Array[0]
startTime:1505234987
endTime:1505407787
period:120
```
**period:120**
**value: 156.5**

## Range = **7  days ago:**
![7days](https://user-images.githubusercontent.com/780434/30442496-fd555aaa-9952-11e7-9f8c-aef1813512c8.png)

_Query Inspector_
```
request:Object
method:"POST"
url:"api/datasources/proxy/6"
data:Object
region:"us-east-1"
action:"GetMetricStatistics"
parameters:Object
namespace:"AWS/ELB"
metricName:"RequestCount"
dimensions:Array[1]
statistics:Array[1]
extendedStatistics:Array[0]
startTime:1504802801
endTime:1505407601
period:420
``` 
**period:420**
**value: 554**

**Comment by torkelo** [comment]
Period should probably be named minimum interval , as 60s interval on two days would return 2880 points , more than pixels on the graph. Grafana will limit period so cloudwatch does not return more data than pixels other wise given a long time range grafana will hang due to too many datapoints

**Comment by igorleao** [comment]
How could I overcome this behavior?

Looking at the same metric for the same period on EC2, it returns as expected.
![screen shot 2017-09-14 at 4 08 15 pm](https://user-images.githubusercontent.com/780434/30454291-325ad7a6-9972-11e7-9a84-83d0d5cae2eb.png)

**Comment by mtanda** [comment]
At first, Grafana use GetMetricStatistics API.
http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html

The API has limitation.
> The maximum number of data points returned from a single call is 1,440. If you request more than 1,440 data points, CloudWatch returns an error.

And, Grafana call the API only once for specified time range.

For CloudWatch console, AWS provides, It use internal API, we can't use it.
![image](https://user-images.githubusercontent.com/224552/30465795-6249fa4e-9a14-11e7-9b9f-408c53a9843c.png)
![image](https://user-images.githubusercontent.com/224552/30465859-c64dcb06-9a14-11e7-8434-81be39264789.png)
![image](https://user-images.githubusercontent.com/224552/30465881-eba9c1ca-9a14-11e7-9560-32f30ca94c90.png)

For the time range = 1 week, period = 1 minute query, it returns about 10080 data points.
10080 = 7 days * 24 * hours * 60 minutes
It actually returns all data points for 1 minute Sum.

Grafana can do same thing by calling GetMetricStatistics multiple times, but the API cost increase to 7 times.

So, currently Grafana reduce the resolution, calculate period like (10080 * 60) / 1440 = 420, it is the reason why the period for 1 week query becomes 420.

**Comment by igorleao** [comment]
Oh, I see.
I really appreciate your explanation @mtanda.

Thanks a lot!

**Comment by mauve** [comment]
@mtanda we personally don't care about the API cost, any chance you can make this configurable?

**Comment by mtanda** [comment]
@mauve I guess it is not easy to support if you don't care about cost.
Too many API requests will cause throttling, some of API call will fail.

You should know the detail of throttling because you are a software engineer in AWS!

If you have a time, please try to change behavior by modifying the following lines.
https://github.com/grafana/grafana/blob/v4.6.3/pkg/tsdb/cloudwatch/cloudwatch.go#L129-L181

**Comment by mtanda** [comment]
I notice that the throttle limit is enough high, it accepts 400 transactions per second (TPS).
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

So, try to support high resolution mode.
