### ISSUE TITLE
New Select: Two selections in a row makes clears input

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#92473]
https://github.com/user-attachments/assets/17f662b7-96b7-4438-a07c-93d498b980b1

1. Go to the many options story, and change the amount of options
2.  Select one option
3. Start searching for another
4. Select it

Clearable is probably interfering with this somehow, in combination with a custom value not being support (options not being updated correctly?)

**Comment by JoaoSilvaGrafana** [comment]
@tskarhed Can you still reproduce this? I can't get it to happen...

**Comment by tskarhed** [comment]
The functuionality has changed drastically since then, so it was automatically fixed.
