### ISSUE TITLE
[Feature request] New alerting channel - Rocket.chat

### ISSUE THREAD

**Issue by fl0wx** [grafana/grafana#9251]
hey all,

i would love to see Rocketchat as a alerting channel.
Is this possible?

Greetings flow

**Comment by bergquist** [comment]
Hi

This will have to wait for back end plugins https://github.com/grafana/grafana/issues/6841 
I'm closing this issue since it wont be a part of core Grafana.

**Comment by kjetilmjos** [comment]
For information. Rocket.chat uses the same script to unpack messages as slack. This means slack can be used as an alert channel with the rocket chat webhook url.

**Comment by fl0wx** [comment]
@kjetilmjos: thanks a lot
