### ISSUE TITLE
[Feature request] support datasource name when making api query

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9252]
Please include this information:
- What Grafana version are you using?
4.4.3
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos

I can make a request to URL `/api/datasources/proxy/30/query`, and I think it would be better to support datasource name in the URL such as `/api/datasources/proxy/name/influxdb_abc/query`

**Comment by bergquist** [comment]
Why would it be better?

Using the ID is generally faster since its primary key in the database.

**Comment by wei-hai** [comment]
we have a cron job that keeps sending request to Grafana to monitor its availability, and when we delete and re-create the datasource, or migrate Grafana from one server to a new one the datasource ID will be different, for which we have to update the cron job script to hit the right datasource. This is not a common use case but I would appreciate if it could be supported.

**Comment by torkelo** [comment]
Will close this for now, if you do do delete and recreate datasource then maybe cron jobb can go directly to influxdb
