### ISSUE TITLE
Query Editor for MYSQL metric is missing

### ISSUE THREAD

**Issue by evanrich** [grafana/grafana#9253]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? **v4.5.0 (commit: 512535e)**
- What datasource are you using? **Mysql** 
- What browers have you used?  **Safari and Chrome**
- What OS are you running grafana on? **CentOS 7.3**
- What did you do? **Added a MySQL data source, then try to add a query to a graph**
- What was the expected result? **I should see a query window to enter the query**
- What happened instead? The query window is missing completely (see screenshot)

![image](https://user-images.githubusercontent.com/518320/30460141-da728dde-9969-11e7-90e0-23459c00ac11.png)

It shows the Row (A) then "Format AS"...no query window.  I searched google for half an hour trying to find out how to add a metric because of this, finally found a screen shot showing the missing window to enter a query.  FWIW, templating accepts mysql queries and they work, just the main metrics line is missing the query box.  Also, the Spacing between the top of "A" and the rest of the line is off.  I've tried restarting grafana, problem persists.  I also see this in console:

![image](https://user-images.githubusercontent.com/518320/30460217-41c19df4-996a-11e7-9ab5-86799564323a.png)

I have tried two different browsers and have also cleared my cache/tried in incognito mode.

**Comment by evanrich** [comment]
dupe of 9247

**Comment by leonyan1314** [comment]
Hi, i face some issue, how about your problem ? are you find solution ? thanks.

**Comment by torkelo** [comment]
upgrade to v4.5.1
