### ISSUE TITLE
[New Data Source]: <name-of-service>

### ISSUE THREAD

**Issue by guangming111** [grafana/grafana#92547]
### Background

Zabbix

### Use case

Zabbix

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by josiahg** [comment]
This appears to be a request for Zabbix, which is already available in the catalog - https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/

Feel free to comment and re-open if there is additional context here!

**Comment by sympatheticmoose** [comment]
@guangming111 if you were looking in `/connections` for Zabbix, note that it is an app plugin and as such currently needs to be installed via the plugin catalog at `/plugins`. We are looking to surface app plugins which include a datasource within `/connections` in a future update.
