### ISSUE TITLE
[New Data Source]: <SQL Lite>

### ISSUE THREAD

**Issue by rk630** [grafana/grafana#92557]
### Background

We would like to use SQLite as datasource.

### Use case

We would like to use SQLite as datasource.

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
@rk630 we have https://grafana.com/grafana/plugins/frser-sqlite-datasource/ as a community plugin which is available. Is this not suitable?
