### ISSUE TITLE
[Feature request] Preserve template variables in table cell link

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#9261]
- What Grafana version are you using?
4.5.1

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
RHEL 6.4

- What did you do?
Add a column style for a table panel and choose 'Render value as link'

- What was the expected result?
To see a checkbox to preserve template variables in the link URL

- What happened instead?
I had to re-type each template variable/value pair in the URL manually.

**Comment by benthorner** [comment]
Great new feature, by the way :-)

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630). We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
