### ISSUE TITLE
Grafana 4.5.x upgrade

### ISSUE THREAD

**Issue by Kenterfie** [grafana/grafana#9262]
I have upgraded my old 4.4.3 to 4.5 and i get on every dashboard the error "grafana.version undefined".
Does already exist a fix for it?

**Comment by torkelo** [comment]
Strange, no other reports like this, can you share your dashboard json (remove any sensitive info)

**Comment by Kenterfie** [comment]
![image](https://user-images.githubusercontent.com/527694/30520568-84d7506e-9bb0-11e7-838c-ff797ababa11.png)

I found the issue. The version was not set on Graphite Plugin, possible was not available in older version. I have now set and error is away.
