### ISSUE TITLE
Login page 'Failed to fetch' on offline environment

### ISSUE THREAD

**Issue by chlinwei** [grafana/grafana#92636]
### What happened?

   I just download the grafana and run it in a **offline** environment.
I enter the default admin/admin as the username and password.
Then try to set the new password. 
When I click the 'Submit' button. I will get the error message 'failed to fetch'.

grafana version: 10.4.8 and 11.2.0

![Image](https://github.com/user-attachments/assets/93722254-b6fa-47d0-97f4-b5bdcbb8c7d1)

the js error message:
        
    LoginCtrl.tsx:83 TypeError: Failed to fetch
    at zone.js:1518:36
    at ge.<computed> (zone.js:973:24)
    at p._subscribe (fetch.js:32:9)
    at p._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at u (errorContext.js:19:9)
    at p.subscribe (Observable.js:23:9)
    at m (mergeInternals.js:53:12)
    at mergeMap.js:14:59
    at b.<anonymous> (lift.js:10:28)

### What did you expect to happen?

If I run it in the internet environment. It won't happen.
This bug will lead to unable change the password.

### Did this work before?

In the internet enviroment. It can work.

### How do we reproduce it?

1.Just download the grafana  and  run it in the offline environment. and Try to change the password. You will get the error message.

### Environment (with versions)?

Grafana: 11.2.0 and 10.4.8
OS: windows 11
Browser: chrome ,firefox,edge.

### Grafana platform?

A downloaded binary

**Comment by joshhunt** [comment]
@chlinwei  I think we're going to need more information on this one. What's your Grafana server config file like? What URL are you accessing Grafana on? What's this `10.121.3.58` address? 

I can't reproduce this by unplugging the internet from my computer, so there must be some other environment or configuration that's getting in the way here.

**Comment by chlinwei** [comment]
@joshhunt 
Grafana was deployed on 10.121.3.58.   Today I do a testing for this.  I do it in another host without internet. 
It  didn't happen. Thus  I think  there is something network  or security policy  on 10.121.3.58. So It caused this problem.
I will close this issue.  Thank you.
