### ISSUE TITLE
adding kg (kilogramm) as unit  

### ISSUE THREAD

**Issue by NextBlaubeere** [grafana/grafana#9265]
Hello,

I've realized a monitoring for my heating infrastructure with influxdb and grafana. Thank you for that.

However i miss the unig kg (kilogramms) for messuring weight.

is it possible to add that? i think it shouldn't be a big deal.

regards

**Comment by NextBlaubeere** [comment]
nice thanks!

**Comment by m0nhawk** [comment]
Hope this can be soon merged and this can be closed than.
