### ISSUE TITLE
Plugins: Versions starting with a "v" can't be selected by a specific version

### ISSUE THREAD

**Issue by GFriedrich** [grafana/grafana#92669]
### What happened?

When trying to select a plugin version via the `GF_INSTALL_PLUGINS` env variable and the plugin version starts with a "v", the "v" gets stripped away before equality checks on the list of versions is executed. This in turn causes the version not be found.

### What did you expect to happen?

The version should be found even if the "number" starts with a "v" (or you need to force all plugin developers to not publish their plugins without the "v" prefix).

### Did this work before?

Likely no (but I've just experienced it)

### How do we reproduce it?

1. Try to run the docker image using the `GF_INSTALL_PLUGINS` environment variable
2. Use the following value `grafana-oncall-app v1.9.17`
3. See that the plugin can't be installed (also selecting `1.9.17` doesn't work either)

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.1.0 (but also 11.2.0 is affected from what I can tell)
OS: Linux
Browser: -

### Grafana platform?

Docker

**Comment by andresmgot** [comment]
This seems to be an issue with the on-call app release proces. It should not prepend the version with a `v`. [It's the only plugin that does it](https://grafana.com/api/plugins). Once they change that, we should add validation in the API so no other plugin attempts to do the same.

@grafana/grafana-oncall-backend can you take a look and modify the release process of the plugin? (this [github action](https://github.com/grafana/oncall/blob/dev/.github/workflows/on-release-published.yml))

**Comment by tolzhabayev** [comment]
Closing in favour of https://github.com/grafana/oncall/issues/5028
