### ISSUE TITLE
Panel/Text: CSS code not working anymore with version 11.2

### ISSUE THREAD

**Issue by github-ps1304** [grafana/grafana#92686]
### What happened?

after updating to version 11.2 the below code:

`<style type="text/css">
  body {
    background-image: url("https://drscdn.500px.org/photo/1102960336/q%3D80_m%3D600/v2?sig=95e672020141a54a754407128b4cea59205a8397575e22502f76043dd0cd46dc");
    height: 100%;
    width: 100%;
    background-repeat: no-repeat;
    background-size: cover;
    position: absolute;
    border-radius: 5;
  .dashboard-row--collapsed{
    background-color: rgba(0,0,0,0);
}
    /* You can also use more advanced CSS for background patterns etc. */
  }
</style>`

is not working anymore

### What did you expect to happen?

css code should display wallpaper from http link as background in Dashboard

### Did this work before?

yes working with 11.0.1

### How do we reproduce it?

1. add  visualization  (text) to a dashboard and use the code above pointing to a picture
2. Dashboard should use picture as background
3.

### Is the bug inside a dashboard panel?

yes the text panel

### Environment (with versions)?

Grafana: 11.2
OS: Debian 12
Browser: Safari

### Grafana platform?

A downloaded binary

**Comment by tskarhed** [comment]
In your config, have you set this:
```
[panels]
disable_sanitize_html = true
```
We have no official support for doing this, which means the class name selectors you are using, might have been updated. Also, double check that your CSS is valid. From the snippet you posted, it doesn't seem like it.

**Comment by Clarity-89** [comment]
Tested with `disable_sanitize_html = true` on both scenes and non-scenes dashboards in 11.3 and the CSS snippet works there, so the issues is most likely in the missing config option.
