### ISSUE TITLE
Set graph background color based on selection of time

### ISSUE THREAD

**Issue by adrianwFPS** [grafana/grafana#92689]
**Why is this needed**: to highlight the changes of time

[Add a description of the problem the feature is trying to solve.]

**What would you like to be added**: Easier to see when time changes

[Add a brief description of what the feature or enhancement should do.]

**Who is this feature for?** me

[Add information on what kind of user the feature is for.]

![Image](https://github.com/user-attachments/assets/2f5fbe42-f742-41ed-b385-21805c014569)

**Comment by leeoniya** [comment]
it exists: https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/#add-time-regions
