### ISSUE TITLE
Grafana 4.5.1 Post upgrade issues 

### ISSUE THREAD

**Issue by psabhar** [grafana/grafana#9269]
Hi
I am on RHEL 7 and upgrade grafana from 3.1 to 4.5.1 as I want to use Alert/Notification features.

I have issues while creating new dashboard after upgrade though some old dashboard works OK. I am also able to play with alert and notifications to slack. 

I dont see any error in /var/log/grafana/grafana/log but when I create new dashboard I see error on GUI. This is the error -> 
**_GraphiteProxy plugin failed
TypeError: a.jsonData is undefined_**

Can someone please help?

**Comment by rotanid** [comment]
a fix is described there:
https://github.com/grafana/grafana/issues/9258#issuecomment-329795046

**Comment by torkelo** [comment]
fixed #9258
