### ISSUE TITLE
Alerting: Panic after failing to create an Alertmanager for an org (duplicate metrics collector registration attempted)

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#92707]
### What happened?

Failing to create an Alertmanager for an org results in a panic due to the metrics collector being registered more than once.

The MultiOrg Alertmanager holds Alertmanagers for the different organizations in an `orgID -> Alertmanager` map. The factory function for Alertmanagers creates some metrics, which then uses to create the Alertmanager.

https://github.com/grafana/grafana/blob/e43ddd516deb0ed720e9d607df7a4c60205ad9b3/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L154-L159

The problem is that when `NewAlertmanager()` returns an error, metrics have already been registered. The next time we attempt to create an Alertmanager for the same org, we also attempt to register the same metrics again, causing a panic.

### What did you expect to happen?

No panics when failing to create an Alertmanager for an org.

### Did this work before?

-

### How do we reproduce it?

1. Return an error from the factory function (e.g. instead of [calling `NewAlertmanager()`](https://github.com/grafana/grafana/blob/e43ddd516deb0ed720e9d607df7a4c60205ad9b3/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L158), return `nil, fmt.Errorf("test")`)
2. Start Grafana
3. After failing to create the Alertmanager and trying again, Grafana will crash

### Grafana platform?

None

**Comment by iXingo** [comment]
Same here

**Comment by iXingo** [comment]
```
panic: duplicate metrics collector registration attempted

goroutine 311 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc00a61f0b0, {0xc007158980?, 0x0?, 0x0?})
	github.com/prometheus/client_golang@v1.19.1/prometheus/wrap.go:104 +0x12b
github.com/prometheus/alertmanager/api/metrics.NewAlerts({0x2743d00, 0xc00a61f0b0})
	github.com/prometheus/alertmanager@v0.27.0/api/metrics/metrics.go:39 +0x4c9
github.com/grafana/grafana/pkg/services/ngalert/metrics.NewAlertmanagerMetrics({0x2742880, 0xc004d17130})
	github.com/grafana/grafana/pkg/services/ngalert/metrics/alertmanager.go:21 +0xe5
github.com/grafana/grafana/pkg/services/ngalert/notifier.NewMultiOrgAlertmanager.func1({0x27649c0, 0xc00640a0a0}, 0x47)
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:156 +0x85
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc000e3c460, {0x27649c0, 0xc00640a0a0}, {0xc00c188800, 0x8c, 0x1?})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:304 +0x322
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc000e3c460, {0x27649c0, 0xc00640a0a0})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:260 +0xce
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).Run(0xc000e3c460, {0x27649c0, 0xc00640a0a0})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:243 +0xeb
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).Run.func1()
	github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:510 +0x26
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 7891
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```

**Comment by iXingo** [comment]
In which version will it be fixed

**Comment by iXingo** [comment]
I am on 11.2.0 can my instance keep restarting!!!

**Comment by iXingo** [comment]
#76809

**Comment by santihernandezc** [comment]
Hi @iXingo, thanks for pointing this out.
I just managed to reproduce this by returning an error from [`NewAlertmanager()`](https://github.com/grafana/grafana/blob/e23ba32722d40930404b7e32012eb5ec3d875f44/pkg/services/ngalert/notifier/alertmanager.go#L92), the panics seem to come from [here](https://github.com/grafana/prometheus-alertmanager/blob/b8b7c2c74eb6b1f9c42fbceae52b328cffcc0625/api/metrics/metrics.go#L39).
It looks like the [fix](https://github.com/grafana/grafana/pull/92725) worked partially, we're now getting panics somewhere else.
I've just reopened this issue, it should be closed once failing to create an Alertmanager and attempting to create a new one doesn't cause a panic.

**Comment by iXingo** [comment]
Thank you for your update and hard work.

**Comment by titolins** [comment]
Haven't tested it yet, but [this](https://github.com/grafana/prometheus-alertmanager/pull/92) should do the trick. Will test and ask for review later today.

Btw @iXingo, this should not be [urgent](https://github.com/grafana/grafana/issues/93732#issuecomment-2373808887). Ofc panics should be handled, but this will only occur in case the alertmanager creation is failing. You should check your logs/setup for any issues happening during the AM initialization

**Comment by santihernandezc** [comment]
Reopening, we need to include the fix in grafana/grafana and grafana/alerting.

**Comment by iXingo** [comment]
Thank you again, I believe that the error in our service is due to #76809. Do you have any suggestions for this. Is this due to the database？

**Comment by santihernandezc** [comment]
@iXingo Yes, the database could be responding too slowly and meeting the 30s deadline before Grafana creates Alertmanagers for each org. We're aware of the feature request but can't address it right now, PRs are welcome!
With the fixes we're merging we'll avoid panics even if we fail to create an Alertmanager for an org, so even if the deadline is met, Grafana will run.
