### ISSUE TITLE
[Feature request] add elasticsearch as a datasource when username and password are available for ES

### ISSUE THREAD

**Issue by datawrangl3r** [grafana/grafana#9270]
I set up x-pack, to provide an extra layer of security to Elasticsearch and now I am unable to use elasticsearch as a data source anymore… All I can see is a red alarming signal, showing that grafana failed to add the elasticsearch as a data source.
I provided the URL as, http://elastic:changeme@localhost:9200
![screenshot from 2017-09-16 12 24 59](https://user-images.githubusercontent.com/29449969/30510045-c6e2f73c-9ada-11e7-953b-7fad17852bef.png)

**Comment by torkelo** [comment]
try basic auth , and specify username and password there
