### ISSUE TITLE
[Bug] Override relative time -setting is ignored

### ISSUE THREAD

**Issue by pendix** [grafana/grafana#9271]
Platform: Grafana 4.5.1, Influxdb 1.3.5, Centos 7 (1708)

After upgrading from 4.4.3 to 4.5.0 (and then 4.5.1), the "Timerange / override relative time setting" is ignored in panels. Removing and redefining the value does nothing (no override note, no timerange change). (Timeshift does seem to work as expected, though).

**Update:** This happens only when the overall dashboard time range is absolute (non-relative). When time range is relative the override works as specified (and that is what the override parameter says, actually). The behaviour has just changed from 4.4.3, where the time range override worked even when dashboard timerange was absolute.

**Comment by cezarolavo** [comment]
Platform: Grafana 6.2
The "Timerange / override relative time setting" is ignored in panels, when the overall dashboard time range is absolute (non-relative). When time range is relative the override works as specified.

**Comment by marefr** [comment]
@cezarolavo sounds like the same issue as reported here #17743
