### ISSUE TITLE
how to find the exactly different affected metric in the graph

### ISSUE THREAD

**Issue by tangr** [grafana/grafana#9272]
I'm using grafana version 4.4.3. The panel data resource is prometheus, there are many metrics in my graph, how could I filter the exactly instance when my mouse stay on the point.
<img width="625" alt="wx20170916-212704 2x" src="https://user-images.githubusercontent.com/4860338/30512658-dfabb7d0-9b26-11e7-88ad-27a1431d1e31.png">
Just like the purple line. The floating division is not full, and the line which I found may not always in the window with "Bold".

**Comment by torkelo** [comment]
you can click on a series in the legend to only how that specific series. There is no way to filter the tooltip only by hovering.

**Comment by tangr** [comment]
@torkelo Thanks so much for your info, I knew that way. But for the reverse, that's much more difficult from the graph line to find the exactly series. The series won't highlight display.
