### ISSUE TITLE
[Bug] cant read data from legend popup

### ISSUE THREAD

**Issue by salehkhazaei** [grafana/grafana#9274]
- What Grafana version are you using?
 Grafana v4.4.1 (commit: 6a9f8ca) 

- What datasource are you using?
InfluxDb

- What OS are you running grafana on?
Ubuntu

When there are a lot of metrics, the popup wont cover them all and I cant see the value of specific metric. Please either sort it by value or bring the one that mouse points to (it already becomes bold on the popup) to the top.

**Comment by salehkhazaei** [comment]
![image](https://user-images.githubusercontent.com/9839920/30531288-8017b638-9c62-11e7-897c-fb82fdec012d.png)

**Comment by torkelo** [comment]
looks like you hit the max number of series that the popup can show. 

Also you can reduce the length of the series names by using the ALIAS BY field
