### ISSUE TITLE
[Bug] Regex: Templating -> Graph difference

### ISSUE THREAD

**Issue by erdna1982** [grafana/grafana#9275]
Hello.

I think i’ve found a bug in connection with templating regex and the values in the graph.

The problem:

I want to grep one especially network interface and this incoming and outgoing traffic from a zabbix template. this template receive all adapters from the windows machine.

:example:

network interface to monitor:
Hyper-V Virtual Ethernet Adapter #2

existing interfaces on windows:
Hyper-V Virtual Ethernet Adapter #2
Hyper-V Virtual Ethernet Adapter #2-WFP 802.3 MAC Layer LightWeight Filter-0000
Hyper-V Virtual Ethernet Adapter #2-WFP Native MAC Layer LightWeight Filter-0000
Hyper-V Virtual Ethernet Adapter #2-QoS Packet Scheduler-0000

templating:
name is netif
regex: /^(?:Incoming|Outgoing) network traffic on Hyper-V Virtual Ethernet Adapter #2$/
output in template:
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2

selection options in dropdown:
all
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2

seems good to me…but…

the graph shows me all the four existing interfaces, each with incoming and outgoing:
item: /$netif/
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2-WFP 802.3 MAC Layer LightWeight Filter-0000
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2-WFP Native MAC Layer LightWeight Filter-0000
Incoming network traffic on Hyper-V Virtual Ethernet Adapter #2-QoS Packet Scheduler-0000
or
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2-WFP 802.3 MAC Layer LightWeight Filter-0000
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2-WFP Native MAC Layer LightWeight Filter-0000
Outgoing network traffic on Hyper-V Virtual Ethernet Adapter #2-QoS Packet Scheduler-0000

I’ve spend a lot of time, many regex and also the regex in graph/item but without success…

Is it on me and my regex or maybe a bug?

cheers
Andre

**Comment by torkelo** [comment]
please open questions on the community site, https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50 

And include your data source and all the relevant queries and the response from your time series store. 

What does your metric query look like? Is the problem that it is matching to much? The regex in templating option is only applied to the response from the templating query. 

Is this your metric query? 

item: /$netif/

maybe try  `item: /^$netif$`

**Comment by erdna1982** [comment]
Hi and thank you for the reply!

If 'I try the item: /^$netif$/ the graph show me "no data points"

BUT...The following fix the problem:
item: /$netif$/

puhh... :D 

Thx
