### ISSUE TITLE
Explore Metrics with empty graphs due to $__rate_interval

### ISSUE THREAD

**Issue by fede843** [grafana/grafana#92762]
### What happened?

We have many metrics with empty graphs in the Explore Metrics section.
For some metrics the panel works just fine, but for others it is empty.
Tried to debug. Opened the query in explore and I found it is using` $__rate_interval`. 
In may case it was:

`sum(rate(jvm_cpu_time_seconds_total{}[$__rate_interval]))`

The issue is that we are scrapping every 30 seconds. That query just does not work. It starts working though if I open the time windows to 24h or similar. There I get what I was looking for.
In the regular explore I can modify the query or change the step interval, etc, but when it comes to the Explore Metrics section I cannot do any of that, leaving lots of metrics unusable for periods shorter that 24h or so.

### What did you expect to happen?

I expect to get the values plotted in the graphics.

### Did this work before?

Never was working.

### How do we reproduce it?

In my case some JVM metrics are not coming up. See picture.

![Image](https://github.com/user-attachments/assets/cf79a1b6-42fa-43e7-a025-35608f17d1af)

Opening the windows to 24h works fine

![Image](https://github.com/user-attachments/assets/47dbf4eb-138e-4a50-b0f6-c8e1498be9c5)

### Environment (with versions)?

Grafana: 11.2.0
Under docker 23.0.5, on Debian 11

### Grafana platform?

Docker

**Comment by Krulknul** [comment]
I am having the same issue after switching to Alloy from grafana-agent static. Exact same issue where I can only see data when on 24h, for example. It will also work if I change the query to using `__range` over using `__rate_interval`

**Comment by iaco86** [comment]
I think manually increasing the `min step` option to be 4x the scrape interval (or lowering the scrape interval to be 1/4 of the minimum step, which I think is 1m) works around the problem.

But this seems to be a bug introduced recently, I'm pretty sure this was working as described in [here](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) before.

**Comment by bboreham** [comment]
There's a setting in the Datasource for scrape interval; make sure you have it set to match your data.

![Image](https://github.com/user-attachments/assets/a8bbcf0c-0f7b-4a91-a94b-3a2761d0fb29)

**Comment by itsmylife** [comment]
As @bboreham pointed the scrape interval value must be configured in the datasource settings. 
Please refer [this post](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) about how we calculate the `$__rate_interval` value.

**Comment by jannst** [comment]
> There's a setting in the Datasource for scrape interval; make sure you have it set to match your data.
> 
> ![Image](https://github.com/user-attachments/assets/a8bbcf0c-0f7b-4a91-a94b-3a2761d0fb29)

In case you want to create your datasource using YAML:

`
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 60s
`

**Comment by fede843** [comment]
that's great. thanks a lot!
