### ISSUE TITLE
[Feature Request] top/bottom y-axis for different serieses

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9277]
With the present implementation of graphs, it is possible to use either a y-axis on the left or right with a data series. This allows different scales to be present, for example packets per second on the left and megabits per second on the right. Unfortunately in such situations what happens is that both graphs have the same shape, meaning that one almost completely makes the other invisible.

<img width="1405" alt="screen shot 2017-09-18 at 6 57 06 pm" src="https://user-images.githubusercontent.com/24280758/30534828-37dac20c-9ca3-11e7-9fd3-d3df5c1d0108.png">

Instead of this, what I'd like to be able to do is have (say) packets per second "above the line" and megabits per second "below the line".

At the moment I can do this by adding "math (*-1)" to my influxdb expression. This "kind of" works - so long as the units are the same. e.g. plotting "interface_rx,if_packets" as >0 and "interface_tx,if_packets" as < 0. Requires the brain to think a little ;)

<img width="1419" alt="screen shot 2017-09-18 at 6 49 35 pm" src="https://user-images.githubusercontent.com/24280758/30534650-7c4d1daa-9ca2-11e7-953c-1d978e2441f1.png">

Where this falls apart is if I want to do "interface_rx,if_octets" as > 0 and "interface_rx,if_packets" as < 0 because the scale for each is quite different.

<img width="1406" alt="screen shot 2017-09-18 at 6 53 11 pm" src="https://user-images.githubusercontent.com/24280758/30534694-a8764a82-9ca2-11e7-97df-cfc81d4f0750.png">

Using y-axis 1 & 2 also fails because grafana will plot the series that is negative from the top of the graph and the series that is positive from the bottom.

<img width="1408" alt="screen shot 2017-09-18 at 6 51 52 pm" src="https://user-images.githubusercontent.com/24280758/30534663-8b3816b2-9ca2-11e7-893c-b56ccd0b9ce6.png">

**Comment by torkelo** [comment]
mixing different units / scale above below zero sounds very bad to me, and not something we will implement as it will be just a mess. having left/right y axis and multiple ways to use negative y to show different metrics (there is also a series override called transform negative that is very similar to using math * -2 in query).

**Comment by yellowpattern** [comment]
"transform negative-y" presents the same problem as "math(*-1)" - the second half of the y-graph is negative when it should be positive.

**Comment by yellowpattern** [comment]
The workaround is to "normalise" the bps to fit into a scale similar to pps. So instead of "pps*1" and "bps*-1", "pps*1" and "bps/-1000".

<img width="1419" alt="screen shot 2017-09-18 at 7 49 14 pm" src="https://user-images.githubusercontent.com/24280758/30536758-8d1fc2e2-9caa-11e7-90dc-b1a5ad1bcda6.png">

This is what it looks like with the different axis approach:

<img width="1424" alt="screen shot 2017-09-18 at 7 52 04 pm" src="https://user-images.githubusercontent.com/24280758/30536853-e7c2c744-9caa-11e7-906a-5c84ce60e646.png">
