### ISSUE TITLE
Documentation feedback: /docs/sources/alerting/alerting-rules/create-grafana-managed-rule.md

### ISSUE THREAD

**Issue by in-op** [grafana/grafana#92784]
Your description for configuring No Data and Error states to `Alerting` states:

> Alerting | Sets alert instance state to Alerting. It transitions from Pending to Alerting after the pending period has finished.

However `Alerting` and `Pending` are two different instance states, so the first sentence isn't really true at first. It's kindof contradictory. It should probably be reworded to something like:

> Sets alert instance state to Pending, and will transition to Alerting after the pending period has finished if it doesn't resolve

**Comment by brendamuir** [comment]
Hi there - it is explained in this doc in step 3 : https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#set-alert-evaluation-behavior

Can you help me by letting me know which topic you are seeing the text you mention above in? Thanks!
