### ISSUE TITLE
How to remove the line which plotted by interpolation

### ISSUE THREAD

**Issue by bjjqqkk** [grafana/grafana#9278]
- What Grafana version are you using?       : Grafana v4.2.0 
- What datasource are you using?              : KairosDB
- What OS are you running grafana on?     : ubuntu
- What did you do?                                     : Plot a Kairosdb datasource  
![default](https://user-images.githubusercontent.com/32057729/30534839-7e856bfa-9c92-11e7-9218-3fd799246c0e.jpg)
![2](https://user-images.githubusercontent.com/32057729/30534890-b6c73642-9c92-11e7-80bb-27433233f441.jpg)

 I expected the line from 8/19 to 9/12 should be empty,  but it plotted a straight line.
How can I hide the line? (8/19~9/12)

**Comment by torkelo** [comment]
Not sure KairosDB has a way to return nulls for "missing data"

**Comment by torkelo** [comment]
https://github.com/grafana/kairosdb-datasource
