### ISSUE TITLE
requesting to be signed Performance Co-Pilot plugin

### ISSUE THREAD

**Issue by diude** [grafana/grafana#92793]
we are getting below error - 

Errors loading rules
Failed to load the data source configuration for [Prometheus-vmetrics](https://grafana-octo-dt-octo-dev.apps.ocp-dc8-03.ikeadt.com/datasources/edit/ebpBoo3Sz): remoteAddr: "100.126.3.1:36216, X-Forwarded-For: 10.232.47.4, 100.126.4.1, ::1, ::1"; requestURI: /api/v1/status/buildinfo; missing route for "/api/v1/status/buildinfo" ; Bad Request 

As we checked, above error is due to unsigned of performancecopilot,how can we get this plugin signed?

![Image](https://github.com/user-attachments/assets/6f554bc2-2d63-4bd3-9b8e-f068902e441d)

**Comment by marefr** [comment]
You probably have to wait for it to be published on https://grafana.com/grafana/plugins/performancecopilot-pcp-app/

Suggest reaching out to the authors for further help https://github.com/performancecopilot/grafana-pcp
