### ISSUE TITLE
[Bug] Internal grafana metrics errors

### ISSUE THREAD

**Issue by korservick** [grafana/grafana#9279]
- What Grafana version are you using? 4.5.1
- What datasource are you using? Graphite (go-carbon)
- What OS are you running grafana on? Centos 7.3
- What did you do? view internal metrics for host carbon-view_linux_local
- What was the expected result? `carbon-view` as hostname 
- What happened instead? `carbon_view` as hostname, metrics are renamed with `_`, errors in log go-carbon (parser)
Sample:
4.5.0: carbon-view_linux_local/api/login/oauth/count.wsp
4.5.1: carbon_view_linux_local/api_login_oauth_total/count.wsp ("_" in place "-")

Plus some NaN in metrics (here some of 20+) that log as errors in go-carbon:
...http_request_duration_milleseconds.handler._login.method.get.quantile.0_99.statuscode.302 NaN
...http_request_duration_milleseconds.handler._datasources_proxy_:id_.method.post.quantile.0_5.statuscode.400 NaN
...api_dataproxy_request_all_milleseconds.quantile.0_99 NaN

**Comment by torkelo** [comment]
Is it like a warning in go-carbon to detect renamed metrics? We accidentally included an internal  metrics rewrite in 4.5.1 , this rewrite is a breaking change as all metric paths change

**Comment by torkelo** [comment]
the NaN stuff looks like a bug though

**Comment by korservick** [comment]
It is like:
[2017-09-18T11:03:02.348+0300] INFO [parser] parse failed {"error": "bad message: \"carbon_view_linux_local.http_request_duration_milleseconds.handler._login.method.get.quantile.0_99.statuscode.302 NaN 1505721782\\n\"", "protocol": "tcp", "peer": "10.76.4.179:55018"}

**Comment by torkelo** [comment]
ok, I guess the error is due to the NaN and not the underscore (changed name)

**Comment by korservick** [comment]
Problem with parsing `-` symbol to `_` in hostname likely solves after edit https://github.com/grafana/grafana/blob/master/pkg/metrics/graphitebridge/graphite.go#L360
by adding || c == '-' ||

**Comment by korservick** [comment]
Other errors in internal metrics I'll take a closer look later

**Comment by bergquist** [comment]
That commit will ignore NaN metrics and allow '-'.

**Comment by korservick** [comment]
What happens if adding `|| c == '.' ||` in https://github.com/grafana/grafana/blob/0a8a6fd872912e7f4bdee2e3468bd901d6298251/pkg/metrics/graphitebridge/graphite.go#L365 ?
May be it fix /api_login_oauth_total/count.wsp to /api/login/oauth/total/count.wsp and so on in graphite backend... or in new model of internal metrics the_long_name_of_metric will prefer?

**Comment by bergquist** [comment]
@korservick thats a bug. Fixed by my last commit. 

Sorry for all the problems :/ this was not suppose to be released in 4.5.1

Leaving this issue open if someone finds more issues with internal metrics

**Comment by korservick** [comment]
@bergquist no problem :)

I have several ideas for naming metrics, but have not yet managed to decorate them nicely.
