### ISSUE TITLE
[Bug] No graph generated with negative-y transform

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9280]
Grafana Version: 4.4.2
Data source: Influxdb 1.3.2

When using "negative y" transform to alter how a series is presented, a series can completely disappear:

<img width="1416" alt="screen shot 2017-09-18 at 7 30 14 pm" src="https://user-images.githubusercontent.com/24280758/30536119-f66df55a-9ca7-11e7-8e45-29e490f31705.png">

<img width="1417" alt="screen shot 2017-09-18 at 7 31 55 pm" src="https://user-images.githubusercontent.com/24280758/30536155-14186c7a-9ca8-11e7-90ce-cf3f6fe8ea63.png">

If I take away the negative transform, the graph returns:

<img width="1419" alt="screen shot 2017-09-18 at 7 36 25 pm" src="https://user-images.githubusercontent.com/24280758/30536328-ba4aa2ac-9ca8-11e7-8756-394f4aab933f.png">

**Comment by yellowpattern** [comment]
Forgot this screenshot

<img width="1415" alt="screen shot 2017-09-18 at 7 35 11 pm" src="https://user-images.githubusercontent.com/24280758/30536406-072eeb50-9ca9-11e7-802e-e90d15baa6c9.png">

**Comment by torkelo** [comment]
do you have any min/max settings defined in Y-Axis options ?

**Comment by yellowpattern** [comment]
No. I tried that (-100/1000) to see if would help but it did not.

**Comment by torkelo** [comment]
strange, unable to replicate it here, the graph shows fine

**Comment by yellowpattern** [comment]
Attaching the a sample of the panel when "broken"
[BUG9280-1505730103431.txt](https://github.com/grafana/grafana/files/1310367/BUG9280-1505730103431.txt)

**Comment by torkelo** [comment]
Ah, you have a logarithmic scale on your axis, this does not support negative values 
https://github.com/grafana/grafana/issues/7627
