### ISSUE TITLE
Issue with Parsing Custom Group Attribute from AWS Cognito in Grafana

### ISSUE THREAD

**Issue by TheSwarnim** [grafana/grafana#92801]
**Why is this needed**:
Hello everyone,
I am currently working on integrating Grafana with AWS SSO through a custom SAML 2.0 application (IAM Identity Center Application). We have set up federated identity provider sign-in with AWS SSO, and the configuration involves using a custom attribute passed to AWS Cognito.
**Steps to Reproduce:**
1. Set up a federated identity provider sign-in with AWS SSO by creating a custom SAML 2.0 application.
2. Configure a custom attribute in the Cognito user pool to receive the "groups" field from the SAML application.
The expected behavior is that the groups should be received as a list/array. However, the actual behavior observed is that the groups are passed to Cognito as a stringified list. For example, the JSON returned by Cognito includes:

```json
{
    "custom:group": '["admin", "editor", "viewer"]'
}
```

**Expected Behavior:**
Grafana should correctly parse the custom:group attribute as a list/array and map the roles accordingly.

**Actual Behavior:**
Grafana seems to treat the custom:group attribute as a plain string and does not correctly parse it as a JSON array. This leads to issues in role mapping, where users are not assigned the correct roles.

**Questions:**
1. Has anyone faced similar issues with parsing JSON strings from AWS Cognito in Grafana?
2. Is there an existing solution or workaround for this issue?
3. If no such solution exists, I am willing to work on resolving this issue. Can anyone guide me on the best way to approach this or point me to relevant sections of the codebase?

**Comment by mgyongyosi** [comment]
Hi @TheSwarnim,

> Grafana seems to treat the custom:group attribute as a plain string and does not correctly parse it as a JSON array. This leads to issues in role mapping, where users are not assigned the correct roles.

Because it looks like a JSON string, however it should use double quotes not single ones. This is an AWS Cognito mapping issue, not a Grafana one.
