### ISSUE TITLE
Grafana/Oncall: cannot unmarshal object into []plugin.OnCallPermission

### ISSUE THREAD

**Issue by senpro-ingwersenk** [grafana/grafana#92815]
### What happened?

I updated to Grafana 11.2.0 and OnCall 1.9.20 but now OnCall no longer responds to Grafana at all.

When registering the Plugin I can see this message in the browser console:

```
error setting up request headers: failed to parse JSON response: json: cannot unmarshal object into Go value of type []plugin.OnCallPermission body={"message":"Not found"}
```

However, I can not tell where this error actually originates from. The URI is `/api/plugins/grafana-oncall-app/resources/plugin/status`

Since I can not exactly tell the origin, I decided to post it here. Apologies if this wasn't correct.

### What did you expect to happen?

I expected to have a working OnCall.

### Did this work before?

Yes. I previously had Grafana 11.1.3 and OnCall 1.8.8 installed but an issue related to re-appearing alerts. That is what prompted me to run the upgrade.

### How do we reproduce it?

I wish I knew. All I did was upgrade and run the migrations. I also updated the point-releases of MySQL and RabbitMQ.

* MySQL: `mysql:8.0.32` -> `mysql:8.0.39`
* RabbitMQ: `rabbitmq:3.12.0-management` -> `rabbitmq:3.12.14-management`

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.2.0; OnCall 1.9.20
OS: Linux, NixOS 24, amd64
* We use a hand-crafted deployment configuration - it stems from before we knew how Helm charts worked and a proper migration to those is currently outstanding.
Browser: Brave

### Grafana platform?

Kubernetes

**Comment by senpro-ingwersenk** [comment]
...that's weird.

https://github.com/grafana/grafana/actions/runs/10668463324

That said, I found the issue. sneaky as heck, but it was a feature toggle one of my collegues had set way, way back: https://github.com/grafana/oncall/issues/4850#issuecomment-2299294185

I went and checked both Grafana's and OnCall's changelogs and found not a single notice about this. Would've been helpful :)

Thank you for your hard work!

**Comment by alireza1371** [comment]
I have the same issue, any update?

**Comment by FecoDoo** [comment]
This is still happening with `Grafana v11.3.1 (9225f4a1cb)` and OnCall plugin `1.13.6`.

For reference, here's part of my ECS setup:

```
oncall = {
    "BASE_URL"                     = "https://${aws_route53_record.oncall.fqdn}:8080"
    "SECRET_KEY"                   = local.secrets.oncall.SECRET_KEY
    "MIRAGE_SECRET_KEY"            = local.secrets.oncall.MIRAGE_SECRET_KEY
    "MIRAGE_CIPHER_IV"             = local.secrets.oncall.MIRAGE_CIPHER_IV
    "DJANGO_SETTINGS_MODULE"       = "settings.prod_without_db"
    "AMIXR_DJANGO_ADMIN_PATH"      = "admin"
    "OSS"                          = "True"
    "DETACHED_INTEGRATIONS_SERVER" = "False"
    "BROKER_TYPE"                  = "redis"

    "GRAFANA_API_URL"                        = "https://${aws_route53_record.oncall.fqdn}:443"
    "GRAFANA_CLOUD_NOTIFICATIONS_ENABLED"    = "False"
    "GRAFANA_CLOUD_ONCALL_HEARTBEAT_ENABLED" = "False"
    "GRAFANA_COM_API_URL"                    = "https://grafana.com/api/"
    # "GRAFANA_COM_USER_AGENT" = "Grafana OnCall"
    # "GCOM_API_TOKEN" = os.environ.get("GCOM_API_TOKEN", None)
    # "GRAFANA_COM_ADMIN_API_TOKEN" = os.environ.get("GRAFANA_COM_ADMIN_API_TOKEN", None)
    # GRAFANA_API_KEY_NAME = "Grafana OnCall"

    "SELF_HOSTED_STACK_ID" : 5
    "SELF_HOSTED_STACK_SLUG" : "self_hosted_stack"
    "SELF_HOSTED_ORG_SLUG" : "self_hosted_org"
    "SELF_HOSTED_ORG_TITLE" : "Metaplay"
    "SELF_HOSTED_REGION_SLUG" : "self_hosted_region"
    "SELF_HOSTED_CLUSTER_SLUG" : "self_hosted_cluster"


    "FEATURE_TELEGRAM_INTEGRATION_ENABLED" = "False"
    "FEATURE_EMAIL_INTEGRATION_ENABLED"    = "False"
    "FEATURE_PROMETHEUS_EXPORTER_ENABLED"  = "False"
    "FEATURE_GRAFANA_ALERTING_V2_ENABLED"  = "False"
    "FEATURE_LABELS_ENABLED_FOR_ALL"       = "False"
    "FEATURE_ALERT_GROUP_SEARCH_ENABLED"   = "False"
    "FEATURE_INBOUND_EMAIL_ENABLED"        = "True"
    "FEATURE_SLACK_INTEGRATION_ENABLED"    = "True"

  }

  grafana = {
    "GF_DATABASE_TYPE"                          = "mysql"
    "GF_DATABASE_HOST"                          = module.rds.db_instance_address
    "GF_DATABASE_PORT"                          = module.rds.db_instance_port
    "GF_DATABASE_NAME"                          = module.rds.db_instance_name
    "GF_DATABASE_USER"                          = local.secrets.database.ADMIN_USER
    "GF_DATABASE_PASSWORD"                      = local.secrets.database.ADMIN_PASSWORD
    "GF_FEATURE_TOGGLES_ENABLE"                 = "externalServiceAccounts" # https://github.com/grafana/oncall/issues/4829#issuecomment-2334880368
    "GF_FEATURE_TOGGLES_ACCESSCONTROLONCALL"    = "false"
    "GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED"  = "true"
    "GF_SECURITY_ADMIN_PASSWORD"                = local.secrets.grafana.ADMIN_PASSWORD
    "GF_SECURITY_ADMIN_USER"                    = local.secrets.grafana.ADMIN_USER
    "GF_SERVER_ROOT_URL"                        = "https://${aws_route53_record.oncall.fqdn}"
    "GF_SERVER_DOMAIN"                          = aws_route53_record.oncall.fqdn
    "GF_SERVER_HTTP_PORT"                       = 3000
    "GF_SERVE_FROM_SUB_PATH"                    = "false"
    "GF_INSTALL_PLUGINS"                        = "grafana-oncall-app"
    "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS" = "grafana-oncall-app"
  }

```

**Comment by matteoridolfiQred** [comment]
It does seem feature toggles are not supported as env variables. Here's the PR that address the issue:
https://github.com/grafana/grafana/pull/90178

Which means setting `GF_FEATURE_TOGGLES_ACCESSCONTROLONCALL` won't work. It has to be set inside grafana.ini or helm chart value.
