### ISSUE TITLE
[Feature request] Add panel option that allows legend to be shown when viewing

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#9281]
Hi,

It would be great to have a panel option that would make legend to be automatically toggled on when viewing the panel.

Regards.

**Comment by torkelo** [comment]
you can toggle legend from panel menu if you want to temporarily enable it

**Comment by sylr** [comment]
Yes I know but this is cumbersome when you are switching from panel to panel.

**Comment by sylr** [comment]
Frankly I don't know anyone around me who uses the keyboard shortcuts.

It would be greatly appreciated to have an option or always show the legend when viewing.

**Comment by torkelo** [comment]
no shortcuts? that's strange :) 

Can't have options for everything otherwise the UI will be a sea of toggles :)
