### ISSUE TITLE
[Feature Request] Display the cursor on multiple graphs at once

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9282]
Grafana Version: 4.4.2

With some displays it would be advantageous to be able to show the cursor on two graphs at the same time so that it is easier to correlate events and measurements on graph A with those on graph B. Of course the cursor needs to be time synchronised on both but that should be easy (ha!) as the time range covers all visible graphs on a page.

e.g. when looking at network traffic or disk activity, I typically want to be able to easily relate the "pps" to "bps" or "IOPS" to "mb/s". Needing to move between different graphs and noting values of A at time T and then finding time  on graph B makes life a bit tedious.

I can see that this would be a PITA to implement to show individual point values but there are already problems for that - e.g. on a switch with 48 ports, putting all 48 on one graph will generate a list of values longer than the screen.

But is it possible? Desirable?

**Comment by torkelo** [comment]
in dashboard settings you have a dashboard wide graph tooltip option (can be cycled using keyboard shortcut as well). 

![image](https://user-images.githubusercontent.com/10999/30538627-2e45adc6-9c6f-11e7-9527-8373d84a46be.png)


shared crosshair will show a line over all graphs when you hover over any graph, shared tooltip will show tooltip as well on all graphs

**Comment by yellowpattern** [comment]
Shared cross hair is perfect. Thanks.

**Comment by torkelo** [comment]
Its under dashboard setting (there is also a keyboard shortcut)

**Comment by rixed** [comment]
Ah yes, was looking for "crosshair" not tooltip. Thank you!

**Comment by sagufta1994** [comment]
Thanks @torkela. This information really helped. 

I have one more request, with the "crosshair" enabled panels which are of table format are not getting a line or changing the when I hover over any graph.

Is there a way we can see tables data also changing when we hover on any graphs.

Thank you in advance.

**Comment by ElijahLynn** [comment]
> Its under dashboard setting (there is also a keyboard shortcut)

Great thread!!! 

`ctrl + o` or `cmd + o`
