### ISSUE TITLE
[Bug] Elasticsearch Breaking Change in 4.5.1

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#9283]
Please include this information:
- What Grafana version are you using?
4.5.1

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
RHEL6.4

- What did you do?
Upgraded to Grafana 4.5.1 from 4.4.3

- What was the expected result?
Dashboards using the bt-grafana-alarm-box panel should continue to work

- What happened instead?
The plugin was unable to render the data as the response format has changed

**Comment by torkelo** [comment]
There has been no change. What does your query look like and what does Elasticsearch return?

**Comment by benthorner** [comment]
Something has definitely changed, as downgrading to 4.4.3, without changing anything else, fixes the issue. The following screenshots show the query and the different responses (before then after).

<img width="1417" alt="screen shot 2017-09-18 at 11 53 03" src="https://user-images.githubusercontent.com/9029009/30539025-7e961ccc-9c68-11e7-96d9-cdf85410171c.png">

<img width="1222" alt="screen shot 2017-09-18 at 11 53 50" src="https://user-images.githubusercontent.com/9029009/30539030-83ba098e-9c68-11e7-92ee-aab230c5645d.png">

<img width="569" alt="screen shot 2017-09-18 at 11 56 17" src="https://user-images.githubusercontent.com/9029009/30539032-85b9ce36-9c68-11e7-97e8-f79c0a3c9eee.png">

**Comment by benthorner** [comment]
Although this plugin allows you to change the way the data is interpreted, using the mathjs library, this doesn't work for the new result format as the object isn't a plain javascript object.

**Comment by torkelo** [comment]
ah, yes we fimproved Elasticsearch response parsing so it returns metric queries in table format. This is a minor breaking change that did not affect the internal panel plugins. Sorry if this caused issue for the bt-grafana-alarm-box panel panel, it needs to be updated to support table response formats.
