### ISSUE TITLE
[Bug] Close 'Unsaved changes' prompt unresponsive

### ISSUE THREAD

**Issue by Conorbro** [grafana/grafana#9284]
**- What Grafana version are you using?**

Grafana 4.5.1

**- What datasource are you using?**

Prometheus

**- What OS are you running grafana on?**

Ubuntu 16.04.2 VM

**- What did you do?**

Made changes to dashboard 
-> Try to navigate away from dashboard without saving 
-> Prompt displays but cannot be closed with 'x' icon in the top right hand corner of the prompt.

Example:
 
![grafana-bug](https://user-images.githubusercontent.com/5826063/30538691-114d40e2-9c67-11e7-95c5-2c48e23c3c10.gif)

**- What was the expected result?**

That the prompt dialog would close.

**- What happened instead?**

Nothing.

**Comment by torkelo** [comment]
thanks for reporting this!
