### ISSUE TITLE
[Feat Req] Improve shared tooltip placement when having many series on top of each other

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9288]
After enabling "shared tooltip" in the dashboard preferences, I moved the cursor over the graphs...

I could see one value list clearly and what appears to be the second one underneath - look at the bottom end of the value list, what's going on there?

<img width="1420" alt="screen shot 2017-09-18 at 10 18 27 pm" src="https://user-images.githubusercontent.com/24280758/30541720-e83a10e6-9cbf-11e7-9fe8-873eb3dc9012.png">

Related to https://github.com/grafana/grafana/issues/9287

**Comment by torkelo** [comment]
could be improved a bit but if you have enough series and graphs on top this is always going to happen.

**Comment by yellowpattern** [comment]
Interesting behaviour! There seems to be a bug in drawing the top list that when it exceeds the bottom of the graph, the second list is draw to start under neath that rather than on its own graph.

<img width="1425" alt="screen shot 2017-09-18 at 11 29 20 pm" src="https://user-images.githubusercontent.com/24280758/30544276-48c0665a-9cc9-11e7-8a99-f7186d62f61f.png">

<img width="1429" alt="screen shot 2017-09-18 at 11 29 35 pm" src="https://user-images.githubusercontent.com/24280758/30544277-490f7e66-9cc9-11e7-91fb-e3893a4399b0.png">

**Comment by yellowpattern** [comment]
<img width="518" alt="screen shot 2017-09-18 at 11 37 56 pm" src="https://user-images.githubusercontent.com/24280758/30544636-80eb41ca-9cca-11e7-99e5-107fc3ab1ea0.png">

**Comment by yellowpattern** [comment]
Very small change in the position of the top list and then *wham* all over.

<img width="298" alt="screen shot 2017-09-18 at 11 39 28 pm" src="https://user-images.githubusercontent.com/24280758/30544700-bb7e2852-9cca-11e7-89bb-01ad71e356a9.png">

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
