### ISSUE TITLE
Feature Request: In templating regex add ability to inverse match results

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#929]
In templating the regex feature should have an option to inverse the results.  So if you put a regex of /tmp/ it would normally show all items that have tmp in them, but after the fix if the 'inverse' checkbox was checked you would get all results that do not have tmp in them.  This is analogous to the '-v' flag of grep.

I tried to use regex negative lookaheads (ex: http://stackoverflow.com/questions/6259443/how-to-match-a-line-not-containing-a-word) but it wasn't parsed correctly and they are quite complex.

**Comment by torkelo** [comment]
closing for lack of interest
