### ISSUE TITLE
[Bug] Templating multi value variable, initial current state should have value as array

### ISSUE THREAD

**Issue by sileht** [grafana/grafana#9290]
Please include this information:
- What Grafana version are you using?
4.5.1

- What datasource are you using?
I discover it with gnocchixyz-gnocchi-datasource, but should occurs with all datasources

- What OS are you running grafana on?
reproduced on centos 7.3, 7.4 and with the official grafana docker image.

- What did you do?

When I import a new dashboard where a templating item have the 'current' field empty and "multi:true":

  templating: {   list: [ {  multi: true, allValue: null,  current: {}, ... } ] }
 
The templateSrv formater returns a string instead of an array of strings when we use replace().

My guess is the usage of "_.isArray(variable.current.value)" here is wrong or the initial value of variable.current is wrong when the dashboard is loaded the first time:

https://github.com/grafana/grafana/blob/master/public/app/features/templating/variable_srv.ts#L164

When "current" is unset in the template, variable.current.value does not yet exists, so variable_srv assumes the template have "multi:false", but the template have "multi:true".

All template formaters assume current.value to be a array when multi:true and a string when false.

(https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateSrv.js#L118)

- What was the expected result?

Initial value of variable.current.value correctly set to {value: ["first-item"]} when the template doesn't provide it and multi:true.

- What happened instead?

Initial value of variable.current.value is wrongly set to {value: "first-item"} when the template doesn't provide it and multi:true.

**Comment by torkelo** [comment]
What is refresh option set to? Try setting current.value to empty array

**Comment by sileht** [comment]
refresh is set to 1
I have try to set current.value to an empty array or an array without random values but that doesn't workaround the issue.

**Comment by torkelo** [comment]
It doesn't? What happens then?

**Comment by sileht** [comment]
The template https://github.com/nhicher/gnocchi-collectd/blob/master/files/grafana-gnocchi-collectd.json

**Comment by sileht** [comment]
The same as with the empty variable.current it's replaced by {value: "first-item"} instead {value: ["first-item"]}

**Comment by sileht** [comment]
I don't known if that important but the dashboard is uploaded through Grafana API

**Comment by sileht** [comment]
Also after dashboard is loaded with the wrong value for variable.current. If I change the options in the selector then the thing work as expected.

**Comment by sileht** [comment]
It looks like if I set includeAll: true, the issue is not triggered.

**Comment by hugohaggmark** [comment]
We've done a lot of work lately around this, and I think we fixed most of this when we migrated the Variable system to Redux. I'm going to close this for now but we can always reopen this if I've missed something in this issue.

Thank You to you for taking the time to create this issue!
