### ISSUE TITLE
[Feat Req] Clickable cell links to dashboards should support passing global time variables

### ISSUE THREAD

**Issue by thibodux** [grafana/grafana#9291]
First, many thanks for the clickable cell link feature in 4.5.1 from #3754.

My request is that this feature should be extended to allow passing the global time variables to the target dashboard. In the "URL" setting for a cell, you should be able to do include something like `?from=$from&to=$to`. Otherwise, you can only hope that the default time filter value of the target dashboard overlaps with the current time filter on the source dashboard.

**Comment by lizhiling** [comment]
+1

**Comment by davidohana** [comment]
+1

**Comment by TayZ25** [comment]
+1

**Comment by vejadu** [comment]
+1

**Comment by aryabov18** [comment]
+1

**Comment by pseudocoder** [comment]
+1

Total hack solution for now - use Javascript in the link to copy the current URL params:

(URL of your dashboard)?var-host=${__cell}" onclick="window.location=this.href + window.location.href.replace(/.*(from=[^&]+).*(&to=[^&]+).*(&refresh=[^&]+).*/,'&$1$2$3')

**Comment by cattt84** [comment]
@pseudocoder I appreciate your total hack solution. I think you are lacking an & behind the variable var-host=${__cell}&' otherwise the variable value and the time variables are just all shown as value for the variable. 
Furthermore I have a question: did you try to make it open in a new tab? Whenever I select that a new tab opens with the overview of all dashboards and the linked dashboard continues opening up in the same tab as the one it was linked from. Unfortunately I am not enough into javascript to understand how that could be changed :D Thank you again for your comment!

**Comment by candyleer** [comment]
> @pseudocoder I appreciate your total hack solution. I think you are lacking an & behind the variable var-host=${__cell}&' otherwise the variable value and the time variables are just all shown as value for the variable.
> Furthermore I have a question: did you try to make it open in a new tab? Whenever I select that a new tab opens with the overview of all dashboards and the linked dashboard continues opening up in the same tab as the one it was linked from. Unfortunately I am not enough into javascript to understand how that could be changed :D Thank you again for your comment!

if you want to open in new tab ,you can use window.open() method,like 
```
" onclick="args = window.location.href.match(/(from|to|refresh)=[^&]+/g); window.open('url of your target dashboard?var-host=${__cell}&' + (args != null ? args.join('&') : ''))
```

**Comment by candyleer** [comment]
@torkelo any schedule to support this feature?

**Comment by cgiraldo** [comment]
@pseudocoder thanks for your hack.

I added my hack code to update a single variable from cell content without modifying the rest of the variables:

```
" onclick=" window.location = window.location.href.replace(/&var-timestamp=[^&]*/g,'')+'&var-timestamp=${__cell_0}000000' "
```
Graph 'Data links' has also an interesing `${__all_variables}` option (but does not work in Table Links).

**Comment by ulikl** [comment]
+1

**Comment by torkelo** [comment]
This was implemented some time last year via data links, and the new table panel supports data links & time variables
