### ISSUE TITLE
[Feature Request] . Value-to-text for Y Axis in Graphs.

### ISSUE THREAD

**Issue by evanrich** [grafana/grafana#9292]
Please include this information:
- What Grafana version are you using?  4.3.2
- What datasource are you using?  MySQL
- What OS are you running grafana on? Centos 7

I tried doing a search first and didn't come up with anything relevant for just graphs, so apologies if this is a dupe.   I know there are value-to-text mappings for single stats, but I'd like to advocate for a Y-axis value-to text mapping (or custom range...if you will).    Take the below image:
![image](https://user-images.githubusercontent.com/518320/30559556-e63edf3e-9c69-11e7-8975-49201562482d.png)

This particular graph will only have a value range of 1-7, never higher or lower.  As is, I've had to add a single row text field with a legend showing the Number-to-text mapping.   Given that this graph will never change besides 1-7, I'd like to be able to label the Y-axis something like "Success, FAIL, error, etc... instead of just the numbers.   I realize this is a somewhat limited scope, but I'm sure there are others out there in similar situations that might find this useful.

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/1032

**Comment by ChimealHeltei** [comment]
+1

**Comment by psarossy** [comment]
In https://github.com/grafana/grafana/pull/12609 the request is to file an FR which didn't happen separately but points to this request. The request there was due to wanting to gauge user interest. Is that looking for +1's here or is there another method?

I use grafana/influxdb to log MQTT sensor data messages, and some of these are protobuf/ENUM-like status indicators (e.g. 0 - AC off, 1 - AC heat, 2 - AC cool, 3 - AC fan on). Some of them have like 30 different states (e.g. Z-Wave door locks) and to be able to track their historical states I use graphs like the one above, and have to map these backwards in my head, which is rather sub-optimal.

**Comment by torkelo** [comment]
use the thumb up emote on the first issue comment to vote for this feature

**Comment by JDSymington** [comment]
This would also be really handy for plotting wind direction using compass direction (N, NW, SE etc.)
At the moment I'm using degrees, but that is not really intuitive.

**Comment by WhitingPetroleum** [comment]
This would be very useful for having graphical boolean panels. It's nice to see when something has gone from On to Off, historically.

**Comment by earlgrei** [comment]
+1

**Comment by BonesyWonesy** [comment]
+1

**Comment by HakamSaffour** [comment]
+1

**Comment by dezka** [comment]
+1

**Comment by arturomp** [comment]
How come [this](https://github.com/grafana/grafana/pull/12609) hasn't been merged?

**Comment by larsjohnson** [comment]
+1.  We have many fields with enumerated values, and need a visual way of assigning the number with a short text value either in the y-axis or in the graph tooltip popup

**Comment by bradfrosty** [comment]
+1 would also find this feature useful for mapping "success" and "failure" over time in Graph Panel.

**Comment by amorphic** [comment]
I went to graph an enum today and assumed this would already exist in Grafana. Really surprised that it doesn't. Would really appreciate this feature being added.

**Comment by lealceldeiro** [comment]
Could anyone, please, give an update on the status of this?
Is it even planned to be added?
