### ISSUE TITLE
[Feature request] Bring back optional URL decoding of metric names

### ISSUE THREAD

**Issue by tybook** [grafana/grafana#9293]
- What Grafana version are you using?
4.3.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS 7

- What did you do?
Added Graphite metrics whose names contain URL-encoded special characters

- What was the expected result?
Grafana would URL decode the metric names like the graphite-web dashboard does

- What happened instead?
Grafana leaves the metric names as-is without URL decoding

It appears this used to be supported, but was removed in #506. I have a lot of dynamically created Graphite metrics which contain special characters which need to be URL encoded; it isn't an option to manually create alias for all of them. The graphite-web dashboard properly decodes the metric names so things look nice on the frontend. It would be nice if Grafana mirrored this functionality, at least optionally.

**Comment by torkelo** [comment]
Sorry, this needs to be solved in Graphite not Grafana. No way for Grafana to know if a series name is url decoded and needs to be decoded, and a new option only for this hacky work around is not a good idea.

**Comment by tybook** [comment]
For posterity, I worked around this by using the Graphite `aliasSub` function to manually substitute the URL encodings I cared about. E.g. `aliasSub(URL_ENCODED_METRIC_NAME_HERE, '%3a', ':')` for colons.
