### ISSUE TITLE
Grafana: Grafana 11.2.0 systemd unit  cannot be enabled in Enterprise Linux 9 variants by default

### ISSUE THREAD

**Issue by carlosrodfern** [grafana/grafana#92949]
### What happened?

This error is reproducible in Centos Stream 9, and Rocky Linux 9

```
systemctl enable --now grafana-server.service

Synchronizing state of grafana-server.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable grafana-server
Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory
```

This is happening because `systemd` is finding the init.d script the RPM installs as well at `/etc/rc.d/init.d/grafana-server`.

The workaround is to install `chkconfig` in addition to `grafana-server` which comes with `/usr/lib/systemd/systemd-sysv-install`; or to manually remove `/etc/init.d/rc.d/grafana-server` post install.

Since the RPM already comes with a grafana-server systemd unit, the best experience would be to remove the init.d script install in EL9 systems. Another less than ideal solution would be to make `chkconfig` a dependency in the rpm.

This began to happen with Grafana 11.2.0, which includes the init.d script in the RPM files. Grafana 11.1.4 does not install the init.d script, so it works.

### What did you expect to happen?

The service is enabled

### Did this work before?

Yes, in Grafana 11.1.4

### How do we reproduce it?

1. Add the grafana repo
2. `dnf install grafana`
3. `systemctl enable --now grafana-server`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.0
OS: Centos Stream 9, Rocky Linux 9
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by a-zb** [comment]
Ditto. systemctl enable or disable on RHEL9 fails with error:

Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory

Version: Grafana v11.2.2+security-01 (dc86a9eafb)

**Comment by Vitaliy155** [comment]
Hi,

Grafana v11.3.0 and Alama 9 - the same issue with enable  service

**Comment by kminehart** [comment]
This should be reoslved in the most recent releases (11.4.0, 11.3.1, 11.2.5, 11.1.10, 11.0.9, 10.4.14). I'm going to close it but we can reopen if the issue persists
