### ISSUE TITLE
FireHD with Fully Kiosk Browser: Grafana is not working

### ISSUE THREAD

**Issue by manuxi** [grafana/grafana#92980]
### What happened?

I use two tablets to display my ioBroker VIS-2, a Samsung Galaxy Note 2014 Edition (old) and a FireHD (new).
Both are running the latest version of the Fully Kiosk browser (1.56.1). The VIS-2 runs almost without problems.
But only almost.
I use Grafana in the iFrame on many screens. However, I have recently started getting the following message with FireHD:
```
If you’re seeing this Grafana has failed to load its application files
This could be caused by your reverse proxy settings.
If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.
IF you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build
Sometimes restarting grafana-serve can help
Check if you are using a non-supported browser. For more information, refer to the list of supported browsers.
```

Recently means ~ 2 Months. I'm not sure but I did a Grafana update at this time. I usually update regularly.

On the (now 10 year old) Galaxy Note everything works fine. Also in Chrome on that FireHD it's working. It seems that it's a combination of FireHD and Fully Kiosk Browser.
I have tried tips such as deleting the history, cookies, etc. in Fully Kiosk Browser without success.

### What did you expect to happen?

Grafana is working

### Did this work before?

Yes, 2 months ago everything worked fine.

### How do we reproduce it?

Load a Page with a Grafana iFrame in Fully Kiosk Browser

### Environment (with versions)?

Grafana: Grafana v11.2.0 (2a88694fd3)
OS: FireOS
Browser: Fully Kiosk Browser

### Grafana platform?

Docker

### Datasource(s)?

influxdb

**Comment by jackw** [comment]
Hello,

Many thanks for reporting this. From looking at your issue it seems to be an incompatibility with the fully kiosk browser and the latest version of Grafana. However it appears Grafana loads correctly on the same Fire HD device using Chrome? I'm not aware of the fully kiosk browser and it's not one we [officially support](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers) either I'm afraid.  From looking at their FAQs it seems they use the `Android Webview` to render webpages.  Have you checked [rheir FAQ page](https://www.fully-kiosk.com/en/#faqs) as it has some tips for webpages that don't work correctly?

**Comment by gabriellxxix** [comment]
Grafana 11+ Update Broke Kiosk Mode in iFrame?
After updating my Grafana server to version 11+, I've noticed that the kiosk mode is no longer working as expected when embedding dashboards via iFrame. Specifically, the embedded content now shows undesired areas of the interface instead of displaying just the charts.

https://www.reddit.com/r/grafana/comments/1h8g6yn/grafana_11_update_broke_kiosk_mode_in_iframe/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by manuxi** [comment]
Got it to work. Had to update the Webview on the FireHD.
