### ISSUE TITLE
Authentication: when using auth_proxy and ldap, any user can login.

### ISSUE THREAD

**Issue by keith6014** [grafana/grafana#93018]
### What happened?

Running version 11.1.4 with nginx. Authentication is being done by nginx with remote_user. The user gets propagated to Grafana. It determines the user's attributes perfectly fin via LDAP (Active Directory). However, even if the user isn't part of the LDAP group she is able to view the dashboard. 

```
[server.attributes]
name="givenName"
surname="sn"
username="sAMAccountName"
member_of="memberOf"
email="mail"

[[server.group_mappings]]
group_dn="CN=DOESNOTEXIST"
org_role="Admin"

[[server.group_mappings]]
group_dn="CN=DOES_NOT_EXIST_ALSO"
org_role="Viewer"
````

When the user logs in using Safari/Firefox, she is able to see the dashboards perfectly fine! Which should be the case.

Nothing specific in the debug log.

### What did you expect to happen?

If the user isn't part of the AD group, she should not be able to login. 

### Did this work before?

I am not sure. 

### How do we reproduce it?

1.Use HTTP_PROXY authentication. 
2.Use LDAP Authorization. 
3.Create a group mapping which doesn't exist
4. The user is still able to login!

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:11.1.4
OS: Windows/Mac/Linux
Browser: Chrome/Firefox/Mozilla/Safari

### Grafana platform?

A downloaded binary

**Comment by Jguer** [comment]
Hey @keith6014 , can you share your relevant grafana cfg (auth_proxy and ldap) with secrets censored?
