### ISSUE TITLE
Re-create target object in QueryController when datasource type changed

### ISSUE THREAD

**Issue by ahules** [grafana/grafana#9301]
- What Grafana version are you using: 4.5.1
- What datasource are you using: PrivateDatasource
- What OS are you running grafana on: OSX
- What did you do: developing datasource
- What was the expected result: worked datasource
- What happened instead: errors

I think we must to create new empty target object for QueryController when Datasource is changed when new Datasource has different type. Because different plugins write variables to target object in different formats, this case break's my plugin.

For example if default datasource has type simple-json-datasource and then i change datasource to another type.

In the constructor of query controller i see that this.target contains data setted by simple json plugin. 

<img width="1446" alt="screenshot 2017-09-19 14 25 09" src="https://user-images.githubusercontent.com/1193007/30590329-c39f06f6-9d46-11e7-895b-baae4aec0cb8.png">

<img width="1453" alt="screenshot 2017-09-19 14 26 23" src="https://user-images.githubusercontent.com/1193007/30590309-b30055c0-9d46-11e7-8f5a-cb03977426ac.png">

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630). We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
