### ISSUE TITLE
Azure Monitor plugin: Link from Prometheus exemplars to App Insights fails

### ISSUE THREAD

**Issue by kayodeprinceMS** [grafana/grafana#93014]
### What happened?

Testing on 11.2
Prometheus and Azure Monitor datasources configured successfully.

Default Azure Monitor subscription is saved as expected.

Exemplars and traces are working fine independently but the automatic integration via Exemplar link is not.

![Image](https://github.com/user-attachments/assets/fd095cfa-1176-47b4-8f90-b3465c0186aa)

Trace query works as expected when App Insights resource is specified

![Image](https://github.com/user-attachments/assets/6b465c22-0279-4c43-b204-8472b48e78ce)

Generic 500 error thrown for plugin error

![Image](https://github.com/user-attachments/assets/db5a31c0-875f-47c1-9f8a-0157b98412c3)

### What did you expect to happen?

Link to Exemplar to open App Insights trace

### Did this work before?

No

### How do we reproduce it?

1. Configure Prometheus datasource Exemplars with internal link to Azure Monitor
2. Query Prometheus with exemplars
3. Click on Exemplar link to drill down to Azure Monitor trace

### Is the bug inside a dashboard panel?

No, this is in Explore

### Environment (with versions)?

Grafana: 11.2.0
OS: Windows
Browser:Edge and Chrome

### Grafana platform?

Docker

### Datasource(s)?

Azure Monitor

**Comment by kayodeprinceMS** [comment]
cc: @taleena for tagging and labels

**Comment by aangelisc** [comment]
Hi @kayodeprinceMS,

Are you able to share any Grafana logs that may provide insight into the failing request? Are you authenticating via user-auth or an App registration? I've tested this with an App Registration and it's functioning as expected.

**Comment by kayodeprinceMS** [comment]
This test was performed with Azure Managed Identity used for auth enabled on both data sources. Will loop in @jcolladokuri for log collection.

**Comment by kayodeprinceMS** [comment]
Hi @aangelisc 

Here is the log msg when running locally with App Registration auth for the same error. 
I've manually replaced the full subscription id with a placeholder <sub_id> but everything else is the same as copied from the lo including the repeated https://management.azure.com in the url string.

logger=context userId=1 orgId=1 uname=admin t=2024-09-13T14:45:11.6082586Z level=error msg=InternalError error="[plugin.downstreamError] client: failed to query data: failed to build azure application insights query: failed to retrieve correlation resources for operation ID - 1e89809ced73ddeaddab25ec0dff3554: Get \"https://management.azure.com/https://management.azure.com/subscriptions/<sub_id>/providers/microsoft.insights/transactions/1e89809ced73ddeaddab25ec0dff3554?api-version=2019-10-17-preview\": context canceled" remote_addr=[::1] traceID=

**Comment by jcolladokuri** [comment]
I was able to run the API separately and verified that it worked:

URL: `https://management.azure.com/subscriptions/<sub_id>/providers/microsoft.insights/transactions/<trace_id>?api-version=2019-10-17-preview`

![Image](https://github.com/user-attachments/assets/32fe796c-c49c-4c23-96b6-218feefde87a)

**Comment by aangelisc** [comment]
Hi @kayodeprinceMS,

Can you confirm if this is a consistent issue that you're seeing? Are you able to run the request with tracing enabled on the Grafana data source to allow us to determine if the HTTP request itself is timing out.

This is possible by running Grafana and a local Jaeger docker container with the following configuration:

Jaeger docker compose:
```
services:
  jaeger:
    image: jaegertracing/all-in-one:1.42
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
    environment:
      - COLLECTOR_OTLP_ENABLED=true
```

Grafana config:
```
[tracing.opentelemetry.jaeger]
address = http://localhost:14268/api/traces
```

This will allow you to configure a Jaeger data source in Grafana and search for traces with the operation name `azure traces correlation request` which should show the duration of the request. Can you also confirm the timeout set in your Grafana instance - is it the default 30s (found under the `dataproxy` config section)?

**Comment by kayodeprinceMS** [comment]
Will do. I can set this up now and get back to you in a few mins.

**Comment by aangelisc** [comment]
Hi,

That is interesting, and it's not something I see in the equivalent traces on my side. Some additional questions from me:

- Are you able to share version details e.g. commit, OSS/enterprise etc. 
- Does the Azure Monitor data source have a default subscription set or none at all? 
- Do you see the duplicated URL path if you query an Operation ID directly rather than attempting an exemplars query?

Are you using the example app that I shared to generate data? If so, are you running Grafana via Docker or via binary? Do the exemplars display as expected in the Grafana instance included within the example app?

**Comment by kayodeprinceMS** [comment]
11.2 Enterprise on local and Pro on Azure Managed Grafana

![Image](https://github.com/user-attachments/assets/73c9d570-ddb1-4af0-86d5-2dcdff74c0d4)

Tested both cases, before and after setting default subscription. Same behavior.

Queries to operation ID also have the duplicated URL path

Using a different demo app: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/exemplars/README.md but configured to send traces to AI with AzMon OTel exporter.

Grafana binary on local, AMG image in Azure.

Exemplars display as expected with correct trace IDs both on local and AMG, only drill down to AI fails.

**Comment by aangelisc** [comment]
Thank you for the additional information. You mentioned before that you attempted this with an Azure data source authenticated via Managed Identity. Can you attempt the same with an App Registration and let me know if this behaviour is still present please.

**Comment by kayodeprinceMS** [comment]
I've tested with MI auth to AMW and App Insights on AMG in Azure, and App Registration auth to App Insights and local auth to Prom on dev box with local Grafana.

**Comment by aangelisc** [comment]
Are you able to run the same scenario using the docker image described [here](https://github.com/grafana/grafana/pull/93534/checks?check_run_id=30432881463). It has some additional logs which may give insight into why the URL is malformed.

**Comment by kayodeprinceMS** [comment]
Tested with Grafana version specified above and using Jaeger for local traces. Same behavior as before with no apparent differences in how URL is formed with or without App Insights resource specified. Will test indexer API independently and update the thread.

![Image](https://github.com/user-attachments/assets/32c233b2-ff01-481b-9f93-7168d4101bb5)

![Image](https://github.com/user-attachments/assets/33bbcaec-c8b6-4298-ad53-84a0acd32fd8)

**Comment by aangelisc** [comment]
> Tested with Grafana version specified above and using Jaeger for local traces. Same behavior as before with no apparent differences in how URL is formed with or without App Insights resource specified. Will test indexer API independently and update the thread.
> 
> ![Image](https://github.com/user-attachments/assets/32c233b2-ff01-481b-9f93-7168d4101bb5)
> 
> ![Image](https://github.com/user-attachments/assets/33bbcaec-c8b6-4298-ad53-84a0acd32fd8)

Thanks @kayodeprinceMS, are you able to submit the additional logs that should've been emitted please?

**Comment by kayodeprinceMS** [comment]
Jaeger traces in JSON format linked:

[trace_lookup_with_AI_success.json](https://github.com/user-attachments/files/17151496/trace_lookup_with_AI_success.json)
[trace_lookup_without_AI_failure.json](https://github.com/user-attachments/files/17151495/trace_lookup_without_AI_failure.json)

It appears to me that the malformed URL issue is not the reason for the drill down failure. In my case, the indexer call returns 404 when the AI resource is not provided but is successful when it is provided. In both cases the malformed url is being used as the target. I'm able to repro this indexer behavior outside of Grafana as well. Will investigate further with the App Insights tracing team.

**Comment by aangelisc** [comment]
Thank you for the update. I'd still like to see the logs to understand why you see a malformed URL when we do not. Please keep us informed on the outcome with the tracing team 😊

**Comment by kayodeprinceMS** [comment]
Can you clarify the logs you are referring to? The traces in the previous comment include the logs for each request.

**Comment by aangelisc** [comment]
I've added some additional logs in [this](https://github.com/grafana/grafana/pull/93534/files) PR that should be available in the Grafana logs which will hopefully allow me to identify why the malformed URL is present.

**Comment by kayodeprinceMS** [comment]
Adding logs. No occurrence of the the duplicate url there.
 [Logs.txt](https://github.com/user-attachments/files/17156240/Logs.txt)

**Comment by aangelisc** [comment]
Thank you for confirming. Let us know the response from the AI team or if we can help debug further.

**Comment by kayodeprinceMS** [comment]
Ack, will work with the App Insights team on the indexer API expected behavior. 
Still curious why the duplicate url shows up in the Jaeger traces Target but it's no longer in the Grafana logs as in the previous version.

**Comment by kayodeprinceMS** [comment]
Confirming that this behavior is based on an App Insights indexer limitation. Only trace_ids that contain request/dependencies are indexed. The App Insights resource lookup will not work for cases where the trace data contains only dependencies without requests as in the case in one of the demo apps that was being tested. 

I think the new 404 failure message that indicates the App Insights resource was not found is good enough for now until we get a different recommendation from the App Insights team.

**Comment by aangelisc** [comment]
Awesome, thank you for the update. Closing this issue out now 😊

**Comment by kayodeprinceMS** [comment]
@aangelisc 

Update: The recommendation from the App Insights team is that this is expected to be a corner case and will not be supported in the short term.

Can we add a more graceful, user-friendly message for this case when App Insights Indexer API does not have a record of the trace_id?
A warning that reflects 'The requested trace was not found by Application Insights indexing, select the relevant Application Insights resource to search for the Operation ID directly."

![Image](https://github.com/user-attachments/assets/f31545cf-abcf-4c6b-a43a-cc350fffeb42)

**Comment by aangelisc** [comment]
@kayodeprinceMS sure, I've created an issue for this work - #95248
