### ISSUE TITLE
[Bug] Pid path is ignored in .rpm package

### ISSUE THREAD

**Issue by FireHelmet** [grafana/grafana#9304]
Hi

- What Grafana version are you using? 4.5.1
- What datasource are you using? N/A
- What OS are you running grafana on? CentOS 7
- What did you do? systemctl start grafana-server
- What was the expected result? Grafana start correctly and PID created in /var/run/ not in /
- What happened instead? lvl=eror msg="Failed to write pidfile" logger=server error="open /grafana-server.pid: permission denied"

Screenshot of /var/log/grafana/grafana.log
![image](https://user-images.githubusercontent.com/17533298/30592944-21ff5f00-9d49-11e7-9c0e-7853fc24143b.png)

Screenshot of //etc/init.d/grafana-server
![image](https://user-images.githubusercontent.com/17533298/30592989-53d0580e-9d49-11e7-88ed-97fe149c3475.png)

Could you correct the issue ?

Thank you

**Comment by torkelo** [comment]
use PID_FILE_DIR for env variable for systemd setups, then systemd will create the folder with the right user permissions

**Comment by torkelo** [comment]
the init.d/grafana-server file is not used if you have systemd

**Comment by juanpaulo** [comment]
ran across this issue post-upgrade and figured out that reinstalling grafana created a new sysconfig file called `/etc/sysconfig/grafana-server.rpmnew`.

```
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : grafana-4.5.2-1.x86_64                                                                                                               1/2
warning: /etc/sysconfig/grafana-server created as /etc/sysconfig/grafana-server.rpmnew
  Cleanup    : grafana-4.4.2-1.x86_64                                                                                                               2/2
POSTTRANS: Running script
  Verifying  : grafana-4.5.2-1.x86_64                                                                                                               1/2
  Verifying  : grafana-4.4.2-1.x86_64                                                                                                               2/2

Updated:
  grafana.x86_64 0:4.5.2-1

Complete!
```
since systemd wouldn't read the .rpmnew file, you should either add [PID_FILE_DIR](https://github.com/grafana/grafana/commit/c3cffeb10ccd586b21774d54a1ebf434fddb2112#diff-b446e7eb8ccffae3702a55ccf6281fec) to your sysconfig file, or mv the new one if you don't have any custom code in your sysconfig file. @FireHelmet

**Comment by FireHelmet** [comment]
@juanpaulo Thank you for this update ! I have moved to the new sysconfig file.

**Comment by gontikas** [comment]
+1 for the .rpmnew issue. 
the old grafana-server file did not include the following lines about PID. When I replaced with .rpmnew I could restart the grafana. 

# Only used on systemd systems
PID_FILE_DIR=/var/run/grafana
