### ISSUE TITLE
Set User's Grafana Organisation with Generic OAuth JSON on Login

### ISSUE THREAD

**Issue by Rotario** [grafana/grafana#93046]
Thanks for all your hard work this is so close to being perfect for a custom OAuth provider application with seamless Grafana integration

**Why is this needed**:

I'm trying to assing a user's organisation from my Generic OAuth application in a json payload

```
    render json: {
             email: user.email,
             name: user.email,
             login: user.email,
             :org => user.organisation.grafana_org_id,
             role: user.grafana_role
           }
```
The user email with auto_sign_up works really well, and role mapping works really well too.
The only thing missing is assigning a user's organisation by a grafana org id or name.

**What would you like to be added**:

An option to map an external organisation from an oauth provider has already been added with
```
org_attribute_path = organisation
org_mapping = 
```
But org_mapping needs to be hard-coded in grafana.ini and is a more complicated case than just assuming the OAuth provider knows about grafana organisations and can return the exact one for the user.

If I could omit org_mapping and just do `org_attribute_path = organisation_id` just like the `role_attribute_path` *already works* then that would be amazing.

Side note: the fact that role_attribute_path and org_attribute_path function in wildly different ways is massively confusing.

**Who is this feature for?**

This feature is extremely useful for anyone adding Grafana to their applications and want to support the smoothest grafana experience possible to their users

**Comment by Jguer** [comment]
Hey @Rotario , we've considered this scenario but decided against it as it would not allow assigning the same user to multiple orgs. 

This makes org_attribute_path behave more as `group_attribute_path` than `role_attribute_path` instead.

I'm closing this issue for now, but feel free to add any extra info and ideas

**Comment by Rotario** [comment]
Hi Joe,
No problem. In that case it's not documented whether it's even possible to
use org attribute path without hard coded org names in the org mapping.

Is this possible?

Thanks
Rowan
