### ISSUE TITLE
use metric as color hash in timeseries data

### ISSUE THREAD

**Issue by jonnytest1** [grafana/grafana#93061]
### What happened?

i have a timeseries graph with a bunch of different data lines 

query looks something like this :

```
SELECT 
  payload as value,
  time_col as timestamp,
  label as metric
FROM tablename
WHERE $__timeFilter(time_col)
```

now each time the query loads all the label/metric based lines get different colors 

the closest i found to what i want is the color scheme "classic palette (series name)" unfortunately is doesnt use the metric value but always gets passed "value" since thats the field name 

how i would like it to go:

https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/fieldColor.ts#L221
in fieldColor.ts#getCalculator:

currently:

`colors[Math.abs(stringHash(field.name)) % colors.length]`

what i would like:

`colors[Math.abs(stringHash(field.labels?.metric ?? field.name)) % colors.length]`

### What did you expect to happen?

the get the same color by metric name

### Did this work before?

not that i know

### How do we reproduce it?

- i tried normal color scheme with order by metric but that still scrambled it (not sure where the seriesIndex gets set)

aside from that just some data with metric labels

### Is the bug inside a dashboard panel?

well the panel implementation 🤔

### Environment (with versions)?

Grafana: <still this way in the most recent version>
OS: windows
Browser: chrome

### Grafana platform?

Kubernetes

**Comment by leeoniya** [comment]
> currently:
>
> `colors[Math.abs(stringHash(field.name)) % colors.length]`

i think this is a mistake, we should instead use `stringHash(field.state.displayName ?? field.name)`, since displayName includes the logic that uniquely names fields such as Value, by looking at unique labels, etc., and generates the legend names you see.

**Comment by jonnytest1** [comment]
oh sure - i didnt see that one - works for me

**Comment by jonnytest1** [comment]
🤔 whats the branching situation here ? i just upgraded my grafana to 11.2.1 and assumed tht its in there cause it got merged into 11.2.x , but its still the old one

**Comment by jonnytest1** [comment]
ah nevermind i pulled the graph - ![Image](https://github.com/user-attachments/assets/251cd7d5-e7ce-4d5e-af54-956c76779662)
seems like that change was missed by 4 days ^^ - gonna be the next one i assume 😌

**Comment by jonnytest1** [comment]
btw , is that on purpose that the brnaches arent "merged back" in a way that git would understand ? i found Release: 11.2.1 commits in 11.2.x but its not discovered as a merge commit 🤔
