### ISSUE TITLE
Table Export to CSV: Export more than 500 rows

### ISSUE THREAD

**Issue by thewillyhuman** [grafana/grafana#93068]
### What happened?

We have an OpenSearch datasource with a query and the limit of the query set to 10.000. The result of this query is displayed on a table visualisation with some transformations.. The table visualisations looks like it loads around 500 elements at a time which is fine for us. But when exporting the table to CSV it also exports always only 500 elements, instead of all of the elements returned by the query.

If we edit the table, force an update of it and export to csv then yes, the full set of 10.000 results is exported.

### What did you expect to happen?

That the 10.000 results are exported.

### Did this work before?

We do not know.

### How do we reproduce it?

1. Have an elasticsearch datasource that results more than 500 elements. Our limit is set to 10.000.
2. Create a table visualisation using the above datasource and some transformations.
3. From the dashboard where the visualisation is try to export the data from the table in CSV.

### Environment (with versions)?

Grafana: 10.2.2
OS: Independent.
Browser: Independent.

### Grafana platform?

A downloaded binary

### Datasource(s)?

[Open|Elastic]Search

**Comment by iwysiu** [comment]
Hi @thewillyhuman ! Can you give us the queries for the panel and tell us what version of the Opensearch plugin you're using? (if you navigate to the plugin underneath the Administration section you can see the plugin version)
![Image](https://github.com/user-attachments/assets/060fbc30-20c5-4133-8141-9563831174fb)

I tried reproducing this locally with Opensearch but I was able to export the whole csv, so it would be helpful to know exactly what queries and transformations you're running.

**Comment by thewillyhuman** [comment]
Hi @iwysiu. We were using the ElasticSearch datasource to connect to the OpenSearch backend. After your comment I noticed that and updated the datasource to be OpenSearch. Now it looks like it is working, still to be ensured. Once it is I will close the issue. Otherwise will report back. Many thanks!!

**Comment by thewillyhuman** [comment]
Hi again, to confirm that this solution works. Issue can be closed safely.
