### ISSUE TITLE
[Bug] HTTP head request does not work in v4.5.1, always return 404

### ISSUE THREAD

**Issue by yinym** [grafana/grafana#9307]
- What Grafana version are you using?
   4.5.1
- What datasource are you using?
   N/A
- What OS are you running grafana on?
   official docker container (https://hub.docker.com/r/grafana/grafana/)
- What did you do?
   Start the Grafana container with no extra configuration and curl to /login page with HEAD request
   ```
   # docker run -d -P grafana/grafana:4.5.1
   # docker ps
   CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                     NAMES
   0a80c9ab63bd        grafana/grafana:4.5.1   "/run.sh"                3 seconds ago       Up 2 seconds        0.0.0.0:32768->3000/tcp   infallible_murdock

   # curl -v -s --head http://127.0.0.1:32768/login
   *   Trying 127.0.0.1...
   * Connected to 127.0.0.1 (127.0.0.1) port 32768 (#0)
   > HEAD /login HTTP/1.1
   > Host: 127.0.0.1:32768
   > User-Agent: curl/7.47.0
   > Accept: */*
   > 
   < HTTP/1.1 404 Not Found
   HTTP/1.1 404 Not Found
   < Content-Type: text/html; charset=UTF-8
   Content-Type: text/html; charset=UTF-8
   ```
- What was the expected result?
  The above request should return `200 OK`
- What happened instead?
  The head request to `/login` page returns `404 NOT FOUND`

I tried 2 alternative ways:
1. Try to directly use `HTTP GET`, it works, return 200 OK
2. Try v4.5.0 with `HTTP HEAD`, it works, return 200 OK

**Comment by yinym** [comment]
Maybe it is related to recent change to `pkg/api/api.go` in commit https://github.com/grafana/grafana/commit/6372e221802817483ce8767ef650cee5402ef5c8

Seems like the `SetAutoHead()` does not work anymore.

**Comment by bergquist** [comment]
Thanks for reporting this!
