### ISSUE TITLE
Alerting: docs feedback on functions in templating

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#93084]
### What happened?

Looking at the documentation for using Go templates in alerting, I can’t find a list of the supported functions in the [reference](https://grafana.com/docs/grafana/latest/alerting/configure-notifications/template-notifications/reference/).

 By testing I found some of them, eg. “js” encodes a string in a javascript safe way, and index finds a value for a key. What I need is something like “fromJson” which looks like it is supported elsewhere in Go templated strings, e.g. [for Loki queries](https://grafana.com/docs/loki/latest/query/template_functions/#fromjson)

It mentions some of the function available, like “index” and “range”, and refers to the [Reference](https://grafana.com/docs/grafana/latest/alerting/configure-notifications/template-notifications/reference/) page for everything else. The ref page describes the data structure of Alerts, but doesn’t provide a list of functions.

### What did you expect to happen?

x

### Did this work before?

x

### How do we reproduce it?

1.
2.x
3.

### Is the bug inside a dashboard panel?

x

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by brendamuir** [comment]
@tonypowa here's one on templating for you!

**Comment by ppcano** [comment]
The available functions are listed at [Template labels and annotations/#Functions](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/templating-labels-annotations/#functions)

However, some functions are not supported in Notification Templates:
- `args`
- `externalURL` 
- `graphLink`
- `humanize**`
- `pathPrefix`
- `tableLink`

We could review the docs in this area. For instance: 
- make more clear that template functions are also available for notification templates. Specify which functions are supported or unsupported
- review if new template functions were added but lacks docs 
- mention [Go template functions](https://pkg.go.dev/text/template#hdr-Functions) such like `printf`, `slice`, `js`, `urlquery`
- differences for data source-managed templates
- ...
