### ISSUE TITLE
[Feature request] Ignore template filter completely

### ISSUE THREAD

**Issue by vanbroup** [grafana/grafana#9308]
Currently, the template filters have an option 'All' which results in a large regex query. You can replace this with a regex '.*' to include all values. Both solutions use a lot of unnecessary resources on the server and will also filter values that don't have this value at all. 

![image](https://user-images.githubusercontent.com/722070/30631777-c364d2fc-9de5-11e7-86f1-f2cbbbe4f1e3.png)

I would like to request an additional selection option, 'Ignore' that will just remove this filter from the query completely.

**Comment by torkelo** [comment]
Sadly this is not possible (or it depends on the query language or how the variable is used):

For example: `WHERE server =~ /$servers$/`   

The contemplating system is based on string interpolation, it cannot modify the query/text surrounding the variable. 

You can used ad-hoc filters (if your data source supports this Grafana variable style) to dynamically add filters to your query (only works with InfluxDB and Elasticsearch at the moment)
