### ISSUE TITLE
Generic Oauth:  Not behaving as documented w.r.t. missing emails

### ISSUE THREAD

**Issue by arianvp** [grafana/grafana#93088]
### What happened?

I set up Grafana using an OAUth server that has no `email` claim.    According to the docs this should all be fine

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/

> Grafana can resolve the user’s email address from the OAuth2 ID token, the user information retrieved from the OAuth2 UserInfo endpoint, or the OAuth2 /emails endpoint. Grafana looks at these sources in the order listed until an email address is found. **If no email is found, then the email address of the user is set to an empty string.**

However, sign up fails with

```
Sep 09 10:44:29 framework grafana-start[296132]: logger=authn.service t=2024-09-09T10:44:29.508504321+02:00 level=info msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.email.missing] required attribute email was not provided"
```

### What did you expect to happen?

I expected sign up to succeed. Email addresses are optional field for grafana users and the docs also mention it's optional.

### Did this work before?

Not sure

### How do we reproduce it?

1. Try to authenticate with an `id_token` that lacks an email claim
2. Observe the error

### Environment (with versions)?

Grafana: 11.2.0
OS: NixOS
Browser: Chromium

### Grafana platform?

None

**Comment by kalleep** [comment]
Hey, I think the docs are a bit misleading. The email scope are not required to perform but it seems like we require the email property to be set even though it don't have to be a valid email. To make it work you have to map the email attribute to something unique like a username

I tested this out with keycloak and this configuration, noticed that I set `email_attribute_path = preferred_username`
```
[auth.generic_oauth]
enabled = true
name = OAuth 
allow_sign_up = true
client_id = grafana-oauth
client_secret = <redacted>
scopes = openid profile offline_access
email_attribute_path = preferred_username
login_attribute_path = preferred_username
name_attribute_path = full_name
groups_attribute_path = groups
auth_url = http://localhost:8087/realms/grafana/protocol/openid-connect/auth
token_url = http://localhost:8087/realms/grafana/protocol/openid-connect/token
```
