### ISSUE TITLE
Design: Visualizations one-click functionality

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#93121]
We need to figure out the best flow for when one-click (data links or actions) is enabled. The main focus would be the tooltip interaction.

**Comment by staton-hyse11** [comment]
@adela-almasan and I discussed and will be exploring this direction more deeply and want to review with the team next week
![Image](https://github.com/user-attachments/assets/9727d4da-fed8-4d2a-9aa7-c4262bd7d6ef)
