### ISSUE TITLE
time series: y axis values do not match the series

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#93125]
### What happened?

As you can see, the values in the tooltip does not match the y-axis values, I've validate directly with promethues and it's the axis falut
![Image](https://github.com/user-attachments/assets/7d531feb-6261-421f-a857-eaba2afa18cc)

### What did you expect to happen?

This is how it looks like in Prometheus:
![Image](https://github.com/user-attachments/assets/443d8bec-9a24-4209-8d2c-b2e13172388c)

### Did this work before?

yes

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 11.1.4
OS: docker
Browser:

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by leeoniya** [comment]
you haven't provided enough information for us to help you.

please follow the issue template. it's there for a reason.

**Comment by amnonh** [comment]
Found the issue, it was a stack graph
