### ISSUE TITLE
Grafana frontend crashes on startup - process is not defined

### ISSUE THREAD

**Issue by yincongcyincong** [grafana/grafana#93156]
### What happened?

make build
./bin/darwin-arm64/grafana server
![Image](https://github.com/user-attachments/assets/6e3bb58f-35f4-4524-b2e3-02e11699c50e)

### What did you expect to happen?

grafana runing normally

### Did this work before?

yep

### How do we reproduce it?

1. make build
2. ./bin/darwin-arm64/grafana server

### Is the bug inside a dashboard panel?

i think so

### Environment (with versions)?

Grafana: grafana version 11.3.0-pre
OS: macos
Browser: chrome

### Grafana platform?

None

### Datasource(s)?

source code from master branch

**Comment by joshhunt** [comment]
Did you build this from source? Or is this from a released version?

**Comment by yincongcyincong** [comment]
firstly, i don't modify anything in grafana
![Image](https://github.com/user-attachments/assets/fcd4991e-618f-4420-9192-3ca019496e24)
secondly, i use `make build` to build backend and frontend part of  grafana.
![Image](https://github.com/user-attachments/assets/4276cba7-a992-4de8-b23c-ad628ef78041)
@tomratcliffe

**Comment by yincongcyincong** [comment]
i have builded grafana a few minutes ago. i find it can run correctly!
i just repeat operation than i did yesterday.

**Comment by joshhunt** [comment]
@yincongcyincong Do you have a `conf/custom.ini` file? This file is not committed into the repo so it won't show in `git status`, and is used be developers to put development config.

If it's working file for you now that's all good I suppose... I'm still pretty confused how it broke for you the other day.

**Comment by yincongcyincong** [comment]
![Image](https://github.com/user-attachments/assets/bf976c5c-7a3d-40a4-b70d-37dcc2789b0a)
actually, i don't find custom.ini file, i'm sorry.

**Comment by joshhunt** [comment]
Thanks @yincongcyincong. I'm going to close this issue for now. If it happens again and you're able to reproduce, please comment here and ping myself and @tomratcliffe and we'll look into it 👍
