### ISSUE TITLE
With proxy auth enabled, grafana is still redirecting users to login page rather than returning 500/407 (therefor 500/407.html)

### ISSUE THREAD

**Issue by asingla82** [grafana/grafana#9315]
After enabling the auth.proxy, grafana is able to do single sign on. But if the user does not exist in grafana, then it is redirecting the user to login page.  While looking at the code in auth_proxy.go, I was expecting the system to send 500 error code (and use 500.html view).  Also defining auth.proxy.whitelist does not seem to send 407 error code if access the grafana application server directly.

**Comment by torkelo** [comment]
> But if the user does not exist in grafana, then it is redirecting the user to login page. While looking at the code in auth_proxy.go, I was expecting the system to send 500 error code

why did you expect 500 error code? It will cause 401 access denied, and redirect to login page. 

The whitelist will cause a 407 but only if the auth proxy header is present.
