### ISSUE TITLE
Adding Elestio as self-hosted deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [grafana/grafana#93167]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Grafana application as shown [here](https://elest.io/open-source/grafana). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/grafana)

**Comment by tolzhabayev** [comment]
Closing this issue as we have other communication ways for commercial discussions.

**Comment by kaiwalyakoparkar** [comment]
@tolzhabayev can you provide me with that information about the communication ways for commercial discussions?

**Comment by tolzhabayev** [comment]
@kaiwalyakoparkar https://grafana.com/contact has all the different contact channels.
