### ISSUE TITLE
[Bug] "Total" Calculation returning strange values

### ISSUE THREAD

**Issue by tammytankian** [grafana/grafana#9316]
- What Grafana version are you using?
	v4.5.0 

- What datasource are you using?
Zabbix-Grafana 3.6.1

- What OS are you running grafana on?
Debian 9.1

Problem:
Example:
![image](https://user-images.githubusercontent.com/27218076/30663856-5ed8592a-9e22-11e7-995c-78d7b15b0d43.png)
![image](https://user-images.githubusercontent.com/27218076/30663932-9306abfc-9e22-11e7-9c51-b672b3ca2a86.png)

And then
![image](https://user-images.githubusercontent.com/27218076/30664043-cd415c0e-9e22-11e7-92ed-d1f61296b7aa.png)

Another example:
![image](https://user-images.githubusercontent.com/27218076/30664160-2f8b6120-9e23-11e7-91a3-5ea8a0f5066c.png)
![image](https://user-images.githubusercontent.com/27218076/30664231-5dc4dcba-9e23-11e7-9ee1-a797b0f469e5.png)

Configurations of the single stat (same to all of them):
![image](https://user-images.githubusercontent.com/27218076/30664266-7afc8404-9e23-11e7-96f0-4135ea43968e.png)
![image](https://user-images.githubusercontent.com/27218076/30664277-844997ae-9e23-11e7-8c5f-3b26c6220050.png)
![image](https://user-images.githubusercontent.com/27218076/30664284-89f91274-9e23-11e7-94d5-a68c6f54fa7a.png)

The query inspector:

> request:Object
> method:"POST"
> url:"api/datasources/proxy/26"
> data:Object
> jsonrpc:"2.0"
> method:"trend.get"
> params:Object
> id:1
> auth:
> response:Object
> jsonrpc:"2.0"
> result:Array[142]
> 0:Object
> 1:Object
> 2:Object
> 3:Object
> 4:Object
> 5:Object
> 6:Object
> 7:Object
> 8:Object
> 9:Object
> 10:Object
> 11:Object
> 12:Object
> 13:Object
> 14:Object
> 15:Object
> 16:Object
> 17:Object
> 18:Object
> 19:Object
> 20:Object
> 21:Object
> 22:Object
> 23:Object
> 24:Object
> 25:Object
> 26:Object
> 27:Object
> 28:Object
> 29:Object
> 30:Object
> 31:Object
> 32:Object
> 33:Object
> 34:Object
> 35:Object
> 36:Object
> 37:Object
> 38:Object
> 39:Object
> 40:Object
> 41:Object
> 42:Object
> 43:Object
> 44:Object
> 45:Object
> 46:Object
> 47:Object
> 48:Object
> 49:Object
> 50:Object
> 51:Object
> 52:Object
> 53:Object
> 54:Object
> 55:Object
> 56:Object
> 57:Object
> 58:Object
> 59:Object
> 60:Object
> 61:Object
> 62:Object
> 63:Object
> 64:Object
> 65:Object
> 66:Object
> 67:Object
> 68:Object
> 69:Object
> 70:Object
> 71:Object
> 72:Object
> 73:Object
> 74:Object
> 75:Object
> 76:Object
> 77:Object
> 78:Object
> 79:Object
> 80:Object
> 81:Object
> 82:Object
> 83:Object
> 84:Object
> 85:Object
> 86:Object
> 87:Object
> 88:Object
> 89:Object
> 90:Object
> 91:Object
> 92:Object
> 93:Object
> 94:Object
> 95:Object
> 96:Object
> 97:Object
> 98:Object
> 99:Object
> 100:Object
> 101:Object
> 102:Object
> 103:Object
> 104:Object
> 105:Object
> 106:Object
> 107:Object
> 108:Object
> 109:Object
> 110:Object
> 111:Object
> 112:Object
> 113:Object
> 114:Object
> 115:Object
> 116:Object
> 117:Object
> 118:Object
> 119:Object
> 120:Object
> 121:Object
> 122:Object
> 123:Object
> 124:Object
> 125:Object
> 126:Object
> 127:Object
> 128:Object
> 129:Object
> 130:Object
> 131:Object
> 132:Object
> 133:Object
> 134:Object
> 135:Object
> 136:Object
> 137:Object
> 138:Object
> 139:Object
> 140:Object
> 141:Object
> id:1

This happens in the single stat AND in the graphs. 
Help?

**Comment by torkelo** [comment]
Did you check if the total does not match what zabbix is returning? (only see Object in your pasted query response not the values, expand and check the values).

You need to make sure you use sum aggregation in your zabbix query, and try to reduce the number of data points you query as the singlestat does not need them (unless you use sparkline option).
