### ISSUE TITLE
Alerting Issue: Individual condition results are false but conditionEvals is true

### ISSUE THREAD

**Issue by snc29590** [grafana/grafana#9318]
I am using  Grafana v4.3.2 (commit: ed4d170) on Ubuntu 14.04 with Graphite datasource.

I am setting up alerting on five conditions with OR operator. The alert is firing even when the conditions are not satisfied. When I hit "Test Rule", the test results show that each condition is evaludated to false, but the overall `conditionEvals` is set to true.

Below is a screenshot of the "Test Rule" results.

![image](https://user-images.githubusercontent.com/16399189/30667228-7fd85bb4-9e74-11e7-9b63-c04498923d2f.png)

Here, you can see that conditions [0,1,2,3,4] are all `Eval: false` but it shows `conditionEvals` as true and hence `firing: true`.

**Comment by torkelo** [comment]
that looks strange! Thanks for reporting this, will investigate!

**Comment by bergquist** [comment]
I cannot managed to reproduce this... yet. :)

@snc29590 just to make sure. If you refresh the page and click the test rule button without changing anything else. Do you still get the same behavior?

**Comment by snc29590** [comment]
@bergquist yep, it happens no matter how many times I refresh the page and hit Test Rule.

I even copied the Panel JSON to a different dashboard and tried the "Test Rule". Still get the same issue.

**Comment by snc29590** [comment]
I turned on debug logging hoping to find something useful. Unfortunately, there is nothing helpful there.

```t=2017-09-22T13:11:01+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:11:02+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-7.912 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:12:59+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:13:00+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-439.415 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:13:58+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:13:59+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-504.625 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:14:57+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:14:58+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-378.547 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:15:56+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:15:57+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=19.295 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:16:55+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:16:56+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-526.189 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:17:54+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:17:55+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-36.699 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:18:53+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:18:54+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-543.634 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:19:52+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:19:53+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-357.074 alertId=335 name=Kafka_Test_Alert firing=true
t=2017-09-22T13:20:51+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name=Kafka_Test_Alert id=335
t=2017-09-22T13:20:52+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-416.380 alertId=335 name=Kafka_Test_Alert firing=true```

**Comment by bergquist** [comment]
Cannot repro. Could you please try latest stable and try to reproduce this behavior?

**Comment by snc29590** [comment]
I was able to figure out the root cause of this issue. This happens when the `operator` type is set to `or` for the first condition in the alert conditions list. Below example will trigger an alert even if the individual conditions evaluate to false. 

```  "alert": {
    "conditions": [
      {
        "evaluator": {
          "params": [
            88
          ],
          "type": "gt"
        },
        "operator": {
          "type": "or"
        },
        "query": {
          "params": [
            "A",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "avg"
        },
        "type": "query"
      },
      {
        "type": "query",
        "query": {
          "params": [
            "A",
            "15m",
            "now"
          ]
        },
        "reducer": {
          "type": "avg",
          "params": []
        },
        "evaluator": {
          "type": "gt",
          "params": [
            66
          ]
        },
        "operator": {
          "type": "or"
        }
      }
    ],
    "executionErrorState": "alerting",
    "frequency": "60s",
    "handler": 1,
    "name": "Panel Title alert",
    "noDataState": "no_data",
    "notifications": []
  }```

The also happens only when there is one condition and the operator type is set to `or`. I was able to reproduce this in the most recent version of grafana as well.

**Comment by snc29590** [comment]
@bergquist , can this be considered a bug in grafana or is it "normal"?

**Comment by bergquist** [comment]
Yes, this is clearly a bug. Thank you for reporting this. I will fix it ASAP.

**Comment by bergquist** [comment]
This will be available in nightly builds within ~ 30min
We will also release 4.6.3 within a day or so to fix this.

**Comment by shivach52668** [comment]
Hi @bergquist , I am using grafana v5.1.4, i am also facing same issue. I configured my server alerts with 70% but the threshold is not breached as mentioned, still i am getting alerts. Could you please help me out. Why it is happening. is this a bug ?

**Comment by pparthenhs** [comment]
Hello @bergquist and @shivach52668,

I am using combine query on elk-source like the following:

![image](https://user-images.githubusercontent.com/9752042/51502117-44c12f80-1ddd-11e9-9483-0af0dde6ac54.png)

I also face the same issue:

![image](https://user-images.githubusercontent.com/9752042/51502288-15f78900-1dde-11e9-9ca5-01bbf2ecb00d.png)

I am at your disposal for any feather help.
PP

**Comment by pparthenhs** [comment]
@marefr thank your for your quick response !

I   change the in `interval: 1m` and the `query(A, 6m, now-1m)`: 
![image](https://user-images.githubusercontent.com/9752042/51537933-965ad000-1e58-11e9-87f7-264bb6a2855c.png)


And also I set the range as following
![image](https://user-images.githubusercontent.com/9752042/51537468-59420e00-1e57-11e9-8c19-2549fed20027.png)

But as you see then **value** on message are still null.

**Comment by marefr** [comment]
Dashboard range have actually nothing to do with the alert rule. You should change the dashboard range to from=now-6m and to=now-1m to get a feel for what the alert rule should evaluate, i.e. what the graph look like when visualized. Can you attach screenshot? 

Please change keep last state to no data and alerting respectively to remove any issues with those settings.

**Comment by pparthenhs** [comment]
I am confused, the graph has metric and data. Although, the alert has state 

 Screenshot :
![image](https://user-images.githubusercontent.com/9752042/51541549-c78bce00-1e61-11e9-960e-d72f22c81cad.png)

**Comment by marefr** [comment]
> As you see on time rage 6h until now, we have data
No, you don't have any current data. The series current value is empty even before zooming in

**Comment by marefr** [comment]
@pparthenhs please read https://community.grafana.com/t/why-is-my-graph-empty-when-i-zoom-in/24/2?u=mefraimsson

**Comment by pparthenhs** [comment]
@marefr thank you !! Now it actually working perfectly

**Comment by luigithor** [comment]
I'm using grafana alerts with clickhouse. 
I get this error "Execution Error: tsdb.HandleRequest() error Could not find executor for data source type: vertamedia-clickhouse-datasource".
I had a set up with an alert for temperature above 80° Celsius. The first time i have above the threshold i get “pending” status and then the “alerting” status and i receive the email.
but then when the temperature goes under 80° …75, 70,65…the status remain “alerting” and there is no way to get “ok” status.
I have to put in pause the alert rule and then start the rule again to have a new “pending” status and a new “alerting” status and so a new email for the new threshold event.
Any help about alerting for clickhouse?
