### ISSUE TITLE
[Feature request] HELO string configurable in SMTP client

### ISSUE THREAD

**Issue by thz** [grafana/grafana#9319]
**Scope:** 
* SMTP client functionality for sending out emails.
* In #7223 the HELO string was changed to the name of the instance.

**Situation:**
We use an SMTP-relay from a provider and we need to set HELO name to a domain we have with them. That domain is not the same as the hostname grafana is running on.

For that reason the InstanceName as HELO name does not work for us.

**Proposal:**
As initially proposed in #7223 : a config option for setting the HELO name.

Would a PR adding an option to override the HELO name have any chance for acceptance?

**Comment by bergquist** [comment]
@thz yes it would.
