### ISSUE TITLE
Timeseries panel: Lines rendering strangely when "disconnect values" set to "threshold"

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#93196]
### What happened?

Recently we've noticed that Timeseries lines have often (but not always) been rendering strangely when the "disconnect values" option has been set to "threshold." In our case, the threshold has usually been 2h. Here I've pointed with red arrows to a few of the many occurrences of this in the screenshot. The issues seems to go away if we zoom in far enough.

![Image](https://github.com/user-attachments/assets/75943087-9932-4b41-b12d-df3c74ffc739)

### What did you expect to happen?

Points that are separated by more than the threshold value in time should be completely disconnected. Points within the threshold or closer should be fully connected. There should be no partial connections.

### Did this work before?

Unsure. We haven't been using the "disconnect values" option for long.

### How do we reproduce it?

Use the panel definition given below.

### Is the bug inside a dashboard panel?

[debug-position filtered - latitude-2024-09-10 15_41_02.json.txt](https://github.com/user-attachments/files/16955174/debug-position.filtered.-.latitude-2024-09-10.15_41_02.json.txt)

### Environment (with versions)?

Grafana: v11.1.4 
OS: Windows 11
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

AWS Timestream

**Comment by leeoniya** [comment]
your data needs to be ordered by time ASC. you should do it in the query if you can, otherwise use a transformation.

https://docs.aws.amazon.com/timestream/latest/developerguide/sample-queries.basic-scenarios.html

![Image](https://github.com/user-attachments/assets/525f7479-4afc-4c84-b801-32011dd66d60)

**Comment by nabelekt** [comment]
@leeoniya, sorting time by ASC has definitely helped in most situations, but not every situation:
![Image](https://github.com/user-attachments/assets/6a3650c3-6855-48ea-bf9a-2544772e1e36)

[panel_snapshot.txt](https://github.com/user-attachments/files/17331201/panel_snapshot.txt)
