### ISSUE TITLE
[Feature Request] Add 'occurrences' to Grafana alerting

### ISSUE THREAD

**Issue by derng** [grafana/grafana#9323]
Hi,

We find Grafana alerting too sensitive for our needs.  We find that if our metrics pass a threshold even for a milli second, it'll throw an alert and create too much noise.

What I propose is a solution to control the sensitivity of the existing Grafana alerting feature.  We could give users the ability to control the 'occurrences' of the alert.  

For example, if user selects 'refresh' value 60 and 'occurrence' value 3, the alert will only trigger if the metric has passed the alerting threshold every 60 seconds 3 times. 

It's very similar to what Sensu offers:
https://sensuapp.org/docs/0.27/reference/plugins.html#sensu-plugin-definition-specification

Please let me know if you need any more information.

Kind Regards,
Tuan

**Comment by chrisjob1021** [comment]
+1

**Comment by surenragu** [comment]
+1

**Comment by dudusakharovich** [comment]
@torkelo - Are you planning to release this feature soon ?

**Comment by torkelo** [comment]
no, it has not been implemented yet (nor is there any PR submitted). It's not on the core teams current roadmap so not sure when or if this will get implemented. Not sure what the best way is to solve the root problem either :) All I know is that the root problem is something we want to address this year
