### ISSUE TITLE
DashboardScenes: Issue with going to panel edit through a link

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#93252]
If using a link that goes directly to a panel edit page, the field selector dropdowns are not populated with the fields from the queries. it works okay when going into panel edit from a dashboard, though.

http://localhost:3000/d/2I2uMSB7z/barchart-thresholds-and-mappings?orgId=1&scenes&from=now-6h&to=now&tab=queries&editPanel=6

![Image](https://github.com/user-attachments/assets/5f940a09-a87d-4adb-ae3d-a60627aeec18)

**Comment by torkelo** [comment]
issue with hook dependency list https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/panel-edit/PanelOptions.tsx#L50
