### ISSUE TITLE
Product Area: Short description of bug

### ISSUE THREAD

**Issue by elvissalvatierra** [grafana/grafana#93289]
### What happened?

Me muestra este error: ![Image](https://github.com/user-attachments/assets/646645da-b605-485e-8c02-6a1059d5db66)

### What did you expect to happen?

Mostra la información

### Did this work before?

Si

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by hairyhenderson** [comment]
Please re-open with more detail, in English please!
