### ISSUE TITLE
[Bug] Graph table legend sort null/no value differently

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9328]
Version: Grafana 4.5.2

When using grafana to display the legend on the right, along with the "current" value, click on "current" to sort the legend sorts the legend by its name and not the value in the "current" value.

Any other field (max/avg/min/total) works correctly - the table is sorted according to the value in that column.

**Comment by torkelo** [comment]
strange, unable to replicate. When I click on the legend value headers the order change. 

Do you get any error in the chrome dev console?

**Comment by torkelo** [comment]
Can you consistently replicate this?

**Comment by yellowpattern** [comment]
If you want me to respond, re-open the bug.

**Comment by torkelo** [comment]
of course sorry

**Comment by torkelo** [comment]
This is what it looks like for me 
![image](https://user-images.githubusercontent.com/10999/30731379-56cb9f02-9f6d-11e7-815c-f39ec2571d7b.png)

**Comment by yellowpattern** [comment]
Oh! Now I see the problem!  Null values in the list appear at the top when doing "sort in descending order".

This happens regardless of the "Hide Series" settings in the Legend display.

If a series has some elements that do not appear at every interval the it may be that the last interval has no current value for some serieses. Every other column (min/max/avg/total) is guaranteed to have a non-null number in it.

The sort puts the "no value" entry above the largest value rather than below the lowest value.

**Comment by torkelo** [comment]
This looks like it's fixed
