### ISSUE TITLE
[Feature Request] Add "name" heading to legend tables

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#9329]
Version: Grafana 4.5.2

When using a "table" (e.g to the right) of the graph in grafana to provide the legend, there is no heading for the column with all of the series names. This means the legend remains "sorted".

That is when the "X" axis is "Time".

When the "X" axis is "Series", it works correctly.

**Comment by torkelo** [comment]
the series sort order is determined by the query (and the sorting done by the backend TSDB)

**Comment by torkelo** [comment]
Sorry, a bit short reply. I cannot sort on name column, the sorting is entirely up the query
