### ISSUE TITLE
Grafana Not Starting in Mac OS

### ISSUE THREAD

**Issue by DeepakSahoo-Reflektion** [grafana/grafana#9330]
When i am trying to start grafana in my mac , i get the below error.
ailed to detect generated css or javascript files in static root (/usr/local/share/grafana/public), have you executed default grunt task? logger=server

I have npm and grunt installed in my system. 
Please, help

**Comment by torkelo** [comment]
How did you install it? did you clone it and tried to build it yourself? or use homebrew?

For building from source, please follow this guide 
http://docs.grafana.org/project/building_from_source/

**Comment by DeepakSahoo-Reflektion** [comment]
I installed via homebrew

**Comment by torkelo** [comment]
try 

``
brew services start grafana
```

**Comment by DeepakSahoo-Reflektion** [comment]
Yeah i started using the above command and it's not starting.
>brew services start grafana

**Comment by DeepakSahoo-Reflektion** [comment]
Any update on this?

**Comment by torkelo** [comment]
anything in the logs? 

http://docs.grafana.org/installation/mac/#logs

**Comment by torkelo** [comment]
what is the contents of your /usr/local/share/grafana/public ?

**Comment by wonderxboy** [comment]
I am experiencing the same problem. I followed the guide from here http://docs.grafana.org/installation/mac/

but the grafana logs shows 
```
t=2017-11-11T22:52:08+0800 lvl=eror msg="Failed to detect generated css or javascript files in static root (/usr/local/opt/grafana/share/grafana/public), have you executed default grunt task?" logger=server
```

**Comment by cjen07** [comment]
I have the same problem with the same log. Anyone solved this issue?
