### ISSUE TITLE
[Bug] tooltip is empty on heatmap panel with time series bucket

### ISSUE THREAD

**Issue by morokosi** [grafana/grafana#9332]
- What Grafana version are you using?
  - 4.5.1
- What datasource are you using?
  - elasticsearch
- What OS are you running grafana on?
  - official docker container
- What did you do?
  - Move cursor to a heatmap card
- What was the expected result?
  - Tooltip is shown with its content
- What happened instead?
  - Tooltip is empty
  - console error: `TypeError: bucket.bounds is undefined`

It seems the change  https://github.com/grafana/grafana/commit/cb8ecb2d5faec9c1ac8b3f4d8dcc466c65da3fa3#diff-3c623908bd3b58da4e0e63acf4e45cbfL168 does not consider time series bucket, which does not have `buckets.bounds`.

**Comment by torkelo** [comment]
what are your heatmap options? And is your ES query a normal time series query?

**Comment by morokosi** [comment]
heatmap option is `Time series buckets` and ES query is pre-bucketed like following:

![image](https://user-images.githubusercontent.com/676622/30735647-b7d5e4f4-9fba-11e7-9a0e-a8e6d0d89dcd.png)

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/commit/3641e8523391ff6ff01330bc93ab549b7d7bd7e8 adds two example scenarios for the Grafana test datasource. We should use these as mock data when we develop panels so we use the same data.

**Comment by hippostar** [comment]
Can confirm the tooltip works fine with the initial options but breaks after changing the option 
"Axes"->"Data format" to "Time series buckets"

**Comment by hippostar** [comment]
Ok after debugging it, there seems to be two problems in heatmap_tooltip.ts.

First, the undefined "bounds" was is being worked around by the "OR" I suppose. However you still have to handle the "undefined" so the browser is happy.

Second, the buckets are in a collection, not an array, so at heatmap_tooltip.ts line 88 the find()'s second parameter bucketIndes is a string which is being strictly compared to yBucketIndex which is a number. Therefore it will never "find" any match.

**Comment by thattolleyguy** [comment]
I am still seeing this issue show up. I'm not sure what to look at to provide more information
