### ISSUE TITLE
[Bug] Auth to grafana throught proxy not working if there is no user at LDAP

### ISSUE THREAD

**Issue by pziental** [grafana/grafana#9333]
Hi, 
i've find problem at Grafana 4.5.1 with auth methods.
We are authenticate our user by the two ways:
- proxy
- ldap

At Grafana we create users with the same login like in the LDAP and external system where proxy auth is comming from.
If we are login to the Grafana through external system and the login is also in the LDAP log in is success 
but if the login isn't at LDAP log in is unavailable. Server side error :( .... 

At Grafana log:
t=2017-09-22T11:55:24+0200 lvl=eror msg="Failed searching for user in ldap" logger=ldap error="Invalid Username or Password"
t=2017-09-22T11:55:24+0200 lvl=eror msg="Unable to authenticate user" logger=context error="Invalid Username or Password"
t=2017-09-22T11:55:24+0200 lvl=eror msg="Request Completed" logger=context userId=407 orgId=36 uname=XXXXXX method=GET path=/ status=500 remote_addr=126.148.121.150 time_ms=17 size=709 referer=

How it is a possible that LDAP auth is rising when auth.proxy has already authorized the user.

- What Grafana version are you using?
4.5.1
- What datasource are you using?
- What OS are you running grafana on?
CentOS Linux release 7.4.1708 (Core)
- What did you do?
i've set to enabled=false [auth.ldap] section
- What was the expected result?
logging to grafana by the LDAP and proxy without checking user LDAP if logging through proxy
- What happened instead?
Server side error :( - Unable to authenticate user
- If related to metric query / data viz:

**Comment by torkelo** [comment]
if you have both options enabled the auth proxy user needs to exist in ldap as well.
