### ISSUE TITLE
Alerting: changing evaluation group for alert rule is broken (v11.1+) - changes groups, not alert rules

### ISSUE THREAD

**Issue by k-meister** [grafana/grafana#93337]
### What happened?

Hello!
One of common scenarios gone wrong since 11.1:
- you have an Alert Rule with evaluation group "5m", interval "5m"
- you have another group, say "1m", interval "1m"
- you want to assign a rule a new group, 1m instead of 5m

When you pick the "1m" group and hit Save rule, "1m" group changes its interval to 5m.

The group is modified silently, it's hard to notice for a user, and modification can cause a lot of alerts run with undesired interval.
Also, I see **no way to controllably change evaluation interval of an existing rule**, except to recreate it, assigning the new group.

Restoring parameters of inadvertently-modified groups is also problematic [#90155](https://github.com/grafana/grafana/issues/90155).

We rolled back to 11.0 release now, and in a process of restoring misedited groups.
Consider this bug a blocker to go to 11.1+

### What did you expect to happen?

Choosing a new group in Alert rule & Save rule:
- SHOULD change this particular Alert rule's evaluation group
- SHOULD NOT modify chosen evaluation group (or any other group)

### Did this work before?

Yes, prior to 11.1

### How do we reproduce it?

- you have an Alert Rule with evaluation group "5m", interval "5m"
- you have another group, say "1m", interval "1m"
- pick the "1m" group for a Rule. Wrong: you still see "All rules in this group evaluated every 5m", should change to 1m
- hit "Save rule". Refresh the page

"1m" group is now running every 5m

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: 11.1+
OS: Any
Browser: Any

### Grafana platform?

I don't know

**Comment by tonypowa** [comment]
Hi @k-meister 

I could reproduce the issue as described

Repro notes for reviewer:

After editing an existing alert rule , created a new evaluation group, and saved and exited the rule, I could see that Grafana silently failed to save the new evaluation interval .  See the interval (in blue) is always 1m, regardless I chose 5m and 10m for 2 of the 3 alert rules.

![Image](https://github.com/user-attachments/assets/be7caeb1-284a-4c1a-aa1d-3983406ec28a)

**Comment by k-meister** [comment]
@tomratcliffe Hello!
Thank you so much for a PR!

I just wanted to make sure your fix really applies for my issue.
As far as I can see, fix addresses new Eval Group creation only - the thing that @tonypowa pointed out.
But the issue is about editing Alert Rule without creation of new Eval Groups.
Your PR should fix that too, am I correct?

**Comment by tomratcliffe** [comment]
Hi @k-meister!

I'm no longer able to recreate the _exact_ issue you describe in your original comment. I was able to previously, but now it seems to not be "working" 🤷 

I've tried moving rules around between 3 folders that have different evaluation intervals, and they aren't being overwritten. Do you have any other specific steps to reproduce it?

The PR will definitely address the other issue where the newly created eval group wasn't setting the interval correctly. For now, I'll remove the fact that the PR fixes this issue, until I can 100% confirm the logic

**Comment by k-meister** [comment]
@tomratcliffe thank you for reaching out,

Yes, on 11.2.1 couldn't reproduce the initial problem too, changing rule group works as expected 👍 
Issues #90155, #93419 could not repro as well, all seems to work fine

**Comment by tomratcliffe** [comment]
🎉 That's great!

Given that https://github.com/grafana/grafana/pull/93821 is now merged as well, is there anything else outstanding that you believe if broken with regards to evaluation groups/intervals, on the latest code?

**Comment by k-meister** [comment]
@tomratcliffe,
I believe everything works fine, though I could not thoroughly test #90155 on provisioned rules.
Regarding my issues, all seem to be fixed 👍

**Comment by k-meister** [comment]
@tomratcliffe , @tonypowa 
Hi guys!
Could you please check if this is actual, once more?

Try this:
- go to alert rule edit page, by pasting direct link in browser address bar
- OR navigate via some link and make sure to refresh the page afterwards
- Then try to reproduce as described

On our version (11.2.2) this seems to consistently reproduce the bug.

Meanwhile, if you come from "Alert rules" page, everything works fine.

The problem is, people mostly come from messengers where they received actual alerts, and this scenario is affected.

Please let me know if I should create a new issue instead 🙏
