### ISSUE TITLE
Template variables are not supported in alert queries

### ISSUE THREAD

**Issue by zhanglp92** [grafana/grafana#9334]
我想给使用 Template 的 panel 添加 alert ，但是会出现 “Template variables are not supported in alert queries” 这个问题，有什么办法能解决吗 ？

**Comment by bergquist** [comment]
Template variables are not supported in alerting.
Template variables should be used for discovery and drill down. Not controlling alert rules 

its also a dupe of https://github.com/grafana/grafana/issues/6557

**Comment by zhanglp92** [comment]
3Q

**Comment by zhanglp92** [comment]
![image](https://user-images.githubusercontent.com/6869148/30748371-b69812ba-9fe2-11e7-9fa6-4f0fd0c0a2b6.png)
![image](https://user-images.githubusercontent.com/6869148/30748429-def271a6-9fe2-11e7-9889-8973af37bb2d.png)

I want monitor this data ，What should I do ?

**Comment by torkelo** [comment]
Remove template variables, replace with wildcard or regex pattern

**Comment by tiagoreip** [comment]
where do i remove those template variables ?

**Comment by DimitriyKh** [comment]
It would be grate to add templates support in alerts. Otherwise the feature looks useless a bit.

**Comment by PrestonR** [comment]
I support this. I have a bunch of different hosts that can use the same graphs. But I can't use alerts because the host is template variable.

This forces me to needlessly create a graph for each host, and I have hundreds of host, all to be able to use alerts.

**Comment by Xaelias** [comment]
How about adding a way to provide the values of said variables?

**Comment by sanchomuzax** [comment]
I updated the Grafana to 5.0 and after I can't use the alerting system. Its works wit 4.6, why can't use on 5.0?
I don't use template variable on alerted graph. 

> Template variables are not supported in alert queries

**Comment by pstatho** [comment]
Agreed with @tiagoreip and @DimitriyKh , the query has a template variable to make the dashboards and it defeats the purpose to not be able to reuse the query for alerting.

@torkelo can you explain how we should be doing this with many graphs and many dashboards?

**Comment by kaybinwong** [comment]
It would be grate to add templates support in alerts. Otherwise the feature looks useless a bit.
+1

**Comment by maklaut** [comment]
+1

**Comment by Freemahn** [comment]
+1

**Comment by yasongxu** [comment]
+1 will  support in new version ?

**Comment by wheelo** [comment]
+1

**Comment by rashidmahmood** [comment]
+1

**Comment by fanjun1980** [comment]
+1

**Comment by bcaparoon** [comment]
+1

**Comment by shinhwagk** [comment]
+1

**Comment by tushar00jain** [comment]
+1

**Comment by lebd** [comment]
+1

**Comment by lephisto** [comment]
+1

**Comment by wansuiye** [comment]
+1

**Comment by rutwickjain** [comment]
+1

**Comment by MikeL9286** [comment]
+1

**Comment by singOfBird** [comment]
+1

**Comment by izern** [comment]
+1

**Comment by markfengyunzhou** [comment]
+1

**Comment by 511er** [comment]
+1

**Comment by phneak** [comment]
+5

**Comment by sevaTechoPark** [comment]
+1

**Comment by deanmax** [comment]
+1

**Comment by JokerQyou** [comment]
Why is this issue not locked as spam like #6557 ? These +1 s are getting us nowhere closer to the goal.

**Comment by phneak** [comment]
Why do people keep asking for this and it keeps getting shut down?

**Comment by JokerQyou** [comment]
It's not shut down. This issue was closed because it is a duplicate of #6557 which kindly suggest adding variable support as a feature request. That issue is still open. It's only locked because people can't stop commenting meaningless +1 s to spam everyone in the same thread.

I'd like to quote [one of the comments](https://github.com/grafana/grafana/issues/6557#issuecomment-379874026) from that issue, in case you don't understand why +1 messages are not welcomed:

> Please stop +1'ing this issue. It generates unnecessary spam emails. The ability to add a reaction to a github issue comment has existed for a while now, and over 429 people have figured out how to like the initial comment instead of spamming everybody who is subscribed.

**Comment by hunanjsd** [comment]
+1

**Comment by gopalk20** [comment]
Is this feature is available in 7.0 version

**Comment by chanyshev** [comment]
Version 8.0.* has already been released and the problem is still not solved =(

**Comment by Nastradamus** [comment]
up, it's very annoying

**Comment by zhangbincheng1997** [comment]
2022 is also not supported.:sob:

**Comment by linuxwind** [comment]
2023 is also not supported.😭
