### ISSUE TITLE
[Bug] Not correct data zooming

### ISSUE THREAD

**Issue by Anna-Fedorova** [grafana/grafana#9335]
- What Grafana version are you using? - grafana:4.5.2
- What datasource are you using? - InfluxDB
- What OS are you running grafana on? - Ubuntu 16.04.3
- What did you do? - I have two docker-containers: one with InfluxDB and another with Grafana. I tune Grafana to datasource: localhost:8086 and create dashboard. I checked that data are located in InfluxDB and I have two days of them. 
However, what I see in Grafana:

**For 24 hours:**
![24 hours](https://user-images.githubusercontent.com/17598530/30743364-ec46d514-9fa5-11e7-9c37-3185ca93c429.png)
**For 6 hours:**
![6 hours](https://user-images.githubusercontent.com/17598530/30743370-f9142f3a-9fa5-11e7-98b8-c444255fbf81.png)
**For 15 minutes:**
![15 minutes](https://user-images.githubusercontent.com/17598530/30743381-0042427e-9fa6-11e7-9e88-1ecb7bc0dbb4.png)

It means that I have data for all 24 hours but when I tried to zoom them they are lost nowhere.
- What was the expected result? - To see zooming data
- What happened instead? - Data are not zoomed correctly

**Comment by torkelo** [comment]
Try setting min interval in data source options (or in metrics panel) to 10s (or 1m), should be the rate at which you write data

**Comment by Anna-Fedorova** [comment]
The attempt to set this parameter to 1s or 100s doesn't provide successful result. Data are really flown every 1s. Why are there gaps when I zoom data?

**Comment by torkelo** [comment]
Because InfluxDB is returning no data or nulls between every value, try enable point in graph display option, any point shown in graph? Try query inspector in metrics tab, will show you raw response from InfluxDB.

Try setting fill(none), in query
