### ISSUE TITLE
[Bug] Jibberish in plugin readme

### ISSUE THREAD

**Issue by apaulsson** [grafana/grafana#9344]
Please include this information:
- What Grafana version are you using?
4.5.2
- What datasource are you using?
Not related to data source
- What OS are you running grafana on?
Debian 9.1 "Jessie", Firefox 55.0.3 on Windows 10 as browser.
- What did you do?
Installed a couple of plugins according to instructions from grafana.com
- What was the expected result?
Working plugin and readable info about the plugin
- What happened instead?
Working plugin, but README is just jibberish. Please see the attached screen shot.
![2017-09-25_11-09-45](https://user-images.githubusercontent.com/29432928/30800998-1a0fb64e-a1e2-11e7-871d-c3ab247c7b96.png)

**Comment by torkelo** [comment]
Unable to replicate, 
![image](https://user-images.githubusercontent.com/10999/30954523-c3896b70-a430-11e7-9055-23e1aff21f5c.png)

Not sure what could cause this, do you have some proxy infront of Grafana?

**Comment by apaulsson** [comment]
Hi,

No proxy in front at all, Grafana is listening on port 80, but that should not be the reason to why it's jibberish.

Forgot to mention that this is the case for _all_ plugins, both those included and those downloaded separately.

**Comment by torkelo** [comment]
very strange, if you open developer tools in chrome or firefox, you should see grafana fetching a file named readme.md, what does this contain according to the developer tools (network tab)

**Comment by apaulsson** [comment]
![2017-09-28_10-10-37](https://user-images.githubusercontent.com/29432928/30955838-5b60f342-a435-11e7-9067-5ca2f509efde.png)

Haven't used the developer tools, but I suppose this is the information you want?

**Comment by apaulsson** [comment]
This is how the file look like on the file system:
`root@drsurvgraf01:/usr/share/grafana/public/app/plugins/panel/graph# cat README.md
# Graph Panel -  Native Plugin

The Graph is the main graph panel and is **included** with Grafana. It provides a very rich set of graphing options.

Read more about it here:

[http://docs.grafana.org/reference/graph/](http://docs.grafana.org/reference/graph/)root@drsurvgraf01:/usr/share/grafana/public/app/plugins/panel/graph#
`

**Comment by apaulsson** [comment]
Ok, this seems to be related to Firefox.. In Microsoft Edge, it works just fine:
![2017-09-28_10-26-23](https://user-images.githubusercontent.com/29432928/30956437-9f0a4ca4-a437-11e7-9c56-276c44f7df2c.png)
![2017-09-28_10-27-43](https://user-images.githubusercontent.com/29432928/30956458-b000d7d0-a437-11e7-92c5-f04954caf392.png)

**Comment by daniellee** [comment]
Something to do with gzip and Firefox? If you turn off gzip does it look correct on Firefox?

**Comment by daniellee** [comment]
Yes, it is something to do with gzipping. Duplicate issue: #5952

**Comment by bergquist** [comment]
https://stackoverflow.com/questions/23600229/what-content-type-header-to-use-when-serving-gzipped-files

**Comment by daniellee** [comment]
Fixed in master and will be included in the next Grafana release. The gzip code tries to automatically figure out the content type and failed for the plugin readmes.
