### ISSUE TITLE
[Feat Req] Add new ratio unit for values 0-1

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#9345]
Graph -> Axes -> Left/Right Y -> Unit -> none offers

* `percent (0-100)`
* `percent (0.0-1.0)`

It would be better to name the second one `ratio (0.0-1.0)` or `ratio / percent (0.0-1.0)`. Alternatively, keep the `percent (0.0-1.0)` and introduce a `ratio (0.0-1.0)`

**Comment by torkelo** [comment]
Not sure why. 

Both are displayed as percent (0 - 100%), the two options differ only in how the source value represents the percentage.

**Comment by RichiH** [comment]
Ratio is arguably more correct.

But I get the point of wanting to say "this ratio is a percentage" and
have the legend say "100 %", etc.

Thus, I am leaning towards having another option `ratio (0.0-1.0)`
which then shows 0/0, 1/4, 2/4, 3/4, 4/4 (or whatever) as legend for
the axis.

**Comment by torkelo** [comment]
But that is a different (new) unit that shows values between 0-1 in a different way?

**Comment by RichiH** [comment]
Initially, I didn't mean it that way, but yes, now I think this would be best.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
