### ISSUE TITLE
Auth user on load automatically

### ISSUE THREAD

**Issue by mre30** [grafana/grafana#9346]
Hi,

I am trying to authenticate user automatically on page load to access the iframe which loads graphs. 
For this i am trying to use ?curl http://admin:admin@localhost:3000/api/org, instead of admin:admin i am putting user and pass of user (not admin) and instead of localhost real address, but all the time i am getting: {"message":"Not found"}

p.s will ?curl http://admin:admin@localhost:3000/api/org automatically auth user and access all the iframes?

Thanks!

**Comment by torkelo** [comment]
strange, I get a json response with the org info in that api call.

not sure you can use basic auth like this in iframe urls, maybe you want this feature:
https://github.com/grafana/grafana/issues/3752

**Comment by mre30** [comment]
Thanks for answer.
In iframe i mean that I am just trying to achieve authentication of user, does not matter - based on cookie or api, just need same result like in case normal authentication from login form.

**Comment by nbayramberdiyev** [comment]
Here is my workaround using Grafana's Generic OAuth Authentication and PHP: https://github.com/nbayramberdiyev/grafana-generic-oauth

Hope this will help you.

**Comment by kaoushtuv** [comment]
@nbayramberdiyev Good work. But your workaround cannot be used for a dynamic userbase. Please post some workaround to that. Thanks
