### ISSUE TITLE
prometheus

### ISSUE THREAD

**Issue by Mohiniambalalpatil** [grafana/grafana#93470]
### Background

prometheus

### Use case

prometheus

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi @Mohiniambalalpatil - Grafana ships with a built in data source for [prometheus](https://grafana.com/docs/grafana/latest/datasources/prometheus/).
