### ISSUE TITLE
Issues when using series in another serie

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#935]
Here is a sample:

A: hosts.*.cpu-0.*    => display a lot of curves => OK
B: mostDeviant(5, #A) => Display the 5 most deviant => OK
C: aliasByNode(#B, 2) => No data points

There is a lot of similar cases 
ex: 
- using highestAverage for B: No data points
- using sortByName(#B) for C: will give an error
- using limit(#B, 2) for C: No data points

Maybe I missed something...

**Comment by torkelo** [comment]
Fixed in https://github.com/grafana/grafana/commit/d3c37bda718bc577ad093cfd72faf356b9422653

**Comment by nemenemsrouge** [comment]
awesome!
thx!
