### ISSUE TITLE
[Bug] storage public_url mixes up query parameters

### ISSUE THREAD

**Issue by vguna** [grafana/grafana#9351]
Please include this information:
- What Grafana version are you using?
4.5.2
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
official grafana docker image
- What did you do?
Setup external webdav storage to allow image upload. Created alert. Image gets uploaded. `public_url` gets mangled instead of appending the filename as advertised.
- What was the expected result?
Simply appending the image filename to the `public_url`
- What happened instead?
The query parameters are cut off from the `public_url`, then the filename is appended, afterwards the query parameters are appended.

I'm using owncloud 10 with a public shared folder, which can be accessed like this `index.php/s/DQGaG7zYra1x7NA/download?path=/&files=myimage.png`

Configuring `public_url = index.php/s/DQGaG7zYra1x7NA/download?path=/&files=` results in `index.php/s/DQGaG7zYra1x7NA/download/grafanaimage.png?path=/&files=` which doesn't work.

**Comment by torkelo** [comment]
Must have configured the options wrong, or your use case is not supported. 

url + filename will be used to PUT image. 

public url + filename will be used for download.

**Comment by vguna** [comment]
? That's it?

The options _are_ properly configured. I know that the urls are different for PUT and putting them into slack - as the documentation already points out.

I think the problem lies here:

https://github.com/grafana/grafana/blob/87308fd97fc63bbcc2b5fe64a9f56f5016f19e77/pkg/components/imguploader/webdavuploader.go#L62

Where only the path part of the URI is replaced with the joined path+filename. That results in that the _query params will be kept as is_. What for owncloud webdav doesn't work out - since in the query params the filename has to be put - not in the path.

The documentation states that the filename will be simply _appended_ to the specified `public_url` - which isn't happening. Instead only the _path_ part of the URI is changed - so not a real append.

So either the documentation is wrong or the code. Are there any plans to change that or to provide an additional option `append=true` or something where one can force a _real_ append?

**Comment by torkelo** [comment]
sorry, the docs is a bit unclear in this case your right. 

> Are there any plans to change that or to provide an additional option append=true or something where one can force a real append?

Maybe if there is demand & PRs

**Comment by huegelc** [comment]
This fix doesn't work with seafile. Seafile generates a URL like this:

`https://example.com/g/1cb7ca2fc4df4af491a4/files/?p=/0AFLmgBN0oEDfwqjeXut.png`

**Comment by huegelc** [comment]
This fix doesn't work for seafile. My public_url looks like this:

`https://example.com/d/1cb7ca2fc4df4af491a4/files/?p=`

grafana renders the url like this which obviously doesn't work:

`https://example.com/d/1cb7ca2fc4df4af491a4/files/Ag5VVk3n4zW5n3YzcPmu.png?p=/`
