### ISSUE TITLE
Add readable SiteWise Edge Gateway name to CloudWatch Dimension key

### ISSUE THREAD

**Issue by ceventyn** [grafana/grafana#93521]
**Why is this needed**:

Today when using variables in Grafana to select an AWS IoT SiteWise Edge Gateway you get a dropdown menu of the GatewayIds which are not great when trying to select a Gateway as nobody remembers the Ids of the several Gateways they have:

![Image](https://github.com/user-attachments/assets/d184ff48-930c-4339-83b1-039b40b327d3)

**What would you like to be added**:

Adding GatewayName as a Dimension key where you get the actual SiteWise Edge Gateway name in the dropdown selection.
Or having the option to somehow give the UUID a label / name.

**Who is this feature for?**

Factory users for e.g., maintenance department, local IT support.

**Comment by iwysiu** [comment]
Hi @ceventyn ! Thanks for the feature request, I see why this would be annoying. Unfortunately AWS only supports using GatewayId as a dimension key ([aws docs](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/monitor-cloudwatch-metrics.html)), and does not support filtering by Gateway name.  Getting the names from the Gateway ids would require us to write special handling for GatewayId dimensions with additional AWS permissions requirements, and we're not currently planning to support it.
