### ISSUE TITLE
[Bug] cannot save changes on Repeating Panel when "All" is selected for Variable

### ISSUE THREAD

**Issue by y-code** [grafana/grafana#9354]
Grafana version: v4.4.3
Datasource: InfluxDB

Steps I did:
1. Create a dashboard.
2. Add a variable with "Include All option" from Templating.
3. Select a value other than "All" for the variable.
4. Add a row with a Singlestat Panel.
5. Edit the panel where Repeat Panel is set to the variable.
6. Save the dashboard.
7. Select "All" for the variable.
8. Go to Panel Edit Page from one of the repeating panels.
9. Change something, and save the dashboard.
10. Go back to the dashboard.
11. Reload on Browser.

Expected Results:
Step 10: The changes made in Step 9 should be applied to all the repeating panel.
Step 11: The panel should be the one after the changes in Step 9.

Actual Results:
Step 10: The change was only applied to the panel from which I opened Panel Edit Page.
Step 11: The panel lost the changes in Step 9 and showed the one before the change.

**Comment by torkelo** [comment]
you cannot edit "repeated panels" and have those edits persist, only changes to the first "source" panel will be persisted (and copied over to the other panels when you change the variable or reload the dashboard)

**Comment by y-code** [comment]
Thank you, @torkelo. I see, that circumstance makes sense.

Then, "Edit" should not appear in the panel's context menu for non-"source" panel, should it.
Or, it makes sense for me if the menu item "Edit" should open Panel Edit Page for the first "source" panel.

My fellow was thinking he'd fixed a query in a dashboard, but it was actually not saved because of it, and accordingly, it was almost causing us not to catch a fault in our release process.

I hope it would get more intuitive. Users cannot see such internal circumstance. If you could take this into account, that would be much appreciated.

**Comment by torkelo** [comment]
agree, the panel repeat system can be much improved
