### ISSUE TITLE
Datasource Plugins: Cannot import from `@grafana/sql`

### ISSUE THREAD

**Issue by jrgns** [grafana/grafana#93557]
**Why is this needed**:

Various data sources, like Postgres and MySQL, has a query builder and a SQL editor. This all sits in the `@grafana/sql` package bundled with Grafana. Unlike `@grafana/data`, though, this pacakge is marked as [private](https://github.com/grafana/grafana/blob/main/packages/grafana-sql/package.json#L4) and cannot be imported into third party data sources:
![Image](https://github.com/user-attachments/assets/478ba7ad-99d5-4b4e-bf7f-1869308a8267)

Exposing this to third party datasource devs will allow them to use a standarized way of exposing query editors / builders to Grafana users.

Also see https://github.com/grafana/grafana/issues/90565 which asks for a generic way to switch between the editor and builder.

**What would you like to be added**:

Make '@grafana/sql` public.

**Who is this feature for?**

Third party datasource plugin developers.

**Comment by academo** [comment]
Hi @jrgns 

We already offer a public package `@grafana/ui` which offers a query editor that fully supports SQL. The component is `CodeEditor` which is on its own a small wrapper around the [monaco editor](https://microsoft.github.io/monaco-editor/)

Here's an example of how to use it

```
 <CodeEditor
        aria-label="SQL"
        language="sql"
        value={query.rawSql || ''}
        onSave={onSqlChange}
        onBlur={(text) => onChange({ ...query, rawSql: text })}
      />
```
