### ISSUE TITLE
Convert timestamp to local time

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#9356]
I am using Grafana with a MySQL data source on Linux Mint. The timestamp column of one of the tables with data I want to visualize contains time stamps in UTC. I’d like that to be converted to the local time of the viewer. Is there a way of doing that?

I could do the conversion in the MySQL query by using the `CONVERT_TZ()` function - but it requires the time zone to convert to and I don’t know how to get from Grafana the time zone of the browser. Is there a macro for that? I see that a few new time-related macros have been added to the latest version (4.5.2), but from their description I still can't figure out how to perform what I want.

In the dashboard settings I’ve set the time zone to be “Local browser time” but this doesn’t help, because I don’t know how to get what the offset is. (Well, it does help in the sense that the displayed time is even more wrong if I select the “UTC” setting there.)

I have tried asking on the forum but got no answer whatsoever. Is what I want possible or not? If not, please consider this a feature request.

**Comment by torkelo** [comment]
Strange, there should be nothing stopping you showing UTC times. 

make sure grafana server is running on UTC server and then MySQL read the date as UTC. Or convert the date field to epoch seconds and have grafana show it as UTC

**Comment by bontchev** [comment]
Sorry, you misunderstand. The time zone of the server and of MySQL has nothing to do with this. The timestamps are _already_ stored as UTC timestamps in the database.

My problem is that I don't want them displayed as UTC - I want them displayed converted into the local time zone of the user who is viewing the graph. Thus, my question is how to convert the (stored) timestamps into local time - not how to display them as UTC.

Since different viewers of the Grafana panel will (presumably) reside in different time zones, I cannot convert the stored UTC timestamps into a particular, fixed time zone. I need to somehow get the time zone of the viewer.

Is this possible, and if yes - how?

Right now, my local time zone is UTC+3. (Geographically, it is GMT+2, but there is one additional hour, because daylight savings time is currently in effect.) I have a linear graph panel that is filled by the following MySQL request:

```
    SELECT
  (UNIX_TIMESTAMP(timestamp) DIV 3600) * 3600 AS time_sec,
  'Logins' AS metric,
  COUNT(*) AS value
FROM auth
WHERE
  $__timeFilter(timestamp)
GROUP BY HOUR(timestamp)
ORDER BY timestamp ASC
```

This results in a graph which is offset by 3 hours before my local time. For instance, if my local time is 16:05, the last dot on the graph will be at the 13:00 mark on the X-axis, instead of on the 16:00 mark.

Also, please do not close an opened issue until you have made sure that it has reached a satisfactory resolution. "It ought to work" is _not_ a resolution. I did not open it in order to waste your time (or mine); I opened it because I have a problem that I do not know how to solve. It is perfectly possible that I am missing something that seems obvious to you, but please wait until you've made sure that I have grasped it before closing the issue. Thank you.

**Comment by torkelo** [comment]
that is strange, that query works for me and gives me a local timed graph,  (so changes depending on my browser time zone). Is your dashboard timezone set to local ?

**Comment by bontchev** [comment]
Yes, the dashboard timezone is set to local. If I set it to the other setting, the results are even more wrong. That's one of the first things I tried.

I can't post pictures right now, because the site is down (electricity is off for 5 hours; some sort of scheduled maintenance) but I tried to view the site from different countries by using the Tor browser and changing circuits until the country of the exit node changed. While I was getting different markings on the X-axis (suggesting that Grafana is indeed trying to convert to local time and not showing UTC), I got the impression that they were all wrong for the corresponding country.

Once the power comes back, I'll do a detailed test from several countries and will post the results.

I wonder - could the problem be that the timestamps are not stored in the database as UTC but as local time? They are stored by a third-party program; not by my software. That program can produce JSON logs too, and the timestamps are _definitely_ in UTC there; I'd have to dig into it and figure out exactly how it saves them in the MySQL database...

**Comment by torkelo** [comment]
Yes, the issue could be that the timestamps are not stored as UTC, but your query reads them as UTC epochs

**Comment by bontchev** [comment]
Power is back on but my experiment with the Tor browser didn't yield very useful results. Apparently, the browser sets the time zone to UTC no matter which country the exit node resides in, so I am getting one and the same X-axis markings from everywhere. However, they are _still_ wrong for a viewer residing in the GMT0 time zone - and they are off by the same 3 hours.

I am inclined to believe now that the timestamps in the database are wrong. MySQL stores `timestamp` data always as UTC in the database. The program sends UTC time stamps there. I guess this results in a double conversion - with the MySQL server converting to UTC time stamps that are _already_ in UTC and subtracting 3 hours from them unnecessarily. I'll talk to the developer of the program about setting the MySQL session time zone to UTC instead of using the server time zone.

Thanks for your help; I guess this isn't a problem caused by Grafana. Too bad that I can't correct it with Grafana, since the `$__timeFilter()` macro cannot work with arguments that contain parentheses, so I can't call `CONVERT_TZ()` on its argument...

**Comment by GuilhermeHideki** [comment]
I had this problem too. The server was configured with UTC timezone `@@system_time_zone` and the session was local timezone (`@@session.time_zone` in UTC-2, same as the grafana users), when used with the "local browser time", they would "cancel out" and show UTC
