### ISSUE TITLE
Add INS(Israeli New Shekel) currency.

### ISSUE THREAD

**Issue by koss110** [grafana/grafana#93566]
**Why is this needed**:

Israeli New Shekel currency missing.

**What would you like to be added**:

Israeli New Shekel currency.

**Who is this feature for?**

Financial data visualisations.

**Comment by koss110** [comment]
@koss110

**Comment by koss110** [comment]
Files to modify:

-  grafana/grafana/packages/grafana-data/src/valueFormats/categories.ts 
under line 121 ValueFormatCategory.Currency.formats
`
      { name: 'Shekel (₪)', id: 'currencyINS', fn: currency('₪') },
`
- grafana/grafana/devenv/dev-dashboards/panel-polystat/polystat_test.json 
- grafana/grafana/devenv/dev-dashboards-without-uid/panel_tests_polystat.json
under `panels.unitFormats.submenu`
`

            {
              "text": "Shekel (₪)",
              "value": "currencyINS"
            },
`

**Comment by tolzhabayev** [comment]
I think this is already resolved via https://github.com/grafana/grafana/pull/93390

**Comment by tolzhabayev** [comment]
Closing as solved by the PR above. Feel free to reopen if something is missing.

**Comment by koss110** [comment]
Seems you're right 
Last time I checked I wasn't

**Comment by masterwishx** [comment]
> Files to modify:
> 
> * grafana/grafana/packages/grafana-data/src/valueFormats/categories.ts
>   under line 121, `ValueFormatCategory.Currency.formats`
>   `{ name: 'Israeli New Shekel (₪)', id: 'currencyINS', fn: currency('₪') },`
> * grafana/grafana/devenv/dev-dashboards/panel-polystat/polystat_test.json
> * grafana/grafana/devenv/dev-dashboards-without-uid/panel_tests_polystat.json
>   under `panels.unitFormats.submenu`
>   ```
>         {
>           "text": "Israeli New Shekel (₪)",
>           "value": "currencyINS"
>         },
>   ```

Sorry but its `ILS` not `INS` https://en.wikipedia.org/wiki/Israeli_new_shekel

![Image](https://github.com/user-attachments/assets/9b81c87a-e0bb-4f52-bd64-4b81166950a6)

![Image](https://github.com/user-attachments/assets/9f9cafaf-3345-4f7f-9211-934fd28dd9cb)

**Comment by masterwishx** [comment]
![Image](https://github.com/user-attachments/assets/e628fa9a-b2cc-4d9f-b91d-2bfe5190cd04)

**Comment by masterwishx** [comment]
NIS also fine
