### ISSUE TITLE
[Feature request] Add "On template variable change" refresh option for template variables

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#9357]
Would be useful to be able to update template variables/dropdowns when another fields change.

Example (using CloudWatch):

![image](https://user-images.githubusercontent.com/94327/30908106-48d74a9c-a385-11e7-8aee-ca3fc26c42c9.png)

The variable for ASG is defined as:

![image](https://user-images.githubusercontent.com/94327/30908150-6cf02db8-a385-11e7-84ec-6a079e83344a.png)

Easiest would be to just refresh all fields with this new option selected, when any of the fields change. Improved logic would only refresh when referenced variables change.

Currently I need to adjust timerange or reload whole dashboard to get fields refresh.

Running Grafana 4.5.1

**Comment by tuukkamustonen** [comment]
Quite related: https://github.com/grafana/grafana/issues/8888

**Comment by tuukkamustonen** [comment]
Nevermind. Grafana seems to already refresh template variables on value change, even if you select "Never" in the dropdown. Maybe I just experienced a temporary glitch.

So... should "Never" be re-labeled as "On template variable change" or such?

**Comment by torkelo** [comment]
yes, variables that contain other variables will automically be updated when that "parent" variable updates.

**Comment by PuppetSumit** [comment]
I have a variable I want to use the same variable on my other dashboards with the persistence of selected values of the variable.
