### ISSUE TITLE
How do decide to send different alert email addresses based on the log query result in Grafana

### ISSUE THREAD

**Issue by cuckoofu** [grafana/grafana#93573]
**Why is this needed**:

I need to send alert emails to different email address based on the query result.

**What would you like to be added**:

Grafana can config different email addresses based on query result.

**Who is this feature for?**

Teams that use grafana to set core alerts。

**Comment by JacobsonMT** [comment]
Hi @cuckoofu, we don't current have any plans to implement log parsing logic as described. However, something equivalent can be achieved with labels and multiple contact points, more information can be found in our [docs](https://grafana.com/docs/grafana/latest/alerting/fundamentals/notifications/notification-policies/)
