### ISSUE TITLE
[Feature request] - Lock time selection between dashboards

### ISSUE THREAD

**Issue by hixxy89** [grafana/grafana#9358]
Hi,

### Request
To be able to select a time range and apply a lock.  When the lock is applied the currently selected time range would then be maintained as you navigate across dashboards.   The user can then unlock the time range and the normal defaults for the dashboards would then be loaded.

### Justification
 We use grafana for trending a variety of sensor readings.  The dashboards are set to a live time range for normal operation i.e. last 24 hours or last 12 hours.  However, we may have an issue that needs investigation after an event (say a 5 hour period in the previous week).  To understand what has happened we would have to check several dashboards for that particular time range and each time change the selection or modify the url.

**Comment by cprivite** [comment]
This is a major issue for me as well. Having grafana reset the timescales makes it extremely hard to troubleshoot an issue when you want to compare data on multiple dashboards. Opening up a tab for each dashboard and customizing the time on each is not a good workflow.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
