### ISSUE TITLE
Table: expose `TableCellInspector` as external component in @grafana/ui

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#93590]
**Why is this needed**:
To allow Table implementations that use custom `cellComponent` to get the latest and greatest updates to the cell inspector.

**What would you like to be added**:
Expose `TableCellInspector` in @grafana/ui, so external apps/plugins can import `TableCellInspector` react component.

**Who is this feature for?**
Explore Logs, developers working with custom Table implementations. Users in Explore (classic)

**Comment by adela-almasan** [comment]
Hey @mjseaman, yes - I've just added it to our epic. It's in Phase 3, so most likely we won't work on it too soon.
