### ISSUE TITLE
No data points - Grafana - Openstack General System Performance 

### ISSUE THREAD

**Issue by prateekvs** [grafana/grafana#9359]
Hello, Everyone,
I'm Running OpenStack private cloud so I want to monitor the performance of OpenStack cloud with grafana. So, for this, I installed graphite in one machine and collectd in another machine where OpenStack is running and added data source graphite in grafana dashboard but when I import dashboard of OpenStack general system performance I'm getting no data points. So, anything is missing or is there any way to get OpenStack performance with grafana ..pls help me out..thank you in advance..

**Comment by torkelo** [comment]
please use community site for questions

**Comment by prateekvs** [comment]
Grafana Community site??

**Comment by nmat** [comment]
@prateekvs think he means: https://community.grafana.com/

**Comment by prateekvs** [comment]
ok..Even I'm using that community
