### ISSUE TITLE
[Bug] Dashboard templating. Dynamic variables. Single directory query results

### ISSUE THREAD

**Issue by Modestas** [grafana/grafana#9360]
### Environment
**Grafana**: 4.5.2
**Datasource**: Graphite
**OS**: CentOS 7.3

### Templating variables
$ServerGroup | ServerA
$DC | servers.$ServerGroup.*
$Host | servers.$ServerGroup.$DC.*

### Query results
**NOT works**

```
-- ServerA
---- DataCenter1
------- ServerA_1
------- ServerA_2
------- ServerA_3
```

$ServerGroup = _ServerA_
$DC = [_All_,DataCenter1]
$Host = [_All_] `(Should be: [All, ServerA_1, ServerA_2, ServerA_3])`

**works**

```
-- ServerA
---- DataCenter1
------- ServerA_1
------- ServerA_2
------- ServerA_3
---- randomKey
```

$ServerGroup = _ServerA_
$DC = [_All_,DataCenter1,randomKey]
$Host = [_All_, ServerA_1, ServerA_2, ServerA_3]

**Bug summary**
If one of the dynamic variables contains only one value, dependant variables stop working.

**Comment by torkelo** [comment]
Try to upgrade Graphite, older versions of graphite can have a problem with a single value in a glob expression
