### ISSUE TITLE
[bug] unreadable amplitude when using transformations non_negative_derivative/difference

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9361]
Please include this information:
- What Grafana version are you using?
4.4.3
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 7

When I use non_negative_derivative or difference, the last untransformed data point sometimes is partially in the graph which makes it hard to view the amplitude of the following data points directly

<img width="793" alt="screen shot 2017-09-27 at 12 05 45 pm" src="https://user-images.githubusercontent.com/2936715/30932727-33c78016-a37d-11e7-9ac9-3305f5db9000.png">

**Comment by torkelo** [comment]
there is not much Grafana can do here as it's a InfluxDB query issue. no sure if it's best fixed in Grafana or InfluxDB though. Looks like non_negative_derivative function in InfluxDB does not handle the starting points very well.
