### ISSUE TITLE
[Bug] Alert values different from graph values

### ISSUE THREAD

**Issue by UndefinedBehaviour** [grafana/grafana#9362]
Grafana version: 4.5.2
OS: CentOs 6
Source: InfluxDB

From Chrome DevTools:
what I get from render endpoint:
<img width="811" alt="schermata 2017-09-27 alle 21 46 21" src="https://user-images.githubusercontent.com/6179913/30934924-63a73c7a-a3cf-11e7-9bd8-073803574a55.png">

what I get from test endpoint:
<img width="719" alt="schermata 2017-09-27 alle 21 46 44" src="https://user-images.githubusercontent.com/6179913/30934834-1bb5e93e-a3cf-11e7-8381-2790b7ef4acb.png">

Also, the negative "timeMs" looks a bit odd.

This is the same symptom as https://github.com/grafana/grafana/issues/6521, but that one seems to be solved in the version I'm using.

**Comment by torkelo** [comment]
Maybe InfluxDB group by time interval is different between queries?

**Comment by torkelo** [comment]
The group by time depends on time range, which is usually different for alert query (compared to graph)
