### ISSUE TITLE
[Bug] Multi-value variables don't work correctly with repeating rows

### ISSUE THREAD

**Issue by dbendelman** [grafana/grafana#9363]
B"H

Grafana 4.4.3
OS: Official docker container running on Ubuntu 14.04
Data Source: Prometheus

**What did you do?**

We have Prometheus monitoring multiple datacenters, each one running N instances of several services: `app1`, `redis2`, etc. Each instance has 3 Prometheus labels: `datacenter`, `instance` (EC2 instance ID), and `instance_name` (EC2 instance tag "Name"). Example:

```
datacenter="eu1" instance="i-00497f11b29b9b590" instance_name="app4"
```

I created these variables:

```
$datacenter -> label_values(datacenter)
$service -> label_values(up{datacenter="$datacenter"}, instance_name) [ Multi-Value, Include All Option, Regex: ([a-z]+)[0-9]* ]
$instance -> label_values(up{datacenter=~"$datacenter", instance_name=~"$service[0-9]*"}, instance) [ Multi-Value, Include All Option, No custom all value ]
$instance_name -> label_values(up{instance="$instance"}, instance_name) [ Hide: Variable ]
```

Next I created a row, repeating for `instance`, that includes the `instance_name` variable in the row title and in the titles of each of the panels.

**What was the expected result?**

When I select exactly one `instance` in the variable dropdown, the row and panel titles correctly show the `instance_name`. I expect that when multiple items in the $instance dropdown are selected, for each of the repeated rows and in each of the panels inside the repeated rows, the $instance_name variable (which references the multi-value $instance variable) should run the `label_values` query and retrieve the instance name for the $instance in its particular row and panel.

**What happened instead?**

When `instance` is set to `All` or multiple are selected, the row and panel titles show "None" for the $instance_name variable. Looking at Chrome DevTools, I confirmed that Grafana is combining all the $instance items into one query to Prometheus:

```
/api/v1/series?match[]=up{instance="i-001afd5ba4a5f1b03|i-025c13d2c49c462b0|i-02e7ffc64ff15f19f"}&start=1506564692&end=1506565592
```

It makes sense that Prometheus is returning "None" for that query. What should happen instead is that each repeating row should do a separate queries to resolve $instance_name based on that row's $instance ID.

**Comment by torkelo** [comment]
Combining panel repeats and row repeats is not supported, sorry.

**Comment by dbendelman** [comment]
@torkelo sorry for the confusion, I'm not using panel repeats, just row repeats.

Let me try to rephrase a bit:

If I have a variable X that references multi-value variable Y, then when I put $X inside the title of a repeating row and set Y=All, the repeating row titles will all show $X="None". This is because Grafana combines all the multiple values in Y and sends only one query to Prometheus to resolve X on the "combined" Y value (i.e. "1|2|3|4"). What it *should* be doing instead is querying Prometheus multiple times to resolve X, once for each value in Y.

Hope this issue is clearer now. Can this please be reopened?

**Comment by torkelo** [comment]
yes, this scenario is not supported, there are no new template variable queries fired for each row. 

The only thing that happens is that each row will have it's own value of Y, X variable will be evaluated with all Y values

**Comment by SeriousM** [comment]
> Combining panel repeats and row repeats is not supported, sorry.

I came here to report this problem but you already answered it, thank you.
Could you please explain why it isn't supported (yet)?

Thanks

**Comment by Cas-pian** [comment]
I met this problem too, sometimes we need to use only part of the label value because of there's special character in the label value which is not working with the regexp.
