### ISSUE TITLE
[New Data Source]: PRTG

### ISSUE THREAD

**Issue by roaralmli** [grafana/grafana#93644]
### Background

Network monitoring

### Use case

Grafana can visualize prtg data in an excellent way.

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
closing as duplicate of [#90786](https://github.com/grafana/grafana/issues/90786) please upvote the original issue
