### ISSUE TITLE
ElasticSearch template query

### ISSUE THREAD

**Issue by satishrao84** [grafana/grafana#9365]
I am trying to get a list of distinct app_ names to display on the dropdown.

I have the below query, which returns the unique app_names.

```
bash-3.2$ curl '172.31.38.157:9200/storedb/server_groups/_search?pretty=true' -d '{"size":0,"aggs":{"distinct_app_names":{"terms":{"field":"app_name.keyword","size":1000}}}}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 621,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "distinct_app_names" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "app_name1",
          "doc_count" : 69
        },
        {
          "key" : "app_name2",
          "doc_count" : 69
        },
        {
          "key" : "app_name3",
          "doc_count" : 69
        }
      ]
    }
  }
}
```

To display the unique app_names i.e. app_name1, app_name2, app_name3 in the dashboard dropdown, I have the below settings in the templating page. 

<img width="768" alt="screen shot 2017-09-27 at 9 53 06 pm" src="https://user-images.githubusercontent.com/20402373/30950064-19b592e2-a3cf-11e7-89c0-c6bcc4b59d61.png">

However, I get a 

> "cannot read property 'then' of undefined"

error. Could you please help me with figuring out the issue?

**Comment by torkelo** [comment]
That query is not looking valid, you cannot have a raw elasticsearch query there.

Looks at the grafana elasticsearch docs for examples of valid queries
