### ISSUE TITLE
Custom panel plugin: Grafana do not catch throwed error

### ISSUE THREAD

**Issue by fcx-Seddik** [grafana/grafana#93667]
### What happened?

After migrating a panel plugin from Grafana 9.5.7 to Grafana 10.4.6, the error handling is not working as expected anymore.

According to [this documentation](https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/error-handling), Grafana should handle errors when I throw one in my panel plugin, and thus showing a small error tooltip at the top left  corner of my panel.

This behavior is correct for the first render of the panel, but as soon as the user edit one of it's options, Grafana display an "unexpected error".

<details>
  <summary>full error</summary>
  
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'pushEvent')
    at vt.logPanelEvent (panelOptionsLogger.ts:41:14)
    at vt.logPanelOptionChanges (panelOptionsLogger.ts:63:14)
    at vt.logChanges (panelOptionsLogger.ts:23:10)
    at It.logPanelChangesOnError (PanelStateWrapper.tsx:387:30)
    at It.onPanelError [as onError] (PanelStateWrapper.tsx:392:12)
    at r.componentDidCatch (ErrorBoundary.tsx:42:18)
    at Rf.ur.componentDidCatch.je.callback (react-dom.production.min.js:190:368)
    at zu (react-dom.production.min.js:144:189)
    at Ze (react-dom.production.min.js:261:422)
    at nh (react-dom.production.min.js:260:446)
Tf @ react-dom.production.min.js:189
  ```
</details>

Here is the code of a newly created panel using `npx @grafana/create-plugin@latest`

```tsx
import React from 'react';
import { PanelProps } from '@grafana/data';
import { SimpleOptions } from 'types';

interface Props extends PanelProps<SimpleOptions> {}

export const SimplePanel: React.FC<Props> = () => {
  throw new Error('My error');

  return <></>;
};
```

and here is a gif of the faulty behavior:

![Image](https://github.com/user-attachments/assets/7c336d74-af95-4286-aefc-e2f52969720d)

As you can see, the error is showing on the top left corner as expected, but only on first render.
after editing an option, we get this unexpected error

### What did you expect to happen?

Grafana should show an error tooltip on the top left corner of the panel, like this : 
![Image](https://github.com/user-attachments/assets/897e0495-6943-4348-a550-d50fbbfbe70b)

### Did this work before?

Yes, in grafana 9.5.7

### How do we reproduce it?

1. In a grafana 10 panel plugin, throw an error
2. On your browser, change an option on the right of the panel (only options added by the developer in the `module.ts` file
3. Observe the issue

### Environment (with versions)?

Grafana: 10.4.6
OS: Linux (5.10.0-32-amd64)
Browser: every
React: 18.2.0

### Grafana platform?

Docker

**Comment by academo** [comment]
Hi @fcx-Seddik I have tested and failed to reproduce this error.

I use the latest create-plugin tool to bootstrap a plugin, then modified the docker-compose file to use exactly to 10.4.6 I run the same code you provided:


```
import React from 'react';
import { PanelProps } from '@grafana/data';
import { SimpleOptions } from 'types';

interface Props extends PanelProps<SimpleOptions> { }

export const SimplePanel: React.FC<Props> = () => {
  throw new Error('My error');

  return <></>;
};
```

and I see the error in the panel 


![Image](https://github.com/user-attachments/assets/023df6db-b9b8-46dc-a582-a71e81e1b350)

My recommendation is, try to run Grafana isolated from any other possible custom configurations or plugins you have in your installation.

How are you running your Grafana installation to develop your plugin? can you share your plugin source code in a public repository?


---

You can download exactly the code I used here [demo-test-panel.zip](https://github.com/user-attachments/files/17127165/demo-test-panel.zip). Simply run `npm install` then `npm run build` and then run `npm run server` (docker required)

**Comment by fcx-Seddik** [comment]
Hi @academo 
i figured out what's the issue was thanks to your answer.
Changing the grafana configuration resolved this behavior.
here's what i did : 

in the `10.4.x.ini` file, i changed the line 1056 as the following:
```diff
# Should Faro javascript agent be initialized
-enabled = false
+enabled = true
```
