### ISSUE TITLE
Explore profiles: Cant edit selected label values

### ISSUE THREAD

**Issue by tomershafir** [grafana/grafana#93664]
### What happened?

After I insert a label value into a filter on Explore Profiles plugin, I can't edit that value. It requires to rewrite it, which is bad UX I think.

### What did you expect to happen?

Enable to edit a selected label value.

### Did this work before?

No

### How do we reproduce it?

1. Open Explore Profiles>labels tab
2. Add label filter and select a label value
3. Try to edit the label value

### Environment (with versions)?

Grafana: 11.2.0
Plugin: 0.1.9

### Grafana platform?

Kubernetes

**Comment by grafakus** [comment]
Hi @tomershafir, thank you for reporting.

AFAIK it has always worked... Here's a short video:

https://github.com/user-attachments/assets/f6465887-e091-47cd-bbe5-e71bb3105f74

**Comment by tomershafir** [comment]
Let me clarify - I expect to be able to edit the value in place. Right now, you can only replace a value, rather than mutate in place. In case of a complex regex for example, its hard to use: it requires to use an external tool to avoid recurring complete rewrites, and results in slower feedback loops.

**Comment by tomershafir** [comment]
I experience the same behavior with `=~` on plugin version 0.1.11

**Comment by grafakus** [comment]
I see. Indeed this is how the [Select component from the design system](https://grafana.com/developers/saga/components/select/) works with custom values. Let me move this issue to the [Explore Profiles repository](https://github.com/grafana/explore-profiles).

Related: https://github.com/grafana/grafana/issues/73528

**Comment by grafakus** [comment]
Will be fixed by https://github.com/grafana/explore-profiles/issues/206
