### ISSUE TITLE
Elasticsearch datasource 400 Bad Request

### ISSUE THREAD

**Issue by danielserrao** [grafana/grafana#93697]
### What happened?

I have added an Elasticsearch datasource to connect to an K8s ingress that redirects traffic to an Elasticsearch service using basic authentication.

The datasource values are:

Skip TLS certificate validation: Enabled
Index name: temporal_visibility_v1_dev
Pattern: Daily
Time field: @timestamp

All the other values are the default.

Grafana version: 10.4.1

Elasticsearch version: 8.14.0

When I click on `Save and Test` I get the messages `Unable to connect with Elasticsearch. Please check the server logs for more details.` and `An error occurred within the plugin`.

The logs on the grafana pod when executing the test are the following:

```
grafana-d995b47b7-j2cw4 grafana logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName=elasticsearch dsUID=fdyvq8zphj75sc uname=daniel.serrao@domain.com t=2024-09-24T16:21:51.344132915Z level=info msg="Response received from Elasticsearch" statusCode=200 status=ok duration=10.476068ms stage=databaseRequest contentLength=331 resourcePath=

grafana-d995b47b7-j2cw4 grafana logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName=elasticsearch dsUID=fdyvq8zphj75sc uname=daniel.serrao@domain.com t=2024-09-24T16:21:51.425620354Z level=error msg="Error received from Elasticsearch" error="Get \"http://elasticsearch.cluster.domain.com/t20poram9/24/2024_vi0ibi9/24/2024it2024_v1_22v/_mapping\": 400 Bad Request" status=error duration=3.132754ms stage=databaseRequest resourcePath=t20poram9/24/2024_vi0ibi9/24/2024it2024_v1_22v/_mapping statusSource=downstream

grafana-d995b47b7-j2cw4 grafana logger=context userId=2 orgId=1 uname=daniel.serrao@domain.comt=2024-09-24T16:21:51.425753046Z level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: Get \"http://elasticsearch.cluster.domain.com/t20poram9/24/2024_vi0ibi9/24/2024it2024_v1_22v/_mapping\": 400 Bad Request" remote_addr=10.233.67.225 traceID=

grafana-d995b47b7-j2cw4 grafana logger=context userId=2 orgId=1 uname=daniel.serrao@domain.comt=2024-09-24T16:21:51.425794447Z level=error msg="Request Completed" method=GET path=/api/datasources/uid/fdyvq8zphj75sc/resources/t20poram9/24/2024_vi0ibi9/24/2024it2024_v1_22v/_mapping status=500 remote_addr=10.233.67.225 time_ms=4 duration=4.768759ms size=116 referer=https://grafana-development.domain.com/connections/datasources/edit/fdyvq8zphj75sc handler=/api/datasources/uid/:uid/resources/* status_source=downstream
```

When port-forwarding to service elasticsearch-es-http on port 9200, I can successfully get a valid response with the command `curl -u "elastic-user:<password>" -k "http://localhost:9200/_search"`

Some sensitive data was changed.

### What did you expect to happen?

I expected the datasource test to be successful.

### Did this work before?

No. First time creating adding this datasource.

### How do we reproduce it?

1. Deploy Elasticsearch according to https://github.com/elastic/cloud-on-k8s/blob/v2.14.0/config/samples/elasticsearch/elasticsearch.yaml with selfsignedcertificate disabled or probably any type of elasticsearch instance version 8.14.0 should do it.
2. Setup the visibility store according to https://docs.temporal.io/self-hosted-guide/visibility#elasticsearch
3. Create elasticsearch datasource with similar values as I mentioned above.

### Is the bug inside a dashboard panel?

No. It starts when validating the datasource.

### Environment (with versions)?

Grafana: 10.4.1
Elasticsearch: 8.14.0
Kubernetes: v1.28.10
Browser: Microsoft Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

Elasticsearch

**Comment by danielserrao** [comment]
Hi @iwysiu, yes I did.

I also tried deploying Elasticsearch [7.17.3](docker.elastic.co/elasticsearch/elasticsearch:7.17.3) without authentication enabled and I get the following error logs on Grafana:

```
grafana-6d96995bcb-hrmjc grafana logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName=Elastic-awssndk8sdnl002 dsUID=P0CBD26C6824FE792 uname=daniel.serrao@domain.com t=2024-10-14T16:22:27.693786847Z level=info msg="Response received from Elasticsearch" statusCode=200 status=ok duration=9.844802ms stage=databaseRequest contentLength=333 resourcePath=
grafana-6d96995bcb-hrmjc grafana logger=tsdb.elasticsearch endpoint=callResource pluginId=elasticsearch dsName=Elastic-awssndk8sdnl002 dsUID=P0CBD26C6824FE792 uname=daniel.serrao@domain.com t=2024-10-14T16:22:27.785110986Z level=error msg="Error received from Elasticsearch" error="Get \"http://elasticsearch.awssndk8sdnl002.domain.com/t10poram10/14/2024_vi0ibi10/14/2024it2024_v1_11v/_mapping\": 400 Bad Request" status=error duration=3.575494ms stage=databaseRequest resourcePath=t10poram10/14/2024_vi0ibi10/14/2024it2024_v1_11v/_mapping statusSource=downstream
grafana-6d96995bcb-hrmjc grafana logger=context userId=2 orgId=1 uname=daniel.serrao@domain.com t=2024-10-14T16:22:27.78521276Z level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: Get \"http://elasticsearch.awssndk8sdnl002.domain.com/t10poram10/14/2024_vi0ibi10/14/2024it2024_v1_11v/_mapping\": 400 Bad Request" remote_addr=10.233.69.222 traceID=
grafana-6d96995bcb-hrmjc grafana logger=context userId=2 orgId=1 uname=daniel.serrao@domain.com t=2024-10-14T16:22:27.785249981Z level=error msg="Request Completed" method=GET path=/api/datasources/uid/P0CBD26C6824FE792/resources/t10poram10/14/2024_vi0ibi10/14/2024it2024_v1_11v/_mapping status=500 remote_addr=10.233.69.222 time_ms=4 duration=4.867337ms size=116 referer=https://grafana-development.domain.com/connections/datasources/edit/P0CBD26C6824FE792 handler=/api/datasources/uid/:uid/resources/* status_source=downstream

```

I also confirmed that the mapping exist with the command `curl -k "http://localhost:9200/temporal_visibility_v1_dev/_mapping"` .

**Comment by njvrzm** [comment]
Hi @danielserrao - the "Pattern" setting is for use with indexes that include a date or time pattern. For instance, if you had daily indices with names like `temporal_visibility_v1_dev-2024-10-21`, you could use an index name of `[temporal_visibility_v1_dev-]YYYY-MM-DD` with the `Daily` pattern and Grafana will always choose the current day's index. Any part of the index that isn't a date pattern needs to be enclosed in square brackets, or else any characters that happen to match date formatting strings will be substituted. (This is not well documented - we'll see about fixing that.)

Since your datasource has "Pattern" set, but your index doesn't include a pattern and isn't wrapped in square brackets, you're getting the somewhat random-seeming index of `t10poram10/14/2024_vi0ibi10/14/2024it2024_v1_11v` in your requests, as various parts of the date are filled into parts of your index.

So, all you should need to do here is select `No pattern` in the "Pattern" dropdown, or, if you do want to use index patterns, enclose the parts of your index that aren't part of the date pattern in square brackets. Let us know if that doesn't resolve things!

**Comment by danielserrao** [comment]
Hi @njvrzm,

Sorry for the late response and thanks for the answer. You are right. Probably I should have said this on my initial post but I tried before using "No Pattern" but didn't work due to the error "No date field named @timestamp found". This was fixed by adding adding the timestamp with the following requests to the elasticsearch API:

```
curl -X PUT "localhost:9200/_ingest/pipeline/add-timestamp?pretty" -H 'Content-Type: application/json' -d'
{
  "description" : "Ingest a timestamp on the documents",
  "processors" : [
    {
      "set" : {
        "field": "timestamp",
        "value": "{{_ingest.timestamp}}"
      }
    }
  ]
}
'

curl -X PUT "localhost:9200/temporal_visibility_v1_dev/_settings?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index.default_pipeline": "add-timestamp" 
  }
}
'

curl -X PUT "localhost:9200/temporal_visibility_v1_dev/_mapping?pretty" -H 'Content-Type: application/json' -d'
{
  "properties": {
	"@timestamp": {
	  "type": "date"
	}
  }
}
'
```
