### ISSUE TITLE
Error in latest chrome

### ISSUE THREAD

**Issue by fuyarchuk-kg** [grafana/grafana#93719]
I have a problem on loading grafana in latest versions of chrome on all the platforms. It load normally in other browsers.
![Image](https://github.com/user-attachments/assets/282cbb6b-8f56-4e6c-ad9b-ce8fadd50ceb)
![Image](https://github.com/user-attachments/assets/cc80d9bb-db8d-4405-8eaa-38d63e1f910d)
Full error 
[error.txt](https://github.com/user-attachments/files/17127333/error.txt)

**Comment by joshhunt** [comment]
This works as expected for me in latest Chrome. A fair bunch of people here use Chrome, and we haven't heard anything about this being broken.

![Image](https://github.com/user-attachments/assets/adc733fa-cf4b-4d07-b5f7-17f711239392)

Are you able to load this dashboard https://play.grafana.org/d/f62a0410-5abb-4dd8-9dfc-caddfc3e2ffd/eccb2445-b0a2-5e83-8e0f-6d5ea53ad575 ?

What version of grafana are you using? Are you on Grafana Cloud or self hosted?

**Comment by fuyarchuk-kg** [comment]
I am so sorry, i just found that TwoSeven Extension blocked the access. May be it was some incompatibility with new chrome(
