### ISSUE TITLE
[Bug] Datasource TLS CA option doesn't work without client authentication and is silently not verified

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#9371]
- What Grafana version are you using?

4.5.1

- What OS are you running grafana on?

Linux

* * *

See also: #8812, #9366.

It looks as though providing your own CA certificate for does not work unless you also enable 'TLS Client Authentication':

https://github.com/grafana/grafana/blob/c114c461198928d5433b88e23985fa27497e914b/pkg/models/datasource_cache.go#L69-L87

The `tlsAuth` option referred to, that gates inclusion of the custom CA, is the 'TLS Client Auth' checkbox:

<img width="1176" alt="screen shot 2017-09-28 at 10 10 21" src="https://user-images.githubusercontent.com/4348848/30958858-49191d80-a436-11e7-94a7-c4930df05c68.png">

Unfortunately it would be difficult to detect that this is not working due to TLS certificates not being verified by default: #8812

It should be possible to specify a TLS CA without enabling client authentication.

**Comment by mattbostock** [comment]
Working on a PR to fix.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9377
