### ISSUE TITLE
Enable User login metrics

### ISSUE THREAD

**Issue by kunalmehta-eve** [grafana/grafana#93722]
**Why is this needed**:

It would be really nice to have login count for each user exposed as metric /metrics in OSS version.Another great thing would be to check the usage count for each dashboard 

**What would you like to be added**:

It would be really nice to have login count for each user exposed as metric /metrics in OSS version.Another great thing would be to check the usage count for each dashboard 

**Who is this feature for?**

Grafana OSS

**Comment by Jguer** [comment]
Hey @kunalmehta-eve this would result in very high metric cardinality for instances with a high number of users. As such we won't be implementing this metric.

Usage insights might help with this particular case: https://grafana.com/docs/grafana-cloud/account-management/usage-insights/ 

As an alternative, this would be more easily monitored from a configured identity provider providing SSO.
