### ISSUE TITLE
[Bug] TLS is not verified during OAuth callback

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#9373]
- What Grafana version are you using?

4.5.1

- What OS are you running grafana on?

Linux

See:
https://github.com/grafana/grafana/blob/c114c461198928d5433b88e23985fa27497e914b/pkg/api/login_oauth.go#L98-L109

TLS should be verified by default.

Related: #8812

**Comment by bergquist** [comment]
:100: 

But this would have to be configurable for those who don't want it. Not sure if it should be one global setting for all outgoing requests or one per oauth, datasources, alert notifications. etc

**Comment by mattbostock** [comment]
I made a start here: #9378

I haven't added a UI option, but wanted to get something out so that at least others can patch their deployment if they wish to.

#9377 tackles this more comprehensively for datasources and adds an explicit 'skip verify' option.

**Comment by mattbostock** [comment]
Seems that TLS verification is only skipped if TLS client authentication is enabled: #9419, which mitigates the issue for some installations.
