### ISSUE TITLE
auth.anonymous.device_limit does not actually limit the amount of devices that can access

### ISSUE THREAD

**Issue by Thiago-Dantas** [grafana/grafana#93755]
### What happened?

After setting device_limit=1, multiple different devices (different browsers, different machines, different ips, etc) could still access the anonymous org.
The only thing that it seems to be actually limiting is the Anonymous devices view in /admin/users

On the second access you do get an unauthorized popup.
Sometimes you are redirected to a blank grafana page, then you could just click the side panel to go to Dashboards and open it.
Sometimes you just click the unauthorized popup and everything just works fine

This was tested on the grafana/grafana:11.2.0 docker image

### What did you expect to happen?

Other anonymous devices to be fully denied access to grafana once device_limit is reached

### Did this work before?

no idea

### How do we reproduce it?

1. make an anonymous org and create a dashboard
2. open the dash in an anonymous browser window on multiple devices
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.2
OS: linux
Browser: brave, chrome, firefox

### Grafana platform?

Docker

**Comment by Jguer** [comment]
Hey @Thiago-Dantas , I've been able to confirm this issue and linking it to a local caching issue. The fix for it should be merged soon
