### ISSUE TITLE
AWS CloudWatch 

### ISSUE THREAD

**Issue by eccforgit** [grafana/grafana#9376]
I am using Grafana on Windows and keep getting the same error

e[31mERORe[0m[09-27|06:58:29] Request Completed e[31mloggere[0m=context e[31muserIde[0m=1 e[31morgIde[0m=1 e[31munamee[0m=admin e[31mmethode[0m=POST e[31mpathe[0m=/api/datasources/proxy/3 e[31mstatuse[0m=500 e[31mremote_addre[0m=[::1] e[31mtime_mse[0m=20411 e[31msizee[0m=36 e[31mreferere[0m=http://localhost:8080/datasources/edit/3
e[31mERORe[0m[09-27|06:59:37] Unable to call AWS API e[31mloggere[0m=context e[31muserIde[0m=1 e[31morgIde[0m=1 e[31munamee[0m=admin e[31merrore[0m="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"

I have my credentials file in C:\users%USER%.aws\credentials. This works for other uses of the AWS SDK which I do with other programs. I have tried explicitly defining the path to the credentials and leaving the credentials blank for the default and both give the same error.

**Comment by torkelo** [comment]
please use community site for questions (https://community.grafana.com)
