### ISSUE TITLE
JIRA

### ISSUE THREAD

**Issue by manojreddyv** [grafana/grafana#93777]
### Background

I need to create jira tickets for my alerts so i need it. 

### Use case

JIRA plugin is required and need to install

### Contribution

- [x] Are you looking to create the plugin?
- [x] Are you affiliated with the project/product the data source integrates with?
- [x] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi - a Jira plugin is available in the catalog already - https://grafana.com/grafana/plugins/grafana-jira-datasource/

It is `enterprise` but you can use without limitation within the Grafana Cloud free tier, as well as through a trial license.
