### ISSUE TITLE
[Bug] Import/Export of plugins does not work

### ISSUE THREAD

**Issue by eccforgit** [grafana/grafana#9379]
Please include this information:
- What Grafana version are you using? **4.5.2**
- What datasource are you using? **MySQL**
- What OS are you running grafana on? **Windows Server 16**
- What did you do? **Exported from on Server, and Imported to another**
- What was the expected result? **All panels to appear just as they did on the original server**
- What happened instead? **The built in panels all showed up, but the plugin panels were all broken**
**PieChart - says unknown panel type: grafana-piechart-panel
D3 Gauge doesn't show up at all
WorldMap Panel - doesn't show up at all**

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
You need to install the piechart panel on the other grafana server
