### ISSUE TITLE
[Feature request] Using "Custom" template variables in the datasource for combining datasources

### ISSUE THREAD

**Issue by divishkumar** [grafana/grafana#9380]
Please include this information:
- What Grafana version are you using?
4.5.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS 7.3.1611

I would like to be able to use the normal(not datasource) template variables in combination with a constant as the datasource for a query. The following is the current setup.

We have 2 datacenters and 3 environments in each. To prevent cross DC comms, we are forced to have a separate influxdb instance in each of those envs. So the list of datasources for e.g. will look like
QA-DC1
QA-DC2
PROD-DC1
PROD-DC2

I would like to see data from both dcs on a panel when I select an env. So I'd like to have a custom tamplate variable env with values QA,PROD and then in my query datasource be able to do
Query1 - datasource -> $env-DC1
Query1 - datasource -> $env-DC2
This would let me run the same query across multiple datasources and combine that on the graph

**Comment by torkelo** [comment]
Sorry, this will never work. You can used mixed datasource and have two queries that go to different datasources on same graph.

But your case is next to impossible to solve

**Comment by divishkumar** [comment]
Hey,

Just out of curiosity, may I ask why this is so difficult. I thought it might be an easy one just getting the datasource variable to substitute any template variables in it before making the request ?

**Comment by torkelo** [comment]
But that is not all your asking, you asking to loop through variable and execute query for each matching datasource, right?

**Comment by divishkumar** [comment]
That's pretty much all I need. Before making the request for each query, we substitute any template variables in it and make the request. If we don't have to check that it's a valid data source then would it be a problem ?

**Comment by divishkumar** [comment]
Ah I think I didnt word my example properly. When I put
Query1 - datasource -> $env-DC1
Query1 - datasource -> $env-DC2

What I actually meant is

Query1 - datasource -> $env-DC1
Query2 - datasource -> $env-DC2

Just that query 2 is basically the same sql as query 1

**Comment by torkelo** [comment]
But is the query being sent to the same data source or different datasources?

**Comment by divishkumar** [comment]
A single query will be sent to a single data source

Datasource 1
Name: QA-DC1
URL: http://qa-dc1.internal/influxdb

Datasource 2
Name: QA-DC2
URL: http://qa-dc2.internal/influxdb

Template variable:
env: QA,PROD

Query 1:
Datasource: $env-DC1
Query: select idl from cpu where app = app1

Query 2:
Datasource: $env-DC2
Query: select idl from cpu where app = app1

So now when I select QA from the template variable drop-down, query 1 is run on QA-DC1 and query 2 is run on QA-DC2.

We could somehow restrict a template variable which will be used in a datasource from allowing the All/multiple option so we can only select 1 value from the drop-down.

**Comment by torkelo** [comment]
but you have 2 data sources? you want two queries sent to each right? that is the thing that is not going to work.

**Comment by divishkumar** [comment]
Hmmm query 1 will be sent to datasource 1 and query 2 to datasource 2.

I can already do that using the existing mixed datasource option by having QA-DC1 for query 1 and QA-DC2 for query 2. All I need here is to make the first part of the datasource name a template variable so I can switch between QA and PROD.

I can try and get some screenshots when I get to work tomorrow

**Comment by divishkumar** [comment]
Couldn't wait :)

![screen shot 2017-09-28 at 21 49 58](https://user-images.githubusercontent.com/27893565/30989843-11949f4a-a497-11e7-8749-ea782649f53f.png)

So in the above, all I want is to be able to have QA as a variable.

**Comment by divishkumar** [comment]
Hey @torkelo 
Had a chance to look at this ?

**Comment by torkelo** [comment]
Yes, while technically possible (if implemented) think this is better done by programmatically building dashboards, not using live templating feature

**Comment by divishkumar** [comment]
Hmmm, still tempted to get this with live templating as that's what templating is meant for ? Atm, we can use template variables pretty much throughout the dashboard except for in the name of the datasource. Struggling to see why that should be an exception :/

**Comment by torkelo** [comment]
Because the datasource template variable is special, and has info on what type of datasource it represents.

**Comment by divishkumar** [comment]
:(
