### ISSUE TITLE
[Bug] sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *time.Time

### ISSUE THREAD

**Issue by cbattlegear** [grafana/grafana#9381]
datasource: MySQL
OS: docker
Grafana Version: v4.5.2 (commit: ec2b0fe)

Doing a MySQL query that is getting datetime values. Currently this is a nullable column with a few null values in it. When running against a column with null values getting the error: 

sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *time.Time

Looks like this was already handled for strings with #8578 and #8918 but not for date times.

**Comment by torkelo** [comment]
what does your query look like ?

**Comment by cbattlegear** [comment]
Table Structure:

MySQL [sheet_sync]> describe KombuchaBrewing;                                                
```
+-------------+--------------+------+-----+---------+-------+                                
| Field       | Type         | Null | Key | Default | Extra |                                
+-------------+--------------+------+-----+---------+-------+                                
| BatchNumber | int(11)      | YES  |     | NULL    |       |                                
| StartDate   | datetime     | YES  |     | NULL    |       |                                
| BottleDate  | datetime     | YES  |     | NULL    |       |                                
| EndDate     | datetime     | YES  |     | NULL    |       |                                
| Notes       | varchar(500) | YES  |     | NULL    |       |                                
+-------------+--------------+------+-----+---------+-------+
```

BottleDate and EndDate currently have nulls
So one query I ran that failed with the error was:
`SELECT * FROM KombuchaBrewing;`
I have also run the query with the columns listed out and received the same error.
If I run: 
`SELECT BatchNumber, StartDate, Notes FROM KombuchaBrewing;`
I do not get the error (Note: Currently Notes has empty strings in it but not NULLS)

**Comment by daniellee** [comment]
@cbattlegear is this for a time series data or table data? Returning null as the timestamp for timeseries data is not valid data.

**Comment by cbattlegear** [comment]
@daniellee Table data is where I am seeing the issue.

**Comment by daniellee** [comment]
@cbattlegear thanks for the clarification. I will be working on the mysql ds tomorrow so I can take a look at it.

**Comment by whwright** [comment]
Seeing the same issue, but with a string type in table data.
Grafana 4.6.1, MySQL datasource as well

Query:

```sql
SELECT
  thing1.id,
  thing2.name,  -- this is nullable b/c of left join
FROM thing1
LEFT JOIN thing2
  ON thing1.id = thing2.thing1_id
```

Error: `sql: Scan error on column index 3: unsupported Scan, storing driver.Value type <nil> into type *string`

This fixes the issue but it's kinda gross

```sql
CASE WHEN thing2.name IS NULL THEN "" ELSE thing2.name END
```

**Comment by vzool** [comment]
Hay @cbattlegear if you still has this issue from time to time. Just convert type of **StartDate** from ***time.Time** to **interface{}**. Hope it help out.

Thanks
