### ISSUE TITLE
[Feature request] Add a label for Template Variables

### ISSUE THREAD

**Issue by bbourqu** [grafana/grafana#9383]
Please include this information:
- What Grafana version are you using? 4.4.3
- What did you do? As a new user I didn't know that the tags on a Dashboard were Template Variables.
I think it may make the UI easier to read if the Template variables were prefixed with a label or placed into a section with a label of Template Variables.  This would draw the user's attention and would also allow them the ability to explore the documentation on those words, especially if they are a new user that is utilizing a previously built board.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
