### ISSUE TITLE
Alerting: no visibility on folder structure when assigning alert to a folder

### ISSUE THREAD

**Issue by Notedop** [grafana/grafana#93838]
### What happened?

When creating an alert, the alert needs to be assigned to a folder which can be selected from a dropdown list. In my case we have a folder structure with multiple levels where-as folders on different levels can have the same name. 

It is impossible from the dropdown to identify to which actual folder the alert will be assigned.

### What did you expect to happen?

I should be able to select the actual folder from a folder structure view instead of from a dropdown with folder names.

### Did this work before?

This was not an issue until support for folder structures was added.

### How do we reproduce it?

1. Create a dashboard folder structure with multiple levels, where-as 
    Consider this folder structure:
    
    - Countries
        - NL
            -   INFRASTRUCTURE
        - DE
            -   INFRASTRUCTURE

2. Create an alert, scroll to the section "3. Set evaluation behavior". There is a dropdown which shows the following values:

    - COUNTRIES
    - NL
    - INFRASTRUCTURE
    - DE
    - INFRASTRUCTURE

4. Try to select the proper INFRASTRUCTURE folder from the dropdown. Note that this is a simple example, but if you have a lot more folders with same names, it becomes very difficult to identify the correct folder.

### Is the bug inside a dashboard panel?

not applicable

### Environment (with versions)?

Grafana: "version": "11.1.3"
OS: Any
Browser: Any

### Grafana platform?

A downloaded binary

**Comment by joeblubaugh** [comment]
I would suggest mimicking or re-using the dashboard menu's folder picker:![Image](https://github.com/user-attachments/assets/64c7980e-695b-4071-8944-0959a7712c16)
