### ISSUE TITLE
i want bigquery please

### ISSUE THREAD

**Issue by falahadima** [grafana/grafana#93850]
### Background

i want bigquery please

### Use case

i want bigquery please

### Contribution

- [x] Are you looking to create the plugin?
- [x] Are you affiliated with the project/product the data source integrates with?
- [x] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi @falahadima BigQuery is available as a data source - https://grafana.com/grafana/plugins/grafana-bigquery-datasource/ could you describe what issue you are having?
