### ISSUE TITLE
Document how to build docker image

### ISSUE THREAD

**Issue by rickard-von-essen** [grafana/grafana#9387]
It would be helpful if there where some more details in [/docs/sources/project/building_from_source.md](https://github.com/grafana/grafana/blob/master/docs/sources/project/building_from_source.md) on how to build your own docker image from master/PR etc.

**Comment by rickard-von-essen** [comment]
There are lots of confusing old/private build scripts making it hard to find what is relevant.

**Comment by fg2it** [comment]
Not excactly on the same topic, but related, build env for deployements and for tests seems a bit different. For example, [tests on ci use yarn 0.27](https://circleci.com/gh/grafana/grafana/9253) and [build env for dep of v4.5.2 use yarn 1.0.2](https://circleci.com/gh/grafana/grafana/9140). Probably better if the env are the same.

**Comment by torkelo** [comment]
Think your missreading the circle ci output regarding yarn version

If you need to build docker container with custom build of grafana following the default build from source guide to generate package, then modify stock grafana docker container to use that package

**Comment by fg2it** [comment]
@torkelo it is possible, but the log are quite misleading : 
for dep, I see yarn 1.0.2
![grafana-dep-yarn1 0 2](https://user-images.githubusercontent.com/13949984/31057612-e2f191e2-a6e5-11e7-98f5-f80b7294d6e9.png)
whereas for tests I see 0.27
![grafana-test-yarn0 27](https://user-images.githubusercontent.com/13949984/31057614-ee22d8c8-a6e5-11e7-89c6-7ee269d09b19.png)

**Comment by rickard-von-essen** [comment]
> following the default build from source guide to generate package, 

That is not very helpfull since I have a Mac and that creates: `grafana_4.6.0-1507036061pre1_darwin-amd64.deb` which doesn't run very well in Docker.

> then modify stock grafana docker container to use that package

It's not very obvious which `Dockerfile` should be used:

```shell
$ find . -name Dockerfile
./docker/blocks/mysql_opendata/Dockerfile
./docker/blocks/smtp/Dockerfile
./docker/blocks/prometheus/Dockerfile
./docker/blocks/openldap/Dockerfile
./docker/blocks/graphite1/Dockerfile
./docker/blocks/graphite/Dockerfile
./docker/blocks/collectd/Dockerfile
./docker/debtest/Dockerfile
./docker/buildcontainer/Dockerfile
./node_modules/ace-builds/demo/kitchen-sink/docs/Dockerfile
./docs/Dockerfile
./scripts/build/Dockerfile
```
Maybe it's actually [grafana-docker/Dockerfile](https://github.com/grafana/grafana-docker/blob/master/Dockerfile).

---

It would be nice witch just some pointer how you cross-compile, or do you build in a build container and then which `Dockerfile` to customize. Not much but it will help contributors allot to cut down of the time to verify their contributions in production. Maybe clean up some old files to.

**Comment by torkelo** [comment]
Sorry, I should have linked to our official docker, https://github.com/grafana/grafana-docker/blob/master/Dockerfile

The ones you linked to that are in the docker folder in the repository are for testing different datasources and dbs.

You cannot easily cross compile grafana as it uses cgo for sqlite, you need to build grafana on Linux or inside a Linux container if you want to use it inside a Linux container
