### ISSUE TITLE
New Select: Async functionality

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#93884]
Why?
To provide a consistent way of handling external requests 

What?

Make the `options` prop accept an async function.

- Support loading on input update
- Support loading on focus/opened menu
- Support option to load on mount
- Have a clear loading state

**Comment by pavan-gopala** [comment]
Requirements Breakdown
Make the options prop accept an async function:
This means that the component should be able to take a function as a prop that returns a Promise. This function will be used to fetch options asynchronously, such as from an API.
Support loading on input update:
The component should show a loading state whenever the user updates the input field. This indicates that new options are being fetched based on the user's input.
Support loading on focus/opened menu:
When the user focuses on the input or opens the dropdown menu, the component should trigger the async function to load options and display a loading indicator while fetching data.
Support option to load on mount:
The component should have an option to automatically load data when it is first rendered (mounted). This is useful for preloading data that might be needed immediately.
Have a clear loading state:
There should be a visible indication (like a spinner or loading message) when data is being fetched, making it clear to users that they should wait for the options to load.

**Comment by pavan-gopala** [comment]
@tskarhed let me know above points are clear.. I want to work on it.. Only thing I am missing is where the changes will take place..(component)

**Comment by tskarhed** [comment]
Hello @pavan-gopala! I would have a look at some issues with the `help-wanted` label instead, as we want to do this specific issue in-house.

**Comment by pavan-gopala** [comment]
@tskarhed Got it! I’ll check "help-wanted." This is concise and clear!
