### ISSUE TITLE
RestoreDashboards: Add a link to the confirmation Toast

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#93886]
Show a button in the confirmation Toast which links to the Recently deleted page. Let the toast stay a bit longer to give users the chance to actually click this button.
=> add `reportInteraction()`

![Image](https://github.com/user-attachments/assets/21aa44ac-fc3b-42d5-96a2-3f664f498d74)

**Comment by akshaywakhare** [comment]
Hi, I'd like to work on this, can you please assign it to me

**Comment by L-M-K-B** [comment]
We discussed this in our daily sync today and decided that we are not going to implement this.
