### ISSUE TITLE
RestoreDashboards: Add link to dashboards browse view

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#93885]
As the Recently deleted page is hard to find we need to link the page.
Consult with @teddyba whether the suggested place is acceptable.

**Requirements:**
- secondary button
- button shown under the same conditions as Recently deleted page
- add `reportInteraction()`
- in the browse view for dashboards and the folder view (see below)

![Image](https://github.com/user-attachments/assets/884001cf-230e-447d-9434-ea42b97fe070)
![Image](https://github.com/user-attachments/assets/a7f518c4-6293-460c-85d2-c444ced68b2c)

**Comment by akshaywakhare** [comment]
Hi, can you please assign this to me.

And can you clarify the 2nd requirement please (`button shown under the same conditions as Recently deleted page`)

**Comment by teddyba** [comment]
I think this placement is fine, and I don't have any suitable alternatives. 

The one thing that I find strange is that the other buttons on this page are **actions**, whereas this new button would be a **link** to the recently deleted page, right?

**Comment by akshaywakhare** [comment]
> I think this placement is fine, and I don't have any suitable alternatives. 
> 
> The one thing that I find strange is that the other buttons on this page are **actions**, whereas this new button would be a **link** to the recently deleted page, right? 

Yes looks like it. It'll be a simple redirect button. 
Can you still clarify the second point of requirement please.

**Comment by L-M-K-B** [comment]
Hi @akshaywakhare, thanks a lot for wanting to contribute to grafana. The changes got already implemented [here](https://github.com/grafana/grafana/pull/94000) but if you like you can have a look at [our list of other issues](https://github.com/grafana/grafana/labels/help%20wanted) labeled with `help wanted`.
