### ISSUE TITLE
Grafana returning incorrect values after "group by" on ElasticSearch

### ISSUE THREAD

**Issue by satishrao84** [grafana/grafana#9389]
Hello,
I have data in json structure of the below format stored in ElasticSearch 
```
{
app_name::"dqdq",
buckets:[{
   name:bucket1,
   node:[{
     hostname:"host1"
     cpu : <some #> 
     }
    ]
  }]
}
```

So multiple nodes belong to a bucket and multiple buckets belong to an application. 

Below is the config on my graph panel in grafana 

<img width="963" alt="screen shot 2017-09-29 at 12 39 31 pm" src="https://user-images.githubusercontent.com/20402373/31032999-571ec8e8-a513-11e7-9f31-c4412500aef3.png">

The problem is (as the graph shows) all the nodes in the graph for a bucket are showing the same value for a given time. The data is incorrect. The data in csv format is shown below

<img width="792" alt="screen shot 2017-09-29 at 12 42 05 pm" src="https://user-images.githubusercontent.com/20402373/31033093-a69a6f6c-a513-11e7-89c3-b25fbe78641b.png">

But when I do the below query on Elasticsearch 

curl '<ipaddr>:9200/buckets/_search?pretty=true' -d '{"query": {"bool": {"must": [{"term": {"app_name": "bio_pass"}},{"term": {"timestamp": "2017-09-07T14:50:16.12-07:00"}}]}}}'

I get the below data which shows that the cpu metric for a node for a bucket for a given timestamp is not the same:

<img width="510" alt="screen shot 2017-09-29 at 12 45 55 pm" src="https://user-images.githubusercontent.com/20402373/31033297-553520a8-a514-11e7-857b-72cce889c586.png">

I can verify that the query going to the elasticsearch is correct with the correct variables 

<img width="1668" alt="screen shot 2017-09-29 at 12 48 17 pm" src="https://user-images.githubusercontent.com/20402373/31033683-dc564e30-a515-11e7-9766-4a795f7b2fa8.png">

Does anyone have any ideas why grafana is returning the same values accross series? Is there anything I could be doing wrong? I've brainstormed this for a long time, and I just cannot figure it out.

**Comment by torkelo** [comment]
Grafana shows what you what Elasticsearch returns,m the query inspector you can expand the response as well. 

Maybe it's the date histogram interval? try increasing it.

**Comment by satishrao84** [comment]
No please don't close the issue. This has nothing to do with date histogram interval. Please help me out here! Please look at the original post.

<img width="1651" alt="screen shot 2017-10-01 at 4 46 16 pm" src="https://user-images.githubusercontent.com/20402373/31060409-2509e962-a6c8-11e7-96c7-f82b41d52f9a.png">

I've changed the query (shown above) where I should now be limiting the aggregate to one element of the buckets array. But again, I am facing the same issue as before i.e. where all the nodes are showing the same value for a given bucket, but in fact they are not the same. 

Is there any way I can see the elasticsearch query being executed in the backend?
