### ISSUE TITLE
Timestream for Grafana machine learning

### ISSUE THREAD

**Issue by Aryan-Morteza** [grafana/grafana#93905]
### Background

I have access to TimeStream data source in Grafana dashboard, But I don't see it in data source selection section in garfana Machine Learning. 

### Use case

Use case:
Incorporating TimeStream into Grafna machine learning

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi - per the issue template:

Please do not request support or file bug reports and feature requests for existing plugins here.

For support, please use the community support resources [here](https://grafana.com/help/).
Please consider the New Bug Report or Feature Requests [issue templates](https://github.com/grafana/grafana/issues/new/choose) for other requests.
