### ISSUE TITLE
[Bug] Alias for Additional Metrics On Same Graph Broken

### ISSUE THREAD

**Issue by amcrn** [grafana/grafana#9390]
![image](https://user-images.githubusercontent.com/4933419/31034393-c5596b10-a518-11e7-9e63-3d36821ecd99.png)

Information:

* Grafana Version: 4.5.2
* Datasource: OpenTSDB
* OS: Ubuntu

How to Reproduce:

* Create a Graph Panel
* Add a Metric 'A' to the Graph and set the Alias to something like say `$tag_foo`.
* Add a Metric 'B' to the same Graph and set the Alias to something different, like `$tag_bar`.

Problem: `$tag_bar` isn't used as expected for Metric B, instead, `$tag_foo` (as a literal string) is. This is true for the tooltip as well as the Legend.

**Comment by torkelo** [comment]
This has been reported many times already (for example, #2687, https://github.com/grafana/grafana/issues/7560)

Due to a limitation in the OpenTSDB query api,
#1876

fixed in latest version of OpenTSDB I think
