### ISSUE TITLE
[Feature request] Clean up how "No data points" is shown

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#9395]
When there is no data to show, a graph panel displays as something like:

![image](https://user-images.githubusercontent.com/94327/31071255-06d1e806-a76c-11e7-8fe7-3009d915f71c.png)

However, it does no good to show the grid lines or Y-axis values here - if there's no data, rather show nothing. Also, the "No data points" label could be re-aligned to the center:

![image](https://user-images.githubusercontent.com/94327/31071244-fb988dfa-a76b-11e7-85e8-3379f0b5a2d0.png)

Running Grafana 4.5.1.

**Comment by daniellee** [comment]
This has been open for a few years and only gotten one thumbs up. The text is now centered though. Closing this feature request due to lack of interest from the community.

**Comment by tuukkamustonen** [comment]
Still don't see what benefit there is in showing the axes and their values, even if people haven't found the ticket. But ok, good to hear it's at least centered.
