### ISSUE TITLE
[Feature request] Show the drag-to-resize handle in panels on mouse-over only

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#9396]
The drag-to-resize handles don't need to be visible at all time:

![image](https://user-images.githubusercontent.com/94327/31071733-ce021bb6-a76d-11e7-8c8d-79bf36faccb6.png)

Rather:

![image](https://user-images.githubusercontent.com/94327/31071737-d52c5000-a76d-11e7-932b-0214d6774652.png)

It is especially ugly when using transparent panels:

![image](https://user-images.githubusercontent.com/94327/31072060-22a58936-a76f-11e7-8fd1-bb49be6e2f86.png)

(The handle is just floating there, all alone.)

It would be sufficient to show the handles on mouse-over only, to make dashboards a bit cleaner.

This may feel trivial, but it's something that could be improved, still. Showing the handles always is unnecessary information - experienced users know this already, and it becomes evident to a new user in a second or two.

Running Grafana 4.5.1.

**Comment by torkelo** [comment]
this is already done in our develop (5.0 branch)

**Comment by tuukkamustonen** [comment]
Oh, pretty neat! :)
