### ISSUE TITLE
Frontend Sandbox: Implement backend API to enable/disable frontend sandbox for specific plugin

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#93984]
Requisites:

 - [ ] Behind a feature flag
 - [ ] Data to store: Plugin ID and if the sandbox is enabled or not. Including a default value (e.g. `plugin: grafana-testdata-datasource, enabled: true` or `plugin: all, enabled: false`).
 - [ ] Setting is namespaced by Org.
 - [ ] Authorization: Require `Admin` or plugin write access (`plugin:install` or `plugin:write` roles) for writing. Require `Viewer` for reading.

Request examples:

 - `GET /apis/sandboxsettings.grafana.app/v0alpha1/namespaces/default/sandboxsettings/grafana-testdata-datasouce`. Response:
```json
{
  "kind": "SandboxSettings",
  "apiVersion": "sandboxsettings.grafana.app/v0alpha1",
  "metadata": {
    "name": "xbs2z5",
    "namespace": "default",
    "uid": "1a9522f8-f97e-477a-b8d7-ec08351e45fa",
    "resourceVersion": "1",
    "creationTimestamp": "2024-09-27T13:41:35Z",
    "annotations": {
      "grafana.app/createdBy": "user:1"
    },
    "managedFields": [...]
  },
  "spec": {
    "plugin": "grafana-testdata-datasource",
    "enabled": true
  }
}
```

 - `POST /apis/sandboxsettings.grafana.app/v0alpha1/namespaces/default/sandboxsettings`. Body:
```json
{
  "apiVersion": "sandboxsettings.grafana.app/v0alpha1",
  "kind": "SandboxSettings",
  "metadata": {"name":"grafana-testdata-datasouce"},
  "spec": {
    "plugin": "grafana-testdata-datasource",
    "enabled": true
  }
}
```

**Comment by tolzhabayev** [comment]
How flexible is spec and it's validation.

would something like:

```
"spec": {
    "enabled": true,
     "plugin": "grafana-testdata-datasource",   
    "apiAllowList": ["all","network","inputs","window"],
    "apiBlockList": ["window"]
  }
```
be validated and possible to handle errors like `window can not be part of apiAllowList and apiBlockList at the same time?`

**Comment by andresmgot** [comment]
yes, right now there are no examples that define a custom validation but it should be doable.
