### ISSUE TITLE
query_string in Elasticsearch backend

### ISSUE THREAD

**Issue by satishrao84** [grafana/grafana#9402]
hello,
I have an elasticsearch backend, which I use a proxy connection through grafana. Currently the only way to query elasticsearch in grafana (for graphs, tables) is through the use of "query_string". This is currently restrictive and cannot  do nested query of array objects, for example. Is there a way for Grafana to do queries against array objects using query_string or for us to pass the elasticsearch query ?

**Comment by torkelo** [comment]
Currently anything you can do in a lucene ES query you can do. 

Similar to https://github.com/grafana/grafana/issues/3163

**Comment by satishrao84** [comment]
Hi Torkel,
So Lucene ES query would be included in https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

.. and that's all right? There seems to be some confusion as to what a Lucene ES query entails. 

Thanks,
Satish

**Comment by torkelo** [comment]
Yes that is correct, the elasticsearch query string param
