### ISSUE TITLE
[Bug]: grafana error from dashboard "server side error :( Failed to get settings"

### ISSUE THREAD

**Issue by bamb00** [grafana/grafana#9403]
Please include this information:
- What Grafana version are you using?     4.4.1
- What datasource are you using?     prometheus
- What OS are you running grafana on?     Debian GNU/Linux 6.0.1 (squeeze)
- What did you do?
     Running Grafana and metrics displaying in dashboard.  Data is querying from prometheus via kubernetes 
- What was the expected result?
     Dashboard running and displaying metrics
- What happened instead?
     1. Error from dashboard "server side error :( " after grafana's up and running for about 15-30 min and in the Grafana container the files and folder (grafana.db, plugins, sessions) in /var/lib/grafana and grafana.ini is deleted.
     2. Logs (/var/log/grafana/grafana.log) is not created in container.  Need to understand what is deleting those files and folder in /var/lib/grafana & /etc/grafana.
     3. The "Server side error :( Failed to get settings" error re-occur in the dashboard when the pod get reset
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by bergquist** [comment]
I suggest you look into how the container is running. Grafana does not delete grafana.ini file by itself. Are you mouting a volume for the pod? Is grafana allowed to use it?

**Comment by torkelo** [comment]
closing due to lack of updates
