### ISSUE TITLE
[New Data Source]: TDengine

### ISSUE THREAD

**Issue by kadirmehmetarslan** [grafana/grafana#94042]
### Background

TdEngine

### Use case

TDengine

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sofianeroda** [comment]
Hi there! We already have a TDengine plugin for Grafana: https://grafana.com/grafana/plugins/tdengine-datasource/

Can you clarify what use case you had in mind?
