### ISSUE TITLE
LDAP certificate 

### ISSUE THREAD

**Issue by Murryy79** [grafana/grafana#9404]
Hello:
I can configure the path to ldap certificate in my manifest like this 
# root_ca_cert = "/path/to/certificate.crt"

my question is how do I ship the certificate.crt file to that path. anyone knows the how do to this manifest?

many thanks

**Comment by bergquist** [comment]
You have to provide the file to the server/container yourself. Grafana does not support uploading cert files. We don't know how that could be solved within your environment. ssh:ing to the machine/puppet/anisble?
