### ISSUE TITLE
[Bug] Right Y-Axis scale is not relevent 

### ISSUE THREAD

**Issue by nicolargo** [grafana/grafana#9405]
Hi ,

when i put the Y-Axis to the right with my time/serie, the scale is not relevant:

![image](https://user-images.githubusercontent.com/776747/31113468-bb1a6722-a819-11e7-804a-18c9a2094ed4.png)

Additional information:

- What Grafana version are you using?  Grafana v4.5.0 (commit: 512535e) 
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 7.3
- What did you do? Put the Y-Axis on my second time/serie to the right
- What was the expected result? **Have a scale like: 0 / 0.25 / 0,5 / 0.75/ 1 / 1.25 .... / 2.25**
- What happened instead? 0 / 0 / 1 / 1 / 1 / 1 / 1 / 2 / 2
- If related to metric query / data viz:

**Comment by torkelo** [comment]
strange, did you hard code the decimal count?

**Comment by nicolargo** [comment]
Nope, set to auto.

When i force the Axes/Right Y/Decimals field to 1 (or higher) it works:

![image](https://user-images.githubusercontent.com/776747/31114173-140c2cdc-a81d-11e7-9243-95a450066030.png)

So the workaround is ok for me but it will be nice if the auto value works ;)

**Comment by torkelo** [comment]
I can replicate, thanks for reporting this! looks like null != undefined bugg. 

You can fix it by specifying a decimal in the decimal input (then move focus away from the input). Then remove the decimal option again. This way the option will be saved as null and auto decimal will work as expected.

**Comment by nicolargo** [comment]
Ok ! Thanks for your quick reply and for the workaround.
