### ISSUE TITLE
[Feature request] support read-only mode when using Postgres

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#9406]
- What Grafana version are you using?
4.5.1

- What datasource are you using?
N/A

- What OS are you running grafana on?
RHEL6.4

- What did you do?
Restart Grafana while using Postgres in read-only mode.
Attempt to view a dashboard while using Postgres in read-only mode.

- What was the expected result?
Grafana would start up (possibly with errors in the logs).
Grafana would render the requested dashboard.

- What happened instead?
Grafana would not start up (Fail to initialize orm engine)
Grafana would not show the dashboard (Anonymous access organization error: 'Main Org.': EOF)

**Comment by benthorner** [comment]
https://github.com/grafana/grafana/issues/3676

**Comment by torkelo** [comment]
Not seeing how we can do this, grafana needs to be able to write to database.

Even for read only operations like login and viewing dashboards will require db updates to columns like last login, view counts

**Comment by benthorner** [comment]
We'd like Grafana to behave gracefully in a read-only scenario. So if we use a separate (and resilient) session store like memcache, we would expect Grafana to still give a minimal, read-only user experience, allowing people to view dashboards, login and change organisations without hitting an error screen. That should be possible with a few well-placed exception handlers.

**Comment by benthorner** [comment]
Ideally gathering metrics and other write operations would also work, but they're not essential in the presence of a failure.

**Comment by torkelo** [comment]
This is the first time this requirement has ever come up. It would not be trivial and would complicate things and disable some features. But it's not impossible to support it :) 

We will be sure to evaluate this feature request if there is enough demand for something like this.

**Comment by benthorner** [comment]
Hopefully this won't disable features. We simply want Grafana to cope i.e. continue trying to process the requests instead of just bombing-out - our users don't care if they temporarily can't create dashboards, they mainly want to see ones they've created in the past. 

As Grafana is critical for us, we need it to be resilient. Unfortunately none of the database options for Grafana are truly master-master, so the best we can do at the moment is to switch to a read-only copy, but this doesn't work as above. An alternative DB driver could also be a possible fix.

**Comment by torkelo** [comment]
I think supporting https://github.com/grafana/grafana/issues/3676 sounds like a much better solution to the underlying problem

**Comment by benthorner** [comment]
That's basically what we do at the moment, but we proxy Postgres through a load balancer, which can detect a failure of the master node and redirect traffic to a read-only slave. Postgres only supports a single master, so you would still need to support the above for it to be of any use.

**Comment by torkelo** [comment]
We will take a look why Grafana is not viewable in anonymous mode when db is in read-only mode.

**Comment by benthorner** [comment]
This is only a problem when the user has session data (irrespective of whether it's stored in the same database). Users without session data (i.e. have not logged-in / have nothing in their browser cache) can still view dashboards without any errors. Closing as the new dashboard folders feature should reduce the scenarios where logging in (i.e. having session data) is necessary, at least for us.
