### ISSUE TITLE
Dashboards: No data in dashboard but in explorer

### ISSUE THREAD

**Issue by mporretta** [grafana/grafana#94079]
### What happened?

Hello,

All our queries return No Data in a dashborad but they works in the Explorer, this issued appeared after a connection loss between grafana and the influx DB

thank you

### What did you expect to happen?

Data should appear in the dashboard like in the explorer

### Did this work before?

Yes, it worked before with the same grafana version v11.1.4

### How do we reproduce it?

1. Setup a dashboard with influx DB data
2. Interrupt the connexion between Grafana and influx DB

### Environment (with versions)?

Grafana: v11.1.4
OS: Debian 12
Browser: Edge 129.0.2792.65

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influx DB datasource plugin : 5.0.0 || Influx DB server : 2.7.10

**Comment by aangelisc** [comment]
Hi @grafana/bizapps-orgs 

What exactly do you mean by:
> Interrupt the connexion between Grafana and influx DB

Does the data source health check pass or fail?

**Comment by mporretta** [comment]
Hello,

Sorry I forgot this, Yes the data source health check was failing but for a short amount of time.

But we somehow manage to resolve this issue by recreating all widgets in the dashboard and clearing the cache on our DB

We tried to recreate the bug but we didn't manage to do it

So I think we can close this case.

Thank you for your time, sorry for the inconvenience.

**Comment by aangelisc** [comment]
No worries and thank you for the update @mporretta!
