### ISSUE TITLE
[shore]: remove jsontree component

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9407]
Today we have two json explorer components 

json-tree used when testing alert rules:
https://github.com/grafana/grafana/blob/master/public/app/core/components/jsontree/jsontree.ts
used here:
https://github.com/grafana/grafana/blob/master/public/app/features/alerting/partials/alert_tab.html#L113

and we have json-explorer:
https://github.com/grafana/grafana/blob/master/public/app/core/components/json_explorer/json_explorer.ts

used here: 
https://github.com/grafana/grafana/blob/79b873e40ee3366444c4076940e399795ef645d0/public/app/features/panel/query_troubleshooter.ts#L150

Would like to get rid of the first one (jsontree), so we only use the json explorer component.

**Comment by Ijin08** [comment]
Fixed with #9416
