### ISSUE TITLE
Change default text colour (for UI Theme and timezone selection) to white for better UX

### ISSUE THREAD

**Issue by nd-rw** [grafana/grafana#9410]
Greyed text typically indicates that the option is unavailable/non-editable (screenshot attached).
**Version/platform:** Grafana 4.5.2, Chrome (latest)

![image](https://user-images.githubusercontent.com/25862553/31124259-3fd0e17e-a876-11e7-89c1-37fb076acd0b.png)

**Comment by torkelo** [comment]
not sure about this, greyed text is also very common for "placeholder"  / default value.

**Comment by nd-rw** [comment]
I [disagree ](https://en.wikipedia.org/wiki/Grayed_out)but irregardless why have the _home dashboard_ option be a lighter shade?

**Comment by aocenas** [comment]
This does not seem relevant anymore as the page was redesigned.
