### ISSUE TITLE
Split the unified_alerting flags to be able to keep the alerting UI component in read-only state

### ISSUE THREAD

**Issue by sa4breeze** [grafana/grafana#94105]
**Why is this needed**:

Related: https://github.com/grafana/grafana/issues/92707 and https://github.com/grafana/grafana/pull/94023

When the alertmanager hits into panic during upgrades, the work-around is to keep unified_alerting = false in grafana.ini and restart the service. 

This sort of work-around causes a side-effect and adds 2 problems:
a. Existing alerts that were configured on the grafana service for orgs or for admins becomes entirely hidden and unusable. An end-user at that point (users of an org or service admin) cannot view if the alerts are still intact. 
b. There is no way to intepret the state of the existing or configured alerts prior to the panic error. 

**What would you like to be added**:

Split the unified_alerting flag to 2 separate flags
_This flag can retain existing behavior and be used to prevent new alerting changes and alert manager from being triggered._

> **unified_alerting = true | false**

_This new flag would allow Grafana Alerting in the UI tab to be in read-only state._

> **unified_alerting.ui.read_only = true | false**

**Who is this feature for?**
- Org users and service admins using grafana who have configured alerts via the Alerting SubSystem.

Any subcomponent that gets directly blocked from flags in the .ini file needs to be split, so the existing settings on the UI can be read-only rather than being removed or hidden entirely.

** How to reproduce **:
- Start service with any of the recent grafana version - grafana/grafana >= 11.1.0, >= 11.2.0 or (the non-public version) grafana/grafana-dev with 11.3.0.
- Set **unified_alerting = true** in **grafana.ini**. Login to grafana UI. Create an org, configure a basic test alert with basic alert_rule.
- Set the **unified_alerting = false** in the **grafana.ini** file.
- Restart the service and log back in. The entire Alerting component interface on the UI is hidden.

For an org user (with admin role to configure alerts) or service admin who configured the system level alerts, this presents an issue whether the alerts are now lost, whether the alerts got corrupted during the upgrade or have been removed following the service restart.

From maintainability standpoint, the UI sub-system of Alerting in Grafana could be better having its own flag.

** Affects versions **:
>=11.1.0, >=11.2.0, >=11.3.0

**Comment by JacobsonMT** [comment]
Both related issues you linked above have since been fixed. If this request is still needed, could you elaborate on the "why" behind the feature?

**Comment by sa4breeze** [comment]
Hi @JacobsonMT,
Thank you for addressing the fix for the panic error. This request can be RFE, given that the immediate issue has been fixed on alertmanager for registered alerts. 

The dependence of single flag for alerting sub-component could cause alertmanager panic and blocks the service from start. Separating the flag behavior will help in keeping grafana to start in a safe mode, while keeping the alert rule to be visible.

- The use of unified_alerting can be used to enable or disable the alert triggers. 
- The unified_alerting.ui.read_only flag is to allow the existing user configured alerts to view in read-only state as the UI will be accessible. i.e. To perform safe start of the service and invocation of the alert triggers are disabled.
