### ISSUE TITLE
new metrics_tab doesn't respect QueryOptionsCtrl class from datasource.

### ISSUE THREAD

**Issue by Kotove** [grafana/grafana#9411]
Seems like 

```
<div class="gf-form-group">
  <rebuild-on-change property="ctrl.panel.datasource" show-null="true">
    <plugin-component type="query-options-ctrl">
    </plugin-component>
  </rebuild-on-change>
</div>

```
was lost during migration from metrics.html to metrics_tab.html

I see that now graphite datasource has it's own hardcoded query options, which were previously located in QueryOptionsCtrl class. 

Please include this missing <plugin-component> to metrics_tab.html

**Comment by torkelo** [comment]
This plugin component/extension point was removed in 4.5, replaced with query option flags set in the plugin.json 

minInterval 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/plugin.json#L12

or max data points are available:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/plugin.json#L15

you can also add data source help to the metrics tab by adding a query_help.md file 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/query_help.md 

The query options can be accessed by clicking on the options link on the top row to the right 

<img width="1264" alt="screen shot 2017-10-03 at 20 22 51" src="https://user-images.githubusercontent.com/10999/31141807-b0d024f0-a878-11e7-8cf6-a0a487014ae9.png">

**Comment by gavol** [comment]
Hello,

is there any preferred and/or suggested way to add custom options? It looks like now we are limited to few of them already defined a-priori. In my organization we have a custom data-source that takes additional options and the QueryOptionsCtrl was working just fine. The removal of that controller is actually creating issues to move to the latest Grafana versions.

Thanks for your great work!

**Comment by torkelo** [comment]
what options did you set in the options controller? cant you set those on the query (target model)? 

The only options that could be set from the options controller was, panel.maxDataPoints, panel.interval and panel.cacheTimeout  as those where the only options that was passed from the panel to the data source in the query call. And all those can still be set (if you enable them in plugin.json).

**Comment by gavol** [comment]
Thanks for your fast reply, very appreciated.

We have specific options at the level of the graph, and not of the single data query. For instance we can ask the data source for different data formats, allowing the data server to send additional information that our plug-in processes before returning time-series data to the Grafana's core.

**Comment by torkelo** [comment]
@gavol but that is not possible as there those options are not sent to the data source in the query. 

https://github.com/grafana/grafana/blob/master/public/app/features/panel/metrics_panel_ctrl.ts#L220

```javascript
 var metricsQuery = {
      timezone: this.dashboard.getTimezone(),
      panelId: this.panel.id,
      range: this.range,
      rangeRaw: this.range.raw,
      interval: this.interval,
      intervalMs: this.intervalMs,
      targets: this.panel.targets,
      maxDataPoints: this.resolution,
      scopedVars: scopedVars,
      cacheTimeout: this.panel.cacheTimeout
    };

    return datasource.query(metricsQuery);
```

that is everything sent to data source in query. 

> specific options at the level of the graph,

What specific options? And how do you get them from the data source?

**Comment by gavol** [comment]
Yes, but we have our own implementation of the "query" function in our data-source plug-in. And there we attach any additional information we need to the "metricsQuery" object.

We use the same schema, for instance, to override the max number of data-points dashboard-wide with a template parameter. Or, as an additional example, to pass the name of the user to the data-source server.

I cannot exclude we were actually abusing the QueryOptionsCtrl.

At the same time it is not clear to me why restricting users to a few parameters (max data points, min interval, cache timeout, ...) while before it was possible to add any possible option (or, at least, that is what we managed to do using the QueryOptionsCtrl).

Here is a snapshot of the additional parameters we have added to our metrics tab:

![queryoptions](https://user-images.githubusercontent.com/34028214/33277366-a2090f90-d398-11e7-886c-9aa1a4bcb25d.jpeg)

As you can see, they are just 2 or 3 parameters, but they are quite useful to us.

**Comment by torkelo** [comment]
How do you add the information? Do you have a custom build of grafana with a modified metrics panel ctrl?

Anyway the query options plugin extension is not coming back, it was mean to set those settings and show datasource help, feature you can still do. 

Since you can mix datasource (using mixed data source) this option component did not make sense and we provided other ways to set these options and help can be specified by adding a query markdown file to plugin root.

Sorry that this is preventing you from upgrading, not sure what we can do to help. Maybe what you want to accomplish (dashboard wide datasource options) can be done some other way?

**Comment by gavol** [comment]
> How do you add the information? Do you have a custom build of grafana with a modified metrics panel ctrl?

Not actually. We have just followed the instruction (and being inspired by the other available plug-ins) about how to write a custom data source. I will try to give some code examples in the followings.

This is an extract of the _query_ function on our data-source:

```
query(options) {
    .....
    // Here we get the reference string 
    let stringSet = {
         isString : options.targets[0].isStringToMatch,
         targetString : options.targets[0].whichStringsToMatch
    };
    ...
   // And then we make the call to our data-source 
   return server.getData(..., stringSet, ...);
}

```
Here is the corresponding section in the partial html:

```
<section class="grafana-metric-options"> 
   <div class="gf-form-inline">  
         <span>
           <a   class="gf-form-label"
              ng-click="ctrl.stringsReferenceDisabled = !ctrl.stringsReferenceDisabled; ctrl.panelCtrl.isString(!ctrl.stringsReferenceDisabled); ctrl.panelCtrl.refresh()"
              bs-tooltip="'match the value returned with the input field one'" role="menuitem">
            <i id="reference" ng-class="{'fa fa-file-o': !ctrl.stringsReferenceDisabled, 'fa fa-file-text-o': ctrl.stringsReferenceDisabled}"></i>            
           </a> 
         </span> 
         <span class="gf-form-label" ng-style="{ 'pointer-events': 'none' }">  
          Reference String:
        </span>
         <span> 
         <input type="text" 
                 class="gf-form-input" 
                 ng-disabled="!ctrl.stringsReferenceDisabled"
                 ng-model="ctrl.panelCtrl.panel.targets[0].whichStringsToMatch"
                 bs-tooltip="'write the reference string to match'" 
                 data-placement="right"
                 ng-model-onblur ng-change="ctrl.panelCtrl.whichStrings(ctrl.panelCtrl.panel.targets[0].whichStringsToMatch); ctrl.panelCtrl.refresh()" 
                 spellcheck='false' 
                 placeholder="{{ctrl.panelCtrl.panel.targets[0].whichStringsToMatch.join() || 'string'}}">
         </input>
         </span>
       <div class="clearfix"></div> 
   </div>
</section>
```
And then in our query controller we have something like:

```
    this.panelCtrl.isString = function(value) {
      _.each(this.panel.targets, function(target){
        return target.isStringToMatch = value;      
      });
    };

    this.panelCtrl.whichStrings = function(strings) {      
      let stringsList = strings.split(',');
      _.each(this.panel.targets, function(target){
        target.whichStringsToMatch = [];
        return _.each(stringsList, function(string){
          return target.whichStringsToMatch.push(string);
        });        
      });
    };

```

> Maybe what you want to accomplish (dashboard wide datasource options) can be done some other way?

I think we would manage to do the same things if it was possible to set a parameter that is in common to all the "query rows". That is actually what the pre-defined options are (like max data points, or maybe I am wrong in this?). Since you allow for custom data sources, it does not look too strange to me allowing custom options too.

What if I need to pass the "foo" option to my data source? At the moment the only solution I see is to have a custom build and add "foo" to the list of allowed options.

**Comment by torkelo** [comment]
ok, so your using first query model as a way to set and pass options that are valid for all queries. You can still do that from the query ctrl if you need to.

**Comment by gavol** [comment]
> You can still do that from the query ctrl if you need to.

Do you have an example for that? Thanks.

**Comment by torkelo** [comment]
just do what you did from the options panel (panelCtrl.targets[0].)

**Comment by gavol** [comment]
Yes, but I would like to avoid having the option defined in every row. So, let me formulate my question better: is there a way to specify options in the metric panel that are somehow "detached" from the query rows? I think I have tried in the past but every option was repeated for every query.

**Comment by torkelo** [comment]
no sadly there is not and there was never been a way to do this (beside maxDataPoints, interval and cacheTimeout).

**Comment by gavol** [comment]
Thanks. Is that something that eventually could be implemented or the general design does not allow it?

**Comment by torkelo** [comment]
currently the design & plugin component hooks do not allow it. If there is demand & good reasons to add it then maybe in a future version
