### ISSUE TITLE
influxdb templating query always returns timestamp

### ISSUE THREAD

**Issue by arifA9** [grafana/grafana#9414]
I am using Grafana to generate diagram , Inflexdb for storing data, I need to store some data in variable using templating, but query of templating always return time stamp. Any suggestion
![image](https://user-images.githubusercontent.com/32505944/31162044-c42f7e26-a8f8-11e7-8f10-f51ae371b69f.png)

**Comment by bergquist** [comment]
Please post further questions on https://community.grafana.com/

Its very hard to see exactly what to do without knowing the data structure. But you most likly want to write another query using `SHOW TAG KEYS` or `SHOW TAG VALUES` ex http://docs.grafana.org/features/datasources/influxdb/#query-variable

**Comment by torkelo** [comment]
open feature request to support SELECT queries in templating, https://github.com/grafana/grafana/issues/5013
