### ISSUE TITLE
[Bug] "Invalid dimensions for plot, height=0" in single page application

### ISSUE THREAD

**Issue by Apollon77** [grafana/grafana#9415]
Please include this information:
*- What Grafana version are you using?* 4.5.2
*- What datasource are you using?* influxDB
*- What OS are you running grafana on?* Ubuntu 16.04 on AMD64
*- What did you do?*
I embedd some Grafana Panels in a one page home visualisation page (ioBroker VIS) using IFrame. The home visualisation allows to create multiple views and change between them and such, but in the end generates one big "one page" html. So some parts of the page are invisible and normally there are the parts with the charts on it.
When I now switch to these "views" and they become visible I often get the error attached here:
![img_4854](https://user-images.githubusercontent.com/11976694/31163381-6f68d1d2-a8e2-11e7-8a73-50409183b5e0.jpg)
![img_4855](https://user-images.githubusercontent.com/11976694/31163382-6f6b0db2-a8e2-11e7-8804-ef5a8bfd0bdf.jpg)

Can it be that because the part is "invisible" at rendering he get's wrong detail for "height"? Can I specify/overwrite the "Height" manually somehow?

Thank you!

**Comment by torkelo** [comment]
whats your iframe options & dimensions & url?

**Comment by Apollon77** [comment]
The following HTML is generated:

```
<div class="vis-widget " style="top: 79px; left: 14px; width: 996px; height: 200px; overflow: hidden;" id="w00430">
    <div class="vis-widget-body">
        <div></div>
        <iframe src="http://nuc1:3000/dashboard-solo/db/klima-and-temperaturen-draussen?orgId=1&amp;panelId=1&amp;from=now-32h&amp;to=now&amp;_vis_refts=1507140733693" style="position: absolute; border: 0px none; padding: 0px; margin: 0px; width: 100%; height: 100%; overflow: hidden;" seamless=""></iframe></div>
    </div>
</div>
```

**Comment by daniellee** [comment]
@Apollon77 have you tried setting the height (and width) attribute on the iframe element instead of on the div?

See iframe docs on MDN:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by Apollon77** [comment]
I can try to try it :-)

**Comment by Apollon77** [comment]
It happend when the IFrame contant was loaded while the iframe element itself was marked "invisible", because then the height is 0 ...
We now solved it by reloading the iframe content as soon as it changed to visible ... so you can decide if you want to close this or how you want to handle it.
