### ISSUE TITLE
[Bug]: Support template variable in region field when doing dimension lookup queries. 

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#9418]
A dashboard with only this template variable:

![image](https://user-images.githubusercontent.com/94327/31176925-25f4e140-a91d-11e7-9e8a-d2b25d84adda.png)

And simple graph with CloudWatch query, where region is parameterized:

![image](https://user-images.githubusercontent.com/94327/31177039-74a33b52-a91d-11e7-910d-638eb339d163.png)

`PUSH/ew1-push-ci` is a custom namespace, that is enabled in datasource config. Everything works when I choose region from dropdown (e.g. `eu-west-1`), but if I try to use template variable (`$region`), clicking on `+` to add dimensions (or trying to select metric after namespace selection) yields following errors in JS console:

```
boot.de7c040d.js:60 POST http://MY_HOST:3000/api/datasources/proxy/3 500 (Internal Server Error)
(anonymous) @ boot.de7c040d.js:60
w @ boot.de7c040d.js:60
k @ boot.de7c040d.js:60
i @ boot.de7c040d.js:61
(anonymous) @ boot.de7c040d.js:61
$eval @ boot.de7c040d.js:61
$digest @ boot.de7c040d.js:61
$apply @ boot.de7c040d.js:61
h.source @ boot.de7c040d.js:31
p.lookup @ boot.de7c040d.js:31
(anonymous) @ boot.de7c040d.js:31
dispatch @ boot.de7c040d.js:57
q.handle @ boot.de7c040d.js:57
boot.de7c040d.js:60 Possibly unhandled rejection: {"data":{"message":"Unable to call AWS API"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/3","data":{"action":"__GetDimensions","region":"$region","parameters":{"namespace":"PUSH/ew1-push-ci"}},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error"}
```

And in Grafana server logs:

```
t=2017-10-04T13:06:00+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=8 orgId=1 uname=musttu error="RequestError: send request failed\ncaused by: Post https://monitoring.$region.amazonaws.com/: Service Unavailable"
t=2017-10-04T13:06:00+0000 lvl=eror msg="Request Completed" logger=context userId=8 orgId=1 uname=musttu method=POST path=/api/datasources/proxy/3 status=500 remote_addr=1.2.3.4 time_ms=389 size=36 referer="http://MY_HOST:3000/dashboard/db/musttu-test?panelId=1&fullscreen&edit&orgId=1&editview=templating"
```

Seems like it's calling `https://monitoring.$region.amazonaws.com` and not replacing the actual region value there.

Parameterizing region like this does work when you use *default* (e.g `AWS/*`) namespaces.

Grafana 4.5.1 (Ubuntu 16.04), using CloudWatch datasource. Windows/chrome client.

Note, related to (but not duplicate): https://github.com/grafana/grafana/issues/8917

**Comment by tuukkamustonen** [comment]
And to clarify: it's just the query editor that fails to populate the field dropdowns here - if you manually choose correct dimensions, the graphs are drawn just ok.

**Comment by mtanda** [comment]
Sorry, I forgot to use templateSrv.replace().
https://github.com/grafana/grafana/blob/v4.5.1/public/app/plugins/datasource/cloudwatch/query_parameter_ctrl.js#L104
https://github.com/grafana/grafana/blob/v4.5.1/public/app/plugins/datasource/cloudwatch/datasource.js#L157

In latest master, it should work.
https://github.com/grafana/grafana/blob/0c31c7b10619088784bd28b31a4948e43d05d2bf/public/app/plugins/datasource/cloudwatch/datasource.js#L173

**Comment by tuukkamustonen** [comment]
@mtanda Thanks good to know. However, I can't find CHANGELOG entry for this fix? Worth adding?

**Comment by mtanda** [comment]
Yes, I think so.

@torkelo Sorry for taking your time. Would you add this fix to changelog?
