### ISSUE TITLE
[Bug] OAuth settings conflate TLS client auth with specifying a TLS CA

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#9419]
Please include this information:
- What Grafana version are you using?

4.5.1

- What OS are you running grafana on?

Linux

It's not possible to specify a user-supplied TLS certificate authority (CA) certificate without enabling TLS client authentication in the OAuth settings:

https://github.com/grafana/grafana/blob/0c31c7b10619088784bd28b31a4948e43d05d2bf/pkg/api/login_oauth.go#L84-L109

It should be possible to either enable TLS client authentication or specify a CA or do both.

Found while looking into #9373.

**Comment by bergquist** [comment]
Sigh. Yes

Thank you for looking into this.

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9378
