### ISSUE TITLE
show graph in full screen mode with one click

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#942]
Currently it takes two clicks to switch a graph to full screen. Conversely, getting out of full screen takes only one click, or only one key press.

It would make Grafana a lot more useful for quick digging into the data if you could switch a graph quickly to full screen, via one single click. E.g., have a "full screen" icon or button hanging off the corner of the graph, or something like that.

I guess the issue is that the graph title drop down menu now has a dual purpose: configure the graph, and change the way it's displayed. From a usability standpoint, this is a bit confusing. The menu should have one purpose only - configure the graph. The fullscreen command should be moved somewhere else, since it's display oriented, not configuration oriented.

**Comment by mbarragan** [comment]
+1

Would it be possible to show the legends below the graph only in full screen mode?

**Comment by torkelo** [comment]
This is possible with using the v or e hotkeys (while hovering over the graph). 

Might introduce some way to do this in the future
