### ISSUE TITLE
Prometheus: Query editor crashes in response to invalid query

### ISSUE THREAD

**Issue by NWRichmond** [grafana/grafana#94219]
## What's happening?

When querying Prometheus in Explore with the following work-in-progress query:
```
histogram_count(0,sum by (le) (increase(duration_seconds{deployment_environment=~\"someEnv\", span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"someService\"} [$__range])))
```
, the query editor crashes:

![Image](https://github.com/user-attachments/assets/782a44c2-eb87-4037-8b78-2aed270b388e)

## What's the expected behavior?

Instead of crashing, the query editor should provide users with feedback about issues with the query:

![Image](https://github.com/user-attachments/assets/04c32db1-6c82-436b-90cc-d822352a98ed)

## Why is this happening?

In `packages/grafana-prometheus/src/querybuilder/operationUtils.ts`:

https://github.com/grafana/grafana/blob/4623a6471bf77036ea3f0f17b0ff4e94272bb01a/packages/grafana-prometheus/src/querybuilder/operationUtils.ts#L96-L105

, it's possible for `def.params` to be an empty array. In that case, the check for `paramDef.type === 'string'` is problematic.

## How to fix?

Add some optional chaining to the `paramDef.type` check. A higher-level unit or integration test could help to guard against future regressions.

While we're at it, we could marginally improve clarity & performance by using string interpolation instead of concatenation when returning the quote-wrapped `value`:

```ts
function renderParams(model: QueryBuilderOperation, def: QueryBuilderOperationDef, innerExpr: string) {
  return (model.params ?? []).map((value, index) => {
    const paramDef = def.params[index];
    if (paramDef?.type === 'string') {
      return `"${value}"`;
    }

    return value;
  });
}
```

**Comment by vimalgattani** [comment]
I'd like to work on this.
Can you assign this to me?

**Comment by smeet07** [comment]
Can I take up this issue?

**Comment by devluisrodrigues** [comment]
Hey, can I try help on this issue?

**Comment by itsmylife** [comment]
@smeet07 @devluisrodrigues Feel free to work on it and send us a PR. We'd be happy to review and merge it eventually.

**Comment by devluisrodrigues** [comment]
Okay, thanks! I just opened a PR to fix the issue. It's my first time working on open projects, and I hope everything is okay

**Comment by ayushmatkar** [comment]
Is this issue solved? If not i can work on it !
