### ISSUE TITLE
[Bug] Problem with Y-axis:2 scaling in version 4.5.2

### ISSUE THREAD

**Issue by gregvolk** [grafana/grafana#9422]
Running 4.5.2 (commit: ec2b0fe) and seeing this:

![right-y](https://user-images.githubusercontent.com/13316371/31184039-ee5b25ac-a8ed-11e7-8daa-3c46627d34ed.png)

![image](https://user-images.githubusercontent.com/13316371/31184856-2e947018-a8f0-11e7-998f-03310ebddb11.png)

I am able to reproduce the problem with Chrome 61, Firefox 50, and IE11.

>- What Grafana version are you using? 4.5.2 (commit: ec2b0fe), standalone binaries
>- What datasource are you using? Graphite
>- What OS are you running grafana on? RHEL7
>- What did you do? Display Override, Y-axis:2
>- What was the expected result? Scale would be correct.
>- What happened instead? Scale is incorrect.

If I take away the y-axis:2 display override, the left-axis scales correctly:
![image](https://user-images.githubusercontent.com/13316371/31184362-d446dd2c-a8ee-11e7-84bc-bfd6e4f47198.png)

**Comment by torkelo** [comment]
this is indeed a bug, was reported earlier today in https://github.com/grafana/grafana/issues/9405#issuecomment-333762736 

See that comment for a temp workaround
