### ISSUE TITLE
[BUG] - Grafana Executes Code Returned from Influxdb Tag Value

### ISSUE THREAD

**Issue by codylewandowski** [grafana/grafana#9423]
Please include this information:
- What Grafana version are you using?
4.4.3 (will try to run on latest version as well when I have time)

- What datasource are you using?
InfluxDB (v1.3.5)

- What OS are you running grafana on?
Centos

- What did you do?
A metric is sent to Influx with code contained within the tag value such as below
```
website,api_name=<SCRIPT>alert('Vulnerable')</SCRIPT>.jsp result=0 1465839830100400200
```
In a Grafana dashboard the metric is selected, followed by the tag key api_name. Then, the 'select tag value' box is clicked.

- What was the expected result?
Grafana should return a list of all of the strings contained within the Influx tag key and not execute code.

- What happened instead?
Grafana executes the code and does not return any results (as pictured)
![grafana_execute_issue](https://user-images.githubusercontent.com/10121824/31196814-ad2eac3a-a914-11e7-9dd8-469718065de1.jpg)
.

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap!
