### ISSUE TITLE
[Bug] The Grafana editor seems to generate faulty SQL syntax when using mysql functions in the argument to the $__timeFilter() function.

### ISSUE THREAD

**Issue by mr2web** [grafana/grafana#9424]
- What Grafana version are you using?
     v4.5.2 (commit: ec2b0fe)

- What datasource are you using?
     MySql

- What OS are you running grafana on?
     Ubuntu 16.04 LTS

- What did you do?
     Tried to do a time zone conversion in my query as my data is stored in UTC format. The $__timeFilter() function in the WHERE clause seems to output faulty SQL syntax. It seems not to be able to handle MySql functions in its argument. Here is the grafana editor query:
`SELECT
  UNIX_TIMESTAMP(convert_tz(last_updated,"etc/UTC","Europe/Stockholm")) as time_sec,
  state as value,
  entity_id as metric
FROM states
WHERE $__timeFilter(convert_tz(last_updated,"etc/UTC","Europe/Stockholm")) AND entity_id IN("sensor.inside_humidity")
ORDER BY last_updated ASC`

- What was the expected result?
     I expected to get the following SQL query to ge generated:
`SELECT
  UNIX_TIMESTAMP(convert_tz(last_updated,"etc/UTC","Europe/Stockholm")) as time_sec,
  state as value,
  entity_id as metric
FROM states
WHERE convert_tz(last_updated,"etc/UTC","Europe/Stockholm") >= FROM_UNIXTIME(1506974018) AND convert_tz(last_updated,"etc/UTC","Europe/Stockholm") <= FROM_UNIXTIME(1507146818) AND entity_id IN("sensor.inside_humidity")
ORDER BY last_updated ASC`

- What happened instead?
     Got the following SQL query generated which is not valid SQL syntax in the WHERE clause:
`SELECT
  UNIX_TIMESTAMP(convert_tz(last_updated,"etc/UTC","Europe/Stockholm")) as time_sec,
  state as value,
  entity_id as metric
FROM states
WHERE convert_tz(last_updated,"etc/UTC","Europe/Stockholm" >= FROM_UNIXTIME(1506974018) AND convert_tz(last_updated,"etc/UTC","Europe/Stockholm" <= FROM_UNIXTIME(1506974018)) AND entity_id IN("sensor.inside_humidity")
ORDER BY last_updated ASC`

**Comment by daniellee** [comment]
Duplicate: #8411

I think this is something to do with the regex parsing used here. But in this case, instead of using the  $__timeFilter function you can quite easily build your own function using the other macro functions: `$__timeFrom()` and `$__timeTo()`.

**Comment by austinbutler** [comment]
That does seem to work, FYI.

```sql
WHERE CONVERT_TZ(Created,'America/Los_Angeles','UTC') >= $__timeFrom() AND CONVERT_TZ(Created,'America/Los_Angeles','UTC') <= $__timeTo()
```
