### ISSUE TITLE
alertnotifier:Pushbullet alerting

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#9425]
It would be cool if Grafana supports pushing alerts to the Pushbullet service, yet another notification push service connecting multiple devices together with a single account, similar to pushover. The API docs can be found [here](https://docs.pushbullet.com/).

**Comment by mayli** [comment]
Seems pretty easy to implement.

**Comment by bergquist** [comment]
This would have to wait for https://github.com/grafana/grafana/issues/6841 unless its get an extreme amount of up votes.

**Comment by Fusl** [comment]
Mind adding P4 as label?

**Comment by tholu** [comment]
This would be really nice to have, the service and subscription model seems superior to Pushover.

**Comment by GainfulShrimp** [comment]
Pushbullet is great.  I'm eagerly awaiting this feature!

**Comment by JDrakeC** [comment]
Yes please!

**Comment by tholu** [comment]
I found Telegram is the much better option for mobile notifications.

**Comment by mattyyey** [comment]
i know its old - but i wouldnt mind official support for pushbullet - I'm looking at using a webhook to do it myself atm.

**Comment by ziplock9000** [comment]
Yes please.

**Comment by pheetr** [comment]
This would be great to have.

**Comment by armandgrillet** [comment]
Grafana Alerting uses the Prometheus Alertmanager, please submit an issue/PR against https://github.com/prometheus/alertmanager for this feature. In the meantime, you can use webhooks + some proxy to do this.
