### ISSUE TITLE
Alerting: Cloudwatch data source with Code editor doesn't work for new alert style

### ISSUE THREAD

**Issue by jwreford99** [grafana/grafana#94250]
### What happened?

I tried to make a new alert using AWS search syntax and the reduce/threshold logic:
![Image](https://github.com/user-attachments/assets/e435b7d4-5f8f-4da2-8227-96ec531d82cf)

But when I saved it, it errored out and didn't work with the following error:
![Image](https://github.com/user-attachments/assets/420bbbc1-fdb3-42aa-a7fa-4a1eb96984eb)

I looked in the logs but I couldn't find any related log messages

### What did you expect to happen?

My expectation was that it would not error out and would be able to successfully alert as I would expect. 

### Did this work before?

It seems to work using classic conditions, but when I use that I can't get access to the queue names in any way from the message template which means the alert is hard to interpret, as there can be a number of different queues which could experience this problem

### How do we reproduce it?

AFAICT, this seems to happen for any query with Cloudwatch SEARCH syntax. 

1. Setup an AWS account with multiple AmazonMQ queues or multiple EC2 instances
2. Connect that account to Grafana
3. Try making an alert with syntax like `SEARCH(' {AWS/EC2,InstanceId} MetricName="CPUUtilization" ', 'Average', 300)` or `SEARCH('{AWS/AmazonMQ,Broker,Queue} MetricName="QueueSize",  'Average', 300)`
4. Try using the reduce and threshold expressions

The alert should go into an error state

### Environment (with versions)?

Grafana: Grafana v10.4.3 (0bfd547800)
OS: My machine is Windows
Browser: Chrome Version 129.0.6668.90

### Grafana platform?

Kubernetes

### Datasource(s)?

Cloudwatch

**Comment by kevinwcyu** [comment]
Hi @jwreford99, can you try a version of Grafana that is at least v11.1.1 or above? There was a [fix](https://github.com/grafana/grafana/pull/88943) that should hopefully address this.

**Comment by jwreford99** [comment]
Ah sorry I hadn't seen that @kevinwcyu, that looks exactly like my issue, so I suspect it will solve it. I'm afraid I can't easily get onto the new version, but I am happy to say it is likely this is fixed. Thanks for taking a look at this
