### ISSUE TITLE
Select which fields to show from a query by templating

### ISSUE THREAD

**Issue by laimaretto** [grafana/grafana#9426]
Hi,

I have the following query which is working fine.

![image](https://user-images.githubusercontent.com/8891825/31201161-08b453e2-a934-11e7-99ba-3d62b97d16be.png)

The query plots the throughput of a given port ($port_name) in a given router ($ip_system). Both the port and router are selected via variables/templating. So far, so good ...

Now I want to be able to select which throughput to plot, either only TX, only RX, or both.

How can I accomplish that? I've been thinking how to use variables in this but could not find a solution.

Any ideas?

Thanks!

Lucas

**Comment by laimaretto** [comment]
Ok. So I've read #6248 and got to reference fields from a variable. The workaround was to manually editing the query.

`SELECT sum(/^$dirThput$/)  FROM "stats_Ports" WHERE ("ip_system" =~ /^$ip_system$/ AND "port_name" =~ /^$port_name$/) AND $timeFilter GROUP BY time(15m), "port_name"`

The issue I'm facing now is with subqueries. If I try to replicate this workaround, I get no points. My queries are:

```
innerQ = SELECT MAX(/^$dirRate$/) FROM "stats_Ports" WHERE "ip_system" =~ /^$ip_system$/ AND "port_name" =~ /^$port_name$/ AND $timeFilter
GROUP BY  time(60m), "port_name"
outerQ = SELECT MEAN(/^$dirRate$/) FROM ( innerQ ) WHERE $timeFilter GROUP BY time(60m), "port_name"
```

So my inner, alone, query works so far. The problem is when I stick them both together.

Any ideas on this?

Thanks!

**Comment by torkelo** [comment]
Please use community site for questions https://community.grafana.com
