### ISSUE TITLE
[Feature request] Allow control over query intervals

### ISSUE THREAD

**Issue by codeaholics** [grafana/grafana#9427]
- What Grafana version are you using?
4.4.3

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux

- What did you do? (...etc...)

I have a measurement with points every 30 seconds. If I zoom out to, say, a year, my screen resolution is such that a time series graph has enough pixels to render buckets 6 or 12 hours in size. I would like the buckets to be 1 day, or sometimes 7 days. Right now, I can't see a way to control this beyond using the "Group by time interval" setting, but of course when I'm zoomed down to the last 3 or 6 hours (my normal view), a "group by time interval" of ">1d" is of no use whatsoever!

It would be good to have a selector (drop down or similar) in the header bar alongside the auto refresh, zoom, etc. to select the interval size.

**Comment by torkelo** [comment]
You can create a template variable of type interval and use that in the group by time, the  you can  control it more

**Comment by codeaholics** [comment]
Thank you for the pointer. Could you explain in a bit more detail or point me at some documentation, please? I've been looking for this for some time and haven't found anything like this.

**Comment by daniellee** [comment]
@codeaholics you probably have already figured this out but here is an example dashboard with an interval template variable: http://play.grafana.org/dashboard/db/influxdb-group-by-time?panelId=1&fullscreen&edit&orgId=1
