### ISSUE TITLE
Nested type query for Elasticsearch

### ISSUE THREAD

**Issue by satishrao84** [grafana/grafana#9428]
- What Grafana version are you using? 4.5.1
- What datasource are you using? Elastisearch 5.6.1
- What OS are you running grafana on? MacOS

I saw on issue  [4693](https://github.com/grafana/grafana/issues/4693) that Nested aggregations were possible (from the screenshots). My version of grafana does not seem to have a "nested" option. Has it been taken out? Or any plans of bringing it back in, if it has?

**Comment by torkelo** [comment]
As you can  see on that issue it's still an open feature request
