### ISSUE TITLE
User search API : Fail to find user when using email addresses

### ISSUE THREAD

**Issue by Lusitaniae** [grafana/grafana#94296]
### What happened?

I create users where name/email/username are all set to the email of that person: `person1@organization.com`

Recently looks like I can't search the user by email, it returns empty results

When searching users in this page `/admin/users`, searching `person1@organization` works `person1@organization.com` doesn't

```
/api/users/search?perpage=50&page=0&query=person1@organization\.com&activeLast30Days=false
```

Running the API call locally I can see results if I remove the dot escape 

`query=person1@organization.com` ✅  
`query=person1@organization\.com` ❌ 

### What did you expect to happen?

searching users by full username should work `person1@organization.com`

### Did this work before?

yes, not sure where the error started

I'm running 11.1.7 (just upgraded from 11.1.3 while looking at this issue)

### How do we reproduce it?

1. Have an user with name/email/username like user@app.com
2. Search user by full email address on 'Users' page
3. Find no results

### Environment (with versions)?

Grafana: 11.1.7 (and 11.1.3)
OS: Ubuntu 24
Browser: Chrome

### Grafana platform?

None

**Comment by Lusitaniae** [comment]
![Image](https://github.com/user-attachments/assets/90600079-ac9e-47e4-a8f6-f1442d29b89e)
![Image](https://github.com/user-attachments/assets/91c3a5ca-0b57-4efc-b937-2d17c1c18add)

**Comment by aarongodin** [comment]
It took me a bit to realize since I'm typically running MySQL for local dev on Grafana, but this issue only applies to SQLite.
