### ISSUE TITLE
Alerting: Alert stuck in alerting state

### ISSUE THREAD

**Issue by yunusbahari** [grafana/grafana#94298]
### What happened?

Alerting -> Group 

1. We do some infrastructure cleanup in our Cloud which have alert set up in Grafana.
2. The infrastructure Is cleaned up, and alert triggered
3. We expect the alert and Acknowledge it because it is triggered by Infra clean up, and 
4. After triggered, because of the alert is not used anymore we delete the rule.

But after removing the alert the alert seems to be stuck in alerting state
![Image](https://github.com/user-attachments/assets/35d968be-bb7e-4a4e-b3fa-d50376803471)

This is when we try to click `See Source` alert rule button
![Image](https://github.com/user-attachments/assets/dc3f2c85-e907-4c36-8aee-43e59a1deb59)

The Alert groups still persist and it will re-trigger when we update/add notification channel)
Currently we suppressing it until there is proper fix, or we remove it manually from db(?)

### What did you expect to happen?

The alert should be resolved and removed from Group alert when the Alert Rule source is deleted.

### Did this work before?

N/A

### How do we reproduce it?

1. Have alert triggered (our case is NoData Alert)
2. Without fixing the root cause, remove alert rules
3. There is no CTA to delete Alert Group in the dashboard

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Grafana: 10.2.2
OS: Grafana Container from `docker.io/grafana/grafana:10.2.2`, on top of kubernetes running on COS (GKE)
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by JacobsonMT** [comment]
Hi @yunusbahari, I've tried to reproduce this issue in the latest version of Grafana and the alert is resolved (and removed from the Group page) when deleting the Alert Rule.

If possible, upgrading Grafana should help resolve this issue moving forward. In any case, the alert should become stale and auto-resolve after a period of time.
