### ISSUE TITLE
https://github.com/VictoriaMetrics/VictoriaMetrics.git

### ISSUE THREAD

**Issue by moontonMartin** [grafana/grafana#94293]
### Background

https://github.com/VictoriaMetrics/VictoriaMetrics.git

### Use case

https://github.com/VictoriaMetrics/VictoriaMetrics.git

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by josiahg** [comment]
Closing in favor of previous issue / discussion #91687
