### ISSUE TITLE
Silences: Unable to preview matched alerts when creating a new silence on AMP Alertmanager

### ISSUE THREAD

**Issue by pjmoore92** [grafana/grafana#94320]
### What happened?

Since upgrading from 11.2.0 to either 11.2.1 or 11.2.2 we are unable to ~~add~~  preview a silence in Grafana. We use an alertmanager datasource for this which is hosted in Amazon Managed Prometheus.

This is an on-prem deployment of OSS Grafana.

When adding a matcher such as alertname = a

We get an error: 
Error: maxFailure (quorum) on a given error family, addr=<IP> state=ACTIVE zone=eu-west-2b, rpc error: code = Code(400) desc = "bad matcher format: \"alertname\"=\"a\""

Rolling back to 11.2.0 this works fine.

![Image](https://github.com/user-attachments/assets/35c081c6-647f-4467-b230-3ed86093b01d)

### What did you expect to happen?

I expected Grafana to find any firing alerts and show them as items that would be silenced by matcher query, it willl allow me to save that silence but i don't see what alerts i'll be silencing (no preview)

### Did this work before?

Worked in Grafana 11.2.0 and earlier.

### How do we reproduce it?

1. Alertmanager instance added to Grafana using Prometheues or Cortex, where the backend is Amazon Managed Prometheus.
2 Add any alert silence matchers
3. Watch it fail on 'Bad Matchers'

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.1 or later
OS: macOS 15
Browser: Chrome 129.0.6668.90 

### Grafana platform?

Kubernetes

### Datasource(s)?

Alertmanager

**Comment by JacobsonMT** [comment]
Regression possibly related to https://github.com/grafana/grafana/pull/93051, tagging frontend.

In general this issue type is related to `utf8-strict-mode` when combined newer versions of Grafana UI with older versions of prometheus alertmanager (or current version with the flag disabled), see https://github.com/grafana/grafana/issues/89960 for more details.

**Comment by gillesdemey** [comment]
I'm a bit confused about the following; we've managed to track this down to the preview feature being impacted but I haven't failed to create a new silence with either vanilla Alertmanager v0.26.0 (pre-UTF-8 support) or Mimir with `utf8_strict_mode` disabled.

@pjmoore92 could you confirm if _saving_ the silence is also impacted?

The preview should be fixed with https://github.com/grafana/grafana/pull/95067

**Comment by pjmoore92** [comment]
Thanks @gillesdemey - you are correct I'd mistakenly said we couldn't save silences - that's not the case it's only failing to preview them.  Confirmed in 11.3.0 that I could still save a silence even though the preview fails. 

I'll keep an eye out for what release version #95067 makes it into - thank you 🙇🏻
