### ISSUE TITLE
Docs feedback: features/datasources/mysql.md

### ISSUE THREAD

**Issue by shubhamod1** [grafana/grafana#9433]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by bergquist** [comment]
Seems like you just posted the template?
Whats the issue/suggestion?

**Comment by shubhamod1** [comment]
Hey , I started using Grafana (version 4.5) with MYSQL as DataSource . While quering I am able to see graph but the graph is not filtering when using zoom in option or time range given on the Dashboard . It says "Data points outside time range ". So what is the solution. Please reply ASAP.

**Comment by daniellee** [comment]
As I mentioned on another issue, ask this question on the community site. And include more details, please.
