### ISSUE TITLE
Explore: Time ranges coupled

### ISSUE THREAD

**Issue by tab0r** [grafana/grafana#94368]
### What happened?

I was using a split Explore view in Grafana Cloud. I had a time range already set on the left, and wanted to set a different one on the right. When I went back to the left one, it had the time range of the right.

### What did you expect to happen?

The two time ranges stay different.

### Did this work before?

I am not sure.

### How do we reproduce it?

1. Open a split explore view, with any valid range query
2. Set absolute time range on the left
3. Set a different absolute time range on the right
4. Confirm that it was copied into the left

### Environment (with versions)?

Grafana: Current Grafana Cloud- as of 8 October, 2024
OS: Linux
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

not datasource specific

**Comment by ifrost** [comment]
This is expected behavior. Time ranges are synced by default since https://github.com/grafana/grafana/pull/77759. To unsync time ranges you need to click the un/link button:

![Image](https://github.com/user-attachments/assets/7eba199e-6216-4e64-80c8-c7b8eca44576)
