### ISSUE TITLE
Add chained variable support  in  custom variable

### ISSUE THREAD

**Issue by DesireWithin** [grafana/grafana#94363]
Hello, 

I want to use garfana to visualize a `elasticsearch `datasource.
My scenario is to input `IP ` as variables into the query. But `IP` options are derived via `Zone`.
These two variables **are not convenient** to query through `elasticsearch `for some reasons. (Of course it would be handy if the datasouce were Prometheus 😃 )

So I wish I could define three variables:
A dictionary of hidden variables: defines the above relations, similarly
```json
{
    "zone1": [
        "ip1",
        "ip2"
    ],
    "zone2": [
        "ip3",
        "ip4"
    ]
}
```
A `Zone` variable visible on the dashboard, selects a specific zone from the above dictionary,
A `ip` visible on the dashboard, from the dictionary generated by zone, select this ip

**What would you like to be added**:

Let custom variable can use chained variable, or anything else can support my scenario 

**Who is this feature for?**

For Ops in the company.

**Comment by kevinwcyu** [comment]
Hi @DesireWithin,

One way you can do this with custom variables is to create one variable that is a custom variable `zone`, and use the [Infinity data source](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/) to create another variable with a mapping of the zones to IPs. I've attached a screenshot of the setup below. Let me know if this solves your use case.

![Image](https://github.com/user-attachments/assets/e26cd915-cd80-4858-80e2-9b98a9fbb1d2)

![Image](https://github.com/user-attachments/assets/2f4452c8-153c-41c5-a573-112437263c49)

**Comment by DesireWithin** [comment]
Hi @kevinwcyu , thanky you for your detailed explanation and screenshot.
Except for one thing, can you help me?
If  I want to select `all` zone,  how to let `Infinity data` return all ip in the json? 
I tried  set `custom all value` in the `zone` to * or .*, it doesn't work.
![Image](https://github.com/user-attachments/assets/843105c5-8f4e-4f4c-9939-ede27403136e)

And I try to read document of `Infinity data`, I don't find an example.

As a workaround, I have to edit my json like this:
```json
{
    "zone1": [
        "ip1",
        "ip2"
    ],
    "zone2": [
        "ip3",
        "ip4"
    ],
   "all": [
      "ip1",
      "...",
      "ip4"
   ]
}
```
But this will cause Lucene String is too long:
![Image](https://github.com/user-attachments/assets/d6dc0fcf-c58c-4ad1-8efd-0b886411648c)
The best practices is 
` conditions AND ip: *`

**Comment by kevinwcyu** [comment]
@DesireWithin,

could you do something like this:

- Set the `all` property in the infinity data source to `"all": ["*"]`
- Set add `all` as an option in the `zone` variable?

**Comment by DesireWithin** [comment]
Hello @kevinwcyu ,
I tried `ALL` , `all` and `all2` vars:
![Image](https://github.com/user-attachments/assets/80a04e0c-4ebb-46dc-8061-0d360a57824c)

None of these three options gave me what I wanted:
![Image](https://github.com/user-attachments/assets/99e7dad3-8d4d-474b-b4f2-f5098d37f55a)

Am I misconfiguring something?

Here is my json:
```json
{
	"asia": [
		"10.65.8.39",
		"10.65.8.40",
		"10.65.8.41",
		"10.65.8.42",
		"10.65.7.214"
	],
	"europe": [
		"10.65.7.212",
		"10.65.7.213",
		"10.65.7.216",
		"10.65.8.50",
		"10.65.8.100",
		"10.65.8.203"
	]
}
```

**Comment by DesireWithin** [comment]
> [@DesireWithin](https://github.com/DesireWithin),
> 
> could you do something like this:
> 
>     * Set the `all` property in the infinity data source to `"all": ["*"]`
> 
>     * Add `all` as an option in the `zone` variable?

Oh, sorry, I misunderstand what you say.
Yes, I can, 
![Image](https://github.com/user-attachments/assets/1c9593e8-bdc5-46a0-be38-cccfe88b3e92)
![Image](https://github.com/user-attachments/assets/da5694c6-0f9f-49e4-aa20-2b7f93a89490)


However `Multi-value` function will not work, 

Maybe the requirements I proposed are unreasonable, and some compromises should be made? 🤔

**Comment by idastambuk** [comment]
Hi @DesireWithin! Can you clarify what you want to have happen with the "multi-value" in the last screenshot? Do you want the variable to resolve to "*" or something else?

**Comment by DesireWithin** [comment]
Let me summarize my requirements:
1. The IP is determined based on the selection of the zone.
2. Both zones and IPs can be selected `multiple values` or `all` can be selected.
3. When both zone and IP are selected as `all`, the IP resolves to `*`

I don't know if my requirement is reasonable, if not, please close this ticket.

**Comment by idastambuk** [comment]
> [@DesireWithin](https://github.com/DesireWithin),
> 
> could you do something like this:
> 
> * Set the `all` property in the infinity data source to `"all": ["*"]`
> * Add `all` as an option in the `zone` variable?

@DesireWithin this should do what you need.

If you want multiple IPs to show when you select an "All" option in the zone variable, you could do something like this:
<img src="https://github.com/user-attachments/assets/6fe5598e-dc90-4d1a-8ce9-41b8290b91e0" width="300"/>
<img src="https://github.com/user-attachments/assets/84c11385-f8d7-471e-976f-8504f80ab99c" width="300"/>

You could probably play around with it more to get exactly what you want. 

If you want a specific feature of dashboard variables, you could submit a feature request [here](https://github.com/grafana/grafana/issues/new?template=1-feature_requests.md), as this isn't in the domain of Elasticsearch plugin, but the wider variables feature in Grafana. 
I will close this ticket in the meantime, but hope this helps!
