### ISSUE TITLE
How to create uptime and downtime of the service dashboard in the Grafana using App insight availability tests results

### ISSUE THREAD

**Issue by kamathnaveen143** [grafana/grafana#94395]
**Why is this needed**:

Hi Team, 

As we got some customer request to build some monitoring dashboard to see the uptime and downtime of the particular services by using KQL queries.

Below are the prerequisites we have currently:

1. We have provisioned app insight in azure.
2. Created availability tests for the certain endpoints.
3. Also integrated the azure subscription as data source in the Grafana instance.

**What would you like to be added**:

But we tried to create some nice dashboards like below as we will get the status of the services on daily basis (statuspage.io)

![Image](https://github.com/user-attachments/assets/65218494-168e-4cf2-9e9b-1896746bf611)

Couldn't find any good plugins or template to create this kind of similar dashboard, hence if anyone done with some experiments similar to this kindly help us.

**Who is this feature for?**

Enterprise customers

**Comment by aangelisc** [comment]
Hi @kamathnaveen143, I believe you want to use the Bar Gauge visualization with the `Retro LCD` option. See docs [here](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-gauge/). Closing this issue.

**Comment by leeoniya** [comment]
you probably want StatusHistory panel

https://play.grafana.org/d/qD-rVv6Mz/state-timeline-and-status-history?orgId=1&from=now-6h&to=now&timezone=utc
