### ISSUE TITLE
auth.azuread does not work with nested groups

### ISSUE THREAD

**Issue by AurimasNav** [grafana/grafana#94411]
### What happened?

auth.azuread [does not work for nested groups](https://community.grafana.com/t/azure-ad-login-fails-with-nested-groups/110926). This has caused significant troubleshooting time while it could be avoided if documentation would mention it.

### What did you expect to happen?

I expected  Azure AD oauth to work after following the docs - https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#configure-application-roles-for-grafana-in-the-azure-portal

### Did this work before?

No, this was initial setup and it did not work until I made the users direct members for the group.

### How do we reproduce it?

1. Configure Azure AD Oauth
2. Make a user member of group "A", make the group "A" member of group "B"
3. Assign group "B" to the [grafana app role](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#create-the-microsoft-entra-id-application) (Editor or Admin)
4. Login to grafana, go to your profile and check the role assigned, it will be default role "Viewer", or if you enable strict role checking you should get `Login failed
IdP did not return a role attribute, please contact your administrator` when trying to login.
5. To double check, make the user direct member of group "B" and login to grafana, correct role should be assigned.

### Environment (with versions)?

Grafana v11.1.5 (2e2ef4e402)

### Grafana platform?

Kubernetes

**Comment by mgyongyosi** [comment]
Hi @AurimasNav, this is a constraint on the Entra side: https://learn.microsoft.com/en-us/entra/identity/users/directory-service-limits-restrictions

From the previously linked document:
```
The following scenarios are not supported with nested groups:
    - App role assignment, for both access and provisioning. Assigning groups to an app is supported, but any groups nested within the directly assigned group won't have access.
```

**Comment by AurimasNav** [comment]
> Hi [@AurimasNav](https://github.com/AurimasNav), this is a constraint on the Entra side: https://learn.microsoft.com/en-us/entra/identity/users/directory-service-limits-restrictions
> 
> From the previously linked document:
> 
> ```
> The following scenarios are not supported with nested groups:
>     - App role assignment, for both access and provisioning. Assigning groups to an app is supported, but any groups nested within the directly assigned group won't have access.
> ```

Would be nice if that would also be mentioned/linked on the grafana documentation for entra id oauth configuration.
