### ISSUE TITLE
Document Generic Oauth2 / OpenID Connect login module settings for well-known providers

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#9444]
The Generic Oauth2 login module supports a wide range of Oauth2.0 / OpenID Connect compatible providers, but the instructions for configuring it are buried in assorted posts on stackoverflow and community.  It would be great if we could gather those up and add them to the official documentation so that users can find them easily.

Some examples:

 - https://stackoverflow.com/a/46469988/3485927 (Okta)
 - https://github.com/grafana/grafana/pull/8248 (bitbucket)

**Comment by papagian** [comment]
Some documentation has been added for [Okta](https://grafana.com/docs/auth/generic-oauth/#set-up-oauth2-with-okta) and [Bitbucket](set-up-oauth2-with-bitbucket) since then.
So maybe this issue can close.
