### ISSUE TITLE
Explore Metrics: Search break down values

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#94452]
### What happened?

When there's a lot of panel in grid view or row view for the breakdown, I'd like to be able to search by value with fuzzy search to reduce noise

![Image](https://github.com/user-attachments/assets/749a424f-dc71-4446-9fcb-71aa8d55f46b)

### What did you expect to happen?

A sticky search bar.

### Did this work before?

No

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by NWRichmond** [comment]
It looks like this was added in #93368:

https://github.com/user-attachments/assets/8b7c209b-b360-4ee5-a145-e09c43c47347
