### ISSUE TITLE
Logs Panel: do not collapse event on text selection

### ISSUE THREAD

**Issue by igrikus** [grafana/grafana#94468]
**Why is this needed**:

I have `Wrap lines` toggle turned off by default (because of multi-line logs)

On the 'Explore' tab I can click on the log event to expand it and select any text freely

On the other hand, when I have a Logs Panel on some dashboards, I can't select any text because the event is constantly collapsing on text selection

Here is the video:
https://github.com/user-attachments/assets/ded2b621-3512-42f1-8c4d-e8695228e516

**What would you like to be added**:

Add the same logic as on the 'Explore' tab: do not collapse on text selection, only on a single click

**Who is this feature for?**

For anyone who is trying to copy some text from their logs (all of us)

**Comment by matyax** [comment]
https://github.com/grafana/grafana/pull/96995 will take care of that.
