### ISSUE TITLE
No data points in direct rendered image

### ISSUE THREAD

**Issue by cwilldev** [grafana/grafana#9447]
I am using Grafana (v4.5.2) with Docker (version 17.06.2-ce) on an Ubuntu machine (17.04 zesty).

I have configured a dashboard that is working quite well:

![astro_dashboard](https://user-images.githubusercontent.com/2727082/31266822-f20a7e08-aa75-11e7-9a77-89e2c7b72ea6.png)

But when I try to use share->Direct link rendered image I get following png:

![astro-dashboard_rendered](https://user-images.githubusercontent.com/2727082/31266850-0ebc6a0c-aa76-11e7-870c-0fcda98b0a88.png)

I already played around with some configurations like [root_url](https://github.com/grafana/grafana/issues/2791) with no success.

I doubt that I have font issues, since everything else is just rendered fine.

There is a red exclamation mark on the very top left corner of the rendered image. But, since it's just an image, I don't know what this is about, because the logs do not display any issues neither..
```
grafana_1           | 2017-10-06T07:01:03.665506391Z t=2017-10-06T07:01:03+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/astro-dashboard?orgId=1&panelId=1&from=1507191739006&to=1507201054321&notitlebar=1&width=1000&height=500&tz=UTC%2B02%3A00"
grafana_1           | 2017-10-06T07:01:04.008818952Z Loading a web page: http://localhost:3000/dashboard-solo/db/astro-dashboard?orgId=1&panelId=1&from=1507191739006&to=1507201054321&notitlebar=1&width=1000&height=500&tz=UTC%2B02%3A00 status: success 60000
grafana_1           | 2017-10-06T07:01:04.447557317Z t=2017-10-06T07:01:04+0000 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/9Wf00QLnaZapI1U2p2u2.png

```

So does anyone has a clue why I don't see any datapoints?

Regards,
Christopher

**Comment by torkelo** [comment]
what is your datasource and how does grafana access it? For server side rendered images grafana-server needs to be able to access the url you specified in data source settings. 

Since your using docker, maybe the docker container has no network access to the data source?

**Comment by cwilldev** [comment]
@torkelo Just awesome, you pointed me to my exact problem!
The datasources was configured to use "localhost". This was fine for using Grafana on the host machine.
But the image generation gets executed on the docker-machine itself, and this machine can not resolve localhost to the other docker-machine (influxdb). 
So I've changed the datasource to use the docker-container name rather than "localhost" and now everything works as expected.
Thanks you!

**Comment by cwilldev** [comment]
But one thing.. why in this case there are no connection errors in the logfiles?

**Comment by ondrejFuchs** [comment]
Please give me more information about "So I've changed the data source to use the docker-container name rather than "localhost" and now everything works as expected.".
I use grafana with influxdb. Every service run on own docker-container and connected by one network in docker-compose.

I got logs: t=2018-11-12T10:56:43+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: https://localhost:3000/d-solo/WYjho9aiz/test-ondra?panelId=4&render=1

And I got in email alert notification only:
![wjuww143x8x6n62faju4](https://user-images.githubusercontent.com/34134418/48347631-11e11980-e67f-11e8-9a1d-a309368ee7d3.png)

I also think, that problem is on connection but don't know where.
Thanks for any help.

**Comment by cwilldev** [comment]
@ondrejFuchs Puh, that's already more than a year ago. As I recall correctly my `datasource` was configured as `localhost`, which then could not get accessed from _outside_. So I've changed it to the docker-container name as mentioned. Did you check whether the `grafana container` has access to the `influx container`?

**Comment by ondrejFuchs** [comment]
Any advice how can i check it? I have also setting influxdb as localhost (run in docker). If I add new datasource in grafana, I settup it like: https://<my_ul>:8086. For example https://test.com:8086 and it work perfect but not in pictures in email notification.

**Comment by iautom8things** [comment]
Just in case someone with a similar issue to me finds this:

I'm running grafana and prometheus in docker, but grafana is connecting to prometheus through nginx w/ https via letsencrypt.

Like OP, dashboards worked fine, but direct rendered image gave me this red exclamation point with no data.

I had to edit my data source and switch it from `Server` to `Browser` for `HTTP -> Access` setting:

![image](https://user-images.githubusercontent.com/522040/54158752-37a5e180-4419-11e9-921f-c82d4258bfed.png)
