### ISSUE TITLE
Logs: downloaded logs use different timezones

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#94486]
When exporting log lines from the explore page, the export button has three formats: json,csv & txt, from that txt file is taking local browser time, where as json and csv are in UTC epoch time stamp. The expectation is that the three methods use the same format.

**Comment by PrajwalParvati** [comment]
Hi @matyax is this open for contribution? I'd like to work on this feature.

**Comment by matyax** [comment]
@PrajwalParvati Not explicitly, but we will consider contributions to any open task. For this one, there's an open PR. Feel free to keep an eye on it or try with other open issues.
