### ISSUE TITLE
[Shore]: Unified Color picker fixes

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9449]
1) The spectrum picker is still used in places. use new color picker everywhere and remove the old one. 

2) The onChange binding should use function binding not value binding. (think ngReach supports this, you can specify how each property should bind). 

So instead of this
```
        <color-picker color="ctrl.panel.colors[2]" onChange="ctrl.onColorChange(2)"></color-picker>
```

Should this not be `on-change="ctrl.onColorChanged(newColor)"` 

Hm.. that might now work with ngReact though. Maybe this will work? 

 `on-change=ctrl.onColorChanged"` 

And change:

```
coreModule.directive('colorPicker', function (reactDirective) {
  return reactDirective(ColorPicker, ['color', 'onChange']);
});
```

using syntax to specify reference binding:

```
app.directive('hello', function(reactDirective) {
  return reactDirective(HelloComponent, [
    'person',
    ['place', {watchDepth: 'reference'}],
    ['func', {watchDepth: 'reference', wrapApply: false}]
  ]);
});
```

might not work.  Not sure. the "onChange" looks wrong though, strange that it works, should it not be on-change?

**Comment by alexanderzobnin** [comment]
Few comments:
`<color-picker color="ctrl.panel.colors[2]" on-change="ctrl.onColorChange(2)"></color-picker>`
1. `on-change` works properly. No matter, which form is used  - `on-change` and `onChange` works identically.
2. `color` is a string, so it will be passed "by value". So this is a problem to change it directly. `ctrl.onColorChange(2)` is a function which returns `(newColor) => {}` function which can change specified color. If we want to use something like this:
`on-change=ctrl.onColorChanged"`, we should know, which color should be changed in `onColorChanged` function. But only property we can pass from picker is a color value. And because colorpicker uses color passed by value, it doesn't know anything about where it was passed from.

**Comment by alexanderzobnin** [comment]
Maybe you just confused by `onChange="ctrl.onColorChange(2)"`? `2` is just an index in `panel.colors` array. This call produces function with signature`function(newColor) {}` which changes color with given index. So `ctrl.onColorChange(2)` is a reference to function.

**Comment by torkelo** [comment]
Think you missunderstood me. 

The thing is if you read an angular template that reads "on-change="ctrl.onColorChange(2)" I would expect that function to be called when colors change but that is not how it works the way you defined the directive wrapper.  You defined the directive wrapper to bind by value which will cause the function to execute only once on initial bind. This is not what you expect from a normal angular directive. 

Did you try function binding in ngReact? maybe we need propTypes with type func for that to work not sure. 

Just very un-angular to bind function by value. function are 99% callbacks but the way on-change is configure now it is by value and will only be called once at compile. Maybe it's how we need to do it for angular react wrappers not sure.

**Comment by alexanderzobnin** [comment]
Did some investigation on it.

**_Angular way:_**
When we create directive and want to provide callback we do something like this:
```js
Directive:
scope: {
  onChange: "&"
}
...
scope.onChange({newValue: newValueFromDirectiveScope})

Usage:
<my-directive on-change="ctrl.changeIt(newValue)"></my-directive>
```
`&` means that expression `ctrl.changeIt(newValue)` will be executed in the context of the parent scope due `scope.onChange()` call. And we can even pass variables from directive's scope by using `name: value` map (`{newValue: newValueFromDirectiveScope}`) as parameter of `onChange()`. So we could do this in Angular color picker:
```js
<color-picker color="ctrl.panel.color" on-change="ctrl.onColorChange(newColor)"></color-picker>
```


**_ngReact way:_**
I looked at ngReact sources and found this difference between "by value" and "by reference" watching:
https://github.com/ngReact/ngReact/blob/master/ngReact.js#L127
```js
} else if (exprWatchDepth === 'reference' && supportsWatchGroup) {
        watchGroupExpressions.push(actualExpr);
...
    if (watchGroupExpressions.length) {
      scope.$watchGroup(watchGroupExpressions, listener);
    }
```
Another thing is a parsing attributes:
https://github.com/ngReact/ngReact/blob/master/ngReact.js#L279
```js
props.forEach(function(prop) {
              var propName = getPropName(prop);
              scopeProps[propName] = scope.$eval(findAttribute(attrs, propName));
              config[propName] = getPropConfig(prop);
            });
```
The key thing is that ngReact evaluates passed expression on rendering, not on call. And then it uses evaluated result as property value. When we use somethig like this:
```js
<color-picker color="ctrl.panel.color" on-change="ctrl.onColorChange(newColor)"></color-picker>
```
`props.onChange` will be result of `ctrl.onColorChange(newColor)` call.

So `scope.$eval(findAttribute(attrs, propName))` should be function if we want to callback. There's no way to tell ngReact to use property as angular-style callback. Or maybe I jsut don't know how to do that.
Any thoughts?

**Comment by torkelo** [comment]
looks like your right, then maybe it would be best to set {watchDepth: 'reference', wrapApply: false}.
Don't see the point of wrapping the call in apply if its only called during compile. and I thinnk watchDepth reference will be faster

**Comment by alexanderzobnin** [comment]
Maybe, will try to use this approach.

**Comment by alexanderzobnin** [comment]
Tried to use `wrapApply: false`, but it doesn't work (function updates color model, but doesn't update view, so color on picker icon isn't updated). So I'll use `{watchDepth: 'reference', wrapApply: true}`.

**Comment by torkelo** [comment]
Ok
