### ISSUE TITLE
[Bug] Hidden json dashboards are not ignored

### ISSUE THREAD

**Issue by nielsole** [grafana/grafana#9451]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 4.5.2
- What datasource are you using?
- What OS are you running grafana on? Linux
- What did you do? I have template files that are in hidden directories (e.g. ".hidden") Then I create symlinks in the main folder.
- What was the expected result? The dashboards are displayed in the search bar
- What happened instead? The dashboards are displayed twice in the search bar
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
we are deprecating this feature (the ability to load json files directly) in 5.0 so will  not fix this. 

Try use a tool like wizzy (to import json dashboard via api) instead. We will hopefully develop something similar as a replacement for this feature. 
https://github.com/utkarshcmu/wizzy
