### ISSUE TITLE
Tempo: Remove mentions of traceQLStreaming feature flag from docs

### ISSUE THREAD

**Issue by adrapereira** [grafana/grafana#94528]
The `traceQLStreaming` feature flag has been removed and the only way to toggle streaming is using the toggle in the datasource config. Users who had the feature flag enabled were automatically migrated to the datasource config.

**Comment by knylander-grafana** [comment]
PR for pages impacted in Tempo docs: https://github.com/grafana/tempo/pull/4173

**Comment by knylander-grafana** [comment]
PR for Grafana - Tempo data sources: https://github.com/grafana/grafana/pull/94581
