### ISSUE TITLE
Make GeoMap match with map of India

### ISSUE THREAD

**Issue by prnam** [grafana/grafana#94553]
**Why is this needed**:

Currently, the map of India is not accurate, which has become a barrier for certain projects in the public sector, as well as for private entities and citizens. This inaccuracy needs to be addressed to ensure compliance with national security requirements.

**What would you like to be added**:

To enhance the mapping system, we need to implementation of GeoMap Support, which would focus on regional territorial boundaries while respecting national sovereignty and territorial integrity.

**Who is this feature for?**

- Citizens of India: To provide accurate information for personal and civic use.
- Public Officials in Technical Roles: To facilitate informed decision-making and effective governance.
- Entities Working on Public Projects: Both commercial and non-profit organizations that require accurate mapping for planning and execution.
- International Users: The feature could be configured based on the user’s context and geographical needs, ensuring relevance for projects in other countries as well.

**Comment by yosiasz** [comment]
what is not accurate?

**Comment by gelicia** [comment]
I chatted with @prnam a bit in the slack, and they recommended https://www.mapmyindia.com/india-map/ as an accurate map. 

For this, I would recommend getting accurate map data on an ArcGIS mapserver - its easy to point to a custom mapserver with Grafana. There's information on how to configure this within Grafana at https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/geomap/#arcgis-mapserver-layer
