### ISSUE TITLE
[Bug] Can't import from /public/ in custom plugin (v4.6.0-pre1)

### ISSUE THREAD

**Issue by petrslavotinek** [grafana/grafana#9456]
Hi,

I've installed grafana v4.6.0-pre1 (commit: 3519d8d69) following instructions in "Run from master".
I've wanted to make some updates in my plugin carpetplot - I've cloned source from git to /data/plugins.
However after building both grafana and the plugin I'm getting 404 not found for any file in /public/ folder. e.g. public/d3, public/app/core/core, public/app/core/utils/ticks.
The request for public/app/core/core goes to http://localhost:3000/public/app/core/core and ends with 404. Request to http://localhost:3000/public/app/core/core.ts works.

I've tried installing the plugin using grafana-cli and I'm getting the same error.
I've also tried different plugin (both cloning and installing) with same result.
I'm using Windows 10.

I've downloaded latest grafana for Windows - v4.5.2 (commit: ec2b0fe6b) and plugin works there.

Am I just missing something?
Thank you very much for any help.

Petr

**Comment by torkelo** [comment]
app/core/core is not exposed to plugins anymore, might change before release if a lot of plugins use it. Or maybe just expose app/core/core_module. 

What are you using from core?

Here is what we currently allow plugins to load:
https://github.com/grafana/grafana/blob/master/public/app/features/plugins/plugin_loader.ts#L47

**Comment by petrslavotinek** [comment]
From exposed:
- app/core/utils/kbn
- app/plugins/sdk
- moment
- lodash

From not exposed:
- contextSrv
- d3

d3 can be installed. However if grafana is still using it (at least Heatmap panel is), I think it'd be better to expose it as well. 

From contextSrv I'm using just contextSrv.user.lightTheme property.
Can I get active theme some other (better) way?
