### ISSUE TITLE
[Feature request] Support managing playlists with the http api

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#9458]

**Comment by bergquist** [comment]
What do you mean by manage? It's technically possible to create/update/delete playlists using the API but its not documented. Would documenting this be enough or are you thinking of something else?

**Comment by roidelapluie** [comment]
Yes documentation would be enough :)

**Comment by andreimic** [comment]
Yes, please, thank you! :+1:

**Comment by tharindupr** [comment]
Is there any update? I need to upload some dashboards using the API and then add one of them to a playlist programmatically. Is that possible?

**Comment by torkelo** [comment]
yes, everything the UI does (in terms of loading or modifying data it does through the api). 

Just have chrome dev tools network tab open and add a dashboard to a playlist and save the playlist, inspect the api call grafana makes to update the playlist

**Comment by bolind** [comment]
Some documentation for this would be great, especially if all the underlying stuff is already there. I tried the chrome dev tools trick, but didn't become fully enlightened.

The URL is clearly `https://example.com/api/playlists`, and the JSON request is something like:

`{"interval":"5m","name":"foo","items":[]}` where I haven't quite deduced the format of `items` (Clearly it's the dashboards you want in your playlist.)

**Comment by davidnewhall** [comment]
This is documented now. You can probably close this issue. https://grafana.com/docs/grafana/latest/http_api/playlist/

**Comment by bergquist** [comment]
@davidnewhall thank you for noticing! :)
