### ISSUE TITLE
create Silence alert rule: bad matcher format: \"alertname\"=\

### ISSUE THREAD

**Issue by cruvie** [grafana/grafana#94580]
### What happened?

![Image](https://github.com/user-attachments/assets/ca83e6a2-4deb-463c-ac8f-ec8b4c0a4016)

### What did you expect to happen?

create Silence alert rule successfully

### Did this work before?

no

### How do we reproduce it?

1. add alter rule and trigger it
2. silence the alert as gif show
(the alertmanager is from mimir build in)

### Environment (with versions)?

Grafana: Grafana v11.2.2 (dbf571744d)
OS: macos15 docker desktop Docker Engine v27.2.0
Browser: edge
Mimir: 2.14.0

### Grafana platform?

None

**Comment by braunsonm** [comment]
Same issue, seems to be related to https://github.com/grafana/grafana/pull/93051

**Comment by JacobsonMT** [comment]
Closing as duplicate of https://github.com/grafana/grafana/issues/94320
