### ISSUE TITLE
[Bug] Can't use postgresql as database backend because SQL syntax error.

### ISSUE THREAD

**Issue by Torxed** [grafana/grafana#9459]
Please include this information:
- What Grafana version are you using?
grafana 4.5.2-1

- What datasource are you using?
postgresql 9.6.5-1

- What OS are you running grafana on?
Arch Linux

- What did you do?
Tried to fire it up for the first time. Followed this guide: https://wiki.archlinux.org/index.php/Grafana
Modified the `[database]` section to use the following values:
```
type = postgres
host = 127.0.0.1:5432
name = grafana
user = grafana
password = """somelongpassword"""
```
(Also this is a weird syntax, because you don't allow spaces in your password, neither `!` apparently?)

- What was the expected result?
It starting ofc.

- What happened instead?
```
Oct 07 23:21:12 postgres[841]: ERROR:  relation "INFORMATION_SCHEMA.TABLES" does not exist at character 26
Oct 07 23:21:12 postgres[841]: STATEMENT:  SELECT "TABLE_NAME" from "INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_SCHEMA"=$1 and "TABLE_NAME"=$2

```

The whole syntax looks off, ignoring the fact that we're abusing uppercase letters, writing `"TABLE_NAME"` won't work. Perhaps this should be `SELECT table_name FROM information_schema.tables WHERE table_schema=$1 and table_name=$2;`?

**Comment by bergquist** [comment]
What postgres version are you using?

**Comment by Torxed** [comment]
postgresql 9.6.5-1
