### ISSUE TITLE
[alerting]: Image capture in alert is having an annoying error "Endpoint only available for users"

### ISSUE THREAD

**Issue by weng5e** [grafana/grafana#94649]
### What happened?

Image capture in alert is having an annoying error "Endpoint only available for users"

I configured Grafana alert with a linked dashboard panel. The Grafana also has image renderer enabled. The triggered email alert will contains an image capture in it. However, there is an annoying "Endpoint only available for users" that blocked a big chunk of my dashboard in the image capture.

![Image](https://github.com/user-attachments/assets/5913fe52-a5ea-46fd-8ae7-d54166c25cac)

### What did you expect to happen?

I do not want to see the banner blocking my dasbhoard panel view.

### Did this work before?

Yes. It was working before like Grafana 10.1.

### How do we reproduce it?

	1. Configure SMTP
	2. Enable image rendered
	3. Create a dashboard with random walk.
	4. Create an alert rule that link to this dashboard panel.
5.   Wait for alert to trigger.

### Environment (with versions)?

Grafana: 10.4.7
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

random walk

**Comment by Desolar1um** [comment]
Hello @weng5e , Is this alert using a custom template or the default one? Asking as I'm having trouble getting image renderer working with custom templates

**Comment by weng5e** [comment]
This should happen for any alerts in the affected Grafana versions. The logic should also impact other features that is not using "user login", e.g. kiosk, reporting.  

Kiosk example:
https://github.com/grafana/grafana-kiosk/issues/146

**Comment by weng5e** [comment]
I am still repro ducing this error in 10.4.15.
