### ISSUE TITLE
the unit 'packets/sec' is not correctly display, when the value less than 1

### ISSUE THREAD

**Issue by bettswang** [grafana/grafana#94665]
### What happened?

the data in the promethues 
![Image](https://github.com/user-attachments/assets/b2b0e820-2050-477e-a03a-97195387709c)

the image on the grafana
![Image](https://github.com/user-attachments/assets/eb75f080-67ba-436f-9b5c-fba0eade7442)

### What did you expect to happen?

Display the original value. Cause I am not sure that  the unit mp/s is seem to be represented millions packet/second.

### Did this work before?

use the template doshboard,which id num is 12492.

### How do we reproduce it?

use the template doshboard,which id num is 12492.

### Environment (with versions)?

Grafana: 11.2.2
OS: ubuntu20.04
Browser: win11, edge

### Grafana platform?

A downloaded binary

### Datasource(s)?

promethues

**Comment by Proximyst** [comment]
The `m` in `mp/s` stands for milli (i.e. counting in 1/1000). For millions, you have `Mp/s`. This is in line with most (all?) other units, but hopefully DataViz can shine some light on whether we want to keep it this way (I'd assume so?) :)

0.05 packets/sec => 50 millipackets/sec => 50 mp/s

![Image](https://github.com/user-attachments/assets/90737592-04cc-4ee3-b87d-d10656821992)

5 000 000 packets/sec => 5 megapackets/sec => 5 Mp/s

![Image](https://github.com/user-attachments/assets/b0fad23b-50aa-43b8-b2f5-d0954f6df61d)

**Comment by bettswang** [comment]
Got it. Thank you.

**Comment by itaispiegel** [comment]
This is hilarious. We've been dealing with an incident in our production environment for a few days, and this graph had us scratching our heads over why we were seeing so many packet drops. Only now did I realize we've been interpreting the graph completely wrong, and that the actual number is completely negligible 🤣
