### ISSUE TITLE
Alarms with template variables

### ISSUE THREAD

**Issue by hac3ru** [grafana/grafana#9470]
I've got the following dashboard (simple panel) that takes memory usage based on the $Host variable. The problem occurs when trying to create an alert using the queries on this graph. I always get "no_data".
After turning grafana's log on debug I've got the following:
(t=2017-10-09T16:10:51+0300 lvl=dbug msg="Influxdb request" logger=tsdb.influxdb url="http://influx:8086/query?db=collectd&epoch=s&q=SELECT+last%28%22value%22%29++%2F+1024%2F1024+FROM+%22memory_value%22+WHERE+%28%22host%22+%3D~+%2F%5E%24Host%24%2F+AND+%22type_instance%22+%3D+%27free%27%29+AND+time+%3E+now%28%29+-+5m+GROUP+BY+time%28200ms%29+fill%28null%29%0A")

I try to run that in a browser, I do get an empty response. Still, if I change the $Host variable with the name of an actual host, like so:
(http://influx:8086/query?db=collectd&epoch=s&q=SELECT+last(%22value%22)++%2F+1024%2F1024+FROM+%22memory_value%22+WHERE+(%22host%22+%3D%20%27webserver0%27+AND+%22type_instance%22+%3D+%27free%27)+AND+time+%3E+now()+-+5m+GROUP+BY+time(200ms)+fill(null)%0A), it works.
Any workaround?

[grafana mem usage.txt](https://github.com/grafana/grafana/files/1368561/grafana.mem.usage.txt)

**Comment by bergquist** [comment]
Alerting does not support templated variable. Dupe https://github.com/grafana/grafana/issues/6557
