### ISSUE TITLE
[Bug] Role of user is lost on Sign out /Sign in

### ISSUE THREAD

**Issue by aborany** [grafana/grafana#9472]
Please include this information:
- What Grafana version are you using?
v4.4.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS 7 (Docker Image)
- What did you do?
I was assigned to the role 'Editor' to be able to edit Grafana dashboards, After sign out / sign in I was not able to edit dashboards anymore and after checking with our Grafana admin it was visible that my role was changed to 'Viewer'
- What was the expected result?
Role 'Editor' should be kept even when signing out and signing in again
- What happened instead?
Role was change to 'Viewer'

**Comment by aborany** [comment]
We just updated Grafana to v4.5.2 and there the issue still exists.

**Comment by torkelo** [comment]
You must be using  ldap, when configured to auth via ldap grafana will take role from ldap group mappings
