### ISSUE TITLE
Non-default retention policies not used when selecting tag and field keys

### ISSUE THREAD

**Issue by omki2005** [grafana/grafana#9473]
If we have a non-default retention policy set in the query builder, it should try to select the tag fields and values based on the retention policy selected rather than depend on the default retention policy.

Requested details :-

What Grafana version are you using? **4.5.2**
What datasource are you using? **influxDB**
What OS are you running grafana on? **RHEL6**
What did you do? **Select field box when non-default retention policy is set**
What was the expected result? **Field list for non-default retention policy is populated in drop-down menu**
What happened instead? **Field list for default detention policy is populated in drop-down menu**
If related to metric query / data viz: 
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac)

The metric query sent :- 
SHOW FIELD KEYS FROM "FOO"

The metric query expected :- 
SHOW FIELD KEYS FROM "MY_RET_POLICY"."FOO"

**Comment by austinbutler** [comment]
Same on 4.6.1.

**Comment by omki2005** [comment]
Thanks for merging!
