### ISSUE TITLE
[Feat]: Create graphite events compatible Annotations HTTP API 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9479]
Support graphite events api via grafana HTTP api `api/annotations/graphite`  

http://graphite.readthedocs.io/en/latest/events.html#adding-events

Start with supporting only write (concat what + and data into grafana's annotation text field).

**Comment by alexanderzobnin** [comment]
Which Graphite data source should be used for adding events?

**Comment by torkelo** [comment]
You misunderstand. This issue is about being able to receive data in the same format as graphite but save it grafana's annotation database. 

So basically do the same as is done here: https://github.com/grafana/grafana/blob/master/pkg/api/annotations.go#L40 

But support the way graphite api receives data. The feature is to enable someone who is using graphite event to migrate to grafana annotations by just changing the url.

**Comment by alexanderzobnin** [comment]
Aha, ok. I just thought about adding events to Graphite from Grafana UI, but it's migration-related feature.

**Comment by torkelo** [comment]
yes :)

**Comment by alexanderzobnin** [comment]
@torkelo have some troubles with graphite annotations. 
1. When we write it to DB, we can't set org_id, so currently GetAnnotations can't return this events. I added workaround for Find() function ```sql.WriteString(`WHERE annotation.org_id = ? OR annotation.org_id = 0`)```, but not sure this looks good. Maybe better to add special tag, ie `graphite` to all this annotations and use it in query?
2. When I write annotation I set `text` data as `what + "\n" + data`, but grafana frontend converts `\n` to space. `what + "<br>" + data` works, but not sure it's good idea to have it in database.

**Comment by DanCech** [comment]
@alexanderzobnin the second issue at least should be easy to solve by converting `\n` to `<br />\n` at display time, which will allow newlines to work as the user would expect.

**Comment by torkelo** [comment]
1) use c.OrgId

2) new line should be translated to <br /> in the frontend, can you check annotation tooltip why that does not happen?

**Comment by alexanderzobnin** [comment]
I think it's due HTML sanitizing. I'll check it and add it to frontend.

**Comment by alexanderzobnin** [comment]
As I understand, `title` field is deprecated now, right?

**Comment by torkelo** [comment]
yes
