### ISSUE TITLE
[BUG?] Evaluation of dependent template variables when repeating panels

### ISSUE THREAD

**Issue by madprogrammer** [grafana/grafana#9481]
**Please include this information:**
- What Grafana version are you using? **4.6.0-pre1**
- What datasource are you using? **Prometheus**
- What OS are you running grafana on? **Linux CentOS 7**
- What did you do? 

I created two 'Query' template variables, `source_id` (A) and `source_name` (B). The variable B is using the value of A in its query. B is single-value only and is hidden from the Web UI (can't be changed by user), A is multi-value (including All option). The A variable is used to repeat a Single Stat panel, and this is working fine. However, if I choose All, or two or more values for A, the value of B in the repeated panels becomes `None`. Selecting a single value for A works fine, and the value of B is displayed correctly in the resulting (single) panel.

Works:
![image](https://user-images.githubusercontent.com/531058/31388179-e2197b44-add5-11e7-8da5-468802ad262c.png)

Doesn't Work:
![image](https://user-images.githubusercontent.com/531058/31388183-e79f17e0-add5-11e7-8859-8f6a1ea4f1aa.png)

- What was the expected result?
The value of the variable B is valid in each of the repeated panels.

- What happened instead?
The value of the variable B is only valid if only one value is selected for A.

Is there a correct way to get the desired behaviour?

Thanks!

**Comment by torkelo** [comment]
this is scenario is not supported (and likely will not). That is repeating over a variable that is used in another query variable. For that to work we would need to  issue the query for variable B for each repeated panel and this is not something Grafana will do.
