### ISSUE TITLE
MySQL Datasource

### ISSUE THREAD

**Issue by JCardoen** [grafana/grafana#9484]
Hi

I recently installed grafana and I wanted to add a Data Source.

Now, my data source is a MySQL database but I can't seem to find the query editor on a new dashboard? I can use templating to get some values, but they are all seperated (rows & cols are splitted into single values).

How can I:
1) See the query editor?
2) Create graphs

The docs & the screencasts are of little use.

Thanks in advance!

J.

**Comment by torkelo** [comment]
What version of Grafana are you using?

**Comment by torkelo** [comment]
Any errors in Chrome dev console? Have you added the data source? What does the metric tab look like when  you select your mysql data source?
