### ISSUE TITLE
[Bug] Incorrect data being displayed for graph axes

### ISSUE THREAD

**Issue by codingwatermelon** [grafana/grafana#9485]
Hello,

I'm fairly new to Grafana. I use InfluxDB v1.2.4 and Grafana v4.4.1 on a CentOS 7 server, and I'm having this issue with one of my graphs incorrectly displaying the right y-axis as well as the metric that goes along with it. The first screenshot is of the graphs in question and the second screenshot is of a graph that correctly displays information (expected output).

I seem to only be having this issue for this specific host, a Dell SonicWall NSA 4600. However, I have verified that the data being used is the same data as the correct graph uses (and they are configured identically since they are on the same dashboard), both graphs should be displaying a right-axis that indicates that the interfaces operate at 1,000,000,000 bps, or 1 GBps, but instead for the SonicWall NSA 2600 it shows 1,000,000,000.00% and therefore does not display the right y-axis, seemingly inheriting my left y-axis configurations. 

For the configurations, I created a series override for the y-axis 2 to display the *_speed_bps and also made it so the right y-axis would show as well, with the min threshold being 0 and the max being 1,000,000,000 (bits per second). A couple screenshots that I've attached show what I'm talking about.

I've included a screenshot of the raw network request as well as a .txt file of the response, although I don't see the value of it. I compared it with my correct graph and they seem to be identical, obviously other than the names.

Thanks for any help in advance!
![grafana dashboard error](https://user-images.githubusercontent.com/32379178/31413681-39bfc44a-adb6-11e7-91e4-37c326ae9be0.png)

![grafana correct graph](https://user-images.githubusercontent.com/32379178/31413685-3f156756-adb6-11e7-9c74-5db4f8721c71.png)

![grafana y axes configs](https://user-images.githubusercontent.com/32379178/31413793-ca91556a-adb6-11e7-939f-96fadd0bb2d8.png)

![grafana - series override](https://user-images.githubusercontent.com/32379178/31413797-cf2b8a32-adb6-11e7-99be-0614c14b0815.png)

![grafana - raw network request](https://user-images.githubusercontent.com/32379178/31413691-43fc4dc0-adb6-11e7-9cb4-e4be1f28088e.png)

[networkresponse.txt](https://github.com/grafana/grafana/files/1373614/networkresponse.txt)

**Comment by torkelo** [comment]
You regex does not seem to match for those series.

**Comment by codingwatermelon** [comment]
sometimes it's the small things...

I didn't include '(' and ')' in my regex to account for what I named my metric.

Thanks @torkelo for the sanity check.
