### ISSUE TITLE
[Feature Request] Constant Variable Without Quotes for use in MySQL Query

### ISSUE THREAD

**Issue by md100play** [grafana/grafana#9486]
Hi,
I am trying to make a dashboard more portable, so I want to include variables that a user can use to change the table that a MySQL query selects from. I tried using the constant and it inserted into the query with single quotes like: SELECT * FROM 'myTableName', which gives an error because the correct syntax is SELECT * FROM myTableName.

If there is already a way to do this, then I'm sorry for posting here, but I cannot find a way and I know that it would be appreciated if it could be added.

Thanks!

**Comment by md100play** [comment]
I see that this seems to be on the roadmap for 5.0, so I'll close this.

Reopen the issue if I am wrong that this is an upcoming feature.
Thanks again!

**Comment by xurde** [comment]
Hi @MikeDombo 
Can you please confirm if this feature went somewhere in v5.0?
We are having a similar use case of the same thing and it would be great to know the status of this.

Thanks in advance!
Jorge

**Comment by MikeDombo** [comment]
Fixed by PR https://github.com/grafana/grafana/pull/9611
It is in 5 now and I'm using it.

**Comment by xurde** [comment]
Thanks for fast reply, 

Maybe you can determine better if this feature could somehow fit for the use case we are figuring out. We need to define a per-user constant value, which forces all charts access to a certain subset of data. I.e. `SELECT metrics WHERE provider='XX' ...` where the XX should be taken from the logged in user context.

Do you think it might be doable using this?

Thanks!

**Comment by xurde** [comment]
Thanks again, Mike

We will be debating this in a FR.

Cheers!
