### ISSUE TITLE
[Feature request] MySQL time series query and ability to insert 0s or nulls for missing intervals 

### ISSUE THREAD

**Issue by MikeDombo** [grafana/grafana#9487]
I have several trend plots that take data from MySQL and they work very well. However, some days I have no data and I would like a way to insert zeroes instead of straight-line connecting between points that do exist.

ex. If I have data for Sept 1, 2, 5, 6, 7 - Right now it connects September 2 to 5 with a line. I would like a way to insert data that does not exist in my MySQL database for Sept 3 and 4 with value 0.

I think that this feature will be difficult to implement, but is ultimately very useful for time series data that is stored in a SQL database and not a time-series database.

**Comment by torkelo** [comment]
This is a feature that most time series databases have. You should be able (but ticky) do it in the query by grouping by time interval and through some trickery return 0 for missing intervals.

**Comment by Angrite** [comment]
If this feature request will be considered to realize for MySql and other relational datasources (databases), time interval to fill missed points/gaps must be configurable (1min, 5min, … 1 day … 1 week….). 

But I’m not sure, if it is correct way to fill missed values from grafana side for relational datasources (databases). To my opinion, most preferable solution is to do this from database side (via query). It is tricky, but manageable.
