### ISSUE TITLE
Alert-handle is not respecting negative-y

### ISSUE THREAD

**Issue by stromnet** [grafana/grafana#9489]
Alerting rules matches actual value. Alert-handle reflects this value.
If the graph has negative-y enabled on the related series, the result looks weird:

![screen shot 2017-10-11 at 09 21 58](https://user-images.githubusercontent.com/668449/31426930-b1229d14-ae65-11e7-9e9e-6f984aaf4241.png)

Dragging the handle down so it visually looks good, will give it a negative value (i.e. -140). This will break the matching rule though, as it is matching on non-inverted values.

Tested on:
Grafana 4.4.3, 4.5.2
Data source: InfluxDb

**Comment by torkelo** [comment]
negative-y display option will not work well with the drag handle since it is a display only option it will cause issues. 

If you need this make the data negative in the query instead.

**Comment by stromnet** [comment]
I don't really "need" it, but it is not working as one would expect, it's just counter-intuitive the way it is now.
