### ISSUE TITLE
[problem] the "/api/alerts" api with params "limit" cause ERROR: "near \"ORDER\": syntax error"

### ISSUE THREAD

**Issue by lzyRun** [grafana/grafana#9492]
grafana version: 4.4.3
OS：centos 7

in the "HTTP API" document, the parameters of "/api/alerts" have the "limit", but when i use the  "/api/alerts" api with params "limit" cause ERROR: "near \"ORDER\": syntax error",
and the response is "message": "List alerts failed".

the request is : http://127.0.0.1:3000/api/alerts?limit=2.

if there is anyting wrong the way i use to get alerts list ?

**Comment by torkelo** [comment]
what database do you use?

**Comment by lzyRun** [comment]
@torkelo default database "sqlite3".

**Comment by torkelo** [comment]
was able to replicate, thanks for reporting this! fixed !
