### ISSUE TITLE
Invite signup page: Missing organization name

### ISSUE THREAD

**Issue by svet-b** [grafana/grafana#94932]
### What happened?

When a user is invited to an organization and they click on the invite link (of the form `https://<grafana_domain>/invite/<invite_code>`), the text on the page reads (verbatim)
> _Alice_ has invited you to join Grafana and the organization

(let's say in this case the invite was sent by Alice). This is not a complete sentence, and looking at [the code](https://github.com/grafana/grafana/blob/main/public/app/features/invites/SignupInvited.tsx#L70-L71), it's clear that the name of the organization ought to be included at the end:
```html
          <em>{invitedBy || 'Someone'}</em> has invited you to join Grafana and the organization{' '}
          <span className="highlight-word">{contextSrv.user.orgName}</span>
```
But this doesn't work because the user account doesn't actually exist yet (it only exists as a temporary account), therefore `contextSrv.user.orgName` is not set.

### What did you expect to happen?

The text should include the name of the organization that the user was invited to, e.g.

> _Alice_ has invited you to join Grafana and the organization **BigCorp**

### Did this work before?

I feel like I've seen this work correctly, so I assumed this was some sort of regression. But I've just tried this in every major Grafana version going back to v3, and it does not appear to work in any version.

### How do we reproduce it?

1. Under "Organization users" click "Invite". Generate an invite
2. Either get the invite link from the email, or just copy it from the list of pending invites
3. Open the invite link on a different browser or in incognito mode
4. Observe that the organization name is not included in the first sentence

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.2.0 (also tested with 3.1.0, 4.6.5, 5.4.4, 6.5.3, 7.5.4, 8.4.11, 9.4.17, 10.1.1
OS: macOS, running Grafana in Docker
Browser: Chrome 129.0.6668.100

### Grafana platform?

Docker

### Datasource(s)?

n/a

**Comment by tskarhed** [comment]
I am surprised this hasn't been reported earlier. Thanks!
