### ISSUE TITLE
Org: need input to choose org.

### ISSUE THREAD

**Issue by yincongcyincong** [grafana/grafana#94938]
### What happened?

when i want choose a use into a organization. i found i can't choose organization that i want to use.
![Image](https://github.com/user-attachments/assets/79eed3a1-88ea-44d3-9cb1-0a8e31ffb525)
the origanization have been choosed. i only can invite use into `new org`. it's uncomfortable for admin.

### What did you expect to happen?

can choose which org i want to invite

### Did this work before?

no

### How do we reproduce it?

1. create two org
2. invite use into org
![Image](https://github.com/user-attachments/assets/cbc3ac16-7c40-4b0b-86ab-0d14c4ac7a44)
![Image](https://github.com/user-attachments/assets/a3540cd4-8201-4a48-b524-0d75d08e9221)

### Is the bug inside a dashboard panel?

yep

### Environment (with versions)?

Grafana: main branch
OS: macos
Browser: chrome

### Grafana platform?

None

**Comment by kalleep** [comment]
Yes this is because you are in a org specific view and it will create and invite for that org. You need to switch org using the org picker in the navbar in order to invite to another org

**Comment by yincongcyincong** [comment]
> Yes this is because you are in a org specific view and it will create and invite for that org. You need to switch org using the org picker in the navbar in order to invite to another org

thanks for your reply. i found the `org picker`. however, when i change `org picker`, this page will go to main view, i think it's a little bit inconvenient for user.
https://github.com/grafana/grafana/issues/94938#issuecomment-2428731781

**Comment by kalleep** [comment]
Yes but that is a separate issue e.g. try to navigate to the same view when switching org and is not guaranteed to succeed because maybe you don't have the same permission on the other org or if you are in a view for a specific resource that one would not exist for the other org
