### ISSUE TITLE
[Feature request] Average Time accross all servers

### ISSUE THREAD

**Issue by aphalke** [grafana/grafana#9494]
We have codehale timer metrics for a process getting populated in graphite. We would like to calculate average of time across all servers. Codehale timer give 2 metrics mean and count. So in we have 3 servers (A,B,C). Then Average time should be
((A.mean*A.count)+(B.mean*B.count)+(C.mean*C.count))/(A.count+B.count+C.count)

Mean we are getting using following expression
<pod>.server*.com.abc.executionTime.mean 
This would result in 
<pod>.A.com.abc.executionTime.mean
<pod>.B.com.abc.executionTime.mean
<pod>.C.com.abc.executionTime.mean 

Similarly we get count using
<pod>.server*.com.abc.executionTime.count
This would result in 
<pod>.A.com.abc.executionTime.count
<pod>.B.com.abc.executionTime.count
<pod>.C.com.abc.executionTime.count

We would like to multiply first series with second by respective elements, sum it and then divide by respective elements in second series.  Multiply series would just multiply all data points. I am not sure if this can be achieved using multiplySeriesWithWildCard, if yes can you give expression to be used over here?

Can you please help me to achieve this.

We are using Grafana 4.1.1. Version we are using doesnt have multiplyWithWildCard function
 
Thanks,
Atul

**Comment by torkelo** [comment]
please use community site for questions (https://community.grafana.com)

**Comment by aphalke** [comment]
Thanks. Created topic in community as couldn't find similar question.
