### ISSUE TITLE
[Bug] Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by knuzhdin** [grafana/grafana#9496]
I'm using grafana 4.4.3 (commit: 54c79c5) on ubuntu-14.04 on top of percona galera cluster (5.6.37-26.21-1.trusty) of 3 servers. 

Once in a while (could be every couple of minutes or once in a couple of hours) I'm getting the following error in grafana.log, regarding its work with the mysql database:

> t=2017-10-11T14:44:04+0300 lvl=eror msg="Request error" logger=context userId=977 orgId=1 uname=robot-maildlv error="session(release): Error 1213: Deadlock found when trying to get lock; try restarting transaction" stack="/usr/local/go/src/runtime/panic.go:489 (0x430e7f)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:82 (0xb41cb6)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb41901)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x79ebb1)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x780e42)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x780c3b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79ed36)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb3f262)\n/usr/local/go/src/runtime/asm_amd64.s:514 (0x45dc58)\n/usr/local/go/src/reflect/value.go:434 (0x4aeccf)\n/usr/local/go/src/reflect/value.go:302 (0x4ae294)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x78116f)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x780b3a)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79ee12)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x7b0c69)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 (0x7ab06d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7a38ec)\n/usr/local/go/src/net/http/server.go:2568 (0x68df12)\n/usr/local/go/src/net/http/server.go:1825 (0x68a2e2)\n/usr/local/go/src/runtime/asm_amd64.s:2197 (0x4603f1)\n"

The client is getting "grafana error" red popup on top of dashboard (with graphite datasource graphs).
Unfortunately it is not happening each time the dashboard is being displayed, so I cannot find any useful correlations.

**Comment by torkelo** [comment]
strange, looks like the session store is under too much load or something else is not right. Does this happen frequently? Whats the usage like? whats are the read/write ops the the galera cluster?

**Comment by knuzhdin** [comment]
> Does this happen frequently?

I see these errors 1200+ times a day

> Whats the usage like?

all 3 grafana servers receive 5-10 rps
grafana.log (from all 3 servers) per day has about these number of log records:
3 session
3 sqlstore
13 alerting.notifier.slack
72 cleanup
92 alerting.notifier.email
197 tsdb.graphite
3629 notifications.webhook
5248 alerting.notifier
5289 alerting.resultHandler
5582 alerting.notifier.telegram
12271 alerting.extractor
21503 png-renderer
34855 context
239272 alerting.evalHandler
1341251 alerting.engine
1367022 alerting.scheduler

> whats are the read/write ops the the galera cluster?

grafana is not the only user of the galera cluster, but other users are quite small 99.9% of the time
here is average latency in ms for grafana:
+--------------------+----------+-------+-----------+
| schema_name        | sql_type | count | latency   |
+--------------------+----------+-------+-----------+
| grafana            | COMMIT   |     1 | 36.317591 |
| grafana            | SHOW     |     4 |  0.194645 |
| grafana            | SELECT   |     8 |  0.055465 |
| grafana            | ROLLBACK |     1 |  0.044747 |
| grafana            | SET      |     1 |  0.036671 |
| grafana            | START    |     1 |  0.026149 |
+--------------------+----------+-------+-----------+
The rate of the requests per minute is as follows:
DELETE 2
UPDATE 513
INSERT 2608
SELECT 8549

COMMIT could take a very long time in case there is a problem with network connectivity between galera nodes. But I thought this should not be related to a possible deadlock issue

**Comment by linpopilan** [comment]
@knuzhdin which application are you using as a load balancer for the Galera nodes?

I'm using HAProxy and I stepped on this issue today, and it's actually very common when running a set of Galera nodes and having applications that are writing at the same row in the same database at different nodes at the time.

I solved this by creating a separated listener in HAProxy that works as active/passive towards the same three nodes. Then I defined that Grafana should use that listener for it's sessions. 

I think tho that there should be some kind of logic in Grafana that restarts the transaction if the query returns deadlock. 

I'll post my config below:

**Grafana**:
```ini
#################################### Session ####################################
[session]
# Either "memory", "file", "redis", "mysql", "postgres", default is "file"
provider = mysql

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
provider_config = `grafana-db:supersecretpassword@tcp(ip.to.ha.proxy:3307)/grafana-db`

# Session cookie name
cookie_name = grafana_sess

# If you use session in https only, default is false
;cookie_secure = false

# Session life time, default is 86400
;session_life_time = 86400
```

```ini
#################################### Database ####################################
[database]

type = mysql
host = ip.to.ha.proxy:3306
name = grafana-db
user = grafana-db
password = supersecretpassword

# For "postgres" only, either "disable", "require" or "verify-full"
;ssl_mode = disable

# For "sqlite3" only, path relative to data_path setting
;path = grafana.db
```
**HAProxy**:
```
listen mysql-cluster-01
        bind 0.0.0.0:3306
        mode tcp
        log global
        option mysql-check user checker
        option tcplog
        balance leastconn
        timeout server 10m
        timeout client 10m
        server mysql-01-01 mysql-node1:3306 check
        server mysql-01-02 mysql-node2:3306 check
        server mysql-01-03 mysql-node3:3306 check

listen mysql-cluster-01-write
        bind 0.0.0.0:3307
        mode tcp
        log global
        option mysql-check user checker
        option tcplog
        balance leastconn
        timeout server 10m
        timeout client 10m
        server mysql-01-01 mysql-node1:3306 check
        server mysql-01-02 mysql-node2:3306 check backup
        server mysql-01-03 mysql-node3:3306 check backup
```

**Comment by torkelo** [comment]
closing this as there has been no other reports like this and seems like it can be solved by haproxy settings. 

We are trying to get rid of session store:
https://github.com/grafana/grafana/issues/7741
