### ISSUE TITLE
Generic OAuth fails at UserInfo call

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#9499]
Version 4.5

Trying to get the generic OAuth work. But getting this error:

```
DBUG[10-11|17:02:37] OAuthLogin Got token                     logger=context userId=0 orgId=0 uname=
EROR[10-11|17:02:37] login.OAuthLogin(get info from generic_oauth) logger=context userId=0 orgId=0 uname= error="Error getting user info: Get http://localhost:5000/OAuth/UserInfo: oauth2: token expired and refresh token is not set"
EROR[10-11|17:02:37] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=[::1] time_ms=84 size=694 referer=http://localhost:3000/login
```

Seems like error being thrown here:

```
// get user info
	userInfo, err := connect.UserInfo(client)
	if err != nil {
		if sErr, ok := err.(*social.Error); ok {
			redirectWithError(ctx, sErr)
		} else {
			ctx.Handle(500, fmt.Sprintf("login.OAuthLogin(get info from %s)", name), err)
		}
		return
	}
```

When http://localhost:5000/OAuth/UserInfo is hit, it returns:

```
{"access_token": "123123123123123", "token_type": "Bearer", "expiry": "0", "refresh_token": "123123123123123123"  }
```
There's no validation on this URL. It returns a hard coded response now. So, oauth client is surely getting this JSON. 

I can see from the server log that grafana never hits the UserInfo. Although it has just received the token, it thinks the token has expired and no refresh_token is provided.

**Comment by oazabir** [comment]
Tried returning token without any expiry. Still no luck

```
{"access_token": "123123123123123", "token_type": "Bearer", "refresh_token": "123123123123123123"  }
```

**Comment by torkelo** [comment]
what oauth provider are you using and what are your oauth settings?

**Comment by oazabir** [comment]
```
[auth.generic_oauth]
name = OAuth
enabled = true
allow_sign_up = true
client_id = grafana_client
client_secret = grafana_client
scopes = user:email
auth_url = http://localhost:5000/OAuth/Authorize
token_url = http://localhost:5000/OAuth/Token
api_url = http://localhost:5000/OAuth/UserInfo
team_ids = 
allowed_organizations =
```

**Comment by smalik03** [comment]
I am having the same issue with my oauth settings

**Comment by oazabir** [comment]
Just checking if you were able to repro the problem or need anything from me.
Happy to buy anyone any amount of coffee to fix this problem.

**Comment by smalik03** [comment]
@oazabir  I was having the same issue, turns out that the 'scope' I was using for email was wrong. There was a console error for that as well.

**Comment by oazabir** [comment]
@smalik03 many thanks for the suggestion. Could you please explain what you did to get it working? 
I am not using any email. Just username.

**Comment by smalik03** [comment]
I am using a custom oauth client and it did not use 'user:email' which is set by default. Updated that and it worked fine. I would suggest look at the console log for Grafana and you will find what the exact error is for the userinfo HTTP request.

**Comment by oazabir** [comment]
In my case grahana does not call UserInfo at all. It throws expired token error even before a call is made.

**Comment by Allen-yan** [comment]
I have the same issue with Grafana  Grafana v4.6.0 (commit: c47f670), running it in docker . 
I think @oazabir  is right, the error  throwed before  call Userinfo.

It may be the token_url need the expired and refresh token , and then give these to api_url. But nothing there. So api_url throws the error

`t=2017-11-09T06:54:32+0000 lvl=eror msg="login.OAuthLogin(get info from generic_
oauth)" logger=context userId=0 orgId=0 uname= error="Error getting user info: G
et https://mydomain.com/identity/oauth2.json: oauth2: token expired and
refresh token is not set"`

**Comment by torkelo** [comment]
please try Grafana v5

**Comment by srikanthrigaps** [comment]
What was the Fix here Guys !! I still face the same issue. 
"login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="user not a member of one of the required organizations
