### ISSUE TITLE
Feature request: Allow thresholds for Time column in tables

### ISSUE THREAD

**Issue by zarbis** [grafana/grafana#9500]
I use tables extensively in my dashboards, for the most part - successfully.

I've got into a problem when tried to create table "Last Heartbeat". Query fetches last record for every host that is displayed it as a table, sorted by Time column in ascending order. So if any host stops sending data - it floats to the top of table.
 
The problem is: currently thresholds are available only for numeric type in "Column Styles" menu. Even if I abandon comfort of automatic conversion from timestamp into human-readable date and set column type as "Number", I still cannot set static thresholds - time moves on :)

My proposal is to add thresholds for "Date" type that are relative to current time.
For example threshold specified as "5m,1h" will highlight in yellow all records with timestamp older than 5 minutes and in red - that are older than 1 hour.

This would be a great addition in scenario of "monitoring that everyone is online".

**Comment by bibek688** [comment]
I am in a similar situation where I need to use thresholds on time columns. Did you by any chance find out a workaround ?

**Comment by sallyruthstruik** [comment]
Fixed in https://github.com/grafana/grafana/pull/10594

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.
