### ISSUE TITLE
Avoid special characters in the release version

### ISSUE THREAD

**Issue by yongzhang** [grafana/grafana#95017]
### What happened?

Hi, team

Can we remove special characters in the release version? I got this when using docker image tag `11.2.2+security-01`, instead of using this, probably simply use `11.2.3`?

```
$ docker pull grafana/grafana-oss:11.2.2+security-01
invalid reference format
```

```
An error occurred (InvalidParameterException) when calling the DescribeImages operation: Invalid parameter at 'imageTag' failed to satisfy constraint: 'must satisfy regular expression '[a-zA-Z0-9-_.]+''
```

### What did you expect to happen?

I want the release version does not contain special characters.

### Did this work before?

11.2.2 works.

### How do we reproduce it?

```
$ docker pull grafana/grafana-oss:11.2.2+security-01
invalid reference format
```

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by kingjan1999** [comment]
The right version to pull is `grafana/grafana:11.2.2-security-01`:

```bash
$ docker pull grafana/grafana:11.2.2-security-01
11.2.2-security-01: Pulling from grafana/grafana
Digest: sha256:464eac539793a183381ae198cb3bfcee137f17888ee192b8ac1ae2e867f72a9d
```

**Comment by yongzhang** [comment]
> The right version to pull is `grafana/grafana:11.2.2-security-01`:
> 
> $ docker pull grafana/grafana:11.2.2-security-01
> 11.2.2-security-01: Pulling from grafana/grafana
> Digest: sha256:464eac539793a183381ae198cb3bfcee137f17888ee192b8ac1ae2e867f72a9d

 The is one of the issue, some providers does not support special characters like `+` in the image tag, like error below:

```
An error occurred (InvalidParameterException) when calling the DescribeImages operation: Invalid parameter at 'imageTag' failed to satisfy constraint: 'must satisfy regular expression '[a-zA-Z0-9-_.]+''
```

**Comment by bob454522** [comment]
came across this same issue-  thanks for posting fix

![Image](https://github.com/user-attachments/assets/2c33f4b2-3fa3-4013-8e58-391c1bf4acfc)
