### ISSUE TITLE
[Security Issue] Insecure InfluxDB Querys

### ISSUE THREAD

**Issue by sketler** [grafana/grafana#9501]
Hello Guys, 

I'm Edward I am part of Sto Labs, information security research division of Stone Payments. and i would like to share a security issue i just found researching the application. 

The version is Grafana v4.3.2 (commit: ed4d170)

The issue is a Injection of InfluxDB commands to enumerate Schemas, tables and all the data from the database including data you wouldn't view normally with a low Priviledged user.

The Parameter that can be used to store the payload is the [q] parameter on the query for the  metrics.

and the payload used was: SELECT%20*%20FROM%20[Tablename] and all other schema enumeration commands on influxdb.

If you guys need images you can contact me for more details on the email: ed.toledano@gmail.com 

I would like to know, if this issue could be credited to my name.

Best regards,

**Comment by torkelo** [comment]
This is not a security issue as grafana is UI for this database and will grant any query to it. When you add the datasource you can specify what InfluxDB user should  e used, this user can be used to restrict access.
