### ISSUE TITLE
[Feature request] : "Comparing grafana same dashboard results for two different time intervals"

### ISSUE THREAD

**Issue by chtnvg** [grafana/grafana#9502]
Grafana version: v4.5.2
Datasource: InfluxDB
On Grafana dashboard, we have metrics being collected from various systems and services. When we want to compare how a system/service behaved during one-time interval vs another, we currently have to view them separately in Grafana. If there could be a way to compare them side by side, it would make comparison very easy to view and relate. 
One way could be to have an option of "comparison" mode which we can enable or disable. On enabling, it lets us choose two time-intervals at the top right corner instead of one. And we could see two graphs side by side for every panel for the same grafana dashboard.

**Comment by torkelo** [comment]
duplicate / similar to https://github.com/grafana/grafana/issues/288

**Comment by torkelo** [comment]
it's an interesting idea, think making it easier to compare two time ranges is solid!
