### ISSUE TITLE
elasticsearch: "an error occured" popup appears if the elastic-user does not have enough permissions

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#95032]
when the elastic query editor is open, the plugin tries to find out the elastic-database-version using https://github.com/grafana/grafana/blob/388023a1727609c8779d35dcd819bb59693c7252/public/app/plugins/datasource/elasticsearch/datasource.ts#L1116 .

if it fails, nothing bad happens, things continue correctly.
the problem is, if it fails, you get an error-popup saying "an error occured within the plugin". would be great not to have this popup.

(i assume the popup is opened automatically by some generic grafana code when a resource-call fails).

to reproduce:
- create an elastic user that has no permission to fetch the `/` path (the root, where the elastic-database-version is)
- use this user
- you will get the popup

**Comment by kevinwcyu** [comment]
@gabor, do you have instructions for `create an elastic user that has no permission to fetch the / path (the root, where the elastic-database-version is)`? I'm using `make devenv sources=elastic`, but I don't actually know how to create a user with the restricted permissions.

**Comment by gabor** [comment]
hi @kevinwcyu , sorry for the late response.

haha, funny situation, i went to give you the info you asked for, i spent a bunch of time reproducing it, and then i found out that on the current main-branch the error does not happen anymore. `play.grafana.org` is still a week old, but when it catches up, the problem will be solved, so we can close this.

but i spent so much time replicating this, so i'll also describe how to do it:
1. the `devenv` elasticsearch has auth-things disabled at: https://github.com/grafana/grafana/blob/b8e92aacd25184bd87f601c35eca2102280c5ecf/devenv/docker/blocks/elastic/docker-compose.yaml#L9 . that `false` has to be switched to `true`
2. we add an environment variable below the line from [1] : `"ELASTIC_PASSWORD=grafana"`. this will cause the default superuser account in elastic (username=`elastic`) to have the password `grafana`

at this point, if you want to connect grafana to elastic, you need to enable the `Basic Authentication` in the `Authentication` section of the datasource config page, and enter `username=elastic` & `password=grafana`, and things will still work.

now we can create the user that can reproduce the problem. the way Elastic does this, first we create a `role`, and tell elastic what the `role` is allowed to do, and then we create an `user`, and assign roles to that user. 
in the following commands we do `curl -u 'elastic:grafana"`, this way we tell Elastic we are the superuser who is creating the new user.

create a role named `role1`, it is allowed to read indices named `logs-*`:
```shell
curl -XPOST -u 'elastic:grafana' http://localhost:9200/_security/role/role1 -H 'Content-Type: application/json' -d '{"indices":[{"names":"logs-*","privileges":["read","view_index_metadata"]}]}'
```

create a user named `user1`, assign the role `role1` to it:
```shell
curl -XPOST -u 'elastic:grafana' http://localhost:9200/_security/user/user1 -H 'Content-Type: application/json' -d '{"password":"grafana", "roles":["role1"]}'
```

at this point you can adjust the datasource config in grafana, and change the username&password to `elastic` & `grafana`, and it should reproduce the problem... except it has been solved :) . closing the issue.
