### ISSUE TITLE
[Feature request] Elasticsearch Average Bucket Aggregation

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#9503]
It would be great if addition to the count, we could have a normailization, e.g. rate per second.

That way when we change the "interval", ti stays comparable.

![rate](https://user-images.githubusercontent.com/291750/31463428-3baea8d8-aecf-11e7-957d-0030594bb046.png)

**Comment by torkelo** [comment]
normally we let this stuff be up the the query and the time series database backend. 

For example for ES metrics you can use a inline script option and specify 

`(_value / $__interval_ms) * 1000`

**Comment by roidelapluie** [comment]
Thanks! Will try out!

**Comment by roidelapluie** [comment]
Hi @torkelo 

This does not work on "count". It changes the value but not the count of values.

**Comment by roidelapluie** [comment]
https://github.com/grafana/grafana/blob/91f60bb6c40bdeed61f259e0170cf56c3eccc3f6/public/app/plugins/datasource/elasticsearch/query_def.ts#L6

That line is probably missing supportsInlineScript:

**Comment by roidelapluie** [comment]
supportsInlineScript: true is not fixing it

**Comment by roidelapluie** [comment]
I tries with sum:

![1000](https://user-images.githubusercontent.com/291750/31583332-fad3bd62-b199-11e7-85d3-8846d924c0e0.png)


but with 1000/$__interval_ms I get a flat line.

When I do 10000/$__interval_ms I get better results, then I have the rate per 10 seconds.

**Comment by roidelapluie** [comment]
![1000](https://user-images.githubusercontent.com/291750/31583347-3c2c265a-b19a-11e7-9300-0fcbc4ab4d99.png)

**Comment by roidelapluie** [comment]
With sum + script of 1000/$__interval_ms I get no result. With 10000/$__interval_ms I see rate per 10 seconds.

**Comment by roidelapluie** [comment]
Actualli

$__interval_ms is always 15k, even when I set the interval to something else??

**Comment by roidelapluie** [comment]
![x1](https://user-images.githubusercontent.com/291750/31583403-64e35a86-b19b-11e7-9ac6-bd090b63eb7c.png)
![x2](https://user-images.githubusercontent.com/291750/31583404-64fba924-b19b-11e7-8ef2-c10430eef7e2.png)
![x3](https://user-images.githubusercontent.com/291750/31583405-65163e42-b19b-11e7-808f-fcd0f286cd31.png)

**Comment by roidelapluie** [comment]
![x4](https://user-images.githubusercontent.com/291750/31585132-9bb855c2-b1bc-11e7-967a-35a8115ba4b6.png)
Here is what I need

**Comment by roidelapluie** [comment]
```
{"index":["logstash-*"],"ignore_unavailable":true,"preference":1508073669825}
{"size":0,"query":{"bool":{"must":[{"query_string":{"analyze_wildcard":true,"query":"*"}},{"range":{"@timestamp":{"gte":1507873782957,"lte":1507877827228,"format":"epoch_millis"}}}],"must_not":[]}},"_source":{"excludes":[]},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"1m","time_zone":"Europe/Berlin","min_doc_count":1},"aggs":{"1":{"avg_bucket":{"buckets_path":"1-bucket>_count"}},"1-bucket":{"date_histogram":{"field":"@timestamp","interval":"1m","time_zone":"Europe/Berlin","min_doc_count":1}}}}}}
```

**Comment by roidelapluie** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-avg-bucket-aggregation.html

**Comment by roidelapluie** [comment]
looks like I am not the only one to have that need: https://github.com/grafana/grafana/issues/3163

**Comment by roidelapluie** [comment]
Let's not waste out time on this ; that kind of query is to expensive for elasticserach.

**Comment by Drewster727** [comment]
I really... need this well :(
