### ISSUE TITLE
[Bug] Seriers overrides stack set to false dosn't work on InfluxDB

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#9508]
- What Grafana version are you using? 4.6.0-9305
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Debian 8
- What did you do? Created the Total value to present only legend values (series overrides set as Lines: False, Stack: False)
- What was the expected result? Total should not stack on the graph over the regular series 
- What happened instead?  The total has been improperly stacked (for Graphite it's ok)

![obraz](https://user-images.githubusercontent.com/12551929/31492703-24d49c24-af44-11e7-8e1c-0706e52dfa0f.png)

**Comment by torkelo** [comment]
what's the response from InfluxDB? It looks like InfluxDB returns 1.158 kpps max for Total. 

Use Query Inspector in metrics tab to view raw influxdb response.

**Comment by pavleec** [comment]
Your're right, but would it be possible even in case like this to have some form of Total on legend part only and avoid stretching the Y-axis of entire graph to the highest value when it's actually disabled via (Lines: False, Stack: False) in series overrides?
