### ISSUE TITLE
[Bug] Grafana doesn't send cookie for external plugin loading request

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#9509]
- What Grafana version are you using?
  - https://grafana.com/grafana/download/4.6.0-9569pre1
- What datasource are you using?
  - Prometheus
- What OS are you running grafana on?
  - Mac
- What did you do?
  - Open dashboard which use external (not official) datasource plugin
- What was the expected result?
  - Success to load plugin and dashboard
- What happened instead?
  - The loading request is failed due to missing cookie.
  - We use oauth2_proxy with Grafana, it responds login page to Grafana.

Not sure, but this could be related.
https://github.com/systemjs/systemjs/issues/1731

**Comment by torkelo** [comment]
I think you need to exclude /public path from auth.  This path should not require authentication.

**Comment by mtanda** [comment]
Okay.
If current behavior is expected, I configure my setting to exclude /public path.

**Comment by torkelo** [comment]
yes, grafana does not have any auth for static assets (and the standard module loaders do not send cookies for assets)

**Comment by dudusakharovich** [comment]
@torkelo - How do I exclude /public path from auth ?

**Comment by dudusakharovich** [comment]
@torkelo - This fix still doesn't work for "404 unauthorized instantiation" error while trying to load dashboard which contains status panel.

**Comment by torkelo** [comment]
@dudusakharovich what build are you using?

**Comment by dudusakharovich** [comment]
@torkelo - I'm using the latest one 4.6.1 which was released earlier today.

**Comment by daniellee** [comment]
@dudusakharovich are you talking about the Vonage Status panel. It won't work until they fix it. It uses internal parts of the graph panel which is not allowed anymore.

**Comment by dudusakharovich** [comment]
@daniellee - I see. 
So there is no point to upgrade to latest Grafana version until they will issue a fix of their own.

**Comment by stellasawicki** [comment]
Any workaround here? I have just upgraded to 4.6.1, but vonage-status-panel is being heavily used in my dashboards...

**Comment by aenima-x** [comment]
My workaround was to exclulde /public/plugins from being served by grafana a create an alias in apache to it

**Comment by daniellee** [comment]
@stellasawicki I'm waiting for the maintainer of vonage-status-panel to merge this [PR](https://github.com/Vonage/Grafana_Status_panel/pull/82) and submit a new release to be published.
