### ISSUE TITLE
jdbranham-diagram-panel

### ISSUE THREAD

**Issue by Anushak928** [grafana/grafana#95116]
### Background

jdbranham-diagram-panel

### Use case

jdbranham-diagram-panel

### Contribution

- [x] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi @Anushak928 - I'm not sure why you've opened this issue? This plugin exists https://grafana.com/grafana/plugins/jdbranham-diagram-panel/ in the catalog already?

Feel free to respond or reopen with more details
