### ISSUE TITLE
[Feature Request] Add HTTP API endpoint to test datasources

### ISSUE THREAD

**Issue by mtlaird** [grafana/grafana#9514]
I could really use an endpoint that performs whatever test is done by the UI when saving changes to a datasource, and then returns a status that indicates whether there is an error with the datasource configuration or connection.

At the moment, I don't see any way to see anything relating to data source status via the API, so this would just be a useful way to bring the API and UI into harmony. I'm looking at this documentation, by the way: http://docs.grafana.org/http_api/data_source/

I would like my scripts /tools using the API to be able to get this information in order to make other decisions, or to report on a configuration issue.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
