### ISSUE TITLE
[Panel]: News feed panel to have on the default home page

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9517]
Would like to replace plugins panel with a news feed panel that can show news (releases, articles) fetched from a rss feed like http://grafana.com/grafana/newsfeed. 

We can inject plugins that has updates into this news feed as well.

**Comment by torkelo** [comment]
thoughts @mattttt ?  

@DanCech any ideas for how we should handle & update the newsfeed api?  (needs some good caching)

**Comment by DanCech** [comment]
Sure, we can just cache the feed (last X entries) in memory like the list of plugin versions.  I can easily provide an API to provide rss/atom (we'd support json also obviously) compatible content (title, url, date, summary, content, author name, author email) that can be consumed by grafana, grafana.com, and any other rss/atom aggregator.

**Comment by torkelo** [comment]
That be cool, then we would have a way to expose timeshift and other articles / news to Grafana users (Who have not changed home dashboard or modified it by removing news feed)

**Comment by mattttt** [comment]
I like this idea a lot!

One thing to consider: In the cases where the feed is unreachable (firewall, etc), we'll need a fallback. 

I suggest we put a message that says "Cant reach Grafana.com, click here to poke holes in your firewall to get official updates."

This has two intentions:
- Avoid having a dead panel on the default home screen, offering no value and taking up space. 
- Open up communication between G.com and their instance, which will be useful when we start offering additional GCloud benefits (dashboard backups, etc). 

I also like the idea of later adding some basic filtering within the panel that could let people just filter out News (to include releases), Plugins & Dashboards.

**Comment by torkelo** [comment]
@Ijin08 if you want you can take a stab at a mockup for this. Think of it like a very simple rss news feedpanel where each item has a title, date and html body

**Comment by Ijin08** [comment]
Here is what I have at the moment:
![news-feed-panel3](https://user-images.githubusercontent.com/23470681/35510952-6ac79400-04fa-11e8-880c-a8321a81d929.png)

**Comment by SkyMoCo** [comment]
Would this allow any rss feed to be displayed?

**Comment by torkelo** [comment]
that is the idea yes.

**Comment by Ijin08** [comment]
Added external link color and author. Also made cards a bit bigger.
![news_feed_v2](https://user-images.githubusercontent.com/23470681/35799748-05193e3e-0a67-11e8-9e13-2f3076dacaea.png)

**Comment by Ijin08** [comment]
Made some small changes:
![news_feed_v2 1](https://user-images.githubusercontent.com/23470681/35813929-2292df1e-0a95-11e8-81b0-259cd512e9c9.png)

**Comment by mattttt** [comment]
I like it, and the blue headline aligns with our link convention. 👍 

Couple notes: 
1. When you click, i think it should open in a new tab. 
2. What doess the failure state (as mentioned above?)
3. Should we mark announcements from Grafana.com in some special way, denoting that they are "official"? Especially if people can subscribe to multiple feeds, it's a nice way of having important Grafana content bubble up to the top. 

I quite like the simplicity of it. I think it's a great feature.

**Comment by Ijin08** [comment]
@mattttt I missed the part with failure state and agree with your points. 
Regarding filters I guess the panel could have a edit page like the other panels where one can set filters and rss feeds. 
Here I added grafana orange to Grafana feed to make it stand out:
![news_feed_v4](https://user-images.githubusercontent.com/23470681/36032687-1594b1ee-0daf-11e8-96dc-83494883c26b.png)

I have also played with the idea of adding Grafana logo but not gotten it to work yet.

**Comment by torkelo** [comment]
> Should we mark announcements from Grafana.com in some special way, denoting that they are "official"? Especially if people can subscribe to multiple feeds, it's a nice way of having important Grafana content bubble up to the top.

Think we can this can be done with the Author line maybe, like "Grafana Release" , "Timeshift", "Panel Update". Maybe not super clean.

Not sure need to support multiple feeds in the same panel, one will do. 

Would like to get panel updates into this panel as well sop we can get rid of the installed plugins panel.

**Comment by Ijin08** [comment]
Here are three versions where news from grafana are stands out from the rest:
![news_feed_v5](https://user-images.githubusercontent.com/23470681/36037299-abcfc042-0dbc-11e8-89ae-dc040c92515b.png)

**Comment by mattttt** [comment]
Talked to @Ijin08 this morning for a bit. 

- Like the right most one with only two states for the headline (warning and then blue link). Introducing the third color makes things very busy imo. 
- Move the RSS logo out of the panel header. Not a current convention and would prefer to use the icon within the panel. 
- Have a default news icon (rss icon, perhaps) for all non-official news items. We'd also encourage people to upload/link to their own icon for their custom feeds. 

Also discussed, moving icons to the right so we have a consistent vertical baseline for titles and isnt reliant on icons.

**Comment by Ijin08** [comment]
![news_feed](https://user-images.githubusercontent.com/23470681/38494157-1b0a4174-3bf5-11e8-8bd7-cc6677ccfc32.png)

**Comment by fyang13** [comment]
It will be nice if the RSS feed panel can be made to show up regardless whether the user's using default dashboard or their own dashboard. This way, we can use that RSS feed to display important notifications to our user.

**Comment by lsward-netwkr** [comment]
Hi, I just wanted to ask if there has been any progress with this issue at all? I'm using a private NetVibes dashboard at the moment and have been wanting to provide access to the news and information sources I use to my team along with information useful to us through the other plugins so I can pull in data from SQL data sources and present them in the same view.

**Comment by philzis** [comment]
I might have missed something. But is this panel already available? I can't seem to find it.

**Comment by mikelindsay** [comment]
Is there an updated link for this?

**Comment by JM1888** [comment]
Do you know a date when this will be completed?

**Comment by abaddon82** [comment]
Does this mean that there are no plans to implement this for the time being?

**Comment by kaldm** [comment]
This would be really useful as I could then create a Jira dashboard with the associated github rss feed

**Comment by XedMada** [comment]
This would be very welcome. I'm currently maintaining an annoying node-red flow to store GitLab atom feeds in influxdb. Much rather just have a feed panel like pictured above.

**Comment by XedMada** [comment]
Looks like this is [now live in 6.6.9](https://grafana.com/blog/2020/01/27/grafana-v6.6-released/#news-panel) thanks to #21128 ! 🎉
