### ISSUE TITLE
Singlestat sum problem

### ISSUE THREAD

**Issue by felixPG** [grafana/grafana#9518]
Hi all:

Im using singlestat panel to show a result of a simple operations like this:

**(kubelet_running_pod_count{instance="$name"} * 100) / sum(kubelet_running_pod_count)**

If I make this operation with a **number** instead of **sum** like:  **(kubelet_running_pod_count{instance="$name"} * 100) / 10** then singlestat show the correct number. So why I cant pass a sum to a division??? With **sum(kubelet_running_pod_count)** I get an integer number, so What is wrong here?

**Comment by torkelo** [comment]
Not sure, not an expert on how Prometheus does math expressions. 
Ask on our community site (https://community.grafana.com)
