### ISSUE TITLE
Docs: Remove old version notices from Grafana docs

### ISSUE THREAD

**Issue by irenerl24** [grafana/grafana#95190]
**Why is this needed**:

We want to remove old version admonitions to align with timeless documentation.

**Who is this feature for?**

All readers of documentation

**List of admonitions to be deleted:**  

[Versions in Grafana documentation](https://docs.google.com/spreadsheets/d/1-MCsfJHtV0I0RlE6Wdq38wI9So_SInYT7H3d-O4E_kk/edit?usp=sharing)

**Comment by jtvdez** [comment]
I've made a copy of the spreadsheet to track initial categorization of the references (things that can be easily removed/reformatted, things that should stay, and things I need to talk to other squads about before moving forward)

https://docs.google.com/spreadsheets/d/11VgIpADm9A88BR7ji_Rk1yTyjVkl5PYJxXPBLFji0SA/edit?usp=sharing

I also found some versioning instances that were missed by the initial regex used to create the original spreadsheet. Things like "Grafana X.X" or anything called "version X.X" slipped the search. I brought it up to @jdbaldry who implemented a new regex and put the output of the latest run in the "More versions" tab - I also believe it is the most up to date as a fair amount of versioning mentions were pruned by @robbymilo, so I am currently using that tab to track the categorization work

**Comment by jtvdez** [comment]
I've completed the initial categorization and made a PR covering initial bulk removal of the easier-to-remove versioning information (anything that doesn't significantly impact the doc in some way that might require some additional edits such as updated screenshots, JSON payloads, or other clarification from the squad who works on the area the impacted doc covers). I just need to verify all currently impacted docs look correct in a local build and then this first PR should be ready for review.

**Comment by jtvdez** [comment]
I've finished the review of the local build and all looks fine. Also resolved a small merge conflict and the initial PR is ready for review.
Next steps for me is to reach out to the squads who are responsible for the areas that need clarification before the edits can be made (deprecation notices, new JSON payloads, etc)

**Comment by jtvdez** [comment]
I've created and shared the following spreadsheet with the Grafana Backend squad who handles the HTTP API: https://docs.google.com/spreadsheets/d/1Xao99NwMX6CDTd1KridvmnobZS6gCOxUNBfMuzN7Azk/edit?usp=sharing

It has the same information as the original spreadsheet with added columns for my questions, proposed action, and feedback from the squad

**Comment by jtvdez** [comment]
I've created and shared a similar spreadsheet for areas the Grafana Operator Experience is responsible for:
https://docs.google.com/spreadsheets/d/1Qla5s6DZ3lQm1C0PiBbzcEyATdfNWgO-rbuZqvAChik/edit?gid=0#gid=0
