### ISSUE TITLE
How to make a link from main dashboard to an internal dashboard

### ISSUE THREAD

**Issue by ebikargar** [grafana/grafana#9520]
Hi folks, 
I have a question; I would like to design a dashboard that gives me this possibility : 
from a general dashboard that represent some of the general metrics , by selecting specific template variable I could be able to direct to an internal dashboard with different panels from the main dashboard.

* After selecting an specific template variable I do not want to represent the panels included in the first dashboard anymore.
Any help/idea on this is appreciated.

**Comment by bergquist** [comment]
Please ask questions on our community site https://community.grafana.com/
