### ISSUE TITLE
[BUG] Prometheus editor does not auto complete on vector range 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#9521]
`rate(up[` <- should trigger auto complete and suggest `1s, 5s, 10s, 30s, 1m ....` 

If you start the query with just `[` the auto complete will trigger.
This seems like a regression bug.

**Comment by bergquist** [comment]
@mtanda any chance you could look into this?

**Comment by mtanda** [comment]
will take a look :-)

**Comment by bergquist** [comment]
Well done! this will be included in v4.6.0-beta3 we also include $__interval and $__interval_ms as suggestions
