### ISSUE TITLE
[Bug] Failed to parse /etc/grafana/grafana.ini at startup (configuration in env variables)

### ISSUE THREAD

**Issue by vineus** [grafana/grafana#9522]
- What Grafana version are you using?
4.6.0-beta1
- What datasource are you using?
(irrelevant)
- What OS are you running grafana on?
official grafana from docker hub (https://hub.docker.com/r/grafana/grafana/) running on AWS ECS
- What did you do?
launched grafana docker container with configuration values passed as env variables. Works like a charm on 4.5.1
- What was the expected result?
grafana launching successfully
- What happened instead?
container stopped, logging the error:

```
Restart grafana after installing plugins . <service grafana-server restart>
t=2017-10-13T13:31:52+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini., open /etc/grafana/grafana.ini.: no such file or directory%!(EXTRA []interface
{}
=[])"
```

**Comment by bergquist** [comment]
Could you share the parameters you used to start the container?

**Comment by bergquist** [comment]
Seems to be related to https://github.com/grafana/grafana-docker/issues/106

**Comment by bergquist** [comment]
build status https://circleci.com/gh/grafana/grafana-docker/2487

**Comment by vineus** [comment]
@bergquist : the latest docker build fixed the issue, thanks a lot!
