### ISSUE TITLE
[Bug] Upgrading from 4.5.2 -> 4.6.0-beta1, Cloudwatch data source no longer works

### ISSUE THREAD

**Issue by jleclanche** [grafana/grafana#9523]
4.6.0-beta1 / Cloudwatch / Debian Jessie

Request payload:

```json
{"from":"1507321037465","to":"1507925837465","queries":[{"refId":"A","intervalMs":600000,"maxDataPoints":851,"datasourceId":2,"type":"timeSeriesQuery","alias":"","application":{"filter":""},"dimensions":{"FunctionName":"twitch-hdt-ebs-live"},"functions":[],"group":{"filter":""},"host":{"filter":""},"item":{"filter":""},"metricName":"Duration","mode":0,"namespace":"AWS/Lambda","options":{"showDisabledItems":false},"period":420,"region":"us-east-1","statistics":["Average"],"from":"zone","metrics":["queryCount"],"filters":[]}]}
```

Response:

```json
{"message":"Metric request error"}
```

-----

I figured before hitting submit that this was caused by my usage of a .aws/credentials file. Seeing as I was on the official repo's build and upgraded to the beta deb, there must have been some issue with permissions there during the upgrade. I switched to setting the access key and now it works fine.

I think this is still actionable though:

1. The data source was claiming to be working when hitting "Save & Test" even though it clearly was not. Even putting in a fake access key/secret key would still cause it to claim to be working. Hitting Save & Test should probably validate that the credentials are valid by hitting some AWS API.
2. I'm not entirely sure this is expected to happen in the upgrade. I didn't bother getting the credentials file working.
3. Is the credentials file validated and checked on save & test? Same as point 1.

**Comment by jleclanche** [comment]
May have spoken too soon. There seems to be a change in behaviour with cloudwatch metrics which is causing queries over a timespan > 24 hours to fail with this error.

**Comment by jleclanche** [comment]
There is also a regression with the AWS/S3 metrics. NumberOfObjects Average and BucketSizeBytes Average are no longer queryable at all -- shows No data points when it doesn't error.

**Comment by mtanda** [comment]
I fix query error in https://github.com/grafana/grafana/pull/9536 .
Sorry for bug, and thanks for reporting it.

About "Save & Test" behavior, I can't replicate it in my env.
> The data source was claiming to be working when hitting "Save & Test" even though it clearly was not. Even putting in a fake access key/secret key would still cause it to claim to be working. Hitting Save & Test should probably validate that the credentials are valid by hitting some AWS API.
