### ISSUE TITLE
Loki: Add shard splitting as a new query direction for logs

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#95233]
With the objective of improving needle-in-a-haystack type of queries, we're adding shard splitting as a new query direction in the data source, called `Scan`. Scan will attempt to query individual `__stream_shard__` labels if present. If the data is not sharded, it will fall back to time-based splitting.

Requires the feature flag `lokiShardSplitting`.

Tasks:
- [x] Integrate Scan with Explore
- [x] Let users know what happened if one of the volume shards time outs
- [x] Update or disable infinite scroll
- [x] Add Beta/Experimental badge
- [x] Double check handling of queries with errors
- [x] Shard metric queries when the flag is enabled

**Comment by matyax** [comment]
This is done.

**Comment by mveitas** [comment]
@matyax What sort of performance improvement have you seen with this change?

**Comment by matyax** [comment]
@mveitas If your Loki data is distributed across shards (represented by the`__stream_shard__` label), using the new query direction for needle-in-a-haystack type of queries there's a chance of producing the first result quicker.
