### ISSUE TITLE
[Bug] Templating constant type variable being escaped

### ISSUE THREAD

**Issue by ricardoj-br** [grafana/grafana#9524]
Please include this information:
- What Grafana version are you using? 4.5.2
- What datasource are you using? Elasticsearch 5.6.2
- What OS are you running grafana on? Ubuntu 16.04
- What did you do? Created a Template with Variable Type Constant

I’m using Elasticsearch as the datasource and created a template to make the Dashboard update when some fields are changed.

So I created a template with 3 variables and one of them is of type constant.

The constant type variable is to be filled by user with numbers that can have dashes “-” in it. This is a Zip Code for Brazil so I can have only the first 5 digits like 12345 or the full Zip Code like “12345-678”.

When I put the first 5 digits it works as expected and the Dashboard is updated with the correct values.

When I put the full Zip Code with “-” in constant type variable it seems like the query sent to Elasticsearch is not correct.

I used the browser to investigate what is going on and noticed that variable is escaped like that “12345\-678”.

Is there any workaround ?

Is there any other way to let customer input the Zip Code ? 

I also tested the query in the Panel | Metrics | Query and the “-” works. The problem is only related to the template variable.

I've found this issue  ( https://github.com/grafana/grafana/issues/5314 ) on GitHub and this bug is supposed to be fixed.

Thank you in advance. Regards,

Ricardo

**Comment by torkelo** [comment]
I am unable to replicate any issue. Escaping "-" is correct in a lucene value. 

For example when I query for a hostname that contains "-" it works with both for custom and constant variables. 

![image](https://user-images.githubusercontent.com/10999/31709054-26092ed2-b3f1-11e7-92b6-d8ab4f0f3d73.png)

**Comment by ricardoj-br** [comment]
Hi Torkel,

     Did you try in a Constant Type variable as I mentioned ?

     What I need is a way to enter a value so the customer can query 
what he / she want to and not something that is in a combo box as you did.

     In my case I'm entering values like "12345-678" and the dash is 
escaped.

     If I put the value in the query field it works as well but not in 
the Constant Type variable.

     Thank you so much for your reply and attention.

     Regards,


             Ricardo Jorge


Em 18-10-2017 06:44, Torkel Ödegaard escreveu:

**Comment by torkelo** [comment]
Yes I tried constant type. Dash should be escaped otherwise it will not match. There are open feature request to disable escaping and another issue to create free input variables

**Comment by ricardoj-br** [comment]
Hi Torkel,

     If you need to escape dash why the Elasticsearch fails with that 
escaped dash ?

     As I told you if I put a dash in the query field it works but not 
in Constant Type variable.

     That is why I guess this is a bug and not the expected behavior.

     What I need and maybe others, is something like the Kibana search 
field.

     Without a filed that user can input values, "templating" is incomplete.

     Just to have an idea the CEP ( Brazilian ZIP code ) field I want to 
search for has more than a million options and it is not possible to 
feed them in a combo box as you did in your demonstration with a bunch 
of servers and hosts.

     If I can not use Constant type variable, because dash is being 
escaped what else could be done ?

     Thank you again for your attention.

     Regards,


             Ricardo Jorge


Em 18-10-2017 12:26, Torkel Ödegaard escreveu:

**Comment by torkelo** [comment]
What index type does the zip code field have?

When I search a string in lucene and don't enclose it in quotes you need to escape dash (according to ES docs)

Free form search variable is something we are missing

**Comment by ricardoj-br** [comment]
Hi Torkel,

    I tried with and without quotes in the Constant Type variable.

    No matter the way I input the CEP ( Brazilian ZIP code ) the query fails.

    In the Query field if I manually put the value it worked as expected.

![image](https://user-images.githubusercontent.com/20463353/31793826-19985d26-b4ff-11e7-9240-88eedfd30476.png)

    The field is named "ceps" as you can see above and is of type "string" in Elasticsearch.

    Thank you so much for your attention.

    Regards,

            Ricardo Jorge

**Comment by torkelo** [comment]
Strange, I wonder why it's  it working for you. What ES version are you using?

**Comment by ricardoj-br** [comment]
Hi Torkel,

What Grafana version are you using? 4.5.2
What datasource are you using? Elasticsearch 5.6.2
What OS are you running grafana on? Ubuntu 16.04

    Thank you,

            Ricardo Jorge

**Comment by torkelo** [comment]
so you specify in query field: `ceps.keyword:123\-123`   (if that is a valid zip code that exists) it does not work for you? It works for me. and is correct according to ES docs.

**Comment by ricardoj-br** [comment]
Hi Torkel,

    1) I don't need to escape the dash character in Grafana Query field. I just put NNNNN-NNN and it works

![image](https://user-images.githubusercontent.com/20463353/31838767-0c08b1b0-b5bd-11e7-986b-0898eb1d76e9.png)


    2) in the Grafana Query field, ".keyword" does not word I just use "ceps"

![image](https://user-images.githubusercontent.com/20463353/31838833-3d1ab32a-b5bd-11e7-9ec4-f1b3313fab3c.png)


    3) The escaped dash happened automatically when I insert the full CEP ( NNNNN-NNN ) in the Constant Type variable field.

     Escaped dash is not a must in the Elasticsearch.

     What you need in Elasticsearch is quotes.

     Thank you again. Regards,

            Ricardo Jorge

**Comment by rangsan** [comment]
+1. Exactly same problem with constant variable.
