### ISSUE TITLE
[UX]: v5 Dashboard Header Design

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9529]
Needs some feedback & help with v5 dashboard header design. 

Challanges / Question marks

1) Should it have a background and shadow? 

Like: 
<img width="1279" alt="screen shot 2017-10-15 at 12 45 19" src="https://user-images.githubusercontent.com/10999/31584052-bf5c39dc-b1a6-11e7-94b7-fd02c22aa0d7.png">

2) Without background

<img width="1280" alt="screen shot 2017-10-15 at 12 42 14" src="https://user-images.githubusercontent.com/10999/31584054-cce4ba98-b1a6-11e7-80f2-6aec9ceb11e9.png">

That screenshot is also testing to clean it up. Move share action hamburger menu icon (instead of settings icon). Move time move arrows to left and right of time range. Where to put zoom out ? Zoom out is hard to convey as a icon, so maybe just  text link to right of time range? (to left of refresh icon). 

3) Here is the same design with template variables:
<img width="1280" alt="screen shot 2017-10-15 at 12 43 26" src="https://user-images.githubusercontent.com/10999/31584066-16951dea-b1a7-11e7-8321-265c2cc6521e.png">

4) What do do with Add panel button, feels a bit off in terms of design. Where to put add row option? Maybe add row can be as an option in the add panel view (add panel view is currently going to be a sort of panel that then morphs into the panel of choice)

**Comment by phemmer** [comment]
Well I have very little opinion on the shadow/background thing as it doesn't make a significant difference to me.
However one thing that jumps out at me is the side bar. I can't say I'm very fond of it. I like in the current version (<5.0) all that stuff being up at the top as it's out of the way. Putting it on the side means you're always going to have this thing there that takes up space, and you can't scroll down to get rid of. It takes away from the clean look of having nothing but panels on the screen.

But yes, also agree with add panel being weird. Its weird in current version too, just no bright ideas how to better handle it. Add row I don't have any issues with.

**Comment by torkelo** [comment]
> However one thing that jumps out at me is the side bar. I can't say I'm very fond of it. I like in the current version (<5.0) all that stuff being up at the top as it's out of the way. Putting it on the side means you're always going to have this thing there that takes up space, and you can't scroll down to get rid of. It takes away from the clean look of having nothing but panels on the screen.

You can toggle (hide) sidemenu like you can in today
