### ISSUE TITLE
[Feature Request] Add cron format for Grafana alerting

### ISSUE THREAD

**Issue by zhangjiang2013** [grafana/grafana#9533]
Since version 4, Grafana supports the alerting feature. But current alert configuration only supports the execution by some time interval. 
<img width="799" alt="alert" src="https://user-images.githubusercontent.com/7018709/31589230-125dcfc2-b1b3-11e7-98fb-659d2ac1101f.png">

Is that possible to add the [cron format](http://www.nncron.ru/help/EN/working/cron-format.htm) to schedule the job execution, just like Jenkins does. For example, `*/5 * * * *` means every 5 minutes.

**Comment by bergquist** [comment]
Thank you for sharing your idea but I don't see us adding this. The cron format is famous for being hard to remember and reason about. It might be ok when used in a text file but since Grafana has a rich UI it should be possible to create a much better experience.

**Comment by thibentran** [comment]
The idea of the cron is interesting (with a rich user experience or not). For instance, we have to monitor a process that is triggered once a day. Thus, we would like to have an alert that check the state only once a day (some minutes after the triggering of the process).

**Comment by Donderia** [comment]
> The idea of the cron is interesting (with a rich user experience or not). For instance, we have to monitor a process that is triggered once a day. Thus, we would like to have an alert that check the state only once a day (some minutes after the triggering of the process).

+1

**Comment by Donderia** [comment]
There should a way to restrict alerts at particular instance of time like every day 1 AM in night.
