### ISSUE TITLE
Checksum of OSS Linux standalone binaries doesn't match

### ISSUE THREAD

**Issue by hasso** [grafana/grafana#95346]
### What happened?

Download page states that checksum of OSS Linux standalone binaries must be c9b03d6e8c117602647bcab278b0c657792bd29aa0b2beec854dc3be07329d73

```
$ wget https://dl.grafana.com/oss/release/grafana-11.3.0.linux-amd64.tar.gz
...
$ shasum -a 256 grafana-11.3.0.linux-amd64.tar.gz
5058c67fc0ff6e209992fb3bd5884f08ac379276eecd8fc810ffb5de2e7ae8c3  grafana-11.3.0.linux-amd64.tar.gz
$
```

### What did you expect to happen?

Checksums match.

### Did this work before?

With previous releases, yes.

### How do we reproduce it?

1. Download.
2. Check checksum.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by Proximyst** [comment]
This is indeed reproducible. Every single OSS release format has wrong SHA256 sums, not just the standalone binaries.

**Comment by Proximyst** [comment]
The website has been updated :)
Thanks for flagging this!
