### ISSUE TITLE
[Bug] Missing image from webhook Grafana 4.5.2

### ISSUE THREAD

**Issue by sonchu** [grafana/grafana#9535]
Hi there,

Please take a look at below and advise.

- What Grafana version are you using?
4.5.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Centos 7

- What did you do?
Create alert for specific metric using WebHook

- What was the expected result?
An alert with imageUrl in json string (Please note that i have enable "include image" feature in webhook config).

- What happened instead?
The alert result returned without imageUrl. Below is example for my testing alert.

`{"evalMatches":[{"value":58.921000480651855,"metric":"win_cpu.% User Time","tags":null}],"ruleId":1,"ruleName":"CPU Usage alert","ruleUrl":"http://localhost:3000/dashboard/db/telegraf-and-influx-windows-host-overview-copy?fullscreen\u0026edit\u0026tab=alert\u0026panelId=7\u0026orgId=1","state":"alerting","title":"[Alerting] CPU Usage alert"}`
 
This didn't happen when i test with version 4.4.2. Please advise.

Thanks a lot in advance.

**Comment by torkelo** [comment]
you need to configure an external image store for that. http://docs.grafana.org/installation/configuration/#external-image-storage

**Comment by maslick** [comment]
@torkelo what about the local image store? It seems it works only with an external image store :(
