### ISSUE TITLE
Not able to keep Null values in Grafana Table.

### ISSUE THREAD

**Issue by akshay26931510** [grafana/grafana#9542]
Hi,
I am using the Grafana Version 3.1.1 with ElasticSearch as datasource.

I have created a table in Grafana by Grouping all the Term values i needed.
For some of the columns there are Null values in some rows.
But when the table is shown in dashboard, rows with the Null values in data are not shown in the table.
But i want to show all that rows with Null values as well.

kindly Help...!!!!

**Comment by akshay26931510** [comment]
Hi, 
I am using the Grafana Version 3.1.1 with ElasticSearch as datasource.

I have created a table in Grafana by Grouping all the Term values i needed.
For some of the columns there are Null values in some rows.
But when the table is shown in dashboard, rows with the Null values in data are not shown in the table.
But i want to show all that rows with Null values as well.

kindly Help...!!!!

**Comment by torkelo** [comment]
make sure you have min doc count set to zero if you want null (missing) terms.

Please use community site for questions and include your query and the response from ES
