### ISSUE TITLE
Adding Hyperlink to a new Dashboard on Column Values in Grafana Table. 

### ISSUE THREAD

**Issue by akshay26931510** [grafana/grafana#9543]
Hi,
I am using the **Grafana Version 3.1.1** with **ElasticSearch** as datasource.

I have created a table in Grafana by Grouping all the Term values i needed.
Is it possible to add the ****hyperlinks on column values in grafana** Table** on click of which i can show the new dashboard in new window. 

kindly Help...!!!!

**Comment by torkelo** [comment]
Yes, available in Grafana v4.3 I think
