### ISSUE TITLE
[Feature request] Table panel and text align center column style option

### ISSUE THREAD

**Issue by Turum** [grafana/grafana#9544]
Hi team,
It would be great if 
1. I could align values at the edges (left,right, etc.) of a cell of the table or center them.
Thanks.
2. Column Styles - Add a space or comma as thousands separator for numbers.

Thanks in advance.

**Comment by yigangzhang** [comment]
On prod, we have the use case to right align the text in a table. Can we have an option to left/center/right align the text for table?

**Comment by ketan12sharma** [comment]
+1
This feature will be great to have.

**Comment by ingoscarn** [comment]
it would be aweson that al the parameters about the text of a table were modifiable

**Comment by ketan12sharma** [comment]
@ingoscarn @sanchomuzax If your column contains a few values overall like 5-10, I would suggest that you can go to column styles, Change the type to string and in mapping specify as below e.g.
Value:"Pass" --> Mapping <center>Pass</center> 
make sure that you check the sanitize HTML, so the column data will be aligned to center.

**Comment by stefaanv** [comment]
@ketan12sharma,
I don't understand your last comment.  I have a column 'heating', but when I apply the trick you suggest, nothing happens at all.  

I applied these settings
- Type: String
- Sanitize HTML: Checked
- Type: Value to text
- Mapping: heating -> \<span align="right"\>heating\</center\>

Can you suggest me the correct HTML formatting ?
Also, I see that the value is display with as many decimals as will fit in the column.  Is there a trick to set the number of decimals as well ?

**Comment by paulkukk** [comment]
I able to right, left, or center justify a value in a column by adding HTML to my sql statement. Example '<div align=right>'||x."Prospect Score"||'</div>' as "Prospect Score". The html then is used inside the column and justifies the value be returned. Hope this helps

**Comment by ketan12sharma** [comment]
> @ketan12sharma,
> I don't understand your last comment. I have a column 'heating', but when I apply the trick you suggest, nothing happens at all.
> 
> I applied these settings
> 
> * Type: String
> * Sanitize HTML: Checked
> * Type: Value to text
> * Mapping: heating -> <span align="right">heating</center>
> 
> Can you suggest me the correct HTML formatting ?
> Also, I see that the value is display with as many decimals as will fit in the column. Is there a trick to set the number of decimals as well ?

Hi, @stefaanv ,
As per your HTML <span align="right">heating</center>, you need to correct the tag's scope here, `<center>Heating</center>` is a correct HTML5 directive, You dont need to use span here. 

For your second question, you need to set the ColumnStyles >> Select your Column name >> Set type to number >> and in the unit and decimals you can specify whatever you like.

Hope it helps :)

**Comment by hokgt** [comment]
> I able to right, left, or center justify a value in a column by adding HTML to my sql statement. Example `'<div align=right>'||x."Prospect Score"||'</div>' as "Prospect Score"` The html then is used inside the column and justifies the value be returned. Hope this helps

@paulkukk 
I tried this but all the records value return 1 
<img width="956" alt="Screen Shot 2019-06-23 at 00 05 44" src="https://user-images.githubusercontent.com/15005756/59966740-c82cab80-954a-11e9-98dd-1a180665067e.png">
In column styles, type String and Sanitize HTML is ticked
<img width="1063" alt="Screen Shot 2019-06-23 at 00 06 27" src="https://user-images.githubusercontent.com/15005756/59966752-f01c0f00-954a-11e9-9f64-875f35312eb7.png">
Am I positioning the HTML syntax wrong? 
Thank you

**Comment by RedShift1** [comment]
> I able to right, left, or center justify a value in a column by adding HTML to my sql statement. Example `'<div align=right>'||x."Prospect Score"||'</div>' as "Prospect Score"` The html then is used inside the column and justifies the value be returned. Hope this helps

That works but the HTML code shows up when you export the table to CSV.

**Comment by beingyash** [comment]
Text alignment option is available in table panel settings but that doesn't work for column header. So, upon applying an alignment, values in all cells of respective column shift as per the alignment but hte header doesn't, which makes this arrangement look absurd.

**Comment by supilee** [comment]
Works in current version with both, header and values.

https://user-images.githubusercontent.com/110845248/219969680-69a024aa-9290-4731-abb0-2d033a5115c5.mov
