### ISSUE TITLE
Some visualization panels are unavailable in version 11.3

### ISSUE THREAD

**Issue by stqf** [grafana/grafana#95447]
### What happened?

Start method docker Start command: `docker run -d --name grafana -p 30000:3000 grafana/grafana:11.3.0`

1. Trend
![Image](https://github.com/user-attachments/assets/b60d0cf3-cd53-4306-8f2f-21b78543453a)
2. Flame Graph
![Image](https://github.com/user-attachments/assets/dad37c66-fc76-439c-8df3-d4f7951f9647)
3. XY Chart
![Image](https://github.com/user-attachments/assets/4d8773e2-a915-4c3c-a2f8-792d067beafd)

The F12 error is as follows
![Image](https://github.com/user-attachments/assets/8d56acfc-5a16-45ab-9efa-2d1952f10602)

Measures already taken
1. Install Trend separately, command grafana-cli plugins install snuids-trend-panel
2. Delete the container and restart
Thank you

### What did you expect to happen?

Can be used normally

### Did this work before?

First time use

### How do we reproduce it?

![Image](https://github.com/user-attachments/assets/803a1e8c-2d19-4b45-9d7c-6e3d14c52a4a)

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 11.3
OS: docker
Browser:  chrome

### Grafana platform?

None

**Comment by nicoledroi1** [comment]
I am facing a similar issue when I create an XY graph I get the Err message. I noticed this issue persists after 11.1.8. It seems every version after and including 11.2 has this issue.
