### ISSUE TITLE
Grafana 11.3 : can't move and resize panels

### ISSUE THREAD

**Issue by Korsani** [grafana/grafana#95449]
### What happened?

Since upgrade to 11.3, I can't move and resize the panels anymore. The mouse doesn't turn to cross when hovering panel, neither handle is available at the bottom right.

### What did you expect to happen?

Same as 11.2 : ability to move and resize panel

### Did this work before?

Yes, in 11.2

### How do we reproduce it?

1. upgrade to 11.3
2.
3.

### Is the bug inside a dashboard panel?

i don't think

### Environment (with versions)?

Grafana: 11.3
OS: Debian Bookworm on RPi 4
Browser: Firefox latest, Safari latest

### Grafana platform?

None

**Comment by Proximyst** [comment]
Do you have permissions to modify the dashboard you're trying to edit?

---

Can't reproduce; dashboards are fully editable. Test environment:

```yaml
# docker-compose.yaml
services:
  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
```
Dashboard tested with 1 panel of Random Walk.

**Comment by Korsani** [comment]
Hi,
I can edit and move panel on 11.2.3.
I tested debian packages v11.3.0 downloaded from dl.grafana.com/oss/release and package from apt.grafana.com : same error (I was surprised that both packages, although they have the same version, their checksum differs)

Did you test on rasperry pi ?

**Comment by Korsani** [comment]
Hi,

I didn't try a fresh grafana install. i'll do

**Comment by Nemric** [comment]
:/ perhaps you already notice this, but there is a new "edit mode" that can be activated at the upper right corner of dashboards

**Comment by Korsani** [comment]
> :/ perhaps you already notice this, but there is a new "edit mode" that can be activated at the upper right corner of dashboards

AaaaAAAAHHHH !!! I didn't notice... :/

Okay, that will be a feature request : a guided tour on version update :)

**Comment by Proximyst** [comment]
Feel free to open a feature request for that, in that case :)
