### ISSUE TITLE
[Bug] Dashboard row 'repeat for variable' broken

### ISSUE THREAD

**Issue by dimrozakis** [grafana/grafana#9547]
I have a dashboard with a template variable (that allows multi/all selection, and reload on time range change) and a row that repeats for that variable. More often that not, the row title (which is the value of the variable), doesn't match the row contents.

See the screenshots below. The rows stay consistent, they don't exchange graphs, that is to say that all graphs of a certain row are evaluated with the same variable value. But for row names, it seems like the variable value assigned to each row name doesn't correspond to that assigned for each row graph evaluation.

![c](https://user-images.githubusercontent.com/5428237/31625797-102c0662-b2b0-11e7-9ec7-9aa1a90e0eca.png)
![b](https://user-images.githubusercontent.com/5428237/31625799-1056156a-b2b0-11e7-9818-07145aaa4ab0.png)
![a](https://user-images.githubusercontent.com/5428237/31625800-107ad99a-b2b0-11e7-8c11-543c364e9b3b.png)

Please include this information:
- What Grafana version are you using?
  - latest docker image
- What datasource are you using?
  - prometheus
- What OS are you running grafana on?
  - official docker image

**Comment by torkelo** [comment]
When does this happen, when you change the template variable value or time range refresh? What is the variable options (for the variable you repeat by). Does it return values in consistent order?

**Comment by dimrozakis** [comment]
>When does this happen, when you change the template variable value or time range refresh?

On time range refresh, or when manually the refresh button on the top right corner of the dashboard.


>What is the variable options (for the variable you repeat by).

![settings](https://user-images.githubusercontent.com/5428237/31628008-eec4fbc0-b2b7-11e7-98af-df9b2ac52b8a.png)


> Does it return values in consistent order?

When I select `All`, after every reload, the order of values in the variable drop down is different, and matches the order of row names (but not contents). I also get the same issue when I select a subset of the values (multi-value).

**Comment by dimrozakis** [comment]
Yes, I can no longer reproduce the issue after configuring the `Sort` option on the query options of the template variable.

But shouldn't it work even with inconsistently sorted values? Isn't this still a bug?

**Comment by torkelo** [comment]
No, it will assume consistency, especially when refresh on time range change (variables that update on time range change is not fully supported when combined with repeated panels or rows)

**Comment by dimrozakis** [comment]
I see. Do you think that it'd perhaps make sense then to change the default 'Sort' option of template variables to anything other than 'Disabled'?

Also, is there any github issue, note in docs or elsewhere documenting the current limitations of template variables with repeating rows/panels? I wasn't aware there were any, I've actually several graphs with repeating rows and variables that update on time range change, mainly to deal with dynamic targets such as containers, kubernetes pods, autodiscovered cluster nodes etc.

**Comment by torkelo** [comment]
Sort is disabled so sorting is delegated to the time series db query.

No that limitation is not documented, should be :)
The problem is that panels will refresh on time range change, and not wait for template variable to update, so if repeat order is different then panels have already fetched data so will be out of sync with variable state
