### ISSUE TITLE
[Bug] Unknown provider: colorPickerDirective (v4.7.0-pre1)

### ISSUE THREAD

**Issue by petrslavotinek** [grafana/grafana#9549]
After downloading and building latest version - v4.7.0-pre1 (commit: 11e3876a1), color picker isn't working in any panel. Not even built-in panels.

Error message examples from Chrome console:
Heatmap panel:
[$injector:unpr] Unknown provider: tProvider <- t <- colorPickerDirective
and Graph panel:
[$injector:unpr] Unknown provider: tProvider <- t <- seriesColorPickerDirective

I checked built source and definition of directives colorPicker and seriesColorPicker is present.

OS - Windows 10.

Thanks for help.

**Comment by hathvi** [comment]
Can confirm I've been experiencing this the last few nightly builds at the least. I started pulling nightly docker builds since the postgres datasource merge and don't believe I've been able to set color in the series override options since at least then.

**Comment by torkelo** [comment]
thanks for reporting this, will investigate!
