### ISSUE TITLE
[Bug] Alerting to Sensu should put "Message" in output field

### ISSUE THREAD

**Issue by cjchand** [grafana/grafana#9551]
Please include this information:
- What Grafana version are you using?
v4.5.2 (commit: ec2b0fe)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
RHEL 6.9

- What did you do?
Created an alert notification, pushed to Sensu

- What was the expected result?
The contents of the `message` field in the Notification pane in Grafana should have been sent to Sensu in the `output` field, as many handlers (e.g.: PagerDuty, Slack, etc) will typically send the contents of this field to any upstream integration.

- What happened instead?
Instead, the contents of the `message` field in the Notification pane in Grafana are sent to Sensu in a field called `message` and the `output` field is hardcoded to say `Grafana Metric Condition Met`. 

As a result, instead of people seeing the contents of the `message` field - which has instructions and useful info about what the alert means and how to handle it - they see `Grafana Metric Condition Met`.

The `output` field is hardcoded here:
https://github.com/grafana/grafana/blob/314bff1b786d57065b8b80e569d5da8565d6f927/pkg/services/alerting/notifiers/sensu.go#L90

... with the, IMHO, mismapping of the Grafana `message` field happening here:
https://github.com/grafana/grafana/blob/314bff1b786d57065b8b80e569d5da8565d6f927/pkg/services/alerting/notifiers/sensu.go#L115

- If related to metric query / data viz:
N/A
 
I've never written anything in Go, but change seems simple enough. Let me know if you'd like me to submit a PR.

**Comment by bergquist** [comment]
A PR would be great. Would also be great if you could include a link to docs confirming this. Support for sensu is 100% provided by the community so we don't know the integration that well :)

**Comment by cjchand** [comment]
Submitted above PR for this. Tested locally, as shown via the screen shots.

For reference, the "output" field for the check result is where checks would put meaningful info for the operator. Source:  https://sensuapp.org/docs/latest/reference/checks.html#example-check-result-output

The prior behavior was to map a static bit of text to the output field, which was sub-optimal.

**Comment by cjchand** [comment]
New PR is green and should be all set: https://github.com/grafana/grafana/pull/9573

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9573
