### ISSUE TITLE
Label filter doesn't work in Query Variable

### ISSUE THREAD

**Issue by HanSJTU** [grafana/grafana#95532]
### What happened?

When i try to add label filters to my variable query result, it doesn't work. The previews of values show the same result whatever i put in the filters.

### What did you expect to happen?

The label filters works for the variable query results.

### Did this work before?

Yes.
It works in previous version of grafana. But it doesn't in the latest grafana image in Docker Hub. (I pulled the grafana image with latest tag on this Monday)

### How do we reproduce it?

My Datasource is Sherlock-PromQL. <!-- Uplo![Image](https://github.com/user-attachments/assets/39d14ae4-dfd0-49dd-8115-1ac115f7a5f0)

### Environment (with versions)?

Grafana: I pulled the grafana image with latest tag on this Monday (https://hub.docker.com/r/grafana/grafana/tags)
OS: MacOS 14.5
Browser: safari

### Grafana platform?

Kubernetes

**Comment by HanSJTU** [comment]
for more info. Below is the result i use explore to search for target metrics.
![Image](https://github.com/user-attachments/assets/8187d502-c430-45a3-b737-6acd116a54e0)

**Comment by seaburr** [comment]
I'm looking into a similar issue after upgrading from 11.0 to 11.2.1. I'm going to continue investigating tomorrow but I hope maybe these help you track down your issue, too. In our case, we're using Azure managed Prometheus.

https://github.com/grafana/grafana/issues/90318
https://github.com/grafana/grafana/issues/91034
https://github.com/grafana/grafana/pull/84778

**Comment by NWRichmond** [comment]
Hi @HanSJTU! In your Prometheus data source configuration (specifically, the [Performance](https://grafana.com/docs/grafana/latest/datasources/prometheus/configure-prometheus-data-source/#performance) section), do you have the Prometheus type & version set? If not, please set these and let us know if the issue persists.

**Comment by HanSJTU** [comment]
> Hi [@HanSJTU](https://github.com/HanSJTU)! In your Prometheus data source configuration (specifically, the [Performance](https://grafana.com/docs/grafana/latest/datasources/prometheus/configure-prometheus-data-source/#performance) section), do you have the Prometheus type & version set? If not, please set these and let us know if the issue persists.

Thanks for your hint! I change the data source configuration by setting the correct version. The issue is fixed.

**Comment by HanSJTU** [comment]
I will close this issue as it has been fixed.
