### ISSUE TITLE
Dashboard: repeating panel cannot be resized

### ISSUE THREAD

**Issue by LarsStegman** [grafana/grafana#95537]
### What happened?

I have a new panel that repeats for every Prometheus data source we have. The panel is too high, so I want to make it shorter. The resize handle is not shown, so this is not possible.

### What did you expect to happen?

On hover, the resize handle appears and I can change the height of the panel. If you first disable repeating, then resize, then reenable repeating it kind of works, but it resets the height back to 10 instead of new height.

### Did this work before?

Yes, in Grafana 11.2.2

### How do we reproduce it?

1. Create new dashboard
2. Go to edit mode
3. Add variable that contains multiple data sources
4. Add a new panel
5. Configure the panel to repeat for the data source variable
6. Go back to the dashboard
7. Try to resize the panel vertically, not possible

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.3.0
OS: Windows
Browser: Microsoft Edge

### Grafana platform?

Kubernetes

**Comment by kaydelaney** [comment]
Hi! Having trouble reproducing this issue on main - would it be possible for you to provide a video or screenshots of the issue to help us debug the problem? Thank you!

**Comment by LarsStegman** [comment]
While making the recording, I think I figured out how to do it. It's a bit confusing. Before you had to resize the first panel to change the height, but now it's the last panel.

https://github.com/user-attachments/assets/3ad94a27-3d6f-45a8-a45c-45fbf74c8d3a
