### ISSUE TITLE
[Feature request] allow user to choose a period of time series and comment it with label

### ISSUE THREAD

**Issue by baiwfg2** [grafana/grafana#9554]
Many times I use grafana and prometheus to perform testing such as benchmark test. As there're many factors that may influence results, when I change one factor which is a part of overall precondition, I get a piece of graph. In the end , I get many disconnected graph and they're the results of different situation, so that I can analyze what kind of role a factor is playing in the result . But I cannot remember which correspond to which. A lame way is to manually write down the time range of one graph and its corresponding preconditions in order not to forget their casual relation.

So is there any way to make it more conveniently such as give each distinct graph a kind of comment using label ?

Thanks.

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
You have a description field in the General tab

**Comment by baiwfg2** [comment]
That's a coarse-grained description. I want fine-grained description in terms of a time range which include a start time and a end time. I know it may sound a little superfluous, so I'll keep record manually

**Comment by baiwfg2** [comment]
Luckily I've found grafana has already implemented what I want. That's `annotation` feature in 4.6+. See http://docs.grafana.org/reference/annotations/
