### ISSUE TITLE
Alerting: "Could not set default permissions" receiver_uid="" error="pq: value too long for type character varying(40)"

### ISSUE THREAD

**Issue by trexx** [grafana/grafana#95542]
### What happened?

We're attempting to add a Contact Point with a name 46 characters long via the API / Terraform. This fails with an error message in Grafana stdout:

`"Could not set default permissions" receiver_uid="BLAH" error="pq: value too long for type character varying(40)"`
Where blah is a base64 encoded string of the Contact Point name.

Looking at the permission table in Postgres, the identifier field is of type varchar(40)

When looking closely at how the UID is generated I suspect the behaviour changed in this commit: https://github.com/grafana/grafana/commit/66522334934ef0f7b72b7cfa614df8b2485fcf5e

### What did you expect to happen?

The contact point gets added successfully

### Did this work before?

Yes. It worked previously in 11.2.1

### How do we reproduce it?

Instructions added above

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.3.0
OS: Windows
Browser: Edge

### Grafana platform?

Kubernetes

**Comment by JacobsonMT** [comment]
Hi @trexx, this issue has been [fixed](https://github.com/grafana/grafana/pull/95084) and will be available in the next patch release of 11.3.x
