### ISSUE TITLE
[Feat Req] Table panel links that change variables via url should trigger update

### ISSUE THREAD

**Issue by hathvi** [grafana/grafana#9556]
> -  What Grafana version are you using?

v4.7.0-pre1 (commit: 24a0eb9) - I've believe this issue was present in v4.5.0 as well.

> - What OS are you running grafana on?

Nightly docker build w Docker running on Ubuntu 16.04

> - What did you do?

Set a table cell to render as a link `/grafana/dashboard/db/debug-account-syncer?orgId=1&var-account_id=$__cell` to open in the current tab.

> - What was the expected result?

For the `account_id` variable to be set and queries updated.

> - What happened instead?

The URL is updated in the address bar but does not trigger any updates. I must focus the address input in my browser and press enter or set Grafana to open the link in a new tab.

**Comment by hugohaggmark** [comment]
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630). We're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
