### ISSUE TITLE
Dashboards: Missing default panel types (text, dashboard list) when creating a new panel

### ISSUE THREAD

**Issue by shih-chris** [grafana/grafana#95560]
### What happened?

I usually am able to create text or dashboard list panels, and checked that they were installed; however, they don't appear on my panel type drop down

![Image](https://github.com/user-attachments/assets/35cb09fb-7199-48df-8ee0-59db2037bba4)

### What did you expect to happen?

I expected to see Text and Dashboard List as panel type options when creating a new dashboard panel

![Image](https://github.com/user-attachments/assets/fdcf1797-3c14-49e8-b187-afd0dc901563)

### Did this work before?

I'm unclear what versions these instances are on specifically, but the ? icon shows that both of the above screenshots are on Grafana Cloud (fast)

### How do we reproduce it?

1. Create a new dashboard
2. Create a new panel
3. Click the panel type (visualizations) drop down
4. Search for "Text"

### Environment (with versions)?

Grafana: Grafana Cloud (fast)
OS: macos
Browser: Firefox

### Grafana platform?

None

**Comment by shih-chris** [comment]
For context, this is happening on bidev.grafana-ops.net. What's extra strange is that we can add a text panel via updating the JSON, so it appears the panel just doesn't exist in the panel type picker.

My (naive) assessment is that this sounds like more of an internal stack problem, rather than a core grafana issue, so I'll close for now until I can verify it's a core issue.

**Comment by kaydelaney** [comment]
It seems the `vizAndWidgetSplit` feature toggle is enabled on the instance in question, which seems to break some things in scenes.
I think the quickest fix in this case is to disable the feature toggle, and in the mean time I'll look into a longer term solution

**Comment by shih-chris** [comment]
That did the trick! Thanks @kaydelaney
