### ISSUE TITLE
How to configure grafana-cli to use the authentication proxy?

### ISSUE THREAD

**Issue by isaquelacerda** [grafana/grafana#9562]
I'm running Grafana in a Docker Centos 7 server linux.
I need to integrate the Grafana with Zabbix, for that I need to download the Zabbix plugin with the grafana-cli. But here we have the http_proxy with authentication, so I cannot use the grafana-cli, when I try to that, I have the error: "Failed to send requesterrorGet https://grafana.com/api/plugins/repo/alexanderzobnin-zabbix-app: Proxy authentication required
"
My server is configured for use the http_proxy in /etc/environment, /etc/profile, /etc/yum.conf, ~/.bash_profile... But I do not know how configure the grafana-cli behind a proxy authentication.

**Comment by bergquist** [comment]
The CLI allows proxy to be configured using environment variables
https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-cli/services/services.go#L29

```
ProxyFromEnvironment returns the URL of the proxy to use for a given request, as indicated by the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.

The environment values may be either a complete URL or a "host[:port]", in which case the "http" scheme is assumed. An error is returned if the value is a different form.

A nil URL and nil error are returned if no proxy is defined in the environment, or a proxy should not be used for the given request, as defined by NO_PROXY.

As a special case, if req.URL.Host is "localhost" (with or without a port number), then a nil URL and nil error will be returned.
```

https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by isaquelacerda** [comment]
Tks for your answer. 

Where can I find this file for this configuration?
