### ISSUE TITLE
[Bug] Intermittent "Failed to create user specified in auth proxy header" with auth.proxy and sqlite

### ISSUE THREAD

**Issue by bedrin** [grafana/grafana#9564]
I'm running Grafana behind a reverse-proxy which does the authentication.

Grafana configuration for database (/data is an NFS mount):
```
[database]
type = sqlite3
path = /data/grafana.db
```

Grafana configuration for authetnication:
```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
ldap_sync_ttl = 60
whitelist =
```

When I have a dashboard with multiple panels and auto-refresh enabled, I'm getting _intermittent_ "failed to create user specified in auth proxy header" errors with following log messages:

```
t=2017-10-17T14:08:09+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname=john.smith@foo.com user_id=3
t=2017-10-17T14:08:09+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname=john.smith@foo.com user_id=3
t=2017-10-17T14:08:09+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname=john.smith@foo.com user_id=3
t=2017-10-17T14:08:09+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-10-17T14:08:09+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname=john.smith@foo.com user_id=3
t=2017-10-17T14:08:09+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname=john.smith@foo.com user_id=3
t=2017-10-17T14:08:09+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-10-17T14:08:09+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2017-10-17T14:08:09+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
```

I believe that I didn't see these errors on Grafana v.4.5.0

I'm using Grafana v4.5.2 (commit: ec2b0fe) on Linux v3.10

**Comment by torkelo** [comment]
Strange, what type of disk storage is used?

**Comment by bedrin** [comment]
@torkelo I'm using sqlite3 database on a not-so-fast NFS share (I'm running Grafana in ephemeral docker and have to mount an external NFS in order to obtain persistence).

If I have 20 panels on a dashboard and refresh it each 5 minutes there's a high contention on user_seen_at column

**Comment by torkelo** [comment]
Sqlite on NFS is not recommended as it is single threaded and require db wide locks.

Suggest you switch to mysql or postgres
