### ISSUE TITLE
Bug: Enable Postgres backend to support redshift to_timestamp function

### ISSUE THREAD

**Issue by ChrisPRobinson** [grafana/grafana#9566]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
grafana 4.6 beta
- What datasource are you using?
postgres
- What OS are you running grafana on?
ubuntu 14.04
- What did you do?
Attempted to use the postgres provider against redshift. The query was something like this.
```
SELECT
  $__time(time),
  controller
FROM
  app_controller_time
WHERE
  $__timeFilter(time)
```
- What was the expected result?
To return a graph of the app controller time
- What happened instead?
A query like this was generated to run against redshift
```
SELECT  time controller FROM app_controller_time
WHERE  time >= to_timestamp(1508171710) AND time <= to_timestamp(1508258110)
```

Redshift doesn't support this version of to_timestamp
http://docs.aws.amazon.com/redshift/latest/dg/r_TO_TIMESTAMP.html

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Request response from grafana
```
Url | api/tsdb/query
-- | --
Method | POST
X-Grafana-Org-Id | 1
Accept | application/json, text/plain, */*
Content-Type | application/json;charset=utf-8

from | "1508172804022"
-- | --
to | "1508259204022"
queries | [ { "refId": "A", "intervalMs": 60000, "maxDataPoints": 1164, "datasourceId": 3, "rawSql": "SELECT\n $__time(time),\n controller\nFROM\n app_controller_time\nWHERE\n $__timeFilter(time)\n", "format": "time_series" } ]
```

Response from grafana
```
{
  "results": {
    "A": {
      "error": "pq: function to_timestamp(integer) does not exist",
      "refId": "A",
      "meta": {
        "sql": "SELECT\n  time AS \"time\",\n  controller\nFROM\n  app_controller_time\nWHERE\n  time >= to_timestamp(1508172804) AND time <= to_timestamp(1508259204)\n"
      },
      "series": null,
      "tables": null
    }
  },
  "message": "pq: function to_timestamp(integer) does not exist"
}
``` 

I haven't looked too deeply at how to fix this through a different query, though I think in redshift I can just create function that is named the same for it to use, maybe.
I understand I can likely write a different query, just thought that this is interesting bug and open another area to explore for testing if the developer so chose. Love the postgres feature!

**Comment by svenklemm** [comment]
The following query should work:
```
SELECT
  $__time(time),
  controller
FROM
  app_controller_time
WHERE
  extract(epoch from time) between $__unixEpochFrom() and $__unixEpochTo()
```

**Comment by ChrisPRobinson** [comment]
yes that seems to get things working.
