### ISSUE TITLE
Refresh not working in embed code

### ISSUE THREAD

**Issue by GkhnGRBZ** [grafana/grafana#95675]
### What happened?

After last update refresh in embed code ( http://grafana.address/d-solo/xxxx ) is not working

### What did you expect to happen?

N/A

### Did this work before?

N/A

### How do we reproduce it?

1) select a visualization
2) select share and embed
3) check the link by making the current time range inactive. You will see that it is not refreshed.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by alekiv** [comment]
duplicate for #95315
