### ISSUE TITLE
[Feature Request] Add date units to $__interval_ms

### ISSUE THREAD

**Issue by Anna-Fedorova** [grafana/grafana#9567]
Please include this information:
- What Grafana version are you using?
 Grafana v4.5.2 (commit: ec2b0fe)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu

- What did you do?
Write queries in the following way: 
select mean(data) from raw_data where $timeFilter group by time($__interval_ms / 10) fill(linear)

- What was the expected result?
Query was executed and provides values groups by the something value which is calculated based on ($__interval_ms / 10)

- What happened instead?
There is InfluxDB error: "Server returned error: error parsing query: time dimension must have duration argument." 
So, please, add time units to the function $__interval_ms for the InfluxDB datasource.

**Comment by torkelo** [comment]
Interval ms variable is numeric, can't  be used in in InfluxDB group by time clause,
