### ISSUE TITLE
Attach String before an InfluxDB table value

### ISSUE THREAD

**Issue by vsreelasya** [grafana/grafana#9569]
Please include this information:
- What Grafana version are you using?
- What datasource are you using?
Influx DB
- What OS are you running grafana on?
Linux
- What did you do?
I want to combine and Influx DB table value with an String which can be displayed in the table like "http://google.com/sessionid" where session id should come from the influx db value

- What was the expected result?
"http://google.com/1234" 
- What happened instead?
Table is not  generated
<img width="1029" alt="using_influxdb_in_grafana __grafana_documentation" src="https://user-images.githubusercontent.com/16893559/31683277-2cb81d9c-b342-11e7-8efc-00783544f3ce.png">

I want exactly like description column in which influx log entry should be my string and 25,23 should be from the influx db

**Comment by torkelo** [comment]
Not sure InfluxDB query language supports string concat, if not open feature request with InfluxDB

**Comment by vsreelasya** [comment]
Can I do that using Grafana?

**Comment by torkelo** [comment]
No, the grafana templating engine does not support math and string concat
