### ISSUE TITLE
Annotations API

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#9571]
The annotations feature needs work on the API.

- if no time is specified, it should default to the current time
- if no text is specified, it should return an error instead of creating an empty annotation
- if a user passes `what` but not `data` to the graphite-compatible API endpoint it shouldn't add a trailing newline to the stored annotation
- the graphite-compatible API needs to be documented

**Comment by torkelo** [comment]
Yes, agree on all points :)

**Comment by alexanderzobnin** [comment]
Dan, you talked about providing created annotation id in api response. Should we do it?

**Comment by alexanderzobnin** [comment]
Also, can't find info about required fields for Graphite events. May `what` field be empty?

**Comment by alexanderzobnin** [comment]
Found another problem. If user pushes graphite annotation without tags (`tags: []` or `tags: ""`) annotation will be successfully written. But there's no way to display it, filter with empty tags returns nothing.
