### ISSUE TITLE
Druid plugin doesn't work on latest Grafana master

### ISSUE THREAD

**Issue by pkarmaka** [grafana/grafana#9572]
- What Grafana version are you using?
      using master code , "4.6.0-pre1"
- What datasource are you using? 
      Druid
- What did you do and what happened?
  On saving the druid datasource, it gives me the error "Plugin module is missing Datasource constructor"
  
It works well till version 4.5.2. 

Did anything change recently?

**Comment by utkarshcmu** [comment]
@abhisant should be able to look into this ^

**Comment by bergquist** [comment]
We introduced some breaking changes in 4.6 https://github.com/grafana/grafana/blob/master/PLUGIN_DEV.md

**Comment by pkarmaka** [comment]
@utkarshcmu  We already have an issue logged on the plugin to track this https://github.com/grafana-druid-plugin/druidplugin/issues/37 , but it looks like 4.6 has introduced some changes that is impacting the plugin.

**Comment by daniellee** [comment]
Fixed by 7cbb4020e97032c3bcf37ef303d87a77de6decc0

We upgraded SystemJS which broke the import syntax for some modules. Should work now.

**Comment by pkarmaka** [comment]
Thanks @daniellee

**Comment by abhisant** [comment]
Thanks @pkarmaka .
