### ISSUE TITLE
MSSQL: Provisioning not working ( Login failed.)

### ISSUE THREAD

**Issue by timo1707** [grafana/grafana#95757]
### What happened?

Hi there,
when provisioning MSSQL Datasource, I'm running into following issue

I tried to connect a `MSSQL` Datasource in Grafana `11.3.0` and `11.0.0` OSS Hosted in k8s.
when adding the Datasource in the UI, it's working as expected. While provisioning the Datasource fails with the frontend error
```
mssql: login error: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
```

log:
```
logger=context userId=35 orgId=1 uname=me@company.de t=2024-11-02T16:24:18.01753038Z level=info msg="Request Completed" method=GET path=/api/datasources/uid/mssql_***/health status=400 remote_addr=***.**.***.*** time_ms=87 duration=87.3911ms size=153 referer=https://***.**.net/connections/datasources/edit/mssql_** handler=/api/datasources/uid/:uid/health status_source=server
```

The GET Datasource API returns this (id: 92 = provisioned, id:72= ui created):

```
  {
    "id": 92,
    "uid": "mssql_db",
    "orgId": 1,
    "name": "myProvisionedConnection",
    "type": "mssql",
    "typeName": "Microsoft SQL Server",
    "typeLogoUrl": "public/app/plugins/datasource/mssql/img/sql_server_logo.svg",
    "access": "proxy",
    "url": "thatsmyurl:1433",
    "user": "DOMAIN\\USER",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
      "authType": "SQL Server Authentication",
      "database": "myDB",
      "timeInterval": "5s",
      "tlsSkipVerify": true
    },
    "readOnly": true
  },
  {
    "id": 72,
    "uid": "ae1mibeixvthcf",
    "orgId": 1,
    "name": "myUIconnection",
    "type": "mssql",
    "typeName": "Microsoft SQL Server",
    "typeLogoUrl": "public/app/plugins/datasource/mssql/img/sql_server_logo.svg",
    "access": "proxy",
    "url": "thatsmyurl:1433",
    "user": "DOMAIN\\USER",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
      "authenticationType": "SQL Server Authentication",
      "connMaxLifetime": 14400,
      "database": "myDB",
      "maxIdleConns": 100,
      "maxIdleConnsAuto": true,
      "maxOpenConns": 100
    },
```

### What did you expect to happen?

No mather if I add the Datasource in the UI or provision it, both should connect successful.

### Did this work before?

no

### How do we reproduce it?

1. setup a mssql datasource in the UI with domain User credentials
2. setup a mssql datasource in provisioning files with domain User credentials
3. try to connect to both variants

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: `11.3.0` and `11.0.0`
OS: macOS
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

mssql

**Comment by timo1707** [comment]
not sure why, but i rebuild my helm deployment, and suddenly it was working.. seems theres an issue when i only reload the Datasource on running pods.

**Comment by tolzhabayev** [comment]
I would close it then as you seem to have resolved the problem
