### ISSUE TITLE
This problem occurs when I want to install offline in Windows system

### ISSUE THREAD

**Issue by gsbaby** [grafana/grafana#95762]
### What happened?

INFO [11-03|15:18:26] Envelope encryption state                logger=secrets enabled=true current provider=secretKey.v1ERROR[11-03|15:18:26] Failed to get renderer plugin sources    logger=renderer.manager error="failed to open plugins path"
INFO [11-03|15:18:26] Restored cache from database             logger=plugin.angulardetectorsprovider.dynamic duration=994.5µs
INFO [11-03|15:18:26] Loading plugins...                       logger=plugin.store
ERROR[11-03|15:18:26] Failed to load external plugins          logger=plugin.sources error="failed to open plugins path"ERROR[11-03|15:18:27] Could not register plugin                logger=plugins.registration pluginId=xychart error="plugin xychart is already registered"
ERROR[11-03|15:18:27] Could not initialize plugin              logger=plugins.initialization pluginId=xychart error="plugin xychart is already registered"
INFO [11-03|15:18:27] Plugins loaded                           logger=plugin.store count=54 duration=289.1826ms
INFO [11-03|15:18:27] Query Service initialization             logger=query_data
INFO [11-03|15:18:27] Live Push Gateway initialization         logger=live.push_http
INFO [11-03|15:18:27] Applying new configuration to Alertmanager logger=ngalert.notifier.alertmanager org=1 configHash=d2c56faca6af2a5772ff4253222f7386
INFO [11-03|15:18:27] Running in alternative execution of Error/NoData mode logger=ngalert.state.manager
INFO [11-03|15:18:27] registering usage stat providers         logger=infra.usagestats.collector usageStatsProvidersLen=2
INFO [11-03|15:18:27] starting to provision alerting           logger=provisioning.alerting
INFO [11-03|15:18:27] finished to provision alerting           logger=provisioning.alerting
INFO [11-03|15:18:27] Installing plugin                        logger=plugin.backgroundinstaller pluginId=grafana-lokiexplore-app version=
INFO [11-03|15:18:27] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=
INFO [11-03|15:18:27] Starting MultiOrg Alertmanager           logger=ngalert.multiorg.alertmanager
INFO [11-03|15:18:27] Storage starting                         logger=grafanaStorageLogger
ERROR[11-03|15:18:27] Failed to get renderer plugin sources    logger=renderer.manager error="failed to open plugins path"
INFO [11-03|15:18:27] Warming state cache for startup          logger=ngalert.state.manager
ERROR[11-03|15:18:27] Failed to install plugin                 logger=plugin.backgroundinstaller pluginId=grafana-lokiexplore-app version= error="Get \"https://grafana.com/api/plugins/grafana-lokiexplore-app/versions\": dial tcp: lookup grafana.com: no such host"
ERROR[11-03|15:18:27] Update check failed                      logger=grafana.update.checker error="failed to get stable version from grafana.com: Get \"https://grafana.com/api/grafana/versions/stable\": dial tcp: lookup grafana.com: no such host" duration=8.4186ms
INFO [11-03|15:18:27] starting to provision dashboards         logger=provisioning.dashboard
INFO [11-03|15:18:27] finished to provision dashboards         logger=provisioning.dashboard
ERROR[11-03|15:18:27] Error downloading plugin manifest keys   logger=plugin.signature.key_retriever error="Get \"https://grafana.com/api/plugins/ci/keys\": dial tcp: lookup grafana.com: no such host"
INFO [11-03|15:18:27] State cache has been initialized         logger=ngalert.state.manager states=0 duration=95.2573ms
INFO [11-03|15:18:27] Starting scheduler                       logger=ngalert.scheduler tickInterval=10s maxAttempts=1
ERROR[11-03|15:18:27] Error while updating detectors           logger=plugin.angulardetectorsprovider.dynamic error="fetch: http do: Get \"https://grafana.com/api/plugins/angular_patterns\": dial tcp: lookup grafana.com: no such host"![Image](https://github.com/user-attachments/assets/7b74c949-68d6-4358-b903-c4145176b2cc)

### What did you expect to happen?

Cannot install offline

### Did this work before?

don't know

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by andresmgot** [comment]
Hi @gsbaby,

Most of those errors are expected and non-critical if you are working without Internet connection. The only one that is not expected is  this one: `error="failed to open plugins path"`. Apparently, the daemon running Grafana is not able to read the plugins directory. You can see which one is configured since there is a log line like this:

```
INFO [11-05|11:24:51] Path Plugins                             logger=settings path=<YOUR_PLUGIN_PATH>
```

Make sure that directory exists and the user running Grafana has permissions over it.

Apart from that, no other error is critical, so you should be able to use Grafana. Please feel free to reopen this issue if you still think there is a issue.
