### ISSUE TITLE
[Bug] Heatmap does not have y-axis labels

### ISSUE THREAD

**Issue by kirbmeister** [grafana/grafana#9576]
Please include this information:
- What Grafana version are you using?
Grafana v4.6.0-beta1 (commit: 9d916fd)

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
Ubuntu 16

- What did you do?
Viewing existing and previously working heatmap graphs. Trying to make a new heatmap graph. Both using elasticsearch data sources.
I think this worked on Grafana 4.5.x

- What was the expected result?
Heatmap graphs have y-axis labels

- What happened instead?
Heatmap graphs have no y-axis labels, despite trying various settings

Here is an example of the missing y-axis on a heatmap panel
![image](https://user-images.githubusercontent.com/5092106/31701554-0b410c16-b386-11e7-9d28-a00812b0c843.png)

**Comment by torkelo** [comment]
thanks for reporting this! will investigate!
