### ISSUE TITLE
[Bug] Min Step Size is not honoured when calculating the $interval_ms global variable

### ISSUE THREAD

**Issue by pparth** [grafana/grafana#9579]
I am not sure whether this is by design, however, to me it looks like a bug. If you enter a simple [[__interval_ms]] in a query with Prometheus data source and set a Min Step size of 60s and then select a time period of 5 minutes, you will see that the result is 200, when it is clear from the graph that the Min Step size is honoured and you get only 5 data points, one every minute. The __interval_ms should then return 60000, that is 60s, and not 200ms which is the value you see if you delete the Min Step size and allow Grafana to calculate one automatically.

**Comment by torkelo** [comment]
fixed in v4.6.0  :)

**Comment by pparth** [comment]
Cool! Thanks!
