### ISSUE TITLE
Fullscreen mode can cause right hand menu to become hidden

### ISSUE THREAD

**Issue by estone** [grafana/grafana#958]
When in fullscreen mode, a narrow window or long dashboard name can cause the right hand menu icons (save etc) to become hidden.

I believe the following screenshots illustrate the issue.

This is problematic if you cannot change the width of the browser as the link to disable fullscreen mode is also hidden.

![screenshot 2014-10-20 17 09 14](https://cloud.githubusercontent.com/assets/1926247/4704653/d37a8df4-5873-11e4-8138-44c016034cf8.png)
![screenshot 2014-10-20 17 10 23](https://cloud.githubusercontent.com/assets/1926247/4704652/d148460c-5873-11e4-8b49-5e5fca5f4a0d.png)

**Comment by tuxinaut** [comment]
> Any ideas?

Hamburger menu sounds fine or the lazy solution for the problem could be to shorten the dashboard name after x characters (depends on the screen with) and add three points at the end of the dashboard name.

**Comment by utkarshcmu** [comment]
IMO, Shortening the name to x characters is a better idea and then 3 dots/points at the end. If then shortened name is hovered then we can show the complete name of the dashboard as the hover text. What do you guys think about this?

**Comment by torkelo** [comment]
fixed in 2.6
