### ISSUE TITLE
Cannot integration PRTG in Grafana CLoud

### ISSUE THREAD

**Issue by semacam1** [grafana/grafana#95815]
### Background

How to integration prtg with grafana?

### Use case

How to integration prtg with grafana?

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
Hi - closing this as a duplicate of https://github.com/grafana/grafana/issues/90786 please upvote the original issue
