### ISSUE TITLE
Datasource: Elasticsearch: Failed to execute phase [query], all shards failed

### ISSUE THREAD

**Issue by whiteud** [grafana/grafana#9581]
Hello, i have problem with datasource elasticsearch on 4.6.1 Grafana. Please help!

Settings datasource:
URL: http://10.200.10.3:9200/ Access: proxy
Index name: [graylog2_]DD pattern: Daily
Timefield: timestamp
Version: 2.x

Index OK, Time field name: OK

Request:
`request:Object
method:"POST"
url:"api/datasources/proxy/2/_msearch"
data:"{"search_type":"count","ignore_unavailable":true,"index":"graylog2_17"} {"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1508234854921","lte":"1508321254922","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"date_histogram":{"interval":"1m","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1508234854921","max":"1508321254922"},"format":"epoch_millis"},"aggs":{}}}} "`

Response:
`responses:Array[1]
0:Object
error:"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[T6KHKQNeR0Kfv7qPVQc7AQ][graylog2_17][0]: SearchParseException[[graylog2_17][0]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1508234871831","lte":"1508321271831","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"date_histogram":{"interval":"1m","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1508234871831","max":"1508321271831"},"format":"epoch_millis"},"aggs":{}}}}]]]; nested: QueryParsingException[[graylog2_17] bool query does not support [filter]]; }{[T6KHKQNeR0Kfv7qPVQc7AQ][graylog2_17][1]: SearchParseException[[graylog2_17][1]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1508234871831","lte":"1508321271831","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"date_histogram":{"interval":"1m","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1508234871831","max":"1508321271831"},"format":"epoch_millis"},"aggs":{}}}}]]]; nested: QueryParsingException[[graylog2_17] bool query does not support [filter]]; }{[T6KHKQNeR0Kfv7qPVQc7AQ][graylog2_17][2]: SearchParseException[[graylog2_17][2]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1508234871831","lte":"1508321271831","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"date_histogram":{"interval":"1m","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1508234871831","max":"1508321271831"},"format":"epoch_millis"},"aggs":{}}}}]]]; nested: QueryParsingException[[graylog2_17] bool query does not support [filter]]; }{[T6KHKQNeR0Kfv7qPVQc7AQ][graylog2_17][3]: SearchParseException[[graylog2_17][3]: from[-1],size[0]: Parse Failure [Failed to parse source [{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1508234871831","lte":"1508321271831","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"3":{"date_histogram":{"interval":"1m","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1508234871831","max":"1508321271831"},"format":"epoch_millis"},"aggs":{}}}}]]]; nested: QueryParsingException[[graylog2_17] bool query does not support [filter]]; }]"`

**Comment by whiteud** [comment]
i check shards on http://10.200.10.3:9200/_cluster/health/?level=shards

and see: 

`	
cluster_name	"graylog2"
status	"yellow"
timed_out	false
number_of_nodes	2
number_of_data_nodes	1
active_primary_shards	85
active_shards	85
relocating_shards	0
initializing_shards	0
unassigned_shards	5
delayed_unassigned_shards	0
number_of_pending_tasks	0
number_of_in_flight_fetch	0
indices	
graylog2_1	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_0	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_3	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_2	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_5	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_4	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_7	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_6	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_9	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_8	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
readme	
status	"yellow"
number_of_shards	5
number_of_replicas	1
active_primary_shards	5
active_shards	5
relocating_shards	0
initializing_shards	0
unassigned_shards	5
shards	
0	
status	"yellow"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	1
1	
status	"yellow"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	1
2	
status	"yellow"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	1
3	
status	"yellow"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	1
4	
status	"yellow"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	1
graylog2_12	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_11	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_10	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_16	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_15	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_14	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_13	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_19	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_18	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
graylog2_17	
status	"green"
number_of_shards	4
number_of_replicas	0
active_primary_shards	4
active_shards	4
relocating_shards	0
initializing_shards	0
unassigned_shards	0
shards	
0	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
1	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
2	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0
3	
status	"green"
primary_active	true
active_shards	1
relocating_shards	0
initializing_shards	0
unassigned_shards	0`

**Comment by torkelo** [comment]
What version of Elasticsearch are you using? Looks like it's pre 2.x

**Comment by whiteud** [comment]
You a right, 1.7. Sorry for this issue.
