### ISSUE TITLE
[Feature request] Add option to provide axis labels in heatmap

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#9584]
- What Grafana version are you using?

v4.5.1

- What datasource are you using?

Prometheus

- What OS are you running grafana on?

Linux Debian

- What did you do?

Built a heatmap panel.

- What was the expected result?

Being able to describe the Y-axis (like in normal graph panels) and heatmap.

- What happened instead?

No such option available.

![screenshot from 2017-10-18 14-22-59](https://user-images.githubusercontent.com/3432/31718425-37882798-b410-11e7-8f14-26c10a8339aa.png)

In that graph, I'd like to describe the Y-Axis with e.g. "Partition number" and add a note that the heatmap colors are in gigabyte.

**Comment by richvdh** [comment]
Just wanted to add a +1 for this feature, in particular the Y-axis labels. Of course on a heatmap, the Y axis is always "number of things", but it would be useful to be able to indicate what it is that we are counting.

**Comment by leeoniya** [comment]
implemented in https://github.com/grafana/grafana/pull/49969

![image](https://user-images.githubusercontent.com/43234/172007874-baeb488d-559a-43ef-bc3f-b73292db9612.png)
