### ISSUE TITLE
export to file button does nothing on 4.6.0 beta2

### ISSUE THREAD

**Issue by lynchc** [grafana/grafana#9586]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 4.6.0 beta2
- What datasource are you using? prometheus
- What OS are you running grafana on? linux
- What did you do? attempted to export dashboard through the ui by clicking save to file
- What was the expected result? it would save to a file
- What happened instead? nothing
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
thanks for reporting this! fix incoming!
