### ISSUE TITLE
Error while embedding Grafana dashboard in external application

### ISSUE THREAD

**Issue by hemsush** [grafana/grafana#9588]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by hemsush** [comment]
I have enabled auth proxy and configured nginx using this link .https://grafana.com/blog/2015/12/07/grafana-authproxy-have-it-your-way/ . 
I tried to access the grafana dashboard from Java class - Httpconnection . I am getting a html page that has relative urls for all css and js. I need to access grafana from external application without login as I am passing the Username and password while hitting the url

**Comment by torkelo** [comment]
please use community site for questions. 

Grafana uses relative urls  (<base href in head to specify relative to)

**Comment by hemsush** [comment]
I have used base href. But I am facing issue in grafana app tag.

**Comment by hemsush** [comment]
I am getting as cannot read property of ‘pageClass’ of undefined. In my html I could find contents of grafana-app tag is not rendering properly. How to get that. My issue is same as mentioned in https://github.com/grafana/grafana/issues/5735

I was able to view dashboard via browser .but when I try the same in Java HTTP connection , I am getting the above issue
