### ISSUE TITLE
selecting timeframe from a panel results in browser crash

### ISSUE THREAD

**Issue by lynchc** [grafana/grafana#9589]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 0.4.6 beta 2
- What datasource are you using? prometheus
- What OS are you running grafana on? linux
- What did you do? open a dashboard and select a new timeframe through a panel
Tested on osx with chrome and safari and arch linux with chromium.
- What was the expected result? The dashboard would load that new time frame
- What happened instead? browser crash (safari just killed the cpu and hung)
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
this has already been reported and fixed, https://github.com/grafana/grafana/issues/9575
