### ISSUE TITLE
[Bug] "Send test" on Slack configuration fails while uploading image

### ISSUE THREAD

**Issue by jmdacruz** [grafana/grafana#9590]
- What Grafana version are you using? **4.6.0-beta2 (docker)**
- What datasource are you using? **Prometheus**
- What OS are you running grafana on? **Docker image**
- What did you do? **Configured a Slack notification channel with a bot token and the "include image" option, and used the "send test" feature**
- What was the expected result? **Message successfully sent to Slack with no errors on Grafana**
- What happened instead? **Message is successfully sent to Slack, but Grafana shows an error: "Failed to send alert notifications". Log file entry below**
 
```
t=2017-10-18T22:16:41+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=slack id=0 isDefault=false
t=2017-10-18T22:16:41+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=0 notification="***REDACTED***"
t=2017-10-18T22:16:41+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
t=2017-10-18T22:16:41+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="open public/img/mixed_styles.png: no such file or directory"
t=2017-10-18T22:16:41+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=10.40.245.164 time_ms=532 size=48 referer=***REDACTED***/grafana/alerting/notification/1/edit
```

Also, if I unselect the "include image" option, Grafana displays the successful "Test notification sent" message instead.

**Comment by jmdacruz** [comment]
I think I might know what the root cause is: private channels and/or the bot that owns the token not being on the channel.

**Comment by torkelo** [comment]
Ok, closing if that is the case

**Comment by jmdacruz** [comment]
I think this is still an issue, since the error message on the UI is misleading. Let me try to clarify:
* This issue was not present in version 4.5.2: Selecting the "include image" option and then clicking on "sent test" would result in a successful UI notification (assuming the setup is correct)
* The issue on version 4.6.0-beta2 is that, when the "include image" option is selected (and the Slack token is also included, although I haven't tested without it), the "send test" function incorrectly reports a failure when in fact the setup is correct.
