### ISSUE TITLE
Convert a UNIX timestamp to a datetime with grafana

### ISSUE THREAD

**Issue by godjil** [grafana/grafana#9595]
Please add a given function $(SUBJ)

**Comment by torkelo** [comment]
you can already convert a unix time stamp to a date time

**Comment by farzadpanahi** [comment]
@torkelo if you don't mind could you mention what the function name is? I looked into the documentation but couldn't find a way to do this. I also create a topic in the forum https://community.grafana.com/t/how-to-convert-timestamp-to-date-in-graph-panel-title/19999

**Comment by giuseppeurso** [comment]
> you can already convert a unix time stamp to a date time

Do you happen to know what time it is?
Yes.

**Comment by Cradac** [comment]
@farzadpanahi  I found a post online about this ([Link](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/GrafanUnixEpochTime))
Basically, all date/time units in Grafana can convert epoch seconds, but they expect milliseconds, instead of seconds. So you need to multiply your value by 1000 and select any of the date/time unit formats.

**Comment by HorselessName** [comment]
> Basically, all date/time units in Grafana can convert epoch seconds, but they expect milliseconds, instead of seconds. So you need to multiply your value by 1000 and select any of the date/time unit formats

Good. So, basically.
Step 1: Multiple Column value by 1000
Step 2: Convert to Time.

Tested and it worked. Thanks!

**Comment by david-martin** [comment]
Worked for me too. Thanks.

Multiply value by 1000 (which results in a second field, but you can hide the original if you want)
![image](https://github.com/grafana/grafana/assets/878251/bd143f29-34f6-40e4-bc6e-d769d70679fa)

then add Override.
![image](https://github.com/grafana/grafana/assets/878251/b2cb84c8-fbd6-400e-a685-f5e03cfa758d)

**Comment by utkarsh150** [comment]
Yes this works, @david-martin and @HorselessName How to remove the original column? Can you share the snip as well?

**Comment by david-martin** [comment]
> How to remove the original column

I believe you can hide fields from the 'Transform' tab with the 'Organize fields' transformation.

**Comment by utkarsh150** [comment]
The transformation “Organize Field” hiding the original column hides the new column as well.

**Comment by utkarsh150** [comment]
It worked after adding the new transformation “filter by name” after epoch conversion. Thanks

**Comment by rwader-swi** [comment]
> @farzadpanahi I found a post online about this ([Link](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/GrafanUnixEpochTime)) Basically, all date/time units in Grafana can convert epoch seconds, but they expect milliseconds, instead of seconds. So you need to multiply your value by 1000 and select any of the date/time unit formats.

thanks a lottttttt
