### ISSUE TITLE
[Bug]? TestData plugin failed, build from source on windows

### ISSUE THREAD

**Issue by remcopoelstra** [grafana/grafana#9597]
I Have built grafana from source on windows and I had the impression everything went ok. However when I enable the TestData app plugin and open one of the imported dashboards the following error pops up:

Grafana TestData plugin failed
Error: Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/app/testdata/\datasource/module Loading app/plugins/app/testdata/\datasource/module

I built the master and v4.6.x branches on two different 64 bit windows machines (win7 and win10) with the exact same result. I also tried installing some plugins/datasources (pie chart, simplejson) through the cli and this seems to work just fine. I suspect the failing testdata plugin has something to do with the slash-backslash shown in the error message.

I originally posted this question to the community support forum and was requested to create a bug report here. If you would like me to provide more details please let me know. 

Best regards, Remco

**Comment by torkelo** [comment]
thanks for reporting this. Must be some path joining issue on windows.

**Comment by remcopoelstra** [comment]
I had some time to do a little debugging this morning (go is new to me so I'm still finding my way..)

I added some logging to setPathsBasedOnApp in frontend_plugin.go, on my system fp.PluginDir prints:
C:\repos\grafana\src\github.com\grafana\grafana\public\app\plugins\app\testdata\datasource

and app.PluginDir prints:
C:\\repos\\grafana\\src\\github.com\\grafana\\grafana\\public\\app\\plugins\\app\\testdata

the resulting appSubPath prints:
\\datasource

As a test I tried the following quick hack, and this got the testdata plugin working:
appSubPath := strings.Replace(fp.PluginDir, app.PluginDir, "", 1)
appSubPath = appSubPath[1:]

I don't really have an idea what's going on with the path separators and I also don't know what the best fix would be but I hope this info helps.

Best regards, Remco

**Comment by remcopoelstra** [comment]
hmm github decided to do some formatting, let me try it in a code block:
`
fp.PluginDir prints:
C:\repos\grafana\src\github.com\grafana\grafana\public\app\plugins\app\testdata\datasource

app.PluginDir prints:
C:\\repos\\grafana\\src\\github.com\\grafana\\grafana\\public\\app\\plugins\\app\\testdata

the resulting appSubPath prints:
\\datasource
`

**Comment by remcopoelstra** [comment]
still no luck..

Ok I'll just try to explain, fp.PluginDir prints with single backslashes, app.PluginDir and appSubPath print with double backslashes

For some reason github changed the double backslashes to singles in my previous 2 posts..

**Comment by remcopoelstra** [comment]
Ah, just noticed that the second string that is passed to plog.Info always prints with double backslashes in the console, so nevermind that. Then i guess the problem is the fact that appSubPath started with a backslash and the JoinUrlFragments util function only checks the prefix/suffix for slashes.
