### ISSUE TITLE
Elasticsearch: Apply Ad-Hoc Filters to Elasticsearch Annotation Queries

### ISSUE THREAD

**Issue by RalfJung** [grafana/grafana#9599]
* What Grafana version are you using? 4.5.2
* What datasource are you using? Elasticsearch
* What OS are you running grafana on? Linux (Debian amd64)
* What did you do?
Create a "filter" template variable, and an annotation query. Configure the ad-hoc filter to restrict the dataset (`branch` = `iris`).
* What was the expected result?
The filter should apply to all queries (as advertised), including annotation queries.
* What happened instead?
Annotation queries are not affected: Grafana still shows annotations that do not match the filter.
* If related to metric query / data viz:
  * Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 [I am not using Chrome, so I am not opening Chrome dev tools.]
Annotation query:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"gitlab-ci"}
{"query":{"bool":{"filter":[{"range":{"date":{"from":1505892910806,"to":1508484910806,"format":"epoch_millis"}}},{"query_string":{"query":"*"}}]}},"size":10000}
```

Annotation response:

```
{"responses":[{"took":57,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":202,"max_score":0.0,"hits":[{"_index":"gitlab-ci","_type":"datapoint","_id":"AV8WM7ZqcMWoDKspb8cp","_score":0.0,"_source":
{
"project" : "iris",
"branch" : "master",
"commit" : "683d42a088a839063395b7b6db9f276754df8802",
"date" : "2017-10-12T11:12:12",
"file" : "theories/heap_lang/proofmode",
"coq-time": 1.81,
"coq-mem": 537460
}},{"_index":"gitlab-ci","_type":"datapoint","_id":"AV8WM7amcMWoDKspb8cq","_score":0.0,"_source":
{
"project" : "iris",
"branch" : "master",
"commit" : "683d42a088a839063395b7b6db9f276754df8802",
"date" : "2017-10-12T11:12:12",
"file": "theories/heap_lang/lib/lock",
"coq-time": 1.31,
"coq-mem": 534796
}
},{"_index":"gitlab-ci","_type":"datapoint","_id":"AV8WM7bZcMWoDKspb8cr","_score":0.0,"_source":
{
"project" : "iris",
"branch" : "master",
"commit" : "ae0d4da1546204803d08d6b658c7f465e02dfb3f",
"date" : "2017-10-10T17:08:12",
"file" :"theories/heap_lang/proofmode",
"coq-time": 1.78,
"coq-mem": 537848
}},{"_index":"gitlab-ci","_type":"datapoint","_id":"AV8WM7cPcMWoDKspb8cs","_score":0.0,"_source":
{
"project" : "iris",
"branch" : "master",
"commit" : "ae0d4da1546204803d08d6b658c7f465e02dfb3f",
"date" : "2017-10-10T17:08:12",
"file" : "theories/heap_lang/lib/lock",
"coq-time": 1.26,
"coq-mem": 536164
}
},[...]
```

**Comment by rjain11** [comment]
@torkelo Do ad-hoc filters work with annotation for InfluxDB? Any timeline on it? This would allow to make annotations per graph panel rather than the whole dashboard.

**Comment by eladamitpxi** [comment]
+1

**Comment by M0rdecay** [comment]
+1 we need this!

**Comment by orenshani7** [comment]
+1

**Comment by aocenas** [comment]
@torkelo I assume this should be somehow generic for all datasource that support ad hoc filtering so assigning it to platform squad. Let me know if that isn't the case and this needs datasource specific implementation.
