### ISSUE TITLE
Add file based dashboards to the dashboard search and list.

### ISSUE THREAD

**Issue by oprietop** [grafana/grafana#960]
If I'm not mistaken it seems file based bashboards can only be reached using their direct URL on the browser. While i don't have any grudge to ES i think it should be neat to be able add the dashboards on  app/dashboards to the dashboard lists. They could be treated as a diferent entity than the ES ones with a different color and it would allow to keep a searchable set of fixed/immutable dashboards plus the ES ones if wanted.

**Comment by torkelo** [comment]
```
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards
```

The path will be scanned every minute and a index built, dashboards will be available and searchable in the dashboard search and dashboard list panel. They cannot be saved / updated from the UI, this feature is only for static dashboards that are automatically generated to edited outside Grafana.
