### ISSUE TITLE
[New Data Source]: zabbix

### ISSUE THREAD

**Issue by prashantdidwania1** [grafana/grafana#96014]
### Background

Pleaseadd zabbix plugins for the same.

### Use case

To monitor zabbix alerts. 

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment]
@prashantdidwania1 the zabbix plugin is an application which can be installed via /plugins in your grafana instance.
