### ISSUE TITLE
Grafana explorer - Fail fast when processing logs with extremely long lines (more than 100,000 characters)

### ISSUE THREAD

**Issue by gburiola** [grafana/grafana#96020]
### What happened?

Using Grafana v11.1.5, in the explorer view and loki datasource.

I have a query that returns 20 log lines and 20MB. 

1 of the 20 log lines is massive with over 19M characters. don't judge me :)

Grafana freezes for almost 30seconds, then shows the 19 lines, a blank line and message:

> Logs with more than 100,000 characters could not be parsed and highlighted

Message above is probably coming from [this bit of code](https://github.com/grafana/grafana/blob/e55100fa90848872eb1e31a75e3abee51fa9f480/public/app/features/explore/Logs/LogsMetaRow.tsx#L127)

Adding this to the end of the query makes it return instantly **and** shows the first 100K lines of the massive log line.

```
 | line_format `{{ __line__ | trunc 100000 }}` 
```

### What did you expect to happen?

I agree that grafana shouldn't be displaying the massive log line, but it should fail fast when dealing with a massive line and at show the first 100K of the massive log line instead of not showing anything.

**Comment by gburiola** [comment]
https://github.com/grafana/grafana/issues/78572 is slightly related but is more focused in the UI and not so much in grafana freezing when displaying lines longer than 100,000 chars

**Comment by matyax** [comment]
Thanks for reporting this @gburiola . Changing the query is definitely not something that we will do, but we will address the performance issue.

**Comment by matyax** [comment]
By the way @gburiola, there's a feature under the feature flag `lokiPredefinedOperations` where you can define common operations to be included in your queries by default. Maybe you can add the truncate bit there.

![Image](https://github.com/user-attachments/assets/958ed01d-1491-477d-abbb-86a8785db152)
