### ISSUE TITLE
Dashboards: Template Variables show $__all instead of All

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#96027]
### What happened?

"$__all" visible in variable instead of "All" when having Custom type of variable. Even is "All" is saved, when reopening dashboard "$__all" is shown.

![Image](https://github.com/user-attachments/assets/a5a2d47d-a57c-4e42-8067-d100f4dfa52c)

### What did you expect to happen?

Variable showing "All" instead of "$__all".

### Did this work before?

Yes, this wasn't an issue before 11.3.0 version.

### How do we reproduce it?

Adding test dashboard: [Test-1730983344627.json](https://github.com/user-attachments/files/17661686/Test-1730983344627.json)

### Environment (with versions)?

Grafana: Grafana v11.3.0 (d9455ff7db)
OS: Debian 11
Browser: Chrome

### Grafana platform?

A downloaded binary

**Comment by torkelo** [comment]
was able to replicate it here: 

https://play.grafana.org/d/be38itgxq0d1cb/variable-with-all?from=now-6h&to=now&timezone=utc&var-query2=$__all

Happens when the custom variable has "include all" (but not multi enabled), and the All option is saved as default

**Comment by tecmatia-dp** [comment]
Also, and maybe related, it seems to ignore custom label from "Custom all value" setting.
