### ISSUE TITLE
Prometheus: Update native histogram hints

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#96035]
Native histograms have hints in the Prometheus query editor. 

![Image](https://github.com/user-attachments/assets/0bc0e135-b397-4d95-aa0e-0918c81653dc)

It is suggested to use only these these in this order:

`histogram_quantile`
`histogram_avg`
`histogram_count`

**Comment by K-Kumar-01** [comment]
Hey @bohandley 
I was wondering if I could work on the issue.
Thanks.

**Comment by yangkb09** [comment]
@K-Kumar-01 thank you for your interest! whenever you see the label `good first issue` please feel free to go ahead and create a PR, no need to ask :)

**Comment by K-Kumar-01** [comment]
Thanks @yangkb09 for informing.
I will try to solve it.
