### ISSUE TITLE
[Feat Request] Persist legend sort order in URL 

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#9603]
Please include this information:
- What Grafana version are you using? **4.7.0-pre1 (nightly build)**
- What datasource are you using? **InfluxData**
- What OS are you running grafana on? **Ubuntu 17.04**
- What did you do? 

I'm using new feature implemented yeasterday:
https://github.com/grafana/grafana/issues/9538#issuecomment-337904176
Here:
https://devstats.k8s.io/dashboard/db/prs-merged-repository-groups?orgId=1&var-period=m&var-repogroups=All
I'm clicking legend header (for example min, max, avg) and sort order of stacked series changes correctly, but there is no new URL generated.
So I cannot create a link for other people to see exactly the same view.

- What was the expected result?
Changing the sort order of stacked series (via clicking legend header) should generate a new URL.
- What happened instead?
Series were sorted correctly, but without generating new URL.

**Comment by lukaszgryglicki** [comment]
Additionally, I would be great to have a way of controlling this feature.
Currently, it is always enabled and it shows top series from legend as a last stacked value on chart.
For example, if we sort series by avg desc we can see Kubernetes is 1st.
Its stacked series would be on the top of the stack.
I think we should have an option to specify that 1st series from legend should be on the top or on the bottom of the stack (maybe also include the option to turn this feature off).
All those options should be encoded in URL and also (ideally) should be exported and imported to/from JSON when exporting/importing entire dashboard.

**Comment by bergquist** [comment]
Closing this and opened https://github.com/grafana/grafana/issues/9617 as a more generic requirement beyond legend sorting.

Currently we only keep template variable in the url.
