### ISSUE TITLE
Alerting: crashes on old alerts

### ISSUE THREAD

**Issue by lukasz-leszczuk-airspace-intelligence** [grafana/grafana#96040]
### What happened?

After upgrading to grafana 11.3.0 I can't open alert definition in grafana and I only get "An unexpected error happened" error message.
Since https://github.com/grafana/grafana/pull/93057 was merged, frontend code overrides uid field on datasource. But sometimes, with older alerts (successfully created via API in grafana 11.2.0), datasource is a string. So calling `datasource.uid` on a string raises an exception:
```
2react-dom.production.min.js:189 TypeError: Cannot create property 'uid' on string '<datasource name>'
    at M (QueryWrapper.tsx:101:34)
    at el (react-dom.production.min.js:167:137)
    at Rf (react-dom.production.min.js:290:337)
    at Cf (react-dom.production.min.js:280:389)
    at Qf (react-dom.production.min.js:280:320)
    at Cl (react-dom.production.min.js:280:180)
    at bc (react-dom.production.min.js:271:88)
    at Ef (react-dom.production.min.js:273:300)
    at Ls (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```
I believe the correct code in QueryWrapper.tsx should be like this:
```
queryWithDefaults.datasource = {}
queryWithDefaults.datasource.uid = query.datasourceUid;
```

### What did you expect to happen?

Editor view presented with all details.

### Did this work before?

Yes, in 11.2.0

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by soniaAguilarPeiron** [comment]
[PR](https://github.com/grafana/grafana/pull/96085) created with the fix.
