### ISSUE TITLE
Documentation feedback: example file for tempo data source has erroneous time shift

### ISSUE THREAD

**Issue by cancub** [grafana/grafana#96049]
### What happened?

I set my Tempo datasource's `traceQuery` to align with what we see in the [example file](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#example-file)

```
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
```
But when I ran a trace ID query, what I saw in the Tempo Query Frontend logs was that the actual shifts for `from`/`start` and `to`/`end` were one hour into the future in both cases. For example, start=12:00 and end=13:00 became start=13:00 and end=14:00.

I needed to artificially shift the query times back an hour to ensure that the Tempo Querier was actually looking in the right location.

The documentation surrounding these values is rather confusing, since the [TraceID query section](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#traceid-query) shows defaults of (positive) `30m` for both values.

Neither "Time shift for start of search" nor "Time shift for end of search" are explicit about the directionality of these shifts (e.g., "into the past" or "into the future") and what effect a `-` would have on this directionality.

### What did you expect to happen?

I expected to be able to use the example file as a reference, and observe a time shift of 1 hour in each direction. That is, if a time range in grafana was

start=12:00
end=13:00

I expected to see the Query Frontend report

start=11:00
end=14:00

### Did this work before?

I don't believe so.

### How do we reproduce it?

1. Use the example configuration file for the tempo datasource found [here](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#example-file)
2. Query tempo for a trace ID
3. Observe both start and end shift 1 hour into the future.

### Environment (with versions)?

Grafana: 11.1.0
OS: windows 11
Browser: all

### Grafana platform?

Kubernetes

**Comment by grafakus** [comment]
Hi @cancub, indeed the logic is not intuitive and the documentation does clearly states what to expect.

From what I see in the [code base](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/tempo/datasource.ts#L709-L721):
- `from` will be shifted by **subtracting** the value of `spanStartTimeShift`, whereas
- `to` will be shifted by **adding** the value of `spanEndTimeShift`

Essentially,  for positive values, the shift will happens _outwards_. This contradicts what [the documentation explains](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#configure-trace-to-logs):
![Image](https://github.com/user-attachments/assets/eaf9b0a5-33d9-490e-9e95-ee39be66053c)

So if the config is:
- `spanStartTimeShift=1h`
- `spanEndTimeShift=-1h`

Then the transformation is:
- `from=12:00` - `spanStartTimeShift=1h` → `11:00`
- `to=13:00`     + `spanEndTimeShift=-1h` → `12:00` 

And if the config is:
- `spanStartTimeShift=-1h`
- `spanEndTimeShift=1h`

Then the transformation is:
- `from=12:00` - `spanStartTimeShift=-1h` → `13:00`
- `to=13:00`     + `spanEndTimeShift=1h` → `14:00` 

Hope this helps, we will clarify the documentation ASAP. @knylander-grafana may I ask you a bit of help here?

**Comment by knylander-grafana** [comment]
We can update the doc pretty eaisly. Thank you for the clear explanation.

**Comment by knylander-grafana** [comment]
To correct: move the - to span start time. 
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'

**Comment by cancub** [comment]
I might be misunderstanding, but I believe we need to remove the `-` entirely from the docs.

This
```
traceQuery:
  timeShiftEnabled: true
  spanStartTimeShift: '-1h'
  spanEndTimeShift: '1h'
```

Will result in the start time being shifted 1 hour into the future.
