### ISSUE TITLE
[BUG] When using a snapshot stats are always for the full snapshot range and not for the selected time range

### ISSUE THREAD

**Issue by PiR43** [grafana/grafana#9606]
Please include this information:

- What Grafana version are you using? Grafana v4.3.2 (commit: ed4d170)
- What datasource are you using? Snapshot 
- What OS are you running grafana on? Docker
- What was the expected result?
The stats (min, max, avg) should change acording to the choose time range
- What happened instead?
 The stats are always the same and corespond to the full snapshot time range

![fullrange](https://user-images.githubusercontent.com/3668638/31840191-884bdcd0-b5e4-11e7-95bf-a267e7925fa8.png)
![last24h](https://user-images.githubusercontent.com/3668638/31840202-8e514868-b5e4-11e7-82f5-49025fa72268.png)

**Comment by torkelo** [comment]
snapshots only capture the visible data at the time. and the legend will show the stats for the timerange at the time of the snapshot
