### ISSUE TITLE
[bug] alert error couldn't find datasource while there is data on the graph

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9607]
Please include this information:
- What Grafana version are you using?
4.4.3
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 6

Some of the alerts show error messages: `couldn't find datasource` while there is data on the graph, what could be wrong?

<img width="445" alt="screen shot 2017-10-20 at 2 11 42 pm" src="https://user-images.githubusercontent.com/2936715/31842101-62c78858-b5a1-11e7-92a8-dc2162e598e3.png">

**Comment by torkelo** [comment]
Maybe your using a template variable for data source? Or you renamed or deleted the datasource? 

Try removing the alert rule (Save dashboard), then re-add the alert rule and save dashboard again
