### ISSUE TITLE
Auto login to grafana by posting username and password to login page

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#9608]
We want to integrate some form of SSO between Grafana and our app. Since the generic OAuth has a bug and not working, I am exploring alternative ways to get a user signed in. Is there a way we can post to the login page the username and password and get the login page to authenticate the user?
I can see the login is performed by an ajax call. I could not find a way to post credentials to the login page.

**Comment by torkelo** [comment]
That wont work as it would have to be done from the Grafana domain. 

If OAuth does not work for you you can use Auth proxy (put a proxy infront of Grafana that add uername headers that grafana will trust) 

http://docs.grafana.org/tutorials/authproxy/#grafana-authproxy
